Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psquota.c File Reference
psquota.c File Reference
#include "psp.h"
Macros
#define PSMINGIVEBACK ((MMPAGED_QUOTA_INCREASE > MMNONPAGED_QUOTA_INCREASE)?MMNONPAGED_QUOTA_INCREASE:MMPAGED_QUOTA_INCREASE)
Functions
VOID PsChargePoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
NTSTATUS PsChargeProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
NTSTATUS PsChargeProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
NTSTATUS PsChargeProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
NTSTATUS PsChargeProcessPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
NTSTATUS PsChargeProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
PEPROCESS_QUOTA_BLOCK PsChargeSharedPoolQuota (IN PEPROCESS Process, IN SIZE_T PagedAmount, IN SIZE_T NonPagedAmount)
VOID PsInitializeQuotaSystem (VOID)
NTSTATUS FORCEINLINE PspChargeQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
VOID PspDereferenceQuota (IN PEPROCESS Process)
VOID PspDereferenceQuotaBlock (IN PEPROCESS_QUOTA_BLOCK QuotaBlock)
BOOLEAN PspExpandQuota (IN PS_QUOTA_TYPE QuotaType, IN PEPROCESS_QUOTA_ENTRY QE, IN SIZE_T Usage, IN SIZE_T Amount, OUT SIZE_T *pLimit)
VOID PspGivebackQuota (IN PS_QUOTA_TYPE QuotaType, IN PEPROCESS_QUOTA_ENTRY QE)
VOID PspInheritQuota (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess)
VOID PspInsertQuotaBlock (IN PEPROCESS_QUOTA_BLOCK QuotaBlock)
SIZE_T FORCEINLINE PspInterlockedAddQuota (IN PSIZE_T pQuota, IN SIZE_T Amount)
SIZE_T FORCEINLINE PspInterlockedCompareExchangeQuota (IN PSIZE_T pQuota, IN SIZE_T NewQuota, IN SIZE_T OldQuota)
SIZE_T FORCEINLINE PspInterlockedExchangeQuota (IN PSIZE_T pQuota, IN SIZE_T NewQuota)
VOID FORCEINLINE PspInterlockedMaxQuota (IN PSIZE_T pQuota, IN SIZE_T NewQuota)
SIZE_T FORCEINLINE PspInterlockedSubtractQuota (IN PSIZE_T pUsage, IN SIZE_T Amount)
SIZE_T PspReleaseReturnedQuota (IN PS_QUOTA_TYPE QuotaType)
VOID FORCEINLINE PspReturnQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
VOID PsReturnPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
VOID PsReturnProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
VOID PsReturnProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
VOID PsReturnProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
VOID PsReturnProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
VOID PsReturnSharedPoolQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN SIZE_T PagedAmount, IN SIZE_T NonPagedAmount)
Variables
LIST_ENTRY PspQuotaBlockList
static const NTSTATUS PspQuotaStatus [PsQuotaTypes]
Macro Definition Documentation
#define PSMINGIVEBACK ((MMPAGED_QUOTA_INCREASE > MMNONPAGED_QUOTA_INCREASE)?MMNONPAGED_QUOTA_INCREASE:MMPAGED_QUOTA_INCREASE)
Referenced by PspReturnQuota().
Function Documentation
VOID PsChargePoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
Definition at line 857 of file psquota.c.
References ExRaiseStatus(), NT_SUCCESS, PsChargeProcessPoolQuota(), and Status.
Referenced by FsRtlCancelNotify(), and FsRtlNotifyFilterReportChange().
NTSTATUS PsChargeProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1109 of file psquota.c.
References PsInitialSystemProcess, PsNonPagedPool, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by ExEnableHandleTracing(), MiCloneProcessAddressSpace(), MiInsertVadCharges(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtSetInformationProcess(), PspSetLdtInformation(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
NTSTATUS PsChargeProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1168 of file psquota.c.
References PsInitialSystemProcess, PsPagedPool, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by ExpAllocateHandleTable(), ExpAllocateTablePagedPool(), ExpAllocateTablePagedPoolNoZero(), MiCloneProcessAddressSpace(), and MiInsertVadCharges().
NTSTATUS PsChargeProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
Definition at line 1227 of file psquota.c.
References PsInitialSystemProcess, PsPageFile, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by MiInsertVadCharges(), MiSetPageModified(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
NTSTATUS PsChargeProcessPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
Definition at line 898 of file psquota.c.
References ASSERT, NonPagedPool, PagedPool, ProcessObject, PsInitialSystemProcess, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by PsChargePoolQuota().
NTSTATUS PsChargeProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
Definition at line 1041 of file psquota.c.
References ASSERT, ProcessObject, PsInitialSystemProcess, PspChargeQuota(), and STATUS_SUCCESS.
PEPROCESS_QUOTA_BLOCK PsChargeSharedPoolQuota (IN PEPROCESS Process, IN SIZE_T PagedAmount, IN SIZE_T NonPagedAmount)
Definition at line 744 of file psquota.c.
References ASSERT, InterlockedIncrement, NT_SUCCESS, NULL, ProcessObject, PsInitialSystemProcess, PsNonPagedPool, PsPagedPool, PspChargeQuota(), PspReturnQuota(), _EPROCESS_QUOTA_BLOCK::ReferenceCount, and Status.
Referenced by ObpChargeQuotaForObject(), and RtlpAllocateAtom().
VOID PsInitializeQuotaSystem (VOID)
Definition at line 37 of file psquota.c.
References InitializeListHead(), KeInitializeSpinLock(), _EPROCESS_QUOTA_ENTRY::Limit, _EPROCESS_QUOTA_BLOCK::ProcessCount, PsGetCurrentProcess(), PsNonPagedPool, PsPagedPool, PsPageFile, PspDefaultQuotaBlock, PspQuotaLock, _EPROCESS::QuotaBlock, _EPROCESS_QUOTA_BLOCK::QuotaEntry, and _EPROCESS_QUOTA_BLOCK::ReferenceCount.
Referenced by ObInitSystem().
NTSTATUS FORCEINLINE PspChargeQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
Definition at line 461 of file psquota.c.
References KeMemoryBarrier(), _EPROCESS_QUOTA_ENTRY::Limit, NULL, _EPROCESS_QUOTA_ENTRY::Peak, PsPageFile, PspExpandQuota(), PspInterlockedAddQuota(), PspInterlockedCompareExchangeQuota(), PspInterlockedExchangeQuota(), PspInterlockedMaxQuota(), PspQuotaStatus, ReadForWriteAccess, _EPROCESS_QUOTA_ENTRY::Return, STATUS_SUCCESS, and _EPROCESS_QUOTA_ENTRY::Usage.
Referenced by PsChargeProcessNonPagedPoolQuota(), PsChargeProcessPagedPoolQuota(), PsChargeProcessPageFileQuota(), PsChargeProcessPoolQuota(), PsChargeProcessQuota(), and PsChargeSharedPoolQuota().
VOID PspDereferenceQuota (IN PEPROCESS Process)
Definition at line 1006 of file psquota.c.
References ASSERT, InterlockedDecrement, _EPROCESS_QUOTA_BLOCK::ProcessCount, PsNonPagedPool, PsPagedPool, PsPageFile, and PspDereferenceQuotaBlock().
Referenced by PspProcessDelete().
VOID PspDereferenceQuotaBlock (IN PEPROCESS_QUOTA_BLOCK QuotaBlock)
Definition at line 97 of file psquota.c.
References ExAcquireSpinLock, ExFreePool(), ExReleaseSpinLock, InterlockedDecrement, MmReturnPoolQuota(), PsNonPagedPool, PsPagedPool, PspQuotaLock, and RemoveEntryList().
Referenced by PspDereferenceQuota(), and PsReturnSharedPoolQuota().
BOOLEAN PspExpandQuota (IN PS_QUOTA_TYPE QuotaType, IN PEPROCESS_QUOTA_ENTRY QE, IN SIZE_T Usage, IN SIZE_T Amount, OUT SIZE_T * pLimit)
Definition at line 381 of file psquota.c.
References ExAcquireSpinLock, ExReleaseSpinLock, FALSE, MmRaisePoolQuota(), PsNonPagedPool, PspDefaultNonPagedLimit, PspDefaultPagedLimit, PspInterlockedAddQuota(), PspQuotaLock, PspReleaseReturnedQuota(), and TRUE.
Referenced by PspChargeQuota().
VOID PspGivebackQuota (IN PS_QUOTA_TYPE QuotaType, IN PEPROCESS_QUOTA_ENTRY QE)
Definition at line 589 of file psquota.c.
References ExAcquireSpinLock, ExReleaseSpinLock, MmReturnPoolQuota(), PspInterlockedExchangeQuota(), and PspQuotaLock.
Referenced by PspReturnQuota().
VOID PspInheritQuota (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess)
Definition at line 987 of file psquota.c.
References InterlockedIncrement, _EPROCESS_QUOTA_BLOCK::ProcessCount, PspDefaultQuotaBlock, and _EPROCESS_QUOTA_BLOCK::ReferenceCount.
Referenced by PspCreateProcess().
VOID PspInsertQuotaBlock (IN PEPROCESS_QUOTA_BLOCK QuotaBlock)
Definition at line 70 of file psquota.c.
References ExAcquireSpinLock, ExReleaseSpinLock, InsertTailList(), and PspQuotaLock.
Referenced by PspSetQuotaLimits().
SIZE_T FORCEINLINE PspInterlockedAddQuota (IN PSIZE_T pQuota, IN SIZE_T Amount)
Definition at line 321 of file psquota.c.
References InterlockedExchangeAdd().
Referenced by PspChargeQuota(), PspExpandQuota(), and PspReturnQuota().
SIZE_T FORCEINLINE PspInterlockedCompareExchangeQuota (IN PSIZE_T pQuota, IN SIZE_T NewQuota, IN SIZE_T OldQuota)
Definition at line 176 of file psquota.c.
References InterlockedCompareExchange(), and InterlockedCompareExchange64.
Referenced by PspChargeQuota(), PspInterlockedMaxQuota(), PspReleaseReturnedQuota(), and PspReturnQuota().
SIZE_T FORCEINLINE PspInterlockedExchangeQuota (IN PSIZE_T pQuota, IN SIZE_T NewQuota)
Definition at line 146 of file psquota.c.
References InterlockedExchange().
Referenced by PspChargeQuota(), PspGivebackQuota(), and PspReleaseReturnedQuota().
VOID FORCEINLINE PspInterlockedMaxQuota (IN PSIZE_T pQuota, IN SIZE_T NewQuota)
Definition at line 280 of file psquota.c.
References PspInterlockedCompareExchangeQuota().
Referenced by PspChargeQuota().
SIZE_T FORCEINLINE PspInterlockedSubtractQuota (IN PSIZE_T pUsage, IN SIZE_T Amount)
Definition at line 351 of file psquota.c.
References InterlockedExchangeAdd().
Referenced by PspReturnQuota().
SIZE_T PspReleaseReturnedQuota (IN PS_QUOTA_TYPE QuotaType)
Definition at line 207 of file psquota.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, _EPROCESS_QUOTA_ENTRY::Limit, MmReturnPoolQuota(), _EPROCESS_QUOTA_BLOCK::ProcessCount, PspInterlockedCompareExchangeQuota(), PspInterlockedExchangeQuota(), _EPROCESS_QUOTA_BLOCK::QuotaEntry, _EPROCESS_QUOTA_ENTRY::Return, and _EPROCESS_QUOTA_ENTRY::Usage.
Referenced by PspExpandQuota().
VOID FORCEINLINE PspReturnQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
Definition at line 626 of file psquota.c.
References ASSERT, _EPROCESS_QUOTA_ENTRY::Limit, MMNONPAGED_QUOTA_INCREASE, MMPAGED_QUOTA_INCREASE, NULL, PSMINGIVEBACK, PsPagedPool, PsPageFile, PspDefaultQuotaBlock, PspDoingGiveBacks, PspGivebackQuota(), PspInterlockedAddQuota(), PspInterlockedCompareExchangeQuota(), PspInterlockedSubtractQuota(), ReadForWriteAccess, _EPROCESS_QUOTA_ENTRY::Return, and _EPROCESS_QUOTA_ENTRY::Usage.
Referenced by PsChargeSharedPoolQuota(), PsReturnPoolQuota(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), PsReturnProcessPageFileQuota(), PsReturnProcessQuota(), and PsReturnSharedPoolQuota().
VOID PsReturnPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
Definition at line 943 of file psquota.c.
References ASSERT, NonPagedPool, PagedPool, ProcessObject, PsInitialSystemProcess, and PspReturnQuota().
Referenced by ExFreePoolWithTag(), and ExReturnPoolQuota().
VOID PsReturnProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1138 of file psquota.c.
References PsInitialSystemProcess, PsNonPagedPool, and PspReturnQuota().
Referenced by ExDereferenceHandleDebugInfo(), ExEnableHandleTracing(), MiCleanPhysicalProcessPages(), MiCloneProcessAddressSpace(), MiDecrementCloneBlockReference(), MiInsertVadCharges(), MiPhysicalViewRemover(), MiRemoveVadCharges(), NtAllocateVirtualMemory(), NtSetInformationProcess(), PspDeleteLdt(), PspDeleteVdmObjects(), PspProcessDelete(), PspSetLdtInformation(), PspSetLdtSize(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
VOID PsReturnProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1197 of file psquota.c.
References PsInitialSystemProcess, PsPagedPool, and PspReturnQuota().
Referenced by ExpAllocateHandleTable(), ExpFreeHandleTable(), ExpFreeTablePagedPool(), FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifyCompleteIrp(), FsRtlNotifyFilterReportChange(), MiCloneProcessAddressSpace(), MiDecrementCloneBlockReference(), MiInsertVadCharges(), MiRemoveVadCharges(), and PspDeleteVdmObjects().
VOID PsReturnProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
Definition at line 1256 of file psquota.c.
References PsInitialSystemProcess, PsPageFile, and PspReturnQuota().
Referenced by MiInsertVadCharges(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MiSetPageModified(), MiSetProtectionOnSection(), MmCleanProcessAddressSpace(), NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
VOID PsReturnProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
Definition at line 1075 of file psquota.c.
References ASSERT, ProcessObject, PsInitialSystemProcess, and PspReturnQuota().
VOID PsReturnSharedPoolQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN SIZE_T PagedAmount, IN SIZE_T NonPagedAmount)
Definition at line 809 of file psquota.c.
References NULL, PsNonPagedPool, PsPagedPool, PspDereferenceQuotaBlock(), and PspReturnQuota().
Referenced by ObpFreeObject(), and RtlpFreeAtom().
Variable Documentation
LIST_ENTRY PspQuotaBlockList
Definition at line 25 of file psquota.c.
const NTSTATUS PspQuotaStatus[PsQuotaTypes] static
Initial value:
= {STATUS_QUOTA_EXCEEDED,
                                                      STATUS_QUOTA_EXCEEDED,
                                                      STATUS_PAGEFILE_QUOTA_EXCEEDED}
Definition at line 274 of file psquota.c.
Referenced by PspChargeQuota().