Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmsavres.c File Reference
cmsavres.c File Reference
#include "cmp.h"
Macros
#define CM_SAVE_MERGED_HIGH_HIVE 2
#define CM_SAVE_MERGED_LOW_HIVE 4
#define CM_SAVE_MERGED_TMP_HIVE 1
#define CM_SAVEKEYBUFSIZE 0x10000
Functions
NTSTATUS CmDumpKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle)
PCMHIVE CmpCreateTemporaryHive (IN HANDLE FileHandle)
VOID CmpDestroyTemporaryHive (PCMHIVE CmHive)
NTSTATUS CmpLoadHiveVolatile (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle)
BOOLEAN CmpMergeKeyValues (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PCM_KEY_NODE SourceKeyNode, PHHIVE TargetHive, HCELL_INDEX TargetKeyCell, PCM_KEY_NODE TargetKeyNode)
NTSTATUS CmpOverwriteHive (PCMHIVE CmHive, PCMHIVE NewHive, HCELL_INDEX LinkCell)
NTSTATUS CmpRefreshHive (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock)
ULONG CmpRefreshWorkerRoutine (PCM_KEY_CONTROL_BLOCK Current, PVOID Context1, PVOID Context2)
NTSTATUS CmpSaveKeyByFileCopy (PCMHIVE Hive, HANDLE FileHandle)
BOOLEAN CmpShiftAllCells (PHHIVE NewHive, PCMHIVE OldHive)
BOOLEAN CmpShiftAllCells2 (PHHIVE Hive, PCMHIVE OldHive, HCELL_INDEX Cell, HCELL_INDEX ParentCell)
NTSTATUS CmpShiftHiveFreeBins (PCMHIVE CmHive, PCMHIVE *NewHive)
VOID CmpShiftIndex (PHHIVE Hive, PCM_KEY_INDEX Index)
VOID CmpShiftKey (PHHIVE Hive, PCMHIVE OldHive, HCELL_INDEX Cell, HCELL_INDEX ParentCell)
VOID CmpShiftSecurityCells (PHHIVE Hive)
VOID CmpShiftValueList (PHHIVE Hive, HCELL_INDEX ValueList, ULONG Count)
VOID CmpSwitchStorageAndRebuildMappings (PCMHIVE OldCmHive, PCMHIVE NewCmHive)
NTSTATUS CmRestoreKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG Flags)
NTSTATUS CmSaveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG HiveVersion)
NTSTATUS CmSaveMergedKeys (IN PCM_KEY_CONTROL_BLOCK HighPrecedenceKcb, IN PCM_KEY_CONTROL_BLOCK LowPrecedenceKcb, IN HANDLE FileHandle)
Variables
SIZE_T CmpGlobalQuotaUsed
PCMHIVE CmpMasterHive
BOOLEAN CmpProfileLoaded
PUCHAR CmpStashBuffer
BOOLEAN HvShutdownComplete
Macro Definition Documentation
#define CM_SAVE_MERGED_HIGH_HIVE 2
Definition at line 1352 of file cmsavres.c.
Referenced by CmSaveMergedKeys().
#define CM_SAVE_MERGED_LOW_HIVE 4
Definition at line 1353 of file cmsavres.c.
Referenced by CmSaveMergedKeys().
#define CM_SAVE_MERGED_TMP_HIVE 1
Definition at line 1351 of file cmsavres.c.
Referenced by CmSaveMergedKeys().
#define CM_SAVEKEYBUFSIZE 0x10000
Definition at line 25 of file cmsavres.c.
Referenced by CmpSaveKeyByFileCopy().
Function Documentation
NTSTATUS CmDumpKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle)
Definition at line 1078 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpLockHiveFlusherExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, FALSE, _CMHIVE::FileHandles, HFILE_TYPE_EXTERNAL, Hive, _CMHIVE::Hive, HvShutdownComplete, HvWriteHive(), NULL, _HBASE_BLOCK::RootCell, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, and STATUS_REGISTRY_IO_FAILED.
Referenced by NtSaveKeyEx().
PCMHIVE CmpCreateTemporaryHive (IN HANDLE FileHandle)
Definition at line 1777 of file cmsavres.c.
References CM_PAGED_CODE, CmpInitializeHive(), HINIT_CREATE, HIVE_VOLATILE, NT_SUCCESS, NULL, Status, and UNREFERENCED_PARAMETER.
Referenced by CmpShiftHiveFreeBins(), CmSaveKey(), and CmSaveMergedKeys().
VOID CmpDestroyTemporaryHive (PCMHIVE CmHive)
Definition at line 1830 of file cmsavres.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_SAVRES, CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpLockHiveListExclusive, CmpRemoveEntryList, CmpUnJoinClassOfTrust, CmpUnlockHiveList, DPFLTR_CONFIG_ID, _CMHIVE::FlusherLock, _CMHIVE::Hive, _CMHIVE::HiveList, HvFreeHive(), NULL, and _CMHIVE::ViewLock.
Referenced by CmCompressKey(), CmpLoadHiveVolatile(), CmpShiftHiveFreeBins(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
NTSTATUS CmpLoadHiveVolatile (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle)
Definition at line 670 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, Cell, CM_CHECK_REGISTRY_CHECK_CLEAN, CM_PAGED_CODE, CmpAddToHiveFileList(), CmpConstructName(), CmpCopyCompressedName(), CmpCopyKeyPartial(), CmpCopyTree, CmpDestroyTemporaryHive(), CmpHKeyNameLen, CmpInitializeHive(), CmpLinkHiveToMaster(), CmpLockRegistryExclusive(), CmpProfileLoaded, CmpSetGlobalQuotaAllowed(), CmpUnlockRegistry(), ExAllocatePool, ExFreePool(), ExFreePoolWithTag, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HFILE_TYPE_PRIMARY, HINIT_CREATE, HINIT_FILE, Hive, _CMHIVE::Hive, HIVE_VOLATILE, HvGetCell, HvReleaseCell, IsHiveFrozen, KEY_COMP_NAME, _CELL_DATA::_u::KeyNode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NT_SUCCESS, NULL, PagedPool, PROTECTED_POOL, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyUnicodeString(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_TOO_LATE, TRUE, and _CELL_DATA::u.
Referenced by CmRestoreKey().
BOOLEAN CmpMergeKeyValues (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PCM_KEY_NODE SourceKeyNode, PHHIVE TargetHive, HCELL_INDEX TargetKeyCell, PCM_KEY_NODE TargetKeyNode)
Definition at line 1506 of file cmtrecpy.c.
References ASSERT, CmpAddValueToList(), CmpCopyValue(), CmpFindNameInList(), CmpInitializeValueNameString(), CmpSyncKeyValues(), _CHILD_LIST::Count, ExAllocatePool, ExFreePool(), FALSE, HCELL_NIL, HvGetCell, HvGetCellType, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CELL_DATA::_u::KeyList, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PagedPool, REG_MAX_KEY_VALUE_NAME_LENGTH, _HHIVE::ReleaseCellRoutine, TRUE, _CELL_DATA::u, and _CM_KEY_NODE::ValueList.
Referenced by CmpCopySyncTree2(), and CmSaveMergedKeys().
NTSTATUS CmpOverwriteHive (PCMHIVE CmHive, PCMHIVE NewHive, HCELL_INDEX LinkCell)
Definition at line 1880 of file cmsavres.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, CM_PAGED_CODE, CmpDestroyHiveViewList(), _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyVector, FALSE, _CMHIVE::FileHandles, _CMHIVE::FileObject, _CM_KEY_NODE::Flags, _HHIVE::Free, HFILE_TYPE_EXTERNAL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HSECTOR_SIZE, HvGetCell, HvMarkCellDirty(), HvpGrowLog2(), HvpWriteLog(), HvReleaseCell, HvWriteHive(), KEY_HIVE_ENTRY, KEY_NO_DELETE, _HHIVE::_DUAL::Length, _HHIVE::Log, NULL, _CM_KEY_NODE::Parent, _HBASE_BLOCK::RootCell, ROUND_UP, RtlClearAllBits(), RtlInitializeBitMap(), RtlSetAllBits(), RtlZeroMemory, _RTL_BITMAP::SizeOfBitMap, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_NO_MEMORY, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, _HHIVE::Storage, TRUE, and _HBASE_BLOCK::Type.
Referenced by CmCompressKey().
NTSTATUS CmpRefreshHive (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 951 of file cmsavres.c.
References ASSERT, CM_PAGED_CODE, CmpFlushNotify(), CmpLockRegistryExclusive(), CmpRefreshWorkerRoutine(), CmpSearchKeyControlBlockTree(), CmpUnlockRegistry(), CONTAINING_RECORD, _LIST_ENTRY::Flink, Hive, HIVE_NOLAZYFLUSH, HvRefreshHive(), IsHiveFrozen, KeGetPreviousMode, KEY_HIVE_ENTRY, _CM_NOTIFY_BLOCK::KeyBody, NULL, SeSinglePrivilegeCheck(), SeTcbPrivilege, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_TOO_LATE, STATUS_UNSUCCESSFUL, TRUE, and Volatile.
Referenced by CmRestoreKey().
ULONG CmpRefreshWorkerRoutine (PCM_KEY_CONTROL_BLOCK Current, PVOID Context1, PVOID Context2)
Definition at line 901 of file cmsavres.c.
References CM_PAGED_CODE, _CM_KEY_CONTROL_BLOCK::Delete, KCB_WORKER_CONTINUE, KCB_WORKER_DELETE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NULL, TRUE, and UNREFERENCED_PARAMETER.
Referenced by CmpRefreshHive().
NTSTATUS CmpSaveKeyByFileCopy (PCMHIVE Hive, HANDLE FileHandle)
Definition at line 1617 of file cmsavres.c.
References CM_PAGED_CODE, CM_SAVEKEYBUFSIZE, CmpFileFlush(), CmpFileRead(), CmpFileWrite(), CmpLockRegistryExclusive(), CmpStashBuffer, CmpUnlockRegistry(), CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _CMHIVE::FileHandles, CMP_OFFSET_ARRAY::FileOffset, HBLOCK_SIZE, HFILE_TYPE_EXTERNAL, HFILE_TYPE_PRIMARY, _HBASE_BLOCK::Length, LOCK_STASH_BUFFER, NULL, PagedPoolCacheAligned, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, and UNLOCK_STASH_BUFFER.
Referenced by CmSaveKey().
BOOLEAN CmpShiftAllCells (PHHIVE NewHive, PCMHIVE OldHive)
Definition at line 2256 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, _CM_KEY_SECURITY_CACHE_ENTRY::Cell, _CMHIVE::CellRemapArray, CM_PAGED_CODE, CmpShiftAllCells2(), CmpShiftSecurityCells(), HCELL_NIL, _CMHIVE::Hive, HvGetCellType, HvShiftCell(), _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, _CM_CELL_REMAP_BLOCK::NewCell, NULL, _CM_CELL_REMAP_BLOCK::OldCell, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, _CMHIVE::SecurityCache, _CMHIVE::SecurityCount, _HHIVE::_DUAL::SmallDir, Stable, _HHIVE::Storage, TRUE, and Volatile.
Referenced by CmpShiftHiveFreeBins().
BOOLEAN CmpShiftAllCells2 (PHHIVE Hive, PCMHIVE OldHive, HCELL_INDEX Cell, HCELL_INDEX ParentCell)
Definition at line 2320 of file cmsavres.c.
References ASSERT, Cell, CMP_CHECK_REGISTRY_STACK_ENTRY::Cell, CMP_CHECK_REGISTRY_STACK_ENTRY::CellChecked, CMP_CHECK_REGISTRY_STACK_ENTRY::ChildIndex, CMP_MAX_REGISTRY_DEPTH, CmpFindSubKeyByNumber(), CmpShiftIndex(), CmpShiftKey(), ExAllocatePool, ExFreePool(), FALSE, HCELL_NIL, HvGetCell, HvGetCellType, HvShiftCell(), Index, InsertTailList(), _CM_KNODE_REMAP_BLOCK::KeyNode, _CMHIVE::KnodeConvertListHead, _CM_KNODE_REMAP_BLOCK::NewParent, NULL, PagedPool, CMP_CHECK_REGISTRY_STACK_ENTRY::ParentCell, _HHIVE::ReleaseCellRoutine, _CM_KNODE_REMAP_BLOCK::RemapList, Stable, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, and Volatile.
Referenced by CmpShiftAllCells().
NTSTATUS CmpShiftHiveFreeBins (PCMHIVE CmHive, PCMHIVE * NewHive)
Definition at line 2130 of file cmsavres.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, CM_PAGED_CODE, CmpCreateTemporaryHive(), CmpDestroyTemporaryHive(), CmpShiftAllCells(), _HHIVE::DirtyCount, _CMHIVE::FileHandles, _HHIVE::_DUAL::FreeBins, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvCloneHive(), HvShiftCell(), HvShrinkHive(), HvSyncHive(), IsListEmpty, _HBASE_BLOCK::Minor, NT_SUCCESS, NULL, _HBASE_BLOCK::RootCell, Stable, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _HHIVE::Storage, and _HHIVE::Version.
Referenced by CmCompressKey().
VOID CmpShiftIndex (PHHIVE Hive, PCM_KEY_INDEX Index)
Definition at line 2454 of file cmsavres.c.
References ASSERT, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, _CM_KEY_INDEX::Count, HvGetCell, HvShiftCell(), _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NULL, and _CM_KEY_INDEX::Signature.
Referenced by CmpShiftAllCells2().
VOID CmpShiftKey (PHHIVE Hive, PCMHIVE OldHive, HCELL_INDEX Cell, HCELL_INDEX ParentCell)
Definition at line 2500 of file cmsavres.c.
References ASSERT, _CM_KEY_NODE::Class, CmpShiftValueList(), CONTAINING_RECORD, _CHILD_LIST::Count, _LIST_ENTRY::Flink, HCELL_NIL, HvGetCell, HvShiftCell(), _CMHIVE::KcbConvertListHead, _CHILD_LIST::List, _CM_KCB_REMAP_BLOCK::NewCellIndex, NULL, _CM_KCB_REMAP_BLOCK::OldCellIndex, _CM_KEY_NODE::Parent, _CM_KCB_REMAP_BLOCK::RemapList, _CM_KEY_NODE::Security, _CM_KCB_REMAP_BLOCK::ValueCount, _CM_KEY_NODE::ValueList, and _CM_KCB_REMAP_BLOCK::ValueList.
Referenced by CmpShiftAllCells2().
VOID CmpShiftSecurityCells (PHHIVE Hive)
Definition at line 2616 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, _CM_KEY_SECURITY::Blink, _CM_KEY_SECURITY::Flink, HvGetCell, HvShiftCell(), NULL, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, and _CM_KEY_NODE::Security.
Referenced by CmpShiftAllCells().
VOID CmpShiftValueList (PHHIVE Hive, HCELL_INDEX ValueList, ULONG Count)
Definition at line 2567 of file cmsavres.c.
References ASSERT, Cell, CM_KEY_VALUE_SPECIAL_SIZE, CmpIsHKeyValueBig, Count, _CM_BIG_DATA::Count, _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, HCELL_NIL, HvGetCell, HvShiftCell(), _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyValue, List, _CM_BIG_DATA::List, NULL, TRUE, and _CELL_DATA::u.
Referenced by CmpShiftKey().
VOID CmpSwitchStorageAndRebuildMappings (PCMHIVE OldCmHive, PCMHIVE NewCmHive)
Definition at line 1963 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, _CM_KEY_SECURITY_CACHE_ENTRY::CachedSecurity, _CM_KEY_SECURITY_CACHE::Cell, _CM_KEY_SECURITY_CACHE_ENTRY::Cell, _CMHIVE::CellRemapArray, CM_KCB_KEY_NON_EXIST, CM_KCB_SYM_LINK_FOUND, CM_PAGED_CODE, CmpCleanUpKcbValueCache(), CmpSetUpKcbValueCache, CONTAINING_RECORD, _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyVector, _CM_KEY_CONTROL_BLOCK::ExtFlags, _CM_KEY_CONTROL_BLOCK::Flags, _LIST_ENTRY::Flink, _HHIVE::_DUAL::FreeBins, HCELL_NIL, _CMHIVE::Hive, HvGetCellType, InsertTailList(), IsListEmpty, _CMHIVE::KcbConvertListHead, KEY_PREDEF_HANDLE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KCB_REMAP_BLOCK::KeyControlBlock, _CM_KNODE_REMAP_BLOCK::KeyNode, _CMHIVE::KnodeConvertListHead, _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, _HHIVE::LogSize, _CMHIVE::LRUViewListHead, _HHIVE::_DUAL::Map, _CMHIVE::MappedViews, _CM_CELL_REMAP_BLOCK::NewCell, _CM_KCB_REMAP_BLOCK::NewCellIndex, _CM_KNODE_REMAP_BLOCK::NewParent, NULL, _CM_CELL_REMAP_BLOCK::OldCell, _CM_KCB_REMAP_BLOCK::OldCellIndex, _CM_KEY_NODE::Parent, _CMHIVE::PinnedViews, _CMHIVE::PinViewListHead, _CM_KCB_REMAP_BLOCK::RemapList, _CM_KNODE_REMAP_BLOCK::RemapList, RemoveHeadList(), _HBASE_BLOCK::RootCell, RtlCopyMemory, _CMHIVE::SecurityCache, _CMHIVE::SecurityCount, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HHIVE::_DUAL::SmallDir, Stable, _HHIVE::Storage, _CMHIVE::UseCount, _CM_KCB_REMAP_BLOCK::ValueCount, and _CM_KCB_REMAP_BLOCK::ValueList.
Referenced by CmCompressKey().
NTSTATUS CmRestoreKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG Flags)
Definition at line 138 of file cmsavres.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, Cell, _CM_INDEX::Cell, _CM_KEY_NODE::ChildHiveReference, CM_CHECK_REGISTRY_CHECK_CLEAN, CM_KCB_INVALID_CACHED_INFO, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, CmKdPrintEx, CML_SAVRES, CmpAssignSecurityToKcb(), CmpCleanUpKcbValueCache(), CmpCleanUpSubKeyInfo(), CmpCopyKeyPartial(), CmpCopyTree, CmpDeleteTree(), CmpDestroyTemporaryHive(), CmpFreeKeyByCell(), CmpInitializeHive(), CmpLoadHiveVolatile(), CmpLockRegistryExclusive(), CmpProfileLoaded, CmpRefreshHive(), CmpReportNotify(), CmpSearchForOpenSubKeys(), CmpSetGlobalQuotaAllowed(), CmpSetUpKcbValueCache, CmpUnlockRegistry(), CONTAINING_RECORD, _CHILD_LIST::Count, _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, DCmCheckRegistry, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _CM_KEY_NODE::Flags, HCELL_NIL, HFILE_TYPE_PRIMARY, HINIT_FILE, Hive, _CMHIVE::Hive, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReallocateCell(), HvReleaseCell, IsHiveFrozen, KEY_COMP_NAME, KEY_HIVE_ENTRY, _CM_KEY_REFERENCE::KeyCell, _CELL_DATA::_u::KeyIndex, _CELL_DATA::_u::KeyNode, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, REG_FORCE_RESTORE, REG_NOTIFY_CHANGE_NAME, REG_REFRESH_HIVE, REG_WHOLE_HIVE_VOLATILE, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, RtlCopyMemory, SearchAndDeref, SearchIfExist, _CM_KEY_NODE::Security, _CM_KEY_INDEX::Signature, STATUS_ACCESS_DENIED, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, STATUS_TOO_LATE, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CELL_DATA::u, and _CM_KEY_NODE::ValueList.
Referenced by NtRestoreKey().
NTSTATUS CmSaveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG HiveVersion)
Definition at line 1164 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_SAVRES, CmpCopyKeyPartial(), CmpCopyTree, CmpCreateTemporaryHive(), CmpDestroyTemporaryHive(), CmpLockHiveFlusherExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpLockRegistryExclusive(), CmpSaveKeyByFileCopy(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CONTAINING_RECORD, DCmCheckRegistry, _HHIVE::DirtyCount, DPFLTR_CONFIG_ID, ENTER_FLUSH_MODE, EXIT_FLUSH_MODE, FALSE, _CMHIVE::FileHandles, HCELL_NIL, HFILE_TYPE_EXTERNAL, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvWriteHive(), _HBASE_BLOCK::Minor, NULL, _HBASE_BLOCK::RootCell, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, TRUE, and _HHIVE::Version.
Referenced by NtSaveKey(), and NtSaveKeyEx().
NTSTATUS CmSaveMergedKeys (IN PCM_KEY_CONTROL_BLOCK HighPrecedenceKcb, IN PCM_KEY_CONTROL_BLOCK LowPrecedenceKcb, IN HANDLE FileHandle)
Definition at line 1356 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, CM_PAGED_CODE, CM_SAVE_MERGED_HIGH_HIVE, CM_SAVE_MERGED_LOW_HIVE, CM_SAVE_MERGED_TMP_HIVE, CmKdPrintEx, CML_SAVRES, CmpCopyKeyPartial(), CmpCopyTree, CmpCreateTemporaryHive(), CmpDestroyTemporaryHive(), CmpLockHiveFlusherExclusive, CmpLockRegistry(), CmpLockTwoHashEntriesShared(), CmpMergeKeyValues(), CmpMergeTrees, CmpUnlockHiveFlusher, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CONTAINING_RECORD, DCmCheckRegistry, _HHIVE::DirtyCount, DPFLTR_CONFIG_ID, ENTER_FLUSH_MODE, EXIT_FLUSH_MODE, FALSE, _CMHIVE::FileHandles, HCELL_NIL, HFILE_TYPE_EXTERNAL, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvGetCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), HvWriteHive(), NULL, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, and TRUE.
Referenced by NtSaveMergedKeys().
Variable Documentation
SIZE_T CmpGlobalQuotaUsed
Definition at line 57 of file cmdat2.c.
PCMHIVE CmpMasterHive
Definition at line 305 of file cmdat.c.
BOOLEAN CmpProfileLoaded
Definition at line 62 of file cmdat2.c.
Referenced by CmpLoadHiveVolatile(), and CmRestoreKey().
PUCHAR CmpStashBuffer
Definition at line 64 of file cmdat2.c.
Referenced by CmpSaveKeyByFileCopy().
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by CmDumpKey().