Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/initkr.c File Reference
initkr.c File Reference
#include "ki.h"
#include <kddll.h>
Data Structures
struct _KI_INTINIT_REC
Macros
#define KiInitializeIdtEntry(Entry, Address, Level, Index)
Typedefs
typedef VOID(* KI_INTERRUPT_HANDLER) (VOID)
typedef struct _KI_INTINIT_REC KI_INTINIT_REC
typedef struct _KI_INTINIT_REC * PKI_INTINIT_REC
Functions
VOID KeCompactServiceTable (IN PVOID Table, IN ULONG Limit, IN BOOLEAN Win32)
ULONG KiFatalFilter (IN ULONG Code, IN PEXCEPTION_POINTERS Pointers)
VOID KiInitializeBootStructures (PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID KiInitializeKernel (IN PKPROCESS Process, IN PKTHREAD Thread, IN PVOID IdleStack, IN PKPRCB Prcb, IN CCHAR Number, PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN KiInitMachineDependent (VOID)
VOID KiSetCacheInformation (VOID)
VOID KiSetCacheInformationAmd (VOID)
VOID KiSetCacheInformationIntel (VOID)
VOID KiSetCpuVendor (VOID)
VOID KiSetFeatureBits (IN PKPRCB Prcb)
VOID KiSetProcessorType (VOID)
Variables
ULONG KeLastBranchMSR = 0
ULONG KiApicMask
UCHAR KiCFlushSize = 0
KI_INTINIT_REC KiInterruptInitTable []
ULONG KiLogicalProcessors
ULONG KiMxCsrMask = 0xFFBF
ULONG KiPhysicalProcessors
UCHAR KiPrefetchRetry = 0x80
KIRQL KiProfileIrql = PROFILE_LEVEL
UNEXPECTED_INTERRUPT KxUnexpectedInterrupt0 [256]
Macro Definition Documentation
#define KiInitializeIdtEntry (Entry, Address, Level, Index)
Value:
(Entry)->OffsetLow = (USHORT)((ULONG64)(Address));                      \
    (Entry)->Selector = KGDT64_R0_CODE;                                     \
    (Entry)->IstIndex = Index;                                              \
    (Entry)->Type = 0xe;                                                    \
    (Entry)->Dpl = (Level);                                                 \
    (Entry)->Present = 1;                                                   \
    (Entry)->OffsetMiddle = (USHORT)((ULONG64)(Address) >> 16);             \
    (Entry)->OffsetHigh = (ULONG)((ULONG64)(Address) >> 32)                 \
Definition at line 148 of file initkr.c.
Referenced by KiInitializeBootStructures().
Typedef Documentation
typedef VOID(* KI_INTERRUPT_HANDLER) (VOID)
Definition at line 75 of file initkr.c.
typedef struct _KI_INTINIT_REC KI_INTINIT_REC
typedef struct _KI_INTINIT_REC * PKI_INTINIT_REC
Function Documentation
VOID KeCompactServiceTable (IN PVOID Table, IN ULONG Limit, IN BOOLEAN Win32)
Definition at line 209 of file initkr.c.
References Index, memcpy(), and TRUE.
Referenced by KiInitializeKernel(), and MmLoadSystemImage().
ULONG KiFatalFilter (IN ULONG Code, IN PEXCEPTION_POINTERS Pointers)
Definition at line 1012 of file initkr.c.
References KeBugCheckEx(), and PHASE0_EXCEPTION.
Referenced by KiInitializeKernel().
VOID KiInitializeBootStructures (PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 750 of file initkr.c.
References AFFINITY_MASK, _KAPC_STATE::ApcListHead, _KTHREAD::ApcState, _KPRCB::BuildType, _KPRCB::CurrentThread, _KPRCB::DpcStack, _KI_INTINIT_REC::Dpl, ExInitPoolLookasidePointers(), FALSE, HalInitializeProcessor(), _KI_INTINIT_REC::Handler, _KPRCB::IdleThread, Index, InitializeListHead(), _KI_INTINIT_REC::IstIndex, KeActiveProcessors, KeFindFirstSetLeftMember(), KeGetCurrentPrcb(), KeGetPcr(), KeNumberProcessors, KernelMode, _LOADER_PARAMETER_BLOCK::KernelStack, KiApicMask, KiComputeIopmOffset, KiInitializeIdtEntry, KiInitialProcess, KiInitialThread, KiInitSpinLocks(), KiInterruptInitTable, KiLogicalProcessors, KiPhysicalProcessors, KiProcessorBlock, KiSaveInitialProcessorControlState(), KiSecondaryClockInterrupt(), KiSetFeatureBits(), KiSystemCall32(), KiSystemCall64(), KiUnexpectedInterrupt(), _KPRCB::LogicalProcessorsPerPhysicalProcessor, _KPRCB::MajorVersion, _KPCR::MajorVersion, MAXIMUM_IDTVECTOR, _KPRCB::MinorVersion, _KPCR::MinorVersion, _KPRCB::NextThread, NULL, _KPRCB::Number, PCR_MAJOR_VERSION, PCR_MINOR_VERSION, _KPCR::Prcb, PRCB_BUILD_DEBUG, PRCB_BUILD_UNIPROCESSOR, PRCB_MAJOR_VERSION, PRCB_MINOR_VERSION, _LOADER_PARAMETER_BLOCK::Process, _KAPC_STATE::Process, _KPRCB::ProcessorState, PUNEXPECTED_INTERRUPT, RPL_MASK, RTL_SIZEOF_THROUGH_FIELD, _KPRCB::SetMember, _LOADER_PARAMETER_BLOCK::Thread, UNEXPECTED_INTERRUPT, and _KI_INTINIT_REC::Vector.
VOID KiInitializeKernel (IN PKPROCESS Process, IN PKTHREAD Thread, IN PVOID IdleStack, IN PKPRCB Prcb, IN CCHAR Number, PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 272 of file initkr.c.
References _enable(), AFFINITY_MASK, APC_LEVEL, CR4_DE, CR4_PSE, DISPATCH_LEVEL, except, ExpInitializeExecutive(), FALSE, HIGH_PRIORITY, Index, _KPRCB::InitialApicId, InitializeListHead(), KeBugCheckEx(), KeCompactServiceTable(), KeComputeReciprocal(), KeFeatureBits, KeFlushCurrentTb(), KeInitializeProcess(), KeInitializeSpinLock(), KeInitializeThread(), KeLowerIrql, KeMaximumIncrement, KeNodeBlock, KeNumberProcessors, KeProcessorArchitecture, KeProcessorLevel, KeProcessorRevision, KeRaiseIrql, KeRaiseIrqlToSynchLevel(), KeSetPriorityThread(), KF_3DNOW, KF_GLOBAL_32BIT_EXECUTE, KF_GLOBAL_32BIT_NOEXECUTE, KF_NOEXECUTE, KiAcquirePrcbLock(), KiAdjustDpcThreshold, KiApicMask, KiCFlushSize, KiFatalFilter(), KiFreezeExecutionLock, KiIdleSummary, KiInitSystem(), KiLogicalProcessors, KiMaximumDpcQueueDepth, KiMinimumDpcRate, KiMxCsrMask, KiNode0, KiNodeInit, KiPhysicalProcessors, KiProcessListHead, KiProcessorBlock, KiReleasePrcbLock(), KiServiceLimit, KiServiceTable, KiSetCacheInformation(), KiSetCpuVendor(), KiSetPageAttributesTable(), KiSetProcessorType(), KiTimeIncrementReciprocal, KiTimeIncrementShiftCount, _LOADER_PARAMETER_BLOCK::LoadOptions, LOW_REALTIME_PRIORITY, MAXCHAR, MAXIMUM_CCNUMA_NODES, MmPaeErrMask, MmPaeMask, MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED, _KPRCB::MultiThreadProcessorSet, _KPRCB::MultiThreadSetMaster, NOTHING, NULL, NX_SUPPORT_POLICY_ALWAYSOFF, NX_SUPPORT_POLICY_ALWAYSON, NX_SUPPORT_POLICY_OPTIN, NX_SUPPORT_POLICY_OPTOUT, PF_3DNOW_INSTRUCTIONS_AVAILABLE, PF_COMPARE_EXCHANGE_DOUBLE, PF_MMX_INSTRUCTIONS_AVAILABLE, PF_NX_ENABLED, PF_PAE_ENABLED, PF_RDTSC_INSTRUCTION_AVAILABLE, PF_XMMI64_INSTRUCTIONS_AVAILABLE, PF_XMMI_INSTRUCTIONS_AVAILABLE, PoInitializePrcb(), _LOADER_PARAMETER_BLOCK::Prcb, PROCESSOR_ARCHITECTURE_AMD64, RtlInitializeHistoryTable(), RtlZeroMemory, Running, SharedUserData, strstr(), and TRUE.
BOOLEAN KiInitMachineDependent (VOID)
Definition at line 1045 of file initkr.c.
Referenced by KeInitSystem().
VOID KiSetCacheInformation (VOID)
Definition at line 1102 of file initkr.c.
References _CACHE_DESCRIPTOR::Associativity, CACHE_FULLY_ASSOCIATIVE, CacheData, CacheUnified, CPU_AMD, CPU_INTEL, KeBugCheck(), KeGetCurrentPrcb(), KeGetPcr(), KeLargestCacheLine, KiSetCacheInformationAmd(), KiSetCacheInformationIntel(), _CACHE_DESCRIPTOR::Level, _CACHE_DESCRIPTOR::LineSize, _KPCR::SecondLevelCacheAssociativity, _KPCR::SecondLevelCacheSize, _CACHE_DESCRIPTOR::Size, _CACHE_DESCRIPTOR::Type, and UNSUPPORTED_PROCESSOR.
Referenced by KiInitializeKernel().
VOID KiSetCacheInformationAmd (VOID)
Definition at line 1205 of file initkr.c.
References _CACHE_DESCRIPTOR::Associativity, CACHE_FULLY_ASSOCIATIVE, CacheData, CacheInstruction, CacheUnified, Index, KeGetCurrentPrcb(), _CACHE_DESCRIPTOR::Level, _CACHE_DESCRIPTOR::LineSize, _CACHE_DESCRIPTOR::Size, and _CACHE_DESCRIPTOR::Type.
Referenced by KiSetCacheInformation().
VOID KiSetCacheInformationIntel (VOID)
Definition at line 1379 of file initkr.c.
References ASSERT, _CACHE_DESCRIPTOR::Associativity, CACHE_FULLY_ASSOCIATIVE, CacheData, CacheInstruction, CacheTrace, CacheUnified, FALSE, Index, KeGetCurrentPrcb(), _CACHE_DESCRIPTOR::Level, _CACHE_DESCRIPTOR::LineSize, RTL_NUMBER_OF, _CACHE_DESCRIPTOR::Size, and _CACHE_DESCRIPTOR::Type.
Referenced by KiSetCacheInformation().
VOID KiSetCpuVendor (VOID)
Definition at line 1493 of file initkr.c.
References CPU_AMD, CPU_INTEL, KeBugCheck(), KeGetCurrentPrcb(), RtlCopyMemory, strncmp(), UNSUPPORTED_PROCESSOR, and _KPRCB::VendorString.
Referenced by KiInitializeKernel().
VOID KiSetFeatureBits (IN PKPRCB Prcb)
Definition at line 1556 of file initkr.c.
References HF_DS, HF_REQUIRED, HF_SMT, KeBugCheckEx(), KeFeatureBits, KF_3DNOW, KF_DTS, KF_NOEXECUTE, KF_REQUIRED, UNSUPPORTED_PROCESSOR, XHF_3DNOW, XHF_FFXSR, XHF_NOEXECUTE, and XHF_SYSCALL.
Referenced by KiInitializeBootStructures().
VOID KiSetProcessorType (VOID)
Definition at line 1659 of file initkr.c.
References CPU_AMD, CPU_INTEL, _KPRCB::CpuID, _KPRCB::CpuStep, _KPRCB::CpuType, KeGetCurrentPrcb(), KiPrefetchRetry, _LARGE_INTEGER::QuadPart, TRUE, and _KPRCB::UpdateSignature.
Referenced by KiInitializeKernel().
Variable Documentation
ULONG KeLastBranchMSR = 0
Definition at line 49 of file initkr.c.
ULONG KiApicMask
Definition at line 41 of file initkr.c.
Referenced by KiInitializeBootStructures(), and KiInitializeKernel().
UCHAR KiCFlushSize = 0
Definition at line 34 of file initkr.c.
Referenced by KiInitializeKernel().
KI_INTINIT_REC KiInterruptInitTable[]
Initial value:
= {
    {0,  0, 0,             KiDivideErrorFault},
    {1,  0, 0,             KiDebugTrapOrFault},
    {2,  0, TSS_IST_NMI,   KiNmiInterrupt},
    {3,  3, 0,             KiBreakpointTrap},
    {4,  3, 0,             KiOverflowTrap},
    {5,  0, 0,             KiBoundFault},
    {6,  0, 0,             KiInvalidOpcodeFault},
    {7,  0, 0,             KiNpxNotAvailableFault},
    {8,  0, TSS_IST_PANIC, KiDoubleFaultAbort},
    {9,  0, 0,             KiNpxSegmentOverrunAbort},
    {10, 0, 0,             KiInvalidTssFault},
    {11, 0, 0,             KiSegmentNotPresentFault},
    {12, 0, 0,             KiStackFault},
    {13, 0, 0,             KiGeneralProtectionFault},
    {14, 0, 0,             KiPageFault},
    {16, 0, 0,             KiFloatingErrorFault},
    {17, 0, 0,             KiAlignmentFault},
    {18, 0, TSS_IST_MCA,   KiMcheckAbort},
    {19, 0, 0,             KiXmmException},
    {31, 0, 0,             KiApcInterrupt},
    {44, 3, 0,             KiRaiseAssertion},
    {45, 3, 0,             KiDebugServiceTrap},
    {47, 0, 0,             KiDpcInterrupt},
    {225, 0, 0,            KiIpiInterrupt},
    {0,  0, 0,             NULL}
}
Definition at line 88 of file initkr.c.
Referenced by KiInitializeBootStructures().
ULONG KiLogicalProcessors
Definition at line 42 of file initkr.c.
Referenced by KeStartAllProcessors(), KiInitializeBootStructures(), and KiInitializeKernel().
ULONG KiMxCsrMask = 0xFFBF
Definition at line 55 of file initkr.c.
Referenced by KiInitializeKernel().
ULONG KiPhysicalProcessors
Definition at line 43 of file initkr.c.
Referenced by KiInitializeBootStructures(), and KiInitializeKernel().
UCHAR KiPrefetchRetry = 0x80
Definition at line 65 of file initkr.c.
Referenced by KeStartAllProcessors(), and KiSetProcessorType().
KIRQL KiProfileIrql = PROFILE_LEVEL
Definition at line 28 of file initkr.c.
Referenced by KeSetProfileIrql(), KeStartProfile(), KeStopProfile(), KiStartProfileInterrupt(), and KiStopProfileInterrupt().
UNEXPECTED_INTERRUPT KxUnexpectedInterrupt0[256]
Definition at line 124 of file initkr.c.
Referenced by KeConnectInterrupt(), and KeDisconnectInterrupt().