Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpccompl.c File Reference
lpccompl.c File Reference
#include "lpcp.h"
Functions
VOID LpcpPrepareToWakeClient (IN PETHREAD ClientThread)
NTSTATUS NtAcceptConnectPort (__out PHANDLE PortHandle, __in_opt PVOID PortContext, __in PPORT_MESSAGE ConnectionRequest, __in BOOLEAN AcceptConnection, __inout_opt PPORT_VIEW ServerView, __out_opt PREMOTE_PORT_VIEW ClientView)
NTSTATUS NtCompleteConnectPort (__in HANDLE PortHandle)
Function Documentation
VOID LpcpPrepareToWakeClient (IN PETHREAD ClientThread)
Definition at line 1036 of file lpccompl.c.
References InitializeListHead(), IsListEmpty, PAGED_CODE, and RemoveEntryList().
Referenced by NtAcceptConnectPort(), and NtCompleteConnectPort().
NTSTATUS NtAcceptConnectPort (__out PHANDLE PortHandle, __in_opt PVOID PortContext, __in PPORT_MESSAGE ConnectionRequest, __in BOOLEAN AcceptConnection, __inout_opt PPORT_VIEW ServerView, __out_opt PREMOTE_PORT_VIEW ClientView)
Definition at line 38 of file lpccompl.c.
References ARGUMENT_PRESENT, _ETHREAD::Cid, _PORT_MESSAGE::ClientId, _LPCP_CONNECTION_MESSAGE::ClientPort, _LPCP_PORT_OBJECT::ClientSectionBase, _LPCP_PORT_OBJECT::ClientThread, _LPCP_CONNECTION_MESSAGE::ClientView, _PORT_MESSAGE::ClientViewSize, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_PORT_OBJECT::Creator, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, _LPCP_PORT_OBJECT::Flags, Handle, _LARGE_INTEGER::HighPart, InitializeListHead(), KeGetPreviousMode, KeReleaseSemaphore(), KernelMode, _PORT_VIEW::Length, _LARGE_INTEGER::LowPart, LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPC_REPLY, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LpcpAcquireLpcpLock, LpcpGetThreadMessage, LpcPortObjectType, LpcpPrepareToWakeClient(), LpcpPrint, LpcpReleaseLpcpLock, LpcpTrace, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MappingProcess, _LPCP_PORT_OBJECT::MaxConnectionInfoLength, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, MmMapViewOfSection(), MmSectionObjectType, NT_SUCCESS, NtClose(), NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGE_READWRITE, PAGED_CODE, PORT_ALL_ACCESS, _LPCP_PORT_OBJECT::PortContext, ProbeAndReadStructure, ProbeAndReadUlong, ProbeForReadSmallStructure, ProbeForWriteHandle, ProbeForWriteSmallStructure(), PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LPCP_MESSAGE::Request, RtlCopyMemory, RtlZeroMemory, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SECTION_MAP_READ, SECTION_MAP_WRITE, _PORT_VIEW::SectionHandle, _PORT_VIEW::SectionOffset, _LPCP_CONNECTION_MESSAGE::SectionToMap, SERVER_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ServerProcess, _LPCP_PORT_OBJECT::ServerSectionBase, _LPCP_CONNECTION_MESSAGE::ServerView, Status, STATUS_INVALID_PARAMETER, STATUS_REPLY_MESSAGE_MISMATCH, THREAD_TO_PROCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _PORT_VIEW::ViewBase, _REMOTE_PORT_VIEW::ViewBase, _PORT_VIEW::ViewRemoteBase, _PORT_VIEW::ViewSize, _REMOTE_PORT_VIEW::ViewSize, and ViewUnmap.
NTSTATUS NtCompleteConnectPort (__in HANDLE PortHandle)
Definition at line 865 of file lpccompl.c.
References _LPCP_PORT_OBJECT::ClientThread, _LPCP_PORT_OBJECT::ConnectionPort, FALSE, _LPCP_PORT_OBJECT::Flags, _LIST_ENTRY::Flink, KeGetPreviousMode, KeReleaseSemaphore(), LpcpAcquireLpcpLock, LpcpGetThreadMessage, LpcpPrepareToWakeClient(), LpcpReferencePortObject, LpcpReleaseLpcpLock, _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplySemaphore, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PORT_TYPE, SERVER_COMMUNICATION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_INVALID_PORT_HANDLE, and STATUS_SUCCESS.