Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/wait.c File Reference
wait.c File Reference
#include "ki.h"
Macros
#define InitializeDelayExecution()
#define InitializeWaitMultiple()
#define InitializeWaitSingle()
#define TestForAlertPending(Alertable)
Functions
NTSTATUS DECLSPEC_NOINLINE KeDelayExecutionThread (__in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in PLARGE_INTEGER Interval)
BOOLEAN KeIsWaitListEmpty (__in PVOID Object)
NTSTATUS KeWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) PVOID Object[], __in WAIT_TYPE WaitType, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout, __out_opt PKWAIT_BLOCK WaitBlockArray)
NTSTATUS KeWaitForSingleObject (__in PVOID Object, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
VOID FASTCALL KiAcquireFastMutex (IN PFAST_MUTEX Mutex)
VOID FASTCALL KiAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
VOID KiAdjustQuantumThread (IN PKTHREAD Thread)
FORCEINLINE PLARGE_INTEGER FASTCALL KiComputeWaitInterval (IN PLARGE_INTEGER OriginalTime, IN PLARGE_INTEGER DueTime, IN OUT PLARGE_INTEGER NewTime)
NTSTATUS KiSetServerWaitClientEvent (__inout PKEVENT ServerEvent, __inout PKEVENT ClientEvent, __in ULONG WaitMode)
Macro Definition Documentation
#define InitializeDelayExecution ()
Value:
Thread->WaitBlockList = WaitBlock;                                      \
    Thread->WaitStatus = 0;                                                 \
    KiSetDueTime(Timer, *Interval, &Hand);                                  \
    DueTime.QuadPart = Timer->DueTime.QuadPart;                             \
    WaitBlock->NextWaitBlock = WaitBlock;                                   \
    Timer->Header.WaitListHead.Flink = &WaitBlock->WaitListEntry;           \
    Timer->Header.WaitListHead.Blink = &WaitBlock->WaitListEntry;           \
    Thread->Alertable = Alertable;                                          \
    Thread->WaitMode = WaitMode;                                            \
    Thread->WaitReason = DelayExecution;                                    \
    Thread->WaitListEntry.Flink = NULL;                                     \
    StackSwappable = KiIsKernelStackSwappable(WaitMode, Thread);            \
    Thread->WaitTime = KiQueryLowTickCount()
Definition at line 218 of file wait.c.
Referenced by KeDelayExecutionThread().
#define InitializeWaitMultiple ()
Value:
Thread->WaitBlockList = WaitBlockArray;                                 \
    Index = 0;                                                              \
    do {                                                                    \
        WaitBlock = &WaitBlockArray[Index];                                 \
        WaitBlock->Object = Object[Index];                                  \
        WaitBlock->WaitKey = (CSHORT)(Index);                               \
        WaitBlock->WaitType = WaitType;                                     \
        WaitBlock->Thread = Thread;                                         \
        WaitBlock->NextWaitBlock = &WaitBlockArray[Index + 1];              \
        Index += 1;                                                         \
    } while (Index < Count);                                                \
    WaitBlock->NextWaitBlock = &WaitBlockArray[0];                          \
    Thread->WaitStatus = 0;                                                 \
    if (ARGUMENT_PRESENT(Timeout)) {                                        \
        WaitTimer->NextWaitBlock = &WaitBlockArray[0];                      \
        KiSetDueTime(Timer, *Timeout, &Hand);                               \
        DueTime.QuadPart = Timer->DueTime.QuadPart;                         \
        InitializeListHead(&Timer->Header.WaitListHead);                    \
    }                                                                       \
    Thread->Alertable = Alertable;                                          \
    Thread->WaitMode = WaitMode;                                            \
    Thread->WaitReason = (UCHAR)WaitReason;                                 \
    Thread->WaitListEntry.Flink = NULL;                                     \
    StackSwappable = KiIsKernelStackSwappable(WaitMode, Thread);            \
    Thread->WaitTime = KiQueryLowTickCount()
Definition at line 520 of file wait.c.
Referenced by KeWaitForMultipleObjects().
#define InitializeWaitSingle ()
Value:
Thread->WaitBlockList = WaitBlock;                                      \
    WaitBlock->Object = Object;                                             \
    WaitBlock->WaitKey = (CSHORT)(STATUS_SUCCESS);                          \
    WaitBlock->WaitType = WaitAny;                                          \
    Thread->WaitStatus = 0;                                                 \
    if (ARGUMENT_PRESENT(Timeout)) {                                        \
        KiSetDueTime(Timer, *Timeout, &Hand);                               \
        DueTime.QuadPart = Timer->DueTime.QuadPart;                         \
        WaitBlock->NextWaitBlock = WaitTimer;                               \
        WaitTimer->NextWaitBlock = WaitBlock;                               \
        Timer->Header.WaitListHead.Flink = &WaitTimer->WaitListEntry;       \
        Timer->Header.WaitListHead.Blink = &WaitTimer->WaitListEntry;       \
    } else {                                                                \
        WaitBlock->NextWaitBlock = WaitBlock;                               \
    }                                                                       \
    Thread->Alertable = Alertable;                                          \
    Thread->WaitMode = WaitMode;                                            \
    Thread->WaitReason = (UCHAR)WaitReason;                                 \
    Thread->WaitListEntry.Flink = NULL;                                     \
    StackSwappable = KiIsKernelStackSwappable(WaitMode, Thread);            \
    Thread->WaitTime = KiQueryLowTickCount()
Definition at line 976 of file wait.c.
Referenced by KeWaitForSingleObject().
#define TestForAlertPending (Alertable)
Value:
if (Alertable) { \
        if (Thread->Alerted[WaitMode] != FALSE) { \
            Thread->Alerted[WaitMode] = FALSE; \
            WaitStatus = STATUS_ALERTED; \
            break; \
        } else if ((WaitMode != KernelMode) && \
                  (IsListEmpty(&Thread->ApcState.ApcListHead[UserMode])) == FALSE) { \
            Thread->ApcState.UserApcPending = TRUE; \
            WaitStatus = STATUS_USER_APC; \
            break; \
        } else if (Thread->Alerted[KernelMode] != FALSE) { \
            Thread->Alerted[KernelMode] = FALSE; \
            WaitStatus = STATUS_ALERTED; \
            break; \
        } \
    } else if (Thread->ApcState.UserApcPending & WaitMode) { \
        WaitStatus = STATUS_USER_APC; \
        break; \
    }
Definition at line 52 of file wait.c.
Referenced by KeDelayExecutionThread(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
Function Documentation
NTSTATUS DECLSPEC_NOINLINE KeDelayExecutionThread (__in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in PLARGE_INTEGER Interval)
Definition at line 235 of file wait.c.
References APC_LEVEL, _KTHREAD::ApcState, ASSERT, DISPATCH_LEVEL, FALSE, InitializeDelayExecution, InsertTailList(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KernelMode, KiActivateWaiterQueue(), KiAdjustQuantumThread(), KiCheckDueTime(), KiComputeWaitInterval(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabase(), KiUnlockDispatcherDatabaseFromSynchLevel, NtYieldExecution(), NULL, _KTHREAD::Preempted, _KTHREAD::Queue, ReadForWriteAccess, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_SUCCESS, STATUS_TIMEOUT, TestForAlertPending, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, _KAPC_STATE::UserApcPending, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KTHREAD::WaitListEntry, _KPRCB::WaitListHead, and _KTHREAD::WaitNext.
Referenced by CcPurgeCacheSection(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateSharedWaiterSemaphore(), ExpExpandResourceOwnerTable(), FsRtlCreateSectionForDataScan(), IoCancelThreadIo(), IoCreateFile(), IopAllocateIrpMustSucceed(), IopCancelAlertedRequest(), KiInitMachineDependent(), KiOpPatchCode(), LpcpDeletePort(), MiAllocateLargeZeroPages(), MiAttachAndLockWorkingSet(), MiCcPutPagesInTransition(), MiCheckControlAreaStatus(), MiCheckSystemTrimEndCriteria(), MiCleanSection(), MiCloneProcessAddressSpace(), MiFindContiguousPages(), MiFlushAllPages(), MiFlushSectionInternal(), MiLockCode(), MiMakeOutswappedPageResident(), MiModifiedPageWriter(), MiModifiedPageWriterWorker(), MiPurgeImageSection(), MiRemoveUnusedSegments(), MiSessionWideReserveImageAddress(), MiShutdownSystem(), MiWriteComplete(), MmAccessFault(), MmFlushSection(), MmFlushVirtualMemory(), MmGatherMemoryForHibernate(), MmGetSystemRoutineAddress(), MmIsMemoryAvailable(), MmZeroPageThread(), NtCancelIoFile(), NtCreateSection(), NtDelayExecution(), PspExitThread(), PspTerminateThreadByPointer(), and WmipFlushBuffersWithMarker().
BOOLEAN KeIsWaitListEmpty (__in PVOID Object)
Definition at line 477 of file wait.c.
References _LIST_ENTRY::Flink, _KEVENT::Header, KeMemoryBarrier(), and _DISPATCHER_HEADER::WaitListHead.
NTSTATUS KeWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) PVOID Object[], __in WAIT_TYPE WaitType, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout, __out_opt PKWAIT_BLOCK WaitBlockArray)
Definition at line 548 of file wait.c.
References APC_LEVEL, _KTHREAD::ApcState, ARGUMENT_PRESENT, ASSERT, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, _KMUTANT::Header, Index, InitializeWaitMultiple, InsertTailList(), KeBugCheck(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KiActivateWaiterQueue(), KiAdjustQuantumThread(), KiCheckDueTime(), KiComputeWaitInterval(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabase(), KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitSatisfyAny, KiWaitSatisfyMutant, KiWaitSatisfyOther, MAXIMUM_WAIT_OBJECTS, MAXIMUM_WAIT_OBJECTS_EXCEEDED, MINLONG, MutantObject, _KWAIT_BLOCK::NextWaitBlock, NULL, _KWAIT_BLOCK::Object, _KMUTANT::OwnerThread, _KTHREAD::Preempted, _KTHREAD::Queue, QueueObject, ReadForWriteAccess, _DISPATCHER_HEADER::SignalState, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_TIMEOUT, TestForAlertPending, THREAD_WAIT_OBJECTS, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, _DISPATCHER_HEADER::Type, WaitAny, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitListEntry, _DISPATCHER_HEADER::WaitListHead, _KPRCB::WaitListHead, _KTHREAD::WaitNext, and _KTHREAD::WaitStatus.
Referenced by CmpFileWrite(), ExpWorkerThreadBalanceManager(), KeBalanceSetManager(), MiDereferenceSegmentThread(), MiFlushSectionInternal(), MiModifiedPageWriterWorker(), MiZeroAllPageFiles(), MiZeroInParallel(), MmZeroPageThread(), ObpWaitForMultipleObjects(), and PsShutdownSystem().
NTSTATUS KeWaitForSingleObject (__in PVOID Object, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 1000 of file wait.c.
References APC_LEVEL, _KTHREAD::ApcState, ARGUMENT_PRESENT, ASSERT, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, _KMUTANT::Header, InitializeWaitSingle, InsertTailList(), KeBalanceSetManager(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KiActivateWaiterQueue(), KiAdjustQuantumThread(), KiCheckDueTime(), KiComputeWaitInterval(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabase(), KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitSatisfyMutant, KiWaitSatisfyOther, MINLONG, MutantObject, NULL, _KMUTANT::OwnerThread, _KTHREAD::Preempted, PsGetCurrentThread(), _KTHREAD::Queue, QueueObject, ReadForWriteAccess, _DISPATCHER_HEADER::SignalState, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_TIMEOUT, TestForAlertPending, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, _DISPATCHER_HEADER::Type, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitListEntry, _DISPATCHER_HEADER::WaitListHead, _KPRCB::WaitListHead, _KTHREAD::WaitNext, and _KTHREAD::WaitStatus.
Referenced by CcCanIWrite(), CcInitializeCacheMap(), CcSetValidData(), CcWaitForCurrentLazyWriterActivity(), CcWaitForUninitializeCacheMap(), CcWaitOnActiveCount(), CcZeroData(), CmpFileRead(), CmpInitializeHiveList(), CmpLoadHiveThread(), CmpOpenHiveFiles(), DbgkpQueueMessage(), ExfWaitForRundownProtectionRelease(), ExpShutdownWorker(), ExpShutdownWorkerThreads(), ExpWaitForResource(), ExpWorkerThreadBalanceManager(), ExSwapinWorkerThreads(), ExTimedWaitForUnblockPushLock(), ExUnregisterCallback(), ExWaitForRundownProtectionReleaseCacheAware(), FsFilterAllocateCompletionStack(), FsRtlBalanceReads(), FsRtlDeregisterUncProvider(), FsRtlGetFileSize(), FsRtlpPostStackOverflow(), FsRtlRegisterUncProvider(), FsRtlSetFileSize(), FsRtlWaitOnIrp(), HalExamineMBR(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoCancelFileOpen(), IoGetBootDiskInformation(), IopAcquireFileObjectLock(), IopAllocateReserveIrp(), IopCancelAlertedRequest(), IopCloseFile(), IopCompleteUnloadOrDelete(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopDeleteFile(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopHardErrorThread(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopSendMessageToTrackService(), IopSetRemoteLink(), IopShutdownBaseFileSystems(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IopUnloadDriver(), IoReadPartitionTable(), IoSetInformation(), IoSetPartitionInformation(), IoShutdownSystem(), IoVerifyVolume(), IoVolumeDeviceToDosName(), IoWritePartitionTable(), KeSwapProcessOrStack(), KiAcquireFastMutex(), KiExecuteDpc(), KiSetServerWaitClientEvent(), KiSuspendThread(), LpcpRequestWaitReplyPort(), MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), MiCleanSection(), MiCreateImageFileMap(), MiDereferenceSessionFinal(), MiEnablePagingTheExecutive(), MiEnsureAvailablePageOrWait(), MiFindInitializationCode(), MiFlushSectionInternal(), MiIssuePageExtendRequest(), MiMakeOutswappedPageResident(), MiMappedPageWriter(), MiModifiedPageWriterWorker(), MiQueueWorkingSetRequest(), MiShutdownSystem(), MiUnlinkWorkingSet(), MiWaitForInPageComplete(), MiZeroPageFile(), MiZeroPageFileFirstPage(), MmCreateSection(), MmLoadSystemImage(), MmLockPageableSectionByHandle(), MmPurgeSection(), MmUnloadSystemImage(), NtLoadDriver(), NtNotifyChangeMultipleKeys(), NtQueryInformationFile(), NtReleaseKeyedEvent(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetInformationFile(), NtSignalAndWaitForSingleObject(), NtStartProfile(), NtStopProfile(), NtWaitForDebugEvent(), NtWaitForKeyedEvent(), NtWaitForSingleObject(), ObWaitForSingleObject(), PsGetContextThread(), PspExitThread(), PspQueryDescriptorThread(), PspQueryLdtInformation(), PspSetLdtInformation(), PspSetLdtSize(), PspWaitForUsermodeExit(), PsSetContextThread(), PsSetLdtEntries(), PsSetProcessLdtInfo(), PsWaitForAllProcesses(), RawCleanup(), RawClose(), RawCreate(), RawQueryFsSizeInfo(), RawUserFsCtrl(), RawVerifyVolume(), SepRmCommandServerThread(), WmipFlushLogger(), WmipForwardWmiIrp(), WmipFreeLoggerContext(), WmipGetDevicePDO(), WmipLogger(), WmipStartLogger(), WmipWaitForCollectionEnabled(), WmipWaitForIrpCompletion(), WmiStopTrace(), WmiUpdateTrace(), and xHalGetPartialGeometry().
VOID FASTCALL KiAcquireFastMutex (IN PFAST_MUTEX Mutex)
Definition at line 1348 of file wait.c.
References ASSERT, FALSE, FM_LOCK_BIT, FM_LOCK_WAITER_INC, FM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), KernelMode, KeWaitForGate(), KeWaitForSingleObject(), NULL, TRUE, WrGuardedMutex, and WrMutex.
Referenced by xxAcquireFastMutex(), and xxAcquireFastMutexUnsafe().
VOID FASTCALL KiAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 1451 of file wait.c.
References ASSERT, GM_LOCK_BIT, GM_LOCK_WAITER_INC, GM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), KernelMode, KeWaitForGate(), TRUE, and WrGuardedMutex.
Referenced by KeAcquireGuardedMutex(), and KeAcquireGuardedMutexUnsafe().
VOID KiAdjustQuantumThread (IN PKTHREAD Thread)
Definition at line 74 of file wait.c.
References FALSE, KeGetCurrentPrcb(), KiAcquirePrcbLock(), KiAcquireThreadLock(), KiComputeNewPriority(), KiExitDispatcher(), KiReleasePrcbLock(), KiReleaseThreadLock(), KiSelectReadyThread(), LOW_REALTIME_PRIORITY, _KPRCB::NextThread, NULL, _KTHREAD::Preempted, Standby, _KTHREAD::State, TIME_CRITICAL_PRIORITY_BOUND, and WAIT_QUANTUM_DECREMENT.
Referenced by KeDelayExecutionThread(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
FORCEINLINE PLARGE_INTEGER FASTCALL KiComputeWaitInterval (IN PLARGE_INTEGER OriginalTime, IN PLARGE_INTEGER DueTime, IN OUT PLARGE_INTEGER NewTime)
Definition at line 161 of file wait.c.
References KiQueryInterruptTime.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
NTSTATUS KiSetServerWaitClientEvent (__inout PKEVENT ServerEvent, __inout PKEVENT ClientEvent, __in ULONG WaitMode)
Definition at line 1299 of file wait.c.
References EVENT_INCREMENT, FALSE, KeSetEvent(), KeWaitForSingleObject(), NULL, TRUE, and WrEventPair.