Windows Research Kernel v1.2: C:/Windows Research Kernel/raw/rawinit.c File Reference
rawinit.c File Reference
#include "RawProcs.h"
#include <zwapi.h>
Functions
NTSTATUS RawInitialize (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
NTSTATUS RawShutdown (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
VOID RawUnload (IN PDRIVER_OBJECT DriverObject)
Variables
PDEVICE_OBJECT RawDeviceCdRomObject
PDEVICE_OBJECT RawDeviceDiskObject
PDEVICE_OBJECT RawDeviceTapeObject
Function Documentation
NTSTATUS RawInitialize (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Definition at line 52 of file rawinit.c.
References DO_DIRECT_IO, FALSE, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, IoCreateDevice(), IoDeleteDevice(), IoRegisterFileSystem(), IoRegisterShutdownNotification(), IRP_MJ_CLEANUP, IRP_MJ_CLOSE, IRP_MJ_CREATE, IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MJ_PNP, IRP_MJ_QUERY_INFORMATION, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_MJ_READ, IRP_MJ_SET_INFORMATION, IRP_MJ_SHUTDOWN, IRP_MJ_WRITE, NT_SUCCESS, ObReferenceObject, RawDeviceCdRomObject, RawDeviceDiskObject, RawDeviceTapeObject, RawDispatch(), RawShutdown(), RawUnload(), RtlInitUnicodeString(), Status, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
NTSTATUS RawShutdown (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 193 of file rawinit.c.
References IoDeleteDevice(), IoUnregisterFileSystem(), RawCompleteRequest, RawDeviceCdRomObject, RawDeviceDiskObject, RawDeviceTapeObject, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RawInitialize().
VOID RawUnload (IN PDRIVER_OBJECT DriverObject)
Definition at line 217 of file rawinit.c.
References ObDereferenceObject(), RawDeviceCdRomObject, RawDeviceDiskObject, RawDeviceTapeObject, and UNREFERENCED_PARAMETER.
Referenced by RawInitialize().
Variable Documentation
PDEVICE_OBJECT RawDeviceCdRomObject
Definition at line 46 of file rawinit.c.
Referenced by RawInitialize(), RawShutdown(), and RawUnload().
PDEVICE_OBJECT RawDeviceDiskObject
Definition at line 48 of file rawinit.c.
Referenced by RawInitialize(), RawShutdown(), and RawUnload().
PDEVICE_OBJECT RawDeviceTapeObject
Definition at line 47 of file rawinit.c.
Referenced by RawInitialize(), RawShutdown(), and RawUnload().