Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmsecache.c File Reference
cmsecache.c File Reference
#include "cmp.h"
Macros
#define SECURITY_CACHE_GROW_INCREMENTS 0x10
Functions
NTSTATUS CmpAddSecurityCellToCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, IN BOOLEAN BuildUp, IN PCM_KEY_SECURITY_CACHE SecurityCached)
BOOLEAN CmpAdjustSecurityCacheSize (IN PCMHIVE CmHive)
VOID CmpAssignSecurityToKcb (IN PCM_KEY_CONTROL_BLOCK Kcb, IN HCELL_INDEX SecurityCell, IN BOOLEAN SecurityLocked)
BOOLEAN CmpBuildSecurityCellMappingArray (IN PCMHIVE CmHive)
VOID CmpDestroySecurityCache (IN OUT PCMHIVE CmHive)
BOOLEAN CmpFindMatchingDescriptorCell (IN PCMHIVE CmHive, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ULONG Type, OUT PHCELL_INDEX MatchingCell, OUT OPTIONAL PCM_KEY_SECURITY_CACHE *CachedSecurityPointer)
PCM_KEY_SECURITY_CACHE CmpFindReusableCellFromCache (IN PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, IN ULONG PreviousCount)
BOOLEAN CmpFindSecurityCellCacheIndex (IN PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, OUT PULONG Index)
VOID CmpInitSecurityCache (IN OUT PCMHIVE CmHive)
BOOLEAN CmpRebuildSecurityCache (IN OUT PCMHIVE CmHive)
VOID CmpRemoveFromSecurityCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell)
ULONG CmpSecConvKey (IN ULONG DescriptorLength, IN PULONG Descriptor)
Macro Definition Documentation
#define SECURITY_CACHE_GROW_INCREMENTS 0x10
Definition at line 21 of file cmsecache.c.
Referenced by CmpAddSecurityCellToCache().
Function Documentation
NTSTATUS CmpAddSecurityCellToCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, IN BOOLEAN BuildUp, IN PCM_KEY_SECURITY_CACHE SecurityCached)
Definition at line 122 of file cmsecache.c.
References ASSERT, CmpFindSecurityCellCacheIndex(), CmpSecConvKey(), CmpSecHashTableSize, CmRetryExAllocatePoolWithTag, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, ExFreePoolWithTag, FIELD_OFFSET, HvGetCell, HvReleaseCell, Index, InsertTailList(), NULL, PAGE_SIZE, PAGED_CODE, PagedPool, PROTECTED_POOL, RtlCopyMemory, RtlMoveMemory, SECURITY_CACHE_GROW_INCREMENTS, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by CmpInsertSecurityCellList(), CmpRebuildSecurityCache(), CmpSetSecurityDescriptorInfo(), and CmpValidateHiveSecurityDescriptors().
BOOLEAN CmpAdjustSecurityCacheSize (IN PCMHIVE CmHive)
Definition at line 489 of file cmsecache.c.
References CmRetryExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, NULL, PAGED_CODE, PagedPool, PROTECTED_POOL, RtlCopyMemory, and TRUE.
Referenced by CmpValidateHiveSecurityDescriptors().
VOID CmpAssignSecurityToKcb (IN PCM_KEY_CONTROL_BLOCK Kcb, IN HCELL_INDEX SecurityCell, IN BOOLEAN SecurityLocked)
Definition at line 1016 of file cmsecache.c.
References BAD_SECURITY_CACHE, _CM_KEY_SECURITY_CACHE_ENTRY::CachedSecurity, CM_BUGCHECK, CmLockHiveSecurityShared, CmpFindSecurityCellCacheIndex(), CmUnlockHiveSecurity, FALSE, HCELL_NIL, Index, NULL, PAGED_CODE, REGISTRY_ERROR, and _CMHIVE::SecurityCache.
Referenced by CmpAssignSecurityDescriptorWrapper(), CmpCreateKeyControlBlock(), CmpSetSecurityDescriptorInfo(), and CmRestoreKey().
BOOLEAN CmpBuildSecurityCellMappingArray (IN PCMHIVE CmHive)
Definition at line 1082 of file cmsecache.c.
References ASSERT, ExAllocatePool, FALSE, HCELL_NIL, HvGetCellType, NULL, PAGED_CODE, PagedPool, TRUE, and Volatile.
Referenced by CmCompressKey().
VOID CmpDestroySecurityCache (IN OUT PCMHIVE CmHive)
Definition at line 616 of file cmsecache.c.
References ASSERT, CmpRemoveEntryList, ExFreePoolWithTag, NULL, PAGED_CODE, and PROTECTED_POOL.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), CmpValidateHiveSecurityDescriptors(), and CmUnloadKey().
BOOLEAN CmpFindMatchingDescriptorCell (IN PCMHIVE CmHive, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ULONG Type, OUT PHCELL_INDEX MatchingCell, OUT OPTIONAL PCM_KEY_SECURITY_CACHE * CachedSecurityPointer)
Definition at line 901 of file cmsecache.c.
References ARGUMENT_PRESENT, _CM_KEY_SECURITY_CACHE::Cell, CmpSecConvKey(), CmpSecHashTableSize, CONTAINING_RECORD, _CM_KEY_SECURITY_CACHE::ConvKey, _CM_KEY_SECURITY_CACHE::Descriptor, _CM_KEY_SECURITY_CACHE::DescriptorLength, FALSE, _LIST_ENTRY::Flink, HvGetCellType, IsListEmpty, List, PAGED_CODE, RtlEqualMemory, RtlLengthSecurityDescriptor(), and TRUE.
Referenced by CmpAssignSecurityDescriptor(), and CmpSetSecurityDescriptorInfo().
PCM_KEY_SECURITY_CACHE CmpFindReusableCellFromCache (IN PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, IN ULONG PreviousCount)
Definition at line 653 of file cmsecache.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _CM_KEY_SECURITY::DescriptorLength, _CM_KEY_SECURITY_CACHE::DescriptorLength, ExFreePoolWithTag, HvGetCell, HvReleaseCell, NULL, PAGED_CODE, PROTECTED_POOL, and RtlMoveMemory.
Referenced by CmpRebuildSecurityCache().
BOOLEAN CmpFindSecurityCellCacheIndex (IN PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, OUT PULONG Index)
Definition at line 308 of file cmsecache.c.
References ASSERT, FALSE, HCELL_TYPE_MASK, NULL, PAGED_CODE, and TRUE.
Referenced by CmpAddSecurityCellToCache(), CmpAssignSecurityToKcb(), CmpCheckNotifyAccess(), CmpCopyKeyPartial(), CmpRemoveFromSecurityCache(), CmpSetSecurityDescriptorInfo(), CmpSyncKeyValues(), and CmpValidateHiveSecurityDescriptors().
VOID CmpInitSecurityCache (IN OUT PCMHIVE CmHive)
Definition at line 103 of file cmsecache.c.
References CmpSecHashTableSize, InitializeListHead(), NULL, and PAGED_CODE.
Referenced by CmGetSystemControlValues(), CmpInitializeHive(), and CmpValidateHiveSecurityDescriptors().
BOOLEAN CmpRebuildSecurityCache (IN OUT PCMHIVE CmHive)
Definition at line 769 of file cmsecache.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, _CM_KEY_SECURITY::Blink, CmKdPrintEx, CML_SEC, CmpAddSecurityCellToCache(), CmpDumpSecurityDescriptor, CmpFindReusableCellFromCache(), CmpSecHashTableSize, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_SECURITY::Flink, Hive, HvGetCell, HvIsCellAllocated(), InitializeListHead(), NT_SUCCESS, NULL, PAGED_CODE, _CM_KEY_SECURITY::ReferenceCount, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, _CM_KEY_NODE::Security, SeValidSecurityDescriptor(), and TRUE.
Referenced by HvRefreshHive().
VOID CmpRemoveFromSecurityCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell)
Definition at line 555 of file cmsecache.c.
References ASSERT, CmpFindSecurityCellCacheIndex(), CmpRemoveEntryList, ExFreePoolWithTag, FALSE, Index, PAGED_CODE, PROTECTED_POOL, and RtlMoveMemory.
Referenced by CmpRemoveSecurityCellList(), and CmpSetSecurityDescriptorInfo().
ULONG CmpSecConvKey (IN ULONG DescriptorLength, IN PULONG Descriptor)
Definition at line 55 of file cmsecache.c.
References Count, and PAGED_CODE.
Referenced by CmpAddSecurityCellToCache(), CmpFindMatchingDescriptorCell(), and CmpSetSecurityDescriptorInfo().