Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/misc.c File Reference
misc.c File Reference
#include "iomgr.h"
Functions
PIO_WORKITEM IoAllocateWorkItem (PDEVICE_OBJECT DeviceObject)
VOID IoFreeWorkItem (PIO_WORKITEM IoWorkItem)
VOID IopProcessWorkItem (IN PVOID Parameter)
VOID IoQueueWorkItem (IN PIO_WORKITEM IoWorkItem, IN PIO_WORKITEM_ROUTINE WorkerRoutine, IN WORK_QUEUE_TYPE QueueType, IN PVOID Context)
NTSTATUS NtCancelIoFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS NtDeleteFile (__in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtFlushBuffersFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS NtQueryAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_BASIC_INFORMATION FileInformation)
NTSTATUS NtQueryFullAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_NETWORK_OPEN_INFORMATION FileInformation)
Function Documentation
PIO_WORKITEM IoAllocateWorkItem (PDEVICE_OBJECT DeviceObject)
Definition at line 902 of file misc.c.
References _IO_WORKITEM::DeviceObject, ExAllocatePool, ExInitializeWorkItem, IopProcessWorkItem(), NonPagedPool, NULL, and _IO_WORKITEM::WorkItem.
VOID IoFreeWorkItem (PIO_WORKITEM IoWorkItem)
Definition at line 935 of file misc.c.
References ASSERT, and ExFreePool().
VOID IopProcessWorkItem (IN PVOID Parameter)
Definition at line 1027 of file misc.c.
References _IO_WORKITEM::Context, _IO_WORKITEM::DeviceObject, ObDereferenceObject(), PAGED_CODE, and _IO_WORKITEM::Routine.
Referenced by IoAllocateWorkItem().
VOID IoQueueWorkItem (IN PIO_WORKITEM IoWorkItem, IN PIO_WORKITEM_ROUTINE WorkerRoutine, IN WORK_QUEUE_TYPE QueueType, IN PVOID Context)
Definition at line 964 of file misc.c.
References ASSERT, DISPATCH_LEVEL, ExQueueWorkItem(), KeGetCurrentIrql(), and ObReferenceObject.
NTSTATUS NtCancelIoFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 40 of file misc.c.
References APC_LEVEL, CONTAINING_RECORD, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LIST_ENTRY::Flink, IoCancelIrp(), IoFileObjectType, IopUpdateOtherOperationCount(), IRP, _ETHREAD::IrpList, KeDelayExecutionThread(), KeGetPreviousModeByThread, KeLowerIrql, KeRaiseIrql, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PIRP, ProbeForWriteIoStatus, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and VOID.
NTSTATUS NtDeleteFile (__in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 291 of file misc.c.
References _OPEN_PACKET::CreateOptions, DELETE, _OPEN_PACKET::DeleteOnly, _OPEN_PACKET::Disposition, FALSE, FILE_DELETE_ON_CLOSE, FILE_OPEN, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, IO_TYPE_OPEN_PACKET, IopUpdateOtherOperationCount(), KeGetPreviousMode, _OPEN_PACKET::LocalFileObject, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, PAGED_CODE, _OPEN_PACKET::ParseCheck, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, _OPEN_PACKET::TraversedMountPoint, TRUE, and _OPEN_PACKET::Type.
NTSTATUS NtFlushBuffersFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 380 of file misc.c.
References _FILE_OBJECT::Event, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FILE_APPEND_DATA, FILE_WRITE_DATA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_NAMED_PIPE, FO_SYNCHRONOUS_IO, _OBJECT_HANDLE_INFORMATION::GrantedAccess, IoAllocateIrp(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IRP_MJ_FLUSH_BUFFERS, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, PIRP, ProbeForWriteIoStatus, PsGetCurrentThread(), SeComputeGrantedAccesses, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSTATUS NtQueryAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_BASIC_INFORMATION FileInformation)
Definition at line 625 of file misc.c.
References _OPEN_PACKET::BasicInformation, _OPEN_PACKET::CreateOptions, _OPEN_PACKET::Disposition, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_REPARSE_POINT, FILE_READ_ATTRIBUTES, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, IO_TYPE_OPEN_PACKET, IopUpdateOtherOperationCount(), KeGetPreviousMode, KernelMode, _OPEN_PACKET::LocalFileObject, _OPEN_PACKET::NetworkInformation, NT_SUCCESS, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, PAGED_CODE, _OPEN_PACKET::ParseCheck, ProbeForWriteSmallStructure(), _OPEN_PACKET::QueryOnly, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, _OPEN_PACKET::TraversedMountPoint, TRUE, _OPEN_PACKET::Type, and ZwClose().
NTSTATUS NtQueryFullAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_NETWORK_OPEN_INFORMATION FileInformation)
Definition at line 749 of file misc.c.
References _OPEN_PACKET::CreateOptions, _OPEN_PACKET::Disposition, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_REPARSE_POINT, FILE_READ_ATTRIBUTES, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, _OPEN_PACKET::FullAttributes, IO_TYPE_OPEN_PACKET, IopUpdateOtherOperationCount(), KeGetPreviousMode, KernelMode, _OPEN_PACKET::LocalFileObject, _OPEN_PACKET::NetworkInformation, NT_SUCCESS, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, PAGED_CODE, _OPEN_PACKET::ParseCheck, ProbeForWriteSmallStructure(), _OPEN_PACKET::QueryOnly, RtlCopyMemory, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, _OPEN_PACKET::TraversedMountPoint, TRUE, _OPEN_PACKET::Type, and ZwClose().