Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcreply.c File Reference
lpcreply.c File Reference
#include "lpcp.h"
Functions
NTSTATUS LpcpCopyRequestData (IN BOOLEAN WriteToMessageData, IN HANDLE PortHandle, IN PPORT_MESSAGE Message, IN ULONG DataEntryIndex, IN PVOID Buffer, IN SIZE_T BufferSize, OUT PSIZE_T NumberOfBytesCopied OPTIONAL)
BOOLEAN FASTCALL LpcpValidateClientPort (IN PETHREAD Thread, IN PLPCP_PORT_OBJECT ReplyPort, IN ULONG Reason)
NTSTATUS NtReadRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
NTSTATUS NtReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE ReplyMessage)
NTSTATUS NtReplyWaitReplyPort (__in HANDLE PortHandle, __inout PPORT_MESSAGE ReplyMessage)
NTSTATUS NtWriteRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __in_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Variables
ULONG LpcpEventCounts = 0
Function Documentation
NTSTATUS LpcpCopyRequestData (IN BOOLEAN WriteToMessageData, IN HANDLE PortHandle, IN PPORT_MESSAGE Message, IN ULONG DataEntryIndex, IN PVOID Buffer, IN SIZE_T BufferSize, OUT PSIZE_T NumberOfBytesCopied OPTIONAL)
Definition at line 987 of file lpcreply.c.
References ARGUMENT_PRESENT, _PORT_DATA_ENTRY::Base, _PORT_MESSAGE::CallbackId, _PORT_MESSAGE::ClientId, _PORT_DATA_INFORMATION::CountDataEntries, _PORT_DATA_INFORMATION::DataEntries, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, LPCP_VALIDATE_REASON_WRONG_DATA, LpcpAcquireLpcpLock, LpcpFindDataInfoMessage(), LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpValidateClientPort(), _ETHREAD::LpcReplyMessageId, _PORT_MESSAGE::MessageId, MmCopyVirtualMemory(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, ProbeForRead, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteUlong_ptr, PsGetCurrentProcess(), PsLookupProcessThreadByCid(), _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _PORT_DATA_ENTRY::Size, Status, STATUS_INVALID_PARAMETER, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, THREAD_TO_PROCESS, and _PORT_MESSAGE::u2.
Referenced by NtReadRequestData(), and NtWriteRequestData().
BOOLEAN FASTCALL LpcpValidateClientPort (IN PETHREAD Thread, IN PLPCP_PORT_OBJECT ReplyPort, IN ULONG Reason)
Definition at line 1247 of file lpcreply.c.
References _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, FALSE, LpcpGetThreadPort, NULL, PORT_TYPE, SERVER_COMMUNICATION_PORT, and TRUE.
Referenced by LpcpCopyRequestData(), LpcpRequestWaitReplyPort(), NtImpersonateClientOfPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
NTSTATUS NtReadRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
Definition at line 870 of file lpcreply.c.
References FALSE, LpcpCopyRequestData(), and PAGED_CODE.
NTSTATUS NtReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE ReplyMessage)
Definition at line 59 of file lpcreply.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, _PORT_MESSAGE::ClientId, DbgBreakPoint(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, InitializeListHead(), IsListEmpty, KeGetPreviousMode, KeReleaseSemaphore(), KernelMode, LPC_KERNELMODE_MESSAGE, LPC_REPLY, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpTrace, LpcpTraceError, LpcpValidateClientPort(), _ETHREAD::LpcReceivedMessageId, _ETHREAD::LpcReceivedMsgIdValid, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, ProbeForReadSmallStructure, PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, THREAD_TO_PROCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, and _CLIENT_ID::UniqueThread.
NTSTATUS NtReplyWaitReplyPort (__in HANDLE PortHandle, __inout PPORT_MESSAGE ReplyMessage)
Definition at line 399 of file lpcreply.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ConnectedPort, DbgBreakPoint(), _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), InsertTailList(), IsListEmpty, KeGetPreviousMode, KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), LPC_KERNELMODE_MESSAGE, LPC_REPLY, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpSetPortToThread, LpcpTrace, LpcpTraceError, LpcpValidateClientPort(), _ETHREAD::LpcReceivedMessageId, _ETHREAD::LpcReceivedMsgIdValid, _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_TYPE, ProbeForWriteSmallStructure(), PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_LPC_REPLY_LOST, STATUS_NO_MEMORY, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_USER_APC, THREAD_TO_PROCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, and WrExecutive.
NTSTATUS NtWriteRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __in_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Definition at line 927 of file lpcreply.c.
References LpcpCopyRequestData(), PAGED_CODE, and TRUE.
Variable Documentation
ULONG LpcpEventCounts = 0
Definition at line 55 of file lpcreply.c.