Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmtrecpy.c File Reference
cmtrecpy.c File Reference
#include "cmp.h"
Data Structures
struct CMP_COPY_STACK_ENTRY
Macros
#define CMP_INITIAL_STACK_SIZE 1024
Typedefs
typedef struct CMP_COPY_STACK_ENTRY * PCMP_COPY_STACK_ENTRY
Functions
HCELL_INDEX CmpCopyCell (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
HCELL_INDEX CmpCopyKeyPartial (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PHHIVE TargetHive, HCELL_INDEX Parent, BOOLEAN CopyValues)
BOOLEAN CmpCopySyncTree (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HCELL_INDEX TargetCell, BOOLEAN CopyVolatile, CMP_COPY_TYPE CopyType)
BOOLEAN CmpCopySyncTree2 (PCMP_COPY_STACK_ENTRY CmpCopyStack, ULONG CmpCopyStackSize, ULONG CmpCopyStackTop, PHHIVE CmpSourceHive, PHHIVE CmpTargetHive, BOOLEAN CopyVolatile, CMP_COPY_TYPE CopyType)
HCELL_INDEX CmpCopyValue (PHHIVE SourceHive, HCELL_INDEX SourceValueCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
BOOLEAN CmpFreeKeyValues (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node)
VOID CmpInitializeKeyNameString (PCM_KEY_NODE Cell, PUNICODE_STRING KeyName, WCHAR *NameBuffer)
VOID CmpInitializeValueNameString (PCM_KEY_VALUE Cell, PUNICODE_STRING ValueName, WCHAR *NameBuffer)
BOOLEAN CmpMarkKeyParentDirty (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN CmpMarkKeyValuesDirty (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node)
BOOLEAN CmpMergeKeyValues (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PCM_KEY_NODE SourceKeyNode, PHHIVE TargetHive, HCELL_INDEX TargetKeyCell, PCM_KEY_NODE TargetKeyNode)
BOOLEAN CmpSyncKeyValues (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PCM_KEY_NODE SourceKeyNode, PHHIVE TargetHive, HCELL_INDEX TargetKeyCell, PCM_KEY_NODE TargetKeyNode)
BOOLEAN CmpSyncSubKeysAfterDelete (PHHIVE SourceHive, PCM_KEY_NODE SourceCell, PHHIVE TargetHive, PCM_KEY_NODE TargetCell, WCHAR *NameBuffer)
Macro Definition Documentation
#define CMP_INITIAL_STACK_SIZE 1024
Definition at line 30 of file cmtrecpy.c.
Referenced by CmpCopySyncTree().
Typedef Documentation
typedef struct CMP_COPY_STACK_ENTRY * PCMP_COPY_STACK_ENTRY
Function Documentation
HCELL_INDEX CmpCopyCell (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
Definition at line 1330 of file cmtrecpy.c.
References ASSERT, CmKdPrintEx, CML_SAVRES, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellSize(), HvReleaseCell, NULL, and RtlCopyMemory.
Referenced by CmpCopyKeyPartial(), CmpCopyValue(), and CmpSyncKeyValues().
HCELL_INDEX CmpCopyKeyPartial (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PHHIVE TargetHive, HCELL_INDEX Parent, BOOLEAN CopyValues)
Definition at line 759 of file cmtrecpy.c.
References ASSERT, ASSERT_CELL_DIRTY, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CmKdPrintEx, CML_SAVRES, CmLockHiveSecurityExclusive, CmLockHiveSecurityShared, CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCopyValue(), CmpFindNameInList(), CmpFindSecurityCellCacheIndex(), CmpInitializeValueNameString(), CmUnlockHiveSecurity, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvGetCellType, HvReleaseCell, Index, KEY_COMP_NAME, KEY_HIVE_ENTRY, KEY_NO_DELETE, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyNode, _CHILD_LIST::List, NT_SUCCESS, NULL, PagedPool, _CM_KEY_NODE::Parent, REG_MAX_KEY_VALUE_NAME_LENGTH, _CM_KEY_NODE::Security, Stable, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpCopySyncTree2(), CmpDuplicateKey(), CmpLoadHiveVolatile(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
BOOLEAN CmpCopySyncTree (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HCELL_INDEX TargetCell, BOOLEAN CopyVolatile, CMP_COPY_TYPE CopyType)
Definition at line 119 of file cmtrecpy.c.
References CmKdPrintEx, CML_SAVRES, CMP_INITIAL_STACK_SIZE, CmpCopySyncTree2(), DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, NULL, PagedPool, _HHIVE::ReleaseCellRoutine, CMP_COPY_STACK_ENTRY::SourceCell, and CMP_COPY_STACK_ENTRY::TargetCell.
BOOLEAN CmpCopySyncTree2 (PCMP_COPY_STACK_ENTRY CmpCopyStack, ULONG CmpCopyStackSize, ULONG CmpCopyStackTop, PHHIVE CmpSourceHive, PHHIVE CmpTargetHive, BOOLEAN CopyVolatile, CMP_COPY_TYPE CopyType)
Definition at line 252 of file cmtrecpy.c.
References CmKdPrintEx, CML_SAVRES, CmpAddSubKey(), CmpCopyKeyPartial(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpInitializeKeyNameString(), CmpMarkKeyParentDirty(), CmpMergeKeyValues(), CmpSyncKeyValues(), CmpSyncSubKeysAfterDelete(), DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, CMP_COPY_STACK_ENTRY::i, KEY_COMP_NAME, KeyName, _CM_KEY_NODE::LastWriteTime, _CM_KEY_NODE::MaxNameLen, Merge, _CM_KEY_NODE::NameLength, NULL, PagedPool, _LARGE_INTEGER::QuadPart, REG_MAX_KEY_NAME_LENGTH, CMP_COPY_STACK_ENTRY::SourceCell, Stable, _CM_KEY_NODE::SubKeyCounts, Sync, CMP_COPY_STACK_ENTRY::TargetCell, TRUE, and Volatile.
Referenced by CmpCopySyncTree().
HCELL_INDEX CmpCopyValue (PHHIVE SourceHive, HCELL_INDEX SourceValueCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
Definition at line 1113 of file cmtrecpy.c.
References ASSERT, CM_KEY_VALUE_SMALL, CM_KEY_VALUE_SPECIAL_SIZE, CmKdPrintEx, CML_SAVRES, CmpCopyCell(), CmpFreeValueData(), CmpGetValueData(), CmpIsHKeyValueBig, CmpIsHKeyValueSmall, CmpSetValueDataNew(), _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyValue, NT_SUCCESS, NULL, TRUE, and _CELL_DATA::u.
Referenced by CmpCopyKeyPartial(), CmpMergeKeyValues(), and CmpSyncKeyValues().
BOOLEAN CmpFreeKeyValues (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node)
Definition at line 1406 of file cmtrecpy.c.
References ASSERT, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CmpFreeValue(), CmpMarkKeyValuesDirty(), _CHILD_LIST::Count, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, KEY_HIVE_EXIT, _CELL_DATA::_u::KeyList, _CHILD_LIST::List, NULL, TRUE, _CELL_DATA::u, and _CM_KEY_NODE::ValueList.
Referenced by CmpSyncKeyValues().
VOID CmpInitializeKeyNameString (PCM_KEY_NODE Cell, PUNICODE_STRING KeyName, WCHAR * NameBuffer)
Definition at line 2058 of file cmtrecpy.c.
References _UNICODE_STRING::Buffer, CmpCompressedNameSize(), CmpCopyCompressedName(), _CM_KEY_NODE::Flags, KEY_COMP_NAME, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, and REG_MAX_KEY_NAME_LENGTH.
Referenced by CmpCopySyncTree2(), CmpNotifyChangeKey(), and CmpSyncSubKeysAfterDelete().
VOID CmpInitializeValueNameString (PCM_KEY_VALUE Cell, PUNICODE_STRING ValueName, WCHAR * NameBuffer)
Definition at line 2125 of file cmtrecpy.c.
References _UNICODE_STRING::Buffer, CmpCompressedNameSize(), CmpCopyCompressedName(), _CM_KEY_VALUE::Flags, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_VALUE::Name, _CM_KEY_VALUE::NameLength, REG_MAX_KEY_VALUE_NAME_LENGTH, and VALUE_COMP_NAME.
Referenced by CmpCopyKeyPartial(), CmpMergeKeyValues(), and CmpSyncKeyValues().
BOOLEAN CmpMarkKeyParentDirty (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2463 of file cmtrecpy.c.
References ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CmpMarkIndexDirty(), FALSE, _CM_KEY_NODE::Flags, HvGetCell, HvMarkCellDirty(), KEY_HIVE_ENTRY, _CELL_DATA::_u::KeyNode, NULL, _CM_KEY_NODE::Parent, TRUE, and _CELL_DATA::u.
Referenced by CmpCopySyncTree2().
BOOLEAN CmpMarkKeyValuesDirty (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node)
Definition at line 2316 of file cmtrecpy.c.
References ASSERT, _CM_KEY_SECURITY::Blink, _CM_KEY_NODE::Class, CmpMarkValueDataDirty(), _CHILD_LIST::Count, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_SECURITY::Flink, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), KEY_HIVE_EXIT, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeySecurity, _CELL_DATA::_u::KeyValue, _CHILD_LIST::List, NULL, _CM_KEY_NODE::Security, TRUE, _CELL_DATA::u, and _CM_KEY_NODE::ValueList.
Referenced by CmpFreeKeyValues().
BOOLEAN CmpMergeKeyValues (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PCM_KEY_NODE SourceKeyNode, PHHIVE TargetHive, HCELL_INDEX TargetKeyCell, PCM_KEY_NODE TargetKeyNode)
Definition at line 1506 of file cmtrecpy.c.
References ASSERT, CmpAddValueToList(), CmpCopyValue(), CmpFindNameInList(), CmpInitializeValueNameString(), CmpSyncKeyValues(), _CHILD_LIST::Count, ExAllocatePool, ExFreePool(), FALSE, HCELL_NIL, HvGetCell, HvGetCellType, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CELL_DATA::_u::KeyList, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PagedPool, REG_MAX_KEY_VALUE_NAME_LENGTH, _HHIVE::ReleaseCellRoutine, TRUE, _CELL_DATA::u, and _CM_KEY_NODE::ValueList.
Referenced by CmpCopySyncTree2(), and CmSaveMergedKeys().
BOOLEAN CmpSyncKeyValues (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PCM_KEY_NODE SourceKeyNode, PHHIVE TargetHive, HCELL_INDEX TargetKeyCell, PCM_KEY_NODE TargetKeyNode)
Definition at line 1683 of file cmtrecpy.c.
References ASSERT, _CM_KEY_SECURITY::Blink, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CmLockHiveSecurityExclusive, CmLockHiveSecurityShared, CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCopyValue(), CmpFindNameInList(), CmpFindSecurityCellCacheIndex(), CmpFreeKeyValues(), CmpFreeSecurityDescriptor(), CmpInitializeValueNameString(), CmUnlockHiveSecurity, _CHILD_LIST::Count, ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, _CM_KEY_SECURITY::Flink, HCELL_NIL, HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), Index, KEY_HIVE_ENTRY, _CELL_DATA::_u::KeyList, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PagedPool, REG_MAX_KEY_VALUE_NAME_LENGTH, _HHIVE::ReleaseCellRoutine, _CM_KEY_NODE::Security, TRUE, _CELL_DATA::u, UNREFERENCED_PARAMETER, and _CM_KEY_NODE::ValueList.
Referenced by CmpCopySyncTree2(), and CmpMergeKeyValues().
BOOLEAN CmpSyncSubKeysAfterDelete (PHHIVE SourceHive, PCM_KEY_NODE SourceCell, PHHIVE TargetHive, PCM_KEY_NODE TargetCell, WCHAR * NameBuffer)
Definition at line 2191 of file cmtrecpy.c.
References CmpDeleteTree(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpFreeKeyByCell(), CmpInitializeKeyNameString(), FALSE, HCELL_NIL, HvGetCell, HvReleaseCell, NT_SUCCESS, NULL, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmpCopySyncTree2().