Windows Research Kernel v1.2: C:/Windows Research Kernel/fstub/drivesup.c File Reference
drivesup.c File Reference
#include "ntos.h"
#include "zwapi.h"
#include "hal.h"
#include "ntdddisk.h"
#include "haldisp.h"
#include "ntddft.h"
#include "mountmgr.h"
#include "stdio.h"
#include <setupblk.h>
#include "drivesup.h"
#include "fstub.h"
Data Structures
struct _BOOT_SECTOR_INFO
struct _DISK_LAYOUT
struct _PARTITION_TABLE
struct _PTE
Macros
#define BOOTABLE_PARTITION 0
#define FSTUB_TAG ('BtsF')
#define FT_PARTITION 3
#define GET_PARTITION_LENGTH(p)
#define GET_STARTING_SECTOR(p)
#define GET_STARTING_SECTOR(p)
#define GPT_PARTITION 5
#define LOGICAL_PARTITION 2
#define OTHER_PARTITION 4
#define PRIMARY_PARTITION 1
#define WHICH_BIT(Data, Bit)
Typedefs
typedef struct _BOOT_SECTOR_INFO BOOT_SECTOR_INFO
typedef struct _DISK_LAYOUT DISK_LAYOUT
typedef struct _PARTITION_TABLE PARTITION_TABLE
typedef struct _BOOT_SECTOR_INFO * PBOOT_SECTOR_INFO
typedef struct _DISK_LAYOUT * PDISK_LAYOUT
typedef struct _PARTITION_TABLE * PPARTITION_TABLE
typedef PTE UNALIGNED * PPTE
typedef struct _PTE PTE
Functions
VOID FstubFixupEfiPartition (IN PPARTITION_DESCRIPTOR Entry, IN ULONGLONG MaxSector)
VOID FASTCALL HalExamineMBR (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG MBRTypeIdentifier, OUT PVOID *Buffer)
VOID HalpCalculateChsValues (IN PLARGE_INTEGER PartitionOffset, IN PLARGE_INTEGER PartitionLength, IN CCHAR ShiftCount, IN ULONG SectorsPerTrack, IN ULONG NumberOfTracks, IN ULONG ConventionalCylinders, OUT PPARTITION_DESCRIPTOR PartitionDescriptor)
NTSTATUS HalpDeleteMountLetter (IN UCHAR DriveLetter)
VOID HalpEnableAutomaticDriveLetterAssignment ()
NTSTATUS HalpGetFullGeometry (IN PDEVICE_OBJECT DeviceObject, IN PDISK_GEOMETRY Geometry, OUT PULONGLONG RealSectorCount)
BOOLEAN HalpIsOldStyleFloppy (IN PUNICODE_STRING DeviceName)
BOOLEAN HalpIsValidPartitionEntry (PPARTITION_DESCRIPTOR Entry, ULONGLONG MaxOffset, ULONGLONG MaxSector)
UCHAR HalpNextDriveLetter (IN PUNICODE_STRING DeviceName, IN PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, IN BOOLEAN UseHardLinksIfNecessary)
NTSTATUS HalpNextMountLetter (IN PUNICODE_STRING DeviceName, OUT PUCHAR DriveLetter)
NTSTATUS HalpQueryDriveLayout (IN PUNICODE_STRING DeviceName, OUT PDRIVE_LAYOUT_INFORMATION *DriveLayout)
NTSTATUS HalpQueryPartitionType (IN PUNICODE_STRING DeviceName, IN PDRIVE_LAYOUT_INFORMATION DriveLayout, OUT PULONG PartitionType)
NTSTATUS HalpSetMountLetter (IN PUNICODE_STRING DeviceName, IN UCHAR DriveLetter)
VOID FASTCALL IoAssignDriveLetters (IN struct _LOADER_PARAMETER_BLOCK *LoaderBlock, IN PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, OUT PSTRING NtSystemPathString)
PULONG IopComputeHarddiskDerangements (IN ULONG DiskCount)
NTSTATUS FASTCALL IoReadPartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN BOOLEAN ReturnRecognizedPartitions, OUT struct _DRIVE_LAYOUT_INFORMATION **PartitionBuffer)
NTSTATUS FASTCALL IoSetPartitionInformation (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG PartitionNumber, IN ULONG PartitionType)
NTSTATUS FASTCALL IoWritePartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG SectorsPerTrack, IN ULONG NumberOfHeads, IN struct _DRIVE_LAYOUT_INFORMATION *PartitionBuffer)
VOID FASTCALL xHalGetPartialGeometry (IN PDEVICE_OBJECT DeviceObject, IN PULONG ConventionalCylinders, IN PLONGLONG DiskSize)
Variables
static PCHAR DiskPartitionName = "\\Device\\Harddisk%d\\Partition%d"
static PCHAR RegistryKeyName = DISK_REGISTRY_KEY
Macro Definition Documentation
#define BOOTABLE_PARTITION 0
Definition at line 721 of file drivesup.c.
Referenced by HalpQueryPartitionType(), and IoAssignDriveLetters().
#define FSTUB_TAG ('BtsF')
Definition at line 38 of file drivesup.c.
Referenced by HalpQueryDriveLayout().
#define FT_PARTITION 3
Definition at line 724 of file drivesup.c.
Referenced by HalpQueryPartitionType(), and IoAssignDriveLetters().
#define GET_PARTITION_LENGTH (p)
Value:
(\
        (ULONG) (p->PartitionLengthLsb0) +          \
        (ULONG) (p->PartitionLengthLsb1 << 8) +     \
        (ULONG) (p->PartitionLengthMsb0 << 16) +    \
        (ULONG) (p->PartitionLengthMsb1 << 24) )
Definition at line 50 of file drivesup.c.
Referenced by HalpIsValidPartitionEntry(), and IoReadPartitionTable().
#define GET_STARTING_SECTOR (p)
Value:
(\
        (ULONG) (p->StartingSectorLsb0) +           \
        (ULONG) (p->StartingSectorLsb1 << 8) +      \
        (ULONG) (p->StartingSectorMsb0 << 16) +     \
        (ULONG) (p->StartingSectorMsb1 << 24) )
Definition at line 44 of file drivesup.c.
Referenced by HalpIsValidPartitionEntry(), IoReadPartitionTable(), and IoSetPartitionInformation().
#define GET_STARTING_SECTOR (p)
Value:
(\
        (ULONG) (p->StartingSectorLsb0) +           \
        (ULONG) (p->StartingSectorLsb1 << 8) +      \
        (ULONG) (p->StartingSectorMsb0 << 16) +     \
        (ULONG) (p->StartingSectorMsb1 << 24) )
Definition at line 44 of file drivesup.c.
#define GPT_PARTITION 5
Definition at line 726 of file drivesup.c.
Referenced by HalpQueryPartitionType(), and IoAssignDriveLetters().
#define LOGICAL_PARTITION 2
Definition at line 723 of file drivesup.c.
Referenced by HalpQueryPartitionType(), and IoAssignDriveLetters().
#define OTHER_PARTITION 4
Definition at line 725 of file drivesup.c.
Referenced by HalpQueryPartitionType().
#define PRIMARY_PARTITION 1
Definition at line 722 of file drivesup.c.
Referenced by HalpQueryPartitionType(), and IoAssignDriveLetters().
#define WHICH_BIT (Data, Bit)
Value:
{                      \
    for (Bit = 0; Bit < 32; Bit++) {                \
        if ((Data >> Bit) == 1) {                   \
            break;                                  \
        }                                           \
    }                                               \
}
Referenced by IoWritePartitionTable().
Typedef Documentation
typedef struct _BOOT_SECTOR_INFO BOOT_SECTOR_INFO
typedef struct _DISK_LAYOUT DISK_LAYOUT
typedef struct _PARTITION_TABLE PARTITION_TABLE
typedef struct _BOOT_SECTOR_INFO * PBOOT_SECTOR_INFO
typedef struct _DISK_LAYOUT * PDISK_LAYOUT
typedef struct _PARTITION_TABLE * PPARTITION_TABLE
typedef PTE UNALIGNED* PPTE
Definition at line 93 of file drivesup.c.
typedef struct _PTE PTE
Function Documentation
VOID FstubFixupEfiPartition (IN PPARTITION_DESCRIPTOR Entry, IN ULONGLONG MaxSector)
Definition at line 3836 of file drivesup.c.
References PAGED_CODE.
Referenced by IoReadPartitionTable().
VOID FASTCALL HalExamineMBR (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG MBRTypeIdentifier, OUT PVOID * Buffer)
Definition at line 212 of file drivesup.c.
References ASSERT, BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, PAGE_SIZE, PARTITION_TABLE_OFFSET, _PARTITION_DESCRIPTOR::PartitionType, PIRP, RtlConvertUlongToLargeInteger(), SL_OVERRIDE_VERIFY_VOLUME, _IO_STATUS_BLOCK::Status, STATUS_PENDING, STATUS_SUCCESS, and VOID.
Referenced by IopCreateArcNamesDisk(), IoReadPartitionTable(), IoSetPartitionInformation(), and IoWritePartitionTable().
VOID HalpCalculateChsValues (IN PLARGE_INTEGER PartitionOffset, IN PLARGE_INTEGER PartitionLength, IN CCHAR ShiftCount, IN ULONG SectorsPerTrack, IN ULONG NumberOfTracks, IN ULONG ConventionalCylinders, OUT PPARTITION_DESCRIPTOR PartitionDescriptor)
Definition at line 568 of file drivesup.c.
References _LARGE_INTEGER::LowPart, PAGED_CODE, and _LARGE_INTEGER::QuadPart.
Referenced by IoWritePartitionTable().
NTSTATUS HalpDeleteMountLetter (IN UCHAR DriveLetter)
Definition at line 1194 of file drivesup.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTMGR_DELETE_POINTS, IoGetDeviceObjectPointer(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, MOUNTMGR_DEVICE_NAME, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PAGE_SIZE, PagedPool, PIRP, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, swprintf, _MOUNTMGR_MOUNT_POINT::SymbolicLinkNameLength, and _MOUNTMGR_MOUNT_POINT::SymbolicLinkNameOffset.
Referenced by IoAssignDriveLetters().
VOID HalpEnableAutomaticDriveLetterAssignment ()
Definition at line 1138 of file drivesup.c.
References Executive, FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTMGR_AUTO_DL_ASSIGNMENTS, IoGetDeviceObjectPointer(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), MOUNTMGR_DEVICE_NAME, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PIRP, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, and STATUS_PENDING.
Referenced by IoAssignDriveLetters().
NTSTATUS HalpGetFullGeometry (IN PDEVICE_OBJECT DeviceObject, IN PDISK_GEOMETRY Geometry, OUT PULONGLONG RealSectorCount)
Definition at line 3976 of file drivesup.c.
References ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_DISK_GET_DRIVE_GEOMETRY, IOCTL_DISK_GET_PARTITION_INFO, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _PARTITION_INFORMATION::PartitionLength, PIRP, _LARGE_INTEGER::QuadPart, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and VOID.
Referenced by IoReadPartitionTable().
BOOLEAN HalpIsOldStyleFloppy (IN PUNICODE_STRING DeviceName)
Definition at line 1383 of file drivesup.c.
References _FILE_OBJECT::DeviceObject, Executive, FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTDEV_QUERY_DEVICE_NAME, IoGetAttachedDeviceReference(), IoGetDeviceObjectPointer(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PIRP, _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_PENDING, and TRUE.
Referenced by IoAssignDriveLetters().
BOOLEAN HalpIsValidPartitionEntry (PPARTITION_DESCRIPTOR Entry, ULONGLONG MaxOffset, ULONGLONG MaxSector)
Definition at line 3879 of file drivesup.c.
References DPFLTR_FSTUB_ID, DPFLTR_TRACE_LEVEL, FALSE, GET_PARTITION_LENGTH, GET_STARTING_SECTOR, KdPrintEx, PAGED_CODE, PARTITION_ENTRY_UNUSED, _PARTITION_DESCRIPTOR::PartitionType, and TRUE.
Referenced by IoReadPartitionTable().
UCHAR HalpNextDriveLetter (IN PUNICODE_STRING DeviceName, IN PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, IN BOOLEAN UseHardLinksIfNecessary)
Definition at line 1046 of file drivesup.c.
References HalpNextMountLetter(), HalpSetMountLetter(), IoCreateSymbolicLink(), NT_SUCCESS, RtlAnsiStringToUnicodeString(), RtlEqualUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlPrefixUnicodeString(), swprintf, and TRUE.
Referenced by IoAssignDriveLetters().
NTSTATUS HalpNextMountLetter (IN PUNICODE_STRING DeviceName, OUT PUCHAR DriveLetter)
Definition at line 963 of file drivesup.c.
References _MOUNTMGR_DRIVE_LETTER_INFORMATION::CurrentDriveLetter, _MOUNTMGR_DRIVE_LETTER_TARGET::DeviceName, _MOUNTMGR_DRIVE_LETTER_TARGET::DeviceNameLength, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTMGR_NEXT_DRIVE_LETTER, IoGetDeviceObjectPointer(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), MOUNTMGR_DEVICE_NAME, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PagedPool, PIRP, RtlCopyMemory, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by HalpNextDriveLetter().
NTSTATUS HalpQueryDriveLayout (IN PUNICODE_STRING DeviceName, OUT PDRIVE_LAYOUT_INFORMATION * DriveLayout)
Definition at line 842 of file drivesup.c.
References ASSERT, _FILE_OBJECT::DeviceObject, ExAllocatePoolWithTag, Executive, ExFreePoolWithTag, FALSE, FILE_READ_ATTRIBUTES, FILE_REMOVABLE_MEDIA, FSTUB_TAG, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_DISK_GET_DRIVE_LAYOUT, IoGetAttachedDeviceReference(), IoGetDeviceObjectPointer(), KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PAGE_SIZE, PAGED_CODE, PIRP, _IO_STATUS_BLOCK::Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEDIA, STATUS_NO_MEMORY, and STATUS_PENDING.
Referenced by IoAssignDriveLetters().
NTSTATUS HalpQueryPartitionType (IN PUNICODE_STRING DeviceName, IN PDRIVE_LAYOUT_INFORMATION DriveLayout, OUT PULONG PartitionType)
Definition at line 729 of file drivesup.c.
References BOOTABLE_PARTITION, _FILE_OBJECT::DeviceObject, Executive, FALSE, FILE_READ_ATTRIBUTES, FILE_REMOVABLE_MEDIA, FT_PARTITION, GPT_PARTITION, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetAttachedDeviceReference(), IoGetDeviceObjectPointer(), IsEqualGUID, IsRecognizedPartition, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LOGICAL_PARTITION, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OTHER_PARTITION, PAGED_CODE, PIRP, PRIMARY_PARTITION, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and STATUS_SUCCESS.
Referenced by IoAssignDriveLetters().
NTSTATUS HalpSetMountLetter (IN PUNICODE_STRING DeviceName, IN UCHAR DriveLetter)
Definition at line 1290 of file drivesup.c.
References _UNICODE_STRING::Buffer, _MOUNTMGR_CREATE_POINT_INPUT::DeviceNameLength, _MOUNTMGR_CREATE_POINT_INPUT::DeviceNameOffset, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTMGR_CREATE_POINT, IoGetDeviceObjectPointer(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, MOUNTMGR_DEVICE_NAME, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PagedPool, PIRP, RtlCopyMemory, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, swprintf, _MOUNTMGR_CREATE_POINT_INPUT::SymbolicLinkNameLength, and _MOUNTMGR_CREATE_POINT_INPUT::SymbolicLinkNameOffset.
Referenced by HalpNextDriveLetter(), and IoAssignDriveLetters().
VOID FASTCALL IoAssignDriveLetters (IN struct _LOADER_PARAMETER_BLOCK * LoaderBlock, IN PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, OUT PSTRING NtSystemPathString)
Definition at line 1562 of file drivesup.c.
References _strupr(), ASSIGN_DRIVE_LETTERS_FAILED, BOOTABLE_PARTITION, _CONFIGURATION_INFORMATION::CdRomCount, DbgPrint(), _CONFIGURATION_INFORMATION::DiskCount, DiskPartitionName, ExAllocatePoolWithTag, ExFreePool(), FALSE, FILE_READ_DATA, FILE_SHARE_READ, FILE_SYNCHRONOUS_IO_NONALERT, _CONFIGURATION_INFORMATION::FloppyCount, FT_PARTITION, GPT_PARTITION, HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpIsOldStyleFloppy(), HalpNextDriveLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), InitializeObjectAttributes, IoCreateSymbolicLink(), IoGetConfigurationInformation(), IopComputeHarddiskDerangements(), IoRemoteBootClient, KeBugCheck(), LOGICAL_PARTITION, NonPagedPool, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, PAGED_CODE, PRIMARY_PARTITION, RtlAnsiStringToUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitString(), RtlInitUnicodeString(), RtlPrefixUnicodeString(), SETUPBLK_FLAGS_REMOTE_INSTALL, SETUPBLK_FLAGS_SYSPREP_INSTALL, sprintf(), strcpy(), strlen(), strrchr(), strstr(), swprintf, SYNCHRONIZE, TRUE, ZwClose(), and ZwOpenFile().
Referenced by IoInitSystem().
PULONG IopComputeHarddiskDerangements (IN ULONG DiskCount)
Definition at line 1453 of file drivesup.c.
References _STORAGE_DEVICE_NUMBER::DeviceNumber, _FILE_OBJECT::DeviceObject, ExAllocatePoolWithTag, Executive, FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_STORAGE_GET_DEVICE_NUMBER, IoGetAttachedDeviceReference(), IoGetDeviceObjectPointer(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PagedPool, PIRP, POOL_COLD_ALLOCATION, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, STATUS_PENDING, and swprintf.
Referenced by IoAssignDriveLetters().
NTSTATUS FASTCALL IoReadPartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN BOOLEAN ReturnRecognizedPartitions, OUT struct _DRIVE_LAYOUT_INFORMATION ** PartitionBuffer)
Definition at line 2136 of file drivesup.c.
References _PARTITION_DESCRIPTOR::ActiveFlag, BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, _PARTITION_INFORMATION::BootIndicator, _DISK_GEOMETRY::BytesPerSector, DPFLTR_ERROR_LEVEL, DPFLTR_FSTUB_ID, DPFLTR_TRACE_LEVEL, DPFLTR_WARNING_LEVEL, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, FstubDbgPrintDriveLayout, FstubFixupEfiPartition(), GET_PARTITION_LENGTH, GET_STARTING_SECTOR, HalExamineMBR(), HalpGetFullGeometry(), HalpIsValidPartitionEntry(), _PARTITION_INFORMATION::HiddenSectors, _LARGE_INTEGER::HighPart, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, IsContainerPartition, _BOOT_SECTOR_INFO::JumpByte, KdPrintEx, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, _DISK_GEOMETRY::MediaType, NonPagedPool, NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, NUM_PARTITION_TABLE_ENTRIES, PAGED_CODE, PARTITION_ACTIVE_FLAG, PARTITION_BUFFER_SIZE, PARTITION_ENTRY_UNUSED, PARTITION_FAT_16, PARTITION_TABLE_OFFSET, _PARTITION_INFORMATION::PartitionLength, _PARTITION_DESCRIPTOR::PartitionType, _PARTITION_INFORMATION::PartitionType, PIRP, _LARGE_INTEGER::QuadPart, _PARTITION_INFORMATION::RecognizedPartition, RemovableMedia, _PARTITION_INFORMATION::RewritePartition, RtlCopyMemory, RtlZeroMemory, SL_OVERRIDE_VERIFY_VOLUME, _PARTITION_INFORMATION::StartingOffset, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_DATA_DETECTED, STATUS_PENDING, STATUS_SUCCESS, TRUE, UInt32x32To64, and VOID.
NTSTATUS FASTCALL IoSetPartitionInformation (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG PartitionNumber, IN ULONG PartitionType)
Definition at line 2911 of file drivesup.c.
References BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, GET_STARTING_SECTOR, HalExamineMBR(), IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, IRP_MJ_WRITE, IsContainerPartition, KeInitializeEvent(), KeResetEvent(), KernelMode, KeWaitForSingleObject(), NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, NUM_PARTITION_TABLE_ENTRIES, PAGE_SIZE, PAGED_CODE, PARTITION_ENTRY_UNUSED, PARTITION_TABLE_OFFSET, _PARTITION_DESCRIPTOR::PartitionType, PIRP, _LARGE_INTEGER::QuadPart, SL_OVERRIDE_VERIFY_VOLUME, _IO_STATUS_BLOCK::Status, STATUS_BAD_MASTER_BOOT_RECORD, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, TRUE, UInt32x32To64, and VOID.
NTSTATUS FASTCALL IoWritePartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG SectorsPerTrack, IN ULONG NumberOfHeads, IN struct _DRIVE_LAYOUT_INFORMATION * PartitionBuffer)
Definition at line 3305 of file drivesup.c.
References BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, _PARTITION_INFORMATION::BootIndicator, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, FstubDbgPrintDriveLayout, HalExamineMBR(), HalpCalculateChsValues(), _PARTITION_INFORMATION::HiddenSectors, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, IRP_MJ_WRITE, IsContainerPartition, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, NUM_PARTITION_TABLE_ENTRIES, PAGE_SIZE, PAGED_CODE, PARTITION_ACTIVE_FLAG, PARTITION_ENTRY_UNUSED, PARTITION_FAT_16, PARTITION_TABLE_OFFSET, _PARTITION_TABLE::PartitionEntry, _PARTITION_INFORMATION::PartitionLength, _PARTITION_INFORMATION::PartitionNumber, _DISK_LAYOUT::PartitionTable, _PARTITION_INFORMATION::PartitionType, PIRP, _LARGE_INTEGER::QuadPart, _PARTITION_INFORMATION::RewritePartition, SL_OVERRIDE_VERIFY_VOLUME, _PARTITION_INFORMATION::StartingOffset, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_SUCCESS, _DISK_LAYOUT::TableCount, TRUE, VOID, WHICH_BIT, and xHalGetPartialGeometry().
VOID FASTCALL xHalGetPartialGeometry (IN PDEVICE_OBJECT DeviceObject, IN PULONG ConventionalCylinders, IN PLONGLONG DiskSize)
Definition at line 404 of file drivesup.c.
References _DISK_GEOMETRY::BytesPerSector, _DISK_GEOMETRY::Cylinders, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_DISK_GET_DRIVE_GEOMETRY, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, PIRP, _LARGE_INTEGER::QuadPart, _DISK_GEOMETRY::SectorsPerTrack, _IO_STATUS_BLOCK::Status, STATUS_PENDING, _DISK_GEOMETRY::TracksPerCylinder, and VOID.
Referenced by IoWritePartitionTable().
Variable Documentation
PCHAR DiskPartitionName = "\\Device\\Harddisk%d\\Partition%d" static
Definition at line 100 of file drivesup.c.
Referenced by IoAssignDriveLetters().
PCHAR RegistryKeyName = DISK_REGISTRY_KEY static
Definition at line 101 of file drivesup.c.