Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/fsrtlp.h File Reference
fsrtlp.h File Reference
#include <ntos.h>
#include <FsRtl.h>
#include <NtDdFt.h>
#include <zwapi.h>
Data Structures
struct _FS_FILTER_COMPLETION_NODE
struct _FS_FILTER_COMPLETION_STACK
struct _FS_FILTER_CTRL
union _UCHAR1
union _UCHAR2
union _UCHAR4
Macros
#define BooleanFlagOn(Flags, SingleFlag) ((BOOLEAN)(((Flags) & (SingleFlag)) != 0))
#define BytesFromSectors(sectors)
#define ClearFlag(F, SF)
#define CopyUchar1(Dst, Src)
#define CopyUchar2(Dst, Src)
#define CopyUchar4(Dst, Src)
#define DebugDump(STR, LEVEL, PTR) {NOTHING;}
#define DebugTrace(INDENT, LEVEL, X, Y) {NOTHING;}
#define FlagOn(Flags, SingleFlag) ((Flags) & (SingleFlag))
#define FS_FILTER_ALLOCATED_COMPLETION_STACK 0x00000001
#define FS_FILTER_CHANGED_DEVICE_STACKS 0x00000004
#define FS_FILTER_DEFAULT_STACK_SIZE 15
#define FS_FILTER_HAVE_COMPLETIONS(fsFilterCtrl) ((fsFilterCtrl)->CompletionStack.NextStackPosition > 0)
#define FS_FILTER_USED_RESERVE_POOL 0x00000002
#define FSRTL_FILTER_MEMORY_TAG 'gmSF'
#define FsRtlAllocatePool(PoolType, NumberOfBytes)
#define FsRtlAllocatePoolWithQuota(PoolType, NumberOfBytes)
#define FsRtlpAllocatePool(a, b) FsRtlAllocatePoolWithTag((a),(b),MODULE_POOL_TAG)
#define GET_COMPLETION_NODE(completionStack)
#define GET_FAST_IO_DISPATCH(DevObj) ((DevObj)->DriverObject->FastIoDispatch)
#define GET_FS_FILTER_CALLBACKS(DevObj) ((DevObj)->DriverObject->DriverExtension->FsFilterCallbacks)
#define LongAlign(Ptr)
#define POP_COMPLETION_NODE(completionStack)
#define PUSH_COMPLETION_NODE(completionStack)
#define QuadAlign(Ptr)
#define SectorAlign(Ptr)
#define SectorsFromBytes(bytes)
#define SetFlag(F, SF)
#define try_return(S) { S; goto try_exit; }
#define VALID_FAST_IO_DISPATCH_HANDLER(FastIoDispatchPtr, FieldName)
#define VALID_FS_FILTER_CALLBACK_HANDLER(FsFilterCallbackPtr, FieldName)
#define WordAlign(Ptr)
Typedefs
typedef struct _FS_FILTER_COMPLETION_NODE FS_FILTER_COMPLETION_NODE
typedef struct _FS_FILTER_COMPLETION_STACK FS_FILTER_COMPLETION_STACK
typedef struct _FS_FILTER_CTRL FS_FILTER_CTRL
typedef struct _FS_FILTER_COMPLETION_NODE * PFS_FILTER_COMPLETION_NODE
typedef struct _FS_FILTER_COMPLETION_STACK * PFS_FILTER_COMPLETION_STACK
typedef struct _FS_FILTER_CTRL * PFS_FILTER_CTRL
typedef union _UCHAR1 * PUCHAR1
typedef union _UCHAR2 * PUCHAR2
typedef union _UCHAR4 * PUCHAR4
typedef union _UCHAR1 UCHAR1
typedef union _UCHAR2 UCHAR2
typedef union _UCHAR4 UCHAR4
Functions
NTSTATUS FsFilterAllocateCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN CanFail, OUT PULONG AllocationSize)
VOID FsFilterCtrlFree (IN PFS_FILTER_CTRL FsFilterCtrl)
NTSTATUS FsFilterCtrlInit (IN OUT PFS_FILTER_CTRL FsFilterCtrl, IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, IN PDEVICE_OBJECT BaseFsDeviceObject, IN PFILE_OBJECT FileObject, IN BOOLEAN CanFail)
VOID FsFilterFreeCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl)
VOID FsFilterGetCallbacks (IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, OUT PFS_FILTER_CALLBACK *PreOperationCallback, OUT PFS_FILTER_COMPLETION_CALLBACK *PostOperationCallback)
NTSTATUS FsFilterInit ()
NTSTATUS FsFilterPerformCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN AllowFilterToFail, IN BOOLEAN AllowBaseFsToFail, OUT BOOLEAN *BaseFsFailedOp)
VOID FsFilterPerformCompletionCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN NTSTATUS OperationStatus)
VOID FsRtlInitializeFileLocks (VOID)
VOID FsRtlInitializeLargeMcbs (VOID)
VOID FsRtlInitializeTunnels (VOID)
NTSTATUS FsRtlInitializeWorkerThread (VOID)
Macro Definition Documentation
#define BooleanFlagOn (Flags, SingleFlag) ((BOOLEAN)(((Flags) & (SingleFlag)) != 0))
Definition at line 174 of file fsrtlp.h.
#define BytesFromSectors (sectors)
Value:
(\
    (sectors) * 512                 \
    )
Definition at line 235 of file fsrtlp.h.
#define ClearFlag (F, SF)
Value:
{ \
    (F) &= ~(SF);         \
}
Definition at line 180 of file fsrtlp.h.
#define CopyUchar1 (Dst, Src)
Value:
{                                \
    *((UCHAR1 *)(Dst)) = *((UNALIGNED UCHAR1 *)(Src)); \
    }
Definition at line 263 of file fsrtlp.h.
#define CopyUchar2 (Dst, Src)
Value:
{                                \
    *((UCHAR2 *)(Dst)) = *((UNALIGNED UCHAR2 *)(Src)); \
    }
Definition at line 271 of file fsrtlp.h.
#define CopyUchar4 (Dst, Src)
Value:
{                                \
    *((UCHAR4 *)(Dst)) = *((UNALIGNED UCHAR4 *)(Src)); \
    }
Definition at line 279 of file fsrtlp.h.
#define DebugDump (STR, LEVEL, PTR) {NOTHING;}
Definition at line 138 of file fsrtlp.h.
#define DebugTrace (INDENT, LEVEL, X, Y) {NOTHING;}
Definition at line 136 of file fsrtlp.h.
#define FlagOn (Flags, SingleFlag) ((Flags) & (SingleFlag))
Definition at line 172 of file fsrtlp.h.
#define FS_FILTER_ALLOCATED_COMPLETION_STACK 0x00000001
Definition at line 374 of file fsrtlp.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterCtrlFree(), and FsFilterFreeCompletionStack().
#define FS_FILTER_CHANGED_DEVICE_STACKS 0x00000004
Definition at line 376 of file fsrtlp.h.
Referenced by FsFilterPerformCallbacks(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
#define FS_FILTER_DEFAULT_STACK_SIZE 15
Definition at line 348 of file fsrtlp.h.
Referenced by FsFilterCtrlInit().
#define FS_FILTER_HAVE_COMPLETIONS (fsFilterCtrl) ((fsFilterCtrl)->CompletionStack.NextStackPosition > 0)
Definition at line 422 of file fsrtlp.h.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
#define FS_FILTER_USED_RESERVE_POOL 0x00000002
Definition at line 375 of file fsrtlp.h.
Referenced by FsFilterAllocateCompletionStack(), and FsFilterFreeCompletionStack().
#define FSRTL_FILTER_MEMORY_TAG 'gmSF'
Definition at line 337 of file fsrtlp.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterInit(), and FsRtlRegisterFileSystemFilterCallbacks().
#define FsRtlAllocatePool (PoolType, NumberOfBytes)
Value:
ExAllocatePoolWithTag((POOL_TYPE)((PoolType) | POOL_RAISE_IF_ALLOCATION_FAILURE), \
                          NumberOfBytes,                                      \
                          'trSF')
Definition at line 33 of file fsrtlp.h.
Referenced by FsRtlInitSystem().
#define FsRtlAllocatePoolWithQuota (PoolType, NumberOfBytes)
Value:
ExAllocatePoolWithQuotaTag((POOL_TYPE)((PoolType) | POOL_RAISE_IF_ALLOCATION_FAILURE), \
                               NumberOfBytes,                                 \
                               'trSF')
Definition at line 39 of file fsrtlp.h.
#define FsRtlpAllocatePool (a, b) FsRtlAllocatePoolWithTag((a),(b),MODULE_POOL_TAG)
Definition at line 44 of file fsrtlp.h.
Referenced by FsRtlAddLargeEntry(), FsRtlAllocateOplock(), FsRtlCancelNotify(), FsRtlInitializeBaseMcb(), FsRtlIsDbcsInExpression(), FsRtlIsNameInExpressionPrivate(), FsRtlNotifyFilterChangeDirectory(), FsRtlNotifyFilterReportChange(), FsRtlNotifyInitializeSync(), FsRtlTruncateBaseMcb(), and FsRtlWaitOnIrp().
#define GET_COMPLETION_NODE (completionStack)
Value:
(ASSERT((completionStack)->NextStackPosition > 0),\
     (&(completionStack)->Stack[(completionStack)->NextStackPosition-1]))
Definition at line 418 of file fsrtlp.h.
Referenced by FsFilterPerformCompletionCallbacks().
#define GET_FAST_IO_DISPATCH (DevObj) ((DevObj)->DriverObject->FastIoDispatch)
Definition at line 314 of file fsrtlp.h.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
#define GET_FS_FILTER_CALLBACKS (DevObj) ((DevObj)->DriverObject->DriverExtension->FsFilterCallbacks)
Definition at line 317 of file fsrtlp.h.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
#define LongAlign (Ptr)
Value:
(\
    ((((ULONG_PTR)(Ptr)) + 3) & -4) \
    )
Definition at line 198 of file fsrtlp.h.
Referenced by FsRtlNotifyFilterReportChange(), and RtlCopySidAndAttributesArray().
#define POP_COMPLETION_NODE (completionStack)
Value:
(ASSERT((completionStack)->NextStackPosition > 0), \
     ((completionStack)->NextStackPosition--))
Definition at line 414 of file fsrtlp.h.
Referenced by FsFilterPerformCallbacks(), and FsFilterPerformCompletionCallbacks().
#define PUSH_COMPLETION_NODE (completionStack)
Value:
(((completionStack)->NextStackPosition < (completionStack)->StackLength) ? \
        &(completionStack)->Stack[(completionStack)->NextStackPosition++] : \
        (ASSERT( FALSE ), NULL) )
Definition at line 409 of file fsrtlp.h.
Referenced by FsFilterPerformCallbacks().
#define QuadAlign (Ptr)
Value:
(\
    ((((ULONG_PTR)(Ptr)) + 7) & -8) \
    )
Definition at line 207 of file fsrtlp.h.
#define SectorAlign (Ptr)
Value:
(\
    ((((ULONG_PTR)(Ptr)) + 511) & -512) \
    )
Definition at line 216 of file fsrtlp.h.
#define SectorsFromBytes (bytes)
Value:
(\
    ((bytes) + 511) / 512         \
    )
Definition at line 226 of file fsrtlp.h.
#define SetFlag (F, SF)
Value:
{ \
    (F) |= (SF);        \
}
Definition at line 176 of file fsrtlp.h.
#define try_return (S) { S; goto try_exit; }
Definition at line 312 of file fsrtlp.h.
#define VALID_FAST_IO_DISPATCH_HANDLER (FastIoDispatchPtr, FieldName)
Value:
(((FastIoDispatchPtr) != NULL) && \
     (((FastIoDispatchPtr)->SizeOfFastIoDispatch) >= \
      (FIELD_OFFSET(FAST_IO_DISPATCH, FieldName) + sizeof(VOID *))) && \
     ((FastIoDispatchPtr)->FieldName != NULL))
Definition at line 325 of file fsrtlp.h.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
#define VALID_FS_FILTER_CALLBACK_HANDLER (FsFilterCallbackPtr, FieldName)
Value:
(((FsFilterCallbackPtr) != NULL) && \
     (((FsFilterCallbackPtr)->SizeOfFsFilterCallbacks) >= \
      (FIELD_OFFSET(FS_FILTER_CALLBACKS, FieldName) + sizeof(VOID *))) && \
     ((FsFilterCallbackPtr)->FieldName != NULL))
Definition at line 331 of file fsrtlp.h.
Referenced by FsFilterGetCallbacks(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
#define WordAlign (Ptr)
Value:
(\
    ((((ULONG_PTR)(Ptr)) + 1) & -2) \
    )
Definition at line 189 of file fsrtlp.h.
Typedef Documentation
typedef struct _FS_FILTER_COMPLETION_NODE FS_FILTER_COMPLETION_NODE
typedef struct _FS_FILTER_COMPLETION_STACK FS_FILTER_COMPLETION_STACK
typedef struct _FS_FILTER_CTRL FS_FILTER_CTRL
typedef struct _FS_FILTER_COMPLETION_NODE * PFS_FILTER_COMPLETION_NODE
typedef struct _FS_FILTER_COMPLETION_STACK * PFS_FILTER_COMPLETION_STACK
typedef struct _FS_FILTER_CTRL * PFS_FILTER_CTRL
typedef union _UCHAR1 * PUCHAR1
typedef union _UCHAR2 * PUCHAR2
typedef union _UCHAR4 * PUCHAR4
typedef union _UCHAR1 UCHAR1
typedef union _UCHAR2 UCHAR2
typedef union _UCHAR4 UCHAR4
Function Documentation
NTSTATUS FsFilterAllocateCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN CanFail, OUT PULONG AllocationSize)
Definition at line 108 of file fsfilter.c.
References AcquireOpsEvent, AcquireOpsReservePool, ASSERT, ASSERTMSG, ExAllocatePoolWithTag, Executive, FALSE, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_ALLOCATED_COMPLETION_STACK, FS_FILTER_RELEASE_FOR_CC_FLUSH, FS_FILTER_RELEASE_FOR_MOD_WRITE, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_USED_RESERVE_POOL, FSRTL_FILTER_MEMORY_TAG, KernelMode, KeWaitForSingleObject(), NonPagedPool, NULL, _FS_FILTER_RESERVE::Owner, PsGetCurrentThread(), ReleaseOpsEvent, ReleaseOpsReservePool, SetFlag, _FS_FILTER_RESERVE::Stack, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by FsFilterCtrlInit().
VOID FsFilterCtrlFree (IN PFS_FILTER_CTRL FsFilterCtrl)
Definition at line 434 of file fsfilter.c.
References ASSERT, FlagOn, FS_FILTER_ALLOCATED_COMPLETION_STACK, FsFilterFreeCompletionStack(), and NULL.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTSTATUS FsFilterCtrlInit (IN OUT PFS_FILTER_CTRL FsFilterCtrl, IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, IN PDEVICE_OBJECT BaseFsDeviceObject, IN PFILE_OBJECT FileObject, IN BOOLEAN CanFail)
Definition at line 324 of file fsfilter.c.
References ASSERT, _FS_FILTER_CALLBACK_DATA::DeviceObject, _FS_FILTER_CALLBACK_DATA::FileObject, FS_FILTER_DEFAULT_STACK_SIZE, FsFilterAllocateCompletionStack(), NT_SUCCESS, NULL, _FS_FILTER_CALLBACK_DATA::Operation, RtlZeroMemory, _FS_FILTER_CALLBACK_DATA::SizeOfFsFilterCallbackData, Status, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
VOID FsFilterFreeCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl)
Definition at line 231 of file fsfilter.c.
References AcquireOpsEvent, ASSERT, ASSERTMSG, CONTAINING_RECORD, ExFreePoolWithTag, FALSE, FlagOn, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_ALLOCATED_COMPLETION_STACK, FS_FILTER_RELEASE_FOR_CC_FLUSH, FS_FILTER_RELEASE_FOR_MOD_WRITE, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_USED_RESERVE_POOL, FSRTL_FILTER_MEMORY_TAG, IO_NO_INCREMENT, KeSetEvent(), NULL, _FS_FILTER_RESERVE::Owner, and ReleaseOpsEvent.
Referenced by FsFilterCtrlFree().
VOID FsFilterGetCallbacks (IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, OUT PFS_FILTER_CALLBACK * PreOperationCallback, OUT PFS_FILTER_COMPLETION_CALLBACK * PostOperationCallback)
Definition at line 468 of file fsfilter.c.
References ASSERT, FALSE, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_RELEASE_FOR_CC_FLUSH, FS_FILTER_RELEASE_FOR_MOD_WRITE, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, NULL, _FS_FILTER_CALLBACKS::PostAcquireForCcFlush, _FS_FILTER_CALLBACKS::PostAcquireForModifiedPageWriter, _FS_FILTER_CALLBACKS::PostAcquireForSectionSynchronization, _FS_FILTER_CALLBACKS::PostReleaseForCcFlush, _FS_FILTER_CALLBACKS::PostReleaseForModifiedPageWriter, _FS_FILTER_CALLBACKS::PostReleaseForSectionSynchronization, _FS_FILTER_CALLBACKS::PreAcquireForCcFlush, _FS_FILTER_CALLBACKS::PreAcquireForModifiedPageWriter, _FS_FILTER_CALLBACKS::PreAcquireForSectionSynchronization, _FS_FILTER_CALLBACKS::PreReleaseForCcFlush, _FS_FILTER_CALLBACKS::PreReleaseForModifiedPageWriter, _FS_FILTER_CALLBACKS::PreReleaseForSectionSynchronization, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by FsFilterPerformCallbacks().
NTSTATUS FsFilterInit ()
Definition at line 56 of file fsfilter.c.
References ExAllocatePoolWithTag, ExFreePoolWithTag, FSRTL_FILTER_MEMORY_TAG, KeInitializeEvent(), NonPagedPool, NULL, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, SynchronizationEvent, and TRUE.
Referenced by FsRtlInitSystem().
NTSTATUS FsFilterPerformCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN AllowFilterToFail, IN BOOLEAN AllowBaseFsToFail, OUT BOOLEAN * BaseFsFailedOp)
Definition at line 639 of file fsfilter.c.
References ASSERT, _FS_FILTER_COMPLETION_NODE::CompletionCallback, _FS_FILTER_COMPLETION_NODE::CompletionContext, _FS_FILTER_COMPLETION_NODE::DeviceObject, _FS_FILTER_CALLBACK_DATA::DeviceObject, FALSE, FILE_SYSTEM, _FS_FILTER_COMPLETION_NODE::FileObject, _FS_FILTER_CALLBACK_DATA::FileObject, FS_FILTER_CHANGED_DEVICE_STACKS, FsFilterGetCallbacks(), KdPrint, KeBugCheckEx(), NOTHING, NT_SUCCESS, NULL, _FS_FILTER_CALLBACK_DATA::Operation, POP_COMPLETION_NODE, PUSH_COMPLETION_NODE, SetFlag, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
VOID FsFilterPerformCompletionCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN NTSTATUS OperationStatus)
Definition at line 960 of file fsfilter.c.
References ASSERT, _FS_FILTER_COMPLETION_NODE::CompletionCallback, _FS_FILTER_COMPLETION_NODE::CompletionContext, _FS_FILTER_COMPLETION_NODE::DeviceObject, _FS_FILTER_CALLBACK_DATA::DeviceObject, _FS_FILTER_COMPLETION_NODE::FileObject, _FS_FILTER_CALLBACK_DATA::FileObject, GET_COMPLETION_NODE, _FS_FILTER_COMPLETION_STACK::NextStackPosition, NULL, and POP_COMPLETION_NODE.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
VOID FsRtlInitializeFileLocks (VOID)
Definition at line 712 of file filelock.c.
References ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), FsRtlExclusiveLockLookasideList, FsRtlFileLockCancelCollideLock, FsRtlFileLockLookasideList, FsRtlLockInfoLookasideList, FsRtlLockTreeNodeLookasideList, FsRtlSharedLockLookasideList, FsRtlWaitingLockLookasideList, KeInitializeGuardedMutex(), KeInitializeSpinLock(), _SINGLE_LIST_ENTRY::Next, NULL, TAG_EXCLUSIVE_LOCK, TAG_FILE_LOCK, TAG_LOCK_INFO, TAG_LOCKTREE_NODE, TAG_SHARED_LOCK, and TAG_WAITING_LOCK.
Referenced by FsRtlInitSystem().
VOID FsRtlInitializeLargeMcbs (VOID)
Definition at line 481 of file largemcb.c.
References ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), FsRtlFastMutexLookasideList, FsRtlFirstMappingLookasideList, INITIAL_MAXIMUM_PAIR_COUNT, NULL, and POOL_RAISE_IF_ALLOCATION_FAILURE.
Referenced by FsRtlInitSystem().
VOID FsRtlInitializeTunnels (VOID)
Definition at line 360 of file tunnel.c.
References _UNICODE_STRING::Buffer, ExInitializePagedLookasideList(), FsRtlGetTunnelParameterValue(), _UNICODE_STRING::Length, LOOKASIDE_NODE_SIZE, MAX_LOOKASIDE_DEPTH, _UNICODE_STRING::MaximumLength, MAXUSHORT, MmIsThisAnNtAsSystem(), NULL, PAGED_CODE, TUNNEL_AGE_VALUE_NAME, TUNNEL_SIZE_VALUE_NAME, TunnelLookasideList, TunnelMaxAge, TunnelMaxEntries, and VOID.
Referenced by FsRtlInitSystem().
NTSTATUS FsRtlInitializeWorkerThread (VOID)
Definition at line 108 of file stackovf.c.
References FsRtlPostPagingFileStackOverflow(), FsRtlPostStackOverflow(), FsRtlWorkerThread(), InitializeObjectAttributes, KeInitializeEvent(), KeInitializeQueue(), NT_SUCCESS, NULL, PsCreateSystemThread(), Status, STATUS_SUCCESS, SynchronizationEvent, THREAD_ALL_ACCESS, TRUE, ULongToPtr, and ZwClose().
Referenced by FsRtlInitSystem().