Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/buildmdl.c File Reference
buildmdl.c File Reference
#include "mi.h"
Data Structures
struct _MI_READ_INFO
Typedefs
typedef struct _MI_READ_INFO MI_READ_INFO
typedef struct _MI_READ_INFO * PMI_READ_INFO
Functions
NTSTATUS MiCcCompletePrefetchIos (PMI_READ_INFO MiReadInfo)
NTSTATUS MiCcCompletePrefetchIos (IN PMI_READ_INFO MiReadInfo)
NTSTATUS MiCcPrepareReadInfo (IN PMI_READ_INFO MiReadInfo)
NTSTATUS MiCcPutPagesInTransition (IN PMI_READ_INFO MiReadInfo)
VOID MiCcReleasePrefetchResources (IN PMI_READ_INFO MiReadInfo, IN NTSTATUS Status)
VOID MiPfFreeDummyPage (IN PMMPFN DummyPagePfn)
VOID MiRemoveUserPages (VOID)
NTSTATUS MmPrefetchPagesIntoLockedMdl (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN SIZE_T Length, OUT PMDL *MdlOut)
Typedef Documentation
typedef struct _MI_READ_INFO MI_READ_INFO
typedef struct _MI_READ_INFO * PMI_READ_INFO
Function Documentation
NTSTATUS MiCcCompletePrefetchIos (PMI_READ_INFO MiReadInfo)
Referenced by MmPrefetchPagesIntoLockedMdl().
NTSTATUS MiCcCompletePrefetchIos (IN PMI_READ_INFO MiReadInfo)
Definition at line 1290 of file buildmdl.c.
References ASSERT, _MMINPAGE_SUPPORT::BasePte, _MDL::ByteCount, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, _MMPFN::InPageError, KeGetCurrentIrql(), _MMINPAGE_SUPPORT::ListEntry, MI_EXTRACT_PREFETCH_MDL, MI_MAGIC_AWE_PTEFRAME, MI_PF_DUMMY_PAGE_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiFreeInPageSupportBlock(), MiInsertPageInFreeList(), MiRestoreTransitionPte(), MiUnlinkPageFromList(), MiWaitForInPageComplete(), _SINGLE_LIST_ENTRY::Next, NULL, NumberOfBytes, PAGE_SIZE, _MMPFNENTRY::PageLocation, PASSIVE_LEVEL, _MMINPAGE_SUPPORT::Pfn, PREFETCH_PROCESS, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, StandbyPageList, STATUS_SUCCESS, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMINPAGE_SUPPORT::WaitCount.
NTSTATUS MiCcPrepareReadInfo (IN PMI_READ_INFO MiReadInfo)
Definition at line 333 of file buildmdl.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMINPAGE_SUPPORT::BasePte, BYTE_OFFSET, _MMINPAGE_SUPPORT::e1, _CONTROL_AREA::FilePointer, _MMINPAGE_SUPPORT::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, KeGetCurrentIrql(), KeMemoryBarrier(), _LARGE_INTEGER::LowPart, MDL_PAGES_LOCKED, _MDL::MdlFlags, MiAddViewsForSectionWithPfn(), MiGetInPageSupportBlock(), MiRemoveUserPages(), MM_NOIRQL, MmCreateMdl(), _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NT_SUCCESS, NULL, PAGE_SHIFT, PASSIVE_LEVEL, _MMSECTION_FLAGS::PhysicalMemory, _MMINPAGE_FLAGS::PrefetchMdlHighBits, _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _MMINPAGE_SUPPORT::ReadOffset, _MMSECTION_FLAGS::Rom, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, _MSUBSECTION::SubsectionBase, TRUE, _CONTROL_AREA::u, and _MMINPAGE_SUPPORT::u1.
Referenced by MmPrefetchPagesIntoLockedMdl().
NTSTATUS MiCcPutPagesInTransition (IN PMI_READ_INFO MiReadInfo)
Definition at line 591 of file buildmdl.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, ASSERT64, _MMINPAGE_SUPPORT::BasePte, BYTE_OFFSET, _MDL::ByteCount, _MDL::ByteOffset, BYTES_TO_PAGES, _MMINPAGE_FLAGS::Completed, _KPROCESS::DirectoryTableBase, _MMPFN::e1, _MMINPAGE_SUPPORT::e1, _MMPFN::e2, _MMPFN::Event, _MMINPAGE_SUPPORT::Event, ExFreePool(), FALSE, _MMINPAGE_SUPPORT::FilePointer, _MMPTE::Hard, _IO_STATUS_BLOCK::Information, _MMPFN::InPageError, InterlockedExchangeAdd(), InterlockedIncrement, IoPageRead(), _MMINPAGE_SUPPORT::IoStatus, KeDelayExecutionThread(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KernelMode, KeSetEvent(), LOCK_PFN, _MMPTE::Long, MAXUSHORT, _MMINPAGE_SUPPORT::Mdl, MDL_IO_PAGE_READ, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_DECREMENT_RESIDENT_AVAILABLE, MI_EXTRACT_PREFETCH_MDL, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_TRANSITION_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PAGE_COLOR_VA_PROCESS, MI_PF_DUMMY_PAGE_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_WRITE_INVALID_PTE, MiEnsureAvailablePageOrWait(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiInitializePfnForOtherProcess(), MiMakeSystemAddressValidPfn(), MiRemoveAnyPage(), MM_HIGH_LIMIT, MM_MAXIMUM_READ_CLUSTER_SIZE, MM_RESAVAIL_ALLOCATE_BUILDMDL, MM_RESAVAIL_FREE_BUILDMDL_EXCESS, MmAvailablePages, MmHalfSecond, MmPagedPoolEnd, MmPagedPoolStart, _KPRCB::MmPageReadCount, _KPRCB::MmPageReadIoCount, MmSpecialPoolEnd, MmSpecialPoolStart, _EPROCESS::NextPageColor, NT_SUCCESS, NULL, _MMINPAGE_SUPPORT::Page, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PASSIVE_LEVEL, _EPROCESS::Pcb, _MMINPAGE_SUPPORT::Pfn, _MMINPAGE_FLAGS::PrefetchMdlHighBits, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), PsGetCurrentThread(), PsInitialSystemProcess, _MMPFN::PteAddress, _MMPFN::PteFrame, _LARGE_INTEGER::QuadPart, _MMPFNENTRY::ReadInProgress, _MMINPAGE_SUPPORT::ReadOffset, RtlCopyMemory, RtlFillMemoryUlong(), _MMPFN::ShareCount, _MDL::Size, _MMPTE::Soft, _MDL::StartVa, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_ISSUE_PAGING_IO, STATUS_SUCCESS, _MMINPAGE_SUPPORT::Thread, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _MMPFN::u1, _MMINPAGE_SUPPORT::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _MMINPAGE_SUPPORT::WaitCount, and ZeroedPageList.
Referenced by MmPrefetchPagesIntoLockedMdl().
VOID MiCcReleasePrefetchResources (IN PMI_READ_INFO MiReadInfo, IN NTSTATUS Status)
Definition at line 264 of file buildmdl.c.
References ExFreePool(), MiFreeInPageSupportBlock(), MiPfFreeDummyPage(), MiRemoveViewsFromSectionWithPfn(), _MSUBSECTION::NextSubsection, NT_SUCCESS, NULL, and _MSUBSECTION::PtesInSubsection.
Referenced by MmPrefetchPagesIntoLockedMdl().
VOID MiPfFreeDummyPage (IN PMMPFN DummyPagePfn)
Referenced by MiCcReleasePrefetchResources().
VOID MiRemoveUserPages (VOID)
Referenced by MiCcPrepareReadInfo().
NTSTATUS MmPrefetchPagesIntoLockedMdl (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN SIZE_T Length, OUT PMDL * MdlOut)
Definition at line 98 of file buildmdl.c.
References _ETHREAD::ActiveFaultCount, _ETHREAD::ApcNeeded, _MI_READ_INFO::ApiMdl, ASSERT, FALSE, _MI_READ_INFO::FileObject, _MI_READ_INFO::FileOffset, FileOffset, _MI_READ_INFO::InPageSupport, IoRetryIrpCompletions(), KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), _MI_READ_INFO::LengthInBytes, MiCcCompletePrefetchIos(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiCcReleasePrefetchResources(), NT_SUCCESS, NULL, PASSIVE_LEVEL, PsGetCurrentThread(), RtlZeroMemory, STATUS_ISSUE_PAGING_IO, _ETHREAD::Tcb, and TRUE.