Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/security.c File Reference
security.c File Reference
#include "psp.h"
Functions
NTSTATUS PsAssignImpersonationToken (__in PETHREAD Thread, __in HANDLE Token)
VOID PsDereferenceImpersonationToken (__in PACCESS_TOKEN ImpersonationToken)
VOID PsDereferencePrimaryToken (__in PACCESS_TOKEN PrimaryToken)
BOOLEAN PsDisableImpersonation (__inout PETHREAD Thread, __inout PSE_IMPERSONATION_STATE ImpersonationState)
NTSTATUS PsImpersonateClient (__inout PETHREAD Thread, __in PACCESS_TOKEN Token, __in BOOLEAN CopyOnOpen, __in BOOLEAN EffectiveOnly, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
NTSTATUS PsOpenTokenOfJobObject (IN HANDLE JobObject, OUT PACCESS_TOKEN *Token)
NTSTATUS PsOpenTokenOfProcess (IN HANDLE ProcessHandle, OUT PACCESS_TOKEN *Token)
NTSTATUS PsOpenTokenOfThread (IN HANDLE ThreadHandle, IN BOOLEAN OpenAsSelf, OUT PACCESS_TOKEN *Token, OUT PBOOLEAN CopyOnOpen, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
NTSTATUS PspAssignPrimaryToken (IN PEPROCESS Process, IN HANDLE Token OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL)
VOID PspDeleteProcessSecurity (IN PEPROCESS Process)
VOID PspDeleteThreadSecurity (IN PETHREAD Thread)
NTSTATUS PspInitializeProcessSecurity (IN PEPROCESS Parent OPTIONAL, IN PEPROCESS Child)
VOID PspInitializeThreadSecurity (IN PEPROCESS Process, IN PETHREAD Thread)
LOGICAL PspSinglePrivCheck (IN LUID PrivilegeValue, IN KPROCESSOR_MODE PreviousMode, OUT PPRIV_CHECK_CTX PrivCtx)
VOID PspSinglePrivCheckAudit (IN LOGICAL PrivUsed, IN PPRIV_CHECK_CTX PrivCtx)
NTSTATUS PspWriteTebImpersonationInfo (IN PETHREAD Thread, IN PETHREAD CurrentThread)
PACCESS_TOKEN PsReferenceEffectiveToken (IN PETHREAD Thread, OUT PTOKEN_TYPE TokenType, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
PACCESS_TOKEN PsReferenceImpersonationToken (__inout PETHREAD Thread, __out PBOOLEAN CopyOnOpen, __out PBOOLEAN EffectiveOnly, __out PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
PACCESS_TOKEN PsReferencePrimaryToken (__inout PEPROCESS Process)
VOID PsRestoreImpersonation (__inout PETHREAD Thread, __in PSE_IMPERSONATION_STATE ImpersonationState)
VOID PsRevertThreadToSelf (__inout PETHREAD Thread)
VOID PsRevertToSelf ()
Function Documentation
NTSTATUS PsAssignImpersonationToken (__in PETHREAD Thread, __in HANDLE Token)
Definition at line 1791 of file security.c.
References ARGUMENT_PRESENT, FALSE, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PsImpersonateClient(), PsRevertThreadToSelf(), SeTokenImpersonationLevel(), SeTokenObjectType, SeTokenType(), Status, STATUS_BAD_TOKEN_TYPE, STATUS_SUCCESS, _ETHREAD::Tcb, TOKEN_IMPERSONATE, and TokenImpersonation.
Referenced by NtSetInformationThread().
VOID PsDereferenceImpersonationToken (__in PACCESS_TOKEN ImpersonationToken)
Definition at line 1951 of file security.c.
References NULL, ObDereferenceObject(), and PAGED_CODE.
Referenced by PsImpersonateClient(), and PsOpenTokenOfThread().
VOID PsDereferencePrimaryToken (__in PACCESS_TOKEN PrimaryToken)
Definition at line 1922 of file security.c.
References ObDereferenceObject(), and PAGED_CODE.
BOOLEAN PsDisableImpersonation (__inout PETHREAD Thread, __inout PSE_IMPERSONATION_STATE ImpersonationState)
Definition at line 998 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, FALSE, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PS_TEST_CLEAR_BITS, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), SecurityAnonymous, ThreadObject, _PS_IMPERSONATION_INFORMATION::Token, and TRUE.
Referenced by NtOpenThreadTokenEx().
NTSTATUS PsImpersonateClient (__inout PETHREAD Thread, __in PACCESS_TOKEN Token, __in BOOLEAN CopyOnOpen, __in BOOLEAN EffectiveOnly, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 663 of file security.c.
References ARGUMENT_PRESENT, ASSERT, _PS_JOB_TOKEN_FILTER::CapturedGroupCount, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedPrivilegeCount, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedSidCount, _PS_JOB_TOKEN_FILTER::CapturedSids, _PS_JOB_TOKEN_FILTER::CapturedSidsLength, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, _EJOB::Filter, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, InterlockedCompareExchangePointer, _EPROCESS::Job, JOB_OBJECT_SECURITY_NO_ADMIN, JOB_OBJECT_SECURITY_RESTRICTED_TOKEN, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PagedPool, PROTECTED_POOL, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PS_SET_BITS, PsDereferenceImpersonationToken(), PsDereferencePrimaryTokenEx, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), PspWriteTebImpersonationInfo(), PsReferencePrimaryToken(), SeCopyClientToken(), SecurityIdentification, _EJOB::SecurityLimitFlags, SeFastFilterToken(), SeTokenCanImpersonate(), SeTokenIsAdmin(), SeTokenIsRestricted(), Status, STATUS_ACCESS_DENIED, STATUS_NO_MEMORY, STATUS_SUCCESS, THREAD_TO_PROCESS, ThreadObject, _PS_IMPERSONATION_INFORMATION::Token, and TRUE.
Referenced by NtImpersonateAnonymousToken(), NtOpenThreadTokenEx(), PsAssignImpersonationToken(), and SeImpersonateClientEx().
NTSTATUS PsOpenTokenOfJobObject (IN HANDLE JobObject, OUT PACCESS_TOKEN * Token)
Definition at line 604 of file security.c.
References JOB_OBJECT_QUERY, KeGetPreviousMode, NT_SUCCESS, NULL, ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PsJobType, Status, STATUS_NO_TOKEN, and _EJOB::Token.
NTSTATUS PsOpenTokenOfProcess (IN HANDLE ProcessHandle, OUT PACCESS_TOKEN * Token)
Definition at line 512 of file security.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_QUERY_INFORMATION, PsProcessType, PsReferencePrimaryToken(), Status, and STATUS_SUCCESS.
Referenced by NtOpenProcessTokenEx().
NTSTATUS PsOpenTokenOfThread (IN HANDLE ThreadHandle, IN BOOLEAN OpenAsSelf, OUT PACCESS_TOKEN * Token, OUT PBOOLEAN CopyOnOpen, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 371 of file security.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsDereferenceImpersonationToken(), PsReferenceImpersonationToken(), PsThreadType, SecurityAnonymous, Status, STATUS_CANT_OPEN_ANONYMOUS, STATUS_NO_TOKEN, STATUS_SUCCESS, THREAD_QUERY_INFORMATION, and UNREFERENCED_PARAMETER.
NTSTATUS PspAssignPrimaryToken (IN PEPROCESS Process, IN HANDLE Token OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL)
Definition at line 1485 of file security.c.
References KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PspLockProcessSecurityExclusive(), PspUnlockProcessSecurityExclusive(), SeExchangePrimaryToken(), SeTokenObjectType, Status, _ETHREAD::Tcb, and TOKEN_ASSIGN_PRIMARY.
Referenced by PspSetPrimaryToken().
VOID PspDeleteProcessSecurity (IN PEPROCESS Process)
Definition at line 1436 of file security.c.
References ExFastRefObjectNull(), PAGED_CODE, and SeDeassignPrimaryToken().
Referenced by PspProcessDelete().
VOID PspDeleteThreadSecurity (IN PETHREAD Thread)
Definition at line 1650 of file security.c.
References ExFreePoolWithTag, NULL, ObDereferenceObject(), PAGED_CODE, PROTECTED_POOL, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by PspThreadDelete().
NTSTATUS PspInitializeProcessSecurity (IN PEPROCESS Parent OPTIONAL, IN PEPROCESS Child)
Definition at line 1342 of file security.c.
References ARGUMENT_PRESENT, MmGetSessionId(), NT_SUCCESS, NULL, ObInitializeFastReference(), PAGED_CODE, PsDereferencePrimaryTokenEx, PspBootAccessToken, PsReferencePrimaryToken(), SeAssignPrimaryToken(), SeSubProcessToken(), Status, STATUS_SUCCESS, and TRUE.
Referenced by PspCreateProcess().
VOID PspInitializeThreadSecurity (IN PEPROCESS Process, IN PETHREAD Thread)
Definition at line 1607 of file security.c.
References NULL, PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, and UNREFERENCED_PARAMETER.
LOGICAL PspSinglePrivCheck (IN LUID PrivilegeValue, IN KPROCESSOR_MODE PreviousMode, OUT PPRIV_CHECK_CTX PrivCtx)
Definition at line 1979 of file security.c.
References KernelMode, PRIVILEGE_SET_ALL_NECESSARY, SeCaptureSubjectContext(), SePrivilegeCheck(), and TRUE.
Referenced by PspSetQuotaLimits().
VOID PspSinglePrivCheckAudit (IN LOGICAL PrivUsed, IN PPRIV_CHECK_CTX PrivCtx)
Definition at line 2025 of file security.c.
References KernelMode, NULL, SePrivilegedServiceAuditAlarm(), and SeReleaseSubjectContext().
Referenced by PspSetQuotaLimits().
NTSTATUS PspWriteTebImpersonationInfo (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Definition at line 1699 of file security.c.
References ASSERT, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), FALSE, KeMemoryBarrier(), KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, PAGED_CODE, _EPROCESS::Pcb, PS_IS_THREAD_IMPERSONATING, PsGetCurrentProcessByThread, PsGetCurrentThread(), STATUS_SUCCESS, THREAD_TO_PROCESS, and TRUE.
Referenced by PsImpersonateClient(), PsRevertThreadToSelf(), and PsRevertToSelf().
PACCESS_TOKEN PsReferenceEffectiveToken (IN PETHREAD Thread, OUT PTOKEN_TYPE TokenType, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 225 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, FALSE, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, ObFastReferenceObject(), ObFastReferenceObjectLocked(), ObReferenceObject, PAGED_CODE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockProcessSecurityShared(), PspLockThreadSecurityShared(), PspUnlockProcessSecurityShared(), PspUnlockThreadSecurityShared(), THREAD_TO_PROCESS, ThreadObject, _PS_IMPERSONATION_INFORMATION::Token, _EPROCESS::Token, TokenImpersonation, and TokenPrimary.
Referenced by SeCreateClientSecurity().
PACCESS_TOKEN PsReferenceImpersonationToken (__inout PETHREAD Thread, __out PBOOLEAN CopyOnOpen, __out PBOOLEAN EffectiveOnly, __out PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 108 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, ObReferenceObject, PAGED_CODE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockThreadSecurityShared(), PspUnlockThreadSecurityShared(), ThreadObject, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by ObpReferenceDeviceMap(), PsOpenTokenOfThread(), SeCaptureSubjectContextEx(), and SepOpenTokenOfThread().
PACCESS_TOKEN PsReferencePrimaryToken (__inout PEPROCESS Process)
Definition at line 59 of file security.c.
References ASSERT, NULL, ObFastReferenceObject(), ObFastReferenceObjectLocked(), PAGED_CODE, ProcessObject, PsGetCurrentThread(), PspLockProcessSecurityShared(), and PspUnlockProcessSecurityShared().
Referenced by NtAssignProcessToJobObject(), NtImpersonateAnonymousToken(), NtOpenThreadTokenEx(), NtSecureConnectPort(), ObpSetCurrentProcessDeviceMap(), PsImpersonateClient(), PsOpenTokenOfProcess(), PspCreateProcess(), PspCreateThread(), PspExitThread(), PspInitializeProcessSecurity(), PspSetPrimaryToken(), SeAuditProcessExit(), SeCaptureSubjectContextEx(), SeIsChildToken(), SeIsChildTokenByPointer(), SeIsSiblingToken(), SeIsSiblingTokenByPointer(), and WmiTraceProcess().
VOID PsRestoreImpersonation (__inout PETHREAD Thread, __in PSE_IMPERSONATION_STATE ImpersonationState)
Definition at line 1096 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, ObDereferenceObject(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PS_SET_BITS, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), ThreadObject, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by NtOpenThreadTokenEx().
VOID PsRevertThreadToSelf (__inout PETHREAD Thread)
Definition at line 1259 of file security.c.
References ASSERT, NULL, ObDereferenceObject(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), PspWriteTebImpersonationInfo(), ThreadObject, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by PsAssignImpersonationToken().
VOID PsRevertToSelf ()
Definition at line 1193 of file security.c.
References _ETHREAD::CrossThreadFlags, _ETHREAD::ImpersonationInfo, NULL, ObDereferenceObject(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), PspWriteTebImpersonationInfo(), THREAD_TO_PROCESS, and _PS_IMPERSONATION_INFORMATION::Token.