Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivemap.c File Reference
hivemap.c File Reference
#include "cmp.h"
Functions
BOOLEAN HvpAllocateMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
NTSTATUS HvpBuildMap (PHHIVE Hive, PVOID Image)
NTSTATUS HvpBuildMapAndCopy (PHHIVE Hive, PVOID Image)
VOID HvpCleanMap (PHHIVE Hive)
NTSTATUS HvpEnlistBinInMap (PHHIVE Hive, ULONG Length, PHBIN Bin, ULONG Offset, PVOID CmView OPTIONAL)
BOOLEAN HvpEnlistFreeCells (PHHIVE Hive, PHBIN Bin, ULONG BinOffset)
VOID HvpFreeMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
ULONG HvpGetBinMemAlloc (IN PHHIVE Hive, PHBIN Bin, IN HSTORAGE_TYPE Type)
NTSTATUS HvpInitMap (PHHIVE Hive)
Variables
struct {
PHBIN BinPoint
PHHIVE Hive
HCELL_INDEX MapPoint
ULONG Space
ULONG Status
} HvCheckHiveDebug
Function Documentation
BOOLEAN HvpAllocateMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
Definition at line 899 of file hivemap.c.
References _HHIVE::Allocate, ASSERT, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::CmView, _HMAP_DIRECTORY::Directory, FALSE, HTABLE_SLOTS, NULL, RtlZeroMemory, _HMAP_TABLE::Table, and TRUE.
Referenced by HvCloneHive(), HvpAddBin(), HvpBuildMapAndCopy(), and HvpInitMap().
NTSTATUS HvpBuildMap (PHHIVE Hive, PVOID Image)
Definition at line 519 of file hivemap.c.
References Bin, CmDoSelfHeal, CmKdPrintEx, CML_HIVE, CmMarkSelfHeal, DPFLTR_CONFIG_ID, _HBIN::FileOffset, HBIN_SIGNATURE, HBLOCK_SIZE, Hive, HvCheckHiveDebug, HvpCleanMap(), HvpEnlistBinInMap(), HvpInitMap(), _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, _HBIN::Signature, _HBIN::Size, Stable, Status, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, and _HHIVE::Storage.
Referenced by HvInitializeHive().
NTSTATUS HvpBuildMapAndCopy (PHHIVE Hive, PVOID Image)
Definition at line 46 of file hivemap.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, CmKdPrintEx, CML_HIVE, _HMAP_ENTRY::CmView, _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, _HBIN::FileOffset, _HHIVE::Free, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HSECTOR_SIZE, HTABLE_SLOTS, HvpAllocateMap(), HvpEnlistFreeCells(), HvpFreeMap(), HvpGetCellMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, _HMAP_ENTRY::MemAlloc, NULL, _HHIVE::ReadOnly, ROUND_UP, RtlCopyMemory, RtlInitializeBitMap(), RtlZeroMemory, _HBIN::Signature, _HBIN::Size, _HHIVE::_DUAL::SmallDir, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, _HHIVE::Storage, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvInitializeHive().
VOID HvpCleanMap (PHHIVE Hive)
Definition at line 785 of file hivemap.c.
References _RTL_BITMAP::Buffer, _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, _HHIVE::Free, HBLOCK_SIZE, HSECTOR_SIZE, HTABLE_SLOTS, HvpFreeMap(), _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, ROUND_UP, _HHIVE::_DUAL::SmallDir, Stable, and _HHIVE::Storage.
Referenced by CmpInitializeHive(), HvLoadHive(), HvMapHive(), HvpBuildMap(), and HvpReadFileImageAndBuildMap().
NTSTATUS HvpEnlistBinInMap (PHHIVE Hive, ULONG Length, PHBIN Bin, ULONG Offset, PVOID CmView OPTIONAL)
Definition at line 410 of file hivemap.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmDoSelfHeal, CmKdPrintEx, CML_BIN_MAP, CML_HIVE, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, FALSE, HBLOCK_SIZE, Hive, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HvCheckHiveDebug, HvpEnlistFreeCells(), HvpGetCellMap(), _HMAP_ENTRY::MemAlloc, NULL, _HHIVE::ReadOnly, _HBIN::Size, Status, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, and VALIDATE_CELL_MAP.
Referenced by HvCloneHive(), HvpBuildMap(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpRecoverWholeHive(), and HvShrinkHive().
BOOLEAN HvpEnlistFreeCells (PHHIVE Hive, PHBIN Bin, ULONG BinOffset)
Definition at line 658 of file hivemap.c.
References ASSERT, Bin, CmDoSelfHeal, CmMarkSelfHeal, FALSE, HCELL_PAD, HvpEnlistFreeCell(), RtlZeroMemory, _HCELL::Size, _HBIN::Size, Stable, and TRUE.
Referenced by HvpBuildMapAndCopy(), HvpEnlistBinInMap(), and HvRefreshHive().
VOID HvpFreeMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
Definition at line 850 of file hivemap.c.
References _HMAP_DIRECTORY::Directory, _HHIVE::Free, HDIRECTORY_SLOTS, and NULL.
Referenced by HvFreeHive(), HvFreeHivePartial(), HvpAddBin(), HvpBuildMapAndCopy(), HvpCleanMap(), HvpInitMap(), and HvShrinkHive().
ULONG HvpGetBinMemAlloc (IN PHHIVE Hive, PHBIN Bin, IN HSTORAGE_TYPE Type)
Definition at line 957 of file hivemap.c.
References ASSERT, Cell, _HBIN::FileOffset, HBIN_SIGNATURE, HBLOCK_SIZE, HCELL_TYPE_MASK, HvpGetCellMap(), _HMAP_ENTRY::MemAlloc, PAGED_CODE, _HBIN::Signature, _HBIN::Size, and VALIDATE_CELL_MAP.
Referenced by HvFreeHive(), HvFreeHivePartial(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistFreeCell(), and HvpFreeAllocatedBins().
NTSTATUS HvpInitMap (PHHIVE Hive)
Definition at line 273 of file hivemap.c.
References _HHIVE::Allocate, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, CmKdPrintEx, CML_HIVE, _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, _HHIVE::Free, HBLOCK_SIZE, HSECTOR_SIZE, HTABLE_SLOTS, HvpAllocateMap(), HvpFreeMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, ROUND_UP, RtlInitializeBitMap(), RtlZeroMemory, _HHIVE::_DUAL::SmallDir, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, _HHIVE::Storage, and TRUE.
Referenced by HvpBuildMap(), HvpMapFileImageAndBuildMap(), and HvpReadFileImageAndBuildMap().
Variable Documentation
PHBIN BinPoint
Definition at line 42 of file hivemap.c.
PHHIVE Hive
Definition at line 38 of file hivemap.c.
Referenced by HvpBuildMap(), and HvpEnlistBinInMap().
struct { ... } HvCheckHiveDebug
Referenced by HvpBuildMap(), and HvpEnlistBinInMap().
HCELL_INDEX MapPoint
Definition at line 41 of file hivemap.c.
ULONG Space
Definition at line 40 of file hivemap.c.
ULONG Status
Definition at line 39 of file hivemap.c.
Referenced by HvpBuildMap(), HvpBuildMapAndCopy(), HvpEnlistBinInMap(), and HvpInitMap().