Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/ioinit.c File Reference
ioinit.c File Reference
#include "iomgr.h"
#include <setupblk.h>
#include <inbv.h>
#include <ntddstor.h>
#include <hdlsblk.h>
#include <hdlsterm.h>
Macros
#define DEFAULT_LOOKASIDE_IRP_LIMIT 512
#define DEVICENAME_BUFFER_LENGTH 256
#define InitializeDriverObject(Object)
#define VALUE_BUFFER_LENGTH 32
Functions
BOOLEAN IoInitSystem (PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopCreateArcNames (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopCreateArcNamesCd (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopCreateArcNamesDisk (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN BOOLEAN SingleBiosDiskFound, OUT BOOLEAN *BootDiskFound)
BOOLEAN IopCreateObjectTypes (VOID)
BOOLEAN IopCreateRootDirectories (VOID)
NTSTATUS IopFetchConfigurationInformation (IN OUT PWSTR *ListTarget, IN GUID ClassGuid, IN ULONG ExpectedNumber, OUT ULONG *NumberFound)
NTSTATUS IopInitializeAttributesAndCreateObject (IN PUNICODE_STRING ObjectName, IN OUT POBJECT_ATTRIBUTES ObjectAttributes, OUT PDRIVER_OBJECT *DriverObject)
NTSTATUS IopInitializeBuiltinDriver (IN PUNICODE_STRING DriverName, IN PUNICODE_STRING RegistryPath, IN PDRIVER_INITIALIZE DriverInitializeRoutine, IN PKLDR_DATA_TABLE_ENTRY DriverEntry, IN BOOLEAN IsFilter, IN PDRIVER_OBJECT *Result)
VOID IopInitializeData (VOID)
BOOLEAN IopInitializeReserveIrp (PIOP_RESERVE_IRP_ALLOCATOR Allocator)
NTSTATUS IopLogErrorEvent (IN ULONG SequenceNumber, IN ULONG UniqueErrorValue, IN NTSTATUS FinalStatus, IN NTSTATUS SpecificIOStatus, IN ULONG LengthOfInsert1, IN PWCHAR Insert1, IN ULONG LengthOfInsert2, IN PWCHAR Insert2)
BOOLEAN IopMarkBootPartition (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN IopReassignSystemRoot (IN PLOADER_PARAMETER_BLOCK LoaderBlock, OUT PSTRING NtDeviceName)
VOID IopSetIoRoutines (IN VOID)
VOID IopSetIoRoutines ()
VOID IopStoreSystemPartitionInformation (IN PUNICODE_STRING NtSystemPartitionDeviceName, IN OUT PUNICODE_STRING OsLoaderPathName)
Variables
const GENERIC_MAPPING IopCompletionMapping
PVOID IopErrorLogObject = NULL
const GENERIC_MAPPING IopFileMapping
ULONG IopInitFailCode
Macro Definition Documentation
#define DEFAULT_LOOKASIDE_IRP_LIMIT 512
Definition at line 32 of file ioinit.c.
Referenced by IoInitSystem().
#define DEVICENAME_BUFFER_LENGTH 256
Definition at line 137 of file ioinit.c.
Referenced by IoInitSystem().
#define InitializeDriverObject (Object)
Value:
{                                 \
    ULONG i;                                                               \
    RtlZeroMemory( Object,                                                 \
                   sizeof( DRIVER_OBJECT ) + sizeof ( DRIVER_EXTENSION )); \
    Object->DriverExtension = (PDRIVER_EXTENSION) (Object + 1);            \
    Object->DriverExtension->DriverObject = Object;                        \
    for (i = 0; i <= IRP_MJ_MAXIMUM_FUNCTION; i++)                         \
        Object->MajorFunction[i] = IopInvalidDeviceRequest;                \
    Object->Type = IO_TYPE_DRIVER;                                         \
    Object->Size = sizeof( DRIVER_OBJECT );                                \
    }
Definition at line 43 of file ioinit.c.
Referenced by IopInitializeBuiltinDriver().
#define VALUE_BUFFER_LENGTH 32
Definition at line 138 of file ioinit.c.
Referenced by IoInitSystem().
Function Documentation
BOOLEAN IoInitSystem (PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 141 of file ioinit.c.
References ASSERT, _STRING::Buffer, CcPfBeginBootPhase(), CmRegistryMachineSystemCurrentControlSetServicesEventLog, _KEY_VALUE_PARTIAL_INFORMATION::Data, DbgPrint(), DEFAULT_LARGE_IRP_LOCATIONS, DEFAULT_LOOKASIDE_IRP_LIMIT, DEVICENAME_BUFFER_LENGTH, _LINK_TRACKING_PACKET::Event, EVENT_ALL_ACCESS, ExAllocatePoolWithTag, ExEventObjectType, ExFreePool(), ExInitializeResourceLite(), ExInitializeSystemLookasideList(), ExInitializeWorkItem, ExSystemLookasideListHead, _IOP_HARD_ERROR_QUEUE::ExWorkItem, FALSE, FileFsMaximumInformation, FileMaximumInformation, _IOP_IRP_STACK_PROFILER::Flags, FLG_ENABLE_KDEBUG_SYMBOL_LOAD, HalInitPnpDriver, HEADLESS_LOG_ANSI_TO_UNICODE_FAILED, HEADLESS_LOG_ASSIGN_SYSTEM_ROOT_FAILED, HEADLESS_LOG_BOOT_DRIVERS_INIT_FAILED, HEADLESS_LOG_EVENT_CREATE_FAILED, HEADLESS_LOG_LOCATE_SYSTEM_DLL_FAILED, HEADLESS_LOG_OBJECT_TYPE_CREATE_FAILED, HEADLESS_LOG_PNP_PHASE0_INIT_FAILED, HEADLESS_LOG_PNP_PHASE1_INIT_FAILED, HEADLESS_LOG_PROTECT_SYSTEM_ROOT_FAILED, HEADLESS_LOG_ROOT_DIR_CREATE_FAILED, HEADLESS_LOG_SYSTEM_DRIVERS_INIT_FAILED, HEADLESS_LOG_UNICODE_TO_ANSI_FAILED, HeadlessKernelAddLogEntry(), Index, InitializeListHead(), InitializeObjectAttributes, IoAssignDriveLetters(), IOP_ENABLE_AUTO_SIZING, IOP_FIXED_SIZE_MDL_PFNS, IopAddRemoteBootValuesToRegistry(), IopBootDriverReinitializeQueueHead, IopCallDriverReinitializationRoutines(), IopCdRomFileSystemQueueHead, IopCompletionLookasideList, IopCrashDumpLock, IopCreateObjectTypes(), IopCreateRootDirectories(), IopCurrentHardError, IopDatabaseResource, IopDiskFileSystemQueueHead, IopDriverLoadResource, IopDriverReinitializeQueueHead, IopErrorLogDisabledThisBoot, IopErrorLogListHead, IopErrorLogLock, IopFsNotifyChangeQueueHead, IopHardError, IopHardErrorThread(), IopInitFailCode, IopInitializeBootDrivers(), IopInitializeIrpStackProfiler(), IopInitializePlugPlayServices(), IopInitializeReserveIrp(), IopInitializeSystemDrivers(), IopIrpAutoSizingEnabled, IopIrpStackProfiler, IopLargeIrpLookasideList, IopLargeIrpStackLocations, IopLinkTrackingPacket, IopLinkTrackingPortObject, IopLinkTrackingServiceEvent, IopLoaderBlock, IopMarkHalDeviceNode(), IopMdlLookasideList, IopNetworkFileSystemQueueHead, IopNotifyLastChanceShutdownQueueHead, IopNotifyShutdownQueueHead, IopProtectSystemPartition(), IopQueryFsOperationAccess, IopQueryFsOperationLength, IopQueryOperationAccess, IopQueryOperationLength, IopReassignSystemRoot(), IopReserveIrpAllocator, IopSecurityResource, IopSetFsOperationAccess, IopSetFsOperationLength, IopSetIoRoutines(), IopSetOperationAccess, IopSetOperationLength, IopSmallIrpLookasideList, IopStartNetworkForRemoteBoot(), IopTapeFileSystemQueueHead, IopTimer, IopTimerDispatch(), IopTimerDpc, IopTimerLock, IopTimerQueueHead, IopUniqueDeviceObjectNumber, IoRemoteBootClient, IoStatisticsLock, IRP, KeBugCheckEx(), KeInitializeDpc(), KeInitializeEvent(), KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitializeTimerEx(), KeNumberProcessors, KernelMode, KeSetTimerEx(), KEY_READ, KeyValuePartialInformation, KiProcessorBlock, _PP_LOOKASIDE_LIST::L, _STRING::Length, LookasideCompletionList, _KPRCB::LookasideIrpFloat, LookasideLargeIrpList, LookasideMdlList, LookasideSmallIrpList, _STRING::MaximumLength, _UNICODE_STRING::MaximumLength, MAXLONG, MmIsThisAnNtAsSystem(), MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSmallSystem, NETWORK_BOOT_INITIALIZATION_FAILED, NonPagedPool, NotificationEvent, NT_SUCCESS, NtCreateEvent(), NtGlobalFlag, NtQueryValueKey(), NtSystemRoot, NULL, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, ObReferenceObjectByHandle, _PP_LOOKASIDE_LIST::P, PfSystemDriverInitPhase, PoInitDriverServices(), PpLastGoodDoBootProcessing(), _KPRCB::PPLookasideList, PsLocateSystemDll(), _LARGE_INTEGER::QuadPart, REG_DWORD, RtlAllocateStringRoutine, RtlAnsiStringToUnicodeString(), RtlInitUnicodeString(), RtlUnicodeStringToAnsiString(), SERVICE_DISABLED, SynchronizationEvent, SynchronizationTimer, _IOP_HARD_ERROR_QUEUE::ThreadStarted, TRUE, _KEY_VALUE_PARTIAL_INFORMATION::Type, VALUE_BUFFER_LENGTH, VOID, WMIInitialize(), _IOP_HARD_ERROR_QUEUE::WorkQueue, _IOP_HARD_ERROR_QUEUE::WorkQueueSemaphore, _IOP_HARD_ERROR_QUEUE::WorkQueueSpinLock, and ZwOpenKey().
Referenced by Phase1InitializationDiscard().
NTSTATUS IopCreateArcNames (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 1919 of file ioinit.c.
References DbgPrint(), _ARC_DISK_INFORMATION::DiskSignatures, ExAllocatePool, FALSE, _LIST_ENTRY::Flink, IoArcBootDeviceName, IoArcHalDeviceName, IoCreateSymbolicLink(), IoLoaderArcBootDeviceName, IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopStoreSystemPartitionInformation(), IoRemoteBootClient, memcpy(), NT_SUCCESS, PagedPool, RtlAnsiStringToUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), sprintf(), strlen(), strstr(), and TRUE.
NTSTATUS IopCreateArcNamesCd (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 1591 of file ioinit.c.
References _ARC_DISK_SIGNATURE::ArcName, _CONFIGURATION_INFORMATION::CdRomCount, _ARC_DISK_SIGNATURE::CheckSum, CONTAINING_RECORD, _STORAGE_DEVICE_NUMBER::DeviceNumber, _ARC_DISK_INFORMATION::DiskSignatures, ExAllocatePool, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, _LIST_ENTRY::Flink, IoBuildDeviceIoControlRequest(), IoBuildSynchronousFsdRequest(), IoCallDriver(), IoCreateSymbolicLink(), IOCTL_STORAGE_GET_DEVICE_NUMBER, IoGetConfigurationInformation(), IoGetDeviceObjectPointer(), IopFetchConfigurationInformation(), IRP_MJ_READ, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), max, NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PIRP, _LARGE_INTEGER::QuadPart, RtlAnsiStringToUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), sprintf(), _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, strcmp(), TRUE, and wcslen().
Referenced by IopCreateArcNames().
NTSTATUS IopCreateArcNamesDisk (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN BOOLEAN SingleBiosDiskFound, OUT BOOLEAN * BootDiskFound)
Definition at line 941 of file ioinit.c.
References _ARC_DISK_SIGNATURE::ArcName, _DISK_GEOMETRY::BytesPerSector, _ARC_DISK_SIGNATURE::CheckSum, CONTAINING_RECORD, DbgPrint(), _STORAGE_DEVICE_NUMBER::DeviceNumber, _CONFIGURATION_INFORMATION::DiskCount, _ARC_DISK_INFORMATION::DiskSignatures, ExAllocatePool, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, _LIST_ENTRY::Flink, HalExamineMBR(), IoBuildDeviceIoControlRequest(), IoBuildSynchronousFsdRequest(), IoCallDriver(), IoCreateSymbolicLink(), IOCTL_DISK_GET_DRIVE_GEOMETRY, IOCTL_STORAGE_GET_DEVICE_NUMBER, IoGetConfigurationInformation(), IoGetDeviceObjectPointer(), IopFetchConfigurationInformation(), IopStoreSystemPartitionInformation(), IopVerifyDiskSignature(), IoReadPartitionTableEx(), IRP_MJ_READ, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), max, NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PIRP, _LARGE_INTEGER::QuadPart, RtlAnsiStringToUnicodeString(), RtlEqualString(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), _ARC_DISK_SIGNATURE::Signature, sprintf(), _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, TRUE, _ARC_DISK_SIGNATURE::ValidPartitionTable, and wcslen().
Referenced by IopCreateArcNames().
BOOLEAN IopCreateObjectTypes (VOID)
Definition at line 2108 of file ioinit.c.
References _OBJECT_TYPE_INITIALIZER::CaseInsensitive, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, DEVICE_OBJECT, FALSE, FILE_ALL_ACCESS, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, IO_COMPLETION_ALL_ACCESS, IO_FILE_OBJECT_NON_PAGED_POOL_CHARGE, IO_FILE_OBJECT_PAGED_POOL_CHARGE, IoAdapterObjectType, IoCompletionObjectType, IoControllerObjectType, IoDeviceHandlerObjectSize, IoDeviceHandlerObjectType, IoDeviceObjectType, IoDriverObjectType, IoFileObjectType, IopCloseFile(), IopCompletionMapping, IopDeleteDevice(), IopDeleteDriver(), IopDeleteFile(), IopDeleteIoCompletion(), IopFileMapping, IopGetSetSecurityObject(), IopParseDevice(), IopParseFile(), IopQueryName(), IopVerifierOn, _OBJECT_TYPE_INITIALIZER::Length, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, _OBJECT_TYPE_INITIALIZER::MaintainTypeList, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_EXCLUSIVE, OBJ_OPENLINK, OBJ_PERMANENT, _OBJECT_TYPE_INITIALIZER::ParseProcedure, PERFINFO_MUNG_FILE_OBJECT_TYPE_INITIALIZER, PERFINFO_UNMUNG_FILE_OBJECT_TYPE_INITIALIZER, _OBJECT_TYPE_INITIALIZER::PoolType, _OBJECT_TYPE_INITIALIZER::QueryNameProcedure, RtlInitUnicodeString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by IoInitSystem().
BOOLEAN IopCreateRootDirectories (VOID)
Definition at line 2293 of file ioinit.c.
References DIRECTORY_ALL_ACCESS, FALSE, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NtCreateDirectoryObject(), NULL, ObCloseHandle(), OBJ_KERNEL_HANDLE, OBJ_PERMANENT, RtlInitUnicodeString(), TRUE, and VOID.
Referenced by IoInitSystem().
NTSTATUS IopFetchConfigurationInformation (IN OUT PWSTR * ListTarget, IN GUID ClassGuid, IN ULONG ExpectedNumber, OUT ULONG * NumberFound)
Definition at line 882 of file ioinit.c.
References IoGetDeviceInterfaces(), NT_SUCCESS, NULL, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and wcslen().
Referenced by IopCreateArcNamesCd(), and IopCreateArcNamesDisk().
NTSTATUS IopInitializeAttributesAndCreateObject (IN PUNICODE_STRING ObjectName, IN OUT POBJECT_ATTRIBUTES ObjectAttributes, OUT PDRIVER_OBJECT * DriverObject)
Definition at line 2376 of file ioinit.c.
References InitializeObjectAttributes, IoDriverObjectType, KeGetPreviousMode, KernelMode, NULL, ObCreateObject, OBJ_CASE_INSENSITIVE, and OBJ_PERMANENT.
Referenced by IopInitializeBuiltinDriver().
NTSTATUS IopInitializeBuiltinDriver (IN PUNICODE_STRING DriverName, IN PUNICODE_STRING RegistryPath, IN PDRIVER_INITIALIZE DriverInitializeRoutine, IN PKLDR_DATA_TABLE_ENTRY DriverEntry, IN BOOLEAN IsFilter, IN PDRIVER_OBJECT * Result)
Definition at line 2431 of file ioinit.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CmRegistryMachineHardwareDescriptionSystemName, CONTAINING_RECORD, DbgPrint(), _IMAGE_OPTIONAL_HEADER::DllCharacteristics, _DRIVER_OBJECT::DriverExtension, _DRIVER_OBJECT::DriverInit, _DRIVER_OBJECT::DriverName, _DRIVER_OBJECT::DriverSection, _DRIVER_OBJECT::DriverSize, _DRIVER_OBJECT::DriverStart, DRVO_LEGACY_DRIVER, ExAllocatePool, exit(), FILE_READ_DATA, _DRIVER_OBJECT::Flags, _LIST_ENTRY::Flink, _DRIVER_OBJECT::HardwareDatabase, HEADLESS_LOG_LOAD_FAILED, HEADLESS_LOG_LOAD_SUCCESSFUL, HEADLESS_LOG_LOADING_FILENAME, HeadlessKernelAddLogEntry(), IMAGE_DLLCHARACTERISTICS_WDM_DRIVER, InbvIndicateProgress(), InitializeDriverObject, IoDriverObjectType, IopDriverLoadingFailed(), IopInitializeAttributesAndCreateObject(), IopOpenRegistryKeyEx(), IopPrepareDriverLoading(), IopReadyDeviceObjects(), KeQuerySystemTime(), KernelMode, KEY_ALL_ACCESS, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NonPagedPool, NT_SUCCESS, NtClose(), NULL, ObDereferenceObject(), ObInsertObject(), OBJ_NAME_PATH_SEPARATOR, ObMakeTemporaryObject(), ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PagedPool, PsLoadedModuleList, _LARGE_INTEGER::QuadPart, RtlCopyMemory, RtlEqualString(), RtlImageNtHeader(), _DRIVER_EXTENSION::ServiceKeyName, _IMAGE_OPTIONAL_HEADER::SizeOfImage, STATUS_INSUFFICIENT_RESOURCES, STATUS_PLUGPLAY_NO_DEVICE, STATUS_SUCCESS, TRUE, and UNICODE_NULL.
VOID IopInitializeData (VOID)
BOOLEAN IopInitializeReserveIrp (PIOP_RESERVE_IRP_ALLOCATOR Allocator)
Definition at line 3512 of file ioinit.c.
References _IOP_RESERVE_IRP_ALLOCATOR::Event, FALSE, IoAllocateIrp(), _IOP_RESERVE_IRP_ALLOCATOR::IrpAllocated, KeInitializeEvent(), MAX_RESERVE_IRP_STACK_SIZE, NULL, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrp, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrpStackSize, SynchronizationEvent, and TRUE.
Referenced by IoInitSystem().
NTSTATUS IopLogErrorEvent (IN ULONG SequenceNumber, IN ULONG UniqueErrorValue, IN NTSTATUS FinalStatus, IN NTSTATUS SpecificIOStatus, IN ULONG LengthOfInsert1, IN PWCHAR Insert1, IN ULONG LengthOfInsert2, IN PWCHAR Insert2)
Definition at line 3397 of file ioinit.c.
References _IO_ERROR_LOG_PACKET::DumpData, _IO_ERROR_LOG_PACKET::DumpDataSize, _IO_ERROR_LOG_PACKET::ErrorCode, _IO_ERROR_LOG_PACKET::FinalStatus, IoAllocateErrorLogEntry(), IopErrorLogObject, IoWriteErrorLogEntry(), _IO_ERROR_LOG_PACKET::MajorFunctionCode, NULL, _IO_ERROR_LOG_PACKET::NumberOfStrings, _IO_ERROR_LOG_PACKET::RetryCount, RtlCopyMemory, _IO_ERROR_LOG_PACKET::SequenceNumber, STATUS_INVALID_HANDLE, STATUS_NO_DATA_DETECTED, STATUS_SUCCESS, _IO_ERROR_LOG_PACKET::StringOffset, and _IO_ERROR_LOG_PACKET::UniqueErrorValue.
BOOLEAN IopMarkBootPartition (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 2743 of file ioinit.c.
References _FILE_OBJECT::DeviceObject, DO_SYSTEM_BOOT_PARTITION, FALSE, FILE_NON_DIRECTORY_FILE, FILE_READ_ATTRIBUTES, FILE_READ_ONLY_DEVICE, FILE_REMOVABLE_MEDIA, INACCESSIBLE_BOOT_DEVICE, INIT_WINPEMODE_READONLY_MEDIA, INIT_WINPEMODE_REMOVABLE_MEDIA, InitializeObjectAttributes, InitIsWinPEMode, InitWinPEModeType, IoFileObjectType, IopErrorLogObject, KeBugCheckEx(), KernelMode, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObject, ObReferenceObjectByHandle, RtlAnsiStringToUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), sprintf(), TRUE, and ZwOpenFile().
BOOLEAN IopReassignSystemRoot (IN PLOADER_PARAMETER_BLOCK LoaderBlock, OUT PSTRING NtDeviceName)
Definition at line 2889 of file ioinit.c.
References _STRING::Buffer, _UNICODE_STRING::Buffer, FALSE, INIT_SYSTEMROOT_LINKNAME, InitializeObjectAttributes, KernelMode, _STRING::Length, _UNICODE_STRING::Length, _STRING::MaximumLength, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtCreateSymbolicLinkObject(), NtMakeTemporaryObject(), NtOpenSymbolicLinkObject(), NtQuerySymbolicLinkObject(), NULL, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, RtlAnsiStringToUnicodeString(), RtlCopyString(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlUnicodeStringToAnsiString(), sprintf(), strlen(), SYMBOLIC_LINK_ALL_ACCESS, TRUE, and ZwDisplayString().
Referenced by IoInitSystem().
VOID IopSetIoRoutines (IN VOID)
Referenced by IoInitSystem().
VOID IopSetIoRoutines ()
Definition at line 863 of file ioinit.c.
References IopAllocateIrpPrivate(), IopfCompleteRequest(), IopFreeIrp(), NULL, pIoAllocateIrp, pIofCompleteRequest, and pIoFreeIrp.
VOID IopStoreSystemPartitionInformation (IN PUNICODE_STRING NtSystemPartitionDeviceName, IN OUT PUNICODE_STRING OsLoaderPathName)
Definition at line 3139 of file ioinit.c.
References ASSERT, _UNICODE_STRING::Buffer, CmRegistryMachineSystemName, DbgPrint(), InitializeObjectAttributes, IopCreateRegistryKeyEx(), IopOpenRegistryKeyEx(), KernelMode, KEY_ALL_ACCESS, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtOpenSymbolicLinkObject(), NtQuerySymbolicLinkObject(), NtSetValueKey(), NULL, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_OPTION_NON_VOLATILE, REG_SZ, SYMBOLIC_LINK_QUERY, and TITLE_INDEX_VALUE.
Referenced by IopCreateArcNames(), and IopCreateArcNamesDisk().
Variable Documentation
const GENERIC_MAPPING IopCompletionMapping
Initial value:
= {
    STANDARD_RIGHTS_READ |
        IO_COMPLETION_QUERY_STATE,
    STANDARD_RIGHTS_WRITE |
        IO_COMPLETION_MODIFY_STATE,
    STANDARD_RIGHTS_EXECUTE |
        SYNCHRONIZE,
    IO_COMPLETION_ALL_ACCESS
}
Definition at line 2097 of file ioinit.c.
Referenced by IopCreateObjectTypes().
PVOID IopErrorLogObject = NULL
Definition at line 37 of file ioinit.c.
Referenced by IopLogErrorEvent(), and IopMarkBootPartition().
const GENERIC_MAPPING IopFileMapping
Initial value:
= {
    STANDARD_RIGHTS_READ |
        FILE_READ_DATA | FILE_READ_ATTRIBUTES | FILE_READ_EA | SYNCHRONIZE,
    STANDARD_RIGHTS_WRITE |
        FILE_WRITE_DATA | FILE_WRITE_ATTRIBUTES | FILE_WRITE_EA | FILE_APPEND_DATA | SYNCHRONIZE,
    STANDARD_RIGHTS_EXECUTE |
        SYNCHRONIZE | FILE_READ_ATTRIBUTES | FILE_EXECUTE,
    FILE_ALL_ACCESS
}
Definition at line 2084 of file ioinit.c.
Referenced by IoGetFileObjectGenericMapping(), and IopCreateObjectTypes().
ULONG IopInitFailCode
Definition at line 55 of file ioinit.c.
Referenced by IoInitSystem().