Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obref.c File Reference
obref.c File Reference
#include "obp.h"
Data Structures
struct _OB_TEMP_BUFFER
Typedefs
typedef struct _OB_TEMP_BUFFER OB_TEMP_BUFFER
typedef struct _OB_TEMP_BUFFER * POB_TEMP_BUFFER
Functions
VOID ObAuditObjectAccess (IN HANDLE Handle, IN POBJECT_HANDLE_INFORMATION HandleInformation OPTIONAL, IN KPROCESSOR_MODE AccessMode, IN ACCESS_MASK DesiredAccess)
LONG_PTR ObDereferenceObject (IN PVOID Object)
VOID ObDereferenceObjectDeferDelete (IN PVOID Object)
LONG_PTR FASTCALL ObDereferenceObjectEx (IN PVOID Object, IN ULONG Count)
LONG_PTR FASTCALL ObfDereferenceObject (__in PVOID Object)
LONG_PTR FASTCALL ObfReferenceObject (__in PVOID Object)
BOOLEAN ObIsObjectDeletionInline (IN PVOID Object)
NTSTATUS ObOpenObjectByName (__in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __inout_opt PVOID ParseContext, __out PHANDLE Handle)
NTSTATUS ObOpenObjectByPointer (__in PVOID Object, __in ULONG HandleAttributes, __in_opt PACCESS_STATE PassedAccessState, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PHANDLE Handle)
VOID ObpAuditObjectAccess (IN HANDLE Handle, IN PHANDLE_TABLE_ENTRY_INFO ObjectTableEntryInfo, IN PUNICODE_STRING ObjectTypeName, IN ACCESS_MASK DesiredAccess)
VOID ObpDeferObjectDeletion (IN POBJECT_HEADER ObjectHeader)
VOID ObpDeleteNameCheck (IN PVOID Object)
VOID ObpProcessRemoveObjectQueue (PVOID Parameter)
NTSTATUS ObpReferenceProcessObjectByHandle (IN HANDLE Handle, IN PEPROCESS Process, IN PHANDLE_TABLE HandleTable, IN KPROCESSOR_MODE AccessMode, OUT PVOID *Object, OUT POBJECT_HANDLE_INFORMATION HandleInformation, OUT PACCESS_MASK AuditMask)
VOID ObpRemoveObjectRoutine (IN PVOID Object, IN BOOLEAN CalledOnWorkerThread)
NTSTATUS ObReferenceFileObjectForWrite (IN HANDLE Handle, IN KPROCESSOR_MODE AccessMode, OUT PVOID *FileObject, OUT POBJECT_HANDLE_INFORMATION HandleInformation)
NTSTATUS ObReferenceObjectByHandle (__in HANDLE Handle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PVOID *Object, __out_opt POBJECT_HANDLE_INFORMATION HandleInformation)
NTSTATUS ObReferenceObjectByName (__in PUNICODE_STRING ObjectName, __in ULONG Attributes, __in_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __in POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PVOID ParseContext, __out PVOID *Object)
NTSTATUS ObReferenceObjectByPointer (__in PVOID Object, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode)
LONG_PTR FASTCALL ObReferenceObjectEx (IN PVOID Object, IN ULONG Count)
BOOLEAN FASTCALL ObReferenceObjectSafe (IN PVOID Object)
Variables
BOOLEAN ObpTraceEnabled = FALSE
ULONG ObpTraceNoDeregister = 0
ULONG ObpTracePoolTags [16]
WCHAR ObpTracePoolTagsBuffer [128] = { 0 }
ULONG ObpTracePoolTagsLength = sizeof(ObpTracePoolTagsBuffer)
Typedef Documentation
typedef struct _OB_TEMP_BUFFER OB_TEMP_BUFFER
typedef struct _OB_TEMP_BUFFER * POB_TEMP_BUFFER
Function Documentation
VOID ObAuditObjectAccess (IN HANDLE Handle, IN POBJECT_HANDLE_INFORMATION HandleInformation OPTIONAL, IN KPROCESSOR_MODE AccessMode, IN ACCESS_MASK DesiredAccess)
Definition at line 1781 of file obref.c.
References ARGUMENT_PRESENT, ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, ExGetHandleInfo, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, _OBJECT_TYPE::Name, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, ObpAuditObjectAccess(), ObpGetObjectTable, TRUE, and _OBJECT_HEADER::Type.
LONG_PTR ObDereferenceObject (IN PVOID Object)
Definition at line 2925 of file obref.c.
References ObfDereferenceObject().
Referenced by BuildQueryDirectoryIrp(), CcDeleteSharedCacheMap(), CcPerformReadAhead(), CmGetSystemDriverList(), CmNotifyRunDown(), CmpCloneControlSet(), CmpDoCreateChild(), CmpDropFileObjectForHive(), CmpDumpOneKeyBody(), CmpFileRead(), CmpFileWrite(), CmpIsHiveAlreadyLoaded(), CmpLinkHiveToMaster(), CmpOpenHiveFiles(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), CmpSaveBootControlSet(), CmShutdownSystem(), CmUnloadKey(), DbgkClearProcessDebugObject(), DbgkOpenProcessDebugPort(), DbgkpCloseObject(), DbgkpFreeDebugEvent(), DbgkpPostFakeProcessCreateMessages(), DbgkpPostFakeThreadMessages(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), ExFreePoolWithTag(), ExpCreateWorkerThread(), ExpProfileDelete(), ExpRegisterFirmwareTableInformationHandler(), ExpShutdownWorker(), ExpShutdownWorkerThreads(), ExpTimerDpcRoutine(), ExpWorkerThreadBalanceManager(), ExRegisterCallback(), ExReturnPoolQuota(), ExUnregisterCallback(), FsRtlAcknowledgeOplockBreak(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlCancelExclusiveIrp(), FsRtlCreateSectionForDataScan(), FsRtlNotifyVolumeEvent(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateLock(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), FsRtlReleaseFileForModWrite(), FsRtlRemoveAndCompleteIrp(), FsRtlUninitializeOplock(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoAttachDevice(), IoCreateDevice(), IoCreateDriver(), IoCreateNotificationEvent(), IoCreateStreamFileObjectEx(), IoCreateSynchronizationEvent(), IoDeleteController(), IoDeleteDriver(), IoFreeErrorLogEntry(), IoGetBootDiskInformation(), IopAllocateIrpCleanup(), IopCheckUnloadDriver(), IopCompleteRequest(), IopCompleteUnloadOrDelete(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopCreateFile(), IopDeleteDevice(), IopDeleteFile(), IopDropIrp(), IopErrorLogThread(), IopExceptionCleanup(), IopGetDriverPathInformation(), IopGetFileInformation(), IopGetSetSecurityObject(), IopInitializeBuiltinDriver(), IopInvalidateVolumesForDevice(), IopLoadDriver(), IopMarkBootPartition(), IopMountVolume(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopProcessWorkItem(), IopQueryXxxInformation(), IopSendMessageToTrackService(), IopSetDeviceSecurityDescriptors(), IopSetEaOrQuotaInformationFile(), IopShutdownBaseFileSystems(), IopTrackLink(), IopUnloadDriver(), IopUnloadSafeCompletion(), IopXxxControlFile(), IoSetInformation(), IoShutdownSystem(), IoUnregisterFsRegistrationChange(), IoUnregisterShutdownNotification(), IoVolumeDeviceToDosName(), IoWriteErrorLogEntry(), LpcExitThread(), LpcpCopyRequestData(), LpcpCreatePort(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeToPortZone(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiLdwPopupWorker(), MiSegmentDelete(), MiSessionWideReserveImageAddress(), MmCheckSystemImage(), MmCreateSection(), MmGetFileNameForAddress(), MmGetNextSession(), MmGetPreviousSession(), MmLoadSystemImage(), MmQuitNextSession(), MmSetBankedSection(), MmShutdownSystem(), MmUnloadSystemImage(), NtAcceptConnectPort(), NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtAlertResumeThread(), NtAlertThread(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtAssignProcessToJobObject(), NtCancelIoFile(), NtClearEvent(), NtCompactKeys(), NtCompareTokens(), NtCompleteConnectPort(), NtCompressKey(), NtCreateJobSet(), NtCreateKey(), NtCreatePagingFile(), NtCreateProfile(), NtCreateSymbolicLinkObject(), NtDebugActiveProcess(), NtDebugContinue(), NtDeleteKey(), NtDeleteValueKey(), NtDuplicateObject(), NtDuplicateToken(), NtEnumerateKey(), NtEnumerateValueKey(), NtExtendSection(), NtFilterToken(), NtFlushBuffersFile(), NtFlushInstructionCache(), NtFlushKey(), NtFlushVirtualMemory(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetContextThread(), NtGetNextProcess(), NtGetNextThread(), NtGetWriteWatch(), NtImpersonateAnonymousToken(), NtImpersonateClientOfPort(), NtImpersonateThread(), NtIsProcessInJob(), NtLoadKeyEx(), NtLockFile(), NtLockRegistryKey(), NtLockVirtualMemory(), NtMakePermanentObject(), NtMakeTemporaryObject(), NtMapViewOfSection(), NtNotifyChangeDirectoryFile(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtOpenObjectAuditAlarm(), NtOpenProcess(), NtOpenProcessTokenEx(), NtOpenThread(), NtOpenThreadTokenEx(), NtPrivilegeCheck(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtProtectVirtualMemory(), NtPulseEvent(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryEvent(), NtQueryInformationFile(), NtQueryInformationJobObject(), NtQueryInformationPort(), NtQueryInformationProcess(), NtQueryInformationThread(), NtQueryInformationToken(), NtQueryIoCompletion(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryMutant(), NtQueryObject(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryQuotaInformationFile(), NtQuerySection(), NtQuerySecurityObject(), NtQuerySemaphore(), NtQuerySymbolicLinkObject(), NtQueryTimer(), NtQueryValueKey(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtQueueApcThread(), NtReadFile(), NtReadFileScatter(), NtReadVirtualMemory(), NtRegisterThreadTerminatePort(), NtReleaseKeyedEvent(), NtReleaseMutant(), NtReleaseSemaphore(), NtRemoveIoCompletion(), NtRemoveProcessDebug(), NtRenameKey(), NtReplaceKey(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtResetEvent(), NtResetWriteWatch(), NtRestoreKey(), NtResumeProcess(), NtResumeThread(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSecureConnectPort(), NtSetContextThread(), NtSetEaFile(), NtSetEvent(), NtSetEventBoostPriority(), NtSetHighEventPair(), NtSetHighWaitLowEventPair(), NtSetInformationDebugObject(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationKey(), NtSetInformationObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetInformationToken(), NtSetIoCompletion(), NtSetLowEventPair(), NtSetLowWaitHighEventPair(), NtSetSecurityObject(), NtSetValueKey(), NtSetVolumeInformationFile(), NtSignalAndWaitForSingleObject(), NtStartProfile(), NtStopProfile(), NtSuspendProcess(), NtSuspendThread(), NtTerminateJobObject(), NtTerminateProcess(), NtTerminateThread(), NtUnloadKey2(), NtUnloadKeyEx(), NtUnlockFile(), NtUnlockVirtualMemory(), NtUnmapViewOfSection(), NtWaitForDebugEvent(), NtWaitForKeyedEvent(), NtWaitForSingleObject(), NtWaitHighEventPair(), NtWaitLowEventPair(), NtWriteFile(), NtWriteFileGather(), NtWriteVirtualMemory(), ObDupHandleProcedure(), ObDuplicateObject(), ObFastDereferenceObject(), ObfDereferenceDeviceMap(), ObInsertObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpDeleteNameCheck(), ObpDestroyTypeArray(), ObpLookupDirectoryEntry(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), ObpQueryNameString(), ObpReleaseLookupContext(), ObpReleaseLookupContextObject(), ObpWaitForMultipleObjects(), ObReferenceObjectByName(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObShutdownSystem(), ObSwapObjectNames(), ObWaitForSingleObject(), PerfInfoFileNameRunDown(), PsAssignImpersonationToken(), PsDereferenceImpersonationToken(), PsDereferencePrimaryToken(), PsEnumProcesses(), PsGetNextJob(), PsGetNextJobProcess(), PsGetNextProcess(), PsGetNextProcessThread(), PsImpersonateClient(), PsLocateSystemDll(), PsLookupProcessThreadByCid(), PsMapSystemDll(), PsOpenTokenOfProcess(), PsOpenTokenOfThread(), PspAssignPrimaryToken(), PspCreateProcess(), PspCreateThread(), PspDeleteThreadSecurity(), PspExitProcess(), PspExitThread(), PspJobClose(), PspJobDelete(), PspProcessDelete(), PspQueryPooledQuotaLimits(), PspQueryQuotaLimits(), PspQueryWorkingSetWatch(), PspReaper(), PspSetPrimaryToken(), PspSetQuotaLimits(), PspThreadDelete(), PspWaitForUsermodeExit(), PsQuitNextJob(), PsQuitNextJobProcess(), PsQuitNextProcess(), PsQuitNextProcessThread(), PsRestoreImpersonation(), PsRevertThreadToSelf(), PsRevertToSelf(), PsShutdownSystem(), PsWaitForAllProcesses(), RawCheckForDismount(), RawMountVolume(), RawUnload(), SeAccessCheckByType(), SeCreateClientSecurity(), SeCreateClientSecurityFromSubjectContext(), SeDeassignPrimaryToken(), SeIsChildToken(), SeIsSiblingToken(), SeLocateProcessImageName(), SepAccessCheckAndAuditAlarm(), SepCleanupLUIDDeviceMapDirectory(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), SepOpenTokenOfThread(), WmiGetClock(), WmipCloseMethod(), WmipCreatePumpThread(), WmipCreatePumpThreadRoutine(), WmipCreateUMLogger(), WmipDeleteMethod(), WmipDeregisterDevice(), WmipDoUnreferenceRegEntry(), WmipForwardWmiIrp(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipOpenBlock(), WmipOpenGuidObject(), WmipProcessEvent(), WmipQueryAllData(), WmipQueryGuidInfo(), WmipQuerySetExecuteSI(), WmipReceiveNotifications(), WmipRegisterUMGuids(), WmipStartLogger(), WmipTraceFile(), WmipTranslateFileHandle(), WmipTranslatePDOInstanceNames(), WmipWriteMBToObject(), and WmiUpdateTrace().
VOID ObDereferenceObjectDeferDelete (IN PVOID Object)
Definition at line 2521 of file obref.c.
References InterlockedDecrement, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDecrPointerCount, and ObpDeferObjectDeletion().
Referenced by CmpCreateLinkNode(), CmpDelayedDerefKeys(), CmpDoCreate(), CmpDoCreateChild(), CmpDoOpen(), CmpFlushNotifiesOnKeyBodyList(), CmpFreePostBlock(), IopCompleteRequest(), MmCreateSection(), ObpDereferenceNameInfo(), PspGetNextJobProcess(), PspJobDelete(), PspProcessDelete(), and PspQuitNextJobProcess().
LONG_PTR FASTCALL ObDereferenceObjectEx (IN PVOID Object, IN ULONG Count)
Definition at line 2335 of file obref.c.
References OBJECT_TO_OBJECT_HEADER, ObpDecrPointerCountEx, and ObpDeferObjectDeletion().
Referenced by ExpTimerApcRoutine(), ExTimerRundown(), IopDropIrp(), NtAssignProcessToJobObject(), NtCancelTimer(), NtSetTimer(), ObFastReferenceObject(), ObFastReplaceObject(), and PspCreateThread().
LONG_PTR FASTCALL ObfDereferenceObject (__in PVOID Object)
Definition at line 2418 of file obref.c.
References ASSERT, FALSE, _OBJECT_HEADER::HandleCount, InterlockedDecrement, KeAreAllApcsDisabled(), KeGetCurrentIrql(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDecrPointerCount, ObpDeferObjectDeletion(), ObpRemoveObjectRoutine(), ObpTraceEnabled, ObpTraceNoDeregister, ReadForWriteAccess, and _OBJECT_HEADER::Type.
Referenced by ObDereferenceObject().
LONG_PTR FASTCALL ObfReferenceObject (__in PVOID Object)
Definition at line 2268 of file obref.c.
References ASSERT, OBJECT_TO_OBJECT_HEADER, and ObpIncrPointerCount.
Referenced by NtQueryObject(), and ObpQueryNameString().
BOOLEAN ObIsObjectDeletionInline (IN PVOID Object)
Definition at line 2952 of file obref.c.
References _OBJECT_HEADER::Flags, OB_FLAG_DELETED_INLINE, and OBJECT_TO_OBJECT_HEADER.
Referenced by IopDeleteFile().
NTSTATUS ObOpenObjectByName (__in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __inout_opt PVOID ParseContext, __out PHANDLE Handle)
Definition at line 592 of file obref.c.
References ARGUMENT_PRESENT, _OBJECT_CREATE_INFORMATION::Attributes, _OB_TEMP_BUFFER::AuxData, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OB_TEMP_BUFFER::LocalAccessState, _OB_TEMP_BUFFER::LookupContext, NonPagedPool, NT_SUCCESS, NULL, OB_FLAG_NEW_OBJECT, ObCreateHandle, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, _OB_TEMP_BUFFER::ObjectCreateInfo, ObOpenHandle, ObpCaptureObjectCreateInformation(), ObpCreateHandle(), ObpFreeObjectCreateInformation, ObpFreeObjectNameBuffer(), ObpLookupObjectName(), ObpReleaseLookupContext(), ObpReleaseObjectCreateInformation, ObpValidateAccessMask(), ObpValidateIrql, PAGED_CODE, _OBJECT_CREATE_INFORMATION::RootDirectory, SeCreateAccessState(), _OBJECT_CREATE_INFORMATION::SecurityDescriptor, _OBJECT_CREATE_INFORMATION::SecurityQos, SeDeleteAccessState(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by CmLoadKey(), CmpCreatePredefined(), CmpLinkHiveToMaster(), ExCreateCallback(), IoFastQueryNetworkAttributes(), IopCreateFile(), IopLoadDriver(), IopReferenceDriverObjectByName(), IopUnloadDriver(), NtCreateKey(), NtDeleteFile(), NtNotifyChangeMultipleKeys(), NtOpenDirectoryObject(), NtOpenEvent(), NtOpenEventPair(), NtOpenIoCompletion(), NtOpenJobObject(), NtOpenKey(), NtOpenKeyedEvent(), NtOpenMutant(), NtOpenProcess(), NtOpenSection(), NtOpenSemaphore(), NtOpenSymbolicLinkObject(), NtOpenThread(), NtOpenTimer(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtUnloadKey2(), and NtUnloadKeyEx().
NTSTATUS ObOpenObjectByPointer (__in PVOID Object, __in ULONG HandleAttributes, __in_opt PACCESS_STATE PassedAccessState, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PHANDLE Handle)
Definition at line 886 of file obref.c.
References ARGUMENT_PRESENT, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObOpenHandle, ObpCreateHandle(), ObpValidateIrql, ObReferenceObjectByPointer(), PAGED_CODE, SeCreateAccessState(), SeDeleteAccessState(), Status, STATUS_INVALID_PARAMETER, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by DbgkOpenProcessDebugPort(), DbgkpOpenHandles(), IopInvalidateVolumesForDevice(), NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenProcessTokenEx(), NtOpenThread(), NtOpenThreadTokenEx(), WmipOpenGuidObject(), and WmipReceiveNotifications().
VOID ObpAuditObjectAccess (IN HANDLE Handle, IN PHANDLE_TABLE_ENTRY_INFO ObjectTableEntryInfo, IN PUNICODE_STRING ObjectTypeName, IN ACCESS_MASK DesiredAccess)
Definition at line 1894 of file obref.c.
References InterlockedCompareExchange(), NULL, and SeOperationAuditAlarm().
Referenced by ObAuditObjectAccess(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
VOID ObpDeferObjectDeletion (IN POBJECT_HEADER ObjectHeader)
Definition at line 2234 of file obref.c.
References CriticalWorkQueue, ExQueueWorkItem(), InterlockedCompareExchangePointer, NULL, ObpRemoveObjectList, ObpRemoveObjectWorkItem, and ReadForWriteAccess.
Referenced by ObDereferenceObjectDeferDelete(), ObDereferenceObjectEx(), and ObfDereferenceObject().
VOID ObpDeleteNameCheck (IN PVOID Object)
Definition at line 2767 of file obref.c.
References _OBJECT_HEADER_NAME_INFO::Directory, FALSE, _OBJECT_HEADER::Flags, _OBJECT_HEADER::HandleCount, InterlockedExchangeAdd(), _UNICODE_STRING::Length, _OBJECT_HEADER_NAME_INFO::Name, NULL, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, OBP_NAME_KERNEL_PROTECTED, ObpDeleteDirectoryEntry(), ObpDeleteSymbolicLinkName(), ObpDereferenceNameInfo(), ObpInitializeLookupContext(), ObpIsKernelExclusiveObject(), ObpLockLookupContext(), ObpLockObject, ObpLookupDirectoryEntry(), ObpReferenceNameInfo(), ObpReleaseLookupContext(), ObpSymbolicLinkObjectType, ObpUnlockObject, ObpValidateIrql, PAGED_CODE, _OBJECT_HEADER_NAME_INFO::QueryReferences, and _OBJECT_HEADER::Type.
Referenced by ObInsertObject(), ObMakeTemporaryObject(), ObpDecrementHandleCount(), and ObSwapObjectNames().
VOID ObpProcessRemoveObjectQueue (PVOID Parameter)
Definition at line 2562 of file obref.c.
References _OBJECT_HEADER::Body, InterlockedCompareExchangePointer, InterlockedExchangePointer, _OBJECT_HEADER::NextToFree, NULL, ObpRemoveObjectList, ObpRemoveObjectRoutine(), ObpTraceEnabled, ObpTraceNoDeregister, TRUE, and UNREFERENCED_PARAMETER.
Referenced by ObInitSystem().
NTSTATUS ObpReferenceProcessObjectByHandle (IN HANDLE Handle, IN PEPROCESS Process, IN PHANDLE_TABLE HandleTable, IN KPROCESSOR_MODE AccessMode, OUT PVOID * Object, OUT POBJECT_HANDLE_INFORMATION HandleInformation, OUT PACCESS_MASK AuditMask)
Definition at line 1355 of file obref.c.
References ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _OBJECT_HEADER::Body, DecodeKernelHandle, ExGetHandleInfo, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), FLG_KERNEL_STACK_TRACE_DB, _ETHREAD::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KernelMode, NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), ObpValidateIrql, PsGetCurrentThread(), Status, STATUS_INVALID_HANDLE, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
Referenced by ObDuplicateObject().
VOID ObpRemoveObjectRoutine (IN PVOID Object, IN BOOLEAN CalledOnWorkerThread)
Definition at line 2625 of file obref.c.
References _UNICODE_STRING::Buffer, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, DeleteSecurityDescriptor, ExFreePool(), _OBJECT_HEADER::Flags, IsListEmpty, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_HEADER_NAME_INFO::Name, NULL, OB_FLAG_DELETED_INLINE, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpEndTypeSpecificCallOut, ObpEnterObjectTypeMutex, ObpFreeObject(), ObpLeaveObjectTypeMutex, ObpValidateIrql, PAGED_CODE, RemoveEntryList(), _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, Status, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_HEADER_CREATOR_INFO::TypeList.
Referenced by ObfDereferenceObject(), and ObpProcessRemoveObjectQueue().
NTSTATUS ObReferenceFileObjectForWrite (IN HANDLE Handle, IN KPROCESSOR_MODE AccessMode, OUT PVOID * FileObject, OUT POBJECT_HANDLE_INFORMATION HandleInformation)
Definition at line 1580 of file obref.c.
References ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _OBJECT_HEADER::Body, DecodeKernelHandle, ExGetHandleInfo, ExMapHandleToPointerEx(), ExUnlockHandleTableEntry(), FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, IoComputeDesiredAccessFileObject(), KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KernelMode, _OBJECT_TYPE::Name, NT_SUCCESS, NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, ObpAuditObjectAccess(), ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), ObpValidateIrql, PsGetCurrentProcessByThread, PsGetCurrentThread(), SeComputeGrantedAccesses, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_HANDLE, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and _OBJECT_HEADER::Type.
Referenced by NtWriteFile().
NTSTATUS ObReferenceObjectByHandle (__in HANDLE Handle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PVOID * Object, __out_opt POBJECT_HANDLE_INFORMATION HandleInformation)
Definition at line 1061 of file obref.c.
References ARGUMENT_PRESENT, ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _OBJECT_HEADER::Body, DecodeKernelHandle, ExGetHandleInfo, ExMapHandleToPointerEx(), ExUnlockHandleTableEntry(), FLG_KERNEL_STACK_TRACE_DB, _EPROCESS::GrantedAccess, _ETHREAD::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KernelMode, _OBJECT_TYPE::Name, NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, ObpAuditObjectAccess(), ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), ObpValidateIrql, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, PsThreadType, ReadForWriteAccess, SeComputeDeniedAccesses, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_HANDLE, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and _OBJECT_HEADER::Type.
NTSTATUS ObReferenceObjectByName (__in PUNICODE_STRING ObjectName, __in ULONG Attributes, __in_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __in POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PVOID ParseContext, __out PVOID * Object)
Definition at line 1991 of file obref.c.
References ARGUMENT_PRESENT, FALSE, _AUX_ACCESS_DATA::GenericMapping, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), ObpCaptureObjectName(), ObpCheckObjectReference(), ObpFreeObjectNameBuffer(), ObpLookupObjectName(), ObpReleaseLookupContext(), ObpValidateIrql, PAGED_CODE, SeCreateAccessState(), SeDeleteAccessState(), Status, STATUS_OBJECT_NAME_INVALID, and TRUE.
Referenced by IopGetDriverPathInformation(), NtSecureConnectPort(), and ObShutdownSystem().
NTSTATUS ObReferenceObjectByPointer (__in PVOID Object, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode)
Definition at line 2169 of file obref.c.
References KernelMode, OBJECT_TO_OBJECT_HEADER, ObpIncrPointerCount, ObpSymbolicLinkObjectType, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, _OBJECT_HEADER::Type, and UNREFERENCED_PARAMETER.
Referenced by NtImpersonateAnonymousToken(), ObOpenObjectByPointer(), ObpLookupObjectName(), ObpParseSymbolicLink(), WmipQueryAllData(), WmipQuerySetExecuteSI(), WmipQueueNotification(), WmipRegisterDevice(), WmipTraceIo(), WmipTranslateFileHandle(), and WmipWriteMBToObject().
LONG_PTR FASTCALL ObReferenceObjectEx (IN PVOID Object, IN ULONG Count)
Definition at line 2305 of file obref.c.
References OBJECT_TO_OBJECT_HEADER, and ObpIncrPointerCountEx.
Referenced by ObFastReferenceObject(), ObFastReplaceObject(), ObInitializeFastReference(), and PspCreateThread().
BOOLEAN FASTCALL ObReferenceObjectSafe (IN PVOID Object)
Definition at line 2372 of file obref.c.
References FALSE, OBJECT_TO_OBJECT_HEADER, ObpPushStackInfo, ObpSafeInterlockedIncrement(), ObpTraceEnabled, _OBJECT_HEADER::PointerCount, and TRUE.
Referenced by CmpFlushNotifiesOnKeyBodyList(), ExpTimerDpcRoutine(), NtImpersonateClientOfPort(), NtRequestPort(), ObpCreateTypeArray(), PsEnumProcesses(), PsGetNextJob(), PsGetNextJobProcess(), PsGetNextProcess(), PsGetNextProcessThread(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PspExitThread(), PspGetJobFromSet(), PspGetNextJobProcess(), SepCleanupLUIDDeviceMapDirectory(), WmipCreatePumpThreadRoutine(), and WmipProcessEvent().
Variable Documentation
BOOLEAN ObpTraceEnabled = FALSE
Definition at line 48 of file obref.c.
Referenced by ObCreateObject(), ObfDereferenceObject(), ObpProcessRemoveObjectQueue(), and ObReferenceObjectSafe().
ULONG ObpTraceNoDeregister = 0
Definition at line 44 of file obref.c.
Referenced by ObfDereferenceObject(), and ObpProcessRemoveObjectQueue().
ULONG ObpTracePoolTags[16]
Definition at line 47 of file obref.c.
WCHAR ObpTracePoolTagsBuffer[128] = { 0 }
Definition at line 45 of file obref.c.
ULONG ObpTracePoolTagsLength = sizeof(ObpTracePoolTagsBuffer)
Definition at line 46 of file obref.c.