Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psenum.c File Reference
psenum.c File Reference
#include "psp.h"
Functions
NTSTATUS NtGetNextProcess (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewProcessHandle)
NTSTATUS NtGetNextThread (__in HANDLE ProcessHandle, __in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewThreadHandle)
NTSTATUS PsEnumProcesses (IN PROCESS_ENUM_ROUTINE CallBack, IN PVOID Context)
NTSTATUS PsEnumProcessThreads (IN PEPROCESS Process, IN THREAD_ENUM_ROUTINE CallBack, IN PVOID Context)
PEJOB PsGetNextJob (IN PEJOB Job)
PEPROCESS PsGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
PEPROCESS PsGetNextProcess (IN PEPROCESS Process)
PETHREAD PsGetNextProcessThread (IN PEPROCESS Process, IN PETHREAD Thread)
PEPROCESS PspGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
VOID PspQuitNextJobProcess (IN PEPROCESS Process)
VOID PsQuitNextJob (IN PEJOB Job)
VOID PsQuitNextJobProcess (IN PEPROCESS Process)
VOID PsQuitNextProcess (IN PEPROCESS Process)
VOID PsQuitNextProcessThread (IN PETHREAD Thread)
Function Documentation
NTSTATUS NtGetNextProcess (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewProcessHandle)
Definition at line 595 of file psenum.c.
References except, ExSystemExceptionFilter(), _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObReferenceObjectByHandle, ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForWriteHandle, PROCESS_ALL_ACCESS, PsGetNextProcess(), PsProcessType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_NO_MORE_ENTRIES, and _OBJECT_TYPE::TypeInfo.
NTSTATUS NtGetNextThread (__in HANDLE ProcessHandle, __in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewThreadHandle)
Definition at line 742 of file psenum.c.
References except, ExSystemExceptionFilter(), _OBJECT_TYPE_INITIALIZER::GenericMapping, _ETHREAD::GrantedAccess, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObReferenceObjectByHandle, ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForWriteHandle, PROCESS_ALL_ACCESS, PROCESS_QUERY_INFORMATION, PsGetNextProcessThread(), PsProcessType, PsThreadType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_NO_MORE_ENTRIES, THREAD_TO_PROCESS, and _OBJECT_TYPE::TypeInfo.
NTSTATUS PsEnumProcesses (IN PROCESS_ENUM_ROUTINE CallBack, IN PVOID Context)
Definition at line 39 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PsActiveProcessHead, PsGetCurrentThread(), PspLockProcessList(), PspUnlockProcessList(), Status, and STATUS_SUCCESS.
Referenced by PsShutdownSystem().
NTSTATUS PsEnumProcessThreads (IN PEPROCESS Process, IN THREAD_ENUM_ROUTINE CallBack, IN PVOID Context)
Definition at line 291 of file psenum.c.
References NT_SUCCESS, NULL, PsGetNextProcessThread(), PsQuitNextProcessThread(), Status, and STATUS_SUCCESS.
PEJOB PsGetNextJob (IN PEJOB Job)
Definition at line 332 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PsGetCurrentThread(), PspJobList, PspLockJobListShared(), and PspUnlockJobListShared().
Referenced by PsEnforceExecutionTimeLimits().
PEPROCESS PsGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
Definition at line 433 of file psenum.c.
References CONTAINING_RECORD, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), _ETHREAD::Tcb, and TRUE.
Referenced by PsEnforceExecutionTimeLimits(), and PspTerminateAllProcessesInJob().
PEPROCESS PsGetNextProcess (IN PEPROCESS Process)
Definition at line 110 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PsActiveProcessHead, PsGetCurrentThread(), PspLockProcessList(), and PspUnlockProcessList().
Referenced by DbgkpCloseObject(), ExpDebuggerWorker(), ExpGetProcessInformation(), NtGetNextProcess(), PerfInfoFileNameRunDown(), PsShutdownSystem(), and PsWaitForAllProcesses().
PETHREAD PsGetNextProcessThread (IN PEPROCESS Process, IN PETHREAD Thread)
Definition at line 210 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), PspLockProcessShared(), and PspUnlockProcessShared().
Referenced by DbgkpPostFakeThreadMessages(), DbgkpSetProcessDebugObject(), ExSwapinWorkerThreads(), NtGetNextThread(), NtSetInformationProcess(), NtSetInformationThread(), NtTerminateProcess(), PsEnumProcessThreads(), PspTerminateProcess(), PspWaitForUsermodeExit(), PsResumeProcess(), and PsSuspendProcess().
PEPROCESS PspGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
Definition at line 519 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObjectDeferDelete(), ObReferenceObjectSafe(), and PAGED_CODE.
Referenced by PspApplyJobLimitsToProcessSet().
VOID PspQuitNextJobProcess (IN PEPROCESS Process)
Definition at line 572 of file psenum.c.
References ObDereferenceObjectDeferDelete().
VOID PsQuitNextJob (IN PEJOB Job)
Definition at line 410 of file psenum.c.
References ObDereferenceObject().
VOID PsQuitNextJobProcess (IN PEPROCESS Process)
Definition at line 496 of file psenum.c.
References ObDereferenceObject().
VOID PsQuitNextProcess (IN PEPROCESS Process)
Definition at line 187 of file psenum.c.
References ObDereferenceObject().
Referenced by ExpDebuggerWorker(), ExpGetProcessInformation(), and PsWaitForAllProcesses().
VOID PsQuitNextProcessThread (IN PETHREAD Thread)
Definition at line 268 of file psenum.c.
References ObDereferenceObject().
Referenced by DbgkpPostFakeThreadMessages(), PsEnumProcessThreads(), and PspWaitForUsermodeExit().