Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivechek.c File Reference
hivechek.c File Reference
#include "cmp.h"
Functions
ULONG HvCheckBin (PHHIVE Hive, PHBIN Bin, PULONG Storage)
ULONG HvCheckHive (PHHIVE Hive, PULONG Storage OPTIONAL)
Variables
struct {
PHBIN Bin
PHCELL CellPoint
ULONG Status
} HvCheckBinDebug
struct {
PHBIN BinPoint
PHHIVE Hive
HCELL_INDEX MapPoint
ULONG Space
ULONG Status
} HvCheckHiveDebug
Function Documentation
ULONG HvCheckBin (PHHIVE Hive, PHBIN Bin, PULONG Storage)
Definition at line 204 of file hivechek.c.
References ARGUMENT_PRESENT, Bin, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FIELD_OFFSET, HBIN_NIL, HvCheckBinDebug, _HCELL::NewCell, _HCELL::OldCell, _HCELL::Size, _HBIN::Size, _HCELL::u, and USE_OLD_CELL.
Referenced by HvCheckHive().
ULONG HvCheckHive (PHHIVE Hive, PULONG Storage OPTIONAL)
Definition at line 49 of file hivechek.c.
References ARGUMENT_PRESENT, ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CmpMapThisBin(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HCELL_NIL, Hive, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvCheckBin(), HvCheckHiveDebug, HvpGetCellMap(), _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, Stable, _HHIVE::Storage, and Volatile.
Referenced by CmCheckRegistry(), and HvRefreshHive().
Variable Documentation
PHBIN Bin
Definition at line 38 of file hivechek.c.
Referenced by HvCheckBin(), and HvCheckHive().
PHBIN BinPoint
Definition at line 34 of file hivechek.c.
PHCELL CellPoint
Definition at line 40 of file hivechek.c.
PHHIVE Hive
Definition at line 30 of file hivechek.c.
Referenced by HvCheckHive().
struct { ... } HvCheckBinDebug
Referenced by HvCheckBin().
struct { ... } HvCheckHiveDebug
Referenced by HvCheckHive().
HCELL_INDEX MapPoint
Definition at line 33 of file hivechek.c.
ULONG Space
Definition at line 32 of file hivechek.c.
ULONG Status
Definition at line 31 of file hivechek.c.