Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/nls.c File Reference
nls.c File Reference
#include "ntrtlp.h"
Macros
#define __max(a, b) (((a) > (b)) ? (a) : (b))
#define __min(a, b) (((a) < (b)) ? (a) : (b))
#define ASCII_CRLF 0x0A0D
#define BYTE_ORDER_MARK 0xFEFF
#define LINE_SEPARATOR 0x2028
#define NETBIOS_NAME_LEN 16
#define PARAGRAPH_SEPARATOR 0x2029
#define REVERSE_BYTE_ORDER_MARK 0xFFFE
#define UNICODE_CJK_SPACE 0x3000
#define UNICODE_CR 0x000D
#define UNICODE_FFFF 0xFFFF
#define UNICODE_LF 0x000A
#define UNICODE_R_CJK_SPACE 0x0030 /* Ambiguous - same as ASCII '0' */
#define UNICODE_R_CR 0x0D00
#define UNICODE_R_LF 0x0A00
#define UNICODE_R_SPACE 0x2000
#define UNICODE_R_TAB 0x0900
#define UNICODE_SPACE 0x0020
#define UNICODE_TAB 0x0009
Functions
WCHAR RtlAnsiCharToUnicodeChar (IN OUT PUCHAR *SourceCharacter)
NTSTATUS RtlAnsiStringToUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCANSI_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlAppendUnicodeStringToString (IN OUT PUNICODE_STRING Destination, IN PCUNICODE_STRING Source)
NTSTATUS RtlAppendUnicodeToString (IN PUNICODE_STRING Destination, IN PCWSTR Source OPTIONAL)
LONG RtlCompareUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
VOID RtlCopyUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString OPTIONAL)
BOOLEAN RtlCreateUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCWSTR SourceString)
NTSTATUS RtlDnsHostNameToComputerName (OUT PUNICODE_STRING ComputerNameString, IN PCUNICODE_STRING DnsHostNameString, IN BOOLEAN AllocateComputerNameString)
WCHAR RtlDowncaseUnicodeChar (IN WCHAR SourceCharacter)
NTSTATUS RtlDowncaseUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlDuplicateUnicodeString (ULONG Flags, PCUNICODE_STRING StringIn, PUNICODE_STRING StringOut)
BOOLEAN RtlEqualComputerName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
BOOLEAN RtlEqualDomainName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
BOOLEAN RtlEqualUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
NTSTATUS NTAPI RtlFindAndReplaceCharacterInString (ULONG Flags, PVOID Reserved, PUNICODE_STRING String, WCHAR Find, WCHAR Replace)
NTSTATUS RtlFindCharInUnicodeString (ULONG Flags, PCUNICODE_STRING StringToSearch, PCUNICODE_STRING CharSet, USHORT *NonInclusivePrefixLength)
VOID RtlFreeAnsiString (IN OUT PANSI_STRING AnsiString)
VOID RtlFreeOemString (IN OUT POEM_STRING OemString)
VOID RtlFreeUnicodeString (IN OUT PUNICODE_STRING UnicodeString)
NTSTATUS RtlHashUnicodeString (const UNICODE_STRING *String, BOOLEAN CaseInSensitive, ULONG HashAlgorithm, PULONG HashValue)
BOOLEAN RtlIsTextUnicode (IN PVOID Buffer, IN ULONG Size, IN OUT PULONG Result OPTIONAL)
NTSTATUS RtlOemStringToCountedUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCOEM_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlOemStringToUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCOEM_STRING SourceString, IN BOOLEAN AllocateDestinationString)
BOOLEAN RtlPrefixUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
NTSTATUS RtlUnicodeStringToAnsiString (OUT PANSI_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlUnicodeStringToCountedOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlUnicodeStringToOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
WCHAR RtlUpcaseUnicodeChar (IN WCHAR SourceCharacter)
NTSTATUS RtlUpcaseUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlUpcaseUnicodeStringToAnsiString (OUT PANSI_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlUpcaseUnicodeStringToCountedOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlUpcaseUnicodeStringToOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSTATUS RtlValidateUnicodeString (ULONG Flags, const UNICODE_STRING *String)
ULONG RtlxAnsiStringToUnicodeSize (IN PCANSI_STRING AnsiString)
ULONG RtlxOemStringToUnicodeSize (IN PCOEM_STRING OemString)
ULONG RtlxUnicodeStringToAnsiSize (IN PCUNICODE_STRING UnicodeString)
ULONG RtlxUnicodeStringToOemSize (IN PCUNICODE_STRING UnicodeString)
Variables
const PUSHORT NlsAnsiToUnicodeData
const PUSHORT NlsLeadByteInfo
Macro Definition Documentation
#define __max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 2205 of file nls.c.
Referenced by RtlIsTextUnicode().
#define __min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 2206 of file nls.c.
Referenced by RtlIsTextUnicode().
#define ASCII_CRLF 0x0A0D
Definition at line 2203 of file nls.c.
Referenced by RtlIsTextUnicode().
#define BYTE_ORDER_MARK 0xFEFF
Definition at line 2186 of file nls.c.
Referenced by RtlIsTextUnicode().
#define LINE_SEPARATOR 0x2028
Definition at line 2189 of file nls.c.
Referenced by RtlIsTextUnicode().
#define NETBIOS_NAME_LEN 16
Definition at line 71 of file nls.c.
Referenced by RtlDnsHostNameToComputerName().
#define PARAGRAPH_SEPARATOR 0x2029
Definition at line 2188 of file nls.c.
Referenced by RtlIsTextUnicode().
#define REVERSE_BYTE_ORDER_MARK 0xFFFE
Definition at line 2185 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_CJK_SPACE 0x3000
Definition at line 2195 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_CR 0x000D
Definition at line 2193 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_FFFF 0xFFFF
Definition at line 2184 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_LF 0x000A
Definition at line 2192 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_R_CJK_SPACE 0x0030 /* Ambiguous - same as ASCII '0' */
Definition at line 2201 of file nls.c.
#define UNICODE_R_CR 0x0D00
Definition at line 2199 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_R_LF 0x0A00
Definition at line 2198 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_R_SPACE 0x2000
Definition at line 2200 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_R_TAB 0x0900
Definition at line 2197 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_SPACE 0x0020
Definition at line 2194 of file nls.c.
Referenced by RtlIsTextUnicode().
#define UNICODE_TAB 0x0009
Definition at line 2191 of file nls.c.
Referenced by RtlIsTextUnicode().
Function Documentation
WCHAR RtlAnsiCharToUnicodeChar (IN OUT PUCHAR * SourceCharacter)
Definition at line 168 of file nls.c.
References NlsLeadByteInfo, NT_SUCCESS, NULL, RTL_PAGED_CODE, and RtlMultiByteToUnicodeN().
NTSTATUS RtlAnsiStringToUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCANSI_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 77 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_OUT, Index, MAX_USTRING, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlAnsiStringToUnicodeSize, RtlFreeStringRoutine, RtlMultiByteToUnicodeN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_SUCCESS, and UNICODE_NULL.
NTSTATUS RtlAppendUnicodeStringToString (IN OUT PUNICODE_STRING Destination, IN PCUNICODE_STRING Source)
Definition at line 1988 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, RtlMoveMemory, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, UNALIGNED, and UNICODE_NULL.
NTSTATUS RtlAppendUnicodeToString (IN PUNICODE_STRING Destination, IN PCWSTR Source OPTIONAL)
Definition at line 1921 of file nls.c.
References ARGUMENT_PRESENT, ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, _UNICODE_STRING::Length, NT_SUCCESS, RtlInitUnicodeStringEx(), RtlMoveMemory, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, UNALIGNED, and UNICODE_NULL.
LONG RtlCompareUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
Definition at line 1577 of file nls.c.
References ASSERT, ASSERT_WELL_FORMED_UNICODE_STRING_IN, NLS_UPCASE, and RTL_PAGED_CODE.
VOID RtlCopyUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString OPTIONAL)
Definition at line 1861 of file nls.c.
References ARGUMENT_PRESENT, ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, RtlCopyMemory, UNALIGNED, and UNICODE_NULL.
BOOLEAN RtlCreateUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCWSTR SourceString)
Definition at line 2042 of file nls.c.
References FALSE, MAX_USTRING, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlCopyMemory, TRUE, UNICODE_NULL, and wcslen().
Referenced by IopBootLog(), IopCopyBootLogRegistryToFile(), ObpCreateDosDevicesDirectory(), RtlConvertSidToUnicodeString(), WmipQueryGLRegistryRoutine(), WmipStartGlobalLogger(), WmipStartLogger(), WmipSwitchToNewFile(), WmipVerifyLoggerInfo(), and WmiUpdateTrace().
NTSTATUS RtlDnsHostNameToComputerName (OUT PUNICODE_STRING ComputerNameString, IN PCUNICODE_STRING DnsHostNameString, IN BOOLEAN AllocateComputerNameString)
Definition at line 2629 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, _STRING::Buffer, _UNICODE_STRING::Buffer, _STRING::Length, _UNICODE_STRING::Length, _STRING::MaximumLength, NETBIOS_NAME_LEN, NT_SUCCESS, RTL_PAGED_CODE, RtlOemStringToUnicodeString(), RtlpDidUnicodeToOemWork(), RtlUpcaseUnicodeToOemN(), Status, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_COMPUTER_NAME, and STATUS_SUCCESS.
WCHAR RtlDowncaseUnicodeChar (IN WCHAR SourceCharacter)
Definition at line 1230 of file nls.c.
References NLS_DOWNCASE, and RTL_PAGED_CODE.
Referenced by RtlFindAndReplaceCharacterInString(), and RtlFindCharInUnicodeString().
NTSTATUS RtlDowncaseUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 1119 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, Index, NLS_DOWNCASE, RTL_PAGED_CODE, RtlAllocateStringRoutine, STATUS_BUFFER_OVERFLOW, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS RtlDuplicateUnicodeString (ULONG Flags, PCUNICODE_STRING StringIn, PUNICODE_STRING StringOut)
Definition at line 2882 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_OUT, _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, RTL_DUPLICATE_UNICODE_STRING_ALLOCATE_NULL_STRING, RTL_DUPLICATE_UNICODE_STRING_NULL_TERMINATE, RtlAllocateStringRoutine, RtlCopyMemory, RtlValidateUnicodeString(), Status, STATUS_INVALID_PARAMETER, STATUS_NAME_TOO_LONG, STATUS_NO_MEMORY, and STATUS_SUCCESS.
BOOLEAN RtlEqualComputerName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
Definition at line 2147 of file nls.c.
References RtlEqualDomainName().
BOOLEAN RtlEqualDomainName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
Definition at line 2069 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, FALSE, NT_SUCCESS, RTL_PAGED_CODE, RtlEqualString(), RtlFreeOemString(), RtlUpcaseUnicodeStringToOemString(), Status, and TRUE.
Referenced by RtlEqualComputerName().
BOOLEAN RtlEqualUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
Definition at line 1675 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, FALSE, NLS_UPCASE, RTL_PAGED_CODE, and TRUE.
NTSTATUS NTAPI RtlFindAndReplaceCharacterInString (ULONG Flags, PVOID Reserved, PUNICODE_STRING String, WCHAR Find, WCHAR Replace)
Definition at line 3151 of file nls.c.
References _UNICODE_STRING::Buffer, Index, NULL, RTL_FIND_AND_REPLACE_CHARACTER_IN_STRING_CASE_SENSITIVE, RTL_STRING_GET_LENGTH_CHARS, RtlDowncaseUnicodeChar(), RtlUpcaseUnicodeChar(), Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlFindCharInUnicodeString (ULONG Flags, PCUNICODE_STRING StringToSearch, PCUNICODE_STRING CharSet, USHORT * NonInclusivePrefixLength)
Definition at line 2968 of file nls.c.
References _UNICODE_STRING::Buffer, FALSE, _UNICODE_STRING::Length, NT_SUCCESS, NULL, RTL_FIND_CHAR_IN_UNICODE_STRING_CASE_INSENSITIVE, RTL_FIND_CHAR_IN_UNICODE_STRING_COMPLEMENT_CHAR_SET, RTL_FIND_CHAR_IN_UNICODE_STRING_START_AT_END, RTL_NUMBER_OF, RtlDowncaseUnicodeChar(), RtlValidateUnicodeString(), Status, STATUS_INVALID_PARAMETER, STATUS_NOT_FOUND, and STATUS_SUCCESS.
VOID RtlFreeAnsiString (IN OUT PANSI_STRING AnsiString)
Definition at line 1302 of file nls.c.
References memset(), RTL_PAGED_CODE, and RtlFreeStringRoutine.
VOID RtlFreeOemString (IN OUT POEM_STRING OemString)
Definition at line 1336 of file nls.c.
References RTL_PAGED_CODE, and RtlFreeStringRoutine.
Referenced by RtlEqualDomainName().
VOID RtlFreeUnicodeString (IN OUT PUNICODE_STRING UnicodeString)
Definition at line 1267 of file nls.c.
References memset(), RTL_PAGED_CODE, and RtlFreeStringRoutine.
NTSTATUS RtlHashUnicodeString (const UNICODE_STRING * String, BOOLEAN CaseInSensitive, ULONG HashAlgorithm, PULONG HashValue)
Definition at line 2785 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, _UNICODE_STRING::Buffer, HASH_STRING_ALGORITHM_DEFAULT, HASH_STRING_ALGORITHM_X65599, _UNICODE_STRING::Length, NLS_UPCASE, NULL, Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
BOOLEAN RtlIsTextUnicode (IN PVOID Buffer, IN ULONG Size, IN OUT PULONG Result OPTIONAL)
Definition at line 2210 of file nls.c.
References __max, __min, ARGUMENT_PRESENT, ASCII_CRLF, BYTE_ORDER_MARK, FALSE, HIBYTE, IS_TEXT_UNICODE_ASCII16, IS_TEXT_UNICODE_CONTROLS, IS_TEXT_UNICODE_DBCS_LEADBYTE, IS_TEXT_UNICODE_ILLEGAL_CHARS, IS_TEXT_UNICODE_NOT_ASCII_MASK, IS_TEXT_UNICODE_NOT_UNICODE_MASK, IS_TEXT_UNICODE_NULL_BYTES, IS_TEXT_UNICODE_ODD_LENGTH, IS_TEXT_UNICODE_REVERSE_ASCII16, IS_TEXT_UNICODE_REVERSE_CONTROLS, IS_TEXT_UNICODE_REVERSE_MASK, IS_TEXT_UNICODE_REVERSE_SIGNATURE, IS_TEXT_UNICODE_REVERSE_STATISTICS, IS_TEXT_UNICODE_SIGNATURE, IS_TEXT_UNICODE_STATISTICS, IS_TEXT_UNICODE_UNICODE_MASK, LINE_SEPARATOR, LOBYTE, NlsLeadByteInfo, NlsMbCodePageTag, PARAGRAPH_SEPARATOR, REVERSE_BYTE_ORDER_MARK, TRUE, UNALIGNED, UNICODE_CJK_SPACE, UNICODE_CR, UNICODE_FFFF, UNICODE_LF, UNICODE_NULL, UNICODE_R_CR, UNICODE_R_LF, UNICODE_R_SPACE, UNICODE_R_TAB, UNICODE_SPACE, and UNICODE_TAB.
NTSTATUS RtlOemStringToCountedUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCOEM_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 717 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_OUT, Index, MAX_USTRING, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlOemStringToCountedUnicodeSize, RtlOemToUnicodeN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS RtlOemStringToUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCOEM_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 434 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_OUT, Index, MAX_USTRING, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlOemStringToUnicodeSize, RtlOemToUnicodeN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by RtlDnsHostNameToComputerName().
BOOLEAN RtlPrefixUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
Definition at line 1780 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, FALSE, NLS_UPCASE, RTL_PAGED_CODE, and TRUE.
Referenced by HalpNextDriveLetter(), IoAssignDriveLetters(), and ObpIsUnsecureName().
NTSTATUS RtlUnicodeStringToAnsiString (OUT PANSI_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 237 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, Index, MAXUSHORT, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlUnicodeStringToAnsiSize, RtlUnicodeToMultiByteN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS RtlUnicodeStringToCountedOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 819 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, Index, MAXUSHORT, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlpDidUnicodeToOemWork(), RtlUnicodeStringToCountedOemSize, RtlUnicodeToOemN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_SUCCESS, and STATUS_UNMAPPABLE_CHARACTER.
NTSTATUS RtlUnicodeStringToOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 525 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, Index, MAXUSHORT, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlUnicodeStringToOemSize, RtlUnicodeToOemN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, and STATUS_SUCCESS.
WCHAR RtlUpcaseUnicodeChar (IN WCHAR SourceCharacter)
Definition at line 1193 of file nls.c.
References NLS_UPCASE, and RTL_PAGED_CODE.
Referenced by RtlFindAndReplaceCharacterInString().
NTSTATUS RtlUpcaseUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 1045 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, Index, NLS_UPCASE, RTL_PAGED_CODE, RtlAllocateStringRoutine, STATUS_BUFFER_OVERFLOW, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS RtlUpcaseUnicodeStringToAnsiString (OUT PANSI_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 343 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, Index, MAXUSHORT, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlUnicodeStringToAnsiSize, RtlUpcaseUnicodeToMultiByteN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS RtlUpcaseUnicodeStringToCountedOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 932 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, Index, MAXUSHORT, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlpDidUnicodeToOemWork(), RtlUnicodeStringToCountedOemSize, RtlUpcaseUnicodeToOemN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_SUCCESS, and STATUS_UNMAPPABLE_CHARACTER.
NTSTATUS RtlUpcaseUnicodeStringToOemString (OUT POEM_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 616 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, Index, MAXUSHORT, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlFreeStringRoutine, RtlpDidUnicodeToOemWork(), RtlUnicodeStringToOemSize, RtlUpcaseUnicodeToOemN(), STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_SUCCESS, and STATUS_UNMAPPABLE_CHARACTER.
Referenced by RtlEqualDomainName().
NTSTATUS RtlValidateUnicodeString (ULONG Flags, const UNICODE_STRING * String)
Definition at line 2845 of file nls.c.
References ASSERT, _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlDuplicateUnicodeString(), and RtlFindCharInUnicodeString().
ULONG RtlxAnsiStringToUnicodeSize (IN PCANSI_STRING AnsiString)
Definition at line 1478 of file nls.c.
References RTL_PAGED_CODE, RtlMultiByteToUnicodeSize(), and UNICODE_NULL.
ULONG RtlxOemStringToUnicodeSize (IN PCOEM_STRING OemString)
Definition at line 1524 of file nls.c.
References RTL_PAGED_CODE, RtlMultiByteToUnicodeSize(), and UNICODE_NULL.
ULONG RtlxUnicodeStringToAnsiSize (IN PCUNICODE_STRING UnicodeString)
Definition at line 1367 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, RTL_PAGED_CODE, and RtlUnicodeToMultiByteSize().
ULONG RtlxUnicodeStringToOemSize (IN PCUNICODE_STRING UnicodeString)
Definition at line 1419 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, RTL_PAGED_CODE, and RtlUnicodeToMultiByteSize().
Variable Documentation
const PUSHORT NlsAnsiToUnicodeData
Definition at line 82 of file nlsxlat.c.
const PUSHORT NlsLeadByteInfo
Definition at line 80 of file nlsxlat.c.
Referenced by CompareNamesCaseSensitive(), ComputeNameLength(), RtlAnsiCharToUnicodeChar(), and RtlIsTextUnicode().