Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/prefix.c File Reference
prefix.c File Reference
#include "ntrtlp.h"
Macros
#define RTL_NTC_INTERNAL ((CSHORT)0x0202)
#define RTL_NTC_PREFIX_TABLE ((CSHORT)0x0200)
#define RTL_NTC_ROOT ((CSHORT)0x0201)
#define RTL_NTC_UNICODE_CASE_MATCH ((CSHORT)0x0803)
#define RTL_NTC_UNICODE_INTERNAL ((CSHORT)0x0802)
#define RTL_NTC_UNICODE_PREFIX_TABLE ((CSHORT)0x0800)
#define RTL_NTC_UNICODE_ROOT ((CSHORT)0x0801)
Typedefs
typedef enum _COMPARISON COMPARISON
Enumerations
enum _COMPARISON { IsLessThan, IsPrefix, IsEqual, IsGreaterThan }
Functions
COMPARISON CompareNamesCaseSensitive (IN PSTRING Prefix, IN PSTRING Name)
COMPARISON CompareUnicodeStrings (IN PUNICODE_STRING Prefix, IN PUNICODE_STRING Name, IN ULONG CaseInsensitiveIndex)
CLONG ComputeNameLength (IN PSTRING Name)
CLONG ComputeUnicodeNameLength (IN PUNICODE_STRING Name)
PPREFIX_TABLE_ENTRY PfxFindPrefix (IN PPREFIX_TABLE PrefixTable, IN PSTRING FullName)
VOID PfxInitialize (IN PPREFIX_TABLE PrefixTable)
BOOLEAN PfxInsertPrefix (IN PPREFIX_TABLE PrefixTable, IN PSTRING Prefix, IN PPREFIX_TABLE_ENTRY PrefixTableEntry)
VOID PfxRemovePrefix (IN PPREFIX_TABLE PrefixTable, IN PPREFIX_TABLE_ENTRY PrefixTableEntry)
PUNICODE_PREFIX_TABLE_ENTRY RtlFindUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN PUNICODE_STRING FullName, IN ULONG CaseInsensitiveIndex)
VOID RtlInitializeUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable)
BOOLEAN RtlInsertUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN PUNICODE_STRING Prefix, IN PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
PUNICODE_PREFIX_TABLE_ENTRY RtlNextUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN BOOLEAN Restart)
VOID RtlRemoveUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
Macro Definition Documentation
#define RTL_NTC_INTERNAL ((CSHORT)0x0202)
Definition at line 94 of file prefix.c.
Referenced by PfxFindPrefix(), PfxInsertPrefix(), and PfxRemovePrefix().
#define RTL_NTC_PREFIX_TABLE ((CSHORT)0x0200)
Definition at line 92 of file prefix.c.
Referenced by PfxInitialize().
#define RTL_NTC_ROOT ((CSHORT)0x0201)
Definition at line 93 of file prefix.c.
Referenced by PfxFindPrefix(), PfxInsertPrefix(), and PfxRemovePrefix().
#define RTL_NTC_UNICODE_CASE_MATCH ((CSHORT)0x0803)
Definition at line 1017 of file prefix.c.
Referenced by RtlInsertUnicodePrefix(), RtlNextUnicodePrefix(), and RtlRemoveUnicodePrefix().
#define RTL_NTC_UNICODE_INTERNAL ((CSHORT)0x0802)
Definition at line 1016 of file prefix.c.
Referenced by RtlFindUnicodePrefix(), RtlInsertUnicodePrefix(), and RtlRemoveUnicodePrefix().
#define RTL_NTC_UNICODE_PREFIX_TABLE ((CSHORT)0x0800)
Definition at line 1014 of file prefix.c.
Referenced by RtlInitializeUnicodePrefix(), and RtlNextUnicodePrefix().
#define RTL_NTC_UNICODE_ROOT ((CSHORT)0x0801)
Definition at line 1015 of file prefix.c.
Referenced by RtlFindUnicodePrefix(), RtlInsertUnicodePrefix(), and RtlRemoveUnicodePrefix().
Typedef Documentation
typedef enum _COMPARISON COMPARISON
Enumeration Type Documentation
enum _COMPARISON
Enumerator
IsLessThan
IsPrefix
IsEqual
IsGreaterThan
Definition at line 41 of file prefix.c.
Function Documentation
COMPARISON CompareNamesCaseSensitive (IN PSTRING Prefix, IN PSTRING Name)
Definition at line 826 of file prefix.c.
References IsEqual, IsGreaterThan, IsLessThan, IsPrefix, NlsLeadByteInfo, NlsMbCodePageTag, RTL_PAGED_CODE, and RtlCompareMemory().
Referenced by PfxFindPrefix(), and PfxInsertPrefix().
COMPARISON CompareUnicodeStrings (IN PUNICODE_STRING Prefix, IN PUNICODE_STRING Name, IN ULONG CaseInsensitiveIndex)
Definition at line 2164 of file prefix.c.
References IsEqual, IsGreaterThan, IsLessThan, IsPrefix, NLS_UPCASE, and RTL_PAGED_CODE.
Referenced by RtlFindUnicodePrefix(), and RtlInsertUnicodePrefix().
CLONG ComputeNameLength (IN PSTRING Name)
Definition at line 736 of file prefix.c.
References Count, NlsLeadByteInfo, NlsMbCodePageTag, and RTL_PAGED_CODE.
Referenced by PfxFindPrefix(), and PfxInsertPrefix().
CLONG ComputeUnicodeNameLength (IN PUNICODE_STRING Name)
Definition at line 2098 of file prefix.c.
References Count, and RTL_PAGED_CODE.
Referenced by RtlFindUnicodePrefix(), and RtlInsertUnicodePrefix().
PPREFIX_TABLE_ENTRY PfxFindPrefix (IN PPREFIX_TABLE PrefixTable, IN PSTRING FullName)
Definition at line 564 of file prefix.c.
References CompareNamesCaseSensitive(), ComputeNameLength(), CONTAINING_RECORD, IsGreaterThan, IsLessThan, _PREFIX_TABLE_ENTRY::Links, _PREFIX_TABLE_ENTRY::NameLength, _PREFIX_TABLE_ENTRY::NextPrefixTree, _PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, _PREFIX_TABLE_ENTRY::Prefix, RTL_NTC_INTERNAL, RTL_NTC_ROOT, RTL_PAGED_CODE, RtlLeftChild, RtlRightChild, and RtlSplay().
VOID PfxInitialize (IN PPREFIX_TABLE PrefixTable)
Definition at line 98 of file prefix.c.
References RTL_NTC_PREFIX_TABLE, and RTL_PAGED_CODE.
BOOLEAN PfxInsertPrefix (IN PPREFIX_TABLE PrefixTable, IN PSTRING Prefix, IN PPREFIX_TABLE_ENTRY PrefixTableEntry)
Definition at line 136 of file prefix.c.
References CompareNamesCaseSensitive(), ComputeNameLength(), CONTAINING_RECORD, FALSE, IsEqual, IsGreaterThan, _PREFIX_TABLE_ENTRY::Links, _PREFIX_TABLE_ENTRY::NameLength, _PREFIX_TABLE_ENTRY::NextPrefixTree, _PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, Prefix, _PREFIX_TABLE_ENTRY::Prefix, RTL_NTC_INTERNAL, RTL_NTC_ROOT, RTL_PAGED_CODE, RtlInitializeSplayLinks, RtlInsertAsLeftChild, RtlInsertAsRightChild, RtlLeftChild, RtlRightChild, RtlSplay(), and TRUE.
VOID PfxRemovePrefix (IN PPREFIX_TABLE PrefixTable, IN PPREFIX_TABLE_ENTRY PrefixTableEntry)
Definition at line 398 of file prefix.c.
References CONTAINING_RECORD, _PREFIX_TABLE_ENTRY::Links, _PREFIX_TABLE_ENTRY::NextPrefixTree, _PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, RTL_NTC_INTERNAL, RTL_NTC_ROOT, RTL_PAGED_CODE, RtlDelete(), RtlIsRoot, and RtlParent.
PUNICODE_PREFIX_TABLE_ENTRY RtlFindUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN PUNICODE_STRING FullName, IN ULONG CaseInsensitiveIndex)
Definition at line 1683 of file prefix.c.
References _UNICODE_PREFIX_TABLE_ENTRY::CaseMatch, CompareUnicodeStrings(), ComputeUnicodeNameLength(), CONTAINING_RECORD, IsEqual, IsGreaterThan, IsLessThan, IsPrefix, _UNICODE_PREFIX_TABLE_ENTRY::Links, _UNICODE_PREFIX_TABLE_ENTRY::NameLength, _UNICODE_PREFIX_TABLE_ENTRY::NextPrefixTree, _UNICODE_PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, _UNICODE_PREFIX_TABLE_ENTRY::Prefix, RTL_NTC_UNICODE_INTERNAL, RTL_NTC_UNICODE_ROOT, RTL_PAGED_CODE, RtlLeftChild, RtlRightChild, and RtlSplay().
VOID RtlInitializeUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable)
Definition at line 1021 of file prefix.c.
References NULL, RTL_NTC_UNICODE_PREFIX_TABLE, and RTL_PAGED_CODE.
BOOLEAN RtlInsertUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN PUNICODE_STRING Prefix, IN PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
Definition at line 1058 of file prefix.c.
References _UNICODE_PREFIX_TABLE_ENTRY::CaseMatch, CompareUnicodeStrings(), ComputeUnicodeNameLength(), CONTAINING_RECORD, FALSE, IsEqual, IsGreaterThan, _UNICODE_PREFIX_TABLE_ENTRY::Links, MAXULONG, _UNICODE_PREFIX_TABLE_ENTRY::NameLength, _UNICODE_PREFIX_TABLE_ENTRY::NextPrefixTree, _UNICODE_PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, Prefix, _UNICODE_PREFIX_TABLE_ENTRY::Prefix, RTL_NTC_UNICODE_CASE_MATCH, RTL_NTC_UNICODE_INTERNAL, RTL_NTC_UNICODE_ROOT, RTL_PAGED_CODE, RtlInitializeSplayLinks, RtlInsertAsLeftChild, RtlInsertAsRightChild, RtlLeftChild, RtlRightChild, RtlSplay(), and TRUE.
PUNICODE_PREFIX_TABLE_ENTRY RtlNextUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN BOOLEAN Restart)
Definition at line 1931 of file prefix.c.
References _UNICODE_PREFIX_TABLE_ENTRY::CaseMatch, CONTAINING_RECORD, _UNICODE_PREFIX_TABLE_ENTRY::Links, _UNICODE_PREFIX_TABLE_ENTRY::NameLength, _UNICODE_PREFIX_TABLE_ENTRY::NextPrefixTree, _UNICODE_PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, RTL_NTC_UNICODE_CASE_MATCH, RTL_NTC_UNICODE_PREFIX_TABLE, RTL_PAGED_CODE, RtlIsRoot, RtlLeftChild, RtlParent, and RtlRealSuccessor().
VOID RtlRemoveUnicodePrefix (IN PUNICODE_PREFIX_TABLE PrefixTable, IN PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
Definition at line 1371 of file prefix.c.
References _UNICODE_PREFIX_TABLE_ENTRY::CaseMatch, CONTAINING_RECORD, _UNICODE_PREFIX_TABLE_ENTRY::Links, _UNICODE_PREFIX_TABLE_ENTRY::NextPrefixTree, _UNICODE_PREFIX_TABLE_ENTRY::NodeTypeCode, NULL, _RTL_SPLAY_LINKS::Parent, RTL_NTC_UNICODE_CASE_MATCH, RTL_NTC_UNICODE_INTERNAL, RTL_NTC_UNICODE_ROOT, RTL_PAGED_CODE, RtlDelete(), RtlIsLeftChild, RtlIsRoot, RtlLeftChild, RtlParent, and RtlRightChild.