Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmsubs2.c File Reference
cmsubs2.c File Reference
#include "cmp.h"
Macros
#define ALIGN_OFFSET(Offset)
#define ALIGN_OFFSET64(Offset)
Functions
NTSTATUS CmpQueryKeyData (PHHIVE Hive, PCM_KEY_NODE Node, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
NTSTATUS CmpQueryKeyDataFromCache (PCM_KEY_CONTROL_BLOCK Kcb, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
VALUE_SEARCH_RETURN_TYPE CmpQueryKeyValueData (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PPCM_CACHED_VALUE ContainingList, PCM_KEY_VALUE ValueKey, BOOLEAN ValueCached, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength, NTSTATUS *status)
Macro Definition Documentation
#define ALIGN_OFFSET (Offset)
Value:
(ULONG) \
        ((((ULONG)(Offset) + sizeof(ULONG)-1)) & (~(sizeof(ULONG) - 1)))
Definition at line 34 of file cmsubs2.c.
Referenced by CmpQueryKeyData(), and CmpQueryKeyValueData().
#define ALIGN_OFFSET64 (Offset)
Value:
(ULONG) \
        ((((ULONG)(Offset) + sizeof(ULONGLONG)-1)) & (~(sizeof(ULONGLONG) - 1)))
Definition at line 37 of file cmsubs2.c.
Referenced by CmpQueryKeyValueData().
Function Documentation
NTSTATUS CmpQueryKeyData (PHHIVE Hive, PCM_KEY_NODE Node, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
Definition at line 46 of file cmsubs2.c.
References ALIGN_OFFSET, _KEY_FULL_INFORMATION::Class, _CM_KEY_NODE::Class, _KEY_NODE_INFORMATION::ClassLength, _KEY_FULL_INFORMATION::ClassLength, _CM_KEY_NODE::ClassLength, _KEY_NODE_INFORMATION::ClassOffset, _KEY_FULL_INFORMATION::ClassOffset, CmpCopyCompressedName(), CmpHKeyNameLen, _CHILD_LIST::Count, FIELD_OFFSET, _CM_KEY_NODE::Flags, HvGetCell, HvReleaseCell, KEY_COMP_NAME, KeyBasicInformation, _KEY_INFORMATION::KeyBasicInformation, KeyFullInformation, _KEY_INFORMATION::KeyFullInformation, KeyNodeInformation, _KEY_INFORMATION::KeyNodeInformation, _KEY_BASIC_INFORMATION::LastWriteTime, _KEY_NODE_INFORMATION::LastWriteTime, _KEY_FULL_INFORMATION::LastWriteTime, _CM_KEY_NODE::LastWriteTime, _KEY_FULL_INFORMATION::MaxClassLen, _CM_KEY_NODE::MaxClassLen, _KEY_FULL_INFORMATION::MaxNameLen, _CM_KEY_NODE::MaxNameLen, _KEY_FULL_INFORMATION::MaxValueDataLen, _CM_KEY_NODE::MaxValueDataLen, _KEY_FULL_INFORMATION::MaxValueNameLen, _CM_KEY_NODE::MaxValueNameLen, _KEY_BASIC_INFORMATION::Name, _KEY_NODE_INFORMATION::Name, _CM_KEY_NODE::Name, _KEY_BASIC_INFORMATION::NameLength, _KEY_NODE_INFORMATION::NameLength, _CM_KEY_NODE::NameLength, NULL, RtlCopyMemory, Stable, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _KEY_FULL_INFORMATION::SubKeys, _KEY_BASIC_INFORMATION::TitleIndex, _KEY_NODE_INFORMATION::TitleIndex, _KEY_FULL_INFORMATION::TitleIndex, _CM_KEY_NODE::ValueList, _KEY_FULL_INFORMATION::Values, and Volatile.
Referenced by CmEnumerateKey(), and CmQueryKey().
NTSTATUS CmpQueryKeyDataFromCache (PCM_KEY_CONTROL_BLOCK Kcb, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
Definition at line 355 of file cmsubs2.c.
References ASSERT, CM_KCB_INVALID_CACHED_INFO, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, CM_PAGED_CODE, CmKdPrintEx, CmpCompressedNameSize(), _CM_NAME_CONTROL_BLOCK::Compressed, _CM_INDEX_HINT_BLOCK::Count, _CACHED_CHILD_LIST::Count, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, _CM_KEY_CONTROL_BLOCK::ExtFlags, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::IndexHint, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueDataLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueNameLen, KeyCachedInformation, _KEY_INFORMATION::KeyCachedInformation, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _KEY_CACHED_INFORMATION::LastWriteTime, _KEY_CACHED_INFORMATION::MaxNameLen, _KEY_CACHED_INFORMATION::MaxValueDataLen, _KEY_CACHED_INFORMATION::MaxValueNameLen, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _KEY_CACHED_INFORMATION::NameLength, _CM_NAME_CONTROL_BLOCK::NameLength, NULL, Stable, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _CM_KEY_CONTROL_BLOCK::SubKeyCount, _CM_KEY_NODE::SubKeyCounts, _KEY_CACHED_INFORMATION::SubKeys, _KEY_CACHED_INFORMATION::TitleIndex, _CM_KEY_CONTROL_BLOCK::ValueCache, _KEY_CACHED_INFORMATION::Values, and Volatile.
Referenced by CmQueryKey().
VALUE_SEARCH_RETURN_TYPE CmpQueryKeyValueData (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PPCM_CACHED_VALUE ContainingList, PCM_KEY_VALUE ValueKey, BOOLEAN ValueCached, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength, NTSTATUS * status)
Definition at line 514 of file cmsubs2.c.
References ALIGN_OFFSET, ALIGN_OFFSET64, ASSERT, CM_KEY_VALUE_SMALL, CmKdPrintEx, CmpCopyCompressedName(), CmpGetValueDataFromCache(), CmpIsHKeyValueSmall, CmpValueNameLen, _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64::Data, _CM_KEY_VALUE::Data, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64::DataLength, _CM_KEY_VALUE::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, ExFreePool(), FALSE, FIELD_OFFSET, _CM_KEY_VALUE::Flags, HCELL_NIL, Hive, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyValue, KeyValueBasicInformation, _KEY_VALUE_INFORMATION::KeyValueBasicInformation, KeyValueFullInformation, _KEY_VALUE_INFORMATION::KeyValueFullInformation, KeyValueFullInformationAlign64, KeyValuePartialInformation, _KEY_VALUE_INFORMATION::KeyValuePartialInformation, KeyValuePartialInformationAlign64, _KEY_VALUE_INFORMATION::KeyValuePartialInformationAlign64, _KEY_VALUE_BASIC_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::Name, _CM_KEY_VALUE::Name, _KEY_VALUE_BASIC_INFORMATION::NameLength, _KEY_VALUE_FULL_INFORMATION::NameLength, _CM_KEY_VALUE::NameLength, NULL, RtlCopyMemory, SearchSuccess, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _KEY_VALUE_BASIC_INFORMATION::TitleIndex, _KEY_VALUE_FULL_INFORMATION::TitleIndex, _KEY_VALUE_PARTIAL_INFORMATION::TitleIndex, TRUE, _KEY_VALUE_BASIC_INFORMATION::Type, _KEY_VALUE_FULL_INFORMATION::Type, _KEY_VALUE_PARTIAL_INFORMATION::Type, _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64::Type, _CM_KEY_VALUE::Type, _CELL_DATA::u, and VALUE_COMP_NAME.
Referenced by CmEnumerateValueKey(), and CmQueryValueKey().