Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/wmikmp.h File Reference
wmikmp.h File Reference
#include "ntos.h"
#include "zwapi.h"
#include "wmiguid.h"
#include "wmidata.h"
#include <stdio.h>
#include "wmistr.h"
#include "wmiumkm.h"
#include <wmi.h>
#include "wmiumds.h"
Data Structures
struct _REGENTRY
struct _REGISTRATIONWORKITEM
struct _tagWMI_Event
struct _WMIGUIDOBJECT
struct _WMILIB_INFO
struct CREATETHREADWORKITEM
struct EVENTWORKCONTEXT
struct GUIDREGINFO
struct INSTID
struct IRPCOMPCTX
struct MBREQUESTS
struct OBJECT_EVENT_INFO
struct REGQUERYBUFFERXFER
struct SMBIOS_EVENTLOG_INFO
struct SMBIOSVERSIONINFO
struct tagINSTIDCHUNK
struct WMIEVENTQUEUE
Macros
#define DEFAULTMAXKMWNODEEVENTSIZE 0x80000
#define INSTIDSPERCHUNK 8
#define IsEqualGUID(guid1, guid2) (!memcmp((guid1), (guid2), sizeof(GUID)))
#define LARGEKMWNODEEVENTSIZE 512
#define MAXREQREPLYSLOTS 4
#define OffsetToPtr(Base, Offset) ((PUCHAR)((PUCHAR)(Base) + (Offset)))
#define REGENTRY_FLAG_CALLBACK 0x00000002
#define REGENTRY_FLAG_INUSE 0x00000001
#define REGENTRY_FLAG_NEWREGINFO 0x00000004
#define REGENTRY_FLAG_NOT_ACCEPTING_IRPS 0x00000010
#define REGENTRY_FLAG_REG_IN_PROGRESS 0x00000100
#define REGENTRY_FLAG_RUNDOWN 0x00000080
#define REGENTRY_FLAG_TOO_SMALL 0x00000020
#define REGENTRY_FLAG_TRACE_NOTIFY_MASK 0x000F0000
#define REGENTRY_FLAG_TRACED 0x00000040
#define REGENTRY_FLAG_UM_PROVIDER 0x00000200
#define REGENTRY_FLAG_UPDREGINFO 0x00000008
#define WMI_GM_POOLTAG 'jimW'
#define WmiDeviceStackSize 2
#define WMIGUID_FLAG_KERNEL_NOTIFICATION 0x00000008
#define WMIGUID_FLAG_RECEIVE_NO_EVENTS 0x00000010
#define WMIGUID_FLAG_REPLY_OBJECT 0x00000002
#define WMIGUID_FLAG_REQUEST_OBJECT 0x00000001
#define WMIGUID_FLAG_SECURITY_OBJECT 0x00000004
#define WMIIIPOOLTAG 'iimW'
#define WmiInsertTimestamp(WnodeHeader) KeQuerySystemTime(&(WnodeHeader)->TimeStamp)
#define WMIMSGPOOLTAG 'mimW'
#define WMINCPOOLTAG 'nimW'
#define WMINPPOOLTAG 'NimW'
#define WMINWPOOLTAG 'wimW'
#define WmipAssert ASSERT
#define WmipBuildWnodeTooSmall(Wnode, BufferSizeNeeded)
#define WMIPCREATETHREADTAG 'CimW'
#define WmipDebugPrintEx(_x_)
#define WmipDeviceObjectToProviderId(DeviceObject) ((ULONG)(DeviceObject))
#define WmipDoFindRegEntryByProviderId(ProviderId, InvalidFlags) WmipDoFindRegEntryByDevice((PDEVICE_OBJECT)(ProviderId), InvalidFlags)
#define WmipEnterSMCritSection() WmipEnterCritSection(FALSE)
#define WmipEnterTLCritSection() WmipEnterTraceCritSection(FALSE);
#define WmipFindRegEntryByProviderId(ProviderId, ReferenceIrp) WmipFindRegEntryByDevice((PDEVICE_OBJECT)(ProviderId) , (ReferenceIrp))
#define WmipInstanceNameTag 'IimW'
#define WmipIsAligned(Value, Alignment) (((((ULONG_PTR)Value)+(Alignment-1)) & ~(Alignment-1)) == ((ULONG_PTR)Value))
#define WmipIsControlGuid(GuidEntry) WmipIsISFlagsSet(GuidEntry, (IS_TRACED | IS_CONTROL_GUID))
#define WmipIsTraceGuid(GuidEntry) WmipIsISFlagsSet(GuidEntry, IS_TRACED)
#define WmipIsWmiNotSetupProperly() (WmipServiceDeviceObject == NULL)
#define WmipLeaveSMCritSection() WmipLeaveCritSection()
#define WmipLeaveTLCritSection() WmipLeaveTraceCritSection();
#define WmipMCAPoolTag 'acMW'
#define WMIPOOLTAG 'pimW'
#define WmipReferenceRegEntry(RegEntry) InterlockedIncrement(&(RegEntry)->RefCount)
#define WmipRegisterDSPoolTag 'DimW'
#define WMIPSCHEDPOOLTAG 'gaiD'
#define WmipSetKmRegInfo(KmRegInfoPtr, RegEntryPtr)
#define WmipUnreferenceRegEntry WmipDoUnreferenceRegEntry
#define WmipValidateWnodeHeader(Wnode, BufSize, BufferSizeMin, RequiredFlags, ProhibitedFlags)
#define WMIREGPOOLTAG 'RimW'
#define WMISYSIDPOOLTAG 'simW'
Typedefs
typedef struct tagINSTIDCHUNK INSTIDCHUNK
typedef struct CREATETHREADWORKITEM * PCREATETHREADWORKITEM
typedef struct EVENTWORKCONTEXT * PEVENTWORKCONTEXT
typedef NTSTATUS(* PEXECUTE_WMI_METHOD) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG MethodId, IN ULONG InBufferSize, IN ULONG OutBufferSize, IN OUT PUCHAR Buffer)
typedef struct GUIDREGINFO * PGUIDREGINFO
typedef struct INSTID * PINSTID
typedef struct tagINSTIDCHUNK * PINSTIDCHUNK
typedef struct IRPCOMPCTX * PIRPCOMPCTX
typedef struct MBREQUESTS * PMBREQUESTS
typedef struct OBJECT_EVENT_INFO * POBJECT_EVENT_INFO
typedef NTSTATUS(* PQUERY_WMI_DATABLOCK) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG InstanceCount, IN OUT PULONG InstanceLengthArray, IN ULONG BufferAvail, OUT PUCHAR Buffer)
typedef NTSTATUS(* PQUERY_WMI_REGINFO) (IN PDEVICE_OBJECT DeviceObject, OUT PULONG RegFlags, OUT PUNICODE_STRING Name, OUT PUNICODE_STRING *RegistryPath)
typedef struct _REGENTRY * PREGENTRY
typedef struct _REGISTRATIONWORKITEM * PREGISTRATIONWORKITEM
typedef enum _REGOPERATION * PREGOPERATION
typedef struct REGQUERYBUFFERXFER * PREGQUERYBUFFERXFER
typedef NTSTATUS(* PSET_WMI_DATABLOCK) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG BufferSize, IN PUCHAR Buffer)
typedef NTSTATUS(* PSET_WMI_DATAITEM) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG DataItemId, IN ULONG BufferSize, IN PUCHAR Buffer)
typedef struct SMBIOS_EVENTLOG_INFO * PSMBIOS_EVENTLOG_INFO
typedef struct SMBIOSVERSIONINFO * PSMBIOSVERSIONINFO
typedef NTSTATUS(* PWMI_FUNCTION_CONTROL) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN WMIENABLEDISABLEFUNCTION Function, IN BOOLEAN Enable)
typedef struct _tagWMI_Event * PWMI_TRACE_EVENT
typedef struct WMIEVENTQUEUE * PWMIEVENTQUEUE
typedef struct _WMIGUIDOBJECT * PWMIGUIDOBJECT
typedef struct _WMILIB_INFO * PWMILIB_INFO
typedef struct _REGENTRY REGENTRY
typedef struct _REGISTRATIONWORKITEM REGISTRATIONWORKITEM
typedef enum _REGOPERATION REGOPERATION
typedef struct _tagWMI_Event WMI_TRACE_EVENT
typedef struct _WMIGUIDOBJECT WMIGUIDOBJECT
typedef struct _WMILIB_INFO WMILIB_INFO
Enumerations
enum _REGOPERATION { RegisterAllDrivers, RegisterSingleDriver, RegisterUpdateSingleDriver, RegisterDeleteSingleDriver }
enum WMIENABLEDISABLEFUNCTION { WmiEventGeneration, WmiDataBlockCollection }
Functions
NTKERNELAPI NTSTATUS IoCreateDriver (IN PUNICODE_STRING DriverName, OPTIONAL IN PDRIVER_INITIALIZE InitializationFunction)
NTSTATUS IoWMIAllocateInstanceIds (IN GUID *Guid, IN ULONG InstanceCount, OUT ULONG *FirstInstanceId)
NTSTATUS IoWMICompleteRequest (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN NTSTATUS Status, IN ULONG BufferUsed, IN CCHAR PriorityBoost)
NTSTATUS IoWMIFireEvent (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN ULONG GuidIndex, IN ULONG EventDataSize, IN PVOID EventData)
NTSTATUS IoWMIRegistrationControl (IN PDEVICE_OBJECT DeviceObject, IN ULONG Action)
NTSTATUS IoWMISystemControl (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS IoWMIWriteEvent (__inout PVOID WnodeEventItem)
NTSTATUS WmipAddDataSource (IN PREGENTRY RegEntry, IN PWMIREGINFOW WmiRegInfo, IN ULONG BufferSize, IN PWCHAR RegPath, IN PWCHAR ResourceName, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN IsUserMode)
PREGENTRY WmipAllocRegEntry (PDEVICE_OBJECT DeviceObject, ULONG Flags)
NTSTATUS WmipCheckGuidAccess (IN LPGUID Guid, IN ACCESS_MASK DesiredAccess, IN PSECURITY_DESCRIPTOR SecurityDescriptor)
void WmipClearIrpObjectList (PIRP Irp)
void WmipClearObjectFromThreadList (PWMIGUIDOBJECT Object)
NTSTATUS WmipCreateAdminSD (PSECURITY_DESCRIPTOR *Sd)
NTSTATUS WmipCreateUMLogger (IN OUT PWMICREATEUMLOGGER CreateInfo)
void WmipDecrementIrpCount (IN PREGENTRY RegEntry)
NTSTATUS WmipDeliverWnodeToDS (CHAR ActionCode, PBDATASOURCE DataSource, PWNODE_HEADER Wnode, ULONG BufferSize)
NTSTATUS WmipDeregisterDevice (PDEVICE_OBJECT DeviceObject)
NTSTATUS WmipDisableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, ULONG64 LoggerContext)
NTSTATUS WmipDisableTraceProviders (ULONG StopLoggerId)
NTSTATUS WmipDockUndockEventCallback (IN PVOID NoificationStructure, IN PVOID Context)
ULONG WmipDoDisableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext, ULONG InProgressFlag)
PREGENTRY WmipDoFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, ULONG InvalidFlags)
BOOLEAN WmipDoUnreferenceRegEntry (PREGENTRY RegEntry)
NTSTATUS WmipDriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
NTSTATUS WmipEnableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, BOOLEAN *RequestSent, ULONG64 LoggerContext)
NTSTATUS WmipEnableDisableTrace (ULONG Ioctl, PWMITRACEENABLEDISABLEINFO TraceEnableInfo)
_inline NTSTATUS WmipEnterCritSection (BOOLEAN AllowAPC)
_inline NTSTATUS WmipEnterTraceCritSection (BOOLEAN AllowAPC)
NTSTATUS WmipEnumerateGuids (ULONG Ioctl, PWMIGUIDLISTINFO GuidList, ULONG MaxBufferSize, ULONG *OutBufferSize)
NTSTATUS WmipEnumerateMofResources (PWMIMOFLIST MofList, ULONG BufferSize, ULONG *RetSize)
void WmipEventNotification (PVOID Context)
PREGENTRY WmipFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, BOOLEAN ReferenceIrp)
BOOLEAN WmipFindSMBiosTable (PPHYSICAL_ADDRESS SMBiosTablePhysicalAddress, PUCHAR *SMBiosTableVirtualAddress, PULONG SMBiosTableLength, PSMBIOSVERSIONINFO SMBiosVersionInfo)
NTSTATUS WmipForwardWmiIrp (PIRP Irp, UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer)
void WmipGenerateMCAEventlog (PUCHAR ErrorLog, ULONG ErrorLogSize, BOOLEAN IsFatal)
NTSTATUS WmipGetDevicePDO (PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT *PDO)
NTSTATUS WmipGetGuidSecurityDescriptor (IN PUNICODE_STRING GuidName, IN PSECURITY_DESCRIPTOR *SecurityDescriptor, IN PSECURITY_DESCRIPTOR UserDefaultSecurity)
NTSTATUS WmipGetRawMCAInfo (OUT PUCHAR Buffer, IN OUT PULONG BufferSize)
NTSTATUS WmipGetSMBiosEventlog (PUCHAR Buffer, PULONG BufferSize)
void WmipGetSMBiosFromLoaderBlock (PVOID LoaderBlockPtr)
NTSTATUS WmipGetSMBiosTableData (PUCHAR Buffer, PULONG BufferSize, OUT PSMBIOSVERSIONINFO SMBiosVersionInfo)
NTSTATUS WmipGetSysIds (PSYSID_UUID *SysIdUuid, ULONG *SysIdUuidCount, PSYSID_1394 *SysId1394, ULONG *SysId1394Count)
NTSTATUS WmipInitializeDataStructs (void)
void WmipInitializeNotifications (void)
void WmipInitializeRegistration (ULONG Phase)
NTSTATUS WmipInitializeSecurity (void)
BOOLEAN WmipIsISFlagsSet (PBGUIDENTRY GuidEntry, ULONG Flags)
BOOLEAN WmipIsValidRegEntry (PREGENTRY CheckRegEntry)
_inline void WmipLeaveCritSection ()
_inline void WmipLeaveTraceCritSection ()
NTSTATUS WmipMarkHandleAsClosed (HANDLE Handle)
NTSTATUS WmipMBReply (IN HANDLE RequestHandle, IN ULONG ReplyIndex, IN PUCHAR Message, IN ULONG MessageSize)
NTSTATUS WmipOpenBlock (IN ULONG Ioctl, IN KPROCESSOR_MODE AccessMode, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG DesiredAccess, OUT PHANDLE Handle)
NTSTATUS WmipOpenGuidObject (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN KPROCESSOR_MODE AccessMode, OUT PHANDLE Handle, OUT PWMIGUIDOBJECT *ObjectPtr)
NTSTATUS WmipPDOToDeviceInstanceName (IN PDEVICE_OBJECT PDO, OUT PUNICODE_STRING DeviceInstanceName)
NTSTATUS WmipProbeAndCaptureGuidObjectAttributes (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS WmipProbeWmiOpenGuidBlock (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, PULONG DesiredAccess, PWMIOPENGUIDBLOCK InBlock, ULONG InBufferLen, ULONG OutBufferLen)
NTSTATUS WmipProcessEvent (PWNODE_HEADER Wnode, BOOLEAN IsHiPriority, BOOLEAN FreeBuffer)
NTSTATUS WmipProcessWmiRegInfo (IN PREGENTRY RegEntry, IN PWMIREGINFO WmiRegInfo, IN ULONG BufferSize, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN Update, IN BOOLEAN IsUserMode)
NTSTATUS WmipQueryAllData (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN PWNODE_ALL_DATA Wnode, IN ULONG OutBufferLen, OUT PULONG RetSize)
NTSTATUS WmipQueryAllDataMultiple (IN ULONG ObjectCount, IN PWMIGUIDOBJECT *ObjectList, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQADMULTIPLE QadMultiple, OUT ULONG *ReturnSize)
NTSTATUS WmipQueryGuidInfo (IN OUT PWMIQUERYGUIDINFO QueryGuidInfo)
NTSTATUS WmipQuerySetExecuteSI (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN UCHAR MinorFunction, IN OUT PWNODE_HEADER Wnode, IN ULONG OutBufferSize, OUT PULONG RetSize)
NTSTATUS WmipQuerySingleMultiple (IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQSIMULTIPLE QsiMultiple, IN ULONG QueryCount, IN PWMIGUIDOBJECT *ObjectList, IN PUNICODE_STRING InstanceNames, OUT ULONG *ReturnSize)
NTSTATUS WmipReceiveNotifications (PWMIRECEIVENOTIFICATION ReceiveNotification, PULONG OutBufferSize, PIRP Irp)
NTSTATUS WmipRegisterDevice (PDEVICE_OBJECT DeviceObject, ULONG RegistrationFlag)
VOID WmipRegisterFirmwareProviders ()
NTSTATUS WmipRegisterMcaHandler (ULONG Phase)
NTSTATUS WmipRegisterUMGuids (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Cookie, IN PWMIREGINFO RegInfo, IN ULONG RegInfoSize, OUT HANDLE *RequestHandle, OUT ULONG64 *LoggerContext)
void WmipReleaseCollectionEnabled (PBGUIDENTRY GuidEntry)
NTSTATUS WmipRemoveDataSource (PREGENTRY RegEntry)
NTSTATUS WmipSendWmiIrp (UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer, PIO_STATUS_BLOCK Iosb)
NTSTATUS WmipTranslateFileHandle (IN OUT PWMIFHTOINSTANCENAME FhToInstanceName, IN OUT PULONG OutBufferLen, IN HANDLE FileHandle, IN PDEVICE_OBJECT DeviceObject, IN PWMIGUIDOBJECT GuidObject, OUT PUNICODE_STRING InstanceNameString)
void WmipTranslatePDOInstanceNames (IN OUT PIRP Irp, IN UCHAR MinorFunction, IN ULONG BufferSize, IN OUT PREGENTRY RegEntry)
NTSTATUS WmipUMProviderCallback (IN WMIACTIONCODE ActionCode, IN PVOID DataPath, IN ULONG BufferSize, IN OUT PVOID Buffer)
NTSTATUS WmipUnregisterGuids (PWMIUNREGGUIDS UnregGuids)
NTSTATUS WmipUpdateDataSource (PREGENTRY RegEntry, PWMIREGINFOW RegistrationInfo, ULONG RetSize)
void WmipUpdateDeviceStackSize (CCHAR NewStackSize)
NTSTATUS WmipUpdateRegistration (PDEVICE_OBJECT DeviceObject)
NTSTATUS WmipValidateWmiRegInfoString (PWMIREGINFO WmiRegInfo, ULONG BufferSize, ULONG Offset, PWCHAR *String)
NTSTATUS WmipWriteWnodeToObject (PWMIGUIDOBJECT Object, PWNODE_HEADER Wnode, BOOLEAN IsHighPriority)
NTSTATUS FASTCALL WmiTraceUserMessage (IN PMESSAGE_TRACE_USER pMessage, IN ULONG MessageSize)
Variables
GUID GUID_MOF_RESOURCE_ADDED_NOTIFICATION
GUID GUID_MOF_RESOURCE_REMOVED_NOTIFICATION
GUID GUID_REGISTRATION_CHANGE_NOTIFICATION
POBJECT_TYPE IoFileObjectType
ULONG WmipCpePollInterval
const GUID WmipDataProviderPnpidGuid
const GUID WmipDataProviderPnPIdInstanceNamesGuid
LONG WmipEventWorkItems
WORK_QUEUE_ITEM WmipEventWorkQueueItem
POBJECT_TYPE WmipGuidObjectType
LONG WmipInUseRegEntryCount
LIST_ENTRY WmipInUseRegEntryHead
ULONG WmipMaxKmWnodeEventSize
LIST_ENTRY WmipNPEvent
KSPIN_LOCK WmipNPNotificationSpinlock
ULONG WmipNSAllocCount
ULONG WmipNSAllocMax
KMUTEX WmipRegistrationMutex
KSPIN_LOCK WmipRegistrationSpinLock
UNICODE_STRING WmipRegistryPath
PDEVICE_OBJECT WmipServiceDeviceObject
ULONG WmipSMBiosTableLength
PHYSICAL_ADDRESS WmipSMBiosTablePhysicalAddress
PUCHAR WmipSMBiosTableVirtualAddress
KMUTEX WmipSMMutex
KMUTEX WmipTLMutex
const WMILIB_INFO WmipWmiLibInfo
Macro Definition Documentation
#define DEFAULTMAXKMWNODEEVENTSIZE 0x80000
Definition at line 126 of file wmikmp.h.
#define INSTIDSPERCHUNK 8
Definition at line 333 of file wmikmp.h.
Referenced by IoWMIAllocateInstanceIds().
#define IsEqualGUID (guid1, guid2) (!memcmp((guid1), (guid2), sizeof(GUID)))
Definition at line 45 of file wmikmp.h.
#define LARGEKMWNODEEVENTSIZE 512
Definition at line 127 of file wmikmp.h.
Referenced by IoWMIWriteEvent().
#define MAXREQREPLYSLOTS 4
Definition at line 467 of file wmikmp.h.
Referenced by WmipDeleteMethod(), WmipMBReply(), and WmipWriteMBToObject().
#define OffsetToPtr (Base, Offset) ((PUCHAR)((PUCHAR)(Base) + (Offset)))
Definition at line 122 of file wmikmp.h.
Referenced by IoWMIExecuteMethod(), IoWMIQuerySingleInstance(), IoWMISetSingleInstance(), IoWMISetSingleItem(), WmipBuildInstanceSet(), WmipDereferenceEvent(), WmipEnumerateMofResources(), WmipFireOffWmiEvent(), WmipGenerateBinaryMofNotification(), WmipGenerateMCAEventlog(), WmipGenerateMofResourceNotification(), WmipIoControl(), WmipPrepareWnodeSI(), WmipProbeWmiRegRequest(), WmipProbeWnodeWorker(), WmipProcessPrevMcaLogs(), WmipQueryAllDataMultiple(), WmipQuerySingleMultiple(), WmipSendGuidUpdateNotifications(), and WmipValidateWmiRegInfoString().
#define REGENTRY_FLAG_CALLBACK 0x00000002
Definition at line 273 of file wmikmp.h.
Referenced by WmipDeregisterDevice(), WmipForwardWmiIrp(), and WmipRegisterDevice().
#define REGENTRY_FLAG_INUSE 0x00000001
Definition at line 272 of file wmikmp.h.
Referenced by WmipInitializeDataStructs(), WmipRegisterDevice(), and WmipRegisterUMGuids().
#define REGENTRY_FLAG_NEWREGINFO 0x00000004
Definition at line 274 of file wmikmp.h.
#define REGENTRY_FLAG_NOT_ACCEPTING_IRPS 0x00000010
Definition at line 277 of file wmikmp.h.
Referenced by IoWMIRegistrationControl(), WmipDecrementIrpCount(), WmipDeleteMethod(), WmipDeregisterDevice(), WmipDoUnreferenceRegEntry(), WmipForwardWmiIrp(), WmipInitializeDataStructs(), WmipRegisterDevice(), WmipRegisterUMGuids(), and WmipWaitForIrpCompletion().
#define REGENTRY_FLAG_REG_IN_PROGRESS 0x00000100
Definition at line 284 of file wmikmp.h.
Referenced by WmipInitializeDataStructs(), WmipRegisterDevice(), WmipRegisterUMGuids(), and WmipRegistrationWorker().
#define REGENTRY_FLAG_RUNDOWN 0x00000080
Definition at line 281 of file wmikmp.h.
Referenced by IoWMIWriteEvent(), WmipDecrementIrpCount(), WmipDeleteMethod(), WmipDeregisterDevice(), WmipDoUnreferenceRegEntry(), WmipFindRegEntryByDevice(), WmipInitializeDataStructs(), WmipRegisterDevice(), WmipRegisterUMGuids(), and WmipWaitForIrpCompletion().
#define REGENTRY_FLAG_TOO_SMALL 0x00000020
Definition at line 278 of file wmikmp.h.
#define REGENTRY_FLAG_TRACE_NOTIFY_MASK 0x000F0000
Definition at line 289 of file wmikmp.h.
#define REGENTRY_FLAG_TRACED 0x00000040
Definition at line 279 of file wmikmp.h.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipInitializeDataStructs(), WmipRegisterDevice(), and WmipRegisterUMGuids().
#define REGENTRY_FLAG_UM_PROVIDER 0x00000200
Definition at line 287 of file wmikmp.h.
#define REGENTRY_FLAG_UPDREGINFO 0x00000008
Definition at line 275 of file wmikmp.h.
#define WMI_GM_POOLTAG 'jimW'
Definition at line 119 of file wmikmp.h.
#define WmiDeviceStackSize 2
Definition at line 236 of file wmikmp.h.
Referenced by WmipDriverEntry().
#define WMIGUID_FLAG_KERNEL_NOTIFICATION 0x00000008
Definition at line 576 of file wmikmp.h.
Referenced by IoWMISetNotificationCallback(), WmipDeleteMethod(), WmipOpenBlock(), and WmipProcessEvent().
#define WMIGUID_FLAG_RECEIVE_NO_EVENTS 0x00000010
Definition at line 580 of file wmikmp.h.
Referenced by WmipMarkHandleAsClosed(), and WmipProcessEvent().
#define WMIGUID_FLAG_REPLY_OBJECT 0x00000002
Definition at line 569 of file wmikmp.h.
Referenced by WmipCloseMethod(), WmipCreateUMLogger(), and WmipDeleteMethod().
#define WMIGUID_FLAG_REQUEST_OBJECT 0x00000001
Definition at line 566 of file wmikmp.h.
Referenced by WmipDeleteMethod(), WmipReceiveNotifications(), and WmipRegisterUMGuids().
#define WMIGUID_FLAG_SECURITY_OBJECT 0x00000004
Definition at line 572 of file wmikmp.h.
Referenced by WmipOpenBlock().
#define WMIIIPOOLTAG 'iimW'
Definition at line 112 of file wmikmp.h.
Referenced by IoWMIAllocateInstanceIds().
#define WmiInsertTimestamp (WnodeHeader) KeQuerySystemTime(&(WnodeHeader)->TimeStamp)
Definition at line 1002 of file wmikmp.h.
Referenced by WmipGenerateBinaryMofNotification(), WmipGenerateMCAEventlog(), and WmipGenerateMofResourceNotification().
#define WMIMSGPOOLTAG 'mimW'
Definition at line 111 of file wmikmp.h.
#define WMINCPOOLTAG 'nimW'
Definition at line 108 of file wmikmp.h.
#define WMINPPOOLTAG 'NimW'
Definition at line 109 of file wmikmp.h.
#define WMINWPOOLTAG 'wimW'
Definition at line 110 of file wmikmp.h.
Referenced by IoWMIWriteEvent().
#define WmipAssert ASSERT
Definition at line 105 of file wmikmp.h.
Referenced by IoWMICompleteRequest(), IoWMISetNotificationCallback(), IoWMISystemControl(), WMIInitialize(), WmipAddDataSource(), WmipAddMofResource(), WmipAllocEntry(), WmipBuildInstanceSet(), WmipClearIrpObjectList(), WmipClearThreadObjectList(), WmipCompleteGuidIrpWithError(), WmipConstructMCAErrorEvent(), WmipConstructMCAErrorEventAMD(), WmipConstructMCAErrorEventIntel(), WmipCopyFromEventQueues(), WmipCreateGuidObject(), WmipCsrClientMessageServer(), WmipDecrementIrpCount(), WmipDeleteMethod(), WmipDisableCollectionForRemovedGuid(), WmipDoUnreferenceRegEntry(), WmipDSCleanup(), WmipEnableCollectionForNewGuid(), WmipEnumerateMofResources(), WmipEventNotification(), WmipFindDSByProviderId(), WmipFindGEByGuid(), WmipFindISByGuid(), WmipFindISinGEbyName(), WmipFindMRByNames(), WmipForwardWmiIrp(), WmipFreeEntry(), WmipFreeLoggerContext(), WmipGECleanup(), WmipGenerateBinaryMofNotification(), WmipGenerateMCAEventlog(), WmipGetLogFromHal(), WmipInitializeDataStructs(), WmipInsertStaticNames(), WmipIoControl(), WmipISCleanup(), WmipIsQuerySetGuid(), WmipLinkDataSourceToList(), WmipMangleInstanceName(), WmipMceDelivery(), WmipOpenBlock(), WmipPDOToDeviceInstanceName(), WmipProbeWnodeAllData(), WmipProbeWnodeMethodItem(), WmipProbeWnodeSingleInstance(), WmipProbeWnodeSingleItem(), WmipPumpThreadApc(), WmipQueryAllDataMultiple(), WmipQuerySetExecuteSI(), WmipQuerySingleMultiple(), WmipQueryWmiDataBlock(), WmipRealloc(), WmipReceiveNotifications(), WmipRegistrationWorker(), WmipSendDisableRequest(), WmipSendEnableDisableRequest(), WmipStaticInstanceNameSize(), WmipTranslateFileHandle(), WmipTranslatePDOInstanceNames(), WmipUnreferenceEntry(), WmipWaitForCollectionEnabled(), WmipWaitForIrpCompletion(), WmipWriteWnodeToObject(), WmiReleaseKernelBuffer(), and WmiTraceProcess().
#define WmipBuildWnodeTooSmall (Wnode, BufferSizeNeeded)
Value:
((PWNODE_TOO_SMALL)Wnode)->WnodeHeader.BufferSize = sizeof(WNODE_TOO_SMALL);\
 ((PWNODE_TOO_SMALL)Wnode)->WnodeHeader.Flags = WNODE_FLAG_TOO_SMALL; \
 ((PWNODE_TOO_SMALL)Wnode)->SizeNeeded = BufferSizeNeeded;
Definition at line 349 of file wmikmp.h.
#define WMIPCREATETHREADTAG 'CimW'
Definition at line 120 of file wmikmp.h.
Referenced by WmipQueueNotification().
#define WmipDebugPrintEx (_x_)
Definition at line 78 of file wmikmp.h.
Referenced by IoWMIWriteEvent(), WmipAddDataSource(), WmipAllocEntry(), WmipAllocGuidEntryX(), WmipBuildInstanceSet(), WmipCachePtrs(), WmipCheckIsWbemRunning(), WmipClearObjectFromThreadList(), WmipCreatePumpThread(), WmipCreatePumpThreadRoutine(), WmipCsrClientMessageServer(), WmipDereferenceEvent(), WmipDeregisterDevice(), WmipDetermineInstanceBaseIndex(), WmipDoDisableRequest(), WmipDoUnreferenceRegEntry(), WmipForwardWmiIrp(), WmipIncludeStaticNames(), WmipInsertStaticNames(), WmipIoControl(), WmipIsWbemRunningWorker(), WmipLinkDataSourceToList(), WmipMangleInstanceName(), WmipMBReply(), WmipMceDelivery(), WmipMceDispatchRoutine(), WmipMceDpcRoutine(), WmipMceEventDelivery(), WmipMceWorkerRoutine(), WmipOpenGuidObject(), WmipProcessEvent(), WmipProcessWmiRegInfo(), WmipPumpThreadApc(), WmipQueryAllDataMultiple(), WmipQueryLogAndFireEvent(), WmipQuerySetExecuteSI(), WmipQuerySingleMultiple(), WmipQueueNotification(), WmipQueueRegWork(), WmipReceiveNotifications(), WmipRegisterDevice(), WmipRegisterMcaHandler(), WmipRegistrationWorker(), WmipReleaseCollectionEnabled(), WmipRemoveDataSource(), WmipSendDisableRequest(), WmipSendEnableDisableRequest(), WmipSendEnableRequest(), WmipSetupWaitForWbem(), WmipUpdateAddGuid(), WmipUpdateDataSource(), WmipUpdateModifyGuid(), WmipUpdateRemoveGuid(), WmipWaitForCollectionEnabled(), WmipWaitForIrpCompletion(), and WmipWriteWnodeToObject().
#define WmipDeviceObjectToProviderId (DeviceObject) ((ULONG)(DeviceObject))
Definition at line 1274 of file wmikmp.h.
#define WmipDoFindRegEntryByProviderId (ProviderId, InvalidFlags) WmipDoFindRegEntryByDevice((PDEVICE_OBJECT)(ProviderId), InvalidFlags)
Definition at line 1275 of file wmikmp.h.
Referenced by IoWMIWriteEvent().
#define WmipEnterSMCritSection () WmipEnterCritSection(FALSE)
Definition at line 182 of file wmikmp.h.
Referenced by IoWMIAllocateInstanceIds(), IoWMIRegistrationControl(), IoWMISetNotificationCallback(), WmipAddDataSource(), WmipAddMofResource(), WmipAllocEntry(), WmipCheckIsWbemRunning(), WmipCloseMethod(), WmipCreatePumpThread(), WmipDeleteMethod(), WmipDeliverWnodeToDS(), WmipDeregisterDevice(), WmipDetermineInstanceBaseIndex(), WmipDisableCollectionForRemovedGuid(), WmipDisableCollectOrEvent(), WmipDisableKernelTrace(), WmipDisableTraceProviders(), WmipDoUnreferenceRegEntry(), WmipDSCleanup(), WmipEnableCollectionForNewGuid(), WmipEnableCollectOrEvent(), WmipEnableDisableTrace(), WmipEnableKernelTrace(), WmipEnumerateGuids(), WmipEnumerateMofResources(), WmipFindDSByProviderId(), WmipFindGEByGuid(), WmipFindISByGuid(), WmipFindISinGEbyName(), WmipFindMRByNames(), WmipFindRegEntryByDevice(), WmipFreeEntry(), WmipIncludeStaticNames(), WmipIsISFlagsSet(), WmipIsQuerySetGuid(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipMceWorkerRoutine(), WmipNotificationIrpCancel(), WmipNtDllLoggerInfo(), WmipOpenBlock(), WmipPrepareForWnodeAD(), WmipPrepareWnodeSI(), WmipProcessEvent(), WmipQueryGuidInfo(), WmipQueueRegWork(), WmipReceiveNotifications(), WmipRegisterDevice(), WmipRegisterUMGuids(), WmipRegistrationWorker(), WmipSendEnableDisableRequest(), WmipTranslateFileHandle(), WmipUnreferenceEntry(), WmipUpdateDataSource(), WmipUpdateDeviceStackSize(), WmipWaitForCollectionEnabled(), WmipWriteMCAEventLogEvent(), and WmipWriteMessageToGuid().
#define WmipEnterTLCritSection () WmipEnterTraceCritSection(FALSE);
Definition at line 228 of file wmikmp.h.
Referenced by WmipEnableDisableTrace(), and WmipNtDllLoggerInfo().
#define WmipFindRegEntryByProviderId (ProviderId, ReferenceIrp) WmipFindRegEntryByDevice((PDEVICE_OBJECT)(ProviderId) , (ReferenceIrp))
Definition at line 1271 of file wmikmp.h.
Referenced by IoWMISystemControl(), and WmipForwardWmiIrp().
#define WmipInstanceNameTag 'IimW'
Definition at line 118 of file wmikmp.h.
Referenced by WmipTranslateFileHandle().
#define WmipIsAligned (Value, Alignment) (((((ULONG_PTR)Value)+(Alignment-1)) & ~(Alignment-1)) == ((ULONG_PTR)Value))
Definition at line 611 of file wmikmp.h.
Referenced by WmipProbeWnodeAllData(), WmipProbeWnodeMethodItem(), WmipProbeWnodeSingleInstance(), WmipProbeWnodeSingleItem(), and WmipProbeWnodeWorker().
#define WmipIsControlGuid (GuidEntry) WmipIsISFlagsSet(GuidEntry, (IS_TRACED | IS_CONTROL_GUID))
Definition at line 1130 of file wmikmp.h.
Referenced by WmipCreateUMLogger(), and WmipEnableDisableTrace().
#define WmipIsTraceGuid (GuidEntry) WmipIsISFlagsSet(GuidEntry, IS_TRACED)
Definition at line 1132 of file wmikmp.h.
#define WmipIsWmiNotSetupProperly () (WmipServiceDeviceObject == NULL)
Definition at line 418 of file wmikmp.h.
Referenced by IoWMIAllocateInstanceIds(), IoWMIRegistrationControl(), IoWMISuggestInstanceName(), and IoWMIWriteEvent().
#define WmipLeaveSMCritSection () WmipLeaveCritSection()
Definition at line 183 of file wmikmp.h.
Referenced by IoWMIAllocateInstanceIds(), IoWMIRegistrationControl(), IoWMISetNotificationCallback(), WmipAddDataSource(), WmipAddMofResource(), WmipAllocEntry(), WmipCheckIsWbemRunning(), WmipCloseMethod(), WmipCreatePumpThread(), WmipDeleteMethod(), WmipDeliverWnodeToDS(), WmipDeregisterDevice(), WmipDetermineInstanceBaseIndex(), WmipDisableCollectionForRemovedGuid(), WmipDisableCollectOrEvent(), WmipDisableKernelTrace(), WmipDisableTraceProviders(), WmipDoUnreferenceRegEntry(), WmipDSCleanup(), WmipEnableCollectionForNewGuid(), WmipEnableCollectOrEvent(), WmipEnableDisableTrace(), WmipEnableKernelTrace(), WmipEnumerateGuids(), WmipEnumerateMofResources(), WmipFindDSByProviderId(), WmipFindGEByGuid(), WmipFindISByGuid(), WmipFindISinGEbyName(), WmipFindMRByNames(), WmipFindRegEntryByDevice(), WmipFreeEntry(), WmipIncludeStaticNames(), WmipIsISFlagsSet(), WmipIsQuerySetGuid(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipMceWorkerRoutine(), WmipNotificationIrpCancel(), WmipNtDllLoggerInfo(), WmipOpenBlock(), WmipPrepareForWnodeAD(), WmipPrepareWnodeSI(), WmipProcessEvent(), WmipQueryGuidInfo(), WmipQueueRegWork(), WmipReceiveNotifications(), WmipRegisterDevice(), WmipRegisterUMGuids(), WmipRegistrationWorker(), WmipSendEnableDisableRequest(), WmipTranslateFileHandle(), WmipUnreferenceEntry(), WmipUpdateDataSource(), WmipUpdateDeviceStackSize(), WmipWaitForCollectionEnabled(), WmipWriteMCAEventLogEvent(), and WmipWriteMessageToGuid().
#define WmipLeaveTLCritSection () WmipLeaveTraceCritSection();
Definition at line 229 of file wmikmp.h.
Referenced by WmipEnableDisableTrace(), and WmipNtDllLoggerInfo().
#define WmipMCAPoolTag 'acMW'
Definition at line 117 of file wmikmp.h.
Referenced by WmipFireOffWmiEvent(), WmipGenerateMCAEventlog(), WmipGetLogFromHal(), and WmipProcessPrevMcaLogs().
#define WMIPOOLTAG 'pimW'
Definition at line 107 of file wmikmp.h.
Referenced by IoWMISuggestInstanceName(), WmipAllocGuidEntryX(), WmipCreateAdminSD(), WmipInitializeSecurity(), WmipSDRegistryQueryRoutine(), and WmipSecurityMethod().
#define WmipReferenceRegEntry (RegEntry) InterlockedIncrement(&(RegEntry)->RefCount)
Definition at line 1202 of file wmikmp.h.
Referenced by IoWMIWriteEvent(), WmipFindRegEntryByDevice(), WmipQueueRegWork(), and WmipRegisterDevice().
#define WmipRegisterDSPoolTag 'DimW'
Definition at line 115 of file wmikmp.h.
Referenced by WmipRegisterOrUpdateDS().
#define WMIPSCHEDPOOLTAG 'gaiD'
Definition at line 116 of file wmikmp.h.
#define WmipSetKmRegInfo (KmRegInfoPtr, RegEntryPtr)
Value:
{ \
    (KmRegInfoPtr)->ProviderId = (RegEntryPtr)->ProviderId; \
    (KmRegInfoPtr)->Flags = (RegEntryPtr)->Flags; \
}
Definition at line 291 of file wmikmp.h.
#define WmipUnreferenceRegEntry WmipDoUnreferenceRegEntry
Definition at line 1243 of file wmikmp.h.
Referenced by IoWMIRegistrationControl(), IoWMISystemControl(), WmipDeleteMethod(), WmipDeregisterDevice(), WmipEventNotification(), WmipForwardWmiIrp(), WmipInitializeDataStructs(), WmipQueryWmiDataBlock(), WmipRegisterDevice(), WmipRegisterUMGuids(), WmipRegistrationWorker(), and WmipUpdateRegistration().
#define WmipValidateWnodeHeader (Wnode, BufSize, BufferSizeMin, RequiredFlags, ProhibitedFlags)
Value:
(((BufSize < BufferSizeMin) || \
        ( (Wnode->Flags & RequiredFlags) != RequiredFlags) || \
        (BufSize != Wnode->BufferSize) || \
        ( (Wnode->Flags & ProhibitedFlags) != 0))  ? \
                                   STATUS_UNSUCCESSFUL : STATUS_SUCCESS)
Definition at line 598 of file wmikmp.h.
Referenced by WmipProbeWnodeAllData(), WmipProbeWnodeMethodItem(), WmipProbeWnodeSingleInstance(), and WmipProbeWnodeSingleItem().
#define WMIREGPOOLTAG 'RimW'
Definition at line 113 of file wmikmp.h.
Referenced by WmipInitializeRegistration().
#define WMISYSIDPOOLTAG 'simW'
Definition at line 114 of file wmikmp.h.
Typedef Documentation
typedef struct tagINSTIDCHUNK INSTIDCHUNK
typedef struct CREATETHREADWORKITEM * PCREATETHREADWORKITEM
typedef struct EVENTWORKCONTEXT * PEVENTWORKCONTEXT
typedef NTSTATUS(* PEXECUTE_WMI_METHOD) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG MethodId, IN ULONG InBufferSize, IN ULONG OutBufferSize, IN OUT PUCHAR Buffer)
Definition at line 811 of file wmikmp.h.
typedef struct GUIDREGINFO * PGUIDREGINFO
typedef struct INSTID * PINSTID
typedef struct tagINSTIDCHUNK * PINSTIDCHUNK
typedef struct IRPCOMPCTX * PIRPCOMPCTX
typedef struct MBREQUESTS * PMBREQUESTS
typedef struct OBJECT_EVENT_INFO * POBJECT_EVENT_INFO
typedef NTSTATUS(* PQUERY_WMI_DATABLOCK) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG InstanceCount, IN OUT PULONG InstanceLengthArray, IN ULONG BufferAvail, OUT PUCHAR Buffer)
Definition at line 666 of file wmikmp.h.
typedef NTSTATUS(* PQUERY_WMI_REGINFO) (IN PDEVICE_OBJECT DeviceObject, OUT PULONG RegFlags, OUT PUNICODE_STRING Name, OUT PUNICODE_STRING *RegistryPath)
Definition at line 625 of file wmikmp.h.
typedef struct _REGENTRY * PREGENTRY
typedef struct _REGISTRATIONWORKITEM * PREGISTRATIONWORKITEM
typedef enum _REGOPERATION * PREGOPERATION
typedef struct REGQUERYBUFFERXFER * PREGQUERYBUFFERXFER
typedef NTSTATUS(* PSET_WMI_DATABLOCK) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG BufferSize, IN PUCHAR Buffer)
Definition at line 724 of file wmikmp.h.
typedef NTSTATUS(* PSET_WMI_DATAITEM) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG DataItemId, IN ULONG BufferSize, IN PUCHAR Buffer)
Definition at line 766 of file wmikmp.h.
typedef struct SMBIOS_EVENTLOG_INFO * PSMBIOS_EVENTLOG_INFO
typedef struct SMBIOSVERSIONINFO * PSMBIOSVERSIONINFO
typedef NTSTATUS(* PWMI_FUNCTION_CONTROL) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN WMIENABLEDISABLEFUNCTION Function, IN BOOLEAN Enable)
Definition at line 868 of file wmikmp.h.
typedef struct _tagWMI_Event * PWMI_TRACE_EVENT
typedef struct WMIEVENTQUEUE * PWMIEVENTQUEUE
typedef struct _WMIGUIDOBJECT * PWMIGUIDOBJECT
typedef struct _WMILIB_INFO * PWMILIB_INFO
typedef struct _REGENTRY REGENTRY
typedef struct _REGISTRATIONWORKITEM REGISTRATIONWORKITEM
typedef enum _REGOPERATION REGOPERATION
typedef struct _tagWMI_Event WMI_TRACE_EVENT
typedef struct _WMIGUIDOBJECT WMIGUIDOBJECT
typedef struct _WMILIB_INFO WMILIB_INFO
Enumeration Type Documentation
enum _REGOPERATION
Enumerator
RegisterAllDrivers
RegisterSingleDriver
RegisterUpdateSingleDriver
RegisterDeleteSingleDriver
Definition at line 298 of file wmikmp.h.
enum WMIENABLEDISABLEFUNCTION
Enumerator
WmiEventGeneration
WmiDataBlockCollection
Definition at line 860 of file wmikmp.h.
Function Documentation
NTKERNELAPI NTSTATUS IoCreateDriver (IN PUNICODE_STRING DriverName, OPTIONAL IN PDRIVER_INITIALIZE InitializationFunction)
NTSTATUS IoWMIAllocateInstanceIds (IN GUID * Guid, IN ULONG InstanceCount, OUT ULONG * FirstInstanceId)
NTSTATUS IoWMICompleteRequest (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN NTSTATUS Status, IN ULONG BufferUsed, IN CCHAR PriorityBoost)
Definition at line 1292 of file dataprov.c.
References _WNODE_HEADER::BufferSize, tagWNODE_ALL_DATA::DataBlockOffset, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, tagWNODE_METHOD_ITEM::DataBlockOffset, _WNODE_HEADER::Flags, tagWNODE_ALL_DATA::InstanceCount, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_ALL_DATA, IRP_MN_QUERY_SINGLE_INSTANCE, KeQuerySystemTime(), OFFSETINSTANCEDATAANDLENGTH::LengthInstanceData, _IO_STACK_LOCATION::MinorFunction, NT_SUCCESS, OFFSETINSTANCEDATAANDLENGTH::OffsetInstanceData, tagWNODE_ALL_DATA::OffsetInstanceDataAndLength, PAGED_CODE, _IO_STACK_LOCATION::Parameters, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, tagWNODE_METHOD_ITEM::SizeDataBlock, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, _WNODE_HEADER::TimeStamp, UNREFERENCED_PARAMETER, WmipAssert, WNODE_FLAG_TOO_SMALL, tagWNODE_ALL_DATA::WnodeHeader, tagWNODE_SINGLE_INSTANCE::WnodeHeader, tagWNODE_METHOD_ITEM::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMISystemControl(), and WmipQueryWmiDataBlock().
NTSTATUS IoWMIFireEvent (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN ULONG GuidIndex, IN ULONG EventDataSize, IN PVOID EventData)
NTSTATUS IoWMIRegistrationControl (IN PDEVICE_OBJECT DeviceObject, IN ULONG Action)
NTSTATUS IoWMISystemControl (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 720 of file dataprov.c.
References _UNICODE_STRING::Buffer, WMIREGINFOW::BufferSize, tagWNODE_ALL_DATA::DataBlockOffset, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, tagWNODE_SINGLE_ITEM::DataBlockOffset, tagWNODE_METHOD_ITEM::DataBlockOffset, _REGENTRY::DeviceObject, ExFreePool(), FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, WMIREGGUIDW::Flags, GUIDREGINFO::Flags, WMIREGGUIDW::Guid, GUIDREGINFO::Guid, WMIREGINFOW::GuidCount, tagWNODE_ALL_DATA::InstanceCount, WMIREGGUIDW::InstanceCount, GUIDREGINFO::InstanceCount, WMIREGGUIDW::InstanceInfo, IO_NO_INCREMENT, IoCallDriver(), IoCompleteRequest(), IoGetCurrentIrpStackLocation, IoSkipCurrentIrpStackLocation, IoWMICompleteRequest(), IRP_MN_CHANGE_SINGLE_INSTANCE, IRP_MN_CHANGE_SINGLE_ITEM, IRP_MN_DISABLE_COLLECTION, IRP_MN_DISABLE_EVENTS, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_ALL_DATA, IRP_MN_QUERY_SINGLE_INSTANCE, IRP_MN_REGINFO, IRP_MN_REGINFO_EX, tagWNODE_SINGLE_ITEM::ItemId, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _REGENTRY::MaxInstanceNames, tagWNODE_METHOD_ITEM::MethodId, _IO_STACK_LOCATION::MinorFunction, WMIREGINFOW::MofResourceName, WMIREGINFOW::NextWmiRegInfo, NT_SUCCESS, NULL, tagWNODE_ALL_DATA::OffsetInstanceDataAndLength, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PnPIdGuidIndex, PnPIdInstanceNamesGuidIndex, _WNODE_HEADER::ProviderId, WMIREGINFOW::RegistryPath, RtlCopyMemory, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, tagWNODE_METHOD_ITEM::SizeDataBlock, tagWNODE_SINGLE_ITEM::SizeDataItem, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, STATUS_WMI_GUID_NOT_FOUND, STATUS_WMI_INSTANCE_NOT_FOUND, STATUS_WMI_READ_ONLY, TRUE, WmiDataBlockCollection, WmiEventGeneration, WmipAssert, WmipFindGuid(), WmipFindRegEntryByProviderId, WmipUnreferenceRegEntry, WMIREG_FLAG_INSTANCE_LIST, WMIREG_FLAG_INSTANCE_PDO, WMIREGINFOW::WmiRegGuid, WNODE_FLAG_FIXED_INSTANCE_SIZE, WNODE_FLAG_STATIC_INSTANCE_NAMES, tagWNODE_ALL_DATA::WnodeHeader, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipSystemControl().
NTSTATUS IoWMIWriteEvent (__inout PVOID WnodeEventItem)
Definition at line 582 of file api.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, DelayedWorkQueue, DPFLTR_WMICORE_ID, ExAllocatePoolWithTag, ExInterlockedInsertTailList(), ExQueueWorkItem(), _WNODE_HEADER::Flags, _WNODE_HEADER::HistoricalContext, InterlockedIncrement, KeAcquireSpinLock, KeReleaseSpinLock(), KernelMode, LARGEKMWNODEEVENTSIZE, EVENTWORKCONTEXT::ListEntry, MAXLOGGERS, NonPagedPool, NULL, _WNODE_HEADER::ProviderId, EVENTWORKCONTEXT::RegEntry, REGENTRY_FLAG_RUNDOWN, Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRACE_HEADER_EVENT_TRACE, TRACE_HEADER_FLAG, TRACE_HEADER_TYPE_FULL_HEADER, _WNODE_HEADER::Version, WmiGetLoggerId, WMINWPOOLTAG, WmipDebugPrintEx, WmipDoFindRegEntryByProviderId, WmipEventWorkItems, WmipEventWorkQueueItem, WmipIsWmiNotSetupProperly, WmipLoggerContext, WmipMaxKmWnodeEventSize, WmipNPEvent, WmipNPNotificationSpinlock, WmipReferenceRegEntry, WmipRegistrationSpinLock, WmiTraceEvent(), WmiTraceFastEvent(), EVENTWORKCONTEXT::Wnode, WNODE_FLAG_LOG_WNODE, and WNODE_FLAG_TRACED_GUID.
NTSTATUS WmipAddDataSource (IN PREGENTRY RegEntry, IN PWMIREGINFOW WmiRegInfo, IN ULONG BufferSize, IN PWCHAR RegPath, IN PWCHAR ResourceName, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN IsUserMode)
Definition at line 1574 of file ds.c.
References tagInstanceSet::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, DS_KERNEL_MODE, DS_USER_MODE, tagInstanceSet::DSISList, FALSE, tagInstanceSet::Flags, WMIREGGUIDW::Flags, tagDATASOURCE::Flags, WMIREGGUIDW::Guid, GUID_MOF_RESOURCE_ADDED_NOTIFICATION, tagInstanceSet::GuidEntry, InsertHeadList(), IS_NEWLY_REGISTERED, IsEqualGUID, tagDATASOURCE::ISHead, MOFEVENT_ACTION_IMAGE_PATH, MOFEVENT_ACTION_REGISTRY_PATH, NT_SUCCESS, NULL, PAGED_CODE, tagInstanceSet::ProviderId, tagDATASOURCE::ProviderId, RegistrationAdd, tagDATASOURCE::RegistryPath, tagDATASOURCE::RequestObject, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, WmipAddMofResource(), WmipAllocDataSource(), WmipAllocInstanceSet, WmipAssert, WmipBuildInstanceSet(), WmipCountedToSz(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFree, WmipGenerateBinaryMofNotification(), WmipGenerateMofResourceNotification(), WmipGenerateRegistrationNotification(), WmipLeaveSMCritSection, WmipLinkDataSourceToList(), WmipUnreferenceDS, WMIREG_FLAG_REMOVE_GUID, WMIREG_FLAG_TRACE_CONTROL_GUID, and WMIREG_FLAG_TRACED_GUID.
Referenced by WmipInitializeDataStructs(), and WmipProcessWmiRegInfo().
PREGENTRY WmipAllocRegEntry (PDEVICE_OBJECT DeviceObject, ULONG Flags)
Definition at line 179 of file register.c.
References _REGENTRY::DataSource, _REGENTRY::DeviceObject, _REGENTRY::Event, ExAllocateFromNPagedLookasideList(), ExInterlockedInsertTailList(), FALSE, _REGENTRY::Flags, InterlockedIncrement, _REGENTRY::InUseEntryList, _REGENTRY::IrpCount, KeInitializeEvent(), NULL, PAGED_CODE, _REGENTRY::PDO, _REGENTRY::ProviderId, _REGENTRY::RefCount, SynchronizationEvent, WmipAllocProviderId, WmipInUseRegEntryCount, WmipRegistrationSpinLock, and WmipRegLookaside.
Referenced by WmipInitializeDataStructs(), WmipRegisterDevice(), and WmipRegisterUMGuids().
NTSTATUS WmipCheckGuidAccess (IN LPGUID Guid, IN ACCESS_MASK DesiredAccess, IN PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 1589 of file secure.c.
References ExFreePool(), FALSE, NT_SUCCESS, NULL, PAGED_CODE, RtlInitUnicodeString(), SeAccessCheck(), SeCaptureSubjectContext(), SeReleaseSubjectContext(), Status, StringCbPrintf, UserMode, WmipDefaultAccessSd, and WmipGetGuidSecurityDescriptor().
Referenced by WmiFlushTrace(), WmipEnableDisableTrace(), WmipNtDllLoggerInfo(), WmipQueryLogger(), WmipStartLogger(), WmiStopTrace(), and WmiUpdateTrace().
void WmipClearIrpObjectList (PIRP Irp)
Definition at line 2335 of file consumer.c.
References CONTAINING_RECORD, _WMIGUIDOBJECT::EventQueueAction, _LIST_ENTRY::Flink, _WMIGUIDOBJECT::Irp, IRP_OBJECT_LIST_HEAD, NULL, PAGED_CODE, RECEIVE_ACTION_NONE, RemoveEntryList(), and WmipAssert.
Referenced by WmipCompleteGuidIrpWithError(), WmipDeleteMethod(), WmipNotificationIrpCancel(), and WmipWriteWnodeToObject().
void WmipClearObjectFromThreadList (PWMIGUIDOBJECT Object)
Definition at line 2370 of file consumer.c.
References DPFLTR_WMICORE_ID, _WMIGUIDOBJECT::EventQueueAction, InitializeListHead(), IsListEmpty, NULL, PAGED_CODE, RECEIVE_ACTION_NONE, RemoveEntryList(), _WMIGUIDOBJECT::ThreadObjectList, _WMIGUIDOBJECT::UserModeCallback, _WMIGUIDOBJECT::UserModeProcess, WmipDebugPrintEx, and ZwClose().
Referenced by WmipClearThreadObjectList(), WmipDeleteMethod(), and WmipReceiveNotifications().
NTSTATUS WmipCreateAdminSD (PSECURITY_DESCRIPTOR * Sd)
Definition at line 1667 of file secure.c.
References ACL_REVISION2, ExAllocatePoolWithTag, ExFreePool(), FALSE, FILE_ALL_ACCESS, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION1, SeLengthSid, SeLocalSystemSid, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, and WMIPOOLTAG.
Referenced by WmipDriverEntry().
NTSTATUS WmipCreateUMLogger (IN OUT PWMICREATEUMLOGGER CreateInfo)
Definition at line 4714 of file consumer.c.
References _WNODE_HEADER::BufferSize, FALSE, _WMIGUIDOBJECT::Flags, InitializeListHead(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _WMIGUIDOBJECT::RequestListHead, Status, STATUS_WMI_INSTANCE_NOT_FOUND, UserMode, WMIGUID_FLAG_REPLY_OBJECT, WmiGuidObjectNameLength, WmipFindGEByGuid(), WmipIsControlGuid, WmipOpenGuidObject(), WmipProbeAndCaptureGuidObjectAttributes(), WmipUnreferenceGE, WmipWriteMessageToGuid(), and ZwClose().
Referenced by WmipIoControl().
void WmipDecrementIrpCount (IN PREGENTRY RegEntry)
Definition at line 811 of file register.c.
References FALSE, InterlockedDecrement, KeSetEvent(), REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, and WmipAssert.
Referenced by WmipForwardWmiIrp(), and WmipWmiIrpCompletion().
NTSTATUS WmipDeliverWnodeToDS (CHAR ActionCode, PBDATASOURCE DataSource, PWNODE_HEADER Wnode, ULONG BufferSize)
Definition at line 155 of file enabdisa.c.
References ASSERT, _WMIGUIDOBJECT::Cookie, _WNODE_HEADER::CountLost, DS_KERNEL_MODE, DS_USER_MODE, FALSE, _WNODE_HEADER::Flags, tagDATASOURCE::Flags, _WNODE_HEADER::Guid, NULL, PAGED_CODE, _WNODE_HEADER::ProviderId, tagDATASOURCE::ProviderId, tagDATASOURCE::RequestObject, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, WmipEnterSMCritSection, WmipLeaveSMCritSection, WmipSendWmiIrp(), WmipWriteWnodeToObject(), and WNODE_FLAG_INTERNAL.
Referenced by WmipDereferenceEvent(), WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), and WmipSendEnableDisableRequest().
NTSTATUS WmipDeregisterDevice (PDEVICE_OBJECT DeviceObject)
Definition at line 546 of file register.c.
References DPFLTR_WMICORE_ID, FALSE, _REGENTRY::Flags, InterlockedExchange(), NULL, ObDereferenceObject(), PAGED_CODE, REGENTRY_FLAG_CALLBACK, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, WmipDebugPrintEx, WmipEnterSMCritSection, WmipFindRegEntryByDevice(), WmipLeaveSMCritSection, WmipUnreferenceRegEntry, and WmipWaitForIrpCompletion().
Referenced by IoWMIRegistrationControl().
NTSTATUS WmipDisableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, ULONG64 LoggerContext)
Definition at line 1009 of file enabdisa.c.
References ASSERT, FALSE, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, PAGED_CODE, Status, STATUS_ILLEGAL_FUNCTION, TRUE, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipSendDisableRequest().
Referenced by WmipDeleteMethod(), and WmipEnableDisableTrace().
NTSTATUS WmipDisableTraceProviders (ULONG StopLoggerId)
Definition at line 1330 of file enabdisa.c.
References CONTAINING_RECORD, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_NOTIFICATION_TRACE_FLAG, tagGUIDENTRY::LoggerContext, PAGED_CODE, Status, STATUS_SUCCESS, TRUE, WmiGetLoggerId, WmipEnterSMCritSection, WmipGEHeadPtr, WmipLeaveSMCritSection, WmipReferenceGE, WmipSendDisableRequest(), and WmipUnreferenceGE.
Referenced by WmipProcessEvent(), and WmiStopTrace().
NTSTATUS WmipDockUndockEventCallback (IN PVOID NoificationStructure, IN PVOID Context)
Referenced by WmipDriverEntry().
ULONG WmipDoDisableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext, ULONG InProgressFlag)
Definition at line 711 of file enabdisa.c.
References tagGUIDENTRY::CollectRefCount, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagGUIDENTRY::EventRefCount, tagGUIDENTRY::Flags, IRP_MN_DISABLE_COLLECTION, IRP_MN_DISABLE_EVENTS, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), Status, WmipDebugPrintEx, WmipReleaseCollectionEnabled(), and WmipSendEnableDisableRequest().
Referenced by WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), and WmipSendDisableRequest().
PREGENTRY WmipDoFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, ULONG InvalidFlags)
Definition at line 735 of file register.c.
References CONTAINING_RECORD, _REGENTRY::DeviceObject, _REGENTRY::Flags, _LIST_ENTRY::Flink, and NULL.
Referenced by WmipFindRegEntryByDevice().
BOOLEAN WmipDoUnreferenceRegEntry (PREGENTRY RegEntry)
Definition at line 239 of file register.c.
References _LIST_ENTRY::Blink, DPFLTR_WMICORE_ID, ExFreeToNPagedLookasideList(), ExInterlockedRemoveHeadList(), FALSE, _REGENTRY::Flags, InterlockedDecrement, _REGENTRY::InUseEntryList, NULL, ObDereferenceObject(), PAGED_CODE, _REGENTRY::PDO, _REGENTRY::ProviderId, _REGENTRY::RefCount, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, TRUE, WmipAssert, WmipDebugPrintEx, WmipEnterSMCritSection, WmipInUseRegEntryCount, WmipLeaveSMCritSection, WmipRegistrationSpinLock, WmipRegLookaside, and WmipRemoveDS().
NTSTATUS WmipDriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Definition at line 193 of file wmi.c.
References DACL_SECURITY_INFORMATION, DO_DEVICE_INITIALIZING, EventCategoryHardwareProfileChange, ExFreePool(), FALSE, _FAST_IO_DISPATCH::FastIoDeviceControl, FILE_DEVICE_SECURE_OPEN, FILE_DEVICE_UNKNOWN, IoCreateDevice(), IoCreateSymbolicLink(), IoDeleteDevice(), IoDeleteSymbolicLink(), IoRegisterPlugPlayNotification(), IoRegisterShutdownNotification(), IoWMIRegistrationControl(), IRP_MJ_CLEANUP, IRP_MJ_CLOSE, IRP_MJ_CREATE, IRP_MJ_DEVICE_CONTROL, IRP_MJ_SHUTDOWN, IRP_MJ_SYSTEM_CONTROL, KeInitializeMutex(), MAXLOGGERS, NT_SUCCESS, NULL, ObSetSecurityObjectByPointer(), OWNER_SECURITY_INFORMATION, PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), RtlZeroMemory, SharedUserData, _FAST_IO_DISPATCH::SizeOfFastIoDispatch, Status, TRUE, UNREFERENCED_PARAMETER, WMIAdminDeviceObjectName, WMIAdminSymbolicLinkName, WmiDeviceStackSize, WmipAdminDeviceObject, WmipCreateAdminSD(), WmipDockUndockEventCallback(), WmipFastIoDeviceControl(), WmipFastIoDispatch, WmipInitializeDataStructs(), WmipInitializeNotifications(), WmipInitializeRegistration(), WmipInitializeSecurity(), WmipIoControl(), WmipLoggerContext, WmipOpenCloseCleanup(), WmipRefCount, WmipServiceDeviceObject, WmipShutdown(), WmipStartGlobalLogger(), WmipSystemControl(), WMIREG_ACTION_REGISTER, WMIServiceDeviceObjectName, and WMIServiceSymbolicLinkName.
NTSTATUS WmipEnableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, BOOLEAN * RequestSent, ULONG64 LoggerContext)
Definition at line 905 of file enabdisa.c.
References ASSERT, CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, IS_EVENT_ONLY, IS_EXPENSIVE, IS_TRACED, tagGUIDENTRY::ISHead, NT_SUCCESS, PAGED_CODE, Status, STATUS_ILLEGAL_FUNCTION, STATUS_SUCCESS, TRUE, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipSendEnableRequest().
Referenced by WmipEnableDisableTrace(), and WmipOpenBlock().
NTSTATUS WmipEnableDisableTrace (ULONG Ioctl, PWMITRACEENABLEDISABLEINFO TraceEnableInfo)
_inline NTSTATUS WmipEnterCritSection (BOOLEAN AllowAPC)
Definition at line 152 of file wmikmp.h.
References Executive, KernelMode, KeWaitForMutexObject, NULL, STATUS_ALERTED, and STATUS_USER_APC.
_inline NTSTATUS WmipEnterTraceCritSection (BOOLEAN AllowAPC)
Definition at line 199 of file wmikmp.h.
References Executive, KernelMode, KeWaitForMutexObject, NULL, STATUS_ALERTED, and STATUS_USER_APC.
NTSTATUS WmipEnumerateGuids (ULONG Ioctl, PWMIGUIDLISTINFO GuidList, ULONG MaxBufferSize, ULONG * OutBufferSize)
Definition at line 2175 of file consumer.c.
References CONTAINING_RECORD, FIELD_OFFSET, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, WMIGUIDPROPERTIES::Guid, WMIGUIDLISTINFO::GuidList, IOCTL_WMI_ENUMERATE_GUIDS_AND_PROPERTIES, PAGED_CODE, WMIGUIDLISTINFO::ReturnedGuidCount, STATUS_SUCCESS, WMIGUIDLISTINFO::TotalGuidCount, WmipEnterSMCritSection, WmipGEHeadPtr, WmipGetGuidPropertiesFromGuidEntry(), and WmipLeaveSMCritSection.
Referenced by WmipIoControl().
NTSTATUS WmipEnumerateMofResources (PWMIMOFLIST MofList, ULONG BufferSize, ULONG * RetSize)
Definition at line 2512 of file ds.c.
References CONTAINING_RECORD, MOFRESOURCE::Flags, WMIMOFENTRY::Flags, _LIST_ENTRY::Flink, WMIMOFLIST::MofEntry, WMIMOFLIST::MofListCount, MOFRESOURCE::MofResourceName, MR_FLAG_USER_MODE, OffsetToPtr, PAGED_CODE, MOFRESOURCE::RegistryPath, WMIMOFENTRY::RegPathOffset, WMIMOFENTRY::ResourceOffset, S_OK, STATUS_SUCCESS, StringCbCopy, wcslen(), WMIMOFENTRY_FLAG_USERMODE, WmipAssert, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipMRHeadPtr.
Referenced by WmipIoControl().
void WmipEventNotification (PVOID Context)
PREGENTRY WmipFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, BOOLEAN ReferenceIrp)
Definition at line 766 of file register.c.
References InterlockedIncrement, _REGENTRY::IrpCount, NULL, PAGED_CODE, REGENTRY_FLAG_RUNDOWN, WmipDoFindRegEntryByDevice(), WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceRegEntry.
Referenced by IoWMIRegistrationControl(), WmipDeregisterDevice(), WmipQueryWmiDataBlock(), WmipRegisterDevice(), and WmipUpdateRegistration().
BOOLEAN WmipFindSMBiosTable (PPHYSICAL_ADDRESS SMBiosTablePhysicalAddress, PUCHAR * SMBiosTableVirtualAddress, PULONG SMBiosTableLength, PSMBIOSVERSIONINFO SMBiosVersionInfo)
NTSTATUS WmipForwardWmiIrp (PIRP Irp, UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer)
Definition at line 1688 of file wmi.c.
References _REGENTRY::DeviceObject, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, IRPCOMPCTX::Event, Executive, FALSE, FIELD_OFFSET, _REGENTRY::Flags, _WNODE_HEADER::Guid, IoCallDriver(), IoGetAttachedDeviceReference(), IoGetCurrentIrpStackLocation, IoGetNextIrpStackLocation, IoMarkIrpPending, IoSetCompletionRoutine, IRP_MJ_SYSTEM_CONTROL, IRP_MN_CHANGE_SINGLE_INSTANCE, IRP_MN_QUERY_ALL_DATA, IRP_MN_QUERY_SINGLE_INSTANCE, IRP_MN_REGINFO, IRP_MN_REGINFO_EX, IsEqualGUID, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _IO_STACK_LOCATION::Parameters, _REGENTRY::PDO, IRPCOMPCTX::RegEntry, REGENTRY_FLAG_CALLBACK, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, Status, STATUS_NOT_SUPPORTED, STATUS_PENDING, STATUS_UNSUCCESSFUL, STATUS_WMI_GUID_NOT_FOUND, STATUS_WMI_INSTANCE_NOT_FOUND, STATUS_WMI_TRY_AGAIN, SynchronizationEvent, TRUE, _REGENTRY::WmiEntry, WmipAssert, WmipDataProviderPnpidGuid, WmipDataProviderPnPIdInstanceNamesGuid, WmipDebugPrintEx, WmipDecrementIrpCount(), WmipFindRegEntryByProviderId, WmipServiceDeviceObject, WmipTranslatePDOInstanceNames(), WmipUnreferenceRegEntry, WmipUpdateDeviceStackSize(), and WmipWmiIrpCompletion().
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipQueryAllData(), WmipQuerySetExecuteSI(), WmipSendWmiIrp(), and WmipSetTraceNotify().
void WmipGenerateMCAEventlog (PUCHAR ErrorLog, ULONG ErrorLogSize, BOOLEAN IsFatal)
Definition at line 1579 of file mca.c.
References _MSMCAEvent_Header::AdditionalErrors, _WNODE_HEADER::BufferSize, _MSMCAEvent_Header::Cpu, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, ExAllocatePoolWithTag, ExFreePool(), FIELD_OFFSET, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, IoRaiseInformationalHardError(), _WNODE_HEADER::Linkage, _MSMCAEvent_Header::LogToEventlog, MAX_ERROR_EVENT_SIZE, MCA_ERROR_UNKNOWN, MCA_ERROR_UNKNOWN_NO_CPU, MCA_EVENT_INSTANCE_NAME, MCA_INFO_NO_MORE_CORRECTED_ERROR_LOGS, MCA_UNDEFINED_CPU, MCA_WARNING_UNKNOWN, MCA_WARNING_UNKNOWN_NO_CPU, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, PagedPool, _MSMCAEvent_InvalidError::RawRecord, RtlCopyMemory, _MSMCAEvent_InvalidError::Size, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_MCA_OCCURED, STATUS_SUCCESS, _MSMCAEvent_InvalidError::Type, wcscpy, WmiInsertTimestamp, WmipAssert, WmipConstructMCAErrorEvent(), WmipCorrectedEventlogCounter, WmipDisableMCAPopups, WmipIsWbemRunning, WmipMCAPoolTag, WmipMSMCAEvent_InvalidErrorGuid, WmipWriteMCAEventLogEvent(), WmipWriteToEventlog(), WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipProcessPrevMcaLogs(), and WmipQueryLogAndFireEvent().
NTSTATUS WmipGetDevicePDO (PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT * PDO)
Definition at line 1580 of file wmi.c.
References ASSERT, _DEVICE_RELATIONS::Count, Executive, ExFreePool(), FALSE, _IO_STATUS_BLOCK::Information, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_PNP, IRP_MN_QUERY_DEVICE_RELATIONS, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NT_SUCCESS, NULL, _DEVICE_RELATIONS::Objects, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_SUPPORTED, STATUS_PENDING, and TargetDeviceRelation.
Referenced by WmipObjectToPDO().
NTSTATUS WmipGetGuidSecurityDescriptor (IN PUNICODE_STRING GuidName, IN PSECURITY_DESCRIPTOR * SecurityDescriptor, IN PSECURITY_DESCRIPTOR UserDefaultSecurity)
Definition at line 746 of file secure.c.
References DefaultSecurityGuidName, _RTL_QUERY_REGISTRY_TABLE::DefaultType, _RTL_QUERY_REGISTRY_TABLE::EntryContext, ExFreePool(), _RTL_QUERY_REGISTRY_TABLE::Flags, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, PAGED_CODE, _RTL_QUERY_REGISTRY_TABLE::QueryRoutine, REG_BINARY, RTL_REGISTRY_CONTROL, RtlQueryRegistryValues(), RtlZeroMemory, Status, STATUS_SUCCESS, WmipDefaultAccessSd, and WmipSDRegistryQueryRoutine().
Referenced by WmipCheckGuidAccess(), WmipCreateGuidObject(), and WmipStartGlobalLogger().
NTSTATUS WmipGetRawMCAInfo (OUT PUCHAR Buffer, IN OUT PULONG BufferSize)
Definition at line 1361 of file mca.c.
References NULL, PAGED_CODE, RtlCopyMemory, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and WmipRawMCASize.
Referenced by WmipQueryWmiDataBlock().
NTSTATUS WmipGetSMBiosEventlog (PUCHAR Buffer, PULONG BufferSize)
Referenced by WmipQueryWmiDataBlock().
void WmipGetSMBiosFromLoaderBlock (PVOID LoaderBlockPtr)
NTSTATUS WmipGetSMBiosTableData (PUCHAR Buffer, PULONG BufferSize, OUT PSMBIOSVERSIONINFO SMBiosVersionInfo)
Referenced by WmipQueryWmiDataBlock(), and WmipRawSMBiosTableHandler().
NTSTATUS WmipGetSysIds (PSYSID_UUID * SysIdUuid, ULONG * SysIdUuidCount, PSYSID_1394 * SysId1394, ULONG * SysId1394Count)
Referenced by WmipQueryWmiDataBlock().
NTSTATUS WmipInitializeDataStructs (void)
Definition at line 2608 of file ds.c.
References _CHUNKINFO::ChunkHead, CONTAINING_RECORD, _REGENTRY::DataSource, ENUMERATE_GUIDS_GUID, FALSE, _REGENTRY::Flags, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_FLAG_INTERNAL, InitializeListHead(), INSTANCE_INFO_GUID, NT_SUCCESS, NULL, PAGED_CODE, REGENTRY_FLAG_INUSE, REGENTRY_FLAG_NEWREGINFO, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_REG_IN_PROGRESS, REGENTRY_FLAG_RUNDOWN, REGENTRY_FLAG_TRACED, RtlZeroMemory, Status, STATUS_SUCCESS, TRUE, WMICOREIMAGEPATH, WMICORERESOURCENAME, WmipAddDataSource(), WmipAddMofResource(), WmipAllocRegEntry(), WmipAssert, WmipDSChunkInfo, WmipDSHead, WmipDSHeadPtr, WmipGEChunkInfo, WmipGEHead, WmipGEHeadPtr, WmipISChunkInfo, WmipMRChunkInfo, WmipMRHead, WmipMRHeadPtr, WmipUMProviderCallback(), WmipUnreferenceRegEntry, and WMIREG_FLAG_CALLBACK.
Referenced by WmipDriverEntry().
void WmipInitializeNotifications (void)
Definition at line 43 of file notify.c.
References ExInitializeWorkItem, KeInitializeSpinLock(), NULL, PAGED_CODE, WmipEventNotification(), and WmipNPNotificationSpinlock.
Referenced by WmipDriverEntry().
void WmipInitializeRegistration (ULONG Phase)
Definition at line 121 of file register.c.
References DelayedWorkQueue, ExInitializeNPagedLookasideList(), ExInitializeWorkItem, ExQueueWorkItem(), InterlockedDecrement, KeInitializeSpinLock(), NULL, PAGED_CODE, WmipRegistrationSpinLock, WmipRegistrationWorker(), WmipRegLookaside, WmipRegWorkItemCount, and WMIREGPOOLTAG.
Referenced by WMIInitialize(), and WmipDriverEntry().
NTSTATUS WmipInitializeSecurity (void)
Definition at line 426 of file secure.c.
References ACCESS_SYSTEM_SECURITY, ACL_REVISION2, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlInitUnicodeString(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlZeroMemory, SeAliasAdminsSid, SeAliasUsersSid, SeCaptureSubjectContext(), SECURITY_DESCRIPTOR_REVISION1, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, _OBJECT_TYPE_INITIALIZER::SecurityRequired, SeExports, SeLengthSid, _SE_EXPORTS::SeLocalServiceSid, SeLocalSystemSid, _SE_EXPORTS::SeNetworkServiceSid, SPECIFIC_RIGHTS_ALL, STANDARD_RIGHTS_ALL, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, WmipCloseMethod(), WmipDefaultAccessSd, WmipDefaultAccessSecurityDescriptor, WmipDeleteMethod(), WmipGenericMapping, WMIPOOLTAG, and WmipSecurityMethod().
Referenced by WmipDriverEntry().
BOOLEAN WmipIsISFlagsSet (PBGUIDENTRY GuidEntry, ULONG Flags)
Definition at line 107 of file enabdisa.c.
References CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, tagGUIDENTRY::ISHead, NULL, PAGED_CODE, TRUE, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
BOOLEAN WmipIsValidRegEntry (PREGENTRY CheckRegEntry)
_inline void WmipLeaveCritSection ()
Definition at line 172 of file wmikmp.h.
References FALSE, and KeReleaseMutex().
_inline void WmipLeaveTraceCritSection ()
Definition at line 218 of file wmikmp.h.
References FALSE, and KeReleaseMutex().
NTSTATUS WmipMarkHandleAsClosed (HANDLE Handle)
Definition at line 2674 of file consumer.c.
References _WMIGUIDOBJECT::Flags, _WMIGUIDOBJECT::Irp, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, Status, UserMode, WMIGUID_FLAG_RECEIVE_NO_EVENTS, WmipCompleteGuidIrpWithError(), WmipEnterSMCritSection, WmipGuidObjectType, and WmipLeaveSMCritSection.
Referenced by WmipIoControl().
NTSTATUS WmipMBReply (IN HANDLE RequestHandle, IN ULONG ReplyIndex, IN PUCHAR Message, IN ULONG MessageSize)
Definition at line 4839 of file consumer.c.
References DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, MAXREQREPLYSLOTS, _WMIGUIDOBJECT::MBRequests, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, RemoveEntryList(), MBREQUESTS::ReplyObject, MBREQUESTS::RequestListEntry, Status, STATUS_INVALID_PARAMETER, UserMode, WmipDebugPrintEx, WmipEnterSMCritSection, WmipGuidObjectType, WmipLeaveSMCritSection, and WmipWriteMBToObject().
Referenced by WmipIoControl().
NTSTATUS WmipOpenBlock (IN ULONG Ioctl, IN KPROCESSOR_MODE AccessMode, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG DesiredAccess, OUT PHANDLE Handle)
Definition at line 252 of file consumer.c.
References _WMIGUIDOBJECT::EnableRequestSent, FALSE, _WMIGUIDOBJECT::Flags, _WMIGUIDOBJECT::GEObjectList, tagGUIDENTRY::Guid, _WMIGUIDOBJECT::Guid, _WMIGUIDOBJECT::GuidEntry, InsertHeadList(), InsertTailList(), Ioctl, IOCTL_WMI_OPEN_GUID, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, tagGUIDENTRY::ISCount, KernelMode, tagGUIDENTRY::MainGEList, memcpy(), NT_SUCCESS, NULL, ObDereferenceObject(), tagGUIDENTRY::ObjectHead, PAGED_CODE, Status, STATUS_ILLEGAL_FUNCTION, STATUS_INSUFFICIENT_RESOURCES, STATUS_WMI_GUID_NOT_FOUND, _WMIGUIDOBJECT::Type, WMIGUID_FLAG_KERNEL_NOTIFICATION, WMIGUID_FLAG_SECURITY_OBJECT, WmipAllocGuidEntry, WmipAssert, WmipEnableCollectOrEvent(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipGEHeadPtr, WmipIsQuerySetGuid(), WmipLeaveSMCritSection, WmipOpenGuidObject(), and ZwClose().
Referenced by IoWMIOpenBlock(), and WmipIoControl().
NTSTATUS WmipOpenGuidObject (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN KPROCESSOR_MODE AccessMode, OUT PHANDLE Handle, OUT PWMIGUIDOBJECT * ObjectPtr)
Definition at line 842 of file secure.c.
References _UNICODE_STRING::Buffer, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, KeAttachProcess(), KeDetachProcess(), NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), PAGED_CODE, _EPROCESS::Pcb, PsInitialSystemProcess, RtlEqualMemory, Status, STATUS_INVALID_PARAMETER, WmiGuidGuidPosition, WmiGuidObjectDirectory, WmiGuidObjectDirectoryLength, WmipCreateGuidObject(), WmipDebugPrintEx, WmipUuidFromString(), and ZwClose().
Referenced by WmipCreateUMLogger(), WmipOpenBlock(), and WmipRegisterUMGuids().
NTSTATUS WmipPDOToDeviceInstanceName (IN PDEVICE_OBJECT PDO, OUT PUNICODE_STRING DeviceInstanceName)
Definition at line 852 of file register.c.
References IoGetDeviceInstanceName(), NULL, PAGED_CODE, Status, and WmipAssert.
Referenced by WmipQueryWmiDataBlock(), WmipTranslateFileHandle(), and WmipTranslatePDOInstanceNames().
NTSTATUS WmipProbeAndCaptureGuidObjectAttributes (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 2865 of file wmi.c.
References _OBJECT_ATTRIBUTES32::Attributes, _OBJECT_ATTRIBUTES::Attributes, _UNICODE_STRING::Buffer, _STRING32::Buffer, except, EXCEPTION_EXECUTE_HANDLER, _UNICODE_STRING::Length, _STRING32::Length, _OBJECT_ATTRIBUTES::Length, _UNICODE_STRING::MaximumLength, _STRING32::MaximumLength, NULL, _OBJECT_ATTRIBUTES32::ObjectName, _OBJECT_ATTRIBUTES::ObjectName, PAGED_CODE, ProbeAndReadStructure, ProbeAndReadUnicodeString, ProbeForRead, _OBJECT_ATTRIBUTES32::RootDirectory, _OBJECT_ATTRIBUTES::RootDirectory, RtlCopyMemory, _OBJECT_ATTRIBUTES32::SecurityDescriptor, _OBJECT_ATTRIBUTES::SecurityDescriptor, _OBJECT_ATTRIBUTES32::SecurityQualityOfService, _OBJECT_ATTRIBUTES::SecurityQualityOfService, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, UlongToPtr, UNICODE_NULL, and WmiGuidObjectNameLength.
Referenced by WmipCreateUMLogger(), WmipProbeWmiOpenGuidBlock(), and WmipRegisterUMGuids().
NTSTATUS WmipProbeWmiOpenGuidBlock (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, PULONG DesiredAccess, PWMIOPENGUIDBLOCK InBlock, ULONG InBufferLen, ULONG OutBufferLen)
Definition at line 2980 of file wmi.c.
References _OBJECT_ATTRIBUTES::Attributes, WMIOPENGUIDBLOCK::DesiredAccess, WMIOPENGUIDBLOCK32::DesiredAccess, NT_SUCCESS, NULL, WMIOPENGUIDBLOCK::ObjectAttributes, WMIOPENGUIDBLOCK32::ObjectAttributes, PAGED_CODE, _OBJECT_ATTRIBUTES::RootDirectory, _OBJECT_ATTRIBUTES::SecurityDescriptor, _OBJECT_ATTRIBUTES::SecurityQualityOfService, Status, STATUS_INVALID_PARAMETER, STATUS_UNSUCCESSFUL, ULongToPtr, and WmipProbeAndCaptureGuidObjectAttributes().
Referenced by WmipIoControl().
NTSTATUS WmipProcessEvent (PWNODE_HEADER Wnode, BOOLEAN IsHiPriority, BOOLEAN FreeBuffer)
Definition at line 4093 of file consumer.c.
References _WNODE_HEADER::BufferSize, _WMIGUIDOBJECT::Callback, _WMIGUIDOBJECT::CallbackContext, CONTAINING_RECORD, DPFLTR_WMICORE_ID, ExFreePool(), _WNODE_HEADER::Flags, _WMIGUIDOBJECT::Flags, _LIST_ENTRY::Flink, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, IsEqualGUID, NT_SUCCESS, NULL, ObDereferenceObject(), tagGUIDENTRY::ObjectHead, ObReferenceObjectSafe(), PAGED_CODE, Status, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WMI_GUID_NOT_FOUND, _tagWMI_Event::TraceErrorFlag, TRUE, WmiGetLoggerId, WMIGUID_FLAG_KERNEL_NOTIFICATION, WMIGUID_FLAG_RECEIVE_NO_EVENTS, WmipDebugPrintEx, WmipDereferenceEvent(), WmipDisableTraceProviders(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipFree, WmipIncludeStaticNames(), WmipLeaveSMCritSection, WmipUnreferenceGE, WmipWriteWnodeToObject(), WNODE_FLAG_EVENT_REFERENCE, and WNODE_FLAG_STATIC_INSTANCE_NAMES.
Referenced by WmipEventNotification(), WmipFlushBuffer(), WmipGenerateBinaryMofNotification(), WmipGenerateMofResourceNotification(), WmipSendGuidUpdateNotifications(), and WmipSendNotification().
NTSTATUS WmipProcessWmiRegInfo (IN PREGENTRY RegEntry, IN PWMIREGINFO WmiRegInfo, IN ULONG BufferSize, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN Update, IN BOOLEAN IsUserMode)
Definition at line 1227 of file register.c.
References DPFLTR_WMICORE_ID, NT_SUCCESS, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, WmipAddDataSource(), WmipDebugPrintEx, WmipUpdateDataSource(), and WmipValidateWmiRegInfoString().
Referenced by WmipRegisterOrUpdateDS(), and WmipRegisterUMGuids().
NTSTATUS WmipQueryAllData (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN PWNODE_ALL_DATA Wnode, IN ULONG OutBufferLen, OUT PULONG RetSize)
Definition at line 858 of file consumer.c.
References _WNODE_HEADER::BufferSize, tagInstanceSet::Count, FALSE, _WNODE_HEADER::Flags, tagInstanceSet::Flags, _WNODE_HEADER::Guid, IRP_MN_QUERY_ALL_DATA, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, _WNODE_HEADER::Linkage, MANYPROVIDERIDS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PAGED_CODE, _WNODE_HEADER::ProviderId, tagInstanceSet::ProviderId, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_SUCCESS, STATUS_WMI_GUID_NOT_FOUND, TRUE, WmipForwardWmiIrp(), WmipFree, WmipGuidObjectType, WmipInsertStaticNames(), WmipPrepareForWnodeAD(), WmipSendWmiIrp(), WmipStaticInstanceNameSize(), WmipUnreferenceIS, WNODE_FLAG_INTERNAL, WNODE_FLAG_STATIC_INSTANCE_NAMES, WNODE_FLAG_TOO_SMALL, tagWNODE_ALL_DATA::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMIQueryAllData(), WmipIoControl(), and WmipQueryAllDataMultiple().
NTSTATUS WmipQueryAllDataMultiple (IN ULONG ObjectCount, IN PWMIGUIDOBJECT * ObjectList, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQADMULTIPLE QadMultiple, OUT ULONG * ReturnSize)
Definition at line 1163 of file consumer.c.
References _WNODE_HEADER::BufferSize, Count, DPFLTR_WMICORE_ID, FALSE, _WNODE_HEADER::Flags, _WNODE_HEADER::KernelHandle, _WNODE_HEADER::Linkage, NT_SUCCESS, NULL, OffsetToPtr, PAGED_CODE, RtlZeroMemory, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, WmipAlloc, WmipAssert, WmipDebugPrintEx, WmipFree, WmipQueryAllData(), WNODE_FLAG_ALL_DATA, WNODE_FLAG_INTERNAL, WNODE_FLAG_TOO_SMALL, tagWNODE_ALL_DATA::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMIQueryAllDataMultiple(), and WmipIoControl().
NTSTATUS WmipQueryGuidInfo (IN OUT PWMIQUERYGUIDINFO QueryGuidInfo)
Definition at line 2257 of file consumer.c.
References CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, _WMIGUIDOBJECT::GuidEntry, Handle, IS_EXPENSIVE, tagGUIDENTRY::ISHead, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, Status, STATUS_WMI_GUID_DISCONNECTED, TRUE, UserMode, WmipEnterSMCritSection, WmipGuidObjectType, and WmipLeaveSMCritSection.
Referenced by WmipIoControl().
NTSTATUS WmipQuerySetExecuteSI (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN UCHAR MinorFunction, IN OUT PWNODE_HEADER Wnode, IN ULONG OutBufferSize, OUT PULONG RetSize)
Definition at line 1607 of file consumer.c.
References DesiredAccessForFunction, DPFLTR_WMICORE_ID, _IO_STATUS_BLOCK::Information, IRP_MN_CHANGE_SINGLE_ITEM, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_ALL_DATA, MANYPROVIDERIDS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PAGED_CODE, tagInstanceSet::ProviderId, Status, STATUS_WMI_GUID_NOT_FOUND, STATUS_WMI_INSTANCE_NOT_FOUND, STATUS_WMI_ITEMID_NOT_FOUND, STATUS_WMI_READ_ONLY, STATUS_WMI_SET_FAILURE, WmipAssert, WmipDebugPrintEx, WmipForwardWmiIrp(), WmipFree, WmipGuidObjectType, WmipPrepareWnodeSI(), WmipSendWmiIrp(), WmipUnreferenceIS, and WNODE_FLAG_INTERNAL.
Referenced by IoWMIExecuteMethod(), IoWMIQuerySingleInstance(), IoWMISetSingleInstance(), IoWMISetSingleItem(), WmipIoControl(), and WmipQuerySingleMultiple().
NTSTATUS WmipQuerySingleMultiple (IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQSIMULTIPLE QsiMultiple, IN ULONG QueryCount, IN PWMIGUIDOBJECT * ObjectList, IN PUNICODE_STRING InstanceNames, OUT ULONG * ReturnSize)
Definition at line 1808 of file consumer.c.
References UNICODE_STRING3264::Buffer, _UNICODE_STRING::Buffer, _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, DPFLTR_WMICORE_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, HANDLE3264::Handle, WMIQSIINFO::Handle, WMIQSIINFO::InstanceName, IRP_MN_QUERY_SINGLE_INSTANCE, _WNODE_HEADER::KernelHandle, KernelMode, UNICODE_STRING3264::Length, _UNICODE_STRING::Length, _WNODE_HEADER::Linkage, UNICODE_STRING3264::MaximumLength, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, ProbeForRead, RtlCopyMemory, RtlZeroMemory, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, UserMode, WmipAlloc, WmipAllocNP, WmipAssert, WmipDebugPrintEx, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_INTERNAL, WNODE_FLAG_SINGLE_INSTANCE, WNODE_FLAG_TOO_SMALL, tagWNODE_SINGLE_INSTANCE::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMIQuerySingleInstanceMultiple(), and WmipIoControl().
NTSTATUS WmipReceiveNotifications (PWMIRECEIVENOTIFICATION ReceiveNotification, PULONG OutBufferSize, PIRP Irp)
Definition at line 2713 of file consumer.c.
References _PsGetCurrentProcess, WMIRECEIVENOTIFICATION::Action, _WNODE_HEADER::BufferSize, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, _WMIGUIDOBJECT::EventQueueAction, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _WNODE_HEADER::Flags, _WMIGUIDOBJECT::Flags, OBJECT_EVENT_INFO::GuidObject, Handle, HANDLE3264::Handle, HANDLE3264::Handle64, WMIRECEIVENOTIFICATION::HandleCount, WMIRECEIVENOTIFICATION::Handles, _WMIGUIDOBJECT::HiPriority, InitializeListHead(), InsertTailList(), IoMarkIrpPending, IoSetCancelRoutine, _WMIGUIDOBJECT::Irp, IRP_OBJECT_LIST_HEAD, _WMIGUIDOBJECT::IrpObjectList, KernelMode, _WNODE_HEADER::Linkage, _WMIGUIDOBJECT::LoPriority, MANY_NOTIFICATION_OBJECTS, WMIEVENTQUEUE::NextOffset, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, ObOpenObjectByPointer(), ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGED_CODE, PROCESS_CREATE_THREAD, PROCESS_QUERY_INFORMATION, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, RECEIVE_ACTION_CREATE_THREAD, RECEIVE_ACTION_NONE, RtlImageNtHeader(), RtlZeroMemory, tagWNODE_TOO_SMALL::SizeNeeded, _IMAGE_OPTIONAL_HEADER::SizeOfStackCommit, _IMAGE_OPTIONAL_HEADER::SizeOfStackReserve, _WMIGUIDOBJECT::StackCommit, _WMIGUIDOBJECT::StackSize, Status, STATUS_ACCESS_DENIED, STATUS_CANCELLED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PENDING, THREAD_ALL_ACCESS, _WMIGUIDOBJECT::ThreadObjectList, TRUE, UserMode, WMIRECEIVENOTIFICATION::UserModeCallback, _WMIGUIDOBJECT::UserModeCallback, WMIRECEIVENOTIFICATION::UserModeProcess, _WMIGUIDOBJECT::UserModeProcess, WMIGUID_FLAG_REQUEST_OBJECT, WmipAlloc, WmipAssert, WmipClearObjectFromThreadList(), WmipCompleteGuidIrpWithError(), WmipCopyFromEventQueues(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFree, WmipGuidObjectType, WmipHaveHiPriorityEvent, WmipHaveLoPriorityEvent, WmipLeaveSMCritSection, WmipNotificationIrpCancel(), WNODE_FLAG_TOO_SMALL, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by WmipIoControl().
NTSTATUS WmipRegisterDevice (PDEVICE_OBJECT DeviceObject, ULONG RegistrationFlag)
Definition at line 345 of file register.c.
References _REGENTRY::DeviceObject, DPFLTR_WMICORE_ID, FALSE, _REGENTRY::Flags, KernelMode, NT_SUCCESS, NULL, ObReferenceObjectByPointer(), PAGED_CODE, REGENTRY_FLAG_CALLBACK, REGENTRY_FLAG_INUSE, REGENTRY_FLAG_NEWREGINFO, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_REG_IN_PROGRESS, REGENTRY_FLAG_RUNDOWN, REGENTRY_FLAG_TRACED, RegisterSingleDriver, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_EXISTS, STATUS_SUCCESS, TRUE, WmipAllocRegEntry(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFindRegEntryByDevice(), WmipLeaveSMCritSection, WmipQueueRegWork(), WmipReferenceRegEntry, WmipRegisterDS(), WmipUnreferenceRegEntry, WmipUpdateDeviceStackSize(), WMIREG_FLAG_CALLBACK, WMIREG_FLAG_TRACE_NOTIFY_MASK, and WMIREG_FLAG_TRACE_PROVIDER.
Referenced by IoWMIRegistrationControl().
VOID WmipRegisterFirmwareProviders ()
Definition at line 39 of file provider.c.
References _SYSTEM_FIRMWARE_TABLE_HANDLER::DriverObject, _SYSTEM_FIRMWARE_TABLE_HANDLER::FirmwareTableHandler, IoPnpDriverObject, NtSetSystemInformation(), _SYSTEM_FIRMWARE_TABLE_HANDLER::ProviderSignature, _SYSTEM_FIRMWARE_TABLE_HANDLER::Register, SystemRegisterFirmwareTableInformationHandler, TRUE, WmipFirmwareTableHandler(), and WmipRawSMBiosTableHandler().
Referenced by WMIInitialize().
NTSTATUS WmipRegisterMcaHandler (ULONG Phase)
Definition at line 1096 of file mca.c.
References _HAL_ERROR_INFO::CmcMaxSize, _HAL_ERROR_INFO::CmcPollingInterval, _HAL_ERROR_INFO::CpeMaxSize, _HAL_ERROR_INFO::CpePollingInterval, MCEQUERYINFO::DeliveryDpc, MCEQUERYINFO::DpcLock, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, ExInitializeWorkItem, HAL_CMC_DISABLED, HAL_CMC_INTERRUPTS_BASED, HAL_CPE_DISABLED, HAL_CPE_INTERRUPTS_BASED, HAL_ERROR_INFO_VERSION, HalErrorInformation, HalKernelErrorHandler, HalQuerySystemInformation, HalSetSystemInformation, KeInitializeDpc(), KeInitializeSpinLock(), KeInitializeTimerEx(), KERNEL_ERROR_HANDLER_VERSION, KERNEL_ERROR_HANDLER_INFO::KernelCmcDelivery, KERNEL_ERROR_HANDLER_INFO::KernelCpeDelivery, KERNEL_ERROR_HANDLER_INFO::KernelMcaDelivery, KERNEL_ERROR_HANDLER_INFO::KernelMceDelivery, KeSetTimerEx(), MCEQUERYINFO::MaxSize, _HAL_ERROR_INFO::McaMaxSize, _HAL_ERROR_INFO::McaPreviousEventsCount, MCE_STATE_ERROR, MCE_STATE_REGISTERED, MCE_STATE_RUNNING, NotificationTimer, NT_SUCCESS, NULL, PAGED_CODE, MCEQUERYINFO::PollFrequency, MCEQUERYINFO::PollingDpc, MCEQUERYINFO::PollingTimer, _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, MCEQUERYINFO::Token, KERNEL_ERROR_HANDLER_INFO::Version, _HAL_ERROR_INFO::Version, WmipCorrectedEventlogCounter, WmipDebugPrintEx, WmipInsertQueueMCEDpc(), WmipMceDelivery(), WmipMceDpcRoutine(), WmipMceEventDelivery(), WmipMCEState, WmipMceWorkerRoutine(), WmipPollingDpcRoutine(), WmipProcessPrevMcaLogs(), and MCEQUERYINFO::WorkItem.
Referenced by WMIInitialize().
NTSTATUS WmipRegisterUMGuids (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Cookie, IN PWMIREGINFO RegInfo, IN ULONG RegInfoSize, OUT HANDLE * RequestHandle, OUT ULONG64 * LoggerContext)
Definition at line 4292 of file consumer.c.
References _WMIGUIDOBJECT::Cookie, _REGENTRY::DataSource, FALSE, _REGENTRY::Flags, tagGUIDENTRY::Flags, _WMIGUIDOBJECT::Flags, GE_NOTIFICATION_TRACE_FLAG, WMIREGGUIDW::Guid, tagGUIDENTRY::LoggerContext, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _WMIGUIDOBJECT::RegEntry, REGENTRY_FLAG_INUSE, REGENTRY_FLAG_NEWREGINFO, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_REG_IN_PROGRESS, REGENTRY_FLAG_RUNDOWN, REGENTRY_FLAG_TRACED, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_WMI_GUID_NOT_FOUND, TRUE, UserMode, WMIGUID_FLAG_REQUEST_OBJECT, WmiGuidObjectNameLength, WmipAllocRegEntry(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipFindISByGuid(), WmipLeaveSMCritSection, WmipOpenGuidObject(), WmipProbeAndCaptureGuidObjectAttributes(), WmipProcessWmiRegInfo(), WmipUMProviderCallback(), WmipUnreferenceGE, WmipUnreferenceIS, WmipUnreferenceRegEntry, WMIREG_FLAG_CALLBACK, and ZwClose().
Referenced by WmipIoControl().
void WmipReleaseCollectionEnabled (PBGUIDENTRY GuidEntry)
Definition at line 433 of file enabdisa.c.
References tagGUIDENTRY::CollectInProgress, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, tagGUIDENTRY::Flags, GE_FLAG_WAIT_ENABLED, KeSetEvent(), PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), and WmipDebugPrintEx.
Referenced by WmipDisableCollectionForRemovedGuid(), WmipDoDisableRequest(), WmipEnableCollectionForNewGuid(), and WmipSendEnableRequest().
NTSTATUS WmipRemoveDataSource (PREGENTRY RegEntry)
Definition at line 2487 of file ds.c.
References _REGENTRY::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, NULL, PAGED_CODE, Status, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, WmipDebugPrintEx, WmipReferenceDS, WmipRemoveDataSourceByDS(), and WmipUnreferenceDS.
Referenced by WmipRemoveDS().
NTSTATUS WmipSendWmiIrp (UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer, PIO_STATUS_BLOCK Iosb)
Definition at line 1937 of file wmi.c.
References _IO_STACK_LOCATION::DeviceObject, FALSE, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoSetNextIrpStackLocation, NULL, PAGED_CODE, PIRP, PsGetCurrentThread(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_WMI_TRY_AGAIN, WmipForwardWmiIrp(), and WmipServiceDeviceObject.
Referenced by WmipDeliverWnodeToDS(), WmipQueryAllData(), WmipQuerySetExecuteSI(), and WmipRegisterOrUpdateDS().
NTSTATUS WmipTranslateFileHandle (IN OUT PWMIFHTOINSTANCENAME FhToInstanceName, IN OUT PULONG OutBufferLen, IN HANDLE FileHandle, IN PDEVICE_OBJECT DeviceObject, IN PWMIGUIDOBJECT GuidObject, OUT PUNICODE_STRING InstanceNameString)
Definition at line 2003 of file wmi.c.
References _wcsnicmp(), ISBASENAME::BaseIndex, ISBASENAME::BaseName, _UNICODE_STRING::Buffer, CONTAINING_RECORD, ExAllocatePoolWithTag, FIELD_OFFSET, FILE_ALL_ACCESS, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IoFileObjectType, IS_INSTANCE_BASENAME, tagInstanceSet::IsBaseName, tagGUIDENTRY::ISCount, tagGUIDENTRY::ISHead, KernelMode, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PAGED_CODE, PagedPool, RtlCopyMemory, RtlFreeUnicodeString(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WMI_INSTANCE_NOT_FOUND, StringCbPrintf, UNICODE_NULL, UserMode, wcslen(), WmipAssert, WmipEnterSMCritSection, WmipGuidObjectType, WmipInstanceNameTag, WmipLeaveSMCritSection, WmipObjectToPDO(), and WmipPDOToDeviceInstanceName().
Referenced by IoWMIDeviceObjectToInstanceName(), IoWMIHandleToInstanceName(), and WmipIoControl().
void WmipTranslatePDOInstanceNames (IN OUT PIRP Irp, IN UCHAR MinorFunction, IN ULONG BufferSize, IN OUT PREGENTRY RegEntry)
Definition at line 885 of file register.c.
References WMIREGGUIDW::BaseNameOffset, _UNICODE_STRING::Buffer, WMIREGINFOW::BufferSize, FALSE, WMIREGGUIDW::Flags, WMIREGGUIDW::Guid, WMIREGINFOW::GuidCount, WMIREGGUIDW::InstanceCount, IoGetCurrentIrpStackLocation, IRP_MN_REGINFO_EX, IsEqualGUID, _UNICODE_STRING::Length, WMIREGINFOW::NextWmiRegInfo, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, WMIREGGUIDW::Pdo, RtlCopyMemory, RtlFreeUnicodeString(), RtlZeroMemory, Status, TRUE, WmipAssert, WmipDataProviderPnpidGuid, WmipDataProviderPnPIdInstanceNamesGuid, WmipPDOToDeviceInstanceName(), WMIREG_FLAG_INSTANCE_BASENAME, WMIREG_FLAG_INSTANCE_LIST, WMIREG_FLAG_INSTANCE_PDO, and WMIREGINFOW::WmiRegGuid.
Referenced by WmipForwardWmiIrp().
NTSTATUS WmipUMProviderCallback (IN WMIACTIONCODE ActionCode, IN PVOID DataPath, IN ULONG BufferSize, IN OUT PVOID Buffer)
Definition at line 4274 of file consumer.c.
References ASSERT, FALSE, PAGED_CODE, STATUS_UNSUCCESSFUL, and UNREFERENCED_PARAMETER.
Referenced by WmipInitializeDataStructs(), and WmipRegisterUMGuids().
NTSTATUS WmipUnregisterGuids (PWMIUNREGGUIDS UnregGuids)
Definition at line 4465 of file consumer.c.
References FALSE, tagGUIDENTRY::Flags, GE_NOTIFICATION_TRACE_FLAG, tagGUIDENTRY::LoggerContext, NULL, PAGED_CODE, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, WmipFindGEByGuid(), and WmipUnreferenceGE.
Referenced by WmipIoControl().
NTSTATUS WmipUpdateDataSource (PREGENTRY RegEntry, PWMIREGINFOW RegistrationInfo, ULONG RetSize)
Definition at line 2277 of file ds.c.
References Action, _REGENTRY::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagInstanceSet::DSISList, tagInstanceSet::Flags, WMIREGGUIDW::Flags, _LIST_ENTRY::Flink, WMIREGGUIDW::Guid, GUID_MOF_RESOURCE_ADDED_NOTIFICATION, GUID_MOF_RESOURCE_REMOVED_NOTIFICATION, WMIREGINFOW::GuidCount, tagInstanceSet::GuidEntry, tagInstanceSet::GuidISList, PTRCACHE::InstanceSet, IS_NEWLY_REGISTERED, tagGUIDENTRY::ISCount, IsEqualGUID, NULL, PAGED_CODE, RegistrationAdd, RegistrationDelete, RegistrationUpdate, RemoveEntryList(), STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, WmipCachePtrs(), WmipDebugPrintEx, WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), WmipEnterSMCritSection, WmipFree, WmipGenerateBinaryMofNotification(), WmipLeaveSMCritSection, WmipReferenceDS, WmipSendGuidUpdateNotifications(), WmipUnreferenceDS, WmipUnreferenceGE, WmipUnreferenceIS, WmipUpdateModifyGuid(), WmipUpdateRemoveGuid(), WMIREG_FLAG_REMOVE_GUID, and WMIREGINFOW::WmiRegGuid.
Referenced by WmipProcessWmiRegInfo().
void WmipUpdateDeviceStackSize (CCHAR NewStackSize)
Definition at line 426 of file wmi.c.
References PAGED_CODE, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipServiceDeviceObject.
Referenced by WmipForwardWmiIrp(), and WmipRegisterDevice().
NTSTATUS WmipUpdateRegistration (PDEVICE_OBJECT DeviceObject)
Definition at line 617 of file register.c.
References FALSE, NULL, PAGED_CODE, RegisterUpdateSingleDriver, Status, STATUS_INVALID_PARAMETER, WmipFindRegEntryByDevice(), WmipQueueRegWork(), and WmipUnreferenceRegEntry.
Referenced by IoWMIRegistrationControl().
NTSTATUS WmipValidateWmiRegInfoString (PWMIREGINFO WmiRegInfo, ULONG BufferSize, ULONG Offset, PWCHAR * String)
Definition at line 1187 of file register.c.
References NULL, OffsetToPtr, PAGED_CODE, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by WmipBuildInstanceSet(), and WmipProcessWmiRegInfo().
NTSTATUS WmipWriteWnodeToObject (PWMIGUIDOBJECT Object, PWNODE_HEADER Wnode, BOOLEAN IsHighPriority)
Definition at line 3984 of file consumer.c.
References _WNODE_HEADER::BufferSize, DPFLTR_WMICORE_ID, _WNODE_HEADER::Flags, IO_NO_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IoSetCancelRoutine, _WMIGUIDOBJECT::Irp, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, RtlCopyMemory, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_SUCCESS, WmipAssert, WmipClearIrpObjectList(), WmipDebugPrintEx, WmipQueueEventToObject, WNODE_FLAG_TOO_SMALL, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by WmipDeleteMethod(), WmipDeliverWnodeToDS(), WmipProcessEvent(), and WmipWriteMBToObject().
NTSTATUS FASTCALL WmiTraceUserMessage (IN PMESSAGE_TRACE_USER pMessage, IN ULONG MessageSize)
Definition at line 1987 of file traceapi.c.
References except, EXCEPTION_EXECUTE_HANDLER, NULL, ProbeForRead, STATUS_UNSUCCESSFUL, TraceDebug, and WmiTraceMessage().
Referenced by WmipFastIoDeviceControl(), and WmipIoControl().
Variable Documentation
GUID GUID_MOF_RESOURCE_ADDED_NOTIFICATION
Definition at line 31 of file alloc.c.
Referenced by WmipAddDataSource(), WmipIoControl(), and WmipUpdateDataSource().
GUID GUID_MOF_RESOURCE_REMOVED_NOTIFICATION
Definition at line 36 of file alloc.c.
Referenced by WmipIoControl(), and WmipUpdateDataSource().
GUID GUID_REGISTRATION_CHANGE_NOTIFICATION
Definition at line 26 of file alloc.c.
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.
ULONG WmipCpePollInterval
const GUID WmipDataProviderPnpidGuid
Definition at line 106 of file register.c.
Referenced by WmipForwardWmiIrp(), and WmipTranslatePDOInstanceNames().
const GUID WmipDataProviderPnPIdInstanceNamesGuid
Definition at line 107 of file register.c.
Referenced by WmipForwardWmiIrp(), and WmipTranslatePDOInstanceNames().
LONG WmipEventWorkItems
Definition at line 38 of file notify.c.
Referenced by IoWMIWriteEvent(), and WmipEventNotification().
WORK_QUEUE_ITEM WmipEventWorkQueueItem
Definition at line 35 of file notify.c.
Referenced by IoWMIWriteEvent().
POBJECT_TYPE WmipGuidObjectType
Definition at line 147 of file secure.c.
Referenced by IoWMIOpenBlock(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipQueryAllData(), WmipQueryGuidInfo(), WmipQuerySetExecuteSI(), WmipReceiveNotifications(), WmipTranslateFileHandle(), and WmipWriteMBToObject().
LONG WmipInUseRegEntryCount
Definition at line 99 of file register.c.
Referenced by WmipAllocRegEntry(), WmipDisableKernelTrace(), WmipDoUnreferenceRegEntry(), and WmipEnableKernelTrace().
LIST_ENTRY WmipInUseRegEntryHead
Definition at line 98 of file register.c.
Referenced by WmipDisableKernelTrace(), and WmipEnableKernelTrace().
ULONG WmipMaxKmWnodeEventSize
Definition at line 154 of file wmi.c.
Referenced by IoWMIWriteEvent().
LIST_ENTRY WmipNPEvent
Definition at line 36 of file notify.c.
Referenced by IoWMIWriteEvent().
KSPIN_LOCK WmipNPNotificationSpinlock
Definition at line 37 of file notify.c.
Referenced by IoWMIWriteEvent(), WmipEventNotification(), and WmipInitializeNotifications().
ULONG WmipNSAllocCount
ULONG WmipNSAllocMax
KMUTEX WmipRegistrationMutex
Definition at line 104 of file register.c.
KSPIN_LOCK WmipRegistrationSpinLock
Definition at line 101 of file register.c.
Referenced by IoWMIWriteEvent(), WmipAllocRegEntry(), WmipDoUnreferenceRegEntry(), and WmipInitializeRegistration().
UNICODE_STRING WmipRegistryPath
Definition at line 171 of file wmi.c.
Referenced by WmipQueryWmiRegInfo().
PDEVICE_OBJECT WmipServiceDeviceObject
Definition at line 149 of file wmi.c.
Referenced by WMIInitialize(), WmipBuildMcaCmcEvent(), WmipDisableKernelTrace(), WmipDriverEntry(), WmipEnableKernelTrace(), WmipForwardWmiIrp(), WmipSendWmiIrp(), WmipSetTraceNotify(), WmipUpdateDeviceStackSize(), and WmipWriteToEventlog().
ULONG WmipSMBiosTableLength
PHYSICAL_ADDRESS WmipSMBiosTablePhysicalAddress
PUCHAR WmipSMBiosTableVirtualAddress
KMUTEX WmipSMMutex
Definition at line 166 of file wmi.c.
KMUTEX WmipTLMutex
Definition at line 167 of file wmi.c.
const WMILIB_INFO WmipWmiLibInfo
Definition at line 197 of file dataprov.c.
Referenced by WmipSystemControl().