Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/name.c File Reference
name.c File Reference
#include "FsRtlP.h"
Macros
#define Dbg (0x10000000)
#define MATCHES_ARRAY_SIZE 16
#define MODULE_POOL_TAG ('nrSF')
Functions
BOOLEAN FsRtlAreNamesEqual (__in PCUNICODE_STRING ConstantNameA, __in PCUNICODE_STRING ConstantNameB, __in BOOLEAN IgnoreCase, __in_opt PCWCH UpcaseTable)
VOID FsRtlDissectName (__in UNICODE_STRING Path, __out PUNICODE_STRING FirstName, __out PUNICODE_STRING RemainingName)
BOOLEAN FsRtlDoesNameContainWildCards (__in PUNICODE_STRING Name)
BOOLEAN FsRtlIsNameInExpression (__in PUNICODE_STRING Expression, __in PUNICODE_STRING Name, __in BOOLEAN IgnoreCase, __in_opt PWCH UpcaseTable)
BOOLEAN FsRtlIsNameInExpressionPrivate (IN PUNICODE_STRING Expression, IN PUNICODE_STRING Name, IN BOOLEAN IgnoreCase, IN PWCH UpcaseTable)
Macro Definition Documentation
#define Dbg (0x10000000)
Definition at line 45 of file name.c.
Referenced by FsRtlIsNameInExpressionPrivate().
#define MATCHES_ARRAY_SIZE 16
Definition at line 458 of file name.c.
Referenced by FsRtlIsNameInExpressionPrivate().
#define MODULE_POOL_TAG ('nrSF')
Definition at line 52 of file name.c.
Function Documentation
BOOLEAN FsRtlAreNamesEqual (__in PCUNICODE_STRING ConstantNameA, __in PCUNICODE_STRING ConstantNameB, __in BOOLEAN IgnoreCase, __in_opt PCWCH UpcaseTable)
Definition at line 271 of file name.c.
References ARGUMENT_PRESENT, ExRaiseStatus(), FALSE, Index, NT_SUCCESS, PAGED_CODE, RtlEqualMemory, RtlFreeUnicodeString(), RtlUpcaseUnicodeString(), Status, and TRUE.
VOID FsRtlDissectName (__in UNICODE_STRING Path, __out PUNICODE_STRING FirstName, __out PUNICODE_STRING RemainingName)
Definition at line 76 of file name.c.
References NOTHING, NULL, and PAGED_CODE.
BOOLEAN FsRtlDoesNameContainWildCards (__in PUNICODE_STRING Name)
Definition at line 212 of file name.c.
References FALSE, FsRtlIsUnicodeCharacterWild, PAGED_CODE, and TRUE.
Referenced by FsRtlIsNameInExpressionPrivate().
BOOLEAN FsRtlIsNameInExpression (__in PUNICODE_STRING Expression, __in PUNICODE_STRING Name, __in BOOLEAN IgnoreCase, __in_opt PWCH UpcaseTable)
Definition at line 398 of file name.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, ExRaiseStatus(), FALSE, FsRtlIsNameInExpressionPrivate(), NT_SUCCESS, NULL, RtlFreeUnicodeString(), RtlUpcaseUnicodeString(), Status, and TRUE.
BOOLEAN FsRtlIsNameInExpressionPrivate (IN PUNICODE_STRING Expression, IN PUNICODE_STRING Name, IN BOOLEAN IgnoreCase, IN PWCH UpcaseTable)
Definition at line 465 of file name.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, Dbg, DebugTrace, DOS_DOT, DOS_QM, DOS_STAR, ExFreePool(), FALSE, FsRtlDoesNameContainWildCards(), FsRtlpAllocatePool, _UNICODE_STRING::Length, MATCHES_ARRAY_SIZE, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlEqualMemory, and TRUE.
Referenced by FsRtlIsNameInExpression().