Windows Research Kernel v1.2: C:/Windows Research Kernel/se/tokenopn.c File Reference
tokenopn.c File Reference
#include "pch.h"
Functions
NTSTATUS NtOpenProcessToken (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __out PHANDLE TokenHandle)
NTSTATUS NtOpenProcessTokenEx (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __out PHANDLE TokenHandle)
NTSTATUS NtOpenThreadToken (__in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in BOOLEAN OpenAsSelf, __out PHANDLE TokenHandle)
NTSTATUS NtOpenThreadTokenEx (__in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in BOOLEAN OpenAsSelf, __in ULONG HandleAttributes, __out PHANDLE TokenHandle)
NTSTATUS SepCreateImpersonationTokenDacl (IN PTOKEN Token, IN PACCESS_TOKEN PrimaryToken, OUT PACL *Acl)
NTSTATUS SepCreateImpersonationTokenDacl (__in PTOKEN Token, __in PACCESS_TOKEN PrimaryToken, __deref_out PACL *Acl)
NTSTATUS SepOpenTokenOfThread (__in HANDLE ThreadHandle, __in BOOLEAN OpenAsSelf, __deref_out PACCESS_TOKEN *Token, __deref_out PETHREAD *Thread, __out PBOOLEAN CopyOnOpen, __out PBOOLEAN EffectiveOnly, __out PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Function Documentation
NTSTATUS NtOpenProcessToken (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __out PHANDLE TokenHandle)
Definition at line 182 of file tokenopn.c.
References NtOpenProcessTokenEx().
Referenced by RtlAdjustPrivilege(), RtlpImpersonateSelfEx(), and RtlpSysVolTakeOwnership().
NTSTATUS NtOpenProcessTokenEx (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __out PHANDLE TokenHandle)
Definition at line 220 of file tokenopn.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObSanitizeHandleAttributes(), PAGED_CODE, ProbeForWriteHandle, PsOpenTokenOfProcess(), SeTokenObjectType, and Status.
Referenced by NtOpenProcessToken().
NTSTATUS NtOpenThreadToken (__in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in BOOLEAN OpenAsSelf, __out PHANDLE TokenHandle)
Definition at line 489 of file tokenopn.c.
References NtOpenThreadTokenEx().
Referenced by RtlAdjustPrivilege().
NTSTATUS NtOpenThreadTokenEx (__in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in BOOLEAN OpenAsSelf, __in ULONG HandleAttributes, __out PHANDLE TokenHandle)
Definition at line 551 of file tokenopn.c.
References ASSERT, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, InitializeObjectAttributes, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObInsertObject(), ObOpenObjectByPointer(), ObReferenceObject, ObReferenceObjectByHandle, ObSanitizeHandleAttributes(), PAGED_CODE, ProbeForWriteHandle, PsDereferencePrimaryTokenEx, PsDisableImpersonation(), PsGetCurrentThread(), PsImpersonateClient(), PsReferencePrimaryToken(), PsRestoreImpersonation(), PsThreadType, RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), SECURITY_DESCRIPTOR_REVISION, SepCreateImpersonationTokenDacl(), SepDuplicateToken(), SepOpenTokenOfThread(), SeTokenObjectType, Status, STATUS_OBJECT_TYPE_MISMATCH, THREAD_ALL_ACCESS, THREAD_TO_PROCESS, TokenImpersonation, and TRUE.
Referenced by NtOpenThreadToken().
NTSTATUS SepCreateImpersonationTokenDacl (IN PTOKEN Token, IN PACCESS_TOKEN PrimaryToken, OUT PACL * Acl)
Referenced by NtOpenThreadTokenEx().
NTSTATUS SepCreateImpersonationTokenDacl (__in PTOKEN Token, __in PACCESS_TOKEN PrimaryToken, __deref_out PACL * Acl)
Definition at line 53 of file tokenopn.c.
References ACL_REVISION2, ARGUMENT_PRESENT, ASSERT, ExAllocatePool, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlAddAccessAllowedAce(), RtlCreateAcl(), SeAliasAdminsSid, SeLengthSid, SeLocalSystemSid, SeRestrictedSid, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TOKEN_ALL_ACCESS.
NTSTATUS SepOpenTokenOfThread (__in HANDLE ThreadHandle, __in BOOLEAN OpenAsSelf, __deref_out PACCESS_TOKEN * Token, __deref_out PETHREAD * Thread, __out PBOOLEAN CopyOnOpen, __out PBOOLEAN EffectiveOnly, __out PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 344 of file tokenopn.c.
References FALSE, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsDereferenceImpersonationToken, PsReferenceImpersonationToken(), PsThreadType, SecurityAnonymous, Status, STATUS_CANT_OPEN_ANONYMOUS, STATUS_NO_TOKEN, STATUS_SUCCESS, and THREAD_QUERY_INFORMATION.
Referenced by NtOpenThreadTokenEx().