Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ex.h File Reference
ex.h File Reference
Data Structures
struct _CALL_HASH_ENTRY
struct _CALL_PERFORMANCE_DATA
struct _EEVENT_PAIR
struct _ERESOURCE
struct _EX_CALLBACK
struct _EX_CALLBACK_ROUTINE_BLOCK
struct _EX_DEBUG_LOG
struct _EX_DEBUG_LOG_EVENT
struct _EX_DEBUG_LOG_TAG
struct _EX_FAST_REF
struct _EX_PUSH_LOCK
struct _EX_PUSH_LOCK_CACHE_AWARE
struct _EX_PUSH_LOCK_CACHE_AWARE_PADDED
struct _EX_RUNDOWN_REF
struct _EX_RUNDOWN_REF_CACHE_AWARE
struct _EX_WORK_QUEUE
struct _EXHANDLE
struct _FAST_MUTEX
struct _GENERAL_LOOKASIDE
struct _HANDLE_TABLE
struct _HANDLE_TABLE_ENTRY
struct _HANDLE_TABLE_ENTRY_INFO
struct _HANDLE_TRACE_DB_ENTRY
struct _HANDLE_TRACE_DEBUG_INFO
struct _NBQUEUE_BLOCK
struct _NPAGED_LOOKASIDE_LIST
struct _OWNER_ENTRY
struct _PAGED_LOOKASIDE_LIST
struct _RESOURCE_HASH_ENTRY
struct _RESOURCE_PERFORMANCE_DATA
struct _WORK_QUEUE_ITEM
struct _ZONE_HEADER
struct _ZONE_SEGMENT_HEADER
union EX_QUEUE_WORKER_INFO
Macros
#define CALL_HASH_TABLE_SIZE 64
#define EX_CACHE_LINE_SIZE 128
#define EX_DEBUG_LOG_FORMAT_HANDLE (UCHAR)7
#define EX_DEBUG_LOG_FORMAT_NONE (UCHAR)0
#define EX_DEBUG_LOG_FORMAT_OBJECT (UCHAR)6
#define EX_DEBUG_LOG_FORMAT_PSZ (UCHAR)2
#define EX_DEBUG_LOG_FORMAT_PWSZ (UCHAR)3
#define EX_DEBUG_LOG_FORMAT_STRING (UCHAR)4
#define EX_DEBUG_LOG_FORMAT_ULONG (UCHAR)1
#define EX_DEBUG_LOG_FORMAT_USTRING (UCHAR)5
#define EX_DEBUG_LOG_NUMBER_OF_BACK_TRACES 4
#define EX_DEBUG_LOG_NUMBER_OF_DATA_VALUES 4
#define EX_PUSH_LOCK_FANNED_COUNT (PAGE_SIZE/EX_CACHE_LINE_SIZE)
#define EX_PUSH_LOCK_FLAGS_EXCLUSIVE (0x1)
#define EX_PUSH_LOCK_FLAGS_SPINNING (0x2)
#define EX_PUSH_LOCK_FLAGS_SPINNING_V (0x1)
#define EX_PUSH_LOCK_LOCK ((ULONG_PTR)0x1)
#define EX_PUSH_LOCK_LOCK_V ((ULONG_PTR)0x0)
#define EX_PUSH_LOCK_MULTIPLE_SHARED ((ULONG_PTR)0x8)
#define EX_PUSH_LOCK_PTR_BITS ((ULONG_PTR)0xf)
#define EX_PUSH_LOCK_SHARE_INC ((ULONG_PTR)0x10)
#define EX_PUSH_LOCK_WAITING ((ULONG_PTR)0x2)
#define EX_PUSH_LOCK_WAKING ((ULONG_PTR)0x4)
#define EX_RUNDOWN_ACTIVE 0x1
#define EX_RUNDOWN_COUNT_INC (1<<EX_RUNDOWN_COUNT_SHIFT)
#define EX_RUNDOWN_COUNT_SHIFT 0x1
#define EX_WORKER_QUEUE_DISABLED 0x80000000
#define ExAcquireFastMutexUnsafe(FastMutex) xxAcquireFastMutexUnsafe(FastMutex)
#define ExAcquireResourceExclusive ExAcquireResourceExclusiveLite
#define ExAcquireResourceShared ExAcquireResourceSharedLite
#define ExAllocateFromZone(Zone)
#define ExAllocatePoolWithQuotaTag(a, b, c) ExAllocatePoolWithQuota(a,b)
#define ExAllocatePoolWithTag(a, b, c) ExAllocatePool(a,b)
#define ExConvertExclusiveToShared ExConvertExclusiveToSharedLite
#define ExDeleteResource ExDeleteResourceLite
#define ExDisableResourceBoost ExDisableResourceBoostLite
#define ExFreePoolWithTag(a, b) ExFreePool(a)
#define ExFreeToZone(Zone, Block)
#define ExGetCurrentResourceThread() ((ULONG_PTR)PsGetCurrentThread())
#define ExGetHandleInfo(HT, H, E) ((HT)->ExtraInfoPages ? ExpGetHandleInfo((HT),(H),(E)) : NULL)
#define ExInitializeFastMutex(_FastMutex)
#define ExInitializeResource ExInitializeResourceLite
#define ExInitializeSListHead InitializeSListHead
#define ExInitializeWorkItem(Item, Routine, Context)
#define ExInterlockedAddLargeStatistic(Addend, Increment) (VOID) _InterlockedAddLargeStatistic ((PLONGLONG)&(Addend)->QuadPart, Increment)
#define ExInterlockedAllocateFromZone(Zone, Lock) (PVOID) ExInterlockedPopEntryList(&(Zone)->FreeList, Lock)
#define ExInterlockedCompareExchange64(Destination, Exchange, Comperand, Lock) ExfInterlockedCompareExchange64(Destination, Exchange, Comperand)
#define ExInterlockedFreeToZone(Zone, Block, Lock) ExInterlockedPushEntryList(&(Zone)->FreeList, ((PSINGLE_LIST_ENTRY) (Block)), Lock)
#define ExInterlockedPopEntrySList(ListHead, Lock) InterlockedPopEntrySList(ListHead)
#define ExInterlockedPushEntrySList(ListHead, ListEntry, Lock) InterlockedPushEntrySList(ListHead, ListEntry)
#define ExIsFastMutexOwned(_FastMutex) ((_FastMutex)->Count != 1)
#define ExIsFullZone(Zone) ((Zone)->FreeList.Next == (PSINGLE_LIST_ENTRY)NULL)
#define ExIsObjectInFirstZoneSegment(Zone, Object)
#define ExIsResourceAcquired ExIsResourceAcquiredSharedLite
#define ExIsResourceAcquiredExclusive ExIsResourceAcquiredExclusiveLite
#define ExIsResourceAcquiredLite ExIsResourceAcquiredSharedLite
#define ExIsResourceAcquiredShared ExIsResourceAcquiredSharedLite
#define EXP_SPIN_LOCK_EXCLUSIVE 0x80000000
#define ExQueryDepthSList(_listhead_) (_listhead_)->Depth
#define ExReleaseFastMutexUnsafe(FastMutex) xxReleaseFastMutexUnsafe(FastMutex)
#define ExReleaseResource(R) (ExReleaseResourceLite(R))
#define ExReleaseResourceForThread ExReleaseResourceForThreadLite
#define ExSetHandleTableOrder(ht, or) {NOTHING;}
#define ExSetHandleTableOwner(ht, id) {(ht)->UniqueProcessId = (id);}
#define FM_LOCK_BIT 0x1
#define FM_LOCK_BIT_V 0x0
#define FM_LOCK_WAITER_INC 0x4
#define FM_LOCK_WAITER_WOKEN 0x2
#define HANDLE_TABLE_LOCKS 4
#define HANDLE_TRACE_DB_BADREF 3
#define HANDLE_TRACE_DB_CLOSE 2
#define HANDLE_TRACE_DB_DEFAULT_STACKS 4096
#define HANDLE_TRACE_DB_MAX_STACKS 65536
#define HANDLE_TRACE_DB_MIN_STACKS 128
#define HANDLE_TRACE_DB_OPEN 1
#define HANDLE_TRACE_DB_STACK_SIZE 16
#define HANDLE_TRACE_DEBUG_INFO_BREAK_ON_WRAP_AROUND 0x4
#define HANDLE_TRACE_DEBUG_INFO_CLEAN_DEBUG_INFO 0x1
#define HANDLE_TRACE_DEBUG_INFO_COMPACT_CLOSE_HANDLE 0x2
#define HANDLE_TRACE_DEBUG_INFO_WAS_SOMETIME_CLEANED 0x80000000
#define HANDLE_TRACE_DEBUG_INFO_WAS_WRAPPED_AROUND 0x40000000
#define HANDLE_VALUE_INC 4
#define InterlockedFlushSList(Head) ExInterlockedFlushSList(Head)
#define MAX_FAST_REFS 7
#define POOL_COLD_ALLOCATION 256
#define POOL_MM_ALLOCATION 0x80000000
#define POOL_QUOTA_FAIL_INSTEAD_OF_RAISE 8
#define POOL_RAISE_IF_ALLOCATION_FAILURE 16
#define ProbeAndNullPointer(Address)
#define ProbeAndReadBoolean(Address)
#define ProbeAndReadChar(Address)
#define ProbeAndReadHandle(Address)
#define ProbeAndReadLargeInteger(Source)
#define ProbeAndReadLong(Address)
#define ProbeAndReadPointer(Address)
#define ProbeAndReadQuad(Address)
#define ProbeAndReadShort(Address)
#define ProbeAndReadStructure(Source, STRUCTURE)
#define ProbeAndReadStructureEx(Dst, Src, STRUCTURE) (Dst) = ProbeAndReadStructure(Src, STRUCTURE)
#define ProbeAndReadUchar(Address)
#define ProbeAndReadUlargeInteger(Source)
#define ProbeAndReadUlong(Address)
#define ProbeAndReadUlong_ptr(Address)
#define ProbeAndReadUnicodeString(Source)
#define ProbeAndReadUnicodeStringEx(Dst, Src) *(Dst) = ProbeAndReadUnicodeString(Src)
#define ProbeAndReadUquad(Address)
#define ProbeAndReadUshort(Address)
#define ProbeAndWriteBoolean(Address, Value)
#define ProbeAndWriteChar(Address, Value)
#define ProbeAndWriteHandle(Address, Value)
#define ProbeAndWriteLong(Address, Value)
#define ProbeAndWritePointer(Address, Value)
#define ProbeAndWriteQuad(Address, Value)
#define ProbeAndWriteShort(Address, Value)
#define ProbeAndWriteStructure(Address, Value, STRUCTURE)
#define ProbeAndWriteUchar(Address, Value)
#define ProbeAndWriteUlong(Address, Value)
#define ProbeAndWriteUlong_ptr(Address, Value)
#define ProbeAndWriteUquad(Address, Value)
#define ProbeAndWriteUshort(Address, Value)
#define ProbeAndZeroHandle(Address)
#define ProbeForRead(Address, Length, Alignment)
#define ProbeForReadSmallStructure(Address, Size, Alignment)
#define ProbeForWriteBoolean(Address)
#define ProbeForWriteChar(Address)
#define ProbeForWriteHandle(Address)
#define ProbeForWriteIoStatus(Address)
#define ProbeForWriteIoStatusEx(Address, Cookie) ProbeForWriteIoStatus(Address)
#define ProbeForWriteLong(Address)
#define ProbeForWritePointer(Address)
#define ProbeForWriteQuad(Address)
#define ProbeForWriteShort(Address)
#define ProbeForWriteUchar(Address)
#define ProbeForWriteUlong(Address)
#define ProbeForWriteUlong_ptr(Address)
#define ProbeForWriteUquad(Address)
#define ProbeForWriteUshort(Address)
#define PROTECTED_POOL 0x80000000
#define QueryDepthSList(Head) ExQueryDepthSList(Head)
#define RECORD_CALL_DATA(Table)
#define RESOURCE_HASH_TABLE_SIZE 64
#define ResourceNeverExclusive 0x10
#define ResourceOwnedExclusive 0x80
#define ResourceReleaseByOtherThread 0x20
Typedefs
typedef struct _CALL_HASH_ENTRY CALL_HASH_ENTRY
typedef struct _CALL_PERFORMANCE_DATA CALL_PERFORMANCE_DATA
typedef struct _EEVENT_PAIR EEVENT_PAIR
typedef struct _ERESOURCE ERESOURCE
typedef ULONG_PTR ERESOURCE_THREAD
typedef struct _EX_CALLBACK EX_CALLBACK
typedef struct _EX_CALLBACK_ROUTINE_BLOCK EX_CALLBACK_ROUTINE_BLOCK
typedef struct _EX_DEBUG_LOG EX_DEBUG_LOG
typedef struct _EX_DEBUG_LOG_EVENT EX_DEBUG_LOG_EVENT
typedef struct _EX_DEBUG_LOG_TAG EX_DEBUG_LOG_TAG
typedef VOID(* EX_DESTROY_HANDLE_ROUTINE) (IN HANDLE Handle)
typedef BOOLEAN(* EX_DUPLICATE_HANDLE_ROUTINE) (IN struct _EPROCESS *Process OPTIONAL, IN PHANDLE_TABLE OldHandleTable, IN PHANDLE_TABLE_ENTRY OldHandleTableEntry, IN PHANDLE_TABLE_ENTRY HandleTableEntry)
typedef BOOLEAN(* EX_ENUMERATE_HANDLE_ROUTINE) (IN PHANDLE_TABLE_ENTRY HandleTableEntry, IN HANDLE Handle, IN PVOID EnumParameter)
typedef struct _EX_FAST_REF EX_FAST_REF
typedef enum _EX_POOL_PRIORITY EX_POOL_PRIORITY
typedef struct _EX_PUSH_LOCK EX_PUSH_LOCK
typedef struct _EX_PUSH_LOCK_CACHE_AWARE EX_PUSH_LOCK_CACHE_AWARE
typedef struct _EX_PUSH_LOCK_CACHE_AWARE_PADDED EX_PUSH_LOCK_CACHE_AWARE_PADDED
typedef struct _EX_RUNDOWN_REF EX_RUNDOWN_REF
typedef struct _EX_RUNDOWN_REF_CACHE_AWARE EX_RUNDOWN_REF_CACHE_AWARE
typedef LONG EX_SPIN_LOCK
typedef struct _EX_WORK_QUEUE EX_WORK_QUEUE
typedef struct _EXHANDLE EXHANDLE
typedef struct _FAST_MUTEX FAST_MUTEX
typedef struct DECLSPEC_CACHEALIGN _GENERAL_LOOKASIDE GENERAL_LOOKASIDE
typedef struct _HANDLE_TABLE HANDLE_TABLE
typedef struct _HANDLE_TABLE_ENTRY HANDLE_TABLE_ENTRY
typedef struct _HANDLE_TABLE_ENTRY_INFO HANDLE_TABLE_ENTRY_INFO
typedef struct _HANDLE_TRACE_DB_ENTRY HANDLE_TRACE_DB_ENTRY
typedef struct _HANDLE_TRACE_DEBUG_INFO HANDLE_TRACE_DEBUG_INFO
typedef struct _NBQUEUE_BLOCK NBQUEUE_BLOCK
typedef struct DECLSPEC_CACHEALIGN _NPAGED_LOOKASIDE_LIST NPAGED_LOOKASIDE_LIST
typedef struct _OWNER_ENTRY OWNER_ENTRY
typedef struct DECLSPEC_CACHEALIGN _PAGED_LOOKASIDE_LIST PAGED_LOOKASIDE_LIST
typedef PVOID(* PALLOCATE_FUNCTION) (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag)
typedef struct _CALL_HASH_ENTRY * PCALL_HASH_ENTRY
typedef struct _CALL_PERFORMANCE_DATA * PCALL_PERFORMANCE_DATA
typedef VOID(* PCALLBACK_FUNCTION) (__in_opt PVOID CallbackContext, __in_opt PVOID Argument1, __in_opt PVOID Argument2)
typedef struct _CALLBACK_OBJECT * PCALLBACK_OBJECT
typedef struct _EEVENT_PAIR * PEEVENT_PAIR
typedef struct _ERESOURCE * PERESOURCE
typedef ERESOURCE_THREAD * PERESOURCE_THREAD
typedef struct _EX_CALLBACK * PEX_CALLBACK
typedef NTSTATUS(* PEX_CALLBACK_FUNCTION) (IN PVOID CallbackContext, IN PVOID Argument1, IN PVOID Argument2)
typedef struct _EX_CALLBACK_ROUTINE_BLOCK * PEX_CALLBACK_ROUTINE_BLOCK
typedef BOOLEAN(* PEX_CHANGE_HANDLE_ROUTINE) (IN OUT PHANDLE_TABLE_ENTRY HandleTableEntry, IN ULONG_PTR Parameter)
typedef struct _EX_DEBUG_LOG * PEX_DEBUG_LOG
typedef struct _EX_DEBUG_LOG_EVENT * PEX_DEBUG_LOG_EVENT
typedef struct _EX_DEBUG_LOG_TAG * PEX_DEBUG_LOG_TAG
typedef struct _EX_FAST_REF * PEX_FAST_REF
typedef struct _EX_PUSH_LOCK * PEX_PUSH_LOCK
typedef struct _EX_PUSH_LOCK_CACHE_AWARE * PEX_PUSH_LOCK_CACHE_AWARE
typedef struct _EX_PUSH_LOCK_CACHE_AWARE_PADDED * PEX_PUSH_LOCK_CACHE_AWARE_PADDED
typedef struct _EX_RUNDOWN_REF * PEX_RUNDOWN_REF
typedef struct _EX_RUNDOWN_REF_CACHE_AWARE * PEX_RUNDOWN_REF_CACHE_AWARE
typedef NTSTATUS(* PEX_SNAPSHOT_HANDLE_ENTRY) (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY HandleEntry, IN HANDLE Handle, IN ULONG Length, IN OUT PULONG RequiredLength)
typedef NTSTATUS(* PEX_SNAPSHOT_HANDLE_ENTRY_EX) (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO_EX *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY HandleEntry, IN HANDLE Handle, IN ULONG Length, IN OUT PULONG RequiredLength)
typedef LONG * PEX_SPIN_LOCK
typedef struct _EX_WORK_QUEUE * PEX_WORK_QUEUE
typedef struct _EXHANDLE * PEXHANDLE
typedef struct _FAST_MUTEX * PFAST_MUTEX
typedef VOID(* PFREE_FUNCTION) (IN PVOID Buffer)
typedef struct DECLSPEC_CACHEALIGN _GENERAL_LOOKASIDE * PGENERAL_LOOKASIDE
typedef struct _HANDLE_TABLE * PHANDLE_TABLE
typedef struct _HANDLE_TABLE_ENTRY * PHANDLE_TABLE_ENTRY
typedef struct _HANDLE_TABLE_ENTRY_INFO * PHANDLE_TABLE_ENTRY_INFO
typedef struct _HANDLE_TRACE_DB_ENTRY * PHANDLE_TRACE_DB_ENTRY
typedef struct _HANDLE_TRACE_DEBUG_INFO * PHANDLE_TRACE_DEBUG_INFO
typedef PVOID(* PKWIN32_GLOBALATOMTABLE_CALLOUT) (void)
typedef struct _NBQUEUE_BLOCK * PNBQUEUE_BLOCK
typedef struct DECLSPEC_CACHEALIGN _NPAGED_LOOKASIDE_LIST * PNPAGED_LOOKASIDE_LIST
typedef enum _POOL_TYPE POOL_TYPE
typedef struct _OWNER_ENTRY * POWNER_ENTRY
typedef enum _PP_NPAGED_LOOKASIDE_NUMBER PP_NPAGED_LOOKASIDE_NUMBER
typedef struct DECLSPEC_CACHEALIGN _PAGED_LOOKASIDE_LIST * PPAGED_LOOKASIDE_LIST
typedef enum _PP_NPAGED_LOOKASIDE_NUMBER * PPP_NPAGED_LOOKASIDE_NUMBER
typedef struct _RESOURCE_HASH_ENTRY * PRESOURCE_HASH_ENTRY
typedef struct _RESOURCE_PERFORMANCE_DATA * PRESOURCE_PERFORMANCE_DATA
typedef struct _WORK_QUEUE_ITEM * PWORK_QUEUE_ITEM
typedef VOID(* PWORKER_THREAD_ROUTINE) (IN PVOID Parameter)
typedef struct _ZONE_HEADER * PZONE_HEADER
typedef struct _ZONE_SEGMENT_HEADER * PZONE_SEGMENT_HEADER
typedef struct _RESOURCE_HASH_ENTRY RESOURCE_HASH_ENTRY
typedef struct _RESOURCE_PERFORMANCE_DATA RESOURCE_PERFORMANCE_DATA
typedef GUID UUID
typedef struct _WORK_QUEUE_ITEM WORK_QUEUE_ITEM
typedef enum _WORK_QUEUE_TYPE WORK_QUEUE_TYPE
typedef struct _ZONE_HEADER ZONE_HEADER
typedef struct _ZONE_SEGMENT_HEADER ZONE_SEGMENT_HEADER
Enumerations
enum _EX_POOL_PRIORITY {
LowPoolPriority, LowPoolPrioritySpecialPoolOverrun = 8, LowPoolPrioritySpecialPoolUnderrun = 9, NormalPoolPriority = 16,
NormalPoolPrioritySpecialPoolOverrun = 24, NormalPoolPrioritySpecialPoolUnderrun = 25, HighPoolPriority = 32, HighPoolPrioritySpecialPoolOverrun = 40,
HighPoolPrioritySpecialPoolUnderrun = 41
}
enum _POOL_TYPE {
NonPagedPool, PagedPool, NonPagedPoolMustSucceed, DontUseThisType,
NonPagedPoolCacheAligned, PagedPoolCacheAligned, NonPagedPoolCacheAlignedMustS, MaxPoolType,
NonPagedPoolSession = 32, PagedPoolSession = NonPagedPoolSession + 1, NonPagedPoolMustSucceedSession = PagedPoolSession + 1, DontUseThisTypeSession = NonPagedPoolMustSucceedSession + 1,
NonPagedPoolCacheAlignedSession = DontUseThisTypeSession + 1, PagedPoolCacheAlignedSession = NonPagedPoolCacheAlignedSession + 1, NonPagedPoolCacheAlignedMustSSession = PagedPoolCacheAlignedSession + 1
}
enum _PP_NPAGED_LOOKASIDE_NUMBER {
LookasideSmallIrpList, LookasideLargeIrpList, LookasideMdlList, LookasideCreateInfoList,
LookasideNameBufferList, LookasideTwilightList, LookasideCompletionList, LookasideMaximumList
}
enum _WORK_QUEUE_TYPE { CriticalWorkQueue, DelayedWorkQueue, HyperCriticalWorkQueue, MaximumWorkQueue }
Functions
DECLSPEC_DEPRECATED_DDK NTKERNELAPI __bcount (NumberOfBytes) PVOID ExAllocatePool(__in POOL_TYPE PoolType
LONG _InterlockedAddLargeStatistic (IN PLONGLONG Addend, IN ULONG Increment)
C_ASSERT (sizeof(FAST_MUTEX)==sizeof(KGUARDED_MUTEX))
C_ASSERT (sizeof(NPAGED_LOOKASIDE_LIST)==sizeof(PAGED_LOOKASIDE_LIST))
struct DECLSPEC_ALIGN (16) _EX_PUSH_LOCK_WAIT_BLOCK *PEX_PUSH_LOCK_WAIT_BLOCK
NTKERNELAPI VOID ExAcquireCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE CacheAwarePushLock)
PEX_PUSH_LOCK FORCEINLINE ExAcquireCacheAwarePushLockShared (IN PEX_PUSH_LOCK_CACHE_AWARE CacheAwarePushLock)
NTKERNELAPI VOID FASTCALL ExAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
VOID FORCEINLINE ExAcquirePushLockExclusive (IN PEX_PUSH_LOCK PushLock)
VOID FORCEINLINE ExAcquirePushLockShared (IN PEX_PUSH_LOCK PushLock)
VOID FORCEINLINE ExAcquirePushLockSharedAssumeNoOwner (IN PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FORCEINLINE ExAcquireReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN ExAcquireResourceExclusiveLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
NTKERNELAPI BOOLEAN ExAcquireResourceSharedLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in ULONG Count)
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
NTKERNELAPI BOOLEAN ExAcquireSharedStarveExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
NTKERNELAPI BOOLEAN ExAcquireSharedWaitForExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
FORCEINLINE KIRQL ExAcquireSpinLockExclusive (IN PEX_SPIN_LOCK SpinLock)
FORCEINLINE KIRQL ExAcquireSpinLockShared (IN PEX_SPIN_LOCK SpinLock)
BOOLEAN ExAcquireTimeRefreshLock (IN BOOLEAN Wait)
VOID ExAdjustLookasideDepth (VOID)
NTKERNELAPI PEX_PUSH_LOCK_CACHE_AWARE ExAllocateCacheAwarePushLock (VOID)
NTKERNELAPI PEX_RUNDOWN_REF_CACHE_AWARE ExAllocateCacheAwareRundownProtection (__in POOL_TYPE PoolType, __in ULONG PoolTag)
PEX_CALLBACK_ROUTINE_BLOCK ExAllocateCallBack (IN PEX_CALLBACK_FUNCTION Function, IN PVOID Context)
__inline PVOID ExAllocateFromNPagedLookasideList (IN PNPAGED_LOOKASIDE_LIST Lookaside)
__inline PVOID ExAllocateFromPagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside)
FORCEINLINE PVOID ExAllocateFromPPLookasideList (IN PP_NPAGED_LOOKASIDE_NUMBER Number)
__inline VOID ExAllocateLocallyUniqueId (IN OUT PLUID Luid)
VOID ExAllocatePoolSanityChecks (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes)
NTKERNELAPI VOID FASTCALL ExBlockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
NTSTATUS ExCallCallBack (IN OUT PEX_CALLBACK CallBack, IN PVOID Argument1, IN PVOID Argument2)
NTKERNELAPI BOOLEAN ExChangeHandle (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PEX_CHANGE_HANDLE_ROUTINE ChangeRoutine, __in ULONG_PTR Parameter)
BOOLEAN ExCompareExchangeCallBack (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK NewBlock, IN PEX_CALLBACK_ROUTINE_BLOCK OldBlock)
ULONG ExComputeTickCountMultiplier (IN ULONG TimeIncrement)
NTKERNELAPI VOID ExConvertExclusiveToSharedLite (__inout PERESOURCE Resource)
VOID FORCEINLINE ExConvertPushLockExclusiveToShared (IN PEX_PUSH_LOCK PushLock)
NTKERNELAPI NTSTATUS ExCreateCallback (__deref_out PCALLBACK_OBJECT *CallbackObject, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN Create, __in BOOLEAN AllowMultipleCallbacks)
NTKERNELAPI PEX_DEBUG_LOG ExCreateDebugLog (__in UCHAR MaximumNumberOfTags, __in ULONG MaximumNumberOfEvents)
NTKERNELAPI UCHAR ExCreateDebugLogTag (__in PEX_DEBUG_LOG Log, __in PCHAR Name, __in UCHAR Format1, __in UCHAR Format2, __in UCHAR Format3, __in UCHAR Format4)
NTKERNELAPI HANDLE ExCreateHandle (__inout PHANDLE_TABLE HandleTable, __in PHANDLE_TABLE_ENTRY HandleTableEntry)
NTKERNELAPI PHANDLE_TABLE ExCreateHandleTable (__in_opt struct _EPROCESS *Process)
NTKERNELAPI VOID ExDebugLogEvent (__in PEX_DEBUG_LOG Log, __in UCHAR Tag, __in ULONG Data1, __in ULONG Data2, __in ULONG Data3, __in ULONG Data4)
NTKERNELAPI VOID ExDeleteNPagedLookasideList (__inout PNPAGED_LOOKASIDE_LIST Lookaside)
NTKERNELAPI VOID ExDeletePagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside)
NTKERNELAPI NTSTATUS ExDeleteResourceLite (__inout PERESOURCE Resource)
VOID ExDereferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
VOID ExDereferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable, IN PHANDLE_TRACE_DEBUG_INFO DebugInfo)
NTKERNELAPI BOOLEAN ExDestroyHandle (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __inout_opt PHANDLE_TABLE_ENTRY HandleTableEntry)
NTKERNELAPI VOID ExDestroyHandleTable (__inout PHANDLE_TABLE HandleTable, __in EX_DESTROY_HANDLE_ROUTINE DestroyHandleProcedure)
NTKERNELAPI NTSTATUS ExDisableHandleTracing (__inout PHANDLE_TABLE HandleTable)
NTKERNELAPI VOID ExDisableResourceBoostLite (__in PERESOURCE Resource)
NTKERNELAPI PHANDLE_TABLE ExDupHandleTable (__inout_opt struct _EPROCESS *Process, __in PHANDLE_TABLE OldHandleTable, __in EX_DUPLICATE_HANDLE_ROUTINE DupHandleProcedure OPTIONAL, __in ULONG_PTR Mask)
NTKERNELAPI NTSTATUS ExEnableHandleTracing (__inout PHANDLE_TABLE HandleTable, __in ULONG Slots)
NTKERNELAPI PVOID ExEnterCriticalRegionAndAcquireResourceExclusive (__inout PERESOURCE Resource)
NTKERNELAPI PVOID ExEnterCriticalRegionAndAcquireResourceShared (__inout PERESOURCE Resource)
NTKERNELAPI PVOID ExEnterCriticalRegionAndAcquireSharedWaitForExclusive (__inout PERESOURCE Resource)
NTKERNELAPI BOOLEAN ExEnumHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter, __out_opt PHANDLE Handle)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS ExExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize)
NTKERNELAPI VOID FASTCALL ExfAcquirePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN FASTCALL ExfAcquireRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefAddAdditionalReferenceCounts (__inout PEX_FAST_REF FastRef, __in PVOID Object, __in ULONG RefsToAdd)
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefCanBeDereferenced (__in EX_FAST_REF FastRef)
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefCanBeReferenced (__in EX_FAST_REF FastRef)
NTKERNELAPI EX_FAST_REF FORCEINLINE ExFastRefCompareSwapObject (__inout PEX_FAST_REF FastRef, __in_opt PVOID Object, __in PVOID OldObject)
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefDereference (__inout PEX_FAST_REF FastRef, __in PVOID Object)
NTKERNELAPI BOOLEAN FORCEINLINE ExFastRefEqualObjects (__in EX_FAST_REF FastRef, __in PVOID Object)
NTKERNELAPI EX_FAST_REF FORCEINLINE ExFastReference (__inout PEX_FAST_REF FastRef)
NTKERNELAPI ULONG FORCEINLINE ExFastRefGetAdditionalReferenceCount (VOID)
NTKERNELAPI PVOID FORCEINLINE ExFastRefGetObject (__in EX_FAST_REF FastRef)
NTKERNELAPI ULONG FORCEINLINE ExFastRefGetUnusedReferences (__in EX_FAST_REF FastRef)
NTKERNELAPI VOID FORCEINLINE ExFastRefInitialize (__out PEX_FAST_REF FastRef, __in_opt PVOID Object)
NTKERNELAPI VOID FORCEINLINE ExFastRefInitializeEx (__out PEX_FAST_REF FastRef, __in_opt PVOID Object, __in ULONG AdditionalRefs)
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefIsLastReference (__in EX_FAST_REF FastRef)
NTKERNELAPI BOOLEAN FORCEINLINE ExFastRefObjectNull (__in EX_FAST_REF FastRef)
NTKERNELAPI EX_FAST_REF FORCEINLINE ExFastRefSwapObject (__inout PEX_FAST_REF FastRef, __in_opt PVOID Object)
NTKERNELAPI VOID FASTCALL ExfConvertPushLockExclusiveToShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID ExFreeCacheAwarePushLock (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
NTKERNELAPI VOID ExFreeCacheAwareRundownProtection (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
VOID ExFreeCallBack (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
NTKERNELAPI VOID NTAPI ExFreePool (__in PVOID P)
VOID ExFreePoolSanityChecks (IN PVOID P)
NTKERNELAPI VOID ExFreePoolWithTag (__in PVOID P, __in ULONG Tag)
__inline VOID ExFreeToNPagedLookasideList (IN PNPAGED_LOOKASIDE_LIST Lookaside, IN PVOID Entry)
__inline VOID ExFreeToPagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside, __in PVOID Entry)
FORCEINLINE VOID ExFreeToPPLookasideList (IN PP_NPAGED_LOOKASIDE_NUMBER Number, IN PVOID Entry)
NTKERNELAPI VOID FASTCALL ExfReInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExfReleasePushLock (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfReleasePushLockShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfReleaseRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExfRundownCompleted (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI BOOLEAN FASTCALL ExfTryAcquirePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN FASTCALL ExfTryAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfTryToWakePushLock (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout_opt PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
NTKERNELAPI VOID FASTCALL ExfWaitForRundownProtectionRelease (__inout PEX_RUNDOWN_REF RunRef)
PVOID ExGetCallBackBlockContext (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
PEX_CALLBACK_FUNCTION ExGetCallBackBlockRoutine (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
NTKERNELAPI VOID ExGetCurrentProcessorCounts (__out PULONG IdleCount, __out PULONG KernelAndUser, __out PULONG Index)
NTKERNELAPI VOID ExGetCurrentProcessorCpuUsage (__out PULONG CpuUsage)
NTKERNELAPI ULONG ExGetExclusiveWaiterCount (__in PERESOURCE Resource)
VOID ExGetNextWakeTime (OUT PULONGLONG DueTime, OUT PTIME_FIELDS TimeFields, OUT PVOID *TimerObject)
NTKERNELAPI KPROCESSOR_MODE ExGetPreviousMode (VOID)
NTKERNELAPI ULONG ExGetSharedWaiterCount (__in PERESOURCE Resource)
VOID ExInitializeCallBack (IN OUT PEX_CALLBACK CallBack)
VOID ExInitializeCallData (IN PCALL_PERFORMANCE_DATA CallData)
NTKERNELAPI VOID ExInitializeHandleTablePackage (VOID)
PVOID ExInitializeNBQueueHead (IN PSLIST_HEADER SlistHead)
NTKERNELAPI VOID ExInitializeNPagedLookasideList (__out PNPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
NTKERNELAPI VOID ExInitializePagedLookasideList (__out PPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
VOID FORCEINLINE ExInitializePushLock (__out PEX_PUSH_LOCK PushLock)
NTKERNELAPI NTSTATUS ExInitializeResourceLite (__out PERESOURCE Resource)
NTKERNELAPI VOID FASTCALL ExInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID ExInitializeRundownProtectionCacheAware (__out PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in SIZE_T RunRefSize)
VOID ExInitializeSystemLookasideList (IN PGENERAL_LOOKASIDE Lookaside, IN POOL_TYPE Type, IN ULONG Size, IN ULONG Tag, IN USHORT Depth, IN PLIST_ENTRY ListHead)
NTKERNELAPI VOID ExInitializeTimeRefresh (VOID)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS ExInitializeZone (__out PZONE_HEADER Zone, __in ULONG BlockSize, __inout PVOID InitialSegment, __in ULONG InitialSegmentSize)
VOID ExInitPoolLookasidePointers (VOID)
NTKERNELAPI BOOLEAN ExInitSystem (VOID)
VOID ExInitSystemPhase2 (VOID)
VOID ExInsertPoolTag (ULONG Tag, PVOID Va, SIZE_T NumberOfBytes, POOL_TYPE PoolType)
BOOLEAN ExInsertTailNBQueue (IN PVOID Header, IN ULONG64 Value)
NTKERNELAPI LARGE_INTEGER ExInterlockedAddLargeInteger (__inout PLARGE_INTEGER Addend, __in LARGE_INTEGER Increment, __inout PKSPIN_LOCK Lock)
NTKERNELAPI ULONG FASTCALL ExInterlockedAddUlong (__inout PULONG Addend, __in ULONG Increment, __inout PKSPIN_LOCK Lock)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS ExInterlockedExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PSLIST_ENTRY FASTCALL ExInterlockedFlushSList (__inout PSLIST_HEADER ListHead)
NTKERNELAPI PLIST_ENTRY FASTCALL ExInterlockedInsertHeadList (__inout PLIST_ENTRY ListHead, __inout PLIST_ENTRY ListEntry, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PLIST_ENTRY FASTCALL ExInterlockedInsertTailList (__inout PLIST_ENTRY ListHead, __inout PLIST_ENTRY ListEntry, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PSINGLE_LIST_ENTRY FASTCALL ExInterlockedPopEntryList (__inout PSINGLE_LIST_ENTRY ListHead, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PSINGLE_LIST_ENTRY FASTCALL ExInterlockedPushEntryList (__inout PSINGLE_LIST_ENTRY ListHead, __inout PSINGLE_LIST_ENTRY ListEntry, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PLIST_ENTRY FASTCALL ExInterlockedRemoveHeadList (__inout PLIST_ENTRY ListHead, __inout PKSPIN_LOCK Lock)
NTKERNELAPI BOOLEAN ExIsProcessorFeaturePresent (__in ULONG ProcessorFeature)
NTKERNELAPI BOOLEAN ExIsResourceAcquiredExclusiveLite (__in PERESOURCE Resource)
NTKERNELAPI ULONG ExIsResourceAcquiredSharedLite (__in PERESOURCE Resource)
NTKERNELAPI VOID ExLocalTimeToSystemTime (__in PLARGE_INTEGER LocalTime, __out PLARGE_INTEGER SystemTime)
NTKERNELAPI KIRQL ExLockPool (__in POOL_TYPE PoolType)
NTKERNELAPI NTSTATUS ExLockUserBuffer (__inout_bcount(Length) PVOID Buffer, __in ULONG Length, __in KPROCESSOR_MODE ProbeMode, __in LOCK_OPERATION LockMode, __deref_out PVOID *LockedBuffer, __deref_out PVOID *LockVariable)
NTKERNELAPI BOOLEAN ExLuidInitialization (VOID)
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointer (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle)
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointerEx (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
NTKERNELAPI VOID ExNotifyCallback (__in PVOID CallbackObject, __in_opt PVOID Argument1, __in_opt PVOID Argument2)
NTKERNELAPI PHANDLE_TABLE_ENTRY_INFO ExpGetHandleInfo (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in BOOLEAN EntryLocked)
NTKERNELAPI SIZE_T ExQueryPoolBlockSize (__in PVOID PoolBlock, __out PBOOLEAN QuotaCharged)
NTKERNELAPI VOID ExQueryPoolUsage (__out PULONG PagedPoolPages, __out PULONG NonPagedPoolPages, __out PULONG PagedPoolAllocs, __out PULONG PagedPoolFrees, __out PULONG PagedPoolLookasideHits, __out PULONG NonPagedPoolAllocs, __out PULONG NonPagedPoolFrees, __out PULONG NonPagedPoolLookasideHits)
NTKERNELAPI NTSTATUS ExQuerySystemLockInformation (__out_bcount(LockInformationLength) struct _RTL_PROCESS_LOCKS *LockInformation, __in ULONG LockInformationLength, __out_opt PULONG ReturnLength)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI VOID ExQueueWorkItem (__inout PWORK_QUEUE_ITEM WorkItem, __in WORK_QUEUE_TYPE QueueType)
NTKERNELAPI DECLSPEC_NORETURN VOID ExRaiseAccessViolation (VOID)
NTKERNELAPI DECLSPEC_NORETURN VOID ExRaiseDatatypeMisalignment (VOID)
NTKERNELAPI VOID NTAPI ExRaiseException (__in PEXCEPTION_RECORD ExceptionRecord)
NTKERNELAPI NTSTATUS ExRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
NTKERNELAPI DECLSPEC_NORETURN VOID NTAPI ExRaiseStatus (__in NTSTATUS Status)
VOID ExRecordCallerInHashTable (IN PCALL_PERFORMANCE_DATA CallData, IN PVOID CallersAddress, IN PVOID CallersCaller)
PEX_CALLBACK_ROUTINE_BLOCK ExReferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack)
PHANDLE_TRACE_DEBUG_INFO ExReferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable)
NTKERNELAPI PVOID ExRegisterCallback (__inout PCALLBACK_OBJECT CallbackObject, __in PCALLBACK_FUNCTION CallbackFunction, __in_opt PVOID CallbackContext)
NTKERNELAPI NTSTATUS ExReinitializeResourceLite (__inout PERESOURCE Resource)
NTKERNELAPI VOID FASTCALL ExReInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExReInitializeRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI VOID ExReleaseCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE CacheAwarePushLock)
VOID FORCEINLINE ExReleaseCacheAwarePushLockShared (IN PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExReleaseFastMutex (__inout PFAST_MUTEX FastMutex)
VOID FORCEINLINE ExReleasePushLock (IN PEX_PUSH_LOCK PushLock)
VOID FORCEINLINE ExReleasePushLockExclusive (IN PEX_PUSH_LOCK PushLock)
VOID FORCEINLINE ExReleasePushLockShared (IN PEX_PUSH_LOCK PushLock)
VOID FORCEINLINE ExReleasePushLockSharedAssumeSingleOwner (IN PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExReleaseResourceAndLeaveCriticalRegion (__inout PERESOURCE Resource)
NTKERNELAPI VOID ExReleaseResourceForThreadLite (__inout PERESOURCE Resource, __in ERESOURCE_THREAD ResourceThreadId)
NTKERNELAPI VOID FASTCALL ExReleaseResourceLite (__inout PERESOURCE Resource)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRef, __in ULONG Count)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
FORCEINLINE VOID ExReleaseSpinLockExclusive (IN PEX_SPIN_LOCK SpinLock, IN KIRQL OldIrql)
FORCEINLINE VOID ExReleaseSpinLockShared (IN PEX_SPIN_LOCK SpinLock, IN KIRQL OldIrql)
VOID ExReleaseTimeRefreshLock (VOID)
NTKERNELAPI VOID ExRemoveHandleTable (__inout PHANDLE_TABLE HandleTable)
BOOLEAN ExRemoveHeadNBQueue (IN PVOID Header, OUT PULONG64 Value)
VOID ExReturnPoolQuota (IN PVOID P)
NTKERNELAPI VOID FASTCALL ExRundownCompleted (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExRundownCompletedCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI NTSTATUS ExSetHandleInfo (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PHANDLE_TABLE_ENTRY_INFO EntryInfo, __in BOOLEAN EntryLocked)
VOID ExSetHandleTableStrictFIFO (IN PHANDLE_TABLE HandleTable)
NTKERNELAPI VOID ExSetResourceOwnerPointer (__inout PERESOURCE Resource, __in PVOID OwnerPointer)
NTKERNELAPI ULONG ExSetTimerResolution (__in ULONG DesiredTime, __in BOOLEAN SetResolution)
VOID ExShutdownSystem (IN ULONG Phase)
NTKERNELAPI SIZE_T ExSizeOfRundownProtectionCacheAware (VOID)
NTKERNELAPI NTSTATUS ExSnapShotHandleTables (__in PEX_SNAPSHOT_HANDLE_ENTRY SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
NTKERNELAPI NTSTATUS ExSnapShotHandleTablesEx (__in PEX_SNAPSHOT_HANDLE_ENTRY_EX SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION_EX HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
VOID ExSwapinWorkerThreads (IN BOOLEAN AllowSwap)
NTKERNELAPI VOID ExSweepHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter)
int ExSystemExceptionFilter (VOID)
NTKERNELAPI VOID ExSystemTimeToLocalTime (__in PLARGE_INTEGER SystemTime, __out PLARGE_INTEGER LocalTime)
NTKERNELAPI NTSTATUS FASTCALL ExTimedWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock, __in_opt PLARGE_INTEGER Timeout)
NTKERNELAPI VOID ExTimerRundown (VOID)
BOOLEAN FORCEINLINE ExTryAcquirePushLockExclusive (IN PEX_PUSH_LOCK PushLock)
BOOLEAN FORCEINLINE ExTryAcquirePushLockShared (IN PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN FORCEINLINE ExTryAcquireReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
FORCEINLINE LOGICAL ExTryAcquireSpinLockExclusive (IN PEX_SPIN_LOCK SpinLock)
BOOLEAN FORCEINLINE ExTryConvertPushLockSharedToExclusive (IN PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN FASTCALL ExTryToAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
NTKERNELAPI BOOLEAN ExTryToAcquireResourceExclusiveLite (__inout PERESOURCE Resource)
VOID FORCEINLINE ExUnblockPushLock (IN PEX_PUSH_LOCK PushLock, IN PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock OPTIONAL)
NTKERNELAPI VOID ExUnlockHandleTableEntry (__inout PHANDLE_TABLE HandleTable, __inout PHANDLE_TABLE_ENTRY HandleTableEntry)
NTKERNELAPI VOID ExUnlockPool (__in POOL_TYPE PoolType, __in KIRQL LockHandle)
NTKERNELAPI VOID ExUnlockUserBuffer (__inout PVOID LockVariable)
NTKERNELAPI VOID ExUnregisterCallback (__inout PVOID CallbackRegistration)
VOID ExUpdateSystemTimeFromCmos (IN BOOLEAN UpdateInterruptTime, IN ULONG MaxSepInSeconds)
NTKERNELAPI NTSTATUS ExUuidCreate (__out UUID *Uuid)
NTKERNELAPI BOOLEAN ExVerifySuite (__in SUITE_TYPE SuiteType)
VOID ExWaitForCallBacks (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
NTKERNELAPI VOID FASTCALL ExWaitForRundownProtectionRelease (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExWaitForRundownProtectionReleaseCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRef)
NTKERNELAPI VOID FASTCALL ExWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
PSLIST_ENTRY FirstEntrySList (IN const SLIST_HEADER *SListHead)
VOID InitializePool (IN POOL_TYPE PoolType, IN ULONG Threshold)
__inline VOID InitializeSListHead (__out PSLIST_HEADER SListHead)
NTKERNELAPI PSLIST_ENTRY FASTCALL InterlockedPopEntrySList (__inout PSLIST_HEADER ListHead)
NTKERNELAPI PSLIST_ENTRY FASTCALL InterlockedPushEntrySList (__inout PSLIST_HEADER ListHead, __inout PSLIST_ENTRY ListEntry)
PSLIST_ENTRY FASTCALL InterlockedPushListSList (IN PSLIST_HEADER ListHead, IN PSLIST_ENTRY List, IN PSLIST_ENTRY ListEnd, IN ULONG Count)
VOID FASTCALL KiAcquireFastMutex (IN PFAST_MUTEX Mutex)
NTKERNELAPI VOID NTAPI ProbeForWrite (__inout_bcount(Length) PVOID Address, __in SIZE_T Length, __in ULONG Alignment)
FORCEINLINE VOID ProbeForWriteSmallStructure (IN PVOID Address, IN SIZE_T Size, IN ULONG Alignment)
FORCEINLINE VOID ProbeForWriteUlongAligned32 (IN PULONG Address)
FORCEINLINE VOID xxAcquireFastMutex (IN PFAST_MUTEX FastMutex)
FORCEINLINE VOID xxAcquireFastMutexUnsafe (IN PFAST_MUTEX FastMutex)
FORCEINLINE VOID xxReleaseFastMutex (IN PFAST_MUTEX FastMutex)
FORCEINLINE VOID xxReleaseFastMutexUnsafe (IN PFAST_MUTEX FastMutex)
FORCEINLINE BOOLEAN xxTryToAcquireFastMutex (IN PFAST_MUTEX FastMutex)
Variables
ULONG EvPrSetHigh
ULONG EvPrSetLow
PCALLBACK_OBJECT ExCbPowerState
PCALLBACK_OBJECT ExCbSetSystemState
PCALLBACK_OBJECT ExCbSetSystemTime
BOOLEAN ExCmosClockIsSane
ULONG ExCriticalWorkerThreads
ULONG ExDelayedWorkerThreads
PKWIN32_GLOBALATOMTABLE_CALLOUT ExGlobalAtomTableCallout
volatile LONG ExHotpSyncRenameSequence
PVOID ExPageLockHandle
LONG ExpAltTimeZoneBias
ULONG ExpCurrentTimeZoneId
LONG ExpLastTimeZoneBias
LARGE_INTEGER ExpLuid
const LARGE_INTEGER ExpLuidIncrement
ULONG ExpRealTimeIsUniversal
ULONG ExpTickCountMultiplier
LARGE_INTEGER ExpTimeZoneBias
BOOLEAN ExReadyForErrors
PKTHREAD ExSyncRenameOwner
LIST_ENTRY ExSystemLookasideListHead
EX_WORK_QUEUE ExWorkerQueue []
DECLSPEC_DEPRECATED_DDK NTKERNELAPI __in SIZE_T NumberOfBytes
NTKERNELAPI __in SIZE_T __in ULONG __in EX_POOL_PRIORITY Priority
NTKERNELAPI __in SIZE_T __in ULONG Tag
Macro Definition Documentation
#define CALL_HASH_TABLE_SIZE 64
Definition at line 26 of file ex.h.
Referenced by ExInitializeCallData(), and ExRecordCallerInHashTable().
#define EX_CACHE_LINE_SIZE 128
Definition at line 4877 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_HANDLE (UCHAR)7
Definition at line 5768 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_NONE (UCHAR)0
Definition at line 5761 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_OBJECT (UCHAR)6
Definition at line 5767 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_PSZ (UCHAR)2
Definition at line 5763 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_PWSZ (UCHAR)3
Definition at line 5764 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_STRING (UCHAR)4
Definition at line 5765 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_ULONG (UCHAR)1
Definition at line 5762 of file ex.h.
#define EX_DEBUG_LOG_FORMAT_USTRING (UCHAR)5
Definition at line 5766 of file ex.h.
#define EX_DEBUG_LOG_NUMBER_OF_BACK_TRACES 4
Definition at line 5771 of file ex.h.
#define EX_DEBUG_LOG_NUMBER_OF_DATA_VALUES 4
Definition at line 5770 of file ex.h.
#define EX_PUSH_LOCK_FANNED_COUNT (PAGE_SIZE/EX_CACHE_LINE_SIZE)
Definition at line 4878 of file ex.h.
Referenced by ExAcquireCacheAwarePushLockExclusive(), ExAcquireCacheAwarePushLockShared(), ExAllocateCacheAwarePushLock(), ExFreeCacheAwarePushLock(), and ExReleaseCacheAwarePushLockExclusive().
#define EX_PUSH_LOCK_FLAGS_EXCLUSIVE (0x1)
Referenced by ExfAcquirePushLockExclusive(), ExfReleasePushLock(), ExfReleasePushLockShared(), and ExfWakePushLock().
#define EX_PUSH_LOCK_FLAGS_SPINNING (0x2)
Referenced by ExBlockPushLock(), ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfUnblockPushLock(), and ExTimedWaitForUnblockPushLock().
#define EX_PUSH_LOCK_FLAGS_SPINNING_V (0x1)
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfUnblockPushLock(), ExfWakePushLock(), and ExTimedWaitForUnblockPushLock().
#define EX_PUSH_LOCK_LOCK ((ULONG_PTR)0x1)
Definition at line 4833 of file ex.h.
Referenced by ExAcquirePushLockShared(), ExAcquirePushLockSharedAssumeNoOwner(), ExConvertPushLockExclusiveToShared(), ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfConvertPushLockExclusiveToShared(), ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExfTryAcquirePushLockShared(), ExReleasePushLockExclusive(), ExReleasePushLockShared(), ExReleasePushLockSharedAssumeSingleOwner(), ExTryAcquirePushLockShared(), and ExTryConvertPushLockSharedToExclusive().
#define EX_PUSH_LOCK_LOCK_V ((ULONG_PTR)0x0)
Definition at line 4832 of file ex.h.
Referenced by ExAcquirePushLockExclusive(), and ExTryAcquirePushLockExclusive().
#define EX_PUSH_LOCK_MULTIPLE_SHARED ((ULONG_PTR)0x8)
Definition at line 4852 of file ex.h.
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfReleasePushLock(), and ExfReleasePushLockShared().
#define EX_PUSH_LOCK_PTR_BITS ((ULONG_PTR)0xf)
Definition at line 4858 of file ex.h.
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfReleasePushLock(), ExfReleasePushLockShared(), ExfWakePushLock(), and ExpOptimizePushLockList().
#define EX_PUSH_LOCK_SHARE_INC ((ULONG_PTR)0x10)
Definition at line 4857 of file ex.h.
Referenced by ExAcquirePushLockShared(), ExAcquirePushLockSharedAssumeNoOwner(), ExConvertPushLockExclusiveToShared(), ExfAcquirePushLockShared(), ExfConvertPushLockExclusiveToShared(), ExfReleasePushLock(), ExfReleasePushLockShared(), ExfTryAcquirePushLockShared(), ExReleasePushLock(), ExReleasePushLockShared(), ExReleasePushLockSharedAssumeSingleOwner(), ExTryAcquirePushLockShared(), and ExTryConvertPushLockSharedToExclusive().
#define EX_PUSH_LOCK_WAITING ((ULONG_PTR)0x2)
Definition at line 4839 of file ex.h.
Referenced by ExfAcquirePushLockExclusive(), and ExfAcquirePushLockShared().
#define EX_PUSH_LOCK_WAKING ((ULONG_PTR)0x4)
Definition at line 4846 of file ex.h.
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExfTryToWakePushLock(), ExfWakePushLock(), and ExpOptimizePushLockList().
#define EX_RUNDOWN_ACTIVE 0x1
Definition at line 4906 of file ex.h.
Referenced by ExAcquireRundownProtection(), ExAcquireRundownProtectionEx(), ExfAcquireRundownProtection(), ExfReInitializeRundownProtection(), ExfReleaseRundownProtection(), ExfRundownCompleted(), ExfWaitForRundownProtectionRelease(), ExReInitializeRundownProtection(), ExReInitializeRundownProtectionCacheAware(), ExReleaseRundownProtection(), ExReleaseRundownProtectionEx(), ExRundownCompleted(), ExRundownCompletedCacheAware(), ExWaitForRundownProtectionRelease(), and ExWaitForRundownProtectionReleaseCacheAware().
#define EX_RUNDOWN_COUNT_INC (1<<EX_RUNDOWN_COUNT_SHIFT)
Definition at line 4908 of file ex.h.
Referenced by ExAcquireRundownProtection(), ExAcquireRundownProtectionEx(), ExfAcquireRundownProtection(), ExfReleaseRundownProtection(), ExReleaseRundownProtection(), and ExReleaseRundownProtectionEx().
#define EX_RUNDOWN_COUNT_SHIFT 0x1
Definition at line 4907 of file ex.h.
Referenced by ExfWaitForRundownProtectionRelease(), and ExWaitForRundownProtectionReleaseCacheAware().
#define EX_WORKER_QUEUE_DISABLED 0x80000000
Definition at line 4222 of file ex.h.
Referenced by ExpShutdownWorkerThreads().
#define ExAcquireFastMutexUnsafe (FastMutex) xxAcquireFastMutexUnsafe(FastMutex)
Definition at line 1084 of file ex.h.
#define ExAcquireResourceExclusive ExAcquireResourceExclusiveLite
Definition at line 4800 of file ex.h.
#define ExAcquireResourceShared ExAcquireResourceSharedLite
Definition at line 4799 of file ex.h.
#define ExAllocateFromZone (Zone)
Value:
(PVOID)((Zone)->FreeList.Next); \
    if ( (Zone)->FreeList.Next ) (Zone)->FreeList.Next = (Zone)->FreeList.Next->Next
Definition at line 4357 of file ex.h.
#define ExAllocatePoolWithQuotaTag (a, b, c) ExAllocatePoolWithQuota(a,b)
Definition at line 271 of file ex.h.
Referenced by CmpNotifyChangeKey(), DbgkpQueueMessage(), ExLockUserBuffer(), ExpGetSystemFirmwareTableInformation(), IopAllocateIrpPrivate(), IopCreateFile(), IoSetIoCompletion(), NtCreateJobSet(), NtQueryDirectoryObject(), NtQueueApcThread(), NtRegisterThreadTerminatePort(), NtSetValueKey(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), PspSetLdtInformation(), and PsSetProcessLdtInfo().
#define ExAllocatePoolWithTag (a, b, c) ExAllocatePool(a,b)
Definition at line 258 of file ex.h.
Referenced by __bcount(), CcAllocateInitializeBcb(), CcAllocateObcb(), CcCreateVacbArray(), CcDeferWrite(), CcExtendVacbArray(), CcFindBitmapRangeToDirty(), CcInitializeCacheManager(), CcInitializeCacheMap(), CcInitializeVacbs(), CcPrefillVacbLevelZone(), CcZeroData(), CmInitSystem1(), CmpAcquireFileObjectForFile(), CmpAddInfoAfterParseFailure(), CmpAllocate(), CmpAllocateCmView(), CmpAllocateDelayItem(), CmpAllocateKeyControlBlock(), CmpConstructName(), CmpDoAccessCheckOnSubtree(), CmpGetNameControlBlock(), CmpGetValueData(), CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpInitHiveFromFile(), CmpInitializeCache(), CmpInitializeHive(), CmpPrefetchHiveFile(), CmRegisterCallback(), ExAllocateCacheAwarePushLock(), ExAllocateCacheAwareRundownProtection(), ExAllocateCallBack(), ExEnableHandleTracing(), ExGetPoolTagInfo(), ExInitializeNBQueueHead(), ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), ExInitializeSystemLookasideList(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateHandleTable(), ExpAllocateSharedWaiterSemaphore(), ExpAllocateStringRoutine(), ExpAllocateTablePagedPool(), ExpAllocateTablePagedPoolNoZero(), ExpExpandResourceOwnerTable(), ExpInitializeExecutive(), ExpInitSystemPhase1(), ExpKeyedEventInitialization(), ExpRegisterFirmwareTableInformationHandler(), ExpSystemErrorHandler(), ExRecordCallerInHashTable(), ExRegisterCallback(), FsFilterAllocateCompletionStack(), FsFilterInit(), FsRtlAddToTunnelCache(), FsRtlGetCompatibilityModeValue(), FsRtlGetTunnelParameterValue(), FsRtlInsertPerFileObjectContext(), FsRtlpPostStackOverflow(), FsRtlpRegisterProviderWithMUP(), FsRtlRegisterFileSystemFilterCallbacks(), FsRtlRegisterUncProvider(), HalExamineMBR(), HalpDeleteMountLetter(), HalpGetFullGeometry(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpSetMountLetter(), HvpAddBin(), HvpRecoverData(), HvpWriteLog(), HvRefreshHive(), HvWriteHive(), InitializePool(), IoAllocateDriverObjectExtension(), IoAllocateMdl(), IoAssignDriveLetters(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoConnectInterrupt(), IoInitializeTimer(), IoInitSystem(), IoIsValidNameGraftingBuffer(), IoMakeAssociatedIrp(), IopAllocateErrorLogEntry(), IopAllocateIrpPrivate(), IopComputeHarddiskDerangements(), IopCreateDefaultDeviceSecurityDescriptor(), IopCreateFile(), IopCreateVpb(), IopDeleteSessionSymLinks(), IopDoNameTransmogrify(), IopParseDevice(), IopQueryNameInternal(), IoQueryFileDosDeviceName(), IoRaiseHardError(), IoRaiseInformationalHardError(), IoReadPartitionTable(), IoRegisterBootDriverReinitialization(), IoRegisterDriverReinitialization(), IoRegisterFsRegistrationChange(), IoRegisterLastChanceShutdownNotification(), IoRegisterShutdownNotification(), IoSetCompletionRoutineEx(), IoSetPartitionInformation(), IoWMIAllocateInstanceIds(), IoWMISuggestInstanceName(), IoWMIWriteEvent(), IoWritePartitionTable(), Ke386CallBios(), KeI386GetLid(), KeRegisterNmiCallback(), KeSaveFloatingPointState(), KeStartAllProcessors(), KeStartProfile(), KiAddRange(), KiAllProcessorsStarted(), KiInitializeInterruptTimers(), KiInitializeKernel(), KiInitializeMTRR(), KiStartEffectiveRangeChange(), LpcpInitializePortQueue(), MiAddMdlTracker(), MiAddViewsForSection(), MiAllocateAweInfo(), MiAllocateContiguousMemory(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiAllocateVad(), MiBuildImportsForBootDrivers(), MiCloneProcessAddressSpace(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreateMemoryEvent(), MiCreatePagingFileMap(), MiCreatePebOrTeb(), MiCreatePhysicalVadRoot(), MiDoPoolCopy(), MiFlushSectionInternal(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiInitializeDriverLargePageList(), MiInitializeLoadedModuleList(), MiInitializeSystemPtes(), MiInitializeSystemSpaceMap(), MiInsertInSystemSpace(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiLoadUserSymbols(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiModifiedPageWriter(), MiPteSListExpansionWorker(), MiReferenceIoSpace(), MiRememberUnloadedDriver(), MiResolveImageReferences(), MiSectionInitialization(), MiSecureVirtualMemory(), MiSessionCreateInternal(), MiSessionInsertImage(), MiSessionWideInitializeAddresses(), MiSessionWideReserveImageAddress(), MiShutdownSystem(), MiSnapThunk(), MiStartZeroPageWorkers(), MiWriteComplete(), MiZeroAllPageFiles(), MmCallDllInitialize(), MmCreateMdl(), MmCreateSection(), MmExtendSection(), MmFreeLoaderBlock(), MmGetFileNameForAddress(), MmGetFileNameForSection(), MmInitializeHandBuiltProcess2(), MmInitializeMemoryLimits(), MmInitializeProcessAddressSpace(), MmInitSystem(), MmLoadSystemImage(), MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), MmProbeAndLockSelectedPages(), MmProtectMdlSystemAddress(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtCloseObjectAuditAlarm(), NtCreatePagingFile(), NtCreateSymbolicLinkObject(), NtDeleteObjectAuditAlarm(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtSetInformationFile(), NtSetInformationProcess(), NtSetSystemInformation(), NtStartProfile(), ObCreateObjectType(), ObGetObjectInformation(), ObGetObjectSecurity(), ObInitSystem(), ObOpenObjectByName(), ObpAllocateObject(), ObpAllocateObjectNameBuffer(), ObpCreateCacheEntry(), ObpCreateTypeArray(), ObpInsertDirectoryEntry(), ObpInsertHandleCount(), ObpLookupObjectName(), ObpParseSymbolicLink(), ObpWaitForMultipleObjects(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), PerfInfoFileNameRunDown(), PerfInfoProcessRunDown(), PerfInfoSysModuleRunDown(), Phase1InitializationDiscard(), PsImpersonateClient(), PspApplyJobLimitsToProcessSet(), PspCaptureTokenFilter(), PspCreateLdt(), PspCreateProcess(), PspInitPhase0(), PspSetLdtInformation(), PspSetQuotaLimits(), PspTerminateThreadByPointer(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawInitializeVcb(), RtlInitializeExceptionLog(), RtlpAllocateAtom(), RtlpAllocDeallocQueryBuffer(), RtlpComputeMergedAcl(), RtlpConvertAclToAutoInherit(), RtlpConvertToAutoInheritSecurityObject(), RtlpCreateServerAcl(), RtlpInheritAcl(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), RtlpSysVolAllocate(), RtlpTraceDatabaseAllocate(), SeAccessCheckByType(), SeAppendPrivileges(), SeCaptureAcl(), SeCaptureAuditPolicy(), SeCaptureLuidAndAttributesArray(), SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SeInitializeProcessAuditName(), SeLocateProcessImageName(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepAccessCheckAndAuditAlarm(), SepAdtLogAuditRecord(), SepAdtMarshallAuditRecord(), SepAdtOpenObjectAuditAlarm(), SepAssemblePrivileges(), SepCleanupLUIDDeviceMapDirectory(), SepCopyProxyData(), SepCreateLogonSessionTrack(), SepCreateToken(), SepDuplicateToken(), SepExpandDynamic(), SepFilterToken(), SepInformFileSystemsOfDeletedLogon(), SepInformLsaOfDeletedLogon(), SepInitializePrivilegeSets(), SepInitProcessAuditSd(), SepInitSystemDacls(), SepProbeAndCaptureString_U(), SepQueryNameString(), SepQueryTypeString(), SePrivilegePolicyCheck(), SepRmDbInitialization(), SepVariableInitialization(), SeRegisterLogonSessionTerminatedRoutine(), SeRmInitPhase1(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipAllocEntry(), WmipAllocGuidEntryX(), WmipCreateAdminSD(), WmipCreateLogFile(), WmipCreateNtFileName(), WmipDelayCreate(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipFireOffWmiEvent(), WmipFlushBuffersWithMarker(), WmipGenerateFileName(), WmipGenerateMCAEventlog(), WmipGetLogFromHal(), WmipInitContext(), WmipInitializeSecurity(), WmipProcessPrevMcaLogs(), WmipQueueNotification(), WmipRegisterOrUpdateDS(), WmipSDRegistryQueryRoutine(), WmipSecurityMethod(), WmipStartLogger(), WmipSwitchToNewFile(), WmipTraceIo(), WmipTranslateFileHandle(), WmiUpdateTrace(), and xHalGetPartialGeometry().
#define ExConvertExclusiveToShared ExConvertExclusiveToSharedLite
Definition at line 4802 of file ex.h.
#define ExDeleteResource ExDeleteResourceLite
Definition at line 4803 of file ex.h.
#define ExDisableResourceBoost ExDisableResourceBoostLite
Definition at line 4809 of file ex.h.
Referenced by CcAllocateInitializeBcb().
#define ExFreePoolWithTag (a, b) ExFreePool(a)
Definition at line 306 of file ex.h.
Referenced by CmpAddInfoAfterParseFailure(), CmpAddSecurityCellToCache(), CmpAdjustSecurityCacheSize(), CmpCheckRegistry2(), CmpCleanUpKcbCacheWithLock(), CmpCleanUpSubKeyInfo(), CmpConstructName(), CmpDereferenceNameControlBlockWithLock(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDoAccessCheckOnSubtree(), CmpDropFileObjectForHive(), CmpDumpKeyBodyList(), CmpFindReusableCellFromCache(), CmpFreeCmView(), CmpFreeDelayItem(), CmpFreeKeyControlBlock(), CmpGetSymbolicLink(), CmpLoadHiveVolatile(), CmpQueryKeyName(), CmpRemoveFromSecurityCache(), CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), CmQueryKey(), CmRenameKey(), ExpGetSystemFirmwareTableInformation(), ExpRegisterFirmwareTableInformationHandler(), FsFilterFreeCompletionStack(), FsFilterInit(), HalpQueryDriveLayout(), KeDeregisterNmiCallback(), ObGetObjectInformation(), ObpDestroyTypeArray(), ObpFreeObject(), PsImpersonateClient(), PspDeleteThreadSecurity(), PspExitThread(), RtlpAllocateAtom(), RtlpTraceDatabaseFree(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipFreeEntry().
#define ExFreeToZone (Zone, Block)
Value:
(((PSINGLE_LIST_ENTRY)(Block))->Next = (Zone)->FreeList.Next,  \
      (Zone)->FreeList.Next = ((PSINGLE_LIST_ENTRY)(Block)),        \
      ((PSINGLE_LIST_ENTRY)(Block))->Next                           \
    )
Definition at line 4393 of file ex.h.
#define ExGetCurrentResourceThread () ((ULONG_PTR)PsGetCurrentThread())
Definition at line 4762 of file ex.h.
#define ExGetHandleInfo (HT, H, E) ((HT)->ExtraInfoPages ? ExpGetHandleInfo((HT),(H),(E)) : NULL)
Definition at line 5520 of file ex.h.
Referenced by ExDupHandleTable(), ExpFreeHandleTableEntry(), ObAuditObjectAccess(), ObpReferenceProcessObjectByHandle(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
#define ExInitializeFastMutex (_FastMutex)
Value:
(_FastMutex)->Count = FM_LOCK_BIT;                                       \
    (_FastMutex)->Owner = NULL;                                              \
    (_FastMutex)->Contention = 0;                                            \
    KeInitializeEvent(&(_FastMutex)->Gate,                                   \
                      SynchronizationEvent,                                  \
                      FALSE);
Definition at line 371 of file ex.h.
Referenced by DbgkInitialize(), ExEnableHandleTracing(), ExpInitSystemPhase0(), ExpUuidInitialization(), ExpWorkerInitialization(), FsRtlAllocateOplock(), FsRtlInitializeTunnelCache(), FsRtlInsertPerFileObjectContext(), FsRtlNotifyInitializeSync(), KiInitSystem(), NtCreateDebugObject(), RtlpTraceDatabaseInitializeLock(), and SepRmDbInitialization().
#define ExInitializeResource ExInitializeResourceLite
Definition at line 4798 of file ex.h.
#define ExInitializeSListHead InitializeSListHead
Definition at line 1407 of file ex.h.
Referenced by ExInitializeSystemLookasideList(), and ExInitPoolLookasidePointers().
#define ExInitializeWorkItem (Item, Routine, Context)
Value:
(Item)->WorkerRoutine = (Routine);               \
    (Item)->Parameter = (Context);                   \
    (Item)->List.Flink = NULL;
Definition at line 4181 of file ex.h.
Referenced by CcInitializeCacheManager(), CmpCanGrowSystemHive(), CmpCmdInit(), CmpDiskFullWarning(), CmpDoQueueLateUnloadWorker(), CmpInitDelayDerefKCBEngine(), CmpInitializeDelayedCloseTable(), CmpRaiseSelfHealWarning(), CmpUpdateSystemHiveHysteresis(), ExpShutdownWorkerThreads(), ExpWorkerThreadBalanceManager(), FsRtlpPostStackOverflow(), IoAllocateWorkItem(), IoInitSystem(), IopCompleteUnloadOrDelete(), IopErrorLogDpc(), IopSendMessageToTrackService(), IopUnloadDriver(), IoRaiseHardError(), IoWriteErrorLogEntry(), MiNoPagesLastChance(), MiReleaseSystemPtes(), MiStartZeroPageWorkers(), MiWriteComplete(), MiZeroAllPageFiles(), NtLoadDriver(), ObInitSystem(), PspInitializeJobStructures(), PspInitPhase0(), SepInformFileSystemsOfDeletedLogon(), SepQueueWorkItem(), WmipInitializeNotifications(), WmipInitializeRegistration(), WmipQueueNotification(), WmipRegisterMcaHandler(), WmipSetupWaitForWbem(), and WmipTraceIo().
#define ExInterlockedAddLargeStatistic (Addend, Increment) (VOID) _InterlockedAddLargeStatistic ((PLONGLONG)&(Addend)->QuadPart, Increment)
Definition at line 1200 of file ex.h.
Referenced by IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IopUpdateReadOperationCount(), IopUpdateReadTransferCount(), IopUpdateWriteOperationCount(), and IopUpdateWriteTransferCount().
#define ExInterlockedAllocateFromZone (Zone, Lock) (PVOID) ExInterlockedPopEntryList(&(Zone)->FreeList, Lock)
Definition at line 4459 of file ex.h.
#define ExInterlockedCompareExchange64 (Destination, Exchange, Comperand, Lock) ExfInterlockedCompareExchange64(Destination, Exchange, Comperand)
Definition at line 1248 of file ex.h.
#define ExInterlockedFreeToZone (Zone, Block, Lock) ExInterlockedPushEntryList(&(Zone)->FreeList, ((PSINGLE_LIST_ENTRY) (Block)), Lock)
Definition at line 4499 of file ex.h.
#define ExInterlockedPopEntrySList (ListHead, Lock) InterlockedPopEntrySList(ListHead)
Definition at line 1533 of file ex.h.
Referenced by ExAllocateFromNPagedLookasideList().
#define ExInterlockedPushEntrySList (ListHead, ListEntry, Lock) InterlockedPushEntrySList(ListHead, ListEntry)
Definition at line 1536 of file ex.h.
Referenced by ExFreeToNPagedLookasideList().
#define ExIsFastMutexOwned (_FastMutex) ((_FastMutex)->Count != 1)
Definition at line 1163 of file ex.h.
#define ExIsFullZone (Zone) ((Zone)->FreeList.Next == (PSINGLE_LIST_ENTRY)NULL)
Definition at line 4424 of file ex.h.
#define ExIsObjectInFirstZoneSegment (Zone, Object)
Value:
((BOOLEAN)     \
    (((PUCHAR)(Object) >= (PUCHAR)(Zone)->SegmentList.Next) &&   \
     ((PUCHAR)(Object) < (PUCHAR)(Zone)->SegmentList.Next +      \
                         (Zone)->TotalSegmentSize))              \
)
Definition at line 4531 of file ex.h.
#define ExIsResourceAcquired ExIsResourceAcquiredSharedLite
Definition at line 4806 of file ex.h.
#define ExIsResourceAcquiredExclusive ExIsResourceAcquiredExclusiveLite
Definition at line 4804 of file ex.h.
#define ExIsResourceAcquiredLite ExIsResourceAcquiredSharedLite
Definition at line 4780 of file ex.h.
#define ExIsResourceAcquiredShared ExIsResourceAcquiredSharedLite
Definition at line 4805 of file ex.h.
#define EXP_SPIN_LOCK_EXCLUSIVE 0x80000000
Definition at line 803 of file ex.h.
Referenced by ExAcquireSpinLockShared(), ExReleaseSpinLockExclusive(), and ExTryAcquireSpinLockExclusive().
#define ExQueryDepthSList (_listhead_) (_listhead_)->Depth
Definition at line 1460 of file ex.h.
Referenced by ExFreePoolWithTag(), ExFreeToNPagedLookasideList(), ExFreeToPagedLookasideList(), ExFreeToPPLookasideList(), ExpGetLookasideInformation(), IopFreeIrp(), IopFreeMiniPacket(), MiAllocatePoolPages(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiFreePoolPages(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiInsertPteTracker(), MiReleaseAllMemory(), MmCreateKernelStack(), MmDeleteKernelStack(), WmipAdjustFreeBuffers(), and WmipFlushActiveBuffers().
#define ExReleaseFastMutexUnsafe (FastMutex) xxReleaseFastMutexUnsafe(FastMutex)
Definition at line 1086 of file ex.h.
#define ExReleaseResource (R) (ExReleaseResourceLite(R))
Definition at line 4684 of file ex.h.
#define ExReleaseResourceForThread ExReleaseResourceForThreadLite
Definition at line 4801 of file ex.h.
#define ExSetHandleTableOrder (ht, or) {NOTHING;}
Definition at line 5531 of file ex.h.
Referenced by ObInitProcess2().
#define ExSetHandleTableOwner (ht, id) {(ht)->UniqueProcessId = (id);}
Definition at line 5529 of file ex.h.
Referenced by PspCreateProcess().
#define FM_LOCK_BIT 0x1
Definition at line 359 of file ex.h.
Referenced by KiAcquireFastMutex(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
#define FM_LOCK_BIT_V 0x0
Definition at line 360 of file ex.h.
Referenced by xxAcquireFastMutex(), xxAcquireFastMutexUnsafe(), and xxTryToAcquireFastMutex().
#define FM_LOCK_WAITER_INC 0x4
Definition at line 362 of file ex.h.
Referenced by KiAcquireFastMutex(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
#define FM_LOCK_WAITER_WOKEN 0x2
Definition at line 361 of file ex.h.
Referenced by KiAcquireFastMutex(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
#define HANDLE_TABLE_LOCKS 4
Definition at line 5201 of file ex.h.
Referenced by ExpAllocateHandleTable(), ExpAllocateHandleTableEntry(), ExpFreeHandleTableEntry(), and ExpMoveFreeHandles().
#define HANDLE_TRACE_DB_BADREF 3
Definition at line 5107 of file ex.h.
Referenced by ExMapHandleToPointer(), and ExMapHandleToPointerEx().
#define HANDLE_TRACE_DB_CLOSE 2
Definition at line 5106 of file ex.h.
Referenced by ExDestroyHandle(), and ExpUpdateDebugInfo().
#define HANDLE_TRACE_DB_DEFAULT_STACKS 4096
Definition at line 5099 of file ex.h.
Referenced by ExEnableHandleTracing().
#define HANDLE_TRACE_DB_MAX_STACKS 65536
Definition at line 5097 of file ex.h.
Referenced by ExEnableHandleTracing().
#define HANDLE_TRACE_DB_MIN_STACKS 128
Definition at line 5098 of file ex.h.
Referenced by ExEnableHandleTracing().
#define HANDLE_TRACE_DB_OPEN 1
Definition at line 5105 of file ex.h.
Referenced by ExCreateHandle(), ExDupHandleTable(), and ExpUpdateDebugInfo().
#define HANDLE_TRACE_DB_STACK_SIZE 16
Definition at line 5100 of file ex.h.
Referenced by ExpUpdateDebugInfo().
#define HANDLE_TRACE_DEBUG_INFO_BREAK_ON_WRAP_AROUND 0x4
Definition at line 5147 of file ex.h.
Referenced by ExpUpdateDebugInfo().
#define HANDLE_TRACE_DEBUG_INFO_CLEAN_DEBUG_INFO 0x1
Definition at line 5131 of file ex.h.
Referenced by ExpUpdateDebugInfo().
#define HANDLE_TRACE_DEBUG_INFO_COMPACT_CLOSE_HANDLE 0x2
Definition at line 5140 of file ex.h.
Referenced by ExpUpdateDebugInfo().
#define HANDLE_TRACE_DEBUG_INFO_WAS_SOMETIME_CLEANED 0x80000000
Definition at line 5153 of file ex.h.
Referenced by ExpUpdateDebugInfo().
#define HANDLE_TRACE_DEBUG_INFO_WAS_WRAPPED_AROUND 0x40000000
Definition at line 5152 of file ex.h.
Referenced by ExpUpdateDebugInfo().
#define HANDLE_VALUE_INC 4
Definition at line 4993 of file ex.h.
Referenced by ExDestroyHandleTable(), ExDupHandleTable(), ExEnumHandleTable(), ExpAllocateHandleTable(), ExpAllocateHandleTableEntrySlow(), ExpAllocateLowLevelTable(), ExpFreeHandleTableEntry(), ExpLookupHandleTableEntry(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), and ExSweepHandleTable().
#define InterlockedFlushSList (Head) ExInterlockedFlushSList(Head)
Definition at line 1565 of file ex.h.
#define MAX_FAST_REFS 7
Definition at line 6388 of file ex.h.
Referenced by ExFastRefAddAdditionalReferenceCounts(), ExFastRefCanBeDereferenced(), ExFastRefCompareSwapObject(), ExFastRefDereference(), ExFastRefEqualObjects(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefInitialize(), ExFastRefInitializeEx(), and ExFastRefSwapObject().
#define POOL_COLD_ALLOCATION 256
Definition at line 133 of file ex.h.
Referenced by __bcount(), CmpAllocatePostBlock(), FsRtlAddToTunnelCache(), FsRtlAllocateOplock(), IopComputeHarddiskDerangements(), IoRegisterFsRegistrationChange(), MiBuildImportsForBootDrivers(), MiResolveImageReferences(), MmLoadSystemImage(), and SeRegisterLogonSessionTerminatedRoutine().
#define POOL_MM_ALLOCATION 0x80000000
Definition at line 144 of file ex.h.
Referenced by __bcount(), MiAddViewsForSection(), MiCreateImageFileMap(), MiCreatePagingFileMap(), and MmExtendSection().
#define POOL_QUOTA_FAIL_INSTEAD_OF_RAISE 8
Definition at line 142 of file ex.h.
Referenced by CmpNotifyChangeKey(), DbgkpQueueMessage(), ExLockUserBuffer(), IopAllocateIrpPrivate(), NtCreateJobSet(), NtQueryDirectoryObject(), NtQueueApcThread(), NtRegisterThreadTerminatePort(), PspSetLdtInformation(), and PsSetProcessLdtInfo().
#define POOL_RAISE_IF_ALLOCATION_FAILURE 16
Definition at line 143 of file ex.h.
Referenced by __bcount(), FsRtlInitializeLargeMcbs(), SepInitializePrivilegeSets(), SepInitSystemDacls(), and SepVariableInitialization().
#define ProbeAndNullPointer (Address)
Value:
{                                       \
    if ((PVOID *)(Address) >= (PVOID * const)MM_USER_PROBE_ADDRESS) {        \
        *(volatile PVOID * const)MM_USER_PROBE_ADDRESS = NULL;               \
    }                                                                        \
                                                                             \
    *(volatile PVOID *)(Address) = NULL;                                     \
}
Definition at line 3357 of file ex.h.
#define ProbeAndReadBoolean (Address)
Value:
(((Address) >= (BOOLEAN * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile BOOLEAN * const)MM_USER_PROBE_ADDRESS) : (*(volatile BOOLEAN *)(Address)))
Definition at line 2346 of file ex.h.
#define ProbeAndReadChar (Address)
Value:
(((Address) >= (CHAR * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile CHAR * const)MM_USER_PROBE_ADDRESS) : (*(volatile CHAR *)(Address)))
Definition at line 2381 of file ex.h.
Referenced by Ki386CheckDivideByZeroTrap().
#define ProbeAndReadHandle (Address)
Value:
(((Address) >= (HANDLE * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile HANDLE * const)MM_USER_PROBE_ADDRESS) : (*(volatile HANDLE *)(Address)))
Definition at line 2521 of file ex.h.
#define ProbeAndReadLargeInteger (Source)
Value:
(((Source) >= (LARGE_INTEGER * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile LARGE_INTEGER * const)MM_USER_PROBE_ADDRESS) : (*(volatile LARGE_INTEGER *)(Source)))
Definition at line 2766 of file ex.h.
Referenced by NtRemoveIoCompletion(), NtReplyWaitReceivePortEx(), NtSetInformationKey(), NtSignalAndWaitForSingleObject(), NtWaitForMultipleObjects(), NtWaitForMultipleObjects32(), and NtWaitForSingleObject().
#define ProbeAndReadLong (Address)
Value:
(((Address) >= (LONG * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile LONG * const)MM_USER_PROBE_ADDRESS) : (*(volatile LONG *)(Address)))
Definition at line 2591 of file ex.h.
Referenced by SeCaptureAuditPolicy().
#define ProbeAndReadPointer (Address)
Value:
(((Address) >= (PVOID * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile PVOID * const)MM_USER_PROBE_ADDRESS) : (*(volatile PVOID *)(Address)))
Definition at line 2556 of file ex.h.
#define ProbeAndReadQuad (Address)
Value:
(((Address) >= (QUAD * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile QUAD * const)MM_USER_PROBE_ADDRESS) : (*(volatile QUAD *)(Address)))
Definition at line 2696 of file ex.h.
#define ProbeAndReadShort (Address)
Value:
(((Address) >= (SHORT * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile SHORT * const)MM_USER_PROBE_ADDRESS) : (*(volatile SHORT *)(Address)))
Definition at line 2451 of file ex.h.
#define ProbeAndReadStructure (Source, STRUCTURE)
Value:
(((Source) >= (STRUCTURE * const)MM_USER_PROBE_ADDRESS) ?                \
        (*(STRUCTURE * const)MM_USER_PROBE_ADDRESS) : (*(STRUCTURE *)(Source)))
Definition at line 2916 of file ex.h.
Referenced by LpcpCreatePort(), NtAcceptConnectPort(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtSecureConnectPort(), NtUnloadKey2(), NtUnloadKeyEx(), and WmipProbeAndCaptureGuidObjectAttributes().
#define ProbeAndReadStructureEx (Dst, Src, STRUCTURE) (Dst) = ProbeAndReadStructure(Src, STRUCTURE)
Definition at line 2901 of file ex.h.
#define ProbeAndReadUchar (Address)
Value:
(((Address) >= (UCHAR * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile UCHAR * const)MM_USER_PROBE_ADDRESS) : (*(volatile UCHAR *)(Address)))
Definition at line 2416 of file ex.h.
Referenced by ExpDebuggerWorker(), Ki386CheckDivideByZeroTrap(), KiEmulateAtlThunk(), KiNextIStreamByte(), KiOpDecode(), KiPreprocessInvalidOpcodeFault(), NtQueryQuotaInformationFile(), SeCaptureSecurityDescriptor(), SeCaptureSid(), and SeCaptureSidAndAttributesArray().
#define ProbeAndReadUlargeInteger (Source)
Value:
(((Source) >= (ULARGE_INTEGER * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile ULARGE_INTEGER * const)MM_USER_PROBE_ADDRESS) : (*(volatile ULARGE_INTEGER *)(Source)))
Definition at line 2801 of file ex.h.
#define ProbeAndReadUlong (Address)
Value:
(((Address) >= (ULONG * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile ULONG * const)MM_USER_PROBE_ADDRESS) : (*(volatile ULONG *)(Address)))
Definition at line 2626 of file ex.h.
Referenced by Ki386CheckDivideByZeroTrap(), KiEmulateAtlThunk(), KiRaiseException(), NtAcceptConnectPort(), NtQueryEaFile(), NtQueryMultipleValueKey(), NtReadFile(), NtReadFileScatter(), NtSecureConnectPort(), NtSetInformationKey(), NtSetInformationThread(), NtWriteFile(), NtWriteFileGather(), and SeAccessCheckByType().
#define ProbeAndReadUlong_ptr (Address)
Value:
(((Address) >= (ULONG_PTR * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile ULONG_PTR * const)MM_USER_PROBE_ADDRESS) : (*(volatile ULONG_PTR *)(Address)))
Definition at line 2661 of file ex.h.
#define ProbeAndReadUnicodeString (Source)
Value:
(((Source) >= (UNICODE_STRING * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile UNICODE_STRING * const)MM_USER_PROBE_ADDRESS) : (*(volatile UNICODE_STRING *)(Source)))
Definition at line 2858 of file ex.h.
Referenced by NtRenameKey(), and WmipProbeAndCaptureGuidObjectAttributes().
#define ProbeAndReadUnicodeStringEx (Dst, Src) *(Dst) = ProbeAndReadUnicodeString(Src)
Definition at line 2841 of file ex.h.
Referenced by BuildQueryDirectoryIrp(), CmpNameFromAttributes(), CmQueryMultipleValueKey(), IopUnloadDriver(), NtCreateKey(), NtDeleteValueKey(), NtLoadDriver(), NtLoadKeyEx(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtSetSystemInformation(), NtSetValueKey(), NtUnloadKey2(), NtUnloadKeyEx(), ObpCaptureObjectName(), and SepProbeAndCaptureString_U().
#define ProbeAndReadUquad (Address)
Value:
(((Address) >= (UQUAD * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile UQUAD * const)MM_USER_PROBE_ADDRESS) : (*(volatile UQUAD *)(Address)))
Definition at line 2731 of file ex.h.
#define ProbeAndReadUshort (Address)
Value:
(((Address) >= (USHORT * const)MM_USER_PROBE_ADDRESS) ? \
        (*(volatile USHORT * const)MM_USER_PROBE_ADDRESS) : (*(volatile USHORT *)(Address)))
Definition at line 2486 of file ex.h.
Referenced by Ki386CheckDivideByZeroTrap(), SeCaptureAcl(), and SeCaptureSecurityDescriptor().
#define ProbeAndWriteBoolean (Address, Value)
Value:
{                               \
    if ((Address) >= (BOOLEAN * const)MM_USER_PROBE_ADDRESS) {               \
        *(volatile BOOLEAN * const)MM_USER_PROBE_ADDRESS = 0;                \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3621 of file ex.h.
#define ProbeAndWriteChar (Address, Value)
Value:
{                                  \
    if ((Address) >= (CHAR * const)MM_USER_PROBE_ADDRESS) {                  \
        *(volatile CHAR * const)MM_USER_PROBE_ADDRESS = 0;                   \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3662 of file ex.h.
#define ProbeAndWriteHandle (Address, Value)
Value:
{                                \
    if ((Address) >= (HANDLE * const)MM_USER_PROBE_ADDRESS) {                \
        *(volatile HANDLE * const)MM_USER_PROBE_ADDRESS = 0;                 \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3826 of file ex.h.
Referenced by IopCreateFile().
#define ProbeAndWriteLong (Address, Value)
Value:
{                                  \
    if ((Address) >= (LONG * const)MM_USER_PROBE_ADDRESS) {                  \
        *(volatile LONG * const)MM_USER_PROBE_ADDRESS = 0;                   \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3867 of file ex.h.
Referenced by NtSetInformationThread().
#define ProbeAndWritePointer (Address, Value)
Value:
{                               \
    if ((Address) >= (PVOID * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile ULONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3990 of file ex.h.
#define ProbeAndWriteQuad (Address, Value)
Value:
{                                  \
    if ((Address) >= (QUAD * const)MM_USER_PROBE_ADDRESS) {                  \
        *(volatile LONG * const)MM_USER_PROBE_ADDRESS = 0;                   \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 4031 of file ex.h.
#define ProbeAndWriteShort (Address, Value)
Value:
{                                 \
    if ((Address) >= (SHORT * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile SHORT * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3744 of file ex.h.
#define ProbeAndWriteStructure (Address, Value, STRUCTURE)
Value:
{                  \
    if ((STRUCTURE * const)(Address) >= (STRUCTURE * const)MM_USER_PROBE_ADDRESS) { \
        *((volatile UCHAR * const)MM_USER_PROBE_ADDRESS) = 0;                \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 4118 of file ex.h.
#define ProbeAndWriteUchar (Address, Value)
Value:
{                                 \
    if ((Address) >= (UCHAR * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile UCHAR * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3703 of file ex.h.
#define ProbeAndWriteUlong (Address, Value)
Value:
{                                 \
    if ((Address) >= (ULONG * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile ULONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3908 of file ex.h.
Referenced by KiEmulateAtlThunk(), and NtSetInformationThread().
#define ProbeAndWriteUlong_ptr (Address, Value)
Value:
{                             \
    if ((Address) >= (ULONG_PTR * const)MM_USER_PROBE_ADDRESS) {             \
        *(volatile ULONG_PTR * const)MM_USER_PROBE_ADDRESS = 0;              \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3949 of file ex.h.
#define ProbeAndWriteUquad (Address, Value)
Value:
{                                 \
    if ((Address) >= (UQUAD * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile ULONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 4072 of file ex.h.
#define ProbeAndWriteUshort (Address, Value)
Value:
{                                \
    if ((Address) >= (USHORT * const)MM_USER_PROBE_ADDRESS) {                \
        *(volatile USHORT * const)MM_USER_PROBE_ADDRESS = 0;                 \
    }                                                                        \
                                                                             \
    *(Address) = (Value);                                                    \
}
Definition at line 3785 of file ex.h.
Referenced by Ki386CheckDelayedNpxTrap().
#define ProbeAndZeroHandle (Address)
Value:
{                                        \
    if ((Address) >= (HANDLE * const)MM_USER_PROBE_ADDRESS) {                \
        *(volatile HANDLE * const)MM_USER_PROBE_ADDRESS = 0;                 \
    }                                                                        \
                                                                             \
    *(volatile HANDLE *)(Address) = 0;                                       \
}
Definition at line 3279 of file ex.h.
Referenced by NtCreateKey(), and NtOpenKey().
#define ProbeForRead (Address, Length, Alignment)
Value:
{                           \
    ASSERT(((Alignment) == 1) || ((Alignment) == 2) ||                       \
           ((Alignment) == 4) || ((Alignment) == 8) ||                       \
           ((Alignment) == 16));                                             \
                                                                             \
    if ((Length) != 0) {                                                     \
        if (((ULONG_PTR)(Address) & ((Alignment) - 1)) != 0) {               \
            ExRaiseDatatypeMisalignment();                                   \
                                                                             \
        }                                                                    \
        if ((((ULONG_PTR)(Address) + (Length)) > (ULONG_PTR)MM_USER_PROBE_ADDRESS) || \
            (((ULONG_PTR)(Address) + (Length)) < (ULONG_PTR)(Address))) {    \
            *(volatile UCHAR * const)MM_USER_PROBE_ADDRESS = 0;              \
        }                                                                    \
    }                                                                        \
}
Definition at line 2221 of file ex.h.
Referenced by BuildQueryDirectoryIrp(), CmpNameFromAttributes(), CmQueryMultipleValueKey(), ExpGetSystemFirmwareTableInformation(), IopCreateFile(), IopSetEaOrQuotaInformationFile(), IopUnloadDriver(), IopXxxControlFile(), KiOp_Div(), KiRaiseException(), LpcpCopyRequestData(), MiCaptureUlongPtrArray(), MiDoMappedCopy(), MiDoPoolCopy(), NtAddAtom(), NtAdjustPrivilegesToken(), NtCompactKeys(), NtCreateJobSet(), NtCreateKey(), NtCreatePagingFile(), NtCreateSymbolicLinkObject(), NtDeleteValueKey(), NtFindAtom(), NtFlushInstructionCache(), NtLoadDriver(), NtLoadKeyEx(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryEaFile(), NtQueryInformationJobObject(), NtQueryInformationProcess(), NtQueryInformationThread(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryQuotaInformationFile(), NtQueryValueKey(), NtRaiseHardError(), NtReadFileScatter(), NtReleaseKeyedEvent(), NtRenameKey(), NtSetEaFile(), NtSetInformationDebugObject(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetInformationToken(), NtSetSystemInformation(), NtSetValueKey(), NtSetVolumeInformationFile(), NtTraceEvent(), NtUnloadKey2(), NtUnloadKeyEx(), NtWaitForKeyedEvent(), NtWaitForMultipleObjects(), NtWaitForMultipleObjects32(), NtWriteFile(), NtWriteFileGather(), ObpCaptureObjectName(), RtlWalkFrameChain(), SeCaptureAcl(), SeCaptureAuditPolicy(), SeCaptureLuidAndAttributesArray(), SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SepProbeAndCaptureQosData(), SepProbeAndCaptureString_U(), WmipNtDllLoggerInfo(), WmipProbeAndCaptureGuidObjectAttributes(), WmipQuerySingleMultiple(), WmipStartLogger(), WmipVerifyLoggerInfo(), WmiTraceEvent(), WmiTraceUserMessage(), and WmiUpdateTrace().
#define ProbeForReadSmallStructure (Address, Size, Alignment)
Value:
{               \
    ASSERT(((Alignment) == 1) || ((Alignment) == 2) ||                       \
           ((Alignment) == 4) || ((Alignment) == 8) ||                       \
           ((Alignment) == 16));                                             \
    if ((Size == 0) || (Size > 0x10000)) {                                   \
        ASSERT(0);                                                           \
        ProbeForRead(Address, Size, Alignment);                              \
    } else {                                                                 \
        if (((ULONG_PTR)(Address) & ((Alignment) - 1)) != 0) {               \
            ExRaiseDatatypeMisalignment();                                   \
        }                                                                    \
        if ((ULONG_PTR)(Address) >= (ULONG_PTR)MM_USER_PROBE_ADDRESS) {      \
            *(volatile UCHAR * const)MM_USER_PROBE_ADDRESS = 0;              \
        }                                                                    \
    }                                                                        \
}
Definition at line 2298 of file ex.h.
Referenced by CmpNameFromAttributes(), DbgkpPostFakeModuleMessages(), IopCreateFile(), KiContinueEx(), KiContinuePreviousModeUser(), KiRaiseException(), LpcpCopyRequestData(), LpcpCreatePort(), MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MmCreatePeb(), MmCreateTeb(), NtAcceptConnectPort(), NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtCreateKey(), NtCreateKeyedEvent(), NtCreateMailslotFile(), NtCreateNamedPipeFile(), NtCreatePagingFile(), NtCreateSection(), NtCreateSymbolicLinkObject(), NtCreateThread(), NtCreateToken(), NtDebugContinue(), NtDelayExecution(), NtFilterToken(), NtImpersonateClientOfPort(), NtImpersonateThread(), NtLoadKeyEx(), NtLockFile(), NtOpenKey(), NtOpenKeyedEvent(), NtOpenObjectAuditAlarm(), NtOpenProcess(), NtOpenThread(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQuerySymbolicLinkObject(), NtRaiseHardError(), NtReadFile(), NtReadFileScatter(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtRequestPort(), NtRequestWaitReplyPort(), NtSetInformationThread(), NtSetSystemInformation(), NtSetTimer(), NtSetUuidSeed(), NtUnlockFile(), NtWaitForDebugEvent(), NtWriteFile(), NtWriteFileGather(), ObpCaptureObjectCreateInformation(), PsGetContextThread(), PspCaptureTokenFilter(), PsSetContextThread(), RtlMakeStackTraceDataPresent(), SeAccessCheckByType(), SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSecurityQos(), SepAccessCheckAndAuditAlarm(), SepProbeAndCaptureQosData(), and WmiTraceEvent().
#define ProbeForWriteBoolean (Address)
Value:
{                                      \
    if ((Address) >= (BOOLEAN * const)MM_USER_PROBE_ADDRESS) {               \
        *(volatile BOOLEAN * const)MM_USER_PROBE_ADDRESS = 0;                \
    }                                                                        \
                                                                             \
    *(volatile BOOLEAN *)(Address) = *(volatile BOOLEAN *)(Address);         \
}
Definition at line 2952 of file ex.h.
Referenced by NtCancelTimer(), NtCompareTokens(), NtOpenObjectAuditAlarm(), NtPrivilegeCheck(), NtSetTimer(), and SepAccessCheckAndAuditAlarm().
#define ProbeForWriteChar (Address)
Value:
{                                         \
    if ((Address) >= (CHAR * const)MM_USER_PROBE_ADDRESS) {                  \
        *(volatile CHAR * const)MM_USER_PROBE_ADDRESS = 0;                   \
    }                                                                        \
                                                                             \
    *(volatile CHAR *)(Address) = *(volatile CHAR *)(Address);               \
}
Definition at line 2991 of file ex.h.
Referenced by MmProbeAndLockPages().
#define ProbeForWriteHandle (Address)
Value:
{                                       \
    if ((Address) >= (HANDLE * const)MM_USER_PROBE_ADDRESS) {                \
        *(volatile HANDLE * const)MM_USER_PROBE_ADDRESS = 0;                 \
    }                                                                        \
                                                                             \
    *(volatile HANDLE *)(Address) = *(volatile HANDLE *)(Address);           \
}
Definition at line 3240 of file ex.h.
Referenced by LpcpCreatePort(), NtAcceptConnectPort(), NtCreateDebugObject(), NtCreateDirectoryObject(), NtCreateEvent(), NtCreateEventPair(), NtCreateIoCompletion(), NtCreateJobObject(), NtCreateMutant(), NtCreateProcessEx(), NtCreateProfile(), NtCreateSection(), NtCreateSemaphore(), NtCreateSymbolicLinkObject(), NtCreateThread(), NtCreateTimer(), NtCreateToken(), NtDuplicateObject(), NtDuplicateToken(), NtFilterToken(), NtGetNextProcess(), NtGetNextThread(), NtOpenDirectoryObject(), NtOpenEvent(), NtOpenEventPair(), NtOpenIoCompletion(), NtOpenJobObject(), NtOpenMutant(), NtOpenProcess(), NtOpenProcessTokenEx(), NtOpenSection(), NtOpenSemaphore(), NtOpenSymbolicLinkObject(), NtOpenThread(), NtOpenThreadTokenEx(), NtOpenTimer(), and NtSecureConnectPort().
#define ProbeForWriteIoStatus (Address)
Value:
{                                     \
    if ((Address) >= (IO_STATUS_BLOCK * const)MM_USER_PROBE_ADDRESS) {       \
        *(volatile ULONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(volatile IO_STATUS_BLOCK *)(Address) = *(volatile IO_STATUS_BLOCK *)(Address); \
}
Definition at line 3070 of file ex.h.
Referenced by BuildQueryDirectoryIrp(), IopCreateFile(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtCancelIoFile(), NtFlushBuffersFile(), NtFlushVirtualMemory(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtRemoveIoCompletion(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
#define ProbeForWriteIoStatusEx (Address, Cookie) ProbeForWriteIoStatus(Address)
Definition at line 3129 of file ex.h.
#define ProbeForWriteLong (Address)
Value:
{                                        \
    if ((Address) >= (LONG * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile LONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                       \
                                                                            \
    *(volatile LONG *)(Address) = *(volatile LONG *)(Address);              \
}
Definition at line 3396 of file ex.h.
Referenced by NtPulseEvent(), NtReleaseMutant(), NtReleaseSemaphore(), NtResetEvent(), and NtSetEvent().
#define ProbeForWritePointer (Address)
Value:
{                                      \
    if ((PVOID *)(Address) >= (PVOID * const)MM_USER_PROBE_ADDRESS) {        \
        *(volatile PVOID * const)MM_USER_PROBE_ADDRESS = NULL;               \
    }                                                                        \
                                                                             \
    *(volatile PVOID *)(Address) = *(volatile PVOID *)(Address);             \
}
Definition at line 3318 of file ex.h.
Referenced by NtAllocateVirtualMemory(), NtFlushVirtualMemory(), NtFreeVirtualMemory(), NtLockVirtualMemory(), NtMapViewOfSection(), NtProtectVirtualMemory(), and NtUnlockVirtualMemory().
#define ProbeForWriteQuad (Address)
Value:
{                                         \
    if ((Address) >= (QUAD * const)MM_USER_PROBE_ADDRESS) {                  \
        *(volatile LONG * const)MM_USER_PROBE_ADDRESS = 0;                   \
    }                                                                        \
                                                                             \
    *(volatile QUAD *)(Address) = *(volatile QUAD *)(Address);               \
}
Definition at line 3538 of file ex.h.
#define ProbeForWriteShort (Address)
Value:
{                                        \
    if ((Address) >= (SHORT * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile SHORT * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(volatile SHORT *)(Address) = *(volatile SHORT *)(Address);             \
}
Definition at line 3162 of file ex.h.
#define ProbeForWriteUchar (Address)
Value:
{                                        \
    if ((Address) >= (UCHAR * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile UCHAR * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(volatile UCHAR *)(Address) = *(volatile UCHAR *)(Address);             \
}
Definition at line 3030 of file ex.h.
#define ProbeForWriteUlong (Address)
Value:
{                                        \
    if ((Address) >= (ULONG * const)MM_USER_PROBE_ADDRESS) {                 \
        *(volatile ULONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(volatile ULONG *)(Address) = *(volatile ULONG *)(Address);             \
}
Definition at line 3435 of file ex.h.
Referenced by NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtAlertResumeThread(), NtCreateKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtGetWriteWatch(), NtProtectVirtualMemory(), NtQueryDefaultLocale(), NtQueryDirectoryObject(), NtQueryEvent(), NtQueryInformationAtom(), NtQueryInformationJobObject(), NtQueryInformationPort(), NtQueryInformationProcess(), NtQueryInformationThread(), NtQueryInformationToken(), NtQueryIntervalProfile(), NtQueryIoCompletion(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryMutant(), NtQueryObject(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQuerySecurityObject(), NtQuerySemaphore(), NtQuerySymbolicLinkObject(), NtQuerySystemInformation(), NtQueryTimer(), NtQueryValueKey(), NtRaiseHardError(), NtReplyWaitReceivePortEx(), NtResumeThread(), NtSecureConnectPort(), NtSetInformationDebugObject(), NtSetSystemInformation(), NtSuspendThread(), ProbeForWriteUlongAligned32(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
#define ProbeForWriteUlong_ptr (Address)
Value:
{                                    \
    if ((Address) >= (ULONG_PTR * const)MM_USER_PROBE_ADDRESS) {             \
        *(volatile ULONG_PTR * const)MM_USER_PROBE_ADDRESS = 0;              \
    }                                                                        \
                                                                             \
    *(volatile ULONG_PTR *)(Address) = *(volatile ULONG_PTR *)(Address);     \
}
Definition at line 3499 of file ex.h.
Referenced by LpcpCopyRequestData(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushVirtualMemory(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtMapViewOfSection(), NtProtectVirtualMemory(), NtQuerySection(), NtQueryVirtualMemory(), NtReadVirtualMemory(), NtRemoveIoCompletion(), NtUnlockVirtualMemory(), and NtWriteVirtualMemory().
#define ProbeForWriteUquad (Address)
Value:
{                                        \
    if ((Address) >= (QUAD * const)MM_USER_PROBE_ADDRESS) {                  \
        *(volatile ULONG * const)MM_USER_PROBE_ADDRESS = 0;                  \
    }                                                                        \
                                                                             \
    *(volatile UQUAD *)(Address) = *(volatile UQUAD *)(Address);             \
}
Definition at line 3577 of file ex.h.
#define ProbeForWriteUshort (Address)
Value:
{                                       \
    if ((Address) >= (USHORT * const)MM_USER_PROBE_ADDRESS) {                \
        *(volatile USHORT * const)MM_USER_PROBE_ADDRESS = 0;                 \
    }                                                                        \
                                                                             \
    *(volatile USHORT *)(Address) = *(volatile USHORT *)(Address);           \
}
Definition at line 3201 of file ex.h.
Referenced by NtAddAtom(), NtFindAtom(), NtQueryDefaultUILanguage(), NtQueryInstallUILanguage(), and NtQuerySymbolicLinkObject().
#define PROTECTED_POOL 0x80000000
Definition at line 291 of file ex.h.
Referenced by CmpAcquireFileObjectForFile(), CmpAddInfoAfterParseFailure(), CmpAddSecurityCellToCache(), CmpAdjustSecurityCacheSize(), CmpAllocateCmView(), CmpAllocateDelayItem(), CmpAllocateKeyControlBlock(), CmpCheckRegistry2(), CmpCleanUpKcbCacheWithLock(), CmpCleanUpSubKeyInfo(), CmpConstructName(), CmpDereferenceNameControlBlockWithLock(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDoAccessCheckOnSubtree(), CmpDropFileObjectForHive(), CmpDumpKeyBodyList(), CmpFindReusableCellFromCache(), CmpFreeCmView(), CmpFreeDelayItem(), CmpFreeKeyControlBlock(), CmpGetNameControlBlock(), CmpGetSymbolicLink(), CmpInitHiveFromFile(), CmpLoadHiveVolatile(), CmpQueryKeyName(), CmpRemoveFromSecurityCache(), CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), CmQueryKey(), ExFreePoolWithTag(), ExGetBigPoolInfo(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), NtRegisterThreadTerminatePort(), ObpAllocateObject(), ObpFreeObject(), PsImpersonateClient(), PspDeleteThreadSecurity(), and PspExitThread().
#define QueryDepthSList (Head) ExQueryDepthSList(Head)
Definition at line 1568 of file ex.h.
#define RECORD_CALL_DATA (Table)
Value:
{                                                                      \
        PVOID CallersAddress;                                              \
        PVOID CallersCaller;                                               \
        RtlGetCallersAddress(&CallersAddress, &CallersCaller);             \
        ExRecordCallerInHashTable((Table), CallersAddress, CallersCaller); \
    }
Definition at line 52 of file ex.h.
#define RESOURCE_HASH_TABLE_SIZE 64
Definition at line 4584 of file ex.h.
#define ResourceNeverExclusive 0x10
Definition at line 4580 of file ex.h.
Referenced by CcAllocateInitializeBcb(), ExAcquireResourceExclusiveLite(), and ExTryToAcquireResourceExclusiveLite().
#define ResourceOwnedExclusive 0x80
Definition at line 4582 of file ex.h.
Referenced by ExAcquireResourceExclusiveLite(), ExConvertExclusiveToSharedLite(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), and ExTryToAcquireResourceExclusiveLite().
#define ResourceReleaseByOtherThread 0x20
Definition at line 4581 of file ex.h.
Typedef Documentation
typedef struct _CALL_HASH_ENTRY CALL_HASH_ENTRY
typedef struct _CALL_PERFORMANCE_DATA CALL_PERFORMANCE_DATA
typedef struct _EEVENT_PAIR EEVENT_PAIR
typedef struct _ERESOURCE ERESOURCE
typedef ULONG_PTR ERESOURCE_THREAD
Definition at line 4546 of file ex.h.
typedef struct _EX_CALLBACK EX_CALLBACK
typedef struct _EX_CALLBACK_ROUTINE_BLOCK EX_CALLBACK_ROUTINE_BLOCK
typedef struct _EX_DEBUG_LOG EX_DEBUG_LOG
typedef struct _EX_DEBUG_LOG_EVENT EX_DEBUG_LOG_EVENT
typedef struct _EX_DEBUG_LOG_TAG EX_DEBUG_LOG_TAG
typedef VOID(* EX_DESTROY_HANDLE_ROUTINE) (IN HANDLE Handle)
Definition at line 5347 of file ex.h.
typedef BOOLEAN(* EX_DUPLICATE_HANDLE_ROUTINE) (IN struct _EPROCESS *Process OPTIONAL, IN PHANDLE_TABLE OldHandleTable, IN PHANDLE_TABLE_ENTRY OldHandleTableEntry, IN PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 5390 of file ex.h.
typedef BOOLEAN(* EX_ENUMERATE_HANDLE_ROUTINE) (IN PHANDLE_TABLE_ENTRY HandleTableEntry, IN HANDLE Handle, IN PVOID EnumParameter)
Definition at line 5363 of file ex.h.
typedef struct _EX_FAST_REF EX_FAST_REF
typedef enum _EX_POOL_PRIORITY EX_POOL_PRIORITY
typedef struct _EX_PUSH_LOCK EX_PUSH_LOCK
typedef struct _EX_PUSH_LOCK_CACHE_AWARE EX_PUSH_LOCK_CACHE_AWARE
typedef struct _EX_PUSH_LOCK_CACHE_AWARE_PADDED EX_PUSH_LOCK_CACHE_AWARE_PADDED
typedef struct _EX_RUNDOWN_REF EX_RUNDOWN_REF
typedef struct _EX_RUNDOWN_REF_CACHE_AWARE EX_RUNDOWN_REF_CACHE_AWARE
typedef LONG EX_SPIN_LOCK
Definition at line 799 of file ex.h.
typedef struct _EX_WORK_QUEUE EX_WORK_QUEUE
typedef struct _EXHANDLE EXHANDLE
typedef struct _FAST_MUTEX FAST_MUTEX
typedef struct DECLSPEC_CACHEALIGN _GENERAL_LOOKASIDE GENERAL_LOOKASIDE
typedef struct _HANDLE_TABLE HANDLE_TABLE
typedef struct _HANDLE_TABLE_ENTRY HANDLE_TABLE_ENTRY
typedef struct _HANDLE_TABLE_ENTRY_INFO HANDLE_TABLE_ENTRY_INFO
typedef struct _HANDLE_TRACE_DB_ENTRY HANDLE_TRACE_DB_ENTRY
typedef struct _HANDLE_TRACE_DEBUG_INFO HANDLE_TRACE_DEBUG_INFO
typedef struct _NBQUEUE_BLOCK NBQUEUE_BLOCK
typedef struct DECLSPEC_CACHEALIGN _NPAGED_LOOKASIDE_LIST NPAGED_LOOKASIDE_LIST
typedef struct _OWNER_ENTRY OWNER_ENTRY
typedef struct DECLSPEC_CACHEALIGN _PAGED_LOOKASIDE_LIST PAGED_LOOKASIDE_LIST
typedef PVOID(* PALLOCATE_FUNCTION) (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag)
Definition at line 1601 of file ex.h.
typedef struct _CALL_HASH_ENTRY * PCALL_HASH_ENTRY
typedef struct _CALL_PERFORMANCE_DATA * PCALL_PERFORMANCE_DATA
typedef VOID(* PCALLBACK_FUNCTION) (__in_opt PVOID CallbackContext, __in_opt PVOID Argument1, __in_opt PVOID Argument2)
Definition at line 5906 of file ex.h.
typedef struct _CALLBACK_OBJECT* PCALLBACK_OBJECT
Definition at line 5904 of file ex.h.
typedef struct _EEVENT_PAIR * PEEVENT_PAIR
typedef struct _ERESOURCE * PERESOURCE
typedef ERESOURCE_THREAD* PERESOURCE_THREAD
Definition at line 4547 of file ex.h.
typedef struct _EX_CALLBACK * PEX_CALLBACK
typedef NTSTATUS(* PEX_CALLBACK_FUNCTION) (IN PVOID CallbackContext, IN PVOID Argument1, IN PVOID Argument2)
Definition at line 7759 of file ex.h.
typedef struct _EX_CALLBACK_ROUTINE_BLOCK * PEX_CALLBACK_ROUTINE_BLOCK
typedef BOOLEAN(* PEX_CHANGE_HANDLE_ROUTINE) (IN OUT PHANDLE_TABLE_ENTRY HandleTableEntry, IN ULONG_PTR Parameter)
Definition at line 5469 of file ex.h.
typedef struct _EX_DEBUG_LOG * PEX_DEBUG_LOG
typedef struct _EX_DEBUG_LOG_EVENT * PEX_DEBUG_LOG_EVENT
typedef struct _EX_DEBUG_LOG_TAG * PEX_DEBUG_LOG_TAG
typedef struct _EX_FAST_REF * PEX_FAST_REF
typedef struct _EX_PUSH_LOCK * PEX_PUSH_LOCK
typedef struct _EX_PUSH_LOCK_CACHE_AWARE * PEX_PUSH_LOCK_CACHE_AWARE
typedef struct _EX_PUSH_LOCK_CACHE_AWARE_PADDED * PEX_PUSH_LOCK_CACHE_AWARE_PADDED
typedef struct _EX_RUNDOWN_REF * PEX_RUNDOWN_REF
typedef struct _EX_RUNDOWN_REF_CACHE_AWARE * PEX_RUNDOWN_REF_CACHE_AWARE
Definition at line 4919 of file ex.h.
typedef NTSTATUS(* PEX_SNAPSHOT_HANDLE_ENTRY) (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY HandleEntry, IN HANDLE Handle, IN ULONG Length, IN OUT PULONG RequiredLength)
Definition at line 5411 of file ex.h.
typedef NTSTATUS(* PEX_SNAPSHOT_HANDLE_ENTRY_EX) (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO_EX *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY HandleEntry, IN HANDLE Handle, IN ULONG Length, IN OUT PULONG RequiredLength)
Definition at line 5420 of file ex.h.
typedef LONG * PEX_SPIN_LOCK
Definition at line 799 of file ex.h.
typedef struct _EX_WORK_QUEUE * PEX_WORK_QUEUE
typedef struct _EXHANDLE * PEXHANDLE
typedef struct _FAST_MUTEX * PFAST_MUTEX
typedef VOID(* PFREE_FUNCTION) (IN PVOID Buffer)
Definition at line 1609 of file ex.h.
typedef struct DECLSPEC_CACHEALIGN _GENERAL_LOOKASIDE * PGENERAL_LOOKASIDE
typedef struct _HANDLE_TABLE * PHANDLE_TABLE
typedef struct _HANDLE_TABLE_ENTRY * PHANDLE_TABLE_ENTRY
typedef struct _HANDLE_TABLE_ENTRY_INFO * PHANDLE_TABLE_ENTRY_INFO
typedef struct _HANDLE_TRACE_DB_ENTRY * PHANDLE_TRACE_DB_ENTRY
typedef struct _HANDLE_TRACE_DEBUG_INFO * PHANDLE_TRACE_DEBUG_INFO
typedef PVOID(* PKWIN32_GLOBALATOMTABLE_CALLOUT) (void)
Definition at line 5991 of file ex.h.
typedef struct _NBQUEUE_BLOCK * PNBQUEUE_BLOCK
typedef struct DECLSPEC_CACHEALIGN _NPAGED_LOOKASIDE_LIST * PNPAGED_LOOKASIDE_LIST
typedef enum _POOL_TYPE POOL_TYPE
typedef struct _OWNER_ENTRY * POWNER_ENTRY
typedef enum _PP_NPAGED_LOOKASIDE_NUMBER PP_NPAGED_LOOKASIDE_NUMBER
typedef struct DECLSPEC_CACHEALIGN _PAGED_LOOKASIDE_LIST * PPAGED_LOOKASIDE_LIST
typedef enum _PP_NPAGED_LOOKASIDE_NUMBER * PPP_NPAGED_LOOKASIDE_NUMBER
typedef struct _RESOURCE_HASH_ENTRY * PRESOURCE_HASH_ENTRY
typedef struct _RESOURCE_PERFORMANCE_DATA * PRESOURCE_PERFORMANCE_DATA
typedef struct _WORK_QUEUE_ITEM * PWORK_QUEUE_ITEM
typedef VOID(* PWORKER_THREAD_ROUTINE) (IN PVOID Parameter)
Definition at line 4168 of file ex.h.
typedef struct _ZONE_HEADER * PZONE_HEADER
typedef struct _ZONE_SEGMENT_HEADER * PZONE_SEGMENT_HEADER
typedef struct _RESOURCE_HASH_ENTRY RESOURCE_HASH_ENTRY
typedef struct _RESOURCE_PERFORMANCE_DATA RESOURCE_PERFORMANCE_DATA
typedef GUID UUID
Definition at line 6003 of file ex.h.
typedef struct _WORK_QUEUE_ITEM WORK_QUEUE_ITEM
typedef enum _WORK_QUEUE_TYPE WORK_QUEUE_TYPE
typedef struct _ZONE_HEADER ZONE_HEADER
typedef struct _ZONE_SEGMENT_HEADER ZONE_SEGMENT_HEADER
Enumeration Type Documentation
enum _EX_POOL_PRIORITY
Enumerator
LowPoolPriority
LowPoolPrioritySpecialPoolOverrun
LowPoolPrioritySpecialPoolUnderrun
NormalPoolPriority
NormalPoolPrioritySpecialPoolOverrun
NormalPoolPrioritySpecialPoolUnderrun
HighPoolPriority
HighPoolPrioritySpecialPoolOverrun
HighPoolPrioritySpecialPoolUnderrun
Definition at line 233 of file ex.h.
enum _POOL_TYPE
Enumerator
NonPagedPool
PagedPool
NonPagedPoolMustSucceed
DontUseThisType
NonPagedPoolCacheAligned
PagedPoolCacheAligned
NonPagedPoolCacheAlignedMustS
MaxPoolType
NonPagedPoolSession
PagedPoolSession
NonPagedPoolMustSucceedSession
DontUseThisTypeSession
NonPagedPoolCacheAlignedSession
PagedPoolCacheAlignedSession
NonPagedPoolCacheAlignedMustSSession
Definition at line 104 of file ex.h.
enum _PP_NPAGED_LOOKASIDE_NUMBER
Enumerator
LookasideSmallIrpList
LookasideLargeIrpList
LookasideMdlList
LookasideCreateInfoList
LookasideNameBufferList
LookasideTwilightList
LookasideCompletionList
LookasideMaximumList
Definition at line 1977 of file ex.h.
enum _WORK_QUEUE_TYPE
Enumerator
CriticalWorkQueue
DelayedWorkQueue
HyperCriticalWorkQueue
MaximumWorkQueue
Definition at line 4159 of file ex.h.
Function Documentation
DECLSPEC_DEPRECATED_DDK NTKERNELAPI __bcount (NumberOfBytes)
LONG _InterlockedAddLargeStatistic (IN PLONGLONG Addend, IN ULONG Increment)
C_ASSERT (sizeof(FAST_MUTEX) = =sizeof(KGUARDED_MUTEX))
C_ASSERT (sizeof(NPAGED_LOOKASIDE_LIST) = =sizeof(PAGED_LOOKASIDE_LIST))
DECLSPEC_ALIGN (16)
Definition at line 7591 of file ex.h.
NTKERNELAPI VOID ExAcquireCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE CacheAwarePushLock)
Definition at line 1398 of file pushlock.c.
References EX_PUSH_LOCK_FANNED_COUNT, ExAcquirePushLockExclusive(), ExTryAcquirePushLockExclusive(), and KeNumberProcessors.
Referenced by MiAweViewInserter(), MiAweViewRemover(), MiProtectAweRegion(), MiRemoveUserPhysicalPagesVad(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
PEX_PUSH_LOCK FORCEINLINE ExAcquireCacheAwarePushLockShared (IN PEX_PUSH_LOCK_CACHE_AWARE CacheAwarePushLock)
Definition at line 7690 of file ex.h.
References EX_PUSH_LOCK_FANNED_COUNT, ExAcquirePushLockSharedAssumeNoOwner(), and KeGetCurrentProcessorNumber().
Referenced by MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtMapUserPhysicalPages(), and NtMapUserPhysicalPagesScatter().
NTKERNELAPI VOID FASTCALL ExAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
Definition at line 26 of file fmutexc.c.
References xxAcquireFastMutex().
Referenced by CcCopyWrite(), CcZeroEndOfLastPage(), DbgkClearProcessDebugObject(), DbgkCopyProcessDebugPort(), DbgkOpenProcessDebugPort(), DbgkpCloseObject(), DbgkpMarkProcessPeb(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), ExpUpdateDebugInfo(), ExSwapinWorkerThreads(), FsRtlAddToTunnelCache(), FsRtlCancelExclusiveIrp(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFindInTunnelCache(), FsRtlInsertPerFileObjectContext(), FsRtlInsertPerStreamContext(), FsRtlLookupPerFileObjectContext(), FsRtlLookupPerStreamContextInternal(), FsRtlRemovePerFileObjectContext(), FsRtlRemovePerStreamContext(), FsRtlTeardownPerStreamContexts(), KeGenericCallDpc(), NtDebugContinue(), NtSetInformationDebugObject(), NtWaitForDebugEvent(), and RtlpTraceDatabaseAcquireLock().
VOID FORCEINLINE ExAcquirePushLockExclusive (IN PEX_PUSH_LOCK PushLock)
Definition at line 7211 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK_V, ExfAcquirePushLockExclusive(), and InterlockedBitTestAndSet().
Referenced by CcGetVirtualAddressIfMapped(), ExAcquireCacheAwarePushLockExclusive(), ExCreateHandleTable(), ExDupHandleTable(), ExReferenceCallBackBlock(), ExRemoveHandleTable(), ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), ObpLockDirectoryExclusive(), PsLocateSystemDll(), PspLockProcessExclusive(), PspLockThreadSecurityExclusive(), and RtlpLockAtomTable().
VOID FORCEINLINE ExAcquirePushLockShared (IN PEX_PUSH_LOCK PushLock)
Definition at line 7317 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, ExfAcquirePushLockShared(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waiting.
Referenced by CcGetVacbMiss(), CcGetVirtualAddress(), CcUnmapVacbArray(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ObLogSecurityDescriptor(), ObpLockDirectoryShared(), PsMapSystemDll(), PspLockProcessShared(), and PspLockThreadSecurityShared().
VOID FORCEINLINE ExAcquirePushLockSharedAssumeNoOwner (IN PEX_PUSH_LOCK PushLock)
Definition at line 7355 of file ex.h.
References EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, ExfAcquirePushLockShared(), InterlockedCompareExchangePointer, and NULL.
Referenced by ExAcquireCacheAwarePushLockShared().
NTKERNELAPI VOID FORCEINLINE ExAcquireReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
Definition at line 7094 of file ex.h.
References ASSERT, ExfAcquirePushLockExclusive(), ExfReleasePushLockExclusive(), and KeMemoryBarrier().
Referenced by ExCompareExchangeCallBack(), ExpMoveFreeHandles(), and ObpReferenceNameInfo().
NTKERNELAPI BOOLEAN ExAcquireResourceExclusiveLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 619 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateExclusiveWaiterEvent(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsOwnedExclusive, KeGetCurrentThread(), KeIsExecutingDpc(), NULL, PsGetCurrentThread(), ResourceNeverExclusive, ResourceOwnedExclusive, and TRUE.
Referenced by CcAcquireByteRangeForWrite(), CcPinFileData(), CcUnpinRepinnedBcb(), CmpLockRegistryExclusive(), ExEnterCriticalRegionAndAcquireResourceExclusive(), ExpRegisterFirmwareTableInformationHandler(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlCopyWrite(), FsRtlPrepareMdlWriteDev(), IopBootLog(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopGetSetSecurityObject(), IopInitializeBootLogging(), IopLoadDriver(), IopSetDeviceSecurityDescriptor(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoShutdownSystem(), IoUnregisterFileSystem(), IoUnregisterFsRegistrationChange(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiProcessLoaderEntry(), MmExtendSection(), MmInitSystem(), NtAssignProcessToJobObject(), NtQuerySystemInformation(), NtSetInformationJobObject(), ObpLockAllObjects(), Ps386GetVdmIoHandler(), PsEnforceExecutionTimeLimits(), PsGetNextJobProcess(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspAddProcessToJob(), PspExitProcessFromJob(), PspJobClose(), PspJobDelete(), PspRemoveProcessFromJob(), PspSetQuotaLimits(), and PspTerminateAllProcessesInJob().
NTKERNELAPI BOOLEAN ExAcquireResourceSharedLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 861 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateSharedWaiterSemaphore(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsExclusiveWaiting, IsOwnedExclusive, KeGetCurrentThread(), KeIsExecutingDpc(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and TRUE.
Referenced by CmpLockRegistry(), ExEnterCriticalRegionAndAcquireResourceShared(), ExpGetSystemFirmwareTableInformation(), FsRtlAcquireFileForCcFlushEx(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), IoEnumerateRegisteredFiltersList(), IopGetSetSecurityObject(), IopInitializeBootLogging(), IopInvalidateVolumesForDevice(), IopLoadDriver(), IopMountVolume(), IopParseDevice(), IopSetDeviceSecurityDescriptor(), MiLookupDataTableEntry(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmLockPageableDataSection(), NtQueryInformationJobObject(), NtSetInformationProcess(), PspCreateThread(), and PspExitProcess().
NTKERNELAPI BOOLEAN FORCEINLINE FASTCALL ExAcquireRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 6260 of file ex.h.
References EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, ExfAcquireRundownProtection(), InterlockedCompareExchangePointerAcquire, ReadForWriteAccess, and TRUE.
Referenced by DbgkpMarkProcessPeb(), DbgkpPostFakeThreadMessages(), ExAcquireRundownProtectionCacheAware(), ExReferenceCallBackBlock(), MmCopyVirtualMemory(), NtAssignProcessToJobObject(), NtDebugActiveProcess(), NtQueryInformationProcess(), NtSetInformationProcess(), NtSetInformationThread(), NtTerminateProcess(), ObReferenceProcessHandleTable(), PspCreateProcess(), PspCreateThread(), PspWriteTebImpersonationInfo(), PsReferenceProcessFilePointer(), PsResumeProcess(), PsSuspendProcess(), and PsSuspendThread().
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 879 of file rundown.c.
References ExAcquireRundownProtection(), and EXP_GET_CURRENT_RUNDOWN_REF().
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in ULONG Count)
Definition at line 931 of file rundown.c.
References ExAcquireRundownProtectionEx(), and EXP_GET_CURRENT_RUNDOWN_REF().
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
Definition at line 231 of file rundown.c.
References Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, InterlockedCompareExchangePointer, and TRUE.
Referenced by ExAcquireRundownProtectionCacheAwareEx(), ExCompareExchangeCallBack(), and ExReferenceCallBackBlock().
NTKERNELAPI BOOLEAN ExAcquireSharedStarveExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 1062 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateSharedWaiterSemaphore(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsOwnedExclusive, KeIsExecutingDpc(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and TRUE.
Referenced by CcPinFileData(), CcPinMappedData(), and CmpLockRegistry().
NTKERNELAPI BOOLEAN ExAcquireSharedWaitForExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 1216 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateSharedWaiterSemaphore(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsExclusiveWaiting, IsOwnedExclusive, KeIsExecutingDpc(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and TRUE.
Referenced by ExEnterCriticalRegionAndAcquireSharedWaitForExclusive(), and FsRtlAcquireFileForModWriteEx().
FORCEINLINE KIRQL ExAcquireSpinLockExclusive (IN PEX_SPIN_LOCK SpinLock)
Definition at line 918 of file ex.h.
References ExAcquireSpinLockShared(), ExReleaseSpinLockShared(), ExTryAcquireSpinLockExclusive(), KeYieldProcessor, and TRUE.
Referenced by ExGetBigPoolInfo().
FORCEINLINE KIRQL ExAcquireSpinLockShared (IN PEX_SPIN_LOCK SpinLock)
Definition at line 807 of file ex.h.
References DISPATCH_LEVEL, EXP_SPIN_LOCK_EXCLUSIVE, InterlockedCompareExchangeAcquire, KeRaiseIrql, KeYieldProcessor, and TRUE.
Referenced by ExAcquireSpinLockExclusive(), ExpAddTagForBigPages(), and ExpFindAndRemoveTagBigPages().
BOOLEAN ExAcquireTimeRefreshLock (IN BOOLEAN Wait)
VOID ExAdjustLookasideDepth (VOID)
Definition at line 82 of file lookasid.c.
References ExNPagedLookasideLock, ExPagedLookasideLock, ExpScanCount, ExpScanGeneralLookasideList(), and ExpScanSystemLookasideList().
Referenced by KeBalanceSetManager().
NTKERNELAPI PEX_PUSH_LOCK_CACHE_AWARE ExAllocateCacheAwarePushLock (VOID)
Definition at line 1276 of file pushlock.c.
References AFFINITY_MASK, EX_PUSH_LOCK_FANNED_COUNT, ExAllocatePoolWithTag, ExFreePool(), ExInitializePushLock(), FALSE, KeNumberNodes, KeNumberProcessors, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), _EX_PUSH_LOCK_CACHE_AWARE_PADDED::Lock, _EX_PUSH_LOCK_CACHE_AWARE::Locks, NULL, PagedPool, _EX_PUSH_LOCK_CACHE_AWARE_PADDED::Single, and TRUE.
Referenced by MiAllocateAweInfo().
NTKERNELAPI PEX_RUNDOWN_REF_CACHE_AWARE ExAllocateCacheAwareRundownProtection (__in POOL_TYPE PoolType, __in ULONG PoolTag)
Definition at line 600 of file rundown.c.
References ASSERT, ExAllocatePoolWithTag, ExFreePool(), ExInitializeRundownProtection(), EXP_ALIGN_UP_PTR_ON_BOUNDARY, EXP_GET_PROCESSOR_RUNDOWN_REF(), EXP_IS_ALIGNED_ON_BOUNDARY, Index, KeGetRecommendedSharedDataAlignment(), KeNumberProcessors, NULL, _EX_RUNDOWN_REF_CACHE_AWARE::Number, PAGED_CODE, _EX_RUNDOWN_REF_CACHE_AWARE::PoolToFree, _EX_RUNDOWN_REF_CACHE_AWARE::RunRefs, and _EX_RUNDOWN_REF_CACHE_AWARE::RunRefSize.
PEX_CALLBACK_ROUTINE_BLOCK ExAllocateCallBack (IN PEX_CALLBACK_FUNCTION Function, IN PVOID Context)
Definition at line 801 of file callback.c.
References _EX_CALLBACK_ROUTINE_BLOCK::Context, ExAllocatePoolWithTag, ExInitializeRundownProtection(), _EX_CALLBACK_ROUTINE_BLOCK::Function, NULL, PagedPool, and _EX_CALLBACK_ROUTINE_BLOCK::RundownProtect.
Referenced by CmRegisterCallback(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
__inline PVOID ExAllocateFromNPagedLookasideList (IN PNPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 1693 of file ex.h.
References ExInterlockedPopEntrySList, InterlockedPopEntrySList(), and NULL.
Referenced by ExDeleteNPagedLookasideList(), FsRtlAllocateExclusiveLock(), FsRtlAllocateLockInfo(), FsRtlAllocateLockTreeNode(), FsRtlAllocateSharedLock(), FsRtlAllocateWaitingLock(), and WmipAllocRegEntry().
__inline PVOID ExAllocateFromPagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 1865 of file ex.h.
References InterlockedPopEntrySList(), and NULL.
Referenced by ExDeletePagedLookasideList(), ExDrainPoolLookasideList(), FsRtlAddToTunnelCache(), FsRtlAllocateFileLock(), and LpcpAllocateFromPortZone().
FORCEINLINE PVOID ExAllocateFromPPLookasideList (IN PP_NPAGED_LOOKASIDE_NUMBER Number)
Definition at line 1992 of file ex.h.
References ASSERT, InterlockedPopEntrySList(), KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, LookasideMaximumList, NULL, _PP_LOOKASIDE_LIST::P, _KPRCB::PPLookasideList, and _GENERAL_LOOKASIDE::TotalAllocates.
Referenced by IoAllocateMdl(), and ObpAllocateObjectNameBuffer().
__inline VOID ExAllocateLocallyUniqueId (IN OUT PLUID Luid)
Definition at line 5580 of file ex.h.
References _LARGE_INTEGER::HighPart, InterlockedCompareExchange64, _LARGE_INTEGER::LowPart, and _LARGE_INTEGER::QuadPart.
Referenced by NtAllocateLocallyUniqueId(), SeCreateAccessStateEx(), SepAccessCheckAndAuditAlarm(), SepCreateToken(), SepDuplicateToken(), and SepFilterToken().
VOID ExAllocatePoolSanityChecks (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes)
Definition at line 6147 of file pool.c.
References APC_LEVEL, DISPATCH_LEVEL, DRIVER_VERIFIER_DETECTED_VIOLATION, KeBugCheckEx(), KeGetCurrentIrql(), and PagedPool.
NTKERNELAPI VOID FASTCALL ExBlockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Definition at line 1107 of file pushlock.c.
References EX_PUSH_LOCK_FLAGS_SPINNING, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Ptr, and ReadForWriteAccess.
Referenced by ExpBlockOnLockedHandleEntry().
NTSTATUS ExCallCallBack (IN OUT PEX_CALLBACK CallBack, IN PVOID Argument1, IN PVOID Argument2)
Definition at line 1138 of file callback.c.
References _EX_CALLBACK_ROUTINE_BLOCK::Context, ExDereferenceCallBackBlock(), ExReferenceCallBackBlock(), _EX_CALLBACK_ROUTINE_BLOCK::Function, Status, and STATUS_SUCCESS.
NTKERNELAPI BOOLEAN ExChangeHandle (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PEX_CHANGE_HANDLE_ROUTINE ChangeRoutine, __in ULONG_PTR Parameter)
Definition at line 1923 of file handle.c.
References ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), FALSE, _EXHANDLE::GenericHandleOverlay, Handle, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, and PAGED_CODE.
Referenced by ObSetHandleAttributes().
BOOLEAN ExCompareExchangeCallBack (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK NewBlock, IN PEX_CALLBACK_ROUTINE_BLOCK OldBlock)
Definition at line 888 of file callback.c.
References ASSERTMSG, ExAcquireReleasePushLockExclusive(), ExAcquireRundownProtectionEx(), ExFastRefCompareSwapObject(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefGetUnusedReferences(), ExReleaseRundownProtectionEx(), FALSE, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, _EX_CALLBACK_ROUTINE_BLOCK::RundownProtect, and TRUE.
Referenced by CmRegisterCallback(), CmUnRegisterCallback(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
ULONG ExComputeTickCountMultiplier (IN ULONG TimeIncrement)
Definition at line 395 of file exinit.c.
References Index.
Referenced by ExpInitializeExecutive().
NTKERNELAPI VOID ExConvertExclusiveToSharedLite (__inout PERESOURCE Resource)
Definition at line 2089 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, IsOwnedExclusive, IsSharedWaiting, KeIsExecutingDpc(), KeReleaseSemaphore(), PsGetCurrentThread(), and ResourceOwnedExclusive.
Referenced by FsRtlAcquireFileForModWriteEx().
VOID FORCEINLINE ExConvertPushLockExclusiveToShared (IN PEX_PUSH_LOCK PushLock)
Definition at line 7163 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, ExfConvertPushLockExclusiveToShared(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Shared, and _EX_PUSH_LOCK::Waiting.
NTKERNELAPI NTSTATUS ExCreateCallback (__deref_out PCALLBACK_OBJECT * CallbackObject, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN Create, __in BOOLEAN AllowMultipleCallbacks)
Definition at line 264 of file callback.c.
References _CALLBACK_OBJECT::AllowMultipleCallbacks, FILE_READ_DATA, Handle, InitializeListHead(), KeInitializeSpinLock(), KernelMode, _CALLBACK_OBJECT::Lock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, PAGED_CODE, _CALLBACK_OBJECT::RegisteredCallbacks, _CALLBACK_OBJECT::Signature, Status, STATUS_UNSUCCESSFUL, and ZwClose().
Referenced by ExpInitializeCallbacks().
NTKERNELAPI PEX_DEBUG_LOG ExCreateDebugLog (__in UCHAR MaximumNumberOfTags, __in ULONG MaximumNumberOfEvents)
NTKERNELAPI UCHAR ExCreateDebugLogTag (__in PEX_DEBUG_LOG Log, __in PCHAR Name, __in UCHAR Format1, __in UCHAR Format2, __in UCHAR Format3, __in UCHAR Format4)
NTKERNELAPI HANDLE ExCreateHandle (__inout PHANDLE_TABLE HandleTable, __in PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 1729 of file handle.c.
References ExpAllocateHandleTableEntry(), ExpUpdateDebugInfo(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_OPEN, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, PsGetCurrentThread(), and _ETHREAD::Tcb.
Referenced by ObDuplicateObject(), ObpCreateHandle(), ObpCreateUnnamedHandle(), PspCreateProcess(), PspCreateThread(), and RtlpCreateHandleForAtom().
NTKERNELAPI PHANDLE_TABLE ExCreateHandleTable (__in_opt struct _EPROCESS * Process)
Definition at line 830 of file handle.c.
References ExAcquirePushLockExclusive(), ExpAllocateHandleTable(), ExReleasePushLockExclusive(), _HANDLE_TABLE::HandleTableList, InsertTailList(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, and TRUE.
Referenced by ObInitProcess(), ObInitSystem(), PspInitPhase0(), and RtlpInitializeHandleTableForAtomTable().
NTKERNELAPI VOID ExDebugLogEvent (__in PEX_DEBUG_LOG Log, __in UCHAR Tag, __in ULONG Data1, __in ULONG Data2, __in ULONG Data3, __in ULONG Data4)
NTKERNELAPI VOID ExDeleteNPagedLookasideList (__inout PNPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 579 of file lookasid.c.
References ExAcquireSpinLock, ExAllocateFromNPagedLookasideList(), ExNPagedLookasideLock, ExpDummyAllocate(), ExReleaseSpinLock, NULL, and RemoveEntryList().
NTKERNELAPI VOID ExDeletePagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 716 of file lookasid.c.
References ExAcquireSpinLock, ExAllocateFromPagedLookasideList(), ExPagedLookasideLock, ExpDummyAllocate(), ExReleaseSpinLock, NULL, and RemoveEntryList().
Referenced by MiDereferenceSessionFinal().
NTKERNELAPI NTSTATUS ExDeleteResourceLite (__inout PERESOURCE Resource)
Definition at line 2151 of file resource.c.
References ASSERT, ASSERT_RESOURCE, ExFreePool(), FALSE, IsExclusiveWaiting, IsSharedWaiting, KeAcquireInStackQueuedSpinLock(), KeIsExecutingDpc(), KeReleaseInStackQueuedSpinLock(), NULL, RemoveEntryList(), and STATUS_SUCCESS.
Referenced by CcDeallocateBcb(), ObpDeleteObjectType(), PspDeleteVdmObjects(), PspJobDelete(), and SepTokenDeleteMethod().
VOID ExDereferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 1111 of file callback.c.
References ExFastRefDereference(), ExpCallBackReturnRefs, and ExReleaseRundownProtection().
Referenced by CmpCallCallBacks(), CmUnRegisterCallback(), ExCallCallBack(), PsCallImageNotifyRoutines(), PspCreateThread(), PspExitProcess(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
VOID ExDereferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable, IN PHANDLE_TRACE_DEBUG_INFO DebugInfo)
Definition at line 2311 of file handle.c.
References ASSERT, ExFreePool(), InterlockedDecrement, InterlockedExchangeAdd(), NULL, PsReturnProcessNonPagedPoolQuota(), and TotalTraceBuffers.
Referenced by ExDisableHandleTracing(), ExEnableHandleTracing(), ExpFreeHandleTable(), ExpUpdateDebugInfo(), and NtQueryInformationProcess().
NTKERNELAPI BOOLEAN ExDestroyHandle (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __inout_opt PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 1815 of file handle.c.
References EXASSERT, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExpFreeHandleTableEntry(), ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), ExUnblockPushLock(), FALSE, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_CLOSE, InterlockedExchangePointer, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, PsGetCurrentThread(), _ETHREAD::Tcb, and TRUE.
Referenced by ObpCloseHandleTableEntry(), PspProcessDelete(), PspThreadDelete(), and RtlpFreeHandleForAtom().
NTKERNELAPI VOID ExDestroyHandleTable (__inout PHANDLE_TABLE HandleTable, __in EX_DESTROY_HANDLE_ROUTINE DestroyHandleProcedure)
Definition at line 952 of file handle.c.
References ARGUMENT_PRESENT, ExpFreeHandleTable(), ExpIsValidObjectEntry, ExpLookupHandleTableEntry(), ExRemoveHandleTable(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, NULL, PAGED_CODE, and _EXHANDLE::Value.
Referenced by ObKillProcess(), and RtlpDestroyHandleTableForAtomTable().
NTKERNELAPI NTSTATUS ExDisableHandleTracing (__inout PHANDLE_TABLE HandleTable)
Definition at line 2342 of file handle.c.
References ExDereferenceHandleDebugInfo(), ExpLockHandleTableExclusive, ExpUnlockHandleTableExclusive, KeGetCurrentThread(), NULL, and STATUS_SUCCESS.
Referenced by NtSetInformationProcess().
NTKERNELAPI VOID ExDisableResourceBoostLite (__in PERESOURCE Resource)
Definition at line 578 of file resource.c.
References ASSERT_RESOURCE, DisablePriorityBoost, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, and EXP_UNLOCK_RESOURCE.
NTKERNELAPI PHANDLE_TABLE ExDupHandleTable (__inout_opt struct _EPROCESS * Process, __in PHANDLE_TABLE OldHandleTable, __in EX_DUPLICATE_HANDLE_ROUTINE DupHandleProcedure OPTIONAL, __in ULONG_PTR Mask)
Definition at line 1212 of file handle.c.
References _HANDLE_TABLE_ENTRY_INFO::AuditMask, _HANDLE_TABLE::DebugInfo, ExAcquirePushLockExclusive(), ExGetHandleInfo, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExpAllocateHandleTable(), ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTable(), ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), ExReleasePushLockExclusive(), ExSetHandleInfo(), _HANDLE_TABLE::ExtraInfoPages, ExUnlockHandleTableEntry(), FALSE, _HANDLE_TABLE::FirstFree, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_OPEN, HANDLE_VALUE_INC, _HANDLE_TABLE::HandleCount, _HANDLE_TABLE::HandleTableList, InsertTailList(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeMemoryBarrier(), LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, _HANDLE_TABLE::NextHandleNeedingPool, NT_SUCCESS, NULL, _HANDLE_TABLE_ENTRY::Object, PAGED_CODE, PsGetCurrentThread(), Status, STATUS_SUCCESS, TRUE, _EXHANDLE::Value, and _HANDLE_TABLE_ENTRY::Value.
Referenced by ObInitProcess().
NTKERNELAPI NTSTATUS ExEnableHandleTracing (__inout PHANDLE_TABLE HandleTable, __in ULONG Slots)
Definition at line 2386 of file handle.c.
References ASSERT, _HANDLE_TRACE_DEBUG_INFO::CloseCompactionLock, ExAllocatePoolWithTag, ExDereferenceHandleDebugInfo(), ExInitializeFastMutex, ExpLockHandleTableExclusive, ExpUnlockHandleTableExclusive, HANDLE_TRACE_DB_DEFAULT_STACKS, HANDLE_TRACE_DB_MAX_STACKS, HANDLE_TRACE_DB_MIN_STACKS, InterlockedExchangeAdd(), KeGetCurrentThread(), MmMaximumNonPagedPoolInBytes, NonPagedPool, NT_SUCCESS, NULL, PsChargeProcessNonPagedPoolQuota(), PsReturnProcessNonPagedPoolQuota(), _HANDLE_TRACE_DEBUG_INFO::RefCount, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _HANDLE_TRACE_DEBUG_INFO::TableSize, TotalTraceBuffers, _HANDLE_TRACE_DEBUG_INFO::TraceDb, and TRUE.
Referenced by ExpAllocateHandleTable(), and NtSetInformationProcess().
NTKERNELAPI PVOID ExEnterCriticalRegionAndAcquireResourceExclusive (__inout PERESOURCE Resource)
Definition at line 759 of file resource.c.
References _PsGetCurrentThread, ExAcquireResourceExclusiveLite(), KeEnterCriticalRegion(), and TRUE.
NTKERNELAPI PVOID ExEnterCriticalRegionAndAcquireResourceShared (__inout PERESOURCE Resource)
Definition at line 1030 of file resource.c.
References _PsGetCurrentThread, ExAcquireResourceSharedLite(), KeEnterCriticalRegion(), and TRUE.
NTKERNELAPI PVOID ExEnterCriticalRegionAndAcquireSharedWaitForExclusive (__inout PERESOURCE Resource)
Definition at line 1448 of file resource.c.
References _PsGetCurrentThread, ExAcquireSharedWaitForExclusive(), KeEnterCriticalRegion(), and TRUE.
NTKERNELAPI BOOLEAN ExEnumHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter, __out_opt PHANDLE Handle)
Definition at line 1098 of file handle.c.
References ARGUMENT_PRESENT, ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), FALSE, _EXHANDLE::GenericHandleOverlay, HANDLE_VALUE_INC, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, and _EXHANDLE::Value.
Referenced by ObFindHandleForObject(), ObInitProcess(), and ObShutdownSystem().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS ExExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize)
Definition at line 129 of file zone.c.
References STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
Referenced by ExInterlockedExtendZone().
NTKERNELAPI VOID FASTCALL ExfAcquirePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
Definition at line 450 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_WAITING, EX_PUSH_LOCK_WAKING, ExpOptimizePushLockList(), ExPushLockSpinCount, FALSE, InterlockedBitTestAndReset(), InterlockedCompareExchangePointer, KeInitializeGate(), KernelMode, KeWaitForGate(), KeYieldProcessor, _EX_PUSH_LOCK::Locked, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, RTL_BACKOFF, RtlBackoff(), _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, _EX_PUSH_LOCK::Waking, and WrPushLock.
Referenced by ExAcquirePushLockExclusive(), ExAcquireReleasePushLockExclusive(), and ExpInitializePushLocks().
NTKERNELAPI VOID FASTCALL ExfAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 602 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_SHARE_INC, EX_PUSH_LOCK_WAITING, EX_PUSH_LOCK_WAKING, ExpOptimizePushLockList(), ExPushLockSpinCount, FALSE, InterlockedBitTestAndReset(), InterlockedCompareExchangePointer, KeInitializeGate(), KernelMode, KeWaitForGate(), KeYieldProcessor, _EX_PUSH_LOCK::Locked, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, RTL_BACKOFF, RtlBackoff(), _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, _EX_PUSH_LOCK::Waking, and WrPushLock.
Referenced by ExAcquirePushLockShared(), ExAcquirePushLockSharedAssumeNoOwner(), and ExpInitializePushLocks().
NTKERNELAPI BOOLEAN FASTCALL ExfAcquireRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 178 of file rundown.c.
References EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, InterlockedCompareExchangePointer, and TRUE.
Referenced by ExAcquireRundownProtection().
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefAddAdditionalReferenceCounts (__inout PEX_FAST_REF FastRef, __in PVOID Object, __in ULONG RefsToAdd)
Definition at line 6804 of file ex.h.
References ASSERT, FALSE, InterlockedCompareExchangePointerAcquire, MAX_FAST_REFS, _EX_FAST_REF::Object, ReadForWriteAccess, _EX_FAST_REF::RefCnt, TRUE, and _EX_FAST_REF::Value.
Referenced by ExReferenceCallBackBlock(), ObFastReferenceObject(), and ObpReferenceSecurityDescriptor().
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefCanBeDereferenced (__in EX_FAST_REF FastRef)
Definition at line 6434 of file ex.h.
References MAX_FAST_REFS.
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefCanBeReferenced (__in EX_FAST_REF FastRef)
Definition at line 6407 of file ex.h.
Referenced by ExReferenceCallBackBlock().
NTKERNELAPI EX_FAST_REF FORCEINLINE ExFastRefCompareSwapObject (__inout PEX_FAST_REF FastRef, __in_opt PVOID Object, __in PVOID OldObject)
Definition at line 6920 of file ex.h.
References ASSERT, ExFastRefEqualObjects(), InterlockedCompareExchangePointerRelease, MAX_FAST_REFS, NULL, _EX_FAST_REF::Object, ReadForWriteAccess, and _EX_FAST_REF::Value.
Referenced by ExCompareExchangeCallBack(), and ObSetSecurityDescriptorInfo().
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefDereference (__inout PEX_FAST_REF FastRef, __in PVOID Object)
Definition at line 6736 of file ex.h.
References ASSERT, FALSE, InterlockedCompareExchangePointerRelease, MAX_FAST_REFS, NULL, _EX_FAST_REF::Object, ReadForWriteAccess, TRUE, and _EX_FAST_REF::Value.
Referenced by ExDereferenceCallBackBlock(), and ObFastDereferenceObject().
NTKERNELAPI BOOLEAN FORCEINLINE ExFastRefEqualObjects (__in EX_FAST_REF FastRef, __in PVOID Object)
Definition at line 6541 of file ex.h.
References MAX_FAST_REFS.
Referenced by ExFastRefCompareSwapObject(), and ObSetSecurityDescriptorInfo().
NTKERNELAPI EX_FAST_REF FORCEINLINE ExFastReference (__inout PEX_FAST_REF FastRef)
Definition at line 6677 of file ex.h.
References InterlockedCompareExchangePointerAcquire, _EX_FAST_REF::Object, ReadForWriteAccess, _EX_FAST_REF::RefCnt, and _EX_FAST_REF::Value.
Referenced by ExReferenceCallBackBlock(), ObFastReferenceObject(), and ObpReferenceSecurityDescriptor().
NTKERNELAPI ULONG FORCEINLINE ExFastRefGetAdditionalReferenceCount (VOID)
Definition at line 6665 of file ex.h.
References MAX_FAST_REFS.
Referenced by ExCompareExchangeCallBack(), ExReferenceCallBackBlock(), ObAssignObjectSecurityDescriptor(), ObFastReferenceObject(), ObFastReplaceObject(), ObInitializeFastReference(), ObpReferenceSecurityDescriptor(), and ObSetSecurityDescriptorInfo().
NTKERNELAPI PVOID FORCEINLINE ExFastRefGetObject (__in EX_FAST_REF FastRef)
Definition at line 6489 of file ex.h.
References MAX_FAST_REFS.
Referenced by ExCompareExchangeCallBack(), ExReferenceCallBackBlock(), ObDeassignSecurity(), ObFastReferenceObject(), ObFastReferenceObjectLocked(), ObFastReplaceObject(), ObGetObjectInformation(), ObpReferenceSecurityDescriptor(), PspInitPhase0(), and SepInitializationPhase1().
NTKERNELAPI ULONG FORCEINLINE ExFastRefGetUnusedReferences (__in EX_FAST_REF FastRef)
Definition at line 6569 of file ex.h.
Referenced by ExCompareExchangeCallBack(), ObDeassignSecurity(), ObFastReferenceObject(), ObFastReplaceObject(), ObpReferenceSecurityDescriptor(), and ObSetSecurityDescriptorInfo().
NTKERNELAPI VOID FORCEINLINE ExFastRefInitialize (__out PEX_FAST_REF FastRef, __in_opt PVOID Object)
Definition at line 6596 of file ex.h.
References ASSERT, MAX_FAST_REFS, and NULL.
Referenced by ExInitializeCallBack(), ObAssignObjectSecurityDescriptor(), and ObInitializeFastReference().
NTKERNELAPI VOID FORCEINLINE ExFastRefInitializeEx (__out PEX_FAST_REF FastRef, __in_opt PVOID Object, __in ULONG AdditionalRefs)
Definition at line 6629 of file ex.h.
References ASSERT, MAX_FAST_REFS, and NULL.
NTKERNELAPI LOGICAL FORCEINLINE ExFastRefIsLastReference (__in EX_FAST_REF FastRef)
Definition at line 6461 of file ex.h.
Referenced by ExReferenceCallBackBlock().
NTKERNELAPI BOOLEAN FORCEINLINE ExFastRefObjectNull (__in EX_FAST_REF FastRef)
Definition at line 6515 of file ex.h.
Referenced by ExReferenceCallBackBlock(), PspDeleteProcessSecurity(), SeAssignPrimaryToken(), SepCreateToken(), and SepInitializationPhase0().
NTKERNELAPI EX_FAST_REF FORCEINLINE ExFastRefSwapObject (__inout PEX_FAST_REF FastRef, __in_opt PVOID Object)
Definition at line 6876 of file ex.h.
References ASSERT, InterlockedExchangePointer, MAX_FAST_REFS, NULL, _EX_FAST_REF::Object, and _EX_FAST_REF::Value.
Referenced by ObFastReplaceObject().
NTKERNELAPI VOID FASTCALL ExfConvertPushLockExclusiveToShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 1060 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, and _EX_PUSH_LOCK::Waiting.
Referenced by ExConvertPushLockExclusiveToShared().
NTKERNELAPI VOID FASTCALL ExfInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
Definition at line 99 of file rundown.c.
NTKERNELAPI VOID ExFreeCacheAwarePushLock (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
Definition at line 1358 of file pushlock.c.
References CONTAINING_RECORD, EX_PUSH_LOCK_FANNED_COUNT, ExFreePool(), and KeNumberProcessors.
Referenced by MiCleanPhysicalProcessPages(), MiFreeAweInfo(), and MiInsertAweInfo().
NTKERNELAPI VOID ExFreeCacheAwareRundownProtection (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 848 of file rundown.c.
References ASSERT, ExFreePool(), PAGED_CODE, and UintToPtr.
VOID ExFreeCallBack (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 836 of file callback.c.
References ExFreePool().
Referenced by CmRegisterCallback(), CmUnRegisterCallback(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
NTKERNELAPI VOID NTAPI ExFreePool (__in PVOID P)
Definition at line 5027 of file pool.c.
References ExFreePoolWithTag().
Referenced by __out_bcount(), BuildQueryDirectoryIrp(), CcDeallocateBcb(), CcDeleteMbcb(), CcDeleteSharedCacheMap(), CcDrainVacbLevelZone(), CcExtendVacbArray(), CcInitializeCacheMap(), CcPostDeferredWrites(), CcUninitializeCacheMap(), CcUnpinData(), CcUnpinDataForThread(), CcWriteBehind(), CcZeroData(), CmCompressKey(), CmGetSystemControlValues(), CmInitSystem1(), CmpAddToHiveFileList(), CmpAllocatePostBlock(), CmpCacheLookup(), CmpCheckKeyAccess(), CmpCleanUpKcbValueCache(), CmpCloneControlSet(), CmpCmdRenameHive(), CmpCompareNewValueDataAgainstKCBCache(), CmpCopyKeyPartial(), CmpCopySyncTree(), CmpCopySyncTree2(), CmpCopyValue(), CmpCreateRegistryRoot(), CmpDelayedDerefKeys(), CmpDiskFullWarningWorker(), CmpDoQueueLateUnloadWorker(), CmpFileWrite(), CmpFindTagIndex(), CmpFlushNotify(), CmpFree(), CmpFreeAllMemory(), CmpFreePostBlock(), CmpGetSymbolicLink(), CmpGetValueData(), CmpGetValueDataFromCache(), CmpHiveRootSecurityDescriptor(), CmpInitializeHardwareConfiguration(), CmpInitializeHiveList(), CmpInitializeRegistryNode(), CmpInitializeSystemHive(), CmpLateUnloadHiveWorker(), CmpLoadHiveVolatile(), CmpMarkIndexDirty(), CmpMergeKeyValues(), CmpNameFromAttributes(), CmpNotifyChangeKey(), CmpOpenHiveFiles(), CmpParseKey(), CmpPrefetchHiveFile(), CmpQueryKeyValueData(), CmpQuotaWarningWorker(), CmpRaiseSelfHealWarning(), CmpRaiseSelfHealWarningWorker(), CmpRemoveSubKey(), CmpSaveBootControlSet(), CmpSaveKeyByFileCopy(), CmpSetSecurityDescriptorInfo(), CmpShiftAllCells2(), CmpSyncKeyValues(), CmpSystemHiveHysteresisWorker(), CmpSystemQuotaWarningWorker(), CmpValueToData(), CmQueryMultipleValueKey(), CmRegisterCallback(), CmSetValueKey(), CmUnRegisterCallback(), DbgkCreateThread(), DbgkpFreeDebugEvent(), DbgkpPostFakeModuleMessages(), DbgkpQueueMessage(), DbgkpSectionToFileHandle(), ExAllocateCacheAwarePushLock(), ExAllocateCacheAwareRundownProtection(), ExDeleteResourceLite(), ExDereferenceHandleDebugInfo(), ExFreeCacheAwarePushLock(), ExFreeCacheAwareRundownProtection(), ExFreeCallBack(), ExGetPoolTagInfo(), ExInitializeNBQueueHead(), ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), ExInitializeSystemLookasideList(), ExLockUserBuffer(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateHandleTable(), ExpAllocateSharedWaiterSemaphore(), ExpAllocateTablePagedPool(), ExpAllocateTablePagedPoolNoZero(), ExpExpandResourceOwnerTable(), ExpFreeHandleTable(), ExpFreeTablePagedPool(), ExpGetProcessInformation(), ExpKeyedEventInitialization(), ExpProfileDelete(), ExpSystemErrorHandler(), ExRegisterCallback(), ExUnlockUserBuffer(), ExUnregisterCallback(), FsRtlAddLargeEntry(), FsRtlAllocateOplock(), FsRtlCancelNotify(), FsRtlDeregisterUncProvider(), FsRtlFreeTunnelNode(), FsRtlGetCompatibilityModeValue(), FsRtlGetTunnelParameterValue(), FsRtlInsertPerFileObjectContext(), FsRtlIsDbcsInExpression(), FsRtlIsNameInExpressionPrivate(), FsRtlNotifyCleanup(), FsRtlNotifyCompleteIrp(), FsRtlNotifyFilterChangeDirectory(), FsRtlNotifyFilterReportChange(), FsRtlNotifyUninitializeSync(), FsRtlpRegisterProviderWithMUP(), FsRtlPTeardownPerFileObjectContexts(), FsRtlRegisterUncProvider(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlStackOverflowRead(), FsRtlTruncateBaseMcb(), FsRtlUninitializeBaseMcb(), FsRtlUninitializeOplock(), HalExamineMBR(), HalpDeleteMountLetter(), HalpGetFullGeometry(), HalpNextMountLetter(), HalpSetMountLetter(), HvpDoWriteHive(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpWriteLog(), HvRefreshHive(), HvReleaseFreeCellRefArray(), HvTrackCellRef(), HvWriteHive(), IoAllocateDriverObjectExtension(), IoAssignDriveLetters(), IoBuildDeviceIoControlRequest(), IoConnectInterrupt(), IoCreateDevice(), IoDeleteDevice(), IoDisconnectInterrupt(), IoFreeErrorLogEntry(), IoFreeMdl(), IoFreeWorkItem(), IoGetBootDiskInformation(), IoInitSystem(), IoIsValidNameGraftingBuffer(), IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), IopApcHardError(), IopBuildFullDriverPath(), IopCallBootDriverReinitializationRoutines(), IopCallDriverReinitializationRoutines(), IopCompleteRequest(), IopCopyBootLogRegistryToFile(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopCreateFile(), IopDeallocateApc(), IopDeleteDevice(), IopDeleteDriver(), IopDeleteFile(), IopDeleteSessionSymLinks(), IopDereferenceVpbAndFree(), IopDoNameTransmogrify(), IopDropIrp(), IopErrorLogDpc(), IopErrorLogThread(), IopExceptionCleanup(), IopfCompleteRequest(), IopFreeIrp(), IopFreeMiniPacket(), IopGetDriverNameFromKeyNode(), IopGetRegistryKeyInformation(), IopGetRegistryValue(), IopGetSetSecurityObject(), IopHardErrorThread(), IopLoadDriver(), IopParseDevice(), IopQueryNameInternal(), IopRaiseHardError(), IopRaiseInformationalHardError(), IopSafebootDriverLoad(), IopSetDeviceSecurityDescriptor(), IopSetEaOrQuotaInformationFile(), IopStartApcHardError(), IopSynchronousApiServiceTail(), IopTrackLink(), IopUnloadDriver(), IopUnloadSafeCompletion(), IoQueryFileDosDeviceName(), IoRaiseInformationalHardError(), IoReadPartitionTable(), IoSetPartitionInformation(), IoShutdownSystem(), IoUnregisterFsRegistrationChange(), IoUnregisterShutdownNotification(), IoVolumeDeviceToDosName(), IoWMISuggestInstanceName(), IoWMISystemControl(), IoWriteErrorLogEntry(), IoWritePartitionTable(), Ke386CallBios(), KeRestoreFloatingPointState(), KeStartProfile(), KeStopProfile(), KiAddRange(), KiCompleteEffectiveRangeChange(), KiInitializeInterruptTimersDpc(), KiInitializeMTRR(), LpcpDestroyPortQueue(), MiAddViewsForSection(), MiAllocateAweInfo(), MiAllocateContiguousMemory(), MiAllocateLargePages(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiAweViewRemover(), MiBuildImportsForBootDrivers(), MiCcPutPagesInTransition(), MiCcReleasePrefetchResources(), MiCleanPhysicalProcessPages(), MiClearImports(), MiCloneProcessAddressSpace(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreateMemoryEvent(), MiCreatePagingFileMap(), MiCreatePebOrTeb(), MiCreatePhysicalVadRoot(), MiDecrementCloneBlockReference(), MiDereferenceImports(), MiDereferenceIoSpace(), MiDoPoolCopy(), MiFindContiguousMemoryInPool(), MiFlushSectionInternal(), MiFreeAweInfo(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiFreeMdlTracker(), MiFreeSessionPoolBitMaps(), MiFreeSessionSpaceMap(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiInitializeLoadedModuleList(), MiInitializeSystemPtes(), MiInsertAweInfo(), MiInsertInSystemSpace(), MiInsertPteTracker(), MiLdwPopupWorker(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiPhysicalViewRemover(), MiReleaseAllMemory(), MiReleaseProcessReferenceToSessionDataPage(), MiRemoveIoSpaceMap(), MiRemoveMappedView(), MiRemoveUnusedSegments(), MiRemoveVadCharges(), MiResolveImageReferences(), MiReturnLargePages(), MiSectionInitialization(), MiSecureVirtualMemory(), MiSegmentDelete(), MiSessionCreateInternal(), MiSessionInsertImage(), MiSessionProcessGlobalSubsections(), MiSessionRemoveImage(), MiSessionWideReserveImageAddress(), MiShutdownSystem(), MiSnapThunk(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MiUnsecureVirtualMemory(), MiZeroPageFile(), MiZeroPageWorker(), MmCallDllInitialize(), MmCleanProcessAddressSpace(), MmCreateSection(), MmDeleteTeb(), MmExtendSection(), MmFreeBootRegistry(), MmFreeContiguousMemory(), MmFreeLoaderBlock(), MmFreeNonCachedMemory(), MmGetFileNameForAddress(), MmGetFileNameForSection(), MmInitializeMemoryLimits(), MmInitializeProcessAddressSpace(), MmLoadSystemImage(), MmPerfUnusedSegmentsEnumerate(), MmProbeAndLockSelectedPages(), MmProtectMdlSystemAddress(), MmUnloadSystemImage(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtCloseObjectAuditAlarm(), NtCompactKeys(), NtCreateJobSet(), NtCreatePagingFile(), NtDeleteObjectAuditAlarm(), NtFlushBuffersFile(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLoadDriver(), NtLoadKeyEx(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtOpenObjectAuditAlarm(), NtOpenThreadTokenEx(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryInformationProcess(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtQueueApcThread(), NtReadFileScatter(), NtReplaceKey(), NtSecureConnectPort(), NtSetEaFile(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationProcess(), NtSetSystemInformation(), NtSetValueKey(), NtSetVolumeInformationFile(), NtStartProfile(), NtStopProfile(), NtUnlockFile(), NtWriteFileGather(), ObAssignObjectSecurityDescriptor(), ObCreateObjectType(), ObDereferenceSecurityDescriptor(), ObfDereferenceDeviceMap(), ObGetObjectSecurity(), ObInitSystem(), ObLogSecurityDescriptor(), ObOpenObjectByName(), ObpCaptureObjectName(), ObpDeleteDirectoryEntry(), ObpDeleteSymbolicLink(), ObpDereferenceNameInfo(), ObpFreeDosDevicesProtection(), ObpFreeObject(), ObpFreeObjectNameBuffer(), ObpInsertHandleCount(), ObpLookupObjectName(), ObpParseSymbolicLink(), ObpRemoveObjectRoutine(), ObpWaitForMultipleObjects(), ObReleaseObjectSecurity(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObSetSecurityDescriptorInfo(), ObShutdownSystem(), PerfInfoFileNameRunDown(), PerfInfoProcessRunDown(), PerfInfoSysModuleRunDown(), Phase1InitializationDiscard(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), PspCaptureTokenFilter(), PspDeleteLdt(), PspDeleteVdmObjects(), PspDereferenceQuotaBlock(), PspExitApcRundown(), PspExitThread(), PspJobDelete(), PspNullSpecialApc(), PspProcessDelete(), PspQueueApcSpecialApc(), PspSetLdtInformation(), PspSetLdtSize(), PspSetQuotaLimits(), PspTerminateThreadByPointer(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawCheckForDismount(), RtlpAllocDeallocQueryBuffer(), RtlpComputeMergedAcl(), RtlpConvertAclToAutoInherit(), RtlpConvertToAutoInheritSecurityObject(), RtlpFreeAtom(), RtlpInheritAcl(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), RtlpSysVolFree(), SeAccessCheckByType(), SeAppendPrivileges(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCaptureAcl(), SeCaptureAuditPolicy(), SeCaptureLuidAndAttributesArray(), SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSecurityQos(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SeDeassignSecurity(), SeDeleteAccessState(), SeFreeCapturedObjectTypeList(), SeFreeCapturedSecurityQos(), SeFreePrivileges(), SeInitializeProcessAuditName(), SeLocateProcessImageName(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtLogAuditRecord(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAuditAssignPrimaryToken(), SepCleanupLUIDDeviceMapDirectory(), SepCreateLogonSessionTrack(), SepCreateToken(), SepDeleteLogonSessionTrack(), SepDequeueWorkItem(), SepDeReferenceLogonSession(), SepDuplicateToken(), SepExpandDynamic(), SepFilterToken(), SepFreeCapturedString(), SepFreeProxyData(), SepInformLsaOfDeletedLogon(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepNotifyFileSystems(), SepProbeAndCaptureQosData(), SepProbeAndCaptureString_U(), SepQueryNameString(), SepQueryTypeString(), SepRmCallLsa(), SepTokenDeleteMethod(), SeReleaseAcl(), SeReleaseAuditPolicy(), SeReleaseLuidAndAttributesArray(), SeReleaseSecurityDescriptor(), SeReleaseSid(), SeReleaseSidAndAttributesArray(), SeRmInitPhase1(), SeUnregisterLogonSessionTerminatedRoutine(), WmipAddLogHeader(), WmipAllocGuidEntryX(), WmipCheckGuidAccess(), WmipCheckIsWbemRunning(), WmipCreateAdminSD(), WmipCreateGuidObject(), WmipCreateLogFile(), WmipCreateNtFileName(), WmipCreatePumpThread(), WmipCreatePumpThreadRoutine(), WmipDelayCreate(), WmipDriverEntry(), WmipEventNotification(), WmipFireOffWmiEvent(), WmipFlushBuffersWithMarker(), WmipFreeLoggerContext(), WmipGECleanup(), WmipGenerateFileName(), WmipGenerateMCAEventlog(), WmipGetDevicePDO(), WmipGetGuidSecurityDescriptor(), WmipGetLogFromHal(), WmipInitializeSecurity(), WmipProcessEvent(), WmipProcessPrevMcaLogs(), WmipPumpThreadApc(), WmipQueryLogAndFireEvent(), WmipQueueNotification(), WmipRegisterOrUpdateDS(), WmipSecurityMethod(), WmipStartLogger(), WmipSwitchToNewFile(), WmipTraceFile(), WmipTraceIo(), WmiStartTrace(), WmiTraceProcess(), and xHalGetPartialGeometry().
VOID ExFreePoolSanityChecks (IN PVOID P)
Definition at line 6201 of file pool.c.
References APC_LEVEL, _POOL_HEADER::BlockSize, BYTE_OFFSET, DISPATCH_LEVEL, DRIVER_VERIFIER_DETECTED_VIOLATION, ExpCheckForResource(), ExpCheckForWorker(), ExpPoolFlags, IS_POOL_HEADER_MARKED_ALLOCATED, KeBugCheckEx(), KeCheckForTimer(), KeGetCurrentIrql(), MM_HIGHEST_USER_ADDRESS, MmDeterminePoolType(), MmIsSpecialPoolAddress(), NULL, PAGE_ALIGNED, PAGE_SIZE, PagedPool, POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_TYPE_MASK, _POOL_HEADER::PoolType, and _POOL_HEADER::Ulong1.
NTKERNELAPI VOID ExFreePoolWithTag (__in PVOID P, __in ULONG Tag)
Definition at line 4297 of file pool.c.
References ASSERT, ASSERT_FREE_IRQL, ASSERT_POOL_NOT_FREE, ASSERT_POOL_TYPE_NOT_ZERO, BAD_POOL_CALLER, BAD_POOL_HEADER, BASE_POOL_TYPE_MASK, _POOL_HEADER::BlockSize, CHECK_LIST, CHECK_POOL_PAGE, _KNODE::Color, DECODE_POOL_INDEX, DecodeLink, EX_CHECK_POOL_FREES_FOR_ACTIVE_RESOURCES, EX_CHECK_POOL_FREES_FOR_ACTIVE_TIMERS, EX_CHECK_POOL_FREES_FOR_ACTIVE_WORKERS, EX_DELAY_POOL_FREES, EX_FREE_POOL_BACKTRACE_LENGTH, EX_KERNEL_VERIFIER_ENABLED, EX_VERIFIER_DEADLOCK_DETECTION_ENABLED, ExDeferredFreePool(), ExFreePoolIndex, ExFreePoolMask, EXP_MAXIMUM_POOL_FREES_PENDING, ExpFindAndRemoveTagBigPages(), ExpGetBilledProcess(), ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExpPoolFlags, ExpRemovePoolTracker(), ExpRemovePoolTrackerInline(), ExpSessionPoolDescriptor, ExpSessionPoolLookaside, ExpSessionPoolSmallLists, ExQueryDepthSList, FALSE, FREE_CHECK_ERESOURCE, FREE_CHECK_KTIMER, FREE_CHECK_WORKER, Index, InterlockedCompareExchangePointer, InterlockedDecrement, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedIncrement, InterlockedPushEntrySList(), IS_POOL_HEADER_MARKED_ALLOCATED, KeBugCheckEx(), KeGetCurrentPrcb(), KeNumberNodes, _PP_LOOKASIDE_LIST::L, _POOL_DESCRIPTOR::ListHeads, LOCK_POOL, MARK_POOL_HEADER_FREED, MiFreePoolPages(), MiIsPoolLargeSession(), MmDeterminePoolType(), MmFreeSpecialPool(), MmGetSizeOfBigPoolAllocation(), MmIsSpecialPoolAddress(), NonPagedPool, NonPagedPoolSession, NULL, NumberOfBytes, ObDereferenceObject(), _KLOCK_QUEUE_HANDLE::OldIrql, _PP_LOOKASIDE_LIST::P, PAGE_ALIGN, PAGE_ALIGNED, PAGE_END, PAGE_SHIFT, PAGE_SIZE, PagedPool, PagedPoolSession, _KPRCB::ParentNode, _POOL_DESCRIPTOR::PendingFreeDepth, _POOL_DESCRIPTOR::PendingFrees, PERFINFO_FREEPOOL, PERFINFO_FREEPOOLPAGE, POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_SMALL_LISTS, POOL_SMALLEST_BLOCK, POOL_TYPE_MASK, POOL_VERIFIER_MASK, _EX_FREE_POOL_TRACES::PoolAddress, _EX_FREE_POOL_TRACES::PoolHeader, _POOL_DESCRIPTOR::PoolIndex, _POOL_HEADER::PoolIndex, _POOL_HEADER::PoolTag, _POOL_HEADER::PoolType, _KPRCB::PPNPagedLookasideList, _KPRCB::PPPagedLookasideList, _POOL_HEADER::PreviousSize, PrivateInsertHeadList, PrivateRemoveEntryList, PROTECTED_POOL, PsGetCurrentThread(), PSLIST_ENTRY, PsReturnPoolQuota(), ReadForWriteAccess, RtlCaptureStackBackTrace(), RtlZeroMemory, _POOL_DESCRIPTOR::RunningDeAllocs, SESSION_POOL_MASK, _EX_FREE_POOL_TRACES::StackTrace, Tag, _EX_FREE_POOL_TRACES::Thread, _POOL_DESCRIPTOR::TotalBigPages, _POOL_DESCRIPTOR::TotalBytes, _GENERAL_LOOKASIDE::TotalFrees, _POOL_DESCRIPTOR::TotalPages, TRUE, _POOL_HEADER::Ulong1, UNLOCK_POOL, UNREFERENCED_PARAMETER, USING_HOT_COLD_METRICS, VerifierDeadlockFreePool(), and VerifierFreeTrackedPool().
Referenced by ExFreePool().
__inline VOID ExFreeToNPagedLookasideList (IN PNPAGED_LOOKASIDE_LIST Lookaside, IN PVOID Entry)
Definition at line 1746 of file ex.h.
References ExInterlockedPushEntrySList, ExQueryDepthSList, InterlockedPushEntrySList(), and PSLIST_ENTRY.
Referenced by FsRtlFreeExclusiveLock(), FsRtlFreeLockInfo(), FsRtlFreeLockTreeNode(), FsRtlFreeSharedLock(), FsRtlFreeWaitingLock(), and WmipDoUnreferenceRegEntry().
__inline VOID ExFreeToPagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside, __in PVOID Entry)
Definition at line 1919 of file ex.h.
References ExQueryDepthSList, InterlockedPushEntrySList(), and PSLIST_ENTRY.
Referenced by FsRtlFreeFileLock(), FsRtlFreeTunnelNode(), and LpcpFreeToPortZone().
FORCEINLINE VOID ExFreeToPPLookasideList (IN PP_NPAGED_LOOKASIDE_NUMBER Number, IN PVOID Entry)
Definition at line 2060 of file ex.h.
References ASSERT, ExQueryDepthSList, InterlockedPushEntrySList(), KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, LookasideMaximumList, _PP_LOOKASIDE_LIST::P, _KPRCB::PPLookasideList, PSLIST_ENTRY, and _GENERAL_LOOKASIDE::TotalFrees.
Referenced by IoFreeMdl(), and ObpFreeObjectNameBuffer().
NTKERNELAPI VOID FASTCALL ExfReInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
Definition at line 124 of file rundown.c.
References ASSERT, EX_RUNDOWN_ACTIVE, InterlockedExchangePointer, NULL, and PAGED_CODE.
NTKERNELAPI VOID FASTCALL ExfReleasePushLock (__inout PEX_PUSH_LOCK PushLock)
Definition at line 955 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_SHARE_INC, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, InterlockedDecrement, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::MultipleShared, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExpInitializePushLocks(), and ExReleasePushLock().
NTKERNELAPI VOID FASTCALL ExfReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
Definition at line 900 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExAcquireReleasePushLockExclusive(), and ExpInitializePushLocks().
NTKERNELAPI VOID FASTCALL ExfReleasePushLockShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 806 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_SHARE_INC, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, InterlockedDecrement, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::MultipleShared, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExpInitializePushLocks(), ExReleasePushLockShared(), and ExReleasePushLockSharedAssumeSingleOwner().
NTKERNELAPI VOID FASTCALL ExfReleaseRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 287 of file rundown.c.
References ASSERT, _EX_RUNDOWN_WAIT_BLOCK::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, FASTCALL, InterlockedCompareExchangePointer, InterlockedDecrement, KeNumberProcessors, KeSetEvent(), NTKERNELAPI, TRUE, VOID, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
Referenced by ExReleaseRundownProtection().
NTKERNELAPI VOID FASTCALL ExfRundownCompleted (__out PEX_RUNDOWN_REF RunRef)
Definition at line 152 of file rundown.c.
References ASSERT, EX_RUNDOWN_ACTIVE, InterlockedExchangePointer, and PAGED_CODE.
NTKERNELAPI BOOLEAN FASTCALL ExfTryAcquirePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN FASTCALL ExfTryAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 753 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, FALSE, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waiting.
Referenced by ExTryAcquirePushLockShared().
NTKERNELAPI VOID FASTCALL ExfTryToWakePushLock (__inout PEX_PUSH_LOCK PushLock)
Definition at line 345 of file pushlock.c.
References EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExReleasePushLockExclusive().
NTKERNELAPI VOID FASTCALL ExfUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout_opt PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Definition at line 1213 of file pushlock.c.
References DISPATCH_LEVEL, EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, ExWaitForUnblockPushLock(), InterlockedBitTestAndReset(), InterlockedExchangePointer, KeLowerIrql, KeRaiseIrql, KeSetEventBoostPriority(), NULL, and _EX_PUSH_LOCK::Ptr.
Referenced by ExTimedWaitForUnblockPushLock(), and ExUnblockPushLock().
NTKERNELAPI VOID FASTCALL ExfWaitForRundownProtectionRelease (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 457 of file rundown.c.
References ASSERT, _EX_RUNDOWN_WAIT_BLOCK::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_SHIFT, Executive, FALSE, InterlockedCompareExchangePointer, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NULL, PAGED_CODE, SynchronizationEvent, TRUE, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
Referenced by ExWaitForRundownProtectionRelease().
PVOID ExGetCallBackBlockContext (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 1087 of file callback.c.
Referenced by CmpCallCallBacks(), and CmUnRegisterCallback().
PEX_CALLBACK_FUNCTION ExGetCallBackBlockRoutine (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 1064 of file callback.c.
Referenced by CmpCallCallBacks(), PsCallImageNotifyRoutines(), PspCreateThread(), PspExitProcess(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
NTKERNELAPI VOID ExGetCurrentProcessorCounts (__out PULONG IdleCount, __out PULONG KernelAndUser, __out PULONG Index)
Definition at line 6170 of file sysinfo.c.
References _KPRCB::IdleThread, KeGetCurrentPrcb(), _KPRCB::KernelTime, _KTHREAD::KernelTime, _KPRCB::Number, and _KPRCB::UserTime.
NTKERNELAPI VOID ExGetCurrentProcessorCpuUsage (__out PULONG CpuUsage)
Definition at line 6142 of file sysinfo.c.
References _KPRCB::IdleThread, KeGetCurrentPrcb(), _KPRCB::KernelTime, _KTHREAD::KernelTime, UInt32x32To64, and _KPRCB::UserTime.
NTKERNELAPI ULONG ExGetExclusiveWaiterCount (__in PERESOURCE Resource)
Definition at line 2221 of file resource.c.
VOID ExGetNextWakeTime (OUT PULONGLONG DueTime, OUT PTIME_FIELDS TimeFields, OUT PVOID * TimerObject)
Definition at line 1218 of file timer.c.
References CONTAINING_RECORD, ExAcquireSpinLock, ExpWakeTimerListLock, ExReleaseSpinLock, ExSystemTimeToLocalTime(), _LIST_ENTRY::Flink, KeQueryInterruptTime(), KeQuerySystemTime(), KeQueryTimerDueTime(), _ETIMER::KeTimer, NULL, _LARGE_INTEGER::QuadPart, RemoveEntryList(), RtlTimeToTimeFields(), _ETIMER::WakeTimer, and _ETIMER::WakeTimerListEntry.
NTKERNELAPI KPROCESSOR_MODE ExGetPreviousMode (VOID)
Definition at line 526 of file exinit.c.
References KeGetPreviousMode.
NTKERNELAPI ULONG ExGetSharedWaiterCount (__in PERESOURCE Resource)
Definition at line 2248 of file resource.c.
VOID ExInitializeCallBack (IN OUT PEX_CALLBACK CallBack)
Definition at line 777 of file callback.c.
References ExFastRefInitialize(), and NULL.
Referenced by CmpInitCallback(), and PspInitPhase0().
VOID ExInitializeCallData (IN PCALL_PERFORMANCE_DATA CallData)
Definition at line 22 of file callperf.c.
References CALL_HASH_TABLE_SIZE, Index, InitializeListHead(), and KeInitializeSpinLock().
NTKERNELAPI VOID ExInitializeHandleTablePackage (VOID)
Definition at line 795 of file handle.c.
References ExInitializePushLock(), and InitializeListHead().
Referenced by ExpInitializeExecutive().
PVOID ExInitializeNBQueueHead (IN PSLIST_HEADER SlistHead)
Definition at line 136 of file nbqueue.c.
References _NBQUEUE_POINTER::Count, _NBQUEUE_POINTER::Data, ExAllocatePoolWithTag, ExFreePool(), _NBQUEUE_HEADER::Head, InterlockedPopEntrySList(), _NBQUEUE_NODE::Next, NonPagedPool, NULL, PackNBQPointer(), _NBQUEUE_HEADER::SlistHead, _NBQUEUE_HEADER::Tail, and _NBQUEUE_NODE::Value.
Referenced by MiInitializeSystemPtes().
NTKERNELAPI VOID ExInitializeNPagedLookasideList (__out PNPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
Definition at line 493 of file lookasid.c.
References ExAllocatePoolWithTag, ExFreePool(), ExInterlockedInsertTailList(), ExMinimumLookasideDepth, ExNPagedLookasideLock, InitializeSListHead(), NonPagedPool, NULL, Tag, and UNREFERENCED_PARAMETER.
Referenced by FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcbs(), and WmipInitializeRegistration().
NTKERNELAPI VOID ExInitializePagedLookasideList (__out PPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
Definition at line 628 of file lookasid.c.
References ExAllocatePoolWithTag, ExFreePool(), ExInterlockedInsertTailList(), ExMinimumLookasideDepth, ExPagedLookasideLock, InitializeSListHead(), NULL, PAGED_CODE, PagedPool, Tag, and UNREFERENCED_PARAMETER.
Referenced by FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcbs(), FsRtlInitializeTunnels(), LpcpInitializePortZone(), and MmSessionCreate().
VOID FORCEINLINE ExInitializePushLock (__out PEX_PUSH_LOCK PushLock)
Definition at line 6996 of file ex.h.
Referenced by CcInitializeCacheMap(), CmInitSystem1(), CmpInitializeCache(), CmpInitializeHive(), CmRegisterCallback(), ExAllocateCacheAwarePushLock(), ExInitializeHandleTablePackage(), ExpAllocateHandleTable(), ExpInitializeCallbacks(), ExpInitializePushLocks(), MiSessionInitializeWorkingSetList(), MmInitializeHandBuiltProcess(), MmInitializeProcessAddressSpace(), MmInitSystem(), NtCreateDirectoryObject(), NtCreateKeyedEvent(), ObInitSystem(), ObpInitSecurityDescriptorCache(), PsLocateSystemDll(), PspInitializeProcessLock(), PspInitializeThreadLock(), and RtlpInitializeLockAtomTable().
NTKERNELAPI NTSTATUS ExInitializeResourceLite (__out PERESOURCE Resource)
Definition at line 435 of file resource.c.
References ASSERT, FLG_KERNEL_STACK_TRACE_DB, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeInitializeSpinLock(), KeReleaseInStackQueuedSpinLock(), MmDeterminePoolType(), NonPagedPool, NtGlobalFlag, RtlLogStackBackTrace(), RtlZeroMemory, and STATUS_SUCCESS.
Referenced by CcAllocateInitializeBcb(), CmInitSystem1(), CmpInitializeHive(), ExpInitSystemPhase0(), FsRtlInitSystem(), IoInitSystem(), IopInitializeBootLogging(), MiInitializeLoadedModuleList(), MmInitSystem(), NtCreateJobObject(), ObCreateObjectType(), Psp386CreateVdmIoListHead(), PspVdmInitialize(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), SepInitializeWorkList(), and SepRmDbInitialization().
NTKERNELAPI VOID FORCEINLINE FASTCALL ExInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
Definition at line 6182 of file ex.h.
Referenced by ExAllocateCacheAwareRundownProtection(), ExAllocateCallBack(), ExInitializeRundownProtectionCacheAware(), PspCreateProcess(), PspCreateThread(), and PspInitPhase0().
NTKERNELAPI VOID ExInitializeRundownProtectionCacheAware (__out PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in SIZE_T RunRefSize)
Definition at line 771 of file rundown.c.
References ExInitializeRundownProtection(), EXP_ALIGN_UP_PTR_ON_BOUNDARY, EXP_GET_PROCESSOR_RUNDOWN_REF(), Index, KeGetRecommendedSharedDataAlignment(), PAGED_CODE, and UintToPtr.
VOID ExInitializeSystemLookasideList (IN PGENERAL_LOOKASIDE Lookaside, IN POOL_TYPE Type, IN ULONG Size, IN ULONG Tag, IN USHORT Depth, IN PLIST_ENTRY ListHead)
Definition at line 555 of file exinit.c.
References ExAllocatePoolWithTag, ExFreePool(), ExInitializeSListHead, InsertTailList(), and Tag.
Referenced by CcInitializeCacheManager(), ExpInitSystemPhase0(), ExpInitSystemPhase1(), IoInitSystem(), and ObInitSystem().
NTKERNELAPI VOID ExInitializeTimeRefresh (VOID)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS ExInitializeZone (__out PZONE_HEADER Zone, __in ULONG BlockSize, __inout PVOID InitialSegment, __in ULONG InitialSegmentSize)
Definition at line 46 of file zone.c.
References DbgBreakPoint(), DbgPrint(), NULL, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
VOID ExInitPoolLookasidePointers (VOID)
Definition at line 48 of file exinit.c.
References ExInitializeSListHead, ExpSmallNPagedPoolLookasideLists, ExpSmallPagedPoolLookasideLists, Index, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, _PP_LOOKASIDE_LIST::P, POOL_SMALL_LISTS, _KPRCB::PPNPagedLookasideList, and _KPRCB::PPPagedLookasideList.
Referenced by ExpInitializeExecutive(), and KiInitializeBootStructures().
NTKERNELAPI BOOLEAN ExInitSystem (VOID)
Definition at line 100 of file exinit.c.
References ExpInitSystemPhase0(), ExpInitSystemPhase1(), ExpSystemOK(), FALSE, InitializationPhase, KeBugCheckEx(), TRUE, and UNEXPECTED_INITIALIZATION_CALL.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
VOID ExInitSystemPhase2 (VOID)
Referenced by Phase1InitializationDiscard().
VOID ExInsertPoolTag (ULONG Tag, PVOID Va, SIZE_T NumberOfBytes, POOL_TYPE PoolType)
Definition at line 3232 of file pool.c.
References ASSERT, BYTES_TO_PAGES, ExpAddTagForBigPages(), ExpInsertPoolTracker(), FALSE, NonPagedPool, PAGE_SIZE, SESSION_POOL_MASK, and UNREFERENCED_PARAMETER.
Referenced by MiFindContiguousMemoryInPool().
BOOLEAN ExInsertTailNBQueue (IN PVOID Header, IN ULONG64 Value)
Definition at line 214 of file nbqueue.c.
References _NBQUEUE_POINTER::Count, _NBQUEUE_POINTER::Data, FALSE, InterlockedCompareExchange64, InterlockedPopEntrySList(), _NBQUEUE_NODE::Next, NULL, PackNBQPointer(), ReadForWriteAccess, _NBQUEUE_HEADER::SlistHead, _NBQUEUE_HEADER::Tail, TRUE, UnpackNBQPointer(), and _NBQUEUE_NODE::Value.
Referenced by MiReleaseSystemPtes(), and MmUnmapLockedPages().
NTKERNELAPI LARGE_INTEGER ExInterlockedAddLargeInteger (__inout PLARGE_INTEGER Addend, __in LARGE_INTEGER Increment, __inout PKSPIN_LOCK Lock)
NTKERNELAPI ULONG FASTCALL ExInterlockedAddUlong (__inout PULONG Addend, __in ULONG Increment, __inout PKSPIN_LOCK Lock)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS ExInterlockedExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize, __inout PKSPIN_LOCK Lock)
Definition at line 197 of file zone.c.
References ExAcquireSpinLock, ExExtendZone(), ExReleaseSpinLock, Status, and UNREFERENCED_PARAMETER.
NTKERNELAPI PSLIST_ENTRY FASTCALL ExInterlockedFlushSList (__inout PSLIST_HEADER ListHead)
Referenced by MiInsertPteTracker(), and WmipFlushActiveBuffers().
NTKERNELAPI PLIST_ENTRY FASTCALL ExInterlockedInsertHeadList (__inout PLIST_ENTRY ListHead, __inout PLIST_ENTRY ListEntry, __inout PKSPIN_LOCK Lock)
Referenced by CcCanIWrite(), and CcDeferWrite().
NTKERNELAPI PLIST_ENTRY FASTCALL ExInterlockedInsertTailList (__inout PLIST_ENTRY ListHead, __inout PLIST_ENTRY ListEntry, __inout PKSPIN_LOCK Lock)
Referenced by CcCanIWrite(), CcDeferWrite(), ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), IoInitializeTimer(), IoWMIWriteEvent(), and WmipAllocRegEntry().
NTKERNELAPI PSINGLE_LIST_ENTRY FASTCALL ExInterlockedPopEntryList (__inout PSINGLE_LIST_ENTRY ListHead, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PSINGLE_LIST_ENTRY FASTCALL ExInterlockedPushEntryList (__inout PSINGLE_LIST_ENTRY ListHead, __inout PSINGLE_LIST_ENTRY ListEntry, __inout PKSPIN_LOCK Lock)
NTKERNELAPI PLIST_ENTRY FASTCALL ExInterlockedRemoveHeadList (__inout PLIST_ENTRY ListHead, __inout PKSPIN_LOCK Lock)
Referenced by WmipDoUnreferenceRegEntry(), and WmipEventNotification().
NTKERNELAPI BOOLEAN ExIsProcessorFeaturePresent (__in ULONG ProcessorFeature)
Definition at line 6047 of file sysinfo.c.
References FALSE, PF_3DNOW_INSTRUCTIONS_AVAILABLE, PF_MMX_INSTRUCTIONS_AVAILABLE, PROCESSOR_FEATURE_MAX, and SharedUserData.
NTKERNELAPI BOOLEAN ExIsResourceAcquiredExclusiveLite (__in PERESOURCE Resource)
Definition at line 2277 of file resource.c.
References ASSERT_RESOURCE, FALSE, IsOwnedExclusive, PsGetCurrentThread(), and TRUE.
Referenced by CmpDoFileSetSize(), and CmpUnlockRegistry().
NTKERNELAPI ULONG ExIsResourceAcquiredSharedLite (__in PERESOURCE Resource)
Definition at line 2326 of file resource.c.
References ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, Index, IsOwnedExclusive, NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and _OWNER_ENTRY::TableSize.
Referenced by FsRtlAcquireFileForCcFlushEx().
NTKERNELAPI VOID ExLocalTimeToSystemTime (__in PLARGE_INTEGER LocalTime, __out PLARGE_INTEGER SystemTime)
Referenced by Phase1InitializationDiscard().
NTKERNELAPI KIRQL ExLockPool (__in POOL_TYPE PoolType)
NTKERNELAPI NTSTATUS ExLockUserBuffer (__inout_bcount(Length) PVOID Buffer, __in ULONG Length, __in KPROCESSOR_MODE ProbeMode, __in LOCK_OPERATION LockMode, __deref_out PVOID * LockedBuffer, __deref_out PVOID * LockVariable)
Definition at line 4124 of file sysinfo.c.
References ASSERT, ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExUnlockUserBuffer(), MDL_MAPPING_CAN_FAIL, _MDL::MdlFlags, MmGetSystemAddressForMdl, MmInitializeMdl, MmProbeAndLockPages(), MmSizeOfMdl(), NonPagedPool, NULL, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by ExGetSessionPoolTagInformation(), ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), and MmGetSessionMappedViewInformation().
NTKERNELAPI BOOLEAN ExLuidInitialization (VOID)
Definition at line 37 of file luid.c.
References TRUE.
Referenced by SepInitializationPhase0().
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointer (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle)
Definition at line 2015 of file handle.c.
References ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_BADREF, _EXHANDLE::Index, LOWLEVEL_COUNT, NULL, PAGED_CODE, and PsGetCurrentThread().
Referenced by ExpGetHandleInfo(), ExSetHandleInfo(), ObAuditObjectAccess(), ObDuplicateObject(), ObpCloseHandle(), ObpCreateHandle(), ObpReferenceProcessObjectByHandle(), ObQueryObjectAuditingByHandle(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), and RtlpAtomMapAtomToHandleEntry().
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointerEx (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
Definition at line 2084 of file handle.c.
References DbgPrint(), ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), FLG_APPLICATION_VERIFIER, FLG_ENABLE_HANDLE_EXCEPTIONS, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_BADREF, _EXHANDLE::Index, INVALID_KERNEL_HANDLE, KeBugCheckEx(), KeIsAttachedProcess(), KeRaiseUserException(), LOWLEVEL_COUNT, NtGlobalFlag, NULL, PAGED_CODE, PsGetCurrentProcess(), PsGetCurrentThread(), STATUS_INVALID_HANDLE, and UserMode.
Referenced by ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
NTKERNELAPI VOID ExNotifyCallback (__in PVOID CallbackObject, __in_opt PVOID Argument1, __in_opt PVOID Argument2)
NTKERNELAPI PHANDLE_TABLE_ENTRY_INFO ExpGetHandleInfo (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in BOOLEAN EntryLocked)
Definition at line 3810 of file handle.c.
References EX_ADDITIONAL_INFO_SIGNATURE, ExMapHandleToPointer(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, _EXHANDLE::Index, _HANDLE_TABLE_ENTRY::InfoTable, LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, and NULL.
NTKERNELAPI SIZE_T ExQueryPoolBlockSize (__in PVOID PoolBlock, __out PBOOLEAN QuotaCharged)
Definition at line 5317 of file pool.c.
References _POOL_HEADER::BlockSize, ExpGetBilledProcess(), ExpPoolFlags, FALSE, MmIsSpecialPoolAddress(), MmQuerySpecialPoolBlockSize(), PAGE_ALIGNED, PAGE_SIZE, POOL_BLOCK_SHIFT, POOL_OVERHEAD, and TRUE.
NTKERNELAPI VOID ExQueryPoolUsage (__out PULONG PagedPoolPages, __out PULONG NonPagedPoolPages, __out PULONG PagedPoolAllocs, __out PULONG PagedPoolFrees, __out PULONG PagedPoolLookasideHits, __out PULONG NonPagedPoolAllocs, __out PULONG NonPagedPoolFrees, __out PULONG NonPagedPoolLookasideHits)
Definition at line 5373 of file pool.c.
References CONTAINING_RECORD, ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExPoolLookasideListHead, _LIST_ENTRY::Flink, Index, NonPagedPool, NonPagedPoolDescriptor, _POOL_DESCRIPTOR::RunningAllocs, _POOL_DESCRIPTOR::RunningDeAllocs, _POOL_DESCRIPTOR::TotalBigPages, and _POOL_DESCRIPTOR::TotalPages.
Referenced by NtQuerySystemInformation().
NTKERNELAPI NTSTATUS ExQuerySystemLockInformation (__out_bcount(LockInformationLength) struct _RTL_PROCESS_LOCKS * LockInformation, __in ULONG LockInformationLength, __out_opt PULONG ReturnLength)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI VOID ExQueueWorkItem (__inout PWORK_QUEUE_ITEM WorkItem, __in WORK_QUEUE_TYPE QueueType)
Definition at line 489 of file worker.c.
References ASSERT, ExpNewThreadNecessary(), FALSE, _EX_WORK_QUEUE::Info, KeBugCheckEx(), KeInsertQueue(), KeSetEvent(), MaximumWorkQueue, MmUserProbeAddress, NULL, EX_QUEUE_WORKER_INFO::QueueDisabled, WORKER_INVALID, and _EX_WORK_QUEUE::WorkerQueue.
Referenced by CcPostWorkQueue(), CmpCanGrowSystemHive(), CmpDelayCloseDpcRoutine(), CmpDelayDerefKCBDpcRoutine(), CmpDiskFullWarning(), CmpDoQueueLateUnloadWorker(), CmpLazyFlushDpcRoutine(), CmpPostNotify(), CmpRaiseSelfHealWarning(), CmpRaiseSelfHealWarningWorker(), CmpUpdateSystemHiveHysteresis(), ExpWorkerThreadBalanceManager(), IopCompleteUnloadOrDelete(), IopErrorLogDpc(), IopSendMessageToTrackService(), IopUnloadDriver(), IoQueueWorkItem(), IoRaiseHardError(), IoRaiseInformationalHardError(), IoWMIWriteEvent(), IoWriteErrorLogEntry(), MiNoPagesLastChance(), MiReleaseSystemPtes(), MiStartZeroPageWorkers(), MiWriteComplete(), MiZeroAllPageFiles(), NtLoadDriver(), ObpDeferObjectDeletion(), PspJobTimeLimitsDpcRoutine(), SepInformFileSystemsOfDeletedLogon(), SepQueueWorkItem(), WmipInitializeRegistration(), WmipIsWbemRunningDispatch(), WmipMceDispatchRoutine(), WmipQueueNotification(), WmipQueueRegWork(), and WmipTraceIo().
NTKERNELAPI DECLSPEC_NORETURN VOID ExRaiseAccessViolation (VOID)
Definition at line 37 of file raise.c.
References ExRaiseStatus(), and STATUS_ACCESS_VIOLATION.
Referenced by ProbeForWrite().
NTKERNELAPI DECLSPEC_NORETURN VOID ExRaiseDatatypeMisalignment (VOID)
Definition at line 66 of file raise.c.
References ExRaiseStatus(), and STATUS_DATATYPE_MISALIGNMENT.
Referenced by ProbeForRead(), ProbeForWrite(), ProbeForWriteSmallStructure(), ProbeForWriteUlongAligned32(), and SeCaptureSecurityDescriptor().
NTKERNELAPI VOID NTAPI ExRaiseException (__in PEXCEPTION_RECORD ExceptionRecord)
Referenced by KiDispatchException().
NTKERNELAPI NTSTATUS ExRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
Definition at line 747 of file harderr.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, except, EXCEPTION_EXECUTE_HANDLER, ExpRaiseHardError(), ExpTooLateForErrors, MAXIMUM_HARDERROR_PARAMETERS, _UNICODE_STRING::MaximumLength, MEM_COMMIT, MEM_RELEASE, NT_SUCCESS, NtCurrentProcess, NULL, PAGE_READWRITE, PAGED_CODE, ResponseNotHandled, RtlCopyMemory, Status, STATUS_SUCCESS, ZwAllocateVirtualMemory(), and ZwFreeVirtualMemory().
Referenced by CmpDiskFullWarningWorker(), CmpLoadHiveThread(), CmpQuotaWarningWorker(), CmpRaiseSelfHealWarningWorker(), CmpSystemQuotaWarningWorker(), IopHardErrorThread(), IopRaiseHardError(), IopRaiseInformationalHardError(), and NtRaiseHardError().
NTKERNELAPI DECLSPEC_NORETURN VOID NTAPI ExRaiseStatus (__in NTSTATUS Status)
Referenced by __bcount(), _purecall(), BuildQueryDirectoryIrp(), CcAllocateObcb(), CcCopyRead(), CcCopyWrite(), CcFastCopyRead(), CcFastCopyWrite(), CcGetVacbMiss(), CcInitializeCacheMap(), CcMapAndCopy(), CcMdlRead(), CcMdlWriteComplete2(), CcPinFileData(), CcPrepareMdlWrite(), CcReferenceFileOffset(), CcSetFileSizes(), CcZeroData(), ExRaiseAccessViolation(), ExRaiseDatatypeMisalignment(), FsRtlAreNamesEqual(), FsRtlIsNameInExpression(), FsRtlpPostStackOverflow(), FsRtlPrivateInitializeFileLock(), FsRtlPrivateLock(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopCreateFile(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), KeReleaseMutant(), KeReleaseSemaphore(), KeSuspendThread(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), MiCheckForUserStackOverflow(), MiDoMappedCopy(), MiMapLockedPagesInUserSpace(), MmProbeAndLockPages(), MmProbeAndLockProcessPages(), MmProbeAndLockSelectedPages(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryMultipleValueKey(), NtQueryQuotaInformationFile(), NtQuerySystemInformation(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetSystemInformation(), NtSetUuidSeed(), NtWriteFile(), NtWriteFileGather(), and PsChargePoolQuota().
VOID ExRecordCallerInHashTable (IN PCALL_PERFORMANCE_DATA CallData, IN PVOID CallersAddress, IN PVOID CallersCaller)
Definition at line 59 of file callperf.c.
References CALL_HASH_TABLE_SIZE, _CALL_HASH_ENTRY::CallCount, _CALL_HASH_ENTRY::CallersAddress, _CALL_HASH_ENTRY::CallersCaller, CONTAINING_RECORD, ExAcquireSpinLock, ExAllocatePoolWithTag, ExReleaseSpinLock, _LIST_ENTRY::Flink, InitializationPhase, InsertTailList(), _CALL_HASH_ENTRY::ListEntry, NonPagedPool, and NULL.
PEX_CALLBACK_ROUTINE_BLOCK ExReferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack)
Definition at line 973 of file callback.c.
References ExAcquirePushLockExclusive(), ExAcquireRundownProtection(), ExAcquireRundownProtectionEx(), ExFastRefAddAdditionalReferenceCounts(), ExFastRefCanBeReferenced(), ExFastReference(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefIsLastReference(), ExFastRefObjectNull(), ExpCallBackReturnRefs, ExReleasePushLockExclusive(), ExReleaseRundownProtectionEx(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, and _EX_CALLBACK_ROUTINE_BLOCK::RundownProtect.
Referenced by CmpCallCallBacks(), CmUnRegisterCallback(), ExCallCallBack(), PsCallImageNotifyRoutines(), PspCreateThread(), PspExitProcess(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
PHANDLE_TRACE_DEBUG_INFO ExReferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable)
Definition at line 2285 of file handle.c.
References ASSERT, ExpLockHandleTableShared, ExpUnlockHandleTableShared, InterlockedIncrement, KeGetCurrentThread(), NULL, and _HANDLE_TRACE_DEBUG_INFO::RefCount.
Referenced by ExpUpdateDebugInfo(), and NtQueryInformationProcess().
NTKERNELAPI PVOID ExRegisterCallback (__inout PCALLBACK_OBJECT CallbackObject, __in PCALLBACK_FUNCTION CallbackFunction, __in_opt PVOID CallbackContext)
Definition at line 434 of file callback.c.
References ASSERT, _CALLBACK_REGISTRATION::Busy, _CALLBACK_REGISTRATION::CallbackContext, _CALLBACK_REGISTRATION::CallbackFunction, _CALLBACK_REGISTRATION::CallbackObject, DISPATCH_LEVEL, ExAllocatePoolWithTag, ExFreePool(), FALSE, InsertTailList(), IsListEmpty, KeAcquireSpinLock, KeGetCurrentIrql(), KeReleaseSpinLock(), _CALLBACK_REGISTRATION::Link, NonPagedPool, NULL, ObDereferenceObject(), ObReferenceObject, TRUE, and _CALLBACK_REGISTRATION::UnregisterWaiting.
NTKERNELAPI NTSTATUS ExReinitializeResourceLite (__inout PERESOURCE Resource)
Definition at line 486 of file resource.c.
References ASSERT, FALSE, Index, KeInitializeEvent(), KeInitializeSemaphore(), MAXLONG, MmDeterminePoolType(), NonPagedPool, NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, STATUS_SUCCESS, SynchronizationEvent, and _OWNER_ENTRY::TableSize.
NTKERNELAPI VOID FORCEINLINE FASTCALL ExReInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
Definition at line 6219 of file ex.h.
References ASSERT, EX_RUNDOWN_ACTIVE, InterlockedExchangePointer, NULL, and PAGED_CODE.
NTKERNELAPI VOID FASTCALL ExReInitializeRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 1114 of file rundown.c.
References ASSERT, _EX_RUNDOWN_REF::Count, EX_RUNDOWN_ACTIVE, EXP_GET_PROCESSOR_RUNDOWN_REF(), Index, InterlockedExchangePointer, NULL, and _EX_RUNDOWN_REF::Ptr.
NTKERNELAPI VOID ExReleaseCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE CacheAwarePushLock)
Definition at line 1447 of file pushlock.c.
References EX_PUSH_LOCK_FANNED_COUNT, ExReleasePushLockExclusive(), and KeNumberProcessors.
Referenced by MiAweViewInserter(), MiAweViewRemover(), MiProtectAweRegion(), MiRemoveUserPhysicalPagesVad(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
VOID FORCEINLINE ExReleaseCacheAwarePushLockShared (IN PEX_PUSH_LOCK PushLock)
Definition at line 7721 of file ex.h.
References ExReleasePushLockSharedAssumeSingleOwner().
Referenced by MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtMapUserPhysicalPages(), and NtMapUserPhysicalPagesScatter().
NTKERNELAPI VOID FASTCALL ExReleaseFastMutex (__inout PFAST_MUTEX FastMutex)
Definition at line 57 of file fmutexc.c.
References xxReleaseFastMutex().
Referenced by CcCopyWrite(), CcZeroEndOfLastPage(), DbgkClearProcessDebugObject(), DbgkCopyProcessDebugPort(), DbgkOpenProcessDebugPort(), DbgkpCloseObject(), DbgkpMarkProcessPeb(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), ExpUpdateDebugInfo(), ExSwapinWorkerThreads(), FsRtlAddToTunnelCache(), FsRtlCancelExclusiveIrp(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFindInTunnelCache(), FsRtlInsertPerFileObjectContext(), FsRtlInsertPerStreamContext(), FsRtlLookupPerFileObjectContext(), FsRtlLookupPerStreamContextInternal(), FsRtlRemovePerFileObjectContext(), FsRtlRemovePerStreamContext(), FsRtlTeardownPerStreamContexts(), KeGenericCallDpc(), NtDebugContinue(), NtSetInformationDebugObject(), NtWaitForDebugEvent(), and RtlpTraceDatabaseReleaseLock().
VOID FORCEINLINE ExReleasePushLock (IN PEX_PUSH_LOCK PushLock)
Definition at line 7417 of file ex.h.
References ASSERT, EX_PUSH_LOCK_SHARE_INC, ExfReleasePushLock(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waiting.
Referenced by ObLogSecurityDescriptor(), and ObpUnlockDirectory().
VOID FORCEINLINE ExReleasePushLockExclusive (IN PEX_PUSH_LOCK PushLock)
Definition at line 7458 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, ExfTryToWakePushLock(), InterlockedExchangeAdd(), _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by CcGetVirtualAddressIfMapped(), ExCreateHandleTable(), ExDupHandleTable(), ExReferenceCallBackBlock(), ExReleaseCacheAwarePushLockExclusive(), ExRemoveHandleTable(), ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), PsLocateSystemDll(), PspUnlockProcessExclusive(), PspUnlockThreadSecurityExclusive(), and RtlpUnlockAtomTable().
VOID FORCEINLINE ExReleasePushLockShared (IN PEX_PUSH_LOCK PushLock)
Definition at line 7505 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, ExfReleasePushLockShared(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waiting.
Referenced by CcGetVacbMiss(), CcGetVirtualAddress(), CcUnmapVacbArray(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ObLogSecurityDescriptor(), PsMapSystemDll(), PspUnlockProcessShared(), and PspUnlockThreadSecurityShared().
VOID FORCEINLINE ExReleasePushLockSharedAssumeSingleOwner (IN PEX_PUSH_LOCK PushLock)
Definition at line 7547 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, ExfReleasePushLockShared(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, NULL, _EX_PUSH_LOCK::Shared, and _EX_PUSH_LOCK::Waiting.
Referenced by ExReleaseCacheAwarePushLockShared().
NTKERNELAPI VOID FASTCALL ExReleaseResourceAndLeaveCriticalRegion (__inout PERESOURCE Resource)
Definition at line 1722 of file resource.c.
References ExReleaseResourceLite(), and KeLeaveCriticalRegion().
NTKERNELAPI VOID ExReleaseResourceForThreadLite (__inout PERESOURCE Resource, __in ERESOURCE_THREAD ResourceThreadId)
Definition at line 1751 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, Index, IsExclusiveWaiting, IsOwnedExclusive, IsSharedWaiting, KeBugCheckEx(), KeGetCurrentThread(), KeReleaseSemaphore(), KeSetEventBoostPriority(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, RESOURCE_NOT_OWNED, ResourceOwnedExclusive, and _OWNER_ENTRY::TableSize.
Referenced by CcUnpinDataForThread().
NTKERNELAPI VOID FASTCALL ExReleaseResourceLite (__inout PERESOURCE Resource)
Definition at line 1485 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, Index, IsExclusiveWaiting, IsOwnedExclusive, IsSharedWaiting, KeBugCheckEx(), KeGetCurrentThread(), KeReleaseSemaphore(), KeSetEventBoostPriority(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), RESOURCE_NOT_OWNED, ResourceOwnedExclusive, and _OWNER_ENTRY::TableSize.
Referenced by CcUnpinFileDataEx(), CmpUnlockRegistry(), ExpGetSystemFirmwareTableInformation(), ExpRegisterFirmwareTableInformationHandler(), ExReleaseResourceAndLeaveCriticalRegion(), FsRtlAcquireFileForModWriteEx(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), FsRtlReleaseFileForModWrite(), IoEnumerateRegisteredFiltersList(), IopBootLog(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopGetSetSecurityObject(), IopInitializeBootLogging(), IopInvalidateVolumesForDevice(), IopLoadDriver(), IopMountVolume(), IopParseDevice(), IopSetDeviceSecurityDescriptor(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoUnregisterFileSystem(), IoUnregisterFsRegistrationChange(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiProcessLoaderEntry(), MmExtendSection(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmInitSystem(), MmLockPageableDataSection(), NtAssignProcessToJobObject(), NtQueryInformationJobObject(), NtQuerySystemInformation(), NtSetInformationJobObject(), NtSetInformationProcess(), ObpUnlockAllObjects(), Ps386GetVdmIoHandler(), PsEnforceExecutionTimeLimits(), PsGetNextJobProcess(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspAddProcessToJob(), PspCreateThread(), PspExitProcess(), PspExitProcessFromJob(), PspJobClose(), PspJobDelete(), PspRemoveProcessFromJob(), PspSetQuotaLimits(), and PspTerminateAllProcessesInJob().
NTKERNELAPI VOID FORCEINLINE FASTCALL ExReleaseRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 6292 of file ex.h.
References ASSERT, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, ExfReleaseRundownProtection(), InterlockedCompareExchangePointerRelease, KeNumberProcessors, and ReadForWriteAccess.
Referenced by DbgkpMarkProcessPeb(), DbgkpPostFakeThreadMessages(), DbgkpSetProcessDebugObject(), DbgkpWakeTarget(), ExDereferenceCallBackBlock(), ExReleaseRundownProtectionCacheAware(), MmCopyVirtualMemory(), NtAssignProcessToJobObject(), NtDebugActiveProcess(), NtQueryInformationProcess(), NtSetInformationProcess(), NtSetInformationThread(), NtTerminateProcess(), ObDereferenceProcessHandleTable(), ObReferenceProcessHandleTable(), PspCreateProcess(), PspCreateThread(), PspWriteTebImpersonationInfo(), PsReferenceProcessFilePointer(), PsResumeProcess(), PsSuspendProcess(), and PsSuspendThread().
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 905 of file rundown.c.
References EXP_GET_CURRENT_RUNDOWN_REF(), and ExReleaseRundownProtection().
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRef, __in ULONG Count)
Definition at line 959 of file rundown.c.
References EXP_GET_CURRENT_RUNDOWN_REF(), and ExReleaseRundownProtectionEx().
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
Definition at line 369 of file rundown.c.
References ASSERT, Count, _EX_RUNDOWN_WAIT_BLOCK::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, FASTCALL, InterlockedCompareExchangePointer, InterlockedExchangeAdd(), KeNumberProcessors, KeSetEvent(), NTKERNELAPI, TRUE, VOID, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
Referenced by ExCompareExchangeCallBack(), ExReferenceCallBackBlock(), and ExReleaseRundownProtectionCacheAwareEx().
FORCEINLINE VOID ExReleaseSpinLockExclusive (IN PEX_SPIN_LOCK SpinLock, IN KIRQL OldIrql)
Definition at line 950 of file ex.h.
References ASSERT, DISPATCH_LEVEL, EXP_SPIN_LOCK_EXCLUSIVE, KeGetCurrentIrql(), KeLowerIrql, and KeMemoryBarrierWithoutFence.
Referenced by ExGetBigPoolInfo(), and ExpExpandBigPageTable().
FORCEINLINE VOID ExReleaseSpinLockShared (IN PEX_SPIN_LOCK SpinLock, IN KIRQL OldIrql)
Definition at line 844 of file ex.h.
References ASSERT, DISPATCH_LEVEL, InterlockedDecrementRelease, KeGetCurrentIrql(), and KeLowerIrql.
Referenced by ExAcquireSpinLockExclusive(), ExpAddTagForBigPages(), and ExpFindAndRemoveTagBigPages().
VOID ExReleaseTimeRefreshLock (VOID)
NTKERNELAPI VOID ExRemoveHandleTable (__inout PHANDLE_TABLE HandleTable)
Definition at line 893 of file handle.c.
References ExAcquirePushLockExclusive(), ExReleasePushLockExclusive(), InitializeListHead(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), PAGED_CODE, and RemoveEntryList().
Referenced by ExDestroyHandleTable(), PspInitPhase0(), and RtlpInitializeHandleTableForAtomTable().
BOOLEAN ExRemoveHeadNBQueue (IN PVOID Header, OUT PULONG64 Value)
Definition at line 339 of file nbqueue.c.
References _NBQUEUE_POINTER::Count, _NBQUEUE_POINTER::Data, FALSE, _NBQUEUE_HEADER::Head, InterlockedCompareExchange64, InterlockedPushEntrySList(), _NBQUEUE_NODE::Next, NULL, PackNBQPointer(), PSLIST_ENTRY, ReadForWriteAccess, _NBQUEUE_HEADER::SlistHead, _NBQUEUE_HEADER::Tail, TRUE, UnpackNBQPointer(), and _NBQUEUE_NODE::Value.
Referenced by MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
VOID ExReturnPoolQuota (IN PVOID P)
Definition at line 5449 of file pool.c.
References _POOL_HEADER::BlockSize, ExpGetBilledProcess(), ExpPoolFlags, InterlockedDecrement, MmIsSpecialPoolAddress(), NULL, ObDereferenceObject(), POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_TYPE_MASK, _POOL_HEADER::PoolType, and PsReturnPoolQuota().
Referenced by IopFreeIrp(), and IopFreeMiniPacket().
NTKERNELAPI VOID FORCEINLINE FASTCALL ExRundownCompleted (__out PEX_RUNDOWN_REF RunRef)
Definition at line 6331 of file ex.h.
References ASSERT, EX_RUNDOWN_ACTIVE, InterlockedExchangePointer, and PAGED_CODE.
Referenced by ObKillProcess().
NTKERNELAPI VOID FASTCALL ExRundownCompletedCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 1147 of file rundown.c.
References ASSERT, _EX_RUNDOWN_REF::Count, EX_RUNDOWN_ACTIVE, EXP_GET_PROCESSOR_RUNDOWN_REF(), Index, InterlockedExchangePointer, and _EX_RUNDOWN_REF::Ptr.
NTKERNELAPI NTSTATUS ExSetHandleInfo (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PHANDLE_TABLE_ENTRY_INFO EntryInfo, __in BOOLEAN EntryLocked)
Definition at line 3682 of file handle.c.
References EX_ADDITIONAL_INFO_SIGNATURE, ExMapHandleToPointer(), ExpAllocateTablePagedPool(), ExpFreeTablePagedPool(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, _EXHANDLE::Index, _HANDLE_TABLE_ENTRY::InfoTable, InterlockedCompareExchangePointer, InterlockedIncrement, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, Status, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
Referenced by ExDupHandleTable(), ObDuplicateObject(), and ObpCreateHandle().
VOID ExSetHandleTableStrictFIFO (IN PHANDLE_TABLE HandleTable)
Definition at line 3365 of file handle.c.
References TRUE.
Referenced by ObInitSystem(), and PspInitPhase0().
NTKERNELAPI VOID ExSetResourceOwnerPointer (__inout PERESOURCE Resource, __in PVOID OwnerPointer)
Definition at line 1980 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpFindCurrentThread(), IsOwnedExclusive, KeBugCheckEx(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and RESOURCE_NOT_OWNED.
Referenced by CcSetBcbOwnerPointer().
NTKERNELAPI ULONG ExSetTimerResolution (__in ULONG DesiredTime, __in BOOLEAN SetResolution)
VOID ExShutdownSystem (IN ULONG Phase)
NTKERNELAPI SIZE_T ExSizeOfRundownProtectionCacheAware (VOID)
Definition at line 719 of file rundown.c.
References KeGetRecommendedSharedDataAlignment(), KeNumberProcessors, and PAGED_CODE.
NTKERNELAPI NTSTATUS ExSnapShotHandleTables (__in PEX_SNAPSHOT_HANDLE_ENTRY SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
Definition at line 1437 of file handle.c.
References CONTAINING_RECORD, ExAcquirePushLockShared(), ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExReleasePushLockShared(), ExUnlockHandleTableEntry(), _LIST_ENTRY::Flink, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, Status, STATUS_SUCCESS, _HANDLE_TABLE::UniqueProcessId, and _EXHANDLE::Value.
Referenced by ObGetHandleInformation().
NTKERNELAPI NTSTATUS ExSnapShotHandleTablesEx (__in PEX_SNAPSHOT_HANDLE_ENTRY_EX SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION_EX HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
Definition at line 1583 of file handle.c.
References CONTAINING_RECORD, ExAcquirePushLockShared(), ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExReleasePushLockShared(), ExUnlockHandleTableEntry(), _LIST_ENTRY::Flink, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, Status, STATUS_SUCCESS, _HANDLE_TABLE::UniqueProcessId, and _EXHANDLE::Value.
Referenced by ObGetHandleInformationEx().
VOID ExSwapinWorkerThreads (IN BOOLEAN AllowSwap)
Definition at line 1336 of file worker.c.
References ExAcquireFastMutex(), Executive, ExpSetSwappingKernelApc(), ExpWorkersCanSwap, ExReleaseFastMutex(), _ETHREAD::ExWorkerCanWaitUser, FALSE, InsertApcEnvironment, KeClearEvent(), KeInitializeApc(), KeInitializeEvent(), KeInsertQueueApc(), KernelMode, KeSetKernelStackSwapEnable(), KeWaitForSingleObject(), NotificationEvent, NULL, PAGED_CODE, PsGetCurrentThread(), PsGetNextProcessThread(), PsInitialSystemProcess, _ETHREAD::Tcb, and _EXP_WORKER_LINK::Thread.
NTKERNELAPI VOID ExSweepHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter)
Definition at line 1026 of file handle.c.
References ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, LOWLEVEL_COUNT, NULL, PAGED_CODE, and _EXHANDLE::Value.
Referenced by ObClearProcessHandleTable(), and ObKillProcess().
int ExSystemExceptionFilter (VOID)
Definition at line 515 of file exinit.c.
References EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, and KernelMode.
Referenced by NtAllocateLocallyUniqueId(), NtAllocateUserPhysicalPages(), NtAllocateUuids(), NtAllocateVirtualMemory(), NtCreateDebugObject(), NtCreateIoCompletion(), NtCreateJobObject(), NtCreateJobSet(), NtCreateKeyedEvent(), NtCreateMutant(), NtCreateThread(), NtDebugContinue(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetNextProcess(), NtGetNextThread(), NtGetWriteWatch(), NtImpersonateThread(), NtLockVirtualMemory(), NtMapViewOfSection(), NtOpenEventPair(), NtOpenIoCompletion(), NtOpenJobObject(), NtOpenKeyedEvent(), NtOpenMutant(), NtQueryInformationJobObject(), NtQueryIoCompletion(), NtQueryMutant(), NtReleaseKeyedEvent(), NtReleaseMutant(), NtReleaseSemaphore(), NtRemoveIoCompletion(), NtSetEvent(), NtSetInformationDebugObject(), NtSetInformationObject(), NtUnlockVirtualMemory(), NtWaitForDebugEvent(), NtWaitForKeyedEvent(), ObpCaptureObjectCreateInformation(), ObpCaptureObjectName(), and SepProbeAndCaptureString_U().
NTKERNELAPI VOID ExSystemTimeToLocalTime (__in PLARGE_INTEGER SystemTime, __out PLARGE_INTEGER LocalTime)
Referenced by ExGetNextWakeTime(), and IopCopyBootLogRegistryToFile().
NTKERNELAPI NTSTATUS FASTCALL ExTimedWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock, __in_opt PLARGE_INTEGER Timeout)
Definition at line 1173 of file pushlock.c.
References EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, ExfUnblockPushLock(), ExPushLockSpinCount, FALSE, InterlockedBitTestAndReset(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), KeYieldProcessor, Status, STATUS_SUCCESS, SynchronizationEvent, UNREFERENCED_PARAMETER, and WrPushLock.
Referenced by ExWaitForUnblockPushLock().
NTKERNELAPI VOID ExTimerRundown (VOID)
Definition at line 392 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListHead, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, CONTAINING_RECORD, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, KeCancelTimer(), KeRemoveQueueApc(), KeRemoveQueueDpc(), _ETIMER::KeTimer, _ETIMER::Lock, ObDereferenceObjectEx(), ObReferenceObject, PsGetCurrentThread(), RemoveEntryList(), _ETHREAD::Tcb, _KAPC::Thread, _ETIMER::TimerApc, and _ETIMER::TimerDpc.
Referenced by PspExitThread().
BOOLEAN FORCEINLINE ExTryAcquirePushLockExclusive (IN PEX_PUSH_LOCK PushLock)
Definition at line 7243 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK_V, FALSE, FORCEINLINE, InterlockedBitTestAndSet(), and TRUE.
Referenced by CmpTryToLockHashEntryByIndexExclusive(), ExAcquireCacheAwarePushLockExclusive(), MiAttachAndLockWorkingSet(), and MiTrimAllSystemPageableMemory().
BOOLEAN FORCEINLINE ExTryAcquirePushLockShared (IN PEX_PUSH_LOCK PushLock)
Definition at line 7276 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, ExfTryAcquirePushLockShared(), FALSE, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waiting.
NTKERNELAPI BOOLEAN FORCEINLINE ExTryAcquireReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
Definition at line 7129 of file ex.h.
References FALSE, KeMemoryBarrier(), and TRUE.
Referenced by ExpFreeHandleTableEntry().
FORCEINLINE LOGICAL ExTryAcquireSpinLockExclusive (IN PEX_SPIN_LOCK SpinLock)
Definition at line 861 of file ex.h.
References ASSERT, DISPATCH_LEVEL, EXP_SPIN_LOCK_EXCLUSIVE, FALSE, InterlockedCompareExchangeAcquire, KeGetCurrentIrql(), KeYieldProcessor, NOTHING, and TRUE.
Referenced by ExAcquireSpinLockExclusive(), and ExpAddTagForBigPages().
BOOLEAN FORCEINLINE ExTryConvertPushLockSharedToExclusive (IN PEX_PUSH_LOCK PushLock)
Definition at line 7383 of file ex.h.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, FALSE, InterlockedCompareExchangePointer, and TRUE.
Referenced by CmpTryConvertKCBLockSharedToExclusive(), and ObpLookupDirectoryEntry().
NTKERNELAPI BOOLEAN FASTCALL ExTryToAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
Definition at line 88 of file fmutexc.c.
References xxTryToAcquireFastMutex().
NTKERNELAPI BOOLEAN ExTryToAcquireResourceExclusiveLite (__inout PERESOURCE Resource)
Definition at line 790 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpIncrementCounter, FALSE, IsOwnedExclusive, KeIsExecutingDpc(), PsGetCurrentThread(), ResourceNeverExclusive, ResourceOwnedExclusive, and TRUE.
VOID FORCEINLINE ExUnblockPushLock (IN PEX_PUSH_LOCK PushLock, IN PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock OPTIONAL)
Definition at line 7633 of file ex.h.
References ExfUnblockPushLock(), KeMemoryBarrier(), and NULL.
Referenced by ExDestroyHandle(), ExpBlockOnLockedHandleEntry(), and ExUnlockHandleTableEntry().
NTKERNELAPI VOID ExUnlockHandleTableEntry (__inout PHANDLE_TABLE HandleTable, __inout PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 729 of file handle.c.
References APC_LEVEL, ASSERT, EXASSERT, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExUnblockPushLock(), InterlockedOr(), KeGetCurrentIrql(), KeGetCurrentThread(), NULL, and PAGED_CODE.
Referenced by ExChangeHandle(), ExCreateHandle(), ExDupHandleTable(), ExEnumHandleTable(), ExpGetHandleInfo(), ExSetHandleInfo(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ObAuditObjectAccess(), ObDupHandleProcedure(), ObDuplicateObject(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), and RtlpAtomMapAtomToHandleEntry().
NTKERNELAPI VOID ExUnlockPool (__in POOL_TYPE PoolType, __in KIRQL LockHandle)
NTKERNELAPI VOID ExUnlockUserBuffer (__inout PVOID LockVariable)
Definition at line 4219 of file sysinfo.c.
References ExFreePool(), and MmUnlockPages().
Referenced by ExGetSessionPoolTagInformation(), ExLockUserBuffer(), ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), and MmGetSessionMappedViewInformation().
NTKERNELAPI VOID ExUnregisterCallback (__inout PVOID CallbackRegistration)
Definition at line 537 of file callback.c.
References ASSERT, _CALLBACK_REGISTRATION::Busy, _CALLBACK_REGISTRATION::CallbackObject, DISPATCH_LEVEL, Executive, ExFreePool(), FALSE, KeAcquireSpinLock, KeClearEvent(), KeGetCurrentIrql(), KeReleaseSpinLock(), KernelMode, KeWaitForSingleObject(), _CALLBACK_REGISTRATION::Link, _CALLBACK_OBJECT::Lock, NULL, ObDereferenceObject(), RemoveEntryList(), TRUE, and _CALLBACK_REGISTRATION::UnregisterWaiting.
VOID ExUpdateSystemTimeFromCmos (IN BOOLEAN UpdateInterruptTime, IN ULONG MaxSepInSeconds)
NTKERNELAPI NTSTATUS ExUuidCreate (__out UUID * Uuid)
Definition at line 849 of file uuid.c.
References _UUID_CACHED_VALUES_STRUCT::AllocatedCount, ASSERT, CACHE_LOCAL_ONLY, _UUID_GENERATE::ClockSeqHiAndReserved, _UUID_CACHED_VALUES_STRUCT::ClockSeqHiAndReserved, ExAcquireFastMutexUnsafe(), ExpUuidCacheValid, ExpUuidGetValues(), ExpUuidSaveSequenceNumberIf(), ExReleaseFastMutexUnsafe(), InterlockedDecrement, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), _UUID_GENERATE::NodeId, _UUID_CACHED_VALUES_STRUCT::NodeId, PAGED_CODE, RPC_NT_UUID_LOCAL_ONLY, Status, STATUS_SUCCESS, _UUID_CACHED_VALUES_STRUCT::Time, _UUID_GENERATE::TimeHiAndVersion, _UUID_GENERATE::TimeLow, _UUID_GENERATE::TimeMid, UUID_TIME_HIGH_MASK, and UUID_VERSION.
Referenced by WmipStartLogger().
NTKERNELAPI BOOLEAN ExVerifySuite (__in SUITE_TYPE SuiteType)
Referenced by IoDeleteSymbolicLink(), and PsLocateSystemDll().
VOID ExWaitForCallBacks (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 860 of file callback.c.
References ExWaitForRundownProtectionRelease().
Referenced by CmUnRegisterCallback(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
NTKERNELAPI VOID FORCEINLINE FASTCALL ExWaitForRundownProtectionRelease (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 6368 of file ex.h.
References EX_RUNDOWN_ACTIVE, ExfWaitForRundownProtectionRelease(), and InterlockedCompareExchangePointerAcquire.
Referenced by ExWaitForCallBacks(), ObKillProcess(), and PspExitThread().
NTKERNELAPI VOID FASTCALL ExWaitForRundownProtectionReleaseCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRef)
Definition at line 987 of file rundown.c.
References ASSERT, _EX_RUNDOWN_WAIT_BLOCK::Count, _EX_RUNDOWN_REF::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_SHIFT, Executive, EXP_GET_PROCESSOR_RUNDOWN_REF(), FALSE, FASTCALL, Index, InterlockedCompareExchangePointer, InterlockedExchangeAdd(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NTKERNELAPI, NULL, _EX_RUNDOWN_REF::Ptr, SynchronizationEvent, TRUE, VOID, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
NTKERNELAPI VOID FASTCALL ExWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Definition at line 1160 of file pushlock.c.
References ExTimedWaitForUnblockPushLock(), and NULL.
Referenced by ExfUnblockPushLock(), and ExpBlockOnLockedHandleEntry().
PSLIST_ENTRY FirstEntrySList (IN const SLIST_HEADER * SListHead)
VOID InitializePool (IN POOL_TYPE PoolType, IN ULONG Threshold)
Definition at line 894 of file pool.c.
References ASSERT, DEFAULT_BIGPAGE_TABLE, DEFAULT_TRACKER_TABLE, EX_DELAY_POOL_FREES, EX_SEPARATE_HOT_PAGES_DURING_BOOT, EX_SPECIAL_POOL_ENABLED, ExAllocatePoolWithTag, ExFreePoolMask, ExInitializePoolDescriptor(), EXP_MAXIMUM_POOL_NODES, ExpInsertPoolTracker(), ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExpPoolFlags, ExpSeedHotTags(), ExpTaggedPoolLock, ExSetPoolFlags(), Index, Int32x32To64, KeBugCheckEx(), KeInitializeDpc(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeInitializeTimer(), KeNumberNodes, KeSetTimer(), MAXULONG_PTR, MiAllocatePoolPages(), MmAllocateIndependentPages(), MmIsVerifierEnabled(), MmNumberOfPhysicalPages, MmSizeOfNonPagedPoolInBytes, MUST_SUCCEED_POOL_EMPTY, MUST_SUCCEED_POOL_TYPE_MASK, NonPagedPool, NonPagedPoolDescriptor, NT_SUCCESS, NULL, NumberOfBytes, PagedPool, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTableHash, PoolBigPageTableSize, PoolTrackTable, PoolTrackTableMask, PoolTrackTableSize, _LARGE_INTEGER::QuadPart, ROUND_TO_PAGES, RtlZeroMemory, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by MiBuildPagedPool(), and MiInitMachineDependent().
__inline VOID InitializeSListHead (__out PSLIST_HEADER SListHead)
Definition at line 1378 of file ex.h.
References DbgPrint(), RtlRaiseStatus(), and STATUS_DATATYPE_MISALIGNMENT.
Referenced by ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), MiComputeInitialLargePage(), MiInitializeIoTrackers(), MiInitializeNonPagedPool(), MiInitializeSystemPtes(), MiInitMachineDependent(), MmInitSystem(), and WmipStartLogger().
NTKERNELAPI PSLIST_ENTRY FASTCALL InterlockedPopEntrySList (__inout PSLIST_HEADER ListHead)
Referenced by __bcount(), ExAllocateFromNPagedLookasideList(), ExAllocateFromPagedLookasideList(), ExAllocateFromPPLookasideList(), ExInitializeNBQueueHead(), ExInsertTailNBQueue(), IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), IoSetIoCompletion(), MiAllocatePoolPages(), MiFreeEventCounter(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiInsertPteTracker(), MiReleaseAllMemory(), MmCreateKernelStack(), MmUnlockPages(), WmipFreeTraceBufferPool(), WmipGetFreeBuffer(), and WmipPopFreeContextSwapBuffer().
NTKERNELAPI PSLIST_ENTRY FASTCALL InterlockedPushEntrySList (__inout PSLIST_HEADER ListHead, __inout PSLIST_ENTRY ListEntry)
Referenced by ExFreePoolWithTag(), ExFreeToNPagedLookasideList(), ExFreeToPagedLookasideList(), ExFreeToPPLookasideList(), ExRemoveHeadNBQueue(), IopFreeIrp(), IopFreeMiniPacket(), MiCheckControlAreaStatus(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiFreePoolPages(), MiGetInPageSupportBlock(), MiInitializeSystemPtes(), MiPteSListExpansionWorker(), MiRemovePteTracker(), MmDeleteKernelStack(), MmInitSystem(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipFlushActiveBuffers(), WmipFlushBuffersWithMarker(), WmipPushDirtyBuffer(), WmipPushFreeBuffer(), and WmipSwitchBuffer().
PSLIST_ENTRY FASTCALL InterlockedPushListSList (IN PSLIST_HEADER ListHead, IN PSLIST_ENTRY List, IN PSLIST_ENTRY ListEnd, IN ULONG Count)
Referenced by MiDeferredUnlockPages().
VOID FASTCALL KiAcquireFastMutex (IN PFAST_MUTEX Mutex)
Definition at line 1348 of file wait.c.
References ASSERT, FALSE, FM_LOCK_BIT, FM_LOCK_WAITER_INC, FM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), KernelMode, KeWaitForGate(), KeWaitForSingleObject(), NULL, TRUE, WrGuardedMutex, and WrMutex.
Referenced by xxAcquireFastMutex(), and xxAcquireFastMutexUnsafe().
NTKERNELAPI VOID NTAPI ProbeForWrite (__inout_bcount(Length) PVOID Address, __in SIZE_T Length, __in ULONG Alignment)
Definition at line 40 of file probe.c.
References ASSERT, ExRaiseAccessViolation(), ExRaiseDatatypeMisalignment(), MM_USER_PROBE_ADDRESS, and PageSize.
Referenced by BuildQueryDirectoryIrp(), ExpGetSystemFirmwareTableInformation(), IopXxxControlFile(), KeUserModeCallback(), KiDispatchException(), KiInitializeUserApc(), LpcpCopyRequestData(), MiDoMappedCopy(), MiDoPoolCopy(), MiSecureVirtualMemory(), NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtAllocateUserPhysicalPages(), NtCreateProfile(), NtEnumerateKey(), NtEnumerateValueKey(), NtGetWriteWatch(), NtNotifyChangeDirectoryFile(), NtNotifyChangeMultipleKeys(), NtPrivilegeCheck(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryEvent(), NtQueryInformationAtom(), NtQueryInformationFile(), NtQueryInformationPort(), NtQueryInformationToken(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryObject(), NtQueryOpenSubKeysEx(), NtQueryQuotaInformationFile(), NtQuerySection(), NtQuerySecurityObject(), NtQuerySymbolicLinkObject(), NtQuerySystemInformation(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtReadFile(), NtSecureConnectPort(), ProbeForWriteSmallStructure(), SeAccessCheckByType(), SepAccessCheckAndAuditAlarm(), WmipNtDllLoggerInfo(), WmipQueryLogger(), and WmipStartLogger().
FORCEINLINE VOID ProbeForWriteSmallStructure (IN PVOID Address, IN SIZE_T Size, IN ULONG Alignment)
Definition at line 5640 of file ex.h.
References ASSERT, ExRaiseDatatypeMisalignment(), MM_USER_PROBE_ADDRESS, and ProbeForWrite().
Referenced by KeRaiseUserException(), KiContinueEx(), KiDispatchException(), KiInitializeUserApc(), NtAcceptConnectPort(), NtAllocateLocallyUniqueId(), NtAllocateUuids(), NtCreateThread(), NtExtendSection(), NtMapViewOfSection(), NtPrivilegeCheck(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), NtQueryMutant(), NtQueryPerformanceCounter(), NtQuerySemaphore(), NtQueryTimer(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), and NtWaitForDebugEvent().
FORCEINLINE VOID ProbeForWriteUlongAligned32 (IN PULONG Address)
Definition at line 3456 of file ex.h.
References ExRaiseDatatypeMisalignment(), and ProbeForWriteUlong.
Referenced by NtAllocateUuids(), and NtQueryIoCompletion().
FORCEINLINE VOID xxAcquireFastMutex (IN PFAST_MUTEX FastMutex)
Definition at line 393 of file ex.h.
References APC_LEVEL, ASSERT, FM_LOCK_BIT_V, FORCEINLINE, InterlockedBitTestAndReset(), InterlockedDecrementAcquire, KeGetCurrentIrql(), KeGetCurrentThread(), KfRaiseIrql(), KiAcquireFastMutex(), and VOID.
Referenced by ExAcquireFastMutex().
FORCEINLINE VOID xxAcquireFastMutexUnsafe (IN PFAST_MUTEX FastMutex)
Definition at line 630 of file ex.h.
References APC_LEVEL, ASSERT, _KTHREAD::CombinedApcDisable, FM_LOCK_BIT_V, FORCEINLINE, InterlockedBitTestAndReset(), InterlockedDecrementAcquire, KeGetCurrentIrql(), KeGetCurrentThread(), KiAcquireFastMutex(), MM_SYSTEM_RANGE_START, NULL, _KTHREAD::Teb, and VOID.
Referenced by ExAcquireFastMutexUnsafe(), and ExEnterCriticalRegionAndAcquireFastMutexUnsafe().
FORCEINLINE VOID xxReleaseFastMutex (IN PFAST_MUTEX FastMutex)
Definition at line 451 of file ex.h.
References APC_LEVEL, ASSERT, FM_LOCK_BIT, FM_LOCK_WAITER_INC, FM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), InterlockedExchangeAdd(), InterlockedIncrementRelease, KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, KeSetEventBoostPriority(), KeSignalGateBoostPriority(), and NULL.
Referenced by ExReleaseFastMutex().
FORCEINLINE VOID xxReleaseFastMutexUnsafe (IN PFAST_MUTEX FastMutex)
Definition at line 691 of file ex.h.
References APC_LEVEL, ASSERT, FM_LOCK_BIT, FM_LOCK_WAITER_INC, FM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), InterlockedExchangeAdd(), InterlockedIncrementRelease, KeGetCurrentIrql(), KeGetCurrentThread(), KeSetEventBoostPriority(), KeSignalGateBoostPriority(), MM_SYSTEM_RANGE_START, and NULL.
Referenced by ExReleaseFastMutexUnsafe(), and ExReleaseFastMutexUnsafeAndLeaveCriticalRegion().
FORCEINLINE BOOLEAN xxTryToAcquireFastMutex (IN PFAST_MUTEX FastMutex)
Definition at line 561 of file ex.h.
References APC_LEVEL, ASSERT, FALSE, FM_LOCK_BIT_V, FORCEINLINE, InterlockedBitTestAndReset(), InterlockedCompareExchangeAcquire, KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, KeYieldProcessor, KfRaiseIrql(), TRUE, and VOID.
Referenced by ExTryToAcquireFastMutex().
Variable Documentation
ULONG EvPrSetHigh
ULONG EvPrSetLow
PCALLBACK_OBJECT ExCbPowerState
Definition at line 27 of file exdata.c.
PCALLBACK_OBJECT ExCbSetSystemState
Definition at line 26 of file exdata.c.
PCALLBACK_OBJECT ExCbSetSystemTime
Definition at line 25 of file exdata.c.
BOOLEAN ExCmosClockIsSane
Referenced by KeSetSystemTime(), and Phase1InitializationDiscard().
ULONG ExCriticalWorkerThreads
Definition at line 114 of file worker.c.
Referenced by CcInitializeCacheManager(), and ExpWorkerInitialization().
ULONG ExDelayedWorkerThreads
Definition at line 115 of file worker.c.
Referenced by ExpWorkerInitialization().
PKWIN32_GLOBALATOMTABLE_CALLOUT ExGlobalAtomTableCallout
Definition at line 50 of file exatom.c.
Referenced by NtAddAtom(), NtDeleteAtom(), NtFindAtom(), NtQueryInformationAtom(), and PsEstablishWin32Callouts().
volatile LONG ExHotpSyncRenameSequence
Referenced by IoCreateFile().
PVOID ExPageLockHandle
Definition at line 22 of file mminit.c.
Referenced by ExpGetLockInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpSystemErrorHandler(), IoUnregisterShutdownNotification(), KeSetPhysicalCacheTypeRange(), KiAmdK6MtrrSetMemoryType(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiFreeInitializationCode(), MiResetVirtualMemory(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiShutdownSystem(), MiUnmapLockedPagesInUserSpace(), MmAdjustWorkingSetSizeEx(), MmFreePagesFromMdl(), MmInitSystem(), MmMapUserAddressesToPage(), MmUnlockPagedPool(), and PspQueryWorkingSetWatch().
LONG ExpAltTimeZoneBias
Referenced by Phase1InitializationDiscard().
ULONG ExpCurrentTimeZoneId
Referenced by NtQuerySystemInformation().
LONG ExpLastTimeZoneBias
Referenced by Phase1InitializationDiscard().
LARGE_INTEGER ExpLuid
Definition at line 30 of file luid.c.
const LARGE_INTEGER ExpLuidIncrement
Definition at line 31 of file luid.c.
ULONG ExpRealTimeIsUniversal
Referenced by Phase1InitializationDiscard().
ULONG ExpTickCountMultiplier
Definition at line 39 of file exinit.c.
Referenced by ExpInitializeExecutive().
LARGE_INTEGER ExpTimeZoneBias
Referenced by NtQuerySystemInformation(), and Phase1InitializationDiscard().
BOOLEAN ExReadyForErrors
Definition at line 69 of file harderr.c.
Referenced by CmpCanGrowSystemHive(), CmpDiskFullWarning(), ExpRaiseHardError(), IopHardErrorThread(), IopRaiseHardError(), IopRaiseInformationalHardError(), and NtSetDefaultHardErrorPort().
PKTHREAD ExSyncRenameOwner
Referenced by IoCreateFile().
LIST_ENTRY ExSystemLookasideListHead
Definition at line 66 of file lookasid.c.
Referenced by CcInitializeCacheManager(), ExpGetLookasideInformation(), ExpInitSystemPhase0(), IoInitSystem(), and ObInitSystem().
EX_WORK_QUEUE ExWorkerQueue[]
Definition at line 105 of file worker.c.
Referenced by KeRemoveQueue(), and KeTerminateThread().
NTKERNELAPI __in SIZE_T NumberOfBytes
Definition at line 187 of file ex.h.
Referenced by ExCreatePoolTagTable(), ExDeletePoolTagTable(), ExFreePoolWithTag(), ExGetPoolTagInfo(), ExpInsertPoolTrackerExpansion(), ExpRemovePoolTrackerExpansion(), InitializePool(), MiAllocateLargePages(), MiCcCompletePrefetchIos(), MiComputeInitialLargePage(), MiDispatchFault(), MiInitializeCacheOverrides(), MiInitializeReadInProgressPfn(), MiInitMachineDependent(), MiMapViewInSystemSpace(), MiRememberUnloadedDriver(), MiSessionPoolBigPageTableSize(), MiSessionPoolTrackTableSize(), MiZeroPageFile(), MmAdvanceMdl(), MmCheckSystemImage(), MmGetFileNameForSection(), MmUnloadSystemImage(), NtFreeUserPhysicalPages(), NtGetWriteWatch(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), and RtlpAllocateAtom().
NTKERNELAPI __in SIZE_T __in ULONG __in EX_POOL_PRIORITY Priority
Definition at line 252 of file ex.h.
Referenced by KeSignalGateBoostPriority(), KiComputeNewPriority(), KiDeferredReadyThread(), KxQueueReadyThread(), MmAccessFault(), NtSetInformationThread(), and Phase1InitializationDiscard().
NTKERNELAPI __in SIZE_T __in ULONG Tag
Definition at line 204 of file ex.h.
Referenced by __bcount(), CmpAddDriverToList(), ExFreePoolWithTag(), ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), ExInitializeSystemLookasideList(), and RtlTraceDatabaseCreate().