Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/acceschk.c File Reference
acceschk.c File Reference
#include "mi.h"
Functions
NTSTATUS MiAccessCheck (IN PMMPTE PointerPte, IN ULONG_PTR WriteOperation, IN KPROCESSOR_MODE PreviousMode, IN ULONG Protection, IN PVOID TrapInformation, IN BOOLEAN CallerHoldsPfnLock)
NTSTATUS FASTCALL MiCheckForUserStackOverflow (IN PVOID FaultingAddress, IN PVOID OpaqueTrapInformation)
NTSTATUS MiClearBackingStoreGuardBits (IN PVOID CurrentBSP, IN PVOID StackBase, IN PVOID DeallocationBStore)
NTSTATUS MiClearStackGuardBits (IN PVOID CurrentSP, IN PVOID StackBase, IN PVOID DeallocationStack)
Variables
CCHAR MmReadWrite [32]
Function Documentation
NTSTATUS MiAccessCheck (IN PMMPTE PointerPte, IN ULONG_PTR WriteOperation, IN KPROCESSOR_MODE PreviousMode, IN ULONG Protection, IN PVOID TrapInformation, IN BOOLEAN CallerHoldsPfnLock)
Definition at line 63 of file acceschk.c.
References ASSERT, _MMPTE_HARDWARE::CopyOnWrite, _MMPFN::e1, FALSE, _MMPTE::Hard, KeInvalidAccessAllowed(), KeIsAttachedProcess(), LOCK_PFN, MI_IS_GUARD, MI_PFN_ELEMENT, MiHighestUserPte, MiLocateCloneAddress, MM_GUARD_PAGE, MM_NOACCESS, MmReadWrite, NULL, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, PASSIVE_LEVEL, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), _MMPFN::PteAddress, SATISFY_OVERZEALOUS_COMPILER, _MMPTE::Soft, STATUS_ACCESS_VIOLATION, STATUS_GUARD_PAGE_VIOLATION, STATUS_SUCCESS, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, UserMode, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by MiResolveProtoPteFault(), and MmAccessFault().
NTSTATUS FASTCALL MiCheckForUserStackOverflow (IN PVOID FaultingAddress, IN PVOID OpaqueTrapInformation)
Definition at line 251 of file acceschk.c.
References _ETHREAD::AddressSpaceOwner, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), FLG_DISABLE_STACK_EXTENSION, GUARD_PAGE_SIZE, KeAreAllApcsDisabled(), KeIsAttachedProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_SHARED, MEM_COMMIT, MEM_RESERVE, MiCheckForConflictingVad, MiClearStackGuardBits(), MiQueryAddressState(), MM_GUARD_PAGE, MM_READWRITE, NT_SUCCESS, NtCurrentProcess, NULL, PAGE_ALIGN, PAGE_GUARD, PAGE_READWRITE, PAGE_SIZE, PageSize, _EPROCESS::Peb, ProbeForReadSmallStructure, PsGetCurrentProcessByThread, PsGetCurrentThread(), ROUND_TO_PAGES, STATUS_ALREADY_COMMITTED, STATUS_GUARD_PAGE_VIOLATION, STATUS_PAGE_FAULT_GUARD_PAGE, STATUS_STACK_OVERFLOW, _ETHREAD::Tcb, _KTHREAD::Teb, TRUE, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_SHARED, WOW64_GET_TEB32, ZwAllocateVirtualMemory(), and ZwProtectVirtualMemory().
Referenced by MmAccessFault().
NTSTATUS MiClearBackingStoreGuardBits (IN PVOID CurrentBSP, IN PVOID StackBase, IN PVOID DeallocationBStore)
NTSTATUS MiClearStackGuardBits (IN PVOID CurrentSP, IN PVOID StackBase, IN PVOID DeallocationStack)
Definition at line 770 of file acceschk.c.
References except, EXCEPTION_EXECUTE_HANDLER, LOCK_ADDRESS_SPACE, LOCK_WS_SHARED, MEM_COMMIT, MEM_RESERVE, MI_VPN_TO_VA, MiCheckForConflictingVad, MiQueryAddressState(), NT_SUCCESS, NtCurrentProcess, NULL, PAGE_GUARD, PAGE_READWRITE, PAGE_SIZE, PageSize, ProbeForReadSmallStructure, PsGetCurrentProcessByThread, PsGetCurrentThread(), SATISFY_OVERZEALOUS_COMPILER, _MMVAD::StartingVpn, STATUS_GUARD_PAGE_VIOLATION, STATUS_STACK_OVERFLOW, _ETHREAD::Tcb, _KTHREAD::Teb, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_SHARED, WOW64_GET_TEB32, and ZwAllocateVirtualMemory().
Referenced by MiCheckForUserStackOverflow().
Variable Documentation
CCHAR MmReadWrite[32]
Initial value:
= {1, 10, 10, 10, 11, 11, 11, 11,
                         1, 10, 10, 10, 11, 11, 11, 11,
                         1, 10, 10, 10, 11, 11, 11, 11,
                         1, 10, 10, 10, 11, 11, 11, 11 }
Definition at line 42 of file acceschk.c.
Referenced by MiAccessCheck(), and MiCheckSecuredVad().