Windows Research Kernel v1.2: C:/Windows Research Kernel/perf/hooks.c File Reference
hooks.c File Reference
#include "perfp.h"
#include "zwapi.h"
Macros
#define MAX_FILENAME_TO_LOG 8192
#define RNDM_CONSTANT 314159269
#define RNDM_PRIME 1000000007
Functions
BOOLEAN PerfInfoAddToFileHash (PPERFINFO_ENTRY_TABLE HashTable, PFILE_OBJECT ObjectPointer)
ULONG PerfInfoCalcHashValue (PVOID Key, ULONG Len)
NTSTATUS PerfInfoFileNameRunDown ()
VOID PerfInfoFlushProfileCache (VOID)
NTSTATUS PerfInfoLogBytesAndUnicodeString (USHORT HookId, PVOID SourceData, ULONG SourceByteCount, PUNICODE_STRING String)
NTSTATUS PerfInfoLogFileName (PVOID FileObject, PUNICODE_STRING SourceString)
VOID FASTCALL PerfInfoLogInterrupt (IN PVOID ServiceRoutine, IN ULONG RetVal, IN ULONGLONG InitialTime)
NTSTATUS PerfInfoProcessRunDown ()
NTSTATUS PerfInfoSysModuleRunDown ()
VOID FASTCALL PerfProfileInterrupt (IN KPROFILE_SOURCE Source, IN PVOID InstructionPointer)
Macro Definition Documentation
#define MAX_FILENAME_TO_LOG 8192
Definition at line 35 of file hooks.c.
Referenced by PerfInfoFileNameRunDown(), and PerfInfoLogBytesAndUnicodeString().
#define RNDM_CONSTANT 314159269
Referenced by PerfInfoCalcHashValue().
#define RNDM_PRIME 1000000007
Referenced by PerfInfoCalcHashValue().
Function Documentation
BOOLEAN PerfInfoAddToFileHash (PPERFINFO_ENTRY_TABLE HashTable, PFILE_OBJECT ObjectPointer)
Definition at line 410 of file hooks.c.
References ASSERT, FALSE, NULL, _PERFINFO_ENTRY_TABLE::NumberOfEntries, ObReferenceObject, PerfInfoCalcHashValue(), _PERFINFO_ENTRY_TABLE::Table, and TRUE.
Referenced by PerfInfoFileNameRunDown().
ULONG PerfInfoCalcHashValue (PVOID Key, ULONG Len)
Definition at line 370 of file hooks.c.
References abs(), RNDM_CONSTANT, and RNDM_PRIME.
Referenced by PerfInfoAddToFileHash().
NTSTATUS PerfInfoFileNameRunDown ()
Definition at line 482 of file hooks.c.
References CcPerfFileRunDown(), ExAllocatePoolWithTag, ExFreePool(), IoFileObjectType, MAX_FILENAME_TO_LOG, MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), _OBJECT_NAME_INFORMATION::Name, NonPagedPool, NT_SUCCESS, NULL, _PERFINFO_ENTRY_TABLE::NumberOfEntries, ObDereferenceObject(), ObPerfHandleTableWalk(), ObQueryNameString(), PAGE_SIZE, PERFINFO_ROUND_UP, PerfInfoAddToFileHash(), PerfInfoLogFileName(), PERFPOOLTAG, PsGetNextProcess(), RtlZeroMemory, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, _PERFINFO_ENTRY_TABLE::Table, and _OBJECT_TYPE::TotalNumberOfObjects.
Referenced by PerfInfoStartLog().
VOID PerfInfoFlushProfileCache (VOID)
Definition at line 39 of file hooks.c.
References _PERFINFO_SAMPLED_PROFILE_CACHE::Entries, FALSE, FIELD_OFFSET, InterlockedDecrement, InterlockedIncrement, PERFINFO_LOG_TYPE_SAMPLED_PROFILE_CACHE, PerfInfoLogBytes(), PerfInfoSampledProfileCaching, PerfInfoSampledProfileFlushInProgress, and PerfProfileCache.
Referenced by PerfInfoProfileUninit(), and WmipTraceLoadImage().
NTSTATUS PerfInfoLogBytesAndUnicodeString (USHORT HookId, PVOID SourceData, ULONG SourceByteCount, PUNICODE_STRING String)
Definition at line 262 of file hooks.c.
References _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, MAX_FILENAME_TO_LOG, NT_SUCCESS, NULL, PERF_FINISH_HOOK, PERFINFO_APPLY_OFFSET_GIVING_TYPE, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), RtlCopyMemory, Status, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by PerfInfoLogFileName().
NTSTATUS PerfInfoLogFileName (PVOID FileObject, PUNICODE_STRING SourceString)
Definition at line 326 of file hooks.c.
References FIELD_OFFSET, _PERFINFO_FILENAME_INFORMATION::HashKeyFileNamePointer, _UNICODE_STRING::Length, NULL, PERFINFO_LOG_TYPE_FILENAME_CREATE, PerfInfoLogBytesAndUnicodeString(), Status, and STATUS_SUCCESS.
Referenced by PerfInfoFileNameRunDown().
VOID FASTCALL PerfInfoLogInterrupt (IN PVOID ServiceRoutine, IN ULONG RetVal, IN ULONGLONG InitialTime)
Definition at line 220 of file hooks.c.
References _PERFINFO_INTERRUPT_INFORMATION::InitialTime, PERFINFO_LOG_TYPE_INTERRUPT, PerfInfoLogBytes(), _PERFINFO_INTERRUPT_INFORMATION::ReturnValue, and _PERFINFO_INTERRUPT_INFORMATION::ServiceRoutine.
NTSTATUS PerfInfoProcessRunDown ()
Definition at line 633 of file hooks.c.
References _STRING::Buffer, _UNICODE_STRING::Buffer, _SYSTEM_THREAD_INFORMATION::ClientId, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, HandleToUlong, _SYSTEM_PROCESS_INFORMATION::ImageName, _SYSTEM_PROCESS_INFORMATION::InheritedFromUniqueProcessId, _UNICODE_STRING::Length, _STRING::MaximumLength, _SYSTEM_PROCESS_INFORMATION::NextEntryOffset, NonPagedPool, NT_SUCCESS, NULL, _SYSTEM_PROCESS_INFORMATION::NumberOfThreads, _WMI_PROCESS_INFORMATION::PageDirectoryBase, _SYSTEM_PROCESS_INFORMATION::PageDirectoryBase, _WMI_PROCESS_INFORMATION::ParentId, PERF_FINISH_HOOK, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), PERFPOOLTAG, _WMI_PROCESS_INFORMATION::ProcessId, _WMI_EXTENDED_THREAD_INFORMATION::ProcessId, RtlCopyMemory, RtlUnicodeStringToAnsiString(), _WMI_PROCESS_INFORMATION::SessionId, _SYSTEM_PROCESS_INFORMATION::SessionId, _WMI_PROCESS_INFORMATION::Sid, _WMI_EXTENDED_THREAD_INFORMATION::StackBase, _SYSTEM_EXTENDED_THREAD_INFORMATION::StackBase, _WMI_EXTENDED_THREAD_INFORMATION::StackLimit, _SYSTEM_EXTENDED_THREAD_INFORMATION::StackLimit, _WMI_EXTENDED_THREAD_INFORMATION::StartAddr, _SYSTEM_THREAD_INFORMATION::StartAddress, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_MEMORY, SystemExtendedProcessInformation, _WMI_EXTENDED_THREAD_INFORMATION::ThreadId, _SYSTEM_EXTENDED_THREAD_INFORMATION::ThreadInfo, TRUE, _CLIENT_ID::UniqueProcess, _SYSTEM_PROCESS_INFORMATION::UniqueProcessId, _CLIENT_ID::UniqueThread, _WMI_EXTENDED_THREAD_INFORMATION::UserStackBase, _WMI_EXTENDED_THREAD_INFORMATION::UserStackLimit, _WMI_EXTENDED_THREAD_INFORMATION::WaitMode, _WMI_EXTENDED_THREAD_INFORMATION::Win32StartAddr, _SYSTEM_EXTENDED_THREAD_INFORMATION::Win32StartAddress, WMI_LOG_TYPE_PROCESS_DC_START, WMI_LOG_TYPE_THREAD_DC_START, and ZwQuerySystemInformation().
Referenced by PerfInfoStartLog().
NTSTATUS PerfInfoSysModuleRunDown ()
Definition at line 778 of file hooks.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, _WMI_IMAGELOAD_INFORMATION::FileName, _RTL_PROCESS_MODULE_INFORMATION::FullPathName, HandleToUlong, _RTL_PROCESS_MODULE_INFORMATION::ImageBase, _WMI_IMAGELOAD_INFORMATION::ImageBase, _RTL_PROCESS_MODULE_INFORMATION::ImageSize, _WMI_IMAGELOAD_INFORMATION::ImageSize, _STRING::Length, _UNICODE_STRING::MaximumLength, _RTL_PROCESS_MODULES::Modules, NonPagedPool, NT_SUCCESS, NULL, _RTL_PROCESS_MODULES::NumberOfModules, PERF_FINISH_HOOK, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), PERFPOOLTAG, _WMI_IMAGELOAD_INFORMATION::ProcessId, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_MEMORY, SystemModuleInformation, UNICODE_NULL, WMI_LOG_TYPE_PROCESS_LOAD_IMAGE, and ZwQuerySystemInformation().
Referenced by PerfInfoStartLog().
VOID FASTCALL PerfProfileInterrupt (IN KPROFILE_SOURCE Source, IN PVOID InstructionPointer)
Definition at line 103 of file hooks.c.
References _PERFINFO_SAMPLED_PROFILE_INFORMATION::Count, _PERFINFO_SAMPLED_PROFILE_CACHE::Entries, HandleToUlong, _PERFINFO_SAMPLED_PROFILE_INFORMATION::InstructionPointer, PERF_PROFILE, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_SAMPLED_PROFILE, PERFINFO_LOG_TYPE_SAMPLED_PROFILE_CACHE, PERFINFO_SAMPLED_PROFILE_CACHE_MAX, PerfInfoLogBytes(), PerfInfoProfileSourceActive, PerfInfoSampledProfileCaching, PerfInfoSampledProfileFlushInProgress, PerfProfileCache, PsGetCurrentThread(), _PERFINFO_SAMPLED_PROFILE_CACHE::Sample, and _PERFINFO_SAMPLED_PROFILE_INFORMATION::ThreadId.