Windows Research Kernel v1.2: C:/Windows Research Kernel/perf/perfp.h File Reference
perfp.h File Reference
#include "ntos.h"
Macros
#define PERFPOOLTAG 'freP'
Functions
NTSTATUS PerfInfoFileNameRunDown ()
NTSTATUS PerfInfoProcessRunDown ()
VOID PerfInfoProfileInit ()
VOID PerfInfoProfileUninit ()
NTSTATUS PerfInfoReserveBytesWMI (PPERFINFO_HOOK_HANDLE Hook, USHORT HookId, ULONG BytesToReserve)
NTSTATUS PerfInfoSysModuleRunDown ()
VOID PerfSetLogging (PVOID MaskAddress)
Variables
PERFINFO_GROUPMASK PerfGlobalGroupMask
KPROFILE_SOURCE PerfInfoProfileInterval
KPROFILE PerfInfoProfileObject
KPROFILE_SOURCE PerfInfoProfileSourceActive
KPROFILE_SOURCE PerfInfoProfileSourceRequested
BOOLEAN PerfInfoSampledProfileCaching
LONG PerfInfoSampledProfileFlushInProgress
PERFINFO_SAMPLED_PROFILE_CACHE PerfProfileCache
Macro Definition Documentation
#define PERFPOOLTAG 'freP'
Definition at line 51 of file perfp.h.
Referenced by PerfInfoFileNameRunDown(), PerfInfoProcessRunDown(), and PerfInfoSysModuleRunDown().
Function Documentation
NTSTATUS PerfInfoFileNameRunDown ()
Definition at line 482 of file hooks.c.
References CcPerfFileRunDown(), ExAllocatePoolWithTag, ExFreePool(), IoFileObjectType, MAX_FILENAME_TO_LOG, MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), _OBJECT_NAME_INFORMATION::Name, NonPagedPool, NT_SUCCESS, NULL, _PERFINFO_ENTRY_TABLE::NumberOfEntries, ObDereferenceObject(), ObPerfHandleTableWalk(), ObQueryNameString(), PAGE_SIZE, PERFINFO_ROUND_UP, PerfInfoAddToFileHash(), PerfInfoLogFileName(), PERFPOOLTAG, PsGetNextProcess(), RtlZeroMemory, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, _PERFINFO_ENTRY_TABLE::Table, and _OBJECT_TYPE::TotalNumberOfObjects.
Referenced by PerfInfoStartLog().
NTSTATUS PerfInfoProcessRunDown ()
Definition at line 633 of file hooks.c.
References _STRING::Buffer, _UNICODE_STRING::Buffer, _SYSTEM_THREAD_INFORMATION::ClientId, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, HandleToUlong, _SYSTEM_PROCESS_INFORMATION::ImageName, _SYSTEM_PROCESS_INFORMATION::InheritedFromUniqueProcessId, _UNICODE_STRING::Length, _STRING::MaximumLength, _SYSTEM_PROCESS_INFORMATION::NextEntryOffset, NonPagedPool, NT_SUCCESS, NULL, _SYSTEM_PROCESS_INFORMATION::NumberOfThreads, _WMI_PROCESS_INFORMATION::PageDirectoryBase, _SYSTEM_PROCESS_INFORMATION::PageDirectoryBase, _WMI_PROCESS_INFORMATION::ParentId, PERF_FINISH_HOOK, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), PERFPOOLTAG, _WMI_PROCESS_INFORMATION::ProcessId, _WMI_EXTENDED_THREAD_INFORMATION::ProcessId, RtlCopyMemory, RtlUnicodeStringToAnsiString(), _WMI_PROCESS_INFORMATION::SessionId, _SYSTEM_PROCESS_INFORMATION::SessionId, _WMI_PROCESS_INFORMATION::Sid, _WMI_EXTENDED_THREAD_INFORMATION::StackBase, _SYSTEM_EXTENDED_THREAD_INFORMATION::StackBase, _WMI_EXTENDED_THREAD_INFORMATION::StackLimit, _SYSTEM_EXTENDED_THREAD_INFORMATION::StackLimit, _WMI_EXTENDED_THREAD_INFORMATION::StartAddr, _SYSTEM_THREAD_INFORMATION::StartAddress, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_MEMORY, SystemExtendedProcessInformation, _WMI_EXTENDED_THREAD_INFORMATION::ThreadId, _SYSTEM_EXTENDED_THREAD_INFORMATION::ThreadInfo, TRUE, _CLIENT_ID::UniqueProcess, _SYSTEM_PROCESS_INFORMATION::UniqueProcessId, _CLIENT_ID::UniqueThread, _WMI_EXTENDED_THREAD_INFORMATION::UserStackBase, _WMI_EXTENDED_THREAD_INFORMATION::UserStackLimit, _WMI_EXTENDED_THREAD_INFORMATION::WaitMode, _WMI_EXTENDED_THREAD_INFORMATION::Win32StartAddr, _SYSTEM_EXTENDED_THREAD_INFORMATION::Win32StartAddress, WMI_LOG_TYPE_PROCESS_DC_START, WMI_LOG_TYPE_THREAD_DC_START, and ZwQuerySystemInformation().
Referenced by PerfInfoStartLog().
VOID PerfInfoProfileInit ()
Definition at line 33 of file perfsup.c.
References _PERFINFO_SAMPLED_PROFILE_CACHE::Entries, FALSE, KeInitializeProfile(), KeSetIntervalProfile(), KeStartProfile(), NULL, PerfInfoProfileInterval, PerfInfoProfileObject, PerfInfoProfileSourceActive, PerfInfoProfileSourceRequested, PerfInfoSampledProfileCaching, PerfInfoSampledProfileFlushInProgress, PerfProfileCache, and TRUE.
Referenced by PerfInfoStartLog().
VOID PerfInfoProfileUninit ()
Definition at line 74 of file perfsup.c.
References KeStopProfile(), PerfInfoFlushProfileCache(), PerfInfoProfileObject, PerfInfoProfileSourceActive, and ProfileMaximum.
Referenced by PerfInfoStartLog(), and PerfInfoStopLog().
NTSTATUS PerfInfoReserveBytesWMI (PPERFINFO_HOOK_HANDLE Hook, USHORT HookId, ULONG BytesToReserve)
NTSTATUS PerfInfoSysModuleRunDown ()
Definition at line 778 of file hooks.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, _WMI_IMAGELOAD_INFORMATION::FileName, _RTL_PROCESS_MODULE_INFORMATION::FullPathName, HandleToUlong, _RTL_PROCESS_MODULE_INFORMATION::ImageBase, _WMI_IMAGELOAD_INFORMATION::ImageBase, _RTL_PROCESS_MODULE_INFORMATION::ImageSize, _WMI_IMAGELOAD_INFORMATION::ImageSize, _STRING::Length, _UNICODE_STRING::MaximumLength, _RTL_PROCESS_MODULES::Modules, NonPagedPool, NT_SUCCESS, NULL, _RTL_PROCESS_MODULES::NumberOfModules, PERF_FINISH_HOOK, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), PERFPOOLTAG, _WMI_IMAGELOAD_INFORMATION::ProcessId, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_MEMORY, SystemModuleInformation, UNICODE_NULL, WMI_LOG_TYPE_PROCESS_LOAD_IMAGE, and ZwQuerySystemInformation().
Referenced by PerfInfoStartLog().
VOID PerfSetLogging (PVOID MaskAddress)
Referenced by PerfInfoStartLog(), and PerfInfoStopLog().
Variable Documentation
PERFINFO_GROUPMASK PerfGlobalGroupMask
Definition at line 21 of file perfdata.c.
Referenced by PerfInfoStartLog().
KPROFILE_SOURCE PerfInfoProfileInterval
Definition at line 32 of file perfdata.c.
Referenced by PerfInfoProfileInit().
KPROFILE PerfInfoProfileObject
Definition at line 29 of file perfdata.c.
Referenced by PerfInfoProfileInit(), and PerfInfoProfileUninit().
KPROFILE_SOURCE PerfInfoProfileSourceActive
Definition at line 30 of file perfdata.c.
Referenced by PerfInfoProfileInit(), PerfInfoProfileUninit(), and PerfProfileInterrupt().
KPROFILE_SOURCE PerfInfoProfileSourceRequested
Definition at line 31 of file perfdata.c.
Referenced by PerfInfoProfileInit().
BOOLEAN PerfInfoSampledProfileCaching
Definition at line 33 of file perfdata.c.
Referenced by PerfInfoFlushProfileCache(), PerfInfoProfileInit(), and PerfProfileInterrupt().
LONG PerfInfoSampledProfileFlushInProgress
Definition at line 34 of file perfdata.c.
Referenced by PerfInfoFlushProfileCache(), PerfInfoProfileInit(), and PerfProfileInterrupt().
PERFINFO_SAMPLED_PROFILE_CACHE PerfProfileCache
Definition at line 35 of file perfdata.c.
Referenced by PerfInfoFlushProfileCache(), PerfInfoProfileInit(), and PerfProfileInterrupt().