Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivesync.c File Reference
hivesync.c File Reference
#include "cmp.h"
Macros
#define DumpDirtyVector(BitMap)
#define ONE_K 1024
Functions
VOID CmpFreeCmView (PCM_VIEW_OF_FILE CmView)
VOID CmpLogError (IN NTSTATUS NtStatusCode)
VOID CmpUnmapCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN MapIsValid, IN BOOLEAN MoveToEnd)
VOID CmpUnmapCmViewSurroundingOffset (IN PCMHIVE CmHive, IN ULONG FileOffset)
BOOLEAN HvHiveWillShrink (IN PHHIVE Hive)
BOOLEAN HvMarkCellDirty (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN LockHeld)
BOOLEAN HvMarkDirty (PHHIVE Hive, HCELL_INDEX Start, ULONG Length, BOOLEAN DirtyAndPin)
BOOLEAN HvpDoWriteHive (PHHIVE Hive, ULONG FileType)
VOID HvpDropAllPagedBins (IN PHHIVE Hive)
VOID HvpDropPagedBins (IN PHHIVE Hive)
BOOLEAN HvpFindNextDirtyBlock (PHHIVE Hive, PRTL_BITMAP BitMap, PULONG Current, PUCHAR *Address, PULONG Length, PULONG Offset)
VOID HvpFlushMappedData (IN PHHIVE Hive, IN OUT PRTL_BITMAP DirtyVector)
BOOLEAN HvpGrowLog1 (PHHIVE Hive, ULONG Count)
BOOLEAN HvpGrowLog2 (PHHIVE Hive, ULONG Size)
VOID HvpTruncateBins (PHHIVE Hive)
VOID HvpTruncateBins (IN PHHIVE Hive)
BOOLEAN HvpWriteLog (PHHIVE Hive)
VOID HvRefreshHive (PHHIVE Hive)
BOOLEAN HvSyncHive (PHHIVE Hive)
NTSTATUS HvWriteHive (PHHIVE Hive, BOOLEAN DontGrow, BOOLEAN WriteThroughCache, BOOLEAN CrashSafe)
Variables
BOOLEAN CmpDontGrowLogFile
BOOLEAN CmpFlushOnLockRelease
HIVE_LIST_ENTRY CmpMachineHiveList []
PUCHAR CmpStashBuffer
ULONG CmpStashBufferSize
LONG CmRegistryLogSizeLimit
BOOLEAN HvShutdownComplete
Macro Definition Documentation
#define DumpDirtyVector (BitMap)
Definition at line 67 of file hivesync.c.
#define ONE_K 1024
Definition at line 22 of file hivesync.c.
Referenced by HvpGrowLog1(), and HvpGrowLog2().
Function Documentation
VOID CmpFreeCmView (PCM_VIEW_OF_FILE CmView)
Definition at line 1471 of file cmmapvw.c.
References ASSERT, _CM_VIEW_OF_FILE::Bcb, CM_BUGCHECK, CM_PAGED_CODE, CMVIEW_ERROR, ExFreePoolWithTag, _CM_VIEW_OF_FILE::FileOffset, IsListEmpty, _CM_VIEW_OF_FILE::LRUViewList, NULL, _CM_VIEW_OF_FILE::PinViewList, PROTECTED_POOL, REGISTRY_ERROR, _CM_VIEW_OF_FILE::Size, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpFixHiveUsageCount(), CmpUnPinCmView(), and HvRefreshHive().
VOID CmpLogError (IN NTSTATUS NtStatusCode)
Definition at line 1260 of file cmchek.c.
References CM_PAGED_CODE, _IO_ERROR_LOG_PACKET::ErrorCode, _IO_ERROR_LOG_PACKET::FinalStatus, IoAllocateGenericErrorLogEntry(), and IoWriteErrorLogEntry().
Referenced by HvSyncHive().
VOID CmpUnmapCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN MapIsValid, IN BOOLEAN MoveToEnd)
Definition at line 91 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, _HMAP_ENTRY::BinAddress, CcUnpinData(), CM_PAGED_CODE, _HMAP_ENTRY::CmView, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvpGetCellMap(), InsertTailList(), NULL, RemoveEntryList(), Stable, TRUE, and VALIDATE_CELL_MAP.
Referenced by CmpDestroyHiveViewList(), CmpFixHiveUsageCount(), CmpMapCmView(), CmpUnmapCmViewSurroundingOffset(), CmpUnmapUnusedViews(), CmpUnPinCmView(), HvpDropPagedBins(), and HvRefreshHive().
VOID CmpUnmapCmViewSurroundingOffset (IN PCMHIVE CmHive, IN ULONG FileOffset)
Definition at line 616 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, ASSERT_VIEW_MAPPED, CM_PAGED_CODE, CmpUnmapCmView(), CONTAINING_RECORD, FALSE, _CM_VIEW_OF_FILE::FileOffset, _LIST_ENTRY::Flink, _CM_VIEW_OF_FILE::LRUViewList, _CM_VIEW_OF_FILE::Size, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by HvRefreshHive().
BOOLEAN HvHiveWillShrink (IN PHHIVE Hive)
Definition at line 2759 of file hivesync.c.
References ASSERT, _HMAP_ENTRY::BinAddress, FALSE, HBLOCK_SIZE, HMAP_DISCARDABLE, HvpGetCellMap(), Stable, TRUE, and VALIDATE_CELL_MAP.
Referenced by CmFlushKey(), CmpDoFlushAll(), and CmpDoFlushNextHive().
BOOLEAN HvMarkCellDirty (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN LockHeld)
Definition at line 135 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_VIEW_MAPPED, ASSERT_VIEW_PINNED, Bin, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_IO, CmLockHiveViews, CmpLockHiveWriter, CmpPinCmView(), CmpUnlockHiveWriter, CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HHIVE_SIGNATURE, HIVE_VOLATILE, HMAP_INVIEW, HvGetCellType, HvMarkDirty(), HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, IsListEmpty, _HCELL::NewCell, NT_SUCCESS, NULL, _CM_VIEW_OF_FILE::PinViewList, _HHIVE::ReadOnly, RtlNumberOfSetBits(), _HBIN::Signature, _HHIVE::Signature, _HCELL::Size, _HBIN::Size, TRUE, USE_OLD_CELL, VALIDATE_CELL_MAP, and Volatile.
Referenced by CmDeleteValueKey(), CmMoveKey(), CmpAddSubKey(), CmpAddToLeaf(), CmpAssignSecurityDescriptor(), CmpCheckKey(), CmpCheckValueList(), CmpCopySyncTree2(), CmpCreateLinkNode(), CmpDoCreate(), CmpInsertSecurityCellList(), CmpMarkCurrentValueDirty(), CmpMarkIndexDirty(), CmpMarkKeyDirty(), CmpMarkKeyParentDirty(), CmpMarkKeyValuesDirty(), CmpMarkValueDataDirty(), CmpOverwriteHive(), CmpRemoveSubKeyCellNoCellRef(), CmpSaveBootControlSet(), CmpSelectLeaf(), CmpSetSecurityDescriptorInfo(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmpUpdateParentForEachSon(), CmpValidateHiveSecurityDescriptors(), CmRenameKey(), CmRestoreKey(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), HvpFindFreeCellInBin(), and HvpIsFreeNeighbor().
BOOLEAN HvMarkDirty (PHHIVE Hive, HCELL_INDEX Start, ULONG Length, BOOLEAN DirtyAndPin)
Definition at line 293 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_VIEW_MAPPED, ASSERT_VIEW_PINNED, BIN_MAP_ALLOCATION_TYPE, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_IO, CmLockHiveViews, CmpLazyFlush(), CmpMapCmView(), CmpPinCmView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, HHIVE_SIGNATURE, HIVE_NOLAZYFLUSH, HIVE_VOLATILE, _HHIVE::HiveFlags, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_COUNT, HSECTOR_PER_PAGE_COUNT, HSECTOR_SIZE, HvGetCellType, HvpGetCellMap(), HvpGrowLog1(), HvpMarkBinReadWrite, IsListEmpty, NT_SUCCESS, NULL, PAGE_SIZE, _CM_VIEW_OF_FILE::PinViewList, _HHIVE::ReadOnly, ROUND_UP, RtlCheckBit, RtlNumberOfSetBits(), RtlSetBits(), _HHIVE::Signature, Stable, TRUE, VALIDATE_CELL_MAP, and Volatile.
Referenced by HvMarkCellDirty(), HvpAddBin(), HvpEnlistFreeCell(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), and HvpRecoverData().
BOOLEAN HvpDoWriteHive (PHHIVE Hive, ULONG FileType)
Definition at line 1857 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED_EXCLUSIVE, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, _HBASE_BLOCK::CheckSum, _HBASE_BLOCK::Cluster, CM_BUGCHECK, CmKdPrintEx, CML_IO, CmpDoFileSetSize(), CmpFileWriteThroughCache(), CmpFree(), Count, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FATAL_MAPPING_ERROR, FileEndOfFileInformation, FileOffset, CMP_OFFSET_ARRAY::FileOffset, _HBASE_BLOCK::Format, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBLOCK_SIZE, HCELL_NIL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, _LARGE_INTEGER::HighPart, HiveWritesThroughCache, HLOG_MINSIZE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_SIZE, HSYS_MAJOR, HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpGetCellMap(), HvpHeaderCheckSum(), _HBASE_BLOCK::Length, _LARGE_INTEGER::LowPart, _HBASE_BLOCK::Major, NT_SUCCESS, NtQueryInformationFile(), NULL, PagedPool, REGISTRY_ERROR, ROUND_UP, RtlCheckBit, RtlCopyMemory, RtlInitializeBitMap(), RtlNumberOfSetBits(), _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBASE_BLOCK::Signature, _RTL_BITMAP::SizeOfBitMap, Stable, Status, _IO_STATUS_BLOCK::Status, _HBIN::TimeStamp, _HBASE_BLOCK::TimeStamp, TRUE, _HBASE_BLOCK::Type, VALIDATE_CELL_MAP, and ZwFlushBuffersFile().
Referenced by HvInitializeHive(), and HvSyncHive().
VOID HvpDropAllPagedBins (IN PHHIVE Hive)
Definition at line 3048 of file hivesync.c.
References ASSERT, ASSERT_BIN_INPAGEDPOOL, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CmpFree(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, _HBIN::FileOffset, _FREE_HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HvpCheckViewBoundary(), HvpGetBinMemAlloc(), HvpGetCellMap(), NULL, PAGED_CODE, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, Stable, and VALIDATE_CELL_MAP.
Referenced by CmCompressKey().
VOID HvpDropPagedBins (IN PHHIVE Hive)
Definition at line 2852 of file hivesync.c.
References ASSERT, ASSERT_BIN_INPAGEDPOOL, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CM_VIEW_SIZE, CmKdPrintEx, CmLockHiveViews, CmpFree(), CmpUnmapCmView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _HBIN::FileOffset, _FREE_HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HvpCheckViewBoundary(), HvpGetBinMemAlloc(), HvpGetCellMap(), NOTHING, NULL, PAGED_CODE, _HBIN::Signature, _HBIN::Size, Stable, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvSyncHive().
BOOLEAN HvpFindNextDirtyBlock (PHHIVE Hive, PRTL_BITMAP BitMap, PULONG Current, PUCHAR * Address, PULONG Length, PULONG Offset)
Definition at line 2533 of file hivesync.c.
References ASSERT, ASSERT_BIN_VALID, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CM_BUGCHECK, CmKdPrintEx, CML_IO, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FALSE, FATAL_MAPPING_ERROR, _FREE_HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HCELL_OFFSET_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_COUNT, HSECTOR_SIZE, HvpCheckViewBoundary(), HvpGetCellMap(), NULL, REGISTRY_ERROR, ROUND_UP, RtlCheckBit, _RTL_BITMAP::SizeOfBitMap, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvpDoWriteHive(), HvpWriteLog(), and HvRefreshHive().
VOID HvpFlushMappedData (IN PHHIVE Hive, IN OUT PRTL_BITMAP DirtyVector)
Definition at line 1700 of file hivesync.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CML_HIVE, CmpUnPinCmView(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, FALSE, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _CM_VIEW_OF_FILE::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_DISCARDABLE, HMAP_INVIEW, HSECTOR_SIZE, HvpGetCellMap(), IsListEmpty, PAGED_CODE, _CMHIVE::PinViewListHead, RemoveHeadList(), RtlClearBits(), _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, _CM_VIEW_OF_FILE::Size, Stable, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvpDoWriteHive().
BOOLEAN HvpGrowLog1 (PHHIVE Hive, ULONG Count)
Definition at line 605 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, _HHIVE::Cluster, CmKdPrintEx, CML_IO, CmpDontGrowLogFile, CmpFlushOnLockRelease, CmRegistryLogSizeLimit, Count, DbgPrintEx(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _HHIVE::FileSetSize, HFILE_TYPE_LOG, HLOG_GROW, HSECTOR_SIZE, _HHIVE::Log, _HHIVE::LogSize, ONE_K, _HHIVE::ReadOnly, ROUND_UP, RtlNumberOfSetBits(), _RTL_BITMAP::SizeOfBitMap, and TRUE.
Referenced by HvMarkDirty().
BOOLEAN HvpGrowLog2 (PHHIVE Hive, ULONG Size)
Definition at line 1472 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, _HHIVE::Cluster, CmKdPrintEx, CML_IO, CmpFlushOnLockRelease, CmRegistryLogSizeLimit, DbgPrintEx(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _HHIVE::FileSetSize, HFILE_TYPE_LOG, HLOG_GROW, HSECTOR_SIZE, _HHIVE::_DUAL::Length, _HHIVE::Log, _HHIVE::LogSize, ONE_K, _HHIVE::ReadOnly, ROUND_UP, RtlNumberOfSetBits(), _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, and TRUE.
Referenced by CmpOverwriteHive(), and HvpAddBin().
VOID HvpTruncateBins (PHHIVE Hive)
Referenced by HvSyncHive().
VOID HvpTruncateBins (IN PHHIVE Hive)
Definition at line 2794 of file hivesync.c.
References _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _FREE_HBIN::FileOffset, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HTYPE_COUNT, HvFreeHivePartial(), HvpGetCellMap(), and VALIDATE_CELL_MAP.
BOOLEAN HvpWriteLog (PHHIVE Hive)
Definition at line 2260 of file hivesync.c.
References ASSERT, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, _HBASE_BLOCK::CheckSum, _HBASE_BLOCK::Cluster, _HHIVE::Cluster, CmKdPrintEx, CML_IO, CmpDoFileSetSize(), CmpStashBuffer, CmpStashBufferSize, Count, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, ExAllocatePool, ExAllocatePoolWithTag, ExFreePool(), FALSE, _HHIVE::FileFlush, CMP_OFFSET_ARRAY::FileOffset, _HHIVE::FileWrite, _HBASE_BLOCK::Format, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HFILE_TYPE_LOG, Hive, HLOG_DV_SIGNATURE, HLOG_GROW, HLOG_HEADER_SIZE, HSECTOR_SIZE, HSYS_MAJOR, HvpFindNextDirtyBlock(), HvpHeaderCheckSum(), KeQuerySystemTime(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, LOCK_STASH_BUFFER, _HHIVE::LogSize, _HBASE_BLOCK::Major, NOTHING, NT_SUCCESS, NULL, PAGE_SIZE, PagedPool, _HHIVE::ReadOnly, ROUND_UP, RtlCopyMemory, RtlNumberOfSetBits(), _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBASE_BLOCK::Signature, _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, _HBASE_BLOCK::TimeStamp, TRUE, _HBASE_BLOCK::Type, and UNLOCK_STASH_BUFFER.
Referenced by CmpOverwriteHive(), and HvSyncHive().
VOID HvRefreshHive (PHHIVE Hive)
Definition at line 685 of file hivesync.c.
References _256K, ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CcPurgeCacheSection(), CM_BUGCHECK, CM_CHECK_REGISTRY_FORCE_CLEAN, CM_VIEW_SIZE, CmCheckRegistry(), CmpFreeCmView(), CmpMapCmView(), CmpRebuildSecurityCache(), CmpStashBuffer, CmpStashBufferSize, CmpTouchView(), CmpUnmapCmView(), CmpUnmapCmViewSurroundingOffset(), CONTAINING_RECORD, _HHIVE::DirtyCount, _HHIVE::DirtyVector, _FREE_DISPLAY::Display, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CMHIVE::FileObject, FileOffset, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _CM_VIEW_OF_FILE::FileOffset, _HHIVE::FileRead, _HHIVE::FileSetSize, _CM_KEY_NODE::Flags, _FREE_HBIN::Flags, _LIST_ENTRY::Flink, _HHIVE::Free, FREE_HBIN_DISCARDABLE, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, HBIN_BASE, HBIN_FLAGS, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_PRIMARY, HHIVE_FREE_DISPLAY_SIZE, _LARGE_INTEGER::HighPart, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HSECTOR_SIZE, HvCheckHive(), HvFreeHivePartial(), HvGetCell, HvpAdjustHiveFreeDisplay(), HvpEnlistFreeCells(), HvpFindNextDirtyBlock(), HvpGetCellMap(), HvReleaseCell, InitializeListHead(), InsertTailList(), IsListEmpty, KEY_HIVE_ENTRY, KEY_NO_DELETE, _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, LOCK_STASH_BUFFER, _LARGE_INTEGER::LowPart, _CM_VIEW_OF_FILE::LRUViewList, _HMAP_ENTRY::MemAlloc, NT_SUCCESS, NULL, PAGE_SIZE, PagedPool, _CM_KEY_NODE::Parent, _CMHIVE::PinnedViews, _CM_VIEW_OF_FILE::PinViewList, _CMHIVE::PinViewListHead, REFRESH_HIVE, _HHIVE::RefreshCount, REGISTRY_ERROR, RemoveEntryList(), RemoveHeadList(), _HBASE_BLOCK::RootCell, ROUND_UP, RtlCheckBit, RtlClearBits(), RtlCopyMemory, RtlNumberOfSetBits(), _FILE_OBJECT::SectionObjectPointer, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, _CM_VIEW_OF_FILE::Size, _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, TRUE, UNLOCK_STASH_BUFFER, _CM_VIEW_OF_FILE::UseCount, VALIDATE_CELL_MAP, and Volatile.
Referenced by CmpRefreshHive().
BOOLEAN HvSyncHive (PHHIVE Hive)
Definition at line 1558 of file hivesync.c.
References ASSERT, CM_NUMBER_OF_MACHINE_HIVES, _HIVE_LIST_ENTRY::CmHive, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmpLogError(), CmpMiniNTBoot, DBG, _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, HFILE_TYPE_PRIMARY, HHIVE_SIGNATURE, HIVE_VOLATILE, _HHIVE::HiveFlags, HvpDoWriteHive(), HvpDropPagedBins(), HvpTruncateBins(), HvpWriteLog(), HvShutdownComplete, Index, IoSetThreadHardErrorMode(), _HHIVE::Log, NULL, _HHIVE::ReadOnly, RtlClearAllBits(), _HHIVE::Signature, STATUS_REGISTRY_IO_FAILED, and TRUE.
Referenced by CmFlushKey(), CmLoadKey(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpInitializeHiveList(), CmpLoadHiveThread(), and CmpShiftHiveFreeBins().
NTSTATUS HvWriteHive (PHHIVE Hive, BOOLEAN DontGrow, BOOLEAN WriteThroughCache, BOOLEAN CrashSafe)
Definition at line 3170 of file hivesync.c.
References ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _HBASE_BLOCK::CheckSum, _HHIVE::Cluster, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmLockHiveViews, CmpDereferenceHiveView(), CmpDereferenceHiveViewWithLock(), CmpDoFileSetSize(), CmpFileWriteThroughCache(), CmpMapThisBin(), CmpReferenceHiveView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DPFLTR_CONFIG_ID, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _HHIVE::FileFlush, _HBIN::FileOffset, CMP_OFFSET_ARRAY::FileOffset, _HHIVE::FileWrite, _FREE_HBIN::Flags, _HBASE_BLOCK::Format, FREE_HBIN_DISCARDABLE, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBIN_BASE, HBIN_NIL, HBIN_SIGNATURE, HBLOCK_SIZE, HCELL_NIL, HFILE_TYPE_EXTERNAL, HHIVE_SIGNATURE, Hive, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_SIZE, HSYS_MAJOR, HvpCheckViewBoundary(), HvpGetCellMap(), HvpHeaderCheckSum(), HvShutdownComplete, _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HBASE_BLOCK::Major, NT_SUCCESS, NULL, PagedPool, _HHIVE::ReadOnly, _HBASE_BLOCK::RootCell, ROUND_UP, RtlZeroMemory, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBIN::Signature, _HBASE_BLOCK::Signature, _HHIVE::Signature, _HCELL::Size, _HBIN::Size, _FREE_HBIN::Size, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, _HHIVE::Storage, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by CmDumpKey(), CmpOverwriteHive(), CmSaveKey(), and CmSaveMergedKeys().
Variable Documentation
BOOLEAN CmpDontGrowLogFile
Definition at line 67 of file cmworker.c.
Referenced by CmSetLazyFlushState(), and HvpGrowLog1().
BOOLEAN CmpFlushOnLockRelease
Definition at line 56 of file cmsubs3.c.
Referenced by CmpUnlockRegistry(), HvpGrowLog1(), and HvpGrowLog2().
HIVE_LIST_ENTRY CmpMachineHiveList[]
Definition at line 284 of file cmdat.c.
PUCHAR CmpStashBuffer
Definition at line 64 of file cmdat2.c.
Referenced by HvpWriteLog(), and HvRefreshHive().
ULONG CmpStashBufferSize
Definition at line 65 of file cmdat2.c.
Referenced by HvpWriteLog(), and HvRefreshHive().
LONG CmRegistryLogSizeLimit
Definition at line 57 of file cmsubs3.c.
Referenced by HvpGrowLog1(), and HvpGrowLog2().
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by HvSyncHive(), and HvWriteHive().