Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/pshelper.c File Reference
pshelper.c File Reference
#include "psp.h"
Functions
PEPROCESS PsGetCurrentProcess (VOID)
ULONG PsGetCurrentProcessSessionId (VOID)
PVOID PsGetCurrentProcessWin32Process (VOID)
PVOID PsGetCurrentProcessWow64Process (VOID)
PETHREAD PsGetCurrentThread (VOID)
CCHAR PsGetCurrentThreadPreviousMode (VOID)
PEPROCESS PsGetCurrentThreadProcess (VOID)
HANDLE PsGetCurrentThreadProcessId (VOID)
PVOID PsGetCurrentThreadStackBase (VOID)
PVOID PsGetCurrentThreadStackLimit (VOID)
PVOID PsGetCurrentThreadTeb (VOID)
PVOID PsGetCurrentThreadWin32Thread (VOID)
PVOID PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion (__out PHANDLE ProcessId)
PERESOURCE PsGetJobLock (__in PEJOB Job)
ULONG PsGetJobSessionId (__in PEJOB Job)
ULONG PsGetJobUIRestrictionsClass (__in PEJOB Job)
LONGLONG PsGetProcessCreateTimeQuadPart (__in PEPROCESS Process)
PVOID PsGetProcessDebugPort (__in PEPROCESS Process)
BOOLEAN PsGetProcessExitProcessCalled (__in PEPROCESS Process)
NTSTATUS PsGetProcessExitStatus (__in PEPROCESS Process)
HANDLE PsGetProcessId (__in PEPROCESS Process)
UCHAR * PsGetProcessImageFileName (__in PEPROCESS Process)
HANDLE PsGetProcessInheritedFromUniqueProcessId (__in PEPROCESS Process)
PEJOB PsGetProcessJob (__in PEPROCESS Process)
PPEB PsGetProcessPeb (__in PEPROCESS Process)
UCHAR PsGetProcessPriorityClass (__in PEPROCESS Process)
PVOID PsGetProcessSectionBaseAddress (__in PEPROCESS Process)
PVOID PsGetProcessSecurityPort (__in PEPROCESS Process)
ULONG PsGetProcessSessionId (__in PEPROCESS Process)
ULONG PsGetProcessSessionIdEx (__in PEPROCESS Process)
PVOID PsGetProcessWin32Process (__in PEPROCESS Process)
HANDLE PsGetProcessWin32WindowStation (__in PEPROCESS Process)
PVOID PsGetProcessWow64Process (__in PEPROCESS Process)
CCHAR PsGetThreadFreezeCount (__in PETHREAD Thread)
BOOLEAN PsGetThreadHardErrorsAreDisabled (__in PETHREAD Thread)
HANDLE PsGetThreadId (__in PETHREAD Thread)
PEPROCESS PsGetThreadProcess (__in PETHREAD Thread)
HANDLE PsGetThreadProcessId (__in PETHREAD Thread)
ULONG PsGetThreadSessionId (__in PETHREAD Thread)
PVOID PsGetThreadTeb (__in PETHREAD Thread)
PVOID PsGetThreadWin32Thread (__in PETHREAD Thread)
BOOLEAN PsIsProcessBeingDebugged (__in PEPROCESS Process)
BOOLEAN PsIsSystemProcess (__in PEPROCESS Process)
BOOLEAN PsIsSystemThread (__in PETHREAD Thread)
BOOLEAN PsIsThreadImpersonating (__in PETHREAD Thread)
NTSTATUS PsReferenceProcessFilePointer (IN PEPROCESS Process, OUT PVOID *OutFileObject)
VOID PsSetJobUIRestrictionsClass (__out PEJOB Job, __in ULONG UIRestrictionsClass)
VOID PsSetProcessPriorityClass (__out PEPROCESS Process, __in UCHAR PriorityClass)
NTSTATUS PsSetProcessSecurityPort (__out PEPROCESS Process, __in PVOID Port)
NTSTATUS PsSetProcessWin32Process (__in PEPROCESS Process, __in PVOID Win32Process, __in PVOID PrevWin32Process)
VOID PsSetProcessWindowStation (__out PEPROCESS Process, __in HANDLE Win32WindowStation)
VOID PsSetThreadHardErrorsAreDisabled (__in PETHREAD Thread, __in BOOLEAN HardErrorsAreDisabled)
VOID PsSetThreadWin32Thread (__inout PETHREAD Thread, __in PVOID Win32Thread, __in PVOID PrevWin32Thread)
Function Documentation
PEPROCESS PsGetCurrentProcess (VOID)
Definition at line 41 of file pshelper.c.
References _PsGetCurrentProcess.
Referenced by CmInitSystem1(), CmNotifyRunDown(), CmpPostApc(), CmpPostApcRunDown(), DbgkExitProcess(), DbgkExitThread(), DbgkForwardException(), DbgkMapViewOfSection(), DbgkpOpenHandles(), DbgkpSendApiMessage(), DbgkpSendApiMessageLpc(), DbgkpSuspendProcess(), DbgkUnMapViewOfSection(), ExHandleTest(), ExMapHandleToPointerEx(), ExpAllocateHandleTable(), ExpMutantInitialization(), ExpRaiseHardError(), ExpWin32SessionCallout(), IoGetCurrentProcess(), IopCloseFile(), IopRaiseHardError(), IopUnloadDriver(), IoRaiseHardError(), Ke386CallBios(), KeContextToKframes(), KiDispatchException(), LpcpCopyRequestData(), LpcpCreatePort(), LpcpDeletePort(), LpcpFindDataInfoMessage(), LpcpFreeDataInfoMessage(), LpcpRequestWaitReplyPort(), LpcpSaveDataInfoMessage(), LpcRequestPort(), MiAccessCheck(), MiAddValidPageToWorkingSet(), MiAddWsleHash(), MiAllocatePagesForMdl(), MiAttachSession(), MiCaptureUlongPtrArray(), MiCcPutPagesInTransition(), MiCloneProcessAddressSpace(), MiCompleteProtoPteFault(), MiCopyHeaderIfResident(), MiCopyOnWrite(), MiCreatePagingFileMap(), MiDecrementCloneBlockReference(), MiDecrementShareCount(), MiDeletePageTablesForPhysicalRange(), MiDeleteVirtualAddresses(), MiDereferenceSession(), MiDereferenceSessionFinal(), MiDetachSession(), MiDoPoolCopy(), MiEliminateWorkingSetEntry(), MiEmptyWorkingSet(), MiFindEmptyAddressRange(), MiFindImageSectionObject(), MiFlushTbAndCapture(), MiFreeLargePages(), MiFreeWsleList(), MiGatherMappedPages(), MiGetPageForHeader(), MiGetPageProtection(), MiGrowWsleHash(), MiInitializeLargePageSupport(), MiInitializePfn(), MiInitMachineDependent(), MiInsertAweInfo(), MiInsertImageSectionObject(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertVad(), MiInsertVadCharges(), MiLoadImageSection(), MiLocateAddress(), MiMakeOutswappedPageResident(), MiMapWithLargePages(), MiMarkSectionWritable(), MiReleasePhysicalCharges(), MiRemoveUserPhysicalPagesVad(), MiRemoveVad(), MiRemoveVadCharges(), MiRestoreTransitionPte(), MiSegmentDelete(), MiSessionAddProcess(), MiSessionCreateInternal(), MiSessionRemoveProcess(), MiSessionWideReserveImageAddress(), MiSnapCopyMemory(), MiUnmapLargePages(), MiUnmapViewOfSection(), MiUnsecureVirtualMemory(), MiUpdateSystemPdes(), MiWaitForInPageComplete(), MiZeroPhysicalPage(), MmAssignProcessToJob(), MmAttachSession(), MmCheckForSafeExecution(), MmCommitSessionMappedView(), MmCopyVirtualMemory(), MmCreateProcessAddressSpace(), MmCreateTeb(), MmDeleteProcessAddressSpace(), MmEnforceWorkingSetLimit(), MmGetExecuteOptions(), MmGetFileNameForAddress(), MmGetImageInformation(), MmGetSessionLocaleId(), MmInitializeHandBuiltProcess(), MmInitializeHandBuiltProcess2(), MmInSwapProcess(), MmLoadSystemImage(), MmMapViewInSessionSpace(), MmMapViewOfSection(), MmOutSwapProcess(), MmProbeAndLockPages(), MmProbeAndLockProcessPages(), MmProbeAndLockSelectedPages(), MmSessionSetUnloadAddress(), MmSetExecuteOptions(), MmSetSessionLocaleId(), MmUnmapViewInSessionSpace(), NtAcceptConnectPort(), NtAreMappedFilesTheSame(), NtDebugActiveProcess(), NtFreeUserPhysicalPages(), NtImpersonateAnonymousToken(), NtNotifyChangeMultipleKeys(), NtOpenObjectAuditAlarm(), NtQueryInformationProcess(), NtReadFileScatter(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetDefaultHardErrorPort(), NtSetSystemInformation(), NtWriteFileGather(), ObDuplicateObject(), ObInitSystem(), ObpAllocateObject(), ObpCaptureObjectCreateInformation(), ObpChargeQuotaForObject(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceDeviceMap(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), ObSetHandleAttributes(), Phase1InitializationDiscard(), PsGetCurrentProcessWin32Process(), PsGetCurrentProcessWow64Process(), PsGetProcessExitTime(), PsInitializeQuotaSystem(), PsLocateSystemDll(), PspInitPhase0(), PspWin32SessionCallout(), PsSetLdtEntries(), PsSetProcessLdtInfo(), PsWatchWorkingSet(), PsWrapApcWow64Thread(), RtlGetCurrentPeb(), RtlpAllocateAtom(), RtlpWalkFrameChain(), SeAuditLPCInvalidUse(), SeAuditSystemTimeChange(), SeCaptureSubjectContext(), SeCreateAccessState(), SeIsChildToken(), SeIsChildTokenByPointer(), SeIsSiblingToken(), SeIsSiblingTokenByPointer(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAuditAssignPrimaryToken(), SepCleanupLUIDDeviceMapDirectory(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), SepInitializationPhase0(), SepInitializationPhase1(), SepRmCommandServerThreadInit(), SeReleaseSubjectContext(), WmiGetClock(), and WmipPumpThreadApc().
ULONG PsGetCurrentProcessSessionId (VOID)
Definition at line 48 of file pshelper.c.
References _PsGetCurrentProcess, and MmGetSessionId().
Referenced by ExpWin32SessionCallout(), NtSetInformationObject(), and ObpLookupObjectName().
PVOID PsGetCurrentProcessWin32Process (VOID)
Definition at line 257 of file pshelper.c.
References PsGetCurrentProcess(), and _EPROCESS::Win32Process.
PVOID PsGetCurrentProcessWow64Process (VOID)
Definition at line 275 of file pshelper.c.
References PS_GET_WOW64_PROCESS, and PsGetCurrentProcess().
PETHREAD PsGetCurrentThread (VOID)
Definition at line 57 of file pshelper.c.
References _PsGetCurrentThread.
Referenced by BuildQueryDirectoryIrp(), CcCopyRead(), CcFastCopyRead(), CcMapAndCopy(), CcMapAndRead(), CcMapData(), CcMapDataCommon(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), CcSetValidData(), CcWorkerThread(), CmpCallCallBacks(), CmpNotifyChangeKey(), DbgkExitProcess(), DbgkExitThread(), DbgkForwardException(), DbgkMapViewOfSection(), DbgkpQueueMessage(), DbgkpSendApiMessage(), DbgkpSetProcessDebugObject(), DbgkUnMapViewOfSection(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExCreateHandle(), ExDestroyHandle(), ExDupHandleTable(), ExFreePoolWithTag(), ExIsResourceAcquiredExclusiveLite(), ExIsResourceAcquiredSharedLite(), ExMapHandleToPointer(), ExMapHandleToPointerEx(), ExpCheckQueueShutdown(), ExpRaiseHardError(), ExpSetSwappingKernelApc(), ExpShutdownWorker(), ExpTimerApcRoutine(), ExpWorkerThread(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), ExSwapinWorkerThreads(), ExTimerRundown(), ExTryToAcquireResourceExclusiveLite(), FsFilterAllocateCompletionStack(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlGetFileSize(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), FsRtlSetFileSize(), FsRtlStackOverflowRead(), FsRtlWorkerThread(), IoAsynchronousPageWrite(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoCancelFileOpen(), IoCancelThreadIo(), IoGetInitialStack(), IoGetTopLevelIrp(), IoPageRead(), IopCloseFile(), IopCompleteRequest(), IopDeleteFile(), IopDisassociateThreadIrp(), IopGetFileInformation(), IopGetSetSecurityObject(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IopUpdateReadOperationCount(), IopUpdateReadTransferCount(), IopUpdateWriteOperationCount(), IopUpdateWriteTransferCount(), IopXxxControlFile(), IoRaiseInformationalHardError(), IoRetryIrpCompletions(), IoSetInformation(), IoSetThreadHardErrorMode(), IoSetTopLevelIrp(), IoSynchronousPageWrite(), IoVerifyVolume(), KeWaitForSingleObject(), LpcExitThread(), LpcpCreatePort(), LpcpDeletePort(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiAllocateLargePages(), MiAllocatePoolPages(), MiAttachAndLockWorkingSet(), MiCcPutPagesInTransition(), MiChargeCommitment(), MiChargeCommitmentPfnLockHeld(), MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MiCloneProcessAddressSpace(), MiCreatePebOrTeb(), MiCreatePhysicalVadRoot(), MiDecommitPages(), MiDecrementCloneBlockReference(), MiDeleteSystemPageableVm(), MiDereferenceSegmentThread(), MiDetachAndUnlockWorkingSet(), MiDispatchFault(), MiDoReplacement(), MiEmptyWorkingSet(), MiEnablePagingTheExecutive(), MiEnsureAvailablePageOrWait(), MiFlushSectionInternal(), MiGetInPageSupportBlock(), MiGetPageProtection(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiIdentifyPfn(), MiIssuePageExtendRequest(), MiLockCode(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MiMapLargePageSection(), MiMapLockedPagesInUserSpace(), MiMappedPageWriter(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiModifiedPageWriterWorker(), MiPhysicalViewRemover(), MiProtectAweRegion(), MiProtectVirtualMemory(), MiQueryAddressState(), MiQueueWorkingSetRequest(), MiRemoveMappedPtes(), MiRemoveMappedView(), MiRemoveVadCharges(), MiResetVirtualMemory(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveTransitionFault(), MiSecureVirtualMemory(), MiSessionCommitPageTables(), MiSessionInsertImage(), MiSessionRemoveImage(), MiSetPageModified(), MiSetPagingOfDriver(), MiSetProtectionOnSection(), MiSetSystemCodeProtection(), MiTrimAllSystemPageableMemory(), MiTrimPte(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MiWaitForForkToComplete(), MiWaitForInPageComplete(), MiZeroInParallel(), MmAccessFault(), MmAdjustWorkingSetSizeEx(), MmCheckCachedPageState(), MmCleanProcessAddressSpace(), MmCopyToCachedPage(), MmDeleteTeb(), MmEnforceWorkingSetLimit(), MmFlushSection(), MmFlushVirtualMemory(), MmFreeLoaderBlock(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmIsRecursiveIoFault(), MmMapLockedPagesSpecifyCache(), MmMapUserAddressesToPage(), MmPrefetchPagesIntoLockedMdl(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmQuerySystemCacheWorkingSetInformation(), MmQueryWorkingSetInformation(), MmResourcesAvailable(), MmSessionCreate(), MmSessionDelete(), MmSetBankedSection(), MmSetPhysicalPagesLimit(), MmUnlockPages(), MmUnmapViewInSystemCache(), MmWorkingSetManager(), NtAcceptConnectPort(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtAssignProcessToJobObject(), NtCancelIoFile(), NtCreateJobObject(), NtCreateJobSet(), NtFlushBuffersFile(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetContextThread(), NtGetWriteWatch(), NtIsProcessInJob(), NtLoadDriver(), NtLockFile(), NtLockVirtualMemory(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtMapViewOfSection(), NtNotifyChangeDirectoryFile(), NtOpenThreadTokenEx(), NtProtectVirtualMemory(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryInformationJobObject(), NtQueryInformationThread(), NtQueryQuotaInformationFile(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtReadVirtualMemory(), NtRegisterThreadTerminatePort(), NtReleaseKeyedEvent(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtResetWriteWatch(), NtSecureConnectPort(), NtSetContextThread(), NtSetEaFile(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetTimer(), NtSetVolumeInformationFile(), NtTerminateJobObject(), NtTerminateProcess(), NtTerminateThread(), NtUnlockFile(), NtUnlockVirtualMemory(), NtWaitForKeyedEvent(), NtWriteFile(), NtWriteFileGather(), NtWriteVirtualMemory(), ObClearProcessHandleTable(), ObDereferenceSecurityDescriptor(), ObInitSystem(), ObLogSecurityDescriptor(), ObpCloseHandle(), ObpReferenceDeviceMap(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PerfProfileInterrupt(), Phase1InitializationDiscard(), PsAssignImpersonationToken(), PsChangeJobMemoryUsage(), PsChangeQuantumTable(), PsConvertToGuiThread(), PsDisableImpersonation(), PsEnforceExecutionTimeLimits(), PsEnumProcesses(), PsExitSpecialApc(), PsGetContextThread(), PsGetCurrentProcessId(), PsGetCurrentThreadId(), PsGetNextJob(), PsGetNextJobProcess(), PsGetNextProcess(), PsGetNextProcessThread(), PsImpersonateClient(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PspAddProcessToJob(), PspApplyJobLimitsToProcess(), PspAssignPrimaryToken(), PspCreateProcess(), PspCreateThread(), PspExitNormalApc(), PspExitProcess(), PspExitProcessFromJob(), PspExitThread(), PspGetJobFromSet(), PspGetSetContextInternal(), PspJobClose(), PspJobDelete(), PspJobTimeLimitsWork(), PspProcessDelete(), PspRemoveProcessFromJob(), PspSetQuotaLimits(), PspShutdownJobLimits(), PspSystemThreadStartup(), PspTerminateAllProcessesInJob(), PspTerminateThreadByPointer(), PspThreadDelete(), PspUserThreadStartup(), PspWriteTebImpersonationInfo(), PsReferenceEffectiveToken(), PsReferenceImpersonationToken(), PsReferencePrimaryToken(), PsReportProcessMemoryLimitViolation(), PsRestoreImpersonation(), PsRevertThreadToSelf(), PsRevertToSelf(), PsSetContextThread(), PsShutdownSystem(), PsSuspendThread(), PsTerminateSystemThread(), RtlCaptureStackBackTrace(), RtlFormatCurrentUserKeyPath(), RtlGetCallersAddress(), RtlWalkFrameChain(), SeCaptureSubjectContext(), SeCreateAccessState(), SeImpersonateClientEx(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), SepInitializationPhase0(), SeTokenCanImpersonate(), WmiGetClock(), WmipAddLogHeader(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipLogger(), WmipPushDirtyBuffer(), WmipPushFreeBuffer(), WmipSendWmiIrp(), WmiReserveWithSystemHeader(), WmiTraceEvent(), WmiTraceKernelEvent(), and WmiTraceMessageVa().
CCHAR PsGetCurrentThreadPreviousMode (VOID)
Definition at line 81 of file pshelper.c.
References KeGetPreviousMode.
PEPROCESS PsGetCurrentThreadProcess (VOID)
Definition at line 319 of file pshelper.c.
References _PsGetCurrentThread, and THREAD_TO_PROCESS.
HANDLE PsGetCurrentThreadProcessId (VOID)
Definition at line 338 of file pshelper.c.
References _PsGetCurrentThread.
PVOID PsGetCurrentThreadStackBase (VOID)
Definition at line 65 of file pshelper.c.
References KeGetCurrentThread(), and _KTHREAD::StackBase.
PVOID PsGetCurrentThreadStackLimit (VOID)
Definition at line 73 of file pshelper.c.
References KeGetCurrentThread(), and _KTHREAD::StackLimit.
PVOID PsGetCurrentThreadTeb (VOID)
Definition at line 365 of file pshelper.c.
References _PsGetCurrentThread.
PVOID PsGetCurrentThreadWin32Thread (VOID)
Definition at line 383 of file pshelper.c.
References _PsGetCurrentThread.
PVOID PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion (__out PHANDLE ProcessId)
Definition at line 392 of file pshelper.c.
References _PsGetCurrentThread, _ETHREAD::Cid, KeEnterCriticalRegionThread(), _ETHREAD::Tcb, _CLIENT_ID::UniqueProcess, and _KTHREAD::Win32Thread.
PERESOURCE PsGetJobLock (__in PEJOB Job)
Definition at line 89 of file pshelper.c.
ULONG PsGetJobSessionId (__in PEJOB Job)
Definition at line 97 of file pshelper.c.
ULONG PsGetJobUIRestrictionsClass (__in PEJOB Job)
Definition at line 105 of file pshelper.c.
LONGLONG PsGetProcessCreateTimeQuadPart (__in PEPROCESS Process)
Definition at line 113 of file pshelper.c.
PVOID PsGetProcessDebugPort (__in PEPROCESS Process)
Definition at line 121 of file pshelper.c.
BOOLEAN PsGetProcessExitProcessCalled (__in PEPROCESS Process)
Definition at line 142 of file pshelper.c.
References PS_PROCESS_FLAGS_PROCESS_EXITING.
NTSTATUS PsGetProcessExitStatus (__in PEPROCESS Process)
Definition at line 150 of file pshelper.c.
HANDLE PsGetProcessId (__in PEPROCESS Process)
Definition at line 158 of file pshelper.c.
UCHAR* PsGetProcessImageFileName (__in PEPROCESS Process)
Definition at line 167 of file pshelper.c.
Referenced by CmpDumpOneKeyBody().
HANDLE PsGetProcessInheritedFromUniqueProcessId (__in PEPROCESS Process)
Definition at line 176 of file pshelper.c.
PEJOB PsGetProcessJob (__in PEPROCESS Process)
Definition at line 185 of file pshelper.c.
PPEB PsGetProcessPeb (__in PEPROCESS Process)
Definition at line 221 of file pshelper.c.
UCHAR PsGetProcessPriorityClass (__in PEPROCESS Process)
Definition at line 230 of file pshelper.c.
PVOID PsGetProcessSectionBaseAddress (__in PEPROCESS Process)
Definition at line 212 of file pshelper.c.
PVOID PsGetProcessSecurityPort (__in PEPROCESS Process)
Definition at line 517 of file pshelper.c.
ULONG PsGetProcessSessionId (__in PEPROCESS Process)
Definition at line 194 of file pshelper.c.
References MmGetSessionId().
ULONG PsGetProcessSessionIdEx (__in PEPROCESS Process)
Definition at line 203 of file pshelper.c.
References MmGetSessionIdEx().
PVOID PsGetProcessWin32Process (__in PEPROCESS Process)
Definition at line 248 of file pshelper.c.
HANDLE PsGetProcessWin32WindowStation (__in PEPROCESS Process)
Definition at line 238 of file pshelper.c.
PVOID PsGetProcessWow64Process (__in PEPROCESS Process)
Definition at line 266 of file pshelper.c.
References PS_GET_WOW64_PROCESS.
CCHAR PsGetThreadFreezeCount (__in PETHREAD Thread)
Definition at line 293 of file pshelper.c.
BOOLEAN PsGetThreadHardErrorsAreDisabled (__in PETHREAD Thread)
Definition at line 302 of file pshelper.c.
References PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED.
HANDLE PsGetThreadId (__in PETHREAD Thread)
Definition at line 284 of file pshelper.c.
PEPROCESS PsGetThreadProcess (__in PETHREAD Thread)
Definition at line 310 of file pshelper.c.
References THREAD_TO_PROCESS.
HANDLE PsGetThreadProcessId (__in PETHREAD Thread)
Definition at line 329 of file pshelper.c.
ULONG PsGetThreadSessionId (__in PETHREAD Thread)
Definition at line 347 of file pshelper.c.
References MmGetSessionId(), and THREAD_TO_PROCESS.
PVOID PsGetThreadTeb (__in PETHREAD Thread)
Definition at line 356 of file pshelper.c.
PVOID PsGetThreadWin32Thread (__in PETHREAD Thread)
Definition at line 374 of file pshelper.c.
BOOLEAN PsIsProcessBeingDebugged (__in PEPROCESS Process)
Definition at line 130 of file pshelper.c.
References FALSE, NULL, and TRUE.
BOOLEAN PsIsSystemProcess (__in PEPROCESS Process)
Definition at line 413 of file pshelper.c.
References PsInitialSystemProcess.
BOOLEAN PsIsSystemThread (__in PETHREAD Thread)
Definition at line 404 of file pshelper.c.
References IS_SYSTEM_THREAD.
BOOLEAN PsIsThreadImpersonating (__in PETHREAD Thread)
Definition at line 537 of file pshelper.c.
References PAGED_CODE, and PS_IS_THREAD_IMPERSONATING.
NTSTATUS PsReferenceProcessFilePointer (IN PEPROCESS Process, OUT PVOID * OutFileObject)
Definition at line 563 of file pshelper.c.
References ExAcquireRundownProtection(), ExReleaseRundownProtection(), MmGetFileObjectForSection(), NULL, ObReferenceObject, PAGED_CODE, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
Referenced by SeLocateProcessImageName().
VOID PsSetJobUIRestrictionsClass (__out PEJOB Job, __in ULONG UIRestrictionsClass)
Definition at line 422 of file pshelper.c.
VOID PsSetProcessPriorityClass (__out PEPROCESS Process, __in UCHAR PriorityClass)
Definition at line 432 of file pshelper.c.
NTSTATUS PsSetProcessSecurityPort (__out PEPROCESS Process, __in PVOID Port)
Definition at line 526 of file pshelper.c.
References STATUS_SUCCESS.
NTSTATUS PsSetProcessWin32Process (__in PEPROCESS Process, __in PVOID Win32Process, __in PVOID PrevWin32Process)
Definition at line 442 of file pshelper.c.
References _PsGetCurrentThread, NULL, PS_PROCESS_FLAGS_PROCESS_DELETE, PspLockProcessExclusive(), PspUnlockProcessExclusive(), Status, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
VOID PsSetProcessWindowStation (__out PEPROCESS Process, __in HANDLE Win32WindowStation)
Definition at line 478 of file pshelper.c.
VOID PsSetThreadHardErrorsAreDisabled (__in PETHREAD Thread, __in BOOLEAN HardErrorsAreDisabled)
Definition at line 488 of file pshelper.c.
References PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, and PS_SET_BITS.
VOID PsSetThreadWin32Thread (__inout PETHREAD Thread, __in PVOID Win32Thread, __in PVOID PrevWin32Thread)
Definition at line 502 of file pshelper.c.
References InterlockedCompareExchangePointer, InterlockedExchangePointer, and NULL.