Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/parse.c File Reference
parse.c File Reference
#include "iomgr.h"
Macros
#define COPY_ATTRIBUTES(n, b, s)
#define IO_MAX_REMOUNT_REPARSE_ATTEMPTS 32
#define RoundNameSize(Length)
Functions
VOID IopCheckBackupRestorePrivilege (IN PACCESS_STATE AccessState, IN OUT PULONG CreateOptions, IN KPROCESSOR_MODE PreviousMode, IN ULONG Disposition)
NTSTATUS IopCheckDeviceAndDriver (IN POPEN_PACKET op, IN PDEVICE_OBJECT parseDeviceObject)
NTSTATUS IopCheckTopDeviceHint (IN OUT PDEVICE_OBJECT *TargetDeviceObject, IN POPEN_PACKET Op, IN BOOLEAN DirectDeviceOpen)
PVPB IopCheckVpbMounted (IN POPEN_PACKET op, IN PDEVICE_OBJECT parseDeviceObject, IN OUT PUNICODE_STRING RemainingName, OUT PNTSTATUS status)
VOID IopDereferenceVpbAndFree (IN PVPB Vpb)
NTSTATUS IopGetNetworkOpenInformation (IN PFILE_OBJECT FileObject, IN POPEN_PACKET Op)
NTSTATUS IopParseDevice (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
NTSTATUS IopParseFile (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
NTSTATUS IopQueryName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
NTSTATUS IopQueryNameInternal (IN PVOID Object, IN BOOLEAN HasObjectName, IN BOOLEAN UseDosDeviceName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Macro Definition Documentation
#define COPY_ATTRIBUTES (n, b, s)
Value:
{                                    \
        (n)->CreationTime.QuadPart = (b)->CreationTime.QuadPart;        \
        (n)->LastAccessTime.QuadPart = (b)->LastAccessTime.QuadPart;    \
        (n)->LastWriteTime.QuadPart = (b)->LastWriteTime.QuadPart;      \
        (n)->ChangeTime.QuadPart = (b)->ChangeTime.QuadPart;            \
        (n)->AllocationSize.QuadPart = (s)->AllocationSize.QuadPart;    \
        (n)->EndOfFile.QuadPart = (s)->EndOfFile.QuadPart;              \
        (n)->FileAttributes = (b)->FileAttributes; }
Referenced by IopGetNetworkOpenInformation().
#define IO_MAX_REMOUNT_REPARSE_ATTEMPTS 32
Definition at line 30 of file parse.c.
Referenced by IopParseDevice().
#define RoundNameSize (Length)
Value:
(\
    (Length < 64 - 8) ? 64 - 8 :  \
    (Length < 128 - 8) ? 128 - 8 :\
    (Length < 256 - 8) ? 256 - 8 : Length )
Definition at line 25 of file parse.c.
Referenced by IopParseDevice().
Function Documentation
VOID IopCheckBackupRestorePrivilege (IN PACCESS_STATE AccessState, IN OUT PULONG CreateOptions, IN KPROCESSOR_MODE PreviousMode, IN ULONG Disposition)
Definition at line 2517 of file parse.c.
References ACCESS_SYSTEM_SECURITY, _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, DELETE, FALSE, FILE_ADD_FILE, FILE_ADD_SUBDIRECTORY, FILE_GENERIC_READ, FILE_GENERIC_WRITE, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_IF, FILE_OVERWRITE_IF, FILE_TRAVERSE, _LUID_AND_ATTRIBUTES::Luid, MAXIMUM_ALLOWED, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, READ_CONTROL, SE_BACKUP_PRIVILEGES_CHECKED, SeAppendPrivileges(), SeBackupPrivilege, SePrivilegeCheck(), SeRestorePrivilege, TOKEN_HAS_BACKUP_PRIVILEGE, TOKEN_HAS_RESTORE_PRIVILEGE, TRUE, VOID, WRITE_DAC, and WRITE_OWNER.
Referenced by IopParseDevice().
NTSTATUS IopCheckDeviceAndDriver (IN POPEN_PACKET op, IN PDEVICE_OBJECT parseDeviceObject)
Definition at line 56 of file parse.c.
References DO_DEVICE_INITIALIZING, DO_EXCLUSIVE, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_START_PENDING, DOE_UNLOAD_PENDING, IO_ATTACH_DEVICE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, STATUS_ACCESS_DENIED, STATUS_NO_SUCH_DEVICE, and STATUS_SUCCESS.
Referenced by IopParseDevice().
NTSTATUS IopCheckTopDeviceHint (IN OUT PDEVICE_OBJECT * TargetDeviceObject, IN POPEN_PACKET Op, IN BOOLEAN DirectDeviceOpen)
Definition at line 234 of file parse.c.
References FALSE, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DFS_FILE_SYSTEM, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, IopVerifyDeviceObjectOnStack(), STATUS_INVALID_DEVICE_OBJECT_PARAMETER, STATUS_INVALID_PARAMETER, STATUS_MOUNT_POINT_NOT_RESOLVED, and STATUS_SUCCESS.
Referenced by IopParseDevice().
PVPB IopCheckVpbMounted (IN POPEN_PACKET op, IN PDEVICE_OBJECT parseDeviceObject, IN OUT PUNICODE_STRING RemainingName, OUT PNTSTATUS status)
Definition at line 107 of file parse.c.
References FALSE, FILE_SYNCHRONOUS_IO_ALERT, _VPB::Flags, IopDecrementDeviceObjectRef(), IopMountVolume(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoVpbLock, NT_SUCCESS, NULL, _VPB::ReferenceCount, STATUS_ACCESS_DENIED, STATUS_ALERTED, STATUS_USER_APC, STATUS_WRONG_VOLUME, TRUE, VPB_LOCKED, and VPB_MOUNTED.
Referenced by IopParseDevice().
VOID IopDereferenceVpbAndFree (IN PVPB Vpb)
Definition at line 211 of file parse.c.
References ExFreePool(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoVpbLock, NULL, and VPB_PERSISTENT.
Referenced by IopParseDevice(), and IoVerifyVolume().
NTSTATUS IopGetNetworkOpenInformation (IN PFILE_OBJECT FileObject, IN POPEN_PACKET Op)
Definition at line 1899 of file parse.c.
References COPY_ATTRIBUTES, FileBasicInformation, FileStandardInformation, IoQueryFileInformation(), NT_SUCCESS, and PAGED_CODE.
Referenced by IopParseDevice().
NTSTATUS IopParseDevice (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 304 of file parse.c.
References ACCESS_SYSTEM_SECURITY, _IO_SECURITY_CONTEXT::AccessState, _OPEN_PACKET::AllocationSize, APC_LEVEL, ASSERT, _OPEN_PACKET::BasicInformation, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, _IO_STACK_LOCATION::Control, _OPEN_PACKET::CreateFileType, CreateFileTypeNamedPipe, CreateFileTypeNone, _OPEN_PACKET::CreateOptions, _FILE_OBJECT::CurrentByteOffset, _OPEN_PACKET::DeleteOnly, _IO_SECURITY_CONTEXT::DesiredAccess, _VPB::DeviceObject, _FILE_OBJECT::DeviceObject, _IO_STACK_LOCATION::DeviceObject, _OPEN_PACKET::Disposition, DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN, _OPEN_PACKET::EaBuffer, _OPEN_PACKET::EaLength, _FILE_OBJECT::Event, ExAcquireResourceSharedLite(), ExAllocatePool, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExReleaseResourceLite(), _OPEN_PACKET::ExtraCreateParameters, FALSE, _FAST_IO_DISPATCH::FastIoQueryBasicInfo, _FAST_IO_DISPATCH::FastIoQueryNetworkOpenInfo, _FAST_IO_DISPATCH::FastIoQueryOpen, FIELD_OFFSET, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_SECURE_OPEN, FILE_DEVICE_TAPE, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_DEVICE_VIRTUAL_DISK, FILE_NO_INTERMEDIATE_BUFFERING, FILE_RANDOM_ACCESS, FILE_READ_ATTRIBUTES, FILE_SEQUENTIAL_ONLY, FILE_SYNCHRONOUS_IO_ALERT, FILE_SYNCHRONOUS_IO_NONALERT, FILE_TRAVERSE, FILE_WRITE_THROUGH, _OPEN_PACKET::FileAttributes, _FILE_BASIC_INFORMATION::FileAttributes, _FILE_NETWORK_OPEN_INFORMATION::FileAttributes, FileBasicInformation, _FILE_OBJECT::FileName, FileNetworkOpenInformation, _OPEN_PACKET::FileObject, _IO_STACK_LOCATION::FileObject, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, _IOP_FILE_OBJECT_EXTENSION::FilterContext, _OPEN_PACKET::FinalStatus, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, FO_FILE_OPEN_CANCELLED, FO_NO_INTERMEDIATE_BUFFERING, FO_OPENED_CASE_SENSITIVE, FO_RANDOM_ACCESS, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, FO_VOLUME_OPEN, FO_WRITE_THROUGH, _OPEN_PACKET::FullAttributes, _IO_SECURITY_CONTEXT::FullCreateOptions, _OBJECT_TYPE_INITIALIZER::GenericMapping, _KEVENT::Header, _OPEN_PACKET::Information, _IO_STATUS_BLOCK::Information, InitializeObjectAttributes, _OPEN_PACKET::InternalFlags, IO_FORCE_ACCESS_CHECK, IO_MAX_REMOUNT_REPARSE_ATTEMPTS, IO_REMOUNT, IO_REPARSE, IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_RESERVED_ONE, IO_REPARSE_TAG_RESERVED_ZERO, IO_TYPE_FILE, IO_TYPE_OPEN_PACKET, IoCallDriver(), IoFileObjectType, IoFreeIrp(), IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IOP_CREATE_DEVICE_OBJECT_EXTENSION, IOP_CREATE_IGNORE_SHARE_ACCESS_CHECK, IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT, IopAllocateIrp, IopCheckBackupRestorePrivilege(), IopCheckDeviceAndDriver(), IopCheckTopDeviceHint(), IopCheckVpbMounted(), IopDecrementDeviceObjectRef(), IopDeleteFile(), IopDequeueThreadIrp, IopDereferenceVpbAndFree(), IopDoNameTransmogrify(), IopGetNetworkOpenInformation(), IopInterlockedIncrementUlong(), IopPerfLogFileCreate(), IopQueueThreadIrp(), IopSecurityResource, IoQueryFileInformation(), IoSetNextIrpStackLocation, IRP_BUFFERED_IO, IRP_CREATE_OPERATION, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_MJ_CREATE, IRP_MJ_CREATE_MAILSLOT, IRP_MJ_CREATE_NAMED_PIPE, IRP_SYNCHRONOUS_API, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeInitializeEvent(), KeLeaveCriticalRegionThread(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, _OPEN_PACKET::LocalFileObject, _FILE_OBJECT::Lock, LockQueueIoVpbLock, _IO_STACK_LOCATION::MajorFunction, MAXIMUM_ALLOWED, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, _UNICODE_STRING::MaximumLength, _OPEN_PACKET::NetworkInformation, NonPagedPool, NOTHING, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, _DUMMY_FILE_OBJECT::ObjectHeader, ObReferenceObject, OPEN_PACKET_PATTERN, _OPEN_PACKET::Options, _OPEN_PACKET::Override, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, _OPEN_PACKET::ParseCheck, PIRP, _OBJECT_HEADER::PointerCount, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _OPEN_PACKET::QueryOnly, READ_CONTROL, _VPB::ReferenceCount, _OPEN_PACKET::RelatedFileObject, _FILE_OBJECT::RelatedFileObject, _REPARSE_DATA_BUFFER::ReparseDataLength, _REPARSE_DATA_BUFFER::ReparseTag, _REPARSE_DATA_BUFFER::Reserved, RoundNameSize, RtlCopyMemory, RtlCopyUnicodeString(), RtlMapGenericMask(), RtlZeroMemory, SE_BACKUP_PRIVILEGES_CHECKED, SeAccessCheck(), SeAppendPrivileges(), _IO_SECURITY_CONTEXT::SecurityQos, SeFastTraverseCheck(), SeFreePrivileges(), SeLockSubjectContext(), SeOpenObjectAuditAlarm(), SeSetAccessStateGenericMapping(), SeUnlockSubjectContext(), _OPEN_PACKET::ShareAccess, _DISPATCHER_HEADER::SignalState, _OPEN_PACKET::Size, _FILE_OBJECT::Size, _FAST_IO_DISPATCH::SizeOfFastIoDispatch, SL_CASE_SENSITIVE, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_IO_REPARSE_DATA_INVALID, STATUS_NOT_IMPLEMENTED, STATUS_OBJECT_TYPE_MISMATCH, STATUS_PENDING, STATUS_REPARSE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, SynchronizationEvent, SYNCHRONIZE, _ETHREAD::Tcb, TOKEN_HAS_TRAVERSE_PRIVILEGE, _IOP_FILE_OBJECT_EXTENSION::TopDeviceObjectHint, _OPEN_PACKET::TraversedMountPoint, TRUE, _OPEN_PACKET::Type, _OBJECT_HEADER::Type, _FILE_OBJECT::Type, _OBJECT_TYPE::TypeInfo, UNREFERENCED_PARAMETER, UserMode, VOID, _FILE_OBJECT::Vpb, _FILE_OBJECT::Waiters, WRITE_DAC, and WRITE_OWNER.
Referenced by IopCreateObjectTypes(), and IopParseFile().
NTSTATUS IopParseFile (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 1978 of file parse.c.
References IO_TYPE_OPEN_PACKET, IoGetRelatedDeviceObject(), IopParseDevice(), NULL, PAGED_CODE, _OPEN_PACKET::RelatedFileObject, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, and _OPEN_PACKET::Type.
Referenced by IopCreateObjectTypes().
NTSTATUS IopQueryName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 2465 of file parse.c.
References FALSE, IopQueryNameInternal(), and UNREFERENCED_PARAMETER.
Referenced by IopCreateObjectTypes().
NTSTATUS IopQueryNameInternal (IN PVOID Object, IN BOOLEAN HasObjectName, IN BOOLEAN UseDosDeviceName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 2099 of file parse.c.
References ASSERT, _UNICODE_STRING::Buffer, _FILE_OBJECT::DeviceObject, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, FILE_DEVICE_NETWORK_FILE_SYSTEM, _FILE_NAME_INFORMATION::FileName, FileNameInformation, _FILE_NAME_INFORMATION::FileNameLength, _FILE_OBJECT::Flags, FO_SYNCHRONOUS_IO, IopGetFileInformation(), IopQueryXxxInformation(), IoVolumeDeviceToDosName(), KernelMode, leave, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_NAME_INFORMATION::Name, NT_ERROR, NT_SUCCESS, OBJ_NAME_PATH_SEPARATOR, ObQueryNameString(), PAGED_CODE, PagedPool, RtlCopyMemory, STATUS_BUFFER_OVERFLOW, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_OBJECT_PATH_INVALID, STATUS_SUCCESS, TRUE, UNREFERENCED_PARAMETER, and UserMode.
Referenced by IopQueryName(), and IoQueryFileDosDeviceName().