Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/tracep.h File Reference
tracep.h File Reference
#include <strsafe.h>
Data Structures
struct _WMI_LOGGER_CONTEXT
struct _WMI_LOGGER_MODE
Macros
#define BYTES_PER_MB 1048576
#define KERNEL_LOGGER (0)
#define MAX_FILE_TABLE_SIZE 64
#define MAX_WMI_BUFFER_SIZE 1024
#define PERF_LOG_NO_TRANSITION 0
#define PERF_LOG_START_TRANSITION 1
#define PERF_LOG_STOP_TRANSITION 2
#define REQUEST_FLAG_CIRCULAR_PERSIST 0x00010000
#define REQUEST_FLAG_CIRCULAR_TRANSITION 0x00020000
#define REQUEST_FLAG_FLUSH_BUFFERS 0x00000002
#define REQUEST_FLAG_NEW_FILE 0x00000001
#define TRACE_MAXIMUM_NP_POOL_USAGE 10
#define TraceDebug(x)
#define TRACEPOOLTAG 'timW'
#define WMI_CTXSWAP_EVENTSIZE_ALIGNMENT 8
#define WMI_FREE_TRACE_BUFFER(Buffer)
#define WmipAcquireMutex(x)
#define WmipDereferenceLogger(Id) InterlockedDecrement(&WmipRefCount[Id])
#define WmipGetLoggerContext(LoggerId)
#define WmipInitializeMutex(x) KeInitializeMutex((x), 0)
#define WmipIsValidLogger(L)
#define WmipReferenceLogger(Id) InterlockedIncrement(&WmipRefCount[Id])
#define WmipReleaseMutex(x) KeReleaseMutex((x), FALSE)
Typedefs
typedef struct _WMI_LOGGER_CONTEXT * PWMI_LOGGER_CONTEXT
typedef struct _WMI_LOGGER_MODE * PWMI_LOGGER_MODE
typedef struct _WMI_LOGGER_CONTEXT WMI_LOGGER_CONTEXT
typedef struct _WMI_LOGGER_MODE WMI_LOGGER_MODE
Functions
NTSTATUS WmipAddLogHeader (IN PWMI_LOGGER_CONTEXT LoggerContext, IN OUT PWMI_BUFFER_HEADER Buffer)
NTSTATUS WmipAdjustFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext)
ULONG WmipAllocateFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG NumberOfBuffers)
NTSTATUS WmipCreateDirectoryFile (IN PWCHAR DirFileName, IN BOOLEAN IsDirectory, OUT PHANDLE FileHandle, ULONG Append)
NTSTATUS WmipCreateNtFileName (IN PWCHAR strFileName, OUT PWCHAR *strNtFileName)
NTSTATUS WmipDelayCreate (OUT PHANDLE FileHandle, IN OUT PUNICODE_STRING FileName, IN ULONG Append)
VOID FASTCALL WmipDisableKernelTrace (IN ULONG EnableFlags)
VOID FASTCALL WmipEnableKernelTrace (IN ULONG EnableFlags)
PVOID WmipExtendBase (IN PWMI_LOGGER_CONTEXT Base, IN ULONG Size)
NTSTATUS WmipFlushActiveBuffers (IN PWMI_LOGGER_CONTEXT, IN ULONG FlushAll)
NTSTATUS WmipFlushBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PWMI_BUFFER_HEADER Buffer, IN USHORT BufferFlag)
NTSTATUS WmipFlushLogger (IN OUT PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG Wait)
VOID WmipFreeLoggerContext (IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipGenerateFileName (IN PUNICODE_STRING FilePattern, IN OUT PLONG FileCounter, OUT PUNICODE_STRING FileName)
PWMI_BUFFER_HEADER WmipGetFreeBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext)
__inline __int64 WmipGetPerfCounter ()
__inline __int64 WmipGetSystemTime ()
PWMI_LOGGER_CONTEXT FASTCALL WmipIsLoggerOn (IN ULONG LoggerId)
VOID WmipLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS FASTCALL WmipNotifyLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipNtDllLoggerInfo (PWMINTDLLLOGGERINFO Buffer)
PWMI_BUFFER_HEADER FASTCALL WmipPopFreeContextSwapBuffer (UCHAR CurrentProcessor)
VOID FASTCALL WmipPushDirtyContextSwapBuffer (UCHAR CurrentProcessor, PWMI_BUFFER_HEADER Buffer)
NTSTATUS WmipQueryGLRegistryRoutine (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
NTSTATUS WmipQueryLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo, IN PWMI_LOGGER_CONTEXT LoggerContext)
ULONG FASTCALL WmipReleaseTraceBuffer (IN PWMI_BUFFER_HEADER Buffer, IN PWMI_LOGGER_CONTEXT LoggerContext)
PVOID FASTCALL WmipReserveTraceBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG RequiredSize, OUT PWMI_BUFFER_HEADER *BufferResource, OUT PLARGE_INTEGER TimeStamp)
VOID FASTCALL WmipResetBufferHeader (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer, USHORT BufferType)
NTSTATUS WmipSendNotification (PWMI_LOGGER_CONTEXT LoggerContext, NTSTATUS Status, ULONG Flag)
VOID WmipSetTraceNotify (IN PDEVICE_OBJECT DeviceObject, IN ULONG TraceClass, IN ULONG Enable)
NTSTATUS WmipShutdown (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
VOID WmipStartGlobalLogger ()
NTSTATUS WmipStartLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTSTATUS WmipStopLoggerInstance (IN PWMI_LOGGER_CONTEXT LoggerContext)
VOID WmipValidateClockType (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTSTATUS WmipVerifyLoggerInfo (IN PWMI_LOGGER_INFORMATION LoggerInfo, OUT PWMI_LOGGER_CONTEXT *LoggerContext)
PSYSTEM_TRACE_HEADER FASTCALL WmiReserveWithSystemHeader (IN ULONG LoggerId, IN ULONG AuxSize, IN PETHREAD Thread, OUT PVOID *BufferResource)
Variables
PSECURITY_DESCRIPTOR EtwpDefaultTraceSecurityDescriptor
LARGE_INTEGER WmiOneSecond
PWMI_BUFFER_HEADER WmipContextSwapProcessorBuffers [MAXIMUM_PROCESSORS]
ULONG WmipEventLogger
PFILE_OBJECT * WmipFileTable
WMI_TRACE_BUFFER_CALLBACK WmipGlobalBufferCallback
ULONG WmipGlobalSequence
ULONG WmipKernelLogger
PWMI_LOGGER_CONTEXT WmipLoggerContext [MAXLOGGERS]
ULONG WmipPtrSize
LONG WmipRefCount [MAXLOGGERS]
KGUARDED_MUTEX WmipTraceGuardedMutex
LARGE_INTEGER WmiShortTime
ULONG WmiTraceAlignment
ULONG WmiUsePerfClock
ULONG WmiWriteFailureLimit
Macro Definition Documentation
#define BYTES_PER_MB 1048576
Definition at line 30 of file tracep.h.
Referenced by WmipFlushBuffer().
#define KERNEL_LOGGER (0)
Definition at line 26 of file tracep.h.
Referenced by WmiStopTrace().
#define MAX_FILE_TABLE_SIZE 64
Definition at line 25 of file tracep.h.
Referenced by WmipDisableKernelTrace(), WmipStartLogger(), and WmipTraceIo().
#define MAX_WMI_BUFFER_SIZE 1024
Definition at line 24 of file tracep.h.
Referenced by WmipStartLogger().
#define PERF_LOG_NO_TRANSITION 0
Definition at line 112 of file tracep.h.
Referenced by WmipStartLogger(), WmipStopLoggerInstance(), and WmiUpdateTrace().
#define PERF_LOG_START_TRANSITION 1
Definition at line 113 of file tracep.h.
Referenced by WmipStartLogger(), WmipStopLoggerInstance(), and WmiUpdateTrace().
#define PERF_LOG_STOP_TRANSITION 2
Definition at line 114 of file tracep.h.
Referenced by WmipStopLoggerInstance().
#define REQUEST_FLAG_CIRCULAR_PERSIST 0x00010000
Definition at line 34 of file tracep.h.
Referenced by WmipFlushBuffer(), WmipGetFreeBuffer(), WmipStartLogger(), WmiTraceEvent(), and WmiTraceMessageVa().
#define REQUEST_FLAG_CIRCULAR_TRANSITION 0x00020000
Definition at line 35 of file tracep.h.
Referenced by WmipFinalizeHeader(), WmipFlushBuffer(), WmipLogger(), WmiTraceEvent(), and WmiTraceMessageVa().
#define REQUEST_FLAG_FLUSH_BUFFERS 0x00000002
Definition at line 33 of file tracep.h.
Referenced by WmipFlushLogger(), and WmipLogger().
#define REQUEST_FLAG_NEW_FILE 0x00000001
Definition at line 32 of file tracep.h.
Referenced by WmipCreateLogFile(), WmipFlushBuffer(), WmipLogger(), WmipSwitchToNewFile(), and WmiUpdateTrace().
#define TRACE_MAXIMUM_NP_POOL_USAGE 10
Definition at line 29 of file tracep.h.
Referenced by WmipAllocateTraceBufferPool(), WmipStartLogger(), and WmiUpdateTrace().
#define TraceDebug (x)
Definition at line 361 of file tracep.h.
Referenced by NtTraceEvent(), WmiFlushTrace(), WmiGetClockType(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipCreateDirectoryFile(), WmipCreateLogFile(), WmipFlushActiveBuffers(), WmipFlushBuffer(), WmipFlushBuffersWithMarker(), WmipFlushLogger(), WmipFreeLoggerContext(), WmipFreeTraceBufferPool(), WmipGetFreeBuffer(), WmipLogger(), WmipPrepareHeader(), WmipPushDirtyBuffer(), WmipPushFreeBuffer(), WmipQueryLogger(), WmipRequestLogFile(), WmipShutdown(), WmipStartLogger(), WmipSwitchBuffer(), WmipSwitchToNewFile(), WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipVerifyLoggerInfo(), WmiReserveWithPerfHeader(), WmiReserveWithSystemHeader(), WmiSetTraceBufferCallback(), WmiStopTrace(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceMessageVa(), WmiTraceProcess(), WmiTraceThread(), WmiTraceUserMessage(), and WmiUpdateTrace().
#define TRACEPOOLTAG 'timW'
Definition at line 36 of file tracep.h.
Referenced by WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipCreateLogFile(), WmipCreateNtFileName(), WmipDelayCreate(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipFlushBuffersWithMarker(), WmipGenerateFileName(), WmipInitContext(), WmipStartLogger(), WmipSwitchToNewFile(), WmipTraceIo(), and WmiUpdateTrace().
#define WMI_CTXSWAP_EVENTSIZE_ALIGNMENT 8
Definition at line 71 of file tracep.h.
Referenced by WmipPopFreeContextSwapBuffer(), and WmiTraceContextSwap().
#define WMI_FREE_TRACE_BUFFER (Buffer)
Value:
ASSERT(Buffer->ReferenceCount == 0);\
                                      ExFreePool(Buffer);
Definition at line 77 of file tracep.h.
Referenced by WmipFreeTraceBufferPool().
#define WmipAcquireMutex (x)
Value:
KeWaitForSingleObject((x), Executive, KernelMode,\
                            FALSE, NULL)
Definition at line 64 of file tracep.h.
Referenced by WmipStartLogger(), and WmipVerifyLoggerInfo().
#define WmipDereferenceLogger (Id) InterlockedDecrement(&WmipRefCount[Id])
Definition at line 51 of file tracep.h.
Referenced by NtTraceEvent(), WmiFlushTrace(), WmiGetClockType(), WmipFreeLoggerContext(), WmipQueryLogger(), WmipReleaseTraceBuffer(), WmipStartLogger(), WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipVerifyLoggerInfo(), WmiQueryTraceInformation(), WmiReserveWithPerfHeader(), WmiReserveWithSystemHeader(), WmiSetTraceBufferCallback(), WmiStopTrace(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceMessageVa(), WmiTraceProcess(), WmiTraceThread(), and WmiUpdateTrace().
#define WmipGetLoggerContext (LoggerId)
Value:
(LoggerId < MAXLOGGERS) ? \
            WmipLoggerContext[LoggerId] : NULL
Definition at line 55 of file tracep.h.
Referenced by NtTraceEvent(), WmiGetClockType(), WmipVerifyLoggerInfo(), WmiReserveWithPerfHeader(), WmiReserveWithSystemHeader(), WmiSetTraceBufferCallback(), WmiTraceEvent(), WmiTraceFastEvent(), and WmiTraceMessageVa().
#define WmipInitializeMutex (x) KeInitializeMutex((x), 0)
Definition at line 63 of file tracep.h.
Referenced by WmipStartLogger().
#define WmipIsValidLogger (L)
Value:
(((L) != NULL) && ((L) != (PWMI_LOGGER_CONTEXT) &WmipLoggerContext[0])\
        ? TRUE : FALSE)
Definition at line 59 of file tracep.h.
Referenced by NtTraceEvent(), WmiGetClockType(), WmipIsLoggerOn(), WmipPopFreeContextSwapBuffer(), WmipPushDirtyContextSwapBuffer(), WmipReserveTraceBuffer(), WmipVerifyLoggerInfo(), WmiQueryTraceInformation(), WmiSetTraceBufferCallback(), WmiStopContextSwapTrace(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), and WmiTraceMessageVa().
#define WmipReferenceLogger (Id) InterlockedIncrement(&WmipRefCount[Id])
Definition at line 48 of file tracep.h.
Referenced by NtTraceEvent(), WmiGetClockType(), WmipStartLogger(), WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipVerifyLoggerInfo(), WmiQueryTraceInformation(), WmiReserveWithPerfHeader(), WmiReserveWithSystemHeader(), WmiSetTraceBufferCallback(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceMessageVa(), WmiTraceProcess(), and WmiTraceThread().
#define WmipReleaseMutex (x) KeReleaseMutex((x), FALSE)
Definition at line 66 of file tracep.h.
Referenced by WmiFlushTrace(), WmipQueryLogger(), WmipStartLogger(), WmipVerifyLoggerInfo(), WmiStopTrace(), and WmiUpdateTrace().
Typedef Documentation
typedef struct _WMI_LOGGER_CONTEXT * PWMI_LOGGER_CONTEXT
typedef struct _WMI_LOGGER_MODE * PWMI_LOGGER_MODE
typedef struct _WMI_LOGGER_CONTEXT WMI_LOGGER_CONTEXT
typedef struct _WMI_LOGGER_MODE WMI_LOGGER_MODE
Function Documentation
NTSTATUS WmipAddLogHeader (IN PWMI_LOGGER_CONTEXT LoggerContext, IN OUT PWMI_BUFFER_HEADER Buffer)
Definition at line 285 of file globalog.c.
References ALIGN_TO_POWER2, ASSERT, _ETHREAD::Cid, EVENT_TRACE_GROUP_HEADER, ExAllocatePoolWithTag, ExFreePool(), FALSE, _WMI_TRACE_PACKET::Group, HandleToUlong, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), KeBootTime, KeMaximumIncrement, KeNumberProcessors, KeQueryPerformanceCounter(), KeQuerySystemTime(), _SYSTEM_TRACE_HEADER::KernelTime, _KTHREAD::KernelTime, _SYSTEM_TRACE_HEADER::Marker, NonPagedPool, NtBuildNumber, NtMajorVersion, NtMinorVersion, NULL, _SYSTEM_TRACE_HEADER::Packet, PPerfGlobalGroupMask, PsGetCurrentThread(), PSLIST_ENTRY, PtrToUlong, _LARGE_INTEGER::QuadPart, RtlCopyMemory, RtlQueryTimeZoneInformation(), RtlZeroMemory, _WMI_TRACE_PACKET::Size, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_SUCCESS, SYSTEM_TRACE_MARKER, _SYSTEM_TRACE_HEADER::SystemTime, _ETHREAD::Tcb, _SYSTEM_TRACE_HEADER::ThreadId, TRACE_VERSION_MAJOR, TRACE_VERSION_MINOR, TraceDebug, TRACEPOOLTAG, TRUE, _WMI_TRACE_PACKET::Type, UNICODE_NULL, _CLIENT_ID::UniqueThread, _SYSTEM_TRACE_HEADER::UserTime, _KTHREAD::UserTime, WMI_BUFFER_FLAG_NORMAL, WMI_BUFFER_TYPE_RUNDOWN, WmipFlushBuffer(), WmipGetFreeBuffer(), WmipKernelLogger, WmipLoggerContext, WmipResetBufferHeader(), and WmiTraceAlignment.
Referenced by WmipSwitchToNewFile().
NTSTATUS WmipAdjustFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 358 of file tracelog.c.
References ExQueryDepthSList, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, and WmipAllocateFreeBuffers().
Referenced by WmipFlushBuffersWithMarker(), and WmipLogger().
ULONG WmipAllocateFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG NumberOfBuffers)
Definition at line 259 of file tracelog.c.
References _WMI_BUFFER_HEADER::CurrentOffset, ExAllocatePoolWithTag, _WMI_BUFFER_STATE::Free, _WMI_BUFFER_HEADER::GlobalEntry, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), KeQuerySystemTime(), NULL, PSLIST_ENTRY, RtlZeroMemory, _WMI_BUFFER_HEADER::SlistEntry, _WMI_BUFFER_HEADER::State, _WMI_BUFFER_HEADER::TimeStamp, TraceDebug, and TRACEPOOLTAG.
Referenced by NtTraceEvent(), WmipAdjustFreeBuffers(), and WmipAllocateTraceBufferPool().
NTSTATUS WmipCreateDirectoryFile (IN PWCHAR DirFileName, IN BOOLEAN IsDirectory, OUT PHANDLE FileHandle, ULONG Append)
NTSTATUS WmipCreateNtFileName (IN PWCHAR strFileName, OUT PWCHAR * strNtFileName)
Definition at line 714 of file globalog.c.
References DOSDEVICES, ExAllocatePoolWithTag, ExFreePool(), FAILED, NULL, PagedPool, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_SUCCESS, StringCbPrintfW(), TRACEPOOLTAG, UNCDEVICES, UNICODE_NULL, and wcslen().
Referenced by WmipCreateLogFile(), WmipDelayCreate(), and WmiStartTrace().
NTSTATUS WmipDelayCreate (OUT PHANDLE FileHandle, IN OUT PUNICODE_STRING FileName, IN ULONG Append)
Definition at line 532 of file globalog.c.
References _UNICODE_STRING::Buffer, DEFAULT_GLOBAL_DIRECTORY, DEFAULT_GLOBAL_LOGFILE, DEFAULT_GLOBAL_LOGFILE_ROOT, ExAllocatePoolWithTag, ExFreePool(), FAILED, FALSE, _UNICODE_STRING::Length, NT_SUCCESS, NtSystemRoot, NULL, PagedPool, RtlCompareUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, StringCbPrintfW(), TRACEPOOLTAG, TRUE, UNICODE_NULL, wcslen(), WmipCreateDirectoryFile(), and WmipCreateNtFileName().
Referenced by WmipSwitchToNewFile().
VOID FASTCALL WmipDisableKernelTrace (IN ULONG EnableFlags)
Definition at line 346 of file callouts.c.
References CmSetTraceNotifyRoutine(), CONTAINING_RECORD, _TRACE_DEVICE::DeviceObject, _REGENTRY::DeviceObject, _IO_STACK_LOCATION::DeviceObject, ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, _REGENTRY::Flags, _LIST_ENTRY::Flink, Index, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoInitializeIrp(), IoSetNextIrpStackLocation, IoSizeOfIrp, IoWMIDeviceObjectToProviderId, IRP_MN_SET_TRACE_NOTIFY, MAX_FILE_TABLE_SIZE, MmSetPageFaultNotifyRoutine(), NULL, PAGED_CODE, PagedPool, PIRP, PsGetCurrentThread(), REGENTRY_FLAG_TRACED, RtlZeroMemory, STATUS_WMI_TRY_AGAIN, _TRACE_DEVICE::TraceClass, TRACEPOOLTAG, TRUE, WmipDiskIoNotify, WmipEnterSMCritSection, WmipForwardWmiIrp(), WmipInUseRegEntryCount, WmipInUseRegEntryHead, WmipLeaveSMCritSection, WmipServiceDeviceObject, WmipTdiIoNotify, WmipTraceFileFlag, WmipVolMgrIoNotify, WMIREG_FLAG_TRACE_NOTIFY_MASK, WMIREG_NOTIFY_DISK_IO, WMIREG_NOTIFY_TDI_IO, and WMIREG_NOTIFY_VOLMGR_IO.
Referenced by WmipStopLoggerInstance(), and WmiUpdateTrace().
VOID FASTCALL WmipEnableKernelTrace (IN ULONG EnableFlags)
Definition at line 141 of file callouts.c.
References CmSetTraceNotifyRoutine(), CONTAINING_RECORD, _TRACE_DEVICE::DeviceObject, _REGENTRY::DeviceObject, _IO_STACK_LOCATION::DeviceObject, ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, _REGENTRY::Flags, _LIST_ENTRY::Flink, Index, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoInitializeIrp(), IoSetNextIrpStackLocation, IoSizeOfIrp, IoWMIDeviceObjectToProviderId, IRP_MN_SET_TRACE_NOTIFY, MmSetPageFaultNotifyRoutine(), NULL, PAGED_CODE, PagedPool, PIRP, PsGetCurrentThread(), PsSetLoadImageNotifyRoutine(), REGENTRY_FLAG_TRACED, RtlZeroMemory, STATUS_WMI_TRY_AGAIN, _TRACE_DEVICE::TraceClass, TRACEPOOLTAG, TRUE, WmipDiskIoNotify, WmipEnterSMCritSection, WmipForwardWmiIrp(), WmipInUseRegEntryCount, WmipInUseRegEntryHead, WmipKernelLoggerStartedOnce, WmipLeaveSMCritSection, WmipServiceDeviceObject, WmipTdiIoNotify, WmipTraceFileFlag, WmipTraceIo(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmipVolMgrIoNotify, WMIREG_FLAG_TRACE_NOTIFY_MASK, WMIREG_NOTIFY_DISK_IO, WMIREG_NOTIFY_TDI_IO, and WMIREG_NOTIFY_VOLMGR_IO.
Referenced by WmipStartLogger(), and WmiUpdateTrace().
PVOID WmipExtendBase (IN PWMI_LOGGER_CONTEXT Base, IN ULONG Size)
Definition at line 1460 of file tracesup.c.
References ALIGN_TO_POWER2, ASSERT, CONTEXT_SIZE, DEFAULT_TRACE_ALIGNMENT, NULL, PAGED_CODE, and Space.
Referenced by WmipAllocateTraceBufferPool(), WmipStartLogger(), and WmiUpdateTrace().
NTSTATUS WmipFlushActiveBuffers (IN PWMI_LOGGER_CONTEXT, IN ULONG FlushAll)
Definition at line 1997 of file tracelog.c.
References CONTAINING_RECORD, ExInterlockedFlushSList(), ExQueryDepthSList, InterlockedExchangePointer, InterlockedPushEntrySList(), KeNumberProcessors, MAXIMUM_PROCESSORS, NULL, PAGED_CODE, PERF_CONTEXT_SWITCH, PERFINFO_IS_GROUP_ON, PSLIST_ENTRY, _WMI_BUFFER_HEADER::ReferenceCount, _WMI_BUFFER_HEADER::SlistEntry, Status, STATUS_SUCCESS, TraceDebug, WMI_BUFFER_FLAG_FLUSH_MARKER, WMI_BUFFER_FLAG_NORMAL, WmipFlushBuffersWithMarker(), WmipKernelLogger, WmipPushDirtyBuffer(), and WmipPushFreeBuffer().
Referenced by WmipLogger(), and WmipRequestLogFile().
NTSTATUS WmipFlushBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PWMI_BUFFER_HEADER Buffer, IN USHORT BufferFlag)
Definition at line 1286 of file tracelog.c.
References ASSERT, BYTES_PER_MB, EVENT_TRACE_CLOCK_PERFCOUNTER, EVENT_TRACE_FILE_MODE_CIRCULAR_PERSIST, EVENT_TRACE_USE_KBYTES_FOR_SIZE, FALSE, NT_SUCCESS, NULL, REQUEST_FLAG_CIRCULAR_PERSIST, REQUEST_FLAG_CIRCULAR_TRANSITION, REQUEST_FLAG_NEW_FILE, Status, STATUS_DISK_FULL, STATUS_LOG_FILE_FULL, STATUS_NO_DATA_DETECTED, STATUS_SEVERITY_ERROR, STATUS_SEVERITY_WARNING, STATUS_SUCCESS, TraceDebug, WMI_BUFFER_TYPE_RUNDOWN, WmipGlobalBufferCallback, WmipGlobalCallbackContext, WmipPrepareHeader(), WmipProcessEvent(), WmipSendNotification(), WNODE_FLAG_USE_TIMESTAMP, and ZwWriteFile().
Referenced by WmipAddLogHeader(), and WmipFlushBuffersWithMarker().
NTSTATUS WmipFlushLogger (IN OUT PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG Wait)
Definition at line 2000 of file tracesup.c.
References Executive, FALSE, KeResetEvent(), KernelMode, KeWaitForSingleObject(), NT_SUCCESS, PAGED_CODE, REQUEST_FLAG_FLUSH_BUFFERS, Status, STATUS_TIMEOUT, TraceDebug, and WmipNotifyLogger().
Referenced by WmiFlushTrace(), and WmiTraceEvent().
VOID WmipFreeLoggerContext (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1499 of file tracesup.c.
References ASSERT, EtwpPageLockHandle, Executive, ExFreePool(), FALSE, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), KeResetEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), MmUnlockPageableImageSection(), NULL, PAGED_CODE, RtlFreeUnicodeString(), Status, STATUS_TIMEOUT, TraceDebug, WmipAssert, WmipDereferenceLogger, WmipFreeTraceBufferPool(), WmipLoggerContext, WmipLoggerCount, and WmipRefCount.
Referenced by WmipLogger(), and WmipStartLogger().
NTSTATUS WmipGenerateFileName (IN PUNICODE_STRING FilePattern, IN OUT PLONG FileCounter, OUT PUNICODE_STRING FileName)
Definition at line 2115 of file tracelog.c.
References ExAllocatePoolWithTag, ExFreePool(), FAILED, InterlockedIncrement, NULL, PAGED_CODE, PagedPool, RtlEqualMemory, RtlInitUnicodeString(), STATUS_INVALID_PARAMETER_MIX, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, StringCbPrintfW(), TRACEPOOLTAG, wcschr(), wcsrchr(), and wcsstr().
Referenced by WmipStartLogger(), and WmipSwitchToNewFile().
PWMI_BUFFER_HEADER WmipGetFreeBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 183 of file tracelog.c.
References CONTAINING_RECORD, InterlockedDecrement, InterlockedIncrement, InterlockedPopEntrySList(), NULL, PSLIST_ENTRY, REQUEST_FLAG_CIRCULAR_PERSIST, TraceDebug, WMI_BUFFER_TYPE_GENERIC, WMI_BUFFER_TYPE_RUNDOWN, WmipPushFreeBuffer(), and WmipResetBufferHeader().
Referenced by WmipAddLogHeader(), WmipAllocateTraceBufferPool(), and WmipSwitchBuffer().
__inline __int64 WmipGetPerfCounter ()
Definition at line 95 of file tracep.h.
References KeQueryPerformanceCounter(), NULL, and _LARGE_INTEGER::QuadPart.
Referenced by WmiGetClock(), and WmipStartLogger().
__inline __int64 WmipGetSystemTime ()
Definition at line 85 of file tracep.h.
References KiQuerySystemTime, and _LARGE_INTEGER::QuadPart.
Referenced by WmiGetClock(), and WmipStartLogger().
PWMI_LOGGER_CONTEXT FASTCALL WmipIsLoggerOn (IN ULONG LoggerId)
Definition at line 1964 of file callouts.c.
References MAXLOGGERS, NULL, WmipIsValidLogger, and WmipLoggerContext.
Referenced by WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmiReserveWithPerfHeader(), WmiTraceProcess(), and WmiTraceThread().
VOID WmipLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 997 of file tracelog.c.
References ASSERT, Executive, FALSE, InterlockedExchange(), KeGetCurrentThread(), KeQuerySystemTime(), KernelMode, KeSetBasePriorityThread(), KeSetEvent(), KeWaitForSingleObject(), LOW_REALTIME_PRIORITY, NT_SUCCESS, NULL, PAGED_CODE, PsGetCurrentThread(), PsTerminateSystemThread(), REQUEST_FLAG_CIRCULAR_TRANSITION, REQUEST_FLAG_FLUSH_BUFFERS, REQUEST_FLAG_NEW_FILE, Status, STATUS_CANCELLED, STATUS_PENDING, STATUS_SUCCESS, STATUS_TIMEOUT, TraceDebug, TRUE, WmiOneSecond, WmipAdjustFreeBuffers(), WmipCreateLogFile(), WmipFinalizeHeader(), WmipFlushActiveBuffers(), WmipFreeLoggerContext(), WmipRequestLogFile(), WmipStopLoggerInstance(), and ZwClose().
Referenced by WmipStartLogger().
NTSTATUS FASTCALL WmipNotifyLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 2037 of file tracesup.c.
References FALSE, KeReadStateSemaphore(), KeReleaseSemaphore(), SEMAPHORE_LIMIT, STATUS_SEMAPHORE_LIMIT_EXCEEDED, and STATUS_SUCCESS.
Referenced by WmipFlushLogger(), WmipReleaseTraceBuffer(), WmipStopLoggerInstance(), WmipSwitchBuffer(), and WmiUpdateTrace().
NTSTATUS WmipNtDllLoggerInfo (PWMINTDLLLOGGERINFO Buffer)
Referenced by WmipIoControl().
PWMI_BUFFER_HEADER FASTCALL WmipPopFreeContextSwapBuffer (UCHAR CurrentProcessor)
Definition at line 2573 of file tracelog.c.
References ASSERT, _WMI_LOGGER_CONTEXT::BuffersAvailable, _WMI_LOGGER_CONTEXT::BuffersInUse, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_BUFFER_HEADER::ClientContext, _WMI_LOGGER_CONTEXT::CollectionOn, CONTAINING_RECORD, _WMI_LOGGER_CONTEXT::EventsLost, _WMI_LOGGER_CONTEXT::FreeList, InterlockedDecrement, InterlockedIncrement, InterlockedPopEntrySList(), NULL, _WMI_BUFFER_HEADER::Offset, _WMI_CLIENT_CONTEXT::ProcessorNumber, _WMI_LOGGER_CONTEXT::SwitchingInProgress, WMI_BUFFER_TYPE_CTX_SWAP, WMI_CTXSWAP_EVENTSIZE_ALIGNMENT, WmipIsValidLogger, WmipKernelLogger, and WmipResetBufferHeader().
Referenced by WmiTraceContextSwap().
VOID FASTCALL WmipPushDirtyContextSwapBuffer (UCHAR CurrentProcessor, PWMI_BUFFER_HEADER Buffer)
Definition at line 2668 of file tracelog.c.
References InterlockedIncrement, _WMI_LOGGER_CONTEXT::ReleaseQueue, UNREFERENCED_PARAMETER, WmipIsValidLogger, WmipKernelLogger, and WmipPushDirtyBuffer().
Referenced by WmiStopContextSwapTrace(), and WmiTraceContextSwap().
NTSTATUS WmipQueryGLRegistryRoutine (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
Definition at line 221 of file globalog.c.
References NULL, PAGED_CODE, REG_BINARY, REG_DWORD, REG_SZ, RtlCreateUnicodeString(), RtlMoveMemory, STATUS_SUCCESS, UNICODE_NULL, and UNREFERENCED_PARAMETER.
Referenced by WmipStartGlobalLogger().
NTSTATUS WmipQueryLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo, IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1076 of file tracesup.c.
References EtwpDefaultTraceSecurityDescriptor, except, EXCEPTION_EXECUTE_HANDLER, InterlockedDecrement, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, ProbeForWrite(), _LARGE_INTEGER::QuadPart, RtlCopyUnicodeString(), Status, STATUS_SUCCESS, TraceDebug, WmiOneSecond, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipReleaseMutex, WmipVerifyLoggerInfo(), and WmiSetLoggerId.
Referenced by WmiFlushTrace(), WmipIoControl(), WmiQueryTrace(), WmiStopTrace(), and WmiUpdateTrace().
ULONG FASTCALL WmipReleaseTraceBuffer (IN PWMI_BUFFER_HEADER Buffer, IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1773 of file tracelog.c.
References ASSERT, DISPATCH_LEVEL, InterlockedDecrement, KeGetCurrentIrql(), WmipDereferenceLogger, and WmipNotifyLogger().
Referenced by WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmiReleaseKernelBuffer(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceMessageVa(), WmiTraceProcess(), and WmiTraceThread().
PVOID FASTCALL WmipReserveTraceBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG RequiredSize, OUT PWMI_BUFFER_HEADER * BufferResource, OUT PLARGE_INTEGER TimeStamp)
Definition at line 531 of file tracelog.c.
References ALIGN_TO_POWER2, ASSERT, _WMI_BUFFER_HEADER::CurrentOffset, InterlockedDecrement, InterlockedExchangeAdd(), InterlockedIncrement, KeGetCurrentProcessorNumber(), NT_SUCCESS, NULL, _WMI_BUFFER_HEADER::ReferenceCount, _WMI_BUFFER_HEADER::SavedOffset, Status, WmipIsValidLogger, WmipSwitchBuffer(), and WmiTraceAlignment.
Referenced by WmipStartGlobalLogger(), WmiReserveWithPerfHeader(), WmiReserveWithSystemHeader(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), and WmiTraceMessageVa().
VOID FASTCALL WmipResetBufferHeader (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer, USHORT BufferType)
Definition at line 2400 of file tracelog.c.
References ASSERT, _WMI_BUFFER_HEADER::BufferType, _WNODE_HEADER::ClientContext, _WMI_BUFFER_HEADER::CurrentOffset, _WMI_BUFFER_STATE::Free, _WMI_BUFFER_STATE::InUse, _WMI_BUFFER_HEADER::LoggerContext, _WMI_BUFFER_HEADER::SavedOffset, _WMI_BUFFER_HEADER::State, WMI_BUFFER_TYPE_MAXIMUM, and _WMI_BUFFER_HEADER::Wnode.
Referenced by WmipAddLogHeader(), WmipGetFreeBuffer(), WmipPopFreeContextSwapBuffer(), and WmipSwitchToNewFile().
NTSTATUS WmipSendNotification (PWMI_LOGGER_CONTEXT LoggerContext, NTSTATUS Status, ULONG Flag)
Definition at line 1252 of file tracelog.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, FALSE, Flag, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, KeQuerySystemTime(), _WMI_LOGGER_CONTEXT::LoggerId, RtlZeroMemory, Status, _tagWMI_Event::Status, STATUS_SUCCESS, _WNODE_HEADER::TimeStamp, _tagWMI_Event::TraceErrorFlag, WmipProcessEvent(), WmiSetLoggerId, and _tagWMI_Event::Wnode.
Referenced by WmipFlushBuffer(), WmipFlushBuffersWithMarker(), WmipStopLoggerInstance(), and WmipSwitchToNewFile().
VOID WmipSetTraceNotify (IN PDEVICE_OBJECT DeviceObject, IN ULONG TraceClass, IN ULONG Enable)
Definition at line 503 of file callouts.c.
References _IO_STACK_LOCATION::DeviceObject, FALSE, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoSetNextIrpStackLocation, IoWMIDeviceObjectToProviderId, IRP_MN_SET_TRACE_NOTIFY, NULL, PIRP, STATUS_WMI_TRY_AGAIN, WmipDiskIoNotify, WmipForwardWmiIrp(), WmipServiceDeviceObject, WmipTdiIoNotify, WmipVolMgrIoNotify, WMIREG_NOTIFY_DISK_IO, WMIREG_NOTIFY_TDI_IO, and WMIREG_NOTIFY_VOLMGR_IO.
Referenced by IoWMIRegistrationControl().
NTSTATUS WmipShutdown (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 1949 of file tracesup.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, _WMI_LOGGER_CONTEXT::InstanceGuid, IO_NO_INCREMENT, IoCompleteRequest(), MAXLOGGERS, NULL, PAGED_CODE, RtlZeroMemory, STATUS_SUCCESS, TraceDebug, UNREFERENCED_PARAMETER, WmipLoggerContext, WmipLoggerCount, WmiSetLoggerId, WmiStopTrace(), _WMI_LOGGER_INFORMATION::Wnode, and WNODE_FLAG_TRACED_GUID.
Referenced by WmipDriverEntry().
VOID WmipStartGlobalLogger ()
Definition at line 64 of file globalog.c.
References DEFAULT_GLOBAL_LOGFILE_ROOT, DEFAULT_TRACE_GUID_NAME, _RTL_QUERY_REGISTRY_TABLE::DefaultData, _RTL_QUERY_REGISTRY_TABLE::DefaultType, _RTL_QUERY_REGISTRY_TABLE::EntryContext, EtwpDefaultSecurityDescriptor, EtwpDefaultTraceSecurityDescriptor, EtwpPageLockHandle, KeInitializeGuardedMutex(), KeNumberProcessors, _TRACE_ENABLE_FLAG_EXTENSION::Length, MAX_ENABLE_FLAGS, MAX_REGKEYS, MmLockPageableCodeSection, MmUnlockPageableImageSection(), _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, NullString, _TRACE_ENABLE_FLAG_EXTENSION::Offset, PAGE_SIZE, _RTL_QUERY_REGISTRY_TABLE::QueryRoutine, REG_BINARY, REG_DWORD, REG_SZ, RTL_REGISTRY_CONTROL, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlNtStatusToDosError(), RtlQueryRegistryValues(), RtlWriteRegistryValue(), RtlZeroMemory, STATUS_NO_MEMORY, STATUS_SUCCESS, UNICODE_NULL, WmipGetGuidSecurityDescriptor(), WmipQueryGLRegistryRoutine(), WmipReserveTraceBuffer(), WmipStartLogger(), WmipTraceGuardedMutex, and WNODE_FLAG_TRACED_GUID.
Referenced by WmipDriverEntry().
NTSTATUS WmipStartLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 105 of file tracesup.c.
References ASSERT, _UNICODE_STRING::Buffer, _WMI_LOGGER_CONTEXT::BufferAgeLimit, _WMI_LOGGER_CONTEXT::BufferCallback, _WMI_LOGGER_CONTEXT::BuffersAvailable, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_LOGGER_CONTEXT::BuffersWritten, _ETHREAD::Cid, _WMI_LOGGER_CONTEXT::ClientSecurityContext, CONTAINING_RECORD, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, DEFAULT_AGE_LIMIT, DEFAULT_BUFFERS, DEFAULT_MAX_IRQL, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, _WMI_LOGGER_CONTEXT::EnableFlagArray, _WMI_LOGGER_CONTEXT::EnableFlags, EtwpDefaultTraceSecurityDescriptor, EtwpPageLockHandle, EVENT_TRACE_CLOCK_CPUCYCLE, EVENT_TRACE_CLOCK_PERFCOUNTER, EVENT_TRACE_CLOCK_SYSTEMTIME, EVENT_TRACE_FILE_MODE_CIRCULAR_PERSIST, EVENT_TRACE_KD_FILTER_MODE, EVENT_TRACE_USE_KBYTES_FOR_SIZE, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExUuidCreate(), FALSE, FILE_WRITE_DATA, _WMI_LOGGER_CONTEXT::FileCounter, _WMI_LOGGER_CONTEXT::FlushEvent, _WMI_LOGGER_CONTEXT::FlushList, _WMI_LOGGER_CONTEXT::FlushTimer, _WMI_LOGGER_CONTEXT::FreeList, _WMI_LOGGER_CONTEXT::GetCpuClock, _WMI_LOGGER_CONTEXT::GlobalList, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, InitializeSListHead(), _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedCompareExchange(), InterlockedCompareExchangePointer, InterlockedDecrement, InterlockedExchange(), InterlockedIncrement, IoFileObjectType, IsEqualGUID, KdReportTraceData(), KeAcquireGuardedMutex(), KeGetCurrentThread(), KeGetPreviousMode, KeInitializeEvent(), KeNumberProcessors, KeQuerySystemTime(), KeReleaseGuardedMutex(), KeResetEvent(), KERNEL_LOGGER_CAPTION, KernelMode, _WMI_LOGGER_CONTEXT::KernelTraceOn, KeWaitForSingleObject(), _TRACE_ENABLE_FLAG_EXTENSION::Length, _UNICODE_STRING::Length, _SECURITY_QUALITY_OF_SERVICE::Length, _WMI_LOGGER_CONTEXT::LocalSequence, _WMI_LOGGER_CONTEXT::LogFileName, _WMI_LOGGER_CONTEXT::LogFilePattern, _WMI_LOGGER_CONTEXT::LoggerEvent, _WMI_LOGGER_CONTEXT::LoggerHeader, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMode, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::LoggerName, _WMI_LOGGER_CONTEXT::LoggerStatus, _WMI_LOGGER_CONTEXT::LoggerThread, max, MAX_FILE_TABLE_SIZE, MAX_WMI_BUFFER_SIZE, _WMI_LOGGER_CONTEXT::MaximumBuffers, _WMI_LOGGER_CONTEXT::MaximumFileSize, _WMI_LOGGER_CONTEXT::MaximumIrql, MAXLOGGERS, _WMI_LOGGER_CONTEXT::MinimumBuffers, MmLockPageableSectionByHandle(), MmMaximumNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, _WMI_LOGGER_CONTEXT::MutexCount, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, _WMI_LOGGER_CONTEXT::NumberOfBuffers, ObDereferenceObject(), ObReferenceObjectByHandle, _TRACE_ENABLE_FLAG_EXTENSION::Offset, PAGE_SIZE, PAGED_CODE, PagedPool, PERF_LOG_NO_TRANSITION, PERF_LOG_START_TRANSITION, PerfGetCycleCount(), PERFINFO_START_LOG_FROM_GLOBAL_LOGGER, PERFINFO_START_LOG_POST_BOOT, PerfInfoStartLog(), _WMI_LOGGER_CONTEXT::PerfLogInTransition, _WMI_LOGGER_CONTEXT::PoolType, ProbeForRead, ProbeForWrite(), PsCreateSystemThread(), _LARGE_INTEGER::QuadPart, _WMI_LOGGER_CONTEXT::ReferenceSystemTime, _WMI_LOGGER_CONTEXT::ReferenceTimeStamp, REQUEST_FLAG_CIRCULAR_PERSIST, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, RtlCopyUnicodeString(), RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlZeroMemory, SeComputeGrantedAccesses, SeCreateClientSecurity(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, _WMI_LOGGER_CONTEXT::SequencePtr, Status, STATUS_ACCESS_DENIED, STATUS_ALREADY_DISCONNECTED, STATUS_CANCELLED, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_COLLISION, STATUS_PENDING, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_ALL_ACCESS, TRACE_MAXIMUM_NP_POOL_USAGE, TraceDebug, TRACEPOOLTAG, TRUE, _CLIENT_ID::UniqueThread, _WMI_LOGGER_CONTEXT::UsePerfClock, _WMI_LOGGER_CONTEXT::WaitList, WmiGetCpuClock, WmiOneSecond, WmipAcquireMutex, WmipAllocateTraceBufferPool(), WmipCheckGuidAccess(), WmipDereferenceLogger, WmipEnableKernelTrace(), WmipEventLogger, WmipExtendBase(), WmipFileTable, WmipFreeLoggerContext(), WmipGenerateFileName(), WmipGetPerfCounter(), WmipGetSystemTime(), WmipGlobalSequence, WmipInitContext(), WmipInitializeMutex, WmipKernelLogger, WmipLogger(), WmipLoggerContext, WmipLoggerCount, WmipLookupLoggerIdByName(), WmipRefCount, WmipReferenceLogger, WmipReleaseMutex, WmipStopLoggerInstance(), WmipValidateClockType(), WmiSetLoggerId, WNODE_FLAG_TRACED_GUID, _WMI_LOGGER_CONTEXT::Wow, _WMI_LOGGER_CONTEXT::WriteFailureLimit, and ZwClose().
Referenced by WmipIoControl(), WmipStartGlobalLogger(), and WmiStartTrace().
NTSTATUS WmipStopLoggerInstance (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1256 of file tracesup.c.
References FALSE, InterlockedCompareExchange(), InterlockedExchange(), NULL, PAGED_CODE, PERF_LOG_NO_TRANSITION, PERF_LOG_START_TRANSITION, PERF_LOG_STOP_TRANSITION, PerfInfoStopLog(), STATUS_ALREADY_DISCONNECTED, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_THREAD_IS_TERMINATING, STATUS_UNSUCCESSFUL, WmipDisableKernelTrace(), WmipEventLogger, WmipLoggerContext, WmipNotifyLogger(), and WmipSendNotification().
Referenced by WmipLogger(), WmipStartLogger(), and WmiStopTrace().
VOID WmipValidateClockType (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 2278 of file tracesup.c.
References UNREFERENCED_PARAMETER.
Referenced by WmipIoControl(), and WmipStartLogger().
NTSTATUS WmipVerifyLoggerInfo (IN PWMI_LOGGER_INFORMATION LoggerInfo, OUT PWMI_LOGGER_CONTEXT * LoggerContext)
Definition at line 1328 of file tracesup.c.
References _UNICODE_STRING::Buffer, _WMI_LOGGER_CONTEXT::CollectionOn, except, EXCEPTION_EXECUTE_HANDLER, InterlockedDecrement, InterlockedIncrement, IsEqualGUID, KeGetPreviousMode, KERNEL_LOGGER_ID, KernelMode, _UNICODE_STRING::Length, _WMI_LOGGER_CONTEXT::LoggerMutex, MAXLOGGERS, _WMI_LOGGER_CONTEXT::MutexCount, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), Status, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TraceDebug, WmiGetLoggerId, WmipAcquireMutex, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, WmipKernelLogger, WmipLookupLoggerIdByName(), WmipReferenceLogger, WmipReleaseMutex, and WNODE_FLAG_TRACED_GUID.
Referenced by WmiFlushTrace(), WmipQueryLogger(), WmiStopTrace(), and WmiUpdateTrace().
PSYSTEM_TRACE_HEADER FASTCALL WmiReserveWithSystemHeader (IN ULONG LoggerId, IN ULONG AuxSize, IN PETHREAD Thread, OUT PVOID * BufferResource)
Variable Documentation
PSECURITY_DESCRIPTOR EtwpDefaultTraceSecurityDescriptor
Definition at line 47 of file tracesup.c.
Referenced by WmiFlushTrace(), WmipEnableDisableTrace(), WmipNtDllLoggerInfo(), WmipQueryLogger(), WmipStartGlobalLogger(), WmipStartLogger(), WmiStopTrace(), and WmiUpdateTrace().
LARGE_INTEGER WmiOneSecond
Definition at line 31 of file wmidata.c.
Referenced by WmipLogger(), WmipQueryLogger(), and WmipStartLogger().
PWMI_BUFFER_HEADER WmipContextSwapProcessorBuffers[MAXIMUM_PROCESSORS]
Definition at line 66 of file tracelog.c.
Referenced by WmiStartContextSwapTrace(), WmiStopContextSwapTrace(), and WmiTraceContextSwap().
ULONG WmipEventLogger
Definition at line 39 of file tracesup.c.
Referenced by WmipStartLogger(), WmipStopLoggerInstance(), WmipTraceLoadImage(), WmiQueryTraceInformation(), WmiStopTrace(), WmiTraceProcess(), and WmiTraceThread().
PFILE_OBJECT* WmipFileTable
Definition at line 120 of file callouts.c.
Referenced by WmipStartLogger().
WMI_TRACE_BUFFER_CALLBACK WmipGlobalBufferCallback
Definition at line 76 of file tracelog.c.
Referenced by WmipFlushBuffer(), and WmiSetTraceBufferCallback().
ULONG WmipGlobalSequence
Definition at line 64 of file tracelog.c.
Referenced by WmipStartLogger().
ULONG WmipKernelLogger
Definition at line 38 of file tracesup.c.
Referenced by WmipAddLogHeader(), WmipFlushActiveBuffers(), WmipPopFreeContextSwapBuffer(), WmipPushDirtyContextSwapBuffer(), WmipStartLogger(), WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmipVerifyLoggerInfo(), WmiReleaseKernelBuffer(), WmiReserveWithPerfHeader(), WmiSetTraceBufferCallback(), WmiStopContextSwapTrace(), WmiStopTrace(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceProcess(), WmiTraceThread(), and WmiUpdateTrace().
PWMI_LOGGER_CONTEXT WmipLoggerContext[MAXLOGGERS]
Definition at line 65 of file tracelog.c.
Referenced by IoWMIWriteEvent(), WmipAddLogHeader(), WmipDriverEntry(), WmipFreeLoggerContext(), WmipIsLoggerOn(), WmipLookupLoggerIdByName(), WmipShutdown(), WmipStartLogger(), WmipStopLoggerInstance(), WmipTraceNetwork(), WmiQueryTraceInformation(), WmiStopContextSwapTrace(), WmiStopTrace(), and WmiTraceKernelEvent().
ULONG WmipPtrSize
LONG WmipRefCount[MAXLOGGERS]
Definition at line 63 of file tracelog.c.
Referenced by WmipDriverEntry(), WmipFreeLoggerContext(), WmipStartLogger(), and WmiTraceKernelEvent().
KGUARDED_MUTEX WmipTraceGuardedMutex
Definition at line 40 of file tracesup.c.
Referenced by WmipStartGlobalLogger().
LARGE_INTEGER WmiShortTime
Definition at line 32 of file wmidata.c.
Referenced by WmipFlushBuffersWithMarker().
ULONG WmiTraceAlignment
Definition at line 61 of file tracelog.c.
Referenced by WmipAddLogHeader(), WmipPrepareHeader(), WmipReserveTraceBuffer(), and WmipTraceFile().
ULONG WmiUsePerfClock
Definition at line 62 of file tracelog.c.
ULONG WmiWriteFailureLimit
Definition at line 74 of file tracelog.c.
Referenced by WmipFlushBuffersWithMarker().