Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/session.c File Reference
session.c File Reference
#include "mi.h"
Macros
#define MI_SESSION_DATA_PAGES_MAXIMUM (MM_ALLOCATION_GRANULARITY / PAGE_SIZE)
#define MI_SESSION_ID_INCREMENT (POOL_SMALLEST_BLOCK * 8)
#define MI_SESSION_TAG_PAGES_MAXIMUM (MM_ALLOCATION_GRANULARITY / PAGE_SIZE)
Functions
VOID MiAttachSession (IN PMM_SESSION_SPACE SessionGlobal)
VOID MiDereferenceSession (VOID)
VOID MiDereferenceSessionFinal (VOID)
VOID MiDetachSession (VOID)
VOID MiInitializeSessionIds (VOID)
VOID MiReleaseProcessReferenceToSessionDataPage (PMM_SESSION_SPACE SessionGlobal)
VOID MiSessionAddProcess (PEPROCESS NewProcess)
NTSTATUS MiSessionCommitPageTables (IN PVOID StartVa, IN PVOID EndVa)
NTSTATUS MiSessionCreateInternal (OUT PULONG SessionId)
VOID MiSessionDeletePde (IN PMMPTE Pde, IN PMMPTE SelfMapPde)
VOID MiSessionInSwapProcess (IN PEPROCESS Process, IN LOGICAL Forced)
VOID MiSessionLeader (IN PEPROCESS Process)
VOID MiSessionOutSwapProcess (IN PEPROCESS Process)
PVOID MiSessionPoolBigPageTable (VOID)
SIZE_T MiSessionPoolBigPageTableSize (VOID)
PGENERAL_LOOKASIDE MiSessionPoolLookaside (VOID)
ULONG MiSessionPoolSmallLists (VOID)
PVOID MiSessionPoolTrackTable (VOID)
SIZE_T MiSessionPoolTrackTableSize (VOID)
VOID MiSessionRemoveProcess (VOID)
NTSTATUS MmAttachSession (IN PVOID OpaqueSession, OUT PRKAPC_STATE ApcState)
NTSTATUS MmDetachSession (IN PVOID OpaqueSession, IN PRKAPC_STATE ApcState)
PVOID MmGetNextSession (IN PVOID OpaqueSession)
PVOID MmGetPreviousSession (IN PVOID OpaqueSession)
PVOID MmGetSessionById (IN ULONG SessionId)
ULONG MmGetSessionId (IN PEPROCESS Process)
ULONG MmGetSessionIdEx (IN PEPROCESS Process)
LCID MmGetSessionLocaleId (VOID)
NTSTATUS MmQuitNextSession (IN PVOID OpaqueSession)
NTSTATUS MmSessionCreate (OUT PULONG SessionId)
NTSTATUS MmSessionDelete (ULONG SessionId)
VOID MmSessionSetUnloadAddress (IN PDRIVER_OBJECT DriverObject)
VOID MmSetSessionLocaleId (IN LCID LocaleId)
Variables
ULONG MiSessionBigPoolPages
ULONG MiSessionCreateCharge
ULONG MiSessionDataPages
PRTL_BITMAP MiSessionIdBitmap = {0}
KGUARDED_MUTEX MiSessionIdMutex
LONG MiSessionLeaderExists
ULONG MiSessionTagPages
ULONG MiSessionTagSizePages
LONG MmSessionDataPages
Macro Definition Documentation
#define MI_SESSION_DATA_PAGES_MAXIMUM (MM_ALLOCATION_GRANULARITY / PAGE_SIZE)
Definition at line 50 of file session.c.
Referenced by MiDereferenceSessionFinal(), MiInitializeSessionIds(), MiReleaseProcessReferenceToSessionDataPage(), and MiSessionCreateInternal().
#define MI_SESSION_ID_INCREMENT (POOL_SMALLEST_BLOCK * 8)
Definition at line 32 of file session.c.
Referenced by MiInitializeSessionIds(), and MiSessionCreateInternal().
#define MI_SESSION_TAG_PAGES_MAXIMUM (MM_ALLOCATION_GRANULARITY / PAGE_SIZE)
Definition at line 51 of file session.c.
Referenced by MiInitializeSessionIds(), and MiSessionCreateInternal().
Function Documentation
VOID MiAttachSession (IN PMM_SESSION_SPACE SessionGlobal)
Definition at line 1682 of file session.c.
References ASSERT, _MMPTE::Long, MI_WRITE_VALID_PTE, MiGetPdeAddress, MiGetPxeAddress, MiSessionSpacePageTables, MmSessionBase, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), RtlCompareMemoryUlong(), RtlCopyMemory, and _MMPTE::u.
Referenced by MiAttachAndLockWorkingSet().
VOID MiDereferenceSession (VOID)
Definition at line 2000 of file session.c.
References ASSERT, _MMSUPPORT::Flags, _EPROCESS::Flags, _MM_SESSION_SPACE::Flags, _MM_SESSION_SPACE_FLAGS::Initialized, InterlockedDecrement, _MMPTE::Long, MI_FLUSH_SESSION_TB, MiDereferenceSessionFinal(), MiGetPdeAddress, MiGetPxeAddress, MiReleaseProcessReferenceToSessionDataPage(), MiSessionSpacePageTables, MmSessionSpace, NULL, PS_CLEAR_BITS, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _MM_SESSION_SPACE::ReferenceCount, _MM_SESSION_SPACE::ResidentProcessCount, RtlCheckBit, RtlZeroMemory, _EPROCESS::Session, SESSION_GLOBAL, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, _MMPTE::u, _MM_SESSION_SPACE::u, and _EPROCESS::Vm.
Referenced by MiSessionRemoveProcess(), MmSessionCreate(), and MmSessionDelete().
VOID MiDereferenceSessionFinal (VOID)
Definition at line 2118 of file session.c.
References ASSERT, _MM_SESSION_SPACE::AttachCount, _MM_SESSION_SPACE::AttachEvent, _LIST_ENTRY::Blink, _MM_SESSION_SPACE::CommittedPages, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMPFN::e2, ExDeferredFreePool(), ExDeletePagedLookasideList(), ExDrainPoolLookasideList(), ExPageLockHandle, FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, _MMPTE::Hard, _MMWSL::HighestPermittedHashAddress, Index, _MM_SESSION_SPACE_FLAGS::Initialized, InterlockedExchangeAddSizeT, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeWaitForSingleObject(), LOCK_EXPANSION, LOCK_PFN, _MMPTE::Long, _MM_SESSION_SPACE::Lookaside, MI_FLUSH_SESSION_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MI_SESSION_DATA_PAGES_MAXIMUM, MI_SESSION_SPACE_WORKING_SET_MINIMUM, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiCheckSessionPoolAllocations(), MiDecrementShareCount(), MiFreeSessionPoolBitMaps(), MiFreeSessionSpaceMap(), MiGetPdeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiReleaseProcessReferenceToSessionDataPage(), MiReturnCommitment, MiSessionDataPages, MiSessionImageStart, MiSessionSpacePageTables, MiSessionSpaceWs, MiSessionTagPages, MiSessionUnloadAllImages(), MiSessionViewStart, MiZeroMemoryPte, MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_RETURN_SESSION_DEREFERENCE, MM_DBG_SESSION_INITIAL_PAGE_FREE, MM_DBG_SESSION_NP_SESSION_DESTROY, MM_DBG_SESSION_NP_SESSION_PTDESTROY, MM_DBG_SESSION_NP_WS_PAGE_FREE, MM_DBG_SESSION_PAGETABLE_FREE, MM_DBG_SESSION_WS_PAGE_FREE, MM_RESAVAIL_FREE_DEREFERENCE_SESSION_PAGES, MM_RESAVAIL_FREE_DEREFERENCE_SESSION_WS, MM_SNAP_SESS_MEMORY_COUNTERS, MM_TRACK_COMMIT, MM_WS_NOT_LISTED, MM_WS_TRIMMING, MmLockPageableSectionByHandle(), MmSessionImageSize, MmSessionSpace, MmSessionSpecialPoolStart, MmSessionViewSize, MmUnlockPageableImageSection(), _MM_SESSION_SPACE::NonPageablePages, NOTHING, NotificationEvent, NULL, _MM_SESSION_SPACE::PagedPool, _MM_SESSION_SPACE::PageTables, PS_CLEAR_BITS, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _MMPFN::PteFrame, _MM_SESSION_SPACE::ReferenceCount, RemoveEntryList(), _MM_SESSION_SPACE::ResidentProcessCount, RtlCheckBit, _EPROCESS::Session, SESSION_GLOBAL, SESSION_POOL_SMALL_LISTS, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::SessionPageDirectoryIndex, _MMPFN::ShareCount, _MMPTE::u, _MM_SESSION_SPACE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MM_SESSION_SPACE::Vm, _MMSUPPORT::VmWorkingSetList, _MM_SESSION_SPACE::Win32KDriverUnload, _MMSUPPORT::WorkingSetExpansionLinks, WrVirtualMemory, _MMPFN::WsIndex, and _MM_SESSION_SPACE::WsListEntry.
Referenced by MiDereferenceSession().
VOID MiDetachSession (VOID)
Definition at line 1735 of file session.c.
References ASSERT, MI_FLUSH_SESSION_TB, MI_WRITE_ZERO_PTE, MiGetPdeAddress, MiGetPxeAddress, MiSessionSpacePageTables, MmIsAddressValid(), MmSessionBase, MmSessionSpace, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), RtlZeroMemory, and TRUE.
Referenced by MiAttachAndLockWorkingSet(), and MiDetachAndUnlockWorkingSet().
VOID MiInitializeSessionIds (VOID)
Definition at line 490 of file session.c.
References ASSERT, INSTALL_MORE_MEMORY, KeBugCheckEx(), KeInitializeGuardedMutex(), MI_SESSION_DATA_PAGES_MAXIMUM, MI_SESSION_ID_INCREMENT, MI_SESSION_TAG_PAGES_MAXIMUM, MiCreateBitMap, MiSessionBigPoolPages, MiSessionCreateCharge, MiSessionDataPages, MiSessionTagPages, MiSessionTagSizePages, MmHighestPhysicalPage, MmLowestPhysicalPage, MmNumberOfPhysicalPages, NULL, PAGE_SHIFT, PagedPool, ROUND_TO_PAGES, and RtlClearAllBits().
Referenced by MmInitSystem().
VOID MiReleaseProcessReferenceToSessionDataPage (PMM_SESSION_SPACE SessionGlobal)
Definition at line 1888 of file session.c.
References ASSERT, _MMPFN::e2, ExFreePool(), InterlockedDecrement, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MI_SESSION_DATA_PAGES_MAXIMUM, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiGetPteAddress, MiReleaseSystemPtes(), MiReturnCommitment, MiSessionDataPages, MM_DBG_COMMIT_RETURN_SESSION_DATAPAGE, MM_RESAVAIL_FREE_DEREFERENCE_SESSION, MM_TRACK_COMMIT, MmSessionDataPages, _MM_SESSION_SPACE::PageTables, _MM_SESSION_SPACE::ProcessReferenceToSession, RtlCheckBit, RtlClearBit(), _MM_SESSION_SPACE::SessionId, _MMPFN::ShareCount, SystemPteSpace, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN.
Referenced by MiDereferenceSession(), MiDereferenceSessionFinal(), and MmDeleteProcessAddressSpace().
VOID MiSessionAddProcess (PEPROCESS NewProcess)
Definition at line 199 of file session.c.
References ASSERT, _EPROCESS::Flags, InsertTailList(), InterlockedIncrement, LOCK_EXPANSION, MmIsAddressValid(), MmSessionSpace, NULL, _MM_SESSION_SPACE::ProcessList, _MM_SESSION_SPACE::ProcessReferenceToSession, PS_PROCESS_FLAGS_IN_SESSION, PS_SET_BITS, PsGetCurrentProcess(), _MM_SESSION_SPACE::ReferenceCount, _MM_SESSION_SPACE::ResidentProcessCount, _EPROCESS::Session, SESSION_GLOBAL, _EPROCESS::SessionProcessLinks, TRUE, and UNLOCK_EXPANSION.
NTSTATUS MiSessionCommitPageTables (IN PVOID StartVa, IN PVOID EndVa)
Definition at line 2842 of file session.c.
References ASSERT, _MM_SESSION_SPACE::CommittedPages, _MMPFN::e1, _MMWSLE::e1, _MMPFN::Event, FALSE, _MMWSL::FirstDynamic, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMPTE::Hard, HYDRA_PROCESS, Index, InterlockedExchangeAddSizeT, LOCK_PFN, LOCK_WORKING_SET, _MMWSLENTRY::LockedInWs, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_SESSION, MI_INCREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_VALID_PTE, MiAddValidPageToWorkingSet(), MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPdeSessionIndex, MiGetVirtualAddressMappedByPte, MiInitializePfnForOtherProcess(), MiLocateWsle(), MiRemoveZeroPage(), MiReturnCommitment, MiSessionSpaceEnd, MiSwapWslEntries(), MiTrimPte(), MM_BUMP_SESS_COUNTER, MM_BUMP_SESSION_FAILURES, MM_DBG_COMMIT_SESSION_PAGETABLE_PAGES, MM_DBG_SESSION_NP_COMMIT_IMAGE_PT, MM_DBG_SESSION_PAGETABLE_ALLOC, MM_RESAVAIL_ALLOCATE_SESSION_PAGE_TABLES, MM_RESAVAIL_FREE_SESSION_PAGE_TABLES_EXCESS, MM_SESSION_FAILURE_NO_COMMIT, MM_SESSION_FAILURE_NO_RESIDENT, MM_TRACK_COMMIT, MmSessionSpace, _MM_SESSION_SPACE::NonPageablePages, NULL, PAGE_ALIGN, _MMPTE_HARDWARE::PageFrameNumber, _MM_SESSION_SPACE::PageTables, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MM_SESSION_SPACE::SessionPageDirectoryIndex, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, ValidKernelPdeLocal, _MM_SESSION_SPACE::Vm, _MMSUPPORT::VmWorkingSetList, _MMPFN::WsIndex, _MM_SESSION_SPACE::Wsle, and ZeroPte.
NTSTATUS MiSessionCreateInternal (OUT PULONG SessionId)
Definition at line 657 of file session.c.
References ASSERT, _LIST_ENTRY::Blink, _RTL_BITMAP::Buffer, _MM_SESSION_SPACE::Color, _MM_SESSION_SPACE::CommittedPages, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), ExPageLockHandle, FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMPTE::Hard, _MM_SESSION_SPACE::ImageList, InitializeListHead(), InterlockedCompareExchange(), InterlockedIncrement, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), _MM_SESSION_SPACE::LocaleId, LOCK_PFN, _MMPTE::Long, _MM_SESSION_SPACE::LongFlags, MI_DECREMENT_RESIDENT_AVAILABLE, MI_FLUSH_SESSION_TB, MI_GET_PAGE_COLOR_FROM_VA, MI_INCREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SESSION_DATA_PAGES_MAXIMUM, MI_SESSION_ID_INCREMENT, MI_SESSION_SPACE_MAXIMUM_PAGE_TABLES, MI_SESSION_SPACE_WORKING_SET_MINIMUM, MI_SESSION_TAG_PAGES_MAXIMUM, MI_SET_PFN_DELETED, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiChargeCommitment(), MiCreateBitMap, MiDecrementShareCount(), MiEnsureAvailablePageOrWait(), MiFreeSessionPoolBitMaps(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), MiInitializeSessionPool(), MiInitializeSystemSpaceMap(), MiReleaseSystemPtes(), MiRemoveBitMap, MiRemoveZeroPageMayReleaseLocks(), MiReserveSystemPtes(), MiReturnCommitment, MiSessionCreateCharge, MiSessionDataPages, MiSessionTagPages, MiZeroMemoryPte, MM_BUMP_SESS_COUNTER, MM_BUMP_SESSION_FAILURES, MM_DBG_COMMIT_RETURN_SESSION_CREATE_FAILURE, MM_DBG_COMMIT_SESSION_CREATE, MM_DBG_SESSION_INITIAL_PAGE_ALLOC, MM_DBG_SESSION_INITIAL_PAGE_FREE_FAIL1, MM_DBG_SESSION_INITIAL_PAGETABLE_ALLOC, MM_DBG_SESSION_INITIAL_PAGETABLE_FREE_FAIL1, MM_DBG_SESSION_NP_SESSION_CREATE, MM_HIGH_LIMIT, MM_RESAVAIL_ALLOCATE_CREATE_SESSION, MM_RESAVAIL_FREE_CREATE_SESSION, MM_SESSION_FAILURE_NO_COMMIT, MM_SESSION_FAILURE_NO_IDS, MM_SESSION_FAILURE_NO_NONPAGED_POOL, MM_SESSION_FAILURE_NO_RESIDENT, MM_SESSION_FAILURE_NO_SYSPTES, MM_TRACK_COMMIT, MmAvailablePages, MmIsAddressValid(), MmLockPageableSectionByHandle(), MmSessionBase, MmSessionDataPages, MmSessionSpace, MmUnlockPageableImageSection(), NO_BITS_FOUND, _MM_SESSION_SPACE::NonPageablePages, NonPagedPool, NT_SUCCESS, NULL, PagedPool, _MMPTE_HARDWARE::PageFrameNumber, _MM_SESSION_SPACE::PageTables, _MM_SESSION_SPACE::ProcessList, _MM_SESSION_SPACE::ProcessReferenceToSession, PS_CLEAR_BITS, PS_PROCESS_FLAGS_CREATING_SESSION, PsDefaultSystemLocaleId, PsGetCurrentProcess(), _MMPFN::PteFrame, _MM_SESSION_SPACE::ReferenceCount, _MM_SESSION_SPACE::ResidentProcessCount, RtlCheckBit, RtlClearAllBits(), RtlClearBit(), RtlCopyMemory, RtlFindClearBitsAndSet(), RtlZeroMemory, _EPROCESS::Session, _MM_SESSION_SPACE::Session, _MM_SESSION_SPACE::SessionId, _MM_SESSION_SPACE::SessionPageDirectoryIndex, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, Status, STATUS_ALREADY_COMMITTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_SUCCESS, SystemPteSpace, TRUE, _MMPTE::u, _MM_SESSION_SPACE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, ValidKernelPdeLocal, ValidKernelPte, ValidKernelPteLocal, and _MM_SESSION_SPACE::WsListEntry.
Referenced by MmSessionCreate().
VOID MiSessionDeletePde (IN PMMPTE Pde, IN PMMPTE SelfMapPde)
VOID MiSessionInSwapProcess (IN PEPROCESS Process, IN LOGICAL Forced)
Definition at line 3230 of file session.c.
References ASSERT, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, FALSE, _MMSUPPORT::Flags, InterlockedIncrement, MM_DBG_SESSIONS, NULL, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_VM_DELETED, _MM_SESSION_SPACE::ReferenceCount, _MM_SESSION_SPACE::ResidentProcessCount, _MM_SESSION_SPACE::Session, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::TrimHard, UNREFERENCED_PARAMETER, _MM_SESSION_SPACE::Vm, and _MMSUPPORT::WorkingSetSize.
Referenced by MiAttachAndLockWorkingSet(), and MmInSwapProcess().
VOID MiSessionLeader (IN PEPROCESS Process)
Definition at line 129 of file session.c.
References LOCK_EXPANSION, and UNLOCK_EXPANSION.
Referenced by MmSessionCreate().
VOID MiSessionOutSwapProcess (IN PEPROCESS Process)
Definition at line 3136 of file session.c.
References ASSERT, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, InterlockedDecrement, InterlockedIncrement, KeQuerySystemTime(), _MM_SESSION_SPACE::LastProcessSwappedOutTime, MM_DBG_SESSIONS, NULL, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_VM_DELETED, _MM_SESSION_SPACE::ReferenceCount, _MM_SESSION_SPACE::ResidentProcessCount, _MM_SESSION_SPACE::Session, _MM_SESSION_SPACE::SessionId, _MM_SESSION_SPACE::Vm, and _MMSUPPORT::WorkingSetSize.
Referenced by MmOutSwapProcess().
PVOID MiSessionPoolBigPageTable (VOID)
Definition at line 618 of file session.c.
References ASSERT, KeGetCurrentIrql(), MiSessionDataPages, MiSessionTagSizePages, MmSessionSpace, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor().
SIZE_T MiSessionPoolBigPageTableSize (VOID)
Definition at line 628 of file session.c.
References ASSERT, FALSE, KeGetCurrentIrql(), MiSessionBigPoolPages, NumberOfBytes, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor().
PGENERAL_LOOKASIDE MiSessionPoolLookaside (VOID)
Definition at line 569 of file session.c.
References ASSERT, KeGetCurrentIrql(), _MM_SESSION_SPACE::Lookaside, MmSessionSpace, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor().
ULONG MiSessionPoolSmallLists (VOID)
Definition at line 561 of file session.c.
References SESSION_POOL_SMALL_LISTS.
Referenced by ExInitializePoolDescriptor().
PVOID MiSessionPoolTrackTable (VOID)
Definition at line 579 of file session.c.
References ASSERT, KeGetCurrentIrql(), MiSessionDataPages, MmSessionSpace, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor(), and MiCheckSessionPoolAllocations().
SIZE_T MiSessionPoolTrackTableSize (VOID)
Definition at line 589 of file session.c.
References ASSERT, FALSE, KeGetCurrentIrql(), MiSessionTagSizePages, NumberOfBytes, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor(), and MiCheckSessionPoolAllocations().
VOID MiSessionRemoveProcess (VOID)
Definition at line 268 of file session.c.
References ASSERT, CONTAINING_RECORD, _MMSUPPORT::Flags, _EPROCESS::Flags, _LIST_ENTRY::Flink, LOCK_EXPANSION, MiDereferenceSession(), MmIsAddressValid(), MmSessionSpace, _MM_SESSION_SPACE::ProcessList, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), RemoveEntryList(), SESSION_GLOBAL, _MMSUPPORT_FLAGS::SessionLeader, _EPROCESS::SessionProcessLinks, TRUE, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by MmCleanProcessAddressSpace().
NTSTATUS MmAttachSession (IN PVOID OpaqueSession, OUT PRKAPC_STATE ApcState)
Definition at line 3834 of file session.c.
References APC_LEVEL, ASSERT, _MM_SESSION_SPACE::AttachCount, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, KeGetCurrentIrql(), KeStackAttachProcess(), LOCK_EXPANSION, NULL, _EPROCESS::Pcb, PsGetCurrentProcess(), _EPROCESS::Session, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by ExGetSessionPoolTagInformation(), ExpWin32SessionCallout(), MmGetSessionMappedViewInformation(), and PspWin32SessionCallout().
NTSTATUS MmDetachSession (IN PVOID OpaqueSession, IN PRKAPC_STATE ApcState)
Definition at line 3933 of file session.c.
References APC_LEVEL, ASSERT, _MM_SESSION_SPACE::AttachCount, _MM_SESSION_SPACE::AttachEvent, _MM_SESSION_SPACE_FLAGS::DeletePending, FALSE, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, KeGetCurrentIrql(), KeSetEvent(), KeUnstackDetachProcess(), LOCK_EXPANSION, NULL, _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, STATUS_SUCCESS, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by ExGetSessionPoolTagInformation(), ExpWin32SessionCallout(), MmGetSessionMappedViewInformation(), and PspWin32SessionCallout().
PVOID MmGetNextSession (IN PVOID OpaqueSession)
Definition at line 3454 of file session.c.
References APC_LEVEL, ASSERT, CONTAINING_RECORD, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_EXPANSION, MiSessionWsList, NULL, ObDereferenceObject(), ObReferenceObject, _MM_SESSION_SPACE::ProcessList, _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, _EPROCESS::Vm, _MMSUPPORT::VmWorkingSetList, and _MM_SESSION_SPACE::WsListEntry.
Referenced by ExGetSessionPoolTagInformation(), and MmGetSessionMappedViewInformation().
PVOID MmGetPreviousSession (IN PVOID OpaqueSession)
Definition at line 3676 of file session.c.
References APC_LEVEL, ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_EXPANSION, MiSessionWsList, NULL, ObDereferenceObject(), ObReferenceObject, _MM_SESSION_SPACE::ProcessList, _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, _EPROCESS::Vm, and _MM_SESSION_SPACE::WsListEntry.
PVOID MmGetSessionById (IN ULONG SessionId)
Definition at line 4002 of file session.c.
References APC_LEVEL, ASSERT, CONTAINING_RECORD, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_EXPANSION, MiSessionWsList, NULL, ObReferenceObject, _MM_SESSION_SPACE::ProcessList, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by ExpWin32SessionCallout(), and PspWin32SessionCallout().
ULONG MmGetSessionId (IN PEPROCESS Process)
Definition at line 3333 of file session.c.
References NULL, _MM_SESSION_SPACE::Session, and _MM_SESSION_SPACE::SessionId.
Referenced by ExGetSessionPoolTagInformation(), ExpGetProcessInformation(), IoGetRequestorSessionId(), MiFindImageSectionObject(), MiInsertImageSectionObject(), MmCreatePeb(), MmGetSessionMappedViewInformation(), NtAssignProcessToJobObject(), NtCreateJobObject(), NtQueryInformationProcess(), NtSetInformationProcess(), PsGetCurrentProcessSessionId(), PsGetProcessSessionId(), PsGetThreadSessionId(), PspInitializeProcessSecurity(), PspWin32SessionCallout(), PsShutdownSystem(), RtlpWalkFrameChain(), SeExchangePrimaryToken(), and WmiTraceProcess().
ULONG MmGetSessionIdEx (IN PEPROCESS Process)
Definition at line 3393 of file session.c.
References NULL, _MM_SESSION_SPACE::Session, and _MM_SESSION_SPACE::SessionId.
Referenced by PsGetProcessSessionIdEx().
LCID MmGetSessionLocaleId (VOID)
Definition at line 360 of file session.c.
References _MMSUPPORT::Flags, _MM_SESSION_SPACE::LocaleId, NULL, PAGED_CODE, PsDefaultThreadLocaleId, PsGetCurrentProcess(), _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, and _EPROCESS::Vm.
Referenced by NtQueryDefaultLocale(), and PspUserThreadStartup().
NTSTATUS MmQuitNextSession (IN PVOID OpaqueSession)
Definition at line 3790 of file session.c.
References APC_LEVEL, ASSERT, _MMSUPPORT::Flags, KeGetCurrentIrql(), NULL, ObDereferenceObject(), _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, STATUS_SUCCESS, and _EPROCESS::Vm.
Referenced by ExGetSessionPoolTagInformation(), ExpWin32SessionCallout(), MmGetSessionMappedViewInformation(), and PspWin32SessionCallout().
NTSTATUS MmSessionCreate (OUT PULONG SessionId)
Definition at line 1441 of file session.c.
References ASSERT, ExInitializePagedLookasideList(), FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _MM_SESSION_SPACE::Flags, _MM_SESSION_SPACE_FLAGS::Initialized, InterlockedCompareExchange(), KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _MMPTE::Long, _MM_SESSION_SPACE::Lookaside, MiDereferenceSession(), MiGetPdeAddress, MiGetPxeAddress, MiInitializeSpecialPool(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiSessionLeader(), MiSessionLeaderExists, MiSessionSpaceEnd, MmIsAddressValid(), MmSessionBase, MmSessionSpace, NT_SUCCESS, NULL, PagedPoolSession, PS_PROCESS_FLAGS_IN_SESSION, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), SESSION_GLOBAL, SESSION_POOL_SMALL_LISTS, _MMSUPPORT_FLAGS::SessionLeader, Status, STATUS_ALREADY_COMMITTED, STATUS_INVALID_SYSTEM_SERVICE, _ETHREAD::Tcb, _MMPTE::u, _MM_SESSION_SPACE::u, and _EPROCESS::Vm.
Referenced by NtSetSystemInformation().
NTSTATUS MmSessionDelete (ULONG SessionId)
Definition at line 1594 of file session.c.
References ASSERT, DbgBreakPoint(), DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _MMSUPPORT::Flags, _EPROCESS::Flags, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), MiDereferenceSession(), MmIsAddressValid(), MmSessionSpace, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, STATUS_SUCCESS, STATUS_UNABLE_TO_FREE_VM, _ETHREAD::Tcb, TRUE, and _EPROCESS::Vm.
VOID MmSessionSetUnloadAddress (IN PDRIVER_OBJECT DriverObject)
Definition at line 166 of file session.c.
References ASSERT, MmIsAddressValid(), MmSessionSpace, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), TRUE, and _MM_SESSION_SPACE::Win32KDriverUnload.
Referenced by NtSetSystemInformation().
VOID MmSetSessionLocaleId (IN LCID LocaleId)
Definition at line 424 of file session.c.
References _MMSUPPORT::Flags, _MM_SESSION_SPACE::LocaleId, NULL, PAGED_CODE, PsDefaultThreadLocaleId, PsGetCurrentProcess(), _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, and _EPROCESS::Vm.
Referenced by NtSetDefaultLocale().
Variable Documentation
ULONG MiSessionBigPoolPages
Definition at line 41 of file session.c.
Referenced by MiInitializeSessionIds(), and MiSessionPoolBigPageTableSize().
ULONG MiSessionCreateCharge
Definition at line 43 of file session.c.
Referenced by MiInitializeSessionIds(), and MiSessionCreateInternal().
ULONG MiSessionDataPages
Definition at line 38 of file session.c.
Referenced by MiDereferenceSessionFinal(), MiInitializeSessionIds(), MiReleaseProcessReferenceToSessionDataPage(), MiSessionCreateInternal(), MiSessionPoolBigPageTable(), and MiSessionPoolTrackTable().
PRTL_BITMAP MiSessionIdBitmap = {0}
Definition at line 30 of file session.c.
KGUARDED_MUTEX MiSessionIdMutex
Definition at line 24 of file session.c.
LONG MiSessionLeaderExists
Definition at line 1437 of file session.c.
Referenced by MmSessionCreate().
ULONG MiSessionTagPages
Definition at line 39 of file session.c.
Referenced by MiDereferenceSessionFinal(), MiInitializeSessionIds(), and MiSessionCreateInternal().
ULONG MiSessionTagSizePages
Definition at line 40 of file session.c.
Referenced by MiInitializeSessionIds(), MiSessionPoolBigPageTable(), and MiSessionPoolTrackTableSize().
LONG MmSessionDataPages
Definition at line 22 of file session.c.
Referenced by MiReleaseProcessReferenceToSessionDataPage(), and MiSessionCreateInternal().