Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcpriv.c File Reference
lpcpriv.c File Reference
#include "lpcp.h"
Functions
VOID LpcpFreePortClientSecurity (IN PLPCP_PORT_OBJECT Port)
NTSTATUS NtImpersonateClientOfPort (__in HANDLE PortHandle, __in PPORT_MESSAGE Message)
Function Documentation
VOID LpcpFreePortClientSecurity (IN PLPCP_PORT_OBJECT Port)
Definition at line 285 of file lpcpriv.c.
References CLIENT_COMMUNICATION_PORT, PORT_DYNAMIC_SECURITY, PORT_TYPE, and SeDeleteClientSecurity.
Referenced by LpcpDeletePort().
NTSTATUS NtImpersonateClientOfPort (__in HANDLE PortHandle, __in PPORT_MESSAGE Message)
Definition at line 29 of file lpcpriv.c.
References _LPCP_PORT_OBJECT::ConnectedPort, except, EXCEPTION_EXECUTE_HANDLER, _LPCP_PORT_OBJECT::Flags, KeGetPreviousMode, KernelMode, LPCP_NO_IMPERSONATION, LPCP_VALIDATE_REASON_IMPERSONATION, LpcpAcquireLpcpLock, LpcpFreeDynamicClientSecurity, LpcpGetDynamicClientSecurity, LpcpGetThreadAttributes, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpValidateClientPort(), _ETHREAD::LpcReplyMessageId, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PAGED_CODE, PORT_DYNAMIC_SECURITY, PORT_TYPE, ProbeForReadSmallStructure, PsLookupProcessThreadByCid(), SeImpersonateClientEx(), SERVER_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::StaticSecurity, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PORT_HANDLE, STATUS_PORT_DISCONNECTED, and STATUS_REPLY_MESSAGE_MISMATCH.