Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/kix86.h File Reference
kix86.h File Reference
Data Structures
struct _IDENTITY_MAP
Macros
#define CONTEXT_ALIGNED_SIZE ((sizeof(CONTEXT) + CONTEXT_ROUND) & ~CONTEXT_ROUND)
#define KiGetCurrentReadySummary() (KAFFINITY)__readfsdword(FIELD_OFFSET(KPCR, PrcbData.ReadySummary))
#define KiGetPdeIndex(va) ((((ULONG)(va)) >> PDI_SHIFT) & PDI_MASK)
#define KiGetPpeIndex(va) ((((ULONG)(va)) >> PPI_SHIFT) & PPI_MASK)
#define KiGetPteIndex(va) ((((ULONG)(va)) >> PTI_SHIFT) & PTI_MASK)
#define KiIpiSendSynchronousPacket(Prcb, Target, Function, P1, P2, P3)
#define MAX_IDENTITYMAP_ALLOCATIONS 30
#define PDI_BITS 10
#define PDI_MASK ((1 << PDI_BITS) - 1)
#define PPI_BITS 0
#define PPI_MASK ((1 << PPI_BITS) - 1)
#define PTI_BITS 10
#define PTI_MASK ((1 << PTI_BITS) - 1)
Typedefs
typedef struct _IDENTITY_MAP IDENTITY_MAP
typedef struct _IDENTITY_MAP * PIDENTITY_MAP
Functions
C_ASSERT ((CONTEXT_ALIGNED_SIZE &CONTEXT_ROUND)==0)
VOID Ke386ConfigureCyrixProcessor (VOID)
VOID Ki386ClearIdentityMap (PIDENTITY_MAP IdentityMap)
BOOLEAN Ki386CreateIdentityMap (IN OUT PIDENTITY_MAP IdentityMap, IN PVOID StartVa, IN PVOID EndVa)
BOOLEAN Ki386EnableCurrentLargePage (IN ULONG IdentityAddr, IN ULONG IdentityCr3)
VOID Ki386EnableTargetLargePage (PIDENTITY_MAP IdentityMap)
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
VOID KiFlushNPXState (PFLOATING_SAVE_AREA SaveArea)
VOID KiInitializePcr (IN ULONG Processor, IN PKPCR Pcr, IN PKIDTENTRY Idt, IN PKGDTENTRY Gdt, IN PKTSS Tss, IN PKTHREAD Thread, IN PVOID DpcStack)
VOID FASTCALL KiIpiSignalPacketDoneAndStall (IN PKIPI_CONTEXT Signaldone, IN ULONG volatile *ReverseStall)
BOOLEAN FASTCALL KiProcessDebugRegister (IN OUT PKTRAP_FRAME TrapFrame, IN ULONG Register)
BOOLEAN FASTCALL KiRecordDr7 (IN OUT PULONG Dr7Ptr, IN OUT PUCHAR Mask OPTIONAL)
VOID KiSetHardwareTrigger (VOID)
ULONG FASTCALL KiUpdateDr7 (IN ULONG Dr7)
__inline VOID Kix86FnSave (PFX_SAVE_AREA NpxFrame)
__inline VOID Kix86FxSave (PFX_SAVE_AREA NpxFrame)
__inline VOID Kix86LdMXCsr (PULONG MXCsr)
__inline VOID Kix86StMXCsr (PULONG MXCsr)
Variables
PVOID Ki386EnableCurrentLargePageEnd
const ULONG KiDebugRegisterContextOffsets []
const ULONG KiDebugRegisterTrapOffsets []
LONG64 KiMtrrMaskBase
LONG64 KiMtrrMaskMask
UCHAR KiMtrrMaxRangeShift
LONG64 KiMtrrOverflowMask
LONG64 KiMtrrResBitMask
KIRQL KiProfileIrql
Macro Definition Documentation
#define CONTEXT_ALIGNED_SIZE ((sizeof(CONTEXT) + CONTEXT_ROUND) & ~CONTEXT_ROUND)
Definition at line 230 of file kix86.h.
Referenced by KiDispatchException(), and KiInitializeUserApc().
#define KiGetCurrentReadySummary () (KAFFINITY)__readfsdword(FIELD_OFFSET(KPCR, PrcbData.ReadySummary))
Definition at line 28 of file kix86.h.
#define KiGetPdeIndex (va) ((((ULONG)(va)) >> PDI_SHIFT) & PDI_MASK)
Definition at line 288 of file kix86.h.
#define KiGetPpeIndex (va) ((((ULONG)(va)) >> PPI_SHIFT) & PPI_MASK)
Definition at line 287 of file kix86.h.
#define KiGetPteIndex (va) ((((ULONG)(va)) >> PTI_SHIFT) & PTI_MASK)
Definition at line 289 of file kix86.h.
#define KiIpiSendSynchronousPacket (Prcb, Target, Function, P1, P2, P3)
Value:
{                                                                   \
        extern PKPRCB KiSynchPacket;                                    \
                                                                        \
        Prcb->CurrentPacket[0] = (PVOID)(P1);                           \
        Prcb->CurrentPacket[1] = (PVOID)(P2);                           \
        Prcb->CurrentPacket[2] = (PVOID)(P3);                           \
        Prcb->TargetSet = (Target);                                     \
        Prcb->WorkerRoutine = (Function);                               \
        if (((Target) & ((Target) - 1)) == 0) {                         \
           KiSynchPacket = (PKPRCB)((ULONG_PTR)(Prcb) | 1);             \
        } else {                                                        \
           KiSynchPacket = (Prcb);                                      \
           Prcb->PacketBarrier = 1;                                     \
        }                                                               \
        KiIpiSend((Target),IPI_SYNCH_REQUEST);                          \
    }
Definition at line 58 of file kix86.h.
Referenced by KeInvalidateAllCaches(), KiCompleteEffectiveRangeChange(), KiInitializePAT(), and KiLockStepOtherProcessors().
#define MAX_IDENTITYMAP_ALLOCATIONS 30
Definition at line 237 of file kix86.h.
#define PDI_BITS 10
Definition at line 279 of file kix86.h.
#define PDI_MASK ((1 << PDI_BITS) - 1)
Definition at line 284 of file kix86.h.
#define PPI_BITS 0
Definition at line 278 of file kix86.h.
#define PPI_MASK ((1 << PPI_BITS) - 1)
Definition at line 283 of file kix86.h.
#define PTI_BITS 10
Definition at line 280 of file kix86.h.
#define PTI_MASK ((1 << PTI_BITS) - 1)
Definition at line 285 of file kix86.h.
Typedef Documentation
typedef struct _IDENTITY_MAP IDENTITY_MAP
typedef struct _IDENTITY_MAP * PIDENTITY_MAP
Function Documentation
C_ASSERT ((CONTEXT_ALIGNED_SIZE &CONTEXT_ROUND) = =0)
VOID Ke386ConfigureCyrixProcessor (VOID)
Referenced by KeOptimizeProcessorControlState().
VOID Ki386ClearIdentityMap (PIDENTITY_MAP IdentityMap)
Referenced by KiInitMachineDependent().
BOOLEAN Ki386CreateIdentityMap (IN OUT PIDENTITY_MAP IdentityMap, IN PVOID StartVa, IN PVOID EndVa)
Definition at line 60 of file largepag.c.
References FALSE, Ki386BuildIdentityBuffer(), Ki386ConvertPte(), Ki386MapAddress(), _LARGE_INTEGER::LowPart, MmGetPhysicalAddress(), PAGE_SIZE, PPI_BITS, PTES_PER_PAGE, _LARGE_INTEGER::QuadPart, RtlZeroMemory, TRUE, and _HARDWARE_PTE_X86::Valid.
Referenced by KiInitMachineDependent().
BOOLEAN Ki386EnableCurrentLargePage (IN ULONG IdentityAddr, IN ULONG IdentityCr3)
Referenced by Ki386EnableTargetLargePage(), and KiInitMachineDependent().
VOID Ki386EnableTargetLargePage (PIDENTITY_MAP IdentityMap)
Referenced by KiInitMachineDependent().
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
Definition at line 821 of file exceptn.c.
VOID KiFlushNPXState (PFLOATING_SAVE_AREA SaveArea)
Referenced by KeContextFromKframes(), and KeContextToKframes().
VOID KiInitializePcr (IN ULONG Processor, IN PKPCR Pcr, IN PKIDTENTRY Idt, IN PKGDTENTRY Gdt, IN PKTSS Tss, IN PKTHREAD Thread, IN PVOID DpcStack)
Definition at line 969 of file kernlini.c.
References _KPRCB::DpcStack, EXCEPTION_CHAIN_END, KiProcessorBlock, NULL, PCR_MAJOR_VERSION, PCR_MINOR_VERSION, PF_PAE_ENABLED, PRCB_BUILD_DEBUG, PRCB_BUILD_UNIPROCESSOR, PRCB_MAJOR_VERSION, PRCB_MINOR_VERSION, SharedUserData, and TRUE.
VOID FASTCALL KiIpiSignalPacketDoneAndStall (IN PKIPI_CONTEXT Signaldone, IN ULONG volatile * ReverseStall)
Referenced by KiInvalidateAllCachesTarget(), KiLoadMTRRTarget(), KiLoadPATTarget(), and KiLockStepProcessor().
BOOLEAN FASTCALL KiProcessDebugRegister (IN OUT PKTRAP_FRAME TrapFrame, IN ULONG Register)
Definition at line 1686 of file misc.c.
References ASSERT, _DISPATCHER_HEADER::DebugActive, DR7_OVERRIDE_MASK, DR7_OVERRIDE_V, DR7_RESERVED_MASK, DR_MASK, DR_REG_MASK, FALSE, _KTHREAD::Header, and KeGetCurrentThread().
BOOLEAN FASTCALL KiRecordDr7 (IN OUT PULONG Dr7Ptr, IN OUT PUCHAR Mask OPTIONAL)
Definition at line 1587 of file misc.c.
References ARGUMENT_PRESENT, ASSERT, _DISPATCHER_HEADER::DebugActive, DR7_OVERRIDE_MASK, DR7_OVERRIDE_V, DR7_RESERVED_MASK, DR_MASK, DR_REG_MASK, FALSE, _KTHREAD::Header, and KeGetCurrentThread().
Referenced by KeContextToKframes().
VOID KiSetHardwareTrigger (VOID)
ULONG FASTCALL KiUpdateDr7 (IN ULONG Dr7)
Definition at line 1779 of file misc.c.
References ASSERT, _DISPATCHER_HEADER::DebugActive, DR7_OVERRIDE_MASK, DR7_OVERRIDE_V, DR7_RESERVED_MASK, DR_MASK, DR_REG_MASK, _KTHREAD::Header, and KeGetCurrentThread().
Referenced by KeContextFromKframes().
__inline VOID Kix86FnSave (PFX_SAVE_AREA NpxFrame)
Definition at line 117 of file kix86.h.
Referenced by KeSaveFloatingPointState().
__inline VOID Kix86FxSave (PFX_SAVE_AREA NpxFrame)
Definition at line 98 of file kix86.h.
Referenced by KeSaveFloatingPointState(), and KiInitMachineDependent().
__inline VOID Kix86LdMXCsr (PULONG MXCsr)
Definition at line 133 of file kix86.h.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
__inline VOID Kix86StMXCsr (PULONG MXCsr)
Definition at line 152 of file kix86.h.
Referenced by KeSaveFloatingPointState().
Variable Documentation
PVOID Ki386EnableCurrentLargePageEnd
Referenced by KiInitMachineDependent().
const ULONG KiDebugRegisterContextOffsets[]
Definition at line 1573 of file misc.c.
Referenced by KeContextToKframes().
const ULONG KiDebugRegisterTrapOffsets[]
Definition at line 1561 of file misc.c.
Referenced by KeContextToKframes().
LONG64 KiMtrrMaskBase
Definition at line 42 of file mtrr.c.
Referenced by KiGetFeatureBits(), and KiInitializeMTRR().
LONG64 KiMtrrMaskMask
Definition at line 43 of file mtrr.c.
Referenced by KiCompleteEffectiveRangeChange(), KiGetFeatureBits(), and KiInitializeMTRR().
UCHAR KiMtrrMaxRangeShift
Definition at line 46 of file mtrr.c.
Referenced by KiCompleteEffectiveRangeChange(), KiGetFeatureBits(), KiLengthToMask(), and KiMaskToLength().
LONG64 KiMtrrOverflowMask
Definition at line 44 of file mtrr.c.
Referenced by KiGetFeatureBits(), and KiInitializeMTRR().
LONG64 KiMtrrResBitMask
Definition at line 45 of file mtrr.c.
Referenced by KiGetFeatureBits(), and KiLengthToMask().
KIRQL KiProfileIrql
Definition at line 28 of file initkr.c.
Referenced by KeSetProfileIrql(), KeStartProfile(), KeStopProfile(), KiStartProfileInterrupt(), and KiStopProfileInterrupt().