Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/dpclock.c File Reference
dpclock.c File Reference
#include "ki.h"
Functions
VOID FASTCALL KeAcquireInStackQueuedSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
KIRQL FASTCALL KeAcquireSpinLockForDpc (__inout PKSPIN_LOCK SpinLock)
VOID FASTCALL KeReleaseInStackQueuedSpinLockForDpc (__in PKLOCK_QUEUE_HANDLE LockHandle)
VOID FASTCALL KeReleaseSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __in KIRQL OldIrql)
Function Documentation
VOID FASTCALL KeAcquireInStackQueuedSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 92 of file dpclock.c.
References KiAcquireInStackQueuedSpinLockForDpc().
KIRQL FASTCALL KeAcquireSpinLockForDpc (__inout PKSPIN_LOCK SpinLock)
Definition at line 24 of file dpclock.c.
References KiAcquireSpinLockForDpc().
VOID FASTCALL KeReleaseInStackQueuedSpinLockForDpc (__in PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 127 of file dpclock.c.
References KiReleaseInStackQueuedSpinLockForDpc().
VOID FASTCALL KeReleaseSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __in KIRQL OldIrql)
Definition at line 56 of file dpclock.c.
References KiReleaseSpinLockForDpc().