Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ps.h File Reference
ps.h File Reference
Data Structures
struct _EJOB
struct _EPROCESS
struct _EPROCESS_QUOTA_BLOCK
struct _EPROCESS_QUOTA_ENTRY
struct _EPROCESS_QUOTA_TRACK
struct _ETHREAD
struct _IMAGE_INFO
struct _INITIAL_PEB
struct _MM_AVL_TABLE
struct _MMADDRESS_NODE
struct _MMSUPPORT
struct _MMSUPPORT_FLAGS
struct _PAGEFAULT_HISTORY
struct _PS_IMPERSONATION_INFORMATION
struct _PS_JOB_TOKEN_FILTER
struct _SE_AUDIT_PROCESS_CREATION_INFO
struct _TERMINATION_PORT
struct _WIN32_CALLOUTS_FPNS
struct _WIN32_JOBCALLOUT_PARAMETERS
struct _WIN32_POWEREVENT_PARAMETERS
struct _WIN32_POWERSTATE_PARAMETERS
struct _WOW64_PROCESS
Macros
#define _PsGetCurrentProcess() (CONTAINING_RECORD(((KeGetCurrentThread())->ApcState.Process),EPROCESS,Pcb))
#define _PsGetCurrentThread() ((PETHREAD)KeGetCurrentThread())
#define EPROCESS_QUOTA_TRACK_MAX 10000
#define IMAGE_ADDRESSING_MODE_32BIT 3
#define IS_SYSTEM_THREAD(Thread) (((Thread)->CrossThreadFlags&PS_CROSS_THREAD_FLAGS_SYSTEM) != 0)
#define MEMORY_PRIORITY_BACKGROUND 0
#define MEMORY_PRIORITY_FOREGROUND 2
#define MEMORY_PRIORITY_WASFOREGROUND 1
#define MI_MAKE_PARENT(ParentNode, ExistingBalance) (PMMADDRESS_NODE)((ULONG_PTR)(ParentNode) | ((ExistingBalance) & 0x3))
#define PS_CLEAR_BITS(Flags, Flag) RtlInterlockedClearBitsDiscardReturn (Flags, Flag)
#define PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION 0x00000040UL
#define PS_CROSS_THREAD_FLAGS_DEADTHREAD 0x00000002UL
#define PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED 0x00000020UL
#define PS_CROSS_THREAD_FLAGS_HIDEFROMDBG 0x00000004UL
#define PS_CROSS_THREAD_FLAGS_IMPERSONATING 0x00000008UL
#define PS_CROSS_THREAD_FLAGS_SKIP_CREATION_MSG 0x00000080UL
#define PS_CROSS_THREAD_FLAGS_SKIP_TERMINATION_MSG 0x00000100UL
#define PS_CROSS_THREAD_FLAGS_SYSTEM 0x00000010UL
#define PS_CROSS_THREAD_FLAGS_TERMINATED 0x00000001UL
#define PS_EMBEDDED_NO_USERMODE 1
#define PS_GET_THREAD_CREATE_TIME(Thread) ((Thread)->CreateTime.QuadPart)
#define PS_GET_WOW64_PROCESS(Process) ((Process), ((PWOW64_PROCESS)NULL))
#define PS_IS_THREAD_IMPERSONATING(Thread) (((Thread)->CrossThreadFlags&PS_CROSS_THREAD_FLAGS_IMPERSONATING) != 0)
#define PS_JOB_FLAGS_CLOSE_DONE 0x1UL
#define PS_JOB_STATUS_ACCOUNTING_FOLDED 0x00000002UL
#define PS_JOB_STATUS_EXIT_PROCESS_REPORTED 0x00000008UL
#define PS_JOB_STATUS_LAST_REPORT_MEMORY 0x00000020UL
#define PS_JOB_STATUS_NEW_PROCESS_REPORTED 0x00000004UL
#define PS_JOB_STATUS_NOT_REALLY_ACTIVE 0x00000001UL
#define PS_JOB_STATUS_REPORT_COMMIT_CHANGES 0x00000010UL
#define PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES 0x00000040UL
#define PS_PROCESS_FLAGS_ADDRESS_SPACE1 0x00000400UL
#define PS_PROCESS_FLAGS_ADDRESS_SPACE2 0x00000800UL
#define PS_PROCESS_FLAGS_BREAK_ON_TERMINATION 0x00002000UL
#define PS_PROCESS_FLAGS_CREATE_FAILED 0x04000000UL
#define PS_PROCESS_FLAGS_CREATE_REPORTED 0x00000001UL
#define PS_PROCESS_FLAGS_CREATING_SESSION 0x00004000UL
#define PS_PROCESS_FLAGS_DEFAULT_IO_PRIORITY 0x38000000UL
#define PS_PROCESS_FLAGS_EXECUTE_SPARE1 0x40000000UL
#define PS_PROCESS_FLAGS_EXECUTE_SPARE2 0x80000000UL
#define PS_PROCESS_FLAGS_FORK_FAILED 0x00000100UL
#define PS_PROCESS_FLAGS_HAS_ADDRESS_SPACE 0x00040000UL
#define PS_PROCESS_FLAGS_IMAGE_NOTIFY_DONE 0x00400000UL
#define PS_PROCESS_FLAGS_IN_SESSION 0x00010000UL
#define PS_PROCESS_FLAGS_LAUNCH_PREFETCHED 0x00080000UL
#define PS_PROCESS_FLAGS_NO_DEBUG_INHERIT 0x00000002UL
#define PS_PROCESS_FLAGS_OUTSWAP_ENABLED 0x00000040UL
#define PS_PROCESS_FLAGS_OUTSWAPPED 0x00000080UL
#define PS_PROCESS_FLAGS_OVERRIDE_ADDRESS_SPACE 0x00020000UL
#define PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED 0x00800000UL
#define PS_PROCESS_FLAGS_PRIORITY_SHIFT 27
#define PS_PROCESS_FLAGS_PROCESS_DELETE 0x00000008UL
#define PS_PROCESS_FLAGS_PROCESS_EXITING 0x00000004UL
#define PS_PROCESS_FLAGS_SET_TIMER_RESOLUTION 0x00001000UL
#define PS_PROCESS_FLAGS_SMAP_ALLOWED 0x02000000UL
#define PS_PROCESS_FLAGS_USING_WRITE_WATCH 0x00008000UL
#define PS_PROCESS_FLAGS_VDM_ALLOWED 0x01000000UL
#define PS_PROCESS_FLAGS_VM_DELETED 0x00000020UL
#define PS_PROCESS_FLAGS_VM_TOP_DOWN 0x00200000UL
#define PS_PROCESS_FLAGS_WOW64_4GB_VA_SPACE 0x00000200UL
#define PS_PROCESS_FLAGS_WOW64_SPLIT_PAGES 0x00000010UL
#define PS_PROCESS_INJECT_INPAGE_ERRORS 0x00100000UL
#define PS_SAME_THREAD_FLAGS_OWNS_A_WORKING_SET 0x000001F8UL
#define PS_SET_BITS(Flags, Flag) RtlInterlockedSetBitsDiscardReturn (Flags, Flag)
#define PS_SET_CLEAR_BITS(Flags, sFlag, cFlag) RtlInterlockedSetClearBits (Flags, sFlag, cFlag)
#define PS_SET_THREAD_CREATE_TIME(Thread, InputCreateTime) ((Thread)->CreateTime.QuadPart = (InputCreateTime.QuadPart))
#define PS_TEST_ALL_BITS_SET(Flags, Bits) ((Flags&(Bits)) == (Bits))
#define PS_TEST_CLEAR_BITS(Flags, Flag) RtlInterlockedClearBits (Flags, Flag)
#define PS_TEST_SET_BITS(Flags, Flag) RtlInterlockedSetBits (Flags, Flag)
#define PS_WS_TRIM_BACKGROUND_ONLY_APP 2
#define PS_WS_TRIM_FROM_EXE_HEADER 1
#define PsDereferenceImpersonationToken(T)
#define PsDereferencePrimaryToken(T) (ObDereferenceObject((T)))
#define PsDereferencePrimaryTokenEx(P, T) (ObFastDereferenceObject (&P->Token,(T)))
#define PsGetCurrentProcess() _PsGetCurrentProcess()
#define PsGetCurrentProcessByThread(xCurrentThread) (ASSERT((xCurrentThread) == PsGetCurrentThread ()),CONTAINING_RECORD(((xCurrentThread)->Tcb.ApcState.Process),EPROCESS,Pcb))
#define PsGetCurrentProcessImageFileName() PsGetProcessImageFileName(PsGetCurrentProcess())
#define PsGetCurrentProcessWin32WindowStation() PsGetProcessWin32WindowStation(PsGetCurrentProcess())
#define PsGetCurrentThread() _PsGetCurrentThread()
#define PsGetProcessPcb(Process) ((PKPROCESS)(Process))
#define PsGetThreadTcb(Thread) ((PKTHREAD)(Thread))
#define PsIsThreadTerminating(T) (((T)->CrossThreadFlags&PS_CROSS_THREAD_FLAGS_TERMINATED) != 0)
#define PsProcessAuditId(Process) ((Process)->UniqueProcessId)
#define SANITIZE_PARENT_NODE(Parent) ((PMMADDRESS_NODE)(((ULONG_PTR)(Parent)) & ~0x3))
#define THREAD_HIT_SLOTS 750
#define THREAD_TO_PROCESS(Thread) ((Thread)->ThreadsProcess)
Typedefs
typedef struct _EJOB EJOB
typedef struct _EPROCESS EPROCESS
typedef struct _EPROCESS_QUOTA_BLOCK EPROCESS_QUOTA_BLOCK
typedef struct _EPROCESS_QUOTA_ENTRY EPROCESS_QUOTA_ENTRY
typedef struct _EPROCESS_QUOTA_TRACK EPROCESS_QUOTA_TRACK
typedef struct _ETHREAD ETHREAD
typedef struct _IMAGE_INFO IMAGE_INFO
typedef struct _INITIAL_PEB INITIAL_PEB
typedef struct _MM_AVL_TABLE MM_AVL_TABLE
typedef struct _MMADDRESS_NODE MMADDRESS_NODE
typedef struct _MMSUPPORT MMSUPPORT
typedef struct _MMSUPPORT_FLAGS MMSUPPORT_FLAGS
typedef struct _PAGEFAULT_HISTORY PAGEFAULT_HISTORY
typedef VOID(* PBBT_NOTIFY_ROUTINE) (PKTHREAD Thread)
typedef VOID(* PCREATE_PROCESS_NOTIFY_ROUTINE) (IN HANDLE ParentId, IN HANDLE ProcessId, IN BOOLEAN Create)
typedef VOID(* PCREATE_THREAD_NOTIFY_ROUTINE) (IN HANDLE ProcessId, IN HANDLE ThreadId, IN BOOLEAN Create)
typedef EJOB * PEJOB
typedef struct _EPROCESS * PEPROCESS
typedef struct _EPROCESS_QUOTA_BLOCK * PEPROCESS_QUOTA_BLOCK
typedef struct _EPROCESS_QUOTA_ENTRY * PEPROCESS_QUOTA_ENTRY
typedef struct _EPROCESS_QUOTA_TRACK * PEPROCESS_QUOTA_TRACK
typedef struct _ETHREAD * PETHREAD
typedef struct _IMAGE_INFO * PIMAGE_INFO
typedef struct _INITIAL_PEB * PINITIAL_PEB
typedef struct _WIN32_CALLOUTS_FPNS * PKWIN32_CALLOUTS_FPNS
typedef NTSTATUS(* PKWIN32_JOB_CALLOUT) (IN PKWIN32_JOBCALLOUT_PARAMETERS Parm)
typedef struct _WIN32_JOBCALLOUT_PARAMETERS * PKWIN32_JOBCALLOUT_PARAMETERS
typedef NTSTATUS(* PKWIN32_OBJECT_CALLOUT) (IN PVOID Parm)
typedef NTSTATUS(* PKWIN32_POWEREVENT_CALLOUT) (IN PKWIN32_POWEREVENT_PARAMETERS Parm)
typedef struct _WIN32_POWEREVENT_PARAMETERS * PKWIN32_POWEREVENT_PARAMETERS
typedef NTSTATUS(* PKWIN32_POWERSTATE_CALLOUT) (IN PKWIN32_POWERSTATE_PARAMETERS Parm)
typedef struct _WIN32_POWERSTATE_PARAMETERS * PKWIN32_POWERSTATE_PARAMETERS
typedef NTSTATUS(* PKWIN32_PROCESS_CALLOUT) (IN PEPROCESS Process, IN BOOLEAN Initialize)
typedef NTSTATUS(* PKWIN32_THREAD_CALLOUT) (IN PETHREAD Thread, IN PSW32THREADCALLOUTTYPE CalloutType)
typedef VOID(* PLOAD_IMAGE_NOTIFY_ROUTINE) (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
typedef struct _MM_AVL_TABLE * PMM_AVL_TABLE
typedef struct _MMADDRESS_NODE * PMMADDRESS_NODE
typedef struct _MMSUPPORT * PMMSUPPORT
typedef enum _POWERSTATETASK POWERSTATETASK
typedef struct _PAGEFAULT_HISTORY * PPAGEFAULT_HISTORY
typedef struct _PS_IMPERSONATION_INFORMATION * PPS_IMPERSONATION_INFORMATION
typedef struct _PS_JOB_TOKEN_FILTER * PPS_JOB_TOKEN_FILTER
typedef enum _PS_QUOTA_TYPE * PPS_QUOTA_TYPE
typedef NTSTATUS(* PROCESS_ENUM_ROUTINE) (IN PEPROCESS Process, IN PVOID Context)
typedef struct _PS_IMPERSONATION_INFORMATION PS_IMPERSONATION_INFORMATION
typedef struct _PS_JOB_TOKEN_FILTER PS_JOB_TOKEN_FILTER
typedef enum _PS_QUOTA_TYPE PS_QUOTA_TYPE
typedef struct _SE_AUDIT_PROCESS_CREATION_INFO * PSE_AUDIT_PROCESS_CREATION_INFO
typedef enum _PSPOWEREVENTTYPE PSPOWEREVENTTYPE
typedef enum _PSPROCESSPRIORITYMODE PSPROCESSPRIORITYMODE
typedef enum _PSW32JOBCALLOUTTYPE PSW32JOBCALLOUTTYPE
typedef enum _PSW32THREADCALLOUTTYPE PSW32THREADCALLOUTTYPE
typedef struct _TERMINATION_PORT * PTERMINATION_PORT
typedef struct _WOW64_PROCESS * PWOW64_PROCESS
typedef ULONG * PWSLE_NUMBER
typedef struct _SE_AUDIT_PROCESS_CREATION_INFO SE_AUDIT_PROCESS_CREATION_INFO
typedef struct _TERMINATION_PORT TERMINATION_PORT
typedef NTSTATUS(* THREAD_ENUM_ROUTINE) (IN PEPROCESS Process, IN PETHREAD Thread, IN PVOID Context)
typedef struct _WIN32_CALLOUTS_FPNS WIN32_CALLOUTS_FPNS
typedef struct _WIN32_JOBCALLOUT_PARAMETERS WIN32_JOBCALLOUT_PARAMETERS
typedef struct _WIN32_POWEREVENT_PARAMETERS WIN32_POWEREVENT_PARAMETERS
typedef struct _WIN32_POWERSTATE_PARAMETERS WIN32_POWERSTATE_PARAMETERS
typedef struct _WOW64_PROCESS WOW64_PROCESS
typedef ULONG WSLE_NUMBER
Enumerations
enum _POWERSTATETASK {
PowerState_BlockSessionSwitch, PowerState_Init, PowerState_QueryApps, PowerState_QueryFailed,
PowerState_SuspendApps, PowerState_ShowUI, PowerState_NotifyWL, PowerState_ResumeApps,
PowerState_UnBlockSessionSwitch
}
enum _PS_QUOTA_TYPE { PsNonPagedPool = 0, PsPagedPool = 1, PsPageFile = 2, PsQuotaTypes = 3 }
enum _PSPOWEREVENTTYPE {
PsW32FullWake, PsW32EventCode, PsW32PowerPolicyChanged, PsW32SystemPowerState,
PsW32SystemTime, PsW32DisplayState, PsW32CapabilitiesChanged, PsW32SetStateFailed,
PsW32GdiOff, PsW32GdiOn
}
enum _PSPROCESSPRIORITYMODE { PsProcessPriorityBackground, PsProcessPriorityForeground, PsProcessPrioritySpinning }
enum _PSW32JOBCALLOUTTYPE { PsW32JobCalloutSetInformation, PsW32JobCalloutAddProcess, PsW32JobCalloutTerminate }
enum _PSW32THREADCALLOUTTYPE { PsW32ThreadCalloutInitialize, PsW32ThreadCalloutExit }
Functions
C_ASSERT (FIELD_OFFSET(EPROCESS, Pcb)==0)
C_ASSERT (FIELD_OFFSET(ETHREAD, Tcb)==0)
NTKERNELAPI NTSTATUS PsAssignImpersonationToken (__in PETHREAD Thread, __in HANDLE Token)
VOID PsCallImageNotifyRoutines (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
BOOLEAN PsChangeJobMemoryUsage (IN ULONG Flags, IN SSIZE_T Amount)
VOID PsChangeQuantumTable (BOOLEAN ModifyActiveProcesses, ULONG PrioritySeparation)
NTKERNELAPI VOID PsChargePoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
NTKERNELAPI NTSTATUS PsChargeProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
NTKERNELAPI NTSTATUS PsChargeProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
NTSTATUS PsChargeProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
NTKERNELAPI NTSTATUS PsChargeProcessPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
NTSTATUS PsChargeProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
PEPROCESS_QUOTA_BLOCK PsChargeSharedPoolQuota (IN PEPROCESS Process, IN ULONG_PTR PagedAmount, IN ULONG_PTR NonPagedAmount)
NTKERNELAPI NTSTATUS PsCreateSystemProcess (__out PHANDLE ProcessHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
NTKERNELAPI NTSTATUS PsCreateSystemThread (__out PHANDLE ThreadHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt HANDLE ProcessHandle, __out_opt PCLIENT_ID ClientId, __in PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext)
NTKERNELAPI VOID PsDereferenceImpersonationToken (__in PACCESS_TOKEN ImpersonationToken)
NTKERNELAPI VOID PsDereferencePrimaryToken (__in PACCESS_TOKEN PrimaryToken)
NTKERNELAPI BOOLEAN PsDisableImpersonation (__inout PETHREAD Thread, __inout PSE_IMPERSONATION_STATE ImpersonationState)
VOID PsEnforceExecutionTimeLimits (VOID)
NTSTATUS PsEnumProcesses (IN PROCESS_ENUM_ROUTINE CallBack, IN PVOID Context)
NTSTATUS PsEnumProcessThreads (IN PEPROCESS Process, IN THREAD_ENUM_ROUTINE CallBack, IN PVOID Context)
NTKERNELAPI VOID PsEstablishWin32Callouts (__in PKWIN32_CALLOUTS_FPNS pWin32Callouts)
VOID PsExitSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
BOOLEAN PsForwardException (IN PEXCEPTION_RECORD ExceptionRecord, IN BOOLEAN DebugException, IN BOOLEAN SecondChance)
NTKERNELAPI NTSTATUS PsGetContextThread (__in PETHREAD Thread, __inout PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
NTKERNELAPI HANDLE PsGetCurrentProcessId (VOID)
NTKERNELAPI ULONG PsGetCurrentProcessSessionId (VOID)
NTKERNELAPI PVOID PsGetCurrentProcessWin32Process (VOID)
NTKERNELAPI HANDLE PsGetCurrentThreadId (VOID)
NTKERNELAPI CCHAR PsGetCurrentThreadPreviousMode (VOID)
NTKERNELAPI PEPROCESS PsGetCurrentThreadProcess (VOID)
NTKERNELAPI HANDLE PsGetCurrentThreadProcessId (VOID)
NTKERNELAPI PVOID PsGetCurrentThreadStackBase (VOID)
NTKERNELAPI PVOID PsGetCurrentThreadStackLimit (VOID)
NTKERNELAPI PVOID PsGetCurrentThreadTeb (VOID)
NTKERNELAPI PVOID PsGetCurrentThreadWin32Thread (VOID)
NTKERNELAPI PVOID PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion (__out PHANDLE ProcessId)
NTKERNELAPI PERESOURCE PsGetJobLock (__in PEJOB Job)
NTKERNELAPI ULONG PsGetJobSessionId (__in PEJOB Job)
NTKERNELAPI ULONG PsGetJobUIRestrictionsClass (__in PEJOB Job)
PKPROCESS FORCEINLINE PsGetKernelProcess (IN PEPROCESS ProcessObject)
PKTHREAD FORCEINLINE PsGetKernelThread (IN PETHREAD ThreadObject)
PEJOB PsGetNextJob (IN PEJOB Job)
PEPROCESS PsGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
PEPROCESS PsGetNextProcess (IN PEPROCESS Process)
PETHREAD PsGetNextProcessThread (IN PEPROCESS Process, IN PETHREAD Thread)
NTKERNELAPI LONGLONG PsGetProcessCreateTimeQuadPart (__in PEPROCESS Process)
NTKERNELAPI PVOID PsGetProcessDebugPort (__in PEPROCESS Process)
NTKERNELAPI BOOLEAN PsGetProcessExitProcessCalled (__in PEPROCESS Process)
NTKERNELAPI NTSTATUS PsGetProcessExitStatus (__in PEPROCESS Process)
NTKERNELAPI LARGE_INTEGER PsGetProcessExitTime (VOID)
NTKERNELAPI HANDLE PsGetProcessId (__in PEPROCESS Process)
NTKERNELAPI UCHAR * PsGetProcessImageFileName (__in PEPROCESS Process)
NTKERNELAPI HANDLE PsGetProcessInheritedFromUniqueProcessId (__in PEPROCESS Process)
NTKERNELAPI PEJOB PsGetProcessJob (__in PEPROCESS Process)
NTKERNELAPI PPEB PsGetProcessPeb (__in PEPROCESS Process)
NTKERNELAPI UCHAR PsGetProcessPriorityClass (__in PEPROCESS Process)
NTKERNELAPI PVOID PsGetProcessSectionBaseAddress (__in PEPROCESS Process)
NTKERNELAPI PVOID PsGetProcessSecurityPort (__in PEPROCESS Process)
NTKERNELAPI ULONG PsGetProcessSessionId (__in PEPROCESS Process)
NTKERNELAPI ULONG PsGetProcessSessionIdEx (__in PEPROCESS Process)
NTKERNELAPI PVOID PsGetProcessWin32Process (__in PEPROCESS Process)
NTKERNELAPI HANDLE PsGetProcessWin32WindowStation (__in PEPROCESS Process)
NTKERNELAPI CCHAR PsGetThreadFreezeCount (__in PETHREAD Thread)
NTKERNELAPI BOOLEAN PsGetThreadHardErrorsAreDisabled (__in PETHREAD Thread)
NTKERNELAPI HANDLE PsGetThreadId (__in PETHREAD Thread)
NTKERNELAPI PEPROCESS PsGetThreadProcess (__in PETHREAD Thread)
NTKERNELAPI HANDLE PsGetThreadProcessId (__in PETHREAD Thread)
NTKERNELAPI ULONG PsGetThreadSessionId (__in PETHREAD Thread)
NTKERNELAPI PVOID PsGetThreadTeb (__in PETHREAD Thread)
NTKERNELAPI PVOID PsGetThreadWin32Thread (__in PETHREAD Thread)
NTKERNELAPI BOOLEAN PsGetVersion (__out_opt PULONG MajorVersion, __out_opt PULONG MinorVersion, __out_opt PULONG BuildNumber, __out_opt PUNICODE_STRING CSDVersion)
NTKERNELAPI NTSTATUS PsImpersonateClient (__inout PETHREAD Thread, __in PACCESS_TOKEN Token, __in BOOLEAN CopyOnOpen, __in BOOLEAN EffectiveOnly, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
VOID PsInitializeQuotaSystem (VOID)
BOOLEAN PsInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTKERNELAPI BOOLEAN PsIsProcessBeingDebugged (__in PEPROCESS Process)
NTKERNELAPI BOOLEAN PsIsSystemProcess (__in PEPROCESS Process)
NTKERNELAPI BOOLEAN PsIsSystemThread (__in PETHREAD Thread)
NTKERNELAPI BOOLEAN PsIsThreadImpersonating (__in PETHREAD Thread)
NTSTATUS PsLocateSystemDll (BOOLEAN ReplaceExisting)
NTKERNELAPI NTSTATUS PsLookupProcessByProcessId (__in HANDLE ProcessId, __deref_out PEPROCESS *Process)
NTKERNELAPI NTSTATUS PsLookupProcessThreadByCid (__in PCLIENT_ID Cid, __deref_opt_out PEPROCESS *Process, __deref_out PETHREAD *Thread)
NTKERNELAPI NTSTATUS PsLookupThreadByThreadId (__in HANDLE ThreadId, __deref_out PETHREAD *Thread)
NTSTATUS PsMapSystemDll (IN PEPROCESS Process, OUT PVOID *DllBase OPTIONAL, IN LOGICAL UseLargePages)
NTSTATUS PsOpenTokenOfJob (IN HANDLE JobHandle, OUT PACCESS_TOKEN *Token)
NTSTATUS PsOpenTokenOfProcess (IN HANDLE ProcessHandle, OUT PACCESS_TOKEN *Token)
NTSTATUS PsOpenTokenOfThread (IN HANDLE ThreadHandle, IN BOOLEAN OpenAsSelf, OUT PACCESS_TOKEN *Token, OUT PBOOLEAN CopyOnOpen, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
VOID PspContextFromKframes (OUT PKTRAP_FRAME TrapFrame, OUT PKEXCEPTION_FRAME ExceptionFrame, IN PCONTEXT Context)
VOID PspContextToKframes (OUT PKTRAP_FRAME TrapFrame, OUT PKEXCEPTION_FRAME ExceptionFrame, IN PCONTEXT Context)
VOID PsQuitNextJob (IN PEJOB Job)
VOID PsQuitNextJobProcess (IN PEPROCESS Process)
VOID PsQuitNextProcess (IN PEPROCESS Process)
VOID PsQuitNextProcessThread (IN PETHREAD Thread)
PACCESS_TOKEN PsReferenceEffectiveToken (IN PETHREAD Thread, OUT PTOKEN_TYPE TokenType, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
NTKERNELAPI PACCESS_TOKEN PsReferenceImpersonationToken (__inout PETHREAD Thread, __out PBOOLEAN CopyOnOpen, __out PBOOLEAN EffectiveOnly, __out PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
NTKERNELAPI PACCESS_TOKEN PsReferencePrimaryToken (__inout PEPROCESS Process)
NTSTATUS PsReferenceProcessFilePointer (IN PEPROCESS Process, OUT PVOID *pFilePointer)
NTKERNELAPI NTSTATUS PsRemoveCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
NTKERNELAPI NTSTATUS PsRemoveLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
VOID PsReportProcessMemoryLimitViolation (VOID)
NTKERNELAPI VOID PsRestoreImpersonation (__inout PETHREAD Thread, __in PSE_IMPERSONATION_STATE ImpersonationState)
NTSTATUS PsResumeProcess (IN PEPROCESS Process)
NTSTATUS PsResumeThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
NTKERNELAPI VOID PsReturnPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
NTKERNELAPI VOID PsReturnProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
NTKERNELAPI VOID PsReturnProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
VOID PsReturnProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
VOID PsReturnProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
VOID PsReturnSharedPoolQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN ULONG_PTR PagedAmount, IN ULONG_PTR NonPagedAmount)
NTKERNELAPI VOID PsRevertThreadToSelf (__inout PETHREAD Thread)
NTKERNELAPI VOID PsRevertToSelf (VOID)
NTKERNELAPI ULONG PsSetBBTNotifyRoutine (__in PBBT_NOTIFY_ROUTINE BBTNotifyRoutine)
NTKERNELAPI NTSTATUS PsSetContextThread (__in PETHREAD Thread, __in PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
NTKERNELAPI NTSTATUS PsSetCreateProcessNotifyRoutine (__in PCREATE_PROCESS_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
NTKERNELAPI NTSTATUS PsSetCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
NTKERNELAPI VOID PsSetJobUIRestrictionsClass (__out PEJOB Job, __in ULONG UIRestrictionsClass)
NTSTATUS PsSetLdtEntries (IN ULONG Selector0, IN ULONG Entry0Low, IN ULONG Entry0Hi, IN ULONG Selector1, IN ULONG Entry1Low, IN ULONG Entry1Hi)
NTKERNELAPI NTSTATUS PsSetLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
NTSTATUS PsSetProcessLdtInfo (IN PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength)
NTKERNELAPI VOID PsSetProcessPriorityByClass (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode)
NTKERNELAPI VOID PsSetProcessPriorityClass (__out PEPROCESS Process, __in UCHAR PriorityClass)
NTKERNELAPI NTSTATUS PsSetProcessSecurityPort (__out PEPROCESS Process, __in PVOID Port)
NTKERNELAPI NTSTATUS PsSetProcessWin32Process (__in PEPROCESS Process, __in PVOID Win32Process, __in PVOID PrevWin32Process)
NTKERNELAPI VOID PsSetProcessWindowStation (__out PEPROCESS Process, __in HANDLE Win32WindowStation)
NTKERNELAPI VOID PsSetThreadHardErrorsAreDisabled (__in PETHREAD Thread, __in BOOLEAN HardErrorsAreDisabled)
NTKERNELAPI VOID PsSetThreadWin32Thread (__inout PETHREAD Thread, __in PVOID Win32Thread, __in PVOID PrevWin32Thread)
LOGICAL PsShutdownSystem (VOID)
NTSTATUS PsSuspendProcess (IN PEPROCESS Process)
NTSTATUS PsSuspendThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
NTSTATUS PsTerminateProcess (IN PEPROCESS Process, IN NTSTATUS Status)
NTKERNELAPI NTSTATUS PsTerminateSystemThread (__in NTSTATUS ExitStatus)
VOID PsThreadHit (IN PETHREAD Thread)
BOOLEAN PsWaitForAllProcesses (VOID)
VOID PsWatchWorkingSet (IN NTSTATUS Status, IN PVOID PcValue, IN PVOID Va)
NTKERNELAPI NTSTATUS PsWrapApcWow64Thread (__inout PVOID *ApcContext, __inout PVOID *ApcRoutine)
Variables
LIST_ENTRY PsActiveProcessHead
LCID PsDefaultSystemLocaleId
LCID PsDefaultThreadLocaleId
LANGID PsDefaultUILanguageId
ULONG PsEmbeddedNTMask
PVOID PsHalImageBase
PEPROCESS PsIdleProcess
BOOLEAN PsImageNotifyEnabled
PEPROCESS PsInitialSystemProcess
LANGID PsInstallUILanguageId
LIST_ENTRY PsLoadedModuleList
ERESOURCE PsLoadedModuleResource
ALIGNED_SPINLOCK PsLoadedModuleSpinLock
const UNICODE_STRING PsNtDllPathName
PVOID PsNtosImageBase
ULONG PsPrioritySeparation
ULONG PsRawPrioritySeparation
SINGLE_LIST_ENTRY PsReaperListHead
WORK_QUEUE_ITEM PsReaperWorkItem
PVOID PsSystemDllBase
ULONG PsThreadHits [THREAD_HIT_SLOTS]
Macro Definition Documentation
#define _PsGetCurrentProcess () (CONTAINING_RECORD(((KeGetCurrentThread())->ApcState.Process),EPROCESS,Pcb))
Definition at line 1132 of file ps.h.
Referenced by PsGetCurrentProcess(), PsGetCurrentProcessSessionId(), and WmipReceiveNotifications().
#define _PsGetCurrentThread () ((PETHREAD)KeGetCurrentThread())
Definition at line 1135 of file ps.h.
Referenced by ExEnterCriticalRegionAndAcquireResourceExclusive(), ExEnterCriticalRegionAndAcquireResourceShared(), ExEnterCriticalRegionAndAcquireSharedWaitForExclusive(), PsGetCurrentThread(), PsGetCurrentThreadProcess(), PsGetCurrentThreadProcessId(), PsGetCurrentThreadTeb(), PsGetCurrentThreadWin32Thread(), PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion(), and PsSetProcessWin32Process().
#define EPROCESS_QUOTA_TRACK_MAX 10000
Definition at line 163 of file ps.h.
#define IMAGE_ADDRESSING_MODE_32BIT 3
Definition at line 1288 of file ps.h.
Referenced by DbgkCreateThread(), MiMapViewOfImageSection(), and MmLoadSystemImage().
#define IS_SYSTEM_THREAD (Thread) (((Thread)->CrossThreadFlags&PS_CROSS_THREAD_FLAGS_SYSTEM) != 0)
Definition at line 1130 of file ps.h.
Referenced by DbgkpPostFakeThreadMessages(), DbgkpSetProcessDebugObject(), ExpRaiseHardError(), IoIsSystemThread(), IoRaiseHardError(), MiZeroInParallel(), NtGetContextThread(), NtQueueApcThread(), NtReplyWaitReceivePortEx(), NtSetContextThread(), PsIsSystemThread(), PspExitThread(), PspTerminateThreadByPointer(), PspWaitForUsermodeExit(), and PsTerminateSystemThread().
#define MEMORY_PRIORITY_BACKGROUND 0
Definition at line 34 of file ps.h.
Referenced by MmSetMemoryPriorityProcess(), NtSetInformationProcess(), PsChangeQuantumTable(), and PspComputeQuantumAndPriority().
#define MEMORY_PRIORITY_FOREGROUND 2
Definition at line 36 of file ps.h.
Referenced by KiDeferredReadyThread(), MiAgeWorkingSet(), MiDetermineTrimAmount(), MiDoReplacement(), MiRearrangeWorkingSetExpansionList(), NtSetInformationProcess(), PspApplyJobLimitsToProcess(), and PspComputeQuantumAndPriority().
#define MEMORY_PRIORITY_WASFOREGROUND 1
Definition at line 35 of file ps.h.
#define MI_MAKE_PARENT (ParentNode, ExistingBalance) (PMMADDRESS_NODE)((ULONG_PTR)(ParentNode) | ((ExistingBalance) & 0x3))
Definition at line 111 of file ps.h.
Referenced by MiCloneProcessAddressSpace(), MiInitializeVadTableAvl(), MiPromoteNode(), MiRemoveNode(), and MiSecureVirtualMemory().
#define PS_CLEAR_BITS (Flags, Flag) RtlInterlockedClearBitsDiscardReturn (Flags, Flag)
Definition at line 219 of file ps.h.
Referenced by IoSetThreadHardErrorMode(), Ke386CallBios(), MiAttachAndLockWorkingSet(), MiDereferenceSession(), MiDereferenceSessionFinal(), MiSessionCreateInternal(), MmCleanProcessAddressSpace(), MmInitializeProcessAddressSpace(), MmInSwapProcess(), NtSetInformationProcess(), NtSetInformationThread(), PsImpersonateClient(), PspDeleteThreadSecurity(), PspInitializeThreadSecurity(), PsRestoreImpersonation(), PsRevertThreadToSelf(), PsRevertToSelf(), PsSetThreadHardErrorsAreDisabled(), and SepInitializationPhase0().
#define PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION 0x00000040UL
Definition at line 712 of file ps.h.
Referenced by NtQueryInformationThread(), NtSetInformationThread(), PspExitThread(), and PspTerminateThreadByPointer().
#define PS_CROSS_THREAD_FLAGS_DEADTHREAD 0x00000002UL
Definition at line 682 of file ps.h.
Referenced by DbgkExitProcess(), DbgkExitThread(), PspCreateThread(), PspExitThread(), PspSystemThreadStartup(), and PspUserThreadStartup().
#define PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED 0x00000020UL
Definition at line 706 of file ps.h.
Referenced by ExpRaiseHardError(), IoRaiseHardError(), IoRaiseInformationalHardError(), IoSetThreadHardErrorMode(), PsGetThreadHardErrorsAreDisabled(), and PsSetThreadHardErrorsAreDisabled().
#define PS_CROSS_THREAD_FLAGS_HIDEFROMDBG 0x00000004UL
Definition at line 688 of file ps.h.
Referenced by DbgkExitProcess(), DbgkExitThread(), DbgkForwardException(), DbgkMapViewOfSection(), DbgkUnMapViewOfSection(), NtSetInformationThread(), and PspUserThreadStartup().
#define PS_CROSS_THREAD_FLAGS_IMPERSONATING 0x00000008UL
Definition at line 694 of file ps.h.
Referenced by PsDisableImpersonation(), PsImpersonateClient(), PspDeleteThreadSecurity(), PspInitializeThreadSecurity(), PsRestoreImpersonation(), PsRevertThreadToSelf(), PsRevertToSelf(), and SepInitializationPhase0().
#define PS_CROSS_THREAD_FLAGS_SKIP_CREATION_MSG 0x00000080UL
Definition at line 717 of file ps.h.
Referenced by DbgkpQueueMessage(), and DbgkpSetProcessDebugObject().
#define PS_CROSS_THREAD_FLAGS_SKIP_TERMINATION_MSG 0x00000100UL
Definition at line 722 of file ps.h.
Referenced by DbgkpQueueMessage(), and DbgkpSetProcessDebugObject().
#define PS_CROSS_THREAD_FLAGS_SYSTEM 0x00000010UL
Definition at line 700 of file ps.h.
Referenced by PspCreateThread().
#define PS_CROSS_THREAD_FLAGS_TERMINATED 0x00000001UL
Definition at line 676 of file ps.h.
Referenced by PsIsThreadTerminating(), PspCreateThread(), PspSystemThreadStartup(), PspTerminateThreadByPointer(), and PsSuspendThread().
#define PS_EMBEDDED_NO_USERMODE 1
Definition at line 1059 of file ps.h.
Referenced by PsLocateSystemDll().
#define PS_GET_THREAD_CREATE_TIME (Thread) ((Thread)->CreateTime.QuadPart)
Definition at line 534 of file ps.h.
Referenced by ExpCopyThreadInfo(), NtQueryInformationThread(), and PspExitThread().
#define PS_GET_WOW64_PROCESS (Process) ((Process), ((PWOW64_PROCESS)NULL))
Definition at line 210 of file ps.h.
Referenced by NtQueryInformationProcess(), PsGetCurrentProcessWow64Process(), and PsGetProcessWow64Process().
#define PS_IS_THREAD_IMPERSONATING (Thread) (((Thread)->CrossThreadFlags&PS_CROSS_THREAD_FLAGS_IMPERSONATING) != 0)
Definition at line 543 of file ps.h.
Referenced by ExpWorkerThread(), ObpReferenceDeviceMap(), PsDisableImpersonation(), PsImpersonateClient(), PsIsThreadImpersonating(), PspDeleteThreadSecurity(), PspWriteTebImpersonationInfo(), PsReferenceEffectiveToken(), PsReferenceImpersonationToken(), PsRestoreImpersonation(), PsRevertThreadToSelf(), PsRevertToSelf(), and RtlFormatCurrentUserKeyPath().
#define PS_JOB_FLAGS_CLOSE_DONE 0x1UL
Definition at line 1022 of file ps.h.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), and PspJobClose().
#define PS_JOB_STATUS_ACCOUNTING_FOLDED 0x00000002UL
Definition at line 403 of file ps.h.
Referenced by NtQueryInformationJobObject(), NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), PspAddProcessToJob(), and PspFoldProcessAccountingIntoJob().
#define PS_JOB_STATUS_EXIT_PROCESS_REPORTED 0x00000008UL
Definition at line 405 of file ps.h.
Referenced by PspExitProcess().
#define PS_JOB_STATUS_LAST_REPORT_MEMORY 0x00000020UL
Definition at line 407 of file ps.h.
Referenced by NtSetInformationJobObject(), PsChangeJobMemoryUsage(), PsEnforceExecutionTimeLimits(), PspAddProcessToJob(), PspExitProcess(), PspFoldProcessAccountingIntoJob(), and PsReportProcessMemoryLimitViolation().
#define PS_JOB_STATUS_NEW_PROCESS_REPORTED 0x00000004UL
Definition at line 404 of file ps.h.
Referenced by NtSetInformationJobObject(), PsChangeJobMemoryUsage(), PspAddProcessToJob(), PspCreateThread(), and PsReportProcessMemoryLimitViolation().
#define PS_JOB_STATUS_NOT_REALLY_ACTIVE 0x00000001UL
Definition at line 402 of file ps.h.
Referenced by NtQueryInformationJobObject(), NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), PspAddProcessToJob(), PspApplyJobLimitsToProcessSet(), PspCreateThread(), PspExitProcess(), PspExitProcessFromJob(), PspRemoveProcessFromJob(), and PspTerminateAllProcessesInJob().
#define PS_JOB_STATUS_REPORT_COMMIT_CHANGES 0x00000010UL
Definition at line 406 of file ps.h.
Referenced by MiInsertVadCharges(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MiSetPageModified(), MiSetProtectionOnSection(), MmAssignProcessToJob(), MmCleanProcessAddressSpace(), NtAllocateVirtualMemory(), NtFreeVirtualMemory(), and PsChangeJobMemoryUsage().
#define PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES 0x00000040UL
Definition at line 408 of file ps.h.
Referenced by MiAllocateLargePages(), MiCleanPhysicalProcessPages(), MiReleasePhysicalCharges(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
#define PS_PROCESS_FLAGS_ADDRESS_SPACE1 0x00000400UL
Definition at line 428 of file ps.h.
Referenced by MmCleanProcessAddressSpace(), MmCreateProcessAddressSpace(), and MmInitializeProcessAddressSpace().
#define PS_PROCESS_FLAGS_ADDRESS_SPACE2 0x00000800UL
Definition at line 429 of file ps.h.
Referenced by MmInitializeProcessAddressSpace().
#define PS_PROCESS_FLAGS_BREAK_ON_TERMINATION 0x00002000UL
Definition at line 431 of file ps.h.
Referenced by NtQueryInformationProcess(), NtSetInformationProcess(), NtTerminateProcess(), PspExitThread(), and PspTerminateProcess().
#define PS_PROCESS_FLAGS_CREATE_FAILED 0x04000000UL
Definition at line 444 of file ps.h.
#define PS_PROCESS_FLAGS_CREATE_REPORTED 0x00000001UL
Definition at line 418 of file ps.h.
Referenced by DbgkCreateThread(), DbgkpSendApiMessage(), DbgkpSendApiMessageLpc(), and DbgkpSetProcessDebugObject().
#define PS_PROCESS_FLAGS_CREATING_SESSION 0x00004000UL
Definition at line 432 of file ps.h.
Referenced by MiSessionCreateInternal().
#define PS_PROCESS_FLAGS_DEFAULT_IO_PRIORITY 0x38000000UL
Definition at line 446 of file ps.h.
#define PS_PROCESS_FLAGS_EXECUTE_SPARE1 0x40000000UL
Definition at line 450 of file ps.h.
#define PS_PROCESS_FLAGS_EXECUTE_SPARE2 0x80000000UL
Definition at line 451 of file ps.h.
#define PS_PROCESS_FLAGS_FORK_FAILED 0x00000100UL
Definition at line 426 of file ps.h.
Referenced by MiCloneProcessAddressSpace(), and MiDecrementCloneBlockReference().
#define PS_PROCESS_FLAGS_HAS_ADDRESS_SPACE 0x00040000UL
Definition at line 436 of file ps.h.
Referenced by PspCreateProcess(), and PspProcessDelete().
#define PS_PROCESS_FLAGS_IMAGE_NOTIFY_DONE 0x00400000UL
Definition at line 440 of file ps.h.
Referenced by DbgkCreateThread().
#define PS_PROCESS_FLAGS_IN_SESSION 0x00010000UL
Definition at line 434 of file ps.h.
Referenced by ExpWin32SessionCallout(), MiAttachAndLockWorkingSet(), MiAttachSession(), MiDereferenceSession(), MiDereferenceSessionFinal(), MiDetachSession(), MiSessionAddProcess(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), MiSessionRemoveProcess(), MiSessionWideReserveImageAddress(), MiTrimAllSystemPageableMemory(), MmCommitSessionMappedView(), MmInSwapProcess(), MmLoadSystemImage(), MmMapViewInSessionSpace(), MmOutSwapProcess(), MmSessionCreate(), MmSessionDelete(), MmSessionSetUnloadAddress(), MmUnmapViewInSessionSpace(), and PspWin32SessionCallout().
#define PS_PROCESS_FLAGS_LAUNCH_PREFETCHED 0x00080000UL
Definition at line 437 of file ps.h.
Referenced by PspUserThreadStartup().
#define PS_PROCESS_FLAGS_NO_DEBUG_INHERIT 0x00000002UL
Definition at line 419 of file ps.h.
Referenced by DbgkCopyProcessDebugPort(), DbgkpSetProcessDebugObject(), NtQueryInformationProcess(), NtSetInformationProcess(), and PspCreateProcess().
#define PS_PROCESS_FLAGS_OUTSWAP_ENABLED 0x00000040UL
Definition at line 424 of file ps.h.
Referenced by MiAttachAndLockWorkingSet(), MiDetermineTrimAmount(), MmInSwapProcess(), and MmOutSwapProcess().
#define PS_PROCESS_FLAGS_OUTSWAPPED 0x00000080UL
Definition at line 425 of file ps.h.
Referenced by MiAttachAndLockWorkingSet(), MiMapWithLargePages(), MiUnmapLargePages(), MmInSwapProcess(), and MmOutSwapProcess().
#define PS_PROCESS_FLAGS_OVERRIDE_ADDRESS_SPACE 0x00020000UL
Definition at line 435 of file ps.h.
Referenced by MmInitializeProcessAddressSpace(), and PspCreateProcess().
#define PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED 0x00800000UL
Definition at line 441 of file ps.h.
Referenced by MiMapWithLargePages(), MiUnmapLargePages(), MmInitializeProcessAddressSpace(), and MmInSwapProcess().
#define PS_PROCESS_FLAGS_PRIORITY_SHIFT 27
Definition at line 448 of file ps.h.
#define PS_PROCESS_FLAGS_PROCESS_DELETE 0x00000008UL
Definition at line 421 of file ps.h.
Referenced by DbgkpSuspendProcess(), NtTerminateProcess(), PspCreateThread(), PspExitThread(), PspTerminateProcess(), and PsSetProcessWin32Process().
#define PS_PROCESS_FLAGS_PROCESS_EXITING 0x00000004UL
Definition at line 420 of file ps.h.
Referenced by ExpGetProcessInformation(), PsGetProcessExitProcessCalled(), PspExitProcess(), PspFreezeProcessWorker(), PsShutdownSystem(), and PsWaitForAllProcesses().
#define PS_PROCESS_FLAGS_SET_TIMER_RESOLUTION 0x00001000UL
Definition at line 430 of file ps.h.
Referenced by PspExitProcess().
#define PS_PROCESS_FLAGS_SMAP_ALLOWED 0x02000000UL
Definition at line 443 of file ps.h.
#define PS_PROCESS_FLAGS_USING_WRITE_WATCH 0x00008000UL
Definition at line 433 of file ps.h.
Referenced by MiCaptureWriteWatchDirtyBit(), MiEliminateWorkingSetEntry(), MiFlushTbAndCapture(), MiFreeWsleList(), MiTrimPte(), NtAllocateVirtualMemory(), NtGetWriteWatch(), and NtResetWriteWatch().
#define PS_PROCESS_FLAGS_VDM_ALLOWED 0x01000000UL
Definition at line 442 of file ps.h.
Referenced by Ke386CallBios(), NtQueryInformationProcess(), and NtSetInformationProcess().
#define PS_PROCESS_FLAGS_VM_DELETED 0x00000020UL
Definition at line 423 of file ps.h.
Referenced by MiAttachAndLockWorkingSet(), MiCloneProcessAddressSpace(), MiEmptyWorkingSet(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiMapLockedPagesInUserSpace(), MiProtectVirtualMemory(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), MiTrimAllSystemPageableMemory(), MiUnmapViewOfSection(), MiUnsecureVirtualMemory(), MmAdjustWorkingSetSizeEx(), MmCleanProcessAddressSpace(), MmFlushVirtualMemory(), MmMapUserAddressesToPage(), MmMapViewOfSection(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtLockVirtualMemory(), NtQueryVirtualMemory(), and NtUnlockVirtualMemory().
#define PS_PROCESS_FLAGS_VM_TOP_DOWN 0x00200000UL
Definition at line 439 of file ps.h.
Referenced by MmInitializeProcessAddressSpace().
#define PS_PROCESS_FLAGS_WOW64_4GB_VA_SPACE 0x00000200UL
Definition at line 427 of file ps.h.
Referenced by MmInitializeProcessAddressSpace(), and NtQueryVirtualMemory().
#define PS_PROCESS_FLAGS_WOW64_SPLIT_PAGES 0x00000010UL
Definition at line 422 of file ps.h.
#define PS_PROCESS_INJECT_INPAGE_ERRORS 0x00100000UL
Definition at line 438 of file ps.h.
Referenced by MmAccessFault().
#define PS_SAME_THREAD_FLAGS_OWNS_A_WORKING_SET 0x000001F8UL
Definition at line 796 of file ps.h.
Referenced by MmAccessFault().
#define PS_SET_BITS (Flags, Flag) RtlInterlockedSetBitsDiscardReturn (Flags, Flag)
Definition at line 213 of file ps.h.
Referenced by DbgkpSendApiMessage(), DbgkpSendApiMessageLpc(), DbgkpSetProcessDebugObject(), IoSetThreadHardErrorMode(), Ke386CallBios(), MiCloneProcessAddressSpace(), MiMapWithLargePages(), MiSessionAddProcess(), MiUnmapLargePages(), MmAssignProcessToJob(), MmCleanProcessAddressSpace(), MmCreateProcessAddressSpace(), MmInitializeProcessAddressSpace(), MmOutSwapProcess(), MmSessionCreate(), NtAllocateVirtualMemory(), NtSetInformationProcess(), NtSetInformationThread(), NtTerminateProcess(), PsChangeJobMemoryUsage(), PsImpersonateClient(), PspAddProcessToJob(), PspCreateProcess(), PspCreateThread(), PspExitProcess(), PspExitProcessFromJob(), PspExitThread(), PspJobClose(), PspRemoveProcessFromJob(), PspTerminateAllProcessesInJob(), PspTerminateProcess(), PspTerminateThreadByPointer(), PsReportProcessMemoryLimitViolation(), PsRestoreImpersonation(), and PsSetThreadHardErrorsAreDisabled().
#define PS_SET_CLEAR_BITS (Flags, sFlag, cFlag) RtlInterlockedSetClearBits (Flags, sFlag, cFlag)
Definition at line 225 of file ps.h.
Referenced by NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), PspAddProcessToJob(), PspExitProcess(), and PspFoldProcessAccountingIntoJob().
#define PS_SET_THREAD_CREATE_TIME (Thread, InputCreateTime) ((Thread)->CreateTime.QuadPart = (InputCreateTime.QuadPart))
Definition at line 536 of file ps.h.
Referenced by PspCreateThread().
#define PS_TEST_ALL_BITS_SET (Flags, Bits) ((Flags&(Bits)) == (Bits))
Definition at line 228 of file ps.h.
Referenced by PspAddProcessToJob(), and PspSetQuotaLimits().
#define PS_TEST_CLEAR_BITS (Flags, Flag) RtlInterlockedClearBits (Flags, Flag)
Definition at line 222 of file ps.h.
Referenced by PsDisableImpersonation().
#define PS_TEST_SET_BITS (Flags, Flag) RtlInterlockedSetBits (Flags, Flag)
Definition at line 216 of file ps.h.
Referenced by DbgkCreateThread(), PspTerminateThreadByPointer(), and PspUserThreadStartup().
#define PS_WS_TRIM_BACKGROUND_ONLY_APP 2
Definition at line 195 of file ps.h.
#define PS_WS_TRIM_FROM_EXE_HEADER 1
Definition at line 194 of file ps.h.
#define PsDereferenceImpersonationToken (T)
Value:
{if (ARGUMENT_PRESENT((T))) {                                     \
                (ObDereferenceObject((T)));                                   \
             } else {                                                         \
                ;                                                             \
             }                                                                \
            }
Definition at line 1351 of file ps.h.
Referenced by ObpReferenceDeviceMap(), SepOpenTokenOfThread(), and SeReleaseSubjectContext().
#define PsDereferencePrimaryToken (T) (ObDereferenceObject((T)))
Definition at line 1349 of file ps.h.
Referenced by NtImpersonateAnonymousToken(), ObpSetCurrentProcessDeviceMap(), and SeAuditProcessExit().
#define PsDereferencePrimaryTokenEx (P, T) (ObFastDereferenceObject (&P->Token,(T)))
Definition at line 1347 of file ps.h.
Referenced by NtAssignProcessToJobObject(), NtImpersonateAnonymousToken(), NtOpenThreadTokenEx(), NtSecureConnectPort(), PsImpersonateClient(), PspCreateProcess(), PspCreateThread(), PspExitThread(), PspInitializeProcessSecurity(), PspSetPrimaryToken(), SeIsChildToken(), SeIsChildTokenByPointer(), SeIsSiblingToken(), SeIsSiblingTokenByPointer(), SeReleaseSubjectContext(), and WmiTraceProcess().
#define PsGetCurrentProcess () _PsGetCurrentProcess()
Definition at line 1161 of file ps.h.
#define PsGetCurrentProcessByThread (xCurrentThread) (ASSERT((xCurrentThread) == PsGetCurrentThread ()),CONTAINING_RECORD(((xCurrentThread)->Tcb.ApcState.Process),EPROCESS,Pcb))
Definition at line 1133 of file ps.h.
Referenced by BuildQueryDirectoryIrp(), DbgkCreateThread(), MiAllocateLargePages(), MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MiCloneProcessAddressSpace(), MiGetPageProtection(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiMapLockedPagesInUserSpace(), MiProtectAweRegion(), MiSecureVirtualMemory(), MiSetPageModified(), MiTrimAllSystemPageableMemory(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MmAccessFault(), MmAdjustWorkingSetSizeEx(), MmFlushVirtualMemory(), MmMapUserAddressesToPage(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmQueryWorkingSetInformation(), MmSessionCreate(), MmSessionDelete(), MmSetPhysicalPagesLimit(), MmUnlockPages(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtCreateJobObject(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtIsProcessInJob(), NtLoadDriver(), NtLockFile(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtMapViewOfSection(), NtProtectVirtualMemory(), NtQueryInformationFile(), NtQueryInformationJobObject(), NtQueryQuotaInformationFile(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtReadVirtualMemory(), NtReleaseKeyedEvent(), NtResetWriteWatch(), NtSetInformationFile(), NtSetInformationThread(), NtSetVolumeInformationFile(), NtTerminateProcess(), NtTerminateThread(), NtUnlockFile(), NtWaitForKeyedEvent(), NtWriteVirtualMemory(), ObClearProcessHandleTable(), ObpCloseHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PsChangeJobMemoryUsage(), PsConvertToGuiThread(), PspCreateProcess(), PspCreateThread(), PspExitThread(), PspUserThreadStartup(), PspWriteTebImpersonationInfo(), and PsReportProcessMemoryLimitViolation().
#define PsGetCurrentProcessImageFileName () PsGetProcessImageFileName(PsGetCurrentProcess())
Definition at line 1917 of file ps.h.
Referenced by NtCreateKey().
#define PsGetCurrentProcessWin32WindowStation () PsGetProcessWin32WindowStation(PsGetCurrentProcess())
Definition at line 1969 of file ps.h.
#define PsGetCurrentThread () _PsGetCurrentThread()
Definition at line 1163 of file ps.h.
#define PsGetProcessPcb (Process) ((PKPROCESS)(Process))
Definition at line 1949 of file ps.h.
#define PsGetThreadTcb (Thread) ((PKTHREAD)(Thread))
Definition at line 2047 of file ps.h.
#define PsIsThreadTerminating (T) (((T)->CrossThreadFlags&PS_CROSS_THREAD_FLAGS_TERMINATED) != 0)
Definition at line 1418 of file ps.h.
#define PsProcessAuditId (Process) ((Process)->UniqueProcessId)
Definition at line 1360 of file ps.h.
Referenced by NtOpenObjectAuditAlarm(), SeAuditHandleDuplication(), SeAuditLPCInvalidUse(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCaptureSubjectContextEx(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), and SepAuditAssignPrimaryToken().
#define SANITIZE_PARENT_NODE (Parent) ((PMMADDRESS_NODE)(((ULONG_PTR)(Parent)) & ~0x3))
Definition at line 105 of file ps.h.
Referenced by MiGetNextNode(), MiGetPreviousNode(), MiInsertNode(), MiPromoteNode(), MiRealPredecessor(), MiRealSuccessor(), MiRebalanceNode(), MiRemoveNode(), and MiSecureVirtualMemory().
#define THREAD_HIT_SLOTS 750
Definition at line 1074 of file ps.h.
#define THREAD_TO_PROCESS (Thread) ((Thread)->ThreadsProcess)
Definition at line 1129 of file ps.h.
Referenced by FsRtlNotifyFilterChangeDirectory(), IoGetRequestorProcess(), IoGetRequestorSessionId(), IopRaiseHardError(), IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IopUpdateReadOperationCount(), IopUpdateReadTransferCount(), IopUpdateWriteOperationCount(), IopUpdateWriteTransferCount(), IoRaiseHardError(), IoThreadToProcess(), LpcpCopyRequestData(), LpcpRequestWaitReplyPort(), NtAcceptConnectPort(), NtGetNextThread(), NtOpenThreadTokenEx(), NtQueryInformationThread(), NtReleaseKeyedEvent(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSetInformationThread(), NtWaitForKeyedEvent(), PsGetCurrentThreadProcess(), PsGetThreadProcess(), PsGetThreadSessionId(), PsImpersonateClient(), PsLookupProcessThreadByCid(), PspCreateThread(), PspExitThread(), PspQueryDescriptorThread(), PspTerminateThreadByPointer(), PspThreadDelete(), PspWriteTebImpersonationInfo(), PsReferenceEffectiveToken(), and PsRevertToSelf().
Typedef Documentation
typedef struct _EJOB EJOB
typedef struct _EPROCESS EPROCESS
typedef struct _EPROCESS_QUOTA_BLOCK EPROCESS_QUOTA_BLOCK
typedef struct _EPROCESS_QUOTA_ENTRY EPROCESS_QUOTA_ENTRY
typedef struct _EPROCESS_QUOTA_TRACK EPROCESS_QUOTA_TRACK
typedef struct _ETHREAD ETHREAD
typedef struct _IMAGE_INFO IMAGE_INFO
typedef struct _INITIAL_PEB INITIAL_PEB
typedef struct _MM_AVL_TABLE MM_AVL_TABLE
typedef struct _MMADDRESS_NODE MMADDRESS_NODE
typedef struct _MMSUPPORT MMSUPPORT
typedef struct _MMSUPPORT_FLAGS MMSUPPORT_FLAGS
typedef struct _PAGEFAULT_HISTORY PAGEFAULT_HISTORY
typedef VOID(* PBBT_NOTIFY_ROUTINE) (PKTHREAD Thread)
Definition at line 1221 of file ps.h.
typedef VOID(* PCREATE_PROCESS_NOTIFY_ROUTINE) (IN HANDLE ParentId, IN HANDLE ProcessId, IN BOOLEAN Create)
Definition at line 1235 of file ps.h.
typedef VOID(* PCREATE_THREAD_NOTIFY_ROUTINE) (IN HANDLE ProcessId, IN HANDLE ThreadId, IN BOOLEAN Create)
Definition at line 1250 of file ps.h.
typedef EJOB* PEJOB
Definition at line 1026 of file ps.h.
typedef struct _EPROCESS * PEPROCESS
typedef struct _EPROCESS_QUOTA_BLOCK * PEPROCESS_QUOTA_BLOCK
typedef struct _EPROCESS_QUOTA_ENTRY * PEPROCESS_QUOTA_ENTRY
typedef struct _EPROCESS_QUOTA_TRACK * PEPROCESS_QUOTA_TRACK
typedef struct _ETHREAD * PETHREAD
typedef struct _IMAGE_INFO * PIMAGE_INFO
typedef struct _INITIAL_PEB * PINITIAL_PEB
typedef struct _WIN32_CALLOUTS_FPNS * PKWIN32_CALLOUTS_FPNS
typedef NTSTATUS(* PKWIN32_JOB_CALLOUT) (IN PKWIN32_JOBCALLOUT_PARAMETERS Parm)
Definition at line 1683 of file ps.h.
typedef struct _WIN32_JOBCALLOUT_PARAMETERS * PKWIN32_JOBCALLOUT_PARAMETERS
typedef NTSTATUS(* PKWIN32_OBJECT_CALLOUT) (IN PVOID Parm)
Definition at line 1753 of file ps.h.
typedef NTSTATUS(* PKWIN32_POWEREVENT_CALLOUT) (IN PKWIN32_POWEREVENT_PARAMETERS Parm)
Definition at line 1741 of file ps.h.
typedef struct _WIN32_POWEREVENT_PARAMETERS * PKWIN32_POWEREVENT_PARAMETERS
typedef NTSTATUS(* PKWIN32_POWERSTATE_CALLOUT) (IN PKWIN32_POWERSTATE_PARAMETERS Parm)
Definition at line 1747 of file ps.h.
typedef struct _WIN32_POWERSTATE_PARAMETERS * PKWIN32_POWERSTATE_PARAMETERS
typedef NTSTATUS(* PKWIN32_PROCESS_CALLOUT) (IN PEPROCESS Process, IN BOOLEAN Initialize)
Definition at line 1664 of file ps.h.
typedef NTSTATUS(* PKWIN32_THREAD_CALLOUT) (IN PETHREAD Thread, IN PSW32THREADCALLOUTTYPE CalloutType)
Definition at line 1694 of file ps.h.
typedef VOID(* PLOAD_IMAGE_NOTIFY_ROUTINE) (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
Definition at line 1292 of file ps.h.
typedef struct _MM_AVL_TABLE * PMM_AVL_TABLE
typedef struct _MMADDRESS_NODE * PMMADDRESS_NODE
typedef struct _MMSUPPORT * PMMSUPPORT
typedef enum _POWERSTATETASK POWERSTATETASK
typedef struct _PAGEFAULT_HISTORY * PPAGEFAULT_HISTORY
typedef struct _PS_IMPERSONATION_INFORMATION * PPS_IMPERSONATION_INFORMATION
typedef struct _PS_JOB_TOKEN_FILTER * PPS_JOB_TOKEN_FILTER
typedef enum _PS_QUOTA_TYPE * PPS_QUOTA_TYPE
typedef NTSTATUS(* PROCESS_ENUM_ROUTINE) (IN PEPROCESS Process, IN PVOID Context)
Definition at line 2162 of file ps.h.
typedef struct _PS_IMPERSONATION_INFORMATION PS_IMPERSONATION_INFORMATION
typedef struct _PS_JOB_TOKEN_FILTER PS_JOB_TOKEN_FILTER
typedef enum _PS_QUOTA_TYPE PS_QUOTA_TYPE
typedef struct _SE_AUDIT_PROCESS_CREATION_INFO * PSE_AUDIT_PROCESS_CREATION_INFO
typedef enum _PSPOWEREVENTTYPE PSPOWEREVENTTYPE
typedef enum _PSPROCESSPRIORITYMODE PSPROCESSPRIORITYMODE
typedef enum _PSW32JOBCALLOUTTYPE PSW32JOBCALLOUTTYPE
typedef enum _PSW32THREADCALLOUTTYPE PSW32THREADCALLOUTTYPE
typedef struct _TERMINATION_PORT * PTERMINATION_PORT
typedef struct _WOW64_PROCESS * PWOW64_PROCESS
typedef ULONG * PWSLE_NUMBER
Definition at line 64 of file ps.h.
typedef struct _SE_AUDIT_PROCESS_CREATION_INFO SE_AUDIT_PROCESS_CREATION_INFO
typedef struct _TERMINATION_PORT TERMINATION_PORT
typedef NTSTATUS(* THREAD_ENUM_ROUTINE) (IN PEPROCESS Process, IN PETHREAD Thread, IN PVOID Context)
Definition at line 2169 of file ps.h.
typedef struct _WIN32_CALLOUTS_FPNS WIN32_CALLOUTS_FPNS
typedef struct _WIN32_JOBCALLOUT_PARAMETERS WIN32_JOBCALLOUT_PARAMETERS
typedef struct _WIN32_POWEREVENT_PARAMETERS WIN32_POWEREVENT_PARAMETERS
typedef struct _WIN32_POWERSTATE_PARAMETERS WIN32_POWERSTATE_PARAMETERS
typedef struct _WOW64_PROCESS WOW64_PROCESS
typedef ULONG WSLE_NUMBER
Definition at line 64 of file ps.h.
Enumeration Type Documentation
enum _POWERSTATETASK
Enumerator
PowerState_BlockSessionSwitch
PowerState_Init
PowerState_QueryApps
PowerState_QueryFailed
PowerState_SuspendApps
PowerState_ShowUI
PowerState_NotifyWL
PowerState_ResumeApps
PowerState_UnBlockSessionSwitch
Definition at line 1717 of file ps.h.
enum _PS_QUOTA_TYPE
Enumerator
PsNonPagedPool
PsPagedPool
PsPageFile
PsQuotaTypes
Definition at line 147 of file ps.h.
enum _PSPOWEREVENTTYPE
Enumerator
PsW32FullWake
PsW32EventCode
PsW32PowerPolicyChanged
PsW32SystemPowerState
PsW32SystemTime
PsW32DisplayState
PsW32CapabilitiesChanged
PsW32SetStateFailed
PsW32GdiOff
PsW32GdiOn
Definition at line 1699 of file ps.h.
enum _PSPROCESSPRIORITYMODE
Enumerator
PsProcessPriorityBackground
PsProcessPriorityForeground
PsProcessPrioritySpinning
Definition at line 1782 of file ps.h.
enum _PSW32JOBCALLOUTTYPE
Enumerator
PsW32JobCalloutSetInformation
PsW32JobCalloutAddProcess
PsW32JobCalloutTerminate
Definition at line 1669 of file ps.h.
enum _PSW32THREADCALLOUTTYPE
Enumerator
PsW32ThreadCalloutInitialize
PsW32ThreadCalloutExit
Definition at line 1687 of file ps.h.
Function Documentation
C_ASSERT (FIELD_OFFSET(EPROCESS, Pcb) = =0)
C_ASSERT (FIELD_OFFSET(ETHREAD, Tcb) = =0)
NTKERNELAPI NTSTATUS PsAssignImpersonationToken (__in PETHREAD Thread, __in HANDLE Token)
Definition at line 1791 of file security.c.
References ARGUMENT_PRESENT, FALSE, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PsImpersonateClient(), PsRevertThreadToSelf(), SeTokenImpersonationLevel(), SeTokenObjectType, SeTokenType(), Status, STATUS_BAD_TOKEN_TYPE, STATUS_SUCCESS, _ETHREAD::Tcb, TOKEN_IMPERSONATE, and TokenImpersonation.
Referenced by NtSetInformationThread().
VOID PsCallImageNotifyRoutines (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
Definition at line 2393 of file create.c.
References ExDereferenceCallBackBlock(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), NULL, PAGED_CODE, PsImageNotifyEnabled, PSP_MAX_LOAD_IMAGE_NOTIFY, and PspLoadImageNotifyRoutine.
Referenced by DbgkCreateThread(), MiMapViewOfImageSection(), and MmLoadSystemImage().
BOOLEAN PsChangeJobMemoryUsage (IN ULONG Flags, IN SSIZE_T Amount)
Definition at line 2863 of file psjob.c.
References _EPROCESS::CommitCharge, _EJOB::CompletionKey, _EJOB::CompletionPort, _EJOB::CurrentJobMemoryUsed, FALSE, IoSetIoCompletion(), _EPROCESS::Job, JOB_OBJECT_LIMIT_JOB_MEMORY, JOB_OBJECT_MSG_JOB_MEMORY_LIMIT, _EJOB::JobMemoryLimit, _EPROCESS::JobStatus, _EJOB::LimitFlags, _EJOB::PeakJobMemoryUsed, _EJOB::PeakProcessMemoryUsed, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspLockJobLimitsShared(), PspUnlockJobLimitsShared(), STATUS_SUCCESS, TRUE, and _EPROCESS::UniqueProcessId.
Referenced by MiAllocateLargePages(), MiCleanPhysicalProcessPages(), MiInsertVadCharges(), MiReleasePhysicalCharges(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MiSetPageModified(), MiSetProtectionOnSection(), MmAssignProcessToJob(), MmCleanProcessAddressSpace(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFreeUserPhysicalPages(), and NtFreeVirtualMemory().
VOID PsChangeQuantumTable (BOOLEAN ModifyActiveProcesses, ULONG PrioritySeparation)
Definition at line 937 of file psinit.c.
References CONTAINING_RECORD, FALSE, _MMSUPPORT::Flags, _LIST_ENTRY::Flink, _EPROCESS::Job, KeSetQuantumProcess(), MEMORY_PRIORITY_BACKGROUND, _MMSUPPORT_FLAGS::MemoryPriority, MmIsThisAnNtAsSystem(), NULL, _EPROCESS::Pcb, _EPROCESS::PriorityClass, PROCESS_PRIORITY_CLASS_IDLE, PROCESS_PRIORITY_SEPARATION_MASK, PROCESS_PRIORITY_SEPARATION_MAX, PROCESS_QUANTUM_FIXED_VALUE, PROCESS_QUANTUM_LONG_DEF, PROCESS_QUANTUM_LONG_MASK, PROCESS_QUANTUM_LONG_VALUE, PROCESS_QUANTUM_SHORT_VALUE, PROCESS_QUANTUM_VARIABLE_DEF, PROCESS_QUANTUM_VARIABLE_MASK, PROCESS_QUANTUM_VARIABLE_VALUE, PsGetCurrentThread(), PspFixedQuantums, PspLockProcessList(), PsPrioritySeparation, PspUnlockProcessList(), PspVariableQuantums, RtlCopyMemory, _EJOB::SchedulingClass, THREAD_QUANTUM, TRUE, and _EPROCESS::Vm.
Referenced by NtSetSystemInformation(), and PspInitPhase0().
NTKERNELAPI VOID PsChargePoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
Definition at line 857 of file psquota.c.
References ExRaiseStatus(), NT_SUCCESS, PsChargeProcessPoolQuota(), and Status.
Referenced by FsRtlCancelNotify(), and FsRtlNotifyFilterReportChange().
NTKERNELAPI NTSTATUS PsChargeProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1109 of file psquota.c.
References PsInitialSystemProcess, PsNonPagedPool, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by ExEnableHandleTracing(), MiCloneProcessAddressSpace(), MiInsertVadCharges(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtSetInformationProcess(), PspSetLdtInformation(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
NTKERNELAPI NTSTATUS PsChargeProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1168 of file psquota.c.
References PsInitialSystemProcess, PsPagedPool, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by ExpAllocateHandleTable(), ExpAllocateTablePagedPool(), ExpAllocateTablePagedPoolNoZero(), MiCloneProcessAddressSpace(), and MiInsertVadCharges().
NTSTATUS PsChargeProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
Definition at line 1227 of file psquota.c.
References PsInitialSystemProcess, PsPageFile, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by MiInsertVadCharges(), MiSetPageModified(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
NTKERNELAPI NTSTATUS PsChargeProcessPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
Definition at line 898 of file psquota.c.
References ASSERT, NonPagedPool, PagedPool, ProcessObject, PsInitialSystemProcess, PspChargeQuota(), and STATUS_SUCCESS.
Referenced by PsChargePoolQuota().
NTSTATUS PsChargeProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
Definition at line 1041 of file psquota.c.
References ASSERT, ProcessObject, PsInitialSystemProcess, PspChargeQuota(), and STATUS_SUCCESS.
PEPROCESS_QUOTA_BLOCK PsChargeSharedPoolQuota (IN PEPROCESS Process, IN ULONG_PTR PagedAmount, IN ULONG_PTR NonPagedAmount)
Definition at line 744 of file psquota.c.
References ASSERT, InterlockedIncrement, NT_SUCCESS, NULL, ProcessObject, PsInitialSystemProcess, PsNonPagedPool, PsPagedPool, PspChargeQuota(), PspReturnQuota(), _EPROCESS_QUOTA_BLOCK::ReferenceCount, and Status.
Referenced by ObpChargeQuotaForObject(), and RtlpAllocateAtom().
NTKERNELAPI NTSTATUS PsCreateSystemProcess (__out PHANDLE ProcessHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 921 of file create.c.
References NULL, PAGED_CODE, PspCreateProcess(), PspInitialSystemProcessHandle, and Status.
NTKERNELAPI NTSTATUS PsCreateSystemThread (__out PHANDLE ThreadHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt HANDLE ProcessHandle, __out_opt PCLIENT_ID ClientId, __in PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext)
Definition at line 172 of file create.c.
References ARGUMENT_PRESENT, FALSE, NULL, PAGED_CODE, PsInitialSystemProcess, PspCreateThread(), and Status.
Referenced by CmpInitializeHiveList(), ExpCreateWorkerThread(), ExpWorkerInitialization(), FsRtlInitializeWorkerThread(), IopStartApcHardError(), KeInitSystem(), MiModifiedPageWriter(), MiSectionInitialization(), MiZeroInParallel(), MmInitSystem(), PspInitPhase0(), SeRmInitPhase1(), and WmipStartLogger().
NTKERNELAPI VOID PsDereferenceImpersonationToken (__in PACCESS_TOKEN ImpersonationToken)
Definition at line 1951 of file security.c.
References NULL, ObDereferenceObject(), and PAGED_CODE.
Referenced by PsImpersonateClient(), and PsOpenTokenOfThread().
NTKERNELAPI VOID PsDereferencePrimaryToken (__in PACCESS_TOKEN PrimaryToken)
Definition at line 1922 of file security.c.
References ObDereferenceObject(), and PAGED_CODE.
NTKERNELAPI BOOLEAN PsDisableImpersonation (__inout PETHREAD Thread, __inout PSE_IMPERSONATION_STATE ImpersonationState)
Definition at line 998 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, FALSE, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PS_TEST_CLEAR_BITS, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), SecurityAnonymous, ThreadObject, _PS_IMPERSONATION_INFORMATION::Token, and TRUE.
Referenced by NtOpenThreadTokenEx().
VOID PsEnforceExecutionTimeLimits (VOID)
Definition at line 2445 of file psjob.c.
References _EJOB::ActiveProcesses, _EJOB::CompletionKey, _EJOB::CompletionPort, _EJOB::EndOfJobTimeAction, ERROR_NOT_ENOUGH_QUOTA, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, IoSetIoCompletion(), JOB_OBJECT_LIMIT_JOB_TIME, JOB_OBJECT_LIMIT_PROCESS_TIME, JOB_OBJECT_MSG_END_OF_JOB_TIME, JOB_OBJECT_MSG_END_OF_PROCESS_TIME, JOB_OBJECT_POST_AT_END_OF_JOB, JOB_OBJECT_TERMINATE_AT_END_OF_JOB, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeMaximumIncrement, KeQueryRuntimeProcess(), _EJOB::LimitFlags, NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, _EJOB::PerJobUserTimeLimit, _EJOB::PerProcessUserTimeLimit, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_CLEAR_BITS, PsGetCurrentThread(), PsGetNextJob(), PsGetNextJobProcess(), PspFoldProcessAccountingIntoJob(), PspTerminateAllProcessesInJob(), PspTerminateProcess(), _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::ThisPeriodTotalUserTime, _EJOB::TotalTerminatedProcesses, TRUE, UInt32x32To64, and _EPROCESS::UniqueProcessId.
Referenced by PspJobTimeLimitsWork().
NTSTATUS PsEnumProcesses (IN PROCESS_ENUM_ROUTINE CallBack, IN PVOID Context)
Definition at line 39 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PsActiveProcessHead, PsGetCurrentThread(), PspLockProcessList(), PspUnlockProcessList(), Status, and STATUS_SUCCESS.
Referenced by PsShutdownSystem().
NTSTATUS PsEnumProcessThreads (IN PEPROCESS Process, IN THREAD_ENUM_ROUTINE CallBack, IN PVOID Context)
Definition at line 291 of file psenum.c.
References NT_SUCCESS, NULL, PsGetNextProcessThread(), PsQuitNextProcessThread(), Status, and STATUS_SUCCESS.
NTKERNELAPI VOID PsEstablishWin32Callouts (__in PKWIN32_CALLOUTS_FPNS pWin32Callouts)
Definition at line 4300 of file psquery.c.
References ExDesktopCloseProcedureCallout, ExDesktopDeleteProcedureCallout, ExDesktopOkToCloseProcedureCallout, ExDesktopOpenProcedureCallout, ExGlobalAtomTableCallout, ExWindowStationCloseProcedureCallout, ExWindowStationDeleteProcedureCallout, ExWindowStationOkToCloseProcedureCallout, ExWindowStationOpenProcedureCallout, ExWindowStationParseProcedureCallout, KeGdiFlushUserBatch, and PAGED_CODE.
VOID PsExitSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 656 of file psdelete.c.
References PAGED_CODE, PsGetCurrentThread(), PspExitApcRundown(), PspExitThread(), and UNREFERENCED_PARAMETER.
Referenced by KiInsertQueueApc(), PspExitNormalApc(), and PspTerminateThreadByPointer().
BOOLEAN PsForwardException (IN PEXCEPTION_RECORD ExceptionRecord, IN BOOLEAN DebugException, IN BOOLEAN SecondChance)
NTKERNELAPI NTSTATUS PsGetContextThread (__in PETHREAD Thread, __inout PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
Definition at line 147 of file psctx.c.
References _GETSETCONTEXT::Apc, ASSERT, _GETSETCONTEXT::Context, CONTEXT_ALIGN, CONTEXT_EXTENDED_REGISTERS, _CONTEXT::ContextFlags, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, FIELD_OFFSET, KeEnterGuardedRegionThread(), KeInitializeApc(), KeInitializeEvent(), KeInsertQueueApc(), KeLeaveGuardedRegionThread(), KernelMode, KeWaitForSingleObject(), _GETSETCONTEXT::Mode, NotificationEvent, NULL, _GETSETCONTEXT::OperationComplete, OriginalApcEnvironment, PAGED_CODE, ProbeForReadSmallStructure, PsGetCurrentThread(), PspGetSetContextSpecialApc(), RtlCopyMemory, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _KAPC::SystemArgument1, _KAPC::SystemArgument2, and _ETHREAD::Tcb.
Referenced by NtGetContextThread().
NTKERNELAPI HANDLE PsGetCurrentProcessId (VOID)
Definition at line 2227 of file create.c.
References _ETHREAD::Cid, PsGetCurrentThread(), and _CLIENT_ID::UniqueProcess.
Referenced by CmpCreateRegistryRoot(), CmpDoCreateChild(), CmpDoOpen(), NtCreateKey(), SeAuditHandleCreation(), WmipAllocGuidEntryX(), WmipDoDisableRequest(), WmipReleaseCollectionEnabled(), WmipSendDisableRequest(), WmipSendEnableRequest(), and WmipWaitForCollectionEnabled().
NTKERNELAPI ULONG PsGetCurrentProcessSessionId (VOID)
Definition at line 48 of file pshelper.c.
References _PsGetCurrentProcess, and MmGetSessionId().
Referenced by ExpWin32SessionCallout(), NtSetInformationObject(), and ObpLookupObjectName().
NTKERNELAPI PVOID PsGetCurrentProcessWin32Process (VOID)
Definition at line 257 of file pshelper.c.
References PsGetCurrentProcess(), and _EPROCESS::Win32Process.
NTKERNELAPI HANDLE PsGetCurrentThreadId (VOID)
Definition at line 2233 of file create.c.
References _ETHREAD::Cid, PsGetCurrentThread(), and _CLIENT_ID::UniqueThread.
Referenced by NtCreateKey(), WmipAllocGuidEntryX(), WmipDoDisableRequest(), WmipReleaseCollectionEnabled(), WmipSendDisableRequest(), WmipSendEnableRequest(), and WmipWaitForCollectionEnabled().
NTKERNELAPI CCHAR PsGetCurrentThreadPreviousMode (VOID)
Definition at line 81 of file pshelper.c.
References KeGetPreviousMode.
NTKERNELAPI PEPROCESS PsGetCurrentThreadProcess (VOID)
Definition at line 319 of file pshelper.c.
References _PsGetCurrentThread, and THREAD_TO_PROCESS.
NTKERNELAPI HANDLE PsGetCurrentThreadProcessId (VOID)
Definition at line 338 of file pshelper.c.
References _PsGetCurrentThread.
NTKERNELAPI PVOID PsGetCurrentThreadStackBase (VOID)
Definition at line 65 of file pshelper.c.
References KeGetCurrentThread(), and _KTHREAD::StackBase.
NTKERNELAPI PVOID PsGetCurrentThreadStackLimit (VOID)
Definition at line 73 of file pshelper.c.
References KeGetCurrentThread(), and _KTHREAD::StackLimit.
NTKERNELAPI PVOID PsGetCurrentThreadTeb (VOID)
Definition at line 365 of file pshelper.c.
References _PsGetCurrentThread.
NTKERNELAPI PVOID PsGetCurrentThreadWin32Thread (VOID)
Definition at line 383 of file pshelper.c.
References _PsGetCurrentThread.
NTKERNELAPI PVOID PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion (__out PHANDLE ProcessId)
Definition at line 392 of file pshelper.c.
References _PsGetCurrentThread, _ETHREAD::Cid, KeEnterCriticalRegionThread(), _ETHREAD::Tcb, _CLIENT_ID::UniqueProcess, and _KTHREAD::Win32Thread.
NTKERNELAPI PERESOURCE PsGetJobLock (__in PEJOB Job)
Definition at line 89 of file pshelper.c.
NTKERNELAPI ULONG PsGetJobSessionId (__in PEJOB Job)
Definition at line 97 of file pshelper.c.
NTKERNELAPI ULONG PsGetJobUIRestrictionsClass (__in PEJOB Job)
Definition at line 105 of file pshelper.c.
PKPROCESS FORCEINLINE PsGetKernelProcess (IN PEPROCESS ProcessObject)
Definition at line 836 of file ps.h.
References ProcessObject.
PKTHREAD FORCEINLINE PsGetKernelThread (IN PETHREAD ThreadObject)
Definition at line 827 of file ps.h.
References ThreadObject.
Referenced by PspExitNormalApc(), and PspTerminateThreadByPointer().
PEJOB PsGetNextJob (IN PEJOB Job)
Definition at line 332 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PsGetCurrentThread(), PspJobList, PspLockJobListShared(), and PspUnlockJobListShared().
Referenced by PsEnforceExecutionTimeLimits().
PEPROCESS PsGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
Definition at line 433 of file psenum.c.
References CONTAINING_RECORD, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), _ETHREAD::Tcb, and TRUE.
Referenced by PsEnforceExecutionTimeLimits(), and PspTerminateAllProcessesInJob().
PEPROCESS PsGetNextProcess (IN PEPROCESS Process)
Definition at line 110 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PsActiveProcessHead, PsGetCurrentThread(), PspLockProcessList(), and PspUnlockProcessList().
Referenced by DbgkpCloseObject(), ExpDebuggerWorker(), ExpGetProcessInformation(), NtGetNextProcess(), PerfInfoFileNameRunDown(), PsShutdownSystem(), and PsWaitForAllProcesses().
PETHREAD PsGetNextProcessThread (IN PEPROCESS Process, IN PETHREAD Thread)
Definition at line 210 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), PspLockProcessShared(), and PspUnlockProcessShared().
Referenced by DbgkpPostFakeThreadMessages(), DbgkpSetProcessDebugObject(), ExSwapinWorkerThreads(), NtGetNextThread(), NtSetInformationProcess(), NtSetInformationThread(), NtTerminateProcess(), PsEnumProcessThreads(), PspTerminateProcess(), PspWaitForUsermodeExit(), PsResumeProcess(), and PsSuspendProcess().
NTKERNELAPI LONGLONG PsGetProcessCreateTimeQuadPart (__in PEPROCESS Process)
Definition at line 113 of file pshelper.c.
NTKERNELAPI PVOID PsGetProcessDebugPort (__in PEPROCESS Process)
Definition at line 121 of file pshelper.c.
NTKERNELAPI BOOLEAN PsGetProcessExitProcessCalled (__in PEPROCESS Process)
Definition at line 142 of file pshelper.c.
References PS_PROCESS_FLAGS_PROCESS_EXITING.
NTKERNELAPI NTSTATUS PsGetProcessExitStatus (__in PEPROCESS Process)
Definition at line 150 of file pshelper.c.
NTKERNELAPI LARGE_INTEGER PsGetProcessExitTime (VOID)
Definition at line 1736 of file psdelete.c.
References _EPROCESS::ExitTime, PAGED_CODE, and PsGetCurrentProcess().
NTKERNELAPI HANDLE PsGetProcessId (__in PEPROCESS Process)
Definition at line 158 of file pshelper.c.
NTKERNELAPI UCHAR* PsGetProcessImageFileName (__in PEPROCESS Process)
Definition at line 167 of file pshelper.c.
Referenced by CmpDumpOneKeyBody().
NTKERNELAPI HANDLE PsGetProcessInheritedFromUniqueProcessId (__in PEPROCESS Process)
Definition at line 176 of file pshelper.c.
NTKERNELAPI PEJOB PsGetProcessJob (__in PEPROCESS Process)
Definition at line 185 of file pshelper.c.
NTKERNELAPI PPEB PsGetProcessPeb (__in PEPROCESS Process)
Definition at line 221 of file pshelper.c.
NTKERNELAPI UCHAR PsGetProcessPriorityClass (__in PEPROCESS Process)
Definition at line 230 of file pshelper.c.
NTKERNELAPI PVOID PsGetProcessSectionBaseAddress (__in PEPROCESS Process)
Definition at line 212 of file pshelper.c.
NTKERNELAPI PVOID PsGetProcessSecurityPort (__in PEPROCESS Process)
Definition at line 517 of file pshelper.c.
NTKERNELAPI ULONG PsGetProcessSessionId (__in PEPROCESS Process)
Definition at line 194 of file pshelper.c.
References MmGetSessionId().
NTKERNELAPI ULONG PsGetProcessSessionIdEx (__in PEPROCESS Process)
Definition at line 203 of file pshelper.c.
References MmGetSessionIdEx().
NTKERNELAPI PVOID PsGetProcessWin32Process (__in PEPROCESS Process)
Definition at line 248 of file pshelper.c.
NTKERNELAPI HANDLE PsGetProcessWin32WindowStation (__in PEPROCESS Process)
Definition at line 238 of file pshelper.c.
NTKERNELAPI CCHAR PsGetThreadFreezeCount (__in PETHREAD Thread)
Definition at line 293 of file pshelper.c.
NTKERNELAPI BOOLEAN PsGetThreadHardErrorsAreDisabled (__in PETHREAD Thread)
Definition at line 302 of file pshelper.c.
References PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED.
NTKERNELAPI HANDLE PsGetThreadId (__in PETHREAD Thread)
Definition at line 284 of file pshelper.c.
NTKERNELAPI PEPROCESS PsGetThreadProcess (__in PETHREAD Thread)
Definition at line 310 of file pshelper.c.
References THREAD_TO_PROCESS.
NTKERNELAPI HANDLE PsGetThreadProcessId (__in PETHREAD Thread)
Definition at line 329 of file pshelper.c.
NTKERNELAPI ULONG PsGetThreadSessionId (__in PETHREAD Thread)
Definition at line 347 of file pshelper.c.
References MmGetSessionId(), and THREAD_TO_PROCESS.
NTKERNELAPI PVOID PsGetThreadTeb (__in PETHREAD Thread)
Definition at line 356 of file pshelper.c.
NTKERNELAPI PVOID PsGetThreadWin32Thread (__in PETHREAD Thread)
Definition at line 374 of file pshelper.c.
NTKERNELAPI BOOLEAN PsGetVersion (__out_opt PULONG MajorVersion, __out_opt PULONG MinorVersion, __out_opt PULONG BuildNumber, __out_opt PUNICODE_STRING CSDVersion)
Definition at line 2239 of file create.c.
References ARGUMENT_PRESENT, CmCSDVersionString, NtBuildNumber, NtMajorVersion, and NtMinorVersion.
NTKERNELAPI NTSTATUS PsImpersonateClient (__inout PETHREAD Thread, __in PACCESS_TOKEN Token, __in BOOLEAN CopyOnOpen, __in BOOLEAN EffectiveOnly, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 663 of file security.c.
References ARGUMENT_PRESENT, ASSERT, _PS_JOB_TOKEN_FILTER::CapturedGroupCount, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedPrivilegeCount, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedSidCount, _PS_JOB_TOKEN_FILTER::CapturedSids, _PS_JOB_TOKEN_FILTER::CapturedSidsLength, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, _EJOB::Filter, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, InterlockedCompareExchangePointer, _EPROCESS::Job, JOB_OBJECT_SECURITY_NO_ADMIN, JOB_OBJECT_SECURITY_RESTRICTED_TOKEN, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PagedPool, PROTECTED_POOL, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PS_SET_BITS, PsDereferenceImpersonationToken(), PsDereferencePrimaryTokenEx, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), PspWriteTebImpersonationInfo(), PsReferencePrimaryToken(), SeCopyClientToken(), SecurityIdentification, _EJOB::SecurityLimitFlags, SeFastFilterToken(), SeTokenCanImpersonate(), SeTokenIsAdmin(), SeTokenIsRestricted(), Status, STATUS_ACCESS_DENIED, STATUS_NO_MEMORY, STATUS_SUCCESS, THREAD_TO_PROCESS, ThreadObject, _PS_IMPERSONATION_INFORMATION::Token, and TRUE.
Referenced by NtImpersonateAnonymousToken(), NtOpenThreadTokenEx(), PsAssignImpersonationToken(), and SeImpersonateClientEx().
VOID PsInitializeQuotaSystem (VOID)
Definition at line 37 of file psquota.c.
References InitializeListHead(), KeInitializeSpinLock(), _EPROCESS_QUOTA_ENTRY::Limit, _EPROCESS_QUOTA_BLOCK::ProcessCount, PsGetCurrentProcess(), PsNonPagedPool, PsPagedPool, PsPageFile, PspDefaultQuotaBlock, PspQuotaLock, _EPROCESS::QuotaBlock, _EPROCESS_QUOTA_BLOCK::QuotaEntry, and _EPROCESS_QUOTA_BLOCK::ReferenceCount.
Referenced by ObInitSystem().
BOOLEAN PsInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 144 of file psinit.c.
References InitializationPhase, KeBugCheckEx(), PspInitPhase0(), PspInitPhase1(), UNEXPECTED_INITIALIZATION_CALL, and UNREFERENCED_PARAMETER.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTKERNELAPI BOOLEAN PsIsProcessBeingDebugged (__in PEPROCESS Process)
Definition at line 130 of file pshelper.c.
References FALSE, NULL, and TRUE.
NTKERNELAPI BOOLEAN PsIsSystemProcess (__in PEPROCESS Process)
Definition at line 413 of file pshelper.c.
References PsInitialSystemProcess.
NTKERNELAPI BOOLEAN PsIsSystemThread (__in PETHREAD Thread)
Definition at line 404 of file pshelper.c.
References IS_SYSTEM_THREAD.
NTKERNELAPI BOOLEAN PsIsThreadImpersonating (__in PETHREAD Thread)
Definition at line 537 of file pshelper.c.
References PAGED_CODE, and PS_IS_THREAD_IMPERSONATING.
NTSTATUS PsLocateSystemDll (BOOLEAN ReplaceExisting)
Definition at line 582 of file psinit.c.
References DbgPrint(), _SYSTEM_DLL::DllBase, _SYSTEM_DLL::DllLock, EmbeddedNT, ExAcquirePushLockExclusive(), ExInitializePushLock(), ExReleasePushLockExclusive(), ExVerifySuite(), FALSE, FILE_EXECUTE, FILE_SHARE_READ, InitializeObjectAttributes, KeBugCheckEx(), KeEnterCriticalRegion(), KeLeaveCriticalRegion(), KernelMode, MmCheckSystemImage(), MmSectionObjectType, NT_SUCCESS, NtRaiseHardError(), NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, OptionOk, PAGE_EXECUTE, PROCESS1_INITIALIZATION_FAILED, PS_EMBEDDED_NO_USERMODE, PsGetCurrentProcess(), PsMapSystemDll(), SEC_IMAGE, _SYSTEM_DLL::Section, SECTION_ALL_ACCESS, STATUS_IMAGE_CHECKSUM_MISMATCH, STATUS_INVALID_IMAGE_PROTECT, STATUS_SUCCESS, SYNCHRONIZE, TRUE, ZwClose(), ZwCreateSection(), and ZwOpenFile().
Referenced by IoInitSystem().
NTKERNELAPI NTSTATUS PsLookupProcessByProcessId (__in HANDLE ProcessId, __deref_out PEPROCESS * Process)
Definition at line 118 of file pscid.c.
References ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _EPROCESS::GrantedAccess, _KPROCESS::Header, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, _HANDLE_TABLE_ENTRY::Object, ObReferenceObjectSafe(), PAGED_CODE, _EPROCESS::Pcb, ProcessObject, PsGetCurrentThread(), PspCidTable, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, and _DISPATCHER_HEADER::Type.
Referenced by CmpDumpOneKeyBody(), and NtOpenProcess().
NTKERNELAPI NTSTATUS PsLookupProcessThreadByCid (__in PCLIENT_ID Cid, __deref_opt_out PEPROCESS * Process, __deref_out PETHREAD * Thread)
Definition at line 28 of file pscid.c.
References ARGUMENT_PRESENT, _ETHREAD::Cid, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _ETHREAD::GrantedAccess, _KTHREAD::Header, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, ObDereferenceObject(), _HANDLE_TABLE_ENTRY::Object, ObReferenceObject, ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), PspCidTable, Status, STATUS_INVALID_CID, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, ThreadObject, _DISPATCHER_HEADER::Type, and _CLIENT_ID::UniqueProcess.
Referenced by LpcpCopyRequestData(), LpcpRequestWaitReplyPort(), NtAcceptConnectPort(), NtImpersonateClientOfPort(), NtOpenProcess(), NtOpenThread(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
NTKERNELAPI NTSTATUS PsLookupThreadByThreadId (__in HANDLE ThreadId, __deref_out PETHREAD * Thread)
Definition at line 180 of file pscid.c.
References ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _ETHREAD::GrantedAccess, _KTHREAD::Header, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, _HANDLE_TABLE_ENTRY::Object, ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), PspCidTable, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, ThreadObject, and _DISPATCHER_HEADER::Type.
Referenced by NtOpenThread().
NTSTATUS PsMapSystemDll (IN PEPROCESS Process, OUT PVOID *DllBase OPTIONAL, IN LOGICAL UseLargePages)
Definition at line 760 of file psinit.c.
References ARGUMENT_PRESENT, DbgPrint(), _SYSTEM_DLL::DllLock, ExAcquirePushLockShared(), ExReleasePushLockShared(), _LARGE_INTEGER::HighPart, KeEnterCriticalRegion(), KeLeaveCriticalRegion(), _LARGE_INTEGER::LowPart, MEM_LARGE_PAGES, MmMapViewOfSection(), NULL, ObDereferenceObject(), ObReferenceObject, PAGE_READWRITE, PAGED_CODE, _SYSTEM_DLL::Section, STATUS_CONFLICTING_ADDRESSES, STATUS_SUCCESS, and ViewShare.
Referenced by MmInitializeProcessAddressSpace(), and PsLocateSystemDll().
NTSTATUS PsOpenTokenOfJob (IN HANDLE JobHandle, OUT PACCESS_TOKEN * Token)
NTSTATUS PsOpenTokenOfProcess (IN HANDLE ProcessHandle, OUT PACCESS_TOKEN * Token)
Definition at line 512 of file security.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_QUERY_INFORMATION, PsProcessType, PsReferencePrimaryToken(), Status, and STATUS_SUCCESS.
Referenced by NtOpenProcessTokenEx().
NTSTATUS PsOpenTokenOfThread (IN HANDLE ThreadHandle, IN BOOLEAN OpenAsSelf, OUT PACCESS_TOKEN * Token, OUT PBOOLEAN CopyOnOpen, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 371 of file security.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsDereferenceImpersonationToken(), PsReferenceImpersonationToken(), PsThreadType, SecurityAnonymous, Status, STATUS_CANT_OPEN_ANONYMOUS, STATUS_NO_TOKEN, STATUS_SUCCESS, THREAD_QUERY_INFORMATION, and UNREFERENCED_PARAMETER.
VOID PspContextFromKframes (OUT PKTRAP_FRAME TrapFrame, OUT PKEXCEPTION_FRAME ExceptionFrame, IN PCONTEXT Context)
VOID PspContextToKframes (OUT PKTRAP_FRAME TrapFrame, OUT PKEXCEPTION_FRAME ExceptionFrame, IN PCONTEXT Context)
VOID PsQuitNextJob (IN PEJOB Job)
Definition at line 410 of file psenum.c.
References ObDereferenceObject().
VOID PsQuitNextJobProcess (IN PEPROCESS Process)
Definition at line 496 of file psenum.c.
References ObDereferenceObject().
VOID PsQuitNextProcess (IN PEPROCESS Process)
Definition at line 187 of file psenum.c.
References ObDereferenceObject().
Referenced by ExpDebuggerWorker(), ExpGetProcessInformation(), and PsWaitForAllProcesses().
VOID PsQuitNextProcessThread (IN PETHREAD Thread)
Definition at line 268 of file psenum.c.
References ObDereferenceObject().
Referenced by DbgkpPostFakeThreadMessages(), PsEnumProcessThreads(), and PspWaitForUsermodeExit().
PACCESS_TOKEN PsReferenceEffectiveToken (IN PETHREAD Thread, OUT PTOKEN_TYPE TokenType, OUT PBOOLEAN EffectiveOnly, OUT PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 225 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, FALSE, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, ObFastReferenceObject(), ObFastReferenceObjectLocked(), ObReferenceObject, PAGED_CODE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockProcessSecurityShared(), PspLockThreadSecurityShared(), PspUnlockProcessSecurityShared(), PspUnlockThreadSecurityShared(), THREAD_TO_PROCESS, ThreadObject, _PS_IMPERSONATION_INFORMATION::Token, _EPROCESS::Token, TokenImpersonation, and TokenPrimary.
Referenced by SeCreateClientSecurity().
NTKERNELAPI PACCESS_TOKEN PsReferenceImpersonationToken (__inout PETHREAD Thread, __out PBOOLEAN CopyOnOpen, __out PBOOLEAN EffectiveOnly, __out PSECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 108 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, ObReferenceObject, PAGED_CODE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockThreadSecurityShared(), PspUnlockThreadSecurityShared(), ThreadObject, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by ObpReferenceDeviceMap(), PsOpenTokenOfThread(), SeCaptureSubjectContextEx(), and SepOpenTokenOfThread().
NTKERNELAPI PACCESS_TOKEN PsReferencePrimaryToken (__inout PEPROCESS Process)
Definition at line 59 of file security.c.
References ASSERT, NULL, ObFastReferenceObject(), ObFastReferenceObjectLocked(), PAGED_CODE, ProcessObject, PsGetCurrentThread(), PspLockProcessSecurityShared(), and PspUnlockProcessSecurityShared().
Referenced by NtAssignProcessToJobObject(), NtImpersonateAnonymousToken(), NtOpenThreadTokenEx(), NtSecureConnectPort(), ObpSetCurrentProcessDeviceMap(), PsImpersonateClient(), PsOpenTokenOfProcess(), PspCreateProcess(), PspCreateThread(), PspExitThread(), PspInitializeProcessSecurity(), PspSetPrimaryToken(), SeAuditProcessExit(), SeCaptureSubjectContextEx(), SeIsChildToken(), SeIsChildTokenByPointer(), SeIsSiblingToken(), SeIsSiblingTokenByPointer(), and WmiTraceProcess().
NTSTATUS PsReferenceProcessFilePointer (IN PEPROCESS Process, OUT PVOID * pFilePointer)
Definition at line 563 of file pshelper.c.
References ExAcquireRundownProtection(), ExReleaseRundownProtection(), MmGetFileObjectForSection(), NULL, ObReferenceObject, PAGED_CODE, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
Referenced by SeLocateProcessImageName().
NTKERNELAPI NTSTATUS PsRemoveCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 1936 of file create.c.
References ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedDecrement, NULL, PAGED_CODE, PSP_MAX_CREATE_THREAD_NOTIFY, PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, STATUS_PROCEDURE_NOT_FOUND, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS PsRemoveLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 2326 of file create.c.
References ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedDecrement, NULL, PAGED_CODE, PSP_MAX_LOAD_IMAGE_NOTIFY, PspLoadImageNotifyRoutine, PspLoadImageNotifyRoutineCount, STATUS_PROCEDURE_NOT_FOUND, and STATUS_SUCCESS.
VOID PsReportProcessMemoryLimitViolation (VOID)
Definition at line 2958 of file psjob.c.
References _EJOB::CompletionKey, _EJOB::CompletionPort, IoSetIoCompletion(), _EPROCESS::Job, JOB_OBJECT_LIMIT_PROCESS_MEMORY, JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT, _EPROCESS::JobStatus, _EJOB::LimitFlags, NULL, PAGED_CODE, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspLockJobLimitsShared(), PspUnlockJobLimitsShared(), STATUS_SUCCESS, TRUE, and _EPROCESS::UniqueProcessId.
Referenced by MiInsertVadCharges(), MiSetPageModified(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
NTKERNELAPI VOID PsRestoreImpersonation (__inout PETHREAD Thread, __in PSE_IMPERSONATION_STATE ImpersonationState)
Definition at line 1096 of file security.c.
References ASSERT, _PS_IMPERSONATION_INFORMATION::CopyOnOpen, _PS_IMPERSONATION_INFORMATION::EffectiveOnly, _PS_IMPERSONATION_INFORMATION::ImpersonationLevel, NULL, ObDereferenceObject(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PS_SET_BITS, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), ThreadObject, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by NtOpenThreadTokenEx().
NTSTATUS PsResumeProcess (IN PEPROCESS Process)
NTSTATUS PsResumeThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
Definition at line 286 of file psspnd.c.
References ARGUMENT_PRESENT, KeResumeThread(), PAGED_CODE, and STATUS_SUCCESS.
Referenced by DbgkpPostFakeThreadMessages(), DbgkpWakeTarget(), and NtResumeThread().
NTKERNELAPI VOID PsReturnPoolQuota (__in PEPROCESS Process, __in POOL_TYPE PoolType, __in ULONG_PTR Amount)
Definition at line 943 of file psquota.c.
References ASSERT, NonPagedPool, PagedPool, ProcessObject, PsInitialSystemProcess, and PspReturnQuota().
Referenced by ExFreePoolWithTag(), and ExReturnPoolQuota().
NTKERNELAPI VOID PsReturnProcessNonPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1138 of file psquota.c.
References PsInitialSystemProcess, PsNonPagedPool, and PspReturnQuota().
Referenced by ExDereferenceHandleDebugInfo(), ExEnableHandleTracing(), MiCleanPhysicalProcessPages(), MiCloneProcessAddressSpace(), MiDecrementCloneBlockReference(), MiInsertVadCharges(), MiPhysicalViewRemover(), MiRemoveVadCharges(), NtAllocateVirtualMemory(), NtSetInformationProcess(), PspDeleteLdt(), PspDeleteVdmObjects(), PspProcessDelete(), PspSetLdtInformation(), PspSetLdtSize(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
NTKERNELAPI VOID PsReturnProcessPagedPoolQuota (__in PEPROCESS Process, __in SIZE_T Amount)
Definition at line 1197 of file psquota.c.
References PsInitialSystemProcess, PsPagedPool, and PspReturnQuota().
Referenced by ExpAllocateHandleTable(), ExpFreeHandleTable(), ExpFreeTablePagedPool(), FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifyCompleteIrp(), FsRtlNotifyFilterReportChange(), MiCloneProcessAddressSpace(), MiDecrementCloneBlockReference(), MiInsertVadCharges(), MiRemoveVadCharges(), and PspDeleteVdmObjects().
VOID PsReturnProcessPageFileQuota (IN PEPROCESS Process, IN SIZE_T Amount)
Definition at line 1256 of file psquota.c.
References PsInitialSystemProcess, PsPageFile, and PspReturnQuota().
Referenced by MiInsertVadCharges(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MiSetPageModified(), MiSetProtectionOnSection(), MmCleanProcessAddressSpace(), NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
VOID PsReturnProcessQuota (IN PEPROCESS Process, IN PS_QUOTA_TYPE QuotaType, IN SIZE_T Amount)
Definition at line 1075 of file psquota.c.
References ASSERT, ProcessObject, PsInitialSystemProcess, and PspReturnQuota().
VOID PsReturnSharedPoolQuota (IN PEPROCESS_QUOTA_BLOCK QuotaBlock, IN ULONG_PTR PagedAmount, IN ULONG_PTR NonPagedAmount)
Definition at line 809 of file psquota.c.
References NULL, PsNonPagedPool, PsPagedPool, PspDereferenceQuotaBlock(), and PspReturnQuota().
Referenced by ObpFreeObject(), and RtlpFreeAtom().
NTKERNELAPI VOID PsRevertThreadToSelf (__inout PETHREAD Thread)
Definition at line 1259 of file security.c.
References ASSERT, NULL, ObDereferenceObject(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PspLockThreadSecurityExclusive(), PspUnlockThreadSecurityExclusive(), PspWriteTebImpersonationInfo(), ThreadObject, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by PsAssignImpersonationToken().
NTKERNELAPI VOID PsRevertToSelf (VOID)
Referenced by CmpCmdHiveOpen(), and WmipCreateLogFile().
NTKERNELAPI ULONG PsSetBBTNotifyRoutine (__in PBBT_NOTIFY_ROUTINE BBTNotifyRoutine)
Definition at line 73 of file psdelete.c.
References FIELD_OFFSET, PAGED_CODE, and PspBBTNotifyRoutine.
NTKERNELAPI NTSTATUS PsSetContextThread (__in PETHREAD Thread, __in PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
Definition at line 389 of file psctx.c.
References _GETSETCONTEXT::Apc, ASSERT, _GETSETCONTEXT::Context, CONTEXT_ALIGN, CONTEXT_EXTENDED_REGISTERS, _CONTEXT::ContextFlags, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, FIELD_OFFSET, KeEnterGuardedRegionThread(), KeInitializeApc(), KeInitializeEvent(), KeInsertQueueApc(), KeLeaveGuardedRegionThread(), KernelMode, KeWaitForSingleObject(), _GETSETCONTEXT::Mode, NotificationEvent, NULL, _GETSETCONTEXT::OperationComplete, OriginalApcEnvironment, PAGED_CODE, ProbeForReadSmallStructure, PsGetCurrentThread(), PspGetSetContextSpecialApc(), RtlCopyMemory, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _KAPC::SystemArgument1, _KAPC::SystemArgument2, and _ETHREAD::Tcb.
Referenced by NtSetContextThread().
NTKERNELAPI NTSTATUS PsSetCreateProcessNotifyRoutine (__in PCREATE_PROCESS_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
Definition at line 1761 of file create.c.
References ExAllocateCallBack(), ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedDecrement, InterlockedIncrement, NULL, PAGED_CODE, PSP_MAX_CREATE_PROCESS_NOTIFY, PspCreateProcessNotifyRoutine, PspCreateProcessNotifyRoutineCount, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PROCEDURE_NOT_FOUND, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS PsSetCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 1876 of file create.c.
References ExAllocateCallBack(), ExCompareExchangeCallBack(), ExFreeCallBack(), InterlockedIncrement, NULL, PAGED_CODE, PSP_MAX_CREATE_THREAD_NOTIFY, PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
NTKERNELAPI VOID PsSetJobUIRestrictionsClass (__out PEJOB Job, __in ULONG UIRestrictionsClass)
Definition at line 422 of file pshelper.c.
NTSTATUS PsSetLdtEntries (IN ULONG Selector0, IN ULONG Entry0Low, IN ULONG Entry0Hi, IN ULONG Selector1, IN ULONG Entry1Low, IN ULONG Entry1Hi)
Definition at line 1152 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ASSERT, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, Ke386SetDescriptorProcess(), Ke386SetLdtProcess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, _EPROCESS::LdtInformation, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, ProcessLdtInformation, PsChargeProcessNonPagedPoolQuota(), PsGetCurrentProcess(), PspIsDescriptorValid(), PsReturnProcessNonPagedPoolQuota(), ROUND_TO_PAGES, RPL_MASK, RtlCopyMemory, RtlZeroMemory, SELECTOR_TABLE_INDEX, _LDTINFORMATION::Size, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_LDT_DESCRIPTOR, and STATUS_SUCCESS.
Referenced by NtSetLdtEntries().
NTKERNELAPI NTSTATUS PsSetLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 2265 of file create.c.
References ExAllocateCallBack(), ExCompareExchangeCallBack(), ExFreeCallBack(), InterlockedIncrement, NULL, PAGED_CODE, PsImageNotifyEnabled, PSP_MAX_LOAD_IMAGE_NOTIFY, PspLoadImageNotifyRoutine, PspLoadImageNotifyRoutineCount, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by PspInitPhase0(), and WmipEnableKernelTrace().
NTSTATUS PsSetProcessLdtInfo (IN PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength)
Definition at line 1508 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ASSERT, ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, Ke386SetDescriptorProcess(), Ke386SetLdtProcess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, _LDT_INFORMATION::LdtEntries, _EPROCESS::LdtInformation, _LDT_INFORMATION::Length, NonPagedPool, NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, _EPROCESS::Pcb, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, PsChargeProcessNonPagedPoolQuota(), PsGetCurrentProcess(), PspCreateLdt(), PspIsDescriptorValid(), PsReturnProcessNonPagedPoolQuota(), ROUND_TO_PAGES, RtlCopyMemory, RtlZeroMemory, _LDTINFORMATION::Size, _LDT_INFORMATION::Start, Status, STATUS_ACCESS_VIOLATION, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_LDT_DESCRIPTOR, STATUS_INVALID_LDT_OFFSET, STATUS_INVALID_LDT_SIZE, and STATUS_SUCCESS.
NTKERNELAPI VOID PsSetProcessPriorityByClass (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode)
Definition at line 4366 of file psquery.c.
References KeSetPriorityAndQuantumProcess(), PAGED_CODE, and PspComputeQuantumAndPriority().
Referenced by NtSetInformationProcess(), and PspApplyJobLimitsToProcess().
NTKERNELAPI VOID PsSetProcessPriorityClass (__out PEPROCESS Process, __in UCHAR PriorityClass)
Definition at line 432 of file pshelper.c.
NTKERNELAPI NTSTATUS PsSetProcessSecurityPort (__out PEPROCESS Process, __in PVOID Port)
Definition at line 526 of file pshelper.c.
References STATUS_SUCCESS.
NTKERNELAPI NTSTATUS PsSetProcessWin32Process (__in PEPROCESS Process, __in PVOID Win32Process, __in PVOID PrevWin32Process)
Definition at line 442 of file pshelper.c.
References _PsGetCurrentThread, NULL, PS_PROCESS_FLAGS_PROCESS_DELETE, PspLockProcessExclusive(), PspUnlockProcessExclusive(), Status, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
NTKERNELAPI VOID PsSetProcessWindowStation (__out PEPROCESS Process, __in HANDLE Win32WindowStation)
Definition at line 478 of file pshelper.c.
NTKERNELAPI VOID PsSetThreadHardErrorsAreDisabled (__in PETHREAD Thread, __in BOOLEAN HardErrorsAreDisabled)
Definition at line 488 of file pshelper.c.
References PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, and PS_SET_BITS.
NTKERNELAPI VOID PsSetThreadWin32Thread (__inout PETHREAD Thread, __in PVOID Win32Thread, __in PVOID PrevWin32Thread)
Definition at line 502 of file pshelper.c.
References InterlockedCompareExchangePointer, InterlockedExchangePointer, and NULL.
LOGICAL PsShutdownSystem (VOID)
Definition at line 1854 of file psdelete.c.
References ASSERT, CONTAINING_RECORD, _SYSTEM_DLL::DllBase, Executive, FALSE, _EPROCESS::Flags, InterlockedCompareExchangePointer, KernelMode, KeWaitForMultipleObjects(), MmGetSessionId(), MmUnmapViewOfSection(), NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _EPROCESS::Pcb, PoCleanShutdownEnabled(), PS_PROCESS_FLAGS_PROCESS_EXITING, PsContinueWaiting, PsEnumProcesses(), PsGetCurrentThread(), PsGetNextProcess(), PsIdleProcess, PsInitialSystemProcess, PspFreezeProcessWorker(), PspInitialSystemProcessHandle, PspShutdownJobLimits(), PspShutdownThread, PspSystemDll, PspWaitForUsermodeExit(), PsTerminateProcess(), _SYSTEM_DLL::Section, _EPROCESS::SecurityPort, Status, STATUS_NOTHING_TO_TERMINATE, STATUS_SUCCESS, STATUS_SYSTEM_SHUTDOWN, STATUS_TIMEOUT, TRUE, WAIT_BATCH, WaitAny, and ZwClose().
NTSTATUS PsSuspendProcess (IN PEPROCESS Process)
Referenced by PspFreezeProcessWorker().
NTSTATUS PsSuspendThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
Definition at line 37 of file psspnd.c.
References ARGUMENT_PRESENT, ExAcquireRundownProtection(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), KeForceResumeThread(), KeSuspendThread(), PAGED_CODE, PS_CROSS_THREAD_FLAGS_TERMINATED, PsGetCurrentThread(), Status, STATUS_SUCCESS, STATUS_SUSPEND_COUNT_EXCEEDED, and STATUS_THREAD_IS_TERMINATING.
Referenced by DbgkpPostFakeThreadMessages(), NtSuspendThread(), and PsSuspendProcess().
NTSTATUS PsTerminateProcess (IN PEPROCESS Process, IN NTSTATUS Status)
Referenced by DbgkpCloseObject(), and ExpDebuggerWorker().
NTKERNELAPI NTSTATUS PsTerminateSystemThread (__in NTSTATUS ExitStatus)
Definition at line 602 of file psdelete.c.
References IS_SYSTEM_THREAD, PsGetCurrentThread(), PspTerminateThreadByPointer(), STATUS_INVALID_PARAMETER, and TRUE.
Referenced by CmpLoadHiveThread(), ExpShutdownWorker(), ExpWorkerThread(), ExpWorkerThreadBalanceManager(), and WmipLogger().
VOID PsThreadHit (IN PETHREAD Thread)
BOOLEAN PsWaitForAllProcesses (VOID)
Definition at line 2035 of file psdelete.c.
References Executive, FALSE, _EPROCESS::Flags, KdPrint, KernelMode, KeWaitForSingleObject(), NULL, ObDereferenceObject(), _EPROCESS::ObjectTable, ObReferenceObject, PS_PROCESS_FLAGS_PROCESS_EXITING, PsGetNextProcess(), PsIdleProcess, PsInitialSystemProcess, PsProcessType, PsQuitNextProcess(), _LARGE_INTEGER::QuadPart, Status, STATUS_TIMEOUT, _OBJECT_TYPE::TotalNumberOfObjects, and TRUE.
VOID PsWatchWorkingSet (IN NTSTATUS Status, IN PVOID PcValue, IN PVOID Va)
Definition at line 4222 of file psquery.c.
References _PAGEFAULT_HISTORY::CurrentIndex, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _PROCESS_WS_WATCH_INFORMATION::FaultingPc, _PROCESS_WS_WATCH_INFORMATION::FaultingVa, _PAGEFAULT_HISTORY::MaxIndex, NULL, PsGetCurrentProcess(), _PAGEFAULT_HISTORY::SpinLock, STATUS_PAGE_FAULT_DEMAND_ZERO, TRUE, _PAGEFAULT_HISTORY::WatchInfo, and _EPROCESS::WorkingSetWatch.
NTKERNELAPI NTSTATUS PsWrapApcWow64Thread (__inout PVOID * ApcContext, __inout PVOID * ApcRoutine)
Definition at line 607 of file psctx.c.
References except, EXCEPTION_EXECUTE_HANDLER, NULL, PsGetCurrentProcess(), STATUS_SUCCESS, UNREFERENCED_PARAMETER, and Wow64KiWrapApcProc.
Variable Documentation
LIST_ENTRY PsActiveProcessHead
Definition at line 139 of file psinit.c.
Referenced by PsEnumProcesses(), PsGetNextProcess(), and PspCreateProcess().
LCID PsDefaultSystemLocaleId
Definition at line 52 of file create.c.
Referenced by CmGetSystemControlValues(), CmpCreatePerfKeys(), LdrpSearchResourceSection_U(), MiSessionCreateInternal(), NtQueryDefaultLocale(), and NtSetDefaultLocale().
LCID PsDefaultThreadLocaleId
Definition at line 53 of file create.c.
Referenced by CmGetSystemControlValues(), MmGetSessionLocaleId(), and MmSetSessionLocaleId().
LANGID PsDefaultUILanguageId
Definition at line 54 of file create.c.
Referenced by CmGetSystemControlValues(), and CmpCreatePerfKeys().
ULONG PsEmbeddedNTMask
Definition at line 49 of file psinit.c.
PVOID PsHalImageBase
PEPROCESS PsIdleProcess
Definition at line 140 of file psinit.c.
Referenced by ExpGetProcessInformation(), MiZeroAwePageWorker(), MiZeroInParallel(), NtQuerySystemInformation(), PspFreezeProcessWorker(), PsShutdownSystem(), and PsWaitForAllProcesses().
BOOLEAN PsImageNotifyEnabled
Definition at line 65 of file create.c.
Referenced by DbgkCreateThread(), MiMapViewOfImageSection(), MmLoadSystemImage(), PsCallImageNotifyRoutines(), and PsSetLoadImageNotifyRoutine().
PEPROCESS PsInitialSystemProcess
Definition at line 115 of file psinit.c.
Referenced by ExSwapinWorkerThreads(), IopUnloadDriver(), MiAddMdlTracker(), MiAttachAndLockWorkingSet(), MiCcPutPagesInTransition(), MiDetachAndUnlockWorkingSet(), MiFreeMdlTracker(), MiLoadImageSection(), MiMapViewOfImageSection(), MiUpdateMdlTracker(), MiUpdateSystemPdes(), MiZeroAwePageWorker(), MiZeroInParallel(), MmCheckSystemImage(), MmInitializeHandBuiltProcess2(), MmUpdateMdlTracker(), NtDebugActiveProcess(), NtLoadDriver(), ObpAllocateObject(), ObpCaptureObjectCreateInformation(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObSetHandleAttributes(), ObShutdownSystem(), PsChargeProcessNonPagedPoolQuota(), PsChargeProcessPagedPoolQuota(), PsChargeProcessPageFileQuota(), PsChargeProcessPoolQuota(), PsChargeProcessQuota(), PsChargeSharedPoolQuota(), PsCreateSystemThread(), PsIsSystemProcess(), PspCreateProcess(), PspCreateThread(), PspFreezeProcessWorker(), PsReturnPoolQuota(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), PsReturnProcessPageFileQuota(), PsReturnProcessQuota(), PsShutdownSystem(), PsWaitForAllProcesses(), SepCleanupLUIDDeviceMapDirectory(), WmipCreateGuidObject(), and WmipOpenGuidObject().
LANGID PsInstallUILanguageId
Definition at line 55 of file create.c.
Referenced by CmGetSystemControlValues(), LdrpSearchResourceSection_U(), NtQueryDefaultUILanguage(), and NtQueryInstallUILanguage().
LIST_ENTRY PsLoadedModuleList
Definition at line 7966 of file sysload.c.
Referenced by IopInitializeBootLogging(), IopInitializeBuiltinDriver(), IopLoadDriver(), KevUtilAddressToFileHeader(), KiPcToFileHeader(), MiBuildImportsForBootDrivers(), MiCheckCacheAttributes(), MiDereferenceImports(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiGetHighestPteConsumer(), MiLookupDataTableEntry(), MiProcessLoaderEntry(), MiReleaseAllMemory(), MiResolveImageReferences(), MiShutdownSystem(), MiSnapThunk(), MmInitSystem(), MmLoadSystemImage(), NtQuerySystemInformation(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
ERESOURCE PsLoadedModuleResource
Definition at line 7967 of file sysload.c.
Referenced by IopInitializeBootLogging(), IopLoadDriver(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiProcessLoaderEntry(), MmGetSectionRange(), MmInitSystem(), MmLockPageableDataSection(), and NtQuerySystemInformation().
ALIGNED_SPINLOCK PsLoadedModuleSpinLock
Definition at line 94 of file hifreqlk.c.
Referenced by MiInitializeLoadedModuleList(), MiProcessLoaderEntry(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
const UNICODE_STRING PsNtDllPathName
Definition at line 32 of file psinit.c.
Referenced by DbgkCreateThread().
PVOID PsNtosImageBase
Definition at line 7952 of file sysload.c.
Referenced by MiInitializeLoadedModuleList().
ULONG PsPrioritySeparation
Definition at line 38 of file psinit.c.
Referenced by KiDeferredReadyThread(), PsChangeQuantumTable(), and PspComputeQuantumAndPriority().
ULONG PsRawPrioritySeparation
Definition at line 48 of file psinit.c.
SINGLE_LIST_ENTRY PsReaperListHead
Definition at line 129 of file psinit.c.
Referenced by KeTerminateThread(), and PspReaper().
WORK_QUEUE_ITEM PsReaperWorkItem
Definition at line 130 of file psinit.c.
Referenced by KeTerminateThread().
PVOID PsSystemDllBase
Definition at line 131 of file psinit.c.
Referenced by DbgkCreateThread().
ULONG PsThreadHits[THREAD_HIT_SLOTS]