Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/globalog.c File Reference
globalog.c File Reference
#include "wmikmp.h"
#include "ntos.h"
#include <evntrace.h>
#include "tracep.h"
Macros
#define DEFAULT_GLOBAL_DIRECTORY L"\\System32\\LogFiles\\WMI"
#define DEFAULT_GLOBAL_LOGFILE L"trace.log"
#define DEFAULT_GLOBAL_LOGFILE_ROOT L"%SystemRoot%"
#define DEFAULT_TRACE_GUID_NAME L"0811c1af-7a07-4a06-82ed-869455cdf713"
#define DOSDEVICES L"\\DosDevices\\"
#define MAX_ENABLE_FLAGS 10
#define MAX_REGKEYS 10
#define UNCDEVICES L"\\??\\UNC"
Functions
NTSTATUS WmipAddLogHeader (IN PWMI_LOGGER_CONTEXT LoggerContext, IN OUT PWMI_BUFFER_HEADER Buffer)
NTSTATUS WmipCreateDirectoryFile (IN PWCHAR DirFileName, IN BOOLEAN IsDirectory, OUT PHANDLE FileHandle, IN ULONG Append)
NTSTATUS WmipCreateNtFileName (IN PWCHAR strFileName, OUT PWCHAR *strNtFileName)
NTSTATUS WmipDelayCreate (OUT PHANDLE FileHandle, IN OUT PUNICODE_STRING FileName, IN ULONG Append)
NTSTATUS WmipQueryGLRegistryRoutine (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
VOID WmipStartGlobalLogger ()
Variables
SECURITY_DESCRIPTOR EtwpDefaultSecurityDescriptor
HANDLE EtwpPageLockHandle
Macro Definition Documentation
#define DEFAULT_GLOBAL_DIRECTORY L"\\System32\\LogFiles\\WMI"
Definition at line 30 of file globalog.c.
Referenced by WmipDelayCreate().
#define DEFAULT_GLOBAL_LOGFILE L"trace.log"
Definition at line 31 of file globalog.c.
Referenced by WmipDelayCreate().
#define DEFAULT_GLOBAL_LOGFILE_ROOT L"%SystemRoot%"
Definition at line 29 of file globalog.c.
Referenced by WmipDelayCreate(), and WmipStartGlobalLogger().
#define DEFAULT_TRACE_GUID_NAME L"0811c1af-7a07-4a06-82ed-869455cdf713"
Definition at line 32 of file globalog.c.
Referenced by WmipStartGlobalLogger().
#define DOSDEVICES L"\\DosDevices\\"
Definition at line 27 of file globalog.c.
Referenced by WmipCreateNtFileName().
#define MAX_ENABLE_FLAGS 10
Definition at line 26 of file globalog.c.
Referenced by WmipStartGlobalLogger().
#define MAX_REGKEYS 10
Definition at line 25 of file globalog.c.
Referenced by WmipStartGlobalLogger().
#define UNCDEVICES L"\\??\\UNC"
Definition at line 28 of file globalog.c.
Referenced by WmipCreateNtFileName().
Function Documentation
NTSTATUS WmipAddLogHeader (IN PWMI_LOGGER_CONTEXT LoggerContext, IN OUT PWMI_BUFFER_HEADER Buffer)
Definition at line 285 of file globalog.c.
References ALIGN_TO_POWER2, ASSERT, _ETHREAD::Cid, EVENT_TRACE_GROUP_HEADER, ExAllocatePoolWithTag, ExFreePool(), FALSE, _WMI_TRACE_PACKET::Group, HandleToUlong, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), KeBootTime, KeMaximumIncrement, KeNumberProcessors, KeQueryPerformanceCounter(), KeQuerySystemTime(), _SYSTEM_TRACE_HEADER::KernelTime, _KTHREAD::KernelTime, _SYSTEM_TRACE_HEADER::Marker, NonPagedPool, NtBuildNumber, NtMajorVersion, NtMinorVersion, NULL, _SYSTEM_TRACE_HEADER::Packet, PPerfGlobalGroupMask, PsGetCurrentThread(), PSLIST_ENTRY, PtrToUlong, _LARGE_INTEGER::QuadPart, RtlCopyMemory, RtlQueryTimeZoneInformation(), RtlZeroMemory, _WMI_TRACE_PACKET::Size, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_SUCCESS, SYSTEM_TRACE_MARKER, _SYSTEM_TRACE_HEADER::SystemTime, _ETHREAD::Tcb, _SYSTEM_TRACE_HEADER::ThreadId, TRACE_VERSION_MAJOR, TRACE_VERSION_MINOR, TraceDebug, TRACEPOOLTAG, TRUE, _WMI_TRACE_PACKET::Type, UNICODE_NULL, _CLIENT_ID::UniqueThread, _SYSTEM_TRACE_HEADER::UserTime, _KTHREAD::UserTime, WMI_BUFFER_FLAG_NORMAL, WMI_BUFFER_TYPE_RUNDOWN, WmipFlushBuffer(), WmipGetFreeBuffer(), WmipKernelLogger, WmipLoggerContext, WmipResetBufferHeader(), and WmiTraceAlignment.
Referenced by WmipSwitchToNewFile().
NTSTATUS WmipCreateDirectoryFile (IN PWCHAR DirFileName, IN BOOLEAN IsDirectory, OUT PHANDLE FileHandle, IN ULONG Append)
Definition at line 645 of file globalog.c.
References FILE_ATTRIBUTE_NORMAL, FILE_DIRECTORY_FILE, FILE_GENERIC_READ, FILE_GENERIC_WRITE, FILE_NO_INTERMEDIATE_BUFFERING, FILE_OPEN_IF, FILE_OVERWRITE_IF, FILE_SHARE_READ, FILE_SYNCHRONOUS_IO_NONALERT, FILE_WRITE_DATA, InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, RtlInitUnicodeString(), Status, STATUS_INVALID_PARAMETER, SYNCHRONIZE, TraceDebug, ZwClose(), and ZwCreateFile().
Referenced by WmipCreateLogFile(), WmipDelayCreate(), and WmiStartTrace().
NTSTATUS WmipCreateNtFileName (IN PWCHAR strFileName, OUT PWCHAR * strNtFileName)
Definition at line 714 of file globalog.c.
References DOSDEVICES, ExAllocatePoolWithTag, ExFreePool(), FAILED, NULL, PagedPool, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_SUCCESS, StringCbPrintfW(), TRACEPOOLTAG, UNCDEVICES, UNICODE_NULL, and wcslen().
Referenced by WmipCreateLogFile(), WmipDelayCreate(), and WmiStartTrace().
NTSTATUS WmipDelayCreate (OUT PHANDLE FileHandle, IN OUT PUNICODE_STRING FileName, IN ULONG Append)
Definition at line 532 of file globalog.c.
References _UNICODE_STRING::Buffer, DEFAULT_GLOBAL_DIRECTORY, DEFAULT_GLOBAL_LOGFILE, DEFAULT_GLOBAL_LOGFILE_ROOT, ExAllocatePoolWithTag, ExFreePool(), FAILED, FALSE, _UNICODE_STRING::Length, NT_SUCCESS, NtSystemRoot, NULL, PagedPool, RtlCompareUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, StringCbPrintfW(), TRACEPOOLTAG, TRUE, UNICODE_NULL, wcslen(), WmipCreateDirectoryFile(), and WmipCreateNtFileName().
Referenced by WmipSwitchToNewFile().
NTSTATUS WmipQueryGLRegistryRoutine (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
Definition at line 221 of file globalog.c.
References NULL, PAGED_CODE, REG_BINARY, REG_DWORD, REG_SZ, RtlCreateUnicodeString(), RtlMoveMemory, STATUS_SUCCESS, UNICODE_NULL, and UNREFERENCED_PARAMETER.
Referenced by WmipStartGlobalLogger().
VOID WmipStartGlobalLogger ()
Definition at line 64 of file globalog.c.
References DEFAULT_GLOBAL_LOGFILE_ROOT, DEFAULT_TRACE_GUID_NAME, _RTL_QUERY_REGISTRY_TABLE::DefaultData, _RTL_QUERY_REGISTRY_TABLE::DefaultType, _RTL_QUERY_REGISTRY_TABLE::EntryContext, EtwpDefaultSecurityDescriptor, EtwpDefaultTraceSecurityDescriptor, EtwpPageLockHandle, KeInitializeGuardedMutex(), KeNumberProcessors, _TRACE_ENABLE_FLAG_EXTENSION::Length, MAX_ENABLE_FLAGS, MAX_REGKEYS, MmLockPageableCodeSection, MmUnlockPageableImageSection(), _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, NullString, _TRACE_ENABLE_FLAG_EXTENSION::Offset, PAGE_SIZE, _RTL_QUERY_REGISTRY_TABLE::QueryRoutine, REG_BINARY, REG_DWORD, REG_SZ, RTL_REGISTRY_CONTROL, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlNtStatusToDosError(), RtlQueryRegistryValues(), RtlWriteRegistryValue(), RtlZeroMemory, STATUS_NO_MEMORY, STATUS_SUCCESS, UNICODE_NULL, WmipGetGuidSecurityDescriptor(), WmipQueryGLRegistryRoutine(), WmipReserveTraceBuffer(), WmipStartLogger(), WmipTraceGuardedMutex, and WNODE_FLAG_TRACED_GUID.
Referenced by WmipDriverEntry().
Variable Documentation
SECURITY_DESCRIPTOR EtwpDefaultSecurityDescriptor
Definition at line 51 of file globalog.c.
Referenced by WmipStartGlobalLogger().
HANDLE EtwpPageLockHandle
Definition at line 46 of file tracesup.c.
Referenced by WmipFreeLoggerContext(), WmipStartGlobalLogger(), and WmipStartLogger().