Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/lookup.c File Reference
lookup.c File Reference
#include "ntrtlp.h"
Functions
VOID RtlCaptureImageExceptionValues (IN PVOID Base, OUT PVOID *FunctionTable, OUT PULONG TableSize)
PVOID RtlLookupFunctionTable (IN PVOID ControlPc, OUT PVOID *ImageBase, OUT PULONG SizeOfTable)
Function Documentation
VOID RtlCaptureImageExceptionValues (IN PVOID Base, OUT PVOID * FunctionTable, OUT PULONG TableSize)
Definition at line 199 of file lookup.c.
References COMIMAGE_FLAGS_ILONLY, _IMAGE_OPTIONAL_HEADER::DllCharacteristics, IMAGE_COR20_HEADER::Flags, IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR, IMAGE_DIRECTORY_ENTRY_EXCEPTION, IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG, IMAGE_DLLCHARACTERISTICS_NO_SEH, LongToPtr, _IMAGE_NT_HEADERS::OptionalHeader, RTL_SIZEOF_THROUGH_FIELD, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), IMAGE_LOAD_CONFIG_DIRECTORY32::SEHandlerCount, IMAGE_LOAD_CONFIG_DIRECTORY32::SEHandlerTable, IMAGE_LOAD_CONFIG_DIRECTORY32::Size, and TRUE.
PVOID RtlLookupFunctionTable (IN PVOID ControlPc, OUT PVOID * ImageBase, OUT PULONG SizeOfTable)
Definition at line 312 of file lookup.c.
References CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireSpinLockAtDpcLevel, _KLDR_DATA_TABLE_ENTRY::ExceptionTable, _KLDR_DATA_TABLE_ENTRY::ExceptionTableSize, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), NULL, PsLoadedModuleList, PsLoadedModuleSpinLock, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, and SYNCH_LEVEL.
Referenced by RtlIsValidHandler(), RtlLookupFunctionEntry(), and RtlpLookupFunctionEntryForStackWalks().