Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obtype.c File Reference
obtype.c File Reference
#include "obp.h"
Data Structures
struct _OBJECT_TYPE_ARRAY
Macros
#define OBGETINFO_MAXFILENAME (260 * sizeof(WCHAR))
Typedefs
typedef struct _OBJECT_TYPE_ARRAY OBJECT_TYPE_ARRAY
typedef struct _OBJECT_TYPE_ARRAY * POBJECT_TYPE_ARRAY
Functions
NTSTATUS ObCreateObjectType (__in PUNICODE_STRING TypeName, __in POBJECT_TYPE_INITIALIZER ObjectTypeInitializer, __in_opt PSECURITY_DESCRIPTOR SecurityDescriptor, __out POBJECT_TYPE *ObjectType)
NTSTATUS ObEnumerateObjectsByType (IN POBJECT_TYPE ObjectType, IN OB_ENUM_OBJECT_TYPE_ROUTINE EnumerationRoutine, IN PVOID Parameter)
NTSTATUS ObGetObjectInformation (IN PCHAR UserModeBufferAddress, OUT PSYSTEM_OBJECTTYPE_INFORMATION ObjectInformation, IN ULONG Length, OUT PULONG ReturnLength OPTIONAL)
POBJECT_TYPE_ARRAY ObpCreateTypeArray (IN POBJECT_TYPE ObjectType)
VOID ObpDeleteObjectType (IN PVOID Object)
VOID ObpDestroyTypeArray (IN POBJECT_TYPE_ARRAY ObjectArray)
Macro Definition Documentation
#define OBGETINFO_MAXFILENAME (260 * sizeof(WCHAR))
Referenced by ObGetObjectInformation().
Typedef Documentation
typedef struct _OBJECT_TYPE_ARRAY OBJECT_TYPE_ARRAY
typedef struct _OBJECT_TYPE_ARRAY * POBJECT_TYPE_ARRAY
Function Documentation
NTSTATUS ObCreateObjectType (__in PUNICODE_STRING TypeName, __in POBJECT_TYPE_INITIALIZER ObjectTypeInitializer, __in_opt PSECURITY_DESCRIPTOR SecurityDescriptor, __out POBJECT_TYPE * ObjectType)
Definition at line 87 of file obtype.c.
References _OBJECT_HEADER::Body, _STRING::Buffer, _UNICODE_STRING::Buffer, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE::DefaultObject, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExAllocatePoolWithTag, ExFreePool(), ExInitializeResourceLite(), FALSE, FIELD_OFFSET, _OBJECT_HEADER::Flags, FLG_MAINTAIN_OBJECT_TYPELIST, _OBJECT_TYPE::Index, InitializeListHead(), InsertTailList(), KernelMode, _STRING::Length, _UNICODE_STRING::Length, _OBJECT_TYPE_INITIALIZER::MaintainTypeList, _UNICODE_STRING::MaximumLength, _OBJECT_TYPE::Mutex, _OBJECT_TYPE::Name, NonPagedPool, NT_SUCCESS, NtGlobalFlag, NULL, OB_FLAG_KERNEL_OBJECT, OB_FLAG_PERMANENT_OBJECT, OBJ_ALL_VALID_ATTRIBUTES, OBJ_CASE_INSENSITIVE, OBJ_NAME_PATH_SEPARATOR, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_LOCK_COUNT, _OBJECT_TYPE::ObjectLocks, OBP_MAX_DEFINED_OBJECT_TYPES, ObpAllocateObject(), ObpDefaultObject, ObpEnterObjectTypeMutex, ObpInitializeLookupContext(), ObpInsertDirectoryEntry(), ObpLeaveObjectTypeMutex, ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpObjectTypes, ObpReleaseLookupContext(), ObpTypeDirectoryObject, ObpTypeObjectType, ObpValidateIrql, ObReferenceObject, PagedPool, PERFINFO_INITIALIZE_OBJECT_ALLOCATED_TYPE_LIST_HEAD, _OBJECT_TYPE_INITIALIZER::PoolType, RtlCopyUnicodeString(), RtlUnicodeStringToAnsiString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SeDefaultObjectMethod(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, SYNCHRONIZE, _OBJECT_TYPE::TotalNumberOfObjects, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_HEADER_CREATOR_INFO::TypeList, ULongToPtr, UNREFERENCED_PARAMETER, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, and wcscmp().
Referenced by CmpCreateObjectTypes(), DbgkInitialize(), ExpEventInitialization(), ExpEventPairInitialization(), ExpInitializeCallbacks(), ExpKeyedEventInitialization(), ExpMutantInitialization(), ExpProfileInitialization(), ExpSemaphoreInitialization(), ExpTimerInitialization(), ExpWin32Initialization(), IopCreateObjectTypes(), LpcInitSystem(), MiSectionInitialization(), ObInitSystem(), PspInitPhase0(), SepTokenInitialization(), and WmipInitializeSecurity().
NTSTATUS ObEnumerateObjectsByType (IN POBJECT_TYPE ObjectType, IN OB_ENUM_OBJECT_TYPE_ROUTINE EnumerationRoutine, IN PVOID Parameter)
Definition at line 543 of file obtype.c.
References _OBJECT_HEADER::Body, _OBJECT_TYPE_ARRAY::CreatorInfoArray, _OBJECT_HEADER::HandleCount, _OBJECT_HEADER_NAME_INFO::Name, NULL, OBJECT_HEADER_TO_NAME_INFO(), ObpCreateTypeArray(), ObpDestroyTypeArray(), _OBJECT_HEADER::PointerCount, RtlZeroMemory, _OBJECT_TYPE_ARRAY::Size, Status, STATUS_NO_MORE_ENTRIES, and STATUS_SUCCESS.
NTSTATUS ObGetObjectInformation (IN PCHAR UserModeBufferAddress, OUT PSYSTEM_OBJECTTYPE_INFORMATION ObjectInformation, IN ULONG Length, OUT PULONG ReturnLength OPTIONAL)
Definition at line 872 of file obtype.c.
References ARGUMENT_PRESENT, _OBJECT_HEADER::Body, _OBJECT_HEADER_CREATOR_INFO::CreatorBackTraceIndex, _OBJECT_TYPE_ARRAY::CreatorInfoArray, _OBJECT_HEADER_CREATOR_INFO::CreatorUniqueProcess, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExAllocatePoolWithTag, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, ExFastRefGetObject(), ExFreePoolWithTag, FALSE, FIELD_OFFSET, _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HEADER::HandleCount, _OBJECT_TYPE::Index, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, IoFileObjectType, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NT_SUCCESS, NULL, OBGETINFO_MAXFILENAME, OBJECT_HEADER_TO_QUOTA_INFO(), ObpCreateTypeArray(), ObpDestroyTypeArray(), ObpTypeObjectType, ObQueryNameString(), ObQueryTypeName(), PAGED_CODE, PagedPool, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, _OBJECT_HEADER::PointerCount, _OBJECT_TYPE_INITIALIZER::PoolType, _OBJECT_TYPE_INITIALIZER::QueryNameProcedure, RtlInitUnicodeString(), RtlMoveMemory, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityRequired, _OBJECT_TYPE_ARRAY::Size, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _OBJECT_TYPE::TotalNumberOfHandles, _OBJECT_TYPE::TotalNumberOfObjects, TRUE, TYPE_ALIGNMENT, _OBJECT_TYPE::TypeInfo, UNICODE_NULL, _EPROCESS::UniqueProcessId, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpGetObjectInformation().
POBJECT_TYPE_ARRAY ObpCreateTypeArray (IN POBJECT_TYPE ObjectType)
Definition at line 670 of file obtype.c.
References ASSERT, _OBJECT_HEADER::Body, CONTAINING_RECORD, Count, _OBJECT_TYPE_ARRAY::CreatorInfoArray, ExAllocatePoolWithTag, _LIST_ENTRY::Flink, NULL, ObpEnterObjectTypeMutex, ObpLeaveObjectTypeMutex, ObReferenceObjectSafe(), PagedPool, and _OBJECT_TYPE_ARRAY::Size.
Referenced by ObEnumerateObjectsByType(), and ObGetObjectInformation().
VOID ObpDeleteObjectType (IN PVOID Object)
Definition at line 499 of file obtype.c.
References ExDeleteResourceLite(), _OBJECT_TYPE::Mutex, OBJECT_LOCK_COUNT, and _OBJECT_TYPE::ObjectLocks.
Referenced by ObInitSystem().
VOID ObpDestroyTypeArray (IN POBJECT_TYPE_ARRAY ObjectArray)
Definition at line 807 of file obtype.c.
References _OBJECT_HEADER::Body, ExFreePoolWithTag, NULL, and ObDereferenceObject().
Referenced by ObEnumerateObjectsByType(), and ObGetObjectInformation().