Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/profile.c File Reference
profile.c File Reference
#include "exp.h"
Data Structures
struct _EPROFILE
Macros
#define ACTIVE_PROFILE_LIMIT 8
Typedefs
typedef struct _EPROFILE EPROFILE
typedef struct _EPROFILE * PEPROFILE
Functions
VOID ExpProfileDelete (IN PVOID Object)
BOOLEAN ExpProfileInitialization (VOID)
NTSTATUS NtCreateProfile (__out PHANDLE ProfileHandle, __in HANDLE Process OPTIONAL, __in PVOID RangeBase, __in SIZE_T RangeSize, __in ULONG BucketSize, __in PULONG Buffer, __in ULONG BufferSize, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY Affinity)
NTSTATUS NtQueryIntervalProfile (__in KPROFILE_SOURCE ProfileSource, __out PULONG Interval)
NTSTATUS NtQueryPerformanceCounter (__out PLARGE_INTEGER PerformanceCounter, __out_opt PLARGE_INTEGER PerformanceFrequency)
NTSTATUS NtSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
NTSTATUS NtStartProfile (__in HANDLE ProfileHandle)
NTSTATUS NtStopProfile (__in HANDLE ProfileHandle)
Variables
const ULONG ExpCurrentProfileUsage = 0
const GENERIC_MAPPING ExpProfileMapping
KMUTEX ExpProfileStateMutex
POBJECT_TYPE ExProfileObjectType
Macro Definition Documentation
#define ACTIVE_PROFILE_LIMIT 8
Definition at line 70 of file profile.c.
Referenced by NtStartProfile().
Typedef Documentation
typedef struct _EPROFILE EPROFILE
typedef struct _EPROFILE * PEPROFILE
Function Documentation
VOID ExpProfileDelete (IN PVOID Object)
Definition at line 150 of file profile.c.
References ASSERT, CONTAINING_RECORD, ExFreePool(), FALSE, KeStopProfile(), _EPROFILE::LockedBufferAddress, _EPROFILE::Mdl, MmUnlockPages(), MmUnmapLockedPages(), NULL, ObDereferenceObject(), _EPROFILE::Process, and _EPROFILE::ProfileObject.
Referenced by ExpProfileInitialization().
BOOLEAN ExpProfileInitialization (VOID)
Definition at line 82 of file profile.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExpProfileDelete(), ExpProfileMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KeInitializeMutex(), _OBJECT_TYPE_INITIALIZER::Length, MUTEX_LEVEL_EX_PROFILE, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, PROFILE_ALL_ACCESS, RtlInitUnicodeString(), RtlZeroMemory, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
NTSTATUS NtCreateProfile (__out PHANDLE ProfileHandle, __in HANDLE Process OPTIONAL, __in PVOID RangeBase, __in SIZE_T RangeSize, __in ULONG BucketSize, __in PULONG Buffer, __in ULONG BufferSize, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY Affinity)
Definition at line 204 of file profile.c.
References _EPROFILE::Affinity, ARGUMENT_PRESENT, _EPROFILE::BucketSize, _EPROFILE::Buffer, _EPROFILE::BufferSize, DbgPrint(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, Handle, InitializeObjectAttributes, KeGetPreviousMode, KernelMode, _EPROFILE::LockedBufferAddress, MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_EXCLUSIVE, ObReferenceObjectByHandle, _EPROCESS::Pcb, ProbeForWrite(), ProbeForWriteHandle, _EPROFILE::Process, PROCESS_QUERY_INFORMATION, PROFILE_CONTROL, _EPROFILE::ProfileSource, PsProcessType, _EPROFILE::RangeBase, _EPROFILE::RangeSize, _EPROFILE::Segment, SeSinglePrivilegeCheck(), SeSystemProfilePrivilege, Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_7, and STATUS_PRIVILEGE_NOT_HELD.
NTSTATUS NtQueryIntervalProfile (__in KPROFILE_SOURCE ProfileSource, __out PULONG Interval)
Definition at line 757 of file profile.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeQueryIntervalProfile(), KernelMode, NOTHING, ProbeForWriteUlong, and STATUS_SUCCESS.
NTSTATUS NtQueryPerformanceCounter (__out PLARGE_INTEGER PerformanceCounter, __out_opt PLARGE_INTEGER PerformanceFrequency)
Definition at line 821 of file profile.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeQueryPerformanceCounter(), KernelMode, ProbeForWriteSmallStructure(), and STATUS_SUCCESS.
NTSTATUS NtSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
Definition at line 730 of file profile.c.
References KeSetIntervalProfile(), and STATUS_SUCCESS.
NTSTATUS NtStartProfile (__in HANDLE ProfileHandle)
Definition at line 499 of file profile.c.
References ACTIVE_PROFILE_LIMIT, _EPROFILE::Affinity, ASSERT, _EPROFILE::BucketSize, _EPROFILE::Buffer, _EPROFILE::BufferSize, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExpCurrentProfileUsage, FALSE, IoWriteAccess, KeGetPreviousMode, KeInitializeProfile(), KeReleaseMutex(), KernelMode, KeStartProfile(), KeWaitForSingleObject(), _EPROFILE::LockedBufferAddress, _EPROFILE::Mdl, MmCached, MmInitializeMdl, MmMapLockedPagesSpecifyCache(), MmProbeAndLockPages(), MmSizeOfMdl(), MmUnlockPages(), NonPagedPool, NormalPagePriority, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _EPROFILE::Process, PROFILE_CONTROL, _EPROFILE::ProfileObject, ProfileObject, _EPROFILE::ProfileSource, _EPROFILE::RangeBase, _EPROFILE::RangeSize, _EPROFILE::Segment, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PROFILING_AT_LIMIT, STATUS_PROFILING_NOT_STOPPED, and STATUS_SUCCESS.
NTSTATUS NtStopProfile (__in HANDLE ProfileHandle)
Definition at line 651 of file profile.c.
References ASSERT, Executive, ExFreePool(), FALSE, KeGetPreviousMode, KeReleaseMutex(), KernelMode, KeStopProfile(), KeWaitForSingleObject(), _EPROFILE::LockedBufferAddress, _EPROFILE::Mdl, MmUnlockPages(), MmUnmapLockedPages(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PROFILE_CONTROL, _EPROFILE::ProfileObject, ProfileObject, Status, STATUS_PROFILING_NOT_STARTED, and STATUS_SUCCESS.
Variable Documentation
const ULONG ExpCurrentProfileUsage = 0
Definition at line 53 of file profile.c.
Referenced by NtStartProfile().
const GENERIC_MAPPING ExpProfileMapping
Initial value:
= {
    STANDARD_RIGHTS_READ | PROFILE_CONTROL,
    STANDARD_RIGHTS_WRITE | PROFILE_CONTROL,
    STANDARD_RIGHTS_EXECUTE | PROFILE_CONTROL,
    PROFILE_ALL_ACCESS
}
Definition at line 59 of file profile.c.
Referenced by ExpProfileInitialization().
KMUTEX ExpProfileStateMutex
Definition at line 47 of file profile.c.
POBJECT_TYPE ExProfileObjectType
Definition at line 45 of file profile.c.