Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/timersup.c File Reference
timersup.c File Reference
#include "ki.h"
Functions
VOID FASTCALL KiCompleteTimer (__inout PKTIMER Timer, __inout PKSPIN_LOCK_QUEUE LockQueue)
LOGICAL FASTCALL KiInsertTimerTable (IN PKTIMER Timer, IN ULONG Hand)
BOOLEAN FASTCALL KiSignalTimer (__inout PKTIMER Timer)
Function Documentation
VOID FASTCALL KiCompleteTimer (__inout PKTIMER Timer, __inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 24 of file timersup.c.
References _LIST_ENTRY::Blink, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, KiLockDispatcherDatabaseAtSynchLevel, KiReleaseTimerTableLock(), KiRemoveEntryTimer(), KiRequestSoftwareInterrupt, KiSignalTimer(), KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
Referenced by KiInsertOrSignalTimer().
LOGICAL FASTCALL KiInsertTimerTable (IN PKTIMER Timer, IN ULONG Hand)
Definition at line 96 of file timersup.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _KTIMER::DueTime, _KTIMER_TABLE_ENTRY::Entry, FALSE, InsertHeadList(), KeMemoryBarrier(), KiComputeTimerTableIndex(), KiQueryInterruptTime, KiTimerTableListHead, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, _KTIMER_TABLE_ENTRY::Time, and TRUE.
Referenced by KeSetSystemTime(), KiInsertOrSignalTimer(), and KiInsertTreeTimer().
BOOLEAN FASTCALL KiSignalTimer (__inout PKTIMER Timer)
Definition at line 199 of file timersup.c.
References FALSE, _LARGE_INTEGER::HighPart, Int32x32To64, IsListEmpty, KeInsertQueueDpc(), KiInsertTreeTimer(), KiQuerySystemTime, KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), _LARGE_INTEGER::LowPart, NULL, _LARGE_INTEGER::QuadPart, TIMER_EXPIRE_INCREMENT, TimerNotificationObject, TRUE, and ULongToPtr.
Referenced by KeSetTimerEx(), and KiCompleteTimer().