Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/waitsup.c File Reference
waitsup.c File Reference
#include "ki.h"
Functions
VOID FASTCALL KiExitDispatcher (IN KIRQL OldIrql)
VOID FASTCALL KiUnwaitThread (IN PRKTHREAD Thread, IN LONG_PTR WaitStatus, IN KPRIORITY Increment)
VOID FASTCALL KiWaitTest (IN PVOID Object, IN KPRIORITY Increment)
Function Documentation
VOID FASTCALL KiExitDispatcher (IN KIRQL OldIrql)
Definition at line 25 of file waitsup.c.
References APC_LEVEL, ASSERT, _KPRCB::CurrentThread, _KPRCB::DeferredReadyListHead, DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, FALSE, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KernelMode, KiAcquirePrcbLock(), KiDeliverApc(), KiProcessDeferredReadyList(), KiRequestSoftwareInterrupt, KiSetContextSwapBusy(), KiSwapContext(), KxQueueReadyThread(), _SINGLE_LIST_ENTRY::Next, _KPRCB::NextThread, NULL, Running, _KTHREAD::State, SYNCH_LEVEL, and _KTHREAD::WaitIrql.
Referenced by KeAlertResumeThread(), KeAlertThread(), KeDetachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertHeadQueue(), KeInsertQueue(), KeInsertQueueApc(), KeRemoveQueue(), KeResumeThread(), KeRundownQueue(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeSetTimerEx(), KeSignalGateBoostPriority(), KeSuspendThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KiAdjustQuantumThread(), KiAttachProcess(), and KiUnlockDispatcherDatabase().
VOID FASTCALL KiUnwaitThread (IN PRKTHREAD Thread, IN LONG_PTR WaitStatus, IN KPRIORITY Increment)
Definition at line 116 of file waitsup.c.
References AdjustUnwait, ASSERT, KiReadyThread(), and KiUnlinkThread().
Referenced by KeAlertResumeThread(), KeAlertThread(), KiActivateWaiterQueue(), KiInsertQueueApc(), KiSetInternalEvent(), KiWaitTest(), KiWaitTestSynchronizationObject(), and KiWaitTestWithoutSideEffects().
VOID FASTCALL KiWaitTest (IN PVOID Object, IN KPRIORITY Increment)
Definition at line 173 of file waitsup.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, _KEVENT::Header, KiUnwaitThread(), KiWaitSatisfyAny, _DISPATCHER_HEADER::SignalState, STATUS_KERNEL_APC, _KWAIT_BLOCK::Thread, WaitAny, _KWAIT_BLOCK::WaitKey, _DISPATCHER_HEADER::WaitListHead, and _KWAIT_BLOCK::WaitType.
Referenced by KeAlertResumeThread(), KeForceResumeThread(), KePulseEvent(), KeReleaseMutant(), KeReleaseSemaphore(), KeResumeThread(), KeRundownThread(), and KeThawAllThreads().