Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/consumer.c File Reference
consumer.c File Reference
#include "wmikmp.h"
#include <evntrace.h>
#include <ntcsrmsg.h>
#include <strsafe.h>
Data Structures
struct _BASE_API_MSG
struct _BASE_CREATETHREAD_MSG
Macros
#define BasepRegisterThread 29
#define IRP_OBJECT_LIST_HEAD(Irp) (PLIST_ENTRY)((Irp)->Tail.Overlay.DriverContext)
#define MANY_NOTIFICATION_OBJECTS 16
#define MANYPROVIDERIDS 16
#define STRSAFE_NO_DEPRECATE
#define WmipHaveHiPriorityEvent(Object)
#define WmipHaveLoPriorityEvent(Object)
#define WmipQueueEventToObject(Object, Wnode, IsHighPriority)
#define WmipSetHighWord(a, b)
Typedefs
typedef struct _BASE_API_MSG BASE_API_MSG
typedef struct _BASE_CREATETHREAD_MSG BASE_CREATETHREAD_MSG
typedef struct _BASE_API_MSG * PBASE_API_MSG
typedef struct _BASE_CREATETHREAD_MSG * PBASE_CREATETHREAD_MSG
Functions
NTSTATUS WmipAddProviderIdToPIList (PBINSTANCESET **PIPtrPtr, PULONG PICountPtr, PULONG PIMaxPtr, PBINSTANCESET *StaticPIPtr, PBINSTANCESET InstanceSet)
void WmipClearIrpObjectList (PIRP Irp)
void WmipClearObjectFromThreadList (PWMIGUIDOBJECT Object)
void WmipClearThreadObjectList (PWMIGUIDOBJECT MainObject)
void WmipCompleteGuidIrpWithError (PWMIGUIDOBJECT GuidObject)
void WmipCopyFromEventQueues (IN POBJECT_EVENT_INFO ObjectArray, IN ULONG HandleCount, OUT PUCHAR OutBuffer, OUT ULONG *OutBufferSizeUsed, OUT PWNODE_HEADER *LastWnode, IN BOOLEAN IsHiPriority)
NTSTATUS WmipCreatePumpThread (PWMIGUIDOBJECT Object)
void WmipCreatePumpThreadRoutine (PVOID Context)
NTSTATUS WmipCreateUMLogger (IN OUT PWMICREATEUMLOGGER CreateInfo)
NTSTATUS WmipCsrClientMessageServer (IN PVOID CsrPort, IN OUT PCSR_API_MSG m, IN CSR_API_NUMBER ApiNumber, IN ULONG ArgLength)
PWNODE_HEADER WmipDereferenceEvent (PWNODE_HEADER Wnode)
NTSTATUS WmipEnumerateGuids (ULONG Ioctl, PWMIGUIDLISTINFO GuidList, ULONG MaxBufferSize, ULONG *OutBufferSize)
void WmipGetGuidPropertiesFromGuidEntry (PWMIGUIDPROPERTIES GuidInfo, PGUIDENTRY GuidEntry)
PWNODE_HEADER WmipIncludeStaticNames (PWNODE_HEADER Wnode)
void WmipInsertStaticNames (PWNODE_ALL_DATA Wnode, ULONG MaxWnodeSize, PBINSTANCESET InstanceSet)
BOOLEAN WmipIsQuerySetGuid (PBGUIDENTRY GuidEntry)
NTSTATUS WmipMarkHandleAsClosed (HANDLE Handle)
NTSTATUS WmipMBReply (IN HANDLE RequestHandle, IN ULONG ReplyIndex, IN PUCHAR Message, IN ULONG MessageSize)
void WmipNotificationIrpCancel (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS WmipOpenBlock (IN ULONG Ioctl, IN KPROCESSOR_MODE AccessMode, IN POBJECT_ATTRIBUTES CapturedObjectAttributes, IN ULONG DesiredAccess, OUT PHANDLE Handle)
NTSTATUS WmipPrepareForWnodeAD (IN PWMIGUIDOBJECT GuidObject, OUT LPGUID Guid, IN OUT ULONG *ProviderIdCount, OUT PBINSTANCESET **ProviderIdList, OUT BOOLEAN *InternalGuid)
NTSTATUS WmipPrepareWnodeSI (IN PWMIGUIDOBJECT GuidObject, IN OUT PWNODE_SINGLE_INSTANCE WnodeSI, IN OUT ULONG *ProviderIdCount, OUT PBINSTANCESET **ProviderIdList, OUT BOOLEAN *IsDynamic, OUT BOOLEAN *InternalGuid)
NTSTATUS WmipProcessEvent (PWNODE_HEADER InWnode, BOOLEAN IsHighPriority, BOOLEAN FreeBuffer)
VOID WmipPumpThreadApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
NTSTATUS WmipQueryAllData (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN PWNODE_ALL_DATA Wnode, IN ULONG OutBufferLen, OUT PULONG RetSize)
NTSTATUS WmipQueryAllDataMultiple (IN ULONG ObjectCount, IN PWMIGUIDOBJECT *ObjectList, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQADMULTIPLE QadMultiple, OUT ULONG *ReturnSize)
NTSTATUS WmipQueryGuidInfo (IN OUT PWMIQUERYGUIDINFO QueryGuidInfo)
NTSTATUS WmipQuerySetExecuteSI (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN UCHAR MinorFunction, IN OUT PWNODE_HEADER Wnode, IN ULONG OutBufferSize, OUT PULONG RetSize)
NTSTATUS WmipQuerySingleMultiple (IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQSIMULTIPLE QsiMultiple, IN ULONG QueryCount, IN PWMIGUIDOBJECT *ObjectList, IN PUNICODE_STRING InstanceNames, OUT ULONG *ReturnSize)
NTSTATUS WmipQueueNotification (PWMIGUIDOBJECT Object, PWMIEVENTQUEUE EventQueue, PWNODE_HEADER Wnode)
NTSTATUS WmipReceiveNotifications (PWMIRECEIVENOTIFICATION ReceiveNotification, PULONG OutBufferSize, PIRP Irp)
NTSTATUS WmipRegisterUMGuids (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Cookie, IN PWMIREGINFO RegInfo, IN ULONG RegInfoSize, OUT HANDLE *RequestHandle, OUT ULONG64 *LoggerContext)
ULONG WmipStaticInstanceNameSize (PBINSTANCESET InstanceSet)
NTSTATUS WmipUMProviderCallback (IN WMIACTIONCODE ActionCode, IN PVOID DataPath, IN ULONG BufferSize, IN OUT PVOID Buffer)
NTSTATUS WmipUnregisterGuids (PWMIUNREGGUIDS UnregGuids)
NTSTATUS WmipWriteMBToObject (IN PWMIGUIDOBJECT RequestObject, IN PWMIGUIDOBJECT ReplyObject, IN PUCHAR Message, IN ULONG MessageSize)
NTSTATUS WmipWriteMessageToGuid (IN PBGUIDENTRY GuidEntry, IN PWMIGUIDOBJECT ReplyObject, IN PUCHAR Message, IN ULONG MessageSize, OUT PULONG WrittenCount)
NTSTATUS WmipWriteWnodeToObject (PWMIGUIDOBJECT Object, PWNODE_HEADER Wnode, BOOLEAN IsHighPriority)
Variables
const ACCESS_MASK DesiredAccessForFunction []
Macro Definition Documentation
#define BasepRegisterThread 29
Definition at line 3253 of file consumer.c.
Referenced by WmipPumpThreadApc().
#define IRP_OBJECT_LIST_HEAD (Irp) (PLIST_ENTRY)((Irp)->Tail.Overlay.DriverContext)
Definition at line 2333 of file consumer.c.
Referenced by WmipClearIrpObjectList(), and WmipReceiveNotifications().
#define MANY_NOTIFICATION_OBJECTS 16
Referenced by WmipReceiveNotifications().
#define MANYPROVIDERIDS 16
Definition at line 855 of file consumer.c.
Referenced by WmipQueryAllData(), and WmipQuerySetExecuteSI().
#define STRSAFE_NO_DEPRECATE
Definition at line 24 of file consumer.c.
#define WmipHaveHiPriorityEvent (Object)
Value:
(((Object)->HiPriority.Buffer != NULL) &&  \
       ((Object)->HiPriority.NextOffset != 0))
Definition at line 2474 of file consumer.c.
Referenced by WmipReceiveNotifications().
#define WmipHaveLoPriorityEvent (Object)
Value:
(((Object)->LoPriority.Buffer != NULL) &&  \
       ((Object)->LoPriority.NextOffset != 0))
Definition at line 2478 of file consumer.c.
Referenced by WmipReceiveNotifications().
#define WmipQueueEventToObject (Object, Wnode, IsHighPriority)
Value:
WmipQueueNotification(Object, IsHighPriority ? &Object->HiPriority : \
                                         &Object->LoPriority, \
                          Wnode);
Definition at line 3480 of file consumer.c.
Referenced by WmipWriteWnodeToObject().
#define WmipSetHighWord (a, b)
Value:
(a) &= ~(0xffff0000); \
    (a) |= ( (USHORT)(b) << 16)
Definition at line 2482 of file consumer.c.
Referenced by WmipCopyFromEventQueues().
Typedef Documentation
typedef struct _BASE_API_MSG BASE_API_MSG
typedef struct _BASE_CREATETHREAD_MSG BASE_CREATETHREAD_MSG
typedef struct _BASE_API_MSG * PBASE_API_MSG
typedef struct _BASE_CREATETHREAD_MSG * PBASE_CREATETHREAD_MSG
Function Documentation
NTSTATUS WmipAddProviderIdToPIList (PBINSTANCESET ** PIPtrPtr, PULONG PICountPtr, PULONG PIMaxPtr, PBINSTANCESET * StaticPIPtr, PBINSTANCESET InstanceSet)
Definition at line 423 of file consumer.c.
References memcpy(), NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, WmipAlloc, WmipFree, and WmipUnreferenceIS.
Referenced by WmipPrepareForWnodeAD(), and WmipPrepareWnodeSI().
void WmipClearIrpObjectList (PIRP Irp)
Definition at line 2335 of file consumer.c.
References CONTAINING_RECORD, _WMIGUIDOBJECT::EventQueueAction, _LIST_ENTRY::Flink, _WMIGUIDOBJECT::Irp, IRP_OBJECT_LIST_HEAD, NULL, PAGED_CODE, RECEIVE_ACTION_NONE, RemoveEntryList(), and WmipAssert.
Referenced by WmipCompleteGuidIrpWithError(), WmipDeleteMethod(), WmipNotificationIrpCancel(), and WmipWriteWnodeToObject().
void WmipClearObjectFromThreadList (PWMIGUIDOBJECT Object)
Definition at line 2370 of file consumer.c.
References DPFLTR_WMICORE_ID, _WMIGUIDOBJECT::EventQueueAction, InitializeListHead(), IsListEmpty, NULL, PAGED_CODE, RECEIVE_ACTION_NONE, RemoveEntryList(), _WMIGUIDOBJECT::ThreadObjectList, _WMIGUIDOBJECT::UserModeCallback, _WMIGUIDOBJECT::UserModeProcess, WmipDebugPrintEx, and ZwClose().
Referenced by WmipClearThreadObjectList(), WmipDeleteMethod(), and WmipReceiveNotifications().
void WmipClearThreadObjectList (PWMIGUIDOBJECT MainObject)
Definition at line 2400 of file consumer.c.
References CONTAINING_RECORD, _WMIGUIDOBJECT::EventQueueAction, _LIST_ENTRY::Flink, IsListEmpty, PAGED_CODE, RECEIVE_ACTION_CREATE_THREAD, _WMIGUIDOBJECT::ThreadObjectList, _WMIGUIDOBJECT::UserModeCallback, _WMIGUIDOBJECT::UserModeProcess, WmipAssert, and WmipClearObjectFromThreadList().
Referenced by WmipCreatePumpThread().
void WmipCompleteGuidIrpWithError (PWMIGUIDOBJECT GuidObject)
Definition at line 2640 of file consumer.c.
References _LIST_ENTRY::Blink, _LIST_ENTRY::Flink, IO_NO_INCREMENT, IoCompleteRequest(), IoSetCancelRoutine, _WMIGUIDOBJECT::Irp, _WMIGUIDOBJECT::IrpObjectList, NULL, PAGED_CODE, PIRP, STATUS_INVALID_HANDLE, WmipAssert, and WmipClearIrpObjectList().
Referenced by WmipMarkHandleAsClosed(), and WmipReceiveNotifications().
void WmipCopyFromEventQueues (IN POBJECT_EVENT_INFO ObjectArray, IN ULONG HandleCount, OUT PUCHAR OutBuffer, OUT ULONG * OutBufferSizeUsed, OUT PWNODE_HEADER * LastWnode, IN BOOLEAN IsHiPriority)
Definition at line 2486 of file consumer.c.
References WMIEVENTQUEUE::Buffer, _WNODE_HEADER::BufferSize, _WMIGUIDOBJECT::Event, WMIEVENTQUEUE::EventsLost, _WMIGUIDOBJECT::HiPriority, KeClearEvent(), WMIEVENTQUEUE::LastWnode, _WNODE_HEADER::Linkage, _WMIGUIDOBJECT::LoPriority, WMIEVENTQUEUE::NextOffset, NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, RtlCopyMemory, _WNODE_HEADER::TimeStamp, WmipAssert, WmipFree, and WmipSetHighWord.
Referenced by WmipReceiveNotifications().
NTSTATUS WmipCreatePumpThread (PWMIGUIDOBJECT Object)
Definition at line 3326 of file consumer.c.
References DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, ExFreePool(), KeInitializeApc(), KeInsertQueueApc(), KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OriginalApcEnvironment, PAGED_CODE, RtlCreateUserThread(), _WMIGUIDOBJECT::StackCommit, _WMIGUIDOBJECT::StackSize, Status, STATUS_SUCCESS, TRUE, _WMIGUIDOBJECT::UserModeCallback, _WMIGUIDOBJECT::UserModeProcess, WmipAllocNP, WmipClearThreadObjectList(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipLeaveSMCritSection, WmipPumpThreadApc(), ZwClose(), and ZwResumeThread().
Referenced by WmipCreatePumpThreadRoutine(), and WmipQueueNotification().
void WmipCreatePumpThreadRoutine (PVOID Context)
Definition at line 3431 of file consumer.c.
References DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, ExFreePool(), NT_SUCCESS, ObDereferenceObject(), CREATETHREADWORKITEM::Object, ObReferenceObjectSafe(), PAGED_CODE, Status, WmipCreatePumpThread(), and WmipDebugPrintEx.
Referenced by WmipQueueNotification().
NTSTATUS WmipCreateUMLogger (IN OUT PWMICREATEUMLOGGER CreateInfo)
Definition at line 4714 of file consumer.c.
References _WNODE_HEADER::BufferSize, FALSE, _WMIGUIDOBJECT::Flags, InitializeListHead(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _WMIGUIDOBJECT::RequestListHead, Status, STATUS_WMI_INSTANCE_NOT_FOUND, UserMode, WMIGUID_FLAG_REPLY_OBJECT, WmiGuidObjectNameLength, WmipFindGEByGuid(), WmipIsControlGuid, WmipOpenGuidObject(), WmipProbeAndCaptureGuidObjectAttributes(), WmipUnreferenceGE, WmipWriteMessageToGuid(), and ZwClose().
Referenced by WmipIoControl().
NTSTATUS WmipCsrClientMessageServer (IN PVOID CsrPort, IN OUT PCSR_API_MSG m, IN CSR_API_NUMBER ApiNumber, IN ULONG ArgLength)
Definition at line 3154 of file consumer.c.
References DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, FALSE, FIELD_OFFSET, LpcRequestPort(), NT_SUCCESS, NtCurrentTeb(), NULL, Status, WmipAssert, and WmipDebugPrintEx.
Referenced by WmipPumpThreadApc().
PWNODE_HEADER WmipDereferenceEvent (PWNODE_HEADER Wnode)
Definition at line 3645 of file consumer.c.
References _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, EVENTLOG_WARNING_TYPE, FIELD_OFFSET, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, tagWNODE_SINGLE_INSTANCE::InstanceIndex, IRP_MN_QUERY_SINGLE_INSTANCE, memcpy(), memset(), NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, _WNODE_HEADER::ProviderId, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, tagWNODE_EVENT_REFERENCE::TargetDataBlockSize, tagWNODE_EVENT_REFERENCE::TargetGuid, tagWNODE_EVENT_REFERENCE::TargetInstanceIndex, tagWNODE_EVENT_REFERENCE::TargetInstanceName, _WNODE_HEADER::Version, WmipAllocNP, WmipDebugPrintEx, WmipDeliverWnodeToDS(), WmipFindDSByProviderId(), WmipFree, WmipReportEventLog, WmipUnreferenceDS, WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SEVERITY_MASK, WNODE_FLAG_SINGLE_INSTANCE, WNODE_FLAG_STATIC_INSTANCE_NAMES, WNODE_FLAG_TOO_SMALL, tagWNODE_SINGLE_INSTANCE::WnodeHeader, and tagWNODE_EVENT_REFERENCE::WnodeHeader.
Referenced by WmipProcessEvent().
NTSTATUS WmipEnumerateGuids (ULONG Ioctl, PWMIGUIDLISTINFO GuidList, ULONG MaxBufferSize, ULONG * OutBufferSize)
Definition at line 2175 of file consumer.c.
References CONTAINING_RECORD, FIELD_OFFSET, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, WMIGUIDPROPERTIES::Guid, WMIGUIDLISTINFO::GuidList, IOCTL_WMI_ENUMERATE_GUIDS_AND_PROPERTIES, PAGED_CODE, WMIGUIDLISTINFO::ReturnedGuidCount, STATUS_SUCCESS, WMIGUIDLISTINFO::TotalGuidCount, WmipEnterSMCritSection, WmipGEHeadPtr, WmipGetGuidPropertiesFromGuidEntry(), and WmipLeaveSMCritSection.
Referenced by WmipIoControl().
void WmipGetGuidPropertiesFromGuidEntry (PWMIGUIDPROPERTIES GuidInfo, PGUIDENTRY GuidEntry)
Definition at line 2106 of file consumer.c.
References CONTAINING_RECORD, WMIGUIDPROPERTIES::EnableFlags, WMIGUIDPROPERTIES::EnableLevel, FALSE, tagInstanceSet::Flags, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_NOTIFICATION_TRACE_FLAG, WMIGUIDPROPERTIES::GuidType, IS_COLLECTING, IS_CONTROL_GUID, IS_ENABLE_COLLECTION, IS_ENABLE_EVENT, IS_EVENT_ONLY, IS_TRACED, WMIGUIDPROPERTIES::IsEnabled, tagGUIDENTRY::ISHead, tagGUIDENTRY::LoggerContext, WMIGUIDPROPERTIES::LoggerId, PAGED_CODE, TRUE, WmiGetLoggerEnableFlags, WmiGetLoggerEnableLevel, and WmiGetLoggerId.
Referenced by WmipEnumerateGuids().
PWNODE_HEADER WmipIncludeStaticNames (PWNODE_HEADER Wnode)
Definition at line 3780 of file consumer.c.
References ISBASENAME::BaseIndex, ISBASENAME::BaseName, BASENAMEFORMATSTRING, _WNODE_HEADER::BufferSize, CONTAINING_RECORD, Count, tagInstanceSet::Count, DPFLTR_WARNING_LEVEL, DPFLTR_WMICORE_ID, EVENTLOG_WARNING_TYPE, FALSE, _WNODE_HEADER::Flags, tagInstanceSet::Flags, _LIST_ENTRY::Flink, _WNODE_HEADER::Guid, Index, tagWNODE_SINGLE_INSTANCE::InstanceIndex, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, IS_PDO_INSTANCENAME, tagInstanceSet::IsBaseName, tagGUIDENTRY::ISHead, tagInstanceSet::IsStaticNames, MAXBASENAMESUFFIXLENGTH, memcpy(), NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, tagWNODE_ALL_DATA::OffsetInstanceNameOffsets, PAGED_CODE, _WNODE_HEADER::ProviderId, tagInstanceSet::ProviderId, ISSTATICENAMES::StaticNamePtr, StringCbCat, StringCbCopy, StringCbPrintf, TRUE, wcslen(), WmipAlloc, WmipDebugPrintEx, WmipEnterSMCritSection, WmipFindGEByGuid(), WmipInsertStaticNames(), WmipLeaveSMCritSection, WmipReferenceIS, WmipReportEventLog, WmipStaticInstanceNameSize(), WmipUnreferenceGE, WmipUnreferenceIS, WNODE_FLAG_ALL_DATA, WNODE_FLAG_PDO_INSTANCE_NAMES, WNODE_FLAG_SINGLE_INSTANCE, and WNODE_FLAG_SINGLE_ITEM.
Referenced by WmipProcessEvent().
void WmipInsertStaticNames (PWNODE_ALL_DATA Wnode, ULONG MaxWnodeSize, PBINSTANCESET InstanceSet)
Definition at line 670 of file consumer.c.
References ISBASENAME::BaseIndex, ISBASENAME::BaseName, BASENAMEFORMATSTRING, _WNODE_HEADER::BufferSize, tagInstanceSet::Count, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, _WNODE_HEADER::Flags, tagInstanceSet::Flags, Index, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, IS_PDO_INSTANCENAME, tagInstanceSet::IsBaseName, tagInstanceSet::IsStaticNames, MAXBASENAMESUFFIXLENGTH, NULL, tagWNODE_ALL_DATA::OffsetInstanceNameOffsets, PAGED_CODE, S_OK, _WMI_DISKIO_READWRITE::Size, ISSTATICENAMES::StaticNamePtr, StringCbCat, StringCbCopy, StringCbCopyEx, StringCbPrintf, wcslen(), WmipAssert, WmipDebugPrintEx, WmipStaticInstanceNameSize(), WNODE_FLAG_PDO_INSTANCE_NAMES, WNODE_FLAG_TOO_SMALL, and tagWNODE_ALL_DATA::WnodeHeader.
Referenced by WmipIncludeStaticNames(), and WmipQueryAllData().
BOOLEAN WmipIsQuerySetGuid (PBGUIDENTRY GuidEntry)
Definition at line 215 of file consumer.c.
References CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IS_CONTROL_GUID, IS_EVENT_ONLY, IS_TRACED, tagGUIDENTRY::ISHead, NULL, PAGED_CODE, TRUE, WmipAssert, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
Referenced by WmipOpenBlock().
NTSTATUS WmipMarkHandleAsClosed (HANDLE Handle)
Definition at line 2674 of file consumer.c.
References _WMIGUIDOBJECT::Flags, _WMIGUIDOBJECT::Irp, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, Status, UserMode, WMIGUID_FLAG_RECEIVE_NO_EVENTS, WmipCompleteGuidIrpWithError(), WmipEnterSMCritSection, WmipGuidObjectType, and WmipLeaveSMCritSection.
Referenced by WmipIoControl().
NTSTATUS WmipMBReply (IN HANDLE RequestHandle, IN ULONG ReplyIndex, IN PUCHAR Message, IN ULONG MessageSize)
Definition at line 4839 of file consumer.c.
References DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, MAXREQREPLYSLOTS, _WMIGUIDOBJECT::MBRequests, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, RemoveEntryList(), MBREQUESTS::ReplyObject, MBREQUESTS::RequestListEntry, Status, STATUS_INVALID_PARAMETER, UserMode, WmipDebugPrintEx, WmipEnterSMCritSection, WmipGuidObjectType, WmipLeaveSMCritSection, and WmipWriteMBToObject().
Referenced by WmipIoControl().
void WmipNotificationIrpCancel (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 2439 of file consumer.c.
References IO_NO_INCREMENT, IoCompleteRequest(), IoReleaseCancelSpinLock(), STATUS_CANCELLED, UNREFERENCED_PARAMETER, WmipClearIrpObjectList(), WmipEnterSMCritSection, and WmipLeaveSMCritSection.
Referenced by WmipReceiveNotifications().
NTSTATUS WmipOpenBlock (IN ULONG Ioctl, IN KPROCESSOR_MODE AccessMode, IN POBJECT_ATTRIBUTES CapturedObjectAttributes, IN ULONG DesiredAccess, OUT PHANDLE Handle)
Definition at line 252 of file consumer.c.
References _WMIGUIDOBJECT::EnableRequestSent, FALSE, _WMIGUIDOBJECT::Flags, _WMIGUIDOBJECT::GEObjectList, tagGUIDENTRY::Guid, _WMIGUIDOBJECT::Guid, _WMIGUIDOBJECT::GuidEntry, InsertHeadList(), InsertTailList(), Ioctl, IOCTL_WMI_OPEN_GUID, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, tagGUIDENTRY::ISCount, KernelMode, tagGUIDENTRY::MainGEList, memcpy(), NT_SUCCESS, NULL, ObDereferenceObject(), tagGUIDENTRY::ObjectHead, PAGED_CODE, Status, STATUS_ILLEGAL_FUNCTION, STATUS_INSUFFICIENT_RESOURCES, STATUS_WMI_GUID_NOT_FOUND, _WMIGUIDOBJECT::Type, WMIGUID_FLAG_KERNEL_NOTIFICATION, WMIGUID_FLAG_SECURITY_OBJECT, WmipAllocGuidEntry, WmipAssert, WmipEnableCollectOrEvent(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipGEHeadPtr, WmipIsQuerySetGuid(), WmipLeaveSMCritSection, WmipOpenGuidObject(), and ZwClose().
Referenced by IoWMIOpenBlock(), and WmipIoControl().
NTSTATUS WmipPrepareForWnodeAD (IN PWMIGUIDOBJECT GuidObject, OUT LPGUID Guid, IN OUT ULONG * ProviderIdCount, OUT PBINSTANCESET ** ProviderIdList, OUT BOOLEAN * InternalGuid)
Definition at line 502 of file consumer.c.
References CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_FLAG_INTERNAL, tagGUIDENTRY::Guid, IS_CONTROL_GUID, IS_EVENT_ONLY, IS_TRACED, tagGUIDENTRY::ISCount, tagGUIDENTRY::ISHead, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_SUCCESS, STATUS_WMI_GUID_DISCONNECTED, TRUE, WmipAddProviderIdToPIList(), WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceIS.
Referenced by WmipQueryAllData().
NTSTATUS WmipPrepareWnodeSI (IN PWMIGUIDOBJECT GuidObject, IN OUT PWNODE_SINGLE_INSTANCE WnodeSI, IN OUT ULONG * ProviderIdCount, OUT PBINSTANCESET ** ProviderIdList, OUT BOOLEAN * IsDynamic, OUT BOOLEAN * InternalGuid)
Definition at line 1356 of file consumer.c.
References _wcsicmp(), _wcsnicmp(), _wtoi(), ISBASENAME::BaseIndex, ISBASENAME::BaseName, BASENAMEFORMATSTRING, CONTAINING_RECORD, tagInstanceSet::Count, FALSE, _WNODE_HEADER::Flags, tagInstanceSet::Flags, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_FLAG_INTERNAL, _WNODE_HEADER::Guid, tagGUIDENTRY::Guid, IS_CONTROL_GUID, IS_EVENT_ONLY, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, IS_TRACED, tagInstanceSet::IsBaseName, tagGUIDENTRY::ISCount, tagGUIDENTRY::ISHead, tagInstanceSet::IsStaticNames, MAXBASENAMESUFFIXLENGTH, MAXBASENAMESUFFIXVALUE, NT_SUCCESS, NULL, OffsetToPtr, PAGED_CODE, _WNODE_HEADER::ProviderId, tagInstanceSet::ProviderId, ISSTATICENAMES::StaticNamePtr, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_WMI_GUID_DISCONNECTED, StringCbPrintf, TRUE, wcslen(), WmipAddProviderIdToPIList(), WmipCountedToSz(), WmipEnterSMCritSection, WmipFree, WmipIsNumber(), WmipLeaveSMCritSection, WmipReferenceIS, WmipUnreferenceIS, and WNODE_FLAG_STATIC_INSTANCE_NAMES.
Referenced by WmipQuerySetExecuteSI().
NTSTATUS WmipProcessEvent (PWNODE_HEADER InWnode, BOOLEAN IsHighPriority, BOOLEAN FreeBuffer)
Definition at line 4093 of file consumer.c.
References _WNODE_HEADER::BufferSize, _WMIGUIDOBJECT::Callback, _WMIGUIDOBJECT::CallbackContext, CONTAINING_RECORD, DPFLTR_WMICORE_ID, ExFreePool(), _WNODE_HEADER::Flags, _WMIGUIDOBJECT::Flags, _LIST_ENTRY::Flink, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, IsEqualGUID, NT_SUCCESS, NULL, ObDereferenceObject(), tagGUIDENTRY::ObjectHead, ObReferenceObjectSafe(), PAGED_CODE, Status, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WMI_GUID_NOT_FOUND, _tagWMI_Event::TraceErrorFlag, TRUE, WmiGetLoggerId, WMIGUID_FLAG_KERNEL_NOTIFICATION, WMIGUID_FLAG_RECEIVE_NO_EVENTS, WmipDebugPrintEx, WmipDereferenceEvent(), WmipDisableTraceProviders(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipFree, WmipIncludeStaticNames(), WmipLeaveSMCritSection, WmipUnreferenceGE, WmipWriteWnodeToObject(), WNODE_FLAG_EVENT_REFERENCE, and WNODE_FLAG_STATIC_INSTANCE_NAMES.
Referenced by WmipEventNotification(), WmipFlushBuffer(), WmipGenerateBinaryMofNotification(), WmipGenerateMofResourceNotification(), WmipSendGuidUpdateNotifications(), and WmipSendNotification().
VOID WmipPumpThreadApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 3256 of file consumer.c.
References BasepRegisterThread, BASESRV_SERVERDLL_INDEX, _BASE_CREATETHREAD_MSG::ClientId, _BASE_API_MSG::CreateThread, CSR_MAKE_API_NUMBER, DPFLTR_ERROR_LEVEL, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, _EPROCESS::ExceptionPort, ExFreePool(), FALSE, NtCurrentTeb(), NULL, PsGetCurrentProcess(), _BASE_CREATETHREAD_MSG::ThreadHandle, _BASE_API_MSG::u, UNREFERENCED_PARAMETER, WmipAssert, WmipCsrClientMessageServer(), and WmipDebugPrintEx.
Referenced by WmipCreatePumpThread().
NTSTATUS WmipQueryAllData (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN PWNODE_ALL_DATA Wnode, IN ULONG OutBufferLen, OUT PULONG RetSize)
Definition at line 858 of file consumer.c.
References _WNODE_HEADER::BufferSize, tagInstanceSet::Count, FALSE, _WNODE_HEADER::Flags, tagInstanceSet::Flags, _WNODE_HEADER::Guid, IRP_MN_QUERY_ALL_DATA, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, _WNODE_HEADER::Linkage, MANYPROVIDERIDS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PAGED_CODE, _WNODE_HEADER::ProviderId, tagInstanceSet::ProviderId, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_SUCCESS, STATUS_WMI_GUID_NOT_FOUND, TRUE, WmipForwardWmiIrp(), WmipFree, WmipGuidObjectType, WmipInsertStaticNames(), WmipPrepareForWnodeAD(), WmipSendWmiIrp(), WmipStaticInstanceNameSize(), WmipUnreferenceIS, WNODE_FLAG_INTERNAL, WNODE_FLAG_STATIC_INSTANCE_NAMES, WNODE_FLAG_TOO_SMALL, tagWNODE_ALL_DATA::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMIQueryAllData(), WmipIoControl(), and WmipQueryAllDataMultiple().
NTSTATUS WmipQueryAllDataMultiple (IN ULONG ObjectCount, IN PWMIGUIDOBJECT * ObjectList, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQADMULTIPLE QadMultiple, OUT ULONG * ReturnSize)
Definition at line 1163 of file consumer.c.
References _WNODE_HEADER::BufferSize, Count, DPFLTR_WMICORE_ID, FALSE, _WNODE_HEADER::Flags, _WNODE_HEADER::KernelHandle, _WNODE_HEADER::Linkage, NT_SUCCESS, NULL, OffsetToPtr, PAGED_CODE, RtlZeroMemory, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, WmipAlloc, WmipAssert, WmipDebugPrintEx, WmipFree, WmipQueryAllData(), WNODE_FLAG_ALL_DATA, WNODE_FLAG_INTERNAL, WNODE_FLAG_TOO_SMALL, tagWNODE_ALL_DATA::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMIQueryAllDataMultiple(), and WmipIoControl().
NTSTATUS WmipQueryGuidInfo (IN OUT PWMIQUERYGUIDINFO QueryGuidInfo)
Definition at line 2257 of file consumer.c.
References CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, _WMIGUIDOBJECT::GuidEntry, Handle, IS_EXPENSIVE, tagGUIDENTRY::ISHead, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, Status, STATUS_WMI_GUID_DISCONNECTED, TRUE, UserMode, WmipEnterSMCritSection, WmipGuidObjectType, and WmipLeaveSMCritSection.
Referenced by WmipIoControl().
NTSTATUS WmipQuerySetExecuteSI (IN PWMIGUIDOBJECT GuidObject, IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN UCHAR MinorFunction, IN OUT PWNODE_HEADER Wnode, IN ULONG OutBufferSize, OUT PULONG RetSize)
Definition at line 1607 of file consumer.c.
References DesiredAccessForFunction, DPFLTR_WMICORE_ID, _IO_STATUS_BLOCK::Information, IRP_MN_CHANGE_SINGLE_ITEM, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_ALL_DATA, MANYPROVIDERIDS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PAGED_CODE, tagInstanceSet::ProviderId, Status, STATUS_WMI_GUID_NOT_FOUND, STATUS_WMI_INSTANCE_NOT_FOUND, STATUS_WMI_ITEMID_NOT_FOUND, STATUS_WMI_READ_ONLY, STATUS_WMI_SET_FAILURE, WmipAssert, WmipDebugPrintEx, WmipForwardWmiIrp(), WmipFree, WmipGuidObjectType, WmipPrepareWnodeSI(), WmipSendWmiIrp(), WmipUnreferenceIS, and WNODE_FLAG_INTERNAL.
Referenced by IoWMIExecuteMethod(), IoWMIQuerySingleInstance(), IoWMISetSingleInstance(), IoWMISetSingleItem(), WmipIoControl(), and WmipQuerySingleMultiple().
NTSTATUS WmipQuerySingleMultiple (IN PIRP Irp, IN KPROCESSOR_MODE AccessMode, IN OUT PUCHAR BufferPtr, IN ULONG BufferSize, IN PWMIQSIMULTIPLE QsiMultiple, IN ULONG QueryCount, IN PWMIGUIDOBJECT * ObjectList, IN PUNICODE_STRING InstanceNames, OUT ULONG * ReturnSize)
Definition at line 1808 of file consumer.c.
References UNICODE_STRING3264::Buffer, _UNICODE_STRING::Buffer, _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, DPFLTR_WMICORE_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, HANDLE3264::Handle, WMIQSIINFO::Handle, WMIQSIINFO::InstanceName, IRP_MN_QUERY_SINGLE_INSTANCE, _WNODE_HEADER::KernelHandle, KernelMode, UNICODE_STRING3264::Length, _UNICODE_STRING::Length, _WNODE_HEADER::Linkage, UNICODE_STRING3264::MaximumLength, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, ProbeForRead, RtlCopyMemory, RtlZeroMemory, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, UserMode, WmipAlloc, WmipAllocNP, WmipAssert, WmipDebugPrintEx, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_INTERNAL, WNODE_FLAG_SINGLE_INSTANCE, WNODE_FLAG_TOO_SMALL, tagWNODE_SINGLE_INSTANCE::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMIQuerySingleInstanceMultiple(), and WmipIoControl().
NTSTATUS WmipQueueNotification (PWMIGUIDOBJECT Object, PWMIEVENTQUEUE EventQueue, PWNODE_HEADER Wnode)
Definition at line 3485 of file consumer.c.
References WMIEVENTQUEUE::Buffer, _WNODE_HEADER::BufferSize, DelayedWorkQueue, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, _WMIGUIDOBJECT::Event, _WMIGUIDOBJECT::EventQueueAction, WMIEVENTQUEUE::EventsLost, ExAllocatePoolWithTag, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), FALSE, KeIsAttachedProcess(), KernelMode, KeSetEvent(), WMIEVENTQUEUE::LastWnode, _WNODE_HEADER::Linkage, WMIEVENTQUEUE::MaxBufferSize, memcpy(), WMIEVENTQUEUE::NextOffset, NonPagedPool, NT_SUCCESS, NULL, CREATETHREADWORKITEM::Object, ObReferenceObjectByPointer(), PAGED_CODE, RECEIVE_ACTION_CREATE_THREAD, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, WmipAlloc, WmipCreatePumpThread(), WmipCreatePumpThreadRoutine(), WMIPCREATETHREADTAG, WmipDebugPrintEx, and CREATETHREADWORKITEM::WorkItem.
NTSTATUS WmipReceiveNotifications (PWMIRECEIVENOTIFICATION ReceiveNotification, PULONG OutBufferSize, PIRP Irp)
Definition at line 2713 of file consumer.c.
References _PsGetCurrentProcess, WMIRECEIVENOTIFICATION::Action, _WNODE_HEADER::BufferSize, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, _WMIGUIDOBJECT::EventQueueAction, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _WNODE_HEADER::Flags, _WMIGUIDOBJECT::Flags, OBJECT_EVENT_INFO::GuidObject, Handle, HANDLE3264::Handle, HANDLE3264::Handle64, WMIRECEIVENOTIFICATION::HandleCount, WMIRECEIVENOTIFICATION::Handles, _WMIGUIDOBJECT::HiPriority, InitializeListHead(), InsertTailList(), IoMarkIrpPending, IoSetCancelRoutine, _WMIGUIDOBJECT::Irp, IRP_OBJECT_LIST_HEAD, _WMIGUIDOBJECT::IrpObjectList, KernelMode, _WNODE_HEADER::Linkage, _WMIGUIDOBJECT::LoPriority, MANY_NOTIFICATION_OBJECTS, WMIEVENTQUEUE::NextOffset, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, ObOpenObjectByPointer(), ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGED_CODE, PROCESS_CREATE_THREAD, PROCESS_QUERY_INFORMATION, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, RECEIVE_ACTION_CREATE_THREAD, RECEIVE_ACTION_NONE, RtlImageNtHeader(), RtlZeroMemory, tagWNODE_TOO_SMALL::SizeNeeded, _IMAGE_OPTIONAL_HEADER::SizeOfStackCommit, _IMAGE_OPTIONAL_HEADER::SizeOfStackReserve, _WMIGUIDOBJECT::StackCommit, _WMIGUIDOBJECT::StackSize, Status, STATUS_ACCESS_DENIED, STATUS_CANCELLED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PENDING, THREAD_ALL_ACCESS, _WMIGUIDOBJECT::ThreadObjectList, TRUE, UserMode, WMIRECEIVENOTIFICATION::UserModeCallback, _WMIGUIDOBJECT::UserModeCallback, WMIRECEIVENOTIFICATION::UserModeProcess, _WMIGUIDOBJECT::UserModeProcess, WMIGUID_FLAG_REQUEST_OBJECT, WmipAlloc, WmipAssert, WmipClearObjectFromThreadList(), WmipCompleteGuidIrpWithError(), WmipCopyFromEventQueues(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFree, WmipGuidObjectType, WmipHaveHiPriorityEvent, WmipHaveLoPriorityEvent, WmipLeaveSMCritSection, WmipNotificationIrpCancel(), WNODE_FLAG_TOO_SMALL, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by WmipIoControl().
NTSTATUS WmipRegisterUMGuids (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Cookie, IN PWMIREGINFO RegInfo, IN ULONG RegInfoSize, OUT HANDLE * RequestHandle, OUT ULONG64 * LoggerContext)
Definition at line 4292 of file consumer.c.
References _WMIGUIDOBJECT::Cookie, _REGENTRY::DataSource, FALSE, _REGENTRY::Flags, tagGUIDENTRY::Flags, _WMIGUIDOBJECT::Flags, GE_NOTIFICATION_TRACE_FLAG, WMIREGGUIDW::Guid, tagGUIDENTRY::LoggerContext, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _WMIGUIDOBJECT::RegEntry, REGENTRY_FLAG_INUSE, REGENTRY_FLAG_NEWREGINFO, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_REG_IN_PROGRESS, REGENTRY_FLAG_RUNDOWN, REGENTRY_FLAG_TRACED, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_WMI_GUID_NOT_FOUND, TRUE, UserMode, WMIGUID_FLAG_REQUEST_OBJECT, WmiGuidObjectNameLength, WmipAllocRegEntry(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipFindISByGuid(), WmipLeaveSMCritSection, WmipOpenGuidObject(), WmipProbeAndCaptureGuidObjectAttributes(), WmipProcessWmiRegInfo(), WmipUMProviderCallback(), WmipUnreferenceGE, WmipUnreferenceIS, WmipUnreferenceRegEntry, WMIREG_FLAG_CALLBACK, and ZwClose().
Referenced by WmipIoControl().
ULONG WmipStaticInstanceNameSize (PBINSTANCESET InstanceSet)
Definition at line 597 of file consumer.c.
References ISBASENAME::BaseIndex, ISBASENAME::BaseName, tagInstanceSet::Count, tagInstanceSet::Flags, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, tagInstanceSet::IsBaseName, tagInstanceSet::IsStaticNames, MAXBASENAMESUFFIXLENGTH, MAXBASENAMESUFFIXVALUE, PAGED_CODE, ISSTATICENAMES::StaticNamePtr, tagInstanceSet::WADInstanceNameSize, wcslen(), and WmipAssert.
Referenced by WmipIncludeStaticNames(), WmipInsertStaticNames(), and WmipQueryAllData().
NTSTATUS WmipUMProviderCallback (IN WMIACTIONCODE ActionCode, IN PVOID DataPath, IN ULONG BufferSize, IN OUT PVOID Buffer)
Definition at line 4274 of file consumer.c.
References ASSERT, FALSE, PAGED_CODE, STATUS_UNSUCCESSFUL, and UNREFERENCED_PARAMETER.
Referenced by WmipInitializeDataStructs(), and WmipRegisterUMGuids().
NTSTATUS WmipUnregisterGuids (PWMIUNREGGUIDS UnregGuids)
Definition at line 4465 of file consumer.c.
References FALSE, tagGUIDENTRY::Flags, GE_NOTIFICATION_TRACE_FLAG, tagGUIDENTRY::LoggerContext, NULL, PAGED_CODE, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, WmipFindGEByGuid(), and WmipUnreferenceGE.
Referenced by WmipIoControl().
NTSTATUS WmipWriteMBToObject (IN PWMIGUIDOBJECT RequestObject, IN PWMIGUIDOBJECT ReplyObject, IN PUCHAR Message, IN ULONG MessageSize)
Definition at line 4495 of file consumer.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, InsertTailList(), KernelMode, MAXREQREPLYSLOTS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByPointer(), PAGED_CODE, _WNODE_HEADER::ProviderId, RemoveEntryList(), MBREQUESTS::ReplyObject, MBREQUESTS::RequestListEntry, RtlCopyMemory, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, _WNODE_HEADER::Version, WmipAlloc, WmipFree, WmipGuidObjectType, WmipWriteWnodeToObject(), and WNODE_FLAG_INTERNAL.
Referenced by WmipMBReply(), and WmipWriteMessageToGuid().
NTSTATUS WmipWriteMessageToGuid (IN PBGUIDENTRY GuidEntry, IN PWMIGUIDOBJECT ReplyObject, IN PUCHAR Message, IN ULONG MessageSize, OUT PULONG WrittenCount)
Definition at line 4627 of file consumer.c.
References ASSERT, CONTAINING_RECORD, tagInstanceSet::DataSource, DS_USER_MODE, tagDATASOURCE::Flags, _LIST_ENTRY::Flink, NT_SUCCESS, NULL, PAGED_CODE, tagDATASOURCE::RequestObject, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipWriteMBToObject().
Referenced by WmipCreateUMLogger().
NTSTATUS WmipWriteWnodeToObject (PWMIGUIDOBJECT Object, PWNODE_HEADER Wnode, BOOLEAN IsHighPriority)
Definition at line 3984 of file consumer.c.
References _WNODE_HEADER::BufferSize, DPFLTR_WMICORE_ID, _WNODE_HEADER::Flags, IO_NO_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IoSetCancelRoutine, _WMIGUIDOBJECT::Irp, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, RtlCopyMemory, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_SUCCESS, WmipAssert, WmipClearIrpObjectList(), WmipDebugPrintEx, WmipQueueEventToObject, WNODE_FLAG_TOO_SMALL, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by WmipDeleteMethod(), WmipDeliverWnodeToDS(), WmipProcessEvent(), and WmipWriteMBToObject().
Variable Documentation
const ACCESS_MASK DesiredAccessForFunction[]
Initial value:
=
{
    WMIGUID_QUERY,
    WMIGUID_QUERY,
    WMIGUID_SET,
    WMIGUID_SET,
    0,
    0,
    0,
    0,
    0,
    WMIGUID_EXECUTE,
    0,
    0
}
Definition at line 1591 of file consumer.c.
Referenced by WmipQuerySetExecuteSI().