Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/amd64/ntrtlamd64.h File Reference
ntrtlamd64.h File Reference
Functions
EXCEPTION_DISPOSITION RtlpExecuteHandlerForException (IN PEXCEPTION_RECORD ExceptionRecord, IN ULONG64 EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PDISPATCHER_CONTEXT DispatcherContext)
EXCEPTION_DISPOSITION RtlpExecuteHandlerForUnwind (IN PEXCEPTION_RECORD ExceptionRecord, IN ULONG_PTR EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PDISPATCHER_CONTEXT DispatcherContext)
BOOLEAN RtlpIsFrameInBounds (IN OUT PULONG64 LowLimit, IN ULONG64 StackFrame, IN OUT PULONG64 HighLimit)
Function Documentation
EXCEPTION_DISPOSITION RtlpExecuteHandlerForException (IN PEXCEPTION_RECORD ExceptionRecord, IN ULONG64 EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PDISPATCHER_CONTEXT DispatcherContext)
EXCEPTION_DISPOSITION RtlpExecuteHandlerForUnwind (IN PEXCEPTION_RECORD ExceptionRecord, IN ULONG_PTR EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PDISPATCHER_CONTEXT DispatcherContext)
BOOLEAN RtlpIsFrameInBounds (IN OUT PULONG64 LowLimit, IN ULONG64 StackFrame, IN OUT PULONG64 HighLimit)
Definition at line 1720 of file exdsptch.c.
References FALSE, and TRUE.
Referenced by RtlDispatchException(), RtlGetCallersAddress(), RtlpWalkFrameChain(), and RtlUnwindEx().