Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmsubs.c File Reference
cmsubs.c File Reference
#include "cmp.h"
Macros
#define CMP_FAST_KEY_BODY_ARRAY_DUMP 1
#define CMP_FAST_KEY_BODY_ARRAY_FLUSH 2
Functions
VOID CmpCleanUpKCBCacheTable (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
VOID CmpCleanUpKcbCacheWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
VOID CmpCleanUpKcbValueCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpCleanUpSubKeyInfo (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
ULONG CmpComputeKcbConvKey (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
PUNICODE_STRING CmpConstructName (PCM_KEY_CONTROL_BLOCK kcb)
PCM_KEY_CONTROL_BLOCK CmpCreateKeyControlBlock (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node, PCM_KEY_CONTROL_BLOCK ParentKcb, ULONG ControlFlags, PUNICODE_STRING KeyName)
VOID CmpDereferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpDereferenceKeyControlBlockWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
VOID CmpDereferenceNameControlBlockWithLock (PCM_NAME_CONTROL_BLOCK Ncb)
VOID CmpDumpKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN PULONG Count, IN PVOID Context)
VOID CmpDumpOneKeyBody (IN PCM_KEY_CONTROL_BLOCK kcb, IN PCM_KEY_BODY KeyBody, IN PUNICODE_STRING Name, IN PVOID Context)
VOID CmpFlushNotifiesOnKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN LockHeld)
BOOLEAN CmpFreeKeyBody (PHHIVE Hive, HCELL_INDEX Cell)
PCM_NAME_CONTROL_BLOCK CmpGetNameControlBlock (PUNICODE_STRING NodeName, PBOOLEAN NameUpCase)
VOID CmpInitializeCache ()
PCM_KEY_CONTROL_BLOCK CmpInsertKeyHash (IN PCM_KEY_HASH KeyHash, IN BOOLEAN FakeKey)
VOID CmpRebuildKcbCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
BOOLEAN CmpReferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
BOOLEAN CmpRehashKcbSubtree (PCM_KEY_CONTROL_BLOCK Start, PCM_KEY_CONTROL_BLOCK End)
VOID CmpRemoveKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpRemoveKeyHash (IN PCM_KEY_HASH KeyHash)
ULONG CmpSearchForOpenSubKeys (PCM_KEY_CONTROL_BLOCK KeyControlBlock, SUBKEY_SEARCH_TYPE SearchType, BOOLEAN RegLockHeldEx, PVOID SearchContext)
BOOLEAN CmpSearchKeyControlBlockTree (PKCB_WORKER_ROUTINE WorkerRoutine, PVOID Context1, PVOID Context2)
VOID DelistKeyBodyFromKCB (IN PCM_KEY_BODY KeyBody, IN BOOLEAN LockHeld)
VOID EnlistKeyBodyWithKCB (IN PCM_KEY_BODY KeyBody, IN ULONG ControlFlags)
VOID InitializeKCBKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb)
Variables
PCM_KEY_HASH_TABLE_ENTRY CmpCacheTable
ULONG CmpDelayedCloseSize
ULONG CmpHashTableSize = 2048
BOOLEAN CmpHoldLazyFlush
PCM_NAME_HASH_TABLE_ENTRY CmpNameCacheTable
EX_PUSH_LOCK CmpPostLock
Macro Definition Documentation
#define CMP_FAST_KEY_BODY_ARRAY_DUMP 1
Definition at line 115 of file cmsubs.c.
Referenced by CmpDumpKeyBodyList(), CmpFlushNotifiesOnKeyBodyList(), and DelistKeyBodyFromKCB().
#define CMP_FAST_KEY_BODY_ARRAY_FLUSH 2
Definition at line 116 of file cmsubs.c.
Referenced by CmpDumpKeyBodyList(), CmpFlushNotifiesOnKeyBodyList(), and DelistKeyBodyFromKCB().
Function Documentation
VOID CmpCleanUpKCBCacheTable (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 434 of file cmsubs.c.
References ASSERT, CM_PAGED_CODE, CmpCleanUpKcbCacheWithLock(), CmpHashTableSize, CmpIsKCBLockedExclusive, CmpKCBLockForceAcquireAllowed(), CmpLockHashEntryByIndexExclusive, CmpRemoveFromDelayedClose(), CmpRunDownDelayDerefKCBEngine(), CmpTryToLockHashEntryByIndexExclusive(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_HASH_TABLE_ENTRY::Entry, FALSE, GET_HASH_INDEX, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_CONTROL_BLOCK::NextHash, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_KEY_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmCompressKey(), and CmpSearchForOpenSubKeys().
VOID CmpCleanUpKcbCacheWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 1325 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_SUBKEY_HINT, CmpCleanUpKcbValueCache(), CmpDelayDerefKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpDereferenceNameControlBlockWithLock(), CmpFreeKeyControlBlock(), CmpRemoveKeyControlBlock(), _CM_KEY_CONTROL_BLOCK::Delete, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, _CM_KEY_CONTROL_BLOCK::IndexHint, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_KEY_CONTROL_BLOCK::ParentKcb, PROTECTED_POOL, _CM_KEY_CONTROL_BLOCK::RefCount, and SET_KCB_SIGNATURE.
Referenced by CmpAddToDelayedClose(), CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpDelayCloseWorker(), CmpDereferenceKeyControlBlockWithLock(), and CmpSearchKeyControlBlockTree().
VOID CmpCleanUpKcbValueCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 1265 of file cmsubs.c.
References ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_NO_DELAY_CLOSE, CM_KCB_SYM_LINK_FOUND, CMP_GET_CACHED_ADDRESS, CMP_GET_CACHED_CELLDATA, CMP_IS_CELL_CACHED, CmpDelayDerefKeyControlBlock(), CmpMakeSpecialPoolReadWrite, _CACHED_CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::Delete, ExFreePool(), _CM_KEY_CONTROL_BLOCK::ExtFlags, HCELL_NIL, _CACHED_CHILD_LIST::RealKcb, _CM_KEY_CONTROL_BLOCK::RefCount, _CM_KEY_CONTROL_BLOCK::ValueCache, and _CACHED_CHILD_LIST::ValueList.
Referenced by CmDeleteValueKey(), CmEnumerateValueKey(), CmpCleanUpKcbCacheWithLock(), CmpCompareNewValueDataAgainstKCBCache(), CmpDoOpen(), CmpGetSymbolicLink(), CmpRebuildKcbCache(), CmpSwitchStorageAndRebuildMappings(), CmQueryValueKey(), CmRestoreKey(), and CmSetValueKey().
VOID CmpCleanUpSubKeyInfo (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 1208 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_INVALID_CACHED_INFO, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, _CM_KEY_CONTROL_BLOCK::Delete, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, HCELL_NIL, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::IndexHint, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NULL, PROTECTED_POOL, Stable, _CM_KEY_CONTROL_BLOCK::SubKeyCount, _CM_KEY_NODE::SubKeyCounts, and Volatile.
Referenced by CmDeleteKey(), CmMoveKey(), CmpCreateLinkNode(), CmpDoCreate(), CmpRebuildKcbCache(), CmpSearchForOpenSubKeys(), CmRenameKey(), CmRestoreKey(), and CmUnloadKey().
ULONG CmpComputeKcbConvKey (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 734 of file cmsubs.c.
References ASSERT, CM_PAGED_CODE, CmUpcaseUnicodeChar, _CM_NAME_CONTROL_BLOCK::Compressed, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_NAME_CONTROL_BLOCK::NameLength, NULL, OBJ_NAME_PATH_SEPARATOR, and _CM_KEY_CONTROL_BLOCK::ParentKcb.
Referenced by CmpRehashKcbSubtree(), and CmRenameKey().
PUNICODE_STRING CmpConstructName (PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 1407 of file cmsubs.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_KCB_KEY_NON_EXIST, CMP_KCB_REAL_NAME_UPCASE, _CM_NAME_CONTROL_BLOCK::Compressed, _CM_KEY_CONTROL_BLOCK::Delete, ExAllocatePoolWithTag, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, HvGetCell, HvReleaseCell, InterlockedCompareExchangePointer, KEY_COMP_NAME, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MAXUSHORT, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_NODE::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_NAME_CONTROL_BLOCK::NameLength, _CM_KEY_NODE::NameLength, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, _CM_KEY_CONTROL_BLOCK::ParentKcb, PROTECTED_POOL, RtlCopyMemory, and TRUE.
Referenced by CmpDumpKeyBodyList(), CmpGetSymbolicLink(), CmpLoadHiveVolatile(), CmpQueryKeyName(), CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), and CmQueryKey().
PCM_KEY_CONTROL_BLOCK CmpCreateKeyControlBlock (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node, PCM_KEY_CONTROL_BLOCK ParentKcb, ULONG ControlFlags, PUNICODE_STRING KeyName)
Definition at line 1688 of file cmsubs.c.
References ASSERT, ASSERT_KCB, _UNICODE_STRING::Buffer, Cell, CM_KCB_INVALID_CACHED_INFO, CM_KCB_KEY_NON_EXIST, CM_KCB_NO_DELAY_CLOSE, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, CMP_CREATE_KCB_FAKE, CMP_CREATE_KCB_KCB_LOCKED, CMP_KCB_REAL_NAME_UPCASE, CMP_MAX_REGISTRY_DEPTH, CmpAllocateKeyControlBlock(), CmpAssignSecurityToKcb(), CmpDelayedCloseSize, CmpDereferenceKeyControlBlockWithLock(), CmpFreeKeyControlBlock(), CmpGetNameControlBlock(), CmpInsertKeyHash(), CmpLockKCBExclusive, CmpLockTwoHashEntriesExclusive(), CmpReferenceKeyControlBlock(), CmpRemoveKeyControlBlock(), CmpTraceKcbCreate, CmpUnlockHashEntry, CmpUnlockTwoHashEntries(), CmUpcaseUnicodeChar, _CM_KEY_CONTROL_BLOCK::ConvKey, _CACHED_CHILD_LIST::Count, _CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::DelayedCloseIndex, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, Hive, HIVE_IS_UNLOADING, _HHIVE::HiveFlags, InitializeKCBKeyBodyList(), IsHiveFrozen, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueDataLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueNameLen, KeGetCurrentThread(), KEY_SYM_LINK, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHash, _CM_KEY_CONTROL_BLOCK::KeyHive, KeyName, _CM_KEY_NODE::LastWriteTime, _UNICODE_STRING::Length, _CHILD_LIST::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_CONTROL_BLOCK::NameBlock, NULL, OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, PERFINFO_REG_KCB_CREATE, _CM_KEY_CONTROL_BLOCK::RefCount, _CM_KEY_NODE::Security, SET_KCB_SIGNATURE, Stable, _CM_KEY_CONTROL_BLOCK::SubKeyCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_CONTROL_BLOCK::TotalLevels, TRUE, _CM_KEY_CONTROL_BLOCK::ValueCache, _CACHED_CHILD_LIST::ValueList, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpAddInfoAfterParseFailure(), CmpCreateRegistryRoot(), CmpDoCreateChild(), CmpDoOpen(), and CmpParseKey().
VOID CmpDereferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 2093 of file cmsubs.c.
References CmpDereferenceKeyControlBlockWithLock(), CmpLockKCBExclusive, CmpUnlockHashEntry, _CM_KEY_CONTROL_BLOCK::ConvKey, FALSE, InterlockedCompareExchange(), LogKCBReference, and _CM_KEY_CONTROL_BLOCK::RefCount.
Referenced by CmpCacheLookup(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpLateUnloadHiveWorker(), and CmpParseKey().
VOID CmpDereferenceKeyControlBlockWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 2140 of file cmsubs.c.
References ASSERT_KCB, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_NO_DELAY_CLOSE, CM_KCB_SYM_LINK_FOUND, CmpAddToDelayedClose(), CmpCleanUpKcbCacheWithLock(), CmpHoldLazyFlush, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_CONTROL_BLOCK::ExtFlags, _CM_KEY_CONTROL_BLOCK::Flags, InterlockedDecrement, KEY_SYM_LINK, LogKCBReference, and _CM_KEY_CONTROL_BLOCK::RefCount.
Referenced by CmpAddInfoAfterParseFailure(), CmpCleanUpKcbCacheWithLock(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpDoCreateChild(), CmpDoOpen(), CmpGetSymbolicLink(), CmpIsHiveAlreadyLoaded(), CmpParseKey(), and CmpRunDownDelayDerefKCBEngine().
VOID CmpDereferenceNameControlBlockWithLock (PCM_NAME_CONTROL_BLOCK Ncb)
Definition at line 1125 of file cmsubs.c.
References ASSERT, CmpLockNameHashEntryExclusive, CmpUnlockNameHashEntry, _CM_NAME_CONTROL_BLOCK::ConvKey, ExFreePoolWithTag, GET_HASH_ENTRY, _CM_NAME_CONTROL_BLOCK::NameHash, _CM_NAME_HASH::NextHash, NULL, PROTECTED_POOL, _CM_NAME_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmpCleanUpKcbCacheWithLock(), and CmRenameKey().
VOID CmpDumpKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN PULONG Count, IN PVOID Context)
Definition at line 223 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CMP_FAST_KEY_BODY_ARRAY_DUMP, CMP_FAST_KEY_BODY_ARRAY_FLUSH, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpConstructName(), CmpDelayedCloseSize, CmpDumpOneKeyBody(), CONTAINING_RECORD, ExFreePoolWithTag, FALSE, _LIST_ENTRY::Flink, InterlockedCompareExchangePointer, IsListEmpty, _CM_KEY_BODY::KeyBodyList, NULL, PROTECTED_POOL, STATUS_INSUFFICIENT_RESOURCES, and TRUE.
Referenced by CmpFreeAllMemory(), and CmpSearchForOpenSubKeys().
VOID CmpDumpOneKeyBody (IN PCM_KEY_CONTROL_BLOCK kcb, IN PCM_KEY_BODY KeyBody, IN PUNICODE_STRING Name, IN PVOID Context)
Definition at line 119 of file cmsubs.c.
References ASSERT_KEY_OBJECT, _UNICODE_STRING::Buffer, _QUERY_OPEN_SUBKEYS_CONTEXT::Buffer, _QUERY_OPEN_SUBKEYS_CONTEXT::BufferLength, _KEY_OPEN_SUBKEYS_INFORMATION::Count, _QUERY_OPEN_SUBKEYS_CONTEXT::CurrentNameBuffer, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, _KEY_OPEN_SUBKEYS_INFORMATION::KeyArray, _QUERY_OPEN_SUBKEYS_CONTEXT::KeyBodyToIgnore, KEY_PID_ARRAY::KeyName, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), KEY_PID_ARRAY::PID, PsGetProcessImageFileName(), PsLookupProcessByProcessId(), _QUERY_OPEN_SUBKEYS_CONTEXT::RequiredSize, RtlCopyMemory, STATUS_BUFFER_OVERFLOW, _QUERY_OPEN_SUBKEYS_CONTEXT::StatusCode, and _QUERY_OPEN_SUBKEYS_CONTEXT::UsedLength.
Referenced by CmpDumpKeyBodyList().
VOID CmpFlushNotifiesOnKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN LockHeld)
Definition at line 321 of file cmsubs.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, ASSERT_KCB_LOCKED_EXCLUSIVE, ASSERT_KEY_OBJECT, CMP_FAST_KEY_BODY_ARRAY_DUMP, CMP_FAST_KEY_BODY_ARRAY_FLUSH, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpFlushNotify(), CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, InterlockedCompareExchangePointer, IsListEmpty, _CM_KEY_BODY::KeyBodyList, _CM_KEY_BODY::NotifyBlock, NULL, ObDereferenceObjectDeferDelete(), and ObReferenceObjectSafe().
Referenced by CmDeleteKey(), CmpSearchForOpenSubKeys(), CmUnloadKey(), and NtRenameKey().
BOOLEAN CmpFreeKeyBody (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2226 of file cmsubs.c.
References ASSERT, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, KEY_HIVE_EXIT, _CELL_DATA::_u::KeyNode, NULL, _CM_KEY_NODE::Security, TRUE, and _CELL_DATA::u.
Referenced by CmpFreeKeyByCell().
PCM_NAME_CONTROL_BLOCK CmpGetNameControlBlock (PUNICODE_STRING NodeName, PBOOLEAN NameUpCase)
Definition at line 977 of file cmsubs.c.
References _UNICODE_STRING::Buffer, CMP_DEST_UP, CmpCompareCompressedName(), CmpLockNameHashEntryExclusive, CmpUnlockNameHashEntry, CmUpcaseUnicodeChar, _CM_NAME_CONTROL_BLOCK::Compressed, CONTAINING_RECORD, _CM_NAME_HASH::ConvKey, _CM_NAME_CONTROL_BLOCK::ConvKey, _CM_NAME_HASH_TABLE_ENTRY::Entry, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, GET_HASH_INDEX, Index, _UNICODE_STRING::Length, _CM_NAME_CONTROL_BLOCK::Name, _CM_NAME_CONTROL_BLOCK::NameHash, _CM_NAME_CONTROL_BLOCK::NameLength, _CM_NAME_HASH::NextHash, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, PROTECTED_POOL, _CM_NAME_CONTROL_BLOCK::RefCount, RtlZeroMemory, and TRUE.
Referenced by CmpCreateKeyControlBlock(), and CmRenameKey().
VOID CmpInitializeCache ()
Definition at line 2419 of file cmsubs.c.
References CM_BUGCHECK, CmpHashTableSize, CmpInitializeDelayedCloseTable(), CONFIG_INITIALIZATION_FAILED, ExAllocatePoolWithTag, ExInitializePushLock(), INIT_CACHE_TABLE, NULL, PagedPool, and RtlZeroMemory.
PCM_KEY_CONTROL_BLOCK CmpInsertKeyHash (IN PCM_KEY_HASH KeyHash, IN BOOLEAN FakeKey)
Definition at line 2288 of file cmsubs.c.
References ASSERT_KEY_HASH, CONTAINING_RECORD, _CM_KEY_HASH::ConvKey, _CM_KEY_HASH_TABLE_ENTRY::Entry, GET_HASH_INDEX, Index, _CM_KEY_HASH::KeyCell, _CM_KEY_HASH::KeyHive, _CM_KEY_HASH::NextHash, and NULL.
Referenced by CmpCreateKeyControlBlock(), CmpRehashKcbSubtree(), and CmRenameKey().
VOID CmpRebuildKcbCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 1161 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_SYM_LINK_FOUND, CmpCleanUpKcbValueCache(), CmpCleanUpSubKeyInfo(), CmpSetUpKcbValueCache, _CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::ExtFlags, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueDataLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueNameLen, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NULL, and _CM_KEY_NODE::ValueList.
Referenced by CmMoveKey(), CmpCloneControlSet(), and CmpSaveBootControlSet().
BOOLEAN CmpReferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 914 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED, CmpDelayedCloseSize, CmpIsKCBLockedExclusive, CmpRemoveFromDelayedClose(), CmpTryConvertKCBLockSharedToExclusive(), CmpUpgradeKCBLockToExclusive, _CM_KEY_CONTROL_BLOCK::DelayedCloseIndex, FALSE, InterlockedDecrement, InterlockedIncrement, LogKCBReference, _CM_KEY_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmpCacheLookup(), CmpCreateKeyControlBlock(), CmpDoOpen(), CmpGetSymbolicLink(), CmpParseKey(), and CmUnloadKeyEx().
BOOLEAN CmpRehashKcbSubtree (PCM_KEY_CONTROL_BLOCK Start, PCM_KEY_CONTROL_BLOCK End)
Definition at line 795 of file cmsubs.c.
References ASSERT, CM_PAGED_CODE, CmpComputeKcbConvKey(), CmpInsertKeyHash(), CmpRemoveKeyHash(), _CM_KEY_CONTROL_BLOCK::ConvKey, FALSE, _CM_KEY_CONTROL_BLOCK::KeyHash, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_KEY_CONTROL_BLOCK::TotalLevels, and TRUE.
Referenced by CmpSearchForOpenSubKeys().
VOID CmpRemoveKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 2188 of file cmsubs.c.
References ASSERT_KCB, ASSERT_KCB_LOCKED_EXCLUSIVE, CmpRemoveKeyHash(), and _CM_KEY_CONTROL_BLOCK::KeyHash.
Referenced by CmDeleteKey(), CmpCacheLookup(), CmpCleanUpKcbCacheWithLock(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDoCreate(), CmpDoCreateChild(), CmpParseKey(), CmpSearchForOpenSubKeys(), and CmUnloadKey().
VOID CmpRemoveKeyHash (IN PCM_KEY_HASH KeyHash)
Definition at line 2368 of file cmsubs.c.
References ASSERT, ASSERT_KEY_HASH, _CM_KEY_HASH_TABLE_ENTRY::Entry, GET_HASH_INDEX, Index, _CM_KEY_HASH::NextHash, NULL, and TRUE.
Referenced by CmpRehashKcbSubtree(), CmpRemoveKeyControlBlock(), and CmRenameKey().
ULONG CmpSearchForOpenSubKeys (PCM_KEY_CONTROL_BLOCK KeyControlBlock, SUBKEY_SEARCH_TYPE SearchType, BOOLEAN RegLockHeldEx, PVOID SearchContext)
Definition at line 523 of file cmsubs.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_KCB_NO_DELAY_CLOSE, CmIsKcbReadOnly, CmpCleanUpKCBCacheTable(), CmpCleanUpSubKeyInfo(), CmpDumpKeyBodyList(), CmpFlushNotifiesOnKeyBodyList(), CmpHashTableSize, CmpIsKCBLockedExclusive, CmpKCBLockForceAcquireAllowed(), CmpLockHashEntryByIndexExclusive, CmpRehashKcbSubtree(), CmpRemoveKeyControlBlock(), CmpTryToLockHashEntryByIndexExclusive(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, Count, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_HASH_TABLE_ENTRY::Entry, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, GET_HASH_INDEX, HCELL_NIL, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::NextHash, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, SearchAndCount, SearchAndDeref, SearchAndRehash, SearchAndTagNoDelayClose, SearchIfExist, _CM_KEY_CONTROL_BLOCK::TotalLevels, and TRUE.
BOOLEAN CmpSearchKeyControlBlockTree (PKCB_WORKER_ROUTINE WorkerRoutine, PVOID Context1, PVOID Context2)
Definition at line 2004 of file cmsubs.c.
References ASSERT, ASSERT_KCB, CmpCleanUpKcbCacheWithLock(), CmpHashTableSize, CmpLockHashEntryByIndexExclusive, CmpRemoveFromDelayedClose(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_HASH_TABLE_ENTRY::Entry, FALSE, KCB_WORKER_CONTINUE, KCB_WORKER_DELETE, KCB_WORKER_DONE, KCB_WORKER_ERROR, _CM_KEY_CONTROL_BLOCK::NextHash, _CM_KEY_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmCompressKey(), CmpRefreshHive(), and CmUnloadKey().
VOID DelistKeyBodyFromKCB (IN PCM_KEY_BODY KeyBody, IN BOOLEAN LockHeld)
Definition at line 2514 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CMP_FAST_KEY_BODY_ARRAY_DUMP, CMP_FAST_KEY_BODY_ARRAY_FLUSH, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpLockKCBExclusive, CmpUnlockKCB, FALSE, InterlockedCompareExchangePointer, IsListEmpty, NULL, and RemoveEntryList().
Referenced by CmpDeleteKeyObject().
VOID EnlistKeyBodyWithKCB (IN PCM_KEY_BODY KeyBody, IN ULONG ControlFlags)
Definition at line 2472 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, CMP_ENLIST_KCB_LOCKED_EXCLUSIVE, CMP_ENLIST_KCB_LOCKED_SHARED, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpLockKCBExclusive, CmpSetNoCallers, CmpUnlockKCB, InitializeListHead(), InsertTailList(), InterlockedCompareExchangePointer, and NULL.
Referenced by CmpCreateRegistryRoot(), CmpDoCreateChild(), and CmpDoOpen().
VOID InitializeKCBKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 2462 of file cmsubs.c.
References CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, InitializeListHead(), and NULL.
Referenced by CmpCreateKeyControlBlock().
Variable Documentation
PCM_KEY_HASH_TABLE_ENTRY CmpCacheTable
Definition at line 26 of file cmsubs.c.
Referenced by CmpCacheLookup(), CmpFreeAllMemory(), CmpGetSymbolicLink(), CmpTryToLockHashEntryByIndexExclusive(), and CmpWmiDumpKcbTable().
ULONG CmpDelayedCloseSize
Definition at line 31 of file cmdelay.c.
Referenced by CmpAddToDelayedClose(), CmpCreateKeyControlBlock(), CmpDelayCloseWorker(), CmpDumpKeyBodyList(), CmpReferenceKeyControlBlock(), and CmpRemoveFromDelayedClose().
ULONG CmpHashTableSize = 2048
Definition at line 28 of file cmsubs.c.
Referenced by CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpDoOpen(), CmpFreeAllMemory(), CmpInitializeCache(), CmpKCBLockForceAcquireAllowed(), CmpParseKey(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), CmpSearchKeyControlBlockTree(), and CmpWmiDumpKcbTable().
BOOLEAN CmpHoldLazyFlush
Definition at line 66 of file cmworker.c.
Referenced by CmpDereferenceKeyControlBlockWithLock().
PCM_NAME_HASH_TABLE_ENTRY CmpNameCacheTable
Definition at line 27 of file cmsubs.c.
Referenced by CmpFreeAllMemory().
EX_PUSH_LOCK CmpPostLock
Definition at line 24 of file cmsubs.c.