Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/debug.c File Reference
debug.c File Reference
#include "stdarg.h"
#include "stdio.h"
#include "ntrtlp.h"
#include "wdbgexts.h"
#include <ntdbg.h>
Macros
#define NOEXTAPI
Functions
VOID DbgCommandString (__in PCH Name, __in PCH Command)
VOID DbgLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
ULONG DbgPrint (__in PCHAR Format,...)
ULONG DbgPrintEx (__in ULONG ComponentId, __in ULONG Level, __in PCHAR Format,...)
ULONG DbgPrintReturnControlC (__in PCHAR Format,...)
ULONG DbgPrompt (__in PCHAR Prompt, __out_bcount(Length) PCHAR Response, __in ULONG Length)
NTSTATUS DbgQueryDebugFilterState (__in ULONG ComponentId, __in ULONG Level)
NTSTATUS DbgSetDebugFilterState (__in ULONG ComponentId, __in ULONG Level, __in BOOLEAN State)
VOID DbgUnLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
ULONG vDbgPrintEx (__in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, __in va_list arglist)
ULONG vDbgPrintExWithPrefix (__in PCH Prefix, __in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, __in va_list arglist)
ULONG vDbgPrintExWithPrefixInternal (__in PCH Prefix, __in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, __in va_list arglist, __in BOOLEAN ControlC)
Macro Definition Documentation
#define NOEXTAPI
Definition at line 22 of file debug.c.
Function Documentation
VOID DbgCommandString (__in PCH Name, __in PCH Command)
Definition at line 489 of file debug.c.
References BREAKPOINT_COMMAND_STRING, _STRING::Buffer, DebugService2(), _STRING::Length, and strlen().
VOID DbgLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
Definition at line 414 of file debug.c.
References _KD_SYMBOLS_INFO::BaseOfDll, BREAKPOINT_LOAD_SYMBOLS, _KD_SYMBOLS_INFO::CheckSum, _IMAGE_OPTIONAL_HEADER::CheckSum, DebugService2(), NULL, _IMAGE_NT_HEADERS::OptionalHeader, _KD_SYMBOLS_INFO::ProcessId, RtlImageNtHeader(), _KD_SYMBOLS_INFO::SizeOfImage, and _IMAGE_OPTIONAL_HEADER::SizeOfImage.
Referenced by ExpInitializeExecutive(), MiLoadUserSymbols(), and MmLoadSystemImage().
ULONG DbgPrint (__in PCHAR Format, ...)
Definition at line 41 of file debug.c.
References TRUE, va_start, and vDbgPrintExWithPrefixInternal().
Referenced by CcInsertIntoCleanSharedCacheMapList(), CmpHysteresisTest(), ExInitializeZone(), ExMapHandleToPointerEx(), ExpCheckForResource(), ExpDebuggerWorker(), ExpUpdateDebugInfo(), ExpWaitForResource(), ExpWorkerThread(), HvpRecoverData(), InitializeSListHead(), IoAssignDriveLetters(), IoInitSystem(), IopCreateArcNames(), IopCreateArcNamesDisk(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopStoreSystemPartitionInformation(), IoShutdownSystem(), KeBugCheck2(), KeConnectInterrupt(), KeUpdateRunTime(), KiGetVectorInfo(), KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), LdrRelocateImageWithBias(), LookupEntryPoint(), NtCreateProfile(), NtQuerySystemInformation(), NtRaiseHardError(), ObpAllocateObject(), ObpFreeObject(), ObpInsertDirectoryEntry(), Ps386GetVdmIoHandler(), PsLocateSystemDll(), PsMapSystemDll(), Psp386GetVdmIoHandler(), Psp386InsertVdmIoHandlerBlock(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspCatchCriticalBreak(), PspInitializeSystemDll(), RtlAssert(), RtlCreateUserThread(), RtlFindClearRuns(), RtlpCallQueryRegistryRoutine(), RtlpCreateStack(), RtlpFreeStack(), RtlpOpenImageFile(), RtlpQueryRegistryDirect(), RtlpTraceDatabaseInternalAdd(), RtlpWalkFrameChainExceptionFilter(), RtlQueryRegistryValues(), RtlTraceDatabaseDestroy(), SeAccessCheck(), SeCaptureAuditPolicy(), SeImpersonateClient(), SeInitializeProcessAuditName(), SepCreateLogonSessionTrack(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), and SeTokenCanImpersonate().
ULONG DbgPrintEx (__in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, ...)
Definition at line 116 of file debug.c.
References TRUE, va_start, and vDbgPrintExWithPrefixInternal().
Referenced by CmpDoFileSetSize(), CmpDumpOneKeyBody(), CmpFileFlush(), CmpFileRead(), CmpFileWrite(), CmpFreeAllMemory(), CmpLoadHiveThread(), CmpSecurityExceptionFilter(), HvpDoWriteHive(), HvpFindNextDirtyBlock(), HvpGrowLog1(), HvpGrowLog2(), MiAllocatePagesForMdl(), MiAttemptPageFileReduction(), MiBuildImportsForBootDrivers(), MiCheckCacheAttributes(), MiCheckPdeForSessionSpace(), MiCompleteProtoPteFault(), MiComputeSystemTrimCriteria(), MiCreateImageFileMap(), MiDeleteVirtualAddresses(), MiDetermineTrimAmount(), MiDispatchFault(), MiEnablePagingOfDriver(), MiFindEmptyAddressRange(), MiFindInitializationCode(), MiFindLargePageMemory(), MiFlushSectionInternal(), MiGatherMappedPages(), MiIdentifyPfn(), MiInitializeMemoryEvents(), MiInsertIoSpaceMap(), MiLoadImageSection(), MiNoPagesLastChance(), MiPurgeImageSection(), MiRearrangeWorkingSetExpansionList(), MiReportPhysicalMemory(), MiResolvePageFileFault(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), MiSetProtectionOnSection(), MiWaitForInPageComplete(), MiWriteComplete(), MmAccessFault(), MmCleanProcessAddressSpace(), MmGrowKernelStackEx(), MmInitSystem(), MmLoadSystemImage(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmResetDriverPaging(), MmSessionDelete(), NtCreateKey(), NtCreatePagingFile(), NtQueryOpenSubKeys(), and WmipTracePageFault().
ULONG DbgPrintReturnControlC (__in PCHAR Format, ...)
Definition at line 78 of file debug.c.
References FALSE, va_start, and vDbgPrintExWithPrefixInternal().
ULONG DbgPrompt (__in PCHAR Prompt, __out_bcount(Length) PCHAR Response, __in ULONG Length)
Definition at line 364 of file debug.c.
References _STRING::Buffer, DebugPrompt(), _STRING::Length, _STRING::MaximumLength, and strlen().
Referenced by PspCatchCriticalBreak(), and RtlAssert().
NTSTATUS DbgQueryDebugFilterState (__in ULONG ComponentId, __in ULONG Level)
Definition at line 522 of file debug.c.
References NtQueryDebugFilterState().
NTSTATUS DbgSetDebugFilterState (__in ULONG ComponentId, __in ULONG Level, __in BOOLEAN State)
Definition at line 560 of file debug.c.
References NtSetDebugFilterState().
VOID DbgUnLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
Definition at line 456 of file debug.c.
References _KD_SYMBOLS_INFO::BaseOfDll, BREAKPOINT_UNLOAD_SYMBOLS, _KD_SYMBOLS_INFO::CheckSum, DebugService2(), _KD_SYMBOLS_INFO::ProcessId, and _KD_SYMBOLS_INFO::SizeOfImage.
Referenced by KeBugCheck2(), MiSegmentDelete(), and MmUnloadSystemImage().
ULONG vDbgPrintEx (__in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, __in va_list arglist)
Definition at line 164 of file debug.c.
References TRUE, and vDbgPrintExWithPrefixInternal().
ULONG vDbgPrintExWithPrefix (__in PCH Prefix, __in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, __in va_list arglist)
Definition at line 208 of file debug.c.
References TRUE, and vDbgPrintExWithPrefixInternal().
ULONG vDbgPrintExWithPrefixInternal (__in PCH Prefix, __in ULONG ComponentId, __in ULONG Level, __in PCHAR Format, __in va_list arglist, __in BOOLEAN ControlC)
Definition at line 255 of file debug.c.
References _vsnprintf(), _STRING::Buffer, DBG_STATUS_CONTROL_C, DbgBreakPointWithStatus(), DebugPrint(), except, EXCEPTION_EXECUTE_HANDLER, _STRING::Length, NtQueryDebugFilterState(), Status, STATUS_BREAKPOINT, STATUS_SUCCESS, strlen(), strncpy(), and TRUE.
Referenced by DbgPrint(), DbgPrintEx(), DbgPrintReturnControlC(), vDbgPrintEx(), and vDbgPrintExWithPrefix().