Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/idsched.c File Reference
idsched.c File Reference
#include "ki.h"
Functions
PKTHREAD FASTCALL KiIdleSchedule (PKPRCB CurrentPrcb)
Function Documentation
PKTHREAD FASTCALL KiIdleSchedule (PKPRCB CurrentPrcb)
Definition at line 28 of file idsched.c.
References AFFINITY_MASK, ASSERT, _KPRCB::CurrentThread, DISPATCH_LEVEL, FALSE, _KPRCB::IdleSchedule, _KPRCB::IdleThread, Index, KeFindFirstSetLeftAffinity, KeGetCurrentPrcb(), KeLowerIrql, KeNumberNodes, KeNumberProcessors, KeRaiseIrqlToSynchLevel(), KiAcquirePrcbLock(), KiAcquireTwoPrcbLocks(), KiClearIdleSummary(), KiClearSMTSummary(), KiFindReadyThread(), KiProcessorBlock, KiReleasePrcbLock(), KiSelectReadyThread(), KiSetContextSwapBusy(), _KPRCB::MultiThreadProcessorSet, _KPRCB::NextThread, NULL, _KPRCB::Number, _KPRCB::ParentNode, _KNODE::ProcessorMask, _KPRCB::ReadySummary, Running, and _KTHREAD::State.