Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/alloc.c File Reference
alloc.c File Reference
#include "wmikmp.h"
Macros
#define DSCHUNKSIZE 64
#define GECHUNKSIZE 512
#define ISCHUNKSIZE 2048
#define MRCHUNKSIZE 16
Functions
PBDATASOURCE WmipAllocDataSource (void)
PBGUIDENTRY WmipAllocGuidEntryX (ULONG LINE, PCHAR FILE)
void WmipDSCleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
PBDATASOURCE WmipFindDSByProviderId (ULONG_PTR ProviderId)
PBGUIDENTRY WmipFindGEByGuid (LPGUID Guid, BOOLEAN MakeTopOfList)
PBINSTANCESET WmipFindISByGuid (PBDATASOURCE DataSource, GUID UNALIGNED *Guid)
PBINSTANCESET WmipFindISinGEbyName (PBGUIDENTRY GuidEntry, PWCHAR InstanceName, PULONG InstanceIndex)
PMOFRESOURCE WmipFindMRByNames (LPCWSTR ImagePath, LPCWSTR MofResourceName)
void WmipGECleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
void WmipISCleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
BOOLEAN WmipIsNumber (LPCWSTR String)
void WmipMRCleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
void WmipMRCleanup (IN PCHUNKINFO ChunkInfo, IN PENTRYHEADER Entry)
BOOLEAN WmipRealloc (PVOID *Buffer, ULONG CurrentSize, ULONG NewSize, BOOLEAN FreeOriginalBuffer)
Variables
GUID GUID_MOF_RESOURCE_ADDED_NOTIFICATION = {0xb48d49a2, 0xe777, 0x11d0, 0xa5, 0xc, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10}
GUID GUID_MOF_RESOURCE_REMOVED_NOTIFICATION = {0xb48d49a3, 0xe777, 0x11d0, 0xa5, 0xc, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10}
GUID GUID_REGISTRATION_CHANGE_NOTIFICATION = {0xb48d49a1, 0xe777, 0x11d0, 0xa5, 0xc, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10}
CHUNKINFO WmipDSChunkInfo
LIST_ENTRY WmipDSHead
PLIST_ENTRY WmipDSHeadPtr
CHUNKINFO WmipGEChunkInfo
LIST_ENTRY WmipGEHead
PLIST_ENTRY WmipGEHeadPtr
CHUNKINFO WmipISChunkInfo
CHUNKINFO WmipMRChunkInfo
LIST_ENTRY WmipMRHead
PLIST_ENTRY WmipMRHeadPtr
Macro Definition Documentation
#define DSCHUNKSIZE 64
Definition at line 44 of file alloc.c.
#define GECHUNKSIZE 512
Definition at line 70 of file alloc.c.
#define ISCHUNKSIZE 2048
Definition at line 96 of file alloc.c.
#define MRCHUNKSIZE 16
Definition at line 117 of file alloc.c.
Function Documentation
PBDATASOURCE WmipAllocDataSource (void)
Definition at line 155 of file alloc.c.
References AVGMOFRESOURCECOUNT, InitializeListHead(), tagDATASOURCE::ISHead, memset(), tagDATASOURCE::MofResourceCount, tagDATASOURCE::MofResources, NULL, tagDATASOURCE::StaticMofResources, and WmipAllocEntry().
Referenced by WmipAddDataSource().
PBGUIDENTRY WmipAllocGuidEntryX (ULONG LINE, PCHAR FILE)
Definition at line 317 of file alloc.c.
References tagGUIDENTRY::CollectInProgress, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, ExAllocatePoolWithTag, ExFreePool(), InitializeListHead(), tagGUIDENTRY::ISHead, NonPagedPool, NULL, tagGUIDENTRY::ObjectHead, PsGetCurrentProcessId(), PsGetCurrentThreadId(), tagGUIDENTRY::RefCount, UNREFERENCED_PARAMETER, WmipAllocEntry(), WmipDebugPrintEx, and WMIPOOLTAG.
void WmipDSCleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
Definition at line 189 of file alloc.c.
References CONTAINING_RECORD, tagInstanceSet::DataSource, FLAG_ENTRY_INVALID, tagInstanceSet::Flags, tagDATASOURCE::Flags, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, tagInstanceSet::GuidEntry, tagInstanceSet::GuidISList, IS_NEWLY_REGISTERED, tagGUIDENTRY::ISCount, IsEqualGUID, tagDATASOURCE::ISHead, tagDATASOURCE::MofResourceCount, tagDATASOURCE::MofResources, NULL, tagDATASOURCE::RegistryPath, RemoveEntryList(), tagDATASOURCE::StaticMofResources, UNREFERENCED_PARAMETER, WmipAssert, WmipBinaryMofGuid, WmipEnterSMCritSection, WmipFree, WmipGenerateBinaryMofNotification(), WmipLeaveSMCritSection, WmipUnreferenceGE, WmipUnreferenceIS, and WmipUnreferenceMR.
PBDATASOURCE WmipFindDSByProviderId (ULONG_PTR ProviderId)
Definition at line 466 of file alloc.c.
References CONTAINING_RECORD, DS_SIGNATURE, _LIST_ENTRY::Flink, NULL, tagDATASOURCE::ProviderId, tagDATASOURCE::Signature, WmipAssert, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceDS.
Referenced by WmipDereferenceEvent().
PBGUIDENTRY WmipFindGEByGuid (LPGUID Guid, BOOLEAN MakeTopOfList)
Definition at line 410 of file alloc.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, GE_SIGNATURE, tagGUIDENTRY::Guid, InsertHeadList(), IsEqualGUID, NULL, RemoveEntryList(), tagGUIDENTRY::Signature, WmipAssert, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceGE.
Referenced by WmipCreateUMLogger(), WmipDetermineInstanceBaseIndex(), WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), WmipEnableDisableTrace(), WmipIncludeStaticNames(), WmipLinkDataSourceToList(), WmipMangleInstanceName(), WmipNtDllLoggerInfo(), WmipOpenBlock(), WmipProcessEvent(), WmipRegisterUMGuids(), and WmipUnregisterGuids().
PBINSTANCESET WmipFindISByGuid (PBDATASOURCE DataSource, GUID UNALIGNED * Guid)
Definition at line 511 of file alloc.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, tagInstanceSet::GuidEntry, IS_SIGNATURE, IsEqualGUID, tagDATASOURCE::ISHead, NULL, tagInstanceSet::Signature, WmipAssert, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceIS.
Referenced by WmipRegisterUMGuids().
PBINSTANCESET WmipFindISinGEbyName (PBGUIDENTRY GuidEntry, PWCHAR InstanceName, PULONG InstanceIndex)
Definition at line 625 of file alloc.c.
References _wtoi(), ISBASENAME::BaseIndex, ISBASENAME::BaseName, CONTAINING_RECORD, tagInstanceSet::Count, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, IS_SIGNATURE, tagInstanceSet::IsBaseName, tagGUIDENTRY::ISHead, tagInstanceSet::IsStaticNames, NULL, tagInstanceSet::Signature, ISSTATICENAMES::StaticNamePtr, wcscmp(), wcslen(), wcsncmp(), WmipAssert, WmipEnterSMCritSection, WmipIsNumber(), WmipLeaveSMCritSection, and WmipReferenceIS.
Referenced by WmipMangleInstanceName().
PMOFRESOURCE WmipFindMRByNames (LPCWSTR ImagePath, LPCWSTR MofResourceName)
Definition at line 560 of file alloc.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, MOFRESOURCE::MofResourceName, MR_SIGNATURE, NULL, MOFRESOURCE::RegistryPath, MOFRESOURCE::Signature, wcscmp(), WmipAssert, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceMR.
Referenced by WmipAddMofResource().
void WmipGECleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
Definition at line 281 of file alloc.c.
References tagGUIDENTRY::CollectInProgress, _GUID::Data4, ExFreePool(), FLAG_ENTRY_INVALID, tagGUIDENTRY::Flags, tagGUIDENTRY::Guid, NULL, UNREFERENCED_PARAMETER, and WmipAssert.
void WmipISCleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
Definition at line 354 of file alloc.c.
References FLAG_ENTRY_INVALID, tagInstanceSet::Flags, tagInstanceSet::IsBaseName, NULL, UNREFERENCED_PARAMETER, WmipAssert, and WmipFree.
BOOLEAN WmipIsNumber (LPCWSTR String)
Definition at line 610 of file alloc.c.
References FALSE, TRUE, and UNICODE_NULL.
Referenced by WmipFindISinGEbyName(), and WmipPrepareWnodeSI().
void WmipMRCleanup (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
void WmipMRCleanup (IN PCHUNKINFO ChunkInfo, IN PENTRYHEADER Entry)
Definition at line 373 of file alloc.c.
References MOFRESOURCE::Flags, MOFEVENT_ACTION_IMAGE_PATH, MOFEVENT_ACTION_REGISTRY_PATH, MOFRESOURCE::MofResourceName, MR_FLAG_USER_MODE, NULL, PAGED_CODE, MOFRESOURCE::RegistryPath, UNREFERENCED_PARAMETER, WmipFree, and WmipGenerateMofResourceNotification().
BOOLEAN WmipRealloc (PVOID * Buffer, ULONG CurrentSize, ULONG NewSize, BOOLEAN FreeOriginalBuffer)
Definition at line 714 of file alloc.c.
References FALSE, memcpy(), memset(), NULL, TRUE, WmipAlloc, WmipAssert, and WmipFree.
Referenced by WmipAddMofResource().
Variable Documentation
GUID GUID_MOF_RESOURCE_ADDED_NOTIFICATION = {0xb48d49a2, 0xe777, 0x11d0, 0xa5, 0xc, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10}
Definition at line 31 of file alloc.c.
Referenced by WmipAddDataSource(), WmipIoControl(), and WmipUpdateDataSource().
GUID GUID_MOF_RESOURCE_REMOVED_NOTIFICATION = {0xb48d49a3, 0xe777, 0x11d0, 0xa5, 0xc, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10}
Definition at line 36 of file alloc.c.
Referenced by WmipIoControl(), and WmipUpdateDataSource().
GUID GUID_REGISTRATION_CHANGE_NOTIFICATION = {0xb48d49a1, 0xe777, 0x11d0, 0xa5, 0xc, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10}
Definition at line 26 of file alloc.c.
CHUNKINFO WmipDSChunkInfo
Initial value:
=
{
    { NULL, NULL },
    sizeof(DATASOURCE),
    DSCHUNKSIZE,
    WmipDSCleanup,
    FLAG_ENTRY_REMOVE_LIST,
    DS_SIGNATURE
}
Definition at line 52 of file alloc.c.
Referenced by WmipInitializeDataStructs().
LIST_ENTRY WmipDSHead
Definition at line 62 of file alloc.c.
Referenced by WmipInitializeDataStructs().
PLIST_ENTRY WmipDSHeadPtr
Definition at line 63 of file alloc.c.
Referenced by WmipInitializeDataStructs(), and WmipLinkDataSourceToList().
CHUNKINFO WmipGEChunkInfo
Initial value:
=
{
    { NULL, NULL },
    sizeof(GUIDENTRY),
    GECHUNKSIZE,
    WmipGECleanup,
    FLAG_ENTRY_REMOVE_LIST,
    GE_SIGNATURE
}
Definition at line 78 of file alloc.c.
Referenced by WmipInitializeDataStructs().
LIST_ENTRY WmipGEHead
Definition at line 88 of file alloc.c.
Referenced by WmipInitializeDataStructs().
PLIST_ENTRY WmipGEHeadPtr
Definition at line 89 of file alloc.c.
Referenced by WmipDisableTraceProviders(), WmipEnableDisableTrace(), WmipEnumerateGuids(), WmipInitializeDataStructs(), WmipLinkDataSourceToList(), WmipNtDllLoggerInfo(), and WmipOpenBlock().
CHUNKINFO WmipISChunkInfo
Initial value:
=
{
    { NULL, NULL },
    sizeof(INSTANCESET),
    ISCHUNKSIZE,
    WmipISCleanup,
    0,
    IS_SIGNATURE
}
Definition at line 104 of file alloc.c.
Referenced by WmipInitializeDataStructs().
CHUNKINFO WmipMRChunkInfo
Initial value:
=
{
    { NULL, NULL },
    sizeof(MOFRESOURCE),
    MRCHUNKSIZE,
    WmipMRCleanup,
    FLAG_ENTRY_REMOVE_LIST,
    MR_SIGNATURE
}
Definition at line 125 of file alloc.c.
Referenced by WmipInitializeDataStructs().
LIST_ENTRY WmipMRHead
Definition at line 135 of file alloc.c.
Referenced by WmipInitializeDataStructs().
PLIST_ENTRY WmipMRHeadPtr
Definition at line 136 of file alloc.c.
Referenced by WmipAddMofResource(), WmipEnumerateMofResources(), and WmipInitializeDataStructs().