Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/vacbsup.c File Reference
vacbsup.c File Reference
#include "cc.h"
#include "ex.h"
Macros
#define CcMoveVacbToReuseFree(V)
#define CcMoveVacbToReuseTail(V)
#define CheckedDec(N)
#define GetVacb(SCM, OFF)
#define GrowArrayForBcbListHeads(_VacbArraySize)
#define me 0x000000040
#define SizeOfVacbArray(LSZ)
Functions
VOID CcAdjustVacbLevelLockCount (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN LONG Adjustment)
VOID CcCalculateVacbLevelLockCount (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVACB *VacbArray, IN ULONG Level)
NTSTATUS FASTCALL CcCreateVacbArray (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER NewSectionSize)
VOID CcDereferenceFileOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset)
VOID CcDrainVacbLevelZone ()
NTSTATUS CcExtendVacbArray (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER NewSectionSize)
VOID FASTCALL CcFreeVirtualAddress (IN PVACB Vacb)
VOID CcGetActiveVacb (IN PSHARED_CACHE_MAP SharedCacheMap, OUT PVACB *Vacb, OUT PULONG Page, OUT PULONG Dirty)
PLIST_ENTRY CcGetBcbListHead (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN BOOLEAN FailToSuccessor)
PLIST_ENTRY CcGetBcbListHeadLargeOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN BOOLEAN FailToSuccessor)
PVACB CcGetVacbLargeOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset)
PVACB CcGetVacbMiss (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset, IN OUT PKLOCK_QUEUE_HANDLE LockHandle, IN LOGICAL HasBcbListHeads)
PVOID CcGetVirtualAddress (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset, OUT PVACB *Vacb, IN OUT PULONG ReceivedLength)
PVOID CcGetVirtualAddressIfMapped (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, OUT PVACB *Vacb, OUT PULONG ReceivedLength)
VOID CcInitializeVacbs ()
ULONG CcPrefillVacbLevelZone (IN ULONG NumberNeeded, OUT PKLOCK_QUEUE_HANDLE LockHandle, IN ULONG NeedBcbListHeads, IN LOGICAL AcquireBcbSpinLock, IN PSHARED_CACHE_MAP SharedCacheMap OPTIONAL)
VOID CcReferenceFileOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset)
VOID CcSetActiveVacb (IN PSHARED_CACHE_MAP SharedCacheMap, IN OUT PVACB *Vacb, IN ULONG Page, IN ULONG Dirty)
VOID CcSetVacbLargeOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN PVACB Vacb)
VOID CcUnmapVacb (IN PVACB Vacb, IN PSHARED_CACHE_MAP SharedCacheMap, IN BOOLEAN UnmapBehind)
BOOLEAN FASTCALL CcUnmapVacbArray (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset OPTIONAL, IN ULONG Length, IN BOOLEAN UnmapBehind)
VOID CcWaitOnActiveCount (IN PSHARED_CACHE_MAP SharedCacheMap)
_inline VOID ReferenceVacbLevel (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVACB *VacbArray, IN ULONG Level, IN LONG Amount, IN LOGICAL Special)
_inline VOID SetVacb (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER Offset, IN PVACB Vacb)
Macro Definition Documentation
#define CcMoveVacbToReuseFree (V)
Value:
RemoveEntryList(&(V)->LruList);                 \
                                        InsertHeadList( &CcVacbFreeList, &(V)->LruList );
Definition at line 130 of file vacbsup.c.
Referenced by CcFreeVirtualAddress(), CcGetVacbMiss(), and CcUnmapVacbArray().
#define CcMoveVacbToReuseTail (V)
Value:
RemoveEntryList(&(V)->LruList);                 \
                                        InsertTailList( &CcVacbLru, &(V)->LruList );
Definition at line 133 of file vacbsup.c.
Referenced by CcFreeVirtualAddress(), CcGetVacbMiss(), CcGetVirtualAddress(), and CcGetVirtualAddressIfMapped().
#define CheckedDec (N)
Value:
{  \
    ASSERT((N) != 0);    \
    (N) -= 1;            \
}
Definition at line 161 of file vacbsup.c.
Referenced by CcFreeVirtualAddress(), and CcGetVacbMiss().
#define GetVacb (SCM, OFF)
Value:
(\
    ((SCM)->SectionSize.QuadPart > VACB_SIZE_OF_FIRST_LEVEL) ?                            \
    CcGetVacbLargeOffset((SCM),(OFF).QuadPart) :                                          \
    (SCM)->Vacbs[(OFF).LowPart >> VACB_OFFSET_SHIFT]                                      \
)
Definition at line 78 of file vacbsup.c.
Referenced by CcGetVacbMiss(), CcGetVirtualAddress(), CcGetVirtualAddressIfMapped(), and CcUnmapVacbArray().
#define GrowArrayForBcbListHeads (_VacbArraySize)
Value:
{                                        \
    (_VacbArraySize) =                                                                    \
    (_VacbArraySize) + (ULONG)AlignedToSize( (_VacbArraySize) , sizeof(LIST_ENTRY) );     \
}
Definition at line 156 of file vacbsup.c.
Referenced by CcCreateVacbArray(), and CcExtendVacbArray().
#define me 0x000000040
Definition at line 29 of file vacbsup.c.
#define SizeOfVacbArray (LSZ)
Value:
(\
    ((LSZ).HighPart != 0) ? MAXULONG :                                                    \
    ((LSZ).LowPart > (PREALLOCATED_VACBS * VACB_MAPPING_GRANULARITY) ?                    \
     (((LSZ).LowPart >> VACB_OFFSET_SHIFT) * sizeof(PVACB)) :                             \
     (PREALLOCATED_VACBS * sizeof(PVACB)))                                                \
)
Definition at line 141 of file vacbsup.c.
Referenced by CcCreateVacbArray(), CcExtendVacbArray(), and CcGetBcbListHead().
Function Documentation
VOID CcAdjustVacbLevelLockCount (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN LONG Adjustment)
Definition at line 2625 of file vacbsup.c.
References ASSERT, CcSetVacbLargeOffset(), FALSE, FileOffset, IsVacbLevelReferenced(), ReferenceVacbLevel(), TRUE, VACB_LEVEL_SHIFT, VACB_OFFSET_SHIFT, VACB_SIZE_OF_FIRST_LEVEL, and VACB_SPECIAL_DEREFERENCE.
VOID CcCalculateVacbLevelLockCount (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVACB * VacbArray, IN ULONG Level)
Definition at line 2729 of file vacbsup.c.
References _BCB::BcbLinks, _LIST_ENTRY::Blink, CACHE_NTC_BCB, CONTAINING_RECORD, Count, FlagOn, Index, MODIFIED_WRITE_DISABLED, _BCB::NodeTypeCode, NULL, _VACB_LEVEL_REFERENCE::Reference, VACB_LAST_INDEX_FOR_LEVEL, and VacbLevelReference().
Referenced by CcExtendVacbArray().
NTSTATUS FASTCALL CcCreateVacbArray (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER NewSectionSize)
Definition at line 1328 of file vacbsup.c.
References ASSERT, BEGIN_BCB_LIST_ARRAY, CcMaxVacbLevelsSeen, ExAllocatePoolWithTag, FALSE, FlagOn, GrowArrayForBcbListHeads, InsertHeadList(), MODIFIED_WRITE_DISABLED, NonPagedPool, NULL, PAGE_SIZE, PREALLOCATED_VACBS, RtlZeroMemory, SIZE_PER_BCB_LIST, SizeOfVacbArray, STATUS_INSUFFICIENT_RESOURCES, STATUS_SECTION_TOO_BIG, STATUS_SUCCESS, TRUE, VACB_LEVEL_BLOCK_SIZE, VACB_LEVEL_SHIFT, VACB_MAPPING_GRANULARITY, VACB_NUMBER_OF_LEVELS, and VACB_OFFSET_SHIFT.
Referenced by CcInitializeCacheMap().
VOID CcDereferenceFileOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset)
Definition at line 1127 of file vacbsup.c.
References ASSERT, CcAcquireBcbSpinLockAndVacbLock(), CcReleaseBcbSpinLockAndVacbLock(), DISPATCH_LEVEL, KeGetCurrentIrql(), SetVacb(), TRUE, VACB_SIZE_OF_FIRST_LEVEL, and VACB_SPECIAL_DEREFERENCE.
Referenced by CcPinFileData().
VOID CcDrainVacbLevelZone ()
Definition at line 2223 of file vacbsup.c.
References CcAcquireVacbLock, CcMaxVacbLevelsSeen, CcReleaseVacbLock, CcVacbLevelEntries, CcVacbLevelFreeList, CcVacbLevelWithBcbsEntries, CcVacbLevelWithBcbsFreeList, ExFreePool(), and NULL.
Referenced by CcDeleteMbcb(), CcGetVacbMiss(), and CcUnmapVacbArray().
NTSTATUS CcExtendVacbArray (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER NewSectionSize)
Definition at line 1507 of file vacbsup.c.
References ASSERT, BEGIN_BCB_LIST_ARRAY, _LIST_ENTRY::Blink, CcAcquireBcbSpinLockAndVacbLock(), CcAllocateVacbLevel(), CcCalculateVacbLevelLockCount(), CcDeallocateVacbLevel(), CcMaxVacbLevelsSeen, CcPrefillVacbLevelZone(), CcReleaseBcbSpinLockAndVacbLock(), CcVacbLevelEntries, CONTAINING_RECORD, ExAllocatePoolWithTag, ExFreePool(), FALSE, FileOffset, FlagOn, _LIST_ENTRY::Flink, GrowArrayForBcbListHeads, InsertHeadList(), InsertTailList(), IsVacbLevelReferenced(), MODIFIED_WRITE_DISABLED, NonPagedPool, NULL, PAGE_SIZE, _LARGE_INTEGER::QuadPart, ReferenceVacbLevel(), RemoveEntryList(), RtlCopyMemory, RtlZeroMemory, SIZE_PER_BCB_LIST, SizeOfVacbArray, STATUS_INSUFFICIENT_RESOURCES, STATUS_SECTION_TOO_BIG, STATUS_SUCCESS, TRUE, VACB_LEVEL_BLOCK_SIZE, VACB_LEVEL_SHIFT, VACB_NUMBER_OF_LEVELS, VACB_OFFSET_SHIFT, and VACB_SIZE_OF_FIRST_LEVEL.
Referenced by CcInitializeCacheMap(), and CcSetFileSizes().
VOID FASTCALL CcFreeVirtualAddress (IN PVACB Vacb)
Definition at line 978 of file vacbsup.c.
References ASSERT, CcAcquireVacbLock, CcMoveVacbToReuseFree, CcMoveVacbToReuseTail, CcReleaseVacbLock, CheckedDec, FALSE, KeSetEvent(), NULL, _SHARED_CACHE_MAP::VacbActiveCount, and _SHARED_CACHE_MAP::WaitOnActiveCount.
Referenced by CcCopyRead(), CcDeleteBcbs(), CcFastCopyRead(), CcFlushCache(), CcFreeActiveVacb(), CcMapAndCopy(), CcMdlRead(), CcPerformReadAhead(), CcPinFileData(), CcPinMappedData(), CcPrepareMdlWrite(), CcPurgeAndClearCacheSection(), and CcUnpinFileDataEx().
VOID CcGetActiveVacb (IN PSHARED_CACHE_MAP SharedCacheMap, OUT PVACB * Vacb, OUT PULONG Page, OUT PULONG Dirty)
Definition at line 3236 of file vacbsup.c.
References ACTIVE_PAGE_IS_DIRTY, ExAcquireFastLock, ExReleaseFastLock, and NULL.
PLIST_ENTRY CcGetBcbListHead (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN BOOLEAN FailToSuccessor)
Definition at line 2286 of file vacbsup.c.
References Add2Ptr, BCB_LIST_SHIFT, BEGIN_BCB_LIST_ARRAY, CcGetBcbListHeadLargeOffset(), FlagOn, MODIFIED_WRITE_DISABLED, SizeOfVacbArray, and VACB_SIZE_OF_FIRST_LEVEL.
Referenced by CcFindBcb().
PLIST_ENTRY CcGetBcbListHeadLargeOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN BOOLEAN FailToSuccessor)
Definition at line 2397 of file vacbsup.c.
References ASSERT, Index, NULL, TRUE, VACB_LAST_INDEX_FOR_LEVEL, VACB_LEVEL_BLOCK_SIZE, VACB_LEVEL_SHIFT, VACB_NUMBER_OF_LEVELS, VACB_OFFSET_SHIFT, and VACB_SIZE_OF_FIRST_LEVEL.
Referenced by CcGetBcbListHead(), and CcSetVacbLargeOffset().
PVACB CcGetVacbLargeOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset)
Definition at line 2824 of file vacbsup.c.
References ASSERT, CcBeyondVacbs, CcVacbs, NULL, VACB_LEVEL_SHIFT, VACB_OFFSET_SHIFT, and VACB_SIZE_OF_FIRST_LEVEL.
PVACB CcGetVacbMiss (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset, IN OUT PKLOCK_QUEUE_HANDLE LockHandle, IN LOGICAL HasBcbListHeads)
Definition at line 465 of file vacbsup.c.
References _VACB::ActiveCount, _SHARED_CACHE_MAP::ActiveVacb, ASSERT, _VACB::BaseAddress, CcAcquireBcbSpinLockAndVacbLock(), CcAcquireMasterLock, CcAcquireMasterLockAtDpcLevel, CcAcquireVacbLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcDrainVacbLevelZone(), CcFreeActiveVacb(), CcIncrementOpenCount, CcMaxVacbLevelsSeen, CcMoveVacbToReuseFree, CcMoveVacbToReuseTail, CcPrefillVacbLevelZone(), CcReleaseBcbSpinLockAndVacbLock(), CcReleaseMasterLock, CcReleaseMasterLockFromDpcLevel, CcReleaseVacbLock, CcScheduleLazyWriteScan(), CcUnmapVacb(), CcUnmapVacbArray(), CcVacbFreeList, CcVacbLru, CheckedDec, CONTAINING_RECORD, DebugTrace, DebugTrace2, _SHARED_CACHE_MAP::DirtyPages, ExAcquirePushLockShared(), ExRaiseStatus(), ExReleasePushLockShared(), FALSE, _SHARED_CACHE_MAP::FileObject, FileOffset, _VACB::FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, FsRtlNormalizeNtstatus(), GetActiveVacbAtDpcLevel, GetVacb, _LARGE_INTEGER::HighPart, InsertTailList(), IsListEmpty, KeSetEvent(), LazyWriter, _LARGE_INTEGER::LowPart, _VACB::LruList, mm, MmMapViewInSystemCache(), MODIFIED_WRITE_DISABLED, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, _VACB::Overlay, _LARGE_INTEGER::QuadPart, RANDOM_ACCESS_SEEN, RemoveEntryList(), _LAZY_WRITER::ScanActive, _FILE_OBJECT::SectionObjectPointer, SEQUENTIAL_MAP_LIMIT, SetVacb(), _VACB::SharedCacheMap, _SECTION_OBJECT_POINTERS::SharedCacheMap, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_UNEXPECTED_MM_MAP_ERROR, TRUE, VACB_MAPPING_GRANULARITY, VACB_SIZE_OF_FIRST_LEVEL, and WRITE_QUEUED.
Referenced by CcGetVirtualAddress().
PVOID CcGetVirtualAddress (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset, OUT PVACB * Vacb, IN OUT PULONG ReceivedLength)
Definition at line 345 of file vacbsup.c.
References _VACB::ActiveCount, ASSERT, _VACB::BaseAddress, CcAcquireBcbSpinLockAndVacbLock(), CcGetVacbMiss(), CcMoveVacbToReuseTail, CcReleaseBcbSpinLockAndVacbLock(), DISPATCH_LEVEL, ExAcquirePushLockShared(), ExReleasePushLockShared(), FALSE, FlagOn, GetVacb, KeGetCurrentIrql(), MODIFIED_WRITE_DISABLED, NULL, _VACB::Overlay, TRUE, and VACB_MAPPING_GRANULARITY.
PVOID CcGetVirtualAddressIfMapped (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, OUT PVACB * Vacb, OUT PULONG ReceivedLength)
Definition at line 219 of file vacbsup.c.
References ASSERT, CcAcquireVacbLock, CcMoveVacbToReuseTail, CcReleaseVacbLock, DISPATCH_LEVEL, ExAcquirePushLockExclusive(), ExReleasePushLockExclusive(), GetVacb, KeGetCurrentIrql(), NULL, and VACB_MAPPING_GRANULARITY.
Referenced by CcFlushCache().
VOID CcInitializeVacbs ()
Definition at line 174 of file vacbsup.c.
References CcBeyondVacbs, CcNumberVacbs, CcVacbFreeList, CcVacbLru, CcVacbs, ExAllocatePoolWithTag, InitializeListHead(), InsertTailList(), _VACB::LruList, MmSizeOfSystemCacheInPages, NonPagedPool, NULL, PAGE_SHIFT, RtlZeroMemory, and VACB_OFFSET_SHIFT.
Referenced by CcInitializeCacheManager().
ULONG CcPrefillVacbLevelZone (IN ULONG NumberNeeded, OUT PKLOCK_QUEUE_HANDLE LockHandle, IN ULONG NeedBcbListHeads, IN LOGICAL AcquireBcbSpinLock, IN PSHARED_CACHE_MAP SharedCacheMap OPTIONAL)
Definition at line 2094 of file vacbsup.c.
References CcAcquireBcbSpinLockAndVacbLock(), CcReleaseBcbSpinLockAndVacbLock(), CcVacbLevelEntries, CcVacbLevelFreeList, CcVacbLevelWithBcbsEntries, CcVacbLevelWithBcbsFreeList, ExAllocatePoolWithTag, FALSE, NonPagedPool, NULL, RtlZeroMemory, TRUE, and VACB_LEVEL_BLOCK_SIZE.
Referenced by CcExtendVacbArray(), CcGetVacbMiss(), CcReferenceFileOffset(), and CcSetDirtyInMask().
VOID CcReferenceFileOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER FileOffset)
Definition at line 1065 of file vacbsup.c.
References ASSERT, CcMaxVacbLevelsSeen, CcPrefillVacbLevelZone(), CcReleaseBcbSpinLockAndVacbLock(), DISPATCH_LEVEL, ExRaiseStatus(), FlagOn, KeGetCurrentIrql(), MODIFIED_WRITE_DISABLED, SetVacb(), STATUS_INSUFFICIENT_RESOURCES, TRUE, VACB_SIZE_OF_FIRST_LEVEL, and VACB_SPECIAL_REFERENCE.
Referenced by CcPinFileData().
VOID CcSetActiveVacb (IN PSHARED_CACHE_MAP SharedCacheMap, IN OUT PVACB * Vacb, IN ULONG Page, IN ULONG Dirty)
Definition at line 3289 of file vacbsup.c.
References ACTIVE_PAGE_IS_DIRTY, _LIST_ENTRY::Blink, CcAcquireMasterLock, CcDirtySharedCacheMapList, CcFirstDelay, CcFreeActiveVacb(), CcReleaseMasterLock, CcTotalDirtyPages, ExAcquireFastLock, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, ExReleaseFastLock, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, KeSetTimer(), LazyWriter, NULL, _LAZY_WRITER::ScanActive, _LAZY_WRITER::ScanDpc, _LAZY_WRITER::ScanTimer, SetFlag, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, and TRUE.
VOID CcSetVacbLargeOffset (IN PSHARED_CACHE_MAP SharedCacheMap, IN LONGLONG FileOffset, IN PVACB Vacb)
Definition at line 2911 of file vacbsup.c.
References ASSERT, _LIST_ENTRY::Blink, CACHE_NTC_BCB, CcAllocateVacbLevel(), CcDeallocateVacbLevel(), CcGetBcbListHeadLargeOffset(), CONTAINING_RECORD, FALSE, FileOffset, FlagOn, _LIST_ENTRY::Flink, Index, IsVacbLevelReferenced(), MODIFIED_WRITE_DISABLED, NULL, ReferenceVacbLevel(), TRUE, VACB_LAST_INDEX_FOR_LEVEL, VACB_LEVEL_BLOCK_SIZE, VACB_LEVEL_SHIFT, VACB_NUMBER_OF_LEVELS, VACB_OFFSET_SHIFT, VACB_SIZE_OF_FIRST_LEVEL, VACB_SPECIAL_DEREFERENCE, and VACB_SPECIAL_FIRST_VALID.
Referenced by CcAdjustVacbLevelLockCount(), and SetVacb().
VOID CcUnmapVacb (IN PVACB Vacb, IN PSHARED_CACHE_MAP SharedCacheMap, IN BOOLEAN UnmapBehind)
Definition at line 1276 of file vacbsup.c.
References ASSERT, DebugTrace, FlagOn, mm, MmUnmapViewInSystemCache(), NULL, and ONLY_SEQUENTIAL_ONLY_SEEN.
Referenced by CcGetVacbMiss(), and CcUnmapVacbArray().
BOOLEAN FASTCALL CcUnmapVacbArray (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset OPTIONAL, IN ULONG Length, IN BOOLEAN UnmapBehind)
Definition at line 1918 of file vacbsup.c.
References _VACB::ActiveCount, ARGUMENT_PRESENT, BEGIN_BCB_LIST_ARRAY, CcAcquireBcbSpinLockAndVacbLock(), CcDrainVacbLevelZone(), CcMoveVacbToReuseFree, CcReleaseBcbSpinLockAndVacbLock(), CcUnmapVacb(), ExAcquirePushLockShared(), ExReleasePushLockShared(), FALSE, FileOffset, FlagOn, GetVacb, MODIFIED_WRITE_DISABLED, NULL, _VACB::Overlay, _LARGE_INTEGER::QuadPart, SetVacb(), _VACB::SharedCacheMap, TRUE, and VACB_MAPPING_GRANULARITY.
Referenced by CcGetVacbMiss(), CcPurgeCacheSection(), CcSetPrivateWriteFile(), and CcUnmapAndPurge().
VOID CcWaitOnActiveCount (IN PSHARED_CACHE_MAP SharedCacheMap)
Definition at line 1182 of file vacbsup.c.
References CcAcquireVacbLock, CcReleaseVacbLock, Executive, FALSE, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, and NULL.
Referenced by CcDeleteSharedCacheMap(), CcPurgeCacheSection(), and CcSetPrivateWriteFile().
_inline VOID ReferenceVacbLevel (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVACB * VacbArray, IN ULONG Level, IN LONG Amount, IN LOGICAL Special)
Definition at line 105 of file vacbsup.c.
References ASSERT, _VACB_LEVEL_REFERENCE::Reference, _VACB_LEVEL_REFERENCE::SpecialReference, and VacbLevelReference().
Referenced by CcAdjustVacbLevelLockCount(), CcExtendVacbArray(), and CcSetVacbLargeOffset().
_inline VOID SetVacb (IN PSHARED_CACHE_MAP SharedCacheMap, IN LARGE_INTEGER Offset, IN PVACB Vacb)
Definition at line 86 of file vacbsup.c.
References CcSetVacbLargeOffset(), VACB_OFFSET_SHIFT, VACB_SIZE_OF_FIRST_LEVEL, and VACB_SPECIAL_FIRST_VALID.
Referenced by CcDereferenceFileOffset(), CcGetVacbMiss(), CcReferenceFileOffset(), and CcUnmapVacbArray().