Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/amd64/exdsptch.c File Reference
exdsptch.c File Reference
#include "ntrtlp.h"
Macros
#define ADD_IMM32_OP 0x81
#define ADD_IMM8_OP 0x83
#define IS_REX_PREFIX(x) (((x) & 0xf0) == 0x40)
#define JMP_IMM32_OP 0xe9
#define JMP_IMM8_OP 0xeb
#define JMP_IND_OP 0xff
#define LEA_OP 0x8d
#define POP_OP 0x58
#define REP_PREFIX 0xf3
#define RET_OP 0xc3
#define RET_OP_2 0xc2
#define SIZE64_PREFIX 0x48
Functions
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
VOID KiExceptionDispatch (VOID)
BOOLEAN RtlDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord)
PRUNTIME_FUNCTION RtlLookupFunctionEntry (IN ULONG64 ControlPc, OUT PULONG64 ImageBase, IN OUT PUNWIND_HISTORY_TABLE HistoryTable OPTIONAL)
FORCEINLINE PRUNTIME_FUNCTION RtlpConvertFunctionEntry (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase)
VOID RtlpCopyContext (OUT PCONTEXT Destination, IN PCONTEXT Source)
DECLSPEC_NOINLINE VOID RtlpGetStackLimits (OUT PULONG64 LowLimit, OUT PULONG64 HighLimit)
BOOLEAN RtlpIsFrameInBounds (IN OUT PULONG64 LowLimit, IN ULONG64 StackFrame, IN OUT PULONG64 HighLimit)
PUNWIND_INFO RtlpLookupPrimaryUnwindInfo (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase, OUT PRUNTIME_FUNCTION *PrimaryEntry)
PRUNTIME_FUNCTION RtlpSameFunction (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase, IN ULONG64 ControlPc)
PRUNTIME_FUNCTION RtlpUnwindPrologue (IN ULONG64 ImageBase, IN ULONG64 ControlPc, IN ULONG64 FrameBase, IN PRUNTIME_FUNCTION FunctionEntry, IN OUT PCONTEXT ContextRecord, IN OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers OPTIONAL)
VOID RtlUnwind (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue)
VOID RtlUnwindEx (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue, IN PCONTEXT OriginalContext, IN PUNWIND_HISTORY_TABLE HistoryTable OPTIONAL)
PEXCEPTION_ROUTINE RtlVirtualUnwind (IN ULONG HandlerType, IN ULONG64 ImageBase, IN ULONG64 ControlPc, IN PRUNTIME_FUNCTION FunctionEntry, IN OUT PCONTEXT ContextRecord, OUT PVOID *HandlerData, OUT PULONG64 EstablisherFrame, IN OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers OPTIONAL)
Variables
PVOID RtlpFunctionAddressTable []
UCHAR RtlpUnwindOpSlotTable []
Macro Definition Documentation
#define ADD_IMM32_OP 0x81
Definition at line 58 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define ADD_IMM8_OP 0x83
Definition at line 57 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define IS_REX_PREFIX (x) (((x) & 0xf0) == 0x40)
Definition at line 68 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define JMP_IMM32_OP 0xe9
Definition at line 60 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define JMP_IMM8_OP 0xeb
Definition at line 59 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define JMP_IND_OP 0xff
Definition at line 61 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define LEA_OP 0x8d
Definition at line 62 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define POP_OP 0x58
Definition at line 64 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define REP_PREFIX 0xf3
Definition at line 63 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define RET_OP 0xc3
Definition at line 65 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define RET_OP_2 0xc2
Definition at line 66 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
#define SIZE64_PREFIX 0x48
Definition at line 56 of file exdsptch.c.
Referenced by RtlVirtualUnwind().
Function Documentation
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
Definition at line 431 of file exceptn.c.
References ASSERT, CONTEXT_ALIGN, CONTEXT_ALIGNED_SIZE, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXTENDED_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_FULL, CONTEXT_LENGTH, CONTEXT_ROUND, CONTEXT_SEGMENTS, _CONTEXT::ContextFlags, DbgkForwardException(), DebugService(), _CONTEXT::EFlags, EFLAGS_AC_MASK, EFLAGS_TF_MASK, EFLAGS_V86_MASK, _CONTEXT::Eip, _CONTEXT::Esp, except, EXCEPTION_EXECUTE_FAULT, EXCEPTION_MAXIMUM_PARAMETERS, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionFlags, ExRaiseException(), FALSE, _EPROCESS::Flags, KdDebuggerEnabled, KdIgnoreUmExceptions, KdIsThisAKdTrap(), KeBugCheckEx(), KeContextFromKframes(), KeContextToKframes(), _KPRCB::KeExceptionDispatchCount, KeFeatureBits, KeGetCurrentPrcb(), KeI386XMMIPresent, KERNEL_MODE_EXCEPTION_NOT_HANDLED, KernelMode, KeUserExceptionDispatcher, KF_GLOBAL_32BIT_EXECUTE, KF_GLOBAL_32BIT_NOEXECUTE, KGDT_R3_CODE, KGDT_R3_DATA, KGDT_R3_TEB, KI_EXCEPTION_ACCESS_VIOLATION, KiCheckForAtlThunk(), KiCopyInformation(), KiDebugRoutine, KiEspToTrapFrame(), KiPreprocessFault(), KiSegSsToTrapFrame(), KMODE_EXCEPTION_NOT_HANDLED, NtCurrentProcess, NULL, _EXCEPTION_RECORD::NumberParameters, PF_NX_ENABLED, ProbeForWrite(), ProbeForWriteSmallStructure(), PsGetCurrentProcess(), RPL_MASK, RtlCopyMemory, RtlDispatchException(), SANITIZE_SEG, _CONTEXT::SegCs, SharedUserData, STATUS_ACCESS_VIOLATION, STATUS_BREAKPOINT, STATUS_DATATYPE_MISALIGNMENT, STATUS_SINGLE_STEP, STATUS_STACK_OVERFLOW, STATUS_WX86_BREAKPOINT, STATUS_WX86_SINGLE_STEP, TRUE, UserMode, and ZwTerminateProcess().
Referenced by Ki386CheckDelayedNpxTrap(), KiInitializeUserApc(), and KiRaiseException().
VOID KiExceptionDispatch (VOID)
BOOLEAN RtlDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord)
Definition at line 114 of file exdsptch.c.
References _DISPATCHER_CONTEXT::ContextRecord, _DISPATCHER_CONTEXT::ControlPc, _UNWIND_HISTORY_TABLE::Count, _DISPATCHER_CONTEXT::EstablisherFrame, EXCEPTION_NESTED_CALL, EXCEPTION_NONCONTINUABLE, EXCEPTION_STACK_INVALID, ExceptionCollidedUnwind, ExceptionContinueExecution, ExceptionContinueSearch, ExceptionNestedException, FALSE, FLG_ENABLE_EXCEPTION_LOGGING, _DISPATCHER_CONTEXT::FunctionEntry, _DISPATCHER_CONTEXT::HandlerData, _UNWIND_HISTORY_TABLE::HighAddress, _DISPATCHER_CONTEXT::HistoryTable, _DISPATCHER_CONTEXT::ImageBase, Index, _DISPATCHER_CONTEXT::LanguageHandler, _UNWIND_HISTORY_TABLE::LowAddress, NtGlobalFlag, NULL, RtlLookupFunctionEntry(), RtlpCopyContext(), RtlpExecuteHandlerForException(), RtlpGetStackLimits(), RtlpIsFrameInBounds(), RtlpLogExceptionHandler(), RtlpLogLastExceptionDisposition(), RtlRaiseStatus(), RtlVirtualUnwind(), _DISPATCHER_CONTEXT::ScopeIndex, _UNWIND_HISTORY_TABLE::Search, STATUS_INVALID_DISPOSITION, STATUS_NONCONTINUABLE_EXCEPTION, TRUE, UNW_FLAG_EHANDLER, and UNWIND_HISTORY_TABLE_NONE.
PRUNTIME_FUNCTION RtlLookupFunctionEntry (IN ULONG64 ControlPc, OUT PULONG64 ImageBase, IN OUT PUNWIND_HISTORY_TABLE HistoryTable OPTIONAL)
Definition at line 1837 of file exdsptch.c.
References ARGUMENT_PRESENT, _RUNTIME_FUNCTION::BeginAddress, _RUNTIME_FUNCTION::EndAddress, Index, NULL, RtlLookupFunctionTable(), RtlpConvertFunctionEntry(), UNWIND_HISTORY_TABLE_GLOBAL, UNWIND_HISTORY_TABLE_LOCAL, UNWIND_HISTORY_TABLE_NONE, and UNWIND_HISTORY_TABLE_SIZE.
Referenced by PspGetSetContextInternal(), RtlDispatchException(), RtlpSameFunction(), RtlRaiseException(), and RtlUnwindEx().
FORCEINLINE PRUNTIME_FUNCTION RtlpConvertFunctionEntry (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase)
Definition at line 1794 of file exdsptch.c.
References NULL, and RUNTIME_FUNCTION_INDIRECT.
Referenced by RtlLookupFunctionEntry(), and RtlpLookupFunctionEntryForStackWalks().
VOID RtlpCopyContext (OUT PCONTEXT Destination, IN PCONTEXT Source)
Definition at line 2034 of file exdsptch.c.
Referenced by RtlDispatchException(), and RtlUnwindEx().
DECLSPEC_NOINLINE VOID RtlpGetStackLimits (OUT PULONG64 LowLimit, OUT PULONG64 HighLimit)
Definition at line 1678 of file exdsptch.c.
References DRIVER_VERIFIER_DETECTED_VIOLATION, FALSE, KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), and KeQueryCurrentStackInformation().
Referenced by RtlDispatchException(), RtlUnwind(), and RtlUnwindEx().
BOOLEAN RtlpIsFrameInBounds (IN OUT PULONG64 LowLimit, IN ULONG64 StackFrame, IN OUT PULONG64 HighLimit)
Definition at line 1720 of file exdsptch.c.
References FALSE, and TRUE.
Referenced by RtlDispatchException(), RtlGetCallersAddress(), RtlpWalkFrameChain(), and RtlUnwindEx().
PUNWIND_INFO RtlpLookupPrimaryUnwindInfo (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase, OUT PRUNTIME_FUNCTION * PrimaryEntry)
Definition at line 2094 of file exdsptch.c.
References _UNWIND_INFO::CountOfCodes, _UNWIND_INFO::Flags, Index, TRUE, UNW_FLAG_CHAININFO, and _UNWIND_INFO::UnwindCode.
Referenced by RtlpSameFunction().
PRUNTIME_FUNCTION RtlpSameFunction (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase, IN ULONG64 ControlPc)
Definition at line 2157 of file exdsptch.c.
References NULL, RtlLookupFunctionEntry(), and RtlpLookupPrimaryUnwindInfo().
Referenced by RtlVirtualUnwind().
PRUNTIME_FUNCTION RtlpUnwindPrologue (IN ULONG64 ImageBase, IN ULONG64 ControlPc, IN ULONG64 FrameBase, IN PRUNTIME_FUNCTION FunctionEntry, IN OUT PCONTEXT ContextRecord, IN OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers OPTIONAL)
Definition at line 870 of file exdsptch.c.
References ARGUMENT_PRESENT, ASSERT, _UNWIND_CODE::CodeOffset, _UNWIND_INFO::CountOfCodes, FALSE, _UNWIND_INFO::Flags, _UNWIND_CODE::FrameOffset, _UNWIND_INFO::FrameOffset, _UNWIND_INFO::FrameRegister, Index, _UNWIND_CODE::OpInfo, RtlpUnwindOpSlotTable, TRUE, UNW_FLAG_CHAININFO, _UNWIND_INFO::UnwindCode, _UNWIND_CODE::UnwindOp, UWOP_ALLOC_LARGE, UWOP_ALLOC_SMALL, UWOP_PUSH_MACHFRAME, UWOP_PUSH_NONVOL, UWOP_SAVE_NONVOL, UWOP_SAVE_NONVOL_FAR, UWOP_SAVE_XMM128, UWOP_SAVE_XMM128_FAR, UWOP_SET_FPREG, UWOP_SPARE_CODE1, and UWOP_SPARE_CODE2.
Referenced by RtlVirtualUnwind().
VOID RtlUnwind (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue)
Definition at line 445 of file exdsptch.c.
References NULL, and RtlUnwindEx().
VOID RtlUnwindEx (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue, IN PCONTEXT OriginalContext, IN PUNWIND_HISTORY_TABLE HistoryTable OPTIONAL)
Definition at line 510 of file exdsptch.c.
References ARGUMENT_PRESENT, _DISPATCHER_CONTEXT::ContextRecord, _DISPATCHER_CONTEXT::ControlPc, _DISPATCHER_CONTEXT::EstablisherFrame, EXCEPTION_COLLIDED_UNWIND, EXCEPTION_EXIT_UNWIND, EXCEPTION_TARGET_UNWIND, EXCEPTION_UNWINDING, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, ExceptionCollidedUnwind, ExceptionContinueSearch, _EXCEPTION_RECORD::ExceptionRecord, FALSE, _DISPATCHER_CONTEXT::FunctionEntry, _DISPATCHER_CONTEXT::HandlerData, _DISPATCHER_CONTEXT::HistoryTable, _DISPATCHER_CONTEXT::ImageBase, _DISPATCHER_CONTEXT::LanguageHandler, NULL, _EXCEPTION_RECORD::NumberParameters, RtlCaptureContext(), RtlLookupFunctionEntry(), RtlpCopyContext(), RtlpExecuteHandlerForUnwind(), RtlpGetStackLimits(), RtlpIsFrameInBounds(), RtlRaiseStatus(), RtlRestoreContext(), RtlVirtualUnwind(), _DISPATCHER_CONTEXT::ScopeIndex, STATUS_BAD_FUNCTION_TABLE, STATUS_BAD_STACK, STATUS_INVALID_DISPOSITION, STATUS_UNWIND, STATUS_UNWIND_CONSOLIDATE, _DISPATCHER_CONTEXT::TargetIp, TRUE, UNW_FLAG_NHANDLER, UNW_FLAG_UHANDLER, UNWIND_HISTORY_TABLE_GLOBAL, and ZwRaiseException().
Referenced by RtlUnwind().
PEXCEPTION_ROUTINE RtlVirtualUnwind (IN ULONG HandlerType, IN ULONG64 ImageBase, IN ULONG64 ControlPc, IN PRUNTIME_FUNCTION FunctionEntry, IN OUT PCONTEXT ContextRecord, OUT PVOID * HandlerData, OUT PULONG64 EstablisherFrame, IN OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers OPTIONAL)
Definition at line 1203 of file exdsptch.c.
References ADD_IMM32_OP, ADD_IMM8_OP, ARGUMENT_PRESENT, _RUNTIME_FUNCTION::BeginAddress, _UNWIND_CODE::CodeOffset, _UNWIND_INFO::CountOfCodes, FALSE, _UNWIND_INFO::Flags, _UNWIND_INFO::FrameOffset, _UNWIND_INFO::FrameRegister, Index, IS_REX_PREFIX, JMP_IMM32_OP, JMP_IMM8_OP, JMP_IND_OP, LEA_OP, NULL, POP_OP, REP_PREFIX, RET_OP, RET_OP_2, RtlpSameFunction(), RtlpUnwindPrologue(), SIZE64_PREFIX, _UNWIND_INFO::SizeOfProlog, TRUE, UNALIGNED, UNW_FLAG_CHAININFO, _UNWIND_INFO::UnwindCode, _UNWIND_CODE::UnwindOp, and UWOP_SET_FPREG.
Referenced by PspGetSetContextInternal(), RtlDispatchException(), RtlGetCallersAddress(), RtlpWalkFrameChain(), RtlRaiseException(), and RtlUnwindEx().
Variable Documentation
PVOID RtlpFunctionAddressTable[]
Initial value:
= {
    &KiExceptionDispatch,
    &KiDispatchException,
    &RtlDispatchException,
    &RtlpExecuteHandlerForException,
    &__C_specific_handler,
    &RtlUnwindEx,
    NULL
    }
Definition at line 42 of file exdsptch.c.
UCHAR RtlpUnwindOpSlotTable[]
Initial value:
= {
    1,
    2,
    1,
    1,
    2,
    3,
    0,
    0,
    2,
    3,
    1
}
Definition at line 75 of file exdsptch.c.
Referenced by RtlpUnwindPrologue().