Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntldr.h File Reference
ntldr.h File Reference
Data Structures
struct _KLDR_DATA_TABLE_ENTRY
struct _KLDR_DATA_TABLE_ENTRY32
struct _KLDR_DATA_TABLE_ENTRY64
struct _LDR_DATA_TABLE_ENTRY
struct _LDR_DATA_TABLE_ENTRY32
struct _LDR_DATA_TABLE_ENTRY64
struct _LDR_DLL_LOADED_NOTIFICATION_DATA
union _LDR_DLL_NOTIFICATION_DATA
struct _LDR_DLL_UNLOADED_NOTIFICATION_DATA
struct _LDR_ENUM_RESOURCE_ENTRY
struct _LDR_OUT_OF_PROCESS_IMAGE
struct _RTL_BUFFER
struct _RTL_PROCESS_MODULE_INFORMATION
struct _RTL_PROCESS_MODULES
Macros
#define DLL_PROCESS_ATTACH 1
#define DLL_PROCESS_DETACH 0
#define DLL_PROCESS_VERIFIER 4
#define DLL_THREAD_ATTACH 2
#define DLL_THREAD_DETACH 3
#define LDR_ADDREF_DLL_PIN (0x00000001)
#define LDR_DATAFILE_TO_VIEW(x) ((PVOID)(((ULONG_PTR)(x)) & ~(ULONG_PTR)1))
#define LDR_DATAFILE_TO_VIEW_INTEGER(x) ((x) - ((x) & 1))
#define LDR_DLL_LOADED_FLAG_RELOCATED (0x00000001)
#define LDR_DLL_MAPPED_AS_DATA (0x00000002)
#define LDR_DLL_MAPPED_AS_IMAGE (0x00000001)
#define LDR_DLL_MAPPED_AS_MASK (0x00000003)
#define LDR_DLL_MAPPED_AS_UNFORMATED_IMAGE (0x00000003)
#define LDR_DLL_NOTIFICATION_REASON_LOADED (1)
#define LDR_DLL_NOTIFICATION_REASON_UNLOADED (2)
#define LDR_DLL_UNLOADED_FLAG_PROCESS_TERMINATION (0x00000001)
#define LDR_FIND_RESOURCE_LANGUAGE_CAN_FALLBACK (0x00000000)
#define LDR_FIND_RESOURCE_LANGUAGE_EXACT (0x00000004)
#define LDR_FIND_RESOURCE_LANGUAGE_REDIRECT_VERSION (0x00000008)
#define LDR_GET_DLL_HANDLE_EX_PIN (0x00000002)
#define LDR_GET_DLL_HANDLE_EX_UNCHANGED_REFCOUNT (0x00000001)
#define LDR_IMAGE_FILE_OPTIONS_KEY_LARGE_PAGE_DLLS L"LargePageDLLs"
#define LDR_IS_DATAFILE(x) (((ULONG_PTR)(x)) & (ULONG_PTR)1)
#define LDR_IS_DATAFILE_INTEGER(x) (((x) & 1) == 1)
#define LDR_IS_VIEW(x) (!LDR_IS_DATAFILE(x))
#define LDR_IS_VIEW_INTEGER(x) (((x) & 1) == 0)
#define LDR_LOCK_LOADER_LOCK_DISPOSITION_INVALID (0)
#define LDR_LOCK_LOADER_LOCK_DISPOSITION_LOCK_ACQUIRED (1)
#define LDR_LOCK_LOADER_LOCK_DISPOSITION_LOCK_NOT_ACQUIRED (2)
#define LDR_LOCK_LOADER_LOCK_FLAG_RAISE_ON_ERRORS (0x00000001)
#define LDR_LOCK_LOADER_LOCK_FLAG_TRY_ONLY (0x00000002)
#define LDR_MAXIMUM_RESOURCE_PATH_DEPTH (3)
#define LDR_RESOURCE_ID_NAME_MASK ((~(ULONG_PTR)0) << 16) /* lower 16bits clear */
#define LDR_RESOURCE_ID_NAME_MINVAL (((ULONG_PTR)1) << 16) /* 17th bit set */
#define LDR_UNLOCK_LOADER_LOCK_FLAG_RAISE_ON_ERRORS (0x00000001)
#define LDR_VIEW_TO_DATAFILE(x) ((PVOID)(((ULONG_PTR)(x)) | (ULONG_PTR)1))
#define LDR_VIEW_TO_DATAFILE_INTEGER(x) ((x) | 1)
#define LDRP_COMPAT_DATABASE_PROCESSED 0x80000000
#define LDRP_COR_IMAGE 0x00400000
#define LDRP_COR_OWNS_UNMAP 0x00800000
#define LDRP_CURRENT_LOAD 0x00010000
#define LDRP_DEBUG_SYMBOLS_LOADED 0x00100000
#define LDRP_DONT_CALL_FOR_THREADS 0x00040000
#define LDRP_DRIVER_DEPENDENT_DLL 0x04000000
#define LDRP_ENTRY_INSERTED 0x00008000
#define LDRP_ENTRY_NATIVE 0x08000000
#define LDRP_ENTRY_PROCESSED 0x00004000
#define LDRP_FAILED_BUILTIN_LOAD 0x00020000
#define LDRP_FIND_RESOURCE_DATA (0x00000000)
#define LDRP_FIND_RESOURCE_DIRECTORY (0x00000002)
#define LDRP_IMAGE_DLL 0x00000004
#define LDRP_IMAGE_NOT_AT_BASE 0x00200000
#define LDRP_IMAGE_VERIFYING 0x02000000
#define LDRP_LOAD_IN_PROGRESS 0x00001000
#define LDRP_MM_LOADED 0x40000000
#define LDRP_NON_PAGED_DEBUG_INFO 0x20000000
#define LDRP_PROCESS_ATTACH_CALLED 0x00080000
#define LDRP_REDIRECTED 0x10000000
#define LDRP_STATIC_LINK 0x00000002
#define LDRP_SYSTEM_MAPPED 0x01000000
#define LDRP_UNLOAD_IN_PROGRESS 0x00002000
#define RTL_BUFFER RTL_BUFFER
Typedefs
typedef IN PCWSTR OUT PVOID * ActivationContext
typedef IN PCWSTR FullDllPath
typedef struct _KLDR_DATA_TABLE_ENTRY KLDR_DATA_TABLE_ENTRY
typedef struct _KLDR_DATA_TABLE_ENTRY32 KLDR_DATA_TABLE_ENTRY32
typedef struct _KLDR_DATA_TABLE_ENTRY64 KLDR_DATA_TABLE_ENTRY64
typedef struct _LDR_DATA_TABLE_ENTRY LDR_DATA_TABLE_ENTRY
typedef struct _LDR_DATA_TABLE_ENTRY32 LDR_DATA_TABLE_ENTRY32
typedef struct _LDR_DATA_TABLE_ENTRY64 LDR_DATA_TABLE_ENTRY64
typedef struct _LDR_DLL_LOADED_NOTIFICATION_DATA LDR_DLL_LOADED_NOTIFICATION_DATA
typedef union _LDR_DLL_NOTIFICATION_DATA LDR_DLL_NOTIFICATION_DATA
typedef struct _LDR_DLL_UNLOADED_NOTIFICATION_DATA LDR_DLL_UNLOADED_NOTIFICATION_DATA
typedef struct _LDR_ENUM_RESOURCE_ENTRY LDR_ENUM_RESOURCE_ENTRY
typedef struct _LDR_OUT_OF_PROCESS_IMAGE LDR_OUT_OF_PROCESS_IMAGE
typedef NTSTATUS LDR_RELOCATE_IMAGE_RETURN_TYPE
typedef const struct _LDR_DATA_TABLE_ENTRY * PCLDR_DATA_TABLE_ENTRY
typedef const LDR_DLL_LOADED_NOTIFICATION_DATA * PCLDR_DLL_LOADED_NOTIFICATION_DATA
typedef const LDR_DLL_NOTIFICATION_DATA * PCLDR_DLL_NOTIFICATION_DATA
typedef const LDR_DLL_UNLOADED_NOTIFICATION_DATA * PCLDR_DLL_UNLOADED_NOTIFICATION_DATA
typedef BOOLEAN(* PDLL_INIT_ROUTINE) (IN PVOID DllHandle, IN ULONG Reason, IN PCONTEXT Context OPTIONAL)
typedef struct _KLDR_DATA_TABLE_ENTRY * PKLDR_DATA_TABLE_ENTRY
typedef struct _KLDR_DATA_TABLE_ENTRY32 * PKLDR_DATA_TABLE_ENTRY32
typedef struct _KLDR_DATA_TABLE_ENTRY64 * PKLDR_DATA_TABLE_ENTRY64
typedef NTSTATUS(NTAPI * PLDR_APP_COMPAT_DLL_REDIRECTION_CALLBACK_FUNCTION) (IN ULONG Flags, IN PCWSTR DllName, IN PCWSTR DllPath OPTIONAL, IN OUT PULONG DllCharacteristics OPTIONAL, IN PVOID CallbackData, OUT PWSTR *EffectiveDllPath)
typedef struct _LDR_DATA_TABLE_ENTRY * PLDR_DATA_TABLE_ENTRY
typedef struct _LDR_DATA_TABLE_ENTRY32 * PLDR_DATA_TABLE_ENTRY32
typedef struct _LDR_DATA_TABLE_ENTRY64 * PLDR_DATA_TABLE_ENTRY64
typedef struct _LDR_DLL_LOADED_NOTIFICATION_DATA * PLDR_DLL_LOADED_NOTIFICATION_DATA
typedef union _LDR_DLL_NOTIFICATION_DATA * PLDR_DLL_NOTIFICATION_DATA
typedef VOID(NTAPI * PLDR_DLL_NOTIFICATION_FUNCTION) (IN ULONG NotificationReason, IN PCLDR_DLL_NOTIFICATION_DATA NotificationData, IN PVOID Context)
typedef struct _LDR_DLL_UNLOADED_NOTIFICATION_DATA * PLDR_DLL_UNLOADED_NOTIFICATION_DATA
typedef struct _LDR_ENUM_RESOURCE_ENTRY * PLDR_ENUM_RESOURCE_ENTRY
typedef VOID(* PLDR_IMPORT_MODULE_CALLBACK) (IN PVOID Parameter, PCHAR ModuleName)
typedef VOID(NTAPI * PLDR_LOADED_MODULE_ENUMERATION_CALLBACK_FUNCTION) (IN PCLDR_DATA_TABLE_ENTRY DataTableEntry, IN PVOID Context, IN OUT BOOLEAN *StopEnumeration)
typedef struct _LDR_OUT_OF_PROCESS_IMAGE * PLDR_OUT_OF_PROCESS_IMAGE
typedef BOOLEAN(* PPROCESS_STARTER_ROUTINE) (IN PVOID RealStartAddress)
typedef struct _RTL_BUFFER * PRTL_BUFFER
typedef struct _RTL_PROCESS_MODULE_INFORMATION * PRTL_PROCESS_MODULE_INFORMATION
typedef struct _RTL_PROCESS_MODULES * PRTL_PROCESS_MODULES
typedef struct _RTL_BUFFER RTL_BUFFER
typedef struct _RTL_PROCESS_MODULE_INFORMATION RTL_PROCESS_MODULE_INFORMATION
typedef struct _RTL_PROCESS_MODULES RTL_PROCESS_MODULES
Functions
NTSTATUS NTAPI LdrAccessOutOfProcessResource (IN ULONG Flags, PLDR_OUT_OF_PROCESS_IMAGE Image, IN CONST IMAGE_RESOURCE_DATA_ENTRY *DataEntry, OUT PULONG64 Address OPTIONAL, OUT PULONG Size OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrAccessResource (IN PVOID DllHandle, IN CONST IMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrAddRefDll (ULONG Flags, PVOID DllHandle)
NTSYSAPI BOOLEAN NTAPI LdrAlternateResourcesEnabled (VOID)
NTSTATUS NTAPI LdrCreateOutOfProcessImage (IN ULONG Flags, IN HANDLE ProcessHandle, IN ULONG64 DllHandle, OUT PLDR_OUT_OF_PROCESS_IMAGE Image)
NTSYSAPI VOID NTAPI LdrDestroyOutOfProcessImage (IN OUT PLDR_OUT_OF_PROCESS_IMAGE Image)
NTSYSAPI NTSTATUS NTAPI LdrDisableThreadCalloutsForDll (IN PVOID DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrEnumerateLoadedModules (IN ULONG Flags, IN PLDR_LOADED_MODULE_ENUMERATION_CALLBACK_FUNCTION CallbackFunction, IN PVOID Context)
NTSYSAPI NTSTATUS NTAPI LdrEnumResources (IN PVOID DllHandle, IN CONST ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, IN OUT PULONG NumberOfResources, OUT PLDR_ENUM_RESOURCE_ENTRY Resources OPTIONAL)
NTSTATUS NTAPI LdrFindCreateProcessManifest (IN ULONG Flags, PLDR_OUT_OF_PROCESS_IMAGE Image, IN CONST ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY ResourceDataEntry)
NTSTATUS NTAPI LdrFindEntryForAddress (IN PVOID Address, OUT PLDR_DATA_TABLE_ENTRY *TableEntry)
NTSYSAPI NTSTATUS NTAPI LdrFindResource_U (IN PVOID DllHandle, IN CONST ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry)
NTSYSAPI NTSTATUS NTAPI LdrFindResourceDirectory_U (IN PVOID DllHandle, IN CONST ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DIRECTORY *ResourceDirectory)
NTSTATUS NTAPI LdrFindResourceEx_U (ULONG Flags, IN PVOID DllHandle, IN CONST ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry)
NTSYSAPI BOOLEAN NTAPI LdrFlushAlternateResourceModules (VOID)
PVOID NTAPI LdrGetAlternateResourceModuleHandle (IN PVOID Module)
NTSYSAPI NTSTATUS NTAPI LdrGetDllHandle (IN PCWSTR DllPath OPTIONAL, IN PULONG DllCharacteristics OPTIONAL, IN PCUNICODE_STRING DllName, OUT PVOID *DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrGetDllHandleEx (IN ULONG Flags, IN PCWSTR DllPath OPTIONAL, IN PULONG DllCharacteristics OPTIONAL, IN PCUNICODE_STRING DllName, OUT PVOID *DllHandle OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrGetProcedureAddress (IN PVOID DllHandle, IN CONST ANSI_STRING *ProcedureName OPTIONAL, IN ULONG ProcedureNumber OPTIONAL, OUT PVOID *ProcedureAddress)
NTSYSAPI PVOID NTAPI LdrLoadAlternateResourceModule (IN PVOID Module, IN LPCWSTR PathToAlternateModule OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrLoadDll (IN PCWSTR DllPath OPTIONAL, IN PULONG DllCharacteristics OPTIONAL, IN PCUNICODE_STRING DllName, OUT PVOID *DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrLockLoaderLock (IN ULONG Flags, OUT ULONG *Disposition OPTIONAL, OUT PVOID *Cookie)
NTSYSAPI NTSTATUS NTAPI LdrOpenImageFileOptionsKey (IN PCUNICODE_STRING ImagePathName, IN BOOLEAN Wow64Path, OUT PHANDLE KeyHandle)
PIMAGE_BASE_RELOCATION NTAPI LdrProcessRelocationBlock (IN ULONG_PTR VA, IN ULONG SizeOfBlock, IN PUSHORT NextOffset, IN LONG_PTR Diff)
NTSYSAPI VOID LdrProcessStarterHelper (IN PPROCESS_STARTER_ROUTINE ProcessStarter, IN PVOID RealStartAddress)
NTSYSAPI NTSTATUS NTAPI LdrQueryImageFileExecutionOptions (IN PCUNICODE_STRING ImagePathName, IN PCWSTR OptionName, IN ULONG Type, OUT PVOID Buffer, IN ULONG BufferSize, OUT PULONG ResultSize OPTIONAL)
NTSYSAPI NTSTATUS LdrQueryImageFileExecutionOptionsEx (IN PCUNICODE_STRING ImagePathName, IN PCWSTR OptionName, IN ULONG Type, OUT PVOID Buffer, IN ULONG BufferSize, OUT PULONG ResultSize OPTIONAL, IN BOOLEAN Wow64Path)
NTSYSAPI NTSTATUS NTAPI LdrQueryImageFileKeyOption (IN HANDLE KeyHandle, IN PCWSTR OptionName, IN ULONG Type, OUT PVOID Buffer, IN ULONG BufferSize, OUT PULONG ResultSize OPTIONAL)
NTSTATUS NTAPI LdrQueryProcessModuleInformation (OUT PRTL_PROCESS_MODULES ModuleInformation, IN ULONG ModuleInformationLength, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS NTAPI LdrRegisterDllNotification (IN ULONG Flags, IN PLDR_DLL_NOTIFICATION_FUNCTION NotificationFunction, IN PVOID Context, OUT PVOID *Cookie)
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImage (__in PVOID NewBase, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImageWithBias (__in PVOID NewBase, __in LONGLONG Bias, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
NTSYSAPI NTSTATUS NTAPI LdrSetAppCompatDllRedirectionCallback (IN ULONG Flags, IN PLDR_APP_COMPAT_DLL_REDIRECTION_CALLBACK_FUNCTION CallbackFunction, IN PVOID CallbackData)
NTSYSAPI VOID NTAPI LdrSetDllManifestProber (IN PLDR_MANIFEST_PROBER_ROUTINE ManifestProberRoutine)
NTSYSAPI VOID NTAPI LdrShutdownProcess (VOID)
NTSYSAPI VOID NTAPI LdrShutdownThread (VOID)
NTSYSAPI BOOLEAN NTAPI LdrUnloadAlternateResourceModule (IN PVOID Module)
NTSYSAPI NTSTATUS NTAPI LdrUnloadDll (IN PVOID DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrUnlockLoaderLock (IN ULONG Flags, IN OUT PVOID Cookie)
NTSTATUS NTAPI LdrUnregisterDllNotification (IN PVOID Cookie)
NTSTATUS NTAPI LdrVerifyImageMatchesChecksum (IN HANDLE ImageFileHandle, IN PLDR_IMPORT_MODULE_CALLBACK ImportCallbackRoutine OPTIONAL, IN PVOID ImportCallbackParameter, OUT PUSHORT ImageCharacteristics OPTIONAL)
BOOLEAN NTAPI LdrVerifyMappedImageMatchesChecksum (IN PVOID BaseAddress, IN SIZE_T NumberOfBytes, IN ULONG FileLength)
typedef NTSTATUS (NTAPI *PLDR_MANIFEST_PROBER_ROUTINE)(IN PVOID DllBase
Macro Definition Documentation
#define DLL_PROCESS_ATTACH 1
Definition at line 243 of file ntldr.h.
#define DLL_PROCESS_DETACH 0
Definition at line 246 of file ntldr.h.
#define DLL_PROCESS_VERIFIER 4
Definition at line 247 of file ntldr.h.
#define DLL_THREAD_ATTACH 2
Definition at line 244 of file ntldr.h.
#define DLL_THREAD_DETACH 3
Definition at line 245 of file ntldr.h.
#define LDR_ADDREF_DLL_PIN (0x00000001)
Definition at line 830 of file ntldr.h.
#define LDR_DATAFILE_TO_VIEW (x) ((PVOID)(((ULONG_PTR)(x)) & ~(ULONG_PTR)1))
Definition at line 412 of file ntldr.h.
Referenced by LdrpAccessResourceDataNoMultipleLanguage(), and RtlImageDirectoryEntryToData().
#define LDR_DATAFILE_TO_VIEW_INTEGER (x) ((x) - ((x) & 1))
Definition at line 421 of file ntldr.h.
#define LDR_DLL_LOADED_FLAG_RELOCATED (0x00000001)
Definition at line 718 of file ntldr.h.
#define LDR_DLL_MAPPED_AS_DATA (0x00000002)
Definition at line 430 of file ntldr.h.
#define LDR_DLL_MAPPED_AS_IMAGE (0x00000001)
Definition at line 429 of file ntldr.h.
#define LDR_DLL_MAPPED_AS_MASK (0x00000003)
Definition at line 432 of file ntldr.h.
#define LDR_DLL_MAPPED_AS_UNFORMATED_IMAGE (0x00000003)
Definition at line 431 of file ntldr.h.
#define LDR_DLL_NOTIFICATION_REASON_LOADED (1)
Definition at line 749 of file ntldr.h.
#define LDR_DLL_NOTIFICATION_REASON_UNLOADED (2)
Definition at line 750 of file ntldr.h.
#define LDR_DLL_UNLOADED_FLAG_PROCESS_TERMINATION (0x00000001)
Definition at line 730 of file ntldr.h.
#define LDR_FIND_RESOURCE_LANGUAGE_CAN_FALLBACK (0x00000000)
Definition at line 444 of file ntldr.h.
#define LDR_FIND_RESOURCE_LANGUAGE_EXACT (0x00000004)
Definition at line 445 of file ntldr.h.
#define LDR_FIND_RESOURCE_LANGUAGE_REDIRECT_VERSION (0x00000008)
Definition at line 446 of file ntldr.h.
#define LDR_GET_DLL_HANDLE_EX_PIN (0x00000002)
Definition at line 817 of file ntldr.h.
#define LDR_GET_DLL_HANDLE_EX_UNCHANGED_REFCOUNT (0x00000001)
Definition at line 816 of file ntldr.h.
#define LDR_IMAGE_FILE_OPTIONS_KEY_LARGE_PAGE_DLLS L"LargePageDLLs"
Definition at line 636 of file ntldr.h.
#define LDR_IS_DATAFILE (x) (((ULONG_PTR)(x)) & (ULONG_PTR)1)
Definition at line 410 of file ntldr.h.
Referenced by LdrpAccessResourceDataNoMultipleLanguage(), and RtlImageDirectoryEntryToData().
#define LDR_IS_DATAFILE_INTEGER (x) (((x) & 1) == 1)
Definition at line 419 of file ntldr.h.
#define LDR_IS_VIEW (x) (!LDR_IS_DATAFILE(x))
Definition at line 411 of file ntldr.h.
#define LDR_IS_VIEW_INTEGER (x) (((x) & 1) == 0)
Definition at line 420 of file ntldr.h.
#define LDR_LOCK_LOADER_LOCK_DISPOSITION_INVALID (0)
Definition at line 793 of file ntldr.h.
#define LDR_LOCK_LOADER_LOCK_DISPOSITION_LOCK_ACQUIRED (1)
Definition at line 794 of file ntldr.h.
#define LDR_LOCK_LOADER_LOCK_DISPOSITION_LOCK_NOT_ACQUIRED (2)
Definition at line 795 of file ntldr.h.
#define LDR_LOCK_LOADER_LOCK_FLAG_RAISE_ON_ERRORS (0x00000001)
Definition at line 790 of file ntldr.h.
#define LDR_LOCK_LOADER_LOCK_FLAG_TRY_ONLY (0x00000002)
Definition at line 791 of file ntldr.h.
#define LDR_MAXIMUM_RESOURCE_PATH_DEPTH (3)
Definition at line 558 of file ntldr.h.
#define LDR_RESOURCE_ID_NAME_MASK ((~(ULONG_PTR)0) << 16) /* lower 16bits clear */
Definition at line 399 of file ntldr.h.
Referenced by LdrpCompareResourceNames_U(), and LdrpSearchResourceSection_U().
#define LDR_RESOURCE_ID_NAME_MINVAL (((ULONG_PTR)1) << 16) /* 17th bit set */
Definition at line 400 of file ntldr.h.
#define LDR_UNLOCK_LOADER_LOCK_FLAG_RAISE_ON_ERRORS (0x00000001)
Definition at line 806 of file ntldr.h.
#define LDR_VIEW_TO_DATAFILE (x) ((PVOID)(((ULONG_PTR)(x)) | (ULONG_PTR)1))
Definition at line 409 of file ntldr.h.
#define LDR_VIEW_TO_DATAFILE_INTEGER (x) ((x) | 1)
Definition at line 418 of file ntldr.h.
#define LDRP_COMPAT_DATABASE_PROCESSED 0x80000000
Definition at line 57 of file ntldr.h.
#define LDRP_COR_IMAGE 0x00400000
Definition at line 48 of file ntldr.h.
#define LDRP_COR_OWNS_UNMAP 0x00800000
Definition at line 49 of file ntldr.h.
#define LDRP_CURRENT_LOAD 0x00010000
Definition at line 42 of file ntldr.h.
#define LDRP_DEBUG_SYMBOLS_LOADED 0x00100000
Definition at line 46 of file ntldr.h.
Referenced by MmLoadSystemImage(), and MmUnloadSystemImage().
#define LDRP_DONT_CALL_FOR_THREADS 0x00040000
Definition at line 44 of file ntldr.h.
#define LDRP_DRIVER_DEPENDENT_DLL 0x04000000
Definition at line 52 of file ntldr.h.
Referenced by MiBuildImportsForBootDrivers().
#define LDRP_ENTRY_INSERTED 0x00008000
Definition at line 41 of file ntldr.h.
#define LDRP_ENTRY_NATIVE 0x08000000
Definition at line 53 of file ntldr.h.
Referenced by MmInitSystem(), and MmLoadSystemImage().
#define LDRP_ENTRY_PROCESSED 0x00004000
Definition at line 40 of file ntldr.h.
Referenced by MmLoadSystemImage().
#define LDRP_FAILED_BUILTIN_LOAD 0x00020000
Definition at line 43 of file ntldr.h.
#define LDRP_FIND_RESOURCE_DATA (0x00000000)
Definition at line 438 of file ntldr.h.
#define LDRP_FIND_RESOURCE_DIRECTORY (0x00000002)
Definition at line 439 of file ntldr.h.
Referenced by LdrFindResourceDirectory_U(), and LdrpSearchResourceSection_U().
#define LDRP_IMAGE_DLL 0x00000004
Definition at line 37 of file ntldr.h.
#define LDRP_IMAGE_NOT_AT_BASE 0x00200000
Definition at line 47 of file ntldr.h.
#define LDRP_IMAGE_VERIFYING 0x02000000
Definition at line 51 of file ntldr.h.
Referenced by KevUtilAddressToFileHeader(), and MmUnloadSystemImage().
#define LDRP_LOAD_IN_PROGRESS 0x00001000
Definition at line 38 of file ntldr.h.
Referenced by MiResolveImageReferences(), and MmLoadSystemImage().
#define LDRP_MM_LOADED 0x40000000
Definition at line 56 of file ntldr.h.
Referenced by MiFindInitializationCode(), and MmLoadSystemImage().
#define LDRP_NON_PAGED_DEBUG_INFO 0x20000000
Definition at line 55 of file ntldr.h.
Referenced by MmLoadSystemImage().
#define LDRP_PROCESS_ATTACH_CALLED 0x00080000
Definition at line 45 of file ntldr.h.
#define LDRP_REDIRECTED 0x10000000
Definition at line 54 of file ntldr.h.
#define LDRP_STATIC_LINK 0x00000002
Definition at line 36 of file ntldr.h.
#define LDRP_SYSTEM_MAPPED 0x01000000
Definition at line 50 of file ntldr.h.
Referenced by MiReloadBootLoadedDrivers(), MmLoadSystemImage(), and MmUnloadSystemImage().
#define LDRP_UNLOAD_IN_PROGRESS 0x00002000
Definition at line 39 of file ntldr.h.
#define RTL_BUFFER RTL_BUFFER
Definition at line 484 of file ntldr.h.
Typedef Documentation
typedef IN PCWSTR OUT PVOID* ActivationContext
Definition at line 315 of file ntldr.h.
typedef IN PCWSTR FullDllPath
Definition at line 315 of file ntldr.h.
typedef struct _KLDR_DATA_TABLE_ENTRY KLDR_DATA_TABLE_ENTRY
typedef struct _KLDR_DATA_TABLE_ENTRY32 KLDR_DATA_TABLE_ENTRY32
typedef struct _KLDR_DATA_TABLE_ENTRY64 KLDR_DATA_TABLE_ENTRY64
typedef struct _LDR_DATA_TABLE_ENTRY LDR_DATA_TABLE_ENTRY
typedef struct _LDR_DATA_TABLE_ENTRY32 LDR_DATA_TABLE_ENTRY32
typedef struct _LDR_DATA_TABLE_ENTRY64 LDR_DATA_TABLE_ENTRY64
typedef struct _LDR_DLL_LOADED_NOTIFICATION_DATA LDR_DLL_LOADED_NOTIFICATION_DATA
typedef union _LDR_DLL_NOTIFICATION_DATA LDR_DLL_NOTIFICATION_DATA
typedef struct _LDR_DLL_UNLOADED_NOTIFICATION_DATA LDR_DLL_UNLOADED_NOTIFICATION_DATA
typedef struct _LDR_ENUM_RESOURCE_ENTRY LDR_ENUM_RESOURCE_ENTRY
typedef struct _LDR_OUT_OF_PROCESS_IMAGE LDR_OUT_OF_PROCESS_IMAGE
typedef NTSTATUS LDR_RELOCATE_IMAGE_RETURN_TYPE
Definition at line 333 of file ntldr.h.
typedef const struct _LDR_DATA_TABLE_ENTRY* PCLDR_DATA_TABLE_ENTRY
Definition at line 97 of file ntldr.h.
typedef const LDR_DLL_LOADED_NOTIFICATION_DATA* PCLDR_DLL_LOADED_NOTIFICATION_DATA
Definition at line 728 of file ntldr.h.
typedef const LDR_DLL_NOTIFICATION_DATA* PCLDR_DLL_NOTIFICATION_DATA
Definition at line 747 of file ntldr.h.
typedef const LDR_DLL_UNLOADED_NOTIFICATION_DATA* PCLDR_DLL_UNLOADED_NOTIFICATION_DATA
Definition at line 740 of file ntldr.h.
typedef BOOLEAN(* PDLL_INIT_ROUTINE) (IN PVOID DllHandle, IN ULONG Reason, IN PCONTEXT Context OPTIONAL)
Definition at line 251 of file ntldr.h.
typedef struct _KLDR_DATA_TABLE_ENTRY * PKLDR_DATA_TABLE_ENTRY
typedef struct _KLDR_DATA_TABLE_ENTRY32 * PKLDR_DATA_TABLE_ENTRY32
typedef struct _KLDR_DATA_TABLE_ENTRY64 * PKLDR_DATA_TABLE_ENTRY64
typedef NTSTATUS(NTAPI * PLDR_APP_COMPAT_DLL_REDIRECTION_CALLBACK_FUNCTION) (IN ULONG Flags, IN PCWSTR DllName, IN PCWSTR DllPath OPTIONAL, IN OUT PULONG DllCharacteristics OPTIONAL, IN PVOID CallbackData, OUT PWSTR *EffectiveDllPath)
Definition at line 841 of file ntldr.h.
typedef struct _LDR_DATA_TABLE_ENTRY * PLDR_DATA_TABLE_ENTRY
typedef struct _LDR_DATA_TABLE_ENTRY32 * PLDR_DATA_TABLE_ENTRY32
typedef struct _LDR_DATA_TABLE_ENTRY64 * PLDR_DATA_TABLE_ENTRY64
typedef struct _LDR_DLL_LOADED_NOTIFICATION_DATA * PLDR_DLL_LOADED_NOTIFICATION_DATA
typedef union _LDR_DLL_NOTIFICATION_DATA * PLDR_DLL_NOTIFICATION_DATA
typedef VOID(NTAPI * PLDR_DLL_NOTIFICATION_FUNCTION) (IN ULONG NotificationReason, IN PCLDR_DLL_NOTIFICATION_DATA NotificationData, IN PVOID Context)
Definition at line 753 of file ntldr.h.
typedef struct _LDR_DLL_UNLOADED_NOTIFICATION_DATA * PLDR_DLL_UNLOADED_NOTIFICATION_DATA
typedef struct _LDR_ENUM_RESOURCE_ENTRY * PLDR_ENUM_RESOURCE_ENTRY
typedef VOID(* PLDR_IMPORT_MODULE_CALLBACK) (IN PVOID Parameter, PCHAR ModuleName)
Definition at line 375 of file ntldr.h.
typedef VOID(NTAPI * PLDR_LOADED_MODULE_ENUMERATION_CALLBACK_FUNCTION) (IN PCLDR_DATA_TABLE_ENTRY DataTableEntry, IN PVOID Context, IN OUT BOOLEAN *StopEnumeration)
Definition at line 775 of file ntldr.h.
typedef struct _LDR_OUT_OF_PROCESS_IMAGE * PLDR_OUT_OF_PROCESS_IMAGE
typedef BOOLEAN(* PPROCESS_STARTER_ROUTINE) (IN PVOID RealStartAddress)
Definition at line 259 of file ntldr.h.
typedef struct _RTL_BUFFER * PRTL_BUFFER
typedef struct _RTL_PROCESS_MODULE_INFORMATION * PRTL_PROCESS_MODULE_INFORMATION
typedef struct _RTL_PROCESS_MODULES * PRTL_PROCESS_MODULES
typedef struct _RTL_BUFFER RTL_BUFFER
typedef struct _RTL_PROCESS_MODULE_INFORMATION RTL_PROCESS_MODULE_INFORMATION
typedef struct _RTL_PROCESS_MODULES RTL_PROCESS_MODULES
Function Documentation
NTSTATUS NTAPI LdrAccessOutOfProcessResource (IN ULONG Flags, PLDR_OUT_OF_PROCESS_IMAGE Image, IN CONST IMAGE_RESOURCE_DATA_ENTRY * DataEntry, OUT PULONG64 Address OPTIONAL, OUT PULONG Size OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrAccessResource (IN PVOID DllHandle, IN CONST IMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
Referenced by ExpInitializeExecutive().
NTSYSAPI NTSTATUS NTAPI LdrAddRefDll (ULONG Flags, PVOID DllHandle)
NTSYSAPI BOOLEAN NTAPI LdrAlternateResourcesEnabled (VOID)
NTSTATUS NTAPI LdrCreateOutOfProcessImage (IN ULONG Flags, IN HANDLE ProcessHandle, IN ULONG64 DllHandle, OUT PLDR_OUT_OF_PROCESS_IMAGE Image)
NTSYSAPI VOID NTAPI LdrDestroyOutOfProcessImage (IN OUT PLDR_OUT_OF_PROCESS_IMAGE Image)
NTSYSAPI NTSTATUS NTAPI LdrDisableThreadCalloutsForDll (IN PVOID DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrEnumerateLoadedModules (IN ULONG Flags, IN PLDR_LOADED_MODULE_ENUMERATION_CALLBACK_FUNCTION CallbackFunction, IN PVOID Context)
NTSYSAPI NTSTATUS NTAPI LdrEnumResources (IN PVOID DllHandle, IN CONST ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, IN OUT PULONG NumberOfResources, OUT PLDR_ENUM_RESOURCE_ENTRY Resources OPTIONAL)
NTSTATUS NTAPI LdrFindCreateProcessManifest (IN ULONG Flags, PLDR_OUT_OF_PROCESS_IMAGE Image, IN CONST ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY ResourceDataEntry)
NTSTATUS NTAPI LdrFindEntryForAddress (IN PVOID Address, OUT PLDR_DATA_TABLE_ENTRY * TableEntry)
Definition at line 294 of file ldrrsrc.c.
References CONTAINING_RECORD, _LDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_LDR_ID, DPFLTR_LEVEL_STATUS, _PEB_LDR_DATA::EntryInProgress, _LIST_ENTRY::Flink, _PEB_LDR_DATA::InMemoryOrderModuleList, KdPrintEx, NT_SUCCESS, NtCurrentPeb, NULL, _IMAGE_NT_HEADERS::OptionalHeader, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SizeOfImage, Status, STATUS_NO_MORE_ENTRIES, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI LdrFindResource_U (IN PVOID DllHandle, IN CONST ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry)
Referenced by ExpInitializeExecutive().
NTSYSAPI NTSTATUS NTAPI LdrFindResourceDirectory_U (IN PVOID DllHandle, IN CONST ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DIRECTORY * ResourceDirectory)
NTSTATUS NTAPI LdrFindResourceEx_U (ULONG Flags, IN PVOID DllHandle, IN CONST ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry)
NTSYSAPI BOOLEAN NTAPI LdrFlushAlternateResourceModules (VOID)
PVOID NTAPI LdrGetAlternateResourceModuleHandle (IN PVOID Module)
NTSYSAPI NTSTATUS NTAPI LdrGetDllHandle (IN PCWSTR DllPath OPTIONAL, IN PULONG DllCharacteristics OPTIONAL, IN PCUNICODE_STRING DllName, OUT PVOID * DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrGetDllHandleEx (IN ULONG Flags, IN PCWSTR DllPath OPTIONAL, IN PULONG DllCharacteristics OPTIONAL, IN PCUNICODE_STRING DllName, OUT PVOID *DllHandle OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrGetProcedureAddress (IN PVOID DllHandle, IN CONST ANSI_STRING *ProcedureName OPTIONAL, IN ULONG ProcedureNumber OPTIONAL, OUT PVOID * ProcedureAddress)
NTSYSAPI PVOID NTAPI LdrLoadAlternateResourceModule (IN PVOID Module, IN LPCWSTR PathToAlternateModule OPTIONAL)
NTSYSAPI NTSTATUS NTAPI LdrLoadDll (IN PCWSTR DllPath OPTIONAL, IN PULONG DllCharacteristics OPTIONAL, IN PCUNICODE_STRING DllName, OUT PVOID * DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrLockLoaderLock (IN ULONG Flags, OUT ULONG *Disposition OPTIONAL, OUT PVOID * Cookie)
NTSYSAPI NTSTATUS NTAPI LdrOpenImageFileOptionsKey (IN PCUNICODE_STRING ImagePathName, IN BOOLEAN Wow64Path, OUT PHANDLE KeyHandle)
PIMAGE_BASE_RELOCATION NTAPI LdrProcessRelocationBlock (IN ULONG_PTR VA, IN ULONG SizeOfBlock, IN PUSHORT NextOffset, IN LONG_PTR Diff)
Definition at line 243 of file ldrreloc.c.
References LdrProcessRelocationBlockLongLong().
NTSYSAPI VOID LdrProcessStarterHelper (IN PPROCESS_STARTER_ROUTINE ProcessStarter, IN PVOID RealStartAddress)
NTSYSAPI NTSTATUS NTAPI LdrQueryImageFileExecutionOptions (IN PCUNICODE_STRING ImagePathName, IN PCWSTR OptionName, IN ULONG Type, OUT PVOID Buffer, IN ULONG BufferSize, OUT PULONG ResultSize OPTIONAL)
NTSYSAPI NTSTATUS LdrQueryImageFileExecutionOptionsEx (IN PCUNICODE_STRING ImagePathName, IN PCWSTR OptionName, IN ULONG Type, OUT PVOID Buffer, IN ULONG BufferSize, OUT PULONG ResultSize OPTIONAL, IN BOOLEAN Wow64Path)
NTSYSAPI NTSTATUS NTAPI LdrQueryImageFileKeyOption (IN HANDLE KeyHandle, IN PCWSTR OptionName, IN ULONG Type, OUT PVOID Buffer, IN ULONG BufferSize, OUT PULONG ResultSize OPTIONAL)
NTSTATUS NTAPI LdrQueryProcessModuleInformation (OUT PRTL_PROCESS_MODULES ModuleInformation, IN ULONG ModuleInformationLength, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS NTAPI LdrRegisterDllNotification (IN ULONG Flags, IN PLDR_DLL_NOTIFICATION_FUNCTION NotificationFunction, IN PVOID Context, OUT PVOID * Cookie)
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImage (__in PVOID NewBase, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
Definition at line 51 of file ldrreloc.c.
References LdrRelocateImageWithBias().
Referenced by MiReloadBootLoadedDrivers(), and MmLoadSystemImage().
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImageWithBias (__in PVOID NewBase, __in LONGLONG Bias, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
Definition at line 100 of file ldrreloc.c.
References _IMAGE_FILE_HEADER::Characteristics, DbgPrint(), _IMAGE_NT_HEADERS::FileHeader, IMAGE_DIRECTORY_ENTRY_BASERELOC, IMAGE_FILE_RELOCS_STRIPPED, IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_NT_OPTIONAL_HDR64_MAGIC, LdrProcessRelocationBlockLongLong(), _IMAGE_OPTIONAL_HEADER::Magic, NULL, _IMAGE_NT_HEADERS::OptionalHeader, RTL_PAGED_CODE, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), Status, and TRUE.
Referenced by LdrRelocateImage().
NTSYSAPI NTSTATUS NTAPI LdrSetAppCompatDllRedirectionCallback (IN ULONG Flags, IN PLDR_APP_COMPAT_DLL_REDIRECTION_CALLBACK_FUNCTION CallbackFunction, IN PVOID CallbackData)
NTSYSAPI VOID NTAPI LdrSetDllManifestProber (IN PLDR_MANIFEST_PROBER_ROUTINE ManifestProberRoutine)
NTSYSAPI VOID NTAPI LdrShutdownProcess (VOID)
NTSYSAPI VOID NTAPI LdrShutdownThread (VOID)
NTSYSAPI BOOLEAN NTAPI LdrUnloadAlternateResourceModule (IN PVOID Module)
NTSYSAPI NTSTATUS NTAPI LdrUnloadDll (IN PVOID DllHandle)
NTSYSAPI NTSTATUS NTAPI LdrUnlockLoaderLock (IN ULONG Flags, IN OUT PVOID Cookie)
NTSTATUS NTAPI LdrUnregisterDllNotification (IN PVOID Cookie)
NTSTATUS NTAPI LdrVerifyImageMatchesChecksum (IN HANDLE ImageFileHandle, IN PLDR_IMPORT_MODULE_CALLBACK ImportCallbackRoutine OPTIONAL, IN PVOID ImportCallbackParameter, OUT PUSHORT ImageCharacteristics OPTIONAL)
BOOLEAN NTAPI LdrVerifyMappedImageMatchesChecksum (IN PVOID BaseAddress, IN SIZE_T NumberOfBytes, IN ULONG FileLength)
Referenced by MmCheckSystemImage().
typedef NTSTATUS (NTAPI * PLDR_MANIFEST_PROBER_ROUTINE)