Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/devquobj.c File Reference
devquobj.c File Reference
#include "ki.h"
Macros
#define ASSERT_DEVICE_QUEUE(E)
#define KiInvalidateDeviceQueueKeyHint(q, e)
#define KiSetDeviceQueueKeyHint(q, e)
Functions
VOID KeInitializeDeviceQueue (__out PKDEVICE_QUEUE DeviceQueue)
BOOLEAN KeInsertByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry, __in ULONG SortKey)
BOOLEAN KeInsertDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueueIfBusy (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
PKDEVICE_QUEUE_ENTRY KeRemoveDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue)
BOOLEAN KeRemoveEntryDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
Macro Definition Documentation
#define ASSERT_DEVICE_QUEUE (E)
Value:
{            \
    ASSERT((E)->Type == DeviceQueueObject); \
}
Definition at line 28 of file devquobj.c.
Referenced by KeInsertByKeyDeviceQueue(), KeInsertDeviceQueue(), KeRemoveByKeyDeviceQueue(), KeRemoveByKeyDeviceQueueIfBusy(), KeRemoveDeviceQueue(), and KeRemoveEntryDeviceQueue().
#define KiInvalidateDeviceQueueKeyHint (q, e)
Definition at line 148 of file devquobj.c.
Referenced by KeRemoveByKeyDeviceQueueIfBusy(), KeRemoveDeviceQueue(), and KeRemoveEntryDeviceQueue().
#define KiSetDeviceQueueKeyHint (q, e)
Definition at line 149 of file devquobj.c.
Referenced by KeInitializeDeviceQueue(), and KeRemoveByKeyDeviceQueue().
Function Documentation
VOID KeInitializeDeviceQueue (__out PKDEVICE_QUEUE DeviceQueue)
Definition at line 154 of file devquobj.c.
References DeviceQueueObject, FALSE, InitializeListHead(), KeInitializeSpinLock(), KiSetDeviceQueueKeyHint, and NULL.
Referenced by IoCreateController(), and IoCreateDevice().
BOOLEAN KeInsertByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry, __in ULONG SortKey)
Definition at line 267 of file devquobj.c.
References ASSERT_DEVICE_QUEUE, _LIST_ENTRY::Blink, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, InsertTailList(), IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiReleaseInStackQueuedSpinLockForDpc(), _KDEVICE_QUEUE_ENTRY::SortKey, and TRUE.
Referenced by IoStartPacket().
BOOLEAN KeInsertDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
Definition at line 199 of file devquobj.c.
References ASSERT_DEVICE_QUEUE, FALSE, InsertTailList(), KiAcquireInStackQueuedSpinLockForDpc(), KiReleaseInStackQueuedSpinLockForDpc(), and TRUE.
Referenced by IoAllocateController(), and IoStartPacket().
PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
Definition at line 439 of file devquobj.c.
References ASSERT, ASSERT_DEVICE_QUEUE, _LIST_ENTRY::Blink, CONTAINING_RECORD, _KDEVICE_QUEUE_ENTRY::DeviceListEntry, FALSE, _LIST_ENTRY::Flink, _KDEVICE_QUEUE_ENTRY::Inserted, IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiReleaseInStackQueuedSpinLockForDpc(), KiSetDeviceQueueKeyHint, NULL, RemoveEntryList(), _KDEVICE_QUEUE_ENTRY::SortKey, and TRUE.
Referenced by IopStartNextPacketByKey().
PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueueIfBusy (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
Definition at line 588 of file devquobj.c.
References ASSERT_DEVICE_QUEUE, CONTAINING_RECORD, _KDEVICE_QUEUE_ENTRY::DeviceListEntry, FALSE, _LIST_ENTRY::Flink, _KDEVICE_QUEUE_ENTRY::Inserted, IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiInvalidateDeviceQueueKeyHint, KiReleaseInStackQueuedSpinLockForDpc(), NULL, RemoveEntryList(), and RemoveHeadList().
PKDEVICE_QUEUE_ENTRY KeRemoveDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue)
Definition at line 369 of file devquobj.c.
References ASSERT, ASSERT_DEVICE_QUEUE, CONTAINING_RECORD, FALSE, _KDEVICE_QUEUE_ENTRY::Inserted, IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiInvalidateDeviceQueueKeyHint, KiReleaseInStackQueuedSpinLockForDpc(), NULL, RemoveHeadList(), and TRUE.
Referenced by IoFreeController(), and IopStartNextPacket().
BOOLEAN KeRemoveEntryDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
Definition at line 683 of file devquobj.c.
References ASSERT, ASSERT_DEVICE_QUEUE, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLock(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), KiInvalidateDeviceQueueKeyHint, RemoveEntryList(), and TRUE.