Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/dpcsup.c File Reference
dpcsup.c File Reference
#include "ki.h"
Data Structures
struct _DPC_ENTRY
Macros
#define MAXIMUM_DPC_TABLE_SIZE 16
#define MAXIMUM_TIMERS_EXAMINED 24
#define MAXIMUM_TIMERS_PROCESSED 4
Typedefs
typedef struct _DPC_ENTRY DPC_ENTRY
typedef struct _DPC_ENTRY * PDPC_ENTRY
Functions
VOID KiExecuteDpc (IN PVOID Context)
FORCEINLINE VOID KiProcessTimerDpcTable (IN PULARGE_INTEGER SystemTime, IN PDPC_ENTRY DpcTable, IN ULONG Count)
VOID KiQuantumEnd (VOID)
VOID FASTCALL KiRetireDpcList (PKPRCB Prcb)
VOID KiTimerExpiration (IN PKDPC TimerDpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID FASTCALL KiTimerListExpire (IN PLIST_ENTRY ExpiredListHead, IN KIRQL OldIrql)
Macro Definition Documentation
#define MAXIMUM_DPC_TABLE_SIZE 16
Definition at line 31 of file dpcsup.c.
Referenced by KiTimerListExpire().
#define MAXIMUM_TIMERS_EXAMINED 24
Definition at line 44 of file dpcsup.c.
Referenced by KiTimerExpiration().
#define MAXIMUM_TIMERS_PROCESSED 4
Definition at line 45 of file dpcsup.c.
Referenced by KiTimerExpiration().
Typedef Documentation
typedef struct _DPC_ENTRY DPC_ENTRY
typedef struct _DPC_ENTRY * PDPC_ENTRY
Function Documentation
VOID KiExecuteDpc (IN PVOID Context)
Definition at line 48 of file dpcsup.c.
References _KTHREAD::Affinity, ASSERT, CONTAINING_RECORD, _KDPC::DeferredContext, _KDPC::DeferredRoutine, DPC_THREADED, _KDPC::DpcData, _KPRCB::DpcData, _KPRCB::DpcEvent, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _PERFINFO_DPC_INFORMATION::DpcRoutine, _KPRCB::DpcThread, _KPRCB::DpcThreadActive, _KPRCB::DpcThreadRequested, FALSE, _LIST_ENTRY::Flink, HIGH_LEVEL, HIGH_PRIORITY, _PERFINFO_DPC_INFORMATION::InitialTime, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, KeMemoryBarrier(), KeRaiseIrql, KeReleaseSpinLockFromDpcLevel(), KernelMode, KeSetPriorityThread(), KeSetSystemAffinityThread(), KeWaitForSingleObject(), NULL, PASSIVE_LEVEL, PERF_DPC, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_DPC, PerfInfoLogBytes(), PerfTimeStamp, _KTHREAD::Priority, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _KPRCB::SetMember, Suspended, _KDPC::SystemArgument1, _KDPC::SystemArgument2, _KPRCB::ThreadDpcEnable, and TRUE.
Referenced by KeInitSystem().
FORCEINLINE VOID KiProcessTimerDpcTable (IN PULARGE_INTEGER SystemTime, IN PDPC_ENTRY DpcTable, IN ULONG Count)
++
Routine Description:
This function processes the time DPC table which is a array of DPCs that
are to be called on the current processor.
N.B. This routine is entered with the dispatcher database locked.
N.B. This routine returns with the dispatcher database unlocked.
Arguments:
SystemTime - Supplies a pointer to the timer expiration time.
DpcTable - Supplies a pointer to an array of DPC entries.
Count - Supplies a count of the number of entries in the DPC table.
Return Value:
None.
–
Definition at line 406 of file dpcsup.c.
References _KPRCB::DebugDpcTime, DISPATCH_LEVEL, _PERFINFO_DPC_INFORMATION::DpcRoutine, FALSE, _PERFINFO_DPC_INFORMATION::InitialTime, KeGetCurrentPrcb(), KiUnlockDispatcherDatabase(), PERF_DPC, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_TIMERDPC, PerfInfoLogBytes(), PerfTimeStamp, _LARGE_INTEGER::QuadPart, and ULongToPtr.
Referenced by KiTimerExpiration(), and KiTimerListExpire().
VOID KiQuantumEnd (VOID)
Definition at line 221 of file dpcsup.c.
References APC_LEVEL, _KTHREAD::ApcState, _KPRCB::CurrentThread, _KPROCESS::DisableQuantum, DISPATCH_LEVEL, _KPRCB::DpcEvent, _KPRCB::DpcSetEventRequest, FALSE, InterlockedExchange(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KeSetEvent(), KiAcquirePrcbLock(), KiAcquireThreadLock(), KiComputeNewPriority(), KiReleasePrcbLock(), KiReleaseThreadLock(), KiSelectReadyThread(), KiSetContextSwapBusy(), KiSwapContext(), KxQueueReadyThread(), LOW_REALTIME_PRIORITY, MAXCHAR, _KPRCB::NextThread, NULL, _KTHREAD::Preempted, _KTHREAD::Priority, _KAPC_STATE::Process, _KTHREAD::Quantum, _KTHREAD::QuantumReset, Running, Standby, _KTHREAD::State, TRUE, _KTHREAD::WaitIrql, _KTHREAD::WaitReason, and WrQuantumEnd.
VOID FASTCALL KiRetireDpcList (PKPRCB Prcb)
Definition at line 1043 of file dpcsup.c.
References _disable(), _enable(), ASSERT, CONTAINING_RECORD, _KPRCB::DebugDpcTime, _KDPC::DeferredContext, _KPRCB::DeferredReadyListHead, _KDPC::DeferredRoutine, DISPATCH_LEVEL, DPC_NORMAL, _KDPC::DpcData, _KPRCB::DpcData, _KPRCB::DpcInterruptRequested, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _PERFINFO_DPC_INFORMATION::DpcRoutine, _KPRCB::DpcRoutineActive, FALSE, _LIST_ENTRY::Flink, _PERFINFO_DPC_INFORMATION::InitialTime, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeLowerIrql, KeMemoryBarrier(), KeRaiseIrqlToSynchLevel(), KeReleaseSpinLockFromDpcLevel(), KiProcessDeferredReadyList(), KiTimerExpiration(), _SINGLE_LIST_ENTRY::Next, NULL, PERF_DPC, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_DPC, PerfInfoLogBytes(), PerfTimeStamp, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _KDPC::SystemArgument1, _KDPC::SystemArgument2, _KPRCB::TimerHand, _KPRCB::TimerRequest, and TRUE.
VOID KiTimerExpiration (IN PKDPC TimerDpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 504 of file dpcsup.c.
References _disable(), _enable(), ASSERT, CONTAINING_RECORD, _DPC_ENTRY::Context, _KDPC::DeferredContext, _KDPC::DeferredRoutine, DISPATCH_LEVEL, _DPC_ENTRY::Dpc, _KTIMER::Dpc, _KTIMER::DueTime, _KTIMER_TABLE_ENTRY::Entry, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, _LARGE_INTEGER::HighPart, Index, _DISPATCHER_HEADER::Inserted, Int32x32To64, IsListEmpty, KeGetCurrentPrcb(), KeInsertQueueDpc(), KeLowerIrql, KeNumberProcessors, KiAcquireTimerTableLock(), KiInsertTreeTimer(), KiLockDispatcherDatabase, KiProcessTimerDpcTable(), KiQueryInterruptTime, KiQueryLowTickCount, KiQuerySystemTime, KiReleaseTimerTableLock(), KiRemoveEntryTimer(), KiTimerTableListHead, KiTryToLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), _LARGE_INTEGER::LowPart, MAXIMUM_PROCESSORS, MAXIMUM_TIMERS_EXAMINED, MAXIMUM_TIMERS_PROCESSED, NULL, _KDPC::Number, _KPRCB::Number, _KTIMER::Period, PtrToLong, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, _DPC_ENTRY::Routine, _DISPATCHER_HEADER::SignalState, _KPRCB::ThreadDpcEnable, ThreadedDpcObject, _KTIMER_TABLE_ENTRY::Time, TIMER_EXPIRE_INCREMENT, TIMER_TABLE_SIZE, _KPRCB::TimerHand, TimerNotificationObject, _KDPC::Type, _DISPATCHER_HEADER::Type, ULongToPtr, UNREFERENCED_PARAMETER, and _DISPATCHER_HEADER::WaitListHead.
Referenced by KiInitSystem(), and KiRetireDpcList().
VOID FASTCALL KiTimerListExpire (IN PLIST_ENTRY ExpiredListHead, IN KIRQL OldIrql)
Definition at line 856 of file dpcsup.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _DPC_ENTRY::Context, Count, _KDPC::DeferredContext, _KDPC::DeferredRoutine, _DPC_ENTRY::Dpc, _KTIMER::Dpc, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, _LARGE_INTEGER::HighPart, _DISPATCHER_HEADER::Inserted, Int32x32To64, IsListEmpty, KeGetCurrentPrcb(), KeInsertQueueDpc(), KeLowerIrql, KiInsertTreeTimer(), KiLockDispatcherDatabase, KiProcessTimerDpcTable(), KiQuerySystemTime, KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), _LARGE_INTEGER::LowPart, MAXIMUM_DPC_TABLE_SIZE, MAXIMUM_PROCESSORS, NULL, _KDPC::Number, _KPRCB::Number, _KTIMER::Period, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _DPC_ENTRY::Routine, _DISPATCHER_HEADER::SignalState, _KPRCB::ThreadDpcEnable, ThreadedDpcObject, TIMER_EXPIRE_INCREMENT, _KTIMER::TimerListEntry, TimerNotificationObject, _KDPC::Type, _DISPATCHER_HEADER::Type, ULongToPtr, and _DISPATCHER_HEADER::WaitListHead.
Referenced by KeSetSystemTime().