Windows Research Kernel v1.2: C:/Windows Research Kernel/se/seastate.c File Reference
seastate.c File Reference
#include "pch.h"
Macros
#define GENERIC_ACCESS (GENERIC_READ | GENERIC_WRITE | GENERIC_EXECUTE | GENERIC_ALL)
#define SEP_PRIVILEGE_SET_HEADER_SIZE
Functions
NTSTATUS SeAppendPrivileges (__inout PACCESS_STATE AccessState, __in PPRIVILEGE_SET Privileges)
NTSTATUS SeCreateAccessState (__out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in_opt PGENERIC_MAPPING GenericMapping)
NTSTATUS SeCreateAccessStateEx (__in_opt PETHREAD Thread, __in PEPROCESS Process, __out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in_opt PGENERIC_MAPPING GenericMapping)
VOID SeDeleteAccessState (__in PACCESS_STATE AccessState)
VOID SepConcatenatePrivileges (IN PPRIVILEGE_SET TargetPrivilegeSet, IN ULONG TargetBufferSize, IN PPRIVILEGE_SET SourcePrivilegeSet)
VOID SeSetAccessStateGenericMapping (__inout PACCESS_STATE AccessState, __in PGENERIC_MAPPING GenericMapping)
Macro Definition Documentation
#define GENERIC_ACCESS (GENERIC_READ | GENERIC_WRITE | GENERIC_EXECUTE | GENERIC_ALL)
Definition at line 38 of file seastate.c.
Referenced by SeCreateAccessStateEx().
#define SEP_PRIVILEGE_SET_HEADER_SIZE
Value:
((ULONG)sizeof(PRIVILEGE_SET) -     \
                (ANYSIZE_ARRAY * (ULONG)sizeof(LUID_AND_ATTRIBUTES)))
Definition at line 47 of file seastate.c.
Referenced by SepConcatenatePrivileges().
Function Documentation
NTSTATUS SeAppendPrivileges (__inout PACCESS_STATE AccessState, __in PPRIVILEGE_SET Privileges)
Definition at line 323 of file seastate.c.
References ExAllocatePoolWithTag, ExFreePool(), INITIAL_PRIVILEGE_COUNT, NULL, PAGED_CODE, PagedPool, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, RtlCopyMemory, SepConcatenatePrivileges(), SepPrivilegeSetSize, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by IopCheckBackupRestorePrivilege(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckTraverseAccess(), and ObpIncrementHandleCount().
NTSTATUS SeCreateAccessState (__out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in_opt PGENERIC_MAPPING GenericMapping)
Definition at line 56 of file seastate.c.
References PsGetCurrentProcess(), PsGetCurrentThread(), and SeCreateAccessStateEx().
NTSTATUS SeCreateAccessStateEx (__in_opt PETHREAD Thread, __in PEPROCESS Process, __out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in_opt PGENERIC_MAPPING GenericMapping)
Definition at line 117 of file seastate.c.
References ARGUMENT_PRESENT, ASSERT, EffectiveToken, ExAllocateLocallyUniqueId(), FALSE, FIELD_OFFSET, GENERIC_ACCESS, NULL, PAGED_CODE, RtlMapGenericMask(), RtlZeroMemory, SeCaptureSubjectContextEx(), STATUS_SUCCESS, and TOKEN_HAS_TRAVERSE_PRIVILEGE.
Referenced by PspCreateProcess(), PspCreateThread(), and SeCreateAccessState().
VOID SeDeleteAccessState (__in PACCESS_STATE AccessState)
Definition at line 237 of file seastate.c.
References ExFreePool(), NULL, PAGED_CODE, _AUX_ACCESS_DATA::PrivilegesUsed, and SeReleaseSubjectContext().
Referenced by NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenThread(), ObDuplicateObject(), ObInsertObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObReferenceObjectByName(), PspCreateProcess(), PspCreateThread(), SepCreateToken(), and WmipCreateGuidObject().
VOID SepConcatenatePrivileges (IN PPRIVILEGE_SET TargetPrivilegeSet, IN ULONG TargetBufferSize, IN PPRIVILEGE_SET SourcePrivilegeSet)
Definition at line 432 of file seastate.c.
References ASSERT, PAGED_CODE, RtlMoveMemory, SEP_PRIVILEGE_SET_HEADER_SIZE, and SepPrivilegeSetSize.
Referenced by SeAppendPrivileges().
VOID SeSetAccessStateGenericMapping (__inout PACCESS_STATE AccessState, __in PGENERIC_MAPPING GenericMapping)
Definition at line 285 of file seastate.c.
References _AUX_ACCESS_DATA::GenericMapping, and PAGED_CODE.
Referenced by IopParseDevice().