Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/fsrtl.h File Reference
fsrtl.h File Reference
Data Structures
struct _BASE_MCB
struct _EOF_WAIT_BLOCK
struct _FILE_LOCK
struct _FILE_LOCK_INFO
struct _FSRTL_ADVANCED_FCB_HEADER
struct _FSRTL_AUXILIARY_BUFFER
struct _FSRTL_COMMON_FCB_HEADER
struct _FSRTL_PER_FILEOBJECT_CONTEXT
struct _FSRTL_PER_STREAM_CONTEXT
struct _LARGE_MCB
struct _MCB
struct TUNNEL
Macros
#define FSRTL_AUXILIARY_FLAG_DEALLOCATE 0x00000001
#define FSRTL_CACHE_TOP_LEVEL_IRP 0x02
#define FSRTL_FAST_IO_TOP_LEVEL_IRP 0x04
#define FSRTL_FAT_LEGAL 0x01
#define FSRTL_FLAG2_DO_MODIFIED_WRITE (0x01)
#define FSRTL_FLAG2_PURGE_WHEN_MAPPED (0x04)
#define FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS (0x02)
#define FSRTL_FLAG_ACQUIRE_MAIN_RSRC_EX (0x08)
#define FSRTL_FLAG_ACQUIRE_MAIN_RSRC_SH (0x10)
#define FSRTL_FLAG_ADVANCED_HEADER (0x40)
#define FSRTL_FLAG_EOF_ADVANCE_ACTIVE (0x80)
#define FSRTL_FLAG_FILE_LENGTH_CHANGED (0x02)
#define FSRTL_FLAG_FILE_MODIFIED (0x01)
#define FSRTL_FLAG_LIMIT_MODIFIED_PAGES (0x04)
#define FSRTL_FLAG_USER_MAPPED_FILE (0x20)
#define FSRTL_FSP_TOP_LEVEL_IRP 0x01
#define FSRTL_HPFS_LEGAL 0x02
#define FSRTL_MAX_TOP_LEVEL_IRP_FLAG 0xFFFF
#define FSRTL_MOD_WRITE_TOP_LEVEL_IRP 0x03
#define FSRTL_NTFS_LEGAL 0x04
#define FSRTL_NTFS_STREAM_LEGAL (FSRTL_NTFS_LEGAL | FSRTL_OLE_LEGAL)
#define FSRTL_OLE_LEGAL 0x10
#define FSRTL_VOLUME_DISMOUNT 1
#define FSRTL_VOLUME_DISMOUNT_FAILED 2
#define FSRTL_VOLUME_LOCK 3
#define FSRTL_VOLUME_LOCK_FAILED 4
#define FSRTL_VOLUME_MOUNT 6
#define FSRTL_VOLUME_UNLOCK 5
#define FSRTL_WILD_CHARACTER 0x08
#define FsRtlAllocatePoolWithQuotaTag(PoolType, NumberOfBytes, Tag)
#define FsRtlAllocatePoolWithTag(PoolType, NumberOfBytes, Tag)
#define FsRtlAreThereCurrentFileLocks(FL)
#define FsRtlCompleteRequest(IRP, STATUS)
#define FsRtlEnterFileSystem()
#define FsRtlExitFileSystem()
#define FsRtlFastLock(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11)
#define FsRtlGetPerStreamContextPointer(_fo) ((PFSRTL_ADVANCED_FCB_HEADER)((_fo)->FsContext))
#define FsRtlInitPerFileObjectContext(_fc, _owner, _inst)
#define FsRtlInitPerStreamContext(_fc, _owner, _inst, _cb)
#define FsRtlIsAnsiCharacterLegal(C, FLAGS)
#define FsRtlIsAnsiCharacterLegalFat(C, WILD_OK)
#define FsRtlIsAnsiCharacterLegalHpfs(C, WILD_OK)
#define FsRtlIsAnsiCharacterLegalNtfs(C, WILD_OK)
#define FsRtlIsAnsiCharacterLegalNtfsStream(C, WILD_OK)
#define FsRtlIsAnsiCharacterWild(C)
#define FsRtlIsLeadDbcsCharacter(DBCS_CHAR)
#define FsRtlIsUnicodeCharacterWild(C)
#define FsRtlLookupPerStreamContext(_sc, _oid, _iid)
#define FsRtlSetTopLevelIrpForModWriter()
#define FsRtlSetupAdvancedHeader(_advhdr, _fmutx)
#define FsRtlSupportsPerFileObjectContexts(_fo) FlagOn((_fo)->Flags,FO_FILE_OBJECT_HAS_EXTENSION)
#define FsRtlSupportsPerStreamContexts(_fo)
#define FsRtlTestAnsiCharacter(C, DEFAULT_RET, WILD_OK, FLAGS)
#define LEGAL_ANSI_CHARACTER_ARRAY FsRtlLegalAnsiCharacterArray
#define NLS_MB_CODE_PAGE_TAG NlsMbOemCodePageTag
#define NLS_OEM_LEAD_BYTE_INFO NlsOemLeadByteInfo
Typedefs
typedef struct _BASE_MCB BASE_MCB
typedef struct _EOF_WAIT_BLOCK EOF_WAIT_BLOCK
typedef enum _FAST_IO_POSSIBLE FAST_IO_POSSIBLE
typedef struct _FILE_LOCK FILE_LOCK
typedef struct _FILE_LOCK_INFO FILE_LOCK_INFO
typedef struct _FSRTL_ADVANCED_FCB_HEADER FSRTL_ADVANCED_FCB_HEADER
typedef struct _FSRTL_AUXILIARY_BUFFER FSRTL_AUXILIARY_BUFFER
typedef struct _FSRTL_COMMON_FCB_HEADER FSRTL_COMMON_FCB_HEADER
typedef enum _FSRTL_COMPARISON_RESULT FSRTL_COMPARISON_RESULT
typedef struct _FSRTL_PER_FILEOBJECT_CONTEXT FSRTL_PER_FILEOBJECT_CONTEXT
typedef struct _FSRTL_PER_STREAM_CONTEXT FSRTL_PER_STREAM_CONTEXT
typedef struct _LARGE_MCB LARGE_MCB
typedef ULONG LBN
typedef struct _MCB MCB
typedef PVOID OPLOCK
typedef BASE_MCB * PBASE_MCB
typedef BOOLEAN(* PCHECK_FOR_TRAVERSE_ACCESS) (__in PVOID NotifyContext, __in_opt PVOID TargetContext, __in PSECURITY_SUBJECT_CONTEXT SubjectContext)
typedef NTSTATUS(* PCOMPLETE_LOCK_IRP_ROUTINE) (__in PVOID Context, __in PIRP Irp)
typedef EOF_WAIT_BLOCK * PEOF_WAIT_BLOCK
typedef FILE_LOCK * PFILE_LOCK
typedef FILE_LOCK_INFO * PFILE_LOCK_INFO
typedef BOOLEAN(* PFILTER_REPORT_CHANGE) (__in PVOID NotifyContext, __in PVOID FilterContext)
typedef FSRTL_ADVANCED_FCB_HEADER * PFSRTL_ADVANCED_FCB_HEADER
typedef FSRTL_AUXILIARY_BUFFER * PFSRTL_AUXILIARY_BUFFER
typedef FSRTL_COMMON_FCB_HEADER * PFSRTL_COMMON_FCB_HEADER
typedef struct _FSRTL_PER_FILEOBJECT_CONTEXT * PFSRTL_PER_FILEOBJECT_CONTEXT
typedef struct _FSRTL_PER_STREAM_CONTEXT * PFSRTL_PER_STREAM_CONTEXT
typedef VOID(* PFSRTL_STACK_OVERFLOW_ROUTINE) (__in PVOID Context, __in PKEVENT Event)
typedef LARGE_MCB * PLARGE_MCB
typedef LBN * PLBN
typedef MCB * PMCB
typedef PVOID PNOTIFY_SYNC
typedef PVOID * POPLOCK
typedef VOID(* POPLOCK_FS_PREPOST_IRP) (__in PVOID Context, __in PIRP Irp)
typedef VOID(* POPLOCK_WAIT_COMPLETE_ROUTINE) (__in PVOID Context, __in PIRP Irp)
typedef struct TUNNEL * PTUNNEL
typedef VOID(* PUNLOCK_ROUTINE) (__in PVOID Context, __in PFILE_LOCK_INFO FileLockInfo)
typedef VBN * PVBN
typedef ULONG VBN
Enumerations
enum _FAST_IO_POSSIBLE { FastIoIsNotPossible = 0, FastIoIsPossible, FastIoIsQuestionable }
enum _FSRTL_COMPARISON_RESULT { LessThan = -1, EqualTo = 0, GreaterThan = 1 }
Functions
NTKERNELAPI VOID FsRtlAcquireFileExclusive (__in PFILE_OBJECT FileObject)
NTKERNELAPI NTSTATUS FsRtlAcquireFileExclusiveCommon (IN PFILE_OBJECT FileObject, IN FS_FILTER_SECTION_SYNC_TYPE SyncType, IN ULONG SectionPageProtection)
NTKERNELAPI VOID FsRtlAcquireFileForCcFlush (IN PFILE_OBJECT FileObject)
NTKERNELAPI NTSTATUS FsRtlAcquireFileForCcFlushEx (IN PFILE_OBJECT FileObject)
NTKERNELAPI BOOLEAN FsRtlAcquireFileForModWrite (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE *ResourceToRelease)
NTKERNELAPI NTSTATUS FsRtlAcquireFileForModWriteEx (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE *ResourceToRelease)
NTKERNELAPI NTSTATUS FsRtlAcquireToCreateMappedSection (IN PFILE_OBJECT FileObject, IN ULONG SectionPageProtection)
NTKERNELAPI BOOLEAN FsRtlAddBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Lbn, __in LONGLONG SectorCount)
NTKERNELAPI BOOLEAN FsRtlAddLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Lbn, __in LONGLONG SectorCount)
NTKERNELAPI BOOLEAN FsRtlAddMcbEntry (__in PMCB Mcb, __in VBN Vbn, __in LBN Lbn, __in ULONG SectorCount)
NTKERNELAPI VOID FsRtlAddToTunnelCache (__in TUNNEL *Cache, __in ULONGLONG DirectoryKey, __in UNICODE_STRING *ShortName, __in UNICODE_STRING *LongName, __in BOOLEAN KeyByShortName, __in ULONG DataLength, __in_bcount(DataLength) VOID *Data)
NTKERNELAPI PFILE_LOCK FsRtlAllocateFileLock (__in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
NTKERNELAPI PERESOURCE FsRtlAllocateResource ()
NTKERNELAPI BOOLEAN FsRtlAreNamesEqual (__in PCUNICODE_STRING ConstantNameA, __in PCUNICODE_STRING ConstantNameB, __in BOOLEAN IgnoreCase, __in_opt PCWCH UpcaseTable)
NTKERNELAPI NTSTATUS FsRtlBalanceReads (__in PDEVICE_OBJECT TargetDevice)
NTKERNELAPI BOOLEAN FsRtlCheckLockForReadAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
NTKERNELAPI BOOLEAN FsRtlCheckLockForWriteAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
NTKERNELAPI NTSTATUS FsRtlCheckOplock (__in POPLOCK Oplock, __in PIRP Irp, __in_opt PVOID Context, __in_opt POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine, __in_opt POPLOCK_FS_PREPOST_IRP PostIrpRoutine)
NTKERNELAPI BOOLEAN FsRtlCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
NTKERNELAPI BOOLEAN FsRtlCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __in_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS FsRtlCreateSectionForDataScan (OUT PHANDLE SectionHandle, OUT PVOID *SectionObject, OUT PLARGE_INTEGER SectionFileSize OPTIONAL, IN PFILE_OBJECT FileObject, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN PLARGE_INTEGER MaximumSize OPTIONAL, IN ULONG SectionPageProtection, IN ULONG AllocationAttributes, IN ULONG Flags)
NTKERNELAPI BOOLEAN FsRtlCurrentBatchOplock (__in POPLOCK Oplock)
NTKERNELAPI VOID FsRtlDeleteKeyFromTunnelCache (__in TUNNEL *Cache, __in ULONGLONG DirectoryKey)
NTKERNELAPI VOID FsRtlDeleteTunnelCache (__in TUNNEL *Cache)
NTKERNELAPI VOID FsRtlDeregisterUncProvider (__in HANDLE Handle)
NTKERNELAPI VOID FsRtlDissectDbcs (__in ANSI_STRING Path, __out PANSI_STRING FirstName, __out PANSI_STRING RemainingName)
NTKERNELAPI VOID FsRtlDissectName (__in UNICODE_STRING Path, __out PUNICODE_STRING FirstName, __out PUNICODE_STRING RemainingName)
NTKERNELAPI BOOLEAN FsRtlDoesDbcsContainWildCards (__in PANSI_STRING Name)
NTKERNELAPI BOOLEAN FsRtlDoesNameContainWildCards (__in PUNICODE_STRING Name)
NTKERNELAPI BOOLEAN FsRtlFastCheckLockForRead (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PFILE_OBJECT FileObject, __in PVOID ProcessId)
NTKERNELAPI BOOLEAN FsRtlFastCheckLockForWrite (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PVOID FileObject, __in PVOID ProcessId)
NTKERNELAPI NTSTATUS FsRtlFastUnlockAll (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in_opt PVOID Context)
NTKERNELAPI NTSTATUS FsRtlFastUnlockAllByKey (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context)
NTKERNELAPI NTSTATUS FsRtlFastUnlockSingle (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in LARGE_INTEGER UNALIGNED *FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
NTKERNELAPI BOOLEAN FsRtlFindInTunnelCache (__in TUNNEL *Cache, __in ULONGLONG DirectoryKey, __in UNICODE_STRING *Name, __out UNICODE_STRING *ShortName, __out UNICODE_STRING *LongName, __inout ULONG *DataLength, __out_bcount_part(*DataLength,*DataLength) VOID *Data)
NTKERNELAPI VOID FsRtlFreeFileLock (__in PFILE_LOCK FileLock)
NTSTATUS FsRtlGetFileSize (__in PFILE_OBJECT FileObject, __inout PLARGE_INTEGER FileSize)
NTKERNELAPI BOOLEAN FsRtlGetNextBaseMcbEntry (__in PBASE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG Vbn, __out PLONGLONG Lbn, __out PLONGLONG SectorCount)
NTKERNELAPI PFILE_LOCK_INFO FsRtlGetNextFileLock (__in PFILE_LOCK FileLock, __in BOOLEAN Restart)
NTKERNELAPI BOOLEAN FsRtlGetNextLargeMcbEntry (__in PLARGE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG Vbn, __out PLONGLONG Lbn, __out PLONGLONG SectorCount)
NTKERNELAPI BOOLEAN FsRtlGetNextMcbEntry (__in PMCB Mcb, __in ULONG RunIndex, __out PVBN Vbn, __out PLBN Lbn, __out PULONG SectorCount)
NTKERNELAPI VOID FsRtlIncrementCcFastReadNotPossible (VOID)
NTKERNELAPI VOID FsRtlIncrementCcFastReadNoWait (VOID)
NTKERNELAPI VOID FsRtlIncrementCcFastReadResourceMiss (VOID)
NTKERNELAPI VOID FsRtlIncrementCcFastReadWait (VOID)
NTKERNELAPI VOID FsRtlInitializeBaseMcb (__in PBASE_MCB Mcb, __in POOL_TYPE PoolType)
NTKERNELAPI VOID FsRtlInitializeFileLock (__in PFILE_LOCK FileLock, __in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
NTKERNELAPI VOID FsRtlInitializeLargeMcb (__in PLARGE_MCB Mcb, __in POOL_TYPE PoolType)
NTKERNELAPI VOID FsRtlInitializeMcb (__in PMCB Mcb, __in POOL_TYPE PoolType)
NTKERNELAPI VOID FsRtlInitializeOplock (__inout POPLOCK Oplock)
NTKERNELAPI VOID FsRtlInitializeTunnelCache (__in TUNNEL *Cache)
NTKERNELAPI BOOLEAN FsRtlInitSystem ()
NTKERNELAPI NTSTATUS FsRtlInsertPerFileObjectContext (__in PFILE_OBJECT FileObject, __in PFSRTL_PER_FILEOBJECT_CONTEXT Ptr)
NTKERNELAPI NTSTATUS FsRtlInsertPerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER PerStreamContext, __in PFSRTL_PER_STREAM_CONTEXT Ptr)
NTKERNELAPI BOOLEAN FsRtlIsDbcsInExpression (__in PANSI_STRING Expression, __in PANSI_STRING Name)
NTKERNELAPI BOOLEAN FsRtlIsFatDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
NTKERNELAPI BOOLEAN FsRtlIsHpfsDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
NTKERNELAPI BOOLEAN FsRtlIsNameInExpression (__in PUNICODE_STRING Expression, __in PUNICODE_STRING Name, __in BOOLEAN IgnoreCase, __in_opt PWCH UpcaseTable)
NTKERNELAPI BOOLEAN FsRtlIsNtstatusExpected (__in NTSTATUS Exception)
NTKERNELAPI LOGICAL FsRtlIsPagingFile (__in PFILE_OBJECT FileObject)
NTKERNELAPI BOOLEAN FsRtlIsTotalDeviceFailure (__in NTSTATUS Status)
NTKERNELAPI BOOLEAN FsRtlLookupBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __out_opt PLONGLONG Lbn, __out_opt PLONGLONG SectorCountFromLbn, __out_opt PLONGLONG StartingLbn, __out_opt PLONGLONG SectorCountFromStartingLbn, __out_opt PULONG Index)
NTKERNELAPI BOOLEAN FsRtlLookupLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __out_opt PLONGLONG Lbn, __out_opt PLONGLONG SectorCountFromLbn, __out_opt PLONGLONG StartingLbn, __out_opt PLONGLONG SectorCountFromStartingLbn, __out_opt PULONG Index)
NTKERNELAPI BOOLEAN FsRtlLookupLastBaseMcbEntry (__in PBASE_MCB Mcb, __out PLONGLONG Vbn, __out PLONGLONG Lbn)
NTKERNELAPI BOOLEAN FsRtlLookupLastBaseMcbEntryAndIndex (__in PBASE_MCB OpaqueMcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
NTKERNELAPI BOOLEAN FsRtlLookupLastLargeMcbEntry (__in PLARGE_MCB Mcb, __out PLONGLONG Vbn, __out PLONGLONG Lbn)
NTKERNELAPI BOOLEAN FsRtlLookupLastLargeMcbEntryAndIndex (__in PLARGE_MCB OpaqueMcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
NTKERNELAPI BOOLEAN FsRtlLookupLastMcbEntry (__in PMCB Mcb, __out PVBN Vbn, __out PLBN Lbn)
NTKERNELAPI BOOLEAN FsRtlLookupMcbEntry (__in PMCB Mcb, __in VBN Vbn, __out PLBN Lbn, __out_opt PULONG SectorCount, __out PULONG Index)
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlLookupPerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlLookupPerStreamContextInternal (__in PFSRTL_ADVANCED_FCB_HEADER StreamContext, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTSTATUS FsRtlMappedFile (IN PFILE_OBJECT FileObject, IN ULONG DesiredAccess, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length)
NTKERNELAPI BOOLEAN FsRtlMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI BOOLEAN FsRtlMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
NTKERNELAPI BOOLEAN FsRtlMdlReadCompleteDev (__in PFILE_OBJECT FileObject, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
NTKERNELAPI BOOLEAN FsRtlMdlReadDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
BOOLEAN FsRtlMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
NTKERNELAPI BOOLEAN FsRtlMdlWriteCompleteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS FsRtlNormalizeNtstatus (__in NTSTATUS Exception, __in NTSTATUS GenericException)
NTKERNELAPI VOID FsRtlNotifyChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in PLIST_ENTRY NotifyList, __in BOOLEAN WatchTree, __in ULONG CompletionFilter, __in PIRP NotifyIrp)
NTKERNELAPI VOID FsRtlNotifyCleanup (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext)
NTKERNELAPI VOID FsRtlNotifyFilterChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext, __in_opt PFILTER_REPORT_CHANGE FilterCallback)
NTKERNELAPI VOID FsRtlNotifyFilterReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in_opt PVOID TargetContext, __in_opt PVOID FilterContext)
NTKERNELAPI VOID FsRtlNotifyFullChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext)
NTKERNELAPI VOID FsRtlNotifyFullReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in PVOID TargetContext)
NTKERNELAPI VOID FsRtlNotifyInitializeSync (__in PNOTIFY_SYNC *NotifySync)
NTKERNELAPI VOID FsRtlNotifyReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in PSTRING TargetName, __in ULONG FilterMatch)
NTKERNELAPI VOID FsRtlNotifyUninitializeSync (__in PNOTIFY_SYNC *NotifySync)
NTKERNELAPI NTSTATUS FsRtlNotifyVolumeEvent (__in PFILE_OBJECT FileObject, __in ULONG EventCode)
NTKERNELAPI ULONG FsRtlNumberOfRunsInBaseMcb (__in PBASE_MCB Mcb)
NTKERNELAPI ULONG FsRtlNumberOfRunsInLargeMcb (__in PLARGE_MCB Mcb)
NTKERNELAPI ULONG FsRtlNumberOfRunsInMcb (__in PMCB Mcb)
NTKERNELAPI NTSTATUS FsRtlOplockFsctrl (__in POPLOCK Oplock, __in PIRP Irp, __in ULONG OpenCount)
NTKERNELAPI BOOLEAN FsRtlOplockIsFastIoPossible (__in POPLOCK Oplock)
NTKERNELAPI VOID FsRtlPostPagingFileStackOverflow (__in PVOID Context, __in PKEVENT Event, __in PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
NTKERNELAPI VOID FsRtlPostStackOverflow (__in PVOID Context, __in PKEVENT Event, __in PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
NTKERNELAPI BOOLEAN FsRtlPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI BOOLEAN FsRtlPrepareMdlWriteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
NTKERNELAPI BOOLEAN FsRtlPrivateLock (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in BOOLEAN FailImmediately, __in BOOLEAN ExclusiveLock, __out PIO_STATUS_BLOCK Iosb, __in_opt PIRP Irp, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
NTKERNELAPI NTSTATUS FsRtlProcessFileLock (__in PFILE_LOCK FileLock, __in PIRP Irp, __in_opt PVOID Context)
VOID FsRtlPTeardownPerFileObjectContexts (__in PFILE_OBJECT FileObject)
NTKERNELAPI NTSTATUS FsRtlRegisterUncProvider (__inout PHANDLE MupHandle, __in PUNICODE_STRING RedirectorDeviceName, __in BOOLEAN MailslotsSupported)
NTKERNELAPI VOID FsRtlReleaseFile (__in PFILE_OBJECT FileObject)
NTKERNELAPI VOID FsRtlReleaseFileForCcFlush (IN PFILE_OBJECT FileObject)
NTKERNELAPI VOID FsRtlReleaseFileForModWrite (IN PFILE_OBJECT FileObject, IN PERESOURCE ResourceToRelease)
NTKERNELAPI VOID FsRtlRemoveBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG SectorCount)
NTKERNELAPI VOID FsRtlRemoveLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG SectorCount)
NTKERNELAPI VOID FsRtlRemoveMcbEntry (__in PMCB Mcb, __in VBN Vbn, __in ULONG SectorCount)
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlRemovePerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlRemovePerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER StreamContext, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTKERNELAPI VOID FsRtlResetBaseMcb (__in PBASE_MCB Mcb)
NTKERNELAPI VOID FsRtlResetLargeMcb (__in PLARGE_MCB Mcb, __in BOOLEAN SelfSynchronized)
NTSTATUS FsRtlSetFileSize (IN PFILE_OBJECT FileObject, IN OUT PLARGE_INTEGER FileSize)
NTKERNELAPI BOOLEAN FsRtlSplitBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Amount)
NTKERNELAPI BOOLEAN FsRtlSplitLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Amount)
NTKERNELAPI NTSTATUS FsRtlSyncVolumes (__in PDEVICE_OBJECT TargetDevice, __in_opt PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER ByteCount)
NTKERNELAPI VOID FsRtlTeardownPerStreamContexts (__in PFSRTL_ADVANCED_FCB_HEADER AdvancedHeader)
NTKERNELAPI VOID FsRtlTruncateBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG Vbn)
NTKERNELAPI VOID FsRtlTruncateLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG Vbn)
NTKERNELAPI VOID FsRtlTruncateMcb (__in PMCB Mcb, __in VBN Vbn)
NTKERNELAPI VOID FsRtlUninitializeBaseMcb (__in PBASE_MCB Mcb)
NTKERNELAPI VOID FsRtlUninitializeFileLock (__in PFILE_LOCK FileLock)
NTKERNELAPI VOID FsRtlUninitializeLargeMcb (__in PLARGE_MCB Mcb)
NTKERNELAPI VOID FsRtlUninitializeMcb (__in PMCB Mcb)
NTKERNELAPI VOID FsRtlUninitializeOplock (__inout POPLOCK Oplock)
Variables
UCHAR const *const LEGAL_ANSI_CHARACTER_ARRAY
PUSHORT NLS_OEM_LEAD_BYTE_INFO
Macro Definition Documentation
#define FSRTL_AUXILIARY_FLAG_DEALLOCATE 0x00000001
Definition at line 400 of file fsrtl.h.
#define FSRTL_CACHE_TOP_LEVEL_IRP 0x02
Definition at line 228 of file fsrtl.h.
#define FSRTL_FAST_IO_TOP_LEVEL_IRP 0x04
Definition at line 230 of file fsrtl.h.
Referenced by FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), and FsRtlPrepareMdlWriteDev().
#define FSRTL_FAT_LEGAL 0x01
Definition at line 922 of file fsrtl.h.
#define FSRTL_FLAG2_DO_MODIFIED_WRITE (0x01)
Definition at line 204 of file fsrtl.h.
Referenced by CcInitializeCacheMap().
#define FSRTL_FLAG2_PURGE_WHEN_MAPPED (0x04)
Definition at line 219 of file fsrtl.h.
Referenced by CcZeroEndOfLastPage().
#define FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS (0x02)
Definition at line 212 of file fsrtl.h.
Referenced by FsRtlInsertPerStreamContext(), FsRtlLookupPerStreamContextInternal(), and FsRtlRemovePerStreamContext().
#define FSRTL_FLAG_ACQUIRE_MAIN_RSRC_EX (0x08)
Definition at line 170 of file fsrtl.h.
Referenced by FsRtlAcquireFileForModWriteEx().
#define FSRTL_FLAG_ACQUIRE_MAIN_RSRC_SH (0x10)
Definition at line 171 of file fsrtl.h.
Referenced by FsRtlAcquireFileForModWriteEx().
#define FSRTL_FLAG_ADVANCED_HEADER (0x40)
Definition at line 185 of file fsrtl.h.
Referenced by CcCopyWrite(), and CcZeroEndOfLastPage().
#define FSRTL_FLAG_EOF_ADVANCE_ACTIVE (0x80)
Definition at line 191 of file fsrtl.h.
#define FSRTL_FLAG_FILE_LENGTH_CHANGED (0x02)
Definition at line 159 of file fsrtl.h.
#define FSRTL_FLAG_FILE_MODIFIED (0x01)
Definition at line 158 of file fsrtl.h.
#define FSRTL_FLAG_LIMIT_MODIFIED_PAGES (0x04)
Definition at line 160 of file fsrtl.h.
Referenced by CcCanIWrite(), CcDeferWrite(), and CcSetDirtyPageThreshold().
#define FSRTL_FLAG_USER_MAPPED_FILE (0x20)
Definition at line 178 of file fsrtl.h.
Referenced by CcFlushCache(), and CcZeroEndOfLastPage().
#define FSRTL_FSP_TOP_LEVEL_IRP 0x01
Definition at line 227 of file fsrtl.h.
Referenced by FsRtlCreateSectionForDataScan(), FsRtlStackOverflowRead(), MiRemoveUnusedSegments(), and MmCreateSection().
#define FSRTL_HPFS_LEGAL 0x02
Definition at line 923 of file fsrtl.h.
#define FSRTL_MAX_TOP_LEVEL_IRP_FLAG 0xFFFF
Definition at line 231 of file fsrtl.h.
#define FSRTL_MOD_WRITE_TOP_LEVEL_IRP 0x03
Definition at line 229 of file fsrtl.h.
#define FSRTL_NTFS_LEGAL 0x04
Definition at line 924 of file fsrtl.h.
#define FSRTL_NTFS_STREAM_LEGAL (FSRTL_NTFS_LEGAL | FSRTL_OLE_LEGAL)
Definition at line 927 of file fsrtl.h.
#define FSRTL_OLE_LEGAL 0x10
Definition at line 926 of file fsrtl.h.
#define FSRTL_VOLUME_DISMOUNT 1
Definition at line 1518 of file fsrtl.h.
Referenced by FsRtlNotifyVolumeEvent(), and RawUserFsCtrl().
#define FSRTL_VOLUME_DISMOUNT_FAILED 2
Definition at line 1519 of file fsrtl.h.
Referenced by FsRtlNotifyVolumeEvent(), and RawUserFsCtrl().
#define FSRTL_VOLUME_LOCK 3
Definition at line 1520 of file fsrtl.h.
Referenced by FsRtlNotifyVolumeEvent(), and RawUserFsCtrl().
#define FSRTL_VOLUME_LOCK_FAILED 4
Definition at line 1521 of file fsrtl.h.
Referenced by FsRtlNotifyVolumeEvent(), and RawUserFsCtrl().
#define FSRTL_VOLUME_MOUNT 6
Definition at line 1523 of file fsrtl.h.
Referenced by FsRtlNotifyVolumeEvent(), and RawMountVolume().
#define FSRTL_VOLUME_UNLOCK 5
Definition at line 1522 of file fsrtl.h.
Referenced by FsRtlNotifyVolumeEvent(), and RawUserFsCtrl().
#define FSRTL_WILD_CHARACTER 0x08
Definition at line 925 of file fsrtl.h.
#define FsRtlAllocatePoolWithQuotaTag (PoolType, NumberOfBytes, Tag)
Value:
ExAllocatePoolWithQuotaTag((POOL_TYPE)((PoolType) | POOL_RAISE_IF_ALLOCATION_FAILURE), \
                               NumberOfBytes,                                 \
                               Tag)
Definition at line 1096 of file fsrtl.h.
#define FsRtlAllocatePoolWithTag (PoolType, NumberOfBytes, Tag)
Value:
ExAllocatePoolWithTag((POOL_TYPE)((PoolType) | POOL_RAISE_IF_ALLOCATION_FAILURE), \
                          NumberOfBytes,                                      \
                          Tag)
Definition at line 1090 of file fsrtl.h.
Referenced by FsRtlFindInTunnelCache().
#define FsRtlAreThereCurrentFileLocks (FL)
Value:
(\
    ((FL)->FastIoIsQuestionable))
Definition at line 789 of file fsrtl.h.
#define FsRtlCompleteRequest (IRP, STATUS)
Value:
{         \
    (IRP)->IoStatus.Status = (STATUS);             \
    IoCompleteRequest( (IRP), IO_DISK_INCREMENT ); \
}
Definition at line 2099 of file fsrtl.h.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCancelExclusiveIrp(), FsRtlCancelNotify(), FsRtlCompleteLockIrpReal(), FsRtlNotifyCompleteIrp(), FsRtlNotifyCompletion(), FsRtlNotifyFilterChangeDirectory(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlOplockFsctrl(), FsRtlProcessFileLock(), FsRtlRemoveAndCompleteIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), and FsRtlUninitializeOplock().
#define FsRtlEnterFileSystem ()
Value:
{ \
    KeEnterCriticalRegion();     \
}
Definition at line 2126 of file fsrtl.h.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlCancelNotify(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlCreateSectionForDataScan(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), and RawDispatch().
#define FsRtlExitFileSystem ()
Value:
{ \
    KeLeaveCriticalRegion();    \
}
Definition at line 2149 of file fsrtl.h.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlCancelNotify(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlCreateSectionForDataScan(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and RawDispatch().
#define FsRtlFastLock (A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11)
Value:
(\
    FsRtlPrivateLock( A1,   /* FileLock            */       \
                      A2,   /* FileObject          */       \
                      A3,   /* FileOffset          */       \
                      A4,   /* Length              */       \
                      A5,   /* ProcessId           */       \
                      A6,   /* Key                 */       \
                      A7,   /* FailImmediately     */       \
                      A8,   /* ExclusiveLock       */       \
                      A9,   /* Iosb                */       \
                      NULL, /* Irp                 */       \
                      A10,  /* Context             */       \
                      A11   /* AlreadySynchronized */ )     \
)
Definition at line 767 of file fsrtl.h.
#define FsRtlGetPerStreamContextPointer (_fo) ((PFSRTL_ADVANCED_FCB_HEADER)((_fo)->FsContext))
Definition at line 1832 of file fsrtl.h.
#define FsRtlInitPerFileObjectContext (_fc, _owner, _inst)
Value:
((_fc)->OwnerId = (_owner),                                     \
     (_fc)->InstanceId = (_inst))                                   \
Definition at line 1999 of file fsrtl.h.
#define FsRtlInitPerStreamContext (_fc, _owner, _inst, _cb)
Value:
((_fc)->OwnerId = (_owner),                               \
     (_fc)->InstanceId = (_inst),                             \
     (_fc)->FreeCallback = (_cb))
Definition at line 1822 of file fsrtl.h.
#define FsRtlIsAnsiCharacterLegal (C, FLAGS)
Value:
(\
    FsRtlTestAnsiCharacter((C), TRUE, FALSE, (FLAGS)) \
)
Definition at line 975 of file fsrtl.h.
#define FsRtlIsAnsiCharacterLegalFat (C, WILD_OK)
Value:
(\
    FsRtlTestAnsiCharacter((C), TRUE, (WILD_OK), FSRTL_FAT_LEGAL) \
)
Definition at line 941 of file fsrtl.h.
Referenced by FsRtlIsFatDbcsLegal().
#define FsRtlIsAnsiCharacterLegalHpfs (C, WILD_OK)
Value:
(\
    FsRtlTestAnsiCharacter((C), TRUE, (WILD_OK), FSRTL_HPFS_LEGAL) \
)
Definition at line 949 of file fsrtl.h.
Referenced by FsRtlIsHpfsDbcsLegal().
#define FsRtlIsAnsiCharacterLegalNtfs (C, WILD_OK)
Value:
(\
    FsRtlTestAnsiCharacter((C), TRUE, (WILD_OK), FSRTL_NTFS_LEGAL) \
)
Definition at line 957 of file fsrtl.h.
#define FsRtlIsAnsiCharacterLegalNtfsStream (C, WILD_OK)
Value:
(\
    FsRtlTestAnsiCharacter((C), TRUE, (WILD_OK), FSRTL_NTFS_STREAM_LEGAL)   \
)
Definition at line 966 of file fsrtl.h.
#define FsRtlIsAnsiCharacterWild (C)
Value:
(\
    FsRtlTestAnsiCharacter((C), FALSE, FALSE, FSRTL_WILD_CHARACTER) \
)
Definition at line 933 of file fsrtl.h.
Referenced by FsRtlDoesDbcsContainWildCards().
#define FsRtlIsLeadDbcsCharacter (DBCS_CHAR)
Value:
(\
    (BOOLEAN)((UCHAR)(DBCS_CHAR) < 0x80 ? FALSE :                  \
              (NLS_MB_CODE_PAGE_TAG &&                             \
               (NLS_OEM_LEAD_BYTE_INFO[(UCHAR)(DBCS_CHAR)] != 0))) \
)
Definition at line 1020 of file fsrtl.h.
Referenced by FsRtlDissectDbcs(), FsRtlDoesDbcsContainWildCards(), FsRtlIsDbcsInExpression(), FsRtlIsFatDbcsLegal(), and FsRtlIsHpfsDbcsLegal().
#define FsRtlIsUnicodeCharacterWild (C)
Value:
(\
      (((C) >= 0x40) ? FALSE : FlagOn( LEGAL_ANSI_CHARACTER_ARRAY[(C)], \
                                       FSRTL_WILD_CHARACTER ) )         \
)
Definition at line 1672 of file fsrtl.h.
Referenced by FsRtlDoesNameContainWildCards().
#define FsRtlLookupPerStreamContext (_sc, _oid, _iid)
Value:
(((NULL != (_sc)) &&                                                         \
   FlagOn((_sc)->Flags2,FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS) &&              \
   !IsListEmpty(&(_sc)->FilterContexts)) ?                                    \
        FsRtlLookupPerStreamContextInternal((_sc), (_oid), (_iid)) :          \
        NULL)
Definition at line 1876 of file fsrtl.h.
#define FsRtlSetTopLevelIrpForModWriter ()
Value:
{             \
    PIRP tempIrp = (PIRP)FSRTL_MOD_WRITE_TOP_LEVEL_IRP; \
    IoSetTopLevelIrp(tempIrp);                          \
}
Definition at line 412 of file fsrtl.h.
Referenced by MiMappedPageWriter().
#define FsRtlSetupAdvancedHeader (_advhdr, _fmutx)
Value:
{                                                                           \
    SetFlag( (_advhdr)->Flags, FSRTL_FLAG_ADVANCED_HEADER );                \
    SetFlag( (_advhdr)->Flags2, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS );     \
    InitializeListHead( &(_advhdr)->FilterContexts );                       \
    if ((_fmutx) != NULL) {                                                 \
        (_advhdr)->FastMutex = (_fmutx);                                    \
    }                                                                       \
}
Definition at line 1921 of file fsrtl.h.
#define FsRtlSupportsPerFileObjectContexts (_fo) FlagOn((_fo)->Flags,FO_FILE_OBJECT_HAS_EXTENSION)
Definition at line 2008 of file fsrtl.h.
Referenced by FsRtlInsertPerFileObjectContext().
#define FsRtlSupportsPerStreamContexts (_fo)
Value:
((NULL != FsRtlGetPerStreamContextPointer(_fo)) &&          \
     FlagOn(FsRtlGetPerStreamContextPointer(_fo)->Flags2,       \
                    FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS))
Definition at line 1840 of file fsrtl.h.
#define FsRtlTestAnsiCharacter (C, DEFAULT_RET, WILD_OK, FLAGS)
Value:
(\
        ((SCHAR)(C) < 0) ? DEFAULT_RET :                                    \
                           FlagOn( LEGAL_ANSI_CHARACTER_ARRAY[(C)],         \
                                   (FLAGS) |                                \
                                   ((WILD_OK) ? FSRTL_WILD_CHARACTER : 0) ) \
)
Definition at line 984 of file fsrtl.h.
#define LEGAL_ANSI_CHARACTER_ARRAY FsRtlLegalAnsiCharacterArray
Definition at line 908 of file fsrtl.h.
#define NLS_MB_CODE_PAGE_TAG NlsMbOemCodePageTag
Definition at line 909 of file fsrtl.h.
#define NLS_OEM_LEAD_BYTE_INFO NlsOemLeadByteInfo
Definition at line 910 of file fsrtl.h.
Typedef Documentation
typedef struct _BASE_MCB BASE_MCB
typedef struct _EOF_WAIT_BLOCK EOF_WAIT_BLOCK
typedef enum _FAST_IO_POSSIBLE FAST_IO_POSSIBLE
typedef struct _FILE_LOCK FILE_LOCK
typedef struct _FILE_LOCK_INFO FILE_LOCK_INFO
typedef struct _FSRTL_ADVANCED_FCB_HEADER FSRTL_ADVANCED_FCB_HEADER
typedef struct _FSRTL_AUXILIARY_BUFFER FSRTL_AUXILIARY_BUFFER
typedef struct _FSRTL_COMMON_FCB_HEADER FSRTL_COMMON_FCB_HEADER
typedef enum _FSRTL_COMPARISON_RESULT FSRTL_COMPARISON_RESULT
typedef struct _FSRTL_PER_FILEOBJECT_CONTEXT FSRTL_PER_FILEOBJECT_CONTEXT
typedef struct _FSRTL_PER_STREAM_CONTEXT FSRTL_PER_STREAM_CONTEXT
typedef struct _LARGE_MCB LARGE_MCB
typedef ULONG LBN
Definition at line 27 of file fsrtl.h.
typedef struct _MCB MCB
typedef PVOID OPLOCK
Definition at line 1452 of file fsrtl.h.
typedef BASE_MCB* PBASE_MCB
Definition at line 1128 of file fsrtl.h.
typedef BOOLEAN(* PCHECK_FOR_TRAVERSE_ACCESS) (__in PVOID NotifyContext, __in_opt PVOID TargetContext, __in PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 1543 of file fsrtl.h.
typedef NTSTATUS(* PCOMPLETE_LOCK_IRP_ROUTINE) (__in PVOID Context, __in PIRP Irp)
Definition at line 568 of file fsrtl.h.
typedef EOF_WAIT_BLOCK* PEOF_WAIT_BLOCK
Definition at line 244 of file fsrtl.h.
typedef FILE_LOCK* PFILE_LOCK
Definition at line 621 of file fsrtl.h.
typedef FILE_LOCK_INFO* PFILE_LOCK_INFO
Definition at line 556 of file fsrtl.h.
typedef BOOLEAN(* PFILTER_REPORT_CHANGE) (__in PVOID NotifyContext, __in PVOID FilterContext)
Definition at line 1550 of file fsrtl.h.
typedef FSRTL_ADVANCED_FCB_HEADER* PFSRTL_ADVANCED_FCB_HEADER
Definition at line 152 of file fsrtl.h.
typedef FSRTL_AUXILIARY_BUFFER* PFSRTL_AUXILIARY_BUFFER
Definition at line 389 of file fsrtl.h.
typedef FSRTL_COMMON_FCB_HEADER* PFSRTL_COMMON_FCB_HEADER
Definition at line 105 of file fsrtl.h.
typedef struct _FSRTL_PER_FILEOBJECT_CONTEXT * PFSRTL_PER_FILEOBJECT_CONTEXT
typedef struct _FSRTL_PER_STREAM_CONTEXT * PFSRTL_PER_STREAM_CONTEXT
typedef VOID(* PFSRTL_STACK_OVERFLOW_ROUTINE) (__in PVOID Context, __in PKEVENT Event)
Definition at line 1716 of file fsrtl.h.
typedef LARGE_MCB* PLARGE_MCB
Definition at line 1134 of file fsrtl.h.
typedef LBN* PLBN
Definition at line 28 of file fsrtl.h.
typedef MCB* PMCB
Definition at line 1348 of file fsrtl.h.
typedef PVOID PNOTIFY_SYNC
Definition at line 1540 of file fsrtl.h.
typedef PVOID * POPLOCK
Definition at line 1452 of file fsrtl.h.
typedef VOID(* POPLOCK_FS_PREPOST_IRP) (__in PVOID Context, __in PIRP Irp)
Definition at line 1463 of file fsrtl.h.
typedef VOID(* POPLOCK_WAIT_COMPLETE_ROUTINE) (__in PVOID Context, __in PIRP Irp)
Definition at line 1456 of file fsrtl.h.
typedef struct TUNNEL * PTUNNEL
typedef VOID(* PUNLOCK_ROUTINE) (__in PVOID Context, __in PFILE_LOCK_INFO FileLockInfo)
Definition at line 573 of file fsrtl.h.
typedef VBN* PVBN
Definition at line 31 of file fsrtl.h.
typedef ULONG VBN
Definition at line 30 of file fsrtl.h.
Enumeration Type Documentation
enum _FAST_IO_POSSIBLE
Enumerator
FastIoIsNotPossible
FastIoIsPossible
FastIoIsQuestionable
Definition at line 55 of file fsrtl.h.
enum _FSRTL_COMPARISON_RESULT
Enumerator
LessThan
EqualTo
GreaterThan
Definition at line 887 of file fsrtl.h.
Function Documentation
NTKERNELAPI VOID FsRtlAcquireFileExclusive (__in PFILE_OBJECT FileObject)
Definition at line 3419 of file fastio.c.
References ASSERT, FsRtlAcquireFileExclusiveCommon(), NT_SUCCESS, PAGED_CODE, Status, and SyncTypeOther.
Referenced by CcSetPrivateWriteFile(), CcWriteBehind(), and CcZeroEndOfLastPage().
NTKERNELAPI NTSTATUS FsRtlAcquireFileExclusiveCommon (IN PFILE_OBJECT FileObject, IN FS_FILTER_SECTION_SYNC_TYPE SyncType, IN ULONG SectionPageProtection)
Definition at line 3521 of file fastio.c.
References _FAST_IO_DISPATCH::AcquireFileForNtCreateSection, _FS_FILTER_PARAMETERS::AcquireForSectionSynchronization, ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExAcquireResourceExclusiveLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlEnterFileSystem, FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FS_FILTER_PARAMETERS::PageProtection, _FS_FILTER_CALLBACK_DATA::Parameters, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, _FS_FILTER_PARAMETERS::SyncType, SyncTypeCreateSection, SyncTypeOther, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by FsRtlAcquireFileExclusive(), and FsRtlAcquireToCreateMappedSection().
NTKERNELAPI VOID FsRtlAcquireFileForCcFlush (IN PFILE_OBJECT FileObject)
Definition at line 2889 of file fastio.c.
References ASSERT, FsRtlAcquireFileForCcFlushEx(), NT_SUCCESS, PAGED_CODE, and Status.
NTKERNELAPI NTSTATUS FsRtlAcquireFileForCcFlushEx (IN PFILE_OBJECT FileObject)
Definition at line 2932 of file fastio.c.
References _FAST_IO_DISPATCH::AcquireForCcFlush, ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExIsResourceAcquiredSharedLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlEnterFileSystem, FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by FsRtlAcquireFileForCcFlush(), MiRemoveUnusedSegments(), MiShutdownSystem(), MmFlushSection(), and MmFlushVirtualMemory().
NTKERNELAPI BOOLEAN FsRtlAcquireFileForModWrite (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE * ResourceToRelease)
Definition at line 2173 of file fastio.c.
References FALSE, FsRtlAcquireFileForModWriteEx(), NT_SUCCESS, Status, and TRUE.
NTKERNELAPI NTSTATUS FsRtlAcquireFileForModWriteEx (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE * ResourceToRelease)
Definition at line 2235 of file fastio.c.
References _FS_FILTER_PARAMETERS::AcquireForModifiedPageWriter, _FAST_IO_DISPATCH::AcquireForModWrite, ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, _FS_FILTER_PARAMETERS::EndingOffset, ExAcquireResourceExclusiveLite(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, _FSRTL_COMMON_FCB_HEADER::FileSize, FlagOn, _FSRTL_COMMON_FCB_HEADER::Flags, _FS_FILTER_CTRL::Flags, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FSRTL_FLAG_ACQUIRE_MAIN_RSRC_EX, FSRTL_FLAG_ACQUIRE_MAIN_RSRC_SH, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), _FSRTL_COMMON_FCB_HEADER::PagingIoResource, _FS_FILTER_CALLBACK_DATA::Parameters, _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, _FS_FILTER_PARAMETERS::ResourceToRelease, Status, STATUS_CANT_WAIT, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, VALID_FS_FILTER_CALLBACK_HANDLER, and _FSRTL_COMMON_FCB_HEADER::ValidDataLength.
Referenced by FsRtlAcquireFileForModWrite(), and MiMappedPageWriter().
NTKERNELAPI NTSTATUS FsRtlAcquireToCreateMappedSection (IN PFILE_OBJECT FileObject, IN ULONG SectionPageProtection)
Definition at line 3470 of file fastio.c.
References FsRtlAcquireFileExclusiveCommon(), PAGED_CODE, and SyncTypeCreateSection.
Referenced by FsRtlCreateSectionForDataScan(), and MmCreateSection().
NTKERNELAPI BOOLEAN FsRtlAddBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Lbn, __in LONGLONG SectorCount)
Definition at line 1045 of file largemcb.c.
References ASSERT, ASSERTMSG, Dbg, DebugTrace, EndingLbn, EndingVbn, FALSE, FsRtlAddLargeEntry(), FsRtlFindLargeIndex(), FsRtlRemoveLargeEntry(), Index, _NONOPAQUE_BASE_MCB::Mapping, NextStartingLbn, NextStartingVbn, NOTHING, PreviousEndingLbn, PreviousEndingVbn, StartingLbn, StartingVbn, TRUE, try_return, and UNUSED_LBN.
Referenced by FsRtlAddLargeMcbEntry().
NTKERNELAPI BOOLEAN FsRtlAddLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Lbn, __in LONGLONG SectorCount)
Definition at line 1583 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlAddBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlAddMcbEntry().
NTKERNELAPI BOOLEAN FsRtlAddMcbEntry (__in PMCB Mcb, __in VBN Vbn, __in LBN Lbn, __in ULONG SectorCount)
Definition at line 346 of file largemcb.c.
References FsRtlAddLargeMcbEntry(), and PAGED_CODE.
NTKERNELAPI VOID FsRtlAddToTunnelCache (__in TUNNEL * Cache, __in ULONGLONG DirectoryKey, __in UNICODE_STRING * ShortName, __in UNICODE_STRING * LongName, __in BOOLEAN KeyByShortName, __in ULONG DataLength, __in_bcount(DataLength) VOID * Data)
Definition at line 557 of file tunnel.c.
References _UNICODE_STRING::Buffer, TUNNEL_NODE::CacheLinks, CONTAINING_RECORD, TUNNEL_NODE::CreateTime, TUNNEL_NODE::DirKey, ExAcquireFastMutex(), ExAllocateFromPagedLookasideList(), ExAllocatePoolWithTag, ExReleaseFastMutex(), FALSE, TUNNEL_NODE::Flags, FsRtlCompareNodeAndKey(), FsRtlEmptyFreePoolList(), FsRtlFreeTunnelNode(), FsRtlPruneTunnelCache(), InitializeListHead(), InsertTailList(), KeQuerySystemTime(), _UNICODE_STRING::Length, TUNNEL_NODE::ListLinks, TUNNEL_NODE::LongName, LOOKASIDE_NODE_SIZE, _UNICODE_STRING::MaximumLength, NULL, PAGED_CODE, PagedPool, _RTL_SPLAY_LINKS::Parent, POOL_COLD_ALLOCATION, RemoveEntryList(), RtlCopyMemory, RtlInitializeSplayLinks, RtlIsLeftChild, RtlIsRoot, RtlLeftChild, RtlParent, RtlRightChild, SetFlag, TUNNEL_NODE::ShortName, TRUE, TUNNEL_FLAG_KEY_SHORT, TUNNEL_FLAG_NON_LOOKASIDE, TUNNEL_NODE::TunnelData, TUNNEL_NODE::TunnelDataLength, TunnelLookasideList, and TunnelMaxEntries.
NTKERNELAPI PFILE_LOCK FsRtlAllocateFileLock (__in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
Definition at line 1147 of file filelock.c.
References ExAllocateFromPagedLookasideList(), FsRtlFileLockLookasideList, FsRtlInitializeFileLock(), and NULL.
NTKERNELAPI PERESOURCE FsRtlAllocateResource ()
Definition at line 306 of file fsrtlpc.c.
References FSRTL_NUMBER_OF_RESOURCES, FsRtlPagingIoResourceSelector, and PAGED_CODE.
NTKERNELAPI BOOLEAN FsRtlAreNamesEqual (__in PCUNICODE_STRING ConstantNameA, __in PCUNICODE_STRING ConstantNameB, __in BOOLEAN IgnoreCase, __in_opt PCWCH UpcaseTable)
Definition at line 271 of file name.c.
References ARGUMENT_PRESENT, ExRaiseStatus(), FALSE, Index, NT_SUCCESS, PAGED_CODE, RtlEqualMemory, RtlFreeUnicodeString(), RtlUpcaseUnicodeString(), Status, and TRUE.
NTKERNELAPI NTSTATUS FsRtlBalanceReads (__in PDEVICE_OBJECT TargetDevice)
Definition at line 29 of file faulttol.c.
References ASSERT, Executive, FALSE, FT_BALANCED_READ_MODE, IoBuildDeviceIoControlRequest(), IoCallDriver(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NULL, PIRP, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and STATUS_SUCCESS.
NTKERNELAPI BOOLEAN FsRtlCheckLockForReadAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
Definition at line 1320 of file filelock.c.
References Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, _IO_STACK_LOCATION::FileObject, FsRtlFastCheckLockForRead(), IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, _LARGE_INTEGER::LowPart, NULL, _IO_STACK_LOCATION::Parameters, _LARGE_INTEGER::QuadPart, and TRUE.
NTKERNELAPI BOOLEAN FsRtlCheckLockForWriteAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
Definition at line 1421 of file filelock.c.
References Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, _IO_STACK_LOCATION::FileObject, FsRtlFastCheckLockForWrite(), IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, _LARGE_INTEGER::LowPart, NULL, _IO_STACK_LOCATION::Parameters, _LARGE_INTEGER::QuadPart, _LOCK_QUEUE::SharedLockTree, and TRUE.
NTKERNELAPI NTSTATUS FsRtlCheckOplock (__in POPLOCK Oplock, __in PIRP Irp, __in_opt PVOID Context, __in_opt POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine, __in_opt POPLOCK_FS_PREPOST_IRP PostIrpRoutine)
Definition at line 820 of file oplock.c.
References BATCH_OPLOCK, Dbg, DebugTrace, FALSE, FILE_OVERWRITE, FILE_OVERWRITE_IF, FILE_READ_ATTRIBUTES, FILE_RESERVE_OPFILTER, FILE_SHARE_READ, FILE_SUPERSEDE, FILE_WRITE_ATTRIBUTES, FileAllocationInformation, FileEndOfFileInformation, FileLinkInformation, _NONOPAQUE_OPLOCK::FileObject, _IO_STACK_LOCATION::FileObject, FileRenameInformation, FileShortNameInformation, FILTER_OPLOCK, FILTER_OPLOCK_VALID_FLAGS, FlagOn, FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), IoGetCurrentIrpStackLocation, IRP_MJ_CLEANUP, IRP_MJ_CREATE, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MJ_FLUSH_BUFFERS, IRP_MJ_LOCK_CONTROL, IRP_MJ_READ, IRP_MJ_SET_INFORMATION, IRP_MJ_WRITE, IRP_PAGING_IO, _IO_STACK_LOCATION::MajorFunction, NoOplocksHeld, NULL, OplockIIGranted, _NONOPAQUE_OPLOCK::OplockState, _IO_STACK_LOCATION::Parameters, Status, STATUS_SUCCESS, SYNCHRONIZE, and TRUE.
NTKERNELAPI BOOLEAN FsRtlCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 78 of file fastio.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, CcCopyRead(), CcFastCopyRead(), CcFastReadNotPossible, CcFastReadNoWait, CcFastReadResourceMiss, CcFastReadWait, ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, _FSRTL_COMMON_FCB_HEADER::FileSize, FO_FILE_FAST_IO_READ, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), _LARGE_INTEGER::HighPart, HOT_STATISTIC, IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, KeIsExecutingDpc(), _LARGE_INTEGER::LowPart, NULL, PAGED_CODE, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_END_OF_FILE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, and VOID.
NTKERNELAPI BOOLEAN FsRtlCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __in_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 356 of file fastio.c.
References _FSRTL_COMMON_FCB_HEADER::AllocationSize, ASSERT, CcCanIWrite(), CcCopyWrite(), CcCopyWriteWontFlush, CcFastCopyWrite(), CcGetFileSizePointer, CcZeroData(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, FILE_WRITE_TO_END_OF_FILE, FileOffset, _FSRTL_COMMON_FCB_HEADER::FileSize, FlagOn, FO_FILE_MODIFIED, FO_FILE_SIZE_CHANGED, FO_WRITE_THROUGH, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), _LARGE_INTEGER::HighPart, IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, KeIsExecutingDpc(), _LARGE_INTEGER::LowPart, NULL, PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, _FSRTL_COMMON_FCB_HEADER::ValidDataLength, and VOID.
NTKERNELAPI NTSTATUS FsRtlCreateSectionForDataScan (OUT PHANDLE SectionHandle, OUT PVOID * SectionObject, OUT PLARGE_INTEGER SectionFileSize OPTIONAL, IN PFILE_OBJECT FileObject, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN PLARGE_INTEGER MaximumSize OPTIONAL, IN ULONG SectionPageProtection, IN ULONG AllocationAttributes, IN ULONG Flags)
Definition at line 998 of file fsfilter.c.
References ARGUMENT_PRESENT, ASSERT, CcZeroEndOfLastPage(), DISPATCH_LEVEL, FALSE, FlagOn, FSRTL_FSP_TOP_LEVEL_IRP, FsRtlAcquireToCreateMappedSection(), FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlGetFileSize(), FsRtlReleaseFile(), Handle, IoGetTopLevelIrp(), IoSetTopLevelIrp(), KeDelayExecutionThread(), KeGetCurrentIrql(), KernelMode, MmCreateSection(), NT_SUCCESS, NULL, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, PAGE_READONLY, PAGE_READWRITE, PIRP, _LARGE_INTEGER::QuadPart, SEC_COMMIT, SEC_FILE, Status, STATUS_END_OF_FILE, STATUS_FILE_LOCK_CONFLICT, STATUS_INVALID_PARAMETER_8, STATUS_INVALID_PARAMETER_9, and UNREFERENCED_PARAMETER.
NTKERNELAPI BOOLEAN FsRtlCurrentBatchOplock (__in POPLOCK Oplock)
Definition at line 1167 of file oplock.c.
References BATCH_OPLOCK, Dbg, DebugTrace, FALSE, FILTER_OPLOCK, FlagOn, NULL, PAGED_CODE, and TRUE.
NTKERNELAPI VOID FsRtlDeleteKeyFromTunnelCache (__in TUNNEL * Cache, __in ULONGLONG DirectoryKey)
Definition at line 1039 of file tunnel.c.
References TUNNEL_NODE::CacheLinks, CONTAINING_RECORD, TUNNEL_NODE::DirKey, ExAcquireFastMutex(), ExReleaseFastMutex(), FsRtlEmptyFreePoolList(), FsRtlRemoveNodeFromTunnel(), InitializeListHead(), NULL, PAGED_CODE, RtlLeftChild, RtlRealSuccessor(), RtlRightChild, TRUE, and TunnelMaxEntries.
NTKERNELAPI VOID FsRtlDeleteTunnelCache (__in TUNNEL * Cache)
Definition at line 1168 of file tunnel.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, FsRtlFreeTunnelNode(), InitializeListHead(), NULL, PAGED_CODE, and TunnelMaxEntries.
NTKERNELAPI VOID FsRtlDeregisterUncProvider (__in HANDLE Handle)
Definition at line 417 of file unc.c.
References ASSERT, Executive, ExFreePool(), FALSE, FsRtlpDRD, FsRtlpRedirs, FsRtlpSetSymbolicLink(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, PAGED_CODE, and ZwClose().
NTKERNELAPI VOID FsRtlDissectDbcs (__in ANSI_STRING Path, __out PANSI_STRING FirstName, __out PANSI_STRING RemainingName)
Definition at line 523 of file dbcsname.c.
References FsRtlIsLeadDbcsCharacter, NULL, and PAGED_CODE.
Referenced by FsRtlIsFatDbcsLegal(), and FsRtlIsHpfsDbcsLegal().
NTKERNELAPI VOID FsRtlDissectName (__in UNICODE_STRING Path, __out PUNICODE_STRING FirstName, __out PUNICODE_STRING RemainingName)
Definition at line 76 of file name.c.
References NOTHING, NULL, and PAGED_CODE.
NTKERNELAPI BOOLEAN FsRtlDoesDbcsContainWildCards (__in PANSI_STRING Name)
Definition at line 675 of file dbcsname.c.
References FALSE, FsRtlIsAnsiCharacterWild, FsRtlIsLeadDbcsCharacter, PAGED_CODE, and TRUE.
Referenced by FsRtlIsDbcsInExpression(), and FsRtlIsFatDbcsLegal().
NTKERNELAPI BOOLEAN FsRtlDoesNameContainWildCards (__in PUNICODE_STRING Name)
Definition at line 212 of file name.c.
References FALSE, FsRtlIsUnicodeCharacterWild, PAGED_CODE, and TRUE.
Referenced by FsRtlIsNameInExpressionPrivate().
NTKERNELAPI BOOLEAN FsRtlFastCheckLockForRead (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PFILE_OBJECT FileObject, __in PVOID ProcessId)
Definition at line 2587 of file filelock.c.
References Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _LOCK_QUEUE::ExclusiveLockTree, FsRtlAcquireLockQueue, FsRtlCheckNoExclusiveConflict(), FsRtlReleaseLockQueue, _FILE_LOCK_INFO::Key, _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, _FILE_LOCK_INFO::StartingByte, Status, and TRUE.
Referenced by FsRtlCheckLockForReadAccess().
NTKERNELAPI BOOLEAN FsRtlFastCheckLockForWrite (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PVOID FileObject, __in PVOID ProcessId)
Definition at line 2723 of file filelock.c.
References Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, _LOCK_QUEUE::ExclusiveLockTree, FsRtlAcquireLockQueue, FsRtlCheckNoExclusiveConflict(), FsRtlCheckNoSharedConflict(), FsRtlReleaseLockQueue, _FILE_LOCK_INFO::Key, _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, _LOCK_QUEUE::SharedLockTree, _FILE_LOCK_INFO::StartingByte, Status, and TRUE.
Referenced by FsRtlCheckLockForWriteAccess().
NTKERNELAPI NTSTATUS FsRtlFastUnlockAll (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in_opt PVOID Context)
Definition at line 3778 of file filelock.c.
References FALSE, and FsRtlPrivateFastUnlockAll().
Referenced by FsRtlProcessFileLock().
NTKERNELAPI NTSTATUS FsRtlFastUnlockAllByKey (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context)
Definition at line 3822 of file filelock.c.
References FsRtlPrivateFastUnlockAll(), and TRUE.
Referenced by FsRtlProcessFileLock().
NTKERNELAPI NTSTATUS FsRtlFastUnlockSingle (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in LARGE_INTEGER UNALIGNED * FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
Definition at line 3248 of file filelock.c.
References FALSE, FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), NULL, Status, STATUS_RANGE_NOT_LOCKED, STATUS_SUCCESS, TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlProcessFileLock().
NTKERNELAPI BOOLEAN FsRtlFindInTunnelCache (__in TUNNEL * Cache, __in ULONGLONG DirectoryKey, __in UNICODE_STRING * Name, __out UNICODE_STRING * ShortName, __out UNICODE_STRING * LongName, __inout ULONG * DataLength, __out_bcount_part *,*DataLength VOID * Data)
Definition at line 877 of file tunnel.c.
References ASSERT, _UNICODE_STRING::Buffer, TUNNEL_NODE::CacheLinks, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, FsRtlAllocatePoolWithTag, FsRtlCompareNodeAndKey(), FsRtlEmptyFreePoolList(), FsRtlPruneTunnelCache(), InitializeListHead(), _UNICODE_STRING::Length, TUNNEL_NODE::LongName, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlCopyUnicodeString(), RtlLeftChild, RtlRightChild, TUNNEL_NODE::ShortName, Status, TRUE, TUNNEL_NODE::TunnelData, TUNNEL_NODE::TunnelDataLength, and TunnelMaxEntries.
NTKERNELAPI VOID FsRtlFreeFileLock (__in PFILE_LOCK FileLock)
Definition at line 1167 of file filelock.c.
References ExFreeToPagedLookasideList(), FsRtlFileLockLookasideList, and FsRtlUninitializeFileLock().
NTSTATUS FsRtlGetFileSize (__in PFILE_OBJECT FileObject, __inout PLARGE_INTEGER FileSize)
Definition at line 4038 of file fastio.c.
References _IO_STACK_LOCATION::DeviceObject, _FILE_STANDARD_INFORMATION::Directory, _FILE_STANDARD_INFORMATION::EndOfFile, Executive, FALSE, _FAST_IO_DISPATCH::FastIoQueryStandardInfo, _IO_STACK_LOCATION::FileObject, FileStandardInformation, HardErrorState, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoSetThreadHardErrorMode(), IRP_MJ_QUERY_INFORMATION, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), Status, _IO_STATUS_BLOCK::Status, STATUS_FILE_IS_A_DIRECTORY, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and TRUE.
Referenced by FsRtlCreateSectionForDataScan(), MiCreateDataFileMap(), MiCreateImageFileMap(), MmCreateSection(), and MmExtendSection().
NTKERNELAPI BOOLEAN FsRtlGetNextBaseMcbEntry (__in PBASE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG Vbn, __out PLONGLONG Lbn, __out PLONGLONG SectorCount)
Definition at line 2680 of file largemcb.c.
References Dbg, DebugTrace, FALSE, SectorsWithinRun, StartingLbn, StartingVbn, TRUE, and UNUSED_LBN.
Referenced by FsRtlGetNextLargeMcbEntry().
NTKERNELAPI PFILE_LOCK_INFO FsRtlGetNextFileLock (__in PFILE_LOCK FileLock, __in BOOLEAN Restart)
Definition at line 1956 of file filelock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, _LOCK_QUEUE::ExclusiveLockTree, FALSE, _FILE_LOCK_INFO::FileObject, FsRtlAcquireLockQueue, FsRtlFindFirstOverlappingExclusiveNode(), FsRtlFindFirstOverlappingSharedNode(), FsRtlReleaseLockQueue, GreaterThan, _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _SH_LOCK::LockInfo, _EX_LOCK::LockInfo, _LOCK_INFO::LockQueue, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlLeftChild, RtlRealSuccessor(), _LOCK_QUEUE::SharedLockTree, _FILE_LOCK_INFO::StartingByte, and TRUE.
NTKERNELAPI BOOLEAN FsRtlGetNextLargeMcbEntry (__in PLARGE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG Vbn, __out PLONGLONG Lbn, __out PLONGLONG SectorCount)
Definition at line 2757 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlGetNextBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlGetNextMcbEntry().
NTKERNELAPI BOOLEAN FsRtlGetNextMcbEntry (__in PMCB Mcb, __in ULONG RunIndex, __out PVBN Vbn, __out PLBN Lbn, __out PULONG SectorCount)
Definition at line 448 of file largemcb.c.
References FsRtlGetNextLargeMcbEntry(), and PAGED_CODE.
NTKERNELAPI VOID FsRtlIncrementCcFastReadNotPossible (VOID)
Definition at line 4375 of file fastio.c.
References CcFastReadNotPossible, and HOT_STATISTIC.
NTKERNELAPI VOID FsRtlIncrementCcFastReadNoWait (VOID)
Definition at line 4416 of file fastio.c.
References CcFastReadNoWait, and HOT_STATISTIC.
NTKERNELAPI VOID FsRtlIncrementCcFastReadResourceMiss (VOID)
Definition at line 4437 of file fastio.c.
References CcFastReadResourceMiss.
NTKERNELAPI VOID FsRtlIncrementCcFastReadWait (VOID)
Definition at line 4395 of file fastio.c.
References CcFastReadWait, and HOT_STATISTIC.
NTKERNELAPI VOID FsRtlInitializeBaseMcb (__in PBASE_MCB Mcb, __in POOL_TYPE PoolType)
Definition at line 532 of file largemcb.c.
References Dbg, DebugTrace, FsRtlAllocateFirstMapping, FsRtlpAllocatePool, INITIAL_MAXIMUM_PAIR_COUNT, and PagedPool.
Referenced by FsRtlInitializeLargeMcb().
NTKERNELAPI VOID FsRtlInitializeFileLock (__in PFILE_LOCK FileLock, __in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
Definition at line 799 of file filelock.c.
References Dbg, DebugTrace, FALSE, and NULL.
Referenced by FsRtlAllocateFileLock().
NTKERNELAPI VOID FsRtlInitializeLargeMcb (__in PLARGE_MCB Mcb, __in POOL_TYPE PoolType)
Definition at line 594 of file largemcb.c.
References Dbg, DebugTrace, FsRtlAllocateFastMutex, FsRtlFreeFastMutex, FsRtlInitializeBaseMcb(), KeInitializeGuardedMutex(), and NULL.
Referenced by FsRtlInitializeMcb().
NTKERNELAPI VOID FsRtlInitializeMcb (__in PMCB Mcb, __in POOL_TYPE PoolType)
Definition at line 305 of file largemcb.c.
References FsRtlInitializeLargeMcb(), and PAGED_CODE.
NTKERNELAPI VOID FsRtlInitializeOplock (__inout POPLOCK Oplock)
Definition at line 370 of file oplock.c.
References Dbg, DebugTrace, PAGED_CODE, and UNREFERENCED_PARAMETER.
NTKERNELAPI VOID FsRtlInitializeTunnelCache (__in TUNNEL * Cache)
Definition at line 490 of file tunnel.c.
References ExInitializeFastMutex, InitializeListHead(), NULL, and PAGED_CODE.
NTKERNELAPI BOOLEAN FsRtlInitSystem ()
Definition at line 219 of file fsrtlpc.c.
References _UNICODE_STRING::Buffer, COMPATIBILITY_MODE_VALUE_NAME, ExInitializeResourceLite(), FALSE, FsFilterInit(), FSRTL_NUMBER_OF_RESOURCES, FsRtlAllocatePool, FsRtlGetCompatibilityModeValue(), FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcbs(), FsRtlInitializeTunnels(), FsRtlInitializeWorkerThread(), FsRtlpUncSemaphore, FsRtlSafeExtensions, KeInitializeSemaphore(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MAXLONG, NonPagedPool, NT_SUCCESS, PAGED_CODE, and TRUE.
Referenced by Phase1InitializationDiscard().
NTKERNELAPI NTSTATUS FsRtlInsertPerFileObjectContext (__in PFILE_OBJECT FileObject, __in PFSRTL_PER_FILEOBJECT_CONTEXT Ptr)
Definition at line 404 of file filtrctx.c.
References ASSERT, ExAcquireFastMutex(), ExAllocatePoolWithTag, ExFreePool(), ExInitializeFastMutex, ExReleaseFastMutex(), _PER_FILEOBJECT_CTXCTRL::FastMutex, _PER_FILEOBJECT_CTXCTRL::FilterContexts, FsRtlSupportsPerFileObjectContexts, InitializeListHead(), InsertHeadList(), IoChangeFileObjectFilterContext(), IoGetFileObjectFilterContext(), NonPagedPool, NT_SUCCESS, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
NTKERNELAPI NTSTATUS FsRtlInsertPerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER PerStreamContext, __in PFSRTL_PER_STREAM_CONTEXT Ptr)
Definition at line 73 of file filtrctx.c.
References ExAcquireFastMutex(), ExReleaseFastMutex(), FlagOn, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS, InsertHeadList(), STATUS_INVALID_DEVICE_REQUEST, and STATUS_SUCCESS.
NTKERNELAPI BOOLEAN FsRtlIsDbcsInExpression (__in PANSI_STRING Expression, __in PANSI_STRING Name)
Definition at line 752 of file dbcsname.c.
References ANSI_DOS_QM, ANSI_DOS_STAR, ASSERT, _STRING::Buffer, Dbg, DebugTrace, DOS_DOT, ExFreePool(), FALSE, FsRtlDoesDbcsContainWildCards(), FsRtlIsLeadDbcsCharacter, FsRtlpAllocatePool, GetDbcs, _STRING::Length, MATCHES_ARRAY_SIZE, NlsMbOemCodePageTag, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlEqualMemory, and TRUE.
NTKERNELAPI BOOLEAN FsRtlIsFatDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
Definition at line 64 of file dbcsname.c.
References ANSI_DOS_DOT, ASSERT, _STRING::Buffer, FALSE, FsRtlDissectDbcs(), FsRtlDoesDbcsContainWildCards(), FsRtlIsAnsiCharacterLegalFat, FsRtlIsFatDbcsLegal(), FsRtlIsLeadDbcsCharacter, Index, _STRING::Length, PAGED_CODE, and TRUE.
Referenced by FsRtlIsFatDbcsLegal().
NTKERNELAPI BOOLEAN FsRtlIsHpfsDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
Definition at line 328 of file dbcsname.c.
References ANSI_DOS_DOT, _STRING::Buffer, FALSE, FsRtlDissectDbcs(), FsRtlIsAnsiCharacterLegalHpfs, FsRtlIsHpfsDbcsLegal(), FsRtlIsLeadDbcsCharacter, Index, _STRING::Length, PAGED_CODE, and TRUE.
Referenced by FsRtlIsHpfsDbcsLegal().
NTKERNELAPI BOOLEAN FsRtlIsNameInExpression (__in PUNICODE_STRING Expression, __in PUNICODE_STRING Name, __in BOOLEAN IgnoreCase, __in_opt PWCH UpcaseTable)
Definition at line 398 of file name.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, ExRaiseStatus(), FALSE, FsRtlIsNameInExpressionPrivate(), NT_SUCCESS, NULL, RtlFreeUnicodeString(), RtlUpcaseUnicodeString(), Status, and TRUE.
NTKERNELAPI BOOLEAN FsRtlIsNtstatusExpected (__in NTSTATUS Exception)
Definition at line 80 of file filter.c.
References FALSE, STATUS_ACCESS_VIOLATION, STATUS_DATATYPE_MISALIGNMENT, STATUS_ILLEGAL_INSTRUCTION, STATUS_INSTRUCTION_MISALIGNMENT, and TRUE.
Referenced by CcExceptionFilter(), FsRtlCancelNotify(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), FsRtlNormalizeNtstatus(), FsRtlNotifyFilterReportChange(), FsRtlPrepareMdlWriteDev(), and RawDispatch().
NTKERNELAPI LOGICAL FsRtlIsPagingFile (__in PFILE_OBJECT FileObject)
Definition at line 776 of file filtrctx.c.
References MmIsFileObjectAPagingFile().
NTKERNELAPI BOOLEAN FsRtlIsTotalDeviceFailure (__in NTSTATUS Status)
Definition at line 306 of file filter.c.
References FALSE, NT_SUCCESS, STATUS_CRC_ERROR, STATUS_DEVICE_DATA_ERROR, and TRUE.
Referenced by IopMountVolume().
NTKERNELAPI BOOLEAN FsRtlLookupBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __out_opt PLONGLONG Lbn, __out_opt PLONGLONG SectorCountFromLbn, __out_opt PLONGLONG StartingLbn, __out_opt PLONGLONG SectorCountFromStartingLbn, __out_opt PULONG Index)
Definition at line 2169 of file largemcb.c.
References ARGUMENT_PRESENT, ASSERTMSG, Dbg, DebugTrace, EndingVbn, FALSE, FsRtlFindLargeIndex(), NOTHING, StartingLbn, StartingVbn, TRUE, try_return, and UNUSED_LBN.
Referenced by FsRtlLookupLargeMcbEntry().
NTKERNELAPI BOOLEAN FsRtlLookupLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __out_opt PLONGLONG Lbn, __out_opt PLONGLONG SectorCountFromLbn, __out_opt PLONGLONG StartingLbn, __out_opt PLONGLONG SectorCountFromStartingLbn, __out_opt PULONG Index)
Definition at line 2304 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlLookupBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlLookupMcbEntry().
NTKERNELAPI BOOLEAN FsRtlLookupLastBaseMcbEntry (__in PBASE_MCB Mcb, __out PLONGLONG Vbn, __out PLONGLONG Lbn)
Definition at line 2369 of file largemcb.c.
References Dbg, DebugTrace, EndingLbn, EndingVbn, FALSE, _NONOPAQUE_BASE_MCB::PairCount, and TRUE.
Referenced by FsRtlLookupLastLargeMcbEntry().
NTKERNELAPI BOOLEAN FsRtlLookupLastBaseMcbEntryAndIndex (__in PBASE_MCB OpaqueMcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
Definition at line 2483 of file largemcb.c.
References Dbg, DebugTrace, EndingLbn, EndingVbn, FALSE, PAGED_CODE, _NONOPAQUE_BASE_MCB::PairCount, TRUE, and UNUSED_LBN.
Referenced by FsRtlLookupLastLargeMcbEntryAndIndex().
NTKERNELAPI BOOLEAN FsRtlLookupLastLargeMcbEntry (__in PLARGE_MCB Mcb, __out PLONGLONG Vbn, __out PLONGLONG Lbn)
Definition at line 2430 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlLookupLastBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlLookupLastMcbEntry().
NTKERNELAPI BOOLEAN FsRtlLookupLastLargeMcbEntryAndIndex (__in PLARGE_MCB OpaqueMcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
Definition at line 2551 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlLookupLastBaseMcbEntryAndIndex(), KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), and PAGED_CODE.
NTKERNELAPI BOOLEAN FsRtlLookupLastMcbEntry (__in PMCB Mcb, __out PVBN Vbn, __out PLBN Lbn)
Definition at line 411 of file largemcb.c.
References FsRtlLookupLastLargeMcbEntry(), and PAGED_CODE.
NTKERNELAPI BOOLEAN FsRtlLookupMcbEntry (__in PMCB Mcb, __in VBN Vbn, __out PLBN Lbn, __out_opt PULONG SectorCount, __out PULONG Index)
Definition at line 379 of file largemcb.c.
References ARGUMENT_PRESENT, FsRtlLookupLargeMcbEntry(), and NULL.
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlLookupPerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 517 of file filtrctx.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), _PER_FILEOBJECT_CTXCTRL::FastMutex, _PER_FILEOBJECT_CTXCTRL::FilterContexts, _LIST_ENTRY::Flink, _FSRTL_PER_FILEOBJECT_CONTEXT::InstanceId, IoGetFileObjectFilterContext(), IsListEmpty, MySearchList, NULL, and _FSRTL_PER_FILEOBJECT_CONTEXT::OwnerId.
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlLookupPerStreamContextInternal (__in PFSRTL_ADVANCED_FCB_HEADER StreamContext, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 119 of file filtrctx.c.
References ARGUMENT_PRESENT, ASSERT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FlagOn, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS, _FSRTL_PER_STREAM_CONTEXT::InstanceId, IsListEmpty, MySearchList, NULL, and _FSRTL_PER_STREAM_CONTEXT::OwnerId.
NTSTATUS FsRtlMappedFile (IN PFILE_OBJECT FileObject, IN ULONG DesiredAccess, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length)
NTKERNELAPI BOOLEAN FsRtlMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 1305 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlMdlReadDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlRead, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
NTKERNELAPI BOOLEAN FsRtlMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
Definition at line 1395 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlMdlReadCompleteDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlReadComplete, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
NTKERNELAPI BOOLEAN FsRtlMdlReadCompleteDev (__in PFILE_OBJECT FileObject, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
Definition at line 1466 of file fastio.c.
References CcMdlReadComplete2(), TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlMdlReadComplete().
NTKERNELAPI BOOLEAN FsRtlMdlReadDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 1092 of file fastio.c.
References ASSERT, CcFastMdlReadNotPossible, CcFastMdlReadWait, CcMdlRead(), ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, _FSRTL_COMMON_FCB_HEADER::FileSize, FO_FILE_FAST_IO_READ, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, KeIsExecutingDpc(), NULL, PAGED_CODE, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_END_OF_FILE, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by FsRtlMdlRead().
BOOLEAN FsRtlMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
Definition at line 1982 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlMdlWriteCompleteDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlWriteComplete, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
NTKERNELAPI BOOLEAN FsRtlMdlWriteCompleteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
Definition at line 2052 of file fastio.c.
References CcMdlWriteComplete2(), FALSE, FlagOn, FO_WRITE_THROUGH, TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlMdlWriteComplete().
NTKERNELAPI NTSTATUS FsRtlNormalizeNtstatus (__in NTSTATUS Exception, __in NTSTATUS GenericException)
Definition at line 47 of file filter.c.
References FsRtlIsNtstatusExpected().
Referenced by CcCopyRead(), CcCopyWrite(), CcFastCopyRead(), CcFastCopyWrite(), CcGetVacbMiss(), CcInitializeCacheMap(), CcMapAndCopy(), CcMdlWriteComplete2(), and CcSetFileSizes().
NTKERNELAPI VOID FsRtlNotifyChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in PLIST_ENTRY NotifyList, __in BOOLEAN WatchTree, __in ULONG CompletionFilter, __in PIRP NotifyIrp)
Definition at line 491 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterChangeDirectory(), NULL, PAGED_CODE, and TRUE.
NTKERNELAPI VOID FsRtlNotifyCleanup (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext)
Definition at line 2045 of file notify.c.
References AcquireNotifySync, _NOTIFY_CHANGE::AllocatedBuffer, Dbg, DebugTrace, ExFreePool(), _NOTIFY_CHANGE::Flags, _LIST_ENTRY::Flink, FsRtlIsNotifyOnList(), FsRtlNotifyCompleteIrpList(), _NOTIFY_CHANGE::FullDirectoryName, InterlockedDecrement, IsListEmpty, NOTIFY_CLEANUP_CALLED, _NOTIFY_CHANGE::NotifyIrps, _NOTIFY_CHANGE::NotifyList, NULL, _NOTIFY_CHANGE::OwningProcess, PAGED_CODE, PsReturnProcessPagedPoolQuota(), _NOTIFY_CHANGE::ReferenceCount, ReleaseNotifySync, RemoveEntryList(), SeReleaseSubjectContext(), SetFlag, STATUS_NOTIFY_CLEANUP, _NOTIFY_CHANGE::SubjectContext, and _NOTIFY_CHANGE::ThisBufferLength.
NTKERNELAPI VOID FsRtlNotifyFilterChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext, __in_opt PFILTER_REPORT_CHANGE FilterCallback)
Definition at line 676 of file notify.c.
References AcquireNotifySync, _NOTIFY_CHANGE::BufferLength, _NOTIFY_CHANGE::CharacterSize, ClearFlag, _NOTIFY_CHANGE::CompletionFilter, _NOTIFY_CHANGE::DataLength, Dbg, DebugTrace, ExFreePool(), FALSE, _IO_STACK_LOCATION::FileObject, _NOTIFY_CHANGE::FilterCallback, FlagOn, _NOTIFY_CHANGE::Flags, _FILE_OBJECT::Flags, FO_CLEANUP_COMPLETE, _NOTIFY_CHANGE::FsContext, _FILE_OBJECT::FsContext, FsRtlCheckNotifyForDelete(), FsRtlCompleteRequest, FsRtlIsNotifyOnList(), FsRtlNotifyCompleteIrp(), FsRtlNotifySetCancelRoutine(), FsRtlpAllocatePool, _NOTIFY_CHANGE::FullDirectoryName, InitializeListHead(), InsertTailList(), InterlockedIncrement, IoGetCurrentIrpStackLocation, IoMarkIrpPending, _NOTIFY_CHANGE::LastEntry, NOTHING, NOTIFY_CLEANUP_CALLED, NOTIFY_DEFER_NOTIFY, NOTIFY_DIR_IS_ROOT, NOTIFY_IMMEDIATE_NOTIFY, NOTIFY_STREAM_IS_DELETED, NOTIFY_WATCH_TREE, _NOTIFY_CHANGE::NotifyIrps, _NOTIFY_CHANGE::NotifyList, _NOTIFY_CHANGE::NotifySync, NULL, _NOTIFY_CHANGE::OwningProcess, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, _NOTIFY_CHANGE::ReferenceCount, ReleaseNotifySync, RtlZeroMemory, SeReleaseSubjectContext(), SetFlag, STATUS_DELETE_PENDING, STATUS_NOTIFY_CLEANUP, STATUS_NOTIFY_ENUM_DIR, STATUS_SUCCESS, _NOTIFY_CHANGE::StreamID, _NOTIFY_CHANGE::SubjectContext, THREAD_TO_PROCESS, _NOTIFY_CHANGE::TraverseCallback, and try_return.
Referenced by FsRtlNotifyChangeDirectory(), and FsRtlNotifyFullChangeDirectory().
NTKERNELAPI VOID FsRtlNotifyFilterReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in_opt PVOID TargetContext, __in_opt PVOID FilterContext)
Definition at line 1205 of file notify.c.
References AcquireNotifySync, Add2Ptr, _NOTIFY_CHANGE::AllocatedBuffer, ARGUMENT_PRESENT, ASSERT, ASSERTMSG, _NOTIFY_CHANGE::Buffer, _STRING::Buffer, _NOTIFY_CHANGE::BufferLength, _NOTIFY_CHANGE::CharacterSize, ClearFlag, _NOTIFY_CHANGE::CompletionFilter, CONTAINING_RECORD, _NOTIFY_CHANGE::DataLength, Dbg, DebugTrace, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FIELD_OFFSET, FILE_ACTION_RENAMED_OLD_NAME, _NOTIFY_CHANGE::FilterCallback, FlagOn, _NOTIFY_CHANGE::Flags, _LIST_ENTRY::Flink, _NOTIFY_CHANGE::FsContext, FsRtlIsNtstatusExpected(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyUpdateBuffer(), FsRtlpAllocatePool, _NOTIFY_CHANGE::FullDirectoryName, IoGetCurrentIrpStackLocation, IRP, IsListEmpty, _NOTIFY_CHANGE::LastEntry, _STRING::Length, LongAlign, _STRING::MaximumLength, MmGetSystemAddressForMdl, _FILE_NOTIFY_INFORMATION::NextEntryOffset, NOTHING, NOTIFY_DEFER_NOTIFY, NOTIFY_DIR_IS_ROOT, NOTIFY_IMMEDIATE_NOTIFY, NOTIFY_WATCH_TREE, _NOTIFY_CHANGE::NotifyIrps, NULL, _NOTIFY_CHANGE::OwningProcess, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, PsChargePoolQuota(), PsReturnProcessPagedPoolQuota(), ReleaseNotifySync, RtlEqualMemory, RtlOemStringToCountedUnicodeSize, SetFlag, STATUS_INSUFFICIENT_RESOURCES, STATUS_QUOTA_EXCEEDED, STATUS_SUCCESS, _NOTIFY_CHANGE::SubjectContext, _NOTIFY_CHANGE::ThisBufferLength, _NOTIFY_CHANGE::TraverseCallback, and TRUE.
Referenced by FsRtlNotifyFullReportChange(), and FsRtlNotifyReportChange().
NTKERNELAPI VOID FsRtlNotifyFullChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 570 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterChangeDirectory(), NULL, and PAGED_CODE.
NTKERNELAPI VOID FsRtlNotifyFullReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in PVOID TargetContext)
Definition at line 1112 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterReportChange(), NULL, and PAGED_CODE.
NTKERNELAPI VOID FsRtlNotifyInitializeSync (__in PNOTIFY_SYNC * NotifySync)
Definition at line 393 of file notify.c.
References Dbg, DebugTrace, ExInitializeFastMutex, _REAL_NOTIFY_SYNC::FastMutex, FsRtlpAllocatePool, NonPagedPool, NULL, _REAL_NOTIFY_SYNC::OwnerCount, _REAL_NOTIFY_SYNC::OwningThread, and PAGED_CODE.
NTKERNELAPI VOID FsRtlNotifyReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in PSTRING TargetName, __in ULONG FilterMatch)
Definition at line 1035 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterReportChange(), NULL, and PAGED_CODE.
NTKERNELAPI VOID FsRtlNotifyUninitializeSync (__in PNOTIFY_SYNC * NotifySync)
Definition at line 448 of file notify.c.
References Dbg, DebugTrace, ExFreePool(), NULL, and PAGED_CODE.
NTKERNELAPI NTSTATUS FsRtlNotifyVolumeEvent (__in PFILE_OBJECT FileObject, __in ULONG EventCode)
Definition at line 39 of file pnp.c.
References ASSERT, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Event, FIELD_OFFSET, _TARGET_DEVICE_CUSTOM_NOTIFICATION::FileObject, FSRTL_VOLUME_DISMOUNT, FSRTL_VOLUME_DISMOUNT_FAILED, FSRTL_VOLUME_LOCK, FSRTL_VOLUME_LOCK_FAILED, FSRTL_VOLUME_MOUNT, FSRTL_VOLUME_UNLOCK, IoGetRelatedTargetDevice(), IoReportTargetDeviceChange(), IoReportTargetDeviceChangeAsynchronous(), _TARGET_DEVICE_CUSTOM_NOTIFICATION::NameBufferOffset, NT_SUCCESS, NULL, ObDereferenceObject(), RtlCopyMemory, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Size, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and _TARGET_DEVICE_CUSTOM_NOTIFICATION::Version.
Referenced by RawMountVolume(), and RawUserFsCtrl().
NTKERNELAPI ULONG FsRtlNumberOfRunsInBaseMcb (__in PBASE_MCB Mcb)
Definition at line 2609 of file largemcb.c.
Referenced by FsRtlNumberOfRunsInLargeMcb().
NTKERNELAPI ULONG FsRtlNumberOfRunsInLargeMcb (__in PLARGE_MCB Mcb)
Definition at line 2640 of file largemcb.c.
References Count, Dbg, DebugTrace, FsRtlNumberOfRunsInBaseMcb(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlNumberOfRunsInMcb().
NTKERNELAPI ULONG FsRtlNumberOfRunsInMcb (__in PMCB Mcb)
Definition at line 437 of file largemcb.c.
References FsRtlNumberOfRunsInLargeMcb(), and PAGED_CODE.
NTKERNELAPI NTSTATUS FsRtlOplockFsctrl (__in POPLOCK Oplock, __in PIRP Irp, __in ULONG OpenCount)
Definition at line 578 of file oplock.c.
References Dbg, DebugTrace, EXCLUSIVE, FALSE, FILE_READ_ATTRIBUTES, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _IO_STACK_LOCATION::FileObject, FlagOn, _FILE_OBJECT::Flags, FO_CLEANUP_COMPLETE, FSCTL_OPBATCH_ACK_CLOSE_PENDING, FSCTL_OPLOCK_BREAK_ACK_NO_2, FSCTL_OPLOCK_BREAK_ACKNOWLEDGE, FSCTL_OPLOCK_BREAK_NOTIFY, FSCTL_REQUEST_BATCH_OPLOCK, FSCTL_REQUEST_FILTER_OPLOCK, FSCTL_REQUEST_OPLOCK_LEVEL_1, FSCTL_REQUEST_OPLOCK_LEVEL_2, FsRtlAcknowledgeOplockBreak(), FsRtlCompleteRequest, FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), IoGetCurrentIrpStackLocation, IoIsOperationSynchronous(), IRP_INPUT_OPERATION, IRP_MJ_CREATE, LEVEL_I_OPLOCK, _IO_STACK_LOCATION::MajorFunction, NULL, OpFilterReqPending, PAGED_CODE, _IO_STACK_LOCATION::Parameters, SetFlag, Status, STATUS_INVALID_PARAMETER, STATUS_OPLOCK_NOT_GRANTED, and TRUE.
NTKERNELAPI BOOLEAN FsRtlOplockIsFastIoPossible (__in POPLOCK Oplock)
Definition at line 1114 of file oplock.c.
References Dbg, DebugTrace, FALSE, FlagOn, LEVEL_II_OPLOCK, NULL, OPLOCK_BREAK_MASK, PAGED_CODE, and TRUE.
NTKERNELAPI VOID FsRtlPostPagingFileStackOverflow (__in PVOID Context, __in PKEVENT Event, __in PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
NTKERNELAPI VOID FsRtlPostStackOverflow (__in PVOID Context, __in PKEVENT Event, __in PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
NTKERNELAPI BOOLEAN FsRtlPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 1892 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlPrepareMdlWriteDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), NULL, _FAST_IO_DISPATCH::PrepareMdlWrite, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
NTKERNELAPI BOOLEAN FsRtlPrepareMdlWriteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 1504 of file fastio.c.
References _FSRTL_COMMON_FCB_HEADER::AllocationSize, ASSERT, CcCanIWrite(), CcGetFileSizePointer, CcPrepareMdlWrite(), CcZeroData(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, FILE_WRITE_TO_END_OF_FILE, FileOffset, _FSRTL_COMMON_FCB_HEADER::FileSize, FlagOn, FO_FILE_MODIFIED, FO_FILE_SIZE_CHANGED, FO_WRITE_THROUGH, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), _LARGE_INTEGER::HighPart, IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, NULL, PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, _FSRTL_COMMON_FCB_HEADER::ValidDataLength, and VOID.
Referenced by FsRtlPrepareMdlWrite().
NTKERNELAPI BOOLEAN FsRtlPrivateLock (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in BOOLEAN FailImmediately, __in BOOLEAN ExclusiveLock, __out PIO_STATUS_BLOCK Iosb, __in_opt PIRP Irp, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
Definition at line 3875 of file filelock.c.
References ARGUMENT_PRESENT, _WAITING_LOCK::CompleteLockIrpRoutine, _LOCK_INFO::CompleteLockIrpRoutine, _WAITING_LOCK::Context, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, ExRaiseStatus(), FALSE, _FILE_LOCK_INFO::FileObject, FileOffset, FsRtlAcquireLockQueue, FsRtlAllocateWaitingLock(), FsRtlCompleteLockIrp, FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckForExclusiveLockAccess(), FsRtlPrivateCheckForSharedLockAccess(), FsRtlPrivateInitializeFileLock(), FsRtlPrivateInsertLock(), FsRtlPrivateRemoveLock(), FsRtlReleaseLockQueue, IoMarkIrpPending, IoSetCancelRoutine, _WAITING_LOCK::Irp, _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _WAITING_LOCK::Link, _LOCK_INFO::LockQueue, _SINGLE_LIST_ENTRY::Next, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, _FILE_LOCK_INFO::StartingByte, STATUS_INSUFFICIENT_RESOURCES, STATUS_LOCK_NOT_GRANTED, STATUS_PENDING, STATUS_SUCCESS, TRUE, try_return, UNREFERENCED_PARAMETER, _LOCK_QUEUE::WaitingLocks, and _LOCK_QUEUE::WaitingLocksTail.
Referenced by FsRtlProcessFileLock().
NTKERNELAPI NTSTATUS FsRtlProcessFileLock (__in PFILE_LOCK FileLock, __in PIRP Irp, __in_opt PVOID Context)
Definition at line 1178 of file filelock.c.
References ASSERT, BooleanFlagOn, Dbg, DebugTrace, FALSE, _IO_STACK_LOCATION::FileObject, _IO_STACK_LOCATION::Flags, FsRtlCompleteLockIrp, FsRtlCompleteRequest, FsRtlFastUnlockAll(), FsRtlFastUnlockAllByKey(), FsRtlFastUnlockSingle(), FsRtlPrivateLock(), _IO_STATUS_BLOCK::Information, IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), IRP_MJ_LOCK_CONTROL, IRP_MN_LOCK, IRP_MN_UNLOCK_ALL, IRP_MN_UNLOCK_ALL_BY_KEY, IRP_MN_UNLOCK_SINGLE, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NULL, _IO_STACK_LOCATION::Parameters, SL_EXCLUSIVE_LOCK, SL_FAIL_IMMEDIATELY, Status, _IO_STATUS_BLOCK::Status, STATUS_INVALID_DEVICE_REQUEST, and VOID.
VOID FsRtlPTeardownPerFileObjectContexts (__in PFILE_OBJECT FileObject)
Definition at line 731 of file filtrctx.c.
References ASSERT, ExFreePool(), FALSE, _PER_FILEOBJECT_CTXCTRL::FilterContexts, IoChangeFileObjectFilterContext(), IoGetFileObjectFilterContext(), IsListEmpty, NULL, and STATUS_SUCCESS.
Referenced by IopDeleteFile().
NTKERNELAPI NTSTATUS FsRtlRegisterUncProvider (__inout PHANDLE MupHandle, __in PUNICODE_STRING RedirectorDeviceName, __in BOOLEAN MailslotsSupported)
Definition at line 246 of file unc.c.
References DevMup, DevNull, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, FsRtlpDRD, FsRtlpIsDfsEnabled(), FsRtlpOpenDev(), FsRtlpRedirs, FsRtlpRegisterProviderWithMUP(), FsRtlpSetSymbolicLink(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), MailslotsSupported, MODULE_POOL_TAG, MupRegKey, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, STATUS_INSUFFICIENT_RESOURCES, VOID, ZwClose(), and ZwLoadDriver().
NTKERNELAPI VOID FsRtlReleaseFile (__in PFILE_OBJECT FileObject)
Definition at line 3820 of file fastio.c.
References ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FAST_IO_DISPATCH::ReleaseFileForNtCreateSection, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by CcDeleteSharedCacheMap(), CcSetPrivateWriteFile(), CcWriteBehind(), CcZeroEndOfLastPage(), FsRtlCreateSectionForDataScan(), and MmCreateSection().
NTKERNELAPI VOID FsRtlReleaseFileForCcFlush (IN PFILE_OBJECT FileObject)
Definition at line 3203 of file fastio.c.
References ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FS_FILTER_RELEASE_FOR_CC_FLUSH, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, _FAST_IO_DISPATCH::ReleaseForCcFlush, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by MiRemoveUnusedSegments(), MiShutdownSystem(), MmFlushSection(), and MmFlushVirtualMemory().
NTKERNELAPI VOID FsRtlReleaseFileForModWrite (IN PFILE_OBJECT FileObject, IN PERESOURCE ResourceToRelease)
Definition at line 2676 of file fastio.c.
References ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FS_FILTER_RELEASE_FOR_MOD_WRITE, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), _FS_FILTER_CALLBACK_DATA::Parameters, _FS_FILTER_PARAMETERS::ReleaseForModifiedPageWriter, _FAST_IO_DISPATCH::ReleaseForModWrite, _FS_FILTER_PARAMETERS::ResourceToRelease, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by MiWriteComplete().
NTKERNELAPI VOID FsRtlRemoveBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG SectorCount)
Definition at line 1655 of file largemcb.c.
References Dbg, DebugTrace, EndingVbn, FsRtlAddLargeEntry(), FsRtlFindLargeIndex(), FsRtlRemoveLargeEntry(), Index, _NONOPAQUE_BASE_MCB::Mapping, NextStartingLbn, _MAPPING::NextVbn, NOTHING, PreviousEndingLbn, SectorsWithinRun, StartingLbn, StartingVbn, and UNUSED_LBN.
Referenced by FsRtlRemoveLargeMcbEntry().
NTKERNELAPI VOID FsRtlRemoveLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG SectorCount)
Definition at line 2101 of file largemcb.c.
References ASSERTMSG, Dbg, DebugTrace, FsRtlRemoveBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlRemoveMcbEntry().
NTKERNELAPI VOID FsRtlRemoveMcbEntry (__in PMCB Mcb, __in VBN Vbn, __in ULONG SectorCount)
Definition at line 363 of file largemcb.c.
References FsRtlRemoveLargeMcbEntry(), and PAGED_CODE.
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlRemovePerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 620 of file filtrctx.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), _PER_FILEOBJECT_CTXCTRL::FastMutex, _PER_FILEOBJECT_CTXCTRL::FilterContexts, _LIST_ENTRY::Flink, _FSRTL_PER_FILEOBJECT_CONTEXT::InstanceId, IoGetFileObjectFilterContext(), IsListEmpty, _FSRTL_PER_FILEOBJECT_CONTEXT::Links, MySearchList, NULL, _FSRTL_PER_FILEOBJECT_CONTEXT::OwnerId, and RemoveEntryList().
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlRemovePerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER StreamContext, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 205 of file filtrctx.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FlagOn, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS, _FSRTL_PER_STREAM_CONTEXT::InstanceId, IsListEmpty, _FSRTL_PER_STREAM_CONTEXT::Links, MySearchList, NULL, _FSRTL_PER_STREAM_CONTEXT::OwnerId, and RemoveEntryList().
NTKERNELAPI VOID FsRtlResetBaseMcb (__in PBASE_MCB Mcb)
Definition at line 962 of file largemcb.c.
NTKERNELAPI VOID FsRtlResetLargeMcb (__in PLARGE_MCB Mcb, __in BOOLEAN SelfSynchronized)
Definition at line 992 of file largemcb.c.
References KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
NTSTATUS FsRtlSetFileSize (IN PFILE_OBJECT FileObject, IN OUT PLARGE_INTEGER FileSize)
Definition at line 4226 of file fastio.c.
References _IO_STACK_LOCATION::DeviceObject, _FILE_END_OF_FILE_INFORMATION::EndOfFile, Executive, FALSE, FileEndOfFileInformation, _IO_STACK_LOCATION::FileObject, HardErrorState, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoSetThreadHardErrorMode(), IRP_MJ_SET_INFORMATION, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by MiCreateDataFileMap(), and MmExtendSection().
NTKERNELAPI BOOLEAN FsRtlSplitBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Amount)
Definition at line 2820 of file largemcb.c.
References ASSERTMSG, Dbg, DebugTrace, FALSE, FsRtlAddLargeEntry(), FsRtlFindLargeIndex(), Index, _NONOPAQUE_BASE_MCB::Mapping, NOTHING, PAGED_CODE, _NONOPAQUE_BASE_MCB::PairCount, PreviousEndingLbn, StartingLbn, StartingVbn, TRUE, try_return, and UNUSED_LBN.
Referenced by FsRtlSplitLargeMcb().
NTKERNELAPI BOOLEAN FsRtlSplitLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG Amount)
Definition at line 3037 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlSplitBaseMcb(), KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), and PAGED_CODE.
NTKERNELAPI NTSTATUS FsRtlSyncVolumes (__in PDEVICE_OBJECT TargetDevice, __in_opt PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER ByteCount)
Definition at line 94 of file faulttol.c.
References STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
NTKERNELAPI VOID FsRtlTeardownPerStreamContexts (__in PFSRTL_ADVANCED_FCB_HEADER AdvancedHeader)
Definition at line 295 of file filtrctx.c.
References ASSERT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, _FSRTL_PER_STREAM_CONTEXT::FreeCallback, IsListEmpty, RemoveHeadList(), and TRUE.
NTKERNELAPI VOID FsRtlTruncateBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG Vbn)
Definition at line 750 of file largemcb.c.
References ASSERTMSG, Dbg, DebugTrace, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FsRtlAllocateFirstMapping, FsRtlFindLargeIndex(), FsRtlpAllocatePool, Index, INITIAL_MAXIMUM_PAIR_COUNT, _NONOPAQUE_BASE_MCB::Mapping, _NONOPAQUE_BASE_MCB::MaximumPairCount, NextStartingVbn, NULL, PagedPool, _NONOPAQUE_BASE_MCB::PairCount, _NONOPAQUE_BASE_MCB::PoolType, RtlCopyMemory, StartingLbn, and UNUSED_LBN.
Referenced by FsRtlTruncateLargeMcb().
NTKERNELAPI VOID FsRtlTruncateLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG Vbn)
Definition at line 917 of file largemcb.c.
References Dbg, DebugTrace, FsRtlTruncateBaseMcb(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlTruncateMcb().
NTKERNELAPI VOID FsRtlTruncateMcb (__in PMCB Mcb, __in VBN Vbn)
Definition at line 332 of file largemcb.c.
References FsRtlTruncateLargeMcb(), and PAGED_CODE.
NTKERNELAPI VOID FsRtlUninitializeBaseMcb (__in PBASE_MCB Mcb)
Definition at line 663 of file largemcb.c.
References Dbg, DebugTrace, ExFreePool(), FsRtlFreeFirstMapping, INITIAL_MAXIMUM_PAIR_COUNT, and PagedPool.
Referenced by FsRtlUninitializeLargeMcb().
NTKERNELAPI VOID FsRtlUninitializeFileLock (__in PFILE_LOCK FileLock)
Definition at line 965 of file filelock.c.
References CONTAINING_RECORD, _WAITING_LOCK::Context, Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, FsRtlAcquireCancelCollide, FsRtlAcquireLockQueueAtDpc, FsRtlCompleteLockIrp, FsRtlFreeExclusiveLock(), FsRtlFreeLockInfo(), FsRtlFreeLockTreeNode(), FsRtlFreeSharedLock(), FsRtlFreeWaitingLock(), FsRtlReleaseCancelCollide, FsRtlReleaseLockQueueFromDpc, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_LOCK::Irp, _WAITING_LOCK::Link, _LOCKTREE_NODE::Links, _EX_LOCK::Links, _LOCK_INFO::LockQueue, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, PIRP, PopEntryList, PushEntryList, RtlDeleteNoSplay(), _LOCK_QUEUE::SharedLockTree, STATUS_RANGE_NOT_LOCKED, and _LOCK_QUEUE::WaitingLocks.
Referenced by FsRtlFreeFileLock().
NTKERNELAPI VOID FsRtlUninitializeLargeMcb (__in PLARGE_MCB Mcb)
Definition at line 705 of file largemcb.c.
References Dbg, DebugTrace, FsRtlFreeFastMutex, FsRtlUninitializeBaseMcb(), and NULL.
Referenced by FsRtlUninitializeMcb().
NTKERNELAPI VOID FsRtlUninitializeMcb (__in PMCB Mcb)
Definition at line 319 of file largemcb.c.
References FsRtlUninitializeLargeMcb(), and PAGED_CODE.
NTKERNELAPI VOID FsRtlUninitializeOplock (__inout POPLOCK Oplock)
Definition at line 410 of file oplock.c.
References _WAITING_IRP::CompletionRoutine, CONTAINING_RECORD, _WAITING_IRP::Context, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExFreePool(), ExReleaseFastMutexUnsafe(), _NONOPAQUE_OPLOCK::FastMutex, FILE_OPLOCK_BROKEN_TO_NONE, _NONOPAQUE_OPLOCK::FileObject, _LIST_ENTRY::Flink, FsRtlCompleteRequest, IoAcquireCancelSpinLock(), IoGetCurrentIrpStackLocation, IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_IRP::Irp, IRP, _NONOPAQUE_OPLOCK::IrpExclusiveOplock, _NONOPAQUE_OPLOCK::IrpOplocksII, IsListEmpty, NULL, ObDereferenceObject(), PIRP, RemoveHeadList(), STATUS_SUCCESS, and _NONOPAQUE_OPLOCK::WaitingIrps.
Variable Documentation
UCHAR const* const LEGAL_ANSI_CHARACTER_ARRAY
PUSHORT NLS_OEM_LEAD_BYTE_INFO