Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/iomgr.h File Reference
iomgr.h File Reference
#include "ntos.h"
#include "ntdddisk.h"
#include "ntddscsi.h"
#include "mountmgr.h"
#include "ntiolog.h"
#include "ntiologc.h"
#include "ntseapi.h"
#include "fsrtl.h"
#include "zwapi.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "safeboot.h"
#include "ioverifier.h"
#include "iopcmn.h"
Data Structures
struct _DUMMY_FILE_OBJECT
struct _ERROR_LOG_ENTRY
struct _IO_UNLOAD_SAFE_COMPLETION_CONTEXT
struct _IO_WORKITEM
struct _IOP_APC_HARD_ERROR_PACKET
struct _IOP_FILE_OBJECT_EXTENSION
struct _IOP_HARD_ERROR_PACKET
struct _IOP_HARD_ERROR_QUEUE
struct _IOP_IRP_STACK_PROFILER
struct _IOP_MINI_COMPLETION_PACKET
struct _IOP_RESERVE_IRP_ALLOCATOR
struct _LINK_TRACKING_PACKET
struct _LOAD_PACKET
struct _NOTIFICATION_PACKET
struct _OPEN_PACKET
struct _REINIT_PACKET
struct _SHUTDOWN_PACKET
Macros
#define BASE_STACK_COUNT DEFAULT_LARGE_IRP_LOCATIONS
#define DEFAULT_LARGE_IRP_LOCATIONS 8
#define FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK 0x1
#define IO_SD_LEGACY 0
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_E 1
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_E_RES_E 2
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE 3
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE_RES_RE 4
#define IO_SD_SYS_ALL_ADM_RE 5
#define IOP_ABORT 1
#define IOP_CREATE_DEVICE_OBJECT_EXTENSION 0x4
#define IOP_CREATE_IGNORE_SHARE_ACCESS_CHECK 0x2
#define IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT 0x1
#define IOP_ENABLE_AUTO_SIZING 0x1
#define IOP_FIXED_SIZE_MDL_PFNS 0x17
#define IOP_MAXIMUM_LOG_ALLOCATION (100*PAGE_SIZE)
#define IOP_MAXIMUM_OUTSTANDING_HARD_ERRORS 25
#define IOP_PROFILE_DURATION 1
#define IOP_PROFILE_STACK_COUNT 0x2
#define IOP_PROFILE_TIME_PERIOD 60
#define IOP_PROFILE_TRIGGER_INTERVAL 10
#define IopAcquireCancelSpinLockAtDpcLevel() KiAcquireQueuedSpinLock (&KeGetCurrentPrcb()->LockQueue[LockQueueIoCancelLock])
#define IopAllocateIrp(StackSize, ChargeQuota) IoAllocateIrp((StackSize), (ChargeQuota))
#define IopApcRoutinePresent(ApcRoutine) ARGUMENT_PRESENT(ApcRoutine)
#define IopDequeueThreadIrp(Irp)
#define IopIrpAutoSizingEnabled() ((IopIrpStackProfiler.Flags & IOP_ENABLE_AUTO_SIZING))
#define IopIrpProfileStackCountEnabled()
#define IopIsReserveIrp(Irp) ((Irp) == (IopReserveIrpAllocator.ReserveIrp))
#define IopMarkApcRoutineIfAsyncronousIo32(Iosb, ApcRoutine, synchronousIo)
#define IopProfileIrpStackCount(StackSize)
#define IopReleaseCancelSpinLockFromDpcLevel() KiReleaseQueuedSpinLock (&KeGetCurrentPrcb()->LockQueue[LockQueueIoCancelLock])
#define IopReleaseFileObjectLock(FileObject)
#define IsIoVerifierOn() IopVerifierOn
#define MAX_LOOKASIDE_IRP_STACK_COUNT 20
#define MAX_RESERVE_IRP_STACK_SIZE 20
#define MIN_IRP_THRESHOLD 400
#define NUM_SAMPLE_IRPS 2000
#define OPEN_PACKET_PATTERN 0xbeaa0251
Typedefs
typedef enum _COMPLETION_PACKET_TYPE COMPLETION_PACKET_TYPE
typedef struct _DUMMY_FILE_OBJECT DUMMY_FILE_OBJECT
typedef struct _DUMP_CONTROL_BLOCK DUMP_CONTROL_BLOCK
typedef struct _ERROR_LOG_ENTRY ERROR_LOG_ENTRY
typedef struct _IO_UNLOAD_SAFE_COMPLETION_CONTEXT IO_UNLOAD_SAFE_COMPLETION_CONTEXT
typedef struct _IO_WORKITEM IO_WORKITEM
typedef struct _IOP_APC_HARD_ERROR_PACKET IOP_APC_HARD_ERROR_PACKET
typedef struct _IOP_FILE_OBJECT_EXTENSION IOP_FILE_OBJECT_EXTENSION
typedef struct _IOP_HARD_ERROR_PACKET IOP_HARD_ERROR_PACKET
typedef struct _IOP_HARD_ERROR_QUEUE IOP_HARD_ERROR_QUEUE
typedef struct _IOP_IRP_STACK_PROFILER IOP_IRP_STACK_PROFILER
typedef struct _IOP_MINI_COMPLETION_PACKET IOP_MINI_COMPLETION_PACKET
typedef struct _IOP_RESERVE_IRP_ALLOCATOR IOP_RESERVE_IRP_ALLOCATOR
typedef IN OUT PIRP Irp
typedef struct _LINK_TRACKING_PACKET LINK_TRACKING_PACKET
typedef struct _LOAD_PACKET LOAD_PACKET
typedef struct _NOTIFICATION_PACKET NOTIFICATION_PACKET
typedef struct _OPEN_PACKET OPEN_PACKET
typedef enum _COMPLETION_PACKET_TYPE * PCOMPLETION_PACKET_TYPE
typedef struct _DUMMY_FILE_OBJECT * PDUMMY_FILE_OBJECT
typedef struct _DUMP_CONTROL_BLOCK * PDUMP_CONTROL_BLOCK
typedef struct _ERROR_LOG_ENTRY * PERROR_LOG_ENTRY
typedef PIRP(* PIO_ALLOCATE_IRP) (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
typedef VOID(* PIO_FREE_IRP) (IN struct _IRP *Irp)
typedef struct _IO_UNLOAD_SAFE_COMPLETION_CONTEXT * PIO_UNLOAD_SAFE_COMPLETION_CONTEXT
typedef struct _IOP_APC_HARD_ERROR_PACKET * PIOP_APC_HARD_ERROR_PACKET
typedef struct _IOP_FILE_OBJECT_EXTENSION * PIOP_FILE_OBJECT_EXTENSION
typedef struct _IOP_HARD_ERROR_PACKET * PIOP_HARD_ERROR_PACKET
typedef struct _IOP_HARD_ERROR_QUEUE * PIOP_HARD_ERROR_QUEUE
typedef struct _IOP_IRP_STACK_PROFILER * PIOP_IRP_STACK_PROFILER
typedef struct _IOP_MINI_COMPLETION_PACKET * PIOP_MINI_COMPLETION_PACKET
typedef struct _IOP_RESERVE_IRP_ALLOCATOR * PIOP_RESERVE_IRP_ALLOCATOR
typedef struct _LINK_TRACKING_PACKET * PLINK_TRACKING_PACKET
typedef struct _LOAD_PACKET * PLOAD_PACKET
typedef struct _NOTIFICATION_PACKET * PNOTIFICATION_PACKET
typedef struct _OPEN_PACKET * POPEN_PACKET
typedef struct _REINIT_PACKET * PREINIT_PACKET
typedef IN CCHAR PriorityBoost
typedef struct _SHUTDOWN_PACKET * PSHUTDOWN_PACKET
typedef enum _TRANSFER_TYPE * PTRANSFER_TYPE
typedef struct _REINIT_PACKET REINIT_PACKET
typedef IN OUT PIRP IN PVOID ReturnAddress
typedef struct _SHUTDOWN_PACKET SHUTDOWN_PACKET
typedef enum _TRANSFER_TYPE TRANSFER_TYPE
Enumerations
enum _COMPLETION_PACKET_TYPE { IopCompletionPacketIrp, IopCompletionPacketMini, IopCompletionPacketQuota }
enum _TRANSFER_TYPE { ReadTransfer, WriteTransfer, OtherTransfer }
Functions
VOID IopAbortRequest (IN PKAPC Apc)
static FORCEINLINE BOOLEAN IopAcquireFastLock (IN PFILE_OBJECT FileObject)
NTSTATUS IopAcquireFileObjectLock (IN PFILE_OBJECT FileObject, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN Alertable, OUT PBOOLEAN Interrupted)
PVOID IopAllocateErrorLogEntry (IN PDEVICE_OBJECT deviceObject, IN PDRIVER_OBJECT driverObject, IN UCHAR EntrySize)
VOID IopAllocateIrpCleanup (IN PFILE_OBJECT FileObject, IN PKEVENT EventObject OPTIONAL)
PIRP IopAllocateIrpMustSucceed (IN CCHAR StackSize)
PIRP IopAllocateIrpPrivate (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
PIRP IopAllocateReserveIrp (IN CCHAR StackSize)
VOID IopApcHardError (IN PVOID StartContext)
PDEVICE_OBJECT IopAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, OUT PDEVICE_OBJECT *AttachedToDeviceObject OPTIONAL)
VOID IopCancelAlertedRequest (IN PKEVENT Event, IN PIRP Irp)
VOID IopCheckBackupRestorePrivilege (IN PACCESS_STATE AccessState, IN OUT PULONG CreateOptions, IN KPROCESSOR_MODE PreviousMode, IN ULONG Disposition)
NTSTATUS IopCheckGetQuotaBufferValidity (IN PFILE_GET_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG_PTR ErrorOffset)
NTSTATUS IopCheckUnloadDriver (IN PDRIVER_OBJECT driverObject, OUT PBOOLEAN unloadDriver)
VOID IopCloseFile (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ULONG GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID IopCompletePageWrite (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopCompleteRequest (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopCompleteUnloadOrDelete (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN OnCleanStack, IN KIRQL Irql)
BOOLEAN IopConfigureCrashDump (IN HANDLE HandlePagingFile)
VOID IopConnectLinkTrackingPort (IN PVOID Parameter)
NTSTATUS IopCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN ULONG InternalFlags, IN PVOID DeviceObject)
NTSTATUS IopCreateSecurityDescriptorPerType (IN PSECURITY_DESCRIPTOR Descriptor, IN ULONG SecurityDescriptorFlavor, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
NTSTATUS IopCreateVpb (IN PDEVICE_OBJECT DeviceObject)
VOID IopDeallocateApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopDecrementDeviceObjectRef (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AlwaysUnload, IN BOOLEAN OnCleanStack)
VOID IopDeleteDevice (IN PVOID Object)
VOID IopDeleteDriver (IN PVOID Object)
VOID IopDeleteFile (IN PVOID Object)
VOID IopDeleteIoCompletion (IN PVOID Object)
VOID IopDereferenceVpbAndFree (IN PVPB Vpb)
VOID IopDisassociateThreadIrp (VOID)
BOOLEAN IopDmaDispatch (IN PKINTERRUPT Interrupt, IN PVOID ServiceContext)
VOID IopDoNameTransmogrify (IN PIRP Irp, IN PFILE_OBJECT FileObject, IN PREPARSE_DATA_BUFFER ReparseBuffer)
VOID IopDropIrp (IN PIRP Irp, IN PFILE_OBJECT FileObject)
VOID IopErrorLogThread (IN PVOID StartContext)
VOID IopExceptionCleanup (IN PFILE_OBJECT FileObject, IN PIRP Irp, IN PKEVENT EventObject OPTIONAL, IN PKEVENT KernelEvent OPTIONAL)
LONG IopExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointers, OUT PNTSTATUS ExceptionCode)
NTSTATUS FORCEINLINE IopfCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
VOID FASTCALL IopfCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBost)
VOID IopFreeIrp (IN PIRP Irp)
VOID IopFreeIrpAndMdls (IN PIRP Irp)
VOID IopFreeReserveIrp (IN CCHAR PriorityBoost)
NTSTATUS IopGetBasicInformationFile (IN PFILE_OBJECT FileObject, IN PFILE_BASIC_INFORMATION BasicInformationBuffer)
PDEVICE_OBJECT IopGetDeviceAttachmentBase (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopGetDriverPathInformation (IN PFILE_OBJECT FileObject, IN PFILE_FS_DRIVER_PATH_INFORMATION FsDpInfo, IN ULONG Length)
NTSTATUS IopGetFileInformation (IN PFILE_OBJECT FileObject, IN ULONG Length, IN FILE_INFORMATION_CLASS FileInformationClass, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
BOOLEAN IopGetMountFlag (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopGetRegistryValues (IN HANDLE KeyHandle, IN PKEY_VALUE_FULL_INFORMATION *ValueList)
NTSTATUS IopGetSetObjectId (IN PFILE_OBJECT FileObject, IN OUT PVOID Buffer, IN ULONG Length, IN ULONG OperationFlags)
NTSTATUS IopGetSetSecurityObject (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS IopGetVolumeId (IN PFILE_OBJECT FileObject, IN OUT PLINK_TRACKING_INFORMATION ObjectId, IN ULONG Length)
VOID IopHardErrorThread (PVOID StartContext)
NTSTATUS IopInitializeIrpStackProfiler (VOID)
BOOLEAN IopInitializeReserveIrp (PIOP_RESERVE_IRP_ALLOCATOR Allocator)
VOID IopInsertRemoveDevice (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Insert)
ULONG FASTCALL IopInterlockedDecrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
ULONG FASTCALL IopInterlockedIncrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
PLIST_ENTRY FASTCALL IopInterlockedInsertHeadList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
PLIST_ENTRY FASTCALL IopInterlockedInsertTailList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
PLIST_ENTRY FASTCALL IopInterlockedRemoveHeadList (IN PLIST_ENTRY ListHead)
VOID IopIrpStackProfilerTimer (IN struct _KDPC *Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
LOGICAL IopIsSameMachine (IN PFILE_OBJECT SourceFile, IN HANDLE TargetFile)
VOID IopLoadFileSystemDriver (IN PDEVICE_OBJECT DeviceObject)
VOID IopLoadUnloadDriver (IN PVOID Parameter)
NTSTATUS IopLogErrorEvent (IN ULONG SequenceNumber, IN ULONG UniqueErrorValue, IN NTSTATUS FinalStatus, IN NTSTATUS SpecificIOStatus, IN ULONG LengthOfInsert1, IN PWCHAR Insert1, IN ULONG LengthOfInsert2, IN PWCHAR Insert2)
NTSTATUS IopLookupBusStringFromID (IN HANDLE KeyHandle, IN INTERFACE_TYPE InterfaceType, OUT PWCHAR Buffer, IN ULONG Length, OUT PULONG BusFlags OPTIONAL)
NTSTATUS IopMountVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount, IN BOOLEAN DeviceLockAlreadyHeld, IN BOOLEAN Alertable, OUT PVPB *Vpb)
VOID IopNotifyAlreadyRegisteredFileSystems (IN PLIST_ENTRY ListHead, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine, IN BOOLEAN SkipRaw)
NTSTATUS IopOpenLinkOrRenameTarget (OUT PHANDLE TargetHandle, IN PIRP Irp, IN PVOID RenameBuffer, IN PFILE_OBJECT FileObject)
NTSTATUS IopOpenRegistryKey (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess, IN BOOLEAN Create)
NTSTATUS IopParseDevice (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
NTSTATUS IopParseFile (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
VOID IopPerfLogFileCreate (IN PFILE_OBJECT FileObject, IN PUNICODE_STRING CompleteName)
static __inline VOID IopProbeAndLockPages (IN OUT PMDL MemoryDescriptorList, IN KPROCESSOR_MODE AccessMode, IN LOCK_OPERATION Operation, IN PDEVICE_OBJECT DeviceObject, IN ULONG MajorFunction)
VOID IopProcessIrpStackProfiler (VOID)
BOOLEAN IopProtectSystemPartition (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopQueryName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
NTSTATUS IopQueryNameInternal (IN PVOID Object, IN BOOLEAN HasObjectName, IN BOOLEAN UseDosDeviceName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
NTSTATUS IopQueryXxxInformation (IN PFILE_OBJECT FileObject, IN ULONG InformationClass, IN ULONG Length, IN KPROCESSOR_MODE Mode, OUT PVOID Information, OUT PULONG ReturnedLength, IN BOOLEAN FileInformation)
VOID IopQueueWorkRequest (IN PIRP Irp)
VOID IopRaiseHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID IopRaiseInformationalHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID IopReadyDeviceObjects (IN PDRIVER_OBJECT DriverObject)
BOOLEAN IopReferenceVerifyVpb (IN PDEVICE_OBJECT DeviceObject, OUT PVPB *Vpb, OUT PDEVICE_OBJECT *FsDeviceObject)
NTSTATUS IopReportResourceUsage (IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PCM_RESOURCE_LIST DriverList OPTIONAL, IN ULONG DriverListSize OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN PCM_RESOURCE_LIST DeviceList OPTIONAL, IN ULONG DeviceListSize OPTIONAL, IN BOOLEAN OverrideConflict, OUT PBOOLEAN ConflictDetected)
NTSTATUS IopSetEaOrQuotaInformationFile (IN HANDLE FileHandle, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PVOID Buffer, IN ULONG Length, IN BOOLEAN SetEa)
NTSTATUS IopSetRemoteLink (IN PFILE_OBJECT FileObject, IN PFILE_OBJECT DestinationFileObject OPTIONAL, IN PFILE_TRACKING_INFORMATION FileInformation OPTIONAL)
VOID IopShutdownBaseFileSystems (IN PLIST_ENTRY ListHead)
VOID IopStartApcHardError (IN PVOID StartContext)
NTSTATUS IopSynchronousApiServiceTail (IN NTSTATUS ReturnedStatus, IN PKEVENT Event, IN PIRP Irp, IN KPROCESSOR_MODE RequestorMode, IN PIO_STATUS_BLOCK LocalIoStatus, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS IopSynchronousServiceTail (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PFILE_OBJECT FileObject, IN BOOLEAN DeferredIoCompletion, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN SynchronousIo, IN TRANSFER_TYPE TransferType)
VOID IopTimerDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
NTSTATUS IopTrackLink (IN PFILE_OBJECT FileObject, IN OUT PIO_STATUS_BLOCK IoStatusBlock, IN PFILE_TRACKING_INFORMATION FileInformation, IN ULONG Length, IN PKEVENT Event, IN KPROCESSOR_MODE RequestorMode)
FORCEINLINE VOID IopUpdateOtherOperationCount (VOID)
FORCEINLINE VOID IopUpdateOtherTransferCount (IN ULONG TransferCount)
FORCEINLINE VOID IopUpdateReadOperationCount (VOID)
FORCEINLINE VOID IopUpdateReadTransferCount (IN ULONG TransferCount)
FORCEINLINE VOID IopUpdateWriteOperationCount (VOID)
FORCEINLINE VOID IopUpdateWriteTransferCount (IN ULONG TransferCount)
VOID IopUserCompletion (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
BOOLEAN IopVerifyDeviceObjectOnStack (IN PDEVICE_OBJECT BaseDeviceObject, IN PDEVICE_OBJECT TopDeviceObject)
BOOLEAN IopVerifyDiskSignature (IN PDRIVE_LAYOUT_INFORMATION_EX DriveLayout, IN PARC_DISK_SIGNATURE LoaderDiskBlock, OUT PULONG DiskSignature)
BOOLEAN IopVerifyDriverObjectOnStack (IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_OBJECT DriverObject)
NTSTATUS IopXxxControlFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, IN ULONG IoControlCode, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN DeviceIoControl)
typedef NTSTATUS (FASTCALL *PIO_CALL_DRIVER)(IN PDEVICE_OBJECT DeviceObject
typedef VOID (FASTCALL *PIO_COMPLETE_REQUEST)(IN PIRP Irp
Variables
POBJECT_TYPE ExEventObjectType
POBJECT_TYPE IoAdapterObjectType
UNICODE_STRING IoArcBootDeviceName
UNICODE_STRING IoArcHalDeviceName
POBJECT_TYPE IoCompletionObjectType
POBJECT_TYPE IoControllerObjectType
LOGICAL IoCountOperations
POBJECT_TYPE IoDeviceHandlerObjectType
PUCHAR IoLoaderArcBootDeviceName
LIST_ENTRY IopBootDriverReinitializeQueueHead
LIST_ENTRY IopCdRomFileSystemQueueHead
GENERAL_LOOKASIDE IopCompletionLookasideList
ERESOURCE IopCrashDumpLock
PIOP_HARD_ERROR_PACKET IopCurrentHardError
ERESOURCE IopDatabaseResource
LIST_ENTRY IopDiskFileSystemQueueHead
ERESOURCE IopDriverLoadResource
LIST_ENTRY IopDriverReinitializeQueueHead
PDUMP_CONTROL_BLOCK IopDumpControlBlock
ULONG IopDumpControlBlockChecksum
LONG IopErrorLogAllocation
KSPIN_LOCK IopErrorLogAllocationLock
BOOLEAN IopErrorLogDisabledThisBoot
LIST_ENTRY IopErrorLogListHead
ALIGNED_SPINLOCK IopErrorLogLock
BOOLEAN IopErrorLogPortPending
WORK_QUEUE_ITEM IopErrorLogWorkItem
ULONG IopFailZeroAccessCreate
const GENERIC_MAPPING IopFileMapping
LIST_ENTRY IopFsNotifyChangeQueueHead
ULONG IopFsRegistrationOps
IOP_HARD_ERROR_QUEUE IopHardError
IOP_IRP_STACK_PROFILER IopIrpStackProfiler
GENERAL_LOOKASIDE IopLargeIrpLookasideList
ULONG IopLargeIrpStackLocations
LINK_TRACKING_PACKET IopLinkTrackingPacket
KEVENT IopLinkTrackingPortObject
PKEVENT IopLinkTrackingServiceEvent
HANDLE IopLinkTrackingServiceEventHandle
PVOID IopLinkTrackingServiceObject
GENERAL_LOOKASIDE IopMdlLookasideList
LIST_ENTRY IopNetworkFileSystemQueueHead
LIST_ENTRY IopNotifyLastChanceShutdownQueueHead
LIST_ENTRY IopNotifyShutdownQueueHead
const ULONG IopQueryFsOperationAccess []
const UCHAR IopQueryFsOperationLength []
const ULONG IopQueryOperationAccess []
const UCHAR IopQueryOperationLength []
const UCHAR IopQuerySetAlignmentRequirement []
const UCHAR IopQuerySetFsAlignmentRequirement []
IOP_RESERVE_IRP_ALLOCATOR IopReserveIrpAllocator
ERESOURCE IopSecurityResource
const ULONG IopSetFsOperationAccess []
const UCHAR IopSetFsOperationLength []
const ULONG IopSetOperationAccess []
const UCHAR IopSetOperationLength []
GENERAL_LOOKASIDE IopSmallIrpLookasideList
LIST_ENTRY IopTapeFileSystemQueueHead
KTIMER IopTimer
ULONG IopTimerCount
KDPC IopTimerDpc
ALIGNED_SPINLOCK IopTimerLock
LIST_ENTRY IopTimerQueueHead
LONG IopUniqueDeviceObjectNumber
BOOLEAN IopVerifierOn
ALIGNED_SPINLOCK IoStatisticsLock
PIO_ALLOCATE_IRP pIoAllocateIrp
PIO_CALL_DRIVER pIofCallDriver
PIO_COMPLETE_REQUEST pIofCompleteRequest
PIO_FREE_IRP pIoFreeIrp
Macro Definition Documentation
#define BASE_STACK_COUNT DEFAULT_LARGE_IRP_LOCATIONS
Definition at line 506 of file iomgr.h.
Referenced by IopProcessIrpStackProfiler().
#define DEFAULT_LARGE_IRP_LOCATIONS 8
Definition at line 505 of file iomgr.h.
Referenced by IoInitSystem().
#define FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK 0x1
Definition at line 487 of file iomgr.h.
Referenced by IoCheckShareAccess(), IopParseDevice(), IoRemoveShareAccess(), IoSetShareAccess(), and IoUpdateShareAccess().
#define IO_SD_LEGACY 0
Definition at line 701 of file iomgr.h.
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_E 1
Definition at line 702 of file iomgr.h.
Referenced by IopCreateSecurityDescriptorPerType().
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_E_RES_E 2
Definition at line 703 of file iomgr.h.
Referenced by IopCreateDefaultDeviceSecurityDescriptor(), and IopCreateSecurityDescriptorPerType().
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE 3
Definition at line 704 of file iomgr.h.
Referenced by IopCreateSecurityDescriptorPerType().
#define IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE_RES_RE 4
Definition at line 705 of file iomgr.h.
Referenced by IopCreateDefaultDeviceSecurityDescriptor(), and IopCreateSecurityDescriptorPerType().
#define IO_SD_SYS_ALL_ADM_RE 5
Definition at line 706 of file iomgr.h.
Referenced by IopCreateSecurityDescriptorPerType().
#define IOP_ABORT 1
Definition at line 27 of file iomgr.h.
Referenced by IopMountVolume(), and IopRaiseHardError().
#define IOP_CREATE_DEVICE_OBJECT_EXTENSION 0x4
Definition at line 483 of file iomgr.h.
Referenced by IoCreateFileSpecifyDeviceObjectHint(), and IopParseDevice().
#define IOP_CREATE_IGNORE_SHARE_ACCESS_CHECK 0x2
Definition at line 482 of file iomgr.h.
Referenced by IoCreateFileSpecifyDeviceObjectHint(), and IopParseDevice().
#define IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT 0x1
Definition at line 481 of file iomgr.h.
Referenced by IoCreateFileSpecifyDeviceObjectHint(), IopOpenLinkOrRenameTarget(), and IopParseDevice().
#define IOP_ENABLE_AUTO_SIZING 0x1
Definition at line 512 of file iomgr.h.
Referenced by IoInitSystem().
#define IOP_FIXED_SIZE_MDL_PFNS 0x17
Definition at line 493 of file iomgr.h.
Referenced by IoAllocateMdl(), and IoInitSystem().
#define IOP_MAXIMUM_LOG_ALLOCATION (100*PAGE_SIZE)
Definition at line 94 of file iomgr.h.
Referenced by IopAllocateErrorLogEntry().
#define IOP_MAXIMUM_OUTSTANDING_HARD_ERRORS 25
Definition at line 168 of file iomgr.h.
Referenced by IoRaiseInformationalHardError().
#define IOP_PROFILE_DURATION 1
Definition at line 514 of file iomgr.h.
#define IOP_PROFILE_STACK_COUNT 0x2
Definition at line 513 of file iomgr.h.
Referenced by IopIrpStackProfilerTimer().
#define IOP_PROFILE_TIME_PERIOD 60
Definition at line 496 of file iomgr.h.
Referenced by IopInitializeIrpStackProfiler().
#define IOP_PROFILE_TRIGGER_INTERVAL 10
Definition at line 515 of file iomgr.h.
Referenced by IopIrpStackProfilerTimer().
#define IopAcquireCancelSpinLockAtDpcLevel () KiAcquireQueuedSpinLock (&KeGetCurrentPrcb()->LockQueue[LockQueueIoCancelLock])
Definition at line 642 of file iomgr.h.
#define IopAllocateIrp (StackSize, ChargeQuota) IoAllocateIrp((StackSize), (ChargeQuota))
Definition at line 648 of file iomgr.h.
Referenced by IopParseDevice(), IopXxxControlFile(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define IopApcRoutinePresent (ApcRoutine) ARGUMENT_PRESENT(ApcRoutine)
Definition at line 886 of file iomgr.h.
Referenced by BuildQueryDirectoryIrp(), IopXxxControlFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define IopDequeueThreadIrp (Irp)
Value:
{ \
   RemoveEntryList( &Irp->ThreadListEntry ); \
   InitializeListHead( &Irp->ThreadListEntry ) ; \
   }
Definition at line 864 of file iomgr.h.
Referenced by IoCancelFileOpen(), IopCloseFile(), IopCompleteRequest(), IopDeleteFile(), and IopParseDevice().
#define IopIrpAutoSizingEnabled () ((IopIrpStackProfiler.Flags & IOP_ENABLE_AUTO_SIZING))
Definition at line 687 of file iomgr.h.
Referenced by IoInitSystem(), IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), and IopFreeIrp().
#define IopIrpProfileStackCountEnabled ()
Value:
((IopIrpStackProfiler.Flags & (IOP_PROFILE_STACK_COUNT|IOP_ENABLE_AUTO_SIZING)) \
            == (IOP_PROFILE_STACK_COUNT|IOP_ENABLE_AUTO_SIZING))
Definition at line 693 of file iomgr.h.
Referenced by IopAllocateIrpPrivate().
#define IopIsReserveIrp (Irp) ((Irp) == (IopReserveIrpAllocator.ReserveIrp))
Definition at line 674 of file iomgr.h.
Referenced by IopfCompleteRequest().
#define IopMarkApcRoutineIfAsyncronousIo32 (Iosb, ApcRoutine, synchronousIo)
Definition at line 887 of file iomgr.h.
Referenced by BuildQueryDirectoryIrp(), IopXxxControlFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define IopProfileIrpStackCount (StackSize)
Value:
((StackSize < MAX_LOOKASIDE_IRP_STACK_COUNT) ? \
                IopIrpStackProfiler.Profile[StackSize]++ : 0)
Definition at line 680 of file iomgr.h.
Referenced by IopAllocateIrpPrivate().
#define IopReleaseCancelSpinLockFromDpcLevel () KiReleaseQueuedSpinLock (&KeGetCurrentPrcb()->LockQueue[LockQueueIoCancelLock])
Definition at line 645 of file iomgr.h.
#define IopReleaseFileObjectLock (FileObject)
Value:
{    \
    ULONG Result;                                   \
    Result = InterlockedExchange( (PLONG) &FileObject->Busy, FALSE ); \
    ASSERT(Result != FALSE);                        \
    if (FileObject->Waiters != 0) {                 \
        KeSetEvent( &FileObject->Lock, 0, FALSE );  \
    }                                               \
    ObDereferenceObject(FileObject);                \
}
Definition at line 1215 of file iomgr.h.
Referenced by IopAllocateIrpCleanup(), IopCloseFile(), IopExceptionCleanup(), IopGetSetSecurityObject(), IopQueryXxxInformation(), IopSynchronousServiceTail(), IopXxxControlFile(), IoSetInformation(), NtQueryInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetInformationFile(), NtWriteFile(), and NtWriteFileGather().
#define IsIoVerifierOn () IopVerifierOn
Definition at line 651 of file iomgr.h.
#define MAX_LOOKASIDE_IRP_STACK_COUNT 20
Definition at line 469 of file iomgr.h.
Referenced by IopInitializeIrpStackProfiler(), IopIrpStackProfilerTimer(), and IopProcessIrpStackProfiler().
#define MAX_RESERVE_IRP_STACK_SIZE 20
Definition at line 495 of file iomgr.h.
Referenced by IopInitializeReserveIrp().
#define MIN_IRP_THRESHOLD 400
Definition at line 498 of file iomgr.h.
Referenced by IopProcessIrpStackProfiler().
#define NUM_SAMPLE_IRPS 2000
Definition at line 497 of file iomgr.h.
Referenced by IopIrpStackProfilerTimer().
#define OPEN_PACKET_PATTERN 0xbeaa0251
Definition at line 206 of file iomgr.h.
Referenced by IoFastQueryNetworkAttributes(), IopCreateFile(), IopParseDevice(), NtDeleteFile(), NtQueryAttributesFile(), and NtQueryFullAttributesFile().
Typedef Documentation
typedef enum _COMPLETION_PACKET_TYPE COMPLETION_PACKET_TYPE
typedef struct _DUMMY_FILE_OBJECT DUMMY_FILE_OBJECT
typedef struct _DUMP_CONTROL_BLOCK DUMP_CONTROL_BLOCK
Definition at line 62 of file iomgr.h.
typedef struct _ERROR_LOG_ENTRY ERROR_LOG_ENTRY
typedef struct _IO_UNLOAD_SAFE_COMPLETION_CONTEXT IO_UNLOAD_SAFE_COMPLETION_CONTEXT
typedef struct _IO_WORKITEM IO_WORKITEM
typedef struct _IOP_APC_HARD_ERROR_PACKET IOP_APC_HARD_ERROR_PACKET
typedef struct _IOP_FILE_OBJECT_EXTENSION IOP_FILE_OBJECT_EXTENSION
typedef struct _IOP_HARD_ERROR_PACKET IOP_HARD_ERROR_PACKET
typedef struct _IOP_HARD_ERROR_QUEUE IOP_HARD_ERROR_QUEUE
typedef struct _IOP_IRP_STACK_PROFILER IOP_IRP_STACK_PROFILER
typedef struct _IOP_MINI_COMPLETION_PACKET IOP_MINI_COMPLETION_PACKET
typedef struct _IOP_RESERVE_IRP_ALLOCATOR IOP_RESERVE_IRP_ALLOCATOR
typedef IN OUT PIRP Irp
Definition at line 141 of file iomgr.h.
typedef struct _LINK_TRACKING_PACKET LINK_TRACKING_PACKET
typedef struct _LOAD_PACKET LOAD_PACKET
typedef struct _NOTIFICATION_PACKET NOTIFICATION_PACKET
typedef struct _OPEN_PACKET OPEN_PACKET
typedef enum _COMPLETION_PACKET_TYPE * PCOMPLETION_PACKET_TYPE
typedef struct _DUMMY_FILE_OBJECT * PDUMMY_FILE_OBJECT
typedef struct _DUMP_CONTROL_BLOCK * PDUMP_CONTROL_BLOCK
Definition at line 62 of file iomgr.h.
typedef struct _ERROR_LOG_ENTRY * PERROR_LOG_ENTRY
typedef PIRP(* PIO_ALLOCATE_IRP) (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
Definition at line 160 of file iomgr.h.
typedef VOID(* PIO_FREE_IRP) (IN struct _IRP *Irp)
Definition at line 154 of file iomgr.h.
typedef struct _IO_UNLOAD_SAFE_COMPLETION_CONTEXT * PIO_UNLOAD_SAFE_COMPLETION_CONTEXT
typedef struct _IOP_APC_HARD_ERROR_PACKET * PIOP_APC_HARD_ERROR_PACKET
typedef struct _IOP_FILE_OBJECT_EXTENSION * PIOP_FILE_OBJECT_EXTENSION
typedef struct _IOP_HARD_ERROR_PACKET * PIOP_HARD_ERROR_PACKET
typedef struct _IOP_HARD_ERROR_QUEUE * PIOP_HARD_ERROR_QUEUE
typedef struct _IOP_IRP_STACK_PROFILER * PIOP_IRP_STACK_PROFILER
typedef struct _IOP_MINI_COMPLETION_PACKET * PIOP_MINI_COMPLETION_PACKET
typedef struct _IOP_RESERVE_IRP_ALLOCATOR * PIOP_RESERVE_IRP_ALLOCATOR
typedef struct _LINK_TRACKING_PACKET * PLINK_TRACKING_PACKET
typedef struct _LOAD_PACKET * PLOAD_PACKET
typedef struct _NOTIFICATION_PACKET * PNOTIFICATION_PACKET
typedef struct _OPEN_PACKET * POPEN_PACKET
typedef struct _REINIT_PACKET * PREINIT_PACKET
typedef IN CCHAR PriorityBoost
Definition at line 150 of file iomgr.h.
typedef struct _SHUTDOWN_PACKET * PSHUTDOWN_PACKET
typedef enum _TRANSFER_TYPE * PTRANSFER_TYPE
typedef struct _REINIT_PACKET REINIT_PACKET
typedef IN OUT PIRP IN PVOID ReturnAddress
Definition at line 141 of file iomgr.h.
typedef struct _SHUTDOWN_PACKET SHUTDOWN_PACKET
typedef enum _TRANSFER_TYPE TRANSFER_TYPE
Enumeration Type Documentation
enum _COMPLETION_PACKET_TYPE
Enumerator
IopCompletionPacketIrp
IopCompletionPacketMini
IopCompletionPacketQuota
Definition at line 387 of file iomgr.h.
enum _TRANSFER_TYPE
Enumerator
ReadTransfer
WriteTransfer
OtherTransfer
Definition at line 83 of file iomgr.h.
Function Documentation
VOID IopAbortRequest (IN PKAPC Apc)
Definition at line 185 of file internal.c.
References IopCompleteRequest(), and PAGED_CODE.
Referenced by IopfCompleteRequest(), and IoRaiseHardError().
static FORCEINLINE BOOLEAN IopAcquireFastLock (IN PFILE_OBJECT FileObject) static
Definition at line 628 of file iomgr.h.
References FALSE, InterlockedExchange(), ObReferenceObject, TRUE, and UNREFERENCED_PARAMETER.
Referenced by BuildQueryDirectoryIrp(), IopCloseFile(), IopGetSetSecurityObject(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
NTSTATUS IopAcquireFileObjectLock (IN PFILE_OBJECT FileObject, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN Alertable, OUT PBOOLEAN Interrupted)
Definition at line 222 of file internal.c.
References Executive, FALSE, InterlockedDecrement, InterlockedExchange(), InterlockedIncrement, KeSetEvent(), KeWaitForSingleObject(), NULL, ObReferenceObject, PAGED_CODE, STATUS_ALERTED, STATUS_SUCCESS, STATUS_USER_APC, and TRUE.
Referenced by BuildQueryDirectoryIrp(), IopCloseFile(), IopGetSetSecurityObject(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
PVOID IopAllocateErrorLogEntry (IN PDEVICE_OBJECT deviceObject, IN PDRIVER_OBJECT driverObject, IN UCHAR EntrySize)
Definition at line 587 of file iosubs.c.
References _ERROR_LOG_ENTRY::DeviceObject, _ERROR_LOG_ENTRY::DriverObject, ERROR_LOG_MAXIMUM_SIZE, ExAllocatePoolWithTag, InterlockedExchangeAdd(), IO_TYPE_ERROR_LOG, IOP_MAXIMUM_LOG_ALLOCATION, IopErrorLogAllocation, NonPagedPool, NULL, ObReferenceObject, RtlZeroMemory, _ERROR_LOG_ENTRY::Size, and _ERROR_LOG_ENTRY::Type.
Referenced by IoAllocateErrorLogEntry(), and IoAllocateGenericErrorLogEntry().
VOID IopAllocateIrpCleanup (IN PFILE_OBJECT FileObject, IN PKEVENT EventObject OPTIONAL)
Definition at line 326 of file internal.c.
References ARGUMENT_PRESENT, FO_SYNCHRONOUS_IO, IopReleaseFileObjectLock, ObDereferenceObject(), and PAGED_CODE.
Referenced by BuildQueryDirectoryIrp(), IopGetSetSecurityObject(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
PIRP IopAllocateIrpMustSucceed (IN CCHAR StackSize)
Definition at line 378 of file internal.c.
References FALSE, IO_INFINITE_RETRIES, IoAllocateIrp(), KeDelayExecutionThread(), KernelMode, PIRP, and _LARGE_INTEGER::QuadPart.
Referenced by IoCancelFileOpen(), IopCloseFile(), and IopDeleteFile().
PIRP IopAllocateIrpPrivate (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
Definition at line 745 of file iosubs.c.
References ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, ExFreePool(), FALSE, InterlockedDecrement, InterlockedPopEntrySList(), IopInitializeIrp, IopIrpAutoSizingEnabled, IopIrpProfileStackCountEnabled, IopLargeIrpStackLocations, IopProfileIrpStackCount, IoSizeOfIrp, IRP_ALLOCATED_FIXED_SIZE, IRP_LOOKASIDE_ALLOCATION, IRP_QUOTA_CHARGED, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, _KPRCB::LookasideIrpFloat, LookasideLargeIrpList, LookasideSmallIrpList, NonPagedPool, NULL, _PP_LOOKASIDE_LIST::P, PIRP, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _KPRCB::PPLookasideList, and _GENERAL_LOOKASIDE::TotalAllocates.
Referenced by IopSetIoRoutines().
PIRP IopAllocateReserveIrp (IN CCHAR StackSize)
Definition at line 10287 of file internal.c.
References _IOP_RESERVE_IRP_ALLOCATOR::Event, Executive, FALSE, InterlockedExchange(), IoInitializeIrp(), IopReserveIrpAllocator, IoSizeOfIrp, _IOP_RESERVE_IRP_ALLOCATOR::IrpAllocated, KernelMode, KeWaitForSingleObject(), NULL, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrp, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrpStackSize, and VOID.
Referenced by IoPageRead().
VOID IopApcHardError (IN PVOID StartContext)
Definition at line 433 of file internal.c.
References ExFreePool(), IopRaiseHardError(), _IOP_APC_HARD_ERROR_PACKET::Irp, _IOP_APC_HARD_ERROR_PACKET::RealDeviceObject, and _IOP_APC_HARD_ERROR_PACKET::Vpb.
Referenced by IopStartApcHardError().
PDEVICE_OBJECT IopAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, OUT PDEVICE_OBJECT *AttachedToDeviceObject OPTIONAL)
Definition at line 1435 of file iosubs.c.
References ASSERT, _DEVOBJ_EXTENSION::AttachedTo, DO_DEVICE_INITIALIZING, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_START_PENDING, DOE_UNLOAD_PENDING, IoGetAttachedDevice(), IOV_ATTACH_DEVICE_TO_DEVICE_STACK, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
Referenced by IoAttachDeviceToDeviceStack(), and IoAttachDeviceToDeviceStackSafe().
VOID IopCancelAlertedRequest (IN PKEVENT Event, IN PIRP Irp)
Definition at line 467 of file internal.c.
References APC_LEVEL, Executive, FALSE, IoCancelIrp(), KeDelayExecutionThread(), KeLowerIrql, KeRaiseIrql, KeReadStateEvent(), KernelMode, KeWaitForSingleObject(), NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, and VOID.
Referenced by IopQueryXxxInformation(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoSetInformation(), NtQueryInformationFile(), and NtSetInformationFile().
VOID IopCheckBackupRestorePrivilege (IN PACCESS_STATE AccessState, IN OUT PULONG CreateOptions, IN KPROCESSOR_MODE PreviousMode, IN ULONG Disposition)
Definition at line 2517 of file parse.c.
References ACCESS_SYSTEM_SECURITY, _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, DELETE, FALSE, FILE_ADD_FILE, FILE_ADD_SUBDIRECTORY, FILE_GENERIC_READ, FILE_GENERIC_WRITE, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_IF, FILE_OVERWRITE_IF, FILE_TRAVERSE, _LUID_AND_ATTRIBUTES::Luid, MAXIMUM_ALLOWED, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, READ_CONTROL, SE_BACKUP_PRIVILEGES_CHECKED, SeAppendPrivileges(), SeBackupPrivilege, SePrivilegeCheck(), SeRestorePrivilege, TOKEN_HAS_BACKUP_PRIVILEGE, TOKEN_HAS_RESTORE_PRIVILEGE, TRUE, VOID, WRITE_DAC, and WRITE_OWNER.
Referenced by IopParseDevice().
NTSTATUS IopCheckGetQuotaBufferValidity (IN PFILE_GET_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG_PTR ErrorOffset)
Definition at line 574 of file internal.c.
References FIELD_OFFSET, GET_OFFSET_LENGTH, _FILE_GET_QUOTA_INFORMATION::NextEntryOffset, PAGED_CODE, RtlLengthSid(), RtlValidSid(), _FILE_GET_QUOTA_INFORMATION::Sid, STATUS_QUOTA_LIST_INCONSISTENT, STATUS_SUCCESS, and _SID::SubAuthority.
Referenced by NtQueryQuotaInformationFile().
NTSTATUS IopCheckUnloadDriver (IN PDRIVER_OBJECT driverObject, OUT PBOOLEAN unloadDriver)
Definition at line 175 of file loadunld.c.
References DOE_UNLOAD_PENDING, DRVO_BASE_FILESYSTEM_DRIVER, DRVO_UNLOAD_INVOKED, FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, ObDereferenceObject(), STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by IopUnloadDriver().
VOID IopCloseFile (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ULONG GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 51 of file objsup.c.
References APC_LEVEL, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, FALSE, _FAST_IO_DISPATCH::FastIoUnlockAll, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_DIRECT_DEVICE_OPEN, FO_HANDLE_CREATED, FO_SYNCHRONOUS_IO, IoCallDriver(), IoFreeIrp(), IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpMustSucceed(), IopDequeueThreadIrp, IopQueueThreadIrp(), IopReleaseFileObjectLock, IopUpdateOtherOperationCount(), IRP_CLOSE_OPERATION, IRP_MJ_CLEANUP, IRP_MJ_LOCK_CONTROL, IRP_MN_UNLOCK_ALL, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _FILE_OBJECT::LockOperation, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NOTHING, NULL, ObReferenceObject, PAGED_CODE, PIRP, PsGetCurrentProcess(), PsGetCurrentThread(), STATUS_PENDING, SynchronizationEvent, UNREFERENCED_PARAMETER, UserRequest, and VOID.
Referenced by IopCreateObjectTypes(), and IopDeleteFile().
VOID IopCompletePageWrite (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 986 of file internal.c.
References CONTAINING_RECORD, IoFreeIrp(), IRP, NT_ERROR, PIRP, and UNREFERENCED_PARAMETER.
Referenced by IopfCompleteRequest().
VOID IopCompleteRequest (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 1086 of file internal.c.
References ASSERT, _FILE_OBJECT::CompletionContext, CONTAINING_RECORD, CurrentApcEnvironment, _FILE_OBJECT::Event, except, ExFreePool(), FALSE, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_SYNCHRONOUS_IO, IO_REPARSE_TAG_MOUNT_POINT, IoFreeIrp(), IoFreeMdl(), IopCompletionPacketIrp, IopDequeueThreadIrp, IopDoNameTransmogrify(), IopExceptionFilter(), IopKernelPointerBit, IopUpdateOtherTransferCount(), IopUpdateReadTransferCount(), IopUpdateWriteTransferCount(), IopUserCompletion(), IopUserRundown(), IOVP_COMPLETE_REQUEST, IRP, IRP_BUFFERED_IO, IRP_CREATE_OPERATION, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_OB_QUERY_NAME, IRP_READ_OPERATION, IRP_RETRY_IO_COMPLETION, IRP_SYNCHRONOUS_API, IRP_WRITE_OPERATION, KeInitializeApc(), KeInsertQueue(), KeInsertQueueApc(), KeMemoryBarrierWithoutFence, KeSetEvent(), _IO_COMPLETION_CONTEXT::Key, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, _MDL::Next, NT_ERROR, NULL, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), PIRP, _IO_COMPLETION_CONTEXT::Port, PsGetCurrentThread(), _REPARSE_DATA_BUFFER::ReparseDataLength, _REPARSE_DATA_BUFFER::ReparseTag, _REPARSE_DATA_BUFFER::Reserved, RtlCopyMemory, STATUS_MULTIPLE_FAULT_VIOLATION, STATUS_REPARSE, STATUS_SUCCESS, STATUS_VERIFY_REQUIRED, SynchronousIo, _ETHREAD::Tcb, TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by IopAbortRequest(), IopfCompleteRequest(), IopSynchronousServiceTail(), IoRetryIrpCompletions(), NtQueryInformationFile(), and NtSetInformationFile().
VOID IopCompleteUnloadOrDelete (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN OnCleanStack, IN KIRQL Irql)
Definition at line 707 of file internal.c.
References ASSERT, DelayedWorkQueue, _DEVOBJ_EXTENSION::DeviceNode, _DRIVER_OBJECT::DeviceObject, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_UNLOAD_PENDING, _LOAD_PACKET::DriverObject, DRVO_BASE_FILESYSTEM_DRIVER, DRVO_UNLOAD_INVOKED, _LOAD_PACKET::Event, Executive, ExInitializeWorkItem, ExQueueWorkItem(), _DEVOBJ_EXTENSION::ExtensionFlags, FALSE, _FAST_IO_DISPATCH::FastIoDetachDevice, FIELD_OFFSET, _DRIVER_OBJECT::Flags, IopChainDereferenceComplete(), IopGetDeviceAttachmentBase(), IopInsertRemoveDevice(), IopLoadUnloadDriver(), KeAcquireQueuedSpinLock(), KeInitializeEvent(), KeReleaseQueuedSpinLock(), KernelMode, KeWaitForSingleObject(), LockQueueIoDatabaseLock, NotificationEvent, NULL, ObDereferenceObject(), ObDereferenceSecurityDescriptor(), ObMakeTemporaryObject(), _FAST_IO_DISPATCH::SizeOfFastIoDispatch, TRUE, VOID, and _LOAD_PACKET::WorkQueueItem.
Referenced by IoDeleteDevice(), IoDetachDevice(), and IopDecrementDeviceObjectRef().
BOOLEAN IopConfigureCrashDump (IN HANDLE HandlePagingFile)
VOID IopConnectLinkTrackingPort (IN PVOID Parameter)
Definition at line 1572 of file internal.c.
References _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, _LINK_TRACKING_PACKET::Event, FALSE, _LINK_TRACKING_PACKET::FinalStatus, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, IopLinkTrackingServiceEvent, IopLinkTrackingServiceObject, KeReadStateEvent(), KernelMode, KeSetEvent(), LpcPortObjectType, MESSAGE_SIZE, NT_SUCCESS, NtClose(), NtConnectPort(), NULL, ObReferenceObjectByHandle, PAGED_CODE, RtlInitUnicodeString(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and TRUE.
Referenced by IopSendMessageToTrackService().
NTSTATUS IopCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN ULONG InternalFlags, IN PVOID DeviceObject)
Definition at line 4948 of file iosubs.c.
References _OPEN_PACKET::AllocationSize, ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, _NAMED_PIPE_CREATE_PARAMETERS::CompletionMode, _OPEN_PACKET::CreateFileType, CreateFileTypeMailslot, CreateFileTypeNamedPipe, CreateFileTypeNone, _OPEN_PACKET::CreateOptions, DELETE, _OPEN_PACKET::DeleteOnly, _FILE_OBJECT::DeviceObject, _OPEN_PACKET::Disposition, _OPEN_PACKET::EaBuffer, _OPEN_PACKET::EaLength, ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), _OPEN_PACKET::ExtraCreateParameters, FALSE, FILE_APPEND_DATA, FILE_ATTRIBUTE_VALID_FLAGS, FILE_COMPLETE_IF_OPLOCKED, FILE_CREATE, FILE_DELETE_ON_CLOSE, FILE_DIRECTORY_FILE, FILE_MAXIMUM_DISPOSITION, FILE_NO_COMPRESSION, FILE_NO_INTERMEDIATE_BUFFERING, FILE_NON_DIRECTORY_FILE, FILE_OPEN, FILE_OPEN_BY_FILE_ID, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_FOR_FREE_SPACE_QUERY, FILE_OPEN_IF, FILE_OPEN_REPARSE_POINT, FILE_PIPE_COMPLETE_OPERATION, FILE_PIPE_MESSAGE_MODE, FILE_PIPE_MESSAGE_TYPE, FILE_RESERVE_OPFILTER, FILE_SHARE_DELETE, FILE_SHARE_VALID_FLAGS, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_ALERT, FILE_SYNCHRONOUS_IO_NONALERT, FILE_VALID_MAILSLOT_OPTION_FLAGS, FILE_VALID_OPTION_FLAGS, FILE_VALID_PIPE_OPTION_FLAGS, FILE_WRITE_THROUGH, _OPEN_PACKET::FileAttributes, _FILE_OBJECT::FileName, _OPEN_PACKET::FileObject, _OPEN_PACKET::FinalStatus, _FILE_OBJECT::Flags, FO_HANDLE_CREATED, _OPEN_PACKET::Information, _OPEN_PACKET::InternalFlags, IO_ATTACH_DEVICE, IO_ATTACH_DEVICE_API, IO_CHECK_CREATE_PARAMETERS, IO_NO_PARAMETER_CHECKING, IO_REPARSE_TAG_MOUNT_POINT, IO_TYPE_FILE, IO_TYPE_OPEN_PACKET, IoCheckEaBufferValidity(), IopAllocateOpenPacket, IopFailZeroAccessCreate, IopFreeOpenPacket, IopUpdateOtherOperationCount(), KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _NAMED_PIPE_CREATE_PARAMETERS::NamedPipeType, NonPagedPool, NOTHING, NT_SUCCESS, NT_WARNING, NULL, ObDereferenceObject(), ObOpenObjectByName(), OPEN_PACKET_PATTERN, _OPEN_PACKET::Options, _OPEN_PACKET::Override, PAGED_CODE, _OPEN_PACKET::ParseCheck, ProbeAndWriteHandle, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, _LARGE_INTEGER::QuadPart, _OPEN_PACKET::QueryOnly, _NAMED_PIPE_CREATE_PARAMETERS::ReadMode, _OPEN_PACKET::RelatedFileObject, RtlCopyMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE_POINT_NOT_RESOLVED, STATUS_SUCCESS, SYNCHRONIZE, _OPEN_PACKET::TopDeviceObjectHint, _OPEN_PACKET::TraversedMountPoint, _OPEN_PACKET::Type, _FILE_OBJECT::Type, and ZwClose().
Referenced by IoCreateFile(), and IoCreateFileSpecifyDeviceObjectHint().
NTSTATUS IopCreateSecurityDescriptorPerType (IN PSECURITY_DESCRIPTOR Descriptor, IN ULONG SecurityDescriptorFlavor, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
Definition at line 13473 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, DACL_SECURITY_INFORMATION, IO_SD_SYS_ALL_ADM_ALL_WORLD_E, IO_SD_SYS_ALL_ADM_ALL_WORLD_E_RES_E, IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE, IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE_RES_RE, IO_SD_SYS_ALL_ADM_RE, NT_SUCCESS, RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), SECURITY_DESCRIPTOR_REVISION, SePublicDefaultDacl, SePublicDefaultUnrestrictedDacl, SePublicOpenDacl, SePublicOpenUnrestrictedDacl, SeSystemDefaultDacl, STATUS_INVALID_PARAMETER, and TRUE.
Referenced by IopCreateDefaultDeviceSecurityDescriptor().
NTSTATUS IopCreateVpb (IN PDEVICE_OBJECT DeviceObject)
Definition at line 4251 of file iosubs.c.
References ExAllocatePoolWithTag, IO_TYPE_VPB, NonPagedPool, _VPB::RealDevice, RtlZeroMemory, _VPB::Size, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _VPB::Type.
Referenced by IoCreateDevice(), and IoVerifyVolume().
VOID IopDeallocateApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 1826 of file internal.c.
References ExFreePool(), PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by IoRaiseHardError(), and IoRaiseInformationalHardError().
VOID IopDecrementDeviceObjectRef (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AlwaysUnload, IN BOOLEAN OnCleanStack)
Definition at line 4433 of file internal.c.
References ASSERT, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_UNLOAD_PENDING, IopCompleteUnloadOrDelete(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and LockQueueIoDatabaseLock.
Referenced by IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopCheckVpbMounted(), IopDecrementDeviceObjectHandleCount(), IopDeleteFile(), IopLoadFileSystemDriver(), IopParseDevice(), and IopShutdownBaseFileSystems().
VOID IopDeleteDevice (IN PVOID Object)
Definition at line 824 of file objsup.c.
References ASSERT, ASSERTMSG, ExFreePool(), _VPB::Flags, InterlockedExchangePointer, IopDestroyDeviceNode(), NULL, ObDereferenceObject(), PAGED_CODE, _VPB::ReferenceCount, VPB_LOCKED, and VPB_MOUNTED.
Referenced by IopCreateObjectTypes().
VOID IopDeleteDriver (IN PVOID Object)
Definition at line 738 of file objsup.c.
References ASSERT, _UNICODE_STRING::Buffer, _DRIVER_EXTENSION::ClientDriverExtension, _DRIVER_OBJECT::DeviceObject, _DRIVER_OBJECT::DriverExtension, _DRIVER_OBJECT::DriverName, _DRIVER_OBJECT::DriverSection, ExFreePool(), _DRIVER_EXTENSION::FsFilterCallbacks, KeFlushQueuedDpcs(), MmUnloadSystemImage(), _IO_CLIENT_EXTENSION::NextExtension, NULL, PAGED_CODE, PpDriverObjectDereferenceComplete(), and _DRIVER_EXTENSION::ServiceKeyName.
Referenced by IopCreateObjectTypes().
VOID IopDeleteFile (IN PVOID Object)
Definition at line 435 of file objsup.c.
References APC_LEVEL, ASSERT, _UNICODE_STRING::Buffer, _FILE_OBJECT::Busy, _FILE_OBJECT::CompletionContext, _VPB::DeviceObject, _FILE_OBJECT::DeviceObject, DO_NEVER_LAST_DEVICE, _FILE_OBJECT::Event, Executive, ExFreePool(), FALSE, _FILE_OBJECT::FileName, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_DIRECT_DEVICE_OPEN, FO_FILE_OBJECT_HAS_EXTENSION, FO_FILE_OPEN_CANCELLED, FO_HANDLE_CREATED, FO_SYNCHRONOUS_IO, FsRtlPTeardownPerFileObjectContexts(), InterlockedExchange(), IoAllocateIrp(), IoCallDriver(), IoFreeIrp(), IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAllocateIrpMustSucceed(), IopCloseFile(), IopDecrementDeviceObjectRef(), IopDequeueThreadIrp, IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopQueueThreadIrp(), IRP_CLOSE_OPERATION, IRP_MJ_CLOSE, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, LockQueueIoDatabaseLock, LockQueueIoVpbLock, _IO_STACK_LOCATION::MajorFunction, NULL, ObDereferenceObject(), ObIsObjectDeletionInline(), PIRP, _IO_COMPLETION_CONTEXT::Port, PsGetCurrentThread(), _VPB::ReferenceCount, STATUS_PENDING, SynchronizationEvent, TRUE, VOID, and _FILE_OBJECT::Vpb.
Referenced by IopCreateObjectTypes(), and IopParseDevice().
VOID IopDeleteIoCompletion (IN PVOID Object)
Definition at line 855 of file complete.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, IoFreeIrp(), IopCompletionPacketIrp, IopFreeMiniPacket(), IRP, KeRundownQueue(), NULL, _IOP_MINI_COMPLETION_PACKET::PacketType, and PIRP.
Referenced by IopCreateObjectTypes().
VOID IopDereferenceVpbAndFree (IN PVPB Vpb)
Definition at line 211 of file parse.c.
References ExFreePool(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoVpbLock, NULL, and VPB_PERSISTENT.
Referenced by IopParseDevice(), and IoVerifyVolume().
VOID IopDisassociateThreadIrp (VOID)
Definition at line 1689 of file internal.c.
References APC_LEVEL, CONTAINING_RECORD, _IO_STACK_LOCATION::DeviceObject, _IO_ERROR_LOG_PACKET::ErrorCode, _LIST_ENTRY::Flink, InitializeListHead(), IO_DRIVER_CANCEL_TIMEOUT, IoAllocateErrorLogEntry(), IoGetCurrentIrpStackLocation, IopDeadIrp, IoWriteErrorLogEntry(), IRP, _ETHREAD::IrpList, IsListEmpty, KeAcquireQueuedSpinLock(), KeLowerIrql, KeRaiseIrql, KeReleaseQueuedSpinLock(), LockQueueIoCompletionLock, NULL, PIRP, PsGetCurrentThread(), and RemoveHeadList().
Referenced by IoCancelThreadIo().
BOOLEAN IopDmaDispatch (IN PKINTERRUPT Interrupt, IN PVOID ServiceContext)
VOID IopDoNameTransmogrify (IN PIRP Irp, IN PFILE_OBJECT FileObject, IN PREPARSE_DATA_BUFFER ReparseBuffer)
Definition at line 8776 of file iosubs.c.
References ASSERT, ExAllocatePoolWithTag, ExFreePool(), FIELD_OFFSET, IO_REPARSE_TAG_MOUNT_POINT, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, MAXUSHORT, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _REPARSE_DATA_BUFFER::PathBuffer, REPARSE_DATA_BUFFER_HEADER_SIZE, RtlCopyMemory, RtlMoveMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_IO_REPARSE_DATA_INVALID, STATUS_NAME_TOO_LONG, STATUS_REPARSE, and UNICODE_NULL.
Referenced by IopCompleteRequest(), and IopParseDevice().
VOID IopDropIrp (IN PIRP Irp, IN PFILE_OBJECT FileObject)
Definition at line 1876 of file internal.c.
References ExFreePool(), IoFreeIrp(), IoFreeMdl(), IRP_CREATE_OPERATION, IRP_DEALLOCATE_BUFFER, IRP_SYNCHRONOUS_API, _MDL::Next, ObDereferenceObject(), and ObDereferenceObjectEx().
Referenced by IopfCompleteRequest().
VOID IopErrorLogThread (IN PVOID StartContext)
Definition at line 87 of file errorlog.c.
References _UNICODE_STRING::Buffer, CONTAINING_RECORD, _ERROR_LOG_ENTRY::DeviceObject, _IO_ERROR_LOG_MESSAGE::DriverNameLength, _IO_ERROR_LOG_MESSAGE::DriverNameOffset, _ERROR_LOG_ENTRY::DriverObject, _IO_ERROR_LOG_MESSAGE::EntryData, ErrorLogPort, ExAllocatePool, ExFreePool(), FIELD_OFFSET, InterlockedExchangeAdd(), IO_ERROR_LOG, IO_ERROR_LOG_MESSAGE_LENGTH, IO_ERROR_NAME_LENGTH, IO_TYPE_ERROR_MESSAGE, ELF_PORT_MSG::IoErrorLogMessage, IopErrorLogAllocation, IopErrorLogConnectPort(), IopErrorLogGetEntry(), IopErrorLogQueueRequest(), IopErrorLogRequeueEntry(), _UNICODE_STRING::Length, _ERROR_LOG_ENTRY::ListEntry, ELF_PORT_MSG::MessageType, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NtClose(), NtRequestPort(), NULL, _IO_ERROR_LOG_PACKET::NumberOfStrings, ObDereferenceObject(), ObQueryNameString(), PAGED_CODE, PagedPool, ELF_PORT_MSG::PortMessage, RtlCopyMemory, RtlZeroMemory, _PORT_MESSAGE::s1, _IO_ERROR_LOG_MESSAGE::Size, _ERROR_LOG_ENTRY::Size, STATUS_INFO_LENGTH_MISMATCH, _IO_ERROR_LOG_PACKET::StringOffset, _IO_ERROR_LOG_MESSAGE::TimeStamp, _ERROR_LOG_ENTRY::TimeStamp, _IO_ERROR_LOG_MESSAGE::Type, ELF_PORT_MSG::u, _PORT_MESSAGE::u1, UNREFERENCED_PARAMETER, and wcslen().
Referenced by IopErrorLogDpc(), and IoWriteErrorLogEntry().
VOID IopExceptionCleanup (IN PFILE_OBJECT FileObject, IN PIRP Irp, IN PKEVENT EventObject OPTIONAL, IN PKEVENT KernelEvent OPTIONAL)
Definition at line 1989 of file internal.c.
References ARGUMENT_PRESENT, ExFreePool(), FO_SYNCHRONOUS_IO, IoFreeIrp(), IoFreeMdl(), IopReleaseFileObjectLock, NULL, ObDereferenceObject(), and PAGED_CODE.
Referenced by BuildQueryDirectoryIrp(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
LONG IopExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointers, OUT PNTSTATUS ExceptionCode)
Definition at line 1938 of file internal.c.
References EXCEPTION_EXECUTE_HANDLER, STATUS_DATATYPE_MISALIGNMENT, STATUS_DATATYPE_MISALIGNMENT_ERROR, and STATUS_IN_PAGE_ERROR.
Referenced by IopCompleteRequest(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
NTSTATUS FORCEINLINE IopfCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
Definition at line 1597 of file iomgr.h.
References ASSERT, _IO_STACK_LOCATION::DeviceObject, IO_TYPE_IRP, IoGetNextIrpStackLocation, KiBugCheck3, _DRIVER_OBJECT::MajorFunction, _IO_STACK_LOCATION::MajorFunction, and NO_MORE_IRP_STACK_LOCATIONS.
Referenced by IofCallDriver(), and IofCallDriverSpecifyReturn().
VOID FASTCALL IopfCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBost)
Definition at line 3339 of file iosubs.c.
References ASSERT, _IO_STACK_LOCATION::CompletionRoutine, _IO_STACK_LOCATION::Context, _IO_STACK_LOCATION::Control, ExFreePool(), IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_RESERVED_RANGE, IO_TYPE_IRP, IoCompleteRequest(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoMarkIrpPending, IopAbortRequest(), IopCompletePageWrite(), IopCompleteRequest(), IopDropIrp(), IopFreeIrpAndMdls(), IopFreeReserveIrp(), IopInterlockedDecrementUlong(), IopIsReserveIrp, IRP, IRP_ASSOCIATED_IRP, IRP_CLOSE_OPERATION, IRP_DEFER_IO_COMPLETION, IRP_PAGING_IO, IRP_SET_USER_EVENT, IRP_SYNCHRONOUS_PAGING_IO, KeAcquireQueuedSpinLock(), KeBugCheckEx(), KeInitializeApc(), KeInsertQueueApc(), KeReleaseQueuedSpinLock(), KernelMode, KeSetEvent(), LockQueueIoCompletionLock, LockQueueIoDatabaseLock, MmUnlockPages(), MULTIPLE_IRP_COMPLETE_REQUESTS, _MDL::Next, NT_SUCCESS, NULL, _IO_STACK_LOCATION::Parameters, PIRP, SL_ERROR_RETURNED, SL_INVOKE_ON_CANCEL, SL_INVOKE_ON_ERROR, SL_INVOKE_ON_SUCCESS, SL_PENDING_RETURNED, STATUS_IO_REPARSE_TAG_NOT_HANDLED, STATUS_MORE_PROCESSING_REQUIRED, STATUS_PENDING, STATUS_REPARSE, STATUS_SUCCESS, _ETHREAD::Tcb, VOID, and ZeroIrpStackLocation.
Referenced by IopSetIoRoutines().
VOID IopFreeIrp (IN PIRP Irp)
Definition at line 7144 of file iosubs.c.
References ASSERT, ExFreePool(), ExQueryDepthSList, ExReturnPoolQuota(), InterlockedIncrement, InterlockedPushEntrySList(), IO_TYPE_IRP, IopIrpAutoSizingEnabled, IopLargeIrpStackLocations, IoSizeOfIrp, IRP_ALLOCATED_FIXED_SIZE, IRP_ALLOCATED_MUST_SUCCEED, IRP_LOOKASIDE_ALLOCATION, IRP_QUOTA_CHARGED, IsListEmpty, KeBugCheckEx(), KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, _KPRCB::LookasideIrpFloat, LookasideLargeIrpList, LookasideSmallIrpList, MULTIPLE_IRP_COMPLETE_REQUESTS, _PP_LOOKASIDE_LIST::P, _KPRCB::PPLookasideList, PSLIST_ENTRY, and _GENERAL_LOOKASIDE::TotalFrees.
Referenced by IopSetIoRoutines().
VOID IopFreeIrpAndMdls (IN PIRP Irp)
Definition at line 2084 of file internal.c.
References IoFreeIrp(), IoFreeMdl(), _MDL::Next, and NULL.
Referenced by IopfCompleteRequest().
VOID IopFreeReserveIrp (IN CCHAR PriorityBoost)
Definition at line 10327 of file internal.c.
References _IOP_RESERVE_IRP_ALLOCATOR::Event, FALSE, InterlockedExchange(), IopReserveIrpAllocator, _IOP_RESERVE_IRP_ALLOCATOR::IrpAllocated, and KeSetEvent().
Referenced by IopfCompleteRequest().
NTSTATUS IopGetBasicInformationFile (IN PFILE_OBJECT FileObject, IN PFILE_BASIC_INFORMATION BasicInformationBuffer)
Definition at line 10352 of file internal.c.
References FALSE, _FAST_IO_DISPATCH::FastIoQueryBasicInfo, FileBasicInformation, FO_SYNCHRONOUS_IO, IoGetRelatedDeviceObject(), IopGetFileInformation(), PAGED_CODE, _IO_STATUS_BLOCK::Status, and TRUE.
Referenced by IopOpenLinkOrRenameTarget().
PDEVICE_OBJECT IopGetDeviceAttachmentBase (IN PDEVICE_OBJECT DeviceObject)
Definition at line 4384 of file internal.c.
References _DEVOBJ_EXTENSION::AttachedTo, and NULL.
Referenced by IoGetDeviceAttachmentBaseRef(), IopCompleteUnloadOrDelete(), IopGetDevicePDO(), and IopVerifyDriverObjectOnStack().
NTSTATUS IopGetDriverPathInformation (IN PFILE_OBJECT FileObject, IN PFILE_FS_DRIVER_PATH_INFORMATION FsDpInfo, IN ULONG Length)
Definition at line 10588 of file internal.c.
References _UNICODE_STRING::Buffer, FIELD_OFFSET, IoDriverObjectType, IopVerifyDriverObjectOnStack(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), KernelMode, _UNICODE_STRING::Length, LockQueueIoDatabaseLock, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByName(), STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by NtQueryVolumeInformationFile().
NTSTATUS IopGetFileInformation (IN PFILE_OBJECT FileObject, IN ULONG Length, IN FILE_INFORMATION_CLASS FileInformationClass, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
Definition at line 2315 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STATUS_BLOCK::Information, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopQueueThreadIrp(), IRP_BUFFERED_IO, IRP_MJ_QUERY_INFORMATION, IRP_OB_QUERY_NAME, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, SynchronizationEvent, and VOID.
Referenced by IopGetBasicInformationFile(), and IopQueryNameInternal().
BOOLEAN IopGetMountFlag (IN PDEVICE_OBJECT DeviceObject)
Definition at line 2474 of file internal.c.
References FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoVpbLock, TRUE, and VPB_MOUNTED.
Referenced by NtQueryVolumeInformationFile().
NTSTATUS IopGetRegistryValues (IN HANDLE KeyHandle, IN PKEY_VALUE_FULL_INFORMATION * ValueList)
Definition at line 2733 of file internal.c.
References IopGetRegistryValue(), NT_SUCCESS, NULL, PAGED_CODE, STATUS_OBJECT_NAME_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS IopGetSetObjectId (IN PFILE_OBJECT FileObject, IN OUT PVOID Buffer, IN ULONG Length, IN ULONG OperationFlags)
Definition at line 2814 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, FSCTL_LMR_GET_LINK_TRACKING_INFORMATION, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_KERNEL_CALL, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NULL, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by IopTrackLink().
NTSTATUS IopGetSetSecurityObject (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 1167 of file objsup.c.
References AssignSecurityDescriptor, DeleteSecurityDescriptor, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExReleaseResourceLite(), FALSE, _FILE_OBJECT::FileName, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_STREAM_FILE, FO_SYNCHRONOUS_IO, _IO_STATUS_BLOCK::Information, IO_TYPE_DEVICE, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopGetDevicePDO(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IopSecurityResource, IopSetDeviceSecurityDescriptor(), IopSetDeviceSecurityDescriptors(), IopUpdateOtherOperationCount(), IRP_MJ_QUERY_SECURITY, IRP_MJ_SET_SECURITY, IRP_SYNCHRONOUS_API, KeClearEvent(), KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, _IO_STACK_LOCATION::MajorFunction, NT_SUCCESS, NULL, ObDereferenceObject(), ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), ObReferenceObject, ObReferenceSecurityDescriptor(), PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), QuerySecurityDescriptor, _FILE_OBJECT::RelatedFileObject, SeAssignWorldSecurityDescriptor(), SeQuerySecurityDescriptorInfo(), SetSecurityDescriptor, _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_PENDING, STATUS_SUCCESS, SynchronizationEvent, _ETHREAD::Tcb, TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by IopCreateObjectTypes().
NTSTATUS IopGetVolumeId (IN PFILE_OBJECT FileObject, IN OUT PLINK_TRACKING_INFORMATION ObjectId, IN ULONG Length)
Definition at line 2947 of file internal.c.
References ASSERT, Executive, FALSE, FileFsObjectIdInformation, _IO_STACK_LOCATION::FileObject, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NtfsLinkTrackingInformation, NULL, _FILE_FS_OBJECTID_INFORMATION::ObjectId, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and UNREFERENCED_PARAMETER.
Referenced by IopTrackLink().
VOID IopHardErrorThread (PVOID StartContext)
NTSTATUS IopInitializeIrpStackProfiler (VOID)
Definition at line 10719 of file internal.c.
References _IOP_IRP_STACK_PROFILER::Dpc, IOP_PROFILE_TIME_PERIOD, IopIrpStackProfiler, IopIrpStackProfilerTimer(), KeInitializeDpc(), KeInitializeTimer(), KeSetTimerEx(), MAX_LOOKASIDE_IRP_STACK_COUNT, _IOP_IRP_STACK_PROFILER::Profile, _LARGE_INTEGER::QuadPart, RtlZeroMemory, STATUS_SUCCESS, _IOP_IRP_STACK_PROFILER::Timer, and _IOP_IRP_STACK_PROFILER::TriggerCount.
Referenced by IoInitSystem().
BOOLEAN IopInitializeReserveIrp (PIOP_RESERVE_IRP_ALLOCATOR Allocator)
Definition at line 3512 of file ioinit.c.
References _IOP_RESERVE_IRP_ALLOCATOR::Event, FALSE, IoAllocateIrp(), _IOP_RESERVE_IRP_ALLOCATOR::IrpAllocated, KeInitializeEvent(), MAX_RESERVE_IRP_STACK_SIZE, NULL, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrp, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrpStackSize, SynchronizationEvent, and TRUE.
Referenced by IoInitSystem().
VOID IopInsertRemoveDevice (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Insert)
Definition at line 4224 of file iosubs.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and LockQueueIoDatabaseLock.
Referenced by IoCreateDevice(), and IopCompleteUnloadOrDelete().
ULONG FASTCALL IopInterlockedDecrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
Definition at line 10035 of file internal.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and UNREFERENCED_PARAMETER.
Referenced by IopDeleteFile(), IopfCompleteRequest(), IopMountVolume(), IoUnregisterFileSystem(), and IoVerifyVolume().
ULONG FASTCALL IopInterlockedIncrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
Definition at line 10077 of file internal.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and UNREFERENCED_PARAMETER.
Referenced by IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopDeleteFile(), IopIncrementDeviceObjectHandleCount(), IopMountVolume(), IopParseDevice(), IopShutdownBaseFileSystems(), and IoRegisterFileSystem().
PLIST_ENTRY FASTCALL IopInterlockedInsertHeadList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
Definition at line 9904 of file internal.c.
References _LIST_ENTRY::Flink, InsertHeadList(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
Referenced by IoRegisterLastChanceShutdownNotification(), and IoRegisterShutdownNotification().
PLIST_ENTRY FASTCALL IopInterlockedInsertTailList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
Definition at line 9948 of file internal.c.
References _LIST_ENTRY::Blink, InsertTailList(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
Referenced by IoRegisterBootDriverReinitialization(), and IoRegisterDriverReinitialization().
PLIST_ENTRY FASTCALL IopInterlockedRemoveHeadList (IN PLIST_ENTRY ListHead)
Definition at line 9992 of file internal.c.
References _LIST_ENTRY::Flink, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and RemoveEntryList().
Referenced by IopCallBootDriverReinitializationRoutines(), IopCallDriverReinitializationRoutines(), and IoShutdownSystem().
VOID IopIrpStackProfilerTimer (IN struct _KDPC * Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 10753 of file internal.c.
References _IOP_IRP_STACK_PROFILER::Flags, IOP_PROFILE_STACK_COUNT, IOP_PROFILE_TRIGGER_INTERVAL, IopProcessIrpStackProfiler(), MAX_LOOKASIDE_IRP_STACK_COUNT, NUM_SAMPLE_IRPS, _IOP_IRP_STACK_PROFILER::Profile, _IOP_IRP_STACK_PROFILER::TriggerCount, and UNREFERENCED_PARAMETER.
Referenced by IopInitializeIrpStackProfiler().
LOGICAL IopIsSameMachine (IN PFILE_OBJECT SourceFile, IN HANDLE TargetFile)
Definition at line 3274 of file internal.c.
References _FAST_IO_DISPATCH::FastIoDeviceControl, IOCTL_LMR_ARE_FILE_OBJECTS_ON_SAME_SERVER, IoGetRelatedDeviceObject(), NULL, PAGED_CODE, _IO_STATUS_BLOCK::Status, STATUS_NOT_SAME_DEVICE, STATUS_SUCCESS, and TRUE.
Referenced by IopTrackLink().
VOID IopLoadFileSystemDriver (IN PDEVICE_OBJECT DeviceObject)
Definition at line 4492 of file internal.c.
References Executive, FALSE, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IopDecrementDeviceObjectRef(), IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_LOAD_FILE_SYSTEM, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NULL, PAGED_CODE, PIRP, STATUS_PENDING, TRUE, and VOID.
Referenced by IopMountVolume().
VOID IopLoadUnloadDriver (IN PVOID Parameter)
Definition at line 4584 of file internal.c.
References _LOAD_PACKET::DriverObject, _LOAD_PACKET::DriverServiceName, _DRIVER_OBJECT::DriverUnload, _LOAD_PACKET::Event, FALSE, _LOAD_PACKET::FinalStatus, IopCallDriverReinitializationRoutines(), IopLoadDriver(), IopOpenRegistryKey(), KeSetEvent(), KEY_READ, NT_SUCCESS, NULL, PAGED_CODE, STATUS_DRIVER_FAILED_PRIOR_UNLOAD, STATUS_FAILED_DRIVER_ENTRY, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, and VOID.
Referenced by IopCompleteUnloadOrDelete(), IopUnloadDriver(), and NtLoadDriver().
NTSTATUS IopLogErrorEvent (IN ULONG SequenceNumber, IN ULONG UniqueErrorValue, IN NTSTATUS FinalStatus, IN NTSTATUS SpecificIOStatus, IN ULONG LengthOfInsert1, IN PWCHAR Insert1, IN ULONG LengthOfInsert2, IN PWCHAR Insert2)
Definition at line 3397 of file ioinit.c.
References _IO_ERROR_LOG_PACKET::DumpData, _IO_ERROR_LOG_PACKET::DumpDataSize, _IO_ERROR_LOG_PACKET::ErrorCode, _IO_ERROR_LOG_PACKET::FinalStatus, IoAllocateErrorLogEntry(), IopErrorLogObject, IoWriteErrorLogEntry(), _IO_ERROR_LOG_PACKET::MajorFunctionCode, NULL, _IO_ERROR_LOG_PACKET::NumberOfStrings, _IO_ERROR_LOG_PACKET::RetryCount, RtlCopyMemory, _IO_ERROR_LOG_PACKET::SequenceNumber, STATUS_INVALID_HANDLE, STATUS_NO_DATA_DETECTED, STATUS_SUCCESS, _IO_ERROR_LOG_PACKET::StringOffset, and _IO_ERROR_LOG_PACKET::UniqueErrorValue.
NTSTATUS IopLookupBusStringFromID (IN HANDLE KeyHandle, IN INTERFACE_TYPE InterfaceType, OUT PWCHAR Buffer, IN ULONG Length, OUT PULONG BusFlags OPTIONAL)
Definition at line 9225 of file internal.c.
References ARGUMENT_PRESENT, _KEY_VALUE_FULL_INFORMATION::DataOffset, Index, KeyValueFullInformation, _KEY_VALUE_FULL_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::NameLength, NT_SUCCESS, PAGED_CODE, REG_BINARY, STATUS_SUCCESS, _KEY_VALUE_FULL_INFORMATION::Type, and ZwEnumerateValueKey().
NTSTATUS IopMountVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount, IN BOOLEAN DeviceLockAlreadyHeld, IN BOOLEAN Alertable, OUT PVPB * Vpb)
Definition at line 4684 of file internal.c.
References CONTAINING_RECORD, DEVICE_OBJECT, DO_SYSTEM_BOOT_PARTITION, DO_VERIFY_VOLUME, ExAcquireResourceSharedLite(), Executive, ExReleaseResourceLite(), FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_DISK, FILE_DEVICE_VIRTUAL_DISK, _IO_STACK_LOCATION::Flags, _LIST_ENTRY::Flink, FsRtlIsTotalDeviceFailure(), _IO_STATUS_BLOCK::Information, InitializationPhase, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoIsErrorUserInduced, IOP_ABORT, IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopFsRegistrationOps, IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopLoadFileSystemDriver(), IopMountInitializeVpb(), IopTapeFileSystemQueueHead, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_MOUNT_VOLUME, IRP_MOUNT_COMPLETION, IRP_SYNCHRONOUS_PAGING_IO, KeBugCheckEx(), KeClearEvent(), KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LockQueueIoDatabaseLock, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_DEVICE_DOES_NOT_EXIST, STATUS_FS_DRIVER_REQUIRED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, STATUS_UNRECOGNIZED_VOLUME, STATUS_UNSUCCESSFUL, STATUS_USER_APC, _ETHREAD::Tcb, TRUE, UNMOUNTABLE_BOOT_VOLUME, VOID, VPB_MOUNTED, VPB_RAW_MOUNT, and VPB_REMOVE_PENDING.
Referenced by IopCheckVpbMounted(), and IoVerifyVolume().
VOID IopNotifyAlreadyRegisteredFileSystems (IN PLIST_ENTRY ListHead, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine, IN BOOLEAN SkipRaw)
Definition at line 10132 of file iosubs.c.
References CONTAINING_RECORD, DEVICE_OBJECT, _LIST_ENTRY::Flink, and TRUE.
Referenced by IoRegisterFsRegistrationChange().
NTSTATUS IopOpenLinkOrRenameTarget (OUT PHANDLE TargetHandle, IN PIRP Irp, IN PVOID RenameBuffer, IN PFILE_OBJECT FileObject)
Definition at line 5430 of file internal.c.
References ASSERT, _UNICODE_STRING::Buffer, CreateFileTypeNone, FIELD_OFFSET, FILE_ADD_SUBDIRECTORY, FILE_ATTRIBUTE_DIRECTORY, FILE_EXISTS, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_DATA, _FILE_BASIC_INFORMATION::FileAttributes, FileLinkInformation, _FILE_RENAME_INFORMATION::FileName, _FILE_RENAME_INFORMATION::FileNameLength, FO_DIRECT_DEVICE_OPEN, FO_FILE_OBJECT_HAS_EXTENSION, FO_OPENED_CASE_SENSITIVE, _IO_STATUS_BLOCK::Information, InitializeObjectAttributes, IO_FORCE_ACCESS_CHECK, IO_NO_PARAMETER_CHECKING, IO_OPEN_TARGET_DIRECTORY, IoCreateFile(), IoCreateFileSpecifyDeviceObjectHint(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT, IopGetBasicInformationFile(), KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, STATUS_NOT_SAME_DEVICE, STATUS_OBJECT_NAME_COLLISION, STATUS_SUCCESS, SYNCHRONIZE, and _IOP_FILE_OBJECT_EXTENSION::TopDeviceObjectHint.
Referenced by IoSetInformation(), and NtSetInformationFile().
NTSTATUS IopOpenRegistryKey (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess, IN BOOLEAN Create)
Definition at line 5684 of file internal.c.
References InitializeObjectAttributes, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_OPTION_VOLATILE, ZwCreateKey(), and ZwOpenKey().
Referenced by IopBootLog(), IopCopyBootLogRegistryToFile(), IopLoadUnloadDriver(), IopSafebootDriverLoad(), and IopUnloadDriver().
NTSTATUS IopParseDevice (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 304 of file parse.c.
References ACCESS_SYSTEM_SECURITY, _IO_SECURITY_CONTEXT::AccessState, _OPEN_PACKET::AllocationSize, APC_LEVEL, ASSERT, _OPEN_PACKET::BasicInformation, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, _IO_STACK_LOCATION::Control, _OPEN_PACKET::CreateFileType, CreateFileTypeNamedPipe, CreateFileTypeNone, _OPEN_PACKET::CreateOptions, _FILE_OBJECT::CurrentByteOffset, _OPEN_PACKET::DeleteOnly, _IO_SECURITY_CONTEXT::DesiredAccess, _VPB::DeviceObject, _FILE_OBJECT::DeviceObject, _IO_STACK_LOCATION::DeviceObject, _OPEN_PACKET::Disposition, DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN, _OPEN_PACKET::EaBuffer, _OPEN_PACKET::EaLength, _FILE_OBJECT::Event, ExAcquireResourceSharedLite(), ExAllocatePool, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExReleaseResourceLite(), _OPEN_PACKET::ExtraCreateParameters, FALSE, _FAST_IO_DISPATCH::FastIoQueryBasicInfo, _FAST_IO_DISPATCH::FastIoQueryNetworkOpenInfo, _FAST_IO_DISPATCH::FastIoQueryOpen, FIELD_OFFSET, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_SECURE_OPEN, FILE_DEVICE_TAPE, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_DEVICE_VIRTUAL_DISK, FILE_NO_INTERMEDIATE_BUFFERING, FILE_RANDOM_ACCESS, FILE_READ_ATTRIBUTES, FILE_SEQUENTIAL_ONLY, FILE_SYNCHRONOUS_IO_ALERT, FILE_SYNCHRONOUS_IO_NONALERT, FILE_TRAVERSE, FILE_WRITE_THROUGH, _OPEN_PACKET::FileAttributes, _FILE_BASIC_INFORMATION::FileAttributes, _FILE_NETWORK_OPEN_INFORMATION::FileAttributes, FileBasicInformation, _FILE_OBJECT::FileName, FileNetworkOpenInformation, _OPEN_PACKET::FileObject, _IO_STACK_LOCATION::FileObject, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, _IOP_FILE_OBJECT_EXTENSION::FilterContext, _OPEN_PACKET::FinalStatus, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, FO_FILE_OPEN_CANCELLED, FO_NO_INTERMEDIATE_BUFFERING, FO_OPENED_CASE_SENSITIVE, FO_RANDOM_ACCESS, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, FO_VOLUME_OPEN, FO_WRITE_THROUGH, _OPEN_PACKET::FullAttributes, _IO_SECURITY_CONTEXT::FullCreateOptions, _OBJECT_TYPE_INITIALIZER::GenericMapping, _KEVENT::Header, _OPEN_PACKET::Information, _IO_STATUS_BLOCK::Information, InitializeObjectAttributes, _OPEN_PACKET::InternalFlags, IO_FORCE_ACCESS_CHECK, IO_MAX_REMOUNT_REPARSE_ATTEMPTS, IO_REMOUNT, IO_REPARSE, IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_RESERVED_ONE, IO_REPARSE_TAG_RESERVED_ZERO, IO_TYPE_FILE, IO_TYPE_OPEN_PACKET, IoCallDriver(), IoFileObjectType, IoFreeIrp(), IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IOP_CREATE_DEVICE_OBJECT_EXTENSION, IOP_CREATE_IGNORE_SHARE_ACCESS_CHECK, IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT, IopAllocateIrp, IopCheckBackupRestorePrivilege(), IopCheckDeviceAndDriver(), IopCheckTopDeviceHint(), IopCheckVpbMounted(), IopDecrementDeviceObjectRef(), IopDeleteFile(), IopDequeueThreadIrp, IopDereferenceVpbAndFree(), IopDoNameTransmogrify(), IopGetNetworkOpenInformation(), IopInterlockedIncrementUlong(), IopPerfLogFileCreate(), IopQueueThreadIrp(), IopSecurityResource, IoQueryFileInformation(), IoSetNextIrpStackLocation, IRP_BUFFERED_IO, IRP_CREATE_OPERATION, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_MJ_CREATE, IRP_MJ_CREATE_MAILSLOT, IRP_MJ_CREATE_NAMED_PIPE, IRP_SYNCHRONOUS_API, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeInitializeEvent(), KeLeaveCriticalRegionThread(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, _OPEN_PACKET::LocalFileObject, _FILE_OBJECT::Lock, LockQueueIoVpbLock, _IO_STACK_LOCATION::MajorFunction, MAXIMUM_ALLOWED, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, _UNICODE_STRING::MaximumLength, _OPEN_PACKET::NetworkInformation, NonPagedPool, NOTHING, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, _DUMMY_FILE_OBJECT::ObjectHeader, ObReferenceObject, OPEN_PACKET_PATTERN, _OPEN_PACKET::Options, _OPEN_PACKET::Override, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, _OPEN_PACKET::ParseCheck, PIRP, _OBJECT_HEADER::PointerCount, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _OPEN_PACKET::QueryOnly, READ_CONTROL, _VPB::ReferenceCount, _OPEN_PACKET::RelatedFileObject, _FILE_OBJECT::RelatedFileObject, _REPARSE_DATA_BUFFER::ReparseDataLength, _REPARSE_DATA_BUFFER::ReparseTag, _REPARSE_DATA_BUFFER::Reserved, RoundNameSize, RtlCopyMemory, RtlCopyUnicodeString(), RtlMapGenericMask(), RtlZeroMemory, SE_BACKUP_PRIVILEGES_CHECKED, SeAccessCheck(), SeAppendPrivileges(), _IO_SECURITY_CONTEXT::SecurityQos, SeFastTraverseCheck(), SeFreePrivileges(), SeLockSubjectContext(), SeOpenObjectAuditAlarm(), SeSetAccessStateGenericMapping(), SeUnlockSubjectContext(), _OPEN_PACKET::ShareAccess, _DISPATCHER_HEADER::SignalState, _OPEN_PACKET::Size, _FILE_OBJECT::Size, _FAST_IO_DISPATCH::SizeOfFastIoDispatch, SL_CASE_SENSITIVE, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_IO_REPARSE_DATA_INVALID, STATUS_NOT_IMPLEMENTED, STATUS_OBJECT_TYPE_MISMATCH, STATUS_PENDING, STATUS_REPARSE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, SynchronizationEvent, SYNCHRONIZE, _ETHREAD::Tcb, TOKEN_HAS_TRAVERSE_PRIVILEGE, _IOP_FILE_OBJECT_EXTENSION::TopDeviceObjectHint, _OPEN_PACKET::TraversedMountPoint, TRUE, _OPEN_PACKET::Type, _OBJECT_HEADER::Type, _FILE_OBJECT::Type, _OBJECT_TYPE::TypeInfo, UNREFERENCED_PARAMETER, UserMode, VOID, _FILE_OBJECT::Vpb, _FILE_OBJECT::Waiters, WRITE_DAC, and WRITE_OWNER.
Referenced by IopCreateObjectTypes(), and IopParseFile().
NTSTATUS IopParseFile (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 1978 of file parse.c.
References IO_TYPE_OPEN_PACKET, IoGetRelatedDeviceObject(), IopParseDevice(), NULL, PAGED_CODE, _OPEN_PACKET::RelatedFileObject, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, and _OPEN_PACKET::Type.
Referenced by IopCreateObjectTypes().
VOID IopPerfLogFileCreate (IN PFILE_OBJECT FileObject, IN PUNICODE_STRING CompleteName)
Referenced by IopParseDevice().
static __inline VOID IopProbeAndLockPages (IN OUT PMDL MemoryDescriptorList, IN KPROCESSOR_MODE AccessMode, IN LOCK_OPERATION Operation, IN PDEVICE_OBJECT DeviceObject, IN ULONG MajorFunction) static
Definition at line 655 of file iomgr.h.
References MmProbeAndLockPages(), MmTrackLockedPages, and MmUpdateMdlTracker().
Referenced by IopSetEaOrQuotaInformationFile(), and IopXxxControlFile().
VOID IopProcessIrpStackProfiler (VOID)
Definition at line 10812 of file internal.c.
References BASE_STACK_COUNT, IopIrpStackProfiler, IopLargeIrpStackLocations, MAX_LOOKASIDE_IRP_STACK_COUNT, MIN_IRP_THRESHOLD, and _IOP_IRP_STACK_PROFILER::Profile.
Referenced by IopIrpStackProfilerTimer().
BOOLEAN IopProtectSystemPartition (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by IoInitSystem().
NTSTATUS IopQueryName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 2465 of file parse.c.
References FALSE, IopQueryNameInternal(), and UNREFERENCED_PARAMETER.
Referenced by IopCreateObjectTypes().
NTSTATUS IopQueryNameInternal (IN PVOID Object, IN BOOLEAN HasObjectName, IN BOOLEAN UseDosDeviceName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 2099 of file parse.c.
References ASSERT, _UNICODE_STRING::Buffer, _FILE_OBJECT::DeviceObject, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, FILE_DEVICE_NETWORK_FILE_SYSTEM, _FILE_NAME_INFORMATION::FileName, FileNameInformation, _FILE_NAME_INFORMATION::FileNameLength, _FILE_OBJECT::Flags, FO_SYNCHRONOUS_IO, IopGetFileInformation(), IopQueryXxxInformation(), IoVolumeDeviceToDosName(), KernelMode, leave, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_NAME_INFORMATION::Name, NT_ERROR, NT_SUCCESS, OBJ_NAME_PATH_SEPARATOR, ObQueryNameString(), PAGED_CODE, PagedPool, RtlCopyMemory, STATUS_BUFFER_OVERFLOW, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_OBJECT_PATH_INVALID, STATUS_SUCCESS, TRUE, UNREFERENCED_PARAMETER, and UserMode.
Referenced by IopQueryName(), and IoQueryFileDosDeviceName().
NTSTATUS IopQueryXxxInformation (IN PFILE_OBJECT FileObject, IN ULONG InformationClass, IN ULONG Length, IN KPROCESSOR_MODE Mode, OUT PVOID Information, OUT PULONG ReturnedLength, IN BOOLEAN FileInformation)
Definition at line 5756 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, _IO_STATUS_BLOCK::Information, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IRP_BUFFERED_IO, IRP_MJ_QUERY_INFORMATION, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, SynchronizationEvent, TRUE, and VOID.
Referenced by IopQueryNameInternal(), IoQueryFileInformation(), and IoQueryVolumeInformation().
VOID IopQueueWorkRequest (IN PIRP Irp)
VOID IopRaiseHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 5979 of file internal.c.
References _UNICODE_STRING::Buffer, _IO_STACK_LOCATION::DeviceObject, ExAllocatePool, ExFreePool(), ExRaiseHardError(), ExReadyForErrors, FALSE, _VPB::Flags, IO_DISK_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IOP_ABORT, IRP_INPUT_OPERATION, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_MOUNT_VOLUME, KeAttachProcess(), KeDetachProcess(), _UNICODE_STRING::Length, _DRIVER_OBJECT::MajorFunction, _IO_STACK_LOCATION::MajorFunction, MAXIMUM_VOLUME_LABEL_LENGTH, _UNICODE_STRING::MaximumLength, _IO_STACK_LOCATION::MinorFunction, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObQueryNameString(), OptionCancelTryContinue, PagedPool, PIRP, PsGetCurrentProcess(), ResponseCancel, ResponseReturnToCaller, ResponseTryAgain, RtlInitUnicodeString(), STATUS_DEVICE_NOT_READY, STATUS_INSUFFICIENT_RESOURCES, STATUS_IO_TIMEOUT, STATUS_MEDIA_WRITE_PROTECTED, STATUS_NO_MEDIA_IN_DEVICE, STATUS_REQUEST_ABORTED, STATUS_SUCCESS, STATUS_UNRECOGNIZED_MEDIA, STATUS_UNSUCCESSFUL, STATUS_WRONG_VOLUME, THREAD_TO_PROCESS, TRUE, _EPROCESS::UniqueProcessId, _VPB::VolumeLabel, _VPB::VolumeLabelLength, and VPB_MOUNTED.
Referenced by IopApcHardError(), and IoRaiseHardError().
VOID IopRaiseInformationalHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 6217 of file internal.c.
References _UNICODE_STRING::Buffer, _IOP_HARD_ERROR_PACKET::ErrorStatus, ExFreePool(), ExRaiseHardError(), ExReadyForErrors, InterlockedDecrement, IopHardError, NULL, _IOP_HARD_ERROR_QUEUE::NumPendingApcPopups, OptionOkNoWait, _IOP_HARD_ERROR_PACKET::String, UNREFERENCED_PARAMETER, and VOID.
Referenced by IoRaiseInformationalHardError().
VOID IopReadyDeviceObjects (IN PDRIVER_OBJECT DriverObject)
Definition at line 6286 of file internal.c.
References DO_DEVICE_INITIALIZING, DRVO_INITIALIZED, and PAGED_CODE.
Referenced by IopInitializeBuiltinDriver(), and IopLoadDriver().
BOOLEAN IopReferenceVerifyVpb (IN PDEVICE_OBJECT DeviceObject, OUT PVPB * Vpb, OUT PDEVICE_OBJECT * FsDeviceObject)
Definition at line 10870 of file internal.c.
References _VPB::DeviceObject, FALSE, _VPB::Flags, IoAcquireVpbSpinLock(), IoReleaseVpbSpinLock(), NULL, _VPB::ReferenceCount, TRUE, and VPB_MOUNTED.
Referenced by IoVerifyVolume().
NTSTATUS IopReportResourceUsage (IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PCM_RESOURCE_LIST DriverList OPTIONAL, IN ULONG DriverListSize OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN PCM_RESOURCE_LIST DeviceList OPTIONAL, IN ULONG DeviceListSize OPTIONAL, IN BOOLEAN OverrideConflict, OUT PBOOLEAN ConflictDetected)
NTSTATUS IopSetEaOrQuotaInformationFile (IN HANDLE FileHandle, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PVOID Buffer, IN ULONG Length, IN BOOLEAN SetEa)
Definition at line 6703 of file internal.c.
References DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FILE_WRITE_DATA, FILE_WRITE_EA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoCheckEaBufferValidity(), IoCheckQuotaBufferValidity(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopProbeAndLockPages(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoReadAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_MJ_SET_EA, IRP_MJ_SET_QUOTA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
Referenced by NtSetQuotaInformationFile().
NTSTATUS IopSetRemoteLink (IN PFILE_OBJECT FileObject, IN PFILE_OBJECT DestinationFileObject OPTIONAL, IN PFILE_TRACKING_INFORMATION FileInformation OPTIONAL)
Definition at line 7104 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, FSCTL_LMR_SET_LINK_TRACKING_INFORMATION, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_KERNEL_CALL, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NULL, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, _REMOTE_LINK_TRACKING_INFORMATION_::TargetFileObject, _REMOTE_LINK_TRACKING_INFORMATION_::TargetLinkTrackingInformationBuffer, _REMOTE_LINK_TRACKING_INFORMATION_::TargetLinkTrackingInformationLength, and _REMOTE_LINK_BUFFER::TrackingInformation.
Referenced by IopTrackLink().
VOID IopShutdownBaseFileSystems (IN PLIST_ENTRY ListHead)
Definition at line 11398 of file iosubs.c.
References CONTAINING_RECORD, DEVICE_OBJECT, Executive, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetAttachedDevice(), IopDecrementDeviceObjectRef(), IopInterlockedIncrementUlong(), IRP_MJ_SHUTDOWN, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LockQueueIoDatabaseLock, NotificationEvent, NULL, ObDereferenceObject(), ObReferenceObject, PIRP, RemoveHeadList(), STATUS_PENDING, TRUE, and VOID.
Referenced by IoShutdownSystem().
VOID IopStartApcHardError (IN PVOID StartContext)
Definition at line 7258 of file internal.c.
References ExFreePool(), IO_DISK_INCREMENT, IoCompleteRequest(), IopApcHardError(), NT_SUCCESS, NULL, PsCreateSystemThread(), and ZwClose().
Referenced by IoRaiseHardError().
NTSTATUS IopSynchronousApiServiceTail (IN NTSTATUS ReturnedStatus, IN PKEVENT Event, IN PIRP Irp, IN KPROCESSOR_MODE RequestorMode, IN PIO_STATUS_BLOCK LocalIoStatus, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 7314 of file internal.c.
References except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, IopCancelAlertedRequest(), KeWaitForSingleObject(), NULL, PAGED_CODE, STATUS_PENDING, and STATUS_USER_APC.
Referenced by IopSetEaOrQuotaInformationFile(), NtFlushBuffersFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetVolumeInformationFile(), and NtUnlockFile().
NTSTATUS IopSynchronousServiceTail (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PFILE_OBJECT FileObject, IN BOOLEAN DeferredIoCompletion, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN SynchronousIo, IN TRANSFER_TYPE TransferType)
Definition at line 7418 of file internal.c.
References APC_LEVEL, ASSERT, Executive, FO_ALERTABLE_IO, IoCallDriver(), IopCancelAlertedRequest(), IopCompleteRequest(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IopUpdateOtherOperationCount(), IopUpdateReadOperationCount(), IopUpdateWriteOperationCount(), KeLowerIrql, KeRaiseIrql, KeWaitForSingleObject(), NULL, OtherTransfer, PAGED_CODE, PASSIVE_LEVEL, ReadTransfer, STATUS_ALERTED, STATUS_PENDING, STATUS_USER_APC, and WriteTransfer.
Referenced by IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
VOID IopTimerDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 7577 of file internal.c.
References CONTAINING_RECORD, _IO_TIMER::Context, _IO_TIMER::DeviceObject, ExAcquireSpinLock, ExReleaseSpinLock, _LIST_ENTRY::Flink, IopTimerCount, IopTimerLock, IopTimerQueueHead, _IO_TIMER::TimerFlag, _IO_TIMER::TimerRoutine, and UNREFERENCED_PARAMETER.
Referenced by IoInitSystem().
NTSTATUS IopTrackLink (IN PFILE_OBJECT FileObject, IN OUT PIO_STATUS_BLOCK IoStatusBlock, IN PFILE_TRACKING_INFORMATION FileInformation, IN ULONG Length, IN PKEVENT Event, IN KPROCESSOR_MODE RequestorMode)
Definition at line 7666 of file internal.c.
References _FILE_TRACKING_INFORMATION::DestinationFile, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FIELD_OFFSET, FILE_WRITE_DATA, FSCTL_LMR_GET_LINK_TRACKING_INFORMATION, IoFileObjectType, IopGetSetObjectId(), IopGetVolumeId(), IopIsSameMachine(), IopMarshalIds(), IopSendMessageToTrackService(), IopSetRemoteLink(), IopTrackLink(), IsFileLocal, KernelMode, KeSetEvent(), leave, NT_SUCCESS, NULL, ObDereferenceObject(), _FILE_TRACKING_INFORMATION::ObjectInformationLength, ObReferenceObjectByHandle, PAGED_CODE, PagedPool, RtlCompareMemoryUlong(), RtlCopyMemory, RtlEqualMemory, STATUS_DUPLICATE_NAME, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, _TRACKING_BUFFER::TrackingInformation, TRUE, and _LINK_TRACKING_INFORMATION::VolumeId.
Referenced by IopTrackLink(), and NtSetInformationFile().
FORCEINLINE VOID IopUpdateOtherOperationCount (VOID)
Definition at line 1344 of file iomgr.h.
References ExInterlockedAddLargeStatistic, InterlockedIncrement, IoOtherOperationCount, KeGetCurrentPrcb(), KeGetCurrentThread(), PsGetCurrentThread(), THREAD_TO_PROCESS, and TRUE.
Referenced by IopCloseFile(), IopCreateFile(), IopGetSetSecurityObject(), IopSynchronousServiceTail(), NtCancelIoFile(), NtDeleteFile(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), NtQueryInformationFile(), and NtSetInformationFile().
FORCEINLINE VOID IopUpdateOtherTransferCount (IN ULONG TransferCount)
Definition at line 1471 of file iomgr.h.
References ExInterlockedAddLargeStatistic, IoOtherTransferCount, KeGetCurrentPrcb(), KeGetCurrentThread(), PsGetCurrentThread(), THREAD_TO_PROCESS, and TRUE.
Referenced by IopCompleteRequest(), and NtSetInformationFile().
FORCEINLINE VOID IopUpdateReadOperationCount (VOID)
Definition at line 1386 of file iomgr.h.
References ExInterlockedAddLargeStatistic, InterlockedIncrement, IoReadOperationCount, KeGetCurrentPrcb(), KeGetCurrentThread(), PsGetCurrentThread(), THREAD_TO_PROCESS, and TRUE.
Referenced by IopSynchronousServiceTail(), and NtReadFile().
FORCEINLINE VOID IopUpdateReadTransferCount (IN ULONG TransferCount)
Definition at line 1513 of file iomgr.h.
References ExInterlockedAddLargeStatistic, IoReadTransferCount, KeGetCurrentPrcb(), KeGetCurrentThread(), PsGetCurrentThread(), THREAD_TO_PROCESS, and TRUE.
Referenced by IopCompleteRequest(), and NtReadFile().
FORCEINLINE VOID IopUpdateWriteOperationCount (VOID)
Definition at line 1429 of file iomgr.h.
References ExInterlockedAddLargeStatistic, InterlockedIncrement, IoWriteOperationCount, KeGetCurrentPrcb(), KeGetCurrentThread(), PsGetCurrentThread(), THREAD_TO_PROCESS, and TRUE.
Referenced by IopSynchronousServiceTail(), and NtWriteFile().
FORCEINLINE VOID IopUpdateWriteTransferCount (IN ULONG TransferCount)
Definition at line 1555 of file iomgr.h.
References ExInterlockedAddLargeStatistic, IoWriteTransferCount, KeGetCurrentPrcb(), KeGetCurrentThread(), PsGetCurrentThread(), THREAD_TO_PROCESS, and TRUE.
Referenced by IopCompleteRequest(), and NtWriteFile().
VOID IopUserCompletion (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 8380 of file internal.c.
References CONTAINING_RECORD, IoFreeIrp(), IRP, PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by IopCompleteRequest().
BOOLEAN IopVerifyDeviceObjectOnStack (IN PDEVICE_OBJECT BaseDeviceObject, IN PDEVICE_OBJECT TopDeviceObject)
Definition at line 10470 of file internal.c.
References ASSERT, FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and TRUE.
Referenced by IoGetRelatedDeviceObject(), and IopCheckTopDeviceHint().
BOOLEAN IopVerifyDiskSignature (IN PDRIVE_LAYOUT_INFORMATION_EX DriveLayout, IN PARC_DISK_SIGNATURE LoaderDiskBlock, OUT PULONG DiskSignature)
Definition at line 10518 of file internal.c.
References FALSE, RtlEqualMemory, and TRUE.
Referenced by IoGetBootDiskInformation(), and IopCreateArcNamesDisk().
BOOLEAN IopVerifyDriverObjectOnStack (IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_OBJECT DriverObject)
Definition at line 10666 of file internal.c.
References FALSE, IopGetDeviceAttachmentBase(), and TRUE.
Referenced by IopGetDriverPathInformation().
NTSTATUS IopXxxControlFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, IN ULONG IoControlCode, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN DeviceIoControl)
Definition at line 8483 of file internal.c.
References ARGUMENT_PRESENT, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, _FAST_IO_DISPATCH::FastIoDeviceControl, FILE_ANY_ACCESS, FILE_READ_DATA, FILE_WRITE_DATA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_SYNCHRONOUS_IO, FSCTL_DISMOUNT_VOLUME, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _IO_STATUS_BLOCK::Information, InterlockedIncrement, IoAllocateMdl(), IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopMarkApcRoutineIfAsyncronousIo32, IopProbeAndLockPages(), IopReleaseFileObjectLock, IopSynchronousServiceTail(), IoReadAccess, IoSetIoCompletion(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, KeSetEvent(), _IO_COMPLETION_CONTEXT::Key, _IO_STACK_LOCATION::MajorFunction, METHOD_BUFFERED, METHOD_IN_DIRECT, METHOD_NEITHER, METHOD_OUT_DIRECT, NonPagedPool, NonPagedPoolCacheAligned, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _IO_COMPLETION_CONTEXT::Port, ProbeForRead, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, SeComputeGrantedAccesses, SharedUserData, SL_READ_ACCESS_GRANTED, SL_WRITE_ACCESS_GRANTED, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _ETHREAD::Tcb, and TRUE.
Referenced by NtDeviceIoControlFile(), and NtFsControlFile().
typedef NTSTATUS (FASTCALL * PIO_CALL_DRIVER)
typedef VOID (FASTCALL * PIO_COMPLETE_REQUEST)
Variable Documentation
POBJECT_TYPE ExEventObjectType
Definition at line 32 of file event.c.
POBJECT_TYPE IoAdapterObjectType
Definition at line 237 of file iodata.c.
Referenced by IopCreateObjectTypes().
UNICODE_STRING IoArcBootDeviceName
Definition at line 760 of file iodata.c.
Referenced by IopCreateArcNames().
UNICODE_STRING IoArcHalDeviceName
Definition at line 761 of file iodata.c.
Referenced by IopCreateArcNames().
POBJECT_TYPE IoCompletionObjectType
Definition at line 239 of file iodata.c.
POBJECT_TYPE IoControllerObjectType
Definition at line 238 of file iodata.c.
Referenced by IoCreateController(), and IopCreateObjectTypes().
LOGICAL IoCountOperations
Definition at line 49 of file iosubs.c.
POBJECT_TYPE IoDeviceHandlerObjectType
Definition at line 242 of file iodata.c.
Referenced by IopCreateObjectTypes().
PUCHAR IoLoaderArcBootDeviceName
Definition at line 762 of file iodata.c.
Referenced by IopCreateArcNames().
LIST_ENTRY IopBootDriverReinitializeQueueHead
Definition at line 127 of file iodata.c.
Referenced by IoInitSystem(), IopCallBootDriverReinitializationRoutines(), and IoRegisterBootDriverReinitialization().
LIST_ENTRY IopCdRomFileSystemQueueHead
Definition at line 100 of file iodata.c.
Referenced by IoInitSystem(), IopInvalidateVolumesForDevice(), IopMountVolume(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), and IoShutdownSystem().
GENERAL_LOOKASIDE IopCompletionLookasideList
Definition at line 162 of file iodata.c.
Referenced by IoInitSystem().
ERESOURCE IopCrashDumpLock
Referenced by IoInitSystem().
PIOP_HARD_ERROR_PACKET IopCurrentHardError
Definition at line 215 of file iodata.c.
Referenced by IoInitSystem(), IopCheckHardErrorEmpty(), IopRemoveHardErrorPacket(), and IoRaiseInformationalHardError().
ERESOURCE IopDatabaseResource
Definition at line 62 of file iodata.c.
Referenced by IoEnumerateRegisteredFiltersList(), IoInitSystem(), IopInvalidateVolumesForDevice(), IopMountVolume(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoShutdownSystem(), IoUnregisterFileSystem(), and IoUnregisterFsRegistrationChange().
LIST_ENTRY IopDiskFileSystemQueueHead
Definition at line 90 of file iodata.c.
Referenced by IoInitSystem(), IopInvalidateVolumesForDevice(), IopMountVolume(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), and IoShutdownSystem().
ERESOURCE IopDriverLoadResource
Definition at line 71 of file iodata.c.
Referenced by IoInitSystem(), and IopLoadDriver().
LIST_ENTRY IopDriverReinitializeQueueHead
Definition at line 134 of file iodata.c.
Referenced by IoInitSystem(), IopCallDriverReinitializationRoutines(), and IoRegisterDriverReinitialization().
PDUMP_CONTROL_BLOCK IopDumpControlBlock
Definition at line 268 of file iodata.c.
ULONG IopDumpControlBlockChecksum
Definition at line 269 of file iodata.c.
LONG IopErrorLogAllocation
Definition at line 190 of file iodata.c.
Referenced by IoFreeErrorLogEntry(), IopAllocateErrorLogEntry(), IopErrorLogThread(), and IoWriteErrorLogEntry().
KSPIN_LOCK IopErrorLogAllocationLock
BOOLEAN IopErrorLogDisabledThisBoot
Definition at line 78 of file errorlog.c.
Referenced by IoInitSystem(), and IoWriteErrorLogEntry().
LIST_ENTRY IopErrorLogListHead
Definition at line 183 of file iodata.c.
Referenced by IoInitSystem(), IopErrorLogGetEntry(), IopErrorLogRequeueEntry(), and IoWriteErrorLogEntry().
ALIGNED_SPINLOCK IopErrorLogLock
Definition at line 54 of file hifreqlk.c.
Referenced by IoInitSystem(), IopErrorLogGetEntry(), IopErrorLogRequeueEntry(), and IoWriteErrorLogEntry().
BOOLEAN IopErrorLogPortPending
Definition at line 77 of file errorlog.c.
Referenced by IopErrorLogGetEntry(), IopErrorLogQueueRequest(), and IoWriteErrorLogEntry().
WORK_QUEUE_ITEM IopErrorLogWorkItem
Definition at line 68 of file errorlog.c.
Referenced by IoWriteErrorLogEntry().
ULONG IopFailZeroAccessCreate
Definition at line 304 of file iodata.c.
Referenced by IopCreateFile().
const GENERIC_MAPPING IopFileMapping
Definition at line 2084 of file ioinit.c.
Referenced by IoGetFileObjectGenericMapping(), and IopCreateObjectTypes().
LIST_ENTRY IopFsNotifyChangeQueueHead
Definition at line 150 of file iodata.c.
Referenced by IoEnumerateRegisteredFiltersList(), IoInitSystem(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoUnregisterFileSystem(), and IoUnregisterFsRegistrationChange().
ULONG IopFsRegistrationOps
Definition at line 297 of file iodata.c.
Referenced by IopMountVolume(), IoRegisterFileSystem(), and IoUnregisterFileSystem().
IOP_HARD_ERROR_QUEUE IopHardError
Definition at line 208 of file iodata.c.
Referenced by IoInitSystem(), IopCheckHardErrorEmpty(), IopHardErrorThread(), IopRaiseInformationalHardError(), IopRemoveHardErrorPacket(), and IoRaiseInformationalHardError().
IOP_IRP_STACK_PROFILER IopIrpStackProfiler
Definition at line 327 of file iodata.c.
Referenced by IoInitSystem(), IopInitializeIrpStackProfiler(), and IopProcessIrpStackProfiler().
GENERAL_LOOKASIDE IopLargeIrpLookasideList
Definition at line 163 of file iodata.c.
Referenced by IoInitSystem().
ULONG IopLargeIrpStackLocations
Definition at line 166 of file iodata.c.
Referenced by IoInitSystem(), IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), IopFreeIrp(), and IopProcessIrpStackProfiler().
LINK_TRACKING_PACKET IopLinkTrackingPacket
Definition at line 325 of file iodata.c.
Referenced by IoInitSystem(), and IopSendMessageToTrackService().
KEVENT IopLinkTrackingPortObject
Definition at line 324 of file iodata.c.
Referenced by IoInitSystem(), and IopSendMessageToTrackService().
PKEVENT IopLinkTrackingServiceEvent
Definition at line 348 of file iodata.c.
Referenced by IoInitSystem(), IopConnectLinkTrackingPort(), and IopSendMessageToTrackService().
HANDLE IopLinkTrackingServiceEventHandle
Definition at line 349 of file iodata.c.
Referenced by IoShutdownSystem().
PVOID IopLinkTrackingServiceObject
Definition at line 347 of file iodata.c.
Referenced by IopConnectLinkTrackingPort(), and IopSendMessageToTrackService().
GENERAL_LOOKASIDE IopMdlLookasideList
Definition at line 165 of file iodata.c.
Referenced by IoInitSystem().
LIST_ENTRY IopNetworkFileSystemQueueHead
Definition at line 110 of file iodata.c.
Referenced by IoInitSystem(), IoRegisterFileSystem(), and IoRegisterFsRegistrationChange().
LIST_ENTRY IopNotifyLastChanceShutdownQueueHead
Definition at line 142 of file iodata.c.
Referenced by IoInitSystem(), IoRegisterLastChanceShutdownNotification(), IoShutdownSystem(), and IoUnregisterShutdownNotification().
LIST_ENTRY IopNotifyShutdownQueueHead
Definition at line 141 of file iodata.c.
Referenced by IoInitSystem(), IoRegisterShutdownNotification(), IoShutdownSystem(), and IoUnregisterShutdownNotification().
const ULONG IopQueryFsOperationAccess[]
Definition at line 683 of file iodata.c.
Referenced by IoCheckFunctionAccess(), IoInitSystem(), and NtQueryVolumeInformationFile().
const UCHAR IopQueryFsOperationLength[]
Definition at line 635 of file iodata.c.
Referenced by IoCheckQuerySetVolumeInformation(), IoInitSystem(), and NtQueryVolumeInformationFile().
const ULONG IopQueryOperationAccess[]
Definition at line 525 of file iodata.c.
Referenced by IoCheckFunctionAccess(), IoInitSystem(), and NtQueryInformationFile().
const UCHAR IopQueryOperationLength[]
Definition at line 360 of file iodata.c.
Referenced by IoCheckQuerySetFileInformation(), IoInitSystem(), and NtQueryInformationFile().
const UCHAR IopQuerySetAlignmentRequirement[]
Definition at line 470 of file iodata.c.
Referenced by BuildQueryDirectoryIrp(), NtQueryInformationFile(), and NtSetInformationFile().
const UCHAR IopQuerySetFsAlignmentRequirement[]
Definition at line 731 of file iodata.c.
Referenced by NtQueryVolumeInformationFile(), and NtSetVolumeInformationFile().
IOP_RESERVE_IRP_ALLOCATOR IopReserveIrpAllocator
Definition at line 309 of file iodata.c.
Referenced by IoInitSystem(), IopAllocateReserveIrp(), and IopFreeReserveIrp().
ERESOURCE IopSecurityResource
Definition at line 80 of file iodata.c.
Referenced by IoInitSystem(), IopGetSetSecurityObject(), IopParseDevice(), and IopSetDeviceSecurityDescriptor().
const ULONG IopSetFsOperationAccess[]
Definition at line 707 of file iodata.c.
Referenced by IoCheckFunctionAccess(), IoInitSystem(), and NtSetVolumeInformationFile().
const UCHAR IopSetFsOperationLength[]
Definition at line 659 of file iodata.c.
Referenced by IoCheckQuerySetVolumeInformation(), IoInitSystem(), and NtSetVolumeInformationFile().
const ULONG IopSetOperationAccess[]
Definition at line 580 of file iodata.c.
Referenced by IoCheckFunctionAccess(), IoInitSystem(), and NtSetInformationFile().
const UCHAR IopSetOperationLength[]
Definition at line 415 of file iodata.c.
Referenced by IoCheckQuerySetFileInformation(), IoInitSystem(), and NtSetInformationFile().
GENERAL_LOOKASIDE IopSmallIrpLookasideList
Definition at line 164 of file iodata.c.
Referenced by IoInitSystem().
LIST_ENTRY IopTapeFileSystemQueueHead
Definition at line 120 of file iodata.c.
Referenced by IoInitSystem(), IopInvalidateVolumesForDevice(), IopMountVolume(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), and IoShutdownSystem().
KTIMER IopTimer
Definition at line 229 of file iodata.c.
Referenced by IoInitSystem().
ULONG IopTimerCount
Definition at line 230 of file iodata.c.
Referenced by IopRemoveTimerFromTimerList(), IopTimerDispatch(), IoStartTimer(), and IoStopTimer().
KDPC IopTimerDpc
Definition at line 228 of file iodata.c.
Referenced by IoInitSystem().
ALIGNED_SPINLOCK IopTimerLock
Definition at line 55 of file hifreqlk.c.
Referenced by IoInitializeTimer(), IoInitSystem(), IopRemoveTimerFromTimerList(), IopTimerDispatch(), IoStartTimer(), and IoStopTimer().
LIST_ENTRY IopTimerQueueHead
Definition at line 227 of file iodata.c.
Referenced by IoInitializeTimer(), IoInitSystem(), and IopTimerDispatch().
LONG IopUniqueDeviceObjectNumber
Definition at line 285 of file iodata.c.
Referenced by IoCreateDevice(), and IoInitSystem().
BOOLEAN IopVerifierOn
Referenced by IoCancelIrp(), and IopCreateObjectTypes().
ALIGNED_SPINLOCK IoStatisticsLock
Definition at line 56 of file hifreqlk.c.
PIO_ALLOCATE_IRP pIoAllocateIrp
Referenced by IoAllocateIrp(), and IopSetIoRoutines().
PIO_CALL_DRIVER pIofCallDriver
Referenced by IofCallDriver(), and IofCallDriverSpecifyReturn().
PIO_COMPLETE_REQUEST pIofCompleteRequest
Referenced by IofCompleteRequest(), and IopSetIoRoutines().
PIO_FREE_IRP pIoFreeIrp
Referenced by IoFreeIrp(), and IopSetIoRoutines().