Windows Research Kernel v1.2: C:/Windows Research Kernel/dbgk/dbgkp.h File Reference
dbgkp.h File Reference
#include "ntos.h"
#include "wdbgexts.h"
#include "ntdbg.h"
#include <zwapi.h>
#include <string.h>
Data Structures
struct _DEBUG_EVENT
Macros
#define DBGKP_FIELD_FROM_IMAGE_OPTIONAL_HEADER(hdrs, field) ((hdrs)->OptionalHeader.##field)
#define DEBUG_EVENT_INACTIVE (0x04)
#define DEBUG_EVENT_NOWAIT (0x02)
#define DEBUG_EVENT_PROTECT_FAILED (0x10)
#define DEBUG_EVENT_READ (0x01)
#define DEBUG_EVENT_RELEASE (0x08)
#define DEBUG_EVENT_SUSPEND (0x20)
#define NOEXTAPI
Typedefs
typedef struct _DEBUG_EVENT DEBUG_EVENT
typedef struct _DEBUG_EVENT * PDEBUG_EVENT
Functions
VOID DbgkpCloseObject (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID DbgkpConvertKernelToUserStateChange (IN OUT PDBGUI_WAIT_STATE_CHANGE WaitStateChange, IN PDEBUG_EVENT DebugEvent)
VOID DbgkpDeleteObject (IN PVOID Object)
VOID DbgkpFreeDebugEvent (IN PDEBUG_EVENT DebugEvent)
VOID DbgkpMarkProcessPeb (PEPROCESS Process)
VOID DbgkpOpenHandles (PDBGUI_WAIT_STATE_CHANGE WaitStateChange, PEPROCESS Process, PETHREAD Thread)
NTSTATUS DbgkpPostAdditionalThreadMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD LastThread)
NTSTATUS DbgkpPostFakeModuleMessages (IN PEPROCESS Process, IN PETHREAD Thread, IN PDEBUG_OBJECT DebugObject)
NTSTATUS DbgkpPostFakeProcessCreateMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD *pLastThread)
NTSTATUS DbgkpPostFakeThreadMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD StartThread, OUT PETHREAD *pFirstThread, OUT PETHREAD *pLastThread)
NTSTATUS DbgkpQueueMessage (IN PEPROCESS Process, IN PETHREAD Thread, IN OUT PDBGKM_APIMSG ApiMsg, IN ULONG Flags, IN PDEBUG_OBJECT TargetDebugObject)
VOID DbgkpResumeProcess (VOID)
HANDLE DbgkpSectionToFileHandle (IN PVOID SectionObject)
NTSTATUS DbgkpSendApiMessage (IN OUT PDBGKM_APIMSG ApiMsg, IN BOOLEAN SuspendProcess)
NTSTATUS DbgkpSendApiMessageLpc (IN OUT PDBGKM_APIMSG ApiMsg, IN PVOID Port, IN BOOLEAN SuspendProcess)
NTSTATUS DbgkpSetProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN NTSTATUS MsgStatus, IN PETHREAD LastThread)
BOOLEAN DbgkpSuspendProcess (VOID)
VOID DbgkpWakeTarget (IN PDEBUG_EVENT DebugEvent)
Macro Definition Documentation
#define DBGKP_FIELD_FROM_IMAGE_OPTIONAL_HEADER (hdrs, field) ((hdrs)->OptionalHeader.##field)
Definition at line 47 of file dbgkp.h.
Referenced by DbgkCreateThread().
#define DEBUG_EVENT_INACTIVE (0x04)
Definition at line 41 of file dbgkp.h.
Referenced by DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), NtDebugContinue(), and NtWaitForDebugEvent().
#define DEBUG_EVENT_NOWAIT (0x02)
Definition at line 40 of file dbgkp.h.
Referenced by DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), DbgkpQueueMessage(), and DbgkpWakeTarget().
#define DEBUG_EVENT_PROTECT_FAILED (0x10)
Definition at line 43 of file dbgkp.h.
Referenced by DbgkpPostFakeThreadMessages(), and DbgkpSetProcessDebugObject().
#define DEBUG_EVENT_READ (0x01)
Definition at line 39 of file dbgkp.h.
Referenced by NtDebugContinue(), and NtWaitForDebugEvent().
#define DEBUG_EVENT_RELEASE (0x08)
Definition at line 42 of file dbgkp.h.
Referenced by DbgkpPostFakeThreadMessages(), DbgkpSetProcessDebugObject(), and DbgkpWakeTarget().
#define DEBUG_EVENT_SUSPEND (0x20)
Definition at line 44 of file dbgkp.h.
Referenced by DbgkpPostFakeThreadMessages(), and DbgkpWakeTarget().
#define NOEXTAPI
Definition at line 30 of file dbgkp.h.
Typedef Documentation
typedef struct _DEBUG_EVENT DEBUG_EVENT
typedef struct _DEBUG_EVENT * PDEBUG_EVENT
Function Documentation
VOID DbgkpCloseObject (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 246 of file dbgkobj.c.
References CONTAINING_RECORD, DbgkpMarkProcessPeb(), DbgkpWakeTarget(), DEBUG_OBJECT_DELETE_PENDING, DEBUG_OBJECT_KILL_ON_CLOSE, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, _DEBUG_OBJECT::Flags, _LIST_ENTRY::Flink, InitializeListHead(), KeSetEvent(), _DEBUG_OBJECT::Mutex, NULL, ObDereferenceObject(), PAGED_CODE, PsGetNextProcess(), PsTerminateProcess(), _DEBUG_EVENT::Status, STATUS_DEBUGGER_INACTIVE, TRUE, and UNREFERENCED_PARAMETER.
Referenced by DbgkInitialize().
VOID DbgkpConvertKernelToUserStateChange (IN OUT PDBGUI_WAIT_STATE_CHANGE WaitStateChange, IN PDEBUG_EVENT DebugEvent)
VOID DbgkpDeleteObject (IN PVOID Object)
Definition at line 127 of file dbgkobj.c.
References ASSERT, _DEBUG_OBJECT::EventList, IsListEmpty, PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by DbgkInitialize().
VOID DbgkpFreeDebugEvent (IN PDEBUG_EVENT DebugEvent)
Definition at line 569 of file dbgkobj.c.
References DbgKmCreateProcessApi, DbgKmLoadDllApi, ExFreePool(), KernelMode, NULL, ObCloseHandle(), ObDereferenceObject(), PAGED_CODE, and Status.
Referenced by DbgkpWakeTarget().
VOID DbgkpMarkProcessPeb (PEPROCESS Process)
Definition at line 162 of file dbgkobj.c.
References _EPROCESS::DebugPort, ExAcquireFastMutex(), ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseFastMutex(), ExReleaseRundownProtection(), FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, PAGED_CODE, _EPROCESS::Pcb, _EPROCESS::Peb, _EPROCESS::RundownProtect, and TRUE.
Referenced by DbgkClearProcessDebugObject(), DbgkpCloseObject(), and DbgkpSetProcessDebugObject().
VOID DbgkpOpenHandles (PDBGUI_WAIT_STATE_CHANGE WaitStateChange, PEPROCESS Process, PETHREAD Thread)
Definition at line 1603 of file dbgkobj.c.
References _DBGUI_WAIT_STATE_CHANGE::CreateProcessInfo, _DBGUI_WAIT_STATE_CHANGE::CreateThread, DbgCreateProcessStateChange, DbgCreateThreadStateChange, DbgLoadDllStateChange, DUPLICATE_SAME_ACCESS, _DBGKM_CREATE_PROCESS::FileHandle, _DBGKM_LOAD_DLL::FileHandle, _DBGUI_CREATE_PROCESS::HandleToProcess, _DBGUI_CREATE_THREAD::HandleToThread, _DBGUI_CREATE_PROCESS::HandleToThread, KernelMode, _DBGUI_WAIT_STATE_CHANGE::LoadDll, _DBGUI_CREATE_PROCESS::NewProcess, _DBGUI_WAIT_STATE_CHANGE::NewState, NT_SUCCESS, NULL, ObCloseHandle(), ObDuplicateObject(), ObOpenObjectByPointer(), PAGED_CODE, PROCESS_CREATE_THREAD, PROCESS_DUP_HANDLE, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, PsGetCurrentProcess(), PsProcessType, PsThreadType, READ_CONTROL, _DBGUI_WAIT_STATE_CHANGE::StateInfo, Status, SYNCHRONIZE, THREAD_GET_CONTEXT, THREAD_QUERY_INFORMATION, THREAD_SET_CONTEXT, THREAD_SET_INFORMATION, THREAD_SUSPEND_RESUME, and THREAD_TERMINATE.
Referenced by NtWaitForDebugEvent().
NTSTATUS DbgkpPostAdditionalThreadMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD LastThread)
NTSTATUS DbgkpPostFakeModuleMessages (IN PEPROCESS Process, IN PETHREAD Thread, IN PDEBUG_OBJECT DebugObject)
Definition at line 1207 of file dbgkobj.c.
References _DBGKM_APIMSG::ApiNumber, ASSERT, _DBGKM_LOAD_DLL::BaseOfDll, _UNICODE_STRING::Buffer, CONTAINING_RECORD, DbgKmLoadDllApi, DbgkpQueueMessage(), DEBUG_EVENT_NOWAIT, _DBGKM_LOAD_DLL::DebugInfoFileOffset, _DBGKM_LOAD_DLL::DebugInfoSize, _LDR_DATA_TABLE_ENTRY::DllBase, _LDR_DATA_TABLE_ENTRY32::DllBase, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, _DBGKM_LOAD_DLL::FileHandle, _IMAGE_NT_HEADERS::FileHeader, _LIST_ENTRY::Flink, LIST_ENTRY32::Flink, GENERIC_READ, InitializeObjectAttributes, _PEB_LDR_DATA::InLoadOrderModuleList, _PEB_LDR_DATA32::InLoadOrderModuleList, KernelMode, _DBGKM_APIMSG::LoadDll, MmGetFileNameForAddress(), _DBGKM_LOAD_DLL::NamePointer, NT_SUCCESS, NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, ProbeForReadSmallStructure, RtlCopyMemory, RtlImageNtHeader(), RtlZeroMemory, Status, STATUS_SUCCESS, SYNCHRONIZE, _DBGKM_APIMSG::u, UlongToPtr, UNICODE_NULL, wcsstr(), WOW64_SYSTEM_DIRECTORY_U, and ZwOpenFile().
Referenced by DbgkpPostFakeProcessCreateMessages().
NTSTATUS DbgkpPostFakeProcessCreateMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD * pLastThread)
Definition at line 1398 of file dbgkobj.c.
References DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, and Status.
Referenced by NtDebugActiveProcess().
NTSTATUS DbgkpPostFakeThreadMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD StartThread, OUT PETHREAD * pFirstThread, OUT PETHREAD * pLastThread)
Definition at line 1031 of file dbgkobj.c.
References _DBGKM_APIMSG::ApiNumber, _DBGKM_CREATE_PROCESS::BaseOfImage, _DBGKM_APIMSG::CreateProcessInfo, _DBGKM_APIMSG::CreateThread, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgkpQueueMessage(), DbgkpSectionToFileHandle(), DEBUG_EVENT_NOWAIT, DEBUG_EVENT_PROTECT_FAILED, DEBUG_EVENT_RELEASE, DEBUG_EVENT_SUSPEND, _DBGKM_CREATE_PROCESS::DebugInfoFileOffset, _DBGKM_CREATE_PROCESS::DebugInfoSize, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), FALSE, _DBGKM_CREATE_PROCESS::FileHandle, _IMAGE_NT_HEADERS::FileHeader, _ETHREAD::GrantedAccess, _DBGKM_CREATE_PROCESS::InitialThread, IS_SYSTEM_THREAD, KernelMode, NT_SUCCESS, NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, PsGetNextProcessThread(), PsQuitNextProcessThread(), PsResumeThread(), PsSuspendThread(), RtlImageNtHeader(), RtlZeroMemory, _ETHREAD::RundownProtect, _DBGKM_CREATE_THREAD::StartAddress, _ETHREAD::StartAddress, Status, STATUS_UNSUCCESSFUL, TRUE, and _DBGKM_APIMSG::u.
Referenced by DbgkpPostFakeProcessCreateMessages(), and DbgkpSetProcessDebugObject().
NTSTATUS DbgkpQueueMessage (IN PEPROCESS Process, IN PETHREAD Thread, IN OUT PDBGKM_APIMSG ApiMsg, IN ULONG Flags, IN PDEBUG_OBJECT TargetDebugObject)
Definition at line 598 of file dbgkobj.c.
References _DEBUG_EVENT::ApiMsg, _DEBUG_EVENT::BackoutThread, _DEBUG_EVENT::ClientId, _DEBUG_EVENT::ContinueEvent, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgKmExitProcessApi, DbgKmExitThreadApi, DEBUG_EVENT_INACTIVE, DEBUG_EVENT_NOWAIT, DEBUG_OBJECT_DELETE_PENDING, _DEBUG_OBJECT::EventList, _DEBUG_EVENT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), ExAllocatePoolWithQuotaTag, Executive, ExFreePool(), ExReleaseFastMutex(), FALSE, _DEBUG_OBJECT::Flags, _DEBUG_EVENT::Flags, InsertTailList(), KeInitializeEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _DEBUG_OBJECT::Mutex, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _DEBUG_EVENT::Process, PS_CROSS_THREAD_FLAGS_SKIP_CREATION_MSG, PS_CROSS_THREAD_FLAGS_SKIP_TERMINATION_MSG, PsGetCurrentThread(), _DEBUG_EVENT::Status, Status, STATUS_DEBUGGER_INACTIVE, STATUS_INSUFFICIENT_RESOURCES, STATUS_PORT_NOT_SET, STATUS_SUCCESS, SynchronizationEvent, and _DEBUG_EVENT::Thread.
Referenced by DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), and DbgkpSendApiMessage().
VOID DbgkpResumeProcess (VOID)
Definition at line 73 of file dbgkproc.c.
References KeThawAllThreads(), and PAGED_CODE.
Referenced by DbgkExitThread(), DbgkpSendApiMessage(), and DbgkpSendApiMessageLpc().
HANDLE DbgkpSectionToFileHandle (IN PVOID SectionObject)
Definition at line 109 of file dbgkproc.c.
References ExFreePool(), FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, GENERIC_READ, Handle, InitializeObjectAttributes, MmGetFileNameForSection(), _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, Status, SYNCHRONIZE, and ZwOpenFile().
Referenced by DbgkCreateThread(), DbgkMapViewOfSection(), and DbgkpPostFakeThreadMessages().
NTSTATUS DbgkpSendApiMessage (IN OUT PDBGKM_APIMSG ApiMsg, IN BOOLEAN SuspendProcess)
Definition at line 30 of file dbgkport.c.
References DbgkpQueueMessage(), DbgkpResumeProcess(), DbgkpSuspendProcess(), _EPROCESS::Flags, NtCurrentProcess, NULL, PAGED_CODE, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_SET_BITS, PsGetCurrentProcess(), PsGetCurrentThread(), STATUS_PENDING, and ZwFlushInstructionCache().
Referenced by DbgkCreateThread(), DbgkExitProcess(), DbgkExitThread(), DbgkForwardException(), DbgkMapViewOfSection(), and DbgkUnMapViewOfSection().
NTSTATUS DbgkpSendApiMessageLpc (IN OUT PDBGKM_APIMSG ApiMsg, IN PVOID Port, IN BOOLEAN SuspendProcess)
Definition at line 88 of file dbgkport.c.
References DbgkpResumeProcess(), DbgkpSuspendProcess(), LpcRequestWaitReplyPortEx(), NT_SUCCESS, NtCurrentProcess, NULL, PAGED_CODE, PORT_TOTAL_MAXIMUM_MESSAGE_LENGTH, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_SET_BITS, PsGetCurrentProcess(), RtlCopyMemory, STATUS_PENDING, and ZwFlushInstructionCache().
Referenced by DbgkForwardException().
NTSTATUS DbgkpSetProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN NTSTATUS MsgStatus, IN PETHREAD LastThread)
Definition at line 820 of file dbgkobj.c.
References _DEBUG_EVENT::BackoutThread, CONTAINING_RECORD, _ETHREAD::CrossThreadFlags, DbgkpMarkProcessPeb(), DbgkpPostFakeThreadMessages(), DbgkpWakeTarget(), DEBUG_EVENT_INACTIVE, DEBUG_EVENT_PROTECT_FAILED, DEBUG_EVENT_RELEASE, DEBUG_OBJECT_DELETE_PENDING, _DEBUG_EVENT::EventList, ExAcquireFastMutex(), ExReleaseFastMutex(), ExReleaseRundownProtection(), FALSE, _DEBUG_EVENT::Flags, _LIST_ENTRY::Flink, _ETHREAD::GrantedAccess, InitializeListHead(), InsertTailList(), IS_SYSTEM_THREAD, IsListEmpty, KeSetEvent(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PS_CROSS_THREAD_FLAGS_SKIP_CREATION_MSG, PS_CROSS_THREAD_FLAGS_SKIP_TERMINATION_MSG, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_SET_BITS, PsGetCurrentThread(), PsGetNextProcessThread(), RemoveEntryList(), RemoveHeadList(), _ETHREAD::RundownProtect, Status, STATUS_DEBUGGER_INACTIVE, STATUS_PORT_ALREADY_SET, STATUS_SUCCESS, _DEBUG_EVENT::Thread, and TRUE.
Referenced by NtDebugActiveProcess().
BOOLEAN DbgkpSuspendProcess (VOID)
Definition at line 36 of file dbgkproc.c.
References FALSE, KeFreezeAllThreads(), PAGED_CODE, PS_PROCESS_FLAGS_PROCESS_DELETE, PsGetCurrentProcess(), and TRUE.
Referenced by DbgkExitThread(), DbgkpSendApiMessage(), and DbgkpSendApiMessageLpc().
VOID DbgkpWakeTarget (IN PDEBUG_EVENT DebugEvent)
Definition at line 219 of file dbgkobj.c.
References DbgkpFreeDebugEvent(), DEBUG_EVENT_NOWAIT, DEBUG_EVENT_RELEASE, DEBUG_EVENT_SUSPEND, ExReleaseRundownProtection(), FALSE, KeSetEvent(), NULL, PsResumeThread(), and _ETHREAD::RundownProtect.
Referenced by DbgkClearProcessDebugObject(), DbgkpCloseObject(), DbgkpSetProcessDebugObject(), and NtDebugContinue().