Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/lockvm.c File Reference
lockvm.c File Reference
#include "mi.h"
Functions
NTSTATUS NtLockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
NTSTATUS NtUnlockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
Function Documentation
NTSTATUS NtLockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
Definition at line 24 of file lockvm.c.
References _ETHREAD::AddressSpaceOwner, ASSERT, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE::Hard, KeAreAllApcsDisabled(), KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MAP_PROCESS, MAP_SYSTEM, MI_PFN_ELEMENT, MI_VPN_TO_VA, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiIsAddressValid(), MiLocateAddress(), MiLocateWsle(), MiMakePdeExistAndMakeValid(), _MMSUPPORT::MinimumWorkingSetSize, MiSwapWslEntries(), MM_FLUID_WORKING_SET, MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MmWorkingSetList, MmWsle, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsProcessType, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_VIOLATION, STATUS_INCOMPATIBLE_FILE_MAP, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_WAS_LOCKED, STATUS_WORKING_SET_QUOTA, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u1, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadLargePageSection, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMPFN::WsIndex, and WSLE_NULL_INDEX.
NTSTATUS NtUnlockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
Definition at line 571 of file lockvm.c.
References ASSERT, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE::Hard, KeGetPreviousMode, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MAP_PROCESS, MAP_SYSTEM, MI_PFN_ELEMENT, MI_VPN_TO_VA, MiFreeWsle(), MiGetPteAddress, MiIsAddressValid(), MiLocateAddress(), MiLocateWsle(), MiSwapWslEntries(), MM_HIGHEST_USER_ADDRESS, MmWorkingSetList, MmWsle, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsProcessType, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), Status, STATUS_INVALID_PARAMETER, STATUS_NOT_LOCKED, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u1, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_AND_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadLargePageSection, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMPFN::WsIndex, and WSLE_NULL_INDEX.