Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmdelay.c File Reference
cmdelay.c File Reference
#include "cmp.h"
Data Structures
struct _CM_DELAY_DEREF_KCB_ITEM
Macros
#define CmpDelayCloseAllocNewEntry() (PCM_DELAYED_CLOSE_ENTRY)CmpAllocateDelayItem()
#define CmpDelayCloseFreeEntry(Item) CmpFreeDelayItem((PVOID)(Item))
#define CmpDelayDerefKCBAllocNewEntry() (PCM_DELAY_DEREF_KCB_ITEM)CmpAllocateDelayItem()
#define CmpDelayDerefKCBFreeEntry(Item) CmpFreeDelayItem((PVOID)(Item))
#define LOCK_DELAY_CLOSE() KeAcquireGuardedMutex(&CmpDelayedCloseTableLock)
#define LOCK_KCB_DELAY_DEREF_LIST() KeAcquireGuardedMutex(&CmpDelayDerefKCBLock)
#define MAX_DELAY_WORKER_ITERATIONS (CmpDelayedCloseSize / 4)
#define UNLOCK_DELAY_CLOSE() KeReleaseGuardedMutex(&CmpDelayedCloseTableLock)
#define UNLOCK_KCB_DELAY_DEREF_LIST() KeReleaseGuardedMutex(&CmpDelayDerefKCBLock)
Typedefs
typedef struct _CM_DELAY_DEREF_KCB_ITEM CM_DELAY_DEREF_KCB_ITEM
typedef struct _CM_DELAY_DEREF_KCB_ITEM * PCM_DELAY_DEREF_KCB_ITEM
Functions
VOID CmpAddToDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN RegLockHeldEx)
VOID CmpArmDelayedCloseTimer (VOID)
VOID CmpArmDelayedCloseTimer ()
VOID CmpDelayCloseDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID CmpDelayCloseWorker (IN PVOID Parameter)
VOID CmpDelayDerefKCBDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID CmpDelayDerefKCBWorker (IN PVOID Parameter)
VOID CmpDelayDerefKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpDoQueueLateUnloadWorker (IN PCMHIVE CmHive)
VOID CmpInitDelayDerefKCBEngine ()
VOID CmpInitializeDelayedCloseTable ()
VOID CmpRemoveFromDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb)
VOID CmpRunDownDelayDerefKCBEngine (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Variables
KDPC CmpDelayCloseDpc
ULONG CmpDelayCloseIntervalInSeconds = 5
KTIMER CmpDelayCloseTimer
WORK_QUEUE_ITEM CmpDelayCloseWorkItem
BOOLEAN CmpDelayCloseWorkItemActive = FALSE
KDPC CmpDelayDerefKCBDpc
ULONG CmpDelayDerefKCBIntervalInSeconds = 5
LIST_ENTRY CmpDelayDerefKCBListHead
KGUARDED_MUTEX CmpDelayDerefKCBLock
KTIMER CmpDelayDerefKCBTimer
WORK_QUEUE_ITEM CmpDelayDerefKCBWorkItem
BOOLEAN CmpDelayDerefKCBWorkItemActive = FALSE
ULONG CmpDelayedCloseElements = 0
ULONG CmpDelayedCloseSize = 2048
KGUARDED_MUTEX CmpDelayedCloseTableLock
LIST_ENTRY CmpDelayedLRUListHead
Macro Definition Documentation
#define CmpDelayCloseAllocNewEntry () (PCM_DELAYED_CLOSE_ENTRY)CmpAllocateDelayItem()
Definition at line 142 of file cmdelay.c.
Referenced by CmpAddToDelayedClose().
#define CmpDelayCloseFreeEntry (Item) CmpFreeDelayItem((PVOID)(Item))
Definition at line 143 of file cmdelay.c.
Referenced by CmpDelayCloseWorker(), and CmpRemoveFromDelayedClose().
#define CmpDelayDerefKCBAllocNewEntry () (PCM_DELAY_DEREF_KCB_ITEM)CmpAllocateDelayItem()
Definition at line 577 of file cmdelay.c.
Referenced by CmpDelayDerefKeyControlBlock().
#define CmpDelayDerefKCBFreeEntry (Item) CmpFreeDelayItem((PVOID)(Item))
Definition at line 578 of file cmdelay.c.
Referenced by CmpDelayDerefKCBWorker(), and CmpRunDownDelayDerefKCBEngine().
#define LOCK_DELAY_CLOSE () KeAcquireGuardedMutex(&CmpDelayedCloseTableLock)
Definition at line 97 of file cmdelay.c.
Referenced by CmpAddToDelayedClose(), CmpDelayCloseWorker(), and CmpRemoveFromDelayedClose().
#define LOCK_KCB_DELAY_DEREF_LIST () KeAcquireGuardedMutex(&CmpDelayDerefKCBLock)
Definition at line 533 of file cmdelay.c.
Referenced by CmpDelayDerefKCBWorker(), CmpDelayDerefKeyControlBlock(), and CmpRunDownDelayDerefKCBEngine().
#define MAX_DELAY_WORKER_ITERATIONS (CmpDelayedCloseSize / 4)
Definition at line 34 of file cmdelay.c.
Referenced by CmpDelayCloseWorker().
#define UNLOCK_DELAY_CLOSE () KeReleaseGuardedMutex(&CmpDelayedCloseTableLock)
Definition at line 98 of file cmdelay.c.
Referenced by CmpAddToDelayedClose(), CmpDelayCloseWorker(), and CmpRemoveFromDelayedClose().
#define UNLOCK_KCB_DELAY_DEREF_LIST () KeReleaseGuardedMutex(&CmpDelayDerefKCBLock)
Definition at line 534 of file cmdelay.c.
Referenced by CmpDelayDerefKCBWorker(), CmpDelayDerefKeyControlBlock(), and CmpRunDownDelayDerefKCBEngine().
Typedef Documentation
typedef struct _CM_DELAY_DEREF_KCB_ITEM CM_DELAY_DEREF_KCB_ITEM
typedef struct _CM_DELAY_DEREF_KCB_ITEM * PCM_DELAY_DEREF_KCB_ITEM
Function Documentation
VOID CmpAddToDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN RegLockHeldEx)
Definition at line 421 of file cmdelay.c.
References ASSERT, ASSERT_KEYBODY_LIST_EMPTY, CM_PAGED_CODE, CmpArmDelayedCloseTimer(), CmpCleanUpKcbCacheWithLock(), CmpDelayCloseAllocNewEntry, CmpDelayCloseWorkItemActive, CmpDelayedCloseElements, CmpDelayedCloseSize, CmpIsKCBLockedExclusive, _CM_DELAYED_CLOSE_ENTRY::DelayedLRUList, FALSE, InsertHeadList(), InterlockedCompareExchange(), InterlockedIncrement, _CM_DELAYED_CLOSE_ENTRY::KeyControlBlock, LOCK_DELAY_CLOSE, NULL, TRUE, and UNLOCK_DELAY_CLOSE.
Referenced by CmpDereferenceKeyControlBlockWithLock().
VOID CmpArmDelayedCloseTimer (VOID)
Referenced by CmpAddToDelayedClose(), and CmpDelayCloseWorker().
VOID CmpArmDelayedCloseTimer ()
Definition at line 297 of file cmdelay.c.
References CM_PAGED_CODE, CmpDelayCloseIntervalInSeconds, CmpDelayCloseWorkItemActive, Int32x32To64, KeSetTimer(), _LARGE_INTEGER::QuadPart, SECOND_MULT, and TRUE.
VOID CmpDelayCloseDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 101 of file cmdelay.c.
References ASSERT, CmpDelayCloseWorkItemActive, DelayedWorkQueue, ExQueueWorkItem(), and UNREFERENCED_PARAMETER.
Referenced by CmpInitializeDelayedCloseTable().
VOID CmpDelayCloseWorker (IN PVOID Parameter)
Definition at line 174 of file cmdelay.c.
References ASSERT, BEGIN_LOCK_CHECKPOINT, _LIST_ENTRY::Blink, CM_PAGED_CODE, CmpArmDelayedCloseTimer(), CmpCleanUpKcbCacheWithLock(), CmpClearListEntry, CmpDelayCloseFreeEntry, CmpDelayCloseWorkItemActive, CmpDelayedCloseElements, CmpDelayedCloseSize, CmpIsListEmpty, CmpLockHashEntryExclusive, CmpLockRegistry(), CmpUnlockHashEntry, CmpUnlockRegistry(), CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_CONTROL_BLOCK::DelayCloseEntry, _CM_KEY_CONTROL_BLOCK::DelayedCloseIndex, _CM_DELAYED_CLOSE_ENTRY::DelayedLRUList, END_LOCK_CHECKPOINT, FALSE, InsertHeadList(), InterlockedDecrement, _CM_DELAYED_CLOSE_ENTRY::KeyControlBlock, LOCK_DELAY_CLOSE, MAX_DELAY_WORKER_ITERATIONS, NULL, _CM_KEY_CONTROL_BLOCK::RefCount, RemoveTailList(), UNLOCK_DELAY_CLOSE, and UNREFERENCED_PARAMETER.
Referenced by CmpInitializeDelayedCloseTable().
VOID CmpDelayDerefKCBDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 537 of file cmdelay.c.
References ASSERT, CmpDelayDerefKCBWorkItemActive, DelayedWorkQueue, ExQueueWorkItem(), and UNREFERENCED_PARAMETER.
Referenced by CmpInitDelayDerefKCBEngine().
VOID CmpDelayDerefKCBWorker (IN PVOID Parameter)
Definition at line 694 of file cmdelay.c.
References ASSERT, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmpClearListEntry, CmpDelayDerefKCBFreeEntry, CmpDelayDerefKCBWorkItemActive, CmpDereferenceKeyControlBlock(), CmpDoQueueLateUnloadWorker(), CmpIsListEmpty, CmpLockRegistry(), CmpUnlockRegistry(), CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::Delete, END_LOCK_CHECKPOINT, FALSE, Hive, IsHiveFrozen, _CM_DELAY_DEREF_KCB_ITEM::Kcb, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_DELAY_DEREF_KCB_ITEM::ListEntry, LOCK_KCB_DELAY_DEREF_LIST, NULL, RemoveHeadList(), TRUE, UNLOCK_KCB_DELAY_DEREF_LIST, and UNREFERENCED_PARAMETER.
Referenced by CmpInitDelayDerefKCBEngine().
VOID CmpDelayDerefKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 780 of file cmdelay.c.
References CM_PAGED_CODE, CmpDelayDerefKCBAllocNewEntry, CmpDelayDerefKCBIntervalInSeconds, CmpDelayDerefKCBWorkItemActive, InsertTailList(), Int32x32To64, InterlockedCompareExchange(), _CM_DELAY_DEREF_KCB_ITEM::Kcb, KeSetTimer(), _CM_DELAY_DEREF_KCB_ITEM::ListEntry, LOCK_KCB_DELAY_DEREF_LIST, LogKCBReference, NULL, _LARGE_INTEGER::QuadPart, _CM_KEY_CONTROL_BLOCK::RefCount, SECOND_MULT, TRUE, and UNLOCK_KCB_DELAY_DEREF_LIST.
Referenced by CmpCleanUpKcbCacheWithLock(), CmpCleanUpKcbValueCache(), and CmpDeleteKeyObject().
VOID CmpDoQueueLateUnloadWorker (IN PCMHIVE CmHive)
Definition at line 186 of file cmdelete.c.
References ASSERT, CM_PAGED_CODE, CmLockHive, CmpLateUnloadHiveWorker(), CmUnlockHive, DelayedWorkQueue, ExAllocatePool, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), InterlockedCompareExchangePointer, NonPagedPool, and NULL.
Referenced by CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), and CmpRunDownDelayDerefKCBEngine().
VOID CmpInitDelayDerefKCBEngine ()
Definition at line 585 of file cmdelay.c.
References CmpDelayDerefKCBDpcRoutine(), CmpDelayDerefKCBWorker(), ExInitializeWorkItem, InitializeListHead(), KeInitializeDpc(), KeInitializeGuardedMutex(), KeInitializeTimer(), and NULL.
Referenced by CmInitSystem1().
VOID CmpInitializeDelayedCloseTable ()
Definition at line 146 of file cmdelay.c.
References CmpDelayCloseDpcRoutine(), CmpDelayCloseWorker(), ExInitializeWorkItem, InitializeListHead(), KeInitializeDpc(), KeInitializeGuardedMutex(), KeInitializeTimer(), and NULL.
Referenced by CmpInitializeCache().
VOID CmpRemoveFromDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 344 of file cmdelay.c.
References ASSERT, CM_PAGED_CODE, CmpDelayCloseFreeEntry, CmpDelayedCloseElements, CmpDelayedCloseSize, CmpIsKCBLockedExclusive, CmpRemoveEntryList, _CM_DELAYED_CLOSE_ENTRY::DelayedLRUList, FALSE, InterlockedCompareExchange(), InterlockedDecrement, LOCK_DELAY_CLOSE, NULL, TRUE, and UNLOCK_DELAY_CLOSE.
Referenced by CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpReferenceKeyControlBlock(), and CmpSearchKeyControlBlockTree().
VOID CmpRunDownDelayDerefKCBEngine (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 599 of file cmdelay.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_PAGED_CODE, CmpClearListEntry, CmpDelayDerefKCBFreeEntry, CmpDereferenceKeyControlBlockWithLock(), CmpDoQueueLateUnloadWorker(), CmpHashTableSize, CmpIsKCBLockedExclusive, CmpIsListEmpty, CmpKCBLockForceAcquireAllowed(), CmpLockHashEntryByIndexExclusive, CmpTryToLockHashEntryByIndexExclusive(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_CONTROL_BLOCK::Delete, FALSE, GET_HASH_INDEX, Hive, InsertHeadList(), IsHiveFrozen, _CM_DELAY_DEREF_KCB_ITEM::Kcb, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_DELAY_DEREF_KCB_ITEM::ListEntry, LOCK_KCB_DELAY_DEREF_LIST, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, RemoveHeadList(), TRUE, and UNLOCK_KCB_DELAY_DEREF_LIST.
Referenced by CmpCleanUpKCBCacheTable(), and CmpFreeAllMemory().
Variable Documentation
KDPC CmpDelayCloseDpc
Definition at line 92 of file cmdelay.c.
ULONG CmpDelayCloseIntervalInSeconds = 5
Definition at line 94 of file cmdelay.c.
Referenced by CmpArmDelayedCloseTimer().
KTIMER CmpDelayCloseTimer
Definition at line 91 of file cmdelay.c.
WORK_QUEUE_ITEM CmpDelayCloseWorkItem
Definition at line 85 of file cmdelay.c.
BOOLEAN CmpDelayCloseWorkItemActive = FALSE
Definition at line 86 of file cmdelay.c.
Referenced by CmpAddToDelayedClose(), CmpArmDelayedCloseTimer(), CmpDelayCloseDpcRoutine(), and CmpDelayCloseWorker().
KDPC CmpDelayDerefKCBDpc
Definition at line 528 of file cmdelay.c.
ULONG CmpDelayDerefKCBIntervalInSeconds = 5
Definition at line 530 of file cmdelay.c.
Referenced by CmpDelayDerefKeyControlBlock().
LIST_ENTRY CmpDelayDerefKCBListHead
Definition at line 522 of file cmdelay.c.
KGUARDED_MUTEX CmpDelayDerefKCBLock
Definition at line 523 of file cmdelay.c.
KTIMER CmpDelayDerefKCBTimer
Definition at line 527 of file cmdelay.c.
WORK_QUEUE_ITEM CmpDelayDerefKCBWorkItem
Definition at line 524 of file cmdelay.c.
BOOLEAN CmpDelayDerefKCBWorkItemActive = FALSE
Definition at line 525 of file cmdelay.c.
Referenced by CmpDelayDerefKCBDpcRoutine(), CmpDelayDerefKCBWorker(), and CmpDelayDerefKeyControlBlock().
ULONG CmpDelayedCloseElements = 0
Definition at line 32 of file cmdelay.c.
Referenced by CmpAddToDelayedClose(), CmpDelayCloseWorker(), and CmpRemoveFromDelayedClose().
ULONG CmpDelayedCloseSize = 2048
Definition at line 31 of file cmdelay.c.
Referenced by CmpAddToDelayedClose(), CmpCreateKeyControlBlock(), CmpDelayCloseWorker(), CmpDumpKeyBodyList(), CmpReferenceKeyControlBlock(), and CmpRemoveFromDelayedClose().
KGUARDED_MUTEX CmpDelayedCloseTableLock
Definition at line 88 of file cmdelay.c.
LIST_ENTRY CmpDelayedLRUListHead
Definition at line 89 of file cmdelay.c.