Windows Research Kernel v1.2: C:/Windows Research Kernel/perf/logging.c File Reference
logging.c File Reference
#include "perfp.h"
Functions
NTSTATUS PerfInfoLogBytes (USHORT HookId, PVOID Data, ULONG BytesToLog)
NTSTATUS PerfInfoReserveBytes (PPERFINFO_HOOK_HANDLE Hook, USHORT HookId, ULONG BytesToReserve)
Function Documentation
NTSTATUS PerfInfoLogBytes (USHORT HookId, PVOID Data, ULONG BytesToLog)
Definition at line 75 of file logging.c.
References NT_SUCCESS, PERF_FINISH_HOOK, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), RtlCopyMemory, Status, and STATUS_SUCCESS.
Referenced by KiCalibrateTimeAdjustment(), KiExecuteDpc(), KiProcessTimerDpcTable(), KiRetireDpcList(), MiDecrementShareCount(), MiDispatchFault(), MiLogPfnInformation(), MmIdentifyPhysicalMemory(), MmInSwapProcess(), MmPerfSnapShotValidPhysicalMemory(), PerfInfoFlushProfileCache(), PerfInfoLogInterrupt(), and PerfProfileInterrupt().
NTSTATUS PerfInfoReserveBytes (PPERFINFO_HOOK_HANDLE Hook, USHORT HookId, ULONG BytesToReserve)
Definition at line 28 of file logging.c.
References FIELD_OFFSET, _WMI_TRACE_PACKET::HookId, MAXUSHORT, NULL, _PERFINFO_TRACE_HEADER::Packet, PERF_ASSERT, PERF_NULL_HOOK_HANDLE, _PERFINFO_HOOK_HANDLE::PerfTraceHeader, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _PERFINFO_HOOK_HANDLE::WmiBufferHeader, and WmiReserveWithPerfHeader().
Referenced by PerfInfoLogBytes(), PerfInfoLogBytesAndUnicodeString(), PerfInfoProcessRunDown(), PerfInfoSysModuleRunDown(), and WmiSetMark().