Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/forksup.c File Reference
forksup.c File Reference
#include "mi.h"
Macros
#define MM_FORK_FAILED 1
#define MM_FORK_SUCCEEDED 0
Functions
VOID MiBuildForkPageTable (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PMMPTE PointerNewPde, IN PFN_NUMBER PdePhysicalPage, IN PMMPFN PfnPdPage, IN LOGICAL MakeValid)
NTSTATUS MiCloneProcessAddressSpace (IN PEPROCESS ProcessToClone, IN PEPROCESS ProcessToInitialize)
ULONG MiDecrementCloneBlockReference (IN PMMCLONE_DESCRIPTOR CloneDescriptor, IN PMMCLONE_BLOCK CloneBlock OPTIONAL, IN PEPROCESS CurrentProcess, IN PMMPTE_FLUSH_LIST PteFlushList OPTIONAL, IN KIRQL OldIrql)
ULONG MiDoneWithThisPageGetAnother (IN PPFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PEPROCESS CurrentProcess)
VOID MiDownShareCountFlushEntireTb (IN PFN_NUMBER PageFrameIndex)
ULONG MiHandleForkTransitionPte (IN PMMPTE PointerPte, IN PMMPTE PointerNewPte, IN PMMCLONE_BLOCK ForkProtoPte)
ULONG MiLeaveThisPageGetAnother (OUT PPFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PEPROCESS CurrentProcess)
VOID MiUpControlAreaRefs (IN PMMVAD Vad)
VOID MiUpForkPageShareCount (IN PMMPFN PfnForkPtePage)
LOGICAL MiWaitForForkToComplete (IN PEPROCESS CurrentProcess)
Macro Definition Documentation
#define MM_FORK_FAILED 1
Definition at line 68 of file forksup.c.
#define MM_FORK_SUCCEEDED 0
Definition at line 67 of file forksup.c.
Function Documentation
VOID MiBuildForkPageTable (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PMMPTE PointerNewPde, IN PFN_NUMBER PdePhysicalPage, IN PMMPFN PfnPdPage, IN LOGICAL MakeValid)
Definition at line 3215 of file forksup.c.
References ActiveAndValid, _MMPFNENTRY::CacheAttribute, DemandZeroPde, _MMPFN::e1, _MMPFN::e2, LOCK_PFN, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_PTE_OWNER_USER, MI_SET_MODIFIED, MI_SET_OWNER_IN_PTE, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiCached, MM_READWRITE, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, TransitionPde, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and ValidPdePde.
Referenced by MiCloneProcessAddressSpace().
NTSTATUS MiCloneProcessAddressSpace (IN PEPROCESS ProcessToClone, IN PEPROCESS ProcessToInitialize)
Definition at line 72 of file forksup.c.
References _MI_PAGING_LEVELS, ASSERT, _EPROCESS::AweInfo, _AWEINFO::AweVadRoot, _MM_AVL_TABLE::BalancedRoot, BYTE_OFFSET, _MMCLONE_DESCRIPTOR::CloneHeader, _MMCLONE_HEADER::ClonePtes, _MMCLONE_BLOCK::CloneRefCount, _EPROCESS::CloneRoot, _MMVAD_FLAGS::CommitCharge, _MMVAD::ControlArea, _MMPFN::e1, _MMVAD::EndingVpn, _MI_PHYSICAL_VIEW::EndingVpn, _MMCLONE_DESCRIPTOR::EndingVpn, _MMPFN::Event, ExAllocatePoolWithTag, ExFreePool(), _MMVAD_FLAGS2::ExtendableFile, _SEGMENT::ExtendInfo, FALSE, _CONTROL_AREA::FilePointer, _MMCLONE_DESCRIPTOR::FinalNumberOfReferences, _EPROCESS::Flags, _CONTROL_AREA::Flags, _EPROCESS::ForkInProgress, _MMPTE::Hard, HighPagePriority, _MMSECTION_FLAGS::Image, _MMVAD_FLAGS2::Inherit, InterlockedIncrement, IS_PTE_NOT_DEMAND_ZERO, KeAcquireGuardedMutexUnsafe(), KeBugCheckEx(), KeDelayExecutionThread(), KeReleaseGuardedMutexUnsafe(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS, LOCK_WS_UNSAFE, _MMPTE::Long, _MMVAD_FLAGS2::LongVad, MDL_PAGES_LOCKED, _MDL::MdlFlags, MEMORY_MANAGEMENT, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_GET_PROTECTION_FROM_WSLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_MAKE_PARENT, MI_MAKE_PROTECT_WRITE_COPY, MI_MAKE_TRANSITION_PTE_VALID, MI_MAKE_VALID_PTE_WRITE_COPY, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PHYSICAL_VIEW_KEY, MI_PTE_LOOKUP_NEEDED, MI_SET_PTE_DIRTY, MI_VPN_TO_VA, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiAddValidPageToWorkingSet(), MiBuildForkPageTable(), MiCheckPdeForPagedPool(), MiCreatePhysicalVadRoot(), MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiDoneWithThisPageGetAnother(), MiDownShareCountFlushEntireTb(), MiEnumerateGenericTableWithoutSplayingAvl(), MiGetFirstClone, MiGetFirstVad, MiGetNextClone, MiGetNextVad, MiGetPdeAddress, MiGetPdeIndex, MiGetPdeOffset, MiGetPpeAddress, MiGetPpeOffset, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiHandleForkTransitionPte(), MiInsertClone, MiInsertNode(), MiInsertVad(), MiInsertVadCharges(), MiIsPteOnPdeBoundary, MiLeaveThisPageGetAnother(), MiLocateCloneAddress, MiLocateWsle(), MiLockPagedAddress(), MiMakePdeExistAndMakeValid(), MiMakeSystemAddressValid(), MiMapSinglePage(), MiProtoAddressForPte, MiPteToProto, MiRemoveClone, MiUnlockPagedAddress(), MiUnmapSinglePage(), MiUpControlAreaRefs(), MiUpForkPageShareCount(), Mm30Milliseconds, MM_DECOMMIT, MM_EXECUTE_READWRITE, MM_HIGHEST_USER_ADDRESS, MM_MAX_COMMIT, MM_NOIRQL, MM_READWRITE, MM_VIEW_SHARE, MM_ZERO_ACCESS, MmCached, MmInitializeMdl, MmMapLockedPagesSpecifyCache(), MmSectionBasedMutex, MmShortTime, MmUnmapLockedPages(), MmWorkingSetList, MmWsle, _MMVAD_FLAGS2::MultipleSecured, _MMVAD_FLAGS::NoChange, NonPagedPool, NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfPrivatePages, _MMCLONE_HEADER::NumberOfProcessReferences, _MMCLONE_HEADER::NumberOfPtes, _MMCLONE_DESCRIPTOR::NumberOfPtes, _MMCLONE_DESCRIPTOR::NumberOfReferences, _MMVAD_FLAGS2::OneSecured, _MMPFN::OriginalPte, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PagedPool, _MMCLONE_DESCRIPTOR::PagedPoolQuotaCharge, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMADDRESS_NODE::Parent, _MMVAD::Parent, _MI_PHYSICAL_VIEW::Parent, _MMCLONE_DESCRIPTOR::Parent, PD_PER_SYSTEM, PDE_BASE, _EPROCESS::PeakVirtualSize, _EPROCESS::PhysicalVadRoot, _MMVAD_FLAGS::PrivateMemory, _MMPTE_SOFTWARE::Protection, _MMVAD_FLAGS::Protection, _MMPTE::Proto, _MMCLONE_BLOCK::ProtoPte, _MMPTE_SOFTWARE::Prototype, _MMPTE_PROTOTYPE::Prototype, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_FORK_FAILED, PS_PROCESS_FLAGS_VM_DELETED, PS_SET_BITS, PsChargeProcessNonPagedPoolQuota(), PsChargeProcessPagedPoolQuota(), PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMEXTEND_INFO::ReferenceCount, RtlCopyMemory, RtlZeroMemory, _MMVAD_FLAGS2::SecNoChange, _CONTROL_AREA::Segment, _MMPFN::ShareCount, _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, _MMCLONE_DESCRIPTOR::StartingVpn, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PAGE_PROTECTION, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMVAD::u, _MMADDRESS_NODE::u1, _MMPFN::u1, _MMVAD::u1, _MI_PHYSICAL_VIEW::u1, _MMCLONE_DESCRIPTOR::u1, _MMPFN::u2, _MMVAD::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, UNLOCK_WS, UNLOCK_WS_UNSAFE, _MMWSL::UsedPageTableEntries, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD::VadFlags2, VadImageMap, VadLargePages, VadLargePageSection, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, _EPROCESS::VirtualSize, _CONTROL_AREA::WritableUserReferences, _MMPFN::WsIndex, and WSLE_NULL_INDEX.
Referenced by MmInitializeProcessAddressSpace().
ULONG MiDecrementCloneBlockReference (IN PMMCLONE_DESCRIPTOR CloneDescriptor, IN PMMCLONE_BLOCK CloneBlock OPTIONAL, IN PEPROCESS CurrentProcess, IN PMMPTE_FLUSH_LIST PteFlushList OPTIONAL, IN KIRQL OldIrql)
Definition at line 2464 of file forksup.c.
References ARGUMENT_PRESENT, ASSERT, _MMCLONE_HEADER::ClonePtes, _MMPFN::e1, _MMPFN::e2, ExFreePool(), FALSE, FreePageList, _MMPTE::Hard, InterlockedDecrement, IS_PTE_NOT_DEMAND_ZERO, LOCK_PFN, LOCK_WS_REGARDLESS, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiFlushPteList(), MiInsertPageInFreeList(), MiIsAddressValid(), MiMakeSystemAddressValidPfnWs(), MiReleasePageFileSpace(), MiRemoveClone, MiUnlinkPageFromList(), MiWaitForForkToComplete(), NULL, _MMCLONE_HEADER::NumberOfProcessReferences, _MMCLONE_HEADER::NumberOfPtes, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Prototype, PS_PROCESS_FLAGS_FORK_FAILED, PsGetCurrentProcess(), PsGetCurrentThread(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), _MMPFN::PteFrame, _MMPTE::Soft, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WS_REGARDLESS, and _MMPTE_HARDWARE::Valid.
Referenced by MiCopyOnWrite(), MiDeletePte(), MiDeletePteList(), and MiDispatchFault().
ULONG MiDoneWithThisPageGetAnother (IN PPFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PEPROCESS CurrentProcess)
Definition at line 2939 of file forksup.c.
References BadPageList, _MMPFN::e1, FALSE, LOCK_PFN, MI_PAGE_COLOR_PTE_PROCESS, MI_PFN_ELEMENT, MiDecrementShareCount(), MiEnsureAvailablePageOrWait(), MiRemoveZeroPage(), MM_HIGH_LIMIT, MmAvailablePages, _MMPFNENTRY::PageLocation, _MMPFN::u3, UNLOCK_PFN, and UNREFERENCED_PARAMETER.
Referenced by MiCloneProcessAddressSpace().
VOID MiDownShareCountFlushEntireTb (IN PFN_NUMBER PageFrameIndex)
Definition at line 3169 of file forksup.c.
References FALSE, LOCK_PFN, MI_FLUSH_PROCESS_TB, MI_PFN_ELEMENT, MiDecrementShareCount(), and UNLOCK_PFN.
Referenced by MiCloneProcessAddressSpace().
ULONG MiHandleForkTransitionPte (IN PMMPTE PointerPte, IN PMMPTE PointerNewPte, IN PMMCLONE_BLOCK ForkProtoPte)
Definition at line 3034 of file forksup.c.
References ASSERT, _MMPFN::e1, FALSE, _MMPTE::Hard, KeBugCheckEx(), LOCK_PFN, _MMPTE::Long, MEMORY_MANAGEMENT, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_PROTECT_WRITE_COPY, MI_PFN_ELEMENT, MI_WRITE_INVALID_PTE, MiCheckPdeForPagedPool(), MiDecrementShareCount(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiProtoAddressForPte, NT_SUCCESS, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::Proto, _MMPTE_SOFTWARE::Prototype, _MMPTE_PROTOTYPE::Prototype, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiCloneProcessAddressSpace().
ULONG MiLeaveThisPageGetAnother (OUT PPFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PEPROCESS CurrentProcess)
Definition at line 2994 of file forksup.c.
References BadPageList, _MMPFN::e1, FALSE, LOCK_PFN, MI_PAGE_COLOR_PTE_PROCESS, MI_PFN_ELEMENT, MiEnsureAvailablePageOrWait(), MiRemoveZeroPage(), MM_HIGH_LIMIT, MmAvailablePages, _MMPFNENTRY::PageLocation, _MMPFN::u3, UNLOCK_PFN, and UNREFERENCED_PARAMETER.
Referenced by MiCloneProcessAddressSpace().
VOID MiUpControlAreaRefs (IN PMMVAD Vad)
Definition at line 2888 of file forksup.c.
References _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::Image, LOCK_PFN, MiLocateSubsection(), MiReferenceSubsection(), _MSUBSECTION::NextSubsection, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfUserReferences, _MMSECTION_FLAGS::PhysicalMemory, _CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by MiCloneProcessAddressSpace().
VOID MiUpForkPageShareCount (IN PMMPFN PfnForkPtePage)
Definition at line 3201 of file forksup.c.
References LOCK_PFN, and UNLOCK_PFN.
Referenced by MiCloneProcessAddressSpace().
LOGICAL MiWaitForForkToComplete (IN PEPROCESS CurrentProcess)
Definition at line 2810 of file forksup.c.
References FALSE, LOCK_ADDRESS_SPACE, LOCK_WS_REGARDLESS, PsGetCurrentThread(), TRUE, UNLOCK_ADDRESS_SPACE, and UNLOCK_WS_REGARDLESS.
Referenced by MiCopyOnWrite(), MiDecrementCloneBlockReference(), MiResolveDemandZeroFault(), and MmAccessFault().