Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/assert.c File Reference
assert.c File Reference
#include <nt.h>
#include <ntrtl.h>
#include <zwapi.h>
Macros
#define RTL_ASSERT_ALWAYS_ENABLED 1
Typedefs
typedef CONST CHAR * PCSTR
Functions
NTSYSAPI VOID NTAPI RtlAssert (__in PVOID VoidFailedAssertion, __in PVOID VoidFileName, __in ULONG LineNumber, __in_opt PSTR MutableMessage)
Macro Definition Documentation
#define RTL_ASSERT_ALWAYS_ENABLED 1
Definition at line 31 of file assert.c.
Typedef Documentation
typedef CONST CHAR* PCSTR
Definition at line 39 of file assert.c.
Function Documentation
NTSYSAPI VOID NTAPI RtlAssert (__in PVOID VoidFailedAssertion, __in PVOID VoidFileName, __in ULONG LineNumber, __in_opt PSTR MutableMessage)
Definition at line 50 of file assert.c.
References CONST, DbgBreakPoint(), DbgPrint(), DbgPrompt(), NtCurrentProcess, NtCurrentThread, RtlCaptureContext(), STATUS_UNSUCCESSFUL, TRUE, ZwTerminateProcess(), and ZwTerminateThread().