Windows Research Kernel v1.2: C:/Windows Research Kernel/init/initos.c File Reference
initos.c File Reference
#include "ntos.h"
#include "ntimage.h"
#include <zwapi.h>
#include <ntdddisk.h>
#include <kddll.h>
#include <setupblk.h>
#include <fsrtl.h>
#include "stdlib.h"
#include "stdio.h"
#include <string.h>
#include <inbv.h>
Data Structures
struct _EXLOCK
Typedefs
typedef struct _EXLOCK EXLOCK
typedef struct _EXLOCK * PEXLOCK
Functions
VOID CmpInitSystemVersion (IN ULONG stage, IN PVOID param)
NTSTATUS CreateSystemRootLink (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID DisplayBootBitmap (IN BOOLEAN DisplayOnScreen)
PFN_COUNT ExBurnMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_COUNT NumberOfPagesToBurn, IN TYPE_OF_MEMORY MemoryTypeForRemovedPages, IN PMEMORY_ALLOCATION_DESCRIPTOR NewMemoryDescriptor OPTIONAL)
NTSTATUS ExpAcquireLockRoutine (PEXLOCK Lock)
VOID ExpInitializeExecutive (IN ULONG Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS ExpInitializeLockRoutine (PEXLOCK Lock)
BOOLEAN ExpIsLoaderValid (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN ExpOkayToLockRoutine (IN PEXLOCK Lock)
NTKERNELAPI BOOLEAN ExpRefreshTimeZoneInformation (IN PLARGE_INTEGER CurrentUniversalTime)
NTSTATUS ExpReleaseLockRoutine (PEXLOCK Lock)
VOID FinalizeBootLogo (VOID)
VOID HeadlessInit (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID KiInitializeInterruptTimers (VOID)
NTSTATUS LookupEntryPoint (IN PVOID DllBase, IN PSZ NameOfEntryPoint, OUT PVOID *AddressOfEntryPoint)
static USHORT NameToOrdinal (IN PSZ NameOfEntryPoint, IN ULONG_PTR DllBase, IN ULONG NumberOfNames, IN PULONG NameTableBase, IN PUSHORT NameOrdinalTableBase)
VOID Phase1Initialization (IN PVOID Context)
VOID Phase1InitializationDiscard (IN PVOID Context)
NTSTATUS RtlFormatBuffer2 (PCHAR Buffer, size_t BufferLen, PCHAR FormatString, PVOID Param0, PVOID Param1)
NTSTATUS RtlInitializeStackTraceDataBase (IN PVOID CommitBase, IN SIZE_T CommitSize, IN SIZE_T ReserveSize)
Variables
PVOID BBTBuffer
MEMORY_ALLOCATION_DESCRIPTOR BBTMemoryDescriptor
PFN_COUNT BBTPagesToReserve
UCHAR CmProcessorMismatch
BOOLEAN InbvBootDriverInstalled
volatile BOOLEAN InitForceInline = FALSE
ULONG InitializationPhase
BOOLEAN InitIsWinPEMode
PVOID InitNlsTableBase
ULONG InitNlsTableSize
NLSTABLEINFO InitTableInfo
ULONG InitWinPEModeType
BOOLEAN KdBreakAfterSymbolLoad
ULONG KdpTimeSlipPending
PMESSAGE_RESOURCE_DATA KiBugCodeMessages
ULONG KiServiceLimit
ULONG NtGlobalFlag
WCHAR NtInitialUserProcessBuffer [128] = L"\\SystemRoot\\System32\\smss.exe"
ULONG NtInitialUserProcessBufferLength
ULONG NtInitialUserProcessBufferType = REG_SZ
UNICODE_STRING NtSystemRoot
ULONG PoolHitTag
Typedef Documentation
typedef struct _EXLOCK EXLOCK
typedef struct _EXLOCK * PEXLOCK
Function Documentation
VOID CmpInitSystemVersion (IN ULONG stage, IN PVOID param)
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTSTATUS CreateSystemRootLink (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 1869 of file initos.c.
References DIRECTORY_ALL_ACCESS, INIT_SYSTEMROOT_LINKNAME, InitializeObjectAttributes, KeBugCheckEx(), NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NtCreateSymbolicLinkObject(), NULL, OBJ_CASE_INSENSITIVE, OBJ_PERMANENT, RtlAnsiStringToUnicodeString(), RtlFormatBuffer2(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitString(), RtlInitUnicodeString(), SePublicDefaultUnrestrictedSd, STATUS_SUCCESS, SYMBOLIC_INITIALIZATION_FAILED, SYMBOLIC_LINK_ALL_ACCESS, TRUE, and VOID.
Referenced by Phase1InitializationDiscard().
VOID DisplayBootBitmap (IN BOOLEAN DisplayOnScreen)
Referenced by Phase1InitializationDiscard().
PFN_COUNT ExBurnMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_COUNT NumberOfPagesToBurn, IN TYPE_OF_MEMORY MemoryTypeForRemovedPages, IN PMEMORY_ALLOCATION_DESCRIPTOR NewMemoryDescriptor OPTIONAL)
Referenced by ExpInitializeExecutive().
NTSTATUS ExpAcquireLockRoutine (PEXLOCK Lock)
Definition at line 204 of file initos.c.
References ExAcquireSpinLock, _EXLOCK::Irql, _EXLOCK::SpinLock, and STATUS_SUCCESS.
VOID ExpInitializeExecutive (IN ULONG Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 242 of file initos.c.
References _enable(), _memicmp(), _strupr(), ANSI_NULL, ASSERT, atol(), _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CmpInitSystemVersion(), CONTAINING_RECORD, Count, _KSERVICE_TABLE_DESCRIPTOR::Count, DBG_STATUS_CONTROL_C, DbgBreakPointWithStatus(), DbgkInitialize(), DbgLoadImageSymbols(), _KLDR_DATA_TABLE_ENTRY::DllBase, ExAllocatePoolWithTag, ExBurnMemory(), ExComputeTickCountMultiplier(), ExInitializeHandleTablePackage(), ExInitPoolLookasidePointers(), ExInitSystem(), ExpInTextModeSetup, ExpIsLoaderValid(), ExpTickCountMultiplier, FALSE, FLG_ENABLE_CLOSE_EXCEPTIONS, FLG_ENABLE_EXCEPTION_LOGGING, FLG_ENABLE_KDEBUG_SYMBOL_LOAD, FLG_KERNEL_STACK_TRACE_DB, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, HAL_INITIALIZATION_FAILED, HalInitSystem(), HeadlessInit(), IMAGE_FILE_MACHINE_AMD64, IMAGE_FILE_MACHINE_I386, InitAnsiCodePageDataOffset, InitializationPhase, InitOemCodePageDataOffset, InitUnicodeCaseTableDataOffset, IoRemoteBootClient, KdBreakAfterSymbolLoad, KdPrint, KeAdjustInterruptTime(), KeBugCheck(), KeBugCheckEx(), KeMaximumIncrement, KeNumaInitialize(), KeServiceDescriptorTable, KeServiceDescriptorTableShadow, KiServiceLimit, LdrAccessResource(), LdrFindResource_U(), _STRING::Length, _UNICODE_STRING::Length, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderBad, LoaderBBTMemory, LoaderNlsData, MAX_EXCEPTION_LOG, _UNICODE_STRING::MaximumLength, MAXULONG, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MISMATCHED_HAL, MM_HIGHEST_USER_ADDRESS, MmInitSystem(), MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSystemRangeStart, MmVerifyImageIsOkForMpUse(), NonPagedPool, NT_SUCCESS, NtGlobalFlag, NtMajorVersion, NtMinorVersion, NULL, ObInitSystem(), OBJECT_INITIALIZATION_FAILED, PAGE_SIZE, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, PERFINFO_INIT_TRACEFLAGS, PHASE0_INITIALIZATION_FAILED, PP0_INITIALIZATION_FAILED, PpInitSystem(), PROCESS_INITIALIZATION_FAILED, PsInitSystem(), RtlAnsiStringToUnicodeString(), RtlCopyMemory, RtlFormatBuffer2(), RtlInitializeExceptionLog(), RtlInitializeStackTraceDataBase(), RtlInitNlsTables(), RtlInitString(), RtlResetRtlTranslations(), RtlZeroMemory, SECURITY_INITIALIZATION_FAILED, SeInitSystem(), SESSION3_INITIALIZATION_FAILED, SETUPBLK_FLAGS_IS_REMOTE_BOOT, SETUPBLK_FLAGS_IS_TEXTMODE, SharedUserData, Status, STATUS_NO_MEMORY, strstr(), TRUE, UP_DRIVER_ON_MP_SYSTEM, and VOID.
Referenced by KiInitializeKernel().
NTSTATUS ExpInitializeLockRoutine (PEXLOCK Lock)
Definition at line 195 of file initos.c.
References KeInitializeSpinLock(), _EXLOCK::SpinLock, and STATUS_SUCCESS.
BOOLEAN ExpIsLoaderValid (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by ExpInitializeExecutive().
BOOLEAN ExpOkayToLockRoutine (IN PEXLOCK Lock)
Definition at line 187 of file initos.c.
References TRUE.
NTKERNELAPI BOOLEAN ExpRefreshTimeZoneInformation (IN PLARGE_INTEGER CurrentUniversalTime)
Referenced by Phase1InitializationDiscard().
NTSTATUS ExpReleaseLockRoutine (PEXLOCK Lock)
Definition at line 213 of file initos.c.
References ExReleaseSpinLock, _EXLOCK::Irql, _EXLOCK::SpinLock, and STATUS_SUCCESS.
VOID FinalizeBootLogo (VOID)
Referenced by Phase1InitializationDiscard().
VOID HeadlessInit (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by ExpInitializeExecutive().
VOID KiInitializeInterruptTimers (VOID)
Definition at line 1149 of file intobj.c.
References KISRTIMERINIT::Dpc, ExAllocatePoolWithTag, KeFeatureBits, KeInitializeDpc(), KeInitializeTimerEx(), KeSetTimerEx(), KF_RDTSC, KiInitializeInterruptTimersDpc(), KiTimeLimitIsrMicroseconds, NonPagedPool, NULL, _LARGE_INTEGER::QuadPart, KISRTIMERINIT::SampleTimer, and SynchronizationTimer.
Referenced by Phase1InitializationDiscard().
NTSTATUS LookupEntryPoint (IN PVOID DllBase, IN PSZ NameOfEntryPoint, OUT PVOID * AddressOfEntryPoint)
Definition at line 2003 of file initos.c.
References _IMAGE_EXPORT_DIRECTORY::AddressOfFunctions, _IMAGE_EXPORT_DIRECTORY::AddressOfNameOrdinals, _IMAGE_EXPORT_DIRECTORY::AddressOfNames, DbgPrint(), IMAGE_DIRECTORY_ENTRY_EXPORT, NameToOrdinal(), _IMAGE_EXPORT_DIRECTORY::NumberOfFunctions, _IMAGE_EXPORT_DIRECTORY::NumberOfNames, RtlImageDirectoryEntryToData(), STATUS_INVALID_PARAMETER, STATUS_PROCEDURE_NOT_FOUND, STATUS_SUCCESS, strcpy(), strlen(), and TRUE.
Referenced by MmLoadSystemImage(), and PspLookupSystemDllEntryPoint().
static USHORT NameToOrdinal (IN PSZ NameOfEntryPoint, IN ULONG_PTR DllBase, IN ULONG NumberOfNames, IN PULONG NameTableBase, IN PUSHORT NameOrdinalTableBase) static
Definition at line 2066 of file initos.c.
References strcmp().
Referenced by LookupEntryPoint().
VOID Phase1Initialization (IN PVOID Context)
Definition at line 923 of file initos.c.
References MmZeroPageThread(), and Phase1InitializationDiscard().
Referenced by PspInitPhase0().
VOID Phase1InitializationDiscard (IN PVOID Context)
Definition at line 934 of file initos.c.
References _strupr(), atol(), _UNICODE_STRING::Buffer, CACHE_INITIALIZATION_FAILED, CcInitializeCacheManager(), CcPfInitializePrefetcher(), CmInitSystem1(), CmpInitSystemVersion(), CmProcessorMismatch, CONFIG_INITIALIZATION_FAILED, CONTAINING_RECORD, CreateSystemRootLink(), DisplayBootBitmap(), _KLDR_DATA_TABLE_ENTRY::DllBase, DOS_MAX_PATH_LENGTH, ERROR_LOG_MAXIMUM_SIZE, _IO_ERROR_LOG_PACKET::ErrorCode, ExAllocatePoolWithTag, ExCmosClockIsSane, ExFreePool(), ExInitSystem(), ExInitSystemPhase2(), ExLocalTimeToSystemTime(), ExpAltTimeZoneBias, ExpLastTimeZoneBias, ExpRealTimeIsUniversal, ExpRefreshTimeZoneInformation(), ExpTimeZoneBias, FALSE, FILE_INITIALIZATION_FAILED, FinalizeBootLogo(), _IO_ERROR_LOG_PACKET::FinalStatus, _LIST_ENTRY::Flink, FsRtlInitSystem(), HAL1_INITIALIZATION_FAILED, HalAllProcessorsStarted(), HalInitSystem(), HalQueryRealTimeClock(), HalReportResourceUsage(), _LARGE_INTEGER::HighPart, InbvBootDriverInstalled, InbvDriverInitialize(), InbvEnableBootDriver(), InbvEnableDisplayString(), InbvNotifyDisplayOwnershipLost(), InbvSetProgressBarSubset(), InbvUpdateProgressBar(), INIT_WINPEMODE_INRAM, INIT_WINPEMODE_REGULAR, InitAnsiCodePageDataOffset, InitializationPhase, InitNlsSectionPointer, InitNlsTableSize, InitOemCodePageDataOffset, InitUnicodeCaseTableDataOffset, Int32x32To64, INTERNAL_POWER_ERROR, IO1_INITIALIZATION_FAILED, IoAllocateGenericErrorLogEntry(), IoInitSystem(), IoWriteErrorLogEntry(), KdDebuggerInitialize1(), KdInitSystem(), KdPrint, KdpTimeSlipPending, KeActiveProcessors, KeAreApcsDisabled(), KeBootTime, KeBootTimeBias, KeBugCheck(), KeBugCheckEx(), KeEnterGuardedRegion(), KeGetCurrentThread(), KeI386VdmInitialize(), KeInitSystem(), KeLeaveGuardedRegion(), KeLoaderBlock, KeRaiseIrqlToDpcLevel(), KernelMode, KeSetAffinityProcess(), KeSetPriorityThread(), KeSetSystemTime(), KeStartAllProcessors(), KeTryToAcquireGuardedMutex(), KiInitializeInterruptTimers(), _UNICODE_STRING::Length, _LOADER_PARAMETER_BLOCK::LoadOptions, _LOADER_PARAMETER_BLOCK::LoadOrderListHead, _LARGE_INTEGER::LowPart, LPC_INITIALIZATION_FAILED, LpcInitSystem(), MAXIMUM_PRIORITY, _UNICODE_STRING::MaximumLength, MEM_COMMIT, MEM_RELEASE, MEMORY1_INITIALIZATION_FAILED, MmFreeLoaderBlock(), MmInitSystem(), MmMapViewInSystemCache(), MmMapViewOfSection(), MmSectionObjectType, MmUnmapViewInSystemCache(), NonPagedPool, NT_SUCCESS, NtCurrentProcess, NtInitialUserProcessBuffer, NtInitialUserProcessBufferLength, NtSystemRoot, NULL, NullString, ObInitSystem(), OBJ_CASE_INSENSITIVE, OBJECT1_INITIALIZATION_FAILED, ObReferenceObjectByHandle, PAGE_READWRITE, PAGE_SIZE, PHASE1_INITIALIZATION_FAILED, PoInitSystem(), PoNotifySystemTimeSet(), PoolHitTag, PP1_INITIALIZATION_FAILED, PpInitSystem(), Priority, _KTHREAD::Process, _RTL_USER_PROCESS_INFORMATION::Process, PROCESS1_INITIALIZATION_FAILED, PsGetCurrentProcess(), PsGetCurrentThread(), PsInitSystem(), _LARGE_INTEGER::QuadPart, REFMON_INITIALIZATION_FAILED, REG_SZ, RTL_USER_PROC_PARAMS_NORMALIZED, RTL_USER_PROC_RESERVE_1MB, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyMemory, RtlCopyUnicodeString(), RtlCreateUserProcess(), RtlDeNormalizeProcessParams(), RtlFindMessage(), RtlInitializeRangeListPackage(), RtlInitNlsTables(), RtlResetRtlTranslations(), RtlTimeFieldsToTime(), SEC_COMMIT, SECTION_ALL_ACCESS, SECURITY1_INITIALIZATION_FAILED, SeInitSystem(), SeRmInitPhase1(), SESSION1_INITIALIZATION_FAILED, SESSION2_INITIALIZATION_FAILED, SESSION3_INITIALIZATION_FAILED, SESSION4_INITIALIZATION_FAILED, SESSION5_INITIALIZATION_FAILED, SharedUserData, Status, STATUS_INVALID_PARAMETER, STATUS_MP_PROCESSOR_MISMATCH, STATUS_NO_MEMORY, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, strstr(), SYMBOLIC_INITIALIZATION_FAILED, _ETHREAD::Tcb, _MESSAGE_RESOURCE_ENTRY::Text, _RTL_USER_PROCESS_INFORMATION::Thread, TRUE, UNICODE_NULL, _IO_ERROR_LOG_PACKET::UniqueErrorValue, ViewShare, WINDOWS_NT_MP_STRING, _TIME_FIELDS::Year, ZwAllocateVirtualMemory(), ZwClose(), ZwCreateSection(), ZwFreeVirtualMemory(), ZwResumeThread(), ZwSetSystemTime(), and ZwWaitForSingleObject().
Referenced by Phase1Initialization().
NTSTATUS RtlFormatBuffer2 (PCHAR Buffer, size_t BufferLen, PCHAR FormatString, PVOID Param0, PVOID Param1)
Referenced by CreateSystemRootLink(), and ExpInitializeExecutive().
NTSTATUS RtlInitializeStackTraceDataBase (IN PVOID CommitBase, IN SIZE_T CommitSize, IN SIZE_T ReserveSize)
Definition at line 212 of file stktrace.c.
References _STACK_TRACE_DATABASE::Buckets, _STACK_TRACE_DATABASE::CommitBase, _STACK_TRACE_DATABASE::CurrentLowerCommitLimit, _STACK_TRACE_DATABASE::CurrentUpperCommitLimit, _STACK_TRACE_DATABASE::EntryIndexArray, FALSE, INITIALIZE_DATABASE_LOCK, KdPrint, _STACK_TRACE_DATABASE::Lock, MEM_COMMIT, _STACK_TRACE_DATABASE::NextFreeLowerMemory, _STACK_TRACE_DATABASE::NextFreeUpperMemory, NT_SUCCESS, NtCurrentProcess, NUMBER_OF_BUCKETS, _STACK_TRACE_DATABASE::NumberOfBuckets, PAGE_READWRITE, _STACK_TRACE_DATABASE::PreCommitted, ROUND_TO_PAGES, RtlZeroMemory, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, and ZwAllocateVirtualMemory().
Referenced by ExpInitializeExecutive().
Variable Documentation
PVOID BBTBuffer
MEMORY_ALLOCATION_DESCRIPTOR BBTMemoryDescriptor
PFN_COUNT BBTPagesToReserve
Definition at line 234 of file initos.c.
Referenced by MiMapBBTMemory(), and MmInitSystem().
UCHAR CmProcessorMismatch
Referenced by Phase1InitializationDiscard().
BOOLEAN InbvBootDriverInstalled
Referenced by Phase1InitializationDiscard().
volatile BOOLEAN InitForceInline = FALSE
Definition at line 232 of file initos.c.
ULONG InitializationPhase
Definition at line 155 of file initos.c.
Referenced by ExInitSystem(), ExpInitializeExecutive(), ExRecordCallerInHashTable(), IopMountVolume(), KiOpPatchCode(), MiChargeCommitment(), MiFindContiguousPages(), MiInitMachineDependent(), MiReloadBootLoadedDrivers(), MiZeroInParallel(), ObInitSystem(), Phase1InitializationDiscard(), PsInitSystem(), and SeInitSystem().
BOOLEAN InitIsWinPEMode
PVOID InitNlsTableBase
ULONG InitNlsTableSize
Referenced by Phase1InitializationDiscard().
NLSTABLEINFO InitTableInfo
Definition at line 233 of file initos.c.
ULONG InitWinPEModeType
BOOLEAN KdBreakAfterSymbolLoad
Referenced by ExpInitializeExecutive().
ULONG KdpTimeSlipPending
Referenced by Phase1InitializationDiscard().
PMESSAGE_RESOURCE_DATA KiBugCodeMessages
Definition at line 305 of file kernldat.c.
Referenced by KeGetBugMessageText().
ULONG KiServiceLimit
Referenced by ExpInitializeExecutive(), KiInitializeKernel(), and KiInitSystem().
ULONG NtGlobalFlag
Definition at line 152 of file initos.c.
Referenced by ExInitializeResourceLite(), ExMapHandleToPointerEx(), ExpInitializeExecutive(), IoInitSystem(), MiLoadImageSection(), MiMapViewOfImageSection(), MmCreatePeb(), MmInPageKernelStack(), MmLoadSystemImage(), MmOutPageKernelStack(), NtQuerySystemInformation(), NtSetSystemInformation(), ObCreateObjectType(), ObDupHandleProcedure(), ObDuplicateObject(), ObInitSystem(), ObpCaptureHandleInformation(), ObpCaptureHandleInformationEx(), ObpCloseHandle(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObpEnumFindHandleProcedure(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PEBTEB_STRUCT(), RtlDispatchException(), and RtlGetNtGlobalFlags().
WCHAR NtInitialUserProcessBuffer[128] = L"\\SystemRoot\\System32\\smss.exe"
Definition at line 167 of file initos.c.
Referenced by Phase1InitializationDiscard().
ULONG NtInitialUserProcessBufferLength
Initial value:
=
    sizeof(NtInitialUserProcessBuffer) - sizeof(WCHAR)
Definition at line 168 of file initos.c.
Referenced by Phase1InitializationDiscard().
ULONG NtInitialUserProcessBufferType = REG_SZ
Definition at line 170 of file initos.c.
UNICODE_STRING NtSystemRoot
Definition at line 33 of file initos.c.
Referenced by IoInitSystem(), Phase1InitializationDiscard(), and WmipDelayCreate().
ULONG PoolHitTag
Definition at line 228 of file initos.c.
Referenced by Phase1InitializationDiscard().