Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/notify.c File Reference
notify.c File Reference
#include "wmikmp.h"
Functions
void WmipEventNotification (IN PVOID Context)
void WmipInitializeNotifications (void)
Variables
LONG WmipEventWorkItems
WORK_QUEUE_ITEM WmipEventWorkQueueItem
LIST_ENTRY WmipNPEvent = {&WmipNPEvent, &WmipNPEvent}
KSPIN_LOCK WmipNPNotificationSpinlock
Function Documentation
void WmipEventNotification (IN PVOID Context)
Definition at line 57 of file notify.c.
References _WNODE_HEADER::ClientContext, CONTAINING_RECORD, ExFreePool(), ExInterlockedRemoveHeadList(), FALSE, InterlockedDecrement, _WNODE_HEADER::Linkage, NULL, PAGED_CODE, EVENTWORKCONTEXT::RegEntry, TRUE, UNREFERENCED_PARAMETER, _WNODE_HEADER::Version, WmipAssert, WmipEventWorkItems, WmipNPNotificationSpinlock, WmipProcessEvent(), WmipUnreferenceRegEntry, and EVENTWORKCONTEXT::Wnode.
Referenced by WmipInitializeNotifications().
void WmipInitializeNotifications (void)
Definition at line 43 of file notify.c.
References ExInitializeWorkItem, KeInitializeSpinLock(), NULL, PAGED_CODE, WmipEventNotification(), and WmipNPNotificationSpinlock.
Referenced by WmipDriverEntry().
Variable Documentation
LONG WmipEventWorkItems
Definition at line 38 of file notify.c.
Referenced by IoWMIWriteEvent(), and WmipEventNotification().
WORK_QUEUE_ITEM WmipEventWorkQueueItem
Definition at line 35 of file notify.c.
Referenced by IoWMIWriteEvent().
LIST_ENTRY WmipNPEvent = {&WmipNPEvent, &WmipNPEvent}
Definition at line 36 of file notify.c.
Referenced by IoWMIWriteEvent().
KSPIN_LOCK WmipNPNotificationSpinlock
Definition at line 37 of file notify.c.
Referenced by IoWMIWriteEvent(), WmipEventNotification(), and WmipInitializeNotifications().