Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/eventobj.c File Reference
eventobj.c File Reference
#include "ki.h"
Macros
#define ASSERT_EVENT(E)
#define ASSERT_EVENT_PAIR(E)
Functions
VOID KeClearEvent (__inout PRKEVENT Event)
VOID KeInitializeEvent (__out PRKEVENT Event, __in EVENT_TYPE Type, __in BOOLEAN State)
VOID KeInitializeEventPair (__inout PKEVENT_PAIR EventPair)
LONG KePulseEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
LONG KeReadStateEvent (__in PRKEVENT Event)
LONG KeResetEvent (__inout PRKEVENT Event)
LONG KeSetEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
VOID KeSetEventBoostPriority (__inout PRKEVENT Event, __in_opt PRKTHREAD *Thread)
Macro Definition Documentation
#define ASSERT_EVENT (E)
Value:
{                             \
    ASSERT((E)->Header.Type == NotificationEvent ||   \
           (E)->Header.Type == SynchronizationEvent); \
}
Definition at line 31 of file eventobj.c.
Referenced by KeClearEvent(), KePulseEvent(), KeReadStateEvent(), KeResetEvent(), and KeSetEvent().
#define ASSERT_EVENT_PAIR (E)
Value:
{                        \
    ASSERT((E)->Type == EventPairObject);             \
}
Definition at line 42 of file eventobj.c.
Function Documentation
VOID KeClearEvent (__inout PRKEVENT Event)
Definition at line 130 of file eventobj.c.
References ASSERT_EVENT.
Referenced by BuildQueryDirectoryIrp(), CcWaitOnActiveCount(), ExSwapinWorkerThreads(), ExUnregisterCallback(), HalpGetFullGeometry(), HalpQueryDriveLayout(), IoCancelFileOpen(), IopCloseFile(), IopDeleteFile(), IopGetSetSecurityObject(), IopInvalidateVolumesForDevice(), IopMountVolume(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopShutdownBaseFileSystems(), IopXxxControlFile(), IoSetInformation(), IoShutdownSystem(), MiAllocatePoolPages(), MiCleanSection(), MiCreateImageFileMap(), MiDereferenceSegmentThread(), MiEnsureAvailablePageOrWait(), MiFindContiguousMemoryInPool(), MiFlushSectionInternal(), MiFreeInPageSupportBlock(), MiFreePoolPages(), MiGetEventCounter(), MiInitializePoolEvents(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiMakeOutswappedPageResident(), MiMappedPageWriter(), MiModifiedPageWriterWorker(), MiNotifyMemoryEvents(), MiQueueWorkingSetRequest(), MiRemovePageByColor(), MiRemovePageFromList(), MiShutdownSystem(), MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MiZeroPageFile(), NtClearEvent(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtNotifyChangeMultipleKeys(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetVolumeInformationFile(), NtUnloadKeyEx(), NtUnlockFile(), NtWaitForDebugEvent(), NtWriteFile(), NtWriteFileGather(), and WmipCopyFromEventQueues().
VOID KeInitializeEvent (__out PRKEVENT Event, __in EVENT_TYPE Type, __in BOOLEAN State)
Definition at line 49 of file eventobj.c.
References InitializeListHead().
Referenced by CcCanIWrite(), CcInitializeCacheMap(), CcSetValidData(), CcWaitForCurrentLazyWriterActivity(), CcWaitForUninitializeCacheMap(), CcWaitOnActiveCount(), CcZeroData(), CmpAllocatePostBlock(), CmpInitializeHiveList(), DbgkpQueueMessage(), ExfWaitForRundownProtectionRelease(), ExpAllocateExclusiveWaiterEvent(), ExpInitializeCallbacks(), ExpWorkerInitialization(), ExReinitializeResourceLite(), ExSwapinWorkerThreads(), ExTimedWaitForUnblockPushLock(), ExWaitForRundownProtectionReleaseCacheAware(), FsFilterInit(), FsRtlBalanceReads(), FsRtlGetFileSize(), FsRtlInitializeWorkerThread(), FsRtlSetFileSize(), FsRtlWaitOnIrp(), HalExamineMBR(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoCancelFileOpen(), IoCreateDevice(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IoGetBootDiskInformation(), IoInitSystem(), IopCloseFile(), IopCompleteUnloadOrDelete(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopDeleteFile(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopInitializeReserveIrp(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IopShutdownBaseFileSystems(), IopUnloadDriver(), IoReadPartitionTable(), IoSetInformation(), IoSetPartitionInformation(), IoShutdownSystem(), IoVerifyVolume(), IoVolumeDeviceToDosName(), IoWritePartitionTable(), KeInitializeEventPair(), KeInitSystem(), KiInitSystem(), LpcpCreatePort(), MiAdjustWorkingSetManagerParameters(), MiChargeCommitment(), MiCleanSection(), MiCreateImageFileMap(), MiDereferenceSessionFinal(), MiFlushSectionInternal(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiMakeOutswappedPageResident(), MiMappedPageWriter(), MiModifiedPageWriter(), MiShutdownSystem(), MiUnlinkWorkingSet(), MiZeroAllPageFiles(), MiZeroInParallel(), MiZeroPageFile(), MiZeroPageFileFirstPage(), MmInitSystem(), NtCreateDebugObject(), NtCreateEvent(), NtCreateJobObject(), NtCreatePagingFile(), NtFlushBuffersFile(), NtLoadDriver(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), ObInitSystem(), PsGetContextThread(), PsSetContextThread(), RawQueryFsSizeInfo(), SepRmCommandServerThread(), WmipAllocRegEntry(), WmipCreateGuidObject(), WmipForwardWmiIrp(), WmipGetDevicePDO(), WmipStartLogger(), WmipWaitForCollectionEnabled(), and xHalGetPartialGeometry().
VOID KeInitializeEventPair (__inout PKEVENT_PAIR EventPair)
Definition at line 92 of file eventobj.c.
References EventPairObject, FALSE, KeInitializeEvent(), and SynchronizationEvent.
Referenced by NtCreateEventPair().
LONG KePulseEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
Definition at line 163 of file eventobj.c.
References ASSERT, ASSERT_EVENT, DISPATCH_LEVEL, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), ReadForWriteAccess, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by MiComputeSystemTrimCriteria(), MiFlushSectionInternal(), MiWriteComplete(), MmLockPageableSectionByHandle(), MmResourcesAvailable(), MmUnlockPageableImageSection(), and NtPulseEvent().
LONG KeReadStateEvent (__in PRKEVENT Event)
Definition at line 251 of file eventobj.c.
References ASSERT_EVENT.
Referenced by IopCancelAlertedRequest(), IopConnectLinkTrackingPort(), IopSendMessageToTrackService(), MiFlushSectionInternal(), MiGetInPageSupportBlock(), MiNotifyMemoryEvents(), NtQueryEvent(), and PspAddProcessToJob().
LONG KeResetEvent (__inout PRKEVENT Event)
Definition at line 283 of file eventobj.c.
References ASSERT, ASSERT_EVENT, DISPATCH_LEVEL, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), and ReadForWriteAccess.
Referenced by IopSendMessageToTrackService(), IoSetPartitionInformation(), NtReplyWaitReceivePortEx(), NtResetEvent(), RawQueryFsSizeInfo(), WmipFlushLogger(), WmipFreeLoggerContext(), WmipStartLogger(), WmiStopTrace(), and WmiUpdateTrace().
LONG KeSetEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
Definition at line 341 of file eventobj.c.
References ASSERT, ASSERT_EVENT, DISPATCH_LEVEL, EventNotificationObject, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), ReadForWriteAccess, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by CcCancelMmWaitForUninitializeCacheMap(), CcDeleteSharedCacheMap(), CcFreeVirtualAddress(), CcGetVacbMiss(), CcInitializeCacheMap(), CcPostDeferredWrites(), CcUninitializeCacheMap(), CcWorkerThread(), CmNotifyRunDown(), CmpLoadHiveThread(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), CmUnloadKey(), DbgkpCloseObject(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), DbgkpWakeTarget(), ExfReleaseRundownProtection(), ExNotifyCallback(), ExpSetSwappingKernelApc(), ExpShutdownWorker(), ExQueueWorkItem(), ExReleaseRundownProtectionEx(), FsFilterFreeCompletionStack(), FsRtlCompletionRoutinePriv(), FsRtlStackOverflowRead(), IopAcquireFileObjectLock(), IopCompleteRequest(), IopConnectLinkTrackingPort(), IopfCompleteRequest(), IopFreeReserveIrp(), IopInvalidateVolumesForDevice(), IopLoadUnloadDriver(), IopMountVolume(), IopSendMessageToTrackService(), IopTrackLink(), IopXxxControlFile(), IoVerifyVolume(), KiQuantumEnd(), KiSetServerWaitClientEvent(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiAllocatePoolPages(), MiCcPutPagesInTransition(), MiCheckControlArea(), MiDereferenceSegmentThread(), MiDispatchFault(), MiFindContiguousMemoryInPool(), MiFlushAllPages(), MiFlushComplete(), MiFreePoolPages(), MiGatherMappedPages(), MiGatherPagefilePages(), MiInitializePoolEvents(), MiInsertPageFileInList(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiModifiedPageWriterTimerDispatch(), MiNotifyMemoryEvents(), MiObtainFreePages(), MiProcessWorkingSets(), MiQueueWorkingSetRequest(), MiRemovePageByColor(), MiRemovePageFromList(), MiRemoveUnusedSegments(), MiSegmentDelete(), MiShutdownSystem(), MiTrimAllSystemPageableMemory(), MiTrimSegmentCache(), MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MiUpdateModifiedWriterMdls(), MiWriteComplete(), MiZeroAllPageFiles(), MiZeroAwePageWorker(), MiZeroPageFile(), MmCopyToCachedPage(), MmCreateSection(), MmDetachSession(), MmIsMemoryAvailable(), MmResourcesAvailable(), MmWorkingSetManager(), NtDebugContinue(), NtLockFile(), NtReadFile(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetEvent(), NtSignalAndWaitForSingleObject(), NtWriteFile(), PspGetSetContextSpecialApc(), PspTerminateAllProcessesInJob(), SepDequeueWorkItem(), WmipDecrementIrpCount(), WmipFreeLoggerContext(), WmipLogger(), WmipQueueNotification(), WmipReleaseCollectionEnabled(), WmipRequestLogFile(), and WmipWmiIrpCompletion().
VOID KeSetEventBoostPriority (__inout PRKEVENT Event, __in_opt PRKTHREAD * Thread)
Definition at line 443 of file eventobj.c.
References AdjustBoost, _KTHREAD::AdjustIncrement, _KTHREAD::AdjustReason, ARGUMENT_PRESENT, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, EVENT_INCREMENT, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiComputeNewPriority(), KiLockDispatcherDatabase, KiReadyThread(), KiUnlinkThread(), KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), _KTHREAD::Priority, STATUS_SUCCESS, SynchronizationEvent, _KWAIT_BLOCK::Thread, WaitAll, and _KWAIT_BLOCK::WaitType.
Referenced by ExfUnblockPushLock(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), NtSetEventBoostPriority(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().