Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/create.c File Reference
create.c File Reference
#include "psp.h"
Functions
NTSTATUS NtCreateProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in BOOLEAN InheritObjectTable, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort)
NTSTATUS NtCreateProcessEx (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in ULONG Flags, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort, __in ULONG JobMemberLevel)
NTSTATUS NtCreateThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ProcessHandle, __out PCLIENT_ID ClientId, __in PCONTEXT ThreadContext, __in PINITIAL_TEB InitialTeb, __in BOOLEAN CreateSuspended)
VOID PsCallImageNotifyRoutines (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
NTSTATUS PsCreateSystemProcess (__out PHANDLE ProcessHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS PsCreateSystemThread (__out PHANDLE ThreadHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt HANDLE ProcessHandle, __out_opt PCLIENT_ID ClientId, __in PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext)
HANDLE PsGetCurrentProcessId (VOID)
HANDLE PsGetCurrentThreadId (VOID)
BOOLEAN PsGetVersion (__out_opt PULONG MajorVersion, __out_opt PULONG MinorVersion, __out_opt PULONG BuildNumber, __out_opt PUNICODE_STRING CSDVersion)
NTSTATUS PspCreateProcess (OUT PHANDLE ProcessHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ParentProcess OPTIONAL, IN ULONG Flags, IN HANDLE SectionHandle OPTIONAL, IN HANDLE DebugPort OPTIONAL, IN HANDLE ExceptionPort OPTIONAL, IN ULONG JobMemberLevel)
NTSTATUS PspCreateThread (OUT PHANDLE ThreadHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ProcessHandle, IN PEPROCESS ProcessPointer, OUT PCLIENT_ID ClientId OPTIONAL, IN PCONTEXT ThreadContext OPTIONAL, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN CreateSuspended, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext)
VOID PspImageNotifyTest (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
VOID PspSystemThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
ULONG PspUnhandledExceptionInSystemThread (IN PEXCEPTION_POINTERS ExceptionPointers)
VOID PspUserThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
NTSTATUS PsRemoveCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
NTSTATUS PsRemoveLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
NTSTATUS PsSetCreateProcessNotifyRoutine (__in PCREATE_PROCESS_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
NTSTATUS PsSetCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
NTSTATUS PsSetLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
Variables
UNICODE_STRING CmCSDVersionString
LCID PsDefaultSystemLocaleId = 0
LCID PsDefaultThreadLocaleId = 0
LANGID PsDefaultUILanguageId = 0
BOOLEAN PsImageNotifyEnabled = FALSE
LANGID PsInstallUILanguageId = 0
ULONG PsMaximumWorkingSet = 45
ULONG PsMinimumWorkingSet = 20
BOOLEAN PsUseImpersonationToken = FALSE
Function Documentation
NTSTATUS NtCreateProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in BOOLEAN InheritObjectTable, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort)
Definition at line 816 of file create.c.
References NtCreateProcessEx(), PROCESS_CREATE_FLAGS_BREAKAWAY, PROCESS_CREATE_FLAGS_INHERIT_HANDLES, and PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT.
NTSTATUS NtCreateProcessEx (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in ULONG Flags, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort, __in ULONG JobMemberLevel)
Definition at line 853 of file create.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, PAGED_CODE, ProbeForWriteHandle, PspCreateProcess(), Status, and STATUS_INVALID_PARAMETER.
Referenced by NtCreateProcess().
NTSTATUS NtCreateThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ProcessHandle, __out PCLIENT_ID ClientId, __in PCONTEXT ThreadContext, __in PINITIAL_TEB InitialTeb, __in BOOLEAN CreateSuspended)
Definition at line 78 of file create.c.
References ARGUMENT_PRESENT, CONTEXT_ALIGN, except, ExSystemExceptionFilter(), KeGetPreviousMode, KernelMode, NULL, _INITIAL_TEB::OldInitialTeb, _INITIAL_TEB::OldStackBase, _INITIAL_TEB::OldStackLimit, PAGED_CODE, ProbeForReadSmallStructure, ProbeForWriteHandle, ProbeForWriteSmallStructure(), PspCreateThread(), Status, and STATUS_INVALID_PARAMETER.
VOID PsCallImageNotifyRoutines (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
Definition at line 2393 of file create.c.
References ExDereferenceCallBackBlock(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), NULL, PAGED_CODE, PsImageNotifyEnabled, PSP_MAX_LOAD_IMAGE_NOTIFY, and PspLoadImageNotifyRoutine.
Referenced by DbgkCreateThread(), MiMapViewOfImageSection(), and MmLoadSystemImage().
NTSTATUS PsCreateSystemProcess (__out PHANDLE ProcessHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 921 of file create.c.
References NULL, PAGED_CODE, PspCreateProcess(), PspInitialSystemProcessHandle, and Status.
NTSTATUS PsCreateSystemThread (__out PHANDLE ThreadHandle, __in ULONG DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt HANDLE ProcessHandle, __out_opt PCLIENT_ID ClientId, __in PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext)
Definition at line 172 of file create.c.
References ARGUMENT_PRESENT, FALSE, NULL, PAGED_CODE, PsInitialSystemProcess, PspCreateThread(), and Status.
Referenced by CmpInitializeHiveList(), ExpCreateWorkerThread(), ExpWorkerInitialization(), FsRtlInitializeWorkerThread(), IopStartApcHardError(), KeInitSystem(), MiModifiedPageWriter(), MiSectionInitialization(), MiZeroInParallel(), MmInitSystem(), PspInitPhase0(), SeRmInitPhase1(), and WmipStartLogger().
HANDLE PsGetCurrentProcessId (VOID)
Definition at line 2227 of file create.c.
References _ETHREAD::Cid, PsGetCurrentThread(), and _CLIENT_ID::UniqueProcess.
Referenced by CmpCreateRegistryRoot(), CmpDoCreateChild(), CmpDoOpen(), NtCreateKey(), SeAuditHandleCreation(), WmipAllocGuidEntryX(), WmipDoDisableRequest(), WmipReleaseCollectionEnabled(), WmipSendDisableRequest(), WmipSendEnableRequest(), and WmipWaitForCollectionEnabled().
HANDLE PsGetCurrentThreadId (VOID)
Definition at line 2233 of file create.c.
References _ETHREAD::Cid, PsGetCurrentThread(), and _CLIENT_ID::UniqueThread.
Referenced by NtCreateKey(), WmipAllocGuidEntryX(), WmipDoDisableRequest(), WmipReleaseCollectionEnabled(), WmipSendDisableRequest(), WmipSendEnableRequest(), and WmipWaitForCollectionEnabled().
BOOLEAN PsGetVersion (__out_opt PULONG MajorVersion, __out_opt PULONG MinorVersion, __out_opt PULONG BuildNumber, __out_opt PUNICODE_STRING CSDVersion)
Definition at line 2239 of file create.c.
References ARGUMENT_PRESENT, CmCSDVersionString, NtBuildNumber, NtMajorVersion, and NtMinorVersion.
NTSTATUS PspCreateProcess (OUT PHANDLE ProcessHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ParentProcess OPTIONAL, IN ULONG Flags, IN HANDLE SectionHandle OPTIONAL, IN HANDLE DebugPort OPTIONAL, IN HANDLE ExceptionPort OPTIONAL, IN ULONG JobMemberLevel)
Definition at line 967 of file create.c.
References _EPROCESS::ActiveProcessLinks, _KPROCESS::Affinity, ARGUMENT_PRESENT, ASSERT, _KPROCESS::BasePriority, _UNICODE_STRING::Buffer, _SECURITY_SUBJECT_CONTEXT::ClientToken, _EPROCESS::CreateTime, DbgkCopyProcessDebugPort(), DbgkDebugObjectType, DEBUG_PROCESS_ASSIGN, _EPROCESS::DebugPort, _EPROCESS::DefaultHardErrorProcessing, ExAcquireRundownProtection(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExCreateHandle(), ExInitializeRundownProtection(), _EPROCESS::ExitStatus, ExReleaseRundownProtection(), ExSetHandleTableOwner, FALSE, FIELD_OFFSET, _EPROCESS::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _SE_AUDIT_PROCESS_CREATION_INFO::ImageFileName, _INITIAL_PEB::ImageUsesLargePages, _INITIAL_PEB::InheritedAddressSpace, _EPROCESS::InheritedFromUniqueProcessId, InitializeListHead(), InsertTailList(), IsListEmpty, _EPROCESS::Job, JOB_OBJECT_LIMIT_BREAKAWAY_OK, JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, KeActiveProcessors, KeGetPreviousModeByThread, KeInitializeProcess(), KeQuerySystemTime(), KernelMode, _EJOB::LimitFlags, LpcPortObjectType, MAXIMUM_ALLOWED, _UNICODE_STRING::MaximumLength, _MMSUPPORT::MaximumWorkingSetSize, MmCopyVirtualMemory(), MmCreatePeb(), MmCreateProcessAddressSpace(), MmInitializeHandBuiltProcess(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmSectionObjectType, _INITIAL_PEB::Mutant, _OBJECT_NAME_INFORMATION::Name, NORMAL_BASE_PRIORITY, NOTHING, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObGetObjectSecurity(), ObInheritDeviceMap(), ObInitProcess(), ObInsertObject(), _HANDLE_TABLE_ENTRY::Object, _EPROCESS::ObjectTable, ObReferenceObject, ObReferenceObjectByHandle, ObReleaseObjectSecurity(), PAGED_CODE, PagedPool, _EPROCESS::Pcb, _EPROCESS::Peb, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, _EPROCESS::PriorityClass, PROCESS_ALL_ACCESS, PROCESS_CREATE_FLAGS_ALL_LARGE_PAGE_FLAGS, PROCESS_CREATE_FLAGS_BREAKAWAY, PROCESS_CREATE_FLAGS_INHERIT_HANDLES, PROCESS_CREATE_FLAGS_LARGE_PAGES, PROCESS_CREATE_FLAGS_LEGAL_MASK, PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT, PROCESS_CREATE_FLAGS_OVERRIDE_ADDRESS_SPACE, PROCESS_CREATE_PROCESS, PROCESS_CREATE_THREAD, PROCESS_DUP_HANDLE, PROCESS_HARDERROR_ALIGNMENT_BIT, PROCESS_HARDERROR_DEFAULT, PROCESS_PRIORITY_CLASS_BELOW_NORMAL, PROCESS_PRIORITY_CLASS_IDLE, PROCESS_PRIORITY_CLASS_NORMAL, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION, PROCESS_SET_QUOTA, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, PS_PROCESS_FLAGS_HAS_ADDRESS_SPACE, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_PROCESS_FLAGS_OVERRIDE_ADDRESS_SPACE, PS_SET_BITS, PsActiveProcessHead, PsDereferencePrimaryTokenEx, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, PsMaximumWorkingSet, PsMinimumWorkingSet, PspAddProcessToJob(), PspCidTable, PspComputeQuantumAndPriority(), PspGetJobFromSet(), PspInheritQuota(), PspInitializeProcessLock(), PspInitializeProcessSecurity(), PspLockProcessList(), PsProcessPriorityBackground, PsProcessType, PspUnlockProcessList(), PsReferencePrimaryToken(), PsUseImpersonationToken, _KPROCESS::QuantumReset, RtlCopyMemory, RtlZeroMemory, _EPROCESS::RundownProtect, SeAccessCheck(), SeAssignPrimaryToken(), SeAuditProcessCreation(), _EPROCESS::SeAuditProcessCreationInfo, SeCreateAccessStateEx(), SECTION_MAP_EXECUTE, _EPROCESS::SectionBaseAddress, _EPROCESS::SectionObject, SeDeleteAccessState(), SeDetailedAuditingWithToken(), _EJOB::SessionId, SeSubProcessToken(), STANDARD_RIGHTS_ALL, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, _EPROCESS::ThreadListHead, _EJOB::Token, TRUE, _OBJECT_TYPE::TypeInfo, _EPROCESS::UniqueProcessId, and _EPROCESS::Vm.
Referenced by NtCreateProcessEx(), PsCreateSystemProcess(), and PspInitPhase0().
NTSTATUS PspCreateThread (OUT PHANDLE ThreadHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ProcessHandle, IN PEPROCESS ProcessPointer, OUT PCLIENT_ID ClientId OPTIONAL, IN PCONTEXT ThreadContext OPTIONAL, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN CreateSuspended, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext)
Definition at line 243 of file create.c.
References _EPROCESS::ActiveThreads, _ETHREAD::ActiveTimerListHead, _ETHREAD::ActiveTimerListLock, ARGUMENT_PRESENT, ASSERT, _ETHREAD::Cid, _SECURITY_SUBJECT_CONTEXT::ClientToken, _EJOB::CompletionKey, _EJOB::CompletionPort, CONTEXT_TO_PROGRAM_COUNTER, _ETHREAD::CrossThreadFlags, ExAcquireResourceSharedLite(), ExAcquireRundownProtection(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExCreateHandle(), ExDereferenceCallBackBlock(), ExGetCallBackBlockRoutine(), ExInitializeRundownProtection(), ExReferenceCallBackBlock(), ExReleaseResourceLite(), ExReleaseRundownProtection(), FALSE, _EPROCESS::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _ETHREAD::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _LARGE_INTEGER::HighPart, _EPROCESS::InheritedFromUniqueProcessId, InitializeListHead(), InsertTailList(), IoSetIoCompletion(), _ETHREAD::IrpList, _EPROCESS::Job, JOB_OBJECT_MSG_NEW_PROCESS, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeForceResumeThread(), KeGetPreviousModeByThread, KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitThread(), KeLeaveCriticalRegionThread(), KeQuerySystemTime(), KeReadyThread(), KeResumeThread(), KernelMode, KeStartThread(), KeSuspendThread(), KeUninitThread(), _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplySemaphore, MAXIMUM_ALLOWED, MmCreateTeb(), MmDeleteTeb(), MmReadClusterSize, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObDereferenceObjectEx(), ObGetObjectSecurity(), ObInsertObject(), _HANDLE_TABLE_ENTRY::Object, ObReferenceObject, ObReferenceObjectByHandle, ObReferenceObjectEx(), ObReleaseObjectSecurity(), PAGED_CODE, _EPROCESS::Pcb, PERFINFO_PROCESS_CREATE, PERFINFO_THREAD_CREATE, _ETHREAD::PostBlockList, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PROCESS_CREATE_THREAD, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_SYSTEM, PS_CROSS_THREAD_FLAGS_TERMINATED, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PS_SET_THREAD_CREATE_TIME, PsDereferencePrimaryTokenEx, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, PSP_MAX_CREATE_PROCESS_NOTIFY, PSP_MAX_CREATE_THREAD_NOTIFY, PspCidTable, PspCreateProcessNotifyRoutine, PspCreateProcessNotifyRoutineCount, PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, PspInitializeThreadLock(), PspLockProcessExclusive(), PsProcessType, PspSystemThreadStartup(), PspUnlockProcessExclusive(), PspUserThreadStartup(), PsReferencePrimaryToken(), PsThreadType, PsUseImpersonationToken, _ETHREAD::ReadClusterSize, RtlZeroMemory, _EPROCESS::RundownProtect, _ETHREAD::RundownProtect, SeAccessCheck(), SeCreateAccessStateEx(), SeDeleteAccessState(), _ETHREAD::StartAddress, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_SUSPEND_COUNT_EXCEEDED, _ETHREAD::Tcb, THREAD_ALL_ACCESS, THREAD_QUERY_INFORMATION, THREAD_SET_INFORMATION, THREAD_TERMINATE, THREAD_TO_PROCESS, _ETHREAD::ThreadListEntry, _EPROCESS::ThreadListHead, _ETHREAD::ThreadsProcess, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _EPROCESS::UniqueProcessId, _CLIENT_ID::UniqueThread, VOID, and _ETHREAD::Win32StartAddress.
Referenced by NtCreateThread(), and PsCreateSystemThread().
VOID PspImageNotifyTest (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
Definition at line 2441 of file create.c.
References UNREFERENCED_PARAMETER.
Referenced by PspInitPhase0().
VOID PspSystemThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
Definition at line 2182 of file create.c.
References _ETHREAD::CrossThreadFlags, except, KeBugCheck(), KeLowerIrql, KMODE_EXCEPTION_NOT_HANDLED, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_TERMINATED, PsGetCurrentThread(), PspTerminateThreadByPointer(), PspUnhandledExceptionInSystemThread(), STATUS_SUCCESS, and TRUE.
Referenced by PspCreateThread().
ULONG PspUnhandledExceptionInSystemThread (IN PEXCEPTION_POINTERS ExceptionPointers)
Definition at line 2152 of file create.c.
References KdPrint, KeBugCheckEx(), and SYSTEM_THREAD_EXCEPTION_NOT_HANDLED.
Referenced by PspSystemThreadStartup().
VOID PspUserThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
Definition at line 2003 of file create.c.
References APC_LEVEL, CCPF_IS_PREFETCHER_ENABLED, CcPfBeginAppLaunch(), _ETHREAD::CrossThreadFlags, DbgkCreateThread(), _SYSTEM_DLL::DllBase, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _EPROCESS::Flags, _LARGE_INTEGER::HighPart, _KTHREAD::IdealProcessor, InterlockedCompareExchange(), _KPRCB::InterruptTime, KeGetCurrentPrcb(), KeLowerIrql, KeQuerySystemTime(), KeRaiseIrql, KiInitializeUserApc(), _SYSTEM_DLL::LoaderInitRoutine, _LARGE_INTEGER::LowPart, MmGetSessionLocaleId(), _KPRCB::MmPageFaultCount, NtCurrentTeb(), NULL, PAGED_CODE, PASSIVE_LEVEL, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PS_PROCESS_FLAGS_LAUNCH_PREFETCHED, PS_TEST_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspGetBaseExceptionFrame, PspGetBaseTrapFrame, PspSystemDll, PspTerminateThreadByPointer(), _EPROCESS::SectionObject, SharedUserData, STATUS_THREAD_IS_TERMINATING, _ETHREAD::Tcb, TRUE, and UNREFERENCED_PARAMETER.
Referenced by PspCreateThread().
NTSTATUS PsRemoveCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 1936 of file create.c.
References ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedDecrement, NULL, PAGED_CODE, PSP_MAX_CREATE_THREAD_NOTIFY, PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, STATUS_PROCEDURE_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS PsRemoveLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 2326 of file create.c.
References ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedDecrement, NULL, PAGED_CODE, PSP_MAX_LOAD_IMAGE_NOTIFY, PspLoadImageNotifyRoutine, PspLoadImageNotifyRoutineCount, STATUS_PROCEDURE_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS PsSetCreateProcessNotifyRoutine (__in PCREATE_PROCESS_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
Definition at line 1761 of file create.c.
References ExAllocateCallBack(), ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedDecrement, InterlockedIncrement, NULL, PAGED_CODE, PSP_MAX_CREATE_PROCESS_NOTIFY, PspCreateProcessNotifyRoutine, PspCreateProcessNotifyRoutineCount, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PROCEDURE_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS PsSetCreateThreadNotifyRoutine (__in PCREATE_THREAD_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 1876 of file create.c.
References ExAllocateCallBack(), ExCompareExchangeCallBack(), ExFreeCallBack(), InterlockedIncrement, NULL, PAGED_CODE, PSP_MAX_CREATE_THREAD_NOTIFY, PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
NTSTATUS PsSetLoadImageNotifyRoutine (__in PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 2265 of file create.c.
References ExAllocateCallBack(), ExCompareExchangeCallBack(), ExFreeCallBack(), InterlockedIncrement, NULL, PAGED_CODE, PsImageNotifyEnabled, PSP_MAX_LOAD_IMAGE_NOTIFY, PspLoadImageNotifyRoutine, PspLoadImageNotifyRoutineCount, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by PspInitPhase0(), and WmipEnableKernelTrace().
Variable Documentation
UNICODE_STRING CmCSDVersionString
Referenced by PsGetVersion().
LCID PsDefaultSystemLocaleId = 0
Definition at line 52 of file create.c.
Referenced by CmGetSystemControlValues(), CmpCreatePerfKeys(), LdrpSearchResourceSection_U(), MiSessionCreateInternal(), NtQueryDefaultLocale(), and NtSetDefaultLocale().
LCID PsDefaultThreadLocaleId = 0
Definition at line 53 of file create.c.
Referenced by CmGetSystemControlValues(), MmGetSessionLocaleId(), and MmSetSessionLocaleId().
LANGID PsDefaultUILanguageId = 0
Definition at line 54 of file create.c.
Referenced by CmGetSystemControlValues(), and CmpCreatePerfKeys().
BOOLEAN PsImageNotifyEnabled = FALSE
Definition at line 65 of file create.c.
Referenced by DbgkCreateThread(), MiMapViewOfImageSection(), MmLoadSystemImage(), PsCallImageNotifyRoutines(), and PsSetLoadImageNotifyRoutine().
LANGID PsInstallUILanguageId = 0
Definition at line 55 of file create.c.
Referenced by CmGetSystemControlValues(), LdrpSearchResourceSection_U(), NtQueryDefaultUILanguage(), and NtQueryInstallUILanguage().
ULONG PsMaximumWorkingSet = 45
Definition at line 63 of file create.c.
Referenced by PspCreateProcess(), and PspInitPhase0().
ULONG PsMinimumWorkingSet = 20
Definition at line 62 of file create.c.
Referenced by NtSetInformationJobObject(), PspCreateProcess(), and PspInitPhase0().
BOOLEAN PsUseImpersonationToken = FALSE
Definition at line 239 of file create.c.
Referenced by PspCreateProcess(), and PspCreateThread().