Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/ldtsup.c File Reference
ldtsup.c File Reference
#include "ki.h"
Data Structures
struct _LDTINFO
Typedefs
typedef struct _LDTINFO LDTINFO
typedef struct _LDTINFO * PLDTINFO
Functions
VOID Ke386SetDescriptorProcess (IN PKPROCESS Process, IN ULONG Offset, IN LDT_ENTRY LdtEntry)
VOID Ke386SetLdtProcess (IN PKPROCESS Process, IN PLDT_ENTRY Ldt, IN ULONG Limit)
VOID Ki386FlushTargetDescriptors (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID Ki386LoadTargetLdtr (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID KiFlushDescriptors (VOID)
VOID KiLoadLdtr (VOID)
Typedef Documentation
typedef struct _LDTINFO LDTINFO
typedef struct _LDTINFO * PLDTINFO
Function Documentation
VOID Ke386SetDescriptorProcess (IN PKPROCESS Process, IN ULONG Offset, IN LDT_ENTRY LdtEntry)
Definition at line 245 of file ldtsup.c.
References KeGenericCallDpc(), Ki386FlushTargetDescriptors(), _LDTINFO::Ldt, _LDTINFO::LdtEntry, _LDTINFO::Offset, and _LDTINFO::Process.
VOID Ke386SetLdtProcess (IN PKPROCESS Process, IN PLDT_ENTRY Ldt, IN ULONG Limit)
Definition at line 66 of file ldtsup.c.
References _KGDTENTRY::BaseLow, _KGDTENTRY::Bits, _KGDTENTRY::Bytes, DPL_SYSTEM, _KGDTENTRY::HighWord, KeGenericCallDpc(), Ki386LoadTargetLdtr(), _LDTINFO::LdtDescriptor, _KGDTENTRY::LimitLow, NULL, _LDTINFO::Process, and TYPE_LDT.
VOID Ki386FlushTargetDescriptors (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 313 of file ldtsup.c.
References KeSignalCallDpcDone(), KeSignalCallDpcSynchronize(), KiFlushDescriptors(), _LDTINFO::Ldt, _LDTINFO::LdtEntry, _LDTINFO::Offset, and UNREFERENCED_PARAMETER.
Referenced by Ke386SetDescriptorProcess().
VOID Ki386LoadTargetLdtr (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 178 of file ldtsup.c.
References KeSignalCallDpcDone(), KeSignalCallDpcSynchronize(), KiLoadLdtr(), _LDTINFO::LdtDescriptor, _KPROCESS::LdtDescriptor, _LDTINFO::Process, and UNREFERENCED_PARAMETER.
Referenced by Ke386SetLdtProcess().
VOID KiFlushDescriptors (VOID)
Referenced by Ki386FlushTargetDescriptors().
VOID KiLoadLdtr (VOID)
Referenced by Ki386LoadTargetLdtr().