Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/kx.h File Reference
kx.h File Reference
Functions
FORCEINLINE VOID FASTCALL KeAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE VOID FASTCALL KeAcquireGuardedMutexUnsafe (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE BOOLEAN KeAreAllApcsDisabled (VOID)
FORCEINLINE BOOLEAN KeAreApcsDisabled (VOID)
FORCEINLINE VOID KeEnterCriticalRegion (VOID)
FORCEINLINE VOID KeEnterCriticalRegionThread (PKTHREAD Thread)
FORCEINLINE VOID KeEnterGuardedRegion (VOID)
FORCEINLINE VOID KeEnterGuardedRegionThread (IN PKTHREAD Thread)
FORCEINLINE PKTHREAD FASTCALL KeGetOwnerGuardedMutex (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE VOID FASTCALL KeInitializeGuardedMutex (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE BOOLEAN FASTCALL KeIsGuardedMutexOwned (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE VOID KeLeaveCriticalRegion (VOID)
FORCEINLINE VOID KeLeaveCriticalRegionThread (IN PKTHREAD Thread)
FORCEINLINE VOID KeLeaveGuardedRegion (VOID)
FORCEINLINE VOID KeLeaveGuardedRegionThread (IN PKTHREAD Thread)
FORCEINLINE VOID FASTCALL KeReleaseGuardedMutex (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE VOID FASTCALL KeReleaseGuardedMutexUnsafe (IN PKGUARDED_MUTEX Mutex)
FORCEINLINE BOOLEAN FASTCALL KeTryToAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
VOID FASTCALL KiAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
NTKERNELAPI VOID KiCheckForKernelApcDelivery (VOID)
Function Documentation
FORCEINLINE VOID FASTCALL KeAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 462 of file kx.h.
References APC_LEVEL, ASSERT, GM_LOCK_BIT_V, InterlockedBitTestAndReset(), KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KiAcquireGuardedMutex(), and _KTHREAD::SpecialApcDisable.
Referenced by FsRtlAddLargeMcbEntry(), FsRtlGetNextLargeMcbEntry(), FsRtlLookupLargeMcbEntry(), FsRtlLookupLastLargeMcbEntry(), FsRtlLookupLastLargeMcbEntryAndIndex(), FsRtlNumberOfRunsInLargeMcb(), FsRtlPrivateInitializeFileLock(), FsRtlRemoveLargeMcbEntry(), FsRtlResetLargeMcb(), FsRtlSplitLargeMcb(), FsRtlTruncateLargeMcb(), MiAllocatePoolPages(), MiFreePoolPages(), MiInitializePoolEvents(), MiReleaseProcessReferenceToSessionDataPage(), MiSectionDelete(), MiSessionCreateInternal(), MmCreateSection(), MmExtendSection(), MmGetSizeOfBigPoolAllocation(), MmGetSystemPageFile(), MmResourcesAvailable(), NtCreatePagingFile(), WmipFreeLoggerContext(), and WmipStartLogger().
FORCEINLINE VOID FASTCALL KeAcquireGuardedMutexUnsafe (IN PKGUARDED_MUTEX Mutex)
Definition at line 680 of file kx.h.
References APC_LEVEL, ASSERT, GM_LOCK_BIT_V, InterlockedBitTestAndReset(), KeGetCurrentIrql(), KeGetCurrentThread(), KiAcquireGuardedMutex(), MM_SYSTEM_RANGE_START, NULL, _KTHREAD::SpecialApcDisable, and _KTHREAD::Teb.
Referenced by MiCloneProcessAddressSpace(), MiMapViewOfDataSection(), MiProtectVirtualMemory(), MiRemoveMappedView(), MmCommitSessionMappedView(), NtAllocateVirtualMemory(), PspLockJobLimitsExclusive(), PspLockJobLimitsExclusiveUnsafe(), PspLockJobLimitsShared(), PspLockJobLimitsSharedUnsafe(), PspLockJobListExclusive(), PspLockJobListShared(), PspLockJobTimeLimitsExclusive(), PspLockJobTimeLimitsShared(), PspLockProcessList(), PspLockWorkingSetChangeExclusive(), and PspLockWorkingSetChangeExclusiveUnsafe().
FORCEINLINE BOOLEAN KeAreAllApcsDisabled (VOID)
Definition at line 399 of file kx.h.
References APC_LEVEL, KeGetCurrentIrql(), KeGetCurrentThread(), and _KTHREAD::SpecialApcDisable.
Referenced by MiAllocateLargePages(), MiCheckForUserStackOverflow(), MiCleanPhysicalProcessPages(), MiDetachAndUnlockWorkingSet(), MiDispatchFault(), MiDoesPdeExistAndMakeValid(), MiFlushPteListFreePfns(), MiMakePdeExistAndMakeValid(), MiMakeSystemAddressValid(), MiRemoveUserPhysicalPagesVad(), MiResolveProtoPteFault(), MiSecureVirtualMemory(), MiTrimPte(), MiWriteComplete(), MmAccessFault(), MmFlushVirtualMemory(), NtLockVirtualMemory(), ObfDereferenceObject(), PspLockJobLimitsExclusiveUnsafe(), PspLockJobLimitsSharedUnsafe(), PspLockWorkingSetChangeExclusiveUnsafe(), PspUnlockJobLimitsExclusiveUnsafe(), PspUnlockJobLimitsSharedUnsafe(), PspUnlockWorkingSetChangeExclusiveUnsafe(), and RtlpCaptureStackTraceForLogging().
FORCEINLINE BOOLEAN KeAreApcsDisabled (VOID)
Definition at line 371 of file kx.h.
References _KTHREAD::CombinedApcDisable, and KeGetCurrentThread().
Referenced by Phase1InitializationDiscard().
FORCEINLINE VOID KeEnterCriticalRegion (VOID)
Definition at line 249 of file kx.h.
References KeEnterCriticalRegionThread(), and KeGetCurrentThread().
Referenced by CmpLockRegistry(), CmpLockRegistryExclusive(), CmUnloadKey(), ExEnterCriticalRegionAndAcquireFastMutexUnsafe(), ExEnterCriticalRegionAndAcquireResourceExclusive(), ExEnterCriticalRegionAndAcquireResourceShared(), ExEnterCriticalRegionAndAcquireSharedWaitForExclusive(), ExpGetSystemFirmwareTableInformation(), ExpRegisterFirmwareTableInformationHandler(), KeFreezeAllThreads(), NtLoadKeyEx(), NtQuerySystemInformation(), NtReplaceKey(), ObpLockAllObjects(), ObpLockDirectoryExclusive(), ObpLockDirectoryShared(), PsLocateSystemDll(), PsMapSystemDll(), and RtlpLockAtomTable().
FORCEINLINE VOID KeEnterCriticalRegionThread (PKTHREAD Thread)
Definition at line 207 of file kx.h.
References ASSERT, KeGetCurrentThread(), KeMemoryBarrierWithoutFence, and _KTHREAD::KernelApcDisable.
Referenced by ExChangeHandle(), ExCompareExchangeCallBack(), ExCreateHandle(), ExCreateHandleTable(), ExDestroyHandle(), ExDupHandleTable(), ExEnumHandleTable(), ExReferenceCallBackBlock(), ExRemoveHandleTable(), ExSetHandleInfo(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ExUuidCreate(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopGetSetSecurityObject(), IopInvalidateVolumesForDevice(), IopMountVolume(), IopParseDevice(), IopSetDeviceSecurityDescriptor(), KeEnterCriticalRegion(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), MiDereferenceSessionFinal(), MiDispatchFault(), MiEmptyWorkingSet(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiFreeLargePageMemory(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiResolveTransitionFault(), MiUnlinkWorkingSet(), MmCopyToCachedPage(), MmExtendSection(), MmGatherMemoryForHibernate(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmLoadSystemImage(), MmLockPageableDataSection(), MmLockPageableSectionByHandle(), MmPrefetchPagesIntoLockedMdl(), MmSessionCreate(), MmSessionDelete(), MmUnloadSystemImage(), MmUnlockPageableImageSection(), NtAllocateUuids(), NtAssignProcessToJobObject(), NtQueryInformationJobObject(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetInformationProcess(), ObAuditObjectAccess(), ObClearProcessHandleTable(), ObDereferenceSecurityDescriptor(), ObDuplicateObject(), ObKillProcess(), ObLogSecurityDescriptor(), ObpCloseHandle(), ObpCreateHandle(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PsEnforceExecutionTimeLimits(), PsGetCurrentThreadWin32ThreadAndEnterCriticalRegion(), PsGetNextJobProcess(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PspAddProcessToJob(), PspCreateThread(), PspExitProcess(), PspExitProcessFromJob(), PspExitThread(), PspJobDelete(), PspLockProcessExclusive(), PspLockProcessShared(), PspLockThreadSecurityExclusive(), PspLockThreadSecurityShared(), PspRemoveProcessFromJob(), and PspTerminateAllProcessesInJob().
FORCEINLINE VOID KeEnterGuardedRegion (VOID)
Definition at line 85 of file kx.h.
References KeEnterGuardedRegionThread(), and KeGetCurrentThread().
Referenced by Phase1InitializationDiscard().
FORCEINLINE VOID KeEnterGuardedRegionThread (IN PKTHREAD Thread)
Definition at line 41 of file kx.h.
References APC_LEVEL, ASSERT, KeGetCurrentIrql(), KeGetCurrentThread(), and KeMemoryBarrierWithoutFence.
Referenced by IopQueueThreadIrp(), KeAcquireGuardedMutex(), KeEnterGuardedRegion(), KeTryToAcquireGuardedMutex(), MiAllocatePagesForMdl(), MiAttachAndLockWorkingSet(), MiFindContiguousPages(), MiFindLargePageMemory(), MiRemoveUserPhysicalPagesVad(), MiTrimAllSystemPageableMemory(), MmIdentifyPhysicalMemory(), MmPerfSnapShotValidPhysicalMemory(), MmPrefetchPagesIntoLockedMdl(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtQueryInformationJobObject(), NtSetInformationJobObject(), PsConvertToGuiThread(), PsGetContextThread(), PspAddProcessToJob(), PspJobClose(), PspLockJobLimitsExclusive(), PspLockJobLimitsShared(), PspLockJobListExclusive(), PspLockJobListShared(), PspLockJobTimeLimitsExclusive(), PspLockJobTimeLimitsShared(), PspLockProcessList(), PspLockWorkingSetChangeExclusive(), PspSetQuotaLimits(), and PsSetContextThread().
FORCEINLINE PKTHREAD FASTCALL KeGetOwnerGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 816 of file kx.h.
Referenced by __bcount().
FORCEINLINE VOID FASTCALL KeInitializeGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 430 of file kx.h.
References GM_LOCK_BIT, KeInitializeGate(), and NULL.
Referenced by CmInitSystem1(), CmpInitCmPrivateAlloc(), CmpInitCmPrivateDelayAlloc(), CmpInitDelayDerefKCBEngine(), CmpInitializeDelayedCloseTable(), CmpInitializeHive(), FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcb(), InitializePool(), MiInitializeSessionIds(), MiInitializeSessionPool(), MiInitializeSystemSpaceMap(), MmInitializeHandBuiltProcess(), MmInitializeProcessAddressSpace(), MmInitSystem(), ObInitSystem(), PspInitializeJobLimitsLock(), PspInitializeJobListLock(), PspInitializeJobTimeLimitsLock(), PspInitializeProcessListLock(), PspInitializeWorkingSetChangeLock(), and WmipStartGlobalLogger().
FORCEINLINE BOOLEAN FASTCALL KeIsGuardedMutexOwned (IN PKGUARDED_MUTEX Mutex)
Definition at line 844 of file kx.h.
References GM_LOCK_BIT.
FORCEINLINE VOID KeLeaveCriticalRegion (VOID)
Definition at line 336 of file kx.h.
References KeGetCurrentThread(), and KeLeaveCriticalRegionThread().
Referenced by CmpUnlockRegistry(), CmUnloadKey(), ExpGetSystemFirmwareTableInformation(), ExpRegisterFirmwareTableInformationHandler(), ExReleaseFastMutexUnsafeAndLeaveCriticalRegion(), ExReleaseResourceAndLeaveCriticalRegion(), KeThawAllThreads(), NtLoadKeyEx(), NtQuerySystemInformation(), NtReplaceKey(), ObpUnlockAllObjects(), ObpUnlockDirectory(), PsLocateSystemDll(), PsMapSystemDll(), and RtlpUnlockAtomTable().
FORCEINLINE VOID KeLeaveCriticalRegionThread (IN PKTHREAD Thread)
Definition at line 284 of file kx.h.
References ASSERT, KeGetCurrentThread(), KeMemoryBarrierWithoutFence, KernelMode, and KiCheckForKernelApcDelivery().
Referenced by ExChangeHandle(), ExCompareExchangeCallBack(), ExCreateHandle(), ExCreateHandleTable(), ExDestroyHandle(), ExDupHandleTable(), ExEnumHandleTable(), ExReferenceCallBackBlock(), ExRemoveHandleTable(), ExSetHandleInfo(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ExUuidCreate(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopGetSetSecurityObject(), IopInvalidateVolumesForDevice(), IopMountVolume(), IopParseDevice(), IopSetDeviceSecurityDescriptor(), KeLeaveCriticalRegion(), KeReleaseMutant(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), MiDereferenceSessionFinal(), MiDispatchFault(), MiEmptyWorkingSet(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiFreeLargePageMemory(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiResolveTransitionFault(), MiUnlinkWorkingSet(), MmCopyToCachedPage(), MmExtendSection(), MmGatherMemoryForHibernate(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmLoadSystemImage(), MmLockPageableDataSection(), MmLockPageableSectionByHandle(), MmPrefetchPagesIntoLockedMdl(), MmSessionCreate(), MmSessionDelete(), MmUnloadSystemImage(), MmUnlockPageableImageSection(), NtAllocateUuids(), NtAssignProcessToJobObject(), NtQueryInformationJobObject(), NtReleaseKeyedEvent(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetInformationProcess(), NtWaitForKeyedEvent(), ObAuditObjectAccess(), ObClearProcessHandleTable(), ObDereferenceSecurityDescriptor(), ObDuplicateObject(), ObKillProcess(), ObLogSecurityDescriptor(), ObpCloseHandle(), ObpCreateHandle(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PsEnforceExecutionTimeLimits(), PsGetNextJobProcess(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PspAddProcessToJob(), PspCreateThread(), PspExitProcess(), PspExitProcessFromJob(), PspExitThread(), PspJobDelete(), PspRemoveProcessFromJob(), PspTerminateAllProcessesInJob(), PspUnlockProcessExclusive(), PspUnlockProcessShared(), PspUnlockThreadSecurityExclusive(), and PspUnlockThreadSecurityShared().
FORCEINLINE VOID KeLeaveGuardedRegion (VOID)
Definition at line 172 of file kx.h.
References KeGetCurrentThread(), and KeLeaveGuardedRegionThread().
Referenced by KeReleaseGuardedMutex(), and Phase1InitializationDiscard().
FORCEINLINE VOID KeLeaveGuardedRegionThread (IN PKTHREAD Thread)
Definition at line 120 of file kx.h.
References APC_LEVEL, ASSERT, KeGetCurrentIrql(), KeGetCurrentThread(), KeMemoryBarrierWithoutFence, KernelMode, and KiCheckForKernelApcDelivery().
Referenced by IopQueueThreadIrp(), KeLeaveGuardedRegion(), KeTryToAcquireGuardedMutex(), MiAllocatePagesForMdl(), MiAttachAndLockWorkingSet(), MiFindContiguousPages(), MiFindLargePageMemory(), MiRemoveUserPhysicalPagesVad(), MiTrimAllSystemPageableMemory(), MmIdentifyPhysicalMemory(), MmPerfSnapShotValidPhysicalMemory(), MmPrefetchPagesIntoLockedMdl(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtQueryInformationJobObject(), NtSetInformationJobObject(), PsConvertToGuiThread(), PsGetContextThread(), PspAddProcessToJob(), PspJobClose(), PspSetQuotaLimits(), PspUnlockJobLimitsExclusive(), PspUnlockJobLimitsShared(), PspUnlockJobListExclusive(), PspUnlockJobListShared(), PspUnlockJobTimeLimitsExclusive(), PspUnlockJobTimeLimitsShared(), PspUnlockProcessList(), PspUnlockWorkingSetChangeExclusive(), and PsSetContextThread().
FORCEINLINE VOID FASTCALL KeReleaseGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 528 of file kx.h.
References APC_LEVEL, ASSERT, GM_LOCK_BIT, GM_LOCK_WAITER_INC, GM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), InterlockedExchangeAdd(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveGuardedRegion(), KeSignalGateBoostPriority(), NULL, and _KTHREAD::SpecialApcDisable.
Referenced by FsRtlAddLargeMcbEntry(), FsRtlGetNextLargeMcbEntry(), FsRtlLookupLargeMcbEntry(), FsRtlLookupLastLargeMcbEntry(), FsRtlLookupLastLargeMcbEntryAndIndex(), FsRtlNumberOfRunsInLargeMcb(), FsRtlPrivateInitializeFileLock(), FsRtlRemoveLargeMcbEntry(), FsRtlResetLargeMcb(), FsRtlSplitLargeMcb(), FsRtlTruncateLargeMcb(), MiAllocatePoolPages(), MiFreePoolPages(), MiInitializePoolEvents(), MiReleaseProcessReferenceToSessionDataPage(), MiSectionDelete(), MiSessionCreateInternal(), MmCreateSection(), MmExtendSection(), MmGetSizeOfBigPoolAllocation(), MmGetSystemPageFile(), MmResourcesAvailable(), NtCreatePagingFile(), WmipFreeLoggerContext(), and WmipStartLogger().
FORCEINLINE VOID FASTCALL KeReleaseGuardedMutexUnsafe (IN PKGUARDED_MUTEX Mutex)
Definition at line 740 of file kx.h.
References APC_LEVEL, ASSERT, GM_LOCK_BIT, GM_LOCK_WAITER_INC, GM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), InterlockedExchangeAdd(), KeGetCurrentIrql(), KeGetCurrentThread(), KeSignalGateBoostPriority(), MM_SYSTEM_RANGE_START, and NULL.
Referenced by MiCloneProcessAddressSpace(), MiMapViewOfDataSection(), MiProtectVirtualMemory(), MiRemoveMappedView(), MmCommitSessionMappedView(), NtAllocateVirtualMemory(), PspUnlockJobLimitsExclusive(), PspUnlockJobLimitsExclusiveUnsafe(), PspUnlockJobLimitsShared(), PspUnlockJobLimitsSharedUnsafe(), PspUnlockJobListExclusive(), PspUnlockJobListShared(), PspUnlockJobTimeLimitsExclusive(), PspUnlockJobTimeLimitsShared(), PspUnlockProcessList(), PspUnlockWorkingSetChangeExclusive(), and PspUnlockWorkingSetChangeExclusiveUnsafe().
FORCEINLINE BOOLEAN FASTCALL KeTryToAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 608 of file kx.h.
References APC_LEVEL, ASSERT, FALSE, GM_LOCK_BIT_V, InterlockedBitTestAndReset(), KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), KeYieldProcessor, _KTHREAD::SpecialApcDisable, and TRUE.
Referenced by Phase1InitializationDiscard().
VOID FASTCALL KiAcquireGuardedMutex (IN PKGUARDED_MUTEX Mutex)
Definition at line 1451 of file wait.c.
References ASSERT, GM_LOCK_BIT, GM_LOCK_WAITER_INC, GM_LOCK_WAITER_WOKEN, InterlockedCompareExchange(), KernelMode, KeWaitForGate(), TRUE, and WrGuardedMutex.
Referenced by KeAcquireGuardedMutex(), and KeAcquireGuardedMutexUnsafe().
NTKERNELAPI VOID KiCheckForKernelApcDelivery (VOID)
Definition at line 24 of file apcsup.c.
References APC_LEVEL, _KTHREAD::ApcState, KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, _KAPC_STATE::KernelApcPending, KernelMode, KfRaiseIrql(), KiDeliverApc(), KiRequestSoftwareInterrupt, NULL, PASSIVE_LEVEL, and TRUE.
Referenced by KeLeaveCriticalRegionThread(), and KeLeaveGuardedRegionThread().