Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/physical.c File Reference
physical.c File Reference
#include "mi.h"
Macros
#define BITS_IN_ULONG ((sizeof (ULONG)) * 8)
#define COPY_STACK_SIZE 1024
#define InterlockedZeroPointer(P)
#define LOWEST_BITMAP_PHYSICAL_PAGE 0
#define LOWEST_USABLE_PHYSICAL_ADDRESS (16 * 1024 * 1024)
#define LOWEST_USABLE_PHYSICAL_PAGE (LOWEST_USABLE_PHYSICAL_ADDRESS >> PAGE_SHIFT)
#define MI_BITMAP_INDEX_TO_FRAME(x) ((ULONG)(x))
#define MI_FRAME_TO_BITMAP_INDEX(x) ((ULONG)(x))
#define MI_WRITE_ZERO_PTE_NO_LOGGING(PointerPte) PointerPte->u.Long = 0
#define SMALL_COPY_STACK_SIZE (COPY_STACK_SIZE / 2)
#define VERY_SMALL_COPY_STACK_SIZE 64
Functions
PVOID MiAllocateAweInfo (VOID)
NTSTATUS MiAllocateLargePages (IN PVOID StartingAddress, IN PVOID EndingAddress, IN MM_PROTECTION_MASK ProtectionMask, IN LOGICAL CallerHasPages)
PMI_LARGEPAGE_MEMORY_RUN MiAllocateLargeZeroPages (IN PFN_NUMBER NumberOfPages, IN MM_PROTECTION_MASK ProtectionMask)
VOID MiAweViewInserter (IN PEPROCESS Process, IN PMI_PHYSICAL_VIEW PhysicalView)
VOID MiAweViewRemover (IN PEPROCESS Process, IN PMMVAD Vad)
NTSTATUS MiCaptureUlongPtrArray (OUT PVOID Destination, IN PVOID Source, IN ULONG_PTR ArraySize)
VOID MiCleanPhysicalProcessPages (IN PEPROCESS Process)
VOID MiFreeAweInfo (IN PAWEINFO AweInfo)
VOID MiFreeLargePages (IN PVOID StartingAddress, IN PVOID EndingAddress, IN LOGICAL CallerHadPages)
PVOID MiInsertAweInfo (IN PAWEINFO AweInfo)
WIN32_PROTECTION_MASK MiProtectAweRegion (IN PVOID StartingAddress, IN PVOID EndingAddress, IN MM_PROTECTION_MASK ProtectionMask)
VOID MiReleasePhysicalCharges (IN SIZE_T NumberOfPages, IN PEPROCESS Process)
VOID MiRemoveUserPhysicalPagesVad (IN PMMVAD_SHORT Vad)
VOID MiReturnLargePages (IN PMI_LARGEPAGE_MEMORY_RUN LargePageListHead)
PFN_NUMBER MmSetPhysicalPagesLimit (IN PFN_NUMBER NewPhysicalPagesLimit)
NTSTATUS NtAllocateUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __out_ecount(*NumberOfPages) PULONG_PTR UserPfnArray)
NTSTATUS NtFreeUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __in_ecount(*NumberOfPages) PULONG_PTR UserPfnArray)
NTSTATUS NtMapUserPhysicalPages (__in PVOID VirtualAddress, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
NTSTATUS NtMapUserPhysicalPagesScatter (__in_ecount(NumberOfPages) PVOID *VirtualAddresses, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
Variables
PFN_NUMBER MmVadPhysicalPages
Macro Definition Documentation
#define BITS_IN_ULONG ((sizeof (ULONG)) * 8)
Definition at line 99 of file physical.c.
#define COPY_STACK_SIZE 1024
Definition at line 94 of file physical.c.
Referenced by NtMapUserPhysicalPages().
#define InterlockedZeroPointer (P)
Value:
{                                                       \
            InterlockedAnd ((PLONG)&(P), 0);                    \
        }
Definition at line 58 of file physical.c.
Referenced by NtMapUserPhysicalPages(), and NtMapUserPhysicalPagesScatter().
#define LOWEST_BITMAP_PHYSICAL_PAGE 0
Definition at line 104 of file physical.c.
#define LOWEST_USABLE_PHYSICAL_ADDRESS (16 * 1024 * 1024)
Definition at line 101 of file physical.c.
Referenced by NtAllocateUserPhysicalPages().
#define LOWEST_USABLE_PHYSICAL_PAGE (LOWEST_USABLE_PHYSICAL_ADDRESS >> PAGE_SHIFT)
Definition at line 102 of file physical.c.
Referenced by MiCleanPhysicalProcessPages(), MiRemoveUserPhysicalPagesVad(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
#define MI_BITMAP_INDEX_TO_FRAME (x) ((ULONG)(x))
Definition at line 106 of file physical.c.
Referenced by MiCleanPhysicalProcessPages().
#define MI_FRAME_TO_BITMAP_INDEX (x) ((ULONG)(x))
Definition at line 105 of file physical.c.
Referenced by NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
#define MI_WRITE_ZERO_PTE_NO_LOGGING (PointerPte) PointerPte->u.Long = 0
Definition at line 115 of file physical.c.
Referenced by MiRemoveUserPhysicalPagesVad(), and NtFreeUserPhysicalPages().
#define SMALL_COPY_STACK_SIZE (COPY_STACK_SIZE / 2)
Definition at line 96 of file physical.c.
Referenced by NtMapUserPhysicalPagesScatter().
#define VERY_SMALL_COPY_STACK_SIZE 64
Definition at line 97 of file physical.c.
Referenced by MiCleanPhysicalProcessPages(), and NtFreeUserPhysicalPages().
Function Documentation
PVOID MiAllocateAweInfo (VOID)
Definition at line 1263 of file physical.c.
References ASSERT, _AWEINFO::AweVadRoot, _MM_AVL_TABLE::BalancedRoot, ExAllocateCacheAwarePushLock(), ExAllocatePoolWithTag, ExFreePool(), MAXIMUM_PROCESSORS, NonPagedPool, NULL, _MM_AVL_TABLE::NumberGenericTableElements, _MMADDRESS_NODE::Parent, _AWEINFO::PhysicalViewHint, _AWEINFO::PushLock, RtlZeroMemory, _MMADDRESS_NODE::u1, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesBitMap, and _AWEINFO::VadPhysicalPagesLimit.
Referenced by MiMapViewOfImageSection(), NtAllocateUserPhysicalPages(), and NtAllocateVirtualMemory().
NTSTATUS MiAllocateLargePages (IN PVOID StartingAddress, IN PVOID EndingAddress, IN MM_PROTECTION_MASK ProtectionMask, IN LOGICAL CallerHasPages)
Definition at line 3293 of file physical.c.
References ASSERT, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _MI_LARGEPAGE_MEMORY_RUN::BasePage, BYTES_TO_PAGES, ExFreePool(), FALSE, _MMPTE::Hard, _EPROCESS::JobStatus, KeAreAllApcsDisabled(), LOCK_PFN, LOCK_WS_UNSAFE, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_MAKE_PDE_MAP_LARGE_PAGE, MI_MAKE_VALID_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SET_ACCESSED_IN_PTE, MI_SET_PFN_DELETED, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiAllocateLargeZeroPages(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiMakePdeExistAndMakeValid(), MM_NOIRQL, MM_RESAVAIL_ALLOCATE_USER_PAGE_TABLE, MM_RESAVAIL_FREE_USER_PAGE_TABLE, MM_VA_MAPPED_BY_PDE, _MI_LARGEPAGE_MEMORY_RUN::Next, NULL, NumberOfBytes, PAGE_SHIFT, _MI_LARGEPAGE_MEMORY_RUN::PageCount, _MMPTE_HARDWARE::PageFrameNumber, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PsChangeJobMemoryUsage(), PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, STATUS_COMMITMENT_LIMIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WS_UNSAFE, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesLimit, and _MMPTE_HARDWARE::Valid.
Referenced by MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), and NtAllocateVirtualMemory().
PMI_LARGEPAGE_MEMORY_RUN MiAllocateLargeZeroPages (IN PFN_NUMBER NumberOfPages, IN MM_PROTECTION_MASK ProtectionMask)
Definition at line 3052 of file physical.c.
References ASSERT, _MI_LARGEPAGE_MEMORY_RUN::BasePage, ExAllocatePoolWithTag, ExFreePool(), ExPageLockHandle, FALSE, InterlockedDecrement, InterlockedIncrement, KeDelayExecutionThread(), KernelMode, MiDelayPageFaults, MiFindLargePageMemory(), MiFlushAllPages(), MiReturnLargePages(), MiZeroInParallel(), MM_EMPTY_LIST, MM_MINIMUM_VA_FOR_LARGE_PAGE, MmEmptyAllWorkingSets(), MmHalfSecond, MmLockPageableSectionByHandle(), MmOneSecond, MmSecondaryColors, MmUnlockPageableImageSection(), _MI_LARGEPAGE_MEMORY_RUN::Next, NonPagedPool, NULL, PAGE_SHIFT, _MI_LARGEPAGE_MEMORY_RUN::PageCount, _COLORED_PAGE_INFO::PagesQueued, _COLORED_PAGE_INFO::PfnAllocation, and TRUE.
Referenced by MiAllocateLargePages(), and MiCreatePagingFileMap().
VOID MiAweViewInserter (IN PEPROCESS Process, IN PMI_PHYSICAL_VIEW PhysicalView)
Definition at line 2864 of file physical.c.
References ASSERT, _AWEINFO::AweVadRoot, ExAcquireCacheAwarePushLockExclusive(), ExReleaseCacheAwarePushLockExclusive(), MiInsertNode(), NULL, and _AWEINFO::PushLock.
Referenced by NtAllocateVirtualMemory().
VOID MiAweViewRemover (IN PEPROCESS Process, IN PMMVAD Vad)
Definition at line 2907 of file physical.c.
References ASSERT, _AWEINFO::AweVadRoot, ExAcquireCacheAwarePushLockExclusive(), ExFreePool(), ExReleaseCacheAwarePushLockExclusive(), MAXIMUM_PROCESSORS, MiFindNodeOrParent(), MiRemoveNode(), NULL, _AWEINFO::PhysicalViewHint, _AWEINFO::PushLock, RtlZeroMemory, TableFoundNode, _MI_PHYSICAL_VIEW::Vad, VadAwe, and VadLargePages.
Referenced by MmCleanProcessAddressSpace(), and NtFreeVirtualMemory().
NTSTATUS MiCaptureUlongPtrArray (OUT PVOID Destination, IN PVOID Source, IN ULONG_PTR ArraySize)
Definition at line 3921 of file physical.c.
References except, EXCEPTION_EXECUTE_HANDLER, NULL, ProbeForRead, PsGetCurrentProcess(), RtlCopyMemory, and STATUS_SUCCESS.
Referenced by NtFreeUserPhysicalPages(), NtMapUserPhysicalPages(), and NtMapUserPhysicalPagesScatter().
VOID MiCleanPhysicalProcessPages (IN PEPROCESS Process)
Definition at line 2663 of file physical.c.
References _4gb, ASSERT, ASSERT64, _MMPFN::AweAllocation, ExFreeCacheAwarePushLock(), ExFreePool(), InterlockedExchangeAddSizeT, KeAreAllApcsDisabled(), LOWEST_USABLE_PHYSICAL_PAGE, MI_BITMAP_INDEX_TO_FRAME, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PFN_DELETED, MmFreePagesFromMdl(), MmHighestPossiblePhysicalPage, MmInitializeMdl, MmVadPhysicalPages, NO_BITS_FOUND, NULL, PAGE_SHIFT, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PsChangeJobMemoryUsage(), PsReturnProcessNonPagedPoolQuota(), _MMPFN::PteAddress, _AWEINFO::PushLock, RtlFindSetBits(), _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, TRUE, _MMPFN::u2, _MMPFN::u4, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesBitMap, and VERY_SMALL_COPY_STACK_SIZE.
Referenced by MmCleanProcessAddressSpace().
VOID MiFreeAweInfo (IN PAWEINFO AweInfo)
Definition at line 1324 of file physical.c.
References ExFreeCacheAwarePushLock(), and ExFreePool().
Referenced by NtAllocateUserPhysicalPages(), and NtAllocateVirtualMemory().
VOID MiFreeLargePages (IN PVOID StartingAddress, IN PVOID EndingAddress, IN LOGICAL CallerHadPages)
Definition at line 3657 of file physical.c.
References ASSERT, FALSE, _MMPTE::Hard, LOCK_PFN, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_FLUSH_PROCESS_TB, MI_GET_USED_PTES_FROM_HANDLE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_WRITE_ZERO_PTE, MiDeletePte(), MiFreeLargePageMemory(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MM_RESAVAIL_FREE_USER_PAGE_TABLE, MM_VA_MAPPED_BY_PDE, NULL, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, PsGetCurrentProcess(), _MMPFN::PteFrame, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiMapViewOfImageSection(), MiRemoveMappedView(), MmCleanProcessAddressSpace(), and NtFreeVirtualMemory().
PVOID MiInsertAweInfo (IN PAWEINFO AweInfo)
Definition at line 1356 of file physical.c.
References ASSERT, _EPROCESS::AweInfo, ExFreeCacheAwarePushLock(), ExFreePool(), InterlockedCompareExchangePointer, NULL, and PsGetCurrentProcess().
Referenced by MiMapViewOfImageSection(), NtAllocateUserPhysicalPages(), and NtAllocateVirtualMemory().
WIN32_PROTECTION_MASK MiProtectAweRegion (IN PVOID StartingAddress, IN PVOID EndingAddress, IN MM_PROTECTION_MASK ProtectionMask)
Definition at line 4028 of file physical.c.
References ASSERT, _EPROCESS::AweInfo, _MMPTE_FLUSH_LIST::Count, ExAcquireCacheAwarePushLockExclusive(), ExReleaseCacheAwarePushLockExclusive(), _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_USER_PTE, MI_PTE_OWNER_KERNEL, MI_PTE_OWNER_USER, MI_SET_OWNER_IN_PTE, MI_SET_PTE_DIRTY, MiFlushPteList(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MM_MAXIMUM_FLUSH_COUNT, MM_NOACCESS, MM_READWRITE, NULL, _MMPTE_HARDWARE::Owner, PAGE_NOACCESS, PAGE_READONLY, PAGE_READWRITE, _MMPTE_HARDWARE::PageFrameNumber, PsGetCurrentProcessByThread, PsGetCurrentThread(), _AWEINFO::PushLock, _MMPTE::u, _AWEINFO::VadPhysicalPagesBitMap, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by MiProtectVirtualMemory().
VOID MiReleasePhysicalCharges (IN SIZE_T NumberOfPages, IN PEPROCESS Process)
Definition at line 3609 of file physical.c.
References ASSERT, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PsChangeJobMemoryUsage(), PsGetCurrentProcess(), and _AWEINFO::VadPhysicalPages.
Referenced by MiMapViewOfImageSection(), MiRemoveMappedView(), MmCleanProcessAddressSpace(), and NtFreeVirtualMemory().
VOID MiRemoveUserPhysicalPagesVad (IN PMMVAD_SHORT Vad)
Definition at line 2491 of file physical.c.
References ASSERT, _EPROCESS::AweInfo, _AWEINFO::AweVadRoot, _MMPTE_FLUSH_LIST::Count, ExAcquireCacheAwarePushLockExclusive(), ExReleaseCacheAwarePushLockExclusive(), _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, KeAreAllApcsDisabled(), KeEnterGuardedRegionThread(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), LOWEST_USABLE_PHYSICAL_PAGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_ZERO_PTE_NO_LOGGING, MiEnumerateGenericTableWithoutSplayingAvl(), MiFlushPteList(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MM_MAXIMUM_FLUSH_COUNT, NULL, PsGetCurrentProcess(), _MMPFN::PteAddress, _AWEINFO::PushLock, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u2, _MI_PHYSICAL_VIEW::Vad, VadAwe, _AWEINFO::VadPhysicalPages, and _MMPTE_HARDWARE::Valid.
Referenced by MmCleanProcessAddressSpace(), and NtFreeVirtualMemory().
VOID MiReturnLargePages (IN PMI_LARGEPAGE_MEMORY_RUN LargePageListHead)
Definition at line 2973 of file physical.c.
References ActiveAndValid, ASSERT, _MMPFN::AweAllocation, _MI_LARGEPAGE_MEMORY_RUN::BasePage, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, ExFreePool(), FALSE, LOCK_PFN, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MiCached, MiInsertPageInFreeList(), MM_RESAVAIL_FREE_LARGE_PAGES, _MI_LARGEPAGE_MEMORY_RUN::Next, NULL, _MI_LARGEPAGE_MEMORY_RUN::PageCount, _MMPFNENTRY::PageLocation, _MMPFNENTRY::PrototypePte, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPFN::VerifierAllocation.
Referenced by MiAllocateLargeZeroPages(), and MiCreatePagingFileMap().
PFN_NUMBER MmSetPhysicalPagesLimit (IN PFN_NUMBER NewPhysicalPagesLimit)
Definition at line 3856 of file physical.c.
References _EPROCESS::AweInfo, LOCK_ADDRESS_SPACE, NULL, PAGED_CODE, PsGetCurrentProcessByThread, PsGetCurrentThread(), UNLOCK_ADDRESS_SPACE, and _AWEINFO::VadPhysicalPagesLimit.
NTSTATUS NtAllocateUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __out_ecount *NumberOfPages PULONG_PTR UserPfnArray)
Definition at line 1415 of file physical.c.
References _4gb, ASSERT, ASSERT64, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _RTL_BITMAP::Buffer, _MDL::ByteCount, ExAcquireCacheAwarePushLockExclusive(), ExAllocatePoolWithTag, except, ExFreePool(), ExReleaseCacheAwarePushLockExclusive(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, InterlockedExchangeAddSizeT, _EPROCESS::JobStatus, KeGetCurrentIrql(), KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOWEST_USABLE_PHYSICAL_ADDRESS, LOWEST_USABLE_PHYSICAL_PAGE, MAXULONG, MAXULONG_PTR, MI_ALLOCATION_IS_AWE, MI_CHECK_BIT, MI_FRAME_TO_BITMAP_INDEX, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_BIT, MiAllocateAweInfo(), MiAllocatePagesForMdl(), MiCached, MiFreeAweInfo(), MiInsertAweInfo(), MmFreePagesFromMdl(), MmHighestPossiblePhysicalPage, MmVadPhysicalPages, _MDL::Next, NonPagedPool, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PASSIVE_LEVEL, _EPROCESS::Pcb, ProbeForWrite(), ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PS_PROCESS_FLAGS_VM_DELETED, PsChangeJobMemoryUsage(), PsChargeProcessNonPagedPoolQuota(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _MMPFN::PteAddress, _AWEINFO::PushLock, _LARGE_INTEGER::QuadPart, RtlClearAllBits(), RtlCopyMemory, RtlInitializeBitMap(), SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, Status, STATUS_COMMITMENT_LIMIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_2, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPFN::u2, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesBitMap, and _AWEINFO::VadPhysicalPagesLimit.
NTSTATUS NtFreeUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __in_ecount *NumberOfPages PULONG_PTR UserPfnArray)
Definition at line 2013 of file physical.c.
References _4gb, ASSERT, ASSERT64, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _RTL_BITMAP::Buffer, _MDL::ByteCount, _MMPTE_FLUSH_LIST::Count, ExAcquireCacheAwarePushLockExclusive(), except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExReleaseCacheAwarePushLockExclusive(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedExchangeAddSizeT, _EPROCESS::JobStatus, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeMemoryBarrier(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOWEST_USABLE_PHYSICAL_PAGE, MAXULONG, MI_CHECK_BIT, MI_CLEAR_BIT, MI_FLUSH_PROCESS_TB, MI_FRAME_TO_BITMAP_INDEX, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE_NO_LOGGING, MiCaptureUlongPtrArray(), MiFlushPteList(), MiGetVirtualAddressMappedByPte, MM_MAXIMUM_FLUSH_COUNT, MmCreateMdl(), MmFreePagesFromMdl(), MmInitializeMdl, MmVadPhysicalPages, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, NumberOfBytes, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PASSIVE_LEVEL, _EPROCESS::Pcb, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PS_PROCESS_FLAGS_VM_DELETED, PsChangeJobMemoryUsage(), PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _MMPFN::PteAddress, _AWEINFO::PushLock, RtlCopyMemory, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesBitMap, _MMPTE_HARDWARE::Valid, and VERY_SMALL_COPY_STACK_SIZE.
NTSTATUS NtMapUserPhysicalPages (__in PVOID VirtualAddress, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
Definition at line 118 of file physical.c.
References ARGUMENT_PRESENT, ASSERT, _EPROCESS::AweInfo, _AWEINFO::AweVadRoot, _RTL_BITMAP::Buffer, COPY_STACK_SIZE, _MMPTE_FLUSH_LIST::Count, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), ExAllocatePoolWithTag, ExFreePool(), ExReleaseCacheAwarePushLockShared(), _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedCompareExchangePointer, InterlockedExchangePte, InterlockedZeroPointer, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KeMemoryBarrier(), _MMPTE::Long, MAXULONG_PTR, MI_CHECK_BIT, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PTE_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiCaptureUlongPtrArray(), MiFindNodeOrParent(), MiFlushPteList(), MiGetPteAddress, MiHighestUserPte, MM_MAXIMUM_FLUSH_COUNT, MM_READWRITE, NonPagedPool, NOTHING, NT_SUCCESS, NULL, NumberOfBytes, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _AWEINFO::PhysicalViewHint, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _AWEINFO::PushLock, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, _MMPTE::u, _MMPFN::u2, VadAwe, _AWEINFO::VadPhysicalPagesBitMap, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and ZeroPte.
NTSTATUS NtMapUserPhysicalPagesScatter (__in_ecount(NumberOfPages) PVOID * VirtualAddresses, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
Definition at line 633 of file physical.c.
References ARGUMENT_PRESENT, ASSERT, _EPROCESS::AweInfo, _AWEINFO::AweVadRoot, _RTL_BITMAP::Buffer, _MMPTE_FLUSH_LIST::Count, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), ExAllocatePoolWithTag, ExFreePool(), ExReleaseCacheAwarePushLockShared(), _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedCompareExchangePointer, InterlockedExchangePte, InterlockedZeroPointer, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KeMemoryBarrier(), _MMPTE::Long, MAXULONG_PTR, MI_CHECK_BIT, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PTE_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiCaptureUlongPtrArray(), MiFindNodeOrParent(), MiFlushPteList(), MiGetPteAddress, MiHighestUserPte, MM_MAXIMUM_FLUSH_COUNT, MM_READWRITE, NonPagedPool, NT_SUCCESS, NULL, NumberOfBytes, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _AWEINFO::PhysicalViewHint, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _AWEINFO::PushLock, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, SMALL_COPY_STACK_SIZE, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, _MMPTE::u, _MMVAD::u, _MMPFN::u2, _MI_PHYSICAL_VIEW::Vad, VadAwe, _MMVAD::VadFlags, _AWEINFO::VadPhysicalPagesBitMap, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and ZeroPte.
Variable Documentation
PFN_NUMBER MmVadPhysicalPages
Definition at line 108 of file physical.c.
Referenced by MiCleanPhysicalProcessPages(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().