Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/misc.c File Reference
misc.c File Reference
#include "ki.h"
Functions
PKPRCB KeQueryPrcbAddress (__in ULONG Number)
VOID KeRestoreProcessorSpecificFeatures (VOID)
VOID KeSaveStateForHibernate (__out PKPROCESSOR_STATE ProcessorState)
VOID KiProcessNMI (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
VOID KiWaitForReboot (VOID)
Function Documentation
PKPRCB KeQueryPrcbAddress (__in ULONG Number)
Definition at line 22 of file misc.c.
References ASSERT, KeNumberProcessors, and KiProcessorBlock.
VOID KeRestoreProcessorSpecificFeatures (VOID)
Definition at line 50 of file misc.c.
References KiSetPageAttributesTable(), and XHF_FFXSR.
VOID KeSaveStateForHibernate (__out PKPROCESSOR_STATE ProcessorState)
Definition at line 99 of file misc.c.
References KiSaveProcessorControlState(), and RtlCaptureContext().
VOID KiProcessNMI (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 141 of file misc.c.
References FALSE, HalHandleNMI(), KeBugCheckActive, KeGetCurrentPrcb(), KeReleaseSpinLockFromDpcLevel(), KiAcquireSpinLockCheckForFreeze(), KiCheckForFreezeExecution(), KiHandleNmi(), KiNMILock, NULL, _KPRCB::Number, and TRUE.
VOID KiWaitForReboot (VOID)
Definition at line 215 of file misc.c.
References NOTHING, and TRUE.
Referenced by KiCheckForFreezeExecution().