Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/umapview.c File Reference
umapview.c File Reference
#include "mi.h"
Functions
VOID MiDecrementSubsections (IN PSUBSECTION FirstSubsection, IN PSUBSECTION LastSubsection OPTIONAL)
VOID MiPurgeImageSection (IN PCONTROL_AREA ControlArea, IN KIRQL OldIrql)
VOID MiRemoveMappedView (IN PEPROCESS CurrentProcess, IN PMMVAD Vad)
NTSTATUS MiUnmapViewOfSection (IN PEPROCESS Process, IN PVOID BaseAddress, IN ULONG Flags)
NTSTATUS MmUnmapViewOfSection (__in PEPROCESS Process, __in PVOID BaseAddress)
NTSTATUS NtUnmapViewOfSection (__in HANDLE ProcessHandle, __in PVOID BaseAddress)
Function Documentation
VOID MiDecrementSubsections (IN PSUBSECTION FirstSubsection, IN PSUBSECTION LastSubsection OPTIONAL)
Definition at line 323 of file umapview.c.
References ARGUMENT_PRESENT, ASSERT, _MSUBSECTION::DereferenceList, _LIST_ENTRY::Flink, InsertTailList(), MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MM_PFN_LOCK_ASSERT, MmUnusedSubsectionList, NULL, _MSUBSECTION::NumberOfMappedViews, _MSUBSECTION::SubsectionFlags, _MMSUBSECTION_FLAGS::SubsectionStatic, TRUE, and _MSUBSECTION::u.
Referenced by MiRemoveMappedView(), MmFlushSection(), and MmPurgeSection().
VOID MiPurgeImageSection (IN PCONTROL_AREA ControlArea, IN KIRQL OldIrql)
Definition at line 893 of file umapview.c.
References ASSERT, _SUBSECTION::ControlArea, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, _MMSUBSECTION_FLAGS::GlobalMemory, _MMPTE::Hard, KeDelayExecutionThread(), KernelMode, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_INVALID_PTE, MiDecrementShareCountInline, MiDeferredUnlockPages(), MiGetPteAddress, MiGetSubsectionAddressForPte, MiInsertPageInFreeList(), MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), MiReleasePageFileSpace(), MiUnlinkPageFromList(), MMSECTOR_SHIFT, MmShortTime, _MMPFNENTRY::Modified, _SUBSECTION::NextSubsection, NoAccessPte, NULL, _SUBSECTION::NumberOfFullSectors, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMSUBSECTION_FLAGS::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteFrame, _SUBSECTION::PtesInSubsection, _MMSUBSECTION_FLAGS::SectorEndOffset, _MMPTE::Soft, _SUBSECTION::StartingSector, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _SUBSECTION::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiCheckControlArea().
VOID MiRemoveMappedView (IN PEPROCESS CurrentProcess, IN PMMVAD Vad)
Definition at line 399 of file umapview.c.
References _MI_PAGING_LEVELS, ASSERT, _MMVAD_LONG::ControlArea, _MMPTE_FLUSH_LIST::Count, _MMVAD_LONG::EndingVpn, ExFreePool(), _MMVAD_LONG::ExtendedInfo, _SEGMENT::ExtendInfo, FALSE, _CONTROL_AREA::FilePointer, _MMVAD_LONG::FirstPrototypePte, _MMPTE::Hard, InterlockedDecrement, KeAcquireGuardedMutexUnsafe(), KeReleaseGuardedMutexUnsafe(), _SEGMENT_FLAGS::LargePages, LOCK_PFN, LOCK_WS_UNSAFE, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_FLUSH_PROCESS_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_USED_PTES_FROM_HANDLE, MI_GET_USED_PTES_HANDLE, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_ZERO_PTE, MiCheckControlArea(), MiDecrementShareCountInline, MiDecrementSubsections(), MiDeletePte(), MiDeleteVirtualAddresses(), MiFreeLargePages(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiLocateSubsection(), MiPhysicalViewRemover(), MiReleasePhysicalCharges(), MM_EXECUTE_READWRITE, MM_MAXIMUM_FLUSH_COUNT, MM_READWRITE, MM_VA_MAPPED_BY_PDE, MmSectionBasedMutex, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfUserReferences, PAGE_SHIFT, PsGetCurrentThread(), _MMEXTEND_INFO::ReferenceCount, _CONTROL_AREA::Segment, _SEGMENT::SegmentFlags, _MMPFN::ShareCount, _MMVAD_LONG::StartingVpn, TRUE, _MMPTE::u, _MMPFN::u2, _MMVAD_LONG::u4, UNLOCK_PFN, UNLOCK_WS_UNSAFE, VadDevicePhysicalMemory, VadImageMap, VadLargePageSection, _MMPTE_HARDWARE::Valid, and _CONTROL_AREA::WritableUserReferences.
Referenced by MiUnmapViewOfSection(), and MmCleanProcessAddressSpace().
NTSTATUS MiUnmapViewOfSection (IN PEPROCESS Process, IN PVOID BaseAddress, IN ULONG Flags)
Definition at line 83 of file umapview.c.
References ASSERT, DbgkUnMapViewOfSection(), _MMVAD::EndingVpn, ExFreePool(), FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiCheckSecuredVad(), MiGetNextVad, MiGetPreviousVad, MiLocateAddress(), MiPhysicalViewRemover(), MiRemoveMappedView(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MM_SECURE_DELETE_CHECK, _MMVAD_FLAGS::NoChange, NT_SUCCESS, NULL, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMVAD_FLAGS::PrivateMemory, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMVAD::StartingVpn, STATUS_NOT_MAPPED_VIEW, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, TRUE, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNMAP_ADDRESS_SPACE_HELD, UNMAP_ROTATE_PHYSICAL_OK, _MMVAD::VadFlags, VadImageMap, VadRotatePhysical, and _MMVAD_FLAGS::VadType.
Referenced by MiLoadImageSection(), MiMapViewOfImageSection(), MmUnmapViewOfSection(), NtFreeVirtualMemory(), and NtUnmapViewOfSection().
NTSTATUS MmUnmapViewOfSection (__in PEPROCESS Process, __in PVOID BaseAddress)
Definition at line 295 of file umapview.c.
References MiUnmapViewOfSection().
Referenced by LpcpDeletePort(), and PsShutdownSystem().
NTSTATUS NtUnmapViewOfSection (__in HANDLE ProcessHandle, __in PVOID BaseAddress)
Definition at line 29 of file umapview.c.
References KeGetPreviousMode, MiUnmapViewOfSection(), MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_VM_OPERATION, PsProcessType, Status, STATUS_NOT_MAPPED_VIEW, and UserMode.