Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntrtl.h File Reference
ntrtl.h File Reference
#include <string.h>
#include <guiddef.h>
#include "ntrtlstringandbuffer.h"
#include "ntrtlpath.h"
Data Structures
struct _COMPRESSED_DATA_INFO
struct _CURDIR
struct _CURDIR64
struct _GENERATE_NAME_CONTEXT
struct _LAST_EXCEPTION_LOG
struct _MESSAGE_RESOURCE_BLOCK
struct _MESSAGE_RESOURCE_DATA
struct _MESSAGE_RESOURCE_ENTRY
struct _OSVERSIONINFOA
struct _OSVERSIONINFOEXA
struct _OSVERSIONINFOEXW
struct _OSVERSIONINFOW
struct _PARSE_MESSAGE_CONTEXT
struct _PREFIX_TABLE
struct _PREFIX_TABLE_ENTRY
struct _RANGE_LIST_ITERATOR
struct _RTL_AVL_TABLE
struct _RTL_BALANCED_LINKS
struct _RTL_BITMAP
struct _RTL_BITMAP_RUN
struct _RTL_DRIVE_LETTER_CURDIR
struct _RTL_DRIVE_LETTER_CURDIR64
struct _RTL_GENERIC_TABLE
struct _RTL_HEAP_PARAMETERS
struct _RTL_PROCESS_BACKTRACE_INFORMATION
struct _RTL_PROCESS_BACKTRACES
struct _RTL_PROCESS_LOCK_INFORMATION
struct _RTL_PROCESS_LOCKS
struct _RTL_QUERY_REGISTRY_TABLE
struct _RTL_RANGE
struct _RTL_RANGE_LIST
struct _RTL_RXACT_CONTEXT
struct _RTL_RXACT_LOG
struct _RTL_SPLAY_LINKS
struct _RTL_STACK_CONTEXT
struct _RTL_STACK_CONTEXT_ENTRY
struct _RTL_TIME_ZONE_INFORMATION
struct _RTL_TRACE_BLOCK
struct _RTL_TRACE_ENUMERATE
struct _RTL_USER_PROCESS_INFORMATION
struct _RTL_USER_PROCESS_INFORMATION64
struct _RTL_USER_PROCESS_PARAMETERS
struct _RTL_USER_PROCESS_PARAMETERS64
union _SLIST_HEADER
struct _TIME_FIELDS
struct _UNICODE_PREFIX_TABLE
struct _UNICODE_PREFIX_TABLE_ENTRY
Macros
#define __IID_ALIGNED__
#define _SLIST_ENTRY _SINGLE_LIST_ENTRY
#define _SLIST_HEADER_
#define ASSERT(exp) ((void) 0)
#define ASSERTMSG(msg, exp) ((void) 0)
#define CLEAR_PARSE_MESSAGE_CONTEXT_FLAG(ctx, flag) ((ctx)->fFlags &= ~(flag))
#define COMPRESSION_ENGINE_HIBER (0x0200)
#define COMPRESSION_ENGINE_MAXIMUM (0x0100)
#define COMPRESSION_ENGINE_STANDARD (0x0000)
#define COMPRESSION_FORMAT_DEFAULT (0x0001)
#define COMPRESSION_FORMAT_LZNT1 (0x0002)
#define COMPRESSION_FORMAT_NONE (0x0000)
#define DBG_STATUS_BUGCHECK_FIRST 3
#define DBG_STATUS_BUGCHECK_SECOND 4
#define DBG_STATUS_CONTROL_C 1
#define DBG_STATUS_DEBUG_CONTROL 6
#define DBG_STATUS_FATAL 5
#define DBG_STATUS_SYSRQ 2
#define DBG_STATUS_WORKER 7
#define DEFINE_GUIDEX(name) EXTERN_C const CDECL GUID name
#define DOS_MAX_COMPONENT_LENGTH 255
#define DOS_MAX_PATH_LENGTH (DOS_MAX_COMPONENT_LENGTH + 5)
#define DPFLTR_ERROR_LEVEL 0
#define DPFLTR_INFO_LEVEL 3
#define DPFLTR_MASK 0x80000000
#define DPFLTR_TRACE_LEVEL 2
#define DPFLTR_WARNING_LEVEL 1
#define FIRSTBYTE(VALUE) ((VALUE) & LOWBYTE_MASK)
#define FOR_ALL_RANGES(RangeList, Iterator, Current)
#define FOR_ALL_RANGES_BACKWARDS(RangeList, Iterator, Current)
#define FOURTHBYTE(VALUE) (((VALUE) >> 24) & LOWBYTE_MASK)
#define HASH_STRING_ALGORITHM_DEFAULT (0)
#define HASH_STRING_ALGORITHM_INVALID (0xffffffff)
#define HASH_STRING_ALGORITHM_X65599 (1)
#define HEAP_CLASS_0 0x00000000
#define HEAP_CLASS_1 0x00001000
#define HEAP_CLASS_2 0x00002000
#define HEAP_CLASS_3 0x00003000
#define HEAP_CLASS_4 0x00004000
#define HEAP_CLASS_5 0x00005000
#define HEAP_CLASS_6 0x00006000
#define HEAP_CLASS_7 0x00007000
#define HEAP_CLASS_8 0x00008000
#define HEAP_CLASS_MASK 0x0000F000
#define HEAP_CREATE_ALIGN_16 0x00010000
#define HEAP_CREATE_ENABLE_EXECUTE 0x00040000
#define HEAP_CREATE_ENABLE_TRACING 0x00020000
#define HEAP_CREATE_VALID_MASK
#define HEAP_DISABLE_COALESCE_ON_FREE 0x00000080
#define HEAP_FREE_CHECKING_ENABLED 0x00000040
#define HEAP_GENERATE_EXCEPTIONS 0x00000004
#define HEAP_GLOBAL_TAG 0x0800
#define HEAP_GROWABLE 0x00000002
#define HEAP_MAKE_TAG_FLAGS(b, o) ((ULONG)((b) + ((o) << 18)))
#define HEAP_MAXIMUM_TAG 0x0FFF
#define HEAP_NO_SERIALIZE 0x00000001
#define HEAP_PSEUDO_TAG_FLAG 0x8000
#define HEAP_REALLOC_IN_PLACE_ONLY 0x00000010
#define HEAP_SETTABLE_USER_FLAG1 0x00000200
#define HEAP_SETTABLE_USER_FLAG2 0x00000400
#define HEAP_SETTABLE_USER_FLAG3 0x00000800
#define HEAP_SETTABLE_USER_FLAGS 0x00000E00
#define HEAP_SETTABLE_USER_VALUE 0x00000100
#define HEAP_TAG_MASK (HEAP_MAXIMUM_TAG << HEAP_TAG_SHIFT)
#define HEAP_TAG_SHIFT 18
#define HEAP_TAIL_CHECKING_ENABLED 0x00000020
#define HEAP_ZERO_MEMORY 0x00000008
#define INIT_PARSE_MESSAGE_CONTEXT(ctx)
#define InitializeListHead32(ListHead)
#define IS_TEXT_UNICODE_ASCII16 0x0001
#define IS_TEXT_UNICODE_CONTROLS 0x0004
#define IS_TEXT_UNICODE_DBCS_LEADBYTE 0x0400
#define IS_TEXT_UNICODE_ILLEGAL_CHARS 0x0100
#define IS_TEXT_UNICODE_NOT_ASCII_MASK 0xF000
#define IS_TEXT_UNICODE_NOT_UNICODE_MASK 0x0F00
#define IS_TEXT_UNICODE_NULL_BYTES 0x1000
#define IS_TEXT_UNICODE_ODD_LENGTH 0x0200
#define IS_TEXT_UNICODE_REVERSE_ASCII16 0x0010
#define IS_TEXT_UNICODE_REVERSE_CONTROLS 0x0040
#define IS_TEXT_UNICODE_REVERSE_MASK 0x00F0
#define IS_TEXT_UNICODE_REVERSE_SIGNATURE 0x0080
#define IS_TEXT_UNICODE_REVERSE_STATISTICS 0x0020
#define IS_TEXT_UNICODE_SIGNATURE 0x0008
#define IS_TEXT_UNICODE_STATISTICS 0x0002
#define IS_TEXT_UNICODE_UNICODE_MASK 0x000F
#define IsEqualGUIDAligned(guid1, guid2) ((*(PLONGLONG)(guid1) == *(PLONGLONG)(guid2)) && (*((PLONGLONG)(guid1) + 1) == *((PLONGLONG)(guid2) + 1)))
#define IsListEmpty(ListHead) ((ListHead)->Flink == (ListHead))
#define KdBreakPoint()
#define KdBreakPointWithStatus(s)
#define KdPrint(_x_)
#define KdPrintEx(_x_)
#define LONG_2ND_MOST_SIGNIFICANT_BIT 2
#define LONG_3RD_MOST_SIGNIFICANT_BIT 1
#define LONG_LEAST_SIGNIFICANT_BIT 0
#define LONG_MASK (LONG_SIZE - 1)
#define LONG_MOST_SIGNIFICANT_BIT 3
#define LONG_SIZE (sizeof(LONG))
#define LONGLONG_MASK (LONGLONG_SIZE - 1)
#define LONGLONG_SIZE (sizeof(LONGLONG))
#define LOWBYTE_MASK 0x00FF
#define MAX_EXCEPTION_LOG 10
#define MAX_EXCEPTION_LOG_DATA_SIZE 5
#define MAX_STACK_DEPTH 32
#define MESSAGE_RESOURCE_UNICODE 0x0001
#define NLS_MB_CODE_PAGE_TAG (*NlsMbCodePageTag)
#define NLS_MB_OEM_CODE_PAGE_TAG (*NlsMbOemCodePageTag)
#define PopEntryList(ListHead)
#define PSLIST_ENTRY PSINGLE_LIST_ENTRY
#define PushEntryList(ListHead, Entry)
#define RTL_ACQUIRE_PRIVILEGE_PROCESS 0x00000002UL
#define RTL_ACQUIRE_PRIVILEGE_REVERT 0x00000001UL
#define RTL_ATOM_INVALID_ATOM (RTL_ATOM)0x0000
#define RTL_ATOM_MAXIMUM_INTEGER_ATOM (RTL_ATOM)0xC000
#define RTL_ATOM_MAXIMUM_NAME_LENGTH 255
#define RTL_ATOM_PINNED 0x01
#define RTL_ATOM_TABLE_DEFAULT_NUMBER_OF_BUCKETS 37
#define RTL_DRIVE_LETTER_VALID (USHORT)0x0001
#define RTL_DUPLICATE_UNICODE_STRING_ALLOCATE_NULL_STRING (0x00000002)
#define RTL_DUPLICATE_UNICODE_STRING_NULL_TERMINATE (0x00000001)
#define RTL_ERRORMODE_FAILCRITICALERRORS (0x0010)
#define RTL_FIND_CHAR_IN_UNICODE_STRING_CASE_INSENSITIVE (0x00000004)
#define RTL_FIND_CHAR_IN_UNICODE_STRING_COMPLEMENT_CHAR_SET (0x00000002)
#define RTL_FIND_CHAR_IN_UNICODE_STRING_START_AT_END (0x00000001)
#define RTL_IMAGE_NT_HEADER_EX_FLAG_NO_RANGE_CHECK (0x00000001)
#define RTL_MAX_DRIVE_LETTERS 32
#define RTL_MEG (1024UL * 1024UL)
#define RTL_QUERY_REGISTRY_DELETE 0x00000040
#define RTL_QUERY_REGISTRY_DIRECT 0x00000020
#define RTL_QUERY_REGISTRY_NOEXPAND 0x00000010
#define RTL_QUERY_REGISTRY_NOVALUE 0x00000008
#define RTL_QUERY_REGISTRY_REQUIRED 0x00000004
#define RTL_QUERY_REGISTRY_SUBKEY 0x00000001
#define RTL_QUERY_REGISTRY_TOPKEY 0x00000002
#define RTL_RANGE_CONFLICT 0x02
#define RTL_RANGE_LIST_ADD_IF_CONFLICT 0x00000001
#define RTL_RANGE_LIST_ADD_SHARED 0x00000002
#define RTL_RANGE_LIST_MERGE_IF_CONFLICT RTL_RANGE_LIST_ADD_IF_CONFLICT
#define RTL_RANGE_LIST_NULL_CONFLICT_OK 0x00000002
#define RTL_RANGE_LIST_SHARED_OK 0x00000001
#define RTL_RANGE_SHARED 0x01
#define RTL_REGISTRY_ABSOLUTE 0
#define RTL_REGISTRY_CONTROL 2
#define RTL_REGISTRY_DEVICEMAP 4
#define RTL_REGISTRY_HANDLE 0x40000000
#define RTL_REGISTRY_MAXIMUM 6
#define RTL_REGISTRY_OPTIONAL 0x80000000
#define RTL_REGISTRY_SERVICES 1
#define RTL_REGISTRY_USER 5
#define RTL_REGISTRY_WINDOWS_NT 3
#define RTL_SOFT_ASSERT(_exp) ((void) 0)
#define RTL_SOFT_ASSERTMSG(_msg, _exp) ((void) 0)
#define RTL_SOFT_VERIFY(_exp) ((_exp) ? TRUE : FALSE)
#define RTL_SOFT_VERIFYMSG(msg, _exp) ((_exp) ? TRUE : FALSE)
#define RTL_SYSTEM_VOLUME_INFORMATION_FOLDER L"System Volume Information"
#define RTL_TRACE_IN_KERNEL_MODE 0x00000002
#define RTL_TRACE_IN_USER_MODE 0x00000001
#define RTL_TRACE_USE_NONPAGED_POOL 0x00000004
#define RTL_TRACE_USE_PAGED_POOL 0x00000008
#define RTL_USER_PROC_APP_MANIFEST_PRESENT 0x00002000
#define RTL_USER_PROC_CASE_SENSITIVE 0x00000080
#define RTL_USER_PROC_CURDIR_CLOSE 0x00000002
#define RTL_USER_PROC_CURDIR_INHERIT 0x00000003
#define RTL_USER_PROC_DISABLE_HEAP_DECOMMIT 0x00000100
#define RTL_USER_PROC_DLL_REDIRECTION_LOCAL 0x00001000
#define RTL_USER_PROC_IMAGE_KEY_MISSING 0x00004000
#define RTL_USER_PROC_OPTIN_PROCESS 0x00020000
#define RTL_USER_PROC_PARAMS_NORMALIZED 0x00000001
#define RTL_USER_PROC_PROFILE_KERNEL 0x00000004
#define RTL_USER_PROC_PROFILE_SERVER 0x00000008
#define RTL_USER_PROC_PROFILE_USER 0x00000002
#define RTL_USER_PROC_RESERVE_16MB 0x00000040
#define RTL_USER_PROC_RESERVE_1MB 0x00000020
#define RTL_VERIFY(exp) ((exp) ? TRUE : FALSE)
#define RTL_VERIFYMSG(msg, exp) ((exp) ? TRUE : FALSE)
#define RtlAnsiStringToUnicodeSize(STRING)
#define RtlApplyAceToObject(Ace, Mapping)
#define RtlApplyGenericMask(Ace, Mask, Mapping)
#define RtlCheckBit(BMH, BP) ((((BMH)->Buffer[(BP) / 32]) >> ((BP) % 32)) & 0x1)
#define RtlCompoundAceClientSid(Ace) ((PSID)(((ULONG_PTR)(&((PKNOWN_COMPOUND_ACE)(Ace))->SidStart))+RtlLengthSid(RtlCompoundAceServerSid((Ace)))))
#define RtlCompoundAceServerSid(Ace) ((PSID)&((PKNOWN_COMPOUND_ACE)(Ace))->SidStart)
#define RtlCopyBytes RtlCopyMemory
#define RtlCopyMemory(Destination, Source, Length) memcpy((Destination),(Source),(Length))
#define RtlCopyMemoryNonTemporal RtlCopyMemory
#define RtlEqualLuid(L1, L2)
#define RtlEqualMemory(Destination, Source, Length) (!memcmp((Destination),(Source),(Length)))
#define RtlFillBytes RtlFillMemory
#define RtlFillMemory(Destination, Length, Fill) memset((Destination),(Fill),(Length))
#define RtlImageDirectoryEntryToData32 RtlImageDirectoryEntryToData
#define RtlInitEmptyUnicodeString(_ucStr, _buf, _bufSize)
#define RtlInitializeSplayLinks(Links)
#define RtlInsertAsLeftChild(ParentLinks, ChildLinks)
#define RtlInsertAsRightChild(ParentLinks, ChildLinks)
#define RtlInterlockedAndBits(Flags, Flag) InterlockedAnd((PLONG)(Flags), Flag)
#define RtlInterlockedAndBitsDiscardReturn(Flags, Flag) (VOID) RtlInterlockedAndBits(Flags, Flag)
#define RtlInterlockedClearBits(Flags, Flag) RtlInterlockedAndBits(Flags, ~(Flag))
#define RtlInterlockedClearBitsDiscardReturn(Flags, Flag) RtlInterlockedAndBitsDiscardReturn(Flags, ~(Flag))
#define RtlInterlockedSetBits(Flags, Flag) InterlockedOr((PLONG)(Flags), Flag)
#define RtlInterlockedSetBitsDiscardReturn(Flags, Flag) (VOID) RtlInterlockedSetBits(Flags, Flag)
#define RtlInterlockedXorBits(Flags, Flag) InterlockedXor(Flags, Flag)
#define RtlIntPtrToUnicodeString(Value, Base, String) RtlIntegerToUnicodeString(Value, Base, String)
#define RtlIpv4AddressToString RtlIpv4AddressToStringA
#define RtlIpv4AddressToStringEx RtlIpv4AddressToStringExA
#define RtlIpv4StringToAddress RtlIpv4StringToAddressA
#define RtlIpv4StringToAddressEx RtlIpv4StringToAddressExA
#define RtlIpv6AddressToString RtlIpv6AddressToStringA
#define RtlIpv6AddressToStringEx RtlIpv6AddressToStringExA
#define RtlIpv6StringToAddress RtlIpv6StringToAddressA
#define RtlIpv6StringToAddressEx RtlIpv6StringToAddressExA
#define RtlIsImpersonating() (NtCurrentTeb()->IsImpersonating ? TRUE : FALSE)
#define RtlIsLeftChild(Links)
#define RtlIsRightChild(Links)
#define RtlIsRoot(Links)
#define RtlIsZeroLuid(L1) ((BOOLEAN) (((L1)->LowPart | (L1)->HighPart) == 0))
#define RtlLargeIntegerAnd(Result, Source, Mask) Result.QuadPart = Source.QuadPart & Mask.QuadPart
#define RtlLargeIntegerEqualTo(X, Y)
#define RtlLargeIntegerEqualToZero(X)
#define RtlLargeIntegerGreaterOrEqualToZero(X)
#define RtlLargeIntegerGreaterThan(X, Y)
#define RtlLargeIntegerGreaterThanOrEqualTo(X, Y)
#define RtlLargeIntegerGreaterThanZero(X)
#define RtlLargeIntegerLessOrEqualToZero(X)
#define RtlLargeIntegerLessThan(X, Y)
#define RtlLargeIntegerLessThanOrEqualTo(X, Y)
#define RtlLargeIntegerLessThanZero(X)
#define RtlLargeIntegerNotEqualTo(X, Y)
#define RtlLargeIntegerNotEqualToZero(X)
#define RtlLeftChild(Links)
#define RtlMoveMemory(Destination, Source, Length) memmove((Destination),(Source),(Length))
#define RtlOemStringToCountedUnicodeSize(STRING)
#define RtlOemStringToUnicodeSize(STRING)
#define RtlOffsetToPointer(B, O) ((PCHAR)(((PCHAR)(B)) + ((ULONG_PTR)(O))))
#define RTLP_ADD_WITH_CARRY_OUT(FunctionName, Type, BaseFunction, BaseType)
#define RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32(FunctionName, Type) RTLP_ADD_WITH_CARRY_OUT(FunctionName, Type, RtlUnsignedAddWithCarryOut32, unsigned __int32)
#define RTLP_ADD_WITH_CARRY_OUT_UNSIGNED64(FunctionName, Type) RTLP_ADD_WITH_CARRY_OUT(FunctionName, Type, RtlUnsignedAddWithCarryOut64, unsigned __int64)
#define RTLP_ADD_WITH_CARRY_OUT_UNSIGNED_PTR(FunctionName, Type) RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32(FunctionName, Type)
#define RTLP_ADD_WITH_OVERFLOW_OUT RTLP_ADD_WITH_CARRY_OUT
#define RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED32(FunctionName, Type) RTLP_ADD_WITH_OVERFLOW_OUT(FunctionName, Type, RtlSignedAddWithOverflowOut32, __int32)
#define RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED64(FunctionName, Type) RTLP_ADD_WITH_OVERFLOW_OUT(FunctionName, Type, RtlSignedAddWithOverflowOut64, __int64)
#define RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED_PTR(FunctionName, Type) RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED32(FunctionName, Type)
#define RTLP_IMAGE_MAX_DOS_HEADER (256UL * RTL_MEG)
#define RtlParent(Links)
#define RtlPointerToOffset(B, P) ((ULONG)(((PCHAR)(P)) - ((PCHAR)(B))))
#define RtlRetrieveUlong(DEST_ADDRESS, SRC_ADDRESS)
#define RtlRetrieveUshort(DEST_ADDRESS, SRC_ADDRESS)
#define RtlRightChild(Links)
#define RtlStoreUlong(ADDRESS, VALUE)
#define RtlStoreUlonglong(ADDRESS, VALUE)
#define RtlStoreUlongPtr(ADDRESS, VALUE) RtlStoreUlong(ADDRESS,VALUE)
#define RtlStoreUshort(ADDRESS, VALUE)
#define RtlUnicodeStringToAnsiSize(STRING)
#define RtlUnicodeStringToCountedOemSize(STRING)
#define RtlUnicodeStringToOemSize(STRING)
#define RtlZeroBytes RtlZeroMemory
#define RtlZeroMemory(Destination, Length) memset((Destination),0,(Length))
#define SECONDBYTE(VALUE) (((VALUE) >> 8) & LOWBYTE_MASK)
#define SET_PARSE_MESSAGE_CONTEXT_FLAG(ctx, flag) ((ctx)->fFlags |= (flag))
#define SHORT_LEAST_SIGNIFICANT_BIT 0
#define SHORT_MASK (SHORT_SIZE - 1)
#define SHORT_MOST_SIGNIFICANT_BIT 1
#define SHORT_SIZE (sizeof(USHORT))
#define SLIST_ENTRY SINGLE_LIST_ENTRY
#define STATICGUIDOF(guid) STATIC_##guid
#define TEST_PARSE_MESSAGE_CONTEXT_FLAG(ctx, flag) ((ctx)->fFlags & (flag))
#define THIRDBYTE(VALUE) (((VALUE) >> 16) & LOWBYTE_MASK)
#define VER_AND 6
#define VER_BUILDNUMBER 0x0000004
#define VER_CONDITION_MASK 7
#define VER_EQUAL 1
#define VER_GREATER 2
#define VER_GREATER_EQUAL 3
#define VER_LESS 4
#define VER_LESS_EQUAL 5
#define VER_MAJORVERSION 0x0000002
#define VER_MINORVERSION 0x0000001
#define VER_NT_DOMAIN_CONTROLLER 0x0000002
#define VER_NT_SERVER 0x0000003
#define VER_NT_WORKSTATION 0x0000001
#define VER_NUM_BITS_PER_CONDITION_MASK 3
#define VER_OR 7
#define VER_PLATFORM_WIN32_NT 2
#define VER_PLATFORM_WIN32_WINDOWS 1
#define VER_PLATFORM_WIN32s 0
#define VER_PLATFORMID 0x0000008
#define VER_PRODUCT_TYPE 0x0000080
#define VER_SERVICEPACKMAJOR 0x0000020
#define VER_SERVICEPACKMINOR 0x0000010
#define VER_SET_CONDITION(_m_, _t_, _c_) ((_m_)=VerSetConditionMask((_m_),(_t_),(_c_)))
#define VER_SUITENAME 0x0000040
#define vKdPrintEx(_x_)
#define vKdPrintExWithPrefix(_x_)
Typedefs
typedef PVOID Buffer
typedef CLONG ByteSize
typedef struct _COMPRESSED_DATA_INFO COMPRESSED_DATA_INFO
typedef struct _CURDIR CURDIR
typedef struct _CURDIR64 CURDIR64
typedef enum _DPFLTR_TYPE DPFLTR_TYPE
typedef PVOID FirstStruct
typedef struct _GENERATE_NAME_CONTEXT GENERATE_NAME_CONTEXT
typedef struct _LAST_EXCEPTION_LOG LAST_EXCEPTION_LOG
typedef LPOSVERSIONINFOA LPOSVERSIONINFO
typedef struct _OSVERSIONINFOA * LPOSVERSIONINFOA
typedef LPOSVERSIONINFOEXA LPOSVERSIONINFOEX
typedef struct _OSVERSIONINFOEXA * LPOSVERSIONINFOEXA
typedef struct _OSVERSIONINFOEXW * LPOSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW * LPOSVERSIONINFOW
typedef PVOID PVOID MatchData
typedef struct _MESSAGE_RESOURCE_BLOCK MESSAGE_RESOURCE_BLOCK
typedef struct _MESSAGE_RESOURCE_DATA MESSAGE_RESOURCE_DATA
typedef struct _MESSAGE_RESOURCE_ENTRY MESSAGE_RESOURCE_ENTRY
typedef OSVERSIONINFOA OSVERSIONINFO
typedef struct _OSVERSIONINFOA OSVERSIONINFOA
typedef OSVERSIONINFOEXA OSVERSIONINFOEX
typedef struct _OSVERSIONINFOEXA OSVERSIONINFOEXA
typedef struct _OSVERSIONINFOEXW OSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW OSVERSIONINFOW
typedef struct _PARSE_MESSAGE_CONTEXT PARSE_MESSAGE_CONTEXT
typedef COMPRESSED_DATA_INFO * PCOMPRESSED_DATA_INFO
typedef struct _CURDIR * PCURDIR
typedef struct _CURDIR64 * PCURDIR64
typedef GENERATE_NAME_CONTEXT * PGENERATE_NAME_CONTEXT
typedef struct _LAST_EXCEPTION_LOG * PLAST_EXCEPTION_LOG
typedef struct _MESSAGE_RESOURCE_BLOCK * PMESSAGE_RESOURCE_BLOCK
typedef struct _MESSAGE_RESOURCE_DATA * PMESSAGE_RESOURCE_DATA
typedef struct _MESSAGE_RESOURCE_ENTRY * PMESSAGE_RESOURCE_ENTRY
typedef POSVERSIONINFOA POSVERSIONINFO
typedef struct _OSVERSIONINFOA * POSVERSIONINFOA
typedef POSVERSIONINFOEXA POSVERSIONINFOEX
typedef struct _OSVERSIONINFOEXA * POSVERSIONINFOEXA
typedef struct _OSVERSIONINFOEXW * POSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW * POSVERSIONINFOW
typedef struct _PARSE_MESSAGE_CONTEXT * PPARSE_MESSAGE_CONTEXT
typedef PREFIX_TABLE * PPREFIX_TABLE
typedef PREFIX_TABLE_ENTRY * PPREFIX_TABLE_ENTRY
typedef struct _PREFIX_TABLE PREFIX_TABLE
typedef struct _PREFIX_TABLE_ENTRY PREFIX_TABLE_ENTRY
typedef RTL_AVL_TABLE * PRTL_AVL_TABLE
typedef RTL_BALANCED_LINKS * PRTL_BALANCED_LINKS
typedef RTL_BITMAP * PRTL_BITMAP
typedef RTL_BITMAP_RUN * PRTL_BITMAP_RUN
typedef enum RTL_BSD_ITEM_TYPE * PRTL_BSD_ITEM_TYPE
typedef BOOLEAN(* PRTL_CONFLICT_RANGE_CALLBACK) (IN PVOID Context, IN PRTL_RANGE Range)
typedef struct _RTL_DRIVE_LETTER_CURDIR * PRTL_DRIVE_LETTER_CURDIR
typedef struct _RTL_DRIVE_LETTER_CURDIR64 * PRTL_DRIVE_LETTER_CURDIR64
typedef RTL_GENERIC_TABLE * PRTL_GENERIC_TABLE
typedef NTSTATUS(NTAPI * PRTL_HEAP_COMMIT_ROUTINE) (IN PVOID Base, IN OUT PVOID *CommitAddress, IN OUT PSIZE_T CommitSize)
typedef struct _RTL_HEAP_PARAMETERS * PRTL_HEAP_PARAMETERS
typedef struct _OSVERSIONINFOEXW * PRTL_OSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW * PRTL_OSVERSIONINFOW
typedef struct _RTL_PROCESS_BACKTRACE_INFORMATION * PRTL_PROCESS_BACKTRACE_INFORMATION
typedef struct _RTL_PROCESS_BACKTRACES * PRTL_PROCESS_BACKTRACES
typedef struct _RTL_PROCESS_LOCK_INFORMATION * PRTL_PROCESS_LOCK_INFORMATION
typedef struct _RTL_PROCESS_LOCKS * PRTL_PROCESS_LOCKS
typedef NTSTATUS(NTAPI * PRTL_QUERY_REGISTRY_ROUTINE) (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
typedef struct _RTL_QUERY_REGISTRY_TABLE * PRTL_QUERY_REGISTRY_TABLE
typedef struct _RTL_RANGE * PRTL_RANGE
typedef struct _RTL_RANGE_LIST * PRTL_RANGE_LIST
typedef struct _RANGE_LIST_ITERATOR * PRTL_RANGE_LIST_ITERATOR
typedef struct _RTL_RXACT_CONTEXT * PRTL_RXACT_CONTEXT
typedef struct _RTL_RXACT_LOG * PRTL_RXACT_LOG
typedef enum _RTL_RXACT_OPERATION * PRTL_RXACT_OPERATION
typedef NTSTATUS(* PRTL_SECURE_MEMORY_CACHE_CALLBACK) (IN PVOID Addr, IN SIZE_T Range)
typedef RTL_SPLAY_LINKS * PRTL_SPLAY_LINKS
typedef struct _RTL_STACK_CONTEXT * PRTL_STACK_CONTEXT
typedef struct _RTL_STACK_CONTEXT_ENTRY * PRTL_STACK_CONTEXT_ENTRY
typedef struct _RTL_TIME_ZONE_INFORMATION * PRTL_TIME_ZONE_INFORMATION
typedef struct _RTL_TRACE_BLOCK * PRTL_TRACE_BLOCK
typedef struct _RTL_TRACE_DATABASE * PRTL_TRACE_DATABASE
typedef struct _RTL_TRACE_ENUMERATE * PRTL_TRACE_ENUMERATE
typedef struct _RTL_USER_PROCESS_INFORMATION * PRTL_USER_PROCESS_INFORMATION
typedef struct _RTL_USER_PROCESS_INFORMATION64 * PRTL_USER_PROCESS_INFORMATION64
typedef struct _RTL_USER_PROCESS_PARAMETERS * PRTL_USER_PROCESS_PARAMETERS
typedef struct _RTL_USER_PROCESS_PARAMETERS64 * PRTL_USER_PROCESS_PARAMETERS64
typedef union _SLIST_HEADER * PSLIST_HEADER
typedef TIME_FIELDS * PTIME_FIELDS
typedef UNICODE_PREFIX_TABLE * PUNICODE_PREFIX_TABLE
typedef UNICODE_PREFIX_TABLE_ENTRY * PUNICODE_PREFIX_TABLE_ENTRY
typedef NTSTATUS(* PUSER_PROCESS_START_ROUTINE) (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
typedef NTSTATUS(* PUSER_THREAD_START_ROUTINE) (PVOID ThreadParameter)
typedef struct _RTL_AVL_TABLE RTL_AVL_TABLE
typedef struct _RTL_BALANCED_LINKS RTL_BALANCED_LINKS
typedef struct _RTL_BITMAP RTL_BITMAP
typedef struct _RTL_BITMAP_RUN RTL_BITMAP_RUN
typedef struct _RTL_DRIVE_LETTER_CURDIR RTL_DRIVE_LETTER_CURDIR
typedef struct _RTL_DRIVE_LETTER_CURDIR64 RTL_DRIVE_LETTER_CURDIR64
typedef enum _RTL_GENERIC_COMPARE_RESULTS RTL_GENERIC_COMPARE_RESULTS
typedef struct _RTL_GENERIC_TABLE RTL_GENERIC_TABLE
typedef struct _RTL_HEAP_PARAMETERS RTL_HEAP_PARAMETERS
typedef struct _OSVERSIONINFOEXW RTL_OSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW RTL_OSVERSIONINFOW
typedef struct _RTL_PROCESS_BACKTRACE_INFORMATION RTL_PROCESS_BACKTRACE_INFORMATION
typedef struct _RTL_PROCESS_BACKTRACES RTL_PROCESS_BACKTRACES
typedef struct _RTL_PROCESS_LOCK_INFORMATION RTL_PROCESS_LOCK_INFORMATION
typedef struct _RTL_PROCESS_LOCKS RTL_PROCESS_LOCKS
typedef struct _RTL_QUERY_REGISTRY_TABLE RTL_QUERY_REGISTRY_TABLE
typedef struct _RTL_RANGE RTL_RANGE
typedef struct _RTL_RANGE_LIST RTL_RANGE_LIST
typedef struct _RANGE_LIST_ITERATOR RTL_RANGE_LIST_ITERATOR
typedef struct _RTL_RXACT_CONTEXT RTL_RXACT_CONTEXT
typedef struct _RTL_RXACT_LOG RTL_RXACT_LOG
typedef enum _RTL_RXACT_OPERATION RTL_RXACT_OPERATION
typedef struct _RTL_SPLAY_LINKS RTL_SPLAY_LINKS
typedef struct _RTL_STACK_CONTEXT RTL_STACK_CONTEXT
typedef struct _RTL_STACK_CONTEXT_ENTRY RTL_STACK_CONTEXT_ENTRY
typedef struct _RTL_TIME_ZONE_INFORMATION RTL_TIME_ZONE_INFORMATION
typedef struct _RTL_TRACE_BLOCK RTL_TRACE_BLOCK
typedef struct _RTL_TRACE_ENUMERATE RTL_TRACE_ENUMERATE
typedef ULONG(* RTL_TRACE_HASH_FUNCTION) (ULONG Count, PVOID *Trace)
typedef struct _RTL_USER_PROCESS_INFORMATION RTL_USER_PROCESS_INFORMATION
typedef struct _RTL_USER_PROCESS_INFORMATION64 RTL_USER_PROCESS_INFORMATION64
typedef struct _RTL_USER_PROCESS_PARAMETERS RTL_USER_PROCESS_PARAMETERS
typedef struct _RTL_USER_PROCESS_PARAMETERS64 RTL_USER_PROCESS_PARAMETERS64
typedef PVOID PVOID SecondStruct
typedef union _SLIST_HEADER SLIST_HEADER
typedef enum _TABLE_SEARCH_RESULT TABLE_SEARCH_RESULT
typedef struct _TIME_FIELDS TIME_FIELDS
typedef struct _UNICODE_PREFIX_TABLE UNICODE_PREFIX_TABLE
typedef struct _UNICODE_PREFIX_TABLE_ENTRY UNICODE_PREFIX_TABLE_ENTRY
typedef PVOID UserData
Enumerations
enum _DPFLTR_TYPE {
DPFLTR_SYSTEM_ID = 0, DPFLTR_SMSS_ID = 1, DPFLTR_SETUP_ID = 2, DPFLTR_NTFS_ID = 3,
DPFLTR_FSTUB_ID = 4, DPFLTR_CRASHDUMP_ID = 5, DPFLTR_CDAUDIO_ID = 6, DPFLTR_CDROM_ID = 7,
DPFLTR_CLASSPNP_ID = 8, DPFLTR_DISK_ID = 9, DPFLTR_REDBOOK_ID = 10, DPFLTR_STORPROP_ID = 11,
DPFLTR_SCSIPORT_ID = 12, DPFLTR_SCSIMINIPORT_ID = 13, DPFLTR_CONFIG_ID = 14, DPFLTR_I8042PRT_ID = 15,
DPFLTR_SERMOUSE_ID = 16, DPFLTR_LSERMOUS_ID = 17, DPFLTR_KBDHID_ID = 18, DPFLTR_MOUHID_ID = 19,
DPFLTR_KBDCLASS_ID = 20, DPFLTR_MOUCLASS_ID = 21, DPFLTR_TWOTRACK_ID = 22, DPFLTR_WMILIB_ID = 23,
DPFLTR_ACPI_ID = 24, DPFLTR_AMLI_ID = 25, DPFLTR_HALIA64_ID = 26, DPFLTR_VIDEO_ID = 27,
DPFLTR_SVCHOST_ID = 28, DPFLTR_VIDEOPRT_ID = 29, DPFLTR_TCPIP_ID = 30, DPFLTR_DMSYNTH_ID = 31,
DPFLTR_NTOSPNP_ID = 32, DPFLTR_FASTFAT_ID = 33, DPFLTR_SAMSS_ID = 34, DPFLTR_PNPMGR_ID = 35,
DPFLTR_NETAPI_ID = 36, DPFLTR_SCSERVER_ID = 37, DPFLTR_SCCLIENT_ID = 38, DPFLTR_SERIAL_ID = 39,
DPFLTR_SERENUM_ID = 40, DPFLTR_UHCD_ID = 41, DPFLTR_RPCPROXY_ID = 42, DPFLTR_AUTOCHK_ID = 43,
DPFLTR_DCOMSS_ID = 44, DPFLTR_UNIMODEM_ID = 45, DPFLTR_SIS_ID = 46, DPFLTR_FLTMGR_ID = 47,
DPFLTR_WMICORE_ID = 48, DPFLTR_BURNENG_ID = 49, DPFLTR_IMAPI_ID = 50, DPFLTR_SXS_ID = 51,
DPFLTR_FUSION_ID = 52, DPFLTR_IDLETASK_ID = 53, DPFLTR_SOFTPCI_ID = 54, DPFLTR_TAPE_ID = 55,
DPFLTR_MCHGR_ID = 56, DPFLTR_IDEP_ID = 57, DPFLTR_PCIIDE_ID = 58, DPFLTR_FLOPPY_ID = 59,
DPFLTR_FDC_ID = 60, DPFLTR_TERMSRV_ID = 61, DPFLTR_W32TIME_ID = 62, DPFLTR_PREFETCHER_ID = 63,
DPFLTR_RSFILTER_ID = 64, DPFLTR_FCPORT_ID = 65, DPFLTR_PCI_ID = 66, DPFLTR_DMIO_ID = 67,
DPFLTR_DMCONFIG_ID = 68, DPFLTR_DMADMIN_ID = 69, DPFLTR_WSOCKTRANSPORT_ID = 70, DPFLTR_VSS_ID = 71,
DPFLTR_PNPMEM_ID = 72, DPFLTR_PROCESSOR_ID = 73, DPFLTR_DMSERVER_ID = 74, DPFLTR_SR_ID = 75,
DPFLTR_INFINIBAND_ID = 76, DPFLTR_IHVDRIVER_ID = 77, DPFLTR_IHVVIDEO_ID = 78, DPFLTR_IHVAUDIO_ID = 79,
DPFLTR_IHVNETWORK_ID = 80, DPFLTR_IHVSTREAMING_ID = 81, DPFLTR_IHVBUS_ID = 82, DPFLTR_HPS_ID = 83,
DPFLTR_RTLTHREADPOOL_ID = 84, DPFLTR_LDR_ID = 85, DPFLTR_TCPIP6_ID = 86, DPFLTR_ISAPNP_ID = 87,
DPFLTR_SHPC_ID = 88, DPFLTR_STORPORT_ID = 89, DPFLTR_STORMINIPORT_ID = 90, DPFLTR_PRINTSPOOLER_ID = 91,
DPFLTR_VSSDYNDISK_ID = 92, DPFLTR_VERIFIER_ID = 93, DPFLTR_VDS_ID = 94, DPFLTR_VDSBAS_ID = 95,
DPFLTR_VDSDYNDR_ID = 96, DPFLTR_VDSUTIL_ID = 97, DPFLTR_DFRGIFC_ID = 98, DPFLTR_DEFAULT_ID = 99,
DPFLTR_MM_ID = 100, DPFLTR_DFSC_ID = 101, DPFLTR_WOW64_ID = 102, DPFLTR_ENDOFTABLE_ID
}
enum _RTL_GENERIC_COMPARE_RESULTS { GenericLessThan, GenericGreaterThan, GenericEqual }
enum _RTL_RXACT_OPERATION { RtlRXactOperationDelete = 1, RtlRXactOperationSetValue, RtlRXactOperationDelAttribute, RtlRXactOperationSetAttribute }
enum _TABLE_SEARCH_RESULT { TableEmptyTree, TableFoundNode, TableInsertAsLeft, TableInsertAsRight }
enum RTL_BSD_ITEM_TYPE {
RtlBsdItemVersionNumber = 0x00, RtlBsdItemProductType, RtlBsdItemAabEnabled, RtlBsdItemAabTimeout,
RtlBsdItemBootGood, RtlBsdItemBootShutdown, RtlBsdItemMax
}
Functions
typedef BOOLEAN (NTAPI *PRTL_OKAY_TO_LOCK_ROUTINE)(IN PVOID Lock)
VOID NTAPI DbgBreakPoint (VOID)
NTSYSAPI VOID NTAPI DbgBreakPointWithStatus (IN ULONG Status)
NTSYSAPI VOID NTAPI DbgCommandString (__in PCH Name, __in PCH Command)
NTSYSAPI VOID NTAPI DbgLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
ULONG __cdecl DbgPrint (__in PCH Format,...)
NTSYSAPI ULONG __cdecl DbgPrintEx (__in ULONG ComponentId, __in ULONG Level, __in PCH Format,...)
NTSYSAPI ULONG __cdecl DbgPrintReturnControlC (__in PCHAR Format,...)
NTSYSAPI ULONG NTAPI DbgPrompt (__in PCH Prompt, __out_bcount(Length) PCH Response, __in ULONG Length)
NTSYSAPI NTSTATUS NTAPI DbgQueryDebugFilterState (__in ULONG ComponentId, __in ULONG Level)
NTSYSAPI NTSTATUS NTAPI DbgSetDebugFilterState (__in ULONG ComponentId, __in ULONG Level, __in BOOLEAN State)
NTSYSAPI VOID NTAPI DbgUnLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
NTSYSAPI VOID NTAPI DbgUserBreakPoint (VOID)
VOID NTAPI DebugService2 (PVOID Arg1, PVOID Arg2, ULONG Service)
VOID FORCEINLINE InitializeListHead (IN PLIST_ENTRY ListHead)
VOID FORCEINLINE InsertHeadList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY Entry)
VOID FORCEINLINE InsertTailList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY Entry)
typedef NTSTATUS (NTAPI *PRTL_AVL_MATCH_FUNCTION)(struct _RTL_AVL_TABLE *Table
NTSYSAPI PPREFIX_TABLE_ENTRY NTAPI PfxFindPrefix (PPREFIX_TABLE PrefixTable, PSTRING FullName)
NTSYSAPI VOID NTAPI PfxInitialize (PPREFIX_TABLE PrefixTable)
NTSYSAPI BOOLEAN NTAPI PfxInsertPrefix (PPREFIX_TABLE PrefixTable, PSTRING Prefix, PPREFIX_TABLE_ENTRY PrefixTableEntry)
NTSYSAPI VOID NTAPI PfxRemovePrefix (PPREFIX_TABLE PrefixTable, PPREFIX_TABLE_ENTRY PrefixTableEntry)
typedef PVOID (NTAPI *PRTL_AVL_ALLOCATE_ROUTINE)(struct _RTL_AVL_TABLE *Table
BOOLEAN FORCEINLINE RemoveEntryList (IN PLIST_ENTRY Entry)
PLIST_ENTRY FORCEINLINE RemoveHeadList (IN PLIST_ENTRY ListHead)
PLIST_ENTRY FORCEINLINE RemoveTailList (IN PLIST_ENTRY ListHead)
typedef RTL_GENERIC_COMPARE_RESULTS (NTAPI *PRTL_AVL_COMPARE_ROUTINE)(struct _RTL_AVL_TABLE *Table
NTSYSAPI NTSTATUS NTAPI RtlAbortRXact (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlAbsoluteToSelfRelativeSD (__in PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __out_bcount(*BufferLength) PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
NTSYSAPI VOID NTAPI RtlAcquirePebLock (VOID)
NTSYSAPI NTSTATUS NTAPI RtlAcquirePrivilege (PULONG Privilege, ULONG NumPriv, ULONG Flags, PVOID *ReturnedState)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessAllowedAce (PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessAllowedAceEx (PACL Acl, ULONG AceRevision, ULONG AceFlags, ACCESS_MASK AccessMask, PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessAllowedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessDeniedAce (PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessDeniedAceEx (PACL Acl, ULONG AceRevision, ULONG AceFlags, ACCESS_MASK AccessMask, PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessDeniedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAce (PACL Acl, ULONG AceRevision, ULONG StartingAceIndex, PVOID AceList, ULONG AceListLength)
NTSYSAPI NTSTATUS NTAPI RtlAddActionToRXact (IN PRTL_RXACT_CONTEXT RXactContext, IN RTL_RXACT_OPERATION Operation, IN PUNICODE_STRING SubKeyName, IN ULONG NewKeyValueType, IN PVOID NewKeyValue OPTIONAL, IN ULONG NewKeyValueLength)
NTSYSAPI NTSTATUS NTAPI RtlAddAtomToAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __inout_opt PRTL_ATOM Atom)
NTSYSAPI NTSTATUS NTAPI RtlAddAttributeActionToRXact (IN PRTL_RXACT_CONTEXT RXactContext, IN RTL_RXACT_OPERATION Operation, IN PUNICODE_STRING SubKeyName, IN HANDLE KeyHandle, IN PUNICODE_STRING AttributeName, IN ULONG NewValueType, IN PVOID NewValue, IN ULONG NewValueLength)
NTSYSAPI NTSTATUS NTAPI RtlAddAuditAccessAce (PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid, BOOLEAN AuditSuccess, BOOLEAN AuditFailure)
NTSYSAPI NTSTATUS NTAPI RtlAddAuditAccessAceEx (PACL Acl, ULONG AceRevision, ULONG AceFlags, ACCESS_MASK AccessMask, PSID Sid, BOOLEAN AuditSuccess, BOOLEAN AuditFailure)
NTSYSAPI NTSTATUS NTAPI RtlAddAuditAccessObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid, BOOLEAN AuditSuccess, BOOLEAN AuditFailure)
NTSYSAPI NTSTATUS NTAPI RtlAddCompoundAce (IN PACL Acl, IN ULONG AceRevision, IN UCHAR AceType, IN ACCESS_MASK AccessMask, IN PSID ServerSid, IN PSID ClientSid)
NTSYSAPI NTSTATUS NTAPI RtlAddRange (IN OUT PRTL_RANGE_LIST RangeList, IN ULONGLONG Start, IN ULONGLONG End, IN UCHAR Attributes, IN ULONG Flags, IN PVOID UserData, OPTIONAL IN PVOID Owner OPTIONAL)
NTSYSAPI PVOID NTAPI RtlAddressInSectionTable (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID BaseOfImage, IN ULONG VirtualAddress)
NTSYSAPI NTSTATUS NTAPI RtlAdjustPrivilege (ULONG Privilege, BOOLEAN Enable, BOOLEAN Client, PBOOLEAN WasEnabled)
NTSYSAPI NTSTATUS NTAPI RtlAllocateAndInitializeSid (IN PSID_IDENTIFIER_AUTHORITY IdentifierAuthority, IN UCHAR SubAuthorityCount, IN ULONG SubAuthority0, IN ULONG SubAuthority1, IN ULONG SubAuthority2, IN ULONG SubAuthority3, IN ULONG SubAuthority4, IN ULONG SubAuthority5, IN ULONG SubAuthority6, IN ULONG SubAuthority7, OUT PSID *Sid)
NTSYSAPI NTSTATUS NTAPI RtlAllocateFromPeb (ULONG Size, PVOID *Block)
NTSYSAPI PVOID NTAPI RtlAllocateHeap (IN PVOID HeapHandle, IN ULONG Flags, IN SIZE_T Size)
NTSYSAPI WCHAR NTAPI RtlAnsiCharToUnicodeChar (PUCHAR *SourceCharacter)
NTSYSAPI NTSTATUS NTAPI RtlAnsiStringToUnicodeString (PUNICODE_STRING DestinationString, PCANSI_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlAppendAsciizToString (PSTRING Destination, PCSZ Source)
NTSYSAPI NTSTATUS NTAPI RtlAppendStringToString (PSTRING Destination, const STRING *Source)
NTSYSAPI NTSTATUS NTAPI RtlAppendUnicodeStringToString (PUNICODE_STRING Destination, PCUNICODE_STRING Source)
NTSYSAPI NTSTATUS NTAPI RtlAppendUnicodeToString (PUNICODE_STRING Destination, PCWSTR Source)
NTSYSAPI NTSTATUS NTAPI RtlApplyRXact (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlApplyRXactNoFlush (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI BOOLEAN NTAPI RtlAreAllAccessesGranted (ACCESS_MASK GrantedAccess, ACCESS_MASK DesiredAccess)
NTSYSAPI BOOLEAN NTAPI RtlAreAnyAccessesGranted (ACCESS_MASK GrantedAccess, ACCESS_MASK DesiredAccess)
NTSYSAPI BOOLEAN NTAPI RtlAreBitsClear (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG Length)
NTSYSAPI BOOLEAN NTAPI RtlAreBitsSet (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG Length)
NTSYSAPI VOID NTAPI RtlAssert (__in PVOID VoidFailedAssertion, __in PVOID VoidFileName, __in ULONG LineNumber, __in_opt PSTR MutableMessage)
VOID RtlBackoff (IN PRTL_BACKOFF Backoff)
NTSYSAPI VOID NTAPI RtlCaptureContext (OUT PCONTEXT ContextRecord)
NTSYSAPI USHORT NTAPI RtlCaptureStackBackTrace (IN ULONG FramesToSkip, IN ULONG FramesToCapture, OUT PVOID *BackTrace, OUT PULONG BackTraceHash OPTIONAL)
NTSYSAPI ULONG NTAPI RtlCaptureStackContext (OUT PULONG_PTR Callers, OUT PRTL_STACK_CONTEXT Context, IN ULONG Limit)
NTSYSAPI NTSTATUS NTAPI RtlCharToInteger (PCSZ String, ULONG Base, PULONG Value)
NTSYSAPI NTSTATUS NTAPI RtlCheckRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
NTSYSAPI VOID NTAPI RtlClearAllBits (PRTL_BITMAP BitMapHeader)
NTSYSAPI VOID NTAPI RtlClearBit (PRTL_BITMAP BitMapHeader, ULONG BitNumber)
NTSYSAPI VOID NTAPI RtlClearBits (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG NumberToClear)
NTSYSAPI SIZE_T NTAPI RtlCompareMemory (const VOID *Source1, const VOID *Source2, SIZE_T Length)
NTSYSAPI SIZE_T NTAPI RtlCompareMemoryUlong (PVOID Source, SIZE_T Length, ULONG Pattern)
NTSYSAPI LONG NTAPI RtlCompareString (const STRING *String1, const STRING *String2, BOOLEAN CaseInSensitive)
NTSYSAPI LONG NTAPI RtlCompareUnicodeString (PCUNICODE_STRING String1, PCUNICODE_STRING String2, BOOLEAN CaseInSensitive)
NTSYSAPI NTSTATUS NTAPI RtlCompressBuffer (IN USHORT CompressionFormatAndEngine, IN PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, OUT PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN ULONG UncompressedChunkSize, OUT PULONG FinalCompressedSize, IN PVOID WorkSpace)
NTSYSAPI NTSTATUS NTAPI RtlCompressChunks (IN PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, OUT PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN OUT PCOMPRESSED_DATA_INFO CompressedDataInfo, IN ULONG CompressedDataInfoLength, IN PVOID WorkSpace)
ULONG32 RtlComputeCrc32 (IN ULONG32 PartialCrc, IN PVOID Buffer, IN ULONG Length)
NTSYSAPI NTSTATUS RtlComputeImportTableHash (__in HANDLE hFile, __out_bcount(16) PCHAR Hash, __in ULONG ImportTableHashRevision)
NTSYSAPI NTSTATUS NTAPI RtlConsoleMultiByteToUnicodeN (__out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWCH UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString OPTIONAL, __in_bcount(BytesInMultiByteString) PCH MultiByteString, __in ULONG BytesInMultiByteString, __out PULONG pdwSpecialChar)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlConvertLongToLargeInteger (LONG SignedInteger)
FORCEINLINE LUID NTAPI RtlConvertLongToLuid (LONG Long)
NTSYSAPI NTSTATUS NTAPI RtlConvertSidToUnicodeString (PUNICODE_STRING UnicodeString, PSID Sid, BOOLEAN AllocateDestinationString)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlConvertUlongToLargeInteger (ULONG UnsignedInteger)
FORCEINLINE LUID NTAPI RtlConvertUlongToLuid (ULONG Ulong)
NTSYSAPI VOID NTAPI RtlCopyLuid (PLUID DestinationLuid, PLUID SourceLuid)
NTSYSAPI VOID NTAPI RtlCopyLuidAndAttributesArray (ULONG ArrayLength, PLUID_AND_ATTRIBUTES Source, PLUID_AND_ATTRIBUTES Target)
NTSYSAPI NTSTATUS NTAPI RtlCopyRangeList (OUT PRTL_RANGE_LIST CopyRangeList, IN PRTL_RANGE_LIST RangeList)
NTSYSAPI NTSTATUS NTAPI RtlCopySid (ULONG DestinationSidLength, PSID DestinationSid, PSID SourceSid)
NTSYSAPI NTSTATUS NTAPI RtlCopySidAndAttributesArray (ULONG ArrayLength, PSID_AND_ATTRIBUTES Source, ULONG TargetSidBufferSize, PSID_AND_ATTRIBUTES TargetArrayElement, PSID TargetSid, PSID *NextTargetSid, PULONG RemainingTargetSidSize)
NTSYSAPI VOID NTAPI RtlCopyString (PSTRING DestinationString, const STRING *SourceString)
NTSYSAPI VOID NTAPI RtlCopyUnicodeString (PUNICODE_STRING DestinationString, PCUNICODE_STRING SourceString)
NTSYSAPI NTSTATUS NTAPI RtlCreateAcl (PACL Acl, ULONG AclLength, ULONG AclRevision)
NTSYSAPI NTSTATUS NTAPI RtlCreateAtomTable (IN ULONG NumberOfBuckets, OUT PVOID *AtomTableHandle)
NTSYSAPI NTSTATUS NTAPI RtlCreateBootStatusDataFile (VOID)
NTSYSAPI NTSTATUS NTAPI RtlCreateEnvironment (BOOLEAN CloneCurrentEnvironment, PVOID *Environment)
NTSYSAPI PVOID NTAPI RtlCreateHeap (IN ULONG Flags, IN PVOID HeapBase OPTIONAL, IN SIZE_T ReserveSize OPTIONAL, IN SIZE_T CommitSize OPTIONAL, IN PVOID Lock OPTIONAL, IN PRTL_HEAP_PARAMETERS Parameters OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlCreateProcessParameters (PRTL_USER_PROCESS_PARAMETERS *ProcessParameters, PUNICODE_STRING ImagePathName, PUNICODE_STRING DllPath, PUNICODE_STRING CurrentDirectory, PUNICODE_STRING CommandLine, PVOID Environment, PUNICODE_STRING WindowTitle, PUNICODE_STRING DesktopInfo, PUNICODE_STRING ShellInfo, PUNICODE_STRING RuntimeData)
NTSYSAPI NTSTATUS NTAPI RtlCreateRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
NTSYSAPI NTSTATUS NTAPI RtlCreateSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Revision)
NTSYSAPI NTSTATUS NTAPI RtlCreateSecurityDescriptorRelative (PISECURITY_DESCRIPTOR_RELATIVE SecurityDescriptor, ULONG Revision)
NTSYSAPI NTSTATUS NTAPI RtlCreateSystemVolumeInformationFolder (IN PUNICODE_STRING VolumeRootPath)
NTSYSAPI BOOLEAN NTAPI RtlCreateUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCWSTR SourceString)
NTSYSAPI BOOLEAN NTAPI RtlCreateUnicodeStringFromAsciiz (OUT PUNICODE_STRING DestinationString, IN PCSZ SourceString)
NTSYSAPI NTSTATUS NTAPI RtlCreateUserProcess (PUNICODE_STRING NtImagePathName, ULONG Attributes, PRTL_USER_PROCESS_PARAMETERS ProcessParameters, PSECURITY_DESCRIPTOR ProcessSecurityDescriptor, PSECURITY_DESCRIPTOR ThreadSecurityDescriptor, HANDLE ParentProcess, BOOLEAN InheritHandles, HANDLE DebugPort, HANDLE ExceptionPort, PRTL_USER_PROCESS_INFORMATION ProcessInformation)
NTSYSAPI NTSTATUS NTAPI RtlCreateUserThread (HANDLE Process, PSECURITY_DESCRIPTOR ThreadSecurityDescriptor, BOOLEAN CreateSuspended, ULONG StackZeroBits, SIZE_T MaximumStackSize OPTIONAL, SIZE_T InitialStackSize OPTIONAL, PUSER_THREAD_START_ROUTINE StartAddress, PVOID Parameter, PHANDLE Thread, PCLIENT_ID ClientId)
NTSYSAPI NTSTATUS NTAPI RtlCustomCPToUnicodeN (__in PCPTABLEINFO CustomCP, __out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWCH UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString, __in_bcount(BytesInCustomCPString) PCH CustomCPString, __in ULONG BytesInCustomCPString)
NTSYSAPI BOOLEAN NTAPI RtlCutoverTimeToSystemTime (PTIME_FIELDS CutoverTime, PLARGE_INTEGER SystemTime, PLARGE_INTEGER CurrentSystemTime, BOOLEAN ThisYear)
NTSYSAPI NTSTATUS NTAPI RtlDecompressBuffer (IN USHORT CompressionFormat, OUT PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, IN PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, OUT PULONG FinalUncompressedSize)
NTSYSAPI NTSTATUS NTAPI RtlDecompressChunks (OUT PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, IN PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN PUCHAR CompressedTail, IN ULONG CompressedTailSize, IN PCOMPRESSED_DATA_INFO CompressedDataInfo)
NTSYSAPI NTSTATUS NTAPI RtlDecompressFragment (IN USHORT CompressionFormat, OUT PUCHAR UncompressedFragment, IN ULONG UncompressedFragmentSize, IN PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN ULONG FragmentOffset, OUT PULONG FinalUncompressedSize, IN PVOID WorkSpace)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlDelete (PRTL_SPLAY_LINKS Links)
NTSYSAPI NTSTATUS NTAPI RtlDeleteAce (PACL Acl, ULONG AceIndex)
NTSYSAPI NTSTATUS NTAPI RtlDeleteAtomFromAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
NTSYSAPI BOOLEAN NTAPI RtlDeleteElementGenericTable (PRTL_GENERIC_TABLE Table, PVOID Buffer)
NTSYSAPI BOOLEAN NTAPI RtlDeleteElementGenericTableAvl (PRTL_AVL_TABLE Table, PVOID Buffer)
NTSYSAPI VOID NTAPI RtlDeleteNoSplay (PRTL_SPLAY_LINKS Links, PRTL_SPLAY_LINKS *Root)
NTSYSAPI NTSTATUS NTAPI RtlDeleteOwnersRanges (IN OUT PRTL_RANGE_LIST RangeList, IN PVOID Owner)
NTSYSAPI NTSTATUS NTAPI RtlDeleteRange (IN OUT PRTL_RANGE_LIST RangeList, IN ULONGLONG Start, IN ULONGLONG End, IN PVOID Owner)
NTSYSAPI NTSTATUS NTAPI RtlDeleteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName)
NTSYSAPI PRTL_USER_PROCESS_PARAMETERS NTAPI RtlDeNormalizeProcessParams (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
NTSYSAPI NTSTATUS NTAPI RtlDescribeChunk (IN USHORT CompressionFormat, IN OUT PUCHAR *CompressedBuffer, IN PUCHAR EndOfCompressedBufferPlus1, OUT PUCHAR *ChunkBuffer, OUT PULONG ChunkSize)
NTSYSAPI NTSTATUS NTAPI RtlDestroyAtomTable (IN PVOID AtomTableHandle)
NTSYSAPI NTSTATUS NTAPI RtlDestroyEnvironment (PVOID Environment)
NTSYSAPI PVOID NTAPI RtlDestroyHeap (IN PVOID HeapHandle)
NTSYSAPI NTSTATUS NTAPI RtlDestroyProcessParameters (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
NTSYSAPI NTSTATUS RtlDnsHostNameToComputerName (OUT PUNICODE_STRING ComputerNameString, IN PCUNICODE_STRING DnsHostNameString, IN BOOLEAN AllocateComputerNameString)
NTSYSAPI WCHAR NTAPI RtlDowncaseUnicodeChar (WCHAR SourceCharacter)
NTSTATUS RtlDowncaseUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlDuplicateUnicodeString (IN ULONG Flags, IN const UNICODE_STRING *StringIn, OUT UNICODE_STRING *StringOut)
NTSYSAPI NTSTATUS NTAPI RtlEmptyAtomTable (IN PVOID AtomTableHandle, IN BOOLEAN IncludePinnedAtoms)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlEnlargedIntegerMultiply (LONG Multiplicand, LONG Multiplier)
DECLSPEC_DEPRECATED_DDK __inline ULONG NTAPI RtlEnlargedUnsignedDivide (IN ULARGE_INTEGER Dividend, IN ULONG Divisor, IN PULONG Remainder OPTIONAL)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlEnlargedUnsignedMultiply (ULONG Multiplicand, ULONG Multiplier)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTable (PRTL_GENERIC_TABLE Table, BOOLEAN Restart)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableAvl (PRTL_AVL_TABLE Table, BOOLEAN Restart)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableLikeADirectory (IN PRTL_AVL_TABLE Table, IN PRTL_AVL_MATCH_FUNCTION MatchFunction, IN PVOID MatchData, IN ULONG NextFlag, IN OUT PVOID *RestartKey, IN OUT PULONG DeleteCount, IN OUT PVOID Buffer)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableWithoutSplaying (PRTL_GENERIC_TABLE Table, PVOID *RestartKey)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableWithoutSplayingAvl (PRTL_AVL_TABLE Table, PVOID *RestartKey)
NTSYSAPI BOOLEAN NTAPI RtlEqualComputerName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
NTSYSAPI BOOLEAN NTAPI RtlEqualDomainName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
NTSYSAPI BOOLEAN NTAPI RtlEqualPrefixSid (PSID Sid1, PSID Sid2)
NTSYSAPI BOOLEAN NTAPI RtlEqualSid (PSID Sid1, PSID Sid2)
NTSYSAPI BOOLEAN NTAPI RtlEqualString (const STRING *String1, const STRING *String2, BOOLEAN CaseInSensitive)
NTSYSAPI BOOLEAN NTAPI RtlEqualUnicodeString (PCUNICODE_STRING String1, PCUNICODE_STRING String2, BOOLEAN CaseInSensitive)
NTSYSAPI VOID NTAPI RtlEraseUnicodeString (PUNICODE_STRING String)
DECLSPEC_NORETURN NTSYSAPI VOID NTAPI RtlExitUserThread (IN NTSTATUS ExitStatus)
NTSYSAPI NTSTATUS NTAPI RtlExpandEnvironmentStrings_U (IN PVOID Environment OPTIONAL, IN PCUNICODE_STRING Source, OUT PUNICODE_STRING Destination, OUT PULONG ReturnedLength OPTIONAL)
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlExtendedIntegerMultiply (LARGE_INTEGER Multiplicand, LONG Multiplier)
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlExtendedLargeIntegerDivide (LARGE_INTEGER Dividend, ULONG Divisor, PULONG Remainder)
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlExtendedMagicDivide (LARGE_INTEGER Dividend, LARGE_INTEGER MagicDivisor, CCHAR ShiftCount)
NTSYSAPI VOID NTAPI RtlFillMemoryUlong (PVOID Destination, SIZE_T Length, ULONG Pattern)
NTSYSAPI VOID NTAPI RtlFillMemoryUlonglong (PVOID Destination, SIZE_T Length, ULONGLONG Pattern)
NTSYSAPI NTSTATUS NTAPI RtlFindCharInUnicodeString (IN ULONG Flags, IN PCUNICODE_STRING StringToSearch, IN PCUNICODE_STRING CharSet, OUT USHORT *NonInclusivePrefixLength)
NTSYSAPI ULONG NTAPI RtlFindClearBits (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
NTSYSAPI ULONG NTAPI RtlFindClearBitsAndSet (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
NTSYSAPI ULONG NTAPI RtlFindClearRuns (PRTL_BITMAP BitMapHeader, PRTL_BITMAP_RUN RunArray, ULONG SizeOfRunArray, BOOLEAN LocateLongestRuns)
NTSYSAPI ULONG NTAPI RtlFindFirstRunClear (PRTL_BITMAP BitMapHeader, PULONG StartingIndex)
NTSYSAPI ULONG NTAPI RtlFindLastBackwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
NTSYSAPI CCHAR NTAPI RtlFindLeastSignificantBit (IN ULONGLONG Set)
NTSYSAPI ULONG NTAPI RtlFindLongestRunClear (PRTL_BITMAP BitMapHeader, PULONG StartingIndex)
NTSYSAPI NTSTATUS NTAPI RtlFindMessage (PVOID DllHandle, ULONG MessageTableId, ULONG MessageLanguageId, ULONG MessageId, PMESSAGE_RESOURCE_ENTRY *MessageEntry)
NTSYSAPI CCHAR NTAPI RtlFindMostSignificantBit (IN ULONGLONG Set)
NTSYSAPI ULONG NTAPI RtlFindNextForwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
NTSYSAPI NTSTATUS NTAPI RtlFindRange (IN PRTL_RANGE_LIST RangeList, IN ULONGLONG Minimum, IN ULONGLONG Maximum, IN ULONG Length, IN ULONG Alignment, IN ULONG Flags, IN UCHAR AttributeAvailableMask, IN PVOID Context OPTIONAL, IN PRTL_CONFLICT_RANGE_CALLBACK Callback OPTIONAL, OUT PULONGLONG Start)
NTSYSAPI ULONG NTAPI RtlFindSetBits (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
NTSYSAPI ULONG NTAPI RtlFindSetBitsAndClear (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
NTSYSAPI PUNICODE_PREFIX_TABLE_ENTRY NTAPI RtlFindUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, PUNICODE_STRING FullName, ULONG CaseInsensitiveIndex)
NTSYSAPI PSLIST_ENTRY NTAPI RtlFirstEntrySList (IN const SLIST_HEADER *ListHead)
NTSYSAPI BOOLEAN NTAPI RtlFirstFreeAce (PACL Acl, PVOID *FirstFree)
NTSYSAPI BOOLEAN RtlFlushSecureMemoryCache (PVOID lpAddr, SIZE_T size)
NTSYSAPI NTSTATUS NTAPI RtlFormatCurrentUserKeyPath (OUT PUNICODE_STRING CurrentUserKeyPath)
NTSYSAPI NTSTATUS NTAPI RtlFormatMessage (__in PWSTR MessageFormat, __in ULONG MaximumWidth, __in BOOLEAN IgnoreInserts, __in BOOLEAN ArgumentsAreAnsi, __in BOOLEAN ArgumentsAreAnArray, __in va_list *Arguments, __out_bcount_part(Length,*ReturnLength) PWSTR Buffer, __in ULONG Length, __out_opt PULONG ReturnLength)
NTSYSAPI NTSTATUS NTAPI RtlFormatMessageEx (__in PWSTR MessageFormat, __in ULONG MaximumWidth, __in BOOLEAN IgnoreInserts, __in BOOLEAN ArgumentsAreAnsi, __in BOOLEAN ArgumentsAreAnArray, __in va_list *Arguments, __out_bcount_part(Length,*ReturnLength) PWSTR Buffer, __in ULONG Length, __out_opt PULONG ReturnLength, __out_opt PPARSE_MESSAGE_CONTEXT ParseContext)
NTSYSAPI VOID NTAPI RtlFreeAnsiString (PANSI_STRING AnsiString)
NTSYSAPI BOOLEAN NTAPI RtlFreeHeap (IN PVOID HeapHandle, IN ULONG Flags, IN PVOID BaseAddress)
NTSYSAPI VOID NTAPI RtlFreeOemString (POEM_STRING OemString)
NTSYSAPI VOID NTAPI RtlFreeRangeList (IN PRTL_RANGE_LIST RangeList)
NTSYSAPI PVOID NTAPI RtlFreeSid (IN PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlFreeToPeb (PVOID Block, ULONG Size)
NTSYSAPI VOID NTAPI RtlFreeUnicodeString (PUNICODE_STRING UnicodeString)
NTSYSAPI VOID NTAPI RtlFreeUserThreadStack (HANDLE hProcess, HANDLE hThread)
NTSYSAPI VOID NTAPI RtlGenerate8dot3Name (IN PUNICODE_STRING Name, IN BOOLEAN AllowExtendedCharacters, IN OUT PGENERATE_NAME_CONTEXT Context, OUT PUNICODE_STRING Name8dot3)
NTSYSAPI NTSTATUS NTAPI RtlGetAce (PACL Acl, ULONG AceIndex, PVOID *Ace)
NTSYSAPI VOID NTAPI RtlGetCallersAddress (OUT PVOID *CallersAddress, OUT PVOID *CallersCaller)
NTSYSAPI NTSTATUS NTAPI RtlGetCompressionWorkSpaceSize (IN USHORT CompressionFormatAndEngine, OUT PULONG CompressBufferWorkSpaceSize, OUT PULONG CompressFragmentWorkSpaceSize)
NTSYSAPI NTSTATUS NTAPI RtlGetControlSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, PSECURITY_DESCRIPTOR_CONTROL Control, PULONG Revision)
PPEB RtlGetCurrentPeb (VOID)
NTSYSAPI NTSTATUS NTAPI RtlGetDaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN DaclPresent, OUT PACL *Dacl, OUT PBOOLEAN DaclDefaulted)
NTSYSAPI VOID NTAPI RtlGetDefaultCodePage (OUT PUSHORT AnsiCodePage, OUT PUSHORT OemCodePage)
NTSYSAPI PVOID NTAPI RtlGetElementGenericTable (PRTL_GENERIC_TABLE Table, ULONG I)
NTSYSAPI PVOID NTAPI RtlGetElementGenericTableAvl (PRTL_AVL_TABLE Table, ULONG I)
NTSYSAPI NTSTATUS NTAPI RtlGetFirstRange (IN PRTL_RANGE_LIST RangeList, OUT PRTL_RANGE_LIST_ITERATOR Iterator, OUT PRTL_RANGE *Range)
NTSYSAPI NTSTATUS NTAPI RtlGetGroupSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID *Group, OUT PBOOLEAN GroupDefaulted)
NTSTATUS NTAPI RtlGetLastNtStatus (VOID)
NTSYSAPI NTSTATUS NTAPI RtlGetLastRange (IN PRTL_RANGE_LIST RangeList, OUT PRTL_RANGE_LIST_ITERATOR Iterator, OUT PRTL_RANGE *Range)
NTSYSAPI LONG NTAPI RtlGetLastWin32Error (VOID)
NTSYSAPI NTSTATUS NTAPI RtlGetNextRange (IN OUT PRTL_RANGE_LIST_ITERATOR Iterator, OUT PRTL_RANGE *Range, IN BOOLEAN MoveForwards)
NTSYSAPI ULONG NTAPI RtlGetNtGlobalFlags (VOID)
NTSYSAPI BOOLEAN NTAPI RtlGetNtProductType (PNT_PRODUCT_TYPE NtProductType)
NTSYSAPI NTSTATUS NTAPI RtlGetOwnerSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID *Owner, OUT PBOOLEAN OwnerDefaulted)
NTSTATUS NTAPI RtlGetPrimaryDomain (IN ULONG SidLength, OUT PBOOLEAN PrimaryDomainPresent, OUT PUNICODE_STRING PrimaryDomainName, OUT PUSHORT RequiredNameLength, OUT PSID PrimaryDomainSid OPTIONAL, OUT PULONG RequiredSidLength)
NTSYSAPI NTSTATUS NTAPI RtlGetSaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN SaclPresent, OUT PACL *Sacl, OUT PBOOLEAN SaclDefaulted)
NTSYSAPI BOOLEAN NTAPI RtlGetSecurityDescriptorRMControl (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PUCHAR RMControl)
NTSYSAPI NTSTATUS NTAPI RtlGetSetBootStatusData (IN HANDLE Handle, IN BOOLEAN Get, IN RTL_BSD_ITEM_TYPE DataItem, IN PVOID DataBuffer, IN ULONG DataBufferLength, OUT PULONG ByteRead OPTIONAL)
NTSYSAPI NTSTATUS RtlGetVersion (OUT PRTL_OSVERSIONINFOW lpVersionInformation)
NTSYSAPI NTSTATUS NTAPI RtlGUIDFromString (IN PUNICODE_STRING GuidString, OUT GUID *Guid)
NTSYSAPI NTSTATUS NTAPI RtlHashUnicodeString (IN const UNICODE_STRING *String, IN BOOLEAN CaseInSensitive, IN ULONG HashAlgorithm, OUT PULONG HashValue)
NTSYSAPI PSID_IDENTIFIER_AUTHORITY NTAPI RtlIdentifierAuthoritySid (PSID Sid)
NTSYSAPI PVOID NTAPI RtlImageDirectoryEntryToData (PVOID BaseOfImage, BOOLEAN MappedAsImage, USHORT DirectoryEntry, PULONG Size)
NTSYSAPI PIMAGE_NT_HEADERS NTAPI RtlImageNtHeader (PVOID Base)
NTSYSAPI NTSTATUS NTAPI RtlImageNtHeaderEx (ULONG Flags, PVOID Base, ULONG64 Size, OUT PIMAGE_NT_HEADERS *OutHeaders)
NTSYSAPI PIMAGE_SECTION_HEADER NTAPI RtlImageRvaToSection (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Rva)
NTSYSAPI PVOID NTAPI RtlImageRvaToVa (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Rva, IN OUT PIMAGE_SECTION_HEADER *LastRvaSection OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlImpersonateSelf (IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
NTSYSAPI VOID NTAPI RtlInitAnsiString (PANSI_STRING DestinationString, PCSZ SourceString)
NTSYSAPI NTSTATUS NTAPI RtlInitAnsiStringEx (OUT PANSI_STRING DestinationString, IN PCSZ SourceString OPTIONAL)
NTSYSAPI VOID NTAPI RtlInitCodePageTable (IN PUSHORT TableBase, OUT PCPTABLEINFO CodePageTable)
NTSYSAPI NTSTATUS NTAPI RtlInitializeAtomPackage (IN ULONG AllocationTag)
NTSYSAPI VOID NTAPI RtlInitializeBitMap (PRTL_BITMAP BitMapHeader, PULONG BitMapBuffer, ULONG SizeOfBitMap)
NTSYSAPI VOID NTAPI RtlInitializeContext (HANDLE Process, PCONTEXT Context, PVOID Parameter, PVOID InitialPc, PVOID InitialSp)
NTSYSAPI VOID NTAPI RtlInitializeExceptionLog (IN ULONG Entries)
NTSYSAPI VOID NTAPI RtlInitializeGenericTable (PRTL_GENERIC_TABLE Table, PRTL_GENERIC_COMPARE_ROUTINE CompareRoutine, PRTL_GENERIC_ALLOCATE_ROUTINE AllocateRoutine, PRTL_GENERIC_FREE_ROUTINE FreeRoutine, PVOID TableContext)
NTSYSAPI VOID NTAPI RtlInitializeGenericTableAvl (PRTL_AVL_TABLE Table, PRTL_AVL_COMPARE_ROUTINE CompareRoutine, PRTL_AVL_ALLOCATE_ROUTINE AllocateRoutine, PRTL_AVL_FREE_ROUTINE FreeRoutine, PVOID TableContext)
NTSYSAPI NTSTATUS NTAPI RtlInitializeHeapManager (VOID)
NTSYSAPI VOID NTAPI RtlInitializeRangeList (IN OUT PRTL_RANGE_LIST RangeList)
VOID NTAPI RtlInitializeRangeListPackage (VOID)
NTSYSAPI NTSTATUS NTAPI RtlInitializeRXact (IN HANDLE RootRegistryKey, IN BOOLEAN CommitIfNecessary, OUT PRTL_RXACT_CONTEXT *RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlInitializeSid (PSID Sid, PSID_IDENTIFIER_AUTHORITY IdentifierAuthority, UCHAR SubAuthorityCount)
NTSYSAPI VOID NTAPI RtlInitializeSListHead (IN PSLIST_HEADER ListHead)
NTSYSAPI VOID NTAPI RtlInitializeUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable)
NTSYSAPI VOID NTAPI RtlInitNlsTables (IN PUSHORT AnsiNlsBase, IN PUSHORT OemNlsBase, IN PUSHORT LanguageNlsBase, OUT PNLSTABLEINFO TableInfo)
NTSYSAPI VOID NTAPI RtlInitString (PSTRING DestinationString, PCSZ SourceString)
NTSYSAPI VOID NTAPI RtlInitUnicodeString (PUNICODE_STRING DestinationString, PCWSTR SourceString)
NTSYSAPI NTSTATUS NTAPI RtlInitUnicodeStringEx (PUNICODE_STRING DestinationString, PCWSTR SourceString)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTable (PRTL_GENERIC_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTableAvl (PRTL_AVL_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTableFull (PRTL_GENERIC_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL, PVOID NodeOrParent, TABLE_SEARCH_RESULT SearchResult)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTableFullAvl (PRTL_AVL_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL, PVOID NodeOrParent, TABLE_SEARCH_RESULT SearchResult)
NTSYSAPI BOOLEAN NTAPI RtlInsertUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, PUNICODE_STRING Prefix, PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
NTSYSAPI NTSTATUS NTAPI RtlInt64ToUnicodeString (IN ULONGLONG Value, IN ULONG Base OPTIONAL, IN OUT PUNICODE_STRING String)
NTSYSAPI NTSTATUS NTAPI RtlIntegerToChar (ULONG Value, ULONG Base, LONG OutputLength, PSZ String)
NTSYSAPI NTSTATUS NTAPI RtlIntegerToUnicode (IN ULONG Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
NTSYSAPI NTSTATUS NTAPI RtlIntegerToUnicodeString (ULONG Value, ULONG Base, PUNICODE_STRING String)
NTSYSAPI PSLIST_ENTRY NTAPI RtlInterlockedFlushSList (IN PSLIST_HEADER ListHead)
NTSYSAPI PSLIST_ENTRY NTAPI RtlInterlockedPopEntrySList (IN PSLIST_HEADER ListHead)
NTSYSAPI PSLIST_ENTRY NTAPI RtlInterlockedPushEntrySList (IN PSLIST_HEADER ListHead, IN PSLIST_ENTRY ListEntry)
PSLIST_ENTRY FASTCALL RtlInterlockedPushListSList (IN PSLIST_HEADER ListHead, IN PSLIST_ENTRY List, IN PSLIST_ENTRY ListEnd, IN ULONG Count)
ULONG FASTCALL RtlInterlockedSetClearBits (IN OUT PULONG Flags, IN ULONG sFlag, IN ULONG cFlag)
NTSYSAPI NTSTATUS NTAPI RtlInvertRangeList (OUT PRTL_RANGE_LIST InvertedRangeList, IN PRTL_RANGE_LIST RangeList)
NTSYSAPI PSTR NTAPI RtlIpv4AddressToStringA (__in const struct in_addr *Addr, __out_ecount(16) PSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv4AddressToStringExA (__in const struct in_addr *Address, __in USHORT Port, __out_ecount_part(*AddressStringLength,*AddressStringLength) PSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI NTSTATUS NTAPI RtlIpv4AddressToStringExW (__in const struct in_addr *Address, __in USHORT Port, __out_ecount_part(*AddressStringLength,*AddressStringLength) PWSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI PWSTR NTAPI RtlIpv4AddressToStringW (__in const struct in_addr *Addr, __out_ecount(16) PWSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressA (IN PCSTR S, IN BOOLEAN Strict, OUT PCSTR *Terminator, OUT struct in_addr *Addr)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressExA (IN PCSTR AddressString, IN BOOLEAN Strict, OUT struct in_addr *Address, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressExW (IN PCWSTR AddressString, IN BOOLEAN Strict, OUT struct in_addr *Address, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressW (IN PCWSTR S, IN BOOLEAN Strict, OUT LPCWSTR *Terminator, OUT struct in_addr *Addr)
NTSYSAPI PSTR NTAPI RtlIpv6AddressToStringA (__in const struct in6_addr *Addr, __out_ecount(65) PSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv6AddressToStringExA (__in const struct in6_addr *Address, __in ULONG ScopeId, __in USHORT Port, __out_ecount_part(*AddressStringLength,*AddressStringLength) PSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI NTSTATUS NTAPI RtlIpv6AddressToStringExW (__in const struct in6_addr *Address, __in ULONG ScopeId, __in USHORT Port, __out_ecount_part(*AddressStringLength,*AddressStringLength) PWSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI PWSTR NTAPI RtlIpv6AddressToStringW (__in const struct in6_addr *Addr, __out_ecount(65) PWSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressA (IN PCSTR S, OUT PCSTR *Terminator, OUT struct in6_addr *Addr)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressExA (IN PCSTR AddressString, OUT struct in6_addr *Address, OUT PULONG ScopeId, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressExW (IN PCWSTR AddressString, OUT struct in6_addr *Address, OUT PULONG ScopeId, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressW (IN PCWSTR S, OUT PCWSTR *Terminator, OUT struct in6_addr *Addr)
NTSYSAPI BOOLEAN NTAPI RtlIsGenericTableEmpty (PRTL_GENERIC_TABLE Table)
NTSYSAPI BOOLEAN NTAPI RtlIsGenericTableEmptyAvl (PRTL_AVL_TABLE Table)
NTSYSAPI BOOLEAN NTAPI RtlIsNameLegalDOS8Dot3 (IN PUNICODE_STRING Name, IN OUT POEM_STRING OemName OPTIONAL, IN OUT PBOOLEAN NameContainsSpaces OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlIsRangeAvailable (IN PRTL_RANGE_LIST RangeList, IN ULONGLONG Start, IN ULONGLONG End, IN ULONG Flags, IN UCHAR AttributeAvailableMask, IN PVOID Context OPTIONAL, IN PRTL_CONFLICT_RANGE_CALLBACK Callback OPTIONAL, OUT PBOOLEAN Available)
NTSYSAPI BOOLEAN NTAPI RtlIsTextUnicode (IN CONST VOID *Buffer, IN ULONG Size, IN OUT PULONG Result OPTIONAL)
BOOLEAN RtlIsValidOemCharacter (__inout PWCHAR Char)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerAdd (LARGE_INTEGER Addend1, LARGE_INTEGER Addend2)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerArithmeticShift (LARGE_INTEGER LargeInteger, CCHAR ShiftCount)
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlLargeIntegerDivide (LARGE_INTEGER Dividend, LARGE_INTEGER Divisor, PLARGE_INTEGER Remainder)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerNegate (LARGE_INTEGER Subtrahend)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerShiftLeft (LARGE_INTEGER LargeInteger, CCHAR ShiftCount)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerShiftRight (LARGE_INTEGER LargeInteger, CCHAR ShiftCount)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerSubtract (LARGE_INTEGER Minuend, LARGE_INTEGER Subtrahend)
NTSYSAPI NTSTATUS NTAPI RtlLargeIntegerToChar (PLARGE_INTEGER Value, ULONG Base OPTIONAL, LONG OutputLength, PSZ String)
NTSYSAPI NTSTATUS NTAPI RtlLargeIntegerToUnicode (IN PLARGE_INTEGER Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
NTSYSAPI ULONG NTAPI RtlLengthRequiredSid (ULONG SubAuthorityCount)
NTSYSAPI ULONG NTAPI RtlLengthSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSYSAPI ULONG NTAPI RtlLengthSid (PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlLengthSidAsUnicodeString (PSID Sid, PULONG StringLength)
NTSYSAPI NTSTATUS NTAPI RtlLocalTimeToSystemTime (IN PLARGE_INTEGER LocalTime, OUT PLARGE_INTEGER SystemTime)
NTSYSAPI NTSTATUS NTAPI RtlLockBootStatusData (OUT PHANDLE BootStatusDataHandle)
NTSYSAPI USHORT NTAPI RtlLogStackBackTrace (VOID)
NTSYSAPI NTSTATUS NTAPI RtlLookupAtomInAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __out_opt PRTL_ATOM Atom)
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTable (PRTL_GENERIC_TABLE Table, PVOID Buffer)
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTableAvl (PRTL_AVL_TABLE Table, PVOID Buffer)
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTableFull (PRTL_GENERIC_TABLE Table, PVOID Buffer, OUT PVOID *NodeOrParent, OUT TABLE_SEARCH_RESULT *SearchResult)
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTableFullAvl (PRTL_AVL_TABLE Table, PVOID Buffer, OUT PVOID *NodeOrParent, OUT TABLE_SEARCH_RESULT *SearchResult)
NTSYSAPI NTSTATUS NTAPI RtlMakeSelfRelativeSD (__in PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __out_bcount(*BufferLength) PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
VOID RtlMakeStackTraceDataPresent (VOID)
NTSYSAPI VOID NTAPI RtlMapGenericMask (PACCESS_MASK AccessMask, PGENERIC_MAPPING GenericMapping)
NTSYSAPI NTSTATUS NTAPI RtlMapSecurityErrorToNtStatus (SECURITY_STATUS Error)
NTSYSAPI NTSTATUS NTAPI RtlMergeRangeLists (OUT PRTL_RANGE_LIST MergedRangeList, IN PRTL_RANGE_LIST RangeList1, IN PRTL_RANGE_LIST RangeList2, IN ULONG Flags)
NTSYSAPI NTSTATUS NTAPI RtlMultiByteToUnicodeN (__out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWCH UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString, __in_bcount(BytesInMultiByteString) PCSTR MultiByteString, __in ULONG BytesInMultiByteString)
NTSYSAPI NTSTATUS NTAPI RtlMultiByteToUnicodeSize (PULONG BytesInUnicodeString, PCSTR MultiByteString, ULONG BytesInMultiByteString)
NTSYSAPI NTSTATUS NTAPI RtlNewSecurityGrantedAccess (ACCESS_MASK DesiredAccess, PPRIVILEGE_SET Privileges, PULONG Length, HANDLE Token, PGENERIC_MAPPING GenericMapping, PACCESS_MASK RemainingDesiredAccess)
NTSYSAPI PUNICODE_PREFIX_TABLE_ENTRY NTAPI RtlNextUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, BOOLEAN Restart)
NTSYSAPI PRTL_USER_PROCESS_PARAMETERS NTAPI RtlNormalizeProcessParams (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
NTSYSAPI ULONG NTAPI RtlNtStatusToDosError (NTSTATUS Status)
NTSYSAPI ULONG NTAPI RtlNtStatusToDosErrorNoTeb (NTSTATUS Status)
NTSYSAPI ULONG NTAPI RtlNumberGenericTableElements (PRTL_GENERIC_TABLE Table)
NTSYSAPI ULONG NTAPI RtlNumberGenericTableElementsAvl (PRTL_AVL_TABLE Table)
NTSYSAPI ULONG NTAPI RtlNumberOfClearBits (PRTL_BITMAP BitMapHeader)
NTSYSAPI ULONG NTAPI RtlNumberOfSetBits (PRTL_BITMAP BitMapHeader)
NTSYSAPI NTSTATUS NTAPI RtlOemStringToCountedUnicodeString (PUNICODE_STRING DestinationString, PCOEM_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlOemStringToUnicodeString (PUNICODE_STRING DestinationString, PCOEM_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlOemToUnicodeN (__out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWSTR UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString, __in_bcount(BytesInOemString) PCH OemString, __in ULONG BytesInOemString)
NTSYSAPI NTSTATUS NTAPI RtlOpenCurrentUser (IN ULONG DesiredAccess, OUT PHANDLE CurrentUserKey)
RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32 (RtlAddWithCarryOutUint, unsigned int) RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32(RtlAddWithCarryOutDword
unsigned long RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED32 (RtlAddWithOverflowOutInt, int) typedef struct _RTL_BACKOFF
NTSYSAPI PVOID NTAPI RtlPcToFileHeader (PVOID PcValue, PVOID *BaseOfImage)
VOID RtlpGetStackLimits (OUT PULONG_PTR LowLimit, OUT PULONG_PTR HighLimit)
__inline PIMAGE_NT_HEADERS NTAPI RtlpImageNtHeader (IN PVOID Base)
NTSYSAPI NTSTATUS NTAPI RtlPinAtomInAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
NTSTATUS RtlpNtCreateKey (PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG Options, PUNICODE_STRING Provider, PULONG Disposition)
NTSTATUS RtlpNtEnumerateSubKey (HANDLE KeyHandle, PUNICODE_STRING SubKeyName, ULONG Index, PLARGE_INTEGER LastWriteTime)
NTSTATUS RtlpNtMakeTemporaryKey (HANDLE KeyHandle)
NTSTATUS RtlpNtOpenKey (PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG Options)
NTSTATUS RtlpNtQueryValueKey (HANDLE KeyHandle, PULONG KeyValueType, PVOID KeyValue, PULONG KeyValueLength, PLARGE_INTEGER LastWriteTime)
NTSTATUS RtlpNtSetValueKey (HANDLE KeyHandle, ULONG KeyValueType, PVOID KeyValue, ULONG KeyValueLength)
NTSYSAPI VOID FASTCALL RtlPrefetchMemoryNonTemporal (IN PVOID Source, IN SIZE_T Length)
NTSYSAPI BOOLEAN NTAPI RtlPrefixString (const STRING *String1, const STRING *String2, BOOLEAN CaseInSensitive)
NTSYSAPI BOOLEAN NTAPI RtlPrefixUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
NTSYSAPI VOID NTAPI RtlProtectHeap (IN PVOID HeapHandle, IN BOOLEAN MakeReadOnly)
NTSYSAPI NTSTATUS NTAPI RtlQueryAtomInAtomTable (__in PVOID AtomTableHandle, __in RTL_ATOM Atom, __out_opt PULONG AtomUsage, __out_opt PULONG AtomFlags, __inout_bcount_part_opt(*AtomNameLength,*AtomNameLength) PWSTR AtomName, __inout_opt PULONG AtomNameLength)
NTSYSAPI NTSTATUS NTAPI RtlQueryAtomsInAtomTable (IN PVOID AtomTableHandle, IN ULONG MaximumNumberOfAtoms, OUT PULONG NumberOfAtoms, OUT PRTL_ATOM Atoms)
NTSYSAPI USHORT NTAPI RtlQueryDepthSList (IN PSLIST_HEADER ListHead)
NTSYSAPI NTSTATUS NTAPI RtlQueryEnvironmentVariable_U (PVOID Environment, PCUNICODE_STRING Name, PUNICODE_STRING Value)
NTSYSAPI NTSTATUS NTAPI RtlQueryInformationAcl (PACL Acl, PVOID AclInformation, ULONG AclInformationLength, ACL_INFORMATION_CLASS AclInformationClass)
NTSYSAPI NTSTATUS NTAPI RtlQueryRegistryValues (IN ULONG RelativeTo, IN PCWSTR Path, IN PRTL_QUERY_REGISTRY_TABLE QueryTable, IN PVOID Context, IN PVOID Environment OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlQueryTimeZoneInformation (OUT PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
NTSYSAPI ULONG NTAPI RtlRandom (PULONG Seed)
NTSYSAPI ULONG NTAPI RtlRandomEx (PULONG Seed)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlRealPredecessor (PRTL_SPLAY_LINKS Links)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlRealSuccessor (PRTL_SPLAY_LINKS Links)
NTSTATUS RtlRegisterSecureMemoryCacheCallback (IN PRTL_SECURE_MEMORY_CACHE_CALLBACK CallBack)
NTSYSAPI VOID NTAPI RtlReleasePebLock (VOID)
NTSYSAPI VOID NTAPI RtlReleasePrivilege (PVOID StatePointer)
NTSYSAPI NTSTATUS NTAPI RtlRemoteCall (HANDLE Process, HANDLE Thread, PVOID CallSite, ULONG ArgumentCount, PULONG_PTR Arguments, BOOLEAN PassContext, BOOLEAN AlreadySuspended)
NTSYSAPI VOID NTAPI RtlRemoveUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
NTSYSAPI NTSTATUS NTAPI RtlReserveChunk (IN USHORT CompressionFormat, IN OUT PUCHAR *CompressedBuffer, IN PUCHAR EndOfCompressedBufferPlus1, OUT PUCHAR *ChunkBuffer, IN ULONG ChunkSize)
NTSYSAPI VOID NTAPI RtlResetRtlTranslations (PNLSTABLEINFO TableInfo)
NTSYSAPI VOID NTAPI RtlRestoreLastWin32Error (LONG Win32Error)
NTSYSAPI VOID NTAPI RtlRunDecodeUnicodeString (UCHAR Seed, PUNICODE_STRING String)
NTSYSAPI VOID NTAPI RtlRunEncodeUnicodeString (PUCHAR Seed OPTIONAL, PUNICODE_STRING String)
NTSYSAPI VOID NTAPI RtlSecondsSince1970ToTime (ULONG ElapsedSeconds, PLARGE_INTEGER Time)
NTSYSAPI VOID NTAPI RtlSecondsSince1980ToTime (ULONG ElapsedSeconds, PLARGE_INTEGER Time)
NTSYSAPI PIMAGE_SECTION_HEADER NTAPI RtlSectionTableFromVirtualAddress (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID BaseOfImage, IN ULONG VirtualAddress)
FORCEINLINE PVOID RtlSecureZeroMemory (IN PVOID ptr, IN SIZE_T cnt)
NTSYSAPI NTSTATUS NTAPI RtlSelfRelativeToAbsoluteSD (__in PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __out_bcount_part_opt(*AbsoluteSecurityDescriptorSize,*AbsoluteSecurityDescriptorSize) PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __inout PULONG AbsoluteSecurityDescriptorSize, __out_bcount_part_opt(*DaclSize,*DaclSize) PACL Dacl, __inout PULONG DaclSize, __out_bcount_part_opt(*SaclSize,*SaclSize) PACL Sacl, __inout PULONG SaclSize, __out_bcount_part_opt(*OwnerSize,*OwnerSize) PSID Owner, __inout PULONG OwnerSize, __out_bcount_part_opt(*PrimaryGroupSize,*PrimaryGroupSize) PSID PrimaryGroup, __inout PULONG PrimaryGroupSize)
NTSYSAPI NTSTATUS NTAPI RtlSelfRelativeToAbsoluteSD2 (__inout_bcount(*pBufferSize) PSECURITY_DESCRIPTOR pSelfRelativeSecurityDescriptor, __inout PULONG pBufferSize)
NTSYSAPI NTSTATUS NTAPI RtlSetActiveTimeBias (IN LONG ActiveBias)
NTSYSAPI VOID NTAPI RtlSetAllBits (PRTL_BITMAP BitMapHeader)
NTSYSAPI NTSTATUS NTAPI RtlSetAttributesSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL Control, IN OUT PULONG Revision)
NTSYSAPI VOID NTAPI RtlSetBit (PRTL_BITMAP BitMapHeader, ULONG BitNumber)
NTSYSAPI VOID NTAPI RtlSetBits (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG NumberToSet)
NTSYSAPI NTSTATUS NTAPI RtlSetControlSecurityDescriptor (IN PSECURITY_DESCRIPTOR pSecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsOfInterest, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsToSet)
NTSYSAPI NTSTATUS NTAPI RtlSetCurrentEnvironment (PVOID Environment, PVOID *PreviousEnvironment)
NTSYSAPI NTSTATUS NTAPI RtlSetDaclSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, BOOLEAN DaclPresent, PACL Dacl, BOOLEAN DaclDefaulted)
NTSYSAPI NTSTATUS NTAPI RtlSetEnvironmentVariable (PVOID *Environment, PCUNICODE_STRING Name, PCUNICODE_STRING Value)
NTSYSAPI NTSTATUS NTAPI RtlSetGroupSecurityDescriptor (IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID Group OPTIONAL, IN BOOLEAN GroupDefaulted OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlSetInformationAcl (PACL Acl, PVOID AclInformation, ULONG AclInformationLength, ACL_INFORMATION_CLASS AclInformationClass)
NTSYSAPI VOID NTAPI RtlSetLastWin32Error (LONG Win32Error)
NTSYSAPI VOID NTAPI RtlSetLastWin32ErrorAndNtStatusFromNtStatus (NTSTATUS Status)
NTSYSAPI NTSTATUS NTAPI RtlSetOwnerSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, PSID Owner, BOOLEAN OwnerDefaulted)
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetProcessIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
NTSYSAPI NTSTATUS NTAPI RtlSetSaclSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, BOOLEAN SaclPresent, PACL Sacl, BOOLEAN SaclDefaulted)
NTSYSAPI VOID NTAPI RtlSetSecurityDescriptorRMControl (IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN PUCHAR RMControl OPTIONAL)
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetThreadIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
NTSYSAPI NTSTATUS NTAPI RtlSetTimeZoneInformation (IN PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
FORCEINLINE BOOLEAN RtlSignedAddWithOverflowOut32 (__int32 *pc, __int32 a, __int32 b)
FORCEINLINE BOOLEAN RtlSignedAddWithOverflowOut64 (__int64 *pc, __int64 a, __int64 b)
NTSYSAPI SIZE_T NTAPI RtlSizeHeap (IN PVOID HeapHandle, IN ULONG Flags, IN PVOID BaseAddress)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlSplay (PRTL_SPLAY_LINKS Links)
NTSYSAPI NTSTATUS NTAPI RtlStartRXact (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlStringFromGUID (IN REFGUID Guid, OUT PUNICODE_STRING GuidString)
NTSYSAPI PUCHAR NTAPI RtlSubAuthorityCountSid (PSID Sid)
NTSYSAPI PULONG NTAPI RtlSubAuthoritySid (PSID Sid, ULONG SubAuthority)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlSubtreePredecessor (PRTL_SPLAY_LINKS Links)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlSubtreeSuccessor (PRTL_SPLAY_LINKS Links)
NTSYSAPI NTSTATUS NTAPI RtlSystemTimeToLocalTime (IN PLARGE_INTEGER SystemTime, OUT PLARGE_INTEGER LocalTime)
NTSYSAPI BOOLEAN NTAPI RtlTestBit (PRTL_BITMAP BitMapHeader, ULONG BitNumber)
NTSYSAPI BOOLEAN NTAPI RtlTimeFieldsToTime (PTIME_FIELDS TimeFields, PLARGE_INTEGER Time)
NTSYSAPI VOID NTAPI RtlTimeToElapsedTimeFields (IN PLARGE_INTEGER Time, OUT PTIME_FIELDS TimeFields)
NTSYSAPI BOOLEAN NTAPI RtlTimeToSecondsSince1970 (PLARGE_INTEGER Time, PULONG ElapsedSeconds)
NTSYSAPI BOOLEAN NTAPI RtlTimeToSecondsSince1980 (PLARGE_INTEGER Time, PULONG ElapsedSeconds)
NTSYSAPI VOID NTAPI RtlTimeToTimeFields (PLARGE_INTEGER Time, PTIME_FIELDS TimeFields)
BOOLEAN RtlTraceDatabaseAdd (IN PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID *Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
PRTL_TRACE_DATABASE RtlTraceDatabaseCreate (IN ULONG Buckets, IN SIZE_T MaximumSize OPTIONAL, IN ULONG Flags, IN ULONG Tag, IN RTL_TRACE_HASH_FUNCTION HashFunction OPTIONAL)
BOOLEAN RtlTraceDatabaseDestroy (IN PRTL_TRACE_DATABASE Database)
BOOLEAN RtlTraceDatabaseEnumerate (PRTL_TRACE_DATABASE Database, OUT PRTL_TRACE_ENUMERATE Enumerate, OUT PRTL_TRACE_BLOCK *TraceBlock)
BOOLEAN RtlTraceDatabaseFind (PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID *Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
VOID RtlTraceDatabaseLock (IN PRTL_TRACE_DATABASE Database)
VOID RtlTraceDatabaseUnlock (IN PRTL_TRACE_DATABASE Database)
BOOLEAN RtlTraceDatabaseValidate (IN PRTL_TRACE_DATABASE Database)
ULONG FASTCALL RtlUlongByteSwap (IN ULONG Source)
ULONGLONG FASTCALL RtlUlonglongByteSwap (IN ULONGLONG Source)
NTSYSAPI LONG NTAPI RtlUnhandledExceptionFilter (IN struct _EXCEPTION_POINTERS *ExceptionInfo)
NTSYSAPI LONG NTAPI RtlUnhandledExceptionFilter2 (__in struct _EXCEPTION_POINTERS *ExceptionInfo, __in PCSTR Function)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToAnsiString (PANSI_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToCountedOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToInteger (PCUNICODE_STRING String, ULONG Base, PULONG Value)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToCustomCPN (__in PCPTABLEINFO CustomCP, __out_bcount_part(MaxBytesInCustomCPString,*BytesInCustomCPString) PCH CustomCPString, __in ULONG MaxBytesInCustomCPString, __out_opt PULONG BytesInCustomCPString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToMultiByteN (__out_bcount_part(MaxBytesInMultiByteString,*BytesInMultiByteString) PCHAR MultiByteString, __in ULONG MaxBytesInMultiByteString, __out_opt PULONG BytesInMultiByteString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToMultiByteSize (__out PULONG BytesInMultiByteString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToOemN (__out_bcount_part(MaxBytesInOemString,*BytesInOemString) PCHAR OemString, __in ULONG MaxBytesInOemString, __out_opt PULONG BytesInOemString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI ULONG NTAPI RtlUniform (PULONG Seed)
NTSYSAPI VOID NTAPI RtlUnlockBootStatusData (IN HANDLE BootStatusDataHandle)
FORCEINLINE BOOLEAN RtlUnsignedAddWithCarryOut32 (unsigned __int32 *pc, unsigned __int32 a, unsigned __int32 b)
FORCEINLINE BOOLEAN RtlUnsignedAddWithCarryOut64 (unsigned __int64 *pc, unsigned __int64 a, unsigned __int64 b)
NTSYSAPI WCHAR NTAPI RtlUpcaseUnicodeChar (WCHAR SourceCharacter)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeString (PUNICODE_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeStringToAnsiString (PANSI_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeStringToCountedOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeStringToOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeToCustomCPN (__in PCPTABLEINFO CustomCP, __out_bcount_part(MaxBytesInCustomCPString,*BytesInCustomCPString) PCH CustomCPString, __in ULONG MaxBytesInCustomCPString, __out_opt PULONG BytesInCustomCPString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeToMultiByteN (__out_bcount_part(MaxBytesInMultiByteString,*BytesInMultiByteString) PCHAR MultiByteString, __in ULONG MaxBytesInMultiByteString, __out_opt PULONG BytesInMultiByteString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeToOemN (__out_bcount_part(MaxBytesInOemString,*BytesInOemString) PCHAR OemString, __in ULONG MaxBytesInOemString, __out_opt PULONG BytesInOemString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
NTSYSAPI CHAR NTAPI RtlUpperChar (CHAR Character)
NTSYSAPI VOID NTAPI RtlUpperString (PSTRING DestinationString, const STRING *SourceString)
USHORT FASTCALL RtlUshortByteSwap (IN USHORT Source)
NTSYSAPI BOOLEAN NTAPI RtlValidAcl (PACL Acl)
NTSYSAPI NTSTATUS NTAPI RtlValidateUnicodeString (IN ULONG Flags, IN const UNICODE_STRING *String)
NTSYSAPI BOOLEAN NTAPI RtlValidRelativeSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptorInput, IN ULONG SecurityDescriptorLength, IN SECURITY_INFORMATION RequiredInformation)
NTSYSAPI BOOLEAN NTAPI RtlValidSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSYSAPI BOOLEAN NTAPI RtlValidSid (PSID Sid)
NTSYSAPI NTSTATUS RtlVerifyVersionInfo (IN PRTL_OSVERSIONINFOEXW VersionInfo, IN ULONG TypeMask, IN ULONGLONG ConditionMask)
NTSYSAPI NTSTATUS NTAPI RtlVolumeDeviceToDosName (IN PVOID VolumeDeviceObject, OUT PUNICODE_STRING DosName)
NTSYSAPI ULONG NTAPI RtlWalkFrameChain (OUT PVOID *Callers, IN ULONG Count, IN ULONG Flags)
NTSYSAPI NTSTATUS NTAPI RtlWriteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength)
NTSYSAPI ULONG NTAPI RtlxAnsiStringToUnicodeSize (PCANSI_STRING AnsiString)
NTSYSAPI ULONG NTAPI RtlxOemStringToUnicodeSize (PCOEM_STRING OemString)
NTSYSAPI ULONG NTAPI RtlxUnicodeStringToAnsiSize (PCUNICODE_STRING UnicodeString)
NTSYSAPI ULONG NTAPI RtlxUnicodeStringToOemSize (PCUNICODE_STRING UnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlZeroHeap (IN PVOID HeapHandle, IN ULONG Flags)
NTSYSAPI ULONGLONG NTAPI VerSetConditionMask (IN ULONGLONG ConditionMask, IN ULONG TypeMask, IN UCHAR Condition)
typedef VOID (NTAPI *PRTL_AVL_FREE_ROUTINE)(struct _RTL_AVL_TABLE *Table
Variables
BOOLEAN NLS_MB_CODE_PAGE_TAG
BOOLEAN NLS_MB_OEM_CODE_PAGE_TAG
* PRTL_BACKOFF
RTL_BACKOFF
const PRTL_ALLOCATE_STRING_ROUTINE RtlAllocateStringRoutine
const PRTL_FREE_STRING_ROUTINE RtlFreeStringRoutine
Macro Definition Documentation
#define __IID_ALIGNED__
Definition at line 3268 of file ntrtl.h.
#define _SLIST_ENTRY _SINGLE_LIST_ENTRY
Definition at line 120 of file ntrtl.h.
#define _SLIST_HEADER_
Definition at line 96 of file ntrtl.h.
#define ASSERT (exp) ((void) 0)
Definition at line 286 of file ntrtl.h.
Referenced by __bcount(), __out_bcount(), CcAcquireBcbSpinLockAndVacbLock(), CcAcquireByteRangeForWrite(), CcAdjustVacbLevelLockCount(), CcAllocateInitializeBcb(), CcAllocateVacbLevel(), CcCopyRead(), CcCopyReadExceptionFilter(), CcCreateVacbArray(), CcDeleteBcbs(), CcDeleteSharedCacheMap(), CcDereferenceFileOffset(), CcExtendVacbArray(), CcFastCopyRead(), CcFastCopyWrite(), CcFindBcb(), CcFindBitmapRangeToClean(), CcFindBitmapRangeToDirty(), CcFlushCache(), CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetBcbListHeadLargeOffset(), CcGetFlushedValidData(), CcGetVacbLargeOffset(), CcGetVacbMiss(), CcGetVirtualAddress(), CcGetVirtualAddressIfMapped(), CcInitializeCacheMap(), CcLogError(), CcMapAndCopy(), CcMapDataCommon(), CcMdlRead(), CcMdlWriteComplete2(), CcPerfFileRunDown(), CcPinFileData(), CcPostWorkQueue(), CcPurgeAndClearCacheSection(), CcPurgeCacheSection(), CcReferenceFileOffset(), CcReleaseByteRangeFromWrite(), CcRemapBcb(), CcScheduleReadAhead(), CcSetBcbOwnerPointer(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcSetFileSizes(), CcSetVacbLargeOffset(), CcUninitializeCacheMap(), CcUnmapVacb(), CcUnpinFileDataEx(), CcUnpinRepinnedBcb(), CcWorkerThread(), CcZeroData(), CcZeroEndOfLastPage(), CmCompressKey(), CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmEnumerateValueKey(), CmFlushKey(), CmGetSystemControlValues(), CmIsLastKnownGoodBoot(), CmLoadKey(), CmLockKcbForWrite(), CmMoveKey(), CmNotifyRunDown(), CmpAcquireFileObjectForFile(), CmpAddAliasEntry(), CmpAddDriverToList(), CmpAddSecurityCellToCache(), CmpAddSubKey(), CmpAddToDelayedClose(), CmpAddToDelayedDeref(), CmpAddToLeaf(), CmpAddValueToList(), CmpAllocateDelayItem(), CmpAllocateKeyControlBlock(), CmpAllocatePostBlock(), CmpAssignSecurityDescriptor(), CmpAssignSecurityDescriptorWrapper(), CmpBuildAndLockKcbArray(), CmpBuildHashStackAndLookupCache(), CmpBuildSecurityCellMappingArray(), CmpCacheLookup(), CmpCallCallBacks(), CmpCancelSlavePost(), CmpCheckKey(), CmpCheckRegistry2(), CmpCleanUpKCBCacheTable(), CmpCleanUpKcbCacheWithLock(), CmpCleanUpSubKeyInfo(), CmpCompareNewValueDataAgainstKCBCache(), CmpCompressKeyWorker(), CmpComputeHashKey(), CmpComputeKcbConvKey(), CmpConstructName(), CmpCopyCell(), CmpCopyKeyPartial(), CmpCopyValue(), CmpCreateControlSet(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpCreatePredefined(), CmpCreateRegistryRoot(), CmpDelayCloseDpcRoutine(), CmpDelayCloseWorker(), CmpDelayDerefKCBDpcRoutine(), CmpDelayDerefKCBWorker(), CmpDelayedDerefKeys(), CmpDeleteKeyObject(), CmpDereferenceNameControlBlockWithLock(), CmpDestroyHive(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDoCreate(), CmpDoCreateChild(), CmpDoFileSetSize(), CmpDoFindSubKeyByNumber(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpDoOpen(), CmpDoQueueLateUnloadWorker(), CmpDoSort(), CmpDropFileObjectForHive(), CmpDumpKeyBodyList(), CmpDuplicateIndex(), CmpDuplicateKey(), CmpFileFlush(), CmpFileRead(), CmpFileSetSize(), CmpFileWrite(), CmpFileWriteThroughCache(), CmpFindControlSet(), CmpFindDrivers(), CmpFindNameInList(), CmpFindNLSData(), CmpFindProfileOption(), CmpFindReusableCellFromCache(), CmpFindSecurityCellCacheIndex(), CmpFindSubKeyByHash(), CmpFindSubKeyByName(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), CmpFindTagIndex(), CmpFindValueByName(), CmpFindValueByNameFromCache(), CmpFixHiveUsageCount(), CmpFlushNotifiesOnKeyBodyList(), CmpFree(), CmpFreeAllMemory(), CmpFreeCmView(), CmpFreeDelayItem(), CmpFreeKeyBody(), CmpFreeKeyByCell(), CmpFreeKeyControlBlock(), CmpFreeKeyValues(), CmpFreePostBlock(), CmpFreeSlavePost(), CmpFreeValue(), CmpFreeValueData(), CmpGetHiveName(), CmpGetKeySecurity(), CmpGetSymbolicLink(), CmpGetValueData(), CmpGetValueDataFromCache(), CmpHiveRootSecurityDescriptor(), CmpInitializeHardwareConfiguration(), CmpInitializeHive(), CmpInitializeHiveList(), CmpInitializeRegistryNode(), CmpIsLoadType(), CmpKCBLockForceAcquireAllowed(), CmpKeyInfoProbeAlingment(), CmpLateUnloadHiveWorker(), CmpLinkHiveToMaster(), CmpLoadHiveThread(), CmpLoadHiveVolatile(), CmpLockRegistryExclusive(), CmpMapCmView(), CmpMapThisBin(), CmpMarkIndexDirty(), CmpMarkKeyDirty(), CmpMarkKeyValuesDirty(), CmpMergeKeyValues(), CmpNameFromAttributes(), CmpNotifyChangeKey(), CmpNotifyTriggerCheck(), CmpOKToFollowLink(), CmpOverwriteHive(), CmpParseKey(), CmpPinCmView(), CmpPostNotify(), CmpPrefetchHiveFile(), CmpQueryKeyDataFromCache(), CmpQueryKeyValueData(), CmpRebuildKcbCache(), CmpReferenceKeyControlBlock(), CmPrefetchHivePages(), CmpRefreshHive(), CmpRehashKcbSubtree(), CmpRemoveFromDelayedClose(), CmpRemoveFromSecurityCache(), CmpRemoveKeyHash(), CmpRemoveSecurityCellList(), CmpRemoveSubKey(), CmpRemoveSubKeyCellNoCellRef(), CmpRemoveValueFromList(), CmpReportNotify(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), CmpSearchKeyControlBlockTree(), CmpSecurityMethod(), CmpSelectLeaf(), CmpSetCurrentProfile(), CmpSetNetworkValue(), CmpSetSecurityDescriptorInfo(), CmpSetSystemValues(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpShiftAllCells(), CmpShiftAllCells2(), CmpShiftHiveFreeBins(), CmpShiftIndex(), CmpShiftKey(), CmpShiftSecurityCells(), CmpShiftValueList(), CmpSortDriverList(), CmpSplitLeaf(), CmpSwitchStorageAndRebuildMappings(), CmpSyncKeyValues(), CmpTouchView(), CmpTryConvertKCBLockSharedToExclusive(), CmpTryToLockHashEntryByIndexExclusive(), CmpUnmapCmView(), CmpUnmapCmViewSurroundingOffset(), CmpUnmapUnusedViews(), CmpUnPinCmView(), CmpUpdateParentForEachSon(), CmpUpdateSystemHiveHysteresis(), CmpValidateHiveSecurityDescriptors(), CmpValidateSelect(), CmpValueToData(), CmpWalkPath(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRenameKey(), CmRestoreKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetValueKey(), CmUnloadKey(), CmUnloadKeyEx(), DbgkpConvertKernelToUserStateChange(), DbgkpDeleteObject(), DbgkpPostFakeModuleMessages(), DeleteNodeFromTree(), DelistKeyBodyFromKCB(), EnlistKeyBodyWithKCB(), ExAcquirePushLockExclusive(), ExAcquirePushLockShared(), ExAcquireReleasePushLockExclusive(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExAllocateCacheAwareRundownProtection(), ExAllocateFromPPLookasideList(), ExConvertExclusiveToSharedLite(), ExConvertPushLockExclusiveToShared(), ExCreatePoolTagTable(), ExDeferredFreePool(), ExDeletePoolTagTable(), ExDeleteResourceLite(), ExDereferenceHandleDebugInfo(), ExEnableHandleTracing(), ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExFastRefAddAdditionalReferenceCounts(), ExFastRefCompareSwapObject(), ExFastRefDereference(), ExFastRefInitialize(), ExFastRefInitializeEx(), ExFastRefSwapObject(), ExfConvertPushLockExclusiveToShared(), ExFreeCacheAwareRundownProtection(), ExFreePoolWithTag(), ExFreeToPPLookasideList(), ExfReInitializeRundownProtection(), ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExfReleaseRundownProtection(), ExfRundownCompleted(), ExfTryAcquirePushLockShared(), ExfWaitForRundownProtectionRelease(), ExfWakePushLock(), ExGetBigPoolInfo(), ExGetPoolTagInfo(), ExGetSessionPoolTagInfo(), ExInitializeResourceLite(), ExInsertPoolTag(), ExLockUserBuffer(), ExpAddTagForBigPages(), ExpDeleteCallback(), ExpDetectWorkerThreadDeadlock(), ExpFindAndRemoveTagBigPages(), ExpFindEmptyEntry(), ExpGetPoolTagInfoTarget(), ExpInitializeExecutive(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpLockHandleTableEntry(), ExpOptimizePushLockList(), ExpProfileDelete(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), ExpSeedHotTags(), ExpShutdownWorker(), ExpShutdownWorkerThreads(), ExpSystemErrorHandler(), ExpUpdateDebugInfo(), ExpUuidGetValues(), ExpWin32CloseProcedure(), ExpWin32DeleteProcedure(), ExpWin32OkayToCloseProcedure(), ExpWin32OpenProcedure(), ExpWin32ParseProcedure(), ExpWin32SessionCallout(), ExpWorkerThread(), ExpWorkerThreadBalanceManager(), ExQueueWorkItem(), ExReferenceHandleDebugInfo(), ExRegisterCallback(), ExReinitializeResourceLite(), ExReInitializeRundownProtection(), ExReInitializeRundownProtectionCacheAware(), ExReleasePushLock(), ExReleasePushLockExclusive(), ExReleasePushLockShared(), ExReleasePushLockSharedAssumeSingleOwner(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExReleaseRundownProtection(), ExReleaseRundownProtectionEx(), ExReleaseSpinLockExclusive(), ExReleaseSpinLockShared(), ExRundownCompleted(), ExRundownCompletedCacheAware(), ExSetResourceOwnerPointer(), ExTryAcquirePushLockExclusive(), ExTryAcquirePushLockShared(), ExTryAcquireSpinLockExclusive(), ExTryConvertPushLockSharedToExclusive(), ExTryToAcquireResourceExclusiveLite(), ExUnlockHandleTableEntry(), ExUnregisterCallback(), ExUuidCreate(), ExWaitForRundownProtectionReleaseCacheAware(), FindNodeOrParent(), FsFilterAllocateCompletionStack(), FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlAcknowledgeOplockBreak(), FsRtlAcquireFileExclusive(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlush(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlAddBaseMcbEntry(), FsRtlBalanceReads(), FsRtlCancelNotify(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlCreateSectionForDataScan(), FsRtlDeregisterUncProvider(), FsRtlFindFirstOverlapInNode(), FsRtlFindInTunnelCache(), FsRtlGetCompatibilityModeValue(), FsRtlGetTunnelParameterValue(), FsRtlInsertPerFileObjectContext(), FsRtlIsDbcsInExpression(), FsRtlIsFatDbcsLegal(), FsRtlIsNameInExpressionPrivate(), FsRtlLookupPerStreamContextInternal(), FsRtlMdlReadDev(), FsRtlNotifyFilterReportChange(), FsRtlNotifyUpdateBuffer(), FsRtlNotifyVolumeEvent(), FsRtlpRegisterProviderWithMUP(), FsRtlPrepareMdlWriteDev(), FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertLock(), FsRtlPrivateInsertSharedLock(), FsRtlPrivateRemoveLock(), FsRtlProcessFileLock(), FsRtlpSetSymbolicLink(), FsRtlPTeardownPerFileObjectContexts(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), FsRtlReleaseFileForModWrite(), FsRtlRequestExclusiveOplock(), FsRtlSplitLocks(), FsRtlTeardownPerStreamContexts(), HalExamineMBR(), HalpQueryDriveLayout(), HvAllocateCell(), HvCheckHive(), HvCloneHive(), HvDuplicateCell(), HvFreeCell(), HvFreeHive(), HvFreeHivePartial(), HvHiveWillShrink(), HvIsCellAllocated(), HvLoadHive(), HvMapHive(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpAllocateMap(), HvpBuildMapAndCopy(), HvpDelistBinFreeCells(), HvpDelistFreeCell(), HvpDoAllocateCell(), HvpDoWriteHive(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistBinInMap(), HvpEnlistFreeCell(), HvpEnlistFreeCells(), HvpFindFreeCell(), HvpFindFreeCellInBin(), HvpFindFreeCellInThisViewWindow(), HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpFreeAllocatedBins(), HvpFreeHiveFreeDisplay(), HvpGetBinMemAlloc(), HvpGetCellFlat(), HvpGetCellMap(), HvpGetCellMapped(), HvpGetCellPaged(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpGrowLog1(), HvpGrowLog2(), HvpIsFreeNeighbor(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpRecoverWholeHive(), HvpReleaseCellMapped(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), HvpWriteLog(), HvReallocateCell(), HvRefreshHive(), HvReleaseFreeCellRefArray(), HvShiftCell(), HvShrinkHive(), HvSyncHive(), HvTrackCellRef(), HvWriteHive(), InitializePool(), IoAllocateMdl(), IoCancelFileOpen(), IoCancelIrp(), IoCreateDevice(), IoCreateFile(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IoCsqInsertIrpEx(), IoCsqRemoveIrp(), IoCsqRemoveNextIrp(), IoDetachDevice(), IoFreeWorkItem(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), IoInitSystem(), IoIsValidNameGraftingBuffer(), IopAttachDeviceToDeviceStackSafe(), IopCompleteRequest(), IopCompleteUnloadOrDelete(), IopCreateDefaultDeviceSecurityDescriptor(), IopCreateFile(), IopCreateSecurityDescriptorPerType(), IopCsqCancelRoutine(), IopDecrementDeviceObjectRef(), IopDeleteDevice(), IopDeleteDriver(), IopDeleteFile(), IopDoNameTransmogrify(), IopfCallDriver(), IopfCompleteRequest(), IopFreeIrp(), IopGetDevicePDO(), IopGetRegistryValue(), IopGetVolumeId(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopQueryNameInternal(), IopSetDeviceSecurityDescriptors(), IopStoreSystemPartitionInformation(), IopSynchronousServiceTail(), IopVerifyDeviceObjectOnStack(), IoQueueWorkItem(), IoRetryIrpCompletions(), IoReuseIrp(), IoSetSystemPartition(), IoUnregisterShutdownNotification(), IoVerifyVolume(), IoVolumeDeviceToDosName(), Ke386CallBios(), KeAcquireGuardedMutex(), KeAcquireGuardedMutexUnsafe(), KeAlertResumeThread(), KeAlertThread(), KeAttachProcess(), KeBoostPriorityThread(), KeBugCheck2(), KeCancelTimer(), KeConnectInterrupt(), KeContextToKframes(), KeDelayExecutionThread(), KeDeregisterNmiCallback(), KeDetachProcess(), KeDisconnectInterrupt(), KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeFindNextRightSetAffinity(), KeFlushMultipleTb(), KeFlushQueueApc(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeGenericCallDpc(), KeGetPrcb(), KeInitializeApc(), KeInitializeProfile(), KeInsertHeadQueue(), KeInsertQueue(), KeInsertQueueApc(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), KeNumaInitialize(), KePulseEvent(), KeQueryBasePriorityThread(), KeQueryPrcbAddress(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeReadyThread(), KeRegisterNmiCallback(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), KeReleaseMutant(), KeReleaseSemaphore(), KeRemoveByKeyDeviceQueue(), KeRemoveDeviceQueue(), KeRemoveEntryDeviceQueue(), KeRemoveQueue(), KeRemoveQueueApc(), KeResetEvent(), KeRestoreFloatingPointState(), KeRestoreMtrr(), KeResumeThread(), KeRevertToUserAffinityThread(), KeRundownQueue(), KeRundownThread(), KeSaveFloatingPointState(), KeSetAffinityProcess(), KeSetAffinityThread(), KeSetBasePriorityThread(), KeSetEvent(), KeSetEventBoostPriority(), KeSetIdealProcessorThread(), KeSetPhysicalCacheTypeRange(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeSetProcess(), KeSetProfileIrql(), KeSetQuantumProcess(), KeSetSystemAffinityThread(), KeSetSystemTime(), KeSetTimerEx(), KeSignalGateBoostPriority(), KeStackAttachProcess(), KeStartAllProcessors(), KeStartProfile(), KeStartThread(), KeStopProfile(), KeSuspendThread(), KeTerminateThread(), KeTestAlertThread(), KeThawAllThreads(), KeTryToAcquireGuardedMutex(), KeUnstackDetachProcess(), KeUserModeCallback(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), Ki386ConvertPte(), KiAcquireFastMutex(), KiAcquireGuardedMutex(), KiAcquireInStackQueuedSpinLockForDpc(), KiAcquireKobjectLock(), KiAcquirePrcbLock(), KiAcquireSpinLockForDpc(), KiAcquireThreadLock(), KiAcquireTimerTableLock(), KiAcquireTwoPrcbLocks(), KiAdjustSimultaneousMultiThreadingCharacteristics(), KiAmdK6MTRRAddRegionFromHW(), KiAttachProcess(), KiClearTbFlushTimeStampBusy(), KiCloneSelector(), KiCompleteEffectiveRangeChange(), KiComputeNewPriority(), KiDeferredReadyThread(), KiDispatchException(), KiExecuteDpc(), KiExitDispatcher(), KiFindFirstSetLeftBit(), KiFindFirstSetRightBit(), KiFindReadyThread(), KiI386PentiumLockErrataFixup(), KiIdleSchedule(), KiInitializePAT(), KiInitializeUserApc(), KiInsertQueueApc(), KiInsertTimerTable(), KiInSwapKernelStacks(), KiIpiProcessRequests(), KiIpiSendPacket(), KiIpiSendRequest(), KiIpiStallOnPacketTargetsPrcb(), KiLockStepOtherProcessors(), KiOpDecode(), KiOpPatchCode(), KiOpRetrieveRegMemAddress(), KiOutSwapKernelStacks(), KiProcessDebugRegister(), KiProcessDeferredReadyList(), KiReadyThread(), KiRecordDr7(), KiReleaseInStackQueuedSpinLockForDpc(), KiReleaseKobjectLock(), KiReleasePrcbLock(), KiReleaseSpinLockForDpc(), KiReleaseThreadLock(), KiReleaseTimerTableLock(), KiReleaseTwoPrcbLocks(), KiRetireDpcList(), KiScanReadyQueues(), KiSelectNextThread(), KiSelectReadyThread(), KiSetAffinityThread(), KiSetCacheInformationIntel(), KiSetContextSwapBusy(), KiSetContextSwapIdle(), KiSetIdealNodeProcess(), KiSetPriorityThread(), KiSwapProcess(), KiSwapThread(), KiTimedChainedDispatch2ndLvl(), KiTimerExpiration(), KiTryToAcquireThreadLock(), KiUnwaitThread(), KiUpdateDr7(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), KxQueueReadyThread(), KxReleaseQueuedSpinLock(), KxReleaseSpinLock(), LpcExitThread(), MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MI_REMOVE_LOCKED_PAGE_CHARGE(), MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_CACHETYPE_TRANSLATION(), MI_TRANSLATE_CACHETYPE(), MiAccessCheck(), MiAddCachedRange(), MiAddExpansionNonPagedPool(), MiAddExtraSystemPteRanges(), MiAddHalIoMappings(), MiAddMappedPtes(), MiAddMdlTracker(), MiAddSystemPtes(), MiAddValidPageToWorkingSet(), MiAddViewsForSection(), MiAddViewsForSectionWithPfn(), MiAddWorkingSetPage(), MiAddWsleHash(), MiAgeWorkingSet(), MiAllocateAweInfo(), MiAllocateContiguousMemory(), MiAllocateLargePages(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiAllocatePoolPages(), MiAllocateVad(), MiAllocateWsle(), MiAllowWorkingSetExpansion(), MiAppendSubsectionChain(), MiAttachAndLockWorkingSet(), MiAttachSession(), MiAttemptPageFileExtension(), MiAttemptPageFileReduction(), MiAweViewInserter(), MiAweViewRemover(), MiBuildImportsForBootDrivers(), MiBuildPagedPool(), MiCallDllUnloadAndUnloadDll(), MiCanFileBeTruncatedInternal(), MiCaptureWriteWatchDirtyBit(), MiCcCompletePrefetchIos(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiChargeCommitment(), MiChargeCommitmentCantExpand(), MiChargeTemporaryCommitmentForReduction(), MiCheckCacheAttributes(), MiCheckControlArea(), MiCheckControlAreaStatus(), MiCheckForConflictingNode(), MiCheckForContiguousMemory(), MiCheckForControlAreaDeletion(), MiCheckForUserStackOverflow(), MiCheckPteRelease(), MiCheckPteReserve(), MiCheckPurgeAndUpMapCount(), MiCheckSessionPoolAllocations(), MiCleanPhysicalProcessPages(), MiCleanSection(), MiCloneProcessAddressSpace(), MiCompleteProtoPteFault(), MiComputeInitialLargePage(), MiComputeSystemTrimCriteria(), MiConvertStaticSubsections(), MiCopyHeaderIfResident(), MiCopyOnWrite(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreatePageTablesForPhysicalRange(), MiCreatePagingFileMap(), MiCreatePhysicalVadRoot(), MiDecommitPages(), MiDecrementCloneBlockReference(), MiDecrementReferenceCount(), MiDecrementReferenceCountForAwePage(), MiDecrementShareCount(), MiDecrementSubsections(), MiDeferredUnlockPages(), MiDeleteAddressesInWorkingSet(), MiDeletePageTablesForPhysicalRange(), MiDeletePte(), MiDeletePteList(), MiDeletePteRange(), MiDeleteSystemPageableVm(), MiDeleteValidSystemPte(), MiDeleteVirtualAddresses(), MiDereferenceImports(), MiDereferenceLastChanceLdw(), MiDereferenceSegmentThread(), MiDereferenceSession(), MiDereferenceSessionFinal(), MiDetachAndUnlockWorkingSet(), MiDetachSession(), MiDetermineUserGlobalPteMask(), MiDispatchFault(), MiDoesPdeExistAndMakeValid(), MiDoMappedCopy(), MiDoPoolCopy(), MiDoReplacement(), MiEliminateWorkingSetEntry(), MiEmptyWorkingSet(), MiEnablePagingOfDriverAtInit(), MiEnablePagingTheExecutive(), MiEnsureAvailablePageOrWait(), MiExtendPagingFileMaximum(), MiExtendPagingFiles(), MiFillSystemPageDirectory(), MiFillWsleHash(), MiFindContiguousMemory(), MiFindContiguousMemoryInPool(), MiFindContiguousPages(), MiFindEmptyAddressRangeDownBasedTree(), MiFindEmptyAddressRangeDownTree(), MiFindEmptyAddressRangeInTree(), MiFindExportedRoutineByName(), MiFindImageSectionObject(), MiFindInitializationCode(), MiFindLargePageMemory(), MiFindNodeOrParent(), MiFinishPageFileExtension(), MiFlushAcquire(), MiFlushComplete(), MiFlushDirtyBitsToPfn(), MiFlushPteList(), MiFlushPteListFreePfns(), MiFlushRelease(), MiFlushSectionInternal(), MiFlushTbAndCapture(), MiFreeAllExpansionNonPagedPool(), MiFreeContiguousPages(), MiFreeEventCounter(), MiFreeInitializationCode(), MiFreeInPageSupportBlock(), MiFreeLargePageMemory(), MiFreeLargePages(), MiFreeMdlTracker(), MiFreeNonPagedPool(), MiFreePoolPages(), MiFreeWsle(), MiFreeWsleList(), MiGatherMappedPages(), MiGatherPagefilePages(), MiGetEventCounter(), MiGetFirstNode(), MiGetInPageSupportBlock(), MiGetNextNode(), MiGetPageForHeader(), MiGetPageProtection(), MiGetPreviousNode(), MiGetProtoPteAddressExtended(), MiGetSubsectionAndProtoFromPte(), MiGetSystemPteAvailability(), MiGetSystemPteListCount(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiGrowWsleHash(), MiHandleForkTransitionPte(), MiIdentifyPfn(), MiInitializeAndChargePfn(), MiInitializeCopyOnWritePfn(), MiInitializeLargePageSupport(), MiInitializeMemoryEvents(), MiInitializeNonPagedPool(), MiInitializeNonPagedPoolThresholds(), MiInitializePfn(), MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), MiInitializeReadInProgressPfn(), MiInitializeReadInProgressSinglePfn(), MiInitializeSessionIds(), MiInitializeSessionPool(), MiInitializeSystemPtes(), MiInitializeSystemSpaceMap(), MiInitializeTransitionPfn(), MiInitializeVadTableAvl(), MiInitializeWorkingSetList(), MiInitMachineDependent(), MiInPageSingleKernelStack(), MiInsertAweInfo(), MiInsertBasedSection(), MiInsertFrontModifiedNoWrite(), MiInsertHandBuiltProcessIntoList(), MiInsertImageSectionObject(), MiInsertInSystemSpace(), MiInsertIoSpaceMap(), MiInsertNode(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertPhysicalViewAndRefControlArea(), MiInsertPteTracker(), MiInsertStandbyListAtFront(), MiInsertVad(), MiInsertVadCharges(), MiInsertWsleHash(), MiInsertZeroListAtBack(), MiIsPoolLargeSession(), MiIsProbeActive(), MiIsProtoAddressValid(), MiIssuePageExtendRequestNoWait(), MiLoadImageSection(), MiLocateAddress(), MiLocateSubsection(), MiLocateWsle(), MiLockCode(), MiLookupDataTableEntry(), MiMakeEntireImageCopyOnWrite(), MiMakeOutswappedPageResident(), MiMakePdeExistAndMakeValid(), MiMakeProtectionMask(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MiMapBBTMemory(), MiMapLargePageSection(), MiMapLockedPagesInUserSpace(), MiMapPageInHyperSpace(), MiMapPageInHyperSpaceAtDpc(), MiMapPagesToZeroInHyperSpace(), MiMapSinglePage(), MiMapViewInSystemSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiMapWithLargePages(), MiMarkImageInSystem(), MiMarkPoolLargeSession(), MiMarkSectionWritable(), MiModifiedPageWriterWorker(), MiNoPagesLastChance(), MiOutPageSingleKernelStack(), MiPhysicalViewAdjuster(), MiPhysicalViewRemover(), MiProcessValidPteList(), MiProcessWorkingSets(), MiPromoteNode(), MiProtectAweRegion(), MiProtectVirtualMemory(), MiPteSListExpansionWorker(), MiPurgeImageSection(), MiPurgeTransitionList(), MiQueryAddressState(), MiQueueWorkingSetRequest(), MiRealSuccessor(), MiRebalanceNode(), MiReferenceSubsection(), MiReleaseAllMemory(), MiReleaseConfirmedPageFileSpace(), MiReleasePageFileSpace(), MiReleasePhysicalCharges(), MiReleaseProcessReferenceToSessionDataPage(), MiReleaseSplitSystemPtes(), MiReleaseSystemPtes(), MiReleaseWsle(), MiReloadBootLoadedDrivers(), MiRemoveAnyPage(), MiRemoveCachedRange(), MiRemoveImageSectionObject(), MiRemoveImageSessionWide(), MiRemoveMappedPtes(), MiRemoveMappedView(), MiRemoveNode(), MiRemovePageByColor(), MiRemovePageFromList(), MiRemovePageFromWorkingSet(), MiRemoveUnusedSegments(), MiRemoveUserPhysicalPagesVad(), MiRemoveVad(), MiRemoveVadCharges(), MiRemoveViewsFromSection(), MiRemoveViewsFromSectionWithPfn(), MiRemoveWorkingSetPages(), MiRemoveWsle(), MiRemoveWsleFromFreeList(), MiRemoveZeroPage(), MiRepointWsleHashIndex(), MiReportPhysicalMemory(), MiReserveAlignedSystemPtes(), MiReserveSystemPtes(), MiResetVirtualMemory(), MiResolveDemandZeroFault(), MiResolveImageReferences(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveProtoPteFault(), MiResolveTransitionFault(), MiRestoreTransitionPte(), MiReturnLargePages(), MiReturnPageTablePageCommitment(), MiSectionDelete(), MiSectionInitialization(), MiSecureVirtualMemory(), MiSegmentDelete(), MiSessionAddProcess(), MiSessionCommitPageTables(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), MiSessionPageTableRelease(), MiSessionPoolBigPageTable(), MiSessionPoolBigPageTableSize(), MiSessionPoolLookaside(), MiSessionPoolTrackTable(), MiSessionPoolTrackTableSize(), MiSessionProcessGlobalSubsections(), MiSessionRemoveImage(), MiSessionRemoveProcess(), MiSessionUnloadAllImages(), MiSessionWideReserveImageAddress(), MiSetPageModified(), MiSetPagingOfDriver(), MiSetProtectionOnSection(), MiSetSystemCodeProtection(), MiShareSessionImage(), MiShutdownSystem(), MiStartingOffset(), MiSwapWslEntries(), MiTerminateWsle(), MiTrimAllSystemPageableMemory(), MiTrimPte(), MiTrimWorkingSet(), MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MiUnlinkWorkingSet(), MiUnlockPagedAddress(), MiUnmapLargePages(), MiUnmapLockedPagesInUserSpace(), MiUnmapPagesInZeroSpace(), MiUnmapSinglePage(), MiUnmapViewOfSection(), MiUnsecureVirtualMemory(), MiUpdateLargeProtoPfns(), MiUpdateMdlTracker(), MiUpdateModifiedWriterMdls(), MiUpdateSystemPdes(), MiUpdateWsle(), MiUseLargeDriverPage(), MiWaitForInPageComplete(), MiWriteComplete(), MiWriteProtectSystemImage(), MiZeroAllPageFiles(), MiZeroAwePageWorker(), MiZeroInParallel(), MiZeroPageWorker(), MmAccessFault(), MmAdjustWorkingSetSizeEx(), MmAdvanceMdl(), MmAllocateIndependentPages(), MmAttachSession(), MmAvailablePoolInPages(), MmBuildMdlForNonPagedPool(), MmCheckCachedPageState(), MmCleanProcessAddressSpace(), MmCommitSessionMappedView(), MmCopyToCachedPage(), MmCopyVirtualMemory(), MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmCreateSection(), MmCreateTeb(), MmDeleteKernelStack(), MmDeleteProcessAddressSpace(), MmDeleteTeb(), MmDetachSession(), MmExtendSection(), MmFlushImageSection(), MmFlushSection(), MmFlushVirtualMemory(), MmForceSectionClosed(), MmFreeBootRegistry(), MmFreeContiguousMemory(), MmFreeDriverInitialization(), MmFreeIndependentPages(), MmFreeLoaderBlock(), MmFreeMappingAddress(), MmFreeNonCachedMemory(), MmFreePagesFromMdl(), MmGetDirectoryFrameFromProcess(), MmGetExecuteOptions(), MmGetFileNameForAddress(), MmGetFileObjectForSection(), MmGetImageInformation(), MmGetNextSession(), MmGetPreviousSession(), MmGetSessionById(), MmGetSizeOfBigPoolAllocation(), MmGetSystemRoutineAddress(), MmGrowKernelStackEx(), MmIdentifyPhysicalMemory(), MmInitializeHandBuiltProcess(), MmInitializeHandBuiltProcess2(), MmInitializeMemoryLimits(), MmInitializeProcessAddressSpace(), MmInitSystem(), MmInPageKernelStack(), MmInSwapProcess(), MmIsIoSpaceActive(), MmIsMemoryAvailable(), MmLoadSystemImage(), MmLockPageableSectionByHandle(), MmMapLockedPagesSpecifyCache(), MmMapLockedPagesWithReservedMapping(), MmMapMemoryDumpMdl(), MmMapUserAddressesToPage(), MmMapViewInSessionSpace(), MmMapViewInSystemCache(), MmOutPageKernelStack(), MmOutSwapProcess(), MmPageEntireDriver(), MmPerfSnapShotValidPhysicalMemory(), MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), MmPrefetchPagesIntoLockedMdl(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmQuerySystemCacheWorkingSetInformation(), MmQueryWorkingSetInformation(), MmQuitNextSession(), MmResetDriverPaging(), MmResourcesAvailable(), MmSessionCreate(), MmSessionDelete(), MmSessionSetUnloadAddress(), MmSetBankedSection(), MmSetExecuteOptions(), MmSetPageProtection(), MmShutdownSystem(), MmUnloadSystemImage(), MmUnlockCachedPage(), MmUnlockPageableImageSection(), MmUnlockPagedPool(), MmUnlockPages(), MmUnmapIoSpace(), MmUnmapLockedPages(), MmUnmapReservedMapping(), MmUnmapViewInSessionSpace(), MmUnmapViewInSystemCache(), MmUpdateMdlTracker(), MmWorkingSetManager(), MmZeroPageThread(), MxConvertToLargePage(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtAssignProcessToJobObject(), NtCloseObjectAuditAlarm(), NtCreateKey(), NtCreatePagingFile(), NtCreateSection(), NtDeleteObjectAuditAlarm(), NtDuplicateToken(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockFile(), NtLockVirtualMemory(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtNotifyChangeMultipleKeys(), NtOpenObjectAuditAlarm(), NtOpenThreadTokenEx(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryInformationToken(), NtQueryObject(), NtQueryVirtualMemory(), NtReadFile(), NtReadFileScatter(), NtReleaseKeyedEvent(), NtResetWriteWatch(), NtSetInformationFile(), NtSetInformationKey(), NtSetInformationToken(), NtSetSecurityObject(), NtSetSystemInformation(), NtSetUuidSeed(), NtSetVolumeInformationFile(), NtStartProfile(), NtStopProfile(), NtUnloadKey2(), NtUnlockVirtualMemory(), NtWaitForKeyedEvent(), NtWriteFile(), NtWriteFileGather(), NtYieldExecution(), ObAssignObjectSecurityDescriptor(), ObAuditObjectAccess(), ObDereferenceSecurityDescriptor(), ObfDereferenceObject(), ObfReferenceObject(), ObInitSystem(), ObInsertObject(), OBJECT_HEADER_TO_HANDLE_INFO_EXISTS(), OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), ObKillProcess(), ObpCompareSecurityDescriptors(), ObpCreateCacheEntry(), ObpCreateTypeArray(), ObpDecrementHandleCount(), ObpDestroySecurityDescriptorHeader(), ObpFreeDosDevicesProtection(), ObpGetDosDevicesProtection(), ObpLookupObjectName(), ObpReferenceProcessObjectByHandle(), ObpShutdownCloseHandleProcedure(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), ObSetSecurityObjectByPointer(), ObShutdownSystem(), PerfInfoAddToFileHash(), ProbeForRead(), ProbeForWrite(), ProbeForWriteSmallStructure(), PromoteNode(), PsChargeProcessPoolQuota(), PsChargeProcessQuota(), PsChargeSharedPoolQuota(), PsConvertToGuiThread(), PsDisableImpersonation(), PsGetContextThread(), PsImpersonateClient(), PspCreateLdt(), PspCreateProcess(), PspCreateThread(), PspDereferenceQuota(), PspExitNormalApc(), PspExitThread(), PspLockJobLimitsExclusiveUnsafe(), PspLockJobLimitsSharedUnsafe(), PspLockWorkingSetChangeExclusiveUnsafe(), PspQueryDescriptorThread(), PspQueryLdtInformation(), PspQueryQuotaLimits(), PspReaper(), PspReturnQuota(), PspSetLdtInformation(), PspSetLdtSize(), PspTerminateThreadByPointer(), PspThreadDelete(), PspUnlockJobLimitsExclusiveUnsafe(), PspUnlockJobLimitsSharedUnsafe(), PspUnlockWorkingSetChangeExclusiveUnsafe(), PspWin32SessionCallout(), PspWriteTebImpersonationInfo(), PsReferenceEffectiveToken(), PsReferenceImpersonationToken(), PsReferencePrimaryToken(), PsRestoreImpersonation(), PsReturnPoolQuota(), PsReturnProcessQuota(), PsRevertThreadToSelf(), PsSetContextThread(), PsSetLdtEntries(), PsSetProcessLdtInfo(), PsShutdownSystem(), RawCheckForDismount(), RawCleanup(), RawClose(), RawCreate(), RawUserFsCtrl(), RawVerifyVolume(), RealSuccessor(), ReferenceVacbLevel(), RtlAdjustPrivilege(), RtlClearBit(), RtlClearBits(), RtlCompareUnicodeString(), RtlCreateProcessParameters(), RtlDeleteElementGenericTableAvl(), RtlEnumerateGenericTableLikeADirectory(), RtlInitializeGenericTableAvl(), RtlInsertElementGenericTableFull(), RtlInsertElementGenericTableFullAvl(), RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), RtlpCopyEffectiveAce(), RtlpCopyProcString(), RtlpCreateServerAcl(), RtlpDidUnicodeToOemWork(), RtlpFindClearBitsRange(), RtlpFindClearRunInChunk(), RtlpFreeAtom(), RtlpGenerateInheritedAce(), RtlpLogExceptionHandler(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseInitializeLock(), RtlpTraceDatabaseReleaseLock(), RtlpTraceDatabaseUninitializeLock(), RtlpUnwindPrologue(), RtlRunEncodeUnicodeString(), RtlSelfRelativeToAbsoluteSD2(), RtlSetBit(), RtlSetBits(), RtlSetEnvironmentStrings(), RtlTestBit(), RtlValidateUnicodeString(), SeAccessCheckByType(), SeAddSaclToProcess(), SeAssignPrimaryToken(), SeAuditHandleCreation(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCaptureAuditPolicy(), SeCreateAccessStateEx(), SeDeassignPrimaryToken(), SeDefaultObjectMethod(), SeExchangePrimaryToken(), SeFastTraverseCheck(), SeInitializeProcessAuditName(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SeOperationAuditAlarm(), SepAccessCheck(), SepAccessCheckAndAuditAlarm(), SepAdtAuditThisEventWithContext(), SepAdtCloseObjectAuditAlarm(), SepAdtCopyToLsaSharedMemory(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtInitializePrivilegeAuditing(), SepAdtMarshallAuditRecord(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAppendDefaultDacl(), SepAppendPrimaryGroup(), SepAssemblePrivileges(), SepAuditAssignPrimaryToken(), SepAuditFailed(), SepConcatenatePrivileges(), SepCreateImpersonationTokenDacl(), SepCreateToken(), SepDeReferenceLogonSessionDirect(), SepDuplicateLogonSessionReference(), SepDuplicateToken(), SepFilterToken(), SepInformFileSystemsOfDeletedLogon(), SepInformLsaOfDeletedLogon(), SepInheritAcl(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), SepMakeTokenEffectiveOnly(), SepModifyTokenPolicyCounter(), SepObjectInTypeList(), SepRegQueryHelper(), SepRemoveDisabledGroupsAndPrivileges(), SePrivilegedServiceAuditAlarm(), SepRmCallLsa(), SepRmCommandServerThread(), SepRmCreateLogonSessionWrkr(), SepRmDbInitialization(), SepRmDeleteLogonSessionWrkr(), SepRmSetAuditEventWrkr(), SepSinglePrivilegeCheck(), SepTokenDeleteMethod(), SepTokenIsOwner(), SeQueryInformationToken(), SeReportSecurityEvent(), WmipAddLogHeader(), WmipCloseMethod(), WmipDeleteMethod(), WmipDeliverWnodeToDS(), WmipDisableCollectOrEvent(), WmipEnableCollectOrEvent(), WmipExtendBase(), WmipFirmwareTableHandler(), WmipFlushBuffer(), WmipFreeLoggerContext(), WmipFreeTraceBufferPool(), WmipGetDevicePDO(), WmipLogger(), WmipPopFreeContextSwapBuffer(), WmipPrepareHeader(), WmipPushDirtyBuffer(), WmipRawSMBiosTableHandler(), WmipReleaseTraceBuffer(), WmipReserveTraceBuffer(), WmipResetBufferHeader(), WmipSecurityMethod(), WmipSendEnableDisableRequest(), WmipStartLogger(), WmipTraceFile(), WmipTraceIo(), WmipUMProviderCallback(), WmipWriteMessageToGuid(), WmiTraceContextSwap(), WmiUpdateTrace(), xxAcquireFastMutex(), xxAcquireFastMutexUnsafe(), xxReleaseFastMutex(), xxReleaseFastMutexUnsafe(), and xxTryToAcquireFastMutex().
#define ASSERTMSG (msg, exp) ((void) 0)
Definition at line 287 of file ntrtl.h.
Referenced by _purecall(), CcLazyWriteScan(), CcMapDataForOverwrite(), CmpCreateControlSet(), ExCompareExchangeCallBack(), FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsRtlAddBaseMcbEntry(), FsRtlLookupBaseMcbEntry(), FsRtlNotifyFilterReportChange(), FsRtlRemoveLargeMcbEntry(), FsRtlSplitBaseMcb(), FsRtlTruncateBaseMcb(), IopDeleteDevice(), and SepInitializationPhase1().
#define CLEAR_PARSE_MESSAGE_CONTEXT_FLAG (ctx, flag) ((ctx)->fFlags &= ~(flag))
Definition at line 7002 of file ntrtl.h.
#define COMPRESSION_ENGINE_HIBER (0x0200)
Definition at line 3630 of file ntrtl.h.
#define COMPRESSION_ENGINE_MAXIMUM (0x0100)
Definition at line 3629 of file ntrtl.h.
#define COMPRESSION_ENGINE_STANDARD (0x0000)
Definition at line 3628 of file ntrtl.h.
#define COMPRESSION_FORMAT_DEFAULT (0x0001)
Definition at line 3625 of file ntrtl.h.
#define COMPRESSION_FORMAT_LZNT1 (0x0002)
Definition at line 3626 of file ntrtl.h.
#define COMPRESSION_FORMAT_NONE (0x0000)
Definition at line 3624 of file ntrtl.h.
#define DBG_STATUS_BUGCHECK_FIRST 3
Definition at line 4548 of file ntrtl.h.
Referenced by KeBugCheck2(), and KiBugCheckDebugBreak().
#define DBG_STATUS_BUGCHECK_SECOND 4
Definition at line 4549 of file ntrtl.h.
Referenced by KeBugCheck2().
#define DBG_STATUS_CONTROL_C 1
Definition at line 4546 of file ntrtl.h.
Referenced by ExpInitializeExecutive(), KdCheckForDebugBreak(), and vDbgPrintExWithPrefixInternal().
#define DBG_STATUS_DEBUG_CONTROL 6
Definition at line 4551 of file ntrtl.h.
#define DBG_STATUS_FATAL 5
Definition at line 4550 of file ntrtl.h.
Referenced by KeEnterKernelDebugger().
#define DBG_STATUS_SYSRQ 2
Definition at line 4547 of file ntrtl.h.
#define DBG_STATUS_WORKER 7
Definition at line 4552 of file ntrtl.h.
Referenced by ExpDebuggerWorker().
#define DEFINE_GUIDEX (name) EXTERN_C const CDECL GUID name
Definition at line 3260 of file ntrtl.h.
#define DOS_MAX_COMPONENT_LENGTH 255
Definition at line 3797 of file ntrtl.h.
#define DOS_MAX_PATH_LENGTH (DOS_MAX_COMPONENT_LENGTH + 5)
Definition at line 3798 of file ntrtl.h.
Referenced by Phase1InitializationDiscard(), and RtlCreateProcessParameters().
#define DPFLTR_ERROR_LEVEL 0
Definition at line 8037 of file ntrtl.h.
Referenced by CmCheckRegistry(), CmInitSystem1(), CmpAcquireFileObjectForFile(), CmpCheckKey(), CmpCheckRegistry2(), CmpCheckValueList(), CmpDumpOneKeyBody(), CmpFileWrite(), CmpFileWriteThroughCache(), CmpFreeAllMemory(), CmpLoadHiveThread(), CmpMapCmView(), CmpOpenFileWithExtremePrejudice(), CmpParseKey(), CmpPinCmView(), CmpSecurityExceptionFilter(), CmpSetNetworkValue(), CmpSetSystemValues(), CmpUnPinCmView(), HvCheckBin(), HvCheckHive(), HvMapHive(), HvpDoWriteHive(), HvpFindFreeCellInBin(), HvpFindNextDirtyBlock(), HvpGetCellMapped(), HvpGetCellPaged(), HvpReleaseCellMapped(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), IoReadPartitionTable(), MiCheckCacheAttributes(), MiCheckPdeForSessionSpace(), MiCompleteProtoPteFault(), MiDeleteVirtualAddresses(), MiDispatchFault(), MiFindEmptyAddressRange(), MiFlushSectionInternal(), MiGatherMappedPages(), MiIdentifyPfn(), MiInitializeMemoryEvents(), MiInsertIoSpaceMap(), MiNoPagesLastChance(), MiResolvePageFileFault(), MiSetProtectionOnSection(), MiWriteComplete(), MmCleanProcessAddressSpace(), MmInitSystem(), NtCreateKey(), NtQueryOpenSubKeys(), WmipCreatePumpThread(), WmipCreatePumpThreadRoutine(), WmipCsrClientMessageServer(), WmipDereferenceEvent(), WmipInsertStaticNames(), WmipMBReply(), WmipPumpThreadApc(), WmipQueueNotification(), WmipReceiveNotifications(), and WmipRegisterMcaHandler().
#define DPFLTR_INFO_LEVEL 3
Definition at line 8040 of file ntrtl.h.
Referenced by MiAllocatePagesForMdl(), MiAttemptPageFileReduction(), MiCreateImageFileMap(), MiEnablePagingOfDriver(), MiFindInitializationCode(), MiFindLargePageMemory(), MiWaitForInPageComplete(), MmAccessFault(), MmGrowKernelStackEx(), MmResetDriverPaging(), NtCreatePagingFile(), WmipAddDataSource(), WmipAllocEntry(), WmipAllocGuidEntryX(), WmipBuildInstanceSet(), WmipCachePtrs(), WmipDetermineInstanceBaseIndex(), WmipDoDisableRequest(), WmipForwardWmiIrp(), WmipIoControl(), WmipLinkDataSourceToList(), WmipMangleInstanceName(), WmipOpenGuidObject(), WmipPumpThreadApc(), WmipReleaseCollectionEnabled(), WmipRemoveDataSource(), WmipSendDisableRequest(), WmipSendEnableDisableRequest(), WmipSendEnableRequest(), WmipTracePageFault(), WmipUpdateAddGuid(), WmipUpdateDataSource(), WmipUpdateModifyGuid(), WmipUpdateRemoveGuid(), and WmipWaitForCollectionEnabled().
#define DPFLTR_MASK 0x80000000
Definition at line 8041 of file ntrtl.h.
#define DPFLTR_TRACE_LEVEL 2
Definition at line 8039 of file ntrtl.h.
Referenced by CmpAcquireFileObjectForFile(), CmpCheckKey(), CmpDoFileSetSize(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpFileFlush(), CmpFileRead(), CmpFileWrite(), CmpFixHiveUsageCount(), CmpInitializeHive(), CmpLazyFlushWorker(), CmpOpenHiveFiles(), CmpQueryKeyDataFromCache(), CmpQueryKeyValueData(), CmUnloadKey(), HalpIsValidPartitionEntry(), HvMapHive(), HvMarkDirty(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpGrowLog1(), HvpGrowLog2(), HvpMapFileImageAndBuildMap(), IoReadPartitionTable(), MiComputeSystemTrimCriteria(), MiDetermineTrimAmount(), MiIdentifyPfn(), MiLoadImageSection(), MiRearrangeWorkingSetExpansionList(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), and MmLoadSystemImage().
#define DPFLTR_WARNING_LEVEL 1
Definition at line 8038 of file ntrtl.h.
Referenced by ExpAllocateUuids(), ExpUuidSaveSequenceNumberIf(), ExpWin32SessionCallout(), IoReadPartitionTable(), MiBuildImportsForBootDrivers(), MiLoadImageSection(), MiPurgeImageSection(), MiReportPhysicalMemory(), MmLoadSystemImage(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmSessionDelete(), PspWin32SessionCallout(), and WmipIncludeStaticNames().
#define FIRSTBYTE (VALUE) ((VALUE) & LOWBYTE_MASK)
Definition at line 5357 of file ntrtl.h.
#define FOR_ALL_RANGES (RangeList, Iterator, Current)
Value:
for (RtlGetFirstRange((RangeList), (Iterator), &(Current)); \
         (Current) != NULL;                                     \
         RtlGetNextRange((Iterator), &(Current), TRUE)          \
         )
Definition at line 7403 of file ntrtl.h.
#define FOR_ALL_RANGES_BACKWARDS (RangeList, Iterator, Current)
Value:
for (RtlGetLastRange((RangeList), (Iterator), &(Current));  \
         (Current) != NULL;                                     \
         RtlGetNextRange((Iterator), &(Current), FALSE)         \
         )
Definition at line 7409 of file ntrtl.h.
#define FOURTHBYTE (VALUE) (((VALUE) >> 24) & LOWBYTE_MASK)
Definition at line 5360 of file ntrtl.h.
#define HASH_STRING_ALGORITHM_DEFAULT (0)
Definition at line 2829 of file ntrtl.h.
Referenced by RtlHashUnicodeString().
#define HASH_STRING_ALGORITHM_INVALID (0xffffffff)
Definition at line 2831 of file ntrtl.h.
#define HASH_STRING_ALGORITHM_X65599 (1)
Definition at line 2830 of file ntrtl.h.
Referenced by RtlHashUnicodeString().
#define HEAP_CLASS_0 0x00000000
Definition at line 1603 of file ntrtl.h.
#define HEAP_CLASS_1 0x00001000
Definition at line 1604 of file ntrtl.h.
#define HEAP_CLASS_2 0x00002000
Definition at line 1605 of file ntrtl.h.
#define HEAP_CLASS_3 0x00003000
Definition at line 1606 of file ntrtl.h.
#define HEAP_CLASS_4 0x00004000
Definition at line 1607 of file ntrtl.h.
#define HEAP_CLASS_5 0x00005000
Definition at line 1608 of file ntrtl.h.
#define HEAP_CLASS_6 0x00006000
Definition at line 1609 of file ntrtl.h.
#define HEAP_CLASS_7 0x00007000
Definition at line 1610 of file ntrtl.h.
#define HEAP_CLASS_8 0x00008000
Definition at line 1611 of file ntrtl.h.
#define HEAP_CLASS_MASK 0x0000F000
Definition at line 1612 of file ntrtl.h.
#define HEAP_CREATE_ALIGN_16 0x00010000
Definition at line 1593 of file ntrtl.h.
#define HEAP_CREATE_ENABLE_EXECUTE 0x00040000
Definition at line 1595 of file ntrtl.h.
#define HEAP_CREATE_ENABLE_TRACING 0x00020000
Definition at line 1594 of file ntrtl.h.
#define HEAP_CREATE_VALID_MASK
Value:
(HEAP_NO_SERIALIZE |             \
                                        HEAP_GROWABLE |                 \
                                        HEAP_GENERATE_EXCEPTIONS |      \
                                        HEAP_ZERO_MEMORY |              \
                                        HEAP_REALLOC_IN_PLACE_ONLY |    \
                                        HEAP_TAIL_CHECKING_ENABLED |    \
                                        HEAP_FREE_CHECKING_ENABLED |    \
                                        HEAP_DISABLE_COALESCE_ON_FREE | \
                                        HEAP_CLASS_MASK |               \
                                        HEAP_CREATE_ALIGN_16 |          \
                                        HEAP_CREATE_ENABLE_TRACING |    \
                                        HEAP_CREATE_ENABLE_EXECUTE)
Definition at line 1621 of file ntrtl.h.
#define HEAP_DISABLE_COALESCE_ON_FREE 0x00000080
Definition at line 1591 of file ntrtl.h.
#define HEAP_FREE_CHECKING_ENABLED 0x00000040
Definition at line 1590 of file ntrtl.h.
#define HEAP_GENERATE_EXCEPTIONS 0x00000004
Definition at line 1586 of file ntrtl.h.
#define HEAP_GLOBAL_TAG 0x0800
Definition at line 1615 of file ntrtl.h.
#define HEAP_GROWABLE 0x00000002
Definition at line 1585 of file ntrtl.h.
#define HEAP_MAKE_TAG_FLAGS (b, o) ((ULONG)((b) + ((o) << 18)))
Definition at line 1618 of file ntrtl.h.
#define HEAP_MAXIMUM_TAG 0x0FFF
Definition at line 1614 of file ntrtl.h.
#define HEAP_NO_SERIALIZE 0x00000001
Definition at line 1584 of file ntrtl.h.
#define HEAP_PSEUDO_TAG_FLAG 0x8000
Definition at line 1616 of file ntrtl.h.
#define HEAP_REALLOC_IN_PLACE_ONLY 0x00000010
Definition at line 1588 of file ntrtl.h.
#define HEAP_SETTABLE_USER_FLAG1 0x00000200
Definition at line 1598 of file ntrtl.h.
#define HEAP_SETTABLE_USER_FLAG2 0x00000400
Definition at line 1599 of file ntrtl.h.
#define HEAP_SETTABLE_USER_FLAG3 0x00000800
Definition at line 1600 of file ntrtl.h.
#define HEAP_SETTABLE_USER_FLAGS 0x00000E00
Definition at line 1601 of file ntrtl.h.
#define HEAP_SETTABLE_USER_VALUE 0x00000100
Definition at line 1597 of file ntrtl.h.
#define HEAP_TAG_MASK (HEAP_MAXIMUM_TAG << HEAP_TAG_SHIFT)
Definition at line 1619 of file ntrtl.h.
#define HEAP_TAG_SHIFT 18
Definition at line 1617 of file ntrtl.h.
#define HEAP_TAIL_CHECKING_ENABLED 0x00000020
Definition at line 1589 of file ntrtl.h.
#define HEAP_ZERO_MEMORY 0x00000008
Definition at line 1587 of file ntrtl.h.
#define INIT_PARSE_MESSAGE_CONTEXT (ctx)
Value:
{ \
    (ctx)->fFlags = 0; \
}
Definition at line 6995 of file ntrtl.h.
#define InitializeListHead32 (ListHead)
Value:
(\
    (ListHead)->Flink = (ListHead)->Blink = PtrToUlong((ListHead)))
Definition at line 327 of file ntrtl.h.
#define IS_TEXT_UNICODE_ASCII16 0x0001
Definition at line 3196 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_CONTROLS 0x0004
Definition at line 3202 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_DBCS_LEADBYTE 0x0400
Definition at line 3210 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_ILLEGAL_CHARS 0x0100
Definition at line 3208 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_NOT_ASCII_MASK 0xF000
Definition at line 3216 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_NOT_UNICODE_MASK 0x0F00
Definition at line 3215 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_NULL_BYTES 0x1000
Definition at line 3211 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_ODD_LENGTH 0x0200
Definition at line 3209 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_REVERSE_ASCII16 0x0010
Definition at line 3197 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_REVERSE_CONTROLS 0x0040
Definition at line 3203 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_REVERSE_MASK 0x00F0
Definition at line 3214 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_REVERSE_SIGNATURE 0x0080
Definition at line 3206 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_REVERSE_STATISTICS 0x0020
Definition at line 3200 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_SIGNATURE 0x0008
Definition at line 3205 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_STATISTICS 0x0002
Definition at line 3199 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IS_TEXT_UNICODE_UNICODE_MASK 0x000F
Definition at line 3213 of file ntrtl.h.
Referenced by RtlIsTextUnicode().
#define IsEqualGUIDAligned (guid1, guid2) ((*(PLONGLONG)(guid1) == *(PLONGLONG)(guid2)) && (*((PLONGLONG)(guid1) + 1) == *((PLONGLONG)(guid2) + 1)))
Definition at line 3275 of file ntrtl.h.
#define IsListEmpty (ListHead) ((ListHead)->Flink == (ListHead))
Definition at line 349 of file ntrtl.h.
Referenced by CcAcquireByteRangeForWrite(), CcCanIWrite(), CcDeleteMbcb(), CcDeleteSharedCacheMap(), CcFlushCache(), CcGetVacbMiss(), CcLazyWriteScan(), CcPostDeferredWrites(), CcPostWorkQueue(), CcPurgeCacheSection(), CcSetFileSizes(), CcUninitializeCacheMap(), CcUnpinRepinnedBcb(), CcWaitForUninitializeCacheMap(), CcWorkerThread(), CcWriteBehind(), CmCompressKey(), CmNotifyRunDown(), CmpAllocateKeyControlBlock(), CmpCallCallBacks(), CmpCancelSlavePost(), CmpCloseKeyObject(), CmpDelayedDerefKeys(), CmpDestroyHiveViewList(), CmpDumpKeyBodyList(), CmpFindMatchingDescriptorCell(), CmpFlushNotifiesOnKeyBodyList(), CmpFlushNotify(), CmpFreeAllMemory(), CmpFreeCmView(), CmpFreePostBlock(), CmpFreeSlavePost(), CmpMapCmView(), CmpNotifyTriggerCheck(), CmpPostNotify(), CmpRaiseSelfHealWarningWorker(), CmpShiftHiveFreeBins(), CmpSwitchStorageAndRebuildMappings(), CmpTouchView(), DbgkClearProcessDebugObject(), DbgkpDeleteObject(), DbgkpSetProcessDebugObject(), DelistKeyBodyFromKCB(), ExNotifyCallback(), ExpDeleteCallback(), ExpGetProcessInformation(), ExpNewThreadNecessary(), ExpWorkerThread(), ExRegisterCallback(), FsRtlAcknowledgeOplockBreak(), FsRtlCancelExclusiveIrp(), FsRtlCancelNotify(), FsRtlCancelOplockIIIrp(), FsRtlCheckNotifyForDelete(), FsRtlEmptyFreePoolList(), FsRtlLookupPerFileObjectContext(), FsRtlLookupPerStreamContextInternal(), FsRtlNotifyCleanup(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyFilterReportChange(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPruneTunnelCache(), FsRtlPTeardownPerFileObjectContexts(), FsRtlRemovePerFileObjectContext(), FsRtlRemovePerStreamContext(), FsRtlTeardownPerStreamContexts(), FsRtlUninitializeOplock(), HvAutoCompressCheck(), HvMarkCellDirty(), HvMarkDirty(), HvpFlushMappedData(), HvpRecoverData(), HvpRecoverWholeHive(), HvRefreshHive(), IoCancelThreadIo(), IopCheckHardErrorEmpty(), IopDisassociateThreadIrp(), IopErrorLogGetEntry(), IopFreeIrp(), IoRegisterFsRegistrationChange(), IoReuseIrp(), KeDetachProcess(), KeFlushQueueApc(), KeInsertByKeyDeviceQueue(), KePulseEvent(), KeReleaseMutant(), KeReleaseSemaphore(), KeRemoveByKeyDeviceQueue(), KeRemoveByKeyDeviceQueueIfBusy(), KeRemoveDeviceQueue(), KeRundownQueue(), KeRundownThread(), KeSetEvent(), KeSetEventBoostPriority(), KeSetProcess(), KeSignalGateBoostPriority(), KeStartThread(), KeStopProfile(), KeTerminateThread(), KeTestAlertThread(), KeUnstackDetachProcess(), KiDeliverApc(), KiFindReadyThread(), KiMoveApcState(), KiScanReadyQueues(), KiSelectReadyThread(), KiSignalTimer(), KiTimerExpiration(), KiTimerListExpire(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), LpcExitThread(), LpcpDestroyPortQueue(), LpcpFreeConMsg(), LpcpFreeToPortZone(), LpcpPrepareToWakeClient(), LpcpRequestWaitReplyPort(), MiCheckSystemPteProtection(), MiDereferenceSegmentThread(), MiExtendPagingFileMaximum(), MiGatherPagefilePages(), MiGetHighestPteConsumer(), MiInsertPageFileInList(), MiMappedPageWriter(), MiModifiedPageWriterWorker(), MiProcessWorkingSets(), MiProtectedPoolInsertList(), MiProtectedPoolRemoveEntryList(), MiRearrangeWorkingSetExpansionList(), MiReleaseAllMemory(), MiRemoveImageSectionObject(), MiRemoveUnusedSegments(), MiShutdownSystem(), MiTrimSegmentCache(), MiUnsecureVirtualMemory(), MiWriteComplete(), MmAccessFault(), MmCleanProcessAddressSpace(), MmDeleteTeb(), MmFlushImageSection(), MmProtectMdlSystemAddress(), NtCreateJobSet(), NtQueryInformationThread(), NtReleaseKeyedEvent(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSetInformationJobObject(), NtWaitForKeyedEvent(), ObpRemoveObjectRoutine(), PspCreateProcess(), PspJobDelete(), SepDequeueWorkItem(), WmipAllocEntry(), WmipCheckIsWbemRunning(), WmipClearObjectFromThreadList(), WmipClearThreadObjectList(), WmipEnableDisableTrace(), WmipProcessPrevMcaLogs(), and WmipRegistrationWorker().
#define KdBreakPoint ()
Definition at line 4578 of file ntrtl.h.
Referenced by NtReplyWaitReceivePortEx(), and ObInsertObject().
#define KdBreakPointWithStatus (s)
Definition at line 4582 of file ntrtl.h.
#define KdPrint (_x_)
Definition at line 4572 of file ntrtl.h.
Referenced by __bcount(), ExpInitializeExecutive(), ExpInitSystemPhase0(), ExpInitSystemPhase1(), FsFilterPerformCallbacks(), IopSafebootDriverLoad(), KeBalanceSetManager(), MiAttemptPageFileExtension(), MiCleanSection(), MiCreateImageFileMap(), MiDereferenceSegmentThread(), MiGatherPagefilePages(), MiIssuePageExtendRequest(), MiUnlinkPageFromList(), MiWriteComplete(), MiWriteProtectSystemImage(), MmAccessFault(), MmGetPhysicalAddress(), MmLoadSystemImage(), NtCreatePagingFile(), NtCreateSymbolicLinkObject(), ObInsertObject(), ObpCaptureObjectCreateInformation(), ObpShutdownCloseHandleProcedure(), ObShutdownSystem(), Phase1InitializationDiscard(), PspLookupKernelUserEntryPoints(), PspUnhandledExceptionInSystemThread(), PsWaitForAllProcesses(), RawDispatch(), RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), RtlInitializeStackTraceDataBase(), RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), RtlpIsDuplicateAce(), SepInitializationPhase0(), SepRmCallLsa(), SepRmCommandServerThread(), SepRmCommandServerThreadInit(), and SeRmInitPhase1().
#define KdPrintEx (_x_)
Definition at line 4574 of file ntrtl.h.
Referenced by ExpAllocateUuids(), ExpUuidSaveSequenceNumberIf(), ExpWin32SessionCallout(), HalpIsValidPartitionEntry(), IoReadPartitionTable(), LdrAccessResource(), LdrFindEntryForAddress(), LdrpAccessResourceData(), LdrpAccessResourceDataNoMultipleLanguage(), and PspWin32SessionCallout().
#define LONG_2ND_MOST_SIGNIFICANT_BIT 2
Definition at line 5371 of file ntrtl.h.
#define LONG_3RD_MOST_SIGNIFICANT_BIT 1
Definition at line 5370 of file ntrtl.h.
#define LONG_LEAST_SIGNIFICANT_BIT 0
Definition at line 5369 of file ntrtl.h.
#define LONG_MASK (LONG_SIZE - 1)
Definition at line 5353 of file ntrtl.h.
#define LONG_MOST_SIGNIFICANT_BIT 3
Definition at line 5372 of file ntrtl.h.
#define LONG_SIZE (sizeof(LONG))
Definition at line 5351 of file ntrtl.h.
#define LONGLONG_MASK (LONGLONG_SIZE - 1)
Definition at line 5354 of file ntrtl.h.
#define LONGLONG_SIZE (sizeof(LONGLONG))
Definition at line 5352 of file ntrtl.h.
#define LOWBYTE_MASK 0x00FF
Definition at line 5355 of file ntrtl.h.
#define MAX_EXCEPTION_LOG 10
Definition at line 4469 of file ntrtl.h.
Referenced by ExpInitializeExecutive(), and RtlpLogExceptionHandler().
#define MAX_EXCEPTION_LOG_DATA_SIZE 5
Definition at line 4470 of file ntrtl.h.
Referenced by RtlpLogExceptionHandler().
#define MAX_STACK_DEPTH 32
Definition at line 1806 of file ntrtl.h.
Referenced by RtlCaptureStackBackTrace(), and RtlpCaptureStackTraceForLogging().
#define MESSAGE_RESOURCE_UNICODE 0x0001
Definition at line 6940 of file ntrtl.h.
Referenced by ExpSystemErrorHandler().
#define NLS_MB_CODE_PAGE_TAG (*NlsMbCodePageTag)
Definition at line 2535 of file ntrtl.h.
#define NLS_MB_OEM_CODE_PAGE_TAG (*NlsMbOemCodePageTag)
Definition at line 2536 of file ntrtl.h.
#define PopEntryList (ListHead)
Value:
(ListHead)->Next;\
    {\
        PSINGLE_LIST_ENTRY FirstEntry;\
        FirstEntry = (ListHead)->Next;\
        if (FirstEntry != NULL) {     \
            (ListHead)->Next = FirstEntry->Next;\
        }                             \
    }
Definition at line 447 of file ntrtl.h.
Referenced by FsRtlUninitializeFileLock().
#define PSLIST_ENTRY PSINGLE_LIST_ENTRY
Definition at line 121 of file ntrtl.h.
Referenced by ExFreePoolWithTag(), ExFreeToNPagedLookasideList(), ExFreeToPagedLookasideList(), ExFreeToPPLookasideList(), ExRemoveHeadNBQueue(), IopFreeIrp(), IopFreeMiniPacket(), MiCheckControlAreaStatus(), MiDeferredUnlockPages(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiFreePoolPages(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiInitializeSystemPtes(), MiInsertPteTracker(), MiPteSListExpansionWorker(), MiReleaseAllMemory(), MiRemovePteTracker(), MmDeleteKernelStack(), MmInitSystem(), MmUnlockPages(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipFlushActiveBuffers(), WmipFlushBuffersWithMarker(), WmipFreeTraceBufferPool(), WmipGetFreeBuffer(), WmipPushDirtyBuffer(), WmipPushFreeBuffer(), and WmipSwitchBuffer().
#define PushEntryList (ListHead, Entry)
Value:
(Entry)->Next = (ListHead)->Next; \
    (ListHead)->Next = (Entry)
Definition at line 466 of file ntrtl.h.
Referenced by FsRtlUninitializeFileLock(), KiInsertDeferredReadyList(), and MiReferenceIoSpace().
#define RTL_ACQUIRE_PRIVILEGE_PROCESS 0x00000002UL
Definition at line 6764 of file ntrtl.h.
#define RTL_ACQUIRE_PRIVILEGE_REVERT 0x00000001UL
Definition at line 6763 of file ntrtl.h.
#define RTL_ATOM_INVALID_ATOM (RTL_ATOM)0x0000
Definition at line 1973 of file ntrtl.h.
Referenced by RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), RtlLookupAtomInAtomTable(), RtlpGetIntegerAtom(), RtlPinAtomInAtomTable(), and RtlQueryAtomInAtomTable().
#define RTL_ATOM_MAXIMUM_INTEGER_ATOM (RTL_ATOM)0xC000
Definition at line 1972 of file ntrtl.h.
Referenced by RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), RtlLookupAtomInAtomTable(), RtlpCreateHandleForAtom(), RtlpGetIntegerAtom(), RtlpHashStringToAtom(), RtlPinAtomInAtomTable(), and RtlQueryAtomInAtomTable().
#define RTL_ATOM_MAXIMUM_NAME_LENGTH 255
Definition at line 1975 of file ntrtl.h.
Referenced by RtlpHashStringToAtom().
#define RTL_ATOM_PINNED 0x01
Definition at line 1976 of file ntrtl.h.
Referenced by RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), RtlEmptyAtomTable(), RtlPinAtomInAtomTable(), and RtlQueryAtomInAtomTable().
#define RTL_ATOM_TABLE_DEFAULT_NUMBER_OF_BUCKETS 37
Definition at line 1974 of file ntrtl.h.
Referenced by RtlCreateAtomTable().
#define RTL_DRIVE_LETTER_VALID (USHORT)0x0001
Definition at line 3820 of file ntrtl.h.
#define RTL_DUPLICATE_UNICODE_STRING_ALLOCATE_NULL_STRING (0x00000002)
Definition at line 2854 of file ntrtl.h.
Referenced by RtlDuplicateUnicodeString().
#define RTL_DUPLICATE_UNICODE_STRING_NULL_TERMINATE (0x00000001)
Definition at line 2853 of file ntrtl.h.
Referenced by RtlDuplicateUnicodeString().
#define RTL_ERRORMODE_FAILCRITICALERRORS (0x0010)
Definition at line 7852 of file ntrtl.h.
Referenced by ExpRaiseHardError(), and IoRaiseHardError().
#define RTL_FIND_CHAR_IN_UNICODE_STRING_CASE_INSENSITIVE (0x00000004)
Definition at line 2889 of file ntrtl.h.
Referenced by RtlFindCharInUnicodeString().
#define RTL_FIND_CHAR_IN_UNICODE_STRING_COMPLEMENT_CHAR_SET (0x00000002)
Definition at line 2888 of file ntrtl.h.
Referenced by RtlFindCharInUnicodeString().
#define RTL_FIND_CHAR_IN_UNICODE_STRING_START_AT_END (0x00000001)
Definition at line 2887 of file ntrtl.h.
Referenced by RtlFindCharInUnicodeString(), and RtlQueryEnvironmentVariable_U().
#define RTL_IMAGE_NT_HEADER_EX_FLAG_NO_RANGE_CHECK (0x00000001)
Definition at line 4096 of file ntrtl.h.
Referenced by RtlImageNtHeader(), and RtlImageNtHeaderEx().
#define RTL_MAX_DRIVE_LETTERS 32
Definition at line 3819 of file ntrtl.h.
#define RTL_MEG (1024UL * 1024UL)
Definition at line 4115 of file ntrtl.h.
#define RTL_QUERY_REGISTRY_DELETE 0x00000040
Definition at line 2150 of file ntrtl.h.
Referenced by RtlQueryRegistryValues().
#define RTL_QUERY_REGISTRY_DIRECT 0x00000020
Definition at line 2141 of file ntrtl.h.
Referenced by CmIsLastKnownGoodBoot(), RtlpCallQueryRegistryRoutine(), RtlQueryRegistryValues(), RtlQueryTimeZoneInformation(), RtlSetActiveTimeBias(), and WmipQueryWmiDataBlock().
#define RTL_QUERY_REGISTRY_NOEXPAND 0x00000010
Definition at line 2136 of file ntrtl.h.
Referenced by RtlpCallQueryRegistryRoutine().
#define RTL_QUERY_REGISTRY_NOVALUE 0x00000008
Definition at line 2132 of file ntrtl.h.
Referenced by RtlQueryRegistryValues().
#define RTL_QUERY_REGISTRY_REQUIRED 0x00000004
Definition at line 2129 of file ntrtl.h.
Referenced by RtlpCallQueryRegistryRoutine(), RtlQueryRegistryValues(), RtlSetActiveTimeBias(), and WmipQueryWmiDataBlock().
#define RTL_QUERY_REGISTRY_SUBKEY 0x00000001
Definition at line 2122 of file ntrtl.h.
Referenced by RtlQueryRegistryValues().
#define RTL_QUERY_REGISTRY_TOPKEY 0x00000002
Definition at line 2126 of file ntrtl.h.
Referenced by RtlQueryRegistryValues().
#define RTL_RANGE_CONFLICT 0x02
Definition at line 7260 of file ntrtl.h.
#define RTL_RANGE_LIST_ADD_IF_CONFLICT 0x00000001
Definition at line 7329 of file ntrtl.h.
#define RTL_RANGE_LIST_ADD_SHARED 0x00000002
Definition at line 7330 of file ntrtl.h.
#define RTL_RANGE_LIST_MERGE_IF_CONFLICT RTL_RANGE_LIST_ADD_IF_CONFLICT
Definition at line 7442 of file ntrtl.h.
#define RTL_RANGE_LIST_NULL_CONFLICT_OK 0x00000002
Definition at line 7364 of file ntrtl.h.
#define RTL_RANGE_LIST_SHARED_OK 0x00000001
Definition at line 7363 of file ntrtl.h.
#define RTL_RANGE_SHARED 0x01
Definition at line 7259 of file ntrtl.h.
#define RTL_REGISTRY_ABSOLUTE 0
Definition at line 2209 of file ntrtl.h.
Referenced by CmIsLastKnownGoodBoot(), RtlpGetRegistryHandle(), and WmipQueryWmiDataBlock().
#define RTL_REGISTRY_CONTROL 2
Definition at line 2211 of file ntrtl.h.
Referenced by RtlpGetTimeZoneInfoHandle(), WmipGetGuidSecurityDescriptor(), WmipSaveGuidSecurityDescriptor(), and WmipStartGlobalLogger().
#define RTL_REGISTRY_DEVICEMAP 4
Definition at line 2213 of file ntrtl.h.
#define RTL_REGISTRY_HANDLE 0x40000000
Definition at line 2216 of file ntrtl.h.
Referenced by RtlCreateRegistryKey(), RtlDeleteRegistryValue(), RtlpGetRegistryHandle(), RtlQueryRegistryValues(), RtlQueryTimeZoneInformation(), RtlSetActiveTimeBias(), RtlSetTimeZoneInformation(), and RtlWriteRegistryValue().
#define RTL_REGISTRY_MAXIMUM 6
Definition at line 2215 of file ntrtl.h.
Referenced by RtlpGetRegistryHandle().
#define RTL_REGISTRY_OPTIONAL 0x80000000
Definition at line 2217 of file ntrtl.h.
Referenced by RtlpGetRegistryHandle().
#define RTL_REGISTRY_SERVICES 1
Definition at line 2210 of file ntrtl.h.
#define RTL_REGISTRY_USER 5
Definition at line 2214 of file ntrtl.h.
Referenced by RtlOpenCurrentUser(), and RtlpGetRegistryHandle().
#define RTL_REGISTRY_WINDOWS_NT 3
Definition at line 2212 of file ntrtl.h.
#define RTL_SOFT_ASSERT (_exp) ((void) 0)
Definition at line 301 of file ntrtl.h.
#define RTL_SOFT_ASSERTMSG (_msg, _exp) ((void) 0)
Definition at line 302 of file ntrtl.h.
#define RTL_SOFT_VERIFY (_exp) ((_exp) ? TRUE : FALSE)
Definition at line 307 of file ntrtl.h.
#define RTL_SOFT_VERIFYMSG (msg, _exp) ((_exp) ? TRUE : FALSE)
Definition at line 308 of file ntrtl.h.
#define RTL_SYSTEM_VOLUME_INFORMATION_FOLDER L"System Volume Information"
Definition at line 7540 of file ntrtl.h.
Referenced by RtlCreateSystemVolumeInformationFolder().
#define RTL_TRACE_IN_KERNEL_MODE 0x00000002
Definition at line 1856 of file ntrtl.h.
Referenced by RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseInitializeLock(), RtlpTraceDatabaseReleaseLock(), RtlpTraceDatabaseUninitializeLock(), and RtlTraceDatabaseCreate().
#define RTL_TRACE_IN_USER_MODE 0x00000001
Definition at line 1855 of file ntrtl.h.
#define RTL_TRACE_USE_NONPAGED_POOL 0x00000004
Definition at line 1857 of file ntrtl.h.
Referenced by RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseAllocate(), RtlpTraceDatabaseInitializeLock(), RtlpTraceDatabaseReleaseLock(), RtlpTraceDatabaseUninitializeLock(), and RtlTraceDatabaseCreate().
#define RTL_TRACE_USE_PAGED_POOL 0x00000008
Definition at line 1858 of file ntrtl.h.
#define RTL_USER_PROC_APP_MANIFEST_PRESENT 0x00002000
Definition at line 3971 of file ntrtl.h.
#define RTL_USER_PROC_CASE_SENSITIVE 0x00000080
Definition at line 3968 of file ntrtl.h.
#define RTL_USER_PROC_CURDIR_CLOSE 0x00000002
Definition at line 3809 of file ntrtl.h.
Referenced by RtlCreateProcessParameters().
#define RTL_USER_PROC_CURDIR_INHERIT 0x00000003
Definition at line 3810 of file ntrtl.h.
Referenced by RtlCreateProcessParameters().
#define RTL_USER_PROC_DISABLE_HEAP_DECOMMIT 0x00000100
Definition at line 3969 of file ntrtl.h.
#define RTL_USER_PROC_DLL_REDIRECTION_LOCAL 0x00001000
Definition at line 3970 of file ntrtl.h.
#define RTL_USER_PROC_IMAGE_KEY_MISSING 0x00004000
Definition at line 3972 of file ntrtl.h.
#define RTL_USER_PROC_OPTIN_PROCESS 0x00020000
Definition at line 3973 of file ntrtl.h.
#define RTL_USER_PROC_PARAMS_NORMALIZED 0x00000001
Definition at line 3962 of file ntrtl.h.
Referenced by Phase1InitializationDiscard(), RtlCreateProcessParameters(), RtlDeNormalizeProcessParams(), and RtlNormalizeProcessParams().
#define RTL_USER_PROC_PROFILE_KERNEL 0x00000004
Definition at line 3964 of file ntrtl.h.
#define RTL_USER_PROC_PROFILE_SERVER 0x00000008
Definition at line 3965 of file ntrtl.h.
#define RTL_USER_PROC_PROFILE_USER 0x00000002
Definition at line 3963 of file ntrtl.h.
#define RTL_USER_PROC_RESERVE_16MB 0x00000040
Definition at line 3967 of file ntrtl.h.
#define RTL_USER_PROC_RESERVE_1MB 0x00000020
Definition at line 3966 of file ntrtl.h.
Referenced by Phase1InitializationDiscard(), and RtlCreateUserProcess().
#define RTL_VERIFY (exp) ((exp) ? TRUE : FALSE)
Definition at line 304 of file ntrtl.h.
#define RTL_VERIFYMSG (msg, exp) ((exp) ? TRUE : FALSE)
Definition at line 305 of file ntrtl.h.
#define RtlAnsiStringToUnicodeSize (STRING)
Value:
(\
    NLS_MB_CODE_PAGE_TAG ?                                   \
    RtlxAnsiStringToUnicodeSize(STRING) :                    \
    ((STRING)->Length + sizeof(ANSI_NULL)) * sizeof(WCHAR) \
)
Definition at line 3057 of file ntrtl.h.
Referenced by RtlAnsiStringToUnicodeString().
#define RtlApplyAceToObject (Ace, Mapping)
Value:
if (!FlagOn((Ace)->AceFlags, INHERIT_ONLY_ACE)) { \
                RtlApplyGenericMask( Ace, &((PKNOWN_ACE)(Ace))->Mask, Mapping ); \
            }
Definition at line 6830 of file ntrtl.h.
Referenced by RtlpApplyAclToObject(), and RtlpCopyAces().
#define RtlApplyGenericMask (Ace, Mask, Mapping)
Value:
{                                                  \
                RtlMapGenericMask( (Mask), (Mapping));  \
                                                                                            \
                if ( (((PKNOWN_ACE)(Ace))->Header.AceType == ACCESS_ALLOWED_ACE_TYPE) ||    \
                     (((PKNOWN_ACE)(Ace))->Header.AceType == ACCESS_DENIED_ACE_TYPE)  ||    \
                     (((PKNOWN_ACE)(Ace))->Header.AceType == ACCESS_ALLOWED_COMPOUND_ACE_TYPE)  ||    \
                     (((PKNOWN_ACE)(Ace))->Header.AceType == ACCESS_ALLOWED_OBJECT_ACE_TYPE)  ||    \
                     (((PKNOWN_ACE)(Ace))->Header.AceType == ACCESS_DENIED_OBJECT_ACE_TYPE)  ) {   \
                    *(Mask) &= (Mapping)->GenericAll;                     \
                } else {                                                                    \
                    *(Mask) &= ((Mapping)->GenericAll |                   \
                                                  ACCESS_SYSTEM_SECURITY);                  \
                }                                                                           \
            }
Definition at line 6836 of file ntrtl.h.
Referenced by RtlpConvertAclToAutoInherit(), and RtlpCopyEffectiveAce().
#define RtlCheckBit (BMH, BP) ((((BMH)->Buffer[(BP) / 32]) >> ((BP) % 32)) & 0x1)
Definition at line 5945 of file ntrtl.h.
Referenced by HvMarkDirty(), HvpDoWriteHive(), HvpFindFreeCellInBin(), HvpFindNextDirtyBlock(), HvpRecoverData(), HvRefreshHive(), MiBuildPagedPool(), MiCheckPteRelease(), MiDereferenceSession(), MiDereferenceSessionFinal(), MiFinishPageFileExtension(), MiFreePoolPages(), MiReleaseConfirmedPageFileSpace(), MiReleasePageFileSpace(), MiReleaseProcessReferenceToSessionDataPage(), MiReleaseSplitSystemPtes(), MiSessionCreateInternal(), MiZeroPageFile(), MmGetSizeOfBigPoolAllocation(), NtGetWriteWatch(), RtlFindLastBackwardRunClear(), and RtlFindNextForwardRunClear().
#define RtlCompoundAceClientSid (Ace) ((PSID)(((ULONG_PTR)(&((PKNOWN_COMPOUND_ACE)(Ace))->SidStart))+RtlLengthSid(RtlCompoundAceServerSid((Ace)))))
Definition at line 6928 of file ntrtl.h.
Referenced by RtlpCopyEffectiveAce(), RtlpCreateServerAcl(), SepMaximumAccessCheck(), and SepNormalAccessCheck().
#define RtlCompoundAceServerSid (Ace) ((PSID)&((PKNOWN_COMPOUND_ACE)(Ace))->SidStart)
Definition at line 6926 of file ntrtl.h.
Referenced by RtlpCopyEffectiveAce(), RtlpCreateServerAcl(), SepMaximumAccessCheck(), and SepNormalAccessCheck().
#define RtlCopyBytes RtlCopyMemory
Definition at line 4303 of file ntrtl.h.
Referenced by CcCopyRead(), CcCopyWrite(), CcFastCopyRead(), CcFastCopyWrite(), CcMapAndCopy(), and MmCopyToCachedPage().
#define RtlCopyMemory (Destination, Source, Length) memcpy((Destination),(Source),(Length))
Definition at line 4266 of file ntrtl.h.
Referenced by BuildQueryDirectoryIrp(), CcExtendVacbArray(), CcLogError(), CcSetDirtyInMask(), CmGetSystemControlValues(), CmpAcquireFileObjectForFile(), CmpAddDriverToList(), CmpAddSecurityCellToCache(), CmpAdjustSecurityCacheSize(), CmpAssignSecurityDescriptor(), CmpCheckKey(), CmpCmdRenameHive(), CmpConstructName(), CmpCopyCell(), CmpCopyName(), CmpDoCreateChild(), CmpDumpOneKeyBody(), CmpFileWriteThroughCache(), CmpGetHiveName(), CmpGetSymbolicLink(), CmpGetValueData(), CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), CmpHiveRootSecurityDescriptor(), CmpInitHiveFromFile(), CmpInitializeRegistryNode(), CmpNameFromAttributes(), CmpQueryKeyData(), CmpQueryKeyName(), CmpQueryKeyValueData(), CmpRaiseSelfHealWarning(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSwitchStorageAndRebuildMappings(), CmQueryKey(), CmQueryMultipleValueKey(), CmRenameKey(), CmRestoreKey(), CmSetValueKey(), DbgkpPostFakeModuleMessages(), DbgkpSendApiMessageLpc(), ExGetBigPoolInfo(), ExpExpandResourceOwnerTable(), ExpGetInstemulInformation(), ExpGetPoolTagInfoTarget(), ExpGetProcessInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpGetSystemFirmwareTableInformation(), ExpInitializeExecutive(), ExpInsertPoolTrackerExpansion(), ExpQueryLegacyDriverInformation(), ExpRaiseHardError(), ExpSystemErrorHandler(), ExRaiseHardError(), FsRtlAddLargeEntry(), FsRtlAddToTunnelCache(), FsRtlCancelNotify(), FsRtlFindInTunnelCache(), FsRtlIsDbcsInExpression(), FsRtlIsNameInExpressionPrivate(), FsRtlNotifyCompleteIrp(), FsRtlNotifyUpdateBuffer(), FsRtlNotifyVolumeEvent(), FsRtlpRegisterProviderWithMUP(), FsRtlRegisterFileSystemFilterCallbacks(), FsRtlRegisterUncProvider(), FsRtlTruncateBaseMcb(), HalpDeleteMountLetter(), HalpNextMountLetter(), HalpSetMountLetter(), HvCloneHive(), HvDuplicateCell(), HvInitializeHive(), HvpAddBin(), HvpAdjustBitmap(), HvpBuildMapAndCopy(), HvpDoWriteHive(), HvpFillFileName(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpWriteLog(), HvRefreshHive(), HvTrackCellRef(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoCreateDriver(), IoIsValidNameGraftingBuffer(), IopBuildFullDriverPath(), IopCompleteRequest(), IopCreateDefaultDeviceSecurityDescriptor(), IopCreateFile(), IopDoNameTransmogrify(), IopErrorLogThread(), IopGetVolumeId(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopLogErrorEvent(), IopMarshalIds(), IopParseDevice(), IopQueryNameInternal(), IopSendMessageToTrackService(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IopTrackLink(), IopUnloadDriver(), IopUnMarshalIds(), IopXxxControlFile(), IoRaiseInformationalHardError(), IoReadPartitionTable(), IoVolumeDeviceToDosName(), IoWMIAllocateInstanceIds(), IoWMIExecuteMethod(), IoWMIQuerySingleInstance(), IoWMISetSingleInstance(), IoWMISetSingleItem(), IoWMISystemControl(), Ke386CallBios(), Ke386GetGdtEntryThread(), Ke386QueryIoAccessMap(), KeContextFromKframes(), KeContextToKframes(), KeRestoreFloatingPointState(), KeSaveFloatingPointState(), KeUserModeCallback(), Ki386BuildIdentityBuffer(), KiAddRange(), KiCloneDescriptor(), KiCompleteEffectiveRangeChange(), KiContinuePreviousModeUser(), KiCopyDescriptorMemory(), KiCopyInformation(), KiDispatchException(), KiGetCpuVendor(), KiI386PentiumLockErrataFixup(), KiInitializeContextThread(), KiInitializeKernel(), KiInitializeUserApc(), KiInitSystem(), KiMoveApcState(), KiOpFetchBytes(), KiRaiseException(), KiSetCpuVendor(), KiSetIoMap(), KiStartEffectiveRangeChange(), MiAllocatePagesForMdl(), MiAttachSession(), MiCaptureUlongPtrArray(), MiCcPutPagesInTransition(), MiCloneProcessAddressSpace(), MiCopyHeaderIfResident(), MiCreateImageFileMap(), MiDoMappedCopy(), MiDoPoolCopy(), MiExtendPagingFileMaximum(), MiHandleBankedSection(), MiInitializeLoadedModuleList(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiLoadImageSection(), MiLoadUserSymbols(), MiMapViewOfImageSection(), MiReferenceIoSpace(), MiReloadBootLoadedDrivers(), MiRememberUnloadedDriver(), MiResolveImageReferences(), MiSecureVirtualMemory(), MiSessionCreateInternal(), MiSessionWideReserveImageAddress(), MiShutdownSystem(), MiSnapCopyMemory(), MiSnapPagefileWrite(), MiSnapThunk(), MiUpdateSystemPdes(), MiUseLargeDriverPage(), MmCallDllInitialize(), MmCreateProcessAddressSpace(), MmCreateSection(), MmCreateTeb(), MmGetPageFileInformation(), MmInitializeHandBuiltProcess2(), MmInitializeMemoryLimits(), MmInitSystem(), MmLoadSystemImage(), MmProbeAndLockSelectedPages(), MmUnlockPages(), NtAcceptConnectPort(), NtAddAtom(), NtAllocateUserPhysicalPages(), NtAllocateUuids(), NtCreateJobSet(), NtCreatePagingFile(), NtCreateSymbolicLinkObject(), NtFindAtom(), NtFreeUserPhysicalPages(), NtGetWriteWatch(), NtLoadDriver(), NtLoadKeyEx(), NtOpenObjectAuditAlarm(), NtPrivilegeCheck(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryFullAttributesFile(), NtQueryInformationJobObject(), NtQueryInformationProcess(), NtQueryInformationToken(), NtQueryQuotaInformationFile(), NtQuerySymbolicLinkObject(), NtQuerySystemInformation(), NtQueryVolumeInformationFile(), NtRaiseHardError(), NtReadFileScatter(), NtReplyWaitReceivePortEx(), NtSecureConnectPort(), NtSetEaFile(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationToken(), NtSetSystemInformation(), NtSetUuidSeed(), NtSetValueKey(), NtSetVolumeInformationFile(), NtWaitForMultipleObjects(), NtWriteFile(), NtWriteFileGather(), ObpCaptureObjectName(), ObpCreateCacheEntry(), ObpInsertHandleCount(), ObpLookupObjectName(), ObpParseSymbolicLink(), ObpQueryNameString(), ObQueryDeviceMapInformation(), ObQueryTypeInfo(), ObQueryTypeName(), PerfInfoLogBytes(), PerfInfoLogBytesAndUnicodeString(), PerfInfoProcessRunDown(), Phase1InitializationDiscard(), PsChangeQuantumTable(), PsGetContextThread(), PspCreateLdt(), PspCreateProcess(), PspQueryDescriptorThread(), PspQueryLdtInformation(), PspQueryQuotaLimits(), PspQueryWorkingSetWatch(), PspSetLdtInformation(), PspSetQuotaLimits(), PsSetContextThread(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawQueryFsAttributeInfo(), RtlAddAtomToAtomTable(), RtlCopyUnicodeString(), RtlCreateEnvironment(), RtlCreateSystemVolumeInformationFolder(), RtlCreateUnicodeString(), RtlDuplicateUnicodeString(), RtlInitCodePageTable(), RtlInsertElementGenericTableFull(), RtlInsertElementGenericTableFullAvl(), RtlIntegerToChar(), RtlIntegerToUnicode(), RtlIpv4AddressToStringExT(), RtlIpv6AddressToStringExT(), RtlMakeSelfRelativeSD(), RtlpAddKnownObjectAce(), RtlpCallQueryRegistryRoutine(), RtlpConvertAclToAutoInherit(), RtlpConvertToAutoInheritSecurityObject(), RtlpCopyAces(), RtlpCopyEffectiveAce(), RtlpCopyProcString(), RtlpCreateServerAcl(), RtlpGenerateInheritedAce(), RtlpLogExceptionHandler(), RtlpNewSecurityObject(), RtlpQueryRegistryDirect(), RtlpSetSecurityObject(), RtlpSysVolCheckOwnerAndSecurity(), RtlQueryAtomInAtomTable(), RtlQueryEnvironmentVariable_U(), RtlRemoteCall(), RtlResetRtlTranslations(), RtlSetEnvironmentStrings(), SeAccessCheckByType(), SeAppendPrivileges(), SeAssignWorldSecurityDescriptor(), SeCaptureAcl(), SeCaptureAuditPolicy(), SeCaptureLuidAndAttributesArray(), SeCaptureSecurityDescriptor(), SeCaptureSecurityQos(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SeLocateProcessImageName(), SepAdtMarshallAuditRecord(), SepAppendDefaultDacl(), SepAppendPrimaryGroup(), SepAssemblePrivileges(), SepCreateToken(), SepDuplicateToken(), SepExpandDynamic(), SepFilterToken(), SepProbeAndCaptureString_U(), SepRegQueryHelper(), SepRmCallLsa(), SeQueryInformationToken(), SeQuerySecurityDescriptorInfo(), SeReportSecurityEvent(), SeSetAuditParameter(), WmipAddLogHeader(), WmipBuildMcaCmcEvent(), WmipCopyFromEventQueues(), WmipFireOffWmiEvent(), WmipFirmwareTableHandler(), WmipFlushBuffersWithMarker(), WmipGenerateMCAEventlog(), WmipGetRawMCAInfo(), WmipIoControl(), WmipNtDllLoggerInfo(), WmipProbeAndCaptureGuidObjectAttributes(), WmipProcessPrevMcaLogs(), WmipQuerySingleMultiple(), WmipQueryWmiDataBlock(), WmipSDRegistryQueryRoutine(), WmipSendEnableDisableRequest(), WmipStartLogger(), WmipTraceFile(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTraceRegistry(), WmipTranslateFileHandle(), WmipTranslatePDOInstanceNames(), WmipWriteMBToObject(), WmipWriteWnodeToObject(), WmiQueryTraceInformation(), WmiSetMark(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceMessageVa(), WmiTraceProcess(), and WmiUpdateTrace().
#define RtlCopyMemoryNonTemporal RtlCopyMemory
Definition at line 4320 of file ntrtl.h.
#define RtlEqualLuid (L1, L2)
Value:
(((L1)->LowPart == (L2)->LowPart) && \
                              ((L1)->HighPart  == (L2)->HighPart))
Definition at line 6190 of file ntrtl.h.
Referenced by ObpReferenceDeviceMap(), ObpSetCurrentProcessDeviceMap(), SeGetLogonIdDeviceMap(), SeIsChildToken(), SeIsChildTokenByPointer(), SeIsSiblingToken(), SeIsSiblingTokenByPointer(), SeMarkLogonSessionForTerminationNotification(), SepAdjustPrivileges(), SepCreateLogonSessionTrack(), SepCreateToken(), SepDeleteLogonSessionTrack(), SepDeReferenceLogonSession(), SepFilterPrivilegeAudits(), SepPrivilegeCheck(), SepReferenceLogonSession(), SepRemoveDisabledGroupsAndPrivileges(), and SeTokenCanImpersonate().
#define RtlEqualMemory (Destination, Source, Length) (!memcmp((Destination),(Source),(Length)))
Definition at line 4264 of file ntrtl.h.
Referenced by CmpFindMatchingDescriptorCell(), FsRtlAreNamesEqual(), FsRtlIsDbcsInExpression(), FsRtlIsNameInExpressionPrivate(), FsRtlNotifyFilterReportChange(), IopTrackLink(), IopVerifyDiskSignature(), MiCheckDosCalls(), MiVerifyImageHeader(), ObpCompareSecurityDescriptors(), RtlEqualSid(), RtlpGuidPresentInGuidList(), SepExamineSacl(), SepExamineSaclEx(), SepSidInSidAndAttributes(), SepSidInToken(), SepSidInTokenEx(), WmipGenerateFileName(), and WmipOpenGuidObject().
#define RtlFillBytes RtlFillMemory
Definition at line 4305 of file ntrtl.h.
#define RtlFillMemory (Destination, Length, Fill) memset((Destination),(Fill),(Length))
Definition at line 4267 of file ntrtl.h.
Referenced by HvFreeCell(), HvpDoAllocateCell(), IoWMIAllocateInstanceIds(), RtlSetBits(), and WmipPrepareHeader().
#define RtlImageDirectoryEntryToData32 RtlImageDirectoryEntryToData
Definition at line 4200 of file ntrtl.h.
#define RtlInitEmptyUnicodeString (_ucStr, _buf, _bufSize)
Value:
((_ucStr)->Buffer = (_buf), \
     (_ucStr)->Length = 0, \
     (_ucStr)->MaximumLength = (USHORT)(_bufSize))
Definition at line 2567 of file ntrtl.h.
#define RtlInitializeSplayLinks (Links)
Value:
{    \
    PRTL_SPLAY_LINKS _SplayLinks;            \
    _SplayLinks = (PRTL_SPLAY_LINKS)(Links); \
    _SplayLinks->Parent = _SplayLinks;   \
    _SplayLinks->LeftChild = NULL;       \
    _SplayLinks->RightChild = NULL;      \
    }
Definition at line 976 of file ntrtl.h.
Referenced by FsRtlAddToTunnelCache(), FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), FsRtlSplitLocks(), PfxInsertPrefix(), RtlInsertElementGenericTableFull(), and RtlInsertUnicodePrefix().
#define RtlInsertAsLeftChild (ParentLinks, ChildLinks)
Value:
{ \
    PRTL_SPLAY_LINKS _SplayParent;                      \
    PRTL_SPLAY_LINKS _SplayChild;                       \
    _SplayParent = (PRTL_SPLAY_LINKS)(ParentLinks);     \
    _SplayChild = (PRTL_SPLAY_LINKS)(ChildLinks);       \
    _SplayParent->LeftChild = _SplayChild;          \
    _SplayChild->Parent = _SplayParent;             \
    }
Definition at line 1090 of file ntrtl.h.
Referenced by FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), FsRtlSplitLocks(), PfxInsertPrefix(), RtlInsertElementGenericTableFull(), and RtlInsertUnicodePrefix().
#define RtlInsertAsRightChild (ParentLinks, ChildLinks)
Value:
{ \
    PRTL_SPLAY_LINKS _SplayParent;                       \
    PRTL_SPLAY_LINKS _SplayChild;                        \
    _SplayParent = (PRTL_SPLAY_LINKS)(ParentLinks);      \
    _SplayChild = (PRTL_SPLAY_LINKS)(ChildLinks);        \
    _SplayParent->RightChild = _SplayChild;          \
    _SplayChild->Parent = _SplayParent;              \
    }
Definition at line 1113 of file ntrtl.h.
Referenced by FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), FsRtlSplitLocks(), PfxInsertPrefix(), RtlInsertElementGenericTableFull(), and RtlInsertUnicodePrefix().
#define RtlInterlockedAndBits (Flags, Flag) InterlockedAnd((PLONG)(Flags), Flag)
Definition at line 7742 of file ntrtl.h.
#define RtlInterlockedAndBitsDiscardReturn (Flags, Flag) (VOID) RtlInterlockedAndBits(Flags, Flag)
Definition at line 7754 of file ntrtl.h.
#define RtlInterlockedClearBits (Flags, Flag) RtlInterlockedAndBits(Flags, ~(Flag))
Definition at line 7745 of file ntrtl.h.
#define RtlInterlockedClearBitsDiscardReturn (Flags, Flag) RtlInterlockedAndBitsDiscardReturn(Flags, ~(Flag))
Definition at line 7757 of file ntrtl.h.
#define RtlInterlockedSetBits (Flags, Flag) InterlockedOr((PLONG)(Flags), Flag)
Definition at line 7739 of file ntrtl.h.
Referenced by ExSetPoolFlags().
#define RtlInterlockedSetBitsDiscardReturn (Flags, Flag) (VOID) RtlInterlockedSetBits(Flags, Flag)
Definition at line 7751 of file ntrtl.h.
Referenced by ExpShutdownWorkerThreads().
#define RtlInterlockedXorBits (Flags, Flag) InterlockedXor(Flags, Flag)
Definition at line 7748 of file ntrtl.h.
#define RtlIntPtrToUnicodeString (Value, Base, String) RtlIntegerToUnicodeString(Value, Base, String)
Definition at line 2511 of file ntrtl.h.
#define RtlIpv4AddressToString RtlIpv4AddressToStringA
Definition at line 2476 of file ntrtl.h.
#define RtlIpv4AddressToStringEx RtlIpv4AddressToStringExA
Definition at line 2481 of file ntrtl.h.
#define RtlIpv4StringToAddress RtlIpv4StringToAddressA
Definition at line 2478 of file ntrtl.h.
#define RtlIpv4StringToAddressEx RtlIpv4StringToAddressExA
Definition at line 2483 of file ntrtl.h.
#define RtlIpv6AddressToString RtlIpv6AddressToStringA
Definition at line 2477 of file ntrtl.h.
#define RtlIpv6AddressToStringEx RtlIpv6AddressToStringExA
Definition at line 2482 of file ntrtl.h.
#define RtlIpv6StringToAddress RtlIpv6StringToAddressA
Definition at line 2479 of file ntrtl.h.
#define RtlIpv6StringToAddressEx RtlIpv6StringToAddressExA
Definition at line 2480 of file ntrtl.h.
#define RtlIsImpersonating () (NtCurrentTeb()->IsImpersonating ? TRUE : FALSE)
Definition at line 8015 of file ntrtl.h.
#define RtlIsLeftChild (Links)
Value:
(\
    (RtlLeftChild(RtlParent(Links)) == (PRTL_SPLAY_LINKS)(Links)) \
    )
Definition at line 1057 of file ntrtl.h.
Referenced by DeleteNodeFromTree(), FsRtlAddToTunnelCache(), RealPredecessor(), RealSuccessor(), RtlInsertElementGenericTableFullAvl(), RtlRealPredecessor(), RtlRealSuccessor(), RtlRemoveUnicodePrefix(), and RtlSplay().
#define RtlIsRightChild (Links)
Value:
(\
    (RtlRightChild(RtlParent(Links)) == (PRTL_SPLAY_LINKS)(Links)) \
    )
Definition at line 1072 of file ntrtl.h.
Referenced by DeleteNodeFromTree(), RealPredecessor(), RealSuccessor(), RtlRealPredecessor(), RtlRealSuccessor(), and RtlSplay().
#define RtlIsRoot (Links)
Value:
(\
    (RtlParent(Links) == (PRTL_SPLAY_LINKS)(Links)) \
    )
Definition at line 1042 of file ntrtl.h.
Referenced by FsRtlAddToTunnelCache(), PfxRemovePrefix(), RtlDelete(), RtlDeleteNoSplay(), RtlNextUnicodePrefix(), RtlRemoveUnicodePrefix(), RtlSplay(), and SwapSplayLinks().
#define RtlIsZeroLuid (L1) ((BOOLEAN) (((L1)->LowPart | (L1)->HighPart) == 0))
Definition at line 6199 of file ntrtl.h.
Referenced by NtSetInformationToken().
#define RtlLargeIntegerAnd (Result, Source, Mask) Result.QuadPart = Source.QuadPart & Mask.QuadPart
Definition at line 5013 of file ntrtl.h.
#define RtlLargeIntegerEqualTo (X, Y)
Value:
(\
    !(((X).LowPart ^ (Y).LowPart) | ((X).HighPart ^ (Y).HighPart)) \
)
Definition at line 5131 of file ntrtl.h.
#define RtlLargeIntegerEqualToZero (X)
Value:
(\
    !((X).LowPart | (X).HighPart)       \
)
Definition at line 5158 of file ntrtl.h.
#define RtlLargeIntegerGreaterOrEqualToZero (X)
Value:
(\
    (X).HighPart >= 0                            \
)
Definition at line 5154 of file ntrtl.h.
#define RtlLargeIntegerGreaterThan (X, Y)
Value:
(\
    (((X).HighPart == (Y).HighPart) && ((X).LowPart > (Y).LowPart)) || \
    ((X).HighPart > (Y).HighPart)                                      \
)
Definition at line 5121 of file ntrtl.h.
#define RtlLargeIntegerGreaterThanOrEqualTo (X, Y)
Value:
(\
    (((X).HighPart == (Y).HighPart) && ((X).LowPart >= (Y).LowPart)) || \
    ((X).HighPart > (Y).HighPart)                                       \
)
Definition at line 5126 of file ntrtl.h.
#define RtlLargeIntegerGreaterThanZero (X)
Value:
(\
    (((X).HighPart == 0) && ((X).LowPart > 0)) || \
    ((X).HighPart > 0 )                           \
)
Definition at line 5149 of file ntrtl.h.
#define RtlLargeIntegerLessOrEqualToZero (X)
Value:
(\
    ((X).HighPart < 0) || !((X).LowPart | (X).HighPart) \
)
Definition at line 5170 of file ntrtl.h.
#define RtlLargeIntegerLessThan (X, Y)
Value:
(\
    (((X).HighPart == (Y).HighPart) && ((X).LowPart < (Y).LowPart)) || \
    ((X).HighPart < (Y).HighPart)                                      \
)
Definition at line 5139 of file ntrtl.h.
#define RtlLargeIntegerLessThanOrEqualTo (X, Y)
Value:
(\
    (((X).HighPart == (Y).HighPart) && ((X).LowPart <= (Y).LowPart)) || \
    ((X).HighPart < (Y).HighPart)                                       \
)
Definition at line 5144 of file ntrtl.h.
#define RtlLargeIntegerLessThanZero (X)
Value:
(\
    ((X).HighPart < 0)                   \
)
Definition at line 5166 of file ntrtl.h.
#define RtlLargeIntegerNotEqualTo (X, Y)
Value:
(\
    (((X).LowPart ^ (Y).LowPart) | ((X).HighPart ^ (Y).HighPart)) \
)
Definition at line 5135 of file ntrtl.h.
#define RtlLargeIntegerNotEqualToZero (X)
Value:
(\
    ((X).LowPart | (X).HighPart)           \
)
Definition at line 5162 of file ntrtl.h.
#define RtlLeftChild (Links)
Value:
(\
    (PRTL_SPLAY_LINKS)(Links)->LeftChild \
    )
Definition at line 1011 of file ntrtl.h.
Referenced by FindNodeOrParent(), FsRtlAddToTunnelCache(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFindFirstOverlappingExclusiveNode(), FsRtlFindFirstOverlappingSharedNode(), FsRtlFindInTunnelCache(), FsRtlGetNextFileLock(), FsRtlPrivateFastUnlockAll(), FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), FsRtlPrivateResetLowestLockOffset(), FsRtlSplitLocks(), PfxFindPrefix(), PfxInsertPrefix(), RtlDelete(), RtlDeleteNoSplay(), RtlEnumerateGenericTable(), RtlEnumerateGenericTableWithoutSplaying(), RtlFindUnicodePrefix(), RtlInsertUnicodePrefix(), RtlNextUnicodePrefix(), RtlRealPredecessor(), RtlRealSuccessor(), RtlRemoveUnicodePrefix(), RtlSubtreePredecessor(), and RtlSubtreeSuccessor().
#define RtlMoveMemory (Destination, Source, Length) memmove((Destination),(Source),(Length))
Definition at line 4265 of file ntrtl.h.
Referenced by CmpAddSecurityCellToCache(), CmpAddToLeaf(), CmpCheckValueList(), CmpFindProfileOption(), CmpFindReusableCellFromCache(), CmpGetSymbolicLink(), CmpRemoveFromSecurityCache(), CmpRemoveSubKey(), CmpRemoveSubKeyCellNoCellRef(), CmpSplitLeaf(), FsRtlAddLargeEntry(), FsRtlRemoveLargeEntry(), HvReallocateCell(), IopDoNameTransmogrify(), MmGetFileNameForAddress(), ObGetObjectInformation(), ObpParseSymbolicLink(), ObpQueryNameString(), RtlAppendAsciizToString(), RtlAppendStringToString(), RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopySid(), RtlIpv6StringToAddressT(), RtlpExtendStackTraceDataBase(), RtlpInheritAcl2(), RtlpTraceDatabaseInternalAdd(), RtlSelfRelativeToAbsoluteSD(), RtlSelfRelativeToAbsoluteSD2(), RtlSetEnvironmentVariable(), SepConcatenatePrivileges(), SepFreeDefaultDacl(), SepFreePrimaryGroup(), SeQuerySecurityDescriptorInfo(), and WmipQueryGLRegistryRoutine().
#define RtlOemStringToCountedUnicodeSize (STRING)
Value:
(\
    (ULONG)(RtlOemStringToUnicodeSize(STRING) - sizeof(UNICODE_NULL)) \
    )
Definition at line 3093 of file ntrtl.h.
Referenced by FsRtlNotifyFilterReportChange(), and RtlOemStringToCountedUnicodeString().
#define RtlOemStringToUnicodeSize (STRING)
Value:
(\
    NLS_MB_OEM_CODE_PAGE_TAG ?                               \
    RtlxOemStringToUnicodeSize(STRING) :                     \
    ((STRING)->Length + sizeof(ANSI_NULL)) * sizeof(WCHAR) \
)
Definition at line 3080 of file ntrtl.h.
Referenced by RtlOemStringToUnicodeString().
#define RtlOffsetToPointer (B, O) ((PCHAR)(((PCHAR)(B)) + ((ULONG_PTR)(O))))
Definition at line 5664 of file ntrtl.h.
Referenced by RtlValidRelativeSecurityDescriptor(), and SeValidSecurityDescriptor().
#define RTLP_ADD_WITH_CARRY_OUT (FunctionName, Type, BaseFunction, BaseType)
Value:
FORCEINLINE \
BOOLEAN \
FunctionName(\
    Type *pc, \
    Type a, \
    Type b \
    ) \
{ \
    return BaseFunction((BaseType*)pc, a, b); \
}
Definition at line 7926 of file ntrtl.h.
#define RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32 (FunctionName, Type) RTLP_ADD_WITH_CARRY_OUT(FunctionName, Type, RtlUnsignedAddWithCarryOut32, unsigned __int32)
Definition at line 7940 of file ntrtl.h.
#define RTLP_ADD_WITH_CARRY_OUT_UNSIGNED64 (FunctionName, Type) RTLP_ADD_WITH_CARRY_OUT(FunctionName, Type, RtlUnsignedAddWithCarryOut64, unsigned __int64)
Definition at line 7943 of file ntrtl.h.
#define RTLP_ADD_WITH_CARRY_OUT_UNSIGNED_PTR (FunctionName, Type) RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32(FunctionName, Type)
Definition at line 7953 of file ntrtl.h.
#define RTLP_ADD_WITH_OVERFLOW_OUT RTLP_ADD_WITH_CARRY_OUT
Definition at line 7938 of file ntrtl.h.
#define RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED32 (FunctionName, Type) RTLP_ADD_WITH_OVERFLOW_OUT(FunctionName, Type, RtlSignedAddWithOverflowOut32, __int32)
Definition at line 7946 of file ntrtl.h.
#define RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED64 (FunctionName, Type) RTLP_ADD_WITH_OVERFLOW_OUT(FunctionName, Type, RtlSignedAddWithOverflowOut64, __int64)
Definition at line 7949 of file ntrtl.h.
#define RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED_PTR (FunctionName, Type) RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED32(FunctionName, Type)
Definition at line 7954 of file ntrtl.h.
#define RTLP_IMAGE_MAX_DOS_HEADER (256UL * RTL_MEG)
Definition at line 4116 of file ntrtl.h.
Referenced by RtlpImageNtHeader().
#define RtlParent (Links)
Value:
(\
    (PRTL_SPLAY_LINKS)(Links)->Parent \
    )
Definition at line 996 of file ntrtl.h.
Referenced by FsRtlAddToTunnelCache(), PfxRemovePrefix(), RtlDelete(), RtlNextUnicodePrefix(), RtlRealPredecessor(), RtlRealSuccessor(), RtlRemoveUnicodePrefix(), RtlSplay(), and SwapSplayLinks().
#define RtlPointerToOffset (B, P) ((ULONG)(((PCHAR)(P)) - ((PCHAR)(B))))
Definition at line 5695 of file ntrtl.h.
Referenced by RtlMakeSelfRelativeSD(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), SeAssignWorldSecurityDescriptor(), and SeCaptureSecurityDescriptor().
#define RtlRetrieveUlong (DEST_ADDRESS, SRC_ADDRESS)
Value:
if ((ULONG_PTR)SRC_ADDRESS & LONG_MASK) {                        \
             ((PUCHAR) DEST_ADDRESS)[0] = ((PUCHAR) SRC_ADDRESS)[0];  \
             ((PUCHAR) DEST_ADDRESS)[1] = ((PUCHAR) SRC_ADDRESS)[1];  \
             ((PUCHAR) DEST_ADDRESS)[2] = ((PUCHAR) SRC_ADDRESS)[2];  \
             ((PUCHAR) DEST_ADDRESS)[3] = ((PUCHAR) SRC_ADDRESS)[3];  \
         }                                                            \
         else {                                                       \
             *((PULONG) DEST_ADDRESS) = *((PULONG) SRC_ADDRESS);      \
         }
Definition at line 5621 of file ntrtl.h.
#define RtlRetrieveUshort (DEST_ADDRESS, SRC_ADDRESS)
Value:
if ((ULONG_PTR)SRC_ADDRESS & SHORT_MASK) {                       \
             ((PUCHAR) DEST_ADDRESS)[0] = ((PUCHAR) SRC_ADDRESS)[0];  \
             ((PUCHAR) DEST_ADDRESS)[1] = ((PUCHAR) SRC_ADDRESS)[1];  \
         }                                                            \
         else {                                                       \
             *((PUSHORT) DEST_ADDRESS) = *((PUSHORT) SRC_ADDRESS);    \
         }                                                            \
Definition at line 5575 of file ntrtl.h.
#define RtlRightChild (Links)
Value:
(\
    (PRTL_SPLAY_LINKS)(Links)->RightChild \
    )
Definition at line 1027 of file ntrtl.h.
Referenced by FindNodeOrParent(), FsRtlAddToTunnelCache(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFindFirstOverlappingExclusiveNode(), FsRtlFindFirstOverlappingSharedNode(), FsRtlFindInTunnelCache(), FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), FsRtlSplitLocks(), PfxFindPrefix(), PfxInsertPrefix(), RtlDelete(), RtlDeleteNoSplay(), RtlFindUnicodePrefix(), RtlInsertUnicodePrefix(), RtlRealPredecessor(), RtlRealSuccessor(), RtlRemoveUnicodePrefix(), RtlSubtreePredecessor(), and RtlSubtreeSuccessor().
#define RtlStoreUlong (ADDRESS, VALUE)
Value:
if ((ULONG_PTR)(ADDRESS) & LONG_MASK) {          \
             ((PUCHAR) (ADDRESS))[LONG_LEAST_SIGNIFICANT_BIT      ] = (UCHAR)(FIRSTBYTE(VALUE));    \
             ((PUCHAR) (ADDRESS))[LONG_3RD_MOST_SIGNIFICANT_BIT   ] = (UCHAR)(SECONDBYTE(VALUE));   \
             ((PUCHAR) (ADDRESS))[LONG_2ND_MOST_SIGNIFICANT_BIT   ] = (UCHAR)(THIRDBYTE(VALUE));    \
             ((PUCHAR) (ADDRESS))[LONG_MOST_SIGNIFICANT_BIT       ] = (UCHAR)(FOURTHBYTE(VALUE));   \
         }                                                \
         else {                                           \
             *((PULONG) (ADDRESS)) = (ULONG) (VALUE);     \
         }
Definition at line 5452 of file ntrtl.h.
#define RtlStoreUlonglong (ADDRESS, VALUE)
Value:
if ((ULONG_PTR)(ADDRESS) & LONGLONG_MASK) {            \
             RtlStoreUlong((ULONG_PTR)(ADDRESS),                \
                           (ULONGLONG)(VALUE) & 0xFFFFFFFF);    \
             RtlStoreUlong((ULONG_PTR)(ADDRESS)+sizeof(ULONG),  \
                           (ULONGLONG)(VALUE) >> 32);           \
         } else {                                               \
             *((PULONGLONG)(ADDRESS)) = (ULONGLONG)(VALUE);     \
         }
Definition at line 5496 of file ntrtl.h.
#define RtlStoreUlongPtr (ADDRESS, VALUE) RtlStoreUlong(ADDRESS,VALUE)
Definition at line 5539 of file ntrtl.h.
#define RtlStoreUshort (ADDRESS, VALUE)
Value:
if ((ULONG_PTR)(ADDRESS) & SHORT_MASK) {         \
             ((PUCHAR) (ADDRESS))[SHORT_LEAST_SIGNIFICANT_BIT] = (UCHAR)(FIRSTBYTE(VALUE));    \
             ((PUCHAR) (ADDRESS))[SHORT_MOST_SIGNIFICANT_BIT ] = (UCHAR)(SECONDBYTE(VALUE));   \
         }                                                \
         else {                                           \
             *((PUSHORT) (ADDRESS)) = (USHORT) VALUE;     \
         }
Definition at line 5405 of file ntrtl.h.
#define RtlUnicodeStringToAnsiSize (STRING)
Value:
(\
    NLS_MB_CODE_PAGE_TAG ?                                    \
    RtlxUnicodeStringToAnsiSize(STRING) :                     \
    ((STRING)->Length + sizeof(UNICODE_NULL)) / sizeof(WCHAR) \
)
Definition at line 2996 of file ntrtl.h.
Referenced by ExpSystemErrorHandler(), RtlUnicodeStringToAnsiString(), and RtlUpcaseUnicodeStringToAnsiString().
#define RtlUnicodeStringToCountedOemSize (STRING)
Value:
(\
    (ULONG)(RtlUnicodeStringToOemSize(STRING) - sizeof(ANSI_NULL)) \
    )
Definition at line 3035 of file ntrtl.h.
Referenced by RtlUnicodeStringToCountedOemString(), and RtlUpcaseUnicodeStringToCountedOemString().
#define RtlUnicodeStringToOemSize (STRING)
Value:
(\
    NLS_MB_OEM_CODE_PAGE_TAG ?                                \
    RtlxUnicodeStringToOemSize(STRING) :                      \
    ((STRING)->Length + sizeof(UNICODE_NULL)) / sizeof(WCHAR) \
)
Definition at line 3020 of file ntrtl.h.
Referenced by ExpSystemErrorHandler(), RtlUnicodeStringToOemString(), and RtlUpcaseUnicodeStringToOemString().
#define RtlZeroBytes RtlZeroMemory
Definition at line 4304 of file ntrtl.h.
Referenced by CcCopyWrite(), CcFastCopyWrite(), and CcFreeActiveVacb().
#define RtlZeroMemory (Destination, Length) memset((Destination),0,(Length))
Definition at line 4268 of file ntrtl.h.
Referenced by CcAllocateInitializeBcb(), CcAllocateObcb(), CcCopyWrite(), CcCreateVacbArray(), CcDeleteMbcb(), CcExtendVacbArray(), CcFastCopyWrite(), CcFindBitmapRangeToDirty(), CcInitializeCacheManager(), CcInitializeCacheMap(), CcInitializeVacbs(), CcPrefillVacbLevelZone(), CcPreparePinWrite(), CcPurgeAndClearCacheSection(), CcSetDirtyInMask(), CcZeroData(), CmGetSystemControlValues(), CmLoadKey(), CmpAllocatePostBlock(), CmpCreateObjectTypes(), CmpGetNameControlBlock(), CmpInitializeCache(), CmpOpenFileWithExtremePrejudice(), CmpOverwriteHive(), DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), ExCreatePoolTagTable(), ExEnableHandleTracing(), ExFreePoolWithTag(), ExInitializeResourceLite(), ExpAllocateHandleTable(), ExpAllocateTablePagedPool(), ExpEventInitialization(), ExpEventPairInitialization(), ExpExpandBigPageTable(), ExpExpandResourceOwnerTable(), ExpGetSystemFirmwareTableInformation(), ExpInitializeCallbacks(), ExpInitializeExecutive(), ExpInsertPoolTrackerExpansion(), ExpMutantInitialization(), ExpProfileInitialization(), ExpSemaphoreInitialization(), ExpSystemErrorHandler(), ExpTimerInitialization(), ExpUpdateDebugInfo(), ExpWin32Initialization(), ExpWorkerInitialization(), FsFilterCtrlInit(), FsRtlAllocateOplock(), FsRtlNotifyFilterChangeDirectory(), FsRtlRegisterUncProvider(), HalpDeleteMountLetter(), HvCloneHive(), HvDuplicateCell(), HvpAddBin(), HvpAdjustBitmap(), HvpAllocateMap(), HvpBuildMapAndCopy(), HvpEnlistFreeCells(), HvpFillFileName(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpInitMap(), HvWriteHive(), InitializePool(), IoAllocateDriverObjectExtension(), IoConnectInterrupt(), IoCreateController(), IoCreateDevice(), IoCreateDriver(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IoFastQueryNetworkAttributes(), IoInitializeIrp(), IoInitializeTimer(), IopAllocateErrorLogEntry(), IopCreateObjectTypes(), IopCreateVpb(), IopErrorLogThread(), IopInitializeBootLogging(), IopInitializeIrpStackProfiler(), IopLoadDriver(), IopMarshalIds(), IopParseDevice(), IopSendMessageToTrackService(), IoRaiseInformationalHardError(), IoReadPartitionTable(), IoWMIExecuteMethod(), IoWMIOpenBlock(), IoWMIQuerySingleInstance(), IoWMISetSingleInstance(), IoWMISetSingleItem(), Ke386CallBios(), KeContextToKframes(), KeI386GetLid(), KeRestoreMtrr(), KeSetPhysicalCacheTypeRange(), KeStartAllProcessors(), KeStartProfile(), Ki386AllocateContiguousMemory(), Ki386CreateIdentityMap(), KiAddRange(), KiCompleteEffectiveRangeChange(), KiFreezeTargetExecution(), KiInitializeContextThread(), KiInitializeKernel(), KiInitializeMTRR(), KiOpDecode(), KiStartEffectiveRangeChange(), LpcInitSystem(), LpcpCreatePort(), MiAllocateAweInfo(), MiAweViewRemover(), MiBuildImportsForBootDrivers(), MiCheckCacheAttributes(), MiCloneProcessAddressSpace(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreatePagingFileMap(), MiCreatePhysicalVadRoot(), MiDereferenceSession(), MiDetachSession(), MiGrowWsleHash(), MiInitializeSystemSpaceMap(), MiInitializeVadTableAvl(), MiInitMachineDependent(), MiInsertInSystemSpace(), MiInsertIoSpaceMap(), MiLoadUserSymbols(), MiLogPfnInformation(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiRememberUnloadedDriver(), MiResolveImageReferences(), MiSectionInitialization(), MiSecureVirtualMemory(), MiSessionCreateInternal(), MiSessionInsertImage(), MiWaitForInPageComplete(), MmCopyToCachedPage(), MmCreateSection(), MmFreeLoaderBlock(), MmIdentifyPhysicalMemory(), MmInitializeProcessAddressSpace(), MmLoadSystemImage(), MmPrefetchPagesIntoLockedMdl(), MxPopulatePageDirectories(), NtAcceptConnectPort(), NtAdjustPrivilegesToken(), NtAllocateVirtualMemory(), NtCreateDirectoryObject(), NtCreateJobObject(), NtCreatePagingFile(), NtDeleteFile(), NtOpenKey(), NtQueryAttributesFile(), NtQueryDirectoryObject(), NtQueryFullAttributesFile(), NtQueryInformationJobObject(), NtQueryObject(), NtQuerySystemInformation(), NtSecureConnectPort(), NtSetSystemInformation(), ObCreateObjectType(), ObDuplicateObject(), ObEnumerateObjectsByType(), ObInitSystem(), ObpCaptureObjectCreateInformation(), ObpInsertHandleCount(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), PerfInfoFileNameRunDown(), Psp386InstallIoHandler(), PspCaptureTokenFilter(), PspCreateLdt(), PspCreateProcess(), PspCreateThread(), PspGetSetContextInternal(), PspInitPhase0(), PspSetLdtInformation(), PspSetQuotaLimits(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawCheckForDismount(), RawInitializeVcb(), RawQueryFsDeviceInfo(), RawQueryFsSizeInfo(), RawQueryFsVolumeInfo(), RtlClearAllBits(), RtlClearBits(), RtlCreateAtomTable(), RtlCreateProcessParameters(), RtlCreateSecurityDescriptor(), RtlCreateSecurityDescriptorRelative(), RtlCreateUserProcess(), RtlDestroyAtomTable(), RtlEraseUnicodeString(), RtlInitializeContext(), RtlInitializeGenericTableAvl(), RtlInitializeStackTraceDataBase(), RtlInsertElementGenericTableFullAvl(), RtlIpv6StringToAddressT(), RtlMakeSelfRelativeSD(), RtlpCopyProcString(), RtlpFreeStack(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), RtlQueryTimeZoneInformation(), RtlResetRtlTranslations(), RtlSetActiveTimeBias(), RtlTraceDatabaseCreate(), SeAuditHandleDuplication(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCreateAccessStateEx(), SeInitializeProcessAuditName(), SeOperationAuditAlarm(), SepAccessCheck(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), SepCreateLogonSessionTrack(), SepTokenInitialization(), SeReportSecurityEvent(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipBuildMcaCmcEvent(), WmipCreateGuidObject(), WmipCreateLogFile(), WmipDeleteMethod(), WmipDisableKernelTrace(), WmipDriverEntry(), WmipEnableKernelTrace(), WmipGetGuidSecurityDescriptor(), WmipInitContext(), WmipInitializeDataStructs(), WmipInitializeSecurity(), WmipIoControl(), WmipQueryAllDataMultiple(), WmipQuerySingleMultiple(), WmipQueryWmiDataBlock(), WmipReceiveNotifications(), WmipSendEnableDisableRequest(), WmipSendNotification(), WmipShutdown(), WmipStartGlobalLogger(), WmipStartLogger(), WmipSwitchToNewFile(), WmipTraceRegistry(), WmipTranslatePDOInstanceNames(), WmipWriteMBToObject(), WmiQueryTraceInformation(), WmiStartContextSwapTrace(), and WmiUpdateTrace().
#define SECONDBYTE (VALUE) (((VALUE) >> 8) & LOWBYTE_MASK)
Definition at line 5358 of file ntrtl.h.
#define SET_PARSE_MESSAGE_CONTEXT_FLAG (ctx, flag) ((ctx)->fFlags |= (flag))
Definition at line 7001 of file ntrtl.h.
#define SHORT_LEAST_SIGNIFICANT_BIT 0
Definition at line 5366 of file ntrtl.h.
#define SHORT_MASK (SHORT_SIZE - 1)
Definition at line 5350 of file ntrtl.h.
#define SHORT_MOST_SIGNIFICANT_BIT 1
Definition at line 5367 of file ntrtl.h.
#define SHORT_SIZE (sizeof(USHORT))
Definition at line 5349 of file ntrtl.h.
#define SLIST_ENTRY SINGLE_LIST_ENTRY
Definition at line 119 of file ntrtl.h.
#define STATICGUIDOF (guid) STATIC_##guid
Definition at line 3264 of file ntrtl.h.
#define TEST_PARSE_MESSAGE_CONTEXT_FLAG (ctx, flag) ((ctx)->fFlags & (flag))
Definition at line 7000 of file ntrtl.h.
#define THIRDBYTE (VALUE) (((VALUE) >> 16) & LOWBYTE_MASK)
Definition at line 5359 of file ntrtl.h.
#define VER_AND 6
Definition at line 7617 of file ntrtl.h.
#define VER_BUILDNUMBER 0x0000004
Definition at line 7629 of file ntrtl.h.
#define VER_CONDITION_MASK 7
Definition at line 7620 of file ntrtl.h.
#define VER_EQUAL 1
Definition at line 7612 of file ntrtl.h.
#define VER_GREATER 2
Definition at line 7613 of file ntrtl.h.
#define VER_GREATER_EQUAL 3
Definition at line 7614 of file ntrtl.h.
#define VER_LESS 4
Definition at line 7615 of file ntrtl.h.
#define VER_LESS_EQUAL 5
Definition at line 7616 of file ntrtl.h.
#define VER_MAJORVERSION 0x0000002
Definition at line 7628 of file ntrtl.h.
#define VER_MINORVERSION 0x0000001
Definition at line 7627 of file ntrtl.h.
#define VER_NT_DOMAIN_CONTROLLER 0x0000002
Definition at line 7641 of file ntrtl.h.
#define VER_NT_SERVER 0x0000003
Definition at line 7642 of file ntrtl.h.
#define VER_NT_WORKSTATION 0x0000001
Definition at line 7640 of file ntrtl.h.
#define VER_NUM_BITS_PER_CONDITION_MASK 3
Definition at line 7621 of file ntrtl.h.
#define VER_OR 7
Definition at line 7618 of file ntrtl.h.
#define VER_PLATFORM_WIN32_NT 2
Definition at line 7650 of file ntrtl.h.
#define VER_PLATFORM_WIN32_WINDOWS 1
Definition at line 7649 of file ntrtl.h.
#define VER_PLATFORM_WIN32s 0
Definition at line 7648 of file ntrtl.h.
#define VER_PLATFORMID 0x0000008
Definition at line 7630 of file ntrtl.h.
#define VER_PRODUCT_TYPE 0x0000080
Definition at line 7634 of file ntrtl.h.
#define VER_SERVICEPACKMAJOR 0x0000020
Definition at line 7632 of file ntrtl.h.
#define VER_SERVICEPACKMINOR 0x0000010
Definition at line 7631 of file ntrtl.h.
#define VER_SET_CONDITION (_m_, _t_, _c_) ((_m_)=VerSetConditionMask((_m_),(_t_),(_c_)))
Definition at line 7662 of file ntrtl.h.
#define VER_SUITENAME 0x0000040
Definition at line 7633 of file ntrtl.h.
#define vKdPrintEx (_x_)
Definition at line 4575 of file ntrtl.h.
#define vKdPrintExWithPrefix (_x_)
Definition at line 4576 of file ntrtl.h.
Typedef Documentation
typedef PVOID Buffer
Definition at line 563 of file ntrtl.h.
typedef CLONG ByteSize
Definition at line 550 of file ntrtl.h.
typedef struct _COMPRESSED_DATA_INFO COMPRESSED_DATA_INFO
typedef struct _CURDIR CURDIR
typedef struct _CURDIR64 CURDIR64
typedef enum _DPFLTR_TYPE DPFLTR_TYPE
typedef PVOID FirstStruct
Definition at line 536 of file ntrtl.h.
typedef struct _GENERATE_NAME_CONTEXT GENERATE_NAME_CONTEXT
typedef struct _LAST_EXCEPTION_LOG LAST_EXCEPTION_LOG
typedef LPOSVERSIONINFOA LPOSVERSIONINFO
Definition at line 7569 of file ntrtl.h.
typedef struct _OSVERSIONINFOA * LPOSVERSIONINFOA
typedef LPOSVERSIONINFOEXA LPOSVERSIONINFOEX
Definition at line 7605 of file ntrtl.h.
typedef struct _OSVERSIONINFOEXA * LPOSVERSIONINFOEXA
typedef struct _OSVERSIONINFOEXW * LPOSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW * LPOSVERSIONINFOW
typedef PVOID PVOID MatchData
Definition at line 583 of file ntrtl.h.
typedef struct _MESSAGE_RESOURCE_BLOCK MESSAGE_RESOURCE_BLOCK
typedef struct _MESSAGE_RESOURCE_DATA MESSAGE_RESOURCE_DATA
typedef struct _MESSAGE_RESOURCE_ENTRY MESSAGE_RESOURCE_ENTRY
typedef OSVERSIONINFOA OSVERSIONINFO
Definition at line 7567 of file ntrtl.h.
typedef struct _OSVERSIONINFOA OSVERSIONINFOA
typedef OSVERSIONINFOEXA OSVERSIONINFOEX
Definition at line 7603 of file ntrtl.h.
typedef struct _OSVERSIONINFOEXA OSVERSIONINFOEXA
typedef struct _OSVERSIONINFOEXW OSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW OSVERSIONINFOW
typedef struct _PARSE_MESSAGE_CONTEXT PARSE_MESSAGE_CONTEXT
typedef COMPRESSED_DATA_INFO* PCOMPRESSED_DATA_INFO
Definition at line 3692 of file ntrtl.h.
typedef struct _CURDIR * PCURDIR
typedef struct _CURDIR64 * PCURDIR64
typedef GENERATE_NAME_CONTEXT* PGENERATE_NAME_CONTEXT
Definition at line 3328 of file ntrtl.h.
typedef struct _LAST_EXCEPTION_LOG * PLAST_EXCEPTION_LOG
typedef struct _MESSAGE_RESOURCE_BLOCK * PMESSAGE_RESOURCE_BLOCK
typedef struct _MESSAGE_RESOURCE_DATA * PMESSAGE_RESOURCE_DATA
typedef struct _MESSAGE_RESOURCE_ENTRY * PMESSAGE_RESOURCE_ENTRY
typedef POSVERSIONINFOA POSVERSIONINFO
Definition at line 7568 of file ntrtl.h.
typedef struct _OSVERSIONINFOA * POSVERSIONINFOA
typedef POSVERSIONINFOEXA POSVERSIONINFOEX
Definition at line 7604 of file ntrtl.h.
typedef struct _OSVERSIONINFOEXA * POSVERSIONINFOEXA
typedef struct _OSVERSIONINFOEXW * POSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW * POSVERSIONINFOW
typedef struct _PARSE_MESSAGE_CONTEXT * PPARSE_MESSAGE_CONTEXT
typedef PREFIX_TABLE* PPREFIX_TABLE
Definition at line 3517 of file ntrtl.h.
typedef PREFIX_TABLE_ENTRY* PPREFIX_TABLE_ENTRY
Definition at line 3510 of file ntrtl.h.
typedef struct _PREFIX_TABLE PREFIX_TABLE
typedef struct _PREFIX_TABLE_ENTRY PREFIX_TABLE_ENTRY
typedef RTL_AVL_TABLE* PRTL_AVL_TABLE
Definition at line 634 of file ntrtl.h.
typedef RTL_BALANCED_LINKS* PRTL_BALANCED_LINKS
Definition at line 612 of file ntrtl.h.
typedef RTL_BITMAP* PRTL_BITMAP
Definition at line 5711 of file ntrtl.h.
typedef RTL_BITMAP_RUN* PRTL_BITMAP_RUN
Definition at line 5870 of file ntrtl.h.
typedef enum RTL_BSD_ITEM_TYPE * PRTL_BSD_ITEM_TYPE
typedef BOOLEAN(* PRTL_CONFLICT_RANGE_CALLBACK) (IN PVOID Context, IN PRTL_RANGE Range)
Definition at line 7368 of file ntrtl.h.
typedef struct _RTL_DRIVE_LETTER_CURDIR * PRTL_DRIVE_LETTER_CURDIR
typedef struct _RTL_DRIVE_LETTER_CURDIR64 * PRTL_DRIVE_LETTER_CURDIR64
typedef RTL_GENERIC_TABLE* PRTL_GENERIC_TABLE
Definition at line 1306 of file ntrtl.h.
typedef NTSTATUS(NTAPI * PRTL_HEAP_COMMIT_ROUTINE) (IN PVOID Base, IN OUT PVOID *CommitAddress, IN OUT PSIZE_T CommitSize)
Definition at line 1552 of file ntrtl.h.
typedef struct _RTL_HEAP_PARAMETERS * PRTL_HEAP_PARAMETERS
typedef struct _OSVERSIONINFOEXW * PRTL_OSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW * PRTL_OSVERSIONINFOW
typedef struct _RTL_PROCESS_BACKTRACE_INFORMATION * PRTL_PROCESS_BACKTRACE_INFORMATION
typedef struct _RTL_PROCESS_BACKTRACES * PRTL_PROCESS_BACKTRACES
typedef struct _RTL_PROCESS_LOCK_INFORMATION * PRTL_PROCESS_LOCK_INFORMATION
typedef struct _RTL_PROCESS_LOCKS * PRTL_PROCESS_LOCKS
typedef NTSTATUS(NTAPI * PRTL_QUERY_REGISTRY_ROUTINE) (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
Definition at line 2096 of file ntrtl.h.
typedef struct _RTL_QUERY_REGISTRY_TABLE * PRTL_QUERY_REGISTRY_TABLE
typedef struct _RTL_RANGE * PRTL_RANGE
typedef struct _RTL_RANGE_LIST * PRTL_RANGE_LIST
typedef struct _RANGE_LIST_ITERATOR * PRTL_RANGE_LIST_ITERATOR
typedef struct _RTL_RXACT_CONTEXT * PRTL_RXACT_CONTEXT
typedef struct _RTL_RXACT_LOG * PRTL_RXACT_LOG
typedef enum _RTL_RXACT_OPERATION * PRTL_RXACT_OPERATION
typedef NTSTATUS(* PRTL_SECURE_MEMORY_CACHE_CALLBACK) (IN PVOID Addr, IN SIZE_T Range)
Definition at line 7697 of file ntrtl.h.
typedef RTL_SPLAY_LINKS* PRTL_SPLAY_LINKS
Definition at line 962 of file ntrtl.h.
typedef struct _RTL_STACK_CONTEXT * PRTL_STACK_CONTEXT
typedef struct _RTL_STACK_CONTEXT_ENTRY * PRTL_STACK_CONTEXT_ENTRY
typedef struct _RTL_TIME_ZONE_INFORMATION * PRTL_TIME_ZONE_INFORMATION
typedef struct _RTL_TRACE_BLOCK * PRTL_TRACE_BLOCK
typedef struct _RTL_TRACE_DATABASE* PRTL_TRACE_DATABASE
Definition at line 1889 of file ntrtl.h.
typedef struct _RTL_TRACE_ENUMERATE * PRTL_TRACE_ENUMERATE
typedef struct _RTL_USER_PROCESS_INFORMATION * PRTL_USER_PROCESS_INFORMATION
typedef struct _RTL_USER_PROCESS_INFORMATION64 * PRTL_USER_PROCESS_INFORMATION64
typedef struct _RTL_USER_PROCESS_PARAMETERS * PRTL_USER_PROCESS_PARAMETERS
typedef struct _RTL_USER_PROCESS_PARAMETERS64 * PRTL_USER_PROCESS_PARAMETERS64
typedef union _SLIST_HEADER * PSLIST_HEADER
typedef TIME_FIELDS* PTIME_FIELDS
Definition at line 5190 of file ntrtl.h.
typedef UNICODE_PREFIX_TABLE* PUNICODE_PREFIX_TABLE
Definition at line 3576 of file ntrtl.h.
typedef UNICODE_PREFIX_TABLE_ENTRY* PUNICODE_PREFIX_TABLE_ENTRY
Definition at line 3568 of file ntrtl.h.
typedef NTSTATUS(* PUSER_PROCESS_START_ROUTINE) (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
Definition at line 4012 of file ntrtl.h.
typedef NTSTATUS(* PUSER_THREAD_START_ROUTINE) (PVOID ThreadParameter)
Definition at line 4016 of file ntrtl.h.
typedef struct _RTL_AVL_TABLE RTL_AVL_TABLE
typedef struct _RTL_BALANCED_LINKS RTL_BALANCED_LINKS
typedef struct _RTL_BITMAP RTL_BITMAP
typedef struct _RTL_BITMAP_RUN RTL_BITMAP_RUN
typedef struct _RTL_DRIVE_LETTER_CURDIR RTL_DRIVE_LETTER_CURDIR
typedef struct _RTL_DRIVE_LETTER_CURDIR64 RTL_DRIVE_LETTER_CURDIR64
typedef RTL_GENERIC_COMPARE_RESULTS
typedef struct _RTL_GENERIC_TABLE RTL_GENERIC_TABLE
typedef struct _RTL_HEAP_PARAMETERS RTL_HEAP_PARAMETERS
typedef struct _OSVERSIONINFOEXW RTL_OSVERSIONINFOEXW
typedef struct _OSVERSIONINFOW RTL_OSVERSIONINFOW
typedef struct _RTL_PROCESS_BACKTRACE_INFORMATION RTL_PROCESS_BACKTRACE_INFORMATION
typedef struct _RTL_PROCESS_BACKTRACES RTL_PROCESS_BACKTRACES
typedef struct _RTL_PROCESS_LOCK_INFORMATION RTL_PROCESS_LOCK_INFORMATION
typedef struct _RTL_PROCESS_LOCKS RTL_PROCESS_LOCKS
typedef struct _RTL_QUERY_REGISTRY_TABLE RTL_QUERY_REGISTRY_TABLE
typedef struct _RTL_RANGE RTL_RANGE
typedef struct _RTL_RANGE_LIST RTL_RANGE_LIST
typedef struct _RANGE_LIST_ITERATOR RTL_RANGE_LIST_ITERATOR
typedef struct _RTL_RXACT_CONTEXT RTL_RXACT_CONTEXT
typedef struct _RTL_RXACT_LOG RTL_RXACT_LOG
typedef enum _RTL_RXACT_OPERATION RTL_RXACT_OPERATION
typedef struct _RTL_SPLAY_LINKS RTL_SPLAY_LINKS
typedef struct _RTL_STACK_CONTEXT RTL_STACK_CONTEXT
typedef struct _RTL_STACK_CONTEXT_ENTRY RTL_STACK_CONTEXT_ENTRY
typedef struct _RTL_TIME_ZONE_INFORMATION RTL_TIME_ZONE_INFORMATION
typedef struct _RTL_TRACE_BLOCK RTL_TRACE_BLOCK
typedef struct _RTL_TRACE_ENUMERATE RTL_TRACE_ENUMERATE
typedef ULONG(* RTL_TRACE_HASH_FUNCTION) (ULONG Count, PVOID *Trace)
Definition at line 1883 of file ntrtl.h.
typedef struct _RTL_USER_PROCESS_INFORMATION RTL_USER_PROCESS_INFORMATION
typedef struct _RTL_USER_PROCESS_INFORMATION64 RTL_USER_PROCESS_INFORMATION64
typedef struct _RTL_USER_PROCESS_PARAMETERS RTL_USER_PROCESS_PARAMETERS
typedef struct _RTL_USER_PROCESS_PARAMETERS64 RTL_USER_PROCESS_PARAMETERS64
typedef PVOID PVOID SecondStruct
Definition at line 536 of file ntrtl.h.
typedef union _SLIST_HEADER SLIST_HEADER
typedef enum _TABLE_SEARCH_RESULT TABLE_SEARCH_RESULT
typedef struct _TIME_FIELDS TIME_FIELDS
typedef struct _UNICODE_PREFIX_TABLE UNICODE_PREFIX_TABLE
typedef struct _UNICODE_PREFIX_TABLE_ENTRY UNICODE_PREFIX_TABLE_ENTRY
typedef PVOID UserData
Definition at line 583 of file ntrtl.h.
Enumeration Type Documentation
enum _DPFLTR_TYPE
Enumerator
DPFLTR_SYSTEM_ID
DPFLTR_SMSS_ID
DPFLTR_SETUP_ID
DPFLTR_NTFS_ID
DPFLTR_FSTUB_ID
DPFLTR_CRASHDUMP_ID
DPFLTR_CDAUDIO_ID
DPFLTR_CDROM_ID
DPFLTR_CLASSPNP_ID
DPFLTR_DISK_ID
DPFLTR_REDBOOK_ID
DPFLTR_STORPROP_ID
DPFLTR_SCSIPORT_ID
DPFLTR_SCSIMINIPORT_ID
DPFLTR_CONFIG_ID
DPFLTR_I8042PRT_ID
DPFLTR_SERMOUSE_ID
DPFLTR_LSERMOUS_ID
DPFLTR_KBDHID_ID
DPFLTR_MOUHID_ID
DPFLTR_KBDCLASS_ID
DPFLTR_MOUCLASS_ID
DPFLTR_TWOTRACK_ID
DPFLTR_WMILIB_ID
DPFLTR_ACPI_ID
DPFLTR_AMLI_ID
DPFLTR_HALIA64_ID
DPFLTR_VIDEO_ID
DPFLTR_SVCHOST_ID
DPFLTR_VIDEOPRT_ID
DPFLTR_TCPIP_ID
DPFLTR_DMSYNTH_ID
DPFLTR_NTOSPNP_ID
DPFLTR_FASTFAT_ID
DPFLTR_SAMSS_ID
DPFLTR_PNPMGR_ID
DPFLTR_NETAPI_ID
DPFLTR_SCSERVER_ID
DPFLTR_SCCLIENT_ID
DPFLTR_SERIAL_ID
DPFLTR_SERENUM_ID
DPFLTR_UHCD_ID
DPFLTR_RPCPROXY_ID
DPFLTR_AUTOCHK_ID
DPFLTR_DCOMSS_ID
DPFLTR_UNIMODEM_ID
DPFLTR_SIS_ID
DPFLTR_FLTMGR_ID
DPFLTR_WMICORE_ID
DPFLTR_BURNENG_ID
DPFLTR_IMAPI_ID
DPFLTR_SXS_ID
DPFLTR_FUSION_ID
DPFLTR_IDLETASK_ID
DPFLTR_SOFTPCI_ID
DPFLTR_TAPE_ID
DPFLTR_MCHGR_ID
DPFLTR_IDEP_ID
DPFLTR_PCIIDE_ID
DPFLTR_FLOPPY_ID
DPFLTR_FDC_ID
DPFLTR_TERMSRV_ID
DPFLTR_W32TIME_ID
DPFLTR_PREFETCHER_ID
DPFLTR_RSFILTER_ID
DPFLTR_FCPORT_ID
DPFLTR_PCI_ID
DPFLTR_DMIO_ID
DPFLTR_DMCONFIG_ID
DPFLTR_DMADMIN_ID
DPFLTR_WSOCKTRANSPORT_ID
DPFLTR_VSS_ID
DPFLTR_PNPMEM_ID
DPFLTR_PROCESSOR_ID
DPFLTR_DMSERVER_ID
DPFLTR_SR_ID
DPFLTR_INFINIBAND_ID
DPFLTR_IHVDRIVER_ID
DPFLTR_IHVVIDEO_ID
DPFLTR_IHVAUDIO_ID
DPFLTR_IHVNETWORK_ID
DPFLTR_IHVSTREAMING_ID
DPFLTR_IHVBUS_ID
DPFLTR_HPS_ID
DPFLTR_RTLTHREADPOOL_ID
DPFLTR_LDR_ID
DPFLTR_TCPIP6_ID
DPFLTR_ISAPNP_ID
DPFLTR_SHPC_ID
DPFLTR_STORPORT_ID
DPFLTR_STORMINIPORT_ID
DPFLTR_PRINTSPOOLER_ID
DPFLTR_VSSDYNDISK_ID
DPFLTR_VERIFIER_ID
DPFLTR_VDS_ID
DPFLTR_VDSBAS_ID
DPFLTR_VDSDYNDR_ID
DPFLTR_VDSUTIL_ID
DPFLTR_DFRGIFC_ID
DPFLTR_DEFAULT_ID
DPFLTR_MM_ID
DPFLTR_DFSC_ID
DPFLTR_WOW64_ID
DPFLTR_ENDOFTABLE_ID
Definition at line 8043 of file ntrtl.h.
enum _RTL_GENERIC_COMPARE_RESULTS
Enumerator
GenericLessThan
GenericGreaterThan
GenericEqual
Definition at line 499 of file ntrtl.h.
enum _RTL_RXACT_OPERATION
Enumerator
RtlRXactOperationDelete
RtlRXactOperationSetValue
RtlRXactOperationDelAttribute
RtlRXactOperationSetAttribute
Definition at line 7026 of file ntrtl.h.
enum _TABLE_SEARCH_RESULT
Enumerator
TableEmptyTree
TableFoundNode
TableInsertAsLeft
TableInsertAsRight
Definition at line 488 of file ntrtl.h.
enum RTL_BSD_ITEM_TYPE
Enumerator
RtlBsdItemVersionNumber
RtlBsdItemProductType
RtlBsdItemAabEnabled
RtlBsdItemAabTimeout
RtlBsdItemBootGood
RtlBsdItemBootShutdown
RtlBsdItemMax
Definition at line 7808 of file ntrtl.h.
Function Documentation
typedef BOOLEAN (NTAPI * PRTL_OKAY_TO_LOCK_ROUTINE)
VOID NTAPI DbgBreakPoint (VOID)
Referenced by __bcount(), CcInsertIntoCleanSharedCacheMapList(), CmpCheckKey(), CmpDoCreateChild(), CmpDoOpen(), CmpFileWriteThroughCache(), CmpLoadHiveThread(), CmpParseKey(), CmpSecurityExceptionFilter(), ExInitializeZone(), ExpCheckForResource(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerInline(), ExpUpdateDebugInfo(), ExpWaitForResource(), KeUpdateRunTime(), KiFreezeTargetExecution(), KiInitMachineDependent(), KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), MiBuildImportsForBootDrivers(), MiCheckCacheAttributes(), MiCheckPdeForSessionSpace(), MiCompleteProtoPteFault(), MiCreateImageFileMap(), MiDeleteVirtualAddresses(), MiDispatchFault(), MiFindEmptyAddressRange(), MiFindLargePageMemory(), MiFlushSectionInternal(), MiGatherMappedPages(), MiIdentifyPfn(), MiInsertIoSpaceMap(), MiNoPagesLastChance(), MiResolvePageFileFault(), MiSetProtectionOnSection(), MiWriteComplete(), MmAccessFault(), MmCleanProcessAddressSpace(), MmLoadSystemImage(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmSessionDelete(), NtQuerySystemInformation(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), ObpCaptureObjectCreateInformation(), ObpInitSecurityDescriptorCache(), ObpInsertDirectoryEntry(), ObpReferenceSecurityDescriptor(), PspCatchCriticalBreak(), RtlAssert(), RtlpWalkFrameChainExceptionFilter(), SeCaptureSubjectContextEx(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), and SeReleaseSubjectContext().
NTSYSAPI VOID NTAPI DbgBreakPointWithStatus (IN ULONG Status)
Referenced by ExpDebuggerWorker(), ExpInitializeExecutive(), KdCheckForDebugBreak(), KiBugCheckDebugBreak(), and vDbgPrintExWithPrefixInternal().
NTSYSAPI VOID NTAPI DbgCommandString (__in PCH Name, __in PCH Command)
Definition at line 489 of file debug.c.
References BREAKPOINT_COMMAND_STRING, _STRING::Buffer, DebugService2(), _STRING::Length, and strlen().
NTSYSAPI VOID NTAPI DbgLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
Definition at line 414 of file debug.c.
References _KD_SYMBOLS_INFO::BaseOfDll, BREAKPOINT_LOAD_SYMBOLS, _KD_SYMBOLS_INFO::CheckSum, _IMAGE_OPTIONAL_HEADER::CheckSum, DebugService2(), NULL, _IMAGE_NT_HEADERS::OptionalHeader, _KD_SYMBOLS_INFO::ProcessId, RtlImageNtHeader(), _KD_SYMBOLS_INFO::SizeOfImage, and _IMAGE_OPTIONAL_HEADER::SizeOfImage.
Referenced by ExpInitializeExecutive(), MiLoadUserSymbols(), and MmLoadSystemImage().
ULONG __cdecl DbgPrint (__in PCH Format, ...)
Definition at line 41 of file debug.c.
References TRUE, va_start, and vDbgPrintExWithPrefixInternal().
Referenced by CcInsertIntoCleanSharedCacheMapList(), CmpHysteresisTest(), ExInitializeZone(), ExMapHandleToPointerEx(), ExpCheckForResource(), ExpDebuggerWorker(), ExpUpdateDebugInfo(), ExpWaitForResource(), ExpWorkerThread(), HvpRecoverData(), InitializeSListHead(), IoAssignDriveLetters(), IoInitSystem(), IopCreateArcNames(), IopCreateArcNamesDisk(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopStoreSystemPartitionInformation(), IoShutdownSystem(), KeBugCheck2(), KeConnectInterrupt(), KeUpdateRunTime(), KiGetVectorInfo(), KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), LdrRelocateImageWithBias(), LookupEntryPoint(), NtCreateProfile(), NtQuerySystemInformation(), NtRaiseHardError(), ObpAllocateObject(), ObpFreeObject(), ObpInsertDirectoryEntry(), Ps386GetVdmIoHandler(), PsLocateSystemDll(), PsMapSystemDll(), Psp386GetVdmIoHandler(), Psp386InsertVdmIoHandlerBlock(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspCatchCriticalBreak(), PspInitializeSystemDll(), RtlAssert(), RtlCreateUserThread(), RtlFindClearRuns(), RtlpCallQueryRegistryRoutine(), RtlpCreateStack(), RtlpFreeStack(), RtlpOpenImageFile(), RtlpQueryRegistryDirect(), RtlpTraceDatabaseInternalAdd(), RtlpWalkFrameChainExceptionFilter(), RtlQueryRegistryValues(), RtlTraceDatabaseDestroy(), SeAccessCheck(), SeCaptureAuditPolicy(), SeImpersonateClient(), SeInitializeProcessAuditName(), SepCreateLogonSessionTrack(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), and SeTokenCanImpersonate().
NTSYSAPI ULONG __cdecl DbgPrintEx (__in ULONG ComponentId, __in ULONG Level, __in PCH Format, ...)
Definition at line 116 of file debug.c.
References TRUE, va_start, and vDbgPrintExWithPrefixInternal().
Referenced by CmpDoFileSetSize(), CmpDumpOneKeyBody(), CmpFileFlush(), CmpFileRead(), CmpFileWrite(), CmpFreeAllMemory(), CmpLoadHiveThread(), CmpSecurityExceptionFilter(), HvpDoWriteHive(), HvpFindNextDirtyBlock(), HvpGrowLog1(), HvpGrowLog2(), MiAllocatePagesForMdl(), MiAttemptPageFileReduction(), MiBuildImportsForBootDrivers(), MiCheckCacheAttributes(), MiCheckPdeForSessionSpace(), MiCompleteProtoPteFault(), MiComputeSystemTrimCriteria(), MiCreateImageFileMap(), MiDeleteVirtualAddresses(), MiDetermineTrimAmount(), MiDispatchFault(), MiEnablePagingOfDriver(), MiFindEmptyAddressRange(), MiFindInitializationCode(), MiFindLargePageMemory(), MiFlushSectionInternal(), MiGatherMappedPages(), MiIdentifyPfn(), MiInitializeMemoryEvents(), MiInsertIoSpaceMap(), MiLoadImageSection(), MiNoPagesLastChance(), MiPurgeImageSection(), MiRearrangeWorkingSetExpansionList(), MiReportPhysicalMemory(), MiResolvePageFileFault(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), MiSetProtectionOnSection(), MiWaitForInPageComplete(), MiWriteComplete(), MmAccessFault(), MmCleanProcessAddressSpace(), MmGrowKernelStackEx(), MmInitSystem(), MmLoadSystemImage(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmResetDriverPaging(), MmSessionDelete(), NtCreateKey(), NtCreatePagingFile(), NtQueryOpenSubKeys(), and WmipTracePageFault().
NTSYSAPI ULONG __cdecl DbgPrintReturnControlC (__in PCHAR Format, ...)
Definition at line 78 of file debug.c.
References FALSE, va_start, and vDbgPrintExWithPrefixInternal().
NTSYSAPI ULONG NTAPI DbgPrompt (__in PCH Prompt, __out_bcount(Length) PCH Response, __in ULONG Length)
Definition at line 364 of file debug.c.
References _STRING::Buffer, DebugPrompt(), _STRING::Length, _STRING::MaximumLength, and strlen().
Referenced by PspCatchCriticalBreak(), and RtlAssert().
NTSYSAPI NTSTATUS NTAPI DbgQueryDebugFilterState (__in ULONG ComponentId, __in ULONG Level)
Definition at line 522 of file debug.c.
References NtQueryDebugFilterState().
NTSYSAPI NTSTATUS NTAPI DbgSetDebugFilterState (__in ULONG ComponentId, __in ULONG Level, __in BOOLEAN State)
Definition at line 560 of file debug.c.
References NtSetDebugFilterState().
NTSYSAPI VOID NTAPI DbgUnLoadImageSymbols (__in PSTRING FileName, __in PVOID ImageBase, __in ULONG_PTR ProcessId)
Definition at line 456 of file debug.c.
References _KD_SYMBOLS_INFO::BaseOfDll, BREAKPOINT_UNLOAD_SYMBOLS, _KD_SYMBOLS_INFO::CheckSum, DebugService2(), _KD_SYMBOLS_INFO::ProcessId, and _KD_SYMBOLS_INFO::SizeOfImage.
Referenced by KeBugCheck2(), MiSegmentDelete(), and MmUnloadSystemImage().
NTSYSAPI VOID NTAPI DbgUserBreakPoint (VOID)
VOID NTAPI DebugService2 (PVOID Arg1, PVOID Arg2, ULONG Service)
Definition at line 100 of file debug3.c.
Referenced by DbgCommandString(), DbgLoadImageSymbols(), and DbgUnLoadImageSymbols().
VOID FORCEINLINE InitializeListHead (IN PLIST_ENTRY ListHead)
Definition at line 335 of file ntrtl.h.
Referenced by CcDeleteMbcb(), CcDeleteSharedCacheMap(), CcInitializeCacheManager(), CcInitializeCacheMap(), CcInitializeVacbs(), CcLazyWriteScan(), CcSetDirtyInMask(), CmGetSystemDriverList(), CmInitSystem1(), CmpAllocateCmView(), CmpAllocatePostBlock(), CmpCallCallBacks(), CmpCloseKeyObject(), CmpDestroyHiveViewList(), CmpFixHiveUsageCount(), CmpInitCmPrivateAlloc(), CmpInitCmPrivateDelayAlloc(), CmpInitDelayDerefKCBEngine(), CmpInitHiveViewList(), CmpInitializeDelayedCloseTable(), CmpInitializeHive(), CmpInitSecurityCache(), CmpNotifyChangeKey(), CmpPinCmView(), CmpPostNotify(), CmpRebuildSecurityCache(), CmpReportNotifyHelper(), CmpUnPinCmView(), CmRegisterCallback(), DbgkClearProcessDebugObject(), DbgkpCloseObject(), DbgkpSetProcessDebugObject(), EnlistKeyBodyWithKCB(), ExCreateCallback(), ExInitializeCallData(), ExInitializeHandleTablePackage(), ExpInitSystemPhase0(), ExpRegisterFirmwareTableInformationHandler(), ExpResourceInitialization(), ExpTimerInitialization(), ExpWorkerInitialization(), ExRemoveHandleTable(), FsRtlAddToTunnelCache(), FsRtlAllocateOplock(), FsRtlDeleteKeyFromTunnelCache(), FsRtlDeleteTunnelCache(), FsRtlFindInTunnelCache(), FsRtlInitializeTunnelCache(), FsRtlInsertPerFileObjectContext(), FsRtlNotifyFilterChangeDirectory(), HvInitializeHive(), HvRefreshHive(), InitializeKCBKeyBodyList(), IoCreateDevice(), IoInitializeIrp(), IoInitSystem(), IopDisassociateThreadIrp(), KeConnectInterrupt(), KeFlushQueueApc(), KeInitializeDeviceQueue(), KeInitializeEvent(), KeInitializeGate(), KeInitializeMutant(), KeInitializeMutex(), KeInitializeProcess(), KeInitializeQueue(), KeInitializeSemaphore(), KeInitializeTimerEx(), KeInitSystem(), KeInitThread(), KeSetSystemTime(), KeStartProfile(), KiAttachProcess(), KiInitializeBootStructures(), KiInitializeKernel(), KiInitSpinLocks(), KiInitSystem(), KiMoveApcState(), LpcpAllocateFromPortZone(), LpcpCreatePort(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeConMsg(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpInitializePortQueue(), LpcpPrepareToWakeClient(), LpcpRequestWaitReplyPort(), MiCreateImageFileMap(), MiInitializeDriverLargePageList(), MiInitializeIoTrackers(), MiInitializeLargePageSupport(), MiInitializeLoadedModuleList(), MiInitializeNonPagedPool(), MiInitializeSessionWsSupport(), MiInsertImageSectionObject(), MiModifiedPageWriter(), MiRearrangeWorkingSetExpansionList(), MiSecureVirtualMemory(), MiSessionCreateInternal(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmInitSystem(), NtAcceptConnectPort(), NtCreateDebugObject(), NtCreateJobObject(), NtCreateJobSet(), NtCreateKeyedEvent(), NtReleaseKeyedEvent(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetInformationJobObject(), NtWaitForKeyedEvent(), ObCreateObjectType(), ObpAllocateObject(), ObpInitSecurityDescriptorCache(), PsInitializeQuotaSystem(), PspCreateProcess(), PspCreateThread(), PspInitializeJobStructures(), PspInitPhase0(), RtlInitializeGenericTable(), SepCreateLogonSessionTrack(), SepInitializeWorkList(), WmipAllocDataSource(), WmipAllocEntry(), WmipAllocGuidEntryX(), WmipClearObjectFromThreadList(), WmipCreateUMLogger(), WmipInitializeDataStructs(), WmipProcessPrevMcaLogs(), and WmipReceiveNotifications().
VOID FORCEINLINE InsertHeadList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY Entry)
Definition at line 424 of file ntrtl.h.
References _LIST_ENTRY::Blink, and _LIST_ENTRY::Flink.
Referenced by CcCreateVacbArray(), CcExtendVacbArray(), CcFindBitmapRangeToDirty(), CcLazyWriteScan(), CmpAddDriverToList(), CmpAddToDelayedClose(), CmpDelayCloseWorker(), CmpDoSort(), CmpNotifyChangeKey(), CmpRunDownDelayDerefKCBEngine(), CmpTouchView(), CmpUnPinCmView(), FsRtlAcknowledgeOplockBreak(), FsRtlFreeTunnelNode(), FsRtlInsertPerFileObjectContext(), FsRtlInsertPerStreamContext(), FsRtlRequestOplockII(), HvpAddBin(), HvpEnlistFreeCell(), IopErrorLogRequeueEntry(), IopInterlockedInsertHeadList(), IopQueueThreadIrp(), IoRegisterFileSystem(), KeInitializeMutant(), KeInsertQueueDpc(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), KeStartProfile(), KiDeferredReadyThread(), KiInsertQueue(), KiInsertQueueApc(), KiInsertTimerTable(), KxQueueReadyThread(), MiAddViewsForSection(), MiInitializeNonPagedPool(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiIssuePageExtendRequest(), MiIssuePageExtendRequestNoWait(), MiProcessWorkingSets(), MiProtectedPoolInsertList(), MiRearrangeWorkingSetExpansionList(), MmProtectMdlSystemAddress(), NtReleaseKeyedEvent(), WmipAddDataSource(), WmipAllocEntry(), WmipEnableDisableTrace(), WmipFindGEByGuid(), WmipLinkDataSourceToList(), WmipNtDllLoggerInfo(), WmipOpenBlock(), WmipUpdateAddGuid(), and WmipUpdateModifyGuid().
VOID FORCEINLINE InsertTailList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY Entry)
Definition at line 407 of file ntrtl.h.
References _LIST_ENTRY::Blink, and _LIST_ENTRY::Flink.
Referenced by CcAllocateInitializeBcb(), CcDeleteMbcb(), CcDeleteSharedCacheMap(), CcExtendVacbArray(), CcFlushCache(), CcGetFlushedValidData(), CcGetVacbMiss(), CcInitializeCacheManager(), CcInitializeCacheMap(), CcInitializeVacbs(), CcInsertIntoCleanSharedCacheMapList(), CcLazyWriteScan(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPerformReadAhead(), CcPostWorkQueue(), CcPurgeCacheSection(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcSetFileSizes(), CcUninitializeCacheMap(), CcWaitForCurrentLazyWriterActivity(), CcWorkerThread(), CcWriteBehind(), CcZeroEndOfLastPage(), CmNotifyRunDown(), CmpAddSecurityCellToCache(), CmpAddToDelayedDeref(), CmpAllocateCmView(), CmpAllocateDelayItem(), CmpAllocateKeyControlBlock(), CmpCheckRecursionAndRecordThreadInfo(), CmpCompressKeyWorker(), CmpDelayDerefKeyControlBlock(), CmpDestroyHiveViewList(), CmpFreeDelayItem(), CmpFreeKeyControlBlock(), CmpInitializeHive(), CmpNotifyChangeKey(), CmpOrderGroup(), CmpPinCmView(), CmpRaiseSelfHealWarning(), CmpSetSecurityDescriptorInfo(), CmpShiftAllCells2(), CmpSwitchStorageAndRebuildMappings(), CmpUnmapCmView(), CmpUnPinCmView(), DbgkClearProcessDebugObject(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), EnlistKeyBodyWithKCB(), ExCreateHandleTable(), ExDupHandleTable(), ExInitializeResourceLite(), ExInitializeSystemLookasideList(), ExpRegisterFirmwareTableInformationHandler(), ExRecordCallerInHashTable(), ExRegisterCallback(), FsRtlAddToTunnelCache(), FsRtlNotifyFilterChangeDirectory(), FsRtlWaitOnIrp(), HvRefreshHive(), IopInterlockedInsertTailList(), IoRaiseInformationalHardError(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoWriteErrorLogEntry(), KeConnectInterrupt(), KeDelayExecutionThread(), KeInsertByKeyDeviceQueue(), KeInsertDeviceQueue(), KeInsertQueueDpc(), KeRemoveQueue(), KeSetSystemTime(), KeStartProfile(), KeStartThread(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiAttachProcess(), KiDeferredReadyThread(), KiInsertQueue(), KiInsertQueueApc(), KiReadyThread(), KxQueueReadyThread(), LpcpRequestWaitReplyPort(), LpcpSaveDataInfoMessage(), LpcRequestPort(), MiAddMdlTracker(), MiAllocatePoolPages(), MiAllowWorkingSetExpansion(), MiCheckForControlAreaDeletion(), MiContractPagingFiles(), MiDecrementSubsections(), MiFlushSectionInternal(), MiFreePoolPages(), MiGatherMappedPages(), MiGatherPagefilePages(), MiInitializeDriverLargePageList(), MiInitializeLargePageSupport(), MiInitializeLoadedModuleList(), MiInsertHandBuiltProcessIntoList(), MiInsertImageSectionObject(), MiInsertPageFileInList(), MiLoadUserSymbols(), MiModifiedPageWriter(), MiProcessLoaderEntry(), MiProcessWorkingSets(), MiProtectedPoolInsertList(), MiRemoveUnusedSegments(), MiRemoveViewsFromSection(), MiSecureVirtualMemory(), MiSessionAddProcess(), MiSessionInitializeWorkingSetList(), MiSessionInsertImage(), MiTrimAllSystemPageableMemory(), MiUpdateModifiedWriterMdls(), MiWriteComplete(), MmCreateProcessAddressSpace(), MmInSwapProcess(), MmPurgeSection(), NtCreateJobObject(), NtCreateJobSet(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetInformationJobObject(), NtSetTimer(), NtWaitForKeyedEvent(), ObCreateObjectType(), ObLogSecurityDescriptor(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), PspAddProcessToJob(), PspApplyJobLimitsToProcessSet(), PspCreateProcess(), PspCreateThread(), PspInsertQuotaBlock(), RtlInsertElementGenericTableFull(), SepQueueWorkItem(), WmipAddMofResource(), WmipFreeEntry(), WmipLinkDataSourceToList(), WmipOpenBlock(), WmipProcessPrevMcaLogs(), WmipQueueRegWork(), WmipReceiveNotifications(), WmipWriteMBToObject(), and WmipWriteMCAEventLogEvent().
typedef NTSTATUS (NTAPI * PRTL_AVL_MATCH_FUNCTION)
NTSYSAPI PPREFIX_TABLE_ENTRY NTAPI PfxFindPrefix (PPREFIX_TABLE PrefixTable, PSTRING FullName)
NTSYSAPI VOID NTAPI PfxInitialize (PPREFIX_TABLE PrefixTable)
NTSYSAPI BOOLEAN NTAPI PfxInsertPrefix (PPREFIX_TABLE PrefixTable, PSTRING Prefix, PPREFIX_TABLE_ENTRY PrefixTableEntry)
NTSYSAPI VOID NTAPI PfxRemovePrefix (PPREFIX_TABLE PrefixTable, PPREFIX_TABLE_ENTRY PrefixTableEntry)
typedef PVOID (NTAPI * PRTL_AVL_ALLOCATE_ROUTINE)
BOOLEAN FORCEINLINE RemoveEntryList (IN PLIST_ENTRY Entry)
Definition at line 356 of file ntrtl.h.
References _LIST_ENTRY::Blink, and _LIST_ENTRY::Flink.
Referenced by CcAcquireByteRangeForWrite(), CcDeleteBcbs(), CcDeleteMbcb(), CcDeleteSharedCacheMap(), CcExtendVacbArray(), CcFindBitmapRangeToDirty(), CcFlushCache(), CcGetFlushedValidData(), CcGetVacbMiss(), CcInitializeCacheMap(), CcLazyWriteScan(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPerformReadAhead(), CcPostDeferredWrites(), CcPurgeCacheSection(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcSetFileSizes(), CcUninitializeCacheMap(), CcUnpinFileDataEx(), CcWriteBehind(), CcZeroEndOfLastPage(), CmpCallCallBacks(), CmpDestroyHiveViewList(), CmpDoSort(), CmpFixHiveUsageCount(), CmpFreeKeyControlBlock(), CmpOrderGroup(), CmpPinCmView(), CmpTouchView(), CmpUnmapCmView(), CmpUnPinCmView(), DbgkClearProcessDebugObject(), DbgkpSetProcessDebugObject(), DelistKeyBodyFromKCB(), ExDeleteNPagedLookasideList(), ExDeletePagedLookasideList(), ExDeleteResourceLite(), ExGetNextWakeTime(), ExpDeleteTimer(), ExpRegisterFirmwareTableInformationHandler(), ExpTimerApcRoutine(), ExRemoveHandleTable(), ExTimerRundown(), ExUnregisterCallback(), FsRtlAddToTunnelCache(), FsRtlCancelNotify(), FsRtlEmptyFreePoolList(), FsRtlNotifyCleanup(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRemoveNodeFromTunnel(), FsRtlRemovePerFileObjectContext(), FsRtlRemovePerStreamContext(), HvFreeHivePartial(), HvpAddBin(), HvpCoalesceDiscardedBins(), HvpDelistBinFreeCells(), HvRefreshHive(), IopInterlockedRemoveHeadList(), IopRemoveTimerFromTimerList(), IoUnregisterFileSystem(), IoUnregisterFsRegistrationChange(), IoUnregisterShutdownNotification(), KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeDisconnectInterrupt(), KeFlushQueueApc(), KeReleaseMutant(), KeRemoveByKeyDeviceQueue(), KeRemoveByKeyDeviceQueueIfBusy(), KeRemoveEntryDeviceQueue(), KeRemoveQueue(), KeRemoveQueueApc(), KeRemoveQueueDpc(), KeRundownQueue(), KeRundownThread(), KeSetSystemTime(), KeSignalGateBoostPriority(), KeStopProfile(), KeTerminateThread(), KiActivateWaiterQueue(), KiAttachProcess(), KiDeliverApc(), KiExecuteDpc(), KiFindReadyThread(), KiInsertQueue(), KiInsertQueueApc(), KiInSwapProcesses(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), KiRemoveEntryTimer(), KiRemoveTreeTimer(), KiRetireDpcList(), KiScanReadyQueues(), KiSelectReadyThread(), KiSetAffinityThread(), KiSetPriorityThread(), KiTimerListExpire(), KiUnlinkThread(), LpcExitThread(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeConMsg(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpPrepareToWakeClient(), LpcpRequestWaitReplyPort(), MiAddViewsForSection(), MiAllocatePoolPages(), MiCancelWriteOfMappedPfn(), MiCheckForControlAreaDeletion(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiFlushSectionInternal(), MiFreeAllExpansionNonPagedPool(), MiFreeMdlTracker(), MiFreePoolPages(), MiIssuePageExtendRequest(), MiProcessLoaderEntry(), MiProtectedPoolRemoveEntryList(), MiReferenceSubsection(), MiRemoveImageSectionObject(), MiRemoveIoSpaceMap(), MiRemovePteTracker(), MiSegmentDelete(), MiSessionRemoveImage(), MiSessionRemoveProcess(), MiTrimAllSystemPageableMemory(), MiUnlinkWorkingSet(), MiUnsecureVirtualMemory(), MiUpdateModifiedWriterMdls(), MiWriteComplete(), MmCleanProcessAddressSpace(), MmCreateSection(), MmDeleteProcessAddressSpace(), MmOutSwapProcess(), MmProtectMdlSystemAddress(), MmPurgeSection(), NtCancelTimer(), NtDebugContinue(), NtReleaseKeyedEvent(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSetTimer(), NtWaitForKeyedEvent(), ObpDestroySecurityDescriptorHeader(), ObpRemoveObjectRoutine(), PspDeleteVdmObjects(), PspDereferenceQuotaBlock(), PspJobDelete(), PspProcessDelete(), PspRemoveProcessFromJob(), PspThreadDelete(), RtlDeleteElementGenericTable(), WmipClearIrpObjectList(), WmipClearObjectFromThreadList(), WmipCloseMethod(), WmipDeleteMethod(), WmipDSCleanup(), WmipFindGEByGuid(), WmipFreeEntry(), WmipMBReply(), WmipUnreferenceEntry(), WmipUpdateDataSource(), WmipUpdateModifyGuid(), and WmipWriteMBToObject().
PLIST_ENTRY FORCEINLINE RemoveHeadList (IN PLIST_ENTRY ListHead)
Definition at line 372 of file ntrtl.h.
References _LIST_ENTRY::Blink, and _LIST_ENTRY::Flink.
Referenced by CcDeleteMbcb(), CcLazyWriteScan(), CcPostWorkQueue(), CcWorkerThread(), CmCompressKey(), CmNotifyRunDown(), CmpAllocateDelayItem(), CmpAllocateKeyControlBlock(), CmpDelayDerefKCBWorker(), CmpDelayedDerefKeys(), CmpDestroyHiveViewList(), CmpFreeAllMemory(), CmpPostNotify(), CmpRaiseSelfHealWarningWorker(), CmpRunDownDelayDerefKCBEngine(), CmpSwitchStorageAndRebuildMappings(), DbgkClearProcessDebugObject(), DbgkpSetProcessDebugObject(), FsRtlNotifyCompleteIrpList(), FsRtlTeardownPerStreamContexts(), FsRtlUninitializeOplock(), HvpFlushMappedData(), HvpRecoverWholeHive(), HvRefreshHive(), IopDisassociateThreadIrp(), IopErrorLogGetEntry(), IopRemoveHardErrorPacket(), IopShutdownBaseFileSystems(), KeRemoveByKeyDeviceQueueIfBusy(), KeRemoveDeviceQueue(), MiDereferenceSegmentThread(), MiGatherMappedPages(), MiMappedPageWriter(), MiModifiedPageWriterWorker(), MiProcessWorkingSets(), MiRearrangeWorkingSetExpansionList(), MiReleaseAllMemory(), MiRemoveUnusedSegments(), NtCreateJobSet(), NtReplyWaitReceivePortEx(), NtSetInformationJobObject(), SepDequeueWorkItem(), WmipAllocEntry(), WmipCheckIsWbemRunning(), WmipProcessPrevMcaLogs(), and WmipRegistrationWorker().
PLIST_ENTRY FORCEINLINE RemoveTailList (IN PLIST_ENTRY ListHead)
Definition at line 390 of file ntrtl.h.
References _LIST_ENTRY::Blink, and _LIST_ENTRY::Flink.
Referenced by CmpDelayCloseWorker().
typedef RTL_GENERIC_COMPARE_RESULTS (NTAPI * PRTL_AVL_COMPARE_ROUTINE)
NTSYSAPI NTSTATUS NTAPI RtlAbortRXact (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlAbsoluteToSelfRelativeSD (__in PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __out_bcount *BufferLength PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
Definition at line 320 of file rtlassig.c.
References RTL_PAGED_CODE, RtlMakeSelfRelativeSD(), RtlpAreControlBitsSet, SE_SELF_RELATIVE, and STATUS_BAD_DESCRIPTOR_FORMAT.
NTSYSAPI VOID NTAPI RtlAcquirePebLock (VOID)
Definition at line 31 of file eballoc.c.
Referenced by RtlCreateEnvironment(), RtlCreateProcessParameters(), RtlQueryEnvironmentVariable_U(), RtlSetCurrentEnvironment(), RtlSetEnvironmentStrings(), and RtlSetEnvironmentVariable().
NTSYSAPI NTSTATUS NTAPI RtlAcquirePrivilege (PULONG Privilege, ULONG NumPriv, ULONG Flags, PVOID * ReturnedState)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessAllowedAce (PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid)
Referenced by CmpHiveRootSecurityDescriptor(), ExpKeyedEventInitialization(), MiCreateMemoryEvent(), NtCreatePagingFile(), ObInitSystem(), ObpGetDosDevicesProtection(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepCreateImpersonationTokenDacl(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), SeRmInitPhase1(), WmipCreateAdminSD(), and WmipInitializeSecurity().
NTSYSAPI NTSTATUS NTAPI RtlAddAccessAllowedAceEx (PACL Acl, ULONG AceRevision, ULONG AceFlags, ACCESS_MASK AccessMask, PSID Sid)
Referenced by RtlpSysVolCreateSecurityDescriptor().
NTSYSAPI NTSTATUS NTAPI RtlAddAccessAllowedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
Definition at line 2037 of file acledit.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_ALLOWED_OBJECT_ACE_TYPE, NULL, RTL_PAGED_CODE, RtlpAddKnownAce(), and RtlpAddKnownObjectAce().
NTSYSAPI NTSTATUS NTAPI RtlAddAccessDeniedAce (PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessDeniedAceEx (PACL Acl, ULONG AceRevision, ULONG AceFlags, ACCESS_MASK AccessMask, PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlAddAccessDeniedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
Definition at line 2124 of file acledit.c.
References ACCESS_DENIED_ACE_TYPE, ACCESS_DENIED_OBJECT_ACE_TYPE, NULL, RTL_PAGED_CODE, RtlpAddKnownAce(), and RtlpAddKnownObjectAce().
NTSYSAPI NTSTATUS NTAPI RtlAddAce (PACL Acl, ULONG AceRevision, ULONG StartingAceIndex, PVOID AceList, ULONG AceListLength)
NTSYSAPI NTSTATUS NTAPI RtlAddActionToRXact (IN PRTL_RXACT_CONTEXT RXactContext, IN RTL_RXACT_OPERATION Operation, IN PUNICODE_STRING SubKeyName, IN ULONG NewKeyValueType, IN PVOID NewKeyValue OPTIONAL, IN ULONG NewKeyValueLength)
NTSYSAPI NTSTATUS NTAPI RtlAddAtomToAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __inout_opt PRTL_ATOM Atom)
Definition at line 581 of file atom.c.
References ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, FIELD_OFFSET, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::HandleIndex, _RTL_ATOM_TABLE_ENTRY::HashLink, KdPrint, _RTL_ATOM_TABLE_ENTRY::Name, _RTL_ATOM_TABLE_ENTRY::NameLength, NULL, _RTL_ATOM_TABLE_ENTRY::ReferenceCount, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlCopyMemory, RtlpAllocateAtom(), RtlpCreateHandleForAtom(), RtlpFreeAtom(), RtlpGetIntegerAtom(), RtlpHashStringToAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtAddAtom().
NTSYSAPI NTSTATUS NTAPI RtlAddAttributeActionToRXact (IN PRTL_RXACT_CONTEXT RXactContext, IN RTL_RXACT_OPERATION Operation, IN PUNICODE_STRING SubKeyName, IN HANDLE KeyHandle, IN PUNICODE_STRING AttributeName, IN ULONG NewValueType, IN PVOID NewValue, IN ULONG NewValueLength)
NTSYSAPI NTSTATUS NTAPI RtlAddAuditAccessAce (PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid, BOOLEAN AuditSuccess, BOOLEAN AuditFailure)
Referenced by ObInitSystem(), and SepInitProcessAuditSd().
NTSYSAPI NTSTATUS NTAPI RtlAddAuditAccessAceEx (PACL Acl, ULONG AceRevision, ULONG AceFlags, ACCESS_MASK AccessMask, PSID Sid, BOOLEAN AuditSuccess, BOOLEAN AuditFailure)
NTSYSAPI NTSTATUS NTAPI RtlAddAuditAccessObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid, BOOLEAN AuditSuccess, BOOLEAN AuditFailure)
NTSYSAPI NTSTATUS NTAPI RtlAddCompoundAce (IN PACL Acl, IN ULONG AceRevision, IN UCHAR AceType, IN ACCESS_MASK AccessMask, IN PSID ServerSid, IN PSID ClientSid)
Definition at line 1127 of file acledit.c.
References ACCESS_ALLOWED_COMPOUND_ACE_TYPE, _ACE_HEADER::AceFlags, _ACE_HEADER::AceSize, _ACE_HEADER::AceType, ACL_REVISION3, ACL_REVISION4, _KNOWN_COMPOUND_ACE::CompoundAceType, _KNOWN_COMPOUND_ACE::Header, _KNOWN_COMPOUND_ACE::Mask, NULL, RTL_PAGED_CODE, RtlCopySid(), RtlFirstFreeAce(), RtlValidAcl(), RtlValidSid(), SeLengthSid, _KNOWN_COMPOUND_ACE::SidStart, STATUS_ALLOTTED_SPACE_EXCEEDED, STATUS_INVALID_ACL, STATUS_INVALID_SID, STATUS_REVISION_MISMATCH, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlAddRange (IN OUT PRTL_RANGE_LIST RangeList, IN ULONGLONG Start, IN ULONGLONG End, IN UCHAR Attributes, IN ULONG Flags, IN PVOID UserData, OPTIONAL IN PVOID Owner OPTIONAL)
NTSYSAPI PVOID NTAPI RtlAddressInSectionTable (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID BaseOfImage, IN ULONG VirtualAddress)
Definition at line 89 of file imagedir.c.
References NULL, _IMAGE_SECTION_HEADER::PointerToRawData, RtlSectionTableFromVirtualAddress(), and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by LdrpAccessResourceDataNoMultipleLanguage(), RtlpImageDirectoryEntryToData32(), and RtlpImageDirectoryEntryToData64().
NTSYSAPI NTSTATUS NTAPI RtlAdjustPrivilege (ULONG Privilege, BOOLEAN Enable, BOOLEAN Client, PBOOLEAN WasEnabled)
Definition at line 659 of file sertl.c.
References ANYSIZE_ARRAY, ASSERT, _LUID_AND_ATTRIBUTES::Attributes, FALSE, _LUID_AND_ATTRIBUTES::Luid, NT_SUCCESS, NtAdjustPrivilegesToken(), NtClose(), NtCurrentProcess, NtCurrentThread, NtOpenProcessToken(), NtOpenThreadToken(), _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, RTL_PAGED_CODE, RtlConvertUlongToLuid(), SE_PRIVILEGE_ENABLED, Status, STATUS_NOT_ALL_ASSIGNED, STATUS_PRIVILEGE_NOT_HELD, TOKEN_ADJUST_PRIVILEGES, TOKEN_QUERY, and TRUE.
NTSYSAPI NTSTATUS NTAPI RtlAllocateAndInitializeSid (IN PSID_IDENTIFIER_AUTHORITY IdentifierAuthority, IN UCHAR SubAuthorityCount, IN ULONG SubAuthority0, IN ULONG SubAuthority1, IN ULONG SubAuthority2, IN ULONG SubAuthority3, IN ULONG SubAuthority4, IN ULONG SubAuthority5, IN ULONG SubAuthority6, IN ULONG SubAuthority7, OUT PSID * Sid)
NTSYSAPI NTSTATUS NTAPI RtlAllocateFromPeb (ULONG Size, PVOID * Block)
NTSYSAPI PVOID NTAPI RtlAllocateHeap (IN PVOID HeapHandle, IN ULONG Flags, IN SIZE_T Size)
Referenced by RtlCreateProcessParameters().
NTSYSAPI WCHAR NTAPI RtlAnsiCharToUnicodeChar (PUCHAR * SourceCharacter)
NTSYSAPI NTSTATUS NTAPI RtlAnsiStringToUnicodeString (PUNICODE_STRING DestinationString, PCANSI_STRING SourceString, BOOLEAN AllocateDestinationString)
Referenced by CmpAddAliasEntry(), CmpCreateControlSet(), CmpFindControlSet(), CmpInitializeRegistryNode(), CmpInitializeSystemHive(), CreateSystemRootLink(), ExpInitializeExecutive(), ExpSystemErrorHandler(), HalpNextDriveLetter(), IoAssignDriveLetters(), IoGetBootDiskInformation(), IoInitSystem(), IopCopyBootLogRegistryToFile(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopInitializeBootLogging(), IopMarkBootPartition(), IopReassignSystemRoot(), MiResolveImageReferences(), MiSnapThunk(), MmLoadSystemImage(), PerfInfoSysModuleRunDown(), RtlCreateUnicodeStringFromAsciiz(), RtlInt64ToUnicodeString(), RtlIntegerToUnicodeString(), SepInitializationPhase1(), WmipDriverEntry(), and WmipQueryWmiRegInfo().
NTSYSAPI NTSTATUS NTAPI RtlAppendAsciizToString (PSTRING Destination, PCSZ Source)
NTSYSAPI NTSTATUS NTAPI RtlAppendStringToString (PSTRING Destination, const STRING * Source)
Referenced by CmpInitializeHiveList(), CmpLoadHiveThread(), CmpOpenHiveFiles(), and MiResolveImageReferences().
NTSYSAPI NTSTATUS NTAPI RtlAppendUnicodeStringToString (PUNICODE_STRING Destination, PCUNICODE_STRING Source)
Referenced by CmpAddDriverToList(), CmpGetSymbolicLink(), CmpLoadHiveVolatile(), CmpNameFromAttributes(), IopBootLog(), IopDeleteSessionSymLinks(), IopGetDriverNameFromKeyNode(), IopSafebootDriverLoad(), MiResolveImageReferences(), MmCallDllInitialize(), MmLoadSystemImage(), Phase1InitializationDiscard(), and RtlpGetRegistryHandle().
NTSYSAPI NTSTATUS NTAPI RtlAppendUnicodeToString (PUNICODE_STRING Destination, PCWSTR Source)
Referenced by CmpAddDriverToList(), CmpFindDrivers(), CmpLoadHiveVolatile(), ExpValidateLocale(), IopGetDriverNameFromKeyNode(), IopLoadDriver(), IopSafebootDriverLoad(), IoWMISuggestInstanceName(), MmCallDllInitialize(), Phase1InitializationDiscard(), RtlFormatCurrentUserKeyPath(), and RtlpGetRegistryHandle().
NTSYSAPI NTSTATUS NTAPI RtlApplyRXact (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlApplyRXactNoFlush (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI BOOLEAN NTAPI RtlAreAllAccessesGranted (ACCESS_MASK GrantedAccess, ACCESS_MASK DesiredAccess)
NTSYSAPI BOOLEAN NTAPI RtlAreAnyAccessesGranted (ACCESS_MASK GrantedAccess, ACCESS_MASK DesiredAccess)
NTSYSAPI BOOLEAN NTAPI RtlAreBitsClear (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG Length)
Referenced by CmpLoadHiveThread(), HvpFindFreeCellInThisViewWindow(), HvpScanForFreeCellInViewWindow(), MiAttemptPageFileReduction(), and MiSessionWideReserveImageAddress().
NTSYSAPI BOOLEAN NTAPI RtlAreBitsSet (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG Length)
Referenced by MiRemoveImageSessionWide(), MiSessionWideReserveImageAddress(), and MiUnmapLargePages().
NTSYSAPI VOID NTAPI RtlAssert (__in PVOID VoidFailedAssertion, __in PVOID VoidFileName, __in ULONG LineNumber, __in_opt PSTR MutableMessage)
Definition at line 50 of file assert.c.
References CONST, DbgBreakPoint(), DbgPrint(), DbgPrompt(), NtCurrentProcess, NtCurrentThread, RtlCaptureContext(), STATUS_UNSUCCESSFUL, TRUE, ZwTerminateProcess(), and ZwTerminateThread().
VOID RtlBackoff (IN PRTL_BACKOFF Backoff)
Referenced by ExfAcquirePushLockExclusive(), and ExfAcquirePushLockShared().
NTSYSAPI VOID NTAPI RtlCaptureContext (OUT PCONTEXT ContextRecord)
Referenced by ExpSystemErrorHandler(), KeBugCheck2(), KeSaveStateForHibernate(), PspGetSetContextInternal(), RtlAssert(), RtlGetCallersAddress(), RtlpWalkFrameChain(), RtlRaiseException(), RtlRaiseStatus(), and RtlUnwindEx().
NTSYSAPI USHORT NTAPI RtlCaptureStackBackTrace (IN ULONG FramesToSkip, IN ULONG FramesToCapture, OUT PVOID * BackTrace, OUT PULONG BackTraceHash OPTIONAL)
Definition at line 151 of file stkwalk.c.
References ARGUMENT_PRESENT, Count, FALSE, Index, MAX_STACK_DEPTH, MmCanThreadFault(), NULL, PsGetCurrentThread(), PtrToUlong, and RtlWalkFrameChain().
Referenced by ExFreePoolWithTag(), MiCheckCacheAttributes(), MiInsertIoSpaceMap(), and RtlpCaptureStackTraceForLogging().
NTSYSAPI ULONG NTAPI RtlCaptureStackContext (OUT PULONG_PTR Callers, OUT PRTL_STACK_CONTEXT Context, IN ULONG Limit)
Definition at line 388 of file getcalr.c.
References DISPATCH_LEVEL, Index, KeGetCurrentIrql(), RtlpCaptureStackLimits(), and RtlpStkIsPointerInDllRange().
NTSYSAPI NTSTATUS NTAPI RtlCharToInteger (PCSZ String, ULONG Base, PULONG Value)
NTSYSAPI NTSTATUS NTAPI RtlCheckRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
Definition at line 1218 of file regutil.c.
References FALSE, NT_SUCCESS, RTL_PAGED_CODE, RtlpGetRegistryHandle(), Status, STATUS_SUCCESS, and ZwClose().
NTSYSAPI VOID NTAPI RtlClearAllBits (PRTL_BITMAP BitMapHeader)
Referenced by CmpOverwriteHive(), HvInitializeHive(), HvpRecoverWholeHive(), HvSyncHive(), MiBuildPagedPool(), MiInitializeLargePageSupport(), MiInitializeSessionIds(), MiInitializeSessionPool(), MiInitializeSystemPtes(), MiInitializeSystemSpaceMap(), MiSessionCreateInternal(), MiSessionWideInitializeAddresses(), MmInitSystem(), MmPerfSnapShotValidPhysicalMemory(), NtAllocateUserPhysicalPages(), and NtAllocateVirtualMemory().
NTSYSAPI VOID NTAPI RtlClearBit (PRTL_BITMAP BitMapHeader, ULONG BitNumber)
Referenced by MiFreePoolPages(), MiReleaseProcessReferenceToSessionDataPage(), MiSessionCreateInternal(), and NtGetWriteWatch().
NTSYSAPI VOID NTAPI RtlClearBits (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG NumberToClear)
Referenced by HvFreeHivePartial(), HvpAdjustBitmap(), HvpDelistBinFreeCells(), HvpFlushMappedData(), HvpRecoverData(), HvpRemoveFreeCellHint(), HvRefreshHive(), MiAllocatePoolPages(), MiAttemptPageFileReduction(), MiBuildPagedPool(), MiCheckPteRelease(), MiFinishPageFileExtension(), MiFreePoolPages(), MiGatherPagefilePages(), MiInitializeSessionPool(), MiMapViewInSystemSpace(), MiMapWithLargePages(), MiRemoveImageSessionWide(), MiReturnPageTablePageCommitment(), MiSessionWideReserveImageAddress(), MiUnmapLargePages(), MiUnmapViewInSystemSpace(), MiZeroPageFile(), NtCreatePagingFile(), and NtResetWriteWatch().
NTSYSAPI SIZE_T NTAPI RtlCompareMemory (const VOID * Source1, const VOID * Source2, SIZE_T Length)
Referenced by CcAllocateVacbLevel(), CmpCompareNewValueDataAgainstKCBCache(), CompareNamesCaseSensitive(), NtSetUuidSeed(), RtlpLogCapturedStackTrace(), and WmipCreateLogFile().
NTSYSAPI SIZE_T NTAPI RtlCompareMemoryUlong (PVOID Source, SIZE_T Length, ULONG Pattern)
Referenced by IopTrackLink(), MiAttachSession(), MiInitMachineDependent(), and MmUnmapViewInSystemCache().
NTSYSAPI LONG NTAPI RtlCompareString (const STRING * String1, const STRING * String2, BOOLEAN CaseInSensitive)
NTSYSAPI LONG NTAPI RtlCompareUnicodeString (PCUNICODE_STRING String1, PCUNICODE_STRING String2, BOOLEAN CaseInSensitive)
Referenced by CmpCheckLexicographicalOrder(), CmpDoCompareKeyName(), CmpFindNameInList(), CmpFindValueByNameFromCache(), CmpIsHiveAlreadyLoaded(), CmPrefetchHivePages(), FsRtlCompareNodeAndKey(), IopDeleteSessionSymLinks(), RtlSetEnvironmentVariable(), and WmipDelayCreate().
NTSYSAPI NTSTATUS NTAPI RtlCompressBuffer (IN USHORT CompressionFormatAndEngine, IN PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, OUT PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN ULONG UncompressedChunkSize, OUT PULONG FinalCompressedSize, IN PVOID WorkSpace)
NTSYSAPI NTSTATUS NTAPI RtlCompressChunks (IN PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, OUT PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN OUT PCOMPRESSED_DATA_INFO CompressedDataInfo, IN ULONG CompressedDataInfoLength, IN PVOID WorkSpace)
ULONG32 RtlComputeCrc32 (IN ULONG32 PartialCrc, IN PVOID Buffer, IN ULONG Length)
NTSYSAPI NTSTATUS RtlComputeImportTableHash (__in HANDLE hFile, __out_bcount(16) PCHAR Hash, __in ULONG ImportTableHashRevision)
NTSYSAPI NTSTATUS NTAPI RtlConsoleMultiByteToUnicodeN (__out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWCH UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString OPTIONAL, __in_bcount(BytesInMultiByteString) PCH MultiByteString, __in ULONG BytesInMultiByteString, __out PULONG pdwSpecialChar)
Definition at line 114 of file nlsxlat.c.
References ARGUMENT_PRESENT, NlsAnsiToUnicodeData, NlsLeadByteInfo, NlsMbAnsiCodePageTables, NlsMbCodePageTag, NULL, RTL_PAGED_CODE, RtlMultiByteToUnicodeN(), STATUS_SUCCESS, and UnicodeNull.
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlConvertLongToLargeInteger (LONG SignedInteger)
Definition at line 5024 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
FORCEINLINE LUID NTAPI RtlConvertLongToLuid (LONG Long)
Definition at line 6206 of file ntrtl.h.
References _LARGE_INTEGER::HighPart, _LUID::HighPart, _LARGE_INTEGER::LowPart, _LUID::LowPart, and _LARGE_INTEGER::QuadPart.
Referenced by RtlpSysVolTakeOwnership(), SepCreateToken(), and SepVariableInitialization().
NTSYSAPI NTSTATUS NTAPI RtlConvertSidToUnicodeString (PUNICODE_STRING UnicodeString, PSID Sid, BOOLEAN AllocateDestinationString)
Definition at line 1472 of file sertl.c.
References _UNICODE_STRING::Buffer, _LARGE_INTEGER::HighPart, _SID::IdentifierAuthority, _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, _UNICODE_STRING::MaximumLength, NT_SUCCESS, _SID::Revision, RTL_PAGED_CODE, RtlCopyUnicodeString(), RtlCreateUnicodeString(), RtlIntegerToUnicode(), RtlLargeIntegerToUnicode(), RtlValidSid(), SID_REVISION, Status, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_SID, STATUS_NO_MEMORY, STATUS_SUCCESS, _SID::SubAuthority, _SID::SubAuthorityCount, TRUE, _SID_IDENTIFIER_AUTHORITY::Value, wcscat, and wcscpy.
Referenced by RtlFormatCurrentUserKeyPath().
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlConvertUlongToLargeInteger (ULONG UnsignedInteger)
Definition at line 5042 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
Referenced by HalExamineMBR().
FORCEINLINE LUID NTAPI RtlConvertUlongToLuid (ULONG Ulong)
Definition at line 6222 of file ntrtl.h.
References _LUID::HighPart, _LUID::LowPart, and Ulong.
Referenced by RtlAdjustPrivilege().
NTSYSAPI VOID NTAPI RtlCopyLuid (PLUID DestinationLuid, PLUID SourceLuid)
Referenced by NtCreateToken().
NTSYSAPI VOID NTAPI RtlCopyLuidAndAttributesArray (ULONG ArrayLength, PLUID_AND_ATTRIBUTES Source, PLUID_AND_ATTRIBUTES Target)
Referenced by NtQueryInformationToken(), SepFilterToken(), and SeQueryInformationToken().
NTSYSAPI NTSTATUS NTAPI RtlCopyRangeList (OUT PRTL_RANGE_LIST CopyRangeList, IN PRTL_RANGE_LIST RangeList)
NTSYSAPI NTSTATUS NTAPI RtlCopySid (ULONG DestinationSidLength, PSID DestinationSid, PSID SourceSid)
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtQueryInformationToken(), RtlAddCompoundAce(), RtlpAddKnownAce(), RtlpAddKnownObjectAce(), SepAdjustGroups(), SepCreateToken(), and SeQueryInformationToken().
NTSYSAPI NTSTATUS NTAPI RtlCopySidAndAttributesArray (ULONG ArrayLength, PSID_AND_ATTRIBUTES Source, ULONG TargetSidBufferSize, PSID_AND_ATTRIBUTES TargetArrayElement, PSID TargetSid, PSID * NextTargetSid, PULONG RemainingTargetSidSize)
Referenced by NtQueryInformationJobObject(), NtQueryInformationToken(), SepCreateToken(), SepFilterToken(), and SeQueryInformationToken().
NTSYSAPI VOID NTAPI RtlCopyString (PSTRING DestinationString, const STRING * SourceString)
Referenced by IopReassignSystemRoot().
NTSYSAPI VOID NTAPI RtlCopyUnicodeString (PUNICODE_STRING DestinationString, PCUNICODE_STRING SourceString)
Referenced by CmpLoadHiveVolatile(), FsRtlFindInTunnelCache(), IopBootLog(), IopDeleteSessionSymLinks(), IopParseDevice(), IopSafebootDriverLoad(), ObCreateObjectType(), Phase1InitializationDiscard(), RtlConvertSidToUnicodeString(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepCopyProxyData(), WmipQueryLogger(), and WmipStartLogger().
NTSYSAPI NTSTATUS NTAPI RtlCreateAcl (PACL Acl, ULONG AclLength, ULONG AclRevision)
Referenced by CmpHiveRootSecurityDescriptor(), ExpKeyedEventInitialization(), MiCreateMemoryEvent(), NtCreatePagingFile(), ObInitSystem(), ObpGetDosDevicesProtection(), RtlpComputeMergedAcl2(), RtlpConvertAclToAutoInherit(), RtlpCreateServerAcl(), RtlpInheritAcl2(), RtlpSysVolCreateSecurityDescriptor(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepCreateImpersonationTokenDacl(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), SeRmInitPhase1(), WmipCreateAdminSD(), and WmipInitializeSecurity().
NTSYSAPI NTSTATUS NTAPI RtlCreateAtomTable (IN ULONG NumberOfBuckets, OUT PVOID * AtomTableHandle)
Definition at line 313 of file atom.c.
References NULL, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_ATOM_TABLE_DEFAULT_NUMBER_OF_BUCKETS, RTL_ATOM_TABLE_SIGNATURE, RTL_PAGED_CODE, RtlpAllocateAtom(), RtlpFreeAtom(), RtlpInitializeHandleTableForAtomTable(), RtlpInitializeLockAtomTable(), RtlZeroMemory, _RTL_ATOM_TABLE::Signature, Status, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlCreateBootStatusDataFile (VOID)
NTSYSAPI NTSTATUS NTAPI RtlCreateEnvironment (BOOLEAN CloneCurrentEnvironment, PVOID * Environment)
NTSYSAPI PVOID NTAPI RtlCreateHeap (IN ULONG Flags, IN PVOID HeapBase OPTIONAL, IN SIZE_T ReserveSize OPTIONAL, IN SIZE_T CommitSize OPTIONAL, IN PVOID Lock OPTIONAL, IN PRTL_HEAP_PARAMETERS Parameters OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlCreateProcessParameters (PRTL_USER_PROCESS_PARAMETERS * ProcessParameters, PUNICODE_STRING ImagePathName, PUNICODE_STRING DllPath, PUNICODE_STRING CurrentDirectory, PUNICODE_STRING CommandLine, PVOID Environment, PUNICODE_STRING WindowTitle, PUNICODE_STRING DesktopInfo, PUNICODE_STRING ShellInfo, PUNICODE_STRING RuntimeData)
NTSYSAPI NTSTATUS NTAPI RtlCreateRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
Definition at line 1239 of file regutil.c.
References NT_SUCCESS, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlpGetRegistryHandle(), Status, STATUS_SUCCESS, TRUE, and ZwClose().
NTSYSAPI NTSTATUS NTAPI RtlCreateSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Revision)
Referenced by CmpHiveRootSecurityDescriptor(), ExpKeyedEventInitialization(), IopCreateDefaultDeviceSecurityDescriptor(), IopCreateSecurityDescriptorPerType(), MiCreateMemoryEvent(), NtCreatePagingFile(), NtOpenThreadTokenEx(), ObInitSystem(), ObpGetDosDevicesProtection(), RtlpSysVolCreateSecurityDescriptor(), RtlpSysVolTakeOwnership(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), SeRmInitPhase1(), WmipCreateAdminSD(), and WmipInitializeSecurity().
NTSYSAPI NTSTATUS NTAPI RtlCreateSecurityDescriptorRelative (PISECURITY_DESCRIPTOR_RELATIVE SecurityDescriptor, ULONG Revision)
Referenced by SeAssignWorldSecurityDescriptor(), and SeQuerySecurityDescriptorInfo().
NTSYSAPI NTSTATUS NTAPI RtlCreateSystemVolumeInformationFolder (IN PUNICODE_STRING VolumeRootPath)
Definition at line 441 of file sysvol.c.
References _UNICODE_STRING::Buffer, FALSE, FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_SYSTEM, FILE_DIRECTORY_FILE, FILE_OPEN_IF, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, InitializeObjectAttributes, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NtCreateFile(), NULL, OBJ_CASE_INSENSITIVE, READ_CONTROL, RTL_SYSTEM_VOLUME_INFORMATION_FOLDER, RtlCopyMemory, RtlInitUnicodeString(), RtlpSysVolAllocate(), RtlpSysVolCheckOwnerAndSecurity(), RtlpSysVolCreateSecurityDescriptor(), RtlpSysVolFree(), RtlpSysVolTakeOwnership(), STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, SYNCHRONIZE, TRUE, WRITE_DAC, and WRITE_OWNER.
NTSYSAPI BOOLEAN NTAPI RtlCreateUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCWSTR SourceString)
Definition at line 2042 of file nls.c.
References FALSE, MAX_USTRING, RTL_PAGED_CODE, RtlAllocateStringRoutine, RtlCopyMemory, TRUE, UNICODE_NULL, and wcslen().
Referenced by IopBootLog(), IopCopyBootLogRegistryToFile(), ObpCreateDosDevicesDirectory(), RtlConvertSidToUnicodeString(), WmipQueryGLRegistryRoutine(), WmipStartGlobalLogger(), WmipStartLogger(), WmipSwitchToNewFile(), WmipVerifyLoggerInfo(), and WmiUpdateTrace().
NTSYSAPI BOOLEAN NTAPI RtlCreateUnicodeStringFromAsciiz (OUT PUNICODE_STRING DestinationString, IN PCSZ SourceString)
Definition at line 641 of file string.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_OUT, FALSE, NT_SUCCESS, RTL_PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlInitAnsiStringEx(), Status, and TRUE.
Referenced by CmpSetSystemValues(), and IopInitializeBootLogging().
NTSYSAPI NTSTATUS NTAPI RtlCreateUserProcess (PUNICODE_STRING NtImagePathName, ULONG Attributes, PRTL_USER_PROCESS_PARAMETERS ProcessParameters, PSECURITY_DESCRIPTOR ProcessSecurityDescriptor, PSECURITY_DESCRIPTOR ThreadSecurityDescriptor, HANDLE ParentProcess, BOOLEAN InheritHandles, HANDLE DebugPort, HANDLE ExceptionPort, PRTL_USER_PROCESS_INFORMATION ProcessInformation)
Referenced by Phase1InitializationDiscard().
NTSYSAPI NTSTATUS NTAPI RtlCreateUserThread (HANDLE Process, PSECURITY_DESCRIPTOR ThreadSecurityDescriptor, BOOLEAN CreateSuspended, ULONG StackZeroBits, SIZE_T MaximumStackSize OPTIONAL, SIZE_T InitialStackSize OPTIONAL, PUSER_THREAD_START_ROUTINE StartAddress, PVOID Parameter, PHANDLE Thread, PCLIENT_ID ClientId)
Referenced by WmipCreatePumpThread().
NTSYSAPI NTSTATUS NTAPI RtlCustomCPToUnicodeN (__in PCPTABLEINFO CustomCP, __out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWCH UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString, __in_bcount(BytesInCustomCPString) PCH CustomCPString, __in ULONG BytesInCustomCPString)
Definition at line 1741 of file nlsxlat.c.
References ARGUMENT_PRESENT, RTL_PAGED_CODE, STATUS_BUFFER_OVERFLOW, STATUS_SUCCESS, and UnicodeNull.
NTSYSAPI BOOLEAN NTAPI RtlCutoverTimeToSystemTime (PTIME_FIELDS CutoverTime, PLARGE_INTEGER SystemTime, PLARGE_INTEGER CurrentSystemTime, BOOLEAN ThisYear)
Definition at line 676 of file time.c.
References _TIME_FIELDS::Day, FALSE, _TIME_FIELDS::Hour, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, _LARGE_INTEGER::QuadPart, RtlTimeFieldsToTime(), RtlTimeToTimeFields(), _TIME_FIELDS::Second, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
NTSYSAPI NTSTATUS NTAPI RtlDecompressBuffer (IN USHORT CompressionFormat, OUT PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, IN PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, OUT PULONG FinalUncompressedSize)
NTSYSAPI NTSTATUS NTAPI RtlDecompressChunks (OUT PUCHAR UncompressedBuffer, IN ULONG UncompressedBufferSize, IN PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN PUCHAR CompressedTail, IN ULONG CompressedTailSize, IN PCOMPRESSED_DATA_INFO CompressedDataInfo)
NTSYSAPI NTSTATUS NTAPI RtlDecompressFragment (IN USHORT CompressionFormat, OUT PUCHAR UncompressedFragment, IN ULONG UncompressedFragmentSize, IN PUCHAR CompressedBuffer, IN ULONG CompressedBufferSize, IN ULONG FragmentOffset, OUT PULONG FinalUncompressedSize, IN PVOID WorkSpace)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlDelete (PRTL_SPLAY_LINKS Links)
Referenced by FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), FsRtlPrivateFastUnlockAll(), FsRtlRemoveNodeFromTunnel(), PfxRemovePrefix(), RtlDeleteElementGenericTable(), and RtlRemoveUnicodePrefix().
NTSYSAPI NTSTATUS NTAPI RtlDeleteAce (PACL Acl, ULONG AceIndex)
NTSYSAPI NTSTATUS NTAPI RtlDeleteAtomFromAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
Definition at line 740 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::HashLink, KdPrint, _RTL_ATOM_TABLE_ENTRY::Name, NULL, _RTL_ATOM_TABLE_ENTRY::ReferenceCount, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlpAtomMapAtomToHandleEntry(), RtlpFreeAtom(), RtlpFreeHandleForAtom(), RtlpHashStringToAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and STATUS_WAS_LOCKED.
Referenced by NtDeleteAtom().
NTSYSAPI BOOLEAN NTAPI RtlDeleteElementGenericTable (PRTL_GENERIC_TABLE Table, PVOID Buffer)
NTSYSAPI BOOLEAN NTAPI RtlDeleteElementGenericTableAvl (PRTL_AVL_TABLE Table, PVOID Buffer)
NTSYSAPI VOID NTAPI RtlDeleteNoSplay (PRTL_SPLAY_LINKS Links, PRTL_SPLAY_LINKS * Root)
Referenced by FsRtlPrivateInsertSharedLock(), FsRtlRemoveNodeFromTunnel(), and FsRtlUninitializeFileLock().
NTSYSAPI NTSTATUS NTAPI RtlDeleteOwnersRanges (IN OUT PRTL_RANGE_LIST RangeList, IN PVOID Owner)
NTSYSAPI NTSTATUS NTAPI RtlDeleteRange (IN OUT PRTL_RANGE_LIST RangeList, IN ULONGLONG Start, IN ULONGLONG End, IN PVOID Owner)
NTSYSAPI NTSTATUS NTAPI RtlDeleteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName)
Definition at line 1262 of file regutil.c.
References KeyValueName, NT_SUCCESS, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlInitUnicodeString(), RtlpGetRegistryHandle(), Status, TRUE, ZwClose(), and ZwDeleteValueKey().
NTSYSAPI PRTL_USER_PROCESS_PARAMETERS NTAPI RtlDeNormalizeProcessParams (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
Referenced by Phase1InitializationDiscard().
NTSYSAPI NTSTATUS NTAPI RtlDescribeChunk (IN USHORT CompressionFormat, IN OUT PUCHAR * CompressedBuffer, IN PUCHAR EndOfCompressedBufferPlus1, OUT PUCHAR * ChunkBuffer, OUT PULONG ChunkSize)
NTSYSAPI NTSTATUS NTAPI RtlDestroyAtomTable (IN PVOID AtomTableHandle)
Definition at line 356 of file atom.c.
References _RTL_ATOM_TABLE::Buckets, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::HashLink, NULL, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_PAGED_CODE, RtlpDestroyHandleTableForAtomTable(), RtlpDestroyLockAtomTable(), RtlpFreeAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), RtlZeroMemory, _RTL_ATOM_TABLE::Signature, Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlDestroyEnvironment (PVOID Environment)
NTSYSAPI PVOID NTAPI RtlDestroyHeap (IN PVOID HeapHandle)
NTSYSAPI NTSTATUS NTAPI RtlDestroyProcessParameters (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
NTSYSAPI NTSTATUS RtlDnsHostNameToComputerName (OUT PUNICODE_STRING ComputerNameString, IN PCUNICODE_STRING DnsHostNameString, IN BOOLEAN AllocateComputerNameString)
Definition at line 2629 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, _STRING::Buffer, _UNICODE_STRING::Buffer, _STRING::Length, _UNICODE_STRING::Length, _STRING::MaximumLength, NETBIOS_NAME_LEN, NT_SUCCESS, RTL_PAGED_CODE, RtlOemStringToUnicodeString(), RtlpDidUnicodeToOemWork(), RtlUpcaseUnicodeToOemN(), Status, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_COMPUTER_NAME, and STATUS_SUCCESS.
NTSYSAPI WCHAR NTAPI RtlDowncaseUnicodeChar (WCHAR SourceCharacter)
NTSTATUS RtlDowncaseUnicodeString (OUT PUNICODE_STRING DestinationString, IN PCUNICODE_STRING SourceString, IN BOOLEAN AllocateDestinationString)
Definition at line 1119 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, ASSERT_WELL_FORMED_UNICODE_STRING_OUT, Index, NLS_DOWNCASE, RTL_PAGED_CODE, RtlAllocateStringRoutine, STATUS_BUFFER_OVERFLOW, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlDuplicateUnicodeString (IN ULONG Flags, IN const UNICODE_STRING * StringIn, OUT UNICODE_STRING * StringOut)
NTSYSAPI NTSTATUS NTAPI RtlEmptyAtomTable (IN PVOID AtomTableHandle, IN BOOLEAN IncludePinnedAtoms)
Definition at line 397 of file atom.c.
References _RTL_ATOM_TABLE::Buckets, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::HashLink, NULL, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlpFreeAtom(), RtlpFreeHandleForAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlEnlargedIntegerMultiply (LONG Multiplicand, LONG Multiplier)
Definition at line 4744 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
DECLSPEC_DEPRECATED_DDK __inline ULONG NTAPI RtlEnlargedUnsignedDivide (IN ULARGE_INTEGER Dividend, IN ULONG Divisor, IN PULONG Remainder OPTIONAL)
Definition at line 4782 of file ntrtl.h.
References ARGUMENT_PRESENT.
Referenced by KiCalibrateTimeAdjustment().
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlEnlargedUnsignedMultiply (ULONG Multiplicand, ULONG Multiplier)
Definition at line 4763 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
Referenced by KiCalibrateTimeAdjustment().
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTable (PRTL_GENERIC_TABLE Table, BOOLEAN Restart)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableAvl (PRTL_AVL_TABLE Table, BOOLEAN Restart)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableLikeADirectory (IN PRTL_AVL_TABLE Table, IN PRTL_AVL_MATCH_FUNCTION MatchFunction, IN PVOID MatchData, IN ULONG NextFlag, IN OUT PVOID * RestartKey, IN OUT PULONG DeleteCount, IN OUT PVOID Buffer)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableWithoutSplaying (PRTL_GENERIC_TABLE Table, PVOID * RestartKey)
NTSYSAPI PVOID NTAPI RtlEnumerateGenericTableWithoutSplayingAvl (PRTL_AVL_TABLE Table, PVOID * RestartKey)
NTSYSAPI BOOLEAN NTAPI RtlEqualComputerName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
Definition at line 2147 of file nls.c.
References RtlEqualDomainName().
NTSYSAPI BOOLEAN NTAPI RtlEqualDomainName (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2)
Definition at line 2069 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, FALSE, NT_SUCCESS, RTL_PAGED_CODE, RtlEqualString(), RtlFreeOemString(), RtlUpcaseUnicodeStringToOemString(), Status, and TRUE.
Referenced by RtlEqualComputerName().
NTSYSAPI BOOLEAN NTAPI RtlEqualPrefixSid (PSID Sid1, PSID Sid2)
NTSYSAPI BOOLEAN NTAPI RtlEqualSid (PSID Sid1, PSID Sid2)
Referenced by IopCreateDefaultDeviceSecurityDescriptor(), NtSecureConnectPort(), NtSetInformationToken(), RtlpSysVolCheckOwnerAndSecurity(), SeFastTraverseCheck(), SepAdjustGroups(), SepAdtPrivilegeObjectAuditAlarm(), SepCreateToken(), SepIdAssignableAsGroup(), SepMakeTokenEffectiveOnly(), SepRemoveDisabledGroupsAndPrivileges(), SePrivilegedServiceAuditAlarm(), SepSidInSidAndAttributes(), SepSidInToken(), SepSidInTokenEx(), SepValidOwnerSubjectContext(), and SeTokenCanImpersonate().
NTSYSAPI BOOLEAN NTAPI RtlEqualString (const STRING * String1, const STRING * String2, BOOLEAN CaseInSensitive)
Referenced by IoGetBootDiskInformation(), IopCreateArcNamesDisk(), IopInitializeBuiltinDriver(), and RtlEqualDomainName().
NTSYSAPI BOOLEAN NTAPI RtlEqualUnicodeString (PCUNICODE_STRING String1, PCUNICODE_STRING String2, BOOLEAN CaseInSensitive)
Referenced by CmpDoSort(), CmpResolveDriverDependencies(), CmSetValueKey(), HalpNextDriveLetter(), IopLoadDriver(), MiBuildImportsForBootDrivers(), MiFindInitializationCode(), MiResolveImageReferences(), MiUseLargeDriverPage(), MmGetSystemRoutineAddress(), MmLoadSystemImage(), ObpLookupDirectoryEntry(), RtlQueryEnvironmentVariable_U(), and WmipLookupLoggerIdByName().
NTSYSAPI VOID NTAPI RtlEraseUnicodeString (PUNICODE_STRING String)
Definition at line 616 of file sertl.c.
References _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, RTL_PAGED_CODE, and RtlZeroMemory.
DECLSPEC_NORETURN NTSYSAPI VOID NTAPI RtlExitUserThread (IN NTSTATUS ExitStatus)
NTSYSAPI NTSTATUS NTAPI RtlExpandEnvironmentStrings_U (IN PVOID Environment OPTIONAL, IN PCUNICODE_STRING Source, OUT PUNICODE_STRING Destination, OUT PULONG ReturnedLength OPTIONAL)
Definition at line 1290 of file regutil.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, RTL_PAGED_CODE, RtlQueryEnvironmentVariable_U(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by RtlpCallQueryRegistryRoutine().
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlExtendedIntegerMultiply (LARGE_INTEGER Multiplicand, LONG Multiplier)
Referenced by MiAttemptPageFileExtension(), and RawQueryFsSizeInfo().
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlExtendedLargeIntegerDivide (LARGE_INTEGER Dividend, ULONG Divisor, PULONG Remainder)
Referenced by KiCalibrateTimeAdjustment(), and RawQueryFsSizeInfo().
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlExtendedMagicDivide (LARGE_INTEGER Dividend, LARGE_INTEGER MagicDivisor, CCHAR ShiftCount)
NTSYSAPI VOID NTAPI RtlFillMemoryUlong (PVOID Destination, SIZE_T Length, ULONG Pattern)
Referenced by MiCcPutPagesInTransition(), MiFreePoolPages(), MiMakeOutswappedPageResident(), MiResolveMappedFileFault(), MiWaitForInPageComplete(), and RtlSetAllBits().
NTSYSAPI VOID NTAPI RtlFillMemoryUlonglong (PVOID Destination, SIZE_T Length, ULONGLONG Pattern)
NTSYSAPI NTSTATUS NTAPI RtlFindCharInUnicodeString (IN ULONG Flags, IN PCUNICODE_STRING StringToSearch, IN PCUNICODE_STRING CharSet, OUT USHORT * NonInclusivePrefixLength)
Referenced by RtlQueryEnvironmentVariable_U().
NTSYSAPI ULONG NTAPI RtlFindClearBits (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
Referenced by MiFindEmptyAddressRange(), MiGatherPagefilePages(), and MmGetSessionMappedViewInformation().
NTSYSAPI ULONG NTAPI RtlFindClearBitsAndSet (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
Referenced by MiAllocatePoolPages(), MiGatherPagefilePages(), MiInsertInSystemSpace(), MiMapWithLargePages(), MiSessionCreateInternal(), and MiSessionWideReserveImageAddress().
NTSYSAPI ULONG NTAPI RtlFindClearRuns (PRTL_BITMAP BitMapHeader, PRTL_BITMAP_RUN RunArray, ULONG SizeOfRunArray, BOOLEAN LocateLongestRuns)
NTSYSAPI ULONG NTAPI RtlFindFirstRunClear (PRTL_BITMAP BitMapHeader, PULONG StartingIndex)
NTSYSAPI ULONG NTAPI RtlFindLastBackwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
Definition at line 2794 of file bitmap.c.
References MAXULONG, RTL_PAGED_CODE, and RtlCheckBit.
NTSYSAPI CCHAR NTAPI RtlFindLeastSignificantBit (IN ULONGLONG Set)
Definition at line 3031 of file bitmap.c.
References BM_0, BM_01, BM_0123, BM_2, BM_4, BM_45, and BM_6.
NTSYSAPI ULONG NTAPI RtlFindLongestRunClear (PRTL_BITMAP BitMapHeader, PULONG StartingIndex)
Referenced by MmGetSessionMappedViewInformation().
NTSYSAPI NTSTATUS NTAPI RtlFindMessage (PVOID DllHandle, ULONG MessageTableId, ULONG MessageLanguageId, ULONG MessageId, PMESSAGE_RESOURCE_ENTRY * MessageEntry)
Referenced by ExpSystemErrorHandler(), IopInitializeBootLogging(), and Phase1InitializationDiscard().
NTSYSAPI CCHAR NTAPI RtlFindMostSignificantBit (IN ULONGLONG Set)
Definition at line 2938 of file bitmap.c.
References BM_1, BM_23, BM_3, BM_4567, BM_5, BM_67, and BM_7.
Referenced by NtAllocateVirtualMemory(), and NtMapViewOfSection().
NTSYSAPI ULONG NTAPI RtlFindNextForwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
Definition at line 2650 of file bitmap.c.
References RtlCheckBit.
Referenced by RtlFindFirstRunClear().
NTSYSAPI NTSTATUS NTAPI RtlFindRange (IN PRTL_RANGE_LIST RangeList, IN ULONGLONG Minimum, IN ULONGLONG Maximum, IN ULONG Length, IN ULONG Alignment, IN ULONG Flags, IN UCHAR AttributeAvailableMask, IN PVOID Context OPTIONAL, IN PRTL_CONFLICT_RANGE_CALLBACK Callback OPTIONAL, OUT PULONGLONG Start)
NTSYSAPI ULONG NTAPI RtlFindSetBits (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
Referenced by MiCleanPhysicalProcessPages(), and NtGetWriteWatch().
NTSYSAPI ULONG NTAPI RtlFindSetBitsAndClear (PRTL_BITMAP BitMapHeader, ULONG NumberToFind, ULONG HintIndex)
NTSYSAPI PUNICODE_PREFIX_TABLE_ENTRY NTAPI RtlFindUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, PUNICODE_STRING FullName, ULONG CaseInsensitiveIndex)
NTSYSAPI PSLIST_ENTRY NTAPI RtlFirstEntrySList (IN const SLIST_HEADER * ListHead)
NTSYSAPI BOOLEAN NTAPI RtlFirstFreeAce (PACL Acl, PVOID * FirstFree)
Referenced by RtlpCopyAces(), RtlpGenerateInheritedAce(), and RtlpInheritAcl2().
NTSYSAPI BOOLEAN RtlFlushSecureMemoryCache (PVOID lpAddr, SIZE_T size)
NTSYSAPI NTSTATUS NTAPI RtlFormatCurrentUserKeyPath (OUT PUNICODE_STRING CurrentUserKeyPath)
Definition at line 1414 of file regutil.c.
References _UNICODE_STRING::Buffer, FALSE, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtCurrentProcess, NtCurrentThread, NULL, OBJ_KERNEL_HANDLE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), RtlAllocateStringRoutine, RtlAppendUnicodeToString(), RtlConvertSidToUnicodeString(), RtlFreeUnicodeString(), RtlLengthSidAsUnicodeString(), SIZE_OF_TOKEN_INFORMATION, Status, STATUS_NO_MEMORY, STATUS_NO_TOKEN, TOKEN_READ, TokenUser, TRUE, UNICODE_NULL, ZwClose(), ZwOpenProcessTokenEx(), ZwOpenThreadTokenEx(), and ZwQueryInformationToken().
Referenced by RtlOpenCurrentUser(), and RtlpGetRegistryHandle().
NTSYSAPI NTSTATUS NTAPI RtlFormatMessage (__in PWSTR MessageFormat, __in ULONG MaximumWidth, __in BOOLEAN IgnoreInserts, __in BOOLEAN ArgumentsAreAnsi, __in BOOLEAN ArgumentsAreAnArray, __in va_list * Arguments, __out_bcount_part(Length,*ReturnLength) PWSTR Buffer, __in ULONG Length, __out_opt PULONG ReturnLength)
NTSYSAPI NTSTATUS NTAPI RtlFormatMessageEx (__in PWSTR MessageFormat, __in ULONG MaximumWidth, __in BOOLEAN IgnoreInserts, __in BOOLEAN ArgumentsAreAnsi, __in BOOLEAN ArgumentsAreAnArray, __in va_list * Arguments, __out_bcount_part(Length,*ReturnLength) PWSTR Buffer, __in ULONG Length, __out_opt PULONG ReturnLength, __out_opt PPARSE_MESSAGE_CONTEXT ParseContext)
NTSYSAPI VOID NTAPI RtlFreeAnsiString (PANSI_STRING AnsiString)
Referenced by MiLoadUserSymbols(), MiSegmentDelete(), MmGetSystemRoutineAddress(), MmUnloadSystemImage(), and WmiTraceProcess().
NTSYSAPI BOOLEAN NTAPI RtlFreeHeap (IN PVOID HeapHandle, IN ULONG Flags, IN PVOID BaseAddress)
Referenced by RtlDestroyProcessParameters().
NTSYSAPI VOID NTAPI RtlFreeOemString (POEM_STRING OemString)
NTSYSAPI VOID NTAPI RtlFreeRangeList (IN PRTL_RANGE_LIST RangeList)
NTSYSAPI PVOID NTAPI RtlFreeSid (IN PSID Sid)
NTSYSAPI NTSTATUS NTAPI RtlFreeToPeb (PVOID Block, ULONG Size)
NTSYSAPI VOID NTAPI RtlFreeUnicodeString (PUNICODE_STRING UnicodeString)
Referenced by CmpInitializeRegistryNode(), CmpSetSystemValues(), CmUnloadKey(), CreateSystemRootLink(), FsRtlAreNamesEqual(), FsRtlIsNameInExpression(), HalpNextDriveLetter(), IoAssignDriveLetters(), IoGetBootDiskInformation(), IopBootLog(), IopCopyBootLogRegistryToFile(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopMarkBootPartition(), IopReassignSystemRoot(), MiReleaseAllMemory(), MiRememberUnloadedDriver(), MiResolveImageReferences(), MiSnapThunk(), MmLoadSystemImage(), RtlFormatCurrentUserKeyPath(), RtlOpenCurrentUser(), RtlpGetRegistryHandle(), SepInitializationPhase1(), WmipCreateLogFile(), WmipDelayCreate(), WmipFreeLoggerContext(), WmipQueryWmiDataBlock(), WmipStartGlobalLogger(), WmipStartLogger(), WmipSwitchToNewFile(), WmipTranslateFileHandle(), WmipTranslatePDOInstanceNames(), WmipVerifyLoggerInfo(), and WmiUpdateTrace().
NTSYSAPI VOID NTAPI RtlFreeUserThreadStack (HANDLE hProcess, HANDLE hThread)
Definition at line 1343 of file rtlexec.c.
References MEM_RELEASE, NT_SUCCESS, NtFreeVirtualMemory(), NtQueryInformationThread(), NtReadVirtualMemory(), NULL, Status, _THREAD_BASIC_INFORMATION::TebBaseAddress, and ThreadBasicInformation.
NTSYSAPI VOID NTAPI RtlGenerate8dot3Name (IN PUNICODE_STRING Name, IN BOOLEAN AllowExtendedCharacters, IN OUT PGENERATE_NAME_CONTEXT Context, OUT PUNICODE_STRING Name8dot3)
NTSYSAPI NTSTATUS NTAPI RtlGetAce (PACL Acl, ULONG AceIndex, PVOID * Ace)
Referenced by CmpHiveRootSecurityDescriptor(), IopCreateDefaultDeviceSecurityDescriptor(), ObInitSystem(), ObpGetDosDevicesProtection(), and RtlpSysVolCheckOwnerAndSecurity().
NTSYSAPI VOID NTAPI RtlGetCallersAddress (OUT PVOID * CallersAddress, OUT PVOID * CallersCaller)
Definition at line 262 of file stkwalk.c.
References FALSE, MmCanThreadFault(), NULL, PsGetCurrentThread(), RtlCaptureContext(), RtlpGetStackLimits(), RtlpIsFrameInBounds(), RtlpLookupFunctionEntryForStackWalks(), RtlVirtualUnwind(), TRUE, and UNW_FLAG_NHANDLER.
Referenced by __bcount(), __out_bcount(), CmpAllocate(), CmpFree(), CmpLockRegistry(), CmpLockRegistryExclusive(), MmMapLockedPagesSpecifyCache(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
NTSYSAPI NTSTATUS NTAPI RtlGetCompressionWorkSpaceSize (IN USHORT CompressionFormatAndEngine, OUT PULONG CompressBufferWorkSpaceSize, OUT PULONG CompressFragmentWorkSpaceSize)
NTSYSAPI NTSTATUS NTAPI RtlGetControlSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, PSECURITY_DESCRIPTOR_CONTROL Control, PULONG Revision)
PPEB RtlGetCurrentPeb (VOID)
Definition at line 28 of file peb.c.
References PAGED_CODE, _EPROCESS::Peb, and PsGetCurrentProcess().
Referenced by RtlSetProcessIsCritical(), and RtlSetThreadIsCritical().
NTSYSAPI NTSTATUS NTAPI RtlGetDaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN DaclPresent, OUT PACL * Dacl, OUT PBOOLEAN DaclDefaulted)
Definition at line 2409 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpDaclAddrSecurityDescriptor, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by ObpFreeDosDevicesProtection(), and RtlpSysVolCheckOwnerAndSecurity().
NTSYSAPI VOID NTAPI RtlGetDefaultCodePage (OUT PUSHORT AnsiCodePage, OUT PUSHORT OemCodePage)
Definition at line 2478 of file nlsxlat.c.
References NlsAnsiCodePage, NlsOemCodePage, and RTL_PAGED_CODE.
NTSYSAPI PVOID NTAPI RtlGetElementGenericTable (PRTL_GENERIC_TABLE Table, ULONG I)
NTSYSAPI PVOID NTAPI RtlGetElementGenericTableAvl (PRTL_AVL_TABLE Table, ULONG I)
NTSYSAPI NTSTATUS NTAPI RtlGetFirstRange (IN PRTL_RANGE_LIST RangeList, OUT PRTL_RANGE_LIST_ITERATOR Iterator, OUT PRTL_RANGE * Range)
NTSYSAPI NTSTATUS NTAPI RtlGetGroupSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID * Group, OUT PBOOLEAN GroupDefaulted)
Definition at line 2976 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpGroupAddrSecurityDescriptor, SE_GROUP_DEFAULTED, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
NTSTATUS NTAPI RtlGetLastNtStatus (VOID)
Definition at line 188 of file error.c.
References NtCurrentTeb().
NTSYSAPI NTSTATUS NTAPI RtlGetLastRange (IN PRTL_RANGE_LIST RangeList, OUT PRTL_RANGE_LIST_ITERATOR Iterator, OUT PRTL_RANGE * Range)
NTSYSAPI LONG NTAPI RtlGetLastWin32Error (VOID)
Definition at line 197 of file error.c.
References NtCurrentTeb().
NTSYSAPI NTSTATUS NTAPI RtlGetNextRange (IN OUT PRTL_RANGE_LIST_ITERATOR Iterator, OUT PRTL_RANGE * Range, IN BOOLEAN MoveForwards)
NTSYSAPI ULONG NTAPI RtlGetNtGlobalFlags (VOID)
Definition at line 1397 of file regutil.c.
References NtGlobalFlag.
Referenced by RtlCreateUserProcess().
NTSYSAPI BOOLEAN NTAPI RtlGetNtProductType (PNT_PRODUCT_TYPE NtProductType)
NTSYSAPI NTSTATUS NTAPI RtlGetOwnerSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID * Owner, OUT PBOOLEAN OwnerDefaulted)
Definition at line 2803 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpOwnerAddrSecurityDescriptor, SE_OWNER_DEFAULTED, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by RtlpSysVolCheckOwnerAndSecurity().
NTSTATUS NTAPI RtlGetPrimaryDomain (IN ULONG SidLength, OUT PBOOLEAN PrimaryDomainPresent, OUT PUNICODE_STRING PrimaryDomainName, OUT PUSHORT RequiredNameLength, OUT PSID PrimaryDomainSid OPTIONAL, OUT PULONG RequiredSidLength)
NTSYSAPI NTSTATUS NTAPI RtlGetSaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN SaclPresent, OUT PACL * Sacl, OUT PBOOLEAN SaclDefaulted)
Definition at line 2615 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpSaclAddrSecurityDescriptor, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
NTSYSAPI BOOLEAN NTAPI RtlGetSecurityDescriptorRMControl (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PUCHAR RMControl)
Definition at line 10300 of file sertl.c.
References _SECURITY_DESCRIPTOR::Control, FALSE, _SECURITY_DESCRIPTOR::Sbz1, SE_RM_CONTROL_VALID, and TRUE.
NTSYSAPI NTSTATUS NTAPI RtlGetSetBootStatusData (IN HANDLE Handle, IN BOOLEAN Get, IN RTL_BSD_ITEM_TYPE DataItem, IN PVOID DataBuffer, IN ULONG DataBufferLength, OUT PULONG ByteRead OPTIONAL)
NTSYSAPI NTSTATUS RtlGetVersion (OUT PRTL_OSVERSIONINFOW lpVersionInformation)
NTSYSAPI NTSTATUS NTAPI RtlGUIDFromString (IN PUNICODE_STRING GuidString, OUT GUID * Guid)
Definition at line 181 of file guid.c.
References Count, GuidFormat, RTL_PAGED_CODE, ScanHexFormat(), STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlHashUnicodeString (IN const UNICODE_STRING * String, IN BOOLEAN CaseInSensitive, IN ULONG HashAlgorithm, OUT PULONG HashValue)
NTSYSAPI PSID_IDENTIFIER_AUTHORITY NTAPI RtlIdentifierAuthoritySid (PSID Sid)
NTSYSAPI PVOID NTAPI RtlImageDirectoryEntryToData (PVOID BaseOfImage, BOOLEAN MappedAsImage, USHORT DirectoryEntry, PULONG Size)
Referenced by LdrEnumResources(), LdrpAccessResourceDataNoMultipleLanguage(), LdrpSearchResourceSection_U(), LdrRelocateImageWithBias(), LookupEntryPoint(), MiBuildImportsForBootDrivers(), MiCacheImageSymbols(), MiFindExportedRoutineByName(), MiLocateExportName(), MiResolveImageReferences(), MiSnapThunk(), MiUpdateThunks(), MmCreatePeb(), NtSetSystemInformation(), and RtlCaptureImageExceptionValues().
NTSYSAPI PIMAGE_NT_HEADERS NTAPI RtlImageNtHeader (PVOID Base)
Definition at line 173 of file rtlnthdr.c.
References NULL, RTL_IMAGE_NT_HEADER_EX_FLAG_NO_RANGE_CHECK, RtlImageNtHeaderEx(), and VOID.
Referenced by DbgkCreateThread(), DbgkMapViewOfSection(), DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), DbgLoadImageSymbols(), IopInitializeBuiltinDriver(), IopLoadDriver(), LdrFindEntryForAddress(), LdrpAccessResourceDataNoMultipleLanguage(), LdrRelocateImageWithBias(), MiCaptureImageExceptionValues(), MiEnablePagingOfDriver(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiLocateKernelSections(), MiReloadBootLoadedDrivers(), MiSessionProcessGlobalSubsections(), MiWriteProtectSystemImage(), MmCheckSystemImage(), MmCreatePeb(), MmFreeDriverInitialization(), MmGetSectionRange(), MmInitSystem(), MmLoadSystemImage(), MmLockPageableDataSection(), MmResetDriverPaging(), MmVerifyImageIsOkForMpUse(), NtSetSystemInformation(), RtlCaptureImageExceptionValues(), RtlImageDirectoryEntryToData(), RtlpCreateStack(), and WmipReceiveNotifications().
NTSYSAPI NTSTATUS NTAPI RtlImageNtHeaderEx (ULONG Flags, PVOID Base, ULONG64 Size, OUT PIMAGE_NT_HEADERS * OutHeaders)
Definition at line 37 of file rtlnthdr.c.
References EXIT, IMAGE_DOS_SIGNATURE, IMAGE_NT_SIGNATURE, MAXULONG, MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, RTL_IMAGE_NT_HEADER_EX_FLAG_NO_RANGE_CHECK, _IMAGE_NT_HEADERS::Signature, SIZEOF_PE_SIGNATURE, Status, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlImageNtHeader().
NTSYSAPI PIMAGE_SECTION_HEADER NTAPI RtlImageRvaToSection (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Rva)
NTSYSAPI PVOID NTAPI RtlImageRvaToVa (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Rva, IN OUT PIMAGE_SECTION_HEADER *LastRvaSection OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlImpersonateSelf (IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 3284 of file sertl.c.
References NULL, RTL_PAGED_CODE, and RtlpImpersonateSelfEx().
NTSYSAPI VOID NTAPI RtlInitAnsiString (PANSI_STRING DestinationString, PCSZ SourceString)
Referenced by CmpAddAliasEntry(), CmpCreateControlSet(), CmpInitializeRegistryNode(), CmpInitializeSystemHive(), CreateSystemRootLink(), ExpSystemErrorHandler(), IoAssignDriveLetters(), IoGetBootDiskInformation(), IopCopyBootLogRegistryToFile(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopMarkBootPartition(), IopReassignSystemRoot(), MiResolveImageReferences(), MmLoadSystemImage(), PerfInfoSysModuleRunDown(), WmipDriverEntry(), and WmipQueryWmiRegInfo().
NTSYSAPI NTSTATUS NTAPI RtlInitAnsiStringEx (OUT PANSI_STRING DestinationString, IN PCSZ SourceString OPTIONAL)
Definition at line 246 of file string.c.
References ARGUMENT_PRESENT, MAXUSHORT, STATUS_NAME_TOO_LONG, STATUS_SUCCESS, and strlen().
Referenced by RtlCreateUnicodeStringFromAsciiz().
NTSYSAPI VOID NTAPI RtlInitCodePageTable (IN PUSHORT TableBase, OUT PCPTABLEINFO CodePageTable)
Definition at line 2335 of file nlsxlat.c.
References DBCS_HEADER, GLYPH_HEADER, GLYPH_TBL_SIZE, MAXIMUM_LEADBYTES, MB_TBL_SIZE, NULL, RTL_PAGED_CODE, and RtlCopyMemory.
Referenced by RtlInitNlsTables().
NTSYSAPI NTSTATUS NTAPI RtlInitializeAtomPackage (IN ULONG AllocationTag)
Definition at line 303 of file atom.c.
References RTL_PAGED_CODE, RtlpAtomAllocateTag, and STATUS_SUCCESS.
Referenced by ExpInitSystemPhase1().
NTSYSAPI VOID NTAPI RtlInitializeBitMap (PRTL_BITMAP BitMapHeader, PULONG BitMapBuffer, ULONG SizeOfBitMap)
Referenced by CmpOverwriteHive(), HvInitializeHive(), HvpAddBin(), HvpAdjustBitmap(), HvpBuildMapAndCopy(), HvpDoWriteHive(), HvpFreeHiveFreeDisplay(), HvpInitMap(), HvpRecoverData(), MiInitializeLargePageSupport(), MiSessionWideInitializeAddresses(), MmInitSystem(), MmPerfSnapShotValidPhysicalMemory(), NtAllocateUserPhysicalPages(), and NtAllocateVirtualMemory().
NTSYSAPI VOID NTAPI RtlInitializeContext (HANDLE Process, PCONTEXT Context, PVOID Parameter, PVOID InitialPc, PVOID InitialSp)
Referenced by RtlCreateUserThread().
NTSYSAPI VOID NTAPI RtlInitializeExceptionLog (IN ULONG Entries)
Definition at line 28 of file excptdbg.c.
References ExAllocatePoolWithTag, NonPagedPool, NULL, and RtlpExceptionLogSize.
Referenced by ExpInitializeExecutive().
NTSYSAPI VOID NTAPI RtlInitializeGenericTable (PRTL_GENERIC_TABLE Table, PRTL_GENERIC_COMPARE_ROUTINE CompareRoutine, PRTL_GENERIC_ALLOCATE_ROUTINE AllocateRoutine, PRTL_GENERIC_FREE_ROUTINE FreeRoutine, PVOID TableContext)
NTSYSAPI VOID NTAPI RtlInitializeGenericTableAvl (PRTL_AVL_TABLE Table, PRTL_AVL_COMPARE_ROUTINE CompareRoutine, PRTL_AVL_ALLOCATE_ROUTINE AllocateRoutine, PRTL_AVL_FREE_ROUTINE FreeRoutine, PVOID TableContext)
NTSYSAPI NTSTATUS NTAPI RtlInitializeHeapManager (VOID)
NTSYSAPI VOID NTAPI RtlInitializeRangeList (IN OUT PRTL_RANGE_LIST RangeList)
VOID NTAPI RtlInitializeRangeListPackage (VOID)
Referenced by Phase1InitializationDiscard().
NTSYSAPI NTSTATUS NTAPI RtlInitializeRXact (IN HANDLE RootRegistryKey, IN BOOLEAN CommitIfNecessary, OUT PRTL_RXACT_CONTEXT * RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlInitializeSid (PSID Sid, PSID_IDENTIFIER_AUTHORITY IdentifierAuthority, UCHAR SubAuthorityCount)
Referenced by CmpHiveRootSecurityDescriptor(), and SepVariableInitialization().
NTSYSAPI VOID NTAPI RtlInitializeSListHead (IN PSLIST_HEADER ListHead)
NTSYSAPI VOID NTAPI RtlInitializeUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable)
NTSYSAPI VOID NTAPI RtlInitNlsTables (IN PUSHORT AnsiNlsBase, IN PUSHORT OemNlsBase, IN PUSHORT LanguageNlsBase, OUT PNLSTABLEINFO TableInfo)
Definition at line 2420 of file nlsxlat.c.
References RTL_PAGED_CODE, RtlInitCodePageTable(), and RtlpInitUpcaseTable().
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTSYSAPI VOID NTAPI RtlInitString (PSTRING DestinationString, PCSZ SourceString)
Referenced by CreateSystemRootLink(), ExpInitializeExecutive(), IoAssignDriveLetters(), MmLoadSystemImage(), and SepInitializationPhase1().
NTSYSAPI VOID NTAPI RtlInitUnicodeString (PUNICODE_STRING DestinationString, PCWSTR SourceString)
Referenced by CmGetSystemControlValues(), CmGetSystemDriverList(), CmpAddAliasEntry(), CmpAddDockingInfo(), CmpAddDriverToList(), CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreatePerfKeys(), CmpCreatePredefined(), CmpCreateRootNode(), CmpFindControlSet(), CmpFindDrivers(), CmpFindNLSData(), CmpFindProfileOption(), CmpInitializeHiveList(), CmpInitializeRegistryNames(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpIsLoadType(), CmpLinkKeyToHive(), CmpLoadHiveThread(), CmpMapCmView(), CmpMarkCurrentValueDirty(), CmpOpenHiveFiles(), CmpPinCmView(), CmpRaiseSelfHealWarningForSystemHives(), CmpRemoveFromHiveFileList(), CmpSaveBootControlSet(), CmpSetCurrentProfile(), CmpSetNetworkValue(), CmpSetSystemValues(), CmpSortDriverList(), CmpTouchView(), CmpValidateSelect(), CmpWalkPath(), CreateSystemRootLink(), DbgkCreateThread(), DbgkInitialize(), ExpEventInitialization(), ExpEventPairInitialization(), ExpGetCurrentUserUILanguage(), ExpGetUILanguagePolicy(), ExpInitializeCallbacks(), ExpIsValidUILanguage(), ExpKeyedEventInitialization(), ExpMutantInitialization(), ExpProfileInitialization(), ExpQueryLegacyDriverInformation(), ExpSemaphoreInitialization(), ExpSetCurrentUserUILanguage(), ExpSystemErrorHandler(), ExpTimerInitialization(), ExpUuidLoadSequenceNumber(), ExpUuidSaveSequenceNumber(), ExpValidateLocale(), ExpWin32Initialization(), FsRtlpOpenDev(), FsRtlpSetSymbolicLink(), FsRtlRegisterUncProvider(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpNextDriveLetter(), HalpNextMountLetter(), HalpSetMountLetter(), HvMapHive(), HvpAddBin(), HvpDoAllocateCell(), HvpFindFreeCell(), IoAssignDriveLetters(), IoCreateDevice(), IoInitSystem(), IoIsValidNameGraftingBuffer(), IopBootLog(), IopBootLogToFile(), IopComputeHarddiskDerangements(), IopConnectLinkTrackingPort(), IopCopyBootLogRegistryToFile(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopCreateObjectTypes(), IopCreateRootDirectories(), IopDeleteSessionSymLinks(), IopErrorLogConnectPort(), IopGetRegistryValue(), IopLoadDriver(), IopRaiseHardError(), IopSafebootDriverLoad(), IoSetSystemPartition(), IoVolumeDeviceToDosName(), IoWMIOpenBlock(), KeSetup80387OrEmulate(), LpcInitSystem(), LpcpCreatePort(), MmLoadSystemImage(), NtCreateSymbolicLinkObject(), NtQueryDirectoryObject(), NtQueryOpenSubKeys(), NtSetDefaultLocale(), ObGetObjectInformation(), ObInitSystem(), ObpCreateDosDevicesDirectory(), ObpIsUnsecureName(), ObpProcessDosDeviceSymbolicLink(), ObShutdownSystem(), PspInitPhase0(), RawInitialize(), RtlCreateSystemVolumeInformationFolder(), RtlCreateUserProcess(), RtlDeleteRegistryValue(), RtlOpenCurrentUser(), RtlQueryRegistryValues(), RtlWriteRegistryValue(), SeGetLogonIdDeviceMap(), SepAdtInitializePrivilegeAuditing(), SepAuditFailed(), SepCleanupLUIDDeviceMapDirectory(), SepRegQueryHelper(), SepRmCommandServerThreadInit(), SepTokenInitialization(), SeRmInitPhase1(), WMIInitialize(), WmipCheckGuidAccess(), WmipCheckIsWbemRunning(), WmipCreateDirectoryFile(), WmipCreateGuidObject(), WmipDelayCreate(), WmipDriverEntry(), WmipGenerateFileName(), WmipInitializeSecurity(), WmipSecurityMethod(), WmipStartGlobalLogger(), WmipStartLogger(), WmipVerifyLoggerInfo(), and WmiQueryTraceInformation().
NTSYSAPI NTSTATUS NTAPI RtlInitUnicodeStringEx (PUNICODE_STRING DestinationString, PCWSTR SourceString)
Referenced by RtlAppendUnicodeToString().
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTable (PRTL_GENERIC_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTableAvl (PRTL_AVL_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTableFull (PRTL_GENERIC_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL, PVOID NodeOrParent, TABLE_SEARCH_RESULT SearchResult)
NTSYSAPI PVOID NTAPI RtlInsertElementGenericTableFullAvl (PRTL_AVL_TABLE Table, PVOID Buffer, CLONG BufferSize, PBOOLEAN NewElement OPTIONAL, PVOID NodeOrParent, TABLE_SEARCH_RESULT SearchResult)
NTSYSAPI BOOLEAN NTAPI RtlInsertUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, PUNICODE_STRING Prefix, PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
NTSYSAPI NTSTATUS NTAPI RtlInt64ToUnicodeString (IN ULONGLONG Value, IN ULONG Base OPTIONAL, IN OUT PUNICODE_STRING String)
Definition at line 621 of file cnvint.c.
References _STRING::Buffer, FALSE, _STRING::Length, _STRING::MaximumLength, NT_SUCCESS, _LARGE_INTEGER::QuadPart, RTL_PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlLargeIntegerToChar(), Status, and strlen().
NTSYSAPI NTSTATUS NTAPI RtlIntegerToChar (ULONG Value, ULONG Base, LONG OutputLength, PSZ String)
Referenced by CmpInitializeRegistryNode().
NTSYSAPI NTSTATUS NTAPI RtlIntegerToUnicode (IN ULONG Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
Definition at line 344 of file cnvint.c.
References except, EXCEPTION_EXECUTE_HANDLER, RTL_PAGED_CODE, RtlCopyMemory, RtlpIntegerWChars, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlConvertSidToUnicodeString().
NTSYSAPI NTSTATUS NTAPI RtlIntegerToUnicodeString (ULONG Value, ULONG Base, PUNICODE_STRING String)
Referenced by ExpValidateLocale().
NTSYSAPI PSLIST_ENTRY NTAPI RtlInterlockedFlushSList (IN PSLIST_HEADER ListHead)
NTSYSAPI PSLIST_ENTRY NTAPI RtlInterlockedPopEntrySList (IN PSLIST_HEADER ListHead)
NTSYSAPI PSLIST_ENTRY NTAPI RtlInterlockedPushEntrySList (IN PSLIST_HEADER ListHead, IN PSLIST_ENTRY ListEntry)
PSLIST_ENTRY FASTCALL RtlInterlockedPushListSList (IN PSLIST_HEADER ListHead, IN PSLIST_ENTRY List, IN PSLIST_ENTRY ListEnd, IN ULONG Count)
ULONG FASTCALL RtlInterlockedSetClearBits (IN OUT PULONG Flags, IN ULONG sFlag, IN ULONG cFlag)
Definition at line 24 of file intbits.c.
References InterlockedCompareExchange().
NTSYSAPI NTSTATUS NTAPI RtlInvertRangeList (OUT PRTL_RANGE_LIST InvertedRangeList, IN PRTL_RANGE_LIST RangeList)
NTSYSAPI PSTR NTAPI RtlIpv4AddressToStringA (__in const struct in_addr * Addr, __out_ecount(16) PSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv4AddressToStringExA (__in const struct in_addr * Address, __in USHORT Port, __out_ecount_part *,*AddressStringLength PSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI NTSTATUS NTAPI RtlIpv4AddressToStringExW (__in const struct in_addr * Address, __in USHORT Port, __out_ecount_part *,*AddressStringLength PWSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI PWSTR NTAPI RtlIpv4AddressToStringW (__in const struct in_addr * Addr, __out_ecount(16) PWSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressA (IN PCSTR S, IN BOOLEAN Strict, OUT PCSTR * Terminator, OUT struct in_addr * Addr)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressExA (IN PCSTR AddressString, IN BOOLEAN Strict, OUT struct in_addr * Address, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressExW (IN PCWSTR AddressString, IN BOOLEAN Strict, OUT struct in_addr * Address, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv4StringToAddressW (IN PCWSTR S, IN BOOLEAN Strict, OUT LPCWSTR * Terminator, OUT struct in_addr * Addr)
NTSYSAPI PSTR NTAPI RtlIpv6AddressToStringA (__in const struct in6_addr * Addr, __out_ecount(65) PSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv6AddressToStringExA (__in const struct in6_addr * Address, __in ULONG ScopeId, __in USHORT Port, __out_ecount_part *,*AddressStringLength PSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI NTSTATUS NTAPI RtlIpv6AddressToStringExW (__in const struct in6_addr * Address, __in ULONG ScopeId, __in USHORT Port, __out_ecount_part *,*AddressStringLength PWSTR AddressString, __inout PULONG AddressStringLength)
NTSYSAPI PWSTR NTAPI RtlIpv6AddressToStringW (__in const struct in6_addr * Addr, __out_ecount(65) PWSTR S)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressA (IN PCSTR S, OUT PCSTR * Terminator, OUT struct in6_addr * Addr)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressExA (IN PCSTR AddressString, OUT struct in6_addr * Address, OUT PULONG ScopeId, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressExW (IN PCWSTR AddressString, OUT struct in6_addr * Address, OUT PULONG ScopeId, OUT PUSHORT Port)
NTSYSAPI NTSTATUS NTAPI RtlIpv6StringToAddressW (IN PCWSTR S, OUT PCWSTR * Terminator, OUT struct in6_addr * Addr)
NTSYSAPI BOOLEAN NTAPI RtlIsGenericTableEmpty (PRTL_GENERIC_TABLE Table)
NTSYSAPI BOOLEAN NTAPI RtlIsGenericTableEmptyAvl (PRTL_AVL_TABLE Table)
NTSYSAPI BOOLEAN NTAPI RtlIsNameLegalDOS8Dot3 (IN PUNICODE_STRING Name, IN OUT POEM_STRING OemName OPTIONAL, IN OUT PBOOLEAN NameContainsSpaces OPTIONAL)
NTSYSAPI NTSTATUS NTAPI RtlIsRangeAvailable (IN PRTL_RANGE_LIST RangeList, IN ULONGLONG Start, IN ULONGLONG End, IN ULONG Flags, IN UCHAR AttributeAvailableMask, IN PVOID Context OPTIONAL, IN PRTL_CONFLICT_RANGE_CALLBACK Callback OPTIONAL, OUT PBOOLEAN Available)
NTSYSAPI BOOLEAN NTAPI RtlIsTextUnicode (IN CONST VOID * Buffer, IN ULONG Size, IN OUT PULONG Result OPTIONAL)
BOOLEAN RtlIsValidOemCharacter (__inout PWCHAR Char)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerAdd (LARGE_INTEGER Addend1, LARGE_INTEGER Addend2)
Definition at line 4725 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerArithmeticShift (LARGE_INTEGER LargeInteger, CCHAR ShiftCount)
Definition at line 5090 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
DECLSPEC_DEPRECATED_DDK NTSYSAPI LARGE_INTEGER NTAPI RtlLargeIntegerDivide (LARGE_INTEGER Dividend, LARGE_INTEGER Divisor, PLARGE_INTEGER Remainder)
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerNegate (LARGE_INTEGER Subtrahend)
Definition at line 4806 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerShiftLeft (LARGE_INTEGER LargeInteger, CCHAR ShiftCount)
Definition at line 5060 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerShiftRight (LARGE_INTEGER LargeInteger, CCHAR ShiftCount)
Definition at line 5075 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
DECLSPEC_DEPRECATED_DDK __inline LARGE_INTEGER NTAPI RtlLargeIntegerSubtract (LARGE_INTEGER Minuend, LARGE_INTEGER Subtrahend)
Definition at line 4824 of file ntrtl.h.
References _LARGE_INTEGER::QuadPart.
NTSYSAPI NTSTATUS NTAPI RtlLargeIntegerToChar (PLARGE_INTEGER Value, ULONG Base OPTIONAL, LONG OutputLength, PSZ String)
NTSYSAPI NTSTATUS NTAPI RtlLargeIntegerToUnicode (IN PLARGE_INTEGER Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
Definition at line 535 of file cnvint.c.
References MAX_DIGITS, RTL_PAGED_CODE, RtlpIntegerWChars, and STATUS_INVALID_PARAMETER.
Referenced by RtlConvertSidToUnicodeString().
NTSYSAPI ULONG NTAPI RtlLengthRequiredSid (ULONG SubAuthorityCount)
Referenced by CmpHiveRootSecurityDescriptor(), NtQueryQuotaInformationFile(), SeCaptureSecurityDescriptor(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SepCreateToken(), and SepVariableInitialization().
NTSYSAPI ULONG NTAPI RtlLengthSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor)
Referenced by CmpAssignSecurityDescriptor(), CmpFindMatchingDescriptorCell(), CmpSetSecurityDescriptorInfo(), ObLogSecurityDescriptor(), ObpCompareSecurityDescriptors(), ObpCreateCacheEntry(), and WmipSaveGuidSecurityDescriptor().
NTSYSAPI ULONG NTAPI RtlLengthSid (PSID Sid)
Referenced by ExpKeyedEventInitialization(), IoCheckQuotaBufferValidity(), IopCheckGetQuotaBufferValidity(), MiCreateMemoryEvent(), NtCreatePagingFile(), ObInitSystem(), ObpGetDosDevicesProtection(), RtlpSysVolCreateSecurityDescriptor(), and SeCaptureSidAndAttributesArray().
NTSYSAPI NTSTATUS NTAPI RtlLengthSidAsUnicodeString (PSID Sid, PULONG StringLength)
Definition at line 1393 of file sertl.c.
References _SID::IdentifierAuthority, RTL_PAGED_CODE, RtlValidSid(), STATUS_INVALID_SID, STATUS_SUCCESS, _SID::SubAuthorityCount, TRUE, and _SID_IDENTIFIER_AUTHORITY::Value.
Referenced by RtlFormatCurrentUserKeyPath().
NTSYSAPI NTSTATUS NTAPI RtlLocalTimeToSystemTime (IN PLARGE_INTEGER LocalTime, OUT PLARGE_INTEGER SystemTime)
Definition at line 1343 of file time.c.
References NT_SUCCESS, NULL, _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, SystemTimeOfDayInformation, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneBias, and ZwQuerySystemInformation().
NTSYSAPI NTSTATUS NTAPI RtlLockBootStatusData (OUT PHANDLE BootStatusDataHandle)
NTSYSAPI USHORT NTAPI RtlLogStackBackTrace (VOID)
Definition at line 496 of file stktrace.c.
References RtlpLogStackBackTraceEx().
Referenced by ExInitializeResourceLite(), ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
NTSYSAPI NTSTATUS NTAPI RtlLookupAtomInAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __out_opt PRTL_ATOM Atom)
Definition at line 678 of file atom.c.
References ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::HandleIndex, NULL, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_PAGED_CODE, RtlpAtomMapAtomToHandleEntry(), RtlpGetIntegerAtom(), RtlpHashStringToAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_INVALID, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtFindAtom().
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTable (PRTL_GENERIC_TABLE Table, PVOID Buffer)
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTableAvl (PRTL_AVL_TABLE Table, PVOID Buffer)
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTableFull (PRTL_GENERIC_TABLE Table, PVOID Buffer, OUT PVOID * NodeOrParent, OUT TABLE_SEARCH_RESULT * SearchResult)
Definition at line 659 of file gentable.c.
References FindNodeOrParent(), NULL, RtlSplay(), TableEmptyTree, TableFoundNode, and _RTL_GENERIC_TABLE::TableRoot.
Referenced by RtlLookupElementGenericTable().
NTSYSAPI PVOID NTAPI RtlLookupElementGenericTableFullAvl (PRTL_AVL_TABLE Table, PVOID Buffer, OUT PVOID * NodeOrParent, OUT TABLE_SEARCH_RESULT * SearchResult)
Definition at line 1534 of file avltable.c.
References FindNodeOrParent(), NULL, and TableFoundNode.
Referenced by RtlLookupElementGenericTableAvl().
NTSYSAPI NTSTATUS NTAPI RtlMakeSelfRelativeSD (__in PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __out_bcount *BufferLength PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
Definition at line 193 of file rtlassig.c.
References _SECURITY_DESCRIPTOR_RELATIVE::Dacl, FIELD_OFFSET, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR_RELATIVE::Owner, RTL_PAGED_CODE, RtlCopyMemory, RtlPointerToOffset, RtlpQuerySecurityDescriptor(), RtlpSetControlBits, RtlZeroMemory, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_SELF_RELATIVE, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by RtlAbsoluteToSelfRelativeSD(), and RtlpSysVolCheckOwnerAndSecurity().
VOID RtlMakeStackTraceDataPresent (VOID)
Definition at line 270 of file imagedir.c.
References CONTAINING_RECORD, except, EXCEPTION_EXECUTE_HANDLER, _LIST_ENTRY::Flink, NOTHING, NtCurrentPeb, PROBE_ALIGNMENT, ProbeForReadSmallStructure, RTL_PAGED_CODE, RtlpMakeStackTraceDataPresentForImage(), and UNALIGNED.
NTSYSAPI VOID NTAPI RtlMapGenericMask (PACCESS_MASK AccessMask, PGENERIC_MAPPING GenericMapping)
Referenced by IoCheckDesiredAccess(), IopParseDevice(), ObDuplicateObject(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), SeCreateAccessStateEx(), SeOpenObjectAuditAlarm(), and SeOpenObjectForDeleteAuditAlarm().
NTSYSAPI NTSTATUS NTAPI RtlMapSecurityErrorToNtStatus (SECURITY_STATUS Error)
NTSYSAPI NTSTATUS NTAPI RtlMergeRangeLists (OUT PRTL_RANGE_LIST MergedRangeList, IN PRTL_RANGE_LIST RangeList1, IN PRTL_RANGE_LIST RangeList2, IN ULONG Flags)
NTSYSAPI NTSTATUS NTAPI RtlMultiByteToUnicodeN (__out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWCH UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString, __in_bcount(BytesInMultiByteString) PCSTR MultiByteString, __in ULONG BytesInMultiByteString)
Definition at line 365 of file nlsxlat.c.
References ARGUMENT_PRESENT, NlsAnsiToUnicodeData, NlsLeadByteInfo, NlsMbAnsiCodePageTables, NlsMbCodePageTag, RTL_PAGED_CODE, STATUS_SUCCESS, and UnicodeNull.
Referenced by RtlAnsiCharToUnicodeChar(), RtlAnsiStringToUnicodeString(), and RtlConsoleMultiByteToUnicodeN().
NTSYSAPI NTSTATUS NTAPI RtlMultiByteToUnicodeSize (PULONG BytesInUnicodeString, PCSTR MultiByteString, ULONG BytesInMultiByteString)
Referenced by RtlxAnsiStringToUnicodeSize(), and RtlxOemStringToUnicodeSize().
NTSYSAPI NTSTATUS NTAPI RtlNewSecurityGrantedAccess (ACCESS_MASK DesiredAccess, PPRIVILEGE_SET Privileges, PULONG Length, HANDLE Token, PGENERIC_MAPPING GenericMapping, PACCESS_MASK RemainingDesiredAccess)
NTSYSAPI PUNICODE_PREFIX_TABLE_ENTRY NTAPI RtlNextUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, BOOLEAN Restart)
NTSYSAPI PRTL_USER_PROCESS_PARAMETERS NTAPI RtlNormalizeProcessParams (PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
NTSYSAPI ULONG NTAPI RtlNtStatusToDosError (NTSTATUS Status)
Referenced by WmipStartGlobalLogger().
NTSYSAPI ULONG NTAPI RtlNtStatusToDosErrorNoTeb (NTSTATUS Status)
NTSYSAPI ULONG NTAPI RtlNumberGenericTableElements (PRTL_GENERIC_TABLE Table)
NTSYSAPI ULONG NTAPI RtlNumberGenericTableElementsAvl (PRTL_AVL_TABLE Table)
NTSYSAPI ULONG NTAPI RtlNumberOfClearBits (PRTL_BITMAP BitMapHeader)
NTSYSAPI ULONG NTAPI RtlNumberOfSetBits (PRTL_BITMAP BitMapHeader)
Referenced by CmpLoadHiveThread(), HvFreeHivePartial(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpDelistBinFreeCells(), HvpDoWriteHive(), HvpGrowLog1(), HvpGrowLog2(), HvpRecoverData(), HvpRemoveFreeCellHint(), HvpWriteLog(), and HvRefreshHive().
NTSYSAPI NTSTATUS NTAPI RtlOemStringToCountedUnicodeString (PUNICODE_STRING DestinationString, PCOEM_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlOemStringToUnicodeString (PUNICODE_STRING DestinationString, PCOEM_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlOemToUnicodeN (__out_bcount_part(MaxBytesInUnicodeString,*BytesInUnicodeString) PWSTR UnicodeString, __in ULONG MaxBytesInUnicodeString, __out_opt PULONG BytesInUnicodeString, __in_bcount(BytesInOemString) PCH OemString, __in ULONG BytesInOemString)
Referenced by FsRtlNotifyUpdateBuffer(), RtlOemStringToCountedUnicodeString(), and RtlOemStringToUnicodeString().
NTSYSAPI NTSTATUS NTAPI RtlOpenCurrentUser (IN ULONG DesiredAccess, OUT PHANDLE CurrentUserKey)
Definition at line 1532 of file regutil.c.
References InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, RTL_PAGED_CODE, RTL_REGISTRY_USER, RtlFormatCurrentUserKeyPath(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlpRegistryPaths, Status, and ZwOpenKey().
Referenced by ExpGetCurrentUserUILanguage(), ExpSetCurrentUserUILanguage(), and NtSetDefaultLocale().
RTLP_ADD_WITH_CARRY_OUT_UNSIGNED32 (RtlAddWithCarryOutUint , unsigned int)
unsigned long RTLP_ADD_WITH_OVERFLOW_OUT_SIGNED32 (RtlAddWithOverflowOutInt , int)
Definition at line 7970 of file ntrtl.h.
NTSYSAPI PVOID NTAPI RtlPcToFileHeader (PVOID PcValue, PVOID * BaseOfImage)
VOID RtlpGetStackLimits (OUT PULONG_PTR LowLimit, OUT PULONG_PTR HighLimit)
Referenced by IoGetStackLimits(), RtlGetCallersAddress(), and RtlpWalkFrameChain().
__inline PIMAGE_NT_HEADERS NTAPI RtlpImageNtHeader (IN PVOID Base)
Definition at line 4122 of file ntrtl.h.
References _IMAGE_DOS_HEADER::e_lfanew, EXCEPTION_EXECUTE_HANDLER, IMAGE_DOS_SIGNATURE, IMAGE_NT_SIGNATURE, NULL, RTLP_IMAGE_MAX_DOS_HEADER, and _IMAGE_NT_HEADERS::Signature.
NTSYSAPI NTSTATUS NTAPI RtlPinAtomInAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
Definition at line 793 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, NULL, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlpAtomMapAtomToHandleEntry(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlpNtCreateKey (PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG Options, PUNICODE_STRING Provider, PULONG Disposition)
NTSTATUS RtlpNtEnumerateSubKey (HANDLE KeyHandle, PUNICODE_STRING SubKeyName, ULONG Index, PLARGE_INTEGER LastWriteTime)
NTSTATUS RtlpNtMakeTemporaryKey (HANDLE KeyHandle)
NTSTATUS RtlpNtOpenKey (PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG Options)
NTSTATUS RtlpNtQueryValueKey (HANDLE KeyHandle, PULONG KeyValueType, PVOID KeyValue, PULONG KeyValueLength, PLARGE_INTEGER LastWriteTime)
NTSTATUS RtlpNtSetValueKey (HANDLE KeyHandle, ULONG KeyValueType, PVOID KeyValue, ULONG KeyValueLength)
NTSYSAPI VOID FASTCALL RtlPrefetchMemoryNonTemporal (IN PVOID Source, IN SIZE_T Length)
NTSYSAPI BOOLEAN NTAPI RtlPrefixString (const STRING * String1, const STRING * String2, BOOLEAN CaseInSensitive)
Referenced by MiSnapThunk().
NTSYSAPI BOOLEAN NTAPI RtlPrefixUnicodeString (IN PCUNICODE_STRING String1, IN PCUNICODE_STRING String2, IN BOOLEAN CaseInSensitive)
Definition at line 1780 of file nls.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_IN, FALSE, NLS_UPCASE, RTL_PAGED_CODE, and TRUE.
Referenced by HalpNextDriveLetter(), IoAssignDriveLetters(), and ObpIsUnsecureName().
NTSYSAPI VOID NTAPI RtlProtectHeap (IN PVOID HeapHandle, IN BOOLEAN MakeReadOnly)
NTSYSAPI NTSTATUS NTAPI RtlQueryAtomInAtomTable (__in PVOID AtomTableHandle, __in RTL_ATOM Atom, __out_opt PULONG AtomUsage, __out_opt PULONG AtomFlags, __inout_bcount_part_opt *,*AtomNameLength PWSTR AtomName, __inout_opt PULONG AtomNameLength)
Definition at line 832 of file atom.c.
References _snwprintf, ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::Name, _RTL_ATOM_TABLE_ENTRY::NameLength, NULL, _RTL_ATOM_TABLE_ENTRY::ReferenceCount, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlCopyMemory, RtlpAtomMapAtomToHandleEntry(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtQueryInformationAtom().
NTSYSAPI NTSTATUS NTAPI RtlQueryAtomsInAtomTable (IN PVOID AtomTableHandle, IN ULONG MaximumNumberOfAtoms, OUT PULONG NumberOfAtoms, OUT PRTL_ATOM Atoms)
Definition at line 947 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, _RTL_ATOM_TABLE::Buckets, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::HashLink, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_PAGED_CODE, RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtQueryInformationAtom().
NTSYSAPI USHORT NTAPI RtlQueryDepthSList (IN PSLIST_HEADER ListHead)
NTSYSAPI NTSTATUS NTAPI RtlQueryEnvironmentVariable_U (PVOID Environment, PCUNICODE_STRING Name, PUNICODE_STRING Value)
Referenced by RtlExpandEnvironmentStrings_U().
NTSYSAPI NTSTATUS NTAPI RtlQueryInformationAcl (PACL Acl, PVOID AclInformation, ULONG AclInformationLength, ACL_INFORMATION_CLASS AclInformationClass)
NTSYSAPI NTSTATUS NTAPI RtlQueryRegistryValues (IN ULONG RelativeTo, IN PCWSTR Path, IN PRTL_QUERY_REGISTRY_TABLE QueryTable, IN PVOID Context, IN PVOID Environment OPTIONAL)
Definition at line 706 of file regutil.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DbgPrint(), FALSE, InitializeObjectAttributes, KeyValueFullInformation, KeyValueName, _UNICODE_STRING::Length, MAXIMUM_ALLOWED, _UNICODE_STRING::MaximumLength, _KEY_VALUE_FULL_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::NameLength, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_MULTI_SZ, REG_NONE, RTL_PAGED_CODE, RTL_QUERY_REGISTRY_DELETE, RTL_QUERY_REGISTRY_DIRECT, RTL_QUERY_REGISTRY_NOVALUE, RTL_QUERY_REGISTRY_REQUIRED, RTL_QUERY_REGISTRY_SUBKEY, RTL_QUERY_REGISTRY_TOPKEY, RTL_REGISTRY_HANDLE, RtlInitUnicodeString(), RtlpAllocDeallocQueryBuffer(), RtlpCallQueryRegistryRoutine(), RtlpGetRegistryHandle(), RtlpRegistryQueryInitialBuffersize, Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, STATUS_NO_MORE_ENTRIES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, _KEY_VALUE_FULL_INFORMATION::Type, UNICODE_NULL, ZwClose(), ZwDeleteValueKey(), ZwEnumerateValueKey(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by CmIsLastKnownGoodBoot(), RtlQueryTimeZoneInformation(), RtlSetActiveTimeBias(), WmipGetGuidSecurityDescriptor(), WmipQueryWmiDataBlock(), and WmipStartGlobalLogger().
NTSYSAPI NTSTATUS NTAPI RtlQueryTimeZoneInformation (OUT PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
Definition at line 1625 of file regutil.c.
References _UNICODE_STRING::Buffer, _RTL_QUERY_REGISTRY_TABLE::EntryContext, FALSE, _RTL_QUERY_REGISTRY_TABLE::Flags, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, RTL_PAGED_CODE, RTL_QUERY_REGISTRY_DIRECT, RTL_REGISTRY_HANDLE, RtlpGetTimeZoneInfoHandle(), RtlQueryRegistryValues(), RtlZeroMemory, Status, szBias, szDaylightBias, szDaylightName, szDaylightStart, szStandardBias, szStandardName, szStandardStart, and ZwClose().
Referenced by WmipAddLogHeader().
NTSYSAPI ULONG NTAPI RtlRandom (PULONG Seed)
Referenced by MmCreateProcessAddressSpace().
NTSYSAPI ULONG NTAPI RtlRandomEx (PULONG Seed)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlRealPredecessor (PRTL_SPLAY_LINKS Links)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlRealSuccessor (PRTL_SPLAY_LINKS Links)
Referenced by FsRtlCheckNoExclusiveConflict(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFastUnlockSingleExclusive(), FsRtlGetNextFileLock(), FsRtlPrivateCheckForSharedLockAccess(), FsRtlPrivateFastUnlockAll(), FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), FsRtlSplitLocks(), RtlEnumerateGenericTable(), RtlEnumerateGenericTableWithoutSplaying(), and RtlNextUnicodePrefix().
NTSTATUS RtlRegisterSecureMemoryCacheCallback (IN PRTL_SECURE_MEMORY_CACHE_CALLBACK CallBack)
NTSYSAPI VOID NTAPI RtlReleasePebLock (VOID)
Definition at line 39 of file eballoc.c.
Referenced by RtlCreateEnvironment(), RtlCreateProcessParameters(), RtlQueryEnvironmentVariable_U(), RtlSetCurrentEnvironment(), RtlSetEnvironmentStrings(), and RtlSetEnvironmentVariable().
NTSYSAPI VOID NTAPI RtlReleasePrivilege (PVOID StatePointer)
NTSYSAPI NTSTATUS NTAPI RtlRemoteCall (HANDLE Process, HANDLE Thread, PVOID CallSite, ULONG ArgumentCount, PULONG_PTR Arguments, BOOLEAN PassContext, BOOLEAN AlreadySuspended)
Definition at line 137 of file context.c.
References CONTEXT_FULL, _CONTEXT::ContextFlags, FALSE, Index, NT_SUCCESS, NtGetContextThread(), NtResumeThread(), NtSetContextThread(), NtSuspendThread(), NtWriteVirtualMemory(), NULL, RTL_PAGED_CODE, Status, STATUS_ALERTED, and STATUS_INVALID_PARAMETER.
NTSYSAPI VOID NTAPI RtlRemoveUnicodePrefix (PUNICODE_PREFIX_TABLE PrefixTable, PUNICODE_PREFIX_TABLE_ENTRY PrefixTableEntry)
NTSYSAPI NTSTATUS NTAPI RtlReserveChunk (IN USHORT CompressionFormat, IN OUT PUCHAR * CompressedBuffer, IN PUCHAR EndOfCompressedBufferPlus1, OUT PUCHAR * ChunkBuffer, IN ULONG ChunkSize)
NTSYSAPI VOID NTAPI RtlResetRtlTranslations (PNLSTABLEINFO TableInfo)
Definition at line 2436 of file nlsxlat.c.
References _NLSTABLEINFO::AnsiTableInfo, _CPTABLEINFO::CodePage, DBCS_TBL_SIZE, _CPTABLEINFO::DBCSCodePage, _CPTABLEINFO::DBCSOffsets, _CPTABLEINFO::DefaultChar, FALSE, _NLSTABLEINFO::LowerCaseTable, _CPTABLEINFO::MultiByteTable, Nls844UnicodeLowercaseTable, Nls844UnicodeUpcaseTable, NlsAnsiCodePage, NlsAnsiToUnicodeData, NlsLeadByteInfo, NlsMbAnsiCodePageTables, NlsMbCodePageTag, NlsMbOemCodePageTables, NlsMbOemCodePageTag, NlsOemCodePage, NlsOemLeadByteInfo, NlsOemToUnicodeData, NlsUnicodeToAnsiData, NlsUnicodeToMbAnsiData, NlsUnicodeToMbOemData, NlsUnicodeToOemData, OemDefaultChar, _NLSTABLEINFO::OemTableInfo, OemTransUniDefaultChar, RTL_PAGED_CODE, RtlCopyMemory, RtlZeroMemory, _CPTABLEINFO::TransDefaultChar, TRUE, UnicodeDefaultChar, _CPTABLEINFO::UniDefaultChar, _NLSTABLEINFO::UpperCaseTable, and _CPTABLEINFO::WideCharTable.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTSYSAPI VOID NTAPI RtlRestoreLastWin32Error (LONG Win32Error)
Definition at line 231 of file error.c.
References NtCurrentTeb().
NTSYSAPI VOID NTAPI RtlRunDecodeUnicodeString (UCHAR Seed, PUNICODE_STRING String)
Definition at line 540 of file sertl.c.
References _STRING::Buffer, _STRING::Length, and RTL_PAGED_CODE.
NTSYSAPI VOID NTAPI RtlRunEncodeUnicodeString (PUCHAR Seed OPTIONAL, PUNICODE_STRING String)
Definition at line 409 of file sertl.c.
References ASSERT, _STRING::Buffer, _STRING::Length, NT_SUCCESS, NtQuerySystemTime(), RTL_PAGED_CODE, and Status.
NTSYSAPI VOID NTAPI RtlSecondsSince1970ToTime (ULONG ElapsedSeconds, PLARGE_INTEGER Time)
NTSYSAPI VOID NTAPI RtlSecondsSince1980ToTime (ULONG ElapsedSeconds, PLARGE_INTEGER Time)
NTSYSAPI PIMAGE_SECTION_HEADER NTAPI RtlSectionTableFromVirtualAddress (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID BaseOfImage, IN ULONG VirtualAddress)
Definition at line 40 of file imagedir.c.
References IMAGE_FIRST_SECTION, NULL, _IMAGE_SECTION_HEADER::SizeOfRawData, and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by LdrpAccessResourceDataNoMultipleLanguage(), and RtlAddressInSectionTable().
FORCEINLINE PVOID RtlSecureZeroMemory (IN PVOID ptr, IN SIZE_T cnt)
Definition at line 4275 of file ntrtl.h.
NTSYSAPI NTSTATUS NTAPI RtlSelfRelativeToAbsoluteSD (__in PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __out_bcount_part_opt *,*AbsoluteSecurityDescriptorSize PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __inout PULONG AbsoluteSecurityDescriptorSize, __out_bcount_part_opt *,*DaclSize PACL Dacl, __inout PULONG DaclSize, __out_bcount_part_opt *,*SaclSize PACL Sacl, __inout PULONG SaclSize, __out_bcount_part_opt *,*OwnerSize PSID Owner, __inout PULONG OwnerSize, __out_bcount_part_opt *,*PrimaryGroupSize PSID PrimaryGroup, __inout PULONG PrimaryGroupSize)
Definition at line 32 of file rtlassig.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR::Dacl, _SECURITY_DESCRIPTOR::Group, NULL, _SECURITY_DESCRIPTOR::Owner, RTL_PAGED_CODE, RtlMoveMemory, RtlpAreControlBitsSet, RtlpClearControlBits, RtlpQuerySecurityDescriptor(), _SECURITY_DESCRIPTOR::Sacl, SE_SELF_RELATIVE, SeLengthSid, STATUS_BAD_DESCRIPTOR_FORMAT, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlSelfRelativeToAbsoluteSD2 (__inout_bcount *pBufferSize PSECURITY_DESCRIPTOR pSelfRelativeSecurityDescriptor, __inout PULONG pBufferSize)
Definition at line 469 of file rtlassig.c.
References ASSERT, C_ASSERT, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, _SECURITY_DESCRIPTOR::Dacl, FIELD_OFFSET, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR::Group, _SECURITY_DESCRIPTOR_RELATIVE::Owner, _SECURITY_DESCRIPTOR::Owner, RTL_PAGED_CODE, RtlMoveMemory, RtlpAreControlBitsSet, RtlpClearControlBits, RtlpQuerySecurityDescriptor(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, _SECURITY_DESCRIPTOR::Sacl, SE_SELF_RELATIVE, STATUS_BAD_DESCRIPTOR_FORMAT, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_SUCCESS, ULONG_PTR_SDEND, and ULONG_ROUND_UP.
Referenced by RtlpSysVolCheckOwnerAndSecurity().
NTSYSAPI NTSTATUS NTAPI RtlSetActiveTimeBias (IN LONG ActiveBias)
Definition at line 1780 of file regutil.c.
References _RTL_QUERY_REGISTRY_TABLE::EntryContext, _RTL_QUERY_REGISTRY_TABLE::Flags, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, REG_DWORD, RTL_PAGED_CODE, RTL_QUERY_REGISTRY_DIRECT, RTL_QUERY_REGISTRY_REQUIRED, RTL_REGISTRY_HANDLE, RtlpGetTimeZoneInfoHandle(), RtlQueryRegistryValues(), RtlWriteRegistryValue(), RtlZeroMemory, Status, TRUE, and ZwClose().
NTSYSAPI VOID NTAPI RtlSetAllBits (PRTL_BITMAP BitMapHeader)
Referenced by CmpLoadHiveThread(), CmpOverwriteHive(), MiBuildPagedPool(), MiExtendPagingFileMaximum(), MiInitializeLargePageSupport(), MiInitializeSessionPool(), and NtCreatePagingFile().
NTSYSAPI NTSTATUS NTAPI RtlSetAttributesSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL Control, IN OUT PULONG Revision)
NTSYSAPI VOID NTAPI RtlSetBit (PRTL_BITMAP BitMapHeader, ULONG BitNumber)
Referenced by MiAllocatePoolPages(), MiZeroPageFile(), and MmPerfSnapShotValidPhysicalMemory().
NTSYSAPI VOID NTAPI RtlSetBits (PRTL_BITMAP BitMapHeader, ULONG StartingIndex, ULONG NumberToSet)
Referenced by CmpLoadHiveThread(), HvMarkDirty(), HvpAddFreeCellHint(), MiAttemptPageFileReduction(), MiCheckPteReserve(), MiInsertVadCharges(), MiSessionWideReserveImageAddress(), and MmInitSystem().
NTSYSAPI NTSTATUS NTAPI RtlSetControlSecurityDescriptor (IN PSECURITY_DESCRIPTOR pSecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsOfInterest, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsToSet)
Definition at line 2216 of file sertl.c.
References SE_VALID_CONTROL_BITS, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlSetAttributesSecurityDescriptor().
NTSYSAPI NTSTATUS NTAPI RtlSetCurrentEnvironment (PVOID Environment, PVOID * PreviousEnvironment)
NTSYSAPI NTSTATUS NTAPI RtlSetDaclSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, BOOLEAN DaclPresent, PACL Dacl, BOOLEAN DaclDefaulted)
Referenced by CmpHiveRootSecurityDescriptor(), ExpKeyedEventInitialization(), IopCreateDefaultDeviceSecurityDescriptor(), IopCreateSecurityDescriptorPerType(), MiCreateMemoryEvent(), NtCreatePagingFile(), NtOpenThreadTokenEx(), ObInitSystem(), ObpGetDosDevicesProtection(), RtlpSysVolCheckOwnerAndSecurity(), RtlpSysVolCreateSecurityDescriptor(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), WmipCreateAdminSD(), and WmipInitializeSecurity().
NTSYSAPI NTSTATUS NTAPI RtlSetEnvironmentVariable (PVOID * Environment, PCUNICODE_STRING Name, PCUNICODE_STRING Value)
NTSYSAPI NTSTATUS NTAPI RtlSetGroupSecurityDescriptor (IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID Group OPTIONAL, IN BOOLEAN GroupDefaulted OPTIONAL)
Referenced by SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), and WmipInitializeSecurity().
NTSYSAPI NTSTATUS NTAPI RtlSetInformationAcl (PACL Acl, PVOID AclInformation, ULONG AclInformationLength, ACL_INFORMATION_CLASS AclInformationClass)
NTSYSAPI VOID NTAPI RtlSetLastWin32Error (LONG Win32Error)
Definition at line 218 of file error.c.
References NtCurrentTeb().
Referenced by RtlSetLastWin32ErrorAndNtStatusFromNtStatus().
NTSYSAPI VOID NTAPI RtlSetLastWin32ErrorAndNtStatusFromNtStatus (NTSTATUS Status)
Definition at line 206 of file error.c.
References RtlNtStatusToDosError(), and RtlSetLastWin32Error().
NTSYSAPI NTSTATUS NTAPI RtlSetOwnerSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, PSID Owner, BOOLEAN OwnerDefaulted)
Referenced by RtlpSysVolCheckOwnerAndSecurity(), RtlpSysVolTakeOwnership(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), WmipCreateAdminSD(), and WmipInitializeSecurity().
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetProcessIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
Definition at line 39 of file peb.c.
References ARGUMENT_PRESENT, FALSE, FLG_ENABLE_SYSTEM_CRIT_BREAKS, NtCurrentProcess, NtQueryInformationProcess(), NtSetInformationProcess(), NULL, ProcessBreakOnTermination, RtlGetCurrentPeb(), Status, and STATUS_UNSUCCESSFUL.
NTSYSAPI NTSTATUS NTAPI RtlSetSaclSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, BOOLEAN SaclPresent, PACL Sacl, BOOLEAN SaclDefaulted)
Referenced by ObInitSystem(), and SepInitProcessAuditSd().
NTSYSAPI VOID NTAPI RtlSetSecurityDescriptorRMControl (IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN PUCHAR RMControl OPTIONAL)
Definition at line 10396 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR::Sbz1, and SE_RM_CONTROL_VALID.
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetThreadIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
Definition at line 81 of file peb.c.
References ARGUMENT_PRESENT, FALSE, FLG_ENABLE_SYSTEM_CRIT_BREAKS, NtCurrentThread, NtQueryInformationThread(), NtSetInformationThread(), NULL, RtlGetCurrentPeb(), Status, STATUS_UNSUCCESSFUL, and ThreadBreakOnTermination.
NTSYSAPI NTSTATUS NTAPI RtlSetTimeZoneInformation (IN PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
Definition at line 1693 of file regutil.c.
References NT_SUCCESS, REG_BINARY, REG_DWORD, REG_SZ, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlpGetTimeZoneInfoHandle(), RtlWriteRegistryValue(), Status, szBias, szDaylightBias, szDaylightName, szDaylightStart, szStandardBias, szStandardName, szStandardStart, TRUE, wcslen(), and ZwClose().
FORCEINLINE BOOLEAN RtlSignedAddWithOverflowOut32 (__int32 * pc, __int32 a, __int32 b)
Definition at line 7888 of file ntrtl.h.
FORCEINLINE BOOLEAN RtlSignedAddWithOverflowOut64 (__int64 * pc, __int64 a, __int64 b)
Definition at line 7912 of file ntrtl.h.
NTSYSAPI SIZE_T NTAPI RtlSizeHeap (IN PVOID HeapHandle, IN ULONG Flags, IN PVOID BaseAddress)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlSplay (PRTL_SPLAY_LINKS Links)
Referenced by FsRtlCheckNoExclusiveConflict(), FsRtlCheckNoSharedConflict(), FsRtlPrivateCheckForExclusiveLockAccess(), FsRtlPrivateCheckForSharedLockAccess(), FsRtlPrivateInsertSharedLock(), PfxFindPrefix(), PfxInsertPrefix(), RtlEnumerateGenericTable(), RtlFindUnicodePrefix(), RtlInsertElementGenericTableFull(), RtlInsertUnicodePrefix(), and RtlLookupElementGenericTableFull().
NTSYSAPI NTSTATUS NTAPI RtlStartRXact (IN PRTL_RXACT_CONTEXT RXactContext)
NTSYSAPI NTSTATUS NTAPI RtlStringFromGUID (IN REFGUID Guid, OUT PUNICODE_STRING GuidString)
Definition at line 41 of file guid.c.
References GUID_STRING_SIZE, GuidFormat, RTL_PAGED_CODE, RtlAllocateStringRoutine, STATUS_NO_MEMORY, STATUS_SUCCESS, swprintf, and UNICODE_NULL.
NTSYSAPI PUCHAR NTAPI RtlSubAuthorityCountSid (PSID Sid)
NTSYSAPI PULONG NTAPI RtlSubAuthoritySid (PSID Sid, ULONG SubAuthority)
Referenced by CmpHiveRootSecurityDescriptor(), and SepVariableInitialization().
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlSubtreePredecessor (PRTL_SPLAY_LINKS Links)
NTSYSAPI PRTL_SPLAY_LINKS NTAPI RtlSubtreeSuccessor (PRTL_SPLAY_LINKS Links)
NTSYSAPI NTSTATUS NTAPI RtlSystemTimeToLocalTime (IN PLARGE_INTEGER SystemTime, OUT PLARGE_INTEGER LocalTime)
Definition at line 1315 of file time.c.
References NT_SUCCESS, NULL, _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, SystemTimeOfDayInformation, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneBias, and ZwQuerySystemInformation().
NTSYSAPI BOOLEAN NTAPI RtlTestBit (PRTL_BITMAP BitMapHeader, ULONG BitNumber)
NTSYSAPI BOOLEAN NTAPI RtlTimeFieldsToTime (PTIME_FIELDS TimeFields, PLARGE_INTEGER Time)
Referenced by Phase1InitializationDiscard(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), and SeMakeSystemToken().
NTSYSAPI VOID NTAPI RtlTimeToElapsedTimeFields (IN PLARGE_INTEGER Time, OUT PTIME_FIELDS TimeFields)
Definition at line 974 of file time.c.
References TimeToDaysAndFraction().
NTSYSAPI BOOLEAN NTAPI RtlTimeToSecondsSince1970 (PLARGE_INTEGER Time, PULONG ElapsedSeconds)
NTSYSAPI BOOLEAN NTAPI RtlTimeToSecondsSince1980 (PLARGE_INTEGER Time, PULONG ElapsedSeconds)
NTSYSAPI VOID NTAPI RtlTimeToTimeFields (PLARGE_INTEGER Time, PTIME_FIELDS TimeFields)
Referenced by ExGetNextWakeTime(), IopCopyBootLogRegistryToFile(), and KeSetSystemTime().
BOOLEAN RtlTraceDatabaseAdd (IN PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID * Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
Definition at line 433 of file tracedb.c.
References RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseInternalAdd(), RtlpTraceDatabaseReleaseLock(), and TRACE_ASSERT.
PRTL_TRACE_DATABASE RtlTraceDatabaseCreate (IN ULONG Buckets, IN SIZE_T MaximumSize OPTIONAL, IN ULONG Flags, IN ULONG Tag, IN RTL_TRACE_HASH_FUNCTION HashFunction OPTIONAL)
Definition at line 129 of file tracedb.c.
References _RTL_TRACE_DATABASE::Buckets, _RTL_TRACE_DATABASE::CurrentSize, _RTL_TRACE_SEGMENT::Database, _RTL_TRACE_DATABASE::Flags, _RTL_TRACE_DATABASE::HashCounter, _RTL_TRACE_DATABASE::HashFunction, _RTL_TRACE_SEGMENT::Magic, _RTL_TRACE_DATABASE::Magic, _RTL_TRACE_DATABASE::MaximumSize, _RTL_TRACE_SEGMENT::NextSegment, _RTL_TRACE_DATABASE::NoOfBuckets, _RTL_TRACE_DATABASE::NoOfHits, _RTL_TRACE_DATABASE::NoOfTraces, NULL, _RTL_TRACE_DATABASE::Owner, RTL_TRACE_DATABASE_MAGIC, RTL_TRACE_IN_KERNEL_MODE, RTL_TRACE_SEGMENT_MAGIC, RTL_TRACE_SIZE_INCREMENT, RTL_TRACE_USE_NONPAGED_POOL, RtlpTraceDatabaseAllocate(), RtlpTraceDatabaseFree(), RtlpTraceDatabaseInitializeLock(), RtlpTraceStandardHashFunction(), RtlZeroMemory, _RTL_TRACE_SEGMENT::SegmentEnd, _RTL_TRACE_SEGMENT::SegmentFree, _RTL_TRACE_DATABASE::SegmentList, _RTL_TRACE_SEGMENT::SegmentStart, _RTL_TRACE_DATABASE::Tag, Tag, and _RTL_TRACE_SEGMENT::TotalSize.
BOOLEAN RtlTraceDatabaseDestroy (IN PRTL_TRACE_DATABASE Database)
Definition at line 272 of file tracedb.c.
References DbgPrint(), FALSE, _RTL_TRACE_SEGMENT::NextSegment, NULL, RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseFree(), RtlpTraceDatabaseUninitializeLock(), RtlTraceDatabaseValidate(), TRACE_ASSERT, and TRUE.
BOOLEAN RtlTraceDatabaseEnumerate (PRTL_TRACE_DATABASE Database, OUT PRTL_TRACE_ENUMERATE Enumerate, OUT PRTL_TRACE_BLOCK * TraceBlock)
Definition at line 1212 of file tracedb.c.
References _RTL_TRACE_DATABASE::Buckets, FALSE, _RTL_TRACE_DATABASE::Magic, _RTL_TRACE_DATABASE::NoOfBuckets, NULL, RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseReleaseLock(), TRACE_ASSERT, and TRUE.
BOOLEAN RtlTraceDatabaseFind (PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID * Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
Definition at line 492 of file tracedb.c.
References _RTL_TRACE_DATABASE::Magic, _RTL_TRACE_DATABASE::NoOfHits, RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseInternalFind(), RtlpTraceDatabaseReleaseLock(), and TRACE_ASSERT.
VOID RtlTraceDatabaseLock (IN PRTL_TRACE_DATABASE Database)
Definition at line 1031 of file tracedb.c.
References RtlpTraceDatabaseAcquireLock().
VOID RtlTraceDatabaseUnlock (IN PRTL_TRACE_DATABASE Database)
Definition at line 1064 of file tracedb.c.
References RtlpTraceDatabaseReleaseLock().
BOOLEAN RtlTraceDatabaseValidate (IN PRTL_TRACE_DATABASE Database)
Definition at line 369 of file tracedb.c.
References Index, _RTL_TRACE_SEGMENT::Magic, _RTL_TRACE_BLOCK::Magic, _RTL_TRACE_BLOCK::Next, _RTL_TRACE_SEGMENT::NextSegment, NULL, RTL_TRACE_BLOCK_MAGIC, RTL_TRACE_DATABASE_MAGIC, RTL_TRACE_SEGMENT_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseReleaseLock(), TRACE_ASSERT, and TRUE.
Referenced by RtlTraceDatabaseDestroy().
ULONG FASTCALL RtlUlongByteSwap (IN ULONG Source)
Definition at line 59 of file byteswap.c.
Referenced by RtlIpv4StringToAddressT().
ULONGLONG FASTCALL RtlUlonglongByteSwap (IN ULONGLONG Source)
Definition at line 94 of file byteswap.c.
NTSYSAPI LONG NTAPI RtlUnhandledExceptionFilter (IN struct _EXCEPTION_POINTERS * ExceptionInfo)
NTSYSAPI LONG NTAPI RtlUnhandledExceptionFilter2 (__in struct _EXCEPTION_POINTERS * ExceptionInfo, __in PCSTR Function)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToAnsiString (PANSI_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
Referenced by ExpQueryModuleInformation(), ExpSystemErrorHandler(), IoInitSystem(), IopReassignSystemRoot(), MiLoadUserSymbols(), MiSegmentDelete(), MmGetSystemRoutineAddress(), MmUnloadSystemImage(), ObCreateObjectType(), PerfInfoProcessRunDown(), and WmiTraceProcess().
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToCountedOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToInteger (PCUNICODE_STRING String, ULONG Base, PULONG Value)
Referenced by CmpFindProfileOption(), ExpGetCurrentUserUILanguage(), ExpGetUILanguagePolicy(), and RtlpGetIntegerAtom().
NTSYSAPI NTSTATUS NTAPI RtlUnicodeStringToOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
Referenced by ExpSystemErrorHandler().
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToCustomCPN (__in PCPTABLEINFO CustomCP, __out_bcount_part(MaxBytesInCustomCPString,*BytesInCustomCPString) PCH CustomCPString, __in ULONG MaxBytesInCustomCPString, __out_opt PULONG BytesInCustomCPString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 1925 of file nlsxlat.c.
References ARGUMENT_PRESENT, HIBYTE, LOBYTE, RTL_PAGED_CODE, STATUS_BUFFER_OVERFLOW, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToMultiByteN (__out_bcount_part(MaxBytesInMultiByteString,*BytesInMultiByteString) PCHAR MultiByteString, __in ULONG MaxBytesInMultiByteString, __out_opt PULONG BytesInMultiByteString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 893 of file nlsxlat.c.
References ARGUMENT_PRESENT, HIBYTE, LOBYTE, NlsMbCodePageTag, NlsUnicodeToAnsiData, NlsUnicodeToMbAnsiData, RTL_PAGED_CODE, and STATUS_SUCCESS.
Referenced by RtlUnicodeStringToAnsiString().
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToMultiByteSize (__out PULONG BytesInMultiByteString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 827 of file nlsxlat.c.
References HIBYTE, NlsMbCodePageTag, NlsUnicodeToMbAnsiData, RTL_PAGED_CODE, and STATUS_SUCCESS.
Referenced by RtlxUnicodeStringToAnsiSize(), and RtlxUnicodeStringToOemSize().
NTSYSAPI NTSTATUS NTAPI RtlUnicodeToOemN (__out_bcount_part(MaxBytesInOemString,*BytesInOemString) PCHAR OemString, __in ULONG MaxBytesInOemString, __out_opt PULONG BytesInOemString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 1263 of file nlsxlat.c.
References ARGUMENT_PRESENT, HIBYTE, LOBYTE, NlsMbOemCodePageTag, NlsUnicodeToMbOemData, NlsUnicodeToOemData, RTL_PAGED_CODE, STATUS_BUFFER_OVERFLOW, and STATUS_SUCCESS.
Referenced by RtlUnicodeStringToCountedOemString(), and RtlUnicodeStringToOemString().
NTSYSAPI ULONG NTAPI RtlUniform (PULONG Seed)
NTSYSAPI VOID NTAPI RtlUnlockBootStatusData (IN HANDLE BootStatusDataHandle)
FORCEINLINE BOOLEAN RtlUnsignedAddWithCarryOut32 (unsigned __int32 * pc, unsigned __int32 a, unsigned __int32 b)
Definition at line 7858 of file ntrtl.h.
FORCEINLINE BOOLEAN RtlUnsignedAddWithCarryOut64 (unsigned __int64 * pc, unsigned __int64 a, unsigned __int64 b)
Definition at line 7873 of file ntrtl.h.
NTSYSAPI WCHAR NTAPI RtlUpcaseUnicodeChar (WCHAR SourceCharacter)
Referenced by ObpCreateSymbolicLinkName(), ObpLookupDirectoryEntry(), and RtlpHashStringToAtom().
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeString (PUNICODE_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
Referenced by FsRtlAreNamesEqual(), and FsRtlIsNameInExpression().
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeStringToAnsiString (PANSI_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeStringToCountedOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeStringToOemString (POEM_STRING DestinationString, PCUNICODE_STRING SourceString, BOOLEAN AllocateDestinationString)
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeToCustomCPN (__in PCPTABLEINFO CustomCP, __out_bcount_part(MaxBytesInCustomCPString,*BytesInCustomCPString) PCH CustomCPString, __in ULONG MaxBytesInCustomCPString, __out_opt PULONG BytesInCustomCPString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 2087 of file nlsxlat.c.
References ARGUMENT_PRESENT, HIBYTE, LOBYTE, NLS_UPCASE, RTL_PAGED_CODE, STATUS_BUFFER_OVERFLOW, and STATUS_SUCCESS.
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeToMultiByteN (__out_bcount_part(MaxBytesInMultiByteString,*BytesInMultiByteString) PCHAR MultiByteString, __in ULONG MaxBytesInMultiByteString, __out_opt PULONG BytesInMultiByteString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 1040 of file nlsxlat.c.
References ARGUMENT_PRESENT, HIBYTE, LOBYTE, NLS_UPCASE, NlsAnsiToUnicodeData, NlsLeadByteInfo, NlsMbAnsiCodePageTables, NlsMbCodePageTag, NlsUnicodeToAnsiData, NlsUnicodeToMbAnsiData, RTL_PAGED_CODE, and STATUS_SUCCESS.
Referenced by RtlUpcaseUnicodeStringToAnsiString().
NTSYSAPI NTSTATUS NTAPI RtlUpcaseUnicodeToOemN (__out_bcount_part(MaxBytesInOemString,*BytesInOemString) PCHAR OemString, __in ULONG MaxBytesInOemString, __out_opt PULONG BytesInOemString, __in_bcount(BytesInUnicodeString) PWCH UnicodeString, __in ULONG BytesInUnicodeString)
Definition at line 1418 of file nlsxlat.c.
References ARGUMENT_PRESENT, HIBYTE, LOBYTE, NLS_UPCASE, NlsMbOemCodePageTables, NlsMbOemCodePageTag, NlsOemLeadByteInfo, NlsOemToUnicodeData, NlsUnicodeToMbOemData, NlsUnicodeToOemData, RTL_PAGED_CODE, STATUS_BUFFER_OVERFLOW, and STATUS_SUCCESS.
Referenced by RtlDnsHostNameToComputerName(), RtlUpcaseUnicodeStringToCountedOemString(), and RtlUpcaseUnicodeStringToOemString().
NTSYSAPI CHAR NTAPI RtlUpperChar (CHAR Character)
NTSYSAPI VOID NTAPI RtlUpperString (PSTRING DestinationString, const STRING * SourceString)
USHORT FASTCALL RtlUshortByteSwap (IN USHORT Source)
Definition at line 26 of file byteswap.c.
Referenced by RtlIpv4AddressToStringExT(), RtlIpv4StringToAddressExT(), RtlIpv6AddressToStringExT(), RtlIpv6AddressToStringT(), RtlIpv6StringToAddressExT(), and RtlIpv6StringToAddressT().
NTSYSAPI BOOLEAN NTAPI RtlValidAcl (PACL Acl)
Referenced by RtlpConvertAclToAutoInherit(), RtlValidRelativeSecurityDescriptor(), RtlValidSecurityDescriptor(), SepCheckAcl(), and SeValidSecurityDescriptor().
NTSYSAPI NTSTATUS NTAPI RtlValidateUnicodeString (IN ULONG Flags, IN const UNICODE_STRING * String)
Referenced by SeReportSecurityEvent().
BOOLEAN RtlValidRelativeSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptorInput, IN ULONG SecurityDescriptorLength, IN SECURITY_INFORMATION RequiredInformation)
Definition at line 10066 of file sertl.c.
References _SECURITY_DESCRIPTOR_RELATIVE::Dacl, FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, _SID::Revision, RtlOffsetToPointer, RtlpAreControlBitsSet, RtlpValidateSDOffsetAndSize(), RtlValidAcl(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_DACL_PRESENT, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SID_MAX_SUB_AUTHORITIES, SID_REVISION, _SID::SubAuthorityCount, and TRUE.
NTSYSAPI BOOLEAN NTAPI RtlValidSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor)
Referenced by ObpReferenceSecurityDescriptor().
NTSYSAPI BOOLEAN NTAPI RtlValidSid (PSID Sid)
Referenced by CmpHiveRootSecurityDescriptor(), IoCheckQuotaBufferValidity(), IopCheckGetQuotaBufferValidity(), NtQueryQuotaInformationFile(), RtlAddCompoundAce(), RtlpAddKnownAce(), RtlpAddKnownObjectAce(), SeCaptureSecurityDescriptor(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), and SeReportSecurityEvent().
NTSYSAPI NTSTATUS RtlVerifyVersionInfo (IN PRTL_OSVERSIONINFOEXW VersionInfo, IN ULONG TypeMask, IN ULONGLONG ConditionMask)
NTSYSAPI NTSTATUS NTAPI RtlVolumeDeviceToDosName (IN PVOID VolumeDeviceObject, OUT PUNICODE_STRING DosName)
NTSYSAPI ULONG NTAPI RtlWalkFrameChain (OUT PVOID * Callers, IN ULONG Count, IN ULONG Flags)
Definition at line 544 of file stkwalk.c.
References Count, DISPATCH_LEVEL, except, FALSE, Index, IS_SYSTEM_ADDRESS, KeGetCurrentIrql(), KeGetCurrentThread(), KeIsAttachedProcess(), MmCanThreadFault(), NULL, ProbeForRead, PsGetCurrentThread(), RtlpCaptureStackLimits(), RtlpWalkFrameChain(), RtlpWalkFrameChainExceptionFilter(), _KTHREAD::StackBase, _KTHREAD::Teb, _KTHREAD::TrapFrame, and TRUE.
Referenced by ExpUpdateDebugInfo(), RtlCaptureStackBackTrace(), RtlpCaptureStackTraceForLogging(), SepCreateToken(), SepDuplicateToken(), and SepFilterToken().
NTSYSAPI NTSTATUS NTAPI RtlWriteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength)
Definition at line 1181 of file regutil.c.
References KeyValueName, NT_SUCCESS, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlInitUnicodeString(), RtlpGetRegistryHandle(), Status, TRUE, ZwClose(), and ZwSetValueKey().
Referenced by RtlSetActiveTimeBias(), RtlSetTimeZoneInformation(), WmipSaveGuidSecurityDescriptor(), and WmipStartGlobalLogger().
NTSYSAPI ULONG NTAPI RtlxAnsiStringToUnicodeSize (PCANSI_STRING AnsiString)
NTSYSAPI ULONG NTAPI RtlxOemStringToUnicodeSize (PCOEM_STRING OemString)
NTSYSAPI ULONG NTAPI RtlxUnicodeStringToAnsiSize (PCUNICODE_STRING UnicodeString)
NTSYSAPI ULONG NTAPI RtlxUnicodeStringToOemSize (PCUNICODE_STRING UnicodeString)
NTSYSAPI NTSTATUS NTAPI RtlZeroHeap (IN PVOID HeapHandle, IN ULONG Flags)
NTSYSAPI ULONGLONG NTAPI VerSetConditionMask (IN ULONGLONG ConditionMask, IN ULONG TypeMask, IN UCHAR Condition)
typedef VOID (NTAPI * PRTL_AVL_FREE_ROUTINE)
Variable Documentation
BOOLEAN NLS_MB_CODE_PAGE_TAG
BOOLEAN NLS_MB_OEM_CODE_PAGE_TAG
* PRTL_BACKOFF
Definition at line 7999 of file ntrtl.h.
RTL_BACKOFF
Definition at line 7999 of file ntrtl.h.
Referenced by ExfAcquirePushLockExclusive(), and ExfAcquirePushLockShared().
const PRTL_ALLOCATE_STRING_ROUTINE RtlAllocateStringRoutine
Definition at line 274 of file pool.c.
Referenced by IoInitSystem(), RtlAnsiStringToUnicodeString(), RtlCreateUnicodeString(), RtlDowncaseUnicodeString(), RtlDuplicateUnicodeString(), RtlFormatCurrentUserKeyPath(), RtlOemStringToCountedUnicodeString(), RtlOemStringToUnicodeString(), RtlpQueryRegistryDirect(), RtlStringFromGUID(), RtlUnicodeStringToAnsiString(), RtlUnicodeStringToCountedOemString(), RtlUnicodeStringToOemString(), RtlUpcaseUnicodeString(), RtlUpcaseUnicodeStringToAnsiString(), RtlUpcaseUnicodeStringToCountedOemString(), and RtlUpcaseUnicodeStringToOemString().
const PRTL_FREE_STRING_ROUTINE RtlFreeStringRoutine
Definition at line 275 of file pool.c.
Referenced by RtlAnsiStringToUnicodeString(), RtlFreeAnsiString(), RtlFreeOemString(), RtlFreeUnicodeString(), RtlOemStringToCountedUnicodeString(), RtlOemStringToUnicodeString(), RtlUnicodeStringToAnsiString(), RtlUnicodeStringToCountedOemString(), RtlUnicodeStringToOemString(), RtlUpcaseUnicodeStringToAnsiString(), RtlUpcaseUnicodeStringToCountedOemString(), and RtlUpcaseUnicodeStringToOemString().