Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntioapi.h File Reference
ntioapi.h File Reference
#include <devioctl.h>
Data Structures
struct _FAT_STATISTICS
struct _FILE_ACCESS_INFORMATION
struct _FILE_ALIGNMENT_INFORMATION
struct _FILE_ALL_INFORMATION
struct _FILE_ALLOCATION_INFORMATION
struct _FILE_ATTRIBUTE_TAG_INFORMATION
struct _FILE_BASIC_INFORMATION
struct _FILE_BOTH_DIR_INFORMATION
struct _FILE_COMPLETION_INFORMATION
struct _FILE_COMPRESSION_INFORMATION
struct _FILE_DIRECTORY_INFORMATION
struct _FILE_DISPOSITION_INFORMATION
struct _FILE_EA_INFORMATION
struct _FILE_END_OF_FILE_INFORMATION
struct _FILE_FS_ATTRIBUTE_INFORMATION
struct _FILE_FS_CONTROL_INFORMATION
struct _FILE_FS_DEVICE_INFORMATION
struct _FILE_FS_DRIVER_PATH_INFORMATION
struct _FILE_FS_FULL_SIZE_INFORMATION
struct _FILE_FS_LABEL_INFORMATION
struct _FILE_FS_OBJECTID_INFORMATION
struct _FILE_FS_SIZE_INFORMATION
struct _FILE_FS_VOLUME_INFORMATION
struct _FILE_FULL_DIR_INFORMATION
struct _FILE_FULL_EA_INFORMATION
struct _FILE_GET_EA_INFORMATION
struct _FILE_GET_QUOTA_INFORMATION
struct _FILE_ID_BOTH_DIR_INFORMATION
struct _FILE_ID_FULL_DIR_INFORMATION
struct _FILE_INTERNAL_INFORMATION
struct _FILE_LINK_INFORMATION
struct _FILE_MAILSLOT_PEEK_BUFFER
struct _FILE_MAILSLOT_QUERY_INFORMATION
struct _FILE_MAILSLOT_SET_INFORMATION
struct _FILE_MODE_INFORMATION
struct _FILE_MOVE_CLUSTER_INFORMATION
struct _FILE_NAME_INFORMATION
struct _FILE_NAMES_INFORMATION
struct _FILE_NETWORK_OPEN_INFORMATION
struct _FILE_NOTIFY_INFORMATION
struct _FILE_OBJECTID_INFORMATION
struct _FILE_PIPE_ASSIGN_EVENT_BUFFER
struct _FILE_PIPE_CLIENT_PROCESS_BUFFER
struct _FILE_PIPE_CLIENT_PROCESS_BUFFER_EX
struct _FILE_PIPE_EVENT_BUFFER
struct _FILE_PIPE_INFORMATION
struct _FILE_PIPE_LOCAL_INFORMATION
struct _FILE_PIPE_PEEK_BUFFER
struct _FILE_PIPE_REMOTE_INFORMATION
struct _FILE_PIPE_WAIT_FOR_BUFFER
struct _FILE_POSITION_INFORMATION
struct _FILE_PREFETCH
struct _FILE_QUOTA_INFORMATION
struct _FILE_RENAME_INFORMATION
struct _FILE_REPARSE_POINT_INFORMATION
union _FILE_SEGMENT_ELEMENT
struct _FILE_STANDARD_INFORMATION
struct _FILE_STREAM_INFORMATION
struct _FILE_TRACKING_INFORMATION
struct _FILE_VALID_DATA_LENGTH_INFORMATION
struct _FILESYSTEM_STATISTICS
struct _FSCTL_QUERY_FAT_BPB_BUFFER
struct _IO_COMPLETION_BASIC_INFORMATION
struct _IO_STATUS_BLOCK
struct _LINK_TRACKING_INFORMATION
struct _NTFS_STATISTICS
struct _PATHNAME_BUFFER
struct _REMOTE_LINK_TRACKING_INFORMATION_
struct _REPARSE_DATA_BUFFER
struct _REPARSE_GUID_DATA_BUFFER
struct _REPARSE_POINT_INFORMATION
Macros
#define _FILESYSTEMFSCTL_
#define ANSI_DOS_DOT ('"')
#define ANSI_DOS_QM ('>')
#define ANSI_DOS_STAR ('<')
#define DOS_DOT (L'"')
#define DOS_QM (L'>')
#define DOS_STAR (L'<')
#define FILE_128_BYTE_ALIGNMENT 0x0000007f
#define FILE_256_BYTE_ALIGNMENT 0x000000ff
#define FILE_32_BYTE_ALIGNMENT 0x0000001f
#define FILE_512_BYTE_ALIGNMENT 0x000001ff
#define FILE_64_BYTE_ALIGNMENT 0x0000003f
#define FILE_ACTION_ADDED 0x00000001
#define FILE_ACTION_ADDED_STREAM 0x00000006
#define FILE_ACTION_ID_NOT_TUNNELLED 0x0000000A
#define FILE_ACTION_MODIFIED 0x00000003
#define FILE_ACTION_MODIFIED_STREAM 0x00000008
#define FILE_ACTION_REMOVED 0x00000002
#define FILE_ACTION_REMOVED_BY_DELETE 0x00000009
#define FILE_ACTION_REMOVED_STREAM 0x00000007
#define FILE_ACTION_RENAMED_NEW_NAME 0x00000005
#define FILE_ACTION_RENAMED_OLD_NAME 0x00000004
#define FILE_ACTION_TUNNELLED_ID_COLLISION 0x0000000B
#define FILE_ADD_FILE (0x0002)
#define FILE_ADD_SUBDIRECTORY (0x0004)
#define FILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)
#define FILE_APPEND_DATA (0x0004)
#define FILE_ATTRIBUTE_ARCHIVE 0x00000020
#define FILE_ATTRIBUTE_COMPRESSED 0x00000800
#define FILE_ATTRIBUTE_DEVICE 0x00000040
#define FILE_ATTRIBUTE_DIRECTORY 0x00000010
#define FILE_ATTRIBUTE_ENCRYPTED 0x00004000
#define FILE_ATTRIBUTE_HIDDEN 0x00000002
#define FILE_ATTRIBUTE_NORMAL 0x00000080
#define FILE_ATTRIBUTE_NOT_CONTENT_INDEXED 0x00002000
#define FILE_ATTRIBUTE_OFFLINE 0x00001000
#define FILE_ATTRIBUTE_READONLY 0x00000001
#define FILE_ATTRIBUTE_REPARSE_POINT 0x00000400
#define FILE_ATTRIBUTE_SPARSE_FILE 0x00000200
#define FILE_ATTRIBUTE_SYSTEM 0x00000004
#define FILE_ATTRIBUTE_TEMPORARY 0x00000100
#define FILE_ATTRIBUTE_VALID_FLAGS 0x00007fb7
#define FILE_ATTRIBUTE_VALID_SET_FLAGS 0x000031a7
#define FILE_AUTOGENERATED_DEVICE_NAME 0x00000080
#define FILE_BYTE_ALIGNMENT 0x00000000
#define FILE_CASE_PRESERVED_NAMES 0x00000002
#define FILE_CASE_SENSITIVE_SEARCH 0x00000001
#define FILE_CHARACTERISTIC_PNP_DEVICE 0x00000800
#define FILE_CHARACTERISTICS_EXPECT_ORDERLY_REMOVAL 0x00000200
#define FILE_CHARACTERISTICS_EXPECT_SURPRISE_REMOVAL 0x00000300
#define FILE_CHARACTERISTICS_PROPAGATED
#define FILE_CHARACTERISTICS_REMOVAL_POLICY_MASK 0x00000300
#define FILE_COMPLETE_IF_OPLOCKED 0x00000100
#define FILE_COPY_STRUCTURED_STORAGE 0x00000041
#define FILE_CREATE 0x00000002
#define FILE_CREATE_PIPE_INSTANCE (0x0004)
#define FILE_CREATE_TREE_CONNECTION 0x00000080
#define FILE_CREATED 0x00000002
#define FILE_DELETE_CHILD (0x0040)
#define FILE_DELETE_ON_CLOSE 0x00001000
#define FILE_DEVICE_IS_MOUNTED 0x00000020
#define FILE_DEVICE_SECURE_OPEN 0x00000100
#define FILE_DIRECTORY_FILE 0x00000001
#define FILE_DOES_NOT_EXIST 0x00000005
#define FILE_EA_TYPE_ASCII 0xfffd
#define FILE_EA_TYPE_ASN1 0xffdd
#define FILE_EA_TYPE_BINARY 0xfffe
#define FILE_EA_TYPE_BITMAP 0xfffb
#define FILE_EA_TYPE_EA 0xffee
#define FILE_EA_TYPE_FAMILY_IDS 0xff01
#define FILE_EA_TYPE_ICON 0xfff9
#define FILE_EA_TYPE_METAFILE 0xfffa
#define FILE_EA_TYPE_MVMT 0xffdf
#define FILE_EA_TYPE_MVST 0xffde
#define FILE_EXECUTE (0x0020)
#define FILE_EXISTS 0x00000004
#define FILE_FILE_COMPRESSION 0x00000010
#define FILE_FLOPPY_DISKETTE 0x00000004
#define FILE_GENERIC_EXECUTE
#define FILE_GENERIC_READ
#define FILE_GENERIC_WRITE
#define FILE_LIST_DIRECTORY (0x0001)
#define FILE_LONG_ALIGNMENT 0x00000003
#define FILE_MAXIMUM_DISPOSITION 0x00000005
#define FILE_NAMED_STREAMS 0x00040000
#define FILE_NEED_EA 0x00000080
#define FILE_NO_COMPRESSION 0x00008000
#define FILE_NO_EA_KNOWLEDGE 0x00000200
#define FILE_NO_INTERMEDIATE_BUFFERING 0x00000008
#define FILE_NON_DIRECTORY_FILE 0x00000040
#define FILE_NOTIFY_CHANGE_ATTRIBUTES 0x00000004
#define FILE_NOTIFY_CHANGE_CREATION 0x00000040
#define FILE_NOTIFY_CHANGE_DIR_NAME 0x00000002
#define FILE_NOTIFY_CHANGE_EA 0x00000080
#define FILE_NOTIFY_CHANGE_FILE_NAME 0x00000001
#define FILE_NOTIFY_CHANGE_LAST_ACCESS 0x00000020
#define FILE_NOTIFY_CHANGE_LAST_WRITE 0x00000010
#define FILE_NOTIFY_CHANGE_NAME 0x00000003
#define FILE_NOTIFY_CHANGE_SECURITY 0x00000100
#define FILE_NOTIFY_CHANGE_SIZE 0x00000008
#define FILE_NOTIFY_CHANGE_STREAM_NAME 0x00000200
#define FILE_NOTIFY_CHANGE_STREAM_SIZE 0x00000400
#define FILE_NOTIFY_CHANGE_STREAM_WRITE 0x00000800
#define FILE_NOTIFY_VALID_MASK 0x00000fff
#define FILE_OCTA_ALIGNMENT 0x0000000f
#define FILE_OPBATCH_BREAK_UNDERWAY 0x00000009
#define FILE_OPEN 0x00000001
#define FILE_OPEN_BY_FILE_ID 0x00002000
#define FILE_OPEN_FOR_BACKUP_INTENT 0x00004000
#define FILE_OPEN_FOR_FREE_SPACE_QUERY 0x00800000
#define FILE_OPEN_FOR_RECOVERY 0x00000400
#define FILE_OPEN_IF 0x00000003
#define FILE_OPEN_NO_RECALL 0x00400000
#define FILE_OPEN_REPARSE_POINT 0x00200000
#define FILE_OPENED 0x00000001
#define FILE_OPLOCK_BROKEN_TO_LEVEL_2 0x00000007
#define FILE_OPLOCK_BROKEN_TO_NONE 0x00000008
#define FILE_OVERWRITE 0x00000004
#define FILE_OVERWRITE_IF 0x00000005
#define FILE_OVERWRITTEN 0x00000003
#define FILE_PERSISTENT_ACLS 0x00000008
#define FILE_PIPE_BYTE_STREAM_MODE 0x00000000
#define FILE_PIPE_BYTE_STREAM_TYPE 0x00000000
#define FILE_PIPE_CLIENT_END 0x00000000
#define FILE_PIPE_CLOSING_STATE 0x00000004
#define FILE_PIPE_COMPLETE_OPERATION 0x00000001
#define FILE_PIPE_COMPUTER_NAME_LENGTH 15
#define FILE_PIPE_CONNECTED_STATE 0x00000003
#define FILE_PIPE_DISCONNECTED_STATE 0x00000001
#define FILE_PIPE_FULL_DUPLEX 0x00000002
#define FILE_PIPE_INBOUND 0x00000000
#define FILE_PIPE_LISTENING_STATE 0x00000002
#define FILE_PIPE_MESSAGE_MODE 0x00000001
#define FILE_PIPE_MESSAGE_TYPE 0x00000001
#define FILE_PIPE_OUTBOUND 0x00000001
#define FILE_PIPE_QUEUE_OPERATION 0x00000000
#define FILE_PIPE_READ_DATA 0x00000000
#define FILE_PIPE_SERVER_END 0x00000001
#define FILE_PIPE_WRITE_SPACE 0x00000001
#define FILE_PREFETCH_TYPE_FOR_CREATE 0x1
#define FILE_QUAD_ALIGNMENT 0x00000007
#define FILE_RANDOM_ACCESS 0x00000800
#define FILE_READ_ATTRIBUTES (0x0080)
#define FILE_READ_DATA (0x0001)
#define FILE_READ_EA (0x0008)
#define FILE_READ_ONLY_DEVICE 0x00000002
#define FILE_READ_ONLY_VOLUME 0x00080000
#define FILE_REMOTE_DEVICE 0x00000010
#define FILE_REMOVABLE_MEDIA 0x00000001
#define FILE_RESERVE_OPFILTER 0x00100000
#define FILE_SEQUENTIAL_ONLY 0x00000004
#define FILE_SHARE_DELETE 0x00000004
#define FILE_SHARE_READ 0x00000001
#define FILE_SHARE_VALID_FLAGS 0x00000007
#define FILE_SHARE_WRITE 0x00000002
#define FILE_STRUCTURED_STORAGE 0x00000441
#define FILE_SUPERSEDE 0x00000000
#define FILE_SUPERSEDED 0x00000000
#define FILE_SUPPORTS_ENCRYPTION 0x00020000
#define FILE_SUPPORTS_OBJECT_IDS 0x00010000
#define FILE_SUPPORTS_REMOTE_STORAGE 0x00000100
#define FILE_SUPPORTS_REPARSE_POINTS 0x00000080
#define FILE_SUPPORTS_SPARSE_FILES 0x00000040
#define FILE_SYNCHRONOUS_IO_ALERT 0x00000010
#define FILE_SYNCHRONOUS_IO_NONALERT 0x00000020
#define FILE_TRAVERSE (0x0020)
#define FILE_UNICODE_ON_DISK 0x00000004
#define FILE_USE_FILE_POINTER_POSITION 0xfffffffe
#define FILE_VALID_MAILSLOT_OPTION_FLAGS 0x00000032
#define FILE_VALID_OPTION_FLAGS 0x00ffffff
#define FILE_VALID_PIPE_OPTION_FLAGS 0x00000032
#define FILE_VALID_SET_FLAGS 0x00000036
#define FILE_VC_CONTENT_INDEX_DISABLED 0x00000008
#define FILE_VC_LOG_QUOTA_LIMIT 0x00000020
#define FILE_VC_LOG_QUOTA_THRESHOLD 0x00000010
#define FILE_VC_LOG_VOLUME_LIMIT 0x00000080
#define FILE_VC_LOG_VOLUME_THRESHOLD 0x00000040
#define FILE_VC_QUOTA_ENFORCE 0x00000002
#define FILE_VC_QUOTA_MASK 0x00000003
#define FILE_VC_QUOTA_NONE 0x00000000
#define FILE_VC_QUOTA_TRACK 0x00000001
#define FILE_VC_QUOTAS_INCOMPLETE 0x00000100
#define FILE_VC_QUOTAS_REBUILDING 0x00000200
#define FILE_VC_VALID_MASK 0x000003ff
#define FILE_VIRTUAL_VOLUME 0x00000040
#define FILE_VOLUME_IS_COMPRESSED 0x00008000
#define FILE_VOLUME_QUOTAS 0x00000020
#define FILE_WORD_ALIGNMENT 0x00000001
#define FILE_WRITE_ATTRIBUTES (0x0100)
#define FILE_WRITE_DATA (0x0002)
#define FILE_WRITE_EA (0x0010)
#define FILE_WRITE_ONCE_MEDIA 0x00000008
#define FILE_WRITE_THROUGH 0x00000002
#define FILE_WRITE_TO_END_OF_FILE 0xffffffff
#define FILESYSTEM_STATISTICS_TYPE_FAT 2
#define FILESYSTEM_STATISTICS_TYPE_NTFS 1
#define FSCTL_DISMOUNT_VOLUME CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_FILESYSTEM_GET_STATISTICS CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 24, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_GET_COMPRESSION CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 15, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_INVALIDATE_VOLUMES CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 21, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_IS_PATHNAME_VALID CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 11, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_IS_VOLUME_MOUNTED CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 10, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_LMR_GET_LINK_TRACKING_INFORMATION CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM,58,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define FSCTL_LMR_SET_LINK_TRACKING_INFORMATION CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM,59,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define FSCTL_LOCK_VOLUME CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_MAILSLOT_PEEK CTL_CODE(FILE_DEVICE_MAILSLOT, 0, METHOD_NEITHER, FILE_READ_DATA)
#define FSCTL_MARK_AS_SYSTEM_HIVE CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 19, METHOD_NEITHER, FILE_ANY_ACCESS)
#define FSCTL_MARK_VOLUME_DIRTY CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 12, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_OPBATCH_ACK_CLOSE_PENDING CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_OPLOCK_BREAK_ACK_NO_2 CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 20, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_OPLOCK_BREAK_ACKNOWLEDGE CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_OPLOCK_BREAK_NOTIFY CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_ASSIGN_EVENT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_DISCONNECT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_IMPERSONATE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_INTERNAL_READ CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2045, METHOD_BUFFERED, FILE_READ_DATA)
#define FSCTL_PIPE_INTERNAL_READ_OVFLOW CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2048, METHOD_BUFFERED, FILE_READ_DATA)
#define FSCTL_PIPE_INTERNAL_TRANSCEIVE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2047, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define FSCTL_PIPE_INTERNAL_WRITE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2046, METHOD_BUFFERED, FILE_WRITE_DATA)
#define FSCTL_PIPE_LISTEN CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_PEEK CTL_CODE(FILE_DEVICE_NAMED_PIPE, 3, METHOD_BUFFERED, FILE_READ_DATA)
#define FSCTL_PIPE_QUERY_CLIENT_PROCESS CTL_CODE(FILE_DEVICE_NAMED_PIPE, 9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_QUERY_EVENT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_SET_CLIENT_PROCESS CTL_CODE(FILE_DEVICE_NAMED_PIPE, 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_PIPE_TRANSCEIVE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 5, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define FSCTL_PIPE_WAIT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_QUERY_FAT_BPB CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 22, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_QUERY_RETRIEVAL_POINTERS CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 14, METHOD_NEITHER, FILE_ANY_ACCESS)
#define FSCTL_REQUEST_BATCH_OPLOCK CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_REQUEST_FILTER_OPLOCK CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 23, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_REQUEST_OPLOCK_LEVEL_1 CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_REQUEST_OPLOCK_LEVEL_2 CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_SET_COMPRESSION CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 16, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define FSCTL_UNLOCK_VOLUME CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IO_COMPLETION_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define IO_COMPLETION_MODIFY_STATE 0x0002
#define IO_COMPLETION_QUERY_STATE 0x0001
#define IO_REPARSE_TAG_ARKIVIO (0x0000000CL)
#define IO_REPARSE_TAG_COMMVAULT (0x0000000EL)
#define IO_REPARSE_TAG_DFS (0x8000000AL)
#define IO_REPARSE_TAG_ENIGMA_HSM (0x00000011L)
#define IO_REPARSE_TAG_FILTER_MANAGER (0x8000000BL)
#define IO_REPARSE_TAG_FRS_GHOST (0x80000012L)
#define IO_REPARSE_TAG_HSM (0xC0000004L)
#define IO_REPARSE_TAG_IFSTEST_CONGRUENT (0x00000009L)
#define IO_REPARSE_TAG_INTERCOPE_HSM (0x00000013L)
#define IO_REPARSE_TAG_KOM_NETWORKS_HSM (0x00000014L)
#define IO_REPARSE_TAG_MEMORY_TECH_HSM (0x00000015L)
#define IO_REPARSE_TAG_MOUNT_POINT (0xA0000003L)
#define IO_REPARSE_TAG_OVERTONE (0x0000000FL)
#define IO_REPARSE_TAG_RESERVED_ONE (1)
#define IO_REPARSE_TAG_RESERVED_RANGE IO_REPARSE_TAG_RESERVED_ONE
#define IO_REPARSE_TAG_RESERVED_ZERO (0)
#define IO_REPARSE_TAG_SIS (0x80000007L)
#define IO_REPARSE_TAG_SOLUTIONSOFT (0x2000000DL)
#define IO_REPARSE_TAG_SYMBOLIC_LINK IO_REPARSE_TAG_RESERVED_ZERO
#define IO_REPARSE_TAG_VALID_VALUES (0xF000FFFF)
#define IOCTL_LMR_ARE_FILE_OBJECTS_ON_SAME_SERVER CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM,60,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define IsReparseTagMicrosoft(_tag)
#define IsReparseTagNameSurrogate(_tag)
#define IsReparseTagValid(_tag)
#define MAILSLOT_CLASS_FIRSTCLASS 1
#define MAILSLOT_CLASS_SECONDCLASS 2
#define MAILSLOT_NO_MESSAGE ((ULONG)-1)
#define MAILSLOT_SIZE_AUTO 0
#define MAILSLOT_WAIT_FOREVER ((ULONG)-1)
#define MAXIMUM_FILENAME_LENGTH 256
#define MAXIMUM_REPARSE_DATA_BUFFER_SIZE (16 * 1024)
#define PIO_APC_ROUTINE_DEFINED
#define REPARSE_DATA_BUFFER_HEADER_SIZE FIELD_OFFSET(REPARSE_DATA_BUFFER, GenericReparseBuffer)
#define REPARSE_GUID_DATA_BUFFER_HEADER_SIZE FIELD_OFFSET(REPARSE_GUID_DATA_BUFFER, GenericReparseBuffer)
Typedefs
typedef enum _BUS_DATA_TYPE BUS_DATA_TYPE
typedef enum _DMA_SPEED DMA_SPEED
typedef enum _DMA_WIDTH DMA_WIDTH
typedef struct _FAT_STATISTICS FAT_STATISTICS
typedef struct _FILE_ACCESS_INFORMATION FILE_ACCESS_INFORMATION
typedef struct _FILE_ALIGNMENT_INFORMATION FILE_ALIGNMENT_INFORMATION
typedef struct _FILE_ALL_INFORMATION FILE_ALL_INFORMATION
typedef struct _FILE_ALLOCATION_INFORMATION FILE_ALLOCATION_INFORMATION
typedef struct _FILE_ATTRIBUTE_TAG_INFORMATION FILE_ATTRIBUTE_TAG_INFORMATION
typedef struct _FILE_BASIC_INFORMATION FILE_BASIC_INFORMATION
typedef struct _FILE_BOTH_DIR_INFORMATION FILE_BOTH_DIR_INFORMATION
typedef struct _FILE_COMPLETION_INFORMATION FILE_COMPLETION_INFORMATION
typedef struct _FILE_COMPRESSION_INFORMATION FILE_COMPRESSION_INFORMATION
typedef struct _FILE_DIRECTORY_INFORMATION FILE_DIRECTORY_INFORMATION
typedef struct _FILE_DISPOSITION_INFORMATION FILE_DISPOSITION_INFORMATION
typedef struct _FILE_EA_INFORMATION FILE_EA_INFORMATION
typedef struct _FILE_END_OF_FILE_INFORMATION FILE_END_OF_FILE_INFORMATION
typedef struct _FILE_FS_ATTRIBUTE_INFORMATION FILE_FS_ATTRIBUTE_INFORMATION
typedef struct _FILE_FS_CONTROL_INFORMATION FILE_FS_CONTROL_INFORMATION
typedef struct _FILE_FS_DEVICE_INFORMATION FILE_FS_DEVICE_INFORMATION
typedef struct _FILE_FS_DRIVER_PATH_INFORMATION FILE_FS_DRIVER_PATH_INFORMATION
typedef struct _FILE_FS_FULL_SIZE_INFORMATION FILE_FS_FULL_SIZE_INFORMATION
typedef struct _FILE_FS_LABEL_INFORMATION FILE_FS_LABEL_INFORMATION
typedef struct _FILE_FS_OBJECTID_INFORMATION FILE_FS_OBJECTID_INFORMATION
typedef struct _FILE_FS_SIZE_INFORMATION FILE_FS_SIZE_INFORMATION
typedef struct _FILE_FS_VOLUME_INFORMATION FILE_FS_VOLUME_INFORMATION
typedef struct _FILE_FULL_DIR_INFORMATION FILE_FULL_DIR_INFORMATION
typedef struct _FILE_FULL_EA_INFORMATION FILE_FULL_EA_INFORMATION
typedef struct _FILE_GET_EA_INFORMATION FILE_GET_EA_INFORMATION
typedef struct _FILE_GET_QUOTA_INFORMATION FILE_GET_QUOTA_INFORMATION
typedef struct _FILE_ID_BOTH_DIR_INFORMATION FILE_ID_BOTH_DIR_INFORMATION
typedef struct _FILE_ID_FULL_DIR_INFORMATION FILE_ID_FULL_DIR_INFORMATION
typedef enum _FILE_INFORMATION_CLASS FILE_INFORMATION_CLASS
typedef struct _FILE_INTERNAL_INFORMATION FILE_INTERNAL_INFORMATION
typedef struct _FILE_LINK_INFORMATION FILE_LINK_INFORMATION
typedef struct _FILE_MAILSLOT_PEEK_BUFFER FILE_MAILSLOT_PEEK_BUFFER
typedef struct _FILE_MAILSLOT_QUERY_INFORMATION FILE_MAILSLOT_QUERY_INFORMATION
typedef struct _FILE_MAILSLOT_SET_INFORMATION FILE_MAILSLOT_SET_INFORMATION
typedef struct _FILE_MODE_INFORMATION FILE_MODE_INFORMATION
typedef struct _FILE_MOVE_CLUSTER_INFORMATION FILE_MOVE_CLUSTER_INFORMATION
typedef struct _FILE_NAME_INFORMATION FILE_NAME_INFORMATION
typedef struct _FILE_NAMES_INFORMATION FILE_NAMES_INFORMATION
typedef struct _FILE_NETWORK_OPEN_INFORMATION FILE_NETWORK_OPEN_INFORMATION
typedef struct _FILE_NOTIFY_INFORMATION FILE_NOTIFY_INFORMATION
typedef struct _FILE_OBJECTID_INFORMATION FILE_OBJECTID_INFORMATION
typedef struct _FILE_PIPE_ASSIGN_EVENT_BUFFER FILE_PIPE_ASSIGN_EVENT_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER FILE_PIPE_CLIENT_PROCESS_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER_EX FILE_PIPE_CLIENT_PROCESS_BUFFER_EX
typedef struct _FILE_PIPE_EVENT_BUFFER FILE_PIPE_EVENT_BUFFER
typedef struct _FILE_PIPE_INFORMATION FILE_PIPE_INFORMATION
typedef struct _FILE_PIPE_LOCAL_INFORMATION FILE_PIPE_LOCAL_INFORMATION
typedef struct _FILE_PIPE_PEEK_BUFFER FILE_PIPE_PEEK_BUFFER
typedef struct _FILE_PIPE_REMOTE_INFORMATION FILE_PIPE_REMOTE_INFORMATION
typedef struct _FILE_PIPE_WAIT_FOR_BUFFER FILE_PIPE_WAIT_FOR_BUFFER
typedef struct _FILE_POSITION_INFORMATION FILE_POSITION_INFORMATION
typedef struct _FILE_PREFETCH FILE_PREFETCH
typedef struct _FILE_QUOTA_INFORMATION FILE_QUOTA_INFORMATION
typedef struct _FILE_RENAME_INFORMATION FILE_RENAME_INFORMATION
typedef struct _FILE_REPARSE_POINT_INFORMATION FILE_REPARSE_POINT_INFORMATION
typedef union _FILE_SEGMENT_ELEMENT FILE_SEGMENT_ELEMENT
typedef struct _FILE_STANDARD_INFORMATION FILE_STANDARD_INFORMATION
typedef struct _FILE_STREAM_INFORMATION FILE_STREAM_INFORMATION
typedef struct _FILE_TRACKING_INFORMATION FILE_TRACKING_INFORMATION
typedef struct _FILE_VALID_DATA_LENGTH_INFORMATION FILE_VALID_DATA_LENGTH_INFORMATION
typedef struct _FILESYSTEM_STATISTICS FILESYSTEM_STATISTICS
typedef enum _FSINFOCLASS FS_INFORMATION_CLASS
typedef struct _FSCTL_QUERY_FAT_BPB_BUFFER FSCTL_QUERY_FAT_BPB_BUFFER
typedef enum _INTERFACE_TYPE INTERFACE_TYPE
typedef struct _IO_COMPLETION_BASIC_INFORMATION IO_COMPLETION_BASIC_INFORMATION
typedef enum _IO_COMPLETION_INFORMATION_CLASS IO_COMPLETION_INFORMATION_CLASS
typedef struct _IO_STATUS_BLOCK IO_STATUS_BLOCK
typedef IN PIO_STATUS_BLOCK IoStatusBlock
typedef struct _LINK_TRACKING_INFORMATION LINK_TRACKING_INFORMATION
typedef enum _LINK_TRACKING_INFORMATION_TYPE LINK_TRACKING_INFORMATION_TYPE
typedef struct _NTFS_STATISTICS NTFS_STATISTICS
typedef struct _PATHNAME_BUFFER PATHNAME_BUFFER
typedef enum _BUS_DATA_TYPE * PBUS_DATA_TYPE
typedef enum _DMA_SPEED * PDMA_SPEED
typedef enum _DMA_WIDTH * PDMA_WIDTH
typedef struct _FAT_STATISTICS * PFAT_STATISTICS
typedef struct _FILE_ACCESS_INFORMATION * PFILE_ACCESS_INFORMATION
typedef struct _FILE_ALIGNMENT_INFORMATION * PFILE_ALIGNMENT_INFORMATION
typedef struct _FILE_ALL_INFORMATION * PFILE_ALL_INFORMATION
typedef struct _FILE_ALLOCATION_INFORMATION * PFILE_ALLOCATION_INFORMATION
typedef struct _FILE_ATTRIBUTE_TAG_INFORMATION * PFILE_ATTRIBUTE_TAG_INFORMATION
typedef struct _FILE_BASIC_INFORMATION * PFILE_BASIC_INFORMATION
typedef struct _FILE_BOTH_DIR_INFORMATION * PFILE_BOTH_DIR_INFORMATION
typedef struct _FILE_COMPLETION_INFORMATION * PFILE_COMPLETION_INFORMATION
typedef struct _FILE_COMPRESSION_INFORMATION * PFILE_COMPRESSION_INFORMATION
typedef struct _FILE_DIRECTORY_INFORMATION * PFILE_DIRECTORY_INFORMATION
typedef struct _FILE_DISPOSITION_INFORMATION * PFILE_DISPOSITION_INFORMATION
typedef struct _FILE_EA_INFORMATION * PFILE_EA_INFORMATION
typedef struct _FILE_END_OF_FILE_INFORMATION * PFILE_END_OF_FILE_INFORMATION
typedef struct _FILE_FS_ATTRIBUTE_INFORMATION * PFILE_FS_ATTRIBUTE_INFORMATION
typedef struct _FILE_FS_CONTROL_INFORMATION * PFILE_FS_CONTROL_INFORMATION
typedef struct _FILE_FS_DEVICE_INFORMATION * PFILE_FS_DEVICE_INFORMATION
typedef struct _FILE_FS_DRIVER_PATH_INFORMATION * PFILE_FS_DRIVER_PATH_INFORMATION
typedef struct _FILE_FS_FULL_SIZE_INFORMATION * PFILE_FS_FULL_SIZE_INFORMATION
typedef struct _FILE_FS_LABEL_INFORMATION * PFILE_FS_LABEL_INFORMATION
typedef struct _FILE_FS_OBJECTID_INFORMATION * PFILE_FS_OBJECTID_INFORMATION
typedef struct _FILE_FS_SIZE_INFORMATION * PFILE_FS_SIZE_INFORMATION
typedef struct _FILE_FS_VOLUME_INFORMATION * PFILE_FS_VOLUME_INFORMATION
typedef struct _FILE_FULL_DIR_INFORMATION * PFILE_FULL_DIR_INFORMATION
typedef struct _FILE_FULL_EA_INFORMATION * PFILE_FULL_EA_INFORMATION
typedef struct _FILE_GET_EA_INFORMATION * PFILE_GET_EA_INFORMATION
typedef struct _FILE_GET_QUOTA_INFORMATION * PFILE_GET_QUOTA_INFORMATION
typedef struct _FILE_ID_BOTH_DIR_INFORMATION * PFILE_ID_BOTH_DIR_INFORMATION
typedef struct _FILE_ID_FULL_DIR_INFORMATION * PFILE_ID_FULL_DIR_INFORMATION
typedef enum _FILE_INFORMATION_CLASS * PFILE_INFORMATION_CLASS
typedef struct _FILE_INTERNAL_INFORMATION * PFILE_INTERNAL_INFORMATION
typedef struct _FILE_LINK_INFORMATION * PFILE_LINK_INFORMATION
typedef struct _FILE_MAILSLOT_PEEK_BUFFER * PFILE_MAILSLOT_PEEK_BUFFER
typedef struct _FILE_MAILSLOT_QUERY_INFORMATION * PFILE_MAILSLOT_QUERY_INFORMATION
typedef struct _FILE_MAILSLOT_SET_INFORMATION * PFILE_MAILSLOT_SET_INFORMATION
typedef struct _FILE_MODE_INFORMATION * PFILE_MODE_INFORMATION
typedef struct _FILE_MOVE_CLUSTER_INFORMATION * PFILE_MOVE_CLUSTER_INFORMATION
typedef struct _FILE_NAME_INFORMATION * PFILE_NAME_INFORMATION
typedef struct _FILE_NAMES_INFORMATION * PFILE_NAMES_INFORMATION
typedef struct _FILE_NETWORK_OPEN_INFORMATION * PFILE_NETWORK_OPEN_INFORMATION
typedef struct _FILE_NOTIFY_INFORMATION * PFILE_NOTIFY_INFORMATION
typedef struct _FILE_OBJECTID_INFORMATION * PFILE_OBJECTID_INFORMATION
typedef struct _FILE_PIPE_ASSIGN_EVENT_BUFFER * PFILE_PIPE_ASSIGN_EVENT_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER * PFILE_PIPE_CLIENT_PROCESS_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER_EX * PFILE_PIPE_CLIENT_PROCESS_BUFFER_EX
typedef struct _FILE_PIPE_EVENT_BUFFER * PFILE_PIPE_EVENT_BUFFER
typedef struct _FILE_PIPE_INFORMATION * PFILE_PIPE_INFORMATION
typedef struct _FILE_PIPE_LOCAL_INFORMATION * PFILE_PIPE_LOCAL_INFORMATION
typedef struct _FILE_PIPE_PEEK_BUFFER * PFILE_PIPE_PEEK_BUFFER
typedef struct _FILE_PIPE_REMOTE_INFORMATION * PFILE_PIPE_REMOTE_INFORMATION
typedef struct _FILE_PIPE_WAIT_FOR_BUFFER * PFILE_PIPE_WAIT_FOR_BUFFER
typedef struct _FILE_POSITION_INFORMATION * PFILE_POSITION_INFORMATION
typedef struct _FILE_PREFETCH * PFILE_PREFETCH
typedef struct _FILE_QUOTA_INFORMATION * PFILE_QUOTA_INFORMATION
typedef struct _FILE_RENAME_INFORMATION * PFILE_RENAME_INFORMATION
typedef struct _FILE_REPARSE_POINT_INFORMATION * PFILE_REPARSE_POINT_INFORMATION
typedef union _FILE_SEGMENT_ELEMENT * PFILE_SEGMENT_ELEMENT
typedef struct _FILE_STANDARD_INFORMATION * PFILE_STANDARD_INFORMATION
typedef struct _FILE_STREAM_INFORMATION * PFILE_STREAM_INFORMATION
typedef struct _FILE_TRACKING_INFORMATION * PFILE_TRACKING_INFORMATION
typedef struct _FILE_VALID_DATA_LENGTH_INFORMATION * PFILE_VALID_DATA_LENGTH_INFORMATION
typedef struct _FILESYSTEM_STATISTICS * PFILESYSTEM_STATISTICS
typedef enum _FSINFOCLASS * PFS_INFORMATION_CLASS
typedef struct _FSCTL_QUERY_FAT_BPB_BUFFER * PFSCTL_QUERY_FAT_BPB_BUFFER
typedef VOID(* PINTERFACE_DEREFERENCE) (PVOID Context)
typedef VOID(* PINTERFACE_REFERENCE) (PVOID Context)
typedef enum _INTERFACE_TYPE * PINTERFACE_TYPE
typedef struct _IO_COMPLETION_BASIC_INFORMATION * PIO_COMPLETION_BASIC_INFORMATION
typedef struct _IO_STATUS_BLOCK * PIO_STATUS_BLOCK
typedef struct _LINK_TRACKING_INFORMATION * PLINK_TRACKING_INFORMATION
typedef enum _LINK_TRACKING_INFORMATION_TYPE * PLINK_TRACKING_INFORMATION_TYPE
typedef struct _NTFS_STATISTICS * PNTFS_STATISTICS
typedef struct _PATHNAME_BUFFER * PPATHNAME_BUFFER
typedef struct _REMOTE_LINK_TRACKING_INFORMATION_ * PREMOTE_LINK_TRACKING_INFORMATION
typedef struct _REPARSE_DATA_BUFFER * PREPARSE_DATA_BUFFER
typedef struct _REPARSE_GUID_DATA_BUFFER * PREPARSE_GUID_DATA_BUFFER
typedef struct _REPARSE_POINT_INFORMATION * PREPARSE_POINT_INFORMATION
typedef struct _REMOTE_LINK_TRACKING_INFORMATION_ REMOTE_LINK_TRACKING_INFORMATION
typedef struct _REPARSE_DATA_BUFFER REPARSE_DATA_BUFFER
typedef struct _REPARSE_GUID_DATA_BUFFER REPARSE_GUID_DATA_BUFFER
typedef struct _REPARSE_POINT_INFORMATION REPARSE_POINT_INFORMATION
typedef IN PIO_STATUS_BLOCK IN ULONG Reserved
Enumerations
enum _BUS_DATA_TYPE {
ConfigurationSpaceUndefined = -1, Cmos, EisaConfiguration, Pos,
CbusConfiguration, PCIConfiguration, VMEConfiguration, NuBusConfiguration,
PCMCIAConfiguration, MPIConfiguration, MPSAConfiguration, PNPISAConfiguration,
SgiInternalConfiguration, MaximumBusDataType
}
enum _DMA_SPEED {
Compatible, TypeA, TypeB, TypeC,
TypeF, MaximumDmaSpeed
}
enum _DMA_WIDTH { Width8Bits, Width16Bits, Width32Bits, MaximumDmaWidth }
enum _FILE_INFORMATION_CLASS {
FileDirectoryInformation = 1, FileFullDirectoryInformation, FileBothDirectoryInformation, FileBasicInformation,
FileStandardInformation, FileInternalInformation, FileEaInformation, FileAccessInformation,
FileNameInformation, FileRenameInformation, FileLinkInformation, FileNamesInformation,
FileDispositionInformation, FilePositionInformation, FileFullEaInformation, FileModeInformation,
FileAlignmentInformation, FileAllInformation, FileAllocationInformation, FileEndOfFileInformation,
FileAlternateNameInformation, FileStreamInformation, FilePipeInformation, FilePipeLocalInformation,
FilePipeRemoteInformation, FileMailslotQueryInformation, FileMailslotSetInformation, FileCompressionInformation,
FileObjectIdInformation, FileCompletionInformation, FileMoveClusterInformation, FileQuotaInformation,
FileReparsePointInformation, FileNetworkOpenInformation, FileAttributeTagInformation, FileTrackingInformation,
FileIdBothDirectoryInformation, FileIdFullDirectoryInformation, FileValidDataLengthInformation, FileShortNameInformation,
FileMaximumInformation
}
enum _FSINFOCLASS {
FileFsVolumeInformation = 1, FileFsLabelInformation, FileFsSizeInformation, FileFsDeviceInformation,
FileFsAttributeInformation, FileFsControlInformation, FileFsFullSizeInformation, FileFsObjectIdInformation,
FileFsDriverPathInformation, FileFsMaximumInformation
}
enum _INTERFACE_TYPE {
InterfaceTypeUndefined = -1, Internal, Isa, Eisa,
MicroChannel, TurboChannel, PCIBus, VMEBus,
NuBus, PCMCIABus, CBus, MPIBus,
MPSABus, ProcessorInternal, InternalPowerBus, PNPISABus,
PNPBus, MaximumInterfaceType
}
enum _IO_COMPLETION_INFORMATION_CLASS { IoCompletionBasicInformation }
enum _LINK_TRACKING_INFORMATION_TYPE { NtfsLinkTrackingInformation, DfsLinkTrackingInformation }
Functions
NTSYSCALLAPI NTSTATUS NTAPI NtCancelIoFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateFile (__out PHANDLE FileHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER AllocationSize, __in ULONG FileAttributes, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in_bcount_opt(EaLength) PVOID EaBuffer, __in ULONG EaLength)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Count OPTIONAL)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateMailslotFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CreateOptions, __in ULONG MailslotQuota, __in ULONG MaximumMessageSize, __in PLARGE_INTEGER ReadTimeout)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateNamedPipeFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in ULONG NamedPipeType, __in ULONG ReadMode, __in ULONG CompletionMode, __in ULONG MaximumInstances, __in ULONG InboundQuota, __in ULONG OutboundQuota, __in_opt PLARGE_INTEGER DefaultTimeout)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteFile (__in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtDeviceIoControlFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG IoControlCode, __in_bcount_opt(InputBufferLength) PVOID InputBuffer, __in ULONG InputBufferLength, __out_bcount_opt(OutputBufferLength) PVOID OutputBuffer, __in ULONG OutputBufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtFlushBuffersFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
NTSYSCALLAPI NTSTATUS NTAPI NtFsControlFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG FsControlCode, __in_bcount_opt(InputBufferLength) PVOID InputBuffer, __in ULONG InputBufferLength, __out_bcount_opt(OutputBufferLength) PVOID OutputBuffer, __in ULONG OutputBufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtLoadDriver (__in PUNICODE_STRING DriverServiceName)
NTSYSCALLAPI NTSTATUS NTAPI NtLockFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER Length, __in ULONG Key, __in BOOLEAN FailImmediately, __in BOOLEAN ExclusiveLock)
NTSYSCALLAPI NTSTATUS NTAPI NtNotifyChangeDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in ULONG CompletionFilter, __in BOOLEAN WatchTree)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenFile (__out PHANDLE FileHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG ShareAccess, __in ULONG OpenOptions)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_BASIC_INFORMATION FileInformation)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass, __in BOOLEAN ReturnSingleEntry, __in_opt PUNICODE_STRING FileName, __in BOOLEAN RestartScan)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(EaListLength) PVOID EaList, __in ULONG EaListLength, __in_opt PULONG EaIndex OPTIONAL, __in BOOLEAN RestartScan)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryFullAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_NETWORK_OPEN_INFORMATION FileInformation)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryIoCompletion (__in HANDLE IoCompletionHandle, __in IO_COMPLETION_INFORMATION_CLASS IoCompletionInformationClass, __out_bcount(IoCompletionInformation) PVOID IoCompletionInformation, __in ULONG IoCompletionInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(SidListLength) PVOID SidList, __in ULONG SidListLength, __in_opt PSID StartSid, __in BOOLEAN RestartScan)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryVolumeInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FsInformation, __in ULONG Length, __in FS_INFORMATION_CLASS FsInformationClass)
NTSYSCALLAPI NTSTATUS NTAPI NtReadFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
NTSYSCALLAPI NTSTATUS NTAPI NtReadFileScatter (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PFILE_SEGMENT_ELEMENT SegmentArray, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
NTSYSCALLAPI NTSTATUS NTAPI NtRemoveIoCompletion (__in HANDLE IoCompletionHandle, __out PVOID *KeyContext, __out PVOID *ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtSetEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
NTSYSCALLAPI NTSTATUS NTAPI NtSetIoCompletion (__in HANDLE IoCompletionHandle, __in PVOID KeyContext, __in_opt PVOID ApcContext, __in NTSTATUS IoStatus, __in ULONG_PTR IoStatusInformation)
NTSYSCALLAPI NTSTATUS NTAPI NtSetQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
NTSYSCALLAPI NTSTATUS NTAPI NtSetVolumeInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID FsInformation, __in ULONG Length, __in FS_INFORMATION_CLASS FsInformationClass)
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadDriver (__in PUNICODE_STRING DriverServiceName)
NTSYSCALLAPI NTSTATUS NTAPI NtUnlockFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER Length, __in ULONG Key)
NTSYSCALLAPI NTSTATUS NTAPI NtWriteFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
NTSYSCALLAPI NTSTATUS NTAPI NtWriteFileGather (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PFILE_SEGMENT_ELEMENT SegmentArray, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
typedef VOID (NTAPI *PIO_APC_ROUTINE)(IN PVOID ApcContext
Macro Definition Documentation
#define _FILESYSTEMFSCTL_
Definition at line 1472 of file ntioapi.h.
#define ANSI_DOS_DOT ('"')
Definition at line 679 of file ntioapi.h.
Referenced by FsRtlIsFatDbcsLegal(), and FsRtlIsHpfsDbcsLegal().
#define ANSI_DOS_QM ('>')
Definition at line 678 of file ntioapi.h.
Referenced by FsRtlIsDbcsInExpression().
#define ANSI_DOS_STAR ('<')
Definition at line 677 of file ntioapi.h.
Referenced by FsRtlIsDbcsInExpression().
#define DOS_DOT (L'"')
Definition at line 683 of file ntioapi.h.
Referenced by FsRtlIsDbcsInExpression(), and FsRtlIsNameInExpressionPrivate().
#define DOS_QM (L'>')
Definition at line 682 of file ntioapi.h.
Referenced by FsRtlIsNameInExpressionPrivate().
#define DOS_STAR (L'<')
Definition at line 681 of file ntioapi.h.
Referenced by FsRtlIsNameInExpressionPrivate().
#define FILE_128_BYTE_ALIGNMENT 0x0000007f
Definition at line 354 of file ntioapi.h.
#define FILE_256_BYTE_ALIGNMENT 0x000000ff
Definition at line 355 of file ntioapi.h.
#define FILE_32_BYTE_ALIGNMENT 0x0000001f
Definition at line 352 of file ntioapi.h.
#define FILE_512_BYTE_ALIGNMENT 0x000001ff
Definition at line 356 of file ntioapi.h.
#define FILE_64_BYTE_ALIGNMENT 0x0000003f
Definition at line 353 of file ntioapi.h.
#define FILE_ACTION_ADDED 0x00000001
Definition at line 251 of file ntioapi.h.
#define FILE_ACTION_ADDED_STREAM 0x00000006
Definition at line 256 of file ntioapi.h.
#define FILE_ACTION_ID_NOT_TUNNELLED 0x0000000A
Definition at line 260 of file ntioapi.h.
#define FILE_ACTION_MODIFIED 0x00000003
Definition at line 253 of file ntioapi.h.
#define FILE_ACTION_MODIFIED_STREAM 0x00000008
Definition at line 258 of file ntioapi.h.
#define FILE_ACTION_REMOVED 0x00000002
Definition at line 252 of file ntioapi.h.
#define FILE_ACTION_REMOVED_BY_DELETE 0x00000009
Definition at line 259 of file ntioapi.h.
#define FILE_ACTION_REMOVED_STREAM 0x00000007
Definition at line 257 of file ntioapi.h.
#define FILE_ACTION_RENAMED_NEW_NAME 0x00000005
Definition at line 255 of file ntioapi.h.
#define FILE_ACTION_RENAMED_OLD_NAME 0x00000004
Definition at line 254 of file ntioapi.h.
Referenced by FsRtlNotifyFilterReportChange().
#define FILE_ACTION_TUNNELLED_ID_COLLISION 0x0000000B
Definition at line 261 of file ntioapi.h.
#define FILE_ADD_FILE (0x0002)
Definition at line 56 of file ntioapi.h.
Referenced by IopCheckBackupRestorePrivilege().
#define FILE_ADD_SUBDIRECTORY (0x0004)
Definition at line 59 of file ntioapi.h.
Referenced by IopCheckBackupRestorePrivilege(), and IopOpenLinkOrRenameTarget().
#define FILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)
Definition at line 76 of file ntioapi.h.
Referenced by IopCreateObjectTypes(), NtCreatePagingFile(), WmipCreateAdminSD(), and WmipTranslateFileHandle().
#define FILE_APPEND_DATA (0x0004)
Definition at line 58 of file ntioapi.h.
Referenced by IoCheckFunctionAccess(), IoCheckShareAccess(), IoComputeDesiredAccessFileObject(), IopCreateFile(), IoSetShareAccess(), NtFlushBuffersFile(), NtWriteFile(), and NtWriteFileGather().
#define FILE_ATTRIBUTE_ARCHIVE 0x00000020
Definition at line 133 of file ntioapi.h.
#define FILE_ATTRIBUTE_COMPRESSED 0x00000800
Definition at line 140 of file ntioapi.h.
#define FILE_ATTRIBUTE_DEVICE 0x00000040
Definition at line 134 of file ntioapi.h.
#define FILE_ATTRIBUTE_DIRECTORY 0x00000010
Definition at line 132 of file ntioapi.h.
Referenced by IopOpenLinkOrRenameTarget().
#define FILE_ATTRIBUTE_ENCRYPTED 0x00004000
Definition at line 144 of file ntioapi.h.
#define FILE_ATTRIBUTE_HIDDEN 0x00000002
Definition at line 128 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), NtCreatePagingFile(), and RtlCreateSystemVolumeInformationFolder().
#define FILE_ATTRIBUTE_NORMAL 0x00000080
Definition at line 135 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), FsRtlpOpenDev(), IopBootLogToFile(), MmLoadSystemImage(), and WmipCreateDirectoryFile().
#define FILE_ATTRIBUTE_NOT_CONTENT_INDEXED 0x00002000
Definition at line 143 of file ntioapi.h.
#define FILE_ATTRIBUTE_OFFLINE 0x00001000
Definition at line 142 of file ntioapi.h.
#define FILE_ATTRIBUTE_READONLY 0x00000001
Definition at line 127 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice().
#define FILE_ATTRIBUTE_REPARSE_POINT 0x00000400
Definition at line 139 of file ntioapi.h.
#define FILE_ATTRIBUTE_SPARSE_FILE 0x00000200
Definition at line 138 of file ntioapi.h.
#define FILE_ATTRIBUTE_SYSTEM 0x00000004
Definition at line 129 of file ntioapi.h.
Referenced by NtCreatePagingFile(), and RtlCreateSystemVolumeInformationFolder().
#define FILE_ATTRIBUTE_TEMPORARY 0x00000100
Definition at line 137 of file ntioapi.h.
#define FILE_ATTRIBUTE_VALID_FLAGS 0x00007fb7
Definition at line 146 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_ATTRIBUTE_VALID_SET_FLAGS 0x000031a7
Definition at line 147 of file ntioapi.h.
#define FILE_AUTOGENERATED_DEVICE_NAME 0x00000080
Definition at line 418 of file ntioapi.h.
Referenced by IoCreateDevice().
#define FILE_BYTE_ALIGNMENT 0x00000000
Definition at line 347 of file ntioapi.h.
#define FILE_CASE_PRESERVED_NAMES 0x00000002
Definition at line 371 of file ntioapi.h.
#define FILE_CASE_SENSITIVE_SEARCH 0x00000001
Definition at line 370 of file ntioapi.h.
#define FILE_CHARACTERISTIC_PNP_DEVICE 0x00000800
Definition at line 420 of file ntioapi.h.
#define FILE_CHARACTERISTICS_EXPECT_ORDERLY_REMOVAL 0x00000200
Definition at line 428 of file ntioapi.h.
#define FILE_CHARACTERISTICS_EXPECT_SURPRISE_REMOVAL 0x00000300
Definition at line 429 of file ntioapi.h.
#define FILE_CHARACTERISTICS_PROPAGATED
Value:
(FILE_REMOVABLE_MEDIA   | \
                                            FILE_READ_ONLY_DEVICE  | \
                                            FILE_FLOPPY_DISKETTE   | \
                                            FILE_WRITE_ONCE_MEDIA  | \
                                            FILE_DEVICE_SECURE_OPEN  )
Definition at line 438 of file ntioapi.h.
#define FILE_CHARACTERISTICS_REMOVAL_POLICY_MASK 0x00000300
Definition at line 430 of file ntioapi.h.
#define FILE_COMPLETE_IF_OPLOCKED 0x00000100
Definition at line 175 of file ntioapi.h.
Referenced by FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), and IopCreateFile().
#define FILE_COPY_STRUCTURED_STORAGE 0x00000041
Definition at line 191 of file ntioapi.h.
#define FILE_CREATE 0x00000002
Definition at line 155 of file ntioapi.h.
Referenced by IopCreateFile(), and NtCreateMailslotFile().
#define FILE_CREATE_PIPE_INSTANCE (0x0004)
Definition at line 60 of file ntioapi.h.
#define FILE_CREATE_TREE_CONNECTION 0x00000080
Definition at line 173 of file ntioapi.h.
#define FILE_CREATED 0x00000002
Definition at line 206 of file ntioapi.h.
Referenced by CmpInitHiveFromFile(), CmpOpenHiveFiles(), and IopBootLogToFile().
#define FILE_DELETE_CHILD (0x0040)
Definition at line 70 of file ntioapi.h.
#define FILE_DELETE_ON_CLOSE 0x00001000
Definition at line 180 of file ntioapi.h.
Referenced by IopCreateFile(), IopGetModeInformation(), NtCreatePagingFile(), and NtDeleteFile().
#define FILE_DEVICE_IS_MOUNTED 0x00000020
Definition at line 416 of file ntioapi.h.
Referenced by NtQueryVolumeInformationFile().
#define FILE_DEVICE_SECURE_OPEN 0x00000100
Definition at line 419 of file ntioapi.h.
Referenced by IopParseDevice(), and WmipDriverEntry().
#define FILE_DIRECTORY_FILE 0x00000001
Definition at line 165 of file ntioapi.h.
Referenced by IopCreateFile(), RawCreate(), RtlCreateSystemVolumeInformationFolder(), RtlpSysVolTakeOwnership(), and WmipCreateDirectoryFile().
#define FILE_DOES_NOT_EXIST 0x00000005
Definition at line 209 of file ntioapi.h.
#define FILE_EA_TYPE_ASCII 0xfffd
Definition at line 396 of file ntioapi.h.
#define FILE_EA_TYPE_ASN1 0xffdd
Definition at line 403 of file ntioapi.h.
#define FILE_EA_TYPE_BINARY 0xfffe
Definition at line 395 of file ntioapi.h.
#define FILE_EA_TYPE_BITMAP 0xfffb
Definition at line 397 of file ntioapi.h.
#define FILE_EA_TYPE_EA 0xffee
Definition at line 400 of file ntioapi.h.
#define FILE_EA_TYPE_FAMILY_IDS 0xff01
Definition at line 404 of file ntioapi.h.
#define FILE_EA_TYPE_ICON 0xfff9
Definition at line 399 of file ntioapi.h.
#define FILE_EA_TYPE_METAFILE 0xfffa
Definition at line 398 of file ntioapi.h.
#define FILE_EA_TYPE_MVMT 0xffdf
Definition at line 401 of file ntioapi.h.
#define FILE_EA_TYPE_MVST 0xffde
Definition at line 402 of file ntioapi.h.
#define FILE_EXECUTE (0x0020)
Definition at line 67 of file ntioapi.h.
Referenced by IoCheckShareAccess(), IoSetShareAccess(), MmLoadSystemImage(), PsLocateSystemDll(), and RtlpOpenImageFile().
#define FILE_EXISTS 0x00000004
Definition at line 208 of file ntioapi.h.
Referenced by IopOpenLinkOrRenameTarget().
#define FILE_FILE_COMPRESSION 0x00000010
Definition at line 374 of file ntioapi.h.
#define FILE_FLOPPY_DISKETTE 0x00000004
Definition at line 413 of file ntioapi.h.
Referenced by IoIsDeviceEjectable(), IopCreateDefaultDeviceSecurityDescriptor(), NtCreatePagingFile(), and RawQueryFsSizeInfo().
#define FILE_GENERIC_EXECUTE
Value:
(STANDARD_RIGHTS_EXECUTE  |\
                                   FILE_READ_ATTRIBUTES     |\
                                   FILE_EXECUTE             |\
                                   SYNCHRONIZE)
Definition at line 93 of file ntioapi.h.
#define FILE_GENERIC_READ
Value:
(STANDARD_RIGHTS_READ     |\
                                   FILE_READ_DATA           |\
                                   FILE_READ_ATTRIBUTES     |\
                                   FILE_READ_EA             |\
                                   SYNCHRONIZE)
Definition at line 78 of file ntioapi.h.
Referenced by IopCheckBackupRestorePrivilege(), and WmipCreateDirectoryFile().
#define FILE_GENERIC_WRITE
Value:
(STANDARD_RIGHTS_WRITE    |\
                                   FILE_WRITE_DATA          |\
                                   FILE_WRITE_ATTRIBUTES    |\
                                   FILE_WRITE_EA            |\
                                   FILE_APPEND_DATA         |\
                                   SYNCHRONIZE)
Definition at line 85 of file ntioapi.h.
Referenced by IopCheckBackupRestorePrivilege(), and WmipCreateDirectoryFile().
#define FILE_LIST_DIRECTORY (0x0001)
Definition at line 53 of file ntioapi.h.
Referenced by BuildQueryDirectoryIrp(), IoCheckFunctionAccess(), and NtNotifyChangeDirectoryFile().
#define FILE_LONG_ALIGNMENT 0x00000003
Definition at line 349 of file ntioapi.h.
#define FILE_MAXIMUM_DISPOSITION 0x00000005
Definition at line 159 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_NAMED_STREAMS 0x00040000
Definition at line 382 of file ntioapi.h.
#define FILE_NEED_EA 0x00000080
Definition at line 389 of file ntioapi.h.
#define FILE_NO_COMPRESSION 0x00008000
Definition at line 183 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), IopCreateFile(), and NtCreatePagingFile().
#define FILE_NO_EA_KNOWLEDGE 0x00000200
Definition at line 176 of file ntioapi.h.
#define FILE_NO_INTERMEDIATE_BUFFERING 0x00000008
Definition at line 168 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), IopCreateFile(), IopGetModeInformation(), IopParseDevice(), NtCreatePagingFile(), and WmipCreateDirectoryFile().
#define FILE_NON_DIRECTORY_FILE 0x00000040
Definition at line 172 of file ntioapi.h.
Referenced by IoAttachDevice(), IoGetDeviceObjectPointer(), IopBootLogToFile(), IopCreateFile(), IopMarkBootPartition(), and RtlpOpenImageFile().
#define FILE_NOTIFY_CHANGE_ATTRIBUTES 0x00000004
Definition at line 235 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_CREATION 0x00000040
Definition at line 239 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_DIR_NAME 0x00000002
Definition at line 233 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_EA 0x00000080
Definition at line 240 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_FILE_NAME 0x00000001
Definition at line 232 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_LAST_ACCESS 0x00000020
Definition at line 238 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_LAST_WRITE 0x00000010
Definition at line 237 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_NAME 0x00000003
Definition at line 234 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_SECURITY 0x00000100
Definition at line 241 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_SIZE 0x00000008
Definition at line 236 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_STREAM_NAME 0x00000200
Definition at line 242 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_STREAM_SIZE 0x00000400
Definition at line 243 of file ntioapi.h.
#define FILE_NOTIFY_CHANGE_STREAM_WRITE 0x00000800
Definition at line 244 of file ntioapi.h.
#define FILE_NOTIFY_VALID_MASK 0x00000fff
Definition at line 245 of file ntioapi.h.
Referenced by NtNotifyChangeDirectoryFile().
#define FILE_OCTA_ALIGNMENT 0x0000000f
Definition at line 351 of file ntioapi.h.
#define FILE_OPBATCH_BREAK_UNDERWAY 0x00000009
Definition at line 226 of file ntioapi.h.
#define FILE_OPEN 0x00000001
Definition at line 154 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice(), CmpOpenHiveFiles(), FsRtlpOpenDev(), IoFastQueryNetworkAttributes(), IopCheckBackupRestorePrivilege(), IopCreateFile(), IopOpenLinkOrRenameTarget(), NtCreatePagingFile(), NtDeleteFile(), NtOpenFile(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), and RawCreate().
#define FILE_OPEN_BY_FILE_ID 0x00002000
Definition at line 181 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_OPEN_FOR_BACKUP_INTENT 0x00004000
Definition at line 182 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice(), CmpOpenHiveFiles(), IopCheckBackupRestorePrivilege(), IopCreateFile(), IopOpenLinkOrRenameTarget(), NtQueryAttributesFile(), and NtQueryFullAttributesFile().
#define FILE_OPEN_FOR_FREE_SPACE_QUERY 0x00800000
Definition at line 188 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_OPEN_FOR_RECOVERY 0x00000400
Definition at line 177 of file ntioapi.h.
#define FILE_OPEN_IF 0x00000003
Definition at line 156 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), IopBootLogToFile(), IopCheckBackupRestorePrivilege(), IopCreateFile(), RtlCreateSystemVolumeInformationFolder(), and WmipCreateDirectoryFile().
#define FILE_OPEN_NO_RECALL 0x00400000
Definition at line 187 of file ntioapi.h.
#define FILE_OPEN_REPARSE_POINT 0x00200000
Definition at line 186 of file ntioapi.h.
Referenced by IoFastQueryNetworkAttributes(), IopCreateFile(), NtQueryAttributesFile(), and NtQueryFullAttributesFile().
#define FILE_OPENED 0x00000001
Definition at line 205 of file ntioapi.h.
Referenced by RawCreate().
#define FILE_OPLOCK_BROKEN_TO_LEVEL_2 0x00000007
Definition at line 218 of file ntioapi.h.
Referenced by FsRtlOplockBreakToII().
#define FILE_OPLOCK_BROKEN_TO_NONE 0x00000008
Definition at line 219 of file ntioapi.h.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlRemoveAndCompleteIrp(), and FsRtlUninitializeOplock().
#define FILE_OVERWRITE 0x00000004
Definition at line 157 of file ntioapi.h.
Referenced by FsRtlCheckOplock().
#define FILE_OVERWRITE_IF 0x00000005
Definition at line 158 of file ntioapi.h.
Referenced by FsRtlCheckOplock(), IopCheckBackupRestorePrivilege(), MmLoadSystemImage(), and WmipCreateDirectoryFile().
#define FILE_OVERWRITTEN 0x00000003
Definition at line 207 of file ntioapi.h.
#define FILE_PERSISTENT_ACLS 0x00000008
Definition at line 373 of file ntioapi.h.
#define FILE_PIPE_BYTE_STREAM_MODE 0x00000000
Definition at line 281 of file ntioapi.h.
#define FILE_PIPE_BYTE_STREAM_TYPE 0x00000000
Definition at line 267 of file ntioapi.h.
#define FILE_PIPE_CLIENT_END 0x00000000
Definition at line 305 of file ntioapi.h.
#define FILE_PIPE_CLOSING_STATE 0x00000004
Definition at line 299 of file ntioapi.h.
#define FILE_PIPE_COMPLETE_OPERATION 0x00000001
Definition at line 275 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_PIPE_COMPUTER_NAME_LENGTH 15
Definition at line 2853 of file ntioapi.h.
#define FILE_PIPE_CONNECTED_STATE 0x00000003
Definition at line 298 of file ntioapi.h.
#define FILE_PIPE_DISCONNECTED_STATE 0x00000001
Definition at line 296 of file ntioapi.h.
#define FILE_PIPE_FULL_DUPLEX 0x00000002
Definition at line 290 of file ntioapi.h.
#define FILE_PIPE_INBOUND 0x00000000
Definition at line 288 of file ntioapi.h.
#define FILE_PIPE_LISTENING_STATE 0x00000002
Definition at line 297 of file ntioapi.h.
#define FILE_PIPE_MESSAGE_MODE 0x00000001
Definition at line 282 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_PIPE_MESSAGE_TYPE 0x00000001
Definition at line 268 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_PIPE_OUTBOUND 0x00000001
Definition at line 289 of file ntioapi.h.
#define FILE_PIPE_QUEUE_OPERATION 0x00000000
Definition at line 274 of file ntioapi.h.
#define FILE_PIPE_READ_DATA 0x00000000
Definition at line 2795 of file ntioapi.h.
#define FILE_PIPE_SERVER_END 0x00000001
Definition at line 306 of file ntioapi.h.
#define FILE_PIPE_WRITE_SPACE 0x00000001
Definition at line 2796 of file ntioapi.h.
#define FILE_PREFETCH_TYPE_FOR_CREATE 0x1
Definition at line 1971 of file ntioapi.h.
#define FILE_QUAD_ALIGNMENT 0x00000007
Definition at line 350 of file ntioapi.h.
#define FILE_RANDOM_ACCESS 0x00000800
Definition at line 178 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), and IopParseDevice().
#define FILE_READ_ATTRIBUTES (0x0080)
Definition at line 72 of file ntioapi.h.
Referenced by FsRtlCheckOplock(), FsRtlOplockFsctrl(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoAttachDevice(), IoGetBootDiskInformation(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopMarkBootPartition(), IopParseDevice(), IopReferenceDriverObjectByName(), IoVolumeDeviceToDosName(), NtQueryAttributesFile(), and NtQueryFullAttributesFile().
#define FILE_READ_DATA (0x0001)
Definition at line 52 of file ntioapi.h.
Referenced by CmpAcquireFileObjectForFile(), CmpOpenFileWithExtremePrejudice(), CmpOpenHiveFiles(), ExCreateCallback(), IoAssignDriveLetters(), IoCheckFunctionAccess(), IoCheckShareAccess(), IoCreateController(), IoCreateDevice(), IoCreateDriver(), IoCreateStreamFileObjectEx(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopUnloadDriver(), IopXxxControlFile(), IoSetShareAccess(), IoValidateDeviceIoControlAccess(), NtCreatePagingFile(), NtLockFile(), NtReadFile(), NtReadFileScatter(), and NtUnlockFile().
#define FILE_READ_EA (0x0008)
Definition at line 63 of file ntioapi.h.
Referenced by IoCheckFunctionAccess(), and NtQueryEaFile().
#define FILE_READ_ONLY_DEVICE 0x00000002
Definition at line 412 of file ntioapi.h.
Referenced by IopMarkBootPartition().
#define FILE_READ_ONLY_VOLUME 0x00080000
Definition at line 383 of file ntioapi.h.
#define FILE_REMOTE_DEVICE 0x00000010
Definition at line 415 of file ntioapi.h.
Referenced by MiCreateImageFileMap().
#define FILE_REMOVABLE_MEDIA 0x00000001
Definition at line 411 of file ntioapi.h.
Referenced by HalpQueryDriveLayout(), HalpQueryPartitionType(), IopMarkBootPartition(), MiCreateImageFileMap(), and ObpProcessDosDeviceSymbolicLink().
#define FILE_RESERVE_OPFILTER 0x00100000
Definition at line 185 of file ntioapi.h.
Referenced by FsRtlCheckOplock(), and IopCreateFile().
#define FILE_SEQUENTIAL_ONLY 0x00000004
Definition at line 167 of file ntioapi.h.
Referenced by IopBootLogToFile(), IopGetModeInformation(), IopParseDevice(), IoSetInformation(), and NtSetInformationFile().
#define FILE_SHARE_DELETE 0x00000004
Definition at line 107 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice(), DbgkCreateThread(), DbgkpPostFakeModuleMessages(), DbgkpSectionToFileHandle(), FsRtlOplockFsctrl(), IoCheckShareAccess(), IoFastQueryNetworkAttributes(), IopCreateFile(), IoSetShareAccess(), MmLoadSystemImage(), NtDeleteFile(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), RtlCreateSystemVolumeInformationFolder(), RtlpOpenImageFile(), and RtlpSysVolTakeOwnership().
#define FILE_SHARE_READ 0x00000001
Definition at line 105 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice(), CmpOpenHiveFiles(), DbgkCreateThread(), DbgkpPostFakeModuleMessages(), DbgkpSectionToFileHandle(), FsRtlCheckOplock(), FsRtlOplockFsctrl(), FsRtlpOpenDev(), IoAssignDriveLetters(), IoCheckShareAccess(), IoFastQueryNetworkAttributes(), IopBootLogToFile(), IopOpenLinkOrRenameTarget(), IoSetShareAccess(), MmLoadSystemImage(), NtCreateMailslotFile(), NtCreatePagingFile(), NtDeleteFile(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), PsLocateSystemDll(), RtlCreateSystemVolumeInformationFolder(), RtlpOpenImageFile(), RtlpSysVolTakeOwnership(), and WmipCreateDirectoryFile().
#define FILE_SHARE_VALID_FLAGS 0x00000007
Definition at line 108 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_SHARE_WRITE 0x00000002
Definition at line 106 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice(), DbgkCreateThread(), DbgkpPostFakeModuleMessages(), DbgkpSectionToFileHandle(), FsRtlOplockFsctrl(), FsRtlpOpenDev(), IoCheckShareAccess(), IoFastQueryNetworkAttributes(), IopCreateFile(), IopOpenLinkOrRenameTarget(), IoSetShareAccess(), NtCreateMailslotFile(), NtCreatePagingFile(), NtDeleteFile(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), RtlCreateSystemVolumeInformationFolder(), and RtlpSysVolTakeOwnership().
#define FILE_STRUCTURED_STORAGE 0x00000441
Definition at line 192 of file ntioapi.h.
#define FILE_SUPERSEDE 0x00000000
Definition at line 153 of file ntioapi.h.
Referenced by CmpOpenHiveFiles(), FsRtlCheckOplock(), and NtCreatePagingFile().
#define FILE_SUPERSEDED 0x00000000
Definition at line 204 of file ntioapi.h.
#define FILE_SUPPORTS_ENCRYPTION 0x00020000
Definition at line 381 of file ntioapi.h.
#define FILE_SUPPORTS_OBJECT_IDS 0x00010000
Definition at line 380 of file ntioapi.h.
#define FILE_SUPPORTS_REMOTE_STORAGE 0x00000100
Definition at line 378 of file ntioapi.h.
#define FILE_SUPPORTS_REPARSE_POINTS 0x00000080
Definition at line 377 of file ntioapi.h.
#define FILE_SUPPORTS_SPARSE_FILES 0x00000040
Definition at line 376 of file ntioapi.h.
#define FILE_SYNCHRONOUS_IO_ALERT 0x00000010
Definition at line 170 of file ntioapi.h.
Referenced by IopCheckVpbMounted(), IopCreateFile(), IopGetModeInformation(), IopParseDevice(), and IoSetInformation().
#define FILE_SYNCHRONOUS_IO_NONALERT 0x00000020
Definition at line 171 of file ntioapi.h.
Referenced by DbgkCreateThread(), DbgkpPostFakeModuleMessages(), DbgkpSectionToFileHandle(), IoAssignDriveLetters(), IopBootLogToFile(), IopCreateFile(), IopGetModeInformation(), IopParseDevice(), MmLoadSystemImage(), RtlCreateSystemVolumeInformationFolder(), RtlpSysVolTakeOwnership(), and WmipCreateDirectoryFile().
#define FILE_TRAVERSE (0x0020)
Definition at line 68 of file ntioapi.h.
Referenced by IopCheckBackupRestorePrivilege(), and IopParseDevice().
#define FILE_UNICODE_ON_DISK 0x00000004
Definition at line 372 of file ntioapi.h.
#define FILE_USE_FILE_POINTER_POSITION 0xfffffffe
Definition at line 341 of file ntioapi.h.
Referenced by NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define FILE_VALID_MAILSLOT_OPTION_FLAGS 0x00000032
Definition at line 197 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_VALID_OPTION_FLAGS 0x00ffffff
Definition at line 195 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_VALID_PIPE_OPTION_FLAGS 0x00000032
Definition at line 196 of file ntioapi.h.
Referenced by IopCreateFile().
#define FILE_VALID_SET_FLAGS 0x00000036
Definition at line 198 of file ntioapi.h.
Referenced by NtSetInformationFile().
#define FILE_VC_CONTENT_INDEX_DISABLED 0x00000008
Definition at line 1038 of file ntioapi.h.
#define FILE_VC_LOG_QUOTA_LIMIT 0x00000020
Definition at line 1041 of file ntioapi.h.
#define FILE_VC_LOG_QUOTA_THRESHOLD 0x00000010
Definition at line 1040 of file ntioapi.h.
#define FILE_VC_LOG_VOLUME_LIMIT 0x00000080
Definition at line 1043 of file ntioapi.h.
#define FILE_VC_LOG_VOLUME_THRESHOLD 0x00000040
Definition at line 1042 of file ntioapi.h.
#define FILE_VC_QUOTA_ENFORCE 0x00000002
Definition at line 1035 of file ntioapi.h.
#define FILE_VC_QUOTA_MASK 0x00000003
Definition at line 1036 of file ntioapi.h.
#define FILE_VC_QUOTA_NONE 0x00000000
Definition at line 1033 of file ntioapi.h.
#define FILE_VC_QUOTA_TRACK 0x00000001
Definition at line 1034 of file ntioapi.h.
#define FILE_VC_QUOTAS_INCOMPLETE 0x00000100
Definition at line 1045 of file ntioapi.h.
#define FILE_VC_QUOTAS_REBUILDING 0x00000200
Definition at line 1046 of file ntioapi.h.
#define FILE_VC_VALID_MASK 0x000003ff
Definition at line 1048 of file ntioapi.h.
#define FILE_VIRTUAL_VOLUME 0x00000040
Definition at line 417 of file ntioapi.h.
#define FILE_VOLUME_IS_COMPRESSED 0x00008000
Definition at line 379 of file ntioapi.h.
#define FILE_VOLUME_QUOTAS 0x00000020
Definition at line 375 of file ntioapi.h.
#define FILE_WORD_ALIGNMENT 0x00000001
Definition at line 348 of file ntioapi.h.
#define FILE_WRITE_ATTRIBUTES (0x0100)
Definition at line 74 of file ntioapi.h.
Referenced by CmpOpenFileWithExtremePrejudice(), and FsRtlCheckOplock().
#define FILE_WRITE_DATA (0x0002)
Definition at line 55 of file ntioapi.h.
Referenced by CmpAcquireFileObjectForFile(), CmpOpenFileWithExtremePrejudice(), CmpOpenHiveFiles(), IoCheckFunctionAccess(), IoCheckShareAccess(), IoComputeDesiredAccessFileObject(), IoCreateController(), IoCreateDevice(), IopOpenLinkOrRenameTarget(), IopSetEaOrQuotaInformationFile(), IopTrackLink(), IopXxxControlFile(), IoSetShareAccess(), IoValidateDeviceIoControlAccess(), NtCreatePagingFile(), NtFlushBuffersFile(), NtLockFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), WmipCreateDirectoryFile(), WmipStartLogger(), and WmiUpdateTrace().
#define FILE_WRITE_EA (0x0010)
Definition at line 65 of file ntioapi.h.
Referenced by IoCheckFunctionAccess(), IopSetEaOrQuotaInformationFile(), and NtSetEaFile().
#define FILE_WRITE_ONCE_MEDIA 0x00000008
Definition at line 414 of file ntioapi.h.
#define FILE_WRITE_THROUGH 0x00000002
Definition at line 166 of file ntioapi.h.
Referenced by IopCreateFile(), IopGetModeInformation(), IopParseDevice(), IoSetInformation(), and NtSetInformationFile().
#define FILE_WRITE_TO_END_OF_FILE 0xffffffff
Definition at line 340 of file ntioapi.h.
Referenced by FsRtlCopyWrite(), FsRtlPrepareMdlWriteDev(), IopBootLogToFile(), NtWriteFile(), and NtWriteFileGather().
#define FILESYSTEM_STATISTICS_TYPE_FAT 2
Definition at line 2008 of file ntioapi.h.
#define FILESYSTEM_STATISTICS_TYPE_NTFS 1
Definition at line 2007 of file ntioapi.h.
#define FSCTL_DISMOUNT_VOLUME CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1488 of file ntioapi.h.
Referenced by IopXxxControlFile(), and RawUserFsCtrl().
#define FSCTL_FILESYSTEM_GET_STATISTICS CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 24, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1504 of file ntioapi.h.
#define FSCTL_GET_COMPRESSION CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 15, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1495 of file ntioapi.h.
#define FSCTL_INVALIDATE_VOLUMES CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 21, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1501 of file ntioapi.h.
Referenced by IopInvalidateVolumesForDevice().
#define FSCTL_IS_PATHNAME_VALID CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 11, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1491 of file ntioapi.h.
#define FSCTL_IS_VOLUME_MOUNTED CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 10, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1490 of file ntioapi.h.
#define FSCTL_LMR_GET_LINK_TRACKING_INFORMATION CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM,58,METHOD_BUFFERED,FILE_ANY_ACCESS)
Definition at line 2744 of file ntioapi.h.
Referenced by IopGetSetObjectId(), and IopTrackLink().
#define FSCTL_LMR_SET_LINK_TRACKING_INFORMATION CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM,59,METHOD_BUFFERED,FILE_ANY_ACCESS)
Definition at line 2751 of file ntioapi.h.
Referenced by IopSetRemoteLink().
#define FSCTL_LOCK_VOLUME CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1486 of file ntioapi.h.
Referenced by RawUserFsCtrl().
#define FSCTL_MAILSLOT_PEEK CTL_CODE(FILE_DEVICE_MAILSLOT, 0, METHOD_NEITHER, FILE_READ_DATA)
Definition at line 2885 of file ntioapi.h.
#define FSCTL_MARK_AS_SYSTEM_HIVE CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 19, METHOD_NEITHER, FILE_ANY_ACCESS)
Definition at line 1499 of file ntioapi.h.
Referenced by CmpOpenHiveFiles().
#define FSCTL_MARK_VOLUME_DIRTY CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 12, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1492 of file ntioapi.h.
#define FSCTL_OPBATCH_ACK_CLOSE_PENDING CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1484 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl().
#define FSCTL_OPLOCK_BREAK_ACK_NO_2 CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 20, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1500 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl().
#define FSCTL_OPLOCK_BREAK_ACKNOWLEDGE CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 3, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1483 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl(), and RawUserFsCtrl().
#define FSCTL_OPLOCK_BREAK_NOTIFY CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 5, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1485 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl(), and RawUserFsCtrl().
#define FSCTL_PIPE_ASSIGN_EVENT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2771 of file ntioapi.h.
#define FSCTL_PIPE_DISCONNECT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2772 of file ntioapi.h.
#define FSCTL_PIPE_IMPERSONATE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2778 of file ntioapi.h.
#define FSCTL_PIPE_INTERNAL_READ CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2045, METHOD_BUFFERED, FILE_READ_DATA)
Definition at line 2786 of file ntioapi.h.
#define FSCTL_PIPE_INTERNAL_READ_OVFLOW CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2048, METHOD_BUFFERED, FILE_READ_DATA)
Definition at line 2789 of file ntioapi.h.
#define FSCTL_PIPE_INTERNAL_TRANSCEIVE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2047, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
Definition at line 2788 of file ntioapi.h.
#define FSCTL_PIPE_INTERNAL_WRITE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2046, METHOD_BUFFERED, FILE_WRITE_DATA)
Definition at line 2787 of file ntioapi.h.
#define FSCTL_PIPE_LISTEN CTL_CODE(FILE_DEVICE_NAMED_PIPE, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2773 of file ntioapi.h.
#define FSCTL_PIPE_PEEK CTL_CODE(FILE_DEVICE_NAMED_PIPE, 3, METHOD_BUFFERED, FILE_READ_DATA)
Definition at line 2774 of file ntioapi.h.
#define FSCTL_PIPE_QUERY_CLIENT_PROCESS CTL_CODE(FILE_DEVICE_NAMED_PIPE, 9, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2780 of file ntioapi.h.
#define FSCTL_PIPE_QUERY_EVENT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 4, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2775 of file ntioapi.h.
#define FSCTL_PIPE_SET_CLIENT_PROCESS CTL_CODE(FILE_DEVICE_NAMED_PIPE, 8, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2779 of file ntioapi.h.
#define FSCTL_PIPE_TRANSCEIVE CTL_CODE(FILE_DEVICE_NAMED_PIPE, 5, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
Definition at line 2776 of file ntioapi.h.
#define FSCTL_PIPE_WAIT CTL_CODE(FILE_DEVICE_NAMED_PIPE, 6, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 2777 of file ntioapi.h.
#define FSCTL_QUERY_FAT_BPB CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 22, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1502 of file ntioapi.h.
#define FSCTL_QUERY_RETRIEVAL_POINTERS CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 14, METHOD_NEITHER, FILE_ANY_ACCESS)
Definition at line 1494 of file ntioapi.h.
#define FSCTL_REQUEST_BATCH_OPLOCK CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1482 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl().
#define FSCTL_REQUEST_FILTER_OPLOCK CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 23, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1503 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl().
#define FSCTL_REQUEST_OPLOCK_LEVEL_1 CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 0, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1480 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl(), and RawUserFsCtrl().
#define FSCTL_REQUEST_OPLOCK_LEVEL_2 CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 1, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1481 of file ntioapi.h.
Referenced by FsRtlOplockFsctrl(), and RawUserFsCtrl().
#define FSCTL_SET_COMPRESSION CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 16, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
Definition at line 1496 of file ntioapi.h.
Referenced by CmpOpenHiveFiles().
#define FSCTL_UNLOCK_VOLUME CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 7, METHOD_BUFFERED, FILE_ANY_ACCESS)
Definition at line 1487 of file ntioapi.h.
Referenced by RawUserFsCtrl().
#define IO_COMPLETION_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
Definition at line 2934 of file ntioapi.h.
Referenced by IopCreateObjectTypes().
#define IO_COMPLETION_MODIFY_STATE 0x0002
Definition at line 2933 of file ntioapi.h.
Referenced by NtRemoveIoCompletion(), NtSetInformationFile(), NtSetInformationJobObject(), and NtSetIoCompletion().
#define IO_COMPLETION_QUERY_STATE 0x0001
Definition at line 2932 of file ntioapi.h.
Referenced by NtQueryIoCompletion().
#define IO_REPARSE_TAG_ARKIVIO (0x0000000CL)
Definition at line 2689 of file ntioapi.h.
#define IO_REPARSE_TAG_COMMVAULT (0x0000000EL)
Definition at line 2701 of file ntioapi.h.
#define IO_REPARSE_TAG_DFS (0x8000000AL)
Definition at line 2659 of file ntioapi.h.
#define IO_REPARSE_TAG_ENIGMA_HSM (0x00000011L)
Definition at line 2713 of file ntioapi.h.
#define IO_REPARSE_TAG_FILTER_MANAGER (0x8000000BL)
Definition at line 2665 of file ntioapi.h.
#define IO_REPARSE_TAG_FRS_GHOST (0x80000012L)
Definition at line 2671 of file ntioapi.h.
#define IO_REPARSE_TAG_HSM (0xC0000004L)
Definition at line 2647 of file ntioapi.h.
#define IO_REPARSE_TAG_IFSTEST_CONGRUENT (0x00000009L)
Definition at line 2683 of file ntioapi.h.
#define IO_REPARSE_TAG_INTERCOPE_HSM (0x00000013L)
Definition at line 2719 of file ntioapi.h.
#define IO_REPARSE_TAG_KOM_NETWORKS_HSM (0x00000014L)
Definition at line 2725 of file ntioapi.h.
#define IO_REPARSE_TAG_MEMORY_TECH_HSM (0x00000015L)
Definition at line 2731 of file ntioapi.h.
#define IO_REPARSE_TAG_MOUNT_POINT (0xA0000003L)
Definition at line 2646 of file ntioapi.h.
Referenced by IoIsValidNameGraftingBuffer(), IopCompleteRequest(), IopCreateFile(), IopDoNameTransmogrify(), IopfCompleteRequest(), and IopParseDevice().
#define IO_REPARSE_TAG_OVERTONE (0x0000000FL)
Definition at line 2707 of file ntioapi.h.
#define IO_REPARSE_TAG_RESERVED_ONE (1)
Definition at line 2573 of file ntioapi.h.
Referenced by IopParseDevice().
#define IO_REPARSE_TAG_RESERVED_RANGE IO_REPARSE_TAG_RESERVED_ONE
Definition at line 2581 of file ntioapi.h.
Referenced by IopfCompleteRequest().
#define IO_REPARSE_TAG_RESERVED_ZERO (0)
Definition at line 2572 of file ntioapi.h.
Referenced by IopParseDevice().
#define IO_REPARSE_TAG_SIS (0x80000007L)
Definition at line 2648 of file ntioapi.h.
#define IO_REPARSE_TAG_SOLUTIONSOFT (0x2000000DL)
Definition at line 2695 of file ntioapi.h.
#define IO_REPARSE_TAG_SYMBOLIC_LINK IO_REPARSE_TAG_RESERVED_ZERO
Definition at line 2645 of file ntioapi.h.
#define IO_REPARSE_TAG_VALID_VALUES (0xF000FFFF)
Definition at line 2630 of file ntioapi.h.
#define IOCTL_LMR_ARE_FILE_OBJECTS_ON_SAME_SERVER CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM,60,METHOD_BUFFERED,FILE_ANY_ACCESS)
Definition at line 2759 of file ntioapi.h.
Referenced by IopIsSameMachine().
#define IsReparseTagMicrosoft (_tag)
Value:
(\
                           ((_tag) & 0x80000000)   \
                           )
Definition at line 2611 of file ntioapi.h.
#define IsReparseTagNameSurrogate (_tag)
Value:
(\
                           ((_tag) & 0x20000000)   \
                           )
Definition at line 2619 of file ntioapi.h.
#define IsReparseTagValid (_tag)
Value:
(\
                  !((_tag) & ~IO_REPARSE_TAG_VALID_VALUES) &&   \
                  ((_tag) > IO_REPARSE_TAG_RESERVED_RANGE)      \
                 )
Definition at line 2636 of file ntioapi.h.
#define MAILSLOT_CLASS_FIRSTCLASS 1
Definition at line 2878 of file ntioapi.h.
#define MAILSLOT_CLASS_SECONDCLASS 2
Definition at line 2879 of file ntioapi.h.
#define MAILSLOT_NO_MESSAGE ((ULONG)-1)
Definition at line 319 of file ntioapi.h.
#define MAILSLOT_SIZE_AUTO 0
Definition at line 326 of file ntioapi.h.
#define MAILSLOT_WAIT_FOREVER ((ULONG)-1)
Definition at line 333 of file ntioapi.h.
#define MAXIMUM_FILENAME_LENGTH 256
Definition at line 362 of file ntioapi.h.
Referenced by BuildQueryDirectoryIrp(), MiSnapThunk(), MmLoadSystemImage(), NtCreatePagingFile(), and RtlpGetRegistryHandle().
#define MAXIMUM_REPARSE_DATA_BUFFER_SIZE (16 * 1024)
Definition at line 2565 of file ntioapi.h.
Referenced by IoIsValidNameGraftingBuffer(), IopCompleteRequest(), IopDoNameTransmogrify(), and IopParseDevice().
#define PIO_APC_ROUTINE_DEFINED
Definition at line 481 of file ntioapi.h.
#define REPARSE_DATA_BUFFER_HEADER_SIZE FIELD_OFFSET(REPARSE_DATA_BUFFER, GenericReparseBuffer)
Definition at line 2522 of file ntioapi.h.
Referenced by IoIsValidNameGraftingBuffer(), and IopDoNameTransmogrify().
#define REPARSE_GUID_DATA_BUFFER_HEADER_SIZE FIELD_OFFSET(REPARSE_GUID_DATA_BUFFER, GenericReparseBuffer)
Definition at line 2544 of file ntioapi.h.
Typedef Documentation
typedef enum _BUS_DATA_TYPE BUS_DATA_TYPE
typedef enum _DMA_SPEED DMA_SPEED
typedef enum _DMA_WIDTH DMA_WIDTH
typedef struct _FAT_STATISTICS FAT_STATISTICS
typedef struct _FILE_ACCESS_INFORMATION FILE_ACCESS_INFORMATION
typedef struct _FILE_ALIGNMENT_INFORMATION FILE_ALIGNMENT_INFORMATION
typedef struct _FILE_ALL_INFORMATION FILE_ALL_INFORMATION
typedef struct _FILE_ALLOCATION_INFORMATION FILE_ALLOCATION_INFORMATION
typedef struct _FILE_ATTRIBUTE_TAG_INFORMATION FILE_ATTRIBUTE_TAG_INFORMATION
typedef struct _FILE_BASIC_INFORMATION FILE_BASIC_INFORMATION
typedef struct _FILE_BOTH_DIR_INFORMATION FILE_BOTH_DIR_INFORMATION
typedef struct _FILE_COMPLETION_INFORMATION FILE_COMPLETION_INFORMATION
typedef struct _FILE_COMPRESSION_INFORMATION FILE_COMPRESSION_INFORMATION
typedef struct _FILE_DIRECTORY_INFORMATION FILE_DIRECTORY_INFORMATION
typedef struct _FILE_DISPOSITION_INFORMATION FILE_DISPOSITION_INFORMATION
typedef struct _FILE_EA_INFORMATION FILE_EA_INFORMATION
typedef struct _FILE_END_OF_FILE_INFORMATION FILE_END_OF_FILE_INFORMATION
typedef struct _FILE_FS_ATTRIBUTE_INFORMATION FILE_FS_ATTRIBUTE_INFORMATION
typedef struct _FILE_FS_CONTROL_INFORMATION FILE_FS_CONTROL_INFORMATION
typedef struct _FILE_FS_DEVICE_INFORMATION FILE_FS_DEVICE_INFORMATION
typedef struct _FILE_FS_DRIVER_PATH_INFORMATION FILE_FS_DRIVER_PATH_INFORMATION
typedef struct _FILE_FS_FULL_SIZE_INFORMATION FILE_FS_FULL_SIZE_INFORMATION
typedef struct _FILE_FS_LABEL_INFORMATION FILE_FS_LABEL_INFORMATION
typedef struct _FILE_FS_OBJECTID_INFORMATION FILE_FS_OBJECTID_INFORMATION
typedef struct _FILE_FS_SIZE_INFORMATION FILE_FS_SIZE_INFORMATION
typedef struct _FILE_FS_VOLUME_INFORMATION FILE_FS_VOLUME_INFORMATION
typedef struct _FILE_FULL_DIR_INFORMATION FILE_FULL_DIR_INFORMATION
typedef struct _FILE_FULL_EA_INFORMATION FILE_FULL_EA_INFORMATION
typedef struct _FILE_GET_EA_INFORMATION FILE_GET_EA_INFORMATION
typedef struct _FILE_GET_QUOTA_INFORMATION FILE_GET_QUOTA_INFORMATION
typedef struct _FILE_ID_BOTH_DIR_INFORMATION FILE_ID_BOTH_DIR_INFORMATION
typedef struct _FILE_ID_FULL_DIR_INFORMATION FILE_ID_FULL_DIR_INFORMATION
typedef enum _FILE_INFORMATION_CLASS FILE_INFORMATION_CLASS
typedef struct _FILE_INTERNAL_INFORMATION FILE_INTERNAL_INFORMATION
typedef struct _FILE_LINK_INFORMATION FILE_LINK_INFORMATION
typedef struct _FILE_MAILSLOT_PEEK_BUFFER FILE_MAILSLOT_PEEK_BUFFER
typedef struct _FILE_MAILSLOT_QUERY_INFORMATION FILE_MAILSLOT_QUERY_INFORMATION
typedef struct _FILE_MAILSLOT_SET_INFORMATION FILE_MAILSLOT_SET_INFORMATION
typedef struct _FILE_MODE_INFORMATION FILE_MODE_INFORMATION
typedef struct _FILE_MOVE_CLUSTER_INFORMATION FILE_MOVE_CLUSTER_INFORMATION
typedef struct _FILE_NAME_INFORMATION FILE_NAME_INFORMATION
typedef struct _FILE_NAMES_INFORMATION FILE_NAMES_INFORMATION
typedef struct _FILE_NETWORK_OPEN_INFORMATION FILE_NETWORK_OPEN_INFORMATION
typedef struct _FILE_NOTIFY_INFORMATION FILE_NOTIFY_INFORMATION
typedef struct _FILE_OBJECTID_INFORMATION FILE_OBJECTID_INFORMATION
typedef struct _FILE_PIPE_ASSIGN_EVENT_BUFFER FILE_PIPE_ASSIGN_EVENT_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER FILE_PIPE_CLIENT_PROCESS_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER_EX FILE_PIPE_CLIENT_PROCESS_BUFFER_EX
typedef struct _FILE_PIPE_EVENT_BUFFER FILE_PIPE_EVENT_BUFFER
typedef struct _FILE_PIPE_INFORMATION FILE_PIPE_INFORMATION
typedef struct _FILE_PIPE_LOCAL_INFORMATION FILE_PIPE_LOCAL_INFORMATION
typedef struct _FILE_PIPE_PEEK_BUFFER FILE_PIPE_PEEK_BUFFER
typedef struct _FILE_PIPE_REMOTE_INFORMATION FILE_PIPE_REMOTE_INFORMATION
typedef struct _FILE_PIPE_WAIT_FOR_BUFFER FILE_PIPE_WAIT_FOR_BUFFER
typedef struct _FILE_POSITION_INFORMATION FILE_POSITION_INFORMATION
typedef struct _FILE_PREFETCH FILE_PREFETCH
typedef struct _FILE_QUOTA_INFORMATION FILE_QUOTA_INFORMATION
typedef struct _FILE_RENAME_INFORMATION FILE_RENAME_INFORMATION
typedef struct _FILE_REPARSE_POINT_INFORMATION FILE_REPARSE_POINT_INFORMATION
typedef union _FILE_SEGMENT_ELEMENT FILE_SEGMENT_ELEMENT
typedef struct _FILE_STANDARD_INFORMATION FILE_STANDARD_INFORMATION
typedef struct _FILE_STREAM_INFORMATION FILE_STREAM_INFORMATION
typedef struct _FILE_TRACKING_INFORMATION FILE_TRACKING_INFORMATION
typedef struct _FILE_VALID_DATA_LENGTH_INFORMATION FILE_VALID_DATA_LENGTH_INFORMATION
typedef struct _FILESYSTEM_STATISTICS FILESYSTEM_STATISTICS
typedef enum _FSINFOCLASS FS_INFORMATION_CLASS
typedef struct _FSCTL_QUERY_FAT_BPB_BUFFER FSCTL_QUERY_FAT_BPB_BUFFER
typedef enum _INTERFACE_TYPE INTERFACE_TYPE
typedef struct _IO_COMPLETION_BASIC_INFORMATION IO_COMPLETION_BASIC_INFORMATION
typedef enum _IO_COMPLETION_INFORMATION_CLASS IO_COMPLETION_INFORMATION_CLASS
typedef struct _IO_STATUS_BLOCK IO_STATUS_BLOCK
typedef IN PIO_STATUS_BLOCK IoStatusBlock
Definition at line 477 of file ntioapi.h.
typedef struct _LINK_TRACKING_INFORMATION LINK_TRACKING_INFORMATION
typedef enum _LINK_TRACKING_INFORMATION_TYPE LINK_TRACKING_INFORMATION_TYPE
typedef struct _NTFS_STATISTICS NTFS_STATISTICS
typedef struct _PATHNAME_BUFFER PATHNAME_BUFFER
typedef enum _BUS_DATA_TYPE * PBUS_DATA_TYPE
typedef enum _DMA_SPEED * PDMA_SPEED
typedef enum _DMA_WIDTH * PDMA_WIDTH
typedef struct _FAT_STATISTICS * PFAT_STATISTICS
typedef struct _FILE_ACCESS_INFORMATION * PFILE_ACCESS_INFORMATION
typedef struct _FILE_ALIGNMENT_INFORMATION * PFILE_ALIGNMENT_INFORMATION
typedef struct _FILE_ALL_INFORMATION * PFILE_ALL_INFORMATION
typedef struct _FILE_ALLOCATION_INFORMATION * PFILE_ALLOCATION_INFORMATION
typedef struct _FILE_ATTRIBUTE_TAG_INFORMATION * PFILE_ATTRIBUTE_TAG_INFORMATION
typedef struct _FILE_BASIC_INFORMATION * PFILE_BASIC_INFORMATION
typedef struct _FILE_BOTH_DIR_INFORMATION * PFILE_BOTH_DIR_INFORMATION
typedef struct _FILE_COMPLETION_INFORMATION * PFILE_COMPLETION_INFORMATION
typedef struct _FILE_COMPRESSION_INFORMATION * PFILE_COMPRESSION_INFORMATION
typedef struct _FILE_DIRECTORY_INFORMATION * PFILE_DIRECTORY_INFORMATION
typedef struct _FILE_DISPOSITION_INFORMATION * PFILE_DISPOSITION_INFORMATION
typedef struct _FILE_EA_INFORMATION * PFILE_EA_INFORMATION
typedef struct _FILE_END_OF_FILE_INFORMATION * PFILE_END_OF_FILE_INFORMATION
typedef struct _FILE_FS_ATTRIBUTE_INFORMATION * PFILE_FS_ATTRIBUTE_INFORMATION
typedef struct _FILE_FS_CONTROL_INFORMATION * PFILE_FS_CONTROL_INFORMATION
typedef struct _FILE_FS_DEVICE_INFORMATION * PFILE_FS_DEVICE_INFORMATION
typedef struct _FILE_FS_DRIVER_PATH_INFORMATION * PFILE_FS_DRIVER_PATH_INFORMATION
typedef struct _FILE_FS_FULL_SIZE_INFORMATION * PFILE_FS_FULL_SIZE_INFORMATION
typedef struct _FILE_FS_LABEL_INFORMATION * PFILE_FS_LABEL_INFORMATION
typedef struct _FILE_FS_OBJECTID_INFORMATION * PFILE_FS_OBJECTID_INFORMATION
typedef struct _FILE_FS_SIZE_INFORMATION * PFILE_FS_SIZE_INFORMATION
typedef struct _FILE_FS_VOLUME_INFORMATION * PFILE_FS_VOLUME_INFORMATION
typedef struct _FILE_FULL_DIR_INFORMATION * PFILE_FULL_DIR_INFORMATION
typedef struct _FILE_FULL_EA_INFORMATION * PFILE_FULL_EA_INFORMATION
typedef struct _FILE_GET_EA_INFORMATION * PFILE_GET_EA_INFORMATION
typedef struct _FILE_GET_QUOTA_INFORMATION * PFILE_GET_QUOTA_INFORMATION
typedef struct _FILE_ID_BOTH_DIR_INFORMATION * PFILE_ID_BOTH_DIR_INFORMATION
typedef struct _FILE_ID_FULL_DIR_INFORMATION * PFILE_ID_FULL_DIR_INFORMATION
typedef enum _FILE_INFORMATION_CLASS * PFILE_INFORMATION_CLASS
typedef struct _FILE_INTERNAL_INFORMATION * PFILE_INTERNAL_INFORMATION
typedef struct _FILE_LINK_INFORMATION * PFILE_LINK_INFORMATION
typedef struct _FILE_MAILSLOT_PEEK_BUFFER * PFILE_MAILSLOT_PEEK_BUFFER
typedef struct _FILE_MAILSLOT_QUERY_INFORMATION * PFILE_MAILSLOT_QUERY_INFORMATION
typedef struct _FILE_MAILSLOT_SET_INFORMATION * PFILE_MAILSLOT_SET_INFORMATION
typedef struct _FILE_MODE_INFORMATION * PFILE_MODE_INFORMATION
typedef struct _FILE_MOVE_CLUSTER_INFORMATION * PFILE_MOVE_CLUSTER_INFORMATION
typedef struct _FILE_NAME_INFORMATION * PFILE_NAME_INFORMATION
typedef struct _FILE_NAMES_INFORMATION * PFILE_NAMES_INFORMATION
typedef struct _FILE_NETWORK_OPEN_INFORMATION * PFILE_NETWORK_OPEN_INFORMATION
typedef struct _FILE_NOTIFY_INFORMATION * PFILE_NOTIFY_INFORMATION
typedef struct _FILE_OBJECTID_INFORMATION * PFILE_OBJECTID_INFORMATION
typedef struct _FILE_PIPE_ASSIGN_EVENT_BUFFER * PFILE_PIPE_ASSIGN_EVENT_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER * PFILE_PIPE_CLIENT_PROCESS_BUFFER
typedef struct _FILE_PIPE_CLIENT_PROCESS_BUFFER_EX * PFILE_PIPE_CLIENT_PROCESS_BUFFER_EX
typedef struct _FILE_PIPE_EVENT_BUFFER * PFILE_PIPE_EVENT_BUFFER
typedef struct _FILE_PIPE_INFORMATION * PFILE_PIPE_INFORMATION
typedef struct _FILE_PIPE_LOCAL_INFORMATION * PFILE_PIPE_LOCAL_INFORMATION
typedef struct _FILE_PIPE_PEEK_BUFFER * PFILE_PIPE_PEEK_BUFFER
typedef struct _FILE_PIPE_REMOTE_INFORMATION * PFILE_PIPE_REMOTE_INFORMATION
typedef struct _FILE_PIPE_WAIT_FOR_BUFFER * PFILE_PIPE_WAIT_FOR_BUFFER
typedef struct _FILE_POSITION_INFORMATION * PFILE_POSITION_INFORMATION
typedef struct _FILE_PREFETCH * PFILE_PREFETCH
typedef struct _FILE_QUOTA_INFORMATION * PFILE_QUOTA_INFORMATION
typedef struct _FILE_RENAME_INFORMATION * PFILE_RENAME_INFORMATION
typedef struct _FILE_REPARSE_POINT_INFORMATION * PFILE_REPARSE_POINT_INFORMATION
typedef union _FILE_SEGMENT_ELEMENT * PFILE_SEGMENT_ELEMENT
typedef struct _FILE_STANDARD_INFORMATION * PFILE_STANDARD_INFORMATION
typedef struct _FILE_STREAM_INFORMATION * PFILE_STREAM_INFORMATION
typedef struct _FILE_TRACKING_INFORMATION * PFILE_TRACKING_INFORMATION
typedef struct _FILE_VALID_DATA_LENGTH_INFORMATION * PFILE_VALID_DATA_LENGTH_INFORMATION
typedef struct _FILESYSTEM_STATISTICS * PFILESYSTEM_STATISTICS
typedef enum _FSINFOCLASS * PFS_INFORMATION_CLASS
typedef struct _FSCTL_QUERY_FAT_BPB_BUFFER * PFSCTL_QUERY_FAT_BPB_BUFFER
typedef VOID(* PINTERFACE_DEREFERENCE) (PVOID Context)
Definition at line 3065 of file ntioapi.h.
typedef VOID(* PINTERFACE_REFERENCE) (PVOID Context)
Definition at line 3064 of file ntioapi.h.
typedef enum _INTERFACE_TYPE * PINTERFACE_TYPE
typedef struct _IO_COMPLETION_BASIC_INFORMATION * PIO_COMPLETION_BASIC_INFORMATION
typedef struct _IO_STATUS_BLOCK * PIO_STATUS_BLOCK
typedef struct _LINK_TRACKING_INFORMATION * PLINK_TRACKING_INFORMATION
typedef enum _LINK_TRACKING_INFORMATION_TYPE * PLINK_TRACKING_INFORMATION_TYPE
typedef struct _NTFS_STATISTICS * PNTFS_STATISTICS
typedef struct _PATHNAME_BUFFER * PPATHNAME_BUFFER
typedef struct _REMOTE_LINK_TRACKING_INFORMATION_ * PREMOTE_LINK_TRACKING_INFORMATION
typedef struct _REPARSE_DATA_BUFFER * PREPARSE_DATA_BUFFER
typedef struct _REPARSE_GUID_DATA_BUFFER * PREPARSE_GUID_DATA_BUFFER
typedef struct _REPARSE_POINT_INFORMATION * PREPARSE_POINT_INFORMATION
typedef struct _REMOTE_LINK_TRACKING_INFORMATION_ REMOTE_LINK_TRACKING_INFORMATION
typedef struct _REPARSE_DATA_BUFFER REPARSE_DATA_BUFFER
typedef struct _REPARSE_GUID_DATA_BUFFER REPARSE_GUID_DATA_BUFFER
typedef struct _REPARSE_POINT_INFORMATION REPARSE_POINT_INFORMATION
typedef IN PIO_STATUS_BLOCK IN ULONG Reserved
Definition at line 477 of file ntioapi.h.
Enumeration Type Documentation
enum _BUS_DATA_TYPE
Enumerator
ConfigurationSpaceUndefined
Cmos
EisaConfiguration
Pos
CbusConfiguration
PCIConfiguration
VMEConfiguration
NuBusConfiguration
PCMCIAConfiguration
MPIConfiguration
MPSAConfiguration
PNPISAConfiguration
SgiInternalConfiguration
MaximumBusDataType
Definition at line 3073 of file ntioapi.h.
enum _DMA_SPEED
Enumerator
Compatible
TypeA
TypeB
TypeC
TypeF
MaximumDmaSpeed
Definition at line 3050 of file ntioapi.h.
enum _DMA_WIDTH
Enumerator
Width8Bits
Width16Bits
Width32Bits
MaximumDmaWidth
Definition at line 3039 of file ntioapi.h.
enum _FILE_INFORMATION_CLASS
Enumerator
FileDirectoryInformation
FileFullDirectoryInformation
FileBothDirectoryInformation
FileBasicInformation
FileStandardInformation
FileInternalInformation
FileEaInformation
FileAccessInformation
FileNameInformation
FileRenameInformation
FileLinkInformation
FileNamesInformation
FileDispositionInformation
FilePositionInformation
FileFullEaInformation
FileModeInformation
FileAlignmentInformation
FileAllInformation
FileAllocationInformation
FileEndOfFileInformation
FileAlternateNameInformation
FileStreamInformation
FilePipeInformation
FilePipeLocalInformation
FilePipeRemoteInformation
FileMailslotQueryInformation
FileMailslotSetInformation
FileCompressionInformation
FileObjectIdInformation
FileCompletionInformation
FileMoveClusterInformation
FileQuotaInformation
FileReparsePointInformation
FileNetworkOpenInformation
FileAttributeTagInformation
FileTrackingInformation
FileIdBothDirectoryInformation
FileIdFullDirectoryInformation
FileValidDataLengthInformation
FileShortNameInformation
FileMaximumInformation
Definition at line 508 of file ntioapi.h.
enum _FSINFOCLASS
Enumerator
FileFsVolumeInformation
FileFsLabelInformation
FileFsSizeInformation
FileFsDeviceInformation
FileFsAttributeInformation
FileFsControlInformation
FileFsFullSizeInformation
FileFsObjectIdInformation
FileFsDriverPathInformation
FileFsMaximumInformation
Definition at line 952 of file ntioapi.h.
enum _INTERFACE_TYPE
Enumerator
InterfaceTypeUndefined
Internal
Isa
Eisa
MicroChannel
TurboChannel
PCIBus
VMEBus
NuBus
PCMCIABus
CBus
MPIBus
MPSABus
ProcessorInternal
InternalPowerBus
PNPISABus
PNPBus
MaximumInterfaceType
Definition at line 3014 of file ntioapi.h.
enum _IO_COMPLETION_INFORMATION_CLASS
Enumerator
IoCompletionBasicInformation
Definition at line 2940 of file ntioapi.h.
enum _LINK_TRACKING_INFORMATION_TYPE
Enumerator
NtfsLinkTrackingInformation
DfsLinkTrackingInformation
Definition at line 2905 of file ntioapi.h.
Function Documentation
NTSYSCALLAPI NTSTATUS NTAPI NtCancelIoFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 40 of file misc.c.
References APC_LEVEL, CONTAINING_RECORD, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LIST_ENTRY::Flink, IoCancelIrp(), IoFileObjectType, IopUpdateOtherOperationCount(), IRP, _ETHREAD::IrpList, KeDelayExecutionThread(), KeGetPreviousModeByThread, KeLowerIrql, KeRaiseIrql, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PIRP, ProbeForWriteIoStatus, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and VOID.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateFile (__out PHANDLE FileHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER AllocationSize, __in ULONG FileAttributes, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in_bcount_opt(EaLength) PVOID EaBuffer, __in ULONG EaLength)
Definition at line 28 of file create.c.
References CreateFileTypeNone, IoCreateFile(), NULL, and PAGED_CODE.
Referenced by RtlCreateSystemVolumeInformationFolder().
NTSYSCALLAPI NTSTATUS NTAPI NtCreateIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Count OPTIONAL)
Definition at line 45 of file complete.c.
References Count, except, ExSystemExceptionFilter(), Handle, IoCompletionObjectType, KeGetPreviousMode, KeInitializeQueue(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateMailslotFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CreateOptions, __in ULONG MailslotQuota, __in ULONG MaximumMessageSize, __in PLARGE_INTEGER ReadTimeout)
Definition at line 276 of file create.c.
References ARGUMENT_PRESENT, CreateFileTypeMailslot, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FILE_CREATE, FILE_SHARE_READ, FILE_SHARE_WRITE, IoCreateFile(), KeGetPreviousMode, KernelMode, _MAILSLOT_CREATE_PARAMETERS::MailslotQuota, _MAILSLOT_CREATE_PARAMETERS::MaximumMessageSize, NULL, PAGED_CODE, ProbeForReadSmallStructure, _MAILSLOT_CREATE_PARAMETERS::ReadTimeout, _MAILSLOT_CREATE_PARAMETERS::TimeoutSpecified, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateNamedPipeFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in ULONG NamedPipeType, __in ULONG ReadMode, __in ULONG CompletionMode, __in ULONG MaximumInstances, __in ULONG InboundQuota, __in ULONG OutboundQuota, __in_opt PLARGE_INTEGER DefaultTimeout)
Definition at line 116 of file create.c.
References ARGUMENT_PRESENT, _NAMED_PIPE_CREATE_PARAMETERS::CompletionMode, CreateFileTypeNamedPipe, _NAMED_PIPE_CREATE_PARAMETERS::DefaultTimeout, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _NAMED_PIPE_CREATE_PARAMETERS::InboundQuota, IoCreateFile(), KeGetPreviousMode, KernelMode, _NAMED_PIPE_CREATE_PARAMETERS::MaximumInstances, _NAMED_PIPE_CREATE_PARAMETERS::NamedPipeType, NULL, _NAMED_PIPE_CREATE_PARAMETERS::OutboundQuota, PAGED_CODE, ProbeForReadSmallStructure, _NAMED_PIPE_CREATE_PARAMETERS::ReadMode, _NAMED_PIPE_CREATE_PARAMETERS::TimeoutSpecified, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteFile (__in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 291 of file misc.c.
References _OPEN_PACKET::CreateOptions, DELETE, _OPEN_PACKET::DeleteOnly, _OPEN_PACKET::Disposition, FALSE, FILE_DELETE_ON_CLOSE, FILE_OPEN, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, IO_TYPE_OPEN_PACKET, IopUpdateOtherOperationCount(), KeGetPreviousMode, _OPEN_PACKET::LocalFileObject, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, PAGED_CODE, _OPEN_PACKET::ParseCheck, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, _OPEN_PACKET::TraversedMountPoint, TRUE, and _OPEN_PACKET::Type.
NTSYSCALLAPI NTSTATUS NTAPI NtDeviceIoControlFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG IoControlCode, __in_bcount_opt(InputBufferLength) PVOID InputBuffer, __in ULONG InputBufferLength, __out_bcount_opt(OutputBufferLength) PVOID OutputBuffer, __in ULONG OutputBufferLength)
Definition at line 25 of file devctrl.c.
References IopXxxControlFile(), and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtFlushBuffersFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 380 of file misc.c.
References _FILE_OBJECT::Event, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FILE_APPEND_DATA, FILE_WRITE_DATA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_NAMED_PIPE, FO_SYNCHRONOUS_IO, _OBJECT_HANDLE_INFORMATION::GrantedAccess, IoAllocateIrp(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IRP_MJ_FLUSH_BUFFERS, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, PIRP, ProbeForWriteIoStatus, PsGetCurrentThread(), SeComputeGrantedAccesses, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtFsControlFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG FsControlCode, __in_bcount_opt(InputBufferLength) PVOID InputBuffer, __in ULONG InputBufferLength, __out_bcount_opt(OutputBufferLength) PVOID OutputBuffer, __in ULONG OutputBufferLength)
Definition at line 25 of file fsctrl.c.
References FALSE, and IopXxxControlFile().
Referenced by FsRtlpRegisterProviderWithMUP().
NTSYSCALLAPI NTSTATUS NTAPI NtLoadDriver (__in PUNICODE_STRING DriverServiceName)
Definition at line 27 of file loadunld.c.
References _UNICODE_STRING::Buffer, DelayedWorkQueue, _LOAD_PACKET::DriverObject, _LOAD_PACKET::DriverServiceName, _LOAD_PACKET::Event, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), FALSE, _LOAD_PACKET::FinalStatus, IopLoadUnloadDriver(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, NotificationEvent, NULL, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, RtlCopyMemory, SeLoadDriverPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, _ETHREAD::Tcb, UserRequest, and _LOAD_PACKET::WorkQueueItem.
NTSYSCALLAPI NTSTATUS NTAPI NtLockFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER Length, __in ULONG Key, __in BOOLEAN FailImmediately, __in BOOLEAN ExclusiveLock)
Definition at line 26 of file lock.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, FALSE, _FAST_IO_DISPATCH::FastIoLock, FILE_READ_DATA, FILE_WRITE_DATA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _IO_STATUS_BLOCK::Information, IoAllocateIrp(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopMarkApcRoutineIfAsyncronousIo32, IopSynchronousServiceTail(), IoSetIoCompletion(), IRP_MJ_LOCK_CONTROL, IRP_MN_LOCK, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, KeSetEvent(), _IO_COMPLETION_CONTEXT::Key, _FILE_OBJECT::LockOperation, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _IO_COMPLETION_CONTEXT::Port, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), SeComputeGrantedAccesses, SL_EXCLUSIVE_LOCK, SL_FAIL_IMMEDIATELY, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtNotifyChangeDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in ULONG CompletionFilter, __in BOOLEAN WatchTree)
Definition at line 859 of file dir.c.
References ARGUMENT_PRESENT, _FILE_OBJECT::CompletionContext, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, FILE_LIST_DIRECTORY, FILE_NOTIFY_VALID_MASK, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopMarkApcRoutineIfAsyncronousIo32, IopSynchronousServiceTail(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_DIRECTORY_CONTROL, IRP_MN_NOTIFY_CHANGE_DIRECTORY, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, MmProbeAndLockPages(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), SL_WATCH_TREE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenFile (__out PHANDLE FileHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG ShareAccess, __in ULONG OpenOptions)
Definition at line 25 of file open.c.
References CreateFileTypeNone, FILE_OPEN, IoCreateFile(), NULL, and PAGED_CODE.
Referenced by RtlpSysVolTakeOwnership().
NTSYSCALLAPI NTSTATUS NTAPI NtOpenIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 172 of file complete.c.
References except, ExSystemExceptionFilter(), Handle, IoCompletionObjectType, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_BASIC_INFORMATION FileInformation)
Definition at line 625 of file misc.c.
References _OPEN_PACKET::BasicInformation, _OPEN_PACKET::CreateOptions, _OPEN_PACKET::Disposition, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_REPARSE_POINT, FILE_READ_ATTRIBUTES, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, IO_TYPE_OPEN_PACKET, IopUpdateOtherOperationCount(), KeGetPreviousMode, KernelMode, _OPEN_PACKET::LocalFileObject, _OPEN_PACKET::NetworkInformation, NT_SUCCESS, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, PAGED_CODE, _OPEN_PACKET::ParseCheck, ProbeForWriteSmallStructure(), _OPEN_PACKET::QueryOnly, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, _OPEN_PACKET::TraversedMountPoint, TRUE, _OPEN_PACKET::Type, and ZwClose().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass, __in BOOLEAN ReturnSingleEntry, __in_opt PUNICODE_STRING FileName, __in BOOLEAN RestartScan)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(EaListLength) PVOID EaList, __in ULONG EaListLength, __in_opt PULONG EaIndex OPTIONAL, __in BOOLEAN RestartScan)
Definition at line 26 of file qsea.c.
References ARGUMENT_PRESENT, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_GET_EA_INFORMATION::EaNameLength, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FIELD_OFFSET, FILE_READ_EA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, GET_OFFSET_LENGTH, IoAllocateIrp(), IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_QUERY_EA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), _FILE_GET_EA_INFORMATION::NextEntryOffset, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUlong, ProbeForRead, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, SL_INDEX_SPECIFIED, SL_RESTART_SCAN, SL_RETURN_SINGLE_ENTRY, STATUS_EA_LIST_INCONSISTENT, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryFullAttributesFile (__in POBJECT_ATTRIBUTES ObjectAttributes, __out PFILE_NETWORK_OPEN_INFORMATION FileInformation)
Definition at line 749 of file misc.c.
References _OPEN_PACKET::CreateOptions, _OPEN_PACKET::Disposition, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_REPARSE_POINT, FILE_READ_ATTRIBUTES, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, _OPEN_PACKET::FullAttributes, IO_TYPE_OPEN_PACKET, IopUpdateOtherOperationCount(), KeGetPreviousMode, KernelMode, _OPEN_PACKET::LocalFileObject, _OPEN_PACKET::NetworkInformation, NT_SUCCESS, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, PAGED_CODE, _OPEN_PACKET::ParseCheck, ProbeForWriteSmallStructure(), _OPEN_PACKET::QueryOnly, RtlCopyMemory, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, _OPEN_PACKET::TraversedMountPoint, TRUE, _OPEN_PACKET::Type, and ZwClose().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
Definition at line 91 of file qsinfo.c.
References _FILE_ACCESS_INFORMATION::AccessFlags, _FILE_ALL_INFORMATION::AccessInformation, _FILE_ALL_INFORMATION::AlignmentInformation, _FILE_ALIGNMENT_INFORMATION::AlignmentRequirement, APC_LEVEL, _FILE_POSITION_INFORMATION::CurrentByteOffset, _FILE_OBJECT::CurrentByteOffset, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, _FAST_IO_DISPATCH::FastIoQueryBasicInfo, _FAST_IO_DISPATCH::FastIoQueryStandardInfo, FileAccessInformation, FileAlignmentInformation, FileAllInformation, FileBasicInformation, FileMaximumInformation, FileModeInformation, _IO_STACK_LOCATION::FileObject, FilePositionInformation, FileStandardInformation, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_SYNCHRONOUS_IO, _OBJECT_HANDLE_INFORMATION::GrantedAccess, IoAllocateIrp(), IoCallDriver(), IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopCompleteRequest(), IopExceptionCleanup(), IopGetModeInformation(), IopQueryOperationAccess, IopQueryOperationLength, IopQuerySetAlignmentRequirement, IopQueueThreadIrp(), IopReleaseFileObjectLock, IopUpdateOtherOperationCount(), IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_QUERY_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _FILE_MODE_INFORMATION::Mode, _FILE_ALL_INFORMATION::ModeInformation, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_PENDING, STATUS_SUCCESS, STATUS_USER_APC, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
Referenced by HvpDoWriteHive().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryIoCompletion (__in HANDLE IoCompletionHandle, __in IO_COMPLETION_INFORMATION_CLASS IoCompletionInformationClass, __out_bcount(IoCompletionInformation) PVOID IoCompletionInformation, __in ULONG IoCompletionInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(SidListLength) PVOID SidList, __in ULONG SidListLength, __in_opt PSID StartSid, __in BOOLEAN RestartScan)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryVolumeInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FsInformation, __in ULONG Length, __in FS_INFORMATION_CLASS FsInformationClass)
Definition at line 28 of file qsfs.c.
References _FILE_FS_DEVICE_INFORMATION::Characteristics, _FILE_OBJECT::DeviceObject, _FILE_FS_DEVICE_INFORMATION::DeviceType, _FILE_FS_DRIVER_PATH_INFORMATION::DriverInPath, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FILE_DEVICE_IS_MOUNTED, FILE_DEVICE_NETWORK_FILE_SYSTEM, FileFsDeviceInformation, FileFsDriverPathInformation, FileFsMaximumInformation, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopGetDriverPathInformation(), IopGetMountFlag(), IopQueryFsOperationAccess, IopQueryFsOperationLength, IopQuerySetFsAlignmentRequirement, IopReleaseFileObjectLock, IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtReadFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Definition at line 31 of file read.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::CurrentByteOffset, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, _FAST_IO_DISPATCH::FastIoRead, FILE_READ_DATA, FILE_USE_FILE_POINTER_POSITION, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_MAILSLOT, FO_NAMED_PIPE, FO_NO_INTERMEDIATE_BUFFERING, FO_SYNCHRONOUS_IO, _LARGE_INTEGER::HighPart, _IO_STATUS_BLOCK::Information, IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopCacheHitIncrement, IopExceptionCleanup(), IopExceptionFilter(), IopMarkApcRoutineIfAsyncronousIo32, IopReleaseFileObjectLock, IopSynchronousServiceTail(), IopUpdateReadOperationCount(), IopUpdateReadTransferCount(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_READ, IRP_NOCACHE, IRP_READ_OPERATION, KeBoostPriorityThread(), KeClearEvent(), KeGetPreviousModeByThread, KernelMode, KeSetEvent(), _LARGE_INTEGER::LowPart, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_OBJECT::PrivateCacheMap, ProbeAndReadUlong, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), ReadTransfer, _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_END_OF_FILE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtReadFileScatter (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PFILE_SEGMENT_ELEMENT SegmentArray, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Definition at line 737 of file read.c.
References ARGUMENT_PRESENT, ASSERT, BYTES_TO_PAGES, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::CurrentByteOffset, DO_BUFFERED_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExFreePool(), ExRaiseStatus(), FALSE, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DFS, FILE_DEVICE_DFS_VOLUME, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_READ_DATA, FILE_USE_FILE_POINTER_POSITION, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_MAILSLOT, FO_NAMED_PIPE, FO_NO_INTERMEDIATE_BUFFERING, FO_SYNCHRONOUS_IO, _LARGE_INTEGER::HighPart, IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopExceptionFilter(), IopMarkApcRoutineIfAsyncronousIo32, IopReleaseFileObjectLock, IopSynchronousServiceTail(), IoWriteAccess, IRP_DEFER_IO_COMPLETION, IRP_MJ_READ, IRP_NOCACHE, IRP_READ_OPERATION, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, _LARGE_INTEGER::LowPart, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockSelectedPages(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SIZE, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUlong, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentProcess(), PsGetCurrentThread(), Ptr64ToPtr(), ReadTransfer, RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and TYPE_ALIGNMENT.
NTSYSCALLAPI NTSTATUS NTAPI NtRemoveIoCompletion (__in HANDLE IoCompletionHandle, __out PVOID * KeyContext, __out PVOID * ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER Timeout)
Definition at line 479 of file complete.c.
References _IOP_MINI_COMPLETION_PACKET::ApcContext, ARGUMENT_PRESENT, CONTAINING_RECORD, except, ExSystemExceptionFilter(), _IO_STATUS_BLOCK::Information, IO_COMPLETION_MODIFY_STATE, IoCompletionObjectType, IoFreeIrp(), IopCompletionPacketIrp, IopFreeMiniPacket(), _IOP_MINI_COMPLETION_PACKET::IoStatus, _IOP_MINI_COMPLETION_PACKET::IoStatusInformation, IRP, KeGetPreviousMode, KeRemoveQueue(), KernelMode, _IOP_MINI_COMPLETION_PACKET::KeyContext, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _IOP_MINI_COMPLETION_PACKET::PacketType, PIRP, ProbeAndReadLargeInteger, ProbeForWriteIoStatus, ProbeForWriteUlong_ptr, Status, _IO_STATUS_BLOCK::Status, STATUS_SUCCESS, STATUS_TIMEOUT, and STATUS_USER_APC.
NTSYSCALLAPI NTSTATUS NTAPI NtSetEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
Definition at line 645 of file qsea.c.
References DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FILE_WRITE_EA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoCheckEaBufferValidity(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoReadAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_MJ_SET_EA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
Definition at line 836 of file qsinfo.c.
References APC_LEVEL, ASSERT, _FILE_OBJECT::CompletionContext, _FILE_POSITION_INFORMATION::CurrentByteOffset, _FILE_OBJECT::CurrentByteOffset, _FILE_DISPOSITION_INFORMATION::DeleteFile, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExRaiseStatus(), FALSE, FIELD_OFFSET, FILE_SEQUENTIAL_ONLY, FILE_VALID_SET_FLAGS, FILE_WRITE_THROUGH, FileAllocationInformation, FileCompletionInformation, FileDispositionInformation, FileEndOfFileInformation, FileLinkInformation, FileMaximumInformation, FileModeInformation, FileMoveClusterInformation, _FILE_NAME_INFORMATION::FileName, _FILE_RENAME_INFORMATION::FileName, _FILE_NAME_INFORMATION::FileNameLength, _FILE_RENAME_INFORMATION::FileNameLength, _IO_STACK_LOCATION::FileObject, FilePositionInformation, FileRenameInformation, FileShortNameInformation, FileTrackingInformation, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_NO_INTERMEDIATE_BUFFERING, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, FSIO_A, FSIO_NA, _LARGE_INTEGER::HighPart, InterlockedCompareExchangePointer, IO_COMPLETION_MODIFY_STATE, IoAllocateIrp(), IoCallDriver(), IoCompletionObjectType, IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopCompleteRequest(), IopExceptionCleanup(), IopOpenLinkOrRenameTarget(), IopQuerySetAlignmentRequirement, IopQueueThreadIrp(), IopReleaseFileObjectLock, IopSetOperationAccess, IopSetOperationLength, IopTrackLink(), IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_MJ_SET_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _FILE_COMPLETION_INFORMATION::Key, _IO_COMPLETION_CONTEXT::Key, _LARGE_INTEGER::LowPart, _IO_STACK_LOCATION::MajorFunction, _FILE_MODE_INFORMATION::Mode, NonPagedPool, NOTHING, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_NAME_PATH_SEPARATOR, ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_COMPLETION_INFORMATION::Port, _IO_COMPLETION_CONTEXT::Port, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_PORT_ALREADY_SET, STATUS_SUCCESS, STATUS_USER_APC, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetIoCompletion (__in HANDLE IoCompletionHandle, __in PVOID KeyContext, __in_opt PVOID ApcContext, __in NTSTATUS IoStatus, __in ULONG_PTR IoStatusInformation)
Definition at line 411 of file complete.c.
References IO_COMPLETION_MODIFY_STATE, IoCompletionObjectType, IoSetIoCompletion(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, Status, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
Definition at line 609 of file qsquota.c.
References FALSE, IopSetEaOrQuotaInformationFile(), and PAGED_CODE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetVolumeInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID FsInformation, __in ULONG Length, __in FS_INFORMATION_CLASS FsInformationClass)
Definition at line 534 of file qsfs.c.
References ASSERT, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Event, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FIELD_OFFSET, FileFsLabelInformation, FileFsMaximumInformation, _TARGET_DEVICE_CUSTOM_NOTIFICATION::FileObject, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoGetRelatedTargetDevice(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopQuerySetFsAlignmentRequirement, IopSetFsOperationAccess, IopSetFsOperationLength, IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoReportTargetDeviceChange(), IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_MJ_SET_VOLUME_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, _TARGET_DEVICE_CUSTOM_NOTIFICATION::NameBufferOffset, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), RtlCopyMemory, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Size, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, SynchronizationEvent, _ETHREAD::Tcb, TRUE, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Version, and _FILE_FS_LABEL_INFORMATION::VolumeLabelLength.
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadDriver (__in PUNICODE_STRING DriverServiceName)
Definition at line 247 of file loadunld.c.
References FALSE, and IopUnloadDriver().
NTSYSCALLAPI NTSTATUS NTAPI NtUnlockFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER Length, __in ULONG Key)
Definition at line 475 of file lock.c.
References _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _FAST_IO_DISPATCH::FastIoUnlockSingle, FILE_READ_DATA, FILE_WRITE_DATA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_SYNCHRONOUS_IO, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _IO_STATUS_BLOCK::Information, IoAllocateIrp(), IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IRP_MJ_LOCK_CONTROL, IRP_MN_UNLOCK_SINGLE, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), SeComputeGrantedAccesses, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtWriteFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Definition at line 25 of file write.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::CurrentByteOffset, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, _FAST_IO_DISPATCH::FastIoWrite, FILE_APPEND_DATA, FILE_USE_FILE_POINTER_POSITION, FILE_WRITE_DATA, FILE_WRITE_TO_END_OF_FILE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_MAILSLOT, FO_NAMED_PIPE, FO_NO_INTERMEDIATE_BUFFERING, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _LARGE_INTEGER::HighPart, _IO_STATUS_BLOCK::Information, IoAllocateMdl(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopExceptionFilter(), IopMarkApcRoutineIfAsyncronousIo32, IopReleaseFileObjectLock, IopSynchronousServiceTail(), IopUpdateWriteOperationCount(), IopUpdateWriteTransferCount(), IoReadAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_MJ_WRITE, IRP_NOCACHE, IRP_WRITE_OPERATION, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, KeSetEvent(), _LARGE_INTEGER::LowPart, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_OBJECT::PrivateCacheMap, ProbeAndReadUlong, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, SeComputeGrantedAccesses, SL_WRITE_THROUGH, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and WriteTransfer.
NTSYSCALLAPI NTSTATUS NTAPI NtWriteFileGather (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PFILE_SEGMENT_ELEMENT SegmentArray, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Definition at line 788 of file write.c.
References ARGUMENT_PRESENT, ASSERT, BYTES_TO_PAGES, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::CurrentByteOffset, DO_BUFFERED_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExFreePool(), ExRaiseStatus(), FALSE, FILE_APPEND_DATA, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DFS, FILE_DEVICE_DFS_VOLUME, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_USE_FILE_POINTER_POSITION, FILE_WRITE_DATA, FILE_WRITE_TO_END_OF_FILE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_MAILSLOT, FO_NAMED_PIPE, FO_NO_INTERMEDIATE_BUFFERING, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _LARGE_INTEGER::HighPart, IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopExceptionFilter(), IopMarkApcRoutineIfAsyncronousIo32, IopReleaseFileObjectLock, IopSynchronousServiceTail(), IoReadAccess, IRP_DEFER_IO_COMPLETION, IRP_MJ_WRITE, IRP_NOCACHE, IRP_WRITE_OPERATION, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, _LARGE_INTEGER::LowPart, MmProbeAndLockSelectedPages(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SIZE, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUlong, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentProcess(), PsGetCurrentThread(), Ptr64ToPtr(), RtlCopyMemory, SeComputeGrantedAccesses, SL_WRITE_THROUGH, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, TYPE_ALIGNMENT, and WriteTransfer.
typedef VOID (NTAPI * PIO_APC_ROUTINE)