Windows Research Kernel v1.2: C:/Windows Research Kernel/se/tokenadj.c File Reference
tokenadj.c File Reference
#include "pch.h"
Functions
NTSTATUS NtAdjustGroupsToken (__in HANDLE TokenHandle, __in BOOLEAN ResetToDefault, __in PTOKEN_GROUPS NewState, __in ULONG BufferLength, __out_bcount_part_opt(BufferLength,*ReturnLength) PTOKEN_GROUPS PreviousState, __out PULONG ReturnLength)
NTSTATUS NtAdjustPrivilegesToken (__in HANDLE TokenHandle, __in BOOLEAN DisableAllPrivileges, __in_opt PTOKEN_PRIVILEGES NewState, __in ULONG BufferLength, __out_bcount_part_opt(BufferLength,*ReturnLength) PTOKEN_PRIVILEGES PreviousState, __out_opt PULONG ReturnLength)
NTSTATUS SepAdjustGroups (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN ResetToDefault, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_GROUPS PreviousState OPTIONAL, OUT PSID SidBuffer OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
NTSTATUS SepAdjustPrivileges (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN DisableAllPrivileges, IN ULONG PrivilegeCount OPTIONAL, IN PLUID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_PRIVILEGES PreviousState OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
Function Documentation
NTSTATUS NtAdjustGroupsToken (__in HANDLE TokenHandle, __in BOOLEAN ResetToDefault, __in PTOKEN_GROUPS NewState, __in ULONG BufferLength, __out_bcount_part_opt(BufferLength,*ReturnLength) PTOKEN_GROUPS PreviousState, __out PULONG ReturnLength)
Definition at line 435 of file tokenadj.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, LongAlignPtr, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteUlong, SeCaptureSidAndAttributesArray(), SepAcquireTokenWriteLock, SepAdjustGroups(), SepReleaseTokenWriteLock, SeReleaseSidAndAttributesArray(), SeTokenObjectType, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, TOKEN_ADJUST_GROUPS, TOKEN_QUERY, and TRUE.
NTSTATUS NtAdjustPrivilegesToken (__in HANDLE TokenHandle, __in BOOLEAN DisableAllPrivileges, __in_opt PTOKEN_PRIVILEGES NewState, __in ULONG BufferLength, __out_bcount_part_opt(BufferLength,*ReturnLength) PTOKEN_PRIVILEGES PreviousState, __out_opt PULONG ReturnLength)
Definition at line 41 of file tokenadj.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, ProbeForRead, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteUlong, RtlZeroMemory, SeCaptureLuidAndAttributesArray(), SepAcquireTokenWriteLock, SepAdjustPrivileges(), SepReleaseTokenWriteLock, SeReleaseLuidAndAttributesArray(), SeTokenObjectType, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, TOKEN_ADJUST_PRIVILEGES, TOKEN_QUERY, and TRUE.
NTSTATUS SepAdjustGroups (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN ResetToDefault, IN ULONG GroupCount , IN PSID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_GROUPS PreviousState OPTIONAL, OUT PSID SidBuffer OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
Definition at line 1170 of file tokenadj.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, _SID_AND_ATTRIBUTES::Attributes, FALSE, LongAlignSize, PAGED_CODE, RtlCopySid(), RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SE_GROUP_USE_FOR_DENY_ONLY, SeLengthSid, SepArrayGroupAttributes, SepTokenGroupAttributes, _SID_AND_ATTRIBUTES::Sid, STATUS_CANT_DISABLE_MANDATORY, STATUS_CANT_ENABLE_DENY_ONLY, STATUS_NOT_ALL_ASSIGNED, STATUS_SUCCESS, and TRUE.
Referenced by NtAdjustGroupsToken().
NTSTATUS SepAdjustPrivileges (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN DisableAllPrivileges, IN ULONG PrivilegeCount OPTIONAL, IN PLUID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_PRIVILEGES PreviousState OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
Definition at line 820 of file tokenadj.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, FALSE, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, RtlEqualLuid, SE_PRIVILEGE_ENABLED, SE_PRIVILEGE_REMOVED, SeBackupPrivilege, SeChangeNotifyPrivilege, SeImpersonatePrivilege, SepArrayPrivilegeAttributes, SepTokenPrivilegeAttributes, SeRestorePrivilege, STATUS_NOT_ALL_ASSIGNED, STATUS_SUCCESS, TOKEN_HAS_BACKUP_PRIVILEGE, TOKEN_HAS_IMPERSONATE_PRIVILEGE, TOKEN_HAS_RESTORE_PRIVILEGE, TOKEN_HAS_TRAVERSE_PRIVILEGE, and TRUE.
Referenced by NtAdjustPrivilegesToken().