Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/amd64/context.c File Reference
context.c File Reference
#include "ntrtlp.h"
Functions
VOID RtlInitializeContext (IN HANDLE Process, OUT PCONTEXT Context, IN PVOID Parameter OPTIONAL, IN PVOID InitialPc OPTIONAL, IN PVOID InitialSp OPTIONAL)
NTSTATUS RtlRemoteCall (HANDLE Process, HANDLE Thread, PVOID CallSite, ULONG ArgumentCount, PULONG_PTR Arguments, BOOLEAN PassContext, BOOLEAN AlreadySuspended)
Function Documentation
VOID RtlInitializeContext (IN HANDLE Process, OUT PCONTEXT Context, IN PVOID Parameter OPTIONAL, IN PVOID InitialPc OPTIONAL, IN PVOID InitialSp OPTIONAL)
Definition at line 27 of file context.c.
References CONTEXT_FULL, EFLAGS_IF_MASK, RTL_PAGED_CODE, RtlRaiseStatus(), RtlZeroMemory, and STATUS_BAD_INITIAL_STACK.
NTSTATUS RtlRemoteCall (HANDLE Process, HANDLE Thread, PVOID CallSite, ULONG ArgumentCount, PULONG_PTR Arguments, BOOLEAN PassContext, BOOLEAN AlreadySuspended)
Definition at line 137 of file context.c.
References CONTEXT_FULL, _CONTEXT::ContextFlags, FALSE, Index, NT_SUCCESS, NtGetContextThread(), NtResumeThread(), NtSetContextThread(), NtSuspendThread(), NtWriteVirtualMemory(), NULL, RTL_PAGED_CODE, Status, STATUS_ALERTED, and STATUS_INVALID_PARAMETER.