Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmp.h File Reference
cmp.h File Reference
#include "ntos.h"
#include "hive.h"
#include "wchar.h"
#include "zwapi.h"
#include <stdio.h>
#include <profiles.h>
#include "cmpbug.h"
#include "kddll.h"
#include "cmdata.h"
Data Structures
struct _BOOT_DRIVER_NODE
struct _CM_ASYNC_KERNEL_POST_BLOCK
struct _CM_ASYNC_USER_POST_BLOCK
struct _CM_CELL_REMAP_BLOCK
struct _CM_DELAY_ALLOC
struct _CM_DELAYED_CLOSE_ENTRY
struct _CM_HARDWARE_PROFILE
struct _CM_HARDWARE_PROFILE_ACPI_ALIAS
struct _CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST
struct _CM_HARDWARE_PROFILE_ALIAS
struct _CM_HARDWARE_PROFILE_ALIAS_LIST
struct _CM_HARDWARE_PROFILE_LIST
struct _CM_KCB_REMAP_BLOCK
struct _CM_KEY_BODY
struct _CM_KNODE_REMAP_BLOCK
struct _CM_NOTIFY_BLOCK
struct _CM_PARSE_CONTEXT
struct _CM_POST_BLOCK
union _CM_POST_BLOCK_UNION
struct _CM_POST_KEY_BODY
struct _CM_SYNC_POST_BLOCK
struct _CM_VIEW_OF_FILE
struct _CM_WRITE_BLOCK
struct _CMHIVE
struct _HIVE_LIST_ENTRY
struct _QUERY_OPEN_SUBKEYS_CONTEXT
struct CMP_CHECK_REGISTRY_STACK_ENTRY
Macros
#define _256K (256L*1024L)
#define _64K (64L*1024L)
#define ASSERT_CM_EXCLUSIVE_HIVE_ACCESS(Hive)
#define ASSERT_CM_LOCK_NOT_OWNED()
#define ASSERT_CM_LOCK_OWNED()
#define ASSERT_CM_LOCK_OWNED_EXCLUSIVE()
#define ASSERT_CM_LOCK_OWNED_EXCLUSIVE_OR_HIVE_LOADING(_CmHive_)
#define ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING(_CmHive_)
#define ASSERT_HASH_ENTRY_LOCKED(ConvKey)
#define ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE(ConvKey) ASSERT((GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Owner == KeGetCurrentThread()) || (CmpTestRegistryLockExclusive() == TRUE))
#define ASSERT_HIVE_FLUSHER_LOCKED(_CmHive_)
#define ASSERT_HIVE_FLUSHER_LOCKED_EXCLUSIVE(_CmHive_)
#define ASSERT_HIVE_LOCK_OWNED(_hive_)
#define ASSERT_HIVE_SECURITY_LOCK_OWNED(_hive_)
#define ASSERT_HIVE_WRITER_LOCK_OWNED(_CmHive_)
#define ASSERT_KCB_LOCKED(kcb)
#define ASSERT_KCB_LOCKED_EXCLUSIVE(kcb) ASSERT((CmpIsKCBLockedExclusive(kcb) == TRUE) || (CmpTestRegistryLockExclusive() == TRUE))
#define ASSERT_KEY_OBJECT(x) ASSERT(((PCM_KEY_BODY)x)->Type == KEY_BODY_TYPE)
#define ASSERT_KEYBODY_LIST_EMPTY(kcb)
#define ASSERT_NODE(x) ASSERT(((PCM_KEY_NODE)x)->Signature == CM_KEY_NODE_SIGNATURE)
#define ASSERT_PASSIVE_LEVEL()
#define ASSERT_RESOURCE_NOT_OWNED(Res) ASSERT((ExIsResourceAcquiredShared(Res) == 0) && (ExIsResourceAcquiredExclusiveLite(Res) == 0))
#define ASSERT_RESOURCE_OWNED(Res) ASSERT((ExIsResourceAcquiredShared(Res) != 0) || (ExIsResourceAcquiredExclusiveLite(Res) != 0))
#define ASSERT_SECURITY(x) ASSERT(((PCM_KEY_SECURITY)x)->Signature == CM_KEY_SECURITY_SIGNATURE)
#define ASSERT_VIEW_LOCK_OWNED(_hive_)
#define ASSERT_VIEW_MAPPED(a)
#define ASSERT_VIEW_PINNED(a)
#define BEGIN_LOCK_CHECKPOINT
#define ClearMasterPostBlockFlag(_post_) (((_post_)->NotifyType) &= ~REG_NOTIFY_MASTER_POST)
#define CLONE_HIVE_INDEX 6
#define CM_CACHE_FAKE_KEY 0x00000001
#define CM_CHECK_REGISTRY_CHECK_CLEAN 0x00000001
#define CM_CHECK_REGISTRY_FORCE_CLEAN 0x00000002
#define CM_CHECK_REGISTRY_HIVE_CHECK 0x00010000
#define CM_CHECK_REGISTRY_LOADER_CLEAN 0x00000004
#define CM_CHECK_REGISTRY_SYSTEM_CLEAN 0x00000008
#define CM_CMHIVE_FLAG_UNTRUSTED 1
#define CM_DONT_ADD_TO_HIVE_LIST 0x01000000
#define CM_FILE_GROW_INCREMENT 256L*1024L
#define CM_HARDWARE_PROFILE_STR_ACPI_ALIAS L"AcpiAlias"
#define CM_HARDWARE_PROFILE_STR_ACPI_SERIAL_NUMBER L"AcpiSerialNumber"
#define CM_HARDWARE_PROFILE_STR_ALIAS L"Alias"
#define CM_HARDWARE_PROFILE_STR_ALIASABLE L"Aliasable"
#define CM_HARDWARE_PROFILE_STR_CAPABILITIES L"Capabilities"
#define CM_HARDWARE_PROFILE_STR_CCS_CURRENT L"\\Registry\\Machine\\System\\CurrentControlSet\\Hardware Profiles\\Current"
#define CM_HARDWARE_PROFILE_STR_CCS_HWPROFILE L"\\Registry\\Machine\\System\\CurrentControlSet\\Hardware Profiles"
#define CM_HARDWARE_PROFILE_STR_CLONED L"Cloned"
#define CM_HARDWARE_PROFILE_STR_CURRENT_DOCK_INFO L"CurrentDockInfo"
#define CM_HARDWARE_PROFILE_STR_DATABASE L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\IDConfigDB"
#define CM_HARDWARE_PROFILE_STR_DOCKED L"Docked"
#define CM_HARDWARE_PROFILE_STR_DOCKID L"DockID"
#define CM_HARDWARE_PROFILE_STR_DOCKING_STATE L"DockingState"
#define CM_HARDWARE_PROFILE_STR_FRIENDLY_NAME L"FriendlyName"
#define CM_HARDWARE_PROFILE_STR_HARDWARE_PROFILES L"Hardware Profiles"
#define CM_HARDWARE_PROFILE_STR_HW_PROFILE_GUID L"HwProfileGuid"
#define CM_HARDWARE_PROFILE_STR_PREFERENCE_ORDER L"PreferenceOrder"
#define CM_HARDWARE_PROFILE_STR_PRISTINE L"Pristine"
#define CM_HARDWARE_PROFILE_STR_PROFILE_NUMBER L"ProfileNumber"
#define CM_HARDWARE_PROFILE_STR_SERIAL_NUMBER L"SerialNumber"
#define CM_HARDWARE_PROFILE_STR_UNDOCKED L"Undocked"
#define CM_HARDWARE_PROFILE_STR_UNKNOWN L"Unknown"
#define CM_HIVE_COMPRESS_LEVEL (25)
#define CM_HP_FLAGS_ALIASABLE 1
#define CM_HP_FLAGS_DUPLICATE 8
#define CM_HP_FLAGS_PRISTINE 4
#define CM_HP_FLAGS_TRUE_MATCH 2
#define CM_MAX_REASONABLE_VALUES 100
#define CM_MAX_STASH 1024*1024
#define CM_NUMBER_OF_MACHINE_HIVES 6
#define CM_PAGED_CODE() PAGED_CODE()
#define CM_TRACK_QUOTA_START()
#define CM_TRACK_QUOTA_STOP()
#define CM_UNLOAD_KCB_LOCKED 1
#define CM_UNLOAD_REG_LOCKED_EX 2
#define CM_VIEW_SIZE 16L*1024L
#define CM_WRAP_LIMIT 0x7fffffff
#define CmAreCallbacksRegistered() ((CmpCallBackCount != 0) && (0 == ExIsResourceAcquiredShared(&CmpRegistryLock)))
#define CmCloseHandle(Handle)
#define CmDoSelfHeal() (CmpSelfHeal || (CmpBootType & (HBOOT_BACKUP|HBOOT_SELFHEAL)))
#define CmIsKcbReadOnly(kcb) ((kcb)->ExtFlags & CM_KCB_READ_ONLY_KEY)
#define CmKdPrintEx(_x_) KdPrintEx(_x_)
#define CML_BIN_MAP 15
#define CML_BUGCHECK 4
#define CML_CHECK_HIVE 23
#define CML_CM 8
#define CML_EXCEPTION 5
#define CML_FLOW 19
#define CML_FREECELL 16
#define CML_HIVE 10
#define CML_INDEX 14
#define CML_INIT 13
#define CML_IO 11
#define CML_LOCKING 18
#define CML_NOTIFY 9
#define CML_NTAPI 6
#define CML_NTAPI_ARGS 7
#define CML_PARSE 20
#define CML_POOL 17
#define CML_SAVRES 21
#define CML_SEC 12
#define CmLockHive(_hive_)
#define CmLockHiveSecurityExclusive(_hive_)
#define CmLockHiveSecurityShared(_hive_) ExAcquirePushLockShared(&((_hive_)->SecurityLock))
#define CmLockHiveViews(_hive_)
#define CmLogCellDeRef(HIVE, CELL)
#define CmLogCellRef(HIVE, CELL)
#define CmLogLockHive(HIVE)
#define CmLogUnlockHive(HIVE)
#define CmMarkSelfHeal(Hive) ((Hive)->BaseBlock->BootType |= HBOOT_SELFHEAL)
#define CMP_CREATE_KCB_FAKE 1
#define CMP_CREATE_KCB_KCB_LOCKED 2
#define CMP_DEST_UP 0x00000002
#define CMP_DO_OPEN_COMPLETE_KEY_CACHED 4
#define CMP_ENLIST_KCB_LOCKED_EXCLUSIVE 2
#define CMP_ENLIST_KCB_LOCKED_SHARED 1
#define CMP_MAX_REGISTRY_DEPTH 512
#define CMP_SOURCE_UP 0x00000001
#define CmpAddKeyTracker(KeyHandle, mode)
#define CmpAllocateMasterPostBlock(b) CmpAllocatePostBlock(b,REG_NOTIFY_MASTER_POST,NULL,NULL)
#define CmpAllocateSlavePostBlock(b, k, m) CmpAllocatePostBlock(b,0,k,m)
#define CmpAllocateTag(a, b, c) CmpAllocate(a,b,c)
#define CmpCheckForOrphanedKcbs(Hive)
#define CmpCheckIfResourceOwned()
#define CmpCheckIoStatusPointer(AsyncUser)
#define CmpClearListEntry(a)
#define CmpCopyTree(s, c, t, l) CmpCopySyncTree(s,c,t,l,FALSE,Copy)
#define CmpCopyTreeEx(s, c, t, l, f) CmpCopySyncTree(s,c,t,l,f,Copy)
#define CmpDumpSecurityDescriptor(x, y)
#define CmpFreeMutex(_mutex_)
#define CmpFreeResource(Resource)
#define CmpHKeyNameLen(Key)
#define CmpHKeyNodeSize(Hive, KeyName) (FIELD_OFFSET(CM_KEY_NODE, Name) + CmpNameSize(Hive, KeyName))
#define CmpHKeyValueSize(Hive, ValueName) (FIELD_OFFSET(CM_KEY_VALUE, Name) + CmpNameSize(Hive, ValueName))
#define CmpIsKCBLockedExclusive(Kcb) (GET_KCB_HASH_ENTRY_OWNER(Kcb) == KeGetCurrentThread())
#define CmpIsListEmpty(a) IsListEmpty(a)
#define CmpJoinClassOfTrust(_NewHive, _OtherHive)
#define CmpLockHashEntryByIndexExclusive(Index)
#define CmpLockHashEntryByIndexShared(Index) ExAcquirePushLockShared(&(CmpCacheTable[(Index)].Lock))
#define CmpLockHashEntryExclusive(ConvKey)
#define CmpLockHashEntryShared(ConvKey) ExAcquirePushLockShared(&(GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Lock))
#define CmpLockHiveFlusherExclusive(CmHive) ExAcquirePushLockExclusive(&(((PCMHIVE)CmHive)->FlusherLock))
#define CmpLockHiveFlusherShared(CmHive) ExAcquirePushLockShared(&(((PCMHIVE)CmHive)->FlusherLock))
#define CmpLockHiveListExclusive() ExAcquirePushLockExclusive(&CmpHiveListHeadLock)
#define CmpLockHiveListShared() ExAcquirePushLockShared(&CmpHiveListHeadLock)
#define CmpLockHiveWriter(_hive_)
#define CmpLockKCBExclusive(Kcb)
#define CmpLockKCBShared(Kcb) ExAcquirePushLockShared(&(GET_KCB_HASH_ENTRY_LOCK((Kcb))))
#define CmpLockNameHashEntryExclusive(ConvKey) ExAcquirePushLockExclusive(&(GET_HASH_ENTRY(CmpNameCacheTable,(ConvKey)).Lock))
#define CmpMakeSpecialPoolReadOnly(a)
#define CmpMakeSpecialPoolReadWrite(a)
#define CmpMakeValueCacheReadOnly(a, b)
#define CmpMakeValueCacheReadWrite(a, b)
#define CmpMarkAllBinsReadOnly(a)
#define CmpMergeTrees(s, c, t, l) CmpCopySyncTree(s,c,t,l,FALSE,Merge)
#define CmpNcbNameLen(Ncb)
#define CmPostCallbackNotification(Type, _Object_, _Status_)
#define CmpParseGetOriginatingPoint(_Context) ARGUMENT_PRESENT(_Context)?((PCM_PARSE_CONTEXT)(_Context))->OriginatingPoint:NULL
#define CmpParseRecordOriginatingPoint(_Context, _CmHive)
#define CmpRemoveEntryList(a) RemoveEntryList(a)
#define CmpSecHashTableSize 64
#define CmpSetHandleProtection(Handle, Protection)
#define CmpSetIoStatus(Iosb, s, i, UseIosb32)
#define CmpSetNoCallers(KeyBody)
#define CmpSetUpKcbValueCache(KeyControlBlock, _Count, _List)
#define CmpSyncTrees(s, c, t, l, f) CmpCopySyncTree(s,c,t,l,f,Sync)
#define CmpTraceKcbCreate(kcb)
#define CmpUnJoinClassOfTrust(CmHive)
#define CmpUnlockHashEntry(ConvKey)
#define CmpUnlockHashEntryByIndex(Index)
#define CmpUnlockHiveFlusher(CmHive) ExReleasePushLock(&(((PCMHIVE)CmHive)->FlusherLock))
#define CmpUnlockHiveList() ExReleasePushLock(&CmpHiveListHeadLock)
#define CmpUnlockHiveWriter(_hive_)
#define CmpUnlockKCB(Kcb)
#define CmpUnlockNameHashEntry(ConvKey) ExReleasePushLock(&(GET_HASH_ENTRY(CmpNameCacheTable,(ConvKey)).Lock))
#define CmpUpgradeKCBLockToExclusive(kcb)
#define CmpValueNameLen(Value)
#define CmpWmiFireEvent(Status, Kcb, ElapsedTime, Index, KeyName, Type)
#define CmRetryExAllocatePoolWithTag(a, b, c, Result)
#define CmUnlockHive(_hive_)
#define CmUnlockHiveSecurity(_hive_)
#define CmUnlockHiveViews(_hive_)
#define CmUpcaseUnicodeChar(c) (((c) < 'a') ? (c) : (((c) > 'z') ? RtlUpcaseUnicodeChar(c) : ((c) - ('a'-'A'))))
#define DCmCheckRegistry(a)
#define END_LOCK_CHECKPOINT
#define EndWmiCmTrace(Status, Index, KeyName, Type)
#define ENTER_FLUSH_MODE() InterlockedIncrement (&CmpFlushStarveWriters);
#define EXIT_FLUSH_MODE() InterlockedDecrement (&CmpFlushStarveWriters)
#define GET_HASH_ENTRY(Table, Key) Table[GET_HASH_INDEX(Key)]
#define GET_HASH_INDEX(Key) HASH_KEY(Key) % CmpHashTableSize
#define GET_KCB_HASH_ENTRY(Table, Key) GET_HASH_ENTRY(Table, Key).Entry
#define GET_KCB_HASH_ENTRY_LOCK(kcb) (GET_HASH_ENTRY(CmpCacheTable,(kcb)->ConvKey).Lock)
#define GET_KCB_HASH_ENTRY_OWNER(kcb) (GET_HASH_ENTRY(CmpCacheTable,(kcb)->ConvKey).Owner)
#define HASH_KEY(_convkey_) ((RNDM_CONSTANT * (_convkey_)) % RNDM_PRIME)
#define HiveWritesThroughCache(Hive, FileType) ((FileType == HFILE_TYPE_PRIMARY) && (((PCMHIVE)CONTAINING_RECORD(Hive, CMHIVE, Hive))->FileObject != NULL))
#define HookKcbForWmiCmTrace(KeyBody)
#define HookKcbFromHandleForWmiCmTrace(KeyHandle)
#define HvpChangeBinAllocation(a, b)
#define HvpMarkBinReadWrite(a, b)
#define INIT_SYSTEMROOT_HIVEPATH L"\\SystemRoot\\System32\\Config\\"
#define IO_BUFFER_SIZE _64K
#define IsHiveFrozen(_CmHive_) (((PCMHIVE)(_CmHive_))->Frozen == TRUE)
#define IsMasterPostBlock(_post_) (((_post_)->NotifyType) & REG_NOTIFY_MASTER_POST)
#define KCB_WORKER_CONTINUE 0
#define KCB_WORKER_DELETE 2
#define KCB_WORKER_DONE 1
#define KCB_WORKER_ERROR 3
#define KEY_BODY_HIVE_UNLOADED 0x00000001
#define KEY_BODY_TYPE 0x6b793032
#define LOCK_HIVE_LOAD() ExAcquirePushLockExclusive(&CmpLoadHiveLock)
#define LOCK_POST_LIST() ExAcquirePushLockExclusive(&CmpPostLock)
#define LOCK_STASH_BUFFER() ExAcquirePushLockExclusive(&CmpStashBufferLock)
#define LogKCBReference(kcb, reason)
#define MAX_HIVE_LAYERS 2
#define MAX_MB_PER_HIVE 16
#define MAX_NAME 128
#define MAX_VIEWS_PER_HIVE MAX_MB_PER_HIVE * ((_256K) / (CM_VIEW_SIZE))
#define NUMBER_TYPES (MaximumType + 1)
#define PostBlockType(_post_) ((POST_BLOCK_TYPE)(((_post_)->NotifyType) & REG_NOTIFY_POST_TYPE_MASK))
#define REG_NOTIFY_MASTER_POST (0x00010000L)
#define REG_NOTIFY_POST_TYPE_MASK (0x0000FFFFL)
#define REG_OPTION_PREDEF_HANDLE (0x01000000L)
#define REG_PREDEF_HANDLE_MASK (0x80000000L)
#define REGCHECKING 1
#define RNDM_CONSTANT 314159269 /* default value for "scrambling constant" */
#define RNDM_PRIME 1000000007 /* prime number, also used for scrambling */
#define SECOND_MULT 10*1000*1000
#define SetMasterPostBlockFlag(_post_) (((_post_)->NotifyType) |= REG_NOTIFY_MASTER_POST)
#define StartWmiCmTrace()
#define SYSTEM_HIVE_INDEX 3
#define UNLOCK_HIVE_LOAD() ExReleasePushLock(&CmpLoadHiveLock)
#define UNLOCK_POST_LIST() ExReleasePushLock(&CmpPostLock)
#define UNLOCK_STASH_BUFFER() ExReleasePushLock(&CmpStashBufferLock)
#define VALIDATE_CELL_MAP(LINE, Map, Hive, Address)
Typedefs
typedef struct _BOOT_DRIVER_NODE BOOT_DRIVER_NODE
typedef struct _CM_ASYNC_KERNEL_POST_BLOCK CM_ASYNC_KERNEL_POST_BLOCK
typedef struct _CM_ASYNC_USER_POST_BLOCK CM_ASYNC_USER_POST_BLOCK
typedef struct _CM_CELL_REMAP_BLOCK CM_CELL_REMAP_BLOCK
typedef struct _CM_DELAY_ALLOC CM_DELAY_ALLOC
typedef struct _CM_DELAYED_CLOSE_ENTRY CM_DELAYED_CLOSE_ENTRY
typedef struct _CM_HARDWARE_PROFILE CM_HARDWARE_PROFILE
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS CM_HARDWARE_PROFILE_ACPI_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_ALIAS CM_HARDWARE_PROFILE_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ALIAS_LIST CM_HARDWARE_PROFILE_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_LIST CM_HARDWARE_PROFILE_LIST
typedef struct _CM_KCB_REMAP_BLOCK CM_KCB_REMAP_BLOCK
typedef struct _CM_KEY_BODY CM_KEY_BODY
typedef struct _CM_KNODE_REMAP_BLOCK CM_KNODE_REMAP_BLOCK
typedef struct _CM_NOTIFY_BLOCK CM_NOTIFY_BLOCK
typedef struct _CM_PARSE_CONTEXT CM_PARSE_CONTEXT
typedef struct _CM_POST_BLOCK CM_POST_BLOCK
typedef union _CM_POST_BLOCK_UNION CM_POST_BLOCK_UNION
typedef struct _CM_POST_KEY_BODY CM_POST_KEY_BODY
typedef struct _CM_SYNC_POST_BLOCK CM_SYNC_POST_BLOCK
typedef struct _CM_VIEW_OF_FILE CM_VIEW_OF_FILE
typedef struct _CM_WRITE_BLOCK CM_WRITE_BLOCK
typedef struct _CMHIVE CMHIVE
typedef struct _HIVE_LIST_ENTRY HIVE_LIST_ENTRY
typedef struct _BOOT_DRIVER_NODE * PBOOT_DRIVER_NODE
typedef NTSTATUS(* PCM_ACPI_SELECTION_ROUTINE) (IN PCM_HARDWARE_PROFILE_LIST ProfileList, OUT PULONG ProfileIndexToUse, IN PVOID Context)
typedef struct _CM_ASYNC_KERNEL_POST_BLOCK * PCM_ASYNC_KERNEL_POST_BLOCK
typedef struct _CM_ASYNC_USER_POST_BLOCK * PCM_ASYNC_USER_POST_BLOCK
typedef struct _CM_CELL_REMAP_BLOCK * PCM_CELL_REMAP_BLOCK
typedef struct _CM_DELAY_ALLOC * PCM_DELAY_ALLOC
typedef struct _CM_DELAYED_CLOSE_ENTRY * PCM_DELAYED_CLOSE_ENTRY
typedef struct _CM_HARDWARE_PROFILE * PCM_HARDWARE_PROFILE
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS * PCM_HARDWARE_PROFILE_ACPI_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST * PCM_HARDWARE_PROFILE_ACPI_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_ALIAS * PCM_HARDWARE_PROFILE_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ALIAS_LIST * PCM_HARDWARE_PROFILE_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_LIST * PCM_HARDWARE_PROFILE_LIST
typedef struct _CM_KCB_REMAP_BLOCK * PCM_KCB_REMAP_BLOCK
typedef struct _CM_KEY_BODY * PCM_KEY_BODY
typedef struct _CM_KNODE_REMAP_BLOCK * PCM_KNODE_REMAP_BLOCK
typedef struct _CM_NOTIFY_BLOCK * PCM_NOTIFY_BLOCK
typedef struct _CM_PARSE_CONTEXT * PCM_PARSE_CONTEXT
typedef struct _CM_POST_BLOCK * PCM_POST_BLOCK
typedef union _CM_POST_BLOCK_UNION * PCM_POST_BLOCK_UNION
typedef struct _CM_POST_KEY_BODY * PCM_POST_KEY_BODY
typedef struct _CM_SYNC_POST_BLOCK * PCM_SYNC_POST_BLOCK
typedef struct _CM_VIEW_OF_FILE * PCM_VIEW_OF_FILE
typedef struct _CM_WRITE_BLOCK * PCM_WRITE_BLOCK
typedef struct _CMHIVE * PCMHIVE
typedef struct CMP_CHECK_REGISTRY_STACK_ENTRY * PCMP_CHECK_REGISTRY_STACK_ENTRY
typedef struct _HIVE_LIST_ENTRY * PHIVE_LIST_ENTRY
typedef ULONG(* PKCB_WORKER_ROUTINE) (PCM_KEY_CONTROL_BLOCK Current, PVOID Context1, PVOID Context2)
typedef enum _POST_BLOCK_TYPE POST_BLOCK_TYPE
typedef struct _QUERY_OPEN_SUBKEYS_CONTEXT * PQUERY_OPEN_SUBKEYS_CONTEXT
typedef struct _QUERY_OPEN_SUBKEYS_CONTEXT QUERY_OPEN_SUBKEYS_CONTEXT
typedef enum _VALUE_SEARCH_RETURN_TYPE VALUE_SEARCH_RETURN_TYPE
Enumerations
enum _POST_BLOCK_TYPE { PostSynchronous = 1, PostAsyncUser = 2, PostAsyncKernel = 3 }
enum _VALUE_SEARCH_RETURN_TYPE { SearchSuccess = 0, SearchNeedExclusiveLock = 1, SearchFail = 2 }
Functions
ULONG CmCheckRegistry (PCMHIVE CmHive, ULONG Flags)
NTSTATUS CmCompressKey (IN PHHIVE Hive)
NTSTATUS CmDeleteKey (IN PCM_KEY_BODY KeyBody)
NTSTATUS CmDeleteValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName)
NTSTATUS CmDumpKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle)
NTSTATUS CmEnumerateKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmEnumerateValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmFlushKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN BOOLEAN RegistryLockOwnedExclusive)
NTSTATUS CmLoadKey (IN POBJECT_ATTRIBUTES TargetKey, IN POBJECT_ATTRIBUTES SourceFile, IN ULONG Flags, IN PCM_KEY_BODY KeyBody)
NTSTATUS CmLockKcbForWrite (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
NTSTATUS CmMoveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock)
NTSTATUS CmpAcquireFileObjectForFile (IN PCMHIVE CmHive, IN HANDLE FileHandle, OUT PFILE_OBJECT *FileObject)
NTSTATUS CmpAddAcpiAliasEntry (IN HANDLE IDConfigDB, IN PPROFILE_ACPI_DOCKING_STATE NewDockState, IN ULONG ProfileNumber, IN PWCHAR nameBuffer, IN PVOID valueBuffer, IN ULONG valueBufferLength, IN BOOLEAN PreventDuplication)
NTSTATUS CmpAddSecurityCellToCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, IN BOOLEAN BuildUp, IN PCM_KEY_SECURITY_CACHE SecurityCached)
BOOLEAN CmpAddSubKey (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
VOID CmpAddToDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN RegLockHeldEx)
NTSTATUS CmpAddToHiveFileList (PCMHIVE CmHive)
NTSTATUS CmpAddValueToList (IN PHHIVE Hive, IN HCELL_INDEX ValueCell, IN ULONG Index, IN ULONG Type, IN OUT PCHILD_LIST ChildList)
BOOLEAN CmpAdjustSecurityCacheSize (IN PCMHIVE CmHive)
PVOID CmpAllocate (ULONG Size, BOOLEAN UseForIo, ULONG Tag)
PVOID CmpAllocateDelayItem ()
PCM_KEY_CONTROL_BLOCK CmpAllocateKeyControlBlock ()
PCM_POST_BLOCK CmpAllocatePostBlock (IN POST_BLOCK_TYPE BlockType, IN ULONG PostFlags, IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK MasterBlock)
NTSTATUS CmpAssignSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PCM_KEY_NODE Node, IN PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSTATUS CmpAssignSecurityDescriptorWrapper (IN PVOID Object, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor)
VOID CmpAssignSecurityToKcb (IN PCM_KEY_CONTROL_BLOCK Kcb, IN HCELL_INDEX SecurityCell, IN BOOLEAN SecurityLocked)
BOOLEAN CmpBuildSecurityCellMappingArray (IN PCMHIVE CmHive)
NTSTATUS CmpCallCallBacks (IN REG_NOTIFY_CLASS Type, IN PVOID Argument, IN BOOLEAN Wind, IN REG_NOTIFY_CLASS PostType, IN PVOID Object)
BOOLEAN CmpCanGrowSystemHive (IN PHHIVE Hive, IN ULONG NewLength)
BOOLEAN CmpCheckCreateAccess (IN PUNICODE_STRING RelativeName, IN PSECURITY_DESCRIPTOR Descriptor, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK AdditionalAccess, OUT PNTSTATUS AccessStatus)
NTSTATUS CmpCheckKeyAccess (IN PHHIVE Hive, IN HCELL_INDEX NodeCell, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK DesiredAccess)
BOOLEAN CmpCheckNotifyAccess (IN PCM_NOTIFY_BLOCK NotifyBlock, IN PHHIVE Hive, IN PCM_KEY_NODE Node)
BOOLEAN CmpClaimGlobalQuota (IN ULONG Size)
VOID CmpCleanUpKCBCacheTable (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
VOID CmpCleanUpKcbCacheWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
VOID CmpCleanUpKcbValueCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpCleanUpSubKeyInfo (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
NTSTATUS CmpCloneHwProfile (IN HANDLE IDConfigDB, IN HANDLE Parent, IN HANDLE OldProfile, IN ULONG OldProfileNumber, IN USHORT DockingState, OUT PHANDLE NewProfile, OUT PULONG NewProfileNumber)
VOID CmpCloseKeyObject (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID CmpCmdHiveClose (PCMHIVE CmHive)
NTSTATUS CmpCmdHiveOpen (POBJECT_ATTRIBUTES FileAttributes, PSECURITY_CLIENT_CONTEXT ImpersonationContext, PBOOLEAN Allocate, PCMHIVE *NewHive, ULONG CheckFlags)
VOID CmpCmdInit (BOOLEAN SetupBoot)
NTSTATUS CmpCmdRenameHive (PCMHIVE CmHive, POBJECT_NAME_INFORMATION OldName, PUNICODE_STRING NewName, ULONG NameInfoLength)
LONG CmpCompareCompressedName (IN PUNICODE_STRING SearchName, IN PWCHAR CompressedName, IN ULONG NameLength, IN ULONG CompareFlags)
LONG CmpCompareTwoCompressedNames (IN PWCHAR CompressedName1, IN ULONG NameLength1, IN PWCHAR CompressedName2, IN ULONG NameLength2)
LONG CmpCompareUnicodeString (IN PUNICODE_STRING SourceName, IN PUNICODE_STRING DestName, IN ULONG CompareFlags)
USHORT CmpCompressedNameSize (IN PWCHAR Name, IN ULONG Length)
VOID CmpComputeGlobalQuotaAllowed (VOID)
ULONG CmpComputeHashKey (IN ULONG HashStart, IN PUNICODE_STRING Name)
ULONG CmpComputeHashKeyForCompressedName (IN ULONG HashStart, IN PWCHAR Source, IN ULONG SourceLength)
ULONG CmpComputeKcbConvKey (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
PUNICODE_STRING CmpConstructName (PCM_KEY_CONTROL_BLOCK kcb)
HCELL_INDEX CmpCopyCell (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
VOID CmpCopyCompressedName (IN PWCHAR Destination, IN ULONG DestinationLength, IN PWCHAR Source, IN ULONG SourceLength)
HCELL_INDEX CmpCopyKeyPartial (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PHHIVE TargetHive, HCELL_INDEX Parent, BOOLEAN CopyValues)
USHORT CmpCopyName (IN PHHIVE Hive, IN PWCHAR Destination, IN PUNICODE_STRING Source)
BOOLEAN CmpCopySyncTree (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HCELL_INDEX TargetCell, BOOLEAN CopyVolatile, CMP_COPY_TYPE CopyType)
HCELL_INDEX CmpCopyValue (PHHIVE SourceHive, HCELL_INDEX SourceValueCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
NTSTATUS CmpCreateEvent (IN EVENT_TYPE eventType, OUT PHANDLE eventHandle, OUT PKEVENT *event)
NTSTATUS CmpCreateHwProfileFriendlyName (IN HANDLE IDConfigDB, IN ULONG DockingState, IN ULONG NewProfileNumber, OUT PUNICODE_STRING FriendlyName)
PCM_KEY_CONTROL_BLOCK CmpCreateKeyControlBlock (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node, PCM_KEY_CONTROL_BLOCK ParentKcb, ULONG ControlFlags, PUNICODE_STRING KeyName)
VOID CmpDelayDerefKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
NTSTATUS CmpDeleteChildByName (PHHIVE Hive, HCELL_INDEX Cell, UNICODE_STRING Name, PHCELL_INDEX ChildCell)
VOID CmpDeleteKeyObject (IN PVOID Object)
VOID CmpDeleteTree (PHHIVE Hive, HCELL_INDEX Cell)
VOID CmpDereferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
VOID CmpDereferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
VOID CmpDereferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpDereferenceKeyControlBlockWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
VOID CmpDestroyCmPrivateAlloc ()
VOID CmpDestroyCmPrivateDelayAlloc ()
LOGICAL CmpDestroyHive (IN PHHIVE Hive, IN HCELL_INDEX Cell)
VOID CmpDestroyHiveViewList (IN PCMHIVE CmHive)
VOID CmpDestroySecurityCache (IN OUT PCMHIVE CmHive)
NTSTATUS CmpDoAccessCheckOnSubtree (PHHIVE HiveToCheck, HCELL_INDEX Cell, KPROCESSOR_MODE PreviousMode, ACCESS_MASK DesiredAccess, BOOLEAN CheckRoot)
NTSTATUS CmpDoCreate (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN PCMHIVE OriginatingHive OPTIONAL, OUT PVOID *Object)
NTSTATUS CmpDoCreateChild (IN PHHIVE Hive, IN HCELL_INDEX ParentCell, IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN USHORT Flags, OUT PHCELL_INDEX KeyCell, OUT PVOID *Object)
NTSTATUS CmpDoFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
BOOLEAN CmpDoFlushAll (BOOLEAN ForceFlush)
VOID CmpDropFileObjectForHive (IN PCMHIVE CmHive)
HCELL_INDEX CmpDuplicateIndex (PHHIVE Hive, HCELL_INDEX IndexCell, ULONG StorageType)
BOOLEAN CmpFileFlush (PHHIVE Hive, ULONG FileType, PLARGE_INTEGER FileOffset, ULONG Length)
BOOLEAN CmpFileRead (PHHIVE Hive, ULONG FileType, PULONG FileOffset, PVOID DataBuffer, ULONG DataLength)
BOOLEAN CmpFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
BOOLEAN CmpFileWrite (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount, PULONG FileOffset)
BOOLEAN CmpFileWriteThroughCache (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount)
HCELL_INDEX CmpFindControlSet (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell, IN PUNICODE_STRING SelectName, OUT PBOOLEAN AutoSelect)
BOOLEAN CmpFindDrivers (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN SERVICE_LOAD_TYPE LoadType, IN PWSTR BootFileSystem OPTIONAL, IN PLIST_ENTRY DriverListHead)
BOOLEAN CmpFindNameInList (IN PHHIVE Hive, IN PCHILD_LIST ChildList, IN PUNICODE_STRING Name, IN OPTIONAL PULONG ChildIndex, OUT PHCELL_INDEX CellIndex)
BOOLEAN CmpFindNLSData (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, OUT PUNICODE_STRING AnsiFilename, OUT PUNICODE_STRING OemFilename, OUT PUNICODE_STRING CaseTableFilename, OUT PUNICODE_STRING OemHalFilename)
HCELL_INDEX CmpFindProfileOption (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, OUT PCM_HARDWARE_PROFILE_LIST *ProfileList, OUT PCM_HARDWARE_PROFILE_ALIAS_LIST *AliasList, OUT PULONG Timeout)
BOOLEAN CmpFindSecurityCellCacheIndex (IN PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, OUT PULONG Index)
HCELL_INDEX CmpFindSubKeyByName (PHHIVE Hive, PCM_KEY_NODE Parent, PUNICODE_STRING SearchName)
HCELL_INDEX CmpFindSubKeyByNumber (PHHIVE Hive, PCM_KEY_NODE Parent, ULONG Number)
HCELL_INDEX CmpFindValueByName (PHHIVE Hive, PCM_KEY_NODE KeyNode, PUNICODE_STRING Name)
VALUE_SEARCH_RETURN_TYPE CmpFindValueByNameFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING Name, OUT PPCM_CACHED_VALUE *ContainingList, OUT ULONG *Index, OUT PCM_KEY_VALUE *Value, OUT BOOLEAN *ValueCached, OUT PHCELL_INDEX CellToRelease)
VOID CmpFixHiveUsageCount (IN PCMHIVE CmHive)
VOID CmpFlushNotifiesOnKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN LockHeld)
VOID CmpFlushNotify (PCM_KEY_BODY KeyBody, BOOLEAN LockHeld)
VOID CmpFree (PVOID MemoryBlock, ULONG GlobalQuotaSize)
VOID CmpFreeDelayItem (PVOID Item)
BOOLEAN CmpFreeKeyBody (PHHIVE Hive, HCELL_INDEX Cell)
NTSTATUS CmpFreeKeyByCell (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN Unlink)
VOID CmpFreeKeyControlBlock (PCM_KEY_CONTROL_BLOCK kcb)
VOID CmpFreePostBlock (IN PCM_POST_BLOCK PostBlock)
VOID CmpFreeSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell)
BOOLEAN CmpFreeValue (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN CmpFreeValueData (PHHIVE Hive, HCELL_INDEX DataCell, ULONG DataLength)
PCM_NAME_CONTROL_BLOCK CmpGetNameControlBlock (PUNICODE_STRING NodeName, PBOOLEAN NameUpCase)
BOOLEAN CmpGetNextName (IN OUT PUNICODE_STRING RemainingName, OUT PUNICODE_STRING NextName, OUT PBOOLEAN Last)
BOOLEAN CmpGetValueData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize, IN OUT PVOID *Buffer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
VALUE_SEARCH_RETURN_TYPE CmpGetValueDataFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PPCM_CACHED_VALUE ContainingList, IN PCELL_DATA ValueKey, IN BOOLEAN ValueCached, OUT PUCHAR *DataPointer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
VALUE_SEARCH_RETURN_TYPE CmpGetValueKeyFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PCELL_DATA List, IN ULONG Index, OUT PPCM_CACHED_VALUE *ContainingList, OUT PCM_KEY_VALUE *Value, IN BOOLEAN IndexCached, OUT BOOLEAN *ValueCached, OUT PHCELL_INDEX CellToRelease)
VALUE_SEARCH_RETURN_TYPE CmpGetValueListFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, OUT PCELL_DATA *List, OUT BOOLEAN *IndexCached, OUT PHCELL_INDEX ValueListToRelease)
PSECURITY_DESCRIPTOR CmpHiveRootSecurityDescriptor (VOID)
VOID CmpInitCmPrivateAlloc ()
VOID CmpInitCmPrivateDelayAlloc ()
VOID CmpInitDelayDerefKCBEngine ()
NTSTATUS CmpInitHiveFromFile (IN PUNICODE_STRING FileName, IN ULONG HiveFlags, OUT PCMHIVE *CmHive, IN OUT PBOOLEAN Allocate, IN ULONG CheckFlags)
VOID CmpInitHiveViewList (IN PCMHIVE CmHive)
VOID CmpInitializeCache (VOID)
VOID CmpInitializeDelayedCloseTable ()
NTSTATUS CmpInitializeHardwareConfiguration (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS CmpInitializeHive (PCMHIVE *CmHive, ULONG OperationType, ULONG HiveFlags, ULONG FileType, PVOID HiveData OPTIONAL, HANDLE Primary, HANDLE Log, HANDLE External, PUNICODE_STRING FileName OPTIONAL, ULONG CheckFlags)
VOID CmpInitializeKeyNameString (PCM_KEY_NODE Cell, PUNICODE_STRING KeyName, WCHAR *NameBuffer)
NTSTATUS CmpInitializeMachineDependentConfiguration (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID CmpInitializeRegistryNames (VOID)
NTSTATUS CmpInitializeRegistryNode (IN PCONFIGURATION_COMPONENT_DATA CurrentEntry, IN HANDLE ParentHandle, OUT PHANDLE NewHandle, IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PUSHORT DeviceIndexTable)
VOID CmpInitializeValueNameString (PCM_KEY_VALUE Cell, PUNICODE_STRING ValueName, WCHAR *NameBuffer)
VOID CmpInitSecurityCache (IN OUT PCMHIVE CmHive)
BOOLEAN CmpKCBLockForceAcquireAllowed (ULONG Index1, ULONG Index2, ULONG NewIndex)
VOID CmpLazyFlush (VOID)
NTSTATUS CmpLinkHiveToMaster (PUNICODE_STRING LinkName, HANDLE RootDirectory, PCMHIVE CmHive, BOOLEAN Allocate, PSECURITY_DESCRIPTOR SecurityDescriptor)
VOID CmpLockRegistry (VOID)
VOID CmpLockRegistryExclusive (VOID)
VOID CmpLockTwoHashEntriesExclusive (ULONG ConvKey1, ULONG ConvKey2)
VOID CmpLockTwoHashEntriesShared (ULONG ConvKey1, ULONG ConvKey2)
NTSTATUS CmpMapCmView (IN PCMHIVE CmHive, IN ULONG FileOffset, OUT PCM_VIEW_OF_FILE *CmView, IN BOOLEAN MapInited)
NTSTATUS CmpMapThisBin (PCMHIVE CmHive, HCELL_INDEX Cell, BOOLEAN Touch)
BOOLEAN CmpMarkIndexDirty (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
BOOLEAN CmpMarkKeyDirty (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN CmpMarkValueDataDirty (IN PHHIVE Hive, IN PCM_KEY_VALUE Value)
USHORT CmpNameSize (IN PHHIVE Hive, IN PUNICODE_STRING Name)
NTSTATUS CmpNotifyChangeKey (IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK PostBlock, IN ULONG CompletionFilter, IN BOOLEAN WatchTree, IN PVOID Buffer, IN ULONG BufferSize, IN PCM_POST_BLOCK MasterPostBlock)
NTSTATUS CmpOpenHiveFiles (PUNICODE_STRING BaseName, PWSTR Extension OPTIONAL, PHANDLE Primary, PHANDLE Secondary, PULONG PrimaryDisposition, PULONG SecondaryDispoition, BOOLEAN CreateAllowed, BOOLEAN MarkAsSystemHive, BOOLEAN NoBuffering, PULONG ClusterSize)
NTSTATUS CmpOverwriteHive (PCMHIVE CmHive, PCMHIVE NewHive, HCELL_INDEX LinkCell)
NTSTATUS CmpParseKey (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
NTSTATUS CmpPinCmView (IN PCMHIVE CmHive, PCM_VIEW_OF_FILE CmView)
VOID CmpPostApc (struct _KAPC *Apc, PKNORMAL_ROUTINE *NormalRoutine, PVOID *NormalContext, PVOID *SystemArgument1, PVOID *SystemArgument2)
VOID CmpPostApcRunDown (struct _KAPC *Apc)
VOID CmpPostNotify (PCM_NOTIFY_BLOCK NotifyBlock, PUNICODE_STRING Name OPTIONAL, ULONG Filter, NTSTATUS Status, BOOLEAN PostListLockHeld, PLIST_ENTRY ExternalKeyDeref OPTIONAL)
VOID CmpPrefetchHiveFile (IN PFILE_OBJECT FileObject, IN ULONG Length)
NTSTATUS CmpQueryKeyData (PHHIVE Hive, PCM_KEY_NODE Node, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
NTSTATUS CmpQueryKeyDataFromCache (PCM_KEY_CONTROL_BLOCK Kcb, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
NTSTATUS CmpQueryKeyName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
VALUE_SEARCH_RETURN_TYPE CmpQueryKeyValueData (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PPCM_CACHED_VALUE ContainingList, PCM_KEY_VALUE ValueKey, BOOLEAN ValueCached, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength, NTSTATUS *status)
VOID CmpQuotaWarningWorker (IN PVOID WorkItem)
VOID CmpRaiseSelfHealWarning (IN PUNICODE_STRING HiveName)
VOID CmpRaiseSelfHealWarningForSystemHives ()
VOID CmpRebuildKcbCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
BOOLEAN CmpRebuildSecurityCache (IN OUT PCMHIVE CmHive)
VOID CmpReferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
VOID CmpReferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
BOOLEAN CmpReferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VOID CmpReleaseGlobalQuota (IN ULONG Size)
VOID CmpRemoveFromDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb)
VOID CmpRemoveFromHiveFileList (PUNICODE_STRING HiveName)
VOID CmpRemoveFromSecurityCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell)
VOID CmpRemoveKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
BOOLEAN CmpRemoveSubKey (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
BOOLEAN CmpRemoveSubKeyCellNoCellRef (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
NTSTATUS CmpRemoveValueFromList (IN PHHIVE Hive, IN ULONG Index, IN OUT PCHILD_LIST ChildList)
VOID CmpReportNotify (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PHHIVE Hive, HCELL_INDEX Cell, ULONG NotifyMask)
BOOLEAN CmpResolveDriverDependencies (IN PLIST_ENTRY DriverListHead)
VOID CmpRunDownDelayDerefKCBEngine (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
NTSTATUS CmpSaveBootControlSet (IN USHORT ControlSetNum)
ULONG CmpSearchForOpenSubKeys (IN PCM_KEY_CONTROL_BLOCK SearchKey, IN SUBKEY_SEARCH_TYPE SearchType, IN BOOLEAN RegLockHeldEx, IN OUT PVOID SearchContext OPTIONAL)
BOOLEAN CmpSearchKeyControlBlockTree (PKCB_WORKER_ROUTINE WorkerRoutine, PVOID Context1, PVOID Context2)
ULONG CmpSecConvKey (IN ULONG DescriptorLength, IN PULONG Descriptor)
NTSTATUS CmpSecurityMethod (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
VOID CmpSetCurrentProfile (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PCM_HARDWARE_PROFILE Profile)
VOID CmpSetGlobalQuotaAllowed (VOID)
NTSTATUS CmpSetValueDataExisting (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX OldDataCell)
NTSTATUS CmpSetValueDataNew (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX ValueCell, OUT PHCELL_INDEX DataCell)
VOID CmpSetVersionData (VOID)
NTSTATUS CmpShiftHiveFreeBins (PCMHIVE CmHive, PCMHIVE *NewHive)
VOID CmpShutdownWorkers (VOID)
BOOLEAN CmpSortDriverList (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PLIST_ENTRY DriverListHead)
VOID CmpSwitchStorageAndRebuildMappings (PCMHIVE OldCmHive, PCMHIVE NewHive)
VOID CmpSystemQuotaWarningWorker (IN PVOID WorkItem)
VOID CmpTouchView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN ULONG Cell)
BOOLEAN CmpTryConvertKCBLockSharedToExclusive (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
BOOLEAN CmpTryToLockHashEntryByIndexExclusive (ULONG Index)
VOID CmpUnlockRegistry ()
VOID CmpUnlockTwoHashEntries (ULONG ConvKey1, ULONG ConvKey2)
VOID CmpUnPinCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN SetClean, IN BOOLEAN MapIsValid)
BOOLEAN CmpUpdateParentForEachSon (PHHIVE Hive, HCELL_INDEX Parent)
VOID CmpUpdateSystemHiveHysteresis (PHHIVE Hive, ULONG NewLength, ULONG OldLength)
BOOLEAN CmpValidateHiveSecurityDescriptors (IN PHHIVE Hive, OUT PBOOLEAN ResetSD)
BOOLEAN CmpValidateSelect (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell)
PCELL_DATA CmpValueToData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize)
VOID CmpWmiDumpKcb (PCM_KEY_CONTROL_BLOCK kcb)
NTSTATUS CmQueryKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmQueryMultipleValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PKEY_VALUE_ENTRY ValueEntries, IN ULONG EntryCount, IN PVOID ValueBuffer, IN OUT PULONG BufferLength, IN OPTIONAL PULONG ResultLength)
NTSTATUS CmQueryValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmRenameKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING NewKeyName, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS CmRenameValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING SourceValueName, IN UNICODE_STRING TargetValueName, IN ULONG TargetIndex)
NTSTATUS CmReplaceKey (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PUNICODE_STRING NewHiveName, IN PUNICODE_STRING OldFileName)
NTSTATUS CmRestoreKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG Flags)
NTSTATUS CmSaveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG HiveVersion)
NTSTATUS CmSaveMergedKeys (IN PCM_KEY_CONTROL_BLOCK HighPrecedenceKcb, IN PCM_KEY_CONTROL_BLOCK LowPrecedenceKcb, IN HANDLE FileHandle)
NTSTATUS CmSetAcpiHwProfile (IN PPROFILE_ACPI_DOCKING_STATE DockState, IN PCM_ACPI_SELECTION_ROUTINE, IN PVOID Context, OUT PHANDLE NewProfile, OUT PBOOLEAN ProfileChanged)
NTSTATUS CmSetKeyUserFlags (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG UserFlags)
NTSTATUS CmSetLastWriteTimeKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PLARGE_INTEGER LastWriteTime)
NTSTATUS CmSetValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING ValueName, IN ULONG Type, IN PVOID Data, IN ULONG DataSize)
NTSTATUS CmUnloadKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN ULONG Flags, IN ULONG ControlFlags)
NTSTATUS CmUnloadKeyEx (IN PCM_KEY_CONTROL_BLOCK Kcb, IN PKEVENT UserEvent)
VOID DelistKeyBodyFromKCB (IN PCM_KEY_BODY KeyBody, IN BOOLEAN LockHeld)
VOID EnlistKeyBodyWithKCB (IN PCM_KEY_BODY KeyBody, IN ULONG ControlFlags)
VOID InitializeKCBKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb)
Variables
ULONG CmpBootType
const ULONG CmpCacheOnFlag
PCM_KEY_HASH_TABLE_ENTRY CmpCacheTable
ULONG CmpCallBackCount
LONG CmpFlushStarveWriters
ULONG CmpHashTableSize
LIST_ENTRY CmpHiveListHead
EX_PUSH_LOCK CmpHiveListHeadLock
POBJECT_TYPE CmpKeyObjectType
EX_PUSH_LOCK CmpLoadHiveLock
PCMHIVE CmpMasterHive
BOOLEAN CmpMiniNTBoot
PCM_NAME_HASH_TABLE_ENTRY CmpNameCacheTable
EX_PUSH_LOCK CmpPostLock
ERESOURCE CmpRegistryLock
HANDLE CmpRegistryRootHandle
BOOLEAN CmpSelfHeal
BOOLEAN CmpShareSystemHives
BOOLEAN CmpSpecialBootCondition
EX_PUSH_LOCK CmpStashBufferLock
PCM_TRACE_NOTIFY_ROUTINE CmpTraceRoutine
UNICODE_STRING CmRegistrySystemCloneName
POBJECT_TYPE IoFileObjectType
Macro Definition Documentation
#define _256K (256L*1024L)
Definition at line 31 of file cmp.h.
Referenced by CmpDoFileSetSize(), and HvRefreshHive().
#define _64K (64L*1024L)
Definition at line 30 of file cmp.h.
#define ASSERT_CM_EXCLUSIVE_HIVE_ACCESS (Hive)
Definition at line 333 of file cmp.h.
Referenced by CmpDeleteTree(), CmpDuplicateIndex(), CmpMarkKeyParentDirty(), CmpUpdateParentForEachSon(), and HvAutoCompressCheck().
#define ASSERT_CM_LOCK_NOT_OWNED ()
Definition at line 336 of file cmp.h.
#define ASSERT_CM_LOCK_OWNED ()
Definition at line 331 of file cmp.h.
Referenced by CmpCancelSlavePost(), CmpCheckNotifyAccess(), CmpCreateLinkNode(), CmpFlushNotify(), CmpLockTwoHashEntriesExclusive(), CmpLockTwoHashEntriesShared(), CmpNotifyChangeKey(), CmpParseKey(), CmpPostNotify(), CmpRunDownDelayDerefKCBEngine(), CmpTryToLockHashEntryByIndexExclusive(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), and HvDuplicateCell().
#define ASSERT_CM_LOCK_OWNED_EXCLUSIVE ()
Definition at line 332 of file cmp.h.
Referenced by CmCompressKey(), CmMoveKey(), CmpCheckKeyAccess(), CmpCmdInit(), CmpDoAccessCheckOnSubtree(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpDuplicateKey(), CmpFindReusableCellFromCache(), CmpFlushNotifiesOnKeyBodyList(), CmpFlushNotify(), CmpInitializeHiveList(), CmpIsHiveAlreadyLoaded(), CmpMarkCurrentValueDirty(), CmpRebuildSecurityCache(), CmpSearchForOpenSubKeys(), CmpShiftHiveFreeBins(), CmpUnlockRegistry(), CmRenameKey(), CmRestoreKey(), CmUnloadKeyEx(), and HvRefreshHive().
#define ASSERT_CM_LOCK_OWNED_EXCLUSIVE_OR_HIVE_LOADING (_CmHive_)
Definition at line 335 of file cmp.h.
Referenced by CmFlushKey(), and CmpCmdHiveClose().
#define ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING (_CmHive_)
Definition at line 334 of file cmp.h.
Referenced by HvpGetCellMapped(), HvpGetCellPaged(), and HvpReleaseCellMapped().
#define ASSERT_HASH_ENTRY_LOCKED (ConvKey)
Definition at line 2924 of file cmp.h.
Referenced by CmpUnlockTwoHashEntries().
#define ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE (ConvKey) ASSERT((GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Owner == KeGetCurrentThread()) || (CmpTestRegistryLockExclusive() == TRUE))
Definition at line 2927 of file cmp.h.
Referenced by CmpCreateLinkNode(), CmpDoCreate(), and CmpFreeKeyControlBlock().
#define ASSERT_HIVE_FLUSHER_LOCKED (_CmHive_)
Definition at line 847 of file cmp.h.
Referenced by CmpAddValueToList(), CmpFreeKeyByCell(), CmpMarkKeyDirty(), CmpMarkValueDataDirty(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), HvFreeCell(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpAddFreeCellHint(), HvpDelistFreeCell(), HvpDoAllocateCell(), HvpEnlistFreeCell(), HvpFindFreeCell(), HvpGrowLog1(), HvpGrowLog2(), and HvpRemoveFreeCellHint().
#define ASSERT_HIVE_FLUSHER_LOCKED_EXCLUSIVE (_CmHive_)
Definition at line 848 of file cmp.h.
Referenced by HvpDoWriteHive().
#define ASSERT_HIVE_LOCK_OWNED (_hive_)
Definition at line 872 of file cmp.h.
Referenced by CmpPostNotify().
#define ASSERT_HIVE_SECURITY_LOCK_OWNED (_hive_)
Definition at line 888 of file cmp.h.
Referenced by CmpAssignSecurityDescriptor(), CmpAssignSecurityDescriptorWrapper(), CmpFreeSecurityDescriptor(), CmpInsertSecurityCellList(), CmpRemoveSecurityCellList(), and CmpSetSecurityDescriptorInfo().
#define ASSERT_HIVE_WRITER_LOCK_OWNED (_CmHive_)
Definition at line 825 of file cmp.h.
Referenced by CmpDoFileSetSize(), CmpFileSetSize(), HvMarkDirty(), HvpAddBin(), HvpAddFreeCellHint(), HvpCoalesceDiscardedBins(), HvpDelistFreeCell(), HvpEnlistFreeCell(), HvpFindFreeCell(), HvpFindFreeCellInBin(), HvpIsFreeNeighbor(), and HvpRemoveFreeCellHint().
#define ASSERT_KCB_LOCKED (kcb)
Definition at line 2923 of file cmp.h.
Referenced by CmFlushKey(), CmpBuildHashStackAndLookupCache(), CmpCacheLookup(), CmpCompareNewValueDataAgainstKCBCache(), CmpDereferenceKeyControlBlockWithLock(), CmpDoOpen(), CmpFindValueByNameFromCache(), CmpGetSymbolicLink(), CmpGetValueDataFromCache(), CmpGetValueListFromCache(), CmpQueryKeyName(), CmpReferenceKeyControlBlock(), CmpSecurityMethod(), CmpTryConvertKCBLockSharedToExclusive(), CmSetValueKey(), and EnlistKeyBodyWithKCB().
#define ASSERT_KCB_LOCKED_EXCLUSIVE (kcb) ASSERT((CmpIsKCBLockedExclusive(kcb) == TRUE) || (CmpTestRegistryLockExclusive() == TRUE))
Definition at line 2926 of file cmp.h.
Referenced by CmpAddInfoAfterParseFailure(), CmpAssignSecurityDescriptorWrapper(), CmpCacheLookup(), CmpCleanUpKcbCacheWithLock(), CmpCleanUpKcbValueCache(), CmpCleanUpSubKeyInfo(), CmpCreateLinkNode(), CmpDereferenceKeyControlBlockWithLock(), CmpDoCreate(), CmpDoOpen(), CmpDumpKeyBodyList(), CmpFlushNotifiesOnKeyBodyList(), CmpParseKey(), CmpRebuildKcbCache(), CmpRemoveKeyControlBlock(), CmpRunDownDelayDerefKCBEngine(), CmpSetSecurityDescriptorInfo(), CmSetValueKey(), DelistKeyBodyFromKCB(), and EnlistKeyBodyWithKCB().
#define ASSERT_KEY_OBJECT (x) ASSERT(((PCM_KEY_BODY)x)->Type == KEY_BODY_TYPE)
Definition at line 511 of file cmp.h.
Referenced by CmpDumpOneKeyBody(), CmpFlushNotifiesOnKeyBodyList(), and CmpSecurityMethod().
#define ASSERT_KEYBODY_LIST_EMPTY (kcb)
Definition at line 498 of file cmp.h.
Referenced by CmpAddToDelayedClose(), and CmpFreeKeyControlBlock().
#define ASSERT_NODE (x) ASSERT(((PCM_KEY_NODE)x)->Signature == CM_KEY_NODE_SIGNATURE)
Definition at line 512 of file cmp.h.
Referenced by CmpAssignSecurityDescriptor(), CmpFreeSecurityDescriptor(), CmpGetKeySecurity(), and CmpInsertSecurityCellList().
#define ASSERT_PASSIVE_LEVEL ()
Definition at line 350 of file cmp.h.
Referenced by CmpCmdRenameHive(), CmpDoFileSetSize(), CmpFileFlush(), CmpFileRead(), CmpFileWrite(), CmpFileWriteThroughCache(), CmpInitializeHive(), CmpOpenFileWithExtremePrejudice(), and CmpOpenHiveFiles().
#define ASSERT_RESOURCE_NOT_OWNED (Res) ASSERT((ExIsResourceAcquiredShared(Res) == 0) && (ExIsResourceAcquiredExclusiveLite(Res) == 0))
Definition at line 2966 of file cmp.h.
#define ASSERT_RESOURCE_OWNED (Res) ASSERT((ExIsResourceAcquiredShared(Res) != 0) || (ExIsResourceAcquiredExclusiveLite(Res) != 0))
Definition at line 2967 of file cmp.h.
#define ASSERT_SECURITY (x) ASSERT(((PCM_KEY_SECURITY)x)->Signature == CM_KEY_SECURITY_SIGNATURE)
Definition at line 513 of file cmp.h.
Referenced by CmpFreeSecurityDescriptor(), CmpGetKeySecurity(), CmpInsertSecurityCellList(), and CmpSetSecurityDescriptorInfo().
#define ASSERT_VIEW_LOCK_OWNED (_hive_)
Definition at line 906 of file cmp.h.
Referenced by CmpDereferenceHiveView(), CmpMapCmView(), CmpMapThisBin(), CmpPinCmView(), CmpReferenceHiveView(), CmpTouchView(), CmpUnmapCmView(), and CmpUnmapCmViewSurroundingOffset().
#define ASSERT_VIEW_MAPPED (a)
Value:
ASSERT((a)->Size != 0);                             \
    ASSERT((a)->ViewAddress != 0);                      \
    ASSERT((a)->Bcb != 0);                              \
    ASSERT( IsListEmpty(&((a)->LRUViewList)) == FALSE); \
    ASSERT( IsListEmpty(&((a)->PinViewList)) == TRUE)
Definition at line 668 of file cmp.h.
Referenced by CmpPinCmView(), CmpUnmapCmViewSurroundingOffset(), HvMarkCellDirty(), HvMarkDirty(), HvpRecoverData(), and HvpRecoverWholeHive().
#define ASSERT_VIEW_PINNED (a)
Value:
ASSERT((a)->Size != 0);                             \
    ASSERT((a)->ViewAddress != 0);                      \
    ASSERT((a)->Bcb != 0);                              \
    ASSERT( IsListEmpty(&((a)->LRUViewList)) == TRUE)
Definition at line 675 of file cmp.h.
Referenced by CmpDestroyHiveViewList(), CmpUnPinCmView(), HvMarkCellDirty(), HvMarkDirty(), HvpRecoverData(), and HvpRecoverWholeHive().
#define BEGIN_LOCK_CHECKPOINT
Definition at line 312 of file cmp.h.
Referenced by CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpParseKey(), CmpQueryKeyName(), NtCompactKeys(), NtCompressKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtLoadKeyEx(), NtLockRegistryKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define ClearMasterPostBlockFlag (_post_) (((_post_)->NotifyType) &= ~REG_NOTIFY_MASTER_POST)
Definition at line 618 of file cmp.h.
Referenced by CmpPostNotify().
#define CLONE_HIVE_INDEX 6
Definition at line 444 of file cmp.h.
#define CM_CACHE_FAKE_KEY 0x00000001
Definition at line 264 of file cmp.h.
Referenced by CmpAddInfoAfterParseFailure().
#define CM_CHECK_REGISTRY_CHECK_CLEAN 0x00000001
Definition at line 1886 of file cmp.h.
Referenced by CmLoadKey(), CmpCheckKey(), CmpLoadHiveThread(), CmpLoadHiveVolatile(), and CmRestoreKey().
#define CM_CHECK_REGISTRY_FORCE_CLEAN 0x00000002
Definition at line 1887 of file cmp.h.
Referenced by CmpCheckKey(), and HvRefreshHive().
#define CM_CHECK_REGISTRY_HIVE_CHECK 0x00010000
Definition at line 1890 of file cmp.h.
Referenced by CmCheckRegistry().
#define CM_CHECK_REGISTRY_LOADER_CLEAN 0x00000004
Definition at line 1888 of file cmp.h.
Referenced by CmpCheckKey().
#define CM_CHECK_REGISTRY_SYSTEM_CLEAN 0x00000008
Definition at line 1889 of file cmp.h.
Referenced by CmpCheckKey(), and CmpInitializeSystemHive().
#define CM_CMHIVE_FLAG_UNTRUSTED 1
Definition at line 717 of file cmp.h.
Referenced by CmLoadKey(), CmpGetSymbolicLink(), and CmpOKToFollowLink().
#define CM_DONT_ADD_TO_HIVE_LIST 0x01000000
Definition at line 1891 of file cmp.h.
Referenced by CmpInitializeHive().
#define CM_FILE_GROW_INCREMENT 256L*1024L
Definition at line 63 of file cmp.h.
Referenced by CmpDoFileSetSize().
#define CM_HARDWARE_PROFILE_STR_ACPI_ALIAS L"AcpiAlias"
Definition at line 1916 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_ACPI_SERIAL_NUMBER L"AcpiSerialNumber"
Definition at line 1926 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_ALIAS L"Alias"
Definition at line 1915 of file cmp.h.
Referenced by CmpAddAliasEntry().
#define CM_HARDWARE_PROFILE_STR_ALIASABLE L"Aliasable"
Definition at line 1928 of file cmp.h.
Referenced by CmpFindProfileOption().
#define CM_HARDWARE_PROFILE_STR_CAPABILITIES L"Capabilities"
Definition at line 1923 of file cmp.h.
Referenced by CmpAddDockingInfo().
#define CM_HARDWARE_PROFILE_STR_CCS_CURRENT L"\\Registry\\Machine\\System\\CurrentControlSet\\Hardware Profiles\\Current"
Definition at line 1911 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_CCS_HWPROFILE L"\\Registry\\Machine\\System\\CurrentControlSet\\Hardware Profiles"
Definition at line 1910 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_CLONED L"Cloned"
Definition at line 1929 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_CURRENT_DOCK_INFO L"CurrentDockInfo"
Definition at line 1936 of file cmp.h.
Referenced by CmpCreateControlSet().
#define CM_HARDWARE_PROFILE_STR_DATABASE L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\IDConfigDB"
Definition at line 1909 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_DOCKED L"Docked"
Definition at line 1941 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_DOCKID L"DockID"
Definition at line 1924 of file cmp.h.
Referenced by CmpAddDockingInfo().
#define CM_HARDWARE_PROFILE_STR_DOCKING_STATE L"DockingState"
Definition at line 1922 of file cmp.h.
Referenced by CmpAddDockingInfo().
#define CM_HARDWARE_PROFILE_STR_FRIENDLY_NAME L"FriendlyName"
Definition at line 1935 of file cmp.h.
Referenced by CmpFindProfileOption().
#define CM_HARDWARE_PROFILE_STR_HARDWARE_PROFILES L"Hardware Profiles"
Definition at line 1917 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_HW_PROFILE_GUID L"HwProfileGuid"
Definition at line 1937 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_PREFERENCE_ORDER L"PreferenceOrder"
Definition at line 1934 of file cmp.h.
Referenced by CmpFindProfileOption().
#define CM_HARDWARE_PROFILE_STR_PRISTINE L"Pristine"
Definition at line 1933 of file cmp.h.
Referenced by CmpFindProfileOption().
#define CM_HARDWARE_PROFILE_STR_PROFILE_NUMBER L"ProfileNumber"
Definition at line 1927 of file cmp.h.
Referenced by CmpAddAliasEntry().
#define CM_HARDWARE_PROFILE_STR_SERIAL_NUMBER L"SerialNumber"
Definition at line 1925 of file cmp.h.
Referenced by CmpAddDockingInfo().
#define CM_HARDWARE_PROFILE_STR_UNDOCKED L"Undocked"
Definition at line 1942 of file cmp.h.
#define CM_HARDWARE_PROFILE_STR_UNKNOWN L"Unknown"
Definition at line 1943 of file cmp.h.
#define CM_HIVE_COMPRESS_LEVEL (25)
Definition at line 2709 of file cmp.h.
Referenced by HvAutoCompressCheck().
#define CM_HP_FLAGS_ALIASABLE 1
Definition at line 1973 of file cmp.h.
Referenced by CmpFindProfileOption().
#define CM_HP_FLAGS_DUPLICATE 8
Definition at line 1976 of file cmp.h.
#define CM_HP_FLAGS_PRISTINE 4
Definition at line 1975 of file cmp.h.
Referenced by CmpFindProfileOption().
#define CM_HP_FLAGS_TRUE_MATCH 2
Definition at line 1974 of file cmp.h.
#define CM_MAX_REASONABLE_VALUES 100
Definition at line 405 of file cmp.h.
Referenced by CmpAddValueToList().
#define CM_MAX_STASH 1024*1024
Definition at line 402 of file cmp.h.
#define CM_NUMBER_OF_MACHINE_HIVES 6
Definition at line 392 of file cmp.h.
Referenced by CmpInitializeHiveList(), CmpLoadHiveThread(), CmpRaiseSelfHealWarningForSystemHives(), and HvSyncHive().
#define CM_PAGED_CODE () PAGED_CODE()
Definition at line 2983 of file cmp.h.
Referenced by CmBootLastKnownGood(), CmDumpKey(), CmGetSystemDriverList(), CmInitSystem1(), CmIsLastKnownGoodBoot(), CmLockKcbForWrite(), CmNotifyRunDown(), CmpAcquireFileObjectForFile(), CmpAddAliasEntry(), CmpAddDockingInfo(), CmpAddSubKey(), CmpAddToDelayedClose(), CmpAddToDelayedDeref(), CmpAddValueToList(), CmpAllocateCmView(), CmpAllocateDelayItem(), CmpArmDelayedCloseTimer(), CmpAssignSecurityDescriptor(), CmpAssignSecurityDescriptorWrapper(), CmpBuildAndLockKcbArray(), CmpCancelSlavePost(), CmpCheckCreateAccess(), CmpCheckKeyAccess(), CmpCheckNotifyAccess(), CmpCleanUpKCBCacheTable(), CmpCloneControlSet(), CmpCloseKeyObject(), CmpCmdHiveClose(), CmpCmdHiveOpen(), CmpCmdInit(), CmpCmdRenameHive(), CmpCompareNewValueDataAgainstKCBCache(), CmpComputeKcbConvKey(), CmpConfigureProcessors(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreateRegistryRoot(), CmpCreateRootNode(), CmpCreateTemporaryHive(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDelayDerefKeyControlBlock(), CmpDelayedDerefKeys(), CmpDeleteKeyObject(), CmpDereferenceHiveView(), CmpDereferenceHiveViewWithLock(), CmpDestroyCmPrivateDelayAlloc(), CmpDestroyHiveViewList(), CmpDestroyTemporaryHive(), CmpDoQueueLateUnloadWorker(), CmpDropFileObjectForHive(), CmpDuplicateIndex(), CmpFindNameInList(), CmpFindSubKeyByHash(), CmpFindSubKeyByName(), CmpFindValueByName(), CmpFixHiveUsageCount(), CmpFlushNotify(), CmpFreeCmView(), CmpFreeDelayItem(), CmpFreeDriverList(), CmpFreeSecurityDescriptor(), CmpFreeSlavePost(), CmpFreeValue(), CmpFreeValueData(), CmpGetKeySecurity(), CmpGetValueData(), CmpHiveRootSecurityDescriptor(), CmpInitHiveFromFile(), CmpInitHiveViewList(), CmpInitializeHiveList(), CmpInitializeSystemHive(), CmpInsertSecurityCellList(), CmpInterlockedFunction(), CmpIsHiveAlreadyLoaded(), CmpLateUnloadHiveWorker(), CmpLazyFlush(), CmpLazyFlushWorker(), CmpLinkHiveToMaster(), CmpLinkKeyToHive(), CmpLoadHiveThread(), CmpLoadHiveVolatile(), CmpLogError(), CmpMapCmView(), CmpMapThisBin(), CmpMarkCurrentValueDirty(), CmpMarkValueDataDirty(), CmpNameFromAttributes(), CmpNotifyChangeKey(), CmpNotifyTriggerCheck(), CmpOverwriteHive(), CmpParseKey(), CmpPinCmView(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), CmpPrefetchHiveFile(), CmpQueryKeyDataFromCache(), CmpQuerySecurityDescriptorInfo(), CmpReferenceHiveView(), CmpReferenceHiveViewWithLock(), CmPrefetchHivePages(), CmpRefreshHive(), CmpRefreshWorkerRoutine(), CmpRehashKcbSubtree(), CmpReLockKcbArray(), CmpRemoveFromDelayedClose(), CmpRemoveSecurityCellList(), CmpRemoveSubKeyCellNoCellRef(), CmpRemoveValueFromList(), CmpReportNotify(), CmpReportNotifyHelper(), CmpRunDownDelayDerefKCBEngine(), CmpSaveKeyByFileCopy(), CmpSecurityMethod(), CmpSetSecurityDescriptorInfo(), CmpSetupPrivateWrite(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpShiftAllCells(), CmpShiftHiveFreeBins(), CmpShutdownWorkers(), CmpSwitchStorageAndRebuildMappings(), CmpTouchView(), CmpUnLockKcbArray(), CmpUnmapCmView(), CmpUnmapCmViewSurroundingOffset(), CmpUnmapUnusedViews(), CmpUnPinCmView(), CmpUpdateParentForEachSon(), CmpValueToData(), CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), CmQueryValueKey(), CmRestoreKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetLazyFlushState(), CmShutdownSystem(), CmUnloadKeyEx(), HvAutoCompressCheck(), HvDuplicateCell(), HvpAddBin(), HvpAddFreeCellHint(), HvpAdjustBitmap(), HvpAdjustHiveFreeDisplay(), HvpCheckViewBoundary(), HvpFindFreeCell(), HvpFindFreeCellInBin(), HvpFindFreeCellInThisViewWindow(), HvpFreeHiveFreeDisplay(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), HvReleaseFreeCellRefArray(), HvTrackCellRef(), NtCompactKeys(), NtCompressKey(), NtCreateKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtInitializeRegistry(), NtLoadKeyEx(), NtLockRegistryKey(), NtNotifyChangeKey(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define CM_TRACK_QUOTA_START ()
Definition at line 2870 of file cmp.h.
Referenced by CmInitSystem1().
#define CM_TRACK_QUOTA_STOP ()
Definition at line 2871 of file cmp.h.
#define CM_UNLOAD_KCB_LOCKED 1
Definition at line 1335 of file cmp.h.
Referenced by CmUnloadKey(), and NtUnloadKey2().
#define CM_UNLOAD_REG_LOCKED_EX 2
Definition at line 1336 of file cmp.h.
Referenced by CmpLateUnloadHiveWorker(), CmUnloadKey(), CmUnloadKeyEx(), and NtUnloadKey2().
#define CM_VIEW_SIZE 16L*1024L
Definition at line 57 of file cmp.h.
Referenced by CmpDoFileSetSize(), CmpFileWriteThroughCache(), CmpMapCmView(), HvpAddBin(), HvpCheckViewBoundary(), HvpDropPagedBins(), HvpFindFreeCell(), HvpFindFreeCellInThisViewWindow(), HvpScanForFreeCellInViewWindow(), HvRefreshHive(), and NtCompactKeys().
#define CM_WRAP_LIMIT 0x7fffffff
Definition at line 396 of file cmp.h.
Referenced by CmpComputeGlobalQuotaAllowed(), and CmSetRegistryQuotaInformation().
#define CmAreCallbacksRegistered () ((CmpCallBackCount != 0) && (0 == ExIsResourceAcquiredShared(&CmpRegistryLock)))
Definition at line 2831 of file cmp.h.
Referenced by CmpDeleteKeyObject(), CmpParseKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtRenameKey(), NtSetInformationKey(), and NtSetValueKey().
#define CmCloseHandle (Handle)
Value:
CmpSetHandleProtection(Handle,FALSE);   \
    ZwClose(Handle)
Definition at line 2809 of file cmp.h.
Referenced by CmpCmdHiveClose(), and CmpFileWrite().
#define CmDoSelfHeal () (CmpSelfHeal || (CmpBootType & (HBOOT_BACKUP|HBOOT_SELFHEAL)))
Definition at line 2847 of file cmp.h.
Referenced by CmpCheckKey(), CmpCheckRegistry2(), CmpCheckValueList(), CmpValidateHiveSecurityDescriptors(), HvLoadHive(), HvMapHive(), HvpBuildMap(), HvpEnlistBinInMap(), HvpEnlistFreeCells(), HvpGetLogHeader(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), and HvpRecoverData().
#define CmIsKcbReadOnly (kcb) ((kcb)->ExtFlags & CM_KCB_READ_ONLY_KEY)
Definition at line 2723 of file cmp.h.
Referenced by CmpCreateLinkNode(), CmpDoCreate(), CmpSearchForOpenSubKeys(), NtDeleteKey(), NtDeleteValueKey(), NtRenameKey(), NtReplaceKey(), NtRestoreKey(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define CmKdPrintEx (_x_) KdPrintEx(_x_)
Definition at line 51 of file cmp.h.
Referenced by CmCheckRegistry(), CmCompressKey(), CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmGetSystemDriverList(), CmInitSystem1(), CmIsLastKnownGoodBoot(), CmMoveKey(), CmNotifyRunDown(), CmpAcquireFileObjectForFile(), CmpAddAliasEntry(), CmpAddSubKey(), CmpAddToHiveFileList(), CmpAddToLeaf(), CmpAllocate(), CmpAssignSecurityDescriptor(), CmpCancelSlavePost(), CmpCheckCreateAccess(), CmpCheckKey(), CmpCheckNotifyAccess(), CmpCheckRegistry2(), CmpCheckValueList(), CmpCloneControlSet(), CmpCloseKeyObject(), CmpCopyCell(), CmpCopyKeyPartial(), CmpCopySyncTree(), CmpCopySyncTree2(), CmpCopyValue(), CmpCreateControlSet(), CmpCreateLinkNode(), CmpCreateObjectTypes(), CmpCreateRegistryRoot(), CmpCreateRootNode(), CmpDeleteKeyObject(), CmpDeleteTree(), CmpDestroyTemporaryHive(), CmpDoCreate(), CmpDoCreateChild(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpDoOpen(), CmpFileFlush(), CmpFileRead(), CmpFileSetSize(), CmpFileWrite(), CmpFileWriteThroughCache(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), CmpFindValueByNameFromCache(), CmpFixHiveUsageCount(), CmpFree(), CmpFreePostBlock(), CmpFreeSecurityDescriptor(), CmpFreeSlavePost(), CmpGetKeySecurity(), CmpGetSymbolicLink(), CmpHiveRootSecurityDescriptor(), CmpInitializeHive(), CmpInitializeHiveList(), CmpInitializeSystemHive(), CmpInsertSecurityCellList(), CmpLazyFlush(), CmpLazyFlushDpcRoutine(), CmpLazyFlushWorker(), CmpLinkHiveToMaster(), CmpLinkKeyToHive(), CmpLoadHiveThread(), CmpLockRegistry(), CmpMapCmView(), CmpNameFromAttributes(), CmpNotifyChangeKey(), CmpNotifyTriggerCheck(), CmpOpenFileWithExtremePrejudice(), CmpOpenHiveFiles(), CmpParseKey(), CmpPinCmView(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), CmpQueryKeyDataFromCache(), CmpQueryKeyName(), CmpQueryKeyValueData(), CmpQuerySecurityDescriptorInfo(), CmpRebuildSecurityCache(), CmpRemoveSecurityCellList(), CmpReportNotify(), CmpSecurityMethod(), CmpSelectLeaf(), CmpSetNetworkValue(), CmpSetSecurityDescriptorInfo(), CmpSetSystemValues(), CmpSetValueDataNew(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmpTouchView(), CmpUnPinCmView(), CmpValidateHiveSecurityDescriptors(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRenameKey(), CmRestoreKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), CmUnloadKey(), HvAllocateCell(), HvCheckBin(), HvCheckHive(), HvFreeCell(), HvFreeHive(), HvGetCellSize(), HvInitializeHive(), HvMapHive(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpBuildMap(), HvpBuildMapAndCopy(), HvpDoAllocateCell(), HvpDoWriteHive(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistBinInMap(), HvpFillFileName(), HvpFindFreeCell(), HvpFindFreeCellInBin(), HvpFindFreeCellInThisViewWindow(), HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpGetCellFlat(), HvpGetCellMap(), HvpGetCellMapped(), HvpGetCellPaged(), HvpGrowLog1(), HvpGrowLog2(), HvpInitMap(), HvpIsFreeNeighbor(), HvpMapFileImageAndBuildMap(), HvpReleaseCellMapped(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), HvpWriteLog(), HvReallocateCell(), HvSyncHive(), HvWriteHive(), NtCompactKeys(), NtCompressKey(), NtCreateKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtInitializeRegistry(), NtLoadKeyEx(), NtNotifyChangeKey(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define CML_BIN_MAP 15
Definition at line 285 of file cmp.h.
Referenced by CmpMapCmView(), CmpPinCmView(), CmpTouchView(), HvFreeHive(), HvInitializeHive(), HvpAddBin(), and HvpEnlistBinInMap().
#define CML_BUGCHECK 4
Definition at line 274 of file cmp.h.
Referenced by CmDumpKey(), CmFlushKey(), CmGetSystemDriverList(), CmInitSystem1(), CmpAddAliasEntry(), CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreateRegistryRoot(), CmpCreateRootNode(), CmpFileRead(), CmpFileSetSize(), CmpFileWrite(), CmpInitializeHive(), CmpInitializeHiveList(), CmpInitializeSystemHive(), CmpLinkHiveToMaster(), CmpLinkKeyToHive(), CmpOpenHiveFiles(), HvSyncHive(), and HvWriteHive().
#define CML_CHECK_HIVE 23
Definition at line 292 of file cmp.h.
#define CML_CM 8
Definition at line 278 of file cmp.h.
Referenced by CmCompressKey(), CmDeleteKey(), CmDeleteValueKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmMoveKey(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRenameKey(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), and CmUnloadKey().
#define CML_EXCEPTION 5
Definition at line 275 of file cmp.h.
Referenced by CmEnumerateValueKey(), CmNotifyRunDown(), CmpFindValueByNameFromCache(), CmpNameFromAttributes(), CmpSecurityMethod(), CmpSetValueDataNew(), CmpSetValueKeyNew(), CmQueryValueKey(), CmRenameKey(), CmSetValueKey(), NtCreateKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtLoadKeyEx(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define CML_FLOW 19
Definition at line 289 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpDeleteKeyObject(), CmpFreePostBlock(), HvGetCellSize(), HvpGetCellFlat(), HvpGetCellMap(), HvpGetCellMapped(), HvpGetCellPaged(), and HvpReleaseCellMapped().
#define CML_FREECELL 16
Definition at line 286 of file cmp.h.
Referenced by HvpDoAllocateCell(), HvpFindFreeCell(), HvpFindFreeCellInBin(), HvpFindFreeCellInThisViewWindow(), and HvpScanForFreeCellInViewWindow().
#define CML_HIVE 10
Definition at line 280 of file cmp.h.
Referenced by HvAllocateCell(), HvFreeCell(), HvpAddBin(), HvpBuildMap(), HvpBuildMapAndCopy(), HvpDoAllocateCell(), HvpEnlistBinInMap(), HvpFillFileName(), HvpFlushMappedData(), HvpInitMap(), HvpIsFreeNeighbor(), and HvReallocateCell().
#define CML_INDEX 14
Definition at line 284 of file cmp.h.
Referenced by CmpAddSubKey(), CmpAddToLeaf(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), CmpSelectLeaf(), and CmpSplitLeaf().
#define CML_INIT 13
Definition at line 283 of file cmp.h.
Referenced by CmInitSystem1(), CmIsLastKnownGoodBoot(), CmpInitializeHive(), CmpInitializeHiveList(), CmpLoadHiveThread(), and HvInitializeHive().
#define CML_IO 11
Definition at line 281 of file cmp.h.
Referenced by CmpDoFlushAll(), CmpDoFlushNextHive(), CmpFileFlush(), CmpFileRead(), CmpFileWrite(), CmpLazyFlush(), CmpLazyFlushDpcRoutine(), CmpLazyFlushWorker(), HvMarkCellDirty(), HvMarkDirty(), HvpDoWriteHive(), HvpFindNextDirtyBlock(), HvpGrowLog1(), HvpGrowLog2(), HvpWriteLog(), HvSyncHive(), and HvWriteHive().
#define CML_LOCKING 18
Definition at line 288 of file cmp.h.
Referenced by CmpLockRegistry().
#define CML_NOTIFY 9
Definition at line 279 of file cmp.h.
Referenced by CmpCancelSlavePost(), CmpFreeSlavePost(), CmpNotifyChangeKey(), CmpNotifyTriggerCheck(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), and CmpReportNotify().
#define CML_NTAPI 6
Definition at line 276 of file cmp.h.
Referenced by NtCompactKeys(), NtCompressKey(), NtCreateKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtInitializeRegistry(), NtLoadKeyEx(), NtNotifyChangeKey(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define CML_NTAPI_ARGS 7
Definition at line 277 of file cmp.h.
Referenced by NtCompactKeys(), NtCreateKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtLoadKeyEx(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtQueryMultipleValueKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtReplaceKey(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define CML_PARSE 20
Definition at line 290 of file cmp.h.
Referenced by CmpCreateLinkNode(), CmpDoCreate(), CmpDoCreateChild(), CmpDoOpen(), CmpGetSymbolicLink(), CmpParseKey(), and CmpQueryKeyName().
#define CML_POOL 17
Definition at line 287 of file cmp.h.
Referenced by CmpAllocate(), CmpCloseKeyObject(), CmpDoOpen(), CmpFree(), and CmpNotifyChangeKey().
#define CML_SAVRES 21
Definition at line 291 of file cmp.h.
Referenced by CmpCopyCell(), CmpCopyKeyPartial(), CmpCopySyncTree(), CmpCopySyncTree2(), CmpCopyValue(), CmpDeleteTree(), CmpDestroyTemporaryHive(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
#define CML_SEC 12
Definition at line 282 of file cmp.h.
Referenced by CmpAssignSecurityDescriptor(), CmpCheckCreateAccess(), CmpCheckNotifyAccess(), CmpFreeSecurityDescriptor(), CmpGetKeySecurity(), CmpHiveRootSecurityDescriptor(), CmpInsertSecurityCellList(), CmpQuerySecurityDescriptorInfo(), CmpRebuildSecurityCache(), CmpRemoveSecurityCellList(), CmpSetSecurityDescriptorInfo(), and CmpValidateHiveSecurityDescriptors().
#define CmLockHive (_hive_)
Value:
ExAcquirePushLockExclusive(&((_hive_)->HiveLock));\
                            CmLogLockHive(_hive_);\
                            ASSERT( (_hive_)->HiveLockOwner = KeGetCurrentThread() )
Definition at line 875 of file cmp.h.
Referenced by CmpCloseKeyObject(), CmpDoQueueLateUnloadWorker(), CmpFlushNotify(), CmpReportNotifyHelper(), and NtNotifyChangeMultipleKeys().
#define CmLockHiveSecurityExclusive (_hive_)
Value:
ExAcquirePushLockExclusive(&((_hive_)->SecurityLock));\
                                            ASSERT( (_hive_)->HiveSecurityLockOwner = KeGetCurrentThread() )
Definition at line 893 of file cmp.h.
Referenced by CmpCopyKeyPartial(), CmpDoCreateChild(), CmpFreeKeyByCell(), CmpSecurityMethod(), and CmpSyncKeyValues().
#define CmLockHiveSecurityShared (_hive_) ExAcquirePushLockShared(&((_hive_)->SecurityLock))
Definition at line 891 of file cmp.h.
Referenced by CmpAssignSecurityToKcb(), CmpCheckNotifyAccess(), CmpCopyKeyPartial(), and CmpSyncKeyValues().
#define CmLockHiveViews (_hive_)
Value:
ASSERT(((PCMHIVE)(_hive_))->ViewLock);\
                                    KeAcquireGuardedMutex(((PCMHIVE)(_hive_))->ViewLock);\
                                    ASSERT( ((PCMHIVE)(_hive_))->ViewLockOwner = KeGetCurrentThread() )
Definition at line 909 of file cmp.h.
Referenced by CmFlushKey(), CmpDereferenceHiveViewWithLock(), CmpReferenceHiveViewWithLock(), CmpUnmapUnusedViews(), CmpUnPinCmView(), HvMarkCellDirty(), HvMarkDirty(), HvpDropPagedBins(), HvpGetCellMapped(), HvpReleaseCellMapped(), HvpScanForFreeCellInViewWindow(), and HvWriteHive().
#define CmLogCellDeRef (HIVE, CELL)
Definition at line 806 of file cmp.h.
Referenced by HvpGetCellMapped(), and HvpReleaseCellMapped().
#define CmLogCellRef (HIVE, CELL)
Definition at line 805 of file cmp.h.
Referenced by HvpGetCellMapped().
#define CmLogLockHive (HIVE)
Definition at line 808 of file cmp.h.
#define CmLogUnlockHive (HIVE)
Definition at line 809 of file cmp.h.
#define CmMarkSelfHeal (Hive) ((Hive)->BaseBlock->BootType |= HBOOT_SELFHEAL)
Definition at line 2849 of file cmp.h.
Referenced by CmpCheckKey(), CmpCheckRegistry2(), CmpCheckValueList(), CmpValidateHiveSecurityDescriptors(), HvpBuildMap(), HvpEnlistFreeCells(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), and HvpRecoverData().
#define CMP_CREATE_KCB_FAKE 1
Definition at line 1733 of file cmp.h.
Referenced by CmpAddInfoAfterParseFailure(), and CmpCreateKeyControlBlock().
#define CMP_CREATE_KCB_KCB_LOCKED 2
Definition at line 1734 of file cmp.h.
Referenced by CmpAddInfoAfterParseFailure(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDoCreateChild(), CmpDoOpen(), and CmpParseKey().
#define CMP_DEST_UP 0x00000002
Definition at line 2733 of file cmp.h.
Referenced by CmpCacheLookup(), CmpCompareCompressedName(), CmpCompareUnicodeString(), and CmpGetNameControlBlock().
#define CMP_DO_OPEN_COMPLETE_KEY_CACHED 4
Definition at line 1735 of file cmp.h.
Referenced by CmpDoOpen(), and CmpParseKey().
#define CMP_ENLIST_KCB_LOCKED_EXCLUSIVE 2
Definition at line 502 of file cmp.h.
Referenced by CmpDoCreateChild(), CmpDoOpen(), and EnlistKeyBodyWithKCB().
#define CMP_ENLIST_KCB_LOCKED_SHARED 1
Definition at line 501 of file cmp.h.
Referenced by CmpDoOpen(), and EnlistKeyBodyWithKCB().
#define CMP_MAX_REGISTRY_DEPTH 512
Definition at line 2712 of file cmp.h.
Referenced by CmpCheckRegistry2(), CmpCreateKeyControlBlock(), CmpDoAccessCheckOnSubtree(), and CmpShiftAllCells2().
#define CMP_SOURCE_UP 0x00000001
Definition at line 2732 of file cmp.h.
Referenced by CmpCompareCompressedName(), and CmpCompareUnicodeString().
#define CmpAddKeyTracker (KeyHandle, mode)
Definition at line 484 of file cmp.h.
Referenced by NtCreateKey(), and NtOpenKey().
#define CmpAllocateMasterPostBlock (b) CmpAllocatePostBlock(b,REG_NOTIFY_MASTER_POST,NULL,NULL)
Definition at line 1814 of file cmp.h.
Referenced by NtNotifyChangeMultipleKeys().
#define CmpAllocateSlavePostBlock (b, k, m) CmpAllocatePostBlock(b,0,k,m)
Definition at line 1824 of file cmp.h.
Referenced by NtNotifyChangeMultipleKeys().
#define CmpAllocateTag (a, b, c) CmpAllocate(a,b,c)
Definition at line 247 of file cmp.h.
#define CmpCheckForOrphanedKcbs (Hive)
Definition at line 2707 of file cmp.h.
Referenced by CmpInitializeHive().
#define CmpCheckIfResourceOwned ()
Definition at line 310 of file cmp.h.
#define CmpCheckIoStatusPointer (AsyncUser)
Value:
if((PVOID)((AsyncUser).IoStatusBlock) == (PVOID)(&((AsyncUser).IoStatusBlock))) { \
        DbgPrint("IoStatusBlock pointing onto itself AsyncUser = %p\n",&(AsyncUser));   \
        DbgBreakPoint();                                                                \
    }
Definition at line 2418 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpPostApc(), and CmpPostApcRunDown().
#define CmpClearListEntry (a)
Definition at line 80 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpAllocateDelayItem(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpFlushNotify(), CmpFreePostBlock(), CmpPostNotify(), and CmpRunDownDelayDerefKCBEngine().
#define CmpCopyTree (s, c, t, l) CmpCopySyncTree(s,c,t,l,FALSE,Copy)
Definition at line 1633 of file cmp.h.
Referenced by CmpCloneControlSet(), CmpLoadHiveVolatile(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
#define CmpCopyTreeEx (s, c, t, l, f) CmpCopySyncTree(s,c,t,l,f,Copy)
Definition at line 1646 of file cmp.h.
Referenced by CmpSaveBootControlSet().
#define CmpDumpSecurityDescriptor (x, y)
Definition at line 375 of file cmp.h.
Referenced by CmpRebuildSecurityCache(), and CmpValidateHiveSecurityDescriptors().
#define CmpFreeMutex (_mutex_)
Value:
ASSERT(_mutex_);                      \
                                    ExFreePool(_mutex_)
Definition at line 2974 of file cmp.h.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), and CmUnloadKey().
#define CmpFreeResource (Resource)
Value:
ASSERT(Resource);                     \
                                    ASSERT_RESOURCE_NOT_OWNED( Resource );  \
                                    ExDeleteResourceLite( Resource );       \
                                    ExFreePool(Resource)
Definition at line 2969 of file cmp.h.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), and CmUnloadKey().
#define CmpHKeyNameLen (Key)
Value:
(((Key)->Flags & KEY_COMP_NAME) ? \
            CmpCompressedNameSize((Key)->Name,(Key)->NameLength) : \
            (Key)->NameLength)
Definition at line 925 of file cmp.h.
Referenced by CmpGetHiveName(), CmpLoadHiveVolatile(), and CmpQueryKeyData().
#define CmpHKeyNodeSize (Hive, KeyName) (FIELD_OFFSET(CM_KEY_NODE, Name) + CmpNameSize(Hive, KeyName))
Definition at line 935 of file cmp.h.
Referenced by CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreateChild(), and CmRenameKey().
#define CmpHKeyValueSize (Hive, ValueName) (FIELD_OFFSET(CM_KEY_VALUE, Name) + CmpNameSize(Hive, ValueName))
Definition at line 949 of file cmp.h.
Referenced by CmpSetValueKeyNew().
#define CmpIsKCBLockedExclusive (Kcb) (GET_KCB_HASH_ENTRY_OWNER(Kcb) == KeGetCurrentThread())
Definition at line 2898 of file cmp.h.
Referenced by CmEnumerateValueKey(), CmpAddToDelayedClose(), CmpCleanUpKCBCacheTable(), CmpCompareNewValueDataAgainstKCBCache(), CmpFindValueByNameFromCache(), CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpReferenceKeyControlBlock(), CmpRemoveFromDelayedClose(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), CmpTryConvertKCBLockSharedToExclusive(), CmQueryValueKey(), CmSetValueKey(), and CmUnloadKey().
#define CmpIsListEmpty (a) IsListEmpty(a)
Definition at line 81 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpAllocateDelayItem(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), and CmpRunDownDelayDerefKCBEngine().
#define CmpJoinClassOfTrust (_NewHive, _OtherHive)
Value:
CmpLockHiveListExclusive();                                                 \
InsertTailList(&(_OtherHive->TrustClassEntry),&(_NewHive->TrustClassEntry));\
CmpUnlockHiveList()
Definition at line 799 of file cmp.h.
Referenced by CmLoadKey().
#define CmpLockHashEntryByIndexExclusive (Index)
Value:
ExAcquirePushLockExclusive(&(CmpCacheTable[(Index)].Lock)); \
                                                CmpCacheTable[(Index)].Owner = KeGetCurrentThread()
Definition at line 2910 of file cmp.h.
Referenced by CmpBuildAndLockKcbArray(), CmpCleanUpKCBCacheTable(), CmpDoOpen(), CmpReLockKcbArray(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), and CmpSearchKeyControlBlockTree().
#define CmpLockHashEntryByIndexShared (Index) ExAcquirePushLockShared(&(CmpCacheTable[(Index)].Lock))
Definition at line 2908 of file cmp.h.
Referenced by CmpBuildAndLockKcbArray(), CmpReLockKcbArray(), and CmpWmiDumpKcbTable().
#define CmpLockHashEntryExclusive (ConvKey)
Value:
ExAcquirePushLockExclusive(&(GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Lock));\
                                            GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Owner = KeGetCurrentThread()
Definition at line 2902 of file cmp.h.
Referenced by CmpDelayCloseWorker(), and CmpLockTwoHashEntriesExclusive().
#define CmpLockHashEntryShared (ConvKey) ExAcquirePushLockShared(&(GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Lock))
Definition at line 2900 of file cmp.h.
Referenced by CmpLockTwoHashEntriesShared().
#define CmpLockHiveFlusherExclusive (CmHive) ExAcquirePushLockExclusive(&(((PCMHIVE)CmHive)->FlusherLock))
Definition at line 844 of file cmp.h.
Referenced by CmDumpKey(), CmFlushKey(), CmLoadKey(), CmpDestroyHive(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmSaveKey(), and CmSaveMergedKeys().
#define CmpLockHiveFlusherShared (CmHive) ExAcquirePushLockShared(&(((PCMHIVE)CmHive)->FlusherLock))
Definition at line 843 of file cmp.h.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmpCreateLinkNode(), CmpDoCreate(), CmpSecurityMethod(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), and CmSetValueKey().
#define CmpLockHiveListExclusive () ExAcquirePushLockExclusive(&CmpHiveListHeadLock)
Definition at line 641 of file cmp.h.
Referenced by CmLoadKey(), CmpDestroyHive(), CmpDestroyTemporaryHive(), and CmpInitializeHive().
#define CmpLockHiveListShared () ExAcquirePushLockShared(&CmpHiveListHeadLock)
Definition at line 640 of file cmp.h.
Referenced by CmIsFileLoadedAsHive(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpOKToFollowLink(), CmPrefetchHivePages(), and CmpUnmapUnusedViews().
#define CmpLockHiveWriter (_hive_)
Value:
ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING((PCMHIVE)(_hive_));\
                                    ExAcquirePushLockExclusive(&(((PCMHIVE)(_hive_))->WriterLock));\
                                    ASSERT( ((PCMHIVE)(_hive_))->WriterLockOwner = KeGetCurrentThread() )
Definition at line 814 of file cmp.h.
Referenced by HvFreeCell(), HvMarkCellDirty(), HvpDoAllocateCell(), and HvReallocateCell().
#define CmpLockKCBExclusive (Kcb)
Value:
ExAcquirePushLockExclusive(&(GET_KCB_HASH_ENTRY_LOCK((Kcb))));\
                                            GET_KCB_HASH_ENTRY_OWNER(Kcb) = KeGetCurrentThread()
Definition at line 2892 of file cmp.h.
Referenced by CmDeleteValueKey(), CmLockKcbForWrite(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpGetSymbolicLink(), CmpSecurityMethod(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), DelistKeyBodyFromKCB(), and EnlistKeyBodyWithKCB().
#define CmpLockKCBShared (Kcb) ExAcquirePushLockShared(&(GET_KCB_HASH_ENTRY_LOCK((Kcb))))
Definition at line 2890 of file cmp.h.
Referenced by CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmpCacheLookup(), CmpQueryKeyName(), CmpSecurityMethod(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmSaveKey(), CmSetValueKey(), and NtFlushKey().
#define CmpLockNameHashEntryExclusive (ConvKey) ExAcquirePushLockExclusive(&(GET_HASH_ENTRY(CmpNameCacheTable,(ConvKey)).Lock))
Definition at line 2918 of file cmp.h.
Referenced by CmpDereferenceNameControlBlockWithLock(), and CmpGetNameControlBlock().
#define CmpMakeSpecialPoolReadOnly (a)
Definition at line 143 of file cmp.h.
Referenced by CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), and CmpGetValueListFromCache().
#define CmpMakeSpecialPoolReadWrite (a)
Definition at line 144 of file cmp.h.
Referenced by CmpCleanUpKcbValueCache(), CmpGetValueDataFromCache(), and CmpGetValueKeyFromCache().
#define CmpMakeValueCacheReadOnly (a, b)
Definition at line 145 of file cmp.h.
#define CmpMakeValueCacheReadWrite (a, b)
Definition at line 146 of file cmp.h.
#define CmpMarkAllBinsReadOnly (a)
Definition at line 150 of file cmp.h.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), and CmSetValueKey().
#define CmpMergeTrees (s, c, t, l) CmpCopySyncTree(s,c,t,l,FALSE,Merge)
Definition at line 1670 of file cmp.h.
Referenced by CmSaveMergedKeys().
#define CmpNcbNameLen (Ncb)
Value:
(((Ncb)->Compressed) ? \
            CmpCompressedNameSize((Ncb)->Name,(Ncb)->NameLength) : \
            (Ncb)->NameLength)
Definition at line 930 of file cmp.h.
#define CmPostCallbackNotification (Type, _Object_, _Status_)
Value:
if(CmAreCallbacksRegistered()) {                          \
        REG_POST_OPERATION_INFORMATION PostInfo;                \
        PostInfo.Object = _Object_;                             \
        PostInfo.Status = _Status_;                             \
        CmpCallCallBacks(Type,&PostInfo,FALSE,Type,_Object_);   \
    }
Definition at line 2833 of file cmp.h.
Referenced by CmpDeleteKeyObject(), CmpParseKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtRenameKey(), NtSetInformationKey(), and NtSetValueKey().
#define CmpParseGetOriginatingPoint (_Context) ARGUMENT_PRESENT(_Context)?((PCM_PARSE_CONTEXT)(_Context))->OriginatingPoint:NULL
Definition at line 982 of file cmp.h.
Referenced by CmpCreateLinkNode(), and CmpParseKey().
#define CmpParseRecordOriginatingPoint (_Context, _CmHive)
Value:
if(ARGUMENT_PRESENT(_Context) && (((PCM_PARSE_CONTEXT)(_Context))->OriginatingPoint == NULL) &&    \
    (((PCMHIVE)_CmHive)->Flags&CM_CMHIVE_FLAG_UNTRUSTED) ){                                         \
    ((PCM_PARSE_CONTEXT)(_Context))->OriginatingPoint = (PCMHIVE)_CmHive;                           \
}
Definition at line 976 of file cmp.h.
Referenced by CmpParseKey().
#define CmpRemoveEntryList (a) RemoveEntryList(a)
Definition at line 79 of file cmp.h.
Referenced by CmLoadKey(), CmNotifyRunDown(), CmpCancelSlavePost(), CmpDestroyHive(), CmpDestroySecurityCache(), CmpDestroyTemporaryHive(), CmpFreeDelayItem(), CmpFreeSlavePost(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), CmpRemoveFromDelayedClose(), CmpRemoveFromSecurityCache(), CmpSetSecurityDescriptorInfo(), and NtNotifyChangeMultipleKeys().
#define CmpSecHashTableSize 64
Definition at line 695 of file cmp.h.
Referenced by CmpAddSecurityCellToCache(), CmpFindMatchingDescriptorCell(), CmpInitSecurityCache(), CmpRebuildSecurityCache(), and CmpSetSecurityDescriptorInfo().
#define CmpSetHandleProtection (Handle, Protection)
Value:
{                                                                       \
    OBJECT_HANDLE_FLAG_INFORMATION  Ohfi = {    FALSE,                  \
                                                FALSE                   \
                                            };                          \
    Ohfi.ProtectFromClose = Protection;                                 \
    ZwSetInformationObject( Handle,                                     \
                            ObjectHandleFlagInformation,                \
                            &Ohfi,                                      \
                            sizeof (OBJECT_HANDLE_FLAG_INFORMATION));   \
}
Definition at line 2797 of file cmp.h.
Referenced by CmpFileWrite(), and CmpInitHiveFromFile().
#define CmpSetIoStatus (Iosb, s, i, UseIosb32)
Value:
(Iosb)->Status = (s);                                                      \
(Iosb)->Information = (i);                                                 \
Definition at line 2412 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpPostApc(), CmpPostApcRunDown(), and NtNotifyChangeMultipleKeys().
#define CmpSetNoCallers (KeyBody)
Definition at line 483 of file cmp.h.
Referenced by EnlistKeyBodyWithKCB().
#define CmpSetUpKcbValueCache (KeyControlBlock, _Count, _List)
Value:
ASSERT(!(CMP_IS_CELL_CACHED(KeyControlBlock->ValueCache.ValueList))); \
    ASSERT( !(KeyControlBlock->ExtFlags & CM_KCB_SYM_LINK_FOUND) );         \
    KeyControlBlock->ValueCache.Count = (ULONG)(_Count);                    \
    KeyControlBlock->ValueCache.ValueList = (ULONG_PTR)(_List)
Definition at line 2266 of file cmp.h.
Referenced by CmDeleteValueKey(), CmEnumerateValueKey(), CmpCompareNewValueDataAgainstKCBCache(), CmpRebuildKcbCache(), CmpSwitchStorageAndRebuildMappings(), CmQueryValueKey(), CmRestoreKey(), and CmSetValueKey().
#define CmpSyncTrees (s, c, t, l, f) CmpCopySyncTree(s,c,t,l,f,Sync)
Definition at line 1658 of file cmp.h.
Referenced by CmpSaveBootControlSet().
#define CmpTraceKcbCreate (kcb)
Value:
if (CmpTraceRoutine) {\
        CmpWmiDumpKcb(kcb);\
    }
Definition at line 138 of file cmp.h.
Referenced by CmpCreateKeyControlBlock().
#define CmpUnJoinClassOfTrust (CmHive)
Value:
if(!IsListEmpty(&(CmHive->TrustClassEntry))) {            \
    ASSERT(CmHive->Flags&CM_CMHIVE_FLAG_UNTRUSTED);         \
    CmpLockHiveListExclusive();                             \
    RemoveEntryList(&(CmHive->TrustClassEntry));            \
    CmpUnlockHiveList();                                    \
}
Definition at line 792 of file cmp.h.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpInitializeHive(), CmShutdownSystem(), and CmUnloadKey().
#define CmpUnlockHashEntry (ConvKey)
Value:
GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Owner = NULL;\
                                            ExReleasePushLock(&(GET_HASH_ENTRY(CmpCacheTable,(ConvKey)).Lock))
Definition at line 2905 of file cmp.h.
Referenced by CmpCreateKeyControlBlock(), CmpDelayCloseWorker(), CmpDereferenceKeyControlBlock(), CmpGetSymbolicLink(), and CmpUnlockTwoHashEntries().
#define CmpUnlockHashEntryByIndex (Index)
Value:
CmpCacheTable[(Index)].Owner = NULL; \
                                                ExReleasePushLock(&(CmpCacheTable[(Index)].Lock))
Definition at line 2915 of file cmp.h.
Referenced by CmpCleanUpKCBCacheTable(), CmpDoOpen(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), CmpSearchKeyControlBlockTree(), CmpUnLockKcbArray(), and CmpWmiDumpKcbTable().
#define CmpUnlockHiveFlusher (CmHive) ExReleasePushLock(&(((PCMHIVE)CmHive)->FlusherLock))
Definition at line 845 of file cmp.h.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmFlushKey(), CmLoadKey(), CmpCreateLinkNode(), CmpDestroyHive(), CmpDoCreate(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpSecurityMethod(), CmSaveKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), and CmSetValueKey().
#define CmpUnlockHiveList () ExReleasePushLock(&CmpHiveListHeadLock)
Definition at line 642 of file cmp.h.
Referenced by CmIsFileLoadedAsHive(), CmLoadKey(), CmpDestroyHive(), CmpDestroyTemporaryHive(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpInitializeHive(), CmpOKToFollowLink(), CmPrefetchHivePages(), and CmpUnmapUnusedViews().
#define CmpUnlockHiveWriter (_hive_)
Value:
ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING((PCMHIVE)(_hive_));\
                             ASSERT_HIVE_WRITER_LOCK_OWNED((PCMHIVE)(_hive_));\
                             ASSERT( (((PCMHIVE)(_hive_))->WriterLockOwner = NULL) == NULL);\
                             ExReleasePushLock(&(((PCMHIVE)(_hive_))->WriterLock))
Definition at line 818 of file cmp.h.
Referenced by HvFreeCell(), HvMarkCellDirty(), HvpDoAllocateCell(), and HvReallocateCell().
#define CmpUnlockKCB (Kcb)
Value:
GET_KCB_HASH_ENTRY_OWNER(Kcb) = NULL;\
                                            ExReleasePushLock(&(GET_KCB_HASH_ENTRY_LOCK((Kcb))))
Definition at line 2895 of file cmp.h.
Referenced by CmDeleteValueKey(), CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmLockKcbForWrite(), CmpCacheLookup(), CmpGetSymbolicLink(), CmpQueryKeyName(), CmpSecurityMethod(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmSaveKey(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), DelistKeyBodyFromKCB(), EnlistKeyBodyWithKCB(), and NtFlushKey().
#define CmpUnlockNameHashEntry (ConvKey) ExReleasePushLock(&(GET_HASH_ENTRY(CmpNameCacheTable,(ConvKey)).Lock))
Definition at line 2919 of file cmp.h.
Referenced by CmpDereferenceNameControlBlockWithLock(), and CmpGetNameControlBlock().
#define CmpUpgradeKCBLockToExclusive (kcb)
Value:
ASSERT(CmpIsKCBLockedExclusive(kcb) == FALSE); \
                                            CmpUnlockKCB(kcb);                               \
                                            CmpLockKCBExclusive(kcb)
Definition at line 2930 of file cmp.h.
Referenced by CmEnumerateValueKey(), CmpReferenceKeyControlBlock(), CmQueryValueKey(), and CmSetValueKey().
#define CmpValueNameLen (Value)
Value:
(((Value)->Flags & VALUE_COMP_NAME) ?                           \
            CmpCompressedNameSize((Value)->Name,(Value)->NameLength) :  \
            (Value)->NameLength)
Definition at line 944 of file cmp.h.
Referenced by CmpQueryKeyValueData().
#define CmpWmiFireEvent (Status, Kcb, ElapsedTime, Index, KeyName, Type)
Value:
{                                                               \
    PCM_TRACE_NOTIFY_ROUTINE TraceRoutine = CmpTraceRoutine;        \
    if( TraceRoutine != NULL ) {                                    \
        (*TraceRoutine)(Status,Kcb,ElapsedTime,Index,KeyName,Type); \
    }                                                               \
}
Definition at line 90 of file cmp.h.
#define CmRetryExAllocatePoolWithTag (a, b, c, Result)
Value:
{                                               \
        ULONG   RetryCount = 10;                    \
        do {                                        \
            Result = ExAllocatePoolWithTag(a,b,c);  \
        } while ((!Result) && (RetryCount--));      \
    }
Definition at line 250 of file cmp.h.
Referenced by CmpAddSecurityCellToCache(), CmpAdjustSecurityCacheSize(), and CmpCheckRegistry2().
#define CmUnlockHive (_hive_)
Value:
ASSERT_HIVE_LOCK_OWNED(_hive_);\
                             ASSERT( ((_hive_)->HiveLockOwner = NULL) == NULL);\
                             CmLogUnlockHive(_hive_);\
                             ExReleasePushLock(&((_hive_)->HiveLock))
Definition at line 879 of file cmp.h.
Referenced by CmpCloseKeyObject(), CmpDoQueueLateUnloadWorker(), CmpFlushNotify(), CmpReportNotifyHelper(), and NtNotifyChangeMultipleKeys().
#define CmUnlockHiveSecurity (_hive_)
Value:
ASSERT(((_hive_)->HiveSecurityLockOwner == NULL) || ((_hive_)->HiveSecurityLockOwner == KeGetCurrentThread()));\
                                        ASSERT( ((_hive_)->HiveSecurityLockOwner = NULL) == NULL);\
                                        ExReleasePushLock(&((_hive_)->SecurityLock))
Definition at line 896 of file cmp.h.
Referenced by CmpAssignSecurityToKcb(), CmpCheckNotifyAccess(), CmpCopyKeyPartial(), CmpDoCreateChild(), CmpFreeKeyByCell(), CmpSecurityMethod(), and CmpSyncKeyValues().
#define CmUnlockHiveViews (_hive_)
Value:
ASSERT(((PCMHIVE)(_hive_))->ViewLock);\
                                    ASSERT_VIEW_LOCK_OWNED((PCMHIVE)(_hive_));\
                                    ASSERT( (((PCMHIVE)(_hive_))->ViewLockOwner = NULL) == NULL);\
                                    KeReleaseGuardedMutex(((PCMHIVE)(_hive_))->ViewLock)
Definition at line 913 of file cmp.h.
Referenced by CmFlushKey(), CmpDereferenceHiveViewWithLock(), CmpReferenceHiveViewWithLock(), CmpUnmapUnusedViews(), CmpUnPinCmView(), HvMarkCellDirty(), HvMarkDirty(), HvpDropPagedBins(), HvpGetCellMapped(), HvpReleaseCellMapped(), HvpScanForFreeCellInViewWindow(), and HvWriteHive().
#define CmUpcaseUnicodeChar (c) (((c) < 'a') ? (c) : (((c) > 'z') ? RtlUpcaseUnicodeChar(c) : ((c) - ('a'-'A'))))
Definition at line 2876 of file cmp.h.
Referenced by CmpCompareCompressedName(), CmpCompareInIndex(), CmpCompareTwoCompressedNames(), CmpCompareUnicodeString(), CmpComputeHashKey(), CmpComputeHashKeyForCompressedName(), CmpComputeHashValue(), CmpComputeKcbConvKey(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDoCreate(), CmpGetNameControlBlock(), and CmpGetSymbolicLink().
#define DCmCheckRegistry (a)
Definition at line 306 of file cmp.h.
Referenced by CmFlushKey(), CmpSetSecurityDescriptorInfo(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
#define END_LOCK_CHECKPOINT
Definition at line 313 of file cmp.h.
Referenced by CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpParseKey(), CmpQueryKeyName(), NtCompactKeys(), NtCompressKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtLoadKeyEx(), NtLockRegistryKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryValueKey(), NtRenameKey(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetInformationKey(), NtSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define EndWmiCmTrace (Status, Index, KeyName, Type)
Value:
if (CmpTraceRoutine) {\
        PerfTimeStamp(EndSystemTime); \
        CmpWmiFireEvent(Status,HookKcb,EndSystemTime.QuadPart - StartSystemTime.QuadPart,Index,KeyName,Type);\
    }
Definition at line 107 of file cmp.h.
Referenced by NtCreateKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtOpenKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtSetInformationKey(), and NtSetValueKey().
#define ENTER_FLUSH_MODE () InterlockedIncrement (&CmpFlushStarveWriters);
Definition at line 1487 of file cmp.h.
Referenced by CmpLazyFlushWorker(), CmSaveKey(), and CmSaveMergedKeys().
#define EXIT_FLUSH_MODE () InterlockedDecrement (&CmpFlushStarveWriters)
Definition at line 1496 of file cmp.h.
Referenced by CmpLazyFlushWorker(), CmSaveKey(), and CmSaveMergedKeys().
#define GET_HASH_ENTRY (Table, Key) Table[GET_HASH_INDEX(Key)]
Definition at line 455 of file cmp.h.
Referenced by CmpDereferenceNameControlBlockWithLock().
#define GET_HASH_INDEX (Key) HASH_KEY(Key) % CmpHashTableSize
Definition at line 454 of file cmp.h.
Referenced by CmpBuildAndLockKcbArray(), CmpBuildHashStackAndLookupCache(), CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpDoOpen(), CmpGetNameControlBlock(), CmpGetSymbolicLink(), CmpInsertKeyHash(), CmpLockTwoHashEntriesExclusive(), CmpLockTwoHashEntriesShared(), CmpRemoveKeyHash(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), and CmpUnlockTwoHashEntries().
#define GET_KCB_HASH_ENTRY (Table, Key) GET_HASH_ENTRY(Table, Key).Entry
Definition at line 456 of file cmp.h.
Referenced by CmpCacheLookup(), and CmpGetSymbolicLink().
#define GET_KCB_HASH_ENTRY_LOCK (kcb) (GET_HASH_ENTRY(CmpCacheTable,(kcb)->ConvKey).Lock)
Definition at line 457 of file cmp.h.
Referenced by CmpTryConvertKCBLockSharedToExclusive().
#define GET_KCB_HASH_ENTRY_OWNER (kcb) (GET_HASH_ENTRY(CmpCacheTable,(kcb)->ConvKey).Owner)
Definition at line 458 of file cmp.h.
Referenced by CmpTryConvertKCBLockSharedToExclusive().
#define HASH_KEY (_convkey_) ((RNDM_CONSTANT * (_convkey_)) % RNDM_PRIME)
Definition at line 452 of file cmp.h.
#define HiveWritesThroughCache (Hive, FileType) ((FileType == HFILE_TYPE_PRIMARY) && (((PCMHIVE)CONTAINING_RECORD(Hive, CMHIVE, Hive))->FileObject != NULL))
Definition at line 853 of file cmp.h.
Referenced by CmpDoFileSetSize(), CmpFileFlush(), CmpFileWriteThroughCache(), and HvpDoWriteHive().
#define HookKcbForWmiCmTrace (KeyBody)
Value:
if (CmpTraceRoutine) {\
        if(KeyBody) {\
            HookKcb = KeyBody->KeyControlBlock;\
        }\
    }
Definition at line 113 of file cmp.h.
Referenced by NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtSetInformationKey(), and NtSetValueKey().
#define HookKcbFromHandleForWmiCmTrace (KeyHandle)
Value:
if (CmpTraceRoutine && (KeyHandle)) {\
        PCM_KEY_BODY KeyBody;\
        NTSTATUS status;\
        status = ObReferenceObjectByHandle(\
                    KeyHandle,\
                    0,\
                    CmpKeyObjectType,\
                    KeGetPreviousMode(),\
                    (PVOID *)(&KeyBody),\
                    NULL\
                    );\
        if (NT_SUCCESS(status)) {\
            HookKcb = KeyBody->KeyControlBlock;\
            ObDereferenceObject((PVOID)KeyBody);\
        }\
    }
Definition at line 120 of file cmp.h.
Referenced by NtCreateKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtOpenKey(), NtQueryKey(), NtQueryValueKey(), and NtSetInformationKey().
#define HvpChangeBinAllocation (a, b)
Definition at line 148 of file cmp.h.
#define HvpMarkBinReadWrite (a, b)
Definition at line 149 of file cmp.h.
Referenced by HvMarkDirty().
#define INIT_SYSTEMROOT_HIVEPATH L"\\SystemRoot\\System32\\Config\\"
Definition at line 2758 of file cmp.h.
Referenced by CmpInitializeHiveList(), and CmpLoadHiveThread().
#define IO_BUFFER_SIZE _64K
Definition at line 32 of file cmp.h.
Referenced by HvpReadFileImageAndBuildMap().
#define IsHiveFrozen (_CmHive_) (((PCMHIVE)(_CmHive_))->Frozen == TRUE)
Definition at line 851 of file cmp.h.
Referenced by CmpCreateKeyControlBlock(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpDoFlushNextHive(), CmpIsHiveAlreadyLoaded(), CmpLoadHiveVolatile(), CmpRefreshHive(), CmpRunDownDelayDerefKCBEngine(), CmRestoreKey(), CmUnloadKeyEx(), and NtUnloadKey2().
#define IsMasterPostBlock (_post_) (((_post_)->NotifyType) & REG_NOTIFY_MASTER_POST)
Definition at line 616 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpAllocatePostBlock(), CmpCancelSlavePost(), CmpFreePostBlock(), CmpFreeSlavePost(), CmpNotifyChangeKey(), and CmpPostNotify().
#define KCB_WORKER_CONTINUE 0
Definition at line 1068 of file cmp.h.
Referenced by CmpCompressKeyWorker(), CmpRefreshWorkerRoutine(), and CmpSearchKeyControlBlockTree().
#define KCB_WORKER_DELETE 2
Definition at line 1070 of file cmp.h.
Referenced by CmpRefreshWorkerRoutine(), and CmpSearchKeyControlBlockTree().
#define KCB_WORKER_DONE 1
Definition at line 1069 of file cmp.h.
Referenced by CmpSearchKeyControlBlockTree().
#define KCB_WORKER_ERROR 3
Definition at line 1071 of file cmp.h.
Referenced by CmpCompressKeyWorker(), and CmpSearchKeyControlBlockTree().
#define KEY_BODY_HIVE_UNLOADED 0x00000001
Definition at line 471 of file cmp.h.
#define KEY_BODY_TYPE 0x6b793032
Definition at line 469 of file cmp.h.
Referenced by CmpCloseKeyObject(), CmpCreateRegistryRoot(), CmpDelayedDerefKeys(), CmpDeleteKeyObject(), CmpDoCreateChild(), and CmpDoOpen().
#define LOCK_HIVE_LOAD () ExAcquirePushLockExclusive(&CmpLoadHiveLock)
Definition at line 648 of file cmp.h.
Referenced by CmLoadKey(), CmpLazyFlushWorker(), and NtUnloadKey2().
#define LOCK_POST_LIST () ExAcquirePushLockExclusive(&CmpPostLock)
Definition at line 627 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpPostNotify(), and NtNotifyChangeMultipleKeys().
#define LOCK_STASH_BUFFER () ExAcquirePushLockExclusive(&CmpStashBufferLock)
Definition at line 632 of file cmp.h.
Referenced by CmpAcquireFileObjectForFile(), CmpSaveKeyByFileCopy(), HvpRecoverData(), HvpWriteLog(), and HvRefreshHive().
#define LogKCBReference (kcb, reason)
Definition at line 309 of file cmp.h.
Referenced by CmpDelayDerefKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), and CmpReferenceKeyControlBlock().
#define MAX_HIVE_LAYERS 2
Definition at line 416 of file cmp.h.
#define MAX_MB_PER_HIVE 16
Definition at line 74 of file cmp.h.
#define MAX_NAME 128
Definition at line 77 of file cmp.h.
#define MAX_VIEWS_PER_HIVE MAX_MB_PER_HIVE * ((_256K) / (CM_VIEW_SIZE))
Definition at line 666 of file cmp.h.
#define NUMBER_TYPES (MaximumType + 1)
Definition at line 394 of file cmp.h.
Referenced by CmpSetupConfigurationTree().
#define PostBlockType (_post_) ((POST_BLOCK_TYPE)(((_post_)->NotifyType) & REG_NOTIFY_POST_TYPE_MASK))
Definition at line 614 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpFreeAllMemory(), CmpFreePostBlock(), CmpNotifyTriggerCheck(), and CmpPostNotify().
#define REG_NOTIFY_MASTER_POST (0x00010000L)
Definition at line 609 of file cmp.h.
Referenced by CmpFreePostBlock().
#define REG_NOTIFY_POST_TYPE_MASK (0x0000FFFFL)
Definition at line 607 of file cmp.h.
#define REG_OPTION_PREDEF_HANDLE (0x01000000L)
Definition at line 961 of file cmp.h.
Referenced by CmpCreatePredefined(), CmpDoCreateChild(), and NtCreateKey().
#define REG_PREDEF_HANDLE_MASK (0x80000000L)
Definition at line 962 of file cmp.h.
Referenced by CmpDeleteKeyObject().
#define REGCHECKING 1
Definition at line 295 of file cmp.h.
#define RNDM_CONSTANT 314159269 /* default value for "scrambling constant" */
Definition at line 449 of file cmp.h.
#define RNDM_PRIME 1000000007 /* prime number, also used for scrambling */
Definition at line 450 of file cmp.h.
#define SECOND_MULT 10*1000*1000
Definition at line 2964 of file cmp.h.
Referenced by CmpArmDelayedCloseTimer(), CmpCmdInit(), CmpDelayDerefKeyControlBlock(), and CmpLazyFlush().
#define SetMasterPostBlockFlag (_post_) (((_post_)->NotifyType) |= REG_NOTIFY_MASTER_POST)
Definition at line 617 of file cmp.h.
Referenced by CmpPostNotify().
#define StartWmiCmTrace ()
Value:
LARGE_INTEGER   StartSystemTime = {0};\
    LARGE_INTEGER   EndSystemTime;\
    PVOID           HookKcb = NULL;\
    if (CmpTraceRoutine) {\
        PerfTimeStamp(StartSystemTime); \
    }
Definition at line 98 of file cmp.h.
Referenced by NtCreateKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtFlushKey(), NtOpenKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtSetInformationKey(), and NtSetValueKey().
#define SYSTEM_HIVE_INDEX 3
Definition at line 443 of file cmp.h.
Referenced by CmpCanGrowSystemHive(), CmpInitializeSystemHive(), CmpLoadHiveThread(), CmpUpdateSystemHiveHysteresis(), CmRegisterSystemHiveLimitCallback(), and CmShutdownSystem().
#define UNLOCK_HIVE_LOAD () ExReleasePushLock(&CmpLoadHiveLock)
Definition at line 649 of file cmp.h.
Referenced by CmLoadKey(), CmpLazyFlushWorker(), CmUnloadKey(), and NtUnloadKey2().
#define UNLOCK_POST_LIST () ExReleasePushLock(&CmpPostLock)
Definition at line 628 of file cmp.h.
Referenced by CmNotifyRunDown(), CmpPostNotify(), and NtNotifyChangeMultipleKeys().
#define UNLOCK_STASH_BUFFER () ExReleasePushLock(&CmpStashBufferLock)
Definition at line 633 of file cmp.h.
Referenced by CmpAcquireFileObjectForFile(), CmpSaveKeyByFileCopy(), HvpRecoverData(), HvpWriteLog(), and HvRefreshHive().
#define VALIDATE_CELL_MAP (LINE, Map, Hive, Address)
Value:
if(Map == NULL) {                                                                             \
            CM_BUGCHECK (REGISTRY_ERROR,BAD_CELL_MAP,(ULONG_PTR)(Hive),(ULONG)(Address),(ULONG)(LINE)) ;      \
    }
Definition at line 353 of file cmp.h.
Referenced by CmpMapCmView(), CmpUnmapCmView(), HvFreeCell(), HvFreeHive(), HvFreeHivePartial(), HvHiveWillShrink(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpAddFreeCellHint(), HvpBuildMapAndCopy(), HvpCoalesceDiscardedBins(), HvpDelistBinFreeCells(), HvpDoAllocateCell(), HvpDoWriteHive(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistBinInMap(), HvpEnlistFreeCell(), HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpGetBinMemAlloc(), HvpRecoverData(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), HvpTruncateBins(), and HvRefreshHive().
Typedef Documentation
typedef struct _BOOT_DRIVER_NODE BOOT_DRIVER_NODE
typedef struct _CM_ASYNC_KERNEL_POST_BLOCK CM_ASYNC_KERNEL_POST_BLOCK
typedef struct _CM_ASYNC_USER_POST_BLOCK CM_ASYNC_USER_POST_BLOCK
typedef struct _CM_CELL_REMAP_BLOCK CM_CELL_REMAP_BLOCK
typedef struct _CM_DELAY_ALLOC CM_DELAY_ALLOC
typedef struct _CM_DELAYED_CLOSE_ENTRY CM_DELAYED_CLOSE_ENTRY
typedef struct _CM_HARDWARE_PROFILE CM_HARDWARE_PROFILE
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS CM_HARDWARE_PROFILE_ACPI_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_ALIAS CM_HARDWARE_PROFILE_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ALIAS_LIST CM_HARDWARE_PROFILE_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_LIST CM_HARDWARE_PROFILE_LIST
typedef struct _CM_KCB_REMAP_BLOCK CM_KCB_REMAP_BLOCK
typedef struct _CM_KEY_BODY CM_KEY_BODY
typedef struct _CM_KNODE_REMAP_BLOCK CM_KNODE_REMAP_BLOCK
typedef struct _CM_NOTIFY_BLOCK CM_NOTIFY_BLOCK
typedef struct _CM_PARSE_CONTEXT CM_PARSE_CONTEXT
typedef struct _CM_POST_BLOCK CM_POST_BLOCK
typedef union _CM_POST_BLOCK_UNION CM_POST_BLOCK_UNION
typedef struct _CM_POST_KEY_BODY CM_POST_KEY_BODY
typedef struct _CM_SYNC_POST_BLOCK CM_SYNC_POST_BLOCK
typedef struct _CM_VIEW_OF_FILE CM_VIEW_OF_FILE
typedef struct _CM_WRITE_BLOCK CM_WRITE_BLOCK
typedef struct _CMHIVE CMHIVE
typedef struct _HIVE_LIST_ENTRY HIVE_LIST_ENTRY
typedef struct _BOOT_DRIVER_NODE * PBOOT_DRIVER_NODE
typedef NTSTATUS(* PCM_ACPI_SELECTION_ROUTINE) (IN PCM_HARDWARE_PROFILE_LIST ProfileList, OUT PULONG ProfileIndexToUse, IN PVOID Context)
Definition at line 2153 of file cmp.h.
typedef struct _CM_ASYNC_KERNEL_POST_BLOCK * PCM_ASYNC_KERNEL_POST_BLOCK
typedef struct _CM_ASYNC_USER_POST_BLOCK * PCM_ASYNC_USER_POST_BLOCK
typedef struct _CM_CELL_REMAP_BLOCK * PCM_CELL_REMAP_BLOCK
typedef struct _CM_DELAY_ALLOC * PCM_DELAY_ALLOC
typedef struct _CM_DELAYED_CLOSE_ENTRY * PCM_DELAYED_CLOSE_ENTRY
typedef struct _CM_HARDWARE_PROFILE * PCM_HARDWARE_PROFILE
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS * PCM_HARDWARE_PROFILE_ACPI_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ACPI_ALIAS_LIST * PCM_HARDWARE_PROFILE_ACPI_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_ALIAS * PCM_HARDWARE_PROFILE_ALIAS
typedef struct _CM_HARDWARE_PROFILE_ALIAS_LIST * PCM_HARDWARE_PROFILE_ALIAS_LIST
typedef struct _CM_HARDWARE_PROFILE_LIST * PCM_HARDWARE_PROFILE_LIST
typedef struct _CM_KCB_REMAP_BLOCK * PCM_KCB_REMAP_BLOCK
typedef struct _CM_KEY_BODY * PCM_KEY_BODY
typedef struct _CM_KNODE_REMAP_BLOCK * PCM_KNODE_REMAP_BLOCK
typedef struct _CM_NOTIFY_BLOCK * PCM_NOTIFY_BLOCK
typedef struct _CM_PARSE_CONTEXT * PCM_PARSE_CONTEXT
typedef struct _CM_POST_BLOCK * PCM_POST_BLOCK
typedef union _CM_POST_BLOCK_UNION * PCM_POST_BLOCK_UNION
typedef struct _CM_POST_KEY_BODY * PCM_POST_KEY_BODY
typedef struct _CM_SYNC_POST_BLOCK * PCM_SYNC_POST_BLOCK
typedef struct _CM_VIEW_OF_FILE * PCM_VIEW_OF_FILE
typedef struct _CM_WRITE_BLOCK * PCM_WRITE_BLOCK
typedef struct _CMHIVE * PCMHIVE
typedef struct CMP_CHECK_REGISTRY_STACK_ENTRY * PCMP_CHECK_REGISTRY_STACK_ENTRY
typedef struct _HIVE_LIST_ENTRY * PHIVE_LIST_ENTRY
typedef ULONG(* PKCB_WORKER_ROUTINE) (PCM_KEY_CONTROL_BLOCK Current, PVOID Context1, PVOID Context2)
Definition at line 1075 of file cmp.h.
typedef enum _POST_BLOCK_TYPE POST_BLOCK_TYPE
typedef struct _QUERY_OPEN_SUBKEYS_CONTEXT * PQUERY_OPEN_SUBKEYS_CONTEXT
typedef struct _QUERY_OPEN_SUBKEYS_CONTEXT QUERY_OPEN_SUBKEYS_CONTEXT
typedef enum _VALUE_SEARCH_RETURN_TYPE VALUE_SEARCH_RETURN_TYPE
Enumeration Type Documentation
enum _POST_BLOCK_TYPE
Enumerator
PostSynchronous
PostAsyncUser
PostAsyncKernel
Definition at line 565 of file cmp.h.
enum _VALUE_SEARCH_RETURN_TYPE
Enumerator
SearchSuccess
SearchNeedExclusiveLock
SearchFail
Definition at line 2288 of file cmp.h.
Function Documentation
ULONG CmCheckRegistry (PCMHIVE CmHive, ULONG Flags)
Definition at line 111 of file cmchek.c.
References _HHIVE::BaseBlock, CM_CHECK_REGISTRY_HIVE_CHECK, CmCheckRegistryDebug, CmKdPrintEx, CmpCheckRegistry2(), CmpValidateHiveSecurityDescriptors(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FALSE, HCELL_NIL, Hive, _CMHIVE::Hive, HvCheckHive(), NULL, _HHIVE::ReleaseCellRoutine, and _HBASE_BLOCK::RootCell.
Referenced by CmpInitializeHive(), and HvRefreshHive().
NTSTATUS CmCompressKey (IN PHHIVE Hive)
Definition at line 4466 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, _CMHIVE::CellRemapArray, _CM_KEY_NODE::ChildHiveReference, CmKdPrintEx, CML_CM, CmpBuildSecurityCellMappingArray(), CmpCleanUpKCBCacheTable(), CmpCompressKeyWorker(), CmpDestroyTemporaryHive(), CmpMasterHive, CmpOverwriteHive(), CmpSearchKeyControlBlockTree(), CmpShiftHiveFreeBins(), CmpSwitchStorageAndRebuildMappings(), CmpUpdateSystemHiveHysteresis(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, _CMHIVE::Hive, HvAutoCompressCheck(), HvGetCell, HvpDropAllPagedBins(), HvReleaseCell, IsListEmpty, _CMHIVE::KcbConvertListHead, _CM_KEY_REFERENCE::KeyCell, _CMHIVE::KnodeConvertListHead, _HBASE_BLOCK::Length, NT_SUCCESS, NULL, PAGED_CODE, _CM_KEY_NODE::Parent, RemoveHeadList(), _HBASE_BLOCK::RootCell, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by CmShutdownSystem(), and NtCompressKey().
NTSTATUS CmDeleteKey (IN PCM_KEY_BODY KeyBody)
Definition at line 29 of file cmapi2.c.
References ASSERT, ASSERT_CELL_DIRTY, Cell, CmKdPrintEx, CML_CM, CmpCleanUpSubKeyInfo(), CmpFlushNotifiesOnKeyBodyList(), CmpFreeKeyByCell(), CmpLockHiveFlusherShared, CmpLockRegistry(), CmpLockTwoHashEntriesExclusive(), CmpMarkAllBinsReadOnly, CmpRemoveKeyControlBlock(), CmpReportNotify(), CmpUnlockHiveFlusher, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, KeQuerySystemTime(), KEY_NO_DELETE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_NODE::LastWriteTime, _CM_KEY_NODE::MaxNameLen, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, _CM_KEY_CONTROL_BLOCK::ParentKcb, PERFINFO_REG_DELETE_KEY, REG_NOTIFY_CHANGE_NAME, Stable, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by NtDeleteKey().
NTSTATUS CmDeleteValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName)
Definition at line 169 of file cmapi.c.
References ASSERT, ASSERT_CELL_DIRTY, Cell, CmKdPrintEx, CML_CM, CmpCleanUpKcbValueCache(), CmpFindNameInList(), CmpFreeValue(), CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpMarkValueDataDirty(), CmpRemoveValueFromList(), CmpReportNotify(), CmpSetUpKcbValueCache, CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), _CHILD_LIST::Count, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, Hive, HvGetCell, HvMarkCellDirty(), HvReleaseCell, KeQuerySystemTime(), _CM_KEY_NODE::LastWriteTime, leave, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PERFINFO_REG_DELETE_VALUE, REG_NOTIFY_CHANGE_LAST_SET, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and _CM_KEY_NODE::ValueList.
Referenced by NtDeleteValueKey().
NTSTATUS CmDumpKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle)
Definition at line 1078 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpLockHiveFlusherExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, FALSE, _CMHIVE::FileHandles, HFILE_TYPE_EXTERNAL, Hive, _CMHIVE::Hive, HvShutdownComplete, HvWriteHive(), NULL, _HBASE_BLOCK::RootCell, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, and STATUS_REGISTRY_IO_FAILED.
Referenced by NtSaveKeyEx().
NTSTATUS CmEnumerateKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 400 of file cmapi.c.
References Cell, CmKdPrintEx, CML_CM, CmpFindSubKeyByNumber(), CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyData(), CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), NULL, PERFINFO_REG_ENUM_KEY, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, and STATUS_NO_MORE_ENTRIES.
Referenced by NtEnumerateKey().
NTSTATUS CmEnumerateValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 573 of file cmapi.c.
References ASSERT, CM_KCB_SYM_LINK_FOUND, CmKdPrintEx, CML_CM, CML_EXCEPTION, CmpCleanUpKcbValueCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpIsKCBLockedExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyValueData(), CmpSetUpKcbValueCache, CmpTryConvertKCBLockSharedToExclusive(), CmpUnlockKCB, CmpUnlockRegistry(), CmpUpgradeKCBLockToExclusive, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, _CHILD_LIST::List, NULL, PERFINFO_REG_ENUM_VALUE, SearchNeedExclusiveLock, SearchSuccess, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_MORE_ENTRIES, and _CM_KEY_NODE::ValueList.
Referenced by NtEnumerateValueKey().
NTSTATUS CmFlushKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN BOOLEAN RegistryLockOwnedExclusive)
Definition at line 802 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE_OR_HIVE_LOADING, ASSERT_KCB_LOCKED, CmKdPrintEx, CML_BUGCHECK, CML_CM, CmLockHiveViews, CmpDoFlushAll(), CmpFixHiveUsageCount(), CmpLockHiveFlusherExclusive, CmpLockKCBShared, CmpLockRegistryExclusive(), CmpMarkAllBinsReadOnly, CmpMasterHive, CmpNoWrite, CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CmUnlockHiveViews, CONTAINING_RECORD, DCmCheckRegistry, DPFLTR_CONFIG_ID, FALSE, Hive, _CMHIVE::Hive, HvHiveWillShrink(), HvSyncHive(), STATUS_KEY_DELETED, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, and _CMHIVE::UseCount.
Referenced by CmUnloadKey(), and NtFlushKey().
NTSTATUS CmLoadKey (IN POBJECT_ATTRIBUTES TargetKey, IN POBJECT_ATTRIBUTES SourceFile, IN ULONG Flags, IN PCM_KEY_BODY KeyBody)
Definition at line 2645 of file cmapi.c.
References ASSERT, CM_CHECK_REGISTRY_CHECK_CLEAN, CM_CMHIVE_FLAG_UNTRUSTED, CmpAddToHiveFileList(), CmpCmdHiveClose(), CmpCmdHiveOpen(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpIsHiveAlreadyLoaded(), CmpJoinClassOfTrust, CmpKeyObjectType, CmpLinkHiveToMaster(), CmpLockHiveFlusherExclusive, CmpLockHiveListExclusive, CmpLockRegistry(), CmpLockRegistryExclusive(), CmpProfileLoaded, CmpRemoveEntryList, CmpSetGlobalQuotaAllowed(), CmpUnJoinClassOfTrust, CmpUnlockHiveFlusher, CmpUnlockHiveList, CmpUnlockRegistry(), CmpWasSetupBoot, CONTAINING_RECORD, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _CM_PARSE_CONTEXT::CreateOperation, _CMHIVE::CreatorOwner, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, FALSE, _CMHIVE::Flags, Hive, _CMHIVE::Hive, HIVE_IS_UNLOADING, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvFreeHive(), HvSyncHive(), _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, KeGetCurrentThread(), KernelMode, KEY_READ, _SECURITY_QUALITY_OF_SERVICE::Length, LOCK_HIVE_LOAD, LogHiveLoad, NT_SUCCESS, NULL, ObOpenObjectByName(), REG_NO_LAZY_FLUSH, RtlZeroMemory, SeCreateClientSecurity(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, SeDeleteClientSecurity, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, UNLOCK_HIVE_LOAD, and ZwClose().
Referenced by NtLoadKeyEx().
NTSTATUS CmLockKcbForWrite (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 4656 of file cmapi.c.
References ASSERT, ASSERT_KCB, CM_KCB_NO_DELAY_CLOSE, CM_KCB_READ_ONLY_KEY, CM_PAGED_CODE, CmpLockKCBExclusive, CmpUnlockKCB, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_CONTROL_BLOCK::ExtFlags, InterlockedIncrement, _CM_KEY_CONTROL_BLOCK::RefCount, STATUS_KEY_DELETED, and STATUS_SUCCESS.
Referenced by NtLockRegistryKey().
NTSTATUS CmMoveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 4004 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CmKdPrintEx, CML_CM, CmpCleanUpSubKeyInfo(), CmpDuplicateKey(), CmpFreeKeyByCell(), CmpMarkKeyDirty(), CmpRebuildKcbCache(), CmpUpdateParentForEachSon(), _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, DBG, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, Hive, HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, KEY_SYM_LINK, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NT_SUCCESS, NULL, PAGED_CODE, _CM_KEY_NODE::Parent, _HBASE_BLOCK::RootCell, _CM_KEY_INDEX::Signature, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and Volatile.
Referenced by NtCompactKeys().
NTSTATUS CmpAcquireFileObjectForFile (IN PCMHIVE CmHive, IN HANDLE FileHandle, OUT PFILE_OBJECT * FileObject)
Definition at line 957 of file cmmapvw.c.
References ASSERT, _UNICODE_STRING::Buffer, CcSetPrivateWriteFile(), CM_PAGED_CODE, CmKdPrintEx, CmpDropFileObjectForHive(), CmpStashBuffer, CmpStashBufferSize, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, DPFLTR_TRACE_LEVEL, ExAllocatePoolWithTag, FILE_READ_DATA, FILE_WRITE_DATA, IoFileObjectType, KernelMode, _UNICODE_STRING::Length, LOCK_STASH_BUFFER, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObQueryNameString(), ObReferenceObjectByHandle, PagedPool, PROTECTED_POOL, RtlCopyMemory, Status, STATUS_RETRY, and UNLOCK_STASH_BUFFER.
Referenced by CmpSetupPrivateWrite(), and HvMapHive().
NTSTATUS CmpAddAcpiAliasEntry (IN HANDLE IDConfigDB, IN PPROFILE_ACPI_DOCKING_STATE NewDockState, IN ULONG ProfileNumber, IN PWCHAR nameBuffer, IN PVOID valueBuffer, IN ULONG valueBufferLength, IN BOOLEAN PreventDuplication)
NTSTATUS CmpAddSecurityCellToCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, IN BOOLEAN BuildUp, IN PCM_KEY_SECURITY_CACHE SecurityCached)
Definition at line 122 of file cmsecache.c.
References ASSERT, CmpFindSecurityCellCacheIndex(), CmpSecConvKey(), CmpSecHashTableSize, CmRetryExAllocatePoolWithTag, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, ExFreePoolWithTag, FIELD_OFFSET, HvGetCell, HvReleaseCell, Index, InsertTailList(), NULL, PAGE_SIZE, PAGED_CODE, PagedPool, PROTECTED_POOL, RtlCopyMemory, RtlMoveMemory, SECURITY_CACHE_GROW_INCREMENTS, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by CmpInsertSecurityCellList(), CmpRebuildSecurityCache(), CmpSetSecurityDescriptorInfo(), and CmpValidateHiveSecurityDescriptors().
BOOLEAN CmpAddSubKey (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
Definition at line 1270 of file cmindex.c.
References _HHIVE::Allocate, ASSERT, _UNICODE_STRING::Buffer, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_MAX_FAST_INDEX, CM_MAX_INDEX, CM_PAGED_CODE, CmKdPrintEx, CML_INDEX, CmpAddToLeaf(), CmpCompressedNameSize(), CmpCopyCompressedName(), CmpSelectLeaf(), _CM_KEY_INDEX::Count, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _HHIVE::Free, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, Index, KEY_COMP_NAME, _UNICODE_STRING::Length, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, _CM_KEY_INDEX::Signature, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, UseFastIndex, and UseHashIndex.
Referenced by CmpCopySyncTree2(), CmpCreateLinkNode(), CmpDoCreate(), and CmRenameKey().
VOID CmpAddToDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN RegLockHeldEx)
Definition at line 421 of file cmdelay.c.
References ASSERT, ASSERT_KEYBODY_LIST_EMPTY, CM_PAGED_CODE, CmpArmDelayedCloseTimer(), CmpCleanUpKcbCacheWithLock(), CmpDelayCloseAllocNewEntry, CmpDelayCloseWorkItemActive, CmpDelayedCloseElements, CmpDelayedCloseSize, CmpIsKCBLockedExclusive, _CM_DELAYED_CLOSE_ENTRY::DelayedLRUList, FALSE, InsertHeadList(), InterlockedCompareExchange(), InterlockedIncrement, _CM_DELAYED_CLOSE_ENTRY::KeyControlBlock, LOCK_DELAY_CLOSE, NULL, TRUE, and UNLOCK_DELAY_CLOSE.
Referenced by CmpDereferenceKeyControlBlockWithLock().
NTSTATUS CmpAddToHiveFileList (PCMHIVE CmHive)
Definition at line 38 of file cmhvlist.c.
References _UNICODE_STRING::Buffer, CmKdPrintEx, CML_BUGCHECK, CmpGetHiveName(), DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), _CMHIVE::FileHandles, HFILE_TYPE_PRIMARY, _CMHIVE::Hive, HIVE_LIST, HIVE_VOLATILE, _HHIVE::HiveFlags, InitializeObjectAttributes, KEY_READ, KEY_WRITE, NAME_BUFFER_SIZE, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, ObjectNameInformation, PagedPool, REG_OPTION_VOLATILE, REG_SZ, RtlInitUnicodeString(), Status, STATUS_NO_MEMORY, UNICODE_NULL, UnicodeNull, ZwCreateKey(), ZwQueryObject(), and ZwSetValueKey().
Referenced by CmInitSystem1(), CmLoadKey(), CmpInitializeHiveList(), and CmpLoadHiveVolatile().
NTSTATUS CmpAddValueToList (IN PHHIVE Hive, IN HCELL_INDEX ValueCell, IN ULONG Index, IN ULONG Type, IN OUT PCHILD_LIST ChildList)
Definition at line 487 of file cmvalue.c.
References ASSERT, ASSERT_CELL_DIRTY, ASSERT_HIVE_FLUSHER_LOCKED, CM_MAX_REASONABLE_VALUES, CM_PAGED_CODE, Count, FALSE, HBLOCK_SIZE, HCELL_NIL, HvAllocateCell(), HvGetCell, HvReallocateCell(), HvReleaseCell, Index, _CELL_DATA::_u::KeyList, NULL, ROUND_UP, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _CELL_DATA::u.
Referenced by CmpCopyKeyPartial(), CmpMergeKeyValues(), CmpSetValueKeyNew(), and CmpSyncKeyValues().
BOOLEAN CmpAdjustSecurityCacheSize (IN PCMHIVE CmHive)
Definition at line 489 of file cmsecache.c.
References CmRetryExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, NULL, PAGED_CODE, PagedPool, PROTECTED_POOL, RtlCopyMemory, and TRUE.
Referenced by CmpValidateHiveSecurityDescriptors().
PVOID CmpAllocate (ULONG Size, BOOLEAN UseForIo, ULONG Tag)
Definition at line 74 of file cmwrapr.c.
References CmKdPrintEx, CML_POOL, CmpClaimGlobalQuota(), CmpReleaseGlobalQuota(), DPFLTR_CONFIG_ID, ExAllocatePoolWithTag, FALSE, NULL, PagedPool, PagedPoolCacheAligned, and RtlGetCallersAddress().
Referenced by CmpInitializeHive().
PVOID CmpAllocateDelayItem ()
Definition at line 396 of file cmalloc.c.
References ASSERT, CM_DELAY_ALLOC_ENTRY_SIZE, CM_DELAYS_PER_PAGE, CM_PAGED_CODE, CmpClearListEntry, CmpIsListEmpty, CONTAINING_RECORD, DELAY_ALLOC_TO_ALLOC_PAGE, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, InsertTailList(), _CM_DELAY_ALLOC::Kcb, _CM_DELAY_ALLOC::ListEntry, LOCK_DELAY_ALLOC_BUCKET, NULL, PAGE_SIZE, PagedPool, PROTECTED_POOL, RemoveHeadList(), and UNLOCK_DELAY_ALLOC_BUCKET.
PCM_KEY_CONTROL_BLOCK CmpAllocateKeyControlBlock ()
Definition at line 114 of file cmalloc.c.
References ASSERT, CM_KCB_ENTRY_SIZE, CM_KCBS_PER_PAGE, CmpAllocInited, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::DelayCloseEntry, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, _CM_KEY_CONTROL_BLOCK::FreeListEntry, InsertTailList(), IsListEmpty, KCB_TO_ALLOC_PAGE, LOCK_ALLOC_BUCKET, NULL, PAGE_SIZE, PAGED_CODE, PagedPool, _CM_KEY_CONTROL_BLOCK::PrivateAlloc, PROTECTED_POOL, RemoveHeadList(), and UNLOCK_ALLOC_BUCKET.
Referenced by CmpCreateKeyControlBlock().
PCM_POST_BLOCK CmpAllocatePostBlock (IN POST_BLOCK_TYPE BlockType, IN ULONG PostFlags, IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK MasterBlock)
Definition at line 4581 of file ntapi.c.
References ALLOCATE_WITH_QUOTA, _CM_ASYNC_USER_POST_BLOCK::Apc, ASSERT, _CM_POST_BLOCK_UNION::AsyncKernel, _CM_POST_BLOCK_UNION::AsyncUser, ExFreePool(), FALSE, InitializeListHead(), IsMasterPostBlock, KeInitializeEvent(), _CM_POST_KEY_BODY::KeyBody, _CM_POST_KEY_BODY::KeyBodyList, NonPagedPool, _CM_POST_BLOCK::NotifyType, NULL, PagedPool, POOL_COLD_ALLOCATION, PostAsyncKernel, PostAsyncUser, _CM_POST_BLOCK::PostKeyBody, PostSynchronous, RtlZeroMemory, _CM_POST_BLOCK_UNION::Sync, SynchronizationEvent, _CM_SYNC_POST_BLOCK::SystemEvent, and _CM_POST_BLOCK::u.
NTSTATUS CmpAssignSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PCM_KEY_NODE Node, IN PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 1007 of file cmse.c.
References ASSERT, ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_NODE, _UNICODE_STRING::Buffer, CM_KEY_SECURITY_SIGNATURE, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpFindMatchingDescriptorCell(), CmpInsertSecurityCellList(), _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, _CM_KEY_SECURITY::ReferenceCount, RtlCopyMemory, RtlLengthSecurityDescriptor(), SECURITY_CELL_LENGTH, _CM_KEY_SECURITY::Signature, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, and STATUS_SUCCESS.
Referenced by CmpAssignSecurityDescriptorWrapper(), CmpCopyKeyPartial(), and CmpSyncKeyValues().
NTSTATUS CmpAssignSecurityDescriptorWrapper (IN PVOID Object, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 148 of file cmse.c.
References ASSERT, ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_PAGED_CODE, CmpAssignSecurityDescriptor(), CmpAssignSecurityToKcb(), CmpSecurityExceptionFilter(), except, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObAssignObjectSecurityDescriptor(), PagedPool, _CM_KEY_NODE::Security, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by CmpDoCreateChild(), and CmpSecurityMethod().
VOID CmpAssignSecurityToKcb (IN PCM_KEY_CONTROL_BLOCK Kcb, IN HCELL_INDEX SecurityCell, IN BOOLEAN SecurityLocked)
Definition at line 1016 of file cmsecache.c.
References BAD_SECURITY_CACHE, _CM_KEY_SECURITY_CACHE_ENTRY::CachedSecurity, CM_BUGCHECK, CmLockHiveSecurityShared, CmpFindSecurityCellCacheIndex(), CmUnlockHiveSecurity, FALSE, HCELL_NIL, Index, NULL, PAGED_CODE, REGISTRY_ERROR, and _CMHIVE::SecurityCache.
Referenced by CmpAssignSecurityDescriptorWrapper(), CmpCreateKeyControlBlock(), CmpSetSecurityDescriptorInfo(), and CmRestoreKey().
BOOLEAN CmpBuildSecurityCellMappingArray (IN PCMHIVE CmHive)
Definition at line 1082 of file cmsecache.c.
References ASSERT, ExAllocatePool, FALSE, HCELL_NIL, HvGetCellType, NULL, PAGED_CODE, PagedPool, TRUE, and Volatile.
Referenced by CmCompressKey().
NTSTATUS CmpCallCallBacks (IN REG_NOTIFY_CLASS Type, IN PVOID Argument, IN BOOLEAN Wind, IN REG_NOTIFY_CLASS PostType, IN PVOID Object)
Definition at line 196 of file cmhook.c.
References ASSERT, _CM_CALLBACK_CONTEXT_BLOCK::CallerContext, CM_MAX_CALLBACKS, CmpCheckRecursionAndRecordThreadInfo(), CmpLockContext, CmpUnlockContext, ExDereferenceCallBackBlock(), ExGetCallBackBlockContext(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), FALSE, InitializeListHead(), IsListEmpty, NT_SUCCESS, NULL, _REG_POST_OPERATION_INFORMATION::Object, PAGED_CODE, PsGetCurrentThread(), RemoveEntryList(), Status, _REG_POST_OPERATION_INFORMATION::Status, STATUS_SUCCESS, _CM_ACTIVE_NOTIFY_THREAD::Thread, _CM_ACTIVE_NOTIFY_THREAD::ThreadList, and TRUE.
Referenced by CmpDeleteKeyObject(), CmpParseKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtRenameKey(), NtSetInformationKey(), and NtSetValueKey().
BOOLEAN CmpCanGrowSystemHive (IN PHHIVE Hive, IN ULONG NewLength)
Definition at line 382 of file cmgquota.c.
References CM_SYSTEM_HIVE_LIMIT_SIZE, CM_SYSTEM_HIVE_WARNING_SIZE, CmpSystemQuotaWarningPopupDisplayed, CmpSystemQuotaWarningWorker(), CONTAINING_RECORD, DelayedWorkQueue, ExAllocatePool, ExInitializeWorkItem, ExQueueWorkItem(), ExReadyForErrors, FALSE, HBLOCK_SIZE, NonPagedPool, NULL, PAGED_CODE, SYSTEM_HIVE_INDEX, and TRUE.
Referenced by HvpAddBin().
BOOLEAN CmpCheckCreateAccess (IN PUNICODE_STRING RelativeName, IN PSECURITY_DESCRIPTOR Descriptor, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK AdditionalAccess, OUT PNTSTATUS AccessStatus)
Definition at line 1255 of file cmse.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpKeyObjectType, DPFLTR_CONFIG_ID, _OBJECT_TYPE_INITIALIZER::GenericMapping, KEY_CREATE_SUB_KEY, NULL, SeAccessCheck(), SeLockSubjectContext(), SeUnlockSubjectContext(), TRUE, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by CmpDoCreate().
NTSTATUS CmpCheckKeyAccess (IN PHHIVE Hive, IN HCELL_INDEX NodeCell, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK DesiredAccess)
Definition at line 2070 of file cmse.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_PAGED_CODE, CmpKeyObjectType, DACL_SECURITY_INFORMATION, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, ExAllocatePool, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, GROUP_SECURITY_INFORMATION, HvGetCell, HvReleaseCell, NT_SUCCESS, NULL, OWNER_SECURITY_INFORMATION, PagedPool, SACL_SECURITY_INFORMATION, SeAccessCheck(), SeCaptureSubjectContext(), _CM_KEY_NODE::Security, SeQuerySecurityDescriptorInfo(), SeReleaseSubjectContext(), Status, STATUS_ACCESS_DENIED, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and _OBJECT_TYPE::TypeInfo.
Referenced by CmpDoAccessCheckOnSubtree(), and CmRenameKey().
BOOLEAN CmpCheckNotifyAccess (IN PCM_NOTIFY_BLOCK NotifyBlock, IN PHHIVE Hive, IN PCM_KEY_NODE Node)
Definition at line 1338 of file cmse.c.
References ASSERT_CM_LOCK_OWNED, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmLockHiveSecurityShared, CmpFindSecurityCellCacheIndex(), CmpKeyObjectType, CmUnlockHiveSecurity, DPFLTR_CONFIG_ID, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, Index, KEY_NOTIFY, NULL, SeAccessCheck(), SeLockSubjectContext(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_TYPE::TypeInfo, and UserMode.
Referenced by CmpNotifyTriggerCheck().
BOOLEAN CmpClaimGlobalQuota (IN ULONG Size)
Definition at line 240 of file cmgquota.c.
References CmpGlobalQuotaUsed, InterlockedExchangeAdd(), and TRUE.
Referenced by CmpAllocate().
VOID CmpCleanUpKCBCacheTable (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 434 of file cmsubs.c.
References ASSERT, CM_PAGED_CODE, CmpCleanUpKcbCacheWithLock(), CmpHashTableSize, CmpIsKCBLockedExclusive, CmpKCBLockForceAcquireAllowed(), CmpLockHashEntryByIndexExclusive, CmpRemoveFromDelayedClose(), CmpRunDownDelayDerefKCBEngine(), CmpTryToLockHashEntryByIndexExclusive(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_HASH_TABLE_ENTRY::Entry, FALSE, GET_HASH_INDEX, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_CONTROL_BLOCK::NextHash, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_KEY_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmCompressKey(), and CmpSearchForOpenSubKeys().
VOID CmpCleanUpKcbCacheWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 1325 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_SUBKEY_HINT, CmpCleanUpKcbValueCache(), CmpDelayDerefKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpDereferenceNameControlBlockWithLock(), CmpFreeKeyControlBlock(), CmpRemoveKeyControlBlock(), _CM_KEY_CONTROL_BLOCK::Delete, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, _CM_KEY_CONTROL_BLOCK::IndexHint, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_KEY_CONTROL_BLOCK::ParentKcb, PROTECTED_POOL, _CM_KEY_CONTROL_BLOCK::RefCount, and SET_KCB_SIGNATURE.
Referenced by CmpAddToDelayedClose(), CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpDelayCloseWorker(), CmpDereferenceKeyControlBlockWithLock(), and CmpSearchKeyControlBlockTree().
VOID CmpCleanUpKcbValueCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 1265 of file cmsubs.c.
References ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_NO_DELAY_CLOSE, CM_KCB_SYM_LINK_FOUND, CMP_GET_CACHED_ADDRESS, CMP_GET_CACHED_CELLDATA, CMP_IS_CELL_CACHED, CmpDelayDerefKeyControlBlock(), CmpMakeSpecialPoolReadWrite, _CACHED_CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::Delete, ExFreePool(), _CM_KEY_CONTROL_BLOCK::ExtFlags, HCELL_NIL, _CACHED_CHILD_LIST::RealKcb, _CM_KEY_CONTROL_BLOCK::RefCount, _CM_KEY_CONTROL_BLOCK::ValueCache, and _CACHED_CHILD_LIST::ValueList.
Referenced by CmDeleteValueKey(), CmEnumerateValueKey(), CmpCleanUpKcbCacheWithLock(), CmpCompareNewValueDataAgainstKCBCache(), CmpDoOpen(), CmpGetSymbolicLink(), CmpRebuildKcbCache(), CmpSwitchStorageAndRebuildMappings(), CmQueryValueKey(), CmRestoreKey(), and CmSetValueKey().
VOID CmpCleanUpSubKeyInfo (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 1208 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_INVALID_CACHED_INFO, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, _CM_KEY_CONTROL_BLOCK::Delete, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, HCELL_NIL, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::IndexHint, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NULL, PROTECTED_POOL, Stable, _CM_KEY_CONTROL_BLOCK::SubKeyCount, _CM_KEY_NODE::SubKeyCounts, and Volatile.
Referenced by CmDeleteKey(), CmMoveKey(), CmpCreateLinkNode(), CmpDoCreate(), CmpRebuildKcbCache(), CmpSearchForOpenSubKeys(), CmRenameKey(), CmRestoreKey(), and CmUnloadKey().
NTSTATUS CmpCloneHwProfile (IN HANDLE IDConfigDB, IN HANDLE Parent, IN HANDLE OldProfile, IN ULONG OldProfileNumber, IN USHORT DockingState, OUT PHANDLE NewProfile, OUT PULONG NewProfileNumber)
Referenced by CmpCreateControlSet().
VOID CmpCloseKeyObject (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 31 of file cmclose.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_POOL, CmLockHive, CmpDelayedDerefKeys(), CmpLockRegistry(), CmpPostNotify(), CmpUnlockRegistry(), CmUnlockHive, DBG, DPFLTR_CONFIG_ID, FALSE, InitializeListHead(), IsListEmpty, KEY_BODY_TYPE, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_BODY::NotifyBlock, NULL, _CM_NOTIFY_BLOCK::PostList, STATUS_NOTIFY_CLEANUP, _CM_KEY_BODY::Type, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateObjectTypes().
VOID CmpCmdHiveClose (PCMHIVE CmHive)
Definition at line 143 of file cmworker.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE_OR_HIVE_LOADING, CM_PAGED_CODE, CmCloseHandle, CmpTrackHiveClose, _HHIVE::DirtyFlag, FALSE, FileBasicInformation, _CMHIVE::FileHandles, HFILE_TYPE_MAX, HFILE_TYPE_PRIMARY, _CMHIVE::Hive, IoSetThreadHardErrorMode(), KeQuerySystemTime(), _FILE_BASIC_INFORMATION::LastAccessTime, _FILE_BASIC_INFORMATION::LastWriteTime, NT_SUCCESS, NULL, TRUE, ZwQueryInformationFile(), and ZwSetInformationFile().
Referenced by CmLoadKey(), CmShutdownSystem(), and CmUnloadKey().
NTSTATUS CmpCmdHiveOpen (POBJECT_ATTRIBUTES FileAttributes, PSECURITY_CLIENT_CONTEXT ImpersonationContext, PBOOLEAN Allocate, PCMHIVE * NewHive, ULONG CheckFlags)
Definition at line 369 of file cmworker.c.
References CM_PAGED_CODE, CmpInitHiveFromFile(), NT_SUCCESS, NULL, _OBJECT_ATTRIBUTES::ObjectName, PsRevertToSelf(), SeImpersonateClientEx(), Status, STATUS_ACCESS_DENIED, STATUS_ACCOUNT_DISABLED, STATUS_ACCOUNT_EXPIRED, STATUS_ACCOUNT_RESTRICTION, STATUS_NO_SUCH_USER, and STATUS_WRONG_PASSWORD.
Referenced by CmLoadKey().
VOID CmpCmdInit (BOOLEAN SetupBoot)
Definition at line 224 of file cmworker.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_PAGED_CODE, CmpEnableLazyFlushDpcRoutine(), CmpInitializeHiveList(), CmpLazyFlushDpcRoutine(), CmpLazyFlushWorker(), CmpMiniNTBoot, CmpNoWrite, CmpShareSystemHives, CmpWasSetupBoot, ENABLE_LAZY_FLUSH_INTERVAL_IN_SECONDS, ExInitializeWorkItem, FALSE, Int32x32To64, KeInitializeDpc(), KeInitializeTimer(), KeSetTimer(), NULL, _LARGE_INTEGER::QuadPart, and SECOND_MULT.
Referenced by NtInitializeRegistry().
NTSTATUS CmpCmdRenameHive (PCMHIVE CmHive, POBJECT_NAME_INFORMATION OldName, PUNICODE_STRING NewName, ULONG NameInfoLength)
Definition at line 291 of file cmworker.c.
References ASSERT_PASSIVE_LEVEL, _UNICODE_STRING::Buffer, CM_PAGED_CODE, ExAllocatePool, ExFreePool(), FALSE, _CMHIVE::FileHandles, _FILE_RENAME_INFORMATION::FileName, _FILE_RENAME_INFORMATION::FileNameLength, FileRenameInformation, Handle, HFILE_TYPE_PRIMARY, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObjectNameInformation, PagedPool, _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, ZwQueryObject(), and ZwSetInformationFile().
LONG CmpCompareCompressedName (IN PUNICODE_STRING SearchName, IN PWCHAR CompressedName, IN ULONG NameLength, IN ULONG CompareFlags)
Definition at line 196 of file cmname.c.
References CMP_DEST_UP, CMP_SOURCE_UP, and CmUpcaseUnicodeChar.
Referenced by CmpCacheLookup(), CmpCheckLexicographicalOrder(), CmpDoCompareKeyName(), CmpFindNameInList(), CmpFindValueByNameFromCache(), and CmpGetNameControlBlock().
LONG CmpCompareTwoCompressedNames (IN PWCHAR CompressedName1, IN ULONG NameLength1, IN PWCHAR CompressedName2, IN ULONG NameLength2)
Definition at line 330 of file cmname.c.
References CmUpcaseUnicodeChar.
Referenced by CmpCheckLexicographicalOrder().
LONG CmpCompareUnicodeString (IN PUNICODE_STRING SourceName, IN PUNICODE_STRING DestName, IN ULONG CompareFlags)
Definition at line 265 of file cmname.c.
References CMP_DEST_UP, CMP_SOURCE_UP, and CmUpcaseUnicodeChar.
Referenced by CmpCacheLookup().
USHORT CmpCompressedNameSize (IN PWCHAR Name, IN ULONG Length)
Definition at line 121 of file cmname.c.
References UNREFERENCED_PARAMETER.
Referenced by CmpAddDriverToList(), CmpAddSubKey(), CmpFindProfileOption(), CmpInitializeKeyNameString(), CmpInitializeValueNameString(), CmpMarkIndexDirty(), CmpQueryKeyDataFromCache(), and CmpRemoveSubKey().
VOID CmpComputeGlobalQuotaAllowed (VOID)
Definition at line 298 of file cmgquota.c.
References CM_DEFAULT_RATIO, CM_LIMIT_RATIO, CM_MINIMUM_GLOBAL_QUOTA, CM_REGISTRY_WARNING_LEVEL, CM_WRAP_LIMIT, CmpGlobalQuota, CmpGlobalQuotaWarning, CmRegistrySizeLimit, CmRegistrySizeLimitLength, CmRegistrySizeLimitType, MmSizeOfPagedPoolInBytes, and REG_DWORD.
Referenced by CmInitSystem1().
ULONG CmpComputeHashKey (IN ULONG HashStart, IN PUNICODE_STRING Name)
Definition at line 2989 of file cmindex.c.
References ASSERT, CmUpcaseUnicodeChar, and OBJ_NAME_PATH_SEPARATOR.
Referenced by CmpAddInfoAfterParseFailure(), CmpAddToLeaf(), CmpFindSubKeyByHash(), CmpFindValueByNameFromCache(), CmpGetValueKeyFromCache(), and CmpParseKey().
ULONG CmpComputeHashKeyForCompressedName (IN ULONG HashStart, IN PWCHAR Source, IN ULONG SourceLength)
Definition at line 3016 of file cmindex.c.
References CmUpcaseUnicodeChar.
Referenced by CmpAddInfoAfterParseFailure(), and CmpGetValueKeyFromCache().
ULONG CmpComputeKcbConvKey (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 734 of file cmsubs.c.
References ASSERT, CM_PAGED_CODE, CmUpcaseUnicodeChar, _CM_NAME_CONTROL_BLOCK::Compressed, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_NAME_CONTROL_BLOCK::NameLength, NULL, OBJ_NAME_PATH_SEPARATOR, and _CM_KEY_CONTROL_BLOCK::ParentKcb.
Referenced by CmpRehashKcbSubtree(), and CmRenameKey().
PUNICODE_STRING CmpConstructName (PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 1407 of file cmsubs.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_KCB_KEY_NON_EXIST, CMP_KCB_REAL_NAME_UPCASE, _CM_NAME_CONTROL_BLOCK::Compressed, _CM_KEY_CONTROL_BLOCK::Delete, ExAllocatePoolWithTag, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, HvGetCell, HvReleaseCell, InterlockedCompareExchangePointer, KEY_COMP_NAME, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MAXUSHORT, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_NODE::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_NAME_CONTROL_BLOCK::NameLength, _CM_KEY_NODE::NameLength, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, _CM_KEY_CONTROL_BLOCK::ParentKcb, PROTECTED_POOL, RtlCopyMemory, and TRUE.
Referenced by CmpDumpKeyBodyList(), CmpGetSymbolicLink(), CmpLoadHiveVolatile(), CmpQueryKeyName(), CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), and CmQueryKey().
HCELL_INDEX CmpCopyCell (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
Definition at line 1330 of file cmtrecpy.c.
References ASSERT, CmKdPrintEx, CML_SAVRES, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellSize(), HvReleaseCell, NULL, and RtlCopyMemory.
Referenced by CmpCopyKeyPartial(), CmpCopyValue(), and CmpSyncKeyValues().
VOID CmpCopyCompressedName (IN PWCHAR Destination, IN ULONG DestinationLength, IN PWCHAR Source, IN ULONG SourceLength)
Definition at line 153 of file cmname.c.
Referenced by CmpAddDriverToList(), CmpAddSubKey(), CmpFindProfileOption(), CmpGetHiveName(), CmpInitializeKeyNameString(), CmpInitializeValueNameString(), CmpLoadHiveVolatile(), CmpMarkIndexDirty(), CmpQueryKeyData(), CmpQueryKeyValueData(), and CmpRemoveSubKey().
HCELL_INDEX CmpCopyKeyPartial (PHHIVE SourceHive, HCELL_INDEX SourceKeyCell, PHHIVE TargetHive, HCELL_INDEX Parent, BOOLEAN CopyValues)
Definition at line 759 of file cmtrecpy.c.
References ASSERT, ASSERT_CELL_DIRTY, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CmKdPrintEx, CML_SAVRES, CmLockHiveSecurityExclusive, CmLockHiveSecurityShared, CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCopyValue(), CmpFindNameInList(), CmpFindSecurityCellCacheIndex(), CmpInitializeValueNameString(), CmUnlockHiveSecurity, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvGetCellType, HvReleaseCell, Index, KEY_COMP_NAME, KEY_HIVE_ENTRY, KEY_NO_DELETE, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyNode, _CHILD_LIST::List, NT_SUCCESS, NULL, PagedPool, _CM_KEY_NODE::Parent, REG_MAX_KEY_VALUE_NAME_LENGTH, _CM_KEY_NODE::Security, Stable, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpCopySyncTree2(), CmpDuplicateKey(), CmpLoadHiveVolatile(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
USHORT CmpCopyName (IN PHHIVE Hive, IN PWCHAR Destination, IN PUNICODE_STRING Source)
Definition at line 74 of file cmname.c.
References RtlCopyMemory.
Referenced by CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreateChild(), CmpSetValueKeyNew(), and CmRenameKey().
BOOLEAN CmpCopySyncTree (PHHIVE SourceHive, HCELL_INDEX SourceCell, PHHIVE TargetHive, HCELL_INDEX TargetCell, BOOLEAN CopyVolatile, CMP_COPY_TYPE CopyType)
Definition at line 119 of file cmtrecpy.c.
References CmKdPrintEx, CML_SAVRES, CMP_INITIAL_STACK_SIZE, CmpCopySyncTree2(), DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, NULL, PagedPool, _HHIVE::ReleaseCellRoutine, CMP_COPY_STACK_ENTRY::SourceCell, and CMP_COPY_STACK_ENTRY::TargetCell.
HCELL_INDEX CmpCopyValue (PHHIVE SourceHive, HCELL_INDEX SourceValueCell, PHHIVE TargetHive, HSTORAGE_TYPE Type)
Definition at line 1113 of file cmtrecpy.c.
References ASSERT, CM_KEY_VALUE_SMALL, CM_KEY_VALUE_SPECIAL_SIZE, CmKdPrintEx, CML_SAVRES, CmpCopyCell(), CmpFreeValueData(), CmpGetValueData(), CmpIsHKeyValueBig, CmpIsHKeyValueSmall, CmpSetValueDataNew(), _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyValue, NT_SUCCESS, NULL, TRUE, and _CELL_DATA::u.
Referenced by CmpCopyKeyPartial(), CmpMergeKeyValues(), and CmpSyncKeyValues().
NTSTATUS CmpCreateEvent (IN EVENT_TYPE eventType, OUT PHANDLE eventHandle, OUT PKEVENT * event)
Definition at line 374 of file cmwrapr.c.
References EVENT_ALL_ACCESS, FALSE, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, ZwClose(), and ZwCreateEvent().
Referenced by CmpFileRead(), CmpFileWrite(), and CmpOpenHiveFiles().
NTSTATUS CmpCreateHwProfileFriendlyName (IN HANDLE IDConfigDB, IN ULONG DockingState, IN ULONG NewProfileNumber, OUT PUNICODE_STRING FriendlyName)
PCM_KEY_CONTROL_BLOCK CmpCreateKeyControlBlock (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node, PCM_KEY_CONTROL_BLOCK ParentKcb, ULONG ControlFlags, PUNICODE_STRING KeyName)
Definition at line 1688 of file cmsubs.c.
References ASSERT, ASSERT_KCB, _UNICODE_STRING::Buffer, Cell, CM_KCB_INVALID_CACHED_INFO, CM_KCB_KEY_NON_EXIST, CM_KCB_NO_DELAY_CLOSE, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, CMP_CREATE_KCB_FAKE, CMP_CREATE_KCB_KCB_LOCKED, CMP_KCB_REAL_NAME_UPCASE, CMP_MAX_REGISTRY_DEPTH, CmpAllocateKeyControlBlock(), CmpAssignSecurityToKcb(), CmpDelayedCloseSize, CmpDereferenceKeyControlBlockWithLock(), CmpFreeKeyControlBlock(), CmpGetNameControlBlock(), CmpInsertKeyHash(), CmpLockKCBExclusive, CmpLockTwoHashEntriesExclusive(), CmpReferenceKeyControlBlock(), CmpRemoveKeyControlBlock(), CmpTraceKcbCreate, CmpUnlockHashEntry, CmpUnlockTwoHashEntries(), CmUpcaseUnicodeChar, _CM_KEY_CONTROL_BLOCK::ConvKey, _CACHED_CHILD_LIST::Count, _CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::DelayedCloseIndex, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, Hive, HIVE_IS_UNLOADING, _HHIVE::HiveFlags, InitializeKCBKeyBodyList(), IsHiveFrozen, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueDataLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueNameLen, KeGetCurrentThread(), KEY_SYM_LINK, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHash, _CM_KEY_CONTROL_BLOCK::KeyHive, KeyName, _CM_KEY_NODE::LastWriteTime, _UNICODE_STRING::Length, _CHILD_LIST::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_CONTROL_BLOCK::NameBlock, NULL, OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, PERFINFO_REG_KCB_CREATE, _CM_KEY_CONTROL_BLOCK::RefCount, _CM_KEY_NODE::Security, SET_KCB_SIGNATURE, Stable, _CM_KEY_CONTROL_BLOCK::SubKeyCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_CONTROL_BLOCK::TotalLevels, TRUE, _CM_KEY_CONTROL_BLOCK::ValueCache, _CACHED_CHILD_LIST::ValueList, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpAddInfoAfterParseFailure(), CmpCreateRegistryRoot(), CmpDoCreateChild(), CmpDoOpen(), and CmpParseKey().
VOID CmpDelayDerefKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 780 of file cmdelay.c.
References CM_PAGED_CODE, CmpDelayDerefKCBAllocNewEntry, CmpDelayDerefKCBIntervalInSeconds, CmpDelayDerefKCBWorkItemActive, InsertTailList(), Int32x32To64, InterlockedCompareExchange(), _CM_DELAY_DEREF_KCB_ITEM::Kcb, KeSetTimer(), _CM_DELAY_DEREF_KCB_ITEM::ListEntry, LOCK_KCB_DELAY_DEREF_LIST, LogKCBReference, NULL, _LARGE_INTEGER::QuadPart, _CM_KEY_CONTROL_BLOCK::RefCount, SECOND_MULT, TRUE, and UNLOCK_KCB_DELAY_DEREF_LIST.
Referenced by CmpCleanUpKcbCacheWithLock(), CmpCleanUpKcbValueCache(), and CmpDeleteKeyObject().
NTSTATUS CmpDeleteChildByName (PHHIVE Hive, HCELL_INDEX Cell, UNICODE_STRING Name, PHCELL_INDEX ChildCell)
VOID CmpDeleteKeyObject (IN PVOID Object)
Definition at line 40 of file cmdelete.c.
References ASSERT, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_FLOW, CmpCallCallBacks(), CmpDelayDerefKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpDoQueueLateUnloadWorker(), CmpFlushNotify(), CmpLockRegistry(), CmPostCallbackNotification, CmpUnlockRegistry(), CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::Delete, DelistKeyBodyFromKCB(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, FALSE, _CM_KEY_CONTROL_BLOCK::Flags, Hive, IsHiveFrozen, KEY_BODY_TYPE, KEY_PREDEF_HANDLE, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NULL, _REG_KEY_HANDLE_CLOSE_INFORMATION::Object, REG_PREDEF_HANDLE_MASK, RegNtPostKeyHandleClose, RegNtPreKeyHandleClose, STATUS_SUCCESS, TRUE, and _CM_KEY_BODY::Type.
Referenced by CmpCreateObjectTypes().
VOID CmpDeleteTree (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 32 of file cmtredel.c.
References ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, Cell, CmKdPrintEx, CML_SAVRES, CmpFindSubKeyByNumber(), CmpFreeKeyByCell(), DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvReleaseCell, NULL, _CM_KEY_NODE::Parent, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmpSyncSubKeysAfterDelete(), and CmRestoreKey().
VOID CmpDereferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1938 of file cmmapvw.c.
References ASSERT_VIEW_LOCK_OWNED, and CM_PAGED_CODE.
Referenced by CmpDereferenceHiveViewWithLock(), and HvWriteHive().
VOID CmpDereferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1998 of file cmmapvw.c.
References CM_PAGED_CODE, CmLockHiveViews, CmpDereferenceHiveView(), and CmUnlockHiveViews.
Referenced by HvpScanForFreeCellInViewWindow(), and HvWriteHive().
VOID CmpDereferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 2093 of file cmsubs.c.
References CmpDereferenceKeyControlBlockWithLock(), CmpLockKCBExclusive, CmpUnlockHashEntry, _CM_KEY_CONTROL_BLOCK::ConvKey, FALSE, InterlockedCompareExchange(), LogKCBReference, and _CM_KEY_CONTROL_BLOCK::RefCount.
Referenced by CmpCacheLookup(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpLateUnloadHiveWorker(), and CmpParseKey().
VOID CmpDereferenceKeyControlBlockWithLock (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 2140 of file cmsubs.c.
References ASSERT_KCB, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_NO_DELAY_CLOSE, CM_KCB_SYM_LINK_FOUND, CmpAddToDelayedClose(), CmpCleanUpKcbCacheWithLock(), CmpHoldLazyFlush, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_CONTROL_BLOCK::ExtFlags, _CM_KEY_CONTROL_BLOCK::Flags, InterlockedDecrement, KEY_SYM_LINK, LogKCBReference, and _CM_KEY_CONTROL_BLOCK::RefCount.
Referenced by CmpAddInfoAfterParseFailure(), CmpCleanUpKcbCacheWithLock(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpDoCreateChild(), CmpDoOpen(), CmpGetSymbolicLink(), CmpIsHiveAlreadyLoaded(), CmpParseKey(), and CmpRunDownDelayDerefKCBEngine().
VOID CmpDestroyCmPrivateAlloc ()
Definition at line 88 of file cmalloc.c.
References CmpAllocInited, and PAGED_CODE.
Referenced by CmpFreeAllMemory().
VOID CmpDestroyCmPrivateDelayAlloc ()
Definition at line 374 of file cmalloc.c.
References CM_PAGED_CODE.
Referenced by CmpFreeAllMemory().
LOGICAL CmpDestroyHive (IN PHHIVE Hive, IN HCELL_INDEX Cell)
Definition at line 803 of file cminit.c.
References ASSERT, CmpFreeKeyByCell(), CmpLockHiveFlusherExclusive, CmpLockHiveListExclusive, CmpRemoveEntryList, CmpUnlockHiveFlusher, CmpUnlockHiveList, FALSE, FIELD_OFFSET, HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyNode, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, Status, TRUE, and _CELL_DATA::u.
Referenced by CmUnloadKey().
VOID CmpDestroyHiveViewList (IN PCMHIVE CmHive)
Definition at line 772 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_PINNED, CcFlushCache(), CcPurgeCacheSection(), CM_PAGED_CODE, CmpUnmapCmView(), CONTAINING_RECORD, ExFreePoolWithTag, FALSE, InitializeListHead(), InsertTailList(), IsListEmpty, _CM_VIEW_OF_FILE::LRUViewList, NULL, _CM_VIEW_OF_FILE::PinViewList, PROTECTED_POOL, RemoveEntryList(), RemoveHeadList(), TRUE, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpInitializeHive(), CmpOverwriteHive(), CmShutdownSystem(), CmUnloadKey(), and HvpRecoverWholeHive().
VOID CmpDestroySecurityCache (IN OUT PCMHIVE CmHive)
Definition at line 616 of file cmsecache.c.
References ASSERT, CmpRemoveEntryList, ExFreePoolWithTag, NULL, PAGED_CODE, and PROTECTED_POOL.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), CmpValidateHiveSecurityDescriptors(), and CmUnloadKey().
NTSTATUS CmpDoAccessCheckOnSubtree (PHHIVE HiveToCheck, HCELL_INDEX Cell, KPROCESSOR_MODE PreviousMode, ACCESS_MASK DesiredAccess, BOOLEAN CheckRoot)
Definition at line 2208 of file cmse.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, Cell, CMP_CHECK_REGISTRY_STACK_ENTRY::Cell, CMP_CHECK_REGISTRY_STACK_ENTRY::CellChecked, CMP_CHECK_REGISTRY_STACK_ENTRY::ChildIndex, CMP_MAX_REGISTRY_DEPTH, CmpCheckKeyAccess(), CmpFindSubKeyByNumber(), ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, HCELL_NIL, HvGetCell, NT_SUCCESS, NULL, PagedPool, PROTECTED_POOL, _HHIVE::ReleaseCellRoutine, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmRenameKey().
NTSTATUS CmpDoCreate (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN PCMHIVE OriginatingHive OPTIONAL, OUT PVOID * Object)
Definition at line 44 of file cmparse2.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, ASSERT, ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE, ASSERT_KCB_LOCKED_EXCLUSIVE, CmIsKcbReadOnly, CmKdPrintEx, CML_PARSE, CmpAddSubKey(), CmpCheckCreateAccess(), CmpCleanUpSubKeyInfo(), CmpDoCreateChild(), CmpFindSubKeyByName(), CmpFreeKeyByCell(), CmpLockHiveFlusherShared, CmpOKToFollowLink(), CmpRemoveKeyControlBlock(), CmpUnlockHiveFlusher, CmUpcaseUnicodeChar, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, KeGetPreviousMode, KeQuerySystemTime(), KEY_CREATE_LINK, KEY_READ, KEY_SYM_LINK, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyNode, _CM_KEY_NODE::LastWriteTime, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, NT_SUCCESS, NULL, ObDereferenceObjectDeferDelete(), OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, REG_CREATED_NEW_KEY, REG_OPTION_BACKUP_RESTORE, REG_OPTION_CREATE_LINK, REG_OPTION_VOLATILE, SeBackupPrivilege, SeRestorePrivilege, SeSinglePrivilegeCheck(), STATUS_ACCESS_DENIED, STATUS_CHILD_MUST_BE_VOLATILE, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_REPARSE, STATUS_SUCCESS, TRUE, _CELL_DATA::u, Volatile, WRITE_DAC, and WRITE_OWNER.
Referenced by CmpParseKey().
NTSTATUS CmpDoCreateChild (IN PHHIVE Hive, IN HCELL_INDEX ParentCell, IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN USHORT Flags, OUT PHCELL_INDEX KeyCell, OUT PVOID * Object)
Definition at line 416 of file cmparse2.c.
References ASSERT, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CM_KCB_KEY_NON_EXIST, CM_KEY_NODE_SIGNATURE, CmKdPrintEx, CML_PARSE, CmLockHiveSecurityExclusive, CMP_CREATE_KCB_KCB_LOCKED, CMP_ENLIST_KCB_LOCKED_EXCLUSIVE, CmpAssignSecurityDescriptorWrapper(), CmpCopyName(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpHKeyNodeSize, CmpKeyObjectType, CmpRemoveKeyControlBlock(), CmpReportNotify(), CmUnlockHiveSecurity, _CHILD_LIST::Count, DbgBreakPoint(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, EnlistKeyBodyWithKCB(), except, EXCEPTION_EXECUTE_HANDLER, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvReleaseCell, KeQuerySystemTime(), KEY_BODY_TYPE, KEY_COMP_NAME, KEY_PREDEF_HANDLE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyString, _CM_KEY_NODE::LastWriteTime, leave, _CHILD_LIST::List, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, _CM_KEY_BODY::NotifyBlock, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), _CM_KEY_NODE::Parent, _OBJECT_TYPE_INITIALIZER::PoolType, _CM_KEY_BODY::ProcessID, PsGetCurrentProcessId(), _CM_KEY_CONTROL_BLOCK::RefCount, REG_NOTIFY_CHANGE_NAME, REG_OPTION_PREDEF_HANDLE, REG_OPTION_VOLATILE, RtlCopyMemory, SeAssignSecurity(), _CM_KEY_NODE::Security, SeDeassignSecurity(), _CM_KEY_NODE::Signature, _CM_KEY_NODE::Spare, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CM_KEY_BODY::Type, _OBJECT_TYPE::TypeInfo, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpCreateLinkNode(), and CmpDoCreate().
NTSTATUS CmpDoFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
Definition at line 231 of file cmwrapr.c.
References _256K, ASSERT, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_PASSIVE_LEVEL, CcFlushCache(), CcPurgeCacheSection(), CM_FILE_GROW_INCREMENT, CM_VIEW_SIZE, CmpFlushOnLockRelease, CmpIoFileSetSize, CmpRegistryLock, CmpUnmapCmViewSurroundingOffset(), CmRegistryIODebug, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, _FILE_END_OF_FILE_INFORMATION::EndOfFile, ExIsResourceAcquiredExclusiveLite(), FALSE, FIELD_OFFSET, FileEndOfFileInformation, _CMHIVE::FileHandles, FileOffset, HFILE_TYPE_PRIMARY, _LARGE_INTEGER::HighPart, HiveWritesThroughCache, IoSetThreadHardErrorMode(), _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, ROUND_UP, Status, _IO_STATUS_BLOCK::Status, STATUS_DISK_FULL, TRUE, and ZwSetInformationFile().
Referenced by CmpFileSetSize(), HvpDoWriteHive(), HvpWriteLog(), and HvWriteHive().
BOOLEAN CmpDoFlushAll (BOOLEAN ForceFlush)
Definition at line 3235 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmKdPrintEx, CML_IO, CmpFixHiveUsageCount(), CmpHiveListHead, CmpLockHiveFlusherExclusive, CmpLockHiveListShared, CmpNoWrite, CmpUnlockHiveFlusher, CmpUnlockHiveList, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _LIST_ENTRY::Flink, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvHiveWillShrink(), HvSyncHive(), NT_SUCCESS, Stable, Status, TRUE, and _CMHIVE::UseCount.
Referenced by CmFlushKey(), CmpUnlockRegistry(), and CmShutdownSystem().
VOID CmpDropFileObjectForHive (IN PCMHIVE CmHive)
Definition at line 899 of file cmmapvw.c.
References ASSERT, CM_PAGED_CODE, ExFreePoolWithTag, NULL, ObDereferenceObject(), and PROTECTED_POOL.
Referenced by CmLoadKey(), CmpAcquireFileObjectForFile(), CmpDestroyTemporaryHive(), CmpInitializeHive(), CmShutdownSystem(), and CmUnloadKey().
HCELL_INDEX CmpDuplicateIndex (PHHIVE Hive, HCELL_INDEX IndexCell, ULONG StorageType)
Definition at line 2730 of file cmindex.c.
References ASSERT, ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, _CM_KEY_INDEX::Count, FALSE, HCELL_NIL, HvDuplicateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), Index, _CM_KEY_INDEX::List, NULL, _CM_KEY_INDEX::Signature, and TRUE.
Referenced by CmpDuplicateKey(), and CmRenameKey().
BOOLEAN CmpFileFlush (PHHIVE Hive, ULONG FileType, PLARGE_INTEGER FileOffset, ULONG Length)
Definition at line 989 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CcFlushCache(), CmKdPrintEx, CML_IO, CmpIoFileFlush, CmpNoWrite, CmRegistryIODebug, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, _CMHIVE::FileObject, HiveWritesThroughCache, NT_SUCCESS, NULL, _FILE_OBJECT::SectionObjectPointer, _IO_STATUS_BLOCK::Status, TRUE, and ZwFlushBuffersFile().
Referenced by CmpInitializeHive(), and CmpSaveKeyByFileCopy().
BOOLEAN CmpFileRead (PHHIVE Hive, ULONG FileType, PULONG FileOffset, PVOID DataBuffer, ULONG DataLength)
Definition at line 411 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmpCreateEvent(), CmpIoFileRead, CmRegistryIODebug, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, Executive, FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, FileOffset, _LARGE_INTEGER::HighPart, _IO_STATUS_BLOCK::Information, KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, MAX_FILE_IO, NT_SUCCESS, NULL, ObDereferenceObject(), _IO_STATUS_BLOCK::Status, STATUS_PENDING, STATUS_SUCCESS, SynchronizationEvent, TRUE, ZwClose(), and ZwReadFile().
Referenced by CmpInitializeHive(), and CmpSaveKeyByFileCopy().
BOOLEAN CmpFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
Definition at line 42 of file cmwrapr2.c.
References ASSERT, ASSERT_HIVE_WRITER_LOCK_OWNED, CmKdPrintEx, CML_BUGCHECK, CmpDoFileSetSize(), DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, NT_SUCCESS, and TRUE.
Referenced by CmpInitializeHive(), and CmpLoadHiveThread().
BOOLEAN CmpFileWrite (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount, PULONG FileOffset)
Definition at line 704 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CmCloseHandle, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmpCreateEvent(), CmpIoFileWrite, CmpNoWrite, CmpSetHandleProtection, CmRegistryIODebug, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, DPFLTR_TRACE_LEVEL, _CM_WRITE_BLOCK::EventHandles, _CM_WRITE_BLOCK::EventObjects, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, FileOffset, CMP_OFFSET_ARRAY::FileOffset, _LARGE_INTEGER::HighPart, _CM_WRITE_BLOCK::IoStatus, KernelMode, KeWaitForMultipleObjects(), _LARGE_INTEGER::LowPart, MAX_FILE_IO, MAXIMUM_WAIT_OBJECTS, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), PAGE_SIZE, perftouchbuffer, _IO_STATUS_BLOCK::Status, STATUS_INVALID_PARAMETER_5, SynchronizationEvent, TRUE, WaitAll, _CM_WRITE_BLOCK::WaitBlockArray, and ZwWriteFile().
Referenced by CmpInitializeHive(), and CmpSaveKeyByFileCopy().
BOOLEAN CmpFileWriteThroughCache (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount)
Definition at line 579 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CcFlushCache(), CcPinRead(), CcSetDirtyPinnedData(), CcUnpinData(), CM_VIEW_SIZE, CmKdPrintEx, CONTAINING_RECORD, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DbgBreakPoint(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CMHIVE::FileObject, FileOffset, CMP_OFFSET_ARRAY::FileOffset, HFILE_TYPE_EXTERNAL, _LARGE_INTEGER::HighPart, HiveWritesThroughCache, _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, PIN_WAIT, RtlCopyMemory, _FILE_OBJECT::SectionObjectPointer, _IO_STATUS_BLOCK::Status, TRUE, and UNREFERENCED_PARAMETER.
Referenced by HvpDoWriteHive(), and HvWriteHive().
HCELL_INDEX CmpFindControlSet (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell, IN PUNICODE_STRING SelectName, OUT PBOOLEAN AutoSelect)
Definition at line 1524 of file cmboot.c.
References ASSERT, _STRING::Buffer, _UNICODE_STRING::Buffer, CmpFindSubKeyByName(), CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, _STRING::Length, _STRING::MaximumLength, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, REG_DWORD, RtlAnsiStringToUnicodeString(), RtlInitUnicodeString(), sprintf(), Status, strlen(), TRUE, and _CM_KEY_VALUE::Type.
Referenced by CmGetSystemControlValues(), and CmGetSystemDriverList().
BOOLEAN CmpFindDrivers (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN SERVICE_LOAD_TYPE LoadType, IN PWSTR BootFileSystem OPTIONAL, IN PLIST_ENTRY DriverListHead)
Definition at line 505 of file cmboot.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CmpAddDriverToList(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpIsLoadType(), CONTAINING_RECORD, _BOOT_DRIVER_NODE::ErrorControl, FALSE, HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, RtlAppendUnicodeToString(), RtlInitUnicodeString(), SERVICE_ERROR_CRITICAL, and TRUE.
Referenced by CmGetSystemDriverList().
BOOLEAN CmpFindNameInList (IN PHHIVE Hive, IN PCHILD_LIST ChildList, IN PUNICODE_STRING Name, IN OPTIONAL PULONG ChildIndex, OUT PHCELL_INDEX CellIndex)
Definition at line 77 of file cmvalue.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmpCompareCompressedName(), FALSE, _CM_KEY_VALUE::Flags, HCELL_NIL, HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyList, _UNICODE_STRING::Length, List, _UNICODE_STRING::MaximumLength, _CM_KEY_VALUE::Name, _CM_KEY_VALUE::NameLength, NULL, RtlCompareUnicodeString(), TRUE, _CELL_DATA::u, and VALUE_COMP_NAME.
Referenced by CmDeleteValueKey(), CmpCopyKeyPartial(), CmpFindValueByName(), CmpMergeKeyValues(), CmpSyncKeyValues(), and CmSetValueKey().
BOOLEAN CmpFindNLSData (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, OUT PUNICODE_STRING AnsiFilename, OUT PUNICODE_STRING OemFilename, OUT PUNICODE_STRING CaseTableFilename, OUT PUNICODE_STRING OemHalFilename)
Definition at line 97 of file cmboot.c.
References ASSERT, _UNICODE_STRING::Buffer, CmpFindSubKeyByName(), CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, RtlInitUnicodeString(), TRUE, and UNICODE_NULL.
HCELL_INDEX CmpFindProfileOption (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, OUT PCM_HARDWARE_PROFILE_LIST * ProfileList, OUT PCM_HARDWARE_PROFILE_ALIAS_LIST * AliasList, OUT PULONG Timeout)
BOOLEAN CmpFindSecurityCellCacheIndex (IN PCMHIVE CmHive, IN HCELL_INDEX SecurityCell, OUT PULONG Index)
Definition at line 308 of file cmsecache.c.
References ASSERT, FALSE, HCELL_TYPE_MASK, NULL, PAGED_CODE, and TRUE.
Referenced by CmpAddSecurityCellToCache(), CmpAssignSecurityToKcb(), CmpCheckNotifyAccess(), CmpCopyKeyPartial(), CmpRemoveFromSecurityCache(), CmpSetSecurityDescriptorInfo(), CmpSyncKeyValues(), and CmpValidateHiveSecurityDescriptors().
HCELL_INDEX CmpFindSubKeyByName (PHHIVE Hive, PCM_KEY_NODE Parent, PUNICODE_STRING SearchName)
Definition at line 193 of file cmindex.c.
References ASSERT, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, CmKdPrintEx, CML_INDEX, CmpFindSubKeyByHash(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvIsCellAllocated(), HvReleaseCell, INVALID_INDEX, NULL, _CM_KEY_INDEX::Signature, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, and _CM_KEY_NODE::SubKeyLists.
Referenced by CmGetSystemControlValues(), CmpCopySyncTree2(), CmpDoCreate(), CmpFindControlSet(), CmpFindDrivers(), CmpFindNLSData(), CmpFindProfileOption(), CmpMarkCurrentValueDirty(), CmpParseKey(), CmpSortDriverList(), CmpSyncSubKeysAfterDelete(), CmpValidateSelect(), CmpWalkPath(), and CmRenameKey().
HCELL_INDEX CmpFindSubKeyByNumber (PHHIVE Hive, PCM_KEY_NODE Parent, ULONG Number)
Definition at line 968 of file cmindex.c.
References CmKdPrintEx, CML_INDEX, CmpDoFindSubKeyByNumber(), DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvReleaseCell, Index, NULL, Stable, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and Volatile.
Referenced by CmEnumerateKey(), CmpCheckRegistry2(), CmpCopySyncTree2(), CmpDeleteTree(), CmpDoAccessCheckOnSubtree(), CmpFindDrivers(), CmpFindProfileOption(), CmpShiftAllCells2(), CmpSyncSubKeysAfterDelete(), and CmpUpdateParentForEachSon().
HCELL_INDEX CmpFindValueByName (PHHIVE Hive, PCM_KEY_NODE KeyNode, PUNICODE_STRING Name)
Definition at line 40 of file cmvalue.c.
References ASSERT, CM_PAGED_CODE, CmpFindNameInList(), FALSE, HCELL_NIL, and NULL.
Referenced by CmGetSystemControlValues(), CmpAddDriverToList(), CmpFindControlSet(), CmpFindNLSData(), CmpFindProfileOption(), CmpFindTagIndex(), CmpGetSymbolicLink(), CmpIsLoadType(), CmpMarkCurrentValueDirty(), CmpSetCurrentProfile(), CmpSortDriverList(), CmpValidateSelect(), and CmQueryMultipleValueKey().
VALUE_SEARCH_RETURN_TYPE CmpFindValueByNameFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING Name, OUT PPCM_CACHED_VALUE * ContainingList, OUT ULONG * Index, OUT PCM_KEY_VALUE * Value, OUT BOOLEAN * ValueCached, OUT PHCELL_INDEX CellToRelease)
Definition at line 307 of file cmtree.c.
References ASSERT, ASSERT_KCB_LOCKED, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_EXCEPTION, CMP_GET_CACHED_ADDRESS, CmpCompareCompressedName(), CmpComputeHashKey(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpIsKCBLockedExclusive, _CACHED_CHILD_LIST::Count, DBG, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, Hive, HvReleaseCell, _UNICODE_STRING::Length, List, _UNICODE_STRING::MaximumLength, NULL, RtlCompareUnicodeString(), SearchFail, SearchSuccess, TRUE, and VALUE_COMP_NAME.
Referenced by CmpCompareNewValueDataAgainstKCBCache(), and CmQueryValueKey().
VOID CmpFixHiveUsageCount (IN PCMHIVE CmHive)
Definition at line 1510 of file cmmapvw.c.
References ASSERT, CM_PAGED_CODE, CmKdPrintEx, CmMaxViewsPerHive, CmpFreeCmView(), CmpUnmapCmView(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _LIST_ENTRY::Flink, InitializeListHead(), _CM_VIEW_OF_FILE::LRUViewList, _CM_VIEW_OF_FILE::PinViewList, RemoveEntryList(), TRUE, and _CM_VIEW_OF_FILE::UseCount.
Referenced by CmFlushKey(), CmpDoFlushAll(), and CmpDoFlushNextHive().
VOID CmpFlushNotifiesOnKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN BOOLEAN LockHeld)
Definition at line 321 of file cmsubs.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, ASSERT_KCB_LOCKED_EXCLUSIVE, ASSERT_KEY_OBJECT, CMP_FAST_KEY_BODY_ARRAY_DUMP, CMP_FAST_KEY_BODY_ARRAY_FLUSH, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpFlushNotify(), CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, InterlockedCompareExchangePointer, IsListEmpty, _CM_KEY_BODY::KeyBodyList, _CM_KEY_BODY::NotifyBlock, NULL, ObDereferenceObjectDeferDelete(), and ObReferenceObjectSafe().
Referenced by CmDeleteKey(), CmpSearchForOpenSubKeys(), CmUnloadKey(), and NtRenameKey().
VOID CmpFlushNotify (PCM_KEY_BODY KeyBody, BOOLEAN LockHeld)
Definition at line 1229 of file cmnotify.c.
References ASSERT_CM_LOCK_OWNED, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _LIST_ENTRY::Blink, CM_PAGED_CODE, CmLockHive, CmpClearListEntry, CmpPostNotify(), CmUnlockHive, CONTAINING_RECORD, DBG, ExFreePool(), FALSE, _LIST_ENTRY::Flink, Hive, _CM_NOTIFY_BLOCK::HiveList, IsListEmpty, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_BODY::NotifyBlock, NULL, _CM_NOTIFY_BLOCK::PostList, SeReleaseSubjectContext(), STATUS_NOTIFY_CLEANUP, and _CM_NOTIFY_BLOCK::SubjectContext.
Referenced by CmpDeleteKeyObject(), CmpFlushNotifiesOnKeyBodyList(), CmpRefreshHive(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpFree (PVOID MemoryBlock, ULONG GlobalQuotaSize)
Definition at line 192 of file cmwrapr.c.
References ASSERT, CmKdPrintEx, CML_POOL, CmpReleaseGlobalQuota(), DPFLTR_CONFIG_ID, ExFreePool(), and RtlGetCallersAddress().
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), CmUnloadKey(), HvFreeHive(), HvFreeHivePartial(), HvpDoWriteHive(), HvpDropAllPagedBins(), and HvpDropPagedBins().
VOID CmpFreeDelayItem (PVOID Item)
Definition at line 492 of file cmalloc.c.
References ASSERT, CM_DELAY_ALLOC_ENTRY_SIZE, CM_DELAYS_PER_PAGE, CM_PAGED_CODE, CmpRemoveEntryList, DELAY_ALLOC_TO_ALLOC_PAGE, ExFreePoolWithTag, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, InsertTailList(), _CM_DELAY_ALLOC::ListEntry, LOCK_DELAY_ALLOC_BUCKET, PROTECTED_POOL, and UNLOCK_DELAY_ALLOC_BUCKET.
BOOLEAN CmpFreeKeyBody (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2226 of file cmsubs.c.
References ASSERT, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, KEY_HIVE_EXIT, _CELL_DATA::_u::KeyNode, NULL, _CM_KEY_NODE::Security, TRUE, and _CELL_DATA::u.
Referenced by CmpFreeKeyByCell().
NTSTATUS CmpFreeKeyByCell (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN Unlink)
Definition at line 176 of file cmtredel.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, CmLockHiveSecurityExclusive, CmpFreeKeyBody(), CmpFreeSecurityDescriptor(), CmpFreeValue(), CmpMarkKeyDirty(), CmpRemoveSubKey(), CmUnlockHiveSecurity, _CHILD_LIST::Count, DBG, FALSE, _CM_KEY_NODE::Flags, HvFreeCell(), HvGetCell, HvReleaseCell, KEY_HIVE_EXIT, KEY_PREDEF_HANDLE, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyNode, _CHILD_LIST::List, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, NULL, _CM_KEY_NODE::Parent, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmDeleteKey(), CmMoveKey(), CmpDeleteTree(), CmpDestroyHive(), CmpDoCreate(), CmpDuplicateKey(), CmpSyncSubKeysAfterDelete(), and CmRestoreKey().
VOID CmpFreeKeyControlBlock (PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 241 of file cmalloc.c.
References ASSERT, ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE, ASSERT_KEYBODY_LIST_EMPTY, CM_KCB_ENTRY_SIZE, CM_KCBS_PER_PAGE, CMP_KCB_REAL_NAME_UPCASE, _CM_KEY_CONTROL_BLOCK::ConvKey, ExFreePoolWithTag, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, _CM_KEY_CONTROL_BLOCK::FreeListEntry, InsertTailList(), KCB_TO_ALLOC_PAGE, LOCK_ALLOC_BUCKET, LogKCBFree, NULL, PAGED_CODE, _CM_KEY_CONTROL_BLOCK::PrivateAlloc, PROTECTED_POOL, RemoveEntryList(), and UNLOCK_ALLOC_BUCKET.
Referenced by CmpCleanUpKcbCacheWithLock(), and CmpCreateKeyControlBlock().
VOID CmpFreePostBlock (IN PCM_POST_BLOCK PostBlock)
Definition at line 4496 of file ntapi.c.
References ASSERT, CmKdPrintEx, CML_FLOW, CmpClearListEntry, DPFLTR_CONFIG_ID, ExFreePool(), IsListEmpty, IsMasterPostBlock, ObDereferenceObjectDeferDelete(), PostAsyncKernel, PostAsyncUser, PostBlockType, PostSynchronous, and REG_NOTIFY_MASTER_POST.
Referenced by CmNotifyRunDown(), CmpFreeSlavePost(), CmpNotifyChangeKey(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), and NtNotifyChangeMultipleKeys().
VOID CmpFreeSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell)
Definition at line 1709 of file cmse.c.
References ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_NODE, ASSERT_SECURITY, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpRemoveSecurityCellList(), DPFLTR_CONFIG_ID, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyNode, _CELL_DATA::_u::KeySecurity, NULL, _CM_KEY_SECURITY::ReferenceCount, _CM_KEY_NODE::Security, and _CELL_DATA::u.
Referenced by CmpFreeKeyByCell(), and CmpSyncKeyValues().
BOOLEAN CmpFreeValue (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 952 of file cmvalue.c.
References ASSERT, CM_PAGED_CODE, CmpFreeValueData(), _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, FALSE, HvFreeCell(), HvGetCell, HvReleaseCell, NULL, and TRUE.
Referenced by CmDeleteValueKey(), CmpFreeKeyByCell(), CmpFreeKeyValues(), and CmpSetValueKeyNew().
BOOLEAN CmpFreeValueData (PHHIVE Hive, HCELL_INDEX DataCell, ULONG DataLength)
Definition at line 832 of file cmvalue.c.
References ASSERT, ASSERT_BIG_DATA, CM_PAGED_CODE, CmpIsHKeyValueBig, CmpIsHKeyValueSmall, _CM_BIG_DATA::Count, FALSE, HCELL_NIL, HvFreeCell(), HvGetCell, HvIsCellAllocated(), HvReleaseCell, _CM_BIG_DATA::List, NULL, and TRUE.
Referenced by CmpCopyValue(), CmpFreeValue(), and CmpSetValueKeyExisting().
PCM_NAME_CONTROL_BLOCK CmpGetNameControlBlock (PUNICODE_STRING NodeName, PBOOLEAN NameUpCase)
Definition at line 977 of file cmsubs.c.
References _UNICODE_STRING::Buffer, CMP_DEST_UP, CmpCompareCompressedName(), CmpLockNameHashEntryExclusive, CmpUnlockNameHashEntry, CmUpcaseUnicodeChar, _CM_NAME_CONTROL_BLOCK::Compressed, CONTAINING_RECORD, _CM_NAME_HASH::ConvKey, _CM_NAME_CONTROL_BLOCK::ConvKey, _CM_NAME_HASH_TABLE_ENTRY::Entry, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, GET_HASH_INDEX, Index, _UNICODE_STRING::Length, _CM_NAME_CONTROL_BLOCK::Name, _CM_NAME_CONTROL_BLOCK::NameHash, _CM_NAME_CONTROL_BLOCK::NameLength, _CM_NAME_HASH::NextHash, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, PROTECTED_POOL, _CM_NAME_CONTROL_BLOCK::RefCount, RtlZeroMemory, and TRUE.
Referenced by CmpCreateKeyControlBlock(), and CmRenameKey().
BOOLEAN CmpGetNextName (IN OUT PUNICODE_STRING RemainingName, OUT PUNICODE_STRING NextName, OUT PBOOLEAN Last)
Definition at line 1216 of file cmparse.c.
References FALSE, NULL, OBJ_NAME_PATH_SEPARATOR, REG_MAX_KEY_NAME_LENGTH, TRUE, and UNICODE_NULL.
Referenced by CmpParseKey(), and CmpWalkPath().
BOOLEAN CmpGetValueData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize, IN OUT PVOID * Buffer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
Definition at line 235 of file cmvalue.c.
References ASSERT, ASSERT_BIG_DATA, ASSERT_KEY_VALUE, CM_KEY_VALUE_BIG, CM_PAGED_CODE, CmpIsHKeyValueBig, CmpIsHKeyValueSmall, _CM_BIG_DATA::Count, ExAllocatePoolWithTag, ExFreePool(), FALSE, HCELL_NIL, HvGetCell, HvReleaseCell, leave, _CM_BIG_DATA::List, NULL, PagedPool, RtlCopyMemory, and TRUE.
Referenced by CmGetSystemControlValues(), CmpCopyValue(), CmpFindTagIndex(), CmpGetSymbolicLink(), CmpGetValueDataFromCache(), CmpValueToData(), and CmQueryMultipleValueKey().
VALUE_SEARCH_RETURN_TYPE CmpGetValueDataFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PPCM_CACHED_VALUE ContainingList, IN PCELL_DATA ValueKey, IN BOOLEAN ValueCached, OUT PUCHAR * DataPointer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
Definition at line 521 of file cmtree.c.
References ASSERT, ASSERT_KCB_LOCKED, CM_CACHE_DATA_CACHED, CM_CACHE_DATA_NOT_CACHED, CM_CACHE_DATA_TOO_BIG, CM_KEY_VALUE_BIG, CM_KEY_VALUE_SPECIAL_SIZE, CMP_GET_CACHED_ADDRESS, CMP_MARK_CELL_CACHED, CmpGetValueData(), CmpIsKCBLockedExclusive, CmpMakeSpecialPoolReadOnly, CmpMakeSpecialPoolReadWrite, CmpTryConvertKCBLockSharedToExclusive(), _CM_CACHED_VALUE::DataCacheType, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, _CM_CACHED_VALUE::HashKey, HCELL_NIL, Hive, HvGetCell, _CM_CACHED_VALUE::KeyValue, MAXIMUM_CACHED_DATA, NULL, PagedPool, RtlCopyMemory, SearchFail, SearchNeedExclusiveLock, SearchSuccess, and _CM_CACHED_VALUE::ValueKeySize.
Referenced by CmpCompareNewValueDataAgainstKCBCache(), and CmpQueryKeyValueData().
VALUE_SEARCH_RETURN_TYPE CmpGetValueKeyFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PCELL_DATA List, IN ULONG Index, OUT PPCM_CACHED_VALUE * ContainingList, OUT PCM_KEY_VALUE * Value, IN BOOLEAN IndexCached, OUT BOOLEAN * ValueCached, OUT PHCELL_INDEX CellToRelease)
Definition at line 154 of file cmtree.c.
References _UNICODE_STRING::Buffer, CM_CACHE_DATA_NOT_CACHED, CMP_GET_CACHED_ADDRESS, CMP_GET_CACHED_KEYVALUE, CMP_IS_CELL_CACHED, CMP_MARK_CELL_CACHED, CmpComputeHashKey(), CmpComputeHashKeyForCompressedName(), CmpIsKCBLockedExclusive, CmpMakeSpecialPoolReadOnly, CmpMakeSpecialPoolReadWrite, CmpTryConvertKCBLockSharedToExclusive(), _CM_CACHED_VALUE::DataCacheType, DBG, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, _CM_CACHED_VALUE::HashKey, HCELL_NIL, Hive, HvGetCell, HvGetCellSize(), Index, _CM_CACHED_VALUE::KeyValue, _UNICODE_STRING::Length, NULL, PagedPool, RtlCopyMemory, SearchFail, SearchNeedExclusiveLock, SearchSuccess, TRUE, VALUE_COMP_NAME, and _CM_CACHED_VALUE::ValueKeySize.
Referenced by CmEnumerateValueKey(), and CmpFindValueByNameFromCache().
VALUE_SEARCH_RETURN_TYPE CmpGetValueListFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, OUT PCELL_DATA * List, OUT BOOLEAN * IndexCached, OUT PHCELL_INDEX ValueListToRelease)
Definition at line 31 of file cmtree.c.
References ASSERT_KCB_LOCKED, _CM_CACHED_VALUE_INDEX::CellIndex, CMP_GET_CACHED_CELL_INDEX, CMP_GET_CACHED_CELLDATA, CMP_IS_CELL_CACHED, CMP_MARK_CELL_CACHED, CmpIsKCBLockedExclusive, CmpMakeSpecialPoolReadOnly, CmpTryConvertKCBLockSharedToExclusive(), _CACHED_CHILD_LIST::Count, _CM_CACHED_VALUE_INDEX::Data, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, HCELL_NIL, Hive, HvGetCell, _CM_CACHED_VALUE_INDEX::List, NULL, PagedPool, SearchFail, SearchNeedExclusiveLock, SearchSuccess, TRUE, and _CACHED_CHILD_LIST::ValueList.
Referenced by CmEnumerateValueKey(), and CmpFindValueByNameFromCache().
PSECURITY_DESCRIPTOR CmpHiveRootSecurityDescriptor (VOID)
Definition at line 1484 of file cmse.c.
References _ACE_HEADER::AceFlags, ACL_REVISION, ALLOCATE_SECURITY_DESCRIPTOR, ASSERT, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CONTAINER_INHERIT_ACE, DOMAIN_ALIAS_RID_ADMINS, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, KEY_ALL_ACCESS, KEY_READ, NT_SUCCESS, NULL, PagedPool, REGISTRY_ERROR, RtlAddAccessAllowedAce(), RtlCopyMemory, RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlGetAce(), RtlInitializeSid(), RtlLengthRequiredSid(), RtlSetDaclSecurityDescriptor(), RtlSubAuthoritySid(), RtlValidSid(), SECURITY_BUILTIN_DOMAIN_RID, SECURITY_DESCRIPTOR_REVISION, SECURITY_LOCAL_SYSTEM_RID, SECURITY_NT_AUTHORITY, SECURITY_RESTRICTED_CODE_RID, SECURITY_WORLD_RID, SECURITY_WORLD_SID_AUTHORITY, SeLengthSid, Status, and TRUE.
Referenced by CmInitSystem1(), CmpCreateRegistryRoot(), CmpInitializeHiveList(), and CmpInitializeSystemHive().
VOID CmpInitCmPrivateAlloc ()
Definition at line 53 of file cmalloc.c.
References CmpAllocInited, InitializeListHead(), KeInitializeGuardedMutex(), and TRUE.
Referenced by CmInitSystem1().
VOID CmpInitCmPrivateDelayAlloc ()
Definition at line 348 of file cmalloc.c.
References InitializeListHead(), and KeInitializeGuardedMutex().
Referenced by CmInitSystem1().
VOID CmpInitDelayDerefKCBEngine ()
Definition at line 585 of file cmdelay.c.
References CmpDelayDerefKCBDpcRoutine(), CmpDelayDerefKCBWorker(), ExInitializeWorkItem, InitializeListHead(), KeInitializeDpc(), KeInitializeGuardedMutex(), KeInitializeTimer(), and NULL.
Referenced by CmInitSystem1().
NTSTATUS CmpInitHiveFromFile (IN PUNICODE_STRING FileName, IN ULONG HiveFlags, OUT PCMHIVE * CmHive, IN OUT PBOOLEAN Allocate, IN ULONG CheckFlags)
Definition at line 2011 of file cmsysini.c.
References CM_PAGED_CODE, CmpInitializeHive(), CmpOpenHiveFiles(), CmpRaiseSelfHealWarning(), CmpSetHandleProtection, CmpShareSystemHives, CmpTrackHiveClose, ExAllocatePoolWithTag, FALSE, FILE_CREATED, HBOOT_SELFHEAL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, HINIT_CREATE, HINIT_FILE, HINIT_MAPFILE, HvShutdownComplete, NT_SUCCESS, NULL, PagedPool, PROTECTED_POOL, RtlCopyMemory, Status, STATUS_RETRY, STATUS_SUCCESS, STATUS_TOO_LATE, TRUE, and ZwClose().
Referenced by CmpCmdHiveOpen(), and CmpLoadHiveThread().
VOID CmpInitHiveViewList (IN PCMHIVE CmHive)
Definition at line 741 of file cmmapvw.c.
References CM_PAGED_CODE, and InitializeListHead().
Referenced by CmGetSystemControlValues(), and CmpInitializeHive().
VOID CmpInitializeCache (VOID)
Referenced by CmInitSystem1().
VOID CmpInitializeDelayedCloseTable ()
Definition at line 146 of file cmdelay.c.
References CmpDelayCloseDpcRoutine(), CmpDelayCloseWorker(), ExInitializeWorkItem, InitializeListHead(), KeInitializeDpc(), KeInitializeGuardedMutex(), KeInitializeTimer(), and NULL.
Referenced by CmpInitializeCache().
NTSTATUS CmpInitializeHardwareConfiguration (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 79 of file cmconfig.c.
References ASSERT, _OBJECT_ATTRIBUTES::Attributes, CmpConfigurationAreaSize, CmpSetupConfigurationTree(), CmRegistryMachineHardwareDescriptionName, CmRegistryMachineHardwareDeviceMapName, ExAllocatePool, ExFreePool(), InitializeObjectAttributes, KEY_READ, KEY_WRITE, NT_SUCCESS, NtClose(), NtCreateKey(), NULL, OBJ_CASE_INSENSITIVE, PagedPool, REG_CREATED_NEW_KEY, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TITLE_INDEX_VALUE.
Referenced by CmInitSystem1().
NTSTATUS CmpInitializeHive (PCMHIVE * CmHive, ULONG OperationType, ULONG HiveFlags, ULONG FileType, PVOID HiveData OPTIONAL, HANDLE Primary, HANDLE Log, HANDLE External, PUNICODE_STRING FileName OPTIONAL, ULONG CheckFlags)
Definition at line 511 of file cminit.c.
References ARGUMENT_PRESENT, ASSERT, ASSERT_PASSIVE_LEVEL, _LIST_ENTRY::Blink, _UNICODE_STRING::Buffer, _FILE_FS_SIZE_INFORMATION::BytesPerSector, _CMHIVE::CellRemapArray, CM_DONT_ADD_TO_HIVE_LIST, CmCheckRegistry(), CmKdPrintEx, CML_BUGCHECK, CML_INIT, CmpAllocate(), CmpCheckForOrphanedKcbs, CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFileFlush(), CmpFileRead(), CmpFileSetSize(), CmpFileWrite(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpInitHiveViewList(), CmpInitSecurityCache(), CmpLockHiveListExclusive, CmpShareSystemHives, CmpUnJoinClassOfTrust, CmpUnlockHiveList, _CMHIVE::CreatorOwner, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, ExAllocatePoolWithTag, ExInitializePushLock(), ExInitializeResourceLite(), FALSE, FileFsSizeInformation, _CMHIVE::FileFullPath, _CMHIVE::FileHandles, _CMHIVE::FileObject, _CMHIVE::FileUserName, _CMHIVE::Flags, _LIST_ENTRY::Flink, _CMHIVE::FlushCount, _CMHIVE::FlusherLock, _CMHIVE::Frozen, _CMHIVE::GrowOffset, _CMHIVE::GrowOnlyMode, HBLOCK_SIZE, HFILE_TYPE_EXTERNAL, HFILE_TYPE_LOG, HFILE_TYPE_MAX, HFILE_TYPE_PRIMARY, HINIT_FILE, HINIT_MAPFILE, HINIT_MEMORY, HINIT_MEMORY_INPLACE, _CMHIVE::Hive, HIVE_HAS_BEEN_FREED, HIVE_VOLATILE, _HHIVE::HiveFlags, _CMHIVE::HiveList, _CMHIVE::HiveLock, HSECTOR_SIZE, HvFreeHive(), HvInitializeHive(), HvpCleanMap(), HvpFreeHiveFreeDisplay(), InitializeListHead(), InsertTailList(), _CMHIVE::KcbConvertListHead, KeInitializeGuardedMutex(), _CMHIVE::KnodeConvertListHead, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NonPagedPool, _CMHIVE::NotifyList, NT_SUCCESS, NULL, _CMHIVE::RootKcb, _CMHIVE::SecurityLock, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, TRUE, _CMHIVE::TrustClassEntry, _CMHIVE::UnloadEvent, _CMHIVE::UnloadWorkItem, _CMHIVE::ViewLock, _CMHIVE::WriterLock, and ZwQueryVolumeInformationFile().
Referenced by CmInitSystem1(), CmpCreateTemporaryHive(), CmpInitHiveFromFile(), CmpInitializeSystemHive(), CmpLoadHiveVolatile(), and CmRestoreKey().
VOID CmpInitializeKeyNameString (PCM_KEY_NODE Cell, PUNICODE_STRING KeyName, WCHAR * NameBuffer)
Definition at line 2058 of file cmtrecpy.c.
References _UNICODE_STRING::Buffer, CmpCompressedNameSize(), CmpCopyCompressedName(), _CM_KEY_NODE::Flags, KEY_COMP_NAME, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, and REG_MAX_KEY_NAME_LENGTH.
Referenced by CmpCopySyncTree2(), CmpNotifyChangeKey(), and CmpSyncSubKeysAfterDelete().
NTSTATUS CmpInitializeMachineDependentConfiguration (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by CmInitSystem1().
VOID CmpInitializeRegistryNames (VOID)
Definition at line 80 of file cmdatini.c.
References CmClassName, CmClassString, CmpRegistryMachineHardwareDescriptionString, CmpRegistryMachineHardwareDescriptionSystemString, CmpRegistryMachineHardwareDeviceMapString, CmpRegistryMachineHardwareOwnerMapString, CmpRegistryMachineHardwareResourceMapString, CmpRegistryMachineHardwareString, CmpRegistryMachineString, CmpRegistryMachineSystemCurrentControlSetControlBootLogString, CmpRegistryMachineSystemCurrentControlSetControlClassString, CmpRegistryMachineSystemCurrentControlSetControlSafeBootString, CmpRegistryMachineSystemCurrentControlSetControlSessionManagerMemoryManagementString, CmpRegistryMachineSystemCurrentControlSetEnumRootString, CmpRegistryMachineSystemCurrentControlSetEnumString, CmpRegistryMachineSystemCurrentControlSetHardwareProfilesCurrentString, CmpRegistryMachineSystemCurrentControlSetServicesEventLogString, CmpRegistryMachineSystemCurrentControlSetServicesString, CmpRegistryMachineSystemCurrentControlSetString, CmpRegistryMachineSystemString, CmpRegistryRootString, CmpRegistrySystemCloneString, CmpRegistrySystemFileNameString, CmpRegistryUserString, CmpSymbolicLinkValueName, CmRegistryMachineSystemCurrentControlSetControlBootLog, CmRegistryMachineSystemCurrentControlSetControlSafeBoot, CmRegistryMachineSystemCurrentControlSetControlSessionManagerMemoryManagement, CmRegistryMachineSystemCurrentControlSetServicesEventLog, CmTypeName, CmTypeString, MaximumClass, MaximumType, and RtlInitUnicodeString().
Referenced by CmInitSystem1().
NTSTATUS CmpInitializeRegistryNode (IN PCONFIGURATION_COMPONENT_DATA CurrentEntry, IN HANDLE ParentHandle, OUT PHANDLE NewHandle, IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PUSHORT DeviceIndexTable)
Definition at line 373 of file cmconfig.c.
References ArcSystem, ASSERT, _OBJECT_ATTRIBUTES::Attributes, _UNICODE_STRING::Buffer, _CM_FULL_RESOURCE_DESCRIPTOR::BusNumber, _CONFIGURATION_COMPONENT::Class, CmpConfigurationAreaSize, CmTypeName, _CONFIGURATION_COMPONENT::ConfigurationDataLength, _CM_PARTIAL_RESOURCE_LIST::Count, ExAllocatePool, ExFreePool(), FALSE, FIELD_OFFSET, _CONFIGURATION_COMPONENT::Flags, Handle, _CONFIGURATION_COMPONENT::Identifier, _CONFIGURATION_COMPONENT::IdentifierLength, InitializeObjectAttributes, InterfaceType, _CM_FULL_RESOURCE_DESCRIPTOR::InterfaceType, KEY_READ, KEY_WRITE, KeyName, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NtCreateKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, PagedPool, _CM_FULL_RESOURCE_DESCRIPTOR::PartialResourceList, REG_BINARY, REG_CREATED_NEW_KEY, REG_FULL_RESOURCE_DESCRIPTOR, REG_SZ, _CM_PARTIAL_RESOURCE_LIST::Revision, RtlAnsiStringToUnicodeString(), RtlCopyMemory, RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), RtlIntegerToChar(), Status, STATUS_SUCCESS, SystemClass, TITLE_INDEX_VALUE, TRUE, _CONFIGURATION_COMPONENT::Type, UNICODE_NULL, and _CM_PARTIAL_RESOURCE_LIST::Version.
Referenced by CmpSetupConfigurationTree().
VOID CmpInitializeValueNameString (PCM_KEY_VALUE Cell, PUNICODE_STRING ValueName, WCHAR * NameBuffer)
Definition at line 2125 of file cmtrecpy.c.
References _UNICODE_STRING::Buffer, CmpCompressedNameSize(), CmpCopyCompressedName(), _CM_KEY_VALUE::Flags, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_VALUE::Name, _CM_KEY_VALUE::NameLength, REG_MAX_KEY_VALUE_NAME_LENGTH, and VALUE_COMP_NAME.
Referenced by CmpCopyKeyPartial(), CmpMergeKeyValues(), and CmpSyncKeyValues().
VOID CmpInitSecurityCache (IN OUT PCMHIVE CmHive)
Definition at line 103 of file cmsecache.c.
References CmpSecHashTableSize, InitializeListHead(), NULL, and PAGED_CODE.
Referenced by CmGetSystemControlValues(), CmpInitializeHive(), and CmpValidateHiveSecurityDescriptors().
BOOLEAN CmpKCBLockForceAcquireAllowed (ULONG Index1, ULONG Index2, ULONG NewIndex)
Definition at line 498 of file cmsubs3.c.
References ASSERT, CmpHashTableSize, FALSE, and TRUE.
Referenced by CmpCleanUpKCBCacheTable(), CmpRunDownDelayDerefKCBEngine(), and CmpSearchForOpenSubKeys().
VOID CmpLazyFlush (VOID)
Definition at line 446 of file cmworker.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_IO, CmpHoldLazyFlush, CmpLazyFlushIntervalInSeconds, CmpNoWrite, DPFLTR_CONFIG_ID, Int32x32To64, KeSetTimer(), _LARGE_INTEGER::QuadPart, and SECOND_MULT.
Referenced by CmpLazyFlushWorker(), HvMarkDirty(), and NtInitializeRegistry().
NTSTATUS CmpLinkHiveToMaster (PUNICODE_STRING LinkName, HANDLE RootDirectory, PCMHIVE CmHive, BOOLEAN Allocate, PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 1267 of file cmsysini.c.
References ASSERT, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::ChildHive, _CM_PARSE_CONTEXT::Class, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpReportNotify(), _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _HHIVE::DirtyFlag, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, _CMHIVE::Hive, InitializeObjectAttributes, KernelMode, KEY_READ, KEY_WRITE, _CM_KEY_REFERENCE::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_REFERENCE::KeyHive, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, REG_NOTIFY_CHANGE_NAME, _HBASE_BLOCK::RootCell, Status, STATUS_SUCCESS, _CM_PARSE_CONTEXT::TitleIndex, TRUE, and ZwClose().
Referenced by CmInitSystem1(), CmLoadKey(), CmpInitializeHiveList(), CmpInitializeSystemHive(), and CmpLoadHiveVolatile().
VOID CmpLockRegistry (VOID)
Definition at line 70 of file cmsubs3.c.
References CmKdPrintEx, CML_LOCKING, CmpFlushStarveWriters, DPFLTR_CONFIG_ID, ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), KeEnterCriticalRegion(), RtlGetCallersAddress(), and TRUE.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmLoadKey(), CmNotifyRunDown(), CmpBuildHashStackAndLookupCache(), CmpCloseKeyObject(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpLateUnloadHiveWorker(), CmpLazyFlushWorker(), CmpQueryKeyName(), CmPrefetchHivePages(), CmpSecurityMethod(), CmpWmiDumpKcbTable(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), NtFlushKey(), NtLockRegistryKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), and NtUnloadKey2().
VOID CmpLockRegistryExclusive (VOID)
Definition at line 116 of file cmsubs3.c.
References ASSERT, CmpFlushStarveWriters, ExAcquireResourceExclusiveLite(), KeEnterCriticalRegion(), RtlGetCallersAddress(), and TRUE.
Referenced by CmFlushKey(), CmGetSystemDriverList(), CmInitSystem1(), CmLoadKey(), CmpCloneControlSet(), CmpLateUnloadHiveWorker(), CmpLazyFlushWorker(), CmpLoadHiveVolatile(), CmpRefreshHive(), CmpSaveBootControlSet(), CmpSaveKeyByFileCopy(), CmRestoreKey(), CmSaveKey(), CmShutdownSystem(), NtCompactKeys(), NtCompressKey(), NtInitializeRegistry(), NtRenameKey(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpLockTwoHashEntriesExclusive (ULONG ConvKey1, ULONG ConvKey2)
Definition at line 267 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, CmpLockHashEntryExclusive, and GET_HASH_INDEX.
Referenced by CmDeleteKey(), CmpCreateKeyControlBlock(), CmpGetSymbolicLink(), CmUnloadKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), and NtUnloadKey2().
VOID CmpLockTwoHashEntriesShared (ULONG ConvKey1, ULONG ConvKey2)
Definition at line 311 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, CmpLockHashEntryShared, and GET_HASH_INDEX.
Referenced by CmSaveMergedKeys(), and NtNotifyChangeMultipleKeys().
NTSTATUS CmpMapCmView (IN PCMHIVE CmHive, IN ULONG FileOffset, OUT PCM_VIEW_OF_FILE * CmView, IN BOOLEAN MapInited)
Definition at line 294 of file cmmapvw.c.
References ASSERT, ASSERT_BIN_INVALID, ASSERT_BIN_INVIEW, ASSERT_VIEW_LOCK_OWNED, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _UNICODE_STRING::Buffer, CcMapData(), CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_BIN_MAP, CmMaxViewsPerHive, CmpAllocateCmView(), CmpUnmapCmView(), CmpUnmapUnusedViews(), _HMAP_ENTRY::CmView, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HBIN_BASE, HBIN_FLAGS, HBLOCK_SIZE, _LARGE_INTEGER::HighPart, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HvpGetCellMap(), IsListEmpty, _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, MAP_NO_READ, MAP_WAIT, NT_SUCCESS, NULL, RtlInitUnicodeString(), _HBIN::Size, Stable, Status, STATUS_CANT_WAIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and VALIDATE_CELL_MAP.
Referenced by CmpMapThisBin(), HvMarkDirty(), HvpGetCellMapped(), HvpMapFileImageAndBuildMap(), HvpRecoverWholeHive(), and HvRefreshHive().
NTSTATUS CmpMapThisBin (PCMHIVE CmHive, HCELL_INDEX Cell, BOOLEAN Touch)
Definition at line 1074 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, CM_PAGED_CODE, CmpMapCmView(), CmpTouchView(), HvGetCellType, NT_SUCCESS, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by HvCheckHive(), HvCloneHive(), HvpAddBin(), HvpRecoverData(), HvpScanForFreeCellInViewWindow(), and HvWriteHive().
BOOLEAN CmpMarkIndexDirty (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
Definition at line 2311 of file cmindex.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmpCompressedNameSize(), CmpCopyCompressedName(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvGetCell, HvIsCellAllocated(), HvMarkCellDirty(), HvReleaseCell, Index, INVALID_INDEX, KEY_COMP_NAME, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, PagedPool, _CM_KEY_INDEX::Signature, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpMarkKeyDirty(), CmpMarkKeyParentDirty(), and CmRenameKey().
BOOLEAN CmpMarkKeyDirty (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 347 of file cmtredel.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, _CM_KEY_SECURITY::Blink, Cell, _CM_KEY_NODE::Class, CmpMarkIndexDirty(), CmpMarkValueDataDirty(), _CHILD_LIST::Count, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_SECURITY::Flink, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, KEY_PREDEF_HANDLE, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyNode, _CELL_DATA::_u::KeySecurity, _CELL_DATA::_u::KeyValue, _CHILD_LIST::List, NULL, _CM_KEY_NODE::Parent, _CM_KEY_NODE::Security, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmMoveKey(), and CmpFreeKeyByCell().
BOOLEAN CmpMarkValueDataDirty (IN PHHIVE Hive, IN PCM_KEY_VALUE Value)
Definition at line 706 of file cmvalue.c.
References ASSERT_BIG_DATA, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_KEY_VALUE, CM_PAGED_CODE, CmpIsHKeyValueBig, CmpIsHKeyValueSmall, _CM_BIG_DATA::Count, FALSE, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, _CM_BIG_DATA::List, NULL, and TRUE.
Referenced by CmDeleteValueKey(), CmpMarkKeyDirty(), CmpMarkKeyValuesDirty(), and CmpSetValueKeyExisting().
USHORT CmpNameSize (IN PHHIVE Hive, IN PUNICODE_STRING Name)
Definition at line 33 of file cmname.c.
NTSTATUS CmpNotifyChangeKey (IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK PostBlock, IN ULONG CompletionFilter, IN BOOLEAN WatchTree, IN PVOID Buffer, IN ULONG BufferSize, IN PCM_POST_BLOCK MasterPostBlock)
Definition at line 1355 of file cmnotify.c.
References APC_LEVEL, ASSERT, ASSERT_CM_LOCK_OWNED, _LIST_ENTRY::Blink, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CML_POOL, CmpFreePostBlock(), CmpInitializeKeyNameString(), CmpPostNotify(), CONTAINING_RECORD, DBG, DPFLTR_CONFIG_ID, ExAllocatePool, ExAllocatePoolWithQuotaTag, ExFreePool(), FALSE, _CM_NOTIFY_BLOCK::Filter, _LIST_ENTRY::Flink, HCELL_NIL, Hive, _CM_NOTIFY_BLOCK::HiveList, HvGetCell, HvReleaseCell, InitializeListHead(), InsertHeadList(), InsertTailList(), IsMasterPostBlock, KeLowerIrql, KeRaiseIrql, _CM_NOTIFY_BLOCK::KeyBody, _CM_NOTIFY_BLOCK::KeyControlBlock, KeyName, _UNICODE_STRING::Length, _CMHIVE::NotifyList, _CM_NOTIFY_BLOCK::NotifyPending, NULL, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _CM_NOTIFY_BLOCK::PostList, PsGetCurrentThread(), REG_MAX_KEY_NAME_LENGTH, SeCaptureSubjectContext(), STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NOTIFY_ENUM_DIR, STATUS_PENDING, STATUS_SUCCESS, _CM_NOTIFY_BLOCK::SubjectContext, _CM_KEY_CONTROL_BLOCK::TotalLevels, TRUE, UNREFERENCED_PARAMETER, and _CM_NOTIFY_BLOCK::WatchTree.
Referenced by NtNotifyChangeMultipleKeys().
NTSTATUS CmpOpenHiveFiles (PUNICODE_STRING BaseName, PWSTR Extension OPTIONAL, PHANDLE Primary, PHANDLE Secondary, PULONG PrimaryDisposition, PULONG SecondaryDispoition, BOOLEAN CreateAllowed, BOOLEAN MarkAsSystemHive, BOOLEAN NoBuffering, PULONG ClusterSize)
NTSTATUS CmpOverwriteHive (PCMHIVE CmHive, PCMHIVE NewHive, HCELL_INDEX LinkCell)
Definition at line 1880 of file cmsavres.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, CM_PAGED_CODE, CmpDestroyHiveViewList(), _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyVector, FALSE, _CMHIVE::FileHandles, _CMHIVE::FileObject, _CM_KEY_NODE::Flags, _HHIVE::Free, HFILE_TYPE_EXTERNAL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HSECTOR_SIZE, HvGetCell, HvMarkCellDirty(), HvpGrowLog2(), HvpWriteLog(), HvReleaseCell, HvWriteHive(), KEY_HIVE_ENTRY, KEY_NO_DELETE, _HHIVE::_DUAL::Length, _HHIVE::Log, NULL, _CM_KEY_NODE::Parent, _HBASE_BLOCK::RootCell, ROUND_UP, RtlClearAllBits(), RtlInitializeBitMap(), RtlSetAllBits(), RtlZeroMemory, _RTL_BITMAP::SizeOfBitMap, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_NO_MEMORY, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, _HHIVE::Storage, TRUE, and _HBASE_BLOCK::Type.
Referenced by CmCompressKey().
NTSTATUS CmpParseKey (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 334 of file cmparse.c.
References ARGUMENT_PRESENT, ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, Cell, CM_KCB_CACHE_MASK, CM_KCB_KEY_NON_EXIST, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_ONE, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_PARSE, CMP_CREATE_KCB_KCB_LOCKED, CMP_DO_OPEN_COMPLETE_KEY_CACHED, CMP_PARSE_GOTO_CREATE, CMP_PARSE_GOTO_NONE, CMP_PARSE_GOTO_RETURN, CMP_PARSE_GOTO_RETURN2, CmpAddInfoAfterParseFailure(), CmpBuildHashStackAndLookupCache(), CmpCallCallBacks(), CmpComputeHashKey(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDereferenceKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpDoCreate(), CmpDoOpen(), CmpFindSubKeyByName(), CmpGetNextName(), CmpGetSymbolicLink(), CmpHashTableSize, CmpKeyObjectType, CmpMasterHive, CmpNoMasterCreates, CmPostCallbackNotification, CmpParseGetOriginatingPoint, CmpParseRecordOriginatingPoint, CmpReferenceKeyControlBlock(), CmpReleasePreviousAndHookNew, CmpRemoveKeyControlBlock(), CmpStepThroughExit, CmpUnLockKcbArray(), CmpUnlockRegistry(), _REG_CREATE_KEY_INFORMATION::CompleteName, _CM_INDEX_HINT_BLOCK::Count, _CM_PARSE_CONTEXT::CreateLink, DBG, DbgBreakPoint(), _CM_KEY_CONTROL_BLOCK::Delete, _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, END_LOCK_CHECKPOINT, ExFreePool(), _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_CONTROL_BLOCK::Flags, _CM_INDEX_HINT_BLOCK::HashKey, _CM_KEY_CONTROL_BLOCK::HashKey, HCELL_NIL, Hive, _CMHIVE::Hive, HvGetCell, _CM_KEY_CONTROL_BLOCK::IndexHint, KEY_SYM_LINK, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, MAX_LOCAL_KCB_ARRAY, _UNICODE_STRING::MaximumLength, MAXUSHORT, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, REG_CREATED_NEW_KEY, RegNtPostCreateKeyEx, RegNtPostOpenKeyEx, RegNtPreCreateKeyEx, RegNtPreOpenKeyEx, _REG_CREATE_KEY_INFORMATION::RootObject, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NAME_TOO_LONG, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateObjectTypes().
NTSTATUS CmpPinCmView (IN PCMHIVE CmHive, PCM_VIEW_OF_FILE CmView)
Definition at line 1129 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, ASSERT_VIEW_MAPPED, _CM_VIEW_OF_FILE::Bcb, _UNICODE_STRING::Buffer, CcPinMappedData(), CM_PAGED_CODE, CmKdPrintEx, CML_BIN_MAP, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_VIEW_OF_FILE::FileOffset, _LARGE_INTEGER::HighPart, InitializeListHead(), InsertTailList(), _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, _CM_VIEW_OF_FILE::LRUViewList, NT_SUCCESS, _CM_VIEW_OF_FILE::PinViewList, RemoveEntryList(), RtlInitUnicodeString(), _CM_VIEW_OF_FILE::Size, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by HvMarkCellDirty(), HvMarkDirty(), HvpRecoverData(), and HvpRecoverWholeHive().
VOID CmpPostApc (struct _KAPC * Apc, PKNORMAL_ROUTINE * NormalRoutine, PVOID * NormalContext, PVOID * SystemArgument1, PVOID * SystemArgument2)
Definition at line 793 of file cmnotify.c.
References _CM_POST_BLOCK_UNION::AsyncUser, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpCheckIoStatusPointer, CmpCheckPostBlock, CmpFreePostBlock(), CmpFreeSlavePost(), CmpRemoveEntryList, CmpSetIoStatus, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, KeSetEvent(), NOTHING, NULL, ObDereferenceObject(), PsGetCurrentProcess(), _CM_POST_BLOCK::ThreadList, _CM_POST_BLOCK::u, UNREFERENCED_PARAMETER, and _CM_ASYNC_USER_POST_BLOCK::UserEvent.
Referenced by NtNotifyChangeMultipleKeys().
VOID CmpPostApcRunDown (struct _KAPC * Apc)
Definition at line 919 of file cmnotify.c.
References APC_LEVEL, _CM_POST_BLOCK_UNION::AsyncUser, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpCheckIoStatusPointer, CmpFreePostBlock(), CmpFreeSlavePost(), CmpRemoveEntryList, CmpSetIoStatus, DBG, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, KeLowerIrql, KeRaiseIrql, KeSetEvent(), NOTHING, NULL, ObDereferenceObject(), PsGetCurrentProcess(), STATUS_NOTIFY_CLEANUP, _KAPC::SystemArgument2, _CM_POST_BLOCK::ThreadList, _CM_POST_BLOCK::u, and _CM_ASYNC_USER_POST_BLOCK::UserEvent.
Referenced by NtNotifyChangeMultipleKeys().
VOID CmpPostNotify (PCM_NOTIFY_BLOCK NotifyBlock, PUNICODE_STRING Name OPTIONAL, ULONG Filter, NTSTATUS Status, BOOLEAN PostListLockHeld, PLIST_ENTRY ExternalKeyDeref OPTIONAL)
Definition at line 487 of file cmnotify.c.
References _CM_ASYNC_USER_POST_BLOCK::Apc, APC_LEVEL, ARGUMENT_PRESENT, ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_HIVE_LOCK_OWNED, _CM_POST_BLOCK_UNION::AsyncUser, _CM_POST_BLOCK::CancelPostList, ClearMasterPostBlockFlag, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpAddToDelayedDeref(), CmpCancelSlavePost(), CmpClearListEntry, CmpDelayedDerefKeys(), CmpFreePostBlock(), CmpRemoveEntryList, CONTAINING_RECORD, DPFLTR_CONFIG_ID, ExQueueWorkItem(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), IsListEmpty, IsMasterPostBlock, KeInsertQueueApc(), KeLowerIrql, KeRaiseIrql, KeSetEvent(), LOCK_POST_LIST, _CM_POST_BLOCK::NotifyList, _CM_NOTIFY_BLOCK::NotifyPending, _CM_POST_BLOCK::NotifyType, NULL, ObDereferenceObject(), PostAsyncKernel, PostAsyncUser, PostBlockType, _CM_NOTIFY_BLOCK::PostList, PostSynchronous, RemoveHeadList(), SetMasterPostBlockFlag, Status, _CM_SYNC_POST_BLOCK::Status, STATUS_NOTIFY_CLEANUP, _CM_POST_BLOCK_UNION::Sync, _CM_SYNC_POST_BLOCK::SystemEvent, _CM_POST_BLOCK::ThreadList, TRUE, _CM_POST_BLOCK::u, ULongToPtr, and UNLOCK_POST_LIST.
Referenced by CmpCloseKeyObject(), CmpFlushNotify(), CmpNotifyChangeKey(), and CmpReportNotifyHelper().
VOID CmpPrefetchHiveFile (IN PFILE_OBJECT FileObject, IN ULONG Length)
Definition at line 1620 of file cmmapvw.c.
References _FILE_SEGMENT_ELEMENT::Alignment, ASSERT, CM_PAGED_CODE, ExAllocatePoolWithTag, ExFreePool(), FALSE, _READ_LIST::FileObject, _READ_LIST::IsImage, _READ_LIST::List, MmPrefetchPages(), NonPagedPool, NULL, _READ_LIST::NumberOfEntries, PAGE_SIZE, and ROUND_UP.
Referenced by HvMapHive().
NTSTATUS CmpQueryKeyData (PHHIVE Hive, PCM_KEY_NODE Node, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
Definition at line 46 of file cmsubs2.c.
References ALIGN_OFFSET, _KEY_FULL_INFORMATION::Class, _CM_KEY_NODE::Class, _KEY_NODE_INFORMATION::ClassLength, _KEY_FULL_INFORMATION::ClassLength, _CM_KEY_NODE::ClassLength, _KEY_NODE_INFORMATION::ClassOffset, _KEY_FULL_INFORMATION::ClassOffset, CmpCopyCompressedName(), CmpHKeyNameLen, _CHILD_LIST::Count, FIELD_OFFSET, _CM_KEY_NODE::Flags, HvGetCell, HvReleaseCell, KEY_COMP_NAME, KeyBasicInformation, _KEY_INFORMATION::KeyBasicInformation, KeyFullInformation, _KEY_INFORMATION::KeyFullInformation, KeyNodeInformation, _KEY_INFORMATION::KeyNodeInformation, _KEY_BASIC_INFORMATION::LastWriteTime, _KEY_NODE_INFORMATION::LastWriteTime, _KEY_FULL_INFORMATION::LastWriteTime, _CM_KEY_NODE::LastWriteTime, _KEY_FULL_INFORMATION::MaxClassLen, _CM_KEY_NODE::MaxClassLen, _KEY_FULL_INFORMATION::MaxNameLen, _CM_KEY_NODE::MaxNameLen, _KEY_FULL_INFORMATION::MaxValueDataLen, _CM_KEY_NODE::MaxValueDataLen, _KEY_FULL_INFORMATION::MaxValueNameLen, _CM_KEY_NODE::MaxValueNameLen, _KEY_BASIC_INFORMATION::Name, _KEY_NODE_INFORMATION::Name, _CM_KEY_NODE::Name, _KEY_BASIC_INFORMATION::NameLength, _KEY_NODE_INFORMATION::NameLength, _CM_KEY_NODE::NameLength, NULL, RtlCopyMemory, Stable, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _KEY_FULL_INFORMATION::SubKeys, _KEY_BASIC_INFORMATION::TitleIndex, _KEY_NODE_INFORMATION::TitleIndex, _KEY_FULL_INFORMATION::TitleIndex, _CM_KEY_NODE::ValueList, _KEY_FULL_INFORMATION::Values, and Volatile.
Referenced by CmEnumerateKey(), and CmQueryKey().
NTSTATUS CmpQueryKeyDataFromCache (PCM_KEY_CONTROL_BLOCK Kcb, KEY_INFORMATION_CLASS KeyInformationClass, PVOID KeyInformation, ULONG Length, PULONG ResultLength)
Definition at line 355 of file cmsubs2.c.
References ASSERT, CM_KCB_INVALID_CACHED_INFO, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, CM_PAGED_CODE, CmKdPrintEx, CmpCompressedNameSize(), _CM_NAME_CONTROL_BLOCK::Compressed, _CM_INDEX_HINT_BLOCK::Count, _CACHED_CHILD_LIST::Count, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, _CM_KEY_CONTROL_BLOCK::ExtFlags, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::IndexHint, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueDataLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueNameLen, KeyCachedInformation, _KEY_INFORMATION::KeyCachedInformation, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _KEY_CACHED_INFORMATION::LastWriteTime, _KEY_CACHED_INFORMATION::MaxNameLen, _KEY_CACHED_INFORMATION::MaxValueDataLen, _KEY_CACHED_INFORMATION::MaxValueNameLen, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _KEY_CACHED_INFORMATION::NameLength, _CM_NAME_CONTROL_BLOCK::NameLength, NULL, Stable, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _CM_KEY_CONTROL_BLOCK::SubKeyCount, _CM_KEY_NODE::SubKeyCounts, _KEY_CACHED_INFORMATION::SubKeys, _KEY_CACHED_INFORMATION::TitleIndex, _CM_KEY_CONTROL_BLOCK::ValueCache, _KEY_CACHED_INFORMATION::Values, and Volatile.
Referenced by CmQueryKey().
NTSTATUS CmpQueryKeyName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 26 of file cmquery.c.
References ASSERT_KCB_LOCKED, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_PARSE, CmpConstructName(), CmpLockKCBShared, CmpLockRegistry(), CmpUnlockKCB, CmpUnlockRegistry(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, ExFreePoolWithTag, FALSE, _UNICODE_STRING::Length, NULL, PROTECTED_POOL, RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_SUCCESS, TRUE, UNICODE_NULL, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateObjectTypes().
VALUE_SEARCH_RETURN_TYPE CmpQueryKeyValueData (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PPCM_CACHED_VALUE ContainingList, PCM_KEY_VALUE ValueKey, BOOLEAN ValueCached, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength, NTSTATUS * status)
Definition at line 514 of file cmsubs2.c.
References ALIGN_OFFSET, ALIGN_OFFSET64, ASSERT, CM_KEY_VALUE_SMALL, CmKdPrintEx, CmpCopyCompressedName(), CmpGetValueDataFromCache(), CmpIsHKeyValueSmall, CmpValueNameLen, _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64::Data, _CM_KEY_VALUE::Data, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64::DataLength, _CM_KEY_VALUE::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, ExFreePool(), FALSE, FIELD_OFFSET, _CM_KEY_VALUE::Flags, HCELL_NIL, Hive, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyValue, KeyValueBasicInformation, _KEY_VALUE_INFORMATION::KeyValueBasicInformation, KeyValueFullInformation, _KEY_VALUE_INFORMATION::KeyValueFullInformation, KeyValueFullInformationAlign64, KeyValuePartialInformation, _KEY_VALUE_INFORMATION::KeyValuePartialInformation, KeyValuePartialInformationAlign64, _KEY_VALUE_INFORMATION::KeyValuePartialInformationAlign64, _KEY_VALUE_BASIC_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::Name, _CM_KEY_VALUE::Name, _KEY_VALUE_BASIC_INFORMATION::NameLength, _KEY_VALUE_FULL_INFORMATION::NameLength, _CM_KEY_VALUE::NameLength, NULL, RtlCopyMemory, SearchSuccess, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _KEY_VALUE_BASIC_INFORMATION::TitleIndex, _KEY_VALUE_FULL_INFORMATION::TitleIndex, _KEY_VALUE_PARTIAL_INFORMATION::TitleIndex, TRUE, _KEY_VALUE_BASIC_INFORMATION::Type, _KEY_VALUE_FULL_INFORMATION::Type, _KEY_VALUE_PARTIAL_INFORMATION::Type, _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64::Type, _CM_KEY_VALUE::Type, _CELL_DATA::u, and VALUE_COMP_NAME.
Referenced by CmEnumerateValueKey(), and CmQueryValueKey().
VOID CmpQuotaWarningWorker (IN PVOID WorkItem)
Definition at line 202 of file cmgquota.c.
References ExFreePool(), ExRaiseHardError(), NULL, OptionOk, Status, and STATUS_REGISTRY_QUOTA_LIMIT.
VOID CmpRaiseSelfHealWarning (IN PUNICODE_STRING HiveName)
Definition at line 757 of file cmgquota.c.
References _UNICODE_STRING::Buffer, CmpRaiseSelfHealWarningWorker(), CmpSelfHealWorkerActive, DelayedWorkQueue, ExAllocatePool, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), CM_SELF_HEAL_WORK_ITEM_PARAMETER::HiveName, InsertTailList(), _UNICODE_STRING::Length, LOCK_SELF_HEAL_QUEUE, _UNICODE_STRING::MaximumLength, NonPagedPool, NULL, PAGED_CODE, RtlCopyMemory, TRUE, UNLOCK_SELF_HEAL_QUEUE, and CM_SELF_HEAL_WORK_ITEM_PARAMETER::WorkItem.
Referenced by CmpInitHiveFromFile(), and CmpRaiseSelfHealWarningForSystemHives().
VOID CmpRaiseSelfHealWarningForSystemHives ()
Definition at line 819 of file cmgquota.c.
References CM_NUMBER_OF_MACHINE_HIVES, CmpRaiseSelfHealWarning(), HBOOT_SELFHEAL, HIVE_VOLATILE, PAGED_CODE, and RtlInitUnicodeString().
Referenced by NtInitializeRegistry().
VOID CmpRebuildKcbCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 1161 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_SYM_LINK_FOUND, CmpCleanUpKcbValueCache(), CmpCleanUpSubKeyInfo(), CmpSetUpKcbValueCache, _CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::ExtFlags, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueDataLen, _CM_KEY_CONTROL_BLOCK::KcbMaxValueNameLen, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NULL, and _CM_KEY_NODE::ValueList.
Referenced by CmMoveKey(), CmpCloneControlSet(), and CmpSaveBootControlSet().
BOOLEAN CmpRebuildSecurityCache (IN OUT PCMHIVE CmHive)
Definition at line 769 of file cmsecache.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, _CM_KEY_SECURITY::Blink, CmKdPrintEx, CML_SEC, CmpAddSecurityCellToCache(), CmpDumpSecurityDescriptor, CmpFindReusableCellFromCache(), CmpSecHashTableSize, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_SECURITY::Flink, Hive, HvGetCell, HvIsCellAllocated(), InitializeListHead(), NT_SUCCESS, NULL, PAGED_CODE, _CM_KEY_SECURITY::ReferenceCount, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, _CM_KEY_NODE::Security, SeValidSecurityDescriptor(), and TRUE.
Referenced by HvRefreshHive().
VOID CmpReferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1905 of file cmmapvw.c.
References ASSERT_VIEW_LOCK_OWNED, and CM_PAGED_CODE.
Referenced by CmpReferenceHiveViewWithLock(), HvpScanForFreeCellInViewWindow(), and HvWriteHive().
VOID CmpReferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1968 of file cmmapvw.c.
References CM_PAGED_CODE, CmLockHiveViews, CmpReferenceHiveView(), and CmUnlockHiveViews.
BOOLEAN CmpReferenceKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 914 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED, CmpDelayedCloseSize, CmpIsKCBLockedExclusive, CmpRemoveFromDelayedClose(), CmpTryConvertKCBLockSharedToExclusive(), CmpUpgradeKCBLockToExclusive, _CM_KEY_CONTROL_BLOCK::DelayedCloseIndex, FALSE, InterlockedDecrement, InterlockedIncrement, LogKCBReference, _CM_KEY_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmpCacheLookup(), CmpCreateKeyControlBlock(), CmpDoOpen(), CmpGetSymbolicLink(), CmpParseKey(), and CmUnloadKeyEx().
VOID CmpReleaseGlobalQuota (IN ULONG Size)
Definition at line 270 of file cmgquota.c.
References CM_BUGCHECK, CmpGlobalQuotaUsed, InterlockedExchangeAdd(), QUOTA_ERROR, and REGISTRY_ERROR.
Referenced by CmpAllocate(), CmpFree(), HvFreeHive(), and HvFreeHivePartial().
VOID CmpRemoveFromDelayedClose (IN PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 344 of file cmdelay.c.
References ASSERT, CM_PAGED_CODE, CmpDelayCloseFreeEntry, CmpDelayedCloseElements, CmpDelayedCloseSize, CmpIsKCBLockedExclusive, CmpRemoveEntryList, _CM_DELAYED_CLOSE_ENTRY::DelayedLRUList, FALSE, InterlockedCompareExchange(), InterlockedDecrement, LOCK_DELAY_CLOSE, NULL, TRUE, and UNLOCK_DELAY_CLOSE.
Referenced by CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpReferenceKeyControlBlock(), and CmpSearchKeyControlBlockTree().
VOID CmpRemoveFromHiveFileList (PUNICODE_STRING HiveName)
Definition at line 174 of file cmhvlist.c.
References HIVE_LIST, InitializeObjectAttributes, KEY_READ, KEY_WRITE, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, RtlInitUnicodeString(), Status, ZwDeleteValueKey(), and ZwOpenKey().
Referenced by CmUnloadKey().
VOID CmpRemoveFromSecurityCache (IN OUT PCMHIVE CmHive, IN HCELL_INDEX SecurityCell)
Definition at line 555 of file cmsecache.c.
References ASSERT, CmpFindSecurityCellCacheIndex(), CmpRemoveEntryList, ExFreePoolWithTag, FALSE, Index, PAGED_CODE, PROTECTED_POOL, and RtlMoveMemory.
Referenced by CmpRemoveSecurityCellList(), and CmpSetSecurityDescriptorInfo().
VOID CmpRemoveKeyControlBlock (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 2188 of file cmsubs.c.
References ASSERT_KCB, ASSERT_KCB_LOCKED_EXCLUSIVE, CmpRemoveKeyHash(), and _CM_KEY_CONTROL_BLOCK::KeyHash.
Referenced by CmDeleteKey(), CmpCacheLookup(), CmpCleanUpKcbCacheWithLock(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDoCreate(), CmpDoCreateChild(), CmpParseKey(), CmpSearchForOpenSubKeys(), and CmUnloadKey().
BOOLEAN CmpRemoveSubKey (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
Definition at line 2485 of file cmindex.c.
References ASSERT, ASSERT_CELL_DIRTY, _UNICODE_STRING::Buffer, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmpCompressedNameSize(), CmpCopyCompressedName(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvGetCellType, HvIsCellAllocated(), HvReleaseCell, INVALID_INDEX, KEY_COMP_NAME, _UNICODE_STRING::Length, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, PagedPool, RtlMoveMemory, _CM_KEY_INDEX::Signature, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpFreeKeyByCell(), and CmRenameKey().
BOOLEAN CmpRemoveSubKeyCellNoCellRef (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
Definition at line 1123 of file cmindex.c.
References ASSERT, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, FALSE, HvGetCell, HvMarkCellDirty(), HvReleaseCell, Index, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NULL, RtlMoveMemory, _CM_KEY_INDEX::Signature, Stable, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpCheckRegistry2().
NTSTATUS CmpRemoveValueFromList (IN PHHIVE Hive, IN ULONG Index, IN OUT PCHILD_LIST ChildList)
Definition at line 617 of file cmvalue.c.
References ASSERT, ASSERT_CELL_DIRTY, CM_PAGED_CODE, Count, HCELL_NIL, HvFreeCell(), HvGetCell, HvReallocateCell(), HvReleaseCell, Index, _CELL_DATA::_u::KeyList, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _CELL_DATA::u.
Referenced by CmDeleteValueKey().
VOID CmpReportNotify (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PHHIVE Hive, HCELL_INDEX Cell, ULONG NotifyMask)
Definition at line 152 of file cmnotify.c.
References ASSERT, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpReportNotifyHelper(), DPFLTR_CONFIG_ID, _CM_KEY_NODE::Flags, HCELL_NIL, _CMHIVE::Hive, HvGetCell, HvReleaseCell, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, NULL, _CM_KEY_NODE::Parent, _CM_KEY_CONTROL_BLOCK::ParentKcb, and REG_NOTIFY_CHANGE_NAME.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmpDoCreateChild(), CmpLinkHiveToMaster(), CmpSecurityMethod(), CmRestoreKey(), CmSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
BOOLEAN CmpResolveDriverDependencies (IN PLIST_ENTRY DriverListHead)
Definition at line 1246 of file cmboot.c.
References CmpOrderGroup(), CONTAINING_RECORD, _LIST_ENTRY::Flink, _BOOT_DRIVER_NODE::Group, RtlEqualUnicodeString(), and TRUE.
Referenced by CmGetSystemDriverList().
VOID CmpRunDownDelayDerefKCBEngine (PCM_KEY_CONTROL_BLOCK KeyControlBlock, BOOLEAN RegLockHeldEx)
Definition at line 599 of file cmdelay.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_PAGED_CODE, CmpClearListEntry, CmpDelayDerefKCBFreeEntry, CmpDereferenceKeyControlBlockWithLock(), CmpDoQueueLateUnloadWorker(), CmpHashTableSize, CmpIsKCBLockedExclusive, CmpIsListEmpty, CmpKCBLockForceAcquireAllowed(), CmpLockHashEntryByIndexExclusive, CmpTryToLockHashEntryByIndexExclusive(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_CONTROL_BLOCK::Delete, FALSE, GET_HASH_INDEX, Hive, InsertHeadList(), IsHiveFrozen, _CM_DELAY_DEREF_KCB_ITEM::Kcb, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_DELAY_DEREF_KCB_ITEM::ListEntry, LOCK_KCB_DELAY_DEREF_LIST, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, RemoveHeadList(), TRUE, and UNLOCK_KCB_DELAY_DEREF_LIST.
Referenced by CmpCleanUpKCBCacheTable(), and CmpFreeAllMemory().
NTSTATUS CmpSaveBootControlSet (IN USHORT ControlSetNum)
Referenced by NtInitializeRegistry().
ULONG CmpSearchForOpenSubKeys (IN PCM_KEY_CONTROL_BLOCK SearchKey, IN SUBKEY_SEARCH_TYPE SearchType, IN BOOLEAN RegLockHeldEx, IN OUT PVOID SearchContext OPTIONAL)
Referenced by CmRenameKey(), CmRestoreKey(), CmUnloadKey(), CmUnloadKeyEx(), NtQueryOpenSubKeys(), and NtQueryOpenSubKeysEx().
BOOLEAN CmpSearchKeyControlBlockTree (PKCB_WORKER_ROUTINE WorkerRoutine, PVOID Context1, PVOID Context2)
Definition at line 2004 of file cmsubs.c.
References ASSERT, ASSERT_KCB, CmpCleanUpKcbCacheWithLock(), CmpHashTableSize, CmpLockHashEntryByIndexExclusive, CmpRemoveFromDelayedClose(), CmpUnlockHashEntryByIndex, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_HASH_TABLE_ENTRY::Entry, FALSE, KCB_WORKER_CONTINUE, KCB_WORKER_DELETE, KCB_WORKER_DONE, KCB_WORKER_ERROR, _CM_KEY_CONTROL_BLOCK::NextHash, _CM_KEY_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmCompressKey(), CmpRefreshHive(), and CmUnloadKey().
ULONG CmpSecConvKey (IN ULONG DescriptorLength, IN PULONG Descriptor)
Definition at line 55 of file cmsecache.c.
References Count, and PAGED_CODE.
Referenced by CmpAddSecurityCellToCache(), CmpFindMatchingDescriptorCell(), and CmpSetSecurityDescriptorInfo().
NTSTATUS CmpSecurityMethod (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 206 of file cmse.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KEY_OBJECT, AssignSecurityDescriptor, BAD_SECURITY_METHOD, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CmLockHiveSecurityExclusive, CmpAssignSecurityDescriptorWrapper(), CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpQuerySecurityDescriptorInfo(), CmpReportNotify(), CmpSecurityExceptionFilter(), CmpSetSecurityDescriptorInfo(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CmUnlockHiveSecurity, _CM_KEY_CONTROL_BLOCK::Delete, DeleteSecurityDescriptor, DPFLTR_CONFIG_ID, except, FALSE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NonPagedPool, NT_SUCCESS, NULL, PagedPool, QuerySecurityDescriptor, REG_NOTIFY_CHANGE_ATTRIBUTES, REG_NOTIFY_CHANGE_SECURITY, REGISTRY_ERROR, SetSecurityDescriptor, Status, STATUS_KEY_DELETED, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by CmpCreateObjectTypes().
VOID CmpSetCurrentProfile (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PCM_HARDWARE_PROFILE Profile)
Definition at line 1751 of file cmboot.c.
References ASSERT, CmpFindProfileOption(), CmpFindValueByName(), CmpValueToData(), HCELL_NIL, HvGetCell, NULL, REG_DWORD, RtlInitUnicodeString(), and _CM_KEY_VALUE::Type.
VOID CmpSetGlobalQuotaAllowed (VOID)
Definition at line 359 of file cmgquota.c.
References CmpGlobalQuota, and CmpGlobalQuotaAllowed.
Referenced by CmLoadKey(), CmpLoadHiveVolatile(), and CmRestoreKey().
NTSTATUS CmpSetValueDataExisting (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX OldDataCell)
Definition at line 1271 of file cmvalue.c.
References ASSERT, ASSERT_BIG_DATA, CM_KEY_VALUE_BIG, CM_PAGED_CODE, Count, _CM_BIG_DATA::Count, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvReallocateCell(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CM_BIG_DATA::List, NULL, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by CmpSetValueKeyExisting().
NTSTATUS CmpSetValueDataNew (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX ValueCell, OUT PHCELL_INDEX DataCell)
Definition at line 1012 of file cmvalue.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, CM_BIG_DATA_SIGNATURE, CM_KEY_VALUE_BIG, CM_KEY_VALUE_SMALL, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CmpIsHKeyValueBig, Count, _CM_BIG_DATA::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CM_BIG_DATA::List, NULL, RtlCopyMemory, _CM_BIG_DATA::Signature, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by CmpCopyValue(), CmpSetValueKeyExisting(), and CmpSetValueKeyNew().
VOID CmpSetVersionData (VOID)
Referenced by NtInitializeRegistry().
NTSTATUS CmpShiftHiveFreeBins (PCMHIVE CmHive, PCMHIVE * NewHive)
Definition at line 2130 of file cmsavres.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, CM_PAGED_CODE, CmpCreateTemporaryHive(), CmpDestroyTemporaryHive(), CmpShiftAllCells(), _HHIVE::DirtyCount, _CMHIVE::FileHandles, _HHIVE::_DUAL::FreeBins, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvCloneHive(), HvShiftCell(), HvShrinkHive(), HvSyncHive(), IsListEmpty, _HBASE_BLOCK::Minor, NT_SUCCESS, NULL, _HBASE_BLOCK::RootCell, Stable, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _HHIVE::Storage, and _HHIVE::Version.
Referenced by CmCompressKey().
VOID CmpShutdownWorkers (VOID)
Definition at line 740 of file cmworker.c.
References CM_PAGED_CODE, and KeCancelTimer().
Referenced by CmShutdownSystem().
BOOLEAN CmpSortDriverList (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PLIST_ENTRY DriverListHead)
Definition at line 1029 of file cmboot.c.
References ASSERT, _UNICODE_STRING::Buffer, CmpDoSort(), CmpFindSubKeyByName(), CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, REG_MULTI_SZ, RtlInitUnicodeString(), and _CM_KEY_VALUE::Type.
Referenced by CmGetSystemDriverList().
VOID CmpSwitchStorageAndRebuildMappings (PCMHIVE OldCmHive, PCMHIVE NewHive)
Definition at line 1963 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, _CM_KEY_SECURITY_CACHE_ENTRY::CachedSecurity, _CM_KEY_SECURITY_CACHE::Cell, _CM_KEY_SECURITY_CACHE_ENTRY::Cell, _CMHIVE::CellRemapArray, CM_KCB_KEY_NON_EXIST, CM_KCB_SYM_LINK_FOUND, CM_PAGED_CODE, CmpCleanUpKcbValueCache(), CmpSetUpKcbValueCache, CONTAINING_RECORD, _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyVector, _CM_KEY_CONTROL_BLOCK::ExtFlags, _CM_KEY_CONTROL_BLOCK::Flags, _LIST_ENTRY::Flink, _HHIVE::_DUAL::FreeBins, HCELL_NIL, _CMHIVE::Hive, HvGetCellType, InsertTailList(), IsListEmpty, _CMHIVE::KcbConvertListHead, KEY_PREDEF_HANDLE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KCB_REMAP_BLOCK::KeyControlBlock, _CM_KNODE_REMAP_BLOCK::KeyNode, _CMHIVE::KnodeConvertListHead, _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, _HHIVE::LogSize, _CMHIVE::LRUViewListHead, _HHIVE::_DUAL::Map, _CMHIVE::MappedViews, _CM_CELL_REMAP_BLOCK::NewCell, _CM_KCB_REMAP_BLOCK::NewCellIndex, _CM_KNODE_REMAP_BLOCK::NewParent, NULL, _CM_CELL_REMAP_BLOCK::OldCell, _CM_KCB_REMAP_BLOCK::OldCellIndex, _CM_KEY_NODE::Parent, _CMHIVE::PinnedViews, _CMHIVE::PinViewListHead, _CM_KCB_REMAP_BLOCK::RemapList, _CM_KNODE_REMAP_BLOCK::RemapList, RemoveHeadList(), _HBASE_BLOCK::RootCell, RtlCopyMemory, _CMHIVE::SecurityCache, _CMHIVE::SecurityCount, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HHIVE::_DUAL::SmallDir, Stable, _HHIVE::Storage, _CMHIVE::UseCount, _CM_KCB_REMAP_BLOCK::ValueCount, and _CM_KCB_REMAP_BLOCK::ValueList.
Referenced by CmCompressKey().
VOID CmpSystemQuotaWarningWorker (IN PVOID WorkItem)
Definition at line 447 of file cmgquota.c.
References ExFreePool(), ExRaiseHardError(), NULL, OptionOk, Status, and STATUS_REGISTRY_QUOTA_LIMIT.
Referenced by CmpCanGrowSystemHive().
VOID CmpTouchView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN ULONG Cell)
Definition at line 212 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_BIN_MAP, DPFLTR_CONFIG_ID, FALSE, InsertHeadList(), IsListEmpty, _UNICODE_STRING::Length, RemoveEntryList(), RtlInitUnicodeString(), and UNREFERENCED_PARAMETER.
Referenced by CmpMapThisBin(), HvpGetCellMapped(), HvpMapFileImageAndBuildMap(), and HvRefreshHive().
BOOLEAN CmpTryConvertKCBLockSharedToExclusive (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 203 of file cmsubs3.c.
References ASSERT, ASSERT_KCB_LOCKED, CmpIsKCBLockedExclusive, ExTryConvertPushLockSharedToExclusive(), FALSE, GET_KCB_HASH_ENTRY_LOCK, GET_KCB_HASH_ENTRY_OWNER, and KeGetCurrentThread().
Referenced by CmEnumerateValueKey(), CmpCompareNewValueDataAgainstKCBCache(), CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpReferenceKeyControlBlock(), CmQueryValueKey(), and CmSetValueKey().
BOOLEAN CmpTryToLockHashEntryByIndexExclusive (ULONG Index)
Definition at line 232 of file cmsubs3.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, CmpCacheTable, ExTryAcquirePushLockExclusive(), Index, KeGetCurrentThread(), NULL, and _CM_KEY_HASH_TABLE_ENTRY::Owner.
Referenced by CmpCleanUpKCBCacheTable(), CmpRunDownDelayDerefKCBEngine(), and CmpSearchForOpenSubKeys().
VOID CmpUnlockRegistry ()
Definition at line 149 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmpDoFlushAll(), CmpFlushOnLockRelease, ExIsResourceAcquiredExclusiveLite(), ExReleaseResourceLite(), FALSE, KeLeaveCriticalRegion(), _OWNER_ENTRY::OwnerCount, _ERESOURCE::OwnerThreads, and TRUE.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmGetSystemDriverList(), CmInitSystem1(), CmLoadKey(), CmNotifyRunDown(), CmpCloneControlSet(), CmpCloseKeyObject(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpLateUnloadHiveWorker(), CmpLazyFlushWorker(), CmpLoadHiveVolatile(), CmpParseKey(), CmpQueryKeyName(), CmPrefetchHivePages(), CmpRefreshHive(), CmpSaveBootControlSet(), CmpSaveKeyByFileCopy(), CmpSecurityMethod(), CmpWmiDumpKcbTable(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRestoreKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), CmShutdownSystem(), CmUnloadKey(), NtCompactKeys(), NtCompressKey(), NtFlushKey(), NtInitializeRegistry(), NtLockRegistryKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtRenameKey(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpUnlockTwoHashEntries (ULONG ConvKey1, ULONG ConvKey2)
Definition at line 355 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, ASSERT_HASH_ENTRY_LOCKED, CmpUnlockHashEntry, and GET_HASH_INDEX.
Referenced by CmDeleteKey(), CmpCreateKeyControlBlock(), CmpGetSymbolicLink(), CmSaveMergedKeys(), CmUnloadKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), and NtUnloadKey2().
VOID CmpUnPinCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN SetClean, IN BOOLEAN MapIsValid)
Definition at line 1251 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_PINNED, _LIST_ENTRY::Blink, CcFlushCache(), CcMapData(), CcPurgeCacheSection(), CcSetDirtyPinnedData(), CcUnpinData(), CM_PAGED_CODE, CmKdPrintEx, CmLockHiveViews, CmMaxViewsPerHive, CmpFreeCmView(), CmpUnmapCmView(), CmUnlockHiveViews, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FileOffset, _LARGE_INTEGER::HighPart, InitializeListHead(), InsertHeadList(), InsertTailList(), _LARGE_INTEGER::LowPart, MAP_NO_READ, MAP_WAIT, NT_SUCCESS, NULL, RemoveEntryList(), Status, STATUS_CANT_WAIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by HvpFlushMappedData().
BOOLEAN CmpUpdateParentForEachSon (PHHIVE Hive, HCELL_INDEX Parent)
Definition at line 2887 of file cmindex.c.
References ASSERT, ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CM_PAGED_CODE, CmpFindSubKeyByNumber(), Count, FALSE, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, NULL, _CM_KEY_NODE::Parent, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmMoveKey(), and CmRenameKey().
VOID CmpUpdateSystemHiveHysteresis (PHHIVE Hive, ULONG NewLength, ULONG OldLength)
Definition at line 530 of file cmgquota.c.
References ASSERT, CM_SYSTEM_HIVE_LIMIT_SIZE, _HIVE_LIST_ENTRY::CmHive, CmpSystemHiveHysteresisCallback, CmpSystemHiveHysteresisHigh, CmpSystemHiveHysteresisHighSeen, CmpSystemHiveHysteresisHitRatio, CmpSystemHiveHysteresisLow, CmpSystemHiveHysteresisLowSeen, CmpSystemHiveHysteresisWorker(), CONTAINING_RECORD, DelayedWorkQueue, ExAllocatePool, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, HBLOCK_SIZE, NonPagedPool, NULL, PAGED_CODE, SYSTEM_HIVE_INDEX, and TRUE.
Referenced by CmCompressKey(), HvFreeHivePartial(), and HvpAddBin().
BOOLEAN CmpValidateHiveSecurityDescriptors (IN PHHIVE Hive, OUT PBOOLEAN ResetSD)
Definition at line 28 of file cmchek2.c.
References ASSERT, _CM_KEY_SECURITY::Blink, CmDoSelfHeal, CmKdPrintEx, CML_SEC, CmMarkSelfHeal, CmpAddSecurityCellToCache(), CmpAdjustSecurityCacheSize(), CmpDestroySecurityCache(), CmpDumpSecurityDescriptor, CmpFindSecurityCellCacheIndex(), CmpInitSecurityCache(), _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_SECURITY::Flink, HvGetCell, HvIsCellAllocated(), HvMarkCellDirty(), Index, NT_SUCCESS, NULL, _CM_KEY_SECURITY::ReferenceCount, _CM_KEY_NODE::Security, SeValidSecurityDescriptor(), and TRUE.
Referenced by CmCheckRegistry().
BOOLEAN CmpValidateSelect (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell)
Definition at line 1406 of file cmboot.c.
References ASSERT, CmpFindSubKeyByName(), CmpFindValueByName(), FALSE, HCELL_NIL, HvGetCell, NULL, RtlInitUnicodeString(), and TRUE.
PCELL_DATA CmpValueToData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize)
Definition at line 420 of file cmvalue.c.
References ASSERT, BIG_CELL_ERROR, CM_BUGCHECK, CM_PAGED_CODE, CmpGetValueData(), ExFreePool(), FALSE, NULL, REGISTRY_ERROR, and TRUE.
Referenced by CmpAddDriverToList(), CmpFindControlSet(), CmpFindNLSData(), CmpFindProfileOption(), CmpFindTagIndex(), CmpIsLoadType(), CmpSetCurrentProfile(), and CmpSortDriverList().
VOID CmpWmiDumpKcb (PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 118 of file cmwmi.c.
References CM_PAGED_CODE, CmpConstructName(), CmpTraceRoutine, ExFreePoolWithTag, KeyName, NULL, PROTECTED_POOL, and STATUS_SUCCESS.
NTSTATUS CmQueryKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 922 of file cmapi.c.
References _UNICODE_STRING::Buffer, CmKdPrintEx, CML_CM, CmpConstructName(), CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyData(), CmpQueryKeyDataFromCache(), CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, ExFreePoolWithTag, FIELD_OFFSET, HvGetCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), KEY_USER_FLAGS_SHIFT, KeyCachedInformation, KeyFlagsInformation, _KEY_INFORMATION::KeyFlagsInformation, KeyNameInformation, _KEY_INFORMATION::KeyNameInformation, _UNICODE_STRING::Length, _KEY_NAME_INFORMATION::Name, _KEY_NAME_INFORMATION::NameLength, NULL, PERFINFO_REG_QUERY_KEY, PROTECTED_POOL, RtlCopyMemory, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and _KEY_FLAGS_INFORMATION::UserFlags.
Referenced by NtQueryKey().
NTSTATUS CmQueryMultipleValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PKEY_VALUE_ENTRY ValueEntries, IN ULONG EntryCount, IN PVOID ValueBuffer, IN OUT PULONG BufferLength, IN OPTIONAL PULONG ResultLength)
Definition at line 1306 of file cmapi.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_CM, CmpFindValueByName(), CmpGetValueData(), CmpIsHKeyValueSmall, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpUnlockKCB, CmpUnlockRegistry(), _CM_KEY_VALUE::DataLength, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, KeGetPreviousMode, _UNICODE_STRING::Length, NT_SUCCESS, NULL, PAGED_CODE, PERFINFO_REG_QUERY_MULTIVALUE, ProbeAndReadUnicodeStringEx, ProbeForRead, RtlCopyMemory, Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, _CM_KEY_VALUE::Type, and UserMode.
Referenced by NtQueryMultipleValueKey().
NTSTATUS CmQueryValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 1127 of file cmapi.c.
References ASSERT, CM_KCB_SYM_LINK_FOUND, CM_PAGED_CODE, CmKdPrintEx, CML_CM, CML_EXCEPTION, CmpCleanUpKcbValueCache(), CmpFindValueByNameFromCache(), CmpIsKCBLockedExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyValueData(), CmpSetUpKcbValueCache, CmpTryConvertKCBLockSharedToExclusive(), CmpUnlockKCB, CmpUnlockRegistry(), CmpUpgradeKCBLockToExclusive, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, HvGetCell, HvReleaseCell, Index, _CHILD_LIST::List, NULL, PERFINFO_REG_QUERY_VALUE, SearchNeedExclusiveLock, SearchSuccess, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_OBJECT_NAME_NOT_FOUND, and _CM_KEY_NODE::ValueList.
Referenced by NtQueryValueKey().
NTSTATUS CmRenameKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING NewKeyName, IN KPROCESSOR_MODE PreviousMode)
Definition at line 3540 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmKdPrintEx, CML_CM, CML_EXCEPTION, CMP_KCB_REAL_NAME_UPCASE, CmpAddSubKey(), CmpCheckKeyAccess(), CmpCleanUpSubKeyInfo(), CmpComputeKcbConvKey(), CmpCopyName(), CmpDereferenceNameControlBlockWithLock(), CmpDoAccessCheckOnSubtree(), CmpDuplicateIndex(), CmpFindSubKeyByName(), CmpGetNameControlBlock(), CmpHKeyNodeSize, CmpInsertKeyHash(), CmpMarkIndexDirty(), CmpMasterHive, CmpRemoveKeyHash(), CmpRemoveSubKey(), CmpSearchForOpenSubKeys(), CmpUpdateParentForEachSon(), _CM_KEY_INDEX::Count, DELETE, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, ExFreePoolWithTag, FALSE, FIELD_OFFSET, _CM_KEY_NODE::Flags, HCELL_NIL, Hive, _CMHIVE::Hive, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, Index, KeQuerySystemTime(), KEY_COMP_NAME, KEY_CREATE_SUB_KEY, _CM_KEY_NODE::LastWriteTime, _CM_KEY_INDEX::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, RtlCopyMemory, SearchAndRehash, _CM_KEY_INDEX::Signature, Status, STATUS_ACCESS_DENIED, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by NtRenameKey().
NTSTATUS CmRenameValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING SourceValueName, IN UNICODE_STRING TargetValueName, IN ULONG TargetIndex)
NTSTATUS CmReplaceKey (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PUNICODE_STRING NewHiveName, IN PUNICODE_STRING OldFileName)
Referenced by NtReplaceKey().
NTSTATUS CmRestoreKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG Flags)
Definition at line 138 of file cmsavres.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, Cell, _CM_INDEX::Cell, _CM_KEY_NODE::ChildHiveReference, CM_CHECK_REGISTRY_CHECK_CLEAN, CM_KCB_INVALID_CACHED_INFO, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, CmKdPrintEx, CML_SAVRES, CmpAssignSecurityToKcb(), CmpCleanUpKcbValueCache(), CmpCleanUpSubKeyInfo(), CmpCopyKeyPartial(), CmpCopyTree, CmpDeleteTree(), CmpDestroyTemporaryHive(), CmpFreeKeyByCell(), CmpInitializeHive(), CmpLoadHiveVolatile(), CmpLockRegistryExclusive(), CmpProfileLoaded, CmpRefreshHive(), CmpReportNotify(), CmpSearchForOpenSubKeys(), CmpSetGlobalQuotaAllowed(), CmpSetUpKcbValueCache, CmpUnlockRegistry(), CONTAINING_RECORD, _CHILD_LIST::Count, _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, DCmCheckRegistry, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _CM_KEY_NODE::Flags, HCELL_NIL, HFILE_TYPE_PRIMARY, HINIT_FILE, Hive, _CMHIVE::Hive, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReallocateCell(), HvReleaseCell, IsHiveFrozen, KEY_COMP_NAME, KEY_HIVE_ENTRY, _CM_KEY_REFERENCE::KeyCell, _CELL_DATA::_u::KeyIndex, _CELL_DATA::_u::KeyNode, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, REG_FORCE_RESTORE, REG_NOTIFY_CHANGE_NAME, REG_REFRESH_HIVE, REG_WHOLE_HIVE_VOLATILE, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, RtlCopyMemory, SearchAndDeref, SearchIfExist, _CM_KEY_NODE::Security, _CM_KEY_INDEX::Signature, STATUS_ACCESS_DENIED, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, STATUS_TOO_LATE, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CELL_DATA::u, and _CM_KEY_NODE::ValueList.
Referenced by NtRestoreKey().
NTSTATUS CmSaveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN HANDLE FileHandle, IN ULONG HiveVersion)
Definition at line 1164 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_SAVRES, CmpCopyKeyPartial(), CmpCopyTree, CmpCreateTemporaryHive(), CmpDestroyTemporaryHive(), CmpLockHiveFlusherExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpLockRegistryExclusive(), CmpSaveKeyByFileCopy(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CONTAINING_RECORD, DCmCheckRegistry, _HHIVE::DirtyCount, DPFLTR_CONFIG_ID, ENTER_FLUSH_MODE, EXIT_FLUSH_MODE, FALSE, _CMHIVE::FileHandles, HCELL_NIL, HFILE_TYPE_EXTERNAL, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvWriteHive(), _HBASE_BLOCK::Minor, NULL, _HBASE_BLOCK::RootCell, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, TRUE, and _HHIVE::Version.
Referenced by NtSaveKey(), and NtSaveKeyEx().
NTSTATUS CmSaveMergedKeys (IN PCM_KEY_CONTROL_BLOCK HighPrecedenceKcb, IN PCM_KEY_CONTROL_BLOCK LowPrecedenceKcb, IN HANDLE FileHandle)
Definition at line 1356 of file cmsavres.c.
References ASSERT, _HHIVE::BaseBlock, CM_PAGED_CODE, CM_SAVE_MERGED_HIGH_HIVE, CM_SAVE_MERGED_LOW_HIVE, CM_SAVE_MERGED_TMP_HIVE, CmKdPrintEx, CML_SAVRES, CmpCopyKeyPartial(), CmpCopyTree, CmpCreateTemporaryHive(), CmpDestroyTemporaryHive(), CmpLockHiveFlusherExclusive, CmpLockRegistry(), CmpLockTwoHashEntriesShared(), CmpMergeKeyValues(), CmpMergeTrees, CmpUnlockHiveFlusher, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CONTAINING_RECORD, DCmCheckRegistry, _HHIVE::DirtyCount, DPFLTR_CONFIG_ID, ENTER_FLUSH_MODE, EXIT_FLUSH_MODE, FALSE, _CMHIVE::FileHandles, HCELL_NIL, HFILE_TYPE_EXTERNAL, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvGetCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), HvWriteHive(), NULL, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, and TRUE.
Referenced by NtSaveMergedKeys().
NTSTATUS CmSetAcpiHwProfile (IN PPROFILE_ACPI_DOCKING_STATE DockState, IN PCM_ACPI_SELECTION_ROUTINE, IN PVOID Context, OUT PHANDLE NewProfile, OUT PBOOLEAN ProfileChanged)
Referenced by CmpCreateControlSet().
NTSTATUS CmSetKeyUserFlags (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG UserFlags)
Definition at line 2452 of file cmapi.c.
References Cell, CmKdPrintEx, CML_CM, CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockRegistry(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, Hive, HvGetCell, HvMarkCellDirty(), HvReleaseCell, KeQuerySystemTime(), KEY_USER_FLAGS_CLEAR_MASK, KEY_USER_FLAGS_SHIFT, KEY_USER_FLAGS_VALID_MASK, _CM_KEY_NODE::LastWriteTime, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationKey().
NTSTATUS CmSetLastWriteTimeKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PLARGE_INTEGER LastWriteTime)
Definition at line 2370 of file cmapi.c.
References Cell, CmKdPrintEx, CML_CM, CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockRegistry(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, FALSE, Hive, HvGetCell, HvMarkCellDirty(), HvReleaseCell, _CM_KEY_NODE::LastWriteTime, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationKey().
NTSTATUS CmSetValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING ValueName, IN ULONG Type, IN PVOID Data, IN ULONG DataSize)
Definition at line 1505 of file cmapi.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, Cell, CM_KEY_VALUE_SMALL, CmKdPrintEx, CML_CM, CML_EXCEPTION, CMP_GET_CACHED_ADDRESS, CMP_GET_CACHED_CELLDATA, CMP_IS_CELL_CACHED, CmpCleanUpKcbValueCache(), CmpCompareNewValueDataAgainstKCBCache(), CmpFindNameInList(), CmpIsKCBLockedExclusive, CmpLockHiveFlusherShared, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpReportNotify(), CmpSetUpKcbValueCache, CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpTryConvertKCBLockSharedToExclusive(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CmpUpgradeKCBLockToExclusive, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, HCELL_NIL, Hive, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, KeQuerySystemTime(), KEY_SYM_LINK, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PERFINFO_REG_SET_VALUE, PERFINFO_REG_SET_VALUE_DECL, PERFINFO_REG_SET_VALUE_DONE, PERFINFO_REG_SET_VALUE_EXIST, PERFINFO_REG_SET_VALUE_NEW, REG_LINK, REG_NOTIFY_CHANGE_LAST_SET, RtlCopyMemory, RtlEqualUnicodeString(), SearchNeedExclusiveLock, SearchSuccess, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, TRUE, and _CM_KEY_NODE::ValueList.
Referenced by NtSetValueKey().
NTSTATUS CmUnloadKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN ULONG Flags, IN ULONG ControlFlags)
Definition at line 2930 of file cmapi.c.
References ASSERT, _HHIVE::BaseBlock, Cell, CM_UNLOAD_KCB_LOCKED, CM_UNLOAD_REG_LOCKED_EX, CmFlushKey(), CmKdPrintEx, CML_CM, CmpCleanUpSubKeyInfo(), CmpCmdHiveClose(), CmpDestroyHive(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFlushNotifiesOnKeyBodyList(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpGetHiveName(), CmpIsKCBLockedExclusive, CmpLockTwoHashEntriesExclusive(), CmpMasterHive, CmpRemoveFromHiveFileList(), CmpRemoveKeyControlBlock(), CmpSearchForOpenSubKeys(), CmpSearchKeyControlBlockTree(), CmpUnJoinClassOfTrust, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _CMHIVE::FlusherLock, Hive, HIVE_IS_UNLOADING, _HHIVE::HiveFlags, HvFreeHive(), InterlockedCompareExchangePointer, KeEnterCriticalRegion(), KeLeaveCriticalRegion(), KeSetEvent(), NULL, ObDereferenceObject(), REG_FORCE_UNLOAD, _HBASE_BLOCK::RootCell, RtlFreeUnicodeString(), SearchAndDeref, SearchIfExist, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_TOO_LATE, TRUE, _CMHIVE::UnloadEvent, _CMHIVE::UnloadWorkItem, UNLOCK_HIVE_LOAD, and _CMHIVE::ViewLock.
Referenced by CmpLateUnloadHiveWorker(), CmUnloadKeyEx(), and NtUnloadKey2().
NTSTATUS CmUnloadKeyEx (IN PCM_KEY_CONTROL_BLOCK Kcb, IN PKEVENT UserEvent)
Definition at line 3144 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, Cell, CM_KCB_NO_DELAY_CLOSE, CM_PAGED_CODE, CM_UNLOAD_REG_LOCKED_EX, CmpReferenceKeyControlBlock(), CmpSearchForOpenSubKeys(), CmUnloadKey(), CONTAINING_RECORD, _CMHIVE::Frozen, Hive, IsHiveFrozen, NULL, _CMHIVE::RootKcb, SearchAndTagNoDelayClose, Status, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_TOO_LATE, TRUE, and _CMHIVE::UnloadEvent.
Referenced by NtUnloadKeyEx().
VOID DelistKeyBodyFromKCB (IN PCM_KEY_BODY KeyBody, IN BOOLEAN LockHeld)
Definition at line 2514 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CMP_FAST_KEY_BODY_ARRAY_DUMP, CMP_FAST_KEY_BODY_ARRAY_FLUSH, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpLockKCBExclusive, CmpUnlockKCB, FALSE, InterlockedCompareExchangePointer, IsListEmpty, NULL, and RemoveEntryList().
Referenced by CmpDeleteKeyObject().
VOID EnlistKeyBodyWithKCB (IN PCM_KEY_BODY KeyBody, IN ULONG ControlFlags)
Definition at line 2472 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, CMP_ENLIST_KCB_LOCKED_EXCLUSIVE, CMP_ENLIST_KCB_LOCKED_SHARED, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpLockKCBExclusive, CmpSetNoCallers, CmpUnlockKCB, InitializeListHead(), InsertTailList(), InterlockedCompareExchangePointer, and NULL.
Referenced by CmpCreateRegistryRoot(), CmpDoCreateChild(), and CmpDoOpen().
VOID InitializeKCBKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 2462 of file cmsubs.c.
References CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, InitializeListHead(), and NULL.
Referenced by CmpCreateKeyControlBlock().
Variable Documentation
ULONG CmpBootType
Definition at line 381 of file cmdat.c.
Referenced by CmpInitializeSystemHive().
const ULONG CmpCacheOnFlag
Definition at line 25 of file cmparse.c.
Referenced by CmpAddInfoAfterParseFailure().
PCM_KEY_HASH_TABLE_ENTRY CmpCacheTable
Definition at line 26 of file cmsubs.c.
Referenced by CmpCacheLookup(), CmpFreeAllMemory(), CmpGetSymbolicLink(), CmpTryToLockHashEntryByIndexExclusive(), and CmpWmiDumpKcbTable().
ULONG CmpCallBackCount
Definition at line 44 of file cmhook.c.
Referenced by CmpInitCallback(), CmRegisterCallback(), and CmUnRegisterCallback().
LONG CmpFlushStarveWriters
Definition at line 55 of file cmsubs3.c.
Referenced by CmpLockRegistry(), and CmpLockRegistryExclusive().
ULONG CmpHashTableSize
Definition at line 28 of file cmsubs.c.
Referenced by CmpCacheLookup(), CmpCleanUpKCBCacheTable(), CmpDoOpen(), CmpFreeAllMemory(), CmpInitializeCache(), CmpKCBLockForceAcquireAllowed(), CmpParseKey(), CmpRunDownDelayDerefKCBEngine(), CmpSearchForOpenSubKeys(), CmpSearchKeyControlBlockTree(), and CmpWmiDumpKcbTable().
LIST_ENTRY CmpHiveListHead
Definition at line 312 of file cmdat.c.
EX_PUSH_LOCK CmpHiveListHeadLock
Definition at line 313 of file cmdat.c.
Referenced by CmInitSystem1().
POBJECT_TYPE CmpKeyObjectType
Definition at line 320 of file cmdat.c.
EX_PUSH_LOCK CmpLoadHiveLock
Definition at line 314 of file cmdat.c.
Referenced by CmInitSystem1().
PCMHIVE CmpMasterHive
Definition at line 305 of file cmdat.c.
BOOLEAN CmpMiniNTBoot
Definition at line 369 of file cmdat.c.
Referenced by CmInitSystem1(), CmpCmdInit(), CmpCreatePredefined(), CmpLoadHiveThread(), CmpOpenHiveFiles(), and HvSyncHive().
PCM_NAME_HASH_TABLE_ENTRY CmpNameCacheTable
Definition at line 27 of file cmsubs.c.
Referenced by CmpFreeAllMemory().
EX_PUSH_LOCK CmpPostLock
Definition at line 24 of file cmsubs.c.
ERESOURCE CmpRegistryLock
Definition at line 52 of file cmsubs3.c.
Referenced by CmpDoFileSetSize().
HANDLE CmpRegistryRootHandle
Definition at line 76 of file cmdat2.c.
Referenced by CmpCreateRegistryRoot(), and CmShutdownSystem().
BOOLEAN CmpSelfHeal
Definition at line 386 of file cmdat.c.
Referenced by CmpInitializeSystemHive().
BOOLEAN CmpShareSystemHives
Definition at line 376 of file cmdat.c.
Referenced by CmInitSystem1(), CmpCmdInit(), CmpInitHiveFromFile(), CmpInitializeHive(), CmpInitializeHiveList(), CmpInitializeSystemHive(), CmpLoadHiveThread(), and CmpOpenHiveFiles().
BOOLEAN CmpSpecialBootCondition
Definition at line 347 of file cmdat.c.
EX_PUSH_LOCK CmpStashBufferLock
Definition at line 66 of file cmdat2.c.
Referenced by CmInitSystem1().
PCM_TRACE_NOTIFY_ROUTINE CmpTraceRoutine
Definition at line 31 of file cmwmi.c.
Referenced by CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), and CmSetTraceNotifyRoutine().
UNICODE_STRING CmRegistrySystemCloneName
Definition at line 220 of file cmdat.c.
Referenced by CmpDeleteCloneTree().
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.