Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/pfnlist.c File Reference
pfnlist.c File Reference
#include "mi.h"
Macros
#define MI_SNAP_PFN(_Pfn, dest, callerid)
#define MI_TALLY_TRANSITION_PAGE_ADDITION(Pfn)
#define MI_TALLY_TRANSITION_PAGE_REMOVAL(Pfn)
Functions
C_ASSERT (StandbyPageList==2)
PFN_NUMBER MiAllocatePfn (IN PMMPTE PointerPte, IN ULONG Protection)
LOGICAL MiDereferenceLastChanceLdw (IN PMM_LDW_WORK_CONTEXT LdwContext)
ULONG FASTCALL MiEnsureAvailablePageOrWait (IN PEPROCESS Process, IN KIRQL OldIrql)
VOID MiInitializePfnTracing (VOID)
VOID FASTCALL MiInsertFrontModifiedNoWrite (IN PFN_NUMBER PageFrameIndex)
VOID FASTCALL MiInsertPageInFreeList (IN PFN_NUMBER PageFrameIndex)
VOID FASTCALL MiInsertPageInList (IN PMMPFNLIST ListHead, IN PFN_NUMBER PageFrameIndex)
VOID FASTCALL MiInsertStandbyListAtFront (IN PFN_NUMBER PageFrameIndex)
VOID FASTCALL MiInsertZeroListAtBack (IN PFN_NUMBER PageFrameIndex)
VOID FASTCALL MiLogPfnInformation (IN PMMPFN Pfn1, IN USHORT Reason)
VOID MiNoPagesLastChance (IN ULONG Limit)
VOID MiPurgeTransitionList (VOID)
PFN_NUMBER FASTCALL MiRemoveAnyPage (IN ULONG Color)
PFN_NUMBER FASTCALL MiRemovePageByColor (IN PFN_NUMBER Page, IN ULONG PageColor)
PFN_NUMBER FASTCALL MiRemovePageFromList (IN PMMPFNLIST ListHead)
PFN_NUMBER FASTCALL MiRemoveZeroPage (IN ULONG Color)
VOID MiUnlinkFreeOrZeroedPage (IN PMMPFN Pfn)
VOID FASTCALL MiUnlinkPageFromList (IN PMMPFN Pfn)
Variables
BOOLEAN Mi4dBreak = TRUE
ULONG Mi4dFiles
ULONG Mi4dPages
ULONG MiAvailablePagesEventHighSets
ULONG MiAvailablePagesEventLowSets
MM_LDW_WORK_CONTEXT MiLastChanceLdwContext
NTSTATUS MiLastMappedWriteError
NTSTATUS MiLastModifiedWriteError
LOGICAL MiZeroingDisabled
KEVENT MmAvailablePagesEventHigh
ULONG MmStandbyRePurposed
ULONG MmSystemShutdown
PFN_NUMBER MmTransitionPrivatePages
PFN_NUMBER MmTransitionSharedPages
Macro Definition Documentation
#define MI_SNAP_PFN (_Pfn, dest, callerid)
Definition at line 92 of file pfnlist.c.
Referenced by MiInsertFrontModifiedNoWrite(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), and MiInsertZeroListAtBack().
#define MI_TALLY_TRANSITION_PAGE_ADDITION (Pfn)
Value:
if (Pfn->u3.e1.PrototypePte) { \
        MmTransitionSharedPages += 1; \
    } \
    else { \
        MmTransitionPrivatePages += 1; \
    }
Definition at line 37 of file pfnlist.c.
Referenced by MiInsertFrontModifiedNoWrite(), and MiInsertPageInList().
#define MI_TALLY_TRANSITION_PAGE_REMOVAL (Pfn)
Value:
if (Pfn->u3.e1.PrototypePte) { \
        MmTransitionSharedPages -= 1; \
    } \
    else { \
        MmTransitionPrivatePages -= 1; \
    }
Definition at line 45 of file pfnlist.c.
Referenced by MiRemovePageFromList(), and MiUnlinkPageFromList().
Function Documentation
C_ASSERT (StandbyPageList = =2)
PFN_NUMBER MiAllocatePfn (IN PMMPTE PointerPte, IN ULONG Protection)
Definition at line 2827 of file pfnlist.c.
References DemandZeroPte, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_COLOR_FROM_PTE, MI_WRITE_INVALID_PTE, MiEnsureAvailablePageOrWait(), MiInitializePfn(), MiRemoveAnyPage(), MM_HIGH_LIMIT, MM_KERNEL_DEMAND_ZERO_PTE, MmAvailablePages, NULL, _MMPTE::u, and UNLOCK_PFN.
Referenced by MiLoadImageSection().
LOGICAL MiDereferenceLastChanceLdw (IN PMM_LDW_WORK_CONTEXT LdwContext)
Definition at line 1563 of file pfnlist.c.
References ASSERT, FALSE, _MM_LDW_WORK_CONTEXT::FileObject, LOCK_PFN, NULL, TRUE, and UNLOCK_PFN.
Referenced by MiLdwPopupWorker().
ULONG FASTCALL MiEnsureAvailablePageOrWait (IN PEPROCESS Process, IN KIRQL OldIrql)
Definition at line 1863 of file pfnlist.c.
References ASSERT, FALSE, _MM_SESSION_SPACE::GlobalVirtualAddress, HYDRA_PROCESS, KeClearEvent(), KernelMode, KeWaitForSingleObject(), LOCK_PFN, LOCK_WORKING_SET, LOCK_WS_REGARDLESS, _ETHREAD::MemoryMaker, MiAvailablePagesEventHighSets, MiAvailablePagesEventLowSets, MiNoPagesLastChance(), MM_HIGH_LIMIT, MM_LOW_LIMIT, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmAvailablePagesEvent, MmSessionSpace, MmSeventySeconds, MmSystemCacheWs, NULL, _ETHREAD::OwnsSystemWorkingSetExclusive, _ETHREAD::OwnsSystemWorkingSetShared, PsGetCurrentThread(), Status, STATUS_TIMEOUT, TRUE, UNLOCK_PFN, UNLOCK_WORKING_SET, UNLOCK_WS_REGARDLESS, _MM_SESSION_SPACE::Vm, and WrFreePage.
Referenced by MiAllocatePfn(), MiCcPutPagesInTransition(), MiCopyOnWrite(), MiDoneWithThisPageGetAnother(), MiFillSystemPageDirectory(), MiGetPageForHeader(), MiInitializeLargePageSupport(), MiLeaveThisPageGetAnother(), MiMakeOutswappedPageResident(), MiReloadBootLoadedDrivers(), MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveTransitionFault(), MiSessionCommitPageTables(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MmAccessFault(), MmAllocateIndependentPages(), MmCopyToCachedPage(), MmCreateKernelStack(), MmCreateProcessAddressSpace(), and MmGrowKernelStackEx().
VOID MiInitializePfnTracing (VOID)
Definition at line 95 of file pfnlist.c.
Referenced by MmInitSystem().
VOID FASTCALL MiInsertFrontModifiedNoWrite (IN PFN_NUMBER PageFrameIndex)
Definition at line 2754 of file pfnlist.c.
References ASSERT, _MMPFNLIST::Blink, _MMPFN::Blink, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPFNLIST::Flink, _MMPFN::Flink, MI_PFN_ELEMENT, MI_SNAP_DATA, MI_SNAP_PFN, MI_TALLY_TRANSITION_PAGE_ADDITION, MiCached, MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmHighestPhysicalPage, MmLowestPhysicalPage, MmModifiedNoWritePageListHead, ModifiedNoWritePageList, _MMPFN::MustBeCached, _MMPFNENTRY::PageLocation, _MMPFN::PteAddress, StandbyPageList, _MMPFNLIST::Total, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, and _MMPFN::u4.
VOID FASTCALL MiInsertPageInFreeList (IN PFN_NUMBER PageFrameIndex)
Definition at line 104 of file pfnlist.c.
References ASSERT, _MMPFN::AweAllocation, _MMPFNLIST::Blink, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, BYTE_OFFSET, _MMCOLOR_TABLES::Count, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, _MMPFN::InPageError, KeClearEvent(), KeFeatureBits, KeNodeBlock, KeNumberNodes, KeSetEvent(), KF_LARGE_PAGE, _MMPTE::Long, MI_GET_COLOR_FROM_LIST_ENTRY, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_RESET_PFN_PRIORITY, MI_SNAP_DATA, MI_SNAP_PFN, MI_STACK_BYTES, MiAvailablePagesEventHighSets, MiAvailablePagesEventLowSets, MiGetStackPointer(), MiHighMemoryEvent, MiInsertPageInList(), MiLogPfnInformation(), MiLowMemoryEvent, MiMapPageInHyperSpaceAtDpc(), MiUnmapPageInHyperSpaceFromDpc, MM_EMPTY_LIST, MM_HIGH_LIMIT, MM_LOW_LIMIT, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmAvailablePagesEvent, MmBadPageListHead, MmFirstReservedMappingPte, MmFreePageListHead, MmFreePagesByColor, MmHighestPhysicalPage, MmHighMemoryThreshold, MmLowestPhysicalPage, MmLowMemoryThreshold, MmMinimumFreePagesToZero, MmZeroingPageEvent, MmZeroingPageThreadActive, _MMPFN::MustBeCached, NULL, _MMPFN::OriginalPte, PAGE_SIZE, _MMPFNENTRY::PageColor, _MMPFNENTRY::PageLocation, PERF_MEMORY, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_INSERTINFREELIST, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::RemovalRequested, _MMPFNENTRY::Rom, RtlCopyMemory, _MMPFNLIST::Total, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and _MMPFN::VerifierAllocation.
Referenced by MiCcCompletePrefetchIos(), MiCleanSection(), MiDecommitPages(), MiDecrementCloneBlockReference(), MiDecrementReferenceCount(), MiDecrementShareCount(), MiDeletePte(), MiDeleteSystemPageableVm(), MiDispatchFault(), MiInitMachineDependent(), MiPurgeImageSection(), MiRemoveUnusedSegments(), MiResolveTransitionFault(), MiReturnLargePages(), MiSegmentDelete(), MiZeroPageWorker(), MmCopyToCachedPage(), MmDeleteProcessAddressSpace(), MmFreeLoaderBlock(), and MmPurgeSection().
VOID FASTCALL MiInsertPageInList (IN PMMPFNLIST ListHead, IN PFN_NUMBER PageFrameIndex)
Definition at line 354 of file pfnlist.c.
References ASSERT, BadPageList, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, _MMPFNENTRY::CacheAttribute, _MMCOLOR_TABLES::Count, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, _MMPFN::InPageError, KeBugCheckEx(), KeClearEvent(), KeFeatureBits, KeNodeBlock, KeNumberNodes, KeSetEvent(), KeSetTimerEx(), KF_LARGE_PAGE, _MMPTE::Long, MEMORY_MANAGEMENT, MI_BARRIER_STAMP_ZEROED_PAGE, MI_GET_COLOR_FROM_LIST_ENTRY, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SNAP_PFN, MI_TALLY_TRANSITION_PAGE_ADDITION, MiAvailablePagesEventHighSets, MiAvailablePagesEventLowSets, MiCached, MiGetByteOffset, MiHighMemoryEvent, MiLowMemoryEvent, MiMapPageInHyperSpaceAtDpc(), MiModifiedPageLife, MiModifiedPageWriterTimer, MiModifiedPageWriterTimerDpc, MiRestoreTransitionPte(), MiTimerPending, MiUnmapPageInHyperSpaceFromDpc, MM_DBG_PAGE_REF_COUNT, MM_EMPTY_LIST, MM_HIGH_LIMIT, MM_LOW_LIMIT, MM_PFN_LOCK_ASSERT, MM_PLENTY_FREE_LIMIT, MM_TIGHT_LIMIT, MmAvailablePages, MmAvailablePagesEvent, MmBadPageListHead, MmFreePageListHead, MmFreePagesByColor, MmHighestPhysicalPage, MmHighMemoryThreshold, MmIsAddressValid(), MmLowestPhysicalPage, MmLowMemoryThreshold, MmModifiedPageListByColor, MmModifiedPageListHead, MmModifiedPageMaximum, MmModifiedPageWriterEvent, MmModifiedWriteClusterSize, MmStandbyPageListByPriority, MmStandbyPageListHead, MmTotalPagesForPagingFile, ModifiedNoWritePageList, _EPROCESS::ModifiedPageCount, ModifiedPageList, _MMPFN::MustBeCached, NULL, _MMPFN::OriginalPte, _MMPFNENTRY::PageColor, _MMPTE_SOFTWARE::PageFileHigh, _MMPFNENTRY::PageLocation, _MMPFN::Priority, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::RemovalRequested, _MMPFNENTRY::Rom, _MMPTE::Soft, StandbyPageList, _MMPFNLIST::Total, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and ZeroedPageList.
Referenced by MiDecrementReferenceCount(), MiGatherMappedPages(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiResetVirtualMemory(), MmEnableModifiedWriteOfSection(), and MmZeroPageThread().
VOID FASTCALL MiInsertStandbyListAtFront (IN PFN_NUMBER PageFrameIndex)
Definition at line 920 of file pfnlist.c.
References ASSERT, _MMPFNLIST::Blink, _MMPFN::Blink, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, KeBugCheckEx(), KeClearEvent(), KeSetEvent(), MEMORY_MANAGEMENT, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SNAP_DATA, MI_SNAP_PFN, MiAvailablePagesEventHighSets, MiAvailablePagesEventLowSets, MiGetByteOffset, MiHighMemoryEvent, MiLowMemoryEvent, MiMapPageInHyperSpaceAtDpc(), MiUnmapPageInHyperSpaceFromDpc, MM_DBG_PAGE_REF_COUNT, MM_EMPTY_LIST, MM_HIGH_LIMIT, MM_LOW_LIMIT, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmAvailablePagesEvent, MmHighestPhysicalPage, MmHighMemoryThreshold, MmIsAddressValid(), MmLowestPhysicalPage, MmLowMemoryThreshold, MmStandbyPageListByPriority, MmTransitionSharedPages, _MMPFN::MustBeCached, NULL, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPFN::Priority, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::Rom, _MMPTE::Soft, StandbyPageList, _MMPFNLIST::Total, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, and _MMPFN::u4.
Referenced by MiDecrementReferenceCount().
VOID FASTCALL MiInsertZeroListAtBack (IN PFN_NUMBER PageFrameIndex)
Definition at line 741 of file pfnlist.c.
References ASSERT, BadPageList, _MMPFNLIST::Blink, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, _MMCOLOR_TABLES::Count, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, _MMPFN::InPageError, KeClearEvent(), KeNodeBlock, KeNumberNodes, KeSetEvent(), _MMPTE::Long, MI_BARRIER_STAMP_ZEROED_PAGE, MI_GET_COLOR_FROM_LIST_ENTRY, MI_PFN_ELEMENT, MI_SNAP_PFN, MiAvailablePagesEventHighSets, MiAvailablePagesEventLowSets, MiHighMemoryEvent, MiLowMemoryEvent, MM_EMPTY_LIST, MM_HIGH_LIMIT, MM_LOW_LIMIT, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmAvailablePagesEvent, MmBadPageListHead, MmFreePagesByColor, MmHighestPhysicalPage, MmHighMemoryThreshold, MmLowestPhysicalPage, MmLowMemoryThreshold, MmPfnDatabase, MmZeroedPageListHead, _MMPFN::MustBeCached, _MMPFN::OriginalPte, _MMPFNENTRY::PageColor, _MMPFNENTRY::PageLocation, _MMPFN::PteFrame, _MMPFNENTRY::RemovalRequested, _MMPFNENTRY::Rom, _MMPFNLIST::Total, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and ZeroedPageList.
Referenced by MiZeroPageWorker().
VOID FASTCALL MiLogPfnInformation (IN PMMPFN Pfn1, IN USHORT Reason)
Definition at line 2879 of file pfnlist.c.
References MiIdentifyPfn(), PerfInfoLogBytes(), and RtlZeroMemory.
Referenced by MiInsertPageInFreeList(), MiRemovePageByColor(), and MiRemovePageFromList().
VOID MiNoPagesLastChance (IN ULONG Limit)
Definition at line 1588 of file pfnlist.c.
References ASSERT, _SUBSECTION::ControlArea, DbgBreakPoint(), DbgPrintEx(), DelayedWorkQueue, DIRTY_MAPPED_PAGES_CONGESTION, DIRTY_NOWRITE_PAGES_CONGESTION, DISORDERLY_SHUTDOWN, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, _MM_LDW_WORK_CONTEXT::FileObject, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMPFNLIST::Flink, _MMPFN::Flink, _MMPAGING_FILE::FreeSpace, _MMSECTION_FLAGS::Image, KdDebuggerNotPresent, KdPitchDebugger, KeBugCheckEx(), LOCK_PFN, _MMPAGING_FILE::MaximumSize, Mi4dBreak, Mi4dFiles, Mi4dPages, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiGetSubsectionAddress, MiLastChanceLdwContext, MiLastMappedWriteError, MiLastModifiedWriteError, MiLdwPopupWorker(), MiUnlinkPageFromList(), MM_EMPTY_LIST, MmAvailablePages, MmModifiedNoWritePageListHead, MmModifiedPageListHead, MmNumberOfPagingFiles, MmPagingFile, MmSystemShutdown, MmTotalPagesForPagingFile, NO_PAGES_AVAILABLE, _MMSECTION_FLAGS::NoModifiedWriting, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfPfnReferences, ObReferenceObject, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_SOFTWARE::Prototype, _MMPAGING_FILE::Size, _MMPTE::Soft, Status, STATUS_SUCCESS, _MMPFNLIST::Total, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u1, UNLOCK_PFN, and _MM_LDW_WORK_CONTEXT::WorkItem.
Referenced by MiEnsureAvailablePageOrWait().
VOID MiPurgeTransitionList (VOID)
Definition at line 2898 of file pfnlist.c.
References ASSERT, _MMPFN::e2, InterlockedIncrementPfn, LOCK_PFN, _MMPTE::Long, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MI_SET_PFN_DELETED, MiDecrementReferenceCount(), MiRemovePageFromList(), MmStandbyPageListByPriority, _MMPFN::OriginalPte, _MMPFN::ShareCount, _MMPFNLIST::Total, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN.
Referenced by MiEmptyWorkingSet(), MiFindContiguousPages(), and MiTrimAllSystemPageableMemory().
PFN_NUMBER FASTCALL MiRemoveAnyPage (IN ULONG Color)
Definition at line 2355 of file pfnlist.c.
References ASSERT, _MMPFN::e1, _MMPFN::e2, _MMPFNLIST::Flink, _MMCOLOR_TABLES::Flink, FreePageList, KeNumberNodes, MI_CHECK_PAGE_ALIGNMENT, MI_GET_COLOR_FROM_LIST_ENTRY, MI_MAGIC_AWE_PTEFRAME, MI_NODE_FROM_COLOR, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MiRemovePageByColor(), MiRemovePageFromList(), MM_COLOR_MASK, MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmFreePageListHead, MmFreePagesByColor, MmSecondaryColorMask, MmSecondaryColors, MmStandbyPageListByPriority, MmStandbyRePurposed, MmZeroedPageListHead, _MMPFNENTRY::PageLocation, _MMPFN::PteFrame, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _MMPFNLIST::Total, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and ZeroedPageList.
Referenced by MiAllocatePfn(), MiAllocatePoolPages(), MiBuildPagedPool(), MiCcPutPagesInTransition(), MiCopyOnWrite(), MiGetPageForHeader(), MiInitMachineDependent(), MiMakeOutswappedPageResident(), MiReloadBootLoadedDrivers(), MiRemoveZeroPageMayReleaseLocks(), MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiZeroPageWorker(), MmAccessFault(), MmAllocateIndependentPages(), MmCopyToCachedPage(), MmCreateKernelStack(), MmGatherMemoryForHibernate(), MmGrowKernelStackEx(), and MmZeroPageThread().
PFN_NUMBER FASTCALL MiRemovePageByColor (IN PFN_NUMBER Page, IN ULONG PageColor)
Definition at line 2597 of file pfnlist.c.
References ASSERT, _MMPFNLIST::Blink, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, _MMPFNENTRY::CacheAttribute, _MMCOLOR_TABLES::Count, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, KeClearEvent(), KeNodeBlock, KeNumberNodes, KeSetEvent(), _MMPFNLIST::ListName, _MMPTE::Long, MI_PFN_ELEMENT, MiHighMemoryEvent, MiLogPfnInformation(), MiLowMemoryEvent, MiObtainFreePages(), MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmFreePagesByColor, MmHighMemoryThreshold, MmLowMemoryThreshold, MmMinimumFreePages, MmPageLocationList, MmSecondaryColorNodeShift, MmSecondaryColors, _MMPFN::OriginalPte, _MMPFNENTRY::PageColor, _MMPFNENTRY::PageLocation, PERF_MEMORY, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_REMOVEPAGEBYCOLOR, _MMPFNENTRY::RemovalRequested, _MMPFNENTRY::Rom, _MMPFNLIST::Total, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, and _MMPFN::u3.
Referenced by MiRemoveAnyPage(), and MiRemoveZeroPage().
PFN_NUMBER FASTCALL MiRemovePageFromList (IN PMMPFNLIST ListHead)
Definition at line 1075 of file pfnlist.c.
References ASSERT, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, _MMPFNENTRY::CacheAttribute, _MMCOLOR_TABLES::Count, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, KeBugCheckEx(), KeClearEvent(), KeSetEvent(), _MMPTE::Long, MI_GET_COLOR_FROM_LIST_ENTRY, MI_PFN_ELEMENT, MI_TALLY_TRANSITION_PAGE_REMOVAL, MiHighMemoryEvent, MiLogPfnInformation(), MiLowMemoryEvent, MiObtainFreePages(), MiRestoreTransitionPte(), MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmFreePagesByColor, MmHighestPhysicalPage, MmHighMemoryThreshold, MmLowestPhysicalPage, MmLowMemoryThreshold, MmMinimumFreePages, MmStandbyPageListHead, ModifiedPageList, _MMPFN::OriginalPte, _MMPFNENTRY::PageColor, PERF_MEMORY, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_REMOVEPAGEFROMLIST, PFN_LIST_CORRUPT, _MMPFNENTRY::RemovalRequested, _MMPFNENTRY::Rom, StandbyPageList, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, and _MMPFN::u3.
Referenced by MiPurgeTransitionList(), MiRemoveAnyPage(), and MiRemoveZeroPage().
PFN_NUMBER FASTCALL MiRemoveZeroPage (IN ULONG Color)
Definition at line 2049 of file pfnlist.c.
References ASSERT, _MMPFN::e1, _MMPFN::e2, _MMPFNLIST::Flink, _MMCOLOR_TABLES::Flink, FreePageList, KeNumberNodes, MI_BARRIER_STAMP_ZEROED_PAGE, MI_GET_COLOR_FROM_LIST_ENTRY, MI_MAGIC_AWE_PTEFRAME, MI_NODE_FROM_COLOR, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MiRemovePageByColor(), MiRemovePageFromList(), MiZeroPhysicalPage(), MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmFreePageListHead, MmFreePagesByColor, MmSecondaryColorMask, MmSecondaryColors, MmStandbyPageListByPriority, MmStandbyRePurposed, MmZeroedPageListHead, NULL, _MMPFNENTRY::PageLocation, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPFNLIST::Total, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and ZeroedPageList.
Referenced by MiAddWorkingSetPage(), MiAddWsleHash(), MiBuildPagedPool(), MiDoneWithThisPageGetAnother(), MiFillSystemPageDirectory(), MiGetPageForHeader(), MiInitializeAndChargePfn(), MiInitializeLargePageSupport(), MiInitializeSystemCache(), MiLeaveThisPageGetAnother(), MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiSessionCommitPageTables(), MiZeroAllPageFiles(), MmCheckCachedPageState(), and MmInitSystem().
VOID MiUnlinkFreeOrZeroedPage (IN PMMPFN Pfn)
Definition at line 1416 of file pfnlist.c.
References ASSERT, _MMPFNLIST::Blink, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, _MMCOLOR_TABLES::Count, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, KeClearEvent(), KeNumberNodes, KeSetEvent(), _MMPFNLIST::ListName, _MMPTE::Long, MI_GET_COLOR_FROM_LIST_ENTRY, MI_NODE_FROM_COLOR, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiHighMemoryEvent, MiLowMemoryEvent, MiObtainFreePages(), MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmFreePagesByColor, MmHighMemoryThreshold, MmLowMemoryThreshold, MmMinimumFreePages, MmPageLocationList, _MMPFN::OriginalPte, _MMPFN::PteFrame, _MMPFNLIST::Total, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, and _MMPFN::u4.
Referenced by MiAllocatePagesForMdl(), MiFindContiguousPages(), and MiFindLargePageMemory().
VOID FASTCALL MiUnlinkPageFromList (IN PMMPFN Pfn)
Definition at line 1250 of file pfnlist.c.
References ASSERT, _MMPFNLIST::Blink, _MMPFN::Blink, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, KdPrint, KeBugCheckEx(), KeClearEvent(), KeSetEvent(), _MMPFNLIST::ListName, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_TALLY_TRANSITION_PAGE_REMOVAL, MiHighMemoryEvent, MiLowMemoryEvent, MiObtainFreePages(), MM_EMPTY_LIST, MM_PFN_LOCK_ASSERT, MmAvailablePages, MmHighestPhysicalPage, MmHighMemoryThreshold, MmLowMemoryThreshold, MmMinimumFreePages, MmModifiedNoWritePageListHead, MmModifiedPageListByColor, MmModifiedPageListHead, MmPageLocationList, MmStandbyPageListByPriority, MmStandbyPageListHead, MmTotalPagesForPagingFile, PFN_LIST_CORRUPT, StandbyPageList, _MMPFNLIST::Total, _MMPFN::u1, and _MMPFN::u2.
Referenced by MiAllocatePagesForMdl(), MiCcCompletePrefetchIos(), MiCleanSection(), MiDecommitPages(), MiDecrementCloneBlockReference(), MiDeletePte(), MiDeleteSystemPageableVm(), MiDispatchFault(), MiFindContiguousPages(), MiFindLargePageMemory(), MiFlushSectionInternal(), MiGatherMappedPages(), MiGatherPagefilePages(), MiLockCode(), MiMakeOutswappedPageResident(), MiNoPagesLastChance(), MiPurgeImageSection(), MiRemoveUnusedSegments(), MiResetVirtualMemory(), MiResolveTransitionFault(), MiSegmentDelete(), MiShutdownSystem(), MmCheckCachedPageState(), MmCopyToCachedPage(), MmEnableModifiedWriteOfSection(), and MmPurgeSection().
Variable Documentation
BOOLEAN Mi4dBreak = TRUE
Definition at line 1583 of file pfnlist.c.
Referenced by MiNoPagesLastChance().
ULONG Mi4dFiles
Definition at line 1584 of file pfnlist.c.
Referenced by MiNoPagesLastChance().
ULONG Mi4dPages
Definition at line 1585 of file pfnlist.c.
Referenced by MiNoPagesLastChance().
ULONG MiAvailablePagesEventHighSets
Definition at line 63 of file pfnlist.c.
Referenced by MiEnsureAvailablePageOrWait(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), and MiInsertZeroListAtBack().
ULONG MiAvailablePagesEventLowSets
Definition at line 62 of file pfnlist.c.
Referenced by MiEnsureAvailablePageOrWait(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), and MiInsertZeroListAtBack().
MM_LDW_WORK_CONTEXT MiLastChanceLdwContext
Definition at line 60 of file pfnlist.c.
Referenced by MiNoPagesLastChance().
NTSTATUS MiLastMappedWriteError
Definition at line 59 of file modwrite.c.
Referenced by MiNoPagesLastChance(), and MiWriteComplete().
NTSTATUS MiLastModifiedWriteError
Definition at line 58 of file modwrite.c.
Referenced by MiNoPagesLastChance(), and MiWriteComplete().
LOGICAL MiZeroingDisabled
Definition at line 27 of file zeropage.c.
KEVENT MmAvailablePagesEventHigh
Definition at line 32 of file pfnlist.c.
Referenced by MmInitSystem().
ULONG MmStandbyRePurposed
Definition at line 58 of file pfnlist.c.
Referenced by MiComputeSystemTrimCriteria(), MiRemoveAnyPage(), MiRemoveZeroPage(), and MmQuerySystemCacheWorkingSetInformation().
ULONG MmSystemShutdown
Definition at line 119 of file modwrite.c.
Referenced by MiNoPagesLastChance().
PFN_NUMBER MmTransitionPrivatePages
Definition at line 34 of file pfnlist.c.
PFN_NUMBER MmTransitionSharedPages
Definition at line 35 of file pfnlist.c.
Referenced by MiAllocateWsle(), MiInsertStandbyListAtFront(), and MmQuerySystemCacheWorkingSetInformation().