Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/freevm.c File Reference
freevm.c File Reference
#include "mi.h"
Macros
#define MM_VALID_PTE_SIZE (256)
Functions
ULONG MiDecommitPages (IN PVOID StartingAddress, IN PMMPTE EndingPte, IN PEPROCESS Process, IN PMMVAD_SHORT Vad)
ULONG MiIsEntireRangeCommitted (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN PEPROCESS Process)
VOID MiProcessValidPteList (IN PMMPTE *PteList, IN ULONG Count)
NTSTATUS NtFreeVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG FreeType)
Variables
MMPTE MmDecommittedPte = {MM_DECOMMIT << MM_PROTECT_FIELD_SHIFT}
Macro Definition Documentation
#define MM_VALID_PTE_SIZE (256)
Definition at line 22 of file freevm.c.
Referenced by MiDecommitPages().
Function Documentation
ULONG MiDecommitPages (IN PVOID StartingAddress, IN PMMPTE EndingPte, IN PEPROCESS Process, IN PMMVAD_SHORT Vad)
Definition at line 1152 of file freevm.c.
References ASSERT, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE::Hard, LOCK_PFN, LOCK_WS_UNSAFE, _MMWSLENTRY::LockedInMemory, _MMWSLENTRY::LockedInWs, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_SET_PTE_IN_WORKING_SET, MI_VPN_TO_VA, MI_WRITE_INVALID_PTE, MiDecrementShareCountInline, MiDeletePte(), MiGetPdeAddress, MiGetPteAddress, MiInsertPageInFreeList(), MiIsPteOnPdeBoundary, MiMakePdeExistAndMakeValid(), MiProcessValidPteList(), MiReleasePageFileSpace(), MiReleaseWsle(), MiRemoveWsle(), MiSwapWslEntries(), MiUnlinkPageFromList(), MM_NOIRQL, MM_VALID_PTE_SIZE, MmWorkingSetList, MmWsle, NULL, _MMPFN::OriginalPte, PAGE_ALIGN, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteFrame, _MMPTE::Soft, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WS_UNSAFE, _MMPTE_SOFTWARE::Valid, _MMPTE_HARDWARE::Valid, and _MMPFN::WsIndex.
Referenced by NtFreeVirtualMemory().
ULONG MiIsEntireRangeCommitted (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN PEPROCESS Process)
Definition at line 864 of file freevm.c.
References FALSE, _MMPTE::Long, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteDecommittedPage(), MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MM_NOIRQL, PAGE_SIZE, PAGED_CODE, TRUE, and _MMPTE::u.
Referenced by MiProtectVirtualMemory().
VOID MiProcessValidPteList (IN PMMPTE * PteList, IN ULONG Count)
Definition at line 1516 of file freevm.c.
References ASSERT, Count, _MMPTE_FLUSH_LIST::Count, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_INVALID_PTE, MiDecrementShareCount(), MiDecrementShareCountInline, MiFlushPteList(), MiGetVirtualAddressMappedByPte, MM_MAXIMUM_FLUSH_COUNT, _MMPFN::PteFrame, _MMPTE::u, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiDecommitPages().
NTSTATUS NtFreeVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG FreeType)
Definition at line 42 of file freevm.c.
References ASSERT, _EPROCESS::CommitCharge, _MMVAD_FLAGS::CommitCharge, _MMVAD::EndingVpn, _MMVAD_SHORT::EndingVpn, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _EPROCESS::JobStatus, KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MEM_DECOMMIT, MEM_RELEASE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiAweViewRemover(), MiCalculatePageCommitment(), MiCheckSecuredVad(), MiDecommitPages(), MiDeletePageTablesForPhysicalRange(), MiDeleteVirtualAddresses(), MiFreeLargePages(), MiGetNextVad, MiGetPreviousVad, MiGetPteAddress, MiInsertVad(), MiInsertVadCharges(), MiLocateAddress(), MiPhysicalViewRemover(), MiReleasePhysicalCharges(), MiRemoveUserPhysicalPagesVad(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnCommitment, MiReturnPageTablePageCommitment(), MiUnmapViewOfSection(), MM_DBG_COMMIT_RETURN_NTFREEVM1, MM_DBG_COMMIT_RETURN_NTFREEVM2, MM_HIGHEST_USER_ADDRESS, MM_SECURE_DELETE_CHECK, MM_TRACK_COMMIT, _MMVAD_FLAGS::NoChange, NonPagedPool, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _EPROCESS::Pcb, _MMVAD_FLAGS::PrivateMemory, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_PROCESS_FLAGS_VM_DELETED, PsChangeJobMemoryUsage(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, PsReturnProcessPageFileQuota(), _MMVAD::StartingVpn, _MMVAD_SHORT::StartingVpn, Status, STATUS_FREE_VM_NOT_AT_BASE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_MEMORY_NOT_ALLOCATED, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_UNABLE_TO_DELETE_SECTION, STATUS_UNABLE_TO_FREE_VM, _ETHREAD::Tcb, TRUE, _MMVAD::u, _MMVAD_SHORT::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, UNMAP_ADDRESS_SPACE_HELD, UNMAP_ROTATE_PHYSICAL_OK, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_SHORT::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, VadWriteWatch, and _EPROCESS::VirtualSize.
Referenced by RtlFreeUserThreadStack().
Variable Documentation
MMPTE MmDecommittedPte = {MM_DECOMMIT << MM_PROTECT_FIELD_SHIFT}
Definition at line 24 of file freevm.c.