Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/amd64/psctxamd64.c File Reference
psctxamd64.c File Reference
#include "psp.h"
Macros
#define CONTEXT_EXCEPTION_FLAGS (CONTEXT_EXCEPTION_ACTIVE | CONTEXT_SERVICE_ACTIVE)
Functions
VOID PspGetContext (IN PKTRAP_FRAME TrapFrame, IN PKNONVOLATILE_CONTEXT_POINTERS ContextPointers, IN OUT PCONTEXT ContextRecord)
PXMM_SAVE_AREA32 PspGetSetContextInternal (IN PKAPC Apc, IN PVOID OperationType, OUT PKEVENT *Event)
VOID PspSetContext (OUT PKTRAP_FRAME TrapFrame, OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers, IN PCONTEXT ContextRecord, KPROCESSOR_MODE PreviousMode)
Macro Definition Documentation
#define CONTEXT_EXCEPTION_FLAGS (CONTEXT_EXCEPTION_ACTIVE | CONTEXT_SERVICE_ACTIVE)
Definition at line 25 of file psctxamd64.c.
Referenced by PspGetContext().
Function Documentation
VOID PspGetContext (IN PKTRAP_FRAME TrapFrame, IN PKNONVOLATILE_CONTEXT_POINTERS ContextPointers, IN OUT PCONTEXT ContextRecord)
Definition at line 43 of file psctxamd64.c.
Referenced by PspGetSetContextInternal().
PXMM_SAVE_AREA32 PspGetSetContextInternal (IN PKAPC Apc, IN PVOID OperationType, OUT PKEVENT * Event)
Definition at line 413 of file psctxamd64.c.
References CONTAINING_RECORD, _GETSETCONTEXT::Context, CONTEXT_FLOATING_POINT, _CONTEXT::ContextFlags, KernelMode, _GETSETCONTEXT::Mode, _GETSETCONTEXT::NonVolatileContext, NULL, _GETSETCONTEXT::OperationComplete, PAGED_CODE, PsGetCurrentThread(), PspGetBaseTrapFrame, PspGetContext(), PspSetContext(), RtlCaptureContext(), RtlLookupFunctionEntry(), RtlVirtualUnwind(), RtlZeroMemory, _ETHREAD::Tcb, _KTHREAD::TrapFrame, UNW_FLAG_EHANDLER, and UserMode.
VOID PspSetContext (OUT PKTRAP_FRAME TrapFrame, OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers, IN PCONTEXT ContextRecord, KPROCESSOR_MODE PreviousMode)
Definition at line 236 of file psctxamd64.c.
Referenced by PspGetSetContextInternal().