Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/mmquota.c File Reference
mmquota.c File Reference
#include "mi.h"
Macros
#define MI_LOG_COMMIT_CHANGE(NewCommitValue, QuotaCharge)
#define MI_LOG_COMMIT_FAILURE(NewCommitValue, QuotaCharge)
#define MM_MINIMAL_COMMIT_INCREASE 512
Functions
SIZE_T MiCalculatePageCommitment (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN PEPROCESS Process)
VOID MiCauseOverCommitPopup (VOID)
LOGICAL FASTCALL MiChargeCommitment (IN SIZE_T QuotaCharge, IN PEPROCESS Process OPTIONAL)
LOGICAL FASTCALL MiChargeCommitmentCantExpand (IN SIZE_T QuotaCharge, IN ULONG MustSucceed)
LOGICAL FASTCALL MiChargeTemporaryCommitmentForReduction (IN SIZE_T QuotaCharge)
VOID MiInitializeCommitment (VOID)
VOID MiReturnPageTablePageCommitment (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PEPROCESS CurrentProcess, IN PMMVAD PreviousVad, IN PMMVAD NextVad)
BOOLEAN MmRaisePoolQuota (IN POOL_TYPE PoolType, IN SIZE_T OldQuotaLimit, OUT PSIZE_T NewQuotaLimit)
VOID MmReturnPoolQuota (IN POOL_TYPE PoolType, IN SIZE_T ReturnedQuota)
Variables
LONG MiCommitPopups [2]
ULONG_PTR MmAllocatedPagedPool
SIZE_T MmPeakCommitment
SIZE_T MmSystemCommitReserve = (5 * 1024 * 1024) / PAGE_SIZE
SIZE_T MmTotalNonPagedPoolQuota
SIZE_T MmTotalPagedPoolQuota
Macro Definition Documentation
#define MI_LOG_COMMIT_CHANGE (NewCommitValue, QuotaCharge)
Definition at line 34 of file mmquota.c.
Referenced by MiChargeCommitment(), and MiChargeCommitmentCantExpand().
#define MI_LOG_COMMIT_FAILURE (NewCommitValue, QuotaCharge)
Definition at line 35 of file mmquota.c.
Referenced by MiChargeCommitment(), and MiChargeCommitmentCantExpand().
#define MM_MINIMAL_COMMIT_INCREASE 512
Definition at line 22 of file mmquota.c.
Referenced by MiChargeCommitmentCantExpand().
Function Documentation
SIZE_T MiCalculatePageCommitment (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN PEPROCESS Process)
Definition at line 461 of file mmquota.c.
References BYTES_TO_PAGES, _MMPTE::Long, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteDecommittedPage(), MiIsPteOnPdeBoundary, MM_NOIRQL, and _MMPTE::u.
Referenced by NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
VOID MiCauseOverCommitPopup (VOID)
Definition at line 1257 of file mmquota.c.
References InterlockedDecrement, InterlockedIncrement, IoRaiseInformationalHardError(), MiCommitPopups, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTotalCommittedPages, NULL, STATUS_COMMITMENT_LIMIT, and STATUS_COMMITMENT_MINIMUM.
Referenced by MiChargeCommitment(), and MiPageFileFull().
LOGICAL FASTCALL MiChargeCommitment (IN SIZE_T QuotaCharge, IN PEPROCESS Process OPTIONAL)
Definition at line 53 of file mmquota.c.
References _MMPAGE_FILE_EXPANSION::ActualExpansion, ASSERT, _MMPAGE_FILE_EXPANSION::Event, FALSE, InitializationPhase, _MMPAGE_FILE_EXPANSION::InProgress, InterlockedCompareExchange(), InterlockedCompareExchange64, KeInitializeEvent(), KeNumberProcessors, KiProcessorBlock, LOCK_WS_REGARDLESS, MI_EXTEND_ANY_PAGEFILE, MI_LOG_COMMIT_CHANGE, MI_LOG_COMMIT_FAILURE, MiCauseOverCommitPopup(), MiChargeCommitmentFailures, MiIssuePageExtendRequest(), MiIssuePageExtendRequestNoWait(), MiTrimSegmentCache(), MM_DBG_COMMIT_CHARGE_NORMAL, MM_TRACK_COMMIT, MmPeakCommitment, MmSystemCommitReserve, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTotalCommittedPages, NotificationEvent, NULL, _MMPAGE_FILE_EXPANSION::PageFileNumber, PsGetCurrentThread(), _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, _MMPAGE_FILE_EXPANSION::Segment, _ETHREAD::Tcb, TRUE, and UNLOCK_WS_REGARDLESS.
Referenced by MiAllocatePagesForMdl(), MiCreateImageFileMap(), MiCreatePagingFileMap(), MiInitializeLargePageSupport(), MiInitializeSessionPool(), MiInsertVadCharges(), MiLoadImageSection(), MiMapViewOfDataSection(), MiSessionCommitPageTables(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiSetPageModified(), MiSetProtectionOnSection(), MiShareSessionImage(), MmAllocateIndependentPages(), MmCommitSessionMappedView(), MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmZeroPageThread(), NtAllocateVirtualMemory(), and NtCreatePagingFile().
LOGICAL FASTCALL MiChargeCommitmentCantExpand (IN SIZE_T QuotaCharge, IN ULONG MustSucceed)
Definition at line 267 of file mmquota.c.
References ASSERT, ASSERT32, FALSE, InterlockedCompareExchange(), InterlockedCompareExchange64, MI_LOG_COMMIT_CHANGE, MI_LOG_COMMIT_FAILURE, MiChargeCommitmentFailures, MiIssuePageExtendRequestNoWait(), MM_DBG_COMMIT_CHARGE_CANT_EXPAND, MM_MINIMAL_COMMIT_INCREASE, MM_TRACK_COMMIT, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTotalCommittedPages, ReadForWriteAccess, and TRUE.
Referenced by MiAddWorkingSetPage(), MiAddWsleHash(), MiAllocatePoolPages(), MiFillSystemPageDirectory(), MiFindContiguousPages(), MiFreeLargePageMemory(), MiPageFileFull(), and MmInitSystem().
LOGICAL FASTCALL MiChargeTemporaryCommitmentForReduction (IN SIZE_T QuotaCharge)
Definition at line 389 of file mmquota.c.
References ASSERT, FALSE, InterlockedCompareExchange(), InterlockedCompareExchange64, MM_DBG_COMMIT_CHARGE_NORMAL, MM_TRACK_COMMIT, MmPeakCommitment, MmTotalCommitLimit, MmTotalCommittedPages, ReadForWriteAccess, and TRUE.
Referenced by MiAttemptPageFileReduction().
VOID MiInitializeCommitment (VOID)
Definition at line 40 of file mmquota.c.
References MmNumberOfPhysicalPages, MmSystemCommitReserve, and PAGE_SIZE.
Referenced by MmInitSystem().
VOID MiReturnPageTablePageCommitment (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PEPROCESS CurrentProcess, IN PMMVAD PreviousVad, IN PMMVAD NextVad)
Definition at line 936 of file mmquota.c.
References ASSERT, ASSERT64, _RTL_BITMAP::Buffer, MI_64K_ALIGN, MI_CHECK_BIT, MI_CLEAR_BIT, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_VPN_TO_VA, MiGetPdeIndex, MiGetPpeIndex, MiGetPxeIndex, MiLastVadBit, MiReturnCommitment, MM_DBG_COMMIT_RETURN_PAGETABLES, MM_HIGHEST_USER_ADDRESS, MM_TRACK_COMMIT, MmWorkingSetList, NULL, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PsChangeJobMemoryUsage(), PsReturnProcessPageFileQuota(), RtlClearBits(), _RTL_BITMAP::SizeOfBitMap, VAD_BITMAP_SPACE, and X64K.
Referenced by MiMapViewOfPhysicalSection(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MmDeleteTeb(), NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
BOOLEAN MmRaisePoolQuota (IN POOL_TYPE PoolType, IN SIZE_T OldQuotaLimit, OUT PSIZE_T NewQuotaLimit)
Definition at line 1311 of file mmquota.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, FALSE, MmAllocatedNonPagedPool, MmAvailablePages, MmMaximumNonPagedPoolInPages, MMNONPAGED_QUOTA_INCREASE, MMPAGED_QUOTA_CHECK, MMPAGED_QUOTA_INCREASE, MmPagedPoolInfo, MmSizeOfPagedPoolInPages, MmTotalNonPagedPoolQuota, MmTotalPagedPoolQuota, PAGE_SHIFT, PagedPool, and TRUE.
Referenced by PspExpandQuota().
VOID MmReturnPoolQuota (IN POOL_TYPE PoolType, IN SIZE_T ReturnedQuota)
Definition at line 1404 of file mmquota.c.
References MmTotalNonPagedPoolQuota, MmTotalPagedPoolQuota, and PagedPool.
Referenced by PspDereferenceQuotaBlock(), PspGivebackQuota(), and PspReleaseReturnedQuota().
Variable Documentation
LONG MiCommitPopups[2]
Definition at line 26 of file mmquota.c.
Referenced by MiCauseOverCommitPopup().
ULONG_PTR MmAllocatedPagedPool
SIZE_T MmPeakCommitment
Definition at line 24 of file mmquota.c.
Referenced by MiChargeCommitment(), MiChargeTemporaryCommitmentForReduction(), and NtQuerySystemInformation().
SIZE_T MmSystemCommitReserve = (5 * 1024 * 1024) / PAGE_SIZE
Definition at line 37 of file mmquota.c.
Referenced by MiChargeCommitment(), MiExtendPagingFiles(), and MiInitializeCommitment().
SIZE_T MmTotalNonPagedPoolQuota
Definition at line 1308 of file mmquota.c.
Referenced by MmRaisePoolQuota(), and MmReturnPoolQuota().
SIZE_T MmTotalPagedPoolQuota
Definition at line 1307 of file mmquota.c.
Referenced by MmRaisePoolQuota(), and MmReturnPoolQuota().