Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/oblink.c File Reference
oblink.c File Reference
#include "obp.h"
Macros
#define CREATE_SYMBOLIC_LINK 0
#define DELETE_SYMBOLIC_LINK 1
#define MAX_DEPTH 16
Functions
NTSTATUS NtCreateSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in PUNICODE_STRING LinkTarget)
NTSTATUS NtOpenSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQuerySymbolicLinkObject (__in HANDLE LinkHandle, __inout PUNICODE_STRING LinkTarget, __out_opt PULONG ReturnedLength)
VOID ObpCreateSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
VOID ObpDeleteSymbolicLink (IN PVOID Object)
VOID ObpDeleteSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
NTSTATUS ObpParseSymbolicLink (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
VOID ObpProcessDosDeviceSymbolicLink (POBJECT_SYMBOLIC_LINK SymbolicLink, ULONG Action)
Variables
POBJECT_TYPE IoDeviceObjectType
ULONG ObpLUIDDeviceMapsEnabled
Macro Definition Documentation
#define CREATE_SYMBOLIC_LINK 0
Definition at line 53 of file oblink.c.
Referenced by ObpCreateSymbolicLinkName(), and ObpProcessDosDeviceSymbolicLink().
#define DELETE_SYMBOLIC_LINK 1
Definition at line 54 of file oblink.c.
Referenced by ObpDeleteSymbolicLinkName().
#define MAX_DEPTH 16
Definition at line 1101 of file oblink.c.
Function Documentation
NTSTATUS NtCreateSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in PUNICODE_STRING LinkTarget)
Definition at line 57 of file oblink.c.
References _UNICODE_STRING::Buffer, _OBJECT_SYMBOLIC_LINK::CreationTime, _OBJECT_SYMBOLIC_LINK::DosDeviceDriveIndex, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Handle, KdPrint, KeGetPreviousMode, KeQuerySystemTime(), KernelMode, _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _OBJECT_SYMBOLIC_LINK::LinkTargetObject, _OBJECT_SYMBOLIC_LINK::LinkTargetRemaining, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObpSymbolicLinkObjectType, PAGED_CODE, PagedPool, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteHandle, RtlCopyMemory, RtlInitUnicodeString(), Status, STATUS_INVALID_PARAMETER, and STATUS_NO_MEMORY.
Referenced by CreateSystemRootLink(), IopReassignSystemRoot(), and ObpCreateDosDevicesDirectory().
NTSTATUS NtOpenSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 246 of file oblink.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NULL, ObOpenObjectByName(), ObpSymbolicLinkObjectType, PAGED_CODE, ProbeForWriteHandle, and Status.
Referenced by IopReassignSystemRoot(), and IopStoreSystemPartitionInformation().
NTSTATUS NtQuerySymbolicLinkObject (__in HANDLE LinkHandle, __inout PUNICODE_STRING LinkTarget, __out_opt PULONG ReturnedLength)
Definition at line 331 of file oblink.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpLockObject, ObpSymbolicLinkObjectType, ObpUnlockObject, ObReferenceObjectByHandle, PAGED_CODE, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteUlong, ProbeForWriteUshort, RtlCopyMemory, Status, STATUS_BUFFER_TOO_SMALL, and SYMBOLIC_LINK_QUERY.
Referenced by IopReassignSystemRoot(), and IopStoreSystemPartitionInformation().
VOID ObpCreateSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
Definition at line 995 of file oblink.c.
References _UNICODE_STRING::Buffer, CREATE_SYMBOLIC_LINK, _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, _OBJECT_SYMBOLIC_LINK::DosDeviceDriveIndex, _UNICODE_STRING::Length, _OBJECT_HEADER_NAME_INFO::Name, NULL, OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceNameInfo(), and RtlUpcaseUnicodeChar().
Referenced by ObInsertObject().
VOID ObpDeleteSymbolicLink (IN PVOID Object)
Definition at line 915 of file oblink.c.
References _UNICODE_STRING::Buffer, ExFreePool(), _OBJECT_SYMBOLIC_LINK::LinkTarget, NULL, and PAGED_CODE.
Referenced by ObInitSystem().
VOID ObpDeleteSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
Definition at line 962 of file oblink.c.
References DELETE_SYMBOLIC_LINK, and ObpProcessDosDeviceSymbolicLink().
Referenced by ObpDeleteNameCheck(), and ObShutdownSystem().
NTSTATUS ObpParseSymbolicLink (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 503 of file oblink.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _OBJECT_SYMBOLIC_LINK::LinkTargetObject, _OBJECT_SYMBOLIC_LINK::LinkTargetRemaining, NT_SUCCESS, NULL, OB_NAMESPACE_POOL_TYPE, OBJ_NAME_PATH_SEPARATOR, ObReferenceObjectByPointer(), PAGED_CODE, RtlCopyMemory, RtlMoveMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NAME_TOO_LONG, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE, STATUS_REPARSE_OBJECT, UNICODE_NULL, and UNREFERENCED_PARAMETER.
Referenced by ObInitSystem(), and ObpLookupObjectName().
VOID ObpProcessDosDeviceSymbolicLink (POBJECT_SYMBOLIC_LINK SymbolicLink, ULONG Action)
Definition at line 1104 of file oblink.c.
References ALIGNEDNAME::Alignment, _UNICODE_STRING::Buffer, CREATE_SYMBOLIC_LINK, _EPROCESS::DeviceMap, _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, _OBP_LOOKUP_CONTEXT::DirectoryLocked, DOSDEVICE_DRIVE_CALCULATE, DOSDEVICE_DRIVE_CDROM, DOSDEVICE_DRIVE_FIXED, DOSDEVICE_DRIVE_RAMDISK, DOSDEVICE_DRIVE_REMOTE, DOSDEVICE_DRIVE_REMOVABLE, DOSDEVICE_DRIVE_UNKNOWN, _OBJECT_SYMBOLIC_LINK::DosDeviceDriveIndex, _DEVICE_MAP::DosDevicesDirectory, _DEVICE_MAP::DriveMap, _DEVICE_MAP::DriveType, FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_MULTI_UNC_PROVIDER, FILE_DEVICE_NETWORK, FILE_DEVICE_NETWORK_BROWSER, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_NETWORK_REDIRECTOR, FILE_DEVICE_VIRTUAL_DISK, FILE_REMOVABLE_MEDIA, IoRemoteBootClient, _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _OBJECT_SYMBOLIC_LINK::LinkTargetObject, _OBJECT_SYMBOLIC_LINK::LinkTargetRemaining, NULL, ObDereferenceObject(), OBJ_MAX_REPARSE_ATTEMPTS, OBJ_NAME_PATH_SEPARATOR, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpDosDevicesShortName, ObpDosDevicesShortNamePrefix, ObpInitializeLookupContext(), ObpLockDeviceMap, ObpLookupDirectoryEntry(), ObpLUIDDeviceMapsEnabled, ObpReferenceNameInfo(), ObpReleaseLookupContext(), ObpRootDirectoryObject, ObpSymbolicLinkObjectType, ObpUnlockDeviceMap, ObReferenceObject, ObSystemDeviceMap, PsGetCurrentProcess(), _ULARGE_INTEGER::QuadPart, RtlInitUnicodeString(), TRUE, and _OBJECT_HEADER::Type.
Referenced by ObpCreateSymbolicLinkName(), and ObpDeleteSymbolicLinkName().
Variable Documentation
POBJECT_TYPE IoDeviceObjectType
Definition at line 240 of file iodata.c.
Referenced by IoCreateDevice(), and IopCreateObjectTypes().
ULONG ObpLUIDDeviceMapsEnabled
Definition at line 188 of file obinit.c.
Referenced by ObpCreateDosDevicesDirectory(), and ObpProcessDosDeviceSymbolicLink().