Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/amd64.h File Reference
amd64.h File Reference
Macros
#define ExRaiseException RtlRaiseException
#define ExRaiseStatus RtlRaiseStatus
#define HF_ACPI_THMON 0x00400000
#define HF_APIC 0x00000200
#define HF_CFLUSH 0x00080000
#define HF_CMOV 0x00008000
#define HF_CX8 0x00000100
#define HF_DE 0x00000004
#define HF_DS 0x00200000
#define HF_FPU 0x00000001
#define HF_FXSR 0x01000000
#define HF_MCA 0x00004000
#define HF_MCE 0x00000080
#define HF_MMX 0x00800000
#define HF_MSR 0x00000020
#define HF_MTRR 0x00001000
#define HF_PAE 0x00000040
#define HF_PAT 0x00010000
#define HF_PBE 0x80000000
#define HF_PGE 0x00002000
#define HF_PSE 0x00000008
#define HF_PSE2 0x00020000
#define HF_PSN 0x00040000
#define HF_REQUIRED
#define HF_SMT 0x10000000
#define HF_SS 0x08000000
#define HF_SYSENTER 0x00000800
#define HF_THERMMON 0x20000000
#define HF_TSC 0x00000010
#define HF_UNUSED0 0x00000400
#define HF_UNUSED1 0x00100000
#define HF_UNUSED2 0x40000000
#define HF_VME 0x00000002
#define HF_XMMI 0x02000000
#define HF_XMMI64 0x04000000
#define KF_3DNOW 0x00004000
#define KF_AMDK6MTRR 0x00008000
#define KF_CMOV 0x00000008
#define KF_CMPXCHG8B 0x00000080
#define KF_CR4 0x00000004
#define KF_DTS 0x00000200
#define KF_FAST_SYSCALL 0x00001000
#define KF_FXSR 0x00000800
#define KF_GLOBAL_32BIT_EXECUTE 0x40000000
#define KF_GLOBAL_32BIT_NOEXECUTE 0x80000000
#define KF_GLOBAL_PAGE 0x00000010
#define KF_LARGE_PAGE 0x00000020
#define KF_MMX 0x00000100
#define KF_MTRR 0x00000040
#define KF_NOEXECUTE 0x20000000
#define KF_PAT 0x00000400
#define KF_RDTSC 0x00000002
#define KF_REQUIRED
#define KF_SMT 0x00000001
#define KF_XMMI 0x00002000
#define KF_XMMI64 0x00010000
#define XHF_3DNOW 0x80000000
#define XHF_3DNOW_EXT 0x40000000
#define XHF_APIC 0x00000200
#define XHF_CMOV 0x00008000
#define XHF_CX8 0x00000100
#define XHF_DE 0x00000004
#define XHF_FFXSR 0x02000000
#define XHF_FPU 0x00000001
#define XHF_FXSR 0x01000000
#define XHF_LONGMODE 0x20000000
#define XHF_MCA 0x00004000
#define XHF_MCE 0x00000080
#define XHF_MMX_EXT 0x00400000
#define XHF_MMX_INT 0x00800000
#define XHF_MSR 0x00000020
#define XHF_MTRR 0x00001000
#define XHF_NOEXECUTE 0x00100000
#define XHF_PAE 0x00000040
#define XHF_PAT 0x00010000
#define XHF_PGE 0x00002000
#define XHF_PSE 0x00000008
#define XHF_PSE2 0x00020000
#define XHF_SYSCALL 0x00000800
#define XHF_TSC 0x00000010
#define XHF_UNUSED0 0x00000400
#define XHF_UNUSED1 0x00040000
#define XHF_UNUSED2 0x00080000
#define XHF_UNUSED3 0x00200000
#define XHF_UNUSED5 0x04000000
#define XHF_UNUSED6 0x08000000
#define XHF_UNUSED7 0x10000000
#define XHF_VME 0x00000002
Functions
__forceinline VOID KeAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
__forceinline KIRQL KeAcquireSpinLockRaiseToDpc (__inout PKSPIN_LOCK SpinLock)
__forceinline KIRQL KeAcquireSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock)
VOID KeOptimizeProcessorControlState (VOID)
__forceinline VOID KeReleaseSpinLock (__inout PKSPIN_LOCK SpinLock, __in KIRQL OldIrql)
__forceinline VOID KeReleaseSpinLockFromDpcLevel (__inout PKSPIN_LOCK SpinLock)
__forceinline BOOLEAN KeTestSpinLock (__in PKSPIN_LOCK SpinLock)
__forceinline BOOLEAN KeTryToAcquireSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKIRQL OldIrql)
__forceinline BOOLEAN KeTryToAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
__forceinline PKSPIN_LOCK_QUEUE KiGetLockQueue (VOID)
__forceinline VOID KxAcquireSpinLock (__inout PKSPIN_LOCK SpinLock)
__forceinline VOID KxReleaseSpinLock (__inout PKSPIN_LOCK SpinLock)
__forceinline BOOLEAN KxTryToAcquireSpinLock (__inout PKSPIN_LOCK SpinLock)
ULONG64 KxWaitForSpinLockAndAcquire (__inout PKSPIN_LOCK SpinLock)
Macro Definition Documentation
#define ExRaiseException RtlRaiseException
Definition at line 46 of file amd64.h.
#define ExRaiseStatus RtlRaiseStatus
Definition at line 47 of file amd64.h.
#define HF_ACPI_THMON 0x00400000
Definition at line 4172 of file amd64.h.
#define HF_APIC 0x00000200
Definition at line 4159 of file amd64.h.
#define HF_CFLUSH 0x00080000
Definition at line 4169 of file amd64.h.
#define HF_CMOV 0x00008000
Definition at line 4165 of file amd64.h.
#define HF_CX8 0x00000100
Definition at line 4158 of file amd64.h.
#define HF_DE 0x00000004
Definition at line 4152 of file amd64.h.
#define HF_DS 0x00200000
Definition at line 4171 of file amd64.h.
Referenced by KiSetFeatureBits().
#define HF_FPU 0x00000001
Definition at line 4150 of file amd64.h.
#define HF_FXSR 0x01000000
Definition at line 4174 of file amd64.h.
#define HF_MCA 0x00004000
Definition at line 4164 of file amd64.h.
#define HF_MCE 0x00000080
Definition at line 4157 of file amd64.h.
#define HF_MMX 0x00800000
Definition at line 4173 of file amd64.h.
#define HF_MSR 0x00000020
Definition at line 4155 of file amd64.h.
#define HF_MTRR 0x00001000
Definition at line 4162 of file amd64.h.
#define HF_PAE 0x00000040
Definition at line 4156 of file amd64.h.
#define HF_PAT 0x00010000
Definition at line 4166 of file amd64.h.
#define HF_PBE 0x80000000
Definition at line 4181 of file amd64.h.
#define HF_PGE 0x00002000
Definition at line 4163 of file amd64.h.
#define HF_PSE 0x00000008
Definition at line 4153 of file amd64.h.
#define HF_PSE2 0x00020000
Definition at line 4167 of file amd64.h.
#define HF_PSN 0x00040000
Definition at line 4168 of file amd64.h.
#define HF_REQUIRED
Value:
(HF_FPU | HF_DE | HF_PSE | HF_TSC | HF_MSR |             \
                     HF_PAE | HF_MCE | HF_CX8 | HF_APIC | HF_MTRR |          \
                     HF_PGE | HF_MCA | HF_CMOV | HF_PAT | HF_MMX |           \
                     HF_FXSR |  HF_XMMI | HF_XMMI64 | HF_CFLUSH)
Definition at line 4187 of file amd64.h.
Referenced by KiSetFeatureBits().
#define HF_SMT 0x10000000
Definition at line 4178 of file amd64.h.
Referenced by KiSetFeatureBits().
#define HF_SS 0x08000000
Definition at line 4177 of file amd64.h.
#define HF_SYSENTER 0x00000800
Definition at line 4161 of file amd64.h.
#define HF_THERMMON 0x20000000
Definition at line 4179 of file amd64.h.
#define HF_TSC 0x00000010
Definition at line 4154 of file amd64.h.
#define HF_UNUSED0 0x00000400
Definition at line 4160 of file amd64.h.
#define HF_UNUSED1 0x00100000
Definition at line 4170 of file amd64.h.
#define HF_UNUSED2 0x40000000
Definition at line 4180 of file amd64.h.
#define HF_VME 0x00000002
Definition at line 4151 of file amd64.h.
#define HF_XMMI 0x02000000
Definition at line 4175 of file amd64.h.
#define HF_XMMI64 0x04000000
Definition at line 4176 of file amd64.h.
#define KF_3DNOW 0x00004000
Definition at line 4130 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeKernel(), and KiSetFeatureBits().
#define KF_AMDK6MTRR 0x00008000
Definition at line 4131 of file amd64.h.
Referenced by KeRestoreMtrr(), KeSetPhysicalCacheTypeRange(), KiGetFeatureBits(), KiInitMachineDependent(), and KiLoadMTRR().
#define KF_CMOV 0x00000008
Definition at line 4119 of file amd64.h.
Referenced by KiGetFeatureBits().
#define KF_CMPXCHG8B 0x00000080
Definition at line 4123 of file amd64.h.
Referenced by KiGetFeatureBits(), and KiInitializeKernel().
#define KF_CR4 0x00000004
Definition at line 4118 of file amd64.h.
Referenced by KiGetFeatureBits().
#define KF_DTS 0x00000200
Definition at line 4125 of file amd64.h.
Referenced by KiGetFeatureBits(), and KiSetFeatureBits().
#define KF_FAST_SYSCALL 0x00001000
Definition at line 4128 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeKernel(), KiRestoreFastSyscallReturnState(), and PspLookupKernelUserEntryPoints().
#define KF_FXSR 0x00000800
Definition at line 4127 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeKernel(), and KiInitMachineDependent().
#define KF_GLOBAL_32BIT_EXECUTE 0x40000000
Definition at line 4134 of file amd64.h.
Referenced by KiDispatchException(), KiInitializeKernel(), and MmAccessFault().
#define KF_GLOBAL_32BIT_NOEXECUTE 0x80000000
Definition at line 4135 of file amd64.h.
Referenced by KiDispatchException(), KiInitializeKernel(), and MmAccessFault().
#define KF_GLOBAL_PAGE 0x00000010
Definition at line 4120 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeKernel(), KiInitMachineDependent(), and MiInitMachineDependent().
#define KF_LARGE_PAGE 0x00000020
Definition at line 4121 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitMachineDependent(), MiCreatePagingFileMap(), MiFindLargePageMemory(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiInsertPageInList(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiMapWithLargePages(), MiUseLargeDriverPage(), MmInitSystem(), and NtAllocateVirtualMemory().
#define KF_MMX 0x00000100
Definition at line 4124 of file amd64.h.
Referenced by KiGetFeatureBits(), and KiInitializeKernel().
#define KF_MTRR 0x00000040
Definition at line 4122 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeKernel(), KiInitializeMTRR(), and KiInitMachineDependent().
#define KF_NOEXECUTE 0x20000000
Definition at line 4133 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeKernel(), and KiSetFeatureBits().
#define KF_PAT 0x00000400
Definition at line 4126 of file amd64.h.
Referenced by KeRestorePAT(), KiGetFeatureBits(), KiInitializeKernel(), KiInitializePAT(), KiInitMachineDependent(), and MiInitMachineDependent().
#define KF_RDTSC 0x00000002
Definition at line 4117 of file amd64.h.
Referenced by KiGetFeatureBits(), KiInitializeInterruptTimers(), KiInitializeKernel(), and KiInitMachineDependent().
#define KF_REQUIRED
Value:
(KF_RDTSC | KF_CR4 | KF_CMOV | KF_GLOBAL_PAGE |          \
                     KF_LARGE_PAGE | KF_MTRR | KF_CMPXCHG8B | KF_MMX |       \
                     KF_PAT | KF_FXSR | KF_FAST_SYSCALL | KF_XMMI |          \
                     KF_XMMI64)
Definition at line 4141 of file amd64.h.
Referenced by KiSetFeatureBits().
#define KF_SMT 0x00000001
Definition at line 4116 of file amd64.h.
#define KF_XMMI 0x00002000
Definition at line 4129 of file amd64.h.
Referenced by KiGetFeatureBits(), and KiInitializeKernel().
#define KF_XMMI64 0x00010000
Definition at line 4132 of file amd64.h.
Referenced by KiGetFeatureBits(), and KiInitializeKernel().
#define XHF_3DNOW 0x80000000
Definition at line 4227 of file amd64.h.
Referenced by KiSetFeatureBits().
#define XHF_3DNOW_EXT 0x40000000
Definition at line 4226 of file amd64.h.
#define XHF_APIC 0x00000200
Definition at line 4205 of file amd64.h.
#define XHF_CMOV 0x00008000
Definition at line 4211 of file amd64.h.
#define XHF_CX8 0x00000100
Definition at line 4204 of file amd64.h.
#define XHF_DE 0x00000004
Definition at line 4198 of file amd64.h.
#define XHF_FFXSR 0x02000000
Definition at line 4221 of file amd64.h.
Referenced by KeRestoreProcessorSpecificFeatures(), and KiSetFeatureBits().
#define XHF_FPU 0x00000001
Definition at line 4196 of file amd64.h.
#define XHF_FXSR 0x01000000
Definition at line 4220 of file amd64.h.
#define XHF_LONGMODE 0x20000000
Definition at line 4225 of file amd64.h.
#define XHF_MCA 0x00004000
Definition at line 4210 of file amd64.h.
#define XHF_MCE 0x00000080
Definition at line 4203 of file amd64.h.
#define XHF_MMX_EXT 0x00400000
Definition at line 4218 of file amd64.h.
#define XHF_MMX_INT 0x00800000
Definition at line 4219 of file amd64.h.
#define XHF_MSR 0x00000020
Definition at line 4201 of file amd64.h.
#define XHF_MTRR 0x00001000
Definition at line 4208 of file amd64.h.
#define XHF_NOEXECUTE 0x00100000
Definition at line 4216 of file amd64.h.
Referenced by KiSetFeatureBits().
#define XHF_PAE 0x00000040
Definition at line 4202 of file amd64.h.
#define XHF_PAT 0x00010000
Definition at line 4212 of file amd64.h.
#define XHF_PGE 0x00002000
Definition at line 4209 of file amd64.h.
#define XHF_PSE 0x00000008
Definition at line 4199 of file amd64.h.
#define XHF_PSE2 0x00020000
Definition at line 4213 of file amd64.h.
#define XHF_SYSCALL 0x00000800
Definition at line 4207 of file amd64.h.
Referenced by KiSetFeatureBits().
#define XHF_TSC 0x00000010
Definition at line 4200 of file amd64.h.
#define XHF_UNUSED0 0x00000400
Definition at line 4206 of file amd64.h.
#define XHF_UNUSED1 0x00040000
Definition at line 4214 of file amd64.h.
#define XHF_UNUSED2 0x00080000
Definition at line 4215 of file amd64.h.
#define XHF_UNUSED3 0x00200000
Definition at line 4217 of file amd64.h.
#define XHF_UNUSED5 0x04000000
Definition at line 4222 of file amd64.h.
#define XHF_UNUSED6 0x08000000
Definition at line 4223 of file amd64.h.
#define XHF_UNUSED7 0x10000000
Definition at line 4224 of file amd64.h.
#define XHF_VME 0x00000002
Definition at line 4197 of file amd64.h.
Function Documentation
__forceinline VOID KeAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
Definition at line 3858 of file amd64.h.
References KxAcquireSpinLock().
Referenced by KeAcquireInterruptSpinLock(), KeFreezeExecution(), KeInvalidateAllCaches(), KeIpiGenericCall(), KeStartProfile(), KeStopProfile(), KiAcquireSpinLockForDpc(), KiExecuteDpc(), KiLockStepOtherProcessors(), KiRetireDpcList(), WmipMceDelivery(), and WmipMceEventDelivery().
__forceinline KIRQL KeAcquireSpinLockRaiseToDpc (__inout PKSPIN_LOCK SpinLock)
Definition at line 3786 of file amd64.h.
References DISPATCH_LEVEL, KfRaiseIrql(), and KxAcquireSpinLock().
__forceinline KIRQL KeAcquireSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock)
Definition at line 3822 of file amd64.h.
References KfRaiseIrql(), KxAcquireSpinLock(), and SYNCH_LEVEL.
Referenced by MiCheckSystemPteProtection(), and MmProtectMdlSystemAddress().
VOID KeOptimizeProcessorControlState (VOID)
Definition at line 2891 of file kernlini.c.
Referenced by CmpConfigureProcessors().
__forceinline VOID KeReleaseSpinLock (__inout PKSPIN_LOCK SpinLock, __in KIRQL OldIrql)
Definition at line 3933 of file amd64.h.
References KeLowerIrql, and KxReleaseSpinLock().
Referenced by ExNotifyCallback(), ExRegisterCallback(), ExUnregisterCallback(), IoWMIWriteEvent(), KeDeregisterNmiCallback(), KeRegisterNmiCallback(), KeReleaseSpinLockEx(), KeRestoreMtrr(), KeSetPhysicalCacheTypeRange(), KiAmdK6InitializeMTRR(), KiAmdK6MtrrSetMemoryType(), KiCompleteEffectiveRangeChange(), KiInitializeKernel(), KiInitializePAT(), KiReleaseSpinLockForDpc(), MiCheckSystemPteProtection(), MmProtectMdlSystemAddress(), RtlpTraceDatabaseReleaseLock(), and WmipInsertQueueMCEDpc().
__forceinline VOID KeReleaseSpinLockFromDpcLevel (__inout PKSPIN_LOCK SpinLock)
Definition at line 3966 of file amd64.h.
References KxReleaseSpinLock().
Referenced by KeInvalidateAllCaches(), KeIpiGenericCall(), KeReleaseInterruptSpinLock(), KeStartProfile(), KeStopProfile(), KiExecuteDpc(), KiLockStepOtherProcessors(), KiProcessNMI(), KiReleaseSpinLockForDpc(), KiRetireDpcList(), WmipMceDelivery(), and WmipMceEventDelivery().
__forceinline BOOLEAN KeTestSpinLock (__in PKSPIN_LOCK SpinLock)
Definition at line 3994 of file amd64.h.
References FALSE, KeMemoryBarrierWithoutFence, KeYieldProcessor, and TRUE.
__forceinline BOOLEAN KeTryToAcquireSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKIRQL OldIrql)
Definition at line 4031 of file amd64.h.
References DISPATCH_LEVEL, FALSE, KeLowerIrql, KfRaiseIrql(), KxTryToAcquireSpinLock(), and TRUE.
Referenced by MiTrimAllSystemPageableMemory().
__forceinline BOOLEAN KeTryToAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
Definition at line 4076 of file amd64.h.
References KxTryToAcquireSpinLock().
Referenced by KeFreezeExecution().
__forceinline PKSPIN_LOCK_QUEUE KiGetLockQueue (VOID)
Definition at line 3776 of file amd64.h.
References FIELD_OFFSET.
Referenced by KeAcquireQueuedSpinLock(), KeAcquireQueuedSpinLockRaiseToSynch(), KeReleaseQueuedSpinLock(), KeTryToAcquireQueuedSpinLock(), KeTryToAcquireQueuedSpinLockRaiseToSynch(), KiAcquireDispatcherLockAtSynchLevel(), KiAcquireDispatcherLockRaiseToSynch(), KiReleaseDispatcherLockFromSynchLevel(), and KiTryToAcquireDispatcherLockRaiseToSynch().
__forceinline VOID KxAcquireSpinLock (__inout PKSPIN_LOCK SpinLock)
Definition at line 3659 of file amd64.h.
References InterlockedCompareExchange64, KeGetCurrentThread(), KxWaitForSpinLockAndAcquire(), and UNREFERENCED_PARAMETER.
Referenced by KeAcquireSpinLockAtDpcLevel(), KeAcquireSpinLockRaiseToDpc(), and KeAcquireSpinLockRaiseToSynch().
__forceinline VOID KxReleaseSpinLock (__inout PKSPIN_LOCK SpinLock)
Definition at line 3890 of file amd64.h.
References ASSERT, KeGetCurrentThread(), and UNREFERENCED_PARAMETER.
Referenced by KeReleaseSpinLock(), and KeReleaseSpinLockFromDpcLevel().
__forceinline BOOLEAN KxTryToAcquireSpinLock (__inout PKSPIN_LOCK SpinLock)
Definition at line 3711 of file amd64.h.
References FALSE, InterlockedCompareExchange64, KeGetCurrentThread(), KeYieldProcessor, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeTryToAcquireSpinLock(), KeTryToAcquireSpinLockAtDpcLevel(), and KiAcquireSpinLockCheckForFreeze().
ULONG64 KxWaitForSpinLockAndAcquire (__inout PKSPIN_LOCK SpinLock)
Definition at line 96 of file spinlock.c.
References InterlockedCompareExchange64, KeGetCurrentThread(), and KeYieldProcessor.
Referenced by KxAcquireSpinLock().