Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/vadtree.c File Reference
vadtree.c File Reference
#include "mi.h"
Functions
LOGICAL MiCheckForConflictingVadExistence (IN PEPROCESS Process, IN PVOID StartingAddress, IN PVOID EndingAddress)
NTSTATUS MiFindEmptyAddressRange (IN SIZE_T SizeOfRange, IN ULONG_PTR Alignment, IN ULONG QuickCheck, IN PVOID *Base)
NTSTATUS MiInsertVadCharges (IN PMMVAD Vad, IN PEPROCESS CurrentProcess)
VOID MiRemoveVadCharges (IN PMMVAD Vad, IN PEPROCESS CurrentProcess)
BOOLEAN MmCheckForSafeExecution (IN PVOID InstructionPointer, IN PVOID StackPointer, IN PVOID BranchTarget, IN BOOLEAN PermitStackExecution)
PFILE_OBJECT * MmPerfVadTreeWalk (IN PEPROCESS TargetProcess)
VOID VadTreeWalk (VOID)
Function Documentation
LOGICAL MiCheckForConflictingVadExistence (IN PEPROCESS Process, IN PVOID StartingAddress, IN PVOID EndingAddress)
Definition at line 659 of file vadtree.c.
References FALSE, MiCheckForConflictingVad, NULL, and TRUE.
Referenced by MiCreatePebOrTeb(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), and NtAllocateVirtualMemory().
NTSTATUS MiFindEmptyAddressRange (IN SIZE_T SizeOfRange, IN ULONG_PTR Alignment, IN ULONG QuickCheck, IN PVOID * Base)
Definition at line 495 of file vadtree.c.
References _RTL_BITMAP::Buffer, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMVAD::EndingVpn, MI_ROUND_TO_64K, MI_ROUND_TO_SIZE, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiCheckForConflictingVad, MiFindEmptyAddressRangeInTree(), MiGetNextVad, MiLastVadBit, MM_HIGHEST_USER_ADDRESS, MmWorkingSetList, NO_BITS_FOUND, NULL, PsGetCurrentProcess(), RtlFindClearBits(), _RTL_BITMAP::SizeOfBitMap, _MMVAD::StartingVpn, Status, STATUS_SUCCESS, VAD_BITMAP_SPACE, _EPROCESS::VadFreeHint, _EPROCESS::VadRoot, and X64K.
Referenced by MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), and NtAllocateVirtualMemory().
NTSTATUS MiInsertVadCharges (IN PMMVAD Vad, IN PEPROCESS CurrentProcess)
Definition at line 42 of file vadtree.c.
References ASSERT, ASSERT32, _RTL_BITMAP::Buffer, FALSE, MI_64K_ALIGN, MI_CHECK_BIT, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_SET_BIT, MI_VA_TO_VPN, MI_VPN_TO_VA, MiChargeCommitment(), MiGetPdeIndex, MiGetPpeIndex, MiGetPxeIndex, MiLastVadBit, MM_DBG_COMMIT_INSERT_VAD, MM_DBG_COMMIT_INSERT_VAD_PT, MM_MAX_COMMIT, MM_TRACK_COMMIT, MmWorkingSetList, NT_SUCCESS, NULL, PD_PER_SYSTEM, PDE_PER_PAGE, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PsChangeJobMemoryUsage(), PsChargeProcessNonPagedPoolQuota(), PsChargeProcessPagedPoolQuota(), PsChargeProcessPageFileQuota(), PsGetCurrentProcess(), PsReportProcessMemoryLimitViolation(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), PsReturnProcessPageFileQuota(), PTE_SHIFT, RtlSetBits(), _RTL_BITMAP::SizeOfBitMap, Status, STATUS_COMMITMENT_LIMIT, STATUS_SUCCESS, TRUE, VAD_BITMAP_SPACE, and X64K.
Referenced by MiCloneProcessAddressSpace(), MiCreatePebOrTeb(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
VOID MiRemoveVadCharges (IN PMMVAD Vad, IN PEPROCESS CurrentProcess)
Definition at line 395 of file vadtree.c.
References ASSERT, CONTAINING_RECORD, ExFreePool(), _LIST_ENTRY::Flink, List, _MMSECURE_ENTRY::List, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MiGetPreviousVad, MiReturnCommitment, MM_ANY_WS_LOCK_HELD, MM_DBG_COMMIT_RETURN_VAD, MM_MAX_COMMIT, MM_TRACK_COMMIT, NULL, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PsChangeJobMemoryUsage(), PsGetCurrentProcess(), PsGetCurrentThread(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), PsReturnProcessPageFileQuota(), and PTE_SHIFT.
Referenced by MiMapViewOfPhysicalSection(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MmCleanProcessAddressSpace(), MmDeleteTeb(), NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
BOOLEAN MmCheckForSafeExecution (IN PVOID InstructionPointer, IN PVOID StackPointer, IN PVOID BranchTarget, IN BOOLEAN PermitStackExecution)
Definition at line 803 of file vadtree.c.
References FALSE, LOCK_ADDRESS_SPACE, MiLocateAddress(), NULL, PsGetCurrentProcess(), TRUE, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNREFERENCED_PARAMETER, _MMVAD::VadFlags, VadImageMap, and _MMVAD_FLAGS::VadType.
Referenced by KiEmulateAtlThunk().
PFILE_OBJECT* MmPerfVadTreeWalk (IN PEPROCESS TargetProcess)
Definition at line 699 of file vadtree.c.
References ASSERT, _MMVAD::ControlArea, ExAllocatePoolWithTag, _CONTROL_AREA::FilePointer, KeGetCurrentIrql(), LOCK_ADDRESS_SPACE, MiEnumerateGenericTableWithoutSplayingAvl(), NULL, _MM_AVL_TABLE::NumberGenericTableElements, ObReferenceObject, PagedPool, PASSIVE_LEVEL, _MMVAD_FLAGS::PrivateMemory, TRUE, _MMVAD::u, UNLOCK_ADDRESS_SPACE, and _MMVAD::VadFlags.
VOID VadTreeWalk (VOID)