Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcclose.c File Reference
lpcclose.c File Reference
#include "lpcp.h"
Functions
VOID LpcExitThread (PETHREAD Thread)
VOID LpcpClosePort (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID LpcpDeletePort (IN PVOID Object)
Function Documentation
VOID LpcExitThread (PETHREAD Thread)
Definition at line 355 of file lpcclose.c.
References ASSERT, _LPCP_MESSAGE::Entry, IsListEmpty, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLockByThread, LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, NULL, ObDereferenceObject(), PsGetCurrentThread(), RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, and TRUE.
Referenced by PspExitThread().
VOID LpcpClosePort (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 30 of file lpcclose.c.
References FALSE, _LPCP_PORT_OBJECT::Flags, LpcpDestroyPortQueue(), PORT_TYPE, SERVER_CONNECTION_PORT, TRUE, and UNREFERENCED_PARAMETER.
Referenced by LpcInitSystem().
VOID LpcpDeletePort (IN PVOID Object)
Definition at line 113 of file lpcclose.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ClientSectionBase, _LPCP_PORT_OBJECT::ClientThread, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, CONTAINING_RECORD, _LPC_CLIENT_DIED_MSG::CreateTime, _EPROCESS::CreateTime, _LPCP_MESSAGE::Entry, FALSE, _LPCP_PORT_OBJECT::Flags, _LIST_ENTRY::Flink, InitializeListHead(), KeDelayExecutionThread(), KernelMode, LPC_PORT_CLOSED, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LPCP_MUTEX_OWNED, LpcpAcquireLpcpLockByThread, LpcpDestroyPortQueue(), LpcpFreePortClientSecurity(), LpcpFreeToPortZone(), LpcpReleaseLpcpLock, LpcpTrace, LpcRequestPort(), _LPCP_PORT_OBJECT::MappingProcess, _PORT_MESSAGE::MessageId, MmUnmapViewOfSection(), NULL, ObDereferenceObject(), PAGED_CODE, PORT_TYPE, _LPC_CLIENT_DIED_MSG::PortMsg, PsGetCurrentProcess(), PsGetCurrentThread(), RemoveEntryList(), _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, _LPCP_PORT_OBJECT::ServerProcess, _LPCP_PORT_OBJECT::ServerSectionBase, Status, STATUS_NO_MEMORY, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, and _CLIENT_ID::UniqueProcess.
Referenced by LpcInitSystem().