Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obdir.c File Reference
obdir.c File Reference
#include "obp.h"
#include <stdio.h>
Macros
#define INVALID_HASH_INDEX 0xFFFFFFFF
Functions
NTSTATUS NtCreateDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtMakePermanentObject (__in HANDLE Handle)
NTSTATUS NtOpenDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQueryDirectoryObject (__in HANDLE DirectoryHandle, __out_bcount_opt(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in BOOLEAN RestartScan, __inout PULONG Context, __out_opt PULONG ReturnLength)
VOID FASTCALL ObfDereferenceDeviceMap (IN PDEVICE_MAP DeviceMap)
BOOLEAN ObpDeleteDirectoryEntry (IN POBP_LOOKUP_CONTEXT LookupContext)
POBJECT_DIRECTORY ObpGetShadowDirectory (POBJECT_DIRECTORY Dir)
BOOLEAN ObpInsertDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LookupContext, IN POBJECT_HEADER ObjectHeader)
BOOLEAN ObpIsUnsecureName (IN PUNICODE_STRING ObjectName, IN BOOLEAN CaseInsensitive)
VOID ObpLinkDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN ULONG HashIndex, IN POBJECT_DIRECTORY_ENTRY NewDirectoryEntry)
PVOID ObpLookupDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN PUNICODE_STRING Name, IN ULONG Attributes, IN BOOLEAN SearchShadow, OUT POBP_LOOKUP_CONTEXT LookupContext)
NTSTATUS ObpLookupObjectName (IN HANDLE RootDirectoryHandle OPTIONAL, IN PUNICODE_STRING ObjectName, IN ULONG Attributes, IN POBJECT_TYPE ObjectType, IN KPROCESSOR_MODE AccessMode, IN PVOID ParseContext OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, IN PVOID InsertObject OPTIONAL, IN OUT PACCESS_STATE AccessState, OUT POBP_LOOKUP_CONTEXT LookupContext, OUT PVOID *FoundObject)
PDEVICE_MAP ObpReferenceDeviceMap ()
VOID ObpReleaseExclusiveNameLock (IN POBJECT_HEADER ObjectHeader)
VOID ObpReleaseLookupContextObject (IN POBP_LOOKUP_CONTEXT LookupContext)
NTSTATUS ObpSetCurrentProcessDeviceMap ()
POBJECT_HEADER_NAME_INFO ObpTryReferenceNameInfoExclusive (IN POBJECT_HEADER ObjectHeader)
POBJECT_DIRECTORY_ENTRY ObpUnlinkDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN ULONG HashIndex)
NTSTATUS ObSwapObjectNames (IN HANDLE DirectoryHandle, IN HANDLE Handle1, IN HANDLE Handle2, IN ULONG Flags)
NTSTATUS SeGetLogonIdDeviceMap (IN PLUID pLogonId, OUT PDEVICE_MAP *ppDevMap)
Variables
ULONG ObpCaseInsensitive = 1
ULONG ObpLUIDDeviceMapsEnabled
WCHAR ObpUnsecureGlobalNamesBuffer [128] = { 0 }
ULONG ObpUnsecureGlobalNamesLength = sizeof(ObpUnsecureGlobalNamesBuffer)
Macro Definition Documentation
#define INVALID_HASH_INDEX 0xFFFFFFFF
Referenced by ObSwapObjectNames().
Function Documentation
NTSTATUS NtCreateDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 145 of file obdir.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExInitializePushLock(), Handle, KeGetPreviousMode, KernelMode, _OBJECT_DIRECTORY::Lock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), OBJ_INVALID_SESSION_ID, ObpDirectoryObjectType, ObpValidateIrql, PAGED_CODE, ProbeForWriteHandle, RtlZeroMemory, _OBJECT_DIRECTORY::SessionId, and Status.
Referenced by CreateSystemRootLink(), ExpInitializeCallbacks(), IopCreateRootDirectories(), ObInitSystem(), ObpCreateDosDevicesDirectory(), and SepInitializationPhase1().
NTSTATUS NtMakePermanentObject (__in HANDLE Handle)
Definition at line 2881 of file obdir.c.
References _OBJECT_HEADER::Flags, KeGetPreviousMode, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpLockObject, ObpUnlockObject, ObReferenceObjectByHandle, PAGED_CODE, SeCreatePermanentPrivilege, SeSinglePrivilegeCheck(), Status, and STATUS_PRIVILEGE_NOT_HELD.
NTSTATUS NtOpenDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 259 of file obdir.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NULL, ObOpenObjectByName(), ObpDirectoryObjectType, ObpValidateIrql, PAGED_CODE, ProbeForWriteHandle, and Status.
NTSTATUS NtQueryDirectoryObject (__in HANDLE DirectoryHandle, __out_bcount_opt(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in BOOLEAN RestartScan, __inout PULONG Context, __out_opt PULONG ReturnLength)
Definition at line 343 of file obdir.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _OBJECT_DIRECTORY_ENTRY::ChainLink, DIRECTORY_QUERY, ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _OBJECT_DIRECTORY::HashBuckets, KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_DIRECTORY_INFORMATION::Name, _OBJECT_TYPE::Name, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, NUMBER_HASH_BUCKETS, ObDereferenceObject(), _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpIsOverflow, ObpLockDirectoryShared(), ObpUnlockDirectory(), ObpValidateIrql, ObReferenceObjectByHandle, PAGED_CODE, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, ProbeForWrite(), ProbeForWriteUlong, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_MORE_ENTRIES, STATUS_NO_MORE_ENTRIES, STATUS_SUCCESS, _OBJECT_HEADER::Type, _OBJECT_DIRECTORY_INFORMATION::TypeName, and UNICODE_NULL.
VOID FASTCALL ObfDereferenceDeviceMap (IN PDEVICE_MAP DeviceMap)
Definition at line 1661 of file obdir.c.
References ExFreePool(), NULL, ObDereferenceObject(), ObMakeTemporaryObject(), ObpLockDeviceMap, and ObpUnlockDeviceMap.
Referenced by ObDereferenceDeviceMap(), ObpLookupObjectName(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), SeGetLogonIdDeviceMap(), SepDeleteLogonSessionTrack(), and SepDeReferenceLogonSession().
BOOLEAN ObpDeleteDirectoryEntry (IN POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 1291 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, ExFreePool(), FALSE, IN, NULL, and TRUE.
Referenced by ObInsertObject(), and ObpDeleteNameCheck().
POBJECT_DIRECTORY ObpGetShadowDirectory (POBJECT_DIRECTORY Dir)
Definition at line 1350 of file obdir.c.
References _OBJECT_DIRECTORY::DeviceMap, _DEVICE_MAP::GlobalDosDevicesDirectory, NULL, ObpLockDeviceMap, and ObpUnlockDeviceMap.
Referenced by ObpLookupDirectoryEntry().
BOOLEAN ObpInsertDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LookupContext, IN POBJECT_HEADER ObjectHeader)
Definition at line 1186 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, DbgBreakPoint(), DbgPrint(), _OBJECT_HEADER_NAME_INFO::Directory, ExAllocatePoolWithTag, FALSE, _OBJECT_DIRECTORY_ENTRY::HashValue, NULL, _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO_EXISTS(), PagedPool, and TRUE.
Referenced by ObCreateObjectType(), ObInitSystem(), and ObpLookupObjectName().
BOOLEAN ObpIsUnsecureName (IN PUNICODE_STRING ObjectName, IN BOOLEAN CaseInsensitive)
Definition at line 110 of file obdir.c.
References FALSE, _UNICODE_STRING::Length, ObpUnsecureGlobalNamesBuffer, RtlInitUnicodeString(), RtlPrefixUnicodeString(), TRUE, and UNICODE_NULL.
Referenced by ObpLookupObjectName().
VOID ObpLinkDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN ULONG HashIndex, IN POBJECT_DIRECTORY_ENTRY NewDirectoryEntry)
Definition at line 3120 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink.
Referenced by ObSwapObjectNames().
PVOID ObpLookupDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN PUNICODE_STRING Name, IN ULONG Attributes, IN BOOLEAN SearchShadow, OUT POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 822 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, ExTryConvertPushLockSharedToExclusive(), FALSE, _OBJECT_DIRECTORY_ENTRY::HashValue, Index, _OBJECT_HEADER_NAME_INFO::Name, NOTHING, NULL, NUMBER_HASH_BUCKETS, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpGetShadowDirectory(), ObpLockDirectoryShared(), ObpLUIDDeviceMapsEnabled, ObpReferenceNameInfo(), ObpUnlockDirectory(), ObReferenceObject, PAGED_CODE, RtlEqualUnicodeString(), RtlUpcaseUnicodeChar(), and TRUE.
Referenced by ObCreateObjectType(), ObInitSystem(), ObpDeleteNameCheck(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), and ObSwapObjectNames().
NTSTATUS ObpLookupObjectName (IN HANDLE RootDirectoryHandle OPTIONAL, IN PUNICODE_STRING ObjectName, IN ULONG Attributes, IN POBJECT_TYPE ObjectType, IN KPROCESSOR_MODE AccessMode, IN PVOID ParseContext OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, IN PVOID InsertObject OPTIONAL, IN OUT PACCESS_STATE AccessState, OUT POBP_LOOKUP_CONTEXT LookupContext, OUT PVOID * FoundObject)
Definition at line 1691 of file obdir.c.
References ALIGNEDNAME::Alignment, ARGUMENT_PRESENT, ASSERT, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, DIRECTORY_CREATE_OBJECT, DIRECTORY_CREATE_SUBDIRECTORY, DIRECTORY_TRAVERSE, _DEVICE_MAP::DosDevicesDirectory, ExAllocatePoolWithTag, ExFreePool(), FALSE, _ULARGE_INTEGER::HighPart, IoFileObjectType, KernelMode, _UNICODE_STRING::Length, _ULARGE_INTEGER::LowPart, _UNICODE_STRING::MaximumLength, MmSectionObjectType, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, ObCheckCreateObjectAccess(), ObDereferenceObject(), ObfDereferenceDeviceMap(), OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_INVALID_SESSION_ID, OBJ_MAX_REPARSE_ATTEMPTS, OBJ_NAME_PATH_SEPARATOR, OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpCaseInsensitive, ObpCheckTraverseAccess(), ObpDirectoryObjectType, ObpDosDevicesShortName, ObpDosDevicesShortNamePrefix, ObpDosDevicesShortNameRoot, ObpEndTypeSpecificCallOut, ObpIncrPointerCount, ObpInitializeLookupContext(), ObpInsertDirectoryEntry(), ObpIsUnsecureName(), ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpParseSymbolicLink(), ObpReferenceDeviceMap(), ObpReleaseLookupContext(), ObpRootDirectoryObject, ObpSymbolicLinkObjectType, ObpValidateIrql, ObReferenceObject, ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PagedPool, _OBJECT_TYPE_INITIALIZER::ParseProcedure, PsGetCurrentProcessSessionId(), _ULARGE_INTEGER::QuadPart, RtlCopyMemory, SeCreateGlobalPrivilege, SeSinglePrivilegeCheck(), _OBJECT_DIRECTORY::SessionId, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_INVALID, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_PATH_NOT_FOUND, STATUS_OBJECT_PATH_SYNTAX_BAD, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE, STATUS_REPARSE_OBJECT, STATUS_SUCCESS, TOKEN_HAS_TRAVERSE_PRIVILEGE, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UserMode.
Referenced by ObInsertObject(), ObOpenObjectByName(), and ObReferenceObjectByName().
PDEVICE_MAP ObpReferenceDeviceMap ()
Definition at line 1471 of file obdir.c.
References _EPROCESS::DeviceMap, FALSE, _LUID::HighPart, _LUID::LowPart, NT_SUCCESS, NULL, ObpLockDeviceMap, ObpLUIDDeviceMapsEnabled, ObpSetCurrentProcessDeviceMap(), ObpUnlockDeviceMap, ObSystemDeviceMap, PS_IS_THREAD_IMPERSONATING, PsDereferenceImpersonationToken, PsGetCurrentProcess(), PsGetCurrentThread(), PsReferenceImpersonationToken(), _DEVICE_MAP::ReferenceCount, RtlEqualLuid, SeGetLogonIdDeviceMap(), SeQueryAuthenticationIdToken(), Status, STATUS_NO_TOKEN, SYSTEM_LUID, and TRUE.
Referenced by ObpLookupObjectName(), and ObQueryDeviceMapInformation().
VOID ObpReleaseExclusiveNameLock (IN POBJECT_HEADER ObjectHeader)
Definition at line 3042 of file obdir.c.
References InterlockedExchangeAdd(), OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBP_NAME_LOCKED, and _OBJECT_HEADER_NAME_INFO::QueryReferences.
Referenced by ObSwapObjectNames().
VOID ObpReleaseLookupContextObject (IN POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 3168 of file obdir.c.
References NULL, ObDereferenceObject(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, and ObpDereferenceNameInfo().
Referenced by ObSwapObjectNames().
NTSTATUS ObpSetCurrentProcessDeviceMap ()
Definition at line 1371 of file obdir.c.
References _EPROCESS::DeviceMap, NT_SUCCESS, NULL, ObfDereferenceDeviceMap(), ObpLockDeviceMap, ObpUnlockDeviceMap, ObSystemDeviceMap, PsDereferencePrimaryToken, PsGetCurrentProcess(), PsReferencePrimaryToken(), _DEVICE_MAP::ReferenceCount, RtlEqualLuid, SeGetLogonIdDeviceMap(), SeQueryAuthenticationIdToken(), Status, STATUS_NO_TOKEN, STATUS_OBJECT_PATH_INVALID, STATUS_SUCCESS, and SYSTEM_LUID.
Referenced by ObpReferenceDeviceMap().
POBJECT_HEADER_NAME_INFO ObpTryReferenceNameInfoExclusive (IN POBJECT_HEADER ObjectHeader)
Definition at line 2967 of file obdir.c.
References _OBJECT_HEADER_NAME_INFO::Directory, InterlockedCompareExchange(), NULL, OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBP_NAME_KERNEL_PROTECTED, OBP_NAME_LOCKED, _OBJECT_HEADER_NAME_INFO::QueryReferences, and TRUE.
Referenced by ObSwapObjectNames().
POBJECT_DIRECTORY_ENTRY ObpUnlinkDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN ULONG HashIndex)
Definition at line 3070 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, and NULL.
Referenced by ObSwapObjectNames().
NTSTATUS ObSwapObjectNames (IN HANDLE DirectoryHandle, IN HANDLE Handle1, IN HANDLE Handle2, IN ULONG Flags)
Definition at line 3209 of file obdir.c.
References DELETE, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_CREATE_OBJECT, DIRECTORY_CREATE_SUBDIRECTORY, exit(), FALSE, _OBJECT_HEADER::Flags, _OBP_LOOKUP_CONTEXT::HashIndex, _OBJECT_DIRECTORY_ENTRY::HashValue, INVALID_HASH_INDEX, KeGetPreviousMode, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpDeleteNameCheck(), ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpLinkDirectoryEntry(), ObpLockAllObjects(), ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpReferenceNameInfo(), ObpReleaseExclusiveNameLock(), ObpReleaseLookupContext(), ObpReleaseLookupContextObject(), ObpTryReferenceNameInfoExclusive(), ObpUnlinkDirectoryEntry(), ObpUnlockAllObjects(), ObReferenceObjectByHandle, Status, STATUS_LOCK_NOT_GRANTED, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_INVALID, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, _OBJECT_HEADER::Type, and UNREFERENCED_PARAMETER.
NTSTATUS SeGetLogonIdDeviceMap (IN PLUID pLogonId, OUT PDEVICE_MAP * ppDevMap)
Definition at line 1440 of file rmlogon.c.
References _snwprintf, DIRECTORY_ALL_ACCESS, InitializeObjectAttributes, InterlockedIncrement, _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NT_SUCCESS, NULL, ObfDereferenceDeviceMap(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_OPENIF, OBJ_PERMANENT, ObSetDirectoryDeviceMap(), PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, RtlInitUnicodeString(), SepDeReferenceLogonSessionDirect(), SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, Status, STATUS_INVALID_PARAMETER, STATUS_NO_SUCH_LOGON_SESSION, STATUS_SUCCESS, SYMBOLIC_LINK_ALL_ACCESS, ZwClose(), ZwCreateDirectoryObject(), and ZwCreateSymbolicLinkObject().
Referenced by ObpReferenceDeviceMap(), and ObpSetCurrentProcessDeviceMap().
Variable Documentation
ULONG ObpCaseInsensitive = 1
Definition at line 102 of file obdir.c.
Referenced by ObpLookupObjectName().
ULONG ObpLUIDDeviceMapsEnabled
Definition at line 188 of file obinit.c.
Referenced by ObpLookupDirectoryEntry(), and ObpReferenceDeviceMap().
WCHAR ObpUnsecureGlobalNamesBuffer[128] = { 0 }
Definition at line 105 of file obdir.c.
Referenced by ObpIsUnsecureName().
ULONG ObpUnsecureGlobalNamesLength = sizeof(ObpUnsecureGlobalNamesBuffer)
Definition at line 106 of file obdir.c.