Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/addrsup.c File Reference
addrsup.c File Reference
#include "mi.h"
Macros
#define COUNT_BALANCE_MAX(a)
#define MiIsLeftChild(Links)
#define MiIsRightChild(Links)
#define MiParent(Links)
#define PRINT
Functions
PMMADDRESS_NODE MiCheckForConflictingNode (IN ULONG_PTR StartVpn, IN ULONG_PTR EndVpn, IN PMM_AVL_TABLE Table)
PVOID MiEnumerateGenericTableWithoutSplayingAvl (IN PMM_AVL_TABLE Table, IN PVOID *RestartKey)
NTSTATUS MiFindEmptyAddressRangeDownBasedTree (IN SIZE_T SizeOfRange, IN PVOID HighestAddressToEndAt, IN ULONG_PTR Alignment, IN PMM_AVL_TABLE Table, OUT PVOID *Base)
NTSTATUS MiFindEmptyAddressRangeDownTree (IN SIZE_T SizeOfRange, IN PVOID HighestAddressToEndAt, IN ULONG_PTR Alignment, IN PMM_AVL_TABLE Table, OUT PVOID *Base)
NTSTATUS MiFindEmptyAddressRangeInTree (IN SIZE_T SizeOfRange, IN ULONG_PTR Alignment, IN PMM_AVL_TABLE Table, OUT PMMADDRESS_NODE *PreviousVad, OUT PVOID *Base)
TABLE_SEARCH_RESULT MiFindNodeOrParent (IN PMM_AVL_TABLE Table, IN ULONG_PTR StartingVpn, OUT PMMADDRESS_NODE *NodeOrParent)
PMMADDRESS_NODE FASTCALL MiGetFirstNode (IN PMM_AVL_TABLE Table)
PMMADDRESS_NODE FASTCALL MiGetNextNode (IN PMMADDRESS_NODE Node)
PMMADDRESS_NODE FASTCALL MiGetPreviousNode (IN PMMADDRESS_NODE Node)
VOID MiInitializeVadTableAvl (IN PMM_AVL_TABLE Table)
VOID FASTCALL MiInsertNode (IN PMMADDRESS_NODE NodeToInsert, IN PMM_AVL_TABLE Table)
PMMVAD FASTCALL MiLocateAddress (IN PVOID VirtualAddress)
PMMADDRESS_NODE FASTCALL MiLocateAddressInTree (IN ULONG_PTR Vpn, IN PMM_AVL_TABLE Table)
VOID MiPromoteNode (IN PMMADDRESS_NODE C)
PMMADDRESS_NODE MiRealPredecessor (IN PMMADDRESS_NODE Links)
PMMADDRESS_NODE MiRealSuccessor (IN PMMADDRESS_NODE Links)
ULONG MiRebalanceNode (IN PMMADDRESS_NODE S)
VOID FASTCALL MiRemoveNode (IN PMMADDRESS_NODE NodeToDelete, IN PMM_AVL_TABLE Table)
Macro Definition Documentation
#define COUNT_BALANCE_MAX (a)
Definition at line 38 of file addrsup.c.
Referenced by MiInsertNode(), MiRebalanceNode(), and MiRemoveNode().
#define MiIsLeftChild (Links)
Value:
(\
    (RtlLeftChild(MiParent(Links)) == (PRTL_SPLAY_LINKS)(Links)) \
    )
Definition at line 127 of file addrsup.c.
Referenced by MiInsertNode(), MiRealPredecessor(), MiRealSuccessor(), and MiRemoveNode().
#define MiIsRightChild (Links)
Value:
(\
    (RtlRightChild(MiParent(Links)) == (PRTL_SPLAY_LINKS)(Links)) \
    )
Definition at line 142 of file addrsup.c.
Referenced by MiRealPredecessor(), MiRealSuccessor(), and MiRemoveNode().
#define MiParent (Links)
Value:
(\
    (PRTL_SPLAY_LINKS)(SANITIZE_PARENT_NODE((Links)->u1.Parent)) \
    )
Definition at line 112 of file addrsup.c.
#define PRINT
Definition at line 37 of file addrsup.c.
Referenced by MiFindEmptyAddressRangeDownBasedTree(), MiInsertNode(), MiRebalanceNode(), and MiRemoveNode().
Function Documentation
PMMADDRESS_NODE MiCheckForConflictingNode (IN ULONG_PTR StartVpn, IN ULONG_PTR EndVpn, IN PMM_AVL_TABLE Table)
Definition at line 343 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::EndingVpn, _MMADDRESS_NODE::LeftChild, NULL, _MMADDRESS_NODE::RightChild, and TRUE.
PVOID MiEnumerateGenericTableWithoutSplayingAvl (IN PMM_AVL_TABLE Table, IN PVOID * RestartKey)
Definition at line 1495 of file addrsup.c.
References _MMADDRESS_NODE::LeftChild, MiRealSuccessor(), NOTHING, NULL, and _MMADDRESS_NODE::RightChild.
Referenced by MiCloneProcessAddressSpace(), MiRemoveUserPhysicalPagesVad(), and MmPerfVadTreeWalk().
NTSTATUS MiFindEmptyAddressRangeDownBasedTree (IN SIZE_T SizeOfRange, IN PVOID HighestAddressToEndAt, IN ULONG_PTR Alignment, IN PMM_AVL_TABLE Table, OUT PVOID * Base)
Definition at line 2137 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::EndingVpn, MI_ALIGN_TO_SIZE, MI_ROUND_TO_SIZE, MiGetPreviousNode(), MM_HIGHEST_VAD_ADDRESS, MM_LOWEST_USER_ADDRESS, NULL, PAGE_SIZE, PRINT, _MMADDRESS_NODE::RightChild, _MMADDRESS_NODE::StartingVpn, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by MmCreateSection().
NTSTATUS MiFindEmptyAddressRangeDownTree (IN SIZE_T SizeOfRange, IN PVOID HighestAddressToEndAt, IN ULONG_PTR Alignment, IN PMM_AVL_TABLE Table, OUT PVOID * Base)
Definition at line 1933 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::EndingVpn, MI_ALIGN_TO_SIZE, MI_ROUND_TO_SIZE, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiGetPreviousNode(), MM_HIGHEST_VAD_ADDRESS, MM_LOWEST_USER_ADDRESS, NULL, PAGE_SHIFT, PAGE_SIZE, _MMADDRESS_NODE::RightChild, _MMADDRESS_NODE::StartingVpn, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
NTSTATUS MiFindEmptyAddressRangeInTree (IN SIZE_T SizeOfRange, IN ULONG_PTR Alignment, IN PMM_AVL_TABLE Table, OUT PMMADDRESS_NODE * PreviousVad, OUT PVOID * Base)
Definition at line 1797 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::EndingVpn, _MMADDRESS_NODE::LeftChild, MI_ROUND_TO_SIZE, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiGetNextNode(), MM_HIGHEST_VAD_ADDRESS, MM_LOWEST_USER_ADDRESS, NULL, PAGE_SHIFT, PAGE_SIZE, _MMADDRESS_NODE::RightChild, _MMADDRESS_NODE::StartingVpn, STATUS_NO_MEMORY, STATUS_SUCCESS, TRUE, and X64K.
Referenced by MiFindEmptyAddressRange().
TABLE_SEARCH_RESULT MiFindNodeOrParent (IN PMM_AVL_TABLE Table, IN ULONG_PTR StartingVpn, OUT PMMADDRESS_NODE * NodeOrParent)
Definition at line 213 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::LeftChild, NULL, _MMADDRESS_NODE::RightChild, TableEmptyTree, TableFoundNode, TableInsertAsLeft, and TableInsertAsRight.
Referenced by MiAweViewRemover(), MiCaptureWriteWatchDirtyBit(), MiGetWorkingSetInfoList(), MiInsertNode(), MiLocateAddress(), MiLocateAddressInTree(), MiPhysicalViewAdjuster(), MiPhysicalViewRemover(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtGetWriteWatch(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), and NtResetWriteWatch().
PMMADDRESS_NODE FASTCALL MiGetFirstNode (IN PMM_AVL_TABLE Table)
Definition at line 410 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::LeftChild, NULL, and _MMADDRESS_NODE::RightChild.
PMMADDRESS_NODE FASTCALL MiGetNextNode (IN PMMADDRESS_NODE Node)
Definition at line 1594 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::LeftChild, NULL, _MMADDRESS_NODE::Parent, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, TRUE, and _MMADDRESS_NODE::u1.
Referenced by MiFindEmptyAddressRangeInTree().
PMMADDRESS_NODE FASTCALL MiGetPreviousNode (IN PMMADDRESS_NODE Node)
Definition at line 1674 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::LeftChild, NULL, _MMADDRESS_NODE::Parent, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, and _MMADDRESS_NODE::u1.
Referenced by MiFindEmptyAddressRangeDownBasedTree(), and MiFindEmptyAddressRangeDownTree().
VOID MiInitializeVadTableAvl (IN PMM_AVL_TABLE Table)
Definition at line 1253 of file addrsup.c.
References ASSERT, MI_MAKE_PARENT, and RtlZeroMemory.
VOID FASTCALL MiInsertNode (IN PMMADDRESS_NODE NodeToInsert, IN PMM_AVL_TABLE Table)
Definition at line 1295 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::Balance, COUNT_BALANCE_MAX, _MMADDRESS_NODE::LeftChild, MAXULONG, MiFindNodeOrParent(), MiIsLeftChild, MiRebalanceNode(), NULL, _MMADDRESS_NODE::Parent, PRINT, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, TableEmptyTree, TableFoundNode, TableInsertAsLeft, TRUE, and _MMADDRESS_NODE::u1.
Referenced by MiAweViewInserter(), MiCloneProcessAddressSpace(), MiInsertBasedSection(), MiInsertPhysicalViewAndRefControlArea(), MiInsertVad(), MiMapLockedPagesInUserSpace(), and NtAllocateVirtualMemory().
PMMVAD FASTCALL MiLocateAddress (IN PVOID VirtualAddress)
Definition at line 2334 of file addrsup.c.
References ASSERT, MI_VA_TO_VPN, MiFindNodeOrParent(), _MM_AVL_TABLE::NodeHint, NULL, PsGetCurrentProcess(), _MMVAD::StartingVpn, TableFoundNode, and _EPROCESS::VadRoot.
Referenced by MiCheckVirtualAddress(), MiDispatchFault(), MiGetWorkingSetInfoList(), MiResolvePageFileFault(), MiSecureVirtualMemory(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MiUnsecureVirtualMemory(), MmCheckForSafeExecution(), MmDeleteTeb(), MmFlushVirtualMemory(), MmGetFileNameForAddress(), MmMapUserAddressesToPage(), MmSetBankedSection(), NtAreMappedFilesTheSame(), NtFreeVirtualMemory(), NtLockVirtualMemory(), and NtUnlockVirtualMemory().
PMMADDRESS_NODE FASTCALL MiLocateAddressInTree (IN ULONG_PTR Vpn, IN PMM_AVL_TABLE Table)
Definition at line 1748 of file addrsup.c.
References MiFindNodeOrParent(), NULL, and TableFoundNode.
VOID MiPromoteNode (IN PMMADDRESS_NODE C)
Definition at line 452 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::Balance, _MMADDRESS_NODE::LeftChild, MI_MAKE_PARENT, NULL, _MMADDRESS_NODE::Parent, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, and _MMADDRESS_NODE::u1.
Referenced by MiRebalanceNode().
PMMADDRESS_NODE MiRealPredecessor (IN PMMADDRESS_NODE Links)
Definition at line 1161 of file addrsup.c.
References _MMADDRESS_NODE::LeftChild, MiIsLeftChild, MiIsRightChild, NULL, _MMADDRESS_NODE::Parent, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, and _MMADDRESS_NODE::u1.
PMMADDRESS_NODE MiRealSuccessor (IN PMMADDRESS_NODE Links)
Definition at line 1071 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::LeftChild, MiIsLeftChild, MiIsRightChild, NULL, _MMADDRESS_NODE::Parent, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, and _MMADDRESS_NODE::u1.
Referenced by MiEnumerateGenericTableWithoutSplayingAvl().
ULONG MiRebalanceNode (IN PMMADDRESS_NODE S)
Definition at line 584 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::Balance, COUNT_BALANCE_MAX, FALSE, _MMADDRESS_NODE::LeftChild, MiPromoteNode(), PRINT, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, TRUE, and _MMADDRESS_NODE::u1.
Referenced by MiInsertNode(), and MiRemoveNode().
VOID FASTCALL MiRemoveNode (IN PMMADDRESS_NODE NodeToDelete, IN PMM_AVL_TABLE Table)
Definition at line 808 of file addrsup.c.
References ASSERT, _MMADDRESS_NODE::Balance, COUNT_BALANCE_MAX, _MMADDRESS_NODE::LeftChild, MI_MAKE_PARENT, MiIsLeftChild, MiIsRightChild, MiRebalanceNode(), NULL, _MMADDRESS_NODE::Parent, PRINT, _MMADDRESS_NODE::RightChild, SANITIZE_PARENT_NODE, TRUE, and _MMADDRESS_NODE::u1.
Referenced by MiAweViewRemover(), MiPhysicalViewRemover(), MiRemoveBasedSection(), and MiRemoveVad().