Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/tracesup.c File Reference
tracesup.c File Reference
#include "wmikmp.h"
#include <ntos.h>
#include <evntrace.h>
#include <wmi.h>
#include "tracep.h"
Macros
#define CONTEXT_SIZE PAGE_SIZE
#define DEFAULT_AGE_LIMIT 15
#define DEFAULT_BUFFERS 2
#define DEFAULT_MAX_BUFFERS 20
#define DEFAULT_MAX_IRQL DISPATCH_LEVEL
#define KERNEL_LOGGER_CAPTION L"NT Kernel Logger"
#define max(a, b) (((a) > (b)) ? (a) : (b))
#define SEMAPHORE_LIMIT 1024
Functions
NTSTATUS WmipAllocateTraceBufferPool (IN PWMI_LOGGER_CONTEXT LoggerContext)
PVOID WmipExtendBase (IN PWMI_LOGGER_CONTEXT Base, IN ULONG Size)
NTSTATUS WmipFlushLogger (IN OUT PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG Wait)
VOID WmipFreeLoggerContext (IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipFreeTraceBufferPool (IN PWMI_LOGGER_CONTEXT LoggerContext)
PWMI_LOGGER_CONTEXT WmipInitContext ()
NTSTATUS WmipLookupLoggerIdByName (IN PUNICODE_STRING Name, OUT PULONG LoggerId)
NTSTATUS FASTCALL WmipNotifyLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipNtDllLoggerInfo (IN OUT PWMINTDLLLOGGERINFO Buffer)
NTSTATUS WmipQueryLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo, IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipShutdown (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS WmipStartLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTSTATUS WmipStopLoggerInstance (IN PWMI_LOGGER_CONTEXT LoggerContext)
VOID WmipValidateClockType (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTSTATUS WmipVerifyLoggerInfo (IN PWMI_LOGGER_INFORMATION LoggerInfo, OUT PWMI_LOGGER_CONTEXT *pLoggerContext)
Variables
PSECURITY_DESCRIPTOR EtwpDefaultTraceSecurityDescriptor
HANDLE EtwpPageLockHandle = NULL
SIZE_T MmMaximumNonPagedPoolInBytes
SIZE_T MmSizeOfPagedPoolInBytes
WMI_GET_CPUCLOCK_ROUTINE WmiGetCpuClock = &WmipGetSystemTime
ULONG WmipEventLogger = 0XFFFFFFFF
ULONG WmipKernelLogger = KERNEL_LOGGER
ULONG WmipLoggerCount = 0
KGUARDED_MUTEX WmipTraceGuardedMutex
Macro Definition Documentation
#define CONTEXT_SIZE PAGE_SIZE
Definition at line 34 of file tracesup.c.
Referenced by WmipExtendBase(), and WmipInitContext().
#define DEFAULT_AGE_LIMIT 15
Definition at line 32 of file tracesup.c.
Referenced by WmipStartLogger().
#define DEFAULT_BUFFERS 2
Definition at line 31 of file tracesup.c.
Referenced by WmipAllocateTraceBufferPool(), WmipInitContext(), and WmipStartLogger().
#define DEFAULT_MAX_BUFFERS 20
Definition at line 36 of file tracesup.c.
Referenced by WmipAllocateTraceBufferPool().
#define DEFAULT_MAX_IRQL DISPATCH_LEVEL
Definition at line 35 of file tracesup.c.
Referenced by WmipStartLogger().
#define KERNEL_LOGGER_CAPTION L"NT Kernel Logger"
Definition at line 30 of file tracesup.c.
Referenced by WmipStartLogger().
#define max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 29 of file tracesup.c.
Referenced by WmipAllocateTraceBufferPool(), and WmipStartLogger().
#define SEMAPHORE_LIMIT 1024
Definition at line 33 of file tracesup.c.
Referenced by WmipInitContext(), and WmipNotifyLogger().
Function Documentation
NTSTATUS WmipAllocateTraceBufferPool (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1669 of file tracesup.c.
References _WMI_BUFFER_HEADER::ClientContext, DEFAULT_BUFFERS, DEFAULT_MAX_BUFFERS, KeNumberProcessors, max, min, MmMaximumNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, NULL, PAGED_CODE, _WMI_CLIENT_CONTEXT::ProcessorNumber, STATUS_NO_MEMORY, STATUS_SUCCESS, TRACE_MAXIMUM_NP_POOL_USAGE, WmipAllocateFreeBuffers(), WmipExtendBase(), WmipFreeTraceBufferPool(), and WmipGetFreeBuffer().
Referenced by WmipStartLogger().
PVOID WmipExtendBase (IN PWMI_LOGGER_CONTEXT Base, IN ULONG Size)
Definition at line 1460 of file tracesup.c.
References ALIGN_TO_POWER2, ASSERT, CONTEXT_SIZE, DEFAULT_TRACE_ALIGNMENT, NULL, PAGED_CODE, and Space.
Referenced by WmipAllocateTraceBufferPool(), WmipStartLogger(), and WmiUpdateTrace().
NTSTATUS WmipFlushLogger (IN OUT PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG Wait)
Definition at line 2000 of file tracesup.c.
References Executive, FALSE, KeResetEvent(), KernelMode, KeWaitForSingleObject(), NT_SUCCESS, PAGED_CODE, REQUEST_FLAG_FLUSH_BUFFERS, Status, STATUS_TIMEOUT, TraceDebug, and WmipNotifyLogger().
Referenced by WmiFlushTrace(), and WmiTraceEvent().
VOID WmipFreeLoggerContext (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1499 of file tracesup.c.
References ASSERT, EtwpPageLockHandle, Executive, ExFreePool(), FALSE, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), KeResetEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), MmUnlockPageableImageSection(), NULL, PAGED_CODE, RtlFreeUnicodeString(), Status, STATUS_TIMEOUT, TraceDebug, WmipAssert, WmipDereferenceLogger, WmipFreeTraceBufferPool(), WmipLoggerContext, WmipLoggerCount, and WmipRefCount.
Referenced by WmipLogger(), and WmipStartLogger().
NTSTATUS WmipFreeTraceBufferPool (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1811 of file tracesup.c.
References ASSERT, CONTAINING_RECORD, InterlockedDecrement, InterlockedExchangePointer, InterlockedPopEntrySList(), KeNumberProcessors, NULL, PAGED_CODE, PSLIST_ENTRY, STATUS_SUCCESS, TraceDebug, and WMI_FREE_TRACE_BUFFER.
Referenced by WmipAllocateTraceBufferPool(), and WmipFreeLoggerContext().
PWMI_LOGGER_CONTEXT WmipInitContext ()
Definition at line 1609 of file tracesup.c.
References ALIGN_TO_POWER2, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_LOGGER_CONTEXT::BufferSpinLock, CONTEXT_SIZE, DEFAULT_BUFFERS, DEFAULT_TRACE_ALIGNMENT, _WMI_LOGGER_CONTEXT::EndPageMarker, ExAllocatePoolWithTag, KeInitializeSemaphore(), KeInitializeSpinLock(), KeNumberProcessors, KeQuerySystemTime(), _WMI_LOGGER_CONTEXT::LoggerSemaphore, _WMI_LOGGER_CONTEXT::MaximumBuffers, _WMI_LOGGER_CONTEXT::MinimumBuffers, NonPagedPool, NULL, PAGE_SIZE, PAGED_CODE, RtlZeroMemory, SEMAPHORE_LIMIT, _WMI_LOGGER_CONTEXT::StartTime, and TRACEPOOLTAG.
Referenced by WmipStartLogger().
NTSTATUS WmipLookupLoggerIdByName (IN PUNICODE_STRING Name, OUT PULONG LoggerId)
Definition at line 1921 of file tracesup.c.
References MAXLOGGERS, NULL, PAGED_CODE, RtlEqualUnicodeString(), STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TRUE, and WmipLoggerContext.
Referenced by WmipStartLogger(), and WmipVerifyLoggerInfo().
NTSTATUS FASTCALL WmipNotifyLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 2037 of file tracesup.c.
References FALSE, KeReadStateSemaphore(), KeReleaseSemaphore(), SEMAPHORE_LIMIT, STATUS_SEMAPHORE_LIMIT_EXCEEDED, and STATUS_SUCCESS.
Referenced by WmipFlushLogger(), WmipReleaseTraceBuffer(), WmipStopLoggerInstance(), WmipSwitchBuffer(), and WmiUpdateTrace().
NTSTATUS WmipNtDllLoggerInfo (IN OUT PWMINTDLLLOGGERINFO Buffer)
Definition at line 2054 of file tracesup.c.
References _WNODE_HEADER::BufferSize, _WMI_LOGGER_INFORMATION::BufferSize, EtwpDefaultTraceSecurityDescriptor, tagGUIDENTRY::EventRefCount, EXCEPTION_EXECUTE_HANDLER, FALSE, tagGUIDENTRY::Flags, GE_NOTIFICATION_TRACE_FLAG, tagGUIDENTRY::Guid, InsertHeadList(), _TRACE_ENABLE_CONTEXT::InternalFlag, IsEqualGUID, KeGetPreviousMode, KernelMode, _TRACE_ENABLE_CONTEXT::LoggerId, tagGUIDENTRY::LoggerInfo, tagGUIDENTRY::MainGEList, _WMI_LOGGER_INFORMATION::MaximumBuffers, _WMI_LOGGER_INFORMATION::MinimumBuffers, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, ProbeForWrite(), RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, WmipAlloc, WmipAllocGuidEntry, WmipCheckGuidAccess(), WmipEnableDisableTrace(), WmipEnterSMCritSection, WmipEnterTLCritSection, WmipFindGEByGuid(), WmipFree, WmipGEHeadPtr, WmipLeaveSMCritSection, WmipLeaveTLCritSection, WmipReferenceGE, WmipUnreferenceGE, and _WMI_LOGGER_INFORMATION::Wnode.
NTSTATUS WmipQueryLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo, IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1076 of file tracesup.c.
References EtwpDefaultTraceSecurityDescriptor, except, EXCEPTION_EXECUTE_HANDLER, InterlockedDecrement, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, ProbeForWrite(), _LARGE_INTEGER::QuadPart, RtlCopyUnicodeString(), Status, STATUS_SUCCESS, TraceDebug, WmiOneSecond, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipReleaseMutex, WmipVerifyLoggerInfo(), and WmiSetLoggerId.
Referenced by WmiFlushTrace(), WmipIoControl(), WmiQueryTrace(), WmiStopTrace(), and WmiUpdateTrace().
NTSTATUS WmipShutdown (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 1949 of file tracesup.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, _WMI_LOGGER_CONTEXT::InstanceGuid, IO_NO_INCREMENT, IoCompleteRequest(), MAXLOGGERS, NULL, PAGED_CODE, RtlZeroMemory, STATUS_SUCCESS, TraceDebug, UNREFERENCED_PARAMETER, WmipLoggerContext, WmipLoggerCount, WmiSetLoggerId, WmiStopTrace(), _WMI_LOGGER_INFORMATION::Wnode, and WNODE_FLAG_TRACED_GUID.
Referenced by WmipDriverEntry().
NTSTATUS WmipStartLogger (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 105 of file tracesup.c.
References ASSERT, _UNICODE_STRING::Buffer, _WMI_LOGGER_CONTEXT::BufferAgeLimit, _WMI_LOGGER_CONTEXT::BufferCallback, _WMI_LOGGER_CONTEXT::BuffersAvailable, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_LOGGER_CONTEXT::BuffersWritten, _ETHREAD::Cid, _WMI_LOGGER_CONTEXT::ClientSecurityContext, CONTAINING_RECORD, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, DEFAULT_AGE_LIMIT, DEFAULT_BUFFERS, DEFAULT_MAX_IRQL, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, _WMI_LOGGER_CONTEXT::EnableFlagArray, _WMI_LOGGER_CONTEXT::EnableFlags, EtwpDefaultTraceSecurityDescriptor, EtwpPageLockHandle, EVENT_TRACE_CLOCK_CPUCYCLE, EVENT_TRACE_CLOCK_PERFCOUNTER, EVENT_TRACE_CLOCK_SYSTEMTIME, EVENT_TRACE_FILE_MODE_CIRCULAR_PERSIST, EVENT_TRACE_KD_FILTER_MODE, EVENT_TRACE_USE_KBYTES_FOR_SIZE, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExUuidCreate(), FALSE, FILE_WRITE_DATA, _WMI_LOGGER_CONTEXT::FileCounter, _WMI_LOGGER_CONTEXT::FlushEvent, _WMI_LOGGER_CONTEXT::FlushList, _WMI_LOGGER_CONTEXT::FlushTimer, _WMI_LOGGER_CONTEXT::FreeList, _WMI_LOGGER_CONTEXT::GetCpuClock, _WMI_LOGGER_CONTEXT::GlobalList, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, InitializeSListHead(), _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedCompareExchange(), InterlockedCompareExchangePointer, InterlockedDecrement, InterlockedExchange(), InterlockedIncrement, IoFileObjectType, IsEqualGUID, KdReportTraceData(), KeAcquireGuardedMutex(), KeGetCurrentThread(), KeGetPreviousMode, KeInitializeEvent(), KeNumberProcessors, KeQuerySystemTime(), KeReleaseGuardedMutex(), KeResetEvent(), KERNEL_LOGGER_CAPTION, KernelMode, _WMI_LOGGER_CONTEXT::KernelTraceOn, KeWaitForSingleObject(), _TRACE_ENABLE_FLAG_EXTENSION::Length, _UNICODE_STRING::Length, _SECURITY_QUALITY_OF_SERVICE::Length, _WMI_LOGGER_CONTEXT::LocalSequence, _WMI_LOGGER_CONTEXT::LogFileName, _WMI_LOGGER_CONTEXT::LogFilePattern, _WMI_LOGGER_CONTEXT::LoggerEvent, _WMI_LOGGER_CONTEXT::LoggerHeader, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMode, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::LoggerName, _WMI_LOGGER_CONTEXT::LoggerStatus, _WMI_LOGGER_CONTEXT::LoggerThread, max, MAX_FILE_TABLE_SIZE, MAX_WMI_BUFFER_SIZE, _WMI_LOGGER_CONTEXT::MaximumBuffers, _WMI_LOGGER_CONTEXT::MaximumFileSize, _WMI_LOGGER_CONTEXT::MaximumIrql, MAXLOGGERS, _WMI_LOGGER_CONTEXT::MinimumBuffers, MmLockPageableSectionByHandle(), MmMaximumNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, _WMI_LOGGER_CONTEXT::MutexCount, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, _WMI_LOGGER_CONTEXT::NumberOfBuffers, ObDereferenceObject(), ObReferenceObjectByHandle, _TRACE_ENABLE_FLAG_EXTENSION::Offset, PAGE_SIZE, PAGED_CODE, PagedPool, PERF_LOG_NO_TRANSITION, PERF_LOG_START_TRANSITION, PerfGetCycleCount(), PERFINFO_START_LOG_FROM_GLOBAL_LOGGER, PERFINFO_START_LOG_POST_BOOT, PerfInfoStartLog(), _WMI_LOGGER_CONTEXT::PerfLogInTransition, _WMI_LOGGER_CONTEXT::PoolType, ProbeForRead, ProbeForWrite(), PsCreateSystemThread(), _LARGE_INTEGER::QuadPart, _WMI_LOGGER_CONTEXT::ReferenceSystemTime, _WMI_LOGGER_CONTEXT::ReferenceTimeStamp, REQUEST_FLAG_CIRCULAR_PERSIST, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, RtlCopyUnicodeString(), RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlZeroMemory, SeComputeGrantedAccesses, SeCreateClientSecurity(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, _WMI_LOGGER_CONTEXT::SequencePtr, Status, STATUS_ACCESS_DENIED, STATUS_ALREADY_DISCONNECTED, STATUS_CANCELLED, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_COLLISION, STATUS_PENDING, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_ALL_ACCESS, TRACE_MAXIMUM_NP_POOL_USAGE, TraceDebug, TRACEPOOLTAG, TRUE, _CLIENT_ID::UniqueThread, _WMI_LOGGER_CONTEXT::UsePerfClock, _WMI_LOGGER_CONTEXT::WaitList, WmiGetCpuClock, WmiOneSecond, WmipAcquireMutex, WmipAllocateTraceBufferPool(), WmipCheckGuidAccess(), WmipDereferenceLogger, WmipEnableKernelTrace(), WmipEventLogger, WmipExtendBase(), WmipFileTable, WmipFreeLoggerContext(), WmipGenerateFileName(), WmipGetPerfCounter(), WmipGetSystemTime(), WmipGlobalSequence, WmipInitContext(), WmipInitializeMutex, WmipKernelLogger, WmipLogger(), WmipLoggerContext, WmipLoggerCount, WmipLookupLoggerIdByName(), WmipRefCount, WmipReferenceLogger, WmipReleaseMutex, WmipStopLoggerInstance(), WmipValidateClockType(), WmiSetLoggerId, WNODE_FLAG_TRACED_GUID, _WMI_LOGGER_CONTEXT::Wow, _WMI_LOGGER_CONTEXT::WriteFailureLimit, and ZwClose().
Referenced by WmipIoControl(), WmipStartGlobalLogger(), and WmiStartTrace().
NTSTATUS WmipStopLoggerInstance (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1256 of file tracesup.c.
References FALSE, InterlockedCompareExchange(), InterlockedExchange(), NULL, PAGED_CODE, PERF_LOG_NO_TRANSITION, PERF_LOG_START_TRANSITION, PERF_LOG_STOP_TRANSITION, PerfInfoStopLog(), STATUS_ALREADY_DISCONNECTED, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_THREAD_IS_TERMINATING, STATUS_UNSUCCESSFUL, WmipDisableKernelTrace(), WmipEventLogger, WmipLoggerContext, WmipNotifyLogger(), and WmipSendNotification().
Referenced by WmipLogger(), WmipStartLogger(), and WmiStopTrace().
VOID WmipValidateClockType (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 2278 of file tracesup.c.
References UNREFERENCED_PARAMETER.
Referenced by WmipIoControl(), and WmipStartLogger().
NTSTATUS WmipVerifyLoggerInfo (IN PWMI_LOGGER_INFORMATION LoggerInfo, OUT PWMI_LOGGER_CONTEXT * pLoggerContext)
Definition at line 1328 of file tracesup.c.
References _UNICODE_STRING::Buffer, _WMI_LOGGER_CONTEXT::CollectionOn, except, EXCEPTION_EXECUTE_HANDLER, InterlockedDecrement, InterlockedIncrement, IsEqualGUID, KeGetPreviousMode, KERNEL_LOGGER_ID, KernelMode, _UNICODE_STRING::Length, _WMI_LOGGER_CONTEXT::LoggerMutex, MAXLOGGERS, _WMI_LOGGER_CONTEXT::MutexCount, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), Status, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TraceDebug, WmiGetLoggerId, WmipAcquireMutex, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, WmipKernelLogger, WmipLookupLoggerIdByName(), WmipReferenceLogger, WmipReleaseMutex, and WNODE_FLAG_TRACED_GUID.
Referenced by WmiFlushTrace(), WmipQueryLogger(), WmiStopTrace(), and WmiUpdateTrace().
Variable Documentation
PSECURITY_DESCRIPTOR EtwpDefaultTraceSecurityDescriptor
Definition at line 47 of file tracesup.c.
Referenced by WmiFlushTrace(), WmipEnableDisableTrace(), WmipNtDllLoggerInfo(), WmipQueryLogger(), WmipStartGlobalLogger(), WmipStartLogger(), WmiStopTrace(), and WmiUpdateTrace().
HANDLE EtwpPageLockHandle = NULL
Definition at line 46 of file tracesup.c.
Referenced by WmipFreeLoggerContext(), WmipStartGlobalLogger(), and WmipStartLogger().
SIZE_T MmMaximumNonPagedPoolInBytes
Definition at line 273 of file miglobal.c.
Referenced by WmipAllocateTraceBufferPool(), and WmipStartLogger().
SIZE_T MmSizeOfPagedPoolInBytes
Definition at line 287 of file miglobal.c.
Referenced by WmipAllocateTraceBufferPool(), and WmipStartLogger().
WMI_GET_CPUCLOCK_ROUTINE WmiGetCpuClock = &WmipGetSystemTime
Definition at line 55 of file tracesup.c.
Referenced by WmipStartLogger().
ULONG WmipEventLogger = 0XFFFFFFFF
Definition at line 39 of file tracesup.c.
Referenced by WmipStartLogger(), WmipStopLoggerInstance(), WmipTraceLoadImage(), WmiQueryTraceInformation(), WmiStopTrace(), WmiTraceProcess(), and WmiTraceThread().
ULONG WmipKernelLogger = KERNEL_LOGGER
Definition at line 38 of file tracesup.c.
Referenced by WmipAddLogHeader(), WmipFlushActiveBuffers(), WmipPopFreeContextSwapBuffer(), WmipPushDirtyContextSwapBuffer(), WmipStartLogger(), WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmipVerifyLoggerInfo(), WmiReleaseKernelBuffer(), WmiReserveWithPerfHeader(), WmiSetTraceBufferCallback(), WmiStopContextSwapTrace(), WmiStopTrace(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceProcess(), WmiTraceThread(), and WmiUpdateTrace().
ULONG WmipLoggerCount = 0
Definition at line 45 of file tracesup.c.
Referenced by WmipFreeLoggerContext(), WmipShutdown(), and WmipStartLogger().
KGUARDED_MUTEX WmipTraceGuardedMutex
Definition at line 40 of file tracesup.c.
Referenced by WmipStartGlobalLogger().