Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/handle.c File Reference
handle.c File Reference
#include "exp.h"
Macros
#define EX_ADDITIONAL_INFO_SIGNATURE (-2)
#define EXASSERT ASSERT
#define EXHANDLE_EXTRA_CHECKS 0
#define EXHANDLE_TABLE_ENTRY_LOCK_BIT 1
#define ExpIsValidObjectEntry(Entry) ((Entry != NULL) && (Entry->Object != NULL) && (Entry->NextFreeTableEntry != EX_ADDITIONAL_INFO_SIGNATURE))
#define ExpLockHandleTableExclusive(xxHandleTable, xxCurrentThread)
#define ExpLockHandleTableShared(xxHandleTable, xxCurrentThread, xxIdx)
#define ExpUnlockHandleTableExclusive(xxHandleTable, xxCurrentThread)
#define ExpUnlockHandleTableShared(xxHandleTable, xxCurrentThread, xxIdx)
#define FREE_HANDLE_MASK 0xFFFFFFFF
#define FREE_SEQ_INC 0
#define FREE_SEQ_MASK (0xFFFFFFFF & ~FREE_HANDLE_MASK)
#define GetNextSeq() 0
#define HIGHLEVEL_COUNT MAX_HANDLES / (LOWLEVEL_COUNT * MIDLEVEL_COUNT)
#define HIGHLEVEL_SIZE (HIGHLEVEL_COUNT * sizeof (PHANDLE_TABLE_ENTRY))
#define HIGHLEVEL_THRESHOLD (MIDLEVEL_COUNT * MIDLEVEL_COUNT * LOWLEVEL_COUNT)
#define LEVEL_CODE_MASK 3
#define LOWLEVEL_COUNT (TABLE_PAGE_SIZE / sizeof(HANDLE_TABLE_ENTRY))
#define LOWLEVEL_THRESHOLD LOWLEVEL_COUNT
#define MAX_ALLOCS 20
#define MAX_HANDLES (1<<24)
#define MIDLEVEL_COUNT (PAGE_SIZE / sizeof(PHANDLE_TABLE_ENTRY))
#define MIDLEVEL_THRESHOLD (MIDLEVEL_COUNT * LOWLEVEL_COUNT)
#define TABLE_PAGE_SIZE PAGE_SIZE
#define TRACE_ALL_TABLES FALSE
Functions
C_ASSERT (RTL_FIELD_SIZE(HANDLE_TRACE_DEBUG_INFO, TraceDb[0])<=MAXULONG)
NTKERNELAPI BOOLEAN ExChangeHandle (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PEX_CHANGE_HANDLE_ROUTINE ChangeRoutine, __in ULONG_PTR Parameter)
NTKERNELAPI HANDLE ExCreateHandle (__inout PHANDLE_TABLE HandleTable, __in PHANDLE_TABLE_ENTRY HandleTableEntry)
NTKERNELAPI PHANDLE_TABLE ExCreateHandleTable (__in_opt struct _EPROCESS *Process)
VOID ExDereferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable, IN PHANDLE_TRACE_DEBUG_INFO DebugInfo)
NTKERNELAPI BOOLEAN ExDestroyHandle (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __inout_opt PHANDLE_TABLE_ENTRY HandleTableEntry)
NTKERNELAPI VOID ExDestroyHandleTable (__inout PHANDLE_TABLE HandleTable, __in EX_DESTROY_HANDLE_ROUTINE DestroyHandleProcedure OPTIONAL)
NTKERNELAPI NTSTATUS ExDisableHandleTracing (__inout PHANDLE_TABLE HandleTable)
NTKERNELAPI PHANDLE_TABLE ExDupHandleTable (__inout_opt struct _EPROCESS *Process, __in PHANDLE_TABLE OldHandleTable, __in EX_DUPLICATE_HANDLE_ROUTINE DupHandleProcedure, __in ULONG_PTR Mask)
NTKERNELAPI NTSTATUS ExEnableHandleTracing (__inout PHANDLE_TABLE HandleTable, __in ULONG Slots)
NTKERNELAPI BOOLEAN ExEnumHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter, __out_opt PHANDLE Handle)
VOID ExHandleTest ()
NTKERNELAPI VOID ExInitializeHandleTablePackage (VOID)
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointer (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle)
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointerEx (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
PHANDLE_TABLE ExpAllocateHandleTable (IN PEPROCESS Process OPTIONAL, IN BOOLEAN DoInit)
PHANDLE_TABLE_ENTRY ExpAllocateHandleTableEntry (IN PHANDLE_TABLE HandleTable, OUT PEXHANDLE Handle)
BOOLEAN ExpAllocateHandleTableEntrySlow (IN PHANDLE_TABLE HandleTable, IN BOOLEAN DoInit)
PHANDLE_TABLE_ENTRY ExpAllocateLowLevelTable (IN PHANDLE_TABLE HandleTable, IN BOOLEAN DoInit)
PHANDLE_TABLE_ENTRY * ExpAllocateMidLevelTable (IN PHANDLE_TABLE HandleTable, IN BOOLEAN DoInit, OUT PHANDLE_TABLE_ENTRY *pNewLowLevel)
PVOID ExpAllocateTablePagedPool (IN PEPROCESS QuotaProcess OPTIONAL, IN SIZE_T NumberOfBytes)
PVOID ExpAllocateTablePagedPoolNoZero (IN PEPROCESS QuotaProcess OPTIONAL, IN SIZE_T NumberOfBytes)
VOID ExpBlockOnLockedHandleEntry (PHANDLE_TABLE HandleTable, PHANDLE_TABLE_ENTRY HandleTableEntry)
VOID ExpFreeHandleTable (IN PHANDLE_TABLE HandleTable)
VOID ExpFreeHandleTableEntry (IN PHANDLE_TABLE HandleTable, IN EXHANDLE Handle, IN PHANDLE_TABLE_ENTRY HandleTableEntry)
VOID ExpFreeLowLevelTable (IN PEPROCESS QuotaProcess, IN PHANDLE_TABLE_ENTRY TableLevel1)
VOID ExpFreeTablePagedPool (IN PEPROCESS QuotaProcess OPTIONAL, IN PVOID PoolMemory, IN SIZE_T NumberOfBytes)
NTKERNELAPI PHANDLE_TABLE_ENTRY_INFO ExpGetHandleInfo (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in BOOLEAN EntryLocked)
FORCEINLINE ULONG ExpInterlockedExchange (IN OUT PULONG Index, IN ULONG FirstIndex, IN PHANDLE_TABLE_ENTRY Entry)
BOOLEAN FORCEINLINE ExpLockHandleTableEntry (PHANDLE_TABLE HandleTable, PHANDLE_TABLE_ENTRY HandleTableEntry)
PHANDLE_TABLE_ENTRY ExpLookupHandleTableEntry (IN PHANDLE_TABLE HandleTable, IN EXHANDLE Handle)
ULONG ExpMoveFreeHandles (IN PHANDLE_TABLE HandleTable)
VOID ExpUpdateDebugInfo (PHANDLE_TABLE HandleTable, PETHREAD CurrentThread, HANDLE Handle, ULONG Type)
PHANDLE_TRACE_DEBUG_INFO ExReferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable)
NTKERNELAPI VOID ExRemoveHandleTable (__inout PHANDLE_TABLE HandleTable)
NTKERNELAPI NTSTATUS ExSetHandleInfo (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PHANDLE_TABLE_ENTRY_INFO EntryInfo, __in BOOLEAN EntryLocked)
VOID ExSetHandleTableStrictFIFO (IN PHANDLE_TABLE HandleTable)
NTKERNELAPI NTSTATUS ExSnapShotHandleTables (__in PEX_SNAPSHOT_HANDLE_ENTRY SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
NTKERNELAPI NTSTATUS ExSnapShotHandleTablesEx (__in PEX_SNAPSHOT_HANDLE_ENTRY_EX SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION_EX HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
NTKERNELAPI VOID ExSweepHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter)
NTKERNELAPI VOID FORCEINLINE ExUnlockHandleTableEntry (__inout PHANDLE_TABLE HandleTable, __inout PHANDLE_TABLE_ENTRY HandleTableEntry)
Variables
LIST_ENTRY HandleTableListHead
EX_PUSH_LOCK HandleTableListLock
ULONG TotalTraceBuffers = 0
Macro Definition Documentation
#define EX_ADDITIONAL_INFO_SIGNATURE (-2)
Definition at line 90 of file handle.c.
Referenced by ExpAllocateHandleTable(), ExpAllocateLowLevelTable(), ExpGetHandleInfo(), and ExSetHandleInfo().
#define EXASSERT ASSERT
Definition at line 80 of file handle.c.
Referenced by ExDestroyHandle(), ExpAllocateHandleTableEntry(), ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTableEntry(), ExpInterlockedExchange(), ExpMoveFreeHandles(), and ExUnlockHandleTableEntry().
#define EXHANDLE_EXTRA_CHECKS 0
Definition at line 68 of file handle.c.
#define EXHANDLE_TABLE_ENTRY_LOCK_BIT 1
Definition at line 88 of file handle.c.
Referenced by ExDestroyHandle(), ExDupHandleTable(), ExpBlockOnLockedHandleEntry(), ExpLockHandleTableEntry(), and ExUnlockHandleTableEntry().
#define ExpIsValidObjectEntry (Entry) ((Entry != NULL) && (Entry->Object != NULL) && (Entry->NextFreeTableEntry != EX_ADDITIONAL_INFO_SIGNATURE))
Definition at line 92 of file handle.c.
Referenced by ExChangeHandle(), ExDestroyHandle(), ExDestroyHandleTable(), ExEnumHandleTable(), ExSnapShotHandleTables(), and ExSnapShotHandleTablesEx().
#define ExpLockHandleTableExclusive (xxHandleTable, xxCurrentThread)
Value:
{ \
    KeEnterCriticalRegionThread (xxCurrentThread);                   \
    ExAcquirePushLockExclusive (&xxHandleTable->HandleTableLock[0]); \
}
Definition at line 292 of file handle.c.
Referenced by ExDisableHandleTracing(), ExEnableHandleTracing(), and ExpAllocateHandleTableEntry().
#define ExpLockHandleTableShared (xxHandleTable, xxCurrentThread, xxIdx)
Value:
{ \
    KeEnterCriticalRegionThread (xxCurrentThread);                      \
    ExAcquirePushLockShared (&xxHandleTable->HandleTableLock[xxIdx]);   \
}
Definition at line 303 of file handle.c.
Referenced by ExpAllocateHandleTableEntry(), and ExReferenceHandleDebugInfo().
#define ExpUnlockHandleTableExclusive (xxHandleTable, xxCurrentThread)
Value:
{ \
    ExReleasePushLockExclusive (&xxHandleTable->HandleTableLock[0]);   \
    KeLeaveCriticalRegionThread (xxCurrentThread);                     \
}
Definition at line 298 of file handle.c.
Referenced by ExDisableHandleTracing(), ExEnableHandleTracing(), and ExpAllocateHandleTableEntry().
#define ExpUnlockHandleTableShared (xxHandleTable, xxCurrentThread, xxIdx)
Value:
{ \
    ExReleasePushLockShared (&xxHandleTable->HandleTableLock[xxIdx]);     \
    KeLeaveCriticalRegionThread (xxCurrentThread);                        \
}
Definition at line 309 of file handle.c.
Referenced by ExpAllocateHandleTableEntry(), and ExReferenceHandleDebugInfo().
#define FREE_HANDLE_MASK 0xFFFFFFFF
Definition at line 115 of file handle.c.
Referenced by ExpAllocateHandleTableEntry(), and ExpFreeHandleTableEntry().
#define FREE_SEQ_INC 0
Definition at line 126 of file handle.c.
#define FREE_SEQ_MASK (0xFFFFFFFF & ~FREE_HANDLE_MASK)
Definition at line 122 of file handle.c.
#define GetNextSeq () 0
Definition at line 127 of file handle.c.
Referenced by ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTableEntry(), ExpInterlockedExchange(), and ExpMoveFreeHandles().
#define HIGHLEVEL_COUNT MAX_HANDLES / (LOWLEVEL_COUNT * MIDLEVEL_COUNT)
Definition at line 141 of file handle.c.
Referenced by ExpAllocateHandleTableEntrySlow(), and ExpFreeHandleTable().
#define HIGHLEVEL_SIZE (HIGHLEVEL_COUNT * sizeof (PHANDLE_TABLE_ENTRY))
Definition at line 147 of file handle.c.
Referenced by ExpAllocateHandleTableEntrySlow(), and ExpFreeHandleTable().
#define HIGHLEVEL_THRESHOLD (MIDLEVEL_COUNT * MIDLEVEL_COUNT * LOWLEVEL_COUNT)
Definition at line 145 of file handle.c.
#define LEVEL_CODE_MASK 3
Definition at line 149 of file handle.c.
Referenced by ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTable(), and ExpLookupHandleTableEntry().
#define LOWLEVEL_COUNT (TABLE_PAGE_SIZE / sizeof(HANDLE_TABLE_ENTRY))
Definition at line 139 of file handle.c.
Referenced by ExDupHandleTable(), ExMapHandleToPointer(), ExMapHandleToPointerEx(), ExpAllocateHandleTable(), ExpAllocateHandleTableEntrySlow(), ExpAllocateLowLevelTable(), ExpFreeLowLevelTable(), ExpGetHandleInfo(), ExpLookupHandleTableEntry(), ExSetHandleInfo(), and ExSweepHandleTable().
#define LOWLEVEL_THRESHOLD LOWLEVEL_COUNT
Definition at line 143 of file handle.c.
#define MAX_ALLOCS 20
Referenced by ExHandleTest().
#define MAX_HANDLES (1<<24)
Definition at line 101 of file handle.c.
#define MIDLEVEL_COUNT (PAGE_SIZE / sizeof(PHANDLE_TABLE_ENTRY))
Definition at line 140 of file handle.c.
Referenced by ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTable(), and ExpLookupHandleTableEntry().
#define MIDLEVEL_THRESHOLD (MIDLEVEL_COUNT * LOWLEVEL_COUNT)
Definition at line 144 of file handle.c.
Referenced by ExpAllocateHandleTableEntrySlow().
#define TABLE_PAGE_SIZE PAGE_SIZE
Definition at line 96 of file handle.c.
Referenced by ExpAllocateHandleTable(), ExpAllocateLowLevelTable(), and ExpFreeLowLevelTable().
#define TRACE_ALL_TABLES FALSE
Definition at line 47 of file handle.c.
Referenced by ExpAllocateHandleTable().
Function Documentation
C_ASSERT (RTL_FIELD_SIZE(HANDLE_TRACE_DEBUG_INFO, TraceDb[0])<= MAXULONG)
NTKERNELAPI BOOLEAN ExChangeHandle (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PEX_CHANGE_HANDLE_ROUTINE ChangeRoutine, __in ULONG_PTR Parameter)
Definition at line 1923 of file handle.c.
References ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), FALSE, _EXHANDLE::GenericHandleOverlay, Handle, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, and PAGED_CODE.
Referenced by ObSetHandleAttributes().
NTKERNELAPI HANDLE ExCreateHandle (__inout PHANDLE_TABLE HandleTable, __in PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 1729 of file handle.c.
References ExpAllocateHandleTableEntry(), ExpUpdateDebugInfo(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_OPEN, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, PsGetCurrentThread(), and _ETHREAD::Tcb.
Referenced by ObDuplicateObject(), ObpCreateHandle(), ObpCreateUnnamedHandle(), PspCreateProcess(), PspCreateThread(), and RtlpCreateHandleForAtom().
NTKERNELAPI PHANDLE_TABLE ExCreateHandleTable (__in_opt struct _EPROCESS * Process)
Definition at line 830 of file handle.c.
References ExAcquirePushLockExclusive(), ExpAllocateHandleTable(), ExReleasePushLockExclusive(), _HANDLE_TABLE::HandleTableList, InsertTailList(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, and TRUE.
Referenced by ObInitProcess(), ObInitSystem(), PspInitPhase0(), and RtlpInitializeHandleTableForAtomTable().
VOID ExDereferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable, IN PHANDLE_TRACE_DEBUG_INFO DebugInfo)
Definition at line 2311 of file handle.c.
References ASSERT, ExFreePool(), InterlockedDecrement, InterlockedExchangeAdd(), NULL, PsReturnProcessNonPagedPoolQuota(), and TotalTraceBuffers.
Referenced by ExDisableHandleTracing(), ExEnableHandleTracing(), ExpFreeHandleTable(), ExpUpdateDebugInfo(), and NtQueryInformationProcess().
NTKERNELAPI BOOLEAN ExDestroyHandle (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __inout_opt PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 1815 of file handle.c.
References EXASSERT, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExpFreeHandleTableEntry(), ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), ExUnblockPushLock(), FALSE, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_CLOSE, InterlockedExchangePointer, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, PsGetCurrentThread(), _ETHREAD::Tcb, and TRUE.
Referenced by ObpCloseHandleTableEntry(), PspProcessDelete(), PspThreadDelete(), and RtlpFreeHandleForAtom().
NTKERNELAPI VOID ExDestroyHandleTable (__inout PHANDLE_TABLE HandleTable, __in EX_DESTROY_HANDLE_ROUTINE DestroyHandleProcedure OPTIONAL)
Definition at line 952 of file handle.c.
References ARGUMENT_PRESENT, ExpFreeHandleTable(), ExpIsValidObjectEntry, ExpLookupHandleTableEntry(), ExRemoveHandleTable(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, NULL, PAGED_CODE, and _EXHANDLE::Value.
Referenced by ObKillProcess(), and RtlpDestroyHandleTableForAtomTable().
NTKERNELAPI NTSTATUS ExDisableHandleTracing (__inout PHANDLE_TABLE HandleTable)
Definition at line 2342 of file handle.c.
References ExDereferenceHandleDebugInfo(), ExpLockHandleTableExclusive, ExpUnlockHandleTableExclusive, KeGetCurrentThread(), NULL, and STATUS_SUCCESS.
Referenced by NtSetInformationProcess().
NTKERNELAPI PHANDLE_TABLE ExDupHandleTable (__inout_opt struct _EPROCESS * Process, __in PHANDLE_TABLE OldHandleTable, __in EX_DUPLICATE_HANDLE_ROUTINE DupHandleProcedure , __in ULONG_PTR Mask)
Definition at line 1212 of file handle.c.
References _HANDLE_TABLE_ENTRY_INFO::AuditMask, _HANDLE_TABLE::DebugInfo, ExAcquirePushLockExclusive(), ExGetHandleInfo, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExpAllocateHandleTable(), ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTable(), ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), ExReleasePushLockExclusive(), ExSetHandleInfo(), _HANDLE_TABLE::ExtraInfoPages, ExUnlockHandleTableEntry(), FALSE, _HANDLE_TABLE::FirstFree, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_OPEN, HANDLE_VALUE_INC, _HANDLE_TABLE::HandleCount, _HANDLE_TABLE::HandleTableList, InsertTailList(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeMemoryBarrier(), LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, _HANDLE_TABLE::NextHandleNeedingPool, NT_SUCCESS, NULL, _HANDLE_TABLE_ENTRY::Object, PAGED_CODE, PsGetCurrentThread(), Status, STATUS_SUCCESS, TRUE, _EXHANDLE::Value, and _HANDLE_TABLE_ENTRY::Value.
Referenced by ObInitProcess().
NTKERNELAPI NTSTATUS ExEnableHandleTracing (__inout PHANDLE_TABLE HandleTable, __in ULONG Slots)
Definition at line 2386 of file handle.c.
References ASSERT, _HANDLE_TRACE_DEBUG_INFO::CloseCompactionLock, ExAllocatePoolWithTag, ExDereferenceHandleDebugInfo(), ExInitializeFastMutex, ExpLockHandleTableExclusive, ExpUnlockHandleTableExclusive, HANDLE_TRACE_DB_DEFAULT_STACKS, HANDLE_TRACE_DB_MAX_STACKS, HANDLE_TRACE_DB_MIN_STACKS, InterlockedExchangeAdd(), KeGetCurrentThread(), MmMaximumNonPagedPoolInBytes, NonPagedPool, NT_SUCCESS, NULL, PsChargeProcessNonPagedPoolQuota(), PsReturnProcessNonPagedPoolQuota(), _HANDLE_TRACE_DEBUG_INFO::RefCount, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _HANDLE_TRACE_DEBUG_INFO::TableSize, TotalTraceBuffers, _HANDLE_TRACE_DEBUG_INFO::TraceDb, and TRUE.
Referenced by ExpAllocateHandleTable(), and NtSetInformationProcess().
NTKERNELAPI BOOLEAN ExEnumHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter, __out_opt PHANDLE Handle)
Definition at line 1098 of file handle.c.
References ARGUMENT_PRESENT, ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), FALSE, _EXHANDLE::GenericHandleOverlay, HANDLE_VALUE_INC, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, and _EXHANDLE::Value.
Referenced by ObFindHandleForObject(), ObInitProcess(), and ObShutdownSystem().
VOID ExHandleTest ()
Definition at line 4045 of file handle.c.
References ExpAllocateHandleTableEntry(), ExpFreeHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, KeQuerySystemTime(), _LARGE_INTEGER::LowPart, MAX_ALLOCS, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, _EPROCESS::ObjectTable, PsGetCurrentProcess(), _LARGE_INTEGER::QuadPart, and _HANDLE_TABLE::StrictFIFO.
NTKERNELAPI VOID ExInitializeHandleTablePackage (VOID)
Definition at line 795 of file handle.c.
References ExInitializePushLock(), and InitializeListHead().
Referenced by ExpInitializeExecutive().
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointer (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle)
Definition at line 2015 of file handle.c.
References ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_BADREF, _EXHANDLE::Index, LOWLEVEL_COUNT, NULL, PAGED_CODE, and PsGetCurrentThread().
Referenced by ExpGetHandleInfo(), ExSetHandleInfo(), ObAuditObjectAccess(), ObDuplicateObject(), ObpCloseHandle(), ObpCreateHandle(), ObpReferenceProcessObjectByHandle(), ObQueryObjectAuditingByHandle(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), and RtlpAtomMapAtomToHandleEntry().
NTKERNELAPI PHANDLE_TABLE_ENTRY ExMapHandleToPointerEx (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
Definition at line 2084 of file handle.c.
References DbgPrint(), ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExpUpdateDebugInfo(), FLG_APPLICATION_VERIFIER, FLG_ENABLE_HANDLE_EXCEPTIONS, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_TRACE_DB_BADREF, _EXHANDLE::Index, INVALID_KERNEL_HANDLE, KeBugCheckEx(), KeIsAttachedProcess(), KeRaiseUserException(), LOWLEVEL_COUNT, NtGlobalFlag, NULL, PAGED_CODE, PsGetCurrentProcess(), PsGetCurrentThread(), STATUS_INVALID_HANDLE, and UserMode.
Referenced by ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
PHANDLE_TABLE ExpAllocateHandleTable (IN PEPROCESS Process OPTIONAL, IN BOOLEAN DoInit)
Definition at line 2536 of file handle.c.
References ARGUMENT_PRESENT, EX_ADDITIONAL_INFO_SIGNATURE, ExAllocatePoolWithTag, ExEnableHandleTracing(), ExFreePool(), ExInitializePushLock(), ExpAllocateTablePagedPoolNoZero(), _HANDLE_TABLE::FirstFree, _HANDLE_TABLE::Flags, HANDLE_TABLE_LOCKS, HANDLE_VALUE_INC, _HANDLE_TABLE::HandleContentionEvent, _HANDLE_TABLE::HandleTableLock, LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, _HANDLE_TABLE::NextHandleNeedingPool, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, PsChargeProcessPagedPoolQuota(), PsGetCurrentProcess(), PsReturnProcessPagedPoolQuota(), _HANDLE_TABLE::QuotaProcess, RtlZeroMemory, _HANDLE_TABLE::StrictFIFO, TABLE_PAGE_SIZE, _HANDLE_TABLE::TableCode, TRACE_ALL_TABLES, TRUE, _EPROCESS::UniqueProcessId, _HANDLE_TABLE::UniqueProcessId, and _HANDLE_TABLE_ENTRY::Value.
Referenced by ExCreateHandleTable(), and ExDupHandleTable().
PHANDLE_TABLE_ENTRY ExpAllocateHandleTableEntry (IN PHANDLE_TABLE HandleTable, OUT PEXHANDLE Handle)
Definition at line 480 of file handle.c.
References EXASSERT, ExpAllocateHandleTableEntrySlow(), ExpLockHandleTableExclusive, ExpLockHandleTableShared, ExpLookupHandleTableEntry(), ExpMoveFreeHandles(), ExpUnlockHandleTableExclusive, ExpUnlockHandleTableShared, FREE_HANDLE_MASK, Handle, HANDLE_TABLE_LOCKS, InterlockedCompareExchange(), InterlockedIncrement, KeGetCurrentThread(), KeMemoryBarrier(), _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, TRUE, and _EXHANDLE::Value.
Referenced by ExCreateHandle(), and ExHandleTest().
BOOLEAN ExpAllocateHandleTableEntrySlow (IN PHANDLE_TABLE HandleTable, IN BOOLEAN DoInit)
Definition at line 3099 of file handle.c.
References EXASSERT, ExpAllocateLowLevelTable(), ExpAllocateMidLevelTable(), ExpAllocateTablePagedPool(), ExpFreeTablePagedPool(), FALSE, GetNextSeq, HANDLE_VALUE_INC, HIGHLEVEL_COUNT, HIGHLEVEL_SIZE, InterlockedCompareExchange(), InterlockedExchangeAdd(), InterlockedExchangePointer, LEVEL_CODE_MASK, LOWLEVEL_COUNT, MIDLEVEL_COUNT, MIDLEVEL_THRESHOLD, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, PAGED_CODE, ReadForWriteAccess, and TRUE.
Referenced by ExDupHandleTable(), and ExpAllocateHandleTableEntry().
PHANDLE_TABLE_ENTRY ExpAllocateLowLevelTable (IN PHANDLE_TABLE HandleTable, IN BOOLEAN DoInit)
Definition at line 2936 of file handle.c.
References EX_ADDITIONAL_INFO_SIGNATURE, ExpAllocateTablePagedPoolNoZero(), HANDLE_VALUE_INC, LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, and TABLE_PAGE_SIZE.
Referenced by ExpAllocateHandleTableEntrySlow(), and ExpAllocateMidLevelTable().
PHANDLE_TABLE_ENTRY * ExpAllocateMidLevelTable (IN PHANDLE_TABLE HandleTable, IN BOOLEAN DoInit, OUT PHANDLE_TABLE_ENTRY * pNewLowLevel)
Definition at line 3026 of file handle.c.
References ExpAllocateLowLevelTable(), ExpAllocateTablePagedPool(), ExpFreeTablePagedPool(), NULL, and PAGE_SIZE.
Referenced by ExpAllocateHandleTableEntrySlow().
PVOID ExpAllocateTablePagedPool (IN PEPROCESS QuotaProcess OPTIONAL, IN SIZE_T NumberOfBytes)
Definition at line 2203 of file handle.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, PagedPool, PsChargeProcessPagedPoolQuota(), and RtlZeroMemory.
Referenced by ExpAllocateHandleTableEntrySlow(), ExpAllocateMidLevelTable(), and ExSetHandleInfo().
PVOID ExpAllocateTablePagedPoolNoZero (IN PEPROCESS QuotaProcess OPTIONAL, IN SIZE_T NumberOfBytes)
Definition at line 2233 of file handle.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, PagedPool, and PsChargeProcessPagedPoolQuota().
Referenced by ExpAllocateHandleTable(), and ExpAllocateLowLevelTable().
VOID ExpBlockOnLockedHandleEntry (PHANDLE_TABLE HandleTable, PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 622 of file handle.c.
References ExBlockPushLock(), EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExUnblockPushLock(), ExWaitForUnblockPushLock(), _HANDLE_TABLE::HandleContentionEvent, and _HANDLE_TABLE_ENTRY::Value.
Referenced by ExpLockHandleTableEntry().
VOID ExpFreeHandleTable (IN PHANDLE_TABLE HandleTable)
Definition at line 2771 of file handle.c.
References ExDereferenceHandleDebugInfo(), ExFreePool(), ExpFreeLowLevelTable(), ExpFreeTablePagedPool(), HIGHLEVEL_COUNT, HIGHLEVEL_SIZE, LEVEL_CODE_MASK, MIDLEVEL_COUNT, NULL, PAGE_SIZE, PAGED_CODE, and PsReturnProcessPagedPoolQuota().
Referenced by ExDestroyHandleTable(), and ExDupHandleTable().
VOID ExpFreeHandleTableEntry (IN PHANDLE_TABLE HandleTable, IN EXHANDLE Handle, IN PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 3406 of file handle.c.
References _HANDLE_TABLE_ENTRY_INFO::AuditMask, EXASSERT, ExGetHandleInfo, ExpLookupHandleTableEntry(), ExTryAcquireReleasePushLockExclusive(), FREE_HANDLE_MASK, GetNextSeq, HANDLE_TABLE_LOCKS, HANDLE_VALUE_INC, InterlockedCompareExchange(), InterlockedDecrement, KeGetCurrentThread(), NULL, PAGED_CODE, ReadForWriteAccess, and TRUE.
Referenced by ExDestroyHandle(), and ExHandleTest().
VOID ExpFreeLowLevelTable (IN PEPROCESS QuotaProcess, IN PHANDLE_TABLE_ENTRY TableLevel1)
Definition at line 2714 of file handle.c.
References ExpFreeTablePagedPool(), LOWLEVEL_COUNT, and TABLE_PAGE_SIZE.
Referenced by ExpFreeHandleTable().
VOID ExpFreeTablePagedPool (IN PEPROCESS QuotaProcess OPTIONAL, IN PVOID PoolMemory, IN SIZE_T NumberOfBytes)
Definition at line 2265 of file handle.c.
References ExFreePool(), and PsReturnProcessPagedPoolQuota().
Referenced by ExpAllocateHandleTableEntrySlow(), ExpAllocateMidLevelTable(), ExpFreeHandleTable(), ExpFreeLowLevelTable(), and ExSetHandleInfo().
NTKERNELAPI PHANDLE_TABLE_ENTRY_INFO ExpGetHandleInfo (__in PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in BOOLEAN EntryLocked)
Definition at line 3810 of file handle.c.
References EX_ADDITIONAL_INFO_SIGNATURE, ExMapHandleToPointer(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, _EXHANDLE::Index, _HANDLE_TABLE_ENTRY::InfoTable, LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, and NULL.
FORCEINLINE ULONG ExpInterlockedExchange (IN OUT PULONG Index, IN ULONG FirstIndex, IN PHANDLE_TABLE_ENTRY Entry)
Definition at line 318 of file handle.c.
References EXASSERT, GetNextSeq, InterlockedCompareExchange(), NULL, and ReadForWriteAccess.
Referenced by ExpMoveFreeHandles().
BOOLEAN FORCEINLINE ExpLockHandleTableEntry (PHANDLE_TABLE HandleTable, PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 647 of file handle.c.
References APC_LEVEL, ASSERT, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExpBlockOnLockedHandleEntry(), FALSE, InterlockedCompareExchangePointer, KeGetCurrentIrql(), KeGetCurrentThread(), _HANDLE_TABLE_ENTRY::Object, ReadForWriteAccess, and TRUE.
Referenced by ExChangeHandle(), ExDestroyHandle(), ExDupHandleTable(), ExEnumHandleTable(), ExMapHandleToPointer(), ExMapHandleToPointerEx(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), and ExSweepHandleTable().
PHANDLE_TABLE_ENTRY ExpLookupHandleTableEntry (IN PHANDLE_TABLE HandleTable, IN EXHANDLE Handle)
Definition at line 3528 of file handle.c.
References Handle, HANDLE_VALUE_INC, LEVEL_CODE_MASK, LOWLEVEL_COUNT, MIDLEVEL_COUNT, NULL, PAGED_CODE, _EXHANDLE::TagBits, and _EXHANDLE::Value.
Referenced by ExChangeHandle(), ExDestroyHandle(), ExDestroyHandleTable(), ExDupHandleTable(), ExEnumHandleTable(), ExMapHandleToPointer(), ExMapHandleToPointerEx(), ExpAllocateHandleTableEntry(), ExpFreeHandleTableEntry(), ExpGetHandleInfo(), ExpMoveFreeHandles(), ExSetHandleInfo(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), and ExSweepHandleTable().
ULONG ExpMoveFreeHandles (IN PHANDLE_TABLE HandleTable)
Definition at line 382 of file handle.c.
References ExAcquireReleasePushLockExclusive(), EXASSERT, ExpInterlockedExchange(), ExpLookupHandleTableEntry(), GetNextSeq, Handle, HANDLE_TABLE_LOCKS, Index, InterlockedCompareExchange(), InterlockedExchange(), _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, _HANDLE_TABLE_ENTRY::Object, and _EXHANDLE::Value.
Referenced by ExpAllocateHandleTableEntry().
void ExpUpdateDebugInfo (PHANDLE_TABLE HandleTable, PETHREAD CurrentThread, HANDLE Handle, ULONG Type)
Definition at line 3884 of file handle.c.
References ASSERT, _HANDLE_TRACE_DEBUG_INFO::BitMaskFlags, _ETHREAD::Cid, _HANDLE_TRACE_DB_ENTRY::ClientId, _HANDLE_TRACE_DEBUG_INFO::CloseCompactionLock, _HANDLE_TRACE_DEBUG_INFO::CurrentStackIndex, DbgBreakPoint(), DbgPrint(), ExAcquireFastMutex(), ExDereferenceHandleDebugInfo(), ExReferenceHandleDebugInfo(), ExReleaseFastMutex(), FALSE, Handle, _HANDLE_TRACE_DB_ENTRY::Handle, HANDLE_TRACE_DB_CLOSE, HANDLE_TRACE_DB_OPEN, HANDLE_TRACE_DB_STACK_SIZE, HANDLE_TRACE_DEBUG_INFO_BREAK_ON_WRAP_AROUND, HANDLE_TRACE_DEBUG_INFO_CLEAN_DEBUG_INFO, HANDLE_TRACE_DEBUG_INFO_COMPACT_CLOSE_HANDLE, HANDLE_TRACE_DEBUG_INFO_WAS_SOMETIME_CLEANED, HANDLE_TRACE_DEBUG_INFO_WAS_WRAPPED_AROUND, Index, InterlockedIncrement, NOTHING, NULL, RtlWalkFrameChain(), RtlZeroMemory, _HANDLE_TRACE_DB_ENTRY::StackTrace, _HANDLE_TRACE_DEBUG_INFO::TableSize, _HANDLE_TRACE_DEBUG_INFO::TraceDb, TRUE, and _HANDLE_TRACE_DB_ENTRY::Type.
Referenced by ExCreateHandle(), ExDestroyHandle(), ExDupHandleTable(), ExMapHandleToPointer(), and ExMapHandleToPointerEx().
PHANDLE_TRACE_DEBUG_INFO ExReferenceHandleDebugInfo (IN PHANDLE_TABLE HandleTable)
Definition at line 2285 of file handle.c.
References ASSERT, ExpLockHandleTableShared, ExpUnlockHandleTableShared, InterlockedIncrement, KeGetCurrentThread(), NULL, and _HANDLE_TRACE_DEBUG_INFO::RefCount.
Referenced by ExpUpdateDebugInfo(), and NtQueryInformationProcess().
NTKERNELAPI VOID ExRemoveHandleTable (__inout PHANDLE_TABLE HandleTable)
Definition at line 893 of file handle.c.
References ExAcquirePushLockExclusive(), ExReleasePushLockExclusive(), InitializeListHead(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), PAGED_CODE, and RemoveEntryList().
Referenced by ExDestroyHandleTable(), PspInitPhase0(), and RtlpInitializeHandleTableForAtomTable().
NTKERNELAPI NTSTATUS ExSetHandleInfo (__inout PHANDLE_TABLE HandleTable, __in HANDLE Handle, __in PHANDLE_TABLE_ENTRY_INFO EntryInfo, __in BOOLEAN EntryLocked)
Definition at line 3682 of file handle.c.
References EX_ADDITIONAL_INFO_SIGNATURE, ExMapHandleToPointer(), ExpAllocateTablePagedPool(), ExpFreeTablePagedPool(), ExpLookupHandleTableEntry(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, _EXHANDLE::Index, _HANDLE_TABLE_ENTRY::InfoTable, InterlockedCompareExchangePointer, InterlockedIncrement, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), LOWLEVEL_COUNT, _HANDLE_TABLE_ENTRY::NextFreeTableEntry, NULL, Status, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
Referenced by ExDupHandleTable(), ObDuplicateObject(), and ObpCreateHandle().
VOID ExSetHandleTableStrictFIFO (IN PHANDLE_TABLE HandleTable)
Definition at line 3365 of file handle.c.
References TRUE.
Referenced by ObInitSystem(), and PspInitPhase0().
NTKERNELAPI NTSTATUS ExSnapShotHandleTables (__in PEX_SNAPSHOT_HANDLE_ENTRY SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
Definition at line 1437 of file handle.c.
References CONTAINING_RECORD, ExAcquirePushLockShared(), ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExReleasePushLockShared(), ExUnlockHandleTableEntry(), _LIST_ENTRY::Flink, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, Status, STATUS_SUCCESS, _HANDLE_TABLE::UniqueProcessId, and _EXHANDLE::Value.
Referenced by ObGetHandleInformation().
NTKERNELAPI NTSTATUS ExSnapShotHandleTablesEx (__in PEX_SNAPSHOT_HANDLE_ENTRY_EX SnapShotHandleEntry, __inout PSYSTEM_HANDLE_INFORMATION_EX HandleInformation, __in ULONG Length, __inout PULONG RequiredLength)
Definition at line 1583 of file handle.c.
References CONTAINING_RECORD, ExAcquirePushLockShared(), ExpIsValidObjectEntry, ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), ExReleasePushLockShared(), ExUnlockHandleTableEntry(), _LIST_ENTRY::Flink, _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, Status, STATUS_SUCCESS, _HANDLE_TABLE::UniqueProcessId, and _EXHANDLE::Value.
Referenced by ObGetHandleInformationEx().
NTKERNELAPI VOID ExSweepHandleTable (__in PHANDLE_TABLE HandleTable, __in EX_ENUMERATE_HANDLE_ROUTINE EnumHandleProcedure, __in PVOID EnumParameter)
Definition at line 1026 of file handle.c.
References ExpLockHandleTableEntry(), ExpLookupHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, Handle, HANDLE_VALUE_INC, LOWLEVEL_COUNT, NULL, PAGED_CODE, and _EXHANDLE::Value.
Referenced by ObClearProcessHandleTable(), and ObKillProcess().
NTKERNELAPI VOID FORCEINLINE ExUnlockHandleTableEntry (__inout PHANDLE_TABLE HandleTable, __inout PHANDLE_TABLE_ENTRY HandleTableEntry)
Definition at line 729 of file handle.c.
References APC_LEVEL, ASSERT, EXASSERT, EXHANDLE_TABLE_ENTRY_LOCK_BIT, ExUnblockPushLock(), InterlockedOr(), KeGetCurrentIrql(), KeGetCurrentThread(), NULL, and PAGED_CODE.
Referenced by ExChangeHandle(), ExCreateHandle(), ExDupHandleTable(), ExEnumHandleTable(), ExpGetHandleInfo(), ExSetHandleInfo(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ObAuditObjectAccess(), ObDupHandleProcedure(), ObDuplicateObject(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), and RtlpAtomMapAtomToHandleEntry().
Variable Documentation
LIST_ENTRY HandleTableListHead
Definition at line 59 of file handle.c.
EX_PUSH_LOCK HandleTableListLock
Definition at line 51 of file handle.c.
ULONG TotalTraceBuffers = 0
Definition at line 53 of file handle.c.
Referenced by ExDereferenceHandleDebugInfo(), and ExEnableHandleTracing().