Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/filter.c File Reference
filter.c File Reference
#include "FsRtlP.h"
Macros
#define Dbg (0x80000000)
Functions
__bcount (NumberOfBytes)
BOOLEAN FsRtlIsNtstatusExpected (__in NTSTATUS Exception)
BOOLEAN FsRtlIsTotalDeviceFailure (__in NTSTATUS Status)
NTSTATUS FsRtlNormalizeNtstatus (__in NTSTATUS Exception, __in NTSTATUS GenericException)
Macro Definition Documentation
#define Dbg (0x80000000)
Definition at line 43 of file filter.c.
Function Documentation
__bcount (NumberOfBytes)
Definition at line 121 of file filter.c.
References ExAllocatePoolWithTag, ExRaiseStatus(), NULL, and STATUS_INSUFFICIENT_RESOURCES.
BOOLEAN FsRtlIsNtstatusExpected (__in NTSTATUS Exception)
Definition at line 80 of file filter.c.
References FALSE, STATUS_ACCESS_VIOLATION, STATUS_DATATYPE_MISALIGNMENT, STATUS_ILLEGAL_INSTRUCTION, STATUS_INSTRUCTION_MISALIGNMENT, and TRUE.
Referenced by CcExceptionFilter(), FsRtlCancelNotify(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), FsRtlNormalizeNtstatus(), FsRtlNotifyFilterReportChange(), FsRtlPrepareMdlWriteDev(), and RawDispatch().
BOOLEAN FsRtlIsTotalDeviceFailure (__in NTSTATUS Status)
Definition at line 306 of file filter.c.
References FALSE, NT_SUCCESS, STATUS_CRC_ERROR, STATUS_DEVICE_DATA_ERROR, and TRUE.
Referenced by IopMountVolume().
NTSTATUS FsRtlNormalizeNtstatus (__in NTSTATUS Exception, __in NTSTATUS GenericException)
Definition at line 47 of file filter.c.
References FsRtlIsNtstatusExpected().
Referenced by CcCopyRead(), CcCopyWrite(), CcFastCopyRead(), CcFastCopyWrite(), CcGetVacbMiss(), CcInitializeCacheMap(), CcMapAndCopy(), CcMdlWriteComplete2(), and CcSetFileSizes().