Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/internal.c File Reference
internal.c File Reference
#include "iomgr.h"
#include <ioevent.h>
#include <hdlsblk.h>
#include <hdlsterm.h>
Data Structures
struct _REMOTE_LINK_BUFFER
struct _TRACKING_BUFFER
Macros
#define GET_OFFSET_LENGTH(CurrentSid, SidBase) ((ULONG) ((PCHAR) CurrentSid - (PCHAR) SidBase))
#define IO_INFINITE_RETRIES -1
#define IO_MAX_ALLOCATE_IRP_TRIES 30*60
#define IopKernelPointerBit 0x80000000
#define IsFileLocal(FileObject) (!((FileObject)->DeviceObject->Characteristics & FILE_REMOTE_DEVICE))
#define MESSAGE_SIZE
#define SynchronousIo(Irp, FileObject)
Typedefs
typedef LINK_TRACKING_INFORMATION FILE_VOLUMEID_WITH_TYPE
typedef LINK_TRACKING_INFORMATION * PFILE_VOLUMEID_WITH_TYPE
typedef struct _REMOTE_LINK_BUFFER * PREMOTE_LINK_BUFFER
typedef struct _TRACKING_BUFFER * PTRACKING_BUFFER
typedef struct _REMOTE_LINK_BUFFER REMOTE_LINK_BUFFER
typedef struct _TRACKING_BUFFER TRACKING_BUFFER
Functions
VOID IopAbortRequest (IN PKAPC Apc)
NTSTATUS IopAcquireFileObjectLock (IN PFILE_OBJECT FileObject, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN Alertable, OUT PBOOLEAN Interrupted)
VOID IopAllocateIrpCleanup (IN PFILE_OBJECT FileObject, IN PKEVENT EventObject OPTIONAL)
PIRP IopAllocateIrpMustSucceed (IN CCHAR StackSize)
PIRP IopAllocateReserveIrp (IN CCHAR StackSize)
VOID IopApcHardError (IN PVOID StartContext)
VOID IopBootLog (PUNICODE_STRING LogEntry, BOOLEAN Loaded)
NTSTATUS IopBootLogToFile (PUNICODE_STRING String)
NTSTATUS IopBuildFullDriverPath (IN PUNICODE_STRING KeyName, IN HANDLE KeyHandle, OUT PUNICODE_STRING FullPath)
BOOLEAN IopCallBootDriverReinitializationRoutines (VOID)
BOOLEAN IopCallDriverReinitializationRoutines (VOID)
VOID IopCancelAlertedRequest (IN PKEVENT Event, IN PIRP Irp)
NTSTATUS IopCheckGetQuotaBufferValidity (IN PFILE_GET_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG_PTR ErrorOffset)
BOOLEAN IopCheckHardErrorEmpty (VOID)
VOID IopCompletePageWrite (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopCompleteRequest (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopCompleteUnloadOrDelete (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN OnCleanStack, IN KIRQL Irql)
VOID IopConnectLinkTrackingPort (IN PVOID Parameter)
VOID IopCopyBootLogRegistryToFile (VOID)
VOID IopDeallocateApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopDecrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
VOID IopDecrementDeviceObjectRef (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AlwaysUnload, IN BOOLEAN OnCleanStack)
VOID IopDisassociateThreadIrp (VOID)
VOID IopDropIrp (IN PIRP Irp, IN PFILE_OBJECT FileObject)
VOID IopExceptionCleanup (IN PFILE_OBJECT FileObject, IN PIRP Irp, IN PKEVENT EventObject OPTIONAL, IN PKEVENT KernelEvent OPTIONAL)
LONG IopExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointer, OUT PNTSTATUS ExceptionCode)
VOID IopFreeIrpAndMdls (IN PIRP Irp)
VOID IopFreeReserveIrp (IN CCHAR PriorityBoost)
NTSTATUS IopGetBasicInformationFile (IN PFILE_OBJECT FileObject, IN PFILE_BASIC_INFORMATION BasicInformationBuffer)
PDEVICE_OBJECT IopGetDeviceAttachmentBase (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopGetDriverNameFromKeyNode (IN HANDLE KeyHandle, OUT PUNICODE_STRING DriverName)
NTSTATUS IopGetDriverPathInformation (IN PFILE_OBJECT FileObject, IN PFILE_FS_DRIVER_PATH_INFORMATION FsDpInfo, IN ULONG Length)
NTSTATUS IopGetFileInformation (IN PFILE_OBJECT FileObject, IN ULONG Length, IN FILE_INFORMATION_CLASS FileInformationClass, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
BOOLEAN IopGetMountFlag (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopGetRegistryKeyInformation (IN HANDLE KeyHandle, OUT PKEY_FULL_INFORMATION *Information)
NTSTATUS IopGetRegistryValue (IN HANDLE KeyHandle, IN PWSTR ValueName, OUT PKEY_VALUE_FULL_INFORMATION *Information)
NTSTATUS IopGetRegistryValues (IN HANDLE KeyHandle, IN PKEY_VALUE_FULL_INFORMATION *ValueList)
NTSTATUS IopGetSetObjectId (IN PFILE_OBJECT FileObject, IN OUT PVOID Buffer, IN ULONG Length, IN ULONG Function)
NTSTATUS IopGetVolumeId (IN PFILE_OBJECT FileObject, IN OUT PFILE_VOLUMEID_WITH_TYPE ObjectId, IN ULONG Length)
VOID IopHardErrorThread (IN PVOID StartContext)
VOID IopIncrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
VOID IopInitializeBootLogging (PLOADER_PARAMETER_BLOCK LoaderBlock, PCHAR HeaderString)
NTSTATUS IopInitializeIrpStackProfiler (VOID)
ULONG FASTCALL IopInterlockedDecrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
ULONG FASTCALL IopInterlockedIncrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
PLIST_ENTRY FASTCALL IopInterlockedInsertHeadList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
PLIST_ENTRY FASTCALL IopInterlockedInsertTailList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
PLIST_ENTRY FASTCALL IopInterlockedRemoveHeadList (IN PLIST_ENTRY ListHead)
NTSTATUS IopInvalidateVolumesForDevice (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopInvalidDeviceRequest (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
VOID IopIrpStackProfilerTimer (IN struct _KDPC *Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
LOGICAL IopIsSameMachine (IN PFILE_OBJECT SourceFile, IN HANDLE TargetFile)
NTSTATUS IopLoadDriver (IN HANDLE KeyHandle, IN BOOLEAN CheckForSafeBoot, IN BOOLEAN IsFilter, OUT NTSTATUS *DriverEntryStatus)
VOID IopLoadFileSystemDriver (IN PDEVICE_OBJECT DeviceObject)
VOID IopLoadUnloadDriver (IN PVOID Parameter)
NTSTATUS IopLookupBusStringFromID (IN HANDLE KeyHandle, IN INTERFACE_TYPE InterfaceType, OUT PWCHAR Buffer, IN ULONG Length, OUT PULONG BusFlags OPTIONAL)
VOID IopMarshalIds (OUT PTRACKING_BUFFER TrackingBuffer, IN PFILE_VOLUMEID_WITH_TYPE TargetVolumeId, IN PFILE_OBJECTID_BUFFER TargetObjectId, IN PFILE_TRACKING_INFORMATION TrackingInfo)
PVPB IopMountInitializeVpb (IN PDEVICE_OBJECT DeviceObject, IN PDEVICE_OBJECT AttachedDevice, IN ULONG RawMountOnly)
NTSTATUS IopMountVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount, IN BOOLEAN DeviceLockAlreadyHeld, IN BOOLEAN Alertable, OUT PVPB *Vpb)
NTSTATUS IopOpenLinkOrRenameTarget (OUT PHANDLE TargetHandle, IN PIRP Irp, IN PVOID RenameBuffer, IN PFILE_OBJECT FileObject)
NTSTATUS IopOpenRegistryKey (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess, IN BOOLEAN Create)
VOID IopProcessIrpStackProfiler (VOID)
NTSTATUS IopQueryXxxInformation (IN PFILE_OBJECT FileObject, IN ULONG InformationClass, IN ULONG Length, IN KPROCESSOR_MODE Mode, OUT PVOID Information, OUT PULONG ReturnedLength, IN BOOLEAN FileInformation)
VOID IopRaiseHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID IopRaiseInformationalHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID IopReadyDeviceObjects (IN PDRIVER_OBJECT DriverObject)
PDRIVER_OBJECT IopReferenceDriverObjectByName (IN PUNICODE_STRING DriverName)
BOOLEAN IopReferenceVerifyVpb (IN PDEVICE_OBJECT DeviceObject, OUT PVPB *Vpb, OUT PDEVICE_OBJECT *FsDeviceObject)
PIOP_HARD_ERROR_PACKET IopRemoveHardErrorPacket (VOID)
NTSTATUS IopResurrectDriver (PDRIVER_OBJECT DriverObject)
BOOLEAN IopSafebootDriverLoad (PUNICODE_STRING DriverId)
NTSTATUS IopSendMessageToTrackService (IN PFILE_VOLUMEID_WITH_TYPE SourceVolumeId, IN PFILE_OBJECTID_BUFFER SourceObjectId, IN PFILE_TRACKING_INFORMATION TargetObjectInformation)
NTSTATUS IopSetEaOrQuotaInformationFile (IN HANDLE FileHandle, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PVOID Buffer, IN ULONG Length, IN BOOLEAN SetEa)
NTSTATUS IopSetRemoteLink (IN PFILE_OBJECT FileObject, IN PFILE_OBJECT DestinationFileObject OPTIONAL, IN PFILE_TRACKING_INFORMATION FileInformation OPTIONAL)
VOID IopStartApcHardError (IN PVOID StartContext)
NTSTATUS IopSynchronousApiServiceTail (IN NTSTATUS ReturnedStatus, IN PKEVENT Event, IN PIRP Irp, IN KPROCESSOR_MODE RequestorMode, IN PIO_STATUS_BLOCK LocalIoStatus, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS IopSynchronousServiceTail (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PFILE_OBJECT FileObject, IN BOOLEAN DeferredIoCompletion, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN SynchronousIo, IN TRANSFER_TYPE TransferType)
VOID IopTimerDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
NTSTATUS IopTrackLink (IN PFILE_OBJECT FileObject, IN OUT PIO_STATUS_BLOCK IoStatusBlock, IN PFILE_TRACKING_INFORMATION FileInformation, IN ULONG Length, IN PKEVENT Event, IN KPROCESSOR_MODE RequestorMode)
VOID IopUnMarshalIds (IN FILE_TRACKING_INFORMATION *TrackingInformation, OUT FILE_VOLUMEID_WITH_TYPE *TargetVolumeId, OUT GUID *TargetObjectId, OUT GUID *TargetMachineId)
VOID IopUserCompletion (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID IopUserRundown (IN PKAPC Apc)
BOOLEAN IopVerifyDeviceObjectOnStack (IN PDEVICE_OBJECT BaseDeviceObject, IN PDEVICE_OBJECT TopDeviceObject)
BOOLEAN IopVerifyDiskSignature (IN PDRIVE_LAYOUT_INFORMATION_EX DriveLayout, IN PARC_DISK_SIGNATURE LoaderDiskBlock, OUT PULONG DiskSignature)
BOOLEAN IopVerifyDriverObjectOnStack (IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_OBJECT DriverObject)
NTSTATUS IopXxxControlFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, IN ULONG IoControlCode, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN DeviceIoControl)
VOID RtlAssert (IN PVOID FailedAssertion, IN PVOID FileName, IN ULONG LineNumber, IN PCHAR Message OPTIONAL)
Variables
static PBOOT_LOG_RECORD BootLogRecord
PIRP IopDeadIrp
Macro Definition Documentation
#define GET_OFFSET_LENGTH (CurrentSid, SidBase) ((ULONG) ((PCHAR) CurrentSid - (PCHAR) SidBase))
Referenced by IopCheckGetQuotaBufferValidity().
#define IO_INFINITE_RETRIES -1
Definition at line 43 of file internal.c.
Referenced by IopAllocateIrpMustSucceed().
#define IO_MAX_ALLOCATE_IRP_TRIES 30*60
Definition at line 42 of file internal.c.
#define IopKernelPointerBit 0x80000000
Definition at line 48 of file internal.c.
Referenced by IopCompleteRequest().
#define IsFileLocal (FileObject) (!((FileObject)->DeviceObject->Characteristics & FILE_REMOTE_DEVICE))
Definition at line 40 of file internal.c.
Referenced by IopTrackLink().
#define MESSAGE_SIZE
Value:
((2 * sizeof(FILE_VOLUMEID_WITH_TYPE)) + \
                            sizeof( FILE_OBJECTID_BUFFER ) +              \
                            sizeof( GUID ) + \
                            sizeof( NTSTATUS ) + \
                            sizeof( ULONG ) )
Referenced by IopConnectLinkTrackingPort().
#define SynchronousIo (Irp, FileObject)
Value:
(\
    (Irp->Flags & IRP_SYNCHRONOUS_API) ||   \
    (FileObject == NULL ? 0 : FileObject->Flags & FO_SYNCHRONOUS_IO) )
Referenced by IopCompleteRequest().
Typedef Documentation
typedef LINK_TRACKING_INFORMATION FILE_VOLUMEID_WITH_TYPE
Definition at line 51 of file internal.c.
typedef LINK_TRACKING_INFORMATION * PFILE_VOLUMEID_WITH_TYPE
Definition at line 51 of file internal.c.
typedef struct _REMOTE_LINK_BUFFER * PREMOTE_LINK_BUFFER
typedef struct _TRACKING_BUFFER * PTRACKING_BUFFER
typedef struct _REMOTE_LINK_BUFFER REMOTE_LINK_BUFFER
typedef struct _TRACKING_BUFFER TRACKING_BUFFER
Function Documentation
VOID IopAbortRequest (IN PKAPC Apc)
Definition at line 185 of file internal.c.
References IopCompleteRequest(), and PAGED_CODE.
Referenced by IopfCompleteRequest(), and IoRaiseHardError().
NTSTATUS IopAcquireFileObjectLock (IN PFILE_OBJECT FileObject, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN Alertable, OUT PBOOLEAN Interrupted)
Definition at line 222 of file internal.c.
References Executive, FALSE, InterlockedDecrement, InterlockedExchange(), InterlockedIncrement, KeSetEvent(), KeWaitForSingleObject(), NULL, ObReferenceObject, PAGED_CODE, STATUS_ALERTED, STATUS_SUCCESS, STATUS_USER_APC, and TRUE.
Referenced by BuildQueryDirectoryIrp(), IopCloseFile(), IopGetSetSecurityObject(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
VOID IopAllocateIrpCleanup (IN PFILE_OBJECT FileObject, IN PKEVENT EventObject OPTIONAL)
Definition at line 326 of file internal.c.
References ARGUMENT_PRESENT, FO_SYNCHRONOUS_IO, IopReleaseFileObjectLock, ObDereferenceObject(), and PAGED_CODE.
Referenced by BuildQueryDirectoryIrp(), IopGetSetSecurityObject(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
PIRP IopAllocateIrpMustSucceed (IN CCHAR StackSize)
Definition at line 378 of file internal.c.
References FALSE, IO_INFINITE_RETRIES, IoAllocateIrp(), KeDelayExecutionThread(), KernelMode, PIRP, and _LARGE_INTEGER::QuadPart.
Referenced by IoCancelFileOpen(), IopCloseFile(), and IopDeleteFile().
PIRP IopAllocateReserveIrp (IN CCHAR StackSize)
Definition at line 10287 of file internal.c.
References _IOP_RESERVE_IRP_ALLOCATOR::Event, Executive, FALSE, InterlockedExchange(), IoInitializeIrp(), IopReserveIrpAllocator, IoSizeOfIrp, _IOP_RESERVE_IRP_ALLOCATOR::IrpAllocated, KernelMode, KeWaitForSingleObject(), NULL, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrp, _IOP_RESERVE_IRP_ALLOCATOR::ReserveIrpStackSize, and VOID.
Referenced by IoPageRead().
VOID IopApcHardError (IN PVOID StartContext)
Definition at line 433 of file internal.c.
References ExFreePool(), IopRaiseHardError(), _IOP_APC_HARD_ERROR_PACKET::Irp, _IOP_APC_HARD_ERROR_PACKET::RealDeviceObject, and _IOP_APC_HARD_ERROR_PACKET::Vpb.
Referenced by IopStartApcHardError().
VOID IopBootLog (PUNICODE_STRING LogEntry, BOOLEAN Loaded)
Definition at line 9549 of file internal.c.
References BOOTLOG_STRSIZE, CmRegistryMachineSystemCurrentControlSetControlBootLog, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _BOOT_LOG_RECORD::FileLogging, IopBootLogToFile(), IopOpenRegistryKey(), IopSetRegistryStringValue(), KEY_ALL_ACCESS, KeyName, _BOOT_LOG_RECORD::LoadedString, _BOOT_LOG_RECORD::NextKey, _BOOT_LOG_RECORD::NotLoadedString, NT_SUCCESS, NULL, PAGED_CODE, _BOOT_LOG_RECORD::Resource, RtlAppendUnicodeStringToString(), RtlCopyUnicodeString(), RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), Space, Status, swprintf, TRUE, and ZwClose().
Referenced by IopInitializeBootLogging(), and IopLoadDriver().
NTSTATUS IopBootLogToFile (PUNICODE_STRING String)
Definition at line 9794 of file internal.c.
References _UNICODE_STRING::Buffer, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FILE_ATTRIBUTE_NORMAL, FILE_CREATED, FILE_NON_DIRECTORY_FILE, FILE_OPEN_IF, FILE_SEQUENTIAL_ONLY, FILE_SHARE_READ, FILE_SYNCHRONOUS_IO_NONALERT, FILE_WRITE_TO_END_OF_FILE, GENERIC_WRITE, _LARGE_INTEGER::HighPart, _IO_STATUS_BLOCK::Information, InitializeObjectAttributes, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), _UNICODE_STRING::Length, _BOOT_LOG_RECORD::LogFileName, _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, _BOOT_LOG_RECORD::Resource, RtlInitUnicodeString(), Status, STATUS_SUCCESS, TRUE, ZwClose(), ZwCreateFile(), and ZwWriteFile().
Referenced by IopBootLog(), and IopCopyBootLogRegistryToFile().
NTSTATUS IopBuildFullDriverPath (IN PUNICODE_STRING KeyName, IN HANDLE KeyHandle, OUT PUNICODE_STRING FullPath)
Definition at line 3340 of file internal.c.
References _KEY_VALUE_FULL_INFORMATION::DataLength, ExAllocatePool, ExFreePool(), IopGetRegistryValue(), KEY_VALUE_DATA, NT_SUCCESS, NULL, PagedPool, RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by IopLoadDriver().
BOOLEAN IopCallBootDriverReinitializationRoutines (VOID)
Definition at line 10118 of file internal.c.
References CONTAINING_RECORD, _REINIT_PACKET::Context, _DRIVER_EXTENSION::Count, _DRIVER_OBJECT::DriverExtension, _REINIT_PACKET::DriverObject, _REINIT_PACKET::DriverReinitializationRoutine, DRVO_BOOTREINIT_REGISTERED, ExFreePool(), FALSE, _DRIVER_OBJECT::Flags, IopBootDriverReinitializeQueueHead, IopInterlockedRemoveHeadList(), and TRUE.
BOOLEAN IopCallDriverReinitializationRoutines (VOID)
Definition at line 10165 of file internal.c.
References CONTAINING_RECORD, _REINIT_PACKET::Context, _DRIVER_EXTENSION::Count, _DRIVER_OBJECT::DriverExtension, _REINIT_PACKET::DriverObject, _REINIT_PACKET::DriverReinitializationRoutine, DRVO_REINIT_REGISTERED, ExFreePool(), FALSE, _DRIVER_OBJECT::Flags, IopDriverReinitializeQueueHead, IopInterlockedRemoveHeadList(), PAGED_CODE, and TRUE.
Referenced by IoInitSystem(), and IopLoadUnloadDriver().
VOID IopCancelAlertedRequest (IN PKEVENT Event, IN PIRP Irp)
Definition at line 467 of file internal.c.
References APC_LEVEL, Executive, FALSE, IoCancelIrp(), KeDelayExecutionThread(), KeLowerIrql, KeRaiseIrql, KeReadStateEvent(), KernelMode, KeWaitForSingleObject(), NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, and VOID.
Referenced by IopQueryXxxInformation(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoSetInformation(), NtQueryInformationFile(), and NtSetInformationFile().
NTSTATUS IopCheckGetQuotaBufferValidity (IN PFILE_GET_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG_PTR ErrorOffset)
Definition at line 574 of file internal.c.
References FIELD_OFFSET, GET_OFFSET_LENGTH, _FILE_GET_QUOTA_INFORMATION::NextEntryOffset, PAGED_CODE, RtlLengthSid(), RtlValidSid(), _FILE_GET_QUOTA_INFORMATION::Sid, STATUS_QUOTA_LIST_INCONSISTENT, STATUS_SUCCESS, and _SID::SubAuthority.
Referenced by NtQueryQuotaInformationFile().
BOOLEAN IopCheckHardErrorEmpty (VOID)
Definition at line 3112 of file internal.c.
References ExAcquireFastLock, ExReleaseFastLock, FALSE, IopCurrentHardError, IopHardError, IsListEmpty, NULL, _IOP_HARD_ERROR_QUEUE::ThreadStarted, TRUE, UNREFERENCED_PARAMETER, _IOP_HARD_ERROR_QUEUE::WorkQueue, and _IOP_HARD_ERROR_QUEUE::WorkQueueSpinLock.
Referenced by IopHardErrorThread().
VOID IopCompletePageWrite (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 986 of file internal.c.
References CONTAINING_RECORD, IoFreeIrp(), IRP, NT_ERROR, PIRP, and UNREFERENCED_PARAMETER.
Referenced by IopfCompleteRequest().
VOID IopCompleteRequest (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 1086 of file internal.c.
References ASSERT, _FILE_OBJECT::CompletionContext, CONTAINING_RECORD, CurrentApcEnvironment, _FILE_OBJECT::Event, except, ExFreePool(), FALSE, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_SYNCHRONOUS_IO, IO_REPARSE_TAG_MOUNT_POINT, IoFreeIrp(), IoFreeMdl(), IopCompletionPacketIrp, IopDequeueThreadIrp, IopDoNameTransmogrify(), IopExceptionFilter(), IopKernelPointerBit, IopUpdateOtherTransferCount(), IopUpdateReadTransferCount(), IopUpdateWriteTransferCount(), IopUserCompletion(), IopUserRundown(), IOVP_COMPLETE_REQUEST, IRP, IRP_BUFFERED_IO, IRP_CREATE_OPERATION, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_OB_QUERY_NAME, IRP_READ_OPERATION, IRP_RETRY_IO_COMPLETION, IRP_SYNCHRONOUS_API, IRP_WRITE_OPERATION, KeInitializeApc(), KeInsertQueue(), KeInsertQueueApc(), KeMemoryBarrierWithoutFence, KeSetEvent(), _IO_COMPLETION_CONTEXT::Key, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, _MDL::Next, NT_ERROR, NULL, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), PIRP, _IO_COMPLETION_CONTEXT::Port, PsGetCurrentThread(), _REPARSE_DATA_BUFFER::ReparseDataLength, _REPARSE_DATA_BUFFER::ReparseTag, _REPARSE_DATA_BUFFER::Reserved, RtlCopyMemory, STATUS_MULTIPLE_FAULT_VIOLATION, STATUS_REPARSE, STATUS_SUCCESS, STATUS_VERIFY_REQUIRED, SynchronousIo, _ETHREAD::Tcb, TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by IopAbortRequest(), IopfCompleteRequest(), IopSynchronousServiceTail(), IoRetryIrpCompletions(), NtQueryInformationFile(), and NtSetInformationFile().
VOID IopCompleteUnloadOrDelete (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN OnCleanStack, IN KIRQL Irql)
Definition at line 707 of file internal.c.
References ASSERT, DelayedWorkQueue, _DEVOBJ_EXTENSION::DeviceNode, _DRIVER_OBJECT::DeviceObject, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_UNLOAD_PENDING, _LOAD_PACKET::DriverObject, DRVO_BASE_FILESYSTEM_DRIVER, DRVO_UNLOAD_INVOKED, _LOAD_PACKET::Event, Executive, ExInitializeWorkItem, ExQueueWorkItem(), _DEVOBJ_EXTENSION::ExtensionFlags, FALSE, _FAST_IO_DISPATCH::FastIoDetachDevice, FIELD_OFFSET, _DRIVER_OBJECT::Flags, IopChainDereferenceComplete(), IopGetDeviceAttachmentBase(), IopInsertRemoveDevice(), IopLoadUnloadDriver(), KeAcquireQueuedSpinLock(), KeInitializeEvent(), KeReleaseQueuedSpinLock(), KernelMode, KeWaitForSingleObject(), LockQueueIoDatabaseLock, NotificationEvent, NULL, ObDereferenceObject(), ObDereferenceSecurityDescriptor(), ObMakeTemporaryObject(), _FAST_IO_DISPATCH::SizeOfFastIoDispatch, TRUE, VOID, and _LOAD_PACKET::WorkQueueItem.
Referenced by IoDeleteDevice(), IoDetachDevice(), and IopDecrementDeviceObjectRef().
VOID IopConnectLinkTrackingPort (IN PVOID Parameter)
Definition at line 1572 of file internal.c.
References _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, _LINK_TRACKING_PACKET::Event, FALSE, _LINK_TRACKING_PACKET::FinalStatus, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, IopLinkTrackingServiceEvent, IopLinkTrackingServiceObject, KeReadStateEvent(), KernelMode, KeSetEvent(), LpcPortObjectType, MESSAGE_SIZE, NT_SUCCESS, NtClose(), NtConnectPort(), NULL, ObReferenceObjectByHandle, PAGED_CODE, RtlInitUnicodeString(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and TRUE.
Referenced by IopSendMessageToTrackService().
VOID IopCopyBootLogRegistryToFile (VOID)
Definition at line 9664 of file internal.c.
References BOOTLOG_STRSIZE, CmRegistryMachineSystemCurrentControlSetControlBootLog, _KEY_VALUE_FULL_INFORMATION::DataOffset, _TIME_FIELDS::Day, ExAcquireResourceExclusiveLite(), ExFreePool(), ExReleaseResourceLite(), ExSystemTimeToLocalTime(), FALSE, _BOOT_LOG_RECORD::FileLogging, _BOOT_LOG_RECORD::HeaderString, _TIME_FIELDS::Hour, Index, IopBootLogToFile(), IopGetRegistryValue(), IopOpenRegistryKey(), KeBootTime, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KEY_ALL_ACCESS, KeyName, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, _BOOT_LOG_RECORD::NextKey, NT_SUCCESS, NULL, PAGED_CODE, _BOOT_LOG_RECORD::Resource, RtlAnsiStringToUnicodeString(), RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), RtlTimeToTimeFields(), _TIME_FIELDS::Second, sprintf(), Status, swprintf, TRUE, _TIME_FIELDS::Year, ZwClose(), and ZwDeleteKey().
Referenced by NtInitializeRegistry().
VOID IopDeallocateApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 1826 of file internal.c.
References ExFreePool(), PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by IoRaiseHardError(), and IoRaiseInformationalHardError().
VOID IopDecrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10711 of file internal.c.
References FALSE, and IopDecrementDeviceObjectRef().
VOID IopDecrementDeviceObjectRef (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AlwaysUnload, IN BOOLEAN OnCleanStack)
Definition at line 4433 of file internal.c.
References ASSERT, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_UNLOAD_PENDING, IopCompleteUnloadOrDelete(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and LockQueueIoDatabaseLock.
Referenced by IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopCheckVpbMounted(), IopDecrementDeviceObjectHandleCount(), IopDeleteFile(), IopLoadFileSystemDriver(), IopParseDevice(), and IopShutdownBaseFileSystems().
VOID IopDisassociateThreadIrp (VOID)
Definition at line 1689 of file internal.c.
References APC_LEVEL, CONTAINING_RECORD, _IO_STACK_LOCATION::DeviceObject, _IO_ERROR_LOG_PACKET::ErrorCode, _LIST_ENTRY::Flink, InitializeListHead(), IO_DRIVER_CANCEL_TIMEOUT, IoAllocateErrorLogEntry(), IoGetCurrentIrpStackLocation, IopDeadIrp, IoWriteErrorLogEntry(), IRP, _ETHREAD::IrpList, IsListEmpty, KeAcquireQueuedSpinLock(), KeLowerIrql, KeRaiseIrql, KeReleaseQueuedSpinLock(), LockQueueIoCompletionLock, NULL, PIRP, PsGetCurrentThread(), and RemoveHeadList().
Referenced by IoCancelThreadIo().
VOID IopDropIrp (IN PIRP Irp, IN PFILE_OBJECT FileObject)
Definition at line 1876 of file internal.c.
References ExFreePool(), IoFreeIrp(), IoFreeMdl(), IRP_CREATE_OPERATION, IRP_DEALLOCATE_BUFFER, IRP_SYNCHRONOUS_API, _MDL::Next, ObDereferenceObject(), and ObDereferenceObjectEx().
Referenced by IopfCompleteRequest().
VOID IopExceptionCleanup (IN PFILE_OBJECT FileObject, IN PIRP Irp, IN PKEVENT EventObject OPTIONAL, IN PKEVENT KernelEvent OPTIONAL)
Definition at line 1989 of file internal.c.
References ARGUMENT_PRESENT, ExFreePool(), FO_SYNCHRONOUS_IO, IoFreeIrp(), IoFreeMdl(), IopReleaseFileObjectLock, NULL, ObDereferenceObject(), and PAGED_CODE.
Referenced by BuildQueryDirectoryIrp(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
LONG IopExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointer, OUT PNTSTATUS ExceptionCode)
Definition at line 1938 of file internal.c.
References EXCEPTION_EXECUTE_HANDLER, STATUS_DATATYPE_MISALIGNMENT, STATUS_DATATYPE_MISALIGNMENT_ERROR, and STATUS_IN_PAGE_ERROR.
Referenced by IopCompleteRequest(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
VOID IopFreeIrpAndMdls (IN PIRP Irp)
Definition at line 2084 of file internal.c.
References IoFreeIrp(), IoFreeMdl(), _MDL::Next, and NULL.
Referenced by IopfCompleteRequest().
VOID IopFreeReserveIrp (IN CCHAR PriorityBoost)
Definition at line 10327 of file internal.c.
References _IOP_RESERVE_IRP_ALLOCATOR::Event, FALSE, InterlockedExchange(), IopReserveIrpAllocator, _IOP_RESERVE_IRP_ALLOCATOR::IrpAllocated, and KeSetEvent().
Referenced by IopfCompleteRequest().
NTSTATUS IopGetBasicInformationFile (IN PFILE_OBJECT FileObject, IN PFILE_BASIC_INFORMATION BasicInformationBuffer)
Definition at line 10352 of file internal.c.
References FALSE, _FAST_IO_DISPATCH::FastIoQueryBasicInfo, FileBasicInformation, FO_SYNCHRONOUS_IO, IoGetRelatedDeviceObject(), IopGetFileInformation(), PAGED_CODE, _IO_STATUS_BLOCK::Status, and TRUE.
Referenced by IopOpenLinkOrRenameTarget().
PDEVICE_OBJECT IopGetDeviceAttachmentBase (IN PDEVICE_OBJECT DeviceObject)
Definition at line 4384 of file internal.c.
References _DEVOBJ_EXTENSION::AttachedTo, and NULL.
Referenced by IoGetDeviceAttachmentBaseRef(), IopCompleteUnloadOrDelete(), IopGetDevicePDO(), and IopVerifyDriverObjectOnStack().
NTSTATUS IopGetDriverNameFromKeyNode (IN HANDLE KeyHandle, OUT PUNICODE_STRING DriverName)
Definition at line 2127 of file internal.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, ExAllocatePool, ExFreePool(), FileSystemType, IopGetRegistryValue(), KeyBasicInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _KEY_BASIC_INFORMATION::Name, _KEY_BASIC_INFORMATION::NameLength, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, RecognizerType, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), STATUS_ILL_FORMED_SERVICE_ENTRY, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and ZwQueryKey().
Referenced by IopLoadDriver(), and IopUnloadDriver().
NTSTATUS IopGetDriverPathInformation (IN PFILE_OBJECT FileObject, IN PFILE_FS_DRIVER_PATH_INFORMATION FsDpInfo, IN ULONG Length)
Definition at line 10588 of file internal.c.
References _UNICODE_STRING::Buffer, FIELD_OFFSET, IoDriverObjectType, IopVerifyDriverObjectOnStack(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), KernelMode, _UNICODE_STRING::Length, LockQueueIoDatabaseLock, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByName(), STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by NtQueryVolumeInformationFile().
NTSTATUS IopGetFileInformation (IN PFILE_OBJECT FileObject, IN ULONG Length, IN FILE_INFORMATION_CLASS FileInformationClass, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
Definition at line 2315 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STATUS_BLOCK::Information, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopQueueThreadIrp(), IRP_BUFFERED_IO, IRP_MJ_QUERY_INFORMATION, IRP_OB_QUERY_NAME, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, SynchronizationEvent, and VOID.
Referenced by IopGetBasicInformationFile(), and IopQueryNameInternal().
BOOLEAN IopGetMountFlag (IN PDEVICE_OBJECT DeviceObject)
Definition at line 2474 of file internal.c.
References FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoVpbLock, TRUE, and VPB_MOUNTED.
Referenced by NtQueryVolumeInformationFile().
NTSTATUS IopGetRegistryKeyInformation (IN HANDLE KeyHandle, OUT PKEY_FULL_INFORMATION * Information)
Definition at line 2522 of file internal.c.
References ExAllocatePool, ExFreePool(), KeyFullInformation, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and ZwQueryKey().
NTSTATUS IopGetRegistryValue (IN HANDLE KeyHandle, IN PWSTR ValueName, OUT PKEY_VALUE_FULL_INFORMATION * Information)
Definition at line 2606 of file internal.c.
References ALIGN_POINTER_OFFSET, ASSERT, ExAllocatePool, ExFreePool(), KeyValueFullInformation, NonPagedPool, NT_SUCCESS, PAGED_CODE, RtlInitUnicodeString(), STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, wcslen(), and ZwQueryValueKey().
Referenced by IopBuildFullDriverPath(), IopCopyBootLogRegistryToFile(), IopGetDriverNameFromKeyNode(), IopGetRegistryValues(), and IopLoadDriver().
NTSTATUS IopGetRegistryValues (IN HANDLE KeyHandle, IN PKEY_VALUE_FULL_INFORMATION * ValueList)
Definition at line 2733 of file internal.c.
References IopGetRegistryValue(), NT_SUCCESS, NULL, PAGED_CODE, STATUS_OBJECT_NAME_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS IopGetSetObjectId (IN PFILE_OBJECT FileObject, IN OUT PVOID Buffer, IN ULONG Length, IN ULONG Function)
Definition at line 2814 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, FSCTL_LMR_GET_LINK_TRACKING_INFORMATION, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_KERNEL_CALL, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NULL, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by IopTrackLink().
NTSTATUS IopGetVolumeId (IN PFILE_OBJECT FileObject, IN OUT PFILE_VOLUMEID_WITH_TYPE ObjectId, IN ULONG Length)
Definition at line 2947 of file internal.c.
References ASSERT, Executive, FALSE, FileFsObjectIdInformation, _IO_STACK_LOCATION::FileObject, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NtfsLinkTrackingInformation, NULL, _FILE_FS_OBJECTID_INFORMATION::ObjectId, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and UNREFERENCED_PARAMETER.
Referenced by IopTrackLink().
VOID IopHardErrorThread (IN PVOID StartContext)
Definition at line 3140 of file internal.c.
References _UNICODE_STRING::Buffer, _IOP_HARD_ERROR_PACKET::ErrorStatus, Executive, ExFreePool(), ExRaiseHardError(), ExReadyForErrors, FALSE, IopCheckHardErrorEmpty(), IopHardError, IopRemoveHardErrorPacket(), KernelMode, KeWaitForSingleObject(), NULL, OptionOkNoWait, PAGED_CODE, _IOP_HARD_ERROR_PACKET::String, TRUE, UNREFERENCED_PARAMETER, VOID, and _IOP_HARD_ERROR_QUEUE::WorkQueueSemaphore.
Referenced by IoInitSystem().
VOID IopIncrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10702 of file internal.c.
References IopInterlockedIncrementUlong(), and LockQueueIoDatabaseLock.
VOID IopInitializeBootLogging (PLOADER_PARAMETER_BLOCK LoaderBlock, PCHAR HeaderString)
Definition at line 9430 of file internal.c.
References BOOTLOG_LOADED, BOOTLOG_NOT_LOADED, _STRING::Buffer, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAllocatePool, ExInitializeResourceLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _BOOT_LOG_RECORD::HeaderString, IopBootLog(), _STRING::Length, _UNICODE_STRING::Length, _BOOT_LOG_RECORD::LoadedString, _LOADER_PARAMETER_BLOCK::LoadOrderListHead, _STRING::MaximumLength, NonPagedPool, _BOOT_LOG_RECORD::NotLoadedString, NT_SUCCESS, NULL, PAGED_CODE, PsLoadedModuleList, PsLoadedModuleResource, _BOOT_LOG_RECORD::Resource, RtlAnsiStringToUnicodeString(), RtlCreateUnicodeStringFromAsciiz(), RtlFindMessage(), RtlZeroMemory, Status, strlen(), _MESSAGE_RESOURCE_ENTRY::Text, TRUE, and UNICODE_NULL.
NTSTATUS IopInitializeIrpStackProfiler (VOID)
Definition at line 10719 of file internal.c.
References _IOP_IRP_STACK_PROFILER::Dpc, IOP_PROFILE_TIME_PERIOD, IopIrpStackProfiler, IopIrpStackProfilerTimer(), KeInitializeDpc(), KeInitializeTimer(), KeSetTimerEx(), MAX_LOOKASIDE_IRP_STACK_COUNT, _IOP_IRP_STACK_PROFILER::Profile, _LARGE_INTEGER::QuadPart, RtlZeroMemory, STATUS_SUCCESS, _IOP_IRP_STACK_PROFILER::Timer, and _IOP_IRP_STACK_PROFILER::TriggerCount.
Referenced by IoInitSystem().
ULONG FASTCALL IopInterlockedDecrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
Definition at line 10035 of file internal.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and UNREFERENCED_PARAMETER.
Referenced by IopDeleteFile(), IopfCompleteRequest(), IopMountVolume(), IoUnregisterFileSystem(), and IoVerifyVolume().
ULONG FASTCALL IopInterlockedIncrementUlong (IN KSPIN_LOCK_QUEUE_NUMBER Number, IN OUT PLONG Addend)
Definition at line 10077 of file internal.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and UNREFERENCED_PARAMETER.
Referenced by IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopDeleteFile(), IopIncrementDeviceObjectHandleCount(), IopMountVolume(), IopParseDevice(), IopShutdownBaseFileSystems(), and IoRegisterFileSystem().
PLIST_ENTRY FASTCALL IopInterlockedInsertHeadList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
Definition at line 9904 of file internal.c.
References _LIST_ENTRY::Flink, InsertHeadList(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
Referenced by IoRegisterLastChanceShutdownNotification(), and IoRegisterShutdownNotification().
PLIST_ENTRY FASTCALL IopInterlockedInsertTailList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY ListEntry)
Definition at line 9948 of file internal.c.
References _LIST_ENTRY::Blink, InsertTailList(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
Referenced by IoRegisterBootDriverReinitialization(), and IoRegisterDriverReinitialization().
PLIST_ENTRY FASTCALL IopInterlockedRemoveHeadList (IN PLIST_ENTRY ListHead)
Definition at line 9992 of file internal.c.
References _LIST_ENTRY::Flink, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and RemoveEntryList().
Referenced by IopCallBootDriverReinitializationRoutines(), IopCallDriverReinitializationRoutines(), and IoShutdownSystem().
NTSTATUS IopInvalidateVolumesForDevice (IN PDEVICE_OBJECT DeviceObject)
Definition at line 5164 of file internal.c.
References CONTAINING_RECORD, DEVICE_OBJECT, ExAcquireResourceSharedLite(), except, EXCEPTION_EXECUTE_HANDLER, Executive, ExReleaseResourceLite(), FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_DISK, FILE_DEVICE_VIRTUAL_DISK, _LIST_ENTRY::Flink, FSCTL_INVALIDATE_VOLUMES, _IO_STATUS_BLOCK::Information, IO_NO_INCREMENT, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoCreateStreamFileObjectLite(), IoFileObjectType, IoGetNextIrpStackLocation, IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopTapeFileSystemQueueHead, IRP_MJ_FILE_SYSTEM_CONTROL, KeClearEvent(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, ObOpenObjectByPointer(), PAGED_CODE, PIRP, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_NOT_IMPLEMENTED, STATUS_PENDING, STATUS_SUCCESS, TRUE, VOID, _FILE_OBJECT::Vpb, and ZwClose().
NTSTATUS IopInvalidDeviceRequest (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 3227 of file internal.c.
References IO_NO_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IRP_MJ_POWER, PoStartNextPowerIrp(), STATUS_INVALID_DEVICE_REQUEST, and UNREFERENCED_PARAMETER.
Referenced by IoCreateDriver(), and IopLoadDriver().
VOID IopIrpStackProfilerTimer (IN struct _KDPC * Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 10753 of file internal.c.
References _IOP_IRP_STACK_PROFILER::Flags, IOP_PROFILE_STACK_COUNT, IOP_PROFILE_TRIGGER_INTERVAL, IopProcessIrpStackProfiler(), MAX_LOOKASIDE_IRP_STACK_COUNT, NUM_SAMPLE_IRPS, _IOP_IRP_STACK_PROFILER::Profile, _IOP_IRP_STACK_PROFILER::TriggerCount, and UNREFERENCED_PARAMETER.
Referenced by IopInitializeIrpStackProfiler().
LOGICAL IopIsSameMachine (IN PFILE_OBJECT SourceFile, IN HANDLE TargetFile)
Definition at line 3274 of file internal.c.
References _FAST_IO_DISPATCH::FastIoDeviceControl, IOCTL_LMR_ARE_FILE_OBJECTS_ON_SAME_SERVER, IoGetRelatedDeviceObject(), NULL, PAGED_CODE, _IO_STATUS_BLOCK::Status, STATUS_NOT_SAME_DEVICE, STATUS_SUCCESS, and TRUE.
Referenced by IopTrackLink().
NTSTATUS IopLoadDriver (IN HANDLE KeyHandle, IN BOOLEAN CheckForSafeBoot, IN BOOLEAN IsFilter, OUT NTSTATUS * DriverEntryStatus)
Definition at line 3689 of file internal.c.
References _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _UNICODE_STRING::Buffer, CmBootLastKnownGood(), CmRegistryMachineHardwareDescriptionSystemName, CONTAINING_RECORD, _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DbgPrint(), _IMAGE_OPTIONAL_HEADER::DllCharacteristics, _DRIVER_OBJECT::DriverExtension, _DRIVER_OBJECT::DriverInit, _DRIVER_OBJECT::DriverName, _DRIVER_EXTENSION::DriverObject, _DRIVER_OBJECT::DriverSection, _DRIVER_OBJECT::DriverSize, _DRIVER_OBJECT::DriverStart, _DRIVER_OBJECT::DriverUnload, DRVO_LEGACY_DRIVER, DRVO_UNLOAD_INVOKED, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAllocatePool, ExFreePool(), ExReleaseResourceLite(), FALSE, FIELD_OFFSET, FILE_READ_DATA, _DRIVER_OBJECT::Flags, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _DRIVER_OBJECT::HardwareDatabase, HEADLESS_LOG_LOAD_FAILED, HEADLESS_LOG_LOAD_SUCCESSFUL, HEADLESS_LOG_LOADING_FILENAME, HeadlessKernelAddLogEntry(), IMAGE_DLLCHARACTERISTICS_WDM_DRIVER, InitializeObjectAttributes, InitSafeBootMode, IO_TYPE_DRIVER, IoDriverObjectType, IopBootLog(), IopBuildFullDriverPath(), IopDriverLoadingFailed(), IopDriverLoadResource, IopGetDriverNameFromKeyNode(), IopGetRegistryValue(), IopInvalidDeviceRequest(), IopIsLegacyDriver(), IopPnpDriverStarted(), IopPrepareDriverLoading(), IopReadyDeviceObjects(), IopResurrectDriver(), IopSafebootDriverLoad(), IRP_MJ_MAXIMUM_FUNCTION, KeGetPreviousMode, KeQuerySystemTime(), KernelMode, KeyBasicInformation, KeyValuePartialInformation, _UNICODE_STRING::Length, _DRIVER_OBJECT::MajorFunction, _UNICODE_STRING::MaximumLength, MmFreeDriverInitialization(), MmLoadSystemImage(), MmUnloadSystemImage(), _OBJECT_NAME_INFORMATION::Name, _KEY_BASIC_INFORMATION::Name, _KEY_BASIC_INFORMATION::NameLength, NonPagedPool, NT_SUCCESS, NtClose(), NtQueryKey(), NtQueryObject(), NtQueryValueKey(), NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_PERMANENT, ObjectNameInformation, ObMakeTemporaryObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_SIZE, PAGED_CODE, PagedPool, PsLoadedModuleList, PsLoadedModuleResource, _LARGE_INTEGER::QuadPart, RtlAppendUnicodeToString(), RtlCopyMemory, RtlEqualUnicodeString(), RtlImageNtHeader(), RtlInitUnicodeString(), RtlZeroMemory, _DRIVER_EXTENSION::ServiceKeyName, _DRIVER_OBJECT::Size, _IMAGE_OPTIONAL_HEADER::SizeOfImage, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_DRIVER_BLOCKED, STATUS_DRIVER_BLOCKED_CRITICAL, STATUS_DRIVER_FAILED_PRIOR_UNLOAD, STATUS_FAILED_DRIVER_ENTRY, STATUS_ILL_FORMED_SERVICE_ENTRY, STATUS_IMAGE_ALREADY_LOADED, STATUS_INCOMPATIBLE_DRIVER_BLOCKED, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PLUGPLAY_NO_DEVICE, STATUS_SUCCESS, TRUE, _DRIVER_OBJECT::Type, and UNICODE_NULL.
Referenced by IopLoadUnloadDriver().
VOID IopLoadFileSystemDriver (IN PDEVICE_OBJECT DeviceObject)
Definition at line 4492 of file internal.c.
References Executive, FALSE, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IopDecrementDeviceObjectRef(), IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_LOAD_FILE_SYSTEM, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NULL, PAGED_CODE, PIRP, STATUS_PENDING, TRUE, and VOID.
Referenced by IopMountVolume().
VOID IopLoadUnloadDriver (IN PVOID Parameter)
Definition at line 4584 of file internal.c.
References _LOAD_PACKET::DriverObject, _LOAD_PACKET::DriverServiceName, _DRIVER_OBJECT::DriverUnload, _LOAD_PACKET::Event, FALSE, _LOAD_PACKET::FinalStatus, IopCallDriverReinitializationRoutines(), IopLoadDriver(), IopOpenRegistryKey(), KeSetEvent(), KEY_READ, NT_SUCCESS, NULL, PAGED_CODE, STATUS_DRIVER_FAILED_PRIOR_UNLOAD, STATUS_FAILED_DRIVER_ENTRY, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, and VOID.
Referenced by IopCompleteUnloadOrDelete(), IopUnloadDriver(), and NtLoadDriver().
NTSTATUS IopLookupBusStringFromID (IN HANDLE KeyHandle, IN INTERFACE_TYPE InterfaceType, OUT PWCHAR Buffer, IN ULONG Length, OUT PULONG BusFlags OPTIONAL)
Definition at line 9225 of file internal.c.
References ARGUMENT_PRESENT, _KEY_VALUE_FULL_INFORMATION::DataOffset, Index, KeyValueFullInformation, _KEY_VALUE_FULL_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::NameLength, NT_SUCCESS, PAGED_CODE, REG_BINARY, STATUS_SUCCESS, _KEY_VALUE_FULL_INFORMATION::Type, and ZwEnumerateValueKey().
VOID IopMarshalIds (OUT PTRACKING_BUFFER TrackingBuffer, IN PFILE_VOLUMEID_WITH_TYPE TargetVolumeId, IN PFILE_OBJECTID_BUFFER TargetObjectId, IN PFILE_TRACKING_INFORMATION TrackingInfo)
Definition at line 6386 of file internal.c.
References NULL, RtlCopyMemory, and RtlZeroMemory.
Referenced by IopTrackLink().
PVPB IopMountInitializeVpb (IN PDEVICE_OBJECT DeviceObject, IN PDEVICE_OBJECT AttachedDevice, IN ULONG RawMountOnly)
Definition at line 10411 of file internal.c.
References _VPB::DeviceObject, _VPB::Flags, IoAcquireVpbSpinLock(), IoReleaseVpbSpinLock(), _VPB::ReferenceCount, VPB_MOUNTED, and VPB_RAW_MOUNT.
Referenced by IopMountVolume().
NTSTATUS IopMountVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount, IN BOOLEAN DeviceLockAlreadyHeld, IN BOOLEAN Alertable, OUT PVPB * Vpb)
Definition at line 4684 of file internal.c.
References CONTAINING_RECORD, DEVICE_OBJECT, DO_SYSTEM_BOOT_PARTITION, DO_VERIFY_VOLUME, ExAcquireResourceSharedLite(), Executive, ExReleaseResourceLite(), FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_DISK, FILE_DEVICE_VIRTUAL_DISK, _IO_STACK_LOCATION::Flags, _LIST_ENTRY::Flink, FsRtlIsTotalDeviceFailure(), _IO_STATUS_BLOCK::Information, InitializationPhase, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoIsErrorUserInduced, IOP_ABORT, IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopFsRegistrationOps, IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopLoadFileSystemDriver(), IopMountInitializeVpb(), IopTapeFileSystemQueueHead, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_MOUNT_VOLUME, IRP_MOUNT_COMPLETION, IRP_SYNCHRONOUS_PAGING_IO, KeBugCheckEx(), KeClearEvent(), KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LockQueueIoDatabaseLock, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_DEVICE_DOES_NOT_EXIST, STATUS_FS_DRIVER_REQUIRED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, STATUS_UNRECOGNIZED_VOLUME, STATUS_UNSUCCESSFUL, STATUS_USER_APC, _ETHREAD::Tcb, TRUE, UNMOUNTABLE_BOOT_VOLUME, VOID, VPB_MOUNTED, VPB_RAW_MOUNT, and VPB_REMOVE_PENDING.
Referenced by IopCheckVpbMounted(), and IoVerifyVolume().
NTSTATUS IopOpenLinkOrRenameTarget (OUT PHANDLE TargetHandle, IN PIRP Irp, IN PVOID RenameBuffer, IN PFILE_OBJECT FileObject)
Definition at line 5430 of file internal.c.
References ASSERT, _UNICODE_STRING::Buffer, CreateFileTypeNone, FIELD_OFFSET, FILE_ADD_SUBDIRECTORY, FILE_ATTRIBUTE_DIRECTORY, FILE_EXISTS, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_DATA, _FILE_BASIC_INFORMATION::FileAttributes, FileLinkInformation, _FILE_RENAME_INFORMATION::FileName, _FILE_RENAME_INFORMATION::FileNameLength, FO_DIRECT_DEVICE_OPEN, FO_FILE_OBJECT_HAS_EXTENSION, FO_OPENED_CASE_SENSITIVE, _IO_STATUS_BLOCK::Information, InitializeObjectAttributes, IO_FORCE_ACCESS_CHECK, IO_NO_PARAMETER_CHECKING, IO_OPEN_TARGET_DIRECTORY, IoCreateFile(), IoCreateFileSpecifyDeviceObjectHint(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT, IopGetBasicInformationFile(), KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, STATUS_NOT_SAME_DEVICE, STATUS_OBJECT_NAME_COLLISION, STATUS_SUCCESS, SYNCHRONIZE, and _IOP_FILE_OBJECT_EXTENSION::TopDeviceObjectHint.
Referenced by IoSetInformation(), and NtSetInformationFile().
NTSTATUS IopOpenRegistryKey (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess, IN BOOLEAN Create)
Definition at line 5684 of file internal.c.
References InitializeObjectAttributes, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_OPTION_VOLATILE, ZwCreateKey(), and ZwOpenKey().
Referenced by IopBootLog(), IopCopyBootLogRegistryToFile(), IopLoadUnloadDriver(), IopSafebootDriverLoad(), and IopUnloadDriver().
VOID IopProcessIrpStackProfiler (VOID)
Definition at line 10812 of file internal.c.
References BASE_STACK_COUNT, IopIrpStackProfiler, IopLargeIrpStackLocations, MAX_LOOKASIDE_IRP_STACK_COUNT, MIN_IRP_THRESHOLD, and _IOP_IRP_STACK_PROFILER::Profile.
Referenced by IopIrpStackProfilerTimer().
NTSTATUS IopQueryXxxInformation (IN PFILE_OBJECT FileObject, IN ULONG InformationClass, IN ULONG Length, IN KPROCESSOR_MODE Mode, OUT PVOID Information, OUT PULONG ReturnedLength, IN BOOLEAN FileInformation)
Definition at line 5756 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, _IO_STATUS_BLOCK::Information, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IRP_BUFFERED_IO, IRP_MJ_QUERY_INFORMATION, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, SynchronizationEvent, TRUE, and VOID.
Referenced by IopQueryNameInternal(), IoQueryFileInformation(), and IoQueryVolumeInformation().
VOID IopRaiseHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 5979 of file internal.c.
References _UNICODE_STRING::Buffer, _IO_STACK_LOCATION::DeviceObject, ExAllocatePool, ExFreePool(), ExRaiseHardError(), ExReadyForErrors, FALSE, _VPB::Flags, IO_DISK_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IOP_ABORT, IRP_INPUT_OPERATION, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_MOUNT_VOLUME, KeAttachProcess(), KeDetachProcess(), _UNICODE_STRING::Length, _DRIVER_OBJECT::MajorFunction, _IO_STACK_LOCATION::MajorFunction, MAXIMUM_VOLUME_LABEL_LENGTH, _UNICODE_STRING::MaximumLength, _IO_STACK_LOCATION::MinorFunction, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObQueryNameString(), OptionCancelTryContinue, PagedPool, PIRP, PsGetCurrentProcess(), ResponseCancel, ResponseReturnToCaller, ResponseTryAgain, RtlInitUnicodeString(), STATUS_DEVICE_NOT_READY, STATUS_INSUFFICIENT_RESOURCES, STATUS_IO_TIMEOUT, STATUS_MEDIA_WRITE_PROTECTED, STATUS_NO_MEDIA_IN_DEVICE, STATUS_REQUEST_ABORTED, STATUS_SUCCESS, STATUS_UNRECOGNIZED_MEDIA, STATUS_UNSUCCESSFUL, STATUS_WRONG_VOLUME, THREAD_TO_PROCESS, TRUE, _EPROCESS::UniqueProcessId, _VPB::VolumeLabel, _VPB::VolumeLabelLength, and VPB_MOUNTED.
Referenced by IopApcHardError(), and IoRaiseHardError().
VOID IopRaiseInformationalHardError (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 6217 of file internal.c.
References _UNICODE_STRING::Buffer, _IOP_HARD_ERROR_PACKET::ErrorStatus, ExFreePool(), ExRaiseHardError(), ExReadyForErrors, InterlockedDecrement, IopHardError, NULL, _IOP_HARD_ERROR_QUEUE::NumPendingApcPopups, OptionOkNoWait, _IOP_HARD_ERROR_PACKET::String, UNREFERENCED_PARAMETER, and VOID.
Referenced by IoRaiseInformationalHardError().
VOID IopReadyDeviceObjects (IN PDRIVER_OBJECT DriverObject)
Definition at line 6286 of file internal.c.
References DO_DEVICE_INITIALIZING, DRVO_INITIALIZED, and PAGED_CODE.
Referenced by IopInitializeBuiltinDriver(), and IopLoadDriver().
PDRIVER_OBJECT IopReferenceDriverObjectByName (IN PUNICODE_STRING DriverName)
Definition at line 10214 of file internal.c.
References FILE_READ_ATTRIBUTES, InitializeObjectAttributes, IoDriverObjectType, KernelMode, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObOpenObjectByName(), and ObReferenceObjectByHandle.
BOOLEAN IopReferenceVerifyVpb (IN PDEVICE_OBJECT DeviceObject, OUT PVPB * Vpb, OUT PDEVICE_OBJECT * FsDeviceObject)
Definition at line 10870 of file internal.c.
References _VPB::DeviceObject, FALSE, _VPB::Flags, IoAcquireVpbSpinLock(), IoReleaseVpbSpinLock(), NULL, _VPB::ReferenceCount, TRUE, and VPB_MOUNTED.
Referenced by IoVerifyVolume().
PIOP_HARD_ERROR_PACKET IopRemoveHardErrorPacket (VOID)
Definition at line 3079 of file internal.c.
References CONTAINING_RECORD, ExAcquireFastLock, ExReleaseFastLock, IopCurrentHardError, IopHardError, RemoveHeadList(), UNREFERENCED_PARAMETER, _IOP_HARD_ERROR_QUEUE::WorkQueue, and _IOP_HARD_ERROR_QUEUE::WorkQueueSpinLock.
Referenced by IopHardErrorThread().
NTSTATUS IopResurrectDriver (PDRIVER_OBJECT DriverObject)
Definition at line 6327 of file internal.c.
References _DRIVER_OBJECT::DeviceObject, DOE_UNLOAD_PENDING, DRVO_UNLOAD_INVOKED, _DRIVER_OBJECT::Flags, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, STATUS_IMAGE_ALREADY_LOADED, and STATUS_SUCCESS.
Referenced by IopLoadDriver().
BOOLEAN IopSafebootDriverLoad (PUNICODE_STRING DriverId)
Definition at line 9318 of file internal.c.
References _UNICODE_STRING::Buffer, CmRegistryMachineSystemCurrentControlSetControlSafeBoot, ExAllocatePool, ExFreePool(), FALSE, InitSafeBootMode, IopOpenRegistryKey(), KdPrint, KernelMode, KEY_ALL_ACCESS, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCloseHandle(), PagedPool, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyUnicodeString(), RtlInitUnicodeString(), SAFEBOOT_DSREPAIR, SAFEBOOT_MINIMAL, SAFEBOOT_MINIMAL_STR_W, SAFEBOOT_NETWORK, SAFEBOOT_NETWORK_STR_W, and TRUE.
Referenced by IopLoadDriver().
NTSTATUS IopSendMessageToTrackService (IN PFILE_VOLUMEID_WITH_TYPE SourceVolumeId, IN PFILE_OBJECTID_BUFFER SourceObjectId, IN PFILE_TRACKING_INFORMATION TargetObjectInformation)
Definition at line 6503 of file internal.c.
References DelayedWorkQueue, _LINK_TRACKING_PACKET::Event, ExAllocatePool, Executive, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, _LINK_TRACKING_PACKET::FinalStatus, IopConnectLinkTrackingPort(), IopLinkTrackingPacket, IopLinkTrackingPortObject, IopLinkTrackingServiceEvent, IopLinkTrackingServiceObject, IopUnMarshalIds(), KeGetPreviousMode, KeReadStateEvent(), KeResetEvent(), KeSetEvent(), KeWaitForSingleObject(), LpcRequestWaitReplyPort(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PagedPool, RtlCopyMemory, RtlZeroMemory, _PORT_MESSAGE::s1, Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_TRACKING_SERVICE, STATUS_PORT_DISCONNECTED, STATUS_SUCCESS, STATUS_USER_APC, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, VOID, _LINK_TRACKING_PACKET::WorkQueueItem, and _PORT_MESSAGE::ZeroInit.
Referenced by IopTrackLink().
NTSTATUS IopSetEaOrQuotaInformationFile (IN HANDLE FileHandle, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PVOID Buffer, IN ULONG Length, IN BOOLEAN SetEa)
Definition at line 6703 of file internal.c.
References DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FILE_WRITE_DATA, FILE_WRITE_EA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoCheckEaBufferValidity(), IoCheckQuotaBufferValidity(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopProbeAndLockPages(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoReadAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_MJ_SET_EA, IRP_MJ_SET_QUOTA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
Referenced by NtSetQuotaInformationFile().
NTSTATUS IopSetRemoteLink (IN PFILE_OBJECT FileObject, IN PFILE_OBJECT DestinationFileObject OPTIONAL, IN PFILE_TRACKING_INFORMATION FileInformation OPTIONAL)
Definition at line 7104 of file internal.c.
References Executive, FALSE, _IO_STACK_LOCATION::FileObject, FSCTL_LMR_SET_LINK_TRACKING_INFORMATION, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_KERNEL_CALL, IRP_SYNCHRONOUS_API, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NULL, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, _REMOTE_LINK_TRACKING_INFORMATION_::TargetFileObject, _REMOTE_LINK_TRACKING_INFORMATION_::TargetLinkTrackingInformationBuffer, _REMOTE_LINK_TRACKING_INFORMATION_::TargetLinkTrackingInformationLength, and _REMOTE_LINK_BUFFER::TrackingInformation.
Referenced by IopTrackLink().
VOID IopStartApcHardError (IN PVOID StartContext)
Definition at line 7258 of file internal.c.
References ExFreePool(), IO_DISK_INCREMENT, IoCompleteRequest(), IopApcHardError(), NT_SUCCESS, NULL, PsCreateSystemThread(), and ZwClose().
Referenced by IoRaiseHardError().
NTSTATUS IopSynchronousApiServiceTail (IN NTSTATUS ReturnedStatus, IN PKEVENT Event, IN PIRP Irp, IN KPROCESSOR_MODE RequestorMode, IN PIO_STATUS_BLOCK LocalIoStatus, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 7314 of file internal.c.
References except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, IopCancelAlertedRequest(), KeWaitForSingleObject(), NULL, PAGED_CODE, STATUS_PENDING, and STATUS_USER_APC.
Referenced by IopSetEaOrQuotaInformationFile(), NtFlushBuffersFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetVolumeInformationFile(), and NtUnlockFile().
NTSTATUS IopSynchronousServiceTail (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PFILE_OBJECT FileObject, IN BOOLEAN DeferredIoCompletion, IN KPROCESSOR_MODE RequestorMode, IN BOOLEAN SynchronousIo, IN TRANSFER_TYPE TransferType)
Definition at line 7418 of file internal.c.
References APC_LEVEL, ASSERT, Executive, FO_ALERTABLE_IO, IoCallDriver(), IopCancelAlertedRequest(), IopCompleteRequest(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IopUpdateOtherOperationCount(), IopUpdateReadOperationCount(), IopUpdateWriteOperationCount(), KeLowerIrql, KeRaiseIrql, KeWaitForSingleObject(), NULL, OtherTransfer, PAGED_CODE, PASSIVE_LEVEL, ReadTransfer, STATUS_ALERTED, STATUS_PENDING, STATUS_USER_APC, and WriteTransfer.
Referenced by IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
VOID IopTimerDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 7577 of file internal.c.
References CONTAINING_RECORD, _IO_TIMER::Context, _IO_TIMER::DeviceObject, ExAcquireSpinLock, ExReleaseSpinLock, _LIST_ENTRY::Flink, IopTimerCount, IopTimerLock, IopTimerQueueHead, _IO_TIMER::TimerFlag, _IO_TIMER::TimerRoutine, and UNREFERENCED_PARAMETER.
Referenced by IoInitSystem().
NTSTATUS IopTrackLink (IN PFILE_OBJECT FileObject, IN OUT PIO_STATUS_BLOCK IoStatusBlock, IN PFILE_TRACKING_INFORMATION FileInformation, IN ULONG Length, IN PKEVENT Event, IN KPROCESSOR_MODE RequestorMode)
Definition at line 7666 of file internal.c.
References _FILE_TRACKING_INFORMATION::DestinationFile, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FIELD_OFFSET, FILE_WRITE_DATA, FSCTL_LMR_GET_LINK_TRACKING_INFORMATION, IoFileObjectType, IopGetSetObjectId(), IopGetVolumeId(), IopIsSameMachine(), IopMarshalIds(), IopSendMessageToTrackService(), IopSetRemoteLink(), IopTrackLink(), IsFileLocal, KernelMode, KeSetEvent(), leave, NT_SUCCESS, NULL, ObDereferenceObject(), _FILE_TRACKING_INFORMATION::ObjectInformationLength, ObReferenceObjectByHandle, PAGED_CODE, PagedPool, RtlCompareMemoryUlong(), RtlCopyMemory, RtlEqualMemory, STATUS_DUPLICATE_NAME, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, _TRACKING_BUFFER::TrackingInformation, TRUE, and _LINK_TRACKING_INFORMATION::VolumeId.
Referenced by IopTrackLink(), and NtSetInformationFile().
VOID IopUnMarshalIds (IN FILE_TRACKING_INFORMATION * TrackingInformation, OUT FILE_VOLUMEID_WITH_TYPE * TargetVolumeId, OUT GUID * TargetObjectId, OUT GUID * TargetMachineId)
Definition at line 6448 of file internal.c.
References min, and RtlCopyMemory.
Referenced by IopSendMessageToTrackService().
VOID IopUserCompletion (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 8380 of file internal.c.
References CONTAINING_RECORD, IoFreeIrp(), IRP, PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by IopCompleteRequest().
VOID IopUserRundown (IN PKAPC Apc)
Definition at line 8450 of file internal.c.
References CONTAINING_RECORD, IoFreeIrp(), IRP, and PAGED_CODE.
Referenced by IopCompleteRequest().
BOOLEAN IopVerifyDeviceObjectOnStack (IN PDEVICE_OBJECT BaseDeviceObject, IN PDEVICE_OBJECT TopDeviceObject)
Definition at line 10470 of file internal.c.
References ASSERT, FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and TRUE.
Referenced by IoGetRelatedDeviceObject(), and IopCheckTopDeviceHint().
BOOLEAN IopVerifyDiskSignature (IN PDRIVE_LAYOUT_INFORMATION_EX DriveLayout, IN PARC_DISK_SIGNATURE LoaderDiskBlock, OUT PULONG DiskSignature)
Definition at line 10518 of file internal.c.
References FALSE, RtlEqualMemory, and TRUE.
Referenced by IoGetBootDiskInformation(), and IopCreateArcNamesDisk().
BOOLEAN IopVerifyDriverObjectOnStack (IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_OBJECT DriverObject)
Definition at line 10666 of file internal.c.
References FALSE, IopGetDeviceAttachmentBase(), and TRUE.
Referenced by IopGetDriverPathInformation().
NTSTATUS IopXxxControlFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, IN ULONG IoControlCode, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN DeviceIoControl)
Definition at line 8483 of file internal.c.
References ARGUMENT_PRESENT, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, _FAST_IO_DISPATCH::FastIoDeviceControl, FILE_ANY_ACCESS, FILE_READ_DATA, FILE_WRITE_DATA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_SYNCHRONOUS_IO, FSCTL_DISMOUNT_VOLUME, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _IO_STATUS_BLOCK::Information, InterlockedIncrement, IoAllocateMdl(), IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopMarkApcRoutineIfAsyncronousIo32, IopProbeAndLockPages(), IopReleaseFileObjectLock, IopSynchronousServiceTail(), IoReadAccess, IoSetIoCompletion(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, KeSetEvent(), _IO_COMPLETION_CONTEXT::Key, _IO_STACK_LOCATION::MajorFunction, METHOD_BUFFERED, METHOD_IN_DIRECT, METHOD_NEITHER, METHOD_OUT_DIRECT, NonPagedPool, NonPagedPoolCacheAligned, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _IO_COMPLETION_CONTEXT::Port, ProbeForRead, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, SeComputeGrantedAccesses, SharedUserData, SL_READ_ACCESS_GRANTED, SL_WRITE_ACCESS_GRANTED, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _ETHREAD::Tcb, and TRUE.
Referenced by NtDeviceIoControlFile(), and NtFsControlFile().
VOID RtlAssert (IN PVOID FailedAssertion, IN PVOID FileName, IN ULONG LineNumber, IN PCHAR Message OPTIONAL)
Variable Documentation
PBOOT_LOG_RECORD BootLogRecord static
Definition at line 9424 of file internal.c.
PIRP IopDeadIrp
Definition at line 63 of file internal.c.
Referenced by IopDisassociateThreadIrp().