Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/profobj.c File Reference
profobj.c File Reference
#include "ki.h"
Data Structures
struct _KACTIVE_PROFILE_SOURCE
Macros
#define ASSERT_PROFILE(E)
Typedefs
typedef struct _KACTIVE_PROFILE_SOURCE KACTIVE_PROFILE_SOURCE
typedef struct _KACTIVE_PROFILE_SOURCE * PKACTIVE_PROFILE_SOURCE
Functions
VOID KeInitializeProfile (__out PKPROFILE Profile, __in_opt PKPROCESS Process, __in_opt PVOID RangeBase, __in SIZE_T RangeSize, __in ULONG BucketSize, __in ULONG Segment, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY ProfileAffinity)
ULONG KeQueryIntervalProfile (__in KPROFILE_SOURCE ProfileSource)
VOID KeSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
BOOLEAN KeStartProfile (__inout PKPROFILE Profile, __out_opt PULONG Buffer)
BOOLEAN KeStopProfile (__inout PKPROFILE Profile)
VOID KiStartProfileInterrupt (__inout PKIPI_CONTEXT SignalDone, __in PVOID Parameter1, __in PVOID Parameter2, __in PVOID Parameter3)
VOID KiStopProfileInterrupt (__inout PKIPI_CONTEXT SignalDone, __in PVOID Parameter1, __in PVOID Parameter2, __in PVOID Parameter3)
Macro Definition Documentation
#define ASSERT_PROFILE (E)
Value:
{             \
    ASSERT((E)->Type == ProfileObject); \
}
Definition at line 30 of file profobj.c.
Referenced by KeStartProfile(), and KeStopProfile().
Typedef Documentation
typedef struct _KACTIVE_PROFILE_SOURCE KACTIVE_PROFILE_SOURCE
typedef struct _KACTIVE_PROFILE_SOURCE * PKACTIVE_PROFILE_SOURCE
Function Documentation
VOID KeInitializeProfile (__out PKPROFILE Profile, __in_opt PKPROCESS Process, __in_opt PVOID RangeBase, __in SIZE_T RangeSize, __in ULONG BucketSize, __in ULONG Segment, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY ProfileAffinity)
Definition at line 66 of file profobj.c.
References ARGUMENT_PRESENT, ASSERT, FALSE, KeActiveProcessors, NULL, and ProfileObject.
Referenced by NtStartProfile(), and PerfInfoProfileInit().
ULONG KeQueryIntervalProfile (__in KPROFILE_SOURCE ProfileSource)
Definition at line 161 of file profobj.c.
References HalProfileSourceInformation, HalQuerySystemInformation, _HAL_PROFILE_SOURCE_INFORMATION::Interval, KiProfileAlignmentFixupInterval, KiProfileInterval, NT_SUCCESS, ProfileAlignmentFixup, ProfileTime, _HAL_PROFILE_SOURCE_INFORMATION::Source, Status, and _HAL_PROFILE_SOURCE_INFORMATION::Supported.
Referenced by NtQueryIntervalProfile().
VOID KeSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
Definition at line 223 of file profobj.c.
References HalProfileSourceInterval, HalSetProfileInterval(), HalSetSystemInformation, _HAL_PROFILE_SOURCE_INTERVAL::Interval, KeIpiGenericCall(), KiProfileAlignmentFixupInterval, KiProfileInterval, MINIMUM_PROFILE_INTERVAL, ProfileAlignmentFixup, ProfileTime, and _HAL_PROFILE_SOURCE_INTERVAL::Source.
Referenced by NtSetIntervalProfile(), and PerfInfoProfileInit().
BOOLEAN KeStartProfile (__inout PKPROFILE Profile, __out_opt PULONG Buffer)
Definition at line 291 of file profobj.c.
References _KACTIVE_PROFILE_SOURCE::Affinity, ASSERT, ASSERT_PROFILE, CONTAINING_RECORD, DISPATCH_LEVEL, ExAllocatePoolWithTag, ExFreePool(), FALSE, _LIST_ENTRY::Flink, HalStartProfileInterrupt(), InitializeListHead(), InsertHeadList(), InsertTailList(), KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KeNumberProcessors, KeReleaseSpinLockFromDpcLevel(), KfRaiseIrql(), KiEnableAlignmentExceptions, KiIpiSendPacket(), KiIpiStallOnPacketTargetsPrcb(), KiProfileAlignmentFixup, KiProfileIrql, KiProfileListHead, KiProfileLock, KiProfileSourceListHead, KiStartProfileInterrupt(), _KACTIVE_PROFILE_SOURCE::ListEntry, NonPagedPool, NULL, _KACTIVE_PROFILE_SOURCE::ProcessorCount, ProfileAlignmentFixup, _KPROCESS::ProfileListHead, RtlZeroMemory, _KPRCB::SetMember, _KACTIVE_PROFILE_SOURCE::Source, and TRUE.
Referenced by NtStartProfile(), and PerfInfoProfileInit().
BOOLEAN KeStopProfile (__inout PKPROFILE Profile)
Definition at line 531 of file profobj.c.
References _KACTIVE_PROFILE_SOURCE::Affinity, ASSERT, ASSERT_PROFILE, CONTAINING_RECORD, DISPATCH_LEVEL, ExFreePool(), FALSE, _LIST_ENTRY::Flink, HalStopProfileInterrupt(), IsListEmpty, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KeReleaseSpinLockFromDpcLevel(), KfRaiseIrql(), KiDisableAlignmentExceptions, KiIpiSendPacket(), KiIpiStallOnPacketTargetsPrcb(), KiProfileAlignmentFixup, KiProfileIrql, KiProfileLock, KiProfileSourceListHead, KiStopProfileInterrupt(), _KACTIVE_PROFILE_SOURCE::ListEntry, NULL, _KACTIVE_PROFILE_SOURCE::ProcessorCount, ProfileAlignmentFixup, RemoveEntryList(), _KPRCB::SetMember, _KACTIVE_PROFILE_SOURCE::Source, and TRUE.
Referenced by ExpProfileDelete(), NtStopProfile(), and PerfInfoProfileUninit().
VOID KiStartProfileInterrupt (__inout PKIPI_CONTEXT SignalDone, __in PVOID Parameter1, __in PVOID Parameter2, __in PVOID Parameter3)
Definition at line 791 of file profobj.c.
References HalStartProfileInterrupt(), KeGetCurrentIrql(), KeLowerIrql, KfRaiseIrql(), KiEnableAlignmentExceptions, KiIpiSignalPacketDone(), KiProfileIrql, ProfileAlignmentFixup, PtrToUlong, and UNREFERENCED_PARAMETER.
Referenced by KeStartProfile().
VOID KiStopProfileInterrupt (__inout PKIPI_CONTEXT SignalDone, __in PVOID Parameter1, __in PVOID Parameter2, __in PVOID Parameter3)
Definition at line 732 of file profobj.c.
References HalStopProfileInterrupt(), KeGetCurrentIrql(), KeLowerIrql, KfRaiseIrql(), KiDisableAlignmentExceptions, KiIpiSignalPacketDone(), KiProfileIrql, ProfileAlignmentFixup, PtrToUlong, and UNREFERENCED_PARAMETER.
Referenced by KeStopProfile().