Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/thredsup.c File Reference
thredsup.c File Reference
#include "ki.h"
Functions
ULONG KeFindNextRightSetAffinity (__in ULONG Number, __in KAFFINITY Set)
VOID FASTCALL KiDeferredReadyThread (IN PKTHREAD Thread)
PKTHREAD FASTCALL KiFindReadyThread (IN ULONG Number, IN PKPRCB Prcb)
VOID FASTCALL KiProcessDeferredReadyList (IN PKPRCB CurrentPrcb)
VOID FASTCALL KiQueueReadyThread (IN PKTHREAD Thread, IN PKPRCB Prcb)
VOID FASTCALL KiReadyThread (IN PKTHREAD Thread)
PKTHREAD FASTCALL KiSelectNextThread (IN PKPRCB Prcb)
KAFFINITY FASTCALL KiSetAffinityThread (IN PKTHREAD Thread, IN KAFFINITY Affinity)
VOID KiSetInternalEvent (IN PKEVENT Event, IN PKTHREAD Thread)
VOID FASTCALL KiSetPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Priority)
VOID KiSuspendNop (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE *NormalRoutine, IN OUT PVOID *NormalContext, IN OUT PVOID *SystemArgument1, IN OUT PVOID *SystemArgument2)
VOID KiSuspendRundown (IN PKAPC Apc)
VOID KiSuspendThread (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
LONG_PTR FASTCALL KiSwapThread (IN PKTHREAD OldThread, IN PKPRCB CurrentPrcb)
Function Documentation
ULONG KeFindNextRightSetAffinity (__in ULONG Number, __in KAFFINITY Set)
Definition at line 2030 of file thredsup.c.
References AFFINITY_MASK, ASSERT, and KeFindFirstSetLeftAffinity.
Referenced by KeStartThread(), KiSetAffinityThread(), and KiSetIdealNodeProcess().
VOID FASTCALL KiDeferredReadyThread (IN PKTHREAD Thread)
Definition at line 114 of file thredsup.c.
References AdjustBoost, AdjustNone, AdjustUnwait, AFFINITY_MASK, ASSERT, _KPRCB::CurrentThread, _KTHREAD::DeferredProcessor, DeferredReady, DISPATCH_LEVEL, _KPRCB::DispatcherReadyListHead, FALSE, HIGH_PRIORITY, _KPRCB::IdleThread, InsertHeadList(), InsertTailList(), KeFindFirstSetLeftAffinity, KeGetCurrentPrcb(), KeIsIdleHaltSet, KiAcquireThreadLock(), KiAcquireTwoPrcbLocks(), KiClearIdleSummary(), KiClearSMTSummary(), KiComputeNewPriority(), KiIdleSMTSummary, KiIdleSummary, KiProcessorBlock, KiQueryLowTickCount, KiReleaseThreadLock(), KiReleaseTwoPrcbLocks(), KiRequestDispatchInterrupt, KiSendSoftwareInterrupt(), LOCK_OWNERSHIP_QUANTUM, LOW_REALTIME_PRIORITY, MEMORY_PRIORITY_FOREGROUND, min, _KPRCB::MultiThreadProcessorSet, _KPRCB::NextThread, NOTHING, NULL, _KPRCB::Number, _KPRCB::ParentNode, _KTHREAD::Preempted, Priority, _KTHREAD::Priority, PRIORITY_MASK, _KNODE::ProcessorMask, PsPrioritySeparation, ReadForWriteAccess, Ready, _KPRCB::ReadySummary, Running, _KPRCB::SetMember, Standby, _KTHREAD::State, STATUS_KERNEL_APC, ThreadPriority, TIME_CRITICAL_PRIORITY_BOUND, TRUE, and WAIT_QUANTUM_DECREMENT.
Referenced by KeSignalGateBoostPriority(), KiInsertDeferredReadyList(), KiProcessDeferredReadyList(), and KxQueueReadyThread().
PKTHREAD FASTCALL KiFindReadyThread (IN ULONG Number, IN PKPRCB Prcb)
Definition at line 688 of file thredsup.c.
References _KTHREAD::Affinity, AFFINITY_MASK, ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeFindFirstSetLeftMember(), _KTHREAD::NextProcessor, NULL, _KTHREAD::Priority, PRIORITY_MASK, RemoveEntryList(), and _KTHREAD::WaitListEntry.
Referenced by KiIdleSchedule(), and KiSwapThread().
VOID FASTCALL KiProcessDeferredReadyList (IN PKPRCB CurrentPrcb)
Definition at line 795 of file thredsup.c.
References ASSERT, CONTAINING_RECORD, KiDeferredReadyThread(), _SINGLE_LIST_ENTRY::Next, and NULL.
Referenced by KiExitDispatcher(), KiRetireDpcList(), and KiSwapThread().
VOID FASTCALL KiQueueReadyThread (IN PKTHREAD Thread, IN PKPRCB Prcb)
Definition at line 859 of file thredsup.c.
References KxQueueReadyThread().
VOID FASTCALL KiReadyThread (IN PKTHREAD Thread)
Definition at line 896 of file thredsup.c.
References ASSERT, FALSE, InsertTailList(), InterlockedPushEntrySingleList(), KiInsertDeferredReadyList(), KiProcessInSwapListHead, KiSetInternalEvent(), KiStackInSwapListHead, KiSwapEvent, KiSwappingThread, MAXULONG_PTR, ProcessInMemory, ProcessInTransition, ProcessOutOfMemory, Ready, _KPROCESS::ReadyListHead, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, Transition, and TRUE.
Referenced by KeReadyThread(), KeSetEventBoostPriority(), KiAttachProcess(), KiInsertQueue(), KiInSwapProcesses(), KiOutSwapProcesses(), and KiUnwaitThread().
PKTHREAD FASTCALL KiSelectNextThread (IN PKPRCB Prcb)
Definition at line 985 of file thredsup.c.
References ASSERT, _KTHREAD::BasePriority, KeIsSMTSetIdle(), KiSelectReadyThread(), KiSetIdleSummary(), KiSetSMTSummary(), NULL, _KTHREAD::Priority, and TRUE.
Referenced by KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), and KiSetAffinityThread().
KAFFINITY FASTCALL KiSetAffinityThread (IN PKTHREAD Thread, IN KAFFINITY Affinity)
Definition at line 1057 of file thredsup.c.
References _KPROCESS::Affinity, AFFINITY_MASK, ASSERT, _KPRCB::CurrentThread, DeferredReady, FALSE, Index, INVALID_AFFINITY_SET, KeBugCheck(), KeFindNextRightSetAffinity(), KeNodeBlock, KeNumberNodes, KeProcessNodeSeed, KiAcquirePrcbLock(), KiAcquireThreadLock(), KiInsertDeferredReadyList(), KiProcessorBlock, KiReleasePrcbLock(), KiReleaseThreadLock(), KiRequestDispatchInterrupt, KiSelectNextThread(), _KPRCB::NextThread, NULL, _KPRCB::Number, PRIORITY_MASK, Ready, _KPRCB::ReadySummary, RemoveEntryList(), Running, _KPRCB::SetMember, Standby, _KTHREAD::State, TRUE, and _KTHREAD::UserAffinity.
Referenced by KeSetAffinityProcess(), and KeSetAffinityThread().
VOID KiSetInternalEvent (IN PKEVENT Event, IN PKTHREAD Thread)
Definition at line 1385 of file thredsup.c.
References BALANCE_INCREMENT, _LIST_ENTRY::Flink, and KiUnwaitThread().
Referenced by KeBalanceSetManager(), KeDetachProcess(), KeTerminateThread(), KeUnstackDetachProcess(), KiAttachProcess(), and KiReadyThread().
VOID FASTCALL KiSetPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Priority)
Definition at line 1431 of file thredsup.c.
References ASSERT, _KPRCB::CurrentThread, DeferredReady, FALSE, HIGH_PRIORITY, KiAcquirePrcbLock(), KiInsertDeferredReadyList(), KiProcessorBlock, KiReleasePrcbLock(), KiRequestDispatchInterrupt, KiSelectReadyThread(), _KPRCB::NextThread, NULL, _KPRCB::Number, PRIORITY_MASK, Ready, _KPRCB::ReadySummary, RemoveEntryList(), Running, Standby, _KTHREAD::State, ThreadPriority, and TRUE.
Referenced by ExpBoostOwnerThread(), KeSetBasePriorityThread(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), and KiBoostPriorityThread().
VOID KiSuspendNop (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE * NormalRoutine, IN OUT PVOID * NormalContext, IN OUT PVOID * SystemArgument1, IN OUT PVOID * SystemArgument2)
Definition at line 30 of file thredsup.c.
References UNREFERENCED_PARAMETER.
VOID KiSuspendRundown (IN PKAPC Apc)
Definition at line 80 of file thredsup.c.
References UNREFERENCED_PARAMETER.
Referenced by KeInitThread().
VOID KiSuspendThread (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 1636 of file thredsup.c.
References FALSE, KeGetCurrentThread(), KernelMode, KeWaitForSingleObject(), NULL, Suspended, _KTHREAD::SuspendSemaphore, and UNREFERENCED_PARAMETER.
Referenced by KeInitThread().
LONG_PTR FASTCALL KiSwapThread (IN PKTHREAD OldThread, IN PKPRCB CurrentPrcb)
Definition at line 1691 of file thredsup.c.
References AFFINITY_MASK, ASSERT, FALSE, Index, KeFindFirstSetLeftAffinity, KeIsSMTSetIdle(), KeNumberNodes, KeNumberProcessors, KiAcquirePrcbLock(), KiAcquireTwoPrcbLocks(), KiClearIdleSummary(), KiClearSMTSummary(), KiFindReadyThread(), KiProcessDeferredReadyList(), KiProcessorBlock, KiReleasePrcbLock(), KiSelectReadyThread(), KiSetIdleSummary(), KiSetSMTSummary(), NULL, _KPRCB::ReadySummary, Running, _KTHREAD::State, and TRUE.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeTerminateThread(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), and KiAttachProcess().