Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/rtlnthdr.c File Reference
rtlnthdr.c File Reference
#include "ntrtlp.h"
Macros
#define EXIT goto Exit
#define RtlImageNtHeaderEx_ExceptionFilter(RangeCheck, ExceptionCode) EXCEPTION_EXECUTE_HANDLER
#define SIZEOF_PE_SIGNATURE 4
Functions
PIMAGE_NT_HEADERS NTAPI RtlImageNtHeader (PVOID Base)
NTSTATUS NTAPI RtlImageNtHeaderEx (ULONG Flags, PVOID Base, ULONG64 Size, OUT PIMAGE_NT_HEADERS *OutHeaders)
Macro Definition Documentation
#define EXIT goto Exit
Referenced by RtlImageNtHeaderEx().
#define RtlImageNtHeaderEx_ExceptionFilter (RangeCheck, ExceptionCode) EXCEPTION_EXECUTE_HANDLER
Definition at line 32 of file rtlnthdr.c.
#define SIZEOF_PE_SIGNATURE 4
Referenced by RtlImageNtHeaderEx().
Function Documentation
PIMAGE_NT_HEADERS NTAPI RtlImageNtHeader (PVOID Base)
Definition at line 173 of file rtlnthdr.c.
References NULL, RTL_IMAGE_NT_HEADER_EX_FLAG_NO_RANGE_CHECK, RtlImageNtHeaderEx(), and VOID.
Referenced by DbgkCreateThread(), DbgkMapViewOfSection(), DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), DbgLoadImageSymbols(), IopInitializeBuiltinDriver(), IopLoadDriver(), LdrFindEntryForAddress(), LdrpAccessResourceDataNoMultipleLanguage(), LdrRelocateImageWithBias(), MiCaptureImageExceptionValues(), MiEnablePagingOfDriver(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiLocateKernelSections(), MiReloadBootLoadedDrivers(), MiSessionProcessGlobalSubsections(), MiWriteProtectSystemImage(), MmCheckSystemImage(), MmCreatePeb(), MmFreeDriverInitialization(), MmGetSectionRange(), MmInitSystem(), MmLoadSystemImage(), MmLockPageableDataSection(), MmResetDriverPaging(), MmVerifyImageIsOkForMpUse(), NtSetSystemInformation(), RtlCaptureImageExceptionValues(), RtlImageDirectoryEntryToData(), RtlpCreateStack(), and WmipReceiveNotifications().
NTSTATUS NTAPI RtlImageNtHeaderEx (ULONG Flags, PVOID Base, ULONG64 Size, OUT PIMAGE_NT_HEADERS * OutHeaders)
Definition at line 37 of file rtlnthdr.c.
References EXIT, IMAGE_DOS_SIGNATURE, IMAGE_NT_SIGNATURE, MAXULONG, MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, RTL_IMAGE_NT_HEADER_EX_FLAG_NO_RANGE_CHECK, _IMAGE_NT_HEADERS::Signature, SIZEOF_PE_SIGNATURE, Status, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlImageNtHeader().