Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/mtrr.c File Reference
mtrr.c File Reference
#include "ki.h"
#include "mtrr.h"
Data Structures
struct _MTRR_RANGE
struct _NEW_RANGE
struct _ONE_RANGE
struct _RANGE_INFO
Macros
#define DBGMSG(a)
#define GROW_RANGE_TABLE 4
#define IDBG 0
#define MOV_CR4_EAX _emit { 0Fh, 22h, E0h }
#define MOV_EAX_CR4 _emit { 0Fh, 20h, E0h }
#define STATIC
Typedefs
typedef struct _MTRR_RANGE MTRR_RANGE
typedef struct _NEW_RANGE NEW_RANGE
typedef struct _ONE_RANGE ONE_RANGE
typedef struct _MTRR_RANGE * PMTRR_RANGE
typedef struct _NEW_RANGE * PNEW_RANGE
typedef struct _ONE_RANGE * PONE_RANGE
typedef struct _RANGE_INFO * PRANGE_INFO
typedef struct _RANGE_INFO RANGE_INFO
Functions
VOID KeRestoreMtrr (VOID)
NTSTATUS KeSetPhysicalCacheTypeRange (IN PHYSICAL_ADDRESS PhysicalAddress, IN ULONG NumberOfBytes, IN MEMORY_CACHING_TYPE CacheType)
VOID KiAddRange (IN PNEW_RANGE NewRange, IN ULONGLONG Base, IN ULONGLONG Limit, IN UCHAR Type)
NTSTATUS KiAmdK6MtrrSetMemoryType (IN ULONG BaseAddress, IN ULONG NumberOfBytes, IN MEMORY_CACHING_TYPE CacheType)
VOID KiAmdK6MtrrWRMSR (VOID)
VOID KiCompleteEffectiveRangeChange (IN PNEW_RANGE NewRange)
STATIC ULONG KiFindFirstSetLeftBit (IN ULONGLONG Set)
STATIC ULONG KiFindFirstSetRightBit (IN ULONGLONG Set)
VOID KiInitializeMTRR (IN BOOLEAN LastProcessor)
ULONGLONG KiLengthToMask (IN ULONGLONG Length)
NTSTATUS KiLoadMTRR (IN PNEW_RANGE Context)
VOID KiLoadMTRRTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID Context, IN PVOID Parameter2, IN PVOID Parameter3)
VOID KiLockStepExecution (IN PPROCESSOR_LOCKSTEP Context)
ULONGLONG KiMaskToLength (IN ULONGLONG Mask)
STATIC ULONG KiRangeWeight (IN PONE_RANGE Range)
BOOLEAN KiRemoveRange (IN PNEW_RANGE NewRange, IN ULONGLONG Base, IN ULONGLONG Limit, IN PBOOLEAN RemoveThisType)
VOID KiStartEffectiveRangeChange (IN PNEW_RANGE NewRange)
Variables
LONG64 KiMtrrMaskBase = 0x0000000ffffff000
LONG64 KiMtrrMaskMask = 0x0000000ffffff000
UCHAR KiMtrrMaxRangeShift = 36
LONG64 KiMtrrOverflowMask = (~0x1000000000)
LONG64 KiMtrrResBitMask = 0xfffffffff
RANGE_INFO KiRangeInfo
KSPIN_LOCK KiRangeLock
Macro Definition Documentation
#define DBGMSG (a)
Definition at line 32 of file mtrr.c.
Referenced by KeSetPhysicalCacheTypeRange(), KiCompleteEffectiveRangeChange(), KiInitializeMTRR(), and KiRemoveRange().
#define GROW_RANGE_TABLE 4
Definition at line 62 of file mtrr.c.
Referenced by KiAddRange(), and KiInitializeMTRR().
#define IDBG 0
Definition at line 27 of file mtrr.c.
#define MOV_CR4_EAX _emit { 0Fh, 22h, E0h }
Definition at line 1811 of file mtrr.c.
#define MOV_EAX_CR4 _emit { 0Fh, 20h, E0h }
Definition at line 1810 of file mtrr.c.
#define STATIC
Definition at line 25 of file mtrr.c.
Typedef Documentation
typedef struct _MTRR_RANGE MTRR_RANGE
typedef struct _NEW_RANGE NEW_RANGE
typedef struct _ONE_RANGE ONE_RANGE
typedef struct _MTRR_RANGE * PMTRR_RANGE
typedef struct _NEW_RANGE * PNEW_RANGE
typedef struct _ONE_RANGE * PONE_RANGE
typedef struct _RANGE_INFO * PRANGE_INFO
typedef struct _RANGE_INFO RANGE_INFO
Function Documentation
VOID KeRestoreMtrr (VOID)
Definition at line 537 of file mtrr.c.
References ASSERT, KeAcquireSpinLock, KeFeatureBits, KeReleaseSpinLock(), KF_AMDK6MTRR, KiCompleteEffectiveRangeChange(), KiLoadMTRR(), KiRangeLock, KiStartEffectiveRangeChange(), NT_SUCCESS, NULL, _RANGE_INFO::RangesValid, RtlZeroMemory, and _NEW_RANGE::Status.
Referenced by KeRestoreProcessorSpecificFeatures().
NTSTATUS KeSetPhysicalCacheTypeRange (IN PHYSICAL_ADDRESS PhysicalAddress, IN ULONG NumberOfBytes, IN MEMORY_CACHING_TYPE CacheType)
Definition at line 587 of file mtrr.c.
References ASSERT, _NEW_RANGE::Base, _RANGE_INFO::Capabilities, DBGMSG, _RANGE_INFO::DefaultCachedType, DISPATCH_LEVEL, ExPageLockHandle, FALSE, _MTRR_CAPABILITIES::hw, KeAcquireSpinLock, KeFeatureBits, KeGetCurrentIrql(), KeReleaseSpinLock(), KF_AMDK6MTRR, KiAddRange(), KiAmdK6MtrrSetMemoryType(), KiCompleteEffectiveRangeChange(), KiRangeLock, KiRemoveRange(), KiStartEffectiveRangeChange(), _NEW_RANGE::Limit, memset(), MmCached, MmLockPageableSectionByHandle(), MmNonCached, MmUnlockPageableImageSection(), MmUSWCCached, MmWriteCombined, MTRR_TYPE_MAX, MTRR_TYPE_UC, MTRR_TYPE_USWC, _RANGE_INFO::MtrrWorkaround, NT_SUCCESS, _RANGE_INFO::RangesValid, RtlZeroMemory, _NEW_RANGE::Status, STATUS_INVALID_PARAMETER, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, _NEW_RANGE::Type, and _MTRR_CAPABILITIES::u.
Referenced by __out_bcount().
VOID KiAddRange (IN PNEW_RANGE NewRange, IN ULONGLONG Base, IN ULONGLONG Limit, IN UCHAR Type)
Definition at line 1003 of file mtrr.c.
References _ONE_RANGE::Base, ExAllocatePoolWithTag, ExFreePool(), GROW_RANGE_TABLE, _ONE_RANGE::Limit, _RANGE_INFO::MaxRange, NonPagedPool, _RANGE_INFO::NoRange, _RANGE_INFO::Ranges, RtlCopyMemory, RtlZeroMemory, STATUS_UNSUCCESSFUL, and _ONE_RANGE::Type.
Referenced by KeSetPhysicalCacheTypeRange(), KiInitializeMTRR(), and KiRemoveRange().
NTSTATUS KiAmdK6MtrrSetMemoryType (IN ULONG BaseAddress, IN ULONG NumberOfBytes, IN MEMORY_CACHING_TYPE CacheType)
Referenced by KeSetPhysicalCacheTypeRange().
VOID KiAmdK6MtrrWRMSR (VOID)
Definition at line 761 of file mtrramd.c.
References AMDK6_MTRR_MSR, _AMDK6_MTRR_MSR_IMAGE::QuadPart, _AMDK6_MTRR_MSR_IMAGE::u, and WRMSR().
Referenced by KiLoadMTRR().
VOID KiCompleteEffectiveRangeChange (IN PNEW_RANGE NewRange)
Definition at line 1123 of file mtrr.c.
References ASSERT, _ONE_RANGE::Base, _MTRR_RANGE::Base, _RANGE_INFO::Capabilities, DBGMSG, _RANGE_INFO::Default, DISPATCH_LEVEL, ExFreePool(), FALSE, HIGH_LEVEL, _MTRR_CAPABILITIES::hw, _MTRR_DEFAULT::hw, _MTRR_VARIABLE_BASE::hw, _MTRR_VARIABLE_MASK::hw, Index, KeAcquireSpinLock, KeActiveProcessors, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeRaiseIrql, KeReleaseSpinLock(), KiFindFirstSetLeftBit(), KiFindFirstSetRightBit(), KiIpiSendSynchronousPacket, KiIpiStallOnPacketTargets(), KiLengthToMask(), KiLoadMTRR(), KiLoadMTRRTarget(), KiMaskToLength(), KiMtrrMaskMask, KiMtrrMaxRangeShift, KiRangeWeight(), KiRemoveRange(), KiReverseStallIpiLock, _ONE_RANGE::Limit, _MTRR_RANGE::Mask, MTRR_PAGE_MASK, MTRR_PAGE_SIZE, MTRR_TYPE_MAX, MTRR_TYPE_UC, MTRR_TYPE_USWC, MTRR_TYPE_WB, MTRR_TYPE_WT, _RANGE_INFO::NoRange, NT_SUCCESS, NULL, _KPRCB::Number, _MTRR_VARIABLE_BASE::QuadPart, _MTRR_VARIABLE_MASK::QuadPart, _RANGE_INFO::Ranges, _KPRCB::ReverseStall, RtlCopyMemory, RtlZeroMemory, _KPRCB::SetMember, STATUS_UNSUCCESSFUL, TRUE, _ONE_RANGE::Type, _MTRR_CAPABILITIES::u, _MTRR_DEFAULT::u, _MTRR_VARIABLE_BASE::u, and _MTRR_VARIABLE_MASK::u.
Referenced by KeRestoreMtrr(), and KeSetPhysicalCacheTypeRange().
STATIC ULONG KiFindFirstSetLeftBit (IN ULONGLONG Set)
Definition at line 1704 of file mtrr.c.
References ASSERT, and KiFindFirstSetLeft.
Referenced by KiCompleteEffectiveRangeChange().
STATIC ULONG KiFindFirstSetRightBit (IN ULONGLONG Set)
Definition at line 1683 of file mtrr.c.
References ASSERT, and KiFindFirstSetRight.
Referenced by KiCompleteEffectiveRangeChange(), KiLengthToMask(), and KiMaskToLength().
VOID KiInitializeMTRR (IN BOOLEAN LastProcessor)
Definition at line 276 of file mtrr.c.
References _RANGE_INFO::Capabilities, _KPRCB::CpuStep, _KPRCB::CpuType, DBGMSG, _RANGE_INFO::Default, _RANGE_INFO::DefaultCachedType, ExAllocatePoolWithTag, ExFreePool(), FALSE, GROW_RANGE_TABLE, _MTRR_CAPABILITIES::hw, _MTRR_DEFAULT::hw, _MTRR_VARIABLE_BASE::hw, _MTRR_VARIABLE_MASK::hw, Index, KeFeatureBits, KeGetCurrentPrcb(), KeGetPcr(), KeInitializeSpinLock(), KF_MTRR, KiAddRange(), KiMaskToLength(), KiMtrrMaskBase, KiMtrrMaskMask, KiMtrrOverflowMask, KiRangeLock, _RANGE_INFO::MaxRange, MTRR_MSR_CAPABILITIES, MTRR_MSR_DEFAULT, MTRR_MSR_VARIABLE_BASE, MTRR_MSR_VARIABLE_MASK, MTRR_TYPE_MAX, MTRR_TYPE_UC, MTRR_TYPE_WB, MTRR_TYPE_WT, _RANGE_INFO::MtrrWorkaround, NonPagedPool, _RANGE_INFO::NoRange, NT_SUCCESS, NULL, _MTRR_CAPABILITIES::QuadPart, _MTRR_DEFAULT::QuadPart, _MTRR_VARIABLE_BASE::QuadPart, _MTRR_VARIABLE_MASK::QuadPart, _RANGE_INFO::Ranges, _RANGE_INFO::RangesValid, RDMSR(), RtlZeroMemory, Status, _NEW_RANGE::Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, strcmp(), TRUE, _MTRR_CAPABILITIES::u, _MTRR_DEFAULT::u, _MTRR_VARIABLE_BASE::u, _MTRR_VARIABLE_MASK::u, and _KPRCB::VendorString.
Referenced by KiInitMachineDependent().
STATIC ULONGLONG KiLengthToMask (IN ULONGLONG Length)
Definition at line 1660 of file mtrr.c.
References KiFindFirstSetRightBit(), KiMtrrMaxRangeShift, and KiMtrrResBitMask.
Referenced by KiCompleteEffectiveRangeChange().
NTSTATUS KiLoadMTRR (IN PNEW_RANGE Context)
Definition at line 1814 of file mtrr.c.
References CR0_CD, CR0_NW, CR4_PGE, _MTRR_DEFAULT::hw, Index, KeDisableInterrupts(), KeEnableInterrupts(), KeFeatureBits, KF_AMDK6MTRR, KiAmdK6MtrrWRMSR(), KiLockStepExecution(), MTRR_MSR_DEFAULT, MTRR_MSR_VARIABLE_BASE, MTRR_MSR_VARIABLE_MASK, _MTRR_DEFAULT::QuadPart, RDMSR(), STATUS_SUCCESS, _MTRR_DEFAULT::u, and WRMSR().
Referenced by KeRestoreMtrr(), KiCompleteEffectiveRangeChange(), and KiLoadMTRRTarget().
VOID KiLoadMTRRTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID Context, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 1780 of file mtrr.c.
References KiIpiSignalPacketDoneAndStall(), KiLoadMTRR(), _NEW_RANGE::Synchronize, _PROCESSOR_LOCKSTEP::TargetPhase, and UNREFERENCED_PARAMETER.
Referenced by KiCompleteEffectiveRangeChange().
VOID KiLockStepExecution (IN PPROCESSOR_LOCKSTEP Context)
Definition at line 1998 of file mtrr.c.
References InterlockedIncrement, KeGetCurrentPrcb(), KeNumberProcessors, KeYieldProcessor, _KPRCB::Number, and UNREFERENCED_PARAMETER.
Referenced by KiLoadMTRR(), and KiLoadPAT().
STATIC ULONGLONG KiMaskToLength (IN ULONGLONG Mask)
Definition at line 1639 of file mtrr.c.
References KiFindFirstSetRightBit(), and KiMtrrMaxRangeShift.
Referenced by KiCompleteEffectiveRangeChange(), and KiInitializeMTRR().
STATIC ULONG KiRangeWeight (IN PONE_RANGE Range)
Definition at line 1601 of file mtrr.c.
References MTRR_TYPE_UC, MTRR_TYPE_USWC, MTRR_TYPE_WB, MTRR_TYPE_WP, and MTRR_TYPE_WT.
Referenced by KiCompleteEffectiveRangeChange().
BOOLEAN KiRemoveRange (IN PNEW_RANGE NewRange, IN ULONGLONG Base, IN ULONGLONG Limit, IN PBOOLEAN RemoveThisType)
Definition at line 866 of file mtrr.c.
References _ONE_RANGE::Base, DBGMSG, FALSE, KiAddRange(), _ONE_RANGE::Limit, _RANGE_INFO::NoRange, NT_SUCCESS, _RANGE_INFO::Ranges, TRUE, and _ONE_RANGE::Type.
Referenced by KeSetPhysicalCacheTypeRange(), and KiCompleteEffectiveRangeChange().
VOID KiStartEffectiveRangeChange (IN PNEW_RANGE NewRange)
Definition at line 1071 of file mtrr.c.
References _RANGE_INFO::Capabilities, ExAllocatePoolWithTag, _MTRR_CAPABILITIES::hw, NonPagedPool, _RANGE_INFO::NoRange, _RANGE_INFO::Ranges, RtlCopyMemory, RtlZeroMemory, STATUS_UNSUCCESSFUL, and _MTRR_CAPABILITIES::u.
Referenced by KeRestoreMtrr(), and KeSetPhysicalCacheTypeRange().
Variable Documentation
LONG64 KiMtrrMaskBase = 0x0000000ffffff000
Definition at line 42 of file mtrr.c.
Referenced by KiGetFeatureBits(), and KiInitializeMTRR().
LONG64 KiMtrrMaskMask = 0x0000000ffffff000
Definition at line 43 of file mtrr.c.
Referenced by KiCompleteEffectiveRangeChange(), KiGetFeatureBits(), and KiInitializeMTRR().
UCHAR KiMtrrMaxRangeShift = 36
Definition at line 46 of file mtrr.c.
Referenced by KiCompleteEffectiveRangeChange(), KiGetFeatureBits(), KiLengthToMask(), and KiMaskToLength().
LONG64 KiMtrrOverflowMask = (~0x1000000000)
Definition at line 44 of file mtrr.c.
Referenced by KiGetFeatureBits(), and KiInitializeMTRR().
LONG64 KiMtrrResBitMask = 0xfffffffff
Definition at line 45 of file mtrr.c.
Referenced by KiGetFeatureBits(), and KiLengthToMask().
RANGE_INFO KiRangeInfo
Definition at line 273 of file mtrr.c.
KSPIN_LOCK KiRangeLock
Definition at line 266 of file mtrr.c.
Referenced by KeRestoreMtrr(), KeSetPhysicalCacheTypeRange(), KiAmdK6InitializeMTRR(), KiAmdK6MtrrSetMemoryType(), and KiInitializeMTRR().