Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/bugcheck.c File Reference
bugcheck.c File Reference
#include "ki.h"
#include "wdbgexts.h"
#include <inbv.h>
#include <hdlsterm.h>
Macros
#define BUGCHECK_UNOWNED ((ULONG) -1)
#define MAX_BUFFER 128
#define MINIDUMP_BUGCHECK 0x10000000
#define NOEXTAPI
#define PROGRAM_COUNTER(_trapframe) ((_trapframe)->Eip)
Functions
VOID KeBugCheck (__in ULONG BugCheckCode)
VOID KeBugCheck2 (__in ULONG BugCheckCode, __in ULONG_PTR BugCheckParameter1, __in ULONG_PTR BugCheckParameter2, __in ULONG_PTR BugCheckParameter3, __in ULONG_PTR BugCheckParameter4, __in_opt PKTRAP_FRAME TrapFrame)
VOID KeBugCheckEx (__in ULONG BugCheckCode, __in ULONG_PTR P1, __in ULONG_PTR P2, __in ULONG_PTR P3, __in ULONG_PTR P4)
PCHAR KeBugCheckUnicodeToAnsi (IN PUNICODE_STRING UnicodeString, OUT PCHAR AnsiBuffer, IN ULONG MaxAnsiLength)
NTKERNELAPI BOOLEAN KeDeregisterBugCheckCallback (__inout PKBUGCHECK_CALLBACK_RECORD CallbackRecord)
NTKERNELAPI BOOLEAN KeDeregisterBugCheckReasonCallback (__inout PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord)
VOID KeEnterKernelDebugger (VOID)
BOOLEAN KeGetBugMessageText (__in ULONG MessageId, __out_opt PANSI_STRING ReturnedString)
NTKERNELAPI BOOLEAN KeRegisterBugCheckCallback (__out PKBUGCHECK_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_CALLBACK_ROUTINE CallbackRoutine, __in PVOID Buffer, __in ULONG Length, __in PUCHAR Component)
NTKERNELAPI BOOLEAN KeRegisterBugCheckReasonCallback (__out PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_REASON_CALLBACK_ROUTINE CallbackRoutine, __in KBUGCHECK_CALLBACK_REASON Reason, __in PUCHAR Component)
VOID KiBugCheckDebugBreak (IN ULONG BreakStatus)
VOID KiDisplayBlueScreen (IN ULONG PssMessage, IN BOOLEAN HardErrorCalled, IN PCHAR HardErrorCaption, IN PCHAR HardErrorMessage, IN PCHAR StateString)
VOID KiDumpParameterImages (IN PCHAR Buffer, IN PULONG_PTR BugCheckParameters, IN ULONG NumberOfParameters, IN PKE_BUGCHECK_UNICODE_TO_ANSI UnicodeToAnsiRoutine)
VOID KiInvokeBugCheckEntryCallbacks (VOID)
PVOID KiPcToFileHeader (IN PVOID PcValue, OUT PLDR_DATA_TABLE_ENTRY *DataTableEntry, IN LOGICAL DriversOnly, OUT PBOOLEAN InKernelOrHal)
VOID KiScanBugCheckCallbackList (VOID)
Variables
PVOID ExPoolCodeEnd
PVOID ExPoolCodeStart
PWD_HANDLER ExpWdHandler
PVOID ExpWdHandlerContext
KDDEBUGGER_DATA64 KdDebuggerDataBlock
BOOLEAN KeBugCheckActive = FALSE
LONG KeBugCheckCount = 1
volatile ULONG KeBugCheckOwner = BUGCHECK_UNOWNED
ULONG KeBugCheckOwnerRecursionCount
ULONG_PTR KiBugCheckData [5]
PUNICODE_STRING KiBugCheckDriver
PVOID MmPoolCodeEnd
PVOID MmPoolCodeStart
PVOID MmPteCodeEnd
PVOID MmPteCodeStart
Macro Definition Documentation
#define BUGCHECK_UNOWNED ((ULONG) -1)
Definition at line 114 of file bugcheck.c.
Referenced by KeBugCheck2().
#define MAX_BUFFER 128
Definition at line 56 of file bugcheck.c.
Referenced by KeBugCheck2().
#define MINIDUMP_BUGCHECK 0x10000000
Referenced by KeBugCheck2().
#define NOEXTAPI
Definition at line 20 of file bugcheck.c.
#define PROGRAM_COUNTER (_trapframe) ((_trapframe)->Eip)
Definition at line 44 of file bugcheck.c.
Referenced by KeBugCheck2().
Function Documentation
VOID KeBugCheck (__in ULONG BugCheckCode)
Definition at line 129 of file bugcheck.c.
References KeBugCheck2(), and NULL.
Referenced by ExpInitializeExecutive(), IoAssignDriveLetters(), IoBuildPartialMdl(), KeDetachProcess(), KeUnstackDetachProcess(), KeWaitForMultipleObjects(), Ki386CheckDivideByZeroTrap(), KiGetVectorInfo(), KiInitMachineDependent(), KiSetAffinityThread(), KiSetCacheInformation(), KiSetCpuVendor(), Phase1InitializationDiscard(), PspProcessDelete(), PspSystemThreadStartup(), and PspThreadDelete().
VOID KeBugCheck2 (__in ULONG BugCheckCode, __in ULONG_PTR BugCheckParameter1, __in ULONG_PTR BugCheckParameter2, __in ULONG_PTR BugCheckParameter3, __in ULONG_PTR BugCheckParameter4, __in_opt PKTRAP_FRAME TrapFrame)
Definition at line 409 of file bugcheck.c.
References ACPI_BIOS_ERROR, ACPI_BIOS_FATAL_ERROR, ASSERT, ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY, ATTEMPTED_WRITE_TO_READONLY_MEMORY, _LDR_DATA_TABLE_ENTRY::BaseDllName, BUGCHECK_UNOWNED, BUGCODE_PSS_MESSAGE, BUGCODE_PSS_MESSAGE_SIGNATURE, CONTEXT_CONTROL, CONTEXT_INTEGER, CONTEXT_SEGMENTS, _CONTEXT::ContextFlags, _KPROCESSOR_STATE::ContextFrame, _KTSS::Cs, DATA_BUS_ERROR, DBG_STATUS_BUGCHECK_FIRST, DBG_STATUS_BUGCHECK_SECOND, DbgPrint(), DbgUnLoadImageSymbols(), _KPRCB::DebuggerSavedIRQL, DRIVER_CORRUPTED_EXPOOL, DRIVER_CORRUPTED_MMPOOL, DRIVER_CORRUPTED_SYSPTES, DRIVER_IRQL_NOT_LESS_OR_EQUAL, DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS, DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION, DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL, DRIVER_PORTION_MUST_BE_NONPAGED, DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS, DRIVER_USED_EXCESSIVE_PTES, _KTSS::Ds, _CONTEXT::Eax, _KTSS::Eax, _CONTEXT::Ebp, _KTSS::Ebp, _CONTEXT::Ebx, _KTSS::Ebx, _CONTEXT::Ecx, _KTSS::Ecx, _CONTEXT::Edi, _KTSS::Edi, _CONTEXT::Edx, _KTSS::Edx, _CONTEXT::EFlags, _KTSS::EFlags, EFLAGS_V86_MASK, _CONTEXT::Eip, _KTSS::Eip, _KTSS::Es, _CONTEXT::Esi, _KTSS::Esi, _CONTEXT::Esp, _KTSS::Esp, ExPoolCodeEnd, ExPoolCodeStart, ExpWdHandler, ExpWdHandlerContext, FALSE, FAT_FILE_SYSTEM, FATAL_UNHANDLED_HARD_ERROR, _KTSS::Fs, _KTSS::Gs, HalRebootRoutine, HalReturnToFirmware(), HIGH_LEVEL, INACCESSIBLE_BOOT_DEVICE, InbvDisplayString(), InterlockedDecrement, InterlockedIncrement, IoAddTriageDumpDataBlock(), IoIsTriageDumpEnabled(), IoWriteCrashDump(), IRQL_NOT_LESS_OR_EQUAL, IS_SYSTEM_ADDRESS, KdDebuggerEnabled, KdDebuggerNotPresent, KdEnableDebuggerWithLock(), KdPitchDebugger, KeActiveProcessors, KeBugCheckActive, KeBugCheckCount, KeBugCheckOwner, KeBugCheckOwnerRecursionCount, KeBugCheckUnicodeToAnsi(), KeContextFromKframes(), KeDisableInterrupts(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeNumberProcessors, KeRaiseIrql, KERNEL_MODE_EXCEPTION_NOT_HANDLED, _KTHREAD::KernelStack, KeStallExecutionProcessor(), KGDT_R0_DATA, KiBugCheckData, KiBugCheckDebugBreak(), KiDisplayBlueScreen(), KiDumpParameterImages(), KiHardwareTrigger, KiInvokeBugCheckEntryCallbacks(), KiPcToFileHeader(), KiPollFreezeExecution(), KiProcessorBlock, KiResumeForReboot, KiSaveProcessorControlState(), KiScanBugCheckCallbackList(), KiSendFreeze(), KiSendThawExecution(), KMODE_EXCEPTION_NOT_HANDLED, MANUALLY_INITIATED_CRASH, MAX_BUFFER, MINIDUMP_BUGCHECK, MmIsSessionAddress(), MmIsSpecialPoolAddress(), MmIsSpecialPoolAddressFree(), MmLocateUnloadedDriver(), MmPoolCodeEnd, MmPoolCodeStart, MmPteCodeEnd, MmPteCodeStart, _KTHREAD::NextProcessor, NO_MORE_SYSTEM_PTES, NOTHING, NTFS_FILE_SYSTEM, NULL, _KPRCB::Number, PAGE_ALIGN, PAGE_FAULT_BEYOND_END_OF_ALLOCATION, PAGE_FAULT_IN_FREED_SPECIAL_POOL, PAGE_FAULT_IN_NONPAGED_AREA, PAGE_SIZE, PAUSE_PROCESSOR, POWER_FAILURE_SIMULATE, _KPRCB::ProcessorState, PROGRAM_COUNTER, Ready, _KSWITCHFRAME::RetAddr, RtlCaptureContext(), Running, _KDDEBUGGER_DATA64::SavedContext, _CONTEXT::SegCs, _CONTEXT::SegDs, _CONTEXT::SegEs, _CONTEXT::SegFs, _CONTEXT::SegGs, _CONTEXT::SegSs, _KPRCB::SetMember, _KTSS::Ss, _KTHREAD::State, STATUS_SYSTEM_IMAGE_BAD_SIGNATURE, SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD, SYSTEM_THREAD_EXCEPTION_NOT_HANDLED, _KTHREAD::Teb, TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE, THREAD_STUCK_IN_DEVICE_DRIVER, TRUE, and UNEXPECTED_KERNEL_MODE_TRAP.
Referenced by KeBugCheck(), and KeBugCheckEx().
VOID KeBugCheckEx (__in ULONG BugCheckCode, __in ULONG_PTR P1, __in ULONG_PTR P2, __in ULONG_PTR P3, __in ULONG_PTR P4)
Definition at line 137 of file bugcheck.c.
References KeBugCheck2(), and NULL.
Referenced by __bcount(), CreateSystemRootLink(), ExAllocatePoolSanityChecks(), ExCheckPoolHeader(), ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExInitSystem(), ExMapHandleToPointerEx(), ExpCheckForWorker(), ExpGetBilledProcess(), ExpInitializeExecutive(), ExpSystemErrorHandler(), ExpWorkerThread(), ExQueueWorkItem(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), FsFilterPerformCallbacks(), FsRtlWorkerThread(), InitializePool(), IoCancelFileOpen(), IoCancelIrp(), IoInitSystem(), IopfCompleteRequest(), IopFreeIrp(), IopMarkBootPartition(), IopMountVolume(), IopParseDevice(), KeAttachProcess(), KeCheckForTimer(), KeCheckIfStackExpandCalloutActive(), KeForceAttachProcess(), KeRemoveQueue(), KeRestoreFloatingPointState(), KeRundownThread(), KeStackAttachProcess(), KeStartAllProcessors(), KiDeliverApc(), KiDispatchException(), KiEspToTrapFrame(), KiFatalFilter(), KiInitializeKernel(), KiInitMachineDependent(), KiSetFeatureBits(), MiAddMdlTracker(), MiBadRefCount(), MiCheckPteRelease(), MiCheckPteReserve(), MiCheckSessionPoolAllocations(), MiCheckSystemPteProtection(), MiCleanSection(), MiCloneProcessAddressSpace(), MiComputeInitialLargePage(), MiDecrementReferenceCount(), MiDecrementShareCount(), MiDeleteAddressesInWorkingSet(), MiDeletePte(), MiDeleteSystemPageableVm(), MiDeleteValidSystemPte(), MiEliminateWorkingSetEntry(), MiFreeMdlTracker(), MiFreePoolPages(), MiFreeSessionSpaceMap(), MiFreeWsleList(), MiHandleForkTransitionPte(), MiInitializeCopyOnWritePfn(), MiInitializePfn(), MiInitializePfnAndMakePteValid(), MiInitializeReadInProgressPfn(), MiInitializeReadInProgressSinglePfn(), MiInitializeSessionIds(), MiInitializeTransitionPfn(), MiInitMachineDependent(), MiInPageSingleKernelStack(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiIssueNoPtesBugcheck(), MiLocateWsle(), MiMakeOutswappedPageResident(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MiModifiedPageWriter(), MiNoPagesLastChance(), MiRemoveFromSystemSpace(), MiRemoveIoSpaceMap(), MiRemovePageFromList(), MiRemovePteTracker(), MiRemoveUnusedSegments(), MiRemoveWsle(), MiResolveMappedFileFault(), MiSessionWideInitializeAddresses(), MiSwapWslEntries(), MiTrimPte(), MiUnlinkPageFromList(), MiWaitForInPageComplete(), MiZeroPageWorker(), MmAccessFault(), MmCleanProcessAddressSpace(), MmCommitSessionMappedView(), MmFreeContiguousMemory(), MmFreeMappingAddress(), MmFreePagesFromMdl(), MmGetSizeOfBigPoolAllocation(), MmInitSystem(), MmLockPageableDataSection(), MmMapLockedPagesSpecifyCache(), MmMapLockedPagesWithReservedMapping(), MmMapViewInSystemCache(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmUnlockCachedPage(), MmUnlockPageableImageSection(), MmUnmapReservedMapping(), MmUnmapViewInSystemCache(), MmZeroPageThread(), MxGetNextPage(), ObpCloseHandle(), ObpCloseHandleTableEntry(), Phase1InitializationDiscard(), PsInitSystem(), PsLocateSystemDll(), PspCatchCriticalBreak(), PspExitThread(), PspInitializeSystemDll(), PspInitPhase0(), PspUnhandledExceptionInSystemThread(), RawDispatch(), RtlpGetStackLimits(), SeDefaultObjectMethod(), SeInitSystem(), SepAuditFailed(), SepDeReferenceLogonSession(), and WmipSecurityMethod().
PCHAR KeBugCheckUnicodeToAnsi (IN PUNICODE_STRING UnicodeString, OUT PCHAR AnsiBuffer, IN ULONG MaxAnsiLength)
Definition at line 216 of file bugcheck.c.
Referenced by KeBugCheck2().
NTKERNELAPI BOOLEAN KeDeregisterBugCheckCallback (__inout PKBUGCHECK_CALLBACK_RECORD CallbackRecord)
Definition at line 1324 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, KeBugCheckCallbackLock, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), RemoveEntryList(), and TRUE.
NTKERNELAPI BOOLEAN KeDeregisterBugCheckReasonCallback (__inout PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord)
Definition at line 1588 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, KeBugCheckCallbackLock, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), RemoveEntryList(), and TRUE.
VOID KeEnterKernelDebugger (VOID)
Definition at line 1273 of file bugcheck.c.
References DBG_STATUS_FATAL, FALSE, HIGH_LEVEL, InterlockedDecrement, KdDebuggerEnabled, KdInitSystem(), KdPitchDebugger, KeBugCheckCount, KeDisableInterrupts(), KeRaiseIrql, KiBugCheckDebugBreak(), KiHardwareTrigger, and NULL.
BOOLEAN KeGetBugMessageText (__in ULONG MessageId, __out_opt PANSI_STRING ReturnedString)
Definition at line 154 of file bugcheck.c.
References ARGUMENT_PRESENT, _MESSAGE_RESOURCE_DATA::Blocks, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InbvDisplayString(), KiBugCodeMessages, _MESSAGE_RESOURCE_BLOCK::LowId, MmMakeKernelResourceSectionWritable(), NULL, _MESSAGE_RESOURCE_DATA::NumberOfBlocks, _MESSAGE_RESOURCE_BLOCK::OffsetToEntries, strlen(), and TRUE.
NTKERNELAPI BOOLEAN KeRegisterBugCheckCallback (__out PKBUGCHECK_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_CALLBACK_ROUTINE CallbackRoutine, __in PVOID Buffer, __in ULONG Length, __in PUCHAR Component)
Definition at line 1383 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, InsertHeadList(), KeBugCheckCallbackListHead, KeBugCheckCallbackLock, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), and TRUE.
NTKERNELAPI BOOLEAN KeRegisterBugCheckReasonCallback (__out PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_REASON_CALLBACK_ROUTINE CallbackRoutine, __in KBUGCHECK_CALLBACK_REASON Reason, __in PUCHAR Component)
Definition at line 1647 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, InsertHeadList(), KeBugCheckCallbackLock, KeBugCheckReasonCallbackListHead, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), and TRUE.
VOID KiBugCheckDebugBreak (IN ULONG BreakStatus)
Definition at line 240 of file bugcheck.c.
References DBG_STATUS_BUGCHECK_FIRST, DbgBreakPointWithStatus(), except, EXCEPTION_EXECUTE_HANDLER, HalHaltSystem, HeadlessCmdDoBugCheckProcessing, HeadlessCmdPutString, HeadlessCmdQueryInformation, HeadlessDispatch(), HeadlessSerialPort, NT_SUCCESS, NULL, _HEADLESS_RSP_QUERY_INFO::PortType, _HEADLESS_RSP_QUERY_INFO::Serial, and Status.
Referenced by KeBugCheck2(), and KeEnterKernelDebugger().
VOID KiDisplayBlueScreen (IN ULONG PssMessage, IN BOOLEAN HardErrorCalled, IN PCHAR HardErrorCaption, IN PCHAR HardErrorMessage, IN PCHAR StateString)
Referenced by KeBugCheck2().
VOID KiDumpParameterImages (IN PCHAR Buffer, IN PULONG_PTR BugCheckParameters, IN ULONG NumberOfParameters, IN PKE_BUGCHECK_UNICODE_TO_ANSI UnicodeToAnsiRoutine)
Referenced by KeBugCheck2().
VOID KiInvokeBugCheckEntryCallbacks (VOID)
Definition at line 1729 of file bugcheck.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, _LIST_ENTRY::Blink, BufferFinished, BufferIncomplete, BufferInserted, _KBUGCHECK_REASON_CALLBACK_RECORD::CallbackRoutine, _KBUGCHECK_REASON_CALLBACK_RECORD::Checksum, _KBUGCHECK_REASON_CALLBACK_RECORD::Component, CONTAINING_RECORD, _KBUGCHECK_REASON_CALLBACK_RECORD::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LIST_ENTRY::Flink, KbCallbackReserved1, KeBugCheckReasonCallbackListHead, MmIsAddressValid(), NULL, PAGE_ALIGN, PAGE_SIZE, _KBUGCHECK_REASON_CALLBACK_RECORD::Reason, and _KBUGCHECK_REASON_CALLBACK_RECORD::State.
Referenced by KeBugCheck2().
PVOID KiPcToFileHeader (IN PVOID PcValue, OUT PLDR_DATA_TABLE_ENTRY * DataTableEntry, IN LOGICAL DriversOnly, OUT PBOOLEAN InKernelOrHal)
Definition at line 308 of file bugcheck.c.
References CONTAINING_RECORD, _LDR_DATA_TABLE_ENTRY::DllBase, FALSE, _LIST_ENTRY::Flink, KeLoaderBlock, _LOADER_PARAMETER_BLOCK::LoadOrderListHead, MmIsAddressValid(), NULL, PsLoadedModuleList, _LDR_DATA_TABLE_ENTRY::SizeOfImage, and TRUE.
Referenced by KeBugCheck2().
VOID KiScanBugCheckCallbackList (VOID)
Definition at line 1467 of file bugcheck.c.
References _LIST_ENTRY::Blink, _KBUGCHECK_CALLBACK_RECORD::Buffer, BufferFinished, BufferIncomplete, BufferInserted, BufferStarted, _KBUGCHECK_CALLBACK_RECORD::CallbackRoutine, _KBUGCHECK_CALLBACK_RECORD::Checksum, _KBUGCHECK_CALLBACK_RECORD::Component, CONTAINING_RECORD, _KBUGCHECK_CALLBACK_RECORD::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LIST_ENTRY::Flink, Index, KeBugCheckCallbackListHead, _KBUGCHECK_CALLBACK_RECORD::Length, MmIsAddressValid(), NULL, and _KBUGCHECK_CALLBACK_RECORD::State.
Referenced by KeBugCheck2().
Variable Documentation
PVOID ExPoolCodeEnd
Definition at line 59 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID ExPoolCodeStart
Definition at line 58 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PWD_HANDLER ExpWdHandler
Definition at line 83 of file sysinfo.c.
Referenced by KeBugCheck2(), NtQuerySystemInformation(), and NtSetSystemInformation().
PVOID ExpWdHandlerContext
Definition at line 84 of file sysinfo.c.
Referenced by KeBugCheck2(), NtQuerySystemInformation(), and NtSetSystemInformation().
KDDEBUGGER_DATA64 KdDebuggerDataBlock
BOOLEAN KeBugCheckActive = FALSE
Definition at line 124 of file bugcheck.c.
Referenced by KeBugCheck2(), KeFreezeExecution(), KeQueryCurrentStackInformation(), KiFreezeTargetExecution(), and KiProcessNMI().
LONG KeBugCheckCount = 1
Definition at line 97 of file bugcheck.c.
Referenced by KeBugCheck2(), and KeEnterKernelDebugger().
volatile ULONG KeBugCheckOwner = BUGCHECK_UNOWNED
Definition at line 116 of file bugcheck.c.
Referenced by KeBugCheck2().
ULONG KeBugCheckOwnerRecursionCount
Definition at line 104 of file bugcheck.c.
Referenced by KeBugCheck2().
ULONG_PTR KiBugCheckData[5]
Definition at line 150 of file bugcheck.c.
Referenced by KeBugCheck2().
PUNICODE_STRING KiBugCheckDriver
Definition at line 151 of file bugcheck.c.
PVOID MmPoolCodeEnd
Definition at line 61 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID MmPoolCodeStart
Definition at line 60 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID MmPteCodeEnd
Definition at line 63 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID MmPteCodeStart
Definition at line 62 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().