Windows Research Kernel v1.2: C:/Windows Research Kernel/se/adtinit.c File Reference
adtinit.c File Reference
#include "pch.h"
Functions
VOID SepAdtInitializeAuditingOptions (VOID)
VOID SepAdtInitializeBounds (VOID)
NTSTATUS SepAdtInitializeCrashOnFail (VOID)
BOOLEAN SepAdtInitializePrivilegeAuditing (VOID)
BOOLEAN SepAdtValidateAuditBounds (ULONG Upper, ULONG Lower)
Function Documentation
VOID SepAdtInitializeAuditingOptions (VOID)
Definition at line 305 of file adtinit.c.
References _SEP_AUDIT_OPTIONS::DoNotAuditCloseObjectEvents, FALSE, NT_SUCCESS, PAGED_CODE, SepAuditOptions, SepRegQueryDwordValue(), Status, and TRUE.
Referenced by SeRmInitPhase1().
VOID SepAdtInitializeBounds (VOID)
Definition at line 81 of file adtinit.c.
References _SEP_AUDIT_BOUNDS::LowerBound, NT_SUCCESS, NULL, PAGED_CODE, REG_BINARY, SepAdtMaxListLength, SepAdtMinListLength, SepAdtValidateAuditBounds(), SepRegQueryHelper(), Status, and _SEP_AUDIT_BOUNDS::UpperBound.
Referenced by SepRmSetAuditEventWrkr().
NTSTATUS SepAdtInitializeCrashOnFail (VOID)
Definition at line 150 of file adtinit.c.
References CRASH_ON_AUDIT_FAIL_VALUE, FALSE, LSAP_CRASH_ON_AUDIT_FAIL, NT_SUCCESS, PAGED_CODE, SepCrashOnAuditFail, SepRegQueryDwordValue(), Status, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and TRUE.
Referenced by SeRmInitPhase1().
BOOLEAN SepAdtInitializePrivilegeAuditing (VOID)
Definition at line 209 of file adtinit.c.
References ASSERT, _KEY_VALUE_PARTIAL_INFORMATION::Data, FALSE, FULL_PRIVILEGE_AUDITING, InitializeObjectAttributes, KEY_QUERY_VALUE, KEY_SET_VALUE, KeyName, KeyValuePartialInformation, NT_SUCCESS, NtClose(), NtOpenKey(), NtQueryValueKey(), NULL, OBJ_CASE_INSENSITIVE, PAGED_CODE, RtlInitUnicodeString(), SepInitializePrivilegeFilter(), Status, and STATUS_OBJECT_NAME_NOT_FOUND.
Referenced by SeRmInitPhase1().
BOOLEAN SepAdtValidateAuditBounds (ULONG Upper, ULONG Lower)
Definition at line 34 of file adtinit.c.
References FALSE, PAGED_CODE, and TRUE.
Referenced by SepAdtInitializeBounds().