Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntlpcapi.h File Reference
ntlpcapi.h File Reference
Data Structures
struct _LPC_CLIENT_DIED_MSG
struct _PORT_DATA_ENTRY
struct _PORT_DATA_INFORMATION
struct _PORT_MESSAGE
struct _PORT_VIEW
struct _REMOTE_PORT_VIEW
Macros
#define LPC_CLIENT_DIED 6
#define LPC_CLIENT_ID CLIENT_ID
#define LPC_CONNECTION_REQUEST 10
#define LPC_DATAGRAM 3
#define LPC_DEBUG_EVENT 8
#define LPC_ERROR_EVENT 9
#define LPC_EXCEPTION 7
#define LPC_HANDLE HANDLE
#define LPC_KERNELMODE_MESSAGE (CSHORT)0x8000
#define LPC_LOST_REPLY 4
#define LPC_MAX_CONNECTION_INFO_SIZE (16 * sizeof(ULONG_PTR))
#define LPC_NO_IMPERSONATE (CSHORT)0x4000
#define LPC_PORT_CLOSED 5
#define LPC_PVOID PVOID
#define LPC_REPLY 2
#define LPC_REQUEST 1
#define LPC_SIZE_T SIZE_T
#define PORT_ALL_ACCESS
#define PORT_CONNECT (0x0001)
#define PORT_MAXIMUM_MESSAGE_LENGTH 256
#define PORT_TOTAL_MAXIMUM_MESSAGE_LENGTH ((PORT_MAXIMUM_MESSAGE_LENGTH + sizeof (PORT_MESSAGE) + LPC_MAX_CONNECTION_INFO_SIZE + 15) & ~15)
#define PORT_VALID_OBJECT_ATTRIBUTES (OBJ_CASE_INSENSITIVE)
Typedefs
typedef struct _LPC_CLIENT_DIED_MSG LPC_CLIENT_DIED_MSG
typedef struct _LPC_CLIENT_DIED_MSG * PLPC_CLIENT_DIED_MSG
typedef struct _PORT_DATA_ENTRY PORT_DATA_ENTRY
typedef struct _PORT_DATA_INFORMATION PORT_DATA_INFORMATION
typedef enum _PORT_INFORMATION_CLASS PORT_INFORMATION_CLASS
typedef struct _PORT_MESSAGE PORT_MESSAGE
typedef struct _PORT_VIEW PORT_VIEW
typedef struct _PORT_DATA_ENTRY * PPORT_DATA_ENTRY
typedef struct _PORT_DATA_INFORMATION * PPORT_DATA_INFORMATION
typedef struct _PORT_MESSAGE * PPORT_MESSAGE
typedef struct _PORT_VIEW * PPORT_VIEW
typedef struct _REMOTE_PORT_VIEW * PREMOTE_PORT_VIEW
typedef struct _REMOTE_PORT_VIEW REMOTE_PORT_VIEW
Enumerations
enum _PORT_INFORMATION_CLASS { PortBasicInformation }
Functions
NTSYSCALLAPI NTSTATUS NTAPI NtAcceptConnectPort (__out PHANDLE PortHandle, __in_opt PVOID PortContext, __in PPORT_MESSAGE ConnectionRequest, __in BOOLEAN AcceptConnection, __inout_opt PPORT_VIEW ServerView, __out_opt PREMOTE_PORT_VIEW ClientView)
NTSYSCALLAPI NTSTATUS NTAPI NtCompleteConnectPort (__in HANDLE PortHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtCreatePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateWaitablePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
NTSYSCALLAPI NTSTATUS NTAPI NtImpersonateClientOfPort (__in HANDLE PortHandle, __in PPORT_MESSAGE Message)
NTSYSCALLAPI NTSTATUS NTAPI NtListenPort (__in HANDLE PortHandle, __out PPORT_MESSAGE ConnectionRequest)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationPort (__in HANDLE PortHandle, __in PORT_INFORMATION_CLASS PortInformationClass, __out_bcount(Length) PVOID PortInformation, __in ULONG Length, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtReadRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
NTSYSCALLAPI NTSTATUS NTAPI NtReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE ReplyMessage)
NTSYSCALLAPI NTSTATUS NTAPI NtReplyWaitReceivePort (__in HANDLE PortHandle, __out_opt PVOID *PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage)
NTSYSCALLAPI NTSTATUS NTAPI NtReplyWaitReceivePortEx (__in HANDLE PortHandle, __out_opt PVOID *PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtReplyWaitReplyPort (__in HANDLE PortHandle, __inout PPORT_MESSAGE ReplyMessage)
NTSYSCALLAPI NTSTATUS NTAPI NtRequestPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage)
NTSYSCALLAPI NTSTATUS NTAPI NtRequestWaitReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
NTSYSCALLAPI NTSTATUS NTAPI NtSecureConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __in_opt PSID RequiredServerSid, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtWriteRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __in_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Macro Definition Documentation
#define LPC_CLIENT_DIED 6
Definition at line 104 of file ntlpcapi.h.
Referenced by LpcpRequestWaitReplyPort(), LpcRequestPort(), and PspExitThread().
#define LPC_CLIENT_ID CLIENT_ID
Definition at line 48 of file ntlpcapi.h.
#define LPC_CONNECTION_REQUEST 10
Definition at line 108 of file ntlpcapi.h.
Referenced by LpcpDestroyPortQueue(), LpcpFreeToPortZone(), NtAcceptConnectPort(), NtListenPort(), NtReplyWaitReceivePortEx(), NtSecureConnectPort(), and SepRmCommandServerThread().
#define LPC_DATAGRAM 3
Definition at line 101 of file ntlpcapi.h.
Referenced by LpcRequestPort(), and NtRequestPort().
#define LPC_DEBUG_EVENT 8
Definition at line 106 of file ntlpcapi.h.
Referenced by LpcpRequestWaitReplyPort().
#define LPC_ERROR_EVENT 9
Definition at line 107 of file ntlpcapi.h.
Referenced by ExpRaiseHardError(), and LpcpRequestWaitReplyPort().
#define LPC_EXCEPTION 7
Definition at line 105 of file ntlpcapi.h.
Referenced by DbgkForwardException(), and LpcpRequestWaitReplyPort().
#define LPC_HANDLE HANDLE
Definition at line 51 of file ntlpcapi.h.
#define LPC_KERNELMODE_MESSAGE (CSHORT)0x8000
Definition at line 119 of file ntlpcapi.h.
Referenced by LpcpDestroyPortQueue(), LpcpFreeToPortZone(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtAcceptConnectPort(), NtListenPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and SepRmCommandServerThread().
#define LPC_LOST_REPLY 4
Definition at line 102 of file ntlpcapi.h.
#define LPC_MAX_CONNECTION_INFO_SIZE (16 * sizeof(ULONG_PTR))
Definition at line 134 of file ntlpcapi.h.
#define LPC_NO_IMPERSONATE (CSHORT)0x4000
Definition at line 123 of file ntlpcapi.h.
Referenced by NtRequestWaitReplyPort().
#define LPC_PORT_CLOSED 5
Definition at line 103 of file ntlpcapi.h.
Referenced by LpcpDeletePort(), LpcpRequestWaitReplyPort(), and SepRmCommandServerThread().
#define LPC_PVOID PVOID
Definition at line 50 of file ntlpcapi.h.
#define LPC_REPLY 2
Definition at line 100 of file ntlpcapi.h.
Referenced by NtAcceptConnectPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), and NtReplyWaitReplyPort().
#define LPC_REQUEST 1
Definition at line 99 of file ntlpcapi.h.
Referenced by LpcpRequestWaitReplyPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), and SepRmCommandServerThread().
#define LPC_SIZE_T SIZE_T
Definition at line 49 of file ntlpcapi.h.
#define PORT_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED | \
                         SYNCHRONIZE | 0x1)
Definition at line 37 of file ntlpcapi.h.
Referenced by LpcInitSystem(), LpcpCreatePort(), NtAcceptConnectPort(), and NtSecureConnectPort().
#define PORT_CONNECT (0x0001)
Definition at line 35 of file ntlpcapi.h.
Referenced by NtSecureConnectPort().
#define PORT_MAXIMUM_MESSAGE_LENGTH 256
Definition at line 131 of file ntlpcapi.h.
Referenced by LpcInitSystem().
#define PORT_TOTAL_MAXIMUM_MESSAGE_LENGTH ((PORT_MAXIMUM_MESSAGE_LENGTH + sizeof (PORT_MESSAGE) + LPC_MAX_CONNECTION_INFO_SIZE + 15) & ~15)
Definition at line 136 of file ntlpcapi.h.
Referenced by DbgkpSendApiMessageLpc(), and ExpRaiseHardError().
#define PORT_VALID_OBJECT_ATTRIBUTES (OBJ_CASE_INSENSITIVE)
Definition at line 125 of file ntlpcapi.h.
Referenced by LpcInitSystem().
Typedef Documentation
typedef struct _LPC_CLIENT_DIED_MSG LPC_CLIENT_DIED_MSG
typedef struct _LPC_CLIENT_DIED_MSG * PLPC_CLIENT_DIED_MSG
typedef struct _PORT_DATA_ENTRY PORT_DATA_ENTRY
typedef struct _PORT_DATA_INFORMATION PORT_DATA_INFORMATION
typedef enum _PORT_INFORMATION_CLASS PORT_INFORMATION_CLASS
typedef struct _PORT_MESSAGE PORT_MESSAGE
typedef struct _PORT_VIEW PORT_VIEW
typedef struct _PORT_DATA_ENTRY * PPORT_DATA_ENTRY
typedef struct _PORT_DATA_INFORMATION * PPORT_DATA_INFORMATION
typedef struct _PORT_MESSAGE * PPORT_MESSAGE
typedef struct _PORT_VIEW * PPORT_VIEW
typedef struct _REMOTE_PORT_VIEW * PREMOTE_PORT_VIEW
typedef struct _REMOTE_PORT_VIEW REMOTE_PORT_VIEW
Enumeration Type Documentation
enum _PORT_INFORMATION_CLASS
Enumerator
PortBasicInformation
Definition at line 344 of file ntlpcapi.h.
Function Documentation
NTSYSCALLAPI NTSTATUS NTAPI NtAcceptConnectPort (__out PHANDLE PortHandle, __in_opt PVOID PortContext, __in PPORT_MESSAGE ConnectionRequest, __in BOOLEAN AcceptConnection, __inout_opt PPORT_VIEW ServerView, __out_opt PREMOTE_PORT_VIEW ClientView)
Definition at line 38 of file lpccompl.c.
References ARGUMENT_PRESENT, _ETHREAD::Cid, _PORT_MESSAGE::ClientId, _LPCP_CONNECTION_MESSAGE::ClientPort, _LPCP_PORT_OBJECT::ClientSectionBase, _LPCP_PORT_OBJECT::ClientThread, _LPCP_CONNECTION_MESSAGE::ClientView, _PORT_MESSAGE::ClientViewSize, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_PORT_OBJECT::Creator, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, _LPCP_PORT_OBJECT::Flags, Handle, _LARGE_INTEGER::HighPart, InitializeListHead(), KeGetPreviousMode, KeReleaseSemaphore(), KernelMode, _PORT_VIEW::Length, _LARGE_INTEGER::LowPart, LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPC_REPLY, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LpcpAcquireLpcpLock, LpcpGetThreadMessage, LpcPortObjectType, LpcpPrepareToWakeClient(), LpcpPrint, LpcpReleaseLpcpLock, LpcpTrace, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MappingProcess, _LPCP_PORT_OBJECT::MaxConnectionInfoLength, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, MmMapViewOfSection(), MmSectionObjectType, NT_SUCCESS, NtClose(), NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGE_READWRITE, PAGED_CODE, PORT_ALL_ACCESS, _LPCP_PORT_OBJECT::PortContext, ProbeAndReadStructure, ProbeAndReadUlong, ProbeForReadSmallStructure, ProbeForWriteHandle, ProbeForWriteSmallStructure(), PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LPCP_MESSAGE::Request, RtlCopyMemory, RtlZeroMemory, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SECTION_MAP_READ, SECTION_MAP_WRITE, _PORT_VIEW::SectionHandle, _PORT_VIEW::SectionOffset, _LPCP_CONNECTION_MESSAGE::SectionToMap, SERVER_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ServerProcess, _LPCP_PORT_OBJECT::ServerSectionBase, _LPCP_CONNECTION_MESSAGE::ServerView, Status, STATUS_INVALID_PARAMETER, STATUS_REPLY_MESSAGE_MISMATCH, THREAD_TO_PROCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _PORT_VIEW::ViewBase, _REMOTE_PORT_VIEW::ViewBase, _PORT_VIEW::ViewRemoteBase, _PORT_VIEW::ViewSize, _REMOTE_PORT_VIEW::ViewSize, and ViewUnmap.
NTSYSCALLAPI NTSTATUS NTAPI NtCompleteConnectPort (__in HANDLE PortHandle)
Definition at line 865 of file lpccompl.c.
References _LPCP_PORT_OBJECT::ClientThread, _LPCP_PORT_OBJECT::ConnectionPort, FALSE, _LPCP_PORT_OBJECT::Flags, _LIST_ENTRY::Flink, KeGetPreviousMode, KeReleaseSemaphore(), LpcpAcquireLpcpLock, LpcpGetThreadMessage, LpcpPrepareToWakeClient(), LpcpReferencePortObject, LpcpReleaseLpcpLock, _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplySemaphore, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PORT_TYPE, SERVER_COMMUNICATION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_INVALID_PORT_HANDLE, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
Definition at line 42 of file lpcconn.c.
References NtSecureConnectPort(), and NULL.
Referenced by IopConnectLinkTrackingPort(), and IopErrorLogConnectPort().
NTSYSCALLAPI NTSTATUS NTAPI NtCreatePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
Definition at line 43 of file lpccreat.c.
References FALSE, LpcpCreatePort(), PAGED_CODE, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateWaitablePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
Definition at line 85 of file lpccreat.c.
References LpcpCreatePort(), PAGED_CODE, Status, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtImpersonateClientOfPort (__in HANDLE PortHandle, __in PPORT_MESSAGE Message)
Definition at line 29 of file lpcpriv.c.
References _LPCP_PORT_OBJECT::ConnectedPort, except, EXCEPTION_EXECUTE_HANDLER, _LPCP_PORT_OBJECT::Flags, KeGetPreviousMode, KernelMode, LPCP_NO_IMPERSONATION, LPCP_VALIDATE_REASON_IMPERSONATION, LpcpAcquireLpcpLock, LpcpFreeDynamicClientSecurity, LpcpGetDynamicClientSecurity, LpcpGetThreadAttributes, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpValidateClientPort(), _ETHREAD::LpcReplyMessageId, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectSafe(), PAGED_CODE, PORT_DYNAMIC_SECURITY, PORT_TYPE, ProbeForReadSmallStructure, PsLookupProcessThreadByCid(), SeImpersonateClientEx(), SERVER_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::StaticSecurity, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PORT_HANDLE, STATUS_PORT_DISCONNECTED, and STATUS_REPLY_MESSAGE_MISMATCH.
NTSYSCALLAPI NTSTATUS NTAPI NtListenPort (__in HANDLE PortHandle, __out PPORT_MESSAGE ConnectionRequest)
Definition at line 27 of file lpclistn.c.
References except, EXCEPTION_EXECUTE_HANDLER, LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, NtReplyWaitReceivePort(), NULL, PAGED_CODE, Status, STATUS_SUCCESS, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationPort (__in HANDLE PortHandle, __in PORT_INFORMATION_CLASS PortInformationClass, __out_bcount(Length) PVOID PortInformation, __in ULONG Length, __out_opt PULONG ReturnLength)
Definition at line 28 of file lpcquery.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, GENERIC_READ, KeGetPreviousMode, KernelMode, LpcPortObjectType, LpcWaitablePortObjectType, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWrite(), ProbeForWriteUlong, Status, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
NTSYSCALLAPI NTSTATUS NTAPI NtReadRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
Definition at line 870 of file lpcreply.c.
References FALSE, LpcpCopyRequestData(), and PAGED_CODE.
NTSYSCALLAPI NTSTATUS NTAPI NtReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE ReplyMessage)
Definition at line 59 of file lpcreply.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, _PORT_MESSAGE::ClientId, DbgBreakPoint(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, InitializeListHead(), IsListEmpty, KeGetPreviousMode, KeReleaseSemaphore(), KernelMode, LPC_KERNELMODE_MESSAGE, LPC_REPLY, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpTrace, LpcpTraceError, LpcpValidateClientPort(), _ETHREAD::LpcReceivedMessageId, _ETHREAD::LpcReceivedMsgIdValid, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, ProbeForReadSmallStructure, PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, THREAD_TO_PROCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, and _CLIENT_ID::UniqueThread.
NTSYSCALLAPI NTSTATUS NTAPI NtReplyWaitReceivePort (__in HANDLE PortHandle, __out_opt PVOID * PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage)
Definition at line 28 of file lpcrecv.c.
References NtReplyWaitReceivePortEx(), NULL, and PAGED_CODE.
Referenced by NtListenPort().
NTSYSCALLAPI NTSTATUS NTAPI NtReplyWaitReceivePortEx (__in HANDLE PortHandle, __out_opt PVOID * PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage, __in_opt PLARGE_INTEGER Timeout)
Definition at line 102 of file lpcrecv.c.
References ARGUMENT_PRESENT, _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ConnectionPort, DbgBreakPoint(), _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), IS_SYSTEM_THREAD, IsListEmpty, KdBreakPoint, KeGetPreviousMode, KeReleaseSemaphore(), KeResetEvent(), KernelMode, KeWaitForSingleObject(), LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPC_REPLY, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpSaveDataInfoMessage(), LpcpTrace, LpcpTraceError, LpcpValidateClientPort(), _ETHREAD::LpcReceivedMessageId, _ETHREAD::LpcReceivedMsgIdValid, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_MESSAGE::PortContext, ProbeAndReadLargeInteger, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), ProbeForWriteUlong, PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LARGE_INTEGER::QuadPart, _LPCP_PORT_QUEUE::ReceiveHead, RemoveEntryList(), RemoveHeadList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, RtlCopyMemory, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_TO_PROCESS, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, UserMode, _LPCP_PORT_OBJECT::WaitEvent, and WrLpcReceive.
Referenced by NtReplyWaitReceivePort().
NTSYSCALLAPI NTSTATUS NTAPI NtReplyWaitReplyPort (__in HANDLE PortHandle, __inout PPORT_MESSAGE ReplyMessage)
Definition at line 399 of file lpcreply.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ConnectedPort, DbgBreakPoint(), _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), InsertTailList(), IsListEmpty, KeGetPreviousMode, KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), LPC_KERNELMODE_MESSAGE, LPC_REPLY, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpSetPortToThread, LpcpTrace, LpcpTraceError, LpcpValidateClientPort(), _ETHREAD::LpcReceivedMessageId, _ETHREAD::LpcReceivedMsgIdValid, _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_TYPE, ProbeForWriteSmallStructure(), PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_LPC_REPLY_LOST, STATUS_NO_MEMORY, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_USER_APC, THREAD_TO_PROCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, and WrExecutive.
NTSYSCALLAPI NTSTATUS NTAPI NtRequestPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage)
Definition at line 41 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LPCP_PORT_OBJECT::Flags, InsertTailList(), KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), LPC_DATAGRAM, LPC_KERNELMODE_MESSAGE, LPC_RELEASE_WAIT_INCREMENT, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateMessageId, LpcpMoveMessage(), LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyMessageId, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectSafe(), PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PROBE_ALIGNMENT, ProbeForReadSmallStructure, PsGetCurrentProcess(), PsGetCurrentThread(), _LPCP_PORT_QUEUE::ReceiveHead, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, _ETHREAD::Tcb, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, and _LPCP_PORT_OBJECT::WaitEvent.
Referenced by IopErrorLogThread().
NTSYSCALLAPI NTSTATUS NTAPI NtRequestWaitReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
Definition at line 430 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _PORT_DATA_INFORMATION::CountDataEntries, _PORT_DATA_INFORMATION::DataEntries, DbgBreakPoint(), _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), InsertTailList(), IsListEmpty, KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LPC_KERNELMODE_MESSAGE, LPC_NO_IMPERSONATE, LPC_RELEASE_WAIT_INCREMENT, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_NO_IMPERSONATION, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateCallbackId, LpcpGenerateMessageId, LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpSaveDataInfoMessage(), LpcpSetPortToThread, LpcpSetThreadAttributes, LpcpTrace, LpcpValidateClientPort(), _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PROBE_ALIGNMENT, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LPCP_PORT_QUEUE::ReceiveHead, RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_LPC_REPLY_LOST, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_THREAD_IS_TERMINATING, STATUS_USER_APC, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, _LPCP_PORT_OBJECT::WaitEvent, WrExecutive, and WrLpcReply.
NTSYSCALLAPI NTSTATUS NTAPI NtSecureConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __in_opt PSID RequiredServerSid, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
Definition at line 83 of file lpcconn.c.
References ARGUMENT_PRESENT, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_CONNECTION_MESSAGE::ClientPort, _LPCP_PORT_OBJECT::ClientSectionBase, _LPCP_CONNECTION_MESSAGE::ClientView, _PORT_MESSAGE::ClientViewSize, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, FIELD_OFFSET, _LPCP_PORT_OBJECT::Flags, Handle, _LARGE_INTEGER::HighPart, InitializeListHead(), InsertTailList(), KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _PORT_VIEW::Length, _LARGE_INTEGER::LowPart, LPC_CONNECTION_REQUEST, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeConMsg(), LpcpFreeToPortZone(), LpcpGenerateMessageId, LpcpInitializePortQueue(), LpcPortObjectType, LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MappingProcess, _LPCP_PORT_OBJECT::MaxConnectionInfoLength, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, MmMapViewOfSection(), MmSectionObjectType, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NtClose(), NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, ObReferenceObjectByHandle, ObReferenceObjectByName(), PAGE_READWRITE, PAGED_CODE, PagedPool, PORT_ALL_ACCESS, PORT_CONNECT, PORT_DYNAMIC_SECURITY, PORT_NAME_DELETED, PORT_TYPE, PORT_WAITABLE, ProbeAndReadStructure, ProbeAndReadUlong, ProbeForWrite(), ProbeForWriteHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsGetCurrentThread(), PsReferencePrimaryToken(), _LPCP_PORT_QUEUE::ReceiveHead, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, RtlCopyMemory, RtlEqualSid(), RtlZeroMemory, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SeCaptureSid(), SeCreateClientSecurity(), SECTION_MAP_READ, SECTION_MAP_WRITE, _PORT_VIEW::SectionHandle, _PORT_VIEW::SectionOffset, _LPCP_CONNECTION_MESSAGE::SectionToMap, SECURITY_DYNAMIC_TRACKING, _LPCP_PORT_OBJECT::SecurityQos, _LPCP_PORT_QUEUE::Semaphore, SeQueryInformationToken(), SeReleaseSid(), SERVER_CONNECTION_PORT, _LPCP_PORT_OBJECT::ServerProcess, _LPCP_CONNECTION_MESSAGE::ServerView, _SID_AND_ATTRIBUTES::Sid, _LPCP_PORT_OBJECT::StaticSecurity, Status, STATUS_INVALID_PARAMETER, STATUS_INVALID_PORT_HANDLE, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, STATUS_PORT_CONNECTION_REFUSED, STATUS_SERVER_SID_MISMATCH, STATUS_SUCCESS, STATUS_USER_APC, _ETHREAD::Tcb, TokenUser, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _TOKEN_USER::User, _PORT_VIEW::ViewBase, _PORT_VIEW::ViewSize, ViewUnmap, _LPCP_PORT_OBJECT::WaitEvent, and WrExecutive.
Referenced by NtConnectPort().
NTSYSCALLAPI NTSTATUS NTAPI NtWriteRequestData (__in HANDLE PortHandle, __in PPORT_MESSAGE Message, __in ULONG DataEntryIndex, __in_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Definition at line 927 of file lpcreply.c.
References LpcpCopyRequestData(), PAGED_CODE, and TRUE.