Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmdelete.c File Reference
cmdelete.c File Reference
#include "cmp.h"
Functions
VOID CmpDeleteKeyObject (IN PVOID Object)
VOID CmpDoQueueLateUnloadWorker (IN PCMHIVE CmHive)
VOID CmpLateUnloadHiveWorker (IN PVOID Hive)
Variables
BOOLEAN HvShutdownComplete
Function Documentation
VOID CmpDeleteKeyObject (IN PVOID Object)
Definition at line 40 of file cmdelete.c.
References ASSERT, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_FLOW, CmpCallCallBacks(), CmpDelayDerefKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpDoQueueLateUnloadWorker(), CmpFlushNotify(), CmpLockRegistry(), CmPostCallbackNotification, CmpUnlockRegistry(), CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::Delete, DelistKeyBodyFromKCB(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, FALSE, _CM_KEY_CONTROL_BLOCK::Flags, Hive, IsHiveFrozen, KEY_BODY_TYPE, KEY_PREDEF_HANDLE, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NULL, _REG_KEY_HANDLE_CLOSE_INFORMATION::Object, REG_PREDEF_HANDLE_MASK, RegNtPostKeyHandleClose, RegNtPreKeyHandleClose, STATUS_SUCCESS, TRUE, and _CM_KEY_BODY::Type.
Referenced by CmpCreateObjectTypes().
VOID CmpDoQueueLateUnloadWorker (IN PCMHIVE CmHive)
Definition at line 186 of file cmdelete.c.
References ASSERT, CM_PAGED_CODE, CmLockHive, CmpLateUnloadHiveWorker(), CmUnlockHive, DelayedWorkQueue, ExAllocatePool, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), InterlockedCompareExchangePointer, NonPagedPool, and NULL.
Referenced by CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpDoFlushNextHive(), and CmpRunDownDelayDerefKCBEngine().
VOID CmpLateUnloadHiveWorker (IN PVOID Hive)
Definition at line 220 of file cmdelete.c.
References ASSERT, ASSERT_KCB, Cell, CM_PAGED_CODE, CM_UNLOAD_REG_LOCKED_EX, CmpDereferenceKeyControlBlock(), CmpLockRegistry(), CmpLockRegistryExclusive(), CmpUnlockRegistry(), CmUnloadKey(), ExFreePool(), FALSE, _CMHIVE::Frozen, _CMHIVE::Hive, HIVE_IS_UNLOADING, _HHIVE::HiveFlags, HvShutdownComplete, _CM_KEY_CONTROL_BLOCK::KeyCell, NT_SUCCESS, NULL, _CM_KEY_CONTROL_BLOCK::RefCount, _CMHIVE::RootKcb, Status, STATUS_CANNOT_DELETE, STATUS_INVALID_PARAMETER, TRUE, and _CMHIVE::UnloadWorkItem.
Referenced by CmpDoQueueLateUnloadWorker().
Variable Documentation
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by CmpLateUnloadHiveWorker().