Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntamd64.h File Reference
ntamd64.h File Reference
Data Structures
struct _DISPATCHER_CONTEXT
struct _DYNAMIC_FUNCTION_TABLE
struct _RUNTIME_FUNCTION
struct _SCOPE_TABLE
union _UNWIND_CODE
struct _UNWIND_HISTORY_TABLE
struct _UNWIND_HISTORY_TABLE_ENTRY
struct _UNWIND_INFO
Macros
#define OUT_OF_PROCESS_FUNCTION_TABLE_CALLBACK_EXPORT_NAME "OutOfProcessFunctionTableCallback"
#define RUNTIME_FUNCTION_INDIRECT 0x1
#define SECTION_ADDITIONAL_INFO_USED 0
#define UNW_FLAG_CHAININFO 0x4
#define UNW_FLAG_EHANDLER 0x1
#define UNW_FLAG_NHANDLER 0x0
#define UNW_FLAG_UHANDLER 0x2
#define UNWIND_HISTORY_TABLE_GLOBAL 1
#define UNWIND_HISTORY_TABLE_LOCAL 2
#define UNWIND_HISTORY_TABLE_NONE 0
#define UNWIND_HISTORY_TABLE_SIZE 12
Typedefs
typedef struct _DISPATCHER_CONTEXT DISPATCHER_CONTEXT
typedef struct _DYNAMIC_FUNCTION_TABLE DYNAMIC_FUNCTION_TABLE
typedef enum _FUNCTION_TABLE_TYPE FUNCTION_TABLE_TYPE
typedef struct _DISPATCHER_CONTEXT * PDISPATCHER_CONTEXT
typedef struct _DYNAMIC_FUNCTION_TABLE * PDYNAMIC_FUNCTION_TABLE
typedef LONG(* PEXCEPTION_FILTER) (struct _EXCEPTION_POINTERS *ExceptionPointers, PVOID EstablisherFrame)
typedef PRUNTIME_FUNCTION(* PGET_RUNTIME_FUNCTION_CALLBACK) (IN ULONG64 ControlPc, IN PVOID Context)
typedef NTSTATUS(* POUT_OF_PROCESS_FUNCTION_TABLE_CALLBACK) (IN HANDLE Process, IN PVOID TableAddress, OUT PULONG Entries, OUT PRUNTIME_FUNCTION *Functions)
typedef struct _RUNTIME_FUNCTION * PRUNTIME_FUNCTION
typedef struct _SCOPE_TABLE * PSCOPE_TABLE
typedef VOID(* PTERMINATION_HANDLER) (BOOLEAN AbnormalTermination, PVOID EstablisherFrame)
typedef union _UNWIND_CODE * PUNWIND_CODE
typedef struct _UNWIND_HISTORY_TABLE * PUNWIND_HISTORY_TABLE
typedef struct _UNWIND_HISTORY_TABLE_ENTRY * PUNWIND_HISTORY_TABLE_ENTRY
typedef struct _UNWIND_INFO * PUNWIND_INFO
typedef enum _UNWIND_OP_CODES * PUNWIND_OP_CODES
typedef struct _RUNTIME_FUNCTION RUNTIME_FUNCTION
typedef struct _SCOPE_TABLE SCOPE_TABLE
typedef union _UNWIND_CODE UNWIND_CODE
typedef struct _UNWIND_HISTORY_TABLE UNWIND_HISTORY_TABLE
typedef struct _UNWIND_HISTORY_TABLE_ENTRY UNWIND_HISTORY_TABLE_ENTRY
typedef struct _UNWIND_INFO UNWIND_INFO
typedef enum _UNWIND_OP_CODES UNWIND_OP_CODES
Enumerations
enum _FUNCTION_TABLE_TYPE { RF_SORTED, RF_UNSORTED, RF_CALLBACK }
enum _UNWIND_OP_CODES {
UWOP_PUSH_NONVOL = 0, UWOP_ALLOC_LARGE, UWOP_ALLOC_SMALL, UWOP_SET_FPREG,
UWOP_SAVE_NONVOL, UWOP_SAVE_NONVOL_FAR, UWOP_SPARE_CODE1, UWOP_SPARE_CODE2,
UWOP_SAVE_XMM128, UWOP_SAVE_XMM128_FAR, UWOP_PUSH_MACHFRAME
}
Functions
NTSYSAPI PLIST_ENTRY RtlGetFunctionTableListHead (VOID)
VOID RtlInitializeHistoryTable (VOID)
NTSYSAPI PRUNTIME_FUNCTION RtlLookupFunctionEntry (IN ULONG64 ControlPc, OUT PULONG64 ImageBase, IN OUT PUNWIND_HISTORY_TABLE HistoryTable OPTIONAL)
NTSYSAPI PRUNTIME_FUNCTION RtlLookupFunctionTable (IN PVOID ControlPc, OUT PVOID *ImageBase, OUT PULONG SizeOfTable)
NTSYSAPI VOID __cdecl RtlRestoreContext (IN PCONTEXT ContextRecord, IN struct _EXCEPTION_RECORD *ExceptionRecord OPTIONAL)
NTSYSAPI PEXCEPTION_ROUTINE RtlVirtualUnwind (IN ULONG HandlerType, IN ULONG64 ImageBase, IN ULONG64 ControlPc, IN PRUNTIME_FUNCTION FunctionEntry, IN OUT PCONTEXT ContextRecord, OUT PVOID *HandlerData, OUT PULONG64 EstablisherFrame, IN OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers OPTIONAL)
Macro Definition Documentation
#define OUT_OF_PROCESS_FUNCTION_TABLE_CALLBACK_EXPORT_NAME "OutOfProcessFunctionTableCallback"
Definition at line 1401 of file ntamd64.h.
#define RUNTIME_FUNCTION_INDIRECT 0x1
Definition at line 1332 of file ntamd64.h.
Referenced by RtlpConvertFunctionEntry().
#define SECTION_ADDITIONAL_INFO_USED 0
Definition at line 1559 of file ntamd64.h.
#define UNW_FLAG_CHAININFO 0x4
Definition at line 1292 of file ntamd64.h.
Referenced by RtlpLookupPrimaryUnwindInfo(), RtlpUnwindPrologue(), and RtlVirtualUnwind().
#define UNW_FLAG_EHANDLER 0x1
Definition at line 1290 of file ntamd64.h.
Referenced by PspGetSetContextInternal(), and RtlDispatchException().
#define UNW_FLAG_NHANDLER 0x0
Definition at line 1289 of file ntamd64.h.
Referenced by RtlGetCallersAddress(), RtlpWalkFrameChain(), RtlRaiseException(), and RtlUnwindEx().
#define UNW_FLAG_UHANDLER 0x2
Definition at line 1291 of file ntamd64.h.
Referenced by RtlUnwindEx().
#define UNWIND_HISTORY_TABLE_GLOBAL 1
Definition at line 1417 of file ntamd64.h.
Referenced by RtlLookupFunctionEntry(), and RtlUnwindEx().
#define UNWIND_HISTORY_TABLE_LOCAL 2
Definition at line 1418 of file ntamd64.h.
Referenced by RtlLookupFunctionEntry().
#define UNWIND_HISTORY_TABLE_NONE 0
Definition at line 1416 of file ntamd64.h.
Referenced by RtlDispatchException(), and RtlLookupFunctionEntry().
#define UNWIND_HISTORY_TABLE_SIZE 12
Definition at line 1409 of file ntamd64.h.
Referenced by RtlLookupFunctionEntry().
Typedef Documentation
typedef struct _DISPATCHER_CONTEXT DISPATCHER_CONTEXT
typedef struct _DYNAMIC_FUNCTION_TABLE DYNAMIC_FUNCTION_TABLE
typedef enum _FUNCTION_TABLE_TYPE FUNCTION_TABLE_TYPE
typedef struct _DISPATCHER_CONTEXT * PDISPATCHER_CONTEXT
typedef struct _DYNAMIC_FUNCTION_TABLE * PDYNAMIC_FUNCTION_TABLE
typedef LONG(* PEXCEPTION_FILTER) (struct _EXCEPTION_POINTERS *ExceptionPointers, PVOID EstablisherFrame)
Definition at line 1543 of file ntamd64.h.
typedef PRUNTIME_FUNCTION(* PGET_RUNTIME_FUNCTION_CALLBACK) (IN ULONG64 ControlPc, IN PVOID Context)
Definition at line 1363 of file ntamd64.h.
typedef NTSTATUS(* POUT_OF_PROCESS_FUNCTION_TABLE_CALLBACK) (IN HANDLE Process, IN PVOID TableAddress, OUT PULONG Entries, OUT PRUNTIME_FUNCTION *Functions)
Definition at line 1394 of file ntamd64.h.
typedef struct _RUNTIME_FUNCTION * PRUNTIME_FUNCTION
typedef struct _SCOPE_TABLE * PSCOPE_TABLE
typedef VOID(* PTERMINATION_HANDLER) (BOOLEAN AbnormalTermination, PVOID EstablisherFrame)
Definition at line 1550 of file ntamd64.h.
typedef union _UNWIND_CODE * PUNWIND_CODE
typedef struct _UNWIND_HISTORY_TABLE * PUNWIND_HISTORY_TABLE
typedef struct _UNWIND_HISTORY_TABLE_ENTRY * PUNWIND_HISTORY_TABLE_ENTRY
typedef struct _UNWIND_INFO * PUNWIND_INFO
typedef enum _UNWIND_OP_CODES * PUNWIND_OP_CODES
typedef struct _RUNTIME_FUNCTION RUNTIME_FUNCTION
typedef struct _SCOPE_TABLE SCOPE_TABLE
typedef union _UNWIND_CODE UNWIND_CODE
typedef struct _UNWIND_HISTORY_TABLE UNWIND_HISTORY_TABLE
typedef struct _UNWIND_HISTORY_TABLE_ENTRY UNWIND_HISTORY_TABLE_ENTRY
typedef struct _UNWIND_INFO UNWIND_INFO
typedef enum _UNWIND_OP_CODES UNWIND_OP_CODES
Enumeration Type Documentation
enum _FUNCTION_TABLE_TYPE
Enumerator
RF_SORTED
RF_UNSORTED
RF_CALLBACK
Definition at line 1370 of file ntamd64.h.
enum _UNWIND_OP_CODES
Enumerator
UWOP_PUSH_NONVOL
UWOP_ALLOC_LARGE
UWOP_ALLOC_SMALL
UWOP_SET_FPREG
UWOP_SAVE_NONVOL
UWOP_SAVE_NONVOL_FAR
UWOP_SPARE_CODE1
UWOP_SPARE_CODE2
UWOP_SAVE_XMM128
UWOP_SAVE_XMM128_FAR
UWOP_PUSH_MACHFRAME
Definition at line 1257 of file ntamd64.h.
Function Documentation
NTSYSAPI PLIST_ENTRY RtlGetFunctionTableListHead (VOID)
VOID RtlInitializeHistoryTable (VOID)
Referenced by KiInitializeKernel().
NTSYSAPI PRUNTIME_FUNCTION RtlLookupFunctionEntry (IN ULONG64 ControlPc, OUT PULONG64 ImageBase, IN OUT PUNWIND_HISTORY_TABLE HistoryTable OPTIONAL)
Definition at line 1837 of file exdsptch.c.
References ARGUMENT_PRESENT, _RUNTIME_FUNCTION::BeginAddress, _RUNTIME_FUNCTION::EndAddress, Index, NULL, RtlLookupFunctionTable(), RtlpConvertFunctionEntry(), UNWIND_HISTORY_TABLE_GLOBAL, UNWIND_HISTORY_TABLE_LOCAL, UNWIND_HISTORY_TABLE_NONE, and UNWIND_HISTORY_TABLE_SIZE.
Referenced by PspGetSetContextInternal(), RtlDispatchException(), RtlpSameFunction(), RtlRaiseException(), and RtlUnwindEx().
NTSYSAPI PRUNTIME_FUNCTION RtlLookupFunctionTable (IN PVOID ControlPc, OUT PVOID * ImageBase, OUT PULONG SizeOfTable)
Definition at line 312 of file lookup.c.
Referenced by RtlIsValidHandler(), RtlLookupFunctionEntry(), and RtlpLookupFunctionEntryForStackWalks().
NTSYSAPI VOID __cdecl RtlRestoreContext (IN PCONTEXT ContextRecord, IN struct _EXCEPTION_RECORD *ExceptionRecord OPTIONAL)
Referenced by RtlUnwindEx().
NTSYSAPI PEXCEPTION_ROUTINE RtlVirtualUnwind (IN ULONG HandlerType, IN ULONG64 ImageBase, IN ULONG64 ControlPc, IN PRUNTIME_FUNCTION FunctionEntry, IN OUT PCONTEXT ContextRecord, OUT PVOID * HandlerData, OUT PULONG64 EstablisherFrame, IN OUT PKNONVOLATILE_CONTEXT_POINTERS ContextPointers OPTIONAL)
Definition at line 1203 of file exdsptch.c.
References ADD_IMM32_OP, ADD_IMM8_OP, ARGUMENT_PRESENT, _RUNTIME_FUNCTION::BeginAddress, _UNWIND_CODE::CodeOffset, _UNWIND_INFO::CountOfCodes, FALSE, _UNWIND_INFO::Flags, _UNWIND_INFO::FrameOffset, _UNWIND_INFO::FrameRegister, Index, IS_REX_PREFIX, JMP_IMM32_OP, JMP_IMM8_OP, JMP_IND_OP, LEA_OP, NULL, POP_OP, REP_PREFIX, RET_OP, RET_OP_2, RtlpSameFunction(), RtlpUnwindPrologue(), SIZE64_PREFIX, _UNWIND_INFO::SizeOfProlog, TRUE, UNALIGNED, UNW_FLAG_CHAININFO, _UNWIND_INFO::UnwindCode, _UNWIND_CODE::UnwindOp, and UWOP_SET_FPREG.
Referenced by PspGetSetContextInternal(), RtlDispatchException(), RtlGetCallersAddress(), RtlpWalkFrameChain(), RtlRaiseException(), and RtlUnwindEx().