Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psjob.c File Reference
psjob.c File Reference
#include "psp.h"
#include "winerror.h"
Macros
#define PSP_JOB_TIME_LIMITS_TIME -7
#define PSP_ONE_SECOND (10 * (1000*1000))
Functions
NTSTATUS NTAPI NtAssignProcessToJobObject (__in HANDLE JobHandle, __in HANDLE ProcessHandle)
NTSTATUS NTAPI NtCreateJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtCreateJobSet (__in ULONG NumJob, __in_ecount(NumJob) PJOB_SET_ARRAY UserJobSet, __in ULONG Flags)
NTSTATUS NtIsProcessInJob (__in HANDLE ProcessHandle, __in_opt HANDLE JobHandle)
NTSTATUS NTAPI NtOpenJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQueryInformationJobObject (__in_opt HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __out_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtSetInformationJobObject (__in HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __in_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength)
NTSTATUS NtTerminateJobObject (__in HANDLE JobHandle, __in NTSTATUS ExitStatus)
BOOLEAN PsChangeJobMemoryUsage (IN ULONG Flags, IN SSIZE_T Amount)
VOID PsEnforceExecutionTimeLimits (VOID)
NTSTATUS PspAddProcessToJob (PEJOB Job, PEPROCESS Process)
VOID PspApplyJobLimitsToProcess (PEJOB Job, PEPROCESS Process)
VOID PspApplyJobLimitsToProcessSet (PEJOB Job)
NTSTATUS PspCaptureTokenFilter (KPROCESSOR_MODE PreviousMode, PJOBOBJECT_SECURITY_LIMIT_INFORMATION SecurityLimitInfo, PPS_JOB_TOKEN_FILTER *TokenFilter)
VOID PspExitProcessFromJob (PEJOB Job, PEPROCESS Process)
VOID PspFoldProcessAccountingIntoJob (PEJOB Job, PEPROCESS Process)
NTSTATUS PspGetJobFromSet (IN PEJOB ParentJob, IN ULONG JobMemberLevel, OUT PEJOB *pJob)
VOID PspInitializeJobStructures ()
VOID PspInitializeJobStructuresPhase1 ()
VOID PspJobClose (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID PspJobDelete (IN PVOID Object)
VOID PspJobTimeLimitsDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID PspJobTimeLimitsWork (IN PVOID Context)
VOID PspRemoveProcessFromJob (PEJOB Job, PEPROCESS Process)
VOID PspShutdownJobLimits (VOID)
BOOLEAN PspTerminateAllProcessesInJob (PEJOB Job, NTSTATUS Status, BOOLEAN IncCounter)
NTSTATUS PspWin32SessionCallout (IN PKWIN32_JOB_CALLOUT CalloutRoutine, IN PKWIN32_JOBCALLOUT_PARAMETERS Parameters, IN ULONG SessionId)
VOID PsReportProcessMemoryLimitViolation (VOID)
Variables
POBJECT_TYPE IoCompletionObjectType
const ULONG PspJobInfoAlign []
const ULONG PspJobInfoLengths []
KDPC PspJobTimeLimitsDpc
LARGE_INTEGER PspJobTimeLimitsInterval = {0}
KGUARDED_MUTEX PspJobTimeLimitsLock
BOOLEAN PspJobTimeLimitsShuttingDown
KTIMER PspJobTimeLimitsTimer
WORK_QUEUE_ITEM PspJobTimeLimitsWorkItem
Macro Definition Documentation
#define PSP_JOB_TIME_LIMITS_TIME -7
Definition at line 60 of file psjob.c.
Referenced by PspInitializeJobStructures().
#define PSP_ONE_SECOND (10 * (1000*1000))
Definition at line 59 of file psjob.c.
Referenced by PspInitializeJobStructures().
Function Documentation
NTSTATUS NTAPI NtAssignProcessToJobObject (__in HANDLE JobHandle, __in HANDLE ProcessHandle)
Definition at line 267 of file psjob.c.
References ASSERT, _WIN32_JOBCALLOUT_PARAMETERS::CalloutType, _WIN32_JOBCALLOUT_PARAMETERS::Data, ERROR_NOT_ENOUGH_QUOTA, ExAcquireResourceExclusiveLite(), ExAcquireRundownProtection(), ExReleaseResourceLite(), ExReleaseRundownProtection(), FALSE, InterlockedCompareExchangePointer, _EPROCESS::Job, _WIN32_JOBCALLOUT_PARAMETERS::Job, JOB_OBJECT_ASSIGN_PROCESS, JOB_OBJECT_SECURITY_NO_ADMIN, JOB_OBJECT_UILIMIT_NONE, _EJOB::JobLock, KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), MmGetSessionId(), NT_SUCCESS, NULL, ObDereferenceObject(), ObDereferenceObjectEx(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_INFORMATION, PROCESS_SET_QUOTA, PROCESS_TERMINATE, PsDereferencePrimaryTokenEx, PsGetCurrentThread(), PsJobType, PspAddProcessToJob(), PsProcessType, PspSetPrimaryToken(), PspTerminateProcess(), PspW32JobCallout, PspWin32SessionCallout(), PsReferencePrimaryToken(), PsW32JobCalloutAddProcess, _EPROCESS::RundownProtect, _EJOB::SecurityLimitFlags, _EJOB::SessionId, SeSubProcessToken(), SeTokenIsAdmin(), Status, STATUS_ACCESS_DENIED, STATUS_PROCESS_IS_TERMINATING, _ETHREAD::Tcb, _EJOB::Token, _EJOB::TotalTerminatedProcesses, TRUE, _EJOB::UIRestrictionsClass, and _EPROCESS::Win32Process.
NTSTATUS NTAPI NtCreateJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 73 of file psjob.c.
References _EJOB::Event, except, ExInitializeResourceLite(), ExSystemExceptionFilter(), FALSE, Handle, InitializeListHead(), InsertTailList(), _EJOB::JobLinks, _EJOB::JobLock, _EJOB::JobSetLinks, KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, MmGetSessionId(), NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), PAGED_CODE, ProbeForWriteHandle, _EJOB::ProcessListHead, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsJobType, PSP_DEFAULT_SCHEDULING_CLASSES, PspInitializeJobLimitsLock(), PspJobList, PspLockJobListExclusive(), PspUnlockJobListExclusive(), RtlZeroMemory, _EJOB::SchedulingClass, _EJOB::SessionId, Status, and _ETHREAD::Tcb.
NTSTATUS NtCreateJobSet (__in ULONG NumJob, __in_ecount(NumJob) PJOB_SET_ARRAY UserJobSet, __in ULONG Flags)
Definition at line 3260 of file psjob.c.
References CONTAINING_RECORD, ExAllocatePoolWithQuotaTag, except, ExFreePool(), ExSystemExceptionFilter(), InitializeListHead(), InsertTailList(), IsListEmpty, JOB_OBJECT_QUERY, _JOB_SET_ARRAY::JobHandle, _EJOB::JobSetLinks, KeGetPreviousModeByThread, MAXULONG_PTR, _JOB_SET_ARRAY::MemberLevel, _EJOB::MemberLevel, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, ProbeForRead, PsGetCurrentThread(), PsJobType, PspLockJobListExclusive(), PspUnlockJobListExclusive(), RemoveHeadList(), RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TYPE_ALIGNMENT, and UserMode.
NTSTATUS NtIsProcessInJob (__in HANDLE ProcessHandle, __in_opt HANDLE JobHandle)
Definition at line 3117 of file psjob.c.
References _EPROCESS::Job, JOB_OBJECT_QUERY, KeGetPreviousModeByThread, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PROCESS_QUERY_INFORMATION, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsJobType, PsProcessType, Status, STATUS_PROCESS_IN_JOB, STATUS_PROCESS_NOT_IN_JOB, and _ETHREAD::Tcb.
NTSTATUS NTAPI NtOpenJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 191 of file psjob.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObOpenObjectByName(), PAGED_CODE, ProbeForWriteHandle, PsJobType, and Status.
NTSTATUS NtQueryInformationJobObject (__in_opt HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __out_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength, __out_opt PULONG ReturnLength)
Definition at line 904 of file psjob.c.
References _EJOB::ActiveProcesses, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::ActiveProcesses, _EJOB::ActiveProcessLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::ActiveProcessLimit, _EJOB::Affinity, _JOBOBJECT_BASIC_LIMIT_INFORMATION::Affinity, ARGUMENT_PRESENT, _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION::BasicInfo, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::BasicLimitInformation, _PS_JOB_TOKEN_FILTER::CapturedGroupCount, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedGroupsLength, _PS_JOB_TOKEN_FILTER::CapturedPrivilegeCount, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedPrivilegesLength, _PS_JOB_TOKEN_FILTER::CapturedSidCount, _PS_JOB_TOKEN_FILTER::CapturedSids, _PS_JOB_TOKEN_FILTER::CapturedSidsLength, CONTAINING_RECORD, _EJOB::EndOfJobTimeAction, _JOBOBJECT_END_OF_JOB_TIME_INFORMATION::EndOfJobTimeAction, ExAcquireResourceSharedLite(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), ExSystemExceptionFilter(), FALSE, FIELD_OFFSET, _EJOB::Filter, _LIST_ENTRY::Flink, _TOKEN_GROUPS::GroupCount, _TOKEN_GROUPS::Groups, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::IoInfo, _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION::IoInfo, _EPROCESS::Job, JOB_OBJECT_QUERY, _EJOB::JobLock, _EJOB::JobMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::JobMemoryLimit, JobObjectBasicAccountingInformation, JobObjectBasicAndIoAccountingInformation, JobObjectBasicLimitInformation, JobObjectBasicProcessIdList, JobObjectBasicUIRestrictions, JobObjectEndOfJobTimeInformation, JobObjectExtendedLimitInformation, JobObjectJobSetInformation, JobObjectSecurityLimitInformation, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), KeQueryValuesProcess(), KernelMode, _KPROCESS_VALUES::KernelTime, leave, _EJOB::LimitFlags, _JOBOBJECT_BASIC_LIMIT_INFORMATION::LimitFlags, _EJOB::MaximumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MaximumWorkingSetSize, MaxJobObjectInfoClass, _EJOB::MemberLevel, _JOBOBJECT_JOBSET_INFORMATION::MemberLevel, _EJOB::MinimumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MinimumWorkingSetSize, NT_SUCCESS, NULL, _JOBOBJECT_BASIC_PROCESS_ID_LIST::NumberOfAssignedProcesses, _JOBOBJECT_BASIC_PROCESS_ID_LIST::NumberOfProcessIdsInList, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, _IO_COUNTERS::OtherOperationCount, _EJOB::OtherOperationCount, _KPROCESS_VALUES::OtherOperationCount, _IO_COUNTERS::OtherTransferCount, _EJOB::OtherTransferCount, _KPROCESS_VALUES::OtherTransferCount, PAGE_SHIFT, PAGED_CODE, _MMSUPPORT::PageFaultCount, _EPROCESS::Pcb, _EJOB::PeakJobMemoryUsed, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::PeakJobMemoryUsed, _EJOB::PeakProcessMemoryUsed, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::PeakProcessMemoryUsed, _EJOB::PerJobUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerJobUserTimeLimit, _EJOB::PerProcessUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerProcessUserTimeLimit, _EJOB::PriorityClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PriorityClass, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::PrivilegesToDelete, ProbeForRead, ProbeForWriteUlong, _JOBOBJECT_BASIC_PROCESS_ID_LIST::ProcessIdList, _EJOB::ProcessListHead, _EJOB::ProcessMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::ProcessMemoryLimit, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsJobType, PspJobInfoAlign, PspJobInfoLengths, PspLockJobLimitsSharedUnsafe(), PspLockJobListShared(), PspUnlockJobLimitsSharedUnsafe(), PspUnlockJobListShared(), _LARGE_INTEGER::QuadPart, _IO_COUNTERS::ReadOperationCount, _EJOB::ReadOperationCount, _KPROCESS_VALUES::ReadOperationCount, _IO_COUNTERS::ReadTransferCount, _EJOB::ReadTransferCount, _KPROCESS_VALUES::ReadTransferCount, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::RestrictedSids, RtlCopyMemory, RtlCopySidAndAttributesArray(), RtlZeroMemory, _EJOB::SchedulingClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::SchedulingClass, _EJOB::SecurityLimitFlags, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SecurityLimitFlags, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SidsToDisable, STATUS_ACCESS_DENIED, STATUS_BUFFER_OVERFLOW, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::ThisPeriodTotalKernelTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::ThisPeriodTotalKernelTime, _EJOB::ThisPeriodTotalUserTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::ThisPeriodTotalUserTime, _EJOB::TotalKernelTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalKernelTime, _EJOB::TotalPageFaultCount, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalPageFaultCount, _EJOB::TotalProcesses, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalProcesses, _EJOB::TotalTerminatedProcesses, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalTerminatedProcesses, _EJOB::TotalUserTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalUserTime, TRUE, _EJOB::UIRestrictionsClass, _JOBOBJECT_BASIC_UI_RESTRICTIONS::UIRestrictionsClass, _EPROCESS::UniqueProcessId, _KPROCESS_VALUES::UserTime, _EPROCESS::Vm, _IO_COUNTERS::WriteOperationCount, _EJOB::WriteOperationCount, _KPROCESS_VALUES::WriteOperationCount, _IO_COUNTERS::WriteTransferCount, _EJOB::WriteTransferCount, and _KPROCESS_VALUES::WriteTransferCount.
NTSTATUS NtSetInformationJobObject (__in HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __in_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength)
Definition at line 1444 of file psjob.c.
References _EJOB::ActiveProcessLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::ActiveProcessLimit, _EJOB::Affinity, _JOBOBJECT_BASIC_LIMIT_INFORMATION::Affinity, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::BasicLimitInformation, _WIN32_JOBCALLOUT_PARAMETERS::CalloutType, _EJOB::CompletionKey, _JOBOBJECT_ASSOCIATE_COMPLETION_PORT::CompletionKey, _EJOB::CompletionPort, _JOBOBJECT_ASSOCIATE_COMPLETION_PORT::CompletionPort, CONTAINING_RECORD, _WIN32_JOBCALLOUT_PARAMETERS::Data, _EJOB::EndOfJobTimeAction, _JOBOBJECT_END_OF_JOB_TIME_INFORMATION::EndOfJobTimeAction, _EJOB::Event, ExAcquireResourceExclusiveLite(), except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExReleaseResourceLite(), FALSE, _EJOB::Filter, _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IO_COMPLETION_MODIFY_STATE, IoSetIoCompletion(), IsListEmpty, _WIN32_JOBCALLOUT_PARAMETERS::Job, JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS, JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS, JOB_OBJECT_LIMIT_ACTIVE_PROCESS, JOB_OBJECT_LIMIT_AFFINITY, JOB_OBJECT_LIMIT_BREAKAWAY_OK, JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION, JOB_OBJECT_LIMIT_JOB_MEMORY, JOB_OBJECT_LIMIT_JOB_TIME, JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME, JOB_OBJECT_LIMIT_PRIORITY_CLASS, JOB_OBJECT_LIMIT_PROCESS_MEMORY, JOB_OBJECT_LIMIT_PROCESS_TIME, JOB_OBJECT_LIMIT_SCHEDULING_CLASS, JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, JOB_OBJECT_LIMIT_WORKINGSET, JOB_OBJECT_MSG_NEW_PROCESS, JOB_OBJECT_POST_AT_END_OF_JOB, JOB_OBJECT_SECURITY_FILTER_TOKENS, JOB_OBJECT_SECURITY_NO_ADMIN, JOB_OBJECT_SECURITY_ONLY_TOKEN, JOB_OBJECT_SECURITY_RESTRICTED_TOKEN, JOB_OBJECT_SECURITY_VALID_FLAGS, JOB_OBJECT_SET_ATTRIBUTES, JOB_OBJECT_SET_SECURITY_ATTRIBUTES, JOB_OBJECT_UI_VALID_FLAGS, _EJOB::JobFlags, _EJOB::JobLock, _EJOB::JobMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::JobMemoryLimit, JobObjectAssociateCompletionPortInformation, JobObjectBasicLimitInformation, JobObjectBasicUIRestrictions, JobObjectEndOfJobTimeInformation, JobObjectExtendedLimitInformation, JobObjectSecurityLimitInformation, _EPROCESS::JobStatus, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::JobToken, KeActiveProcessors, KeClearEvent(), KeEnterGuardedRegionThread(), KeGetPreviousModeByThread, KeLeaveGuardedRegionThread(), KeMaximumIncrement, KeMemoryBarrier(), KeQueryRuntimeProcess(), KeReadStateProcess(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), _EJOB::LimitFlags, _JOBOBJECT_BASIC_LIMIT_INFORMATION::LimitFlags, _JOB_WORKING_SET_CHANGE_HEAD::Links, _JOB_WORKING_SET_CHANGE_HEAD::MaximumWorkingSetSize, _EJOB::MaximumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MaximumWorkingSetSize, MaxJobObjectInfoClass, _JOB_WORKING_SET_CHANGE_HEAD::MinimumWorkingSetSize, _EJOB::MinimumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MinimumWorkingSetSize, MmAdjustWorkingSetSize(), MmEnforceWorkingSetLimit(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _EPROCESS::Pcb, _EJOB::PerJobUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerJobUserTimeLimit, _EJOB::PerProcessUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerProcessUserTimeLimit, _EJOB::PriorityClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PriorityClass, ProbeForRead, _JOB_WORKING_SET_CHANGE_RECORD::Process, PROCESS_PRIORITY_CLASS_ABOVE_NORMAL, PROCESS_PRIORITY_CLASS_HIGH, PROCESS_PRIORITY_CLASS_REALTIME, _EJOB::ProcessListHead, _EJOB::ProcessMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::ProcessMemoryLimit, PS_JOB_FLAGS_CLOSE_DONE, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_CLEAR_BITS, PsGetCurrentThread(), PsJobType, PsMinimumWorkingSet, PSP_DEFAULT_SCHEDULING_CLASSES, PSP_NUMBER_OF_SCHEDULING_CLASSES, PspApplyJobLimitsToProcessSet(), PspCaptureTokenFilter(), PspFoldProcessAccountingIntoJob(), PspJobInfoAlign, PspJobInfoLengths, PspLockJobLimitsExclusiveUnsafe(), PspLockWorkingSetChangeExclusiveUnsafe(), PspUnlockJobLimitsExclusiveUnsafe(), PspUnlockWorkingSetChangeExclusiveUnsafe(), PspW32JobCallout, PspWin32SessionCallout(), PspWorkingSetChangeHead, PsW32JobCalloutSetInformation, _LARGE_INTEGER::QuadPart, RemoveHeadList(), RtlCopyMemory, _EJOB::SchedulingClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::SchedulingClass, SeAssignPrimaryTokenPrivilege, SeCheckPrivilegedObject(), _EJOB::SecurityLimitFlags, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SecurityLimitFlags, SeIncreaseBasePriorityPrivilege, SeIsChildTokenByPointer(), SeSinglePrivilegeCheck(), _EJOB::SessionId, SeTokenIsAdmin(), SeTokenObjectType, SeTokenType(), STATUS_BAD_TOKEN_TYPE, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::ThisPeriodTotalKernelTime, _EJOB::ThisPeriodTotalUserTime, _EJOB::Token, TOKEN_ASSIGN_PRIMARY, TOKEN_DUPLICATE, TOKEN_IMPERSONATE, TokenPrimary, TRUE, UInt32x32To64, _EJOB::UIRestrictionsClass, _JOBOBJECT_BASIC_UI_RESTRICTIONS::UIRestrictionsClass, ULongToPtr, and _EPROCESS::UniqueProcessId.
NTSTATUS NtTerminateJobObject (__in HANDLE JobHandle, __in NTSTATUS ExitStatus)
Definition at line 2412 of file psjob.c.
References FALSE, JOB_OBJECT_TERMINATE, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PsJobType, PspTerminateAllProcessesInJob(), and _ETHREAD::Tcb.
BOOLEAN PsChangeJobMemoryUsage (IN ULONG Flags, IN SSIZE_T Amount)
Definition at line 2863 of file psjob.c.
References _EPROCESS::CommitCharge, _EJOB::CompletionKey, _EJOB::CompletionPort, _EJOB::CurrentJobMemoryUsed, FALSE, IoSetIoCompletion(), _EPROCESS::Job, JOB_OBJECT_LIMIT_JOB_MEMORY, JOB_OBJECT_MSG_JOB_MEMORY_LIMIT, _EJOB::JobMemoryLimit, _EPROCESS::JobStatus, _EJOB::LimitFlags, _EJOB::PeakJobMemoryUsed, _EJOB::PeakProcessMemoryUsed, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspLockJobLimitsShared(), PspUnlockJobLimitsShared(), STATUS_SUCCESS, TRUE, and _EPROCESS::UniqueProcessId.
Referenced by MiAllocateLargePages(), MiCleanPhysicalProcessPages(), MiInsertVadCharges(), MiReleasePhysicalCharges(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MiSetPageModified(), MiSetProtectionOnSection(), MmAssignProcessToJob(), MmCleanProcessAddressSpace(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFreeUserPhysicalPages(), and NtFreeVirtualMemory().
VOID PsEnforceExecutionTimeLimits (VOID)
Definition at line 2445 of file psjob.c.
References _EJOB::ActiveProcesses, _EJOB::CompletionKey, _EJOB::CompletionPort, _EJOB::EndOfJobTimeAction, ERROR_NOT_ENOUGH_QUOTA, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, IoSetIoCompletion(), JOB_OBJECT_LIMIT_JOB_TIME, JOB_OBJECT_LIMIT_PROCESS_TIME, JOB_OBJECT_MSG_END_OF_JOB_TIME, JOB_OBJECT_MSG_END_OF_PROCESS_TIME, JOB_OBJECT_POST_AT_END_OF_JOB, JOB_OBJECT_TERMINATE_AT_END_OF_JOB, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeMaximumIncrement, KeQueryRuntimeProcess(), _EJOB::LimitFlags, NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, _EJOB::PerJobUserTimeLimit, _EJOB::PerProcessUserTimeLimit, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_CLEAR_BITS, PsGetCurrentThread(), PsGetNextJob(), PsGetNextJobProcess(), PspFoldProcessAccountingIntoJob(), PspTerminateAllProcessesInJob(), PspTerminateProcess(), _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::ThisPeriodTotalUserTime, _EJOB::TotalTerminatedProcesses, TRUE, UInt32x32To64, and _EPROCESS::UniqueProcessId.
Referenced by PspJobTimeLimitsWork().
NTSTATUS PspAddProcessToJob (PEJOB Job, PEPROCESS Process)
Definition at line 457 of file psjob.c.
References _EJOB::ActiveProcesses, _EJOB::ActiveProcessLimit, _EJOB::CompletionKey, _EJOB::CompletionPort, _EJOB::Event, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, InsertTailList(), IoSetIoCompletion(), JOB_OBJECT_LIMIT_ACTIVE_PROCESS, JOB_OBJECT_LIMIT_JOB_TIME, JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, JOB_OBJECT_LIMIT_WORKINGSET, JOB_OBJECT_MSG_ACTIVE_PROCESS_LIMIT, JOB_OBJECT_MSG_NEW_PROCESS, _EJOB::JobFlags, _EPROCESS::JobLinks, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), KeReadStateEvent(), KeStackAttachProcess(), KeUnstackDetachProcess(), _EJOB::LimitFlags, _EJOB::MaximumWorkingSetSize, _EJOB::MinimumWorkingSetSize, MmAdjustWorkingSetSize(), MmAssignProcessToJob(), MmEnforceWorkingSetLimit(), NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, _EJOB::ProcessListHead, PS_JOB_FLAGS_CLOSE_DONE, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PS_SET_CLEAR_BITS, PS_TEST_ALL_BITS_SET, PsGetCurrentThread(), PspApplyJobLimitsToProcess(), PspLockWorkingSetChangeExclusiveUnsafe(), PspUnlockWorkingSetChangeExclusiveUnsafe(), Status, STATUS_INVALID_PARAMETER, STATUS_QUOTA_EXCEEDED, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::TotalProcesses, TRUE, and _EPROCESS::UniqueProcessId.
Referenced by NtAssignProcessToJobObject(), and PspCreateProcess().
VOID PspApplyJobLimitsToProcess (PEJOB Job, PEPROCESS Process)
Definition at line 2340 of file psjob.c.
References _EJOB::Affinity, _EPROCESS::CommitChargeLimit, FALSE, _MMSUPPORT::Flags, JOB_OBJECT_LIMIT_AFFINITY, JOB_OBJECT_LIMIT_PRIORITY_CLASS, JOB_OBJECT_LIMIT_PROCESS_MEMORY, JOB_OBJECT_LIMIT_WORKINGSET, KeSetAffinityProcess(), KeSetDisableQuantumProcess(), KeSetQuantumProcess(), _EJOB::LimitFlags, MEMORY_PRIORITY_FOREGROUND, _MMSUPPORT_FLAGS::MemoryPriority, MmEnforceWorkingSetLimit(), PAGED_CODE, _EPROCESS::Pcb, _EPROCESS::PriorityClass, _EJOB::PriorityClass, PROCESS_PRIORITY_CLASS_IDLE, _EJOB::ProcessMemoryLimit, PsGetCurrentThread(), PSP_NUMBER_OF_SCHEDULING_CLASSES, PspJobSchedulingClasses, PspLockJobLimitsShared(), PspLockProcessExclusive(), PsProcessPriorityBackground, PsProcessPriorityForeground, PspUnlockJobLimitsShared(), PspUnlockProcessExclusive(), PspUseJobSchedulingClasses, PsSetProcessPriorityByClass(), _EJOB::SchedulingClass, TRUE, and _EPROCESS::Vm.
Referenced by PspAddProcessToJob(), and PspApplyJobLimitsToProcessSet().
VOID PspApplyJobLimitsToProcessSet (PEJOB Job)
Definition at line 2306 of file psjob.c.
References ExAllocatePoolWithTag, InsertTailList(), JOB_OBJECT_LIMIT_WORKINGSET, _EPROCESS::JobStatus, _EJOB::LimitFlags, _JOB_WORKING_SET_CHANGE_HEAD::Links, _JOB_WORKING_SET_CHANGE_RECORD::Links, NULL, ObReferenceObject, PAGED_CODE, PagedPool, _JOB_WORKING_SET_CHANGE_RECORD::Process, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PspApplyJobLimitsToProcess(), PspGetNextJobProcess(), and PspWorkingSetChangeHead.
Referenced by NtSetInformationJobObject().
NTSTATUS PspCaptureTokenFilter (KPROCESSOR_MODE PreviousMode, PJOBOBJECT_SECURITY_LIMIT_INFORMATION SecurityLimitInfo, PPS_JOB_TOKEN_FILTER * TokenFilter)
Definition at line 2730 of file psjob.c.
References ARGUMENT_PRESENT, _PS_JOB_TOKEN_FILTER::CapturedGroupCount, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedGroupsLength, _PS_JOB_TOKEN_FILTER::CapturedPrivilegeCount, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedPrivilegesLength, _PS_JOB_TOKEN_FILTER::CapturedSidCount, _PS_JOB_TOKEN_FILTER::CapturedSids, _PS_JOB_TOKEN_FILTER::CapturedSidsLength, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _TOKEN_GROUPS::GroupCount, _TOKEN_GROUPS::Groups, NonPagedPool, NT_SUCCESS, NULL, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::PrivilegesToDelete, ProbeForReadSmallStructure, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::RestrictedSids, RtlZeroMemory, SeCaptureLuidAndAttributesArray(), SeCaptureSidAndAttributesArray(), _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SidsToDisable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationJobObject().
VOID PspExitProcessFromJob (PEJOB Job, PEPROCESS Process)
Definition at line 650 of file psjob.c.
References _EJOB::ActiveProcesses, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), PAGED_CODE, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PsGetCurrentThread(), PspFoldProcessAccountingIntoJob(), _ETHREAD::Tcb, and TRUE.
Referenced by PspExitThread().
VOID PspFoldProcessAccountingIntoJob (PEJOB Job, PEPROCESS Process)
Definition at line 2681 of file psjob.c.
References _EJOB::ActiveProcesses, _EPROCESS::CommitChargePeak, _EJOB::CompletionKey, _EJOB::CompletionPort, FALSE, IoSetIoCompletion(), JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO, _EPROCESS::JobStatus, KeQueryValuesProcess(), _KPROCESS_VALUES::KernelTime, NULL, _EJOB::OtherOperationCount, _KPROCESS_VALUES::OtherOperationCount, _EJOB::OtherTransferCount, _KPROCESS_VALUES::OtherTransferCount, _MMSUPPORT::PageFaultCount, _EPROCESS::Pcb, _EJOB::PeakProcessMemoryUsed, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_SET_CLEAR_BITS, _LARGE_INTEGER::QuadPart, _EJOB::ReadOperationCount, _KPROCESS_VALUES::ReadOperationCount, _EJOB::ReadTransferCount, _KPROCESS_VALUES::ReadTransferCount, STATUS_SUCCESS, _EJOB::ThisPeriodTotalKernelTime, _EJOB::ThisPeriodTotalUserTime, _EJOB::TotalKernelTime, _EJOB::TotalPageFaultCount, _EJOB::TotalUserTime, _KPROCESS_VALUES::UserTime, _EPROCESS::Vm, _EJOB::WriteOperationCount, _KPROCESS_VALUES::WriteOperationCount, _EJOB::WriteTransferCount, and _KPROCESS_VALUES::WriteTransferCount.
Referenced by NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), PspExitProcessFromJob(), PspRemoveProcessFromJob(), and PspTerminateAllProcessesInJob().
NTSTATUS PspGetJobFromSet (IN PEJOB ParentJob, IN ULONG JobMemberLevel, OUT PEJOB * pJob)
Definition at line 3195 of file psjob.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, _EJOB::MemberLevel, ObReferenceObject, ObReferenceObjectSafe(), PsGetCurrentThread(), PspLockJobListShared(), PspUnlockJobListShared(), Status, STATUS_ACCESS_DENIED, and STATUS_SUCCESS.
Referenced by PspCreateProcess().
VOID PspInitializeJobStructures ()
Definition at line 3049 of file psjob.c.
References ExInitializeWorkItem, FALSE, InitializeListHead(), Int32x32To64, KeInitializeDpc(), KeInitializeTimer(), NULL, PSP_JOB_TIME_LIMITS_TIME, PSP_ONE_SECOND, PspInitializeJobListLock(), PspInitializeJobTimeLimitsLock(), PspJobList, PspJobTimeLimitsDpcRoutine(), PspJobTimeLimitsShuttingDown, PspJobTimeLimitsWork(), and _LARGE_INTEGER::QuadPart.
Referenced by PspInitPhase0().
VOID PspInitializeJobStructuresPhase1 ()
Definition at line 3081 of file psjob.c.
References KeSetTimer().
Referenced by PspInitPhase1().
VOID PspJobClose (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 780 of file psjob.c.
References _EJOB::CompletionPort, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, _EJOB::JobFlags, _EJOB::JobLock, KeEnterGuardedRegionThread(), KeLeaveGuardedRegionThread(), _EJOB::LimitFlags, NULL, ObDereferenceObject(), PAGED_CODE, PS_JOB_FLAGS_CLOSE_DONE, PS_SET_BITS, PsGetCurrentThread(), PspLockJobLimitsExclusiveUnsafe(), PspTerminateAllProcessesInJob(), PspUnlockJobLimitsExclusiveUnsafe(), STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and UNREFERENCED_PARAMETER.
Referenced by PspInitPhase0().
VOID PspJobDelete (IN PVOID Object)
Definition at line 681 of file psjob.c.
References _WIN32_JOBCALLOUT_PARAMETERS::CalloutType, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedSids, _EJOB::CompletionPort, CONTAINING_RECORD, _WIN32_JOBCALLOUT_PARAMETERS::Data, ExAcquireResourceExclusiveLite(), ExDeleteResourceLite(), ExFreePool(), ExReleaseResourceLite(), _EJOB::Filter, _LIST_ENTRY::Flink, IsListEmpty, _WIN32_JOBCALLOUT_PARAMETERS::Job, _EJOB::JobLinks, _EJOB::JobLock, _EJOB::JobSetLinks, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _EJOB::LimitFlags, NULL, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), PAGED_CODE, PsGetCurrentThread(), PspLockJobListExclusive(), PspUnlockJobListExclusive(), PspW32JobCallout, PspWin32SessionCallout(), PsW32JobCalloutTerminate, RemoveEntryList(), _EJOB::SessionId, _ETHREAD::Tcb, _EJOB::Token, and TRUE.
Referenced by PspInitPhase0().
VOID PspJobTimeLimitsDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 3034 of file psjob.c.
References DelayedWorkQueue, ExQueueWorkItem(), and UNREFERENCED_PARAMETER.
Referenced by PspInitializeJobStructures().
VOID PspJobTimeLimitsWork (IN PVOID Context)
Definition at line 3003 of file psjob.c.
References KeSetTimer(), PAGED_CODE, PsEnforceExecutionTimeLimits(), PsGetCurrentThread(), PspJobTimeLimitsShuttingDown, PspLockJobTimeLimitsShared(), PspUnlockJobTimeLimitsShared(), and UNREFERENCED_PARAMETER.
Referenced by PspInitializeJobStructures().
VOID PspRemoveProcessFromJob (PEJOB Job, PEPROCESS Process)
Definition at line 617 of file psjob.c.
References _EJOB::ActiveProcesses, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _EPROCESS::JobLinks, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), PAGED_CODE, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PsGetCurrentThread(), PspFoldProcessAccountingIntoJob(), RemoveEntryList(), _ETHREAD::Tcb, and TRUE.
Referenced by PspProcessDelete().
VOID PspShutdownJobLimits (VOID)
Definition at line 3096 of file psjob.c.
References KeCancelTimer(), PsGetCurrentThread(), PspJobTimeLimitsShuttingDown, PspLockJobTimeLimitsExclusive(), PspUnlockJobTimeLimitsExclusive(), and TRUE.
Referenced by PsShutdownSystem().
BOOLEAN PspTerminateAllProcessesInJob (PEJOB Job, NTSTATUS Status, BOOLEAN IncCounter)
Definition at line 2626 of file psjob.c.
References _EJOB::ActiveProcesses, _EJOB::Event, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeSetEvent(), NT_SUCCESS, NULL, PAGED_CODE, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PsGetCurrentThread(), PsGetNextJobProcess(), PspFoldProcessAccountingIntoJob(), PspTerminateProcess(), _ETHREAD::Tcb, _EJOB::TotalTerminatedProcesses, and TRUE.
Referenced by NtTerminateJobObject(), PsEnforceExecutionTimeLimits(), and PspJobClose().
NTSTATUS PspWin32SessionCallout (IN PKWIN32_JOB_CALLOUT CalloutRoutine, IN PKWIN32_JOBCALLOUT_PARAMETERS Parameters, IN ULONG SessionId)
Definition at line 3416 of file psjob.c.
References ASSERT, DPFLTR_SYSTEM_ID, DPFLTR_WARNING_LEVEL, _EPROCESS::Flags, KdPrintEx, MmAttachSession(), MmDetachSession(), MmGetSessionById(), MmGetSessionId(), MmIsSessionAddress(), MmQuitNextSession(), NT_SUCCESS, NULL, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), Status, STATUS_INVALID_PARAMETER, STATUS_NOT_FOUND, and STATUS_SUCCESS.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PspJobDelete().
VOID PsReportProcessMemoryLimitViolation (VOID)
Definition at line 2958 of file psjob.c.
References _EJOB::CompletionKey, _EJOB::CompletionPort, IoSetIoCompletion(), _EPROCESS::Job, JOB_OBJECT_LIMIT_PROCESS_MEMORY, JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT, _EPROCESS::JobStatus, _EJOB::LimitFlags, NULL, PAGED_CODE, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspLockJobLimitsShared(), PspUnlockJobLimitsShared(), STATUS_SUCCESS, TRUE, and _EPROCESS::UniqueProcessId.
Referenced by MiInsertVadCharges(), MiSetPageModified(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
Variable Documentation
POBJECT_TYPE IoCompletionObjectType
Definition at line 239 of file iodata.c.
Referenced by IopCreateObjectTypes(), NtCreateIoCompletion(), NtOpenIoCompletion(), NtQueryIoCompletion(), NtRemoveIoCompletion(), NtSetInformationFile(), and NtSetIoCompletion().
const ULONG PspJobInfoAlign[]
Initial value:
= {
    sizeof(ULONG),
    sizeof(ULONG),
    sizeof(ULONG),
    sizeof(ULONG),
    sizeof(ULONG),
    sizeof(ULONG),
    sizeof(PVOID),
    sizeof(ULONG),
    sizeof(ULONG),
    TYPE_ALIGNMENT (JOBOBJECT_JOBSET_INFORMATION),
    0
    }
Definition at line 889 of file psjob.c.
Referenced by NtQueryInformationJobObject(), and NtSetInformationJobObject().
const ULONG PspJobInfoLengths[]
Initial value:
= {
    sizeof(JOBOBJECT_BASIC_ACCOUNTING_INFORMATION),
    sizeof(JOBOBJECT_BASIC_LIMIT_INFORMATION),
    sizeof(JOBOBJECT_BASIC_PROCESS_ID_LIST),
    sizeof(JOBOBJECT_BASIC_UI_RESTRICTIONS),
    sizeof(JOBOBJECT_SECURITY_LIMIT_INFORMATION),
    sizeof(JOBOBJECT_END_OF_JOB_TIME_INFORMATION),
    sizeof(JOBOBJECT_ASSOCIATE_COMPLETION_PORT),
    sizeof(JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION),
    sizeof(JOBOBJECT_EXTENDED_LIMIT_INFORMATION),
    sizeof(JOBOBJECT_JOBSET_INFORMATION),
    0
    }
Definition at line 875 of file psjob.c.
Referenced by NtQueryInformationJobObject(), and NtSetInformationJobObject().
KDPC PspJobTimeLimitsDpc
Definition at line 53 of file psjob.c.
LARGE_INTEGER PspJobTimeLimitsInterval = {0}
Definition at line 65 of file psjob.c.
KGUARDED_MUTEX PspJobTimeLimitsLock
Definition at line 56 of file psjob.c.
BOOLEAN PspJobTimeLimitsShuttingDown
Definition at line 57 of file psjob.c.
Referenced by PspInitializeJobStructures(), PspJobTimeLimitsWork(), and PspShutdownJobLimits().
KTIMER PspJobTimeLimitsTimer
Definition at line 54 of file psjob.c.
WORK_QUEUE_ITEM PspJobTimeLimitsWorkItem
Definition at line 55 of file psjob.c.