Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/qsinfo.c File Reference
qsinfo.c File Reference
#include "iomgr.h"
Macros
#define FSIO_A FILE_SYNCHRONOUS_IO_ALERT
#define FSIO_NA FILE_SYNCHRONOUS_IO_NONALERT
Functions
ULONG IopGetModeInformation (IN PFILE_OBJECT FileObject)
NTSTATUS NtQueryInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
NTSTATUS NtSetInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
Macro Definition Documentation
#define FSIO_A FILE_SYNCHRONOUS_IO_ALERT
Definition at line 27 of file qsinfo.c.
Referenced by NtSetInformationFile().
#define FSIO_NA FILE_SYNCHRONOUS_IO_NONALERT
Definition at line 28 of file qsinfo.c.
Referenced by NtSetInformationFile().
Function Documentation
ULONG IopGetModeInformation (IN PFILE_OBJECT FileObject)
Definition at line 44 of file qsinfo.c.
References FILE_DELETE_ON_CLOSE, FILE_NO_INTERMEDIATE_BUFFERING, FILE_SEQUENTIAL_ONLY, FILE_SYNCHRONOUS_IO_ALERT, FILE_SYNCHRONOUS_IO_NONALERT, FILE_WRITE_THROUGH, FO_ALERTABLE_IO, FO_DELETE_ON_CLOSE, FO_NO_INTERMEDIATE_BUFFERING, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, and FO_WRITE_THROUGH.
Referenced by NtQueryInformationFile().
NTSTATUS NtQueryInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
Definition at line 91 of file qsinfo.c.
References _FILE_ACCESS_INFORMATION::AccessFlags, _FILE_ALL_INFORMATION::AccessInformation, _FILE_ALL_INFORMATION::AlignmentInformation, _FILE_ALIGNMENT_INFORMATION::AlignmentRequirement, APC_LEVEL, _FILE_POSITION_INFORMATION::CurrentByteOffset, _FILE_OBJECT::CurrentByteOffset, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, _FAST_IO_DISPATCH::FastIoQueryBasicInfo, _FAST_IO_DISPATCH::FastIoQueryStandardInfo, FileAccessInformation, FileAlignmentInformation, FileAllInformation, FileBasicInformation, FileMaximumInformation, FileModeInformation, _IO_STACK_LOCATION::FileObject, FilePositionInformation, FileStandardInformation, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_SYNCHRONOUS_IO, _OBJECT_HANDLE_INFORMATION::GrantedAccess, IoAllocateIrp(), IoCallDriver(), IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopCompleteRequest(), IopExceptionCleanup(), IopGetModeInformation(), IopQueryOperationAccess, IopQueryOperationLength, IopQuerySetAlignmentRequirement, IopQueueThreadIrp(), IopReleaseFileObjectLock, IopUpdateOtherOperationCount(), IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_QUERY_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _FILE_MODE_INFORMATION::Mode, _FILE_ALL_INFORMATION::ModeInformation, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_PENDING, STATUS_SUCCESS, STATUS_USER_APC, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
Referenced by HvpDoWriteHive().
NTSTATUS NtSetInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass)
Definition at line 836 of file qsinfo.c.
References APC_LEVEL, ASSERT, _FILE_OBJECT::CompletionContext, _FILE_POSITION_INFORMATION::CurrentByteOffset, _FILE_OBJECT::CurrentByteOffset, _FILE_DISPOSITION_INFORMATION::DeleteFile, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExRaiseStatus(), FALSE, FIELD_OFFSET, FILE_SEQUENTIAL_ONLY, FILE_VALID_SET_FLAGS, FILE_WRITE_THROUGH, FileAllocationInformation, FileCompletionInformation, FileDispositionInformation, FileEndOfFileInformation, FileLinkInformation, FileMaximumInformation, FileModeInformation, FileMoveClusterInformation, _FILE_NAME_INFORMATION::FileName, _FILE_RENAME_INFORMATION::FileName, _FILE_NAME_INFORMATION::FileNameLength, _FILE_RENAME_INFORMATION::FileNameLength, _IO_STACK_LOCATION::FileObject, FilePositionInformation, FileRenameInformation, FileShortNameInformation, FileTrackingInformation, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_NO_INTERMEDIATE_BUFFERING, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, FSIO_A, FSIO_NA, _LARGE_INTEGER::HighPart, InterlockedCompareExchangePointer, IO_COMPLETION_MODIFY_STATE, IoAllocateIrp(), IoCallDriver(), IoCompletionObjectType, IoFileObjectType, IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopCompleteRequest(), IopExceptionCleanup(), IopOpenLinkOrRenameTarget(), IopQuerySetAlignmentRequirement, IopQueueThreadIrp(), IopReleaseFileObjectLock, IopSetOperationAccess, IopSetOperationLength, IopTrackLink(), IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_MJ_SET_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _FILE_COMPLETION_INFORMATION::Key, _IO_COMPLETION_CONTEXT::Key, _LARGE_INTEGER::LowPart, _IO_STACK_LOCATION::MajorFunction, _FILE_MODE_INFORMATION::Mode, NonPagedPool, NOTHING, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_NAME_PATH_SEPARATOR, ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_COMPLETION_INFORMATION::Port, _IO_COMPLETION_CONTEXT::Port, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_PORT_ALREADY_SET, STATUS_SUCCESS, STATUS_USER_APC, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.