Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obcreate.c File Reference
obcreate.c File Reference
#include "obp.h"
Functions
C_ASSERT ((FIELD_OFFSET(OBJECT_HEADER, Body)%MEMORY_ALLOCATION_ALIGNMENT)==0)
C_ASSERT ((sizeof(OBJECT_HEADER_CREATOR_INFO)%MEMORY_ALLOCATION_ALIGNMENT)==0)
C_ASSERT ((sizeof(OBJECT_HEADER_NAME_INFO)%MEMORY_ALLOCATION_ALIGNMENT)==0)
C_ASSERT ((sizeof(OBJECT_HEADER_QUOTA_INFO)%MEMORY_ALLOCATION_ALIGNMENT)==0)
NTSTATUS ObCreateObject (__in KPROCESSOR_MODE ProbeMode, __in POBJECT_TYPE ObjectType, __in POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE OwnershipMode, __inout_opt PVOID ParseContext, __in ULONG ObjectBodySize, __in ULONG PagedPoolCharge, __in ULONG NonPagedPoolCharge, __out PVOID *Object)
NTKERNELAPI VOID ObDeleteCapturedInsertInfo (__in PVOID Object)
VOID FASTCALL ObFreeObjectCreateInfoBuffer (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo)
NTSTATUS ObpAllocateObject (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN KPROCESSOR_MODE OwnershipMode, IN POBJECT_TYPE ObjectType OPTIONAL, IN PUNICODE_STRING ObjectName, IN ULONG ObjectBodySize, OUT POBJECT_HEADER *ReturnedObjectHeader)
PWCHAR ObpAllocateObjectNameBuffer (IN ULONG Length, IN LOGICAL UseLookaside, IN OUT PUNICODE_STRING ObjectName)
NTSTATUS ObpCaptureObjectCreateInformation (IN POBJECT_TYPE ObjectType OPTIONAL, IN KPROCESSOR_MODE ProbeMode, IN KPROCESSOR_MODE CreatorMode, IN POBJECT_ATTRIBUTES ObjectAttributes, IN OUT PUNICODE_STRING CapturedObjectName, IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN LOGICAL UseLookaside)
NTSTATUS ObpCaptureObjectName (IN KPROCESSOR_MODE ProbeMode, IN PUNICODE_STRING ObjectName, IN OUT PUNICODE_STRING CapturedObjectName, IN LOGICAL UseLookaside)
VOID FASTCALL ObpFreeObject (IN PVOID Object)
VOID FASTCALL ObpFreeObjectNameBuffer (OUT PUNICODE_STRING ObjectName)
Variables
const BOOLEAN ObWatchHandles = FALSE
Function Documentation
C_ASSERT ((FIELD_OFFSET(OBJECT_HEADER, Body)%MEMORY_ALLOCATION_ALIGNMENT) = =0)
C_ASSERT ((sizeof(OBJECT_HEADER_CREATOR_INFO)%MEMORY_ALLOCATION_ALIGNMENT) = =0)
C_ASSERT ((sizeof(OBJECT_HEADER_NAME_INFO)%MEMORY_ALLOCATION_ALIGNMENT) = =0)
C_ASSERT ((sizeof(OBJECT_HEADER_QUOTA_INFO)%MEMORY_ALLOCATION_ALIGNMENT) = =0)
NTSTATUS ObCreateObject (__in KPROCESSOR_MODE ProbeMode, __in POBJECT_TYPE ObjectType, __in POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE OwnershipMode, __inout_opt PVOID ParseContext, __in ULONG ObjectBodySize, __in ULONG PagedPoolCharge, __in ULONG NonPagedPoolCharge, __out PVOID * Object)
Definition at line 71 of file obcreate.c.
References _OBJECT_CREATE_INFORMATION::Attributes, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, FALSE, _OBJECT_HEADER::Flags, _OBJECT_CREATE_INFORMATION::NonPagedPoolCharge, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, ObpAllocateObject(), ObpAllocateObjectCreateInfoBuffer, ObpCaptureObjectCreateInformation(), ObpFreeObject(), ObpFreeObjectCreateInfoBuffer, ObpFreeObjectNameBuffer(), ObpPushStackInfo, ObpReleaseObjectCreateInformation, ObpTraceEnabled, PAGED_CODE, _OBJECT_CREATE_INFORMATION::PagedPoolCharge, SeCreatePermanentPrivilege, SeSinglePrivilegeCheck(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, TRUE, and UNREFERENCED_PARAMETER.
NTKERNELAPI VOID ObDeleteCapturedInsertInfo (__in PVOID Object)
Definition at line 757 of file obcreate.c.
References _OBJECT_HEADER::Flags, NULL, OB_FLAG_NEW_OBJECT, OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, ObpFreeObjectCreateInformation, and PAGED_CODE.
Referenced by CcInitializeCacheMap().
VOID FASTCALL ObFreeObjectCreateInfoBuffer (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo)
Definition at line 1350 of file obcreate.c.
References ObpFreeObjectCreateInfoBuffer.
Referenced by IoCreateStreamFileObjectLite().
NTSTATUS ObpAllocateObject (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN KPROCESSOR_MODE OwnershipMode, IN POBJECT_TYPE ObjectType OPTIONAL, IN PUNICODE_STRING ObjectName, IN ULONG ObjectBodySize, OUT POBJECT_HEADER * ReturnedObjectHeader)
Definition at line 805 of file obcreate.c.
References _OBJECT_HEADER_CREATOR_INFO::CreatorBackTraceIndex, _OBJECT_HEADER_CREATOR_INFO::CreatorUniqueProcess, DbgPrint(), _OBJECT_HEADER_NAME_INFO::Directory, ExAllocatePoolWithTag, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, FIELD_OFFSET, _OBJECT_HEADER::Flags, _OBJECT_HANDLE_COUNT_ENTRY::HandleCount, _OBJECT_HEADER::HandleCount, _OBJECT_HEADER::HandleInfoOffset, InitializeListHead(), InterlockedIncrement, KernelMode, _OBJECT_HEADER_NAME_INFO::Name, _OBJECT_HEADER::NameInfoOffset, NonPagedPool, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NULL, OB_FLAG_CREATOR_INFO, OB_FLAG_EXCLUSIVE_OBJECT, OB_FLAG_KERNEL_OBJECT, OB_FLAG_NEW_OBJECT, OB_FLAG_PERMANENT_OBJECT, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJ_EXCLUSIVE, OBJ_KERNEL_EXCLUSIVE, OBJ_PERMANENT, _OBJECT_HEADER::ObjectCreateInfo, OBP_NAME_KERNEL_PROTECTED, PAGED_CODE, PagedPool, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, PERFINFO_ADD_OBJECT_TO_ALLOCATED_TYPE_LIST, _OBJECT_HEADER::PointerCount, PROTECTED_POOL, PsGetCurrentProcess(), PsInitialSystemProcess, _OBJECT_HEADER_NAME_INFO::QueryReferences, _OBJECT_HEADER::QuotaInfoOffset, SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, _OBJECT_HEADER_HANDLE_INFO::SingleEntry, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _OBJECT_HEADER::Type, _OBJECT_HEADER_CREATOR_INFO::TypeList, and _EPROCESS::UniqueProcessId.
Referenced by ObCreateObject(), and ObCreateObjectType().
PWCHAR ObpAllocateObjectNameBuffer (IN ULONG Length, IN LOGICAL UseLookaside, IN OUT PUNICODE_STRING ObjectName)
Definition at line 633 of file obcreate.c.
References ExAllocateFromPPLookasideList(), ExAllocatePoolWithTag, FALSE, LookasideNameBufferList, OB_NAMESPACE_POOL_TYPE, and OBJECT_NAME_BUFFER_SIZE.
Referenced by ObpCaptureObjectName().
NTSTATUS ObpCaptureObjectCreateInformation (IN POBJECT_TYPE ObjectType OPTIONAL, IN KPROCESSOR_MODE ProbeMode, IN KPROCESSOR_MODE CreatorMode, IN POBJECT_ATTRIBUTES ObjectAttributes, IN OUT PUNICODE_STRING CapturedObjectName, IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN LOGICAL UseLookaside)
Definition at line 282 of file obcreate.c.
References ARGUMENT_PRESENT, DbgBreakPoint(), except, ExSystemExceptionFilter(), KdPrint, KernelMode, NT_SUCCESS, NULL, OBJ_ALL_VALID_ATTRIBUTES, OBJ_KERNEL_HANDLE, ObpCaptureObjectName(), ObpReleaseObjectCreateInformation, ObWatchHandles, PAGED_CODE, PagedPool, ProbeForReadSmallStructure, PsGetCurrentProcess(), PsInitialSystemProcess, RtlZeroMemory, SeCaptureSecurityDescriptor(), SeComputeQuotaInformationSize(), SeComputeSecurityQuota, Status, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, TRUE, and UNREFERENCED_PARAMETER.
Referenced by ObCreateObject(), and ObOpenObjectByName().
NTSTATUS ObpCaptureObjectName (IN KPROCESSOR_MODE ProbeMode, IN PUNICODE_STRING ObjectName, IN OUT PUNICODE_STRING CapturedObjectName, IN LOGICAL UseLookaside)
Definition at line 488 of file obcreate.c.
References _UNICODE_STRING::Buffer, except, ExFreePool(), ExSystemExceptionFilter(), KernelMode, _UNICODE_STRING::Length, MAXUSHORT, NULL, ObpAllocateObjectNameBuffer(), PAGED_CODE, ProbeAndReadUnicodeStringEx, ProbeForRead, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by ObpCaptureObjectCreateInformation(), and ObReferenceObjectByName().
VOID FASTCALL ObpFreeObject (IN PVOID Object)
Definition at line 1165 of file obcreate.c.
References _UNICODE_STRING::Buffer, DbgPrint(), _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExFreePool(), ExFreePoolWithTag, _OBJECT_HEADER::Flags, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, InterlockedDecrement, _OBJECT_TYPE::Name, _OBJECT_HEADER_NAME_INFO::Name, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NULL, OB_FLAG_DEFAULT_SECURITY_QUOTA, OB_FLAG_NEW_OBJECT, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_HANDLE_INFO(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_HEADER_TO_QUOTA_INFO(), OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, ObpFreeObjectCreateInformation, PAGED_CODE, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, PERFINFO_REMOVE_OBJECT_FROM_ALLOCATED_TYPE_LIST, PROTECTED_POOL, PsReturnSharedPoolQuota(), _OBJECT_HEADER::QuotaBlockCharged, SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, _OBJECT_TYPE::TotalNumberOfObjects, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UIntToPtr.
Referenced by ObCreateObject(), and ObpRemoveObjectRoutine().
VOID FASTCALL ObpFreeObjectNameBuffer (OUT PUNICODE_STRING ObjectName)
Definition at line 711 of file obcreate.c.
References ExFreePool(), ExFreeToPPLookasideList(), LookasideNameBufferList, and OBJECT_NAME_BUFFER_SIZE.
Referenced by ObCreateObject(), ObOpenObjectByName(), and ObReferenceObjectByName().
Variable Documentation
const BOOLEAN ObWatchHandles = FALSE
Definition at line 48 of file obcreate.c.
Referenced by ObpCaptureObjectCreateInformation().