Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/biosc.c File Reference
biosc.c File Reference
#include "ki.h"
#include "vdmntos.h"
Macros
#define INT_10_TEB 0x13000
#define INT_OPCODE 0xcd
#define IOPM_OFFSET FIELD_OFFSET(KTSS, IoMaps[0].IoMap)
#define V86_BOP_OPCODE 0xfec4c4
#define V86_CODE_ADDRESS 0x10000
#define V86_STACK_POINTER 0x1ffe
#define VDM_TIB_ADDRESS 0x12000
Functions
NTSTATUS Ke386CallBios (IN ULONG BiosCommand, IN OUT PCONTEXT BiosArguments)
VOID Ki386SetupAndExitToV86Code (PVOID ExecutionAddress)
Variables
PVOID Ki386IopmSaveArea
Macro Definition Documentation
#define INT_10_TEB 0x13000
Definition at line 38 of file biosc.c.
Referenced by Ke386CallBios().
#define INT_OPCODE 0xcd
Definition at line 33 of file biosc.c.
Referenced by Ke386CallBios().
#define IOPM_OFFSET FIELD_OFFSET(KTSS, IoMaps[0].IoMap)
Definition at line 36 of file biosc.c.
Referenced by Ke386CallBios().
#define V86_BOP_OPCODE 0xfec4c4
Definition at line 34 of file biosc.c.
Referenced by Ke386CallBios().
#define V86_CODE_ADDRESS 0x10000
Definition at line 32 of file biosc.c.
Referenced by Ke386CallBios().
#define V86_STACK_POINTER 0x1ffe
Definition at line 35 of file biosc.c.
#define VDM_TIB_ADDRESS 0x12000
Definition at line 37 of file biosc.c.
Referenced by Ke386CallBios().
Function Documentation
NTSTATUS Ke386CallBios (IN ULONG BiosCommand, IN OUT PCONTEXT BiosArguments)
Definition at line 52 of file biosc.c.
References _KTHREAD::ApcState, ASSERT, CONTEXT_FULL, _DISPATCHER_HEADER::DebugActive, EFLAGS_INTERRUPT_MASK, EFLAGS_V86_MASK, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FIELD_OFFSET, _KTHREAD::Header, INT_10_TEB, INT_OPCODE, _KiIoAccessMap::IoMap, _KTSS::IoMapBase, _KTSS::IoMaps, IOPM_OFFSET, _KPROCESS::IopmOffset, KeGetCurrentThread(), KeGetPcr(), KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KGDT_TSS, Ki386IopmSaveArea, Ki386SetupAndExitToV86Code(), NonPagedPool, NULL, PAGE_SIZE, _KAPC_STATE::Process, PS_CLEAR_BITS, PS_PROCESS_FLAGS_VDM_ALLOWED, PS_SET_BITS, PsGetCurrentProcess(), RtlCopyMemory, RtlZeroMemory, STATUS_NO_MEMORY, STATUS_SUCCESS, _KPCR::TSS, V86_BOP_OPCODE, V86_CODE_ADDRESS, VDM_TIB_ADDRESS, and _EPROCESS::VdmObjects.
VOID Ki386SetupAndExitToV86Code (PVOID ExecutionAddress)
Referenced by Ke386CallBios().
Variable Documentation
PVOID Ki386IopmSaveArea
Definition at line 44 of file biosc.c.
Referenced by Ke386CallBios(), and KiInitializeKernel().