Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/zeropage.c File Reference
zeropage.c File Reference
#include "mi.h"
Macros
#define MACHINE_ZERO_PAGE(ZeroBase, NumberOfBytes) KeZeroPagesFromIdleThread(ZeroBase,NumberOfBytes)
#define MM_ZERO_PAGE_OBJECT 0
#define NUMBER_WAIT_OBJECTS 2
#define PO_SYS_IDLE_OBJECT 1
Functions
VOID MiStartZeroPageWorkers (VOID)
VOID MiZeroPageWorker (IN PVOID Context)
VOID MmZeroPageThread (VOID)
Variables
LONG MiNextZeroProcessor = (LONG)-1
LOGICAL MiZeroingDisabled = FALSE
Macro Definition Documentation
#define MACHINE_ZERO_PAGE (ZeroBase, NumberOfBytes) KeZeroPagesFromIdleThread(ZeroBase,NumberOfBytes)
Definition at line 25 of file zeropage.c.
Referenced by MmZeroPageThread().
#define MM_ZERO_PAGE_OBJECT 0
Definition at line 21 of file zeropage.c.
Referenced by MmZeroPageThread().
#define NUMBER_WAIT_OBJECTS 2
Definition at line 23 of file zeropage.c.
Referenced by MmZeroPageThread().
#define PO_SYS_IDLE_OBJECT 1
Definition at line 22 of file zeropage.c.
Referenced by MmZeroPageThread().
Function Documentation
VOID MiStartZeroPageWorkers (VOID)
Definition at line 782 of file zeropage.c.
References CriticalWorkQueue, ExAllocatePoolWithTag, ExInitializeWorkItem, ExQueueWorkItem(), KeNumberProcessors, MiZeroPageWorker(), NonPagedPool, and NULL.
Referenced by MmInitSystem().
VOID MiZeroPageWorker (IN PVOID Context)
Definition at line 437 of file zeropage.c.
References AFFINITY_MASK, ASSERT, BadPageList, _KTHREAD::BasePriority, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, ExFreePool(), FALSE, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, _MMPTE::Hard, InterlockedIncrement, KeBugCheckEx(), KeGetCurrentNode, KeGetCurrentThread(), KeNumberNodes, KeNumberProcessors, KeRevertToUserAffinityThread(), KeSetPriorityThread(), KeSetSystemAffinityThread(), KeZeroPages, LOCK_PFN, MI_DISABLE_CACHING, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MiGetVirtualAddressMappedByPte, MiInsertPageInFreeList(), MiInsertZeroListAtBack(), MiNextZeroProcessor, MiNonCached, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiWriteCombined, MM_EMPTY_LIST, MmFreePagesByColor, MmSecondaryColorMask, MmSecondaryColors, NULL, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PFN_LIST_CORRUPT, _MMPFN::PteAddress, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and ValidKernelPte.
Referenced by MiStartZeroPageWorkers().
VOID MmZeroPageThread (VOID)
Definition at line 44 of file zeropage.c.
References ASSERT, BadPageList, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, KeBugCheckEx(), KeDelayExecutionThread(), KeFindFirstSetLeftAffinity, KeGetCurrentThread(), KeNodeBlock, KeNumberNodes, KernelMode, KeSetIdealProcessorThread(), KeSetPriorityZeroPageThread(), KeWaitForMultipleObjects(), LOCK_PFN, MACHINE_ZERO_PAGE, MI_DECREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiChargeCommitment(), MiFindInitializationCode(), MiFreeInitializationCode(), MiInsertPageInList(), MiMapPagesToZeroInHyperSpace(), MiRemoveAnyPage(), MiUnmapPagesInZeroSpace(), MiZeroingDisabled, MM_EMPTY_LIST, MM_RESAVAIL_ALLOCATE_ZERO_PAGE_CLUSTERS, MM_ZERO_PAGE_OBJECT, MmFreePageListHead, MmFreePagesByColor, MmHalfSecond, MmSecondaryColorMask, MmZeroedPageListHead, MmZeroingPageEvent, MmZeroingPageThreadActive, NO_BITS_FOUND, NULL, NUMBER_OF_ZEROING_PTES, NUMBER_WAIT_OBJECTS, PAGE_SHIFT, _MMPFNENTRY::PageLocation, PFN_LIST_CORRUPT, PO_SYS_IDLE_OBJECT, PoSystemIdleTimer, PoSystemIdleWorker(), _MMPFN::PteAddress, Status, _MMPFNLIST::Total, TRUE, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, WaitAny, and WrFreePage.
Referenced by Phase1Initialization().
Variable Documentation
LONG MiNextZeroProcessor = (LONG)-1
Definition at line 35 of file zeropage.c.
Referenced by MiZeroPageWorker().
LOGICAL MiZeroingDisabled = FALSE
Definition at line 27 of file zeropage.c.
Referenced by MiReleaseAllMemory(), and MmZeroPageThread().