Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/pushlock.c File Reference
pushlock.c File Reference
#include "exp.h"
Macros
#define USE_EXP_BACKOFF
Functions
NTKERNELAPI VOID ExAcquireCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
NTKERNELAPI PEX_PUSH_LOCK_CACHE_AWARE ExAllocateCacheAwarePushLock (VOID)
NTKERNELAPI VOID FASTCALL ExBlockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfAcquirePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfConvertPushLockExclusiveToShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID ExFreeCacheAwarePushLock (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfReleasePushLock (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfReleasePushLockShared (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI BOOLEAN FASTCALL ExfTryAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
VOID FASTCALL ExfTryToWakePushLock (__inout PEX_PUSH_LOCK PushLock)
NTKERNELAPI VOID FASTCALL ExfUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout_opt PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
NTKERNELAPI VOID FASTCALL ExfWakePushLock (IN PEX_PUSH_LOCK PushLock, IN EX_PUSH_LOCK TopValue)
VOID ExpInitializePushLocks (VOID)
VOID FASTCALL ExpOptimizePushLockList (IN PEX_PUSH_LOCK PushLock, IN EX_PUSH_LOCK TopValue)
NTKERNELAPI VOID ExReleaseCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
NTKERNELAPI NTSTATUS FASTCALL ExTimedWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock, __in_opt PLARGE_INTEGER Timeout)
NTKERNELAPI VOID FASTCALL ExWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Variables
ULONG ExPushLockSpinCount = 0
Macro Definition Documentation
#define USE_EXP_BACKOFF
Definition at line 147 of file pushlock.c.
Function Documentation
NTKERNELAPI VOID ExAcquireCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
Definition at line 1398 of file pushlock.c.
References EX_PUSH_LOCK_FANNED_COUNT, ExAcquirePushLockExclusive(), ExTryAcquirePushLockExclusive(), and KeNumberProcessors.
Referenced by MiAweViewInserter(), MiAweViewRemover(), MiProtectAweRegion(), MiRemoveUserPhysicalPagesVad(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
NTKERNELAPI PEX_PUSH_LOCK_CACHE_AWARE ExAllocateCacheAwarePushLock (VOID)
Definition at line 1276 of file pushlock.c.
References AFFINITY_MASK, EX_PUSH_LOCK_FANNED_COUNT, ExAllocatePoolWithTag, ExFreePool(), ExInitializePushLock(), FALSE, KeNumberNodes, KeNumberProcessors, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), _EX_PUSH_LOCK_CACHE_AWARE_PADDED::Lock, _EX_PUSH_LOCK_CACHE_AWARE::Locks, NULL, PagedPool, _EX_PUSH_LOCK_CACHE_AWARE_PADDED::Single, and TRUE.
Referenced by MiAllocateAweInfo().
NTKERNELAPI VOID FASTCALL ExBlockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Definition at line 1107 of file pushlock.c.
References EX_PUSH_LOCK_FLAGS_SPINNING, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Ptr, and ReadForWriteAccess.
Referenced by ExpBlockOnLockedHandleEntry().
NTKERNELAPI VOID FASTCALL ExfAcquirePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
Definition at line 450 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_WAITING, EX_PUSH_LOCK_WAKING, ExpOptimizePushLockList(), ExPushLockSpinCount, FALSE, InterlockedBitTestAndReset(), InterlockedCompareExchangePointer, KeInitializeGate(), KernelMode, KeWaitForGate(), KeYieldProcessor, _EX_PUSH_LOCK::Locked, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, RTL_BACKOFF, RtlBackoff(), _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, _EX_PUSH_LOCK::Waking, and WrPushLock.
Referenced by ExAcquirePushLockExclusive(), ExAcquireReleasePushLockExclusive(), and ExpInitializePushLocks().
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 602 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_SHARE_INC, EX_PUSH_LOCK_WAITING, EX_PUSH_LOCK_WAKING, ExpOptimizePushLockList(), ExPushLockSpinCount, FALSE, InterlockedBitTestAndReset(), InterlockedCompareExchangePointer, KeInitializeGate(), KernelMode, KeWaitForGate(), KeYieldProcessor, _EX_PUSH_LOCK::Locked, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, RTL_BACKOFF, RtlBackoff(), _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, _EX_PUSH_LOCK::Waking, and WrPushLock.
Referenced by ExAcquirePushLockShared(), ExAcquirePushLockSharedAssumeNoOwner(), and ExpInitializePushLocks().
NTKERNELAPI VOID FASTCALL ExfConvertPushLockExclusiveToShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 1060 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, and _EX_PUSH_LOCK::Waiting.
Referenced by ExConvertPushLockExclusiveToShared().
NTKERNELAPI VOID ExFreeCacheAwarePushLock (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
Definition at line 1358 of file pushlock.c.
References CONTAINING_RECORD, EX_PUSH_LOCK_FANNED_COUNT, ExFreePool(), and KeNumberProcessors.
Referenced by MiCleanPhysicalProcessPages(), MiFreeAweInfo(), and MiInsertAweInfo().
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfReleasePushLock (__inout PEX_PUSH_LOCK PushLock)
Definition at line 955 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_SHARE_INC, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, InterlockedDecrement, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::MultipleShared, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExpInitializePushLocks(), and ExReleasePushLock().
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfReleasePushLockExclusive (__inout PEX_PUSH_LOCK PushLock)
Definition at line 900 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExAcquireReleasePushLockExclusive(), and ExpInitializePushLocks().
NTKERNELAPI VOID DECLSPEC_NOINLINE FASTCALL ExfReleasePushLockShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 806 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_MULTIPLE_SHARED, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_SHARE_INC, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, InterlockedDecrement, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::MultipleShared, NULL, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExpInitializePushLocks(), ExReleasePushLockShared(), and ExReleasePushLockSharedAssumeSingleOwner().
NTKERNELAPI BOOLEAN FASTCALL ExfTryAcquirePushLockShared (__inout PEX_PUSH_LOCK PushLock)
Definition at line 753 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_LOCK, EX_PUSH_LOCK_SHARE_INC, FALSE, InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, ReadForWriteAccess, _EX_PUSH_LOCK::Shared, TRUE, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waiting.
Referenced by ExTryAcquirePushLockShared().
VOID FASTCALL ExfTryToWakePushLock (__inout PEX_PUSH_LOCK PushLock)
Definition at line 345 of file pushlock.c.
References EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::Ptr, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExReleasePushLockExclusive().
NTKERNELAPI VOID FASTCALL ExfUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout_opt PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Definition at line 1213 of file pushlock.c.
References DISPATCH_LEVEL, EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, ExWaitForUnblockPushLock(), InterlockedBitTestAndReset(), InterlockedExchangePointer, KeLowerIrql, KeRaiseIrql, KeSetEventBoostPriority(), NULL, and _EX_PUSH_LOCK::Ptr.
Referenced by ExTimedWaitForUnblockPushLock(), and ExUnblockPushLock().
NTKERNELAPI VOID FASTCALL ExfWakePushLock (IN PEX_PUSH_LOCK PushLock, IN EX_PUSH_LOCK TopValue)
Definition at line 209 of file pushlock.c.
References ASSERT, DISPATCH_LEVEL, EX_PUSH_LOCK_FLAGS_EXCLUSIVE, EX_PUSH_LOCK_FLAGS_SPINNING_V, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_WAKING, InterlockedAnd(), InterlockedBitTestAndReset(), InterlockedCompareExchangePointer, KeLowerIrql, KeRaiseIrql, KeSignalGateBoostPriority(), _EX_PUSH_LOCK::Locked, _EX_PUSH_LOCK::MultipleShared, NULL, _EX_PUSH_LOCK::Ptr, TRUE, _EX_PUSH_LOCK::Value, _EX_PUSH_LOCK::Waiting, and _EX_PUSH_LOCK::Waking.
Referenced by ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExfTryToWakePushLock(), and ExpOptimizePushLockList().
VOID ExpInitializePushLocks (VOID)
Definition at line 151 of file pushlock.c.
References ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExInitializePushLock(), ExPushLockSpinCount, and KeNumberProcessors.
Referenced by ExpInitSystemPhase1().
VOID FASTCALL ExpOptimizePushLockList (IN PEX_PUSH_LOCK PushLock, IN EX_PUSH_LOCK TopValue)
Definition at line 384 of file pushlock.c.
References ASSERT, EX_PUSH_LOCK_PTR_BITS, EX_PUSH_LOCK_WAKING, ExfWakePushLock(), InterlockedCompareExchangePointer, _EX_PUSH_LOCK::Locked, NULL, _EX_PUSH_LOCK::Ptr, _EX_PUSH_LOCK::Value, and _EX_PUSH_LOCK::Waking.
Referenced by ExfAcquirePushLockExclusive(), and ExfAcquirePushLockShared().
NTKERNELAPI VOID ExReleaseCacheAwarePushLockExclusive (__inout PEX_PUSH_LOCK_CACHE_AWARE PushLock)
Definition at line 1447 of file pushlock.c.
References EX_PUSH_LOCK_FANNED_COUNT, ExReleasePushLockExclusive(), and KeNumberProcessors.
Referenced by MiAweViewInserter(), MiAweViewRemover(), MiProtectAweRegion(), MiRemoveUserPhysicalPagesVad(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
NTKERNELAPI NTSTATUS FASTCALL ExTimedWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock, __in_opt PLARGE_INTEGER Timeout)
Definition at line 1173 of file pushlock.c.
References EX_PUSH_LOCK_FLAGS_SPINNING, EX_PUSH_LOCK_FLAGS_SPINNING_V, ExfUnblockPushLock(), ExPushLockSpinCount, FALSE, InterlockedBitTestAndReset(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), KeYieldProcessor, Status, STATUS_SUCCESS, SynchronizationEvent, UNREFERENCED_PARAMETER, and WrPushLock.
Referenced by ExWaitForUnblockPushLock().
NTKERNELAPI VOID FASTCALL ExWaitForUnblockPushLock (__inout PEX_PUSH_LOCK PushLock, __inout PEX_PUSH_LOCK_WAIT_BLOCK WaitBlock)
Definition at line 1160 of file pushlock.c.
References ExTimedWaitForUnblockPushLock(), and NULL.
Referenced by ExfUnblockPushLock(), and ExpBlockOnLockedHandleEntry().
Variable Documentation
ULONG ExPushLockSpinCount = 0
Definition at line 143 of file pushlock.c.
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExpInitializePushLocks(), and ExTimedWaitForUnblockPushLock().