Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/yield.c File Reference
yield.c File Reference
#include "ki.h"
Functions
NTSTATUS NtYieldExecution (VOID)
Function Documentation
NTSTATUS NtYieldExecution (VOID)
Definition at line 23 of file yield.c.
References APC_LEVEL, ASSERT, _KPRCB::CurrentThread, DISPATCH_LEVEL, KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiAcquirePrcbLock(), KiAcquireThreadLock(), KiComputeNewPriority(), KiGetCurrentReadySummary, KiReleasePrcbLock(), KiReleaseThreadLock(), KiSelectReadyThread(), KiSetContextSwapBusy(), KiSwapContext(), KxQueueReadyThread(), _KPRCB::NextThread, NULL, _KTHREAD::Priority, _KTHREAD::Quantum, _KTHREAD::QuantumReset, _KPRCB::ReadySummary, Running, _KTHREAD::State, Status, STATUS_NO_YIELD_PERFORMED, STATUS_SUCCESS, _KTHREAD::WaitIrql, _KTHREAD::WaitReason, and WrYieldExecution.
Referenced by KeDelayExecutionThread().