Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/timerobj.c File Reference
timerobj.c File Reference
#include "ki.h"
Macros
#define ASSERT_TIMER(E)
#define KE_TIMER_CHECK_FREES 0x1
Functions
BOOLEAN KeCancelTimer (__inout PKTIMER Timer)
VOID KeCheckForTimer (__in_bcount(BlockSize) PVOID BlockStart, __in SIZE_T BlockSize)
VOID KeClearTimer (__inout PKTIMER Timer)
VOID KeInitializeTimer (__out PKTIMER Timer)
VOID KeInitializeTimerEx (__out PKTIMER Timer, __in TIMER_TYPE Type)
ULONGLONG KeQueryTimerDueTime (__in PKTIMER Timer)
BOOLEAN KeReadStateTimer (__in PKTIMER Timer)
BOOLEAN KeSetTimer (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in_opt PKDPC Dpc)
BOOLEAN KeSetTimerEx (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in LONG Period, __in_opt PKDPC Dpc)
Variables
ULONG KeTimerCheckFlags = KE_TIMER_CHECK_FREES
Macro Definition Documentation
#define ASSERT_TIMER (E)
Value:
{                                                    \
    ASSERT(((E)->Header.Type == TimerNotificationObject) ||                  \
           ((E)->Header.Type == TimerSynchronizationObject));                \
}
Definition at line 36 of file timerobj.c.
Referenced by KeCancelTimer(), KeClearTimer(), KeQueryTimerDueTime(), KeReadStateTimer(), and KeSetTimerEx().
#define KE_TIMER_CHECK_FREES 0x1
Definition at line 28 of file timerobj.c.
Referenced by KeCheckForTimer().
Function Documentation
BOOLEAN KeCancelTimer (__inout PKTIMER Timer)
Definition at line 157 of file timerobj.c.
References ASSERT, ASSERT_TIMER, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiRemoveTreeTimer(), and KiUnlockDispatcherDatabase().
Referenced by CmpShutdownWorkers(), ExpDeleteTimer(), ExpWorkerThreadBalanceManager(), ExTimerRundown(), KiInitializeInterruptTimersDpc(), NtCancelTimer(), NtSetTimer(), and PspShutdownJobLimits().
VOID KeCheckForTimer (__in_bcount(BlockSize) PVOID BlockStart, __in SIZE_T BlockSize)
Definition at line 434 of file timerobj.c.
References CONTAINING_RECORD, _KDPC::DeferredRoutine, _KTIMER::Dpc, _KTIMER_TABLE_ENTRY::Entry, _LIST_ENTRY::Flink, Index, KE_TIMER_CHECK_FREES, KeBugCheckEx(), KeTimerCheckFlags, KiAcquireTimerTableLock(), KiLockDispatcherDatabase, KiReleaseTimerTableLock(), KiTimerTableListHead, KiUnlockDispatcherDatabase(), TIMER_OR_DPC_INVALID, and TIMER_TABLE_SIZE.
Referenced by ExFreePoolSanityChecks().
VOID KeClearTimer (__inout PKTIMER Timer)
Definition at line 124 of file timerobj.c.
References ASSERT_TIMER.
VOID KeInitializeTimer (__out PKTIMER Timer)
Definition at line 42 of file timerobj.c.
References KeInitializeTimerEx(), and NotificationTimer.
Referenced by CcInitializeCacheManager(), CmpCmdInit(), CmpInitDelayDerefKCBEngine(), CmpInitializeDelayedCloseTable(), ExpWorkerThreadBalanceManager(), InitializePool(), IopErrorLogQueueRequest(), IopInitializeIrpStackProfiler(), KeInitThread(), PspInitializeJobStructures(), and WmipSetupWaitForWbem().
VOID KeInitializeTimerEx (__out PKTIMER Timer, __in TIMER_TYPE Type)
Definition at line 74 of file timerobj.c.
References FALSE, InitializeListHead(), NULL, and TimerNotificationObject.
Referenced by IoInitSystem(), KeBalanceSetManager(), KeInitializeTimer(), KiInitializeInterruptTimers(), MmInitSystem(), NtCreateTimer(), and WmipRegisterMcaHandler().
ULONGLONG KeQueryTimerDueTime (__in PKTIMER Timer)
Definition at line 379 of file timerobj.c.
References ASSERT_TIMER, KiLockDispatcherDatabase, and KiUnlockDispatcherDatabase().
Referenced by ExGetNextWakeTime().
BOOLEAN KeReadStateTimer (__in PKTIMER Timer)
Definition at line 211 of file timerobj.c.
References ASSERT_TIMER.
Referenced by NtCancelTimer(), NtQueryTimer(), and NtSetTimer().
BOOLEAN KeSetTimer (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in_opt PKDPC Dpc)
Definition at line 243 of file timerobj.c.
References KeSetTimerEx().
Referenced by CcScheduleLazyWriteScan(), CcSetActiveVacb(), CmpArmDelayedCloseTimer(), CmpCmdInit(), CmpDelayDerefKeyControlBlock(), CmpLazyFlush(), ExpWorkerThreadBalanceManager(), InitializePool(), IopErrorLogQueueRequest(), PspInitializeJobStructuresPhase1(), PspJobTimeLimitsWork(), WmipIsWbemRunningWorker(), and WmipSetupWaitForWbem().
BOOLEAN KeSetTimerEx (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in LONG Period, __in_opt PKDPC Dpc)
Definition at line 285 of file timerobj.c.
References ASSERT, ASSERT_TIMER, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KiComputeDueTime(), KiExitDispatcher(), KiInsertOrSignalTimer(), KiLockDispatcherDatabase, KiRemoveTreeTimer(), KiRequestSoftwareInterrupt, KiSignalTimer(), KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
Referenced by IoInitSystem(), IopInitializeIrpStackProfiler(), KeBalanceSetManager(), KeSetTimer(), KiInitializeInterruptTimers(), MiInsertPageInList(), MiModifiedPageWriterWorker(), NtSetTimer(), WmipPollingDpcRoutine(), and WmipRegisterMcaHandler().
Variable Documentation
ULONG KeTimerCheckFlags = KE_TIMER_CHECK_FREES
Definition at line 29 of file timerobj.c.
Referenced by KeCheckForTimer().