Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/cm.h File Reference
cm.h File Reference
Data Structures
struct _BOOT_DRIVER_LIST_ENTRY
struct _CM_SYSTEM_CONTROL_VECTOR
struct _REG_CREATE_KEY_INFORMATION
struct _REG_DELETE_KEY_INFORMATION
struct _REG_DELETE_VALUE_KEY_INFORMATION
struct _REG_ENUMERATE_KEY_INFORMATION
struct _REG_ENUMERATE_VALUE_KEY_INFORMATION
struct _REG_KEY_HANDLE_CLOSE_INFORMATION
struct _REG_POST_CREATE_KEY_INFORMATION
struct _REG_POST_OPERATION_INFORMATION
struct _REG_PRE_CREATE_KEY_INFORMATION
struct _REG_QUERY_KEY_INFORMATION
struct _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION
struct _REG_QUERY_VALUE_KEY_INFORMATION
struct _REG_RENAME_KEY_INFORMATION
struct _REG_SET_INFORMATION_KEY_INFORMATION
struct _REG_SET_VALUE_KEY_INFORMATION
Typedefs
typedef struct _BOOT_DRIVER_LIST_ENTRY BOOT_DRIVER_LIST_ENTRY
typedef struct _CM_SYSTEM_CONTROL_VECTOR CM_SYSTEM_CONTROL_VECTOR
typedef struct _BOOT_DRIVER_LIST_ENTRY * PBOOT_DRIVER_LIST_ENTRY
typedef VOID(* PCM_HYSTERESIS_CALLBACK) (PVOID Ref, ULONG Level)
typedef struct _CM_SYSTEM_CONTROL_VECTOR * PCM_SYSTEM_CONTROL_VECTOR
typedef VOID(* PCM_TRACE_NOTIFY_ROUTINE) (IN NTSTATUS Status, IN PVOID Kcb, IN LONGLONG ElapsedTime, IN ULONG Index, IN PUNICODE_STRING KeyName, IN UCHAR Type)
typedef struct _REG_CREATE_KEY_INFORMATION * PREG_CREATE_KEY_INFORMATION
typedef struct _REG_DELETE_KEY_INFORMATION * PREG_DELETE_KEY_INFORMATION
typedef struct _REG_DELETE_VALUE_KEY_INFORMATION * PREG_DELETE_VALUE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_KEY_INFORMATION * PREG_ENUMERATE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_VALUE_KEY_INFORMATION * PREG_ENUMERATE_VALUE_KEY_INFORMATION
typedef struct _REG_KEY_HANDLE_CLOSE_INFORMATION * PREG_KEY_HANDLE_CLOSE_INFORMATION
typedef struct _REG_CREATE_KEY_INFORMATION * PREG_OPEN_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION * PREG_POST_CREATE_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION * PREG_POST_OPEN_KEY_INFORMATION
typedef struct _REG_POST_OPERATION_INFORMATION * PREG_POST_OPERATION_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION * PREG_PRE_CREATE_KEY_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION * PREG_PRE_OPEN_KEY_INFORMATION
typedef struct _REG_QUERY_KEY_INFORMATION * PREG_QUERY_KEY_INFORMATION
typedef struct _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION * PREG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION
typedef struct _REG_QUERY_VALUE_KEY_INFORMATION * PREG_QUERY_VALUE_KEY_INFORMATION
typedef struct _REG_RENAME_KEY_INFORMATION * PREG_RENAME_KEY_INFORMATION
typedef struct _REG_SET_INFORMATION_KEY_INFORMATION * PREG_SET_INFORMATION_KEY_INFORMATION
typedef struct _REG_SET_VALUE_KEY_INFORMATION * PREG_SET_VALUE_KEY_INFORMATION
typedef struct _REG_CREATE_KEY_INFORMATION REG_CREATE_KEY_INFORMATION
typedef struct _REG_DELETE_KEY_INFORMATION REG_DELETE_KEY_INFORMATION
typedef struct _REG_DELETE_VALUE_KEY_INFORMATION REG_DELETE_VALUE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_KEY_INFORMATION REG_ENUMERATE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_VALUE_KEY_INFORMATION REG_ENUMERATE_VALUE_KEY_INFORMATION
typedef struct _REG_KEY_HANDLE_CLOSE_INFORMATION REG_KEY_HANDLE_CLOSE_INFORMATION
typedef enum _REG_NOTIFY_CLASS REG_NOTIFY_CLASS
typedef struct _REG_CREATE_KEY_INFORMATION REG_OPEN_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION REG_POST_CREATE_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION REG_POST_OPEN_KEY_INFORMATION
typedef struct _REG_POST_OPERATION_INFORMATION REG_POST_OPERATION_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION REG_PRE_CREATE_KEY_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION REG_PRE_OPEN_KEY_INFORMATION
typedef struct _REG_QUERY_KEY_INFORMATION REG_QUERY_KEY_INFORMATION
typedef struct _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION
typedef struct _REG_QUERY_VALUE_KEY_INFORMATION REG_QUERY_VALUE_KEY_INFORMATION
typedef struct _REG_RENAME_KEY_INFORMATION REG_RENAME_KEY_INFORMATION
typedef struct _REG_SET_INFORMATION_KEY_INFORMATION REG_SET_INFORMATION_KEY_INFORMATION
typedef struct _REG_SET_VALUE_KEY_INFORMATION REG_SET_VALUE_KEY_INFORMATION
Enumerations
enum _REG_NOTIFY_CLASS {
RegNtDeleteKey, RegNtPreDeleteKey = RegNtDeleteKey, RegNtSetValueKey, RegNtPreSetValueKey = RegNtSetValueKey,
RegNtDeleteValueKey, RegNtPreDeleteValueKey = RegNtDeleteValueKey, RegNtSetInformationKey, RegNtPreSetInformationKey = RegNtSetInformationKey,
RegNtRenameKey, RegNtPreRenameKey = RegNtRenameKey, RegNtEnumerateKey, RegNtPreEnumerateKey = RegNtEnumerateKey,
RegNtEnumerateValueKey, RegNtPreEnumerateValueKey = RegNtEnumerateValueKey, RegNtQueryKey, RegNtPreQueryKey = RegNtQueryKey,
RegNtQueryValueKey, RegNtPreQueryValueKey = RegNtQueryValueKey, RegNtQueryMultipleValueKey, RegNtPreQueryMultipleValueKey = RegNtQueryMultipleValueKey,
RegNtPreCreateKey, RegNtPostCreateKey, RegNtPreOpenKey, RegNtPostOpenKey,
RegNtKeyHandleClose, RegNtPreKeyHandleClose = RegNtKeyHandleClose, RegNtPostDeleteKey, RegNtPostSetValueKey,
RegNtPostDeleteValueKey, RegNtPostSetInformationKey, RegNtPostRenameKey, RegNtPostEnumerateKey,
RegNtPostEnumerateValueKey, RegNtPostQueryKey, RegNtPostQueryValueKey, RegNtPostQueryMultipleValueKey,
RegNtPostKeyHandleClose, RegNtPreCreateKeyEx, RegNtPostCreateKeyEx, RegNtPreOpenKeyEx,
RegNtPostOpenKeyEx
}
Functions
VOID CmBootLastKnownGood (__in ULONG ErrorLevel)
VOID CmGetSystemControlValues (__in PVOID SystemHiveBuffer, __inout PCM_SYSTEM_CONTROL_VECTOR ControlVector)
PHANDLE CmGetSystemDriverList (VOID)
BOOLEAN CmInitSystem1 (__in PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN CmInitSystem2 (VOID)
BOOLEAN CmIsLastKnownGoodBoot (VOID)
VOID CmNotifyRunDown (__in PETHREAD Thread)
NTSTATUS CmPrefetchHivePages (__in PUNICODE_STRING FullHivePath, __inout PREAD_LIST ReadList)
VOID CmQueryRegistryQuotaInformation (__inout PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
NTSTATUS CmRegisterCallback (__in PEX_CALLBACK_FUNCTION Function, __in_opt PVOID Context, __out PLARGE_INTEGER Cookie)
ULONG CmRegisterSystemHiveLimitCallback (__in ULONG Low, __in ULONG High, __in PVOID Ref, __in PCM_HYSTERESIS_CALLBACK Callback)
VOID CmSetLazyFlushState (__in BOOLEAN Enable)
VOID CmSetRegistryQuotaInformation (__in PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
NTSTATUS CmSetTraceNotifyRoutine (__in_opt PCM_TRACE_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
VOID CmShutdownSystem (VOID)
NTSTATUS CmUnRegisterCallback (__in LARGE_INTEGER Cookie)
Variables
UNICODE_STRING CmClassName []
const PWSTR CmClassString []
UNICODE_STRING CmRegistryMachineHardwareDescriptionName
UNICODE_STRING CmRegistryMachineHardwareDescriptionSystemName
UNICODE_STRING CmRegistryMachineHardwareDeviceMapName
UNICODE_STRING CmRegistryMachineHardwareName
UNICODE_STRING CmRegistryMachineHardwareOwnerMapName
UNICODE_STRING CmRegistryMachineHardwareResourceMapName
UNICODE_STRING CmRegistryMachineName
UNICODE_STRING CmRegistryMachineSystemCurrentControlSet
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlBootLog
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlClass
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlSafeBoot
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlSessionManagerMemoryManagement
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetEnumName
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetEnumRootName
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetHardwareProfilesCurrent
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetServices
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetServicesEventLog
UNICODE_STRING CmRegistryMachineSystemName
UNICODE_STRING CmRegistryRootName
UNICODE_STRING CmRegistryUserName
UNICODE_STRING CmTypeName []
const PWSTR CmTypeString []
Typedef Documentation
typedef struct _BOOT_DRIVER_LIST_ENTRY BOOT_DRIVER_LIST_ENTRY
typedef struct _CM_SYSTEM_CONTROL_VECTOR CM_SYSTEM_CONTROL_VECTOR
typedef struct _BOOT_DRIVER_LIST_ENTRY * PBOOT_DRIVER_LIST_ENTRY
typedef VOID(* PCM_HYSTERESIS_CALLBACK) (PVOID Ref, ULONG Level)
Definition at line 400 of file cm.h.
typedef struct _CM_SYSTEM_CONTROL_VECTOR * PCM_SYSTEM_CONTROL_VECTOR
typedef VOID(* PCM_TRACE_NOTIFY_ROUTINE) (IN NTSTATUS Status, IN PVOID Kcb, IN LONGLONG ElapsedTime, IN ULONG Index, IN PUNICODE_STRING KeyName, IN UCHAR Type)
Definition at line 199 of file cm.h.
typedef struct _REG_CREATE_KEY_INFORMATION* PREG_CREATE_KEY_INFORMATION
typedef struct _REG_DELETE_KEY_INFORMATION * PREG_DELETE_KEY_INFORMATION
typedef struct _REG_DELETE_VALUE_KEY_INFORMATION * PREG_DELETE_VALUE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_KEY_INFORMATION * PREG_ENUMERATE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_VALUE_KEY_INFORMATION * PREG_ENUMERATE_VALUE_KEY_INFORMATION
typedef struct _REG_KEY_HANDLE_CLOSE_INFORMATION * PREG_KEY_HANDLE_CLOSE_INFORMATION
typedef struct _REG_CREATE_KEY_INFORMATION * PREG_OPEN_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION * PREG_POST_CREATE_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION * PREG_POST_OPEN_KEY_INFORMATION
typedef struct _REG_POST_OPERATION_INFORMATION* PREG_POST_OPERATION_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION* PREG_PRE_CREATE_KEY_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION * PREG_PRE_OPEN_KEY_INFORMATION
typedef struct _REG_QUERY_KEY_INFORMATION * PREG_QUERY_KEY_INFORMATION
typedef struct _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION * PREG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION
typedef struct _REG_QUERY_VALUE_KEY_INFORMATION * PREG_QUERY_VALUE_KEY_INFORMATION
typedef struct _REG_RENAME_KEY_INFORMATION * PREG_RENAME_KEY_INFORMATION
typedef struct _REG_SET_INFORMATION_KEY_INFORMATION * PREG_SET_INFORMATION_KEY_INFORMATION
typedef struct _REG_SET_VALUE_KEY_INFORMATION * PREG_SET_VALUE_KEY_INFORMATION
typedef struct _REG_CREATE_KEY_INFORMATION REG_CREATE_KEY_INFORMATION
typedef struct _REG_DELETE_KEY_INFORMATION REG_DELETE_KEY_INFORMATION
typedef struct _REG_DELETE_VALUE_KEY_INFORMATION REG_DELETE_VALUE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_KEY_INFORMATION REG_ENUMERATE_KEY_INFORMATION
typedef struct _REG_ENUMERATE_VALUE_KEY_INFORMATION REG_ENUMERATE_VALUE_KEY_INFORMATION
typedef struct _REG_KEY_HANDLE_CLOSE_INFORMATION REG_KEY_HANDLE_CLOSE_INFORMATION
typedef enum _REG_NOTIFY_CLASS REG_NOTIFY_CLASS
typedef struct _REG_CREATE_KEY_INFORMATION REG_OPEN_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION REG_POST_CREATE_KEY_INFORMATION
typedef struct _REG_POST_CREATE_KEY_INFORMATION REG_POST_OPEN_KEY_INFORMATION
typedef struct _REG_POST_OPERATION_INFORMATION REG_POST_OPERATION_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION REG_PRE_CREATE_KEY_INFORMATION
typedef struct _REG_PRE_CREATE_KEY_INFORMATION REG_PRE_OPEN_KEY_INFORMATION
typedef struct _REG_QUERY_KEY_INFORMATION REG_QUERY_KEY_INFORMATION
typedef struct _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION
typedef struct _REG_QUERY_VALUE_KEY_INFORMATION REG_QUERY_VALUE_KEY_INFORMATION
typedef struct _REG_RENAME_KEY_INFORMATION REG_RENAME_KEY_INFORMATION
typedef struct _REG_SET_INFORMATION_KEY_INFORMATION REG_SET_INFORMATION_KEY_INFORMATION
typedef struct _REG_SET_VALUE_KEY_INFORMATION REG_SET_VALUE_KEY_INFORMATION
Enumeration Type Documentation
enum _REG_NOTIFY_CLASS
Enumerator
RegNtDeleteKey
RegNtPreDeleteKey
RegNtSetValueKey
RegNtPreSetValueKey
RegNtDeleteValueKey
RegNtPreDeleteValueKey
RegNtSetInformationKey
RegNtPreSetInformationKey
RegNtRenameKey
RegNtPreRenameKey
RegNtEnumerateKey
RegNtPreEnumerateKey
RegNtEnumerateValueKey
RegNtPreEnumerateValueKey
RegNtQueryKey
RegNtPreQueryKey
RegNtQueryValueKey
RegNtPreQueryValueKey
RegNtQueryMultipleValueKey
RegNtPreQueryMultipleValueKey
RegNtPreCreateKey
RegNtPostCreateKey
RegNtPreOpenKey
RegNtPostOpenKey
RegNtKeyHandleClose
RegNtPreKeyHandleClose
RegNtPostDeleteKey
RegNtPostSetValueKey
RegNtPostDeleteValueKey
RegNtPostSetInformationKey
RegNtPostRenameKey
RegNtPostEnumerateKey
RegNtPostEnumerateValueKey
RegNtPostQueryKey
RegNtPostQueryValueKey
RegNtPostQueryMultipleValueKey
RegNtPostKeyHandleClose
RegNtPreCreateKeyEx
RegNtPostCreateKeyEx
RegNtPreOpenKeyEx
RegNtPostOpenKeyEx
Definition at line 233 of file cm.h.
Function Documentation
VOID CmBootLastKnownGood (__in ULONG ErrorLevel)
Definition at line 3331 of file cmsysini.c.
References BAD_LAST_KNOWN_GOOD, CM_BUGCHECK, CM_PAGED_CODE, CmFirstTime, CmIsLastKnownGoodBoot(), CRITICAL_SERVICE_FAILED, CriticalError, ESUCCESS, HalRebootRoutine, HalReturnToFirmware(), HalSetEnvironmentVariable(), IgnoreError, NormalError, SET_ENV_VAR_FAILED, SevereError, Status, and TRUE.
Referenced by IopLoadDriver().
VOID CmGetSystemControlValues (__in PVOID SystemHiveBuffer, __inout PCM_SYSTEM_CONTROL_VECTOR ControlVector)
Definition at line 57 of file cmcontrl.c.
References ASSERT, BAD_SYSTEM_CONFIG_INFO, BAD_SYSTEM_CONTROL_VALUES, CM_BUGCHECK, CM_KEY_VALUE_SMALL, CmDefaultLanguageId, CmDefaultLanguageIdLength, CmDefaultLanguageIdType, CmInstallUILanguageId, CmInstallUILanguageIdLength, CmInstallUILanguageIdType, CmpConvertLangId(), CmpFindControlSet(), CmpFindSubKeyByName(), CmpFindValueByName(), CmpGetValueData(), CmpInitHiveViewList(), CmpInitSecurityCache(), CmpIsHKeyValueSmall, CmpWalkPath(), _CM_KEY_VALUE::DataLength, ExFreePool(), FALSE, HCELL_NIL, HFILE_TYPE_PRIMARY, HINIT_FLAT, HIVE_VOLATILE, HvGetCell, HvInitializeHive(), HvReleaseCell, LANGIDFROMLCID, NT_SUCCESS, NULL, PsDefaultSystemLocaleId, PsDefaultThreadLocaleId, PsDefaultUILanguageId, PsInstallUILanguageId, REG_SZ, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, TRUE, and _CM_KEY_VALUE::Type.
PHANDLE CmGetSystemDriverList (VOID)
Definition at line 1747 of file cmsysini.c.
References CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpFindControlSet(), CmpFindDrivers(), CmpFreeDriverList(), CmpLockRegistryExclusive(), CmpResolveDriverDependencies(), CmpSortDriverList(), CmpUnlockRegistry(), CONFIG_INITIALIZATION_FAILED, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DriverEntry(), ExAllocatePool, _LIST_ENTRY::Flink, Handle, HCELL_NIL, Hive, INIT_SYSTEM_DRIVER_LIST, InitializeListHead(), InitializeObjectAttributes, KernelMode, KEY_QUERY_VALUE, KEY_READ, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NonPagedPool, NT_SUCCESS, NtClose(), NtOpenKey(), NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByHandle, _BOOT_DRIVER_LIST_ENTRY::RegistryPath, RtlInitUnicodeString(), Status, and SystemLoad.
BOOLEAN CmInitSystem1 (__in PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 311 of file cmsysini.c.
References _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_PAGED_CODE, CM_TRACK_QUOTA_START, _HIVE_LIST_ENTRY::CmHive, CmKdPrintEx, CML_BUGCHECK, CML_INIT, CmpAddToHiveFileList(), CmpComputeGlobalQuotaAllowed(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreateRegistryRoot(), CmpHiveListHeadLock, CmpHiveRootSecurityDescriptor(), CmpInitCallback(), CmpInitCmPrivateAlloc(), CmpInitCmPrivateDelayAlloc(), CmpInitDelayDerefKCBEngine(), CmpInitializeCache(), CmpInitializeHardwareConfiguration(), CmpInitializeHive(), CmpInitializeMachineDependentConfiguration(), CmpInitializeRegistryNames(), CmpInitializeSystemHive(), CmpLinkHiveToMaster(), CmpLoadHiveLock, CmpLockRegistryExclusive(), CmpMiniNTBoot, CmpNoMasterCreates, CmpSetNetworkValue(), CmpSetSystemValues(), CmpShareSystemHives, CmpStashBuffer, CmpStashBufferLock, CmpStashBufferSize, CmpUnlockRegistry(), CmRegistryMachineHardwareName, CmRegistryMachineName, CmRegistryUserName, CONFIG_INITIALIZATION_FAILED, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, ExAllocatePoolWithTag, ExFreePool(), ExInitializePushLock(), ExInitializeResourceLite(), HFILE_TYPE_PRIMARY, HINIT_CREATE, HIVE_VOLATILE, INIT_SYSTEM1, InitializeListHead(), InitializeObjectAttributes, InitIsWinPEMode, KeInitializeGuardedMutex(), KEY_READ, KEY_WRITE, NT_SUCCESS, NtClose(), NtCreateKey(), NULL, OBJ_CASE_INSENSITIVE, PAGE_SIZE, PagedPool, _EPROCESS::Pcb, PsGetCurrentProcess(), RTL_SIZEOF_THROUGH_FIELD, STATUS_SUCCESS, and TRUE.
Referenced by Phase1InitializationDiscard().
BOOLEAN CmInitSystem2 (VOID)
BOOLEAN CmIsLastKnownGoodBoot (VOID)
Definition at line 3416 of file cmsysini.c.
References ASSERT, CM_PAGED_CODE, CmKdPrintEx, CML_INIT, DPFLTR_CONFIG_ID, FALSE, NT_SUCCESS, NULL, REG_DWORD, REG_NONE, RTL_QUERY_REGISTRY_DIRECT, RTL_REGISTRY_ABSOLUTE, RtlQueryRegistryValues(), Status, and TRUE.
Referenced by CmBootLastKnownGood().
VOID CmNotifyRunDown (__in PETHREAD Thread)
Definition at line 1023 of file cmnotify.c.
References _CM_ASYNC_USER_POST_BLOCK::Apc, APC_LEVEL, ASSERT, _CM_POST_BLOCK_UNION::AsyncUser, _CM_POST_BLOCK::CancelPostList, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_FLOW, CmpCancelSlavePost(), CmpCheckIoStatusPointer, CmpClearListEntry, CmpFreePostBlock(), CmpFreeSlavePost(), CmpIsListEmpty, CmpLockRegistry(), CmpRemoveEntryList, CmpSetIoStatus, CmpUnlockRegistry(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InsertTailList(), _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, IsListEmpty, IsMasterPostBlock, KeLowerIrql, KeRaiseIrql, KeRemoveQueueApc(), KeSetEvent(), LOCK_POST_LIST, NOTHING, _CM_POST_BLOCK::NotifyList, NULL, ObDereferenceObject(), PostAsyncUser, PostBlockType, PsGetCurrentProcess(), RemoveHeadList(), STATUS_NOTIFY_CLEANUP, _CM_POST_BLOCK::ThreadList, TRUE, _CM_POST_BLOCK::u, UNLOCK_POST_LIST, and _CM_ASYNC_USER_POST_BLOCK::UserEvent.
Referenced by PspExitThread().
NTSTATUS CmPrefetchHivePages (__in PUNICODE_STRING FullHivePath, __inout PREAD_LIST ReadList)
Definition at line 1780 of file cmmapvw.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmpHiveListHead, CmpLockHiveListShared, CmpLockRegistry(), CmpUnlockHiveList, CmpUnlockRegistry(), CONTAINING_RECORD, FALSE, _CMHIVE::FileFullPath, _CMHIVE::FileObject, _LIST_ENTRY::Flink, MmDisableModifiedWriteOfSection(), MmPrefetchPages(), NULL, RtlCompareUnicodeString(), _FILE_OBJECT::SectionObjectPointer, Status, STATUS_INVALID_PARAMETER, and TRUE.
VOID CmQueryRegistryQuotaInformation (__inout PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
Definition at line 129 of file cmgquota.c.
References CmpGlobalQuota, CmpGlobalQuotaUsed, and MmSizeOfPagedPoolInBytes.
Referenced by NtQuerySystemInformation().
NTSTATUS CmRegisterCallback (__in PEX_CALLBACK_FUNCTION Function, __in_opt PVOID Context, __out PLARGE_INTEGER Cookie)
Definition at line 70 of file cmhook.c.
References _CM_CALLBACK_CONTEXT_BLOCK::CallerContext, CM_MAX_CALLBACKS, CmpCallBackCount, _CM_CALLBACK_CONTEXT_BLOCK::Cookie, ExAllocateCallBack(), ExAllocatePoolWithTag, ExCompareExchangeCallBack(), ExFreeCallBack(), ExFreePool(), ExInitializePushLock(), InitializeListHead(), InterlockedExchangeAdd(), KeQuerySystemTime(), NULL, PAGED_CODE, PagedPool, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _CM_CALLBACK_CONTEXT_BLOCK::ThreadListHead, and _CM_CALLBACK_CONTEXT_BLOCK::ThreadListLock.
ULONG CmRegisterSystemHiveLimitCallback (__in ULONG Low, __in ULONG High, __in PVOID Ref, __in PCM_HYSTERESIS_CALLBACK Callback)
Definition at line 616 of file cmgquota.c.
References _HHIVE::BaseBlock, CM_SYSTEM_HIVE_LIMIT_SIZE, _HIVE_LIST_ENTRY::CmHive, CmpSystemHiveHysteresisCallback, CmpSystemHiveHysteresisContext, CmpSystemHiveHysteresisHigh, CmpSystemHiveHysteresisHighSeen, CmpSystemHiveHysteresisLow, CmpSystemHiveHysteresisLowSeen, FALSE, HBLOCK_SIZE, _CMHIVE::Hive, _HBASE_BLOCK::Length, NULL, PAGED_CODE, SYSTEM_HIVE_INDEX, and TRUE.
VOID CmSetLazyFlushState (__in BOOLEAN Enable)
Definition at line 765 of file cmworker.c.
References CM_PAGED_CODE, CmpDontGrowLogFile, and CmpHoldLazyFlush.
VOID CmSetRegistryQuotaInformation (__in PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
Definition at line 158 of file cmgquota.c.
References CM_MINIMUM_GLOBAL_QUOTA, CM_REGISTRY_WARNING_LEVEL, CM_WRAP_LIMIT, CmpGlobalQuota, CmpGlobalQuotaAllowed, and CmpGlobalQuotaWarning.
Referenced by NtSetSystemInformation().
NTSTATUS CmSetTraceNotifyRoutine (__in_opt PCM_TRACE_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
Definition at line 41 of file cmwmi.c.
References CmpTraceRoutine, CmpWmiDumpKcbTable(), NULL, and STATUS_SUCCESS.
Referenced by WmipDisableKernelTrace(), and WmipEnableKernelTrace().
VOID CmShutdownSystem (VOID)
Definition at line 249 of file cmdown.c.
References CM_PAGED_CODE, CmCompressKey(), CmFirstTime, CmpCmdHiveClose(), CmpDestroyHiveViewList(), CmpDoFlushAll(), CmpDropFileObjectForHive(), CmpFreeAllMemory(), CmpHiveListHead, CmpLockRegistryExclusive(), CmpRegistryRootHandle, CmpShutdownWorkers(), CmpUnJoinClassOfTrust, CmpUnlockRegistry(), CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _CMHIVE::Hive, HvShutdownComplete, KernelMode, KEY_READ, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), ObReferenceObjectByHandle, PO_CLEAN_SHUTDOWN_REGISTRY, PoCleanShutdownEnabled(), Status, SYSTEM_HIVE_INDEX, and TRUE.
NTSTATUS CmUnRegisterCallback (__in LARGE_INTEGER Cookie)
Definition at line 137 of file cmhook.c.
References CM_MAX_CALLBACKS, CmpCallBackCount, _CM_CALLBACK_CONTEXT_BLOCK::Cookie, ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExFreePool(), ExGetCallBackBlockContext(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedExchangeAdd(), NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Variable Documentation
UNICODE_STRING CmClassName[]
Definition at line 45 of file cmdat.c.
Referenced by CmpInitializeRegistryNames().
const PWSTR CmClassString[]
Definition at line 47 of file cmdat.c.
Referenced by CmpInitializeRegistryNames().
UNICODE_STRING CmRegistryMachineHardwareDescriptionName
Definition at line 203 of file cmdat.c.
Referenced by CmpInitializeHardwareConfiguration().
UNICODE_STRING CmRegistryMachineHardwareDescriptionSystemName
Definition at line 204 of file cmdat.c.
Referenced by IopInitializeBuiltinDriver(), IopLoadDriver(), and KeSetup80387OrEmulate().
UNICODE_STRING CmRegistryMachineHardwareDeviceMapName
Definition at line 205 of file cmdat.c.
Referenced by CmpInitializeHardwareConfiguration().
UNICODE_STRING CmRegistryMachineHardwareName
Definition at line 202 of file cmdat.c.
Referenced by CmInitSystem1().
UNICODE_STRING CmRegistryMachineHardwareOwnerMapName
Definition at line 207 of file cmdat.c.
UNICODE_STRING CmRegistryMachineHardwareResourceMapName
Definition at line 206 of file cmdat.c.
UNICODE_STRING CmRegistryMachineName
Definition at line 201 of file cmdat.c.
Referenced by CmInitSystem1().
UNICODE_STRING CmRegistryMachineSystemCurrentControlSet
Definition at line 209 of file cmdat.c.
Referenced by CmpInterlockedFunction(), and CmpSaveBootControlSet().
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlBootLog
Definition at line 217 of file cmdat.c.
Referenced by CmpInitializeRegistryNames(), IopBootLog(), and IopCopyBootLogRegistryToFile().
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlClass
Definition at line 214 of file cmdat.c.
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlSafeBoot
Definition at line 215 of file cmdat.c.
Referenced by CmpInitializeRegistryNames(), and IopSafebootDriverLoad().
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetControlSessionManagerMemoryManagement
Definition at line 216 of file cmdat.c.
Referenced by CmpInitializeRegistryNames().
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetEnumName
Definition at line 210 of file cmdat.c.
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetEnumRootName
Definition at line 211 of file cmdat.c.
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetHardwareProfilesCurrent
Definition at line 213 of file cmdat.c.
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetServices
Definition at line 212 of file cmdat.c.
Referenced by MmCallDllInitialize().
UNICODE_STRING CmRegistryMachineSystemCurrentControlSetServicesEventLog
Definition at line 218 of file cmdat.c.
Referenced by CmpInitializeRegistryNames(), and IoInitSystem().
UNICODE_STRING CmRegistryMachineSystemName
Definition at line 208 of file cmdat.c.
Referenced by CmpInitializeSystemHive(), and IopStoreSystemPartitionInformation().
UNICODE_STRING CmRegistryRootName
Definition at line 200 of file cmdat.c.
Referenced by CmpCreateRegistryRoot().
UNICODE_STRING CmRegistryUserName
Definition at line 219 of file cmdat.c.
Referenced by CmInitSystem1().
UNICODE_STRING CmTypeName[]
Definition at line 87 of file cmdat.c.
Referenced by CmpInitializeRegistryNames(), CmpInitializeRegistryNode(), and KeSetup80387OrEmulate().
const PWSTR CmTypeString[]
Definition at line 99 of file cmdat.c.
Referenced by CmpInitializeRegistryNames().