Windows Research Kernel v1.2: C:/Windows Research Kernel/se/tokenqry.c File Reference
tokenqry.c File Reference
#include "pch.h"
Functions
NTSTATUS NtQueryInformationToken (__in HANDLE TokenHandle, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __out_bcount_part_opt(TokenInformationLength,*ReturnLength) PVOID TokenInformation, __in ULONG TokenInformationLength, __out PULONG ReturnLength)
NTSTATUS SeQueryAuthenticationIdToken (__in PACCESS_TOKEN Token, __out PLUID AuthenticationId)
NTSTATUS SeQueryInformationToken (__in PACCESS_TOKEN AccessToken, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __deref_out PVOID *TokenInformation)
NTSTATUS SeQuerySessionIdToken (__in PACCESS_TOKEN Token, __out PULONG SessionId)
Function Documentation
NTSTATUS NtQueryInformationToken (__in HANDLE TokenHandle, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __out_bcount_part_opt(TokenInformationLength,*ReturnLength) PVOID TokenInformation, __in ULONG TokenInformationLength, __out PULONG ReturnLength)
Definition at line 34 of file tokenqry.c.
References _SEP_AUDIT_POLICY_CATEGORIES::AccountLogon, _SEP_AUDIT_POLICY_CATEGORIES::AccountManagement, _ACL::AclSize, ANYSIZE_ARRAY, ARGUMENT_PRESENT, ASSERT, AuditCategoryAccountLogon, AuditCategoryAccountManagement, AuditCategoryDetailedTracking, AuditCategoryDirectoryServiceAccess, AuditCategoryLogon, AuditCategoryObjectAccess, AuditCategoryPolicyChange, AuditCategoryPrivilegeUse, AuditCategorySystem, _TOKEN::AuthenticationId, _TOKEN_GROUPS_AND_PRIVILEGES::AuthenticationId, _TOKEN_STATISTICS::AuthenticationId, _TOKEN_AUDIT_POLICY_ELEMENT::Category, _TOKEN::DefaultDacl, _TOKEN_DEFAULT_DACL::DefaultDacl, _TOKEN::DefaultOwnerIndex, _SEP_AUDIT_POLICY_CATEGORIES::DetailedTracking, _SEP_AUDIT_POLICY_CATEGORIES::DirectoryServiceAccess, _TOKEN_STATISTICS::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN_STATISTICS::DynamicCharged, except, EXCEPTION_EXECUTE_HANDLER, _TOKEN::ExpirationTime, _TOKEN_STATISTICS::ExpirationTime, FALSE, _TOKEN_GROUPS::GroupCount, _TOKEN_STATISTICS::GroupCount, _TOKEN_GROUPS::Groups, _TOKEN::ImpersonationLevel, _TOKEN_STATISTICS::ImpersonationLevel, Index, KeGetPreviousMode, KernelMode, _SEP_AUDIT_POLICY_CATEGORIES::Logon, _TOKEN::ModifiedId, _TOKEN_STATISTICS::ModifiedId, NT_SUCCESS, NULL, ObDereferenceObject(), _SEP_AUDIT_POLICY_CATEGORIES::ObjectAccess, ObReferenceObjectByHandle, _TOKEN_ORIGIN::OriginatingLogonSession, _SEP_AUDIT_POLICY::Overlay, _TOKEN_OWNER::Owner, PAGED_CODE, PER_USER_AUDITING_POLICY_SIZE_BY_COUNT, _TOKEN_AUDIT_POLICY::Policy, _SEP_AUDIT_POLICY_CATEGORIES::PolicyChange, _TOKEN_AUDIT_POLICY::PolicyCount, _SEP_AUDIT_POLICY::PolicyElements, _TOKEN_AUDIT_POLICY_ELEMENT::PolicyMask, _TOKEN::PrimaryGroup, _TOKEN_PRIMARY_GROUP::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_GROUPS_AND_PRIVILEGES::PrivilegeCount, _TOKEN_STATISTICS::PrivilegeCount, _TOKEN_GROUPS_AND_PRIVILEGES::PrivilegeLength, _TOKEN::Privileges, _TOKEN_PRIVILEGES::Privileges, _TOKEN_GROUPS_AND_PRIVILEGES::Privileges, _SEP_AUDIT_POLICY_CATEGORIES::PrivilegeUse, ProbeForWrite(), ProbeForWriteUlong, _TOKEN::RestrictedSidCount, _TOKEN_GROUPS_AND_PRIVILEGES::RestrictedSidCount, _TOKEN_GROUPS_AND_PRIVILEGES::RestrictedSidLength, _TOKEN::RestrictedSids, _TOKEN_GROUPS_AND_PRIVILEGES::RestrictedSids, RtlCopyLuidAndAttributesArray(), RtlCopyMemory, RtlCopySid(), RtlCopySidAndAttributesArray(), SeLengthSid, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SeQuerySessionIdToken(), SeSecurityPrivilege, SeSinglePrivilegeCheck(), SeTokenIsRestricted(), SeTokenObjectType, _SID_AND_ATTRIBUTES::Sid, _TOKEN_GROUPS_AND_PRIVILEGES::SidCount, _TOKEN_GROUPS_AND_PRIVILEGES::SidLength, _TOKEN_GROUPS_AND_PRIVILEGES::Sids, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_INFO_CLASS, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _SEP_AUDIT_POLICY_CATEGORIES::System, TOKEN_QUERY, TOKEN_QUERY_SOURCE, TOKEN_SANDBOX_INERT, TokenAuditPolicy, TokenDefaultDacl, TokenGroups, TokenGroupsAndPrivileges, _TOKEN::TokenId, _TOKEN_STATISTICS::TokenId, TokenImpersonation, TokenImpersonationLevel, TokenOrigin, TokenOwner, TokenPrimaryGroup, TokenPrivileges, TokenRestrictedSids, TokenSandBoxInert, TokenSessionId, _TOKEN::TokenSource, TokenSource, TokenStatistics, _TOKEN::TokenType, TokenType, _TOKEN_STATISTICS::TokenType, TokenUser, TRUE, _TOKEN_USER::User, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
NTSTATUS SeQueryAuthenticationIdToken (__in PACCESS_TOKEN Token, __out PLUID AuthenticationId)
Definition at line 1623 of file tokenqry.c.
References PAGED_CODE, and STATUS_SUCCESS.
Referenced by NtSetUuidSeed(), ObpReferenceDeviceMap(), and ObpSetCurrentProcessDeviceMap().
NTSTATUS SeQueryInformationToken (__in PACCESS_TOKEN AccessToken, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __deref_out PVOID * TokenInformation)
Definition at line 1664 of file tokenqry.c.
References _ACL::AclSize, ANYSIZE_ARRAY, ARGUMENT_PRESENT, ASSERT, _TOKEN::AuthenticationId, _TOKEN_STATISTICS::AuthenticationId, _TOKEN::DefaultDacl, _TOKEN_DEFAULT_DACL::DefaultDacl, _TOKEN::DefaultOwnerIndex, _TOKEN::DynamicAvailable, _TOKEN_STATISTICS::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN_STATISTICS::DynamicCharged, ExAllocatePool, _TOKEN::ExpirationTime, _TOKEN_STATISTICS::ExpirationTime, _TOKEN_GROUPS::GroupCount, _TOKEN_STATISTICS::GroupCount, _TOKEN_GROUPS::Groups, _TOKEN::ImpersonationLevel, _TOKEN_STATISTICS::ImpersonationLevel, Index, _TOKEN::ModifiedId, _TOKEN_STATISTICS::ModifiedId, NT_SUCCESS, NULL, _TOKEN_OWNER::Owner, PAGED_CODE, PagedPool, _TOKEN::PrimaryGroup, _TOKEN_PRIMARY_GROUP::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_STATISTICS::PrivilegeCount, _TOKEN::Privileges, _TOKEN_PRIVILEGES::Privileges, RtlCopyLuidAndAttributesArray(), RtlCopyMemory, RtlCopySid(), RtlCopySidAndAttributesArray(), SeLengthSid, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SeQuerySessionIdToken(), _SID_AND_ATTRIBUTES::Sid, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, TokenDefaultDacl, TokenGroups, _TOKEN::TokenId, _TOKEN_STATISTICS::TokenId, TokenImpersonation, TokenImpersonationLevel, TokenOwner, TokenPrimaryGroup, TokenPrivileges, TokenSessionId, _TOKEN::TokenSource, TokenSource, TokenStatistics, _TOKEN::TokenType, TokenType, _TOKEN_STATISTICS::TokenType, TokenUser, _TOKEN_USER::User, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
Referenced by NtSecureConnectPort(), and WmiTraceProcess().
NTSTATUS SeQuerySessionIdToken (__in PACCESS_TOKEN Token, __out PULONG SessionId)
Definition at line 2251 of file tokenqry.c.
References PAGED_CODE, SepAcquireTokenReadLock, SepReleaseTokenReadLock, and STATUS_SUCCESS.
Referenced by NtQueryInformationToken(), and SeQueryInformationToken().