Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/mminit.c File Reference
mminit.c File Reference
#include "mi.h"
Data Structures
struct _REGISTRY_MEMORY_RUN
Macros
#define CONSTANT_UNICODE_STRING(s) { sizeof(s) - sizeof(WCHAR), sizeof(s), s }
#define MM_ALLOCATION_FRAGMENT (64 * 1024)
#define MM_ALLOCATION_FRAGMENT_MAX (2 * 1024 * 1024)
#define MM_DEFAULT_IO_LOCK_LIMIT (2 * 1024 * 1024)
#define MM_MB_MAPPED_BY_PDE (MM_VA_MAPPED_BY_PDE / (1024*1024))
#define MM_MEDIUM_SYSTEM ((19*1024*1024) / 4096)
#define MM_MIN_INITIAL_PAGED_POOL ((32*1024*1024) >> PAGE_SHIFT)
#define MM_SMALL_SYSTEM ((13*1024*1024) / 4096)
Typedefs
typedef struct _REGISTRY_MEMORY_RUN * PREGISTRY_MEMORY_RUN
typedef struct _REGISTRY_MEMORY_RUN REGISTRY_MEMORY_RUN
Functions
__declspec (noinline)
VOID MiAddHalIoMappings (VOID)
VOID MiBuildPagedPool ()
VOID MiBuildPagedPool (VOID)
NTSTATUS MiCreateMemoryEvent (IN PUNICODE_STRING EventName, OUT PKEVENT *Event)
VOID MiEnablePagingOfDriverAtInit (IN PMMPTE PointerPte, IN PMMPTE LastPte)
VOID MiEnablePagingTheExecutive (VOID)
VOID MiFindInitializationCode (OUT PVOID *StartVa, OUT PVOID *EndVa)
VOID MiFreeInitializationCode (IN PVOID StartVa, IN PVOID EndVa)
VOID MiInitializeCacheOverrides (VOID)
LOGICAL MiInitializeMemoryEvents (VOID)
VOID MiInitializeNonPagedPoolThresholds (VOID)
VOID MiInitializePfnTracing (VOID)
VOID MiMapBBTMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID MiMemorySan (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID MiNotifyMemoryEvents (VOID)
PFN_NUMBER MiPagesInLoaderBlock (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PBOOLEAN IncludeType)
VOID MiWriteProtectSystemImage (IN PVOID DllBase)
VOID MmFreeBootRegistry (VOID)
VOID MmFreeLoaderBlock (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
PPHYSICAL_MEMORY_DESCRIPTOR MmInitializeMemoryLimits (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PBOOLEAN IncludeType, IN OUT PPHYSICAL_MEMORY_DESCRIPTOR InputMemory OPTIONAL)
BOOLEAN MmInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTKERNELAPI BOOLEAN MmIsThisAnNtAsSystem (VOID)
MM_SYSTEMSIZE MmQuerySystemSize (VOID)
NTKERNELAPI VOID FASTCALL MmSetPageFaultNotifyRoutine (PPAGE_FAULT_NOTIFY_ROUTINE NotifyRoutine)
Variables
PVOID BBTBuffer
PFN_COUNT BBTPagesToReserve
POBJECT_TYPE ExEventObjectType
PVOID ExPageLockHandle
BOOLEAN MiAllMainMemoryMustBeCached = FALSE
PREGISTRY_MEMORY_RUN MiBootRegistryRuns
PFN_NUMBER MiExpansionPoolPagesInitialCharge
ULONG MiFullyInitialized
PKEVENT MiHighMemoryEvent
PKEVENT MiHighNonPagedPoolEvent
PFN_NUMBER MiHighNonPagedPoolThreshold
PKEVENT MiHighPagedPoolEvent
PFN_NUMBER MiHighPagedPoolThreshold
PKEVENT MiLowMemoryEvent
PKEVENT MiLowNonPagedPoolEvent
PFN_NUMBER MiLowNonPagedPoolThreshold
PKEVENT MiLowPagedPoolEvent
PFN_NUMBER MiLowPagedPoolThreshold
KEVENT MiMappedPagesTooOldEvent
LARGE_INTEGER MiModifiedPageLife
KTIMER MiModifiedPageWriterTimer
KDPC MiModifiedPageWriterTimerDpc
RTL_BITMAP MiPfnBitMap
LOGICAL MiSafeBooted = FALSE
PMMPTE MiSpecialPoolFirstPte
KEVENT MiTempEvent
BOOLEAN MiTimerPending = FALSE
LONG MiTrimInProgressCount
ULONG MiVerifyAllDrivers
SIZE_T MmAllocationFragment
ULONG MmAllocationPreference
ULONG MmCodeClusterSize
ULONG MmDataClusterSize
ULONG MmEnforceWriteProtection
PFN_NUMBER MmFreedExpansionPoolMaximum
PFN_NUMBER MmHighMemoryThreshold
ULONG MmInPageSupportMinimum
ULONG MmKeepBootRegistry = 0
ULONG MmLargeSystemCache
LIST_ENTRY MmLoadedUserImageList
PFN_NUMBER MmLowMemoryThreshold
WSLE_NUMBER MmMaximumWorkingSetSize
ULONG MmModifiedPageLifeInSeconds = 300
ULONG MmPagedPoolCommit
LOGICAL MmPagedPoolMaximumDesired = FALSE
KGUARDED_MUTEX MmPagedPoolMutex
PPAGE_FAULT_NOTIFY_ROUTINE MmPageFaultNotifyRoutine
PPHYSICAL_MEMORY_DESCRIPTOR MmPhysicalMemoryBlock
ULONG MmProductType
LIST_ENTRY MmProtectedPteList
KSPIN_LOCK MmProtectedPteLock
PFN_NUMBER MmResidentAvailableAtInit
PMMPTE MmSharedUserDataPte
ULONG_PTR MmSubsectionBase
ULONG_PTR MmSubsectionTopPage
PFN_NUMBER MmSystemPageDirectory [PD_PER_SYSTEM]
PMMPTE MmSystemPagePtes
MM_SYSTEMSIZE MmSystemSize
ULONG MmTotalSystemCodePages
Macro Definition Documentation
#define CONSTANT_UNICODE_STRING (s) { sizeof(s) - sizeof(WCHAR), sizeof(s), s }
Definition at line 4835 of file mminit.c.
Referenced by MiInitializeMemoryEvents().
#define MM_ALLOCATION_FRAGMENT (64 * 1024)
Definition at line 235 of file mminit.c.
Referenced by MmInitSystem().
#define MM_ALLOCATION_FRAGMENT_MAX (2 * 1024 * 1024)
Definition at line 236 of file mminit.c.
Referenced by MmInitSystem().
#define MM_DEFAULT_IO_LOCK_LIMIT (2 * 1024 * 1024)
Definition at line 205 of file mminit.c.
#define MM_MB_MAPPED_BY_PDE (MM_VA_MAPPED_BY_PDE / (1024*1024))
Referenced by MmInitSystem().
#define MM_MEDIUM_SYSTEM ((19*1024*1024) / 4096)
Definition at line 201 of file mminit.c.
Referenced by MmInitSystem().
#define MM_MIN_INITIAL_PAGED_POOL ((32*1024*1024) >> PAGE_SHIFT)
Definition at line 203 of file mminit.c.
Referenced by MiBuildPagedPool().
#define MM_SMALL_SYSTEM ((13*1024*1024) / 4096)
Definition at line 199 of file mminit.c.
Referenced by MmInitSystem().
Typedef Documentation
typedef struct _REGISTRY_MEMORY_RUN * PREGISTRY_MEMORY_RUN
typedef struct _REGISTRY_MEMORY_RUN REGISTRY_MEMORY_RUN
Function Documentation
__declspec (noinline)
Definition at line 5325 of file mminit.c.
VOID MiAddHalIoMappings (VOID)
Definition at line 5216 of file mminit.c.
References ASSERT, _MMPTE_HARDWARE::CacheDisable, FALSE, _MMPTE::Hard, _MMPTE_HARDWARE::LargePage, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_CACHING_DISABLED, MI_IS_PFN(), MiCached, MiGetPdeAddress, MiGetPdeOffset, MiGetPteAddress, MiGetPteOffset, MiInsertIoSpaceMap(), MiNonCached, MiWriteCombined, MiWriteCombiningPtes, MM_VA_MAPPED_BY_PDE, PAGE_SIZE, PDE_PER_PAGE, PTE_PER_PAGE, TRUE, _MMPTE::u, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::WriteThrough.
Referenced by MmInitSystem().
VOID MiBuildPagedPool ()
Referenced by MmInitSystem().
VOID MiBuildPagedPool (VOID)
Definition at line 3301 of file mminit.c.
References ASSERT, ASSERT64, BYTES_TO_PAGES, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MM_PAGED_POOL_INFO::FirstPteForPagedPool, _MMPTE::Hard, InitializePool(), InterlockedExchangeAddSizeT, _MM_PAGED_POOL_INFO::LastPteForPagedPool, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiCreateBitMap, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiHighPagedPoolThreshold, MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), MiInitializeSpecialPool(), MiInitializeSystemSpaceMap(), MiIssueNoPtesBugcheck(), MiLowPagedPoolThreshold, MiRemoveAnyPage(), MiRemoveZeroPage(), MiReserveSystemPtes(), MiSystemViewStart, MiZeroMemoryPte, MM_DEMAND_ZERO_WRITE_PTE, MM_MAX_PAGED_POOL, MM_MIN_INITIAL_PAGED_POOL, MM_MINIMUM_PAGED_POOL_NTAS, MM_PAGED_POOL_LOCKED_DOWN, MM_VA_MAPPED_BY_PDE, MmAvailablePages, MmDisablePagingExecutive, MmIsThisAnNtAsSystem(), MmMaximumNonPagedPoolInBytes, MmNonPagedSystemStart, MmNumberOfPhysicalPages, MmPagedPoolCommit, MmPagedPoolEnd, MmPagedPoolInfo, MmPagedPoolMaximumDesired, MmPagedPoolStart, MmResidentAvailablePages, MmSizeOfPagedPoolInBytes, MmSizeOfPagedPoolInPages, MmSystemPageDirectory, MmSystemViewSize, MmTotalCommittedPages, MmVerifyDriverBufferLength, _MM_PAGED_POOL_INFO::NextPdeForPagedPoolExpansion, NonPagedPool, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, PagedPool, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_PAGED_POOL_INFO::PagedPoolCommit, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PDE_PER_PAGE, PTE_PER_PAGE, RtlCheckBit, RtlClearAllBits(), RtlClearBits(), RtlSetAllBits(), SystemPteSpace, TRUE, _MMPTE::u, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, ValidKernelPde, ValidKernelPte, and VerifierLargePagedPoolMap.
NTSTATUS MiCreateMemoryEvent (IN PUNICODE_STRING EventName, OUT PKEVENT * Event)
Definition at line 5029 of file mminit.c.
References ACL_REVISION, EVENT_ALL_ACCESS, EVENT_MODIFY_STATE, EVENT_QUERY_STATE, ExAllocatePoolWithTag, ExFreePool(), FALSE, InitializeObjectAttributes, KernelMode, NotificationEvent, NT_SUCCESS, NULL, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, ObReferenceObjectByHandle, PagedPool, READ_CONTROL, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlLengthSid(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SeLocalSystemSid, SeWorldSid, Status, STATUS_INSUFFICIENT_RESOURCES, SYNCHRONIZE, TRUE, ZwClose(), and ZwCreateEvent().
Referenced by MiInitializeMemoryEvents().
VOID MiEnablePagingOfDriverAtInit (IN PMMPTE PointerPte, IN PMMPTE LastPte)
Definition at line 4668 of file mminit.c.
References ASSERT, _MMPTE::Long, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_SESSION_PTE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_WRITE_INVALID_PTE, MI_ZERO_WSINDEX, MiDecrementShareCount(), MiGetVirtualAddressMappedByPte, MM_EXECUTE, MM_KERNEL_DEMAND_ZERO_PTE, MM_MAXIMUM_FLUSH_COUNT, MM_PFN_LOCK_ASSERT, MM_RESAVAIL_FREE_PAGE_DRIVER, MmTotalSystemCodePages, NOTHING, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_SOFTWARE::Protection, _MMPFN::ShareCount, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, and _MMPFN::WsIndex.
Referenced by MiEnablePagingTheExecutive().
VOID MiEnablePagingTheExecutive (VOID)
Definition at line 4248 of file mminit.c.
References ASSERT, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, _IMAGE_NT_HEADERS::FileHeader, _LIST_ENTRY::Flink, IoRemoteBootClient, KdPitchDebugger, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeReleaseMutant(), KernelMode, KeWaitForSingleObject(), LOCK_PFN, LOCK_SYSTEM_WS, MI_IS_PHYSICAL_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MiEnablePagingOfDriverAtInit(), MiGetPdeAddress, MiGetPteAddress, MiMakeSystemAddressValidPfnSystemWs(), _IMAGE_SECTION_HEADER::Misc, MM_SYSTEM_CODE_LOCKED_DOWN, MmDisablePagingExecutive, MmSystemLoadLock, MmVerifyDriverBufferLength, _IMAGE_SECTION_HEADER::Name, NULL, _IMAGE_FILE_HEADER::NumberOfSections, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_ALIGN, PAGE_SIZE, PsGetCurrentThread(), PsLoadedModuleList, PsLoadedModuleResource, ROUND_TO_PAGES, RtlImageNtHeader(), SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_OPTIONAL_HEADER::SectionAlignment, _KLDR_DATA_TABLE_ENTRY::SectionPointer, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, _ETHREAD::Tcb, TRUE, UNLOCK_PFN, UNLOCK_SYSTEM_WS, _IMAGE_SECTION_HEADER::VirtualAddress, _IMAGE_SECTION_HEADER::VirtualSize, and WrVirtualMemory.
Referenced by MmInitSystem().
VOID MiFindInitializationCode (OUT PVOID * StartVa, OUT PVOID * EndVa)
Definition at line 3843 of file mminit.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, _IMAGE_SECTION_HEADER::Characteristics, CONTAINING_RECORD, DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, _IMAGE_NT_HEADERS::FileHeader, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, HAL_NAME, IMAGE_SCN_MEM_DISCARDABLE, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseMutant(), KERNEL_NAME, KernelMode, KeWaitForSingleObject(), LDRP_MM_LOADED, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MI_IS_PHYSICAL_ADDRESS, MiFreeInitializationCode(), _IMAGE_SECTION_HEADER::Misc, MmGetProcedureAddress, MmSystemLoadLock, MmVerifyDriverBufferLength, _IMAGE_SECTION_HEADER::Name, NULL, _IMAGE_FILE_HEADER::NumberOfSections, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_ALIGN, PAGE_SIZE, PsLoadedModuleList, PsLoadedModuleResource, ROUND_TO_PAGES, RtlEqualUnicodeString(), RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SectionAlignment, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, _IMAGE_SECTION_HEADER::VirtualSize, and WrVirtualMemory.
Referenced by MmZeroPageThread().
VOID MiFreeInitializationCode (IN PVOID StartVa, IN PVOID EndVa)
Definition at line 4165 of file mminit.c.
References ASSERT, ExPageLockHandle, FALSE, MI_CONVERT_PHYSICAL_TO_PFN, MI_DELETE_FLUSH_TB, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MiAddExpansionNonPagedPool(), MiDeleteSystemPageableVm(), MiGetPteAddress, MiNoLowMemory, MiReturnCommitment, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE1, and NULL.
Referenced by MiFindInitializationCode(), and MmZeroPageThread().
VOID MiInitializeCacheOverrides (VOID)
Definition at line 5138 of file mminit.c.
References HAL_PLATFORM_DISABLE_UC_MAIN_MEMORY, HAL_PLATFORM_DISABLE_WRITE_COMBINING, HAL_PLATFORM_ENABLE_WRITE_COMBINING_MMIO, HalPlatformInformation, HalQuerySystemInformation, _MMPTE::Long, MI_ENABLE_CACHING, MI_SET_CACHETYPE_TRANSLATION(), MiCached, MiNonCached, MM_NOCACHE, MM_WRITECOMBINE, MmNonCached, MmProtectToPteMask, MmWriteCombined, NT_SUCCESS, NumberOfBytes, _HAL_PLATFORM_INFORMATION::PlatformFlags, Status, TRUE, and _MMPTE::u.
Referenced by MmInitSystem().
LOGICAL MiInitializeMemoryEvents (VOID)
Definition at line 4882 of file mminit.c.
References ASSERT, CONSTANT_UNICODE_STRING, DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, FALSE, LOCK_PFN, MiCreateMemoryEvent(), MiInitializePoolEvents(), MiNotifyMemoryEvents(), MmHighMemoryThreshold, MmLowMemoryThreshold, MmNumberOfPhysicalPages, MmPlentyFreePages, NT_SUCCESS, PAGE_SIZE, Status, TRUE, and UNLOCK_PFN.
Referenced by MmInitSystem().
VOID MiInitializeNonPagedPoolThresholds (VOID)
Definition at line 3790 of file mminit.c.
References ASSERT, MiHighNonPagedPoolThreshold, MiLowNonPagedPoolThreshold, MmMaximumNonPagedPoolInPages, and PAGE_SHIFT.
Referenced by MiInitMachineDependent().
VOID MiInitializePfnTracing (VOID)
Definition at line 95 of file pfnlist.c.
Referenced by MmInitSystem().
VOID MiMapBBTMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 2400 of file mminit.c.
References ASSERT, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, BBTBuffer, BBTPagesToReserve, CONTAINING_RECORD, _LIST_ENTRY::Flink, _MMPTE::Hard, KeZeroPages, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderBBTMemory, _MMPTE::Long, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MI_FLUSH_ENTIRE_TB, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiReserveAlignedSystemPtes(), MM_PTE_OWNER_MASK, MM_VA_MAPPED_BY_PDE, NULL, PAGE_SHIFT, PAGE_SIZE, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _MMPTE_HARDWARE::PageFrameNumber, PTE_PER_PAGE, SystemPteSpace, _MMPTE::u, and ValidUserPte.
Referenced by MmInitSystem().
VOID MiMemorySan (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by MmInitSystem().
VOID MiNotifyMemoryEvents (VOID)
Definition at line 4838 of file mminit.c.
References FALSE, KeClearEvent(), KeReadStateEvent(), KeSetEvent(), MmAvailablePages, MmHighMemoryThreshold, and MmLowMemoryThreshold.
Referenced by MiInitializeMemoryEvents().
PFN_NUMBER MiPagesInLoaderBlock (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PBOOLEAN IncludeType)
Definition at line 2743 of file mminit.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderMaximum, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, and _MEMORY_ALLOCATION_DESCRIPTOR::PageCount.
Referenced by MmInitSystem().
VOID MiWriteProtectSystemImage (IN PVOID DllBase)
Definition at line 6689 of file sysload.c.
References ASSERT, BYTES_TO_PAGES, _IMAGE_SECTION_HEADER::Characteristics, FALSE, _IMAGE_NT_HEADERS::FileHeader, IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_READ, IMAGE_SCN_MEM_WRITE, KdPrint, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_ADDRESS, MiComputeDriverProtection(), MiGetPteAddress, _IMAGE_SECTION_HEADER::Misc, MiSetSystemCodeProtection(), NULL, _IMAGE_FILE_HEADER::NumberOfSections, _IMAGE_NT_HEADERS::OptionalHeader, PAGED_CODE, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SizeOfImage, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by MmInitSystem(), and MmLoadSystemImage().
VOID MmFreeBootRegistry (VOID)
Definition at line 2811 of file mminit.c.
References ASSERT, _REGISTRY_MEMORY_RUN::BasePage, ExFreePool(), InterlockedExchangeAddSizeT, KeGetCurrentIrql(), LOCK_PFN, MI_DELETE_FLUSH_TB, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiDeleteSystemPageableVm(), MiGetVirtualAddressMappedByPte, MmTotalCommitLimit, MmTotalCommitLimitMaximum, NULL, _REGISTRY_MEMORY_RUN::PageCount, PASSIVE_LEVEL, _REGISTRY_MEMORY_RUN::PointerPte, _MMPFN::PteAddress, and UNLOCK_PFN.
Referenced by MmFreeLoaderBlock().
VOID MmFreeLoaderBlock (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 2886 of file mminit.c.
References _MI_MORE_THAN_4GB_, ActiveAndValid, ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, _REGISTRY_MEMORY_RUN::BasePage, _MMPFNENTRY::CacheAttribute, CONTAINING_RECORD, _MMPFN::e1, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), _LIST_ENTRY::Flink, _MMPFN::Flink, _MMPTE::Hard, InterlockedExchangeAddSizeT, KSEG0_BASE, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderNlsData, LoaderOsloaderHeap, LoaderRegistryData, LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MI_FLUSH_ENTIRE_TB, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PFN_DELETED, MI_WRITE_INVALID_PTE, MI_WRITE_ZERO_PTE, MiBootRegistryRuns, MiCached, MiDecrementShareCount(), MiDetermineNode, MiGetPdeAddress, MiGetVirtualAddressMappedByPte, MiInsertPageInFreeList(), MiNoLowMemory, MM_DEMAND_ZERO_WRITE_PTE, MM_READWRITE, MM_VA_MAPPED_BY_PDE, MmBootImageSize, MmFreeBootRegistry(), MmKeepBootRegistry, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmVirtualBias, NonPagedPool, NOTHING, NULL, _MMPFN::OriginalPte, PAGE_SIZE, _PHYSICAL_MEMORY_RUN::PageCount, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _REGISTRY_MEMORY_RUN::PageCount, _MMPFNENTRY::PageLocation, _REGISTRY_MEMORY_RUN::PointerPte, PsGetCurrentThread(), PTE_SHIFT, _MMPFN::PteAddress, RtlZeroMemory, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, UNLOCK_SYSTEM_WS, and _MMPTE_HARDWARE::Valid.
Referenced by Phase1InitializationDiscard().
PPHYSICAL_MEMORY_DESCRIPTOR MmInitializeMemoryLimits (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PBOOLEAN IncludeType, IN OUT PPHYSICAL_MEMORY_DESCRIPTOR InputMemory OPTIONAL)
Definition at line 2580 of file mminit.c.
References ARGUMENT_PRESENT, ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, CONTAINING_RECORD, ExAllocatePoolWithTag, ExFreePool(), _LIST_ENTRY::Flink, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderMaximum, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, NonPagedPool, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfPages, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _PHYSICAL_MEMORY_RUN::PageCount, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, RtlCopyMemory, and _PHYSICAL_MEMORY_DESCRIPTOR::Run.
Referenced by MmInitSystem().
BOOLEAN MmInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 337 of file mminit.c.
References _1gb, _2gb, _4gb, _MMPAGE_FILE_EXPANSION::ActualExpansion, ASSERT, atol(), _PHYSICAL_MEMORY_RUN::BasePage, BBTPagesToReserve, _MMPFNLIST::Blink, CODE_START, CONTAINING_RECORD, DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPAGE_FILE_EXPANSION::Event, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExInitializePushLock(), ExInitializeResourceLite(), ExPageLockHandle, ExpMultiUserTS, ExReleaseResourceLite(), FALSE, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, _MMPFNLIST::Flink, _MMPTE::Hard, InitializeListHead(), InitializeObjectAttributes, InitializeSListHead(), _MMPAGE_FILE_EXPANSION::InProgress, INSTALL_MORE_MEMORY, Int32x32To64, InterlockedDecrement, InterlockedPushEntrySList(), KeBalanceSetManager(), KeBugCheckEx(), KeFeatureBits, KeInitializeDpc(), KeInitializeEvent(), KeInitializeGuardedMutex(), KeInitializeMutant(), KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitializeTimerEx(), KeNodeBlock, KeNumberNodes, KeSwapProcessOrStack(), KF_LARGE_PAGE, KI_USER_SHARED_DATA, KSEG0_BASE, LDRP_ENTRY_NATIVE, _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMWORKING_SET_EXPANSION_HEAD::ListHead, _MMPFNLIST::ListName, LoaderBad, LoaderBBTMemory, LoaderFirmwarePermanent, LoaderMaximum, LoaderSpecialMemory, _MMDEREFERENCE_SEGMENT_HEADER::Lock, LOCK_PFN, _MMPTE::Long, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, MAXLONG, MI_EXTEND_ANY_PAGEFILE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_INITIALIZE_DYNAMIC_MEMORY_LOCK, MI_MAKE_VALID_KERNEL_PTE, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MI_ROUND_TO_SIZE, MI_SESSION_DEFAULT_IMAGE_SIZE, MI_SESSION_DEFAULT_POOL_SIZE, MI_SESSION_DEFAULT_VIEW_SIZE, MI_SESSION_SPACE_DEFAULT_TOTAL_SIZE, MI_SESSION_SPACE_MAXIMUM_TOTAL_SIZE, MI_SESSION_SPACE_STRUCT_SIZE, MI_SESSION_SPACE_WS_SIZE, MI_SYSTEM_PAGE_COLOR, MI_WRITE_VALID_PTE, MiAddExtraSystemPteRanges(), MiAddHalIoMappings(), MiAddSystemPtes(), MiAdjustWorkingSetManagerParameters(), MiBuildPagedPool(), MiChargeCommitmentCantExpand(), MiEnableKernelVerifier(), MiEnablePagingTheExecutive(), MiExpansionPoolPagesInitialCharge, MiFullyInitialized, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetSubsectionAddress, MiGetSubsectionAddressForPte, MiGetVirtualAddressMappedByPte, MiHighestUserPde, MiHighestUserPte, MiHotPatchList, MiIncrementSystemPtes(), MiInitializeCacheOverrides(), MiInitializeCommitment(), MiInitializeDriverLargePageList(), MiInitializeDriverVerifierList(), MiInitializeIoTrackers(), MiInitializeLargePageSupport(), MiInitializeLoadedModuleList(), MiInitializeMemoryEvents(), MiInitializePfnAndMakePteValid(), MiInitializePfnTracing(), MiInitializeSessionIds(), MiInitializeSessionWsSupport(), MiInitializeSystemCache(), MiInitializeVerifyingComponents(), MiInitialSystemPageDirectory, MiInitMachineDependent(), MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiMapBBTMemory(), MiMaximumSystemCacheSizeExtra, MiMaximumWorkingSet, MiMemorySan(), MiModifiedPageWriter(), MiModifiedPageWriterTimerDispatch(), MiNoLowMemory, MiPagesInLoaderBlock(), MiProtoAddressForPte, MiPteRanges, MiPteToProto, MiReloadBootLoadedDrivers(), MiRemoveLowPages(), MiRemoveZeroPage(), MiReportPhysicalMemory(), MiRequestedSystemPtes, MiSafeBooted, MiSectionInitialization(), MiSessionBasePte, MiSessionImageEnd, MiSessionImagePteEnd, MiSessionImagePteStart, MiSessionImageStart, MiSessionLastPte, MiSessionPoolEnd, MiSessionPoolStart, MiSessionSpaceEnd, MiSessionSpacePageTables, MiSessionSpaceWs, MiSessionViewStart, MiSessionWideInitializeAddresses(), MiStartZeroPageWorkers(), MiSyncCachedRanges(), MiSystemCacheEndExtra, MiSystemCacheStartExtra, MiSystemViewStart, MiTempEvent, MiTriageSystem(), MiTrimInProgressCount, MiUseMaximumSystemSpace, MiUseMaximumSystemSpaceEnd, MiVerifyAllDrivers, MiWriteProtectSystemImage(), MM_ALLOCATION_FRAGMENT, MM_ALLOCATION_FRAGMENT_MAX, MM_DBG_COMMIT_EXTRA_SYSTEM_PTES, MM_DEFAULT_SYSTEM_PTES, MM_DEMAND_ZERO_WRITE_PTE, MM_EMPTY_LIST, MM_FLUID_PHYSICAL_PAGES, MM_MAXIMUM_SYSTEM_PTES, MM_MAXIMUM_WORKING_SET, MM_MB_MAPPED_BY_PDE, MM_MEDIUM_SYSTEM, MM_MINIMUM_SYSTEM_PTES, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NONPAGED_POOL_END, MM_READONLY, MM_SESSION_SPACE_DEFAULT, MM_SESSION_SPACE_DEFAULT_END, MM_SHARED_USER_DATA_VA, MM_SMALL_SYSTEM, MM_SPECIAL_POOL_PTES, MM_SYSTEM_CACHE_END, MM_SYSTEM_VIEW_SIZE, MM_TRACK_COMMIT, MM_VA_MAPPED_BY_PDE, MmAllocationFragment, MmAllocationPreference, MmAttemptForCantExtend, MmAvailablePages, MmAvailablePagesEvent, MmAvailablePagesEventHigh, MmBootImageSize, MmCodeClusterSize, MmCollidedFlushEvent, MmCollidedLockEvent, MmConsumedPoolPercentage, MmCriticalSectionTimeout, MmCritsectTimeoutSeconds, MmDataClusterSize, MmDeadStackSListHead, MmDereferenceSegmentHeader, MmEnforceWriteProtection, MmEventCountSListHead, MmExpansionLock, MmFreedExpansionPoolMaximum, MmHeapDeCommitFreeBlockThreshold, MmHeapDeCommitTotalFreeThreshold, MmHeapSegmentCommit, MmHeapSegmentReserve, MmHighestPhysicalPage, MmHighestPossiblePhysicalPage, MmHighestUserAddress, MmHighSectionBase, MmInitializeMemoryLimits(), MmInPageSupportMinimum, MmInPageSupportSListHead, MmIsVerifierEnabled(), MmLargePageDriverBufferLength, MmLargeSystem, MmLockPageableCodeSection, MmLowestPhysicalPage, MmMappedFileIoComplete, MmMaximumDeadKernelStacks, MmMaximumWorkingSetSize, MmMediumSystem, MmMinimumFreePages, MmModifiedPageLifeInSeconds, MmModifiedPageMaximum, MmModifiedPageWriterEvent, MmNonPagedSystemStart, MmNumberOfPhysicalPages, MmNumberOfSystemPtes, MmPagedPoolEnd, MmPagedPoolMaximumDesired, MmPagedPoolStart, MmPageFaultNotifyRoutine, MmPageFileCreationLock, MmPfnDereferenceSListHead, MmProductType, MmProtectedPteLock, MmProtectFreedNonPagedPool, MmReadClusterSize, MmResidentAvailableAtInit, MmResidentAvailablePages, MmSecondaryColors, MmSectionBasedMutex, MmSectionCommitMutex, MmSectionExtendResource, MmSectionExtendSetResource, MmSessionBase, MmSessionImageSize, MmSessionPoolSize, MmSessionSize, MmSessionSpace, MmSessionSpecialPoolEnd, MmSessionSpecialPoolStart, MmSessionViewSize, MmShutdownSystem(), MmSizeOfPagedPoolInBytes, MmSizeOfSystemCacheInPages, MmSmallSystem, MmSnapUnloads, MmSpecialPoolTag, MmStandbyPageListByPriority, MmSystemCacheEnd, MmSystemCacheStart, MmSystemCacheWorkingSetList, MmSystemCacheWs, MmSystemCacheWsMinimum, MmSystemLoadLock, MmSystemRangeStart, MmSystemSize, MmSystemViewSize, MmThrottleBottom, MmThrottleTop, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTrackLockedPages, MmTrackPtes, MmUnlockPageableImageSection(), MmUnusedSegmentCleanup, MmUnusedSegmentList, MmUnusedSubsectionList, MmUserProbeAddress, MmVerifyDriverBufferLength, MmVerifyDriverLevel, MmVirtualBias, MmWorkingSetExpansionHead, MmWorkingSetManagerEvent, MmZeroingPageEvent, MmZeroingPageThreadActive, NON_PAGED_SYSTEM_END, NonPagedPool, NotificationEvent, NT_SUCCESS, NtProductLanManNt, NtProductServer, NtProductWinNt, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _IMAGE_NT_HEADERS::OptionalHeader, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, PAGE_SHIFT, PAGE_SIZE, _PHYSICAL_MEMORY_RUN::PageCount, PagedPool, _MMPAGE_FILE_EXPANSION::PageFileNumber, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PsCreateSystemThread(), PSLIST_ENTRY, PsLoadedModuleList, PsLoadedModuleResource, PTE_PER_PAGE, PTE_SHIFT, _LARGE_INTEGER::QuadPart, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, ROUND_TO_PAGES, RtlClearAllBits(), RtlCopyMemory, RtlImageNtHeader(), RtlInitializeBitMap(), RtlSetBits(), _PHYSICAL_MEMORY_DESCRIPTOR::Run, SAFEBOOT_LOAD_OPTION_A, _MMPAGE_FILE_EXPANSION::Segment, _MMDEREFERENCE_SEGMENT_HEADER::Semaphore, SharedUserData, StandbyPageList, _MI_PTE_RANGES::StartingVa, strstr(), SynchronizationEvent, SynchronizationTimer, SystemPteSpace, THREAD_ALL_ACCESS, _MMPFNLIST::Total, TRUE, _MMPTE::u, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, ValidKernelPde, ValidKernelPte, _MMSUPPORT::WorkingSetMutex, and ZwClose().
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTKERNELAPI BOOLEAN MmIsThisAnNtAsSystem (VOID)
Definition at line 4818 of file mminit.c.
References MmProductType.
Referenced by CcInitializeCacheManager(), ExpWorkerInitialization(), FsRtlInitializeTunnels(), IoInitSystem(), MiBuildPagedPool(), ObInitSystem(), and PsChangeQuantumTable().
MM_SYSTEMSIZE MmQuerySystemSize (VOID)
Definition at line 4804 of file mminit.c.
References MmSystemSize.
Referenced by CcInitializeCacheManager(), ExpInitializeExecutive(), ExpWorkerInitialization(), IoInitSystem(), KeBalanceSetManager(), ObInitSystem(), and PspInitPhase0().
NTKERNELAPI VOID FASTCALL MmSetPageFaultNotifyRoutine (PPAGE_FAULT_NOTIFY_ROUTINE NotifyRoutine)
Definition at line 4828 of file mminit.c.
References MmPageFaultNotifyRoutine.
Variable Documentation
PVOID BBTBuffer
Referenced by MiMapBBTMemory().
PFN_COUNT BBTPagesToReserve
Definition at line 234 of file initos.c.
Referenced by MiMapBBTMemory(), and MmInitSystem().
POBJECT_TYPE ExEventObjectType
Definition at line 32 of file event.c.
PVOID ExPageLockHandle
Definition at line 22 of file mminit.c.
Referenced by ExpGetLockInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpSystemErrorHandler(), IoUnregisterShutdownNotification(), KeSetPhysicalCacheTypeRange(), KiAmdK6MtrrSetMemoryType(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiFreeInitializationCode(), MiResetVirtualMemory(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiShutdownSystem(), MiUnmapLockedPagesInUserSpace(), MmAdjustWorkingSetSizeEx(), MmFreePagesFromMdl(), MmInitSystem(), MmMapUserAddressesToPage(), MmUnlockPagedPool(), and PspQueryWorkingSetWatch().
BOOLEAN MiAllMainMemoryMustBeCached = FALSE
Definition at line 5135 of file mminit.c.
Referenced by MmEnablePAT().
PREGISTRY_MEMORY_RUN MiBootRegistryRuns
Definition at line 2808 of file mminit.c.
Referenced by MmFreeLoaderBlock().
PFN_NUMBER MiExpansionPoolPagesInitialCharge
Definition at line 104 of file allocpag.c.
Referenced by MiAllocatePoolPages(), MiFreeNonPagedPool(), MiFreePoolPages(), MiInitializeNonPagedPool(), and MmInitSystem().
ULONG MiFullyInitialized
Definition at line 55 of file mminit.c.
Referenced by MmEmptyAllWorkingSets(), and MmInitSystem().
PKEVENT MiHighMemoryEvent
Definition at line 125 of file mminit.c.
Referenced by MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiRemovePageByColor(), MiRemovePageFromList(), MiUnlinkFreeOrZeroedPage(), and MiUnlinkPageFromList().
PKEVENT MiHighNonPagedPoolEvent
Definition at line 131 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), and MiInitializePoolEvents().
PFN_NUMBER MiHighNonPagedPoolThreshold
Definition at line 137 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), MiInitializeNonPagedPoolThresholds(), and MiInitializePoolEvents().
PKEVENT MiHighPagedPoolEvent
Definition at line 128 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiFreePoolPages(), and MiInitializePoolEvents().
PFN_NUMBER MiHighPagedPoolThreshold
Definition at line 134 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), MiFreePoolPages(), and MiInitializePoolEvents().
PKEVENT MiLowMemoryEvent
Definition at line 124 of file mminit.c.
Referenced by MiComputeSystemTrimCriteria(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiRemovePageByColor(), MiRemovePageFromList(), MiUnlinkFreeOrZeroedPage(), and MiUnlinkPageFromList().
PKEVENT MiLowNonPagedPoolEvent
Definition at line 130 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), MiInitializePoolEvents(), and MmResourcesAvailable().
PFN_NUMBER MiLowNonPagedPoolThreshold
Definition at line 136 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), MiInitializeNonPagedPoolThresholds(), and MiInitializePoolEvents().
PKEVENT MiLowPagedPoolEvent
Definition at line 127 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiFreePoolPages(), MiInitializePoolEvents(), and MmResourcesAvailable().
PFN_NUMBER MiLowPagedPoolThreshold
Definition at line 133 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), MiFreePoolPages(), and MiInitializePoolEvents().
KEVENT MiMappedPagesTooOldEvent
Definition at line 187 of file mminit.c.
Referenced by MiModifiedPageWriterTimerDispatch(), MiModifiedPageWriterWorker(), and MiWriteComplete().
LARGE_INTEGER MiModifiedPageLife
Definition at line 183 of file mminit.c.
Referenced by MiInsertPageInList(), and MiModifiedPageWriterWorker().
KTIMER MiModifiedPageWriterTimer
Definition at line 191 of file mminit.c.
Referenced by MiInsertPageInList(), and MiModifiedPageWriterWorker().
KDPC MiModifiedPageWriterTimerDpc
Definition at line 189 of file mminit.c.
Referenced by MiInsertPageInList(), and MiModifiedPageWriterWorker().
RTL_BITMAP MiPfnBitMap
Definition at line 61 of file mminit.c.
Referenced by MiAddCachedRange(), MiReleaseAllMemory(), and MiRemoveCachedRange().
LOGICAL MiSafeBooted = FALSE
Definition at line 57 of file mminit.c.
Referenced by MmCleanProcessAddressSpace(), and MmInitSystem().
PMMPTE MiSpecialPoolFirstPte
KEVENT MiTempEvent
Definition at line 122 of file mminit.c.
Referenced by MmInitSystem().
BOOLEAN MiTimerPending = FALSE
Definition at line 185 of file mminit.c.
Referenced by MiInsertPageInList(), MiModifiedPageWriterTimerDispatch(), MiModifiedPageWriterWorker(), and MiWriteComplete().
LONG MiTrimInProgressCount
Definition at line 2311 of file wsmanage.c.
Referenced by MiTrimAllSystemPageableMemory(), and MmInitSystem().
ULONG MiVerifyAllDrivers
Referenced by MmInitSystem().
SIZE_T MmAllocationFragment
Definition at line 243 of file mminit.c.
Referenced by MiCreateDataFileMap(), MmExtendSection(), and MmInitSystem().
ULONG MmAllocationPreference
Definition at line 38 of file mminit.c.
Referenced by MmInitializeProcessAddressSpace(), and MmInitSystem().
ULONG MmCodeClusterSize
Definition at line 43 of file mminit.c.
Referenced by MiResolveMappedFileFault(), and MmInitSystem().
ULONG MmDataClusterSize
Definition at line 42 of file mminit.c.
Referenced by MiResolveMappedFileFault(), and MmInitSystem().
ULONG MmEnforceWriteProtection
Definition at line 52 of file sysload.c.
Referenced by MiComputeDriverProtection(), and MmInitSystem().
PFN_NUMBER MmFreedExpansionPoolMaximum
Definition at line 59 of file mminit.c.
Referenced by MiFreePoolPages(), and MmInitSystem().
PFN_NUMBER MmHighMemoryThreshold
Definition at line 114 of file mminit.c.
Referenced by MiInitializeMemoryEvents(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiNotifyMemoryEvents(), MiRemovePageByColor(), MiRemovePageFromList(), MiUnlinkFreeOrZeroedPage(), and MiUnlinkPageFromList().
ULONG MmInPageSupportMinimum
Definition at line 23 of file pagfault.c.
Referenced by MiFreeInPageSupportBlock(), and MmInitSystem().
ULONG MmKeepBootRegistry = 0
Definition at line 49 of file mminit.c.
Referenced by MmFreeLoaderBlock().
ULONG MmLargeSystemCache
Definition at line 222 of file mminit.c.
Referenced by MiInitMachineDependent().
LIST_ENTRY MmLoadedUserImageList
Definition at line 228 of file mminit.c.
Referenced by MiLoadUserSymbols().
PFN_NUMBER MmLowMemoryThreshold
Definition at line 113 of file mminit.c.
Referenced by MiInitializeMemoryEvents(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiNotifyMemoryEvents(), MiRemovePageByColor(), MiRemovePageFromList(), MiUnlinkFreeOrZeroedPage(), and MiUnlinkPageFromList().
WSLE_NUMBER MmMaximumWorkingSetSize
Definition at line 538 of file miglobal.c.
Referenced by MmInitSystem().
ULONG MmModifiedPageLifeInSeconds = 300
Definition at line 178 of file mminit.c.
Referenced by MmInitSystem().
ULONG MmPagedPoolCommit
Definition at line 56 of file allocpag.c.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), and MiFreePoolPages().
LOGICAL MmPagedPoolMaximumDesired = FALSE
Definition at line 53 of file mminit.c.
Referenced by MiBuildPagedPool(), MiInitMachineDependent(), and MmInitSystem().
KGUARDED_MUTEX MmPagedPoolMutex
Definition at line 51 of file mminit.c.
Referenced by MiFreePoolPages(), and MmGetSizeOfBigPoolAllocation().
PPAGE_FAULT_NOTIFY_ROUTINE MmPageFaultNotifyRoutine
Definition at line 229 of file mminit.c.
Referenced by MmAccessFault(), MmInitSystem(), and MmSetPageFaultNotifyRoutine().
PPHYSICAL_MEMORY_DESCRIPTOR MmPhysicalMemoryBlock
Definition at line 45 of file mminit.c.
Referenced by MiFindContiguousPages(), MiFindLargePageMemory(), MiReleaseAllMemory(), MiReportPhysicalMemory(), MmIdentifyPhysicalMemory(), and MmPerfSnapShotValidPhysicalMemory().
ULONG MmProductType
Definition at line 224 of file mminit.c.
Referenced by MmInitSystem(), and MmIsThisAnNtAsSystem().
LIST_ENTRY MmProtectedPteList
Definition at line 46 of file mminit.c.
Referenced by MiCheckSystemPteProtection(), MmAccessFault(), and MmProtectMdlSystemAddress().
KSPIN_LOCK MmProtectedPteLock
Definition at line 47 of file mminit.c.
Referenced by MiCheckSystemPteProtection(), MmInitSystem(), and MmProtectMdlSystemAddress().
PFN_NUMBER MmResidentAvailableAtInit
Definition at line 44 of file mminit.c.
Referenced by MmInitSystem().
PMMPTE MmSharedUserDataPte
Definition at line 24 of file mminit.c.
Referenced by MiCheckVirtualAddress().
ULONG_PTR MmSubsectionBase
Definition at line 40 of file mminit.c.
Referenced by MiInitMachineDependent().
ULONG_PTR MmSubsectionTopPage
Definition at line 41 of file mminit.c.
PFN_NUMBER MmSystemPageDirectory[PD_PER_SYSTEM]
Definition at line 214 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), and MiFillSystemPageDirectory().
PMMPTE MmSystemPagePtes
Definition at line 215 of file mminit.c.
Referenced by MiAllocatePoolPages(), MiCheckPdeForPagedPool(), MiFillSystemPageDirectory(), MiRemoveMappedPtes(), and MxConvertToLargePage().
MM_SYSTEMSIZE MmSystemSize
Definition at line 220 of file mminit.c.
Referenced by MmInitSystem(), MmQuerySystemSize(), and MmSetMemoryPriorityProcess().
ULONG MmTotalSystemCodePages
Definition at line 218 of file mminit.c.
Referenced by MiEnablePagingOfDriverAtInit(), and NtQuerySystemInformation().