Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/byteswap.c File Reference
byteswap.c File Reference
#include "nt.h"
#include "ntrtlp.h"
Functions
ULONG FASTCALL RtlUlongByteSwap (IN ULONG Source)
ULONGLONG FASTCALL RtlUlonglongByteSwap (IN ULONGLONG Source)
USHORT FASTCALL RtlUshortByteSwap (IN USHORT Source)
Function Documentation
ULONG FASTCALL RtlUlongByteSwap (IN ULONG Source)
Definition at line 59 of file byteswap.c.
Referenced by RtlIpv4StringToAddressT().
ULONGLONG FASTCALL RtlUlonglongByteSwap (IN ULONGLONG Source)
Definition at line 94 of file byteswap.c.
USHORT FASTCALL RtlUshortByteSwap (IN USHORT Source)
Definition at line 26 of file byteswap.c.
Referenced by RtlIpv4AddressToStringExT(), RtlIpv4StringToAddressExT(), RtlIpv6AddressToStringExT(), RtlIpv6AddressToStringT(), RtlIpv6StringToAddressExT(), and RtlIpv6StringToAddressT().