Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/ds.c File Reference
ds.c File Reference
#include "wmikmp.h"
#include <strsafe.h>
Macros
#define REGUPDATENAME L"REGUPDATEINFO"
Functions
PWCHAR GuidToString (PWCHAR s, ULONG SizeInBytes, LPGUID piid)
NTSTATUS WmipAddDataSource (IN PREGENTRY RegEntry, IN PWMIREGINFOW WmiRegInfo, IN ULONG BufferSize, IN PWCHAR RegPath, IN PWCHAR ResourceName, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN IsUserMode)
NTSTATUS WmipAddMofResource (PBDATASOURCE DataSource, LPWSTR ImagePath, BOOLEAN IsImagePath, LPWSTR MofResourceName, PBOOLEAN NewMofResource)
NTSTATUS WmipBuildInstanceSet (PWMIREGGUID RegGuid, PWMIREGINFOW WmiRegInfo, ULONG BufferSize, PBINSTANCESET InstanceSet, ULONG ProviderId, LPCTSTR MofImagePath)
NTSTATUS WmipBuildInstanceSet (IN PWMIREGGUID RegGuid, IN PWMIREGINFOW WmiRegInfo, IN ULONG BufferSize, IN PBINSTANCESET InstanceSet, IN ULONG ProviderId, IN LPCTSTR MofImagePath)
void WmipCachePtrs (LPGUID Ptr1, PBINSTANCESET Ptr2, ULONG *PtrCount, ULONG *PtrMax, PTRCACHE **PtrArray)
ULONG WmipDetermineInstanceBaseIndex (LPGUID Guid, PWCHAR BaseName, ULONG InstanceCount)
void WmipDisableCollectionForRemovedGuid (LPGUID Guid, PBINSTANCESET InstanceSet)
void WmipEnableCollectionForNewGuid (LPGUID Guid, PBINSTANCESET InstanceSet)
NTSTATUS WmipEnumerateMofResources (PWMIMOFLIST MofList, ULONG BufferSize, ULONG *RetSize)
PBINSTANCESET WmipFindISInDSByGuid (PBDATASOURCE DataSource, LPGUID Guid)
void WmipGenerateBinaryMofNotification (PBINSTANCESET BinaryMofInstanceSet, LPCGUID Guid)
void WmipGenerateMofResourceNotification (LPWSTR ImagePath, LPWSTR ResourceName, LPCGUID Guid, ULONG ActionCode)
void WmipGenerateRegistrationNotification (PBDATASOURCE DataSource, ULONG NotificationCode)
void WmipGenerateRegistrationNotification (PBDATASOURCE DataSource, NOTIFICATIONTYPES NotificationType)
NTSTATUS WmipInitializeDataStructs (void)
BOOLEAN WmipIsEqualInstanceSets (PBINSTANCESET InstanceSet1, PBINSTANCESET InstanceSet2)
NTSTATUS WmipLinkDataSourceToList (PBDATASOURCE DataSource, BOOLEAN AddDSToList)
NTSTATUS WmipMangleInstanceName (IN LPGUID Guid, IN PWCHAR Name, IN SIZE_T MaxMangledNameLen, OUT PWCHAR MangledName)
NTSTATUS WmipRemoveDataSource (PREGENTRY RegEntry)
void WmipRemoveDataSourceByDS (PBDATASOURCE DataSource)
void WmipSendGuidUpdateNotifications (NOTIFICATIONTYPES NotificationType, ULONG GuidCount, PTRCACHE *GuidList)
ULONG WmipUpdateAddGuid (PBDATASOURCE DataSource, PWMIREGGUID RegGuid, PWMIREGINFO WmiRegInfo, ULONG BufferSize, PBINSTANCESET *AddModInstanceSet)
NTSTATUS WmipUpdateDataSource (PREGENTRY RegEntry, PWMIREGINFOW WmiRegInfo, ULONG RetSize)
ULONG WmipUpdateModifyGuid (PBDATASOURCE DataSource, PWMIREGGUID RegGuid, PWMIREGINFO WmiRegInfo, ULONG BufferSize, PBINSTANCESET *AddModInstanceSet)
BOOLEAN WmipUpdateRemoveGuid (PBDATASOURCE DataSource, PWMIREGGUID RegGuid, PBINSTANCESET *AddModInstanceSet)
Variables
const GUID RegChangeNotificationGuid
const GUID WmipBinaryMofGuid = BINARY_MOF_GUID
Macro Definition Documentation
#define REGUPDATENAME L"REGUPDATEINFO"
Referenced by WmipSendGuidUpdateNotifications().
Function Documentation
PWCHAR GuidToString (PWCHAR s, ULONG SizeInBytes, LPGUID piid)
Referenced by WmipUpdateRemoveGuid().
NTSTATUS WmipAddDataSource (IN PREGENTRY RegEntry, IN PWMIREGINFOW WmiRegInfo, IN ULONG BufferSize, IN PWCHAR RegPath, IN PWCHAR ResourceName, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN IsUserMode)
Definition at line 1574 of file ds.c.
References tagInstanceSet::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, DS_KERNEL_MODE, DS_USER_MODE, tagInstanceSet::DSISList, FALSE, tagInstanceSet::Flags, WMIREGGUIDW::Flags, tagDATASOURCE::Flags, WMIREGGUIDW::Guid, GUID_MOF_RESOURCE_ADDED_NOTIFICATION, tagInstanceSet::GuidEntry, InsertHeadList(), IS_NEWLY_REGISTERED, IsEqualGUID, tagDATASOURCE::ISHead, MOFEVENT_ACTION_IMAGE_PATH, MOFEVENT_ACTION_REGISTRY_PATH, NT_SUCCESS, NULL, PAGED_CODE, tagInstanceSet::ProviderId, tagDATASOURCE::ProviderId, RegistrationAdd, tagDATASOURCE::RegistryPath, tagDATASOURCE::RequestObject, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, WmipAddMofResource(), WmipAllocDataSource(), WmipAllocInstanceSet, WmipAssert, WmipBuildInstanceSet(), WmipCountedToSz(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFree, WmipGenerateBinaryMofNotification(), WmipGenerateMofResourceNotification(), WmipGenerateRegistrationNotification(), WmipLeaveSMCritSection, WmipLinkDataSourceToList(), WmipUnreferenceDS, WMIREG_FLAG_REMOVE_GUID, WMIREG_FLAG_TRACE_CONTROL_GUID, and WMIREG_FLAG_TRACED_GUID.
Referenced by WmipInitializeDataStructs(), and WmipProcessWmiRegInfo().
NTSTATUS WmipAddMofResource (PBDATASOURCE DataSource, LPWSTR ImagePath, BOOLEAN IsImagePath, LPWSTR MofResourceName, PBOOLEAN NewMofResource)
Definition at line 1438 of file ds.c.
References AVGMOFRESOURCECOUNT, FALSE, MOFRESOURCE::Flags, InsertTailList(), MOFRESOURCE::MainMRList, tagDATASOURCE::MofResourceCount, MOFRESOURCE::MofResourceName, tagDATASOURCE::MofResources, MR_FLAG_USER_MODE, NULL, PAGED_CODE, MOFRESOURCE::RegistryPath, S_OK, tagDATASOURCE::StaticMofResources, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, StringCbCopy, TRUE, wcslen(), WmipAlloc, WmipAllocMofResource, WmipAssert, WmipEnterSMCritSection, WmipFindMRByNames(), WmipLeaveSMCritSection, WmipMRHeadPtr, WmipRealloc(), and WmipUnreferenceMR.
Referenced by WmipAddDataSource(), and WmipInitializeDataStructs().
NTSTATUS WmipBuildInstanceSet (PWMIREGGUID RegGuid, PWMIREGINFOW WmiRegInfo, ULONG BufferSize, PBINSTANCESET InstanceSet, ULONG ProviderId, LPCTSTR MofImagePath)
Referenced by WmipAddDataSource(), WmipUpdateAddGuid(), and WmipUpdateModifyGuid().
NTSTATUS WmipBuildInstanceSet (IN PWMIREGGUID RegGuid, IN PWMIREGINFOW WmiRegInfo, IN ULONG BufferSize, IN PBINSTANCESET InstanceSet, IN ULONG ProviderId, IN LPCTSTR MofImagePath)
Definition at line 691 of file ds.c.
References ISBASENAME::BaseIndex, ISBASENAME::BaseName, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, EVENTLOG_WARNING_TYPE, FIELD_OFFSET, IS_CONTROL_GUID, IS_EVENT_ONLY, IS_EXPENSIVE, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, IS_PDO_INSTANCENAME, IS_TRACED, MAXBASENAMESUFFIXLENGTH, NT_SUCCESS, NULL, OffsetToPtr, PAGED_CODE, ISSTATICENAMES::StaticNamePtr, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TEXT, UNICODE_NULL, UNREFERENCED_PARAMETER, wcslen(), wcsncpy(), WmipAlloc, WmipAssert, WmipDebugPrintEx, WmipDetermineInstanceBaseIndex(), WmipFree, WmipMangleInstanceName(), WmipReportEventLog, WmipValidateWmiRegInfoString(), WMIREG_FLAG_EVENT_ONLY_GUID, WMIREG_FLAG_EXPENSIVE, WMIREG_FLAG_INSTANCE_BASENAME, WMIREG_FLAG_INSTANCE_LIST, WMIREG_FLAG_INSTANCE_PDO, WMIREG_FLAG_TRACE_CONTROL_GUID, and WMIREG_FLAG_TRACED_GUID.
void WmipCachePtrs (LPGUID Ptr1, PBINSTANCESET Ptr2, ULONG * PtrCount, ULONG * PtrMax, PTRCACHE ** PtrArray)
Definition at line 2237 of file ds.c.
References DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, PTRCACHE::Guid, PTRCACHE::InstanceSet, memcpy(), NULL, PAGED_CODE, PTRCACHEGROWSIZE, WmipAlloc, WmipDebugPrintEx, and WmipFree.
Referenced by WmipGenerateRegistrationNotification(), and WmipUpdateDataSource().
ULONG WmipDetermineInstanceBaseIndex (LPGUID Guid, PWCHAR BaseName, ULONG InstanceCount)
Definition at line 462 of file ds.c.
References ISBASENAME::BaseIndex, ISBASENAME::BaseName, CONTAINING_RECORD, tagInstanceSet::Count, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IS_INSTANCE_BASENAME, tagInstanceSet::IsBaseName, tagGUIDENTRY::ISHead, NULL, PAGED_CODE, UNREFERENCED_PARAMETER, wcscmp(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFindGEByGuid(), WmipLeaveSMCritSection, and WmipUnreferenceGE.
Referenced by WmipBuildInstanceSet().
void WmipDisableCollectionForRemovedGuid (LPGUID Guid, PBINSTANCESET InstanceSet)
Definition at line 335 of file ds.c.
References _WNODE_HEADER::BufferSize, tagGUIDENTRY::CollectRefCount, tagInstanceSet::DataSource, DS_KERNEL_MODE, tagGUIDENTRY::EventRefCount, FALSE, tagInstanceSet::Flags, tagGUIDENTRY::Flags, tagDATASOURCE::Flags, GE_FLAG_COLLECTION_IN_PROGRESS, GE_FLAG_NOTIFICATION_IN_PROGRESS, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, IRP_MN_DISABLE_COLLECTION, IRP_MN_DISABLE_EVENTS, IS_ENABLE_COLLECTION, IS_ENABLE_EVENT, IS_TRACED, tagGUIDENTRY::LoggerContext, memcpy(), memset(), NULL, PAGED_CODE, Status, TRUE, WmipAssert, WmipDeliverWnodeToDS(), WmipDoDisableRequest(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipLeaveSMCritSection, WmipReleaseCollectionEnabled(), and WmipUnreferenceGE.
Referenced by WmipGenerateRegistrationNotification(), and WmipUpdateDataSource().
void WmipEnableCollectionForNewGuid (LPGUID Guid, PBINSTANCESET InstanceSet)
Definition at line 197 of file ds.c.
References _WNODE_HEADER::BufferSize, tagGUIDENTRY::CollectRefCount, tagInstanceSet::DataSource, DS_KERNEL_MODE, tagGUIDENTRY::EventRefCount, FALSE, tagInstanceSet::Flags, tagGUIDENTRY::Flags, tagDATASOURCE::Flags, GE_FLAG_COLLECTION_IN_PROGRESS, GE_FLAG_NOTIFICATION_IN_PROGRESS, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, IS_ENABLE_COLLECTION, IS_ENABLE_EVENT, IS_EXPENSIVE, IS_TRACED, tagGUIDENTRY::LoggerContext, memcpy(), memset(), NULL, PAGED_CODE, Status, TRUE, WmipAssert, WmipDeliverWnodeToDS(), WmipDoDisableRequest(), WmipEnterSMCritSection, WmipFindGEByGuid(), WmipLeaveSMCritSection, WmipReleaseCollectionEnabled(), and WmipUnreferenceGE.
Referenced by WmipGenerateRegistrationNotification(), and WmipUpdateDataSource().
NTSTATUS WmipEnumerateMofResources (PWMIMOFLIST MofList, ULONG BufferSize, ULONG * RetSize)
Definition at line 2512 of file ds.c.
References CONTAINING_RECORD, MOFRESOURCE::Flags, WMIMOFENTRY::Flags, _LIST_ENTRY::Flink, WMIMOFLIST::MofEntry, WMIMOFLIST::MofListCount, MOFRESOURCE::MofResourceName, MR_FLAG_USER_MODE, OffsetToPtr, PAGED_CODE, MOFRESOURCE::RegistryPath, WMIMOFENTRY::RegPathOffset, WMIMOFENTRY::ResourceOffset, S_OK, STATUS_SUCCESS, StringCbCopy, wcslen(), WMIMOFENTRY_FLAG_USERMODE, WmipAssert, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipMRHeadPtr.
Referenced by WmipIoControl().
PBINSTANCESET WmipFindISInDSByGuid (PBDATASOURCE DataSource, LPGUID Guid)
Definition at line 1849 of file ds.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, tagInstanceSet::GuidEntry, IsEqualGUID, tagDATASOURCE::ISHead, NULL, PAGED_CODE, and WmipReferenceIS.
Referenced by WmipUpdateModifyGuid(), and WmipUpdateRemoveGuid().
void WmipGenerateBinaryMofNotification (PBINSTANCESET BinaryMofInstanceSet, LPCGUID Guid)
Definition at line 1216 of file ds.c.
References ISBASENAME::BaseIndex, ISBASENAME::BaseName, _WNODE_HEADER::BufferSize, tagInstanceSet::Count, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, tagInstanceSet::Flags, _WNODE_HEADER::Guid, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, tagInstanceSet::IsBaseName, tagInstanceSet::IsStaticNames, _WNODE_HEADER::Linkage, MAXBASENAMESUFFIXLENGTH, memcpy(), MOFEVENT_ACTION_BINARY_MOF, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, _WNODE_HEADER::ProviderId, S_OK, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, ISSTATICENAMES::StaticNamePtr, StringCbCopy, StringCbPrintfEx, STRSAFE_FILL_BEHIND_NULL, TRUE, tagWNODE_SINGLE_INSTANCE::VariableData, _WNODE_HEADER::Version, wcslen(), WmiInsertTimestamp, WmipAlloc, WmipAssert, WmipFree, WmipProcessEvent(), WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipAddDataSource(), WmipDSCleanup(), and WmipUpdateDataSource().
void WmipGenerateMofResourceNotification (LPWSTR ImagePath, LPWSTR ResourceName, LPCGUID Guid, ULONG ActionCode)
Definition at line 1307 of file ds.c.
References _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, _WNODE_HEADER::Linkage, memcpy(), NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, _WNODE_HEADER::ProviderId, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, TRUE, tagWNODE_SINGLE_INSTANCE::VariableData, _WNODE_HEADER::Version, wcslen(), WmiInsertTimestamp, WmipAlloc, WmipFree, WmipProcessEvent(), WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_INTERNAL, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipAddDataSource(), WmipIoControl(), and WmipMRCleanup().
void WmipGenerateRegistrationNotification (PBDATASOURCE DataSource, ULONG NotificationCode)
Referenced by WmipAddDataSource(), and WmipRemoveDataSourceByDS().
void WmipGenerateRegistrationNotification (PBDATASOURCE DataSource, NOTIFICATIONTYPES NotificationType)
Definition at line 1368 of file ds.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, tagInstanceSet::GuidEntry, tagDATASOURCE::ISHead, NULL, PAGED_CODE, RegistrationAdd, RegistrationDelete, WmipCachePtrs(), WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), WmipFree, WmipReferenceDS, WmipSendGuidUpdateNotifications(), and WmipUnreferenceDS.
NTSTATUS WmipInitializeDataStructs (void)
Definition at line 2608 of file ds.c.
References _CHUNKINFO::ChunkHead, CONTAINING_RECORD, _REGENTRY::DataSource, ENUMERATE_GUIDS_GUID, FALSE, _REGENTRY::Flags, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_FLAG_INTERNAL, InitializeListHead(), INSTANCE_INFO_GUID, NT_SUCCESS, NULL, PAGED_CODE, REGENTRY_FLAG_INUSE, REGENTRY_FLAG_NEWREGINFO, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_REG_IN_PROGRESS, REGENTRY_FLAG_RUNDOWN, REGENTRY_FLAG_TRACED, RtlZeroMemory, Status, STATUS_SUCCESS, TRUE, WMICOREIMAGEPATH, WMICORERESOURCENAME, WmipAddDataSource(), WmipAddMofResource(), WmipAllocRegEntry(), WmipAssert, WmipDSChunkInfo, WmipDSHead, WmipDSHeadPtr, WmipGEChunkInfo, WmipGEHead, WmipGEHeadPtr, WmipISChunkInfo, WmipMRChunkInfo, WmipMRHead, WmipMRHeadPtr, WmipUMProviderCallback(), WmipUnreferenceRegEntry, and WMIREG_FLAG_CALLBACK.
Referenced by WmipDriverEntry().
BOOLEAN WmipIsEqualInstanceSets (PBINSTANCESET InstanceSet1, PBINSTANCESET InstanceSet2)
Definition at line 2056 of file ds.c.
References ISBASENAME::BaseName, tagInstanceSet::Count, FALSE, tagInstanceSet::Flags, IS_ENABLE_COLLECTION, IS_ENABLE_EVENT, IS_INSTANCE_BASENAME, IS_INSTANCE_STATICNAMES, tagInstanceSet::IsBaseName, tagInstanceSet::IsStaticNames, PAGED_CODE, ISSTATICENAMES::StaticNamePtr, TRUE, and wcscmp().
Referenced by WmipUpdateModifyGuid().
NTSTATUS WmipLinkDataSourceToList (PBDATASOURCE DataSource, BOOLEAN AddDSToList)
Definition at line 1050 of file ds.c.
References CONTAINING_RECORD, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, FLAG_ENTRY_ON_INUSE_LIST, tagInstanceSet::Flags, tagDATASOURCE::Flags, _LIST_ENTRY::Flink, tagGUIDENTRY::Guid, tagInstanceSet::GuidEntry, tagInstanceSet::GuidISList, InsertHeadList(), InsertTailList(), IS_NEWLY_REGISTERED, tagGUIDENTRY::ISCount, tagGUIDENTRY::ISHead, tagDATASOURCE::ISHead, tagDATASOURCE::MainDSList, tagGUIDENTRY::MainGEList, memcpy(), NULL, PAGED_CODE, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, WmipAllocGuidEntry, WmipAssert, WmipDebugPrintEx, WmipDSHeadPtr, WmipFindGEByGuid(), and WmipGEHeadPtr.
Referenced by WmipAddDataSource(), and WmipUpdateAddGuid().
NTSTATUS WmipMangleInstanceName (IN LPGUID Guid, IN PWCHAR Name, IN SIZE_T MaxMangledNameLen, OUT PWCHAR MangledName)
Definition at line 533 of file ds.c.
References DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, NULL, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, UNICODE_NULL, wcslen(), wcsncpy(), WmipAssert, WmipDebugPrintEx, WmipFindGEByGuid(), WmipFindISinGEbyName(), WmipUnreferenceGE, and WmipUnreferenceIS.
Referenced by WmipBuildInstanceSet().
NTSTATUS WmipRemoveDataSource (PREGENTRY RegEntry)
Definition at line 2487 of file ds.c.
References _REGENTRY::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, NULL, PAGED_CODE, Status, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, WmipDebugPrintEx, WmipReferenceDS, WmipRemoveDataSourceByDS(), and WmipUnreferenceDS.
Referenced by WmipRemoveDS().
void WmipRemoveDataSourceByDS (PBDATASOURCE DataSource)
Definition at line 2474 of file ds.c.
References PAGED_CODE, RegistrationDelete, WmipGenerateRegistrationNotification(), and WmipUnreferenceDS.
Referenced by WmipRemoveDataSource().
void WmipSendGuidUpdateNotifications (NOTIFICATIONTYPES NotificationType, ULONG GuidCount, PTRCACHE * GuidList)
Definition at line 1149 of file ds.c.
References _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FALSE, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, PTRCACHE::Guid, _MSWmi_GuidRegistrationInfo::GuidCount, _MSWmi_GuidRegistrationInfo::GuidList, memset(), MSWmi_GuidRegistrationInfoGuid, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, _MSWmi_GuidRegistrationInfo::Operation, PAGED_CODE, REGUPDATENAME, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, StringCbCopy, TRUE, WmipAlloc, WmipFree, WmipProcessEvent(), WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipGenerateRegistrationNotification(), and WmipUpdateDataSource().
ULONG WmipUpdateAddGuid (PBDATASOURCE DataSource, PWMIREGGUID RegGuid, PWMIREGINFO WmiRegInfo, ULONG BufferSize, PBINSTANCESET * AddModInstanceSet)
Definition at line 1897 of file ds.c.
References tagInstanceSet::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagInstanceSet::DSISList, FALSE, tagInstanceSet::Flags, WMIREGGUIDW::Guid, tagInstanceSet::GuidEntry, InsertHeadList(), IS_NEWLY_REGISTERED, tagDATASOURCE::ISHead, NT_SUCCESS, NULL, PAGED_CODE, tagDATASOURCE::ProviderId, tagDATASOURCE::RegistryPath, Status, WmipAllocInstanceSet, WmipBuildInstanceSet(), WmipDebugPrintEx, WmipLinkDataSourceToList(), and WmipUnreferenceIS.
Referenced by WmipUpdateModifyGuid().
NTSTATUS WmipUpdateDataSource (PREGENTRY RegEntry, PWMIREGINFOW WmiRegInfo, ULONG RetSize)
Definition at line 2277 of file ds.c.
References Action, _REGENTRY::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagInstanceSet::DSISList, tagInstanceSet::Flags, WMIREGGUIDW::Flags, _LIST_ENTRY::Flink, WMIREGGUIDW::Guid, GUID_MOF_RESOURCE_ADDED_NOTIFICATION, GUID_MOF_RESOURCE_REMOVED_NOTIFICATION, WMIREGINFOW::GuidCount, tagInstanceSet::GuidEntry, tagInstanceSet::GuidISList, PTRCACHE::InstanceSet, IS_NEWLY_REGISTERED, tagGUIDENTRY::ISCount, IsEqualGUID, NULL, PAGED_CODE, RegistrationAdd, RegistrationDelete, RegistrationUpdate, RemoveEntryList(), STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, WmipCachePtrs(), WmipDebugPrintEx, WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), WmipEnterSMCritSection, WmipFree, WmipGenerateBinaryMofNotification(), WmipLeaveSMCritSection, WmipReferenceDS, WmipSendGuidUpdateNotifications(), WmipUnreferenceDS, WmipUnreferenceGE, WmipUnreferenceIS, WmipUpdateModifyGuid(), WmipUpdateRemoveGuid(), WMIREG_FLAG_REMOVE_GUID, and WMIREGINFOW::WmiRegGuid.
Referenced by WmipProcessWmiRegInfo().
ULONG WmipUpdateModifyGuid (PBDATASOURCE DataSource, PWMIREGGUID RegGuid, PWMIREGINFO WmiRegInfo, ULONG BufferSize, PBINSTANCESET * AddModInstanceSet)
Definition at line 2100 of file ds.c.
References DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, WMIREGGUIDW::Guid, tagInstanceSet::GuidEntry, tagInstanceSet::GuidISList, InsertHeadList(), tagInstanceSet::IsBaseName, tagGUIDENTRY::ISHead, NT_SUCCESS, NULL, PAGED_CODE, tagDATASOURCE::ProviderId, tagDATASOURCE::RegistryPath, RemoveEntryList(), Status, WmipAllocInstanceSet, WmipBuildInstanceSet(), WmipDebugPrintEx, WmipFindISInDSByGuid(), WmipFree, WmipIsEqualInstanceSets(), WmipUnreferenceIS, and WmipUpdateAddGuid().
Referenced by WmipUpdateDataSource().
BOOLEAN WmipUpdateRemoveGuid (PBDATASOURCE DataSource, PWMIREGGUID RegGuid, PBINSTANCESET * AddModInstanceSet)
Definition at line 2005 of file ds.c.
References DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, WMIREGGUIDW::Guid, GuidToString(), NULL, PAGED_CODE, tagDATASOURCE::RegistryPath, TRUE, WmipDebugPrintEx, WmipFindISInDSByGuid(), and WmipUnreferenceIS.
Referenced by WmipUpdateDataSource().
Variable Documentation
const GUID RegChangeNotificationGuid
Initial value:
=
{ 0x4ee0b301, 0x94bc, 0x11d0, { 0xa4, 0xec, 0x0, 0xa0, 0xc9, 0x6, 0x29, 0x10 } }
Definition at line 193 of file ds.c.
const GUID WmipBinaryMofGuid = BINARY_MOF_GUID
Definition at line 190 of file ds.c.
Referenced by WmipDSCleanup().