Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/iopm.c File Reference
iopm.c File Reference
#include "ki.h"
Data Structures
struct _MAPINFO
Macros
#define ALIGN_DOWN(address, amt) ((ULONG)(address) & ~((amt) - 1))
#define ALIGN_UP(address, amt) (ALIGN_DOWN((address + (amt) - 1), (amt)))
Typedefs
typedef struct _MAPINFO MAPINFO
typedef struct _MAPINFO * PMAPINFO
Functions
BOOLEAN Ke386IoSetAccessProcess (PKPROCESS Process, ULONG MapNumber)
BOOLEAN Ke386QueryIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
BOOLEAN Ke386SetIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
VOID Ke386SetIOPL (VOID)
VOID KiLoadIopmOffset (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
VOID KiLoadIopmOffset (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID KiSetIoMap (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Macro Definition Documentation
#define ALIGN_DOWN (address, amt) ((ULONG)(address) & ~((amt) - 1))
Definition at line 30 of file iopm.c.
#define ALIGN_UP (address, amt) (ALIGN_DOWN((address + (amt) - 1), (amt)))
Definition at line 31 of file iopm.c.
Referenced by Ke386SetIOPL().
Typedef Documentation
typedef struct _MAPINFO MAPINFO
typedef struct _MAPINFO * PMAPINFO
Function Documentation
BOOLEAN Ke386IoSetAccessProcess (PKPROCESS Process, ULONG MapNumber)
Definition at line 276 of file iopm.c.
References FALSE, IOPM_COUNT, KeGenericCallDpc(), KiComputeIopmOffset, KiLoadIopmOffset(), _MAPINFO::MapOffset, _MAPINFO::Process, and TRUE.
BOOLEAN Ke386QueryIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
Definition at line 192 of file iopm.c.
References DISPATCH_LEVEL, FALSE, IO_ACCESS_MAP_NONE, IOPM_COUNT, IOPM_SIZE, KeLowerIrql, KeRaiseIrql, KiPcr, RtlCopyMemory, and TRUE.
BOOLEAN Ke386SetIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
Definition at line 76 of file iopm.c.
References _KTHREAD::ApcState, FALSE, IO_ACCESS_MAP_NONE, IOPM_COUNT, KeGenericCallDpc(), KeGetCurrentThread(), KiSetIoMap(), _MAPINFO::MapNumber, _MAPINFO::MapSource, _MAPINFO::Process, _KAPC_STATE::Process, and TRUE.
VOID Ke386SetIOPL (VOID)
Definition at line 394 of file iopm.c.
References ALIGN_UP, _KTHREAD::ApcState, CONTEXT_CONTROL, _CONTEXT::ContextFlags, _CONTEXT::EFlags, EFLAGS_IOPL_MASK, _KTHREAD::InitialStack, _KPROCESS::Iopl, _KTHREAD::Iopl, KeContextFromKframes(), KeContextToKframes(), KeGetCurrentThread(), KTRAP_FRAME_ALIGN, NULL, _KAPC_STATE::Process, and UserMode.
Referenced by NtSetInformationProcess().
VOID KiLoadIopmOffset (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Referenced by Ke386IoSetAccessProcess().
VOID KiLoadIopmOffset (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 331 of file iopm.c.
References _KTHREAD::ApcState, _KPRCB::CurrentThread, _KTSS::IoMapBase, _KPROCESS::IopmOffset, KeSignalCallDpcDone(), KiPcr, _MAPINFO::MapOffset, _KPCR::Prcb, _MAPINFO::Process, _KAPC_STATE::Process, _KPCR::TSS, and UNREFERENCED_PARAMETER.
VOID KiSetIoMap (PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 130 of file iopm.c.
References _KTHREAD::ApcState, _KPRCB::CurrentThread, _KiIoAccessMap::IoMap, _KTSS::IoMapBase, _KTSS::IoMaps, IOPM_SIZE, _KPROCESS::IopmOffset, KeSignalCallDpcDone(), KiPcr, _MAPINFO::MapNumber, _MAPINFO::MapSource, _KPCR::Prcb, _KAPC_STATE::Process, RtlCopyMemory, _KPCR::TSS, and UNREFERENCED_PARAMETER.
Referenced by Ke386SetIoAccessMap().