Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/mmfault.c File Reference
mmfault.c File Reference
#include "mi.h"
Macros
#define PROCESS_FOREGROUND_PRIORITY (9)
Functions
NTSTATUS MmAccessFault (IN ULONG_PTR FaultStatus, IN PVOID VirtualAddress, IN KPROCESSOR_MODE PreviousMode, IN PVOID TrapInformation)
NTSTATUS MmGetExecuteOptions (IN PULONG ExecuteOptions)
VOID MmGetImageInformation (OUT PSECTION_IMAGE_INFORMATION ImageInformation)
DECLSPEC_NOINLINE NTSTATUS MmSetExecuteOptions (IN ULONG ExecuteOptions)
Variables
LONG MiDelayPageFaults
Macro Definition Documentation
#define PROCESS_FOREGROUND_PRIORITY (9)
Definition at line 27 of file mmfault.c.
Referenced by MmAccessFault().
Function Documentation
NTSTATUS MmAccessFault (IN ULONG_PTR FaultStatus, IN PVOID VirtualAddress, IN KPROCESSOR_MODE PreviousMode, IN PVOID TrapInformation)
Definition at line 51 of file mmfault.c.
References _MI_PAGING_LEVELS, _ETHREAD::ActiveFaultCount, _IMAGE_ENTRY_IN_SESSION::Address, APC_LEVEL, _ETHREAD::ApcNeeded, ASSERT, ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY, ATTEMPTED_WRITE_TO_READONLY_MEMORY, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _KPROCESS::BasePriority, _MMPFNENTRY::CacheAttribute, _EPROCESS::CloneRoot, CONTAINING_RECORD, _MMPTE_HARDWARE::CopyOnWrite, DbgBreakPoint(), DbgPrintEx(), DemandZeroPde, _MMPTE_HARDWARE::Dirty, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, DRIVER_CAUGHT_MODIFYING_FREED_POOL, _MMPFN::e1, _MMPFN::Event, _KEXECUTE_OPTIONS::ExecuteDisable, _KEXECUTE_OPTIONS::ExecuteEnable, FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _KPROCESS::Flags, _LIST_ENTRY::Flink, _EPROCESS::ForkInProgress, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMSUPPORT_FLAGS::GrowWsleHash, _MMPTE::Hard, HYDRA_PROCESS, HYPER_SPACE, _MM_SESSION_SPACE::ImageList, _IMAGE_ENTRY_IN_SESSION::ImageLoading, InterlockedCompareExchangePte, InterlockedIncrement, IoRetryIrpCompletions(), IsListEmpty, KdPrint, KeAreAllApcsDisabled(), KeBugCheckEx(), KeDelayExecutionThread(), KeFeatureBits, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeInvalidAccessAllowed(), KeLowerIrql, KeRaiseIrql, KernelMode, KeZeroSinglePage, KF_GLOBAL_32BIT_EXECUTE, KF_GLOBAL_32BIT_NOEXECUTE, LOCK_PFN, LOCK_WORKING_SET, LOCK_WS, _MMPTE::Long, LOW_REALTIME_PRIORITY, MI_BARRIER_STAMP_ZEROED_PAGE, MI_BARRIER_SYNCHRONIZE, MI_BREAK_ON_AV, MI_DISABLE_CACHING, MI_DISPLAY_TRAP_INFORMATION, MI_FAULT_STATUS_INDICATES_EXECUTION, MI_FAULT_STATUS_INDICATES_WRITE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_GUARD, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_PAGE_TABLE_OR_HYPER_ADDRESS, MI_IS_PFN(), MI_IS_PTE_EXECUTABLE, MI_IS_SESSION_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MI_IS_SESSION_PTE, MI_MAKE_VALID_PTE, MI_MAKE_VALID_USER_PTE, MI_NO_FAULT_FOUND, MI_PAGE_COLOR_VA_PROCESS, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_PTE_OWNER_KERNEL, MI_RESERVED_BITS_CANONICAL(), MI_SET_PAGE_DIRTY, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiAccessCheck(), MiAllocateWsle(), MiCheckForUserStackOverflow(), MiCheckPdeForPagedPool(), MiCheckPdeForSessionSpace(), MiCheckSystemPteProtection(), MiCheckVirtualAddress(), MiCopyOnWrite(), MiDelayPageFaults, MiDispatchFault(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPde, MiGetVirtualAddressMappedByPte, MiGrowWsleHash(), MiHighestUserPte, MiInitializePfn(), _MMSUPPORT::MinimumWorkingSetSize, MiNonCached, MiProtoAddressForPte, MiPteToProto, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiRemoveZeroPageIfAny, MiReserveSystemPtes(), MiResolveDemandZeroFault(), MiSetDirtyBit(), MiTrimPte(), MiWaitForForkToComplete(), MiWriteCombined, MiZeroPhysicalPage(), Mm30Milliseconds, MM_DEMAND_ZERO_WRITE_PTE, MM_GUARD_PAGE, MM_HIGH_LIMIT, MM_HIGHEST_USER_ADDRESS, MM_NOACCESS, MM_NOIRQL, MM_PLENTY_FREE_LIMIT, MM_PTE_WRITE_MASK, MM_READONLY, MM_READWRITE, MM_SHARED_USER_DATA_VA, MM_UNKNOWN_PROTECTION, MM_ZERO_KERNEL_PTE, MM_ZERO_PTE, MmAvailablePages, MmHalfSecond, MmHighestUserAddress, MmIsRetryIoStatus, MmModifiedPageListHead, MmModifiedPageMaximum, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmPaeMask, MmPageFaultNotifyRoutine, MmProtectedPteList, MmProtectFreedNonPagedPool, MmSessionSpace, MmShortTime, MmSizeOfNonPagedPoolInBytes, MmSystemCacheWs, MmSystemRangeStart, _EPROCESS::ModifiedPageCount, _EPROCESS::NextPageColor, _MMPTE_HARDWARE::NoExecute, NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfPrivatePages, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, _ETHREAD::OwnsSessionWorkingSetExclusive, _ETHREAD::OwnsSessionWorkingSetShared, PAGE_ALIGN, PAGE_FAULT_IN_NONPAGED_AREA, PAGE_SIZE, _MMSUPPORT::PageFaultCount, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _EPROCESS::Pcb, Priority, PROCESS_FOREGROUND_PRIORITY, _MMPTE_SOFTWARE::Protection, _MMPTE_TRANSITION::Protection, _MMPTE::Proto, _MMPTE_SOFTWARE::Prototype, PrototypePte, _MMPFNENTRY::PrototypePte, PS_PROCESS_INJECT_INPAGE_ERRORS, PS_SAME_THREAD_FLAGS_OWNS_A_WORKING_SET, PsGetCurrentProcessByThread, PsGetCurrentThread(), PTE_BASE, _MMPFN::PteFrame, _MMPTE_PROTOTYPE::ReadOnly, _ETHREAD::SameThreadApcFlags, _MMPTE::Soft, STATUS_ACCESS_VIOLATION, STATUS_DEVICE_NOT_CONNECTED, STATUS_GUARD_PAGE_VIOLATION, STATUS_IN_PAGE_ERROR, STATUS_PAGE_FAULT_COPY_ON_WRITE, STATUS_PAGE_FAULT_DEMAND_ZERO, STATUS_SUCCESS, STATUS_WAIT_1, SystemPteSpace, _MMPFNLIST::Total, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WORKING_SET, UNLOCK_WS, UserMode, _MMPTE_HARDWARE::Valid, ValidKernelPte, _EPROCESS::Vm, _MM_SESSION_SPACE::Vm, _MMSUPPORT::WorkingSetSize, _MMPTE_HARDWARE::Write, and ZeroPte.
Referenced by MiDispatchFault(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MmCheckCachedPageState(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
NTSTATUS MmGetExecuteOptions (IN PULONG ExecuteOptions)
Definition at line 2165 of file mmfault.c.
References ASSERT, _KEXECUTE_OPTIONS::DisableThunkEmulation, _KEXECUTE_OPTIONS::ExecuteDisable, _KEXECUTE_OPTIONS::ExecuteDispatchEnable, _KEXECUTE_OPTIONS::ExecuteEnable, _KPROCESS::ExecuteOptions, _KEXECUTE_OPTIONS::ImageDispatchEnable, KeGetCurrentIrql(), MEM_EXECUTE_OPTION_DISABLE, MEM_EXECUTE_OPTION_DISABLE_THUNK_EMULATION, MEM_EXECUTE_OPTION_ENABLE, MEM_EXECUTE_OPTION_EXECUTE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_IMAGE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_PERMANENT, NULL, PASSIVE_LEVEL, _EPROCESS::Pcb, _KEXECUTE_OPTIONS::Permanent, PsGetCurrentProcess(), STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtQueryInformationProcess().
VOID MmGetImageInformation (OUT PSECTION_IMAGE_INFORMATION ImageInformation)
Definition at line 2349 of file mmfault.c.
References ASSERT, _SEGMENT::ImageInformation, NULL, PsGetCurrentProcess(), _EPROCESS::SectionObject, _SECTION::Segment, and _SEGMENT::u2.
Referenced by NtQueryInformationProcess().
DECLSPEC_NOINLINE NTSTATUS MmSetExecuteOptions (IN ULONG ExecuteOptions)
Definition at line 2244 of file mmfault.c.
References ASSERT, _KEXECUTE_OPTIONS::DisableThunkEmulation, _KEXECUTE_OPTIONS::ExecuteDisable, _KEXECUTE_OPTIONS::ExecuteDispatchEnable, _KEXECUTE_OPTIONS::ExecuteEnable, _KPROCESS::Flags, _KEXECUTE_OPTIONS::ImageDispatchEnable, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), MEM_EXECUTE_OPTION_DISABLE, MEM_EXECUTE_OPTION_DISABLE_THUNK_EMULATION, MEM_EXECUTE_OPTION_ENABLE, MEM_EXECUTE_OPTION_EXECUTE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_IMAGE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_PERMANENT, MEM_EXECUTE_OPTION_VALID_FLAGS, NULL, PASSIVE_LEVEL, _EPROCESS::Pcb, _KEXECUTE_OPTIONS::Permanent, _KPROCESS::ProcessLock, PsGetCurrentProcess(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtSetInformationProcess().
Variable Documentation
LONG MiDelayPageFaults
Definition at line 29 of file mmfault.c.
Referenced by MiAllocateLargeZeroPages(), MiFindContiguousPages(), MmAccessFault(), and MmGatherMemoryForHibernate().