Windows Research Kernel v1.2: C:/Windows Research Kernel/se/seinit.c File Reference
seinit.c File Reference
#include "pch.h"
#include "adt.h"
#include <string.h>
Macros
#define SEP_INITIAL_KEY_COUNT 15
#define SEP_INITIAL_LEVEL_COUNT 6L
Functions
BOOLEAN SeInitSystem (VOID)
BOOLEAN SepInitializationPhase0 (VOID)
BOOLEAN SepInitializationPhase1 (VOID)
VOID SepInitProcessAuditSd (VOID)
Macro Definition Documentation
#define SEP_INITIAL_KEY_COUNT 15
Definition at line 30 of file seinit.c.
#define SEP_INITIAL_LEVEL_COUNT 6L
Definition at line 31 of file seinit.c.
Function Documentation
BOOLEAN SeInitSystem (VOID)
Definition at line 40 of file seinit.c.
References InitializationPhase, KeBugCheckEx(), PAGED_CODE, SepInitializationPhase0(), SepInitializationPhase1(), and UNEXPECTED_INITIALIZATION_CALL.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
BOOLEAN SepInitializationPhase0 (VOID)
Definition at line 79 of file seinit.c.
References ExFastRefObjectNull(), ExLuidInitialization(), FALSE, _ETHREAD::ImpersonationInfo, KdPrint, NULL, ObInitializeFastReference(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PsGetCurrentProcess(), PsGetCurrentThread(), SeMakeSystemToken(), SepInitializeWorkList(), SepRmInitPhase0(), SepTokenInitialization(), and SepVariableInitialization().
Referenced by SeInitSystem().
BOOLEAN SepInitializationPhase1 (VOID)
Definition at line 186 of file seinit.c.
References ACL_REVISION, ASSERT, ASSERTMSG, DIRECTORY_ALL_ACCESS, DIRECTORY_QUERY, DIRECTORY_TRAVERSE, ExAllocatePool, ExFastRefGetObject(), ExFreePool(), FALSE, GENERIC_WRITE, InitializeObjectAttributes, NonPagedPool, NotificationEvent, NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NtCreateEvent(), NULL, ObInsertObject(), OBJ_CASE_INSENSITIVE, OBJ_PERMANENT, PAGED_CODE, PsGetCurrentProcess(), READ_CONTROL, RtlAddAccessAllowedAce(), RtlAnsiStringToUnicodeString(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlFreeUnicodeString(), RtlInitString(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SeAnonymousLogonToken, SeAnonymousLogonTokenNoEveryone, SECURITY_DESCRIPTOR_MIN_LENGTH, SECURITY_DESCRIPTOR_REVISION, SeLocalSystemSid, SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SepDevelopmentTest(), SepInitProcessAuditSd(), SePublicDefaultSd, SeWorldSid, Status, and TRUE.
Referenced by SeInitSystem().
VOID SepInitProcessAuditSd (VOID)
Definition at line 730 of file seglobal.c.
References ACL_REVISION2, ASSERT, ExAllocatePoolWithTag, ExFreePool(), FALSE, NonPagedPool, NT_SUCCESS, NULL, RtlAddAccessAllowedAce(), RtlAddAuditAccessAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetSaclSecurityDescriptor(), SECURITY_DESCRIPTOR_REVISION1, SeLengthSid, SeLocalServiceSid, SeLocalSystemSid, SeNetworkServiceSid, SEP_QUERY_MEMBERSHIP, SepAuditFailed(), SepImportantProcessSd, SepProcessAccessesToAudit, SepProcessAuditSd, SeWorldSid, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by SepInitializationPhase1().