Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/api.c File Reference
api.c File Reference
#include "wmikmp.h"
#include "evntrace.h"
#include "tracep.h"
Macros
#define WMIDRIVERNAME L"\\Driver\\WMIxWDM"
#define WmipBuildWnodeHeader(Wnode, WnodeSize, FlagsUlong, Handle)
Functions
NTSTATUS IoWMIAllocateInstanceIds (__in GUID *Guid, __in ULONG InstanceCount, __out ULONG *FirstInstanceId)
NTSTATUS IoWMIDeviceObjectToInstanceName (__in PVOID DataBlockObject, __in PDEVICE_OBJECT DeviceObject, __out PUNICODE_STRING InstanceName)
NTSTATUS IoWMIExecuteMethod (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG MethodId, __in ULONG InBufferSize, __inout PULONG OutBufferSize, __inout_bcount_part_opt(*OutBufferSize, InBufferSize) PUCHAR InOutBuffer)
NTSTATUS IoWMIHandleToInstanceName (__in PVOID DataBlockObject, __in HANDLE FileHandle, __out PUNICODE_STRING InstanceName)
NTSTATUS IoWMIOpenBlock (__in GUID *Guid, __in ULONG DesiredAccess, __out PVOID *DataBlockObject)
NTSTATUS IoWMIQueryAllData (__in PVOID DataBlockObject, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTSTATUS IoWMIQueryAllDataMultiple (__in_ecount(ObjectCount) PVOID *DataBlockObjectList, __in ULONG ObjectCount, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTSTATUS IoWMIQuerySingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTSTATUS IoWMIQuerySingleInstanceMultiple (__in_ecount(ObjectCount) PVOID *DataBlockObjectList, __in_ecount(ObjectCount) PUNICODE_STRING InstanceNames, __in ULONG ObjectCount, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTSTATUS IoWMIRegistrationControl (__in PDEVICE_OBJECT DeviceObject, __in ULONG Action)
NTSTATUS IoWMISetNotificationCallback (__inout PVOID Object, __in WMI_NOTIFICATION_CALLBACK Callback, __in_opt PVOID Context)
NTSTATUS IoWMISetSingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
NTSTATUS IoWMISetSingleItem (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG DataItemId, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
NTSTATUS IoWMISuggestInstanceName (__in_opt PDEVICE_OBJECT PhysicalDeviceObject, __in_opt PUNICODE_STRING SymbolicLinkName, __in BOOLEAN CombineNames, __out PUNICODE_STRING SuggestedInstanceName)
NTSTATUS IoWMIWriteEvent (__inout PVOID WnodeEventItem)
BOOLEAN WMIInitialize (ULONG Phase, PVOID LoaderBlock)
NTSTATUS WmipDriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Variables
PINSTIDCHUNK WmipInstIdChunkHead
Macro Definition Documentation
#define WMIDRIVERNAME L"\\Driver\\WMIxWDM"
Referenced by WMIInitialize().
#define WmipBuildWnodeHeader (Wnode, WnodeSize, FlagsUlong, Handle)
Value:
{ \
    ((PWNODE_HEADER)(Wnode))->Flags = FlagsUlong;                    \
    ((PWNODE_HEADER)(Wnode))->KernelHandle = Handle;                 \
    ((PWNODE_HEADER)(Wnode))->BufferSize = WnodeSize;                \
    ((PWNODE_HEADER)(Wnode))->Linkage = 0;                           \
}
Definition at line 826 of file api.c.
Referenced by IoWMIExecuteMethod(), IoWMIQueryAllData(), IoWMIQuerySingleInstance(), IoWMISetSingleInstance(), and IoWMISetSingleItem().
Function Documentation
NTSTATUS IoWMIAllocateInstanceIds (__in GUID * Guid, __in ULONG InstanceCount, __out ULONG * FirstInstanceId)
Definition at line 261 of file api.c.
References INSTID::BaseId, ExAllocatePoolWithTag, INSTID::Guid, tagINSTIDCHUNK::InstId, INSTIDSPERCHUNK, IsEqualGUID, tagINSTIDCHUNK::Next, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlFillMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, WMIIIPOOLTAG, WmipEnterSMCritSection, WmipInstIdChunkHead, WmipIsWmiNotSetupProperly, and WmipLeaveSMCritSection.
NTSTATUS IoWMIDeviceObjectToInstanceName (__in PVOID DataBlockObject, __in PDEVICE_OBJECT DeviceObject, __out PUNICODE_STRING InstanceName)
Definition at line 1495 of file api.c.
References NULL, PAGED_CODE, Status, and WmipTranslateFileHandle().
NTSTATUS IoWMIExecuteMethod (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG MethodId, __in ULONG InBufferSize, __inout PULONG OutBufferSize, __inout_bcount_part_opt *, InBufferSize PUCHAR InOutBuffer)
Definition at line 1340 of file api.c.
References tagWNODE_METHOD_ITEM::DataBlockOffset, FIELD_OFFSET, _WNODE_HEADER::Flags, IRP_MN_EXECUTE_METHOD, KernelMode, tagWNODE_METHOD_ITEM::MethodId, NT_SUCCESS, NULL, tagWNODE_METHOD_ITEM::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, tagWNODE_METHOD_ITEM::SizeDataBlock, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_METHOD_ITEM, and WNODE_FLAG_TOO_SMALL.
NTSTATUS IoWMIHandleToInstanceName (__in PVOID DataBlockObject, __in HANDLE FileHandle, __out PUNICODE_STRING InstanceName)
Definition at line 1476 of file api.c.
References NULL, PAGED_CODE, Status, and WmipTranslateFileHandle().
NTSTATUS IoWMIOpenBlock (__in GUID * Guid, __in ULONG DesiredAccess, __out PVOID * DataBlockObject)
Definition at line 758 of file api.c.
References _OBJECT_ATTRIBUTES::Attributes, Ioctl, IOCTL_WMI_OPEN_GUID, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, KernelMode, _OBJECT_ATTRIBUTES::Length, NT_SUCCESS, NULL, OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObReferenceObjectByHandle, PAGED_CODE, RtlInitUnicodeString(), RtlZeroMemory, Status, StringCchCopyW(), StringCchPrintfW(), WmiGuidObjectDirectory, WmiGuidObjectDirectoryLength, WmiGuidObjectNameLength, WmipGuidObjectType, WmipOpenBlock(), WRITE_DAC, and ZwClose().
NTSTATUS IoWMIQueryAllData (__in PVOID DataBlockObject, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 833 of file api.c.
References _WNODE_HEADER::Flags, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_NOT_SUPPORTED, WmipBuildWnodeHeader, WmipQueryAllData(), WNODE_FLAG_ALL_DATA, WNODE_FLAG_INTERNAL, WNODE_FLAG_TOO_SMALL, and tagWNODE_ALL_DATA::WnodeHeader.
NTSTATUS IoWMIQueryAllDataMultiple (__in_ecount(ObjectCount) PVOID * DataBlockObjectList, __in ULONG ObjectCount, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 913 of file api.c.
References ARGUMENT_PRESENT, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, WmipQueryAllDataMultiple(), and WNODE_FLAG_TOO_SMALL.
NTSTATUS IoWMIQuerySingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 992 of file api.c.
References tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FIELD_OFFSET, _WNODE_HEADER::Flags, IRP_MN_QUERY_SINGLE_INSTANCE, KernelMode, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_SUPPORTED, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_INTERNAL, WNODE_FLAG_SINGLE_INSTANCE, and WNODE_FLAG_TOO_SMALL.
NTSTATUS IoWMIQuerySingleInstanceMultiple (__in_ecount(ObjectCount) PVOID * DataBlockObjectList, __in_ecount(ObjectCount) PUNICODE_STRING InstanceNames, __in ULONG ObjectCount, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 1106 of file api.c.
References ARGUMENT_PRESENT, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, WmipQuerySingleMultiple(), and WNODE_FLAG_TOO_SMALL.
NTSTATUS IoWMIRegistrationControl (__in PDEVICE_OBJECT DeviceObject, __in ULONG Action)
Definition at line 121 of file api.c.
References FALSE, _REGENTRY::Flags, NT_SUCCESS, NULL, PAGED_CODE, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, WmipDeregisterDevice(), WmipEnterSMCritSection, WmipFindRegEntryByDevice(), WmipIsWmiNotSetupProperly, WmipLeaveSMCritSection, WmipRegisterDevice(), WmipSetTraceNotify(), WmipUnreferenceRegEntry, WmipUpdateRegistration(), WMIREG_ACTION_BLOCK_IRPS, WMIREG_ACTION_DEREGISTER, WMIREG_ACTION_REGISTER, WMIREG_ACTION_REREGISTER, WMIREG_ACTION_UPDATE_GUIDS, WMIREG_FLAG_CALLBACK, WMIREG_FLAG_TRACE_NOTIFY_MASK, and WMIREG_FLAG_TRACE_PROVIDER.
Referenced by WmipDriverEntry().
NTSTATUS IoWMISetNotificationCallback (__inout PVOID Object, __in WMI_NOTIFICATION_CALLBACK Callback, __in_opt PVOID Context)
Definition at line 1452 of file api.c.
References _WMIGUIDOBJECT::Callback, _WMIGUIDOBJECT::CallbackContext, _WMIGUIDOBJECT::Flags, PAGED_CODE, STATUS_SUCCESS, WMIGUID_FLAG_KERNEL_NOTIFICATION, WmipAssert, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
NTSTATUS IoWMISetSingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
Definition at line 1187 of file api.c.
References tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FIELD_OFFSET, IRP_MN_CHANGE_SINGLE_INSTANCE, KernelMode, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, Status, STATUS_INSUFFICIENT_RESOURCES, _WNODE_HEADER::Version, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
NTSTATUS IoWMISetSingleItem (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG DataItemId, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
Definition at line 1263 of file api.c.
References tagWNODE_SINGLE_ITEM::DataBlockOffset, FIELD_OFFSET, IRP_MN_CHANGE_SINGLE_ITEM, tagWNODE_SINGLE_ITEM::ItemId, KernelMode, NULL, tagWNODE_SINGLE_ITEM::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, tagWNODE_SINGLE_ITEM::SizeDataItem, Status, STATUS_INSUFFICIENT_RESOURCES, _WNODE_HEADER::Version, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_SINGLE_ITEM, and tagWNODE_SINGLE_ITEM::WnodeHeader.
NTSTATUS IoWMISuggestInstanceName (__in_opt PDEVICE_OBJECT PhysicalDeviceObject, __in_opt PUNICODE_STRING SymbolicLinkName, __in BOOLEAN CombineNames, __out PUNICODE_STRING SuggestedInstanceName)
Definition at line 362 of file api.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DevicePropertyDeviceDescription, ExAllocatePoolWithTag, ExFreePool(), IoGetDeviceProperty(), IoOpenDeviceInterfaceRegistryKey(), KEY_ALL_ACCESS, KeyValueFullInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlAppendUnicodeToString(), Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_MIX, STATUS_UNSUCCESSFUL, WmipIsWmiNotSetupProperly, WMIPOOLTAG, ZwClose(), and ZwQueryValueKey().
NTSTATUS IoWMIWriteEvent (__inout PVOID WnodeEventItem)
Definition at line 582 of file api.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, DelayedWorkQueue, DPFLTR_WMICORE_ID, ExAllocatePoolWithTag, ExInterlockedInsertTailList(), ExQueueWorkItem(), _WNODE_HEADER::Flags, _WNODE_HEADER::HistoricalContext, InterlockedIncrement, KeAcquireSpinLock, KeReleaseSpinLock(), KernelMode, LARGEKMWNODEEVENTSIZE, EVENTWORKCONTEXT::ListEntry, MAXLOGGERS, NonPagedPool, NULL, _WNODE_HEADER::ProviderId, EVENTWORKCONTEXT::RegEntry, REGENTRY_FLAG_RUNDOWN, Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRACE_HEADER_EVENT_TRACE, TRACE_HEADER_FLAG, TRACE_HEADER_TYPE_FULL_HEADER, _WNODE_HEADER::Version, WmiGetLoggerId, WMINWPOOLTAG, WmipDebugPrintEx, WmipDoFindRegEntryByProviderId, WmipEventWorkItems, WmipEventWorkQueueItem, WmipIsWmiNotSetupProperly, WmipLoggerContext, WmipMaxKmWnodeEventSize, WmipNPEvent, WmipNPNotificationSpinlock, WmipReferenceRegEntry, WmipRegistrationSpinLock, WmiTraceEvent(), WmiTraceFastEvent(), EVENTWORKCONTEXT::Wnode, WNODE_FLAG_LOG_WNODE, and WNODE_FLAG_TRACED_GUID.
BOOLEAN WMIInitialize (ULONG Phase, PVOID LoaderBlock)
Definition at line 57 of file api.c.
References FALSE, IoCreateDriver(), NT_SUCCESS, NULL, RtlInitUnicodeString(), Status, STATUS_SUCCESS, TRUE, UNREFERENCED_PARAMETER, WMIDRIVERNAME, WmipAssert, WmipDriverEntry(), WmipInitializeRegistration(), WmipRegisterFirmwareProviders(), WmipRegisterMcaHandler(), and WmipServiceDeviceObject.
Referenced by IoInitSystem().
NTSTATUS WmipDriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Definition at line 193 of file wmi.c.
Referenced by WMIInitialize().
Variable Documentation
PINSTIDCHUNK WmipInstIdChunkHead
Definition at line 49 of file api.c.
Referenced by IoWMIAllocateInstanceIds().