Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/flush.c File Reference
flush.c File Reference
#include "ki.h"
Functions
BOOLEAN KeInvalidateAllCaches (VOID)
VOID KiInvalidateAllCachesTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Variables
ULONG KeI386CpuType
Function Documentation
BOOLEAN KeInvalidateAllCaches (VOID)
Definition at line 37 of file flush.c.
References FALSE, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeGetCurrentPrcb(), KeI386CpuType, KeLowerIrql, KeRaiseIrqlToSynchLevel(), KeReleaseSpinLockFromDpcLevel(), KiInvalidateAllCachesTarget(), KiIpiSendSynchronousPacket, KiIpiStallOnPacketTargets(), KiReverseStallIpiLock, NULL, _KPRCB::ReverseStall, _KPRCB::SetMember, and TRUE.
VOID KiInvalidateAllCachesTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 154 of file flush.c.
References KiIpiSignalPacketDoneAndStall(), and UNREFERENCED_PARAMETER.
Referenced by KeInvalidateAllCaches().
Variable Documentation
ULONG KeI386CpuType
Definition at line 35 of file i386init.c.
Referenced by KeInvalidateAllCaches().