Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmname.c File Reference
cmname.c File Reference
#include "cmp.h"
Functions
LONG CmpCompareCompressedName (IN PUNICODE_STRING SearchName, IN PWCHAR CompressedName, IN ULONG NameLength, IN ULONG CompareFlags)
LONG CmpCompareTwoCompressedNames (IN PWCHAR CompressedName1, IN ULONG NameLength1, IN PWCHAR CompressedName2, IN ULONG NameLength2)
LONG CmpCompareUnicodeString (IN PUNICODE_STRING SourceName, IN PUNICODE_STRING DestName, IN ULONG CompareFlags)
USHORT CmpCompressedNameSize (IN PWCHAR Name, IN ULONG Length)
VOID CmpCopyCompressedName (IN PWCHAR Destination, IN ULONG DestinationLength, IN PWCHAR Source, IN ULONG SourceLength)
USHORT CmpCopyName (IN PHHIVE Hive, IN PWCHAR Destination, IN PUNICODE_STRING Source)
USHORT CmpNameSize (IN PHHIVE Hive, IN PUNICODE_STRING Name)
Function Documentation
LONG CmpCompareCompressedName (IN PUNICODE_STRING SearchName, IN PWCHAR CompressedName, IN ULONG NameLength, IN ULONG CompareFlags)
Definition at line 196 of file cmname.c.
References CMP_DEST_UP, CMP_SOURCE_UP, and CmUpcaseUnicodeChar.
Referenced by CmpCacheLookup(), CmpCheckLexicographicalOrder(), CmpDoCompareKeyName(), CmpFindNameInList(), CmpFindValueByNameFromCache(), and CmpGetNameControlBlock().
LONG CmpCompareTwoCompressedNames (IN PWCHAR CompressedName1, IN ULONG NameLength1, IN PWCHAR CompressedName2, IN ULONG NameLength2)
Definition at line 330 of file cmname.c.
References CmUpcaseUnicodeChar.
Referenced by CmpCheckLexicographicalOrder().
LONG CmpCompareUnicodeString (IN PUNICODE_STRING SourceName, IN PUNICODE_STRING DestName, IN ULONG CompareFlags)
Definition at line 265 of file cmname.c.
References CMP_DEST_UP, CMP_SOURCE_UP, and CmUpcaseUnicodeChar.
Referenced by CmpCacheLookup().
USHORT CmpCompressedNameSize (IN PWCHAR Name, IN ULONG Length)
Definition at line 121 of file cmname.c.
References UNREFERENCED_PARAMETER.
Referenced by CmpAddDriverToList(), CmpAddSubKey(), CmpFindProfileOption(), CmpInitializeKeyNameString(), CmpInitializeValueNameString(), CmpMarkIndexDirty(), CmpQueryKeyDataFromCache(), and CmpRemoveSubKey().
VOID CmpCopyCompressedName (IN PWCHAR Destination, IN ULONG DestinationLength, IN PWCHAR Source, IN ULONG SourceLength)
Definition at line 153 of file cmname.c.
Referenced by CmpAddDriverToList(), CmpAddSubKey(), CmpFindProfileOption(), CmpGetHiveName(), CmpInitializeKeyNameString(), CmpInitializeValueNameString(), CmpLoadHiveVolatile(), CmpMarkIndexDirty(), CmpQueryKeyData(), CmpQueryKeyValueData(), and CmpRemoveSubKey().
USHORT CmpCopyName (IN PHHIVE Hive, IN PWCHAR Destination, IN PUNICODE_STRING Source)
Definition at line 74 of file cmname.c.
References RtlCopyMemory.
Referenced by CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreateChild(), CmpSetValueKeyNew(), and CmRenameKey().
USHORT CmpNameSize (IN PHHIVE Hive, IN PUNICODE_STRING Name)
Definition at line 33 of file cmname.c.