Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/i386/psldt.c File Reference
psldt.c File Reference
#include "psp.h"
Macros
#define DESCRIPTOR_CONFORM 0x00001C00
#define DESCRIPTOR_DPL 0x00006000
#define DESCRIPTOR_GRAN 0x00800000
#define DESCRIPTOR_NP 0x00008000
#define DESCRIPTOR_SYSTEM 0x00001000
#define DESCRIPTOR_TYPEDPL 0x00007F00
Functions
NTSTATUS NtSetLdtEntries (__in ULONG Selector0, __in ULONG Entry0Low, __in ULONG Entry0Hi, __in ULONG Selector1, __in ULONG Entry1Low, __in ULONG Entry1Hi)
PLDT_ENTRY PspCreateLdt (IN PLDT_ENTRY Ldt, IN ULONG Offset, IN ULONG Size, IN ULONG AllocationSize)
VOID PspDeleteLdt (IN PEPROCESS Process)
LOGICAL PspIsDescriptorValid (IN PLDT_ENTRY Descriptor)
NTSTATUS PspLdtInitialize (VOID)
NTSTATUS PspQueryDescriptorThread (PETHREAD Thread, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength)
NTSTATUS PspQueryLdtInformation (IN PEPROCESS Process, OUT PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength, OUT PULONG ReturnLength)
NTSTATUS PspSetLdtInformation (IN PEPROCESS Process, IN PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength)
NTSTATUS PspSetLdtSize (IN PEPROCESS Process, IN PPROCESS_LDT_SIZE LdtSize, IN ULONG LdtSizeLength)
NTSTATUS PsSetLdtEntries (IN ULONG Selector0, IN ULONG Entry0Low, IN ULONG Entry0Hi, IN ULONG Selector1, IN ULONG Entry1Low, IN ULONG Entry1Hi)
NTSTATUS PsSetProcessLdtInfo (IN PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength)
Variables
KMUTEX LdtMutex
Macro Definition Documentation
#define DESCRIPTOR_CONFORM 0x00001C00
Definition at line 38 of file psldt.c.
#define DESCRIPTOR_DPL 0x00006000
Definition at line 39 of file psldt.c.
#define DESCRIPTOR_GRAN 0x00800000
Definition at line 35 of file psldt.c.
#define DESCRIPTOR_NP 0x00008000
Definition at line 36 of file psldt.c.
#define DESCRIPTOR_SYSTEM 0x00001000
Definition at line 37 of file psldt.c.
#define DESCRIPTOR_TYPEDPL 0x00007F00
Definition at line 40 of file psldt.c.
Function Documentation
NTSTATUS NtSetLdtEntries (__in ULONG Selector0, __in ULONG Entry0Low, __in ULONG Entry0Hi, __in ULONG Selector1, __in ULONG Entry1Low, __in ULONG Entry1Hi)
Definition at line 1465 of file psldt.c.
References PsSetLdtEntries().
PLDT_ENTRY PspCreateLdt (IN PLDT_ENTRY Ldt, IN ULONG Offset, IN ULONG Size, IN ULONG AllocationSize)
Definition at line 822 of file psldt.c.
References ASSERT, ExAllocatePoolWithTag, NonPagedPool, NULL, PAGED_CODE, RtlCopyMemory, and RtlZeroMemory.
Referenced by PspSetLdtInformation(), PspSetLdtSize(), and PsSetProcessLdtInfo().
VOID PspDeleteLdt (IN PEPROCESS Process)
Definition at line 1118 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ExFreePool(), _LDTINFORMATION::Ldt, NULL, PAGED_CODE, PsReturnProcessNonPagedPoolQuota(), and UNREFERENCED_PARAMETER.
LOGICAL PspIsDescriptorValid (IN PLDT_ENTRY Descriptor)
Definition at line 870 of file psldt.c.
References FALSE, MM_HIGHEST_USER_ADDRESS, PAGED_CODE, and TRUE.
Referenced by PspSetLdtInformation(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
NTSTATUS PspLdtInitialize (VOID)
Definition at line 77 of file psldt.c.
References KeInitializeMutex(), and STATUS_SUCCESS.
Referenced by PspInitPhase0().
NTSTATUS PspQueryDescriptorThread (PETHREAD Thread, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength)
Definition at line 992 of file psldt.c.
References ARGUMENT_PRESENT, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, Ke386GetGdtEntryThread(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), KGDT_NUMBER, _EPROCESS::LdtInformation, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, _DESCRIPTOR_TABLE_ENTRY::Selector, SELECTOR_TABLE_INDEX, Status, STATUS_ACCESS_VIOLATION, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_LDT, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, and UNREFERENCED_PARAMETER.
NTSTATUS PspQueryLdtInformation (IN PEPROCESS Process, OUT PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength, OUT PULONG ReturnLength)
Definition at line 103 of file psldt.c.
References ARGUMENT_PRESENT, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, _LDTINFORMATION::Size, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_LDT_OFFSET, STATUS_INVALID_LDT_SIZE, and STATUS_SUCCESS.
NTSTATUS PspSetLdtInformation (IN PEPROCESS Process, IN PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength)
Definition at line 484 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ASSERT, ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, Ke386SetDescriptorProcess(), Ke386SetLdtProcess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, _LDT_INFORMATION::LdtEntries, _LDT_INFORMATION::Length, NonPagedPool, NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, PsChargeProcessNonPagedPoolQuota(), PspCreateLdt(), PspIsDescriptorValid(), PsReturnProcessNonPagedPoolQuota(), ROUND_TO_PAGES, RtlCopyMemory, RtlZeroMemory, _LDTINFORMATION::Size, _LDT_INFORMATION::Start, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_LDT_DESCRIPTOR, STATUS_INVALID_LDT_OFFSET, STATUS_INVALID_LDT_SIZE, and STATUS_SUCCESS.
NTSTATUS PspSetLdtSize (IN PEPROCESS Process, IN PPROCESS_LDT_SIZE LdtSize, IN ULONG LdtSizeLength)
Definition at line 294 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, Ke386SetLdtProcess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, PspCreateLdt(), PsReturnProcessNonPagedPoolQuota(), ROUND_TO_PAGES, _LDTINFORMATION::Size, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_LDT_SIZE, STATUS_NO_LDT, and STATUS_SUCCESS.
NTSTATUS PsSetLdtEntries (IN ULONG Selector0, IN ULONG Entry0Low, IN ULONG Entry0Hi, IN ULONG Selector1, IN ULONG Entry1Low, IN ULONG Entry1Hi)
Definition at line 1152 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ASSERT, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, Ke386SetDescriptorProcess(), Ke386SetLdtProcess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, _EPROCESS::LdtInformation, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, ProcessLdtInformation, PsChargeProcessNonPagedPoolQuota(), PsGetCurrentProcess(), PspIsDescriptorValid(), PsReturnProcessNonPagedPoolQuota(), ROUND_TO_PAGES, RPL_MASK, RtlCopyMemory, RtlZeroMemory, SELECTOR_TABLE_INDEX, _LDTINFORMATION::Size, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_LDT_DESCRIPTOR, and STATUS_SUCCESS.
Referenced by NtSetLdtEntries().
NTSTATUS PsSetProcessLdtInfo (IN PPROCESS_LDT_INFORMATION LdtInformation, IN ULONG LdtInformationLength)
Definition at line 1508 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ASSERT, ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, Ke386SetDescriptorProcess(), Ke386SetLdtProcess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), _LDTINFORMATION::Ldt, _LDT_INFORMATION::LdtEntries, _EPROCESS::LdtInformation, _LDT_INFORMATION::Length, NonPagedPool, NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, _EPROCESS::Pcb, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, PsChargeProcessNonPagedPoolQuota(), PsGetCurrentProcess(), PspCreateLdt(), PspIsDescriptorValid(), PsReturnProcessNonPagedPoolQuota(), ROUND_TO_PAGES, RtlCopyMemory, RtlZeroMemory, _LDTINFORMATION::Size, _LDT_INFORMATION::Start, Status, STATUS_ACCESS_VIOLATION, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_LDT_DESCRIPTOR, STATUS_INVALID_LDT_OFFSET, STATUS_INVALID_LDT_SIZE, and STATUS_SUCCESS.
Variable Documentation
KMUTEX LdtMutex
Definition at line 43 of file psldt.c.