Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ke.h File Reference
ke.h File Reference
Data Structures
struct _KNODE::_flags
struct _KAPC_STATE
struct _KBUGCHECK_CALLBACK_RECORD
struct _KBUGCHECK_DUMP_IO
struct _KBUGCHECK_REASON_CALLBACK_RECORD
struct _KBUGCHECK_SECONDARY_DUMP_DATA
struct _KDEVICE_QUEUE
struct _KDEVICE_QUEUE_ENTRY
struct _KEVENT_PAIR
struct _KEXECUTE_OPTIONS
struct _KGUARDED_MUTEX
struct _KINTERRUPT
struct _KMUTANT
struct _KNODE
struct _KPROCESS
struct _KPROCESS_VALUES
struct _KPROFILE
struct _KQUEUE
struct _KSEMAPHORE
struct _KSERVICE_TABLE_DESCRIPTOR
struct _KTHREAD
struct _KTHREAD_SWITCH_COUNTERS
struct _KWAIT_BLOCK
Macros
#define _DECL_HAL_KE_IMPORT __declspec(dllimport)
#define AFFINITY_MASK(n) (KiAffinityArray[n])
#define ASSERT_PROCESS(object) ASSERT((object)->Header.Type == ProcessObject)
#define ASSERT_QUEUE(Q) ASSERT(((Q)->Header.Type & KOBJECT_TYPE_MASK) == QueueObject);
#define ASSERT_THREAD(object) ASSERT((object)->Header.Type == ThreadObject)
#define BASE_PRIORITY_THRESHOLD NORMAL_BASE_PRIORITY
#define CLOCK_QUANTUM_DECREMENT 3
#define DISPATCHER_OBJECT_TYPE_MASK 0x7
#define DMA_READ_DCACHE_INVALIDATE 0x1
#define DMA_READ_ICACHE_INVALIDATE 0x2
#define DMA_WRITE_DCACHE_SNOOP 0x4
#define EVENT_WAIT_BLOCK 2
#define EXCEPTION_ALIGNMENT_CHECK 0x011
#define EXCEPTION_BOUND_CHECK 5
#define EXCEPTION_DEBUG 1
#define EXCEPTION_DIVIDED_BY_ZERO 0
#define EXCEPTION_DOUBLE_FAULT 8
#define EXCEPTION_GP_FAULT 0x0D
#define EXCEPTION_INT3 3
#define EXCEPTION_INVALID_OPCODE 6
#define EXCEPTION_INVALID_TSS 0x0A
#define EXCEPTION_NMI 2
#define EXCEPTION_NPX_ERROR 0x010
#define EXCEPTION_NPX_NOT_AVAILABLE 7
#define EXCEPTION_NPX_OVERRUN 9
#define EXCEPTION_RESERVED_TRAP 0x0F
#define EXCEPTION_SEGMENT_NOT_PRESENT 0x0B
#define EXCEPTION_STACK_FAULT 0x0C
#define GM_LOCK_BIT 0x1
#define GM_LOCK_BIT_V 0x0
#define GM_LOCK_WAITER_INC 0x4
#define GM_LOCK_WAITER_WOKEN 0x2
#define KAPC_STATE_ACTUAL_LENGTH (FIELD_OFFSET(KAPC_STATE, UserApcPending) + sizeof(BOOLEAN))
#define KeAcquireSpinLock(a, b) *(b) = KfAcquireSpinLock(a)
#define KeAcquireSpinLockAtDpcLevel(a) KefAcquireSpinLockAtDpcLevel(a)
#define KeClearEvent(Event) (Event)->Header.SignalState = 0
#define KeCopyPage(d, s) RtlCopyMemory((d),(s),PAGE_SIZE)
#define KeFindFirstSetLeftAffinity(Set, Member) KeFindFirstSetLeftMember(Set, Member)
#define KeGetCurrentApcEnvironment() KeGetCurrentThread()->ApcStateIndex
#define KeGetCurrentNode() (KeGetCurrentPrcb()->ParentNode)
#define KeGetPreviousMode() (KeGetCurrentThread()->PreviousMode)
#define KeGetPreviousModeByThread(xxCurrentThread)
#define KeInitializeCallbackRecord(CallbackRecord) (CallbackRecord)->State = BufferEmpty
#define KeInitializeEvent(_Event, _Type, _State)
#define KeIsAttachedProcess() KiIsAttachedProcess()
#define KeLowerIrql(a) KfLowerIrql(a)
#define KeQueuedSpinLockContext(n) (&(KeGetCurrentPrcb()->LockQueue[n]))
#define KeRaiseIrql(a, b) *(b) = KfRaiseIrql(a)
#define KeReleaseSpinLock(a, b) KfReleaseSpinLock(a,b)
#define KeReleaseSpinLockFromDpcLevel(a) KefReleaseSpinLockFromDpcLevel(a)
#define KeSetHighEventPair(EventPair, Increment, Wait)
#define KeSetHighWaitLowEventPair(EventPair, WaitMode)
#define KeSetLowEventPair(EventPair, Increment, Wait)
#define KeSetLowWaitHighEventPair(EventPair, WaitMode)
#define KeTerminateProcess(Process) (Process)->StackCount += 1;
#define KeWaitForHighEventPair(EventPair, WaitMode, Alertable, TimeOut)
#define KeWaitForLowEventPair(EventPair, WaitMode, Alertable, TimeOut)
#define KeWaitForMutexObject KeWaitForSingleObject
#define KeZeroSinglePage(v) KeZeroPages((v), PAGE_SIZE)
#define KI_SLIST_FAULT_COUNT_MAXIMUM 1024
#define KiAffinityArray KiMask32Array
#define KiBugCheck3(b, p1, p2, p3) KeBugCheckEx(b,p1,p2,p3,0)
#define KiIsAttachedProcess() (KeGetCurrentThread()->ApcStateIndex == AttachedApcEnvironment)
#define KiLockDispatcherDatabase(OldIrql) *(OldIrql) = KeAcquireQueuedSpinLockRaiseToSynch(LockQueueDispatcherLock)
#define KiLockDispatcherDatabaseAtSynchLevel() KeAcquireQueuedSpinLockAtDpcLevel(&KeGetCurrentPrcb()->LockQueue[LockQueueDispatcherLock])
#define KiQueryLowTickCount() KeTickCount.LowPart
#define KiQuerySystemTime(CurrentTime)
#define KiTryToLockDispatcherDatabase(OldIrql) KeTryToAcquireQueuedSpinLockRaiseToSynch(LockQueueDispatcherLock,OldIrql)
#define KiUnlockDispatcherDatabaseFromSynchLevel() KeReleaseQueuedSpinLockFromDpcLevel(&KeGetCurrentPrcb()->LockQueue[LockQueueDispatcherLock])
#define KOBJECT_LOCK_BIT 0x80
#define KOBJECT_LOCK_BIT_NUMBER 7
#define KOBJECT_TYPE_MASK 0x7f
#define KPROCESS_AUTO_ALIGNMENT_BIT 0
#define KPROCESS_DISABLE_BOOST_BIT 1
#define KPROCESS_DISABLE_QUANTUM_BIT 2
#define KSEMAPHORE_ACTUAL_LENGTH (FIELD_OFFSET(KSEMAPHORE, Limit) + sizeof(LONG))
#define KTHREAD_AUTO_ALIGNMENT_BIT 0
#define KTHREAD_DISABLE_BOOST_BIT 1
#define KWAIT_BLOCK_OFFSET_TO_BYTE0 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 0)
#define KWAIT_BLOCK_OFFSET_TO_BYTE1 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 1)
#define KWAIT_BLOCK_OFFSET_TO_BYTE2 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 2)
#define KWAIT_BLOCK_OFFSET_TO_BYTE3 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 3)
#define LOCK_OWNERSHIP_QUANTUM (WAIT_QUANTUM_DECREMENT * 4)
#define MAXIMUM_CCNUMA_NODES 16
#define NUMBER_SERVICE_TABLES 2
#define PAUSE_PROCESSOR _asm { rep nop }
#define PRIORITY_MASK(n) (KiMask32Array[n])
#define READY_SKIP_QUANTUM 2
#define ROUND_TRIP_DECREMENT_COUNT 16
#define SEMAPHORE_WAIT_BLOCK 2
#define SERVICE_NUMBER_MASK ((1 << 12) - 1)
#define SERVICE_TABLE_MASK (((1 << 1) - 1) << 4)
#define SERVICE_TABLE_SHIFT (12 - 4)
#define SERVICE_TABLE_TEST (WIN32K_SERVICE_INDEX << 4)
#define SYSTEM_SERVICE_INDEX 0
#define THREAD_QUANTUM (READY_SKIP_QUANTUM * CLOCK_QUANTUM_DECREMENT)
#define THREAD_WAIT_OBJECTS 3
#define TIMER_WAIT_BLOCK 3
#define WAIT_QUANTUM_DECREMENT 1
#define WIN32K_SERVICE_INDEX 1
Typedefs
typedef enum _ADJUST_REASON ADJUST_REASON
typedef enum _FIRMWARE_REENTRY FIRMWARE_REENTRY
typedef enum _KAPC_ENVIRONMENT KAPC_ENVIRONMENT
typedef struct _KAPC_STATE KAPC_STATE
typedef enum _KBUGCHECK_BUFFER_DUMP_STATE KBUGCHECK_BUFFER_DUMP_STATE
typedef enum _KBUGCHECK_CALLBACK_REASON KBUGCHECK_CALLBACK_REASON
typedef struct _KBUGCHECK_CALLBACK_RECORD KBUGCHECK_CALLBACK_RECORD
typedef struct _KBUGCHECK_DUMP_IO KBUGCHECK_DUMP_IO
typedef enum _KBUGCHECK_DUMP_IO_TYPE KBUGCHECK_DUMP_IO_TYPE
typedef struct _KBUGCHECK_REASON_CALLBACK_RECORD KBUGCHECK_REASON_CALLBACK_RECORD
typedef struct _KBUGCHECK_SECONDARY_DUMP_DATA KBUGCHECK_SECONDARY_DUMP_DATA
typedef struct _KDEVICE_QUEUE KDEVICE_QUEUE
typedef struct _KDEVICE_QUEUE_ENTRY KDEVICE_QUEUE_ENTRY
typedef VOID(FASTCALL * KE_ZERO_PAGE_ROUTINE) (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
typedef struct _KEVENT_PAIR KEVENT_PAIR
typedef struct _KEXECUTE_OPTIONS KEXECUTE_OPTIONS
typedef struct _KGUARDED_MUTEX KGUARDED_MUTEX
typedef struct _KINTERRUPT KINTERRUPT
typedef enum _KINTERRUPT_MODE KINTERRUPT_MODE
typedef struct _KMUTANT KMUTANT
typedef struct _KMUTANT KMUTEX
typedef struct DECLSPEC_CACHEALIGN _KNODE KNODE
typedef enum _KOBJECTS KOBJECTS
typedef ULONG KPAGE_FRAME
typedef struct _KPROCESS KPROCESS
typedef enum _KPROCESS_STATE KPROCESS_STATE
typedef struct _KPROCESS_VALUES KPROCESS_VALUES
typedef struct _KPROFILE KPROFILE
typedef struct _KQUEUE KQUEUE
typedef struct _KSEMAPHORE KSEMAPHORE
typedef struct _KSERVICE_TABLE_DESCRIPTOR KSERVICE_TABLE_DESCRIPTOR
typedef struct _KTHREAD KTHREAD
typedef enum _KTHREAD_STATE KTHREAD_STATE
typedef struct _KTHREAD_SWITCH_COUNTERS KTHREAD_SWITCH_COUNTERS
typedef struct _KWAIT_BLOCK KWAIT_BLOCK
typedef enum _KWAIT_REASON KWAIT_REASON
typedef enum _MEMORY_CACHING_TYPE MEMORY_CACHING_TYPE
typedef enum _MEMORY_CACHING_TYPE_ORIG MEMORY_CACHING_TYPE_ORIG
typedef enum _FIRMWARE_REENTRY * PFIRMWARE_REENTRY
typedef VOID(* PGDI_BATCHFLUSH_ROUTINE) (VOID)
typedef struct _KAPC_STATE * PKAPC_STATE
typedef struct _KBUGCHECK_CALLBACK_RECORD * PKBUGCHECK_CALLBACK_RECORD
typedef VOID(* PKBUGCHECK_CALLBACK_ROUTINE) (IN PVOID Buffer, IN ULONG Length)
typedef struct _KBUGCHECK_DUMP_IO * PKBUGCHECK_DUMP_IO
typedef struct _KBUGCHECK_REASON_CALLBACK_RECORD * PKBUGCHECK_REASON_CALLBACK_RECORD
typedef VOID(* PKBUGCHECK_REASON_CALLBACK_ROUTINE) (IN KBUGCHECK_CALLBACK_REASON Reason, IN struct _KBUGCHECK_REASON_CALLBACK_RECORD *Record, IN OUT PVOID ReasonSpecificData, IN ULONG ReasonSpecificDataLength)
typedef struct _KBUGCHECK_SECONDARY_DUMP_DATA * PKBUGCHECK_SECONDARY_DUMP_DATA
typedef BOOLEAN(* PKDEBUG_ROUTINE) (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame, IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN SecondChance)
typedef BOOLEAN(* PKDEBUG_SWITCH_ROUTINE) (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN BOOLEAN SecondChance)
typedef struct _KDEVICE_QUEUE * PKDEVICE_QUEUE
typedef struct _KDEVICE_QUEUE_ENTRY * PKDEVICE_QUEUE_ENTRY
typedef PCHAR(* PKE_BUGCHECK_UNICODE_TO_ANSI) (IN PUNICODE_STRING UnicodeString, OUT PCHAR AnsiBuffer, IN ULONG MaxAnsiLength)
typedef struct _KEVENT_PAIR * PKEVENT_PAIR
typedef struct _KEXECUTE_OPTIONS PKEXECUTE_OPTIONS
typedef struct _KGUARDED_MUTEX * PKGUARDED_MUTEX
typedef struct _KINTERRUPT * PKINTERRUPT
typedef ULONG_PTR(* PKIPI_BROADCAST_WORKER) (IN ULONG_PTR Argument)
typedef struct _KMUTANT * PKMUTANT
typedef struct _KMUTANT * PKMUTEX
typedef struct DECLSPEC_CACHEALIGN _KNODE * PKNODE
typedef struct _KPROCESS * PKPROCESS
typedef struct _KPROCESS_VALUES * PKPROCESS_VALUES
typedef struct _KPROFILE * PKPROFILE
typedef struct _KQUEUE * PKQUEUE
typedef struct _KSEMAPHORE * PKSEMAPHORE
typedef BOOLEAN(* PKSERVICE_ROUTINE) (IN struct _KINTERRUPT *Interrupt, IN PVOID ServiceContext)
typedef struct _KSERVICE_TABLE_DESCRIPTOR * PKSERVICE_TABLE_DESCRIPTOR
typedef VOID(* PKSTART_ROUTINE) (IN PVOID StartContext)
typedef VOID(* PKSYSTEM_ROUTINE) (IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext OPTIONAL)
typedef struct _KTHREAD * PKTHREAD
typedef struct _KTHREAD_SWITCH_COUNTERS * PKTHREAD_SWITCH_COUNTERS
typedef struct _KWAIT_BLOCK * PKWAIT_BLOCK
typedef BOOLEAN(* PNMI_CALLBACK) (__in_opt PVOID Context, __in BOOLEAN Handled)
typedef struct _KAPC_STATE * PRKAPC_STATE
typedef struct _KDEVICE_QUEUE * PRKDEVICE_QUEUE
typedef struct _KDEVICE_QUEUE_ENTRY * PRKDEVICE_QUEUE_ENTRY
typedef struct _KEVENT_PAIR * PRKEVENT_PAIR
typedef struct _KINTERRUPT * PRKINTERRUPT
typedef struct _KMUTANT * PRKMUTANT
typedef struct _KMUTANT * PRKMUTEX
typedef struct _KPROCESS * PRKPROCESS
typedef struct _KPROFILE * PRKPROFILE
typedef struct _KQUEUE * PRKQUEUE
typedef struct _KSEMAPHORE * PRKSEMAPHORE
typedef struct _KTHREAD * PRKTHREAD
typedef struct _KWAIT_BLOCK * PRKWAIT_BLOCK
Enumerations
enum _ADJUST_REASON { AdjustNone = 0, AdjustUnwait = 1, AdjustBoost = 2 }
enum _FIRMWARE_REENTRY {
HalHaltRoutine, HalPowerDownRoutine, HalRestartRoutine, HalRebootRoutine,
HalInteractiveModeRoutine, HalMaximumRoutine
}
enum _KAPC_ENVIRONMENT { OriginalApcEnvironment, AttachedApcEnvironment, CurrentApcEnvironment, InsertApcEnvironment }
enum _KBUGCHECK_BUFFER_DUMP_STATE {
BufferEmpty, BufferInserted, BufferStarted, BufferFinished,
BufferIncomplete
}
enum _KBUGCHECK_CALLBACK_REASON { KbCallbackInvalid, KbCallbackReserved1, KbCallbackSecondaryDumpData, KbCallbackDumpIo }
enum _KBUGCHECK_DUMP_IO_TYPE {
KbDumpIoInvalid, KbDumpIoHeader, KbDumpIoBody, KbDumpIoSecondaryData,
KbDumpIoComplete
}
enum _KINTERRUPT_MODE { LevelSensitive, Latched }
enum _KOBJECTS {
EventNotificationObject = 0, EventSynchronizationObject = 1, MutantObject = 2, ProcessObject = 3,
QueueObject = 4, SemaphoreObject = 5, ThreadObject = 6, GateObject = 7,
TimerNotificationObject = 8, TimerSynchronizationObject = 9, Spare2Object = 10, Spare3Object = 11,
Spare4Object = 12, Spare5Object = 13, Spare6Object = 14, Spare7Object = 15,
Spare8Object = 16, Spare9Object = 17, ApcObject, DpcObject,
DeviceQueueObject, EventPairObject, InterruptObject, ProfileObject,
ThreadedDpcObject, MaximumKernelObject
}
enum _KPROCESS_STATE {
ProcessInMemory, ProcessOutOfMemory, ProcessInTransition, ProcessOutTransition,
ProcessInSwap, ProcessOutSwap
}
enum _KTHREAD_STATE {
Initialized, Ready, Running, Standby,
Terminated, Waiting, Transition, DeferredReady,
GateWait
}
enum _KWAIT_REASON {
Executive, FreePage, PageIn, PoolAllocation,
DelayExecution, Suspended, UserRequest, WrExecutive,
WrFreePage, WrPageIn, WrPoolAllocation, WrDelayExecution,
WrSuspended, WrUserRequest, WrEventPair, WrQueue,
WrLpcReceive, WrLpcReply, WrVirtualMemory, WrPageOut,
WrRendezvous, Spare2, Spare3, Spare4,
Spare5, Spare6, WrKernel, WrResource,
WrPushLock, WrMutex, WrQuantumEnd, WrDispatchInt,
WrPreempted, WrYieldExecution, WrFastMutex, WrGuardedMutex,
WrRundown, MaximumWaitReason
}
enum _MEMORY_CACHING_TYPE {
MmNonCached = FALSE, MmCached = TRUE, MmWriteCombined = MmFrameBufferCached, MmHardwareCoherentCached,
MmNonCachedUnordered, MmUSWCCached, MmMaximumCacheType
}
enum _MEMORY_CACHING_TYPE_ORIG { MmFrameBufferCached = 2 }
enum KCONTINUE_STATUS { ContinueError = FALSE, ContinueSuccess = TRUE, ContinueProcessorReselected, ContinueNextProcessor }
Functions
C_ASSERT ((MaximumKernelObject &KOBJECT_LOCK_BIT)==0)
C_ASSERT (THREAD_WAIT_OBJECTS >=3)
C_ASSERT (MAXIMUM_WAIT_OBJECTS<=255)
C_ASSERT (sizeof(KDEVICE_QUEUE)==0x14)
C_ASSERT (sizeof(KDEVICE_QUEUE_ENTRY)==0x10)
BOOLEAN KdpStub (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame, IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN SecondChance)
_DECL_HAL_KE_IMPORT VOID FASTCALL KeAcquireInStackQueuedSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
NTKERNELAPI VOID FASTCALL KeAcquireInStackQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
NTKERNELAPI VOID FASTCALL KeAcquireInStackQueuedSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
_DECL_HAL_KE_IMPORT VOID FASTCALL KeAcquireInStackQueuedSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
NTKERNELAPI KIRQL KeAcquireInterruptSpinLock (__inout PKINTERRUPT Interrupt)
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KeAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number)
VOID FASTCALL KeAcquireQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KeAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number)
NTKERNELAPI KIRQL FASTCALL KeAcquireSpinLockForDpc (__inout PKSPIN_LOCK SpinLock)
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KeAcquireSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock)
NTKERNELAPI BOOLEAN KeAddSystemServiceTable (IN PULONG_PTR Base, IN PULONG Count OPTIONAL, IN ULONG Limit, IN PUCHAR Number, IN ULONG Index)
BOOLEAN KeAdjustInterruptTime (IN LONGLONG TimeDelta)
ULONG KeAlertResumeThread (__inout PKTHREAD Thread)
BOOLEAN KeAlertThread (__inout PKTHREAD Thread, __in KPROCESSOR_MODE ProcessorMode)
NTKERNELAPI VOID KeAttachProcess (__inout PRKPROCESS Process)
VOID KeBalanceSetManager (IN PVOID Context)
VOID KeBoostPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Increment)
NTKERNELAPI DECLSPEC_NORETURN VOID NTAPI KeBugCheck (__in ULONG BugCheckCode)
VOID KeBugCheck2 (__in ULONG BugCheckCode, __in ULONG_PTR BugCheckParameter1, __in ULONG_PTR BugCheckParameter2, __in ULONG_PTR BugCheckParameter3, __in ULONG_PTR BugCheckParameter4, __in_opt PKTRAP_FRAME TrapFrame)
NTKERNELAPI DECLSPEC_NORETURN VOID KeBugCheckEx (__in ULONG BugCheckCode, __in ULONG_PTR BugCheckParameter1, __in ULONG_PTR BugCheckParameter2, __in ULONG_PTR BugCheckParameter3, __in ULONG_PTR BugCheckParameter4)
NTKERNELAPI BOOLEAN KeCancelTimer (__inout PKTIMER)
VOID KeCheckForTimer (__in_bcount(BlockSize) PVOID BlockStart, __in SIZE_T BlockSize)
VOID KeClearTimer (__inout PKTIMER Timer)
ULARGE_INTEGER KeComputeReciprocal (IN LONG Divisor, OUT PCCHAR Shift)
ULONG KeComputeReciprocal32 (IN LONG Divisor, OUT PCCHAR Shift)
NTKERNELAPI BOOLEAN KeConnectInterrupt (__inout PKINTERRUPT Interrupt)
VOID KeContextFromKframes (__in PKTRAP_FRAME TrapFrame, __in_opt PKEXCEPTION_FRAME ExceptionFrame, __inout PCONTEXT ContextFrame)
VOID KeContextToKframes (__inout PKTRAP_FRAME TrapFrame, __inout_opt PKEXCEPTION_FRAME ExceptionFrame, __in PCONTEXT ContextFrame, __in ULONG ContextFlags, __in KPROCESSOR_MODE PreviousMode)
NTKERNELAPI NTSTATUS KeDelayExecutionThread (__in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in PLARGE_INTEGER Interval)
NTKERNELAPI BOOLEAN KeDeregisterBugCheckCallback (__inout PKBUGCHECK_CALLBACK_RECORD CallbackRecord)
NTKERNELAPI BOOLEAN KeDeregisterBugCheckReasonCallback (__inout PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord)
NTSTATUS KeDeregisterNmiCallback (__in PVOID Handle)
NTKERNELAPI VOID KeDetachProcess (VOID)
NTKERNELAPI BOOLEAN KeDisconnectInterrupt (__inout PKINTERRUPT Interrupt)
FORCEINLINE VOID KeEnableInterrupts (__in BOOLEAN Enable)
NTKERNELAPI VOID KeEnterKernelDebugger (VOID)
NTKERNELAPI VOID FASTCALL KefAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
NTKERNELAPI PCONFIGURATION_COMPONENT_DATA KeFindConfigurationEntry (IN PCONFIGURATION_COMPONENT_DATA Child, IN CONFIGURATION_CLASS Class, IN CONFIGURATION_TYPE Type, IN PULONG Key OPTIONAL)
NTKERNELAPI PCONFIGURATION_COMPONENT_DATA KeFindConfigurationNextEntry (IN PCONFIGURATION_COMPONENT_DATA Child, IN CONFIGURATION_CLASS Class, IN CONFIGURATION_TYPE Type, IN PULONG Key OPTIONAL, IN PCONFIGURATION_COMPONENT_DATA *Resume)
FORCEINLINE void KeFindFirstSetLeftMember (__in ULONG Set, __out PULONG Member)
FORCEINLINE ULONG KeFindFirstSetRightMember (__in ULONG Set)
ULONG KeFindNextRightSetAffinity (__in ULONG Number, __in KAFFINITY Set)
FORCEINLINE VOID KeFlushEntireTb (__in BOOLEAN Invalid, __in BOOLEAN AllProcessors)
VOID KeFlushMultipleTb (IN ULONG Number, IN PVOID *Virtual, IN BOOLEAN AllProcesors)
VOID KeFlushProcessTb (VOID)
PLIST_ENTRY KeFlushQueueApc (__inout PKTHREAD Thread, __in KPROCESSOR_MODE ProcessorMode)
NTKERNELAPI VOID KeFlushQueuedDpcs (VOID)
VOID FASTCALL KeFlushSingleTb (IN PVOID Virtual, IN BOOLEAN AllProcesors)
LOGICAL KeForceAttachProcess (__inout PKPROCESS Process)
ULONG KeForceResumeThread (__inout PKTHREAD Thread)
VOID KeFreezeAllThreads (VOID)
BOOLEAN KeFreezeExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
NTKERNELAPI VOID FASTCALL KefReleaseSpinLockFromDpcLevel (__inout PKSPIN_LOCK SpinLock)
VOID KeGenericCallDpc (__in PKDEFERRED_ROUTINE Routine, __in_opt PVOID Context)
BOOLEAN KeGetBugMessageText (__in ULONG MessageId, __out_opt PANSI_STRING ReturnedString OPTIONAL)
VOID KeGetNonVolatileContextPointers (IN PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext)
PKPRCB KeGetPrcb (IN ULONG ProcessorNumber)
NTKERNELAPI ULONG KeGetRecommendedSharedDataAlignment (VOID)
NTKERNELAPI VOID KeInitializeApc (__out PRKAPC Apc, __in PRKTHREAD Thread, __in KAPC_ENVIRONMENT Environment, __in PKKERNEL_ROUTINE KernelRoutine, __in_opt PKRUNDOWN_ROUTINE RundownRoutine, __in_opt PKNORMAL_ROUTINE NormalRoutine, __in_opt KPROCESSOR_MODE ProcessorMode, __in_opt PVOID NormalContext)
NTKERNELAPI VOID KeInitializeDeviceQueue (__out PKDEVICE_QUEUE DeviceQueue)
NTKERNELAPI VOID KeInitializeDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
VOID KeInitializeEventPair (__inout PKEVENT_PAIR EventPair)
VOID FASTCALL KeInitializeGate (__out PKGATE Gate)
NTKERNELAPI VOID KeInitializeInterrupt (__out PKINTERRUPT Interrupt, __in PKSERVICE_ROUTINE ServiceRoutine, __in_opt PVOID ServiceContext, __out_opt PKSPIN_LOCK SpinLock, __in ULONG Vector, __in KIRQL Irql, __in KIRQL SynchronizeIrql, __in KINTERRUPT_MODE InterruptMode, __in BOOLEAN ShareVector, __in CCHAR ProcessorNumber, __in BOOLEAN FloatingSave)
NTKERNELAPI VOID KeInitializeMutant (__out PRKMUTANT Mutant, __in BOOLEAN InitialOwner)
NTKERNELAPI VOID KeInitializeMutex (__out PRKMUTEX Mutex, __in ULONG Level)
VOID KeInitializeProcess (__out PRKPROCESS Process, __in KPRIORITY Priority, __in KAFFINITY Affinity, __in ULONG_PTR DirectoryTableBase[2], __in BOOLEAN Enable)
VOID KeInitializeProfile (__out PKPROFILE Profile, __in_opt PKPROCESS Process, __in_opt PVOID RangeBase, __in SIZE_T RangeSize, __in ULONG BucketSize, __in ULONG Segment, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY Affinity)
NTKERNELAPI VOID KeInitializeQueue (__out PRKQUEUE Queue, __in ULONG Count)
NTKERNELAPI VOID KeInitializeSemaphore (__out PRKSEMAPHORE Semaphore, __in LONG Count, __in LONG Limit)
FORCEINLINE VOID NTAPI KeInitializeSpinLock (__out PKSPIN_LOCK SpinLock)
NTSTATUS KeInitializeThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
NTKERNELAPI VOID KeInitializeThreadedDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
NTKERNELAPI VOID KeInitializeTimer (__out PKTIMER Timer)
NTKERNELAPI VOID KeInitializeTimerEx (__out PKTIMER Timer, __in TIMER_TYPE Type)
BOOLEAN KeInitSystem (VOID)
NTSTATUS KeInitThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
NTKERNELAPI BOOLEAN KeInsertByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry, __in ULONG SortKey)
NTKERNELAPI BOOLEAN KeInsertDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
NTKERNELAPI LONG KeInsertHeadQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
NTKERNELAPI LONG KeInsertQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
NTKERNELAPI BOOLEAN KeInsertQueueApc (__inout PRKAPC Apc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2, __in KPRIORITY Increment)
NTKERNELAPI BOOLEAN KeInsertQueueDpc (__inout PRKDPC Dpc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2)
BOOLEAN FASTCALL KeInvalidAccessAllowed (__in_opt PVOID TrapInformation)
NTKERNELAPI BOOLEAN KeInvalidateAllCaches (VOID)
ULONG_PTR KeIpiGenericCall (IN PKIPI_BROADCAST_WORKER BroadcastFunction, IN ULONG_PTR Context)
FORCEINLINE BOOLEAN KeIsSMTSetIdle (__in PKPRCB Prcb)
NTKERNELAPI BOOLEAN KeIsWaitListEmpty (__in PVOID Object)
FORCEINLINE VOID KeLoopTbFlushTimeStampUnlocked (VOID)
VOID KeNumaInitialize (VOID)
VOID KeOptimizeProcessorControlState (VOID)
NTKERNELAPI LONG KePulseEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
NTKERNELAPI KAFFINITY KeQueryActiveProcessors (VOID)
LOGICAL KeQueryAutoAlignmentThread (__in PKTHREAD Thread)
LONG KeQueryBasePriorityThread (__in PKTHREAD Thread)
NTKERNELAPI ULONGLONG KeQueryInterruptTime (VOID)
ULONG KeQueryIntervalProfile (__in KPROFILE_SOURCE Source)
NTSTATUS KeQueryLogicalProcessorInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnLength)
NTKERNELAPI KPRIORITY KeQueryPriorityThread (__in PKTHREAD Thread)
ULONG KeQueryRuntimeProcess (__in PKPROCESS Process, __out PULONG UserTime)
NTKERNELAPI ULONG KeQueryRuntimeThread (__in PKTHREAD Thread, __out PULONG UserTime)
NTKERNELAPI VOID KeQuerySystemTime (OUT PLARGE_INTEGER CurrentTime)
NTKERNELAPI ULONG KeQueryTimeIncrement (VOID)
ULONGLONG KeQueryTimerDueTime (__in PKTIMER Timer)
VOID KeQueryValuesProcess (__in PKPROCESS Process, __out PKPROCESS_VALUES Values)
_DECL_HAL_KE_IMPORT KIRQL KeRaiseIrqlToDpcLevel (VOID)
_DECL_HAL_KE_IMPORT KIRQL KeRaiseIrqlToSynchLevel (VOID)
NTSTATUS KeRaiseUserException (IN NTSTATUS ExceptionCode)
NTKERNELAPI LONG KeReadStateEvent (__in PRKEVENT Event)
LONG KeReadStateMutant (__in PRKMUTANT Mutant)
NTKERNELAPI LONG KeReadStateMutex (__in PRKMUTEX Mutex)
LONG KeReadStateProcess (__in PKPROCESS Process)
NTKERNELAPI LONG KeReadStateQueue (__in PRKQUEUE Queue)
NTKERNELAPI LONG KeReadStateSemaphore (__in PRKSEMAPHORE Semaphore)
BOOLEAN KeReadStateThread (__in PKTHREAD Thread)
NTKERNELAPI BOOLEAN KeReadStateTimer (__in PKTIMER Timer)
FORCEINLINE ULONG KeReadTbFlushTimeStamp (VOID)
VOID KeReadyThread (__inout PKTHREAD Thread)
NTKERNELAPI BOOLEAN KeRegisterBugCheckCallback (__out PKBUGCHECK_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_CALLBACK_ROUTINE CallbackRoutine, __in PVOID Buffer, __in ULONG Length, __in PUCHAR Component)
NTKERNELAPI BOOLEAN KeRegisterBugCheckReasonCallback (__out PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_REASON_CALLBACK_ROUTINE CallbackRoutine, __in KBUGCHECK_CALLBACK_REASON Reason, __in PUCHAR Component)
NTKERNELAPI PVOID KeRegisterNmiCallback (__in PNMI_CALLBACK CallbackRoutine, __in_opt PVOID Context)
_DECL_HAL_KE_IMPORT VOID FASTCALL KeReleaseInStackQueuedSpinLock (__in PKLOCK_QUEUE_HANDLE LockHandle)
NTKERNELAPI VOID FASTCALL KeReleaseInStackQueuedSpinLockForDpc (__in PKLOCK_QUEUE_HANDLE LockHandle)
NTKERNELAPI VOID FASTCALL KeReleaseInStackQueuedSpinLockFromDpcLevel (__in PKLOCK_QUEUE_HANDLE LockHandle)
NTKERNELAPI VOID KeReleaseInterruptSpinLock (__inout PKINTERRUPT Interrupt, __in KIRQL OldIrql)
NTKERNELAPI LONG KeReleaseMutant (__inout PRKMUTANT Mutant, __in KPRIORITY Increment, __in BOOLEAN Abandoned, __in BOOLEAN Wait)
NTKERNELAPI LONG KeReleaseMutex (__inout PRKMUTEX Mutex, __in BOOLEAN Wait)
_DECL_HAL_KE_IMPORT VOID FASTCALL KeReleaseQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __in KIRQL OldIrql)
VOID FASTCALL KeReleaseQueuedSpinLockFromDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
NTKERNELAPI LONG KeReleaseSemaphore (__inout PRKSEMAPHORE Semaphore, __in KPRIORITY Increment, __in LONG Adjustment, __in BOOLEAN Wait)
NTKERNELAPI VOID FASTCALL KeReleaseSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __in KIRQL OldIrql)
NTKERNELAPI PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
NTKERNELAPI PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueueIfBusy (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
NTKERNELAPI PKDEVICE_QUEUE_ENTRY KeRemoveDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue)
NTKERNELAPI BOOLEAN KeRemoveEntryDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
NTKERNELAPI PLIST_ENTRY KeRemoveQueue (__inout PRKQUEUE Queue, __in KPROCESSOR_MODE WaitMode, __in_opt PLARGE_INTEGER Timeout)
BOOLEAN KeRemoveQueueApc (__inout PKAPC Apc)
NTKERNELAPI BOOLEAN KeRemoveQueueDpc (__inout PRKDPC Dpc)
NTKERNELAPI BOOLEAN KeRemoveSystemServiceTable (IN ULONG Index)
NTKERNELAPI LONG KeResetEvent (__inout PRKEVENT Event)
ULONG KeResumeThread (__inout PKTHREAD Thread)
NTKERNELAPI VOID KeRevertToUserAffinityThread (VOID)
NTKERNELAPI PLIST_ENTRY KeRundownQueue (__inout PRKQUEUE Queue)
VOID KeRundownThread (VOID)
NTKERNELAPI VOID __cdecl KeSaveStateForHibernate (__out PKPROCESSOR_STATE ProcessorState)
KAFFINITY KeSetAffinityProcess (__inout PKPROCESS Process, __in KAFFINITY Affinity)
KAFFINITY KeSetAffinityThread (__inout PKTHREAD Thread, __in KAFFINITY Affinity)
LOGICAL KeSetAutoAlignmentProcess (__inout PKPROCESS Process, __in LOGICAL Enable)
LOGICAL KeSetAutoAlignmentThread (__inout PKTHREAD Thread, __in LOGICAL Enable)
NTKERNELAPI LONG KeSetBasePriorityThread (__inout PKTHREAD Thread, __in LONG Increment)
LOGICAL KeSetDisableBoostProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
LOGICAL KeSetDisableBoostThread (__inout PKTHREAD Thread, __in LOGICAL Disable)
LOGICAL KeSetDisableQuantumProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
NTKERNELAPI VOID KeSetDmaIoCoherency (IN ULONG Attributes)
NTKERNELAPI LONG KeSetEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
VOID KeSetEventBoostPriority (__inout PRKEVENT Event, __in_opt PRKTHREAD *Thread)
NTKERNELAPI UCHAR KeSetIdealProcessorThread (__inout PKTHREAD Thread, __in UCHAR Processor)
FORCEINLINE VOID KeSetImportanceDpc (__inout PRKDPC Dpc, __in KDPC_IMPORTANCE Importance)
VOID KeSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
NTKERNELAPI BOOLEAN KeSetKernelStackSwapEnable (__in BOOLEAN Enable)
NTSTATUS KeSetPhysicalCacheTypeRange (IN PHYSICAL_ADDRESS PhysicalAddress, IN ULONG NumberOfBytes, IN MEMORY_CACHING_TYPE CacheType)
KPRIORITY KeSetPriorityAndQuantumProcess (__inout PKPROCESS Process, __in KPRIORITY BasePriority, __in SCHAR QuantumReset)
NTKERNELAPI KPRIORITY KeSetPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Priority)
VOID KeSetPriorityZeroPageThread (__in KPRIORITY Priority)
LONG KeSetProcess (__inout PKPROCESS Process, __in KPRIORITY Increment, __in BOOLEAN Wait)
NTKERNELAPI VOID KeSetProfileIrql (IN KIRQL ProfileIrql)
VOID KeSetQuantumProcess (__inout PKPROCESS Process, __in SCHAR QuantumReset)
NTKERNELAPI VOID KeSetSystemAffinityThread (__in KAFFINITY Affinity)
VOID KeSetSystemTime (IN PLARGE_INTEGER NewTime, OUT PLARGE_INTEGER OldTime, IN BOOLEAN AdjustInterruptTime, IN PLARGE_INTEGER HalTimeToSet OPTIONAL)
FORCEINLINE VOID KeSetTargetProcessorDpc (__inout PRKDPC Dpc, __in CCHAR Number)
NTKERNELAPI VOID KeSetTimeIncrement (IN ULONG MaximumIncrement, IN ULONG MimimumIncrement)
NTKERNELAPI BOOLEAN KeSetTimer (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in_opt PKDPC Dpc)
NTKERNELAPI BOOLEAN KeSetTimerEx (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in LONG Period, __in_opt PKDPC Dpc)
VOID KeSignalCallDpcDone (__in PVOID SystemArgument1)
LOGICAL KeSignalCallDpcSynchronize (__in PVOID SystemArgument2)
VOID FASTCALL KeSignalGateBoostPriority (__inout PKGATE Gate)
NTKERNELAPI VOID KeStackAttachProcess (__inout PRKPROCESS PROCESS, __out PRKAPC_STATE ApcState)
VOID KeStartAllProcessors (VOID)
BOOLEAN KeStartProfile (__inout PKPROFILE Profile, __out_opt PULONG Buffer)
VOID KeStartThread (__inout PKTHREAD Thread)
BOOLEAN KeStopProfile (__inout PKPROFILE Profile)
ULONG KeSuspendThread (__inout PKTHREAD Thread)
VOID KeSwapProcessOrStack (IN PVOID Context)
KCONTINUE_STATUS KeSwitchFrozenProcessor (IN ULONG ProcessorNumber)
PVOID KeSwitchKernelStack (IN PVOID StackBase, IN PVOID StackLimit)
NTKERNELAPI BOOLEAN KeSynchronizeExecution (__inout PKINTERRUPT Interrupt, __in PKSYNCHRONIZE_ROUTINE SynchronizeRoutine, __in_opt PVOID SynchronizeContext)
NTKERNELAPI VOID KeTerminateThread (__in KPRIORITY Increment)
BOOLEAN KeTestAlertThread (__in KPROCESSOR_MODE)
FORCEINLINE LOGICAL KeTestForWaitersQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number)
NTKERNELAPI BOOLEAN FASTCALL KeTestSpinLock (__in PKSPIN_LOCK SpinLock)
VOID KeThawAllThreads (VOID)
VOID KeThawExecution (IN BOOLEAN Enable)
_DECL_HAL_KE_IMPORT LOGICAL FASTCALL KeTryToAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
LOGICAL FASTCALL KeTryToAcquireQueuedSpinLockAtRaisedIrql (__inout PKSPIN_LOCK_QUEUE QueuedLock)
_DECL_HAL_KE_IMPORT LOGICAL FASTCALL KeTryToAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
BOOLEAN KeTryToAcquireSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKIRQL OldIrql)
NTKERNELAPI BOOLEAN FASTCALL KeTryToAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
VOID KeUninitThread (__inout PKTHREAD Thread)
NTKERNELAPI VOID KeUnstackDetachProcess (__in PRKAPC_STATE ApcState)
NTKERNELAPI NTSTATUS KeUserModeCallback (IN ULONG ApiNumber, IN PVOID InputBuffer, IN ULONG InputLength, OUT PVOID *OutputBuffer, OUT PULONG OutputLength)
NTSTATUS KevUtilAddressToFileHeader (IN PVOID Address, OUT UINT_PTR *OffsetIntoImage, OUT PUNICODE_STRING *DriverName, OUT BOOLEAN *InVerifierList)
FORCEINLINE VOID KeWaitForContextSwap (__in PKTHREAD Thread)
VOID FASTCALL KeWaitForGate (__inout PKGATE Gate, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode)
NTKERNELAPI NTSTATUS KeWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) PVOID Object[], __in WAIT_TYPE WaitType, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout, __out_opt PKWAIT_BLOCK WaitBlockArray)
NTKERNELAPI NTSTATUS KeWaitForSingleObject (__in PVOID Object, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KfAcquireSpinLock (__inout PKSPIN_LOCK SpinLock)
_DECL_HAL_KE_IMPORT VOID FASTCALL KfLowerIrql (__in KIRQL NewIrql)
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KfRaiseIrql (__in KIRQL NewIrql)
_DECL_HAL_KE_IMPORT VOID FASTCALL KfReleaseSpinLock (__inout PKSPIN_LOCK SpinLock, __in KIRQL NewIrql)
FORCEINLINE ULONG KiFindFirstSetLeftMemberInt (__in ULONG Set)
BOOLEAN KiIpiServiceRoutine (IN struct _KTRAP_FRAME *TrapFrame, IN struct _KEXCEPTION_FRAME *ExceptionFrame)
VOID FASTCALL KiSetPriorityThread (__inout PRKTHREAD Thread, __in KPRIORITY Priority)
NTSTATUS KiSetServerWaitClientEvent (__inout PKEVENT SeverEvent, __inout PKEVENT ClientEvent, __in ULONG WaitMode)
VOID KxFlushEntireTb (VOID)
Variables
KAFFINITY KeActiveProcessors
LARGE_INTEGER KeBootTime
ULONGLONG KeBootTimeBias
BOOLEAN KeBugCheckActive
LIST_ENTRY KeBugCheckCallbackListHead
KSPIN_LOCK KeBugCheckCallbackLock
LIST_ENTRY KeBugCheckReasonCallbackListHead
ULONG KeErrorMask
ULONG KeFeatureBits
PGDI_BATCHFLUSH_ROUTINE KeGdiFlushUserBatch
ULONGLONG KeInterruptTimeBias
ULONG KeLargestCacheLine
PLOADER_PARAMETER_BLOCK KeLoaderBlock
ULONG KeMaximumIncrement
ULONG KeMinimumIncrement
PKNODE KeNodeBlock []
UCHAR KeNumberNodes
NTSYSAPI CCHAR KeNumberProcessors
ULONG KeNumprocSpecified
UCHAR KeProcessNodeSeed
USHORT KeProcessorArchitecture
USHORT KeProcessorLevel
USHORT KeProcessorRevision
PVOID KeRaiseUserExceptionDispatcher
PULONG KeServiceCountTable
KSERVICE_TABLE_DESCRIPTOR KeServiceDescriptorTable [NUMBER_SERVICE_TABLES]
KSERVICE_TABLE_DESCRIPTOR KeServiceDescriptorTableShadow [NUMBER_SERVICE_TABLES]
ULONG KeThreadDpcEnable
KTHREAD_SWITCH_COUNTERS KeThreadSwitchCounters
volatile KSYSTEM_TIME KeTickCount
ULONG KeTimeAdjustment
ULONG KeTimeIncrement
ULONG KeTimerCheckFlags
BOOLEAN KeTimeSynchronization
PVOID KeUserApcDispatcher
PVOID KeUserCallbackDispatcher
PVOID KeUserExceptionDispatcher
PVOID KeUserPopEntrySListEnd
PVOID KeUserPopEntrySListFault
PVOID KeUserPopEntrySListResume
KE_ZERO_PAGE_ROUTINE KeZeroPages
KE_ZERO_PAGE_ROUTINE KeZeroPagesFromIdleThread
const ULONG_PTR KiAffinityArray []
ALIGNED_SPINLOCK KiDispatcherLock
ULONG KiDPCTimeout
DECLSPEC_CACHEALIGN DECLSPEC_SELECTANY const CCHAR KiFindFirstSetLeft [256]
DECLSPEC_CACHEALIGN DECLSPEC_SELECTANY const CCHAR KiFindFirstSetRight [256]
volatile KAFFINITY KiIdleSummary
DECLSPEC_CACHEALIGN DECLSPEC_SELECTANY const ULONG KiMask32Array [32]
PKPRCB KiProcessorBlock []
ULONG KiSpinlockTimeout
ULONG KiStackProtectTime
volatile LONG KiTbFlushTimeStamp
Macro Definition Documentation
#define _DECL_HAL_KE_IMPORT __declspec(dllimport)
Definition at line 2929 of file ke.h.
#define AFFINITY_MASK (n) (KiAffinityArray[n])
Definition at line 237 of file ke.h.
Referenced by CmpConfigureProcessors(), ExAllocateCacheAwarePushLock(), KeConnectInterrupt(), KeDisconnectInterrupt(), KeFindNextRightSetAffinity(), KeFlushQueuedDpcs(), KeFreezeExecution(), KeInsertQueueDpc(), KeSetIdealProcessorThread(), KeSetSystemAffinityThread(), KeStartAllProcessors(), KeStartThread(), KiDeferredReadyThread(), KiFindReadyThread(), KiIdleSchedule(), KiInitializeBootStructures(), KiInitializeKernel(), KiIpiProcessRequests(), KiIpiSendRequest(), KiSelectReadyThread(), KiSendThawExecution(), KiSetAffinityThread(), KiSwapThread(), MiZeroPageWorker(), and WmiStopContextSwapTrace().
#define ASSERT_PROCESS (object) ASSERT((object)->Header.Type == ProcessObject)
Definition at line 932 of file ke.h.
Referenced by KeAttachProcess(), KeForceAttachProcess(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeReadStateProcess(), KeSetAffinityProcess(), KeSetAutoAlignmentProcess(), KeSetDisableBoostProcess(), KeSetDisableQuantumProcess(), KeSetPriorityAndQuantumProcess(), KeSetProcess(), KeSetQuantumProcess(), and KeStackAttachProcess().
#define ASSERT_QUEUE (Q) ASSERT(((Q)->Header.Type & KOBJECT_TYPE_MASK) == QueueObject);
Definition at line 816 of file ke.h.
Referenced by KeInsertHeadQueue(), KeInsertQueue(), KeReadStateQueue(), KeRemoveQueue(), KeRundownQueue(), and KiInsertQueue().
#define ASSERT_THREAD (object) ASSERT((object)->Header.Type == ThreadObject)
Definition at line 1060 of file ke.h.
Referenced by KeAlertResumeThread(), KeAlertThread(), KeForceResumeThread(), KeQueryAutoAlignmentThread(), KeQueryBasePriorityThread(), KeQueryPriorityThread(), KeQueryRuntimeThread(), KeReadStateThread(), KeReadyThread(), KeResumeThread(), KeSetAffinityThread(), KeSetAutoAlignmentThread(), KeSetBasePriorityThread(), KeSetDisableBoostThread(), KeSetPriorityThread(), and KeSuspendThread().
#define BASE_PRIORITY_THRESHOLD NORMAL_BASE_PRIORITY
Definition at line 65 of file ke.h.
#define CLOCK_QUANTUM_DECREMENT 3
Definition at line 26 of file ke.h.
Referenced by KeSignalGateBoostPriority(), and KeUpdateRunTime().
#define DISPATCHER_OBJECT_TYPE_MASK 0x7
Definition at line 310 of file ke.h.
#define DMA_READ_DCACHE_INVALIDATE 0x1
Definition at line 4271 of file ke.h.
#define DMA_READ_ICACHE_INVALIDATE 0x2
Definition at line 4272 of file ke.h.
#define DMA_WRITE_DCACHE_SNOOP 0x4
Definition at line 4273 of file ke.h.
#define EVENT_WAIT_BLOCK 2
Definition at line 73 of file ke.h.
#define EXCEPTION_ALIGNMENT_CHECK 0x011
Definition at line 3757 of file ke.h.
#define EXCEPTION_BOUND_CHECK 5
Definition at line 3746 of file ke.h.
#define EXCEPTION_DEBUG 1
Definition at line 3743 of file ke.h.
#define EXCEPTION_DIVIDED_BY_ZERO 0
Definition at line 3742 of file ke.h.
#define EXCEPTION_DOUBLE_FAULT 8
Definition at line 3749 of file ke.h.
#define EXCEPTION_GP_FAULT 0x0D
Definition at line 3754 of file ke.h.
#define EXCEPTION_INT3 3
Definition at line 3745 of file ke.h.
#define EXCEPTION_INVALID_OPCODE 6
Definition at line 3747 of file ke.h.
#define EXCEPTION_INVALID_TSS 0x0A
Definition at line 3751 of file ke.h.
#define EXCEPTION_NMI 2
Definition at line 3744 of file ke.h.
#define EXCEPTION_NPX_ERROR 0x010
Definition at line 3756 of file ke.h.
#define EXCEPTION_NPX_NOT_AVAILABLE 7
Definition at line 3748 of file ke.h.
#define EXCEPTION_NPX_OVERRUN 9
Definition at line 3750 of file ke.h.
#define EXCEPTION_RESERVED_TRAP 0x0F
Definition at line 3755 of file ke.h.
#define EXCEPTION_SEGMENT_NOT_PRESENT 0x0B
Definition at line 3752 of file ke.h.
#define EXCEPTION_STACK_FAULT 0x0C
Definition at line 3753 of file ke.h.
#define GM_LOCK_BIT 0x1
Definition at line 4755 of file ke.h.
Referenced by KeInitializeGuardedMutex(), KeIsGuardedMutexOwned(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), and KiAcquireGuardedMutex().
#define GM_LOCK_BIT_V 0x0
Definition at line 4756 of file ke.h.
Referenced by KeAcquireGuardedMutex(), KeAcquireGuardedMutexUnsafe(), and KeTryToAcquireGuardedMutex().
#define GM_LOCK_WAITER_INC 0x4
Definition at line 4758 of file ke.h.
Referenced by KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), and KiAcquireGuardedMutex().
#define GM_LOCK_WAITER_WOKEN 0x2
Definition at line 4757 of file ke.h.
Referenced by KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), and KiAcquireGuardedMutex().
#define KAPC_STATE_ACTUAL_LENGTH (FIELD_OFFSET(KAPC_STATE, UserApcPending) + sizeof(BOOLEAN))
Definition at line 466 of file ke.h.
Referenced by KiMoveApcState().
#define KeAcquireSpinLock (a, b) *(b) = KfAcquireSpinLock(a)
Definition at line 3238 of file ke.h.
Referenced by ExNotifyCallback(), ExRegisterCallback(), ExUnregisterCallback(), IoWMIWriteEvent(), KeAcquireSpinLockEx(), KeDeregisterNmiCallback(), KeRegisterNmiCallback(), KeRestoreMtrr(), KeSetPhysicalCacheTypeRange(), KiAcquireSpinLockForDpc(), KiAmdK6InitializeMTRR(), KiAmdK6MtrrSetMemoryType(), KiCompleteEffectiveRangeChange(), KiInitializePAT(), RtlpTraceDatabaseAcquireLock(), and WmipInsertQueueMCEDpc().
#define KeAcquireSpinLockAtDpcLevel (a) KefAcquireSpinLockAtDpcLevel(a)
Definition at line 3209 of file ke.h.
#define KeClearEvent (Event) (Event)->Header.SignalState = 0
Definition at line 1813 of file ke.h.
#define KeCopyPage (d, s) RtlCopyMemory((d),(s),PAGE_SIZE)
Definition at line 4733 of file ke.h.
Referenced by MiCopyOnWrite().
#define KeFindFirstSetLeftAffinity (Set, Member) KeFindFirstSetLeftMember(Set, Member)
Definition at line 3961 of file ke.h.
Referenced by KeFindNextRightSetAffinity(), KeFreezeExecution(), KeI386SetGdtSelector(), KeSetSystemAffinityThread(), KiDeferredReadyThread(), KiIdleSchedule(), KiSendFreeze(), KiSendThawExecution(), KiSwapThread(), MiZeroAwePageWorker(), and MmZeroPageThread().
#define KeGetCurrentApcEnvironment () KeGetCurrentThread()->ApcStateIndex
Definition at line 87 of file ke.h.
Referenced by IoInitializeIrp().
#define KeGetCurrentNode () (KeGetCurrentPrcb()->ParentNode)
Definition at line 891 of file ke.h.
Referenced by MiAllocatePagesForMdl(), MiDeferredUnlockPages(), MiZeroPageWorker(), and MmUnlockPages().
#define KeGetPreviousMode () (KeGetCurrentThread()->PreviousMode)
Definition at line 2748 of file ke.h.
Referenced by CmpDoCreate(), CmpDoOpen(), CmpRefreshHive(), CmQueryMultipleValueKey(), DbgkMapViewOfSection(), DbgkUnMapViewOfSection(), ExGetPreviousMode(), ExGetSessionPoolTagInformation(), ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), ExpRaiseHardError(), ExSystemExceptionFilter(), IopCreateFile(), IopInitializeAttributesAndCreateObject(), IopLoadDriver(), IopSendMessageToTrackService(), IopUnloadDriver(), KeUserModeCallback(), KiContinue(), KiRaiseException(), LpcpCopyRequestData(), LpcpCreatePort(), LpcpRequestWaitReplyPort(), LpcRequestPort(), LpcRequestWaitReplyPortEx(), MiCheckPurgeAndUpMapCount(), MiMapViewOfImageSection(), MmCreateSection(), MmGetSessionMappedViewInformation(), NtAcceptConnectPort(), NtAddAtom(), NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtAlertResumeThread(), NtAlertThread(), NtAllocateLocallyUniqueId(), NtAllocateUuids(), NtCancelTimer(), NtClearEvent(), NtClose(), NtCloseObjectAuditAlarm(), NtCompactKeys(), NtCompareTokens(), NtCompleteConnectPort(), NtCompressKey(), NtCreateDebugObject(), NtCreateDirectoryObject(), NtCreateEvent(), NtCreateEventPair(), NtCreateIoCompletion(), NtCreateKey(), NtCreateKeyedEvent(), NtCreateMailslotFile(), NtCreateMutant(), NtCreateNamedPipeFile(), NtCreatePagingFile(), NtCreateProcessEx(), NtCreateProfile(), NtCreateSection(), NtCreateSemaphore(), NtCreateSymbolicLinkObject(), NtCreateThread(), NtCreateTimer(), NtCreateToken(), NtDebugActiveProcess(), NtDebugContinue(), NtDelayExecution(), NtDeleteFile(), NtDeleteKey(), NtDeleteObjectAuditAlarm(), NtDeleteValueKey(), NtDuplicateObject(), NtDuplicateToken(), NtEnumerateKey(), NtEnumerateValueKey(), NtExtendSection(), NtFilterToken(), NtFindAtom(), NtFlushInstructionCache(), NtFlushKey(), NtFlushVirtualMemory(), NtGetNextProcess(), NtGetNextThread(), NtImpersonateAnonymousToken(), NtImpersonateClientOfPort(), NtImpersonateThread(), NtInitializeRegistry(), NtLoadKeyEx(), NtLockRegistryKey(), NtMakePermanentObject(), NtMakeTemporaryObject(), NtNotifyChangeMultipleKeys(), NtOpenDirectoryObject(), NtOpenEvent(), NtOpenEventPair(), NtOpenIoCompletion(), NtOpenJobObject(), NtOpenKey(), NtOpenKeyedEvent(), NtOpenMutant(), NtOpenObjectAuditAlarm(), NtOpenProcess(), NtOpenProcessTokenEx(), NtOpenSection(), NtOpenSemaphore(), NtOpenSymbolicLinkObject(), NtOpenThread(), NtOpenThreadTokenEx(), NtOpenTimer(), NtPrivilegeCheck(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtPulseEvent(), NtQueryAttributesFile(), NtQueryDefaultLocale(), NtQueryDefaultUILanguage(), NtQueryDirectoryObject(), NtQueryEvent(), NtQueryFullAttributesFile(), NtQueryInformationAtom(), NtQueryInformationPort(), NtQueryInformationProcess(), NtQueryInformationToken(), NtQueryInstallUILanguage(), NtQueryIntervalProfile(), NtQueryIoCompletion(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryMutant(), NtQueryObject(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryPerformanceCounter(), NtQuerySection(), NtQuerySecurityObject(), NtQuerySemaphore(), NtQuerySymbolicLinkObject(), NtQuerySystemInformation(), NtQueryTimer(), NtQueryValueKey(), NtQueueApcThread(), NtRaiseHardError(), NtReleaseMutant(), NtReleaseSemaphore(), NtRemoveIoCompletion(), NtRemoveProcessDebug(), NtRenameKey(), NtReplaceKey(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtResetEvent(), NtRestoreKey(), NtResumeProcess(), NtResumeThread(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSecureConnectPort(), NtSetDefaultHardErrorPort(), NtSetEvent(), NtSetEventBoostPriority(), NtSetHighEventPair(), NtSetHighWaitLowEventPair(), NtSetInformationDebugObject(), NtSetInformationKey(), NtSetInformationObject(), NtSetInformationToken(), NtSetIoCompletion(), NtSetLowEventPair(), NtSetLowWaitHighEventPair(), NtSetSecurityObject(), NtSetSystemInformation(), NtSetTimer(), NtSetUuidSeed(), NtSetValueKey(), NtSignalAndWaitForSingleObject(), NtStartProfile(), NtStopProfile(), NtSuspendProcess(), NtSuspendThread(), NtTestAlert(), NtTraceEvent(), NtUnloadKey2(), NtUnloadKeyEx(), NtUnlockVirtualMemory(), NtUnmapViewOfSection(), NtWaitForDebugEvent(), NtWaitForMultipleObjects(), NtWaitForMultipleObjects32(), NtWaitForSingleObject(), NtWaitHighEventPair(), NtWaitLowEventPair(), ObInsertObject(), ObpCreateHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObSetDeviceMap(), ObSwapObjectNames(), PerfInfoStartLog(), PsGetCurrentThreadPreviousMode(), PsOpenTokenOfJobObject(), PsOpenTokenOfProcess(), PsOpenTokenOfThread(), PspSetPrimaryToken(), PspSetProcessIoHandlers(), RtlpNewSecurityObject(), SeAccessCheckByType(), SeFilterToken(), SeIsChildToken(), SeIsSiblingToken(), SepAccessCheckAndAuditAlarm(), SepCreateToken(), SepOpenTokenOfThread(), WmipFastIoDeviceControl(), WmipIoControl(), WmipNtDllLoggerInfo(), WmipQueryLogger(), WmipStartLogger(), WmipVerifyLoggerInfo(), WmiTraceMessageVa(), and WmiUpdateTrace().
#define KeGetPreviousModeByThread (xxCurrentThread)
Value:
(ASSERT (xxCurrentThread == KeGetCurrentThread ()),                     \
    (xxCurrentThread)->PreviousMode)
Definition at line 2774 of file ke.h.
Referenced by BuildQueryDirectoryIrp(), IopGetSetSecurityObject(), IopMountVolume(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtAssignProcessToJobObject(), NtCancelIoFile(), NtCreateJobObject(), NtCreateJobSet(), NtFlushBuffersFile(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetContextThread(), NtGetWriteWatch(), NtIsProcessInJob(), NtLoadDriver(), NtLockFile(), NtLockVirtualMemory(), NtMapViewOfSection(), NtNotifyChangeDirectoryFile(), NtProtectVirtualMemory(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryInformationJobObject(), NtQueryInformationThread(), NtQueryQuotaInformationFile(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtReadVirtualMemory(), NtRegisterThreadTerminatePort(), NtReleaseKeyedEvent(), NtResetWriteWatch(), NtSetContextThread(), NtSetEaFile(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetVolumeInformationFile(), NtTerminateJobObject(), NtTerminateProcess(), NtTerminateThread(), NtUnlockFile(), NtWaitForKeyedEvent(), NtWriteFile(), NtWriteFileGather(), NtWriteVirtualMemory(), PsAssignImpersonationToken(), PsConvertToGuiThread(), PspAssignPrimaryToken(), PspCreateProcess(), and PspCreateThread().
#define KeInitializeCallbackRecord (CallbackRecord) (CallbackRecord)->State = BufferEmpty
Definition at line 3669 of file ke.h.
#define KeInitializeEvent (_Event, _Type, _State)
Value:
(_Event)->Header.Type = (UCHAR)_Type;                   \
    (_Event)->Header.Size =  sizeof(KEVENT) / sizeof(LONG); \
    (_Event)->Header.SignalState = _State;                  \
    InitializeListHead(&(_Event)->Header.WaitListHead)
Definition at line 1807 of file ke.h.
#define KeIsAttachedProcess () KiIsAttachedProcess()
Definition at line 2053 of file ke.h.
#define KeLowerIrql (a) KfLowerIrql(a)
Definition at line 3442 of file ke.h.
Referenced by CmNotifyRunDown(), CmpNotifyChangeKey(), CmpPostApcRunDown(), CmpPostNotify(), CmpReportNotifyHelper(), ExDeletePoolTagTable(), ExfUnblockPushLock(), ExfWakePushLock(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExReleaseSpinLockExclusive(), ExReleaseSpinLockShared(), IoAsynchronousPageWrite(), IoCancelFileOpen(), IoCancelThreadIo(), IopCancelAlertedRequest(), IopCloseFile(), IopDeleteFile(), IopDisassociateThreadIrp(), IopParseDevice(), IopSynchronousServiceTail(), IoRetryIrpCompletions(), IoStartPacket(), Ke386QueryIoAccessMap(), KeConnectInterrupt(), KeContextFromKframes(), KeContextToKframes(), KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushQueuedDpcs(), KeFlushSingleTb(), KeGenericCallDpc(), KeInsertQueueDpc(), KeInvalidateAllCaches(), KeIpiGenericCall(), KeQueryBasePriorityThread(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), KeReleaseInStackQueuedSpinLock(), KeReleaseInterruptSpinLock(), KeReleaseQueuedSpinLock(), KeReleaseSpinLock(), KeSetSystemTime(), KeSignalGateBoostPriority(), KeStartAllProcessors(), KeStartProfile(), KeStopProfile(), KeThawExecution(), KeTryToAcquireQueuedSpinLock(), KeTryToAcquireQueuedSpinLockRaiseToSynch(), KeTryToAcquireSpinLock(), Ki386CheckDelayedNpxTrap(), KiCheckForKernelApcDelivery(), KiContinue(), KiContinueEx(), KiDeliverApc(), KiEspToTrapFrame(), KiExecuteDpc(), KiExitDispatcher(), KiFreezeTargetExecution(), KiIdleSchedule(), KiInitializeKernel(), KiInitializeUserApc(), KiOpPatchCode(), KiPreprocessInvalidOpcodeFault(), KiQuantumEnd(), KiRetireDpcList(), KiStartProfileInterrupt(), KiStopProfileInterrupt(), KiTimerExpiration(), KiTimerListExpire(), KiTryToAcquireDispatcherLockRaiseToSynch(), KxFlushEntireTb(), MiCancelWriteOfMappedPfn(), MiCleanSection(), MiFlushSectionInternal(), MiGatherMappedPages(), MiGatherPagefilePages(), MiMappedPageWriter(), MiProcessLoaderEntry(), MmAccessFault(), MmPurgeSection(), NtCancelIoFile(), NtNotifyChangeMultipleKeys(), NtQueryInformationFile(), NtSetInformationFile(), NtYieldExecution(), Ps386GetVdmIoHandler(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspExitThread(), PspSystemThreadStartup(), PspUserThreadStartup(), RtlLookupFunctionTable(), RtlPcToFileHeader(), xxReleaseFastMutex(), and xxTryToAcquireFastMutex().
#define KeQueuedSpinLockContext (n) (&(KeGetCurrentPrcb()->LockQueue[n]))
Definition at line 3060 of file ke.h.
Referenced by KiAcquireTimerTableLock().
#define KeRaiseIrql (a, b) *(b) = KfRaiseIrql(a)
Definition at line 3443 of file ke.h.
Referenced by CmNotifyRunDown(), CmpNotifyChangeKey(), CmpPostApcRunDown(), CmpPostNotify(), CmpReportNotifyHelper(), ExAcquireSpinLockShared(), ExDeletePoolTagTable(), ExfUnblockPushLock(), ExfWakePushLock(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), IoAsynchronousPageWrite(), IoCancelFileOpen(), IoCancelThreadIo(), IopCancelAlertedRequest(), IopCloseFile(), IopDeleteFile(), IopDisassociateThreadIrp(), IopParseDevice(), IopSynchronousServiceTail(), IoRetryIrpCompletions(), IoStartPacket(), Ke386QueryIoAccessMap(), KeAcquireInterruptSpinLock(), KeBugCheck2(), KeConnectInterrupt(), KeContextFromKframes(), KeContextToKframes(), KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeEnterKernelDebugger(), KeFlushQueuedDpcs(), KeFreezeExecution(), KeGenericCallDpc(), KeInsertQueueDpc(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), KeSetSystemTime(), Ki386CheckDelayedNpxTrap(), Ki386CheckDivideByZeroTrap(), KiCompleteEffectiveRangeChange(), KiDeliverApc(), KiEspToTrapFrame(), KiExecuteDpc(), KiFreezeTargetExecution(), KiInitializeKernel(), KiInitializePAT(), KiOpPatchCode(), MiCancelWriteOfMappedPfn(), MiFlushSectionInternal(), MiGatherMappedPages(), MiGatherPagefilePages(), MiMappedPageWriter(), MmAccessFault(), NtCancelIoFile(), NtNotifyChangeMultipleKeys(), NtQueryInformationFile(), NtSetInformationFile(), Ps386GetVdmIoHandler(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), and PspUserThreadStartup().
#define KeReleaseSpinLock (a, b) KfReleaseSpinLock(a,b)
Definition at line 3239 of file ke.h.
#define KeReleaseSpinLockFromDpcLevel (a) KefReleaseSpinLockFromDpcLevel(a)
Definition at line 3210 of file ke.h.
#define KeSetHighEventPair (EventPair, Increment, Wait)
Value:
KeSetEvent(&((EventPair)->EventHigh),              \
               Increment,                              \
               Wait)
Definition at line 1864 of file ke.h.
Referenced by NtSetHighEventPair().
#define KeSetHighWaitLowEventPair (EventPair, WaitMode)
Value:
KiSetServerWaitClientEvent(&((EventPair)->EventHigh),                    \
                               &((EventPair)->EventLow),                     \
                               WaitMode)
Definition at line 2805 of file ke.h.
Referenced by NtSetHighWaitLowEventPair().
#define KeSetLowEventPair (EventPair, Increment, Wait)
Value:
KeSetEvent(&((EventPair)->EventLow),               \
               Increment,                              \
               Wait)
Definition at line 1869 of file ke.h.
Referenced by NtSetLowEventPair().
#define KeSetLowWaitHighEventPair (EventPair, WaitMode)
Value:
KiSetServerWaitClientEvent(&((EventPair)->EventLow),                     \
                               &((EventPair)->EventHigh),                    \
                               WaitMode)
Definition at line 2810 of file ke.h.
Referenced by NtSetLowWaitHighEventPair().
#define KeTerminateProcess (Process) (Process)->StackCount += 1;
Definition at line 2141 of file ke.h.
Referenced by PspProcessDelete().
#define KeWaitForHighEventPair (EventPair, WaitMode, Alertable, TimeOut)
Value:
KeWaitForSingleObject(&((EventPair)->EventHigh),                         \
                          WrEventPair,                                       \
                          WaitMode,                                          \
                          Alertable,                                         \
                          TimeOut)
Definition at line 2815 of file ke.h.
Referenced by NtWaitHighEventPair().
#define KeWaitForLowEventPair (EventPair, WaitMode, Alertable, TimeOut)
Value:
KeWaitForSingleObject(&((EventPair)->EventLow),                          \
                          WrEventPair,                                       \
                          WaitMode,                                          \
                          Alertable,                                         \
                          TimeOut)
Definition at line 2822 of file ke.h.
Referenced by NtWaitLowEventPair().
#define KeWaitForMutexObject KeWaitForSingleObject
Definition at line 2870 of file ke.h.
Referenced by WmipEnterCritSection(), and WmipEnterTraceCritSection().
#define KeZeroSinglePage (v) KeZeroPages((v), PAGE_SIZE)
Definition at line 4700 of file ke.h.
Referenced by MiResolveDemandZeroFault(), MiSessionInitializeWorkingSetList(), MiZeroPageFileFirstPage(), MiZeroPhysicalPage(), and MmAccessFault().
#define KI_SLIST_FAULT_COUNT_MAXIMUM 1024
Definition at line 1067 of file ke.h.
Referenced by KiOpPreprocessAccessViolation().
#define KiAffinityArray KiMask32Array
Definition at line 231 of file ke.h.
#define KiBugCheck3 (b, p1, p2, p3) KeBugCheckEx(b,p1,p2,p3,0)
Definition at line 3820 of file ke.h.
Referenced by IopfCallDriver().
#define KiIsAttachedProcess () (KeGetCurrentThread()->ApcStateIndex == AttachedApcEnvironment)
Definition at line 2048 of file ke.h.
Referenced by KeIsAttachedProcess().
#define KiLockDispatcherDatabase (OldIrql) *(OldIrql) = KeAcquireQueuedSpinLockRaiseToSynch(LockQueueDispatcherLock)
Definition at line 3111 of file ke.h.
Referenced by ExpCheckForWorker(), ExpExpandResourceOwnerTable(), ExpWaitForResource(), KeBalanceSetManager(), KeBoostPriorityThread(), KeCancelTimer(), KeCheckForTimer(), KeConnectInterrupt(), KeDisconnectInterrupt(), KeInitializeMutant(), KeInsertHeadQueue(), KeInsertQueue(), KePulseEvent(), KeQueryTimerDueTime(), KeReadyThread(), KeReleaseMutant(), KeReleaseSemaphore(), KeResetEvent(), KeRevertToUserAffinityThread(), KeRundownQueue(), KeRundownThread(), KeSetAffinityThread(), KeSetBasePriorityThread(), KeSetEvent(), KeSetEventBoostPriority(), KeSetIdealProcessorThread(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeSetProcess(), KeSetSystemAffinityThread(), KeSetSystemTime(), KeSetTimerEx(), KeSetup80387OrEmulate(), KiInSwapKernelStacks(), KiInSwapProcesses(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), KiScanReadyQueues(), KiTimerExpiration(), and KiTimerListExpire().
#define KiLockDispatcherDatabaseAtSynchLevel () KeAcquireQueuedSpinLockAtDpcLevel(&KeGetCurrentPrcb()->LockQueue[LockQueueDispatcherLock])
Definition at line 3148 of file ke.h.
Referenced by ExpGetProcessInformation(), KeAlertResumeThread(), KeAlertThread(), KeAttachProcess(), KeDelayExecutionThread(), KeDetachProcess(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeRemoveQueue(), KeRemoveQueueApc(), KeResumeThread(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeSignalGateBoostPriority(), KeStackAttachProcess(), KeStartThread(), KeSuspendThread(), KeTerminateThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiAttachProcess(), KiCompleteTimer(), and KiInsertQueueApc().
#define KiQueryLowTickCount () KeTickCount.LowPart
Definition at line 290 of file ke.h.
Referenced by IoCreateDriver(), KiCalibrateTimeAdjustment(), KiDeferredReadyThread(), KiOutSwapKernelStacks(), KiScanReadyQueues(), KiTimerExpiration(), and KxQueueReadyThread().
#define KiQuerySystemTime (CurrentTime)
Value:
while (TRUE) {                                                                  \
        (CurrentTime)->HighPart = SharedUserData->SystemTime.High1Time;             \
        (CurrentTime)->LowPart = SharedUserData->SystemTime.LowPart;                \
        if ((CurrentTime)->HighPart == SharedUserData->SystemTime.High2Time) break; \
        PAUSE_PROCESSOR                                                             \
    }
Definition at line 274 of file ke.h.
Referenced by KeQuerySystemTime(), KeSetSystemTime(), KiComputeDueTime(), KiSetDueTime(), KiSignalTimer(), KiTimerExpiration(), KiTimerListExpire(), and WmipGetSystemTime().
#define KiTryToLockDispatcherDatabase (OldIrql) KeTryToAcquireQueuedSpinLockRaiseToSynch(LockQueueDispatcherLock,OldIrql)
Definition at line 3114 of file ke.h.
Referenced by KiTimerExpiration().
#define KiUnlockDispatcherDatabaseFromSynchLevel () KeReleaseQueuedSpinLockFromDpcLevel(&KeGetCurrentPrcb()->LockQueue[LockQueueDispatcherLock])
Definition at line 3151 of file ke.h.
Referenced by ExpGetProcessInformation(), KeAlertResumeThread(), KeAlertThread(), KeDelayExecutionThread(), KeDetachProcess(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertHeadQueue(), KeInsertQueue(), KeRemoveQueue(), KeRemoveQueueApc(), KeResumeThread(), KeRundownQueue(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeSetTimerEx(), KeSignalGateBoostPriority(), KeStartThread(), KeSuspendThread(), KeTerminateThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiAttachProcess(), KiCompleteTimer(), KiInsertOrSignalTimer(), KiInsertQueueApc(), and KiUnlockDispatcherDatabase().
#define KOBJECT_LOCK_BIT 0x80
Definition at line 341 of file ke.h.
Referenced by KiAcquireKobjectLock(), and KiReleaseKobjectLock().
#define KOBJECT_LOCK_BIT_NUMBER 7
Definition at line 342 of file ke.h.
Referenced by KiAcquireKobjectLock().
#define KOBJECT_TYPE_MASK 0x7f
Definition at line 343 of file ke.h.
#define KPROCESS_AUTO_ALIGNMENT_BIT 0
Definition at line 1013 of file ke.h.
Referenced by KeSetAutoAlignmentProcess().
#define KPROCESS_DISABLE_BOOST_BIT 1
Definition at line 1014 of file ke.h.
Referenced by KeSetDisableBoostProcess().
#define KPROCESS_DISABLE_QUANTUM_BIT 2
Definition at line 1015 of file ke.h.
Referenced by KeSetDisableQuantumProcess().
#define KSEMAPHORE_ACTUAL_LENGTH (FIELD_OFFSET(KSEMAPHORE, Limit) + sizeof(LONG))
Definition at line 843 of file ke.h.
#define KTHREAD_AUTO_ALIGNMENT_BIT 0
Definition at line 1162 of file ke.h.
Referenced by KeSetAutoAlignmentThread().
#define KTHREAD_DISABLE_BOOST_BIT 1
Definition at line 1163 of file ke.h.
Referenced by KeSetDisableBoostThread().
#define KWAIT_BLOCK_OFFSET_TO_BYTE0 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 0)
Definition at line 509 of file ke.h.
#define KWAIT_BLOCK_OFFSET_TO_BYTE1 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 1)
Definition at line 512 of file ke.h.
#define KWAIT_BLOCK_OFFSET_TO_BYTE2 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 2)
Definition at line 515 of file ke.h.
#define KWAIT_BLOCK_OFFSET_TO_BYTE3 (FIELD_OFFSET(KWAIT_BLOCK, SpareByte) + sizeof(KWAIT_BLOCK) * 3)
Definition at line 518 of file ke.h.
#define LOCK_OWNERSHIP_QUANTUM (WAIT_QUANTUM_DECREMENT * 4)
Definition at line 28 of file ke.h.
Referenced by KiDeferredReadyThread(), and KiScanReadyQueues().
#define MAXIMUM_CCNUMA_NODES 16
Definition at line 879 of file ke.h.
Referenced by KeNumaInitialize(), KeStartAllProcessors(), KiAllProcessorsStarted(), and KiInitializeKernel().
#define NUMBER_SERVICE_TABLES 2
Definition at line 552 of file ke.h.
Referenced by KeAddSystemServiceTable(), KeRemoveSystemServiceTable(), KiInitSystem(), and NtQuerySystemInformation().
#define PAUSE_PROCESSOR _asm { rep nop }
Definition at line 96 of file ke.h.
Referenced by KeBugCheck2().
#define PRIORITY_MASK (n) (KiMask32Array[n])
Definition at line 255 of file ke.h.
Referenced by KiDeferredReadyThread(), KiFindReadyThread(), KiScanReadyQueues(), KiSelectReadyThread(), KiSetAffinityThread(), KiSetPriorityThread(), and KxQueueReadyThread().
#define READY_SKIP_QUANTUM 2
Definition at line 34 of file ke.h.
#define ROUND_TRIP_DECREMENT_COUNT 16
Definition at line 41 of file ke.h.
#define SEMAPHORE_WAIT_BLOCK 2
Definition at line 74 of file ke.h.
#define SERVICE_NUMBER_MASK ((1 << 12) - 1)
Definition at line 553 of file ke.h.
#define SERVICE_TABLE_MASK (((1 << 1) - 1) << 4)
Definition at line 574 of file ke.h.
#define SERVICE_TABLE_SHIFT (12 - 4)
Definition at line 573 of file ke.h.
#define SERVICE_TABLE_TEST (WIN32K_SERVICE_INDEX << 4)
Definition at line 575 of file ke.h.
#define SYSTEM_SERVICE_INDEX 0
Definition at line 4355 of file ke.h.
Referenced by KeInitThread().
#define THREAD_QUANTUM (READY_SKIP_QUANTUM * CLOCK_QUANTUM_DECREMENT)
Definition at line 35 of file ke.h.
Referenced by KeInitializeProcess(), PsChangeQuantumTable(), and PspComputeQuantumAndPriority().
#define THREAD_WAIT_OBJECTS 3
Definition at line 69 of file ke.h.
Referenced by KeInitThread(), KeWaitForMultipleObjects(), and ObpWaitForMultipleObjects().
#define TIMER_WAIT_BLOCK 3
Definition at line 75 of file ke.h.
Referenced by KeDelayExecutionThread(), KeInitThread(), KeRemoveQueue(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
#define WAIT_QUANTUM_DECREMENT 1
Definition at line 27 of file ke.h.
Referenced by KiAdjustQuantumThread(), and KiDeferredReadyThread().
#define WIN32K_SERVICE_INDEX 1
Definition at line 4359 of file ke.h.
Referenced by KeAddSystemServiceTable(), KeRemoveSystemServiceTable(), and PsConvertToGuiThread().
Typedef Documentation
typedef enum _ADJUST_REASON ADJUST_REASON
typedef enum _FIRMWARE_REENTRY FIRMWARE_REENTRY
typedef enum _KAPC_ENVIRONMENT KAPC_ENVIRONMENT
typedef struct _KAPC_STATE KAPC_STATE
typedef enum _KBUGCHECK_BUFFER_DUMP_STATE KBUGCHECK_BUFFER_DUMP_STATE
typedef enum _KBUGCHECK_CALLBACK_REASON KBUGCHECK_CALLBACK_REASON
typedef struct _KBUGCHECK_CALLBACK_RECORD KBUGCHECK_CALLBACK_RECORD
typedef struct _KBUGCHECK_DUMP_IO KBUGCHECK_DUMP_IO
typedef enum _KBUGCHECK_DUMP_IO_TYPE KBUGCHECK_DUMP_IO_TYPE
typedef struct _KBUGCHECK_REASON_CALLBACK_RECORD KBUGCHECK_REASON_CALLBACK_RECORD
typedef struct _KBUGCHECK_SECONDARY_DUMP_DATA KBUGCHECK_SECONDARY_DUMP_DATA
typedef struct _KDEVICE_QUEUE KDEVICE_QUEUE
typedef struct _KDEVICE_QUEUE_ENTRY KDEVICE_QUEUE_ENTRY
typedef VOID(FASTCALL * KE_ZERO_PAGE_ROUTINE) (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
Definition at line 4692 of file ke.h.
typedef struct _KEVENT_PAIR KEVENT_PAIR
typedef struct _KEXECUTE_OPTIONS KEXECUTE_OPTIONS
typedef struct _KGUARDED_MUTEX KGUARDED_MUTEX
typedef struct _KINTERRUPT KINTERRUPT
typedef enum _KINTERRUPT_MODE KINTERRUPT_MODE
typedef struct _KMUTANT KMUTANT
typedef struct _KMUTANT KMUTEX
typedef struct DECLSPEC_CACHEALIGN _KNODE KNODE
typedef enum _KOBJECTS KOBJECTS
typedef ULONG KPAGE_FRAME
Definition at line 483 of file ke.h.
typedef struct _KPROCESS KPROCESS
typedef enum _KPROCESS_STATE KPROCESS_STATE
typedef struct _KPROCESS_VALUES KPROCESS_VALUES
typedef struct _KPROFILE KPROFILE
typedef struct _KQUEUE KQUEUE
typedef struct _KSEMAPHORE KSEMAPHORE
typedef struct _KSERVICE_TABLE_DESCRIPTOR KSERVICE_TABLE_DESCRIPTOR
typedef struct _KTHREAD KTHREAD
typedef enum _KTHREAD_STATE KTHREAD_STATE
typedef struct _KTHREAD_SWITCH_COUNTERS KTHREAD_SWITCH_COUNTERS
typedef struct _KWAIT_BLOCK KWAIT_BLOCK
typedef enum _KWAIT_REASON KWAIT_REASON
typedef enum _MEMORY_CACHING_TYPE MEMORY_CACHING_TYPE
typedef enum _MEMORY_CACHING_TYPE_ORIG MEMORY_CACHING_TYPE_ORIG
typedef enum _FIRMWARE_REENTRY * PFIRMWARE_REENTRY
typedef VOID(* PGDI_BATCHFLUSH_ROUTINE) (VOID)
Definition at line 3930 of file ke.h.
typedef struct _KAPC_STATE * PKAPC_STATE
typedef struct _KBUGCHECK_CALLBACK_RECORD * PKBUGCHECK_CALLBACK_RECORD
typedef VOID(* PKBUGCHECK_CALLBACK_ROUTINE) (IN PVOID Buffer, IN ULONG Length)
Definition at line 3654 of file ke.h.
typedef struct _KBUGCHECK_DUMP_IO * PKBUGCHECK_DUMP_IO
typedef struct _KBUGCHECK_REASON_CALLBACK_RECORD * PKBUGCHECK_REASON_CALLBACK_RECORD
typedef VOID(* PKBUGCHECK_REASON_CALLBACK_ROUTINE) (IN KBUGCHECK_CALLBACK_REASON Reason, IN struct _KBUGCHECK_REASON_CALLBACK_RECORD *Record, IN OUT PVOID ReasonSpecificData, IN ULONG ReasonSpecificDataLength)
Definition at line 3697 of file ke.h.
typedef struct _KBUGCHECK_SECONDARY_DUMP_DATA * PKBUGCHECK_SECONDARY_DUMP_DATA
typedef BOOLEAN(* PKDEBUG_ROUTINE) (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame, IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN SecondChance)
Definition at line 594 of file ke.h.
typedef BOOLEAN(* PKDEBUG_SWITCH_ROUTINE) (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN BOOLEAN SecondChance)
Definition at line 615 of file ke.h.
typedef struct _KDEVICE_QUEUE * PKDEVICE_QUEUE
typedef struct _KDEVICE_QUEUE_ENTRY * PKDEVICE_QUEUE_ENTRY
typedef PCHAR(* PKE_BUGCHECK_UNICODE_TO_ANSI) (IN PUNICODE_STRING UnicodeString, OUT PCHAR AnsiBuffer, IN ULONG MaxAnsiLength)
Definition at line 3865 of file ke.h.
typedef struct _KEVENT_PAIR * PKEVENT_PAIR
typedef struct _KEXECUTE_OPTIONS PKEXECUTE_OPTIONS
typedef struct _KGUARDED_MUTEX * PKGUARDED_MUTEX
typedef struct _KINTERRUPT* PKINTERRUPT
Definition at line 796 of file ke.h.
typedef ULONG_PTR(* PKIPI_BROADCAST_WORKER) (IN ULONG_PTR Argument)
Definition at line 2901 of file ke.h.
typedef struct _KMUTANT * PKMUTANT
typedef struct _KMUTANT * PKMUTEX
typedef struct DECLSPEC_CACHEALIGN _KNODE * PKNODE
typedef struct _KPROCESS * PKPROCESS
typedef struct _KPROCESS_VALUES * PKPROCESS_VALUES
typedef struct _KPROFILE * PKPROFILE
typedef struct _KQUEUE * PKQUEUE
typedef struct _KSEMAPHORE * PKSEMAPHORE
typedef BOOLEAN(* PKSERVICE_ROUTINE) (IN struct _KINTERRUPT *Interrupt, IN PVOID ServiceContext)
Definition at line 743 of file ke.h.
typedef struct _KSERVICE_TABLE_DESCRIPTOR * PKSERVICE_TABLE_DESCRIPTOR
typedef VOID(* PKSTART_ROUTINE) (IN PVOID StartContext)
Definition at line 645 of file ke.h.
typedef VOID(* PKSYSTEM_ROUTINE) (IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext OPTIONAL)
Definition at line 657 of file ke.h.
typedef struct _KTHREAD * PKTHREAD
typedef struct _KTHREAD_SWITCH_COUNTERS * PKTHREAD_SWITCH_COUNTERS
typedef struct _KWAIT_BLOCK * PKWAIT_BLOCK
typedef BOOLEAN(* PNMI_CALLBACK) (__in_opt PVOID Context, __in BOOLEAN Handled)
Definition at line 3776 of file ke.h.
typedef struct _KAPC_STATE * PRKAPC_STATE
typedef struct _KDEVICE_QUEUE * PRKDEVICE_QUEUE
typedef struct _KDEVICE_QUEUE_ENTRY * PRKDEVICE_QUEUE_ENTRY
typedef struct _KEVENT_PAIR * PRKEVENT_PAIR
typedef struct _KINTERRUPT * PRKINTERRUPT
Definition at line 796 of file ke.h.
typedef struct _KMUTANT * PRKMUTANT
typedef struct _KMUTANT * PRKMUTEX
typedef struct _KPROCESS * PRKPROCESS
typedef struct _KPROFILE * PRKPROFILE
typedef struct _KQUEUE * PRKQUEUE
typedef struct _KSEMAPHORE * PRKSEMAPHORE
typedef struct _KTHREAD * PRKTHREAD
typedef struct _KWAIT_BLOCK * PRKWAIT_BLOCK
Enumeration Type Documentation
enum _ADJUST_REASON
Enumerator
AdjustNone
AdjustUnwait
AdjustBoost
Definition at line 1054 of file ke.h.
enum _FIRMWARE_REENTRY
Enumerator
HalHaltRoutine
HalPowerDownRoutine
HalRestartRoutine
HalRebootRoutine
HalInteractiveModeRoutine
HalMaximumRoutine
Definition at line 4474 of file ke.h.
enum _KAPC_ENVIRONMENT
Enumerator
OriginalApcEnvironment
AttachedApcEnvironment
CurrentApcEnvironment
InsertApcEnvironment
Definition at line 353 of file ke.h.
enum _KBUGCHECK_BUFFER_DUMP_STATE
Enumerator
BufferEmpty
BufferInserted
BufferStarted
BufferFinished
BufferIncomplete
Definition at line 3644 of file ke.h.
enum _KBUGCHECK_CALLBACK_REASON
Enumerator
KbCallbackInvalid
KbCallbackReserved1
KbCallbackSecondaryDumpData
KbCallbackDumpIo
Definition at line 3688 of file ke.h.
enum _KBUGCHECK_DUMP_IO_TYPE
Enumerator
KbDumpIoInvalid
KbDumpIoHeader
KbDumpIoBody
KbDumpIoSecondaryData
KbDumpIoComplete
Definition at line 3722 of file ke.h.
enum _KINTERRUPT_MODE
Enumerator
LevelSensitive
Latched
Definition at line 366 of file ke.h.
enum _KOBJECTS
Enumerator
EventNotificationObject
EventSynchronizationObject
MutantObject
ProcessObject
QueueObject
SemaphoreObject
ThreadObject
GateObject
TimerNotificationObject
TimerSynchronizationObject
Spare2Object
Spare3Object
Spare4Object
Spare5Object
Spare6Object
Spare7Object
Spare8Object
Spare9Object
ApcObject
DpcObject
DeviceQueueObject
EventPairObject
InterruptObject
ProfileObject
ThreadedDpcObject
MaximumKernelObject
Definition at line 312 of file ke.h.
enum _KPROCESS_STATE
Enumerator
ProcessInMemory
ProcessOutOfMemory
ProcessInTransition
ProcessOutTransition
ProcessInSwap
ProcessOutSwap
Definition at line 377 of file ke.h.
enum _KTHREAD_STATE
Enumerator
Initialized
Ready
Running
Standby
Terminated
Waiting
Transition
DeferredReady
GateWait
Definition at line 390 of file ke.h.
enum _KWAIT_REASON
Enumerator
Executive
FreePage
PageIn
PoolAllocation
DelayExecution
Suspended
UserRequest
WrExecutive
WrFreePage
WrPageIn
WrPoolAllocation
WrDelayExecution
WrSuspended
WrUserRequest
WrEventPair
WrQueue
WrLpcReceive
WrLpcReply
WrVirtualMemory
WrPageOut
WrRendezvous
Spare2
Spare3
Spare4
Spare5
Spare6
WrKernel
WrResource
WrPushLock
WrMutex
WrQuantumEnd
WrDispatchInt
WrPreempted
WrYieldExecution
WrFastMutex
WrGuardedMutex
WrRundown
MaximumWaitReason
Definition at line 407 of file ke.h.
enum _MEMORY_CACHING_TYPE
Enumerator
MmNonCached
MmCached
MmWriteCombined
MmHardwareCoherentCached
MmNonCachedUnordered
MmUSWCCached
MmMaximumCacheType
Definition at line 4654 of file ke.h.
enum _MEMORY_CACHING_TYPE_ORIG
Enumerator
MmFrameBufferCached
Definition at line 4650 of file ke.h.
enum KCONTINUE_STATUS
Enumerator
ContinueError
ContinueSuccess
ContinueProcessorReselected
ContinueNextProcessor
Definition at line 621 of file ke.h.
Function Documentation
C_ASSERT ((MaximumKernelObject &KOBJECT_LOCK_BIT) = =0)
C_ASSERT (THREAD_WAIT_OBJECTS >= 3)
C_ASSERT (MAXIMUM_WAIT_OBJECTS<= 255)
C_ASSERT (sizeof(KDEVICE_QUEUE) = =0x14)
C_ASSERT (sizeof(KDEVICE_QUEUE_ENTRY) = =0x10)
BOOLEAN KdpStub (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame, IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN SecondChance)
_DECL_HAL_KE_IMPORT VOID FASTCALL KeAcquireInStackQueuedSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 609 of file queuelock.c.
References DISPATCH_LEVEL, KfRaiseIrql(), KxAcquireQueuedSpinLock(), NULL, and UNREFERENCED_PARAMETER.
Referenced by CcAcquireBcbSpinLockAndVacbLock(), CcAcquireByteRangeForWrite(), CcDeleteMbcb(), CcGetDirtyPages(), CcGetFlushedValidData(), CcGetLsnForFileObject(), CcPinFileData(), CcPrepareMdlWrite(), CcRepinBcb(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcUnpinFileDataEx(), CcWriteBehind(), ExDeleteResourceLite(), ExInitializeResourceLite(), ExpCheckForResource(), ExQuerySystemLockInformation(), KeRemoveEntryDeviceQueue(), KiAcquireInStackQueuedSpinLockForDpc(), KiDeliverApc(), MiAddMdlTracker(), MiFreeMdlTracker(), MiUpdateMdlTracker(), and MmUpdateMdlTracker().
NTKERNELAPI VOID FASTCALL KeAcquireInStackQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 705 of file queuelock.c.
References KxAcquireQueuedSpinLock(), NULL, and UNREFERENCED_PARAMETER.
Referenced by KeFreezeAllThreads(), KeStartThread(), KeTerminateThread(), KeThawAllThreads(), and KiAcquireInStackQueuedSpinLockForDpc().
NTKERNELAPI VOID FASTCALL KeAcquireInStackQueuedSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 92 of file dpclock.c.
References KiAcquireInStackQueuedSpinLockForDpc().
_DECL_HAL_KE_IMPORT VOID FASTCALL KeAcquireInStackQueuedSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 657 of file queuelock.c.
References KfRaiseIrql(), KxAcquireQueuedSpinLock(), NULL, SYNCH_LEVEL, and UNREFERENCED_PARAMETER.
Referenced by ExpGetProcessInformation(), KeAlertResumeThread(), KeAlertThread(), KeAttachProcess(), KeDetachProcess(), KeFlushQueueApc(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertQueueApc(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeRemoveQueueApc(), KeResumeThread(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeSetQuantumProcess(), KeStackAttachProcess(), KeStartThread(), KeSuspendThread(), KeTerminateThread(), KeTestAlertThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KeWaitForGate(), KiAttachProcess(), and MmSetExecuteOptions().
NTKERNELAPI KIRQL KeAcquireInterruptSpinLock (__inout PKINTERRUPT Interrupt)
Definition at line 23 of file interobj.c.
References KeAcquireSpinLockAtDpcLevel(), and KeRaiseIrql.
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KeAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number)
Definition at line 287 of file queuelock.c.
References DISPATCH_LEVEL, KfRaiseIrql(), KiGetLockQueue(), KxAcquireQueuedSpinLock(), and _KSPIN_LOCK_QUEUE::Lock.
Referenced by IoAcquireCancelSpinLock(), IoAcquireVpbSpinLock(), IoAllocateDriverObjectExtension(), IoDeleteDevice(), IoDetachDevice(), IoEnumerateDeviceObjectList(), IoGetAttachedDeviceReference(), IoGetDeviceAttachmentBaseRef(), IoGetDriverObjectExtension(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCheckUnloadDriver(), IopCheckVpbMounted(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), IopDereferenceVpbAndFree(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopGetDevicePDO(), IopGetDriverPathInformation(), IopGetMountFlag(), IopInsertRemoveDevice(), IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopInterlockedInsertHeadList(), IopInterlockedInsertTailList(), IopInterlockedRemoveHeadList(), IopResurrectDriver(), IopVerifyDeviceObjectOnStack(), IoUnregisterShutdownNotification(), MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiInitializePoolEvents(), and MmResourcesAvailable().
VOID FASTCALL KeAcquireQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 371 of file queuelock.c.
References KxAcquireQueuedSpinLock().
Referenced by KiAcquireTimerTableLock(), and KiInitializeKernel().
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KeAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number)
Definition at line 329 of file queuelock.c.
References KfRaiseIrql(), KiGetLockQueue(), KxAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, and SYNCH_LEVEL.
NTKERNELAPI KIRQL FASTCALL KeAcquireSpinLockForDpc (__inout PKSPIN_LOCK SpinLock)
Definition at line 24 of file dpclock.c.
References KiAcquireSpinLockForDpc().
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KeAcquireSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock)
Definition at line 3822 of file amd64.h.
References KfRaiseIrql(), KxAcquireSpinLock(), and SYNCH_LEVEL.
Referenced by MiCheckSystemPteProtection(), and MmProtectMdlSystemAddress().
NTKERNELAPI BOOLEAN KeAddSystemServiceTable (IN PULONG_PTR Base, IN PULONG Count OPTIONAL, IN ULONG Limit, IN PUCHAR Number, IN ULONG Index)
Definition at line 729 of file miscc.c.
References _KSERVICE_TABLE_DESCRIPTOR::Base, Count, _KSERVICE_TABLE_DESCRIPTOR::Count, FALSE, Index, KeServiceDescriptorTable, KeServiceDescriptorTableShadow, _KSERVICE_TABLE_DESCRIPTOR::Limit, NULL, _KSERVICE_TABLE_DESCRIPTOR::Number, NUMBER_SERVICE_TABLES, PAGED_CODE, TRUE, and WIN32K_SERVICE_INDEX.
BOOLEAN KeAdjustInterruptTime (IN LONGLONG TimeDelta)
Definition at line 425 of file miscc.c.
References ADJUST_INTERRUPT_TIME_CONTEXT::Adjustment, ADJUST_INTERRUPT_TIME_CONTEXT::Barrier, FALSE, ADJUST_INTERRUPT_TIME_CONTEXT::HalNumber, KeIpiGenericCall(), KeNumberProcessors, KiCalibrateTimeAdjustment(), ADJUST_INTERRUPT_TIME_CONTEXT::KiNumber, and TRUE.
Referenced by ExpInitializeExecutive(), KeSetSystemTime(), and KeStartAllProcessors().
ULONG KeAlertResumeThread (__inout PKTHREAD Thread)
Definition at line 656 of file thredobj.c.
References ALERT_INCREMENT, ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiUnwaitThread(), KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, RESUME_INCREMENT, STATUS_ALERTED, TRUE, and Waiting.
Referenced by NtAlertResumeThread().
BOOLEAN KeAlertThread (__inout PKTHREAD Thread, __in KPROCESSOR_MODE ProcessorMode)
Definition at line 571 of file thredobj.c.
References ALERT_INCREMENT, ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiUnwaitThread(), _KLOCK_QUEUE_HANDLE::OldIrql, STATUS_ALERTED, TRUE, and Waiting.
Referenced by NtAlertThread().
NTKERNELAPI VOID KeAttachProcess (__inout PRKPROCESS Process)
Definition at line 226 of file procobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, INVALID_PROCESS_ATTACH_ATTEMPT, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KiAttachProcess(), KiLockDispatcherDatabaseAtSynchLevel, _KAPC_STATE::Process, and _KTHREAD::SavedApcState.
Referenced by IopRaiseHardError(), MmCreatePeb(), MmCreateTeb(), MmDeleteTeb(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), SepRmCallLsa(), WmipCreateGuidObject(), and WmipOpenGuidObject().
VOID KeBalanceSetManager (IN PVOID Context)
Definition at line 143 of file balmgr.c.
References ExAdjustLookasideDepth(), Executive, FALSE, InterlockedCompareExchange(), KdPrint, KeGetCurrentThread(), KeInitializeDpc(), KeInitializeTimerEx(), KernelMode, KeSetPriorityThread(), KeSetTimerEx(), KeWaitForMultipleObjects(), KiAdjustIrpCredits(), KiLockDispatcherDatabase, KiReadyScanLast, KiScanReadyQueues(), KiSetInternalEvent(), KiStackOutSwapRequest, KiStackProtectTime, KiSwapEvent, KiSwappingThread, LARGE_SYSTEM_STACK_PROTECT_TIME, LOW_REALTIME_PRIORITY, MaximumObject, MmQuerySystemSize(), MmSmallSystem, MmWorkingSetManager(), MmWorkingSetManagerEvent, NULL, PERIODIC_INTERVAL, _LARGE_INTEGER::QuadPart, SMALL_SYSTEM_STACK_PROTECT_TIME, STACK_SCAN_PERIOD, Status, SynchronizationTimer, TimerExpiration, TRUE, UNREFERENCED_PARAMETER, WaitAny, _KTHREAD::WaitIrql, _KTHREAD::WaitNext, and WorkingSetManagerEvent.
Referenced by KeWaitForSingleObject(), and MmInitSystem().
VOID KeBoostPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Increment)
Definition at line 752 of file thredobj.c.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KiBoostPriorityThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), and LOW_REALTIME_PRIORITY.
Referenced by NtReadFile(), and NtSetInformationProcess().
NTKERNELAPI DECLSPEC_NORETURN VOID NTAPI KeBugCheck (__in ULONG BugCheckCode)
Definition at line 129 of file bugcheck.c.
References KeBugCheck2(), and NULL.
Referenced by ExpInitializeExecutive(), IoAssignDriveLetters(), IoBuildPartialMdl(), KeDetachProcess(), KeUnstackDetachProcess(), KeWaitForMultipleObjects(), Ki386CheckDivideByZeroTrap(), KiGetVectorInfo(), KiInitMachineDependent(), KiSetAffinityThread(), KiSetCacheInformation(), KiSetCpuVendor(), Phase1InitializationDiscard(), PspProcessDelete(), PspSystemThreadStartup(), and PspThreadDelete().
VOID KeBugCheck2 (__in ULONG BugCheckCode, __in ULONG_PTR BugCheckParameter1, __in ULONG_PTR BugCheckParameter2, __in ULONG_PTR BugCheckParameter3, __in ULONG_PTR BugCheckParameter4, __in_opt PKTRAP_FRAME TrapFrame)
Definition at line 409 of file bugcheck.c.
References ACPI_BIOS_ERROR, ACPI_BIOS_FATAL_ERROR, ASSERT, ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY, ATTEMPTED_WRITE_TO_READONLY_MEMORY, _LDR_DATA_TABLE_ENTRY::BaseDllName, BUGCHECK_UNOWNED, BUGCODE_PSS_MESSAGE, BUGCODE_PSS_MESSAGE_SIGNATURE, CONTEXT_CONTROL, CONTEXT_INTEGER, CONTEXT_SEGMENTS, _CONTEXT::ContextFlags, _KPROCESSOR_STATE::ContextFrame, _KTSS::Cs, DATA_BUS_ERROR, DBG_STATUS_BUGCHECK_FIRST, DBG_STATUS_BUGCHECK_SECOND, DbgPrint(), DbgUnLoadImageSymbols(), _KPRCB::DebuggerSavedIRQL, DRIVER_CORRUPTED_EXPOOL, DRIVER_CORRUPTED_MMPOOL, DRIVER_CORRUPTED_SYSPTES, DRIVER_IRQL_NOT_LESS_OR_EQUAL, DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS, DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION, DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL, DRIVER_PORTION_MUST_BE_NONPAGED, DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS, DRIVER_USED_EXCESSIVE_PTES, _KTSS::Ds, _CONTEXT::Eax, _KTSS::Eax, _CONTEXT::Ebp, _KTSS::Ebp, _CONTEXT::Ebx, _KTSS::Ebx, _CONTEXT::Ecx, _KTSS::Ecx, _CONTEXT::Edi, _KTSS::Edi, _CONTEXT::Edx, _KTSS::Edx, _CONTEXT::EFlags, _KTSS::EFlags, EFLAGS_V86_MASK, _CONTEXT::Eip, _KTSS::Eip, _KTSS::Es, _CONTEXT::Esi, _KTSS::Esi, _CONTEXT::Esp, _KTSS::Esp, ExPoolCodeEnd, ExPoolCodeStart, ExpWdHandler, ExpWdHandlerContext, FALSE, FAT_FILE_SYSTEM, FATAL_UNHANDLED_HARD_ERROR, _KTSS::Fs, _KTSS::Gs, HalRebootRoutine, HalReturnToFirmware(), HIGH_LEVEL, INACCESSIBLE_BOOT_DEVICE, InbvDisplayString(), InterlockedDecrement, InterlockedIncrement, IoAddTriageDumpDataBlock(), IoIsTriageDumpEnabled(), IoWriteCrashDump(), IRQL_NOT_LESS_OR_EQUAL, IS_SYSTEM_ADDRESS, KdDebuggerEnabled, KdDebuggerNotPresent, KdEnableDebuggerWithLock(), KdPitchDebugger, KeActiveProcessors, KeBugCheckActive, KeBugCheckCount, KeBugCheckOwner, KeBugCheckOwnerRecursionCount, KeBugCheckUnicodeToAnsi(), KeContextFromKframes(), KeDisableInterrupts(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeNumberProcessors, KeRaiseIrql, KERNEL_MODE_EXCEPTION_NOT_HANDLED, _KTHREAD::KernelStack, KeStallExecutionProcessor(), KGDT_R0_DATA, KiBugCheckData, KiBugCheckDebugBreak(), KiDisplayBlueScreen(), KiDumpParameterImages(), KiHardwareTrigger, KiInvokeBugCheckEntryCallbacks(), KiPcToFileHeader(), KiPollFreezeExecution(), KiProcessorBlock, KiResumeForReboot, KiSaveProcessorControlState(), KiScanBugCheckCallbackList(), KiSendFreeze(), KiSendThawExecution(), KMODE_EXCEPTION_NOT_HANDLED, MANUALLY_INITIATED_CRASH, MAX_BUFFER, MINIDUMP_BUGCHECK, MmIsSessionAddress(), MmIsSpecialPoolAddress(), MmIsSpecialPoolAddressFree(), MmLocateUnloadedDriver(), MmPoolCodeEnd, MmPoolCodeStart, MmPteCodeEnd, MmPteCodeStart, _KTHREAD::NextProcessor, NO_MORE_SYSTEM_PTES, NOTHING, NTFS_FILE_SYSTEM, NULL, _KPRCB::Number, PAGE_ALIGN, PAGE_FAULT_BEYOND_END_OF_ALLOCATION, PAGE_FAULT_IN_FREED_SPECIAL_POOL, PAGE_FAULT_IN_NONPAGED_AREA, PAGE_SIZE, PAUSE_PROCESSOR, POWER_FAILURE_SIMULATE, _KPRCB::ProcessorState, PROGRAM_COUNTER, Ready, _KSWITCHFRAME::RetAddr, RtlCaptureContext(), Running, _KDDEBUGGER_DATA64::SavedContext, _CONTEXT::SegCs, _CONTEXT::SegDs, _CONTEXT::SegEs, _CONTEXT::SegFs, _CONTEXT::SegGs, _CONTEXT::SegSs, _KPRCB::SetMember, _KTSS::Ss, _KTHREAD::State, STATUS_SYSTEM_IMAGE_BAD_SIGNATURE, SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD, SYSTEM_THREAD_EXCEPTION_NOT_HANDLED, _KTHREAD::Teb, TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE, THREAD_STUCK_IN_DEVICE_DRIVER, TRUE, and UNEXPECTED_KERNEL_MODE_TRAP.
Referenced by KeBugCheck(), and KeBugCheckEx().
NTKERNELAPI DECLSPEC_NORETURN VOID KeBugCheckEx (__in ULONG BugCheckCode, __in ULONG_PTR BugCheckParameter1, __in ULONG_PTR BugCheckParameter2, __in ULONG_PTR BugCheckParameter3, __in ULONG_PTR BugCheckParameter4)
Definition at line 137 of file bugcheck.c.
References KeBugCheck2(), and NULL.
Referenced by __bcount(), CreateSystemRootLink(), ExAllocatePoolSanityChecks(), ExCheckPoolHeader(), ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExInitSystem(), ExMapHandleToPointerEx(), ExpCheckForWorker(), ExpGetBilledProcess(), ExpInitializeExecutive(), ExpSystemErrorHandler(), ExpWorkerThread(), ExQueueWorkItem(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), FsFilterPerformCallbacks(), FsRtlWorkerThread(), InitializePool(), IoCancelFileOpen(), IoCancelIrp(), IoInitSystem(), IopfCompleteRequest(), IopFreeIrp(), IopMarkBootPartition(), IopMountVolume(), IopParseDevice(), KeAttachProcess(), KeCheckForTimer(), KeCheckIfStackExpandCalloutActive(), KeForceAttachProcess(), KeRemoveQueue(), KeRestoreFloatingPointState(), KeRundownThread(), KeStackAttachProcess(), KeStartAllProcessors(), KiDeliverApc(), KiDispatchException(), KiEspToTrapFrame(), KiFatalFilter(), KiInitializeKernel(), KiInitMachineDependent(), KiSetFeatureBits(), MiAddMdlTracker(), MiBadRefCount(), MiCheckPteRelease(), MiCheckPteReserve(), MiCheckSessionPoolAllocations(), MiCheckSystemPteProtection(), MiCleanSection(), MiCloneProcessAddressSpace(), MiComputeInitialLargePage(), MiDecrementReferenceCount(), MiDecrementShareCount(), MiDeleteAddressesInWorkingSet(), MiDeletePte(), MiDeleteSystemPageableVm(), MiDeleteValidSystemPte(), MiEliminateWorkingSetEntry(), MiFreeMdlTracker(), MiFreePoolPages(), MiFreeSessionSpaceMap(), MiFreeWsleList(), MiHandleForkTransitionPte(), MiInitializeCopyOnWritePfn(), MiInitializePfn(), MiInitializePfnAndMakePteValid(), MiInitializeReadInProgressPfn(), MiInitializeReadInProgressSinglePfn(), MiInitializeSessionIds(), MiInitializeTransitionPfn(), MiInitMachineDependent(), MiInPageSingleKernelStack(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiIssueNoPtesBugcheck(), MiLocateWsle(), MiMakeOutswappedPageResident(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MiModifiedPageWriter(), MiNoPagesLastChance(), MiRemoveFromSystemSpace(), MiRemoveIoSpaceMap(), MiRemovePageFromList(), MiRemovePteTracker(), MiRemoveUnusedSegments(), MiRemoveWsle(), MiResolveMappedFileFault(), MiSessionWideInitializeAddresses(), MiSwapWslEntries(), MiTrimPte(), MiUnlinkPageFromList(), MiWaitForInPageComplete(), MiZeroPageWorker(), MmAccessFault(), MmCleanProcessAddressSpace(), MmCommitSessionMappedView(), MmFreeContiguousMemory(), MmFreeMappingAddress(), MmFreePagesFromMdl(), MmGetSizeOfBigPoolAllocation(), MmInitSystem(), MmLockPageableDataSection(), MmMapLockedPagesSpecifyCache(), MmMapLockedPagesWithReservedMapping(), MmMapViewInSystemCache(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmUnlockCachedPage(), MmUnlockPageableImageSection(), MmUnmapReservedMapping(), MmUnmapViewInSystemCache(), MmZeroPageThread(), MxGetNextPage(), ObpCloseHandle(), ObpCloseHandleTableEntry(), Phase1InitializationDiscard(), PsInitSystem(), PsLocateSystemDll(), PspCatchCriticalBreak(), PspExitThread(), PspInitializeSystemDll(), PspInitPhase0(), PspUnhandledExceptionInSystemThread(), RawDispatch(), RtlpGetStackLimits(), SeDefaultObjectMethod(), SeInitSystem(), SepAuditFailed(), SepDeReferenceLogonSession(), and WmipSecurityMethod().
NTKERNELAPI BOOLEAN KeCancelTimer (__inout PKTIMER)
Definition at line 157 of file timerobj.c.
References ASSERT, ASSERT_TIMER, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiRemoveTreeTimer(), and KiUnlockDispatcherDatabase().
Referenced by CmpShutdownWorkers(), ExpDeleteTimer(), ExpWorkerThreadBalanceManager(), ExTimerRundown(), KiInitializeInterruptTimersDpc(), NtCancelTimer(), NtSetTimer(), and PspShutdownJobLimits().
VOID KeCheckForTimer (__in_bcount(BlockSize) PVOID BlockStart, __in SIZE_T BlockSize)
Definition at line 434 of file timerobj.c.
References CONTAINING_RECORD, _KDPC::DeferredRoutine, _KTIMER::Dpc, _KTIMER_TABLE_ENTRY::Entry, _LIST_ENTRY::Flink, Index, KE_TIMER_CHECK_FREES, KeBugCheckEx(), KeTimerCheckFlags, KiAcquireTimerTableLock(), KiLockDispatcherDatabase, KiReleaseTimerTableLock(), KiTimerTableListHead, KiUnlockDispatcherDatabase(), TIMER_OR_DPC_INVALID, and TIMER_TABLE_SIZE.
Referenced by ExFreePoolSanityChecks().
VOID KeClearTimer (__inout PKTIMER Timer)
Definition at line 124 of file timerobj.c.
References ASSERT_TIMER.
ULARGE_INTEGER KeComputeReciprocal (IN LONG Divisor, OUT PCCHAR Shift)
Definition at line 416 of file kiinit.c.
References _LARGE_INTEGER::HighPart, and _LARGE_INTEGER::LowPart.
Referenced by KiInitializeKernel().
ULONG KeComputeReciprocal32 (IN LONG Divisor, OUT PCCHAR Shift)
Definition at line 492 of file kiinit.c.
NTKERNELAPI BOOLEAN KeConnectInterrupt (__inout PKINTERRUPT Interrupt)
Definition at line 184 of file intobj.c.
References AFFINITY_MASK, ASSERT, ChainConnect, CONTAINING_RECORD, DbgPrint(), _KINTERRUPT::DispatchAddress, Enabled, FALSE, HalEnableSystemInterrupt(), HalVectorToIDTEntry, HIGH_LEVEL, InitializeListHead(), InsertTailList(), DISPATCH_INFO::Interrupt, _KINTERRUPT::InterruptListEntry, KeDisconnectInterrupt(), KeLowerIrql, KeNumberProcessors, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiChainedDispatch(), KiConnectVectorAndInterruptObject(), KiGetVectorInfo(), KiInterruptDispatch(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KxUnexpectedInterrupt0, MAXIMUM_PRIMARY_VECTOR, _KINTERRUPT::Mode, NoConnect, NormalConnect, PRIMARY_VECTOR_BASE, _KINTERRUPT::ShareVector, SYNCH_LEVEL, TRUE, DISPATCH_INFO::Type, and UnknownConnect.
Referenced by IoConnectInterrupt().
VOID KeContextFromKframes (__in PKTRAP_FRAME TrapFrame, __in_opt PKEXCEPTION_FRAME ExceptionFrame, __inout PCONTEXT ContextFrame)
Referenced by Ke386SetIOPL(), KeBugCheck2(), KiInitializeUserApc(), KiSaveProcessorState(), and PspGetContext().
VOID KeContextToKframes (__inout PKTRAP_FRAME TrapFrame, __inout_opt PKEXCEPTION_FRAME ExceptionFrame, __in PCONTEXT ContextFrame, __in ULONG ContextFlags, __in KPROCESSOR_MODE PreviousMode)
Referenced by Ke386SetIOPL(), KiContinue(), KiContinueEx(), KiContinuePreviousModeUser(), KiInitializeContextThread(), KiRaiseException(), KiRestoreProcessorState(), and PspSetContext().
NTKERNELAPI NTSTATUS KeDelayExecutionThread (__in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in PLARGE_INTEGER Interval)
Definition at line 235 of file wait.c.
References APC_LEVEL, _KTHREAD::ApcState, ASSERT, DISPATCH_LEVEL, FALSE, InitializeDelayExecution, InsertTailList(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KernelMode, KiActivateWaiterQueue(), KiAdjustQuantumThread(), KiCheckDueTime(), KiComputeWaitInterval(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabase(), KiUnlockDispatcherDatabaseFromSynchLevel, NtYieldExecution(), NULL, _KTHREAD::Preempted, _KTHREAD::Queue, ReadForWriteAccess, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_SUCCESS, STATUS_TIMEOUT, TestForAlertPending, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, _KAPC_STATE::UserApcPending, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KTHREAD::WaitListEntry, _KPRCB::WaitListHead, and _KTHREAD::WaitNext.
Referenced by CcPurgeCacheSection(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateSharedWaiterSemaphore(), ExpExpandResourceOwnerTable(), FsRtlCreateSectionForDataScan(), IoCancelThreadIo(), IoCreateFile(), IopAllocateIrpMustSucceed(), IopCancelAlertedRequest(), KiInitMachineDependent(), KiOpPatchCode(), LpcpDeletePort(), MiAllocateLargeZeroPages(), MiAttachAndLockWorkingSet(), MiCcPutPagesInTransition(), MiCheckControlAreaStatus(), MiCheckSystemTrimEndCriteria(), MiCleanSection(), MiCloneProcessAddressSpace(), MiFindContiguousPages(), MiFlushAllPages(), MiFlushSectionInternal(), MiLockCode(), MiMakeOutswappedPageResident(), MiModifiedPageWriter(), MiModifiedPageWriterWorker(), MiPurgeImageSection(), MiRemoveUnusedSegments(), MiSessionWideReserveImageAddress(), MiShutdownSystem(), MiWriteComplete(), MmAccessFault(), MmFlushSection(), MmFlushVirtualMemory(), MmGatherMemoryForHibernate(), MmGetSystemRoutineAddress(), MmIsMemoryAvailable(), MmZeroPageThread(), NtCancelIoFile(), NtCreateSection(), NtDelayExecution(), PspExitThread(), PspTerminateThreadByPointer(), and WmipFlushBuffersWithMarker().
NTKERNELAPI BOOLEAN KeDeregisterBugCheckCallback (__inout PKBUGCHECK_CALLBACK_RECORD CallbackRecord)
Definition at line 1324 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, KeBugCheckCallbackLock, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), RemoveEntryList(), and TRUE.
NTKERNELAPI BOOLEAN KeDeregisterBugCheckReasonCallback (__inout PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord)
Definition at line 1588 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, KeBugCheckCallbackLock, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), RemoveEntryList(), and TRUE.
NTSTATUS KeDeregisterNmiCallback (__in PVOID Handle)
Definition at line 1349 of file miscc.c.
References ASSERT, DISPATCH_LEVEL, ExFreePoolWithTag, _KNMI_HANDLER_CALLBACK::Handle, KeAcquireSpinLock, KeActiveProcessors, KeGetCurrentIrql(), KeReleaseSpinLock(), KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiNmiCallbackListHead, KiNmiCallbackListLock, _KNMI_HANDLER_CALLBACK::Next, NULL, STATUS_INVALID_HANDLE, and STATUS_SUCCESS.
NTKERNELAPI VOID KeDetachProcess (VOID)
Definition at line 479 of file procobj.c.
References APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, _KTHREAD::ApcStatePointer, ASSERT, DISPATCH_LEVEL, FALSE, InterlockedPushEntrySingleList(), INVALID_PROCESS_DETACH_ATTEMPT, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheck(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiMoveApcState(), KiProcessOutSwapListHead, KiRequestSoftwareInterrupt, KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapProcess(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, ProcessInMemory, ProcessOutTransition, _KTHREAD::SavedApcState, _KTHREAD::SpecialApcDisable, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, _KPROCESS::ThreadListHead, TRUE, and UserMode.
Referenced by IopRaiseHardError(), MiAttachAndLockWorkingSet(), MiDetachAndUnlockWorkingSet(), MmCreatePeb(), MmCreateTeb(), MmDeleteTeb(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), SepRmCallLsa(), WmipCreateGuidObject(), and WmipOpenGuidObject().
NTKERNELAPI BOOLEAN KeDisconnectInterrupt (__inout PKINTERRUPT Interrupt)
Definition at line 339 of file intobj.c.
References AFFINITY_MASK, ASSERT, ChainConnect, CONTAINING_RECORD, _KINTERRUPT::DispatchAddress, _KINTERRUPT::DispatchCode, FALSE, _LIST_ENTRY::Flink, HalDisableSystemInterrupt(), HalVectorToIDTEntry, DISPATCH_INFO::Interrupt, _KINTERRUPT::InterruptListEntry, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KeSweepIcache, KiChainedDispatch(), KiConnectVectorAndInterruptObject(), KiGetVectorInfo(), KiInterruptDispatch(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KxUnexpectedInterrupt0, NoConnect, NormalConnect, RemoveEntryList(), SYNCH_LEVEL, TRUE, and DISPATCH_INFO::Type.
Referenced by IoDisconnectInterrupt(), and KeConnectInterrupt().
FORCEINLINE VOID KeEnableInterrupts (__in BOOLEAN Enable)
Definition at line 3368 of file ke.h.
References _enable(), and FALSE.
Referenced by KeFreezeExecution(), KeRemoveQueueDpc(), KeThawExecution(), KiCalibrateTimeAdjustment(), KiFreezeTargetExecution(), KiI386PentiumLockErrataFixup(), KiLoadMTRR(), and KiLoadPAT().
NTKERNELAPI VOID KeEnterKernelDebugger (VOID)
Definition at line 1273 of file bugcheck.c.
References DBG_STATUS_FATAL, FALSE, HIGH_LEVEL, InterlockedDecrement, KdDebuggerEnabled, KdInitSystem(), KdPitchDebugger, KeBugCheckCount, KeDisableInterrupts(), KeRaiseIrql, KiBugCheckDebugBreak(), KiHardwareTrigger, and NULL.
NTKERNELAPI VOID FASTCALL KefAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
NTKERNELAPI PCONFIGURATION_COMPONENT_DATA KeFindConfigurationEntry (IN PCONFIGURATION_COMPONENT_DATA Child, IN CONFIGURATION_CLASS Class, IN CONFIGURATION_TYPE Type, IN PULONG Key OPTIONAL)
Definition at line 26 of file config.c.
References KeFindConfigurationNextEntry(), and NULL.
NTKERNELAPI PCONFIGURATION_COMPONENT_DATA KeFindConfigurationNextEntry (IN PCONFIGURATION_COMPONENT_DATA Child, IN CONFIGURATION_CLASS Class, IN CONFIGURATION_TYPE Type, IN PULONG Key OPTIONAL, IN PCONFIGURATION_COMPONENT_DATA * Resume)
Definition at line 57 of file config.c.
References ARGUMENT_PRESENT, _CONFIGURATION_COMPONENT_DATA::Child, _CONFIGURATION_COMPONENT::Class, _CONFIGURATION_COMPONENT_DATA::ComponentEntry, _CONFIGURATION_COMPONENT::Key, NULL, _CONFIGURATION_COMPONENT_DATA::Sibling, and _CONFIGURATION_COMPONENT::Type.
Referenced by KeFindConfigurationEntry().
FORCEINLINE void KeFindFirstSetLeftMember (__in ULONG Set, __out PULONG Member)
Definition at line 4029 of file ke.h.
References KiFindFirstSetLeftMemberInt().
Referenced by KiAdjustSimultaneousMultiThreadingCharacteristics(), KiFindReadyThread(), KiInitializeBootStructures(), and KiSelectReadyThread().
FORCEINLINE ULONG KeFindFirstSetRightMember (__in ULONG Set)
Definition at line 4074 of file ke.h.
ULONG KeFindNextRightSetAffinity (__in ULONG Number, __in KAFFINITY Set)
Definition at line 2030 of file thredsup.c.
References AFFINITY_MASK, ASSERT, and KeFindFirstSetLeftAffinity.
Referenced by KeStartThread(), KiSetAffinityThread(), and KiSetIdealNodeProcess().
FORCEINLINE VOID KeFlushEntireTb (__in BOOLEAN Invalid, __in BOOLEAN AllProcessors)
Definition at line 4122 of file ke.h.
References KxFlushEntireTb(), and UNREFERENCED_PARAMETER.
VOID KeFlushMultipleTb (IN ULONG Number, IN PVOID * Virtual, IN BOOLEAN AllProcesors)
Definition at line 161 of file flushtb.c.
References _KPROCESS::ActiveProcessors, _KTHREAD::ApcState, ASSERT, _KPRCB::CurrentThread, FALSE, FLUSH_MULTIPLE_MAXIMUM, IPI_FLUSH_MULTIPLE, IPI_INSTRUMENT_COUNT, KeActiveProcessors, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiFlushSingleTb(), KiFlushTargetMultipleTb(), KiIpiSendPacket(), KiIpiSendRequest(), KiIpiStallOnPacketTargets(), KiIpiWaitForRequestBarrier(), NULL, _KPRCB::Number, _KAPC_STATE::Process, and _KPRCB::SetMember.
VOID KeFlushProcessTb (VOID)
Definition at line 97 of file flushtb.c.
References _KPROCESS::ActiveProcessors, _KTHREAD::ApcState, _KPRCB::CurrentThread, IPI_FLUSH_PROCESS, IPI_INSTRUMENT_COUNT, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiFlushProcessTb(), KiFlushTargetProcessTb(), KiIpiSendPacket(), KiIpiSendRequest(), KiIpiStallOnPacketTargets(), KiIpiWaitForRequestBarrier(), NULL, _KPRCB::Number, _KAPC_STATE::Process, and _KPRCB::SetMember.
PLIST_ENTRY KeFlushQueueApc (__inout PKTHREAD Thread, __in KPROCESSOR_MODE ProcessorMode)
Definition at line 129 of file apcobj.c.
References ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, InitializeListHead(), _KAPC::Inserted, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), NULL, RemoveEntryList(), and UserMode.
Referenced by PspExitThread().
NTKERNELAPI VOID KeFlushQueuedDpcs (VOID)
Definition at line 553 of file dpcobj.c.
References AFFINITY_MASK, DISPATCH_LEVEL, DPC_NORMAL, DPC_THREADED, _KPRCB::DpcData, _KDPC_DATA::DpcQueueDepth, FALSE, HIGH_PRIORITY, KeActiveProcessors, KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetPriorityThread(), KeSetSystemAffinityThread(), KiRequestSoftwareInterrupt, KiSendSoftwareInterrupt(), _KPRCB::Number, PAGED_CODE, and TRUE.
Referenced by ExpDeleteTimer(), IopDeleteDriver(), and MmPageEntireDriver().
VOID FASTCALL KeFlushSingleTb (IN PVOID Virtual, IN BOOLEAN AllProcesors)
Definition at line 256 of file flushtb.c.
References _KPROCESS::ActiveProcessors, _KTHREAD::ApcState, _KPRCB::CurrentThread, FALSE, IPI_FLUSH_SINGLE, IPI_INSTRUMENT_COUNT, KeActiveProcessors, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiFlushSingleTb(), KiFlushTargetSingleTb(), KiIpiSendPacket(), KiIpiSendRequest(), KiIpiStallOnPacketTargets(), KiIpiWaitForRequestBarrier(), NULL, _KPRCB::Number, _KAPC_STATE::Process, and _KPRCB::SetMember.
LOGICAL KeForceAttachProcess (__inout PKPROCESS Process)
Definition at line 297 of file procobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, INVALID_PROCESS_ATTACH_ATTEMPT, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KeReleaseInStackQueuedSpinLock(), KiAttachProcess(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, _KAPC_STATE::Process, ProcessInMemory, ProcessInSwap, ProcessInTransition, ProcessOutSwap, ProcessOutTransition, _KTHREAD::SavedApcState, and TRUE.
Referenced by MiAttachAndLockWorkingSet().
ULONG KeForceResumeThread (__inout PKTHREAD Thread)
Definition at line 808 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, and RESUME_INCREMENT.
Referenced by PspCreateThread(), PspExitThread(), PspTerminateThreadByPointer(), and PsSuspendThread().
VOID KeFreezeAllThreads (VOID)
Definition at line 876 of file thredobj.c.
References _KTHREAD::ApcQueueable, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, _KTHREAD::FreezeCount, _KSEMAPHORE::Header, _KAPC::Inserted, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeEnterCriticalRegion(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiInsertQueueApc(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, MAXIMUM_SUSPEND_COUNT, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, _KPROCESS::ProcessLock, RESUME_INCREMENT, _DISPATCHER_HEADER::SignalState, _KTHREAD::SuspendApc, _KTHREAD::SuspendCount, _KTHREAD::SuspendSemaphore, _KPROCESS::ThreadListHead, and TRUE.
Referenced by DbgkpSuspendProcess().
BOOLEAN KeFreezeExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 54 of file debug.c.
References AFFINITY_MASK, ClearMember, Count, FALSE, Flag, FREEZE_ACTIVE, FREEZE_BACKUP, FREEZE_FROZEN, FREEZE_OWNER, FREEZE_SKIPPED_PROCESSOR, FrozenState, HIGH_LEVEL, _KPRCB::IpiFrozen, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeBugCheckActive, KeDisableInterrupts(), KeEnableInterrupts(), KeFindFirstSetLeftAffinity, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeRaiseIrql, KeStallExecutionProcessor(), KeTryToAcquireSpinLockAtDpcLevel(), KeYieldProcessor, KiFreezeExecutionLock, KiFreezeFlag, KiFreezeLockBackup, KiIpiServiceRoutine(), KiOldIrql, KiProcessorBlock, KiSendFreeze(), _KPRCB::Number, _KPRCB::SkipTick, TARGET_FROZEN, TRUE, and UNREFERENCED_PARAMETER.
NTKERNELAPI VOID FASTCALL KefReleaseSpinLockFromDpcLevel (__inout PKSPIN_LOCK SpinLock)
VOID KeGenericCallDpc (__in PKDEFERRED_ROUTINE Routine, __in_opt PVOID Context)
Definition at line 691 of file dpcobj.c.
References ASSERT, _DEFERRED_REVERSE_BARRIER::Barrier, _KPRCB::CallDpc, _KDPC::DeferredContext, _KDPC::DeferredRoutine, DISPATCH_LEVEL, ExAcquireFastMutex(), ExReleaseFastMutex(), Index, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentProcessorNumber(), KeInsertQueueDpc(), KeLowerIrql, KeNumberProcessors, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KeYieldProcessor, KiGenericCallDpcMutex, KiProcessorBlock, and _DEFERRED_REVERSE_BARRIER::TotalProcessors.
Referenced by ExGetPoolTagInfo(), Ke386IoSetAccessProcess(), Ke386SetDescriptorProcess(), Ke386SetIoAccessMap(), and Ke386SetLdtProcess().
BOOLEAN KeGetBugMessageText (__in ULONG MessageId, __out_opt PANSI_STRING ReturnedString OPTIONAL)
Definition at line 154 of file bugcheck.c.
References ARGUMENT_PRESENT, _MESSAGE_RESOURCE_DATA::Blocks, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InbvDisplayString(), KiBugCodeMessages, _MESSAGE_RESOURCE_BLOCK::LowId, MmMakeKernelResourceSectionWritable(), NULL, _MESSAGE_RESOURCE_DATA::NumberOfBlocks, _MESSAGE_RESOURCE_BLOCK::OffsetToEntries, strlen(), and TRUE.
VOID KeGetNonVolatileContextPointers (IN PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext)
PKPRCB KeGetPrcb (IN ULONG ProcessorNumber)
NTKERNELAPI ULONG KeGetRecommendedSharedDataAlignment (VOID)
Definition at line 1143 of file miscc.c.
References KeLargestCacheLine.
Referenced by ExAllocateCacheAwareRundownProtection(), ExInitializeRundownProtectionCacheAware(), ExSizeOfRundownProtectionCacheAware(), and NtQuerySystemInformation().
NTKERNELAPI VOID KeInitializeApc (__out PRKAPC Apc, __in PRKTHREAD Thread, __in KAPC_ENVIRONMENT Environment, __in PKKERNEL_ROUTINE KernelRoutine, __in_opt PKRUNDOWN_ROUTINE RundownRoutine, __in_opt PKNORMAL_ROUTINE NormalRoutine, __in_opt KPROCESSOR_MODE ProcessorMode, __in_opt PVOID NormalContext)
Definition at line 30 of file apcobj.c.
References ApcObject, ARGUMENT_PRESENT, ASSERT, CurrentApcEnvironment, FALSE, InsertApcEnvironment, KernelMode, and NIL.
Referenced by ExSwapinWorkerThreads(), IopCompleteRequest(), IopfCompleteRequest(), IoRaiseHardError(), IoRaiseInformationalHardError(), KeInitThread(), NtNotifyChangeMultipleKeys(), NtQueueApcThread(), NtSetTimer(), PsGetContextThread(), PspExitNormalApc(), PspTerminateThreadByPointer(), PsSetContextThread(), and WmipCreatePumpThread().
NTKERNELAPI VOID KeInitializeDeviceQueue (__out PKDEVICE_QUEUE DeviceQueue)
Definition at line 154 of file devquobj.c.
References DeviceQueueObject, FALSE, InitializeListHead(), KeInitializeSpinLock(), KiSetDeviceQueueKeyHint, and NULL.
Referenced by IoCreateController(), and IoCreateDevice().
NTKERNELAPI VOID KeInitializeDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
Definition at line 133 of file dpcobj.c.
References DpcObject, and KiInitializeDpc().
Referenced by CcInitializeCacheManager(), CmpCmdInit(), CmpInitDelayDerefKCBEngine(), CmpInitializeDelayedCloseTable(), InitializePool(), IoInitSystem(), IopErrorLogQueueRequest(), IopInitializeIrpStackProfiler(), KeBalanceSetManager(), KiInitializeInterruptTimers(), KiInitSpinLocks(), KiInitSystem(), MmInitSystem(), NtCreateTimer(), PspInitializeJobStructures(), WmipRegisterMcaHandler(), and WmipSetupWaitForWbem().
VOID KeInitializeEventPair (__inout PKEVENT_PAIR EventPair)
Definition at line 92 of file eventobj.c.
References EventPairObject, FALSE, KeInitializeEvent(), and SynchronizationEvent.
Referenced by NtCreateEventPair().
VOID FASTCALL KeInitializeGate (__out PKGATE Gate)
Definition at line 24 of file gateobj.c.
References GateObject, and InitializeListHead().
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), and KeInitializeGuardedMutex().
NTKERNELAPI VOID KeInitializeInterrupt (__out PKINTERRUPT Interrupt, __in PKSERVICE_ROUTINE ServiceRoutine, __in_opt PVOID ServiceContext, __out_opt PKSPIN_LOCK SpinLock, __in ULONG Vector, __in KIRQL Irql, __in KIRQL SynchronizeIrql, __in KINTERRUPT_MODE InterruptMode, __in BOOLEAN ShareVector, __in CCHAR ProcessorNumber, __in BOOLEAN FloatingSave)
Definition at line 23 of file intobj.c.
References ARGUMENT_PRESENT, CPU_INTEL, FALSE, Index, InterruptObject, KeGetCurrentPrcb(), KeInitializeSpinLock(), KeSweepDcache, KiInterruptDispatch(), KiInterruptDispatchLBControl(), KiInterruptDispatchNoLock(), KiInterruptTemplate, KiInterruptTemplateObject, NORMAL_DISPATCH_LENGTH, and UNREFERENCED_PARAMETER.
Referenced by IoConnectInterrupt().
NTKERNELAPI VOID KeInitializeMutant (__out PRKMUTANT Mutant, __in BOOLEAN InitialOwner)
Definition at line 34 of file mutntobj.c.
References _LIST_ENTRY::Blink, FALSE, _KTHREAD::Header, InitializeListHead(), InsertHeadList(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), _KTHREAD::MutantListHead, MutantObject, NULL, TRUE, and _DISPATCHER_HEADER::Type.
Referenced by MmInitSystem(), and NtCreateMutant().
NTKERNELAPI VOID KeInitializeMutex (__out PRKMUTEX Mutex, __in ULONG Level)
Definition at line 93 of file mutntobj.c.
References FALSE, InitializeListHead(), MutantObject, NULL, and UNREFERENCED_PARAMETER.
Referenced by ExpProfileInitialization(), PspLdtInitialize(), RawInitializeVcb(), and WmipDriverEntry().
VOID KeInitializeProcess (__out PRKPROCESS Process, __in KPRIORITY Priority, __in KAFFINITY Affinity, __in ULONG_PTR DirectoryTableBase[2], __in BOOLEAN Enable)
Definition at line 118 of file procobj.c.
References InitializeListHead(), IO_ACCESS_MAP_NONE, KiComputeIopmOffset, KiSetIdealNodeProcess(), ProcessInMemory, ProcessObject, and THREAD_QUANTUM.
Referenced by KiInitializeKernel(), and PspCreateProcess().
VOID KeInitializeProfile (__out PKPROFILE Profile, __in_opt PKPROCESS Process, __in_opt PVOID RangeBase, __in SIZE_T RangeSize, __in ULONG BucketSize, __in ULONG Segment, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY Affinity)
Definition at line 66 of file profobj.c.
References ARGUMENT_PRESENT, ASSERT, FALSE, KeActiveProcessors, NULL, and ProfileObject.
Referenced by NtStartProfile(), and PerfInfoProfileInit().
NTKERNELAPI VOID KeInitializeQueue (__out PRKQUEUE Queue, __in ULONG Count)
Definition at line 23 of file queueobj.c.
References ARGUMENT_PRESENT, Count, InitializeListHead(), KeNumberProcessors, and QueueObject.
Referenced by ExpWorkerInitialization(), FsRtlInitializeWorkerThread(), and NtCreateIoCompletion().
NTKERNELAPI VOID KeInitializeSemaphore (__out PRKSEMAPHORE Semaphore, __in LONG Count, __in LONG Limit)
Definition at line 32 of file semphobj.c.
References Count, InitializeListHead(), and SemaphoreObject.
Referenced by ExpAllocateSharedWaiterSemaphore(), ExReinitializeResourceLite(), FsRtlInitSystem(), IoInitSystem(), KeInitThread(), LpcpInitializePortQueue(), MmInitSystem(), NtCreateSemaphore(), PspCreateThread(), and WmipInitContext().
FORCEINLINE VOID NTAPI KeInitializeSpinLock (__out PKSPIN_LOCK SpinLock)
Definition at line 3184 of file ke.h.
Referenced by CcInitializeCacheManager(), CcInitializeCacheMap(), ExCreateCallback(), ExInitializeCallData(), ExInitializeResourceLite(), ExpInitializeLockRoutine(), ExpInitSystemPhase0(), ExpResourceInitialization(), ExpTimerInitialization(), FsRtlInitializeFileLocks(), FsRtlPrivateInitializeFileLock(), InitializePool(), IoInitSystem(), KeInitializeDeviceQueue(), KeInitializeInterrupt(), KeInitializeSpinLockEx(), KeInitSystem(), KeInitThread(), KiAmdK6InitializeMTRR(), KiInitializeAbios(), KiInitializeKernel(), KiInitializeMTRR(), KiInitSpinLocks(), KiInitSystem(), MiInitializeIoTrackers(), MiInitializeLargePageSupport(), MiInitializeLoadedModuleList(), MiInitializeSystemPtes(), MmCreateProcessAddressSpace(), MmInitializeHandBuiltProcess(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmInitSystem(), NtCreateTimer(), NtSetInformationProcess(), ObInitSystem(), PsInitializeQuotaSystem(), PspCreateThread(), RtlpTraceDatabaseInitializeLock(), WmipInitContext(), WmipInitializeNotifications(), WmipInitializeRegistration(), and WmipRegisterMcaHandler().
NTSTATUS KeInitializeThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
Definition at line 483 of file thredobj.c.
References KeInitThread(), KeStartThread(), NT_SUCCESS, Status, and STATUS_SUCCESS.
Referenced by KiInitializeKernel().
NTKERNELAPI VOID KeInitializeThreadedDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
Definition at line 168 of file dpcobj.c.
References KiInitializeDpc(), and ThreadedDpcObject.
NTKERNELAPI VOID KeInitializeTimer (__out PKTIMER Timer)
Definition at line 42 of file timerobj.c.
References KeInitializeTimerEx(), and NotificationTimer.
Referenced by CcInitializeCacheManager(), CmpCmdInit(), CmpInitDelayDerefKCBEngine(), CmpInitializeDelayedCloseTable(), ExpWorkerThreadBalanceManager(), InitializePool(), IopErrorLogQueueRequest(), IopInitializeIrpStackProfiler(), KeInitThread(), PspInitializeJobStructures(), and WmipSetupWaitForWbem().
NTKERNELAPI VOID KeInitializeTimerEx (__out PKTIMER Timer, __in TIMER_TYPE Type)
Definition at line 74 of file timerobj.c.
References FALSE, InitializeListHead(), NULL, and TimerNotificationObject.
Referenced by IoInitSystem(), KeBalanceSetManager(), KeInitializeTimer(), KiInitializeInterruptTimers(), MmInitSystem(), NtCreateTimer(), and WmipRegisterMcaHandler().
BOOLEAN KeInitSystem (VOID)
Definition at line 58 of file kiinit.c.
References DPC_THREADED, _KPRCB::DpcData, _KPRCB::DpcEvent, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, FALSE, Handle, Index, InitializeListHead(), InitializeObjectAttributes, KeInitializeEvent(), KeInitializeSpinLock(), KeNumberProcessors, KeThreadDpcEnable, KiExecuteDpc(), KiInitMachineDependent(), KiProcessorBlock, NT_SUCCESS, NULL, PsCreateSystemThread(), Status, SynchronizationEvent, THREAD_ALL_ACCESS, and ZwClose().
Referenced by Phase1InitializationDiscard().
NTSTATUS KeInitThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
Definition at line 32 of file thredobj.c.
References AdjustNone, _KSERVICE_TABLE_DESCRIPTOR::Base, _LIST_ENTRY::Blink, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, Index, Initialized, InitializeListHead(), KeInitializeApc(), KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitializeTimer(), KERNEL_STACK_SIZE, KernelMode, KeServiceDescriptorTable, KiInitializeContextThread(), KiSuspendNop(), KiSuspendRundown(), KiSuspendThread(), _KSERVICE_TABLE_DESCRIPTOR::Limit, MmCreateKernelStack(), MmDeleteKernelStack(), NULL, _KWAIT_BLOCK::Object, OriginalApcEnvironment, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_TIMEOUT, SYSTEM_SERVICE_INDEX, THREAD_WAIT_OBJECTS, ThreadObject, TIMER_WAIT_BLOCK, TRUE, UserMode, WaitAny, _KWAIT_BLOCK::WaitKey, _KWAIT_BLOCK::WaitListEntry, _DISPATCHER_HEADER::WaitListHead, and _KWAIT_BLOCK::WaitType.
Referenced by KeInitializeThread(), and PspCreateThread().
NTKERNELAPI BOOLEAN KeInsertByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry, __in ULONG SortKey)
Definition at line 267 of file devquobj.c.
References ASSERT_DEVICE_QUEUE, _LIST_ENTRY::Blink, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, InsertTailList(), IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiReleaseInStackQueuedSpinLockForDpc(), _KDEVICE_QUEUE_ENTRY::SortKey, and TRUE.
Referenced by IoStartPacket().
NTKERNELAPI BOOLEAN KeInsertDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
Definition at line 199 of file devquobj.c.
References ASSERT_DEVICE_QUEUE, FALSE, InsertTailList(), KiAcquireInStackQueuedSpinLockForDpc(), KiReleaseInStackQueuedSpinLockForDpc(), and TRUE.
Referenced by IoAllocateController(), and IoStartPacket().
NTKERNELAPI LONG KeInsertHeadQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
Definition at line 165 of file queueobj.c.
References ASSERT, ASSERT_QUEUE, DISPATCH_LEVEL, KeGetCurrentIrql(), KiExitDispatcher(), KiInsertQueue(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
NTKERNELAPI LONG KeInsertQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
Definition at line 107 of file queueobj.c.
References ASSERT, ASSERT_QUEUE, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KiExitDispatcher(), KiInsertQueue(), KiLockDispatcherDatabase, and KiUnlockDispatcherDatabaseFromSynchLevel.
Referenced by ExpCheckQueueShutdown(), ExpShutdownWorkerThreads(), ExQueueWorkItem(), FsRtlpPostStackOverflow(), IopCompleteRequest(), and IoSetIoCompletion().
NTKERNELAPI BOOLEAN KeInsertQueueApc (__inout PRKAPC Apc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2, __in KPRIORITY Increment)
Definition at line 228 of file apcobj.c.
References _KTHREAD::ApcQueueable, _KTHREAD::ApcQueueLock, ASSERT, ASSERT_APC, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiInsertQueueApc(), _KLOCK_QUEUE_HANDLE::OldIrql, and TRUE.
Referenced by CmpPostNotify(), ExpTimerDpcRoutine(), ExSwapinWorkerThreads(), IopCompleteRequest(), IopfCompleteRequest(), IoRaiseHardError(), IoRaiseInformationalHardError(), NtQueueApcThread(), PsGetContextThread(), PspExitNormalApc(), PspTerminateThreadByPointer(), PsSetContextThread(), and WmipCreatePumpThread().
NTKERNELAPI BOOLEAN KeInsertQueueDpc (__inout PRKDPC Dpc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2)
Definition at line 203 of file dpcobj.c.
References AFFINITY_MASK, ASSERT_DPC, DISPATCH_LEVEL, DPC_THREADED, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KPRCB::DpcInterruptRequested, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _KPRCB::DpcRequestRate, _KPRCB::DpcRoutineActive, _KPRCB::DpcSetEventRequest, _KPRCB::DpcThreadActive, _KPRCB::DpcThreadRequested, FALSE, HIGH_LEVEL, HighImportance, InsertHeadList(), InsertTailList(), InterlockedCompareExchangePointer, InterlockedExchange(), KeGetCurrentPrcb(), KeIsIdleHaltSet, KeLowerIrql, KeMemoryBarrier(), KeRaiseIrql, KiAcquireSpinLock(), KiIdleSummary, KiProcessorBlock, KiReleaseSpinLock(), KiRequestSoftwareInterrupt, KiSelectDpcData(), KiSendSoftwareInterrupt(), LowImportance, MAXIMUM_PROCESSORS, _KPRCB::MaximumDpcQueueDepth, _KPRCB::MinimumDpcRate, NULL, _KPRCB::Number, _KPRCB::QuantumEnd, and TRUE.
Referenced by KeGenericCallDpc(), KiCalibrateTimeAdjustment(), KiSignalTimer(), KiTimerExpiration(), KiTimerListExpire(), WmipInsertQueueMCEDpc(), WmipMceDelivery(), and WmipMceEventDelivery().
BOOLEAN FASTCALL KeInvalidAccessAllowed (__in_opt PVOID TrapInformation)
Definition at line 2861 of file decode.c.
References ARGUMENT_PRESENT, _KTRAP_FRAME::Eip, ExpInterlockedPopEntrySListFault(), FALSE, KeUserPopEntrySListFault, KGDT_R0_CODE, KGDT_R3_CODE, RPL_MASK, _KTRAP_FRAME::SegCs, and TRUE.
Referenced by MiAccessCheck(), and MmAccessFault().
NTKERNELAPI BOOLEAN KeInvalidateAllCaches (VOID)
Definition at line 23 of file flush.c.
References FALSE, IPI_INVALIDATE_ALL, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeGetCurrentPrcb(), KeI386CpuType, KeLowerIrql, KeRaiseIrqlToSynchLevel(), KeReleaseSpinLockFromDpcLevel(), KiInvalidateAllCachesTarget(), KiIpiSendRequest(), KiIpiSendSynchronousPacket, KiIpiStallOnPacketTargets(), KiIpiWaitForRequestBarrier(), KiReverseStallIpiLock, NULL, _KPRCB::ReverseStall, _KPRCB::SetMember, and TRUE.
ULONG_PTR KeIpiGenericCall (IN PKIPI_BROADCAST_WORKER BroadcastFunction, IN ULONG_PTR Context)
Definition at line 34 of file xipi.c.
References Count, IPI_LEVEL, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KeNumberProcessors, KeReleaseSpinLockFromDpcLevel(), KeYieldProcessor, KfRaiseIrql(), KiIpiGenericCallTarget(), KiIpiSendPacket(), KiIpiStallOnPacketTargets(), KiReverseStallIpiLock, _KPRCB::SetMember, Status, and SYNCH_LEVEL.
Referenced by KeAdjustInterruptTime(), KeSetIntervalProfile(), KiInitMachineDependent(), KiOpPatchCode(), and KiRestoreFastSyscallReturnState().
FORCEINLINE BOOLEAN KeIsSMTSetIdle (__in PKPRCB Prcb)
Definition at line 2683 of file ke.h.
References FALSE, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KiSelectNextThread(), and KiSwapThread().
NTKERNELAPI BOOLEAN KeIsWaitListEmpty (__in PVOID Object)
Definition at line 477 of file wait.c.
References _LIST_ENTRY::Flink, _KEVENT::Header, KeMemoryBarrier(), and _DISPATCHER_HEADER::WaitListHead.
FORCEINLINE VOID KeLoopTbFlushTimeStampUnlocked (VOID)
Definition at line 4319 of file ke.h.
References IN, KeMemoryBarrier(), KeSetSystemTime(), KeYieldProcessor, OUT, and VOID.
Referenced by MiCompareTbFlushTimeStamp().
VOID KeNumaInitialize (VOID)
Definition at line 559 of file kiinit.c.
References ASSERT, HalNumaTopologyInterface, HalQuerySystemInformation, KeNumberNodes, KiQueryProcessorNode, MAXIMUM_CCNUMA_NODES, NT_SUCCESS, NULL, _HAL_NUMA_TOPOLOGY_INTERFACE::NumberOfNodes, _HAL_NUMA_TOPOLOGY_INTERFACE::PageToNode, _HAL_NUMA_TOPOLOGY_INTERFACE::QueryProcessorNode, and Status.
Referenced by ExpInitializeExecutive().
VOID KeOptimizeProcessorControlState (VOID)
Definition at line 2891 of file kernlini.c.
References Ke386ConfigureCyrixProcessor().
NTKERNELAPI LONG KePulseEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
Definition at line 163 of file eventobj.c.
References ASSERT, ASSERT_EVENT, DISPATCH_LEVEL, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), ReadForWriteAccess, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by MiComputeSystemTrimCriteria(), MiFlushSectionInternal(), MiWriteComplete(), MmLockPageableSectionByHandle(), MmResourcesAvailable(), MmUnlockPageableImageSection(), and NtPulseEvent().
NTKERNELAPI KAFFINITY KeQueryActiveProcessors (VOID)
Definition at line 856 of file miscc.c.
References KeActiveProcessors, and PAGED_CODE.
LOGICAL KeQueryAutoAlignmentThread (__in PKTHREAD Thread)
Definition at line 1014 of file thredobj.c.
References ASSERT_THREAD.
LONG KeQueryBasePriorityThread (__in PKTHREAD Thread)
Definition at line 1045 of file thredobj.c.
References ASSERT, ASSERT_THREAD, _KPROCESS::BasePriority, DISPATCH_LEVEL, HIGH_PRIORITY, KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiAcquireThreadLock(), and KiReleaseThreadLock().
Referenced by NtQueryInformationThread().
NTKERNELAPI ULONGLONG KeQueryInterruptTime (VOID)
Definition at line 37 of file miscc.c.
References KiQueryInterruptTime, and _LARGE_INTEGER::QuadPart.
Referenced by ExGetNextWakeTime(), and KiCalibrateTimeAdjustment().
ULONG KeQueryIntervalProfile (__in KPROFILE_SOURCE Source)
Definition at line 161 of file profobj.c.
References HalProfileSourceInformation, HalQuerySystemInformation, _HAL_PROFILE_SOURCE_INFORMATION::Interval, KiProfileAlignmentFixupInterval, KiProfileInterval, NT_SUCCESS, ProfileAlignmentFixup, ProfileTime, _HAL_PROFILE_SOURCE_INFORMATION::Source, Status, and _HAL_PROFILE_SOURCE_INFORMATION::Supported.
Referenced by NtQueryIntervalProfile().
NTSTATUS KeQueryLogicalProcessorInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnLength)
Definition at line 884 of file miscc.c.
References _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::Cache, Index, KeActiveProcessors, KeNodeBlock, KeNumberNodes, KiProcessorBlock, LTP_PC_SMT, _KPRCB::MultiThreadProcessorSet, _KPRCB::MultiThreadSetMaster, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::NumaNode, PAGED_CODE, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::ProcessorCore, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::ProcessorMask, RelationCache, RelationNumaNode, RelationProcessorCore, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::Relationship, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::Reserved, _KPRCB::SetMember, Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTKERNELAPI KPRIORITY KeQueryPriorityThread (__in PKTHREAD Thread)
Definition at line 1106 of file thredobj.c.
References ASSERT_THREAD.
ULONG KeQueryRuntimeProcess (__in PKPROCESS Process, __out PULONG UserTime)
Definition at line 790 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), _KTHREAD::KernelTime, and _KTHREAD::UserTime.
Referenced by NtQueryInformationProcess(), NtQuerySystemInformation(), NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), and WmiGetClock().
NTKERNELAPI ULONG KeQueryRuntimeThread (__in PKTHREAD Thread, __out PULONG UserTime)
Definition at line 1134 of file thredobj.c.
References ASSERT_THREAD.
NTKERNELAPI VOID KeQuerySystemTime (OUT PLARGE_INTEGER CurrentTime)
Definition at line 68 of file miscc.c.
References KiQuerySystemTime.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmpCmdHiveClose(), CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreate(), CmpDoCreateChild(), CmpSetSecurityDescriptorInfo(), CmRegisterCallback(), CmRenameKey(), CmSetKeyUserFlags(), CmSetValueKey(), DbgkExitProcess(), ExGetNextWakeTime(), ExHandleTest(), ExpAllocateUuids(), ExpRaiseHardError(), ExpUuidInitialization(), FsRtlAddToTunnelCache(), FsRtlPruneTunnelCache(), HvpWriteLog(), IopInitializeBuiltinDriver(), IopLoadDriver(), IoWMICompleteRequest(), IoWriteErrorLogEntry(), MiAdjustClaimParameters(), MiDoReplacement(), MiGatherPagefilePages(), MiProcessWorkingSets(), MiRearrangeWorkingSetExpansionList(), MiRememberUnloadedDriver(), MiSessionOutSwapProcess(), MiWriteComplete(), MmInitializeHandBuiltProcess(), MmInitializeProcessAddressSpace(), NtCreateSymbolicLinkObject(), NtQueryInformationProcess(), NtQuerySystemInformation(), NtWaitForDebugEvent(), PspCreateProcess(), PspCreateThread(), PspExitThread(), PspUserThreadStartup(), WmiGetClock(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipBuildMcaCmcEvent(), WmipFinalizeHeader(), WmipFireOffWmiEvent(), WmipInitContext(), WmipLogger(), WmipPrepareHeader(), WmipSendNotification(), and WmipStartLogger().
NTKERNELAPI ULONG KeQueryTimeIncrement (VOID)
Definition at line 128 of file miscc.c.
References KeMaximumIncrement.
Referenced by CcInitializeCacheManager().
ULONGLONG KeQueryTimerDueTime (__in PKTIMER Timer)
Definition at line 379 of file timerobj.c.
References ASSERT_TIMER, KiLockDispatcherDatabase, and KiUnlockDispatcherDatabase().
Referenced by ExGetNextWakeTime().
VOID KeQueryValuesProcess (__in PKPROCESS Process, __out PKPROCESS_VALUES Values)
Definition at line 854 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeMaximumIncrement, KeReleaseInStackQueuedSpinLock(), _KTHREAD::KernelTime, UInt32x32To64, and _KTHREAD::UserTime.
Referenced by ExpCopyProcessInfo(), NtQueryInformationJobObject(), NtQueryInformationProcess(), and PspFoldProcessAccountingIntoJob().
_DECL_HAL_KE_IMPORT KIRQL KeRaiseIrqlToDpcLevel (VOID)
Referenced by Phase1InitializationDiscard().
_DECL_HAL_KE_IMPORT KIRQL KeRaiseIrqlToSynchLevel (VOID)
Referenced by KeContextToKframes(), KeDelayExecutionThread(), KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeInvalidateAllCaches(), KeQueryBasePriorityThread(), KeRemoveQueue(), KeSignalGateBoostPriority(), KeStartAllProcessors(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiIdleSchedule(), KiInitializeKernel(), KiQuantumEnd(), KiRetireDpcList(), KxFlushEntireTb(), MiProcessLoaderEntry(), NtYieldExecution(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
NTSTATUS KeRaiseUserException (IN NTSTATUS ExceptionCode)
Definition at line 956 of file exceptn.c.
References _KTRAP_FRAME::Eip, except, EXCEPTION_EXECUTE_HANDLER, KeGetCurrentThread(), KeRaiseUserExceptionDispatcher, KiEspFromTrapFrame(), MODE_MASK, NULL, ProbeForWriteSmallStructure(), _KTRAP_FRAME::SegCs, _KTHREAD::Teb, _KTHREAD::TrapFrame, and UserMode.
Referenced by ExMapHandleToPointerEx(), ObpCloseHandle(), and ObpCloseHandleTableEntry().
NTKERNELAPI LONG KeReadStateEvent (__in PRKEVENT Event)
Definition at line 251 of file eventobj.c.
References ASSERT_EVENT.
Referenced by IopCancelAlertedRequest(), IopConnectLinkTrackingPort(), IopSendMessageToTrackService(), MiFlushSectionInternal(), MiGetInPageSupportBlock(), MiNotifyMemoryEvents(), NtQueryEvent(), and PspAddProcessToJob().
LONG KeReadStateMutant (__in PRKMUTANT Mutant)
Definition at line 140 of file mutntobj.c.
References ASSERT_MUTANT.
Referenced by NtQueryMutant(), and RawCheckForDismount().
NTKERNELAPI LONG KeReadStateMutex (__in PRKMUTEX Mutex)
LONG KeReadStateProcess (__in PKPROCESS Process)
Definition at line 939 of file procobj.c.
References ASSERT_PROCESS.
Referenced by NtSetInformationJobObject().
NTKERNELAPI LONG KeReadStateQueue (__in PRKQUEUE Queue)
Definition at line 79 of file queueobj.c.
References ASSERT_QUEUE.
Referenced by ExpDetectWorkerThreadDeadlock(), and NtQueryIoCompletion().
NTKERNELAPI LONG KeReadStateSemaphore (__in PRKSEMAPHORE Semaphore)
Definition at line 78 of file semphobj.c.
References ASSERT_SEMAPHORE.
Referenced by IoRaiseInformationalHardError(), LpcpDestroyPortQueue(), LpcpRequestWaitReplyPort(), NtQuerySemaphore(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), and WmipNotifyLogger().
BOOLEAN KeReadStateThread (__in PKTHREAD Thread)
Definition at line 1168 of file thredobj.c.
References ASSERT_THREAD.
Referenced by NtQueryInformationThread(), PspExitThread(), and PspWaitForUsermodeExit().
NTKERNELAPI BOOLEAN KeReadStateTimer (__in PKTIMER Timer)
Definition at line 211 of file timerobj.c.
References ASSERT_TIMER.
Referenced by NtCancelTimer(), NtQueryTimer(), and NtSetTimer().
FORCEINLINE ULONG KeReadTbFlushTimeStamp (VOID)
Definition at line 4298 of file ke.h.
References KeMemoryBarrier(), and KiTbFlushTimeStamp.
Referenced by MiCompareTbFlushTimeStamp(), MiDeleteSystemPageableVm(), MiReleaseSystemPtes(), MmMapViewInSystemCache(), MmUnmapLockedPages(), and MmUnmapViewInSystemCache().
VOID KeReadyThread (__inout PKTHREAD Thread)
Definition at line 1200 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiReadyThread(), and KiUnlockDispatcherDatabase().
Referenced by PspCreateThread().
NTKERNELAPI BOOLEAN KeRegisterBugCheckCallback (__out PKBUGCHECK_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_CALLBACK_ROUTINE CallbackRoutine, __in PVOID Buffer, __in ULONG Length, __in PUCHAR Component)
Definition at line 1383 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, InsertHeadList(), KeBugCheckCallbackListHead, KeBugCheckCallbackLock, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), and TRUE.
NTKERNELAPI BOOLEAN KeRegisterBugCheckReasonCallback (__out PKBUGCHECK_REASON_CALLBACK_RECORD CallbackRecord, __in PKBUGCHECK_REASON_CALLBACK_ROUTINE CallbackRoutine, __in KBUGCHECK_CALLBACK_REASON Reason, __in PUCHAR Component)
Definition at line 1647 of file bugcheck.c.
References BufferEmpty, BufferInserted, FALSE, HIGH_LEVEL, InsertHeadList(), KeBugCheckCallbackLock, KeBugCheckReasonCallbackListHead, KeLowerIrql, KeRaiseIrql, KiAcquireSpinLock(), KiReleaseSpinLock(), and TRUE.
NTKERNELAPI PVOID KeRegisterNmiCallback (__in PNMI_CALLBACK CallbackRoutine, __in_opt PVOID Context)
Definition at line 1260 of file miscc.c.
References ASSERT, _KNMI_HANDLER_CALLBACK::Callback, _KNMI_HANDLER_CALLBACK::Context, DISPATCH_LEVEL, ExAllocatePoolWithTag, _KNMI_HANDLER_CALLBACK::Handle, InterlockedCompareExchangePointer, KeAcquireSpinLock, KeGetCurrentIrql(), KeReleaseSpinLock(), KiNmiCallbackListHead, KiNmiCallbackListLock, _KNMI_HANDLER_CALLBACK::Next, NonPagedPool, and NULL.
_DECL_HAL_KE_IMPORT VOID FASTCALL KeReleaseInStackQueuedSpinLock (__in PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 752 of file queuelock.c.
References KeLowerIrql, and KxReleaseQueuedSpinLock().
Referenced by CcAcquireByteRangeForWrite(), CcDeleteMbcb(), CcGetDirtyPages(), CcGetLsnForFileObject(), CcPinFileData(), CcPrepareMdlWrite(), CcReleaseBcbSpinLockAndVacbLock(), CcRepinBcb(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcUnpinFileDataEx(), CcWriteBehind(), ExDeleteResourceLite(), ExInitializeResourceLite(), ExpCheckForResource(), ExpGetProcessInformation(), ExQuerySystemLockInformation(), KeDetachProcess(), KeFlushQueueApc(), KeForceAttachProcess(), KeFreezeAllThreads(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeRemoveEntryDeviceQueue(), KeRemoveQueueApc(), KeSetQuantumProcess(), KeStartThread(), KeSuspendThread(), KeTestAlertThread(), KeUnstackDetachProcess(), KeWaitForGate(), KiDeliverApc(), KiReleaseInStackQueuedSpinLockForDpc(), MiAddMdlTracker(), MiFreeMdlTracker(), MiUpdateMdlTracker(), MmSetExecuteOptions(), and MmUpdateMdlTracker().
NTKERNELAPI VOID FASTCALL KeReleaseInStackQueuedSpinLockForDpc (__in PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 127 of file dpclock.c.
References KiReleaseInStackQueuedSpinLockForDpc().
NTKERNELAPI VOID FASTCALL KeReleaseInStackQueuedSpinLockFromDpcLevel (__in PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 785 of file queuelock.c.
References KxReleaseQueuedSpinLock().
Referenced by CcGetFlushedValidData(), KeAlertResumeThread(), KeAlertThread(), KeDetachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertQueueApc(), KeResumeThread(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeStartThread(), KeSuspendThread(), KeTerminateThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KeWaitForGate(), KiAttachProcess(), and KiReleaseInStackQueuedSpinLockForDpc().
NTKERNELAPI VOID KeReleaseInterruptSpinLock (__inout PKINTERRUPT Interrupt, __in KIRQL OldIrql)
Definition at line 59 of file interobj.c.
References KeLowerIrql, and KeReleaseSpinLockFromDpcLevel().
NTKERNELAPI LONG KeReleaseMutant (__inout PRKMUTANT Mutant, __in KPRIORITY Increment, __in BOOLEAN Abandoned, __in BOOLEAN Wait)
Definition at line 172 of file mutntobj.c.
References ASSERT, ASSERT_MUTANT, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), NULL, RemoveEntryList(), STATUS_ABANDONED, STATUS_MUTANT_NOT_OWNED, TRUE, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by ExpDeleteMutant(), KeReleaseMutex(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiShutdownSystem(), MmLoadSystemImage(), MmUnloadSystemImage(), NtReleaseMutant(), and NtSignalAndWaitForSingleObject().
NTKERNELAPI LONG KeReleaseMutex (__inout PRKMUTEX Mutex, __in BOOLEAN Wait)
Definition at line 310 of file mutntobj.c.
References ASSERT_MUTANT, FALSE, and KeReleaseMutant().
Referenced by NtStartProfile(), NtStopProfile(), PspQueryDescriptorThread(), PspQueryLdtInformation(), PspSetLdtInformation(), PspSetLdtSize(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawCheckForDismount(), RawCleanup(), RawClose(), RawCreate(), RawUserFsCtrl(), RawVerifyVolume(), WmipLeaveCritSection(), and WmipLeaveTraceCritSection().
_DECL_HAL_KE_IMPORT VOID FASTCALL KeReleaseQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __in KIRQL OldIrql)
Definition at line 540 of file queuelock.c.
References KeLowerIrql, KiGetLockQueue(), and KxReleaseQueuedSpinLock().
Referenced by IoAllocateDriverObjectExtension(), IoDeleteDevice(), IoDetachDevice(), IoEnumerateDeviceObjectList(), IoGetAttachedDeviceReference(), IoGetDeviceAttachmentBaseRef(), IoGetDriverObjectExtension(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCheckUnloadDriver(), IopCheckVpbMounted(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), IopDereferenceVpbAndFree(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopGetDevicePDO(), IopGetDriverPathInformation(), IopGetMountFlag(), IopInsertRemoveDevice(), IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopInterlockedInsertHeadList(), IopInterlockedInsertTailList(), IopInterlockedRemoveHeadList(), IopResurrectDriver(), IopVerifyDeviceObjectOnStack(), IoReleaseCancelSpinLock(), IoReleaseVpbSpinLock(), IoUnregisterShutdownNotification(), MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiInitializePoolEvents(), and MmResourcesAvailable().
VOID FASTCALL KeReleaseQueuedSpinLockFromDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 578 of file queuelock.c.
References KxReleaseQueuedSpinLock().
Referenced by KiInitializeKernel(), and KiReleaseTimerTableLock().
NTKERNELAPI LONG KeReleaseSemaphore (__inout PRKSEMAPHORE Semaphore, __in KPRIORITY Increment, __in LONG Adjustment, __in BOOLEAN Wait)
Definition at line 111 of file semphobj.c.
References ASSERT, ASSERT_SEMAPHORE, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), ReadForWriteAccess, STATUS_SEMAPHORE_LIMIT_EXCEEDED, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by ExConvertExclusiveToSharedLite(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), FsRtlDeregisterUncProvider(), FsRtlRegisterUncProvider(), IoRaiseInformationalHardError(), LpcpDestroyPortQueue(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiCheckForControlAreaDeletion(), MiContractPagingFiles(), MiIssuePageExtendRequest(), MiIssuePageExtendRequestNoWait(), NtAcceptConnectPort(), NtCompleteConnectPort(), NtReleaseKeyedEvent(), NtReleaseSemaphore(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSignalAndWaitForSingleObject(), NtWaitForKeyedEvent(), and WmipNotifyLogger().
NTKERNELAPI VOID FASTCALL KeReleaseSpinLockForDpc (__inout PKSPIN_LOCK SpinLock, __in KIRQL OldIrql)
Definition at line 56 of file dpclock.c.
References KiReleaseSpinLockForDpc().
NTKERNELAPI PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
Definition at line 439 of file devquobj.c.
References ASSERT, ASSERT_DEVICE_QUEUE, _LIST_ENTRY::Blink, CONTAINING_RECORD, _KDEVICE_QUEUE_ENTRY::DeviceListEntry, FALSE, _LIST_ENTRY::Flink, _KDEVICE_QUEUE_ENTRY::Inserted, IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiReleaseInStackQueuedSpinLockForDpc(), KiSetDeviceQueueKeyHint, NULL, RemoveEntryList(), _KDEVICE_QUEUE_ENTRY::SortKey, and TRUE.
Referenced by IopStartNextPacketByKey().
NTKERNELAPI PKDEVICE_QUEUE_ENTRY KeRemoveByKeyDeviceQueueIfBusy (__inout PKDEVICE_QUEUE DeviceQueue, __in ULONG SortKey)
Definition at line 588 of file devquobj.c.
References ASSERT_DEVICE_QUEUE, CONTAINING_RECORD, _KDEVICE_QUEUE_ENTRY::DeviceListEntry, FALSE, _LIST_ENTRY::Flink, _KDEVICE_QUEUE_ENTRY::Inserted, IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiInvalidateDeviceQueueKeyHint, KiReleaseInStackQueuedSpinLockForDpc(), NULL, RemoveEntryList(), and RemoveHeadList().
NTKERNELAPI PKDEVICE_QUEUE_ENTRY KeRemoveDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue)
Definition at line 369 of file devquobj.c.
References ASSERT, ASSERT_DEVICE_QUEUE, CONTAINING_RECORD, FALSE, _KDEVICE_QUEUE_ENTRY::Inserted, IsListEmpty, KiAcquireInStackQueuedSpinLockForDpc(), KiInvalidateDeviceQueueKeyHint, KiReleaseInStackQueuedSpinLockForDpc(), NULL, RemoveHeadList(), and TRUE.
Referenced by IoFreeController(), and IopStartNextPacket().
NTKERNELAPI BOOLEAN KeRemoveEntryDeviceQueue (__inout PKDEVICE_QUEUE DeviceQueue, __inout PKDEVICE_QUEUE_ENTRY DeviceQueueEntry)
Definition at line 683 of file devquobj.c.
References ASSERT, ASSERT_DEVICE_QUEUE, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLock(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), KiInvalidateDeviceQueueKeyHint, RemoveEntryList(), and TRUE.
NTKERNELAPI PLIST_ENTRY KeRemoveQueue (__inout PRKQUEUE Queue, __in KPROCESSOR_MODE WaitMode, __in_opt PLARGE_INTEGER Timeout)
Definition at line 258 of file queueobj.c.
References APC_LEVEL, _KTHREAD::ApcState, ARGUMENT_PRESENT, ASSERT, ASSERT_QUEUE, _LIST_ENTRY::Blink, DISPATCH_LEVEL, ExWorkerQueue, FALSE, _LIST_ENTRY::Flink, InitializeRemoveQueue, InsertTailList(), INVALID_WORK_QUEUE_ITEM, KeBugCheckEx(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KernelMode, KiActivateWaiterQueue(), KiCheckDueTime(), KiComputeWaitInterval(), KiExitDispatcher(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KTHREAD::Queue, _KTHREAD::QueueListEntry, RemoveEntryList(), _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_TIMEOUT, STATUS_USER_APC, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, ULongToPtr, _KAPC_STATE::UserApcPending, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitListEntry, _KPRCB::WaitListHead, _KTHREAD::WaitNext, and _KTHREAD::WaitReason.
Referenced by ExpWorkerThread(), FsRtlWorkerThread(), and NtRemoveIoCompletion().
BOOLEAN KeRemoveQueueApc (__inout PKAPC Apc)
Definition at line 308 of file apcobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcStatePointer, ASSERT, ASSERT_APC, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), _KAPC_STATE::KernelApcPending, KernelMode, KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, RemoveEntryList(), and _KAPC_STATE::UserApcPending.
Referenced by CmNotifyRunDown(), ExTimerRundown(), NtCancelTimer(), and NtSetTimer().
NTKERNELAPI BOOLEAN KeRemoveQueueDpc (__inout PRKDPC Dpc)
Definition at line 466 of file dpcobj.c.
References ASSERT_DPC, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, FALSE, KeDisableInterrupts(), KeEnableInterrupts(), KiAcquireSpinLock(), KiReleaseSpinLock(), NULL, RemoveEntryList(), and TRUE.
Referenced by ExTimerRundown(), KiCalibrateTimeAdjustment(), NtCancelTimer(), and NtSetTimer().
NTKERNELAPI BOOLEAN KeRemoveSystemServiceTable (IN ULONG Index)
Definition at line 807 of file miscc.c.
References _KSERVICE_TABLE_DESCRIPTOR::Base, _KSERVICE_TABLE_DESCRIPTOR::Count, FALSE, Index, KeServiceDescriptorTable, KeServiceDescriptorTableShadow, _KSERVICE_TABLE_DESCRIPTOR::Limit, NULL, _KSERVICE_TABLE_DESCRIPTOR::Number, NUMBER_SERVICE_TABLES, PAGED_CODE, TRUE, and WIN32K_SERVICE_INDEX.
NTKERNELAPI LONG KeResetEvent (__inout PRKEVENT Event)
Definition at line 283 of file eventobj.c.
References ASSERT, ASSERT_EVENT, DISPATCH_LEVEL, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), and ReadForWriteAccess.
Referenced by IopSendMessageToTrackService(), IoSetPartitionInformation(), NtReplyWaitReceivePortEx(), NtResetEvent(), RawQueryFsSizeInfo(), WmipFlushLogger(), WmipFreeLoggerContext(), WmipStartLogger(), WmiStopTrace(), and WmiUpdateTrace().
ULONG KeResumeThread (__inout PKTHREAD Thread)
Definition at line 1245 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, and RESUME_INCREMENT.
Referenced by PspCreateThread(), PsResumeProcess(), and PsResumeThread().
NTKERNELAPI VOID KeRevertToUserAffinityThread (VOID)
Definition at line 1318 of file thredobj.c.
References _KTHREAD::Affinity, ASSERT, DISPATCH_LEVEL, FALSE, _KTHREAD::IdealProcessor, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KiAcquirePrcbLock(), KiLockDispatcherDatabase, KiReleasePrcbLock(), KiSelectNextThread(), KiUnlockDispatcherDatabase(), _KPRCB::NextThread, NULL, _KPRCB::SetMember, Standby, _KTHREAD::State, _KTHREAD::SystemAffinityActive, _KTHREAD::UserAffinity, and _KTHREAD::UserIdealProcessor.
Referenced by CmpConfigureProcessors(), ExAllocateCacheAwarePushLock(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), Ke386CallBios(), KeConnectInterrupt(), KeDeregisterNmiCallback(), KeDisconnectInterrupt(), KeFlushQueuedDpcs(), KeGenericCallDpc(), KeSetSystemTime(), KeSetup80387OrEmulate(), KiInitMachineDependent(), MiZeroPageWorker(), and WmiStopContextSwapTrace().
NTKERNELAPI PLIST_ENTRY KeRundownQueue (__inout PRKQUEUE Queue)
Definition at line 567 of file queueobj.c.
References ASSERT, ASSERT_QUEUE, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, IsListEmpty, KeGetCurrentIrql(), KiExitDispatcher(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KTHREAD::Queue, and RemoveEntryList().
Referenced by IopDeleteIoCompletion().
VOID KeRundownThread (VOID)
Definition at line 1400 of file thredobj.c.
References _KMUTANT::Abandoned, _KMUTANT::ApcDisable, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, _KMUTANT::Header, IsListEmpty, KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), MUTANT_INCREMENT, _KMUTANT::MutantListEntry, _KTHREAD::MutantListHead, NULL, _KMUTANT::OwnerThread, RemoveEntryList(), _DISPATCHER_HEADER::SignalState, THREAD_TERMINATE_HELD_MUTEX, TRUE, and _DISPATCHER_HEADER::WaitListHead.
Referenced by PspExitThread().
NTKERNELAPI VOID __cdecl KeSaveStateForHibernate (__out PKPROCESSOR_STATE ProcessorState)
Definition at line 99 of file misc.c.
References KiSaveProcessorControlState(), and RtlCaptureContext().
KAFFINITY KeSetAffinityProcess (__inout PKPROCESS Process, __in KAFFINITY Affinity)
Definition at line 1055 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeActiveProcessors, KeGetCurrentIrql(), KeNodeBlock, KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiSetAffinityThread(), KiSetIdealNodeProcess(), KiUnlockDispatcherDatabaseFromSynchLevel, and _KLOCK_QUEUE_HANDLE::OldIrql.
Referenced by NtSetInformationProcess(), Phase1InitializationDiscard(), and PspApplyJobLimitsToProcess().
KAFFINITY KeSetAffinityThread (__inout PKTHREAD Thread, __in KAFFINITY Affinity)
Definition at line 1482 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiSetAffinityThread(), and KiUnlockDispatcherDatabase().
Referenced by NtSetInformationThread().
LOGICAL KeSetAutoAlignmentProcess (__inout PKPROCESS Process, __in LOGICAL Enable)
Definition at line 1428 of file procobj.c.
References ASSERT_PROCESS, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KPROCESS_AUTO_ALIGNMENT_BIT.
Referenced by NtSetInformationProcess().
LOGICAL KeSetAutoAlignmentThread (__inout PKTHREAD Thread, __in LOGICAL Enable)
Definition at line 1785 of file thredobj.c.
References ASSERT_THREAD, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KTHREAD_AUTO_ALIGNMENT_BIT.
Referenced by NtSetInformationThread().
NTKERNELAPI LONG KeSetBasePriorityThread (__inout PKTHREAD Thread, __in LONG Increment)
Definition at line 1642 of file thredobj.c.
References abs(), ASSERT, ASSERT_THREAD, _KPROCESS::BasePriority, DISPATCH_LEVEL, FALSE, HIGH_PRIORITY, KeGetCurrentIrql(), KiAcquireThreadLock(), KiComputeNewPriority(), KiLockDispatcherDatabase, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabase(), LOW_PRIORITY, and LOW_REALTIME_PRIORITY.
Referenced by ExpCreateWorkerThread(), ExpWorkerThreadBalanceManager(), NtSetInformationThread(), and WmipLogger().
LOGICAL KeSetDisableBoostProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
Definition at line 1474 of file procobj.c.
References ASSERT_PROCESS, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KPROCESS_DISABLE_BOOST_BIT.
Referenced by NtSetInformationProcess().
LOGICAL KeSetDisableBoostThread (__inout PKTHREAD Thread, __in LOGICAL Disable)
Definition at line 1831 of file thredobj.c.
References ASSERT_THREAD, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KTHREAD_DISABLE_BOOST_BIT.
Referenced by NtSetInformationProcess(), and NtSetInformationThread().
LOGICAL KeSetDisableQuantumProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
Definition at line 1520 of file procobj.c.
References ASSERT_PROCESS, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KPROCESS_DISABLE_QUANTUM_BIT.
Referenced by PspApplyJobLimitsToProcess().
NTKERNELAPI VOID KeSetDmaIoCoherency (IN ULONG Attributes)
Definition at line 156 of file miscc.c.
References KiDmaIoCoherency.
NTKERNELAPI LONG KeSetEvent (__inout PRKEVENT Event, __in KPRIORITY Increment, __in BOOLEAN Wait)
Definition at line 341 of file eventobj.c.
References ASSERT, ASSERT_EVENT, DISPATCH_LEVEL, EventNotificationObject, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), ReadForWriteAccess, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by CcCancelMmWaitForUninitializeCacheMap(), CcDeleteSharedCacheMap(), CcFreeVirtualAddress(), CcGetVacbMiss(), CcInitializeCacheMap(), CcPostDeferredWrites(), CcUninitializeCacheMap(), CcWorkerThread(), CmNotifyRunDown(), CmpLoadHiveThread(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), CmUnloadKey(), DbgkpCloseObject(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), DbgkpWakeTarget(), ExfReleaseRundownProtection(), ExNotifyCallback(), ExpSetSwappingKernelApc(), ExpShutdownWorker(), ExQueueWorkItem(), ExReleaseRundownProtectionEx(), FsFilterFreeCompletionStack(), FsRtlCompletionRoutinePriv(), FsRtlStackOverflowRead(), IopAcquireFileObjectLock(), IopCompleteRequest(), IopConnectLinkTrackingPort(), IopfCompleteRequest(), IopFreeReserveIrp(), IopInvalidateVolumesForDevice(), IopLoadUnloadDriver(), IopMountVolume(), IopSendMessageToTrackService(), IopTrackLink(), IopXxxControlFile(), IoVerifyVolume(), KiQuantumEnd(), KiSetServerWaitClientEvent(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiAllocatePoolPages(), MiCcPutPagesInTransition(), MiCheckControlArea(), MiDereferenceSegmentThread(), MiDispatchFault(), MiFindContiguousMemoryInPool(), MiFlushAllPages(), MiFlushComplete(), MiFreePoolPages(), MiGatherMappedPages(), MiGatherPagefilePages(), MiInitializePoolEvents(), MiInsertPageFileInList(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiModifiedPageWriterTimerDispatch(), MiNotifyMemoryEvents(), MiObtainFreePages(), MiProcessWorkingSets(), MiQueueWorkingSetRequest(), MiRemovePageByColor(), MiRemovePageFromList(), MiRemoveUnusedSegments(), MiSegmentDelete(), MiShutdownSystem(), MiTrimAllSystemPageableMemory(), MiTrimSegmentCache(), MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MiUpdateModifiedWriterMdls(), MiWriteComplete(), MiZeroAllPageFiles(), MiZeroAwePageWorker(), MiZeroPageFile(), MmCopyToCachedPage(), MmCreateSection(), MmDetachSession(), MmIsMemoryAvailable(), MmResourcesAvailable(), MmWorkingSetManager(), NtDebugContinue(), NtLockFile(), NtReadFile(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetEvent(), NtSignalAndWaitForSingleObject(), NtWriteFile(), PspGetSetContextSpecialApc(), PspTerminateAllProcessesInJob(), SepDequeueWorkItem(), WmipDecrementIrpCount(), WmipFreeLoggerContext(), WmipLogger(), WmipQueueNotification(), WmipReleaseCollectionEnabled(), WmipRequestLogFile(), and WmipWmiIrpCompletion().
VOID KeSetEventBoostPriority (__inout PRKEVENT Event, __in_opt PRKTHREAD * Thread)
Definition at line 443 of file eventobj.c.
References AdjustBoost, _KTHREAD::AdjustIncrement, _KTHREAD::AdjustReason, ARGUMENT_PRESENT, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, EVENT_INCREMENT, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiComputeNewPriority(), KiLockDispatcherDatabase, KiReadyThread(), KiUnlinkThread(), KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), _KTHREAD::Priority, STATUS_SUCCESS, SynchronizationEvent, _KWAIT_BLOCK::Thread, WaitAll, and _KWAIT_BLOCK::WaitType.
Referenced by ExfUnblockPushLock(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), NtSetEventBoostPriority(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
NTKERNELAPI UCHAR KeSetIdealProcessorThread (__inout PKTHREAD Thread, __in UCHAR Processor)
Definition at line 1877 of file thredobj.c.
References AFFINITY_MASK, ASSERT, FALSE, KeNumberProcessors, KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), and MAXIMUM_PROCESSORS.
Referenced by MiZeroAwePageWorker(), MmZeroPageThread(), and NtSetInformationThread().
FORCEINLINE VOID KeSetImportanceDpc (__inout PRKDPC Dpc, __in KDPC_IMPORTANCE Importance)
Definition at line 1531 of file ke.h.
References ASSERT_DPC.
Referenced by KiInitSpinLocks().
VOID KeSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
Definition at line 223 of file profobj.c.
References HalProfileSourceInterval, HalSetProfileInterval(), HalSetSystemInformation, _HAL_PROFILE_SOURCE_INTERVAL::Interval, KeIpiGenericCall(), KiProfileAlignmentFixupInterval, KiProfileInterval, MINIMUM_PROFILE_INTERVAL, ProfileAlignmentFixup, ProfileTime, and _HAL_PROFILE_SOURCE_INTERVAL::Source.
Referenced by NtSetIntervalProfile(), and PerfInfoProfileInit().
NTKERNELAPI BOOLEAN KeSetKernelStackSwapEnable (__in BOOLEAN Enable)
Definition at line 1947 of file thredobj.c.
References _KTHREAD::EnableStackSwap, and KeGetCurrentThread().
Referenced by ExpSetSwappingKernelApc(), ExpShutdownWorker(), ExpWorkerThread(), and ExSwapinWorkerThreads().
NTSTATUS KeSetPhysicalCacheTypeRange (IN PHYSICAL_ADDRESS PhysicalAddress, IN ULONG NumberOfBytes, IN MEMORY_CACHING_TYPE CacheType)
Definition at line 587 of file mtrr.c.
References ASSERT, _NEW_RANGE::Base, _RANGE_INFO::Capabilities, DBGMSG, _RANGE_INFO::DefaultCachedType, DISPATCH_LEVEL, ExPageLockHandle, FALSE, _MTRR_CAPABILITIES::hw, KeAcquireSpinLock, KeFeatureBits, KeGetCurrentIrql(), KeReleaseSpinLock(), KF_AMDK6MTRR, KiAddRange(), KiAmdK6MtrrSetMemoryType(), KiCompleteEffectiveRangeChange(), KiRangeLock, KiRemoveRange(), KiStartEffectiveRangeChange(), _NEW_RANGE::Limit, memset(), MmCached, MmLockPageableSectionByHandle(), MmNonCached, MmUnlockPageableImageSection(), MmUSWCCached, MmWriteCombined, MTRR_TYPE_MAX, MTRR_TYPE_UC, MTRR_TYPE_USWC, _RANGE_INFO::MtrrWorkaround, NT_SUCCESS, _RANGE_INFO::RangesValid, RtlZeroMemory, _NEW_RANGE::Status, STATUS_INVALID_PARAMETER, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, _NEW_RANGE::Type, and _MTRR_CAPABILITIES::u.
Referenced by __out_bcount().
KPRIORITY KeSetPriorityAndQuantumProcess (__inout PKPROCESS Process, __in KPRIORITY BasePriority, __in SCHAR QuantumReset)
Definition at line 1145 of file procobj.c.
References ASSERT, ASSERT_PROCESS, _KTHREAD::BasePriority, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, HIGH_PRIORITY, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiAcquireThreadLock(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabaseFromSynchLevel, LOW_PRIORITY, LOW_REALTIME_PRIORITY, _KLOCK_QUEUE_HANDLE::OldIrql, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, _KTHREAD::QuantumReset, and _KTHREAD::Saturation.
Referenced by NtSetInformationProcess(), and PsSetProcessPriorityByClass().
NTKERNELAPI KPRIORITY KeSetPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Priority)
Definition at line 1986 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, FALSE, HIGH_PRIORITY, KeGetCurrentIrql(), KeIsExecutingDpc(), KiAcquireThreadLock(), KiLockDispatcherDatabase, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabase(), and LOW_PRIORITY.
Referenced by FsRtlWorkerThread(), KeBalanceSetManager(), KeFlushQueuedDpcs(), KeSwapProcessOrStack(), KiExecuteDpc(), KiInitializeKernel(), MiDereferenceSegmentThread(), MiMappedPageWriter(), MiModifiedPageWriter(), MiZeroAwePageWorker(), MiZeroInParallel(), MiZeroPageWorker(), NtSetInformationThread(), and Phase1InitializationDiscard().
VOID KeSetPriorityZeroPageThread (__in KPRIORITY Priority)
Definition at line 2060 of file thredobj.c.
References ASSERT, _KTHREAD::BasePriority, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KiAcquireThreadLock(), KiLockDispatcherDatabase, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabase(), _KTHREAD::Priority, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, and _KTHREAD::QuantumReset.
Referenced by MmZeroPageThread().
LONG KeSetProcess (__inout PKPROCESS Process, __in KPRIORITY Increment, __in BOOLEAN Wait)
Definition at line 971 of file procobj.c.
References ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTestWithoutSideEffects(), _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by PspExitThread().
NTKERNELAPI VOID KeSetProfileIrql (IN KIRQL ProfileIrql)
Definition at line 189 of file miscc.c.
References ASSERT, HIGH_LEVEL, KiProfileIrql, and PROFILE_LEVEL.
VOID KeSetQuantumProcess (__inout PKPROCESS Process, __in SCHAR QuantumReset)
Definition at line 1369 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), and _KTHREAD::QuantumReset.
Referenced by PsChangeQuantumTable(), and PspApplyJobLimitsToProcess().
NTKERNELAPI VOID KeSetSystemAffinityThread (__in KAFFINITY Affinity)
Definition at line 1536 of file thredobj.c.
References _KTHREAD::Affinity, AFFINITY_MASK, ASSERT, DISPATCH_LEVEL, _KTHREAD::IdealProcessor, KeActiveProcessors, KeFindFirstSetLeftAffinity, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KiAcquirePrcbLock(), KiLockDispatcherDatabase, KiProcessorBlock, KiReleasePrcbLock(), KiSelectNextThread(), KiUnlockDispatcherDatabase(), _KPRCB::NextThread, NULL, _KPRCB::ParentNode, _KNODE::ProcessorMask, _KPRCB::SetMember, Standby, _KTHREAD::State, _KTHREAD::SystemAffinityActive, and TRUE.
Referenced by CmpConfigureProcessors(), ExAllocateCacheAwarePushLock(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), Ke386CallBios(), KeConnectInterrupt(), KeDeregisterNmiCallback(), KeDisconnectInterrupt(), KeFlushQueuedDpcs(), KeGenericCallDpc(), KeSetSystemTime(), KeSetup80387OrEmulate(), KiExecuteDpc(), KiInitMachineDependent(), MiZeroPageWorker(), and WmiStopContextSwapTrace().
VOID KeSetSystemTime (IN PLARGE_INTEGER NewTime, OUT PLARGE_INTEGER OldTime, IN BOOLEAN AdjustInterruptTime, IN PLARGE_INTEGER HalTimeToSet OPTIONAL)
Definition at line 223 of file miscc.c.
References _DISPATCHER_HEADER::Absolute, ARGUMENT_PRESENT, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _KTIMER::DueTime, _KTIMER_TABLE_ENTRY::Entry, ExCmosClockIsSane, FALSE, _LIST_ENTRY::Flink, HalSetRealTimeClock(), _DISPATCHER_HEADER::Hand, _KTIMER::Header, HIGH_LEVEL, Index, InitializeListHead(), InsertTailList(), KeAdjustInterruptTime(), KeBootTime, KeBootTimeBias, KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiAcquireTimerTableLock(), KiComputeTimerTableIndex(), KiInsertTimerTable(), KiLockDispatcherDatabase, KiQuerySystemTime, KiReleaseTimerTableLock(), KiRemoveEntryTimer(), KiTimerListExpire(), KiTimerTableListHead, KiUnlockDispatcherDatabase(), _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, RemoveEntryList(), RtlTimeToTimeFields(), SharedUserData, TIMER_TABLE_SIZE, _KTIMER::TimerListEntry, and TRUE.
Referenced by KeLoopTbFlushTimeStampUnlocked(), and Phase1InitializationDiscard().
FORCEINLINE VOID KeSetTargetProcessorDpc (__inout PRKDPC Dpc, __in CCHAR Number)
Definition at line 1568 of file ke.h.
References ASSERT_DPC, and MAXIMUM_PROCESSORS.
Referenced by KiInitSpinLocks(), and KiInitSystem().
NTKERNELAPI VOID KeSetTimeIncrement (IN ULONG MaximumIncrement, IN ULONG MimimumIncrement)
Definition at line 685 of file miscc.c.
References KeMaximumIncrement, KeMinimumIncrement, KeTimeAdjustment, KeTimeIncrement, KiProcessorBlock, KiTickOffset, and max.
NTKERNELAPI BOOLEAN KeSetTimer (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in_opt PKDPC Dpc)
Definition at line 243 of file timerobj.c.
References KeSetTimerEx().
Referenced by CcScheduleLazyWriteScan(), CcSetActiveVacb(), CmpArmDelayedCloseTimer(), CmpCmdInit(), CmpDelayDerefKeyControlBlock(), CmpLazyFlush(), ExpWorkerThreadBalanceManager(), InitializePool(), IopErrorLogQueueRequest(), PspInitializeJobStructuresPhase1(), PspJobTimeLimitsWork(), WmipIsWbemRunningWorker(), and WmipSetupWaitForWbem().
NTKERNELAPI BOOLEAN KeSetTimerEx (__inout PKTIMER Timer, __in LARGE_INTEGER DueTime, __in LONG Period, __in_opt PKDPC Dpc)
Definition at line 285 of file timerobj.c.
References ASSERT, ASSERT_TIMER, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KiComputeDueTime(), KiExitDispatcher(), KiInsertOrSignalTimer(), KiLockDispatcherDatabase, KiRemoveTreeTimer(), KiRequestSoftwareInterrupt, KiSignalTimer(), KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
Referenced by IoInitSystem(), IopInitializeIrpStackProfiler(), KeBalanceSetManager(), KeSetTimer(), KiInitializeInterruptTimers(), MiInsertPageInList(), MiModifiedPageWriterWorker(), NtSetTimer(), WmipPollingDpcRoutine(), and WmipRegisterMcaHandler().
VOID KeSignalCallDpcDone (__in PVOID SystemArgument1)
Definition at line 826 of file dpcobj.c.
References InterlockedDecrement.
Referenced by ExpGetPoolTagInfoTarget(), Ki386FlushTargetDescriptors(), Ki386LoadTargetLdtr(), KiLoadIopmOffset(), and KiSetIoMap().
LOGICAL KeSignalCallDpcSynchronize (__in PVOID SystemArgument2)
Definition at line 857 of file dpcobj.c.
References _DEFERRED_REVERSE_BARRIER::Barrier, DEFERRED_REVERSE_BARRIER_SYNCHRONIZED, FALSE, InterlockedDecrement, InterlockedExchange(), InterlockedIncrement, KeYieldProcessor, _DEFERRED_REVERSE_BARRIER::TotalProcessors, TRUE, and UNREFERENCED_PARAMETER.
Referenced by ExpGetPoolTagInfoTarget(), Ki386FlushTargetDescriptors(), and Ki386LoadTargetLdtr().
VOID FASTCALL KeSignalGateBoostPriority (__inout PKGATE Gate)
Definition at line 59 of file gateobj.c.
References AdjustBoost, _KTHREAD::AdjustIncrement, _KTHREAD::AdjustReason, ASSERT, ASSERT_GATE, _KTHREAD::BasePriority, CLOCK_QUANTUM_DECREMENT, CONTAINING_RECORD, _KQUEUE::CurrentCount, _KTHREAD::DeferredProcessor, DeferredReady, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiAcquireKobjectLock(), KiDeferredReadyThread(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseKobjectLock(), KiReleaseThreadLock(), KiTryToAcquireThreadLock(), KiUnlockDispatcherDatabaseFromSynchLevel, LOW_REALTIME_PRIORITY, NULL, _KPRCB::Number, Priority, _KTHREAD::Priority, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, _KTHREAD::Queue, RemoveEntryList(), _KTHREAD::State, STATUS_SUCCESS, _KWAIT_BLOCK::Thread, TRUE, and _KTHREAD::WaitStatus.
Referenced by ExfWakePushLock(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
NTKERNELAPI VOID KeStackAttachProcess (__inout PRKPROCESS PROCESS, __out PRKAPC_STATE ApcState)
Definition at line 393 of file procobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, INVALID_PROCESS_ATTACH_ATTEMPT, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KiAttachProcess(), KiLockDispatcherDatabaseAtSynchLevel, NULL, _KAPC_STATE::Process, and _KTHREAD::SavedApcState.
Referenced by DbgkpMarkProcessPeb(), DbgkpPostFakeProcessCreateMessages(), ExpDebuggerWorker(), MiCloneProcessAddressSpace(), MiDoMappedCopy(), MiDoPoolCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiLoadImageSection(), MiUnmapViewOfSection(), MmAssignProcessToJob(), MmAttachSession(), MmCheckSystemImage(), MmEnforceWorkingSetLimit(), MmFlushVirtualMemory(), MmMapViewOfSection(), MmProbeAndLockProcessPages(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushInstructionCache(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtProtectVirtualMemory(), NtQueryInformationProcess(), NtQueryVirtualMemory(), NtResetWriteWatch(), NtSetInformationJobObject(), NtSetInformationThread(), NtUnlockVirtualMemory(), ObClearProcessHandleTable(), ObDuplicateObject(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObSetHandleAttributes(), PspAddProcessToJob(), PspProcessDelete(), PspQueryQuotaLimits(), PspSetQuotaLimits(), PspWriteTebImpersonationInfo(), and SepCleanupLUIDDeviceMapDirectory().
VOID KeStartAllProcessors (VOID)
Definition at line 82 of file allproc.c.
References AFFINITY_MASK, ASSERT, _DESCRIPTOR::Base, _KPROCESSOR_STATE::ContextFrame, _KSPECIAL_REGISTERS::Cr0, _KSPECIAL_REGISTERS::Cr3, _KSPECIAL_REGISTERS::Cr4, DOUBLE_FAULT_STACK_SIZE, _CONTEXT::EFlags, ExAllocatePoolWithTag, ExCreatePoolTagTable(), ExDeletePoolTagTable(), FALSE, FIELD_OFFSET, _KSPECIAL_REGISTERS::Gdtr, HalStartNextProcessor(), _KSPECIAL_REGISTERS::Idtr, Index, IPI_FLUSH_SINGLE, KcStartContinue, KeActiveProcessors, KeAdjustInterruptTime(), KeBugCheckEx(), KeFeatureBits, KeGetCurrentPrcb(), KeGetPcr(), KeLoaderBlock, KeLowerIrql, KeNodeBlock, KeNumberNodes, KeNumberProcessors, KeNumprocSpecified, KeRaiseIrqlToSynchLevel(), KeRegisteredProcessors, _LOADER_PARAMETER_BLOCK::KernelStack, KeYieldProcessor, KF_WORKING_PTE, KiAllProcessorsStarted(), KiBarrierWait, KiCopyDescriptorMemory(), KiInitProcessor(), KiIpiSendRequest(), KiLogicalProcessors, KiNode0, KiNodeInit, KiPrefetchRetry, KiProcessorBlock, KiProcessorStartControl, KiQueryProcessorNode, KiSetDescriptorBase(), KiSystemStartup(), _DESCRIPTOR::Limit, _LOADER_PARAMETER_BLOCK::LoadOptions, MAXIMUM_CCNUMA_NODES, MAXIMUM_PROCESSORS, _KPRCB::MHz, MmAllocateIndependentPages(), MmCreateKernelStack(), MmDeleteKernelStack(), MmFreeIndependentPages(), MmSecondaryColorMask, _KPRCB::NodeColor, _KPRCB::NodeShiftedColor, NonPagedPool, NT_SUCCESS, NULL, _KPRCB::Number, _KPRCB::ParentNode, PHASE1_INITIALIZATION_FAILED, _LOADER_PARAMETER_BLOCK::Prcb, _KPCR::Prcb, _KPRCB::ProcessorState, ROUNDUP16, ROUNDUP64, RPL_MASK, RtlZeroMemory, _KPRCB::SecondaryColorMask, _CONTEXT::SegCs, _CONTEXT::SegDs, _CONTEXT::SegEs, _CONTEXT::SegFs, _CONTEXT::SegGs, _CONTEXT::SegSs, _KPROCESSOR_STATE::SpecialRegisters, Status, strstr(), _LOADER_PARAMETER_BLOCK::Thread, and _KSPECIAL_REGISTERS::Tr.
Referenced by Phase1InitializationDiscard().
BOOLEAN KeStartProfile (__inout PKPROFILE Profile, __out_opt PULONG Buffer)
Definition at line 291 of file profobj.c.
References _KACTIVE_PROFILE_SOURCE::Affinity, ASSERT, ASSERT_PROFILE, CONTAINING_RECORD, DISPATCH_LEVEL, ExAllocatePoolWithTag, ExFreePool(), FALSE, _LIST_ENTRY::Flink, HalStartProfileInterrupt(), InitializeListHead(), InsertHeadList(), InsertTailList(), KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KeNumberProcessors, KeReleaseSpinLockFromDpcLevel(), KfRaiseIrql(), KiEnableAlignmentExceptions, KiIpiSendPacket(), KiIpiStallOnPacketTargetsPrcb(), KiProfileAlignmentFixup, KiProfileIrql, KiProfileListHead, KiProfileLock, KiProfileSourceListHead, KiStartProfileInterrupt(), _KACTIVE_PROFILE_SOURCE::ListEntry, NonPagedPool, NULL, _KACTIVE_PROFILE_SOURCE::ProcessorCount, ProfileAlignmentFixup, _KPROCESS::ProfileListHead, RtlZeroMemory, _KPRCB::SetMember, _KACTIVE_PROFILE_SOURCE::Source, and TRUE.
Referenced by NtStartProfile(), and PerfInfoProfileInit().
VOID KeStartThread (__inout PKTHREAD Thread)
Definition at line 297 of file thredobj.c.
References _KPROCESS::Affinity, AFFINITY_MASK, ASSERT, _KPROCESS::BasePriority, _KPROCESS::DisableBoost, FALSE, _KPROCESS::IdealNode, InsertTailList(), _KPROCESS::Iopl, IsListEmpty, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeFindNextRightSetAffinity(), KeNodeBlock, KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiInitialProcess, KiLockDispatcherDatabaseAtSynchLevel, KiProcessListHead, KiProcessListLock, KiProcessorBlock, KiUnlockDispatcherDatabaseFromSynchLevel, MAXULONG_PTR, _KPRCB::MultiThreadProcessorSet, _EPROCESS::Pcb, _KPROCESS::ProcessListEntry, _KPROCESS::ProcessLock, _KPROCESS::QuantumReset, _KPROCESS::StackCount, _KPROCESS::ThreadListHead, _KPROCESS::ThreadSeed, and TRUE.
Referenced by KeInitializeThread(), and PspCreateThread().
BOOLEAN KeStopProfile (__inout PKPROFILE Profile)
Definition at line 531 of file profobj.c.
References _KACTIVE_PROFILE_SOURCE::Affinity, ASSERT, ASSERT_PROFILE, CONTAINING_RECORD, DISPATCH_LEVEL, ExFreePool(), FALSE, _LIST_ENTRY::Flink, HalStopProfileInterrupt(), IsListEmpty, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KeReleaseSpinLockFromDpcLevel(), KfRaiseIrql(), KiDisableAlignmentExceptions, KiIpiSendPacket(), KiIpiStallOnPacketTargetsPrcb(), KiProfileAlignmentFixup, KiProfileIrql, KiProfileLock, KiProfileSourceListHead, KiStopProfileInterrupt(), _KACTIVE_PROFILE_SOURCE::ListEntry, NULL, _KACTIVE_PROFILE_SOURCE::ProcessorCount, ProfileAlignmentFixup, RemoveEntryList(), _KPRCB::SetMember, _KACTIVE_PROFILE_SOURCE::Source, and TRUE.
Referenced by ExpProfileDelete(), NtStopProfile(), and PerfInfoProfileUninit().
ULONG KeSuspendThread (__inout PKTHREAD Thread)
Definition at line 2129 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, ExRaiseStatus(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiInsertQueueApc(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, MAXIMUM_SUSPEND_COUNT, _KLOCK_QUEUE_HANDLE::OldIrql, RESUME_INCREMENT, STATUS_SUSPEND_COUNT_EXCEEDED, and TRUE.
Referenced by PspCreateThread(), and PsSuspendThread().
VOID KeSwapProcessOrStack (IN PVOID Context)
Definition at line 329 of file balmgr.c.
References Executive, FALSE, InterlockedCompareExchange(), InterlockedFlushSingleList(), KeGetCurrentThread(), KernelMode, KeSetPriorityThread(), KeWaitForSingleObject(), KiInSwapKernelStacks(), KiInSwapProcesses(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), KiProcessInSwapListHead, KiProcessOutSwapListHead, KiStackInSwapListHead, KiStackOutSwapRequest, KiSwapEvent, KiSwappingThread, LOW_REALTIME_PRIORITY, NULL, TRUE, and UNREFERENCED_PARAMETER.
Referenced by MmInitSystem().
KCONTINUE_STATUS KeSwitchFrozenProcessor (IN ULONG ProcessorNumber)
Definition at line 386 of file debug.c.
References ContinueError, ContinueNextProcessor, ContinueProcessorReselected, FREEZE_ACTIVE, FREEZE_OWNER, FrozenState, _KPRCB::IpiFrozen, KeGetCurrentPrcb(), KeNumberProcessors, KeYieldProcessor, KiProcessorBlock, TARGET_FROZEN, and UNREFERENCED_PARAMETER.
PVOID KeSwitchKernelStack (IN PVOID StackBase, IN PVOID StackLimit)
Referenced by PsConvertToGuiThread().
NTKERNELAPI BOOLEAN KeSynchronizeExecution (__inout PKINTERRUPT Interrupt, __in PKSYNCHRONIZE_ROUTINE SynchronizeRoutine, __in_opt PVOID SynchronizeContext)
NTKERNELAPI VOID KeTerminateThread (__in KPRIORITY Increment)
Definition at line 2218 of file thredobj.c.
References _KTHREAD::ApcState, ASSERT, _LIST_ENTRY::Blink, DISPATCH_LEVEL, ExWorkerQueue, FALSE, _LIST_ENTRY::Flink, HyperCriticalWorkQueue, InterlockedPushEntrySingleList(), IsListEmpty, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeCheckIfStackExpandCalloutActive(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KPROCESS::KernelTime, _KTHREAD::KernelTime, KiActivateWaiterQueue(), KiInsertQueue(), KiLockDispatcherDatabaseAtSynchLevel, KiProcessListLock, KiProcessOutSwapListHead, KiRundownThread, KiSetContextSwapBusy(), KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTestWithoutSideEffects(), _WORK_QUEUE_ITEM::List, NULL, _KAPC_STATE::Process, ProcessInMemory, _KPROCESS::ProcessListEntry, _KPROCESS::ProcessLock, ProcessOutTransition, PsReaperListHead, PsReaperWorkItem, RemoveEntryList(), _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, Terminated, _ETHREAD::ThreadListEntry, _KTHREAD::ThreadListEntry, _KPROCESS::ThreadListHead, TRUE, _KPROCESS::UserTime, and _KTHREAD::UserTime.
Referenced by PspExitThread().
BOOLEAN KeTestAlertThread (__in KPROCESSOR_MODE)
Definition at line 2415 of file thredobj.c.
References _KTHREAD::Alerted, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, DISPATCH_LEVEL, FALSE, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), TRUE, _KAPC_STATE::UserApcPending, and UserMode.
Referenced by KiContinueEx(), KiDeliverApc(), and NtTestAlert().
FORCEINLINE LOGICAL KeTestForWaitersQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number)
Definition at line 2976 of file ke.h.
References KeGetCurrentPrcb(), _KSPIN_LOCK_QUEUE::Lock, LOCK_QUEUE_OWNER, LOCK_QUEUE_WAIT, and _KPRCB::LockQueue.
NTKERNELAPI BOOLEAN FASTCALL KeTestSpinLock (__in PKSPIN_LOCK SpinLock)
Definition at line 3994 of file amd64.h.
References FALSE, KeMemoryBarrierWithoutFence, KeYieldProcessor, and TRUE.
VOID KeThawAllThreads (VOID)
Definition at line 2482 of file thredobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, _KTHREAD::FreezeCount, _KSEMAPHORE::Header, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveCriticalRegion(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, _KPROCESS::ProcessLock, RESUME_INCREMENT, _DISPATCHER_HEADER::SignalState, _KTHREAD::SuspendCount, _KTHREAD::SuspendSemaphore, and _KPROCESS::ThreadListHead.
Referenced by DbgkpResumeProcess().
VOID KeThawExecution (IN BOOLEAN Enable)
Definition at line 448 of file debug.c.
References Flag, FREEZE_BACKUP, KeEnableInterrupts(), KeFlushCurrentTb(), KeLowerIrql, KeSweepCurrentDcache, KeSweepCurrentIcache, KiFreezeExecutionLock, KiFreezeFlag, KiFreezeLockBackup, KiOldIrql, KiReleaseSpinLock(), KiSendThawExecution(), and TRUE.
_DECL_HAL_KE_IMPORT LOGICAL FASTCALL KeTryToAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
Definition at line 405 of file queuelock.c.
References DISPATCH_LEVEL, FALSE, KeLowerIrql, KfRaiseIrql(), KiGetLockQueue(), KxTryToAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, and TRUE.
LOGICAL FASTCALL KeTryToAcquireQueuedSpinLockAtRaisedIrql (__inout PKSPIN_LOCK_QUEUE QueuedLock)
Definition at line 506 of file queuelock.c.
References KxTryToAcquireQueuedSpinLock().
Referenced by KiInitializeKernel().
_DECL_HAL_KE_IMPORT LOGICAL FASTCALL KeTryToAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
Definition at line 455 of file queuelock.c.
References FALSE, KeLowerIrql, KfRaiseIrql(), KiGetLockQueue(), KxTryToAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, SYNCH_LEVEL, and TRUE.
BOOLEAN KeTryToAcquireSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKIRQL OldIrql)
Definition at line 4031 of file amd64.h.
References DISPATCH_LEVEL, FALSE, KeLowerIrql, KfRaiseIrql(), KxTryToAcquireSpinLock(), and TRUE.
Referenced by MiTrimAllSystemPageableMemory().
NTKERNELAPI BOOLEAN FASTCALL KeTryToAcquireSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock)
Definition at line 4076 of file amd64.h.
References KxTryToAcquireSpinLock().
Referenced by KeFreezeExecution().
VOID KeUninitThread (__inout PKTHREAD Thread)
Definition at line 269 of file thredobj.c.
References FALSE, MmDeleteKernelStack(), and NULL.
Referenced by PspCreateThread().
NTKERNELAPI VOID KeUnstackDetachProcess (__in PRKAPC_STATE ApcState)
Definition at line 632 of file procobj.c.
References APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, _KTHREAD::ApcStatePointer, ASSERT, DISPATCH_LEVEL, FALSE, InterlockedPushEntrySingleList(), INVALID_PROCESS_DETACH_ATTEMPT, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheck(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiMoveApcState(), KiProcessOutSwapListHead, KiRequestSoftwareInterrupt, KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapProcess(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, ProcessInMemory, ProcessOutTransition, _KTHREAD::SavedApcState, _KTHREAD::SpecialApcDisable, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, _KPROCESS::ThreadListHead, TRUE, and UserMode.
Referenced by DbgkpMarkProcessPeb(), DbgkpPostFakeProcessCreateMessages(), ExpDebuggerWorker(), MiCloneProcessAddressSpace(), MiDoMappedCopy(), MiDoPoolCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiLoadImageSection(), MiUnmapViewOfSection(), MmAssignProcessToJob(), MmCheckSystemImage(), MmDetachSession(), MmEnforceWorkingSetLimit(), MmFlushVirtualMemory(), MmMapViewOfSection(), MmProbeAndLockProcessPages(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushInstructionCache(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtProtectVirtualMemory(), NtQueryInformationProcess(), NtQueryVirtualMemory(), NtResetWriteWatch(), NtSetInformationJobObject(), NtSetInformationThread(), NtUnlockVirtualMemory(), ObClearProcessHandleTable(), ObDuplicateObject(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObSetHandleAttributes(), PspAddProcessToJob(), PspProcessDelete(), PspQueryQuotaLimits(), PspSetQuotaLimits(), PspWriteTebImpersonationInfo(), and SepCleanupLUIDDeviceMapDirectory().
NTKERNELAPI NTSTATUS KeUserModeCallback (IN ULONG ApiNumber, IN PVOID InputBuffer, IN ULONG InputLength, OUT PVOID * OutputBuffer, OUT PULONG OutputLength)
NTSTATUS KevUtilAddressToFileHeader (IN PVOID Address, OUT UINT_PTR * OffsetIntoImage, OUT PUNICODE_STRING * DriverName, OUT BOOLEAN * InVerifierList)
Definition at line 24 of file kevutil.c.
References _LDR_DATA_TABLE_ENTRY::BaseDllName, CONTAINING_RECORD, _LDR_DATA_TABLE_ENTRY::DllBase, FALSE, _LDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, LDRP_IMAGE_VERIFYING, NULL, PsLoadedModuleList, _LDR_DATA_TABLE_ENTRY::SizeOfImage, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
FORCEINLINE VOID KeWaitForContextSwap (__in PKTHREAD Thread)
Definition at line 2831 of file ke.h.
References FALSE, KeYieldProcessor, and UNREFERENCED_PARAMETER.
Referenced by KiOutSwapKernelStacks(), and PspReaper().
VOID FASTCALL KeWaitForGate (__inout PKGATE Gate, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode)
Definition at line 204 of file gateobj.c.
References APC_LEVEL, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, ASSERT_GATE, DISPATCH_LEVEL, _KTHREAD::GateObject, GateWait, InsertTailList(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KAPC_STATE::KernelApcPending, KiAcquireKobjectLock(), KiAcquireThreadLock(), KiActivateWaiterQueue(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseKobjectLock(), KiReleaseThreadLock(), KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KWAIT_BLOCK::Object, _KLOCK_QUEUE_HANDLE::OldIrql, _KTHREAD::Queue, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_SUCCESS, _KWAIT_BLOCK::Thread, TRUE, _KTHREAD::WaitBlock, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitMode, and _KTHREAD::WaitReason.
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), KiAcquireFastMutex(), and KiAcquireGuardedMutex().
NTKERNELAPI NTSTATUS KeWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) PVOID Object[], __in WAIT_TYPE WaitType, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout, __out_opt PKWAIT_BLOCK WaitBlockArray)
Definition at line 548 of file wait.c.
References APC_LEVEL, _KTHREAD::ApcState, ARGUMENT_PRESENT, ASSERT, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, _KMUTANT::Header, Index, InitializeWaitMultiple, InsertTailList(), KeBugCheck(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KiActivateWaiterQueue(), KiAdjustQuantumThread(), KiCheckDueTime(), KiComputeWaitInterval(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabase(), KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitSatisfyAny, KiWaitSatisfyMutant, KiWaitSatisfyOther, MAXIMUM_WAIT_OBJECTS, MAXIMUM_WAIT_OBJECTS_EXCEEDED, MINLONG, MutantObject, _KWAIT_BLOCK::NextWaitBlock, NULL, _KWAIT_BLOCK::Object, _KMUTANT::OwnerThread, _KTHREAD::Preempted, _KTHREAD::Queue, QueueObject, ReadForWriteAccess, _DISPATCHER_HEADER::SignalState, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_TIMEOUT, TestForAlertPending, THREAD_WAIT_OBJECTS, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, _DISPATCHER_HEADER::Type, WaitAny, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitListEntry, _DISPATCHER_HEADER::WaitListHead, _KPRCB::WaitListHead, _KTHREAD::WaitNext, and _KTHREAD::WaitStatus.
Referenced by CmpFileWrite(), ExpWorkerThreadBalanceManager(), KeBalanceSetManager(), MiDereferenceSegmentThread(), MiFlushSectionInternal(), MiModifiedPageWriterWorker(), MiZeroAllPageFiles(), MiZeroInParallel(), MmZeroPageThread(), ObpWaitForMultipleObjects(), and PsShutdownSystem().
NTKERNELAPI NTSTATUS KeWaitForSingleObject (__in PVOID Object, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 1000 of file wait.c.
References APC_LEVEL, _KTHREAD::ApcState, ARGUMENT_PRESENT, ASSERT, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, _KMUTANT::Header, InitializeWaitSingle, InsertTailList(), KeBalanceSetManager(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KiActivateWaiterQueue(), KiAdjustQuantumThread(), KiCheckDueTime(), KiComputeWaitInterval(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabase(), KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitSatisfyMutant, KiWaitSatisfyOther, MINLONG, MutantObject, NULL, _KMUTANT::OwnerThread, _KTHREAD::Preempted, PsGetCurrentThread(), _KTHREAD::Queue, QueueObject, ReadForWriteAccess, _DISPATCHER_HEADER::SignalState, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_TIMEOUT, TestForAlertPending, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, _DISPATCHER_HEADER::Type, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitListEntry, _DISPATCHER_HEADER::WaitListHead, _KPRCB::WaitListHead, _KTHREAD::WaitNext, and _KTHREAD::WaitStatus.
Referenced by CcCanIWrite(), CcInitializeCacheMap(), CcSetValidData(), CcWaitForCurrentLazyWriterActivity(), CcWaitForUninitializeCacheMap(), CcWaitOnActiveCount(), CcZeroData(), CmpFileRead(), CmpInitializeHiveList(), CmpLoadHiveThread(), CmpOpenHiveFiles(), DbgkpQueueMessage(), ExfWaitForRundownProtectionRelease(), ExpShutdownWorker(), ExpShutdownWorkerThreads(), ExpWaitForResource(), ExpWorkerThreadBalanceManager(), ExSwapinWorkerThreads(), ExTimedWaitForUnblockPushLock(), ExUnregisterCallback(), ExWaitForRundownProtectionReleaseCacheAware(), FsFilterAllocateCompletionStack(), FsRtlBalanceReads(), FsRtlDeregisterUncProvider(), FsRtlGetFileSize(), FsRtlpPostStackOverflow(), FsRtlRegisterUncProvider(), FsRtlSetFileSize(), FsRtlWaitOnIrp(), HalExamineMBR(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoCancelFileOpen(), IoGetBootDiskInformation(), IopAcquireFileObjectLock(), IopAllocateReserveIrp(), IopCancelAlertedRequest(), IopCloseFile(), IopCompleteUnloadOrDelete(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopDeleteFile(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopHardErrorThread(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopSendMessageToTrackService(), IopSetRemoteLink(), IopShutdownBaseFileSystems(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IopUnloadDriver(), IoReadPartitionTable(), IoSetInformation(), IoSetPartitionInformation(), IoShutdownSystem(), IoVerifyVolume(), IoVolumeDeviceToDosName(), IoWritePartitionTable(), KeSwapProcessOrStack(), KiAcquireFastMutex(), KiExecuteDpc(), KiSetServerWaitClientEvent(), KiSuspendThread(), LpcpRequestWaitReplyPort(), MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), MiCleanSection(), MiCreateImageFileMap(), MiDereferenceSessionFinal(), MiEnablePagingTheExecutive(), MiEnsureAvailablePageOrWait(), MiFindInitializationCode(), MiFlushSectionInternal(), MiIssuePageExtendRequest(), MiMakeOutswappedPageResident(), MiMappedPageWriter(), MiModifiedPageWriterWorker(), MiQueueWorkingSetRequest(), MiShutdownSystem(), MiUnlinkWorkingSet(), MiWaitForInPageComplete(), MiZeroPageFile(), MiZeroPageFileFirstPage(), MmCreateSection(), MmLoadSystemImage(), MmLockPageableSectionByHandle(), MmPurgeSection(), MmUnloadSystemImage(), NtLoadDriver(), NtNotifyChangeMultipleKeys(), NtQueryInformationFile(), NtReleaseKeyedEvent(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetInformationFile(), NtSignalAndWaitForSingleObject(), NtStartProfile(), NtStopProfile(), NtWaitForDebugEvent(), NtWaitForKeyedEvent(), NtWaitForSingleObject(), ObWaitForSingleObject(), PsGetContextThread(), PspExitThread(), PspQueryDescriptorThread(), PspQueryLdtInformation(), PspSetLdtInformation(), PspSetLdtSize(), PspWaitForUsermodeExit(), PsSetContextThread(), PsSetLdtEntries(), PsSetProcessLdtInfo(), PsWaitForAllProcesses(), RawCleanup(), RawClose(), RawCreate(), RawQueryFsSizeInfo(), RawUserFsCtrl(), RawVerifyVolume(), SepRmCommandServerThread(), WmipFlushLogger(), WmipForwardWmiIrp(), WmipFreeLoggerContext(), WmipGetDevicePDO(), WmipLogger(), WmipStartLogger(), WmipWaitForCollectionEnabled(), WmipWaitForIrpCompletion(), WmiStopTrace(), WmiUpdateTrace(), and xHalGetPartialGeometry().
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KfAcquireSpinLock (__inout PKSPIN_LOCK SpinLock)
Referenced by KiInitializeKernel().
_DECL_HAL_KE_IMPORT VOID FASTCALL KfLowerIrql (__in KIRQL NewIrql)
Referenced by KiInitMachineDependent(), and KiTimedChainedDispatch2ndLvl().
_DECL_HAL_KE_IMPORT KIRQL FASTCALL KfRaiseIrql (__in KIRQL NewIrql)
Referenced by KeAcquireInStackQueuedSpinLock(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeAcquireQueuedSpinLock(), KeAcquireQueuedSpinLockRaiseToSynch(), KeAcquireSpinLockRaiseToDpc(), KeAcquireSpinLockRaiseToSynch(), KeContextFromKframes(), KeIpiGenericCall(), KeStartProfile(), KeStopProfile(), KeTryToAcquireQueuedSpinLock(), KeTryToAcquireQueuedSpinLockRaiseToSynch(), KeTryToAcquireSpinLock(), KiAcquireDispatcherLockRaiseToSynch(), KiCheckForKernelApcDelivery(), KiContinue(), KiContinueEx(), KiInitMachineDependent(), KiOpPatchCode(), KiPreprocessInvalidOpcodeFault(), KiStartProfileInterrupt(), KiStopProfileInterrupt(), KiTimedChainedDispatch2ndLvl(), KiTryToAcquireDispatcherLockRaiseToSynch(), xxAcquireFastMutex(), and xxTryToAcquireFastMutex().
_DECL_HAL_KE_IMPORT VOID FASTCALL KfReleaseSpinLock (__inout PKSPIN_LOCK SpinLock, __in KIRQL NewIrql)
FORCEINLINE ULONG KiFindFirstSetLeftMemberInt (__in ULONG Set)
Definition at line 4018 of file ke.h.
Referenced by KeFindFirstSetLeftMember().
BOOLEAN KiIpiServiceRoutine (IN struct _KTRAP_FRAME * TrapFrame, IN struct _KEXCEPTION_FRAME * ExceptionFrame)
Referenced by KeFreezeExecution().
VOID FASTCALL KiSetPriorityThread (__inout PRKTHREAD Thread, __in KPRIORITY Priority)
Definition at line 1431 of file thredsup.c.
References ASSERT, _KPRCB::CurrentThread, DeferredReady, FALSE, HIGH_PRIORITY, KiAcquirePrcbLock(), KiInsertDeferredReadyList(), KiProcessorBlock, KiReleasePrcbLock(), KiRequestDispatchInterrupt, KiSelectReadyThread(), _KPRCB::NextThread, NULL, _KPRCB::Number, PRIORITY_MASK, Ready, _KPRCB::ReadySummary, RemoveEntryList(), Running, Standby, _KTHREAD::State, ThreadPriority, and TRUE.
Referenced by ExpBoostOwnerThread(), KeSetBasePriorityThread(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), and KiBoostPriorityThread().
NTSTATUS KiSetServerWaitClientEvent (__inout PKEVENT SeverEvent, __inout PKEVENT ClientEvent, __in ULONG WaitMode)
Definition at line 1299 of file wait.c.
References EVENT_INCREMENT, FALSE, KeSetEvent(), KeWaitForSingleObject(), NULL, TRUE, and WrEventPair.
VOID KxFlushEntireTb (VOID)
Definition at line 23 of file flushtb.c.
References IPI_FLUSH_ALL, IPI_INSTRUMENT_COUNT, KeActiveProcessors, KeFlushCurrentTb(), KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiClearTbFlushTimeStampBusy(), KiFlushTargetEntireTb(), KiIpiSendPacket(), KiIpiSendRequest(), KiIpiStallOnPacketTargets(), KiIpiWaitForRequestBarrier(), KiSetTbFlushTimeStampBusy(), NULL, _KPRCB::Number, and _KPRCB::SetMember.
Referenced by KeFlushEntireTb().
Variable Documentation
KAFFINITY KeActiveProcessors
Definition at line 76 of file kernldat.c.
Referenced by ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpGetSystemBasicInformation(), IoConnectInterrupt(), KeBugCheck2(), KeDeregisterNmiCallback(), KeFlushMultipleTb(), KeFlushQueuedDpcs(), KeFlushSingleTb(), KeFreezeExecution(), KeI386SetGdtSelector(), KeInitializeProfile(), KeInvalidateAllCaches(), KeIpiGenericCall(), KeQueryActiveProcessors(), KeQueryLogicalProcessorInformation(), KeSetAffinityProcess(), KeSetSystemAffinityThread(), KeSetup80387OrEmulate(), KeStartAllProcessors(), KiAllProcessorsStarted(), KiCompleteEffectiveRangeChange(), KiInitializeBootStructures(), KiInitializePAT(), KiInitMachineDependent(), KiLockStepOtherProcessors(), KiSendThawExecution(), KxFlushEntireTb(), MmCreatePeb(), NtSetInformationJobObject(), NtSetInformationProcess(), Phase1InitializationDiscard(), and PspCreateProcess().
LARGE_INTEGER KeBootTime
Definition at line 82 of file kernldat.c.
Referenced by IopCopyBootLogRegistryToFile(), KeSetSystemTime(), NtQuerySystemInformation(), Phase1InitializationDiscard(), and WmipAddLogHeader().
ULONGLONG KeBootTimeBias
Definition at line 88 of file kernldat.c.
Referenced by KeSetSystemTime(), NtQuerySystemInformation(), and Phase1InitializationDiscard().
BOOLEAN KeBugCheckActive
Definition at line 124 of file bugcheck.c.
Referenced by KeBugCheck2(), KeFreezeExecution(), KeQueryCurrentStackInformation(), KiFreezeTargetExecution(), and KiProcessNMI().
LIST_ENTRY KeBugCheckCallbackListHead
Definition at line 101 of file kernldat.c.
Referenced by KeRegisterBugCheckCallback(), KiInitSystem(), and KiScanBugCheckCallbackList().
KSPIN_LOCK KeBugCheckCallbackLock
Definition at line 109 of file kernldat.c.
Referenced by KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), and KiInitSystem().
LIST_ENTRY KeBugCheckReasonCallbackListHead
Definition at line 102 of file kernldat.c.
Referenced by KeRegisterBugCheckReasonCallback(), KiInitSystem(), and KiInvokeBugCheckEntryCallbacks().
ULONG KeErrorMask
ULONG KeFeatureBits
Definition at line 187 of file kernldat.c.
Referenced by ExpGetSystemEmulationProcessorInformation(), ExpGetSystemProcessorInformation(), KeRestoreMtrr(), KeRestorePAT(), KeSetPhysicalCacheTypeRange(), KeStartAllProcessors(), KiDispatchException(), KiInitializeInterruptTimers(), KiInitializeKernel(), KiInitializeMTRR(), KiInitializePAT(), KiInitMachineDependent(), KiLoadMTRR(), KiRestoreFastSyscallReturnState(), KiSetFeatureBits(), MiCreatePagingFileMap(), MiFindLargePageMemory(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiInsertPageInList(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiMapWithLargePages(), MiUseLargeDriverPage(), MmAccessFault(), MmInitSystem(), NtAllocateVirtualMemory(), and PspLookupKernelUserEntryPoints().
PGDI_BATCHFLUSH_ROUTINE KeGdiFlushUserBatch
Definition at line 116 of file kernldat.c.
Referenced by KeUserModeCallback(), and PsEstablishWin32Callouts().
ULONGLONG KeInterruptTimeBias
Definition at line 94 of file kernldat.c.
Referenced by KiCalibrateTimeAdjustment(), and NtQuerySystemInformation().
ULONG KeLargestCacheLine
Definition at line 297 of file kernldat.c.
Referenced by KeGetRecommendedSharedDataAlignment(), KiGetCacheInformation(), and KiSetCacheInformation().
PLOADER_PARAMETER_BLOCK KeLoaderBlock
Definition at line 123 of file kernldat.c.
Referenced by KeStartAllProcessors(), KiInitializeAbios(), KiInitializeKernel(), KiInitializeMachineType(), KiPcToFileHeader(), and Phase1InitializationDiscard().
ULONG KeMaximumIncrement
Referenced by ExpCopyThreadInfo(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpGetSystemBasicInformation(), ExpInitializeExecutive(), KeQueryTimeIncrement(), KeQueryValuesProcess(), KeSetTimeIncrement(), KeUpdateRunTime(), KiCalibrateTimeAdjustment(), KiInitializeKernel(), NtQueryInformationProcess(), NtQueryInformationThread(), NtQuerySystemInformation(), NtSetInformationJobObject(), NtSetSystemInformation(), PsEnforceExecutionTimeLimits(), PspExitProcess(), and WmipAddLogHeader().
ULONG KeMinimumIncrement
Definition at line 130 of file kernldat.c.
Referenced by KeSetTimeIncrement().
PKNODE KeNodeBlock[]
Definition at line 400 of file kernldat.c.
Referenced by ExpQueryNumaAvailableMemory(), ExpQueryNumaProcessorMap(), KeQueryLogicalProcessorInformation(), KeSetAffinityProcess(), KeStartAllProcessors(), KeStartThread(), KiAllProcessorsStarted(), KiInitializeKernel(), KiSetAffinityThread(), KiSetIdealNodeProcess(), MiComputeInitialLargePage(), MiDeferredUnlockPages(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertZeroListAtBack(), MiRemovePageByColor(), MiZeroInParallel(), MmCreateKernelStack(), MmDeleteKernelStack(), MmInitSystem(), and MmZeroPageThread().
UCHAR KeNumberNodes
Definition at line 383 of file kernldat.c.
Referenced by __bcount(), ExAllocateCacheAwarePushLock(), ExFreePoolWithTag(), ExpQueryNumaAvailableMemory(), ExpQueryNumaProcessorMap(), InitializePool(), KeNumaInitialize(), KeQueryLogicalProcessorInformation(), KeStartAllProcessors(), KiAllProcessorsStarted(), KiIdleSchedule(), KiSetAffinityThread(), KiSetIdealNodeProcess(), KiSwapThread(), MiAllocatePagesForMdl(), MiComputeInitialLargePage(), MiDeferredUnlockPages(), MiFindLargePageMemory(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertZeroListAtBack(), MiRemoveAnyPage(), MiRemovePageByColor(), MiRemoveZeroPage(), MiUnlinkFreeOrZeroedPage(), MiZeroInParallel(), MiZeroPageWorker(), MmAllocateIndependentPages(), MmDeleteKernelStack(), MmInitSystem(), and MmZeroPageThread().
NTSYSAPI CCHAR KeNumberProcessors
Definition at line 146 of file kernldat.c.
Referenced by CcInitializeCacheManager(), CmpConfigureProcessors(), ExAcquireCacheAwarePushLockExclusive(), ExAllocateCacheAwarePushLock(), ExAllocateCacheAwareRundownProtection(), ExFreeCacheAwarePushLock(), ExfReleaseRundownProtection(), ExpCheckForResource(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpGetSystemBasicInformation(), ExpInitializePushLocks(), ExpInitSystemPhase1(), ExpScanSystemLookasideList(), ExReleaseCacheAwarePushLockExclusive(), ExReleaseRundownProtection(), ExReleaseRundownProtectionEx(), ExSizeOfRundownProtectionCacheAware(), IoInitSystem(), KeAdjustInterruptTime(), KeBugCheck2(), KeConnectInterrupt(), KeGenericCallDpc(), KeGetPrcb(), KeI386FlatToGdtSelector(), KeInitializeQueue(), KeInitSystem(), KeIpiGenericCall(), KeQueryPrcbAddress(), KeSetIdealProcessorThread(), KeStartAllProcessors(), KeStartProfile(), KeSwitchFrozenProcessor(), KeUpdateRunTime(), KiAdjustIrpCredits(), KiAdjustSimultaneousMultiThreadingCharacteristics(), KiAllProcessorsStarted(), KiIdleSchedule(), KiInitializeBootStructures(), KiInitializeKernel(), KiInitMachineDependent(), KiLockStepExecution(), KiOpPatchCode(), KiOutSwapKernelStacks(), KiScanReadyQueues(), KiSwapThread(), KiTimerExpiration(), MiChargeCommitment(), MiStartZeroPageWorkers(), MiZeroPageWorker(), MmCreatePeb(), MmVerifyImageIsOkForMpUse(), NtQuerySystemInformation(), ObInitSystem(), WmipAddLogHeader(), WmipAllocateTraceBufferPool(), WmipFlushActiveBuffers(), WmipFreeTraceBufferPool(), WmipInitContext(), WmipStartGlobalLogger(), WmipStartLogger(), and WmiStopContextSwapTrace().
ULONG KeNumprocSpecified
Definition at line 157 of file kernldat.c.
Referenced by KeStartAllProcessors().
UCHAR KeProcessNodeSeed
Definition at line 392 of file kernldat.c.
Referenced by KiSetAffinityThread(), and KiSetIdealNodeProcess().
USHORT KeProcessorArchitecture
Definition at line 166 of file kernldat.c.
Referenced by ExpGetSystemProcessorInformation(), and KiInitializeKernel().
USHORT KeProcessorLevel
Definition at line 173 of file kernldat.c.
Referenced by ExpGetSystemEmulationProcessorInformation(), ExpGetSystemProcessorInformation(), and KiInitializeKernel().
USHORT KeProcessorRevision
Definition at line 180 of file kernldat.c.
Referenced by ExpGetSystemEmulationProcessorInformation(), ExpGetSystemProcessorInformation(), and KiInitializeKernel().
PVOID KeRaiseUserExceptionDispatcher
Definition at line 286 of file kernldat.c.
Referenced by KeRaiseUserException(), and PspLookupKernelUserEntryPoints().
PULONG KeServiceCountTable
KSERVICE_TABLE_DESCRIPTOR KeServiceDescriptorTable[NUMBER_SERVICE_TABLES]
Definition at line 195 of file kernldat.c.
Referenced by ExpInitializeExecutive(), KeAddSystemServiceTable(), KeInitThread(), KeRemoveSystemServiceTable(), KiInitSystem(), and PsConvertToGuiThread().
KSERVICE_TABLE_DESCRIPTOR KeServiceDescriptorTableShadow[NUMBER_SERVICE_TABLES]
Definition at line 196 of file kernldat.c.
Referenced by ExpInitializeExecutive(), KeAddSystemServiceTable(), KeRemoveSystemServiceTable(), KiInitSystem(), NtQuerySystemInformation(), and PsConvertToGuiThread().
ULONG KeThreadDpcEnable
Definition at line 137 of file kernldat.c.
Referenced by KeInitSystem().
KTHREAD_SWITCH_COUNTERS KeThreadSwitchCounters
Definition at line 204 of file kernldat.c.
Referenced by NtQuerySystemInformation().
volatile KSYSTEM_TIME KeTickCount
Referenced by KiCalibrateTimeAdjustment().
ULONG KeTimeAdjustment
Referenced by KeSetTimeIncrement(), NtQuerySystemInformation(), and NtSetSystemInformation().
ULONG KeTimeIncrement
Definition at line 213 of file kernldat.c.
Referenced by KeSetTimeIncrement(), and NtQuerySystemInformation().
ULONG KeTimerCheckFlags
Definition at line 29 of file timerobj.c.
Referenced by KeCheckForTimer().
BOOLEAN KeTimeSynchronization
Definition at line 221 of file kernldat.c.
Referenced by NtQuerySystemInformation(), and NtSetSystemInformation().
PVOID KeUserApcDispatcher
Definition at line 229 of file kernldat.c.
Referenced by KiInitializeUserApc(), and PspLookupKernelUserEntryPoints().
PVOID KeUserCallbackDispatcher
Definition at line 237 of file kernldat.c.
Referenced by PspLookupKernelUserEntryPoints().
PVOID KeUserExceptionDispatcher
Definition at line 245 of file kernldat.c.
Referenced by KiDispatchException(), and PspLookupKernelUserEntryPoints().
PVOID KeUserPopEntrySListEnd
Definition at line 252 of file kernldat.c.
Referenced by KiCheckForSListAddress(), and PspLookupKernelUserEntryPoints().
PVOID KeUserPopEntrySListFault
Definition at line 259 of file kernldat.c.
Referenced by KeInvalidAccessAllowed(), KiOpPreprocessAccessViolation(), and PspLookupKernelUserEntryPoints().
PVOID KeUserPopEntrySListResume
Definition at line 266 of file kernldat.c.
Referenced by KiCheckForSListAddress(), KiOpPreprocessAccessViolation(), and PspLookupKernelUserEntryPoints().
KE_ZERO_PAGE_ROUTINE KeZeroPages
Definition at line 243 of file kernlini.c.
Referenced by MiMapBBTMemory(), MiZeroAwePageWorker(), and MiZeroPageWorker().
KE_ZERO_PAGE_ROUTINE KeZeroPagesFromIdleThread
Definition at line 244 of file kernlini.c.
const ULONG_PTR KiAffinityArray[]
ALIGNED_SPINLOCK KiDispatcherLock
Definition at line 68 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ULONG KiDPCTimeout
Definition at line 318 of file kernldat.c.
Referenced by KeUpdateRunTime().
DECLSPEC_CACHEALIGN DECLSPEC_SELECTANY const CCHAR KiFindFirstSetLeft[256]
Initial value:
= {
        0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7}
Referenced by KiFindFirstSetLeftBit().
DECLSPEC_CACHEALIGN DECLSPEC_SELECTANY const CCHAR KiFindFirstSetRight[256]
Initial value:
= {
        0, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        5, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        6, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        5, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        7, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        5, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        6, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        5, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0,
        4, 0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0}
Referenced by KiFindFirstSetRightBit().
volatile KAFFINITY KiIdleSummary
Referenced by KeInsertQueueDpc(), KiClearIdleSummary(), KiDeferredReadyThread(), KiInitializeKernel(), and KiSetIdleSummary().
const ULONG KiMask32Array
Definition at line 253 of file ke.h.
PKPRCB KiProcessorBlock[]
Definition at line 376 of file kernldat.c.
Referenced by CcInitializeCacheManager(), ExpInitSystemPhase1(), ExpScanSystemLookasideList(), IoInitSystem(), KeBugCheck2(), KeFreezeExecution(), KeGenericCallDpc(), KeGetPrcb(), KeI386SetGdtSelector(), KeInitSystem(), KeInsertQueueDpc(), KeQueryLogicalProcessorInformation(), KeQueryPrcbAddress(), KeSetSystemAffinityThread(), KeSetTimeIncrement(), KeStartAllProcessors(), KeStartThread(), KeSwitchFrozenProcessor(), KiAdjustIrpCredits(), KiAdjustSimultaneousMultiThreadingCharacteristics(), KiAllProcessorsStarted(), KiDeferredReadyThread(), KiIdleSchedule(), KiInitializeBootStructures(), KiInitializeKernel(), KiInitializePcr(), KiIpiProcessRequests(), KiIpiSendRequest(), KiOutSwapKernelStacks(), KiScanReadyQueues(), KiSendFreeze(), KiSendThawExecution(), KiSetAffinityThread(), KiSetPriorityThread(), KiSwapThread(), MiChargeCommitment(), NtQuerySystemInformation(), ObInitSystem(), and PsConvertToGuiThread().
ULONG KiSpinlockTimeout
Definition at line 360 of file kernldat.c.
ULONG KiStackProtectTime
Definition at line 80 of file balmgr.c.
Referenced by KeBalanceSetManager(), and KiOutSwapKernelStacks().
volatile LONG KiTbFlushTimeStamp
Referenced by KeReadTbFlushTimeStamp(), KiClearTbFlushTimeStampBusy(), and KiSetTbFlushTimeStampBusy().