Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hiveload.c File Reference
hiveload.c File Reference
#include "cmp.h"
Typedefs
typedef enum _RESULT RESULT
Enumerations
enum _RESULT {
NotHive, Fail, NoMemory, HiveSuccess,
RecoverHeader, RecoverData, SelfHeal
}
Functions
NTSTATUS HvCloneHive (PHHIVE SourceHive, PHHIVE DestHive, PULONG NewLength)
NTSTATUS HvLoadHive (PHHIVE Hive)
NTSTATUS HvMapHive (PHHIVE Hive)
VOID HvpDelistBinFreeCells (PHHIVE Hive, PHBIN Bin, HSTORAGE_TYPE Type)
RESULT HvpGetHiveHeader (PHHIVE Hive, PHBASE_BLOCK *BaseBlock, PLARGE_INTEGER TimeStamp)
RESULT HvpGetLogHeader (PHHIVE Hive, PHBASE_BLOCK *BaseBlock, PLARGE_INTEGER TimeStamp)
NTSTATUS HvpMapFileImageAndBuildMap (PHHIVE Hive, ULONG Length)
NTSTATUS HvpReadFileImageAndBuildMap (PHHIVE Hive, ULONG Length)
RESULT HvpRecoverData (PHHIVE Hive)
NTSTATUS HvpRecoverWholeHive (PHHIVE Hive, ULONG FileOffset)
NTSTATUS HvShrinkHive (PHHIVE Hive, ULONG NewLength)
Variables
PUCHAR CmpStashBuffer
ULONG CmpStashBufferSize
struct {
PHBIN BinPoint
PHHIVE Hive
HCELL_INDEX MapPoint
ULONG Space
ULONG Status
} HvCheckHiveDebug
struct {
ULONG FailPoint
ULONG FileOffset
PHHIVE Hive
} HvRecoverDataDebug
Typedef Documentation
typedef enum _RESULT RESULT
Enumeration Type Documentation
enum _RESULT
Enumerator
NotHive
Fail
NoMemory
HiveSuccess
RecoverHeader
RecoverData
SelfHeal
Definition at line 31 of file hiveload.c.
Function Documentation
NTSTATUS HvCloneHive (PHHIVE SourceHive, PHHIVE DestHive, PULONG NewLength)
Definition at line 2283 of file hiveload.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmpMapThisBin(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, FileOffset, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HTABLE_SLOTS, HvpAllocateMap(), HvpEnlistBinInMap(), HvpGetCellMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NT_SUCCESS, NULL, _HHIVE::ReadOnly, RtlCopyMemory, RtlZeroMemory, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, _HHIVE::_DUAL::SmallDir, _HBIN::Spare, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, _HHIVE::Storage, and TRUE.
Referenced by CmpShiftHiveFreeBins().
NTSTATUS HvLoadHive (PHHIVE Hive)
Definition at line 375 of file hiveload.c.
References ASSERT, _HHIVE::BaseBlock, _HHIVE::BaseBlockAlloc, _HBASE_BLOCK::BootType, CmDoSelfHeal, _HHIVE::DirtyCount, Fail, FALSE, _HHIVE::Free, HBOOT_SELFHEAL, HFILE_TYPE_PRIMARY, HHIVE_SIGNATURE, HvpAdjustHiveFreeDisplay(), HvpCleanMap(), HvpFreeAllocatedBins(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), _HBASE_BLOCK::Length, _HHIVE::Log, _HBASE_BLOCK::Minor, NoMemory, NotHive, NT_SUCCESS, NULL, RecoverData, RecoverHeader, SelfHeal, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HHIVE::Signature, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_REGISTRY_FILE, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, _HBASE_BLOCK::Type, and _HHIVE::Version.
Referenced by HvInitializeHive().
NTSTATUS HvMapHive (PHHIVE Hive)
Definition at line 113 of file hiveload.c.
References ASSERT, _HHIVE::BaseBlock, _HBASE_BLOCK::BootType, _UNICODE_STRING::Buffer, CmDoSelfHeal, CmKdPrintEx, CmpAcquireFileObjectForFile(), CmpPrefetchHiveFile(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, DPFLTR_TRACE_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, Fail, FALSE, _HBASE_BLOCK::FileName, HBOOT_SELFHEAL, HFILE_TYPE_PRIMARY, HHIVE_SIGNATURE, HvpAdjustHiveFreeDisplay(), HvpCleanMap(), HvpFreeAllocatedBins(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpMapFileImageAndBuildMap(), HvpRecoverData(), _HBASE_BLOCK::Length, _UNICODE_STRING::Length, _HHIVE::Log, _HBASE_BLOCK::Minor, NoMemory, NotHive, NT_SUCCESS, NULL, RecoverData, RecoverHeader, RtlInitUnicodeString(), SelfHeal, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HHIVE::Signature, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_REGISTRY_FILE, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, _HBASE_BLOCK::Type, and _HHIVE::Version.
Referenced by HvInitializeHive().
VOID HvpDelistBinFreeCells (PHHIVE Hive, PHBIN Bin, HSTORAGE_TYPE Type)
Definition at line 1264 of file hivecell.c.
References ASSERT, ASSERT_LISTENTRY, BAD_FREE_BINS_LIST, _HMAP_ENTRY::BinAddress, Cell, CM_BUGCHECK, CONTAINING_RECORD, _FREE_DISPLAY::Display, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _LIST_ENTRY::Flink, _HHIVE::Free, _HHIVE::_DUAL::FreeBins, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HHIVE_FREE_DISPLAY_SIZE, HMAP_DISCARDABLE, HMAP_NEWALLOC, HvpGetCellMap(), _FREE_HBIN::ListEntry, REGISTRY_ERROR, RemoveEntryList(), RtlClearBits(), RtlNumberOfSetBits(), _FREE_HBIN::Size, _HHIVE::Storage, and VALIDATE_CELL_MAP.
Referenced by HvpRecoverData().
RESULT HvpGetHiveHeader (PHHIVE Hive, PHBASE_BLOCK * BaseBlock, PLARGE_INTEGER TimeStamp)
Definition at line 918 of file hiveload.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlockAlloc, _HHIVE::Cluster, FALSE, FileOffset, _HHIVE::FileRead, _HHIVE::Free, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_PRIMARY, HiveSuccess, HSECTOR_SIZE, HSYS_MAJOR, HSYS_MINOR_SUPPORTED, HvpHeaderCheckSum(), NoMemory, NotHive, NULL, PAGE_SIZE, RecoverData, RecoverHeader, RtlZeroMemory, and TRUE.
Referenced by HvLoadHive(), and HvMapHive().
RESULT HvpGetLogHeader (PHHIVE Hive, PHBASE_BLOCK * BaseBlock, PLARGE_INTEGER TimeStamp)
Definition at line 1081 of file hiveload.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlockAlloc, _FILE_FS_SIZE_INFORMATION::BytesPerSector, _HHIVE::Cluster, CmDoSelfHeal, Fail, FALSE, FileEndOfFileInformation, FileFsSizeInformation, FileOffset, _HHIVE::FileRead, _HHIVE::Free, HBASE_BLOCK_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, _LARGE_INTEGER::HighPart, HiveSuccess, HSECTOR_SIZE, HvpHeaderCheckSum(), _LARGE_INTEGER::LowPart, NoMemory, NT_SUCCESS, NULL, RtlZeroMemory, SelfHeal, Status, TRUE, ZwQueryInformationFile(), and ZwQueryVolumeInformationFile().
Referenced by HvLoadHive(), and HvMapHive().
NTSTATUS HvpMapFileImageAndBuildMap (PHHIVE Hive, ULONG Length)
Definition at line 1217 of file hiveload.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmDoSelfHeal, CmKdPrintEx, CmMarkSelfHeal, CmpMapCmView(), CmpTouchView(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, FileOffset, _HBIN::FileOffset, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_PRIMARY, Hive, HMAP_INVIEW, HvCheckHiveDebug, HvMarkDirty(), HvpCheckViewBoundary(), HvpEnlistBinInMap(), HvpGetCellMap(), HvpInitMap(), NT_SUCCESS, NULL, _HBIN::Signature, _HBIN::Size, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_IO_FAILED, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, and TRUE.
Referenced by HvMapHive().
NTSTATUS HvpReadFileImageAndBuildMap (PHHIVE Hive, ULONG Length)
Definition at line 584 of file hiveload.c.
References _HHIVE::Allocate, ASSERT, Bin, CmDoSelfHeal, CmMarkSelfHeal, ExAllocatePool, ExFreePool(), FALSE, FileOffset, _HBIN::FileOffset, _HHIVE::FileRead, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_PRIMARY, Hive, HvCheckHiveDebug, HvMarkDirty(), HvpCleanMap(), HvpEnlistBinInMap(), HvpInitMap(), IO_BUFFER_SIZE, NT_SUCCESS, NULL, PagedPool, RtlCopyMemory, _HBIN::Signature, _HBIN::Size, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_IO_FAILED, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, and TRUE.
Referenced by HvLoadHive().
RESULT HvpRecoverData (PHHIVE Hive)
Definition at line 1464 of file hiveload.c.
References _HHIVE::Allocate, ASSERT, ASSERT_VIEW_MAPPED, ASSERT_VIEW_PINNED, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, _HHIVE::Cluster, CmDoSelfHeal, CmMarkSelfHeal, CmpMapThisBin(), CmpPinCmView(), CmpStashBuffer, CmpStashBufferSize, _HMAP_ENTRY::CmView, DbgPrint(), _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyVector, ExAllocatePoolWithTag, ExFreePool(), Fail, FALSE, FileOffset, _HBIN::FileOffset, _HHIVE::FileRead, _HHIVE::Free, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_LOG, Hive, HiveSuccess, HLOG_DV_SIGNATURE, HLOG_HEADER_SIZE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HSECTOR_SIZE, HvMarkDirty(), HvpDelistBinFreeCells(), HvpEnlistBinInMap(), HvpGetCellMap(), HvpRecoverWholeHive(), HvRecoverDataDebug, IsListEmpty, _HBASE_BLOCK::Length, LOCK_STASH_BUFFER, NoMemory, NT_SUCCESS, NULL, PAGE_SIZE, PagedPool, _CM_VIEW_OF_FILE::PinViewList, ROUND_UP, RtlCheckBit, RtlClearBits(), RtlCopyMemory, RtlInitializeBitMap(), RtlNumberOfSetBits(), SelfHeal, _HBIN::Signature, _HBIN::Size, Stable, Status, STATUS_REGISTRY_RECOVERED, TRUE, UNLOCK_STASH_BUFFER, and VALIDATE_CELL_MAP.
Referenced by HvLoadHive(), and HvMapHive().
NTSTATUS HvpRecoverWholeHive (PHHIVE Hive, ULONG FileOffset)
Definition at line 2059 of file hiveload.c.
References ASSERT, ASSERT_VIEW_MAPPED, ASSERT_VIEW_PINNED, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmpDestroyHiveViewList(), CmpMapCmView(), CmpPinCmView(), CmpStashBuffer, _HMAP_ENTRY::CmView, CONTAINING_RECORD, FALSE, FileOffset, _HBIN::FileOffset, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_LOG, HHIVE_FREE_DISPLAY_SIZE, Hive, HMAP_INVIEW, HvpCheckViewBoundary(), HvpEnlistBinInMap(), HvpFreeAllocatedBins(), HvpGetCellMap(), HvRecoverDataDebug, IsListEmpty, NT_SUCCESS, NULL, _CM_VIEW_OF_FILE::PinViewList, RemoveHeadList(), RtlClearAllBits(), _HBIN::Signature, _HBIN::Size, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, and TRUE.
Referenced by HvpRecoverData().
NTSTATUS HvShrinkHive (PHHIVE Hive, ULONG NewLength)
Definition at line 2469 of file hiveload.c.
References ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HTABLE_SLOTS, HvpAdjustHiveFreeDisplay(), HvpEnlistBinInMap(), HvpFreeMap(), HvpGetCellMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NT_SUCCESS, NULL, PAGED_CODE, _HBIN::Signature, _HBIN::Size, _HBIN::Spare, Stable, Status, and _HHIVE::Storage.
Referenced by CmpShiftHiveFreeBins().
Variable Documentation
PHBIN BinPoint
Definition at line 103 of file hiveload.c.
PUCHAR CmpStashBuffer
Definition at line 64 of file cmdat2.c.
Referenced by HvpRecoverData(), and HvpRecoverWholeHive().
ULONG CmpStashBufferSize
Definition at line 65 of file cmdat2.c.
Referenced by HvpRecoverData().
ULONG FailPoint
Definition at line 109 of file hiveload.c.
ULONG FileOffset
Definition at line 108 of file hiveload.c.
Referenced by HvCloneHive(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), and HvpRecoverWholeHive().
PHHIVE Hive
Definition at line 99 of file hiveload.c.
Referenced by HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), and HvpRecoverWholeHive().
struct { ... } HvCheckHiveDebug
Referenced by HvpMapFileImageAndBuildMap(), and HvpReadFileImageAndBuildMap().
struct { ... } HvRecoverDataDebug
Referenced by HvpRecoverData(), and HvpRecoverWholeHive().
HCELL_INDEX MapPoint
Definition at line 102 of file hiveload.c.
ULONG Space
Definition at line 101 of file hiveload.c.
ULONG Status
Definition at line 100 of file hiveload.c.
Referenced by HvCloneHive(), HvpGetLogHeader(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpRecoverWholeHive(), and HvShrinkHive().