Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/notify.c File Reference
notify.c File Reference
#include "FsRtlP.h"
Data Structures
struct _NOTIFY_CHANGE
struct _REAL_NOTIFY_SYNC
Macros
#define AcquireNotifySync(NS)
#define Add2Ptr(PTR, INC, CAST) ((CAST)((PUCHAR)(PTR) + (INC)))
#define ClearFlag(F, SF)
#define Dbg (0x04000000)
#define MODULE_POOL_TAG ('NrSF')
#define NOTIFY_CLEANUP_CALLED (0x0004)
#define NOTIFY_DEFER_NOTIFY (0x0008)
#define NOTIFY_DIR_IS_ROOT (0x0010)
#define NOTIFY_IMMEDIATE_NOTIFY (0x0002)
#define NOTIFY_STREAM_IS_DELETED (0x0020)
#define NOTIFY_WATCH_TREE (0x0001)
#define PtrOffset(BASE, OFFSET) ((ULONG)((PCHAR)(OFFSET) - (PCHAR)(BASE)))
#define ReleaseNotifySync(NS)
#define SetFlag(F, SF)
Typedefs
typedef struct _NOTIFY_CHANGE NOTIFY_CHANGE
typedef struct _NOTIFY_CHANGE * PNOTIFY_CHANGE
typedef struct _REAL_NOTIFY_SYNC * PREAL_NOTIFY_SYNC
typedef struct _REAL_NOTIFY_SYNC REAL_NOTIFY_SYNC
Functions
VOID FsRtlCancelNotify (IN PDEVICE_OBJECT DeviceObject, IN PIRP ThisIrp)
VOID FsRtlCheckNotifyForDelete (IN PLIST_ENTRY NotifyListHead, IN PVOID FsContext)
PNOTIFY_CHANGE FsRtlIsNotifyOnList (IN PLIST_ENTRY NotifyListHead, IN PVOID FsContext)
VOID FsRtlNotifyChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in PLIST_ENTRY NotifyList, __in BOOLEAN WatchTree, __in ULONG CompletionFilter, __in PIRP NotifyIrp)
VOID FsRtlNotifyCleanup (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext)
VOID FsRtlNotifyCompleteIrp (IN PIRP NotifyIrp, IN PNOTIFY_CHANGE Notify, IN ULONG DataLength, IN NTSTATUS Status, IN ULONG CheckCancel)
VOID FsRtlNotifyCompleteIrpList (IN PNOTIFY_CHANGE Notify, IN NTSTATUS Status)
VOID FsRtlNotifyCompleteIrpList (IN OUT PNOTIFY_CHANGE Notify, IN NTSTATUS Status)
VOID FsRtlNotifyFilterChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext, __in_opt PFILTER_REPORT_CHANGE FilterCallback)
VOID FsRtlNotifyFilterReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in_opt PVOID TargetContext, __in_opt PVOID FilterContext)
VOID FsRtlNotifyFullChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID FsRtlNotifyFullReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in PVOID TargetContext)
NTKERNELAPI VOID FsRtlNotifyInitializeSync (__in PNOTIFY_SYNC *NotifySync)
VOID FsRtlNotifyReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in PSTRING TargetName, __in ULONG FilterMatch)
BOOLEAN FsRtlNotifySetCancelRoutine (IN PIRP NotifyIrp, IN PNOTIFY_CHANGE Notify OPTIONAL)
NTKERNELAPI VOID FsRtlNotifyUninitializeSync (__in PNOTIFY_SYNC *NotifySync)
BOOLEAN FsRtlNotifyUpdateBuffer (IN PFILE_NOTIFY_INFORMATION NotifyInfo, IN ULONG FileAction, IN PSTRING ParentName, IN PSTRING TargetName, IN PSTRING StreamName OPTIONAL, IN BOOLEAN UnicodeName, IN ULONG SizeOfEntry)
Macro Definition Documentation
#define AcquireNotifySync (NS)
Value:
{                                             \
    ERESOURCE_THREAD _CurrentThread;                                        \
    _CurrentThread = (ERESOURCE_THREAD) PsGetCurrentThread();               \
    if (_CurrentThread != ((PREAL_NOTIFY_SYNC) (NS))->OwningThread) {       \
        ExAcquireFastMutexUnsafe( &((PREAL_NOTIFY_SYNC) (NS))->FastMutex ); \
        ((PREAL_NOTIFY_SYNC) (NS))->OwningThread = _CurrentThread;          \
    }                                                                       \
    ((PREAL_NOTIFY_SYNC) (NS))->OwnerCount += 1;                            \
}
Definition at line 293 of file notify.c.
Referenced by FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define Add2Ptr (PTR, INC, CAST) ((CAST)((PUCHAR)(PTR) + (INC)))
Definition at line 255 of file notify.c.
Referenced by FsRtlNotifyFilterReportChange(), and FsRtlNotifyUpdateBuffer().
#define ClearFlag (F, SF)
Value:
{   \
    (F) &= ~(SF);           \
}
Definition at line 277 of file notify.c.
Referenced by FsRtlNotifyCompleteIrpList(), FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define Dbg (0x04000000)
Definition at line 76 of file notify.c.
Referenced by FsRtlCancelNotify(), FsRtlIsNotifyOnList(), FsRtlNotifyChangeDirectory(), FsRtlNotifyCleanup(), FsRtlNotifyCompleteIrp(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyFilterChangeDirectory(), FsRtlNotifyFilterReportChange(), FsRtlNotifyFullChangeDirectory(), FsRtlNotifyFullReportChange(), FsRtlNotifyInitializeSync(), FsRtlNotifyReportChange(), FsRtlNotifySetCancelRoutine(), FsRtlNotifyUninitializeSync(), and FsRtlNotifyUpdateBuffer().
#define MODULE_POOL_TAG ('NrSF')
Definition at line 316 of file notify.c.
#define NOTIFY_CLEANUP_CALLED (0x0004)
Definition at line 235 of file notify.c.
Referenced by FsRtlNotifyCleanup(), and FsRtlNotifyFilterChangeDirectory().
#define NOTIFY_DEFER_NOTIFY (0x0008)
Definition at line 236 of file notify.c.
Referenced by FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define NOTIFY_DIR_IS_ROOT (0x0010)
Definition at line 237 of file notify.c.
Referenced by FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define NOTIFY_IMMEDIATE_NOTIFY (0x0002)
Definition at line 234 of file notify.c.
Referenced by FsRtlCancelNotify(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define NOTIFY_STREAM_IS_DELETED (0x0020)
Definition at line 238 of file notify.c.
Referenced by FsRtlCheckNotifyForDelete(), and FsRtlNotifyFilterChangeDirectory().
#define NOTIFY_WATCH_TREE (0x0001)
Definition at line 233 of file notify.c.
Referenced by FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define PtrOffset (BASE, OFFSET) ((ULONG)((PCHAR)(OFFSET) - (PCHAR)(BASE)))
Definition at line 257 of file notify.c.
#define ReleaseNotifySync (NS)
Value:
{                                             \
    ((PREAL_NOTIFY_SYNC) (NS))->OwnerCount -= 1;                            \
    if (((PREAL_NOTIFY_SYNC) (NS))->OwnerCount == 0) {                      \
        ((PREAL_NOTIFY_SYNC) (NS))->OwningThread = (ERESOURCE_THREAD) 0;    \
        ExReleaseFastMutexUnsafe(&((PREAL_NOTIFY_SYNC) (NS))->FastMutex);   \
    }                                                                       \
}
Definition at line 303 of file notify.c.
Referenced by FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
#define SetFlag (F, SF)
Value:
{     \
    (F) |= (SF);            \
}
Definition at line 273 of file notify.c.
Referenced by FsRtlCancelNotify(), FsRtlCheckNotifyForDelete(), FsRtlNotifyCleanup(), FsRtlNotifyFilterChangeDirectory(), and FsRtlNotifyFilterReportChange().
Typedef Documentation
typedef struct _NOTIFY_CHANGE NOTIFY_CHANGE
typedef struct _NOTIFY_CHANGE * PNOTIFY_CHANGE
typedef struct _REAL_NOTIFY_SYNC * PREAL_NOTIFY_SYNC
typedef struct _REAL_NOTIFY_SYNC REAL_NOTIFY_SYNC
Function Documentation
VOID FsRtlCancelNotify (IN PDEVICE_OBJECT DeviceObject, IN PIRP ThisIrp)
Definition at line 2826 of file notify.c.
References AcquireNotifySync, _NOTIFY_CHANGE::AllocatedBuffer, ASSERT, _NOTIFY_CHANGE::Buffer, _NOTIFY_CHANGE::BufferLength, CONTAINING_RECORD, _NOTIFY_CHANGE::DataLength, Dbg, DebugTrace, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FlagOn, _NOTIFY_CHANGE::Flags, _LIST_ENTRY::Flink, FsRtlCompleteRequest, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), FsRtlpAllocatePool, _NOTIFY_CHANGE::FullDirectoryName, InterlockedDecrement, IoGetCurrentIrpStackLocation, IoMarkIrpPending, IoReleaseCancelSpinLock(), IoSetCancelRoutine, IRP, IsListEmpty, _NOTIFY_CHANGE::LastEntry, MmGetSystemAddressForMdl, NOTIFY_IMMEDIATE_NOTIFY, _NOTIFY_CHANGE::NotifyIrps, _NOTIFY_CHANGE::NotifyList, _NOTIFY_CHANGE::NotifySync, NULL, _NOTIFY_CHANGE::OwningProcess, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, PsChargePoolQuota(), PsReturnProcessPagedPoolQuota(), _NOTIFY_CHANGE::ReferenceCount, ReleaseNotifySync, RemoveEntryList(), RtlCopyMemory, SeReleaseSubjectContext(), SetFlag, STATUS_CANCELLED, STATUS_INSUFFICIENT_RESOURCES, STATUS_QUOTA_EXCEEDED, _NOTIFY_CHANGE::SubjectContext, _NOTIFY_CHANGE::ThisBufferLength, TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlNotifySetCancelRoutine().
VOID FsRtlCheckNotifyForDelete (IN PLIST_ENTRY NotifyListHead, IN PVOID FsContext)
Definition at line 3151 of file notify.c.
References CONTAINING_RECORD, _NOTIFY_CHANGE::Flags, _LIST_ENTRY::Flink, FsRtlNotifyCompleteIrpList(), IsListEmpty, NOTIFY_STREAM_IS_DELETED, _NOTIFY_CHANGE::NotifyIrps, PAGED_CODE, SetFlag, STATUS_DELETE_PENDING, and _NOTIFY_CHANGE::StreamID.
Referenced by FsRtlNotifyFilterChangeDirectory().
PNOTIFY_CHANGE FsRtlIsNotifyOnList (IN PLIST_ENTRY NotifyListHead, IN PVOID FsContext)
Definition at line 2184 of file notify.c.
References CONTAINING_RECORD, Dbg, DebugTrace, _LIST_ENTRY::Flink, _NOTIFY_CHANGE::FsContext, NULL, and PAGED_CODE.
Referenced by FsRtlNotifyCleanup(), and FsRtlNotifyFilterChangeDirectory().
VOID FsRtlNotifyChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in PLIST_ENTRY NotifyList, __in BOOLEAN WatchTree, __in ULONG CompletionFilter, __in PIRP NotifyIrp)
Definition at line 491 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterChangeDirectory(), NULL, PAGED_CODE, and TRUE.
VOID FsRtlNotifyCleanup (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext)
Definition at line 2045 of file notify.c.
References AcquireNotifySync, _NOTIFY_CHANGE::AllocatedBuffer, Dbg, DebugTrace, ExFreePool(), _NOTIFY_CHANGE::Flags, _LIST_ENTRY::Flink, FsRtlIsNotifyOnList(), FsRtlNotifyCompleteIrpList(), _NOTIFY_CHANGE::FullDirectoryName, InterlockedDecrement, IsListEmpty, NOTIFY_CLEANUP_CALLED, _NOTIFY_CHANGE::NotifyIrps, _NOTIFY_CHANGE::NotifyList, NULL, _NOTIFY_CHANGE::OwningProcess, PAGED_CODE, PsReturnProcessPagedPoolQuota(), _NOTIFY_CHANGE::ReferenceCount, ReleaseNotifySync, RemoveEntryList(), SeReleaseSubjectContext(), SetFlag, STATUS_NOTIFY_CLEANUP, _NOTIFY_CHANGE::SubjectContext, and _NOTIFY_CHANGE::ThisBufferLength.
VOID FsRtlNotifyCompleteIrp (IN PIRP NotifyIrp, IN PNOTIFY_CHANGE Notify, IN ULONG DataLength, IN NTSTATUS Status, IN ULONG CheckCancel)
Definition at line 2264 of file notify.c.
References _IO_STACK_LOCATION::Control, Dbg, DebugTrace, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FlagOn, FsRtlCompleteRequest, FsRtlNotifySetCancelRoutine(), IoGetCurrentIrpStackLocation, IoMarkIrpPending, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, MmGetSystemAddressForMdl, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PsReturnProcessPagedPoolQuota(), RtlCopyMemory, SL_PENDING_RETURNED, STATUS_NOTIFY_ENUM_DIR, and STATUS_SUCCESS.
Referenced by FsRtlNotifyCompleteIrpList(), and FsRtlNotifyFilterChangeDirectory().
VOID FsRtlNotifyCompleteIrpList (IN PNOTIFY_CHANGE Notify, IN NTSTATUS Status)
Referenced by FsRtlCheckNotifyForDelete(), FsRtlNotifyCleanup(), and FsRtlNotifyFilterReportChange().
VOID FsRtlNotifyCompleteIrpList (IN OUT PNOTIFY_CHANGE Notify, IN NTSTATUS Status)
Definition at line 2731 of file notify.c.
References ClearFlag, CONTAINING_RECORD, Dbg, DebugTrace, FsRtlNotifyCompleteIrp(), IRP, IsListEmpty, NOTIFY_IMMEDIATE_NOTIFY, NULL, PIRP, RemoveHeadList(), STATUS_SUCCESS, and TRUE.
VOID FsRtlNotifyFilterChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext, __in_opt PFILTER_REPORT_CHANGE FilterCallback)
Definition at line 676 of file notify.c.
References AcquireNotifySync, _NOTIFY_CHANGE::BufferLength, _NOTIFY_CHANGE::CharacterSize, ClearFlag, _NOTIFY_CHANGE::CompletionFilter, _NOTIFY_CHANGE::DataLength, Dbg, DebugTrace, ExFreePool(), FALSE, _IO_STACK_LOCATION::FileObject, _NOTIFY_CHANGE::FilterCallback, FlagOn, _NOTIFY_CHANGE::Flags, _FILE_OBJECT::Flags, FO_CLEANUP_COMPLETE, _NOTIFY_CHANGE::FsContext, _FILE_OBJECT::FsContext, FsRtlCheckNotifyForDelete(), FsRtlCompleteRequest, FsRtlIsNotifyOnList(), FsRtlNotifyCompleteIrp(), FsRtlNotifySetCancelRoutine(), FsRtlpAllocatePool, _NOTIFY_CHANGE::FullDirectoryName, InitializeListHead(), InsertTailList(), InterlockedIncrement, IoGetCurrentIrpStackLocation, IoMarkIrpPending, _NOTIFY_CHANGE::LastEntry, NOTHING, NOTIFY_CLEANUP_CALLED, NOTIFY_DEFER_NOTIFY, NOTIFY_DIR_IS_ROOT, NOTIFY_IMMEDIATE_NOTIFY, NOTIFY_STREAM_IS_DELETED, NOTIFY_WATCH_TREE, _NOTIFY_CHANGE::NotifyIrps, _NOTIFY_CHANGE::NotifyList, _NOTIFY_CHANGE::NotifySync, NULL, _NOTIFY_CHANGE::OwningProcess, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, _NOTIFY_CHANGE::ReferenceCount, ReleaseNotifySync, RtlZeroMemory, SeReleaseSubjectContext(), SetFlag, STATUS_DELETE_PENDING, STATUS_NOTIFY_CLEANUP, STATUS_NOTIFY_ENUM_DIR, STATUS_SUCCESS, _NOTIFY_CHANGE::StreamID, _NOTIFY_CHANGE::SubjectContext, THREAD_TO_PROCESS, _NOTIFY_CHANGE::TraverseCallback, and try_return.
Referenced by FsRtlNotifyChangeDirectory(), and FsRtlNotifyFullChangeDirectory().
VOID FsRtlNotifyFilterReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in_opt PVOID TargetContext, __in_opt PVOID FilterContext)
Definition at line 1205 of file notify.c.
References AcquireNotifySync, Add2Ptr, _NOTIFY_CHANGE::AllocatedBuffer, ARGUMENT_PRESENT, ASSERT, ASSERTMSG, _NOTIFY_CHANGE::Buffer, _STRING::Buffer, _NOTIFY_CHANGE::BufferLength, _NOTIFY_CHANGE::CharacterSize, ClearFlag, _NOTIFY_CHANGE::CompletionFilter, CONTAINING_RECORD, _NOTIFY_CHANGE::DataLength, Dbg, DebugTrace, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FIELD_OFFSET, FILE_ACTION_RENAMED_OLD_NAME, _NOTIFY_CHANGE::FilterCallback, FlagOn, _NOTIFY_CHANGE::Flags, _LIST_ENTRY::Flink, _NOTIFY_CHANGE::FsContext, FsRtlIsNtstatusExpected(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyUpdateBuffer(), FsRtlpAllocatePool, _NOTIFY_CHANGE::FullDirectoryName, IoGetCurrentIrpStackLocation, IRP, IsListEmpty, _NOTIFY_CHANGE::LastEntry, _STRING::Length, LongAlign, _STRING::MaximumLength, MmGetSystemAddressForMdl, _FILE_NOTIFY_INFORMATION::NextEntryOffset, NOTHING, NOTIFY_DEFER_NOTIFY, NOTIFY_DIR_IS_ROOT, NOTIFY_IMMEDIATE_NOTIFY, NOTIFY_WATCH_TREE, _NOTIFY_CHANGE::NotifyIrps, NULL, _NOTIFY_CHANGE::OwningProcess, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, PsChargePoolQuota(), PsReturnProcessPagedPoolQuota(), ReleaseNotifySync, RtlEqualMemory, RtlOemStringToCountedUnicodeSize, SetFlag, STATUS_INSUFFICIENT_RESOURCES, STATUS_QUOTA_EXCEEDED, STATUS_SUCCESS, _NOTIFY_CHANGE::SubjectContext, _NOTIFY_CHANGE::ThisBufferLength, _NOTIFY_CHANGE::TraverseCallback, and TRUE.
Referenced by FsRtlNotifyFullReportChange(), and FsRtlNotifyReportChange().
VOID FsRtlNotifyFullChangeDirectory (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PVOID FsContext, __in PSTRING FullDirectoryName, __in BOOLEAN WatchTree, __in BOOLEAN IgnoreBuffer, __in ULONG CompletionFilter, __in PIRP NotifyIrp, __in_opt PCHECK_FOR_TRAVERSE_ACCESS TraverseCallback, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 570 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterChangeDirectory(), NULL, and PAGED_CODE.
VOID FsRtlNotifyFullReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in USHORT TargetNameOffset, __in_opt PSTRING StreamName, __in_opt PSTRING NormalizedParentName, __in ULONG FilterMatch, __in ULONG Action, __in PVOID TargetContext)
Definition at line 1112 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterReportChange(), NULL, and PAGED_CODE.
NTKERNELAPI VOID FsRtlNotifyInitializeSync (__in PNOTIFY_SYNC * NotifySync)
Definition at line 393 of file notify.c.
References Dbg, DebugTrace, ExInitializeFastMutex, _REAL_NOTIFY_SYNC::FastMutex, FsRtlpAllocatePool, NonPagedPool, NULL, _REAL_NOTIFY_SYNC::OwnerCount, _REAL_NOTIFY_SYNC::OwningThread, and PAGED_CODE.
VOID FsRtlNotifyReportChange (__in PNOTIFY_SYNC NotifySync, __in PLIST_ENTRY NotifyList, __in PSTRING FullTargetName, __in PSTRING TargetName, __in ULONG FilterMatch)
Definition at line 1035 of file notify.c.
References Dbg, DebugTrace, FsRtlNotifyFilterReportChange(), NULL, and PAGED_CODE.
BOOLEAN FsRtlNotifySetCancelRoutine (IN PIRP NotifyIrp, IN PNOTIFY_CHANGE Notify OPTIONAL)
Definition at line 2459 of file notify.c.
References ARGUMENT_PRESENT, Dbg, DebugTrace, FALSE, FsRtlCancelNotify(), InterlockedDecrement, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, NULL, and TRUE.
Referenced by FsRtlNotifyCompleteIrp(), and FsRtlNotifyFilterChangeDirectory().
NTKERNELAPI VOID FsRtlNotifyUninitializeSync (__in PNOTIFY_SYNC * NotifySync)
Definition at line 448 of file notify.c.
References Dbg, DebugTrace, ExFreePool(), NULL, and PAGED_CODE.
BOOLEAN FsRtlNotifyUpdateBuffer (IN PFILE_NOTIFY_INFORMATION NotifyInfo, IN ULONG FileAction, IN PSTRING ParentName, IN PSTRING TargetName, IN PSTRING StreamName OPTIONAL, IN BOOLEAN UnicodeName, IN ULONG SizeOfEntry)
Definition at line 2550 of file notify.c.
References Add2Ptr, ARGUMENT_PRESENT, ASSERT, Dbg, DebugTrace, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, PAGED_CODE, RtlCopyMemory, RtlOemToUnicodeN(), and TRUE.
Referenced by FsRtlNotifyFilterReportChange().