Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/tracelog.c File Reference
tracelog.c File Reference
#include "ntos.h"
#include "wmikmp.h"
#include <zwapi.h>
#include "evntrace.h"
#include "tracep.h"
Macros
#define _WMIKM_
#define ERROR_RETRY_COUNT 100
Functions
NTKERNELAPI VOID WmiBootPhase1 ()
NTSTATUS WmipAdjustFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext)
ULONG WmipAllocateFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG NumberOfBuffers)
NTSTATUS WmipCreateLogFile (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG SwitchFile, IN ULONG Append)
NTSTATUS WmipFinalizeHeader (IN HANDLE FileHandle, IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipFlushActiveBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG FlushAll)
NTSTATUS WmipFlushBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PWMI_BUFFER_HEADER Buffer, IN USHORT BufferFlag)
NTSTATUS WmipFlushBuffersWithMarker (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PSLIST_ENTRY List, IN USHORT BufferFlag)
NTSTATUS WmipGenerateFileName (IN PUNICODE_STRING FilePattern, IN OUT PLONG FileCounter, OUT PUNICODE_STRING FileName)
PWMI_BUFFER_HEADER WmipGetFreeBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext)
VOID WmipLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
PWMI_BUFFER_HEADER FASTCALL WmipPopFreeContextSwapBuffer (UCHAR CurrentProcessor)
NTSTATUS WmipPrepareHeader (IN PWMI_LOGGER_CONTEXT LoggerContext, IN OUT PWMI_BUFFER_HEADER Buffer, IN USHORT BufferFlag)
VOID FASTCALL WmipPushDirtyBuffer (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer)
VOID FASTCALL WmipPushDirtyContextSwapBuffer (UCHAR CurrentProcessor, PWMI_BUFFER_HEADER Buffer)
VOID FASTCALL WmipPushFreeBuffer (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer)
ULONG FASTCALL WmipReleaseTraceBuffer (IN PWMI_BUFFER_HEADER BufferResource, IN PWMI_LOGGER_CONTEXT LoggerContext)
NTSTATUS WmipRequestLogFile (IN PWMI_LOGGER_CONTEXT LoggerContext)
PVOID FASTCALL WmipReserveTraceBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG RequiredSize, OUT PWMI_BUFFER_HEADER *BufferResource, OUT PLARGE_INTEGER TimeStamp)
VOID FASTCALL WmipResetBufferHeader (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer, USHORT BufferType)
NTSTATUS WmipSendNotification (PWMI_LOGGER_CONTEXT LoggerContext, NTSTATUS Status, ULONG Flag)
NTSTATUS WmipSwitchBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PWMI_BUFFER_HEADER *BufferPointer, IN PVOID BufferPointerLocation, IN ULONG ProcessorNumber)
NTSTATUS WmipSwitchToNewFile (IN PWMI_LOGGER_CONTEXT LoggerContext)
NTKERNELAPI ULONG FASTCALL WmiReleaseKernelBuffer (IN PWMI_BUFFER_HEADER BufferResource)
PPERFINFO_TRACE_HEADER FASTCALL WmiReserveWithPerfHeader (IN ULONG AuxSize, OUT PWMI_BUFFER_HEADER *BufferResource)
PSYSTEM_TRACE_HEADER FASTCALL WmiReserveWithSystemHeader (IN ULONG LoggerId, IN ULONG AuxSize, IN PETHREAD Thread, OUT PWMI_BUFFER_HEADER *BufferResource)
Variables
PWMI_BUFFER_HEADER WmipContextSwapProcessorBuffers [MAXIMUM_PROCESSORS]
ULONG WmipFileSystemReady = FALSE
WMI_TRACE_BUFFER_CALLBACK WmipGlobalBufferCallback = NULL
PVOID WmipGlobalCallbackContext = NULL
ULONG WmipGlobalSequence = 0
PWMI_LOGGER_CONTEXT WmipLoggerContext [MAXLOGGERS]
LONG WmipRefCount [MAXLOGGERS]
ULONG WmiTraceAlignment = DEFAULT_TRACE_ALIGNMENT
ULONG WmiUsePerfClock = EVENT_TRACE_CLOCK_SYSTEMTIME
ULONG WmiWriteFailureLimit = ERROR_RETRY_COUNT
Macro Definition Documentation
#define _WMIKM_
Definition at line 37 of file tracelog.c.
#define ERROR_RETRY_COUNT 100
Definition at line 55 of file tracelog.c.
Function Documentation
NTKERNELAPI VOID WmiBootPhase1 ()
Definition at line 2259 of file tracelog.c.
References PAGED_CODE, TRUE, and WmipFileSystemReady.
NTSTATUS WmipAdjustFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 358 of file tracelog.c.
References ExQueryDepthSList, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, and WmipAllocateFreeBuffers().
Referenced by WmipFlushBuffersWithMarker(), and WmipLogger().
ULONG WmipAllocateFreeBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG NumberOfBuffers)
Definition at line 259 of file tracelog.c.
References _WMI_BUFFER_HEADER::CurrentOffset, ExAllocatePoolWithTag, _WMI_BUFFER_STATE::Free, _WMI_BUFFER_HEADER::GlobalEntry, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), KeQuerySystemTime(), NULL, PSLIST_ENTRY, RtlZeroMemory, _WMI_BUFFER_HEADER::SlistEntry, _WMI_BUFFER_HEADER::State, _WMI_BUFFER_HEADER::TimeStamp, TraceDebug, and TRACEPOOLTAG.
Referenced by NtTraceEvent(), WmipAdjustFreeBuffers(), and WmipAllocateTraceBufferPool().
NTSTATUS WmipCreateLogFile (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG SwitchFile, IN ULONG Append)
Definition at line 1511 of file tracelog.c.
References _UNICODE_STRING::Buffer, _WNODE_HEADER::BufferSize, _FILE_STANDARD_INFORMATION::EndOfFile, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, FileStandardInformation, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, PsRevertToSelf(), _LARGE_INTEGER::QuadPart, REQUEST_FLAG_NEW_FILE, RtlCompareMemory(), RtlFreeUnicodeString(), RtlZeroMemory, SeDeleteClientSecurity, SeImpersonateClientEx(), Status, STATUS_FAIL_CHECK, STATUS_NO_MEMORY, TraceDebug, TRACEPOOLTAG, TRUE, WmipCreateDirectoryFile(), WmipCreateNtFileName(), WmipFinalizeHeader(), _WMI_BUFFER_HEADER::Wnode, ZwClose(), ZwQueryInformationFile(), and ZwReadFile().
Referenced by WmipLogger(), and WmipRequestLogFile().
NTSTATUS WmipFinalizeHeader (IN HANDLE FileHandle, IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 2286 of file tracelog.c.
References KeQuerySystemTime(), NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, _LARGE_INTEGER::QuadPart, REQUEST_FLAG_CIRCULAR_TRANSITION, Status, ZwReadFile(), and ZwWriteFile().
Referenced by WmipCreateLogFile(), WmipLogger(), and WmipSwitchToNewFile().
NTSTATUS WmipFlushActiveBuffers (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG FlushAll)
Definition at line 1997 of file tracelog.c.
References CONTAINING_RECORD, ExInterlockedFlushSList(), ExQueryDepthSList, InterlockedExchangePointer, InterlockedPushEntrySList(), KeNumberProcessors, MAXIMUM_PROCESSORS, NULL, PAGED_CODE, PERF_CONTEXT_SWITCH, PERFINFO_IS_GROUP_ON, PSLIST_ENTRY, _WMI_BUFFER_HEADER::ReferenceCount, _WMI_BUFFER_HEADER::SlistEntry, Status, STATUS_SUCCESS, TraceDebug, WMI_BUFFER_FLAG_FLUSH_MARKER, WMI_BUFFER_FLAG_NORMAL, WmipFlushBuffersWithMarker(), WmipKernelLogger, WmipPushDirtyBuffer(), and WmipPushFreeBuffer().
Referenced by WmipLogger(), and WmipRequestLogFile().
NTSTATUS WmipFlushBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PWMI_BUFFER_HEADER Buffer, IN USHORT BufferFlag)
Definition at line 1286 of file tracelog.c.
References ASSERT, BYTES_PER_MB, EVENT_TRACE_CLOCK_PERFCOUNTER, EVENT_TRACE_FILE_MODE_CIRCULAR_PERSIST, EVENT_TRACE_USE_KBYTES_FOR_SIZE, FALSE, NT_SUCCESS, NULL, REQUEST_FLAG_CIRCULAR_PERSIST, REQUEST_FLAG_CIRCULAR_TRANSITION, REQUEST_FLAG_NEW_FILE, Status, STATUS_DISK_FULL, STATUS_LOG_FILE_FULL, STATUS_NO_DATA_DETECTED, STATUS_SEVERITY_ERROR, STATUS_SEVERITY_WARNING, STATUS_SUCCESS, TraceDebug, WMI_BUFFER_TYPE_RUNDOWN, WmipGlobalBufferCallback, WmipGlobalCallbackContext, WmipPrepareHeader(), WmipProcessEvent(), WmipSendNotification(), WNODE_FLAG_USE_TIMESTAMP, and ZwWriteFile().
Referenced by WmipAddLogHeader(), and WmipFlushBuffersWithMarker().
NTSTATUS WmipFlushBuffersWithMarker (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PSLIST_ENTRY List, IN USHORT BufferFlag)
Definition at line 1818 of file tracelog.c.
References CONTAINING_RECORD, ExAllocatePoolWithTag, ExFreePool(), FALSE, Flag, InterlockedPushEntrySList(), KeDelayExecutionThread(), KernelMode, List, NonPagedPool, NT_SUCCESS, NULL, PSLIST_ENTRY, _WMI_BUFFER_HEADER::ReferenceCount, RtlCopyMemory, _WMI_BUFFER_HEADER::SlistEntry, Status, STATUS_DISK_FULL, STATUS_LOG_FILE_FULL, STATUS_NO_DATA_DETECTED, STATUS_NO_MEMORY, STATUS_SEVERITY_WARNING, STATUS_SUCCESS, TraceDebug, TRACEPOOLTAG, WMI_BUFFER_FLAG_NORMAL, WmipAdjustFreeBuffers(), WmipFlushBuffer(), WmipPushFreeBuffer(), WmipSendNotification(), WmiShortTime, WmiWriteFailureLimit, and ZwClose().
Referenced by WmipFlushActiveBuffers().
NTSTATUS WmipGenerateFileName (IN PUNICODE_STRING FilePattern, IN OUT PLONG FileCounter, OUT PUNICODE_STRING FileName)
Definition at line 2115 of file tracelog.c.
References ExAllocatePoolWithTag, ExFreePool(), FAILED, InterlockedIncrement, NULL, PAGED_CODE, PagedPool, RtlEqualMemory, RtlInitUnicodeString(), STATUS_INVALID_PARAMETER_MIX, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, StringCbPrintfW(), TRACEPOOLTAG, wcschr(), wcsrchr(), and wcsstr().
Referenced by WmipStartLogger(), and WmipSwitchToNewFile().
PWMI_BUFFER_HEADER WmipGetFreeBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 183 of file tracelog.c.
References CONTAINING_RECORD, InterlockedDecrement, InterlockedIncrement, InterlockedPopEntrySList(), NULL, PSLIST_ENTRY, REQUEST_FLAG_CIRCULAR_PERSIST, TraceDebug, WMI_BUFFER_TYPE_GENERIC, WMI_BUFFER_TYPE_RUNDOWN, WmipPushFreeBuffer(), and WmipResetBufferHeader().
Referenced by WmipAddLogHeader(), WmipAllocateTraceBufferPool(), and WmipSwitchBuffer().
VOID WmipLogger (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 997 of file tracelog.c.
References ASSERT, Executive, FALSE, InterlockedExchange(), KeGetCurrentThread(), KeQuerySystemTime(), KernelMode, KeSetBasePriorityThread(), KeSetEvent(), KeWaitForSingleObject(), LOW_REALTIME_PRIORITY, NT_SUCCESS, NULL, PAGED_CODE, PsGetCurrentThread(), PsTerminateSystemThread(), REQUEST_FLAG_CIRCULAR_TRANSITION, REQUEST_FLAG_FLUSH_BUFFERS, REQUEST_FLAG_NEW_FILE, Status, STATUS_CANCELLED, STATUS_PENDING, STATUS_SUCCESS, STATUS_TIMEOUT, TraceDebug, TRUE, WmiOneSecond, WmipAdjustFreeBuffers(), WmipCreateLogFile(), WmipFinalizeHeader(), WmipFlushActiveBuffers(), WmipFreeLoggerContext(), WmipRequestLogFile(), WmipStopLoggerInstance(), and ZwClose().
Referenced by WmipStartLogger().
PWMI_BUFFER_HEADER FASTCALL WmipPopFreeContextSwapBuffer (UCHAR CurrentProcessor)
Definition at line 2573 of file tracelog.c.
References ASSERT, _WMI_LOGGER_CONTEXT::BuffersAvailable, _WMI_LOGGER_CONTEXT::BuffersInUse, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_BUFFER_HEADER::ClientContext, _WMI_LOGGER_CONTEXT::CollectionOn, CONTAINING_RECORD, _WMI_LOGGER_CONTEXT::EventsLost, _WMI_LOGGER_CONTEXT::FreeList, InterlockedDecrement, InterlockedIncrement, InterlockedPopEntrySList(), NULL, _WMI_BUFFER_HEADER::Offset, _WMI_CLIENT_CONTEXT::ProcessorNumber, _WMI_LOGGER_CONTEXT::SwitchingInProgress, WMI_BUFFER_TYPE_CTX_SWAP, WMI_CTXSWAP_EVENTSIZE_ALIGNMENT, WmipIsValidLogger, WmipKernelLogger, and WmipResetBufferHeader().
Referenced by WmiTraceContextSwap().
NTSTATUS WmipPrepareHeader (IN PWMI_LOGGER_CONTEXT LoggerContext, IN OUT PWMI_BUFFER_HEADER Buffer, IN USHORT BufferFlag)
Definition at line 2159 of file tracelog.c.
References ASSERT, KeQuerySystemTime(), KERNEL_LOGGER_ID, PAGED_CODE, RtlFillMemory, STATUS_NO_DATA_DETECTED, STATUS_SUCCESS, TraceDebug, WMI_BUFFER_FLAG_FLUSH_MARKER, WmiTraceAlignment, and WNODE_FLAG_TRACED_GUID.
Referenced by WmipFlushBuffer(), and WmipSwitchToNewFile().
VOID FASTCALL WmipPushDirtyBuffer (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer)
Definition at line 2447 of file tracelog.c.
References ASSERT, _WMI_LOGGER_CONTEXT::BuffersAvailable, _WMI_LOGGER_CONTEXT::BuffersDirty, _WMI_LOGGER_CONTEXT::BuffersInUse, _WMI_BUFFER_STATE::Flush, _WMI_LOGGER_CONTEXT::FlushList, _WMI_BUFFER_STATE::Free, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), _WMI_BUFFER_STATE::InUse, _WMI_LOGGER_CONTEXT::NumberOfBuffers, PsGetCurrentThread(), PSLIST_ENTRY, _WMI_BUFFER_HEADER::SlistEntry, _WMI_BUFFER_HEADER::State, and TraceDebug.
Referenced by WmipFlushActiveBuffers(), WmipPushDirtyContextSwapBuffer(), and WmipSwitchBuffer().
VOID FASTCALL WmipPushDirtyContextSwapBuffer (UCHAR CurrentProcessor, PWMI_BUFFER_HEADER Buffer)
Definition at line 2668 of file tracelog.c.
References InterlockedIncrement, _WMI_LOGGER_CONTEXT::ReleaseQueue, UNREFERENCED_PARAMETER, WmipIsValidLogger, WmipKernelLogger, and WmipPushDirtyBuffer().
Referenced by WmiStopContextSwapTrace(), and WmiTraceContextSwap().
VOID FASTCALL WmipPushFreeBuffer (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer)
Definition at line 2513 of file tracelog.c.
References _WMI_LOGGER_CONTEXT::BuffersAvailable, _WMI_LOGGER_CONTEXT::BuffersDirty, _WMI_LOGGER_CONTEXT::BuffersInUse, _WMI_BUFFER_STATE::Flush, _WMI_BUFFER_STATE::Free, _WMI_LOGGER_CONTEXT::FreeList, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), _WMI_BUFFER_STATE::InUse, _WMI_LOGGER_CONTEXT::NumberOfBuffers, PsGetCurrentThread(), PSLIST_ENTRY, _WMI_BUFFER_HEADER::SlistEntry, _WMI_BUFFER_HEADER::State, and TraceDebug.
Referenced by WmipFlushActiveBuffers(), WmipFlushBuffersWithMarker(), and WmipGetFreeBuffer().
ULONG FASTCALL WmipReleaseTraceBuffer (IN PWMI_BUFFER_HEADER BufferResource, IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 1773 of file tracelog.c.
References ASSERT, DISPATCH_LEVEL, InterlockedDecrement, KeGetCurrentIrql(), WmipDereferenceLogger, and WmipNotifyLogger().
Referenced by WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmiReleaseKernelBuffer(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), WmiTraceMessageVa(), WmiTraceProcess(), and WmiTraceThread().
NTSTATUS WmipRequestLogFile (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 883 of file tracelog.c.
References FALSE, KeSetEvent(), NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_SUCCESS, TraceDebug, TRUE, WmipCreateLogFile(), WmipFileSystemReady, WmipFlushActiveBuffers(), and WmipSwitchToNewFile().
Referenced by WmipLogger().
PVOID FASTCALL WmipReserveTraceBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN ULONG RequiredSize, OUT PWMI_BUFFER_HEADER * BufferResource, OUT PLARGE_INTEGER TimeStamp)
Definition at line 531 of file tracelog.c.
References ALIGN_TO_POWER2, ASSERT, _WMI_BUFFER_HEADER::CurrentOffset, InterlockedDecrement, InterlockedExchangeAdd(), InterlockedIncrement, KeGetCurrentProcessorNumber(), NT_SUCCESS, NULL, _WMI_BUFFER_HEADER::ReferenceCount, _WMI_BUFFER_HEADER::SavedOffset, Status, WmipIsValidLogger, WmipSwitchBuffer(), and WmiTraceAlignment.
Referenced by WmipStartGlobalLogger(), WmiReserveWithPerfHeader(), WmiReserveWithSystemHeader(), WmiTraceEvent(), WmiTraceFastEvent(), WmiTraceKernelEvent(), and WmiTraceMessageVa().
VOID FASTCALL WmipResetBufferHeader (PWMI_LOGGER_CONTEXT LoggerContext, PWMI_BUFFER_HEADER Buffer, USHORT BufferType)
Definition at line 2400 of file tracelog.c.
References ASSERT, _WMI_BUFFER_HEADER::BufferType, _WNODE_HEADER::ClientContext, _WMI_BUFFER_HEADER::CurrentOffset, _WMI_BUFFER_STATE::Free, _WMI_BUFFER_STATE::InUse, _WMI_BUFFER_HEADER::LoggerContext, _WMI_BUFFER_HEADER::SavedOffset, _WMI_BUFFER_HEADER::State, WMI_BUFFER_TYPE_MAXIMUM, and _WMI_BUFFER_HEADER::Wnode.
Referenced by WmipAddLogHeader(), WmipGetFreeBuffer(), WmipPopFreeContextSwapBuffer(), and WmipSwitchToNewFile().
NTSTATUS WmipSendNotification (PWMI_LOGGER_CONTEXT LoggerContext, NTSTATUS Status, ULONG Flag)
Definition at line 1252 of file tracelog.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, FALSE, Flag, _WNODE_HEADER::Guid, _WNODE_HEADER::HistoricalContext, KeQuerySystemTime(), _WMI_LOGGER_CONTEXT::LoggerId, RtlZeroMemory, Status, _tagWMI_Event::Status, STATUS_SUCCESS, _WNODE_HEADER::TimeStamp, _tagWMI_Event::TraceErrorFlag, WmipProcessEvent(), WmiSetLoggerId, and _tagWMI_Event::Wnode.
Referenced by WmipFlushBuffer(), WmipFlushBuffersWithMarker(), WmipStopLoggerInstance(), and WmipSwitchToNewFile().
NTSTATUS WmipSwitchBuffer (IN PWMI_LOGGER_CONTEXT LoggerContext, IN PWMI_BUFFER_HEADER * BufferPointer, IN PVOID BufferPointerLocation, IN ULONG ProcessorNumber)
Definition at line 2740 of file tracelog.c.
References _WMI_BUFFER_HEADER::ClientContext, DISPATCH_LEVEL, InterlockedCompareExchangePointer, InterlockedDecrement, InterlockedIncrement, InterlockedPushEntrySList(), KeGetCurrentIrql(), NULL, _WMI_CLIENT_CONTEXT::ProcessorNumber, PSLIST_ENTRY, _WMI_BUFFER_HEADER::SlistEntry, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, STATUS_WMI_ALREADY_DISABLED, TraceDebug, WmipGetFreeBuffer(), WmipNotifyLogger(), and WmipPushDirtyBuffer().
Referenced by WmipReserveTraceBuffer().
NTSTATUS WmipSwitchToNewFile (IN PWMI_LOGGER_CONTEXT LoggerContext)
Definition at line 732 of file tracelog.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), FALSE, NT_SUCCESS, NULL, PAGED_CODE, REQUEST_FLAG_NEW_FILE, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlZeroMemory, Status, STATUS_INVALID_PARAMETER, STATUS_MEDIA_CHANGED, STATUS_NO_MEMORY, STATUS_SEVERITY_INFORMATIONAL, STATUS_SUCCESS, TraceDebug, TRACEPOOLTAG, WMI_BUFFER_TYPE_RUNDOWN, WmipAddLogHeader(), WmipDelayCreate(), WmipFinalizeHeader(), WmipGenerateFileName(), WmipPrepareHeader(), WmipResetBufferHeader(), WmipSendNotification(), ZwClose(), and ZwWriteFile().
Referenced by WmipRequestLogFile().
NTKERNELAPI ULONG FASTCALL WmiReleaseKernelBuffer (IN PWMI_BUFFER_HEADER BufferResource)
Definition at line 1804 of file tracelog.c.
References NULL, WmipAssert, WmipKernelLogger, and WmipReleaseTraceBuffer().
PPERFINFO_TRACE_HEADER FASTCALL WmiReserveWithPerfHeader (IN ULONG AuxSize, OUT PWMI_BUFFER_HEADER * BufferResource)
Definition at line 471 of file tracelog.c.
References FIELD_OFFSET, _PERFINFO_TRACE_HEADER::Marker, NULL, _PERFINFO_TRACE_HEADER::Packet, PERFINFO_TRACE_MARKER, _WMI_TRACE_PACKET::Size, _PERFINFO_TRACE_HEADER::SystemTime, TraceDebug, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, and WmipReserveTraceBuffer().
Referenced by PerfInfoReserveBytes(), WmipTraceFile(), and WmipTraceNetwork().
PSYSTEM_TRACE_HEADER FASTCALL WmiReserveWithSystemHeader (IN ULONG LoggerId, IN ULONG AuxSize, IN PETHREAD Thread, OUT PWMI_BUFFER_HEADER * BufferResource)
Definition at line 406 of file tracelog.c.
References HandleToUlong, _SYSTEM_TRACE_HEADER::KernelTime, _SYSTEM_TRACE_HEADER::Marker, NULL, _SYSTEM_TRACE_HEADER::Packet, _SYSTEM_TRACE_HEADER::ProcessId, PsGetCurrentThread(), _WMI_TRACE_PACKET::Size, SYSTEM_TRACE_MARKER, _SYSTEM_TRACE_HEADER::SystemTime, _SYSTEM_TRACE_HEADER::ThreadId, TraceDebug, _SYSTEM_TRACE_HEADER::UserTime, WmipDereferenceLogger, WmipGetLoggerContext, WmipReferenceLogger, and WmipReserveTraceBuffer().
Referenced by WmipTraceIo(), WmipTraceLoadImage(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmiTraceProcess(), and WmiTraceThread().
Variable Documentation
PWMI_BUFFER_HEADER WmipContextSwapProcessorBuffers[MAXIMUM_PROCESSORS]
Definition at line 66 of file tracelog.c.
Referenced by WmiStartContextSwapTrace(), WmiStopContextSwapTrace(), and WmiTraceContextSwap().
ULONG WmipFileSystemReady = FALSE
Definition at line 75 of file tracelog.c.
Referenced by WmiBootPhase1(), and WmipRequestLogFile().
WMI_TRACE_BUFFER_CALLBACK WmipGlobalBufferCallback = NULL
Definition at line 76 of file tracelog.c.
Referenced by WmipFlushBuffer(), and WmiSetTraceBufferCallback().
PVOID WmipGlobalCallbackContext = NULL
Definition at line 77 of file tracelog.c.
Referenced by WmipFlushBuffer().
ULONG WmipGlobalSequence = 0
Definition at line 64 of file tracelog.c.
Referenced by WmipStartLogger().
PWMI_LOGGER_CONTEXT WmipLoggerContext[MAXLOGGERS]
Definition at line 65 of file tracelog.c.
Referenced by IoWMIWriteEvent(), WmipAddLogHeader(), WmipDriverEntry(), WmipFreeLoggerContext(), WmipIsLoggerOn(), WmipLookupLoggerIdByName(), WmipShutdown(), WmipStartLogger(), WmipStopLoggerInstance(), WmipTraceNetwork(), WmiQueryTraceInformation(), WmiStopContextSwapTrace(), WmiStopTrace(), and WmiTraceKernelEvent().
LONG WmipRefCount[MAXLOGGERS]
Definition at line 63 of file tracelog.c.
Referenced by WmipDriverEntry(), WmipFreeLoggerContext(), WmipStartLogger(), and WmiTraceKernelEvent().
ULONG WmiTraceAlignment = DEFAULT_TRACE_ALIGNMENT
Definition at line 61 of file tracelog.c.
Referenced by WmipAddLogHeader(), WmipPrepareHeader(), WmipReserveTraceBuffer(), and WmipTraceFile().
ULONG WmiUsePerfClock = EVENT_TRACE_CLOCK_SYSTEMTIME
Definition at line 62 of file tracelog.c.
ULONG WmiWriteFailureLimit = ERROR_RETRY_COUNT
Definition at line 74 of file tracelog.c.
Referenced by WmipFlushBuffersWithMarker().