Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/enabdisa.c File Reference
enabdisa.c File Reference
#include "wmikmp.h"
#include "tracep.h"
Macros
#define AVGISPERGUID 64
Functions
NTSTATUS WmipDeliverWnodeToDS (CHAR ActionCode, PBDATASOURCE DataSource, PWNODE_HEADER Wnode, ULONG BufferSize)
NTSTATUS WmipDisableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, ULONG64 LoggerContext)
NTSTATUS WmipDisableTraceProviders (ULONG StopLoggerId)
ULONG WmipDoDisableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext, ULONG InProgressFlag)
NTSTATUS WmipEnableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, BOOLEAN *RequestSent, ULONG64 LoggerContext)
NTSTATUS WmipEnableDisableTrace (IN ULONG Ioctl, IN PWMITRACEENABLEDISABLEINFO TraceEnableInfo)
BOOLEAN WmipIsISFlagsSet (PBGUIDENTRY GuidEntry, ULONG Flags)
void WmipReleaseCollectionEnabled (PBGUIDENTRY GuidEntry)
ULONG WmipSendDisableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext)
NTSTATUS WmipSendEnableDisableRequest (UCHAR ActionCode, PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext)
ULONG WmipSendEnableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext)
void WmipWaitForCollectionEnabled (PBGUIDENTRY GuidEntry)
Macro Definition Documentation
#define AVGISPERGUID 64
Referenced by WmipSendEnableDisableRequest().
Function Documentation
NTSTATUS WmipDeliverWnodeToDS (CHAR ActionCode, PBDATASOURCE DataSource, PWNODE_HEADER Wnode, ULONG BufferSize)
Definition at line 155 of file enabdisa.c.
References ASSERT, _WMIGUIDOBJECT::Cookie, _WNODE_HEADER::CountLost, DS_KERNEL_MODE, DS_USER_MODE, FALSE, _WNODE_HEADER::Flags, tagDATASOURCE::Flags, _WNODE_HEADER::Guid, NULL, PAGED_CODE, _WNODE_HEADER::ProviderId, tagDATASOURCE::ProviderId, tagDATASOURCE::RequestObject, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, WmipEnterSMCritSection, WmipLeaveSMCritSection, WmipSendWmiIrp(), WmipWriteWnodeToObject(), and WNODE_FLAG_INTERNAL.
Referenced by WmipDereferenceEvent(), WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), and WmipSendEnableDisableRequest().
NTSTATUS WmipDisableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, ULONG64 LoggerContext)
Definition at line 1009 of file enabdisa.c.
References ASSERT, FALSE, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, PAGED_CODE, Status, STATUS_ILLEGAL_FUNCTION, TRUE, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipSendDisableRequest().
Referenced by WmipDeleteMethod(), and WmipEnableDisableTrace().
NTSTATUS WmipDisableTraceProviders (ULONG StopLoggerId)
Definition at line 1330 of file enabdisa.c.
References CONTAINING_RECORD, tagGUIDENTRY::Flags, _LIST_ENTRY::Flink, GE_NOTIFICATION_TRACE_FLAG, tagGUIDENTRY::LoggerContext, PAGED_CODE, Status, STATUS_SUCCESS, TRUE, WmiGetLoggerId, WmipEnterSMCritSection, WmipGEHeadPtr, WmipLeaveSMCritSection, WmipReferenceGE, WmipSendDisableRequest(), and WmipUnreferenceGE.
Referenced by WmipProcessEvent(), and WmiStopTrace().
ULONG WmipDoDisableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext, ULONG InProgressFlag)
Definition at line 711 of file enabdisa.c.
References tagGUIDENTRY::CollectRefCount, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagGUIDENTRY::EventRefCount, tagGUIDENTRY::Flags, IRP_MN_DISABLE_COLLECTION, IRP_MN_DISABLE_EVENTS, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), Status, WmipDebugPrintEx, WmipReleaseCollectionEnabled(), and WmipSendEnableDisableRequest().
Referenced by WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), and WmipSendDisableRequest().
NTSTATUS WmipEnableCollectOrEvent (PBGUIDENTRY GuidEntry, ULONG Ioctl, BOOLEAN * RequestSent, ULONG64 LoggerContext)
Definition at line 905 of file enabdisa.c.
References ASSERT, CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, IS_EVENT_ONLY, IS_EXPENSIVE, IS_TRACED, tagGUIDENTRY::ISHead, NT_SUCCESS, PAGED_CODE, Status, STATUS_ILLEGAL_FUNCTION, STATUS_SUCCESS, TRUE, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipSendEnableRequest().
Referenced by WmipEnableDisableTrace(), and WmipOpenBlock().
NTSTATUS WmipEnableDisableTrace (IN ULONG Ioctl, IN PWMITRACEENABLEDISABLEINFO TraceEnableInfo)
Definition at line 1064 of file enabdisa.c.
References DISABLECRITSECTRACE, DISABLEHEAPTRACE, DISABLENTDLLTRACE, ENABLECRITSECTRACE, ENABLEHEAPTRACE, EtwpDefaultTraceSecurityDescriptor, tagGUIDENTRY::EventRefCount, FALSE, tagGUIDENTRY::Flags, GE_NOTIFICATION_TRACE_FLAG, GE_NOTIFICATION_TRACE_UPDATE, tagGUIDENTRY::Guid, InsertHeadList(), IsEqualGUID, tagGUIDENTRY::ISHead, IsListEmpty, tagGUIDENTRY::LoggerContext, tagGUIDENTRY::MainGEList, NT_SUCCESS, NULL, PAGED_CODE, SharedUserData, Status, STATUS_ILLEGAL_FUNCTION, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_WMI_ALREADY_DISABLED, WmipAllocGuidEntry, WmipCheckGuidAccess(), WmipDisableCollectOrEvent(), WmipEnableCollectOrEvent(), WmipEnterSMCritSection, WmipEnterTLCritSection, WmipFindGEByGuid(), WmipGEHeadPtr, WmipIsControlGuid, WmipLeaveSMCritSection, WmipLeaveTLCritSection, WmipReferenceGE, and WmipUnreferenceGE.
Referenced by WmipIoControl(), and WmipNtDllLoggerInfo().
BOOLEAN WmipIsISFlagsSet (PBGUIDENTRY GuidEntry, ULONG Flags)
Definition at line 107 of file enabdisa.c.
References CONTAINING_RECORD, FALSE, tagInstanceSet::Flags, _LIST_ENTRY::Flink, tagGUIDENTRY::ISHead, NULL, PAGED_CODE, TRUE, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
void WmipReleaseCollectionEnabled (PBGUIDENTRY GuidEntry)
Definition at line 433 of file enabdisa.c.
References tagGUIDENTRY::CollectInProgress, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, tagGUIDENTRY::Flags, GE_FLAG_WAIT_ENABLED, KeSetEvent(), PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), and WmipDebugPrintEx.
Referenced by WmipDisableCollectionForRemovedGuid(), WmipDoDisableRequest(), WmipEnableCollectionForNewGuid(), and WmipSendEnableRequest().
ULONG WmipSendDisableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext)
Definition at line 786 of file enabdisa.c.
References tagGUIDENTRY::CollectRefCount, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagGUIDENTRY::EventRefCount, tagGUIDENTRY::Flags, GE_FLAG_COLLECTION_IN_PROGRESS, GE_FLAG_NOTIFICATION_IN_PROGRESS, PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), Status, STATUS_SUCCESS, WmipAssert, WmipDebugPrintEx, and WmipDoDisableRequest().
Referenced by WmipDisableCollectOrEvent(), and WmipDisableTraceProviders().
NTSTATUS WmipSendEnableDisableRequest (UCHAR ActionCode, PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext)
Definition at line 205 of file enabdisa.c.
References ASSERT, AVGISPERGUID, _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, CONTAINING_RECORD, tagInstanceSet::DataSource, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, DS_KERNEL_MODE, DS_USER_MODE, FALSE, _WNODE_HEADER::Flags, tagInstanceSet::Flags, tagGUIDENTRY::Flags, tagDATASOURCE::Flags, _LIST_ENTRY::Flink, GE_FLAG_INTERNAL, GE_NOTIFICATION_TRACE_UPDATE, _WNODE_HEADER::Guid, tagGUIDENTRY::Guid, _WNODE_HEADER::HistoricalContext, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, IS_ENABLE_COLLECTION, IS_ENABLE_EVENT, IS_EXPENSIVE, IS_TRACED, tagGUIDENTRY::ISCount, tagGUIDENTRY::ISHead, WMITRACE_NOTIFY_HEADER::LoggerContext, memset(), NULL, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, WmipAlloc, WmipAssert, WmipDebugPrintEx, WmipDeliverWnodeToDS(), WmipEnterSMCritSection, WmipFree, WmipLeaveSMCritSection, WmipReferenceDS, WmipUnreferenceDS, WMITRACE_NOTIFY_HEADER::Wnode, and WNODE_FLAG_TRACED_GUID.
Referenced by WmipDoDisableRequest(), and WmipSendEnableRequest().
ULONG WmipSendEnableRequest (PBGUIDENTRY GuidEntry, BOOLEAN IsEvent, BOOLEAN IsTraceLog, ULONG64 LoggerContext)
Definition at line 504 of file enabdisa.c.
References tagGUIDENTRY::CollectRefCount, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, tagGUIDENTRY::EventRefCount, tagGUIDENTRY::Flags, GE_FLAG_COLLECTION_IN_PROGRESS, GE_FLAG_NOTIFICATION_IN_PROGRESS, GE_NOTIFICATION_TRACE_UPDATE, IRP_MN_DISABLE_COLLECTION, IRP_MN_DISABLE_EVENTS, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), Status, STATUS_SUCCESS, WmipDebugPrintEx, WmipReferenceGE, WmipReleaseCollectionEnabled(), WmipSendEnableDisableRequest(), WmipUnreferenceGE, and WmipWaitForCollectionEnabled().
Referenced by WmipEnableCollectOrEvent().
void WmipWaitForCollectionEnabled (PBGUIDENTRY GuidEntry)
Definition at line 456 of file enabdisa.c.
References tagGUIDENTRY::CollectInProgress, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, Executive, FALSE, tagGUIDENTRY::Flags, GE_FLAG_COLLECTION_IN_PROGRESS, GE_FLAG_WAIT_ENABLED, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NULL, PAGED_CODE, PsGetCurrentProcessId(), PsGetCurrentThreadId(), WmipAssert, WmipDebugPrintEx, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
Referenced by WmipSendEnableRequest().