Windows Research Kernel v1.2: C:/Windows Research Kernel/se/adt.h File Reference
adt.h File Reference
#include <ntlsa.h>
Functions
NTSTATUS SepAdtCopyToLsaSharedMemory (IN HANDLE LsaProcessHandle, IN PVOID Buffer, IN ULONG BufferLength, OUT PVOID *LsaBufferAddress)
BOOLEAN SepAdtInitializePhase0 ()
BOOLEAN SepAdtInitializePhase1 ()
VOID SepAdtLogAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters)
Function Documentation
NTSTATUS SepAdtCopyToLsaSharedMemory (IN HANDLE LsaProcessHandle, IN PVOID Buffer, IN ULONG BufferLength, OUT PVOID * LsaBufferAddress)
Definition at line 472 of file adtlog.c.
References ASSERT, FALSE, MEM_COMMIT, MEM_RELEASE, NT_SUCCESS, NULL, PAGE_READWRITE, PAGED_CODE, Status, TRUE, ZwAllocateVirtualMemory(), ZwFreeVirtualMemory(), and ZwWriteVirtualMemory().
Referenced by SepRmCallLsa().
BOOLEAN SepAdtInitializePhase0 ()
BOOLEAN SepAdtInitializePhase1 ()
VOID SepAdtLogAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters)
Definition at line 42 of file adtlog.c.
References _SEP_LSA_WORK_ITEM::BaseAddress, _SEP_LSA_WORK_ITEM::CleanupFunction, _SEP_LSA_WORK_ITEM::CommandNumber, _SEP_LSA_WORK_ITEM::CommandParams, _SEP_LSA_WORK_ITEM::CommandParamsLength, _SEP_LSA_WORK_ITEM::CommandParamsMemoryType, ExAllocatePoolWithTag, ExFreePool(), FALSE, LsapWriteAuditMessageCommand, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _SEP_LSA_WORK_ITEM::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBufferLength, SE_AUDITID_AUDITS_DISCARDED, SepAdtMarshallAuditRecord(), SepAuditFailed(), SepAuditRecord, SepCrashOnAuditFail, SepQueueWorkItem(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_UNSUCCESSFUL, _SEP_LSA_WORK_ITEM::Tag, and TRUE.
Referenced by SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and SeReportSecurityEvent().