Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/decode.c File Reference
decode.c File Reference
#include "ki.h"
Data Structures
struct _DECODE_CONTEXT
struct _DECODE_ENTRY
struct _KIOP_COPY_CONTEXT
Macros
#define OP_MAXIMUM_LENGTH 15
#define OP_NOREGEXT 0xFF
#define OP_PREFIX_ADDR (1 << 7)
#define OP_PREFIX_CS (1 << 1)
#define OP_PREFIX_DS (1 << 3)
#define OP_PREFIX_ES (1 << 0)
#define OP_PREFIX_FS (1 << 4)
#define OP_PREFIX_GS (1 << 5)
#define OP_PREFIX_LOCK (1 << 8)
#define OP_PREFIX_OPERAND (1 << 6)
#define OP_PREFIX_REPE (1 << 10)
#define OP_PREFIX_REPNE (1 << 9)
#define OP_PREFIX_REX (1 << 11)
#define OP_PREFIX_SS (1 << 2)
#define OP_PREFIXGRP_REP (1 << 1)
#define OP_PREFIXGRP_SEGMENT (1 << 0)
#define OP_TWOBYTE 0x0F
#define OPF_AV ((ULONG)1 << 28)
#define OPF_DIV ((ULONG)1 << 29)
#define OPF_GP ((ULONG)1 << 31)
#define OPF_IMM32 (1 << 1)
#define OPF_IMM8 (1 << 0)
#define OPF_INVAL ((ULONG)1 << 30)
#define OPF_MODRM (1 << 2)
#define OPF_NONE (0)
Typedefs
typedef struct _DECODE_CONTEXT DECODE_CONTEXT
typedef struct _DECODE_ENTRY DECODE_ENTRY
typedef struct _KIOP_COPY_CONTEXT KIOP_COPY_CONTEXT
typedef struct _DECODE_CONTEXT * PDECODE_CONTEXT
typedef struct _DECODE_ENTRY const * PDECODE_ENTRY
typedef struct _KIOP_COPY_CONTEXT * PKIOP_COPY_CONTEXT
typedef NTSTATUS(* PKOP_OPCODE_HANDLER) (IN PDECODE_CONTEXT DecodeContext)
Functions
BOOLEAN KeInvalidAccessAllowed (__in_opt PVOID TrapInformation)
NTSTATUS KiCheckForAtlThunk (IN PDECODE_CONTEXT DecodeContext)
VOID KiCheckForSListAddress (IN PKTRAP_FRAME TrapFrame)
VOID KiCpuIdFault (VOID)
BOOLEAN KiFilterFiberContext (PCONTEXT Context)
NTSTATUS KiOp_Div (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_Illegal (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_LSAHF (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_MOVAPS (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_MOVDQA (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_PREF_NOP (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_PREFETCH3 (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_PREFETCHx (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOp_Priv (IN PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOpDecode (IN OUT PEXCEPTION_RECORD ExceptionRecord, IN OUT PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode, OUT PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOpDecodeModRM (IN OUT PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOpFetchBytes (IN PDECODE_CONTEXT DecodeContext, IN ULONG Count, OUT PVOID Buffer)
NTSTATUS KiOpFetchNextByte (IN PDECODE_CONTEXT DecodeContext, OUT PUCHAR NextByte)
NTSTATUS KiOpIsPrefix (IN PDECODE_CONTEXT DecodeContext, IN UCHAR OpByte, OUT PBOOLEAN IsPrefix)
NTSTATUS KiOpLocateDecodeEntry (IN OUT PDECODE_CONTEXT DecodeContext)
NTSTATUS KiOpPatchCode (IN PDECODE_CONTEXT DecodeContext, OUT PUCHAR Destination, IN UCHAR Replacement)
NTSTATUS KiOpPatchCode (IN PDECODE_CONTEXT DecodeContext, IN PUCHAR Destination, IN UCHAR Replacement)
BOOLEAN KiOpPreprocessAccessViolation (IN PEXCEPTION_RECORD ExceptionRecord, IN OUT PCONTEXT ContextRecord)
NTSTATUS KiOpRetrieveRegMemAddress (IN OUT PDECODE_CONTEXT DecodeContext, OUT PVOID *OperandAddress, OUT KPROCESSOR_MODE *ProcessorMode)
ULONG_PTR KiOpSingleProcCopy (IN ULONG_PTR Context)
DECLSPEC_NOINLINE BOOLEAN KiPreprocessFault (IN OUT PEXCEPTION_RECORD ExceptionRecord, IN PKTRAP_FRAME TrapFrame, IN OUT PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode)
LOGICAL KiPreprocessInvalidOpcodeFault (IN PKTRAP_FRAME TrapFrame)
NTSTATUS KiPreprocessKernelAccessFault (IN ULONG FaultStatus, IN PVOID VirtualAddress, IN KPROCESSOR_MODE PreviousMode, IN PKTRAP_FRAME TrapFrame)
Variables
LONG volatile KiCodePatchCycle
DECODE_ENTRY const KiOpOneByteTable []
ULONG KiOpPrefetchPatchCount
ULONG KiOpPrefetchPatchRetry
struct {
ULONG Flag
ULONG Group
UCHAR Prefix
} KiOpPrefixTable []
DECODE_ENTRY const KiOpTwoByteTable []
Macro Definition Documentation
#define OP_MAXIMUM_LENGTH 15
Definition at line 64 of file decode.c.
#define OP_NOREGEXT 0xFF
Definition at line 62 of file decode.c.
Referenced by KiOpLocateDecodeEntry().
#define OP_PREFIX_ADDR (1 << 7)
Definition at line 47 of file decode.c.
#define OP_PREFIX_CS (1 << 1)
Definition at line 41 of file decode.c.
#define OP_PREFIX_DS (1 << 3)
Definition at line 43 of file decode.c.
#define OP_PREFIX_ES (1 << 0)
Definition at line 40 of file decode.c.
#define OP_PREFIX_FS (1 << 4)
Definition at line 44 of file decode.c.
#define OP_PREFIX_GS (1 << 5)
Definition at line 45 of file decode.c.
#define OP_PREFIX_LOCK (1 << 8)
Definition at line 48 of file decode.c.
#define OP_PREFIX_OPERAND (1 << 6)
Definition at line 46 of file decode.c.
Referenced by KiOp_Div(), and KiOpDecode().
#define OP_PREFIX_REPE (1 << 10)
Definition at line 50 of file decode.c.
#define OP_PREFIX_REPNE (1 << 9)
Definition at line 49 of file decode.c.
#define OP_PREFIX_REX (1 << 11)
Definition at line 51 of file decode.c.
Referenced by KiOpIsPrefix().
#define OP_PREFIX_SS (1 << 2)
Definition at line 42 of file decode.c.
#define OP_PREFIXGRP_REP (1 << 1)
Definition at line 59 of file decode.c.
#define OP_PREFIXGRP_SEGMENT (1 << 0)
Definition at line 58 of file decode.c.
#define OP_TWOBYTE 0x0F
Definition at line 61 of file decode.c.
Referenced by KiOpDecode().
#define OPF_AV ((ULONG)1 << 28)
Definition at line 78 of file decode.c.
Referenced by KiPreprocessFault().
#define OPF_DIV ((ULONG)1 << 29)
Definition at line 77 of file decode.c.
Referenced by KiPreprocessFault().
#define OPF_GP ((ULONG)1 << 31)
Definition at line 75 of file decode.c.
Referenced by KiPreprocessFault().
#define OPF_IMM32 (1 << 1)
Definition at line 72 of file decode.c.
Referenced by KiOpDecode().
#define OPF_IMM8 (1 << 0)
Definition at line 71 of file decode.c.
Referenced by KiOpDecode().
#define OPF_INVAL ((ULONG)1 << 30)
Definition at line 76 of file decode.c.
Referenced by KiPreprocessFault().
#define OPF_MODRM (1 << 2)
Definition at line 73 of file decode.c.
Referenced by KiOpDecode(), and KiOpRetrieveRegMemAddress().
#define OPF_NONE (0)
Definition at line 70 of file decode.c.
Typedef Documentation
typedef struct _DECODE_CONTEXT DECODE_CONTEXT
typedef struct _DECODE_ENTRY DECODE_ENTRY
typedef struct _KIOP_COPY_CONTEXT KIOP_COPY_CONTEXT
typedef struct _DECODE_CONTEXT * PDECODE_CONTEXT
typedef struct _DECODE_ENTRY const* PDECODE_ENTRY
Definition at line 146 of file decode.c.
typedef struct _KIOP_COPY_CONTEXT * PKIOP_COPY_CONTEXT
typedef NTSTATUS(* PKOP_OPCODE_HANDLER) (IN PDECODE_CONTEXT DecodeContext)
Definition at line 212 of file decode.c.
Function Documentation
BOOLEAN KeInvalidAccessAllowed (__in_opt PVOID TrapInformation)
Definition at line 2861 of file decode.c.
References ARGUMENT_PRESENT, ExpInterlockedPopEntrySListFault(), FALSE, KeUserPopEntrySListFault, RPL_MASK, _KTRAP_FRAME::SegCs, and TRUE.
NTSTATUS KiCheckForAtlThunk (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1404 of file decode.c.
References _EXCEPTION_RECORD::ExceptionInformation, _EXCEPTION_RECORD::ExceptionRecord, FALSE, KiEmulateAtlThunk(), STATUS_SUCCESS, and TRUE.
Referenced by KiPreprocessFault().
VOID KiCheckForSListAddress (IN PKTRAP_FRAME TrapFrame)
Definition at line 1478 of file decode.c.
References ExpInterlockedPopEntrySListEnd(), ExpInterlockedPopEntrySListResume(), KeUserPopEntrySListEnd, KeUserPopEntrySListResume, and RPL_MASK.
Referenced by KiDeliverApc().
VOID KiCpuIdFault (VOID)
BOOLEAN KiFilterFiberContext (PCONTEXT Context)
Referenced by KiOp_Div().
NTSTATUS KiOp_Div (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1859 of file decode.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KiFilterFiberContext(), KiOpRetrieveRegMemAddress(), NT_SUCCESS, OP_PREFIX_OPERAND, ProbeForRead, STATUS_INTEGER_DIVIDE_BY_ZERO, STATUS_INTEGER_OVERFLOW, STATUS_SUCCESS, TRUE, and UserMode.
NTSTATUS KiOp_Illegal (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1371 of file decode.c.
References _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionRecord, _EXCEPTION_RECORD::NumberParameters, STATUS_ILLEGAL_INSTRUCTION, and STATUS_SUCCESS.
NTSTATUS KiOp_LSAHF (IN PDECODE_CONTEXT DecodeContext)
Definition at line 2002 of file decode.c.
References STATUS_ILLEGAL_INSTRUCTION, STATUS_SUCCESS, and TRUE.
NTSTATUS KiOp_MOVAPS (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1610 of file decode.c.
References _KTHREAD::ApcState, _KPROCESS::AutoAlignment, _KTHREAD::AutoAlignment, FALSE, KeGetCurrentThread(), KiOpPatchCode(), NT_SUCCESS, _KAPC_STATE::Process, STATUS_RETRY, STATUS_SUCCESS, TRUE, and UserMode.
NTSTATUS KiOp_MOVDQA (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1537 of file decode.c.
References _KTHREAD::ApcState, _KPROCESS::AutoAlignment, _KTHREAD::AutoAlignment, FALSE, KeGetCurrentThread(), KiOpPatchCode(), NT_SUCCESS, _KAPC_STATE::Process, STATUS_RETRY, STATUS_SUCCESS, and TRUE.
NTSTATUS KiOp_PREF_NOP (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1693 of file decode.c.
References KiCodePatchCycle, STATUS_ILLEGAL_INSTRUCTION, STATUS_SUCCESS, and TRUE.
NTSTATUS KiOp_PREFETCH3 (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1736 of file decode.c.
References KiOpPatchCode(), KiOpPrefetchPatchCount, KiOpPrefetchPatchRetry, NT_SUCCESS, STATUS_ACCESS_VIOLATION, STATUS_ILLEGAL_INSTRUCTION, STATUS_SUCCESS, and TRUE.
NTSTATUS KiOp_PREFETCHx (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1812 of file decode.c.
References STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, and TRUE.
NTSTATUS KiOp_Priv (IN PDECODE_CONTEXT DecodeContext)
Definition at line 1339 of file decode.c.
References _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionRecord, _EXCEPTION_RECORD::NumberParameters, STATUS_PRIVILEGED_INSTRUCTION, and STATUS_SUCCESS.
NTSTATUS KiOpDecode (IN OUT PEXCEPTION_RECORD ExceptionRecord, IN OUT PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode, OUT PDECODE_CONTEXT DecodeContext)
Definition at line 613 of file decode.c.
References ASSERT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KiOpDecodeModRM(), KiOpFetchBytes(), KiOpFetchNextByte(), KiOpIsPrefix(), KiOpLocateDecodeEntry(), NT_SUCCESS, NULL, OP_PREFIX_OPERAND, OP_TWOBYTE, OPF_IMM32, OPF_IMM8, OPF_MODRM, ProbeAndReadUchar, RPL_MASK, RtlZeroMemory, STATUS_SUCCESS, TRUE, and UserMode.
Referenced by KiPreprocessFault().
NTSTATUS KiOpDecodeModRM (IN OUT PDECODE_CONTEXT DecodeContext)
Definition at line 1109 of file decode.c.
References FALSE, KiOpFetchBytes(), KiOpFetchNextByte(), NT_SUCCESS, STATUS_SUCCESS, and TRUE.
Referenced by KiOpDecode().
NTSTATUS KiOpFetchBytes (IN PDECODE_CONTEXT DecodeContext, IN ULONG Count, OUT PVOID Buffer)
Definition at line 814 of file decode.c.
References Count, except, EXCEPTION_EXECUTE_HANDLER, NT_SUCCESS, RtlCopyMemory, and STATUS_SUCCESS.
Referenced by KiOpDecode(), KiOpDecodeModRM(), and KiOpFetchNextByte().
NTSTATUS KiOpFetchNextByte (IN PDECODE_CONTEXT DecodeContext, OUT PUCHAR NextByte)
Definition at line 860 of file decode.c.
References KiOpFetchBytes().
Referenced by KiOpDecode(), KiOpDecodeModRM(), and KiOpLocateDecodeEntry().
NTSTATUS KiOpIsPrefix (IN PDECODE_CONTEXT DecodeContext, IN UCHAR OpByte, OUT PBOOLEAN IsPrefix)
Definition at line 891 of file decode.c.
References FALSE, KiOpPrefixTable, NT_SUCCESS, OP_PREFIX_REX, Prefix, RTL_NUMBER_OF, STATUS_ILLEGAL_INSTRUCTION, STATUS_SUCCESS, and TRUE.
Referenced by KiOpDecode().
NTSTATUS KiOpLocateDecodeEntry (IN OUT PDECODE_CONTEXT DecodeContext)
Definition at line 991 of file decode.c.
References FALSE, KiOpFetchNextByte(), KiOpOneByteTable, KiOpTwoByteTable, NT_SUCCESS, OP_NOREGEXT, RTL_NUMBER_OF, STATUS_SUCCESS, and TRUE.
Referenced by KiOpDecode().
NTSTATUS KiOpPatchCode (IN PDECODE_CONTEXT DecodeContext, OUT PUCHAR Destination, IN UCHAR Replacement)
Referenced by KiOp_MOVAPS(), KiOp_MOVDQA(), and KiOp_PREFETCH3().
NTSTATUS KiOpPatchCode (IN PDECODE_CONTEXT DecodeContext, IN PUCHAR Destination, IN UCHAR Replacement)
Definition at line 2086 of file decode.c.
References ASSERT, _KIOP_COPY_CONTEXT::CopyDirect, _KIOP_COPY_CONTEXT::CopyPerformed, _KIOP_COPY_CONTEXT::Destination, DISPATCH_LEVEL, EFLAGS_IF_MASK, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InitializationPhase, InterlockedCompareExchange64, IoReadAccess, IPI_LEVEL, KeDelayExecutionThread(), KeGetCurrentIrql(), KeGetCurrentProcessorNumber(), KeGetCurrentThread(), KeIpiGenericCall(), KeLowerIrql, KeNumberProcessors, KeRaiseIrql, KernelMode, KfRaiseIrql(), KiOpSingleProcCopy(), memset(), MmCanThreadFault(), MmGetSystemAddressForMdlSafe, MmInitializeMdl, MmProbeAndLockPages(), MmUnlockPages(), NormalPagePriority, NT_SUCCESS, NtCurrentProcess, NULL, PAGE_EXECUTE_READWRITE, _LARGE_INTEGER::QuadPart, _KIOP_COPY_CONTEXT::Replacement, _KIOP_COPY_CONTEXT::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_RETRY, STATUS_SUCCESS, TRUE, UserMode, and ZwProtectVirtualMemory().
BOOLEAN KiOpPreprocessAccessViolation (IN PEXCEPTION_RECORD ExceptionRecord, IN OUT PCONTEXT ContextRecord)
Definition at line 2771 of file decode.c.
References ExpInterlockedPopEntrySListFault(), ExpInterlockedPopEntrySListResume(), FALSE, KeGetCurrentThread(), KeUserPopEntrySListFault, KeUserPopEntrySListResume, KI_SLIST_FAULT_COUNT_MAXIMUM, RPL_MASK, _KTHREAD::SListFaultAddress, _KTHREAD::SListFaultCount, and TRUE.
Referenced by KiPreprocessFault().
NTSTATUS KiOpRetrieveRegMemAddress (IN OUT PDECODE_CONTEXT DecodeContext, OUT PVOID * OperandAddress, OUT KPROCESSOR_MODE * ProcessorMode)
Definition at line 1210 of file decode.c.
References ASSERT, FALSE, KernelMode, NOTHING, OPF_MODRM, and STATUS_SUCCESS.
Referenced by KiOp_Div().
ULONG_PTR KiOpSingleProcCopy (IN ULONG_PTR Context)
Definition at line 2358 of file decode.c.
References _KIOP_COPY_CONTEXT::CopyDirect, _KIOP_COPY_CONTEXT::CopyPerformed, _KIOP_COPY_CONTEXT::Destination, _KIOP_COPY_CONTEXT::Done, FALSE, InterlockedDecrement, KeGetCurrentProcessorNumber(), KeYieldProcessor, KiCodePatchCycle, MMDBG_COPY_UNSAFE, MMDBG_COPY_WRITE, MmDbgCopyMemory(), NT_SUCCESS, _KIOP_COPY_CONTEXT::ProcessorNumber, _KIOP_COPY_CONTEXT::ProcessorsRunning, _KIOP_COPY_CONTEXT::ProcessorsToResume, _KIOP_COPY_CONTEXT::Replacement, _KIOP_COPY_CONTEXT::Status, STATUS_SUCCESS, and TRUE.
Referenced by KiOpPatchCode().
DECLSPEC_NOINLINE BOOLEAN KiPreprocessFault (IN OUT PEXCEPTION_RECORD ExceptionRecord, IN PKTRAP_FRAME TrapFrame, IN OUT PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode)
Definition at line 443 of file decode.c.
References _DECODE_CONTEXT::DecodeEntry, FALSE, KI_EXCEPTION_ACCESS_VIOLATION, KI_EXCEPTION_GP_FAULT, KI_EXCEPTION_INTEGER_DIVIDE_BY_ZERO, KI_EXCEPTION_INVALID_OP, KiCheckForAtlThunk(), KiCodePatchCycle, KiOpDecode(), KiOpPreprocessAccessViolation(), NT_SUCCESS, NULL, OPF_AV, OPF_DIV, OPF_GP, OPF_INVAL, _DECODE_CONTEXT::Retry, STATUS_ACCESS_VIOLATION, STATUS_ILLEGAL_INSTRUCTION, STATUS_INTEGER_DIVIDE_BY_ZERO, and TRUE.
Referenced by KiDispatchException().
LOGICAL KiPreprocessInvalidOpcodeFault (IN PKTRAP_FRAME TrapFrame)
Definition at line 2653 of file decode.c.
References APC_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetCurrentIrql(), KeLowerIrql, KernelMode, KfRaiseIrql(), MODE_MASK, NOTHING, ProbeAndReadUchar, TRUE, and UserMode.
NTSTATUS KiPreprocessKernelAccessFault (IN ULONG FaultStatus, IN PVOID VirtualAddress, IN KPROCESSOR_MODE PreviousMode, IN PKTRAP_FRAME TrapFrame)
Definition at line 2481 of file decode.c.
References FALSE, STATUS_ACCESS_VIOLATION, TRUE, and UNREFERENCED_PARAMETER.
Variable Documentation
ULONG Flag
Definition at line 122 of file decode.c.
Referenced by KeFreezeExecution(), KeThawExecution(), WmipFlushBuffersWithMarker(), and WmipSendNotification().
ULONG Group
Definition at line 130 of file decode.c.
Referenced by RtlSetGroupSecurityDescriptor(), RtlValidSecurityDescriptor(), and SeComputeQuotaInformationSize().
LONG volatile KiCodePatchCycle
Definition at line 26 of file decode.c.
Referenced by KiOp_PREF_NOP(), KiOpSingleProcCopy(), and KiPreprocessFault().
DECODE_ENTRY const KiOpOneByteTable[]
Initial value:
= {
    { 0xfa, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0xfb, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0xe4, 4,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0xec, 4,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x6c, 4,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x9E, 2,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_LSAHF     },
    { 0xf4, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0xf6, 1,                 0,           6, OPF_MODRM, KiOp_Div       },
    { 0xf6, 1,                 0,           7, OPF_MODRM, KiOp_Div       },
    { 0xf7, 1,                 0,           6, OPF_MODRM, KiOp_Div       },
    { 0xf7, 1,                 0,           7, OPF_MODRM, KiOp_Div       }
}
Definition at line 397 of file decode.c.
Referenced by KiOpLocateDecodeEntry().
ULONG KiOpPrefetchPatchCount
Definition at line 33 of file decode.c.
Referenced by KiOp_PREFETCH3().
ULONG KiOpPrefetchPatchRetry
Definition at line 34 of file decode.c.
Referenced by KiOp_PREFETCH3().
struct { ... } KiOpPrefixTable[]
Initial value:
= {
    { 0x26, OP_PREFIX_ES,      OP_PREFIXGRP_SEGMENT },
    { 0x2e, OP_PREFIX_CS,      OP_PREFIXGRP_SEGMENT },
    { 0x36, OP_PREFIX_SS,      OP_PREFIXGRP_SEGMENT },
    { 0x3e, OP_PREFIX_DS,      OP_PREFIXGRP_SEGMENT },
    { 0x64, OP_PREFIX_FS,      OP_PREFIXGRP_SEGMENT },
    { 0x65, OP_PREFIX_GS,      OP_PREFIXGRP_SEGMENT },
    { 0x66, OP_PREFIX_OPERAND, 0 },
    { 0x67, OP_PREFIX_ADDR,    0 },
    { 0xf0, OP_PREFIX_LOCK,    0 },
    { 0xf2, OP_PREFIX_REPNE,   OP_PREFIXGRP_REP },
    { 0xf3, OP_PREFIX_REPE,    OP_PREFIXGRP_REP }
}
Referenced by KiOpIsPrefix().
DECODE_ENTRY const KiOpTwoByteTable[]
Initial value:
= {
    { 0x6F, 1, OP_PREFIX_OPERAND, OP_NOREGEXT, OPF_MODRM, KiOp_MOVDQA    },
    { 0x7F, 1, OP_PREFIX_OPERAND, OP_NOREGEXT, OPF_MODRM, KiOp_MOVDQA    },
    { 0x28, 1,                 0, OP_NOREGEXT, OPF_MODRM, KiOp_MOVAPS    },
    { 0x29, 1,                 0, OP_NOREGEXT, OPF_MODRM, KiOp_MOVAPS    },
    { 0x00, 1,                 0,           2, OPF_NONE,  KiOp_Priv      },
    { 0x00, 1,                 0,           3, OPF_NONE,  KiOp_Priv      },
    { 0x01, 1,                 0,           2, OPF_NONE,  KiOp_Priv      },
    { 0x01, 1,                 0,           3, OPF_NONE,  KiOp_Priv      },
    { 0x01, 1,                 0,           6, OPF_NONE,  KiOp_Priv      },
    { 0x01, 1,                 0,           7, OPF_NONE,  KiOp_Priv      },
    { 0x08, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x09, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x0D, 1,                 0,           0, OPF_MODRM, KiOp_PREFETCH3 },
    { 0x0D, 1,                 0,           1, OPF_MODRM, KiOp_PREFETCH3 },
    { 0x18, 1,                 0,           0, OPF_MODRM, KiOp_PREFETCHx },
    { 0x18, 1,                 0,           1, OPF_MODRM, KiOp_PREFETCHx },
    { 0x18, 1,                 0,           2, OPF_MODRM, KiOp_PREFETCHx },
    { 0x18, 1,                 0,           3, OPF_MODRM, KiOp_PREFETCHx },
    { 0x1f, 1,                 0,           1, OPF_MODRM, KiOp_PREF_NOP  },
    { 0x35, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x20, 4,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x30, 4,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0x06, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      },
    { 0xAA, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Illegal   },
    { 0x07, 1,                 0, OP_NOREGEXT, OPF_NONE,  KiOp_Priv      }
}
Definition at line 413 of file decode.c.
Referenced by KiOpLocateDecodeEntry().
UCHAR Prefix
Definition at line 116 of file decode.c.
Referenced by IopDeleteSessionSymLinks(), KiOpIsPrefix(), PfxInsertPrefix(), and RtlInsertUnicodePrefix().