Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmtredel.c File Reference
cmtredel.c File Reference
#include "cmp.h"
Functions
VOID CmpDeleteTree (PHHIVE Hive, HCELL_INDEX Cell)
NTSTATUS CmpFreeKeyByCell (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN Unlink)
BOOLEAN CmpMarkKeyDirty (PHHIVE Hive, HCELL_INDEX Cell)
Function Documentation
VOID CmpDeleteTree (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 32 of file cmtredel.c.
References ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, Cell, CmKdPrintEx, CML_SAVRES, CmpFindSubKeyByNumber(), CmpFreeKeyByCell(), DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvReleaseCell, NULL, _CM_KEY_NODE::Parent, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmpSyncSubKeysAfterDelete(), and CmRestoreKey().
NTSTATUS CmpFreeKeyByCell (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN Unlink)
Definition at line 176 of file cmtredel.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, CmLockHiveSecurityExclusive, CmpFreeKeyBody(), CmpFreeSecurityDescriptor(), CmpFreeValue(), CmpMarkKeyDirty(), CmpRemoveSubKey(), CmUnlockHiveSecurity, _CHILD_LIST::Count, DBG, FALSE, _CM_KEY_NODE::Flags, HvFreeCell(), HvGetCell, HvReleaseCell, KEY_HIVE_EXIT, KEY_PREDEF_HANDLE, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyNode, _CHILD_LIST::List, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, NULL, _CM_KEY_NODE::Parent, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmDeleteKey(), CmMoveKey(), CmpDeleteTree(), CmpDestroyHive(), CmpDoCreate(), CmpDuplicateKey(), CmpSyncSubKeysAfterDelete(), and CmRestoreKey().
BOOLEAN CmpMarkKeyDirty (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 347 of file cmtredel.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, _CM_KEY_SECURITY::Blink, Cell, _CM_KEY_NODE::Class, CmpMarkIndexDirty(), CmpMarkValueDataDirty(), _CHILD_LIST::Count, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_SECURITY::Flink, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, KEY_PREDEF_HANDLE, _CELL_DATA::_u::KeyList, _CELL_DATA::_u::KeyNode, _CELL_DATA::_u::KeySecurity, _CELL_DATA::_u::KeyValue, _CHILD_LIST::List, NULL, _CM_KEY_NODE::Parent, _CM_KEY_NODE::Security, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmMoveKey(), and CmpFreeKeyByCell().