Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/sysptes.c File Reference
sysptes.c File Reference
#include "mi.h"
Data Structures
struct _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT
union _PTE_QUEUE_POINTER
struct _PTE_SLIST
Macros
#define MI_MAXIMUM_SLIST_PTE_PAGES 8
#define MM_MAX_SYSPTE_FREE 3000
#define MM_MIN_SYSPTE_FREE 500
#define MM_PTE_LIST_1 400
#define MM_PTE_LIST_16 40
#define MM_PTE_LIST_18 40
#define MM_PTE_LIST_19 40
#define MM_PTE_LIST_2 100
#define MM_PTE_LIST_4 60
#define MM_PTE_LIST_6 100
#define MM_PTE_LIST_8 50
#define MM_PTE_LIST_9 50
#define MM_PTE_TABLE_LIMIT 16
#define MM_SYS_PTE_TABLES_MAX 5
#define SYSPTES_FLUSH_COUNTER_MASK 0xFFFFFFFF
Typedefs
typedef struct _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT MM_PTE_SLIST_EXPANSION_WORK_CONTEXT
typedef struct _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT * PMM_PTE_SLIST_EXPANSION_WORK_CONTEXT
typedef union _PTE_QUEUE_POINTER * PPTE_QUEUE_POINTER
typedef struct _PTE_SLIST * PPTE_SLIST
typedef union _PTE_QUEUE_POINTER PTE_QUEUE_POINTER
typedef struct _PTE_SLIST PTE_SLIST
Functions
VOID MiAddExtraSystemPteRanges (IN PMMPTE PointerPte, IN ULONG NumberOfPtes)
VOID MiAddSystemPtes (IN PMMPTE StartingPte, IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiCheckPteRelease (IN PMMPTE StartingPte, IN ULONG NumberOfPtes)
VOID MiCheckPteReserve (IN PMMPTE StartingPte, IN ULONG NumberOfPtes)
ULONG MiCountFreeSystemPtes (IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiDumpSystemPtes (IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiFeedSysPtePool (IN ULONG Index)
PVOID MiGetHighestPteConsumer (OUT PULONG_PTR NumberOfPtes)
LOGICAL MiGetSystemPteAvailability (IN ULONG NumberOfPtes, IN MM_PAGE_PRIORITY Priority)
ULONG MiGetSystemPteListCount (IN ULONG ListSize)
VOID MiIncrementSystemPtes (IN ULONG NumberOfPtes)
VOID MiInitializeSystemPtes (IN PMMPTE StartingPte, IN PFN_NUMBER NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiInsertPteTracker (IN PMDL MemoryDescriptorList, IN ULONG Flags, IN LOGICAL IoMapping, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute, IN PVOID MyCaller, IN PVOID MyCallersCaller)
VOID MiIssueNoPtesBugcheck (IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
PVOID MiMapLockedPagesInUserSpace (IN PMDL MemoryDescriptorList, IN PVOID StartingVa, IN MEMORY_CACHING_TYPE CacheType, IN PVOID BaseVa)
VOID MiPteSListExpansionWorker (IN PVOID Context)
LOGICAL MiRecoverExtraPtes (ULONG NumberOfPtes)
LOGICAL MiRecoverExtraPtes (IN ULONG NumberOfPtes)
VOID MiReleaseSplitSystemPtes (IN PMMPTE StartingPte, IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiReleaseSystemPtes (IN PMMPTE StartingPte, IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiRemovePteTracker (IN PMDL MemoryDescriptorList OPTIONAL, IN PVOID VirtualAddress, IN PFN_NUMBER NumberOfPtes)
PMMPTE MiReserveAlignedSystemPtes (IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType, IN ULONG Alignment)
PMMPTE MiReserveSystemPtes (IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiUnmapLockedPagesInUserSpace (IN PVOID BaseAddress, IN PMDL MemoryDescriptorList)
ULONG MmGetNumberOfFreeSystemPtes (VOID)
PVOID MmMapLockedPagesSpecifyCache (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in MEMORY_CACHING_TYPE CacheType, __in_opt PVOID RequestedAddress, __in ULONG BugCheckOnFailure, __in MM_PAGE_PRIORITY Priority)
VOID MmUnmapLockedPages (__in PVOID BaseAddress, __in PMDL MemoryDescriptorList)
__inline VOID PackPTEValue (IN PPTE_QUEUE_POINTER Entry, IN PMMPTE PointerPte, IN ULONG TimeStamp)
__inline PMMPTE UnpackPTEPointer (IN PPTE_QUEUE_POINTER Entry)
__inline ULONG UnpackPTETimeStamp (IN PPTE_QUEUE_POINTER Entry)
Variables
MMPTE MiAddPtesList
ULONG MiCacheOverride [4]
PVOID MiLowestSystemPteVirtualAddress
PRTL_BITMAP MiPteEndBitmap
ULONG MiPteRangeIndex
MI_PTE_RANGES MiPteRanges [MI_NUMBER_OF_PTE_RANGES]
MM_PTE_SLIST_EXPANSION_WORK_CONTEXT MiPteSListExpand
PMMPTE MiPteStart
PRTL_BITMAP MiPteStartBitmap
KSPIN_LOCK MiPteTrackerLock
ULONG MiSpecialPoolExtraCount
ULONG MiSysPteTimeStamp [MaximumPtePoolTypes]
ULONG MiSystemPteAllocationFailed
LONG MiSystemPteFreeCount [MM_SYS_PTE_TABLES_MAX]
PVOID MiSystemPteNBHead [MM_SYS_PTE_TABLES_MAX]
SLIST_HEADER MiSystemPteSListHead
KSPIN_LOCK MiSystemPteSListHeadLock
ULONG MmPteFailures [MaximumPtePoolTypes]
PMMPTE MmSharedUserDataPte
ULONG MmSysPteIndex [MM_SYS_PTE_TABLES_MAX] = {1,2,4,8,MM_PTE_TABLE_LIMIT}
ULONG MmSysPteListBySizeCount [MM_SYS_PTE_TABLES_MAX]
ULONG MmSysPteMinimumFree [MM_SYS_PTE_TABLES_MAX] = {100,50,30,20,20}
UCHAR MmSysPteTables [MM_PTE_TABLE_LIMIT+1] = {0,0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4}
PMMPTE MmSystemPtesEnd [MaximumPtePoolTypes]
PMMPTE MmSystemPtesStart [MaximumPtePoolTypes]
ULONG MmTotalFreeSystemPtes [MaximumPtePoolTypes]
ULONG MmTotalSystemPtes
Macro Definition Documentation
#define MI_MAXIMUM_SLIST_PTE_PAGES 8
Definition at line 159 of file sysptes.c.
Referenced by MiPteSListExpansionWorker(), and MiReleaseSystemPtes().
#define MM_MAX_SYSPTE_FREE 3000
Definition at line 133 of file sysptes.c.
Referenced by MiReleaseSystemPtes(), and MmUnmapLockedPages().
#define MM_MIN_SYSPTE_FREE 500
Definition at line 132 of file sysptes.c.
Referenced by MiFeedSysPtePool(), MiReleaseSystemPtes(), and MmUnmapLockedPages().
#define MM_PTE_LIST_1 400
Definition at line 141 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_16 40
Definition at line 147 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_18 40
Definition at line 148 of file sysptes.c.
#define MM_PTE_LIST_19 40
Definition at line 149 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_2 100
Definition at line 142 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_4 60
Definition at line 143 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_6 100
Definition at line 144 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_8 50
Definition at line 145 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define MM_PTE_LIST_9 50
Definition at line 146 of file sysptes.c.
#define MM_PTE_TABLE_LIMIT 16
Definition at line 119 of file sysptes.c.
Referenced by MiCheckPteRelease(), MiGetSystemPteAvailability(), MiGetSystemPteListCount(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
#define MM_SYS_PTE_TABLES_MAX 5
Definition at line 117 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
#define SYSPTES_FLUSH_COUNTER_MASK 0xFFFFFFFF
Definition at line 336 of file sysptes.c.
Referenced by MiReserveAlignedSystemPtes(), MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
Typedef Documentation
typedef struct _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT MM_PTE_SLIST_EXPANSION_WORK_CONTEXT
typedef struct _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT * PMM_PTE_SLIST_EXPANSION_WORK_CONTEXT
typedef union _PTE_QUEUE_POINTER * PPTE_QUEUE_POINTER
typedef struct _PTE_SLIST * PPTE_SLIST
typedef union _PTE_QUEUE_POINTER PTE_QUEUE_POINTER
typedef struct _PTE_SLIST PTE_SLIST
Function Documentation
VOID MiAddExtraSystemPteRanges (IN PMMPTE PointerPte, IN ULONG NumberOfPtes)
Definition at line 3069 of file sysptes.c.
References ASSERT, _MI_PTE_RANGES::EndingVa, FALSE, _MMPTE::List, MI_NUMBER_OF_PTE_RANGES, MiGetVirtualAddressMappedByPte, MiLockSystemSpace, MiPteRangeIndex, MiUnlockSystemSpace, MM_EMPTY_PTE_LIST, MmSystemPteBase, _MMPTE_LIST::NextEntry, NULL, PAGE_SHIFT, _MI_PTE_RANGES::StartingVa, and _MMPTE::u.
Referenced by MiInitMachineDependent(), and MmInitSystem().
VOID MiAddSystemPtes (IN PMMPTE StartingPte, IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Definition at line 2544 of file sysptes.c.
References ASSERT, MiGetVirtualAddressMappedByPte, MiLowestSystemPteVirtualAddress, MiReleaseSystemPtes(), MmTrackPtes, and SystemPteSpace.
Referenced by MiRecoverExtraPtes(), and MmInitSystem().
VOID MiCheckPteRelease (IN PMMPTE StartingPte, IN ULONG NumberOfPtes)
Definition at line 2827 of file sysptes.c.
References ASSERT, _RTL_BITMAP::Buffer, ExAcquireSpinLock, ExReleaseSpinLock, Index, KeBugCheckEx(), MI_CHECK_BIT, MI_CLEAR_BIT, MiGetVirtualAddressMappedByPte, MiPteTrackerLock, MM_PTE_TABLE_LIMIT, MmSysPteIndex, MmSysPteTables, MmTrackPtes, PAGE_SHIFT, RtlCheckBit, RtlClearBits(), SYSTEM_PTE_MISUSE, and SystemPteSpace.
Referenced by MiReleaseSystemPtes(), and MmUnmapLockedPages().
VOID MiCheckPteReserve (IN PMMPTE StartingPte, IN ULONG NumberOfPtes)
Definition at line 2741 of file sysptes.c.
References ASSERT, _RTL_BITMAP::Buffer, ExAcquireSpinLock, ExReleaseSpinLock, KeBugCheckEx(), MI_CHECK_BIT, MI_SET_BIT, MiGetVirtualAddressMappedByPte, MiPteTrackerLock, MmTrackPtes, PAGE_SHIFT, RtlSetBits(), and SYSTEM_PTE_MISUSE.
Referenced by MiReserveAlignedSystemPtes(), MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
ULONG MiCountFreeSystemPtes (IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Referenced by MiInitializeSystemPtes(), MiReleaseSystemPtes(), and MiReserveAlignedSystemPtes().
VOID MiDumpSystemPtes (IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
VOID MiFeedSysPtePool (IN ULONG Index)
Definition at line 476 of file sysptes.c.
References Index, MiRecoverExtraPtes(), MiReleaseSystemPtes(), MiReserveAlignedSystemPtes(), MM_MIN_SYSPTE_FREE, MmSysPteIndex, MmTotalFreeSystemPtes, NULL, PTE_PER_PAGE, and SystemPteSpace.
Referenced by MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
PVOID MiGetHighestPteConsumer (OUT PULONG_PTR NumberOfPtes)
Definition at line 4653 of file iosup.c.
References _LIST_ENTRY::Blink, _PTE_TRACKER::CallersCaller, _PTE_TRACKER::CallingAddress, CONTAINING_RECORD, _PTE_TRACKER::Count, _KLDR_DATA_TABLE_ENTRY::DllBase, _LIST_ENTRY::Flink, IsListEmpty, _SYSPTES_HEADER::ListHead, _PTE_TRACKER::Matched, MiTrackPtesAborted, MmTrackPtes, NOTHING, NULL, PsLoadedModuleList, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, and TRUE.
Referenced by MiIssueNoPtesBugcheck().
LOGICAL MiGetSystemPteAvailability (IN ULONG NumberOfPtes, IN MM_PAGE_PRIORITY Priority)
Definition at line 2643 of file sysptes.c.
References ASSERT, FALSE, HighPagePriority, Index, MiRecoverExtraPtes(), MM_PTE_TABLE_LIMIT, MmPteFailures, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmTotalFreeSystemPtes, NormalPagePriority, SystemPteSpace, and TRUE.
Referenced by MmMapLockedPagesSpecifyCache().
ULONG MiGetSystemPteListCount (IN ULONG ListSize)
Definition at line 2605 of file sysptes.c.
References ASSERT, Index, MM_PTE_TABLE_LIMIT, MmSysPteListBySizeCount, and MmSysPteTables.
VOID MiIncrementSystemPtes (IN ULONG NumberOfPtes)
Definition at line 2513 of file sysptes.c.
References MmTotalSystemPtes.
Referenced by MiInitMachineDependent(), and MmInitSystem().
VOID MiInitializeSystemPtes (IN PMMPTE StartingPte, IN PFN_NUMBER NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Definition at line 2248 of file sysptes.c.
References _4gb, _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::Active, ASSERT, ASSERT64, _MI_PTE_RANGES::EndingVa, ExAllocatePoolWithTag, ExFreePool(), ExInitializeNBQueueHead(), FALSE, InitializeSListHead(), InterlockedPushEntrySList(), KeInitializeSpinLock(), _MMPTE::List, _MMPTE::Long, MI_PTE_BASE_FOR_LOWEST_KERNEL_ADDRESS, MI_ROUND_TO_SIZE, MI_WRITE_ZERO_PTE, MiCountFreeSystemPtes(), MiCreateBitMap, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIssueNoPtesBugcheck(), MiLowestSystemPteVirtualAddress, MiPteRangeIndex, MiReleaseSystemPtes(), MiReserveSystemPtes(), MiSystemPteNBHead, MiSystemPteSListHeadLock, MiZeroMemoryPte, MM_EMPTY_LIST, MM_PTE_LIST_1, MM_PTE_LIST_16, MM_PTE_LIST_19, MM_PTE_LIST_2, MM_PTE_LIST_4, MM_PTE_LIST_6, MM_PTE_LIST_8, MM_SYS_PTE_TABLES_MAX, MmFirstFreeSystemPte, MmNumberOfSystemPtes, MmSysPteIndex, MmSystemPteBase, MmSystemRangeStart, MmTotalFreeSystemPtes, MmTotalSystemPtes, MmTrackPtes, _MMPTE_LIST::NextEntry, NonPagedPool, NULL, _MMPTE_LIST::OneEntry, PAGE_SHIFT, PAGE_SIZE, PSLIST_ENTRY, PTE_TOP, RtlClearAllBits(), _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::SListPages, _MI_PTE_RANGES::StartingVa, SystemPteSpace, TRUE, and _MMPTE::u.
Referenced by MiInitializeNonPagedPool(), and MiInitMachineDependent().
VOID MiInsertPteTracker (IN PMDL MemoryDescriptorList, IN ULONG Flags, IN LOGICAL IoMapping, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute, IN PVOID MyCaller, IN PVOID MyCallersCaller)
Definition at line 4321 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _PTE_TRACKER::CacheAttribute, _PTE_TRACKER::CallersCaller, _PTE_TRACKER::CallingAddress, _PTE_TRACKER::Count, _SYSPTES_HEADER::Count, DISPATCH_LEVEL, ExAcquireSpinLock, ExAllocatePoolWithTag, ExFreePool(), ExInterlockedFlushSList(), ExQueryDepthSList, ExReleaseSpinLock, FALSE, InsertHeadList(), InterlockedPopEntrySList(), _PTE_TRACKER::IoMapping, KeGetCurrentIrql(), _PTE_TRACKER::Length, _PTE_TRACKER::ListEntry, _SYSPTES_HEADER::ListHead, _PTE_TRACKER::Matched, _PTE_TRACKER::Mdl, MiPteTrackerLock, MiTrackPtesAborted, NonPagedPool, NULL, _SYSPTES_HEADER::NumberOfEntries, _SYSPTES_HEADER::NumberOfEntriesPeak, _PTE_TRACKER::Offset, _PTE_TRACKER::Page, PAGE_SHIFT, PSLIST_ENTRY, _PTE_TRACKER::StartVa, _PTE_TRACKER::SystemVa, and TRUE.
Referenced by __bcount(), __out_bcount(), and MmMapLockedPagesSpecifyCache().
VOID MiIssueNoPtesBugcheck (IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Definition at line 1053 of file sysptes.c.
References DRIVER_USED_EXCESSIVE_PTES, KeBugCheckEx(), MiGetHighestPteConsumer(), MmNumberOfSystemPtes, MmTotalFreeSystemPtes, NO_MORE_SYSTEM_PTES, NULL, and SystemPteSpace.
Referenced by MiBuildPagedPool(), MiInitializeLargePageSupport(), MiInitializeSystemPtes(), and MmMapLockedPagesSpecifyCache().
PVOID MiMapLockedPagesInUserSpace (IN PMDL MemoryDescriptorList, IN PVOID StartingVa, IN MEMORY_CACHING_TYPE CacheType, IN PVOID BaseVa)
Definition at line 7081 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, BYTE_OFFSET, _MMPFNENTRY::CacheAttribute, _MMVAD_LONG::ControlArea, _MMPFN::e1, _MMPFN::e2, _MMVAD_LONG::EndingVpn, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, ExFreePool(), ExRaiseStatus(), FALSE, _MMVAD_LONG::FirstPrototypePte, _EPROCESS::Flags, _MMPTE::Hard, LOCK_ADDRESS_SPACE, LOCK_PFN, LOCK_WS_UNSAFE, _MMVAD_LONG::LongFlags, _MMVAD_FLAGS2::LongVad, MDL_IO_SPACE, MI_DISABLE_CACHING, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PHYSICAL_VIEW_KEY, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_VA_TO_VPN, MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiCheckForConflictingVadExistence(), MiCreatePhysicalVadRoot(), MiFindEmptyAddressRange(), MiGetPteAddress, MiInsertNode(), MiInsertVad(), MiInsertVadCharges(), MiMakePdeExistAndMakeValid(), MiNonCached, MiNonCachedCollisions, MiNotMapped, MiWriteCombined, MM_EMPTY_LIST, MM_HIGHEST_VAD_ADDRESS, MM_NOIRQL, MM_READWRITE, NonPagedPool, NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::PhysicalVadRoot, _MMVAD_FLAGS::PrivateMemory, _MMVAD_FLAGS::Protection, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, RtlZeroMemory, _MMPFN::ShareCount, _MMVAD_LONG::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_ADDRESS, STATUS_PROCESS_IS_TERMINATING, TRUE, _MMPTE::u, _MMVAD_LONG::u, _MMPFN::u2, _MMVAD_LONG::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, UNLOCK_PFN, UNLOCK_WS_AND_ADDRESS_SPACE, _MI_PHYSICAL_VIEW::Vad, VadDevicePhysicalMemory, _MMVAD_LONG::VadFlags, _MMVAD_LONG::VadFlags2, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, ValidUserPte, and X64K.
Referenced by MmMapLockedPagesSpecifyCache().
VOID MiPteSListExpansionWorker (IN PVOID Context)
Definition at line 1105 of file sysptes.c.
References _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::Active, ASSERT, ExAllocatePoolWithTag, InterlockedExchange(), InterlockedPushEntrySList(), KeGetCurrentIrql(), MI_MAXIMUM_SLIST_PTE_PAGES, NonPagedPool, NULL, PAGE_SIZE, PASSIVE_LEVEL, PSLIST_ENTRY, and _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::SListPages.
Referenced by MiReleaseSystemPtes().
LOGICAL MiRecoverExtraPtes (ULONG NumberOfPtes)
Referenced by MiFeedSysPtePool(), MiGetSystemPteAvailability(), and MiReserveAlignedSystemPtes().
LOGICAL MiRecoverExtraPtes (IN ULONG NumberOfPtes)
Definition at line 3136 of file sysptes.c.
References FALSE, _MMPTE::List, MiAddPtesList, MiAddSystemPtes(), MiLockSystemSpace, MiRecoverSpecialPtes(), MiUnlockSystemSpace, MM_EMPTY_PTE_LIST, MmSystemPteBase, _MMPTE_LIST::NextEntry, SystemPteSpace, TRUE, and _MMPTE::u.
VOID MiReleaseSplitSystemPtes (IN PMMPTE StartingPte, IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Definition at line 2132 of file sysptes.c.
References ASSERT, _RTL_BITMAP::Buffer, ExAcquireSpinLock, ExReleaseSpinLock, MI_CHECK_BIT, MI_SET_BIT, MiGetVirtualAddressMappedByPte, MiPteTrackerLock, MiReleaseSystemPtes(), MmTrackPtes, RtlCheckBit, and SystemPteSpace.
VOID MiReleaseSystemPtes (IN PMMPTE StartingPte, IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Definition at line 1823 of file sysptes.c.
References _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::Active, ASSERT, CriticalWorkQueue, _PTE_QUEUE_POINTER::Data, ExInitializeWorkItem, ExInsertTailNBQueue(), ExQueueWorkItem(), Index, InterlockedCompareExchange(), InterlockedIncrement, KeReadTbFlushTimeStamp(), _MMPTE::List, MI_MAXIMUM_SLIST_PTE_PAGES, MiCheckPteRelease(), MiCountFreeSystemPtes(), MiLockSystemSpace, MiPteSListExpansionWorker(), MiSysPteTimeStamp, MiSystemPteNBHead, MiUnlockSystemSpace, MiZeroMemoryPte, MM_DBG_SYS_PTES, MM_EMPTY_PTE_LIST, MM_MAX_SYSPTE_FREE, MM_MIN_SYSPTE_FREE, MM_PTE_TABLE_LIMIT, MmFirstFreeSystemPte, MmSysPteIndex, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmSystemPteBase, MmTotalFreeSystemPtes, MmTrackPtes, _MMPTE_LIST::NextEntry, _MMPTE_LIST::OneEntry, PackPTEValue(), _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::SListPages, SystemPteSpace, TRUE, _MMPTE::u, and _MM_PTE_SLIST_EXPANSION_WORK_CONTEXT::WorkItem.
Referenced by __out_bcount(), MiAddSystemPtes(), MiAllocatePoolPages(), MiCopyHeaderIfResident(), MiCopyOnWrite(), MiCreateImageFileMap(), MiFeedSysPtePool(), MiFreeNonPagedPool(), MiFreePoolPages(), MiInitializeSystemPtes(), MiLoadImageSection(), MiMapWithLargePages(), MiPhysicalViewRemover(), MiReleaseProcessReferenceToSessionDataPage(), MiReleaseSplitSystemPtes(), MiReloadBootLoadedDrivers(), MiResolveDemandZeroFault(), MiSessionCreateInternal(), MiUnmapLargePages(), MiUnmapSinglePage(), MiUseLargeDriverPage(), MiZeroAwePageWorker(), MiZeroPageWorker(), MmAccessFault(), MmAllocateIndependentPages(), MmCopyToCachedPage(), MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmDeleteKernelStack(), MmFreeIndependentPages(), MmFreeMappingAddress(), MmFreeNonCachedMemory(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmOutSwapProcess(), MmUnloadSystemImage(), MmUnmapIoSpace(), and MmUnmapLockedPages().
VOID MiRemovePteTracker (IN PMDL MemoryDescriptorList OPTIONAL, IN PVOID VirtualAddress, IN PFN_NUMBER NumberOfPtes)
Definition at line 4492 of file iosup.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, _PTE_TRACKER::Count, _SYSPTES_HEADER::Count, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _LIST_ENTRY::Flink, InterlockedPushEntrySList(), KeBugCheckEx(), _PTE_TRACKER::ListEntry, _SYSPTES_HEADER::ListHead, MDL_FREE_EXTRA_PTES, MiMdlsAdjusted, MiPteTrackerLock, MiTrackPtesAborted, NULL, _SYSPTES_HEADER::NumberOfEntries, _PTE_TRACKER::Page, PAGE_ALIGN, PSLIST_ENTRY, RemoveEntryList(), _PTE_TRACKER::StartVa, SYSTEM_PTE_MISUSE, and _PTE_TRACKER::SystemVa.
Referenced by MmFreeMappingAddress(), MmUnmapIoSpace(), and MmUnmapLockedPages().
PMMPTE MiReserveAlignedSystemPtes (IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType, IN ULONG Alignment)
Definition at line 542 of file sysptes.c.
References ASSERT, FALSE, _MMPTE::Hard, _MMPTE::List, _MMPTE::Long, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MiCheckPteReserve(), MiCompareTbFlushTimeStamp(), MiCountFreeSystemPtes(), MiGetVirtualAddressMappedByPte, MiLockSystemSpace, MiRecoverExtraPtes(), MiSysPteTimeStamp, MiUnlockSystemSpace, MM_DBG_SYS_PTES, MM_EMPTY_PTE_LIST, MM_MAXIMUM_FLUSH_COUNT, MmFirstFreeSystemPte, MmPteFailures, MmSystemPteBase, MmTotalFreeSystemPtes, MmTrackPtes, _MMPTE_LIST::NextEntry, NOTHING, NULL, _MMPTE_LIST::OneEntry, PAGE_SHIFT, PAGE_SIZE, PTE_SHIFT, SYSPTES_FLUSH_COUNTER_MASK, SystemPteSpace, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiFeedSysPtePool(), MiMapBBTMemory(), MiMapWithLargePages(), and MiReserveSystemPtes().
PMMPTE MiReserveSystemPtes (IN ULONG NumberOfPtes, IN MMSYSTEM_PTE_POOL_TYPE SystemPtePoolType)
Definition at line 355 of file sysptes.c.
References ASSERT, ExRemoveHeadNBQueue(), _MMPTE::Hard, Index, InterlockedDecrement, _MMPTE::List, MI_FLUSH_ENTIRE_TB, MiCheckPteReserve(), MiCompareTbFlushTimeStamp(), MiFeedSysPtePool(), MiReserveAlignedSystemPtes(), MiSystemPteAllocationFailed, MiSystemPteNBHead, MM_PTE_TABLE_LIMIT, MmSysPteIndex, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmTrackPtes, _MMPTE_LIST::NextEntry, NULL, SYSPTES_FLUSH_COUNTER_MASK, SystemPteSpace, TRUE, _MMPTE::u, UnpackPTEPointer(), UnpackPTETimeStamp(), and _MMPTE_HARDWARE::Valid.
Referenced by __bcount(), __out_bcount(), MiAllocatePoolPages(), MiBuildPagedPool(), MiCopyHeaderIfResident(), MiCopyOnWrite(), MiCreateImageFileMap(), MiInitializeLargePageSupport(), MiInitializeSystemPtes(), MiInitMachineDependent(), MiLoadImageSection(), MiMapSinglePage(), MiReloadBootLoadedDrivers(), MiResolveDemandZeroFault(), MiSessionCreateInternal(), MiZeroAwePageWorker(), MiZeroPageWorker(), MmAccessFault(), MmAllocateIndependentPages(), MmCopyToCachedPage(), MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmMapLockedPagesSpecifyCache(), and MmOutSwapProcess().
VOID MiUnmapLockedPagesInUserSpace (IN PVOID BaseAddress, IN PMDL MemoryDescriptorList)
Definition at line 7536 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, ASSERT64, _MMPTE_FLUSH_LIST::Count, _MMVAD::EndingVpn, ExFreePool(), ExPageLockHandle, FALSE, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_ADDRESS_SPACE, LOCK_PFN, LOCK_WS_UNSAFE, _MMPTE::Long, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_USED_PTES_FROM_HANDLE, MI_GET_USED_PTES_HANDLE, MI_PFN_ELEMENT, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_ZERO_PTE, MiDecrementShareCountInline, MiDeletePte(), MiFlushPteList(), MiGetNextVad, MiGetPdeAddress, MiGetPreviousVad, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiLocateAddress(), MiPhysicalViewRemover(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MM_EMPTY_LIST, MM_MAXIMUM_FLUSH_COUNT, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), NULL, PAGE_SIZE, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMVAD::StartingVpn, _MMPTE::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_PFN, UNLOCK_WS_AND_ADDRESS_SPACE, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, and _MMPTE_HARDWARE::Valid.
Referenced by MmUnmapLockedPages().
ULONG MmGetNumberOfFreeSystemPtes (VOID)
Definition at line 3234 of file sysptes.c.
References _MMPTE::List, MiAddPtesList, MiLockSystemSpace, MiSpecialPoolExtraCount, MiUnlockSystemSpace, MM_EMPTY_PTE_LIST, MmSystemPteBase, MmTotalFreeSystemPtes, _MMPTE_LIST::NextEntry, and _MMPTE::u.
Referenced by NtQuerySystemInformation().
PVOID MmMapLockedPagesSpecifyCache (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in MEMORY_CACHING_TYPE CacheType, __in_opt PVOID RequestedAddress, __in ULONG BugCheckOnFailure, __in MM_PAGE_PRIORITY Priority)
Definition at line 1176 of file sysptes.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, ExRemoveHeadNBQueue(), FALSE, _MMPTE::Hard, HIGH_LEVEL, HighPagePriority, Index, InterlockedDecrement, KeBugCheckEx(), KeIsExecutingDpc(), KernelMode, _MMPTE::List, LOCK_PFN2, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_MAPPING_CAN_FAIL, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_PARTIAL_HAS_BEEN_MAPPED, MDL_SOURCE_IS_NONPAGED_POOL, MEMORY_MANAGEMENT, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DISABLE_CACHING, MI_FLUSH_ENTIRE_TB, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiCheckPteReserve(), MiCompareTbFlushTimeStamp(), MiFeedSysPtePool(), MiGetSystemPteAvailability(), MiGetVirtualAddressMappedByPte, MiInsertPteTracker(), MiIssueNoPtesBugcheck(), MiMapLockedPagesInUserSpace(), MiNonCached, MiNonCachedCollisions, MiNotMapped, MiReserveSystemPtes(), MiSystemPteNBHead, MiWriteCombined, MM_EMPTY_LIST, MM_PTE_TABLE_LIMIT, MmMaximumCacheType, MmSysPteIndex, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmTotalFreeSystemPtes, MmTrackPtes, _MMPTE_LIST::NextEntry, NULL, _MMPTE_HARDWARE::PageFrameNumber, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, RtlGetCallersAddress(), SYSPTES_FLUSH_COUNTER_MASK, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, UnpackPTEPointer(), UnpackPTETimeStamp(), _MMPTE_HARDWARE::Valid, ValidKernelPte, and X64K.
Referenced by MiCloneProcessAddressSpace(), MiDoMappedCopy(), MmMapLockedPages(), and NtStartProfile().
VOID MmUnmapLockedPages (__in PVOID BaseAddress, __in PMDL MemoryDescriptorList)
Definition at line 1634 of file sysptes.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _PTE_QUEUE_POINTER::Data, _MMPFN::e2, ExInsertTailNBQueue(), _MMPTE::Hard, Index, InterlockedExchangeAddSizeT, InterlockedIncrement, KeReadTbFlushTimeStamp(), MDL_FREE_EXTRA_PTES, MDL_MAPPED_TO_SYSTEM_VA, MDL_PARENT_MAPPED_SYSTEM_VA, MDL_PARTIAL_HAS_BEEN_MAPPED, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiCheckPteRelease(), MiGetPteAddress, MiReleaseSystemPtes(), MiRemovePteTracker(), MiSystemPteNBHead, MiUnmapLockedPagesInUserSpace(), MiZeroMemoryPte, MM_HIGHEST_USER_ADDRESS, MM_MAX_SYSPTE_FREE, MM_MIN_SYSPTE_FREE, MM_PTE_TABLE_LIMIT, MmSysPteIndex, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmTotalFreeSystemPtes, MmTrackPtes, PackPTEValue(), PAGE_SHIFT, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
Referenced by CcZeroData(), ExpProfileDelete(), MiCleanSection(), MiCloneProcessAddressSpace(), MiCreateImageFileMap(), MiDoMappedCopy(), MiFlushComplete(), MiFlushSectionInternal(), MiMakeOutswappedPageResident(), MiShutdownSystem(), MiWaitForInPageComplete(), MiWriteComplete(), MiZeroPageFile(), MiZeroPageFileFirstPage(), MmUnlockPages(), and NtStopProfile().
__inline VOID PackPTEValue (IN PPTE_QUEUE_POINTER Entry, IN PMMPTE PointerPte, IN ULONG TimeStamp)
Definition at line 316 of file sysptes.c.
Referenced by MiReleaseSystemPtes(), and MmUnmapLockedPages().
__inline PMMPTE UnpackPTEPointer (IN PPTE_QUEUE_POINTER Entry)
Definition at line 329 of file sysptes.c.
Referenced by MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
__inline ULONG UnpackPTETimeStamp (IN PPTE_QUEUE_POINTER Entry)
Definition at line 346 of file sysptes.c.
Referenced by MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
Variable Documentation
MMPTE MiAddPtesList
Definition at line 69 of file sysptes.c.
Referenced by MiRecoverExtraPtes(), and MmGetNumberOfFreeSystemPtes().
ULONG MiCacheOverride[4]
Definition at line 23 of file iosup.c.
Referenced by __out_bcount(), MiInsertIoSpaceMap(), MiMapLockedPagesInUserSpace(), MiMapSinglePage(), MmMapLockedPagesSpecifyCache(), and MmMapLockedPagesWithReservedMapping().
PVOID MiLowestSystemPteVirtualAddress
Definition at line 62 of file sysptes.c.
Referenced by MiAddSystemPtes(), MiInitializeSystemPtes(), MiRemoveWsle(), and MiUpdateWsle().
PRTL_BITMAP MiPteEndBitmap
Definition at line 73 of file sysptes.c.
ULONG MiPteRangeIndex
Definition at line 84 of file sysptes.c.
Referenced by MiAddExtraSystemPteRanges(), MiIdentifyPfn(), MiInitializeSystemPtes(), and MiUpdateSystemPdes().
MI_PTE_RANGES MiPteRanges[MI_NUMBER_OF_PTE_RANGES]
Definition at line 85 of file sysptes.c.
Referenced by MiIdentifyPfn(), MiUpdateSystemPdes(), and MmInitSystem().
MM_PTE_SLIST_EXPANSION_WORK_CONTEXT MiPteSListExpand
Definition at line 168 of file sysptes.c.
PMMPTE MiPteStart
Definition at line 71 of file sysptes.c.
PRTL_BITMAP MiPteStartBitmap
Definition at line 72 of file sysptes.c.
KSPIN_LOCK MiPteTrackerLock
Definition at line 108 of file iosup.c.
Referenced by MiCheckPteRelease(), MiCheckPteReserve(), MiInitializeIoTrackers(), MiInsertPteTracker(), MiReleaseSplitSystemPtes(), and MiRemovePteTracker().
ULONG MiSpecialPoolExtraCount
Referenced by MmGetNumberOfFreeSystemPtes().
ULONG MiSysPteTimeStamp[MaximumPtePoolTypes]
Definition at line 154 of file sysptes.c.
Referenced by MiReleaseSystemPtes(), and MiReserveAlignedSystemPtes().
ULONG MiSystemPteAllocationFailed
Definition at line 76 of file sysptes.c.
Referenced by MiReserveSystemPtes().
LONG MiSystemPteFreeCount[MM_SYS_PTE_TABLES_MAX]
Definition at line 152 of file sysptes.c.
PVOID MiSystemPteNBHead[MM_SYS_PTE_TABLES_MAX]
Definition at line 151 of file sysptes.c.
Referenced by MiInitializeSystemPtes(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
SLIST_HEADER MiSystemPteSListHead
Definition at line 130 of file sysptes.c.
KSPIN_LOCK MiSystemPteSListHeadLock
Definition at line 129 of file sysptes.c.
Referenced by MiInitializeSystemPtes().
ULONG MmPteFailures[MaximumPtePoolTypes]
Definition at line 68 of file sysptes.c.
Referenced by MiGetSystemPteAvailability(), and MiReserveAlignedSystemPtes().
PMMPTE MmSharedUserDataPte
Definition at line 24 of file mminit.c.
ULONG MmSysPteIndex[MM_SYS_PTE_TABLES_MAX] = {1,2,4,8,MM_PTE_TABLE_LIMIT}
Definition at line 121 of file sysptes.c.
Referenced by MiCheckPteRelease(), MiFeedSysPtePool(), MiInitializeSystemPtes(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
ULONG MmSysPteListBySizeCount[MM_SYS_PTE_TABLES_MAX]
Definition at line 135 of file sysptes.c.
Referenced by MiGetSystemPteAvailability(), MiGetSystemPteListCount(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
ULONG MmSysPteMinimumFree[MM_SYS_PTE_TABLES_MAX] = {100,50,30,20,20}
Definition at line 125 of file sysptes.c.
Referenced by MiGetSystemPteAvailability(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
UCHAR MmSysPteTables[MM_PTE_TABLE_LIMIT+1] = {0,0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4}
Definition at line 123 of file sysptes.c.
Referenced by MiCheckPteRelease(), MiGetSystemPteAvailability(), MiGetSystemPteListCount(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
PMMPTE MmSystemPtesEnd[MaximumPtePoolTypes]
Definition at line 67 of file sysptes.c.
PMMPTE MmSystemPtesStart[MaximumPtePoolTypes]
Definition at line 66 of file sysptes.c.
ULONG MmTotalFreeSystemPtes[MaximumPtePoolTypes]
Definition at line 65 of file sysptes.c.
Referenced by MiFeedSysPtePool(), MiGetSystemPteAvailability(), MiInitializeSystemPtes(), MiIssueNoPtesBugcheck(), MiReleaseSystemPtes(), MiReserveAlignedSystemPtes(), MiUseLargeDriverPage(), MmGetNumberOfFreeSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
ULONG MmTotalSystemPtes
Definition at line 64 of file sysptes.c.
Referenced by MiIncrementSystemPtes(), and MiInitializeSystemPtes().