Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/se.h File Reference
se.h File Reference
#include <ntlsa.h>
Data Structures
struct _ACCESS_STATE
struct _AUX_ACCESS_DATA
struct _INITIAL_PRIVILEGE_SET
struct _SE_AUDITING_STATE
struct _SE_EXPORTS
struct _SE_PROCESS_AUDIT_INFO
struct _SECURITY_SUBJECT_CONTEXT
Macros
#define INITIAL_PRIVILEGE_COUNT 3
#define SE_BACKUP_PRIVILEGES_CHECKED 0x00000010
#define SE_DEFAULT_SECURITY_QUOTA 2048
#define SeAssertMappedCanonicalAccess(AccessMask)
#define SeComputeDeniedAccesses(GrantedAccess, DesiredAccess) ((~(GrantedAccess)) & (DesiredAccess))
#define SeComputeGrantedAccesses(GrantedAccess, DesiredAccess) ((GrantedAccess) & (DesiredAccess))
#define SeComputeSecurityQuota(Size)
#define SeDeleteClientSecurity(C)
*++
#define SeLengthSid(Sid) (8 + (4 * ((SID *)Sid)->SubAuthorityCount))
#define SeQuerySubjectContextToken(SubjectContext)
#define SeSameToken(TC1, TC2)
#define SeStopImpersonatingClient() PsRevertToSelf()
*++
#define TOKEN_HAS_ADMIN_GROUP 0x08
#define TOKEN_HAS_BACKUP_PRIVILEGE 0x02
#define TOKEN_HAS_IMPERSONATE_PRIVILEGE 0x80
#define TOKEN_HAS_RESTORE_PRIVILEGE 0x04
#define TOKEN_HAS_TRAVERSE_PRIVILEGE 0x01
#define TOKEN_IS_RESTRICTED 0x10
#define TOKEN_SANDBOX_INERT 0x40
#define TOKEN_SESSION_NOT_REFERENCED 0x20
Typedefs
typedef struct _ACCESS_STATE ACCESS_STATE
typedef struct _AUX_ACCESS_DATA AUX_ACCESS_DATA
typedef struct _INITIAL_PRIVILEGE_SET INITIAL_PRIVILEGE_SET
typedef struct _ACCESS_STATE * PACCESS_STATE
typedef struct _AUX_ACCESS_DATA * PAUX_ACCESS_DATA
typedef struct _INITIAL_PRIVILEGE_SET * PINITIAL_PRIVILEGE_SET
typedef struct _SE_AUDITING_STATE * PSE_AUDITING_STATE
typedef struct _SE_EXPORTS * PSE_EXPORTS
typedef NTSTATUS(* PSE_LOGON_SESSION_TERMINATED_ROUTINE) (IN PLUID LogonId)
typedef struct _SE_PROCESS_AUDIT_INFO * PSE_PROCESS_AUDIT_INFO
typedef enum _SECURITY_OPERATION_CODE * PSECURITY_OPERATION_CODE
typedef struct _SECURITY_SUBJECT_CONTEXT * PSECURITY_SUBJECT_CONTEXT
typedef struct _SE_AUDITING_STATE SE_AUDITING_STATE
typedef struct _SE_EXPORTS SE_EXPORTS
typedef struct _SE_PROCESS_AUDIT_INFO SE_PROCESS_AUDIT_INFO
typedef enum _SECURITY_OPERATION_CODE SECURITY_OPERATION_CODE
typedef struct _SECURITY_SUBJECT_CONTEXT SECURITY_SUBJECT_CONTEXT
Enumerations
enum _SECURITY_OPERATION_CODE { SetSecurityDescriptor, QuerySecurityDescriptor, DeleteSecurityDescriptor, AssignSecurityDescriptor }
Functions
NTKERNELAPI BOOLEAN SeAccessCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in BOOLEAN SubjectContextLocked, __in ACCESS_MASK DesiredAccess, __in ACCESS_MASK PreviouslyGrantedAccess, __deref_out_opt PPRIVILEGE_SET *Privileges, __in PGENERIC_MAPPING GenericMapping, __in KPROCESSOR_MODE AccessMode, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
VOID SeAddSaclToProcess (IN PEPROCESS Process, IN PACCESS_TOKEN Token, IN PVOID Reserved)
NTKERNELAPI NTSTATUS SeAppendPrivileges (__inout PACCESS_STATE AccessState, __in PPRIVILEGE_SET Privileges)
VOID SeAssignPrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN Token)
NTKERNELAPI NTSTATUS SeAssignSecurity (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR *NewDescriptor, __in BOOLEAN IsDirectoryObject, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
NTKERNELAPI NTSTATUS SeAssignSecurityEx (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR *NewDescriptor, __in_opt GUID *ObjectType, __in BOOLEAN IsDirectoryObject, __in ULONG AutoInheritFlags, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
NTSTATUS SeAssignWorldSecurityDescriptor (__inout_bcount_part(*Length,*Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __in PSECURITY_INFORMATION SecurityInformation)
VOID SeAuditHandleCreation (__in PACCESS_STATE AccessState, __in HANDLE Handle)
VOID SeAuditHandleDuplication (__in PVOID SourceHandle, __in PVOID NewHandle, __in PEPROCESS SourceProcess, __in PEPROCESS TargetProcess)
NTKERNELAPI VOID SeAuditHardLinkCreation (__in PUNICODE_STRING FileName, __in PUNICODE_STRING LinkName, __in BOOLEAN bSuccess)
NTKERNELAPI BOOLEAN SeAuditingFileEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
NTKERNELAPI BOOLEAN SeAuditingFileEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
NTKERNELAPI BOOLEAN SeAuditingFileOrGlobalEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
NTKERNELAPI BOOLEAN SeAuditingHardLinkEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
NTKERNELAPI BOOLEAN SeAuditingHardLinkEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
VOID SeAuditLPCInvalidUse (__in PUNICODE_STRING LpcCallName, __in PUNICODE_STRING LpcServerPort)
VOID SeAuditProcessCreation (__in PEPROCESS Process)
VOID SeAuditProcessExit (__in PEPROCESS Process)
VOID SeAuditSystemTimeChange (__in LARGE_INTEGER OldTime, __in LARGE_INTEGER NewTime)
NTSTATUS SeCaptureAcl (__in PACL InputAcl, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(*AlignedAclSize) PACL *CapturedAcl, __out PULONG AlignedAclSize)
NTSTATUS SeCaptureAuditPolicy (__in PTOKEN_AUDIT_POLICY Policy, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PTOKEN_AUDIT_POLICY *CapturedPolicy)
NTSTATUS SeCaptureLuidAndAttributesArray (__in_ecount(ArrayCount) PLUID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(*AlignedArraySize) PLUID_AND_ATTRIBUTES *CapturedArray, __out PULONG AlignedArraySize)
NTKERNELAPI NTSTATUS SeCaptureSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSECURITY_DESCRIPTOR *OutputSecurityDescriptor)
NTSTATUS SeCaptureSecurityQos (__in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE RequestorMode, __out PBOOLEAN SecurityQosPresent, __out PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
NTSTATUS SeCaptureSid (__in PSID InputSid, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSID *CapturedSid)
NTSTATUS SeCaptureSidAndAttributesArray (__in_ecount(ArrayCount) PSID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(AlignedArraySize) PSID_AND_ATTRIBUTES *CapturedArray, __out PULONG AlignedArraySize)
NTKERNELAPI VOID SeCaptureSubjectContext (__out PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SeCaptureSubjectContextEx (__in PETHREAD Thread, __in PEPROCESS Process, __out PSECURITY_SUBJECT_CONTEXT SubjectContext)
BOOLEAN SeCheckAuditPrivilege (__in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE PreviousMode)
BOOLEAN SeCheckPrivilegedObject (__in LUID PrivilegeValue, __in HANDLE ObjectHandle, __in ACCESS_MASK DesiredAccess, __in KPROCESSOR_MODE PreviousMode)
VOID SeCloseObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle, __in BOOLEAN GenerateOnClose)
NTSTATUS SeComputeQuotaInformationSize (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __out PULONG Size)
NTSTATUS SeCopyClientToken (__in PACCESS_TOKEN ClientToken, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, __in KPROCESSOR_MODE RequestorMode, __deref_out PACCESS_TOKEN *DuplicateToken)
NTKERNELAPI NTSTATUS SeCreateAccessState (__out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in PGENERIC_MAPPING GenericMapping)
NTSTATUS SeCreateAccessStateEx (__in_opt PETHREAD Thread, __in PEPROCESS Process, __out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in_opt PGENERIC_MAPPING GenericMapping)
NTKERNELAPI NTSTATUS SeCreateClientSecurity (__in PETHREAD ClientThread, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN RemoteSession, __out PSECURITY_CLIENT_CONTEXT ClientContext)
NTKERNELAPI NTSTATUS SeCreateClientSecurityFromSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN ServerIsRemote, __out PSECURITY_CLIENT_CONTEXT ClientContext)
VOID SeCreateInstanceAuditAlarm (IN PLUID OperationID OPTIONAL, IN PVOID Object, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, IN KPROCESSOR_MODE AccessMode)
VOID SeCreateObjectAuditAlarm (IN PLUID OperationID OPTIONAL, IN PVOID Object, IN PUNICODE_STRING ComponentName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, OUT PBOOLEAN AuditPerformed, IN KPROCESSOR_MODE AccessMode)
VOID SeDeassignPrimaryToken (__in PEPROCESS Process)
NTKERNELAPI NTSTATUS SeDeassignSecurity (__deref_inout PSECURITY_DESCRIPTOR *SecurityDescriptor)
NTSTATUS SeDefaultObjectMethod (__in PVOID Object, __in SECURITY_OPERATION_CODE OperationCode, __in PSECURITY_INFORMATION SecurityInformation, __inout PSECURITY_DESCRIPTOR SecurityDescriptor, __inout_opt PULONG CapturedLength, __deref_inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
NTKERNELAPI VOID SeDeleteAccessState (__in PACCESS_STATE AccessState)
NTKERNELAPI VOID SeDeleteObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle)
NTKERNELAPI BOOLEAN FASTCALL SeDetailedAuditingWithToken (__in_opt PACCESS_TOKEN AccessToken)
NTSTATUS SeExchangePrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN NewAccessToken, __deref_out PACCESS_TOKEN *OldAccessToken)
NTSTATUS SeFastFilterToken (__in PACCESS_TOKEN ExistingToken, __in KPROCESSOR_MODE RequestorMode, __in ULONG Flags, __in ULONG GroupCount, __in_ecount_opt(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount_opt(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete, __in ULONG SidCount, __in_ecount_opt(SidCount) PSID_AND_ATTRIBUTES RestrictedSids, __in ULONG SidLength, __deref_out PACCESS_TOKEN *FilteredToken)
BOOLEAN SeFastTraverseCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PACCESS_STATE AccessState, __in ACCESS_MASK TraverseAccess, __in KPROCESSOR_MODE AccessMode)
NTKERNELAPI NTSTATUS SeFilterToken (__in PACCESS_TOKEN ExistingToken, __in ULONG Flags, __in_opt PTOKEN_GROUPS SidsToDisable, __in_opt PTOKEN_PRIVILEGES PrivilegesToDelete, __in_opt PTOKEN_GROUPS RestrictedSids, __deref_out PACCESS_TOKEN *FilteredToken)
VOID SeFreeCapturedSecurityQos (__in PVOID SecurityQos)
NTKERNELAPI VOID SeFreePrivileges (__in PPRIVILEGE_SET Privileges)
VOID SeGenerateMessage (IN PSTRING ObjectName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, IN HANDLE AuditPort, IN HANDLE AlarmPort, IN KPROCESSOR_MODE AccessMode)
VOID SeGetTokenControlInformation (__in PACCESS_TOKEN Token, __out PTOKEN_CONTROL TokenControl)
NTKERNELAPI VOID SeImpersonateClient (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
NTKERNELAPI NTSTATUS SeImpersonateClientEx (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
NTSTATUS SeInitializeProcessAuditName (__in __typefix(PFILE_OBJECT) PVOID FileObject, __in BOOLEAN bIgnoreAuditPolicy, __deref_out POBJECT_NAME_INFORMATION *pAuditName)
BOOLEAN SeInitSystem (VOID)
NTSTATUS SeIsChildToken (__in HANDLE Token, __out PBOOLEAN IsChild)
NTSTATUS SeIsChildTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsChild)
NTSTATUS SeIsSiblingToken (__in HANDLE Token, __out PBOOLEAN IsSibling)
NTSTATUS SeIsSiblingTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsSibling)
NTSTATUS SeLocateProcessImageName (__in PEPROCESS Process, __deref_out PUNICODE_STRING *pImageFileName)
NTKERNELAPI VOID SeLockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
PACCESS_TOKEN SeMakeAnonymousLogonToken (VOID)
PACCESS_TOKEN SeMakeAnonymousLogonTokenNoEveryone (VOID)
PACCESS_TOKEN SeMakeSystemToken (VOID)
NTKERNELAPI NTSTATUS SeMarkLogonSessionForTerminationNotification (IN PLUID LogonId)
VOID SeMaximumAuditMask (IN PACL Sacl, IN ACCESS_MASK GrantedAccess, IN PACCESS_TOKEN Token, OUT PACCESS_MASK pAuditMask)
VOID SeObjectReferenceAuditAlarm (__in_opt PLUID OperationID, __in PVOID Object, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in_opt PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
NTKERNELAPI VOID SeOpenObjectAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
NTKERNELAPI VOID SeOpenObjectForDeleteAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
VOID SeOperationAuditAlarm (__in_opt PUNICODE_STRING CapturedSubsystemName, __in PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in ACCESS_MASK AuditMask, __in_opt PSID UserSid)
NTKERNELAPI BOOLEAN SePrivilegeCheck (__inout PPRIVILEGE_SET RequiredPrivileges, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE AccessMode)
VOID SePrivilegedServiceAuditAlarm (__in_opt PUNICODE_STRING ServiceName, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
NTKERNELAPI VOID SePrivilegeObjectAuditAlarm (__in HANDLE Handle, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
NTSTATUS SePrivilegePolicyCheck (__inout PACCESS_MASK RemainingDesiredAccess, __inout PACCESS_MASK PreviouslyGrantedAccess, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in_opt PACCESS_TOKEN ExplicitToken, __deref_out PPRIVILEGE_SET *PrivilegeSet, __in KPROCESSOR_MODE PreviousMode)
NTKERNELAPI NTSTATUS SeQueryAuthenticationIdToken (__in PACCESS_TOKEN Token, __out PLUID AuthenticationId)
NTKERNELAPI NTSTATUS SeQueryInformationToken (__in PACCESS_TOKEN Token, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __deref_out PVOID *TokenInformation)
VOID SeQuerySecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
NTKERNELAPI NTSTATUS SeQuerySecurityDescriptorInfo (__in PSECURITY_INFORMATION SecurityInformation, __out_bcount(*Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __deref_inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor)
NTKERNELAPI NTSTATUS SeQuerySessionIdToken (__in PACCESS_TOKEN Token, __out PULONG SessionId)
NTKERNELAPI NTSTATUS SeRegisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
VOID SeReleaseAcl (__in PACL CapturedAcl, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseAuditPolicy (__in PTOKEN_AUDIT_POLICY CapturedPolicy, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseLuidAndAttributesArray (__in PLUID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
NTKERNELAPI VOID SeReleaseSecurityDescriptor (__in PSECURITY_DESCRIPTOR CapturedSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseSid (__in PSID CapturedSid, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseSidAndAttributesArray (__in PSID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
NTKERNELAPI VOID SeReleaseSubjectContext (__inout PSECURITY_SUBJECT_CONTEXT SubjectContext)
NTSTATUS SeReportSecurityEvent (__in ULONG Flags, __in PUNICODE_STRING SourceName, __in_opt PSID UserSid, __in PSE_ADT_PARAMETER_ARRAY AuditParameters)
BOOLEAN SeRmInitPhase1 (VOID)
VOID SeSetAccessStateGenericMapping (__inout PACCESS_STATE AccessState, __in PGENERIC_MAPPING GenericMapping)
NTSTATUS SeSetAuditParameter (__inout PSE_ADT_PARAMETER_ARRAY AuditParameters, __in SE_ADT_PARAMETER_TYPE Type, __in ULONG Index, __in PVOID Data)
VOID SeSetSecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
NTKERNELAPI NTSTATUS SeSetSecurityDescriptorInfo (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
NTKERNELAPI NTSTATUS SeSetSecurityDescriptorInfoEx (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in ULONG AutoInheritFlags, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
NTKERNELAPI NTSTATUS SeSetSessionIdToken (__in PACCESS_TOKEN Token, __in ULONG SessionId)
NTKERNELAPI BOOLEAN SeSinglePrivilegeCheck (__in LUID PrivilegeValue, __in KPROCESSOR_MODE PreviousMode)
NTSTATUS SeSubProcessToken (__in PACCESS_TOKEN ParentToken, __deref_out PACCESS_TOKEN *ChildToken, __in BOOLEAN MarkAsActive, __in ULONG SessionId)
NTKERNELAPI NTSTATUS SeTokenCanImpersonate (__in PACCESS_TOKEN ProcessToken, __in PACCESS_TOKEN Token, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
SECURITY_IMPERSONATION_LEVEL SeTokenImpersonationLevel (__in PACCESS_TOKEN Token)
NTKERNELAPI BOOLEAN SeTokenIsAdmin (__in PACCESS_TOKEN Token)
NTKERNELAPI BOOLEAN SeTokenIsRestricted (__in PACCESS_TOKEN Token)
NTKERNELAPI TOKEN_TYPE SeTokenType (__in PACCESS_TOKEN Token)
NTKERNELAPI VOID SeUnlockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
NTKERNELAPI NTSTATUS SeUnregisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
NTSTATUS SeUpdateClientSecurity (IN PETHREAD ClientThread, IN OUT PSECURITY_CLIENT_CONTEXT ClientContext, OUT PBOOLEAN ChangesMade, OUT PBOOLEAN NewToken)
NTKERNELAPI BOOLEAN SeValidSecurityDescriptor (__in ULONG Length, __in_bcount(Length) PSECURITY_DESCRIPTOR SecurityDescriptor)
Variables
PSID SeAliasAccountOpsSid
PSID SeAliasAdminsSid
PSID SeAliasBackupOpsSid
PSID SeAliasGuestsSid
PSID SeAliasPowerUsersSid
PSID SeAliasPrintOpsSid
PSID SeAliasSystemOpsSid
PSID SeAliasUsersSid
const LUID SeAnonymousAuthenticationId
PSID SeAnonymousLogonSid
PACCESS_TOKEN SeAnonymousLogonToken
PACCESS_TOKEN SeAnonymousLogonTokenNoEveryone
LUID SeAssignPrimaryTokenPrivilege
SE_AUDITING_STATE SeAuditingState []
LUID SeAuditPrivilege
PSID SeAuthenticatedUsersSid
LUID SeBackupPrivilege
PSID SeBatchSid
LUID SeChangeNotifyPrivilege
LUID SeCreateGlobalPrivilege
LUID SeCreatePagefilePrivilege
LUID SeCreatePermanentPrivilege
LUID SeCreateTokenPrivilege
PSID SeCreatorGroupServerSid
PSID SeCreatorGroupSid
PSID SeCreatorOwnerServerSid
PSID SeCreatorOwnerSid
LUID SeDebugPrivilege
PSID SeDialupSid
LUID SeEnableDelegationPrivilege
NTKERNELAPI PSE_EXPORTS SeExports
LUID SeImpersonatePrivilege
LUID SeIncreaseBasePriorityPrivilege
LUID SeIncreaseQuotaPrivilege
PSID SeInteractiveSid
LUID SeLoadDriverPrivilege
PACL SeLocalServicePublicDacl
PSECURITY_DESCRIPTOR SeLocalServicePublicSd
PSID SeLocalSid
PSID SeLocalSystemSid
LUID SeLockMemoryPrivilege
LUID SeManageVolumePrivilege
PSID SeNetworkSid
PSID SeNtAuthoritySid
PSID SeNullSid
PSID SePrincipalSelfSid
LUID SeProfileSingleProcessPrivilege
PACL SePublicDefaultDacl
PSECURITY_DESCRIPTOR SePublicDefaultSd
PACL SePublicDefaultUnrestrictedDacl
PSECURITY_DESCRIPTOR SePublicDefaultUnrestrictedSd
PACL SePublicOpenDacl
PSECURITY_DESCRIPTOR SePublicOpenSd
PACL SePublicOpenUnrestrictedDacl
PSECURITY_DESCRIPTOR SePublicOpenUnrestrictedSd
LUID SeRemoteShutdownPrivilege
LUID SeRestorePrivilege
PSID SeRestrictedSid
LUID SeSecurityPrivilege
LUID SeShutdownPrivilege
const UNICODE_STRING SeSubsystemName
LUID SeSyncAgentPrivilege
const LUID SeSystemAuthenticationId
PACL SeSystemDefaultDacl
PSECURITY_DESCRIPTOR SeSystemDefaultSd
LUID SeSystemEnvironmentPrivilege
LUID SeSystemProfilePrivilege
LUID SeSystemtimePrivilege
const TOKEN_SOURCE SeSystemTokenSource
LUID SeTakeOwnershipPrivilege
LUID SeTcbPrivilege
struct _OBJECT_TYPE * SeTokenObjectType
LUID SeUndockPrivilege
PACL SeUnrestrictedDacl
LUID SeUnsolicitedInputPrivilege
PSID SeWorldSid
Macro Definition Documentation
#define INITIAL_PRIVILEGE_COUNT 3
Definition at line 146 of file se.h.
Referenced by SeAppendPrivileges().
#define SE_BACKUP_PRIVILEGES_CHECKED 0x00000010
Definition at line 84 of file se.h.
Referenced by IopCheckBackupRestorePrivilege(), and IopParseDevice().
#define SE_DEFAULT_SECURITY_QUOTA 2048
Definition at line 58 of file se.h.
Referenced by ObpAllocateObject(), ObpChargeQuotaForObject(), ObpFreeObject(), and ObValidateSecurityQuota().
#define SeAssertMappedCanonicalAccess (AccessMask)
Value:
ASSERT(!((AccessMask) &                                       \
            ( GENERIC_READ        |                                  \
              GENERIC_WRITE       |                                  \
              GENERIC_EXECUTE     |                                  \
              GENERIC_ALL ))                                         \
          )
Definition at line 671 of file se.h.
Referenced by SeAccessCheck(), and SepAccessCheck().
#define SeComputeDeniedAccesses (GrantedAccess, DesiredAccess) ((~(GrantedAccess)) & (DesiredAccess))
Definition at line 497 of file se.h.
Referenced by IoCheckDesiredAccess(), IoCheckFunctionAccess(), NtSignalAndWaitForSingleObject(), ObpWaitForMultipleObjects(), and ObReferenceObjectByHandle().
#define SeComputeGrantedAccesses (GrantedAccess, DesiredAccess) ((GrantedAccess) & (DesiredAccess))
Definition at line 532 of file se.h.
Referenced by IoCheckFunctionAccess(), IopXxxControlFile(), IoValidateDeviceIoControlAccess(), NtFlushBuffersFile(), NtLockFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), ObReferenceFileObjectForWrite(), WmipStartLogger(), and WmiUpdateTrace().
#define SeComputeSecurityQuota (Size)
Value:
(\
       ((( Size ) * 2 )  > SE_DEFAULT_SECURITY_QUOTA) ?                \
                    (( Size ) * 2 ) : SE_DEFAULT_SECURITY_QUOTA        \
    )
Definition at line 697 of file se.h.
Referenced by ObpCaptureObjectCreateInformation().
#define SeDeleteClientSecurity (C)
Value:
{                                           \
            if (SeTokenType((C)->ClientToken) == TokenPrimary) {               \
                PsDereferencePrimaryToken( (C)->ClientToken );                 \
            } else {                                                           \
                PsDereferenceImpersonationToken( (C)->ClientToken );           \
            }                                                                  \
        }
*++
Definition at line 633 of file se.h.
Referenced by CmLoadKey(), LpcpFreePortClientSecurity(), NtImpersonateThread(), and WmipCreateLogFile().
#define SeLengthSid (Sid) (8 + (4 * ((SID *)Sid)->SubAuthorityCount))
Definition at line 558 of file se.h.
Referenced by CmpHiveRootSecurityDescriptor(), NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtQueryInformationToken(), NtSetInformationToken(), ObInitSystem(), RtlAddCompoundAce(), RtlCopySid(), RtlCopySidAndAttributesArray(), RtlEqualSid(), RtlLengthSecurityDescriptor(), RtlLengthSid(), RtlpAddKnownAce(), RtlpAddKnownObjectAce(), RtlpConvertToAutoInheritSecurityObject(), RtlpCopyEffectiveAce(), RtlpCreateServerAcl(), RtlpNewSecurityObject(), RtlpQuerySecurityDescriptor(), RtlpSetSecurityObject(), RtlSelfRelativeToAbsoluteSD(), RtlValidAcl(), RtlValidRelativeSecurityDescriptor(), SeAssignWorldSecurityDescriptor(), SeComputeQuotaInformationSize(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepAdjustGroups(), SepAppendDefaultDacl(), SepAppendPrimaryGroup(), SepCreateImpersonationTokenDacl(), SepDuplicateToken(), SepExamineSacl(), SepExamineSaclEx(), SepExpandDynamic(), SepFilterToken(), SepFreeDefaultDacl(), SepFreePrimaryGroup(), SepInitProcessAuditSd(), SepInitSystemDacls(), SeQueryInformationToken(), SeQuerySecurityDescriptorInfo(), SeRmInitPhase1(), SeSetAuditParameter(), SeValidSecurityDescriptor(), WmipCreateAdminSD(), WmipInitializeSecurity(), and WmiTraceProcess().
#define SeQuerySubjectContextToken (SubjectContext)
Value:
(ARGUMENT_PRESENT(((PSECURITY_SUBJECT_CONTEXT) SubjectContext)->ClientToken) ? \
            ((PSECURITY_SUBJECT_CONTEXT) SubjectContext)->ClientToken : \
            ((PSECURITY_SUBJECT_CONTEXT) SubjectContext)->PrimaryToken )
Definition at line 753 of file se.h.
Referenced by NtSetUuidSeed(), ObDuplicateObject(), and SeCreateClientSecurityFromSubjectContext().
#define SeSameToken (TC1, TC2)
Value:
(\
        ((TC1)->TokenId.HighPart == (TC2)->TokenId.HighPart)               && \
        ((TC1)->TokenId.LowPart  == (TC2)->TokenId.LowPart)                && \
        (RtlEqualLuid(&(TC1)->AuthenticationId,&(TC2)->AuthenticationId))     \
        )
Definition at line 597 of file se.h.
#define SeStopImpersonatingClient () PsRevertToSelf()
*++
Definition at line 667 of file se.h.
#define TOKEN_HAS_ADMIN_GROUP 0x08
Definition at line 71 of file se.h.
Referenced by SepCreateToken(), SepMakeTokenEffectiveOnly(), SepRemoveDisabledGroupsAndPrivileges(), and SeTokenIsAdmin().
#define TOKEN_HAS_BACKUP_PRIVILEGE 0x02
Definition at line 69 of file se.h.
Referenced by IopCheckBackupRestorePrivilege(), and SepAdjustPrivileges().
#define TOKEN_HAS_IMPERSONATE_PRIVILEGE 0x80
Definition at line 75 of file se.h.
Referenced by SepAdjustPrivileges(), SepCreateToken(), SepRemoveDisabledGroupsAndPrivileges(), and SeTokenCanImpersonate().
#define TOKEN_HAS_RESTORE_PRIVILEGE 0x04
Definition at line 70 of file se.h.
Referenced by IopCheckBackupRestorePrivilege(), and SepAdjustPrivileges().
#define TOKEN_HAS_TRAVERSE_PRIVILEGE 0x01
Definition at line 68 of file se.h.
Referenced by IopParseDevice(), ObpLookupObjectName(), SeCreateAccessStateEx(), SepAdjustPrivileges(), SepCreateToken(), and SepRemoveDisabledGroupsAndPrivileges().
#define TOKEN_IS_RESTRICTED 0x10
Definition at line 72 of file se.h.
Referenced by SeFastTraverseCheck(), SepFilterToken(), SepTokenIsOwner(), and SeTokenIsRestricted().
#define TOKEN_SANDBOX_INERT 0x40
Definition at line 74 of file se.h.
Referenced by NtQueryInformationToken(), and SepFilterToken().
#define TOKEN_SESSION_NOT_REFERENCED 0x20
Definition at line 73 of file se.h.
Referenced by NtSetInformationToken(), SepCreateToken(), SepDuplicateLogonSessionReference(), SepDuplicateToken(), SepFilterToken(), and SepTokenDeleteMethod().
Typedef Documentation
typedef struct _ACCESS_STATE ACCESS_STATE
typedef struct _AUX_ACCESS_DATA AUX_ACCESS_DATA
typedef struct _INITIAL_PRIVILEGE_SET INITIAL_PRIVILEGE_SET
typedef struct _ACCESS_STATE * PACCESS_STATE
typedef struct _AUX_ACCESS_DATA * PAUX_ACCESS_DATA
typedef struct _INITIAL_PRIVILEGE_SET * PINITIAL_PRIVILEGE_SET
typedef struct _SE_AUDITING_STATE * PSE_AUDITING_STATE
typedef struct _SE_EXPORTS * PSE_EXPORTS
typedef NTSTATUS(* PSE_LOGON_SESSION_TERMINATED_ROUTINE) (IN PLUID LogonId)
Definition at line 451 of file se.h.
typedef struct _SE_PROCESS_AUDIT_INFO * PSE_PROCESS_AUDIT_INFO
typedef enum _SECURITY_OPERATION_CODE * PSECURITY_OPERATION_CODE
typedef struct _SECURITY_SUBJECT_CONTEXT * PSECURITY_SUBJECT_CONTEXT
typedef struct _SE_AUDITING_STATE SE_AUDITING_STATE
typedef struct _SE_EXPORTS SE_EXPORTS
typedef struct _SE_PROCESS_AUDIT_INFO SE_PROCESS_AUDIT_INFO
typedef enum _SECURITY_OPERATION_CODE SECURITY_OPERATION_CODE
typedef struct _SECURITY_SUBJECT_CONTEXT SECURITY_SUBJECT_CONTEXT
Enumeration Type Documentation
enum _SECURITY_OPERATION_CODE
Enumerator
SetSecurityDescriptor
QuerySecurityDescriptor
DeleteSecurityDescriptor
AssignSecurityDescriptor
Definition at line 39 of file se.h.
Function Documentation
NTKERNELAPI BOOLEAN SeAccessCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in BOOLEAN SubjectContextLocked, __in ACCESS_MASK DesiredAccess, __in ACCESS_MASK PreviouslyGrantedAccess, __deref_out_opt PPRIVILEGE_SET * Privileges, __in PGENERIC_MAPPING GenericMapping, __in KPROCESSOR_MODE AccessMode, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
Definition at line 3318 of file accessck.c.
References DbgPrint(), EffectiveToken, FALSE, KernelMode, MAXIMUM_ALLOWED, NULL, PAGED_CODE, READ_CONTROL, SeAssertMappedCanonicalAccess, SecurityImpersonation, SeLockSubjectContext(), SepAccessCheck(), SepTokenIsOwner(), SeUnlockSubjectContext(), STATUS_ACCESS_DENIED, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_SUCCESS, TRUE, and WRITE_DAC.
Referenced by CmpCheckCreateAccess(), CmpCheckKeyAccess(), CmpCheckNotifyAccess(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), PspCreateProcess(), PspCreateThread(), PspSetPrimaryToken(), and WmipCheckGuidAccess().
VOID SeAddSaclToProcess (IN PEPROCESS Process, IN PACCESS_TOKEN Token, IN PVOID Reserved)
NTKERNELAPI NTSTATUS SeAppendPrivileges (__inout PACCESS_STATE AccessState, __in PPRIVILEGE_SET Privileges)
Definition at line 323 of file seastate.c.
References ExAllocatePoolWithTag, ExFreePool(), INITIAL_PRIVILEGE_COUNT, NULL, PAGED_CODE, PagedPool, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, RtlCopyMemory, SepConcatenatePrivileges(), SepPrivilegeSetSize, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by IopCheckBackupRestorePrivilege(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckTraverseAccess(), and ObpIncrementHandleCount().
VOID SeAssignPrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN Token)
Definition at line 502 of file token.c.
References ASSERT, ExFastRefObjectNull(), NULL, ObInitializeFastReference(), ObReferenceObject, PAGED_CODE, SeDeassignPrimaryToken(), SeDetailedAuditingWithToken(), SepAuditAssignPrimaryToken(), Status, _TOKEN::TokenInUse, TokenPrimary, _TOKEN::TokenType, and TRUE.
Referenced by PspCreateProcess(), and PspInitializeProcessSecurity().
NTKERNELAPI NTSTATUS SeAssignSecurity (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR * NewDescriptor, __in BOOLEAN IsDirectoryObject, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
Definition at line 76 of file seassign.c.
References ARGUMENT_PRESENT, NT_SUCCESS, NULL, PAGED_CODE, RtlpNewSecurityObject(), SE_DACL_AUTO_INHERITED, SE_DACL_PRESENT, SE_SACL_AUTO_INHERITED, SE_SACL_PRESENT, SEF_DACL_AUTO_INHERIT, SEF_SACL_AUTO_INHERIT, Status, and UNREFERENCED_PARAMETER.
Referenced by CmpDoCreateChild(), and ObAssignSecurity().
NTKERNELAPI NTSTATUS SeAssignSecurityEx (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR * NewDescriptor, __in_opt GUID * ObjectType, __in BOOLEAN IsDirectoryObject, __in ULONG AutoInheritFlags, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
Definition at line 216 of file seassign.c.
References ARGUMENT_PRESENT, NT_SUCCESS, NULL, PAGED_CODE, RtlpNewSecurityObject(), Status, and UNREFERENCED_PARAMETER.
NTSTATUS SeAssignWorldSecurityDescriptor (__inout_bcount_part *,*Length PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __in PSECURITY_INFORMATION SecurityInformation)
Definition at line 519 of file seassign.c.
References ARGUMENT_PRESENT, DACL_SECURITY_INFORMATION, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, NT_SUCCESS, _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlPointerToOffset, RtlpSetControlBits, SACL_SECURITY_INFORMATION, SE_DACL_PRESENT, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SeWorldSid, Status, STATUS_ACCESS_DENIED, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by IopGetSetSecurityObject().
VOID SeAuditHandleCreation (__in PACCESS_STATE AccessState, __in HANDLE Handle)
Definition at line 3478 of file seaudit.c.
References ASSERT, AuditCategoryObjectAccess, DBG, FALSE, Handle, IsValidPrivilegeCount, NULL, PAGED_CODE, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, PsGetCurrentProcessId(), SepAdtOpenObjectAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SeSubsystemName, TRUE, and VOID.
Referenced by ObDuplicateObject(), and ObpCreateHandle().
VOID SeAuditHandleDuplication (__in PVOID SourceHandle, __in PVOID NewHandle, __in PEPROCESS SourceProcess, __in PEPROCESS TargetProcess)
Definition at line 2775 of file sepaudit.c.
References ASSERT, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, PAGED_CODE, PsProcessAuditId, RtlZeroMemory, SE_AUDITID_DUPLICATE_HANDLE, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeCaptureSubjectContext(), SepAdtLogAuditRecord(), SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenUserSid, SeReleaseSubjectContext(), and SeSubsystemName.
Referenced by ObAuditInheritedHandleProcedure(), and ObDuplicateObject().
NTKERNELAPI VOID SeAuditHardLinkCreation (__in PUNICODE_STRING FileName, __in PUNICODE_STRING LinkName, __in BOOLEAN bSuccess)
Definition at line 3681 of file sepaudit.c.
References ASSERT, _SE_ADT_PARAMETER_ARRAY::AuditId, _SE_ADT_PARAMETER_ARRAY::CategoryId, EffectiveToken, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, PAGED_CODE, _SE_ADT_PARAMETER_ARRAY::ParameterCount, SE_AUDITID_HARDLINK_CREATION, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeCaptureSubjectContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, and _SE_ADT_PARAMETER_ARRAY::Type.
NTKERNELAPI BOOLEAN SeAuditingFileEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 4584 of file seaudit.c.
References AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, PAGED_CODE, SepAdtAuditThisEvent, and UNREFERENCED_PARAMETER.
NTKERNELAPI BOOLEAN SeAuditingFileEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
Definition at line 4620 of file seaudit.c.
References AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, PAGED_CODE, SepAdtAuditThisEventWithContext(), and UNREFERENCED_PARAMETER.
NTKERNELAPI BOOLEAN SeAuditingFileOrGlobalEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
Definition at line 4538 of file seaudit.c.
References AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, EffectiveToken, FALSE, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), and TRUE.
NTKERNELAPI BOOLEAN SeAuditingHardLinkEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 4662 of file seaudit.c.
References _ACL::AceCount, AuditCategoryObjectAccess, FALSE, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEvent, and TRUE.
NTKERNELAPI BOOLEAN SeAuditingHardLinkEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
Definition at line 4714 of file seaudit.c.
References _ACL::AceCount, AuditCategoryObjectAccess, FALSE, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), and TRUE.
VOID SeAuditLPCInvalidUse (__in PUNICODE_STRING LpcCallName, __in PUNICODE_STRING LpcServerPort)
Definition at line 3460 of file sepaudit.c.
References ASSERT, AuditCategorySystem, _SECURITY_SUBJECT_CONTEXT::ClientToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NULL, NullString, PAGED_CODE, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_LPC_INVALID_USE, SE_CATEGID_SYSTEM, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and TRUE.
VOID SeAuditProcessCreation (__in PEPROCESS Process)
Definition at line 2662 of file sepaudit.c.
References ASSERT, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NullString, PAGED_CODE, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, RtlZeroMemory, SE_AUDITID_PROCESS_CREATED, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, and Status.
Referenced by PspCreateProcess().
VOID SeAuditProcessExit (__in PEPROCESS Process)
Definition at line 2855 of file sepaudit.c.
References ASSERT, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NullString, PAGED_CODE, PsDereferencePrimaryToken, PsProcessAuditId, PsReferencePrimaryToken(), RtlZeroMemory, SE_AUDITID_PROCESS_EXIT, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, and Status.
Referenced by PspExitThread().
VOID SeAuditSystemTimeChange (__in LARGE_INTEGER OldTime, __in LARGE_INTEGER NewTime)
Definition at line 3573 of file sepaudit.c.
References ASSERT, AuditCategorySystem, _SECURITY_SUBJECT_CONTEXT::ClientToken, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NullString, PAGED_CODE, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_SYSTEM_TIME_CHANGE, SE_CATEGID_SYSTEM, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeTime, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and TRUE.
NTSTATUS SeCaptureAcl (__in PACL InputAcl, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full *AlignedAclSize PACL * CapturedAcl, __out PULONG AlignedAclSize)
Definition at line 1362 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, LongAlignSize, NULL, PAGED_CODE, ProbeAndReadUshort, ProbeForRead, RtlCopyMemory, SepCheckAcl(), STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_ACL, and STATUS_SUCCESS.
Referenced by NtCreateToken(), and NtSetInformationToken().
NTSTATUS SeCaptureAuditPolicy (__in PTOKEN_AUDIT_POLICY Policy, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PTOKEN_AUDIT_POLICY * CapturedPolicy)
Referenced by NtSetInformationToken().
NTSTATUS SeCaptureLuidAndAttributesArray (__in_ecount(ArrayCount) PLUID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full *AlignedArraySize PLUID_AND_ATTRIBUTES * CapturedArray, __out PULONG AlignedArraySize)
Definition at line 1599 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, LongAlignSize, NULL, PAGED_CODE, ProbeForRead, RtlCopyMemory, SEP_MAX_PRIVILEGE_COUNT, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtAdjustPrivilegesToken(), NtCreateToken(), NtFilterToken(), NtPrivilegeCheck(), and PspCaptureTokenFilter().
NTKERNELAPI NTSTATUS SeCaptureSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSECURITY_DESCRIPTOR * OutputSecurityDescriptor)
Definition at line 47 of file capture.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, _SECURITY_DESCRIPTOR::Dacl, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseDatatypeMisalignment(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR::Group, KernelMode, LongAlignSize, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, _SECURITY_DESCRIPTOR::Owner, PAGED_CODE, ProbeAndReadUchar, ProbeAndReadUshort, ProbeForRead, ProbeForReadSmallStructure, _SECURITY_DESCRIPTOR::Revision, RtlCopyMemory, RtlLengthRequiredSid(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlValidSid(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, _SECURITY_DESCRIPTOR::Sacl, SE_DACL_PRESENT, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SEP_USHORT_OVERFLOW, SepCheckAcl(), STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_ACL, STATUS_INVALID_SID, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by NtOpenObjectAuditAlarm(), NtSetSecurityObject(), ObpCaptureObjectCreateInformation(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
NTSTATUS SeCaptureSecurityQos (__in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE RequestorMode, __out PBOOLEAN SecurityQosPresent, __out PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
Definition at line 946 of file capture.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, _SECURITY_QUALITY_OF_SERVICE::Length, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::Length, NT_SUCCESS, NULL, PAGED_CODE, ProbeForReadSmallStructure, RtlCopyMemory, SepFreeProxyData(), SepProbeAndCaptureQosData(), Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by NtCreateToken(), and NtDuplicateToken().
NTSTATUS SeCaptureSid (__in PSID InputSid, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSID * CapturedSid)
Definition at line 1134 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, NULL, PAGED_CODE, ProbeAndReadUchar, ProbeForRead, RtlCopyMemory, RtlLengthRequiredSid(), RtlValidSid(), STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_SID, and STATUS_SUCCESS.
Referenced by NtCreateToken(), NtSecureConnectPort(), NtSetInformationToken(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
NTSTATUS SeCaptureSidAndAttributesArray (__in_ecount(ArrayCount) PSID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(AlignedArraySize) PSID_AND_ATTRIBUTES * CapturedArray, __out PULONG AlignedArraySize)
Definition at line 1840 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, LongAlignSize, NT_SUCCESS, NULL, PAGED_CODE, ProbeAndReadUchar, ProbeForRead, RtlCopyMemory, RtlLengthRequiredSid(), RtlLengthSid(), RtlValidSid(), SEP_MAX_GROUP_COUNT, _SID_AND_ATTRIBUTES::Sid, SID_MAX_SUB_AUTHORITIES, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_INVALID_SID, and STATUS_SUCCESS.
Referenced by NtAdjustGroupsToken(), NtCreateToken(), NtFilterToken(), and PspCaptureTokenFilter().
NTKERNELAPI VOID SeCaptureSubjectContext (__out PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 43 of file subject.c.
References PsGetCurrentProcess(), PsGetCurrentThread(), and SeCaptureSubjectContextEx().
Referenced by CmpCheckKeyAccess(), CmpNotifyChangeKey(), NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtSetUuidSeed(), PspSinglePrivCheck(), RtlpSetSecurityObject(), SeAccessCheckByType(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditSystemTimeChange(), SeCheckPrivilegedObject(), SeCloseObjectAuditAlarm(), SeDeleteObjectAuditAlarm(), SeDetailedAuditingWithToken(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtAuditThisEventWithContext(), SepAuditAssignPrimaryToken(), SeReportSecurityEvent(), SeSinglePrivilegeCheck(), WmipCheckGuidAccess(), and WmipInitializeSecurity().
VOID SeCaptureSubjectContextEx (__in PETHREAD Thread, __in PEPROCESS Process, __out PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 86 of file subject.c.
References DbgBreakPoint(), InterlockedIncrement, NULL, PAGED_CODE, PsProcessAuditId, PsReferenceImpersonationToken(), and PsReferencePrimaryToken().
Referenced by SeCaptureSubjectContext(), and SeCreateAccessStateEx().
BOOLEAN SeCheckAuditPrivilege (__in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE PreviousMode)
Definition at line 200 of file seaudit.c.
References _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, KernelMode, _LUID_AND_ATTRIBUTES::Luid, NULL, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, SeAuditPrivilege, SepPrivilegeCheck(), and SePrivilegedServiceAuditAlarm().
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SeCheckPrivilegedObject (__in LUID PrivilegeValue, __in HANDLE ObjectHandle, __in ACCESS_MASK DesiredAccess, __in KPROCESSOR_MODE PreviousMode)
Definition at line 496 of file privileg.c.
References _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, KernelMode, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, SeCaptureSubjectContext(), SePrivilegeCheck(), SePrivilegeObjectAuditAlarm(), and SeReleaseSubjectContext().
Referenced by NtSetInformationJobObject(), NtSetInformationProcess(), NtSetInformationThread(), and PspSetPrimaryToken().
VOID SeCloseObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle, __in BOOLEAN GenerateOnClose)
Definition at line 3578 of file seaudit.c.
References EffectiveToken, PAGED_CODE, SeCaptureSubjectContext(), SepAdtCloseObjectAuditAlarm(), SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and UNREFERENCED_PARAMETER.
Referenced by ObpCloseHandleTableEntry().
NTSTATUS SeComputeQuotaInformationSize (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __out PULONG Size)
Definition at line 2576 of file capture.c.
References _ACL::AclSize, Group, LongAlignSize, NULL, PAGED_CODE, _SECURITY_DESCRIPTOR::Revision, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by ObpCaptureObjectCreateInformation().
NTSTATUS SeCopyClientToken (__in PACCESS_TOKEN ClientToken, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, __in KPROCESSOR_MODE RequestorMode, __deref_out PACCESS_TOKEN * DuplicateToken)
Definition at line 1266 of file tokendup.c.
References FALSE, InitializeObjectAttributes, NT_SUCCESS, NULL, ObInsertObject(), PAGED_CODE, SepDuplicateToken(), Status, and TokenImpersonation.
Referenced by PsImpersonateClient(), and SepCreateClientSecurity().
NTKERNELAPI NTSTATUS SeCreateAccessState (__out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in PGENERIC_MAPPING GenericMapping)
Referenced by NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenThread(), ObDuplicateObject(), ObInsertObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObReferenceObjectByName(), SepCreateToken(), and WmipCreateGuidObject().
NTSTATUS SeCreateAccessStateEx (__in_opt PETHREAD Thread, __in PEPROCESS Process, __out PACCESS_STATE AccessState, __out PAUX_ACCESS_DATA AuxData, __in ACCESS_MASK DesiredAccess, __in_opt PGENERIC_MAPPING GenericMapping)
Definition at line 117 of file seastate.c.
References ARGUMENT_PRESENT, ASSERT, EffectiveToken, ExAllocateLocallyUniqueId(), FALSE, FIELD_OFFSET, GENERIC_ACCESS, NULL, PAGED_CODE, RtlMapGenericMask(), RtlZeroMemory, SeCaptureSubjectContextEx(), STATUS_SUCCESS, and TOKEN_HAS_TRAVERSE_PRIVILEGE.
Referenced by PspCreateProcess(), PspCreateThread(), and SeCreateAccessState().
NTKERNELAPI NTSTATUS SeCreateClientSecurity (__in PETHREAD ClientThread, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN RemoteSession, __out PSECURITY_CLIENT_CONTEXT ClientContext)
Definition at line 231 of file seclient.c.
References NT_SUCCESS, ObDereferenceObject(), PAGED_CODE, PsReferenceEffectiveToken(), SECURITY_STATIC_TRACKING, SepCreateClientSecurity(), Status, STATUS_SUCCESS, and TokenType.
Referenced by CmLoadKey(), NtImpersonateThread(), NtSecureConnectPort(), WmipStartLogger(), and WmiUpdateTrace().
NTKERNELAPI NTSTATUS SeCreateClientSecurityFromSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN ServerIsRemote, __out PSECURITY_CLIENT_CONTEXT ClientContext)
Definition at line 456 of file seclient.c.
References FALSE, NT_SUCCESS, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, SECURITY_STATIC_TRACKING, SepCreateClientSecurity(), SeQuerySubjectContextToken, Status, STATUS_SUCCESS, TokenImpersonation, and TokenPrimary.
VOID SeCreateInstanceAuditAlarm (IN PLUID OperationID OPTIONAL, IN PVOID Object, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, IN KPROCESSOR_MODE AccessMode)
VOID SeCreateObjectAuditAlarm (IN PLUID OperationID OPTIONAL, IN PVOID Object, IN PUNICODE_STRING ComponentName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, OUT PBOOLEAN AuditPerformed, IN KPROCESSOR_MODE AccessMode)
VOID SeDeassignPrimaryToken (__in PEPROCESS Process)
Definition at line 583 of file token.c.
References ASSERT, FALSE, NULL, ObDereferenceObject(), ObFastReplaceObject(), PAGED_CODE, _TOKEN::TokenInUse, TokenPrimary, and _TOKEN::TokenType.
Referenced by PspDeleteProcessSecurity(), and SeAssignPrimaryToken().
NTKERNELAPI NTSTATUS SeDeassignSecurity (__deref_inout PSECURITY_DESCRIPTOR * SecurityDescriptor)
Definition at line 362 of file seassign.c.
References ExFreePool(), NULL, PAGED_CODE, and STATUS_SUCCESS.
Referenced by CmpDoCreateChild(), and ObAssignSecurity().
NTSTATUS SeDefaultObjectMethod (__in PVOID Object, __in SECURITY_OPERATION_CODE OperationCode, __in PSECURITY_INFORMATION SecurityInformation, __inout PSECURITY_DESCRIPTOR SecurityDescriptor, __inout_opt PULONG CapturedLength, __deref_inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 190 of file semethod.c.
References ASSERT, AssignSecurityDescriptor, DeleteSecurityDescriptor, KeBugCheckEx(), NonPagedPool, NULL, ObAssignObjectSecurityDescriptor(), ObQuerySecurityDescriptorInfo(), ObSetSecurityDescriptorInfo(), PAGED_CODE, PagedPool, QuerySecurityDescriptor, SECURITY_SYSTEM, SepDefaultDeleteMethod(), SetSecurityDescriptor, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by ObCreateObjectType(), and ObDuplicateObject().
NTKERNELAPI VOID SeDeleteAccessState (__in PACCESS_STATE AccessState)
Definition at line 237 of file seastate.c.
References ExFreePool(), NULL, PAGED_CODE, _AUX_ACCESS_DATA::PrivilegesUsed, and SeReleaseSubjectContext().
Referenced by NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenThread(), ObDuplicateObject(), ObInsertObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObReferenceObjectByName(), PspCreateProcess(), PspCreateThread(), SepCreateToken(), and WmipCreateGuidObject().
NTKERNELAPI VOID SeDeleteObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle)
Definition at line 3642 of file seaudit.c.
References EffectiveToken, PAGED_CODE, SeCaptureSubjectContext(), SepAdtDeleteObjectAuditAlarm(), SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and UNREFERENCED_PARAMETER.
Referenced by NtDeleteKey(), and NtMakeTemporaryObject().
NTKERNELAPI BOOLEAN FASTCALL SeDetailedAuditingWithToken (__in_opt PACCESS_TOKEN AccessToken)
Definition at line 181 of file sepaudit.c.
References ARGUMENT_PRESENT, AuditCategoryDetailedTracking, _SE_AUDITING_STATE::AuditOnSuccess, _TOKEN::AuditPolicy, _SEP_AUDIT_POLICY_CATEGORIES::DetailedTracking, EffectiveToken, FALSE, NULL, PAGED_CODE, _SEP_AUDIT_POLICY::PolicyElements, SeAuditingState, SeCaptureSubjectContext(), SepAuditFailed(), SepTokenPolicyCounter, SeReleaseSubjectContext(), STATUS_NO_TOKEN, TOKEN_AUDIT_SUCCESS_EXCLUDE, TOKEN_AUDIT_SUCCESS_INCLUDE, and TRUE.
Referenced by ObDuplicateObject(), ObInitProcess(), PspCreateProcess(), PspExitThread(), SeAssignPrimaryToken(), and SeExchangePrimaryToken().
NTSTATUS SeExchangePrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN NewAccessToken, __deref_out PACCESS_TOKEN * OldAccessToken)
Definition at line 627 of file token.c.
References ASSERT, FALSE, MmGetSessionId(), NULL, ObFastReplaceObject(), ObReferenceObject, PAGED_CODE, SeDetailedAuditingWithToken(), SepAcquireTokenWriteLock, SepAuditAssignPrimaryToken(), SepReleaseTokenWriteLock, _TOKEN::SessionId, Status, STATUS_BAD_TOKEN_TYPE, STATUS_NO_TOKEN, STATUS_SUCCESS, STATUS_TOKEN_ALREADY_IN_USE, _TOKEN::TokenInUse, TokenPrimary, _TOKEN::TokenType, and TRUE.
Referenced by PspAssignPrimaryToken().
NTSTATUS SeFastFilterToken (__in PACCESS_TOKEN ExistingToken, __in KPROCESSOR_MODE RequestorMode, __in ULONG Flags, __in ULONG GroupCount, __in_ecount_opt(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount_opt(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete, __in ULONG SidCount, __in_ecount_opt(SidCount) PSID_AND_ATTRIBUTES RestrictedSids, __in ULONG SidLength, __deref_out PACCESS_TOKEN * FilteredToken)
Definition at line 1859 of file tokendup.c.
References NT_SUCCESS, NULL, ObInsertObject(), SepFilterToken(), and Status.
Referenced by PsImpersonateClient().
BOOLEAN SeFastTraverseCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PACCESS_STATE AccessState, __in ACCESS_MASK TraverseAccess, __in KPROCESSOR_MODE AccessMode)
Referenced by IopParseDevice(), and ObpCheckTraverseAccess().
NTKERNELAPI NTSTATUS SeFilterToken (__in PACCESS_TOKEN ExistingToken, __in ULONG Flags, __in_opt PTOKEN_GROUPS SidsToDisable, __in_opt PTOKEN_PRIVILEGES PrivilegesToDelete, __in_opt PTOKEN_GROUPS RestrictedSids, __deref_out PACCESS_TOKEN * FilteredToken)
Definition at line 1663 of file tokendup.c.
References ARGUMENT_PRESENT, Index, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObInsertObject(), PAGED_CODE, SepFilterToken(), Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
VOID SeFreeCapturedSecurityQos (__in PVOID SecurityQos)
Definition at line 904 of file capture.c.
References _SECURITY_ADVANCED_QUALITY_OF_SERVICE::AuditData, ExFreePool(), _SECURITY_ADVANCED_QUALITY_OF_SERVICE::Length, NULL, PAGED_CODE, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::ProxyData, and SepFreeProxyData().
Referenced by NtCreateToken(), and NtDuplicateToken().
NTKERNELAPI VOID SeFreePrivileges (__in PPRIVILEGE_SET Privileges)
Definition at line 3289 of file accessck.c.
References ExFreePool(), and PAGED_CODE.
Referenced by IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckTraverseAccess(), and SeAccessCheckByType().
VOID SeGenerateMessage (IN PSTRING ObjectName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, IN HANDLE AuditPort, IN HANDLE AlarmPort, IN KPROCESSOR_MODE AccessMode)
VOID SeGetTokenControlInformation (__in PACCESS_TOKEN Token, __out PTOKEN_CONTROL TokenControl)
Definition at line 783 of file token.c.
References PAGED_CODE, SepAcquireTokenReadLock, and SepReleaseTokenReadLock.
Referenced by SepCreateClientSecurity().
NTKERNELAPI VOID SeImpersonateClient (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
Definition at line 337 of file seclient.c.
References DbgPrint(), PAGED_CODE, SeImpersonateClientEx(), and VOID.
NTKERNELAPI NTSTATUS SeImpersonateClientEx (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
Definition at line 380 of file seclient.c.
References ARGUMENT_PRESENT, PAGED_CODE, PsGetCurrentThread(), PsImpersonateClient(), Status, and TRUE.
Referenced by CmpCmdHiveOpen(), NtImpersonateClientOfPort(), NtImpersonateThread(), SeImpersonateClient(), and WmipCreateLogFile().
NTSTATUS SeInitializeProcessAuditName (__in __typefix(PFILE_OBJECT) PVOID FileObject, __in BOOLEAN bIgnoreAuditPolicy, __deref_out POBJECT_NAME_INFORMATION * pAuditName)
Definition at line 2996 of file sepaudit.c.
References ASSERT, AuditCategoryDetailedTracking, AuditCategoryObjectAccess, DbgPrint(), ExAllocatePoolWithTag, ExFreePool(), FALSE, NonPagedPool, NT_SUCCESS, NULL, ObQueryNameString(), PAGED_CODE, RtlZeroMemory, SepAdtAuditThisEventWithContext(), Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by MmInitializeProcessAddressSpace(), and SeLocateProcessImageName().
BOOLEAN SeInitSystem (VOID)
Definition at line 40 of file seinit.c.
References InitializationPhase, KeBugCheckEx(), PAGED_CODE, SepInitializationPhase0(), SepInitializationPhase1(), and UNEXPECTED_INITIALIZATION_CALL.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTSTATUS SeIsChildToken (__in HANDLE Token, __out PBOOLEAN IsChild)
Definition at line 3227 of file token.c.
References FALSE, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _TOKEN::TokenId, and TRUE.
NTSTATUS SeIsChildTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsChild)
Definition at line 3317 of file token.c.
References FALSE, NULL, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _TOKEN::TokenId, and TRUE.
Referenced by NtSetInformationJobObject(), and PspSetPrimaryToken().
NTSTATUS SeIsSiblingToken (__in HANDLE Token, __out PBOOLEAN IsSibling)
Definition at line 3392 of file token.c.
References _TOKEN::AuthenticationId, FALSE, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
NTSTATUS SeIsSiblingTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsSibling)
Definition at line 3497 of file token.c.
References _TOKEN::AuthenticationId, FALSE, NULL, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by PspSetPrimaryToken().
NTSTATUS SeLocateProcessImageName (__in PEPROCESS Process, __deref_out PUNICODE_STRING * pImageFileName)
Definition at line 3206 of file sepaudit.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), InterlockedCompareExchangePointer, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PsReferenceProcessFilePointer(), RtlCopyMemory, SeInitializeProcessAuditName(), Status, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by ExpGetProcessInformation(), NtQueryInformationProcess(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and WmiTraceProcess().
NTKERNELAPI VOID SeLockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 180 of file subject.c.
References ARGUMENT_PRESENT, PAGED_CODE, and SepAcquireTokenReadLock.
Referenced by CmpCheckCreateAccess(), CmpCheckNotifyAccess(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), RtlpNewSecurityObject(), SeAccessCheck(), and SepAccessCheckAndAuditAlarm().
PACCESS_TOKEN SeMakeAnonymousLogonToken (VOID)
Definition at line 1503 of file token.c.
References ACL_REVISION2, ASSERT, _SID_AND_ATTRIBUTES::Attributes, _TIME_FIELDS::Day, ExAllocatePoolWithTag, ExFreePool(), FALSE, _TIME_FIELDS::Hour, InitializeObjectAttributes, KernelMode, LongAlignSize, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _TOKEN_PRIMARY_GROUP::PrimaryGroup, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlTimeFieldsToTime(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SeAnonymousAuthenticationId, SeAnonymousLogonSid, _TIME_FIELDS::Second, SECURITY_DESCRIPTOR_MIN_LENGTH, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SepCreateToken(), SeSystemTokenSource, SeWorldSid, _SID_AND_ATTRIBUTES::Sid, Status, TOKEN_ALL_ACCESS, TokenPrimary, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
Referenced by SepInitializationPhase1().
PACCESS_TOKEN SeMakeAnonymousLogonTokenNoEveryone (VOID)
Definition at line 1289 of file token.c.
References ACL_REVISION2, ASSERT, _SID_AND_ATTRIBUTES::Attributes, _TIME_FIELDS::Day, ExAllocatePoolWithTag, ExFreePool(), FALSE, _TIME_FIELDS::Hour, InitializeObjectAttributes, KernelMode, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _TOKEN_PRIMARY_GROUP::PrimaryGroup, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlTimeFieldsToTime(), SeAnonymousAuthenticationId, SeAnonymousLogonSid, _TIME_FIELDS::Second, SECURITY_DESCRIPTOR_MIN_LENGTH, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SepCreateToken(), SeSystemTokenSource, SeWorldSid, _SID_AND_ATTRIBUTES::Sid, Status, TOKEN_ALL_ACCESS, TokenPrimary, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
Referenced by SepInitializationPhase1().
PACCESS_TOKEN SeMakeSystemToken (VOID)
Referenced by SepInitializationPhase0().
NTKERNELAPI NTSTATUS SeMarkLogonSessionForTerminationNotification (IN PLUID LogonId)
Definition at line 1279 of file rmlogon.c.
References _SEP_LOGON_SESSION_REFERENCES::Flags, _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, PAGED_CODE, RtlEqualLuid, SEP_TERMINATION_NOTIFY, SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_NOT_FOUND, and STATUS_SUCCESS.
VOID SeMaximumAuditMask (IN PACL Sacl, IN ACCESS_MASK GrantedAccess, IN PACCESS_TOKEN Token, OUT PACCESS_MASK pAuditMask)
Definition at line 1609 of file accessck.c.
References FALSE, FirstAce, INHERIT_ONLY_ACE, NextAce, NULL, SepSidInToken(), SUCCESSFUL_ACCESS_ACE_FLAG, and SYSTEM_AUDIT_ACE_TYPE.
Referenced by SeOpenObjectAuditAlarm().
VOID SeObjectReferenceAuditAlarm (__in_opt PLUID OperationID, __in PVOID Object, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in_opt PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
Definition at line 3404 of file seaudit.c.
References AuditCategoryDetailedTracking, EffectiveToken, FALSE, KernelMode, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), SepAdtObjectReferenceAuditAlarm(), SepExamineSacl(), and UNREFERENCED_PARAMETER.
Referenced by ObpCheckObjectReference().
NTKERNELAPI VOID SeOpenObjectAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
Definition at line 2734 of file seaudit.c.
References ARGUMENT_PRESENT, AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, _TOKEN::AuditData, _SECURITY_TOKEN_AUDIT_DATA::DenyMask, EffectiveToken, ExAllocatePool, ExFreePool(), FALSE, _AUX_ACCESS_DATA::GenericMapping, _SECURITY_TOKEN_AUDIT_DATA::GrantMask, KernelMode, _AUX_ACCESS_DATA::MaximumAuditMask, _UNICODE_STRING::MaximumLength, _OBJECT_NAME_INFORMATION::Name, NULL, PAGED_CODE, PagedPool, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, RtlCopyUnicodeString(), RtlMapGenericMask(), RtlpSaclAddrSecurityDescriptor, SeMaximumAuditMask(), SepAdtAuditThisEventWithContext(), SepAdtOpenObjectAuditAlarm(), SepExamineSacl(), SepFilterPrivilegeAudits(), SepQueryNameString(), SepQueryTypeString(), SeSubsystemName, TRUE, and UNREFERENCED_PARAMETER.
Referenced by IopParseDevice(), and ObCheckObjectAccess().
NTKERNELAPI VOID SeOpenObjectForDeleteAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
Definition at line 3067 of file seaudit.c.
References ARGUMENT_PRESENT, AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, _TOKEN::AuditData, _SECURITY_TOKEN_AUDIT_DATA::DenyMask, EffectiveToken, ExAllocatePool, ExFreePool(), FALSE, _AUX_ACCESS_DATA::GenericMapping, _SECURITY_TOKEN_AUDIT_DATA::GrantMask, KernelMode, _UNICODE_STRING::MaximumLength, _OBJECT_NAME_INFORMATION::Name, NULL, PAGED_CODE, PagedPool, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, RtlCopyUnicodeString(), RtlMapGenericMask(), RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepExamineSacl(), SepFilterPrivilegeAudits(), SepQueryNameString(), SepQueryTypeString(), SeSubsystemName, TRUE, and UNREFERENCED_PARAMETER.
VOID SeOperationAuditAlarm (__in_opt PUNICODE_STRING CapturedSubsystemName, __in PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in ACCESS_MASK AuditMask, __in_opt PSID UserSid)
Definition at line 2092 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_OBJECT_ACCESS, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeAccessMask, SepSetParmTypeFileSpec, SepSetParmTypeHexUlong, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and TRUE.
Referenced by ObpAuditObjectAccess().
NTKERNELAPI BOOLEAN SePrivilegeCheck (__inout PPRIVILEGE_SET RequiredPrivileges, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE AccessMode)
Definition at line 155 of file privileg.c.
References EffectiveToken, FALSE, NULL, PAGED_CODE, SecurityImpersonation, SepPrivilegeCheck(), and Status.
Referenced by IopCheckBackupRestorePrivilege(), ObpIncrementHandleCount(), PspSinglePrivCheck(), RtlpNewSecurityObject(), SeCheckPrivilegedObject(), and SeSinglePrivilegeCheck().
VOID SePrivilegedServiceAuditAlarm (__in_opt PUNICODE_STRING ServiceName, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
Definition at line 944 of file seaudit.c.
References ASSERT, EffectiveToken, IsValidPrivilegeCount, PAGED_CODE, RtlEqualSid(), SeExports, _SE_EXPORTS::SeLocalServiceSid, SeLocalSystemSid, _SE_EXPORTS::SeNetworkServiceSid, SEP_SERVICES_FILTER, SepAdtPrivilegedServiceAuditAlarm(), SepFilterPrivilegeAudits(), SepTokenUserSid, and SeSubsystemName.
Referenced by ObpIncrementHandleCount(), PspSinglePrivCheckAudit(), RtlpNewSecurityObject(), SeCheckAuditPrivilege(), and SeSinglePrivilegeCheck().
NTKERNELAPI VOID SePrivilegeObjectAuditAlarm (__in HANDLE Handle, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
Definition at line 628 of file seaudit.c.
References KernelMode, PAGED_CODE, SepAdtPrivilegeObjectAuditAlarm(), and SeSubsystemName.
Referenced by ObpCreateHandle(), and SeCheckPrivilegedObject().
NTSTATUS SePrivilegePolicyCheck (__inout PACCESS_MASK RemainingDesiredAccess, __inout PACCESS_MASK PreviouslyGrantedAccess, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in_opt PACCESS_TOKEN ExplicitToken, __deref_out PPRIVILEGE_SET * PrivilegeSet, __in KPROCESSOR_MODE PreviousMode)
Definition at line 3568 of file accessck.c.
References ACCESS_SYSTEM_SECURITY, ANYSIZE_ARRAY, ARGUMENT_PRESENT, EffectiveToken, ExAllocatePoolWithTag, FALSE, NULL, PAGED_CODE, PagedPool, SE_PRIVILEGE_USED_FOR_ACCESS, SepSinglePrivilegeCheck(), SeSecurityPrivilege, SeTakeOwnershipPrivilege, STATUS_INSUFFICIENT_RESOURCES, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TRUE, and WRITE_OWNER.
Referenced by SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
NTKERNELAPI NTSTATUS SeQueryAuthenticationIdToken (__in PACCESS_TOKEN Token, __out PLUID AuthenticationId)
Definition at line 1623 of file tokenqry.c.
References PAGED_CODE, and STATUS_SUCCESS.
Referenced by NtSetUuidSeed(), ObpReferenceDeviceMap(), and ObpSetCurrentProcessDeviceMap().
NTKERNELAPI NTSTATUS SeQueryInformationToken (__in PACCESS_TOKEN Token, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __deref_out PVOID * TokenInformation)
Definition at line 1664 of file tokenqry.c.
References _ACL::AclSize, ANYSIZE_ARRAY, ARGUMENT_PRESENT, ASSERT, _TOKEN::AuthenticationId, _TOKEN_STATISTICS::AuthenticationId, _TOKEN::DefaultDacl, _TOKEN_DEFAULT_DACL::DefaultDacl, _TOKEN::DefaultOwnerIndex, _TOKEN::DynamicAvailable, _TOKEN_STATISTICS::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN_STATISTICS::DynamicCharged, ExAllocatePool, _TOKEN::ExpirationTime, _TOKEN_STATISTICS::ExpirationTime, _TOKEN_GROUPS::GroupCount, _TOKEN_STATISTICS::GroupCount, _TOKEN_GROUPS::Groups, _TOKEN::ImpersonationLevel, _TOKEN_STATISTICS::ImpersonationLevel, Index, _TOKEN::ModifiedId, _TOKEN_STATISTICS::ModifiedId, NT_SUCCESS, NULL, _TOKEN_OWNER::Owner, PAGED_CODE, PagedPool, _TOKEN::PrimaryGroup, _TOKEN_PRIMARY_GROUP::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_STATISTICS::PrivilegeCount, _TOKEN::Privileges, _TOKEN_PRIVILEGES::Privileges, RtlCopyLuidAndAttributesArray(), RtlCopyMemory, RtlCopySid(), RtlCopySidAndAttributesArray(), SeLengthSid, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SeQuerySessionIdToken(), _SID_AND_ATTRIBUTES::Sid, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, TokenDefaultDacl, TokenGroups, _TOKEN::TokenId, _TOKEN_STATISTICS::TokenId, TokenImpersonation, TokenImpersonationLevel, TokenOwner, TokenPrimaryGroup, TokenPrivileges, TokenSessionId, _TOKEN::TokenSource, TokenSource, TokenStatistics, _TOKEN::TokenType, TokenType, _TOKEN_STATISTICS::TokenType, TokenUser, _TOKEN_USER::User, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
Referenced by NtSecureConnectPort(), and WmiTraceProcess().
VOID SeQuerySecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
Definition at line 133 of file semethod.c.
References ACCESS_SYSTEM_SECURITY, DACL_SECURITY_INFORMATION, GROUP_SECURITY_INFORMATION, OWNER_SECURITY_INFORMATION, PAGED_CODE, READ_CONTROL, and SACL_SECURITY_INFORMATION.
Referenced by IoCheckFunctionAccess(), and NtQuerySecurityObject().
NTKERNELAPI NTSTATUS SeQuerySecurityDescriptorInfo (__in PSECURITY_INFORMATION SecurityInformation, __out_bcount *Length PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __deref_inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor)
Definition at line 554 of file semethod.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, _SECURITY_DESCRIPTOR::Dacl, DACL_SECURITY_INFORMATION, except, EXCEPTION_EXECUTE_HANDLER, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR::Group, GROUP_SECURITY_INFORMATION, LongAlignPtr, LongAlignSize, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, _SECURITY_DESCRIPTOR::Owner, OWNER_SECURITY_INFORMATION, PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlMoveMemory, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpPropagateControlBits, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, _SECURITY_DESCRIPTOR::Sacl, SACL_SECURITY_INFORMATION, SE_DACL_AUTO_INHERITED, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_GROUP_DEFAULTED, SE_OWNER_DEFAULTED, SE_SACL_AUTO_INHERITED, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by CmpCheckKeyAccess(), CmpQuerySecurityDescriptorInfo(), IopGetSetSecurityObject(), and ObQuerySecurityDescriptorInfo().
NTKERNELAPI NTSTATUS SeQuerySessionIdToken (__in PACCESS_TOKEN Token, __out PULONG SessionId)
Definition at line 2251 of file tokenqry.c.
References PAGED_CODE, SepAcquireTokenReadLock, SepReleaseTokenReadLock, and STATUS_SUCCESS.
Referenced by NtQueryInformationToken(), and SeQueryInformationToken().
NTKERNELAPI NTSTATUS SeRegisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
Definition at line 1146 of file rmlogon.c.
References _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::CallbackRoutine, ExAllocatePoolWithTag, _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::Next, NULL, PAGED_CODE, PagedPool, POOL_COLD_ALLOCATION, SeFileSystemNotifyRoutinesHead, SepRmAcquireNotifyLock, SepRmReleaseNotifyLock, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
VOID SeReleaseAcl (__in PACL CapturedAcl, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 1551 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtCreateToken(), and NtSetInformationToken().
VOID SeReleaseAuditPolicy (__in PTOKEN_AUDIT_POLICY CapturedPolicy, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 2529 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtSetInformationToken().
VOID SeReleaseLuidAndAttributesArray (__in PLUID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 1787 of file capture.c.
References ExFreePool(), KernelMode, NULL, PAGED_CODE, TRUE, and UserMode.
Referenced by NtAdjustPrivilegesToken(), NtCreateToken(), NtFilterToken(), and NtPrivilegeCheck().
NTKERNELAPI VOID SeReleaseSecurityDescriptor (__in PSECURITY_DESCRIPTOR CapturedSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 642 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtOpenObjectAuditAlarm(), NtSetSecurityObject(), ObInsertObject(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
VOID SeReleaseSid (__in PSID CapturedSid, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 1312 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtCreateToken(), NtSecureConnectPort(), NtSetInformationToken(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
VOID SeReleaseSidAndAttributesArray (__in PSID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 2286 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtAdjustGroupsToken(), NtCreateToken(), and NtFilterToken().
NTKERNELAPI VOID SeReleaseSubjectContext (__inout PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 261 of file subject.c.
References DbgBreakPoint(), InterlockedDecrement, NULL, PAGED_CODE, PsDereferenceImpersonationToken, PsDereferencePrimaryTokenEx, and PsGetCurrentProcess().
Referenced by CmpCheckKeyAccess(), CmpFlushNotify(), FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifyFilterChangeDirectory(), NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtSetUuidSeed(), PspSinglePrivCheckAudit(), RtlpSetSecurityObject(), SeAccessCheckByType(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditSystemTimeChange(), SeCheckPrivilegedObject(), SeCloseObjectAuditAlarm(), SeDeleteAccessState(), SeDeleteObjectAuditAlarm(), SeDetailedAuditingWithToken(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtAuditThisEventWithContext(), SepAuditAssignPrimaryToken(), SeReportSecurityEvent(), SeSinglePrivilegeCheck(), and WmipCheckGuidAccess().
NTSTATUS SeReportSecurityEvent (__in ULONG Flags, __in PUNICODE_STRING SourceName, __in_opt PSID UserSid, __in PSE_ADT_PARAMETER_ARRAY AuditParameters)
Definition at line 3890 of file sepaudit.c.
References ASSERT, _SE_ADT_PARAMETER_ARRAY::AuditId, _SE_ADT_PARAMETER_ARRAY::CategoryId, EffectiveToken, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, FALSE, NT_SUCCESS, NULL, _SE_ADT_PARAMETER_ARRAY::ParameterCount, _SE_ADT_PARAMETER_ARRAY::Parameters, RtlCopyMemory, RtlValidateUnicodeString(), RtlValidSid(), RtlZeroMemory, SE_AUDITID_GENERIC_AUDIT_EVENT, SE_MAX_AUDIT_PARAMETERS, SE_MAX_GENERIC_AUDIT_PARAMETERS, SeCaptureSubjectContext(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, and _SE_ADT_PARAMETER_ARRAY::Type.
BOOLEAN SeRmInitPhase1 (VOID)
Referenced by Phase1InitializationDiscard().
VOID SeSetAccessStateGenericMapping (__inout PACCESS_STATE AccessState, __in PGENERIC_MAPPING GenericMapping)
Definition at line 285 of file seastate.c.
References _AUX_ACCESS_DATA::GenericMapping, and PAGED_CODE.
Referenced by IopParseDevice().
NTSTATUS SeSetAuditParameter (__inout PSE_ADT_PARAMETER_ARRAY AuditParameters, __in SE_ADT_PARAMETER_TYPE Type, __in ULONG Index, __in PVOID Data)
Definition at line 3760 of file sepaudit.c.
References Index, NT_SUCCESS, NULL, RtlCopyMemory, SeAdtParmTypeAccessMask, SeAdtParmTypeDateTime, SeAdtParmTypeDuration, SeAdtParmTypeFileSpec, SeAdtParmTypeGuid, SeAdtParmTypeHexInt64, SeAdtParmTypeHexUlong, SeAdtParmTypeLogonId, SeAdtParmTypeLuid, SeAdtParmTypeMessage, SeAdtParmTypeNoLogonId, SeAdtParmTypeNone, SeAdtParmTypeNoUac, SeAdtParmTypeObjectTypes, SeAdtParmTypePrivs, SeAdtParmTypePtr, SeAdtParmTypeSid, SeAdtParmTypeSidList, SeAdtParmTypeSockAddr, SeAdtParmTypeString, SeAdtParmTypeStringList, SeAdtParmTypeTime, SeAdtParmTypeUlong, SeAdtParmTypeUserAccountControl, SeLengthSid, SepPrivilegeSetSize, Status, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, and STATUS_SUCCESS.
VOID SeSetSecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
Definition at line 73 of file semethod.c.
References ACCESS_SYSTEM_SECURITY, DACL_SECURITY_INFORMATION, GROUP_SECURITY_INFORMATION, OWNER_SECURITY_INFORMATION, PAGED_CODE, SACL_SECURITY_INFORMATION, WRITE_DAC, and WRITE_OWNER.
Referenced by IoCheckFunctionAccess(), and NtSetSecurityObject().
NTKERNELAPI NTSTATUS SeSetSecurityDescriptorInfo (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 359 of file semethod.c.
References NULL, RtlpSetSecurityObject(), and STATUS_NO_SECURITY_ON_OBJECT.
Referenced by CmpSetSecurityDescriptorInfo(), IopSetDeviceSecurityDescriptor(), and ObSetSecurityDescriptorInfo().
NTKERNELAPI NTSTATUS SeSetSecurityDescriptorInfoEx (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in ULONG AutoInheritFlags, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 446 of file semethod.c.
References NULL, PAGED_CODE, RtlpSetSecurityObject(), and STATUS_NO_SECURITY_ON_OBJECT.
NTKERNELAPI NTSTATUS SeSetSessionIdToken (__in PACCESS_TOKEN Token, __in ULONG SessionId)
Definition at line 1290 of file tokenset.c.
References FALSE, PAGED_CODE, SepAcquireTokenWriteLock, SepReleaseTokenWriteLock, and STATUS_SUCCESS.
Referenced by NtSetInformationToken().
NTKERNELAPI BOOLEAN SeSinglePrivilegeCheck (__in LUID PrivilegeValue, __in KPROCESSOR_MODE PreviousMode)
Definition at line 428 of file privileg.c.
References _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, KernelMode, _LUID_AND_ATTRIBUTES::Luid, NULL, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, SeCaptureSubjectContext(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), and SeReleaseSubjectContext().
Referenced by CmpDoCreate(), CmpDoOpen(), CmpRefreshHive(), ExpRaiseHardError(), IopUnloadDriver(), MiMapViewOfImageSection(), MmCreateSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtCompactKeys(), NtCompressKey(), NtCreatePagingFile(), NtCreateProfile(), NtGetNextProcess(), NtGetNextThread(), NtLoadDriver(), NtLoadKeyEx(), NtLockRegistryKey(), NtLockVirtualMemory(), NtMakePermanentObject(), NtOpenProcess(), NtOpenThread(), NtQueryInformationToken(), NtQueryOpenSubKeysEx(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetDefaultHardErrorPort(), NtSetInformationJobObject(), NtSetInformationObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetInformationToken(), NtSetSystemInformation(), NtUnloadKey2(), NtUnloadKeyEx(), NtUnlockVirtualMemory(), ObCreateObject(), ObpLookupObjectName(), PerfInfoStartLog(), PspSetQuotaLimits(), SepCreateToken(), and SepValidOwnerSubjectContext().
NTSTATUS SeSubProcessToken (__in PACCESS_TOKEN ParentToken, __deref_out PACCESS_TOKEN * ChildToken, __in BOOLEAN MarkAsActive, __in ULONG SessionId)
Definition at line 1762 of file token.c.
References FALSE, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NULL, ObInsertObject(), PAGED_CODE, SepDuplicateToken(), _TOKEN::SessionId, Status, _TOKEN::TokenInUse, and TokenPrimary.
Referenced by NtAssignProcessToJobObject(), PspCreateProcess(), and PspInitializeProcessSecurity().
NTKERNELAPI NTSTATUS SeTokenCanImpersonate (__in PACCESS_TOKEN ProcessToken, __in PACCESS_TOKEN Token, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 192 of file token.c.
References _TOKEN::AuthenticationId, DbgPrint(), NT_SUCCESS, _TOKEN::OriginatingLogonSession, PAGED_CODE, PsGetCurrentThread(), RtlEqualLuid, RtlEqualSid(), SeAnonymousAuthenticationId, SecurityImpersonation, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SeTokenIsRestricted(), _SID_AND_ATTRIBUTES::Sid, Status, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TOKEN_HAS_IMPERSONATE_PRIVILEGE, _TOKEN::TokenFlags, and _TOKEN::UserAndGroups.
Referenced by PsImpersonateClient().
SECURITY_IMPERSONATION_LEVEL SeTokenImpersonationLevel (__in PACCESS_TOKEN Token)
Definition at line 329 of file token.c.
References PAGED_CODE.
Referenced by PsAssignImpersonationToken().
NTKERNELAPI BOOLEAN SeTokenIsAdmin (__in PACCESS_TOKEN Token)
Definition at line 162 of file token.c.
References PAGED_CODE, and TOKEN_HAS_ADMIN_GROUP.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PsImpersonateClient().
NTKERNELAPI BOOLEAN SeTokenIsRestricted (__in PACCESS_TOKEN Token)
Definition at line 299 of file token.c.
References PAGED_CODE, and TOKEN_IS_RESTRICTED.
Referenced by NtCompareTokens(), NtImpersonateAnonymousToken(), NtQueryInformationToken(), PsImpersonateClient(), SepAccessCheck(), and SeTokenCanImpersonate().
NTKERNELAPI TOKEN_TYPE SeTokenType (__in PACCESS_TOKEN Token)
Definition at line 130 of file token.c.
References PAGED_CODE, and TokenType.
Referenced by NtSetInformationJobObject(), and PsAssignImpersonationToken().
NTKERNELAPI VOID SeUnlockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 224 of file subject.c.
References ARGUMENT_PRESENT, PAGED_CODE, and SepReleaseTokenReadLock.
Referenced by CmpCheckCreateAccess(), CmpCheckNotifyAccess(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), RtlpNewSecurityObject(), SeAccessCheck(), and SepAccessCheckAndAuditAlarm().
NTKERNELAPI NTSTATUS SeUnregisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
Definition at line 1205 of file rmlogon.c.
References _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::CallbackRoutine, ExFreePool(), _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::Next, NULL, PAGED_CODE, SeFileSystemNotifyRoutinesHead, SepRmAcquireNotifyLock, SepRmReleaseNotifyLock, Status, STATUS_INVALID_PARAMETER, STATUS_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS SeUpdateClientSecurity (IN PETHREAD ClientThread, IN OUT PSECURITY_CLIENT_CONTEXT ClientContext, OUT PBOOLEAN ChangesMade, OUT PBOOLEAN NewToken)
NTKERNELAPI BOOLEAN SeValidSecurityDescriptor (__in ULONG Length, __in_bcount(Length) PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 2639 of file capture.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, LongAligned, _SECURITY_DESCRIPTOR_RELATIVE::Owner, PAGED_CODE, _SID::Revision, _SECURITY_DESCRIPTOR_RELATIVE::Revision, RtlOffsetToPointer, RtlValidAcl(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SID_MAX_SUB_AUTHORITIES, SID_REVISION, _SID::SubAuthorityCount, and TRUE.
Referenced by CmpRebuildSecurityCache(), CmpValidateHiveSecurityDescriptors(), and WmipSDRegistryQueryRoutine().
Variable Documentation
PSID SeAliasAccountOpsSid
Definition at line 108 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeAliasAdminsSid
Definition at line 103 of file seglobal.c.
Referenced by ExpKeyedEventInitialization(), IopCreateDefaultDeviceSecurityDescriptor(), MiCreateMemoryEvent(), NtCreatePagingFile(), ObInitSystem(), ObpGetDosDevicesProtection(), SeMakeSystemToken(), SepCreateImpersonationTokenDacl(), SepCreateToken(), SepInitializationPhase1(), SepInitSystemDacls(), SepMakeTokenEffectiveOnly(), SepRemoveDisabledGroupsAndPrivileges(), SepVariableInitialization(), WmipCreateAdminSD(), and WmipInitializeSecurity().
PSID SeAliasBackupOpsSid
Definition at line 111 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeAliasGuestsSid
Definition at line 106 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeAliasPowerUsersSid
Definition at line 107 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeAliasPrintOpsSid
Definition at line 110 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeAliasSystemOpsSid
Definition at line 109 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeAliasUsersSid
Definition at line 105 of file seglobal.c.
Referenced by SepVariableInitialization(), and WmipInitializeSecurity().
const LUID SeAnonymousAuthenticationId
Definition at line 74 of file seglobal.c.
Referenced by SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SepRmDbInitialization(), and SeTokenCanImpersonate().
PSID SeAnonymousLogonSid
Definition at line 112 of file seglobal.c.
Referenced by SeFastTraverseCheck(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SepExamineSacl(), SepExamineSaclEx(), and SepVariableInitialization().
PACCESS_TOKEN SeAnonymousLogonToken
Definition at line 120 of file seglobal.c.
Referenced by NtImpersonateAnonymousToken(), and SepInitializationPhase1().
PACCESS_TOKEN SeAnonymousLogonTokenNoEveryone
Definition at line 121 of file seglobal.c.
Referenced by NtImpersonateAnonymousToken(), and SepInitializationPhase1().
LUID SeAssignPrimaryTokenPrivilege
Definition at line 212 of file seglobal.c.
Referenced by NtSetInformationJobObject(), PspSetPrimaryToken(), SeMakeSystemToken(), and SepVariableInitialization().
SE_AUDITING_STATE SeAuditingState[]
Definition at line 285 of file seglobal.c.
Referenced by SeDetailedAuditingWithToken(), SepAdtAuditThisEventWithContext(), and SepRmSetAuditEventWrkr().
LUID SeAuditPrivilege
Definition at line 230 of file seglobal.c.
Referenced by SeCheckAuditPrivilege(), SeMakeSystemToken(), and SepVariableInitialization().
PSID SeAuthenticatedUsersSid
Definition at line 102 of file seglobal.c.
Referenced by SeMakeSystemToken(), and SepVariableInitialization().
LUID SeBackupPrivilege
Definition at line 226 of file seglobal.c.
Referenced by CmpDoCreate(), CmpDoOpen(), IopCheckBackupRestorePrivilege(), NtCompactKeys(), NtCompressKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), SeMakeSystemToken(), SepAdjustPrivileges(), and SepVariableInitialization().
PSID SeBatchSid
Definition at line 97 of file seglobal.c.
Referenced by SepVariableInitialization().
LUID SeChangeNotifyPrivilege
Definition at line 232 of file seglobal.c.
Referenced by SeMakeSystemToken(), SepAdjustPrivileges(), SepCreateToken(), SepRemoveDisabledGroupsAndPrivileges(), and SepVariableInitialization().
LUID SeCreateGlobalPrivilege
Definition at line 239 of file seglobal.c.
Referenced by ObpLookupObjectName(), SeMakeSystemToken(), and SepVariableInitialization().
LUID SeCreatePagefilePrivilege
Definition at line 220 of file seglobal.c.
Referenced by NtCreatePagingFile(), SeMakeSystemToken(), and SepVariableInitialization().
LUID SeCreatePermanentPrivilege
Definition at line 225 of file seglobal.c.
Referenced by NtMakePermanentObject(), ObCreateObject(), SeMakeSystemToken(), and SepVariableInitialization().
LUID SeCreateTokenPrivilege
Definition at line 211 of file seglobal.c.
Referenced by SeMakeSystemToken(), SepCreateToken(), and SepVariableInitialization().
PSID SeCreatorGroupServerSid
Definition at line 86 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeCreatorGroupSid
Definition at line 85 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeCreatorOwnerServerSid
Definition at line 87 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeCreatorOwnerSid
Definition at line 84 of file seglobal.c.
Referenced by ObpGetDosDevicesProtection(), and SepVariableInitialization().
LUID SeDebugPrivilege
Definition at line 229 of file seglobal.c.
Referenced by NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenThread(), NtSetInformationProcess(), NtSetInformationThread(), NtSetSystemInformation(), SeMakeSystemToken(), and SepVariableInitialization().
PSID SeDialupSid
Definition at line 95 of file seglobal.c.
Referenced by SepVariableInitialization().
LUID SeEnableDelegationPrivilege
Definition at line 236 of file seglobal.c.
Referenced by SepVariableInitialization().
NTKERNELAPI PSE_EXPORTS SeExports
Definition at line 256 of file seglobal.c.
Referenced by SePrivilegedServiceAuditAlarm(), and WmipInitializeSecurity().
LUID SeImpersonatePrivilege
Definition at line 238 of file seglobal.c.
Referenced by SeMakeSystemToken(), SepAdjustPrivileges(), SepCreateToken(), SepRemoveDisabledGroupsAndPrivileges(), and SepVariableInitialization().
LUID SeIncreaseBasePriorityPrivilege
Definition at line 221 of file seglobal.c.
Referenced by NtSetInformationJobObject(), NtSetInformationProcess(), NtSetInformationThread(), PspSetQuotaLimits(), SeMakeSystemToken(), and SepVariableInitialization().
LUID SeIncreaseQuotaPrivilege
Definition at line 214 of file seglobal.c.
Referenced by NtSetSystemInformation(), PspSetQuotaLimits(), SeMakeSystemToken(), and SepVariableInitialization().
PSID SeInteractiveSid
Definition at line 98 of file seglobal.c.
Referenced by SepVariableInitialization().
LUID SeLoadDriverPrivilege
Definition at line 219 of file seglobal.c.
Referenced by IopUnloadDriver(), NtLoadDriver(), NtSetSystemInformation(), SeMakeSystemToken(), and SepVariableInitialization().
PACL SeLocalServicePublicDacl
Definition at line 194 of file seglobal.c.
PSECURITY_DESCRIPTOR SeLocalServicePublicSd
Definition at line 152 of file seglobal.c.
Referenced by SepInitSystemDacls().
PSID SeLocalSid
Definition at line 83 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeLocalSystemSid
Definition at line 101 of file seglobal.c.
Referenced by ExpKeyedEventInitialization(), MiCreateMemoryEvent(), NtCreatePagingFile(), ObInitSystem(), ObpGetDosDevicesProtection(), SeMakeSystemToken(), SepAdtGenerateDiscardAudit(), SepAdtPrivilegeObjectAuditAlarm(), SepCreateImpersonationTokenDacl(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), SePrivilegedServiceAuditAlarm(), SepVariableInitialization(), SeRmInitPhase1(), WmipCreateAdminSD(), and WmipInitializeSecurity().
LUID SeLockMemoryPrivilege
Definition at line 213 of file seglobal.c.
Referenced by MiMapViewOfImageSection(), MmCreateSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtLockRegistryKey(), NtLockVirtualMemory(), NtUnlockVirtualMemory(), SeMakeSystemToken(), and SepVariableInitialization().
LUID SeManageVolumePrivilege
Definition at line 237 of file seglobal.c.
Referenced by SeMakeSystemToken(), and SepVariableInitialization().
PSID SeNetworkSid
Definition at line 96 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeNtAuthoritySid
Definition at line 93 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeNullSid
Definition at line 81 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SePrincipalSelfSid
Definition at line 100 of file seglobal.c.
Referenced by SepSidInSidAndAttributes(), SepSidInToken(), SepSidInTokenEx(), and SepVariableInitialization().
LUID SeProfileSingleProcessPrivilege
Definition at line 224 of file seglobal.c.
Referenced by SeMakeSystemToken(), and SepVariableInitialization().
PACL SePublicDefaultDacl
Definition at line 189 of file seglobal.c.
Referenced by IopCreateSecurityDescriptorPerType().
PSECURITY_DESCRIPTOR SePublicDefaultSd
Definition at line 142 of file seglobal.c.
Referenced by ExpInitializeCallbacks(), SepInitializationPhase1(), and SepInitSystemDacls().
PACL SePublicDefaultUnrestrictedDacl
Definition at line 190 of file seglobal.c.
Referenced by IopCreateDefaultDeviceSecurityDescriptor(), IopCreateSecurityDescriptorPerType(), and ObInitSystem().
PSECURITY_DESCRIPTOR SePublicDefaultUnrestrictedSd
Definition at line 144 of file seglobal.c.
Referenced by CreateSystemRootLink(), IoCreateSymbolicLink(), ObInitSystem(), and SepInitSystemDacls().
PACL SePublicOpenDacl
Definition at line 191 of file seglobal.c.
Referenced by IopCreateSecurityDescriptorPerType().
PSECURITY_DESCRIPTOR SePublicOpenSd
Definition at line 148 of file seglobal.c.
Referenced by SepInitSystemDacls().
PACL SePublicOpenUnrestrictedDacl
Definition at line 192 of file seglobal.c.
Referenced by IopCreateSecurityDescriptorPerType().
PSECURITY_DESCRIPTOR SePublicOpenUnrestrictedSd
Definition at line 146 of file seglobal.c.
Referenced by SepInitSystemDacls().
LUID SeRemoteShutdownPrivilege
Definition at line 233 of file seglobal.c.
Referenced by SepVariableInitialization().
LUID SeRestorePrivilege
Definition at line 227 of file seglobal.c.
Referenced by CmpDoCreate(), CmpDoOpen(), IopCheckBackupRestorePrivilege(), NtLoadKeyEx(), NtQueryOpenSubKeysEx(), NtReplaceKey(), NtRestoreKey(), NtUnloadKey2(), NtUnloadKeyEx(), SeMakeSystemToken(), SepAdjustPrivileges(), SepValidOwnerSubjectContext(), and SepVariableInitialization().
PSID SeRestrictedSid
Definition at line 104 of file seglobal.c.
Referenced by SepCreateImpersonationTokenDacl(), SepInitSystemDacls(), and SepVariableInitialization().
LUID SeSecurityPrivilege
Definition at line 217 of file seglobal.c.
Referenced by NtQueryInformationToken(), ObpIncrementHandleCount(), RtlpNewSecurityObject(), SeMakeSystemToken(), SepAccessCheck(), SepInitializePrivilegeSets(), SePrivilegePolicyCheck(), and SepVariableInitialization().
LUID SeShutdownPrivilege
Definition at line 228 of file seglobal.c.
Referenced by ExpRaiseHardError(), SeMakeSystemToken(), and SepVariableInitialization().
const UNICODE_STRING SeSubsystemName
Definition at line 318 of file seglobal.c.
Referenced by SeAuditHandleCreation(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCloseObjectAuditAlarm(), SeDeleteObjectAuditAlarm(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), SePrivilegedServiceAuditAlarm(), SePrivilegeObjectAuditAlarm(), and SeReportSecurityEvent().
LUID SeSyncAgentPrivilege
Definition at line 235 of file seglobal.c.
Referenced by SepVariableInitialization().
const LUID SeSystemAuthenticationId
Definition at line 73 of file seglobal.c.
Referenced by SeMakeSystemToken(), and SepRmDbInitialization().
PACL SeSystemDefaultDacl
Definition at line 193 of file seglobal.c.
Referenced by IopCreateSecurityDescriptorPerType(), and SeMakeSystemToken().
PSECURITY_DESCRIPTOR SeSystemDefaultSd
Definition at line 150 of file seglobal.c.
Referenced by SepInitSystemDacls().
LUID SeSystemEnvironmentPrivilege
Definition at line 231 of file seglobal.c.
Referenced by SeMakeSystemToken(), and SepVariableInitialization().
LUID SeSystemProfilePrivilege
Definition at line 222 of file seglobal.c.
Referenced by NtCreateProfile(), PerfInfoStartLog(), and SepVariableInitialization().
LUID SeSystemtimePrivilege
Definition at line 223 of file seglobal.c.
Referenced by NtSetSystemInformation(), SeMakeSystemToken(), and SepVariableInitialization().
const TOKEN_SOURCE SeSystemTokenSource
Definition at line 72 of file seglobal.c.
Referenced by SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), and SeMakeSystemToken().
LUID SeTakeOwnershipPrivilege
Definition at line 218 of file seglobal.c.
Referenced by SeMakeSystemToken(), SepAccessCheck(), SepInitializePrivilegeSets(), SePrivilegePolicyCheck(), and SepVariableInitialization().
LUID SeTcbPrivilege
Definition at line 216 of file seglobal.c.
Referenced by CmpRefreshHive(), NtSetDefaultHardErrorPort(), NtSetInformationObject(), NtSetInformationProcess(), NtSetInformationToken(), NtSetSystemInformation(), SeMakeSystemToken(), SepSinglePrivilegeCheck(), and SepVariableInitialization().
struct _OBJECT_TYPE* SeTokenObjectType
Definition at line 97 of file token.c.
Referenced by NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtDuplicateToken(), NtFilterToken(), NtOpenObjectAuditAlarm(), NtOpenProcessTokenEx(), NtOpenThreadTokenEx(), NtPrivilegeCheck(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryInformationToken(), NtSetInformationJobObject(), NtSetInformationToken(), PsAssignImpersonationToken(), PspAssignPrimaryToken(), PspSetPrimaryToken(), SeAccessCheckByType(), SepAccessCheckAndAuditAlarm(), SepDuplicateToken(), and SepFilterToken().
LUID SeUndockPrivilege
Definition at line 234 of file seglobal.c.
Referenced by SeMakeSystemToken(), and SepVariableInitialization().
PACL SeUnrestrictedDacl
LUID SeUnsolicitedInputPrivilege
Definition at line 215 of file seglobal.c.
Referenced by SepVariableInitialization().
PSID SeWorldSid
Definition at line 82 of file seglobal.c.
Referenced by ExpKeyedEventInitialization(), IopCreateDefaultDeviceSecurityDescriptor(), MiCreateMemoryEvent(), ObInitSystem(), ObpGetDosDevicesProtection(), SeAssignWorldSecurityDescriptor(), SeFastTraverseCheck(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SepExamineSacl(), SepExamineSaclEx(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepInitSystemDacls(), and SepVariableInitialization().