Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/qsquota.c File Reference
qsquota.c File Reference
#include "iomgr.h"
Macros
#define ALIGN_LONG(Address) ((Address + 3) & ~3)
Functions
NTSTATUS NtQueryQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(SidListLength) PVOID SidList, __in ULONG SidListLength, __in_opt PULONG StartSid, __in BOOLEAN RestartScan)
NTSTATUS NtSetQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
Macro Definition Documentation
#define ALIGN_LONG (Address) ((Address + 3) & ~3)
Referenced by NtQueryQuotaInformationFile().
Function Documentation
NTSTATUS NtQueryQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(SidListLength) PVOID SidList, __in ULONG SidListLength, __in_opt PULONG StartSid, __in BOOLEAN RestartScan)
Definition at line 26 of file qsquota.c.
References ALIGN_LONG, ARGUMENT_PRESENT, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCheckGetQuotaBufferValidity(), IopExceptionCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_QUERY_QUOTA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUchar, ProbeForRead, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), RtlCopyMemory, RtlLengthRequiredSid(), RtlValidSid(), SL_INDEX_SPECIFIED, SL_RESTART_SCAN, SL_RETURN_SINGLE_ENTRY, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_SID, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSTATUS NtSetQuotaInformationFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
Definition at line 609 of file qsquota.c.
References FALSE, IopSetEaOrQuotaInformationFile(), and PAGED_CODE.