Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/stktrace.c File Reference
stktrace.c File Reference
#include <ntos.h>
#include <ntrtl.h>
#include "ntrtlp.h"
#include <nturtl.h>
#include <zwapi.h>
#include <stktrace.h>
Data Structures
struct _KSPIN_LOCK_EX
Macros
#define ACQUIRE_DATABASE_LOCK(R) KeAcquireSpinLockEx((PKSPIN_LOCK_EX)R)
#define INITIALIZE_DATABASE_LOCK(R) KeInitializeSpinLockEx((PKSPIN_LOCK_EX)R)
#define NUMBER_OF_BUCKETS 1567
#define OKAY_TO_LOCK_DATABASE(R) ExOkayToLockRoutine(&(((PKSPIN_LOCK_EX)R)->Lock))
#define RELEASE_DATABASE_LOCK(R) KeReleaseSpinLockEx((PKSPIN_LOCK_EX)R)
Typedefs
typedef struct _KSPIN_LOCK_EX KSPIN_LOCK_EX
typedef struct _KSPIN_LOCK_EX * PKSPIN_LOCK_EX
Functions
BOOLEAN ExOkayToLockRoutine (IN PVOID Lock)
VOID KeAcquireSpinLockEx (PKSPIN_LOCK_EX Lock)
NTSTATUS KeInitializeSpinLockEx (PKSPIN_LOCK_EX Lock)
VOID KeReleaseSpinLockEx (PKSPIN_LOCK_EX Lock)
NTSTATUS RtlInitializeStackTraceDataBase (IN PVOID CommitBase, IN SIZE_T CommitSize, IN SIZE_T ReserveSize)
USHORT RtlLogStackBackTrace (VOID)
USHORT RtlLogUmodeStackBackTrace (VOID)
PSTACK_TRACE_DATABASE RtlpAcquireStackTraceDataBase ()
LOGICAL RtlpCaptureStackTraceForLogging (PRTL_STACK_TRACE_ENTRY Trace, PULONG Hash, ULONG FramesToSkip, LOGICAL UserModeStackFromKernelMode)
PRTL_STACK_TRACE_ENTRY RtlpExtendStackTraceDataBase (IN PRTL_STACK_TRACE_ENTRY InitialValue, IN SIZE_T Size)
PVOID RtlpGetStackTraceAddress (USHORT Index)
USHORT RtlpLogCapturedStackTrace (PRTL_STACK_TRACE_ENTRY Trace, ULONG Hash)
USHORT RtlpLogStackBackTraceEx (ULONG FramesToSkip)
VOID RtlpReleaseStackTraceDataBase ()
ULONG RtlpWalkFrameChainExceptionFilter (ULONG ExceptionCode, PVOID ExceptionRecord)
Variables
BOOLEAN RtlpFuzzyStackTracesEnabled
PSTACK_TRACE_DATABASE RtlpStackTraceDataBase
KSPIN_LOCK_EX RtlpStackTraceDataBaseLock
Macro Definition Documentation
#define ACQUIRE_DATABASE_LOCK (R) KeAcquireSpinLockEx((PKSPIN_LOCK_EX)R)
Definition at line 79 of file stktrace.c.
Referenced by RtlpAcquireStackTraceDataBase().
#define INITIALIZE_DATABASE_LOCK (R) KeInitializeSpinLockEx((PKSPIN_LOCK_EX)R)
Definition at line 78 of file stktrace.c.
Referenced by RtlInitializeStackTraceDataBase().
#define NUMBER_OF_BUCKETS 1567
Definition at line 32 of file stktrace.c.
Referenced by RtlInitializeStackTraceDataBase().
#define OKAY_TO_LOCK_DATABASE (R) ExOkayToLockRoutine(&(((PKSPIN_LOCK_EX)R)->Lock))
Definition at line 81 of file stktrace.c.
Referenced by RtlpAcquireStackTraceDataBase(), and RtlpLogStackBackTraceEx().
#define RELEASE_DATABASE_LOCK (R) KeReleaseSpinLockEx((PKSPIN_LOCK_EX)R)
Definition at line 80 of file stktrace.c.
Referenced by RtlpAcquireStackTraceDataBase(), and RtlpReleaseStackTraceDataBase().
Typedef Documentation
typedef struct _KSPIN_LOCK_EX KSPIN_LOCK_EX
typedef struct _KSPIN_LOCK_EX * PKSPIN_LOCK_EX
Function Documentation
BOOLEAN ExOkayToLockRoutine (IN PVOID Lock)
Definition at line 257 of file pool.c.
References FALSE, KeIsExecutingDpc(), TRUE, and UNREFERENCED_PARAMETER.
VOID KeAcquireSpinLockEx (PKSPIN_LOCK_EX Lock)
Definition at line 61 of file stktrace.c.
References KeAcquireSpinLock, KeGetCurrentThread(), _KSPIN_LOCK_EX::Lock, _KSPIN_LOCK_EX::OldIrql, and _KSPIN_LOCK_EX::Owner.
NTSTATUS KeInitializeSpinLockEx (PKSPIN_LOCK_EX Lock)
Definition at line 50 of file stktrace.c.
References KeInitializeSpinLock(), _KSPIN_LOCK_EX::Lock, NULL, _KSPIN_LOCK_EX::OldIrql, _KSPIN_LOCK_EX::Owner, and STATUS_SUCCESS.
VOID KeReleaseSpinLockEx (PKSPIN_LOCK_EX Lock)
Definition at line 70 of file stktrace.c.
References KeReleaseSpinLock(), _KSPIN_LOCK_EX::Lock, NULL, _KSPIN_LOCK_EX::OldIrql, and _KSPIN_LOCK_EX::Owner.
NTSTATUS RtlInitializeStackTraceDataBase (IN PVOID CommitBase, IN SIZE_T CommitSize, IN SIZE_T ReserveSize)
Definition at line 212 of file stktrace.c.
References _STACK_TRACE_DATABASE::Buckets, _STACK_TRACE_DATABASE::CommitBase, _STACK_TRACE_DATABASE::CurrentLowerCommitLimit, _STACK_TRACE_DATABASE::CurrentUpperCommitLimit, _STACK_TRACE_DATABASE::EntryIndexArray, FALSE, INITIALIZE_DATABASE_LOCK, KdPrint, _STACK_TRACE_DATABASE::Lock, MEM_COMMIT, _STACK_TRACE_DATABASE::NextFreeLowerMemory, _STACK_TRACE_DATABASE::NextFreeUpperMemory, NT_SUCCESS, NtCurrentProcess, NUMBER_OF_BUCKETS, _STACK_TRACE_DATABASE::NumberOfBuckets, PAGE_READWRITE, _STACK_TRACE_DATABASE::PreCommitted, ROUND_TO_PAGES, RtlZeroMemory, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, and ZwAllocateVirtualMemory().
Referenced by ExpInitializeExecutive().
USHORT RtlLogStackBackTrace (VOID)
Definition at line 496 of file stktrace.c.
References RtlpLogStackBackTraceEx().
Referenced by ExInitializeResourceLite(), ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
USHORT RtlLogUmodeStackBackTrace (VOID)
Definition at line 610 of file stktrace.c.
References FALSE, NULL, RtlpCaptureStackTraceForLogging(), RtlpLogCapturedStackTrace(), and TRUE.
Referenced by ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
PSTACK_TRACE_DATABASE RtlpAcquireStackTraceDataBase ()
Definition at line 158 of file stktrace.c.
References ACQUIRE_DATABASE_LOCK, _STACK_TRACE_DATABASE::DumpInProgress, _STACK_TRACE_DATABASE::Lock, NULL, OKAY_TO_LOCK_DATABASE, RELEASE_DATABASE_LOCK, and RtlpStackTraceDataBase.
Referenced by RtlpLogCapturedStackTrace().
LOGICAL RtlpCaptureStackTraceForLogging (PRTL_STACK_TRACE_ENTRY Trace, PULONG Hash, ULONG FramesToSkip, LOGICAL UserModeStackFromKernelMode)
Definition at line 672 of file stktrace.c.
References _RTL_STACK_TRACE_ENTRY::BackTrace, _RTL_STACK_TRACE_ENTRY::Depth, except, EXCEPTION_EXECUTE_HANDLER, FALSE, Index, KeAreAllApcsDisabled(), MAX_STACK_DEPTH, PtrToUlong, RtlCaptureStackBackTrace(), RtlWalkFrameChain(), and TRUE.
Referenced by RtlLogUmodeStackBackTrace(), and RtlpLogStackBackTraceEx().
PRTL_STACK_TRACE_ENTRY RtlpExtendStackTraceDataBase (IN PRTL_STACK_TRACE_ENTRY InitialValue, IN SIZE_T Size)
Definition at line 301 of file stktrace.c.
References _STACK_TRACE_DATABASE::CurrentLowerCommitLimit, _STACK_TRACE_DATABASE::CurrentUpperCommitLimit, _RTL_STACK_TRACE_ENTRY::HashChain, _RTL_STACK_TRACE_ENTRY::Index, MEM_COMMIT, _STACK_TRACE_DATABASE::NextFreeLowerMemory, _STACK_TRACE_DATABASE::NextFreeUpperMemory, NT_SUCCESS, NtCurrentProcess, NULL, _STACK_TRACE_DATABASE::NumberOfEntriesAdded, PAGE_READWRITE, PAGE_SIZE, _STACK_TRACE_DATABASE::PreCommitted, RtlMoveMemory, RtlpStackTraceDataBase, Status, _RTL_STACK_TRACE_ENTRY::TraceCount, and ZwAllocateVirtualMemory().
Referenced by RtlpLogCapturedStackTrace().
PVOID RtlpGetStackTraceAddress (USHORT Index)
Definition at line 905 of file stktrace.c.
References _STACK_TRACE_DATABASE::EntryIndexArray, Index, and NULL.
USHORT RtlpLogCapturedStackTrace (PRTL_STACK_TRACE_ENTRY Trace, ULONG Hash)
Definition at line 746 of file stktrace.c.
References _RTL_STACK_TRACE_ENTRY::BackTrace, _STACK_TRACE_DATABASE::Buckets, _RTL_STACK_TRACE_ENTRY::Depth, except, EXCEPTION_EXECUTE_HANDLER, FIELD_OFFSET, _RTL_STACK_TRACE_ENTRY::HashChain, _RTL_STACK_TRACE_ENTRY::Index, NULL, _STACK_TRACE_DATABASE::NumberOfBuckets, _STACK_TRACE_DATABASE::NumberOfEntriesLookedUp, RtlCompareMemory(), RtlpAcquireStackTraceDataBase(), RtlpExtendStackTraceDataBase(), RtlpReleaseStackTraceDataBase(), RtlpStackTraceDataBase, and _RTL_STACK_TRACE_ENTRY::TraceCount.
Referenced by RtlLogUmodeStackBackTrace(), and RtlpLogStackBackTraceEx().
USHORT RtlpLogStackBackTraceEx (ULONG FramesToSkip)
Definition at line 535 of file stktrace.c.
References FALSE, _STACK_TRACE_DATABASE::Lock, NULL, OKAY_TO_LOCK_DATABASE, RtlpCaptureStackTraceForLogging(), RtlpLogCapturedStackTrace(), RtlpStackTraceDataBase, and Status.
Referenced by RtlLogStackBackTrace().
VOID RtlpReleaseStackTraceDataBase ()
Definition at line 192 of file stktrace.c.
References _STACK_TRACE_DATABASE::Lock, NULL, RELEASE_DATABASE_LOCK, and RtlpStackTraceDataBase.
Referenced by RtlpLogCapturedStackTrace().
ULONG RtlpWalkFrameChainExceptionFilter (ULONG ExceptionCode, PVOID ExceptionRecord)
Definition at line 922 of file stktrace.c.
References DbgBreakPoint(), DbgPrint(), EXCEPTION_EXECUTE_HANDLER, and STATUS_IN_PAGE_ERROR.
Referenced by RtlpWalkFrameChain(), and RtlWalkFrameChain().
Variable Documentation
BOOLEAN RtlpFuzzyStackTracesEnabled
PSTACK_TRACE_DATABASE RtlpStackTraceDataBase
Definition at line 128 of file stktrace.c.
Referenced by RtlpAcquireStackTraceDataBase(), RtlpExtendStackTraceDataBase(), RtlpLogCapturedStackTrace(), RtlpLogStackBackTraceEx(), and RtlpReleaseStackTraceDataBase().
KSPIN_LOCK_EX RtlpStackTraceDataBaseLock
Definition at line 138 of file stktrace.c.