Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/timer.c File Reference
timer.c File Reference
#include "exp.h"
Data Structures
struct _ETIMER
Typedefs
typedef struct _ETIMER ETIMER
typedef struct _ETIMER * PETIMER
Functions
VOID ExGetNextWakeTime (OUT PULONGLONG DueTime, OUT PTIME_FIELDS TimeFields, OUT PVOID *TimerObject)
VOID ExpDeleteTimer (IN PVOID Object)
VOID ExpTimerApcRoutine (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID ExpTimerDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
BOOLEAN ExpTimerInitialization (VOID)
VOID ExTimerRundown (VOID)
NTSTATUS NtCancelTimer (__in HANDLE TimerHandle, __out_opt PBOOLEAN CurrentState)
NTSTATUS NtCreateTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in TIMER_TYPE TimerType)
NTSTATUS NtOpenTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQueryTimer (__in HANDLE TimerHandle, __in TIMER_INFORMATION_CLASS TimerInformationClass, __out_bcount(TimerInformationLength) PVOID TimerInformation, __in ULONG TimerInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtSetTimer (__in HANDLE TimerHandle, __in PLARGE_INTEGER DueTime, __in_opt PTIMER_APC_ROUTINE TimerApcRoutine, __in_opt PVOID TimerContext, __in BOOLEAN WakeTimer, __in_opt LONG Period, __out_opt PBOOLEAN PreviousState)
Variables
const GENERIC_MAPPING ExpTimerMapping
LIST_ENTRY ExpWakeTimerList
KSPIN_LOCK ExpWakeTimerListLock
POBJECT_TYPE ExTimerObjectType
Typedef Documentation
typedef struct _ETIMER ETIMER
typedef struct _ETIMER * PETIMER
Function Documentation
VOID ExGetNextWakeTime (OUT PULONGLONG DueTime, OUT PTIME_FIELDS TimeFields, OUT PVOID * TimerObject)
Definition at line 1218 of file timer.c.
References CONTAINING_RECORD, ExAcquireSpinLock, ExpWakeTimerListLock, ExReleaseSpinLock, ExSystemTimeToLocalTime(), _LIST_ENTRY::Flink, KeQueryInterruptTime(), KeQuerySystemTime(), KeQueryTimerDueTime(), _ETIMER::KeTimer, NULL, _LARGE_INTEGER::QuadPart, RemoveEntryList(), RtlTimeToTimeFields(), _ETIMER::WakeTimer, and _ETIMER::WakeTimerListEntry.
VOID ExpDeleteTimer (IN PVOID Object)
Definition at line 267 of file timer.c.
References ExAcquireSpinLock, ExpWakeTimerListLock, ExReleaseSpinLock, _LIST_ENTRY::Flink, KeCancelTimer(), KeFlushQueuedDpcs(), _ETIMER::KeTimer, NULL, RemoveEntryList(), and _ETIMER::WakeTimerListEntry.
Referenced by ExpTimerInitialization().
VOID ExpTimerApcRoutine (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 78 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, CONTAINING_RECORD, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _ETIMER::Lock, NULL, ObDereferenceObjectEx(), _ETIMER::Period, PsGetCurrentThread(), RemoveEntryList(), _ETHREAD::Tcb, _KAPC::Thread, _ETIMER::TimerApc, and UNREFERENCED_PARAMETER.
Referenced by NtSetTimer().
VOID ExpTimerDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 164 of file timer.c.
References _ETIMER::ApcAssociated, ExAcquireSpinLockAtDpcLevel, except, ExReleaseSpinLockFromDpcLevel, FALSE, KeInsertQueueApc(), _ETIMER::KeTimer, _ETIMER::Lock, ObDereferenceObject(), ObReferenceObjectSafe(), TIMER_APC_INCREMENT, _ETIMER::TimerApc, and UNREFERENCED_PARAMETER.
Referenced by NtCreateTimer().
BOOLEAN ExpTimerInitialization (VOID)
Definition at line 324 of file timer.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExpDeleteTimer(), ExpTimerMapping, ExpWakeTimerListLock, _OBJECT_TYPE_INITIALIZER::GenericMapping, InitializeListHead(), _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KeInitializeSpinLock(), _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, Status, TIMER_ALL_ACCESS, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
VOID ExTimerRundown (VOID)
Definition at line 392 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListHead, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, CONTAINING_RECORD, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, KeCancelTimer(), KeRemoveQueueApc(), KeRemoveQueueDpc(), _ETIMER::KeTimer, _ETIMER::Lock, ObDereferenceObjectEx(), ObReferenceObject, PsGetCurrentThread(), RemoveEntryList(), _ETHREAD::Tcb, _KAPC::Thread, _ETIMER::TimerApc, and _ETIMER::TimerDpc.
Referenced by PspExitThread().
NTSTATUS NtCancelTimer (__in HANDLE TimerHandle, __out_opt PBOOLEAN CurrentState)
Definition at line 710 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, except, EXCEPTION_EXECUTE_HANDLER, ExpWakeTimerListLock, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, KeCancelTimer(), KeGetPreviousMode, KeReadStateTimer(), KeRemoveQueueApc(), KeRemoveQueueDpc(), KernelMode, _ETIMER::KeTimer, _ETIMER::Lock, NOTHING, NT_SUCCESS, NULL, ObDereferenceObjectEx(), ObReferenceObjectByHandle, ProbeForWriteBoolean, RemoveEntryList(), Status, _KAPC::Thread, TIMER_MODIFY_STATE, _ETIMER::TimerApc, _ETIMER::TimerDpc, and _ETIMER::WakeTimerListEntry.
NTSTATUS NtCreateTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in TIMER_TYPE TimerType)
Definition at line 488 of file timer.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExpTimerDpcRoutine(), FALSE, Handle, KeGetPreviousMode, KeInitializeDpc(), KeInitializeSpinLock(), KeInitializeTimerEx(), KernelMode, NOTHING, NotificationTimer, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, Status, STATUS_INVALID_PARAMETER_4, SynchronizationTimer, and _ETIMER::TimerDpc.
NTSTATUS NtOpenTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 620 of file timer.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSTATUS NtQueryTimer (__in HANDLE TimerHandle, __in TIMER_INFORMATION_CLASS TimerInformationClass, __out_bcount(TimerInformationLength) PVOID TimerInformation, __in ULONG TimerInformationLength, __out_opt PULONG ReturnLength)
Definition at line 846 of file timer.c.
References ARGUMENT_PRESENT, _KTIMER::DueTime, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeReadStateTimer(), KernelMode, _ETIMER::KeTimer, KiQueryInterruptTime, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, _TIMER_BASIC_INFORMATION::RemainingTime, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, TIMER_QUERY_STATE, TimerBasicInformation, and _TIMER_BASIC_INFORMATION::TimerState.
NTSTATUS NtSetTimer (__in HANDLE TimerHandle, __in PLARGE_INTEGER DueTime, __in_opt PTIMER_APC_ROUTINE TimerApcRoutine, __in_opt PVOID TimerContext, __in BOOLEAN WakeTimer, __in_opt LONG Period, __out_opt PBOOLEAN PreviousState)
Definition at line 981 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListHead, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, ARGUMENT_PRESENT, CONTAINING_RECORD, CurrentApcEnvironment, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, except, EXCEPTION_EXECUTE_HANDLER, ExpTimerApcRoutine(), ExpWakeTimerListLock, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, InsertTailList(), KeCancelTimer(), KeGetPreviousMode, KeInitializeApc(), KeReadStateTimer(), KeRemoveQueueApc(), KeRemoveQueueDpc(), KernelMode, KeSetTimerEx(), _ETIMER::KeTimer, _ETIMER::Lock, NOTHING, NT_SUCCESS, NULL, ObDereferenceObjectEx(), ObReferenceObjectByHandle, _ETIMER::Period, PoWakeTimerSupported, ProbeForReadSmallStructure, ProbeForWriteBoolean, PsGetCurrentThread(), RemoveEntryList(), Status, STATUS_INVALID_PARAMETER_6, STATUS_TIMER_RESUME_IGNORED, _ETHREAD::Tcb, _KAPC::Thread, TIMER_MODIFY_STATE, _ETIMER::TimerApc, _ETIMER::TimerDpc, TRUE, _ETIMER::WakeTimer, and _ETIMER::WakeTimerListEntry.
Variable Documentation
const GENERIC_MAPPING ExpTimerMapping
Initial value:
= {
    STANDARD_RIGHTS_READ | TIMER_QUERY_STATE,
    STANDARD_RIGHTS_WRITE | TIMER_MODIFY_STATE,
    STANDARD_RIGHTS_EXECUTE | SYNCHRONIZE,
    TIMER_ALL_ACCESS
}
Definition at line 60 of file timer.c.
Referenced by ExpTimerInitialization().
LIST_ENTRY ExpWakeTimerList
Definition at line 43 of file timer.c.
KSPIN_LOCK ExpWakeTimerListLock
Definition at line 42 of file timer.c.
Referenced by ExGetNextWakeTime(), ExpDeleteTimer(), ExpTimerInitialization(), NtCancelTimer(), and NtSetTimer().
POBJECT_TYPE ExTimerObjectType
Definition at line 49 of file timer.c.