Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/i386/psctx386.c File Reference
psctx386.c File Reference
#include "psp.h"
Functions
VOID PspGetContext (IN PKTRAP_FRAME TrapFrame, IN PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN OUT PCONTEXT Context)
VOID PspGetSetContextSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID PspSetContext (OUT PKTRAP_FRAME TrapFrame, OUT PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN PCONTEXT Context, KPROCESSOR_MODE Mode)
Function Documentation
VOID PspGetContext (IN PKTRAP_FRAME TrapFrame, IN PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN OUT PCONTEXT Context)
Definition at line 37 of file psctx386.c.
References CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXCEPTION_FLAGS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, CONTEXT_SEGMENTS, DR7_ACTIVE, KeContextFromKframes(), NULL, PAGED_CODE, RPL_MASK, and UNREFERENCED_PARAMETER.
Referenced by PspGetSetContextSpecialApc().
VOID PspGetSetContextSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 117 of file psctx386.c.
References CONTAINING_RECORD, _GETSETCONTEXT::Context, FALSE, KernelMode, KeSetEvent(), _GETSETCONTEXT::Mode, NULL, _GETSETCONTEXT::OperationComplete, PAGED_CODE, PspGetBaseTrapFrame, PspGetContext(), PspSetContext(), _ETHREAD::Tcb, _KTHREAD::TrapFrame, and UNREFERENCED_PARAMETER.
Referenced by PsGetContextThread(), and PsSetContextThread().
VOID PspSetContext (OUT PKTRAP_FRAME TrapFrame, OUT PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN PCONTEXT Context, KPROCESSOR_MODE Mode)
Definition at line 76 of file psctx386.c.
References CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, _DISPATCHER_HEADER::DebugActive, DR7_ACTIVE, _KTHREAD::Header, KeContextToKframes(), KeGetCurrentThread(), KernelMode, NULL, PAGED_CODE, RPL_MASK, SANITIZE_DR7, SANITIZE_DRADDR, SANITIZE_MXCSR, UNREFERENCED_PARAMETER, and UserMode.
Referenced by PspGetSetContextSpecialApc().