Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/atom.c File Reference
atom.c File Reference
#include "ntrtlp.h"
#include "atom.h"
Data Structures
struct _RTLP_ATOM_QUOTA
Typedefs
typedef struct _RTLP_ATOM_QUOTA * PRTLP_ATOM_QUOTA
typedef struct _RTLP_ATOM_QUOTA RTLP_ATOM_QUOTA
Functions
NTSTATUS RtlAddAtomToAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __inout_opt PRTL_ATOM Atom)
NTSTATUS RtlCreateAtomTable (IN ULONG NumberOfBuckets, OUT PVOID *AtomTableHandle)
NTSTATUS RtlDeleteAtomFromAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
NTSTATUS RtlDestroyAtomTable (IN PVOID AtomTableHandle)
NTSTATUS RtlEmptyAtomTable (IN PVOID AtomTableHandle, IN BOOLEAN IncludePinnedAtoms)
NTSTATUS RtlInitializeAtomPackage (IN ULONG AllocationTag)
NTSTATUS RtlLookupAtomInAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __out_opt PRTL_ATOM Atom)
PVOID RtlpAllocateAtom (IN ULONG NumberOfBytes, IN ULONG Tag)
PRTL_ATOM_TABLE_ENTRY RtlpAtomMapAtomToHandleEntry (IN PRTL_ATOM_TABLE AtomTable, IN ULONG HandleIndex)
BOOLEAN RtlpCreateHandleForAtom (PRTL_ATOM_TABLE p, PRTL_ATOM_TABLE_ENTRY a)
void RtlpDestroyHandleTableForAtomTable (PRTL_ATOM_TABLE AtomTable)
void RtlpDestroyLockAtomTable (IN OUT PRTL_ATOM_TABLE AtomTable)
void RtlpFreeAtom (IN PVOID p)
void RtlpFreeHandleForAtom (PRTL_ATOM_TABLE p, PRTL_ATOM_TABLE_ENTRY a)
BOOLEAN RtlpGetIntegerAtom (PWSTR Name, PRTL_ATOM Atom OPTIONAL)
PRTL_ATOM_TABLE_ENTRY RtlpHashStringToAtom (IN PRTL_ATOM_TABLE p, IN PWSTR Name, OUT PRTL_ATOM_TABLE_ENTRY **PreviousAtom OPTIONAL, OUT PULONG NameLength)
NTSTATUS RtlPinAtomInAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
BOOLEAN RtlpInitializeHandleTableForAtomTable (PRTL_ATOM_TABLE AtomTable)
void RtlpInitializeLockAtomTable (IN OUT PRTL_ATOM_TABLE AtomTable)
BOOLEAN RtlpLockAtomTable (IN PRTL_ATOM_TABLE AtomTable)
void RtlpUnlockAtomTable (IN PRTL_ATOM_TABLE AtomTable)
NTSTATUS RtlQueryAtomInAtomTable (__in PVOID AtomTableHandle, __in RTL_ATOM Atom, __out_opt PULONG AtomUsage, __out_opt PULONG AtomFlags, __inout_bcount_part_opt(*AtomNameLength,*AtomNameLength) PWSTR AtomName, __inout_opt PULONG AtomNameLength)
NTSTATUS RtlQueryAtomsInAtomTable (IN PVOID AtomTableHandle, IN ULONG MaximumNumberOfAtoms, OUT PULONG NumberOfAtoms, OUT PRTL_ATOM Atoms)
Variables
ULONG RtlpAtomAllocateTag
Typedef Documentation
typedef struct _RTLP_ATOM_QUOTA * PRTLP_ATOM_QUOTA
typedef struct _RTLP_ATOM_QUOTA RTLP_ATOM_QUOTA
Function Documentation
NTSTATUS RtlAddAtomToAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __inout_opt PRTL_ATOM Atom)
Definition at line 581 of file atom.c.
References ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, FIELD_OFFSET, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::HandleIndex, _RTL_ATOM_TABLE_ENTRY::HashLink, KdPrint, _RTL_ATOM_TABLE_ENTRY::Name, _RTL_ATOM_TABLE_ENTRY::NameLength, NULL, _RTL_ATOM_TABLE_ENTRY::ReferenceCount, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlCopyMemory, RtlpAllocateAtom(), RtlpCreateHandleForAtom(), RtlpFreeAtom(), RtlpGetIntegerAtom(), RtlpHashStringToAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtAddAtom().
NTSTATUS RtlCreateAtomTable (IN ULONG NumberOfBuckets, OUT PVOID * AtomTableHandle)
Definition at line 313 of file atom.c.
References NULL, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_ATOM_TABLE_DEFAULT_NUMBER_OF_BUCKETS, RTL_ATOM_TABLE_SIGNATURE, RTL_PAGED_CODE, RtlpAllocateAtom(), RtlpFreeAtom(), RtlpInitializeHandleTableForAtomTable(), RtlpInitializeLockAtomTable(), RtlZeroMemory, _RTL_ATOM_TABLE::Signature, Status, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS RtlDeleteAtomFromAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
Definition at line 740 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::HashLink, KdPrint, _RTL_ATOM_TABLE_ENTRY::Name, NULL, _RTL_ATOM_TABLE_ENTRY::ReferenceCount, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlpAtomMapAtomToHandleEntry(), RtlpFreeAtom(), RtlpFreeHandleForAtom(), RtlpHashStringToAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and STATUS_WAS_LOCKED.
Referenced by NtDeleteAtom().
NTSTATUS RtlDestroyAtomTable (IN PVOID AtomTableHandle)
Definition at line 356 of file atom.c.
References _RTL_ATOM_TABLE::Buckets, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::HashLink, NULL, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_PAGED_CODE, RtlpDestroyHandleTableForAtomTable(), RtlpDestroyLockAtomTable(), RtlpFreeAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), RtlZeroMemory, _RTL_ATOM_TABLE::Signature, Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlEmptyAtomTable (IN PVOID AtomTableHandle, IN BOOLEAN IncludePinnedAtoms)
Definition at line 397 of file atom.c.
References _RTL_ATOM_TABLE::Buckets, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::HashLink, NULL, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlpFreeAtom(), RtlpFreeHandleForAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlInitializeAtomPackage (IN ULONG AllocationTag)
Definition at line 303 of file atom.c.
References RTL_PAGED_CODE, RtlpAtomAllocateTag, and STATUS_SUCCESS.
Referenced by ExpInitSystemPhase1().
NTSTATUS RtlLookupAtomInAtomTable (__in PVOID AtomTableHandle, __in PWSTR AtomName, __out_opt PRTL_ATOM Atom)
Definition at line 678 of file atom.c.
References ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::HandleIndex, NULL, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_PAGED_CODE, RtlpAtomMapAtomToHandleEntry(), RtlpGetIntegerAtom(), RtlpHashStringToAtom(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_INVALID, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtFindAtom().
PVOID RtlpAllocateAtom (IN ULONG NumberOfBytes, IN ULONG Tag)
Definition at line 123 of file atom.c.
References ExAllocatePoolWithTag, ExFreePoolWithTag, NULL, NumberOfBytes, _RTLP_ATOM_QUOTA::PagedAmount, PagedPool, PsChargeSharedPoolQuota(), PsGetCurrentProcess(), and _RTLP_ATOM_QUOTA::QuotaBlock.
Referenced by RtlAddAtomToAtomTable(), and RtlCreateAtomTable().
PRTL_ATOM_TABLE_ENTRY RtlpAtomMapAtomToHandleEntry (IN PRTL_ATOM_TABLE AtomTable, IN ULONG HandleIndex)
Definition at line 245 of file atom.c.
References ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _EXHANDLE::GenericHandleOverlay, _EXHANDLE::Index, NULL, and _HANDLE_TABLE_ENTRY::Object.
Referenced by RtlDeleteAtomFromAtomTable(), RtlLookupAtomInAtomTable(), RtlpHashStringToAtom(), RtlPinAtomInAtomTable(), and RtlQueryAtomInAtomTable().
BOOLEAN RtlpCreateHandleForAtom (PRTL_ATOM_TABLE p, PRTL_ATOM_TABLE_ENTRY a)
Definition at line 269 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, ExCreateHandle(), FALSE, _EXHANDLE::GenericHandleOverlay, _HANDLE_TABLE_ENTRY::GrantedAccess, _RTL_ATOM_TABLE_ENTRY::HandleIndex, _EXHANDLE::Index, NULL, _HANDLE_TABLE_ENTRY::Object, RTL_ATOM_MAXIMUM_INTEGER_ATOM, and TRUE.
Referenced by RtlAddAtomToAtomTable().
void RtlpDestroyHandleTableForAtomTable (PRTL_ATOM_TABLE AtomTable)
Definition at line 236 of file atom.c.
References ExDestroyHandleTable(), and NULL.
Referenced by RtlDestroyAtomTable().
void RtlpDestroyLockAtomTable (IN OUT PRTL_ATOM_TABLE AtomTable)
Definition at line 209 of file atom.c.
Referenced by RtlDestroyAtomTable().
void RtlpFreeAtom (IN PVOID p)
Definition at line 154 of file atom.c.
References ASSERT, ExFreePool(), _RTLP_ATOM_QUOTA::PagedAmount, PsReturnSharedPoolQuota(), and _RTLP_ATOM_QUOTA::QuotaBlock.
Referenced by RtlAddAtomToAtomTable(), RtlCreateAtomTable(), RtlDeleteAtomFromAtomTable(), RtlDestroyAtomTable(), and RtlEmptyAtomTable().
void RtlpFreeHandleForAtom (PRTL_ATOM_TABLE p, PRTL_ATOM_TABLE_ENTRY a)
Definition at line 289 of file atom.c.
References ExDestroyHandle(), _EXHANDLE::GenericHandleOverlay, _RTL_ATOM_TABLE_ENTRY::HandleIndex, _EXHANDLE::Index, and NULL.
Referenced by RtlDeleteAtomFromAtomTable(), and RtlEmptyAtomTable().
BOOLEAN RtlpGetIntegerAtom (PWSTR Name, PRTL_ATOM Atom OPTIONAL)
Definition at line 439 of file atom.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, FALSE, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, PtrToUlong, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RtlUnicodeStringToInteger(), Status, TRUE, and UNICODE_NULL.
Referenced by RtlAddAtomToAtomTable(), and RtlLookupAtomInAtomTable().
PRTL_ATOM_TABLE_ENTRY RtlpHashStringToAtom (IN PRTL_ATOM_TABLE p, IN PWSTR Name, OUT PRTL_ATOM_TABLE_ENTRY **PreviousAtom OPTIONAL, OUT PULONG NameLength)
Definition at line 505 of file atom.c.
References _wcsicmp(), ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::HashLink, _RTL_ATOM_TABLE_ENTRY::Name, _RTL_ATOM_TABLE_ENTRY::NameLength, NOTHING, NULL, PtrToUlong, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_MAXIMUM_NAME_LENGTH, RtlpAtomMapAtomToHandleEntry(), RtlUpcaseUnicodeChar(), and UNICODE_NULL.
Referenced by RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), and RtlLookupAtomInAtomTable().
NTSTATUS RtlPinAtomInAtomTable (IN PVOID AtomTableHandle, IN RTL_ATOM Atom)
Definition at line 793 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, NULL, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlpAtomMapAtomToHandleEntry(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
BOOLEAN RtlpInitializeHandleTableForAtomTable (PRTL_ATOM_TABLE AtomTable)
Definition at line 217 of file atom.c.
References ExCreateHandleTable(), ExRemoveHandleTable(), FALSE, NULL, and TRUE.
Referenced by RtlCreateAtomTable().
void RtlpInitializeLockAtomTable (IN OUT PRTL_ATOM_TABLE AtomTable)
Definition at line 175 of file atom.c.
References ExInitializePushLock().
Referenced by RtlCreateAtomTable().
BOOLEAN RtlpLockAtomTable (IN PRTL_ATOM_TABLE AtomTable)
Definition at line 184 of file atom.c.
References ExAcquirePushLockExclusive(), FALSE, KeEnterCriticalRegion(), NULL, RTL_ATOM_TABLE_SIGNATURE, and TRUE.
Referenced by RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), RtlDestroyAtomTable(), RtlEmptyAtomTable(), RtlLookupAtomInAtomTable(), RtlPinAtomInAtomTable(), RtlQueryAtomInAtomTable(), and RtlQueryAtomsInAtomTable().
void RtlpUnlockAtomTable (IN PRTL_ATOM_TABLE AtomTable)
Definition at line 199 of file atom.c.
References ExReleasePushLockExclusive(), and KeLeaveCriticalRegion().
Referenced by RtlAddAtomToAtomTable(), RtlDeleteAtomFromAtomTable(), RtlDestroyAtomTable(), RtlEmptyAtomTable(), RtlLookupAtomInAtomTable(), RtlPinAtomInAtomTable(), RtlQueryAtomInAtomTable(), and RtlQueryAtomsInAtomTable().
NTSTATUS RtlQueryAtomInAtomTable (__in PVOID AtomTableHandle, __in RTL_ATOM Atom, __out_opt PULONG AtomUsage, __out_opt PULONG AtomFlags, __inout_bcount_part_opt *,*AtomNameLength PWSTR AtomName, __inout_opt PULONG AtomNameLength)
Definition at line 832 of file atom.c.
References _snwprintf, ARGUMENT_PRESENT, _RTL_ATOM_TABLE_ENTRY::Atom, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::Flags, _RTL_ATOM_TABLE_ENTRY::Name, _RTL_ATOM_TABLE_ENTRY::NameLength, NULL, _RTL_ATOM_TABLE_ENTRY::ReferenceCount, RTL_ATOM_INVALID_ATOM, RTL_ATOM_MAXIMUM_INTEGER_ATOM, RTL_ATOM_PINNED, RTL_PAGED_CODE, RtlCopyMemory, RtlpAtomMapAtomToHandleEntry(), RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtQueryInformationAtom().
NTSTATUS RtlQueryAtomsInAtomTable (IN PVOID AtomTableHandle, IN ULONG MaximumNumberOfAtoms, OUT PULONG NumberOfAtoms, OUT PRTL_ATOM Atoms)
Definition at line 947 of file atom.c.
References _RTL_ATOM_TABLE_ENTRY::Atom, _RTL_ATOM_TABLE::Buckets, except, EXCEPTION_EXECUTE_HANDLER, _RTL_ATOM_TABLE_ENTRY::HashLink, _RTL_ATOM_TABLE::NumberOfBuckets, RTL_PAGED_CODE, RtlpLockAtomTable(), RtlpUnlockAtomTable(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtQueryInformationAtom().
Variable Documentation
ULONG RtlpAtomAllocateTag
Definition at line 115 of file atom.c.
Referenced by RtlInitializeAtomPackage().