Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmapi.c File Reference
cmapi.c File Reference
#include "cmp.h"
Macros
#define LogHiveLoad(a, b)
Functions
NTSTATUS CmCompressKey (IN PHHIVE Hive)
NTSTATUS CmDeleteValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName)
NTSTATUS CmEnumerateKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmEnumerateValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmFlushKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN BOOLEAN RegistryLockOwnedExclusive)
NTSTATUS CmLoadKey (IN POBJECT_ATTRIBUTES TargetKey, IN POBJECT_ATTRIBUTES SourceFile, IN ULONG Flags, IN PCM_KEY_BODY KeyBody)
NTSTATUS CmLockKcbForWrite (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
NTSTATUS CmMoveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock)
VALUE_SEARCH_RETURN_TYPE CmpCompareNewValueDataAgainstKCBCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PUNICODE_STRING ValueName, ULONG Type, PVOID Data, ULONG DataSize)
ULONG CmpCompressKeyWorker (PCM_KEY_CONTROL_BLOCK Current, PVOID Context1, PVOID Context2)
VOID CmpDereferenceNameControlBlockWithLock (PCM_NAME_CONTROL_BLOCK Ncb)
VOID CmpDestroyTemporaryHive (PCMHIVE CmHive)
BOOLEAN CmpDoFlushAll (BOOLEAN ForceFlush)
BOOLEAN CmpDoFlushNextHive (BOOLEAN ForceFlush, PBOOLEAN PostWarning, PULONG DirtyCount)
VOID CmpDoQueueLateUnloadWorker (IN PCMHIVE CmHive)
NTSTATUS CmpDuplicateKey (PHHIVE Hive, HCELL_INDEX OldKeyCell, PHCELL_INDEX NewKeyCell)
BOOLEAN CmpGetHiveName (PCMHIVE CmHive, PUNICODE_STRING HiveName)
PCM_KEY_CONTROL_BLOCK CmpInsertKeyHash (IN PCM_KEY_HASH KeyHash, IN BOOLEAN FakeKey)
BOOLEAN CmpIsHiveAlreadyLoaded (IN HANDLE KeyHandle, IN POBJECT_ATTRIBUTES SourceFile, OUT PCMHIVE *CmHive)
VOID CmpRemoveKeyHash (IN PCM_KEY_HASH KeyHash)
NTSTATUS CmpSetValueKeyExisting (IN PHHIVE Hive, IN HCELL_INDEX OldChild, IN PCM_KEY_VALUE Value, IN ULONG Type, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN ULONG TempData)
NTSTATUS CmpSetValueKeyNew (IN PHHIVE Hive, IN PCM_KEY_NODE Parent, IN PUNICODE_STRING ValueName, IN ULONG Index, IN ULONG Type, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN ULONG TempData)
NTSTATUS CmQueryKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmQueryMultipleValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PKEY_VALUE_ENTRY ValueEntries, IN ULONG EntryCount, IN PVOID ValueBuffer, IN OUT PULONG BufferLength, IN OPTIONAL PULONG ResultLength)
NTSTATUS CmQueryValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
NTSTATUS CmRenameKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING NewKeyName, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS CmSetKeyUserFlags (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG UserFlags)
NTSTATUS CmSetLastWriteTimeKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PLARGE_INTEGER LastWriteTime)
NTSTATUS CmSetValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING ValueName, IN ULONG Type, IN PVOID Data, IN ULONG DataSize)
NTSTATUS CmUnloadKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN ULONG Flags, IN ULONG ControlFlags)
NTSTATUS CmUnloadKeyEx (IN PCM_KEY_CONTROL_BLOCK kcb, IN PKEVENT UserEvent)
Variables
BOOLEAN CmpForceForceFlush
ULONG CmpLazyFlushCount
ULONG CmpLazyFlushHiveCount
HIVE_LIST_ENTRY CmpMachineHiveList []
BOOLEAN CmpNoWrite
BOOLEAN CmpProfileLoaded
BOOLEAN CmpWasSetupBoot
UNICODE_STRING CmSymbolicLinkValueName
Macro Definition Documentation
#define LogHiveLoad (a, b)
Definition at line 2642 of file cmapi.c.
Referenced by CmLoadKey().
Function Documentation
NTSTATUS CmCompressKey (IN PHHIVE Hive)
Definition at line 4466 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, _CMHIVE::CellRemapArray, _CM_KEY_NODE::ChildHiveReference, CmKdPrintEx, CML_CM, CmpBuildSecurityCellMappingArray(), CmpCleanUpKCBCacheTable(), CmpCompressKeyWorker(), CmpDestroyTemporaryHive(), CmpMasterHive, CmpOverwriteHive(), CmpSearchKeyControlBlockTree(), CmpShiftHiveFreeBins(), CmpSwitchStorageAndRebuildMappings(), CmpUpdateSystemHiveHysteresis(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, _CMHIVE::Hive, HvAutoCompressCheck(), HvGetCell, HvpDropAllPagedBins(), HvReleaseCell, IsListEmpty, _CMHIVE::KcbConvertListHead, _CM_KEY_REFERENCE::KeyCell, _CMHIVE::KnodeConvertListHead, _HBASE_BLOCK::Length, NT_SUCCESS, NULL, PAGED_CODE, _CM_KEY_NODE::Parent, RemoveHeadList(), _HBASE_BLOCK::RootCell, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by CmShutdownSystem(), and NtCompressKey().
NTSTATUS CmDeleteValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName)
Definition at line 169 of file cmapi.c.
References ASSERT, ASSERT_CELL_DIRTY, Cell, CmKdPrintEx, CML_CM, CmpCleanUpKcbValueCache(), CmpFindNameInList(), CmpFreeValue(), CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpMarkValueDataDirty(), CmpRemoveValueFromList(), CmpReportNotify(), CmpSetUpKcbValueCache, CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), _CHILD_LIST::Count, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, Hive, HvGetCell, HvMarkCellDirty(), HvReleaseCell, KeQuerySystemTime(), _CM_KEY_NODE::LastWriteTime, leave, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PERFINFO_REG_DELETE_VALUE, REG_NOTIFY_CHANGE_LAST_SET, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and _CM_KEY_NODE::ValueList.
Referenced by NtDeleteValueKey().
NTSTATUS CmEnumerateKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 400 of file cmapi.c.
References Cell, CmKdPrintEx, CML_CM, CmpFindSubKeyByNumber(), CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyData(), CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), NULL, PERFINFO_REG_ENUM_KEY, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, and STATUS_NO_MORE_ENTRIES.
Referenced by NtEnumerateKey().
NTSTATUS CmEnumerateValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG Index, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 573 of file cmapi.c.
References ASSERT, CM_KCB_SYM_LINK_FOUND, CmKdPrintEx, CML_CM, CML_EXCEPTION, CmpCleanUpKcbValueCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpIsKCBLockedExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyValueData(), CmpSetUpKcbValueCache, CmpTryConvertKCBLockSharedToExclusive(), CmpUnlockKCB, CmpUnlockRegistry(), CmpUpgradeKCBLockToExclusive, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, _CHILD_LIST::List, NULL, PERFINFO_REG_ENUM_VALUE, SearchNeedExclusiveLock, SearchSuccess, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_MORE_ENTRIES, and _CM_KEY_NODE::ValueList.
Referenced by NtEnumerateValueKey().
NTSTATUS CmFlushKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN BOOLEAN RegistryLockOwnedExclusive)
Definition at line 802 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE_OR_HIVE_LOADING, ASSERT_KCB_LOCKED, CmKdPrintEx, CML_BUGCHECK, CML_CM, CmLockHiveViews, CmpDoFlushAll(), CmpFixHiveUsageCount(), CmpLockHiveFlusherExclusive, CmpLockKCBShared, CmpLockRegistryExclusive(), CmpMarkAllBinsReadOnly, CmpMasterHive, CmpNoWrite, CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CmUnlockHiveViews, CONTAINING_RECORD, DCmCheckRegistry, DPFLTR_CONFIG_ID, FALSE, Hive, _CMHIVE::Hive, HvHiveWillShrink(), HvSyncHive(), STATUS_KEY_DELETED, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, and _CMHIVE::UseCount.
Referenced by CmUnloadKey(), and NtFlushKey().
NTSTATUS CmLoadKey (IN POBJECT_ATTRIBUTES TargetKey, IN POBJECT_ATTRIBUTES SourceFile, IN ULONG Flags, IN PCM_KEY_BODY KeyBody)
Definition at line 2645 of file cmapi.c.
References ASSERT, CM_CHECK_REGISTRY_CHECK_CLEAN, CM_CMHIVE_FLAG_UNTRUSTED, CmpAddToHiveFileList(), CmpCmdHiveClose(), CmpCmdHiveOpen(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpIsHiveAlreadyLoaded(), CmpJoinClassOfTrust, CmpKeyObjectType, CmpLinkHiveToMaster(), CmpLockHiveFlusherExclusive, CmpLockHiveListExclusive, CmpLockRegistry(), CmpLockRegistryExclusive(), CmpProfileLoaded, CmpRemoveEntryList, CmpSetGlobalQuotaAllowed(), CmpUnJoinClassOfTrust, CmpUnlockHiveFlusher, CmpUnlockHiveList, CmpUnlockRegistry(), CmpWasSetupBoot, CONTAINING_RECORD, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _CM_PARSE_CONTEXT::CreateOperation, _CMHIVE::CreatorOwner, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, FALSE, _CMHIVE::Flags, Hive, _CMHIVE::Hive, HIVE_IS_UNLOADING, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvFreeHive(), HvSyncHive(), _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, KeGetCurrentThread(), KernelMode, KEY_READ, _SECURITY_QUALITY_OF_SERVICE::Length, LOCK_HIVE_LOAD, LogHiveLoad, NT_SUCCESS, NULL, ObOpenObjectByName(), REG_NO_LAZY_FLUSH, RtlZeroMemory, SeCreateClientSecurity(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, SeDeleteClientSecurity, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, UNLOCK_HIVE_LOAD, and ZwClose().
Referenced by NtLoadKeyEx().
NTSTATUS CmLockKcbForWrite (PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 4656 of file cmapi.c.
References ASSERT, ASSERT_KCB, CM_KCB_NO_DELAY_CLOSE, CM_KCB_READ_ONLY_KEY, CM_PAGED_CODE, CmpLockKCBExclusive, CmpUnlockKCB, _CM_KEY_CONTROL_BLOCK::Delete, _CM_KEY_CONTROL_BLOCK::ExtFlags, InterlockedIncrement, _CM_KEY_CONTROL_BLOCK::RefCount, STATUS_KEY_DELETED, and STATUS_SUCCESS.
Referenced by NtLockRegistryKey().
NTSTATUS CmMoveKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock)
Definition at line 4004 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CmKdPrintEx, CML_CM, CmpCleanUpSubKeyInfo(), CmpDuplicateKey(), CmpFreeKeyByCell(), CmpMarkKeyDirty(), CmpRebuildKcbCache(), CmpUpdateParentForEachSon(), _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, DBG, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, Hive, HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, KEY_SYM_LINK, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NT_SUCCESS, NULL, PAGED_CODE, _CM_KEY_NODE::Parent, _HBASE_BLOCK::RootCell, _CM_KEY_INDEX::Signature, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and Volatile.
Referenced by NtCompactKeys().
VALUE_SEARCH_RETURN_TYPE CmpCompareNewValueDataAgainstKCBCache (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PUNICODE_STRING ValueName, ULONG Type, PVOID Data, ULONG DataSize)
Definition at line 4701 of file cmapi.c.
References ASSERT, ASSERT_KCB_LOCKED, CM_KEY_VALUE_SPECIAL_SIZE, CM_PAGED_CODE, CmpCleanUpKcbValueCache(), CmpFindValueByNameFromCache(), CmpGetValueDataFromCache(), CmpIsHKeyValueSmall, CmpIsKCBLockedExclusive, CmpSetUpKcbValueCache, CmpTryConvertKCBLockSharedToExclusive(), _CHILD_LIST::Count, _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, HvGetCell, HvReleaseCell, Index, KEY_SYM_LINK, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CHILD_LIST::List, NULL, RtlCompareMemory(), SearchFail, SearchNeedExclusiveLock, SearchSuccess, TRUE, _CM_KEY_VALUE::Type, and _CM_KEY_NODE::ValueList.
Referenced by CmSetValueKey().
ULONG CmpCompressKeyWorker (PCM_KEY_CONTROL_BLOCK Current, PVOID Context1, PVOID Context2)
Definition at line 4435 of file cmapi.c.
References ASSERT, ExAllocatePool, HCELL_NIL, InsertTailList(), KCB_WORKER_CONTINUE, KCB_WORKER_ERROR, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KCB_REMAP_BLOCK::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KCB_REMAP_BLOCK::NewCellIndex, NULL, _CM_KCB_REMAP_BLOCK::OldCellIndex, PagedPool, _CM_KCB_REMAP_BLOCK::RemapList, _CM_KCB_REMAP_BLOCK::ValueCount, and _CM_KCB_REMAP_BLOCK::ValueList.
Referenced by CmCompressKey().
VOID CmpDereferenceNameControlBlockWithLock (PCM_NAME_CONTROL_BLOCK Ncb)
Definition at line 1125 of file cmsubs.c.
Referenced by CmRenameKey().
VOID CmpDestroyTemporaryHive (PCMHIVE CmHive)
Definition at line 1830 of file cmsavres.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_SAVRES, CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpLockHiveListExclusive, CmpRemoveEntryList, CmpUnJoinClassOfTrust, CmpUnlockHiveList, DPFLTR_CONFIG_ID, _CMHIVE::FlusherLock, _CMHIVE::Hive, _CMHIVE::HiveList, HvFreeHive(), NULL, and _CMHIVE::ViewLock.
Referenced by CmCompressKey(), CmpLoadHiveVolatile(), CmpShiftHiveFreeBins(), CmRestoreKey(), CmSaveKey(), and CmSaveMergedKeys().
BOOLEAN CmpDoFlushAll (BOOLEAN ForceFlush)
Definition at line 3235 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmKdPrintEx, CML_IO, CmpFixHiveUsageCount(), CmpHiveListHead, CmpLockHiveFlusherExclusive, CmpLockHiveListShared, CmpNoWrite, CmpUnlockHiveFlusher, CmpUnlockHiveList, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _LIST_ENTRY::Flink, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HvHiveWillShrink(), HvSyncHive(), NT_SUCCESS, Stable, Status, TRUE, and _CMHIVE::UseCount.
Referenced by CmFlushKey(), CmpUnlockRegistry(), and CmShutdownSystem().
BOOLEAN CmpDoFlushNextHive (BOOLEAN ForceFlush, PBOOLEAN PostWarning, PULONG DirtyCount)
Definition at line 3357 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmKdPrintEx, CML_IO, CmpDoQueueLateUnloadWorker(), CmpFixHiveUsageCount(), CmpHiveListHead, CmpLazyFlushCount, CmpLazyFlushHiveCount, CmpLockHiveFlusherExclusive, CmpLockHiveListShared, CmpNoWrite, CmpUnlockHiveFlusher, CmpUnlockHiveList, CONTAINING_RECORD, _HHIVE::DirtyCount, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _LIST_ENTRY::Flink, _CMHIVE::FlushCount, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, HIVE_VOLATILE, _HHIVE::HiveFlags, HvHiveWillShrink(), HvSyncHive(), IsHiveFrozen, NT_SUCCESS, Stable, Status, TRUE, and _CMHIVE::UseCount.
Referenced by CmpLazyFlushWorker().
VOID CmpDoQueueLateUnloadWorker (IN PCMHIVE CmHive)
Definition at line 186 of file cmdelete.c.
Referenced by CmpDoFlushNextHive().
NTSTATUS CmpDuplicateKey (PHHIVE Hive, HCELL_INDEX OldKeyCell, PHCELL_INDEX NewKeyCell)
Definition at line 4343 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmpCopyKeyPartial(), CmpDuplicateIndex(), CmpFreeKeyByCell(), FALSE, HCELL_NIL, HvGetCell, HvGetCellType, HvReleaseCell, NULL, PAGED_CODE, _CM_KEY_NODE::Parent, _HHIVE::ReleaseCellRoutine, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, and Volatile.
Referenced by CmMoveKey().
BOOLEAN CmpGetHiveName (PCMHIVE CmHive, PUNICODE_STRING HiveName)
Definition at line 233 of file cmhvlist.c.
Referenced by CmUnloadKey().
PCM_KEY_CONTROL_BLOCK CmpInsertKeyHash (IN PCM_KEY_HASH KeyHash, IN BOOLEAN FakeKey)
Definition at line 2288 of file cmsubs.c.
References ASSERT_KEY_HASH, CONTAINING_RECORD, _CM_KEY_HASH::ConvKey, _CM_KEY_HASH_TABLE_ENTRY::Entry, GET_HASH_INDEX, Index, _CM_KEY_HASH::KeyCell, _CM_KEY_HASH::KeyHive, _CM_KEY_HASH::NextHash, and NULL.
Referenced by CmpCreateKeyControlBlock(), CmpRehashKcbSubtree(), and CmRenameKey().
BOOLEAN CmpIsHiveAlreadyLoaded (IN HANDLE KeyHandle, IN POBJECT_ATTRIBUTES SourceFile, OUT PCMHIVE * CmHive)
Definition at line 2558 of file cmapi.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_PAGED_CODE, CmpDereferenceKeyControlBlockWithLock(), CmpKeyObjectType, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::Delete, FALSE, _CM_KEY_CONTROL_BLOCK::Flags, Hive, IsHiveFrozen, KernelMode, KEY_HIVE_ENTRY, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, RtlCompareUnicodeString(), and TRUE.
Referenced by CmLoadKey().
VOID CmpRemoveKeyHash (IN PCM_KEY_HASH KeyHash)
Definition at line 2368 of file cmsubs.c.
References ASSERT, ASSERT_KEY_HASH, _CM_KEY_HASH_TABLE_ENTRY::Entry, GET_HASH_INDEX, Index, _CM_KEY_HASH::NextHash, NULL, and TRUE.
Referenced by CmpRehashKcbSubtree(), CmpRemoveKeyControlBlock(), and CmRenameKey().
NTSTATUS CmpSetValueKeyExisting (IN PHHIVE Hive, IN HCELL_INDEX OldChild, IN PCM_KEY_VALUE Value, IN ULONG Type, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN ULONG TempData)
Definition at line 1883 of file cmapi.c.
References ASSERT, ASSERT_CELL_DIRTY, ASSERT_HIVE_FLUSHER_LOCKED, CM_KEY_VALUE_SMALL, CM_KEY_VALUE_SPECIAL_SIZE, CmpFreeValueData(), CmpIsHKeyValueBig, CmpIsHKeyValueSmall, CmpMarkValueDataDirty(), CmpSetValueDataExisting(), CmpSetValueDataNew(), FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellSize(), HvGetCellType, HvMarkCellDirty(), HvReallocateCell(), HvReleaseCell, MM_HIGHEST_USER_ADDRESS, MmSecureVirtualMemory(), MmUnsecureVirtualMemory(), NT_SUCCESS, NULL, PAGE_READONLY, RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, and TRUE.
Referenced by CmSetValueKey().
NTSTATUS CmpSetValueKeyNew (IN PHHIVE Hive, IN PCM_KEY_NODE Parent, IN PUNICODE_STRING ValueName, IN ULONG Index, IN ULONG Type, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN ULONG TempData)
Definition at line 2204 of file cmapi.c.
References ASSERT, ASSERT_CELL_DIRTY, ASSERT_HIVE_FLUSHER_LOCKED, CM_KEY_VALUE_SIGNATURE, CM_KEY_VALUE_SMALL, CM_KEY_VALUE_SPECIAL_SIZE, CmKdPrintEx, CML_EXCEPTION, CmpAddValueToList(), CmpCopyName(), CmpFreeValue(), CmpHKeyValueSize, CmpSetValueDataNew(), _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_KEY_VALUE::Flags, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvMarkCellDirty(), HvReleaseCell, _CELL_DATA::_u::KeyValue, _CM_KEY_VALUE::Name, _CM_KEY_VALUE::NameLength, NT_SUCCESS, NULL, _CM_KEY_VALUE::Signature, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_VALUE::Type, _CELL_DATA::u, and VALUE_COMP_NAME.
Referenced by CmSetValueKey().
NTSTATUS CmQueryKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN KEY_INFORMATION_CLASS KeyInformationClass, IN PVOID KeyInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 922 of file cmapi.c.
References _UNICODE_STRING::Buffer, CmKdPrintEx, CML_CM, CmpConstructName(), CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyData(), CmpQueryKeyDataFromCache(), CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, ExFreePoolWithTag, FIELD_OFFSET, HvGetCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), KEY_USER_FLAGS_SHIFT, KeyCachedInformation, KeyFlagsInformation, _KEY_INFORMATION::KeyFlagsInformation, KeyNameInformation, _KEY_INFORMATION::KeyNameInformation, _UNICODE_STRING::Length, _KEY_NAME_INFORMATION::Name, _KEY_NAME_INFORMATION::NameLength, NULL, PERFINFO_REG_QUERY_KEY, PROTECTED_POOL, RtlCopyMemory, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and _KEY_FLAGS_INFORMATION::UserFlags.
Referenced by NtQueryKey().
NTSTATUS CmQueryMultipleValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PKEY_VALUE_ENTRY ValueEntries, IN ULONG EntryCount, IN PVOID ValueBuffer, IN OUT PULONG BufferLength, IN OPTIONAL PULONG ResultLength)
Definition at line 1306 of file cmapi.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_CM, CmpFindValueByName(), CmpGetValueData(), CmpIsHKeyValueSmall, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpUnlockKCB, CmpUnlockRegistry(), _CM_KEY_VALUE::DataLength, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, KeGetPreviousMode, _UNICODE_STRING::Length, NT_SUCCESS, NULL, PAGED_CODE, PERFINFO_REG_QUERY_MULTIVALUE, ProbeAndReadUnicodeStringEx, ProbeForRead, RtlCopyMemory, Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, _CM_KEY_VALUE::Type, and UserMode.
Referenced by NtQueryMultipleValueKey().
NTSTATUS CmQueryValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING ValueName, IN KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, IN PVOID KeyValueInformation, IN ULONG Length, IN PULONG ResultLength)
Definition at line 1127 of file cmapi.c.
References ASSERT, CM_KCB_SYM_LINK_FOUND, CM_PAGED_CODE, CmKdPrintEx, CML_CM, CML_EXCEPTION, CmpCleanUpKcbValueCache(), CmpFindValueByNameFromCache(), CmpIsKCBLockedExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpQueryKeyValueData(), CmpSetUpKcbValueCache, CmpTryConvertKCBLockSharedToExclusive(), CmpUnlockKCB, CmpUnlockRegistry(), CmpUpgradeKCBLockToExclusive, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, HvGetCell, HvReleaseCell, Index, _CHILD_LIST::List, NULL, PERFINFO_REG_QUERY_VALUE, SearchNeedExclusiveLock, SearchSuccess, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_OBJECT_NAME_NOT_FOUND, and _CM_KEY_NODE::ValueList.
Referenced by NtQueryValueKey().
NTSTATUS CmRenameKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN UNICODE_STRING NewKeyName, IN KPROCESSOR_MODE PreviousMode)
Definition at line 3540 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmKdPrintEx, CML_CM, CML_EXCEPTION, CMP_KCB_REAL_NAME_UPCASE, CmpAddSubKey(), CmpCheckKeyAccess(), CmpCleanUpSubKeyInfo(), CmpComputeKcbConvKey(), CmpCopyName(), CmpDereferenceNameControlBlockWithLock(), CmpDoAccessCheckOnSubtree(), CmpDuplicateIndex(), CmpFindSubKeyByName(), CmpGetNameControlBlock(), CmpHKeyNodeSize, CmpInsertKeyHash(), CmpMarkIndexDirty(), CmpMasterHive, CmpRemoveKeyHash(), CmpRemoveSubKey(), CmpSearchForOpenSubKeys(), CmpUpdateParentForEachSon(), _CM_KEY_INDEX::Count, DELETE, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, ExFreePoolWithTag, FALSE, FIELD_OFFSET, _CM_KEY_NODE::Flags, HCELL_NIL, Hive, _CMHIVE::Hive, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, Index, KeQuerySystemTime(), KEY_COMP_NAME, KEY_CREATE_SUB_KEY, _CM_KEY_NODE::LastWriteTime, _CM_KEY_INDEX::List, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, RtlCopyMemory, SearchAndRehash, _CM_KEY_INDEX::Signature, Status, STATUS_ACCESS_DENIED, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by NtRenameKey().
NTSTATUS CmSetKeyUserFlags (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN ULONG UserFlags)
Definition at line 2452 of file cmapi.c.
References Cell, CmKdPrintEx, CML_CM, CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockRegistry(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, Hive, HvGetCell, HvMarkCellDirty(), HvReleaseCell, KeQuerySystemTime(), KEY_USER_FLAGS_CLEAR_MASK, KEY_USER_FLAGS_SHIFT, KEY_USER_FLAGS_VALID_MASK, _CM_KEY_NODE::LastWriteTime, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationKey().
NTSTATUS CmSetLastWriteTimeKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PLARGE_INTEGER LastWriteTime)
Definition at line 2370 of file cmapi.c.
References Cell, CmKdPrintEx, CML_CM, CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockRegistry(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), DPFLTR_CONFIG_ID, FALSE, Hive, HvGetCell, HvMarkCellDirty(), HvReleaseCell, _CM_KEY_NODE::LastWriteTime, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationKey().
NTSTATUS CmSetValueKey (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING ValueName, IN ULONG Type, IN PVOID Data, IN ULONG DataSize)
Definition at line 1505 of file cmapi.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, Cell, CM_KEY_VALUE_SMALL, CmKdPrintEx, CML_CM, CML_EXCEPTION, CMP_GET_CACHED_ADDRESS, CMP_GET_CACHED_CELLDATA, CMP_IS_CELL_CACHED, CmpCleanUpKcbValueCache(), CmpCompareNewValueDataAgainstKCBCache(), CmpFindNameInList(), CmpIsKCBLockedExclusive, CmpLockHiveFlusherShared, CmpLockKCBShared, CmpLockRegistry(), CmpMarkAllBinsReadOnly, CmpReportNotify(), CmpSetUpKcbValueCache, CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpTryConvertKCBLockSharedToExclusive(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CmpUpgradeKCBLockToExclusive, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, HCELL_NIL, Hive, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, KeQuerySystemTime(), KEY_SYM_LINK, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, NT_SUCCESS, NULL, PERFINFO_REG_SET_VALUE, PERFINFO_REG_SET_VALUE_DECL, PERFINFO_REG_SET_VALUE_DONE, PERFINFO_REG_SET_VALUE_EXIST, PERFINFO_REG_SET_VALUE_NEW, REG_LINK, REG_NOTIFY_CHANGE_LAST_SET, RtlCopyMemory, RtlEqualUnicodeString(), SearchNeedExclusiveLock, SearchSuccess, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, TRUE, and _CM_KEY_NODE::ValueList.
Referenced by NtSetValueKey().
NTSTATUS CmUnloadKey (IN PCM_KEY_CONTROL_BLOCK Kcb, IN ULONG Flags, IN ULONG ControlFlags)
Definition at line 2930 of file cmapi.c.
References ASSERT, _HHIVE::BaseBlock, Cell, CM_UNLOAD_KCB_LOCKED, CM_UNLOAD_REG_LOCKED_EX, CmFlushKey(), CmKdPrintEx, CML_CM, CmpCleanUpSubKeyInfo(), CmpCmdHiveClose(), CmpDestroyHive(), CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFlushNotifiesOnKeyBodyList(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpGetHiveName(), CmpIsKCBLockedExclusive, CmpLockTwoHashEntriesExclusive(), CmpMasterHive, CmpRemoveFromHiveFileList(), CmpRemoveKeyControlBlock(), CmpSearchForOpenSubKeys(), CmpSearchKeyControlBlockTree(), CmpUnJoinClassOfTrust, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _CMHIVE::FlusherLock, Hive, HIVE_IS_UNLOADING, _HHIVE::HiveFlags, HvFreeHive(), InterlockedCompareExchangePointer, KeEnterCriticalRegion(), KeLeaveCriticalRegion(), KeSetEvent(), NULL, ObDereferenceObject(), REG_FORCE_UNLOAD, _HBASE_BLOCK::RootCell, RtlFreeUnicodeString(), SearchAndDeref, SearchIfExist, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_TOO_LATE, TRUE, _CMHIVE::UnloadEvent, _CMHIVE::UnloadWorkItem, UNLOCK_HIVE_LOAD, and _CMHIVE::ViewLock.
Referenced by CmpLateUnloadHiveWorker(), CmUnloadKeyEx(), and NtUnloadKey2().
NTSTATUS CmUnloadKeyEx (IN PCM_KEY_CONTROL_BLOCK kcb, IN PKEVENT UserEvent)
Definition at line 3144 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, Cell, CM_KCB_NO_DELAY_CLOSE, CM_PAGED_CODE, CM_UNLOAD_REG_LOCKED_EX, CmpReferenceKeyControlBlock(), CmpSearchForOpenSubKeys(), CmUnloadKey(), CONTAINING_RECORD, _CMHIVE::Frozen, Hive, IsHiveFrozen, NULL, _CMHIVE::RootKcb, SearchAndTagNoDelayClose, Status, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_TOO_LATE, TRUE, and _CMHIVE::UnloadEvent.
Referenced by NtUnloadKeyEx().
Variable Documentation
BOOLEAN CmpForceForceFlush
Definition at line 65 of file cmworker.c.
Referenced by CmpLazyFlushWorker().
ULONG CmpLazyFlushCount
Definition at line 554 of file cmworker.c.
Referenced by CmpDoFlushNextHive(), and CmpLazyFlushWorker().
ULONG CmpLazyFlushHiveCount
Definition at line 42 of file cmworker.c.
Referenced by CmpDoFlushNextHive().
HIVE_LIST_ENTRY CmpMachineHiveList[]
Definition at line 284 of file cmdat.c.
BOOLEAN CmpNoWrite
Definition at line 330 of file cmdat.c.
Referenced by CmFlushKey(), CmpDoFlushAll(), and CmpDoFlushNextHive().
BOOLEAN CmpProfileLoaded
Definition at line 62 of file cmdat2.c.
Referenced by CmLoadKey().
BOOLEAN CmpWasSetupBoot
Definition at line 363 of file cmdat.c.
Referenced by CmLoadKey().
UNICODE_STRING CmSymbolicLinkValueName
Definition at line 222 of file cmdat.c.