Windows Research Kernel v1.2: C:/Windows Research Kernel/raw/create.c File Reference
create.c File Reference
#include "RawProcs.h"
Functions
NTSTATUS RawCreate (IN PVCB Vcb, IN PIRP Irp, IN PIO_STACK_LOCATION IrpSp)
Function Documentation
NTSTATUS RawCreate (IN PVCB Vcb, IN PIRP Irp, IN PIO_STACK_LOCATION IrpSp)
Definition at line 28 of file create.c.
References ASSERT, Executive, FALSE, FILE_DIRECTORY_FILE, FILE_OPEN, FILE_OPENED, FlagOn, FO_NO_INTERMEDIATE_BUFFERING, IoCheckShareAccess(), IoSetShareAccess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, PAGED_CODE, RawCheckForDismount(), RawCompleteRequest, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_VOLUME_DISMOUNTED, TRUE, VCB_STATE_FLAG_DISMOUNTED, VCB_STATE_FLAG_LOCKED, and VOID.
Referenced by RawDispatch().