Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/keyedevent.c File Reference
keyedevent.c File Reference
#include "exp.h"
Data Structures
struct _KEYED_EVENT_OBJECT
Macros
#define KEYVALUE_RELEASE 1
#define LOCK_KEYED_EVENT_EXCLUSIVE(xxxKeyedEventObject, xxxCurrentThread)
#define UNLOCK_KEYED_EVENT_EXCLUSIVE(xxxKeyedEventObject, xxxCurrentThread)
#define UNLOCK_KEYED_EVENT_EXCLUSIVE_UNSAFE(xxxKeyedEventObject)
Typedefs
typedef struct _KEYED_EVENT_OBJECT KEYED_EVENT_OBJECT
typedef struct _KEYED_EVENT_OBJECT * PKEYED_EVENT_OBJECT
Functions
NTSTATUS ExpKeyedEventInitialization (VOID)
NTSTATUS NtCreateKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Flags)
NTSTATUS NtOpenKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtReleaseKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSTATUS NtWaitForKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Variables
POBJECT_TYPE ExpKeyedEventObjectType
Macro Definition Documentation
#define KEYVALUE_RELEASE 1
Definition at line 43 of file keyedevent.c.
Referenced by NtReleaseKeyedEvent(), and NtWaitForKeyedEvent().
#define LOCK_KEYED_EVENT_EXCLUSIVE (xxxKeyedEventObject, xxxCurrentThread)
Value:
{ \
    KeEnterCriticalRegionThread (&(xxxCurrentThread)->Tcb);                \
    ExAcquirePushLockExclusive (&(xxxKeyedEventObject)->Lock);             \
}
Definition at line 45 of file keyedevent.c.
Referenced by NtReleaseKeyedEvent(), and NtWaitForKeyedEvent().
#define UNLOCK_KEYED_EVENT_EXCLUSIVE (xxxKeyedEventObject, xxxCurrentThread)
Value:
{ \
    ExReleasePushLockExclusive (&(xxxKeyedEventObject)->Lock);               \
    KeLeaveCriticalRegionThread (&(xxxCurrentThread)->Tcb);                  \
}
Definition at line 50 of file keyedevent.c.
Referenced by NtReleaseKeyedEvent(), and NtWaitForKeyedEvent().
#define UNLOCK_KEYED_EVENT_EXCLUSIVE_UNSAFE (xxxKeyedEventObject)
Value:
{ \
    ExReleasePushLockExclusive (&(xxxKeyedEventObject)->Lock);     \
}
Definition at line 55 of file keyedevent.c.
Referenced by NtReleaseKeyedEvent(), and NtWaitForKeyedEvent().
Typedef Documentation
typedef struct _KEYED_EVENT_OBJECT KEYED_EVENT_OBJECT
typedef struct _KEYED_EVENT_OBJECT * PKEYED_EVENT_OBJECT
Function Documentation
NTSTATUS ExpKeyedEventInitialization (VOID)
Definition at line 60 of file keyedevent.c.
References ACL_REVISION, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, InitializeObjectAttributes, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KEYEDEVENT_ALL_ACCESS, KEYEDEVENT_WAIT, KEYEDEVENT_WAKE, _OBJECT_TYPE_INITIALIZER::Length, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_PERMANENT, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, READ_CONTROL, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlInitUnicodeString(), RtlLengthSid(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SeLocalSystemSid, SeWorldSid, STANDARD_RIGHTS_EXECUTE, STANDARD_RIGHTS_READ, STANDARD_RIGHTS_WRITE, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, ZwClose(), and ZwCreateKeyedEvent().
Referenced by ExpInitSystemPhase1().
NTSTATUS NtCreateKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Flags)
Definition at line 198 of file keyedevent.c.
References except, ExInitializePushLock(), ExSystemExceptionFilter(), Handle, InitializeListHead(), KeGetPreviousMode, KernelMode, _KEYED_EVENT_OBJECT::Lock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForReadSmallStructure, Status, STATUS_INVALID_PARAMETER_4, and _KEYED_EVENT_OBJECT::WaitQueue.
NTSTATUS NtOpenKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 309 of file keyedevent.c.
References except, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForReadSmallStructure, and Status.
NTSTATUS NtReleaseKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 383 of file keyedevent.c.
References ASSERT, CONTAINING_RECORD, except, Executive, ExSystemExceptionFilter(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), InsertHeadList(), IsListEmpty, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), KEYEDEVENT_WAKE, _ETHREAD::KeyedEventInUse, _ETHREAD::KeyedWaitChain, _ETHREAD::KeyedWaitSemaphore, _ETHREAD::KeyedWaitValue, KEYVALUE_RELEASE, LOCK_KEYED_EVENT_EXCLUSIVE, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PASSIVE_LEVEL, ProbeForRead, PsGetCurrentProcessByThread, PsGetCurrentThread(), RemoveEntryList(), SEMAPHORE_INCREMENT, Status, STATUS_INVALID_PARAMETER_1, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, UNLOCK_KEYED_EVENT_EXCLUSIVE, UNLOCK_KEYED_EVENT_EXCLUSIVE_UNSAFE, and _KEYED_EVENT_OBJECT::WaitQueue.
NTSTATUS NtWaitForKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 552 of file keyedevent.c.
References ASSERT, CONTAINING_RECORD, except, Executive, ExSystemExceptionFilter(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IsListEmpty, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), KEYEDEVENT_WAIT, _ETHREAD::KeyedEventInUse, _ETHREAD::KeyedWaitChain, _ETHREAD::KeyedWaitSemaphore, _ETHREAD::KeyedWaitValue, KEYVALUE_RELEASE, LOCK_KEYED_EVENT_EXCLUSIVE, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PASSIVE_LEVEL, ProbeForRead, PsGetCurrentProcessByThread, PsGetCurrentThread(), RemoveEntryList(), SEMAPHORE_INCREMENT, Status, STATUS_INVALID_PARAMETER_1, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, UNLOCK_KEYED_EVENT_EXCLUSIVE, UNLOCK_KEYED_EVENT_EXCLUSIVE_UNSAFE, and _KEYED_EVENT_OBJECT::WaitQueue.
Variable Documentation
POBJECT_TYPE ExpKeyedEventObjectType
Definition at line 36 of file keyedevent.c.