Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/callperf.c File Reference
callperf.c File Reference
#include "exp.h"
Functions
VOID ExInitializeCallData (IN PCALL_PERFORMANCE_DATA CallData)
VOID ExRecordCallerInHashTable (IN PCALL_PERFORMANCE_DATA CallData, IN PVOID CallersAddress, IN PVOID CallersCaller)
Function Documentation
VOID ExInitializeCallData (IN PCALL_PERFORMANCE_DATA CallData)
Definition at line 22 of file callperf.c.
References CALL_HASH_TABLE_SIZE, Index, InitializeListHead(), and KeInitializeSpinLock().
VOID ExRecordCallerInHashTable (IN PCALL_PERFORMANCE_DATA CallData, IN PVOID CallersAddress, IN PVOID CallersCaller)
Definition at line 59 of file callperf.c.
References CALL_HASH_TABLE_SIZE, _CALL_HASH_ENTRY::CallCount, _CALL_HASH_ENTRY::CallersAddress, _CALL_HASH_ENTRY::CallersCaller, CONTAINING_RECORD, ExAcquireSpinLock, ExAllocatePoolWithTag, ExReleaseSpinLock, _LIST_ENTRY::Flink, InitializationPhase, InsertTailList(), _CALL_HASH_ENTRY::ListEntry, NonPagedPool, and NULL.