Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/excptdbg.c File Reference
excptdbg.c File Reference
#include "ntrtlp.h"
Functions
VOID RtlInitializeExceptionLog (IN ULONG Entries)
ULONG RtlpLogExceptionHandler (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN ULONG_PTR ControlPc, IN PVOID HandlerData, IN ULONG Size)
VOID RtlpLogLastExceptionDisposition (ULONG LogIndex, EXCEPTION_DISPOSITION Disposition)
Variables
PLAST_EXCEPTION_LOG RtlpExceptionLog = NULL
ULONG RtlpExceptionLogCount
ULONG RtlpExceptionLogSize
Function Documentation
VOID RtlInitializeExceptionLog (IN ULONG Entries)
Definition at line 28 of file excptdbg.c.
References ExAllocatePoolWithTag, NonPagedPool, NULL, and RtlpExceptionLogSize.
Referenced by ExpInitializeExecutive().
ULONG RtlpLogExceptionHandler (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN ULONG_PTR ControlPc, IN PVOID HandlerData, IN ULONG Size)
Definition at line 62 of file excptdbg.c.
References ASSERT, _LAST_EXCEPTION_LOG::ContextRecord, _LAST_EXCEPTION_LOG::Disposition, _LAST_EXCEPTION_LOG::ExceptionRecord, InterlockedCompareExchange(), MAX_EXCEPTION_LOG, MAX_EXCEPTION_LOG_DATA_SIZE, RtlCopyMemory, and RtlpExceptionLogCount.
Referenced by RtlDispatchException().
VOID RtlpLogLastExceptionDisposition (ULONG LogIndex, EXCEPTION_DISPOSITION Disposition)
Definition at line 130 of file excptdbg.c.
References _LAST_EXCEPTION_LOG::Disposition, and NULL.
Referenced by RtlDispatchException().
Variable Documentation
PLAST_EXCEPTION_LOG RtlpExceptionLog = NULL
Definition at line 21 of file excptdbg.c.
ULONG RtlpExceptionLogCount
Definition at line 22 of file excptdbg.c.
Referenced by RtlpLogExceptionHandler().
ULONG RtlpExceptionLogSize
Definition at line 23 of file excptdbg.c.
Referenced by RtlInitializeExceptionLog().