Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmhvlist.c File Reference
cmhvlist.c File Reference
#include "cmp.h"
Macros
#define HIVE_LIST L"\\registry\\machine\\system\\currentcontrolset\\control\\hivelist"
#define NAME_BUFFER_SIZE 512
Functions
NTSTATUS CmpAddToHiveFileList (PCMHIVE CmHive)
BOOLEAN CmpGetHiveName (PCMHIVE CmHive, PUNICODE_STRING HiveName)
VOID CmpRemoveFromHiveFileList (PUNICODE_STRING EntryName)
Macro Definition Documentation
#define HIVE_LIST L"\\registry\\machine\\system\\currentcontrolset\\control\\hivelist"
Definition at line 22 of file cmhvlist.c.
Referenced by CmpAddToHiveFileList(), and CmpRemoveFromHiveFileList().
#define NAME_BUFFER_SIZE 512
Referenced by CmpAddToHiveFileList().
Function Documentation
NTSTATUS CmpAddToHiveFileList (PCMHIVE CmHive)
Definition at line 38 of file cmhvlist.c.
References _UNICODE_STRING::Buffer, CmKdPrintEx, CML_BUGCHECK, CmpGetHiveName(), DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), _CMHIVE::FileHandles, HFILE_TYPE_PRIMARY, _CMHIVE::Hive, HIVE_LIST, HIVE_VOLATILE, _HHIVE::HiveFlags, InitializeObjectAttributes, KEY_READ, KEY_WRITE, NAME_BUFFER_SIZE, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, ObjectNameInformation, PagedPool, REG_OPTION_VOLATILE, REG_SZ, RtlInitUnicodeString(), Status, STATUS_NO_MEMORY, UNICODE_NULL, UnicodeNull, ZwCreateKey(), ZwQueryObject(), and ZwSetValueKey().
Referenced by CmInitSystem1(), CmLoadKey(), CmpInitializeHiveList(), and CmpLoadHiveVolatile().
BOOLEAN CmpGetHiveName (PCMHIVE CmHive, PUNICODE_STRING HiveName)
Definition at line 233 of file cmhvlist.c.
References ASSERT, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, CmpCopyCompressedName(), CmpHKeyNameLen, CmpMasterHive, ExAllocatePool, FALSE, _CM_KEY_NODE::Flags, _CMHIVE::Hive, HvGetCell, HvReleaseCell, KEY_COMP_NAME, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, _CM_KEY_NODE::Parent, _HBASE_BLOCK::RootCell, RtlCopyMemory, TRUE, and wcslen().
Referenced by CmpAddToHiveFileList(), and CmUnloadKey().
VOID CmpRemoveFromHiveFileList (PUNICODE_STRING EntryName)
Definition at line 174 of file cmhvlist.c.
References HIVE_LIST, InitializeObjectAttributes, KEY_READ, KEY_WRITE, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, RtlInitUnicodeString(), Status, ZwDeleteValueKey(), and ZwOpenKey().
Referenced by CmUnloadKey().