Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/cnvint.c File Reference
cnvint.c File Reference
#include <ntrtlp.h>
Macros
#define MAX_DIGITS 65
Functions
NTSTATUS RtlCharToInteger (IN PCSZ String, IN ULONG Base OPTIONAL, OUT PULONG Value)
NTSTATUS RtlInt64ToUnicodeString (IN ULONGLONG Value, IN ULONG Base OPTIONAL, IN OUT PUNICODE_STRING String)
NTSTATUS RtlIntegerToChar (IN ULONG Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PSZ String)
NTSTATUS RtlIntegerToUnicode (IN ULONG Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
NTSTATUS RtlIntegerToUnicodeString (IN ULONG Value, IN ULONG Base OPTIONAL, IN OUT PUNICODE_STRING String)
NTSTATUS RtlLargeIntegerToChar (IN PLARGE_INTEGER Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PSZ String)
NTSTATUS RtlLargeIntegerToUnicode (IN PLARGE_INTEGER Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
NTSTATUS RtlUnicodeStringToInteger (IN PCUNICODE_STRING String, IN ULONG Base OPTIONAL, OUT PULONG Value)
Variables
const CHAR RtlpIntegerChars []
const WCHAR RtlpIntegerWChars []
Macro Definition Documentation
#define MAX_DIGITS 65
Definition at line 447 of file cnvint.c.
Referenced by RtlLargeIntegerToChar(), and RtlLargeIntegerToUnicode().
Function Documentation
NTSTATUS RtlCharToInteger (IN PCSZ String, IN ULONG Base OPTIONAL, OUT PULONG Value)
Definition at line 122 of file cnvint.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, RTL_PAGED_CODE, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlInt64ToUnicodeString (IN ULONGLONG Value, IN ULONG Base OPTIONAL, IN OUT PUNICODE_STRING String)
Definition at line 621 of file cnvint.c.
References _STRING::Buffer, FALSE, _STRING::Length, _STRING::MaximumLength, NT_SUCCESS, _LARGE_INTEGER::QuadPart, RTL_PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlLargeIntegerToChar(), Status, and strlen().
NTSTATUS RtlIntegerToChar (IN ULONG Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PSZ String)
Definition at line 43 of file cnvint.c.
References except, EXCEPTION_EXECUTE_HANDLER, RTL_PAGED_CODE, RtlCopyMemory, RtlpIntegerChars, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlIntegerToUnicodeString().
NTSTATUS RtlIntegerToUnicode (IN ULONG Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
Definition at line 344 of file cnvint.c.
References except, EXCEPTION_EXECUTE_HANDLER, RTL_PAGED_CODE, RtlCopyMemory, RtlpIntegerWChars, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlConvertSidToUnicodeString().
NTSTATUS RtlIntegerToUnicodeString (IN ULONG Value, IN ULONG Base OPTIONAL, IN OUT PUNICODE_STRING String)
Definition at line 423 of file cnvint.c.
References _STRING::Buffer, FALSE, _STRING::Length, _STRING::MaximumLength, NT_SUCCESS, RTL_PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlIntegerToChar(), Status, and strlen().
NTSTATUS RtlLargeIntegerToChar (IN PLARGE_INTEGER Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PSZ String)
Definition at line 450 of file cnvint.c.
References MAX_DIGITS, RTL_PAGED_CODE, RtlpIntegerChars, and STATUS_INVALID_PARAMETER.
Referenced by RtlInt64ToUnicodeString().
NTSTATUS RtlLargeIntegerToUnicode (IN PLARGE_INTEGER Value, IN ULONG Base OPTIONAL, IN LONG OutputLength, OUT PWSTR String)
Definition at line 535 of file cnvint.c.
References MAX_DIGITS, RTL_PAGED_CODE, RtlpIntegerWChars, and STATUS_INVALID_PARAMETER.
Referenced by RtlConvertSidToUnicodeString().
NTSTATUS RtlUnicodeStringToInteger (IN PCUNICODE_STRING String, IN ULONG Base OPTIONAL, OUT PULONG Value)
Definition at line 215 of file cnvint.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, RTL_PAGED_CODE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and UNICODE_NULL.
Variable Documentation
const CHAR RtlpIntegerChars[]
Initial value:
= {'0', '1', '2', '3', '4', '5', '6', '7',
                           '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'}
Definition at line 35 of file cnvint.c.
Referenced by RtlIntegerToChar(), and RtlLargeIntegerToChar().
const WCHAR RtlpIntegerWChars[]
Initial value:
= { L'0', L'1', L'2', L'3', L'4', L'5',
                              L'6', L'7', L'8', L'9', L'A', L'B',
                              L'C', L'D', L'E', L'F' }
Definition at line 38 of file cnvint.c.
Referenced by RtlIntegerToUnicode(), and RtlLargeIntegerToUnicode().