Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/pnp.c File Reference
pnp.c File Reference
#include "FsRtlP.h"
#include <IoEvent.h>
Macros
#define FAR
Functions
NTKERNELAPI NTSTATUS FsRtlNotifyVolumeEvent (__in PFILE_OBJECT FileObject, __in ULONG EventCode)
Macro Definition Documentation
#define FAR
Definition at line 28 of file pnp.c.
Function Documentation
NTKERNELAPI NTSTATUS FsRtlNotifyVolumeEvent (__in PFILE_OBJECT FileObject, __in ULONG EventCode)
Definition at line 39 of file pnp.c.
References ASSERT, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Event, FIELD_OFFSET, _TARGET_DEVICE_CUSTOM_NOTIFICATION::FileObject, FSRTL_VOLUME_DISMOUNT, FSRTL_VOLUME_DISMOUNT_FAILED, FSRTL_VOLUME_LOCK, FSRTL_VOLUME_LOCK_FAILED, FSRTL_VOLUME_MOUNT, FSRTL_VOLUME_UNLOCK, IoGetRelatedTargetDevice(), IoReportTargetDeviceChange(), IoReportTargetDeviceChangeAsynchronous(), _TARGET_DEVICE_CUSTOM_NOTIFICATION::NameBufferOffset, NT_SUCCESS, NULL, ObDereferenceObject(), RtlCopyMemory, _TARGET_DEVICE_CUSTOM_NOTIFICATION::Size, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and _TARGET_DEVICE_CUSTOM_NOTIFICATION::Version.
Referenced by RawMountVolume(), and RawUserFsCtrl().