Windows Research Kernel v1.2: C:/Windows Research Kernel/dbgk/dbgkport.c File Reference
dbgkport.c File Reference
#include "dbgkp.h"
Functions
DECLSPEC_NOINLINE BOOLEAN DbgkForwardException (IN PEXCEPTION_RECORD ExceptionRecord, IN BOOLEAN DebugException, IN BOOLEAN SecondChance)
NTSTATUS DbgkpSendApiMessage (IN OUT PDBGKM_APIMSG ApiMsg, IN BOOLEAN SuspendProcess)
NTSTATUS DbgkpSendApiMessageLpc (IN OUT PDBGKM_APIMSG ApiMsg, IN PVOID Port, IN BOOLEAN SuspendProcess)
Function Documentation
DECLSPEC_NOINLINE BOOLEAN DbgkForwardException (IN PEXCEPTION_RECORD ExceptionRecord, IN BOOLEAN DebugException, IN BOOLEAN SecondChance)
Definition at line 155 of file dbgkport.c.
References DBG_EXCEPTION_NOT_HANDLED, DBGKM_FORMAT_API_MSG, DbgKmExceptionApi, DbgkpSendApiMessage(), DbgkpSendApiMessageLpc(), _EPROCESS::DebugPort, _DBGKM_APIMSG::Exception, _EPROCESS::ExceptionPort, _DBGKM_EXCEPTION::ExceptionRecord, FALSE, _DBGKM_EXCEPTION::FirstChance, _DBGKM_APIMSG::h, LPC_EXCEPTION, NT_SUCCESS, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), _DBGKM_APIMSG::ReturnedStatus, TRUE, _DBGKM_APIMSG::u, _PORT_MESSAGE::u2, and _PORT_MESSAGE::ZeroInit.
Referenced by KiDispatchException().
NTSTATUS DbgkpSendApiMessage (IN OUT PDBGKM_APIMSG ApiMsg, IN BOOLEAN SuspendProcess)
Definition at line 30 of file dbgkport.c.
References DbgkpQueueMessage(), DbgkpResumeProcess(), DbgkpSuspendProcess(), _EPROCESS::Flags, NtCurrentProcess, NULL, PAGED_CODE, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_SET_BITS, PsGetCurrentProcess(), PsGetCurrentThread(), STATUS_PENDING, and ZwFlushInstructionCache().
Referenced by DbgkCreateThread(), DbgkExitProcess(), DbgkExitThread(), DbgkForwardException(), DbgkMapViewOfSection(), and DbgkUnMapViewOfSection().
NTSTATUS DbgkpSendApiMessageLpc (IN OUT PDBGKM_APIMSG ApiMsg, IN PVOID Port, IN BOOLEAN SuspendProcess)
Definition at line 88 of file dbgkport.c.
References DbgkpResumeProcess(), DbgkpSuspendProcess(), LpcRequestWaitReplyPortEx(), NT_SUCCESS, NtCurrentProcess, NULL, PAGED_CODE, PORT_TOTAL_MAXIMUM_MESSAGE_LENGTH, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_SET_BITS, PsGetCurrentProcess(), RtlCopyMemory, STATUS_PENDING, and ZwFlushInstructionCache().
Referenced by DbgkForwardException().