Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/creasect.c File Reference
creasect.c File Reference
#include "mi.h"
Data Structures
struct _PHARLAP_CONFIG
Macros
#define INIT_IMAGE_INFORMATION(OptHdr)
#define InvalidAlignmentAllowed FALSE
#define MI_BAD_IMAGE(x) MiImageFailure = x;
#define MM_MAXIMUM_IMAGE_HEADER (2 * PAGE_SIZE)
#define MM_MAXIMUM_IMAGE_SECTIONS
#define MM_SIZE_OF_LARGEST_IMAGE ((ULONG)0x77000000)
#define VALIDATE_NTHEADER(Hdr)
Typedefs
typedef struct _PHARLAP_CONFIG CONFIGPHARLAP
typedef struct _PHARLAP_CONFIG * PCONFIGPHARLAP
Functions
LOGICAL MiCheckDosCalls (IN PIMAGE_OS2_HEADER Os2Header, IN ULONG HeaderSize)
PVOID MiCopyHeaderIfResident (IN PFILE_OBJECT File, IN PFN_NUMBER ImagePageFrameNumber)
NTSTATUS MiCreateDataFileMap (IN PFILE_OBJECT File, OUT PSEGMENT *Segment, IN PUINT64 MaximumSize, IN ULONG SectionPageProtection, IN ULONG AllocationAttributes, IN ULONG IgnoreFileSizing)
NTSTATUS MiCreateImageFileMap (IN PFILE_OBJECT File, OUT PSEGMENT *Segment)
NTSTATUS MiCreatePagingFileMap (OUT PSEGMENT *Segment, IN PUINT64 MaximumSize, IN MM_PROTECTION_MASK ProtectionMask, IN ULONG AllocationAttributes)
PCONTROL_AREA MiFindImageSectionObject (IN PFILE_OBJECT File, IN LOGICAL PfnLockHeld, OUT PLOGICAL GlobalNeeded)
LOGICAL MiFlushDataSection (IN PFILE_OBJECT File)
CCHAR MiGetImageProtection (IN ULONG SectionCharacteristics)
PFN_NUMBER MiGetPageForHeader (LOGICAL ZeroPage)
VOID MiInsertImageSectionObject (IN PFILE_OBJECT File, IN PCONTROL_AREA ControlArea)
LOGICAL MiMakeControlAreaRom (IN PFILE_OBJECT File, IN PLARGE_CONTROL_AREA ControlArea, IN PFN_NUMBER PageFrameNumber)
VOID MiRemoveImageHeaderPage (IN PFN_NUMBER PageFrameNumber)
VOID MiRemoveImageSectionObject (IN PFILE_OBJECT File, IN PCONTROL_AREA InputControlArea)
VOID MiUpdateImageHeaderPage (IN PMMPTE PointerPte, IN PFN_NUMBER PageFrameNumber, IN PCONTROL_AREA ControlArea, IN LOGICAL MarkModified)
VOID MiUpdateLargeProtoPfns (IN PMMPTE PointerPte, IN PMMPTE LastPte, IN PMMPFN Pfn1, IN MMPTE OriginalPte)
NTSTATUS MiVerifyImageHeader (IN PIMAGE_NT_HEADERS NtHeader, IN PIMAGE_DOS_HEADER DosHeader, IN ULONG NtHeaderSize)
NTSTATUS MmCreateSection (__deref_out PVOID *SectionObject, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in PLARGE_INTEGER InputMaximumSize, __in WIN32_PROTECTION_MASK SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle, __in_opt PFILE_OBJECT FileObject)
NTSTATUS NtCreateSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PLARGE_INTEGER MaximumSize, __in ULONG SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle)
NTSTATUS NtOpenSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Variables
POBJECT_TYPE IoFileObjectType
ULONG MiImageFailure
SIZE_T MmAllocationFragment
const ULONG MMCONTROL = 'aCmM'
CCHAR MmImageProtectionArray [16]
const ULONG MMTEMPORARY = 'xxmM'
Macro Definition Documentation
#define INIT_IMAGE_INFORMATION (OptHdr)
Value:
{                            \
    NewSegment->u2.ImageInformation->TransferAddress =              \
                    (PVOID)((ULONG_PTR)((OptHdr).ImageBase) +       \
                            (OptHdr).AddressOfEntryPoint);          \
    NewSegment->u2.ImageInformation->MaximumStackSize =             \
                            (OptHdr).SizeOfStackReserve;            \
    NewSegment->u2.ImageInformation->CommittedStackSize =           \
                            (OptHdr).SizeOfStackCommit;             \
    NewSegment->u2.ImageInformation->SubSystemType =                \
                            (OptHdr).Subsystem;                     \
    NewSegment->u2.ImageInformation->SubSystemMajorVersion = (USHORT)((OptHdr).MajorSubsystemVersion); \
    NewSegment->u2.ImageInformation->SubSystemMinorVersion = (USHORT)((OptHdr).MinorSubsystemVersion); \
    NewSegment->u2.ImageInformation->DllCharacteristics =           \
                            (OptHdr).DllCharacteristics;            \
    NewSegment->u2.ImageInformation->ImageContainsCode =            \
                            (BOOLEAN)(((OptHdr).SizeOfCode != 0) || \
                                      ((OptHdr).AddressOfEntryPoint != 0)); \
    }
Referenced by MiCreateImageFileMap().
#define InvalidAlignmentAllowed FALSE
Referenced by MiCreateImageFileMap().
#define MI_BAD_IMAGE (x) MiImageFailure = x;
Definition at line 1674 of file creasect.c.
Referenced by MiCreateImageFileMap().
#define MM_MAXIMUM_IMAGE_HEADER (2 * PAGE_SIZE)
Definition at line 27 of file creasect.c.
Referenced by MiCreateImageFileMap().
#define MM_MAXIMUM_IMAGE_SECTIONS
Value:
((MM_MAXIMUM_IMAGE_HEADER - (PAGE_SIZE + sizeof(IMAGE_NT_HEADERS))) /  \
            sizeof(IMAGE_SECTION_HEADER))
Definition at line 37 of file creasect.c.
#define MM_SIZE_OF_LARGEST_IMAGE ((ULONG)0x77000000)
Definition at line 25 of file creasect.c.
#define VALIDATE_NTHEADER (Hdr)
Referenced by MiVerifyImageHeader().
Typedef Documentation
typedef struct _PHARLAP_CONFIG CONFIGPHARLAP
typedef struct _PHARLAP_CONFIG * PCONFIGPHARLAP
Function Documentation
LOGICAL MiCheckDosCalls (IN PIMAGE_OS2_HEADER Os2Header, IN ULONG HeaderSize)
Definition at line 3775 of file creasect.c.
References FALSE, PAGED_CODE, RtlEqualMemory, TRUE, and UNALIGNED.
Referenced by MiVerifyImageHeader().
PVOID MiCopyHeaderIfResident (IN PFILE_OBJECT File, IN PFN_NUMBER ImagePageFrameNumber)
Definition at line 5718 of file creasect.c.
References ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _SECTION_OBJECT_POINTERS::DataSectionObject, _MMPFN::e1, _CONTROL_AREA::Flags, _MMPTE::Hard, KeSweepIcacheRange, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_WRITE_VALID_PTE, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpaceAtDpc(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiUnmapPageInHyperSpaceFromDpc, NULL, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, PsGetCurrentProcess(), _MMPFNENTRY::ReadInProgress, _MMSECTION_FLAGS::Rom, RtlCopyMemory, _MMPTE::Soft, _SUBSECTION::SubsectionBase, SystemPteSpace, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and ValidKernelPte.
Referenced by MiCreateImageFileMap().
NTSTATUS MiCreateDataFileMap (IN PFILE_OBJECT File, OUT PSEGMENT * Segment, IN PUINT64 MaximumSize, IN ULONG SectionPageProtection, IN ULONG AllocationAttributes, IN ULONG IgnoreFileSizing)
Definition at line 4199 of file creasect.c.
References _4gb, ASSERT, ASSERT64, ExAllocatePoolWithTag, ExFreePool(), FileOffset, FsRtlGetFileSize(), FsRtlSetFileSize(), MI_MAXIMUM_SECTION_SIZE, MiGetByteOffset, MmAllocationFragment, _MSUBSECTION::NextSubsection, NonPagedPool, NT_SUCCESS, NULL, PAGE_EXECUTE_READWRITE, PAGE_READWRITE, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PagedPool, _MSUBSECTION::PtesInSubsection, ROUND_TO_PAGES, RtlZeroMemory, Status, STATUS_FILE_IS_A_DIRECTORY, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_FILE_FOR_SECTION, STATUS_MAPPED_FILE_SIZE_ZERO, and STATUS_SECTION_TOO_BIG.
Referenced by MmCreateSection().
NTSTATUS MiCreateImageFileMap (IN PFILE_OBJECT File, OUT PSEGMENT * Segment)
Definition at line 1678 of file creasect.c.
References _4gb, ASSERT, _SEGMENT::BasedAddress, _MMSECTION_FLAGS::BeingCreated, _MMPFN::Blink, BYTE_OFFSET, BYTES_TO_PAGES, CcZeroEndOfLastPage(), _IMAGE_FILE_HEADER::Characteristics, _IMAGE_SECTION_HEADER::Characteristics, _SEGMENT::ControlArea, _SUBSECTION::ControlArea, _IMAGE_OPTIONAL_HEADER::DataDirectory, DbgBreakPoint(), DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _IMAGE_DOS_HEADER::e_lfanew, _IMAGE_DOS_HEADER::e_magic, ExAllocatePoolWithTag, ExFreePool(), _SEGMENT_FLAGS::ExtraSharedWowSubsections, FALSE, _MMSECTION_FLAGS::File, FILE_REMOTE_DEVICE, FILE_REMOVABLE_MEDIA, _IMAGE_OPTIONAL_HEADER::FileAlignment, _IMAGE_NT_HEADERS::FileHeader, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LARGE_CONTROL_AREA::Flags, _MMPFN::Flink, _MMSECTION_FLAGS::FloppyMedia, FsRtlGetFileSize(), _MMSECTION_FLAGS::GlobalMemory, _MMSUBSECTION_FLAGS::GlobalMemory, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _LARGE_INTEGER::HighPart, _MMSECTION_FLAGS::Image, IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR, IMAGE_DOS_SIGNATURE, IMAGE_FILE_NET_RUN_FROM_SWAP, IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP, IMAGE_LOADER_FLAGS_COMPLUS, IMAGE_LOADER_FLAGS_SYSTEM_GLOBAL, IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_SHARED, IMAGE_SCN_MEM_WRITE, _IMAGE_OPTIONAL_HEADER::ImageBase, _SECTION_IMAGE_INFORMATION::ImageCharacteristics, _SEGMENT::ImageCommitment, _SECTION_IMAGE_INFORMATION::ImageFileSize, _SEGMENT::ImageInformation, _IO_STATUS_BLOCK::Information, INIT_IMAGE_INFORMATION, InitializeListHead(), InterlockedExchangeAddSizeT, InvalidAlignmentAllowed, IoIsDeviceEjectable(), IoPageRead(), KdPrint, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _SECTION_IMAGE_INFORMATION::LoaderFlags, _IMAGE_OPTIONAL_HEADER::LoaderFlags, _MMPTE::Long, _SUBSECTION::LongFlags, _LARGE_INTEGER::LowPart, _IMAGE_FILE_HEADER::Machine, _SECTION_IMAGE_INFORMATION::Machine, _IMAGE_OPTIONAL_HEADER::Magic, _MDL::MappedSystemVa, MAXULONG_PTR, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_BAD_IMAGE, MI_COMPUTE_PAGES_SPANNED, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_HYPER_ADDRESS, MI_PFN_ELEMENT, MI_ROUND_TO_SIZE, MI_ROUND_WOULD_WRAP, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiChargeCommitment(), MiCopyHeaderIfResident(), MiFlushDataSection(), MiGetImageProtection(), MiGetPageForHeader(), MiGetPteAddress, MiGetSubsectionAddress, MiGetSubsectionAddressForPte, MiGetVirtualAddressMappedByPte, MiReleaseSystemPtes(), MiRemoveImageHeaderPage(), MiReserveSystemPtes(), MiReturnCommitment, _IMAGE_SECTION_HEADER::Misc, MiUpdateImageHeaderPage(), MiVerifyImageHeader(), MiZeroMemoryPte, MM_COPY_ON_WRITE_MASK, MM_DBG_COMMIT_IMAGE, MM_DBG_COMMIT_RETURN_IMAGE_NO_LARGE_CA, MM_EXECUTE_WRITECOPY, MM_MAXIMUM_IMAGE_HEADER, MM_PROTECTION_WRITE_MASK, MM_READONLY, MM_TRACK_COMMIT, MmBuildMdlForNonPagedPool(), MMCONTROL, MmInitializeMdl, MmPfnDatabase, MMSECT, MMSECTOR_MASK, MMSECTOR_SHIFT, MmSharedCommit, MMTEMPORARY, MmUnmapLockedPages(), _MMSECTION_FLAGS::Networked, _SUBSECTION::NextSubsection, _SEGMENT::NonExtendedPtes, NonPagedPool, NOTHING, NotificationEvent, NT_SUCCESS, NULL, _SEGMENT::NumberOfCommittedPages, _SUBSECTION::NumberOfFullSectors, _CONTROL_AREA::NumberOfPfnReferences, _CONTROL_AREA::NumberOfSectionReferences, _IMAGE_FILE_HEADER::NumberOfSections, _CONTROL_AREA::NumberOfUserReferences, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PagedPool, _MMPTE_HARDWARE::PageFrameNumber, _IMAGE_SECTION_HEADER::PointerToRawData, POOL_MM_ALLOCATION, _MMPTE_SOFTWARE::Protection, _MMSUBSECTION_FLAGS::Protection, _MMPTE_SOFTWARE::Prototype, PrototypePte, _SEGMENT::PrototypePte, _SUBSECTION::PtesInSubsection, PtrToUlong, _LARGE_INTEGER::QuadPart, _MMSUBSECTION_FLAGS::ReadOnly, RtlCopyMemory, RtlZeroMemory, _IMAGE_OPTIONAL_HEADER::SectionAlignment, _MMSUBSECTION_FLAGS::SectorEndOffset, _CONTROL_AREA::Segment, _SEGMENT::SegmentFlags, _SEGMENT::SegmentPteTemplate, _LARGE_CONTROL_AREA::SessionId, _IMAGE_DATA_DIRECTORY::Size, _IMAGE_OPTIONAL_HEADER::SizeOfHeaders, _IMAGE_OPTIONAL_HEADER::SizeOfImage, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, _SEGMENT::SizeOfSegment, _MMPTE::Soft, _SUBSECTION::StartingSector, Status, _IO_STATUS_BLOCK::Status, STATUS_COMMITMENT_LIMIT, STATUS_FILE_IS_A_DIRECTORY, STATUS_FILE_IS_OFFLINE, STATUS_FILE_LOCK_CONFLICT, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_FILE_FOR_SECTION, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_IMAGE_NOT_MZ, STATUS_INVALID_IMAGE_PROTECT, STATUS_PENDING, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, SystemPteSpace, _SEGMENT::ThePtes, _SEGMENT::TotalNumberOfPtes, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _LARGE_CONTROL_AREA::u, _SUBSECTION::u, _MMPFN::u1, _SEGMENT::u1, _MMPFN::u2, _SEGMENT::u2, _SUBSECTION::UnusedPtes, _LARGE_CONTROL_AREA::UserGlobalList, _MMPTE_HARDWARE::Valid, ValidKernelPte, _IMAGE_DATA_DIRECTORY::VirtualAddress, _IMAGE_SECTION_HEADER::VirtualAddress, _IMAGE_SECTION_HEADER::VirtualSize, WrPageIn, X64K, and ZERO_LARGE.
Referenced by MmCreateSection().
NTSTATUS MiCreatePagingFileMap (OUT PSEGMENT * Segment, IN PUINT64 MaximumSize, IN MM_PROTECTION_MASK ProtectionMask, IN ULONG AllocationAttributes)
Definition at line 4671 of file creasect.c.
References ASSERT, _MMSECTION_FLAGS::Based, _MI_LARGEPAGE_MEMORY_RUN::BasePage, _MMSECTION_FLAGS::Commit, _SEGMENT::ControlArea, _SUBSECTION::ControlArea, _SEGMENT::CreatingProcess, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CONTROL_AREA::Flags, _MMPTE::Hard, InterlockedExchangeAddSizeT, KeFeatureBits, KF_LARGE_PAGE, _SEGMENT_FLAGS::LargePages, _MMPTE::Long, MAXULONG_PTR, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MiAllocateLargeZeroPages(), MiChargeCommitment(), MiFillMemoryPte, MiReturnCommitment, MiReturnLargePages(), MiUpdateLargeProtoPfns(), MM_DBG_COMMIT_PAGEFILE_BACKED_SHMEM, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_PROTECTION_WRITE_MASK, MM_TRACK_COMMIT, MMCONTROL, MMSECT, MmSharedCommit, _MI_LARGEPAGE_MEMORY_RUN::Next, _SEGMENT::NonExtendedPtes, NonPagedPool, NULL, _SEGMENT::NumberOfCommittedPages, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfUserReferences, PAGE_SHIFT, PAGE_SIZE, _MI_LARGEPAGE_MEMORY_RUN::PageCount, PAGED_CODE, PagedPool, _MMPTE_HARDWARE::PageFrameNumber, POOL_MM_ALLOCATION, _MMPTE_SOFTWARE::Protection, _MMSUBSECTION_FLAGS::Protection, _SEGMENT::PrototypePte, PsGetCurrentProcess(), _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Reserve, RtlZeroMemory, SEC_BASED, SEC_COMMIT, SEC_LARGE_PAGES, SEC_RESERVE, _CONTROL_AREA::Segment, _SEGMENT::SegmentFlags, _SEGMENT::SegmentPteTemplate, _SEGMENT::SizeOfSegment, _MMPTE::Soft, STATUS_COMMITMENT_LIMIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_4, STATUS_NOT_SUPPORTED, STATUS_SECTION_TOO_BIG, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, _SEGMENT::ThePtes, _SEGMENT::TotalNumberOfPtes, _MMPTE::u, _CONTROL_AREA::u, _SUBSECTION::u, and _SEGMENT::u1.
Referenced by MmCreateSection().
PCONTROL_AREA MiFindImageSectionObject (IN PFILE_OBJECT File, IN LOGICAL PfnLockHeld, OUT PLOGICAL GlobalNeeded)
Definition at line 5301 of file creasect.c.
References ASSERT, CONTAINING_RECORD, FALSE, _CONTROL_AREA::Flags, _LARGE_CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, LOCK_PFN, MM_PFN_LOCK_ASSERT, MmGetSessionId(), NULL, PASSIVE_LEVEL, PsGetCurrentProcess(), SATISFY_OVERZEALOUS_COMPILER, _LARGE_CONTROL_AREA::SessionId, TRUE, _CONTROL_AREA::u, _LARGE_CONTROL_AREA::u, UNLOCK_PFN, and _LARGE_CONTROL_AREA::UserGlobalList.
Referenced by MmCreateSection(), and NtAreMappedFilesTheSame().
LOGICAL MiFlushDataSection (IN PFILE_OBJECT File)
Definition at line 5648 of file creasect.c.
References CcFlushCache(), FALSE, LOCK_PFN, MmFlushSection(), NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfSystemCacheViews, TRUE, and UNLOCK_PFN.
Referenced by MiCreateImageFileMap(), and MmCreateSection().
CCHAR MiGetImageProtection (IN ULONG SectionCharacteristics)
Definition at line 5062 of file creasect.c.
References IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_READ, IMAGE_SCN_MEM_SHARED, IMAGE_SCN_MEM_WRITE, Index, MmImageProtectionArray, and PAGED_CODE.
Referenced by MiCreateImageFileMap().
PFN_NUMBER MiGetPageForHeader (LOGICAL ZeroPage)
Definition at line 5107 of file creasect.c.
References ASSERT, _MMPFN::Blink, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFN::Flink, LOCK_PFN, _MMPTE::Long, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_PAGE_COLOR_VA_PROCESS, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiCached, MiEnsureAvailablePageOrWait(), MiRemoveAnyPage(), MiRemoveZeroPage(), MM_HIGH_LIMIT, MmAvailablePages, _EPROCESS::NextPageColor, NULL, _MMPFN::OriginalPte, PsGetCurrentProcess(), _MMPFN::PteAddress, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, and X64K.
Referenced by MiCreateImageFileMap(), and MiZeroPageFileFirstPage().
VOID MiInsertImageSectionObject (IN PFILE_OBJECT File, IN PCONTROL_AREA ControlArea)
Definition at line 5418 of file creasect.c.
References ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, CONTAINING_RECORD, _LARGE_CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, InitializeListHead(), InsertTailList(), MM_PFN_LOCK_ASSERT, MmGetSessionId(), NULL, PsGetCurrentProcess(), _LARGE_CONTROL_AREA::SessionId, _LARGE_CONTROL_AREA::u, and _LARGE_CONTROL_AREA::UserGlobalList.
Referenced by MmCreateSection().
LOGICAL MiMakeControlAreaRom (IN PFILE_OBJECT File, IN PLARGE_CONTROL_AREA ControlArea, IN PFN_NUMBER PageFrameNumber)
Definition at line 1614 of file creasect.c.
References FALSE, _CONTROL_AREA::Flags, LOCK_PFN, NULL, _MMSECTION_FLAGS::Rom, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
VOID MiRemoveImageHeaderPage (IN PFN_NUMBER PageFrameNumber)
Definition at line 5267 of file creasect.c.
References LOCK_PFN, MI_PFN_ELEMENT, MiDecrementReferenceCount(), and UNLOCK_PFN.
Referenced by MiCreateImageFileMap(), and MiZeroPageFileFirstPage().
VOID MiRemoveImageSectionObject (IN PFILE_OBJECT File, IN PCONTROL_AREA InputControlArea)
Definition at line 5531 of file creasect.c.
References ASSERT, CONTAINING_RECORD, _LARGE_CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, IsListEmpty, MM_PFN_LOCK_ASSERT, NULL, RemoveEntryList(), _LARGE_CONTROL_AREA::u, and _LARGE_CONTROL_AREA::UserGlobalList.
Referenced by MiCheckControlArea(), MiCheckForControlAreaDeletion(), MiCleanSection(), and MmCreateSection().
VOID MiUpdateImageHeaderPage (IN PMMPTE PointerPte, IN PFN_NUMBER PageFrameNumber, IN PCONTROL_AREA ControlArea, IN LOGICAL MarkModified)
Definition at line 5198 of file creasect.c.
References _MMPTE::Hard, LOCK_PFN, MI_PFN_ELEMENT, MI_SET_MODIFIED, MiDecrementReferenceCount(), MiGetPteAddress, MiInitializeTransitionPfn(), MiMakeSystemAddressValidPfn(), _MMPFN::OriginalPte, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, TRUE, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiCreateImageFileMap().
VOID MiUpdateLargeProtoPfns (IN PMMPTE PointerPte, IN PMMPTE LastPte, IN PMMPFN Pfn1, IN MMPTE OriginalPte)
Definition at line 4593 of file creasect.c.
References ASSERT, _MMPTE::Hard, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MiCheckPdeForPagedPool(), MiGetPteAddress, MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u2, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiCreatePagingFileMap().
NTSTATUS MiVerifyImageHeader (IN PIMAGE_NT_HEADERS NtHeader, IN PIMAGE_DOS_HEADER DosHeader, IN ULONG NtHeaderSize)
Definition at line 3909 of file creasect.c.
References IMAGE_FILE_EXECUTABLE_IMAGE, IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_NT_OPTIONAL_HDR64_MAGIC, IMAGE_NT_OPTIONAL_HDR_MAGIC, IMAGE_NT_SIGNATURE, IMAGE_OS2_SIGNATURE, IMAGE_OS2_SIGNATURE_LE, MiCheckDosCalls(), PAGE_SIZE, PAGED_CODE, RtlEqualMemory, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_IMAGE_NE_FORMAT, STATUS_INVALID_IMAGE_PROTECT, STATUS_INVALID_IMAGE_WIN_16, STATUS_INVALID_IMAGE_WIN_64, STATUS_SUCCESS, _PHARLAP_CONFIG::uchCopyRight, _PHARLAP_CONFIG::usSign, and VALIDATE_NTHEADER.
Referenced by MiCreateImageFileMap().
NTSTATUS MmCreateSection (__deref_out PVOID * SectionObject, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in PLARGE_INTEGER InputMaximumSize, __in WIN32_PROTECTION_MASK SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle, __in_opt PFILE_OBJECT FileObject)
Definition at line 403 of file creasect.c.
References _MMSECTION_FLAGS::Accessed, _SECTION::Address, ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::Based, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _LIST_ENTRY::Blink, CcWaitForUninitializeCacheMap(), _SEGMENT::ControlArea, _MMSECTION_FLAGS::CopyOnWrite, _SECTION_OBJECT_POINTERS::DataSectionObject, _CONTROL_AREA::DereferenceList, _MMADDRESS_NODE::EndingVpn, _EVENT_COUNTER::Event, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CONTROL_AREA::FilePointer, _MMSECTION_FLAGS::FilePointerNull, _CONTROL_AREA::Flags, _SECTION::Flags, _LIST_ENTRY::Flink, FSRTL_FSP_TOP_LEVEL_IRP, FsRtlAcquireToCreateMappedSection(), FsRtlGetFileSize(), FsRtlReleaseFile(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, _MMSECTION_FLAGS::ImageMappedInSystemSpace, _SECTION::InitialPageProtection, InterlockedDecrement, InterlockedIncrement, IoSetTopLevelIrp(), KeAcquireGuardedMutex(), KeGetPreviousMode, KeReleaseGuardedMutex(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LOCK_PFN, _CONTROL_AREA::LongFlags, _SECTION::LongFlags, _LARGE_INTEGER::LowPart, MI_UNUSED_SEGMENTS_REMOVE_CHARGE, MiCheckControlArea(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreatePagingFileMap(), MiFindEmptyAddressRangeDownBasedTree(), MiFindImageSectionObject(), MiFlushDataSection(), MiFreeEventCounter(), MiGetEventCounter(), MiInsertBasedSection(), MiInsertImageSectionObject(), MiMakeProtectionMask(), MiRemoveImageSectionObject(), MM_INVALID_PROTECTION, MMCONTROL, MmExtendSection(), MmHighSectionBase, MmMakeFileAccess, MmSectionBasedMutex, MmSectionBasedRoot, MmSectionObjectType, _CONTROL_AREA::ModifiedWriteCount, _SUBSECTION::NextSubsection, _MMSECTION_FLAGS::NoChange, NonPagedPool, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfUserReferences, ObCreateObject, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), ObReferenceObject, ObReferenceObjectByHandle, PAGE_EXECUTE_READWRITE, PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_READWRITE, PAGE_WRITECOMBINE, PIRP, _LARGE_INTEGER::QuadPart, _EVENT_COUNTER::RefCount, RemoveEntryList(), _MMSECTION_FLAGS::Rom, RtlCopyMemory, RtlZeroMemory, SEC_BASED, SEC_COMMIT, SEC_IMAGE, SEC_LARGE_PAGES, SEC_NO_CHANGE, SEC_NOCACHE, SEC_RESERVE, _FILE_OBJECT::SectionObjectPointer, _CONTROL_AREA::Segment, _SECTION::Segment, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _SECTION::SizeOfSection, _SEGMENT::SizeOfSegment, _MMADDRESS_NODE::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_FILE_FOR_SECTION, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_6, STATUS_MAPPED_FILE_SIZE_ZERO, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, STATUS_SECTION_TOO_BIG, _SEGMENT::TotalNumberOfPtes, TRUE, _CONTROL_AREA::u, _SECTION::u, UNLOCK_PFN, UNREFERENCED_PARAMETER, _MMSECTION_FLAGS::UserReference, _MMSECTION_FLAGS::UserWritable, _CONTROL_AREA::WaitingForDeletion, _MMSECTION_FLAGS::WasPurged, _CONTROL_AREA::WritableUserReferences, WrVirtualMemory, and X64K.
Referenced by CcInitializeCacheMap(), FsRtlCreateSectionForDataScan(), and NtCreateSection().
NTSTATUS NtCreateSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PLARGE_INTEGER MaximumSize, __in ULONG SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle)
Definition at line 132 of file creasect.c.
References ARGUMENT_PRESENT, ASSERT, CcZeroEndOfLastPage(), _SEGMENT::ControlArea, DISPATCH_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CONTROL_AREA::FilePointer, Handle, KeDelayExecutionThread(), KeGetCurrentIrql(), KeGetPreviousMode, KernelMode, MmCreateSection(), MmHalfSecond, NT_SUCCESS, NULL, ObInsertObject(), PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_WRITECOMBINE, PROBE_ALIGNMENT, ProbeForReadSmallStructure, ProbeForWriteHandle, SEC_BASED, SEC_COMMIT, SEC_IMAGE, SEC_LARGE_PAGES, SEC_NO_CHANGE, SEC_NOCACHE, SEC_RESERVE, _CONTROL_AREA::Segment, Status, STATUS_FILE_LOCK_CONFLICT, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_6, and ZERO_LARGE.
NTSTATUS NtOpenSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 4982 of file creasect.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, MmSectionObjectType, NULL, ObOpenObjectByName(), PAGED_CODE, ProbeForWriteHandle, and Status.
Variable Documentation
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.
ULONG MiImageFailure
Definition at line 1672 of file creasect.c.
SIZE_T MmAllocationFragment
Definition at line 243 of file mminit.c.
Referenced by MiCreateDataFileMap().
const ULONG MMCONTROL = 'aCmM'
Definition at line 22 of file creasect.c.
Referenced by MiCreateImageFileMap(), MiCreatePagingFileMap(), MiSectionInitialization(), and MmCreateSection().
CCHAR MmImageProtectionArray[16]
Initial value:
= {
                                    MM_NOACCESS,
                                    MM_EXECUTE,
                                    MM_READONLY,
                                    MM_EXECUTE_READ,
                                    MM_WRITECOPY,
                                    MM_EXECUTE_WRITECOPY,
                                    MM_WRITECOPY,
                                    MM_EXECUTE_WRITECOPY,
                                    MM_NOACCESS,
                                    MM_EXECUTE,
                                    MM_READONLY,
                                    MM_EXECUTE_READ,
                                    MM_READWRITE,
                                    MM_EXECUTE_READWRITE,
                                    MM_READWRITE,
                                    MM_EXECUTE_READWRITE }
Definition at line 48 of file creasect.c.
Referenced by MiGetImageProtection().
const ULONG MMTEMPORARY = 'xxmM'
Definition at line 23 of file creasect.c.
Referenced by MiCreateImageFileMap().