Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/oplock.c File Reference
oplock.c File Reference
#include "FsRtlP.h"
Data Structures
struct _NONOPAQUE_OPLOCK
struct _WAITING_IRP
Macros
#define BATCH_OPLOCK (0x00000004)
#define BREAK_TO_II (0x00000100)
#define BREAK_TO_II_TO_NONE (0x00000400)
#define BREAK_TO_NONE (0x00000200)
#define CLOSE_PENDING (0x00000800)
#define Dbg (0x08000000)
#define EXCLUSIVE (0x00000040)
#define FILTER_OPLOCK (0x00000008)
#define FILTER_OPLOCK_VALID_FLAGS
#define LEVEL_I_OPLOCK (0x00000002)
#define LEVEL_II_OPLOCK (0x00000010)
#define MODULE_POOL_TAG ('orSF')
#define NO_OPLOCK (0x00000001)
#define NoOplocksHeld (NO_OPLOCK)
#define OpBatchBreaktoII (BATCH_OPLOCK | EXCLUSIVE | BREAK_TO_II)
#define OpBatchBreaktoIItoNone (BATCH_OPLOCK | EXCLUSIVE | BREAK_TO_II_NONE)
#define OpBatchBreaktoNone (BATCH_OPLOCK | EXCLUSIVE | BREAK_TO_NONE)
#define OpBatchClosePending (BATCH_OPLOCK | EXCLUSIVE | CLOSE_PENDING)
#define OpBatchGranted (BATCH_OPLOCK | EXCLUSIVE)
#define OpFilterBreaktoII (FILTER_OPLOCK | EXCLUSIVE | BREAK_TO_II)
#define OpFilterBreaktoIItoNone (FILTER_OPLOCK | EXCLUSIVE | BREAK_TO_II_NONE)
#define OpFilterBreaktoNone (FILTER_OPLOCK | EXCLUSIVE | BREAK_TO_NONE)
#define OpFilterClosePending (FILTER_OPLOCK | EXCLUSIVE | CLOSE_PENDING)
#define OpFilterGranted (FILTER_OPLOCK | EXCLUSIVE)
#define OpFilterReqPending (FILTER_OPLOCK | EXCLUSIVE | PENDING)
#define OPLOCK_BREAK_MASK (0x00000f00)
#define OPLOCK_HELD_MASK (0x000000c0)
#define OPLOCK_TYPE_MASK (0x0000001f)
#define OplockBreakItoII (LEVEL_I_OPLOCK | EXCLUSIVE | BREAK_TO_II)
#define OplockBreakItoIItoNone (LEVEL_I_OPLOCK | EXCLUSIVE | BREAK_TO_II_NONE)
#define OplockBreakItoNone (LEVEL_I_OPLOCK | EXCLUSIVE | BREAK_TO_NONE)
#define OplockIGranted (LEVEL_I_OPLOCK | EXCLUSIVE)
#define OplockIIGranted (LEVEL_II_OPLOCK)
#define PENDING (0x00000080)
Typedefs
typedef struct _NONOPAQUE_OPLOCK NONOPAQUE_OPLOCK
typedef ULONG OPLOCK_STATE
typedef struct _NONOPAQUE_OPLOCK * PNONOPAQUE_OPLOCK
typedef struct _WAITING_IRP * PWAITING_IRP
typedef struct _WAITING_IRP WAITING_IRP
Functions
NTSTATUS FsRtlAcknowledgeOplockBreak (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp, IN BOOLEAN GrantLevelII)
PNONOPAQUE_OPLOCK FsRtlAllocateOplock ()
VOID FsRtlCancelExclusiveIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
VOID FsRtlCancelOplockIIIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
VOID FsRtlCancelWaitIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS FsRtlCheckOplock (__in POPLOCK Oplock, __in PIRP Irp, __in_opt PVOID Context, __in_opt POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine, __in_opt POPLOCK_FS_PREPOST_IRP PostIrpRoutine)
VOID FsRtlCompletionRoutinePriv (IN PVOID Context, IN PIRP Irp)
BOOLEAN FsRtlCurrentBatchOplock (__in POPLOCK Oplock)
VOID FsRtlInitializeOplock (__inout POPLOCK Oplock)
VOID FsRtlNotifyCompletion (IN PVOID Context, IN PIRP Irp)
NTSTATUS FsRtlOpBatchBreakClosePending (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp)
NTSTATUS FsRtlOplockBreakNotify (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp)
NTSTATUS FsRtlOplockBreakToII (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp, IN PVOID Context, IN POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine OPTIONAL, IN POPLOCK_FS_PREPOST_IRP PostIrpRoutine OPTIONAL)
NTSTATUS FsRtlOplockBreakToNone (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp, IN PVOID Context, IN POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine OPTIONAL, IN POPLOCK_FS_PREPOST_IRP PostIrpRoutine OPTIONAL)
VOID FsRtlOplockCleanup (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp)
NTSTATUS FsRtlOplockFsctrl (__in POPLOCK Oplock, __in PIRP Irp, __in ULONG OpenCount)
BOOLEAN FsRtlOplockIsFastIoPossible (__in POPLOCK Oplock)
VOID FsRtlRemoveAndCompleteIrp (IN PLIST_ENTRY Link)
VOID FsRtlRemoveAndCompleteWaitIrp (IN PWAITING_IRP WaitingIrp)
NTSTATUS FsRtlRequestExclusiveOplock (IN OUT PNONOPAQUE_OPLOCK *Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp OPTIONAL, IN OPLOCK_STATE NextOplockState)
NTSTATUS FsRtlRequestOplockII (IN OUT PNONOPAQUE_OPLOCK *Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp)
VOID FsRtlUninitializeOplock (__inout POPLOCK Oplock)
NTSTATUS FsRtlWaitOnIrp (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIRP Irp, IN PVOID Context, IN POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine OPTIONAL, IN POPLOCK_FS_PREPOST_IRP PostIrpRoutine OPTIONAL, IN PKEVENT Event)
Macro Definition Documentation
#define BATCH_OPLOCK (0x00000004)
Definition at line 75 of file oplock.c.
Referenced by FsRtlCheckOplock(), FsRtlCurrentBatchOplock(), and FsRtlOplockBreakToII().
#define BREAK_TO_II (0x00000100)
Definition at line 86 of file oplock.c.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakToII(), and FsRtlOplockBreakToNone().
#define BREAK_TO_II_TO_NONE (0x00000400)
Definition at line 88 of file oplock.c.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlOpBatchBreakClosePending(), and FsRtlOplockBreakToNone().
#define BREAK_TO_NONE (0x00000200)
Definition at line 87 of file oplock.c.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakToII(), and FsRtlOplockBreakToNone().
#define CLOSE_PENDING (0x00000800)
Definition at line 89 of file oplock.c.
Referenced by FsRtlOpBatchBreakClosePending().
#define Dbg (0x08000000)
Definition at line 47 of file oplock.c.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlAllocateOplock(), FsRtlCancelExclusiveIrp(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlCheckOplock(), FsRtlCompletionRoutinePriv(), FsRtlCurrentBatchOplock(), FsRtlInitializeOplock(), FsRtlNotifyCompletion(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlOplockFsctrl(), FsRtlOplockIsFastIoPossible(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeOplock(), and FsRtlWaitOnIrp().
#define EXCLUSIVE (0x00000040)
Definition at line 81 of file oplock.c.
Referenced by FsRtlOplockBreakToII(), and FsRtlOplockFsctrl().
#define FILTER_OPLOCK (0x00000008)
Definition at line 76 of file oplock.c.
Referenced by FsRtlCheckOplock(), and FsRtlCurrentBatchOplock().
#define FILTER_OPLOCK_VALID_FLAGS
Value:
(\
    FILE_READ_ATTRIBUTES            |   \
    FILE_WRITE_ATTRIBUTES           |   \
    FILE_READ_DATA                  |   \
    FILE_READ_EA                    |   \
    FILE_EXECUTE                    |   \
    SYNCHRONIZE                     |   \
    READ_CONTROL                        \
)
Definition at line 54 of file oplock.c.
Referenced by FsRtlCheckOplock().
#define LEVEL_I_OPLOCK (0x00000002)
Definition at line 74 of file oplock.c.
Referenced by FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakToII(), and FsRtlOplockFsctrl().
#define LEVEL_II_OPLOCK (0x00000010)
Definition at line 77 of file oplock.c.
Referenced by FsRtlOplockBreakToNone(), FsRtlOplockIsFastIoPossible(), FsRtlRequestExclusiveOplock(), and FsRtlRequestOplockII().
#define MODULE_POOL_TAG ('orSF')
Definition at line 232 of file oplock.c.
#define NO_OPLOCK (0x00000001)
Definition at line 73 of file oplock.c.
Referenced by FsRtlRequestExclusiveOplock(), and FsRtlRequestOplockII().
#define NoOplocksHeld (NO_OPLOCK)
Definition at line 97 of file oplock.c.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlAllocateOplock(), FsRtlCancelExclusiveIrp(), FsRtlCancelOplockIIIrp(), FsRtlCheckOplock(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), and FsRtlOplockCleanup().
#define OpBatchBreaktoII (BATCH_OPLOCK | EXCLUSIVE | BREAK_TO_II)
Definition at line 105 of file oplock.c.
#define OpBatchBreaktoIItoNone (BATCH_OPLOCK | EXCLUSIVE | BREAK_TO_II_NONE)
Definition at line 113 of file oplock.c.
#define OpBatchBreaktoNone (BATCH_OPLOCK | EXCLUSIVE | BREAK_TO_NONE)
Definition at line 109 of file oplock.c.
#define OpBatchClosePending (BATCH_OPLOCK | EXCLUSIVE | CLOSE_PENDING)
Definition at line 116 of file oplock.c.
#define OpBatchGranted (BATCH_OPLOCK | EXCLUSIVE)
Definition at line 100 of file oplock.c.
#define OpFilterBreaktoII (FILTER_OPLOCK | EXCLUSIVE | BREAK_TO_II)
Definition at line 106 of file oplock.c.
#define OpFilterBreaktoIItoNone (FILTER_OPLOCK | EXCLUSIVE | BREAK_TO_II_NONE)
Definition at line 114 of file oplock.c.
#define OpFilterBreaktoNone (FILTER_OPLOCK | EXCLUSIVE | BREAK_TO_NONE)
Definition at line 110 of file oplock.c.
#define OpFilterClosePending (FILTER_OPLOCK | EXCLUSIVE | CLOSE_PENDING)
Definition at line 117 of file oplock.c.
#define OpFilterGranted (FILTER_OPLOCK | EXCLUSIVE)
Definition at line 101 of file oplock.c.
#define OpFilterReqPending (FILTER_OPLOCK | EXCLUSIVE | PENDING)
Definition at line 102 of file oplock.c.
Referenced by FsRtlOplockFsctrl(), and FsRtlRequestExclusiveOplock().
#define OPLOCK_BREAK_MASK (0x00000f00)
Definition at line 91 of file oplock.c.
Referenced by FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), and FsRtlOplockIsFastIoPossible().
#define OPLOCK_HELD_MASK (0x000000c0)
Definition at line 84 of file oplock.c.
#define OPLOCK_TYPE_MASK (0x0000001f)
Definition at line 79 of file oplock.c.
#define OplockBreakItoII (LEVEL_I_OPLOCK | EXCLUSIVE | BREAK_TO_II)
Definition at line 104 of file oplock.c.
#define OplockBreakItoIItoNone (LEVEL_I_OPLOCK | EXCLUSIVE | BREAK_TO_II_NONE)
Definition at line 112 of file oplock.c.
#define OplockBreakItoNone (LEVEL_I_OPLOCK | EXCLUSIVE | BREAK_TO_NONE)
Definition at line 108 of file oplock.c.
#define OplockIGranted (LEVEL_I_OPLOCK | EXCLUSIVE)
Definition at line 99 of file oplock.c.
#define OplockIIGranted (LEVEL_II_OPLOCK)
Definition at line 119 of file oplock.c.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCheckOplock(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlRequestExclusiveOplock(), and FsRtlRequestOplockII().
#define PENDING (0x00000080)
Definition at line 82 of file oplock.c.
Referenced by FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), and FsRtlRequestExclusiveOplock().
Typedef Documentation
typedef struct _NONOPAQUE_OPLOCK NONOPAQUE_OPLOCK
typedef ULONG OPLOCK_STATE
Definition at line 125 of file oplock.c.
typedef struct _NONOPAQUE_OPLOCK * PNONOPAQUE_OPLOCK
typedef struct _WAITING_IRP * PWAITING_IRP
typedef struct _WAITING_IRP WAITING_IRP
Function Documentation
NTSTATUS FsRtlAcknowledgeOplockBreak (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp, IN BOOLEAN GrantLevelII)
Definition at line 1674 of file oplock.c.
References ASSERT, BREAK_TO_II, BREAK_TO_II_TO_NONE, BREAK_TO_NONE, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FALSE, FILE_OPLOCK_BROKEN_TO_NONE, FlagOn, FsRtlCancelOplockIIIrp(), FsRtlCompleteRequest, FsRtlRemoveAndCompleteWaitIrp(), InsertHeadList(), IoAcquireCancelSpinLock(), IoIsOperationSynchronous(), IoMarkIrpPending, IoReleaseCancelSpinLock(), IoSetCancelRoutine, IsListEmpty, NoOplocksHeld, NOTHING, NULL, ObDereferenceObject(), OplockIIGranted, Status, STATUS_INVALID_OPLOCK_PROTOCOL, STATUS_PENDING, STATUS_SUCCESS, TRUE, and try_return.
Referenced by FsRtlOplockFsctrl().
PNONOPAQUE_OPLOCK FsRtlAllocateOplock ()
Definition at line 1219 of file oplock.c.
References Dbg, DebugTrace, ExFreePool(), ExInitializeFastMutex, _NONOPAQUE_OPLOCK::FastMutex, FsRtlpAllocatePool, InitializeListHead(), _NONOPAQUE_OPLOCK::IrpOplocksII, NonPagedPool, NoOplocksHeld, NULL, _NONOPAQUE_OPLOCK::OplockState, PAGED_CODE, PagedPool, POOL_COLD_ALLOCATION, RtlZeroMemory, and _NONOPAQUE_OPLOCK::WaitingIrps.
Referenced by FsRtlRequestExclusiveOplock(), and FsRtlRequestOplockII().
VOID FsRtlCancelExclusiveIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 3514 of file oplock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutex(), ExReleaseFastMutex(), _NONOPAQUE_OPLOCK::FastMutex, _NONOPAQUE_OPLOCK::FileObject, _LIST_ENTRY::Flink, FsRtlCompleteRequest, FsRtlRemoveAndCompleteWaitIrp(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, _NONOPAQUE_OPLOCK::IrpExclusiveOplock, IsListEmpty, NoOplocksHeld, NULL, ObDereferenceObject(), _NONOPAQUE_OPLOCK::OplockState, STATUS_CANCELLED, UNREFERENCED_PARAMETER, and _NONOPAQUE_OPLOCK::WaitingIrps.
Referenced by FsRtlRequestExclusiveOplock().
VOID FsRtlCancelOplockIIIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 3391 of file oplock.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, _NONOPAQUE_OPLOCK::FastMutex, _LIST_ENTRY::Flink, FsRtlRemoveAndCompleteIrp(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, IRP, _NONOPAQUE_OPLOCK::IrpOplocksII, IsListEmpty, NoOplocksHeld, NULL, _NONOPAQUE_OPLOCK::OplockState, PIRP, TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlAcknowledgeOplockBreak(), and FsRtlRequestOplockII().
VOID FsRtlCancelWaitIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 3283 of file oplock.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutex(), ExReleaseFastMutex(), _NONOPAQUE_OPLOCK::FastMutex, _LIST_ENTRY::Flink, FsRtlRemoveAndCompleteWaitIrp(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_IRP::Irp, NULL, UNREFERENCED_PARAMETER, and _NONOPAQUE_OPLOCK::WaitingIrps.
Referenced by FsRtlWaitOnIrp().
NTSTATUS FsRtlCheckOplock (__in POPLOCK Oplock, __in PIRP Irp, __in_opt PVOID Context, __in_opt POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine, __in_opt POPLOCK_FS_PREPOST_IRP PostIrpRoutine)
Definition at line 820 of file oplock.c.
References BATCH_OPLOCK, Dbg, DebugTrace, FALSE, FILE_OVERWRITE, FILE_OVERWRITE_IF, FILE_READ_ATTRIBUTES, FILE_RESERVE_OPFILTER, FILE_SHARE_READ, FILE_SUPERSEDE, FILE_WRITE_ATTRIBUTES, FileAllocationInformation, FileEndOfFileInformation, FileLinkInformation, _NONOPAQUE_OPLOCK::FileObject, _IO_STACK_LOCATION::FileObject, FileRenameInformation, FileShortNameInformation, FILTER_OPLOCK, FILTER_OPLOCK_VALID_FLAGS, FlagOn, FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), IoGetCurrentIrpStackLocation, IRP_MJ_CLEANUP, IRP_MJ_CREATE, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MJ_FLUSH_BUFFERS, IRP_MJ_LOCK_CONTROL, IRP_MJ_READ, IRP_MJ_SET_INFORMATION, IRP_MJ_WRITE, IRP_PAGING_IO, _IO_STACK_LOCATION::MajorFunction, NoOplocksHeld, NULL, OplockIIGranted, _NONOPAQUE_OPLOCK::OplockState, _IO_STACK_LOCATION::Parameters, Status, STATUS_SUCCESS, SYNCHRONIZE, and TRUE.
VOID FsRtlCompletionRoutinePriv (IN PVOID Context, IN PIRP Irp)
Definition at line 3236 of file oplock.c.
References Dbg, DebugTrace, FALSE, KeSetEvent(), PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlWaitOnIrp().
BOOLEAN FsRtlCurrentBatchOplock (__in POPLOCK Oplock)
Definition at line 1167 of file oplock.c.
References BATCH_OPLOCK, Dbg, DebugTrace, FALSE, FILTER_OPLOCK, FlagOn, NULL, PAGED_CODE, and TRUE.
VOID FsRtlInitializeOplock (__inout POPLOCK Oplock)
Definition at line 370 of file oplock.c.
References Dbg, DebugTrace, PAGED_CODE, and UNREFERENCED_PARAMETER.
VOID FsRtlNotifyCompletion (IN PVOID Context, IN PIRP Irp)
Definition at line 3693 of file oplock.c.
References Dbg, DebugTrace, FsRtlCompleteRequest, PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlOplockBreakNotify().
NTSTATUS FsRtlOpBatchBreakClosePending (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp)
Definition at line 1933 of file oplock.c.
References BREAK_TO_II, BREAK_TO_II_TO_NONE, BREAK_TO_NONE, ClearFlag, CLOSE_PENDING, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FlagOn, FsRtlCompleteRequest, FsRtlRemoveAndCompleteWaitIrp(), IsListEmpty, LEVEL_I_OPLOCK, NoOplocksHeld, NULL, ObDereferenceObject(), OPLOCK_BREAK_MASK, PAGED_CODE, PENDING, SetFlag, Status, STATUS_INVALID_OPLOCK_PROTOCOL, and STATUS_SUCCESS.
Referenced by FsRtlOplockFsctrl().
NTSTATUS FsRtlOplockBreakNotify (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp)
Definition at line 2104 of file oplock.c.
References Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FALSE, FlagOn, FsRtlCompleteRequest, FsRtlNotifyCompletion(), FsRtlWaitOnIrp(), NoOplocksHeld, NOTHING, NULL, OPLOCK_BREAK_MASK, PAGED_CODE, PENDING, Status, STATUS_SUCCESS, TRUE, try_return, and UNREFERENCED_PARAMETER.
Referenced by FsRtlOplockFsctrl().
NTSTATUS FsRtlOplockBreakToII (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp, IN PVOID Context, IN POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine OPTIONAL, IN POPLOCK_FS_PREPOST_IRP PostIrpRoutine OPTIONAL)
Definition at line 2449 of file oplock.c.
References BATCH_OPLOCK, BREAK_TO_II, BREAK_TO_NONE, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), EXCLUSIVE, ExReleaseFastMutexUnsafe(), FALSE, FILE_COMPLETE_IF_OPLOCKED, FILE_OPLOCK_BROKEN_TO_LEVEL_2, FILE_OPLOCK_BROKEN_TO_NONE, FlagOn, FsRtlCompleteRequest, FsRtlRemoveAndCompleteWaitIrp(), FsRtlWaitOnIrp(), IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, IRP_MJ_CREATE, IsListEmpty, LEVEL_I_OPLOCK, NoOplocksHeld, NOTHING, NULL, ObDereferenceObject(), OPLOCK_BREAK_MASK, PENDING, PIRP, SetFlag, Status, STATUS_CANCELLED, STATUS_OPLOCK_BREAK_IN_PROGRESS, STATUS_SUCCESS, TRUE, and try_return.
Referenced by FsRtlCheckOplock().
NTSTATUS FsRtlOplockBreakToNone (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp, IN PVOID Context, IN POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine OPTIONAL, IN POPLOCK_FS_PREPOST_IRP PostIrpRoutine OPTIONAL)
Definition at line 2686 of file oplock.c.
References BREAK_TO_II, BREAK_TO_II_TO_NONE, BREAK_TO_NONE, ClearFlag, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FALSE, FILE_COMPLETE_IF_OPLOCKED, FILE_OPLOCK_BROKEN_TO_NONE, FlagOn, FsRtlCompleteRequest, FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlWaitOnIrp(), IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, IRP_MJ_CREATE, IsListEmpty, LEVEL_II_OPLOCK, NoOplocksHeld, NOTHING, NULL, ObDereferenceObject(), OPLOCK_BREAK_MASK, OplockIIGranted, PENDING, PIRP, SetFlag, Status, STATUS_CANCELLED, STATUS_OPLOCK_BREAK_IN_PROGRESS, STATUS_SUCCESS, TRUE, and try_return.
Referenced by FsRtlCheckOplock().
VOID FsRtlOplockCleanup (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIO_STACK_LOCATION IrpSp)
Definition at line 2244 of file oplock.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FILE_OPLOCK_BROKEN_TO_NONE, _IO_STACK_LOCATION::FileObject, FlagOn, _LIST_ENTRY::Flink, FsRtlCompleteRequest, FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), IoAcquireCancelSpinLock(), IoGetCurrentIrpStackLocation, IoReleaseCancelSpinLock(), IoSetCancelRoutine, IRP, IsListEmpty, NoOplocksHeld, NOTHING, NULL, ObDereferenceObject(), OPLOCK_BREAK_MASK, OplockIIGranted, PENDING, PIRP, STATUS_SUCCESS, and try_return.
Referenced by FsRtlCheckOplock().
NTSTATUS FsRtlOplockFsctrl (__in POPLOCK Oplock, __in PIRP Irp, __in ULONG OpenCount)
Definition at line 578 of file oplock.c.
References Dbg, DebugTrace, EXCLUSIVE, FALSE, FILE_READ_ATTRIBUTES, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _IO_STACK_LOCATION::FileObject, FlagOn, _FILE_OBJECT::Flags, FO_CLEANUP_COMPLETE, FSCTL_OPBATCH_ACK_CLOSE_PENDING, FSCTL_OPLOCK_BREAK_ACK_NO_2, FSCTL_OPLOCK_BREAK_ACKNOWLEDGE, FSCTL_OPLOCK_BREAK_NOTIFY, FSCTL_REQUEST_BATCH_OPLOCK, FSCTL_REQUEST_FILTER_OPLOCK, FSCTL_REQUEST_OPLOCK_LEVEL_1, FSCTL_REQUEST_OPLOCK_LEVEL_2, FsRtlAcknowledgeOplockBreak(), FsRtlCompleteRequest, FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), IoGetCurrentIrpStackLocation, IoIsOperationSynchronous(), IRP_INPUT_OPERATION, IRP_MJ_CREATE, LEVEL_I_OPLOCK, _IO_STACK_LOCATION::MajorFunction, NULL, OpFilterReqPending, PAGED_CODE, _IO_STACK_LOCATION::Parameters, SetFlag, Status, STATUS_INVALID_PARAMETER, STATUS_OPLOCK_NOT_GRANTED, and TRUE.
BOOLEAN FsRtlOplockIsFastIoPossible (__in POPLOCK Oplock)
Definition at line 1114 of file oplock.c.
References Dbg, DebugTrace, FALSE, FlagOn, LEVEL_II_OPLOCK, NULL, OPLOCK_BREAK_MASK, PAGED_CODE, and TRUE.
VOID FsRtlRemoveAndCompleteIrp (IN PLIST_ENTRY Link)
Definition at line 2947 of file oplock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, FILE_OPLOCK_BROKEN_TO_NONE, _IO_STACK_LOCATION::FileObject, FsRtlCompleteRequest, IoAcquireCancelSpinLock(), IoGetCurrentIrpStackLocation, IoReleaseCancelSpinLock(), IoSetCancelRoutine, IRP, NULL, ObDereferenceObject(), PIRP, RemoveEntryList(), STATUS_CANCELLED, and STATUS_SUCCESS.
Referenced by FsRtlCancelOplockIIIrp(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), and FsRtlRequestExclusiveOplock().
VOID FsRtlRemoveAndCompleteWaitIrp (IN PWAITING_IRP WaitingIrp)
Definition at line 3618 of file oplock.c.
References Dbg, DebugTrace, ExFreePool(), IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, NULL, PAGED_CODE, PIRP, RemoveEntryList(), STATUS_CANCELLED, and STATUS_SUCCESS.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCancelExclusiveIrp(), FsRtlCancelWaitIrp(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), and FsRtlOplockCleanup().
NTSTATUS FsRtlRequestExclusiveOplock (IN OUT PNONOPAQUE_OPLOCK * Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp OPTIONAL, IN OPLOCK_STATE NextOplockState)
Definition at line 1297 of file oplock.c.
References ARGUMENT_PRESENT, ASSERT, _LIST_ENTRY::Blink, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FALSE, _NONOPAQUE_OPLOCK::FastMutex, _NONOPAQUE_OPLOCK::FileObject, FlagOn, _LIST_ENTRY::Flink, FsRtlAllocateOplock(), FsRtlCancelExclusiveIrp(), FsRtlCompleteRequest, FsRtlRemoveAndCompleteIrp(), IoAcquireCancelSpinLock(), IoMarkIrpPending, IoReleaseCancelSpinLock(), IoSetCancelRoutine, _NONOPAQUE_OPLOCK::IrpExclusiveOplock, _NONOPAQUE_OPLOCK::IrpOplocksII, LEVEL_II_OPLOCK, NO_OPLOCK, NULL, ObReferenceObject, OpFilterReqPending, OplockIIGranted, _NONOPAQUE_OPLOCK::OplockState, PENDING, Status, STATUS_OPLOCK_NOT_GRANTED, STATUS_PENDING, STATUS_SUCCESS, and TRUE.
Referenced by FsRtlOplockFsctrl().
NTSTATUS FsRtlRequestOplockII (IN OUT PNONOPAQUE_OPLOCK * Oplock, IN PIO_STACK_LOCATION IrpSp, IN PIRP Irp)
Definition at line 1510 of file oplock.c.
References Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExReleaseFastMutexUnsafe(), FALSE, _NONOPAQUE_OPLOCK::FastMutex, FlagOn, FsRtlAllocateOplock(), FsRtlCancelOplockIIIrp(), FsRtlCompleteRequest, InsertHeadList(), IoAcquireCancelSpinLock(), IoMarkIrpPending, IoReleaseCancelSpinLock(), IoSetCancelRoutine, _NONOPAQUE_OPLOCK::IrpOplocksII, LEVEL_II_OPLOCK, NO_OPLOCK, NULL, ObReferenceObject, OplockIIGranted, _NONOPAQUE_OPLOCK::OplockState, Status, STATUS_OPLOCK_NOT_GRANTED, STATUS_PENDING, STATUS_SUCCESS, and TRUE.
Referenced by FsRtlOplockFsctrl().
VOID FsRtlUninitializeOplock (__inout POPLOCK Oplock)
Definition at line 410 of file oplock.c.
References _WAITING_IRP::CompletionRoutine, CONTAINING_RECORD, _WAITING_IRP::Context, Dbg, DebugTrace, ExAcquireFastMutexUnsafe(), ExFreePool(), ExReleaseFastMutexUnsafe(), _NONOPAQUE_OPLOCK::FastMutex, FILE_OPLOCK_BROKEN_TO_NONE, _NONOPAQUE_OPLOCK::FileObject, _LIST_ENTRY::Flink, FsRtlCompleteRequest, IoAcquireCancelSpinLock(), IoGetCurrentIrpStackLocation, IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_IRP::Irp, IRP, _NONOPAQUE_OPLOCK::IrpExclusiveOplock, _NONOPAQUE_OPLOCK::IrpOplocksII, IsListEmpty, NULL, ObDereferenceObject(), PIRP, RemoveHeadList(), STATUS_SUCCESS, and _NONOPAQUE_OPLOCK::WaitingIrps.
NTSTATUS FsRtlWaitOnIrp (IN OUT PNONOPAQUE_OPLOCK Oplock, IN PIRP Irp, IN PVOID Context, IN POPLOCK_WAIT_COMPLETE_ROUTINE CompletionRoutine OPTIONAL, IN POPLOCK_FS_PREPOST_IRP PostIrpRoutine OPTIONAL, IN PKEVENT Event)
Definition at line 3020 of file oplock.c.
References ARGUMENT_PRESENT, _WAITING_IRP::CompletionRoutine, _WAITING_IRP::Context, Dbg, DebugTrace, Executive, ExReleaseFastMutexUnsafe(), FALSE, FsRtlCancelWaitIrp(), FsRtlCompletionRoutinePriv(), FsRtlpAllocatePool, _WAITING_IRP::Information, InsertTailList(), IoAcquireCancelSpinLock(), IoMarkIrpPending, IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_IRP::Irp, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _WAITING_IRP::Links, NotificationEvent, NULL, PagedPool, Status, STATUS_CANCELLED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, and TRUE.
Referenced by FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), and FsRtlOplockBreakToNone().