Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/semphore.c File Reference
semphore.c File Reference
#include "exp.h"
Functions
BOOLEAN ExpSemaphoreInitialization (VOID)
NTSTATUS NtCreateSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in LONG InitialCount, __in LONG MaximumCount)
NTSTATUS NtOpenSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQuerySemaphore (__in HANDLE SemaphoreHandle, __in SEMAPHORE_INFORMATION_CLASS SemaphoreInformationClass, __out_bcount(SemaphoreInformationLength) PVOID SemaphoreInformation, __in ULONG SemaphoreInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtReleaseSemaphore (__in HANDLE SemaphoreHandle, __in LONG ReleaseCount, __out_opt PLONG PreviousCount)
Variables
ULONG ExpSemaphoreBoost = SEMAPHORE_INCREMENT
const GENERIC_MAPPING ExpSemaphoreMapping
POBJECT_TYPE ExSemaphoreObjectType
Function Documentation
BOOLEAN ExpSemaphoreInitialization (VOID)
Definition at line 61 of file semphore.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, ExpSemaphoreMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, SEMAPHORE_ALL_ACCESS, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
NTSTATUS NtCreateSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in LONG InitialCount, __in LONG MaximumCount)
Definition at line 121 of file semphore.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KeInitializeSemaphore(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, Status, and STATUS_INVALID_PARAMETER.
NTSTATUS NtOpenSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 252 of file semphore.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSTATUS NtQuerySemaphore (__in HANDLE SemaphoreHandle, __in SEMAPHORE_INFORMATION_CLASS SemaphoreInformationClass, __out_bcount(SemaphoreInformationLength) PVOID SemaphoreInformation, __in ULONG SemaphoreInformationLength, __out_opt PULONG ReturnLength)
Definition at line 343 of file semphore.c.
References ARGUMENT_PRESENT, Count, _SEMAPHORE_BASIC_INFORMATION::CurrentCount, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeReadStateSemaphore(), KernelMode, _SEMAPHORE_BASIC_INFORMATION::MaximumCount, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, SEMAPHORE_QUERY_STATE, SemaphoreBasicInformation, Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_INVALID_INFO_CLASS.
NTSTATUS NtReleaseSemaphore (__in HANDLE SemaphoreHandle, __in LONG ReleaseCount, __out_opt PLONG PreviousCount)
Definition at line 476 of file semphore.c.
References ARGUMENT_PRESENT, Count, except, EXCEPTION_EXECUTE_HANDLER, ExpSemaphoreBoost, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KeReleaseSemaphore(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, SEMAPHORE_MODIFY_STATE, Status, and STATUS_INVALID_PARAMETER.
Variable Documentation
ULONG ExpSemaphoreBoost = SEMAPHORE_INCREMENT
Definition at line 26 of file semphore.c.
Referenced by NtReleaseSemaphore().
const GENERIC_MAPPING ExpSemaphoreMapping
Initial value:
= {
    STANDARD_RIGHTS_READ | SEMAPHORE_QUERY_STATE,
    STANDARD_RIGHTS_WRITE | SEMAPHORE_MODIFY_STATE,
    STANDARD_RIGHTS_EXECUTE | SYNCHRONIZE,
    SEMAPHORE_ALL_ACCESS
}
Definition at line 43 of file semphore.c.
Referenced by ExpSemaphoreInitialization().
POBJECT_TYPE ExSemaphoreObjectType
Definition at line 32 of file semphore.c.