Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/shutdown.c File Reference
shutdown.c File Reference
#include "mi.h"
Data Structures
struct _MM_ZERO_PAGEFILE_CONTEXT
Typedefs
typedef struct _MM_ZERO_PAGEFILE_CONTEXT MM_ZERO_PAGEFILE_CONTEXT
typedef struct _MM_ZERO_PAGEFILE_CONTEXT * PMM_ZERO_PAGEFILE_CONTEXT
Functions
VOID MiReleaseAllMemory (VOID)
BOOLEAN MiShutdownSystem (VOID)
LOGICAL MiZeroAllPageFiles (VOID)
VOID MiZeroPageFile (IN PVOID Context)
BOOLEAN MmShutdownSystem (IN ULONG Phase)
Variables
LIST_ENTRY MiVerifierDriverAddedThunkListHead
LOGICAL MiZeroingDisabled
LIST_ENTRY MmLoadedUserImageList
ULONG MmNumberOfMappedMdls
ULONG MmNumberOfMappedMdlsInUse
ULONG MmSystemShutdown
ULONG MmUnusedSegmentForceFree
ULONG MmZeroPageFile
Typedef Documentation
typedef struct _MM_ZERO_PAGEFILE_CONTEXT MM_ZERO_PAGEFILE_CONTEXT
typedef struct _MM_ZERO_PAGEFILE_CONTEXT * PMM_ZERO_PAGEFILE_CONTEXT
Function Documentation
VOID MiReleaseAllMemory (VOID)
Definition at line 898 of file shutdown.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, _RTL_BITMAP::Buffer, CONTAINING_RECORD, _MMINPAGE_SUPPORT::e1, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, ExFreePool(), ExQueryDepthSList, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, InterlockedPopEntrySList(), IsListEmpty, _MMMOD_WRITER_LISTHEAD::ListHead, LOADED_AT_BOOT, _KLDR_DATA_TABLE_ENTRY::LoadedImports, MI_UNLOADED_DRIVERS, MiPfnBitMap, MiSuspectDriverList, MiZeroingDisabled, MM_PAGING_FILE_MDLS, MmEventCountSListHead, MmInPageSupportSListHead, MmMappedFileHeader, MmNumberOfMappedMdls, MmNumberOfMappedMdlsInUse, MmNumberOfPagingFiles, MmPagedPoolInfo, MmPagingFile, MmPhysicalMemoryBlock, MmSession, MmUnloadedDrivers, MmUnusedSegmentList, _UNLOADED_DRIVERS::Name, NO_IMPORTS_USED, NULL, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MMINPAGE_FLAGS::PrefetchMdlHighBits, PSLIST_ENTRY, PsLoadedModuleList, RemoveHeadList(), RtlFreeUnicodeString(), SINGLE_ENTRY, _MMSESSION::SystemSpaceBitMap, _MMSESSION::SystemSpaceViewTable, TRUE, _MMINPAGE_SUPPORT::u1, and VerifierLargePagedPoolMap.
Referenced by MmShutdownSystem().
BOOLEAN MiShutdownSystem (VOID)
Definition at line 399 of file shutdown.c.
References ASSERT, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _SUBSECTION::ControlArea, _LOAD_IMPORTS::Count, ExAllocatePoolWithTag, ExFreePool(), ExPageLockHandle, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMPFNLIST::Flink, _MMPFN::Flink, FsRtlAcquireFileForCcFlushEx(), FsRtlReleaseFileForCcFlush(), _KLDR_DATA_TABLE_ENTRY::FullDllName, _MMSECTION_FLAGS::Image, IoSynchronousPageWrite(), IsListEmpty, KeClearEvent(), KeDelayExecutionThread(), KeInitializeEvent(), KeReleaseMutant(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LOADED_AT_BOOT, _KLDR_DATA_TABLE_ENTRY::LoadedImports, LOCK_PFN, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiCheckControlArea(), MiGetSubsectionAddress, MiStartingOffset(), MiUnlinkPageFromList(), MiZeroAllPageFiles(), MM_EMPTY_LIST, MM_MAXIMUM_WRITE_CLUSTER, MmInitializeMdl, MmLockPageableSectionByHandle(), MmModifiedPageListHead, MmNumberOfPagingFiles, MmPagingFile, MmShortTime, MmSystemLoadLock, MmSystemShutdown, MmTwentySeconds, MmUnlockPageableImageSection(), MmUnmapLockedPages(), MmUnusedSegmentCleanup, MmUnusedSegmentForceFree, MmUnusedSegmentList, MmZeroPageFile, NO_IMPORTS_USED, _MMSECTION_FLAGS::NoModifiedWriting, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, _MMPFN::OriginalPte, PAGE_SIZE, _MMPAGING_FILE::PageFileName, PoCleanShutdownEnabled(), PopShutdownCleanly, _MMPTE_SOFTWARE::Prototype, PsLoadedModuleList, _MMPFN::PteAddress, _LARGE_INTEGER::QuadPart, RtlCopyMemory, SINGLE_ENTRY, _MMPTE::Soft, Status, STATUS_FILE_LOCK_CONFLICT, STATUS_TIMEOUT, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u1, UNLOCK_PFN, WrPageOut, WrVirtualMemory, and ZwClose().
Referenced by MmShutdownSystem().
LOGICAL MiZeroAllPageFiles (VOID)
Definition at line 258 of file shutdown.c.
References _MM_ZERO_PAGEFILE_CONTEXT::AllDone, ASSERT, CriticalWorkQueue, _MMPFN::e2, ExAllocatePoolWithTag, Executive, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, KeInitializeEvent(), KernelMode, KeSetEvent(), KeWaitForMultipleObjects(), LOCK_PFN, _MMPTE::Long, MAX_PAGE_FILES, MI_DECREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementReferenceCountInline, MiRemoveZeroPage(), MiZeroPageFile(), MM_LOW_LIMIT, MM_RESAVAIL_ALLOCATE_FOR_PAGEFILE_ZEROING, MM_RESAVAIL_FREE_FOR_PAGEFILE_ZEROING, MmAvailablePages, MmModifiedWriteClusterSize, MmNumberOfPagingFiles, MmPagingFile, NonPagedPool, NotificationEvent, NULL, _MMPFN::OriginalPte, _MM_ZERO_PAGEFILE_CONTEXT::PagingFile, _MMPFN::PteAddress, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, WaitAll, _MM_ZERO_PAGEFILE_CONTEXT::WorkItem, X64K, and _MM_ZERO_PAGEFILE_CONTEXT::ZeroedPageFrame.
Referenced by MiShutdownSystem().
VOID MiZeroPageFile (IN PVOID Context)
Definition at line 68 of file shutdown.c.
References _MM_ZERO_PAGEFILE_CONTEXT::AllDone, _MMPAGING_FILE::Bitmap, _MMPFN::e2, ExFreePool(), FALSE, _MMPAGING_FILE::File, InterlockedIncrementPfn, IoSynchronousPageWrite(), KeClearEvent(), KeInitializeEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LOCK_PFN, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MI_PFN_ELEMENT, MM_MAXIMUM_WRITE_CLUSTER, MmInitializeMdl, MmModifiedWriteClusterSize, MmTwentySeconds, MmUnmapLockedPages(), NotificationEvent, NT_SUCCESS, NULL, NumberOfBytes, PAGE_SHIFT, PAGE_SIZE, _MM_ZERO_PAGEFILE_CONTEXT::PagingFile, _LARGE_INTEGER::QuadPart, RtlCheckBit, RtlClearBits(), RtlSetBit(), SATISFY_OVERZEALOUS_COMPILER, _MMPAGING_FILE::Size, Status, STATUS_TIMEOUT, TRUE, _MMPFN::u3, UNLOCK_PFN, WrPageOut, and _MM_ZERO_PAGEFILE_CONTEXT::ZeroedPageFrame.
Referenced by MiZeroAllPageFiles().
BOOLEAN MmShutdownSystem (IN ULONG Phase)
Definition at line 791 of file shutdown.c.
References ASSERT, MiReleaseAllMemory(), MiShutdownSystem(), MmModifiedPageListHead, MmNumberOfPagingFiles, MmPagingFile, MmSystemShutdown, MmTotalPagesForPagingFile, MmTrimAllSystemPageableMemory(), ObDereferenceObject(), PO_CLEAN_SHUTDOWN_PAGING, PoCleanShutdownEnabled(), _MMPFNLIST::Total, and TRUE.
Referenced by MmInitSystem().
Variable Documentation
LIST_ENTRY MiVerifierDriverAddedThunkListHead
LOGICAL MiZeroingDisabled
Definition at line 27 of file zeropage.c.
Referenced by MiReleaseAllMemory(), and MmZeroPageThread().
LIST_ENTRY MmLoadedUserImageList
Definition at line 228 of file mminit.c.
ULONG MmNumberOfMappedMdls
Definition at line 38 of file modwrite.c.
Referenced by MiModifiedPageWriter(), and MiReleaseAllMemory().
ULONG MmNumberOfMappedMdlsInUse
Referenced by MiGatherMappedPages(), MiReleaseAllMemory(), and MiWriteComplete().
ULONG MmSystemShutdown
Definition at line 119 of file modwrite.c.
Referenced by MiModifiedPageWriter(), MiModifiedPageWriterWorker(), MiShutdownSystem(), and MmShutdownSystem().
ULONG MmUnusedSegmentForceFree
Definition at line 43 of file sectsup.c.
Referenced by MiRemoveUnusedSegments(), and MiShutdownSystem().
ULONG MmZeroPageFile
Definition at line 58 of file shutdown.c.
Referenced by MiShutdownSystem().