Windows Research Kernel v1.2: C:/Windows Research Kernel/se/rmmain.c File Reference
rmmain.c File Reference
#include "pch.h"
Functions
NTSTATUS SepRmCallLsa (PSEP_WORK_ITEM SepWorkItem)
VOID SepRmCommandServerThread (IN PVOID StartContext)
BOOLEAN SepRmCommandServerThreadInit (VOID)
BOOLEAN SepRmInitPhase0 ()
BOOLEAN SeRmInitPhase1 ()
Variables
const SEP_RM_COMMAND_WORKER SepRmCommandDispatch []
Function Documentation
NTSTATUS SepRmCallLsa (PSEP_WORK_ITEM SepWorkItem)
Definition at line 794 of file rmmain.c.
References ARGUMENT_PRESENT, ASSERT, _SEP_LSA_WORK_ITEM::BaseAddress, _SEP_LSA_WORK_ITEM::CleanupFunction, _SEP_LSA_WORK_ITEM::CleanupParameter, _LSA_COMMAND_MESSAGE::CommandNumber, _SEP_LSA_WORK_ITEM::CommandNumber, _LSA_COMMAND_MESSAGE::CommandParams, _SEP_LSA_WORK_ITEM::CommandParams, _SEP_LSA_WORK_ITEM::CommandParamsLength, _LSA_COMMAND_MESSAGE::CommandParamsMemoryType, _SEP_LSA_WORK_ITEM::CommandParamsMemoryType, ExFreePool(), KdPrint, KeAttachProcess(), KeDetachProcess(), LSA_MAXIMUM_COMMAND_PARAM_SIZE, _SEP_RM_STATE::LsaCommandPortHandle, LsapLogonSessionDeletedCommand, _SEP_RM_STATE::LsaViewPortMemory, MEM_RELEASE, _LSA_COMMAND_MESSAGE::MessageHeader, _LSA_REPLY_MESSAGE::MessageHeader, NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, _LSA_REPLY_MESSAGE::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBufferLength, _LSA_REPLY_MESSAGE::ReturnedStatus, RM_COMMAND_MESSAGE_HEADER_SIZE, _SEP_RM_STATE::RmViewPortMemory, RtlCopyMemory, _PORT_MESSAGE::s1, SEP_RM_LSA_SHARED_MEMORY_SIZE, SepAdtCopyToLsaSharedMemory(), SepDequeueWorkItem(), SepLsaHandle, SepLsaQueueLength, SepRmImmediateMemory, SepRmLsaCallProcess, SepRmLsaCommandPortSharedMemory, SepRmLsaCustomSharedMemory, SepRmPagedPoolMemory, SepRmState, SepRmUnspecifiedMemory, SepWorkListHead, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, UNREFERENCED_PARAMETER, _PORT_MESSAGE::ZeroInit, ZwFreeVirtualMemory(), ZwRequestPort(), and ZwRequestWaitReplyPort().
Referenced by SepQueueWorkItem().
VOID SepRmCommandServerThread (IN PVOID StartContext)
Definition at line 291 of file rmmain.c.
References ASSERT, _PORT_MESSAGE::ClientId, Executive, FALSE, KdPrint, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPC_PORT_CLOSED, LPC_REQUEST, _SEP_RM_STATE::LsaCommandPortHandle, _RM_COMMAND_MESSAGE::MessageHeader, _RM_REPLY_MESSAGE::MessageHeader, _PORT_MESSAGE::MessageId, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, PoRequestShutdownEvent(), RmAuditSetCommand, _SEP_RM_STATE::RmCommandPortHandle, _SEP_RM_STATE::RmCommandServerPortHandle, RmDeleteLogonSession, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SepAdtLsaDeadEvent, SepLockLsaQueue, SepLsaHandle, SepRmCommandDispatch, SepRmCommandServerThreadInit(), SepRmState, SepUnlockLsaQueue, SepWorkListEmpty, Status, STATUS_INVALID_CID, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_UNSUCCESSFUL, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, UNREFERENCED_PARAMETER, _PORT_MESSAGE::ZeroInit, ZwAcceptConnectPort(), ZwClose(), and ZwReplyWaitReceivePort().
Referenced by SeRmInitPhase1().
BOOLEAN SepRmCommandServerThreadInit (VOID)
Definition at line 517 of file rmmain.c.
References _PORT_MESSAGE::ClientId, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, FALSE, _LARGE_INTEGER::HighPart, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, InitializeObjectAttributes, KdPrint, _PORT_VIEW::Length, _REMOTE_PORT_VIEW::Length, _LARGE_INTEGER::LowPart, _SEP_RM_STATE::LsaCommandPortHandle, _SEP_RM_STATE::LsaCommandPortMemoryDelta, _SEP_RM_STATE::LsaCommandPortSectionHandle, _SEP_RM_STATE::LsaCommandPortSectionSize, _SEP_RM_STATE::LsaInitEventHandle, _SEP_RM_STATE::LsaViewPortMemory, NT_SUCCESS, NtClose(), NULL, ObReferenceObject, PAGE_READWRITE, PAGE_SIZE, PAGED_CODE, PROCESS_VM_OPERATION, PROCESS_VM_WRITE, PsGetCurrentProcess(), _SEP_RM_STATE::RmCommandPortHandle, _SEP_RM_STATE::RmCommandServerPortHandle, _SEP_RM_STATE::RmViewPortMemory, RtlInitUnicodeString(), _PORT_MESSAGE::s1, SEC_COMMIT, SECTION_ALL_ACCESS, _PORT_VIEW::SectionHandle, _PORT_VIEW::SectionOffset, SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, SepLsaHandle, SepRmLsaCallProcess, SepRmState, Status, TRUE, _PORT_MESSAGE::u1, _PORT_VIEW::ViewBase, _PORT_VIEW::ViewRemoteBase, _PORT_VIEW::ViewSize, ZwAcceptConnectPort(), ZwClose(), ZwCompleteConnectPort(), ZwConnectPort(), ZwCreateSection(), ZwListenPort(), ZwOpenProcess(), and ZwWaitForSingleObject().
Referenced by SepRmCommandServerThread().
BOOLEAN SepRmInitPhase0 ()
Definition at line 1165 of file rmmain.c.
References PAGED_CODE, and SepRmDbInitialization().
Referenced by SepInitializationPhase0().
BOOLEAN SeRmInitPhase1 ()
Definition at line 53 of file rmmain.c.
References ACL_REVISION2, _SECURITY_DESCRIPTOR::Dacl, EVENT_MODIFY_STATE, ExAllocatePoolWithTag, ExFreePool(), FALSE, GENERIC_ALL, InitializeObjectAttributes, KdPrint, _SEP_RM_STATE::LsaInitEventHandle, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, PsCreateSystemThread(), _SEP_RM_STATE::RmCommandServerPortHandle, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlInitUnicodeString(), SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SeLocalSystemSid, SepAdtInitializeAuditingOptions(), SepAdtInitializeCrashOnFail(), SepAdtInitializePrivilegeAuditing(), SepRmCommandServerThread(), SepRmState, _SEP_RM_STATE::SepRmThreadHandle, Status, THREAD_GET_CONTEXT, THREAD_SET_CONTEXT, THREAD_SET_INFORMATION, TRUE, ZwClose(), ZwCreateEvent(), and ZwCreatePort().
Variable Documentation
const SEP_RM_COMMAND_WORKER SepRmCommandDispatch[]
Initial value:
= {
                          NULL,
                          SepRmSetAuditEventWrkr,
                          SepRmCreateLogonSessionWrkr,
                          SepRmDeleteLogonSessionWrkr
                          }
Definition at line 44 of file rmmain.c.
Referenced by SepRmCommandServerThread().