Windows Research Kernel v1.2: C:/Windows Research Kernel/se/sep.h File Reference
sep.h File Reference
#include "ntos.h"
#include <ntrmlsa.h>
#include "seopaque.h"
Data Structures
struct _SEP_LOGON_SESSION_REFERENCES
struct _SEP_LSA_WORK_ITEM
struct _SEP_WORK_ITEM
Macros
#define EffectiveToken(SubjectSecurityContext)
#define ExAllocatePool(a, b) ExAllocatePoolWithTag(a,b,' eS')
#define ExAllocatePoolWithQuota(a, b) ExAllocatePoolWithQuotaTag(a,b,' eS')
#define IF_SE_GLOBAL(FlagName) if (FALSE)
#define IsInRange(item, min_val, max_val) (((item) >= min_val) && ((item) <= max_val))
#define IsValidAuditId(a) (IsInRange((a), SE_ADT_MIN_AUDIT_ID, SE_ADT_MAX_AUDIT_ID))
#define IsValidCategoryId(c) (IsInRange((c), SE_ADT_MIN_CATEGORY_ID, SE_ADT_MAX_CATEGORY_ID))
#define IsValidElementCount(Count, STRUCTURE)
#define IsValidObjectTypeListCount(count)
#define IsValidParameterCount(p) (IsInRange((p), 2, SE_MAX_AUDIT_PARAMETERS))
#define IsValidPrivilegeCount(count)
#define SE_DIAG_SD_TRACKING ((ULONG) 0x00000001L)
#define SeDiagPrint(FlagName, _Text_) ;
#define SEP_MAX_GROUP_COUNT 4096
#define SEP_MAX_OBJECT_TYPE_LIST_COUNT 4096
#define SEP_MAX_PRIVILEGE_COUNT (SE_MAX_WELL_KNOWN_PRIVILEGE-SE_MIN_WELL_KNOWN_PRIVILEGE+32)
#define SEP_SERVICES_FILTER 0x1
#define SepAreFlagsSet(Mask, Bits)
#define SepBadImpersonationLevel(IL, SIR)
#define SepClearFlags(Mask, Bits)
#define SepLockLsaQueue()
#define SepPrivilegeSetSize(PrivilegeSet)
#define SepSetFlags(Mask, Bits)
#define SepTokenAuthenticationId(Token) (((PTOKEN)(Token))->AuthenticationId)
#define SepTokenUserSid(Token) ((PTOKEN)(Token))->UserAndGroups->Sid
#define SepUnlockLsaQueue()
#define SepWorkListEmpty() (IsListEmpty (&SepLsaQueue))
#define SepWorkListHead() ((PSEP_LSA_WORK_ITEM)(&SepLsaQueue)->Flink)
#define TOKEN_LEAK_MONITOR 0
Typedefs
typedef struct _SEP_LOGON_SESSION_REFERENCES * PSEP_LOGON_SESSION_REFERENCES
typedef struct _SEP_LSA_WORK_ITEM * PSEP_LSA_WORK_ITEM
typedef enum _SEP_LSA_WORK_ITEM_TAG * PSEP_LSA_WORK_ITEM_TAG
typedef VOID(* PSEP_LSA_WORKER_CLEANUP_ROUTINE) (IN PVOID Parameter)
typedef struct _SEP_WORK_ITEM * PSEP_WORK_ITEM
typedef struct _SEP_LOGON_SESSION_REFERENCES SEP_LOGON_SESSION_REFERENCES
typedef struct _SEP_LSA_WORK_ITEM SEP_LSA_WORK_ITEM
typedef enum _SEP_LSA_WORK_ITEM_TAG SEP_LSA_WORK_ITEM_TAG
typedef struct _SEP_WORK_ITEM SEP_WORK_ITEM
Enumerations
enum _SEP_LSA_WORK_ITEM_TAG { SepDeleteLogon, SepAuditRecord }
Functions
BOOLEAN SepAdtAuditThisEventWithContext (IN POLICY_AUDIT_EVENT_TYPE Category, IN BOOLEAN AccessGranted, IN BOOLEAN AccessDenied, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext OPTIONAL)
VOID SepAdtGenerateDiscardAudit (VOID)
NTSTATUS SepAdtInitializeCrashOnFail (VOID)
BOOLEAN SepAdtInitializePrivilegeAuditing (VOID)
BOOLEAN SepAdtValidateAuditBounds (ULONG Upper, ULONG Lower)
VOID SepAssemblePrivileges (IN ULONG PrivilegeCount, IN BOOLEAN SystemSecurity, IN BOOLEAN WriteOwner, OUT PPRIVILEGE_SET *Privileges)
BOOLEAN SepAuditAlarm (IN PUNICODE_STRING SubsystemName, IN PVOID HandleId, IN PUNICODE_STRING ObjectTypeName, IN PUNICODE_STRING ObjectName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ACCESS_MASK DesiredAccess, IN BOOLEAN ObjectCreation, IN ACCESS_MASK GrantedAccess, OUT PBOOLEAN GenerateOnClose)
VOID SepAuditAssignPrimaryToken (IN PEPROCESS Process, IN PACCESS_TOKEN NewAccessToken)
BOOLEAN SepCheckAcl (IN PACL Acl, IN ULONG Length)
VOID SepConcatenatePrivileges (IN PPRIVILEGE_SET TargetPrivilegeSet, IN ULONG TargetBufferSize, IN PPRIVILEGE_SET SourcePrivilegeSet)
NTSTATUS SepCopyProxyData (OUT PSECURITY_TOKEN_PROXY_DATA *DestProxyData, IN PSECURITY_TOKEN_PROXY_DATA SourceProxyData)
VOID SepCopyString (IN PUNICODE_STRING SourceString, OUT PUNICODE_STRING *DestString)
NTSTATUS SepCreateToken (OUT PHANDLE TokenHandle, IN KPROCESSOR_MODE RequestorMode, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN TOKEN_TYPE TokenType, IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel OPTIONAL, IN PLUID AuthenticationId, IN PLARGE_INTEGER ExpirationTime, IN PSID_AND_ATTRIBUTES User, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES Groups, IN ULONG GroupsLength, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES Privileges, IN PSID Owner OPTIONAL, IN PSID PrimaryGroup, IN PACL DefaultDacl OPTIONAL, IN PTOKEN_SOURCE TokenSource, IN BOOLEAN SystemToken, IN PSECURITY_TOKEN_PROXY_DATA ProxyData OPTIONAL, IN PSECURITY_TOKEN_AUDIT_DATA AuditData OPTIONAL)
PSEP_LSA_WORK_ITEM SepDequeueWorkItem (VOID)
VOID SepDeReferenceLogonSession (IN PLUID LogonId)
BOOLEAN SepDevelopmentTest (VOID)
VOID SepExamineSacl (IN PACL Sacl, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, OUT PBOOLEAN GenerateAudit, OUT PBOOLEAN GenerateAlarm)
BOOLEAN SepFilterPrivilegeAudits (IN ULONG Flags, IN PPRIVILEGE_SET PrivilegeSet)
VOID SepFreeProxyData (IN PSECURITY_TOKEN_PROXY_DATA ProxyData)
VOID SepFreeSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SepGetDefaultsSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, OUT PSID *Owner, OUT PSID *Group, OUT PSID *ServerOwner, OUT PSID *ServerGroup, OUT PACL *Dacl)
BOOLEAN SepIdAssignableAsGroup (IN PACCESS_TOKEN Token, IN PSID Group)
BOOLEAN SepInitializationPhase0 (VOID)
BOOLEAN SepInitializationPhase1 (VOID)
BOOLEAN SepInitializeWorkList (VOID)
VOID SepLockSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext)
NTSTATUS SepProbeAndCaptureQosData (IN PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
POBJECT_NAME_INFORMATION SepQueryNameString (IN PVOID Object)
PUNICODE_STRING SepQueryTypeString (IN PVOID Object)
BOOLEAN SepQueueWorkItem (IN PSEP_LSA_WORK_ITEM LsaWorkItem, IN BOOLEAN ForceQueue)
NTSTATUS SepReferenceLogonSession (IN PLUID LogonId, OUT PSEP_LOGON_SESSION_REFERENCES *ReturnSession)
NTSTATUS SepRmCallLsa (PSEP_WORK_ITEM SepWorkItem)
BOOLEAN SepRmInitPhase0 ()
BOOLEAN SepSidInToken (IN PACCESS_TOKEN Token, IN PSID PrincipalSelfSid, IN PSID Sid, IN BOOLEAN DenyAce)
BOOLEAN SepSinglePrivilegeCheck (LUID DesiredPrivilege, IN PACCESS_TOKEN EffectiveToken, IN KPROCESSOR_MODE PreviousMode)
BOOLEAN SepTokenIsOwner (IN PACCESS_TOKEN Token, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN TokenLocked)
BOOLEAN SepValidOwnerSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, IN PSID Owner, IN BOOLEAN ServerObject)
BOOLEAN SepVariableInitialization (VOID)
Variables
SEP_WORK_ITEM SepExWorkItem
HANDLE SepLsaHandle
LIST_ENTRY SepLsaQueue
ULONG SepLsaQueueLength
ERESOURCE SepLsaQueueLock
LONG SepTokenPolicyCounter [POLICY_AUDIT_EVENT_TYPE_COUNT]
Macro Definition Documentation
#define EffectiveToken (SubjectSecurityContext)
Value:
(\
                 (SubjectSecurityContext)->ClientToken ?                      \
                 (SubjectSecurityContext)->ClientToken :                      \
                 (SubjectSecurityContext)->PrimaryToken                       \
                 )                                                            \
Definition at line 161 of file sep.h.
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), SeAccessCheck(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditingFileOrGlobalEvents(), SeAuditSystemTimeChange(), SeCloseObjectAuditAlarm(), SeCreateAccessStateEx(), SeDeleteObjectAuditAlarm(), SeDetailedAuditingWithToken(), SeObjectReferenceAuditAlarm(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtAuditThisEventWithContext(), SepAuditAssignPrimaryToken(), SepGetDefaultsSubjectContext(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), SePrivilegePolicyCheck(), SepValidOwnerSubjectContext(), and SeReportSecurityEvent().
#define ExAllocatePool (a, b) ExAllocatePoolWithTag(a,b,' eS')
Definition at line 338 of file sep.h.
Referenced by CmGetSystemDriverList(), CmpAddToHiveFileList(), CmpBuildSecurityCellMappingArray(), CmpCanGrowSystemHive(), CmpCheckKeyAccess(), CmpCloneControlSet(), CmpCmdRenameHive(), CmpCompressKeyWorker(), CmpCopyKeyPartial(), CmpCopySyncTree(), CmpCopySyncTree2(), CmpDiskFullWarning(), CmpDoQueueLateUnloadWorker(), CmpFileWrite(), CmpGetHiveName(), CmpGetSymbolicLink(), CmpHiveRootSecurityDescriptor(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpInitializeSystemHive(), CmpLoadHiveVolatile(), CmpMarkIndexDirty(), CmpMergeKeyValues(), CmpNotifyChangeKey(), CmpOpenHiveFiles(), CmpRaiseSelfHealWarning(), CmpRemoveSubKey(), CmpSaveBootControlSet(), CmpShiftAllCells2(), CmpSyncKeyValues(), CmpUpdateSystemHiveHysteresis(), HvpDoWriteHive(), HvpReadFileImageAndBuildMap(), HvpWriteLog(), HvTrackCellRef(), IoAllocateWorkItem(), IoCreateDriver(), IopBuildFullDriverPath(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopErrorLogQueueRequest(), IopErrorLogThread(), IopGetDriverNameFromKeyNode(), IopGetRegistryKeyInformation(), IopGetRegistryValue(), IopInitializeBootLogging(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopParseDevice(), IopRaiseHardError(), IopSafebootDriverLoad(), IopSendMessageToTrackService(), IopSetEaOrQuotaInformationFile(), IoVolumeDeviceToDosName(), NtCompactKeys(), NtFlushBuffersFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), ObpGetDosDevicesProtection(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepCreateImpersonationTokenDacl(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), SepInitializationPhase1(), SepProbeAndCaptureQosData(), and SeQueryInformationToken().
#define ExAllocatePoolWithQuota (a, b) ExAllocatePoolWithQuotaTag(a,b,' eS')
Definition at line 341 of file sep.h.
Referenced by BuildQueryDirectoryIrp(), CmpSaveKeyByFileCopy(), IopSetEaOrQuotaInformationFile(), IopTrackLink(), IopUnloadDriver(), IopXxxControlFile(), NtLoadDriver(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
#define IF_SE_GLOBAL (FlagName) if (FALSE)
Definition at line 75 of file sep.h.
#define IsInRange (item, min_val, max_val) (((item) >= min_val) && ((item) <= max_val))
Definition at line 258 of file sep.h.
#define IsValidAuditId (a) (IsInRange((a), SE_ADT_MIN_AUDIT_ID, SE_ADT_MAX_AUDIT_ID))
Definition at line 271 of file sep.h.
#define IsValidCategoryId (c) (IsInRange((c), SE_ADT_MIN_CATEGORY_ID, SE_ADT_MAX_CATEGORY_ID))
Definition at line 264 of file sep.h.
#define IsValidElementCount (Count, STRUCTURE)
Value:
(Count < ((ULONG_PTR) ((PUCHAR) ((PUCHAR) (LONG_PTR)(LONG)0xFFFFFFFF - (PUCHAR) MM_SYSTEM_RANGE_START) + 1) \
        / sizeof( STRUCTURE ) ) )
Definition at line 238 of file sep.h.
Referenced by NtPrivilegeCheck(), SeAccessCheckByType(), and SeCaptureObjectTypeList().
#define IsValidObjectTypeListCount (count)
Value:
((count == 0) || \
           (count <= SEP_MAX_OBJECT_TYPE_LIST_COUNT))
Definition at line 254 of file sep.h.
Referenced by SepAccessCheckAndAuditAlarm().
#define IsValidParameterCount (p) (IsInRange((p), 2, SE_MAX_AUDIT_PARAMETERS))
Definition at line 280 of file sep.h.
Referenced by SepAdtMarshallAuditRecord().
#define IsValidPrivilegeCount (count)
Value:
((count == 0) || \
                                        ((count > 0) && \
                                         (count <= SEP_MAX_PRIVILEGE_COUNT)))
Definition at line 245 of file sep.h.
Referenced by NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), SeAuditHandleCreation(), and SePrivilegedServiceAuditAlarm().
#define SE_DIAG_SD_TRACKING ((ULONG) 0x00000001L)
Definition at line 98 of file sep.h.
#define SeDiagPrint (FlagName, _Text_) ;
Definition at line 81 of file sep.h.
#define SEP_MAX_GROUP_COUNT 4096
Definition at line 293 of file sep.h.
Referenced by SeCaptureSidAndAttributesArray().
#define SEP_MAX_OBJECT_TYPE_LIST_COUNT 4096
Definition at line 252 of file sep.h.
#define SEP_MAX_PRIVILEGE_COUNT (SE_MAX_WELL_KNOWN_PRIVILEGE-SE_MIN_WELL_KNOWN_PRIVILEGE+32)
Definition at line 243 of file sep.h.
Referenced by SeCaptureLuidAndAttributesArray().
#define SEP_SERVICES_FILTER 0x1
Definition at line 686 of file sep.h.
Referenced by SepFilterPrivilegeAudits(), and SePrivilegedServiceAuditAlarm().
#define SepAreFlagsSet (Mask, Bits)
Value:
(\
            ((Mask) & ( Bits )) == ( Bits )                                    \
            )
Definition at line 113 of file sep.h.
#define SepBadImpersonationLevel (IL, SIR)
Value:
((\
            ((IL) == SecurityAnonymous) || ((IL) == SecurityIdentification) || \
            ( (SIR) && ((IL) != SecurityDelegation) )                          \
            ) ? TRUE : FALSE )
Definition at line 221 of file sep.h.
Referenced by SepCreateClientSecurity().
#define SepClearFlags (Mask, Bits)
Value:
(\
            ( Mask ) &= ~( Bits )                                              \
            )
Definition at line 131 of file sep.h.
#define SepLockLsaQueue ()
Value:
KeEnterCriticalRegion();                           \
                           ExAcquireResourceExclusiveLite(&SepLsaQueueLock, TRUE)
Definition at line 327 of file sep.h.
Referenced by SepDequeueWorkItem(), SepQueueWorkItem(), and SepRmCommandServerThread().
#define SepPrivilegeSetSize (PrivilegeSet)
Value:
((PrivilegeSet) == NULL ? 0 :                                       \
        ((( PrivilegeSet )->PrivilegeCount > 0)                                \
         ?                                                                     \
         ((ULONG)sizeof(PRIVILEGE_SET) +                                       \
           (                                                                   \
             (( PrivilegeSet )->PrivilegeCount  -  ANYSIZE_ARRAY) *            \
             (ULONG)sizeof(LUID_AND_ATTRIBUTES)                                \
           )                                                                   \
         )                                                                     \
         : ((ULONG)sizeof(PRIVILEGE_SET) - (ULONG)sizeof(LUID_AND_ATTRIBUTES)) \
        ))
Definition at line 143 of file sep.h.
Referenced by SeAccessCheckByType(), SeAppendPrivileges(), SepConcatenatePrivileges(), and SeSetAuditParameter().
#define SepSetFlags (Mask, Bits)
Value:
(\
            ( Mask ) |= ( Bits )                                               \
            )
Definition at line 122 of file sep.h.
#define SepTokenAuthenticationId (Token) (((PTOKEN)(Token))->AuthenticationId)
Definition at line 179 of file sep.h.
Referenced by SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SepAuditAssignPrimaryToken().
#define SepTokenUserSid (Token) ((PTOKEN)(Token))->UserAndGroups->Sid
Definition at line 172 of file sep.h.
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCloseObjectAuditAlarm(), SeDeleteObjectAuditAlarm(), SeOperationAuditAlarm(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), SePrivilegedServiceAuditAlarm(), and SeReportSecurityEvent().
#define SepUnlockLsaQueue ()
Value:
ExReleaseResourceLite(&SepLsaQueueLock);              \
                            KeLeaveCriticalRegion()
Definition at line 330 of file sep.h.
Referenced by SepDequeueWorkItem(), SepQueueWorkItem(), and SepRmCommandServerThread().
#define SepWorkListEmpty () (IsListEmpty (&SepLsaQueue))
Definition at line 335 of file sep.h.
Referenced by SepRmCommandServerThread().
#define SepWorkListHead () ((PSEP_LSA_WORK_ITEM)(&SepLsaQueue)->Flink)
Definition at line 333 of file sep.h.
Referenced by SepRmCallLsa().
#define TOKEN_LEAK_MONITOR 0
Definition at line 497 of file sep.h.
Typedef Documentation
typedef struct _SEP_LOGON_SESSION_REFERENCES * PSEP_LOGON_SESSION_REFERENCES
typedef struct _SEP_LSA_WORK_ITEM * PSEP_LSA_WORK_ITEM
typedef enum _SEP_LSA_WORK_ITEM_TAG * PSEP_LSA_WORK_ITEM_TAG
typedef VOID(* PSEP_LSA_WORKER_CLEANUP_ROUTINE) (IN PVOID Parameter)
Definition at line 346 of file sep.h.
typedef struct _SEP_WORK_ITEM * PSEP_WORK_ITEM
typedef struct _SEP_LOGON_SESSION_REFERENCES SEP_LOGON_SESSION_REFERENCES
typedef struct _SEP_LSA_WORK_ITEM SEP_LSA_WORK_ITEM
typedef enum _SEP_LSA_WORK_ITEM_TAG SEP_LSA_WORK_ITEM_TAG
typedef struct _SEP_WORK_ITEM SEP_WORK_ITEM
Enumeration Type Documentation
enum _SEP_LSA_WORK_ITEM_TAG
Enumerator
SepDeleteLogon
SepAuditRecord
Definition at line 351 of file sep.h.
Function Documentation
BOOLEAN SepAdtAuditThisEventWithContext (IN POLICY_AUDIT_EVENT_TYPE Category, IN BOOLEAN AccessGranted, IN BOOLEAN AccessDenied, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext OPTIONAL)
Definition at line 282 of file sepaudit.c.
References _SEP_AUDIT_POLICY_CATEGORIES::AccountLogon, _SEP_AUDIT_POLICY_CATEGORIES::AccountManagement, ARGUMENT_PRESENT, ASSERT, AuditCategoryAccountLogon, AuditCategoryAccountManagement, AuditCategoryDetailedTracking, AuditCategoryDirectoryServiceAccess, AuditCategoryLogon, AuditCategoryObjectAccess, AuditCategoryPolicyChange, AuditCategoryPrivilegeUse, AuditCategorySystem, _TOKEN::AuditPolicy, _SEP_AUDIT_POLICY_CATEGORIES::DetailedTracking, _SEP_AUDIT_POLICY_CATEGORIES::DirectoryServiceAccess, EffectiveToken, FALSE, _SEP_AUDIT_POLICY_CATEGORIES::Logon, NULL, _SEP_AUDIT_POLICY_CATEGORIES::ObjectAccess, PAGED_CODE, _SEP_AUDIT_POLICY_CATEGORIES::PolicyChange, _SEP_AUDIT_POLICY::PolicyElements, _SEP_AUDIT_POLICY_CATEGORIES::PrivilegeUse, SeAuditingState, SeCaptureSubjectContext(), SepAuditFailed(), SepTokenPolicyCounter, SeReleaseSubjectContext(), STATUS_NO_TOKEN, _SEP_AUDIT_POLICY_CATEGORIES::System, TOKEN_AUDIT_FAILURE_EXCLUDE, TOKEN_AUDIT_FAILURE_INCLUDE, TOKEN_AUDIT_SUCCESS_EXCLUDE, TOKEN_AUDIT_SUCCESS_INCLUDE, and TRUE.
Referenced by NtOpenObjectAuditAlarm(), SeAuditingFileEventsWithContext(), SeAuditingFileOrGlobalEvents(), SeAuditingHardLinkEventsWithContext(), SeAuditLPCInvalidUse(), SeAuditSystemTimeChange(), SeInitializeProcessAuditName(), SeObjectReferenceAuditAlarm(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SeReportSecurityEvent().
VOID SepAdtGenerateDiscardAudit (VOID)
Definition at line 2940 of file sepaudit.c.
References ASSERT, EVENTLOG_AUDIT_SUCCESS, PAGED_CODE, RtlZeroMemory, SE_AUDITID_AUDITS_DISCARDED, SE_CATEGID_SYSTEM, SeAdtParmTypeNone, SeLocalSystemSid, SepAdtCountEventsDiscarded, SepAdtLogAuditRecord(), SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, and SeSubsystemName.
Referenced by SepQueueWorkItem().
NTSTATUS SepAdtInitializeCrashOnFail (VOID)
Definition at line 150 of file adtinit.c.
References CRASH_ON_AUDIT_FAIL_VALUE, FALSE, LSAP_CRASH_ON_AUDIT_FAIL, NT_SUCCESS, PAGED_CODE, SepCrashOnAuditFail, SepRegQueryDwordValue(), Status, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, and TRUE.
Referenced by SeRmInitPhase1().
BOOLEAN SepAdtInitializePrivilegeAuditing (VOID)
Definition at line 209 of file adtinit.c.
References ASSERT, _KEY_VALUE_PARTIAL_INFORMATION::Data, FALSE, FULL_PRIVILEGE_AUDITING, InitializeObjectAttributes, KEY_QUERY_VALUE, KEY_SET_VALUE, KeyName, KeyValuePartialInformation, NT_SUCCESS, NtClose(), NtOpenKey(), NtQueryValueKey(), NULL, OBJ_CASE_INSENSITIVE, PAGED_CODE, RtlInitUnicodeString(), SepInitializePrivilegeFilter(), Status, and STATUS_OBJECT_NAME_NOT_FOUND.
Referenced by SeRmInitPhase1().
BOOLEAN SepAdtValidateAuditBounds (ULONG Upper, ULONG Lower)
Definition at line 34 of file adtinit.c.
References FALSE, PAGED_CODE, and TRUE.
Referenced by SepAdtInitializeBounds().
VOID SepAssemblePrivileges (IN ULONG PrivilegeCount, IN BOOLEAN SystemSecurity, IN BOOLEAN WriteOwner, OUT PPRIVILEGE_SET * Privileges)
Definition at line 1391 of file seglobal.c.
References ARGUMENT_PRESENT, ASSERT, DoublePrivilegeSetSize, ExAllocatePoolWithTag, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, SepDoublePrivilegeSet, SepSystemSecurityPrivilegeSet, SepTakeOwnershipPrivilegeSet, and SinglePrivilegeSetSize.
Referenced by SepAccessCheck().
BOOLEAN SepAuditAlarm (IN PUNICODE_STRING SubsystemName, IN PVOID HandleId, IN PUNICODE_STRING ObjectTypeName, IN PUNICODE_STRING ObjectName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ACCESS_MASK DesiredAccess, IN BOOLEAN ObjectCreation, IN ACCESS_MASK GrantedAccess, OUT PBOOLEAN GenerateOnClose)
VOID SepAuditAssignPrimaryToken (IN PEPROCESS Process, IN PACCESS_TOKEN NewAccessToken)
Definition at line 3319 of file sepaudit.c.
References ASSERT, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_ASSIGN_TOKEN, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepAuditFailed(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, STATUS_NO_TOKEN, and STATUS_SUCCESS.
Referenced by SeAssignPrimaryToken(), and SeExchangePrimaryToken().
BOOLEAN SepCheckAcl (IN PACL Acl, IN ULONG Length)
Definition at line 32 of file sep.c.
References FALSE, and RtlValidAcl().
Referenced by SeCaptureAcl(), and SeCaptureSecurityDescriptor().
VOID SepConcatenatePrivileges (IN PPRIVILEGE_SET TargetPrivilegeSet, IN ULONG TargetBufferSize, IN PPRIVILEGE_SET SourcePrivilegeSet)
Definition at line 432 of file seastate.c.
References ASSERT, PAGED_CODE, RtlMoveMemory, SEP_PRIVILEGE_SET_HEADER_SIZE, and SepPrivilegeSetSize.
Referenced by SeAppendPrivileges().
NTSTATUS SepCopyProxyData (OUT PSECURITY_TOKEN_PROXY_DATA * DestProxyData, IN PSECURITY_TOKEN_PROXY_DATA SourceProxyData)
Definition at line 691 of file capture.c.
References ExAllocatePoolWithTag, NULL, PAGED_CODE, PagedPool, PtrAlignSize, RtlCopyUnicodeString(), STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by SepCreateToken(), SepDuplicateToken(), SepFilterToken(), and SepProbeAndCaptureQosData().
VOID SepCopyString (IN PUNICODE_STRING SourceString, OUT PUNICODE_STRING * DestString)
NTSTATUS SepCreateToken (OUT PHANDLE TokenHandle, IN KPROCESSOR_MODE RequestorMode, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN TOKEN_TYPE TokenType, IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel OPTIONAL, IN PLUID AuthenticationId, IN PLARGE_INTEGER ExpirationTime, IN PSID_AND_ATTRIBUTES User, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES Groups, IN ULONG GroupsLength, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES Privileges, IN PSID Owner OPTIONAL, IN PSID PrimaryGroup, IN PACL DefaultDacl OPTIONAL, IN PTOKEN_SOURCE TokenSource, IN BOOLEAN SystemToken, IN PSECURITY_TOKEN_PROXY_DATA ProxyData OPTIONAL, IN PSECURITY_TOKEN_AUDIT_DATA AuditData OPTIONAL)
Definition at line 2500 of file token.c.
References ALIGN_UP, ARGUMENT_PRESENT, ASSERT, _TOKEN::AuditData, _TOKEN::AuditPolicy, _TOKEN::AuthenticationId, _ETHREAD::Cid, DbgBreakPoint(), DbgPrint(), _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, DISPATCH_LEVEL, _TOKEN::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN::DynamicPart, ExAllocateLocallyUniqueId(), ExAllocatePool, ExAllocatePoolWithTag, ExFastRefObjectNull(), ExFreePool(), ExInitializeResourceLite(), _TOKEN::ExpirationTime, FALSE, FIELD_OFFSET, _OBJECT_TYPE_INITIALIZER::GenericMapping, _TOKEN::ImpersonationLevel, InterlockedIncrement, KeGetCurrentIrql(), KeGetPreviousMode, _TOKEN::LogonSession, LongAlignSize, min, _TOKEN::ModifiedId, NonPagedPool, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), _TOKEN::OriginatingLogonSession, _SEP_AUDIT_POLICY::Overlay, PAGED_CODE, PagedPool, _TOKEN::ParentTokenId, _TOKEN::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN::Privileges, _TOKEN::ProxyData, PsGetCurrentProcess(), PsGetCurrentThread(), _TOKEN::RestrictedSidCount, _TOKEN::RestrictedSids, RtlConvertLongToLuid(), RtlCopyMemory, RtlCopySid(), RtlCopySidAndAttributesArray(), RtlEqualLuid, RtlEqualSid(), RtlLengthRequiredSid(), RtlWalkFrameChain(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SE_GROUP_OWNER, SE_PRIVILEGE_ENABLED, SeAliasAdminsSid, SeChangeNotifyPrivilege, SeCreateAccessState(), SeCreateTokenPrivilege, SeDeleteAccessState(), SeImpersonatePrivilege, SepArrayGroupAttributes, SepCopyProxyData(), SepReferenceLogonSession(), SeSinglePrivilegeCheck(), _TOKEN::SessionId, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_OWNER, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, TOKEN_DEFAULT_DYNAMIC_CHARGE, TOKEN_HAS_ADMIN_GROUP, TOKEN_HAS_IMPERSONATE_PRIVILEGE, TOKEN_HAS_TRAVERSE_PRIVILEGE, TOKEN_SESSION_NOT_REFERENCED, _TOKEN::TokenFlags, _TOKEN::TokenId, _TOKEN::TokenInUse, _TOKEN::TokenLock, _TOKEN::TokenSource, _TOKEN::TokenType, TokenType, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _EPROCESS::UniqueProcessId, _CLIENT_ID::UniqueThread, _TOKEN::UserAndGroupCount, _TOKEN::UserAndGroups, UserMode, _TOKEN::VariableLength, and _TOKEN::VariablePart.
Referenced by NtCreateToken(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), and SeMakeSystemToken().
PSEP_LSA_WORK_ITEM SepDequeueWorkItem (VOID)
Definition at line 699 of file adtlog.c.
References ExFreePool(), FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeSetEvent(), _SEP_LSA_WORK_ITEM::List, NULL, PAGED_CODE, RemoveHeadList(), SepAdtCurrentListLength, SepAdtLsaDeadEvent, SepLockLsaQueue, SepLsaQueue, and SepUnlockLsaQueue.
Referenced by SepRmCallLsa().
VOID SepDeReferenceLogonSession (IN PLUID LogonId)
Definition at line 637 of file rmlogon.c.
References DEREF_UNKNOWN_LOGON_SESSION, ExFreePool(), _SEP_LOGON_SESSION_REFERENCES::Flags, InterlockedDecrement, KeBugCheckEx(), _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, ObfDereferenceDeviceMap(), PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, SEP_TERMINATION_NOTIFY, SepCleanupLUIDDeviceMapDirectory(), SepInformFileSystemsOfDeletedLogon(), SepInformLsaOfDeletedLogon(), SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, and SepRmReleaseDbWriteLock.
Referenced by SepDeReferenceLogonSessionDirect().
BOOLEAN SepDevelopmentTest (VOID)
Referenced by SepInitializationPhase1().
VOID SepExamineSacl (IN PACL Sacl, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, OUT PBOOLEAN GenerateAudit, OUT PBOOLEAN GenerateAlarm)
Definition at line 3702 of file seaudit.c.
References FAILED_ACCESS_ACE_FLAG, FALSE, FirstAce, INHERIT_ONLY_ACE, MAXIMUM_ALLOWED, NextAce, NULL, PAGED_CODE, RtlEqualMemory, SeAnonymousLogonSid, SeLengthSid, SepSidInToken(), SeWorldSid, SUCCESSFUL_ACCESS_ACE_FLAG, SYSTEM_AUDIT_ACE_TYPE, and TRUE.
Referenced by NtOpenObjectAuditAlarm(), SeObjectReferenceAuditAlarm(), SeOpenObjectAuditAlarm(), and SeOpenObjectForDeleteAuditAlarm().
BOOLEAN SepFilterPrivilegeAudits (IN ULONG Flags, IN PPRIVILEGE_SET PrivilegeSet)
Definition at line 4453 of file seaudit.c.
References ARGUMENT_PRESENT, FALSE, NULL, PAGED_CODE, RtlEqualLuid, SEP_SERVICES_FILTER, SepFilterPrivileges, SepServicesFilterPrivileges, and TRUE.
Referenced by SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SePrivilegedServiceAuditAlarm().
VOID SepFreeProxyData (IN PSECURITY_TOKEN_PROXY_DATA ProxyData)
Definition at line 739 of file capture.c.
References ExFreePool(), NULL, and PAGED_CODE.
Referenced by SeCaptureSecurityQos(), SeFreeCapturedSecurityQos(), SepDuplicateToken(), SepFilterToken(), SepProbeAndCaptureQosData(), and SepTokenDeleteMethod().
VOID SepFreeSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SepGetDefaultsSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, OUT PSID * Owner, OUT PSID * Group, OUT PSID * ServerOwner, OUT PSID * ServerGroup, OUT PACL * Dacl)
Definition at line 320 of file subject.c.
References ARGUMENT_PRESENT, _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, EffectiveToken, PAGED_CODE, _TOKEN::PrimaryGroup, _SID_AND_ATTRIBUTES::Sid, and _TOKEN::UserAndGroups.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
BOOLEAN SepIdAssignableAsGroup (IN PACCESS_TOKEN Token, IN PSID Group)
Definition at line 392 of file subject.c.
References FALSE, Index, NULL, PAGED_CODE, RtlEqualSid(), SepAcquireTokenReadLock, SepReleaseTokenReadLock, _SID_AND_ATTRIBUTES::Sid, and _TOKEN::UserAndGroups.
Referenced by NtSetInformationToken().
BOOLEAN SepInitializationPhase0 (VOID)
Definition at line 79 of file seinit.c.
References ExFastRefObjectNull(), ExLuidInitialization(), FALSE, _ETHREAD::ImpersonationInfo, KdPrint, NULL, ObInitializeFastReference(), PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PsGetCurrentProcess(), PsGetCurrentThread(), SeMakeSystemToken(), SepInitializeWorkList(), SepRmInitPhase0(), SepTokenInitialization(), and SepVariableInitialization().
Referenced by SeInitSystem().
BOOLEAN SepInitializationPhase1 (VOID)
Definition at line 186 of file seinit.c.
References ACL_REVISION, ASSERT, ASSERTMSG, DIRECTORY_ALL_ACCESS, DIRECTORY_QUERY, DIRECTORY_TRAVERSE, ExAllocatePool, ExFastRefGetObject(), ExFreePool(), FALSE, GENERIC_WRITE, InitializeObjectAttributes, NonPagedPool, NotificationEvent, NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NtCreateEvent(), NULL, ObInsertObject(), OBJ_CASE_INSENSITIVE, OBJ_PERMANENT, PAGED_CODE, PsGetCurrentProcess(), READ_CONTROL, RtlAddAccessAllowedAce(), RtlAnsiStringToUnicodeString(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlFreeUnicodeString(), RtlInitString(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SeAnonymousLogonToken, SeAnonymousLogonTokenNoEveryone, SECURITY_DESCRIPTOR_MIN_LENGTH, SECURITY_DESCRIPTOR_REVISION, SeLocalSystemSid, SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SepDevelopmentTest(), SepInitProcessAuditSd(), SePublicDefaultSd, SeWorldSid, Status, and TRUE.
Referenced by SeInitSystem().
BOOLEAN SepInitializeWorkList (VOID)
Definition at line 1472 of file seglobal.c.
References ExInitializeResourceLite(), InitializeListHead(), PAGED_CODE, and TRUE.
Referenced by SepInitializationPhase0().
VOID SepLockSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext)
NTSTATUS SepProbeAndCaptureQosData (IN PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
Definition at line 768 of file capture.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, ExAllocatePool, ExFreePool(), _UNICODE_STRING::Length, _SECURITY_TOKEN_PROXY_DATA::Length, _SECURITY_TOKEN_AUDIT_DATA::Length, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _SECURITY_TOKEN_PROXY_DATA::PathInfo, ProbeForRead, ProbeForReadSmallStructure, SepCopyProxyData(), SepFreeProxyData(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by SeCaptureSecurityQos().
POBJECT_NAME_INFORMATION SepQueryNameString (IN PVOID Object)
Definition at line 2518 of file sepaudit.c.
References ExAllocatePoolWithTag, ExFreePool(), _UNICODE_STRING::Length, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObQueryNameString(), PAGED_CODE, PagedPool, Status, and STATUS_INFO_LENGTH_MISMATCH.
Referenced by SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), and SepAdtObjectReferenceAuditAlarm().
PUNICODE_STRING SepQueryTypeString (IN PVOID Object)
Definition at line 2591 of file sepaudit.c.
References ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, ObQueryTypeName(), PAGED_CODE, PagedPool, Status, and STATUS_INFO_LENGTH_MISMATCH.
Referenced by SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), and SepAdtObjectReferenceAuditAlarm().
BOOLEAN SepQueueWorkItem (IN PSEP_LSA_WORK_ITEM LsaWorkItem, IN BOOLEAN ForceQueue)
Definition at line 570 of file adtlog.c.
References DelayedWorkQueue, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, InsertTailList(), NULL, PAGED_CODE, SepAdtCountEventsDiscarded, SepAdtCurrentListLength, SepAdtDiscardingAudits, SepAdtGenerateDiscardAudit(), SepAdtLsaDeadEvent, SepAdtMaxListLength, SepAdtMinListLength, SepExWorkItem, SepLockLsaQueue, SepLsaQueue, SepRmCallLsa(), SepUnlockLsaQueue, TRUE, and _SEP_WORK_ITEM::WorkItem.
Referenced by SepAdtLogAuditRecord(), and SepInformLsaOfDeletedLogon().
NTSTATUS SepReferenceLogonSession (IN PLUID LogonId, OUT PSEP_LOGON_SESSION_REFERENCES * ReturnSession)
Definition at line 299 of file rmlogon.c.
References InterlockedIncrement, _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_NO_SUCH_LOGON_SESSION, and STATUS_SUCCESS.
Referenced by SepCreateToken(), and SepDuplicateLogonSessionReference().
NTSTATUS SepRmCallLsa (PSEP_WORK_ITEM SepWorkItem)
Definition at line 794 of file rmmain.c.
References ARGUMENT_PRESENT, ASSERT, _SEP_LSA_WORK_ITEM::BaseAddress, _SEP_LSA_WORK_ITEM::CleanupFunction, _SEP_LSA_WORK_ITEM::CleanupParameter, _LSA_COMMAND_MESSAGE::CommandNumber, _SEP_LSA_WORK_ITEM::CommandNumber, _LSA_COMMAND_MESSAGE::CommandParams, _SEP_LSA_WORK_ITEM::CommandParams, _SEP_LSA_WORK_ITEM::CommandParamsLength, _LSA_COMMAND_MESSAGE::CommandParamsMemoryType, _SEP_LSA_WORK_ITEM::CommandParamsMemoryType, ExFreePool(), KdPrint, KeAttachProcess(), KeDetachProcess(), LSA_MAXIMUM_COMMAND_PARAM_SIZE, _SEP_RM_STATE::LsaCommandPortHandle, LsapLogonSessionDeletedCommand, _SEP_RM_STATE::LsaViewPortMemory, MEM_RELEASE, _LSA_COMMAND_MESSAGE::MessageHeader, _LSA_REPLY_MESSAGE::MessageHeader, NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, _LSA_REPLY_MESSAGE::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBufferLength, _LSA_REPLY_MESSAGE::ReturnedStatus, RM_COMMAND_MESSAGE_HEADER_SIZE, _SEP_RM_STATE::RmViewPortMemory, RtlCopyMemory, _PORT_MESSAGE::s1, SEP_RM_LSA_SHARED_MEMORY_SIZE, SepAdtCopyToLsaSharedMemory(), SepDequeueWorkItem(), SepLsaHandle, SepLsaQueueLength, SepRmImmediateMemory, SepRmLsaCallProcess, SepRmLsaCommandPortSharedMemory, SepRmLsaCustomSharedMemory, SepRmPagedPoolMemory, SepRmState, SepRmUnspecifiedMemory, SepWorkListHead, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, UNREFERENCED_PARAMETER, _PORT_MESSAGE::ZeroInit, ZwFreeVirtualMemory(), ZwRequestPort(), and ZwRequestWaitReplyPort().
Referenced by SepQueueWorkItem().
BOOLEAN SepRmInitPhase0 ()
Definition at line 1165 of file rmmain.c.
References PAGED_CODE, and SepRmDbInitialization().
Referenced by SepInitializationPhase0().
BOOLEAN SepSidInToken (IN PACCESS_TOKEN Token, IN PSID PrincipalSelfSid, IN PSID Sid, IN BOOLEAN DenyAce)
Definition at line 747 of file accessck.c.
References _SID_AND_ATTRIBUTES::Attributes, C_ASSERT, FALSE, FIELD_OFFSET, NULL, PAGED_CODE, _SID::Revision, RtlEqualMemory, RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_USE_FOR_DENY_ONLY, SePrincipalSelfSid, _SID_AND_ATTRIBUTES::Sid, TRUE, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
Referenced by SeMaximumAuditMask(), SepExamineSacl(), SepExamineSaclEx(), and SepTokenIsOwner().
BOOLEAN SepSinglePrivilegeCheck (LUID DesiredPrivilege, IN PACCESS_TOKEN EffectiveToken, IN KPROCESSOR_MODE PreviousMode)
Definition at line 144 of file seaudit.c.
References ASSERT, _LUID_AND_ATTRIBUTES::Attributes, _LUID::HighPart, _LUID::LowPart, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, PRIVILEGE_SET_ALL_NECESSARY, SepPrivilegeCheck(), and SeTcbPrivilege.
Referenced by SepAccessCheck(), and SePrivilegePolicyCheck().
BOOLEAN SepTokenIsOwner (IN PACCESS_TOKEN Token, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN TokenLocked)
Definition at line 3712 of file accessck.c.
References ASSERT, FALSE, NULL, PAGED_CODE, RtlpOwnerAddrSecurityDescriptor, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SepSidInToken(), SepSidInTokenEx(), TOKEN_IS_RESTRICTED, _TOKEN::TokenFlags, and TRUE.
Referenced by SeAccessCheck(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SepValidOwnerSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, IN PSID Owner, IN BOOLEAN ServerObject)
Definition at line 467 of file subject.c.
References ARGUMENT_PRESENT, EffectiveToken, exit(), FALSE, _TOKEN::ImpersonationLevel, Index, NULL, PAGED_CODE, RtlEqualSid(), SecurityImpersonation, SepAcquireTokenReadLock, SepIdAssignableAsOwner(), SepReleaseTokenReadLock, SeRestorePrivilege, SeSinglePrivilegeCheck(), _SID_AND_ATTRIBUTES::Sid, TokenImpersonation, _TOKEN::TokenType, TRUE, _TOKEN::UserAndGroups, and UserMode.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
BOOLEAN SepVariableInitialization (VOID)
Variable Documentation
SEP_WORK_ITEM SepExWorkItem
Definition at line 347 of file seglobal.c.
Referenced by SepQueueWorkItem().
HANDLE SepLsaHandle
Definition at line 315 of file seglobal.c.
Referenced by SepRmCallLsa(), SepRmCommandServerThread(), and SepRmCommandServerThreadInit().
LIST_ENTRY SepLsaQueue
Definition at line 329 of file seglobal.c.
Referenced by SepDequeueWorkItem(), and SepQueueWorkItem().
ULONG SepLsaQueueLength
Definition at line 335 of file seglobal.c.
Referenced by SepRmCallLsa().
ERESOURCE SepLsaQueueLock
Definition at line 345 of file seglobal.c.
LONG SepTokenPolicyCounter[POLICY_AUDIT_EVENT_TYPE_COUNT]
Definition at line 249 of file seglobal.c.
Referenced by SeDetailedAuditingWithToken(), SepAdtAuditThisEventWithContext(), SepModifyTokenPolicyCounter(), and SepTokenDeleteMethod().