Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psspnd.c File Reference
psspnd.c File Reference
#include "psp.h"
Functions
NTSTATUS NtAlertResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
NTSTATUS NtAlertThread (__in HANDLE ThreadHandle)
NTSTATUS NtResumeProcess (__in HANDLE ProcessHandle)
NTSTATUS NtResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
NTSTATUS NtSuspendProcess (__in HANDLE ProcessHandle)
NTSTATUS NtSuspendThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
NTSTATUS NtTestAlert (VOID)
NTSTATUS PsResumeProcess (PEPROCESS Process)
NTSTATUS PsResumeThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
NTSTATUS PsSuspendProcess (PEPROCESS Process)
NTSTATUS PsSuspendThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
Function Documentation
NTSTATUS NtAlertResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
Definition at line 534 of file psspnd.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeAlertResumeThread(), KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong, PsThreadType, STATUS_SUCCESS, _ETHREAD::Tcb, and THREAD_SUSPEND_RESUME.
NTSTATUS NtAlertThread (__in HANDLE ThreadHandle)
Definition at line 483 of file psspnd.c.
References KeAlertThread(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsThreadType, STATUS_SUCCESS, _ETHREAD::Tcb, and THREAD_ALERT.
NTSTATUS NtResumeProcess (__in HANDLE ProcessHandle)
Definition at line 441 of file psspnd.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsProcessType, PsResumeProcess(), and Status.
NTSTATUS NtResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
Definition at line 323 of file psspnd.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong, PsResumeThread(), PsThreadType, STATUS_SUCCESS, and THREAD_SUSPEND_RESUME.
Referenced by RtlRemoteCall().
NTSTATUS NtSuspendProcess (__in HANDLE ProcessHandle)
Definition at line 398 of file psspnd.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsProcessType, PsSuspendProcess(), and Status.
NTSTATUS NtSuspendThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
Definition at line 206 of file psspnd.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong, PsSuspendThread(), PsThreadType, and THREAD_SUSPEND_RESUME.
Referenced by RtlRemoteCall().
NTSTATUS NtTestAlert (VOID)
Definition at line 611 of file psspnd.c.
References KeGetPreviousMode, KeTestAlertThread(), PAGED_CODE, STATUS_ALERTED, and STATUS_SUCCESS.
NTSTATUS PsResumeProcess (PEPROCESS Process)
Definition at line 163 of file psspnd.c.
References ExAcquireRundownProtection(), ExReleaseRundownProtection(), KeResumeThread(), NULL, PAGED_CODE, PsGetNextProcessThread(), _EPROCESS::RundownProtect, Status, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by NtResumeProcess().
NTSTATUS PsResumeThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
Definition at line 286 of file psspnd.c.
References ARGUMENT_PRESENT, KeResumeThread(), PAGED_CODE, and STATUS_SUCCESS.
Referenced by DbgkpPostFakeThreadMessages(), DbgkpWakeTarget(), and NtResumeThread().
NTSTATUS PsSuspendProcess (PEPROCESS Process)
Definition at line 118 of file psspnd.c.
References ExAcquireRundownProtection(), ExReleaseRundownProtection(), NULL, PAGED_CODE, PsGetNextProcessThread(), PsSuspendThread(), _EPROCESS::RundownProtect, Status, STATUS_PROCESS_IS_TERMINATING, and STATUS_SUCCESS.
Referenced by NtSuspendProcess().
NTSTATUS PsSuspendThread (IN PETHREAD Thread, OUT PULONG PreviousSuspendCount OPTIONAL)
Definition at line 37 of file psspnd.c.
References ARGUMENT_PRESENT, ExAcquireRundownProtection(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), KeForceResumeThread(), KeSuspendThread(), PAGED_CODE, PS_CROSS_THREAD_FLAGS_TERMINATED, PsGetCurrentThread(), Status, STATUS_SUCCESS, STATUS_SUSPEND_COUNT_EXCEEDED, and STATUS_THREAD_IS_TERMINATING.
Referenced by DbgkpPostFakeThreadMessages(), NtSuspendThread(), and PsSuspendProcess().