Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/mdlsup.c File Reference
mdlsup.c File Reference
#include "cc.h"
Macros
#define me (0x00000010)
Functions
VOID CcMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
VOID CcMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
VOID CcMdlReadComplete2 (IN PFILE_OBJECT FileObject, IN PMDL MdlChain)
VOID CcMdlWriteAbort (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
VOID CcMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
VOID CcMdlWriteComplete2 (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain)
VOID CcPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Macro Definition Documentation
#define me (0x00000010)
Definition at line 25 of file mdlsup.c.
Referenced by CcMdlRead(), CcMdlReadComplete2(), CcMdlWriteAbort(), CcMdlWriteComplete2(), and CcPrepareMdlWrite().
Function Documentation
VOID CcMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 36 of file mdlsup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_SET_PRIVATE_CACHE_MAP, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMdlReadWait, CcMdlReadWaitMiss, CcMissCounter, CcScheduleReadAhead(), CcThrowAway, CONTAINING_RECORD, DebugTrace, DebugTrace2, ExRaiseStatus(), FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, _SHARED_CACHE_MAP::FileSize, FlagOn, _PRIVATE_CACHE_MAP::Flags, FO_RANDOM_ACCESS, GetActiveVacb, IoAllocateMdl(), IoFreeMdl(), IoReadAccess, KernelMode, me, mm, MmProbeAndLockPages(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmUnlockPages(), _SHARED_CACHE_MAP::NeedToZero, _MDL::Next, NULL, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _PRIVATE_CACHE_MAP_FLAGS::ReadAheadEnabled, _PRIVATE_CACHE_MAP::ReadAheadLength, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by FsRtlMdlReadDev().
VOID CcMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
Definition at line 386 of file mdlsup.c.
References CcMdlReadComplete2(), FIELD_OFFSET, IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlReadComplete, NOTHING, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
VOID CcMdlReadComplete2 (IN PFILE_OBJECT FileObject, IN PMDL MdlChain)
Definition at line 411 of file mdlsup.c.
References DebugTrace, IoFreeMdl(), me, mm, MmUnlockPages(), _MDL::Next, NULL, and UNREFERENCED_PARAMETER.
Referenced by CcMdlReadComplete(), and FsRtlMdlReadCompleteDev().
VOID CcMdlWriteAbort (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
Definition at line 1048 of file mdlsup.c.
References CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcReleaseMasterLock, CcScheduleLazyWriteScan(), DebugTrace, _SHARED_CACHE_MAP::DirtyPages, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, InsertTailList(), IoFreeMdl(), LazyWriter, MDL_PAGES_LOCKED, me, mm, MmUnlockPages(), _MDL::Next, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, and WRITE_QUEUED.
VOID CcMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
Definition at line 825 of file mdlsup.c.
References CcMdlWriteComplete2(), FIELD_OFFSET, IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlWriteComplete, NOTHING, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
VOID CcMdlWriteComplete2 (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain)
Definition at line 851 of file mdlsup.c.
References ASSERT, _MDL::ByteCount, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcSetDirtyInMask(), DebugTrace, _SHARED_CACHE_MAP::DirtyPages, ExRaiseStatus(), FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, FO_WRITE_THROUGH, FsRtlNormalizeNtstatus(), InsertTailList(), IoFreeMdl(), LazyWriter, MDL_PAGES_LOCKED, me, mm, MM_FLUSH_ACQUIRE_FILE, MmFlushSection(), MmUnlockPages(), _MDL::Next, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, TRUE, UNALIGNED, and WRITE_QUEUED.
Referenced by CcMdlWriteComplete(), and FsRtlMdlWriteCompleteDev().
VOID CcPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 473 of file mdlsup.c.
References _SHARED_CACHE_MAP::BcbSpinLock, CcAcquireMasterLock, CcForceWriteThrough(), CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcIncrementOpenCount, CcMapAndRead(), CcReleaseMasterLock, CcSetDirtyInMask(), CONTAINING_RECORD, DebugTrace, DebugTrace2, ExRaiseStatus(), FALSE, FileOffset, FlagOn, FO_WRITE_THROUGH, GetActiveVacb, _LARGE_INTEGER::HighPart, IoAllocateMdl(), IoFreeMdl(), IoWriteAccess, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), KernelMode, _LARGE_INTEGER::LowPart, me, mm, MmDisablePageFaultClustering, MmEnablePageFaultClustering, MmProbeAndLockPages(), MmUnlockPages(), _SHARED_CACHE_MAP::NeedToZero, _MDL::Next, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, PAGE_SIZE, _LARGE_INTEGER::QuadPart, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _SHARED_CACHE_MAP::ValidDataGoal, VOID, ZERO_FIRST_PAGE, ZERO_LAST_PAGE, and ZERO_MIDDLE_PAGES.
Referenced by FsRtlPrepareMdlWriteDev().