Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/wmi.h File Reference
wmi.h File Reference
#include <evntrace.h>
#include <stdarg.h>
#include <wmistr.h>
#include <ntwmi.h>
Macros
#define _WMIKM_
#define RUN_WPP
#define TRACE_INFORMATION_CLASS_DEFINE
Typedefs
typedef enum _TRACE_INFORMATION_CLASS TRACE_INFORMATION_CLASS
typedef enum tagWMI_CLOCK_TYPE WMI_CLOCK_TYPE
typedef __int64(* WMI_GET_CPUCLOCK_ROUTINE) ()
typedef VOID(* WMI_TRACE_BUFFER_CALLBACK) (IN PWMI_BUFFER_HEADER Buffer, IN PVOID Context)
Enumerations
enum _TRACE_INFORMATION_CLASS {
TraceIdClass, TraceHandleClass, TraceEnableFlagsClass, TraceEnableLevelClass,
GlobalLoggerHandleClass, EventLoggerHandleClass, AllLoggerHandlesClass, TraceHandleByNameClass
}
enum tagWMI_CLOCK_TYPE {
WMICT_DEFAULT, WMICT_SYSTEMTIME, WMICT_PERFCOUNTER, WMICT_PROCESS,
WMICT_THREAD, WMICT_CPUCYCLE
}
Functions
NTKERNELAPI VOID WmiBootPhase1 (VOID)
NTKERNELAPI NTSTATUS WmiFlushTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTKERNELAPI LONG64 FASTCALL WmiGetClock (IN WMI_CLOCK_TYPE ClockType, IN PVOID Context)
NTKERNELAPI NTSTATUS FASTCALL WmiGetClockType (IN TRACEHANDLE LoggerHandle, OUT WMI_CLOCK_TYPE *ClockType)
NTKERNELAPI NTSTATUS WmiQueryTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTKERNELAPI NTSTATUS WmiQueryTraceInformation (IN TRACE_INFORMATION_CLASS TraceInformationClass, OUT PVOID TraceInformation, IN ULONG TraceInformationLength, OUT PULONG RequiredLength OPTIONAL, IN PVOID Buffer OPTIONAL)
NTKERNELAPI ULONG FASTCALL WmiReleaseKernelBuffer (IN PWMI_BUFFER_HEADER BufferResource)
NTKERNELAPI PPERFINFO_TRACE_HEADER FASTCALL WmiReserveWithPerfHeader (IN ULONG AuxSize, OUT PWMI_BUFFER_HEADER *BufferResource)
NTKERNELAPI NTSTATUS WmiSetMark (IN PWMI_SET_MARK_INFORMATION MarkInfo, IN ULONG InBufferLen)
NTKERNELAPI NTSTATUS WmiSetTraceBufferCallback (IN TRACEHANDLE TraceHandle, IN WMI_TRACE_BUFFER_CALLBACK Callback, IN PVOID Context)
VOID FASTCALL WmiStartContextSwapTrace ()
NTKERNELAPI NTSTATUS WmiStartTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
VOID FASTCALL WmiStopContextSwapTrace ()
NTKERNELAPI NTSTATUS WmiStopTrace (IN PWMI_LOGGER_INFORMATION LoggerInfo)
VOID FASTCALL WmiTraceContextSwap (IN PETHREAD pOldEThread, IN PETHREAD pNewEThread)
NTKERNELAPI NTSTATUS FASTCALL WmiTraceEvent (IN PWNODE_HEADER Wnode, IN KPROCESSOR_MODE RequestorMode)
NTKERNELAPI NTSTATUS FASTCALL WmiTraceFastEvent (IN PWNODE_HEADER Wnode)
NTKERNELAPI NTSTATUS WmiTraceKernelEvent (IN ULONG GroupType, IN PVOID EventInfo, IN ULONG EventInfoLen, IN PETHREAD Thread)
NTKERNELAPI NTSTATUS WmiTraceMessage (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, IN...)
NTKERNELAPI NTSTATUS WmiTraceMessageVa (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, IN va_list MessageArgList)
NTKERNELAPI VOID FASTCALL WmiTraceProcess (IN PEPROCESS Process, IN BOOLEAN Create)
NTKERNELAPI VOID WmiTraceThread (IN PETHREAD Thread, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN Create)
NTKERNELAPI NTSTATUS WmiUpdateTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Variables
WMI_GET_CPUCLOCK_ROUTINE WmiGetCpuClock
ULONG WmiUsePerfClock
Macro Definition Documentation
#define _WMIKM_
Definition at line 25 of file wmi.h.
#define RUN_WPP
Definition at line 29 of file wmi.h.
#define TRACE_INFORMATION_CLASS_DEFINE
Definition at line 180 of file wmi.h.
Typedef Documentation
typedef enum _TRACE_INFORMATION_CLASS TRACE_INFORMATION_CLASS
typedef enum tagWMI_CLOCK_TYPE WMI_CLOCK_TYPE
typedef __int64(* WMI_GET_CPUCLOCK_ROUTINE) ()
Definition at line 42 of file wmi.h.
typedef VOID(* WMI_TRACE_BUFFER_CALLBACK) (IN PWMI_BUFFER_HEADER Buffer, IN PVOID Context)
Definition at line 51 of file wmi.h.
Enumeration Type Documentation
enum _TRACE_INFORMATION_CLASS
Enumerator
TraceIdClass
TraceHandleClass
TraceEnableFlagsClass
TraceEnableLevelClass
GlobalLoggerHandleClass
EventLoggerHandleClass
AllLoggerHandlesClass
TraceHandleByNameClass
Definition at line 160 of file wmi.h.
enum tagWMI_CLOCK_TYPE
Enumerator
WMICT_DEFAULT
WMICT_SYSTEMTIME
WMICT_PERFCOUNTER
WMICT_PROCESS
WMICT_THREAD
WMICT_CPUCYCLE
Definition at line 57 of file wmi.h.
Function Documentation
NTKERNELAPI VOID WmiBootPhase1 (VOID)
Referenced by NtInitializeRegistry().
NTKERNELAPI NTSTATUS WmiFlushTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 775 of file traceapi.c.
References EtwpDefaultTraceSecurityDescriptor, _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedDecrement, _WMI_LOGGER_CONTEXT::KernelTraceOn, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMode, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::MutexCount, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, TraceDebug, TRUE, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipFlushLogger(), WmipQueryLogger(), WmipReleaseMutex, and WmipVerifyLoggerInfo().
Referenced by WmipIoControl(), and WmiStartTrace().
NTKERNELAPI LONG64 FASTCALL WmiGetClock (IN WMI_CLOCK_TYPE ClockType, IN PVOID Context)
Definition at line 952 of file traceapi.c.
References _LARGE_INTEGER::HighPart, KeQueryRuntimeProcess(), KeQuerySystemTime(), _KTHREAD::KernelTime, _LARGE_INTEGER::LowPart, NULL, ObDereferenceObject(), ObReferenceObject, _EPROCESS::Pcb, PerfGetCycleCount(), PsGetCurrentProcess(), PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _ETHREAD::Tcb, _KTHREAD::UserTime, WMICT_CPUCYCLE, WMICT_DEFAULT, WMICT_PERFCOUNTER, WMICT_PROCESS, WMICT_SYSTEMTIME, WMICT_THREAD, WmipGetPerfCounter(), and WmipGetSystemTime().
NTKERNELAPI NTSTATUS FASTCALL WmiGetClockType (IN TRACEHANDLE LoggerHandle, OUT WMI_CLOCK_TYPE * ClockType)
Definition at line 880 of file traceapi.c.
References EVENT_TRACE_CLOCK_CPUCYCLE, EVENT_TRACE_CLOCK_PERFCOUNTER, MAXLOGGERS, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TraceDebug, _WMI_LOGGER_CONTEXT::UsePerfClock, WMICT_CPUCYCLE, WMICT_PERFCOUNTER, WMICT_SYSTEMTIME, WmiGetLoggerId, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, and WmipReferenceLogger.
NTKERNELAPI NTSTATUS WmiQueryTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 128 of file traceapi.c.
References NULL, PAGED_CODE, STATUS_INVALID_PARAMETER, and WmipQueryLogger().
Referenced by WmiQueryTraceInformation().
NTKERNELAPI NTSTATUS WmiQueryTraceInformation (IN TRACE_INFORMATION_CLASS TraceInformationClass, OUT PVOID TraceInformation, IN ULONG TraceInformationLength, OUT PULONG RequiredLength OPTIONAL, IN PVOID Buffer OPTIONAL)
Definition at line 2172 of file traceapi.c.
References AllLoggerHandlesClass, ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _WNODE_HEADER::BufferSize, EventLoggerHandleClass, except, EXCEPTION_EXECUTE_HANDLER, _WNODE_HEADER::Flags, GlobalLoggerHandleClass, _WNODE_HEADER::HistoricalContext, _UNICODE_STRING::Length, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_INFORMATION::LoggerName, MAXLOGGERS, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_HANDLE, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_MIX, STATUS_MORE_ENTRIES, STATUS_NOT_FOUND, STATUS_SUCCESS, TraceEnableFlagsClass, TraceEnableLevelClass, TraceHandleByNameClass, TraceHandleClass, TraceIdClass, WmiGetLoggerEnableFlags, WmiGetLoggerEnableLevel, WmiGetLoggerId, WmipDereferenceLogger, WmipEventLogger, WmipIsValidLogger, WmipLoggerContext, WmipReferenceLogger, WmiQueryTrace(), WmiSetLoggerId, _WMI_LOGGER_INFORMATION::Wnode, and WNODE_FLAG_TRACED_GUID.
NTKERNELAPI ULONG FASTCALL WmiReleaseKernelBuffer (IN PWMI_BUFFER_HEADER BufferResource)
Definition at line 1804 of file tracelog.c.
References NULL, WmipAssert, WmipKernelLogger, and WmipReleaseTraceBuffer().
NTKERNELAPI PPERFINFO_TRACE_HEADER FASTCALL WmiReserveWithPerfHeader (IN ULONG AuxSize, OUT PWMI_BUFFER_HEADER * BufferResource)
Definition at line 471 of file tracelog.c.
References FIELD_OFFSET, _PERFINFO_TRACE_HEADER::Marker, NULL, _PERFINFO_TRACE_HEADER::Packet, PERFINFO_TRACE_MARKER, _WMI_TRACE_PACKET::Size, _PERFINFO_TRACE_HEADER::SystemTime, TraceDebug, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, and WmipReserveTraceBuffer().
Referenced by PerfInfoReserveBytes(), WmipTraceFile(), and WmipTraceNetwork().
NTKERNELAPI NTSTATUS WmiSetMark (IN PWMI_SET_MARK_INFORMATION MarkInfo, IN ULONG InBufferLen)
Definition at line 2037 of file traceapi.c.
References FIELD_OFFSET, MmEmptyAllWorkingSets(), MmPerfSnapShotValidPhysicalMemory(), NT_SUCCESS, PERF_FINISH_HOOK, PERF_FOOTPRINT, PERFINFO_HOOK_HANDLE_TO_DATA, PERFINFO_IS_ANY_GROUP_ON, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_MARK, PerfInfoReserveBytes(), RtlCopyMemory, Status, STATUS_WMI_SET_FAILURE, UNICODE_NULL, and WMI_SET_MARK_WITH_FLUSH.
Referenced by WmipIoControl().
NTKERNELAPI NTSTATUS WmiSetTraceBufferCallback (IN TRACEHANDLE TraceHandle, IN WMI_TRACE_BUFFER_CALLBACK Callback, IN PVOID Context)
Definition at line 2098 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::BufferCallback, _WMI_LOGGER_CONTEXT::CallbackContext, KERNEL_LOGGER_ID, MAXLOGGERS, PAGED_CODE, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TraceDebug, WmiGetLoggerId, WmipDereferenceLogger, WmipGetLoggerContext, WmipGlobalBufferCallback, WmipIsValidLogger, WmipKernelLogger, and WmipReferenceLogger.
VOID FASTCALL WmiStartContextSwapTrace ()
Definition at line 1821 of file callouts.c.
References MAXIMUM_PROCESSORS, PAGED_CODE, RtlZeroMemory, and WmipContextSwapProcessorBuffers.
Referenced by PerfInfoStartLog().
NTKERNELAPI NTSTATUS WmiStartTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 47 of file traceapi.c.
References ExFreePool(), FALSE, NT_SUCCESS, NULL, PAGED_CODE, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_PARAMETER, WmiFlushTrace(), WmipCreateDirectoryFile(), WmipCreateNtFileName(), WmipStartLogger(), and ZwClose().
VOID FASTCALL WmiStopContextSwapTrace ()
Definition at line 1867 of file callouts.c.
References _KTHREAD::Affinity, AFFINITY_MASK, KeGetCurrentThread(), KeNumberProcessors, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), NULL, PAGED_CODE, WmipContextSwapProcessorBuffers, WmipIsValidLogger, WmipKernelLogger, WmipLoggerContext, and WmipPushDirtyContextSwapBuffer().
Referenced by PerfInfoStartLog(), and PerfInfoStopLog().
NTKERNELAPI NTSTATUS WmiStopTrace (IN PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 160 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::BuffersAvailable, EtwpDefaultTraceSecurityDescriptor, Executive, FALSE, _WMI_LOGGER_CONTEXT::FlushEvent, _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedDecrement, KeResetEvent(), KERNEL_LOGGER, KernelMode, _WMI_LOGGER_CONTEXT::KernelTraceOn, KeWaitForSingleObject(), _WMI_LOGGER_CONTEXT::LogFileHandle, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::LoggerStatus, _WMI_LOGGER_CONTEXT::MutexCount, NT_SUCCESS, NULL, _WMI_LOGGER_CONTEXT::NumberOfBuffers, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_TIMEOUT, TraceDebug, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipDisableTraceProviders(), WmipEventLogger, WmipKernelLogger, WmipLoggerContext, WmipQueryLogger(), WmipReleaseMutex, WmipStopLoggerInstance(), and WmipVerifyLoggerInfo().
Referenced by WmipIoControl(), and WmipShutdown().
VOID FASTCALL WmiTraceContextSwap (IN PETHREAD pOldEThread, IN PETHREAD pNewEThread)
Definition at line 1655 of file callouts.c.
References ASSERT, _WMI_BUFFER_HEADER::CurrentOffset, FIELD_OFFSET, HandleToUlong, _WMI_TRACE_PACKET::HookId, KeGetCurrentProcessorNumber(), _PERFINFO_TRACE_HEADER::Marker, _WMI_CONTEXTSWAP::NewThreadId, _WMI_CONTEXTSWAP::NewThreadPriority, _WMI_CONTEXTSWAP::NewThreadQuantum, NULL, _WMI_BUFFER_HEADER::Offset, _WMI_CONTEXTSWAP::OldThreadId, _WMI_CONTEXTSWAP::OldThreadIdealProcessor, _WMI_CONTEXTSWAP::OldThreadPriority, _WMI_CONTEXTSWAP::OldThreadQuantum, _WMI_CONTEXTSWAP::OldThreadState, _WMI_CONTEXTSWAP::OldThreadWaitMode, _WMI_CONTEXTSWAP::OldThreadWaitReason, _PERFINFO_TRACE_HEADER::Packet, PERFINFO_LOG_TYPE_CONTEXTSWAP, PERFINFO_TRACE_MARKER, PerfTimeStamp, _WMI_TRACE_PACKET::Size, _PERFINFO_TRACE_HEADER::SystemTime, WMI_CTXSWAP_EVENTSIZE_ALIGNMENT, WmipContextSwapProcessorBuffers, WmipPopFreeContextSwapBuffer(), and WmipPushDirtyContextSwapBuffer().
NTKERNELAPI NTSTATUS FASTCALL WmiTraceEvent (IN PWNODE_HEADER Wnode, IN KPROCESSOR_MODE RequestorMode)
Definition at line 1154 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::BufferSize, _ETHREAD::Cid, DISPATCH_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, HandleToUlong, InterlockedCompareExchange(), KeGetCurrentIrql(), KernelMode, _KTHREAD::KernelTime, _WMI_LOGGER_CONTEXT::LoggerMode, MAXLOGGERS, NULL, ProbeForRead, ProbeForReadSmallStructure, PsGetCurrentThread(), REQUEST_FLAG_CIRCULAR_PERSIST, REQUEST_FLAG_CIRCULAR_TRANSITION, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, Status, STATUS_ARRAY_BOUNDS_EXCEEDED, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_HANDLE, STATUS_NO_MEMORY, STATUS_SEVERITY_WARNING, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _ETHREAD::Tcb, TRACE_HEADER_ENUM_MASK, TRACE_HEADER_FLAG, TRACE_HEADER_TYPE_INSTANCE, TraceDebug, TRUE, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, _KTHREAD::UserTime, WmiGetLoggerId, WmipDereferenceLogger, WmipFlushLogger(), WmipGetLoggerContext, WmipIsValidLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), WmipReserveTraceBuffer(), WNODE_FLAG_LOG_WNODE, WNODE_FLAG_PERSIST_EVENT, WNODE_FLAG_TRACED_GUID, WNODE_FLAG_USE_GUID_PTR, WNODE_FLAG_USE_MOF_PTR, and WNODE_FLAG_USE_TIMESTAMP.
Referenced by IoWMIWriteEvent(), NtTraceEvent(), WmipFastIoDeviceControl(), and WmipIoControl().
NTKERNELAPI NTSTATUS FASTCALL WmiTraceFastEvent (IN PWNODE_HEADER Wnode)
Definition at line 1562 of file traceapi.c.
References DBG, _TIMED_TRACE_HEADER::EventId, _TIMED_TRACE_HEADER::LoggerId, MAXLOGGERS, NULL, RtlCopyMemory, _TIMED_TRACE_HEADER::Size, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_SUCCESS, _TIMED_TRACE_HEADER::TimeStamp, TRACE_HEADER_ULONG32_TIME, TraceDebug, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmipReserveTraceBuffer().
Referenced by IoWMIWriteEvent().
NTKERNELAPI NTSTATUS WmiTraceKernelEvent (IN ULONG GroupType, IN PVOID EventInfo, IN ULONG EventInfoLen, IN PETHREAD Thread)
Definition at line 1449 of file traceapi.c.
References HandleToUlong, _SYSTEM_TRACE_HEADER::Header, _SYSTEM_TRACE_HEADER::KernelTime, _WMI_LOGGER_CONTEXT::LoggerId, _SYSTEM_TRACE_HEADER::Marker, NULL, _SYSTEM_TRACE_HEADER::ProcessId, PsGetCurrentThread(), RtlCopyMemory, STATUS_ALREADY_DISCONNECTED, STATUS_NO_MEMORY, STATUS_SUCCESS, SYSTEM_TRACE_MARKER, _SYSTEM_TRACE_HEADER::SystemTime, _SYSTEM_TRACE_HEADER::ThreadId, TraceDebug, _SYSTEM_TRACE_HEADER::UserTime, WmipDereferenceLogger, WmipIsValidLogger, WmipKernelLogger, WmipLoggerContext, WmipRefCount, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmipReserveTraceBuffer().
NTKERNELAPI NTSTATUS WmiTraceMessage (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, IN...)
NTKERNELAPI NTSTATUS WmiTraceMessageVa (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, IN va_list MessageArgList)
NTKERNELAPI VOID FASTCALL WmiTraceProcess (IN PEPROCESS Process, IN BOOLEAN Create)
Definition at line 564 of file callouts.c.
References _STRING::Buffer, _WMI_LOGGER_CONTEXT::EnableFlags, ExFreePool(), _WMI_PROCESS_INFORMATION::ExitStatus, FALSE, FIELD_OFFSET, HandleToUlong, _WMI_TRACE_PACKET::HookId, _STRING::Length, _UNICODE_STRING::Length, MAXLOGGERS, MmGetDirectoryFrameFromProcess(), MmGetSessionId(), NT_SUCCESS, NULL, _SYSTEM_TRACE_HEADER::Packet, PAGED_CODE, _WMI_PROCESS_INFORMATION::PageDirectoryBase, _WMI_PROCESS_INFORMATION::ParentId, _WMI_PROCESS_INFORMATION::ProcessId, PsDereferencePrimaryTokenEx, PsReferencePrimaryToken(), RtlCopyMemory, RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), SeLengthSid, SeLocateProcessImageName(), SeQueryInformationToken(), _WMI_PROCESS_INFORMATION::SessionId, _SID_AND_ATTRIBUTES::Sid, _WMI_PROCESS_INFORMATION::Sid, Status, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, strlen(), TokenUser, TraceDebug, TRUE, _TOKEN_USER::User, WMI_LOG_TYPE_PROCESS_CREATE, WMI_LOG_TYPE_PROCESS_DELETE, WmipAssert, WmipDereferenceLogger, WmipEventLogger, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
NTKERNELAPI VOID WmiTraceThread (IN PETHREAD Thread, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN Create)
Definition at line 760 of file callouts.c.
References _WMI_LOGGER_CONTEXT::EnableFlags, HandleToUlong, _WMI_TRACE_PACKET::HookId, MAXLOGGERS, NULL, _SYSTEM_TRACE_HEADER::Packet, PAGED_CODE, _WMI_THREAD_INFORMATION::ProcessId, _WMI_EXTENDED_THREAD_INFORMATION::ProcessId, _WMI_EXTENDED_THREAD_INFORMATION::StackBase, _WMI_EXTENDED_THREAD_INFORMATION::StackLimit, _WMI_EXTENDED_THREAD_INFORMATION::StartAddr, _WMI_THREAD_INFORMATION::ThreadId, _WMI_EXTENDED_THREAD_INFORMATION::ThreadId, TraceDebug, _WMI_EXTENDED_THREAD_INFORMATION::UserStackBase, _WMI_EXTENDED_THREAD_INFORMATION::UserStackLimit, _WMI_EXTENDED_THREAD_INFORMATION::WaitMode, _WMI_EXTENDED_THREAD_INFORMATION::Win32StartAddr, WMI_LOG_TYPE_THREAD_CREATE, WMI_LOG_TYPE_THREAD_DELETE, WmipDereferenceLogger, WmipEventLogger, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
NTKERNELAPI NTSTATUS WmiUpdateTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 321 of file traceapi.c.
References ASSERT, _UNICODE_STRING::Buffer, _WMI_LOGGER_CONTEXT::BufferCallback, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_LOGGER_CONTEXT::ClientSecurityContext, _WMI_LOGGER_CONTEXT::CollectionOn, CONTAINING_RECORD, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, _WMI_LOGGER_CONTEXT::EnableFlagArray, _WMI_LOGGER_CONTEXT::EnableFlags, EtwpDefaultTraceSecurityDescriptor, EVENT_TRACE_KD_FILTER_MODE, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, FIELD_OFFSET, FILE_WRITE_DATA, _WMI_LOGGER_CONTEXT::FlushEvent, _WMI_LOGGER_CONTEXT::FlushTimer, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedCompareExchange(), InterlockedDecrement, InterlockedExchange(), IoFileObjectType, IsEqualGUID, KdReportTraceData(), KeGetCurrentThread(), KeGetPreviousMode, KeResetEvent(), KernelMode, _WMI_LOGGER_CONTEXT::KernelTraceOn, KeWaitForSingleObject(), _TRACE_ENABLE_FLAG_EXTENSION::Length, _SECURITY_QUALITY_OF_SERVICE::Length, _WMI_LOGGER_CONTEXT::LogFileHandle, _WMI_LOGGER_CONTEXT::LoggerHeader, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMode, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::LoggerStatus, _WMI_LOGGER_CONTEXT::MaximumBuffers, MmMaximumNonPagedPoolInBytes, _WMI_LOGGER_CONTEXT::MutexCount, _WMI_LOGGER_CONTEXT::NewLogFileName, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _TRACE_ENABLE_FLAG_EXTENSION::Offset, PAGED_CODE, PagedPool, PERF_LOG_NO_TRANSITION, PERF_LOG_START_TRANSITION, PERFINFO_START_LOG_POST_BOOT, PerfInfoStartLog(), _WMI_LOGGER_CONTEXT::PerfLogInTransition, ProbeForRead, REQUEST_FLAG_NEW_FILE, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlZeroMemory, SeComputeGrantedAccesses, SeCreateClientSecurity(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, Status, STATUS_ACCESS_DENIED, STATUS_ALREADY_DISCONNECTED, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, TRACE_MAXIMUM_NP_POOL_USAGE, TraceDebug, TRACEPOOLTAG, TRUE, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipExtendBase(), WmipKernelLogger, WmipNotifyLogger(), WmipQueryLogger(), WmipReleaseMutex, WmipVerifyLoggerInfo(), and ZwClose().
Referenced by WmipIoControl().
Variable Documentation
WMI_GET_CPUCLOCK_ROUTINE WmiGetCpuClock
Definition at line 55 of file tracesup.c.
Referenced by WmipStartLogger().
ULONG WmiUsePerfClock
Definition at line 62 of file tracelog.c.