Windows Research Kernel v1.2: C:/Windows Research Kernel/config/ntapi.c File Reference
ntapi.c File Reference
#include "cmp.h"
#include "safeboot.h"
#include <evntrace.h>
Macros
#define ALLOCATE_WITH_QUOTA(a, b, c) ExAllocatePoolWithQuota((a)|POOL_QUOTA_FAIL_INSTEAD_OF_RAISE,b)
#define CmpExceptionFilter(x) EXCEPTION_EXECUTE_HANDLER
#define OBJ_AUDIT_OBJECT_CLOSE 0x00000004L
Functions
PCM_POST_BLOCK CmpAllocatePostBlock (IN POST_BLOCK_TYPE BlockType, IN ULONG PostFlags, IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK MasterBlock)
VOID CmpDummyApc (struct _KAPC *Apc, PVOID *SystemArgument1, PVOID *SystemArgument2)
VOID CmpFreePostBlock (IN PCM_POST_BLOCK PostBlock)
ULONG CmpKeyInfoProbeAlingment (IN KEY_INFORMATION_CLASS KeyInformationClass)
NTSTATUS CmpNameFromAttributes (IN POBJECT_ATTRIBUTES Attributes, KPROCESSOR_MODE PreviousMode, OUT PUNICODE_STRING FullName)
NTSTATUS NtCompactKeys (__in ULONG Count, __in_ecount(Count) HANDLE KeyArray[])
NTSTATUS NtCompressKey (__in HANDLE Key)
NTSTATUS NtCreateKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __reserved ULONG TitleIndex, __in_opt PUNICODE_STRING Class, __in ULONG CreateOptions, __out_opt PULONG Disposition)
NTSTATUS NtDeleteKey (__in HANDLE KeyHandle)
NTSTATUS NtDeleteValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName)
NTSTATUS NtEnumerateKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
NTSTATUS NtEnumerateValueKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
NTSTATUS NtFlushKey (__in HANDLE KeyHandle)
NTSTATUS NtInitializeRegistry (__in USHORT BootCondition)
NTSTATUS NtLoadKey (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile)
NTSTATUS NtLoadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags)
NTSTATUS NtLoadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags, __in_opt HANDLE TrustClassKey)
NTSTATUS NtLockRegistryKey (__in HANDLE KeyHandle)
NTSTATUS NtNotifyChangeKey (__in HANDLE KeyHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
NTSTATUS NtNotifyChangeMultipleKeys (__in HANDLE MasterKeyHandle, __in_opt ULONG Count, __in_ecount_opt(Count) OBJECT_ATTRIBUTES SlaveObjects[], __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
NTSTATUS NtOpenKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQueryKey (__in HANDLE KeyHandle, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
NTSYSAPI NTSTATUS NTAPI NtQueryMultipleValueKey (__in HANDLE KeyHandle, __inout_ecount(EntryCount) PKEY_VALUE_ENTRY ValueEntries, __in ULONG EntryCount, __out_bcount(*BufferLength) PVOID ValueBuffer, __inout PULONG BufferLength, __out_opt PULONG RequiredBufferLength)
NTSTATUS NtQueryOpenSubKeys (__in POBJECT_ATTRIBUTES TargetKey, __out PULONG HandleCount)
NTSTATUS NtQueryOpenSubKeysEx (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG BufferLength, __out_bcount(BufferLength) PVOID Buffer, __out PULONG RequiredSize)
NTSTATUS NtQueryValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
NTSTATUS NtRenameKey (__in HANDLE KeyHandle, __in PUNICODE_STRING NewName)
NTSTATUS NtReplaceKey (__in POBJECT_ATTRIBUTES NewFile, __in HANDLE TargetHandle, __in POBJECT_ATTRIBUTES OldFile)
NTSTATUS NtRestoreKey (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Flags)
NTSTATUS NtSaveKey (__in HANDLE KeyHandle, __in HANDLE FileHandle)
NTSTATUS NtSaveKeyEx (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Format)
NTSTATUS NtSaveMergedKeys (__in HANDLE HighPrecedenceKeyHandle, __in HANDLE LowPrecedenceKeyHandle, __in HANDLE FileHandle)
NTSTATUS NtSetInformationKey (__in HANDLE KeyHandle, __in KEY_SET_INFORMATION_CLASS KeySetInformationClass, __in_bcount(KeySetInformationLength) PVOID KeySetInformation, __in ULONG KeySetInformationLength)
NTSTATUS NtSetValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in_opt ULONG TitleIndex, __in ULONG Type, __in_bcount_opt(DataSize) PVOID Data, __in ULONG DataSize)
NTSTATUS NtUnloadKey (__in POBJECT_ATTRIBUTES TargetKey)
NTSTATUS NtUnloadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG Flags)
NTSTATUS NtUnloadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in_opt HANDLE Event)
Variables
BOOLEAN CmBootAcceptFirstTime
BOOLEAN CmFirstTime
BOOLEAN CmpCannotWriteConfiguration
BOOLEAN CmpHoldLazyFlush
POBJECT_TYPE CmpKeyObjectType
ULONG CmpOpenSubKeys
BOOLEAN CmpTraceFlag
POBJECT_TYPE ExEventObjectType
PCM_KEY_BODY ExpControlKey [2]
BOOLEAN HvShutdownComplete
Macro Definition Documentation
#define ALLOCATE_WITH_QUOTA (a, b, c) ExAllocatePoolWithQuota((a)|POOL_QUOTA_FAIL_INSTEAD_OF_RAISE,b)
Definition at line 58 of file ntapi.c.
Referenced by CmpAllocatePostBlock(), CmpNameFromAttributes(), and NtLoadKeyEx().
#define CmpExceptionFilter (x) EXCEPTION_EXECUTE_HANDLER
Definition at line 74 of file ntapi.c.
Referenced by NtCreateKey(), NtNotifyChangeMultipleKeys(), NtOpenKey(), and NtSetValueKey().
#define OBJ_AUDIT_OBJECT_CLOSE 0x00000004L
Definition at line 389 of file ntapi.c.
Referenced by NtDeleteKey(), NtMakeTemporaryObject(), ObAuditInheritedHandleProcedure(), ObAuditObjectAccess(), ObDuplicateObject(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
Function Documentation
PCM_POST_BLOCK CmpAllocatePostBlock (IN POST_BLOCK_TYPE BlockType, IN ULONG PostFlags, IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK MasterBlock)
Definition at line 4581 of file ntapi.c.
References ALLOCATE_WITH_QUOTA, _CM_ASYNC_USER_POST_BLOCK::Apc, ASSERT, _CM_POST_BLOCK_UNION::AsyncKernel, _CM_POST_BLOCK_UNION::AsyncUser, ExFreePool(), FALSE, InitializeListHead(), IsMasterPostBlock, KeInitializeEvent(), _CM_POST_KEY_BODY::KeyBody, _CM_POST_KEY_BODY::KeyBodyList, NonPagedPool, _CM_POST_BLOCK::NotifyType, NULL, PagedPool, POOL_COLD_ALLOCATION, PostAsyncKernel, PostAsyncUser, _CM_POST_BLOCK::PostKeyBody, PostSynchronous, RtlZeroMemory, _CM_POST_BLOCK_UNION::Sync, SynchronizationEvent, _CM_SYNC_POST_BLOCK::SystemEvent, and _CM_POST_BLOCK::u.
VOID CmpDummyApc (struct _KAPC * Apc, PVOID * SystemArgument1, PVOID * SystemArgument2)
Definition at line 120 of file cmnotify.c.
References UNREFERENCED_PARAMETER.
Referenced by NtNotifyChangeMultipleKeys().
VOID CmpFreePostBlock (IN PCM_POST_BLOCK PostBlock)
Definition at line 4496 of file ntapi.c.
References ASSERT, CmKdPrintEx, CML_FLOW, CmpClearListEntry, DPFLTR_CONFIG_ID, ExFreePool(), IsListEmpty, IsMasterPostBlock, ObDereferenceObjectDeferDelete(), PostAsyncKernel, PostAsyncUser, PostBlockType, PostSynchronous, and REG_NOTIFY_MASTER_POST.
Referenced by CmNotifyRunDown(), CmpFreeSlavePost(), CmpNotifyChangeKey(), CmpPostApc(), CmpPostApcRunDown(), CmpPostNotify(), and NtNotifyChangeMultipleKeys().
ULONG CmpKeyInfoProbeAlingment (IN KEY_INFORMATION_CLASS KeyInformationClass)
Definition at line 5216 of file ntapi.c.
References ASSERT, FALSE, KeyBasicInformation, KeyCachedInformation, KeyFlagsInformation, KeyFullInformation, KeyNameInformation, KeyNodeInformation, and PROBE_ALIGNMENT.
Referenced by NtQueryKey().
NTSTATUS CmpNameFromAttributes (IN POBJECT_ATTRIBUTES Attributes, KPROCESSOR_MODE PreviousMode, OUT PUNICODE_STRING FullName)
Definition at line 4337 of file ntapi.c.
References ALLOCATE_WITH_QUOTA, ASSERT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _UNICODE_STRING::Length, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, ObjectNameInformation, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForReadSmallStructure, _OBJECT_ATTRIBUTES::RootDirectory, RtlAppendUnicodeStringToString(), RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_PATH_INVALID, STATUS_OBJECT_PATH_SYNTAX_BAD, STATUS_SUCCESS, UserMode, and ZwQueryObject().
Referenced by NtLoadKeyEx(), and NtReplaceKey().
NTSTATUS NtCompactKeys (__in ULONG Count, __in_ecount(Count) HANDLE KeyArray[])
Definition at line 5248 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_NTAPI, CML_NTAPI_ARGS, CmMoveKey(), CmpLockRegistryExclusive(), CmpUnlockRegistry(), CONTAINING_RECORD, Count, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _CMHIVE::GrowOffset, _CMHIVE::GrowOnlyMode, HBLOCK_SIZE, Hive, KeGetPreviousMode, KEY_WRITE, _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PagedPool, ProbeForRead, SeBackupPrivilege, SeSinglePrivilegeCheck(), Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _HHIVE::Storage, TRUE, and UserMode.
NTSTATUS NtCompressKey (__in HANDLE Key)
Definition at line 5438 of file ntapi.c.
References _HHIVE::BaseBlock, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmCompressKey(), CmKdPrintEx, CML_NTAPI, CmpLockRegistryExclusive(), CmpUnlockRegistry(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, KeGetPreviousMode, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _HBASE_BLOCK::RootCell, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, and STATUS_PRIVILEGE_NOT_HELD.
NTSTATUS NtCreateKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __reserved ULONG TitleIndex, __in_opt PUNICODE_STRING Class, __in ULONG CreateOptions, __out_opt PULONG Disposition)
Definition at line 132 of file ntapi.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpAddKeyTracker, CmpExceptionFilter, _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, DbgPrintEx(), _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, EndWmiCmTrace, except, FALSE, Handle, HookKcbFromHandleForWmiCmTrace, HvShutdownComplete, INVALID_WRITE_OPERATION, KeGetPreviousMode, KernelMode, KEY_WOW64_RES, _UNICODE_STRING::Length, LongToHandle, NT_SUCCESS, NtClose(), NULL, ObDereferenceObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, PO_CLEAN_SHUTDOWN_REGISTRY, PoCleanShutdownEnabled(), _CM_PARSE_CONTEXT::PredefinedHandle, PROBE_ALIGNMENT, ProbeAndReadUnicodeStringEx, ProbeAndZeroHandle, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteUlong, PsGetCurrentProcessId(), PsGetCurrentProcessImageFileName, PsGetCurrentThreadId(), REG_LEGAL_OPTION, REG_OPTION_PREDEF_HANDLE, REGISTRY_ERROR, StartWmiCmTrace, STATUS_INVALID_PARAMETER, STATUS_PREDEFINED_HANDLE, STATUS_SUCCESS, STATUS_TOO_LATE, _CM_PARSE_CONTEXT::TitleIndex, TRUE, _CM_KEY_BODY::Type, UNREFERENCED_PARAMETER, and UserMode.
Referenced by CmInitSystem1(), CmpAddAliasEntry(), CmpCloneControlSet(), CmpCreateControlSet(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpLinkKeyToHive(), CmpSaveBootControlSet(), and CmpSetNetworkValue().
NTSTATUS NtDeleteKey (__in HANDLE KeyHandle)
Definition at line 392 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmDeleteKey(), CmIsKcbReadOnly, CmKdPrintEx, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DELETE, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, _OBJECT_HANDLE_INFORMATION::HandleAttributes, HookKcbForWmiCmTrace, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, _REG_DELETE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, _CM_KEY_CONTROL_BLOCK::ParentKcb, RegNtPostDeleteKey, RegNtPreDeleteKey, SeDeleteObjectAuditAlarm(), StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_SUCCESS, and TRUE.
Referenced by KiMoveRegTree().
NTSTATUS NtDeleteValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName)
Definition at line 499 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmDeleteValueKey(), CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, KeGetPreviousMode, KEY_SET_VALUE, _CM_KEY_BODY::KeyControlBlock, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_DELETE_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUnicodeStringEx, ProbeForRead, RegNtPostDeleteValueKey, RegNtPreDeleteValueKey, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, TRUE, UserMode, and _REG_DELETE_VALUE_KEY_INFORMATION::ValueName.
NTSTATUS NtEnumerateKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 624 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmEnumerateKey(), CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, Index, _REG_ENUMERATE_KEY_INFORMATION::Index, KeGetPreviousMode, KEY_ENUMERATE_SUB_KEYS, KeyBasicInformation, _CM_KEY_BODY::KeyControlBlock, KeyFullInformation, _REG_ENUMERATE_KEY_INFORMATION::KeyInformation, _REG_ENUMERATE_KEY_INFORMATION::KeyInformationClass, KeyNodeInformation, _REG_ENUMERATE_KEY_INFORMATION::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_ENUMERATE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, RegNtPostEnumerateKey, RegNtPreEnumerateKey, _REG_ENUMERATE_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
NTSTATUS NtEnumerateValueKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 786 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmEnumerateValueKey(), CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, Index, _REG_ENUMERATE_VALUE_KEY_INFORMATION::Index, KeGetPreviousMode, KEY_QUERY_VALUE, _CM_KEY_BODY::KeyControlBlock, KeyValueBasicInformation, KeyValueFullInformation, _REG_ENUMERATE_VALUE_KEY_INFORMATION::KeyValueInformation, _REG_ENUMERATE_VALUE_KEY_INFORMATION::KeyValueInformationClass, KeyValuePartialInformation, _REG_ENUMERATE_VALUE_KEY_INFORMATION::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_ENUMERATE_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, RegNtPostEnumerateValueKey, RegNtPreEnumerateValueKey, _REG_ENUMERATE_VALUE_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
NTSTATUS NtFlushKey (__in HANDLE KeyHandle)
Definition at line 950 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmFlushKey(), CmKdPrintEx, CML_NTAPI, CmpLockKCBShared, CmpLockRegistry(), CmpUnlockKCB, CmpUnlockRegistry(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, FALSE, HookKcbForWmiCmTrace, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, StartWmiCmTrace, and STATUS_KEY_DELETED.
Referenced by CmpInterlockedFunction().
NTSTATUS NtInitializeRegistry (__in USHORT BootCondition)
Definition at line 1030 of file ntapi.c.
References CcPfBeginBootPhase(), CM_PAGED_CODE, CmBootAcceptFirstTime, CmFirstTime, CmKdPrintEx, CML_NTAPI, CmpCmdInit(), CmpHoldLazyFlush, CmpLazyFlush(), CmpLockRegistryExclusive(), CmpRaiseSelfHealWarningForSystemHives(), CmpSaveBootControlSet(), CmpSetVersionData(), CmpUnlockRegistry(), DPFLTR_CONFIG_ID, FALSE, HalEndOfBoot, IopCopyBootLogRegistryToFile(), KeGetPreviousMode, PfBootAcceptedRegistryInitPhase, PfSMRegistryInitPhase, PoInitHiberServices(), REG_INIT_BOOT_ACCEPTED_BASE, REG_INIT_BOOT_ACCEPTED_MAX, REG_INIT_BOOT_SETUP, REG_INIT_MAX_VALID_CONDITION, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, UserMode, WmiBootPhase1(), and ZwInitializeRegistry().
NTSTATUS NtLoadKey (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile)
Definition at line 3159 of file ntapi.c.
References NtLoadKeyEx(), and NULL.
NTSTATUS NtLoadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags)
Definition at line 3207 of file ntapi.c.
References NtLoadKeyEx(), and NULL.
NTSTATUS NtLoadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags, __in_opt HANDLE TrustClassKey)
Definition at line 3260 of file ntapi.c.
References ALLOCATE_WITH_QUOTA, ARGUMENT_PRESENT, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmLoadKey(), CmpNameFromAttributes(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), KeEnterCriticalRegion(), KeGetPreviousMode, KeLeaveCriticalRegion(), _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _OBJECT_ATTRIBUTES::ObjectName, ObReferenceObjectByHandle, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForReadSmallStructure, REG_NO_LAZY_FLUSH, RtlCopyMemory, _OBJECT_ATTRIBUTES::SecurityDescriptor, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, and UserMode.
Referenced by NtLoadKey(), and NtLoadKey2().
NTSTATUS NtLockRegistryKey (__in HANDLE KeyHandle)
Definition at line 5510 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmLockKcbForWrite(), CmpLockRegistry(), CmpUnlockRegistry(), END_LOCK_CHECKPOINT, KeGetPreviousMode, KernelMode, KEY_WRITE, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), and STATUS_PRIVILEGE_NOT_HELD.
NTSTATUS NtNotifyChangeKey (__in HANDLE KeyHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
Definition at line 1219 of file ntapi.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_NTAPI, DPFLTR_CONFIG_ID, NtNotifyChangeMultipleKeys(), and NULL.
NTSTATUS NtNotifyChangeMultipleKeys (__in HANDLE MasterKeyHandle, __in_opt ULONG Count, __in_ecount_opt(Count) OBJECT_ATTRIBUTES SlaveObjects[], __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
Definition at line 1375 of file ntapi.c.
References _CM_ASYNC_USER_POST_BLOCK::Apc, APC_LEVEL, ARGUMENT_PRESENT, ASSERT, _CM_POST_BLOCK_UNION::AsyncKernel, _CM_POST_BLOCK_UNION::AsyncUser, _OBJECT_ATTRIBUTES::Attributes, BAD_NOTIFY_CONTEXT, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmLockHive, CmpAllocateMasterPostBlock, CmpAllocateSlavePostBlock, CmpDummyApc(), CmpExceptionFilter, CmpFreePostBlock(), CmpLockRegistry(), CmpLockTwoHashEntriesShared(), CmpNotifyChangeKey(), CmpPostApc(), CmpPostApcRunDown(), CmpRemoveEntryList, CmpSetIoStatus, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CmUnlockHive, _CM_KEY_CONTROL_BLOCK::ConvKey, CurrentApcEnvironment, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, _CM_ASYNC_KERNEL_POST_BLOCK::Event, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, _LIST_ENTRY::Flink, HvShutdownComplete, _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, KeClearEvent(), KeGetCurrentThread(), KeGetPreviousMode, KeInitializeApc(), KeIsAttachedProcess(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), KEY_NOTIFY, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, LOCK_POST_LIST, _CM_POST_BLOCK::NotifyList, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, PostAsyncKernel, PostAsyncUser, PostSynchronous, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWrite(), PsGetCurrentProcess(), _CM_ASYNC_KERNEL_POST_BLOCK::QueueType, REG_LEGAL_CHANGE_FILTER, REGISTRY_ERROR, _CM_SYNC_POST_BLOCK::Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PENDING, STATUS_SUCCESS, STATUS_TOO_LATE, STATUS_UNSUCCESSFUL, STATUS_USER_APC, _CM_POST_BLOCK_UNION::Sync, _CM_SYNC_POST_BLOCK::SystemEvent, _CM_POST_BLOCK::ThreadList, TRUE, _CM_POST_BLOCK::u, UNLOCK_POST_LIST, _CM_ASYNC_USER_POST_BLOCK::UserEvent, UserMode, _CM_ASYNC_KERNEL_POST_BLOCK::WorkItem, and ZwClose().
Referenced by NtNotifyChangeKey().
NTSTATUS NtOpenKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 2028 of file ntapi.c.
References _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpAddKeyTracker, CmpExceptionFilter, _CM_PARSE_CONTEXT::CreateOperation, DPFLTR_CONFIG_ID, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, FALSE, Handle, HookKcbFromHandleForWmiCmTrace, HvShutdownComplete, KeGetPreviousMode, KernelMode, KEY_WOW64_RES, _UNICODE_STRING::Length, LongToHandle, NT_SUCCESS, NtClose(), NULL, ObDereferenceObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, PROBE_ALIGNMENT, ProbeAndReadUnicodeStringEx, ProbeAndZeroHandle, ProbeForRead, ProbeForReadSmallStructure, RtlZeroMemory, StartWmiCmTrace, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PREDEFINED_HANDLE, STATUS_SUCCESS, STATUS_TOO_LATE, TRUE, _CM_KEY_BODY::Type, and UserMode.
Referenced by CmGetSystemDriverList(), CmpAddAliasEntry(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreatePerfKeys(), CmpInterlockedFunction(), CmpSaveBootControlSet(), CmpSetSystemValues(), and SepAdtInitializePrivilegeAuditing().
NTSTATUS NtQueryKey (__in HANDLE KeyHandle, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 2189 of file ntapi.c.
References CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CmpCallCallBacks(), CmpKeyInfoProbeAlingment(), CmPostCallbackNotification, CmQueryKey(), DPFLTR_CONFIG_ID, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, _OBJECT_HANDLE_INFORMATION::GrantedAccess, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, KeGetPreviousMode, KEY_QUERY_VALUE, KeyBasicInformation, KeyCachedInformation, _CM_KEY_BODY::KeyControlBlock, KeyFlagsInformation, KeyFullInformation, _REG_QUERY_KEY_INFORMATION::KeyInformation, _REG_QUERY_KEY_INFORMATION::KeyInformationClass, KeyNameInformation, KeyNodeInformation, _REG_QUERY_KEY_INFORMATION::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_QUERY_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, RegNtPostQueryKey, RegNtPreQueryKey, _REG_QUERY_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
Referenced by IopLoadDriver().
NTSYSAPI NTSTATUS NTAPI NtQueryMultipleValueKey (__in HANDLE KeyHandle, __inout_ecount(EntryCount) PKEY_VALUE_ENTRY ValueEntries, __in ULONG EntryCount, __out_bcount *BufferLength PVOID ValueBuffer, __inout PULONG BufferLength, __out_opt PULONG RequiredBufferLength)
Definition at line 4191 of file ntapi.c.
References ARGUMENT_PRESENT, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::BufferLength, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, CmQueryMultipleValueKey(), DPFLTR_CONFIG_ID, EndWmiCmTrace, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::EntryCount, except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), HookKcbForWmiCmTrace, KeGetPreviousMode, KEY_QUERY_VALUE, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUlong, ProbeForWrite(), ProbeForWriteUlong, RegNtPostQueryMultipleValueKey, RegNtPreQueryMultipleValueKey, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::RequiredBufferLength, StartWmiCmTrace, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, UserMode, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::ValueBuffer, and _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::ValueEntries.
NTSTATUS NtQueryOpenSubKeys (__in POBJECT_ATTRIBUTES TargetKey, __out PULONG HandleCount)
Definition at line 4750 of file ntapi.c.
References _OBJECT_ATTRIBUTES::Attributes, _HHIVE::BaseBlock, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpLockRegistry(), CmpLockTwoHashEntriesExclusive(), CmpOpenSubKeys, CmpSearchForOpenSubKeys(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), _CM_KEY_CONTROL_BLOCK::ConvKey, DbgPrintEx(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBASE_BLOCK::FileName, Hive, KeGetPreviousMode, KernelMode, KEY_READ, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_KEY_CONTROL_BLOCK::ParentKcb, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWriteUlong, _HBASE_BLOCK::RootCell, RtlInitUnicodeString(), SearchAndCount, Status, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, UserMode, and ZwClose().
NTSTATUS NtQueryOpenSubKeysEx (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG BufferLength, __out_bcount(BufferLength) PVOID Buffer, __out PULONG RequiredSize)
Definition at line 4905 of file ntapi.c.
References _OBJECT_ATTRIBUTES::Attributes, _HHIVE::BaseBlock, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, _QUERY_OPEN_SUBKEYS_CONTEXT::Buffer, _QUERY_OPEN_SUBKEYS_CONTEXT::BufferLength, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpLockRegistry(), CmpLockTwoHashEntriesExclusive(), CmpSearchForOpenSubKeys(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), _CM_KEY_CONTROL_BLOCK::ConvKey, _QUERY_OPEN_SUBKEYS_CONTEXT::CurrentNameBuffer, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, Hive, KeGetPreviousMode, KernelMode, KEY_READ, _QUERY_OPEN_SUBKEYS_CONTEXT::KeyBodyToIgnore, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_KEY_CONTROL_BLOCK::ParentKcb, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWrite(), ProbeForWriteUlong, _QUERY_OPEN_SUBKEYS_CONTEXT::RequiredSize, _HBASE_BLOCK::RootCell, SearchAndCount, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _QUERY_OPEN_SUBKEYS_CONTEXT::StatusCode, _QUERY_OPEN_SUBKEYS_CONTEXT::UsedLength, UserMode, and ZwClose().
NTSTATUS NtQueryValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 2370 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, CmQueryValueKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, KeGetPreviousMode, KEY_QUERY_VALUE, _CM_KEY_BODY::KeyControlBlock, KeyValueBasicInformation, KeyValueFullInformation, KeyValueFullInformationAlign64, _REG_QUERY_VALUE_KEY_INFORMATION::KeyValueInformation, _REG_QUERY_VALUE_KEY_INFORMATION::KeyValueInformationClass, KeyValuePartialInformation, KeyValuePartialInformationAlign64, _REG_QUERY_VALUE_KEY_INFORMATION::Length, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_QUERY_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWriteUlong, RegNtPostQueryValueKey, RegNtPreQueryValueKey, _REG_QUERY_VALUE_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_INVALID_PARAMETER, TRUE, UNICODE_NULL, UserMode, and _REG_QUERY_VALUE_KEY_INFORMATION::ValueName.
Referenced by CmpCreateControlSet(), CmpInterlockedFunction(), IoInitSystem(), IopLoadDriver(), and SepAdtInitializePrivilegeAuditing().
NTSTATUS NtRenameKey (__in HANDLE KeyHandle, __in PUNICODE_STRING NewName)
Definition at line 5084 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmpFlushNotifiesOnKeyBodyList(), CmpLockRegistryExclusive(), CmPostCallbackNotification, CmpUnlockRegistry(), CmRenameKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KEY_WRITE, _CM_KEY_BODY::KeyControlBlock, _UNICODE_STRING::Length, _REG_RENAME_KEY_INFORMATION::NewName, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_NAME_PATH_SEPARATOR, _REG_RENAME_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUnicodeString, ProbeForRead, REG_MAX_KEY_NAME_LENGTH, RegNtPostRenameKey, RegNtPreRenameKey, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
NTSTATUS NtReplaceKey (__in POBJECT_ATTRIBUTES NewFile, __in HANDLE TargetHandle, __in POBJECT_ATTRIBUTES OldFile)
Definition at line 4068 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmIsKcbReadOnly, CmKdPrintEx, CML_NTAPI, CML_NTAPI_ARGS, CmpNameFromAttributes(), CmReplaceKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, ExFreePool(), KeEnterCriticalRegion(), KeGetPreviousMode, KeLeaveCriticalRegion(), _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, and STATUS_PRIVILEGE_NOT_HELD.
NTSTATUS NtRestoreKey (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Flags)
Definition at line 2555 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmIsKcbReadOnly, CmKdPrintEx, CML_NTAPI, CmRestoreKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeRestorePrivilege, SeSinglePrivilegeCheck(), STATUS_ACCESS_DENIED, STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwRestoreKey().
NTSTATUS NtSaveKey (__in HANDLE KeyHandle, __in HANDLE FileHandle)
Definition at line 2679 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmKdPrintEx, CML_NTAPI, CmSaveKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, HSYS_MINOR, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwSaveKey().
NTSTATUS NtSaveKeyEx (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Format)
Definition at line 2764 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmDumpKey(), CmKdPrintEx, CML_NTAPI, CmSaveKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, HSYS_MINOR, HSYS_WHISTLER, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, REG_LATEST_FORMAT, REG_NO_COMPRESSION, REG_STANDARD_FORMAT, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwSaveKeyEx().
NTSTATUS NtSaveMergedKeys (__in HANDLE HighPrecedenceKeyHandle, __in HANDLE LowPrecedenceKeyHandle, __in HANDLE FileHandle)
Definition at line 2871 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmKdPrintEx, CML_NTAPI, CmSaveMergedKeys(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwSaveMergedKeys().
NTSTATUS NtSetInformationKey (__in HANDLE KeyHandle, __in KEY_SET_INFORMATION_CLASS KeySetInformationClass, __in_bcount(KeySetInformationLength) PVOID KeySetInformation, __in ULONG KeySetInformationLength)
Definition at line 3894 of file ntapi.c.
References ASSERT, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, KeGetPreviousMode, KEY_SET_VALUE, _CM_KEY_BODY::KeyControlBlock, _REG_SET_INFORMATION_KEY_INFORMATION::KeySetInformation, _REG_SET_INFORMATION_KEY_INFORMATION::KeySetInformationClass, _REG_SET_INFORMATION_KEY_INFORMATION::KeySetInformationLength, KeyUserFlagsInformation, KeyWriteTimeInformation, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_SET_INFORMATION_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadLargeInteger, ProbeAndReadUlong, RegNtPostSetInformationKey, RegNtPreSetInformationKey, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_UNSUCCESSFUL, TRUE, and UserMode.
NTSTATUS NtSetValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in_opt ULONG TitleIndex, __in ULONG Type, __in_bcount_opt(DataSize) PVOID Data, __in ULONG DataSize)
Definition at line 2976 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmpExceptionFilter, CmPostCallbackNotification, CmSetValueKey(), _REG_SET_VALUE_KEY_INFORMATION::Data, _REG_SET_VALUE_KEY_INFORMATION::DataSize, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, ExAllocatePoolWithQuotaTag, except, ExFreePool(), HookKcbForWmiCmTrace, KeGetPreviousMode, KEY_SET_VALUE, _CM_KEY_BODY::KeyControlBlock, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_SET_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, REG_MAX_KEY_VALUE_NAME_LENGTH, RegNtPostSetValueKey, RegNtPreSetValueKey, RtlCopyMemory, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _REG_SET_VALUE_KEY_INFORMATION::TitleIndex, TRUE, _REG_SET_VALUE_KEY_INFORMATION::Type, UNICODE_NULL, UserMode, and _REG_SET_VALUE_KEY_INFORMATION::ValueName.
Referenced by CmpAddAliasEntry(), CmpAddDockingInfo(), CmpCreateControlSet(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpLinkKeyToHive(), CmpSetNetworkValue(), CmpSetSystemValues(), and IopStoreSystemPartitionInformation().
NTSTATUS NtUnloadKey (__in POBJECT_ATTRIBUTES TargetKey)
Definition at line 3466 of file ntapi.c.
References NtUnloadKey2().
Referenced by CmpDeleteCloneTree().
NTSTATUS NtUnloadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG Flags)
Definition at line 3504 of file ntapi.c.
References ASSERT, _OBJECT_ATTRIBUTES::Attributes, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CM_PAGED_CODE, CM_UNLOAD_KCB_LOCKED, CM_UNLOAD_REG_LOCKED_EX, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpFlushNotify(), CmpLockRegistry(), CmpLockRegistryExclusive(), CmpLockTwoHashEntriesExclusive(), CmpReportNotify(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CmUnloadKey(), _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _CM_KEY_CONTROL_BLOCK::Delete, _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, IsHiveFrozen, KeGetPreviousMode, KernelMode, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, LOCK_HIVE_LOAD, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_PARSE_CONTEXT::PredefinedHandle, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, REG_FORCE_UNLOAD, REG_NOTIFY_CHANGE_LAST_SET, REG_OPTION_BACKUP_RESTORE, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_CANNOT_DELETE, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_TOO_LATE, _CM_PARSE_CONTEXT::TitleIndex, TRUE, UNLOCK_HIVE_LOAD, UserMode, and ZwClose().
Referenced by NtUnloadKey().
NTSTATUS NtUnloadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in_opt HANDLE Event)
Definition at line 3710 of file ntapi.c.
References ARGUMENT_PRESENT, _OBJECT_ATTRIBUTES::Attributes, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CM_PAGED_CODE, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpFlushNotify(), CmpLockRegistryExclusive(), CmpReportNotify(), CmpUnlockRegistry(), CmUnloadKeyEx(), _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _CM_KEY_CONTROL_BLOCK::Delete, _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeClearEvent(), KeGetPreviousMode, KernelMode, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, _CM_PARSE_CONTEXT::PredefinedHandle, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, REG_NOTIFY_CHANGE_LAST_SET, REG_OPTION_BACKUP_RESTORE, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_KEY_DELETED, STATUS_PENDING, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _CM_PARSE_CONTEXT::TitleIndex, TRUE, UserMode, and ZwClose().
Variable Documentation
BOOLEAN CmBootAcceptFirstTime
Definition at line 356 of file cmdat.c.
Referenced by NtInitializeRegistry().
BOOLEAN CmFirstTime
Definition at line 342 of file cmdat.c.
Referenced by NtInitializeRegistry().
BOOLEAN CmpCannotWriteConfiguration
Definition at line 52 of file cmdat2.c.
BOOLEAN CmpHoldLazyFlush
Definition at line 66 of file cmworker.c.
Referenced by CmpEnableLazyFlushDpcRoutine(), CmpLazyFlush(), CmpLazyFlushDpcRoutine(), CmpLazyFlushWorker(), CmSetLazyFlushState(), and NtInitializeRegistry().
POBJECT_TYPE CmpKeyObjectType
Definition at line 320 of file cmdat.c.
Referenced by CmLoadKey(), CmpCheckCreateAccess(), CmpCheckKeyAccess(), CmpCheckNotifyAccess(), CmpDoCreateChild(), CmpDoOpen(), CmpIsHiveAlreadyLoaded(), and CmpParseKey().
ULONG CmpOpenSubKeys
Definition at line 4747 of file ntapi.c.
Referenced by NtQueryOpenSubKeys().
BOOLEAN CmpTraceFlag
POBJECT_TYPE ExEventObjectType
Definition at line 32 of file event.c.
Referenced by BuildQueryDirectoryIrp(), IoCreateNotificationEvent(), IoCreateSynchronizationEvent(), IoInitSystem(), IopXxxControlFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
PCM_KEY_BODY ExpControlKey[2]
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by NtCreateKey(), NtNotifyChangeMultipleKeys(), and NtOpenKey().