Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/fsrtlpc.c File Reference
fsrtlpc.c File Reference
#include "FsRtlP.h"
Macros
#define _FAT_ FSRTL_FAT_LEGAL
#define _HPFS_ FSRTL_HPFS_LEGAL
#define _NTFS_ FSRTL_NTFS_LEGAL
#define _OLE_ FSRTL_OLE_LEGAL
#define _WILD_ FSRTL_WILD_CHARACTER
#define COMPATIBILITY_MODE_KEY_NAME L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\FileSystem"
#define COMPATIBILITY_MODE_VALUE_NAME L"Win95TruncatedExtensions"
#define FSRTL_NUMBER_OF_RESOURCES (16)
#define KEY_WORK_AREA
Functions
PERESOURCE FsRtlAllocateResource ()
NTSTATUS FsRtlGetCompatibilityModeValue (IN PUNICODE_STRING ValueName, IN OUT PULONG Value)
BOOLEAN FsRtlInitSystem ()
Variables
UCHAR const *const FsRtlLegalAnsiCharacterArray = &LocalLegalAnsiCharacterArray[0]
PERESOURCE FsRtlPagingIoResources
ULONG FsRtlPagingIoResourceSelector = 0
BOOLEAN FsRtlSafeExtensions = TRUE
static const UCHAR LocalLegalAnsiCharacterArray [128]
Macro Definition Documentation
#define _FAT_ FSRTL_FAT_LEGAL
Definition at line 74 of file fsrtlpc.c.
#define _HPFS_ FSRTL_HPFS_LEGAL
Definition at line 75 of file fsrtlpc.c.
#define _NTFS_ FSRTL_NTFS_LEGAL
Definition at line 76 of file fsrtlpc.c.
#define _OLE_ FSRTL_OLE_LEGAL
Definition at line 77 of file fsrtlpc.c.
#define _WILD_ FSRTL_WILD_CHARACTER
Definition at line 78 of file fsrtlpc.c.
#define COMPATIBILITY_MODE_KEY_NAME L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\FileSystem"
Definition at line 21 of file fsrtlpc.c.
Referenced by FsRtlGetCompatibilityModeValue().
#define COMPATIBILITY_MODE_VALUE_NAME L"Win95TruncatedExtensions"
Definition at line 22 of file fsrtlpc.c.
Referenced by FsRtlInitSystem().
#define FSRTL_NUMBER_OF_RESOURCES (16)
Definition at line 55 of file fsrtlpc.c.
Referenced by FsRtlAllocateResource(), and FsRtlInitSystem().
#define KEY_WORK_AREA
Value:
((sizeof(KEY_VALUE_FULL_INFORMATION) + \
                        sizeof(ULONG)) + 64)
Definition at line 24 of file fsrtlpc.c.
Referenced by FsRtlGetCompatibilityModeValue().
Function Documentation
PERESOURCE FsRtlAllocateResource ()
Definition at line 306 of file fsrtlpc.c.
References FSRTL_NUMBER_OF_RESOURCES, FsRtlPagingIoResourceSelector, and PAGED_CODE.
NTSTATUS FsRtlGetCompatibilityModeValue (IN PUNICODE_STRING ValueName, IN OUT PULONG Value)
Definition at line 336 of file fsrtlpc.c.
References ASSERT, _UNICODE_STRING::Buffer, COMPATIBILITY_MODE_KEY_NAME, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, ExAllocatePoolWithTag, ExFreePool(), Handle, InitializeObjectAttributes, KEY_READ, KEY_WORK_AREA, KeyName, KeyValueFullInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, PagedPool, Status, STATUS_BUFFER_OVERFLOW, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by FsRtlInitSystem().
BOOLEAN FsRtlInitSystem ()
Definition at line 219 of file fsrtlpc.c.
References _UNICODE_STRING::Buffer, COMPATIBILITY_MODE_VALUE_NAME, ExInitializeResourceLite(), FALSE, FsFilterInit(), FSRTL_NUMBER_OF_RESOURCES, FsRtlAllocatePool, FsRtlGetCompatibilityModeValue(), FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcbs(), FsRtlInitializeTunnels(), FsRtlInitializeWorkerThread(), FsRtlpUncSemaphore, FsRtlSafeExtensions, KeInitializeSemaphore(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MAXLONG, NonPagedPool, NT_SUCCESS, PAGED_CODE, and TRUE.
Referenced by Phase1InitializationDiscard().
Variable Documentation
UCHAR const* const FsRtlLegalAnsiCharacterArray = &LocalLegalAnsiCharacterArray[0]
Definition at line 212 of file fsrtlpc.c.
PERESOURCE FsRtlPagingIoResources
Definition at line 57 of file fsrtlpc.c.
ULONG FsRtlPagingIoResourceSelector = 0
Definition at line 62 of file fsrtlpc.c.
Referenced by FsRtlAllocateResource().
BOOLEAN FsRtlSafeExtensions = TRUE
Definition at line 63 of file fsrtlpc.c.
Referenced by FsRtlInitSystem().
const UCHAR LocalLegalAnsiCharacterArray[128] static
Definition at line 80 of file fsrtlpc.c.