Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/luid.c File Reference
luid.c File Reference
#include "exp.h"
Functions
BOOLEAN ExLuidInitialization (VOID)
NTSTATUS NtAllocateLocallyUniqueId (__out PLUID Luid)
Variables
LARGE_INTEGER ExpLuid = {1001,0}
const LARGE_INTEGER ExpLuidIncrement = {1,0}
Function Documentation
BOOLEAN ExLuidInitialization (VOID)
Definition at line 37 of file luid.c.
References TRUE.
Referenced by SepInitializationPhase0().
NTSTATUS NtAllocateLocallyUniqueId (__out PLUID Luid)
Definition at line 67 of file luid.c.
References ExAllocateLocallyUniqueId(), except, ExSystemExceptionFilter(), KeGetPreviousMode, KernelMode, ProbeForWriteSmallStructure(), and STATUS_SUCCESS.
Variable Documentation
LARGE_INTEGER ExpLuid = {1001,0}
Definition at line 30 of file luid.c.
const LARGE_INTEGER ExpLuidIncrement = {1,0}
Definition at line 31 of file luid.c.