Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/gentable.c File Reference
gentable.c File Reference
#include <nt.h>
#include <ntrtl.h>
Data Structures
struct _TABLE_ENTRY_HEADER
Typedefs
typedef struct _TABLE_ENTRY_HEADER * PTABLE_ENTRY_HEADER
typedef struct _TABLE_ENTRY_HEADER TABLE_ENTRY_HEADER
Functions
static TABLE_SEARCH_RESULT FindNodeOrParent (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer, OUT PRTL_SPLAY_LINKS *NodeOrParent)
BOOLEAN RtlDeleteElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer)
PVOID RtlEnumerateGenericTable (IN PRTL_GENERIC_TABLE Table, IN BOOLEAN Restart)
PVOID RtlEnumerateGenericTableWithoutSplaying (IN PRTL_GENERIC_TABLE Table, IN PVOID *RestartKey)
PVOID RtlGetElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN ULONG I)
VOID RtlInitializeGenericTable (IN PRTL_GENERIC_TABLE Table, IN PRTL_GENERIC_COMPARE_ROUTINE CompareRoutine, IN PRTL_GENERIC_ALLOCATE_ROUTINE AllocateRoutine, IN PRTL_GENERIC_FREE_ROUTINE FreeRoutine, IN PVOID TableContext)
PVOID RtlInsertElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL)
PVOID RtlInsertElementGenericTableFull (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL, PVOID NodeOrParent, TABLE_SEARCH_RESULT SearchResult)
BOOLEAN RtlIsGenericTableEmpty (IN PRTL_GENERIC_TABLE Table)
PVOID RtlLookupElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer)
PVOID NTAPI RtlLookupElementGenericTableFull (PRTL_GENERIC_TABLE Table, PVOID Buffer, OUT PVOID *NodeOrParent, OUT TABLE_SEARCH_RESULT *SearchResult)
ULONG RtlNumberGenericTableElements (IN PRTL_GENERIC_TABLE Table)
Typedef Documentation
typedef struct _TABLE_ENTRY_HEADER * PTABLE_ENTRY_HEADER
typedef struct _TABLE_ENTRY_HEADER TABLE_ENTRY_HEADER
Function Documentation
static TABLE_SEARCH_RESULT FindNodeOrParent (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer, OUT PRTL_SPLAY_LINKS * NodeOrParent) static
Definition at line 54 of file gentable.c.
References ASSERT, GenericEqual, GenericGreaterThan, GenericLessThan, RtlIsGenericTableEmpty(), RtlLeftChild, RtlRightChild, TableEmptyTree, TableFoundNode, TableInsertAsLeft, TableInsertAsRight, and TRUE.
Referenced by RtlDeleteElementGenericTable(), RtlInsertElementGenericTable(), and RtlLookupElementGenericTableFull().
BOOLEAN RtlDeleteElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer)
Definition at line 522 of file gentable.c.
References FALSE, FindNodeOrParent(), RemoveEntryList(), RtlDelete(), TableEmptyTree, TableFoundNode, and TRUE.
PVOID RtlEnumerateGenericTable (IN PRTL_GENERIC_TABLE Table, IN BOOLEAN Restart)
Definition at line 728 of file gentable.c.
References NULL, RtlIsGenericTableEmpty(), RtlLeftChild, RtlRealSuccessor(), and RtlSplay().
PVOID RtlEnumerateGenericTableWithoutSplaying (IN PRTL_GENERIC_TABLE Table, IN PVOID * RestartKey)
Definition at line 1100 of file gentable.c.
References NULL, RtlIsGenericTableEmpty(), RtlLeftChild, and RtlRealSuccessor().
PVOID RtlGetElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN ULONG I)
Definition at line 874 of file gentable.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _LIST_ENTRY::Flink, MAXULONG, and NULL.
VOID RtlInitializeGenericTable (IN PRTL_GENERIC_TABLE Table, IN PRTL_GENERIC_COMPARE_ROUTINE CompareRoutine, IN PRTL_GENERIC_ALLOCATE_ROUTINE AllocateRoutine, IN PRTL_GENERIC_FREE_ROUTINE FreeRoutine, IN PVOID TableContext)
Definition at line 203 of file gentable.c.
References InitializeListHead(), and NULL.
PVOID RtlInsertElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL)
Definition at line 261 of file gentable.c.
References FindNodeOrParent(), and RtlInsertElementGenericTableFull().
PVOID RtlInsertElementGenericTableFull (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL, PVOID NodeOrParent, TABLE_SEARCH_RESULT SearchResult)
Definition at line 347 of file gentable.c.
References ARGUMENT_PRESENT, ASSERT, FALSE, FIELD_OFFSET, InsertTailList(), MAXULONG, NULL, RtlCopyMemory, RtlInitializeSplayLinks, RtlInsertAsLeftChild, RtlInsertAsRightChild, RtlSplay(), TableEmptyTree, TableFoundNode, TableInsertAsLeft, and TRUE.
Referenced by RtlInsertElementGenericTable().
BOOLEAN RtlIsGenericTableEmpty (IN PRTL_GENERIC_TABLE Table)
Definition at line 841 of file gentable.c.
References FALSE, and TRUE.
Referenced by FindNodeOrParent(), RtlEnumerateGenericTable(), and RtlEnumerateGenericTableWithoutSplaying().
PVOID RtlLookupElementGenericTable (IN PRTL_GENERIC_TABLE Table, IN PVOID Buffer)
Definition at line 609 of file gentable.c.
References RtlLookupElementGenericTableFull().
PVOID NTAPI RtlLookupElementGenericTableFull (PRTL_GENERIC_TABLE Table, PVOID Buffer, OUT PVOID * NodeOrParent, OUT TABLE_SEARCH_RESULT * SearchResult)
Definition at line 659 of file gentable.c.
References FindNodeOrParent(), NULL, RtlSplay(), TableEmptyTree, TableFoundNode, and _RTL_GENERIC_TABLE::TableRoot.
Referenced by RtlLookupElementGenericTable().
ULONG RtlNumberGenericTableElements (IN PRTL_GENERIC_TABLE Table)
Definition at line 1069 of file gentable.c.