Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/traceapi.c File Reference
traceapi.c File Reference
#include "wmikmp.h"
#include <ntos.h>
#include <evntrace.h>
#include <wmi.h>
#include "tracep.h"
Functions
NTSYSCALLAPI NTSTATUS NTAPI NtTraceEvent (__in HANDLE TraceHandle, __in ULONG Flags, __in ULONG FieldSize, __in PVOID Fields)
NTKERNELAPI NTSTATUS WmiFlushTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTKERNELAPI LONG64 FASTCALL WmiGetClock (IN WMI_CLOCK_TYPE ClockType, IN PVOID Context)
NTKERNELAPI NTSTATUS FASTCALL WmiGetClockType (IN TRACEHANDLE LoggerHandle, OUT WMI_CLOCK_TYPE *ClockType)
NTKERNELAPI NTSTATUS WmiQueryTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTKERNELAPI NTSTATUS WmiQueryTraceInformation (IN TRACE_INFORMATION_CLASS TraceInformationClass, OUT PVOID TraceInformation, IN ULONG TraceInformationLength, OUT PULONG RequiredLength OPTIONAL, IN PVOID Buffer OPTIONAL)
NTKERNELAPI NTSTATUS WmiSetMark (IN PWMI_SET_MARK_INFORMATION MarkInfo, IN ULONG InBufferLen)
NTKERNELAPI NTSTATUS WmiSetTraceBufferCallback (IN TRACEHANDLE TraceHandle, IN WMI_TRACE_BUFFER_CALLBACK Callback, IN PVOID Context)
NTKERNELAPI NTSTATUS WmiStartTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
NTKERNELAPI NTSTATUS WmiStopTrace (IN PWMI_LOGGER_INFORMATION LoggerInfo)
NTKERNELAPI NTSTATUS FASTCALL WmiTraceEvent (IN PWNODE_HEADER Wnode, IN KPROCESSOR_MODE RequestorMode)
NTKERNELAPI NTSTATUS FASTCALL WmiTraceFastEvent (IN PWNODE_HEADER Wnode)
NTKERNELAPI NTSTATUS WmiTraceKernelEvent (IN ULONG GroupType, IN PVOID EventInfo, IN ULONG EventInfoLen, IN PETHREAD Thread)
NTKERNELAPI NTSTATUS WmiTraceMessage (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber,...)
NTSTATUS WmiTraceMessageVa (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, va_list MessageArgList)
NTKERNELAPI NTSTATUS FASTCALL WmiTraceUserMessage (IN PMESSAGE_TRACE_USER pMessage, IN ULONG MessageSize)
NTKERNELAPI NTSTATUS WmiUpdateTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Variables
SIZE_T MmMaximumNonPagedPoolInBytes
Function Documentation
NTSYSCALLAPI NTSTATUS NTAPI NtTraceEvent (__in HANDLE TraceHandle, __in ULONG Flags, __in ULONG FieldSize, __in PVOID Fields)
Definition at line 1034 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::CollectionOn, ETW_NT_FLAGS_TRACE_HEADER, ETW_NT_FLAGS_TRACE_MESSAGE, _WMI_LOGGER_CONTEXT::EventsLost, except, EXCEPTION_EXECUTE_HANDLER, FIELD_OFFSET, _WNODE_HEADER::HistoricalContext, InterlockedDecrement, KeGetPreviousMode, MAXLOGGERS, NULL, ProbeForRead, Status, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_UNSUCCESSFUL, TraceDebug, WmiGetLoggerId, WmipAllocateFreeBuffers(), WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, WmipReferenceLogger, WmiTraceEvent(), and WmiTraceMessage().
NTKERNELAPI NTSTATUS WmiFlushTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 775 of file traceapi.c.
References EtwpDefaultTraceSecurityDescriptor, _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedDecrement, _WMI_LOGGER_CONTEXT::KernelTraceOn, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMode, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::MutexCount, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, TraceDebug, TRUE, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipFlushLogger(), WmipQueryLogger(), WmipReleaseMutex, and WmipVerifyLoggerInfo().
Referenced by WmipIoControl(), and WmiStartTrace().
NTKERNELAPI LONG64 FASTCALL WmiGetClock (IN WMI_CLOCK_TYPE ClockType, IN PVOID Context)
Definition at line 952 of file traceapi.c.
References _LARGE_INTEGER::HighPart, KeQueryRuntimeProcess(), KeQuerySystemTime(), _KTHREAD::KernelTime, _LARGE_INTEGER::LowPart, NULL, ObDereferenceObject(), ObReferenceObject, _EPROCESS::Pcb, PerfGetCycleCount(), PsGetCurrentProcess(), PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _ETHREAD::Tcb, _KTHREAD::UserTime, WMICT_CPUCYCLE, WMICT_DEFAULT, WMICT_PERFCOUNTER, WMICT_PROCESS, WMICT_SYSTEMTIME, WMICT_THREAD, WmipGetPerfCounter(), and WmipGetSystemTime().
NTKERNELAPI NTSTATUS FASTCALL WmiGetClockType (IN TRACEHANDLE LoggerHandle, OUT WMI_CLOCK_TYPE * ClockType)
Definition at line 880 of file traceapi.c.
References EVENT_TRACE_CLOCK_CPUCYCLE, EVENT_TRACE_CLOCK_PERFCOUNTER, MAXLOGGERS, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TraceDebug, _WMI_LOGGER_CONTEXT::UsePerfClock, WMICT_CPUCYCLE, WMICT_PERFCOUNTER, WMICT_SYSTEMTIME, WmiGetLoggerId, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, and WmipReferenceLogger.
NTKERNELAPI NTSTATUS WmiQueryTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 128 of file traceapi.c.
References NULL, PAGED_CODE, STATUS_INVALID_PARAMETER, and WmipQueryLogger().
Referenced by WmiQueryTraceInformation().
NTKERNELAPI NTSTATUS WmiQueryTraceInformation (IN TRACE_INFORMATION_CLASS TraceInformationClass, OUT PVOID TraceInformation, IN ULONG TraceInformationLength, OUT PULONG RequiredLength OPTIONAL, IN PVOID Buffer OPTIONAL)
Definition at line 2172 of file traceapi.c.
References AllLoggerHandlesClass, ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _WNODE_HEADER::BufferSize, EventLoggerHandleClass, except, EXCEPTION_EXECUTE_HANDLER, _WNODE_HEADER::Flags, GlobalLoggerHandleClass, _WNODE_HEADER::HistoricalContext, _UNICODE_STRING::Length, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_INFORMATION::LoggerName, MAXLOGGERS, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_HANDLE, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_MIX, STATUS_MORE_ENTRIES, STATUS_NOT_FOUND, STATUS_SUCCESS, TraceEnableFlagsClass, TraceEnableLevelClass, TraceHandleByNameClass, TraceHandleClass, TraceIdClass, WmiGetLoggerEnableFlags, WmiGetLoggerEnableLevel, WmiGetLoggerId, WmipDereferenceLogger, WmipEventLogger, WmipIsValidLogger, WmipLoggerContext, WmipReferenceLogger, WmiQueryTrace(), WmiSetLoggerId, _WMI_LOGGER_INFORMATION::Wnode, and WNODE_FLAG_TRACED_GUID.
NTKERNELAPI NTSTATUS WmiSetMark (IN PWMI_SET_MARK_INFORMATION MarkInfo, IN ULONG InBufferLen)
Definition at line 2037 of file traceapi.c.
References FIELD_OFFSET, MmEmptyAllWorkingSets(), MmPerfSnapShotValidPhysicalMemory(), NT_SUCCESS, PERF_FINISH_HOOK, PERF_FOOTPRINT, PERFINFO_HOOK_HANDLE_TO_DATA, PERFINFO_IS_ANY_GROUP_ON, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_MARK, PerfInfoReserveBytes(), RtlCopyMemory, Status, STATUS_WMI_SET_FAILURE, UNICODE_NULL, and WMI_SET_MARK_WITH_FLUSH.
Referenced by WmipIoControl().
NTKERNELAPI NTSTATUS WmiSetTraceBufferCallback (IN TRACEHANDLE TraceHandle, IN WMI_TRACE_BUFFER_CALLBACK Callback, IN PVOID Context)
Definition at line 2098 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::BufferCallback, _WMI_LOGGER_CONTEXT::CallbackContext, KERNEL_LOGGER_ID, MAXLOGGERS, PAGED_CODE, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_WMI_INSTANCE_NOT_FOUND, TraceDebug, WmiGetLoggerId, WmipDereferenceLogger, WmipGetLoggerContext, WmipGlobalBufferCallback, WmipIsValidLogger, WmipKernelLogger, and WmipReferenceLogger.
NTKERNELAPI NTSTATUS WmiStartTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 47 of file traceapi.c.
References ExFreePool(), FALSE, NT_SUCCESS, NULL, PAGED_CODE, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_PARAMETER, WmiFlushTrace(), WmipCreateDirectoryFile(), WmipCreateNtFileName(), WmipStartLogger(), and ZwClose().
NTKERNELAPI NTSTATUS WmiStopTrace (IN PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 160 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::BuffersAvailable, EtwpDefaultTraceSecurityDescriptor, Executive, FALSE, _WMI_LOGGER_CONTEXT::FlushEvent, _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedDecrement, KeResetEvent(), KERNEL_LOGGER, KernelMode, _WMI_LOGGER_CONTEXT::KernelTraceOn, KeWaitForSingleObject(), _WMI_LOGGER_CONTEXT::LogFileHandle, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::LoggerStatus, _WMI_LOGGER_CONTEXT::MutexCount, NT_SUCCESS, NULL, _WMI_LOGGER_CONTEXT::NumberOfBuffers, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_TIMEOUT, TraceDebug, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipDisableTraceProviders(), WmipEventLogger, WmipKernelLogger, WmipLoggerContext, WmipQueryLogger(), WmipReleaseMutex, WmipStopLoggerInstance(), and WmipVerifyLoggerInfo().
Referenced by WmipIoControl(), and WmipShutdown().
NTKERNELAPI NTSTATUS FASTCALL WmiTraceEvent (IN PWNODE_HEADER Wnode, IN KPROCESSOR_MODE RequestorMode)
Definition at line 1154 of file traceapi.c.
References _WMI_LOGGER_CONTEXT::BufferSize, _ETHREAD::Cid, DISPATCH_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, HandleToUlong, InterlockedCompareExchange(), KeGetCurrentIrql(), KernelMode, _KTHREAD::KernelTime, _WMI_LOGGER_CONTEXT::LoggerMode, MAXLOGGERS, NULL, ProbeForRead, ProbeForReadSmallStructure, PsGetCurrentThread(), REQUEST_FLAG_CIRCULAR_PERSIST, REQUEST_FLAG_CIRCULAR_TRANSITION, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, Status, STATUS_ARRAY_BOUNDS_EXCEEDED, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_HANDLE, STATUS_NO_MEMORY, STATUS_SEVERITY_WARNING, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _ETHREAD::Tcb, TRACE_HEADER_ENUM_MASK, TRACE_HEADER_FLAG, TRACE_HEADER_TYPE_INSTANCE, TraceDebug, TRUE, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, _KTHREAD::UserTime, WmiGetLoggerId, WmipDereferenceLogger, WmipFlushLogger(), WmipGetLoggerContext, WmipIsValidLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), WmipReserveTraceBuffer(), WNODE_FLAG_LOG_WNODE, WNODE_FLAG_PERSIST_EVENT, WNODE_FLAG_TRACED_GUID, WNODE_FLAG_USE_GUID_PTR, WNODE_FLAG_USE_MOF_PTR, and WNODE_FLAG_USE_TIMESTAMP.
Referenced by IoWMIWriteEvent(), NtTraceEvent(), WmipFastIoDeviceControl(), and WmipIoControl().
NTKERNELAPI NTSTATUS FASTCALL WmiTraceFastEvent (IN PWNODE_HEADER Wnode)
Definition at line 1562 of file traceapi.c.
References DBG, _TIMED_TRACE_HEADER::EventId, _TIMED_TRACE_HEADER::LoggerId, MAXLOGGERS, NULL, RtlCopyMemory, _TIMED_TRACE_HEADER::Size, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_SUCCESS, _TIMED_TRACE_HEADER::TimeStamp, TRACE_HEADER_ULONG32_TIME, TraceDebug, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmipReserveTraceBuffer().
Referenced by IoWMIWriteEvent().
NTKERNELAPI NTSTATUS WmiTraceKernelEvent (IN ULONG GroupType, IN PVOID EventInfo, IN ULONG EventInfoLen, IN PETHREAD Thread)
Definition at line 1449 of file traceapi.c.
References HandleToUlong, _SYSTEM_TRACE_HEADER::Header, _SYSTEM_TRACE_HEADER::KernelTime, _WMI_LOGGER_CONTEXT::LoggerId, _SYSTEM_TRACE_HEADER::Marker, NULL, _SYSTEM_TRACE_HEADER::ProcessId, PsGetCurrentThread(), RtlCopyMemory, STATUS_ALREADY_DISCONNECTED, STATUS_NO_MEMORY, STATUS_SUCCESS, SYSTEM_TRACE_MARKER, _SYSTEM_TRACE_HEADER::SystemTime, _SYSTEM_TRACE_HEADER::ThreadId, TraceDebug, _SYSTEM_TRACE_HEADER::UserTime, WmipDereferenceLogger, WmipIsValidLogger, WmipKernelLogger, WmipLoggerContext, WmipRefCount, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmipReserveTraceBuffer().
NTKERNELAPI NTSTATUS WmiTraceMessage (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, ...)
Definition at line 1641 of file traceapi.c.
References va_start, and WmiTraceMessageVa().
Referenced by NtTraceEvent(), and WmiTraceUserMessage().
NTSTATUS WmiTraceMessageVa (IN TRACEHANDLE LoggerHandle, IN ULONG MessageFlags, IN LPGUID MessageGuid, IN USHORT MessageNumber, va_list MessageArgList)
Definition at line 1693 of file traceapi.c.
References _ETHREAD::Cid, except, EXCEPTION_EXECUTE_HANDLER, HandleToUlong, _LARGE_INTEGER::HighPart, KeGetPreviousMode, KernelMode, _WMI_LOGGER_CONTEXT::LoggerMode, _LARGE_INTEGER::LowPart, _MESSAGE_TRACE_HEADER::Marker, MAXLOGGERS, _WMI_TRACE_MESSAGE_PACKET::MessageNumber, NULL, _WMI_TRACE_MESSAGE_PACKET::OptionFlags, _MESSAGE_TRACE_HEADER::Packet, PsGetCurrentThread(), REQUEST_FLAG_CIRCULAR_PERSIST, REQUEST_FLAG_CIRCULAR_TRANSITION, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, _MESSAGE_TRACE_HEADER::Size, STATUS_INVALID_BUFFER_SIZE, STATUS_INVALID_HANDLE, STATUS_NO_MEMORY, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRACE_HEADER_FLAG, TRACE_MESSAGE, TraceDebug, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, va_arg, WmiGetLoggerId, WmipDereferenceLogger, WmipGetLoggerContext, WmipIsValidLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmipReserveTraceBuffer().
Referenced by WmiTraceMessage().
NTKERNELAPI NTSTATUS FASTCALL WmiTraceUserMessage (IN PMESSAGE_TRACE_USER pMessage, IN ULONG MessageSize)
Definition at line 1987 of file traceapi.c.
References except, EXCEPTION_EXECUTE_HANDLER, NULL, ProbeForRead, STATUS_UNSUCCESSFUL, TraceDebug, and WmiTraceMessage().
Referenced by WmipFastIoDeviceControl(), and WmipIoControl().
NTKERNELAPI NTSTATUS WmiUpdateTrace (IN OUT PWMI_LOGGER_INFORMATION LoggerInfo)
Definition at line 321 of file traceapi.c.
References ASSERT, _UNICODE_STRING::Buffer, _WMI_LOGGER_CONTEXT::BufferCallback, _WMI_LOGGER_CONTEXT::BufferSize, _WMI_LOGGER_CONTEXT::ClientSecurityContext, _WMI_LOGGER_CONTEXT::CollectionOn, CONTAINING_RECORD, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, _WMI_LOGGER_CONTEXT::EnableFlagArray, _WMI_LOGGER_CONTEXT::EnableFlags, EtwpDefaultTraceSecurityDescriptor, EVENT_TRACE_KD_FILTER_MODE, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, FIELD_OFFSET, FILE_WRITE_DATA, _WMI_LOGGER_CONTEXT::FlushEvent, _WMI_LOGGER_CONTEXT::FlushTimer, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, _WMI_LOGGER_CONTEXT::InstanceGuid, InterlockedCompareExchange(), InterlockedDecrement, InterlockedExchange(), IoFileObjectType, IsEqualGUID, KdReportTraceData(), KeGetCurrentThread(), KeGetPreviousMode, KeResetEvent(), KernelMode, _WMI_LOGGER_CONTEXT::KernelTraceOn, KeWaitForSingleObject(), _TRACE_ENABLE_FLAG_EXTENSION::Length, _SECURITY_QUALITY_OF_SERVICE::Length, _WMI_LOGGER_CONTEXT::LogFileHandle, _WMI_LOGGER_CONTEXT::LoggerHeader, _WMI_LOGGER_CONTEXT::LoggerId, _WMI_LOGGER_CONTEXT::LoggerMode, _WMI_LOGGER_CONTEXT::LoggerMutex, _WMI_LOGGER_CONTEXT::LoggerStatus, _WMI_LOGGER_CONTEXT::MaximumBuffers, MmMaximumNonPagedPoolInBytes, _WMI_LOGGER_CONTEXT::MutexCount, _WMI_LOGGER_CONTEXT::NewLogFileName, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _TRACE_ENABLE_FLAG_EXTENSION::Offset, PAGED_CODE, PagedPool, PERF_LOG_NO_TRANSITION, PERF_LOG_START_TRANSITION, PERFINFO_START_LOG_POST_BOOT, PerfInfoStartLog(), _WMI_LOGGER_CONTEXT::PerfLogInTransition, ProbeForRead, REQUEST_FLAG_NEW_FILE, _WMI_LOGGER_CONTEXT::RequestFlag, RtlCopyMemory, RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlZeroMemory, SeComputeGrantedAccesses, SeCreateClientSecurity(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, Status, STATUS_ACCESS_DENIED, STATUS_ALREADY_DISCONNECTED, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, TRACE_MAXIMUM_NP_POOL_USAGE, TraceDebug, TRACEPOOLTAG, TRUE, WmipCheckGuidAccess(), WmipDereferenceLogger, WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipExtendBase(), WmipKernelLogger, WmipNotifyLogger(), WmipQueryLogger(), WmipReleaseMutex, WmipVerifyLoggerInfo(), and ZwClose().
Referenced by WmipIoControl().
Variable Documentation
SIZE_T MmMaximumNonPagedPoolInBytes
Definition at line 273 of file miglobal.c.
Referenced by WmiUpdateTrace().