Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmnotify.c File Reference
cmnotify.c File Reference
#include "cmp.h"
Macros
#define CmpCheckPostBlock(a)
Functions
VOID CmNotifyRunDown (__in PETHREAD Thread)
VOID CmpAddToDelayedDeref (PCM_POST_BLOCK PostBlock, PLIST_ENTRY DelayedDeref)
VOID CmpCancelSlavePost (PCM_POST_BLOCK PostBlock, PLIST_ENTRY DelayedDeref)
VOID CmpDelayedDerefKeys (PLIST_ENTRY DelayedDeref)
VOID CmpDummyApc (struct _KAPC *Apc, PVOID *SystemArgument1, PVOID *SystemArgument2)
VOID CmpFlushNotify (PCM_KEY_BODY KeyBody, BOOLEAN LockHeld)
VOID CmpFreeSlavePost (PCM_POST_BLOCK MasterPostBlock)
NTSTATUS CmpNotifyChangeKey (IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK PostBlock, IN ULONG CompletionFilter, IN BOOLEAN WatchTree, IN PVOID Buffer, IN ULONG BufferSize, IN PCM_POST_BLOCK MasterPostBlock)
BOOLEAN CmpNotifyTriggerCheck (IN PCM_NOTIFY_BLOCK NotifyBlock, IN PHHIVE Hive, IN PCM_KEY_NODE Node)
VOID CmpPostApc (struct _KAPC *Apc, PKNORMAL_ROUTINE *NormalRoutine, PVOID *NormalContext, PVOID *SystemArgument1, PVOID *SystemArgument2)
VOID CmpPostApcRunDown (struct _KAPC *Apc)
VOID CmpPostNotify (PCM_NOTIFY_BLOCK NotifyBlock, PUNICODE_STRING Name OPTIONAL, ULONG Filter, NTSTATUS Status, BOOLEAN PostListLockHeld, PLIST_ENTRY ExternalKeyDeref OPTIONAL)
VOID CmpReportNotify (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PHHIVE Hive, HCELL_INDEX Cell, ULONG Filter)
VOID CmpReportNotifyHelper (PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PHHIVE SearchHive, IN PHHIVE Hive, IN HCELL_INDEX Cell, IN ULONG Filter)
Variables
PCMHIVE CmpMasterHive
Macro Definition Documentation
#define CmpCheckPostBlock (a)
Definition at line 49 of file cmnotify.c.
Referenced by CmpPostApc().
Function Documentation
VOID CmNotifyRunDown (__in PETHREAD Thread)
Definition at line 1023 of file cmnotify.c.
References _CM_ASYNC_USER_POST_BLOCK::Apc, APC_LEVEL, ASSERT, _CM_POST_BLOCK_UNION::AsyncUser, _CM_POST_BLOCK::CancelPostList, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_FLOW, CmpCancelSlavePost(), CmpCheckIoStatusPointer, CmpClearListEntry, CmpFreePostBlock(), CmpFreeSlavePost(), CmpIsListEmpty, CmpLockRegistry(), CmpRemoveEntryList, CmpSetIoStatus, CmpUnlockRegistry(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InsertTailList(), _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, IsListEmpty, IsMasterPostBlock, KeLowerIrql, KeRaiseIrql, KeRemoveQueueApc(), KeSetEvent(), LOCK_POST_LIST, NOTHING, _CM_POST_BLOCK::NotifyList, NULL, ObDereferenceObject(), PostAsyncUser, PostBlockType, PsGetCurrentProcess(), RemoveHeadList(), STATUS_NOTIFY_CLEANUP, _CM_POST_BLOCK::ThreadList, TRUE, _CM_POST_BLOCK::u, UNLOCK_POST_LIST, and _CM_ASYNC_USER_POST_BLOCK::UserEvent.
Referenced by PspExitThread().
VOID CmpAddToDelayedDeref (PCM_POST_BLOCK PostBlock, PLIST_ENTRY DelayedDeref)
Definition at line 1830 of file cmnotify.c.
References ASSERT, CM_PAGED_CODE, InsertTailList(), _CM_POST_KEY_BODY::KeyBody, _CM_POST_KEY_BODY::KeyBodyList, NULL, and _CM_POST_BLOCK::PostKeyBody.
Referenced by CmpCancelSlavePost(), and CmpPostNotify().
VOID CmpCancelSlavePost (PCM_POST_BLOCK PostBlock, PLIST_ENTRY DelayedDeref)
Definition at line 1731 of file cmnotify.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, _CM_POST_BLOCK::CancelPostList, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpAddToDelayedDeref(), CmpRemoveEntryList, CONTAINING_RECORD, DPFLTR_CONFIG_ID, _LIST_ENTRY::Flink, IsListEmpty, IsMasterPostBlock, _CM_POST_BLOCK::NotifyList, and TRUE.
Referenced by CmNotifyRunDown(), and CmpPostNotify().
VOID CmpDelayedDerefKeys (PLIST_ENTRY DelayedDeref)
Definition at line 1885 of file cmnotify.c.
References ASSERT, CM_PAGED_CODE, CONTAINING_RECORD, ExFreePool(), FALSE, IsListEmpty, KEY_BODY_TYPE, _CM_POST_KEY_BODY::KeyBody, NULL, ObDereferenceObjectDeferDelete(), RemoveHeadList(), and _CM_KEY_BODY::Type.
Referenced by CmpCloseKeyObject(), CmpPostNotify(), and CmpReportNotifyHelper().
VOID CmpDummyApc (struct _KAPC * Apc, PVOID * SystemArgument1, PVOID * SystemArgument2)
Definition at line 120 of file cmnotify.c.
References UNREFERENCED_PARAMETER.
Referenced by NtNotifyChangeMultipleKeys().
VOID CmpFlushNotify (PCM_KEY_BODY KeyBody, BOOLEAN LockHeld)
Definition at line 1229 of file cmnotify.c.
References ASSERT_CM_LOCK_OWNED, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _LIST_ENTRY::Blink, CM_PAGED_CODE, CmLockHive, CmpClearListEntry, CmpPostNotify(), CmUnlockHive, CONTAINING_RECORD, DBG, ExFreePool(), FALSE, _LIST_ENTRY::Flink, Hive, _CM_NOTIFY_BLOCK::HiveList, IsListEmpty, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_BODY::NotifyBlock, NULL, _CM_NOTIFY_BLOCK::PostList, SeReleaseSubjectContext(), STATUS_NOTIFY_CLEANUP, and _CM_NOTIFY_BLOCK::SubjectContext.
Referenced by CmpDeleteKeyObject(), CmpFlushNotifiesOnKeyBodyList(), CmpRefreshHive(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpFreeSlavePost (PCM_POST_BLOCK MasterPostBlock)
Definition at line 1635 of file cmnotify.c.
References ASSERT, _CM_POST_BLOCK::CancelPostList, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpFreePostBlock(), CmpRemoveEntryList, CONTAINING_RECORD, DPFLTR_CONFIG_ID, _LIST_ENTRY::Flink, IsListEmpty, IsMasterPostBlock, _CM_POST_BLOCK::ThreadList, and TRUE.
Referenced by CmNotifyRunDown(), CmpPostApc(), and CmpPostApcRunDown().
NTSTATUS CmpNotifyChangeKey (IN PCM_KEY_BODY KeyBody, IN PCM_POST_BLOCK PostBlock, IN ULONG CompletionFilter, IN BOOLEAN WatchTree, IN PVOID Buffer, IN ULONG BufferSize, IN PCM_POST_BLOCK MasterPostBlock)
Definition at line 1355 of file cmnotify.c.
References APC_LEVEL, ASSERT, ASSERT_CM_LOCK_OWNED, _LIST_ENTRY::Blink, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CML_POOL, CmpFreePostBlock(), CmpInitializeKeyNameString(), CmpPostNotify(), CONTAINING_RECORD, DBG, DPFLTR_CONFIG_ID, ExAllocatePool, ExAllocatePoolWithQuotaTag, ExFreePool(), FALSE, _CM_NOTIFY_BLOCK::Filter, _LIST_ENTRY::Flink, HCELL_NIL, Hive, _CM_NOTIFY_BLOCK::HiveList, HvGetCell, HvReleaseCell, InitializeListHead(), InsertHeadList(), InsertTailList(), IsMasterPostBlock, KeLowerIrql, KeRaiseIrql, _CM_NOTIFY_BLOCK::KeyBody, _CM_NOTIFY_BLOCK::KeyControlBlock, KeyName, _UNICODE_STRING::Length, _CMHIVE::NotifyList, _CM_NOTIFY_BLOCK::NotifyPending, NULL, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _CM_NOTIFY_BLOCK::PostList, PsGetCurrentThread(), REG_MAX_KEY_NAME_LENGTH, SeCaptureSubjectContext(), STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NOTIFY_ENUM_DIR, STATUS_PENDING, STATUS_SUCCESS, _CM_NOTIFY_BLOCK::SubjectContext, _CM_KEY_CONTROL_BLOCK::TotalLevels, TRUE, UNREFERENCED_PARAMETER, and _CM_NOTIFY_BLOCK::WatchTree.
Referenced by NtNotifyChangeMultipleKeys().
BOOLEAN CmpNotifyTriggerCheck (IN PCM_NOTIFY_BLOCK NotifyBlock, IN PHHIVE Hive, IN PCM_KEY_NODE Node)
Definition at line 265 of file cmnotify.c.
References ASSERT, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpCheckNotifyAccess(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, FALSE, _LIST_ENTRY::Flink, IsListEmpty, _CM_POST_BLOCK::NotifyList, PostAsyncKernel, PostBlockType, and TRUE.
Referenced by CmpReportNotifyHelper().
VOID CmpPostApc (struct _KAPC * Apc, PKNORMAL_ROUTINE * NormalRoutine, PVOID * NormalContext, PVOID * SystemArgument1, PVOID * SystemArgument2)
Definition at line 793 of file cmnotify.c.
References _CM_POST_BLOCK_UNION::AsyncUser, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpCheckIoStatusPointer, CmpCheckPostBlock, CmpFreePostBlock(), CmpFreeSlavePost(), CmpRemoveEntryList, CmpSetIoStatus, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, KeSetEvent(), NOTHING, NULL, ObDereferenceObject(), PsGetCurrentProcess(), _CM_POST_BLOCK::ThreadList, _CM_POST_BLOCK::u, UNREFERENCED_PARAMETER, and _CM_ASYNC_USER_POST_BLOCK::UserEvent.
Referenced by NtNotifyChangeMultipleKeys().
VOID CmpPostApcRunDown (struct _KAPC * Apc)
Definition at line 919 of file cmnotify.c.
References APC_LEVEL, _CM_POST_BLOCK_UNION::AsyncUser, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpCheckIoStatusPointer, CmpFreePostBlock(), CmpFreeSlavePost(), CmpRemoveEntryList, CmpSetIoStatus, DBG, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, KeLowerIrql, KeRaiseIrql, KeSetEvent(), NOTHING, NULL, ObDereferenceObject(), PsGetCurrentProcess(), STATUS_NOTIFY_CLEANUP, _KAPC::SystemArgument2, _CM_POST_BLOCK::ThreadList, _CM_POST_BLOCK::u, and _CM_ASYNC_USER_POST_BLOCK::UserEvent.
Referenced by NtNotifyChangeMultipleKeys().
VOID CmpPostNotify (PCM_NOTIFY_BLOCK NotifyBlock, PUNICODE_STRING Name OPTIONAL, ULONG Filter, NTSTATUS Status, BOOLEAN PostListLockHeld, PLIST_ENTRY ExternalKeyDeref OPTIONAL)
Definition at line 487 of file cmnotify.c.
References _CM_ASYNC_USER_POST_BLOCK::Apc, APC_LEVEL, ARGUMENT_PRESENT, ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_HIVE_LOCK_OWNED, _CM_POST_BLOCK_UNION::AsyncUser, _CM_POST_BLOCK::CancelPostList, ClearMasterPostBlockFlag, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpAddToDelayedDeref(), CmpCancelSlavePost(), CmpClearListEntry, CmpDelayedDerefKeys(), CmpFreePostBlock(), CmpRemoveEntryList, CONTAINING_RECORD, DPFLTR_CONFIG_ID, ExQueueWorkItem(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), IsListEmpty, IsMasterPostBlock, KeInsertQueueApc(), KeLowerIrql, KeRaiseIrql, KeSetEvent(), LOCK_POST_LIST, _CM_POST_BLOCK::NotifyList, _CM_NOTIFY_BLOCK::NotifyPending, _CM_POST_BLOCK::NotifyType, NULL, ObDereferenceObject(), PostAsyncKernel, PostAsyncUser, PostBlockType, _CM_NOTIFY_BLOCK::PostList, PostSynchronous, RemoveHeadList(), SetMasterPostBlockFlag, Status, _CM_SYNC_POST_BLOCK::Status, STATUS_NOTIFY_CLEANUP, _CM_POST_BLOCK_UNION::Sync, _CM_SYNC_POST_BLOCK::SystemEvent, _CM_POST_BLOCK::ThreadList, TRUE, _CM_POST_BLOCK::u, ULongToPtr, and UNLOCK_POST_LIST.
Referenced by CmpCloseKeyObject(), CmpFlushNotify(), CmpNotifyChangeKey(), and CmpReportNotifyHelper().
VOID CmpReportNotify (PCM_KEY_CONTROL_BLOCK KeyControlBlock, PHHIVE Hive, HCELL_INDEX Cell, ULONG Filter)
Definition at line 152 of file cmnotify.c.
References ASSERT, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_NOTIFY, CmpReportNotifyHelper(), DPFLTR_CONFIG_ID, _CM_KEY_NODE::Flags, HCELL_NIL, _CMHIVE::Hive, HvGetCell, HvReleaseCell, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, NULL, _CM_KEY_NODE::Parent, _CM_KEY_CONTROL_BLOCK::ParentKcb, and REG_NOTIFY_CHANGE_NAME.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmpDoCreateChild(), CmpLinkHiveToMaster(), CmpSecurityMethod(), CmRestoreKey(), CmSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpReportNotifyHelper (PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PHHIVE SearchHive, IN PHHIVE Hive, IN HCELL_INDEX Cell, IN ULONG Filter)
Definition at line 341 of file cmnotify.c.
References APC_LEVEL, CM_PAGED_CODE, CmLockHive, CmpDelayedDerefKeys(), CmpNotifyTriggerCheck(), CmpPostNotify(), CmUnlockHive, CONTAINING_RECORD, DBG, FALSE, _CM_NOTIFY_BLOCK::Filter, _LIST_ENTRY::Flink, HvGetCell, HvReleaseCell, InitializeListHead(), KeLowerIrql, KeRaiseIrql, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_NOTIFY_BLOCK::KeyControlBlock, _CMHIVE::NotifyList, NULL, _CM_KEY_CONTROL_BLOCK::ParentKcb, STATUS_NOTIFY_ENUM_DIR, _CM_KEY_CONTROL_BLOCK::TotalLevels, TRUE, and _CM_NOTIFY_BLOCK::WatchTree.
Referenced by CmpReportNotify().
Variable Documentation
PCMHIVE CmpMasterHive
Definition at line 305 of file cmdat.c.