Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psimpers.c File Reference
psimpers.c File Reference
#include "psp.h"
Functions
NTSTATUS NtImpersonateThread (__in HANDLE ServerThreadHandle, __in HANDLE ClientThreadHandle, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos)
Function Documentation
NTSTATUS NtImpersonateThread (__in HANDLE ServerThreadHandle, __in HANDLE ClientThreadHandle, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos)
Definition at line 27 of file psimpers.c.
References except, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForReadSmallStructure, PsThreadType, SeCreateClientSecurity(), SeDeleteClientSecurity, SeImpersonateClientEx(), Status, THREAD_DIRECT_IMPERSONATION, and THREAD_IMPERSONATE.