Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/procobj.c File Reference
procobj.c File Reference
#include "ki.h"
Functions
VOID KeAttachProcess (__inout PRKPROCESS Process)
VOID KeDetachProcess (VOID)
LOGICAL KeForceAttachProcess (__inout PRKPROCESS Process)
VOID KeInitializeProcess (__out PRKPROCESS Process, __in KPRIORITY BasePriority, __in KAFFINITY Affinity, __in ULONG_PTR DirectoryTableBase[2], __in BOOLEAN Enable)
ULONG KeQueryRuntimeProcess (__in PKPROCESS Process, __out PULONG UserTime)
VOID KeQueryValuesProcess (__in PKPROCESS Process, __out PKPROCESS_VALUES Values)
LONG KeReadStateProcess (__in PRKPROCESS Process)
KAFFINITY KeSetAffinityProcess (__inout PKPROCESS Process, __in KAFFINITY Affinity)
LOGICAL KeSetAutoAlignmentProcess (__inout PKPROCESS Process, __in LOGICAL Enable)
LOGICAL KeSetDisableBoostProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
LOGICAL KeSetDisableQuantumProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
KPRIORITY KeSetPriorityAndQuantumProcess (__inout PKPROCESS Process, __in KPRIORITY NewBase, __in SCHAR QuantumReset)
LONG KeSetProcess (__inout PRKPROCESS Process, __in KPRIORITY Increment, __in BOOLEAN Wait)
VOID KeSetQuantumProcess (__inout PKPROCESS Process, __in SCHAR QuantumReset)
VOID KeStackAttachProcess (__inout PRKPROCESS Process, __out PRKAPC_STATE ApcState)
VOID KeUnstackDetachProcess (__in PRKAPC_STATE ApcState)
VOID KiAttachProcess (__inout PRKTHREAD Thread, __in PRKPROCESS Process, __in PKLOCK_QUEUE_HANDLE LockHandle, __out PRKAPC_STATE SavedApcState)
VOID KiMoveApcState (__in PKAPC_STATE Source, __out PKAPC_STATE Destination)
FORCEINLINE VOID KiSetIdealNodeProcess (__inout PKPROCESS Process, __in KAFFINITY Affinity)
Function Documentation
VOID KeAttachProcess (__inout PRKPROCESS Process)
Definition at line 226 of file procobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, INVALID_PROCESS_ATTACH_ATTEMPT, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KiAttachProcess(), KiLockDispatcherDatabaseAtSynchLevel, _KAPC_STATE::Process, and _KTHREAD::SavedApcState.
Referenced by IopRaiseHardError(), MmCreatePeb(), MmCreateTeb(), MmDeleteTeb(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), SepRmCallLsa(), WmipCreateGuidObject(), and WmipOpenGuidObject().
VOID KeDetachProcess (VOID)
Definition at line 479 of file procobj.c.
References APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, _KTHREAD::ApcStatePointer, ASSERT, DISPATCH_LEVEL, FALSE, InterlockedPushEntrySingleList(), INVALID_PROCESS_DETACH_ATTEMPT, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheck(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiMoveApcState(), KiProcessOutSwapListHead, KiRequestSoftwareInterrupt, KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapProcess(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, ProcessInMemory, ProcessOutTransition, _KTHREAD::SavedApcState, _KTHREAD::SpecialApcDisable, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, _KPROCESS::ThreadListHead, TRUE, and UserMode.
Referenced by IopRaiseHardError(), MiAttachAndLockWorkingSet(), MiDetachAndUnlockWorkingSet(), MmCreatePeb(), MmCreateTeb(), MmDeleteTeb(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), SepRmCallLsa(), WmipCreateGuidObject(), and WmipOpenGuidObject().
LOGICAL KeForceAttachProcess (__inout PRKPROCESS Process)
Definition at line 297 of file procobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, INVALID_PROCESS_ATTACH_ATTEMPT, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KeReleaseInStackQueuedSpinLock(), KiAttachProcess(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, _KAPC_STATE::Process, ProcessInMemory, ProcessInSwap, ProcessInTransition, ProcessOutSwap, ProcessOutTransition, _KTHREAD::SavedApcState, and TRUE.
Referenced by MiAttachAndLockWorkingSet().
VOID KeInitializeProcess (__out PRKPROCESS Process, __in KPRIORITY BasePriority, __in KAFFINITY Affinity, __in ULONG_PTR DirectoryTableBase[2], __in BOOLEAN Enable)
Definition at line 118 of file procobj.c.
References InitializeListHead(), IO_ACCESS_MAP_NONE, KiComputeIopmOffset, KiSetIdealNodeProcess(), ProcessInMemory, ProcessObject, and THREAD_QUANTUM.
Referenced by KiInitializeKernel(), and PspCreateProcess().
ULONG KeQueryRuntimeProcess (__in PKPROCESS Process, __out PULONG UserTime)
Definition at line 790 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), _KTHREAD::KernelTime, and _KTHREAD::UserTime.
Referenced by NtQueryInformationProcess(), NtQuerySystemInformation(), NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), and WmiGetClock().
VOID KeQueryValuesProcess (__in PKPROCESS Process, __out PKPROCESS_VALUES Values)
Definition at line 854 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeMaximumIncrement, KeReleaseInStackQueuedSpinLock(), _KTHREAD::KernelTime, UInt32x32To64, and _KTHREAD::UserTime.
Referenced by ExpCopyProcessInfo(), NtQueryInformationJobObject(), NtQueryInformationProcess(), and PspFoldProcessAccountingIntoJob().
LONG KeReadStateProcess (__in PRKPROCESS Process)
Definition at line 939 of file procobj.c.
References ASSERT_PROCESS.
Referenced by NtSetInformationJobObject().
KAFFINITY KeSetAffinityProcess (__inout PKPROCESS Process, __in KAFFINITY Affinity)
Definition at line 1055 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeActiveProcessors, KeGetCurrentIrql(), KeNodeBlock, KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiSetAffinityThread(), KiSetIdealNodeProcess(), KiUnlockDispatcherDatabaseFromSynchLevel, and _KLOCK_QUEUE_HANDLE::OldIrql.
Referenced by NtSetInformationProcess(), Phase1InitializationDiscard(), and PspApplyJobLimitsToProcess().
LOGICAL KeSetAutoAlignmentProcess (__inout PKPROCESS Process, __in LOGICAL Enable)
Definition at line 1428 of file procobj.c.
References ASSERT_PROCESS, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KPROCESS_AUTO_ALIGNMENT_BIT.
Referenced by NtSetInformationProcess().
LOGICAL KeSetDisableBoostProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
Definition at line 1474 of file procobj.c.
References ASSERT_PROCESS, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KPROCESS_DISABLE_BOOST_BIT.
Referenced by NtSetInformationProcess().
LOGICAL KeSetDisableQuantumProcess (__inout PKPROCESS Process, __in LOGICAL Disable)
Definition at line 1520 of file procobj.c.
References ASSERT_PROCESS, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KPROCESS_DISABLE_QUANTUM_BIT.
Referenced by PspApplyJobLimitsToProcess().
KPRIORITY KeSetPriorityAndQuantumProcess (__inout PKPROCESS Process, __in KPRIORITY NewBase, __in SCHAR QuantumReset)
Definition at line 1145 of file procobj.c.
References ASSERT, ASSERT_PROCESS, _KTHREAD::BasePriority, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, HIGH_PRIORITY, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiAcquireThreadLock(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabaseFromSynchLevel, LOW_PRIORITY, LOW_REALTIME_PRIORITY, _KLOCK_QUEUE_HANDLE::OldIrql, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, _KTHREAD::QuantumReset, and _KTHREAD::Saturation.
Referenced by NtSetInformationProcess(), and PsSetProcessPriorityByClass().
LONG KeSetProcess (__inout PRKPROCESS Process, __in KPRIORITY Increment, __in BOOLEAN Wait)
Definition at line 971 of file procobj.c.
References ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTestWithoutSideEffects(), _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by PspExitThread().
VOID KeSetQuantumProcess (__inout PKPROCESS Process, __in SCHAR QuantumReset)
Definition at line 1369 of file procobj.c.
References ASSERT, ASSERT_PROCESS, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), and _KTHREAD::QuantumReset.
Referenced by PsChangeQuantumTable(), and PspApplyJobLimitsToProcess().
VOID KeStackAttachProcess (__inout PRKPROCESS Process, __out PRKAPC_STATE ApcState)
Definition at line 393 of file procobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, ASSERT_PROCESS, DISPATCH_LEVEL, FALSE, INVALID_PROCESS_ATTACH_ATTEMPT, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KiAttachProcess(), KiLockDispatcherDatabaseAtSynchLevel, NULL, _KAPC_STATE::Process, and _KTHREAD::SavedApcState.
Referenced by DbgkpMarkProcessPeb(), DbgkpPostFakeProcessCreateMessages(), ExpDebuggerWorker(), MiCloneProcessAddressSpace(), MiDoMappedCopy(), MiDoPoolCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiLoadImageSection(), MiUnmapViewOfSection(), MmAssignProcessToJob(), MmAttachSession(), MmCheckSystemImage(), MmEnforceWorkingSetLimit(), MmFlushVirtualMemory(), MmMapViewOfSection(), MmProbeAndLockProcessPages(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushInstructionCache(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtProtectVirtualMemory(), NtQueryInformationProcess(), NtQueryVirtualMemory(), NtResetWriteWatch(), NtSetInformationJobObject(), NtSetInformationThread(), NtUnlockVirtualMemory(), ObClearProcessHandleTable(), ObDuplicateObject(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObSetHandleAttributes(), PspAddProcessToJob(), PspProcessDelete(), PspQueryQuotaLimits(), PspSetQuotaLimits(), PspWriteTebImpersonationInfo(), and SepCleanupLUIDDeviceMapDirectory().
VOID KeUnstackDetachProcess (__in PRKAPC_STATE ApcState)
Definition at line 632 of file procobj.c.
References APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, _KTHREAD::ApcStatePointer, ASSERT, DISPATCH_LEVEL, FALSE, InterlockedPushEntrySingleList(), INVALID_PROCESS_DETACH_ATTEMPT, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeBugCheck(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiMoveApcState(), KiProcessOutSwapListHead, KiRequestSoftwareInterrupt, KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapProcess(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, ProcessInMemory, ProcessOutTransition, _KTHREAD::SavedApcState, _KTHREAD::SpecialApcDisable, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, _KPROCESS::ThreadListHead, TRUE, and UserMode.
Referenced by DbgkpMarkProcessPeb(), DbgkpPostFakeProcessCreateMessages(), ExpDebuggerWorker(), MiCloneProcessAddressSpace(), MiDoMappedCopy(), MiDoPoolCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiLoadImageSection(), MiUnmapViewOfSection(), MmAssignProcessToJob(), MmCheckSystemImage(), MmDetachSession(), MmEnforceWorkingSetLimit(), MmFlushVirtualMemory(), MmMapViewOfSection(), MmProbeAndLockProcessPages(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushInstructionCache(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtProtectVirtualMemory(), NtQueryInformationProcess(), NtQueryVirtualMemory(), NtResetWriteWatch(), NtSetInformationJobObject(), NtSetInformationThread(), NtUnlockVirtualMemory(), ObClearProcessHandleTable(), ObDuplicateObject(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObSetHandleAttributes(), PspAddProcessToJob(), PspProcessDelete(), PspQueryQuotaLimits(), PspSetQuotaLimits(), PspWriteTebImpersonationInfo(), and SepCleanupLUIDDeviceMapDirectory().
VOID KiAttachProcess (__inout PRKTHREAD Thread, __in PRKPROCESS Process, __in PKLOCK_QUEUE_HANDLE LockHandle, __out PRKAPC_STATE SavedApcState)
Definition at line 1566 of file procobj.c.
References ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), InterlockedPushEntrySingleList(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentPrcb(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiMoveApcState(), KiProcessInSwapListHead, KiReadyThread(), KiSetContextSwapBusy(), KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapProcess(), KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, MAXULONG_PTR, ProcessInMemory, ProcessInTransition, ProcessOutOfMemory, _KTHREAD::ProcessReadyQueue, Ready, RemoveEntryList(), TRUE, and UserMode.
Referenced by KeAttachProcess(), KeForceAttachProcess(), and KeStackAttachProcess().
VOID KiMoveApcState (__in PKAPC_STATE Source, __out PKAPC_STATE Destination)
Definition at line 1714 of file procobj.c.
References _LIST_ENTRY::Blink, FALSE, _LIST_ENTRY::Flink, InitializeListHead(), IsListEmpty, KAPC_STATE_ACTUAL_LENGTH, KernelMode, RtlCopyMemory, and UserMode.
Referenced by KeDetachProcess(), KeUnstackDetachProcess(), and KiAttachProcess().
FORCEINLINE VOID KiSetIdealNodeProcess (__inout PKPROCESS Process, __in KAFFINITY Affinity)
Definition at line 47 of file procobj.c.
References ASSERT, Index, KeFindNextRightSetAffinity(), KeNodeBlock, KeNumberNodes, and KeProcessNodeSeed.
Referenced by KeInitializeProcess(), and KeSetAffinityProcess().