Windows Research Kernel v1.2: C:/Windows Research Kernel/se/adtutil.h File Reference
adtutil.h File Reference
Functions
NTSTATUS SepRegQueryDwordValue (IN PCWSTR KeyName, IN PCWSTR ValueName, OUT PULONG Value)
NTSTATUS SepRegQueryHelper (IN PCWSTR KeyName, IN PCWSTR ValueName, IN ULONG ValueType, IN ULONG ValueLength, OUT PVOID ValueBuffer, OUT PULONG LengthRequired)
Function Documentation
NTSTATUS SepRegQueryDwordValue (IN PCWSTR KeyName, IN PCWSTR ValueName, OUT PULONG Value)
Definition at line 153 of file adtutil.c.
References NULL, REG_DWORD, and SepRegQueryHelper().
Referenced by NtImpersonateAnonymousToken(), SepAdtInitializeAuditingOptions(), and SepAdtInitializeCrashOnFail().
NTSTATUS SepRegQueryHelper (IN PCWSTR KeyName, IN PCWSTR ValueName, IN ULONG ValueType, IN ULONG ValueLength, OUT PVOID ValueBuffer, OUT PULONG LengthRequired)
Definition at line 31 of file adtutil.c.
References ASSERT, InitializeObjectAttributes, KEY_QUERY_VALUE, KeyValuePartialInformation, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_BINARY, REG_DWORD, RtlCopyMemory, RtlInitUnicodeString(), Status, STATUS_INVALID_PARAMETER, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by SepAdtInitializeBounds(), and SepRegQueryDwordValue().