Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/flushsec.c File Reference
flushsec.c File Reference
#include "mi.h"
Data Structures
struct _MI_FLUSH_ARRAY
struct _MI_FLUSH_ENTRY
Macros
#define MI_LOG_DEREF_INFO(a, b, c)
#define MI_MAX_FLUSH_MDLS 8
Typedefs
typedef struct _MI_FLUSH_ARRAY MI_FLUSH_ARRAY
typedef struct _MI_FLUSH_ENTRY MI_FLUSH_ENTRY
typedef struct _MI_FLUSH_ARRAY * PMI_FLUSH_ARRAY
typedef struct _MI_FLUSH_ENTRY * PMI_FLUSH_ENTRY
Functions
LOGICAL MiCheckProtoPtePageState (IN PMMPTE PrototypePte, IN KIRQL OldIrql, OUT PLOGICAL DroppedPfnLock)
VOID MiFlushAcquire (IN PCONTROL_AREA ControlArea)
VOID MiFlushComplete (IN PVOID Context, IN PIO_STATUS_BLOCK IoStatus, IN ULONG Reserved)
VOID MiFlushDirtyBitsToPfn (IN PMMPTE PointerPte, IN PMMPTE LastPte, IN PEPROCESS Process, IN PCONTROL_AREA ControlArea)
VOID MiFlushRelease (IN PCONTROL_AREA ControlArea)
NTSTATUS MiFlushSectionInternal (IN PMMPTE StartingPte, IN PMMPTE FinalPte, IN PSUBSECTION FirstSubsection, IN PSUBSECTION LastSubsection, IN ULONG Flags, OUT PIO_STATUS_BLOCK IoStatus)
PSUBSECTION MiGetSystemCacheSubsection (IN PVOID BaseAddress, OUT PMMPTE *ProtoPte)
BOOLEAN MmFlushImageSection (__in PSECTION_OBJECT_POINTERS SectionPointer, __in MMFLUSH_TYPE FlushType)
NTSTATUS MmFlushSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset, IN SIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus, IN ULONG Flags)
NTSTATUS MmFlushVirtualMemory (IN PEPROCESS Process, IN OUT PVOID *BaseAddress, IN OUT PSIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus)
BOOLEAN MmPurgeSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset, IN SIZE_T RegionSize, IN ULONG IgnoreCacheViews)
NTSTATUS NtFlushVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __out PIO_STATUS_BLOCK IoStatus)
Variables
POBJECT_TYPE IoFileObjectType
Macro Definition Documentation
#define MI_LOG_DEREF_INFO (a, b, c)
Referenced by MiFlushSectionInternal().
#define MI_MAX_FLUSH_MDLS 8
Definition at line 1118 of file flushsec.c.
Referenced by MiFlushSectionInternal().
Typedef Documentation
typedef struct _MI_FLUSH_ARRAY MI_FLUSH_ARRAY
typedef struct _MI_FLUSH_ENTRY MI_FLUSH_ENTRY
typedef struct _MI_FLUSH_ARRAY * PMI_FLUSH_ARRAY
typedef struct _MI_FLUSH_ENTRY * PMI_FLUSH_ENTRY
Function Documentation
LOGICAL MiCheckProtoPtePageState (IN PMMPTE PrototypePte, IN KIRQL OldIrql, OUT PLOGICAL DroppedPfnLock)
Definition at line 3476 of file flushsec.c.
References ActiveAndValid, _MMPFN::e1, FALSE, _MMPTE::Hard, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MiCheckPdeForPagedPool(), MiGetPdeAddress, MiGetPteAddress, MiMakeSystemAddressValidPfn(), MM_NOIRQL, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Prototype, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
Referenced by MiCleanSection(), MiFlushSectionInternal(), MiRemoveUnusedSegments(), and MmPurgeSection().
VOID MiFlushAcquire (IN PCONTROL_AREA ControlArea)
Definition at line 207 of file flushsec.c.
References ASSERT, LOCK_PFN, and UNLOCK_PFN.
Referenced by NtAllocateVirtualMemory().
VOID MiFlushComplete (IN PVOID Context, IN PIO_STATUS_BLOCK IoStatus, IN ULONG Reserved)
Definition at line 1130 of file flushsec.c.
References APC_LEVEL, ASSERT, FALSE, _MI_FLUSH_ENTRY::IoEvent, _MI_FLUSH_ENTRY::IoStatus, KeGetCurrentIrql(), KeSetEvent(), _MI_FLUSH_ENTRY::LastPage, LOCK_PFN, _MDL::MappedSystemVa, _MI_FLUSH_ENTRY::Mdl, MDL_MAPPED_TO_SYSTEM_VA, _MDL::MdlFlags, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MmUnmapLockedPages(), NT_SUCCESS, UNLOCK_PFN, and UNREFERENCED_PARAMETER.
Referenced by MiFlushSectionInternal().
VOID MiFlushDirtyBitsToPfn (IN PMMPTE PointerPte, IN PMMPTE LastPte, IN PEPROCESS Process, IN PCONTROL_AREA ControlArea)
Definition at line 3284 of file flushsec.c.
References ASSERT, _MMPTE_FLUSH_LIST::Count, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_PFN, MI_IS_PTE_DIRTY, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PTE_CLEAN, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiFlushPteList(), MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MM_MAXIMUM_FLUSH_COUNT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmFlushVirtualMemory().
VOID MiFlushRelease (IN PCONTROL_AREA ControlArea)
Definition at line 242 of file flushsec.c.
References ASSERT, LOCK_PFN, and MiCheckControlArea().
Referenced by MmFlushVirtualMemory(), and NtAllocateVirtualMemory().
NTSTATUS MiFlushSectionInternal (IN PMMPTE StartingPte, IN PMMPTE FinalPte, IN PSUBSECTION FirstSubsection, IN PSUBSECTION LastSubsection, IN ULONG Flags, OUT PIO_STATUS_BLOCK IoStatus)
Definition at line 1248 of file flushsec.c.
References _MMSECTION_FLAGS::Accessed, APC_LEVEL, ASSERT, _MDL::ByteCount, _MMSECTION_FLAGS::CollidedFlush, DbgBreakPoint(), DbgPrintEx(), _MSUBSECTION::DereferenceList, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MI_FLUSH_ARRAY::FlushEntry, _CONTROL_AREA::FlushInProgressCount, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _IO_STATUS_BLOCK::Information, InsertTailList(), IoAsynchronousPageWrite(), _MI_FLUSH_ENTRY::IoEvent, IoPagingPriorityNormal, _MI_FLUSH_ENTRY::IoStatus, IoSynchronousPageWrite(), KeClearEvent(), KeDelayExecutionThread(), KeGetCurrentIrql(), KeInitializeEvent(), KeLowerIrql, KePulseEvent(), KeRaiseIrql, KeReadStateEvent(), KernelMode, KeWaitForMultipleObjects(), KeWaitForSingleObject(), _MI_FLUSH_ENTRY::LastPage, LOCK_PFN, _MDL::MappedSystemVa, _MI_FLUSH_ENTRY::Mdl, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_DEFER_PFN_HELD, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_INITIALIZE_ZERO_MDL, MI_LOG_DEREF_INFO, MI_MAX_FLUSH_MDLS, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MiCheckProtoPtePageState(), MiDeferredUnlockPages(), MiDereferenceSegmentThread(), MiEndingOffset(), MiFlushComplete(), MiGetPteAddress, MiIoRetryMask, MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), MiStartingOffset(), MiUnlinkPageFromList(), Mm30Milliseconds, MM_FLUSH_ASYNCHRONOUS, MM_FLUSH_FAIL_COLLISIONS, MM_FLUSH_IN_PARALLEL, MM_FLUSH_SEG_DEREF, MM_MAXIMUM_DISK_IO_SIZE, MmCollidedFlushEvent, MmIsRetryIoStatus, MmModifiedWriteClusterSize, MmOneSecond, MmPfnDeferredList, MmUnmapLockedPages(), MmUnusedSubsectionList, _MMPFNENTRY::Modified, _SUBSECTION::NextSubsection, NonPagedPool, NotificationEvent, NT_ERROR, NT_SUCCESS, NULL, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPFNENTRY::PageColor, PASSIVE_LEVEL, _MMSECTION_FLAGS::PhysicalMemory, _MMPTE_SOFTWARE::Prototype, PsGetCurrentThread(), _MMPFN::PteAddress, _SUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _MDL::Size, _MMPTE::Soft, _MDL::StartVa, Status, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, _MMSUBSECTION_FLAGS2::SubsectionAccessed, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MSUBSECTION::u2, _MMPFN::u3, ULongToPtr, UNLOCK_PFN, UNLOCK_PFN_AND_THEN_WAIT, _MMPTE_HARDWARE::Valid, WaitAny, _MI_FLUSH_ARRAY::WaitBlockArray, _MI_FLUSH_ARRAY::WaitObjects, _MMPFNENTRY::WriteInProgress, and WrPageOut.
Referenced by MiRemoveUnusedSegments(), MmFlushSection(), and MmFlushVirtualMemory().
PSUBSECTION MiGetSystemCacheSubsection (IN PVOID BaseAddress, OUT PMMPTE * ProtoPte)
Definition at line 3458 of file flushsec.c.
References MiGetPteAddress, and MiGetSubsectionAndProtoFromPte().
BOOLEAN MmFlushImageSection (__in PSECTION_OBJECT_POINTERS SectionPointer, __in MMFLUSH_TYPE FlushType)
Definition at line 3106 of file flushsec.c.
References ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, CheckImageSection, CONTAINING_RECORD, FALSE, _CONTROL_AREA::Flags, _LARGE_CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, IsListEmpty, LOCK_PFN, MiCheckControlArea(), MiCheckControlAreaStatus(), MiCleanSection(), MmFlushForDelete, NOTHING, NULL, _CONTROL_AREA::NumberOfMappedViews, _LARGE_CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfUserReferences, TRUE, _CONTROL_AREA::u, _LARGE_CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by MiCanFileBeTruncatedInternal().
NTSTATUS MmFlushSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset , IN SIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus, IN ULONG Flags)
Definition at line 715 of file flushsec.c.
References ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, BYTE_OFFSET, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _ETHREAD::ForwardClusterOnly, FsRtlAcquireFileForCcFlushEx(), FsRtlReleaseFileForCcFlush(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, KeDelayExecutionThread(), KernelMode, _MAPPED_FILE_SEGMENT::LastSubsectionHint, LOCK_PFN, MiCheckControlArea(), MiDecrementSubsections(), MiFlushSectionInternal(), MiIsAddressValid(), MiReferenceSubsection(), MM_FLUSH_ACQUIRE_FILE, MmShortTime, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, PAGE_SHIFT, _MMSECTION_FLAGS::PhysicalMemory, PsGetCurrentThread(), _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, STATUS_FILE_LOCK_CONFLICT, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by CcFlushCache(), CcMapAndCopy(), CcMdlWriteComplete2(), CcPurgeAndClearCacheSection(), CcSetFileSizes(), CcUnpinRepinnedBcb(), and MiFlushDataSection().
NTSTATUS MmFlushVirtualMemory (IN PEPROCESS Process, IN OUT PVOID * BaseAddress, IN OUT PSIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus)
Definition at line 281 of file flushsec.c.
References ASSERT, _MMVAD::ControlArea, _MMVAD::EndingVpn, FALSE, _CONTROL_AREA::FilePointer, FsRtlAcquireFileForCcFlushEx(), FsRtlReleaseFileForCcFlush(), KeAreAllApcsDisabled(), KeDelayExecutionThread(), KeMemoryBarrier(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_IS_SESSION_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_VA_TO_VPN, MI_VPN_TO_VA_ENDING, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiFlushDirtyBitsToPfn(), MiFlushRelease(), MiFlushSectionInternal(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiLocateAddress(), MiLocateSubsection(), MM_FLUSH_ASYNCHRONOUS, MM_NOIRQL, MmShortTime, MmWorkingSetList, MmWsle, _SUBSECTION::NextSubsection, NT_SUCCESS, NULL, PAGE_ALIGN, PAGE_SIZE, PAGED_CODE, _MMVAD_FLAGS::PrivateMemory, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _SUBSECTION::PtesInSubsection, Status, STATUS_FILE_LOCK_CONFLICT, STATUS_NOT_MAPPED_DATA, STATUS_NOT_MAPPED_VIEW, STATUS_PROCESS_IS_TERMINATING, _SUBSECTION::SubsectionBase, TRUE, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, _MMVAD::VadFlags, VadImageMap, and _MMVAD_FLAGS::VadType.
Referenced by NtFlushVirtualMemory().
BOOLEAN MmPurgeSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset , IN SIZE_T RegionSize, IN ULONG IgnoreCacheViews)
Definition at line 2366 of file flushsec.c.
References APC_LEVEL, ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::BeingDeleted, _MMSECTION_FLAGS::BeingPurged, BYTE_OFFSET, _MSUBSECTION::DereferenceList, DISPATCH_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, InsertTailList(), KeBugCheckEx(), KeGetCurrentIrql(), KeLowerIrql, KernelMode, KeWaitForSingleObject(), _MAPPED_FILE_SEGMENT::LastSubsectionHint, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MI_WRITE_INVALID_PTE, MiCancelWriteOfMappedPfn(), MiCanFileBeTruncatedInternal(), MiCheckControlArea(), MiCheckProtoPtePageState(), MiDecrementShareCountInline, MiDecrementSubsections(), MiGetPteAddress, MiInsertPageInFreeList(), MiIsAddressValid(), MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), MiReferenceSubsection(), MiReleasePageFileSpace(), MiUnlinkPageFromList(), MM_NOIRQL, MmMappedFileIoComplete, MmUnusedSubsectionList, _CONTROL_AREA::ModifiedWriteCount, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NULL, _CONTROL_AREA::NumberOfMappedViews, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, _CONTROL_AREA::NumberOfSystemCacheViews, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, POOL_CORRUPTION_IN_FILE_AREA, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteAddress, _MMPFN::PteFrame, _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _MMPFNENTRY::ReadInProgress, RemoveEntryList(), _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, _MMSECTION_FLAGS::SetMappedFileIoComplete, _MMPTE::Soft, _MMSUBSECTION_FLAGS2::SubsectionAccessed, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MSUBSECTION::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_PFN_AND_THEN_WAIT, _MMPTE_HARDWARE::Valid, _MMSECTION_FLAGS::WasPurged, _MMPFNENTRY::WriteInProgress, and WrPageOut.
Referenced by CcPurgeCacheSection(), MiLoadImageSection(), and MmCheckSystemImage().
NTSTATUS NtFlushVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 43 of file flushsec.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, MM_HIGHEST_USER_ADDRESS, MmFlushVirtualMemory(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGED_CODE, ProbeForWriteIoStatus, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PsProcessType, Status, and STATUS_INVALID_PARAMETER_2.
Variable Documentation
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.