Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obinit.c File Reference
obinit.c File Reference
#include "obp.h"
Data Structures
struct _OBP_FIND_HANDLE_DATA
Macros
#define OBJ_SECURITY_MODE_BNO_RESTRICTED 1
#define OBJECT_NAME_BUFFER_SIZE 248
#define ObpGlobalDosDevicesShortName L"\\GLOBAL??"
Typedefs
typedef struct _OBP_FIND_HANDLE_DATA OBP_FIND_HANDLE_DATA
typedef struct _OBP_FIND_HANDLE_DATA * POBP_FIND_HANDLE_DATA
Functions
BOOLEAN ObAuditInheritedHandleProcedure (IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleId, IN PVOID EnumParameter)
VOID ObClearProcessHandleTable (PEPROCESS Process)
VOID ObDestroyHandleProcedure (IN HANDLE HandleIndex)
BOOLEAN ObDupHandleProcedure (PEPROCESS Process, PHANDLE_TABLE OldObjectTable, PHANDLE_TABLE_ENTRY OldObjectTableEntry, PHANDLE_TABLE_ENTRY ObjectTableEntry)
BOOLEAN ObFindHandleForObject (__in PEPROCESS Process, __in_opt PVOID Object OPTIONAL, __in_opt POBJECT_TYPE ObjectType OPTIONAL, __in_opt POBJECT_HANDLE_INFORMATION HandleInformation, __out PHANDLE Handle)
ULONG ObGetSecurityMode ()
NTSTATUS ObInitProcess (PEPROCESS ParentProcess OPTIONAL, PEPROCESS NewProcess)
VOID ObInitProcess2 (PEPROCESS NewProcess)
BOOLEAN ObInitSystem (VOID)
VOID ObKillProcess (PEPROCESS Process)
BOOLEAN ObpCloseHandleProcedure (IN PHANDLE_TABLE_ENTRY HandleTableEntry, IN HANDLE Handle, IN PVOID EnumParameter)
NTSTATUS ObpCreateDosDevicesDirectory (VOID)
BOOLEAN ObpEnumFindHandleProcedure (PHANDLE_TABLE_ENTRY ObjectTableEntry, HANDLE HandleId, PVOID EnumParameter)
VOID ObpFreeDosDevicesProtection (PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSTATUS ObpGetDosDevicesProtection (PSECURITY_DESCRIPTOR SecurityDescriptor)
BOOLEAN ObpShutdownCloseHandleProcedure (IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleId, IN PVOID EnumParameter)
VOID ObShutdownSystem (IN ULONG Phase)
Variables
ULONG MmNumberOfPagingFiles
ULONG ObpAccessProtectCloseBit = MAXIMUM_ALLOWED
ULONG ObpAuditBaseDirectories
ULONG ObpAuditBaseObjects
GENERAL_LOOKASIDE ObpCreateInfoLookasideList
const GENERIC_MAPPING ObpDirectoryMapping
const UNICODE_STRING ObpDosDevicesShortName
const ALIGNEDNAME ObpDosDevicesShortNamePrefix = { L'\\',L'?',L'?',L'\\' }
const ALIGNEDNAME ObpDosDevicesShortNameRoot = { L'\\',L'?',L'?',L'\0' }
ULONG ObpLUIDDeviceMapsDisabled
ULONG ObpLUIDDeviceMapsEnabled
GENERAL_LOOKASIDE ObpNameBufferLookasideList
ULONG ObpObjectSecurityMode = OBJ_SECURITY_MODE_BNO_RESTRICTED
ULONG ObpProtectionMode
const GENERIC_MAPPING ObpSymbolicLinkMapping
const GENERIC_MAPPING ObpTypeMapping
PLIST_ENTRY * ObsSecurityDescriptorCache
PDEVICE_MAP ObSystemDeviceMap = NULL
Macro Definition Documentation
#define OBJ_SECURITY_MODE_BNO_RESTRICTED 1
Definition at line 165 of file obinit.c.
#define OBJECT_NAME_BUFFER_SIZE 248
Definition at line 31 of file obinit.c.
Referenced by ObInitSystem(), ObpAllocateObjectNameBuffer(), and ObpFreeObjectNameBuffer().
#define ObpGlobalDosDevicesShortName L"\\GLOBAL??"
Definition at line 216 of file obinit.c.
Referenced by ObpCreateDosDevicesDirectory().
Typedef Documentation
typedef struct _OBP_FIND_HANDLE_DATA OBP_FIND_HANDLE_DATA
typedef struct _OBP_FIND_HANDLE_DATA * POBP_FIND_HANDLE_DATA
Function Documentation
BOOLEAN ObAuditInheritedHandleProcedure (IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleId, IN PVOID EnumParameter)
Definition at line 1033 of file obinit.c.
References FALSE, OBJ_AUDIT_OBJECT_CLOSE, _SE_PROCESS_AUDIT_INFO::Parent, _SE_PROCESS_AUDIT_INFO::Process, and SeAuditHandleDuplication().
Referenced by ObInitProcess().
VOID ObClearProcessHandleTable (PEPROCESS Process)
Definition at line 1318 of file obinit.c.
References ExSweepHandleTable(), FALSE, _OBP_SWEEP_CONTEXT::HandleTable, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, ObDereferenceProcessHandleTable(), ObpCloseHandleProcedure(), ObReferenceProcessHandleTable(), _EPROCESS::Pcb, _OBP_SWEEP_CONTEXT::PreviousMode, PsGetCurrentProcessByThread, PsGetCurrentThread(), _ETHREAD::Tcb, TRUE, and UserMode.
Referenced by NtTerminateProcess(), and PspTerminateProcess().
VOID ObDestroyHandleProcedure (IN HANDLE HandleIndex)
Definition at line 1252 of file obinit.c.
References ZwClose().
BOOLEAN ObDupHandleProcedure (PEPROCESS Process, PHANDLE_TABLE OldObjectTable, PHANDLE_TABLE_ENTRY OldObjectTableEntry, PHANDLE_TABLE_ENTRY ObjectTableEntry)
Definition at line 924 of file obinit.c.
References _OBJECT_HEADER::Body, ExUnlockHandleTableEntry(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KernelMode, NT_SUCCESS, NtGlobalFlag, _HANDLE_TABLE_ENTRY::ObAttributes, ObDereferenceObject(), ObInheritHandle, OBJ_HANDLE_ATTRIBUTES, OBJ_INHERIT, _HANDLE_TABLE_ENTRY::Object, ObpDecodeGrantedAccess, ObpIncrementHandleCount(), ObpIncrPointerCount, ObpTranslateGrantedAccessIndex(), _ACCESS_STATE::PreviouslyGrantedAccess, Status, TRUE, and _OBJECT_HEADER::Type.
Referenced by ObInitProcess().
BOOLEAN ObFindHandleForObject (__in PEPROCESS Process, __in_opt PVOID Object OPTIONAL, __in_opt POBJECT_TYPE ObjectType OPTIONAL, __in_opt POBJECT_HANDLE_INFORMATION HandleInformation, __out PHANDLE Handle)
Definition at line 1590 of file obinit.c.
References ARGUMENT_PRESENT, ExEnumHandleTable(), FALSE, _OBP_FIND_HANDLE_DATA::HandleInformation, NULL, ObDereferenceProcessHandleTable(), OBJECT_TO_OBJECT_HEADER, _OBP_FIND_HANDLE_DATA::ObjectHeader, _OBP_FIND_HANDLE_DATA::ObjectType, ObpEnumFindHandleProcedure(), ObReferenceProcessHandleTable(), and TRUE.
ULONG ObGetSecurityMode ()
Definition at line 2614 of file obinit.c.
References ObpObjectSecurityMode.
Referenced by NtQuerySystemInformation().
NTSTATUS ObInitProcess (PEPROCESS ParentProcess OPTIONAL, PEPROCESS NewProcess)
Definition at line 1089 of file obinit.c.
References ARGUMENT_PRESENT, ExCreateHandleTable(), ExDupHandleTable(), ExEnumHandleTable(), NULL, ObAuditInheritedHandleProcedure(), ObDereferenceProcessHandleTable(), ObDupHandleProcedure(), OBJ_INHERIT, _EPROCESS::ObjectTable, ObReferenceProcessHandleTable(), _SE_PROCESS_AUDIT_INFO::Parent, _SE_PROCESS_AUDIT_INFO::Process, SeDetailedAuditingWithToken(), STATUS_INSUFFICIENT_RESOURCES, STATUS_PROCESS_IS_TERMINATING, and STATUS_SUCCESS.
Referenced by PspCreateProcess().
VOID ObInitProcess2 (PEPROCESS NewProcess)
Definition at line 1214 of file obinit.c.
References ExSetHandleTableOrder, _EPROCESS::ObjectTable, and _EPROCESS::SubSystemVersion.
BOOLEAN ObInitSystem (VOID)
Definition at line 224 of file obinit.c.
References ACL_REVISION, ACL_REVISION2, ASSERT, _OBJECT_TYPE_INITIALIZER::CaseInsensitive, CONTAINER_INHERIT_ACE, CONTAINING_RECORD, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_ALL_ACCESS, DIRECTORY_QUERY, DIRECTORY_TRAVERSE, ExAllocatePoolWithTag, ExCreateHandleTable(), ExFreePool(), ExInitializePushLock(), ExInitializeSystemLookasideList(), ExInitializeWorkItem, ExSetHandleTableStrictFIFO(), ExSystemLookasideListHead, FALSE, FLG_KERNEL_STACK_TRACE_DB, _LIST_ENTRY::Flink, GENERIC_ALL, _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, _ETHREAD::GrantedAccess, Index, INHERIT_ONLY_ACE, InitializationPhase, InitializeObjectAttributes, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KeGetCurrentPrcb(), KeInitializeEvent(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeNumberProcessors, KernelMode, KiProcessorBlock, _PP_LOOKASIDE_LIST::L, _OBJECT_TYPE_INITIALIZER::Length, LookasideCreateInfoList, LookasideNameBufferList, _OBJECT_TYPE_INITIALIZER::MaintainTypeList, MmIsThisAnNtAsSystem(), MmLargeSystem, MmQuerySystemSize(), _OBJECT_HEADER_NAME_INFO::Name, NonPagedPool, NotificationEvent, NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NtGlobalFlag, NULL, OB_NAMESPACE_POOL_TYPE, ObCreateObjectType(), OBJ_CASE_INSENSITIVE, OBJ_OPENLINK, OBJ_PERMANENT, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_INHERIT_ACE, OBJECT_NAME_BUFFER_SIZE, OBJECT_TYPE_ALL_ACCESS, _EPROCESS::ObjectTable, OBP_PAGEDPOOL_NAMESPACE, ObpAccessProtectCloseBit, ObpAuditBaseDirectories, ObpAuditBaseObjects, ObpCreateDosDevicesDirectory(), ObpCreateInfoLookasideList, ObpDefaultObject, ObpDeleteObjectType(), ObpDeleteSymbolicLink(), ObpDeviceMapLock, ObpDirectoryMapping, ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpInitSecurityDescriptorCache(), ObpInsertDirectoryEntry(), ObpKernelHandleTable, ObpLock, ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpNameBufferLookasideList, ObpParseSymbolicLink(), ObpProcessRemoveObjectQueue(), ObpReleaseLookupContext(), ObpRemoveObjectList, ObpRemoveObjectWorkItem, ObpRootDirectoryObject, ObpSymbolicLinkMapping, ObpSymbolicLinkObjectType, ObpTypeDirectoryObject, ObpTypeMapping, ObpTypeObjectType, ObReferenceObjectByHandle, _PP_LOOKASIDE_LIST::P, PAGE_SIZE, PagedPool, _OBJECT_TYPE_INITIALIZER::ParseProcedure, _OBJECT_TYPE_INITIALIZER::PoolType, _KPRCB::PPLookasideList, PROCESS_ALL_ACCESS, PsGetCurrentProcess(), PsGetCurrentThread(), PsInitializeQuotaSystem(), READ_CONTROL, RtlAddAccessAllowedAce(), RtlAddAuditAccessAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlGetAce(), RtlInitUnicodeString(), RtlLengthSid(), RtlSetDaclSecurityDescriptor(), RtlSetSaclSecurityDescriptor(), RtlZeroMemory, SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SECURITY_DESCRIPTOR_REVISION1, SeLengthSid, SeLocalSystemSid, SePublicDefaultUnrestrictedDacl, SePublicDefaultUnrestrictedSd, SeWorldSid, Status, SYMBOLIC_LINK_ALL_ACCESS, SYNCHRONIZE, THREAD_ALL_ACCESS, TRUE, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
VOID ObKillProcess (PEPROCESS Process)
Definition at line 1376 of file obinit.c.
References ASSERT, ExDestroyHandleTable(), ExRundownCompleted(), ExSweepHandleTable(), ExWaitForRundownProtectionRelease(), FALSE, _HANDLE_TABLE::HandleCount, _OBP_SWEEP_CONTEXT::HandleTable, IoSetThreadHardErrorMode(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, NULL, _EPROCESS::ObjectTable, ObpCloseHandleProcedure(), ObpValidateIrql, PAGED_CODE, _OBP_SWEEP_CONTEXT::PreviousMode, and _EPROCESS::RundownProtect.
Referenced by PspExitThread(), and PspProcessDelete().
BOOLEAN ObpCloseHandleProcedure (IN PHANDLE_TABLE_ENTRY HandleTableEntry, IN HANDLE Handle, IN PVOID EnumParameter)
Definition at line 1282 of file obinit.c.
References _OBP_SWEEP_CONTEXT::HandleTable, ObpCloseHandleTableEntry(), _OBP_SWEEP_CONTEXT::PreviousMode, and TRUE.
Referenced by ObClearProcessHandleTable(), and ObKillProcess().
NTSTATUS ObpCreateDosDevicesDirectory (VOID)
Definition at line 1693 of file obinit.c.
References DIRECTORY_ALL_ACCESS, InitializeObjectAttributes, NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NtCreateSymbolicLinkObject(), NULL, OBJ_PERMANENT, ObpFreeDosDevicesProtection(), ObpGetDosDevicesProtection(), ObpGlobalDosDevicesShortName, ObpLUIDDeviceMapsDisabled, ObpLUIDDeviceMapsEnabled, ObpProtectionMode, ObSetDeviceMap(), RtlCreateUnicodeString(), RtlInitUnicodeString(), Status, STATUS_SUCCESS, and SYMBOLIC_LINK_ALL_ACCESS.
Referenced by ObInitSystem().
BOOLEAN ObpEnumFindHandleProcedure (PHANDLE_TABLE_ENTRY ObjectTableEntry, HANDLE HandleId, PVOID EnumParameter)
Definition at line 1481 of file obinit.c.
References ARGUMENT_PRESENT, FALSE, FLG_KERNEL_STACK_TRACE_DB, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, _OBJECT_HANDLE_INFORMATION::HandleAttributes, _OBP_FIND_HANDLE_DATA::HandleInformation, NtGlobalFlag, NULL, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, _OBP_FIND_HANDLE_DATA::ObjectHeader, _OBP_FIND_HANDLE_DATA::ObjectType, ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpTranslateGrantedAccessIndex(), TRUE, _OBJECT_HEADER::Type, and UNREFERENCED_PARAMETER.
Referenced by ObFindHandleForObject().
VOID ObpFreeDosDevicesProtection (PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 2145 of file obinit.c.
References ASSERT, ExFreePool(), NT_SUCCESS, NULL, RtlGetDaclSecurityDescriptor(), and Status.
Referenced by ObpCreateDosDevicesDirectory().
NTSTATUS ObpGetDosDevicesProtection (PSECURITY_DESCRIPTOR SecurityDescriptor)
DaclDefaulted
DaclDefaulted
Definition at line 1885 of file obinit.c.
References ACL_REVISION2, ASSERT, CONTAINER_INHERIT_ACE, ExAllocatePool, FALSE, GENERIC_ALL, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, INHERIT_ONLY_ACE, NT_SUCCESS, NULL, OBJECT_INHERIT_ACE, ObpProtectionMode, PagedPool, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlGetAce(), RtlLengthSid(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SeCreatorOwnerSid, SECURITY_DESCRIPTOR_REVISION, SeLocalSystemSid, SeWorldSid, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by ObpCreateDosDevicesDirectory().
BOOLEAN ObpShutdownCloseHandleProcedure (IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleId, IN PVOID EnumParameter)
Definition at line 2186 of file obinit.c.
References ASSERT, _OBJECT_HEADER::Body, FALSE, KdPrint, OBJ_HANDLE_ATTRIBUTES, and UNREFERENCED_PARAMETER.
Referenced by ObShutdownSystem().
VOID ObShutdownSystem (IN ULONG Phase)
Definition at line 2253 of file obinit.c.
References ASSERT, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, _OBJECT_DIRECTORY_ENTRY::ChainLink, CONTAINING_RECORD, DeleteSecurityDescriptor, _OBJECT_HEADER_NAME_INFO::Directory, ExEnumHandleTable(), ExFreePool(), _OBJECT_HEADER::Flags, _LIST_ENTRY::Flink, _OBJECT_HEADER::HandleCount, _OBJECT_DIRECTORY::HashBuckets, KdPrint, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MmNumberOfPagingFiles, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, NUMBER_HASH_BUCKETS, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, _EPROCESS::ObjectTable, ObMakeTemporaryObject(), ObpBeginTypeSpecificCallOut, ObpDeleteSymbolicLinkName(), ObpDirectoryObjectType, ObpEndTypeSpecificCallOut, ObpLockObject, ObpRootDirectoryObject, ObpShutdownCloseHandleProcedure(), ObpSymbolicLinkObjectType, ObpTypeDirectoryObject, ObpTypeObjectType, ObpUnlockObject, ObReferenceObjectByName(), _OBJECT_TYPE_INITIALIZER::PoolType, PsInitialSystemProcess, RtlInitUnicodeString(), _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, _OBJECT_TYPE_INITIALIZER::SecurityRequired, Status, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE::TypeList.
Variable Documentation
ULONG MmNumberOfPagingFiles
Definition at line 437 of file miglobal.c.
Referenced by ObShutdownSystem().
ULONG ObpAccessProtectCloseBit = MAXIMUM_ALLOWED
Definition at line 155 of file obinit.c.
Referenced by ObInitSystem(), and ObpSetHandleAttributes().
ULONG ObpAuditBaseDirectories
Definition at line 169 of file obinit.c.
Referenced by ObInitSystem().
ULONG ObpAuditBaseObjects
Definition at line 170 of file obinit.c.
Referenced by ObInitSystem().
GENERAL_LOOKASIDE ObpCreateInfoLookasideList
Definition at line 25 of file obinit.c.
Referenced by ObInitSystem().
const GENERIC_MAPPING ObpDirectoryMapping
Initial value:
= {
    STANDARD_RIGHTS_READ |
        DIRECTORY_QUERY |
        DIRECTORY_TRAVERSE,
    STANDARD_RIGHTS_WRITE |
        DIRECTORY_CREATE_OBJECT |
        DIRECTORY_CREATE_SUBDIRECTORY,
    STANDARD_RIGHTS_EXECUTE |
        DIRECTORY_QUERY |
        DIRECTORY_TRAVERSE,
    DIRECTORY_ALL_ACCESS
}
Definition at line 51 of file obinit.c.
Referenced by ObInitSystem().
const UNICODE_STRING ObpDosDevicesShortName
Initial value:
= {
    sizeof(ObpDosDevicesShortNamePrefix),
    sizeof(ObpDosDevicesShortNamePrefix),
    (PWSTR)&ObpDosDevicesShortNamePrefix
}
Definition at line 210 of file obinit.c.
Referenced by ObpLookupObjectName(), and ObpProcessDosDeviceSymbolicLink().
const ALIGNEDNAME ObpDosDevicesShortNamePrefix = { L'\\',L'?',L'?',L'\\' }
Definition at line 208 of file obinit.c.
Referenced by ObpLookupObjectName(), and ObpProcessDosDeviceSymbolicLink().
const ALIGNEDNAME ObpDosDevicesShortNameRoot = { L'\\',L'?',L'?',L'\0' }
Definition at line 209 of file obinit.c.
Referenced by ObpLookupObjectName().
ULONG ObpLUIDDeviceMapsDisabled
Definition at line 168 of file obinit.c.
Referenced by ObpCreateDosDevicesDirectory().
ULONG ObpLUIDDeviceMapsEnabled
Definition at line 188 of file obinit.c.
Referenced by ObIsLUIDDeviceMapsEnabled(), ObpCreateDosDevicesDirectory(), ObpLookupDirectoryEntry(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceDeviceMap(), and ObQueryDeviceMapInformation().
GENERAL_LOOKASIDE ObpNameBufferLookasideList
Definition at line 33 of file obinit.c.
Referenced by ObInitSystem().
ULONG ObpObjectSecurityMode = OBJ_SECURITY_MODE_BNO_RESTRICTED
Definition at line 171 of file obinit.c.
Referenced by ObGetSecurityMode().
ULONG ObpProtectionMode
Definition at line 167 of file obinit.c.
Referenced by ObpCreateDosDevicesDirectory(), and ObpGetDosDevicesProtection().
const GENERIC_MAPPING ObpSymbolicLinkMapping
Initial value:
= {
    STANDARD_RIGHTS_READ |
        SYMBOLIC_LINK_QUERY,
    STANDARD_RIGHTS_WRITE,
    STANDARD_RIGHTS_EXECUTE |
        SYMBOLIC_LINK_QUERY,
    SYMBOLIC_LINK_ALL_ACCESS
}
Definition at line 64 of file obinit.c.
Referenced by ObInitSystem().
const GENERIC_MAPPING ObpTypeMapping
Initial value:
= {
    STANDARD_RIGHTS_READ,
    STANDARD_RIGHTS_WRITE,
    STANDARD_RIGHTS_EXECUTE,
    OBJECT_TYPE_ALL_ACCESS
}
Definition at line 44 of file obinit.c.
Referenced by ObInitSystem().
PLIST_ENTRY* ObsSecurityDescriptorCache
Definition at line 102 of file obsdata.c.
PDEVICE_MAP ObSystemDeviceMap = NULL
Definition at line 158 of file obinit.c.
Referenced by ObInheritDeviceMap(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceDeviceMap(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), and ObSetDirectoryDeviceMap().