Windows Research Kernel v1.2: C:/Windows Research Kernel/se/semethod.c File Reference
semethod.c File Reference
#include "pch.h"
Functions
NTSTATUS SeDefaultObjectMethod (__in PVOID Object, __in SECURITY_OPERATION_CODE OperationCode, __in PSECURITY_INFORMATION SecurityInformation, __inout PSECURITY_DESCRIPTOR SecurityDescriptor, __inout_opt PULONG CapturedLength, __deref_inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
NTSTATUS SepDefaultDeleteMethod (IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor)
VOID SeQuerySecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
NTSTATUS SeQuerySecurityDescriptorInfo (__in PSECURITY_INFORMATION SecurityInformation, __out_bcount(*Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __deref_inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor)
VOID SeSetSecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
NTSTATUS SeSetSecurityDescriptorInfo (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
NTSTATUS SeSetSecurityDescriptorInfoEx (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in ULONG AutoInheritFlags, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Function Documentation
NTSTATUS SeDefaultObjectMethod (__in PVOID Object, __in SECURITY_OPERATION_CODE OperationCode, __in PSECURITY_INFORMATION SecurityInformation, __inout PSECURITY_DESCRIPTOR SecurityDescriptor, __inout_opt PULONG CapturedLength, __deref_inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 190 of file semethod.c.
References ASSERT, AssignSecurityDescriptor, DeleteSecurityDescriptor, KeBugCheckEx(), NonPagedPool, NULL, ObAssignObjectSecurityDescriptor(), ObQuerySecurityDescriptorInfo(), ObSetSecurityDescriptorInfo(), PAGED_CODE, PagedPool, QuerySecurityDescriptor, SECURITY_SYSTEM, SepDefaultDeleteMethod(), SetSecurityDescriptor, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by ObCreateObjectType(), and ObDuplicateObject().
NTSTATUS SepDefaultDeleteMethod (IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor)
Definition at line 915 of file semethod.c.
References ObDeassignSecurity(), and PAGED_CODE.
Referenced by SeDefaultObjectMethod().
VOID SeQuerySecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
Definition at line 133 of file semethod.c.
References ACCESS_SYSTEM_SECURITY, DACL_SECURITY_INFORMATION, GROUP_SECURITY_INFORMATION, OWNER_SECURITY_INFORMATION, PAGED_CODE, READ_CONTROL, and SACL_SECURITY_INFORMATION.
Referenced by IoCheckFunctionAccess(), and NtQuerySecurityObject().
NTSTATUS SeQuerySecurityDescriptorInfo (__in PSECURITY_INFORMATION SecurityInformation, __out_bcount *Length PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __deref_inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor)
Definition at line 554 of file semethod.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, _SECURITY_DESCRIPTOR::Dacl, DACL_SECURITY_INFORMATION, except, EXCEPTION_EXECUTE_HANDLER, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR::Group, GROUP_SECURITY_INFORMATION, LongAlignPtr, LongAlignSize, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, _SECURITY_DESCRIPTOR::Owner, OWNER_SECURITY_INFORMATION, PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlMoveMemory, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpPropagateControlBits, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, _SECURITY_DESCRIPTOR::Sacl, SACL_SECURITY_INFORMATION, SE_DACL_AUTO_INHERITED, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_GROUP_DEFAULTED, SE_OWNER_DEFAULTED, SE_SACL_AUTO_INHERITED, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by CmpCheckKeyAccess(), CmpQuerySecurityDescriptorInfo(), IopGetSetSecurityObject(), and ObQuerySecurityDescriptorInfo().
VOID SeSetSecurityAccessMask (__in SECURITY_INFORMATION SecurityInformation, __out PACCESS_MASK DesiredAccess)
Definition at line 73 of file semethod.c.
References ACCESS_SYSTEM_SECURITY, DACL_SECURITY_INFORMATION, GROUP_SECURITY_INFORMATION, OWNER_SECURITY_INFORMATION, PAGED_CODE, SACL_SECURITY_INFORMATION, WRITE_DAC, and WRITE_OWNER.
Referenced by IoCheckFunctionAccess(), and NtSetSecurityObject().
NTSTATUS SeSetSecurityDescriptorInfo (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 359 of file semethod.c.
References NULL, RtlpSetSecurityObject(), and STATUS_NO_SECURITY_ON_OBJECT.
Referenced by CmpSetSecurityDescriptorInfo(), IopSetDeviceSecurityDescriptor(), and ObSetSecurityDescriptorInfo().
NTSTATUS SeSetSecurityDescriptorInfoEx (__in_opt PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR ModificationDescriptor, __inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in ULONG AutoInheritFlags, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 446 of file semethod.c.
References NULL, PAGED_CODE, RtlpSetSecurityObject(), and STATUS_NO_SECURITY_ON_OBJECT.