Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/amd64/raise.c File Reference
raise.c File Reference
#include "ntrtlp.h"
Functions
DECLSPEC_NOINLINE VOID RtlRaiseException (IN PEXCEPTION_RECORD ExceptionRecord)
DECLSPEC_NOINLINE VOID RtlRaiseStatus (IN NTSTATUS Status)
Function Documentation
DECLSPEC_NOINLINE VOID RtlRaiseException (IN PEXCEPTION_RECORD ExceptionRecord)
Definition at line 24 of file raise.c.
References FALSE, NULL, RtlCaptureContext(), RtlDispatchException(), RtlLookupFunctionEntry(), RtlRaiseStatus(), RtlVirtualUnwind(), Status, STATUS_INVALID_DISPOSITION, UNW_FLAG_NHANDLER, and ZwRaiseException().
Referenced by RtlDispatchException(), and RtlUnwind().
DECLSPEC_NOINLINE VOID RtlRaiseStatus (IN NTSTATUS Status)
Definition at line 98 of file raise.c.
References EXCEPTION_NONCONTINUABLE, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionFlags, _EXCEPTION_RECORD::ExceptionRecord, FALSE, NULL, _EXCEPTION_RECORD::NumberParameters, RtlCaptureContext(), RtlDispatchException(), Status, and ZwRaiseException().
Referenced by InitializeSListHead(), RtlDispatchException(), RtlInitializeContext(), RtlLargeIntegerDivide(), RtlRaiseException(), and RtlUnwindEx().