Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/pnp.h File Reference
pnp.h File Reference
Data Structures
struct _ACPI_CMOS_INTERFACE_STANDARD
struct _ACPI_INTERFACE_STANDARD
struct _AGP_TARGET_BUS_INTERFACE_STANDARD
struct _ARBITER_CONFLICT_INFO
struct _ARBITER_INTERFACE
struct _ARBITER_LIST_ENTRY
struct _ARBITER_PARAMETERS
struct _BUS_INTERFACE_STANDARD
struct _DEVICE_INTERFACE_CHANGE_NOTIFICATION
struct _HAL_PORT_RANGE_INTERFACE
struct _HWPROFILE_CHANGE_NOTIFICATION
struct _INT_ROUTE_INTERFACE_STANDARD
struct _LEGACY_BUS_INFORMATION
struct _LEGACY_DEVICE_DETECTION_INTERFACE
struct _PLUGPLAY_NOTIFICATION_HEADER
struct _PNP_BUS_INFORMATION
struct _PNP_LOCATION_INTERFACE
struct _TARGET_DEVICE_CUSTOM_NOTIFICATION
struct _TARGET_DEVICE_REMOVAL_NOTIFICATION
struct _TRANSLATOR_INTERFACE
struct ACPI_REGS_INTERFACE_STANDARD
struct ROUTING_TOKEN
Macros
#define ARBITER_FLAG_BOOT_CONFIG 0x00000001
#define ARBITER_PARTIAL 0x00000001
#define DEVICE_INTERFACE_INCLUDE_NONACTIVE 0x00000001
#define IoAdjustPagingPathCount(_count_, _paging_)
#define PCI_INT_ROUTE_INTRF_STANDARD_VER 1
#define PCI_MSI_ROUTING 0x1
#define PCI_STATIC_ROUTING 0x2
#define PLUGPLAY_REGKEY_CURRENT_HWPROFILE 4
#define PLUGPLAY_REGKEY_DEVICE 1
#define PLUGPLAY_REGKEY_DRIVER 2
#define PNPNOTIFY_DEVICE_INTERFACE_INCLUDE_EXISTING_INTERFACES 0x00000001
#define TDF_DEVICEEJECTABLE 0x00000001
#define TDF_KERNEL_INITIATED 0x00000004
#define TDF_NO_RESTART 0x00000002
#define TDF_ONLY_RESTART_RELATIONS 0x00000008
Typedefs
typedef struct _ACPI_CMOS_INTERFACE_STANDARD ACPI_CMOS_INTERFACE_STANDARD
typedef struct _ACPI_INTERFACE_STANDARD ACPI_INTERFACE_STANDARD
typedef enum _ACPI_REG_TYPE ACPI_REG_TYPE
typedef struct ACPI_REGS_INTERFACE_STANDARD ACPI_REGS_INTERFACE_STANDARD
typedef struct _AGP_TARGET_BUS_INTERFACE_STANDARD AGP_TARGET_BUS_INTERFACE_STANDARD
typedef enum _ARBITER_ACTION ARBITER_ACTION
typedef struct _ARBITER_CONFLICT_INFO ARBITER_CONFLICT_INFO
typedef struct _ARBITER_INTERFACE ARBITER_INTERFACE
typedef struct _ARBITER_LIST_ENTRY ARBITER_LIST_ENTRY
typedef struct _ARBITER_PARAMETERS ARBITER_PARAMETERS
typedef enum _ARBITER_REQUEST_SOURCE ARBITER_REQUEST_SOURCE
typedef enum _ARBITER_RESULT ARBITER_RESULT
typedef struct _BUS_INTERFACE_STANDARD BUS_INTERFACE_STANDARD
typedef enum _CMOS_DEVICE_TYPE CMOS_DEVICE_TYPE
typedef enum _DEVICE_INSTALL_STATE DEVICE_INSTALL_STATE
typedef struct _DEVICE_INTERFACE_CHANGE_NOTIFICATION DEVICE_INTERFACE_CHANGE_NOTIFICATION
typedef enum _DEVICE_REMOVAL_POLICY DEVICE_REMOVAL_POLICY
typedef struct _HAL_PORT_RANGE_INTERFACE HAL_PORT_RANGE_INTERFACE
typedef struct _HWPROFILE_CHANGE_NOTIFICATION HWPROFILE_CHANGE_NOTIFICATION
typedef struct _INT_ROUTE_INTERFACE_STANDARD INT_ROUTE_INTERFACE_STANDARD
typedef enum _IO_NOTIFICATION_EVENT_CATEGORY IO_NOTIFICATION_EVENT_CATEGORY
typedef struct _LEGACY_BUS_INFORMATION LEGACY_BUS_INFORMATION
typedef struct _LEGACY_DEVICE_DETECTION_INTERFACE LEGACY_DEVICE_DETECTION_INTERFACE
typedef struct _ACPI_CMOS_INTERFACE_STANDARD * PACPI_CMOS_INTERFACE_STANDARD
typedef struct _ACPI_INTERFACE_STANDARD * PACPI_INTERFACE_STANDARD
typedef enum _ACPI_REG_TYPE * PACPI_REG_TYPE
typedef struct ACPI_REGS_INTERFACE_STANDARD * PACPI_REGS_INTERFACE_STANDARD
typedef struct _AGP_TARGET_BUS_INTERFACE_STANDARD * PAGP_TARGET_BUS_INTERFACE_STANDARD
typedef enum _ARBITER_ACTION * PARBITER_ACTION
typedef struct _ARBITER_CONFLICT_INFO * PARBITER_CONFLICT_INFO
typedef NTSTATUS(* PARBITER_HANDLER) (IN PVOID Context, IN ARBITER_ACTION Action, IN OUT PARBITER_PARAMETERS Parameters)
typedef struct _ARBITER_INTERFACE * PARBITER_INTERFACE
typedef struct _ARBITER_LIST_ENTRY * PARBITER_LIST_ENTRY
typedef struct _ARBITER_PARAMETERS * PARBITER_PARAMETERS
typedef struct _BUS_INTERFACE_STANDARD * PBUS_INTERFACE_STANDARD
typedef VOID(* PDEVICE_CHANGE_COMPLETE_CALLBACK) (IN PVOID Context)
typedef enum _DEVICE_INSTALL_STATE * PDEVICE_INSTALL_STATE
typedef struct _DEVICE_INTERFACE_CHANGE_NOTIFICATION * PDEVICE_INTERFACE_CHANGE_NOTIFICATION
typedef VOID(* PDEVICE_NOTIFY_CALLBACK) (PVOID, ULONG)
typedef enum _DEVICE_REMOVAL_POLICY * PDEVICE_REMOVAL_POLICY
typedef NTSTATUS(* PDRIVER_NOTIFICATION_CALLBACK_ROUTINE) (IN PVOID NotificationStructure, IN PVOID Context)
typedef struct _DMA_ADAPTER *(* PGET_DMA_ADAPTER) (IN PVOID Context, IN struct _DEVICE_DESCRIPTION *DeviceDescriptor, OUT PULONG NumberOfMapRegisters)
typedef NTSTATUS(* PGET_INTERRUPT_ROUTING) (IN PDEVICE_OBJECT Pdo, OUT ULONG *Bus, OUT ULONG *PciSlot, OUT UCHAR *InterruptLine, OUT UCHAR *InterruptPin, OUT UCHAR *ClassCode, OUT UCHAR *SubClassCode, OUT PDEVICE_OBJECT *ParentPdo, OUT ROUTING_TOKEN *RoutingToken, OUT UCHAR *Flags)
typedef NTSTATUS(* PGET_LOCATION_STRING) (IN PVOID Context, OUT PWCHAR *LocationStrings)
typedef ULONG(* PGET_SET_DEVICE_DATA) (IN PVOID Context, IN ULONG DataType, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
typedef NTSTATUS(* PGPE_CLEAR_STATUS) (PDEVICE_OBJECT, PVOID)
typedef NTSTATUS(* PGPE_CONNECT_VECTOR) (PDEVICE_OBJECT, ULONG, KINTERRUPT_MODE, BOOLEAN, PGPE_SERVICE_ROUTINE, PVOID, PVOID)
typedef NTSTATUS(* PGPE_DISABLE_EVENT) (PDEVICE_OBJECT, PVOID)
typedef NTSTATUS(* PGPE_DISCONNECT_VECTOR) (PVOID)
typedef NTSTATUS(* PGPE_ENABLE_EVENT) (PDEVICE_OBJECT, PVOID)
typedef BOOLEAN(* PGPE_SERVICE_ROUTINE) (PVOID, PVOID)
typedef VOID(* PHAL_FREE_PORT_RANGE) (IN USHORT RangeId)
typedef struct _HAL_PORT_RANGE_INTERFACE * PHAL_PORT_RANGE_INTERFACE
typedef NTSTATUS(* PHAL_QUERY_ALLOCATE_PORT_RANGE) (IN BOOLEAN IsSparse, IN BOOLEAN PrimaryIsMmio, IN PVOID VirtBaseAddr OPTIONAL, IN PHYSICAL_ADDRESS PhysBaseAddr, IN ULONG Length, OUT PUSHORT NewRangeId)
typedef struct _HWPROFILE_CHANGE_NOTIFICATION * PHWPROFILE_CHANGE_NOTIFICATION
typedef struct _INT_ROUTE_INTERFACE_STANDARD * PINT_ROUTE_INTERFACE_STANDARD
typedef struct _LEGACY_BUS_INFORMATION * PLEGACY_BUS_INFORMATION
typedef NTSTATUS(* PLEGACY_DEVICE_DETECTION_HANDLER) (IN PVOID Context, IN INTERFACE_TYPE LegacyBusType, IN ULONG BusNumber, IN ULONG SlotNumber, OUT PDEVICE_OBJECT *PhysicalDeviceObject)
typedef struct _LEGACY_DEVICE_DETECTION_INTERFACE * PLEGACY_DEVICE_DETECTION_INTERFACE
typedef struct _PLUGPLAY_NOTIFICATION_HEADER PLUGPLAY_NOTIFICATION_HEADER
typedef struct _PNP_BUS_INFORMATION PNP_BUS_INFORMATION
typedef struct _PNP_LOCATION_INTERFACE PNP_LOCATION_INTERFACE
typedef struct _PLUGPLAY_NOTIFICATION_HEADER * PPLUGPLAY_NOTIFICATION_HEADER
typedef struct _PNP_BUS_INFORMATION * PPNP_BUS_INFORMATION
typedef struct _PNP_LOCATION_INTERFACE * PPNP_LOCATION_INTERFACE
typedef ULONG(* PREAD_ACPI_CMOS) (IN CMOS_DEVICE_TYPE CmosType, IN ULONG SourceAddress, IN PUCHAR DataBuffer, IN ULONG ByteCount)
typedef USHORT(* PREAD_ACPI_REGISTER) (IN ACPI_REG_TYPE AcpiReg, IN ULONG Register)
typedef NTSTATUS(* PREGISTER_FOR_DEVICE_NOTIFICATIONS) (PDEVICE_OBJECT, PDEVICE_NOTIFY_CALLBACK, PVOID)
typedef struct ROUTING_TOKEN * PROUTING_TOKEN
typedef NTSTATUS(* PSET_INTERRUPT_ROUTING_TOKEN) (IN PDEVICE_OBJECT Pdo, IN PROUTING_TOKEN RoutingToken)
typedef struct _TARGET_DEVICE_CUSTOM_NOTIFICATION * PTARGET_DEVICE_CUSTOM_NOTIFICATION
typedef struct _TARGET_DEVICE_REMOVAL_NOTIFICATION * PTARGET_DEVICE_REMOVAL_NOTIFICATION
typedef BOOLEAN(* PTRANSLATE_BUS_ADDRESS) (IN PVOID Context, IN PHYSICAL_ADDRESS BusAddress, IN ULONG Length, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
typedef NTSTATUS(* PTRANSLATE_RESOURCE_HANDLER) (IN PVOID Context, IN PCM_PARTIAL_RESOURCE_DESCRIPTOR Source, IN RESOURCE_TRANSLATION_DIRECTION Direction, IN ULONG AlternativesCount, OPTIONAL IN IO_RESOURCE_DESCRIPTOR Alternatives[], OPTIONAL IN PDEVICE_OBJECT PhysicalDeviceObject, OUT PCM_PARTIAL_RESOURCE_DESCRIPTOR Target)
typedef NTSTATUS(* PTRANSLATE_RESOURCE_REQUIREMENTS_HANDLER) (IN PVOID Context, IN PIO_RESOURCE_DESCRIPTOR Source, IN PDEVICE_OBJECT PhysicalDeviceObject, OUT PULONG TargetCount, OUT PIO_RESOURCE_DESCRIPTOR *Target)
typedef struct _TRANSLATOR_INTERFACE * PTRANSLATOR_INTERFACE
typedef void(* PUNREGISTER_FOR_DEVICE_NOTIFICATIONS) (PDEVICE_OBJECT, PDEVICE_NOTIFY_CALLBACK)
typedef VOID(* PUPDATE_INTERRUPT_LINE) (IN PDEVICE_OBJECT Pdo, IN UCHAR LineRegister)
typedef ULONG(* PWRITE_ACPI_CMOS) (IN CMOS_DEVICE_TYPE CmosType, IN ULONG SourceAddress, IN PUCHAR DataBuffer, IN ULONG ByteCount)
typedef VOID(* PWRITE_ACPI_REGISTER) (IN ACPI_REG_TYPE AcpiReg, IN ULONG Register, IN USHORT Value)
typedef enum _RESOURCE_TRANSLATION_DIRECTION RESOURCE_TRANSLATION_DIRECTION
typedef struct _TARGET_DEVICE_CUSTOM_NOTIFICATION TARGET_DEVICE_CUSTOM_NOTIFICATION
typedef struct _TARGET_DEVICE_REMOVAL_NOTIFICATION TARGET_DEVICE_REMOVAL_NOTIFICATION
typedef struct _TRANSLATOR_INTERFACE TRANSLATOR_INTERFACE
Enumerations
enum _ACPI_REG_TYPE {
PM1a_ENABLE, PM1b_ENABLE, PM1a_STATUS, PM1b_STATUS,
PM1a_CONTROL, PM1b_CONTROL, GP_STATUS, GP_ENABLE,
SMI_CMD, MaxRegType
}
enum _ARBITER_ACTION {
ArbiterActionTestAllocation, ArbiterActionRetestAllocation, ArbiterActionCommitAllocation, ArbiterActionRollbackAllocation,
ArbiterActionQueryAllocatedResources, ArbiterActionWriteReservedResources, ArbiterActionQueryConflict, ArbiterActionQueryArbitrate,
ArbiterActionAddReserved, ArbiterActionBootAllocation
}
enum _ARBITER_REQUEST_SOURCE {
ArbiterRequestUndefined = -1, ArbiterRequestLegacyReported, ArbiterRequestHalReported, ArbiterRequestLegacyAssigned,
ArbiterRequestPnpDetected, ArbiterRequestPnpEnumerated
}
enum _ARBITER_RESULT { ArbiterResultUndefined = -1, ArbiterResultSuccess, ArbiterResultExternalConflict, ArbiterResultNullRequest }
enum _CMOS_DEVICE_TYPE { CmosTypeStdPCAT, CmosTypeIntelPIIX4, CmosTypeDal1501 }
enum _DEVICE_INSTALL_STATE { InstallStateInstalled, InstallStateNeedsReinstall, InstallStateFailedInstall, InstallStateFinishInstall }
enum _DEVICE_REMOVAL_POLICY {
RemovalPolicyNotDetermined = 0, RemovalPolicyExpectNoRemoval = 1, RemovalPolicyExpectOrderlyRemoval = 2, RemovalPolicyExpectSurpriseRemoval = 3,
RemovalPolicySuggestOrderlyRemoval = 4, RemovalPolicySuggestSurpriseRemoval = 5, RemovalPolicyUnspecified = 6
}
enum _IO_NOTIFICATION_EVENT_CATEGORY { EventCategoryReserved, EventCategoryHardwareProfileChange, EventCategoryDeviceInterfaceChange, EventCategoryTargetDeviceChange }
enum _RESOURCE_TRANSLATION_DIRECTION { TranslateChildToParent, TranslateParentToChild }
enum DEVICE_REGISTRY_PROPERTY {
DevicePropertyDeviceDescription, DevicePropertyHardwareID, DevicePropertyCompatibleIDs, DevicePropertyBootConfiguration,
DevicePropertyBootConfigurationTranslated, DevicePropertyClassName, DevicePropertyClassGuid, DevicePropertyDriverKeyName,
DevicePropertyManufacturer, DevicePropertyFriendlyName, DevicePropertyLocationInformation, DevicePropertyPhysicalDeviceObjectName,
DevicePropertyBusTypeGuid, DevicePropertyLegacyBusType, DevicePropertyBusNumber, DevicePropertyEnumeratorName,
DevicePropertyAddress, DevicePropertyUINumber, DevicePropertyInstallState, DevicePropertyRemovalPolicy
}
Functions
NTKERNELAPI NTSTATUS NTAPI IoGetDeviceInterfaceAlias (IN PUNICODE_STRING SymbolicLinkName, IN CONST GUID *AliasInterfaceClassGuid, OUT PUNICODE_STRING AliasSymbolicLinkName)
NTKERNELAPI NTSTATUS NTAPI IoGetDeviceInterfaces (IN CONST GUID *InterfaceClassGuid, IN PDEVICE_OBJECT PhysicalDeviceObject OPTIONAL, IN ULONG Flags, OUT PWSTR *SymbolicLinkList)
NTKERNELAPI NTSTATUS IoGetDeviceProperty (IN PDEVICE_OBJECT DeviceObject, IN DEVICE_REGISTRY_PROPERTY DeviceProperty, IN ULONG BufferLength, OUT PVOID PropertyBuffer, OUT PULONG ResultLength)
NTKERNELAPI VOID IoInvalidateDeviceRelations (IN PDEVICE_OBJECT DeviceObject, IN DEVICE_RELATION_TYPE Type)
NTKERNELAPI VOID IoInvalidateDeviceState (IN PDEVICE_OBJECT PhysicalDeviceObject)
NTKERNELAPI NTSTATUS IoOpenDeviceInterfaceRegistryKey (IN PUNICODE_STRING SymbolicLinkName, IN ACCESS_MASK DesiredAccess, OUT PHANDLE DeviceInterfaceKey)
NTKERNELAPI NTSTATUS IoOpenDeviceRegistryKey (IN PDEVICE_OBJECT DeviceObject, IN ULONG DevInstKeyType, IN ACCESS_MASK DesiredAccess, OUT PHANDLE DevInstRegKey)
NTKERNELAPI ULONG IoPnPDeliverServicePowerNotification (IN POWER_ACTION PowerOperation, IN ULONG PowerNotificationCode, IN ULONG PowerNotificationData, IN BOOLEAN Synchronous)
NTKERNELAPI NTSTATUS NTAPI IoRegisterDeviceInterface (IN PDEVICE_OBJECT PhysicalDeviceObject, IN CONST GUID *InterfaceClassGuid, IN PUNICODE_STRING ReferenceString, OPTIONAL OUT PUNICODE_STRING SymbolicLinkName)
NTKERNELAPI NTSTATUS IoRegisterPlugPlayNotification (IN IO_NOTIFICATION_EVENT_CATEGORY EventCategory, IN ULONG EventCategoryFlags, IN PVOID EventCategoryData OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDRIVER_NOTIFICATION_CALLBACK_ROUTINE CallbackRoutine, IN PVOID Context, OUT PVOID *NotificationEntry)
NTKERNELAPI NTSTATUS IoReportDetectedDevice (IN PDRIVER_OBJECT DriverObject, IN INTERFACE_TYPE LegacyBusType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PCM_RESOURCE_LIST ResourceList, IN PIO_RESOURCE_REQUIREMENTS_LIST ResourceRequirements OPTIONAL, IN BOOLEAN ResourceAssigned, IN OUT PDEVICE_OBJECT *DeviceObject)
NTKERNELAPI NTSTATUS IoReportResourceForDetection (IN PDRIVER_OBJECT DriverObject, IN PCM_RESOURCE_LIST DriverList OPTIONAL, IN ULONG DriverListSize OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN PCM_RESOURCE_LIST DeviceList OPTIONAL, IN ULONG DeviceListSize OPTIONAL, OUT PBOOLEAN ConflictDetected)
NTKERNELAPI NTSTATUS IoReportTargetDeviceChange (IN PDEVICE_OBJECT PhysicalDeviceObject, IN PVOID NotificationStructure)
NTKERNELAPI NTSTATUS IoReportTargetDeviceChangeAsynchronous (IN PDEVICE_OBJECT PhysicalDeviceObject, IN PVOID NotificationStructure, IN PDEVICE_CHANGE_COMPLETE_CALLBACK Callback, OPTIONAL IN PVOID Context OPTIONAL)
NTKERNELAPI VOID IoRequestDeviceEject (IN PDEVICE_OBJECT PhysicalDeviceObject)
NTKERNELAPI NTSTATUS IoSetDeviceInterfaceState (IN PUNICODE_STRING SymbolicLinkName, IN BOOLEAN Enable)
NTKERNELAPI NTSTATUS IoSynchronousInvalidateDeviceRelations (PDEVICE_OBJECT DeviceObject, DEVICE_RELATION_TYPE Type)
NTKERNELAPI NTSTATUS IoUnregisterPlugPlayNotification (IN PVOID NotificationEntry)
NTKERNELAPI NTSTATUS PpDeviceRegistration (IN PUNICODE_STRING DeviceInstancePath, IN BOOLEAN Add, IN PUNICODE_STRING ServiceKeyName OPTIONAL)
NTSTATUS PpInitializeNotification (VOID)
NTKERNELAPI BOOLEAN PpInitSystem (VOID)
NTSTATUS PpNotifyUserModeRemovalSafe (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS PpPagePathAssign (IN PFILE_OBJECT FileObject)
NTSTATUS PpPagePathRelease (IN PFILE_OBJECT FileObject)
NTSTATUS PpSetBlockedDriverEvent (IN GUID CONST *BlockedDriverGuid)
NTSTATUS PpSetCustomTargetEvent (IN PDEVICE_OBJECT DeviceObject, IN PKEVENT SyncEvent OPTIONAL, OUT PULONG Result OPTIONAL, IN PDEVICE_CHANGE_COMPLETE_CALLBACK Callback OPTIONAL, IN PVOID Context OPTIONAL, IN PTARGET_DEVICE_CUSTOM_NOTIFICATION NotificationStructure)
NTSTATUS PpSetDeviceClassChange (IN CONST GUID *EventGuid, IN CONST GUID *ClassGuid, IN PUNICODE_STRING SymbolicLinkName)
NTSTATUS PpSetDeviceRemovalSafe (IN PDEVICE_OBJECT DeviceObject, IN PKEVENT SyncEvent OPTIONAL, OUT PULONG Result OPTIONAL)
NTSTATUS PpSetHwProfileChangeEvent (IN CONST GUID *EventGuid, IN PKEVENT CompletionEvent OPTIONAL, OUT PNTSTATUS CompletionStatus OPTIONAL, OUT PPNP_VETO_TYPE VetoType OPTIONAL, OUT PUNICODE_STRING VetoName OPTIONAL)
NTSTATUS PpSetInvalidIDEvent (IN PUNICODE_STRING ParentInstance)
VOID PpSetPlugPlayEvent (IN CONST GUID *EventGuid, IN PDEVICE_OBJECT DeviceObject)
NTSTATUS PpSetPowerEvent (IN ULONG EventCode, IN ULONG EventData, IN PKEVENT CompletionEvent OPTIONAL, OUT PNTSTATUS CompletionStatus OPTIONAL, OUT PPNP_VETO_TYPE VetoType OPTIONAL, OUT PUNICODE_STRING VetoName OPTIONAL)
NTSTATUS PpSetPowerVetoEvent (IN POWER_ACTION VetoedPowerOperation, IN PKEVENT CompletionEvent OPTIONAL, OUT PNTSTATUS CompletionStatus OPTIONAL, IN PDEVICE_OBJECT DeviceObject, IN PNP_VETO_TYPE VetoType, IN PUNICODE_STRING VetoName OPTIONAL)
NTSTATUS PpSetTargetDeviceRemove (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN KernelInitiated, IN BOOLEAN NoRestart, IN BOOLEAN OnlyRestartRelations, IN BOOLEAN DoEject, IN ULONG Problem, IN PKEVENT SyncEvent OPTIONAL, OUT PULONG Result OPTIONAL, OUT PPNP_VETO_TYPE VetoType OPTIONAL, OUT PUNICODE_STRING VetoName OPTIONAL)
VOID PpShutdownSystem (IN BOOLEAN Reboot, IN ULONG Phase, IN OUT PVOID *Context)
NTSTATUS PpSynchronizeDeviceEventQueue (VOID)
Variables
PDRIVER_OBJECT IoPnpDriverObject
ERESOURCE PpRegistryDeviceResource
Macro Definition Documentation
#define ARBITER_FLAG_BOOT_CONFIG 0x00000001
Definition at line 848 of file pnp.h.
#define ARBITER_PARTIAL 0x00000001
Definition at line 949 of file pnp.h.
#define DEVICE_INTERFACE_INCLUDE_NONACTIVE 0x00000001
Definition at line 553 of file pnp.h.
#define IoAdjustPagingPathCount (_count_, _paging_)
Value:
{     \
    if (_paging_) {                                     \
        InterlockedIncrement(_count_);                  \
    } else {                                            \
        InterlockedDecrement(_count_);                  \
    }                                                   \
}
Definition at line 627 of file pnp.h.
#define PCI_INT_ROUTE_INTRF_STANDARD_VER 1
Definition at line 435 of file pnp.h.
#define PCI_MSI_ROUTING 0x1
Definition at line 383 of file pnp.h.
#define PCI_STATIC_ROUTING 0x2
Definition at line 384 of file pnp.h.
#define PLUGPLAY_REGKEY_CURRENT_HWPROFILE 4
Definition at line 507 of file pnp.h.
#define PLUGPLAY_REGKEY_DEVICE 1
Definition at line 505 of file pnp.h.
#define PLUGPLAY_REGKEY_DRIVER 2
Definition at line 506 of file pnp.h.
#define PNPNOTIFY_DEVICE_INTERFACE_INCLUDE_EXISTING_INTERFACES 0x00000001
Definition at line 580 of file pnp.h.
#define TDF_DEVICEEJECTABLE 0x00000001
Definition at line 1191 of file pnp.h.
#define TDF_KERNEL_INITIATED 0x00000004
Definition at line 1193 of file pnp.h.
#define TDF_NO_RESTART 0x00000002
Definition at line 1192 of file pnp.h.
#define TDF_ONLY_RESTART_RELATIONS 0x00000008
Definition at line 1198 of file pnp.h.
Typedef Documentation
typedef struct _ACPI_CMOS_INTERFACE_STANDARD ACPI_CMOS_INTERFACE_STANDARD
typedef struct _ACPI_INTERFACE_STANDARD ACPI_INTERFACE_STANDARD
typedef enum _ACPI_REG_TYPE ACPI_REG_TYPE
typedef struct ACPI_REGS_INTERFACE_STANDARD ACPI_REGS_INTERFACE_STANDARD
typedef struct _AGP_TARGET_BUS_INTERFACE_STANDARD AGP_TARGET_BUS_INTERFACE_STANDARD
typedef enum _ARBITER_ACTION ARBITER_ACTION
typedef struct _ARBITER_CONFLICT_INFO ARBITER_CONFLICT_INFO
typedef struct _ARBITER_INTERFACE ARBITER_INTERFACE
typedef struct _ARBITER_LIST_ENTRY ARBITER_LIST_ENTRY
typedef struct _ARBITER_PARAMETERS ARBITER_PARAMETERS
typedef enum _ARBITER_REQUEST_SOURCE ARBITER_REQUEST_SOURCE
typedef enum _ARBITER_RESULT ARBITER_RESULT
typedef struct _BUS_INTERFACE_STANDARD BUS_INTERFACE_STANDARD
typedef enum _CMOS_DEVICE_TYPE CMOS_DEVICE_TYPE
typedef enum _DEVICE_INSTALL_STATE DEVICE_INSTALL_STATE
typedef struct _DEVICE_INTERFACE_CHANGE_NOTIFICATION DEVICE_INTERFACE_CHANGE_NOTIFICATION
typedef enum _DEVICE_REMOVAL_POLICY DEVICE_REMOVAL_POLICY
typedef struct _HAL_PORT_RANGE_INTERFACE HAL_PORT_RANGE_INTERFACE
typedef struct _HWPROFILE_CHANGE_NOTIFICATION HWPROFILE_CHANGE_NOTIFICATION
typedef struct _INT_ROUTE_INTERFACE_STANDARD INT_ROUTE_INTERFACE_STANDARD
typedef enum _IO_NOTIFICATION_EVENT_CATEGORY IO_NOTIFICATION_EVENT_CATEGORY
typedef struct _LEGACY_BUS_INFORMATION LEGACY_BUS_INFORMATION
typedef struct _LEGACY_DEVICE_DETECTION_INTERFACE LEGACY_DEVICE_DETECTION_INTERFACE
typedef struct _ACPI_CMOS_INTERFACE_STANDARD * PACPI_CMOS_INTERFACE_STANDARD
typedef struct _ACPI_INTERFACE_STANDARD * PACPI_INTERFACE_STANDARD
typedef enum _ACPI_REG_TYPE * PACPI_REG_TYPE
typedef struct ACPI_REGS_INTERFACE_STANDARD * PACPI_REGS_INTERFACE_STANDARD
typedef struct _AGP_TARGET_BUS_INTERFACE_STANDARD * PAGP_TARGET_BUS_INTERFACE_STANDARD
typedef enum _ARBITER_ACTION * PARBITER_ACTION
typedef struct _ARBITER_CONFLICT_INFO * PARBITER_CONFLICT_INFO
typedef NTSTATUS(* PARBITER_HANDLER) (IN PVOID Context, IN ARBITER_ACTION Action, IN OUT PARBITER_PARAMETERS Parameters)
Definition at line 939 of file pnp.h.
typedef struct _ARBITER_INTERFACE * PARBITER_INTERFACE
typedef struct _ARBITER_LIST_ENTRY * PARBITER_LIST_ENTRY
typedef struct _ARBITER_PARAMETERS * PARBITER_PARAMETERS
typedef struct _BUS_INTERFACE_STANDARD * PBUS_INTERFACE_STANDARD
typedef VOID(* PDEVICE_CHANGE_COMPLETE_CALLBACK) (IN PVOID Context)
Definition at line 617 of file pnp.h.
typedef enum _DEVICE_INSTALL_STATE * PDEVICE_INSTALL_STATE
typedef struct _DEVICE_INTERFACE_CHANGE_NOTIFICATION * PDEVICE_INTERFACE_CHANGE_NOTIFICATION
typedef VOID(* PDEVICE_NOTIFY_CALLBACK) (PVOID, ULONG)
Definition at line 208 of file pnp.h.
typedef enum _DEVICE_REMOVAL_POLICY * PDEVICE_REMOVAL_POLICY
typedef NTSTATUS(* PDRIVER_NOTIFICATION_CALLBACK_ROUTINE) (IN PVOID NotificationStructure, IN PVOID Context)
Definition at line 584 of file pnp.h.
typedef struct _DMA_ADAPTER*(* PGET_DMA_ADAPTER) (IN PVOID Context, IN struct _DEVICE_DESCRIPTION *DeviceDescriptor, OUT PULONG NumberOfMapRegisters)
Definition at line 69 of file pnp.h.
typedef NTSTATUS(* PGET_INTERRUPT_ROUTING) (IN PDEVICE_OBJECT Pdo, OUT ULONG *Bus, OUT ULONG *PciSlot, OUT UCHAR *InterruptLine, OUT UCHAR *InterruptPin, OUT UCHAR *ClassCode, OUT UCHAR *SubClassCode, OUT PDEVICE_OBJECT *ParentPdo, OUT ROUTING_TOKEN *RoutingToken, OUT UCHAR *Flags)
Definition at line 388 of file pnp.h.
typedef NTSTATUS(* PGET_LOCATION_STRING) (IN PVOID Context, OUT PWCHAR *LocationStrings)
Definition at line 649 of file pnp.h.
typedef ULONG(* PGET_SET_DEVICE_DATA) (IN PVOID Context, IN ULONG DataType, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
Definition at line 75 of file pnp.h.
typedef NTSTATUS(* PGPE_CLEAR_STATUS) (PDEVICE_OBJECT, PVOID)
Definition at line 204 of file pnp.h.
typedef NTSTATUS(* PGPE_CONNECT_VECTOR) (PDEVICE_OBJECT, ULONG, KINTERRUPT_MODE, BOOLEAN, PGPE_SERVICE_ROUTINE, PVOID, PVOID)
Definition at line 184 of file pnp.h.
typedef NTSTATUS(* PGPE_DISABLE_EVENT) (PDEVICE_OBJECT, PVOID)
Definition at line 200 of file pnp.h.
typedef NTSTATUS(* PGPE_DISCONNECT_VECTOR) (PVOID)
Definition at line 193 of file pnp.h.
typedef NTSTATUS(* PGPE_ENABLE_EVENT) (PDEVICE_OBJECT, PVOID)
Definition at line 196 of file pnp.h.
typedef BOOLEAN(* PGPE_SERVICE_ROUTINE) (PVOID, PVOID)
Definition at line 180 of file pnp.h.
typedef VOID(* PHAL_FREE_PORT_RANGE) (IN USHORT RangeId)
Definition at line 296 of file pnp.h.
typedef struct _HAL_PORT_RANGE_INTERFACE * PHAL_PORT_RANGE_INTERFACE
typedef NTSTATUS(* PHAL_QUERY_ALLOCATE_PORT_RANGE) (IN BOOLEAN IsSparse, IN BOOLEAN PrimaryIsMmio, IN PVOID VirtBaseAddr OPTIONAL, IN PHYSICAL_ADDRESS PhysBaseAddr, IN ULONG Length, OUT PUSHORT NewRangeId)
Definition at line 287 of file pnp.h.
typedef struct _HWPROFILE_CHANGE_NOTIFICATION * PHWPROFILE_CHANGE_NOTIFICATION
typedef struct _INT_ROUTE_INTERFACE_STANDARD * PINT_ROUTE_INTERFACE_STANDARD
typedef struct _LEGACY_BUS_INFORMATION * PLEGACY_BUS_INFORMATION
typedef NTSTATUS(* PLEGACY_DEVICE_DETECTION_HANDLER) (IN PVOID Context, IN INTERFACE_TYPE LegacyBusType, IN ULONG BusNumber, IN ULONG SlotNumber, OUT PDEVICE_OBJECT *PhysicalDeviceObject)
Definition at line 1033 of file pnp.h.
typedef struct _LEGACY_DEVICE_DETECTION_INTERFACE * PLEGACY_DEVICE_DETECTION_INTERFACE
typedef struct _PLUGPLAY_NOTIFICATION_HEADER PLUGPLAY_NOTIFICATION_HEADER
typedef struct _PNP_BUS_INFORMATION PNP_BUS_INFORMATION
typedef struct _PNP_LOCATION_INTERFACE PNP_LOCATION_INTERFACE
typedef struct _PLUGPLAY_NOTIFICATION_HEADER * PPLUGPLAY_NOTIFICATION_HEADER
typedef struct _PNP_BUS_INFORMATION * PPNP_BUS_INFORMATION
typedef struct _PNP_LOCATION_INTERFACE * PPNP_LOCATION_INTERFACE
typedef ULONG(* PREAD_ACPI_CMOS) (IN CMOS_DEVICE_TYPE CmosType, IN ULONG SourceAddress, IN PUCHAR DataBuffer, IN ULONG ByteCount)
Definition at line 333 of file pnp.h.
typedef USHORT(* PREAD_ACPI_REGISTER) (IN ACPI_REG_TYPE AcpiReg, IN ULONG Register)
Definition at line 258 of file pnp.h.
typedef NTSTATUS(* PREGISTER_FOR_DEVICE_NOTIFICATIONS) (PDEVICE_OBJECT, PDEVICE_NOTIFY_CALLBACK, PVOID)
Definition at line 212 of file pnp.h.
typedef struct ROUTING_TOKEN * PROUTING_TOKEN
typedef NTSTATUS(* PSET_INTERRUPT_ROUTING_TOKEN) (IN PDEVICE_OBJECT Pdo, IN PROUTING_TOKEN RoutingToken)
Definition at line 403 of file pnp.h.
typedef struct _TARGET_DEVICE_CUSTOM_NOTIFICATION * PTARGET_DEVICE_CUSTOM_NOTIFICATION
typedef struct _TARGET_DEVICE_REMOVAL_NOTIFICATION * PTARGET_DEVICE_REMOVAL_NOTIFICATION
typedef BOOLEAN(* PTRANSLATE_BUS_ADDRESS) (IN PVOID Context, IN PHYSICAL_ADDRESS BusAddress, IN ULONG Length, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
Definition at line 61 of file pnp.h.
typedef NTSTATUS(* PTRANSLATE_RESOURCE_HANDLER) (IN PVOID Context, IN PCM_PARTIAL_RESOURCE_DESCRIPTOR Source, IN RESOURCE_TRANSLATION_DIRECTION Direction, IN ULONG AlternativesCount, OPTIONAL IN IO_RESOURCE_DESCRIPTOR Alternatives[], OPTIONAL IN PDEVICE_OBJECT PhysicalDeviceObject, OUT PCM_PARTIAL_RESOURCE_DESCRIPTOR Target)
Definition at line 991 of file pnp.h.
typedef NTSTATUS(* PTRANSLATE_RESOURCE_REQUIREMENTS_HANDLER) (IN PVOID Context, IN PIO_RESOURCE_DESCRIPTOR Source, IN PDEVICE_OBJECT PhysicalDeviceObject, OUT PULONG TargetCount, OUT PIO_RESOURCE_DESCRIPTOR *Target)
Definition at line 1003 of file pnp.h.
typedef struct _TRANSLATOR_INTERFACE * PTRANSLATOR_INTERFACE
typedef void(* PUNREGISTER_FOR_DEVICE_NOTIFICATIONS) (PDEVICE_OBJECT, PDEVICE_NOTIFY_CALLBACK)
Definition at line 217 of file pnp.h.
typedef VOID(* PUPDATE_INTERRUPT_LINE) (IN PDEVICE_OBJECT Pdo, IN UCHAR LineRegister)
Definition at line 410 of file pnp.h.
typedef ULONG(* PWRITE_ACPI_CMOS) (IN CMOS_DEVICE_TYPE CmosType, IN ULONG SourceAddress, IN PUCHAR DataBuffer, IN ULONG ByteCount)
Definition at line 342 of file pnp.h.
typedef VOID(* PWRITE_ACPI_REGISTER) (IN ACPI_REG_TYPE AcpiReg, IN ULONG Register, IN USHORT Value)
Definition at line 262 of file pnp.h.
typedef enum _RESOURCE_TRANSLATION_DIRECTION RESOURCE_TRANSLATION_DIRECTION
typedef struct _TARGET_DEVICE_CUSTOM_NOTIFICATION TARGET_DEVICE_CUSTOM_NOTIFICATION
typedef struct _TARGET_DEVICE_REMOVAL_NOTIFICATION TARGET_DEVICE_REMOVAL_NOTIFICATION
typedef struct _TRANSLATOR_INTERFACE TRANSLATOR_INTERFACE
Enumeration Type Documentation
enum _ACPI_REG_TYPE
Enumerator
PM1a_ENABLE
PM1b_ENABLE
PM1a_STATUS
PM1b_STATUS
PM1a_CONTROL
PM1b_CONTROL
GP_STATUS
GP_ENABLE
SMI_CMD
MaxRegType
Definition at line 245 of file pnp.h.
enum _ARBITER_ACTION
Enumerator
ArbiterActionTestAllocation
ArbiterActionRetestAllocation
ArbiterActionCommitAllocation
ArbiterActionRollbackAllocation
ArbiterActionQueryAllocatedResources
ArbiterActionWriteReservedResources
ArbiterActionQueryConflict
ArbiterActionQueryArbitrate
ArbiterActionAddReserved
ArbiterActionBootAllocation
Definition at line 675 of file pnp.h.
enum _ARBITER_REQUEST_SOURCE
Enumerator
ArbiterRequestUndefined
ArbiterRequestLegacyReported
ArbiterRequestHalReported
ArbiterRequestLegacyAssigned
ArbiterRequestPnpDetected
ArbiterRequestPnpEnumerated
Definition at line 821 of file pnp.h.
enum _ARBITER_RESULT
Enumerator
ArbiterResultUndefined
ArbiterResultSuccess
ArbiterResultExternalConflict
ArbiterResultNullRequest
Definition at line 833 of file pnp.h.
enum _CMOS_DEVICE_TYPE
Enumerator
CmosTypeStdPCAT
CmosTypeIntelPIIX4
CmosTypeDal1501
Definition at line 324 of file pnp.h.
enum _DEVICE_INSTALL_STATE
Enumerator
InstallStateInstalled
InstallStateNeedsReinstall
InstallStateFailedInstall
InstallStateFinishInstall
Definition at line 83 of file pnp.h.
enum _DEVICE_REMOVAL_POLICY
Enumerator
RemovalPolicyNotDetermined
RemovalPolicyExpectNoRemoval
RemovalPolicyExpectOrderlyRemoval
RemovalPolicyExpectSurpriseRemoval
RemovalPolicySuggestOrderlyRemoval
RemovalPolicySuggestSurpriseRemoval
RemovalPolicyUnspecified
Definition at line 118 of file pnp.h.
enum _IO_NOTIFICATION_EVENT_CATEGORY
Enumerator
EventCategoryReserved
EventCategoryHardwareProfileChange
EventCategoryDeviceInterfaceChange
EventCategoryTargetDeviceChange
Definition at line 568 of file pnp.h.
enum _RESOURCE_TRANSLATION_DIRECTION
Enumerator
TranslateChildToParent
TranslateParentToChild
Definition at line 979 of file pnp.h.
enum DEVICE_REGISTRY_PROPERTY
Enumerator
DevicePropertyDeviceDescription
DevicePropertyHardwareID
DevicePropertyCompatibleIDs
DevicePropertyBootConfiguration
DevicePropertyBootConfigurationTranslated
DevicePropertyClassName
DevicePropertyClassGuid
DevicePropertyDriverKeyName
DevicePropertyManufacturer
DevicePropertyFriendlyName
DevicePropertyLocationInformation
DevicePropertyPhysicalDeviceObjectName
DevicePropertyBusTypeGuid
DevicePropertyLegacyBusType
DevicePropertyBusNumber
DevicePropertyEnumeratorName
DevicePropertyAddress
DevicePropertyUINumber
DevicePropertyInstallState
DevicePropertyRemovalPolicy
Definition at line 38 of file pnp.h.
Function Documentation
NTKERNELAPI NTSTATUS NTAPI IoGetDeviceInterfaceAlias (IN PUNICODE_STRING SymbolicLinkName, IN CONST GUID * AliasInterfaceClassGuid, OUT PUNICODE_STRING AliasSymbolicLinkName)
NTKERNELAPI NTSTATUS NTAPI IoGetDeviceInterfaces (IN CONST GUID * InterfaceClassGuid, IN PDEVICE_OBJECT PhysicalDeviceObject OPTIONAL, IN ULONG Flags, OUT PWSTR * SymbolicLinkList)
Referenced by IopFetchConfigurationInformation().
NTKERNELAPI NTSTATUS IoGetDeviceProperty (IN PDEVICE_OBJECT DeviceObject, IN DEVICE_REGISTRY_PROPERTY DeviceProperty, IN ULONG BufferLength, OUT PVOID PropertyBuffer, OUT PULONG ResultLength)
Referenced by IoWMISuggestInstanceName().
NTKERNELAPI VOID IoInvalidateDeviceRelations (IN PDEVICE_OBJECT DeviceObject, IN DEVICE_RELATION_TYPE Type)
NTKERNELAPI VOID IoInvalidateDeviceState (IN PDEVICE_OBJECT PhysicalDeviceObject)
NTKERNELAPI NTSTATUS IoOpenDeviceInterfaceRegistryKey (IN PUNICODE_STRING SymbolicLinkName, IN ACCESS_MASK DesiredAccess, OUT PHANDLE DeviceInterfaceKey)
Referenced by IoWMISuggestInstanceName().
NTKERNELAPI NTSTATUS IoOpenDeviceRegistryKey (IN PDEVICE_OBJECT DeviceObject, IN ULONG DevInstKeyType, IN ACCESS_MASK DesiredAccess, OUT PHANDLE DevInstRegKey)
NTKERNELAPI ULONG IoPnPDeliverServicePowerNotification (IN POWER_ACTION PowerOperation, IN ULONG PowerNotificationCode, IN ULONG PowerNotificationData, IN BOOLEAN Synchronous)
NTKERNELAPI NTSTATUS NTAPI IoRegisterDeviceInterface (IN PDEVICE_OBJECT PhysicalDeviceObject, IN CONST GUID * InterfaceClassGuid, IN PUNICODE_STRING ReferenceString, OPTIONAL OUT PUNICODE_STRING SymbolicLinkName)
NTKERNELAPI NTSTATUS IoRegisterPlugPlayNotification (IN IO_NOTIFICATION_EVENT_CATEGORY EventCategory, IN ULONG EventCategoryFlags, IN PVOID EventCategoryData OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDRIVER_NOTIFICATION_CALLBACK_ROUTINE CallbackRoutine, IN PVOID Context, OUT PVOID * NotificationEntry)
Referenced by WmipDriverEntry().
NTKERNELAPI NTSTATUS IoReportDetectedDevice (IN PDRIVER_OBJECT DriverObject, IN INTERFACE_TYPE LegacyBusType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PCM_RESOURCE_LIST ResourceList, IN PIO_RESOURCE_REQUIREMENTS_LIST ResourceRequirements OPTIONAL, IN BOOLEAN ResourceAssigned, IN OUT PDEVICE_OBJECT * DeviceObject)
NTKERNELAPI NTSTATUS IoReportResourceForDetection (IN PDRIVER_OBJECT DriverObject, IN PCM_RESOURCE_LIST DriverList OPTIONAL, IN ULONG DriverListSize OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN PCM_RESOURCE_LIST DeviceList OPTIONAL, IN ULONG DeviceListSize OPTIONAL, OUT PBOOLEAN ConflictDetected)
NTKERNELAPI NTSTATUS IoReportTargetDeviceChange (IN PDEVICE_OBJECT PhysicalDeviceObject, IN PVOID NotificationStructure)
Referenced by FsRtlNotifyVolumeEvent(), and NtSetVolumeInformationFile().
NTKERNELAPI NTSTATUS IoReportTargetDeviceChangeAsynchronous (IN PDEVICE_OBJECT PhysicalDeviceObject, IN PVOID NotificationStructure, IN PDEVICE_CHANGE_COMPLETE_CALLBACK Callback, OPTIONAL IN PVOID Context OPTIONAL)
Referenced by FsRtlNotifyVolumeEvent().
NTKERNELAPI VOID IoRequestDeviceEject (IN PDEVICE_OBJECT PhysicalDeviceObject)
NTKERNELAPI NTSTATUS IoSetDeviceInterfaceState (IN PUNICODE_STRING SymbolicLinkName, IN BOOLEAN Enable)
NTKERNELAPI NTSTATUS IoSynchronousInvalidateDeviceRelations (PDEVICE_OBJECT DeviceObject, DEVICE_RELATION_TYPE Type)
NTKERNELAPI NTSTATUS IoUnregisterPlugPlayNotification (IN PVOID NotificationEntry)
NTKERNELAPI NTSTATUS PpDeviceRegistration (IN PUNICODE_STRING DeviceInstancePath, IN BOOLEAN Add, IN PUNICODE_STRING ServiceKeyName OPTIONAL)
NTSTATUS PpInitializeNotification (VOID)
NTKERNELAPI BOOLEAN PpInitSystem (VOID)
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTSTATUS PpNotifyUserModeRemovalSafe (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS PpPagePathAssign (IN PFILE_OBJECT FileObject)
Referenced by MmLoadSystemImage(), and NtCreatePagingFile().
NTSTATUS PpPagePathRelease (IN PFILE_OBJECT FileObject)
NTSTATUS PpSetBlockedDriverEvent (IN GUID CONST * BlockedDriverGuid)
NTSTATUS PpSetCustomTargetEvent (IN PDEVICE_OBJECT DeviceObject, IN PKEVENT SyncEvent OPTIONAL, OUT PULONG Result OPTIONAL, IN PDEVICE_CHANGE_COMPLETE_CALLBACK Callback OPTIONAL, IN PVOID Context OPTIONAL, IN PTARGET_DEVICE_CUSTOM_NOTIFICATION NotificationStructure)
NTSTATUS PpSetDeviceClassChange (IN CONST GUID * EventGuid, IN CONST GUID * ClassGuid, IN PUNICODE_STRING SymbolicLinkName)
NTSTATUS PpSetDeviceRemovalSafe (IN PDEVICE_OBJECT DeviceObject, IN PKEVENT SyncEvent OPTIONAL, OUT PULONG Result OPTIONAL)
NTSTATUS PpSetHwProfileChangeEvent (IN CONST GUID * EventGuid, IN PKEVENT CompletionEvent OPTIONAL, OUT PNTSTATUS CompletionStatus OPTIONAL, OUT PPNP_VETO_TYPE VetoType OPTIONAL, OUT PUNICODE_STRING VetoName OPTIONAL)
NTSTATUS PpSetInvalidIDEvent (IN PUNICODE_STRING ParentInstance)
VOID PpSetPlugPlayEvent (IN CONST GUID * EventGuid, IN PDEVICE_OBJECT DeviceObject)
NTSTATUS PpSetPowerEvent (IN ULONG EventCode, IN ULONG EventData, IN PKEVENT CompletionEvent OPTIONAL, OUT PNTSTATUS CompletionStatus OPTIONAL, OUT PPNP_VETO_TYPE VetoType OPTIONAL, OUT PUNICODE_STRING VetoName OPTIONAL)
NTSTATUS PpSetPowerVetoEvent (IN POWER_ACTION VetoedPowerOperation, IN PKEVENT CompletionEvent OPTIONAL, OUT PNTSTATUS CompletionStatus OPTIONAL, IN PDEVICE_OBJECT DeviceObject, IN PNP_VETO_TYPE VetoType, IN PUNICODE_STRING VetoName OPTIONAL)
NTSTATUS PpSetTargetDeviceRemove (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN KernelInitiated, IN BOOLEAN NoRestart, IN BOOLEAN OnlyRestartRelations, IN BOOLEAN DoEject, IN ULONG Problem, IN PKEVENT SyncEvent OPTIONAL, OUT PULONG Result OPTIONAL, OUT PPNP_VETO_TYPE VetoType OPTIONAL, OUT PUNICODE_STRING VetoName OPTIONAL)
VOID PpShutdownSystem (IN BOOLEAN Reboot, IN ULONG Phase, IN OUT PVOID * Context)
NTSTATUS PpSynchronizeDeviceEventQueue (VOID)
Variable Documentation
PDRIVER_OBJECT IoPnpDriverObject
Referenced by WmipRegisterFirmwareProviders().
ERESOURCE PpRegistryDeviceResource