Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/pool.c File Reference
pool.c File Reference
#include "exp.h"
Data Structures
struct _EX_FREE_POOL_TRACES
struct _POOL_DPC_CONTEXT
Macros
#define ASSERT_ALLOCATE_IRQL(_PoolType, _NumberOfBytes)
#define ASSERT_FREE_IRQL(_PoolType, _P)
#define ASSERT_POOL_NOT_FREE(_Entry)
#define ASSERT_POOL_TYPE_NOT_ZERO(_Entry)
#define CacheOverhead POOL_OVERHEAD
#define CHECK_LIST(LIST)
#define CHECK_POOL_HEADER(ENTRY) ExCheckPoolHeader(ENTRY)
#define CHECK_POOL_PAGE(PAGE)
#define DECODE_POOL_INDEX(POOLHEADER) ((ULONG)((POOLHEADER)->PoolIndex))
#define DecodeLink(Link) ((PLIST_ENTRY)((ULONG_PTR)(Link) & ~1))
#define DEFAULT_BIGPAGE_TABLE 4096
#define DEFAULT_TRACKER_TABLE 2048
#define ENCODE_POOL_INDEX(POOLHEADER, INDEX) {(POOLHEADER)->PoolIndex = ((UCHAR)(INDEX));}
#define EncodeLink(Link) ((PLIST_ENTRY)((ULONG_PTR)(Link) | 1))
#define EX_FREE_POOL_BACKTRACE_LENGTH 8
#define EXP_MAXIMUM_POOL_FREES_PENDING 32
#define EXP_MAXIMUM_POOL_NODES 16
#define FREE_CHECK_ERESOURCE(Va, NumberOfBytes)
#define FREE_CHECK_KTIMER(Va, NumberOfBytes)
#define FREE_CHECK_WORKER(Va, NumberOfBytes)
#define IS_POOL_HEADER_MARKED_ALLOCATED(POOLHEADER) ((POOLHEADER)->PoolType & POOL_IN_USE_MASK)
#define LOCK_POOL(PoolDesc, LockHandle)
#define MARK_POOL_HEADER_FREED(POOLHEADER) {(POOLHEADER)->PoolType &= ~POOL_IN_USE_MASK;}
#define MAXIMUM_PROCESSOR_TAG_TABLES 32
#define POOL_BIG_TABLE_ENTRY_FREE 0x1
#define POOL_HOTPAGE_MASK POOL_RAISE_IF_ALLOCATION_FAILURE
#define POOL_IN_USE_MASK 0x4
#define POOL_SPECIAL_POOL_BIT 0x8
#define POOL_SPECIAL_POOL_UNDERRUN_BIT 0x1
#define PrivateInitializeListHead(ListHead)
#define PrivateInsertHeadList(ListHead, Entry)
#define PrivateInsertTailList(ListHead, Entry)
#define PrivateIsListEmpty(ListHead) (DecodeLink((ListHead)->Flink) == (ListHead))
#define PrivateRemoveEntryList(Entry)
#define PrivateRemoveHeadList(ListHead)
#define PrivateRemoveTailList(ListHead)
#define UNLOCK_POOL(PoolDesc, LockHandle)
#define USING_HOT_COLD_METRICS 0
Typedefs
typedef struct _EX_FREE_POOL_TRACES EX_FREE_POOL_TRACES
typedef struct _EX_FREE_POOL_TRACES * PEX_FREE_POOL_TRACES
typedef struct _POOL_DPC_CONTEXT POOL_DPC_CONTEXT
typedef struct _POOL_DPC_CONTEXT * PPOOL_DPC_CONTEXT
Functions
__bcount (NumberOfBytes)
VOID ExAllocatePoolSanityChecks (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes)
VOID FORCEINLINE ExCheckPoolHeader (IN PPOOL_HEADER Entry)
PVOID ExCreatePoolTagTable (IN ULONG NewProcessorNumber, IN UCHAR NodeNumber)
VOID ExDeferredFreePool (IN PPOOL_DESCRIPTOR PoolDesc)
VOID ExDeletePoolTagTable (IN ULONG NewProcessorNumber)
VOID ExDrainPoolLookasideList (IN PPAGED_LOOKASIDE_LIST Lookaside)
VOID ExFreePool (__in PVOID P)
VOID ExFreePoolSanityChecks (IN PVOID P)
VOID ExFreePoolWithTag (__in PVOID P, __in ULONG TagToFree)
NTSTATUS ExGetBigPoolInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
NTSTATUS ExGetPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
NTSTATUS ExGetSessionPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnedEntries, IN OUT PULONG ActualEntries)
VOID ExInitializePoolDescriptor (IN PPOOL_DESCRIPTOR PoolDescriptor, IN POOL_TYPE PoolType, IN ULONG PoolIndex, IN ULONG Threshold, IN PVOID PoolLock)
VOID ExInsertPoolTag (ULONG Tag, PVOID Va, SIZE_T NumberOfBytes, POOL_TYPE PoolType)
BOOLEAN ExOkayToLockRoutine (IN PVOID Lock)
LOGICAL ExpAddTagForBigPages (IN PVOID Va, IN ULONG Key, IN ULONG NumberOfPages, IN POOL_TYPE PoolType)
PVOID ExpAllocateStringRoutine (IN SIZE_T NumberOfBytes)
PVOID ExpDummyAllocate (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag)
LOGICAL ExpExpandBigPageTable (IN KIRQL OldIrql)
ULONG ExpFindAndRemoveTagBigPages (IN PVOID Va, OUT PULONG BigPages, IN POOL_TYPE PoolType)
FORCEINLINE PEPROCESS ExpGetBilledProcess (IN PPOOL_HEADER Entry)
VOID ExpGetPoolTagInfoTarget (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID ExpInsertPoolTracker (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
VOID ExpInsertPoolTrackerExpansion (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
FORCEINLINE VOID ExpInsertPoolTrackerInline (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
VOID ExpRemovePoolTracker (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
VOID ExpRemovePoolTrackerExpansion (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
FORCEINLINE VOID ExpRemovePoolTrackerInline (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
VOID ExpSeedHotTags (VOID)
SIZE_T ExQueryPoolBlockSize (__in PVOID PoolBlock, __out PBOOLEAN QuotaCharged)
VOID ExQueryPoolUsage (__out PULONG PagedPoolPages, __out PULONG NonPagedPoolPages, __out PULONG PagedPoolAllocs, __out PULONG PagedPoolFrees, __out PULONG PagedPoolLookasideHits, __out PULONG NonPagedPoolAllocs, __out PULONG NonPagedPoolFrees, __out PULONG NonPagedPoolLookasideHits)
VOID ExReturnPoolQuota (IN PVOID P)
VOID ExSetPoolFlags (IN ULONG PoolFlag)
VOID InitializePool (IN POOL_TYPE PoolType, IN ULONG Threshold)
FORCEINLINE ULONG POOLTAG_HASH (IN ULONG Key, IN SIZE_T Mask)
PVOID VeAllocatePoolWithTagPriority (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag, IN EX_POOL_PRIORITY Priority, IN PVOID CallingAddress)
Variables
LONG ExFreePoolIndex
LONG ExFreePoolMask = 0x4000 - 1
PEX_FREE_POOL_TRACES ExFreePoolTraces
ULONG ExpBigTableExpansionFailed
EX_SPIN_LOCK ExpLargePoolTableLock
PPOOL_DESCRIPTOR ExpNonPagedPoolDescriptor [EXP_MAXIMUM_POOL_NODES]
ULONG ExpNumberOfNonPagedPools = 1
ULONG ExpNumberOfPagedPools = NUMBER_OF_PAGED_POOLS
ULONG ExPoolFailures
PPOOL_TRACKER_TABLE ExPoolTagTables [MAXIMUM_PROCESSOR_TAG_TABLES]
PPOOL_DESCRIPTOR ExpPagedPoolDescriptor [EXP_MAXIMUM_POOL_NODES+1]
PKGUARDED_MUTEX ExpPagedPoolMutex
LONG ExpPoolBigEntriesInUse
ULONG ExpPoolFlags = 0
volatile ULONG ExpPoolIndex = 1
PPOOL_TRACKER_BIG_PAGES ExpSessionPoolBigPageTable
SIZE_T ExpSessionPoolBigPageTableHash
SIZE_T ExpSessionPoolBigPageTableSize
PPOOL_DESCRIPTOR ExpSessionPoolDescriptor
PGENERAL_LOOKASIDE ExpSessionPoolLookaside
ULONG ExpSessionPoolSmallLists
PPOOL_TRACKER_TABLE ExpSessionPoolTrackTable
SIZE_T ExpSessionPoolTrackTableMask
SIZE_T ExpSessionPoolTrackTableSize
GENERAL_LOOKASIDE ExpSmallNPagedPoolLookasideLists [POOL_SMALL_LISTS]
GENERAL_LOOKASIDE ExpSmallPagedPoolLookasideLists [POOL_SMALL_LISTS]
KSPIN_LOCK ExpTaggedPoolLock
SIZE_T MmSizeOfNonPagedPoolInBytes
POOL_DESCRIPTOR NonPagedPoolDescriptor
PPOOL_TRACKER_BIG_PAGES PoolBigPageTable
SIZE_T PoolBigPageTableHash
SIZE_T PoolBigPageTableSize
ULONG PoolHitTag = 0xffffff0f
PPOOL_TRACKER_TABLE PoolTrackTable
PPOOL_TRACKER_TABLE PoolTrackTableExpansion
SIZE_T PoolTrackTableExpansionPages
SIZE_T PoolTrackTableExpansionSize
SIZE_T PoolTrackTableMask
SIZE_T PoolTrackTableSize
PPOOL_DESCRIPTOR PoolVector [NUMBER_OF_POOLS]
const PRTL_ALLOCATE_STRING_ROUTINE RtlAllocateStringRoutine = ExpAllocateStringRoutine
const PRTL_FREE_STRING_ROUTINE RtlFreeStringRoutine = (PRTL_FREE_STRING_ROUTINE)ExFreePool
Macro Definition Documentation
#define ASSERT_ALLOCATE_IRQL (_PoolType, _NumberOfBytes)
Value:
if ((_PoolType & BASE_POOL_TYPE_MASK) == PagedPool) {               \
        if (KeGetCurrentIrql() > APC_LEVEL) {                           \
            KeBugCheckEx (BAD_POOL_CALLER, 8, KeGetCurrentIrql(), _PoolType, _NumberOfBytes);                                                           \
        }                                                               \
    }                                                                   \
    else {                                                              \
        if (KeGetCurrentIrql() > DISPATCH_LEVEL) {                      \
            KeBugCheckEx (BAD_POOL_CALLER, 8, KeGetCurrentIrql(), _PoolType, _NumberOfBytes);                                                           \
        }                                                               \
    }
Definition at line 551 of file pool.c.
Referenced by __bcount().
#define ASSERT_FREE_IRQL (_PoolType, _P)
Value:
if ((_PoolType & BASE_POOL_TYPE_MASK) == PagedPool) {               \
        if (KeGetCurrentIrql() > APC_LEVEL) {                           \
            KeBugCheckEx (BAD_POOL_CALLER, 9, KeGetCurrentIrql(), _PoolType, (ULONG_PTR)_P);                                                            \
        }                                                               \
    }                                                                   \
    else {                                                              \
        if (KeGetCurrentIrql() > DISPATCH_LEVEL) {                      \
            KeBugCheckEx (BAD_POOL_CALLER, 9, KeGetCurrentIrql(), _PoolType, (ULONG_PTR)P);                                                             \
        }                                                               \
    }
Definition at line 563 of file pool.c.
Referenced by ExFreePoolWithTag().
#define ASSERT_POOL_NOT_FREE (_Entry)
Value:
if ((_Entry->PoolType & POOL_TYPE_MASK) == 0) {                     \
        KeBugCheckEx (BAD_POOL_CALLER, 6, __LINE__, (ULONG_PTR)_Entry, _Entry->Ulong1);                                                                 \
    }
Definition at line 575 of file pool.c.
Referenced by ExFreePoolWithTag().
#define ASSERT_POOL_TYPE_NOT_ZERO (_Entry)
Value:
if (_Entry->PoolType == 0) {                                        \
        KeBugCheckEx(BAD_POOL_CALLER, 1, (ULONG_PTR)_Entry, (ULONG_PTR)(*(PULONG)_Entry), 0);                                                           \
    }
Definition at line 580 of file pool.c.
Referenced by ExFreePoolWithTag().
#define CacheOverhead POOL_OVERHEAD
Referenced by __bcount().
#define CHECK_LIST (LIST)
Value:
if ((DecodeLink(DecodeLink((LIST)->Flink)->Blink) != (LIST)) ||         \
        (DecodeLink(DecodeLink((LIST)->Blink)->Flink) != (LIST))) {         \
            KeBugCheckEx (BAD_POOL_HEADER,                                  \
                          3,                                                \
                          (ULONG_PTR)LIST,                                  \
                          (ULONG_PTR)DecodeLink(DecodeLink((LIST)->Flink)->Blink),     \
                          (ULONG_PTR)DecodeLink(DecodeLink((LIST)->Blink)->Flink));    \
    }
Definition at line 443 of file pool.c.
Referenced by __bcount(), ExDeferredFreePool(), and ExFreePoolWithTag().
#define CHECK_POOL_HEADER (ENTRY) ExCheckPoolHeader(ENTRY)
Definition at line 549 of file pool.c.
#define CHECK_POOL_PAGE (PAGE)
Value:
{                                                                         \
        PPOOL_HEADER P = (PPOOL_HEADER)PAGE_ALIGN(PAGE);                      \
        ULONG SIZE = 0;                                                       \
        LOGICAL FOUND=FALSE;                                                  \
        ASSERT (P->PreviousSize == 0);                                        \
        do {                                                                  \
            if (P == (PPOOL_HEADER)PAGE) {                                    \
                FOUND = TRUE;                                                 \
            }                                                                 \
            CHECK_POOL_HEADER(P);                                             \
            SIZE += P->BlockSize;                                             \
            P = (PPOOL_HEADER)((PPOOL_BLOCK)P + P->BlockSize);                \
        } while ((SIZE < (PAGE_SIZE / POOL_SMALLEST_BLOCK)) &&                \
                 (PAGE_END(P) == FALSE));                                     \
        if ((PAGE_END(P) == FALSE) || (FOUND == FALSE)) {                     \
            KeBugCheckEx (BAD_POOL_HEADER, 0xA, (ULONG_PTR) PAGE, __LINE__, (ULONG_PTR) P); \
        }                                                                     \
    }
Definition at line 585 of file pool.c.
Referenced by __bcount(), ExDeferredFreePool(), and ExFreePoolWithTag().
#define DECODE_POOL_INDEX (POOLHEADER) ((ULONG)((POOLHEADER)->PoolIndex))
Definition at line 287 of file pool.c.
Referenced by __bcount(), ExCheckPoolHeader(), ExDeferredFreePool(), and ExFreePoolWithTag().
#define DecodeLink (Link) ((PLIST_ENTRY)((ULONG_PTR)(Link) & ~1))
Definition at line 417 of file pool.c.
Referenced by ExDeferredFreePool(), and ExFreePoolWithTag().
#define DEFAULT_BIGPAGE_TABLE 4096
Definition at line 154 of file pool.c.
Referenced by InitializePool().
#define DEFAULT_TRACKER_TABLE 2048
Definition at line 138 of file pool.c.
Referenced by InitializePool().
#define ENCODE_POOL_INDEX (POOLHEADER, INDEX) {(POOLHEADER)->PoolIndex = ((UCHAR)(INDEX));}
Definition at line 286 of file pool.c.
Referenced by __bcount(), and ExDeferredFreePool().
#define EncodeLink (Link) ((PLIST_ENTRY)((ULONG_PTR)(Link) | 1))
Definition at line 418 of file pool.c.
#define EX_FREE_POOL_BACKTRACE_LENGTH 8
Definition at line 642 of file pool.c.
Referenced by ExFreePoolWithTag().
#define EXP_MAXIMUM_POOL_FREES_PENDING 32
Definition at line 94 of file pool.c.
Referenced by ExFreePoolWithTag().
#define EXP_MAXIMUM_POOL_NODES 16
Definition at line 324 of file pool.c.
Referenced by InitializePool().
#define FREE_CHECK_ERESOURCE (Va, NumberOfBytes)
Value:
if (ExpPoolFlags & EX_CHECK_POOL_FREES_FOR_ACTIVE_RESOURCES) {  \
                ExpCheckForResource(Va, NumberOfBytes);                     \
            }
Definition at line 852 of file pool.c.
Referenced by ExFreePoolWithTag().
#define FREE_CHECK_KTIMER (Va, NumberOfBytes)
Value:
if (ExpPoolFlags & EX_CHECK_POOL_FREES_FOR_ACTIVE_TIMERS) {     \
                KeCheckForTimer(Va, NumberOfBytes);                         \
            }
Definition at line 857 of file pool.c.
Referenced by ExFreePoolWithTag().
#define FREE_CHECK_WORKER (Va, NumberOfBytes)
Value:
if (ExpPoolFlags & EX_CHECK_POOL_FREES_FOR_ACTIVE_WORKERS) {    \
                ExpCheckForWorker(Va, NumberOfBytes);                       \
            }
Definition at line 862 of file pool.c.
Referenced by ExFreePoolWithTag().
#define IS_POOL_HEADER_MARKED_ALLOCATED (POOLHEADER) ((POOLHEADER)->PoolType & POOL_IN_USE_MASK)
Definition at line 296 of file pool.c.
Referenced by ExFreePoolSanityChecks(), and ExFreePoolWithTag().
#define LOCK_POOL (PoolDesc, LockHandle)
Value:
{                                   \
    if ((PoolDesc->PoolType & BASE_POOL_TYPE_MASK) == NonPagedPool) {       \
        if (PoolDesc == &NonPagedPoolDescriptor) {                          \
            LockHandle.OldIrql = KeAcquireQueuedSpinLock(LockQueueNonPagedPoolLock); \
        }                                                                   \
        else {                                                              \
            ASSERT (ExpNumberOfNonPagedPools > 1);                          \
            KeAcquireInStackQueuedSpinLock (PoolDesc->LockAddress, &LockHandle); \
        }                                                                   \
    }                                                                       \
    else {                                                                  \
        KeAcquireGuardedMutex ((PKGUARDED_MUTEX)PoolDesc->LockAddress);     \
    }                                                                       \
}
Definition at line 373 of file pool.c.
Referenced by __bcount(), ExDeferredFreePool(), and ExFreePoolWithTag().
#define MARK_POOL_HEADER_FREED (POOLHEADER) {(POOLHEADER)->PoolType &= ~POOL_IN_USE_MASK;}
Definition at line 295 of file pool.c.
Referenced by ExFreePoolWithTag().
#define MAXIMUM_PROCESSOR_TAG_TABLES 32
Definition at line 131 of file pool.c.
Referenced by ExCreatePoolTagTable(), ExDeletePoolTagTable(), ExpGetPoolTagInfoTarget(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), and ExpRemovePoolTrackerInline().
#define POOL_BIG_TABLE_ENTRY_FREE 0x1
Definition at line 166 of file pool.c.
Referenced by ExGetBigPoolInfo(), ExInitializePoolDescriptor(), ExpAddTagForBigPages(), ExpExpandBigPageTable(), ExpFindAndRemoveTagBigPages(), and InitializePool().
#define POOL_HOTPAGE_MASK POOL_RAISE_IF_ALLOCATION_FAILURE
Definition at line 302 of file pool.c.
#define POOL_IN_USE_MASK 0x4
Definition at line 293 of file pool.c.
Referenced by __bcount(), and ExDrainPoolLookasideList().
#define POOL_SPECIAL_POOL_BIT 0x8
Definition at line 34 of file pool.c.
#define POOL_SPECIAL_POOL_UNDERRUN_BIT 0x1
Definition at line 35 of file pool.c.
#define PrivateInitializeListHead (ListHead)
Value:
(\
    (ListHead)->Flink = (ListHead)->Blink = EncodeLink(ListHead))
Definition at line 420 of file pool.c.
Referenced by ExInitializePoolDescriptor().
#define PrivateInsertHeadList (ListHead, Entry)
Value:
{  \
    PLIST_ENTRY _EX_Flink;                       \
    PLIST_ENTRY _EX_ListHead;                    \
    _EX_ListHead = (ListHead);                   \
    CHECK_LIST(_EX_ListHead);                    \
    _EX_Flink = DecodeLink(_EX_ListHead->Flink); \
    (Entry)->Flink = EncodeLink(_EX_Flink);      \
    (Entry)->Blink = EncodeLink(_EX_ListHead);   \
    _EX_Flink->Blink = EncodeLink(Entry);        \
    _EX_ListHead->Flink = EncodeLink(Entry);     \
    CHECK_LIST(_EX_ListHead);                    \
    }
Definition at line 466 of file pool.c.
Referenced by ExDeferredFreePool(), and ExFreePoolWithTag().
#define PrivateInsertTailList (ListHead, Entry)
Value:
{  \
    PLIST_ENTRY _EX_Blink;                       \
    PLIST_ENTRY _EX_ListHead;                    \
    _EX_ListHead = (ListHead);                   \
    CHECK_LIST(_EX_ListHead);                    \
    _EX_Blink = DecodeLink(_EX_ListHead->Blink); \
    (Entry)->Flink = EncodeLink(_EX_ListHead);   \
    (Entry)->Blink = EncodeLink(_EX_Blink);      \
    _EX_Blink->Flink = EncodeLink(Entry);        \
    _EX_ListHead->Blink = EncodeLink(Entry);     \
    CHECK_LIST(_EX_ListHead);                    \
    }
Definition at line 453 of file pool.c.
Referenced by __bcount().
#define PrivateIsListEmpty (ListHead) (DecodeLink((ListHead)->Flink) == (ListHead))
Definition at line 423 of file pool.c.
Referenced by __bcount().
#define PrivateRemoveEntryList (Entry)
Value:
{       \
    PLIST_ENTRY _EX_Blink;                    \
    PLIST_ENTRY _EX_Flink;                    \
    _EX_Flink = DecodeLink((Entry)->Flink);   \
    _EX_Blink = DecodeLink((Entry)->Blink);   \
    _EX_Blink->Flink = EncodeLink(_EX_Flink); \
    _EX_Flink->Blink = EncodeLink(_EX_Blink); \
    }
Definition at line 434 of file pool.c.
Referenced by ExDeferredFreePool(), and ExFreePoolWithTag().
#define PrivateRemoveHeadList (ListHead)
Value:
DecodeLink((ListHead)->Flink);                          \
    {PrivateRemoveEntryList(DecodeLink((ListHead)->Flink))}
Definition at line 426 of file pool.c.
Referenced by __bcount().
#define PrivateRemoveTailList (ListHead)
Value:
DecodeLink((ListHead)->Blink);                          \
    {PrivateRemoveEntryList(DecodeLink((ListHead)->Blink))}
Definition at line 430 of file pool.c.
#define UNLOCK_POOL (PoolDesc, LockHandle)
Value:
{                                 \
    if ((PoolDesc->PoolType & BASE_POOL_TYPE_MASK) == NonPagedPool) {       \
        if (PoolDesc == &NonPagedPoolDescriptor) {                          \
            KeReleaseQueuedSpinLock(LockQueueNonPagedPoolLock, LockHandle.OldIrql); \
        }                                                                   \
        else {                                                              \
            ASSERT (ExpNumberOfNonPagedPools > 1);                          \
            KeReleaseInStackQueuedSpinLock (&LockHandle);                   \
        }                                                                   \
    }                                                                       \
    else {                                                                  \
        KeReleaseGuardedMutex ((PKGUARDED_MUTEX)PoolDesc->LockAddress);     \
    }                                                                       \
}
Definition at line 390 of file pool.c.
Referenced by __bcount(), ExDeferredFreePool(), and ExFreePoolWithTag().
#define USING_HOT_COLD_METRICS 0
Definition at line 91 of file pool.c.
Referenced by __bcount(), and ExFreePoolWithTag().
Typedef Documentation
typedef struct _EX_FREE_POOL_TRACES EX_FREE_POOL_TRACES
typedef struct _EX_FREE_POOL_TRACES * PEX_FREE_POOL_TRACES
typedef struct _POOL_DPC_CONTEXT POOL_DPC_CONTEXT
typedef struct _POOL_DPC_CONTEXT * PPOOL_DPC_CONTEXT
Function Documentation
NTKERNELAPI __bcount (NumberOfBytes)
Definition at line 1738 of file pool.c.
References ASSERT, ASSERT_ALLOCATE_IRQL, BAD_POOL_CALLER, BASE_POOL_TYPE_MASK, _POOL_HEADER::BlockSize, BYTES_TO_PAGES, CacheOverhead, CHECK_LIST, CHECK_POOL_PAGE, _KNODE::Color, DbgBreakPoint(), DECODE_POOL_INDEX, ENCODE_POOL_INDEX, EX_DELAY_POOL_FREES, EX_KERNEL_VERIFIER_ENABLED, EX_PRINT_POOL_FAILURES, EX_SPECIAL_POOL_ENABLED, EX_STOP_ON_POOL_FAILURES, ExDeferredFreePool(), ExpAddTagForBigPages(), ExpInsertPoolTracker(), ExpInsertPoolTrackerInline(), ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExPoolFailures, ExpPoolFlags, ExpPoolIndex, ExpSessionPoolDescriptor, ExpSessionPoolLookaside, ExpSessionPoolSmallLists, ExRaiseStatus(), FALSE, HighPoolPriority, Index, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedIncrement, InterlockedPopEntrySList(), KdPrint, KeBugCheckEx(), KeGetCurrentPrcb(), KeGetOwnerGuardedMutex(), KeNumberNodes, _PP_LOOKASIDE_LIST::L, _POOL_DESCRIPTOR::ListHeads, LOCK_POOL, MiAllocatePoolPages(), MiMarkPoolLargeSession(), MmAllocateSpecialPool(), MmUseSpecialPool(), MUST_SUCCEED_POOL_EMPTY, MUST_SUCCEED_POOL_TYPE_MASK, NonPagedPool, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _PP_LOOKASIDE_LIST::P, PAGE_END, PAGE_SHIFT, PAGE_SIZE, PagedPool, _KPRCB::ParentNode, PERFINFO_ADDPOOLPAGE, PERFINFO_BIGPOOLALLOC, PERFINFO_EXALLOCATEPOOLWITHTAG_DECL, PERFINFO_POOLALLOC, PERFINFO_POOLALLOC_ADDR, POOL_BLOCK_SHIFT, POOL_BUDDY_MAX, POOL_COLD_ALLOCATION, POOL_DRIVER_MASK, POOL_IN_USE_MASK, POOL_LIST_HEADS, POOL_MM_ALLOCATION, POOL_OVERHEAD, POOL_QUOTA_MASK, POOL_RAISE_IF_ALLOCATION_FAILURE, POOL_SMALL_LISTS, POOL_SMALLEST_BLOCK, POOL_VERIFIER_MASK, _POOL_DESCRIPTOR::PoolIndex, _POOL_HEADER::PoolIndex, _POOL_HEADER::PoolTag, _POOL_HEADER::PoolType, _KPRCB::PPNPagedLookasideList, _KPRCB::PPPagedLookasideList, _POOL_HEADER::PreviousSize, PrivateInsertTailList, PrivateIsListEmpty, PrivateRemoveHeadList, ROUND_TO_PAGES, RtlGetCallersAddress(), _POOL_DESCRIPTOR::RunningAllocs, SESSION_POOL_MASK, STATUS_INSUFFICIENT_RESOURCES, Tag, _GENERAL_LOOKASIDE::TotalAllocates, _POOL_DESCRIPTOR::TotalBigPages, _POOL_DESCRIPTOR::TotalBytes, _POOL_DESCRIPTOR::TotalPages, _POOL_HEADER::Ulong1, UNLOCK_POOL, USING_HOT_COLD_METRICS, and VeAllocatePoolWithTagPriority().
VOID ExAllocatePoolSanityChecks (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes)
Definition at line 6147 of file pool.c.
References APC_LEVEL, DISPATCH_LEVEL, DRIVER_VERIFIER_DETECTED_VIOLATION, KeBugCheckEx(), KeGetCurrentIrql(), and PagedPool.
VOID FORCEINLINE ExCheckPoolHeader (IN PPOOL_HEADER Entry)
Definition at line 481 of file pool.c.
References BAD_POOL_HEADER, _POOL_HEADER::BlockSize, DECODE_POOL_INDEX, KeBugCheckEx(), PAGE_ALIGN, PAGE_ALIGNED, PAGE_END, and _POOL_HEADER::PreviousSize.
PVOID ExCreatePoolTagTable (IN ULONG NewProcessorNumber, IN UCHAR NodeNumber)
Definition at line 5542 of file pool.c.
References ASSERT, KeGetCurrentIrql(), MAXIMUM_PROCESSOR_TAG_TABLES, MmAllocateIndependentPages(), NULL, NumberOfBytes, PASSIVE_LEVEL, PoolTrackTableSize, and RtlZeroMemory.
Referenced by KeStartAllProcessors().
VOID ExDeferredFreePool (IN PPOOL_DESCRIPTOR PoolDesc)
Definition at line 5037 of file pool.c.
References ASSERT, BASE_POOL_TYPE_MASK, _POOL_HEADER::BlockSize, CHECK_LIST, CHECK_POOL_PAGE, DECODE_POOL_INDEX, DecodeLink, ENCODE_POOL_INDEX, FALSE, Index, InterlockedCompareExchangePointer, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedIncrement, LOCK_POOL, MiFreePoolPages(), _SINGLE_LIST_ENTRY::Next, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, PAGE_ALIGNED, PAGE_END, PERFINFO_FREEPOOLPAGE, POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_SMALLEST_BLOCK, _POOL_HEADER::PoolType, _POOL_HEADER::PreviousSize, PrivateInsertHeadList, PrivateRemoveEntryList, TRUE, and UNLOCK_POOL.
Referenced by __bcount(), ExFreePoolWithTag(), and MiDereferenceSessionFinal().
VOID ExDeletePoolTagTable (IN ULONG NewProcessorNumber)
Definition at line 5578 of file pool.c.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrql, MAXIMUM_PROCESSOR_TAG_TABLES, MmFreeIndependentPages(), NULL, NumberOfBytes, PASSIVE_LEVEL, and PoolTrackTableSize.
Referenced by KeStartAllProcessors().
VOID ExDrainPoolLookasideList (IN PPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 766 of file pool.c.
References _POOL_HEADER::BlockSize, ExAllocateFromPagedLookasideList(), ExpDummyAllocate(), ExpInsertPoolTracker(), NULL, POOL_BLOCK_SHIFT, POOL_IN_USE_MASK, _POOL_HEADER::PoolTag, and _POOL_HEADER::PoolType.
Referenced by MiDereferenceSessionFinal().
VOID ExFreePool (__in PVOID P)
Definition at line 5027 of file pool.c.
References ExFreePoolWithTag().
Referenced by __out_bcount(), BuildQueryDirectoryIrp(), CcDeallocateBcb(), CcDeleteMbcb(), CcDeleteSharedCacheMap(), CcDrainVacbLevelZone(), CcExtendVacbArray(), CcInitializeCacheMap(), CcPostDeferredWrites(), CcUninitializeCacheMap(), CcUnpinData(), CcUnpinDataForThread(), CcWriteBehind(), CcZeroData(), CmCompressKey(), CmGetSystemControlValues(), CmInitSystem1(), CmpAddToHiveFileList(), CmpAllocatePostBlock(), CmpCacheLookup(), CmpCheckKeyAccess(), CmpCleanUpKcbValueCache(), CmpCloneControlSet(), CmpCmdRenameHive(), CmpCompareNewValueDataAgainstKCBCache(), CmpCopyKeyPartial(), CmpCopySyncTree(), CmpCopySyncTree2(), CmpCopyValue(), CmpCreateRegistryRoot(), CmpDelayedDerefKeys(), CmpDiskFullWarningWorker(), CmpDoQueueLateUnloadWorker(), CmpFileWrite(), CmpFindTagIndex(), CmpFlushNotify(), CmpFree(), CmpFreeAllMemory(), CmpFreePostBlock(), CmpGetSymbolicLink(), CmpGetValueData(), CmpGetValueDataFromCache(), CmpHiveRootSecurityDescriptor(), CmpInitializeHardwareConfiguration(), CmpInitializeHiveList(), CmpInitializeRegistryNode(), CmpInitializeSystemHive(), CmpLateUnloadHiveWorker(), CmpLoadHiveVolatile(), CmpMarkIndexDirty(), CmpMergeKeyValues(), CmpNameFromAttributes(), CmpNotifyChangeKey(), CmpOpenHiveFiles(), CmpParseKey(), CmpPrefetchHiveFile(), CmpQueryKeyValueData(), CmpQuotaWarningWorker(), CmpRaiseSelfHealWarning(), CmpRaiseSelfHealWarningWorker(), CmpRemoveSubKey(), CmpSaveBootControlSet(), CmpSaveKeyByFileCopy(), CmpSetSecurityDescriptorInfo(), CmpShiftAllCells2(), CmpSyncKeyValues(), CmpSystemHiveHysteresisWorker(), CmpSystemQuotaWarningWorker(), CmpValueToData(), CmQueryMultipleValueKey(), CmRegisterCallback(), CmSetValueKey(), CmUnRegisterCallback(), DbgkCreateThread(), DbgkpFreeDebugEvent(), DbgkpPostFakeModuleMessages(), DbgkpQueueMessage(), DbgkpSectionToFileHandle(), ExAllocateCacheAwarePushLock(), ExAllocateCacheAwareRundownProtection(), ExDeleteResourceLite(), ExDereferenceHandleDebugInfo(), ExFreeCacheAwarePushLock(), ExFreeCacheAwareRundownProtection(), ExFreeCallBack(), ExGetPoolTagInfo(), ExInitializeNBQueueHead(), ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), ExInitializeSystemLookasideList(), ExLockUserBuffer(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateHandleTable(), ExpAllocateSharedWaiterSemaphore(), ExpAllocateTablePagedPool(), ExpAllocateTablePagedPoolNoZero(), ExpExpandResourceOwnerTable(), ExpFreeHandleTable(), ExpFreeTablePagedPool(), ExpGetProcessInformation(), ExpKeyedEventInitialization(), ExpProfileDelete(), ExpSystemErrorHandler(), ExRegisterCallback(), ExUnlockUserBuffer(), ExUnregisterCallback(), FsRtlAddLargeEntry(), FsRtlAllocateOplock(), FsRtlCancelNotify(), FsRtlDeregisterUncProvider(), FsRtlFreeTunnelNode(), FsRtlGetCompatibilityModeValue(), FsRtlGetTunnelParameterValue(), FsRtlInsertPerFileObjectContext(), FsRtlIsDbcsInExpression(), FsRtlIsNameInExpressionPrivate(), FsRtlNotifyCleanup(), FsRtlNotifyCompleteIrp(), FsRtlNotifyFilterChangeDirectory(), FsRtlNotifyFilterReportChange(), FsRtlNotifyUninitializeSync(), FsRtlpRegisterProviderWithMUP(), FsRtlPTeardownPerFileObjectContexts(), FsRtlRegisterUncProvider(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlStackOverflowRead(), FsRtlTruncateBaseMcb(), FsRtlUninitializeBaseMcb(), FsRtlUninitializeOplock(), HalExamineMBR(), HalpDeleteMountLetter(), HalpGetFullGeometry(), HalpNextMountLetter(), HalpSetMountLetter(), HvpDoWriteHive(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpWriteLog(), HvRefreshHive(), HvReleaseFreeCellRefArray(), HvTrackCellRef(), HvWriteHive(), IoAllocateDriverObjectExtension(), IoAssignDriveLetters(), IoBuildDeviceIoControlRequest(), IoConnectInterrupt(), IoCreateDevice(), IoDeleteDevice(), IoDisconnectInterrupt(), IoFreeErrorLogEntry(), IoFreeMdl(), IoFreeWorkItem(), IoGetBootDiskInformation(), IoInitSystem(), IoIsValidNameGraftingBuffer(), IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), IopApcHardError(), IopBuildFullDriverPath(), IopCallBootDriverReinitializationRoutines(), IopCallDriverReinitializationRoutines(), IopCompleteRequest(), IopCopyBootLogRegistryToFile(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopCreateFile(), IopDeallocateApc(), IopDeleteDevice(), IopDeleteDriver(), IopDeleteFile(), IopDeleteSessionSymLinks(), IopDereferenceVpbAndFree(), IopDoNameTransmogrify(), IopDropIrp(), IopErrorLogDpc(), IopErrorLogThread(), IopExceptionCleanup(), IopfCompleteRequest(), IopFreeIrp(), IopFreeMiniPacket(), IopGetDriverNameFromKeyNode(), IopGetRegistryKeyInformation(), IopGetRegistryValue(), IopGetSetSecurityObject(), IopHardErrorThread(), IopLoadDriver(), IopParseDevice(), IopQueryNameInternal(), IopRaiseHardError(), IopRaiseInformationalHardError(), IopSafebootDriverLoad(), IopSetDeviceSecurityDescriptor(), IopSetEaOrQuotaInformationFile(), IopStartApcHardError(), IopSynchronousApiServiceTail(), IopTrackLink(), IopUnloadDriver(), IopUnloadSafeCompletion(), IoQueryFileDosDeviceName(), IoRaiseInformationalHardError(), IoReadPartitionTable(), IoSetPartitionInformation(), IoShutdownSystem(), IoUnregisterFsRegistrationChange(), IoUnregisterShutdownNotification(), IoVolumeDeviceToDosName(), IoWMISuggestInstanceName(), IoWMISystemControl(), IoWriteErrorLogEntry(), IoWritePartitionTable(), Ke386CallBios(), KeRestoreFloatingPointState(), KeStartProfile(), KeStopProfile(), KiAddRange(), KiCompleteEffectiveRangeChange(), KiInitializeInterruptTimersDpc(), KiInitializeMTRR(), LpcpDestroyPortQueue(), MiAddViewsForSection(), MiAllocateAweInfo(), MiAllocateContiguousMemory(), MiAllocateLargePages(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiAweViewRemover(), MiBuildImportsForBootDrivers(), MiCcPutPagesInTransition(), MiCcReleasePrefetchResources(), MiCleanPhysicalProcessPages(), MiClearImports(), MiCloneProcessAddressSpace(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreateMemoryEvent(), MiCreatePagingFileMap(), MiCreatePebOrTeb(), MiCreatePhysicalVadRoot(), MiDecrementCloneBlockReference(), MiDereferenceImports(), MiDereferenceIoSpace(), MiDoPoolCopy(), MiFindContiguousMemoryInPool(), MiFlushSectionInternal(), MiFreeAweInfo(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiFreeMdlTracker(), MiFreeSessionPoolBitMaps(), MiFreeSessionSpaceMap(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiInitializeLoadedModuleList(), MiInitializeSystemPtes(), MiInsertAweInfo(), MiInsertInSystemSpace(), MiInsertPteTracker(), MiLdwPopupWorker(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiPhysicalViewRemover(), MiReleaseAllMemory(), MiReleaseProcessReferenceToSessionDataPage(), MiRemoveIoSpaceMap(), MiRemoveMappedView(), MiRemoveUnusedSegments(), MiRemoveVadCharges(), MiResolveImageReferences(), MiReturnLargePages(), MiSectionInitialization(), MiSecureVirtualMemory(), MiSegmentDelete(), MiSessionCreateInternal(), MiSessionInsertImage(), MiSessionProcessGlobalSubsections(), MiSessionRemoveImage(), MiSessionWideReserveImageAddress(), MiShutdownSystem(), MiSnapThunk(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MiUnsecureVirtualMemory(), MiZeroPageFile(), MiZeroPageWorker(), MmCallDllInitialize(), MmCleanProcessAddressSpace(), MmCreateSection(), MmDeleteTeb(), MmExtendSection(), MmFreeBootRegistry(), MmFreeContiguousMemory(), MmFreeLoaderBlock(), MmFreeNonCachedMemory(), MmGetFileNameForAddress(), MmGetFileNameForSection(), MmInitializeMemoryLimits(), MmInitializeProcessAddressSpace(), MmLoadSystemImage(), MmPerfUnusedSegmentsEnumerate(), MmProbeAndLockSelectedPages(), MmProtectMdlSystemAddress(), MmUnloadSystemImage(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtCloseObjectAuditAlarm(), NtCompactKeys(), NtCreateJobSet(), NtCreatePagingFile(), NtDeleteObjectAuditAlarm(), NtFlushBuffersFile(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLoadDriver(), NtLoadKeyEx(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtOpenObjectAuditAlarm(), NtOpenThreadTokenEx(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryInformationProcess(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtQueueApcThread(), NtReadFileScatter(), NtReplaceKey(), NtSecureConnectPort(), NtSetEaFile(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationProcess(), NtSetSystemInformation(), NtSetValueKey(), NtSetVolumeInformationFile(), NtStartProfile(), NtStopProfile(), NtUnlockFile(), NtWriteFileGather(), ObAssignObjectSecurityDescriptor(), ObCreateObjectType(), ObDereferenceSecurityDescriptor(), ObfDereferenceDeviceMap(), ObGetObjectSecurity(), ObInitSystem(), ObLogSecurityDescriptor(), ObOpenObjectByName(), ObpCaptureObjectName(), ObpDeleteDirectoryEntry(), ObpDeleteSymbolicLink(), ObpDereferenceNameInfo(), ObpFreeDosDevicesProtection(), ObpFreeObject(), ObpFreeObjectNameBuffer(), ObpInsertHandleCount(), ObpLookupObjectName(), ObpParseSymbolicLink(), ObpRemoveObjectRoutine(), ObpWaitForMultipleObjects(), ObReleaseObjectSecurity(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObSetSecurityDescriptorInfo(), ObShutdownSystem(), PerfInfoFileNameRunDown(), PerfInfoProcessRunDown(), PerfInfoSysModuleRunDown(), Phase1InitializationDiscard(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), PspCaptureTokenFilter(), PspDeleteLdt(), PspDeleteVdmObjects(), PspDereferenceQuotaBlock(), PspExitApcRundown(), PspExitThread(), PspJobDelete(), PspNullSpecialApc(), PspProcessDelete(), PspQueueApcSpecialApc(), PspSetLdtInformation(), PspSetLdtSize(), PspSetQuotaLimits(), PspTerminateThreadByPointer(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawCheckForDismount(), RtlpAllocDeallocQueryBuffer(), RtlpComputeMergedAcl(), RtlpConvertAclToAutoInherit(), RtlpConvertToAutoInheritSecurityObject(), RtlpFreeAtom(), RtlpInheritAcl(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), RtlpSysVolFree(), SeAccessCheckByType(), SeAppendPrivileges(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeCaptureAcl(), SeCaptureAuditPolicy(), SeCaptureLuidAndAttributesArray(), SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSecurityQos(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SeDeassignSecurity(), SeDeleteAccessState(), SeFreeCapturedObjectTypeList(), SeFreeCapturedSecurityQos(), SeFreePrivileges(), SeInitializeProcessAuditName(), SeLocateProcessImageName(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), SeMakeSystemToken(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtLogAuditRecord(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAuditAssignPrimaryToken(), SepCleanupLUIDDeviceMapDirectory(), SepCreateLogonSessionTrack(), SepCreateToken(), SepDeleteLogonSessionTrack(), SepDequeueWorkItem(), SepDeReferenceLogonSession(), SepDuplicateToken(), SepExpandDynamic(), SepFilterToken(), SepFreeCapturedString(), SepFreeProxyData(), SepInformLsaOfDeletedLogon(), SepInitializationPhase1(), SepInitProcessAuditSd(), SepNotifyFileSystems(), SepProbeAndCaptureQosData(), SepProbeAndCaptureString_U(), SepQueryNameString(), SepQueryTypeString(), SepRmCallLsa(), SepTokenDeleteMethod(), SeReleaseAcl(), SeReleaseAuditPolicy(), SeReleaseLuidAndAttributesArray(), SeReleaseSecurityDescriptor(), SeReleaseSid(), SeReleaseSidAndAttributesArray(), SeRmInitPhase1(), SeUnregisterLogonSessionTerminatedRoutine(), WmipAddLogHeader(), WmipAllocGuidEntryX(), WmipCheckGuidAccess(), WmipCheckIsWbemRunning(), WmipCreateAdminSD(), WmipCreateGuidObject(), WmipCreateLogFile(), WmipCreateNtFileName(), WmipCreatePumpThread(), WmipCreatePumpThreadRoutine(), WmipDelayCreate(), WmipDriverEntry(), WmipEventNotification(), WmipFireOffWmiEvent(), WmipFlushBuffersWithMarker(), WmipFreeLoggerContext(), WmipGECleanup(), WmipGenerateFileName(), WmipGenerateMCAEventlog(), WmipGetDevicePDO(), WmipGetGuidSecurityDescriptor(), WmipGetLogFromHal(), WmipInitializeSecurity(), WmipProcessEvent(), WmipProcessPrevMcaLogs(), WmipPumpThreadApc(), WmipQueryLogAndFireEvent(), WmipQueueNotification(), WmipRegisterOrUpdateDS(), WmipSecurityMethod(), WmipStartLogger(), WmipSwitchToNewFile(), WmipTraceFile(), WmipTraceIo(), WmiStartTrace(), WmiTraceProcess(), and xHalGetPartialGeometry().
VOID ExFreePoolSanityChecks (IN PVOID P)
Definition at line 6201 of file pool.c.
References APC_LEVEL, _POOL_HEADER::BlockSize, BYTE_OFFSET, DISPATCH_LEVEL, DRIVER_VERIFIER_DETECTED_VIOLATION, ExpCheckForResource(), ExpCheckForWorker(), ExpPoolFlags, IS_POOL_HEADER_MARKED_ALLOCATED, KeBugCheckEx(), KeCheckForTimer(), KeGetCurrentIrql(), MM_HIGHEST_USER_ADDRESS, MmDeterminePoolType(), MmIsSpecialPoolAddress(), NULL, PAGE_ALIGNED, PAGE_SIZE, PagedPool, POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_TYPE_MASK, _POOL_HEADER::PoolType, and _POOL_HEADER::Ulong1.
VOID ExFreePoolWithTag (__in PVOID P, __in ULONG TagToFree)
Definition at line 4297 of file pool.c.
References ASSERT, ASSERT_FREE_IRQL, ASSERT_POOL_NOT_FREE, ASSERT_POOL_TYPE_NOT_ZERO, BAD_POOL_CALLER, BAD_POOL_HEADER, BASE_POOL_TYPE_MASK, _POOL_HEADER::BlockSize, CHECK_LIST, CHECK_POOL_PAGE, _KNODE::Color, DECODE_POOL_INDEX, DecodeLink, EX_CHECK_POOL_FREES_FOR_ACTIVE_RESOURCES, EX_CHECK_POOL_FREES_FOR_ACTIVE_TIMERS, EX_CHECK_POOL_FREES_FOR_ACTIVE_WORKERS, EX_DELAY_POOL_FREES, EX_FREE_POOL_BACKTRACE_LENGTH, EX_KERNEL_VERIFIER_ENABLED, EX_VERIFIER_DEADLOCK_DETECTION_ENABLED, ExDeferredFreePool(), ExFreePoolIndex, ExFreePoolMask, EXP_MAXIMUM_POOL_FREES_PENDING, ExpFindAndRemoveTagBigPages(), ExpGetBilledProcess(), ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExpPoolFlags, ExpRemovePoolTracker(), ExpRemovePoolTrackerInline(), ExpSessionPoolDescriptor, ExpSessionPoolLookaside, ExpSessionPoolSmallLists, ExQueryDepthSList, FALSE, FREE_CHECK_ERESOURCE, FREE_CHECK_KTIMER, FREE_CHECK_WORKER, Index, InterlockedCompareExchangePointer, InterlockedDecrement, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedIncrement, InterlockedPushEntrySList(), IS_POOL_HEADER_MARKED_ALLOCATED, KeBugCheckEx(), KeGetCurrentPrcb(), KeNumberNodes, _PP_LOOKASIDE_LIST::L, _POOL_DESCRIPTOR::ListHeads, LOCK_POOL, MARK_POOL_HEADER_FREED, MiFreePoolPages(), MiIsPoolLargeSession(), MmDeterminePoolType(), MmFreeSpecialPool(), MmGetSizeOfBigPoolAllocation(), MmIsSpecialPoolAddress(), NonPagedPool, NonPagedPoolSession, NULL, NumberOfBytes, ObDereferenceObject(), _KLOCK_QUEUE_HANDLE::OldIrql, _PP_LOOKASIDE_LIST::P, PAGE_ALIGN, PAGE_ALIGNED, PAGE_END, PAGE_SHIFT, PAGE_SIZE, PagedPool, PagedPoolSession, _KPRCB::ParentNode, _POOL_DESCRIPTOR::PendingFreeDepth, _POOL_DESCRIPTOR::PendingFrees, PERFINFO_FREEPOOL, PERFINFO_FREEPOOLPAGE, POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_SMALL_LISTS, POOL_SMALLEST_BLOCK, POOL_TYPE_MASK, POOL_VERIFIER_MASK, _EX_FREE_POOL_TRACES::PoolAddress, _EX_FREE_POOL_TRACES::PoolHeader, _POOL_DESCRIPTOR::PoolIndex, _POOL_HEADER::PoolIndex, _POOL_HEADER::PoolTag, _POOL_HEADER::PoolType, _KPRCB::PPNPagedLookasideList, _KPRCB::PPPagedLookasideList, _POOL_HEADER::PreviousSize, PrivateInsertHeadList, PrivateRemoveEntryList, PROTECTED_POOL, PsGetCurrentThread(), PSLIST_ENTRY, PsReturnPoolQuota(), ReadForWriteAccess, RtlCaptureStackBackTrace(), RtlZeroMemory, _POOL_DESCRIPTOR::RunningDeAllocs, SESSION_POOL_MASK, _EX_FREE_POOL_TRACES::StackTrace, Tag, _EX_FREE_POOL_TRACES::Thread, _POOL_DESCRIPTOR::TotalBigPages, _POOL_DESCRIPTOR::TotalBytes, _GENERAL_LOOKASIDE::TotalFrees, _POOL_DESCRIPTOR::TotalPages, TRUE, _POOL_HEADER::Ulong1, UNLOCK_POOL, UNREFERENCED_PARAMETER, USING_HOT_COLD_METRICS, VerifierDeadlockFreePool(), and VerifierFreeTrackedPool().
Referenced by ExFreePool().
NTSTATUS ExGetBigPoolInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
Definition at line 5996 of file pool.c.
References ARGUMENT_PRESENT, ASSERT, ExAcquireSpinLockExclusive(), except, EXCEPTION_EXECUTE_HANDLER, ExpLargePoolTableLock, ExReleaseSpinLockExclusive(), FIELD_OFFSET, KeGetCurrentIrql(), _POOL_TRACKER_BIG_PAGES::Key, MiAllocatePoolPages(), MiFreePoolPages(), MmDeterminePoolType(), NonPagedPool, NULL, _POOL_TRACKER_BIG_PAGES::NumberOfPages, PAGE_SHIFT, PASSIVE_LEVEL, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTableSize, PROTECTED_POOL, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by NtQuerySystemInformation().
NTSTATUS ExGetPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
Definition at line 5767 of file pool.c.
References ARGUMENT_PRESENT, ASSERT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExpGetPoolTagInfoTarget(), FIELD_OFFSET, KeGenericCallDpc(), KeGetCurrentIrql(), _POOL_TRACKER_TABLE::Key, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, NonPagedPool, NULL, NumberOfBytes, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, PASSIVE_LEVEL, _POOL_DPC_CONTEXT::PoolTrackTable, _POOL_DPC_CONTEXT::PoolTrackTableExpansion, PoolTrackTableExpansionSize, PoolTrackTableSize, _POOL_DPC_CONTEXT::PoolTrackTableSize, _POOL_DPC_CONTEXT::PoolTrackTableSizeExpansion, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExGetSessionPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnedEntries, IN OUT PULONG ActualEntries)
Definition at line 5889 of file pool.c.
References ASSERT, ExpSessionPoolTrackTable, ExpSessionPoolTrackTableSize, KeGetCurrentIrql(), _POOL_TRACKER_TABLE::Key, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, PASSIVE_LEVEL, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by ExGetSessionPoolTagInformation().
VOID ExInitializePoolDescriptor (IN PPOOL_DESCRIPTOR PoolDescriptor, IN POOL_TYPE PoolType, IN ULONG PoolIndex, IN ULONG Threshold, IN PVOID PoolLock)
Definition at line 660 of file pool.c.
References ExpSessionPoolBigPageTableHash, ExpSessionPoolBigPageTableSize, ExpSessionPoolLookaside, ExpSessionPoolSmallLists, ExpSessionPoolTrackTableMask, ExpSessionPoolTrackTableSize, MiSessionPoolBigPageTable(), MiSessionPoolBigPageTableSize(), MiSessionPoolLookaside(), MiSessionPoolSmallLists(), MiSessionPoolTrackTable(), MiSessionPoolTrackTableSize(), MiSessionPoolVector(), NULL, PagedPoolSession, POOL_BIG_TABLE_ENTRY_FREE, POOL_LIST_HEADS, PrivateInitializeListHead, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by InitializePool(), and MiInitializeSessionPool().
VOID ExInsertPoolTag (ULONG Tag, PVOID Va, SIZE_T NumberOfBytes, POOL_TYPE PoolType)
Definition at line 3232 of file pool.c.
References ASSERT, BYTES_TO_PAGES, ExpAddTagForBigPages(), ExpInsertPoolTracker(), FALSE, NonPagedPool, PAGE_SIZE, SESSION_POOL_MASK, and UNREFERENCED_PARAMETER.
Referenced by MiFindContiguousMemoryInPool().
BOOLEAN ExOkayToLockRoutine (IN PVOID Lock)
Definition at line 257 of file pool.c.
References FALSE, KeIsExecutingDpc(), TRUE, and UNREFERENCED_PARAMETER.
LOGICAL ExpAddTagForBigPages (IN PVOID Va, IN ULONG Key, IN ULONG NumberOfPages, IN POOL_TYPE PoolType)
Definition at line 3998 of file pool.c.
References ASSERT, ExAcquireSpinLockShared(), ExpBigTableExpansionFailed, ExpExpandBigPageTable(), ExpLargePoolTableLock, ExpPoolBigEntriesInUse, ExpSessionPoolBigPageTableHash, ExpSessionPoolBigPageTableSize, ExReleaseSpinLockShared(), ExTryAcquireSpinLockExclusive(), FALSE, InterlockedCompareExchangePointer, InterlockedIncrement, _POOL_TRACKER_BIG_PAGES::Key, _POOL_TRACKER_BIG_PAGES::NumberOfPages, PAGE_SHIFT, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTableHash, PoolBigPageTableSize, SESSION_POOL_MASK, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by __bcount(), and ExInsertPoolTag().
PVOID ExpAllocateStringRoutine (IN SIZE_T NumberOfBytes)
Definition at line 249 of file pool.c.
References ExAllocatePoolWithTag, and PagedPool.
PVOID ExpDummyAllocate (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag)
Definition at line 765 of file lookasid.c.
References NULL, and UNREFERENCED_PARAMETER.
Referenced by ExDeleteNPagedLookasideList(), ExDeletePagedLookasideList(), and ExDrainPoolLookasideList().
LOGICAL ExpExpandBigPageTable (IN KIRQL OldIrql)
Definition at line 3865 of file pool.c.
References ExpInsertPoolTracker(), ExpLargePoolTableLock, ExpRemovePoolTracker(), ExReleaseSpinLockExclusive(), FALSE, MiAllocatePoolPages(), MiFreePoolPages(), NonPagedPool, NULL, PAGE_SHIFT, PAGE_SIZE, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTable, PoolBigPageTableHash, PoolBigPageTableSize, ROUND_TO_PAGES, RtlZeroMemory, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by ExpAddTagForBigPages().
ULONG ExpFindAndRemoveTagBigPages (IN PVOID Va, OUT PULONG BigPages, IN POOL_TYPE PoolType)
Definition at line 4181 of file pool.c.
References ASSERT, ExAcquireSpinLockShared(), ExpLargePoolTableLock, ExpPoolBigEntriesInUse, ExpSessionPoolBigPageTableHash, ExpSessionPoolBigPageTableSize, ExReleaseSpinLockShared(), FALSE, InterlockedDecrement, InterlockedIncrement, InterlockedOr(), _POOL_TRACKER_BIG_PAGES::Key, _POOL_TRACKER_BIG_PAGES::NumberOfPages, PAGE_SHIFT, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTableHash, PoolBigPageTableSize, SESSION_POOL_MASK, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by ExFreePoolWithTag().
FORCEINLINE PEPROCESS ExpGetBilledProcess (IN PPOOL_HEADER Entry)
Definition at line 3009 of file pool.c.
References BAD_POOL_CALLER, KeBugCheckEx(), NULL, POOL_BLOCK_SHIFT, POOL_QUOTA_MASK, and ProcessObject.
Referenced by ExFreePoolWithTag(), ExQueryPoolBlockSize(), and ExReturnPoolQuota().
VOID ExpGetPoolTagInfoTarget (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 5640 of file pool.c.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KeSignalCallDpcDone(), KeSignalCallDpcSynchronize(), _POOL_TRACKER_TABLE::Key, MAXIMUM_PROCESSOR_TAG_TABLES, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, NULL, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, _POOL_DPC_CONTEXT::PoolTrackTable, _POOL_DPC_CONTEXT::PoolTrackTableExpansion, _POOL_DPC_CONTEXT::PoolTrackTableSize, _POOL_DPC_CONTEXT::PoolTrackTableSizeExpansion, RtlCopyMemory, and UNREFERENCED_PARAMETER.
Referenced by ExGetPoolTagInfo().
VOID ExpInsertPoolTracker (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
Definition at line 3700 of file pool.c.
References ExpInsertPoolTrackerInline().
Referenced by __bcount(), ExDrainPoolLookasideList(), ExInsertPoolTag(), ExpExpandBigPageTable(), ExpInsertPoolTrackerExpansion(), and InitializePool().
VOID ExpInsertPoolTrackerExpansion (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
Definition at line 3436 of file pool.c.
References ASSERT, ExAcquireSpinLock, ExpInsertPoolTracker(), ExpRemovePoolTracker(), ExpSessionPoolTrackTableSize, ExpTaggedPoolLock, ExReleaseSpinLock, InterlockedExchangeAddSizeT, InterlockedIncrement, _POOL_TRACKER_TABLE::Key, MiAllocatePoolPages(), MiFreePoolPages(), _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, NonPagedPool, NULL, NumberOfBytes, PAGE_SHIFT, PAGE_SIZE, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, PagedPool, PoolTrackTableExpansion, PoolTrackTableExpansionPages, PoolTrackTableExpansionSize, PoolTrackTableSize, PROTECTED_POOL, RtlCopyMemory, RtlZeroMemory, and SESSION_POOL_MASK.
Referenced by ExpInsertPoolTrackerInline().
FORCEINLINE VOID ExpInsertPoolTrackerInline (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
Definition at line 1361 of file pool.c.
References ASSERT, BASE_POOL_TYPE_MASK, DbgBreakPoint(), ExAcquireSpinLock, ExpInsertPoolTrackerExpansion(), ExpSessionPoolTrackTable, ExpSessionPoolTrackTableMask, ExpSessionPoolTrackTableSize, ExpTaggedPoolLock, ExReleaseSpinLock, Index, InterlockedCompareExchange(), InterlockedExchangeAddSizeT, InterlockedIncrement, KeGetCurrentProcessorNumber(), _POOL_TRACKER_TABLE::Key, MAXIMUM_PROCESSOR_TAG_TABLES, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, PagedPool, PoolHitTag, POOLTAG_HASH(), PoolTrackTable, PoolTrackTableMask, PoolTrackTableSize, PROTECTED_POOL, SESSION_POOL_MASK, and TRUE.
Referenced by __bcount(), and ExpInsertPoolTracker().
VOID ExpRemovePoolTracker (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
Definition at line 3854 of file pool.c.
References ExpRemovePoolTrackerInline().
Referenced by ExFreePoolWithTag(), ExpExpandBigPageTable(), and ExpInsertPoolTrackerExpansion().
VOID ExpRemovePoolTrackerExpansion (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
Definition at line 3711 of file pool.c.
References ASSERT, ExAcquireSpinLock, ExpSessionPoolTrackTable, ExpSessionPoolTrackTableSize, ExpTaggedPoolLock, ExReleaseSpinLock, InterlockedExchangeAddSizeT, InterlockedIncrement, KeGetCurrentProcessorNumber(), MAXIMUM_PROCESSOR_TAG_TABLES, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, NumberOfBytes, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, PagedPool, PoolTrackTable, PoolTrackTableExpansionSize, PoolTrackTableSize, PROTECTED_POOL, and SESSION_POOL_MASK.
Referenced by ExpRemovePoolTrackerInline().
FORCEINLINE VOID ExpRemovePoolTrackerInline (IN ULONG Key, IN SIZE_T NumberOfBytes, IN POOL_TYPE PoolType)
Definition at line 1582 of file pool.c.
References ASSERT, BASE_POOL_TYPE_MASK, DbgBreakPoint(), ExpRemovePoolTrackerExpansion(), ExpSessionPoolTrackTable, ExpSessionPoolTrackTableMask, ExpSessionPoolTrackTableSize, Index, InterlockedExchangeAddSizeT, InterlockedIncrement, KeGetCurrentProcessorNumber(), _POOL_TRACKER_TABLE::Key, MAXIMUM_PROCESSOR_TAG_TABLES, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, PagedPool, PoolHitTag, POOLTAG_HASH(), PoolTrackTable, PoolTrackTableMask, PoolTrackTableSize, PROTECTED_POOL, SESSION_POOL_MASK, and TRUE.
Referenced by ExFreePoolWithTag(), and ExpRemovePoolTracker().
VOID ExpSeedHotTags (VOID)
Definition at line 3292 of file pool.c.
References ASSERT, Index, _POOL_TRACKER_TABLE::Key, POOLTAG_HASH(), PoolTrackTable, PoolTrackTableMask, PoolTrackTableSize, and TRUE.
Referenced by InitializePool().
SIZE_T ExQueryPoolBlockSize (__in PVOID PoolBlock, __out PBOOLEAN QuotaCharged)
Definition at line 5317 of file pool.c.
References _POOL_HEADER::BlockSize, ExpGetBilledProcess(), ExpPoolFlags, FALSE, MmIsSpecialPoolAddress(), MmQuerySpecialPoolBlockSize(), PAGE_ALIGNED, PAGE_SIZE, POOL_BLOCK_SHIFT, POOL_OVERHEAD, and TRUE.
VOID ExQueryPoolUsage (__out PULONG PagedPoolPages, __out PULONG NonPagedPoolPages, __out PULONG PagedPoolAllocs, __out PULONG PagedPoolFrees, __out PULONG PagedPoolLookasideHits, __out PULONG NonPagedPoolAllocs, __out PULONG NonPagedPoolFrees, __out PULONG NonPagedPoolLookasideHits)
Definition at line 5373 of file pool.c.
References CONTAINING_RECORD, ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExPoolLookasideListHead, _LIST_ENTRY::Flink, Index, NonPagedPool, NonPagedPoolDescriptor, _POOL_DESCRIPTOR::RunningAllocs, _POOL_DESCRIPTOR::RunningDeAllocs, _POOL_DESCRIPTOR::TotalBigPages, and _POOL_DESCRIPTOR::TotalPages.
Referenced by NtQuerySystemInformation().
VOID ExReturnPoolQuota (IN PVOID P)
Definition at line 5449 of file pool.c.
References _POOL_HEADER::BlockSize, ExpGetBilledProcess(), ExpPoolFlags, InterlockedDecrement, MmIsSpecialPoolAddress(), NULL, ObDereferenceObject(), POOL_BLOCK_SHIFT, POOL_OVERHEAD, POOL_TYPE_MASK, _POOL_HEADER::PoolType, and PsReturnPoolQuota().
Referenced by IopFreeIrp(), and IopFreeMiniPacket().
VOID ExSetPoolFlags (IN ULONG PoolFlag)
Definition at line 869 of file pool.c.
References ExpPoolFlags, and RtlInterlockedSetBits.
Referenced by InitializePool().
VOID InitializePool (IN POOL_TYPE PoolType, IN ULONG Threshold)
Definition at line 894 of file pool.c.
References ASSERT, DEFAULT_BIGPAGE_TABLE, DEFAULT_TRACKER_TABLE, EX_DELAY_POOL_FREES, EX_SEPARATE_HOT_PAGES_DURING_BOOT, EX_SPECIAL_POOL_ENABLED, ExAllocatePoolWithTag, ExFreePoolMask, ExInitializePoolDescriptor(), EXP_MAXIMUM_POOL_NODES, ExpInsertPoolTracker(), ExpNumberOfNonPagedPools, ExpNumberOfPagedPools, ExpPoolFlags, ExpSeedHotTags(), ExpTaggedPoolLock, ExSetPoolFlags(), Index, Int32x32To64, KeBugCheckEx(), KeInitializeDpc(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeInitializeTimer(), KeNumberNodes, KeSetTimer(), MAXULONG_PTR, MiAllocatePoolPages(), MmAllocateIndependentPages(), MmIsVerifierEnabled(), MmNumberOfPhysicalPages, MmSizeOfNonPagedPoolInBytes, MUST_SUCCEED_POOL_EMPTY, MUST_SUCCEED_POOL_TYPE_MASK, NonPagedPool, NonPagedPoolDescriptor, NT_SUCCESS, NULL, NumberOfBytes, PagedPool, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTableHash, PoolBigPageTableSize, PoolTrackTable, PoolTrackTableMask, PoolTrackTableSize, _LARGE_INTEGER::QuadPart, ROUND_TO_PAGES, RtlZeroMemory, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by MiBuildPagedPool(), and MiInitMachineDependent().
FORCEINLINE ULONG POOLTAG_HASH (IN ULONG Key, IN SIZE_T Mask)
Definition at line 172 of file pool.c.
Referenced by ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerInline(), and ExpSeedHotTags().
PVOID VeAllocatePoolWithTagPriority (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag, IN EX_POOL_PRIORITY Priority, IN PVOID CallingAddress)
Referenced by __bcount().
Variable Documentation
LONG ExFreePoolIndex
Definition at line 653 of file pool.c.
Referenced by ExFreePoolWithTag().
LONG ExFreePoolMask = 0x4000 - 1
Definition at line 654 of file pool.c.
Referenced by ExFreePoolWithTag(), and InitializePool().
PEX_FREE_POOL_TRACES ExFreePoolTraces
Definition at line 656 of file pool.c.
ULONG ExpBigTableExpansionFailed
Definition at line 109 of file pool.c.
Referenced by ExpAddTagForBigPages().
EX_SPIN_LOCK ExpLargePoolTableLock
Definition at line 343 of file pool.c.
Referenced by ExGetBigPoolInfo(), ExpAddTagForBigPages(), ExpExpandBigPageTable(), and ExpFindAndRemoveTagBigPages().
PPOOL_DESCRIPTOR ExpNonPagedPoolDescriptor[EXP_MAXIMUM_POOL_NODES]
Definition at line 326 of file pool.c.
ULONG ExpNumberOfNonPagedPools = 1
Definition at line 311 of file pool.c.
Referenced by __bcount(), ExFreePoolWithTag(), ExQueryPoolUsage(), and InitializePool().
ULONG ExpNumberOfPagedPools = NUMBER_OF_PAGED_POOLS
Definition at line 309 of file pool.c.
Referenced by __bcount(), ExFreePoolWithTag(), ExQueryPoolUsage(), and InitializePool().
ULONG ExPoolFailures
Definition at line 280 of file pool.c.
Referenced by __bcount().
PPOOL_TRACKER_TABLE ExPoolTagTables[MAXIMUM_PROCESSOR_TAG_TABLES]
Definition at line 134 of file pool.c.
PPOOL_DESCRIPTOR ExpPagedPoolDescriptor[EXP_MAXIMUM_POOL_NODES+1]
Definition at line 337 of file pool.c.
PKGUARDED_MUTEX ExpPagedPoolMutex
Definition at line 338 of file pool.c.
LONG ExpPoolBigEntriesInUse
Definition at line 110 of file pool.c.
Referenced by ExpAddTagForBigPages(), and ExpFindAndRemoveTagBigPages().
ULONG ExpPoolFlags = 0
Definition at line 849 of file pool.c.
Referenced by __bcount(), ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExQueryPoolBlockSize(), ExReturnPoolQuota(), ExSetPoolFlags(), and InitializePool().
volatile ULONG ExpPoolIndex = 1
Definition at line 340 of file pool.c.
Referenced by __bcount().
PPOOL_TRACKER_BIG_PAGES ExpSessionPoolBigPageTable
Definition at line 101 of file pool.c.
SIZE_T ExpSessionPoolBigPageTableHash
Definition at line 103 of file pool.c.
Referenced by ExInitializePoolDescriptor(), ExpAddTagForBigPages(), and ExpFindAndRemoveTagBigPages().
SIZE_T ExpSessionPoolBigPageTableSize
Definition at line 102 of file pool.c.
Referenced by ExInitializePoolDescriptor(), ExpAddTagForBigPages(), and ExpFindAndRemoveTagBigPages().
PPOOL_DESCRIPTOR ExpSessionPoolDescriptor
Definition at line 96 of file pool.c.
Referenced by __bcount(), and ExFreePoolWithTag().
PGENERAL_LOOKASIDE ExpSessionPoolLookaside
Definition at line 97 of file pool.c.
Referenced by __bcount(), ExFreePoolWithTag(), and ExInitializePoolDescriptor().
ULONG ExpSessionPoolSmallLists
Definition at line 104 of file pool.c.
Referenced by __bcount(), ExFreePoolWithTag(), and ExInitializePoolDescriptor().
PPOOL_TRACKER_TABLE ExpSessionPoolTrackTable
Definition at line 98 of file pool.c.
Referenced by ExGetSessionPoolTagInfo(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), and ExpRemovePoolTrackerInline().
SIZE_T ExpSessionPoolTrackTableMask
Definition at line 100 of file pool.c.
Referenced by ExInitializePoolDescriptor(), ExpInsertPoolTrackerInline(), and ExpRemovePoolTrackerInline().
SIZE_T ExpSessionPoolTrackTableSize
Definition at line 99 of file pool.c.
Referenced by ExGetSessionPoolTagInfo(), ExInitializePoolDescriptor(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), and ExpRemovePoolTrackerInline().
GENERAL_LOOKASIDE ExpSmallNPagedPoolLookasideLists[POOL_SMALL_LISTS]
Definition at line 367 of file pool.c.
Referenced by ExInitPoolLookasidePointers(), ExpInitSystemPhase0(), and ExpScanSystemLookasideList().
GENERAL_LOOKASIDE ExpSmallPagedPoolLookasideLists[POOL_SMALL_LISTS]
Definition at line 369 of file pool.c.
Referenced by ExInitPoolLookasidePointers(), ExpInitSystemPhase0(), and ExpScanSystemLookasideList().
KSPIN_LOCK ExpTaggedPoolLock
Definition at line 341 of file pool.c.
Referenced by ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), and InitializePool().
SIZE_T MmSizeOfNonPagedPoolInBytes
Definition at line 271 of file miglobal.c.
Referenced by InitializePool(), MiComputeInitialLargePage(), MiFreePoolPages(), MiInitializeNonPagedPool(), MiInitMachineDependent(), MmAccessFault(), MmFreeContiguousMemory(), and MmGetSizeOfBigPoolAllocation().
POOL_DESCRIPTOR NonPagedPoolDescriptor
Definition at line 322 of file pool.c.
Referenced by ExQueryPoolUsage(), and InitializePool().
PPOOL_TRACKER_BIG_PAGES PoolBigPageTable
Definition at line 156 of file pool.c.
Referenced by ExpExpandBigPageTable().
SIZE_T PoolBigPageTableHash
Definition at line 164 of file pool.c.
Referenced by ExpAddTagForBigPages(), ExpExpandBigPageTable(), ExpFindAndRemoveTagBigPages(), and InitializePool().
SIZE_T PoolBigPageTableSize
Definition at line 162 of file pool.c.
Referenced by ExGetBigPoolInfo(), ExpAddTagForBigPages(), ExpExpandBigPageTable(), ExpFindAndRemoveTagBigPages(), and InitializePool().
ULONG PoolHitTag = 0xffffff0f
Definition at line 168 of file pool.c.
Referenced by ExpInsertPoolTrackerInline(), and ExpRemovePoolTrackerInline().
PPOOL_TRACKER_TABLE PoolTrackTable
Definition at line 140 of file pool.c.
Referenced by ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), ExpSeedHotTags(), and InitializePool().
PPOOL_TRACKER_TABLE PoolTrackTableExpansion
Definition at line 150 of file pool.c.
Referenced by ExpInsertPoolTrackerExpansion().
SIZE_T PoolTrackTableExpansionPages
Definition at line 152 of file pool.c.
Referenced by ExpInsertPoolTrackerExpansion().
SIZE_T PoolTrackTableExpansionSize
Definition at line 151 of file pool.c.
Referenced by ExGetPoolTagInfo(), ExpInsertPoolTrackerExpansion(), and ExpRemovePoolTrackerExpansion().
SIZE_T PoolTrackTableMask
Definition at line 148 of file pool.c.
Referenced by ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerInline(), ExpSeedHotTags(), and InitializePool().
SIZE_T PoolTrackTableSize
Definition at line 146 of file pool.c.
Referenced by ExCreatePoolTagTable(), ExDeletePoolTagTable(), ExGetPoolTagInfo(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), ExpSeedHotTags(), and InitializePool().
PPOOL_DESCRIPTOR PoolVector[NUMBER_OF_POOLS]
Definition at line 336 of file pool.c.
const PRTL_ALLOCATE_STRING_ROUTINE RtlAllocateStringRoutine = ExpAllocateStringRoutine
Definition at line 274 of file pool.c.
Referenced by IoInitSystem(), RtlAnsiStringToUnicodeString(), RtlCreateUnicodeString(), RtlDowncaseUnicodeString(), RtlDuplicateUnicodeString(), RtlFormatCurrentUserKeyPath(), RtlOemStringToCountedUnicodeString(), RtlOemStringToUnicodeString(), RtlpQueryRegistryDirect(), RtlStringFromGUID(), RtlUnicodeStringToAnsiString(), RtlUnicodeStringToCountedOemString(), RtlUnicodeStringToOemString(), RtlUpcaseUnicodeString(), RtlUpcaseUnicodeStringToAnsiString(), RtlUpcaseUnicodeStringToCountedOemString(), and RtlUpcaseUnicodeStringToOemString().
const PRTL_FREE_STRING_ROUTINE RtlFreeStringRoutine = (PRTL_FREE_STRING_ROUTINE)ExFreePool
Definition at line 275 of file pool.c.
Referenced by RtlAnsiStringToUnicodeString(), RtlFreeAnsiString(), RtlFreeOemString(), RtlFreeUnicodeString(), RtlOemStringToCountedUnicodeString(), RtlOemStringToUnicodeString(), RtlUnicodeStringToAnsiString(), RtlUnicodeStringToCountedOemString(), RtlUnicodeStringToOemString(), RtlUpcaseUnicodeStringToAnsiString(), RtlUpcaseUnicodeStringToCountedOemString(), and RtlUpcaseUnicodeStringToOemString().