Windows Research Kernel v1.2: C:/Windows Research Kernel/dbgk/dbgkobj.c File Reference
dbgkobj.c File Reference
#include "dbgkp.h"
Functions
NTSTATUS DbgkClearProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT SourceDebugObject)
VOID DbgkCopyProcessDebugPort (IN PEPROCESS TargetProcess, IN PEPROCESS SourceProcess)
NTSTATUS DbgkInitialize (VOID)
NTSTATUS DbgkOpenProcessDebugPort (IN PEPROCESS Process, IN KPROCESSOR_MODE PreviousMode, OUT HANDLE *pHandle)
VOID DbgkpCloseObject (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID DbgkpConvertKernelToUserStateChange (PDBGUI_WAIT_STATE_CHANGE WaitStateChange, PDEBUG_EVENT DebugEvent)
VOID DbgkpDeleteObject (IN PVOID Object)
VOID DbgkpFreeDebugEvent (IN PDEBUG_EVENT DebugEvent)
VOID DbgkpMarkProcessPeb (PEPROCESS Process)
VOID DbgkpOpenHandles (PDBGUI_WAIT_STATE_CHANGE WaitStateChange, PEPROCESS Process, PETHREAD Thread)
NTSTATUS DbgkpPostFakeModuleMessages (IN PEPROCESS Process, IN PETHREAD Thread, IN PDEBUG_OBJECT DebugObject)
NTSTATUS DbgkpPostFakeProcessCreateMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD *pLastThread)
NTSTATUS DbgkpPostFakeThreadMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD StartThread, OUT PETHREAD *pFirstThread, OUT PETHREAD *pLastThread)
NTSTATUS DbgkpQueueMessage (IN PEPROCESS Process, IN PETHREAD Thread, IN OUT PDBGKM_APIMSG ApiMsg, IN ULONG Flags, IN PDEBUG_OBJECT TargetDebugObject)
NTSTATUS DbgkpSetProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN NTSTATUS MsgStatus, IN PETHREAD LastThread)
VOID DbgkpWakeTarget (IN PDEBUG_EVENT DebugEvent)
NTSTATUS NtCreateDebugObject (OUT PHANDLE DebugObjectHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Flags)
NTSTATUS NtDebugActiveProcess (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
NTSTATUS NtDebugContinue (IN HANDLE DebugObjectHandle, IN PCLIENT_ID ClientId, IN NTSTATUS ContinueStatus)
NTSTATUS NtRemoveProcessDebug (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
NTSTATUS NtSetInformationDebugObject (IN HANDLE DebugObjectHandle, IN DEBUGOBJECTINFOCLASS DebugObjectInformationClass, IN PVOID DebugInformation, IN ULONG DebugInformationLength, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS NtWaitForDebugEvent (IN HANDLE DebugObjectHandle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL, OUT PDBGUI_WAIT_STATE_CHANGE WaitStateChange)
Variables
POBJECT_TYPE DbgkDebugObjectType = NULL
FAST_MUTEX DbgkpProcessDebugPortMutex
Function Documentation
NTSTATUS DbgkClearProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT SourceDebugObject)
Definition at line 734 of file dbgkobj.c.
References CONTAINING_RECORD, DbgkpMarkProcessPeb(), DbgkpWakeTarget(), _DEBUG_OBJECT::EventList, _DEBUG_EVENT::EventList, ExAcquireFastMutex(), ExReleaseFastMutex(), _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IsListEmpty, _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _DEBUG_EVENT::Process, RemoveEntryList(), RemoveHeadList(), _DEBUG_EVENT::Status, Status, STATUS_DEBUGGER_INACTIVE, STATUS_PORT_NOT_SET, and STATUS_SUCCESS.
Referenced by NtRemoveProcessDebug(), and NtTerminateProcess().
VOID DbgkCopyProcessDebugPort (IN PEPROCESS TargetProcess, IN PEPROCESS SourceProcess)
Definition at line 354 of file dbgkobj.c.
References DEBUG_OBJECT_DELETE_PENDING, ExAcquireFastMutex(), ExReleaseFastMutex(), _DEBUG_OBJECT::Flags, _DEBUG_OBJECT::Mutex, NULL, ObReferenceObject, PAGED_CODE, and PS_PROCESS_FLAGS_NO_DEBUG_INHERIT.
Referenced by PspCreateProcess().
NTSTATUS DbgkInitialize (VOID)
Definition at line 74 of file dbgkobj.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, DbgkpCloseObject(), DbgkpDeleteObject(), DEBUG_ALL_ACCESS, DEBUG_PROCESS_ASSIGN, DEBUG_READ_EVENT, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExInitializeFastMutex, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), PAGED_CODE, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), _OBJECT_TYPE_INITIALIZER::SecurityRequired, STANDARD_RIGHTS_EXECUTE, STANDARD_RIGHTS_READ, STANDARD_RIGHTS_WRITE, Status, SYNCHRONIZE, TRUE, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitializeExecutive().
NTSTATUS DbgkOpenProcessDebugPort (IN PEPROCESS Process, IN KPROCESSOR_MODE PreviousMode, OUT HANDLE * pHandle)
Definition at line 405 of file dbgkobj.c.
References ExAcquireFastMutex(), ExReleaseFastMutex(), MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObReferenceObject, PAGED_CODE, Status, and STATUS_PORT_NOT_SET.
Referenced by NtQueryInformationProcess().
VOID DbgkpCloseObject (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 246 of file dbgkobj.c.
References CONTAINING_RECORD, DbgkpMarkProcessPeb(), DbgkpWakeTarget(), DEBUG_OBJECT_DELETE_PENDING, DEBUG_OBJECT_KILL_ON_CLOSE, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, _DEBUG_OBJECT::Flags, _LIST_ENTRY::Flink, InitializeListHead(), KeSetEvent(), _DEBUG_OBJECT::Mutex, NULL, ObDereferenceObject(), PAGED_CODE, PsGetNextProcess(), PsTerminateProcess(), _DEBUG_EVENT::Status, STATUS_DEBUGGER_INACTIVE, TRUE, and UNREFERENCED_PARAMETER.
Referenced by DbgkInitialize().
VOID DbgkpConvertKernelToUserStateChange (PDBGUI_WAIT_STATE_CHANGE WaitStateChange, PDEBUG_EVENT DebugEvent)
Definition at line 1725 of file dbgkobj.c.
References _DEBUG_EVENT::ApiMsg, _DBGKM_APIMSG::ApiNumber, _DBGUI_WAIT_STATE_CHANGE::AppClientId, ASSERT, _DEBUG_EVENT::ClientId, _DBGKM_APIMSG::CreateProcessInfo, _DBGUI_WAIT_STATE_CHANGE::CreateProcessInfo, _DBGKM_APIMSG::CreateThread, _DBGUI_WAIT_STATE_CHANGE::CreateThread, DbgBreakpointStateChange, DbgCreateProcessStateChange, DbgCreateThreadStateChange, DbgExceptionStateChange, DbgExitProcessStateChange, DbgExitThreadStateChange, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgKmExceptionApi, DbgKmExitProcessApi, DbgKmExitThreadApi, DbgKmLoadDllApi, DbgKmUnloadDllApi, DbgLoadDllStateChange, DbgSingleStepStateChange, DbgUnloadDllStateChange, _DBGKM_APIMSG::Exception, _DBGUI_WAIT_STATE_CHANGE::Exception, _EXCEPTION_RECORD::ExceptionCode, _DBGKM_EXCEPTION::ExceptionRecord, _DBGKM_APIMSG::ExitProcess, _DBGUI_WAIT_STATE_CHANGE::ExitProcess, _DBGKM_APIMSG::ExitThread, _DBGUI_WAIT_STATE_CHANGE::ExitThread, FALSE, _DBGKM_CREATE_PROCESS::FileHandle, _DBGKM_LOAD_DLL::FileHandle, _DBGKM_APIMSG::LoadDll, _DBGUI_WAIT_STATE_CHANGE::LoadDll, _DBGUI_CREATE_PROCESS::NewProcess, _DBGUI_WAIT_STATE_CHANGE::NewState, _DBGUI_CREATE_THREAD::NewThread, NULL, PAGED_CODE, _DBGUI_WAIT_STATE_CHANGE::StateInfo, STATUS_BREAKPOINT, STATUS_SINGLE_STEP, _DBGKM_APIMSG::u, _DBGKM_APIMSG::UnloadDll, and _DBGUI_WAIT_STATE_CHANGE::UnloadDll.
Referenced by NtWaitForDebugEvent().
VOID DbgkpDeleteObject (IN PVOID Object)
Definition at line 127 of file dbgkobj.c.
References ASSERT, _DEBUG_OBJECT::EventList, IsListEmpty, PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by DbgkInitialize().
VOID DbgkpFreeDebugEvent (IN PDEBUG_EVENT DebugEvent)
Definition at line 569 of file dbgkobj.c.
References DbgKmCreateProcessApi, DbgKmLoadDllApi, ExFreePool(), KernelMode, NULL, ObCloseHandle(), ObDereferenceObject(), PAGED_CODE, and Status.
Referenced by DbgkpWakeTarget().
VOID DbgkpMarkProcessPeb (PEPROCESS Process)
Definition at line 162 of file dbgkobj.c.
References _EPROCESS::DebugPort, ExAcquireFastMutex(), ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseFastMutex(), ExReleaseRundownProtection(), FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, PAGED_CODE, _EPROCESS::Pcb, _EPROCESS::Peb, _EPROCESS::RundownProtect, and TRUE.
Referenced by DbgkClearProcessDebugObject(), DbgkpCloseObject(), and DbgkpSetProcessDebugObject().
VOID DbgkpOpenHandles (PDBGUI_WAIT_STATE_CHANGE WaitStateChange, PEPROCESS Process, PETHREAD Thread)
Definition at line 1603 of file dbgkobj.c.
References _DBGUI_WAIT_STATE_CHANGE::CreateProcessInfo, _DBGUI_WAIT_STATE_CHANGE::CreateThread, DbgCreateProcessStateChange, DbgCreateThreadStateChange, DbgLoadDllStateChange, DUPLICATE_SAME_ACCESS, _DBGKM_CREATE_PROCESS::FileHandle, _DBGKM_LOAD_DLL::FileHandle, _DBGUI_CREATE_PROCESS::HandleToProcess, _DBGUI_CREATE_THREAD::HandleToThread, _DBGUI_CREATE_PROCESS::HandleToThread, KernelMode, _DBGUI_WAIT_STATE_CHANGE::LoadDll, _DBGUI_CREATE_PROCESS::NewProcess, _DBGUI_WAIT_STATE_CHANGE::NewState, NT_SUCCESS, NULL, ObCloseHandle(), ObDuplicateObject(), ObOpenObjectByPointer(), PAGED_CODE, PROCESS_CREATE_THREAD, PROCESS_DUP_HANDLE, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, PsGetCurrentProcess(), PsProcessType, PsThreadType, READ_CONTROL, _DBGUI_WAIT_STATE_CHANGE::StateInfo, Status, SYNCHRONIZE, THREAD_GET_CONTEXT, THREAD_QUERY_INFORMATION, THREAD_SET_CONTEXT, THREAD_SET_INFORMATION, THREAD_SUSPEND_RESUME, and THREAD_TERMINATE.
Referenced by NtWaitForDebugEvent().
NTSTATUS DbgkpPostFakeModuleMessages (IN PEPROCESS Process, IN PETHREAD Thread, IN PDEBUG_OBJECT DebugObject)
Definition at line 1207 of file dbgkobj.c.
References _DBGKM_APIMSG::ApiNumber, ASSERT, _DBGKM_LOAD_DLL::BaseOfDll, _UNICODE_STRING::Buffer, CONTAINING_RECORD, DbgKmLoadDllApi, DbgkpQueueMessage(), DEBUG_EVENT_NOWAIT, _DBGKM_LOAD_DLL::DebugInfoFileOffset, _DBGKM_LOAD_DLL::DebugInfoSize, _LDR_DATA_TABLE_ENTRY::DllBase, _LDR_DATA_TABLE_ENTRY32::DllBase, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, _DBGKM_LOAD_DLL::FileHandle, _IMAGE_NT_HEADERS::FileHeader, _LIST_ENTRY::Flink, LIST_ENTRY32::Flink, GENERIC_READ, InitializeObjectAttributes, _PEB_LDR_DATA::InLoadOrderModuleList, _PEB_LDR_DATA32::InLoadOrderModuleList, KernelMode, _DBGKM_APIMSG::LoadDll, MmGetFileNameForAddress(), _DBGKM_LOAD_DLL::NamePointer, NT_SUCCESS, NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, ProbeForReadSmallStructure, RtlCopyMemory, RtlImageNtHeader(), RtlZeroMemory, Status, STATUS_SUCCESS, SYNCHRONIZE, _DBGKM_APIMSG::u, UlongToPtr, UNICODE_NULL, wcsstr(), WOW64_SYSTEM_DIRECTORY_U, and ZwOpenFile().
Referenced by DbgkpPostFakeProcessCreateMessages().
NTSTATUS DbgkpPostFakeProcessCreateMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD * pLastThread)
Definition at line 1398 of file dbgkobj.c.
References DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, and Status.
Referenced by NtDebugActiveProcess().
NTSTATUS DbgkpPostFakeThreadMessages (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN PETHREAD StartThread, OUT PETHREAD * pFirstThread, OUT PETHREAD * pLastThread)
Definition at line 1031 of file dbgkobj.c.
References _DBGKM_APIMSG::ApiNumber, _DBGKM_CREATE_PROCESS::BaseOfImage, _DBGKM_APIMSG::CreateProcessInfo, _DBGKM_APIMSG::CreateThread, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgkpQueueMessage(), DbgkpSectionToFileHandle(), DEBUG_EVENT_NOWAIT, DEBUG_EVENT_PROTECT_FAILED, DEBUG_EVENT_RELEASE, DEBUG_EVENT_SUSPEND, _DBGKM_CREATE_PROCESS::DebugInfoFileOffset, _DBGKM_CREATE_PROCESS::DebugInfoSize, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), FALSE, _DBGKM_CREATE_PROCESS::FileHandle, _IMAGE_NT_HEADERS::FileHeader, _ETHREAD::GrantedAccess, _DBGKM_CREATE_PROCESS::InitialThread, IS_SYSTEM_THREAD, KernelMode, NT_SUCCESS, NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, PsGetNextProcessThread(), PsQuitNextProcessThread(), PsResumeThread(), PsSuspendThread(), RtlImageNtHeader(), RtlZeroMemory, _ETHREAD::RundownProtect, _DBGKM_CREATE_THREAD::StartAddress, _ETHREAD::StartAddress, Status, STATUS_UNSUCCESSFUL, TRUE, and _DBGKM_APIMSG::u.
Referenced by DbgkpPostFakeProcessCreateMessages(), and DbgkpSetProcessDebugObject().
NTSTATUS DbgkpQueueMessage (IN PEPROCESS Process, IN PETHREAD Thread, IN OUT PDBGKM_APIMSG ApiMsg, IN ULONG Flags, IN PDEBUG_OBJECT TargetDebugObject)
Definition at line 598 of file dbgkobj.c.
References _DEBUG_EVENT::ApiMsg, _DEBUG_EVENT::BackoutThread, _DEBUG_EVENT::ClientId, _DEBUG_EVENT::ContinueEvent, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgKmExitProcessApi, DbgKmExitThreadApi, DEBUG_EVENT_INACTIVE, DEBUG_EVENT_NOWAIT, DEBUG_OBJECT_DELETE_PENDING, _DEBUG_OBJECT::EventList, _DEBUG_EVENT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), ExAllocatePoolWithQuotaTag, Executive, ExFreePool(), ExReleaseFastMutex(), FALSE, _DEBUG_OBJECT::Flags, _DEBUG_EVENT::Flags, InsertTailList(), KeInitializeEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _DEBUG_OBJECT::Mutex, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _DEBUG_EVENT::Process, PS_CROSS_THREAD_FLAGS_SKIP_CREATION_MSG, PS_CROSS_THREAD_FLAGS_SKIP_TERMINATION_MSG, PsGetCurrentThread(), _DEBUG_EVENT::Status, Status, STATUS_DEBUGGER_INACTIVE, STATUS_INSUFFICIENT_RESOURCES, STATUS_PORT_NOT_SET, STATUS_SUCCESS, SynchronizationEvent, and _DEBUG_EVENT::Thread.
Referenced by DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), and DbgkpSendApiMessage().
NTSTATUS DbgkpSetProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT DebugObject, IN NTSTATUS MsgStatus, IN PETHREAD LastThread)
Definition at line 820 of file dbgkobj.c.
References _DEBUG_EVENT::BackoutThread, CONTAINING_RECORD, _ETHREAD::CrossThreadFlags, DbgkpMarkProcessPeb(), DbgkpPostFakeThreadMessages(), DbgkpWakeTarget(), DEBUG_EVENT_INACTIVE, DEBUG_EVENT_PROTECT_FAILED, DEBUG_EVENT_RELEASE, DEBUG_OBJECT_DELETE_PENDING, _DEBUG_EVENT::EventList, ExAcquireFastMutex(), ExReleaseFastMutex(), ExReleaseRundownProtection(), FALSE, _DEBUG_EVENT::Flags, _LIST_ENTRY::Flink, _ETHREAD::GrantedAccess, InitializeListHead(), InsertTailList(), IS_SYSTEM_THREAD, IsListEmpty, KeSetEvent(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PS_CROSS_THREAD_FLAGS_SKIP_CREATION_MSG, PS_CROSS_THREAD_FLAGS_SKIP_TERMINATION_MSG, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_SET_BITS, PsGetCurrentThread(), PsGetNextProcessThread(), RemoveEntryList(), RemoveHeadList(), _ETHREAD::RundownProtect, Status, STATUS_DEBUGGER_INACTIVE, STATUS_PORT_ALREADY_SET, STATUS_SUCCESS, _DEBUG_EVENT::Thread, and TRUE.
Referenced by NtDebugActiveProcess().
VOID DbgkpWakeTarget (IN PDEBUG_EVENT DebugEvent)
Definition at line 219 of file dbgkobj.c.
References DbgkpFreeDebugEvent(), DEBUG_EVENT_NOWAIT, DEBUG_EVENT_RELEASE, DEBUG_EVENT_SUSPEND, ExReleaseRundownProtection(), FALSE, KeSetEvent(), NULL, PsResumeThread(), and _ETHREAD::RundownProtect.
Referenced by DbgkClearProcessDebugObject(), DbgkpCloseObject(), DbgkpSetProcessDebugObject(), and NtDebugContinue().
NTSTATUS NtCreateDebugObject (OUT PHANDLE DebugObjectHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Flags)
Definition at line 458 of file dbgkobj.c.
References DEBUG_KILL_ON_CLOSE, DEBUG_OBJECT_KILL_ON_CLOSE, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, except, ExInitializeFastMutex, ExSystemExceptionFilter(), FALSE, _DEBUG_OBJECT::Flags, Handle, InitializeListHead(), KeGetPreviousMode, KeInitializeEvent(), KernelMode, _DEBUG_OBJECT::Mutex, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), PAGED_CODE, ProbeForWriteHandle, Status, and STATUS_INVALID_PARAMETER.
NTSTATUS NtDebugActiveProcess (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
Definition at line 1457 of file dbgkobj.c.
References DbgkpPostFakeProcessCreateMessages(), DbgkpSetProcessDebugObject(), DEBUG_PROCESS_ASSIGN, ExAcquireRundownProtection(), ExReleaseRundownProtection(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsGetCurrentProcess(), PsInitialSystemProcess, PsProcessType, _EPROCESS::RundownProtect, Status, STATUS_ACCESS_DENIED, and STATUS_PROCESS_IS_TERMINATING.
NTSTATUS NtDebugContinue (IN HANDLE DebugObjectHandle, IN PCLIENT_ID ClientId, IN NTSTATUS ContinueStatus)
Definition at line 2010 of file dbgkobj.c.
References _DEBUG_EVENT::ApiMsg, _DEBUG_EVENT::ClientId, CONTAINING_RECORD, DBG_CONTINUE, DBG_EXCEPTION_HANDLED, DBG_EXCEPTION_NOT_HANDLED, DBG_TERMINATE_PROCESS, DBG_TERMINATE_THREAD, DbgkpWakeTarget(), DEBUG_EVENT_INACTIVE, DEBUG_EVENT_READ, DEBUG_READ_EVENT, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), except, ExReleaseFastMutex(), ExSystemExceptionFilter(), FALSE, _DEBUG_EVENT::Flags, _LIST_ENTRY::Flink, KeGetPreviousMode, KernelMode, KeSetEvent(), _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForReadSmallStructure, RemoveEntryList(), _DBGKM_APIMSG::ReturnedStatus, _DEBUG_EVENT::Status, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, _CLIENT_ID::UniqueProcess, and _CLIENT_ID::UniqueThread.
NTSTATUS NtRemoveProcessDebug (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
Definition at line 1548 of file dbgkobj.c.
References DbgkClearProcessDebugObject(), DEBUG_PROCESS_ASSIGN, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsProcessType, and Status.
NTSTATUS NtSetInformationDebugObject (IN HANDLE DebugObjectHandle, IN DEBUGOBJECTINFOCLASS DebugObjectInformationClass, IN PVOID DebugInformation, IN ULONG DebugInformationLength, OUT PULONG ReturnLength OPTIONAL)
Definition at line 2126 of file dbgkobj.c.
References ARGUMENT_PRESENT, DEBUG_KILL_ON_CLOSE, DEBUG_OBJECT_KILL_ON_CLOSE, DEBUG_SET_INFORMATION, DebugObjectFlags, ExAcquireFastMutex(), except, ExReleaseFastMutex(), ExSystemExceptionFilter(), _DEBUG_OBJECT::Flags, KeGetPreviousMode, KernelMode, _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForRead, ProbeForWriteUlong, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS NtWaitForDebugEvent (IN HANDLE DebugObjectHandle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL, OUT PDBGUI_WAIT_STATE_CHANGE WaitStateChange)
Definition at line 1812 of file dbgkobj.c.
References ARGUMENT_PRESENT, _DEBUG_EVENT::BackoutThread, _DEBUG_EVENT::ClientId, CONTAINING_RECORD, DbgkpConvertKernelToUserStateChange(), DbgkpOpenHandles(), DEBUG_EVENT_INACTIVE, DEBUG_EVENT_READ, DEBUG_OBJECT_DELETE_PENDING, DEBUG_READ_EVENT, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), except, Executive, ExReleaseFastMutex(), ExSystemExceptionFilter(), FALSE, _DEBUG_OBJECT::Flags, _DEBUG_EVENT::Flags, _LIST_ENTRY::Flink, KeClearEvent(), KeGetPreviousMode, KeQuerySystemTime(), KernelMode, KeWaitForSingleObject(), _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), _DEBUG_EVENT::Process, _LARGE_INTEGER::QuadPart, Status, STATUS_ALERTED, STATUS_DEBUGGER_INACTIVE, STATUS_SUCCESS, STATUS_TIMEOUT, STATUS_USER_APC, _DEBUG_EVENT::Thread, TRUE, and _CLIENT_ID::UniqueProcess.
Variable Documentation
POBJECT_TYPE DbgkDebugObjectType = NULL
Definition at line 66 of file dbgkobj.c.
Referenced by PspCreateProcess().
FAST_MUTEX DbgkpProcessDebugPortMutex
Definition at line 56 of file dbgkobj.c.