Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmtree.c File Reference
cmtree.c File Reference
#include "cmp.h"
Functions
VALUE_SEARCH_RETURN_TYPE CmpFindValueByNameFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING Name, OUT PPCM_CACHED_VALUE *ContainingList, OUT ULONG *Index, OUT PCM_KEY_VALUE *Value, OUT BOOLEAN *ValueCached, OUT PHCELL_INDEX CellToRelease)
VALUE_SEARCH_RETURN_TYPE CmpGetValueDataFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PPCM_CACHED_VALUE ContainingList, IN PCELL_DATA ValueKey, IN BOOLEAN ValueCached, OUT PUCHAR *DataPointer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
VALUE_SEARCH_RETURN_TYPE CmpGetValueKeyFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PCELL_DATA List, IN ULONG Index, OUT PPCM_CACHED_VALUE *ContainingList, OUT PCM_KEY_VALUE *Value, IN BOOLEAN IndexCached, OUT BOOLEAN *ValueCached, OUT PHCELL_INDEX CellToRelease)
VALUE_SEARCH_RETURN_TYPE CmpGetValueListFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, OUT PCELL_DATA *List, OUT BOOLEAN *IndexCached, OUT PHCELL_INDEX ValueListToRelease)
Function Documentation
VALUE_SEARCH_RETURN_TYPE CmpFindValueByNameFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PUNICODE_STRING Name, OUT PPCM_CACHED_VALUE * ContainingList, OUT ULONG * Index, OUT PCM_KEY_VALUE * Value, OUT BOOLEAN * ValueCached, OUT PHCELL_INDEX CellToRelease)
Definition at line 307 of file cmtree.c.
References ASSERT, ASSERT_KCB_LOCKED, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_EXCEPTION, CMP_GET_CACHED_ADDRESS, CmpCompareCompressedName(), CmpComputeHashKey(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpIsKCBLockedExclusive, _CACHED_CHILD_LIST::Count, DBG, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, Hive, HvReleaseCell, _UNICODE_STRING::Length, List, _UNICODE_STRING::MaximumLength, NULL, RtlCompareUnicodeString(), SearchFail, SearchSuccess, TRUE, and VALUE_COMP_NAME.
Referenced by CmpCompareNewValueDataAgainstKCBCache(), and CmQueryValueKey().
VALUE_SEARCH_RETURN_TYPE CmpGetValueDataFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PPCM_CACHED_VALUE ContainingList, IN PCELL_DATA ValueKey, IN BOOLEAN ValueCached, OUT PUCHAR * DataPointer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
Definition at line 521 of file cmtree.c.
References ASSERT, ASSERT_KCB_LOCKED, CM_CACHE_DATA_CACHED, CM_CACHE_DATA_NOT_CACHED, CM_CACHE_DATA_TOO_BIG, CM_KEY_VALUE_BIG, CM_KEY_VALUE_SPECIAL_SIZE, CMP_GET_CACHED_ADDRESS, CMP_MARK_CELL_CACHED, CmpGetValueData(), CmpIsKCBLockedExclusive, CmpMakeSpecialPoolReadOnly, CmpMakeSpecialPoolReadWrite, CmpTryConvertKCBLockSharedToExclusive(), _CM_CACHED_VALUE::DataCacheType, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, _CM_CACHED_VALUE::HashKey, HCELL_NIL, Hive, HvGetCell, _CM_CACHED_VALUE::KeyValue, MAXIMUM_CACHED_DATA, NULL, PagedPool, RtlCopyMemory, SearchFail, SearchNeedExclusiveLock, SearchSuccess, and _CM_CACHED_VALUE::ValueKeySize.
Referenced by CmpCompareNewValueDataAgainstKCBCache(), and CmpQueryKeyValueData().
VALUE_SEARCH_RETURN_TYPE CmpGetValueKeyFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, IN PCELL_DATA List, IN ULONG Index, OUT PPCM_CACHED_VALUE * ContainingList, OUT PCM_KEY_VALUE * Value, IN BOOLEAN IndexCached, OUT BOOLEAN * ValueCached, OUT PHCELL_INDEX CellToRelease)
Definition at line 154 of file cmtree.c.
References _UNICODE_STRING::Buffer, CM_CACHE_DATA_NOT_CACHED, CMP_GET_CACHED_ADDRESS, CMP_GET_CACHED_KEYVALUE, CMP_IS_CELL_CACHED, CMP_MARK_CELL_CACHED, CmpComputeHashKey(), CmpComputeHashKeyForCompressedName(), CmpIsKCBLockedExclusive, CmpMakeSpecialPoolReadOnly, CmpMakeSpecialPoolReadWrite, CmpTryConvertKCBLockSharedToExclusive(), _CM_CACHED_VALUE::DataCacheType, DBG, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, _CM_CACHED_VALUE::HashKey, HCELL_NIL, Hive, HvGetCell, HvGetCellSize(), Index, _CM_CACHED_VALUE::KeyValue, _UNICODE_STRING::Length, NULL, PagedPool, RtlCopyMemory, SearchFail, SearchNeedExclusiveLock, SearchSuccess, TRUE, VALUE_COMP_NAME, and _CM_CACHED_VALUE::ValueKeySize.
Referenced by CmEnumerateValueKey(), and CmpFindValueByNameFromCache().
VALUE_SEARCH_RETURN_TYPE CmpGetValueListFromCache (IN PCM_KEY_CONTROL_BLOCK KeyControlBlock, OUT PCELL_DATA * List, OUT BOOLEAN * IndexCached, OUT PHCELL_INDEX ValueListToRelease)
Definition at line 31 of file cmtree.c.
References ASSERT_KCB_LOCKED, _CM_CACHED_VALUE_INDEX::CellIndex, CMP_GET_CACHED_CELL_INDEX, CMP_GET_CACHED_CELLDATA, CMP_IS_CELL_CACHED, CMP_MARK_CELL_CACHED, CmpIsKCBLockedExclusive, CmpMakeSpecialPoolReadOnly, CmpTryConvertKCBLockSharedToExclusive(), _CACHED_CHILD_LIST::Count, _CM_CACHED_VALUE_INDEX::Data, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, HCELL_NIL, Hive, HvGetCell, _CM_CACHED_VALUE_INDEX::List, NULL, PagedPool, SearchFail, SearchNeedExclusiveLock, SearchSuccess, TRUE, and _CACHED_CHILD_LIST::ValueList.
Referenced by CmEnumerateValueKey(), and CmpFindValueByNameFromCache().