Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/lpc.h File Reference
lpc.h File Reference
Data Structures
struct _LPCP_CONNECTION_MESSAGE
struct _LPCP_MESSAGE
struct _LPCP_NONPAGED_PORT_QUEUE
struct _LPCP_PORT_OBJECT
struct _LPCP_PORT_QUEUE
struct _LPCP_PORT_ZONE
Macros
#define CLIENT_COMMUNICATION_PORT 0x00000004
#define LPCP_ZONE_ALIGNMENT 16
#define LPCP_ZONE_ALIGNMENT_MASK ~(LPCP_ZONE_ALIGNMENT-1)
#define LPCP_ZONE_MAX_POOL_USAGE (8*PAGE_SIZE)
#define PORT_DYNAMIC_SECURITY 0x80000000
#define PORT_NAME_DELETED 0x40000000
#define PORT_TYPE 0x0000000F
#define PORT_WAITABLE 0x20000000
#define SERVER_COMMUNICATION_PORT 0x00000003
#define SERVER_CONNECTION_PORT 0x00000001
#define UNCONNECTED_COMMUNICATION_PORT 0x00000002
Typedefs
typedef struct _LPCP_CONNECTION_MESSAGE LPCP_CONNECTION_MESSAGE
typedef struct _LPCP_MESSAGE LPCP_MESSAGE
typedef struct _LPCP_NONPAGED_PORT_QUEUE LPCP_NONPAGED_PORT_QUEUE
typedef struct _LPCP_PORT_OBJECT LPCP_PORT_OBJECT
typedef struct _LPCP_PORT_QUEUE LPCP_PORT_QUEUE
typedef struct _LPCP_PORT_ZONE LPCP_PORT_ZONE
typedef struct _LPCP_CONNECTION_MESSAGE * PLPCP_CONNECTION_MESSAGE
typedef struct _LPCP_MESSAGE * PLPCP_MESSAGE
typedef struct _LPCP_NONPAGED_PORT_QUEUE * PLPCP_NONPAGED_PORT_QUEUE
typedef struct _LPCP_PORT_OBJECT * PLPCP_PORT_OBJECT
typedef struct _LPCP_PORT_QUEUE * PLPCP_PORT_QUEUE
typedef struct _LPCP_PORT_ZONE * PLPCP_PORT_ZONE
Functions
NTKERNELAPI NTSTATUS LpcDisconnectPort (IN PVOID Port)
VOID LpcDumpThread (PETHREAD Thread, IN POB_DUMP_CONTROL Control OPTIONAL)
VOID LpcExitThread (PETHREAD Thread)
BOOLEAN LpcInitSystem (VOID)
NTKERNELAPI NTSTATUS LpcRequestPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage)
NTKERNELAPI NTSTATUS LpcRequestWaitReplyPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
NTKERNELAPI NTSTATUS LpcRequestWaitReplyPortEx (IN PVOID PortAddress, IN PPORT_MESSAGE RequestMessage, OUT PPORT_MESSAGE ReplyMessage)
Variables
ULONG LpcCallBackOperationCount
ULONG LpcCallOperationCount
ULONG LpcDatagramOperationCount
Macro Definition Documentation
#define CLIENT_COMMUNICATION_PORT 0x00000004
Definition at line 149 of file lpc.h.
Referenced by LpcpDeletePort(), LpcpFreePortClientSecurity(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyWaitReceivePortEx(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define LPCP_ZONE_ALIGNMENT 16
Definition at line 98 of file lpc.h.
Referenced by LpcInitSystem().
#define LPCP_ZONE_ALIGNMENT_MASK ~(LPCP_ZONE_ALIGNMENT-1)
Definition at line 99 of file lpc.h.
Referenced by LpcInitSystem().
#define LPCP_ZONE_MAX_POOL_USAGE (8*PAGE_SIZE)
Definition at line 105 of file lpc.h.
#define PORT_DYNAMIC_SECURITY 0x80000000
Definition at line 152 of file lpc.h.
Referenced by LpcpFreePortClientSecurity(), NtImpersonateClientOfPort(), and NtSecureConnectPort().
#define PORT_NAME_DELETED 0x40000000
Definition at line 151 of file lpc.h.
Referenced by LpcpDestroyPortQueue(), LpcpRequestWaitReplyPort(), and NtSecureConnectPort().
#define PORT_TYPE 0x0000000F
Definition at line 145 of file lpc.h.
Referenced by LpcpClosePort(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFindDataInfoMessage(), LpcpFreeDataInfoMessage(), LpcpFreePortClientSecurity(), LpcpRequestWaitReplyPort(), LpcpSaveDataInfoMessage(), LpcpValidateClientPort(), LpcRequestPort(), NtCompleteConnectPort(), NtImpersonateClientOfPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define PORT_WAITABLE 0x20000000
Definition at line 150 of file lpc.h.
Referenced by LpcpCreatePort(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyWaitReceivePortEx(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define SERVER_COMMUNICATION_PORT 0x00000003
Definition at line 148 of file lpc.h.
Referenced by LpcpDeletePort(), LpcpRequestWaitReplyPort(), LpcpValidateClientPort(), LpcRequestPort(), NtAcceptConnectPort(), NtCompleteConnectPort(), NtImpersonateClientOfPort(), NtRequestPort(), and NtRequestWaitReplyPort().
#define SERVER_CONNECTION_PORT 0x00000001
Definition at line 146 of file lpc.h.
Referenced by LpcpClosePort(), LpcpCreatePort(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define UNCONNECTED_COMMUNICATION_PORT 0x00000002
Definition at line 147 of file lpc.h.
Referenced by LpcpCreatePort(), LpcpDestroyPortQueue(), LpcpFindDataInfoMessage(), LpcpFreeDataInfoMessage(), and LpcpSaveDataInfoMessage().
Typedef Documentation
typedef struct _LPCP_CONNECTION_MESSAGE LPCP_CONNECTION_MESSAGE
typedef struct _LPCP_MESSAGE LPCP_MESSAGE
typedef struct _LPCP_NONPAGED_PORT_QUEUE LPCP_NONPAGED_PORT_QUEUE
typedef struct _LPCP_PORT_OBJECT LPCP_PORT_OBJECT
typedef struct _LPCP_PORT_QUEUE LPCP_PORT_QUEUE
typedef struct _LPCP_PORT_ZONE LPCP_PORT_ZONE
typedef struct _LPCP_CONNECTION_MESSAGE * PLPCP_CONNECTION_MESSAGE
typedef struct _LPCP_MESSAGE * PLPCP_MESSAGE
typedef struct _LPCP_NONPAGED_PORT_QUEUE * PLPCP_NONPAGED_PORT_QUEUE
typedef struct _LPCP_PORT_OBJECT * PLPCP_PORT_OBJECT
typedef struct _LPCP_PORT_QUEUE * PLPCP_PORT_QUEUE
typedef struct _LPCP_PORT_ZONE * PLPCP_PORT_ZONE
Function Documentation
NTKERNELAPI NTSTATUS LpcDisconnectPort (IN PVOID Port)
Definition at line 310 of file lpcqueue.c.
References FALSE, LpcpDestroyPortQueue(), and STATUS_SUCCESS.
Referenced by PspFreezeProcessWorker().
VOID LpcDumpThread (PETHREAD Thread, IN POB_DUMP_CONTROL Control OPTIONAL)
VOID LpcExitThread (PETHREAD Thread)
Definition at line 355 of file lpcclose.c.
References ASSERT, _LPCP_MESSAGE::Entry, IsListEmpty, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLockByThread, LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, NULL, ObDereferenceObject(), PsGetCurrentThread(), RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, and TRUE.
Referenced by PspExitThread().
BOOLEAN LpcInitSystem (VOID)
Definition at line 89 of file lpcinit.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, FALSE, FIELD_OFFSET, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, LPCP_ZONE_ALIGNMENT, LPCP_ZONE_ALIGNMENT_MASK, LpcpClosePort(), LpcpDeletePort(), LpcpInitializeLpcpLock, LpcpInitializePortZone(), LpcpInitilizeLogging, LpcpPortMapping, _OBJECT_TYPE_INITIALIZER::MaintainTypeList, NonPagedPool, NULL, ObCreateObjectType(), OBJ_VALID_ATTRIBUTES, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, PORT_ALL_ACCESS, PORT_MAXIMUM_MESSAGE_LENGTH, PORT_VALID_OBJECT_ATTRIBUTES, RtlInitUnicodeString(), RtlZeroMemory, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by Phase1InitializationDiscard().
NTKERNELAPI NTSTATUS LpcRequestPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage)
Definition at line 1261 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_MESSAGE::Entry, FALSE, _LPCP_PORT_OBJECT::Flags, InsertTailList(), KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), LPC_CLIENT_DIED, LPC_DATAGRAM, LPC_KERNELMODE_MESSAGE, LPC_RELEASE_WAIT_INCREMENT, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateMessageId, LpcpMoveMessage(), LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyMessageId, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PsGetCurrentProcess(), PsGetCurrentThread(), _LPCP_PORT_QUEUE::ReceiveHead, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_SUCCESS, _ETHREAD::Tcb, _PORT_MESSAGE::u2, and _LPCP_PORT_OBJECT::WaitEvent.
Referenced by LpcpDeletePort(), PspExitThread(), and WmipCsrClientMessageServer().
NTKERNELAPI NTSTATUS LpcRequestWaitReplyPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
Definition at line 2076 of file lpcsend.c.
References KernelMode, and LpcpRequestWaitReplyPort().
Referenced by IopSendMessageToTrackService().
NTKERNELAPI NTSTATUS LpcRequestWaitReplyPortEx (IN PVOID PortAddress, IN PPORT_MESSAGE RequestMessage, OUT PPORT_MESSAGE ReplyMessage)
Definition at line 2091 of file lpcsend.c.
References KeGetPreviousMode, and LpcpRequestWaitReplyPort().
Referenced by DbgkpSendApiMessageLpc(), and ExpRaiseHardError().
Variable Documentation
ULONG LpcCallBackOperationCount
ULONG LpcCallOperationCount
ULONG LpcDatagramOperationCount