Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntxcapi.h File Reference
ntxcapi.h File Reference
#include "pshpack4.h"
#include "poppack.h"
Data Structures
struct _EXCEPTION_POINTERS
struct _EXCEPTION_RECORD
struct _EXCEPTION_RECORD32
struct _EXCEPTION_RECORD64
struct _FP_128
struct _FP_32
struct _FP_64
struct _FP_80
struct _FP_IEEE_RECORD
struct _FP_IEEE_VALUE
Macros
#define EXCEPTION_COLLIDED_UNWIND 0x40
#define EXCEPTION_EXIT_UNWIND 0x4
#define EXCEPTION_MAXIMUM_PARAMETERS 15
#define EXCEPTION_NESTED_CALL 0x10
#define EXCEPTION_NONCONTINUABLE 0x1
#define EXCEPTION_STACK_INVALID 0x8
#define EXCEPTION_TARGET_UNWIND 0x20
#define EXCEPTION_UNWIND
#define EXCEPTION_UNWINDING 0x2
#define IS_DISPATCHING(Flag) ((Flag & EXCEPTION_UNWIND) == 0)
#define IS_TARGET_UNWIND(Flag) (Flag & EXCEPTION_TARGET_UNWIND)
#define IS_UNWINDING(Flag) ((Flag & EXCEPTION_UNWIND) != 0)
Typedefs
typedef struct _EXCEPTION_POINTERS EXCEPTION_POINTERS
typedef struct _EXCEPTION_RECORD EXCEPTION_RECORD
typedef struct _EXCEPTION_RECORD32 EXCEPTION_RECORD32
typedef struct _EXCEPTION_RECORD64 EXCEPTION_RECORD64
typedef struct _FP_128 FP_128
typedef struct _FP_32 FP_32
typedef struct _FP_64 FP_64
typedef struct _FP_80 FP_80
typedef enum _FP_IEEE_COMPARE_RESULT FP_IEEE_COMPARE_RESULT
typedef enum _FP__IEEE_FORMAT FP_IEEE_FORMAT
typedef struct _FP_IEEE_RECORD FP_IEEE_RECORD
typedef enum _FP__IEEE_ROUNDING_MODE FP_IEEE_ROUNDING_MODE
typedef struct _FP_IEEE_VALUE FP_IEEE_VALUE
typedef enum _FP_IEEE_OPERATION_CODE FP_OPERATION_CODE
typedef struct _EXCEPTION_POINTERS * PEXCEPTION_POINTERS
typedef EXCEPTION_RECORD * PEXCEPTION_RECORD
typedef struct _EXCEPTION_RECORD32 * PEXCEPTION_RECORD32
typedef struct _EXCEPTION_RECORD64 * PEXCEPTION_RECORD64
typedef struct _FP_128 * PFP_128
typedef struct _FP_32 * PFP_32
typedef struct _FP_64 * PFP_64
typedef struct _FP_80 * PFP_80
typedef struct _FP_IEEE_RECORD * PFP_IEEE_RECORD
typedef struct _FP_IEEE_VALUE * PFP_IEEE_VALUE
Enumerations
enum _FP__IEEE_FORMAT {
FpFormatFp32, FpFormatFp64, FpFormatFp80, FpFormatFp128,
FpFormatI16, FpFormatI32, FpFormatI64, FpFormatU16,
FpFormatU32, FpFormatU64, FpFormatCompare, FpFormatString
}
enum _FP__IEEE_ROUNDING_MODE { FpRoundNearest, FpRoundMinusInfinity, FpRoundPlusInfinity, FpRoundChopped }
enum _FP_IEEE_COMPARE_RESULT { FpCompareEqual, FpCompareGreater, FpCompareLess, FpCompareUnordered }
enum _FP_IEEE_OPERATION_CODE {
FpCodeUnspecified, FpCodeAdd, FpCodeSubtract, FpCodeMultiply,
FpCodeDivide, FpCodeSquareRoot, FpCodeRemainder, FpCodeCompare,
FpCodeConvert, FpCodeRound, FpCodeTruncate, FpCodeFloor,
FpCodeCeil, FpCodeAcos, FpCodeAsin, FpCodeAtan,
FpCodeAtan2, FpCodeCabs, FpCodeCos, FpCodeCosh,
FpCodeExp, FpCodeFabs, FpCodeFmod, FpCodeFrexp,
FpCodeHypot, FpCodeLdexp, FpCodeLog, FpCodeLog10,
FpCodeModf, FpCodePow, FpCodeSin, FpCodeSinh,
FpCodeTan, FpCodeTanh, FpCodeY0, FpCodeY1,
FpCodeYn
}
Functions
NTSYSCALLAPI NTSTATUS NTAPI NtContinue (__in PCONTEXT ContextRecord, __in BOOLEAN TestAlert)
NTSYSCALLAPI NTSTATUS NTAPI NtRaiseException (__in PEXCEPTION_RECORD ExceptionRecord, __in PCONTEXT ContextRecord, __in BOOLEAN FirstChance)
NTSYSAPI BOOLEAN NTAPI RtlDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord)
NTSYSAPI VOID NTAPI RtlRaiseException (IN PEXCEPTION_RECORD)
NTSYSAPI DECLSPEC_NORETURN VOID NTAPI RtlRaiseStatus (IN NTSTATUS Status)
NTSYSAPI VOID NTAPI RtlUnwind (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue)
Macro Definition Documentation
#define EXCEPTION_COLLIDED_UNWIND 0x40
Definition at line 46 of file ntxcapi.h.
Referenced by RtlUnwindEx().
#define EXCEPTION_EXIT_UNWIND 0x4
Definition at line 42 of file ntxcapi.h.
Referenced by RtlUnwind(), and RtlUnwindEx().
#define EXCEPTION_MAXIMUM_PARAMETERS 15
Definition at line 61 of file ntxcapi.h.
Referenced by ExceptionRecord32To64(), ExceptionRecord64To32(), KiDispatchException(), and KiRaiseException().
#define EXCEPTION_NESTED_CALL 0x10
Definition at line 44 of file ntxcapi.h.
Referenced by RtlDispatchException().
#define EXCEPTION_NONCONTINUABLE 0x1
Definition at line 37 of file ntxcapi.h.
Referenced by RtlDispatchException(), RtlRaiseStatus(), and RtlUnwind().
#define EXCEPTION_STACK_INVALID 0x8
Definition at line 43 of file ntxcapi.h.
Referenced by RtlDispatchException().
#define EXCEPTION_TARGET_UNWIND 0x20
Definition at line 45 of file ntxcapi.h.
Referenced by RtlUnwindEx().
#define EXCEPTION_UNWIND
Value:
(EXCEPTION_UNWINDING | EXCEPTION_EXIT_UNWIND | \
                          EXCEPTION_TARGET_UNWIND | EXCEPTION_COLLIDED_UNWIND)
Definition at line 48 of file ntxcapi.h.
#define EXCEPTION_UNWINDING 0x2
Definition at line 41 of file ntxcapi.h.
Referenced by RtlUnwind(), and RtlUnwindEx().
#define IS_DISPATCHING (Flag) ((Flag & EXCEPTION_UNWIND) == 0)
Definition at line 52 of file ntxcapi.h.
#define IS_TARGET_UNWIND (Flag) (Flag & EXCEPTION_TARGET_UNWIND)
Definition at line 53 of file ntxcapi.h.
#define IS_UNWINDING (Flag) ((Flag & EXCEPTION_UNWIND) != 0)
Definition at line 51 of file ntxcapi.h.
Typedef Documentation
typedef struct _EXCEPTION_POINTERS EXCEPTION_POINTERS
typedef struct _EXCEPTION_RECORD EXCEPTION_RECORD
typedef struct _EXCEPTION_RECORD32 EXCEPTION_RECORD32
typedef struct _EXCEPTION_RECORD64 EXCEPTION_RECORD64
typedef struct _FP_128 FP_128
typedef struct _FP_32 FP_32
typedef struct _FP_64 FP_64
typedef struct _FP_80 FP_80
typedef enum _FP_IEEE_COMPARE_RESULT FP_IEEE_COMPARE_RESULT
typedef enum _FP__IEEE_FORMAT FP_IEEE_FORMAT
typedef struct _FP_IEEE_RECORD FP_IEEE_RECORD
typedef enum _FP__IEEE_ROUNDING_MODE FP_IEEE_ROUNDING_MODE
typedef struct _FP_IEEE_VALUE FP_IEEE_VALUE
typedef enum _FP_IEEE_OPERATION_CODE FP_OPERATION_CODE
typedef struct _EXCEPTION_POINTERS * PEXCEPTION_POINTERS
typedef EXCEPTION_RECORD* PEXCEPTION_RECORD
Definition at line 76 of file ntxcapi.h.
typedef struct _EXCEPTION_RECORD32 * PEXCEPTION_RECORD32
typedef struct _EXCEPTION_RECORD64 * PEXCEPTION_RECORD64
typedef struct _FP_128 * PFP_128
typedef struct _FP_32 * PFP_32
typedef struct _FP_64 * PFP_64
typedef struct _FP_80 * PFP_80
typedef struct _FP_IEEE_RECORD * PFP_IEEE_RECORD
typedef struct _FP_IEEE_VALUE * PFP_IEEE_VALUE
Enumeration Type Documentation
enum _FP__IEEE_FORMAT
Enumerator
FpFormatFp32
FpFormatFp64
FpFormatFp80
FpFormatFp128
FpFormatI16
FpFormatI32
FpFormatI64
FpFormatU16
FpFormatU32
FpFormatU64
FpFormatCompare
FpFormatString
Definition at line 146 of file ntxcapi.h.
enum _FP__IEEE_ROUNDING_MODE
Enumerator
FpRoundNearest
FpRoundMinusInfinity
FpRoundPlusInfinity
FpRoundChopped
Definition at line 209 of file ntxcapi.h.
enum _FP_IEEE_COMPARE_RESULT
Enumerator
FpCompareEqual
FpCompareGreater
FpCompareLess
FpCompareUnordered
Definition at line 135 of file ntxcapi.h.
enum _FP_IEEE_OPERATION_CODE
Enumerator
FpCodeUnspecified
FpCodeAdd
FpCodeSubtract
FpCodeMultiply
FpCodeDivide
FpCodeSquareRoot
FpCodeRemainder
FpCodeCompare
FpCodeConvert
FpCodeRound
FpCodeTruncate
FpCodeFloor
FpCodeCeil
FpCodeAcos
FpCodeAsin
FpCodeAtan
FpCodeAtan2
FpCodeCabs
FpCodeCos
FpCodeCosh
FpCodeExp
FpCodeFabs
FpCodeFmod
FpCodeFrexp
FpCodeHypot
FpCodeLdexp
FpCodeLog
FpCodeLog10
FpCodeModf
FpCodePow
FpCodeSin
FpCodeSinh
FpCodeTan
FpCodeTanh
FpCodeY0
FpCodeY1
FpCodeYn
Definition at line 165 of file ntxcapi.h.
Function Documentation
NTSYSCALLAPI NTSTATUS NTAPI NtContinue (__in PCONTEXT ContextRecord, __in BOOLEAN TestAlert)
NTSYSCALLAPI NTSTATUS NTAPI NtRaiseException (__in PEXCEPTION_RECORD ExceptionRecord, __in PCONTEXT ContextRecord, __in BOOLEAN FirstChance)
NTSYSAPI BOOLEAN NTAPI RtlDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord)
Definition at line 114 of file exdsptch.c.
References _DISPATCHER_CONTEXT::ContextRecord, _DISPATCHER_CONTEXT::ControlPc, _UNWIND_HISTORY_TABLE::Count, DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, _KPRCB::DpcStack, _DISPATCHER_CONTEXT::EstablisherFrame, EXCEPTION_CHAIN_END, EXCEPTION_NESTED_CALL, EXCEPTION_NONCONTINUABLE, EXCEPTION_STACK_INVALID, _EXCEPTION_RECORD::ExceptionCode, ExceptionCollidedUnwind, ExceptionContinueExecution, ExceptionContinueSearch, _EXCEPTION_RECORD::ExceptionFlags, ExceptionNestedException, _EXCEPTION_RECORD::ExceptionRecord, FALSE, FLG_ENABLE_EXCEPTION_LOGGING, _DISPATCHER_CONTEXT::FunctionEntry, _EXCEPTION_REGISTRATION_RECORD::Handler, _DISPATCHER_CONTEXT::HandlerData, _UNWIND_HISTORY_TABLE::HighAddress, _DISPATCHER_CONTEXT::HistoryTable, _DISPATCHER_CONTEXT::ImageBase, Index, KeGetCurrentIrql(), KeGetCurrentPrcb(), KERNEL_STACK_SIZE, _DISPATCHER_CONTEXT::LanguageHandler, _UNWIND_HISTORY_TABLE::LowAddress, NtGlobalFlag, NULL, _EXCEPTION_RECORD::NumberParameters, RtlIsValidHandler(), RtlLookupFunctionEntry(), RtlpCopyContext(), RtlpExecuteHandlerForException(), RtlpGetRegistrationHead(), RtlpGetStackLimits(), RtlpIsFrameInBounds(), RtlpLogExceptionHandler(), RtlpLogLastExceptionDisposition(), RtlRaiseException(), RtlRaiseStatus(), RtlVirtualUnwind(), _DISPATCHER_CONTEXT::ScopeIndex, _UNWIND_HISTORY_TABLE::Search, STATUS_INVALID_DISPOSITION, STATUS_NONCONTINUABLE_EXCEPTION, TRUE, UNW_FLAG_EHANDLER, and UNWIND_HISTORY_TABLE_NONE.
Referenced by KiDispatchException(), RtlRaiseException(), and RtlRaiseStatus().
NTSYSAPI VOID NTAPI RtlRaiseException (IN PEXCEPTION_RECORD)
Definition at line 24 of file raise.c.
References FALSE, NULL, RtlCaptureContext(), RtlDispatchException(), RtlLookupFunctionEntry(), RtlRaiseStatus(), RtlVirtualUnwind(), Status, STATUS_INVALID_DISPOSITION, UNW_FLAG_NHANDLER, and ZwRaiseException().
Referenced by RtlDispatchException(), and RtlUnwind().
NTSYSAPI DECLSPEC_NORETURN VOID NTAPI RtlRaiseStatus (IN NTSTATUS Status)
Definition at line 98 of file raise.c.
References EXCEPTION_NONCONTINUABLE, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionFlags, _EXCEPTION_RECORD::ExceptionRecord, FALSE, NULL, _EXCEPTION_RECORD::NumberParameters, RtlCaptureContext(), RtlDispatchException(), Status, and ZwRaiseException().
Referenced by InitializeSListHead(), RtlDispatchException(), RtlInitializeContext(), RtlLargeIntegerDivide(), RtlRaiseException(), and RtlUnwindEx().
NTSYSAPI VOID NTAPI RtlUnwind (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue)
Definition at line 445 of file exdsptch.c.
References ARGUMENT_PRESENT, CONTEXT_CONTROL, CONTEXT_INTEGER, CONTEXT_SEGMENTS, _CONTEXT::ContextFlags, DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, _KPRCB::DpcStack, _CONTEXT::Eax, _CONTEXT::Esp, EXCEPTION_CHAIN_END, EXCEPTION_EXIT_UNWIND, EXCEPTION_NONCONTINUABLE, EXCEPTION_UNWINDING, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, ExceptionCollidedUnwind, ExceptionContinueSearch, _EXCEPTION_RECORD::ExceptionFlags, _EXCEPTION_RECORD::ExceptionRecord, FALSE, KeGetCurrentIrql(), KeGetCurrentPrcb(), KERNEL_STACK_SIZE, _EXCEPTION_REGISTRATION_RECORD::Next, NULL, _EXCEPTION_RECORD::NumberParameters, RtlpCaptureContext(), RtlpExecuteHandlerForUnwind(), RtlpGetRegistrationHead(), RtlpGetStackLimits(), RtlpUnlinkHandler(), RtlRaiseException(), RtlUnwindEx(), STATUS_BAD_STACK, STATUS_INVALID_DISPOSITION, STATUS_INVALID_UNWIND_TARGET, STATUS_UNWIND, TRUE, ZwContinue(), and ZwRaiseException().