Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/queryvm.c File Reference
queryvm.c File Reference
#include "mi.h"
Functions
NTSTATUS MiGetWorkingSetInfo (IN PMEMORY_WORKING_SET_INFORMATION WorkingSetInfo, IN SIZE_T Length, IN PEPROCESS Process)
NTSTATUS MiGetWorkingSetInfoList (__in PMEMORY_WORKING_SET_EX_INFORMATION WorkingSetInfo, __in SIZE_T Length, __in PEPROCESS Process)
NTSTATUS MiGetWorkingSetInfoList (IN PMEMORY_WORKING_SET_EX_INFORMATION WorkingSetInfo, IN SIZE_T Length, IN PEPROCESS Process)
ULONG MiQueryAddressState (IN PVOID Va, IN PMMVAD Vad, IN PEPROCESS TargetProcess, OUT PULONG ReturnedProtect, OUT PVOID *NextVaToQuery)
NTSTATUS NtQueryVirtualMemory (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in MEMORY_INFORMATION_CLASS MemoryInformationClass, __out_bcount(MemoryInformationLength) PVOID MemoryInformation, __in SIZE_T MemoryInformationLength, __out_opt PSIZE_T ReturnLength)
Variables
POBJECT_TYPE IoFileObjectType
Function Documentation
NTSTATUS MiGetWorkingSetInfo (IN PMEMORY_WORKING_SET_INFORMATION WorkingSetInfo, IN SIZE_T Length, IN PEPROCESS Process)
Definition at line 1185 of file queryvm.c.
References ASSERT, BYTES_TO_PAGES, _MMPFN::e1, _MMWSLE::e1, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _MMPTE::Hard, IoWriteAccess, KeGetPreviousModeByThread, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_WS_SHARED, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_PFN_ELEMENT, MiGetPteAddress, MM_ZERO_ACCESS, MmGetSystemAddressForMdlSafe, MmInitializeMdl, MmProbeAndLockPages(), MmUnlockPages(), MmWorkingSetList, MmWsle, _MEMORY_WORKING_SET_BLOCK::Node, NonPagedPool, NormalPagePriority, NT_SUCCESS, NULL, _MEMORY_WORKING_SET_INFORMATION::NumberOfEntries, _MMPFN::OriginalPte, _MMPFNENTRY::PageColor, _MMPTE_HARDWARE::PageFrameNumber, _MEMORY_WORKING_SET_BLOCK::Protection, _MMWSLENTRY::Protection, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MEMORY_WORKING_SET_BLOCK::ShareCount, _MMPFN::ShareCount, _MEMORY_WORKING_SET_BLOCK::Shared, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_WS_SHARED, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MEMORY_WORKING_SET_BLOCK::VirtualPage, _MMWSLENTRY::VirtualPageNumber, and _MEMORY_WORKING_SET_INFORMATION::WorkingSetInfo.
Referenced by NtQueryVirtualMemory().
NTSTATUS MiGetWorkingSetInfoList (__in PMEMORY_WORKING_SET_EX_INFORMATION WorkingSetInfo, __in SIZE_T Length, __in PEPROCESS Process)
Referenced by NtQueryVirtualMemory().
NTSTATUS MiGetWorkingSetInfoList (IN PMEMORY_WORKING_SET_EX_INFORMATION WorkingSetInfo, IN SIZE_T Length, IN PEPROCESS Process)
Definition at line 1343 of file queryvm.c.
References _MI_PAGING_LEVELS, ASSERT, _MMPFN::AweAllocation, BYTES_TO_PAGES, _MMPFN::e1, _MMWSLE::e1, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _MMPTE::Hard, IoWriteAccess, KeGetPreviousModeByThread, KeStackAttachProcess(), KeUnstackDetachProcess(), _MEMORY_WORKING_SET_EX_BLOCK::LargePage, LOCK_WS_SHARED, _MEMORY_WORKING_SET_EX_BLOCK::Locked, _MEMORY_WORKING_SET_EX_INFORMATION::Long, _MMPTE::Long, MI_CONVERT_FROM_PTE_PROTECTION, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PFN_PRIORITY, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_IS_PFN(), MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_OWNER_USER, MI_VA_TO_VPN, MiFindNodeOrParent(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiLocateAddress(), MiLocateWsle(), MM_HIGHEST_USER_ADDRESS, MM_ZERO_ACCESS, MmGetSystemAddressForMdlSafe, MmInitializeMdl, MmProbeAndLockPages(), MmUnlockPages(), MmWorkingSetList, MmWsle, _MEMORY_WORKING_SET_EX_BLOCK::Node, NonPagedPool, NormalPagePriority, NULL, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, PAGE_NOACCESS, PAGE_READONLY, PAGE_READWRITE, _MMPFNENTRY::PageColor, _MEMORY_WORKING_SET_EX_BLOCK::Priority, _MMWSLENTRY::Protection, _MMVAD_FLAGS::Protection, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), SATISFY_OVERZEALOUS_COMPILER, _MEMORY_WORKING_SET_EX_BLOCK::ShareCount, _MMPFN::ShareCount, _MEMORY_WORKING_SET_EX_BLOCK::Shared, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MEMORY_WORKING_SET_EX_INFORMATION::u1, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_WS_SHARED, _MI_PHYSICAL_VIEW::Vad, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePageSection, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MEMORY_WORKING_SET_EX_BLOCK::Valid, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MEMORY_WORKING_SET_EX_INFORMATION::VirtualAddress, _MEMORY_WORKING_SET_EX_INFORMATION::VirtualAttributes, _MEMORY_WORKING_SET_EX_BLOCK::Win32Protection, _MMPTE_HARDWARE::Write, and _MMPFN::WsIndex.
ULONG MiQueryAddressState (IN PVOID Va, IN PMMVAD Vad, IN PEPROCESS TargetProcess, OUT PULONG ReturnedProtect, OUT PVOID * NextVaToQuery)
Definition at line 794 of file queryvm.c.
References ASSERT, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_PFN, LOCK_WS_SHARED, _MMPTE::Long, MEM_COMMIT, MEM_RESERVE, MI_CONVERT_FROM_PTE_PROTECTION, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_VA_TO_VPN, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiGetPageProtection(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteDecommittedPage(), MiMakeSystemAddressValidPfn(), MM_NOIRQL, NOTHING, NULL, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, PAGE_NOACCESS, PAGE_READONLY, PAGE_READWRITE, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS_SHARED, VadAwe, VadDevicePhysicalMemory, VadImageMap, VadRotatePhysical, _MMPTE_SOFTWARE::Valid, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by MiCheckForUserStackOverflow(), MiClearStackGuardBits(), and NtQueryVirtualMemory().
NTSTATUS NtQueryVirtualMemory (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in MEMORY_INFORMATION_CLASS MemoryInformationClass, __out_bcount(MemoryInformationLength) PVOID MemoryInformation, __in SIZE_T MemoryInformationLength, __out_opt PSIZE_T ReturnLength)
Definition at line 39 of file queryvm.c.
References _2gb, _4gb, _MEMORY_BASIC_INFORMATION::AllocationBase, _MEMORY_BASIC_INFORMATION::AllocationProtect, ARGUMENT_PRESENT, ASSERT, _MM_AVL_TABLE::BalancedRoot, _MEMORY_BASIC_INFORMATION::BaseAddress, _MMVAD::ControlArea, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CONTROL_AREA::FilePointer, _EPROCESS::Flags, KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), _MMVAD::LeftChild, LOCK_ADDRESS_SPACE, LOCK_WS_SHARED, MEM_COMMIT, MEM_FREE, MEM_IMAGE, MEM_MAPPED, MEM_PRIVATE, MEM_RESERVE, MemoryBasicInformation, MemoryMappedFilenameInformation, MemoryWorkingSetExInformation, MI_CONVERT_FROM_PTE_PROTECTION, MI_VA_TO_VPN, MI_VPN_TO_VA, MiGetNextVad, MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiQueryAddressState(), MM_HIGHEST_USER_ADDRESS, MM_HIGHEST_VAD_ADDRESS, MM_SHARED_USER_DATA_VA, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, _MM_AVL_TABLE::NumberGenericTableElements, ObDereferenceObject(), ObQueryNameString(), ObReferenceObject, ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_NOACCESS, PAGE_READONLY, PAGE_SIZE, _EPROCESS::Pcb, _MMVAD_FLAGS::PrivateMemory, ProbeForWrite(), ProbeForWriteUlong_ptr, PROCESS_QUERY_INFORMATION, _MEMORY_BASIC_INFORMATION::Protect, _MMVAD_FLAGS::Protection, PS_PROCESS_FLAGS_VM_DELETED, PS_PROCESS_FLAGS_WOW64_4GB_VA_SPACE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _MEMORY_BASIC_INFORMATION::RegionSize, _MMADDRESS_NODE::RightChild, _MMVAD::RightChild, _MMVAD::StartingVpn, _MEMORY_BASIC_INFORMATION::State, Status, STATUS_FILE_INVALID, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_ADDRESS, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_5, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MEMORY_BASIC_INFORMATION::Type, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_SHARED, _MMVAD::VadFlags, VadImageMap, _EPROCESS::VadRoot, VadRotatePhysical, _MMVAD_FLAGS::VadType, and X64K.
Variable Documentation
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.