Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/pat.c File Reference
pat.c File Reference
#include "ki.h"
#include "pat.h"
#include "mtrr.h"
Data Structures
struct _NEW_PAT
Macros
#define DBGMSG(a)
Typedefs
typedef struct _NEW_PAT NEW_PAT
typedef struct _NEW_PAT * PNEW_PAT
Functions
VOID KeRestorePAT (VOID)
VOID KiInitializePAT (VOID)
VOID KiLoadPAT (IN PNEW_PAT Context)
VOID KiLoadPATTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID Context, IN PVOID Parameter2, IN PVOID Parameter3)
Macro Definition Documentation
#define DBGMSG (a)
Definition at line 32 of file pat.c.
Typedef Documentation
typedef struct _NEW_PAT NEW_PAT
typedef struct _NEW_PAT * PNEW_PAT
Function Documentation
VOID KeRestorePAT (VOID)
Definition at line 90 of file pat.c.
References KeFeatureBits, KF_PAT, and KiInitializePAT().
Referenced by KeRestoreProcessorSpecificFeatures().
VOID KiInitializePAT (VOID)
Definition at line 115 of file pat.c.
References ASSERT, _NEW_PAT::Attributes, HIGH_LEVEL, _PAT::hw, KeAcquireSpinLock, KeActiveProcessors, KeFeatureBits, KeGetCurrentPrcb(), KeRaiseIrql, KeReleaseSpinLock(), KF_PAT, KiIpiSendSynchronousPacket, KiIpiStallOnPacketTargets(), KiLoadPAT(), KiLoadPATTarget(), KiReverseStallIpiLock, MmEnablePAT(), NULL, _KPRCB::Number, _PAT::Pat, PAT_TYPE_STRONG_UC, PAT_TYPE_USWC, PAT_TYPE_WB, PAT_TYPE_WEAK_UC, _PROCESSOR_LOCKSTEP::Processor, _KPRCB::ReverseStall, _KPRCB::SetMember, _NEW_PAT::Synchronize, _PROCESSOR_LOCKSTEP::TargetCount, and _PROCESSOR_LOCKSTEP::TargetPhase.
Referenced by KeRestorePAT(), and KiInitMachineDependent().
VOID KiLoadPAT (IN PNEW_PAT Context)
Definition at line 290 of file pat.c.
References CR0_CD, CR0_NW, CR4_PGE, KeDisableInterrupts(), KeEnableInterrupts(), KiLockStepExecution(), PAT_MSR, and WRMSR().
Referenced by KiInitializePAT(), and KiLoadPATTarget().
VOID KiLoadPATTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID Context, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 246 of file pat.c.
References KiIpiSignalPacketDoneAndStall(), KiLoadPAT(), _NEW_PAT::Synchronize, _PROCESSOR_LOCKSTEP::TargetPhase, and UNREFERENCED_PARAMETER.
Referenced by KiInitializePAT().