Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/intrlk.h File Reference
intrlk.h File Reference
Functions
FORCEINLINE PSINGLE_LIST_ENTRY InterlockedFlushSingleList (IN PSINGLE_LIST_ENTRY ListHead)
FORCEINLINE PSINGLE_LIST_ENTRY InterlockedPopEntrySingleList (IN PSINGLE_LIST_ENTRY ListHead)
FORCEINLINE PSINGLE_LIST_ENTRY InterlockedPushEntrySingleList (IN PSINGLE_LIST_ENTRY ListHead, IN PSINGLE_LIST_ENTRY Entry)
Function Documentation
FORCEINLINE PSINGLE_LIST_ENTRY InterlockedFlushSingleList (IN PSINGLE_LIST_ENTRY ListHead)
Definition at line 122 of file intrlk.h.
References InterlockedExchangePointer, and NULL.
Referenced by KeSwapProcessOrStack().
FORCEINLINE PSINGLE_LIST_ENTRY InterlockedPopEntrySingleList (IN PSINGLE_LIST_ENTRY ListHead)
Definition at line 32 of file intrlk.h.
References InterlockedCompareExchangePointer, _SINGLE_LIST_ENTRY::Next, and NULL.
FORCEINLINE PSINGLE_LIST_ENTRY InterlockedPushEntrySingleList (IN PSINGLE_LIST_ENTRY ListHead, IN PSINGLE_LIST_ENTRY Entry)
Definition at line 77 of file intrlk.h.
References InterlockedCompareExchangePointer, and _SINGLE_LIST_ENTRY::Next.
Referenced by KeDetachProcess(), KeTerminateThread(), KeUnstackDetachProcess(), KiAttachProcess(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), and KiReadyThread().