Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/tracedb.c File Reference
tracedb.c File Reference
#include <nt.h>
#include <ntrtl.h>
#include <nturtl.h>
#include <ntos.h>
#include "tracedbp.h"
Macros
#define RTL_TRACE_BLOCK_MAGIC 0xABCDAAAA
#define RTL_TRACE_DATABASE_MAGIC 0xABCDCCCC
#define RTL_TRACE_SEGMENT_MAGIC 0xABCDBBBB
#define RTL_TRACE_SIZE_INCREMENT PAGE_SIZE
#define TRACE_ASSERT(Expr)
Functions
BOOLEAN RtlpTraceDatabaseAcquireLock (IN PRTL_TRACE_DATABASE Database)
PVOID RtlpTraceDatabaseAllocate (IN SIZE_T Size, IN ULONG Flags, IN ULONG Tag)
BOOLEAN RtlpTraceDatabaseFree (PVOID Block, IN ULONG Tag)
BOOLEAN RtlpTraceDatabaseInitializeLock (IN PRTL_TRACE_DATABASE Database)
BOOLEAN RtlpTraceDatabaseInternalAdd (IN PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID *Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
BOOLEAN RtlpTraceDatabaseInternalFind (PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID *Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
BOOLEAN RtlpTraceDatabaseReleaseLock (IN PRTL_TRACE_DATABASE Database)
BOOLEAN RtlpTraceDatabaseUninitializeLock (IN PRTL_TRACE_DATABASE Database)
PRTL_TRACE_SEGMENT RtlpTraceSegmentCreate (IN SIZE_T Size, IN ULONG Flags, IN ULONG Tag)
ULONG RtlpTraceStandardHashFunction (IN ULONG Count, IN PVOID *Trace)
BOOLEAN RtlTraceDatabaseAdd (IN PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID *Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
PRTL_TRACE_DATABASE RtlTraceDatabaseCreate (IN ULONG Buckets, IN SIZE_T MaximumSize OPTIONAL, IN ULONG Flags, IN ULONG Tag, IN RTL_TRACE_HASH_FUNCTION HashFunction OPTIONAL)
BOOLEAN RtlTraceDatabaseDestroy (IN PRTL_TRACE_DATABASE Database)
BOOLEAN RtlTraceDatabaseEnumerate (PRTL_TRACE_DATABASE Database, OUT PRTL_TRACE_ENUMERATE Enumerate, OUT PRTL_TRACE_BLOCK *TraceBlock)
BOOLEAN RtlTraceDatabaseFind (PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID *Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
VOID RtlTraceDatabaseLock (IN PRTL_TRACE_DATABASE Database)
VOID RtlTraceDatabaseUnlock (IN PRTL_TRACE_DATABASE Database)
BOOLEAN RtlTraceDatabaseValidate (IN PRTL_TRACE_DATABASE Database)
Macro Definition Documentation
#define RTL_TRACE_BLOCK_MAGIC 0xABCDAAAA
Definition at line 47 of file tracedb.c.
Referenced by RtlpTraceDatabaseInternalAdd(), and RtlTraceDatabaseValidate().
#define RTL_TRACE_DATABASE_MAGIC 0xABCDCCCC
Definition at line 49 of file tracedb.c.
Referenced by RtlTraceDatabaseAdd(), RtlTraceDatabaseCreate(), RtlTraceDatabaseDestroy(), RtlTraceDatabaseEnumerate(), RtlTraceDatabaseFind(), and RtlTraceDatabaseValidate().
#define RTL_TRACE_SEGMENT_MAGIC 0xABCDBBBB
Definition at line 48 of file tracedb.c.
Referenced by RtlpTraceDatabaseInternalAdd(), RtlTraceDatabaseCreate(), and RtlTraceDatabaseValidate().
#define RTL_TRACE_SIZE_INCREMENT PAGE_SIZE
Definition at line 56 of file tracedb.c.
Referenced by RtlpTraceDatabaseInternalAdd(), and RtlTraceDatabaseCreate().
#define TRACE_ASSERT (Expr)
Definition at line 39 of file tracedb.c.
Referenced by RtlTraceDatabaseAdd(), RtlTraceDatabaseDestroy(), RtlTraceDatabaseEnumerate(), RtlTraceDatabaseFind(), and RtlTraceDatabaseValidate().
Function Documentation
BOOLEAN RtlpTraceDatabaseAcquireLock (IN PRTL_TRACE_DATABASE Database)
Definition at line 1097 of file tracedb.c.
References ASSERT, ExAcquireFastMutex(), KeAcquireSpinLock, KeGetCurrentThread(), RTL_TRACE_IN_KERNEL_MODE, RTL_TRACE_USE_NONPAGED_POOL, and TRUE.
Referenced by RtlTraceDatabaseAdd(), RtlTraceDatabaseEnumerate(), RtlTraceDatabaseFind(), RtlTraceDatabaseLock(), and RtlTraceDatabaseValidate().
PVOID RtlpTraceDatabaseAllocate (IN SIZE_T Size, IN ULONG Flags, IN ULONG Tag)
Definition at line 875 of file tracedb.c.
References ExAllocatePoolWithTag, NonPagedPool, PagedPool, and RTL_TRACE_USE_NONPAGED_POOL.
Referenced by RtlpTraceSegmentCreate(), and RtlTraceDatabaseCreate().
BOOLEAN RtlpTraceDatabaseFree (PVOID Block, IN ULONG Tag)
Definition at line 915 of file tracedb.c.
References ExFreePoolWithTag, and TRUE.
Referenced by RtlTraceDatabaseCreate(), and RtlTraceDatabaseDestroy().
BOOLEAN RtlpTraceDatabaseInitializeLock (IN PRTL_TRACE_DATABASE Database)
Definition at line 948 of file tracedb.c.
References ASSERT, ExInitializeFastMutex, KeInitializeSpinLock(), RTL_TRACE_IN_KERNEL_MODE, RTL_TRACE_USE_NONPAGED_POOL, and TRUE.
Referenced by RtlTraceDatabaseCreate().
BOOLEAN RtlpTraceDatabaseInternalAdd (IN PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID * Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
Definition at line 554 of file tracedb.c.
References Count, _RTL_TRACE_BLOCK::Count, _RTL_TRACE_SEGMENT::Database, DbgPrint(), FALSE, _RTL_TRACE_SEGMENT::Magic, _RTL_TRACE_BLOCK::Magic, _RTL_TRACE_BLOCK::Next, _RTL_TRACE_SEGMENT::NextSegment, NULL, RequestSize, RTL_TRACE_BLOCK_MAGIC, RTL_TRACE_SEGMENT_MAGIC, RTL_TRACE_SIZE_INCREMENT, RtlMoveMemory, RtlpTraceDatabaseInternalFind(), RtlpTraceSegmentCreate(), _RTL_TRACE_SEGMENT::SegmentEnd, _RTL_TRACE_SEGMENT::SegmentFree, _RTL_TRACE_SEGMENT::SegmentStart, _RTL_TRACE_BLOCK::Size, _RTL_TRACE_SEGMENT::TotalSize, _RTL_TRACE_BLOCK::Trace, TRUE, _RTL_TRACE_BLOCK::UserCount, and _RTL_TRACE_BLOCK::UserSize.
Referenced by RtlTraceDatabaseAdd().
BOOLEAN RtlpTraceDatabaseInternalFind (PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID * Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
Definition at line 734 of file tracedb.c.
References _RTL_TRACE_DATABASE::Buckets, Count, FALSE, _RTL_TRACE_DATABASE::HashCounter, _RTL_TRACE_DATABASE::HashFunction, Index, _RTL_TRACE_BLOCK::Next, _RTL_TRACE_DATABASE::NoOfBuckets, NULL, RequestSize, _RTL_TRACE_BLOCK::Size, _RTL_TRACE_BLOCK::Trace, and TRUE.
Referenced by RtlpTraceDatabaseInternalAdd(), and RtlTraceDatabaseFind().
BOOLEAN RtlpTraceDatabaseReleaseLock (IN PRTL_TRACE_DATABASE Database)
Definition at line 1135 of file tracedb.c.
References ASSERT, ExReleaseFastMutex(), KeReleaseSpinLock(), NULL, RTL_TRACE_IN_KERNEL_MODE, RTL_TRACE_USE_NONPAGED_POOL, and TRUE.
Referenced by RtlTraceDatabaseAdd(), RtlTraceDatabaseEnumerate(), RtlTraceDatabaseFind(), RtlTraceDatabaseUnlock(), and RtlTraceDatabaseValidate().
BOOLEAN RtlpTraceDatabaseUninitializeLock (IN PRTL_TRACE_DATABASE Database)
Definition at line 986 of file tracedb.c.
References ASSERT, RTL_TRACE_IN_KERNEL_MODE, RTL_TRACE_USE_NONPAGED_POOL, and TRUE.
Referenced by RtlTraceDatabaseDestroy().
PRTL_TRACE_SEGMENT RtlpTraceSegmentCreate (IN SIZE_T Size, IN ULONG Flags, IN ULONG Tag)
Definition at line 1173 of file tracedb.c.
References RtlpTraceDatabaseAllocate().
Referenced by RtlpTraceDatabaseInternalAdd().
ULONG RtlpTraceStandardHashFunction (IN ULONG Count, IN PVOID * Trace)
Definition at line 831 of file tracedb.c.
References Index, and PtrToUlong.
Referenced by RtlTraceDatabaseCreate().
BOOLEAN RtlTraceDatabaseAdd (IN PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID * Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
Definition at line 433 of file tracedb.c.
References RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseInternalAdd(), RtlpTraceDatabaseReleaseLock(), and TRACE_ASSERT.
PRTL_TRACE_DATABASE RtlTraceDatabaseCreate (IN ULONG Buckets, IN SIZE_T MaximumSize OPTIONAL, IN ULONG Flags, IN ULONG Tag, IN RTL_TRACE_HASH_FUNCTION HashFunction OPTIONAL)
Definition at line 129 of file tracedb.c.
References _RTL_TRACE_DATABASE::Buckets, _RTL_TRACE_DATABASE::CurrentSize, _RTL_TRACE_SEGMENT::Database, _RTL_TRACE_DATABASE::Flags, _RTL_TRACE_DATABASE::HashCounter, _RTL_TRACE_DATABASE::HashFunction, _RTL_TRACE_SEGMENT::Magic, _RTL_TRACE_DATABASE::Magic, _RTL_TRACE_DATABASE::MaximumSize, _RTL_TRACE_SEGMENT::NextSegment, _RTL_TRACE_DATABASE::NoOfBuckets, _RTL_TRACE_DATABASE::NoOfHits, _RTL_TRACE_DATABASE::NoOfTraces, NULL, _RTL_TRACE_DATABASE::Owner, RTL_TRACE_DATABASE_MAGIC, RTL_TRACE_IN_KERNEL_MODE, RTL_TRACE_SEGMENT_MAGIC, RTL_TRACE_SIZE_INCREMENT, RTL_TRACE_USE_NONPAGED_POOL, RtlpTraceDatabaseAllocate(), RtlpTraceDatabaseFree(), RtlpTraceDatabaseInitializeLock(), RtlpTraceStandardHashFunction(), RtlZeroMemory, _RTL_TRACE_SEGMENT::SegmentEnd, _RTL_TRACE_SEGMENT::SegmentFree, _RTL_TRACE_DATABASE::SegmentList, _RTL_TRACE_SEGMENT::SegmentStart, _RTL_TRACE_DATABASE::Tag, Tag, and _RTL_TRACE_SEGMENT::TotalSize.
BOOLEAN RtlTraceDatabaseDestroy (IN PRTL_TRACE_DATABASE Database)
Definition at line 272 of file tracedb.c.
References DbgPrint(), FALSE, _RTL_TRACE_SEGMENT::NextSegment, NULL, RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseFree(), RtlpTraceDatabaseUninitializeLock(), RtlTraceDatabaseValidate(), TRACE_ASSERT, and TRUE.
BOOLEAN RtlTraceDatabaseEnumerate (PRTL_TRACE_DATABASE Database, OUT PRTL_TRACE_ENUMERATE Enumerate, OUT PRTL_TRACE_BLOCK * TraceBlock)
Definition at line 1212 of file tracedb.c.
References _RTL_TRACE_DATABASE::Buckets, FALSE, _RTL_TRACE_DATABASE::Magic, _RTL_TRACE_DATABASE::NoOfBuckets, NULL, RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseReleaseLock(), TRACE_ASSERT, and TRUE.
BOOLEAN RtlTraceDatabaseFind (PRTL_TRACE_DATABASE Database, IN ULONG Count, IN PVOID * Trace, OUT PRTL_TRACE_BLOCK *TraceBlock OPTIONAL)
Definition at line 492 of file tracedb.c.
References _RTL_TRACE_DATABASE::Magic, _RTL_TRACE_DATABASE::NoOfHits, RTL_TRACE_DATABASE_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseInternalFind(), RtlpTraceDatabaseReleaseLock(), and TRACE_ASSERT.
VOID RtlTraceDatabaseLock (IN PRTL_TRACE_DATABASE Database)
Definition at line 1031 of file tracedb.c.
References RtlpTraceDatabaseAcquireLock().
VOID RtlTraceDatabaseUnlock (IN PRTL_TRACE_DATABASE Database)
Definition at line 1064 of file tracedb.c.
References RtlpTraceDatabaseReleaseLock().
BOOLEAN RtlTraceDatabaseValidate (IN PRTL_TRACE_DATABASE Database)
Definition at line 369 of file tracedb.c.
References Index, _RTL_TRACE_SEGMENT::Magic, _RTL_TRACE_BLOCK::Magic, _RTL_TRACE_BLOCK::Next, _RTL_TRACE_SEGMENT::NextSegment, NULL, RTL_TRACE_BLOCK_MAGIC, RTL_TRACE_DATABASE_MAGIC, RTL_TRACE_SEGMENT_MAGIC, RtlpTraceDatabaseAcquireLock(), RtlpTraceDatabaseReleaseLock(), TRACE_ASSERT, and TRUE.
Referenced by RtlTraceDatabaseDestroy().