Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/cancelapi.c File Reference
cancelapi.c File Reference
#include "iomgr.h"
Macros
#define CSQLIB_DDI(x) x
Functions
NTSTATUS CSQLIB_DDI() IoCsqInitialize (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
NTSTATUS CSQLIB_DDI() IoCsqInitializeEx (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP_EX CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
VOID CSQLIB_DDI() IoCsqInsertIrp (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context)
NTSTATUS CSQLIB_DDI() IoCsqInsertIrpEx (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context, IN PVOID InsertContext)
PIRP CSQLIB_DDI() IoCsqRemoveIrp (IN PIO_CSQ Csq, IN PIO_CSQ_IRP_CONTEXT Context)
PIRP CSQLIB_DDI() IoCsqRemoveNextIrp (IN PIO_CSQ Csq, IN PVOID PeekContext)
VOID IopCsqCancelRoutine (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Macro Definition Documentation
#define CSQLIB_DDI (x) x
Definition at line 32 of file cancelapi.c.
Referenced by IoCsqInsertIrp().
Function Documentation
NTSTATUS CSQLIB_DDI() IoCsqInitialize (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
Definition at line 110 of file cancelapi.c.
References IO_TYPE_CSQ, NULL, and STATUS_SUCCESS.
NTSTATUS CSQLIB_DDI() IoCsqInitializeEx (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP_EX CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
Definition at line 150 of file cancelapi.c.
References IO_TYPE_CSQ_EX, NULL, and STATUS_SUCCESS.
VOID CSQLIB_DDI() IoCsqInsertIrp (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context)
Definition at line 460 of file cancelapi.c.
References CSQLIB_DDI, IoCsqInsertIrpEx(), NULL, and VOID.
NTSTATUS CSQLIB_DDI() IoCsqInsertIrpEx (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context, IN PVOID InsertContext)
Definition at line 190 of file cancelapi.c.
References ASSERT, IO_TYPE_CSQ_EX, IO_TYPE_CSQ_IRP_CONTEXT, IoMarkIrpPending, IopCsqCancelRoutine(), IoSetCancelRoutine, NT_SUCCESS, NULL, and STATUS_SUCCESS.
Referenced by IoCsqInsertIrp().
PIRP CSQLIB_DDI() IoCsqRemoveIrp (IN PIO_CSQ Csq, IN PIO_CSQ_IRP_CONTEXT Context)
Definition at line 389 of file cancelapi.c.
References ASSERT, IoSetCancelRoutine, NULL, and PIRP.
PIRP CSQLIB_DDI() IoCsqRemoveNextIrp (IN PIO_CSQ Csq, IN PVOID PeekContext)
Definition at line 314 of file cancelapi.c.
References ASSERT, _IO_CSQ_IRP_CONTEXT::Csq, IO_TYPE_CSQ_IRP_CONTEXT, IoSetCancelRoutine, _IO_CSQ_IRP_CONTEXT::Irp, NULL, PIRP, and _IO_CSQ_IRP_CONTEXT::Type.
VOID IopCsqCancelRoutine (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 37 of file cancelapi.c.
References ASSERT, _IO_CSQ_IRP_CONTEXT::Csq, _IO_CSQ::CsqAcquireLock, _IO_CSQ::CsqRemoveIrp, IO_TYPE_CSQ, IO_TYPE_CSQ_EX, IO_TYPE_CSQ_IRP_CONTEXT, IoReleaseCancelSpinLock(), _IO_CSQ_IRP_CONTEXT::Irp, NULL, _IO_CSQ::ReservePointer, _IO_CSQ_IRP_CONTEXT::Type, and UNREFERENCED_PARAMETER.
Referenced by IoCsqInsertIrpEx().