Windows Research Kernel v1.2: C:/Windows Research Kernel/se/capture.c File Reference
capture.c File Reference
#include "pch.h"
Macros
#define LongAligned(ptr) (LongAlignPtr(ptr) == (ptr))
#define SEP_USHORT_OVERFLOW ((ULONG) ((USHORT) -1))
Functions
NTSTATUS SeCaptureAcl (__in PACL InputAcl, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(*AlignedAclSize) PACL *CapturedAcl, __out PULONG AlignedAclSize)
NTSTATUS SeCaptureAuditPolicy (__in PTOKEN_AUDIT_POLICY Policy, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in_opt ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PTOKEN_AUDIT_POLICY *CapturedPolicy)
NTSTATUS SeCaptureLuidAndAttributesArray (__in_ecount(ArrayCount) PLUID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(*AlignedArraySize) PLUID_AND_ATTRIBUTES *CapturedArray, __out PULONG AlignedArraySize)
NTSTATUS SeCaptureSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSECURITY_DESCRIPTOR *OutputSecurityDescriptor)
NTSTATUS SeCaptureSecurityQos (__in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE RequestorMode, __out PBOOLEAN SecurityQosPresent, __out PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
NTSTATUS SeCaptureSid (__in PSID InputSid, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSID *CapturedSid)
NTSTATUS SeCaptureSidAndAttributesArray (__in_ecount(ArrayCount) PSID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(AlignedArraySize) PSID_AND_ATTRIBUTES *CapturedArray, __out PULONG AlignedArraySize)
NTSTATUS SeComputeQuotaInformationSize (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __out PULONG Size)
VOID SeFreeCapturedSecurityQos (__in PVOID SecurityQos)
NTSTATUS SepCopyProxyData (OUT PSECURITY_TOKEN_PROXY_DATA *DestProxyData, IN PSECURITY_TOKEN_PROXY_DATA SourceProxyData)
VOID SepFreeProxyData (IN PSECURITY_TOKEN_PROXY_DATA ProxyData)
NTSTATUS SepProbeAndCaptureQosData (IN PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
VOID SeReleaseAcl (__in PACL CapturedAcl, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseAuditPolicy (__in PTOKEN_AUDIT_POLICY CapturedPolicy, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseLuidAndAttributesArray (__in PLUID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseSecurityDescriptor (__in PSECURITY_DESCRIPTOR CapturedSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseSid (__in PSID CapturedSid, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
VOID SeReleaseSidAndAttributesArray (__in PSID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
BOOLEAN SeValidSecurityDescriptor (__in ULONG Length, __in_bcount(Length) PSECURITY_DESCRIPTOR SecurityDescriptor)
Macro Definition Documentation
#define LongAligned (ptr) (LongAlignPtr(ptr) == (ptr))
Definition at line 44 of file capture.c.
Referenced by SeValidSecurityDescriptor().
#define SEP_USHORT_OVERFLOW ((ULONG) ((USHORT) -1))
Referenced by SeCaptureSecurityDescriptor().
Function Documentation
NTSTATUS SeCaptureAcl (__in PACL InputAcl, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full *AlignedAclSize PACL * CapturedAcl, __out PULONG AlignedAclSize)
Definition at line 1362 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, LongAlignSize, NULL, PAGED_CODE, ProbeAndReadUshort, ProbeForRead, RtlCopyMemory, SepCheckAcl(), STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_ACL, and STATUS_SUCCESS.
Referenced by NtCreateToken(), and NtSetInformationToken().
NTSTATUS SeCaptureAuditPolicy (__in PTOKEN_AUDIT_POLICY Policy, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in_opt ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PTOKEN_AUDIT_POLICY * CapturedPolicy)
Definition at line 2336 of file capture.c.
References ARGUMENT_PRESENT, ASSERT, DbgPrint(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, NULL, PAGED_CODE, PER_USER_AUDITING_POLICY_SIZE_BY_COUNT, ProbeAndReadLong, ProbeForRead, RtlCopyMemory, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and VALID_TOKEN_AUDIT_POLICY_ELEMENT.
NTSTATUS SeCaptureLuidAndAttributesArray (__in_ecount(ArrayCount) PLUID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full *AlignedArraySize PLUID_AND_ATTRIBUTES * CapturedArray, __out PULONG AlignedArraySize)
Definition at line 1599 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, LongAlignSize, NULL, PAGED_CODE, ProbeForRead, RtlCopyMemory, SEP_MAX_PRIVILEGE_COUNT, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtAdjustPrivilegesToken(), NtCreateToken(), NtFilterToken(), NtPrivilegeCheck(), and PspCaptureTokenFilter().
NTSTATUS SeCaptureSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSECURITY_DESCRIPTOR * OutputSecurityDescriptor)
Definition at line 47 of file capture.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, _SECURITY_DESCRIPTOR::Dacl, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseDatatypeMisalignment(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR::Group, KernelMode, LongAlignSize, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, _SECURITY_DESCRIPTOR::Owner, PAGED_CODE, ProbeAndReadUchar, ProbeAndReadUshort, ProbeForRead, ProbeForReadSmallStructure, _SECURITY_DESCRIPTOR::Revision, RtlCopyMemory, RtlLengthRequiredSid(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlValidSid(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, _SECURITY_DESCRIPTOR::Sacl, SE_DACL_PRESENT, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SEP_USHORT_OVERFLOW, SepCheckAcl(), STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_ACL, STATUS_INVALID_SID, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by NtOpenObjectAuditAlarm(), NtSetSecurityObject(), ObpCaptureObjectCreateInformation(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
NTSTATUS SeCaptureSecurityQos (__in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE RequestorMode, __out PBOOLEAN SecurityQosPresent, __out PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
Definition at line 946 of file capture.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, _SECURITY_QUALITY_OF_SERVICE::Length, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::Length, NT_SUCCESS, NULL, PAGED_CODE, ProbeForReadSmallStructure, RtlCopyMemory, SepFreeProxyData(), SepProbeAndCaptureQosData(), Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by NtCreateToken(), and NtDuplicateToken().
NTSTATUS SeCaptureSid (__in PSID InputSid, __in KPROCESSOR_MODE RequestorMode, __inout_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out PSID * CapturedSid)
Definition at line 1134 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, NULL, PAGED_CODE, ProbeAndReadUchar, ProbeForRead, RtlCopyMemory, RtlLengthRequiredSid(), RtlValidSid(), STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_SID, and STATUS_SUCCESS.
Referenced by NtCreateToken(), NtSecureConnectPort(), NtSetInformationToken(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
NTSTATUS SeCaptureSidAndAttributesArray (__in_ecount(ArrayCount) PSID_AND_ATTRIBUTES InputArray, __in ULONG ArrayCount, __in KPROCESSOR_MODE RequestorMode, __in_bcount_opt(CaptureBufferLength) PVOID CaptureBuffer, __in ULONG CaptureBufferLength, __in POOL_TYPE PoolType, __in BOOLEAN ForceCapture, __deref_out_bcount_full(AlignedArraySize) PSID_AND_ATTRIBUTES * CapturedArray, __out PULONG AlignedArraySize)
Definition at line 1840 of file capture.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, KernelMode, LongAlignSize, NT_SUCCESS, NULL, PAGED_CODE, ProbeAndReadUchar, ProbeForRead, RtlCopyMemory, RtlLengthRequiredSid(), RtlLengthSid(), RtlValidSid(), SEP_MAX_GROUP_COUNT, _SID_AND_ATTRIBUTES::Sid, SID_MAX_SUB_AUTHORITIES, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_INVALID_SID, and STATUS_SUCCESS.
Referenced by NtAdjustGroupsToken(), NtCreateToken(), NtFilterToken(), and PspCaptureTokenFilter().
NTSTATUS SeComputeQuotaInformationSize (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __out PULONG Size)
Definition at line 2576 of file capture.c.
References _ACL::AclSize, Group, LongAlignSize, NULL, PAGED_CODE, _SECURITY_DESCRIPTOR::Revision, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by ObpCaptureObjectCreateInformation().
VOID SeFreeCapturedSecurityQos (__in PVOID SecurityQos)
Definition at line 904 of file capture.c.
References _SECURITY_ADVANCED_QUALITY_OF_SERVICE::AuditData, ExFreePool(), _SECURITY_ADVANCED_QUALITY_OF_SERVICE::Length, NULL, PAGED_CODE, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::ProxyData, and SepFreeProxyData().
Referenced by NtCreateToken(), and NtDuplicateToken().
NTSTATUS SepCopyProxyData (OUT PSECURITY_TOKEN_PROXY_DATA * DestProxyData, IN PSECURITY_TOKEN_PROXY_DATA SourceProxyData)
Definition at line 691 of file capture.c.
References ExAllocatePoolWithTag, NULL, PAGED_CODE, PagedPool, PtrAlignSize, RtlCopyUnicodeString(), STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by SepCreateToken(), SepDuplicateToken(), SepFilterToken(), and SepProbeAndCaptureQosData().
VOID SepFreeProxyData (IN PSECURITY_TOKEN_PROXY_DATA ProxyData)
Definition at line 739 of file capture.c.
References ExFreePool(), NULL, and PAGED_CODE.
Referenced by SeCaptureSecurityQos(), SeFreeCapturedSecurityQos(), SepDuplicateToken(), SepFilterToken(), SepProbeAndCaptureQosData(), and SepTokenDeleteMethod().
NTSTATUS SepProbeAndCaptureQosData (IN PSECURITY_ADVANCED_QUALITY_OF_SERVICE CapturedSecurityQos)
Definition at line 768 of file capture.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, ExAllocatePool, ExFreePool(), _UNICODE_STRING::Length, _SECURITY_TOKEN_PROXY_DATA::Length, _SECURITY_TOKEN_AUDIT_DATA::Length, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _SECURITY_TOKEN_PROXY_DATA::PathInfo, ProbeForRead, ProbeForReadSmallStructure, SepCopyProxyData(), SepFreeProxyData(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by SeCaptureSecurityQos().
VOID SeReleaseAcl (__in PACL CapturedAcl, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 1551 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtCreateToken(), and NtSetInformationToken().
VOID SeReleaseAuditPolicy (__in PTOKEN_AUDIT_POLICY CapturedPolicy, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 2529 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtSetInformationToken().
VOID SeReleaseLuidAndAttributesArray (__in PLUID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 1787 of file capture.c.
References ExFreePool(), KernelMode, NULL, PAGED_CODE, TRUE, and UserMode.
Referenced by NtAdjustPrivilegesToken(), NtCreateToken(), NtFilterToken(), and NtPrivilegeCheck().
VOID SeReleaseSecurityDescriptor (__in PSECURITY_DESCRIPTOR CapturedSecurityDescriptor, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 642 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtOpenObjectAuditAlarm(), NtSetSecurityObject(), ObInsertObject(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
VOID SeReleaseSid (__in PSID CapturedSid, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 1312 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtCreateToken(), NtSecureConnectPort(), NtSetInformationToken(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
VOID SeReleaseSidAndAttributesArray (__in PSID_AND_ATTRIBUTES CapturedArray, __in KPROCESSOR_MODE RequestorMode, __in BOOLEAN ForceCapture)
Definition at line 2286 of file capture.c.
References ExFreePool(), KernelMode, PAGED_CODE, TRUE, and UserMode.
Referenced by NtAdjustGroupsToken(), NtCreateToken(), and NtFilterToken().
BOOLEAN SeValidSecurityDescriptor (__in ULONG Length, __in_bcount(Length) PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 2639 of file capture.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, LongAligned, _SECURITY_DESCRIPTOR_RELATIVE::Owner, PAGED_CODE, _SID::Revision, _SECURITY_DESCRIPTOR_RELATIVE::Revision, RtlOffsetToPointer, RtlValidAcl(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SID_MAX_SUB_AUTHORITIES, SID_REVISION, _SID::SubAuthorityCount, and TRUE.
Referenced by CmpRebuildSecurityCache(), CmpValidateHiveSecurityDescriptors(), and WmipSDRegistryQueryRoutine().