Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmparse.c File Reference
cmparse.c File Reference
#include "cmp.h"
Data Structures
struct _CM_HASH_ENTRY
Macros
#define CM_HASH_STACK_SIZE 32
#define CMP_PARSE_GOTO_CREATE 1
#define CMP_PARSE_GOTO_NONE 0
#define CMP_PARSE_GOTO_RETURN 2
#define CMP_PARSE_GOTO_RETURN2 3
#define CmpReleasePreviousAndHookNew(NewHive, NewCell, ReleaseHive, ReleaseCell)
#define CmpStepThroughExit(h, c, n, ReleaseHive, ReleaseCell)
#define MAX_LOCAL_KCB_ARRAY (CM_HASH_STACK_SIZE + 1)
Typedefs
typedef struct _CM_HASH_ENTRY CM_HASH_ENTRY
typedef struct _CM_HASH_ENTRY * PCM_HASH_ENTRY
Functions
C_ASSERT (sizeof(REG_CREATE_KEY_INFORMATION) >=sizeof(REG_OPEN_KEY_INFORMATION))
C_ASSERT (FIELD_OFFSET(REG_CREATE_KEY_INFORMATION, CompleteName)==FIELD_OFFSET(REG_OPEN_KEY_INFORMATION, CompleteName))
C_ASSERT (FIELD_OFFSET(REG_CREATE_KEY_INFORMATION, RootObject)==FIELD_OFFSET(REG_OPEN_KEY_INFORMATION, RootObject))
PCM_KEY_CONTROL_BLOCK CmpAddInfoAfterParseFailure (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node, PCM_KEY_CONTROL_BLOCK kcb, PUNICODE_STRING NodeName)
PULONG CmpBuildAndLockKcbArray (IN PCM_HASH_ENTRY HashStack, IN ULONG TotalLevels, IN ULONG RemainingLevel, IN PCM_KEY_CONTROL_BLOCK kcb, IN PULONG OuterStackArray, IN BOOLEAN LockExclusive)
NTSTATUS CmpBuildHashStackAndLookupCache (PCM_KEY_BODY ParseObject, PCM_KEY_CONTROL_BLOCK *kcb, PUNICODE_STRING Current, PHHIVE *Hive, HCELL_INDEX *Cell, PULONG TotalRemainingSubkeys, PULONG MatchRemainSubkeyLevel, PULONG TotalSubkeys, PULONG OuterStackArray, PULONG *LockedKcbs)
VOID CmpCacheAdd (IN PCM_HASH_ENTRY LastHashEntry, IN ULONG Count)
NTSTATUS CmpCacheLookup (IN PCM_HASH_ENTRY HashStack, IN ULONG TotalRemainingSubkeys, OUT ULONG *MatchRemainSubkeyLevel, IN OUT PCM_KEY_CONTROL_BLOCK *Kcb, OUT PUNICODE_STRING RemainingName, OUT PHHIVE *Hive, OUT HCELL_INDEX *Cell, IN PULONG OuterStackArray)
ULONG CmpComputeHashValue (IN PCM_HASH_ENTRY HashStack, IN OUT ULONG *TotalSubkeys, IN ULONG BaseConvKey, IN PUNICODE_STRING RemainingName)
NTSTATUS CmpCreateLinkNode (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PACCESS_STATE AccessState, IN UNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN PULONG LockedKcbs, OUT PVOID *Object)
NTSTATUS CmpDoOpen (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PCM_KEY_NODE Node, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN PCM_PARSE_CONTEXT Context, IN ULONG ControlFlags, IN OUT PCM_KEY_CONTROL_BLOCK *CachedKcb, IN PUNICODE_STRING KeyName, IN PCMHIVE OriginatingHive OPTIONAL, IN PULONG KcbsLocked, OUT PVOID *Object, OUT PBOOLEAN NeedDeref OPTIONAL)
BOOLEAN CmpGetHiveName (PCMHIVE CmHive, PUNICODE_STRING HiveName)
BOOLEAN CmpGetNextName (IN OUT PUNICODE_STRING RemainingName, OUT PUNICODE_STRING NextName, OUT PBOOLEAN Last)
BOOLEAN CmpGetSymbolicLink (IN PHHIVE Hive, IN OUT PUNICODE_STRING ObjectName, IN OUT PCM_KEY_CONTROL_BLOCK SymbolicKcb, IN PUNICODE_STRING RemainingName)
BOOLEAN CmpOKToFollowLink (IN PCMHIVE OrigHive, IN PCMHIVE DestHive)
NTSTATUS CmpParseKey (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
VOID CmpReLockKcbArray (IN PULONG LockedKcbs, IN BOOLEAN LockExclusive)
ULONG CmpUnLockKcbArray (IN PULONG LockedKcbs, IN ULONG Exempt)
Variables
const ULONG CmpCacheOnFlag = CM_CACHE_FAKE_KEY
PCM_KEY_CONTROL_BLOCK CmpKeyControlBlockRoot
BOOLEAN CmpNoMasterCreates
UNICODE_STRING CmSymbolicLinkValueName
Macro Definition Documentation
#define CM_HASH_STACK_SIZE 32
Definition at line 31 of file cmparse.c.
Referenced by CmpBuildHashStackAndLookupCache(), and CmpComputeHashValue().
#define CMP_PARSE_GOTO_CREATE 1
Definition at line 212 of file cmparse.c.
Referenced by CmpParseKey().
#define CMP_PARSE_GOTO_NONE 0
Definition at line 211 of file cmparse.c.
Referenced by CmpParseKey().
#define CMP_PARSE_GOTO_RETURN 2
Definition at line 213 of file cmparse.c.
Referenced by CmpParseKey().
#define CMP_PARSE_GOTO_RETURN2 3
Definition at line 214 of file cmparse.c.
Referenced by CmpParseKey().
#define CmpReleasePreviousAndHookNew (NewHive, NewCell, ReleaseHive, ReleaseCell)
Value:
if(ReleaseCell != HCELL_NIL) {                                            \
        ASSERT( ReleaseHive != NULL );                                          \
        HvReleaseCell( ReleaseHive,ReleaseCell);                                \
    }                                                                           \
    ReleaseHive = (NewHive);                                                    \
    ReleaseCell = (NewCell)
Definition at line 203 of file cmparse.c.
Referenced by CmpParseKey().
#define CmpStepThroughExit (h, c, n, ReleaseHive, ReleaseCell)
Value:
if ((n)->Flags & KEY_HIVE_EXIT) {                                   \
    if( ReleaseCell != HCELL_NIL ) {                                \
        ASSERT( ReleaseHive != NULL );                              \
        HvReleaseCell( ReleaseHive,ReleaseCell);                    \
    }                                                               \
    (h)=(n)->ChildHiveReference.KeyHive;                            \
    (c)=(n)->ChildHiveReference.KeyCell;                            \
    (n)=(PCM_KEY_NODE)HvGetCell((h),(c));                           \
    if( (n) == NULL ) {                                             \
        ReleaseHive = NULL;                                         \
        ReleaseCell = HCELL_NIL;                                    \
    } else {                                                        \
        ReleaseHive = (h);                                          \
        ReleaseCell = (c);                                          \
    }                                                               \
}
Definition at line 185 of file cmparse.c.
Referenced by CmpParseKey().
#define MAX_LOCAL_KCB_ARRAY (CM_HASH_STACK_SIZE + 1)
Definition at line 32 of file cmparse.c.
Referenced by CmpBuildAndLockKcbArray(), and CmpParseKey().
Typedef Documentation
typedef struct _CM_HASH_ENTRY CM_HASH_ENTRY
typedef struct _CM_HASH_ENTRY * PCM_HASH_ENTRY
Function Documentation
C_ASSERT (sizeof(REG_CREATE_KEY_INFORMATION) >=sizeof(REG_OPEN_KEY_INFORMATION))
C_ASSERT (FIELD_OFFSET(REG_CREATE_KEY_INFORMATION, CompleteName) = =FIELD_OFFSET(REG_OPEN_KEY_INFORMATION, CompleteName))
C_ASSERT (FIELD_OFFSET(REG_CREATE_KEY_INFORMATION, RootObject) = =FIELD_OFFSET(REG_OPEN_KEY_INFORMATION, RootObject))
PCM_KEY_CONTROL_BLOCK CmpAddInfoAfterParseFailure (PHHIVE Hive, HCELL_INDEX Cell, PCM_KEY_NODE Node, PCM_KEY_CONTROL_BLOCK kcb, PUNICODE_STRING NodeName)
Definition at line 2844 of file cmparse.c.
References ASSERT_KCB_LOCKED_EXCLUSIVE, _UNICODE_STRING::Buffer, _CM_INDEX::Cell, CM_CACHE_FAKE_KEY, CM_KCB_INVALID_CACHED_INFO, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_HINT, CM_KCB_SUBKEY_ONE, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CM_MAX_CACHE_HINT_SIZE, CMP_CREATE_KCB_FAKE, CMP_CREATE_KCB_KCB_LOCKED, CmpCacheOnFlag, CmpComputeHashKey(), CmpComputeHashKeyForCompressedName(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), _CM_INDEX_HINT_BLOCK::Count, DBG, ExAllocatePoolWithTag, ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _CM_INDEX_HINT_BLOCK::HashKey, _CM_INDEX::HashKey, _CM_KEY_CONTROL_BLOCK::HashKey, HvGetCell, HvReleaseCell, Index, _CM_KEY_CONTROL_BLOCK::IndexHint, KEY_COMP_NAME, _UNICODE_STRING::Length, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, PagedPool, PROTECTED_POOL, _CM_KEY_INDEX::Signature, Stable, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, UseFastIndex, and Volatile.
Referenced by CmpParseKey().
PULONG CmpBuildAndLockKcbArray (IN PCM_HASH_ENTRY HashStack, IN ULONG TotalLevels, IN ULONG RemainingLevel, IN PCM_KEY_CONTROL_BLOCK kcb, IN PULONG OuterStackArray, IN BOOLEAN LockExclusive)
Definition at line 3245 of file cmparse.c.
References ASSERT, CM_PAGED_CODE, CmpLockHashEntryByIndexExclusive, CmpLockHashEntryByIndexShared, Count, GET_HASH_INDEX, MAX_LOCAL_KCB_ARRAY, and NULL.
Referenced by CmpBuildHashStackAndLookupCache(), and CmpCacheLookup().
NTSTATUS CmpBuildHashStackAndLookupCache (PCM_KEY_BODY ParseObject, PCM_KEY_CONTROL_BLOCK * kcb, PUNICODE_STRING Current, PHHIVE * Hive, HCELL_INDEX * Cell, PULONG TotalRemainingSubkeys, PULONG MatchRemainSubkeyLevel, PULONG TotalSubkeys, PULONG OuterStackArray, PULONG * LockedKcbs)
Definition at line 217 of file cmparse.c.
References ASSERT, ASSERT_KCB_LOCKED, CM_HASH_STACK_SIZE, CmpBuildAndLockKcbArray(), CmpCacheLookup(), CmpComputeHashValue(), CmpLockRegistry(), FALSE, GET_HASH_INDEX, NT_SUCCESS, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_NAME_TOO_LONG, and TRUE.
Referenced by CmpParseKey().
VOID CmpCacheAdd (IN PCM_HASH_ENTRY LastHashEntry, IN ULONG Count)
NTSTATUS CmpCacheLookup (IN PCM_HASH_ENTRY HashStack, IN ULONG TotalRemainingSubkeys, OUT ULONG * MatchRemainSubkeyLevel, IN OUT PCM_KEY_CONTROL_BLOCK * Kcb, OUT PUNICODE_STRING RemainingName, OUT PHHIVE * Hive, OUT HCELL_INDEX * Cell, IN PULONG OuterStackArray)
Definition at line 2512 of file cmparse.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, ASSERT_KEY_HASH, _UNICODE_STRING::Buffer, CM_KCB_KEY_NON_EXIST, CMP_DEST_UP, CmpBuildAndLockKcbArray(), CmpCacheTable, CmpCleanUpKcbCacheWithLock(), CmpCompareCompressedName(), CmpCompareUnicodeString(), CmpDereferenceKeyControlBlock(), CmpHashTableSize, CmpLockKCBShared, CmpReferenceKeyControlBlock(), CmpRemoveFromDelayedClose(), CmpRemoveKeyControlBlock(), CmpUnlockKCB, CmpUnLockKcbArray(), _CM_NAME_CONTROL_BLOCK::Compressed, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_CONTROL_BLOCK::Delete, ExFreePool(), _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, GET_HASH_INDEX, GET_KCB_HASH_ENTRY, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, KeyName, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_NAME_CONTROL_BLOCK::Name, _CM_KEY_CONTROL_BLOCK::NameBlock, _CM_NAME_CONTROL_BLOCK::NameLength, _CM_KEY_HASH::NextHash, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_KEY_CONTROL_BLOCK::RefCount, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, _CM_KEY_CONTROL_BLOCK::TotalLevels, and TRUE.
Referenced by CmpBuildHashStackAndLookupCache().
ULONG CmpComputeHashValue (IN PCM_HASH_ENTRY HashStack, IN OUT ULONG * TotalSubkeys, IN ULONG BaseConvKey, IN PUNICODE_STRING RemainingName)
Definition at line 2394 of file cmparse.c.
References CM_HASH_STACK_SIZE, CmUpcaseUnicodeChar, and OBJ_NAME_PATH_SEPARATOR.
Referenced by CmpBuildHashStackAndLookupCache().
NTSTATUS CmpCreateLinkNode (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PACCESS_STATE AccessState, IN UNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN PULONG LockedKcbs, OUT PVOID * Object)
Definition at line 1661 of file cmparse.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE, ASSERT_KCB, ASSERT_KCB_LOCKED_EXCLUSIVE, Cell, _CM_KEY_NODE::ChildHiveReference, _CM_KEY_NODE::ClassLength, CM_KCB_NO_DELAY_CLOSE, CM_LINK_NODE_SIGNATURE, CmIsKcbReadOnly, CmKdPrintEx, CML_PARSE, CMP_CREATE_KCB_KCB_LOCKED, CmpAddSubKey(), CmpCleanUpSubKeyInfo(), CmpCopyName(), CmpDoCreateChild(), CmpDoOpen(), CmpHKeyNodeSize, CmpLockHiveFlusherShared, CmpMasterHive, CmpParseGetOriginatingPoint, CmpRemoveKeyControlBlock(), CmpUnlockHiveFlusher, CmUpcaseUnicodeChar, _CHILD_LIST::Count, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, _CMHIVE::Hive, HvAllocateCell(), HvFreeCell(), HvGetCell, HvMarkCellDirty(), HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, KeQuerySystemTime(), KEY_COMP_NAME, KEY_HIVE_ENTRY, KEY_HIVE_EXIT, KEY_NO_DELETE, _CM_KEY_REFERENCE::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_REFERENCE::KeyHive, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyNode, _CM_KEY_NODE::LastWriteTime, _CHILD_LIST::List, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NT_SUCCESS, NULL, ObDereferenceObjectDeferDelete(), OBJ_NAME_PATH_SEPARATOR, _CM_KEY_NODE::Parent, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_KEY_NODE::Signature, Stable, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_OBJECT_NAME_NOT_FOUND, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpParseKey().
NTSTATUS CmpDoOpen (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PCM_KEY_NODE Node, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN PCM_PARSE_CONTEXT Context OPTIONAL, IN ULONG ControlFlags, IN OUT PCM_KEY_CONTROL_BLOCK * CachedKcb, IN PUNICODE_STRING KeyName, IN PCMHIVE OriginatingHive OPTIONAL, IN PULONG KcbsLocked, OUT PVOID * Object, OUT PBOOLEAN NeedDeref OPTIONAL)
Definition at line 1318 of file cmparse.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, ASSERT, ASSERT_KCB_LOCKED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_KCB_KEY_NON_EXIST, CM_KCB_SYM_LINK_FOUND, CmKdPrintEx, CML_PARSE, CML_POOL, CMP_CREATE_KCB_KCB_LOCKED, CMP_DO_OPEN_COMPLETE_KEY_CACHED, CMP_ENLIST_KCB_LOCKED_EXCLUSIVE, CMP_ENLIST_KCB_LOCKED_SHARED, CmpCleanUpKcbValueCache(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpHashTableSize, CmpKeyObjectType, CmpLockHashEntryByIndexExclusive, CmpOKToFollowLink(), CmpReferenceKeyControlBlock(), CmpUnlockHashEntryByIndex, CmpUnLockKcbArray(), _CM_KEY_CONTROL_BLOCK::ConvKey, _CACHED_CHILD_LIST::Count, DbgBreakPoint(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, EnlistKeyBodyWithKCB(), _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_CONTROL_BLOCK::Flags, GET_HASH_INDEX, HIVE_IS_UNLOADING, KeGetCurrentThread(), KeGetPreviousMode, KEY_BODY_TYPE, KEY_PREDEF_HANDLE, KEY_READ, KEY_SYM_LINK, KEY_WRITE, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_BODY::NotifyBlock, NT_SUCCESS, NULL, ObCheckObjectAccess(), ObCreateObject, ObDereferenceObjectDeferDelete(), OBJ_OPENLINK, _CM_KEY_BODY::ProcessID, PsGetCurrentProcessId(), _CACHED_CHILD_LIST::RealKcb, REG_OPENED_EXISTING_KEY, REG_OPTION_BACKUP_RESTORE, REG_OPTION_CREATE_LINK, SeBackupPrivilege, SeRestorePrivilege, SeSinglePrivilegeCheck(), STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PREDEFINED_HANDLE, STATUS_REPARSE, STATUS_SUCCESS, TRUE, _CM_KEY_BODY::Type, _CM_KEY_CONTROL_BLOCK::ValueCache, WRITE_DAC, and WRITE_OWNER.
Referenced by CmpCreateLinkNode(), and CmpParseKey().
BOOLEAN CmpGetHiveName (PCMHIVE CmHive, PUNICODE_STRING HiveName)
Definition at line 233 of file cmhvlist.c.
References ASSERT, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, CmpCopyCompressedName(), CmpHKeyNameLen, CmpMasterHive, ExAllocatePool, FALSE, _CM_KEY_NODE::Flags, _CMHIVE::Hive, HvGetCell, HvReleaseCell, KEY_COMP_NAME, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, _CM_KEY_NODE::Parent, _HBASE_BLOCK::RootCell, RtlCopyMemory, TRUE, and wcslen().
Referenced by CmpAddToHiveFileList().
BOOLEAN CmpGetNextName (IN OUT PUNICODE_STRING RemainingName, OUT PUNICODE_STRING NextName, OUT PBOOLEAN Last)
Definition at line 1216 of file cmparse.c.
References FALSE, NULL, OBJ_NAME_PATH_SEPARATOR, REG_MAX_KEY_NAME_LENGTH, TRUE, and UNICODE_NULL.
Referenced by CmpParseKey(), and CmpWalkPath().
BOOLEAN CmpGetSymbolicLink (IN PHHIVE Hive, IN OUT PUNICODE_STRING ObjectName, IN OUT PCM_KEY_CONTROL_BLOCK SymbolicKcb, IN PUNICODE_STRING RemainingName OPTIONAL)
Definition at line 2051 of file cmparse.c.
References ARGUMENT_PRESENT, ASSERT, ASSERT_KCB_LOCKED, _UNICODE_STRING::Buffer, CM_CMHIVE_FLAG_UNTRUSTED, CM_KCB_KEY_NON_EXIST, CM_KCB_SYM_LINK_FOUND, CmKdPrintEx, CML_PARSE, CmpCacheTable, CmpCleanUpKcbValueCache(), CmpConstructName(), CmpDereferenceKeyControlBlockWithLock(), CmpFindValueByName(), CmpGetValueData(), CmpLockKCBExclusive, CmpLockTwoHashEntriesExclusive(), CmpOKToFollowLink(), CmpReferenceKeyControlBlock(), CmpUnlockHashEntry, CmpUnlockKCB, CmpUnlockTwoHashEntries(), CmUpcaseUnicodeChar, CONTAINING_RECORD, _CM_KEY_HASH::ConvKey, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), ExFreePoolWithTag, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, GET_HASH_INDEX, GET_KCB_HASH_ENTRY, HCELL_NIL, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_HASH::NextHash, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, PagedPool, PROTECTED_POOL, REG_LINK, RtlAppendUnicodeStringToString(), RtlCopyMemory, RtlMoveMemory, Status, _CM_KEY_CONTROL_BLOCK::TotalLevels, TRUE, _CM_KEY_VALUE::Type, and UNICODE_NULL.
Referenced by CmpParseKey().
BOOLEAN CmpOKToFollowLink (IN PCMHIVE OrigHive, IN PCMHIVE DestHive)
Definition at line 3155 of file cmparse.c.
References ASSERT, CM_CMHIVE_FLAG_UNTRUSTED, CmpLockHiveListShared, CmpUnlockHiveList, CONTAINING_RECORD, Fail, FALSE, _LIST_ENTRY::Flink, NULL, PAGED_CODE, TRUE, and _CMHIVE::TrustClassEntry.
Referenced by CmpDoCreate(), CmpDoOpen(), and CmpGetSymbolicLink().
NTSTATUS CmpParseKey (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 334 of file cmparse.c.
References ARGUMENT_PRESENT, ASSERT, ASSERT_CM_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, Cell, CM_KCB_CACHE_MASK, CM_KCB_KEY_NON_EXIST, CM_KCB_NO_SUBKEY, CM_KCB_SUBKEY_ONE, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_PARSE, CMP_CREATE_KCB_KCB_LOCKED, CMP_DO_OPEN_COMPLETE_KEY_CACHED, CMP_PARSE_GOTO_CREATE, CMP_PARSE_GOTO_NONE, CMP_PARSE_GOTO_RETURN, CMP_PARSE_GOTO_RETURN2, CmpAddInfoAfterParseFailure(), CmpBuildHashStackAndLookupCache(), CmpCallCallBacks(), CmpComputeHashKey(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDereferenceKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpDoCreate(), CmpDoOpen(), CmpFindSubKeyByName(), CmpGetNextName(), CmpGetSymbolicLink(), CmpHashTableSize, CmpKeyObjectType, CmpMasterHive, CmpNoMasterCreates, CmPostCallbackNotification, CmpParseGetOriginatingPoint, CmpParseRecordOriginatingPoint, CmpReferenceKeyControlBlock(), CmpReleasePreviousAndHookNew, CmpRemoveKeyControlBlock(), CmpStepThroughExit, CmpUnLockKcbArray(), CmpUnlockRegistry(), _REG_CREATE_KEY_INFORMATION::CompleteName, _CM_INDEX_HINT_BLOCK::Count, _CM_PARSE_CONTEXT::CreateLink, DBG, DbgBreakPoint(), _CM_KEY_CONTROL_BLOCK::Delete, _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, END_LOCK_CHECKPOINT, ExFreePool(), _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_CONTROL_BLOCK::Flags, _CM_INDEX_HINT_BLOCK::HashKey, _CM_KEY_CONTROL_BLOCK::HashKey, HCELL_NIL, Hive, _CMHIVE::Hive, HvGetCell, _CM_KEY_CONTROL_BLOCK::IndexHint, KEY_SYM_LINK, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, MAX_LOCAL_KCB_ARRAY, _UNICODE_STRING::MaximumLength, MAXUSHORT, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, REG_CREATED_NEW_KEY, RegNtPostCreateKeyEx, RegNtPostOpenKeyEx, RegNtPreCreateKeyEx, RegNtPreOpenKeyEx, _REG_CREATE_KEY_INFORMATION::RootObject, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NAME_TOO_LONG, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateObjectTypes().
VOID CmpReLockKcbArray (IN PULONG LockedKcbs, IN BOOLEAN LockExclusive)
Definition at line 3427 of file cmparse.c.
References CM_PAGED_CODE, CmpLockHashEntryByIndexExclusive, CmpLockHashEntryByIndexShared, and Count.
ULONG CmpUnLockKcbArray (IN PULONG LockedKcbs, IN ULONG Exempt)
Definition at line 3408 of file cmparse.c.
References CM_PAGED_CODE, CmpUnlockHashEntryByIndex, and Count.
Referenced by CmpCacheLookup(), CmpDoOpen(), and CmpParseKey().
Variable Documentation
const ULONG CmpCacheOnFlag = CM_CACHE_FAKE_KEY
Definition at line 25 of file cmparse.c.
Referenced by CmpAddInfoAfterParseFailure().
PCM_KEY_CONTROL_BLOCK CmpKeyControlBlockRoot
Definition at line 74 of file cmdat2.c.
BOOLEAN CmpNoMasterCreates
Definition at line 306 of file cmdat.c.
Referenced by CmpParseKey().
UNICODE_STRING CmSymbolicLinkValueName
Definition at line 222 of file cmdat.c.