Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/runtime.c File Reference
runtime.c File Reference
#include "ki.h"
Functions
VOID KeUpdateRunTime (IN PKTRAP_FRAME TrapFrame, IN LONG Increment)
Function Documentation
VOID KeUpdateRunTime (IN PKTRAP_FRAME TrapFrame, IN LONG Increment)
Definition at line 23 of file runtime.c.
References _KPRCB::AdjustDpcThreshold, CLOCK_QUANTUM_DECREMENT, DbgBreakPoint(), DbgPrint(), _KPRCB::DebugDpcTime, DISPATCH_LEVEL, DPC_NORMAL, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KPRCB::DpcInterruptRequested, _KPRCB::DpcLastCount, _KDPC_DATA::DpcQueueDepth, _KPRCB::DpcRequestRate, _KPRCB::DpcRoutineActive, _KPRCB::DpcTime, FALSE, _KPRCB::IdleThread, _KPRCB::InterruptTime, KdCheckForDebugBreak(), KdDebuggerEnabled, KeGetCurrentPrcb(), KeGetCurrentThread(), KeMaximumIncrement, KeNumberProcessors, _KPRCB::KernelTime, _KTHREAD::KernelTime, KiAdjustDpcThreshold, KiDPCTimeout, KiIdealDpcRate, KiMaximumDpcQueueDepth, KiRequestSoftwareInterrupt, _KPRCB::MaximumDpcQueueDepth, MODE_MASK, _KPRCB::Number, _KTHREAD::Quantum, _KPRCB::QuantumEnd, _KPRCB::SkipTick, _KPRCB::TickOffset, TRUE, _KPRCB::UserTime, and _KTHREAD::UserTime.