Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/copysup.c File Reference
copysup.c File Reference
#include "cc.h"
Macros
#define me 0x00000004
Functions
BOOLEAN CcCanIWrite (__in PFILE_OBJECT FileObject, __in ULONG BytesToWrite, __in BOOLEAN Wait, __in UCHAR Retrying)
BOOLEAN CcCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
LONG CcCopyReadExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointer, IN PNTSTATUS ExceptionCode)
BOOLEAN CcCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in_bcount(Length) PVOID Buffer)
VOID CcDeferWrite (__in PFILE_OBJECT FileObject, __in PCC_POST_DEFERRED_WRITE PostRoutine, __in PVOID Context1, __in PVOID Context2, __in ULONG BytesToWrite, __in BOOLEAN Retrying)
VOID CcFastCopyRead (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in ULONG PageCount, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
VOID CcFastCopyWrite (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in_bcount(Length) PVOID Buffer)
VOID CcPostDeferredWrites ()
Macro Definition Documentation
#define me 0x00000004
Definition at line 25 of file copysup.c.
Referenced by CcCopyRead(), CcCopyWrite(), CcFastCopyRead(), and CcFastCopyWrite().
Function Documentation
BOOLEAN CcCanIWrite (__in PFILE_OBJECT FileObject, __in ULONG BytesToWrite, __in BOOLEAN Wait, __in UCHAR Retrying)
Definition at line 1710 of file copysup.c.
References BooleanFlagOn, _DEFERRED_WRITE::BytesToWrite, CACHE_NTC_DEFERRED_WRITE, CcAcquireMasterLock, CcDeferredWrites, CcDeferredWriteSpinLock, CcDirtyPageThreshold, CcIdleDelay, CcPostDeferredWrites(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcTotalDirtyPages, _DEFERRED_WRITE::DeferredWriteLinks, _SHARED_CACHE_MAP::DirtyPages, _SHARED_CACHE_MAP::DirtyPageThreshold, _DEFERRED_WRITE::Event, Executive, ExInterlockedInsertHeadList(), ExInterlockedInsertTailList(), FALSE, _DEFERRED_WRITE::FileObject, FlagOn, FO_WRITE_THROUGH, FSRTL_FLAG_LIMIT_MODIFIED_PAGES, IoIsFileOriginRemote(), IsListEmpty, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _DEFERRED_WRITE::LimitModifiedPages, MAXUCHAR, MmEnoughMemoryForWrite, _DEFERRED_WRITE::NodeByteSize, _DEFERRED_WRITE::NodeTypeCode, NotificationEvent, NULL, PAGE_SIZE, _SECTION_OBJECT_POINTERS::SharedCacheMap, STATUS_SUCCESS, TRUE, and WRITE_CHARGE_THRESHOLD.
Referenced by CcForceWriteThrough(), CcLazyWriteScan(), CcPostDeferredWrites(), FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
BOOLEAN CcCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 34 of file copysup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _VACB::BaseAddress, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_SET_PRIVATE_CACHE_MAP, CcCopyReadExceptionFilter(), CcCopyReadNoWait, CcCopyReadNoWaitMiss, CcCopyReadWait, CcCopyReadWaitMiss, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMissCounter, CcPinFileData(), CcScheduleReadAhead(), CcThrowAway, CcUnpinFileData, DebugTrace, except, ExRaiseStatus(), FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, _SHARED_CACHE_MAP::FileSize, FlagOn, _PRIVATE_CACHE_MAP::Flags, FO_RANDOM_ACCESS, FsRtlNormalizeNtstatus(), GetActiveVacb, HOT_STATISTIC, _LARGE_INTEGER::LowPart, me, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, _SHARED_CACHE_MAP::NeedToZero, NULL, PAGE_SHIFT, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _PRIVATE_CACHE_MAP_FLAGS::ReadAheadEnabled, _PRIVATE_CACHE_MAP::ReadAheadLength, ROUND_TO_PAGES, RtlCopyBytes, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, TRUE, UNPIN, VACB_MAPPING_GRANULARITY, and VACB_OFFSET_SHIFT.
Referenced by FsRtlCopyRead().
LONG CcCopyReadExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointer, IN PNTSTATUS ExceptionCode)
Definition at line 1667 of file copysup.c.
References ASSERT, EXCEPTION_EXECUTE_HANDLER, NT_SUCCESS, and STATUS_IN_PAGE_ERROR.
Referenced by CcCopyRead(), CcCopyWrite(), CcFastCopyRead(), CcFastCopyWrite(), and CcMapAndCopy().
BOOLEAN CcCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in_bcount(Length) PVOID Buffer)
Definition at line 1081 of file copysup.c.
References ACTIVE_PAGE_IS_DIRTY, _SHARED_CACHE_MAP::ActiveVacbSpinLock, _VACB::BaseAddress, CcCopyReadExceptionFilter(), CcFreeActiveVacb(), CcMapAndCopy(), DebugTrace, ExAcquireFastLock, ExAcquireFastMutex(), except, ExRaiseStatus(), ExReleaseFastLock, ExReleaseFastMutex(), FALSE, _FSRTL_ADVANCED_FCB_HEADER::FastMutex, FileOffset, FlagOn, FO_WRITE_THROUGH, FSRTL_FLAG_ADVANCED_HEADER, FsRtlNormalizeNtstatus(), GetActiveVacb, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, me, _SHARED_CACHE_MAP::NeedToZero, _SHARED_CACHE_MAP::NeedToZeroVacb, NULL, OPTIMIZE_FIRST_PAGE, OPTIMIZE_LAST_PAGE, OPTIMIZE_MIDDLE_PAGES, PAGE_SHIFT, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlCopyBytes, RtlZeroBytes, RtlZeroMemory, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_UNEXPECTED_IO_ERROR, TRUE, and VACB_MAPPING_GRANULARITY.
Referenced by FsRtlCopyWrite().
VOID CcDeferWrite (__in PFILE_OBJECT FileObject, __in PCC_POST_DEFERRED_WRITE PostRoutine, __in PVOID Context1, __in PVOID Context2, __in ULONG BytesToWrite, __in BOOLEAN Retrying)
Definition at line 1922 of file copysup.c.
References BooleanFlagOn, _DEFERRED_WRITE::BytesToWrite, CACHE_NTC_DEFERRED_WRITE, CcAcquireMasterLock, CcDeferredWrites, CcDeferredWriteSpinLock, CcPostDeferredWrites(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), _DEFERRED_WRITE::Context1, _DEFERRED_WRITE::Context2, _DEFERRED_WRITE::DeferredWriteLinks, _DEFERRED_WRITE::Event, ExAllocatePoolWithTag, ExInterlockedInsertHeadList(), ExInterlockedInsertTailList(), FALSE, _DEFERRED_WRITE::FileObject, FSRTL_FLAG_LIMIT_MODIFIED_PAGES, LazyWriter, _DEFERRED_WRITE::LimitModifiedPages, _DEFERRED_WRITE::NodeByteSize, _DEFERRED_WRITE::NodeTypeCode, NonPagedPool, NULL, _DEFERRED_WRITE::PostRoutine, and _LAZY_WRITER::ScanActive.
VOID CcFastCopyRead (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in ULONG PageCount, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 593 of file copysup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _VACB::BaseAddress, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_SET_PRIVATE_CACHE_MAP, CcCopyReadExceptionFilter(), CcCopyReadWait, CcCopyReadWaitMiss, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMissCounter, CcScheduleReadAhead(), CcThrowAway, DebugTrace, except, ExRaiseStatus(), FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, _SHARED_CACHE_MAP::FileSize, FlagOn, _PRIVATE_CACHE_MAP::Flags, FO_RANDOM_ACCESS, FsRtlNormalizeNtstatus(), GetActiveVacb, _LARGE_INTEGER::HighPart, HOT_STATISTIC, _LARGE_INTEGER::LowPart, me, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, _SHARED_CACHE_MAP::NeedToZero, NULL, PAGE_SHIFT, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _PRIVATE_CACHE_MAP_FLAGS::ReadAheadEnabled, _PRIVATE_CACHE_MAP::ReadAheadLength, ROUND_TO_PAGES, RtlCopyBytes, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, UNREFERENCED_PARAMETER, VACB_MAPPING_GRANULARITY, and VACB_OFFSET_SHIFT.
Referenced by FsRtlCopyRead().
VOID CcFastCopyWrite (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in_bcount(Length) PVOID Buffer)
Definition at line 1399 of file copysup.c.
References ACTIVE_PAGE_IS_DIRTY, _SHARED_CACHE_MAP::ActiveVacbSpinLock, ASSERT, _VACB::BaseAddress, CcCopyReadExceptionFilter(), CcFreeActiveVacb(), CcMapAndCopy(), DebugTrace, ExAcquireFastLock, except, ExRaiseStatus(), ExReleaseFastLock, FALSE, FileOffset, FlagOn, FO_WRITE_THROUGH, FsRtlNormalizeNtstatus(), GetActiveVacb, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, MAXULONG, me, _SHARED_CACHE_MAP::NeedToZero, _SHARED_CACHE_MAP::NeedToZeroVacb, NULL, OPTIMIZE_FIRST_PAGE, OPTIMIZE_LAST_PAGE, OPTIMIZE_MIDDLE_PAGES, PAGE_SHIFT, PAGE_SIZE, RtlCopyBytes, RtlZeroBytes, RtlZeroMemory, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_UNEXPECTED_IO_ERROR, TRUE, and VACB_MAPPING_GRANULARITY.
Referenced by FsRtlCopyWrite().
VOID CcPostDeferredWrites ()
Definition at line 2039 of file copysup.c.
References _DEFERRED_WRITE::BytesToWrite, CcCanIWrite(), CcDeferredWrites, CcDeferredWriteSpinLock, CONTAINING_RECORD, _DEFERRED_WRITE::Context1, _DEFERRED_WRITE::Context2, _DEFERRED_WRITE::DeferredWriteLinks, _DEFERRED_WRITE::Event, ExAcquireSpinLock, ExFreePool(), ExReleaseSpinLock, FALSE, _DEFERRED_WRITE::FileObject, _LIST_ENTRY::Flink, IsListEmpty, KeSetEvent(), _DEFERRED_WRITE::LimitModifiedPages, MAXUCHAR, NULL, _DEFERRED_WRITE::PostRoutine, and RemoveEntryList().
Referenced by CcCanIWrite(), CcDeferWrite(), CcFlushCache(), CcLazyWriteScan(), CcUnpinRepinnedBcb(), and CcWriteBehind().