Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obclose.c File Reference
obclose.c File Reference
#include "obp.h"
Functions
NTSTATUS NtClose (__in HANDLE Handle)
NTSTATUS NtMakeTemporaryObject (__in HANDLE Handle)
NTSTATUS ObCloseHandle (__in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
VOID ObMakeTemporaryObject (__in PVOID Object)
NTSTATUS ObpCloseHandle (IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS ObpCloseHandleTableEntry (IN PHANDLE_TABLE ObjectTable, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN Rundown)
Variables
BOOLEAN SepAdtAuditingEnabled
Function Documentation
NTSTATUS NtClose (__in HANDLE Handle)
Definition at line 399 of file obclose.c.
References KeGetPreviousMode, and ObpCloseHandle().
Referenced by CmGetSystemDriverList(), CmInitSystem1(), CmpAddAliasEntry(), CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpLinkKeyToHive(), CmpRemoveFromHiveFileList(), CmpSaveBootControlSet(), CmpSetNetworkValue(), CmpSetSystemValues(), CmpSetupConfigurationTree(), CreateSystemRootLink(), ExpInitializeCallbacks(), IopConnectLinkTrackingPort(), IopErrorLogConnectPort(), IopErrorLogThread(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopReferenceDriverObjectByName(), IoSetSystemPartition(), LpcpCreatePort(), MiSectionInitialization(), NtAcceptConnectPort(), NtCreateKey(), NtOpenKey(), NtSecureConnectPort(), ObDuplicateObject(), ObInitSystem(), ObpCreateDosDevicesDirectory(), RtlAdjustPrivilege(), RtlCreateSystemVolumeInformationFolder(), RtlpImpersonateSelfEx(), RtlpSysVolTakeOwnership(), RtlQueryRegistryValues(), SepAdtInitializePrivilegeAuditing(), SepInitializationPhase1(), and SepRmCommandServerThreadInit().
NTSTATUS NtMakeTemporaryObject (__in HANDLE Handle)
Definition at line 425 of file obclose.c.
References DELETE, _OBJECT_HANDLE_INFORMATION::HandleAttributes, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, ObMakeTemporaryObject(), ObReferenceObjectByHandle, PAGED_CODE, SeDeleteObjectAuditAlarm(), and Status.
Referenced by IopReassignSystemRoot().
NTSTATUS ObCloseHandle (__in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
Definition at line 373 of file obclose.c.
References ObpCloseHandle().
Referenced by CmShutdownSystem(), DbgkCreateThread(), DbgkMapViewOfSection(), DbgkpFreeDebugEvent(), DbgkpOpenHandles(), DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), IoCreateController(), IoCreateDevice(), IoCreateStreamFileObjectEx(), IoInitSystem(), IopCreateRootDirectories(), IopLoadDriver(), IopMarkBootPartition(), IopOpenLinkOrRenameTarget(), IopReassignSystemRoot(), IopSafebootDriverLoad(), IopStoreSystemPartitionInformation(), IopUnloadDriver(), IoSetInformation(), NtQueryInformationProcess(), NtSetInformationFile(), PspCreateProcess(), PspCreateThread(), and PspExitThread().
VOID ObMakeTemporaryObject (__in PVOID Object)
Definition at line 495 of file obclose.c.
References _OBJECT_HEADER::Flags, OB_FLAG_PERMANENT_OBJECT, OBJECT_TO_OBJECT_HEADER, ObpDeleteNameCheck(), ObpLockObject, ObpUnlockObject, PAGED_CODE, and _OBJECT_HEADER::Type.
Referenced by IoCreateDriver(), IoDeleteDevice(), IopCompleteUnloadOrDelete(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopUnloadDriver(), NtMakeTemporaryObject(), ObfDereferenceDeviceMap(), and ObShutdownSystem().
NTSTATUS ObpCloseHandle (IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
Definition at line 211 of file obclose.c.
References _HANDLE_TABLE::DebugInfo, _EPROCESS::DebugPort, DecodeKernelHandle, ExMapHandleToPointer(), FALSE, FLG_ENABLE_CLOSE_EXCEPTIONS, INVALID_KERNEL_HANDLE, IsKernelHandle, KdDebuggerEnabled, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeIsAttachedProcess(), KeLeaveCriticalRegionThread(), KeRaiseUserException(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, _EPROCESS::ObjectTable, ObpCloseHandleTableEntry(), ObpKernelHandleTable, ObpValidateIrql, _EPROCESS::Pcb, _EPROCESS::Peb, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, PsIsThreadTerminating(), Status, STATUS_INVALID_HANDLE, _ETHREAD::Tcb, and TRUE.
Referenced by NtClose(), and ObCloseHandle().
NTSTATUS ObpCloseHandleTableEntry (IN PHANDLE_TABLE ObjectTable, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN Rundown)
Definition at line 38 of file obclose.c.
References _OBJECT_HEADER::Body, ExDestroyHandle(), ExUnlockHandleTableEntry(), FALSE, FLG_ENABLE_CLOSE_EXCEPTIONS, FLG_KERNEL_STACK_TRACE_DB, INVALID_KERNEL_HANDLE, KeBugCheckEx(), KeIsAttachedProcess(), KeRaiseUserException(), KernelMode, NtGlobalFlag, NULL, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, OBJ_HANDLE_TAGBITS, OBJ_PROTECT_CLOSE, ObpBeginTypeSpecificCallOut, ObpDecodeGrantedAccess, ObpDecrementHandleCount(), ObpEndTypeSpecificCallOut, ObpGetHandleAttributes, ObpTranslateGrantedAccessIndex(), _OBJECT_TYPE_INITIALIZER::OkayToCloseProcedure, PsGetCurrentProcess(), SeCloseObjectAuditAlarm(), SepAdtAuditingEnabled, STATUS_HANDLE_NOT_CLOSABLE, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by ObpCloseHandle(), and ObpCloseHandleProcedure().
Variable Documentation
BOOLEAN SepAdtAuditingEnabled
Definition at line 302 of file seglobal.c.
Referenced by ObpCloseHandleTableEntry(), and SepRmSetAuditEventWrkr().