Windows Research Kernel v1.2: C:/Windows Research Kernel/se/token.c File Reference
token.c File Reference
#include "pch.h"
Macros
#define EVERYONE_INCLUDES_ANONYMOUS 1
#define SepEqualLuidAndAttribute(a, b)
#define SepEqualSidAndAttribute(a, b)
Functions
NTSTATUS NtCompareTokens (__in HANDLE FirstTokenHandle, __in HANDLE SecondTokenHandle, __out PBOOLEAN Equal)
NTSTATUS NtCreateToken (__out PHANDLE TokenHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in TOKEN_TYPE TokenType, __in PLUID AuthenticationId, __in PLARGE_INTEGER ExpirationTime, __in PTOKEN_USER User, __in PTOKEN_GROUPS Groups, __in PTOKEN_PRIVILEGES Privileges, __in_opt PTOKEN_OWNER Owner, __in PTOKEN_PRIMARY_GROUP PrimaryGroup, __in_opt PTOKEN_DEFAULT_DACL DefaultDacl, __in PTOKEN_SOURCE TokenSource)
NTSTATUS NtImpersonateAnonymousToken (__in HANDLE ThreadHandle)
VOID SeAddSaclToProcess (__in PEPROCESS Process, __in PACCESS_TOKEN Token, __in PVOID Reserved)
VOID SeAssignPrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN Token)
VOID SeDeassignPrimaryToken (__in PEPROCESS Process)
NTSTATUS SeExchangePrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN NewAccessToken, __deref_out PACCESS_TOKEN *OldAccessToken)
VOID SeGetTokenControlInformation (__in PACCESS_TOKEN Token, __out PTOKEN_CONTROL TokenControl)
NTSTATUS SeIsChildToken (__in HANDLE Token, __out PBOOLEAN IsChild)
NTSTATUS SeIsChildTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsChild)
NTSTATUS SeIsSiblingToken (__in HANDLE Token, __out PBOOLEAN IsSibling)
NTSTATUS SeIsSiblingTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsSibling)
PACCESS_TOKEN SeMakeAnonymousLogonToken (VOID)
PACCESS_TOKEN SeMakeAnonymousLogonTokenNoEveryone (VOID)
PACCESS_TOKEN SeMakeSystemToken ()
BOOLEAN SepCheckTokenForCoreSystemSids (__in PACCESS_TOKEN Token)
BOOLEAN SepComparePrivilegeAndAttributeArrays (IN PLUID_AND_ATTRIBUTES PrivilegeArray1, IN ULONG Count1, IN PLUID_AND_ATTRIBUTES PrivilegeArray2, IN ULONG Count2)
BOOLEAN SepCompareSidAndAttributeArrays (IN PSID_AND_ATTRIBUTES SidArray1, IN ULONG Count1, IN PSID_AND_ATTRIBUTES SidArray2, IN ULONG Count2)
NTSTATUS SepCreateToken (OUT PHANDLE TokenHandle, IN KPROCESSOR_MODE RequestorMode, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN TOKEN_TYPE TokenType, IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel OPTIONAL, IN PLUID AuthenticationId, IN PLARGE_INTEGER ExpirationTime, IN PSID_AND_ATTRIBUTES User, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES Groups, IN ULONG GroupsLength, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES Privileges, IN PSID Owner OPTIONAL, IN PSID PrimaryGroup, IN PACL DefaultDacl OPTIONAL, IN PTOKEN_SOURCE TokenSource, IN BOOLEAN SystemToken, IN PSECURITY_TOKEN_PROXY_DATA ProxyData OPTIONAL, IN PSECURITY_TOKEN_AUDIT_DATA AuditData OPTIONAL)
BOOLEAN SepIdAssignableAsOwner (IN PTOKEN Token, IN ULONG Index)
VOID SepTokenDeleteMethod (IN PVOID Token)
BOOLEAN SepTokenInitialization (VOID)
NTSTATUS SeSubProcessToken (__in PACCESS_TOKEN ParentToken, __deref_out PACCESS_TOKEN *ChildToken, __in BOOLEAN MarkAsActive, __in ULONG SessionId)
NTKERNELAPI NTSTATUS SeTokenCanImpersonate (__in PACCESS_TOKEN ProcessToken, __in PACCESS_TOKEN Token, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
SECURITY_IMPERSONATION_LEVEL SeTokenImpersonationLevel (__in PACCESS_TOKEN Token)
NTKERNELAPI BOOLEAN SeTokenIsAdmin (__in PACCESS_TOKEN Token)
NTKERNELAPI BOOLEAN SeTokenIsRestricted (__in PACCESS_TOKEN Token)
TOKEN_TYPE SeTokenType (__in PACCESS_TOKEN Token)
Variables
const GENERIC_MAPPING SepTokenMapping
POBJECT_TYPE SeTokenObjectType = NULL
Macro Definition Documentation
#define EVERYONE_INCLUDES_ANONYMOUS 1
Referenced by NtImpersonateAnonymousToken().
#define SepEqualLuidAndAttribute (a, b)
Value:
((RtlEqualLuid(&(a).Luid, &(b).Luid)) &&                               \
         ((((a).Attributes ^ (b).Attributes) &  SE_PRIVILEGE_ENABLED) == 0)    \
        )
Definition at line 3718 of file token.c.
Referenced by SepComparePrivilegeAndAttributeArrays().
#define SepEqualSidAndAttribute (a, b)
Value:
((RtlEqualSid((a).Sid, (b).Sid)) &&                                    \
         ((((a).Attributes ^ (b).Attributes) &                                 \
           (SE_GROUP_ENABLED | SE_GROUP_USE_FOR_DENY_ONLY)) == 0)              \
        )
Definition at line 3712 of file token.c.
Referenced by NtCompareTokens(), and SepCompareSidAndAttributeArrays().
Function Documentation
NTSTATUS NtCompareTokens (__in HANDLE FirstTokenHandle, __in HANDLE SecondTokenHandle, __out PBOOLEAN Equal)
Definition at line 3951 of file token.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _TOKEN::PrivilegeCount, _TOKEN::Privileges, ProbeForWriteBoolean, SepAcquireTokenReadLock, SepComparePrivilegeAndAttributeArrays(), SepCompareSidAndAttributeArrays(), SepEqualSidAndAttribute, SepReleaseTokenReadLock, SeTokenIsRestricted(), Status, STATUS_SUCCESS, TOKEN_QUERY, TRUE, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
NTSTATUS NtCreateToken (__out PHANDLE TokenHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in TOKEN_TYPE TokenType, __in PLUID AuthenticationId, __in PLARGE_INTEGER ExpirationTime, __in PTOKEN_USER User, __in PTOKEN_GROUPS Groups, __in PTOKEN_PRIVILEGES Privileges, __in_opt PTOKEN_OWNER Owner, __in PTOKEN_PRIMARY_GROUP PrimaryGroup, __in_opt PTOKEN_DEFAULT_DACL DefaultDacl, __in PTOKEN_SOURCE TokenSource)
Definition at line 1934 of file token.c.
References ARGUMENT_PRESENT, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::AuditData, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::ImpersonationLevel, KeGetPreviousMode, KernelMode, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, ProbeForReadSmallStructure, ProbeForWriteHandle, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::ProxyData, RtlCopyLuid(), SeCaptureAcl(), SeCaptureLuidAndAttributesArray(), SeCaptureSecurityQos(), SeCaptureSid(), SeCaptureSidAndAttributesArray(), SecurityAnonymous, SecurityDelegation, SecurityIdentification, SecurityImpersonation, SeFreeCapturedSecurityQos(), SepCreateToken(), SeReleaseAcl(), SeReleaseLuidAndAttributesArray(), SeReleaseSid(), SeReleaseSidAndAttributesArray(), Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_BAD_TOKEN_TYPE, STATUS_SUCCESS, TokenImpersonation, TokenPrimary, and TRUE.
NTSTATUS NtImpersonateAnonymousToken (__in HANDLE ThreadHandle)
Definition at line 3584 of file token.c.
References EVERYONE_INCLUDES_ANONYMOUS, FALSE, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PsDereferencePrimaryToken, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsImpersonateClient(), PsReferencePrimaryToken(), PsThreadType, SeAnonymousLogonToken, SeAnonymousLogonTokenNoEveryone, SecurityImpersonation, SepRegQueryDwordValue(), SeTokenIsRestricted(), Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_IMPERSONATE, TOKEN_IMPERSONATE, and TRUE.
VOID SeAddSaclToProcess (__in PEPROCESS Process, __in PACCESS_TOKEN Token, __in PVOID Reserved)
Definition at line 412 of file token.c.
References ASSERT, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NonPagedPool, NT_SUCCESS, NULL, OBJECT_TO_OBJECT_HEADER, ObSetSecurityDescriptorInfo(), PAGED_CODE, SACL_SECURITY_INFORMATION, _OBJECT_HEADER::SecurityDescriptor, SepAuditFailed(), SepCheckTokenForCoreSystemSids(), SepProcessAuditSd, Status, STATUS_NO_SECURITY_ON_OBJECT, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
VOID SeAssignPrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN Token)
Definition at line 502 of file token.c.
References ASSERT, ExFastRefObjectNull(), NULL, ObInitializeFastReference(), ObReferenceObject, PAGED_CODE, SeDeassignPrimaryToken(), SeDetailedAuditingWithToken(), SepAuditAssignPrimaryToken(), Status, _TOKEN::TokenInUse, TokenPrimary, _TOKEN::TokenType, and TRUE.
Referenced by PspCreateProcess(), and PspInitializeProcessSecurity().
VOID SeDeassignPrimaryToken (__in PEPROCESS Process)
Definition at line 583 of file token.c.
References ASSERT, FALSE, NULL, ObDereferenceObject(), ObFastReplaceObject(), PAGED_CODE, _TOKEN::TokenInUse, TokenPrimary, and _TOKEN::TokenType.
Referenced by PspDeleteProcessSecurity(), and SeAssignPrimaryToken().
NTSTATUS SeExchangePrimaryToken (__in PEPROCESS Process, __in PACCESS_TOKEN NewAccessToken, __deref_out PACCESS_TOKEN * OldAccessToken)
Definition at line 627 of file token.c.
References ASSERT, FALSE, MmGetSessionId(), NULL, ObFastReplaceObject(), ObReferenceObject, PAGED_CODE, SeDetailedAuditingWithToken(), SepAcquireTokenWriteLock, SepAuditAssignPrimaryToken(), SepReleaseTokenWriteLock, _TOKEN::SessionId, Status, STATUS_BAD_TOKEN_TYPE, STATUS_NO_TOKEN, STATUS_SUCCESS, STATUS_TOKEN_ALREADY_IN_USE, _TOKEN::TokenInUse, TokenPrimary, _TOKEN::TokenType, and TRUE.
Referenced by PspAssignPrimaryToken().
VOID SeGetTokenControlInformation (__in PACCESS_TOKEN Token, __out PTOKEN_CONTROL TokenControl)
Definition at line 783 of file token.c.
References PAGED_CODE, SepAcquireTokenReadLock, and SepReleaseTokenReadLock.
Referenced by SepCreateClientSecurity().
NTSTATUS SeIsChildToken (__in HANDLE Token, __out PBOOLEAN IsChild)
Definition at line 3227 of file token.c.
References FALSE, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _TOKEN::TokenId, and TRUE.
NTSTATUS SeIsChildTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsChild)
Definition at line 3317 of file token.c.
References FALSE, NULL, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _TOKEN::TokenId, and TRUE.
Referenced by NtSetInformationJobObject(), and PspSetPrimaryToken().
NTSTATUS SeIsSiblingToken (__in HANDLE Token, __out PBOOLEAN IsSibling)
Definition at line 3392 of file token.c.
References _TOKEN::AuthenticationId, FALSE, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
NTSTATUS SeIsSiblingTokenByPointer (__in PACCESS_TOKEN Token, __out PBOOLEAN IsSibling)
Definition at line 3497 of file token.c.
References _TOKEN::AuthenticationId, FALSE, NULL, _TOKEN::ParentTokenId, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsReferencePrimaryToken(), RtlEqualLuid, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by PspSetPrimaryToken().
PACCESS_TOKEN SeMakeAnonymousLogonToken (VOID)
Definition at line 1503 of file token.c.
References ACL_REVISION2, ASSERT, _SID_AND_ATTRIBUTES::Attributes, _TIME_FIELDS::Day, ExAllocatePoolWithTag, ExFreePool(), FALSE, _TIME_FIELDS::Hour, InitializeObjectAttributes, KernelMode, LongAlignSize, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _TOKEN_PRIMARY_GROUP::PrimaryGroup, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlTimeFieldsToTime(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SeAnonymousAuthenticationId, SeAnonymousLogonSid, _TIME_FIELDS::Second, SECURITY_DESCRIPTOR_MIN_LENGTH, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SepCreateToken(), SeSystemTokenSource, SeWorldSid, _SID_AND_ATTRIBUTES::Sid, Status, TOKEN_ALL_ACCESS, TokenPrimary, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
Referenced by SepInitializationPhase1().
PACCESS_TOKEN SeMakeAnonymousLogonTokenNoEveryone (VOID)
Definition at line 1289 of file token.c.
References ACL_REVISION2, ASSERT, _SID_AND_ATTRIBUTES::Attributes, _TIME_FIELDS::Day, ExAllocatePoolWithTag, ExFreePool(), FALSE, _TIME_FIELDS::Hour, InitializeObjectAttributes, KernelMode, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _TOKEN_PRIMARY_GROUP::PrimaryGroup, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlTimeFieldsToTime(), SeAnonymousAuthenticationId, SeAnonymousLogonSid, _TIME_FIELDS::Second, SECURITY_DESCRIPTOR_MIN_LENGTH, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SepCreateToken(), SeSystemTokenSource, SeWorldSid, _SID_AND_ATTRIBUTES::Sid, Status, TOKEN_ALL_ACCESS, TokenPrimary, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
Referenced by SepInitializationPhase1().
PACCESS_TOKEN SeMakeSystemToken ()
Definition at line 849 of file token.c.
References ACL_REVISION2, ASSERT, _LUID_AND_ATTRIBUTES::Attributes, _SID_AND_ATTRIBUTES::Attributes, _TIME_FIELDS::Day, ExAllocatePoolWithTag, ExFreePool(), FALSE, _TIME_FIELDS::Hour, InitializeObjectAttributes, KernelMode, LongAlignSize, _LUID_AND_ATTRIBUTES::Luid, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _TOKEN_PRIMARY_GROUP::PrimaryGroup, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlTimeFieldsToTime(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SE_GROUP_OWNER, SE_PRIVILEGE_ENABLED, SE_PRIVILEGE_ENABLED_BY_DEFAULT, SeAliasAdminsSid, SeAssignPrimaryTokenPrivilege, SeAuditPrivilege, SeAuthenticatedUsersSid, SeBackupPrivilege, SeChangeNotifyPrivilege, _TIME_FIELDS::Second, SeCreateGlobalPrivilege, SeCreatePagefilePrivilege, SeCreatePermanentPrivilege, SeCreateTokenPrivilege, SECURITY_DESCRIPTOR_REVISION, SeDebugPrivilege, SeImpersonatePrivilege, SeIncreaseBasePriorityPrivilege, SeIncreaseQuotaPrivilege, SeLengthSid, SeLoadDriverPrivilege, SeLocalSystemSid, SeLockMemoryPrivilege, SeManageVolumePrivilege, SepCreateToken(), SeProfileSingleProcessPrivilege, SeRestorePrivilege, SeSecurityPrivilege, SeShutdownPrivilege, SeSystemAuthenticationId, SeSystemDefaultDacl, SeSystemEnvironmentPrivilege, SeSystemtimePrivilege, SeSystemTokenSource, SeTakeOwnershipPrivilege, SeTcbPrivilege, SeUndockPrivilege, SeWorldSid, _SID_AND_ATTRIBUTES::Sid, Status, TOKEN_ALL_ACCESS, TokenPrimary, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
BOOLEAN SepCheckTokenForCoreSystemSids (__in PACCESS_TOKEN Token)
Definition at line 359 of file token.c.
References GenericMappingForMembershipCheck, KernelMode, NULL, PAGED_CODE, SEP_QUERY_MEMBERSHIP, SepAccessCheck(), SepImportantProcessSd, STATUS_ACCESS_DENIED, and STATUS_SUCCESS.
Referenced by SeAddSaclToProcess().
BOOLEAN SepComparePrivilegeAndAttributeArrays (IN PLUID_AND_ATTRIBUTES PrivilegeArray1, IN ULONG Count1, IN PLUID_AND_ATTRIBUTES PrivilegeArray2, IN ULONG Count2)
Definition at line 3724 of file token.c.
References FALSE, SepEqualLuidAndAttribute, and TRUE.
Referenced by NtCompareTokens().
BOOLEAN SepCompareSidAndAttributeArrays (IN PSID_AND_ATTRIBUTES SidArray1, IN ULONG Count1, IN PSID_AND_ATTRIBUTES SidArray2, IN ULONG Count2)
Definition at line 3837 of file token.c.
References FALSE, SepEqualSidAndAttribute, and TRUE.
Referenced by NtCompareTokens().
NTSTATUS SepCreateToken (OUT PHANDLE TokenHandle, IN KPROCESSOR_MODE RequestorMode, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN TOKEN_TYPE TokenType, IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel OPTIONAL, IN PLUID AuthenticationId, IN PLARGE_INTEGER ExpirationTime, IN PSID_AND_ATTRIBUTES User, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES Groups, IN ULONG GroupsLength, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES Privileges, IN PSID Owner OPTIONAL, IN PSID PrimaryGroup, IN PACL DefaultDacl OPTIONAL, IN PTOKEN_SOURCE TokenSource, IN BOOLEAN SystemToken, IN PSECURITY_TOKEN_PROXY_DATA ProxyData OPTIONAL, IN PSECURITY_TOKEN_AUDIT_DATA AuditData OPTIONAL)
Definition at line 2500 of file token.c.
References ALIGN_UP, ARGUMENT_PRESENT, ASSERT, _TOKEN::AuditData, _TOKEN::AuditPolicy, _TOKEN::AuthenticationId, _ETHREAD::Cid, DbgBreakPoint(), DbgPrint(), _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, DISPATCH_LEVEL, _TOKEN::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN::DynamicPart, ExAllocateLocallyUniqueId(), ExAllocatePool, ExAllocatePoolWithTag, ExFastRefObjectNull(), ExFreePool(), ExInitializeResourceLite(), _TOKEN::ExpirationTime, FALSE, FIELD_OFFSET, _OBJECT_TYPE_INITIALIZER::GenericMapping, _TOKEN::ImpersonationLevel, InterlockedIncrement, KeGetCurrentIrql(), KeGetPreviousMode, _TOKEN::LogonSession, LongAlignSize, min, _TOKEN::ModifiedId, NonPagedPool, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), _TOKEN::OriginatingLogonSession, _SEP_AUDIT_POLICY::Overlay, PAGED_CODE, PagedPool, _TOKEN::ParentTokenId, _TOKEN::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN::Privileges, _TOKEN::ProxyData, PsGetCurrentProcess(), PsGetCurrentThread(), _TOKEN::RestrictedSidCount, _TOKEN::RestrictedSids, RtlConvertLongToLuid(), RtlCopyMemory, RtlCopySid(), RtlCopySidAndAttributesArray(), RtlEqualLuid, RtlEqualSid(), RtlLengthRequiredSid(), RtlWalkFrameChain(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SE_GROUP_OWNER, SE_PRIVILEGE_ENABLED, SeAliasAdminsSid, SeChangeNotifyPrivilege, SeCreateAccessState(), SeCreateTokenPrivilege, SeDeleteAccessState(), SeImpersonatePrivilege, SepArrayGroupAttributes, SepCopyProxyData(), SepReferenceLogonSession(), SeSinglePrivilegeCheck(), _TOKEN::SessionId, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_OWNER, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, TOKEN_DEFAULT_DYNAMIC_CHARGE, TOKEN_HAS_ADMIN_GROUP, TOKEN_HAS_IMPERSONATE_PRIVILEGE, TOKEN_HAS_TRAVERSE_PRIVILEGE, TOKEN_SESSION_NOT_REFERENCED, _TOKEN::TokenFlags, _TOKEN::TokenId, _TOKEN::TokenInUse, _TOKEN::TokenLock, _TOKEN::TokenSource, _TOKEN::TokenType, TokenType, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _EPROCESS::UniqueProcessId, _CLIENT_ID::UniqueThread, _TOKEN::UserAndGroupCount, _TOKEN::UserAndGroups, UserMode, _TOKEN::VariableLength, and _TOKEN::VariablePart.
Referenced by NtCreateToken(), SeMakeAnonymousLogonToken(), SeMakeAnonymousLogonTokenNoEveryone(), and SeMakeSystemToken().
BOOLEAN SepIdAssignableAsOwner (IN PTOKEN Token, IN ULONG Index)
Definition at line 3173 of file token.c.
References PAGED_CODE, SE_GROUP_OWNER, SepTokenGroupAttributes, and TRUE.
Referenced by NtSetInformationToken(), and SepValidOwnerSubjectContext().
VOID SepTokenDeleteMethod (IN PVOID Token)
Definition at line 2423 of file token.c.
References ARGUMENT_PRESENT, ASSERT, ExDeleteResourceLite(), ExFreePool(), FALSE, PAGED_CODE, SepDeReferenceLogonSessionDirect(), SepFreeProxyData(), SepModifyTokenPolicyCounter(), SepTokenPolicyCounter, and TOKEN_SESSION_NOT_REFERENCED.
Referenced by SepTokenInitialization().
BOOLEAN SepTokenInitialization (VOID)
Definition at line 1864 of file token.c.
References _OBJECT_TYPE_INITIALIZER::DeleteProcedure, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityRequired, SepTokenDeleteMethod(), SepTokenMapping, Status, TOKEN_ALL_ACCESS, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by SepInitializationPhase0().
NTSTATUS SeSubProcessToken (__in PACCESS_TOKEN ParentToken, __deref_out PACCESS_TOKEN * ChildToken, __in BOOLEAN MarkAsActive, __in ULONG SessionId)
Definition at line 1762 of file token.c.
References FALSE, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NULL, ObInsertObject(), PAGED_CODE, SepDuplicateToken(), _TOKEN::SessionId, Status, _TOKEN::TokenInUse, and TokenPrimary.
Referenced by NtAssignProcessToJobObject(), PspCreateProcess(), and PspInitializeProcessSecurity().
NTKERNELAPI NTSTATUS SeTokenCanImpersonate (__in PACCESS_TOKEN ProcessToken, __in PACCESS_TOKEN Token, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 192 of file token.c.
References _TOKEN::AuthenticationId, DbgPrint(), NT_SUCCESS, _TOKEN::OriginatingLogonSession, PAGED_CODE, PsGetCurrentThread(), RtlEqualLuid, RtlEqualSid(), SeAnonymousAuthenticationId, SecurityImpersonation, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SeTokenIsRestricted(), _SID_AND_ATTRIBUTES::Sid, Status, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TOKEN_HAS_IMPERSONATE_PRIVILEGE, _TOKEN::TokenFlags, and _TOKEN::UserAndGroups.
Referenced by PsImpersonateClient().
SECURITY_IMPERSONATION_LEVEL SeTokenImpersonationLevel (__in PACCESS_TOKEN Token)
Definition at line 329 of file token.c.
References PAGED_CODE.
Referenced by PsAssignImpersonationToken().
NTKERNELAPI BOOLEAN SeTokenIsAdmin (__in PACCESS_TOKEN Token)
Definition at line 162 of file token.c.
References PAGED_CODE, and TOKEN_HAS_ADMIN_GROUP.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PsImpersonateClient().
NTKERNELAPI BOOLEAN SeTokenIsRestricted (__in PACCESS_TOKEN Token)
Definition at line 299 of file token.c.
References PAGED_CODE, and TOKEN_IS_RESTRICTED.
Referenced by NtCompareTokens(), NtImpersonateAnonymousToken(), NtQueryInformationToken(), PsImpersonateClient(), SepAccessCheck(), and SeTokenCanImpersonate().
TOKEN_TYPE SeTokenType (__in PACCESS_TOKEN Token)
Definition at line 130 of file token.c.
References PAGED_CODE, and TokenType.
Referenced by NtSetInformationJobObject(), and PsAssignImpersonationToken().
Variable Documentation
const GENERIC_MAPPING SepTokenMapping
Initial value:
= { TOKEN_READ,
                                    TOKEN_WRITE,
                                    TOKEN_EXECUTE,
                                    TOKEN_ALL_ACCESS
                                  }
Definition at line 87 of file token.c.
Referenced by SepTokenInitialization().
POBJECT_TYPE SeTokenObjectType = NULL
Definition at line 97 of file token.c.
Referenced by NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtDuplicateToken(), NtFilterToken(), NtOpenObjectAuditAlarm(), NtOpenProcessTokenEx(), NtOpenThreadTokenEx(), NtPrivilegeCheck(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtQueryInformationToken(), NtSetInformationJobObject(), NtSetInformationToken(), PsAssignImpersonationToken(), PspAssignPrimaryToken(), PspSetPrimaryToken(), SeAccessCheckByType(), SepAccessCheckAndAuditAlarm(), SepDuplicateToken(), and SepFilterToken().