Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/harderr.c File Reference
harderr.c File Reference
#include "exp.h"
Macros
#define HARDERROR_API_MSG_LENGTH sizeof(HARDERROR_MSG)<<16 | (HARDERROR_MSG_OVERHEAD)
#define HARDERROR_MSG_OVERHEAD (sizeof(HARDERROR_MSG) - sizeof(PORT_MESSAGE))
#define SHUTDOWN 2
#define STARTED 1
#define STARTING 0
Functions
VOID __cdecl _purecall ()
NTSTATUS ExpRaiseHardError (IN NTSTATUS ErrorStatus, IN ULONG NumberOfParameters, IN ULONG UnicodeStringParameterMask, IN PULONG_PTR Parameters, IN ULONG ValidResponseOptions, OUT PULONG Response)
VOID ExpSystemErrorHandler (IN NTSTATUS ErrorStatus, IN ULONG NumberOfParameters, IN ULONG UnicodeStringParameterMask, IN PULONG_PTR Parameters, IN BOOLEAN CallShutdown)
NTSTATUS ExRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
NTSTATUS NtRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
NTSTATUS NtSetDefaultHardErrorPort (__in HANDLE DefaultHardErrorPort)
Variables
HANDLE ExpDefaultErrorPort
PEPROCESS ExpDefaultErrorPortProcess
BOOLEAN ExpTooLateForErrors = FALSE
BOOLEAN ExReadyForErrors = FALSE
ULONG HardErrorState = STARTING
PVOID PsSystemDllDllBase
Macro Definition Documentation
#define HARDERROR_API_MSG_LENGTH sizeof(HARDERROR_MSG)<<16 | (HARDERROR_MSG_OVERHEAD)
Definition at line 60 of file harderr.c.
Referenced by ExpRaiseHardError().
#define HARDERROR_MSG_OVERHEAD (sizeof(HARDERROR_MSG) - sizeof(PORT_MESSAGE))
Definition at line 59 of file harderr.c.
#define SHUTDOWN 2
Definition at line 67 of file harderr.c.
Referenced by ExpRaiseHardError().
#define STARTED 1
Definition at line 66 of file harderr.c.
Referenced by NtSetDefaultHardErrorPort().
#define STARTING 0
Definition at line 65 of file harderr.c.
Referenced by ExpRaiseHardError().
Function Documentation
VOID __cdecl _purecall ()
Definition at line 955 of file harderr.c.
References ASSERTMSG, ExRaiseStatus(), FALSE, and STATUS_NOT_IMPLEMENTED.
NTSTATUS ExpRaiseHardError (IN NTSTATUS ErrorStatus, IN ULONG NumberOfParameters, IN ULONG UnicodeStringParameterMask, IN PULONG_PTR Parameters, IN ULONG ValidResponseOptions, OUT PULONG Response)
Definition at line 421 of file harderr.c.
References _ETHREAD::CrossThreadFlags, _EPROCESS::DefaultHardErrorProcessing, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExpDefaultErrorPort, ExpSystemErrorHandler(), ExReadyForErrors, FALSE, HARDERROR_API_MSG_LENGTH, HARDERROR_OVERRIDE_ERRORMODE, HardErrorState, IS_SYSTEM_THREAD, KeGetPreviousMode, KeQuerySystemTime(), KernelMode, LPC_ERROR_EVENT, LpcRequestWaitReplyPortEx(), NT_ERROR, NT_SUCCESS, NULL, OptionShutdownSystem, PAGED_CODE, PORT_TOTAL_MAXIMUM_MESSAGE_LENGTH, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PsGetCurrentProcess(), PsGetCurrentThread(), ResponseAbort, ResponseCancel, ResponseContinue, ResponseIgnore, ResponseNo, ResponseNotHandled, ResponseOk, ResponseRetry, ResponseReturnToCaller, ResponseTryAgain, ResponseYes, RTL_ERRORMODE_FAILCRITICALERRORS, RtlCopyMemory, SeShutdownPrivilege, SeSinglePrivilegeCheck(), SHUTDOWN, STARTING, Status, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, and TRUE.
Referenced by ExRaiseHardError(), and NtRaiseHardError().
VOID ExpSystemErrorHandler (IN NTSTATUS ErrorStatus, IN ULONG NumberOfParameters, IN ULONG UnicodeStringParameterMask, IN PULONG_PTR Parameters, IN BOOLEAN CallShutdown)
Definition at line 95 of file harderr.c.
References _snprintf(), ASSERT, _STRING::Buffer, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExPageLockHandle, FALSE, FATAL_UNHANDLED_HARD_ERROR, _MESSAGE_RESOURCE_ENTRY::Flags, KeBugCheckEx(), KeGetCurrentPrcb(), KiSaveProcessorControlState(), LANG_ENGLISH, _STRING::Length, MAKELANGID, MAXIMUM_HARDERROR_PARAMETERS, _STRING::MaximumLength, MESSAGE_RESOURCE_UNICODE, MmLockPageableSectionByHandle(), NlsMbCodePageTag, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, PoShutdownBugCheck(), PsSystemDllDllBase, RtlAnsiStringToUnicodeString(), RtlCaptureContext(), RtlCopyMemory, RtlFindMessage(), RtlInitAnsiString(), RtlInitUnicodeString(), RtlUnicodeStringToAnsiSize, RtlUnicodeStringToAnsiString(), RtlUnicodeStringToOemSize, RtlUnicodeStringToOemString(), RtlZeroMemory, Status, strcat(), strcpy(), strlen(), SUBLANG_ENGLISH_US, _MESSAGE_RESOURCE_ENTRY::Text, and TRUE.
Referenced by ExpRaiseHardError().
NTSTATUS ExRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
Definition at line 747 of file harderr.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, except, EXCEPTION_EXECUTE_HANDLER, ExpRaiseHardError(), ExpTooLateForErrors, MAXIMUM_HARDERROR_PARAMETERS, _UNICODE_STRING::MaximumLength, MEM_COMMIT, MEM_RELEASE, NT_SUCCESS, NtCurrentProcess, NULL, PAGE_READWRITE, PAGED_CODE, ResponseNotHandled, RtlCopyMemory, Status, STATUS_SUCCESS, ZwAllocateVirtualMemory(), and ZwFreeVirtualMemory().
Referenced by CmpDiskFullWarningWorker(), CmpLoadHiveThread(), CmpQuotaWarningWorker(), CmpRaiseSelfHealWarningWorker(), CmpSystemQuotaWarningWorker(), IopHardErrorThread(), IopRaiseHardError(), IopRaiseInformationalHardError(), and NtRaiseHardError().
NTSTATUS NtRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
Definition at line 606 of file harderr.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, DbgPrint(), except, EXCEPTION_EXECUTE_HANDLER, ExpRaiseHardError(), ExRaiseHardError(), KdDebuggerEnabled, KeGetPreviousMode, KernelMode, MAXIMUM_HARDERROR_PARAMETERS, _UNICODE_STRING::MaximumLength, NOTHING, OptionAbortRetryIgnore, OptionCancelTryContinue, OptionOk, OptionOkCancel, OptionOkNoWait, OptionRetryCancel, OptionShutdownSystem, OptionYesNo, OptionYesNoCancel, PAGED_CODE, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteUlong, RtlCopyMemory, Status, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_4, STATUS_SUCCESS, and STATUS_SYSTEM_IMAGE_BAD_SIGNATURE.
Referenced by PsLocateSystemDll().
NTSTATUS NtSetDefaultHardErrorPort (__in HANDLE DefaultHardErrorPort)
Definition at line 918 of file harderr.c.
References ExpDefaultErrorPort, ExReadyForErrors, HardErrorState, KeGetPreviousMode, LpcPortObjectType, NT_SUCCESS, NULL, ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentProcess(), SeSinglePrivilegeCheck(), SeTcbPrivilege, STARTED, Status, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
Variable Documentation
HANDLE ExpDefaultErrorPort
Definition at line 73 of file harderr.c.
Referenced by ExpRaiseHardError(), and NtSetDefaultHardErrorPort().
PEPROCESS ExpDefaultErrorPortProcess
Definition at line 63 of file harderr.c.
BOOLEAN ExpTooLateForErrors = FALSE
Definition at line 72 of file harderr.c.
Referenced by ExRaiseHardError().
BOOLEAN ExReadyForErrors = FALSE
Definition at line 69 of file harderr.c.
Referenced by CmpCanGrowSystemHive(), CmpDiskFullWarning(), ExpRaiseHardError(), IopHardErrorThread(), IopRaiseHardError(), IopRaiseInformationalHardError(), and NtSetDefaultHardErrorPort().
ULONG HardErrorState = STARTING
Definition at line 71 of file harderr.c.
Referenced by ExpRaiseHardError(), FsRtlGetFileSize(), FsRtlSetFileSize(), and NtSetDefaultHardErrorPort().
PVOID PsSystemDllDllBase
Definition at line 116 of file psinit.c.
Referenced by ExpSystemErrorHandler().