Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivehint.c File Reference
hivehint.c File Reference
#include "cmp.h"
Macros
#define ROUND_INCREMENTS 0x100
#define ROUND_UP_NOZERO(a, b) (a)?ROUND_UP(a,b):(b)
Functions
VOID HvpAddFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
NTSTATUS HvpAdjustBitmap (IN PHHIVE Hive, IN ULONG HiveLength, IN OUT PFREE_DISPLAY FreeDisplay)
NTSTATUS HvpAdjustHiveFreeDisplay (IN PHHIVE Hive, IN ULONG HiveLength, IN HSTORAGE_TYPE Type)
BOOLEAN HvpCheckViewBoundary (IN ULONG Start, IN ULONG End)
HCELL_INDEX HvpFindFreeCell (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
HCELL_INDEX HvpFindFreeCellInBin (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, PHBIN Bin)
HCELL_INDEX HvpFindFreeCellInThisViewWindow (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
VOID HvpFreeHiveFreeDisplay (IN PHHIVE Hive)
VOID HvpRemoveFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
HCELL_INDEX HvpScanForFreeCellInViewWindow (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX FileOffsetStart)
Macro Definition Documentation
#define ROUND_INCREMENTS 0x100
Definition at line 112 of file hivehint.c.
Referenced by HvpAdjustBitmap().
#define ROUND_UP_NOZERO (a, b) (a)?ROUND_UP(a,b):(b)
Definition at line 111 of file hivehint.c.
Referenced by HvpAdjustBitmap().
Function Documentation
VOID HvpAddFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
Definition at line 256 of file hivehint.c.
References ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, Bin, _HMAP_ENTRY::BinAddress, CM_PAGED_CODE, _HBIN::FileOffset, HBIN_BASE, HBLOCK_SIZE, HvpGetCellMap(), Index, RtlSetBits(), _HBIN::Size, and VALIDATE_CELL_MAP.
Referenced by HvpEnlistFreeCell().
NTSTATUS HvpAdjustBitmap (IN PHHIVE Hive, IN ULONG HiveLength, IN OUT PFREE_DISPLAY FreeDisplay)
Definition at line 154 of file hivehint.c.
References _RTL_BITMAP::Buffer, CM_PAGED_CODE, HBLOCK_SIZE, NULL, ROUND_INCREMENTS, ROUND_UP_NOZERO, RtlClearBits(), RtlCopyMemory, RtlInitializeBitMap(), RtlZeroMemory, _RTL_BITMAP::SizeOfBitMap, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by HvpAdjustHiveFreeDisplay().
NTSTATUS HvpAdjustHiveFreeDisplay (IN PHHIVE Hive, IN ULONG HiveLength, IN HSTORAGE_TYPE Type)
Definition at line 69 of file hivehint.c.
References CM_PAGED_CODE, HHIVE_FREE_DISPLAY_SIZE, HvpAdjustBitmap(), NT_SUCCESS, Status, and STATUS_SUCCESS.
Referenced by HvFreeHivePartial(), HvInitializeHive(), HvLoadHive(), HvMapHive(), HvpAddBin(), HvRefreshHive(), and HvShrinkHive().
BOOLEAN HvpCheckViewBoundary (IN ULONG Start, IN ULONG End)
Definition at line 995 of file hivehint.c.
References CM_PAGED_CODE, CM_VIEW_SIZE, FALSE, HBLOCK_SIZE, and TRUE.
Referenced by HvpAddBin(), HvpCoalesceDiscardedBins(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpFindFreeCell(), HvpFindNextDirtyBlock(), HvpMapFileImageAndBuildMap(), HvpRecoverWholeHive(), and HvWriteHive().
HCELL_INDEX HvpFindFreeCell (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
Definition at line 866 of file hivehint.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, Cell, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_FREECELL, CONTAINING_RECORD, DPFLTR_CONFIG_ID, FALSE, _HBASE_BLOCK::FileName, FileOffset, _CMHIVE::GrowOffset, _CMHIVE::GrowOnlyMode, HBLOCK_SIZE, HCELL_NIL, HCELL_TYPE_MASK, HvGetCellType, HvpCheckViewBoundary(), HvpFindFreeCellInThisViewWindow(), _UNICODE_STRING::Length, RtlInitUnicodeString(), TRUE, and Volatile.
Referenced by HvpDoAllocateCell().
HCELL_INDEX HvpFindFreeCellInBin (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, PHBIN Bin)
Definition at line 433 of file hivehint.c.
References ASSERT, ASSERT_HIVE_WRITER_LOCK_OWNED, Bin, CM_PAGED_CODE, CmKdPrintEx, CML_FREECELL, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, _HBIN::FileOffset, HBLOCK_SIZE, HCELL_NIL, HCELL_TYPE_MASK, HvMarkCellDirty(), HvpComputeIndex, HvpDelistFreeCell(), RtlCheckBit, _HCELL::Size, _HBIN::Size, and TRUE.
Referenced by HvpScanForFreeCellInViewWindow().
HCELL_INDEX HvpFindFreeCellInThisViewWindow (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
Definition at line 724 of file hivehint.c.
References ASSERT, Cell, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_FREECELL, CmpFindFirstSetRight, _FREE_DISPLAY::Display, DPFLTR_CONFIG_ID, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, HBLOCK_SIZE, HCELL_NIL, HCELL_TYPE_MASK, HHIVE_FREE_DISPLAY_SIZE, HvpScanForFreeCellInViewWindow(), Index, _HHIVE::_DUAL::Length, RtlAreBitsClear(), and _HHIVE::Storage.
Referenced by HvpFindFreeCell().
VOID HvpFreeHiveFreeDisplay (IN PHHIVE Hive)
Definition at line 115 of file hivehint.c.
References ASSERT, CM_PAGED_CODE, HHIVE_FREE_DISPLAY_SIZE, NULL, RtlInitializeBitMap(), Stable, and Volatile.
Referenced by CmpInitializeHive(), and HvFreeHive().
VOID HvpRemoveFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
Definition at line 308 of file hivehint.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, Bin, _HMAP_ENTRY::BinAddress, CM_PAGED_CODE, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBIN::FileOffset, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HvpComputeIndex, HvpGetCellMap(), Index, RtlClearBits(), RtlNumberOfSetBits(), _HCELL::Size, _HBIN::Size, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvpDelistFreeCell().
HCELL_INDEX HvpScanForFreeCellInViewWindow (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX FileOffsetStart)
Definition at line 560 of file hivehint.c.
References ASSERT, Bin, Cell, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_FREECELL, CmLockHiveViews, CmpDereferenceHiveViewWithLock(), CmpMapThisBin(), CmpReferenceHiveView(), CmUnlockHiveViews, _FREE_DISPLAY::Display, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _HHIVE::_DUAL::FreeDisplay, HBIN_BASE, HBLOCK_SIZE, HCELL_NIL, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvpFindFreeCellInBin(), HvpGetCellMap(), _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, RtlAreBitsClear(), _HBIN::Size, _FREE_HBIN::Size, _HHIVE::Storage, and VALIDATE_CELL_MAP.
Referenced by HvpFindFreeCellInThisViewWindow().