Windows Research Kernel v1.2: C:/Windows Research Kernel/se/sepaudit.c File Reference
sepaudit.c File Reference
#include "pch.h"
#include <msaudite.h>
#include <string.h>
Data Structures
struct in_addr
struct sockaddr_in
Macros
#define s_addr S_un.S_addr
#define s_host S_un.S_un_b.s_b2
#define s_imp S_un.S_un_w.s_w2
#define s_impno S_un.S_un_b.s_b4
#define s_lh S_un.S_un_b.s_b3
#define s_net S_un.S_un_b.s_b1
#define SepSetParmTypeAccessMask(AuditParameters, Index, AccessMask, ObjectTypeIndex)
#define SepSetParmTypeFileSpec(AuditParameters, Index, String)
#define SepSetParmTypeHexUlong(AuditParameters, Index, Ulong)
#define SepSetParmTypeLogonId(AuditParameters, Index, LogonId)
#define SepSetParmTypeNoLogon(AuditParameters, Index)
#define SepSetParmTypeObjectTypes(AuditParameters, Index, ObjectTypes, ObjectTypeCount, ObjectTypeIndex)
#define SepSetParmTypePrivileges(AuditParameters, Index, Privileges)
#define SepSetParmTypePtr(AuditParameters, Index, Ptr)
#define SepSetParmTypeSid(AuditParameters, Index, Sid)
#define SepSetParmTypeString(AuditParameters, Index, String)
#define SepSetParmTypeTime(AuditParameters, Index, Time)
#define SepSetParmTypeUlong(AuditParameters, Index, Ulong)
Typedefs
typedef struct sockaddr_in * PSOCKADDR_IN
typedef struct sockaddr_in SOCKADDR_IN
Functions
VOID SeAuditHandleDuplication (__in PVOID SourceHandle, __in PVOID NewHandle, __in PEPROCESS SourceProcess, __in PEPROCESS TargetProcess)
VOID SeAuditHardLinkCreation (__in PUNICODE_STRING FileName, __in PUNICODE_STRING LinkName, __in BOOLEAN bSuccess)
VOID SeAuditLPCInvalidUse (__in PUNICODE_STRING LpcCallName, __in PUNICODE_STRING LpcServerPort)
VOID SeAuditProcessCreation (__in PEPROCESS Process)
VOID SeAuditProcessExit (__in PEPROCESS Process)
VOID SeAuditSystemTimeChange (__in LARGE_INTEGER OldTime, __in LARGE_INTEGER NewTime)
BOOLEAN FASTCALL SeDetailedAuditingWithToken (__in_opt PACCESS_TOKEN AccessToken)
NTSTATUS SeInitializeProcessAuditName (__in __typefix(PFILE_OBJECT) PVOID FileObject, __in BOOLEAN bIgnoreAuditPolicy, __deref_out POBJECT_NAME_INFORMATION *pAuditName)
NTSTATUS SeLocateProcessImageName (__in PEPROCESS Process, __deref_out PUNICODE_STRING *pImageFileName)
VOID SeOperationAuditAlarm (__in_opt PUNICODE_STRING CapturedSubsystemName, __in PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in ACCESS_MASK AuditMask, __in_opt PSID UserSid)
BOOLEAN SepAdtAuditThisEventWithContext (IN POLICY_AUDIT_EVENT_TYPE Category, IN BOOLEAN AccessGranted, IN BOOLEAN AccessDenied, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext OPTIONAL)
VOID SepAdtCloseObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
VOID SepAdtDeleteObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
VOID SepAdtGenerateDiscardAudit (VOID)
VOID SepAdtObjectReferenceAuditAlarm (IN PVOID Object, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted)
BOOLEAN SepAdtOpenObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId OPTIONAL, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName OPTIONAL, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID, IN POLICY_AUDIT_EVENT_TYPE AuditType, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PACCESS_MASK GrantedAccessArray OPTIONAL)
BOOLEAN SepAdtOpenObjectForDeleteAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId OPTIONAL, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName OPTIONAL, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID)
VOID SepAdtPrivilegedServiceAuditAlarm (IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN PUNICODE_STRING CapturedSubsystemName, IN PUNICODE_STRING CapturedServiceName, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
BOOLEAN SepAdtPrivilegeObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName OPTIONAL, IN PVOID HandleId, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PVOID ProcessId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
VOID SepAuditAssignPrimaryToken (IN PEPROCESS Process, IN PACCESS_TOKEN AccessToken)
POBJECT_NAME_INFORMATION SepQueryNameString (IN PVOID Object)
PUNICODE_STRING SepQueryTypeString (IN PVOID Object)
NTSTATUS SeReportSecurityEvent (__in ULONG Flags, __in PUNICODE_STRING SourceName, __in_opt PSID UserSid, __in PSE_ADT_PARAMETER_ARRAY AuditParameters)
NTSTATUS SeSetAuditParameter (__inout PSE_ADT_PARAMETER_ARRAY AuditParameters, __in SE_ADT_PARAMETER_TYPE Type, __in ULONG Index, __in PVOID Data)
Macro Definition Documentation
#define s_addr S_un.S_addr
Definition at line 37 of file sepaudit.c.
#define s_host S_un.S_un_b.s_b2
Definition at line 39 of file sepaudit.c.
#define s_imp S_un.S_un_w.s_w2
Definition at line 43 of file sepaudit.c.
#define s_impno S_un.S_un_b.s_b4
Definition at line 45 of file sepaudit.c.
#define s_lh S_un.S_un_b.s_b3
Definition at line 47 of file sepaudit.c.
#define s_net S_un.S_un_b.s_b1
Definition at line 41 of file sepaudit.c.
#define SepSetParmTypeAccessMask (AuditParameters, Index, AccessMask, ObjectTypeIndex)
Value:
{                                                                        \
        ASSERT( (ObjectTypeIndex < Index) && L"SepSetParmTypeAccessMask" );  \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeAccessMask;\
        (AuditParameters).Parameters[(Index)].Length = sizeof( ACCESS_MASK );\
        (AuditParameters).Parameters[(Index)].Data[0] = (AccessMask);        \
        (AuditParameters).Parameters[(Index)].Data[1] = (ObjectTypeIndex);   \
    }
Definition at line 145 of file sepaudit.c.
Referenced by SeOperationAuditAlarm(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), and SepAdtOpenObjectForDeleteAuditAlarm().
#define SepSetParmTypeFileSpec (AuditParameters, Index, String)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeFileSpec;    \
        (AuditParameters).Parameters[(Index)].Length =                         \
                sizeof(UNICODE_STRING)+(String)->Length;                       \
        (AuditParameters).Parameters[(Index)].Address = (String);              \
    }
Definition at line 101 of file sepaudit.c.
Referenced by SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), and SepAuditAssignPrimaryToken().
#define SepSetParmTypeHexUlong (AuditParameters, Index, Ulong)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeHexUlong;    \
        (AuditParameters).Parameters[(Index)].Length =  sizeof( (Ulong) );     \
        (AuditParameters).Parameters[(Index)].Data[0] = (ULONG)(Ulong);        \
    }
Definition at line 116 of file sepaudit.c.
Referenced by SeOperationAuditAlarm(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), and SepAdtOpenObjectForDeleteAuditAlarm().
#define SepSetParmTypeLogonId (AuditParameters, Index, LogonId)
Value:
{                                                                        \
        LUID * TmpLuid;                                                      \
                                                                             \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeLogonId;   \
        (AuditParameters).Parameters[(Index)].Length =  sizeof( (LogonId) ); \
        TmpLuid = (LUID *)(&(AuditParameters).Parameters[(Index)].Data[0]);  \
        *TmpLuid = (LogonId);                                                \
    }
Definition at line 135 of file sepaudit.c.
Referenced by SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SepAuditAssignPrimaryToken().
#define SepSetParmTypeNoLogon (AuditParameters, Index)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeNoLogonId;   \
    }
Definition at line 130 of file sepaudit.c.
Referenced by SeAuditLPCInvalidUse(), SeAuditSystemTimeChange(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), and SepAdtPrivilegeObjectAuditAlarm().
#define SepSetParmTypeObjectTypes (AuditParameters, Index, ObjectTypes, ObjectTypeCount, ObjectTypeIndex)
Value:
{                                                                               \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeObjectTypes;            \
        (AuditParameters).Parameters[(Index)].Length = sizeof( SE_ADT_OBJECT_TYPE ) * (ObjectTypeCount);\
        (AuditParameters).Parameters[(Index)].Address = (ObjectTypes);                    \
        (AuditParameters).Parameters[(Index)].Data[1] = (ObjectTypeIndex);               \
    }
Definition at line 163 of file sepaudit.c.
Referenced by SepAdtOpenObjectAuditAlarm().
#define SepSetParmTypePrivileges (AuditParameters, Index, Privileges)
Value:
{                                                                                       \
        ASSERT( Privileges->PrivilegeCount <= SEP_MAX_PRIVILEGE_COUNT ); \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypePrivs;                    \
        (AuditParameters).Parameters[(Index)].Length = SepPrivilegeSetSize( (Privileges) ); \
        (AuditParameters).Parameters[(Index)].Address = (Privileges);                       \
    }
Definition at line 155 of file sepaudit.c.
Referenced by SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), and SepAdtPrivilegeObjectAuditAlarm().
#define SepSetParmTypePtr (AuditParameters, Index, Ptr)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypePtr;         \
        (AuditParameters).Parameters[(Index)].Length =  sizeof( ULONG_PTR );   \
        (AuditParameters).Parameters[(Index)].Data[0] = (ULONG_PTR)(Ptr);      \
    }
Definition at line 123 of file sepaudit.c.
Referenced by SeAuditHandleDuplication(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SepAuditAssignPrimaryToken().
#define SepSetParmTypeSid (AuditParameters, Index, Sid)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeSid;         \
        (AuditParameters).Parameters[(Index)].Length = SeLengthSid( (Sid) );   \
        (AuditParameters).Parameters[(Index)].Address = (Sid);                 \
    }
Definition at line 85 of file sepaudit.c.
Referenced by SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and SeReportSecurityEvent().
#define SepSetParmTypeString (AuditParameters, Index, String)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeString;      \
        (AuditParameters).Parameters[(Index)].Length =                         \
                sizeof(UNICODE_STRING)+(String)->Length;                       \
        (AuditParameters).Parameters[(Index)].Address = (String);              \
    }
Definition at line 93 of file sepaudit.c.
Referenced by SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and SeReportSecurityEvent().
#define SepSetParmTypeTime (AuditParameters, Index, Time)
Value:
{                                                                                 \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeTime;               \
        (AuditParameters).Parameters[(Index)].Length =  sizeof( (Time) );             \
        *((PLARGE_INTEGER)(&(AuditParameters).Parameters[(Index)].Data[0])) = Time;   \
    }
Definition at line 172 of file sepaudit.c.
Referenced by SeAuditSystemTimeChange().
#define SepSetParmTypeUlong (AuditParameters, Index, Ulong)
Value:
{                                                                          \
        (AuditParameters).Parameters[(Index)].Type = SeAdtParmTypeUlong;       \
        (AuditParameters).Parameters[(Index)].Length =  sizeof( (Ulong) );     \
        (AuditParameters).Parameters[(Index)].Data[0] = (ULONG)(Ulong);        \
    }
Definition at line 109 of file sepaudit.c.
Referenced by SepAdtGenerateDiscardAudit(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), and SeReportSecurityEvent().
Typedef Documentation
typedef struct sockaddr_in * PSOCKADDR_IN
typedef struct sockaddr_in SOCKADDR_IN
Function Documentation
VOID SeAuditHandleDuplication (__in PVOID SourceHandle, __in PVOID NewHandle, __in PEPROCESS SourceProcess, __in PEPROCESS TargetProcess)
Definition at line 2775 of file sepaudit.c.
References ASSERT, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, PAGED_CODE, PsProcessAuditId, RtlZeroMemory, SE_AUDITID_DUPLICATE_HANDLE, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeCaptureSubjectContext(), SepAdtLogAuditRecord(), SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenUserSid, SeReleaseSubjectContext(), and SeSubsystemName.
Referenced by ObAuditInheritedHandleProcedure(), and ObDuplicateObject().
VOID SeAuditHardLinkCreation (__in PUNICODE_STRING FileName, __in PUNICODE_STRING LinkName, __in BOOLEAN bSuccess)
Definition at line 3681 of file sepaudit.c.
References ASSERT, _SE_ADT_PARAMETER_ARRAY::AuditId, _SE_ADT_PARAMETER_ARRAY::CategoryId, EffectiveToken, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, PAGED_CODE, _SE_ADT_PARAMETER_ARRAY::ParameterCount, SE_AUDITID_HARDLINK_CREATION, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeCaptureSubjectContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, and _SE_ADT_PARAMETER_ARRAY::Type.
VOID SeAuditLPCInvalidUse (__in PUNICODE_STRING LpcCallName, __in PUNICODE_STRING LpcServerPort)
Definition at line 3460 of file sepaudit.c.
References ASSERT, AuditCategorySystem, _SECURITY_SUBJECT_CONTEXT::ClientToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NULL, NullString, PAGED_CODE, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_LPC_INVALID_USE, SE_CATEGID_SYSTEM, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and TRUE.
VOID SeAuditProcessCreation (__in PEPROCESS Process)
Definition at line 2662 of file sepaudit.c.
References ASSERT, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NullString, PAGED_CODE, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, RtlZeroMemory, SE_AUDITID_PROCESS_CREATED, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, and Status.
Referenced by PspCreateProcess().
VOID SeAuditProcessExit (__in PEPROCESS Process)
Definition at line 2855 of file sepaudit.c.
References ASSERT, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NullString, PAGED_CODE, PsDereferencePrimaryToken, PsProcessAuditId, PsReferencePrimaryToken(), RtlZeroMemory, SE_AUDITID_PROCESS_EXIT, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, and Status.
Referenced by PspExitThread().
VOID SeAuditSystemTimeChange (__in LARGE_INTEGER OldTime, __in LARGE_INTEGER NewTime)
Definition at line 3573 of file sepaudit.c.
References ASSERT, AuditCategorySystem, _SECURITY_SUBJECT_CONTEXT::ClientToken, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NullString, PAGED_CODE, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_SYSTEM_TIME_CHANGE, SE_CATEGID_SYSTEM, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeTime, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and TRUE.
BOOLEAN FASTCALL SeDetailedAuditingWithToken (__in_opt PACCESS_TOKEN AccessToken)
Definition at line 181 of file sepaudit.c.
References ARGUMENT_PRESENT, AuditCategoryDetailedTracking, _SE_AUDITING_STATE::AuditOnSuccess, _TOKEN::AuditPolicy, _SEP_AUDIT_POLICY_CATEGORIES::DetailedTracking, EffectiveToken, FALSE, NULL, PAGED_CODE, _SEP_AUDIT_POLICY::PolicyElements, SeAuditingState, SeCaptureSubjectContext(), SepAuditFailed(), SepTokenPolicyCounter, SeReleaseSubjectContext(), STATUS_NO_TOKEN, TOKEN_AUDIT_SUCCESS_EXCLUDE, TOKEN_AUDIT_SUCCESS_INCLUDE, and TRUE.
Referenced by ObDuplicateObject(), ObInitProcess(), PspCreateProcess(), PspExitThread(), SeAssignPrimaryToken(), and SeExchangePrimaryToken().
NTSTATUS SeInitializeProcessAuditName (__in __typefix(PFILE_OBJECT) PVOID FileObject, __in BOOLEAN bIgnoreAuditPolicy, __deref_out POBJECT_NAME_INFORMATION * pAuditName)
Definition at line 2996 of file sepaudit.c.
References ASSERT, AuditCategoryDetailedTracking, AuditCategoryObjectAccess, DbgPrint(), ExAllocatePoolWithTag, ExFreePool(), FALSE, NonPagedPool, NT_SUCCESS, NULL, ObQueryNameString(), PAGED_CODE, RtlZeroMemory, SepAdtAuditThisEventWithContext(), Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by MmInitializeProcessAddressSpace(), and SeLocateProcessImageName().
NTSTATUS SeLocateProcessImageName (__in PEPROCESS Process, __deref_out PUNICODE_STRING * pImageFileName)
Definition at line 3206 of file sepaudit.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), InterlockedCompareExchangePointer, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PsReferenceProcessFilePointer(), RtlCopyMemory, SeInitializeProcessAuditName(), Status, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by ExpGetProcessInformation(), NtQueryInformationProcess(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and WmiTraceProcess().
VOID SeOperationAuditAlarm (__in_opt PUNICODE_STRING CapturedSubsystemName, __in PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in ACCESS_MASK AuditMask, __in_opt PSID UserSid)
Definition at line 2092 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_OBJECT_ACCESS, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeAccessMask, SepSetParmTypeFileSpec, SepSetParmTypeHexUlong, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and TRUE.
Referenced by ObpAuditObjectAccess().
BOOLEAN SepAdtAuditThisEventWithContext (IN POLICY_AUDIT_EVENT_TYPE Category, IN BOOLEAN AccessGranted, IN BOOLEAN AccessDenied, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext OPTIONAL)
Definition at line 282 of file sepaudit.c.
References _SEP_AUDIT_POLICY_CATEGORIES::AccountLogon, _SEP_AUDIT_POLICY_CATEGORIES::AccountManagement, ARGUMENT_PRESENT, ASSERT, AuditCategoryAccountLogon, AuditCategoryAccountManagement, AuditCategoryDetailedTracking, AuditCategoryDirectoryServiceAccess, AuditCategoryLogon, AuditCategoryObjectAccess, AuditCategoryPolicyChange, AuditCategoryPrivilegeUse, AuditCategorySystem, _TOKEN::AuditPolicy, _SEP_AUDIT_POLICY_CATEGORIES::DetailedTracking, _SEP_AUDIT_POLICY_CATEGORIES::DirectoryServiceAccess, EffectiveToken, FALSE, _SEP_AUDIT_POLICY_CATEGORIES::Logon, NULL, _SEP_AUDIT_POLICY_CATEGORIES::ObjectAccess, PAGED_CODE, _SEP_AUDIT_POLICY_CATEGORIES::PolicyChange, _SEP_AUDIT_POLICY::PolicyElements, _SEP_AUDIT_POLICY_CATEGORIES::PrivilegeUse, SeAuditingState, SeCaptureSubjectContext(), SepAuditFailed(), SepTokenPolicyCounter, SeReleaseSubjectContext(), STATUS_NO_TOKEN, _SEP_AUDIT_POLICY_CATEGORIES::System, TOKEN_AUDIT_FAILURE_EXCLUDE, TOKEN_AUDIT_FAILURE_INCLUDE, TOKEN_AUDIT_SUCCESS_EXCLUDE, TOKEN_AUDIT_SUCCESS_INCLUDE, and TRUE.
Referenced by NtOpenObjectAuditAlarm(), SeAuditingFileEventsWithContext(), SeAuditingFileOrGlobalEvents(), SeAuditingHardLinkEventsWithContext(), SeAuditLPCInvalidUse(), SeAuditSystemTimeChange(), SeInitializeProcessAuditName(), SeObjectReferenceAuditAlarm(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SeReportSecurityEvent().
VOID SepAdtCloseObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
Definition at line 1742 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryObjectAccess, _SEP_AUDIT_OPTIONS::DoNotAuditCloseObjectEvents, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_CLOSE_HANDLE, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepAuditOptions, SepSetParmTypeFileSpec, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SeSubsystemName, Status, and TRUE.
Referenced by NtCloseObjectAuditAlarm(), and SeCloseObjectAuditAlarm().
VOID SepAdtDeleteObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
Definition at line 1924 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryObjectAccess, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_DELETE_OBJECT, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SeSubsystemName, Status, STATUS_SUCCESS, and TRUE.
Referenced by NtDeleteObjectAuditAlarm(), and SeDeleteObjectAuditAlarm().
VOID SepAdtGenerateDiscardAudit (VOID)
Definition at line 2940 of file sepaudit.c.
References ASSERT, EVENTLOG_AUDIT_SUCCESS, PAGED_CODE, RtlZeroMemory, SE_AUDITID_AUDITS_DISCARDED, SE_CATEGID_SYSTEM, SeAdtParmTypeNone, SeLocalSystemSid, SepAdtCountEventsDiscarded, SepAdtLogAuditRecord(), SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, and SeSubsystemName.
Referenced by SepQueueWorkItem().
VOID SepAdtObjectReferenceAuditAlarm (IN PVOID Object, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted)
Definition at line 2306 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), _OBJECT_NAME_INFORMATION::Name, NULL, ObjectNameInformation, ObjectTypeInformation, PAGED_CODE, RtlZeroMemory, SE_AUDITID_INDIRECT_REFERENCE, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SepAdtLogAuditRecord(), SepQueryNameString(), SepQueryTypeString(), SepSetParmTypeAccessMask, SepSetParmTypeHexUlong, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, and SeSubsystemName.
Referenced by SeObjectReferenceAuditAlarm().
BOOLEAN SepAdtOpenObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId OPTIONAL, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName OPTIONAL, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID, IN POLICY_AUDIT_EVENT_TYPE AuditType, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PACCESS_MASK GrantedAccessArray OPTIONAL)
Definition at line 910 of file sepaudit.c.
References _SE_ADT_OBJECT_TYPE::AccessMask, ARGUMENT_PRESENT, ASSERT, AuditCategoryDirectoryServiceAccess, AuditCategoryObjectAccess, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, ExAllocatePoolWithTag, ExFreePool(), _SE_ADT_OBJECT_TYPE::Flags, _SE_ADT_OBJECT_TYPE::Level, NT_SUCCESS, NULL, NullString, OBJECT_FAILURE_AUDIT, OBJECT_SUCCESS_AUDIT, _SE_ADT_OBJECT_TYPE::ObjectType, PAGED_CODE, PagedPool, PsGetCurrentProcess(), RtlZeroMemory, SE_ADT_OBJECT_ONLY, SE_AUDITID_OPEN_HANDLE, SE_AUDITID_OPEN_HANDLE_OBJECT_TYPE, SE_CATEGID_DS_ACCESS, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeAccessMask, SepSetParmTypeFileSpec, SepSetParmTypeHexUlong, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypeObjectTypes, SepSetParmTypePrivileges, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtOpenObjectAuditAlarm(), SeAuditHandleCreation(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SepAdtOpenObjectForDeleteAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId OPTIONAL, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName OPTIONAL, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID)
Definition at line 1412 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, NULL, PAGED_CODE, RtlZeroMemory, SE_AUDITID_OPEN_OBJECT_FOR_DELETE, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SepAdtLogAuditRecord(), SepSetParmTypeAccessMask, SepSetParmTypeFileSpec, SepSetParmTypeHexUlong, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePrivileges, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, and TRUE.
VOID SepAdtPrivilegedServiceAuditAlarm (IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN PUNICODE_STRING CapturedSubsystemName, IN PUNICODE_STRING CapturedServiceName, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
Definition at line 682 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryPrivilegeUse, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, NULL, PAGED_CODE, RtlZeroMemory, SE_AUDITID_PRIVILEGED_SERVICE, SE_CATEGID_PRIVILEGE_USE, SeAdtParmTypeNone, SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepFilterPrivilegeAudits(), SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePrivileges, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, and SeSubsystemName.
Referenced by NtPrivilegedServiceAuditAlarm(), and SePrivilegedServiceAuditAlarm().
BOOLEAN SepAdtPrivilegeObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName OPTIONAL, IN PVOID HandleId, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PVOID ProcessId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
Definition at line 449 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryPrivilegeUse, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, FALSE, NULL, PAGED_CODE, RtlEqualSid(), RtlZeroMemory, SE_AUDITID_PRIVILEGED_OBJECT, SE_CATEGID_PRIVILEGE_USE, SeAdtParmTypeNone, SeLocalSystemSid, SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepFilterPrivilegeAudits(), SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePrivileges, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, TRUE, and UNREFERENCED_PARAMETER.
Referenced by NtOpenObjectAuditAlarm(), NtPrivilegeObjectAuditAlarm(), SeAuditHandleCreation(), SepAccessCheckAndAuditAlarm(), and SePrivilegeObjectAuditAlarm().
VOID SepAuditAssignPrimaryToken (IN PEPROCESS Process, IN PACCESS_TOKEN AccessToken)
Definition at line 3319 of file sepaudit.c.
References ASSERT, EffectiveToken, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_ASSIGN_TOKEN, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SeCaptureSubjectContext(), SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepAuditFailed(), SepSetParmTypeFileSpec, SepSetParmTypeLogonId, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, STATUS_NO_TOKEN, and STATUS_SUCCESS.
Referenced by SeAssignPrimaryToken(), and SeExchangePrimaryToken().
POBJECT_NAME_INFORMATION SepQueryNameString (IN PVOID Object)
Definition at line 2518 of file sepaudit.c.
References ExAllocatePoolWithTag, ExFreePool(), _UNICODE_STRING::Length, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObQueryNameString(), PAGED_CODE, PagedPool, Status, and STATUS_INFO_LENGTH_MISMATCH.
Referenced by SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), and SepAdtObjectReferenceAuditAlarm().
PUNICODE_STRING SepQueryTypeString (IN PVOID Object)
Definition at line 2591 of file sepaudit.c.
References ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, ObQueryTypeName(), PAGED_CODE, PagedPool, Status, and STATUS_INFO_LENGTH_MISMATCH.
Referenced by SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), and SepAdtObjectReferenceAuditAlarm().
NTSTATUS SeReportSecurityEvent (__in ULONG Flags, __in PUNICODE_STRING SourceName, __in_opt PSID UserSid, __in PSE_ADT_PARAMETER_ARRAY AuditParameters)
Definition at line 3890 of file sepaudit.c.
References ASSERT, _SE_ADT_PARAMETER_ARRAY::AuditId, _SE_ADT_PARAMETER_ARRAY::CategoryId, EffectiveToken, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, FALSE, NT_SUCCESS, NULL, _SE_ADT_PARAMETER_ARRAY::ParameterCount, _SE_ADT_PARAMETER_ARRAY::Parameters, RtlCopyMemory, RtlValidateUnicodeString(), RtlValidSid(), RtlZeroMemory, SE_AUDITID_GENERIC_AUDIT_EVENT, SE_MAX_AUDIT_PARAMETERS, SE_MAX_GENERIC_AUDIT_PARAMETERS, SeCaptureSubjectContext(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, and _SE_ADT_PARAMETER_ARRAY::Type.
NTSTATUS SeSetAuditParameter (__inout PSE_ADT_PARAMETER_ARRAY AuditParameters, __in SE_ADT_PARAMETER_TYPE Type, __in ULONG Index, __in PVOID Data)
Definition at line 3760 of file sepaudit.c.
References Index, NT_SUCCESS, NULL, RtlCopyMemory, SeAdtParmTypeAccessMask, SeAdtParmTypeDateTime, SeAdtParmTypeDuration, SeAdtParmTypeFileSpec, SeAdtParmTypeGuid, SeAdtParmTypeHexInt64, SeAdtParmTypeHexUlong, SeAdtParmTypeLogonId, SeAdtParmTypeLuid, SeAdtParmTypeMessage, SeAdtParmTypeNoLogonId, SeAdtParmTypeNone, SeAdtParmTypeNoUac, SeAdtParmTypeObjectTypes, SeAdtParmTypePrivs, SeAdtParmTypePtr, SeAdtParmTypeSid, SeAdtParmTypeSidList, SeAdtParmTypeSockAddr, SeAdtParmTypeString, SeAdtParmTypeStringList, SeAdtParmTypeTime, SeAdtParmTypeUlong, SeAdtParmTypeUserAccountControl, SeLengthSid, SepPrivilegeSetSize, Status, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, and STATUS_SUCCESS.