Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/allproc.c File Reference
allproc.c File Reference
#include "ki.h"
#include "pool.h"
Macros
#define ROUNDUP16(x) (((x)+15) & ~15)
Enumerations
enum {
KcStartContinue, KcStartWait, KcStartGetId, KcStartDoNotStart,
KcStartCommandError = 0xff
}
Functions
VOID KeStartAllProcessors (VOID)
VOID KiAdjustSimultaneousMultiThreadingCharacteristics (VOID)
VOID KiAllProcessorsStarted (VOID)
VOID KiClearBusyBitInTssDescriptor (IN ULONG DescriptorOffset)
static VOID KiCloneDescriptor (IN PKDESCRIPTOR pSrcDescriptorInfo, IN PKDESCRIPTOR pDestDescriptorInfo, IN PVOID Base)
static VOID KiCloneSelector (IN ULONG SrcSelector, IN PKGDTENTRY pNGDT, IN PKDESCRIPTOR pDestDescriptor, IN PVOID Base)
VOID KiDummyDoubleFaultHandler (VOID)
VOID KiDummyNmiHandler (VOID)
VOID KiHaltThisProcessor (VOID)
BOOLEAN KiInitProcessor (ULONG NewProcessorNumber, PUCHAR pNodeNumber, ULONG IdtOffset, ULONG GdtOffset, SIZE_T ProcessorDataSize)
PKPRCB KiInitProcessorState (PKPROCESSOR_STATE pProcessorState, PVOID PerProcessorAllocation, ULONG NewProcessorNumber, UCHAR NodeNumber, ULONG IdtOffset, ULONG GdtOffset, PVOID *ppStack, PVOID *ppDpcStack)
VOID KiProcessorStart (VOID)
VOID KiSetHaltedNmiandDoubleFaultHandler (VOID)
BOOLEAN KiStartWaitAcknowledge (VOID)
Variables
ULONG KiBarrierWait = 0
enum { ... } KiProcessorStartControl = KcStartContinue
ULONG KiProcessorStartData [4]
BOOLEAN KiSMTProcessorsPresent
Macro Definition Documentation
#define ROUNDUP16 (x) (((x)+15) & ~15)
Definition at line 186 of file allproc.c.
Referenced by KeStartAllProcessors().
Enumeration Type Documentation
anonymous enum
Enumerator
KcStartContinue
KcStartWait
KcStartGetId
KcStartDoNotStart
KcStartCommandError
Definition at line 148 of file allproc.c.
Function Documentation
VOID KeStartAllProcessors (VOID)
Definition at line 420 of file allproc.c.
References ASSERT, DOUBLE_FAULT_STACK_SIZE, FIELD_OFFSET, KcStartContinue, KeAdjustInterruptTime(), KeFeatureBits, KeLoaderBlock, KeNodeBlock, KeNumberNodes, KeYieldProcessor, KF_WORKING_PTE, KiAllProcessorsStarted(), KiBarrierWait, KiInitProcessor(), KiNode0, KiNodeInit, KiProcessorStartControl, KiQueryProcessorNode, _DESCRIPTOR::Limit, _LOADER_PARAMETER_BLOCK::LoadOptions, MAXIMUM_PROCESSORS, NT_SUCCESS, NULL, _LOADER_PARAMETER_BLOCK::Prcb, ROUNDUP16, Status, and strstr().
Referenced by Phase1InitializationDiscard().
VOID KiAdjustSimultaneousMultiThreadingCharacteristics (VOID)
Definition at line 723 of file allproc.c.
References ASSERT, _KPRCB::InitialApicId, KeFindFirstSetLeftMember(), KeNumberProcessors, KiProcessorBlock, KiSMTProcessorsPresent, _KPRCB::LogicalProcessorsPerPhysicalProcessor, _KPRCB::MultiThreadProcessorSet, NULL, _KPRCB::Number, and _KPRCB::ParentNode.
Referenced by KiAllProcessorsStarted().
VOID KiAllProcessorsStarted (VOID)
Definition at line 854 of file allproc.c.
References ExAllocatePoolWithTag, KeActiveProcessors, KeNodeBlock, KeNumberNodes, KeNumberProcessors, KiAdjustSimultaneousMultiThreadingCharacteristics(), KiNodeInit, KiProcessorBlock, MAXIMUM_CCNUMA_NODES, MmSecondaryColorMask, _KPRCB::NodeColor, _KPRCB::NodeShiftedColor, NonPagedPool, NULL, _KPRCB::ParentNode, and _KPRCB::SecondaryColorMask.
Referenced by KeStartAllProcessors().
VOID KiClearBusyBitInTssDescriptor (IN ULONG DescriptorOffset)
Definition at line 1184 of file allproc.c.
References _KGDTENTRY::Bytes, _KPCR::GDT, _KGDTENTRY::HighWord, and KeGetPcr().
Referenced by KiDummyDoubleFaultHandler(), and KiDummyNmiHandler().
static VOID KiCloneDescriptor (IN PKDESCRIPTOR pSrcDescriptorInfo, IN PKDESCRIPTOR pDestDescriptorInfo, IN PVOID Base) static
Definition at line 687 of file allproc.c.
References RtlCopyMemory.
Referenced by KiCloneSelector(), and KiInitProcessorState().
static VOID KiCloneSelector (IN ULONG SrcSelector, IN PKGDTENTRY pNGDT, IN PKDESCRIPTOR pDestDescriptor, IN PVOID Base) static
Definition at line 623 of file allproc.c.
References ASSERT, _DESCRIPTOR::Base, _KGDTENTRY::BaseLow, _KGDTENTRY::Bits, GRAN_PAGE, _KGDTENTRY::HighWord, KiCloneDescriptor(), _DESCRIPTOR::Limit, _KGDTENTRY::LimitLow, and PAGE_SHIFT.
VOID KiDummyDoubleFaultHandler (VOID)
Definition at line 1155 of file allproc.c.
References DF_TSS_DESC_OFFSET, KiClearBusyBitInTssDescriptor(), and KiHaltThisProcessor().
Referenced by KiSetHaltedNmiandDoubleFaultHandler().
VOID KiDummyNmiHandler (VOID)
Definition at line 1124 of file allproc.c.
References KiClearBusyBitInTssDescriptor(), KiHaltThisProcessor(), and NMI_TSS_DESC_OFFSET.
Referenced by KiSetHaltedNmiandDoubleFaultHandler().
VOID KiHaltThisProcessor (VOID)
Definition at line 1215 of file allproc.c.
Referenced by KiDummyDoubleFaultHandler(), and KiDummyNmiHandler().
BOOLEAN KiInitProcessor (ULONG NewProcessorNumber, PUCHAR pNodeNumber, ULONG IdtOffset, ULONG GdtOffset, SIZE_T ProcessorDataSize)
Referenced by KeStartAllProcessors().
PKPRCB KiInitProcessorState (PKPROCESSOR_STATE pProcessorState, PVOID PerProcessorAllocation, ULONG NewProcessorNumber, UCHAR NodeNumber, ULONG IdtOffset, ULONG GdtOffset, PVOID * ppStack, PVOID * ppDpcStack)
Definition at line 189 of file allproc.c.
References _DESCRIPTOR::Base, _KSPECIAL_REGISTERS::Gdtr, KiCloneDescriptor(), _DESCRIPTOR::Limit, and _KPROCESSOR_STATE::SpecialRegisters.
VOID KiProcessorStart (VOID)
Definition at line 989 of file allproc.c.
References _disable(), CPUID(), KcStartCommandError, KcStartContinue, KcStartDoNotStart, KcStartGetId, KcStartWait, KeYieldProcessor, KiProcessorStartControl, KiProcessorStartData, KiSetHaltedNmiandDoubleFaultHandler(), and TRUE.
VOID KiSetHaltedNmiandDoubleFaultHandler (VOID)
Definition at line 1078 of file allproc.c.
References _KGDTENTRY::BaseLow, _KGDTENTRY::Bits, _KPCR::GDT, _KGDTENTRY::HighWord, _KPCR::IDT, IDT_DFH_VECTOR, IDT_NMI_VECTOR, KeGetPcr(), KiDummyDoubleFaultHandler(), KiDummyNmiHandler(), and _KIDTENTRY::Selector.
Referenced by KiProcessorStart().
BOOLEAN KiStartWaitAcknowledge (VOID)
Definition at line 1064 of file allproc.c.
References FALSE, KcStartCommandError, KcStartWait, KeYieldProcessor, KiProcessorStartControl, and TRUE.
Variable Documentation
ULONG KiBarrierWait = 0
Definition at line 158 of file allproc.c.
enum { ... } KiProcessorStartControl
Referenced by KeStartAllProcessors(), KiProcessorStart(), and KiStartWaitAcknowledge().
ULONG KiProcessorStartData[4]
Definition at line 156 of file allproc.c.
Referenced by KiProcessorStart().
BOOLEAN KiSMTProcessorsPresent
Referenced by KiAdjustSimultaneousMultiThreadingCharacteristics().