Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/fastio.c File Reference
fastio.c File Reference
#include "FsRtlP.h"
Macros
#define Dbg (0x04000000)
Functions
NTKERNELAPI VOID FsRtlAcquireFileExclusive (__in PFILE_OBJECT FileObject)
NTKERNELAPI NTSTATUS FsRtlAcquireFileExclusiveCommon (IN PFILE_OBJECT FileObject, IN FS_FILTER_SECTION_SYNC_TYPE SyncType, IN ULONG SectionPageProtection)
NTKERNELAPI VOID FsRtlAcquireFileForCcFlush (IN PFILE_OBJECT FileObject)
NTKERNELAPI NTSTATUS FsRtlAcquireFileForCcFlushEx (IN PFILE_OBJECT FileObject)
NTKERNELAPI BOOLEAN FsRtlAcquireFileForModWrite (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE *ResourceToRelease)
NTKERNELAPI NTSTATUS FsRtlAcquireFileForModWriteEx (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE *ResourceToRelease)
NTKERNELAPI NTSTATUS FsRtlAcquireToCreateMappedSection (IN PFILE_OBJECT FileObject, IN ULONG SectionPageProtection)
BOOLEAN FsRtlCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
BOOLEAN FsRtlCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __in_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
NTSTATUS FsRtlGetFileSize (__in PFILE_OBJECT FileObject, __inout PLARGE_INTEGER FileSize)
VOID FsRtlIncrementCcFastReadNotPossible (VOID)
VOID FsRtlIncrementCcFastReadNoWait (VOID)
VOID FsRtlIncrementCcFastReadResourceMiss (VOID)
VOID FsRtlIncrementCcFastReadWait (VOID)
BOOLEAN FsRtlMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
BOOLEAN FsRtlMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
BOOLEAN FsRtlMdlReadCompleteDev (__in PFILE_OBJECT FileObject, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
BOOLEAN FsRtlMdlReadDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
BOOLEAN FsRtlMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
BOOLEAN FsRtlMdlWriteCompleteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
BOOLEAN FsRtlPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
BOOLEAN FsRtlPrepareMdlWriteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS FsRtlRegisterFileSystemFilterCallbacks (__in PDRIVER_OBJECT FilterDriverObject, __in PFS_FILTER_CALLBACKS Callbacks)
NTKERNELAPI VOID FsRtlReleaseFile (__in PFILE_OBJECT FileObject)
NTKERNELAPI VOID FsRtlReleaseFileForCcFlush (IN PFILE_OBJECT FileObject)
NTKERNELAPI VOID FsRtlReleaseFileForModWrite (IN PFILE_OBJECT FileObject, IN PERESOURCE ResourceToRelease)
NTSTATUS FsRtlSetFileSize (IN PFILE_OBJECT FileObject, IN OUT PLARGE_INTEGER FileSize)
Macro Definition Documentation
#define Dbg (0x04000000)
Definition at line 51 of file fastio.c.
Function Documentation
NTKERNELAPI VOID FsRtlAcquireFileExclusive (__in PFILE_OBJECT FileObject)
Definition at line 3419 of file fastio.c.
References ASSERT, FsRtlAcquireFileExclusiveCommon(), NT_SUCCESS, PAGED_CODE, Status, and SyncTypeOther.
Referenced by CcSetPrivateWriteFile(), CcWriteBehind(), and CcZeroEndOfLastPage().
NTKERNELAPI NTSTATUS FsRtlAcquireFileExclusiveCommon (IN PFILE_OBJECT FileObject, IN FS_FILTER_SECTION_SYNC_TYPE SyncType, IN ULONG SectionPageProtection)
Definition at line 3521 of file fastio.c.
References _FAST_IO_DISPATCH::AcquireFileForNtCreateSection, _FS_FILTER_PARAMETERS::AcquireForSectionSynchronization, ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExAcquireResourceExclusiveLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlEnterFileSystem, FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FS_FILTER_PARAMETERS::PageProtection, _FS_FILTER_CALLBACK_DATA::Parameters, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, _FS_FILTER_PARAMETERS::SyncType, SyncTypeCreateSection, SyncTypeOther, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by FsRtlAcquireFileExclusive(), and FsRtlAcquireToCreateMappedSection().
NTKERNELAPI VOID FsRtlAcquireFileForCcFlush (IN PFILE_OBJECT FileObject)
Definition at line 2889 of file fastio.c.
References ASSERT, FsRtlAcquireFileForCcFlushEx(), NT_SUCCESS, PAGED_CODE, and Status.
NTKERNELAPI NTSTATUS FsRtlAcquireFileForCcFlushEx (IN PFILE_OBJECT FileObject)
Definition at line 2932 of file fastio.c.
References _FAST_IO_DISPATCH::AcquireForCcFlush, ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExIsResourceAcquiredSharedLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlEnterFileSystem, FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by FsRtlAcquireFileForCcFlush(), MiRemoveUnusedSegments(), MiShutdownSystem(), MmFlushSection(), and MmFlushVirtualMemory().
NTKERNELAPI BOOLEAN FsRtlAcquireFileForModWrite (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE * ResourceToRelease)
Definition at line 2173 of file fastio.c.
References FALSE, FsRtlAcquireFileForModWriteEx(), NT_SUCCESS, Status, and TRUE.
NTKERNELAPI NTSTATUS FsRtlAcquireFileForModWriteEx (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER EndingOffset, OUT PERESOURCE * ResourceToRelease)
Definition at line 2235 of file fastio.c.
References _FS_FILTER_PARAMETERS::AcquireForModifiedPageWriter, _FAST_IO_DISPATCH::AcquireForModWrite, ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, _FS_FILTER_PARAMETERS::EndingOffset, ExAcquireResourceExclusiveLite(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, _FSRTL_COMMON_FCB_HEADER::FileSize, FlagOn, _FSRTL_COMMON_FCB_HEADER::Flags, _FS_FILTER_CTRL::Flags, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FSRTL_FLAG_ACQUIRE_MAIN_RSRC_EX, FSRTL_FLAG_ACQUIRE_MAIN_RSRC_SH, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), _FSRTL_COMMON_FCB_HEADER::PagingIoResource, _FS_FILTER_CALLBACK_DATA::Parameters, _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, _FS_FILTER_PARAMETERS::ResourceToRelease, Status, STATUS_CANT_WAIT, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, VALID_FS_FILTER_CALLBACK_HANDLER, and _FSRTL_COMMON_FCB_HEADER::ValidDataLength.
Referenced by FsRtlAcquireFileForModWrite(), and MiMappedPageWriter().
NTKERNELAPI NTSTATUS FsRtlAcquireToCreateMappedSection (IN PFILE_OBJECT FileObject, IN ULONG SectionPageProtection)
Definition at line 3470 of file fastio.c.
References FsRtlAcquireFileExclusiveCommon(), PAGED_CODE, and SyncTypeCreateSection.
Referenced by FsRtlCreateSectionForDataScan(), and MmCreateSection().
BOOLEAN FsRtlCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 78 of file fastio.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, CcCopyRead(), CcFastCopyRead(), CcFastReadNotPossible, CcFastReadNoWait, CcFastReadResourceMiss, CcFastReadWait, ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, _FSRTL_COMMON_FCB_HEADER::FileSize, FO_FILE_FAST_IO_READ, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), _LARGE_INTEGER::HighPart, HOT_STATISTIC, IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, KeIsExecutingDpc(), _LARGE_INTEGER::LowPart, NULL, PAGED_CODE, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_END_OF_FILE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, and VOID.
BOOLEAN FsRtlCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in ULONG LockKey, __in_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 356 of file fastio.c.
References _FSRTL_COMMON_FCB_HEADER::AllocationSize, ASSERT, CcCanIWrite(), CcCopyWrite(), CcCopyWriteWontFlush, CcFastCopyWrite(), CcGetFileSizePointer, CcZeroData(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, FILE_WRITE_TO_END_OF_FILE, FileOffset, _FSRTL_COMMON_FCB_HEADER::FileSize, FlagOn, FO_FILE_MODIFIED, FO_FILE_SIZE_CHANGED, FO_WRITE_THROUGH, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), _LARGE_INTEGER::HighPart, IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, KeIsExecutingDpc(), _LARGE_INTEGER::LowPart, NULL, PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, _FSRTL_COMMON_FCB_HEADER::ValidDataLength, and VOID.
NTSTATUS FsRtlGetFileSize (__in PFILE_OBJECT FileObject, __inout PLARGE_INTEGER FileSize)
Definition at line 4038 of file fastio.c.
References _IO_STACK_LOCATION::DeviceObject, _FILE_STANDARD_INFORMATION::Directory, _FILE_STANDARD_INFORMATION::EndOfFile, Executive, FALSE, _FAST_IO_DISPATCH::FastIoQueryStandardInfo, _IO_STACK_LOCATION::FileObject, FileStandardInformation, HardErrorState, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoSetThreadHardErrorMode(), IRP_MJ_QUERY_INFORMATION, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), Status, _IO_STATUS_BLOCK::Status, STATUS_FILE_IS_A_DIRECTORY, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and TRUE.
Referenced by FsRtlCreateSectionForDataScan(), MiCreateDataFileMap(), MiCreateImageFileMap(), MmCreateSection(), and MmExtendSection().
VOID FsRtlIncrementCcFastReadNotPossible (VOID)
Definition at line 4375 of file fastio.c.
References CcFastReadNotPossible, and HOT_STATISTIC.
VOID FsRtlIncrementCcFastReadNoWait (VOID)
Definition at line 4416 of file fastio.c.
References CcFastReadNoWait, and HOT_STATISTIC.
VOID FsRtlIncrementCcFastReadResourceMiss (VOID)
Definition at line 4437 of file fastio.c.
References CcFastReadResourceMiss.
VOID FsRtlIncrementCcFastReadWait (VOID)
Definition at line 4395 of file fastio.c.
References CcFastReadWait, and HOT_STATISTIC.
BOOLEAN FsRtlMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 1305 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlMdlReadDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlRead, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
BOOLEAN FsRtlMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
Definition at line 1395 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlMdlReadCompleteDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlReadComplete, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
BOOLEAN FsRtlMdlReadCompleteDev (__in PFILE_OBJECT FileObject, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
Definition at line 1466 of file fastio.c.
References CcMdlReadComplete2(), TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlMdlReadComplete().
BOOLEAN FsRtlMdlReadDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 1092 of file fastio.c.
References ASSERT, CcFastMdlReadNotPossible, CcFastMdlReadWait, CcMdlRead(), ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, _FSRTL_COMMON_FCB_HEADER::FileSize, FO_FILE_FAST_IO_READ, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, KeIsExecutingDpc(), NULL, PAGED_CODE, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_END_OF_FILE, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by FsRtlMdlRead().
BOOLEAN FsRtlMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
Definition at line 1982 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlMdlWriteCompleteDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlWriteComplete, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
BOOLEAN FsRtlMdlWriteCompleteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain, __in PDEVICE_OBJECT DeviceObject)
Definition at line 2052 of file fastio.c.
References CcMdlWriteComplete2(), FALSE, FlagOn, FO_WRITE_THROUGH, TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlMdlWriteComplete().
BOOLEAN FsRtlPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 1892 of file fastio.c.
References FALSE, FIELD_OFFSET, FsRtlPrepareMdlWriteDev(), IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), NULL, _FAST_IO_DISPATCH::PrepareMdlWrite, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
BOOLEAN FsRtlPrepareMdlWriteDev (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG LockKey, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus, __in PDEVICE_OBJECT DeviceObject)
Definition at line 1504 of file fastio.c.
References _FSRTL_COMMON_FCB_HEADER::AllocationSize, ASSERT, CcCanIWrite(), CcGetFileSizePointer, CcPrepareMdlWrite(), CcZeroData(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), FALSE, _FAST_IO_DISPATCH::FastIoCheckIfPossible, FastIoIsNotPossible, FastIoIsQuestionable, FILE_WRITE_TO_END_OF_FILE, FileOffset, _FSRTL_COMMON_FCB_HEADER::FileSize, FlagOn, FO_FILE_MODIFIED, FO_FILE_SIZE_CHANGED, FO_WRITE_THROUGH, FSRTL_FAST_IO_TOP_LEVEL_IRP, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), _LARGE_INTEGER::HighPart, IoGetRelatedDeviceObject(), _FSRTL_COMMON_FCB_HEADER::IsFastIoPossible, NULL, PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_SUCCESS, _ETHREAD::TopLevelIrp, TRUE, UNREFERENCED_PARAMETER, _FSRTL_COMMON_FCB_HEADER::ValidDataLength, and VOID.
Referenced by FsRtlPrepareMdlWrite().
NTKERNELAPI NTSTATUS FsRtlRegisterFileSystemFilterCallbacks (__in PDRIVER_OBJECT FilterDriverObject, __in PFS_FILTER_CALLBACKS Callbacks)
Definition at line 2098 of file fastio.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, _DRIVER_EXTENSION::FsFilterCallbacks, FSRTL_FILTER_MEMORY_TAG, NonPagedPool, NULL, PAGED_CODE, RtlCopyMemory, _FS_FILTER_CALLBACKS::SizeOfFsFilterCallbacks, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTKERNELAPI VOID FsRtlReleaseFile (__in PFILE_OBJECT FileObject)
Definition at line 3820 of file fastio.c.
References ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FAST_IO_DISPATCH::ReleaseFileForNtCreateSection, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by CcDeleteSharedCacheMap(), CcSetPrivateWriteFile(), CcWriteBehind(), CcZeroEndOfLastPage(), FsRtlCreateSectionForDataScan(), and MmCreateSection().
NTKERNELAPI VOID FsRtlReleaseFileForCcFlush (IN PFILE_OBJECT FileObject)
Definition at line 3203 of file fastio.c.
References ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FS_FILTER_RELEASE_FOR_CC_FLUSH, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), FsRtlExitFileSystem, GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _FSRTL_COMMON_FCB_HEADER::PagingIoResource, _FAST_IO_DISPATCH::ReleaseForCcFlush, _FSRTL_COMMON_FCB_HEADER::Resource, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by MiRemoveUnusedSegments(), MiShutdownSystem(), MmFlushSection(), and MmFlushVirtualMemory().
NTKERNELAPI VOID FsRtlReleaseFileForModWrite (IN PFILE_OBJECT FileObject, IN PERESOURCE ResourceToRelease)
Definition at line 2676 of file fastio.c.
References ASSERT, _FS_FILTER_CTRL::Data, _FS_FILTER_CALLBACK_DATA::DeviceObject, ExReleaseResourceLite(), FALSE, _FS_FILTER_CALLBACK_DATA::FileObject, FlagOn, _FS_FILTER_CTRL::Flags, FS_FILTER_CHANGED_DEVICE_STACKS, FS_FILTER_HAVE_COMPLETIONS, FS_FILTER_RELEASE_FOR_MOD_WRITE, FsFilterCtrlFree(), FsFilterCtrlInit(), FsFilterPerformCallbacks(), FsFilterPerformCompletionCallbacks(), GET_FAST_IO_DISPATCH, GET_FS_FILTER_CALLBACKS, IoGetBaseFileSystemDeviceObject(), IoGetDeviceAttachmentBaseRef(), IoGetRelatedDeviceObject(), NT_SUCCESS, NULL, ObDereferenceObject(), _FS_FILTER_CALLBACK_DATA::Parameters, _FS_FILTER_PARAMETERS::ReleaseForModifiedPageWriter, _FAST_IO_DISPATCH::ReleaseForModWrite, _FS_FILTER_PARAMETERS::ResourceToRelease, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, TRUE, VALID_FAST_IO_DISPATCH_HANDLER, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by MiWriteComplete().
NTSTATUS FsRtlSetFileSize (IN PFILE_OBJECT FileObject, IN OUT PLARGE_INTEGER FileSize)
Definition at line 4226 of file fastio.c.
References _IO_STACK_LOCATION::DeviceObject, _FILE_END_OF_FILE_INFORMATION::EndOfFile, Executive, FALSE, FileEndOfFileInformation, _IO_STACK_LOCATION::FileObject, HardErrorState, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoSetThreadHardErrorMode(), IRP_MJ_SET_INFORMATION, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by MiCreateDataFileMap(), and MmExtendSection().