Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/abiosc.c File Reference
abiosc.c File Reference
#include "ki.h"
#include "abios.h"
Functions
NTSTATUS KeI386AbiosCall (IN USHORT LogicalId, IN PDRIVER_OBJECT DriverObject, IN PUCHAR RequestBlock, IN USHORT EntryPoint)
NTSTATUS KeI386AllocateGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
NTSTATUS KeI386FlatToGdtSelector (IN ULONG SelectorBase, IN USHORT Length, IN USHORT Selector)
NTSTATUS KeI386GetLid (IN USHORT DeviceId, IN USHORT RelativeLid, IN BOOLEAN SharedLid, IN PDRIVER_OBJECT DriverObject, OUT PUSHORT LogicalId)
NTSTATUS KeI386ReleaseGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
NTSTATUS KeI386ReleaseLid (IN USHORT LogicalId, IN PDRIVER_OBJECT DriverObject)
VOID Ki386InitializeGdtFreeList (PKFREE_GDT_ENTRY EndOfGdt)
ULONG KiI386SelectorBase (IN USHORT Selector)
VOID KiInitializeAbios (IN UCHAR Processor)
VOID KiInitializeAbiosGdtEntry (OUT PKGDTENTRY GdtEntry, IN ULONG Base, IN ULONG Limit, IN USHORT Type)
Variables
ULONG KiAbiosGdt [MAXIMUM_PROCESSORS]
KSPIN_LOCK KiAbiosGdtLock
KSPIN_LOCK KiAbiosLidTableLock
BOOLEAN KiAbiosPresent
PKCOMMON_DATA_AREA KiCommonDataArea
static PKFREE_GDT_ENTRY KiFreeGdtListHead = 0L
PKLID_TABLE_ENTRY KiLogicalIdTable
static USHORT KiNumberFreeSelectors = 0
ULONG KiStack16GdtEntry
Function Documentation
NTSTATUS KeI386AbiosCall (IN USHORT LogicalId, IN PDRIVER_OBJECT DriverObject, IN PUCHAR RequestBlock, IN USHORT EntryPoint)
Definition at line 364 of file abiosc.c.
References _KFUNCTION_TRANSFER_TABLE::CommonRoutine, KiAbiosPresent, KiI386CallAbios(), KiI386SelectorBase(), LID_NO_SPECIFIC_OWNER, _KCOMMON_DATA_AREA::NumberLids, _KABIOS_POINTER::Offset, _KABIOS_POINTER::Selector, STATUS_ABIOS_INVALID_COMMAND, STATUS_ABIOS_INVALID_LID, STATUS_ABIOS_NOT_LID_OWNER, STATUS_ABIOS_NOT_PRESENT, and STATUS_SUCCESS.
NTSTATUS KeI386AllocateGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
Definition at line 446 of file abiosc.c.
References ExAcquireSpinLock, ExReleaseSpinLock, _KFREE_GDT_ENTRY::Flink, KiAbiosGdt, KiAbiosGdtLock, KiFreeGdtListHead, KiNumberFreeSelectors, STATUS_ABIOS_SELECTOR_NOT_AVAILABLE, and STATUS_SUCCESS.
NTSTATUS KeI386FlatToGdtSelector (IN ULONG SelectorBase, IN USHORT Length, IN USHORT Selector)
Definition at line 555 of file abiosc.c.
References _KGDTENTRY::BaseLow, _KGDTENTRY::Bits, _KGDTENTRY::Bytes, DPL_SYSTEM, ExAcquireSpinLock, ExReleaseSpinLock, HIGHBYTE, HIGHWORD, _KGDTENTRY::HighWord, KeNumberProcessors, KiAbiosGdt, KiAbiosGdtLock, KiAbiosPresent, _KGDTENTRY::LimitLow, LOWBYTE, LOWWORD, RESERVED_GDT_ENTRIES, STATUS_ABIOS_INVALID_SELECTOR, STATUS_ABIOS_NOT_PRESENT, STATUS_SUCCESS, and TYPE_DATA.
NTSTATUS KeI386GetLid (IN USHORT DeviceId, IN USHORT RelativeLid, IN BOOLEAN SharedLid, IN PDRIVER_OBJECT DriverObject, OUT PUSHORT LogicalId)
Definition at line 167 of file abiosc.c.
References _KDB_FTT_SECTION::DeviceBlock, _KDEVICE_BLOCK::DeviceId, ExAcquireSpinLock, ExAllocatePoolWithTag, ExReleaseSpinLock, _KDB_FTT_SECTION::FunctionTransferTable, KiAbiosLidTableLock, KiAbiosPresent, KiI386SelectorBase(), LID_NO_SPECIFIC_OWNER, NonPagedPool, NULL, NUMBER_LID_TABLE_ENTRIES, _KCOMMON_DATA_AREA::NumberLids, _KABIOS_POINTER::Offset, _KLID_TABLE_ENTRY::Owner, _KLID_TABLE_ENTRY::OwnerCount, RtlZeroMemory, _KABIOS_POINTER::Selector, Status, STATUS_ABIOS_LID_ALREADY_OWNED, STATUS_ABIOS_LID_NOT_EXIST, STATUS_ABIOS_NOT_PRESENT, STATUS_NO_MEMORY, and STATUS_SUCCESS.
NTSTATUS KeI386ReleaseGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
Definition at line 504 of file abiosc.c.
References ExAcquireSpinLock, ExReleaseSpinLock, _KFREE_GDT_ENTRY::Flink, KiAbiosGdt, KiAbiosGdtLock, KiFreeGdtListHead, KiNumberFreeSelectors, and STATUS_SUCCESS.
NTSTATUS KeI386ReleaseLid (IN USHORT LogicalId, IN PDRIVER_OBJECT DriverObject)
Definition at line 305 of file abiosc.c.
References ExAcquireSpinLock, ExReleaseSpinLock, KiAbiosLidTableLock, KiAbiosPresent, LID_NO_SPECIFIC_OWNER, _KLID_TABLE_ENTRY::Owner, _KLID_TABLE_ENTRY::OwnerCount, Status, STATUS_ABIOS_NOT_LID_OWNER, STATUS_ABIOS_NOT_PRESENT, and STATUS_SUCCESS.
VOID Ki386InitializeGdtFreeList (PKFREE_GDT_ENTRY EndOfGdt)
Definition at line 619 of file abiosc.c.
References _KFREE_GDT_ENTRY::Flink, KiAbiosGetGdt(), KiFreeGdtListHead, KiNumberFreeSelectors, _KFREE_GDT_ENTRY::Present, and RESERVED_GDT_ENTRIES.
Referenced by KiInitializeAbios().
ULONG KiI386SelectorBase (IN USHORT Selector)
Definition at line 130 of file abiosc.c.
References _KGDTENTRY::BaseLow, _KGDTENTRY::Bits, _KGDTENTRY::Bytes, _KGDTENTRY::HighWord, and KiAbiosGetGdt().
Referenced by KeI386AbiosCall(), and KeI386GetLid().
VOID KiInitializeAbios (IN UCHAR Processor)
Definition at line 656 of file abiosc.c.
References _KGDTENTRY::Bits, _I386_LOADER_BLOCK::CommonDataArea, FALSE, _KGDTENTRY::HighWord, _LOADER_PARAMETER_BLOCK::I386, KeInitializeSpinLock(), KeLoaderBlock, KGDT_CDA16, KGDT_CODE16, KGDT_GDT_ALIAS, KGDT_STACK16, Ki386InitializeGdtFreeList(), KiAbiosGdt, KiAbiosGdtLock, KiAbiosGetGdt(), KiAbiosLidTableLock, KiAbiosPresent, KiEndOfCode16, KiI386CallAbios(), KiInitializeAbiosGdtEntry(), KiStack16GdtEntry, _KGDTENTRY::LimitLow, NULL, TRUE, TYPE_DATA, and _LOADER_PARAMETER_BLOCK::u.
VOID KiInitializeAbiosGdtEntry (OUT PKGDTENTRY GdtEntry, IN ULONG Base, IN ULONG Limit, IN USHORT Type)
Definition at line 80 of file abiosc.c.
Referenced by KiInitializeAbios().
Variable Documentation
ULONG KiAbiosGdt[MAXIMUM_PROCESSORS]
Definition at line 59 of file abiosc.c.
Referenced by KeI386AllocateGdtSelectors(), KeI386FlatToGdtSelector(), KeI386ReleaseGdtSelectors(), and KiInitializeAbios().
KSPIN_LOCK KiAbiosGdtLock
Definition at line 65 of file abiosc.c.
Referenced by KeI386AllocateGdtSelectors(), KeI386FlatToGdtSelector(), KeI386ReleaseGdtSelectors(), and KiInitializeAbios().
KSPIN_LOCK KiAbiosLidTableLock
Definition at line 71 of file abiosc.c.
Referenced by KeI386GetLid(), KeI386ReleaseLid(), and KiInitializeAbios().
BOOLEAN KiAbiosPresent
Referenced by KeI386AbiosCall(), KeI386FlatToGdtSelector(), KeI386GetLid(), KeI386ReleaseLid(), and KiInitializeAbios().
PKCOMMON_DATA_AREA KiCommonDataArea
PKFREE_GDT_ENTRY KiFreeGdtListHead = 0L static
Definition at line 47 of file abiosc.c.
Referenced by KeI386AllocateGdtSelectors(), KeI386ReleaseGdtSelectors(), and Ki386InitializeGdtFreeList().
PKLID_TABLE_ENTRY KiLogicalIdTable
Definition at line 53 of file abiosc.c.
USHORT KiNumberFreeSelectors = 0 static
Definition at line 41 of file abiosc.c.
Referenced by KeI386AllocateGdtSelectors(), KeI386ReleaseGdtSelectors(), and Ki386InitializeGdtFreeList().
ULONG KiStack16GdtEntry
Definition at line 77 of file abiosc.c.
Referenced by KiInitializeAbios().