Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obinsert.c File Reference
obinsert.c File Reference
#include "obp.h"
Functions
NTSTATUS ObInsertObject (__in PVOID Object, __in_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __in ULONG ObjectPointerBias, __out_opt PVOID *NewObject, __out_opt PHANDLE Handle)
Function Documentation
NTSTATUS ObInsertObject (__in PVOID Object, __in_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __in ULONG ObjectPointerBias, __out_opt PVOID * NewObject, __out_opt PHANDLE Handle)
Definition at line 27 of file obinsert.c.
References ARGUMENT_PRESENT, ASSERT, _OBJECT_CREATE_INFORMATION::Attributes, _UNICODE_STRING::Buffer, _OBJECT_HEADER_NAME_INFO::Directory, _OBP_LOOKUP_CONTEXT::DirectoryLocked, FALSE, _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, KdBreakPoint, KdPrint, KeGetPreviousMode, KernelMode, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, OB_FLAG_KERNEL_OBJECT, OB_FLAG_NEW_OBJECT, ObAssignSecurity(), ObCreateHandle, ObDereferenceObject(), ObGetObjectSecurity(), OBJ_OPENIF, OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, ObOpenHandle, ObpChargeQuotaForObject(), ObpCreateHandle(), ObpCreateSymbolicLinkName(), ObpCreateUnnamedHandle(), ObpDeleteDirectoryEntry(), ObpDeleteNameCheck(), ObpDereferenceNameInfo(), ObpFreeObjectCreateInformation, ObpInitializeLookupContext(), ObpLockObject, ObpLookupObjectName(), ObpReferenceNameInfo(), ObpReleaseLookupContext(), ObpSymbolicLinkObjectType, ObpUnlockObject, ObpValidateAccessMask(), ObpValidateIrql, ObReleaseObjectSecurity(), PAGED_CODE, _OBJECT_CREATE_INFORMATION::ParseContext, _OBJECT_CREATE_INFORMATION::ProbeMode, _OBJECT_CREATE_INFORMATION::RootDirectory, SeCreateAccessState(), _OBJECT_CREATE_INFORMATION::SecurityDescriptor, _OBJECT_CREATE_INFORMATION::SecurityQos, _OBJECT_TYPE_INITIALIZER::SecurityRequired, SeDeleteAccessState(), SeReleaseSecurityDescriptor(), Status, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_EXISTS, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UserMode.
Referenced by CmpCreateRegistryRoot(), ExCreateCallback(), FsRtlCreateSectionForDataScan(), IoCreateController(), IoCreateDevice(), IoCreateDriver(), IoCreateStreamFileObjectEx(), IopInitializeBuiltinDriver(), IopLoadDriver(), LpcpCreatePort(), MiSectionInitialization(), NtAcceptConnectPort(), NtCreateDebugObject(), NtCreateDirectoryObject(), NtCreateEvent(), NtCreateEventPair(), NtCreateIoCompletion(), NtCreateJobObject(), NtCreateKeyedEvent(), NtCreateMutant(), NtCreateProfile(), NtCreateSection(), NtCreateSemaphore(), NtCreateSymbolicLinkObject(), NtCreateTimer(), NtDuplicateToken(), NtFilterToken(), NtOpenThreadTokenEx(), NtSecureConnectPort(), PspCreateProcess(), PspCreateThread(), SeCopyClientToken(), SeFastFilterToken(), SeFilterToken(), SepCreateToken(), SepInitializationPhase1(), SeSubProcessToken(), and WmipCreateGuidObject().