Windows Research Kernel v1.2: C:/Windows Research Kernel/se/rmlogon.c File Reference
rmlogon.c File Reference
#include "pch.h"
#include "rmp.h"
#include <bugcodes.h>
#include <stdio.h>
#include <zwapi.h>
Data Structures
struct _SEP_FILE_SYSTEM_NOTIFY_CONTEXT
Macros
#define SepLogonSessionIndex(PLogonId)
Typedefs
typedef struct _SEP_FILE_SYSTEM_NOTIFY_CONTEXT * PSEP_FILE_SYSTEM_NOTIFY_CONTEXT
typedef struct _SEP_FILE_SYSTEM_NOTIFY_CONTEXT SEP_FILE_SYSTEM_NOTIFY_CONTEXT
Functions
VOID FASTCALL ObfDereferenceDeviceMap (IN PDEVICE_MAP DeviceMap)
NTSTATUS SeGetLogonIdDeviceMap (IN PLUID pLogonId, OUT PDEVICE_MAP *ppDevMap)
NTSTATUS SeMarkLogonSessionForTerminationNotification (IN PLUID LogonId)
NTSTATUS SepCleanupLUIDDeviceMapDirectory (PLUID pLogonId)
NTSTATUS SepCreateLogonSessionTrack (IN PLUID LogonId)
NTSTATUS SepDeleteLogonSessionTrack (IN PLUID LogonId)
VOID SepDeReferenceLogonSession (IN PLUID LogonId)
VOID SepInformFileSystemsOfDeletedLogon (IN PLUID LogonId)
VOID SepInformLsaOfDeletedLogon (IN PLUID LogonId)
VOID SepNotifyFileSystems (IN PVOID Context)
NTSTATUS SepReferenceLogonSession (IN PLUID LogonId, OUT PSEP_LOGON_SESSION_REFERENCES *ReturnSession)
VOID SepRmCreateLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
VOID SepRmDeleteLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
NTSTATUS SeRegisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
NTSTATUS SeUnregisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
Variables
SEP_LOGON_SESSION_TERMINATED_NOTIFICATION SeFileSystemNotifyRoutinesHead = {0}
Macro Definition Documentation
#define SepLogonSessionIndex (PLogonId)
Value:
(\
     (PLogonId)->LowPart & SEP_LOGON_TRACK_INDEX_MASK                         \
     )
Definition at line 131 of file rmlogon.c.
Referenced by SeGetLogonIdDeviceMap(), SeMarkLogonSessionForTerminationNotification(), SepCreateLogonSessionTrack(), SepDeleteLogonSessionTrack(), SepDeReferenceLogonSession(), and SepReferenceLogonSession().
Typedef Documentation
typedef struct _SEP_FILE_SYSTEM_NOTIFY_CONTEXT * PSEP_FILE_SYSTEM_NOTIFY_CONTEXT
typedef struct _SEP_FILE_SYSTEM_NOTIFY_CONTEXT SEP_FILE_SYSTEM_NOTIFY_CONTEXT
Function Documentation
VOID FASTCALL ObfDereferenceDeviceMap (IN PDEVICE_MAP DeviceMap)
Definition at line 1661 of file obdir.c.
References ExFreePool(), NULL, ObDereferenceObject(), ObMakeTemporaryObject(), ObpLockDeviceMap, and ObpUnlockDeviceMap.
Referenced by ObDereferenceDeviceMap(), ObpLookupObjectName(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), SeGetLogonIdDeviceMap(), SepDeleteLogonSessionTrack(), and SepDeReferenceLogonSession().
NTSTATUS SeGetLogonIdDeviceMap (IN PLUID pLogonId, OUT PDEVICE_MAP * ppDevMap)
Definition at line 1440 of file rmlogon.c.
References _snwprintf, DIRECTORY_ALL_ACCESS, InitializeObjectAttributes, InterlockedIncrement, _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NT_SUCCESS, NULL, ObfDereferenceDeviceMap(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_OPENIF, OBJ_PERMANENT, ObSetDirectoryDeviceMap(), PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, RtlInitUnicodeString(), SepDeReferenceLogonSessionDirect(), SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, Status, STATUS_INVALID_PARAMETER, STATUS_NO_SUCH_LOGON_SESSION, STATUS_SUCCESS, SYMBOLIC_LINK_ALL_ACCESS, ZwClose(), ZwCreateDirectoryObject(), and ZwCreateSymbolicLinkObject().
Referenced by ObpReferenceDeviceMap(), and ObpSetCurrentProcessDeviceMap().
NTSTATUS SeMarkLogonSessionForTerminationNotification (IN PLUID LogonId)
Definition at line 1279 of file rmlogon.c.
References _SEP_LOGON_SESSION_REFERENCES::Flags, _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, PAGED_CODE, RtlEqualLuid, SEP_TERMINATION_NOTIFY, SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_NOT_FOUND, and STATUS_SUCCESS.
NTSTATUS SepCleanupLUIDDeviceMapDirectory (PLUID pLogonId)
Definition at line 388 of file rmlogon.c.
References _snwprintf, _UNICODE_STRING::Buffer, Count, DIRECTORY_QUERY, ExAllocatePoolWithTag, ExFreePool(), FALSE, _LUID::HighPart, InitializeObjectAttributes, KeStackAttachProcess(), KeUnstackDetachProcess(), _LUID::LowPart, _OBJECT_DIRECTORY_INFORMATION::Name, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectSafe(), PAGED_CODE, PagedPool, _EPROCESS::Pcb, PsGetCurrentProcess(), PsInitialSystemProcess, RtlInitUnicodeString(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_NO_MORE_ENTRIES, STATUS_SUCCESS, SYMBOLIC_LINK_ALL_ACCESS, TRUE, _OBJECT_DIRECTORY_INFORMATION::TypeName, wcscmp(), ZwClose(), ZwMakeTemporaryObject(), ZwOpenDirectoryObject(), ZwOpenSymbolicLinkObject(), and ZwQueryDirectoryObject().
Referenced by SepDeleteLogonSessionTrack(), and SepDeReferenceLogonSession().
NTSTATUS SepCreateLogonSessionTrack (IN PLUID LogonId)
Definition at line 800 of file rmlogon.c.
References DbgPrint(), ExAllocatePoolWithTag, ExFreePool(), InitializeListHead(), _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, PAGED_CODE, PagedPool, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, RtlZeroMemory, SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_INSUFFICIENT_RESOURCES, STATUS_LOGON_SESSION_EXISTS, and STATUS_SUCCESS.
Referenced by SepRmCreateLogonSessionWrkr(), and SepRmDbInitialization().
NTSTATUS SepDeleteLogonSessionTrack (IN PLUID LogonId)
Definition at line 925 of file rmlogon.c.
References ExFreePool(), _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, ObfDereferenceDeviceMap(), PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, SepCleanupLUIDDeviceMapDirectory(), SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_BAD_LOGON_SESSION_STATE, STATUS_NO_SUCH_LOGON_SESSION, and STATUS_SUCCESS.
Referenced by SepRmDeleteLogonSessionWrkr().
VOID SepDeReferenceLogonSession (IN PLUID LogonId)
Definition at line 637 of file rmlogon.c.
References DEREF_UNKNOWN_LOGON_SESSION, ExFreePool(), _SEP_LOGON_SESSION_REFERENCES::Flags, InterlockedDecrement, KeBugCheckEx(), _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, ObfDereferenceDeviceMap(), PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, SEP_TERMINATION_NOTIFY, SepCleanupLUIDDeviceMapDirectory(), SepInformFileSystemsOfDeletedLogon(), SepInformLsaOfDeletedLogon(), SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, and SepRmReleaseDbWriteLock.
Referenced by SepDeReferenceLogonSessionDirect().
VOID SepInformFileSystemsOfDeletedLogon (IN PLUID LogonId)
Definition at line 1348 of file rmlogon.c.
References ASSERT, DelayedWorkQueue, ExAllocatePoolWithTag, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, _SEP_FILE_SYSTEM_NOTIFY_CONTEXT::LogonId, NonPagedPool, NULL, PAGED_CODE, SepNotifyFileSystems(), and _SEP_FILE_SYSTEM_NOTIFY_CONTEXT::WorkItem.
Referenced by SepDeReferenceLogonSession().
VOID SepInformLsaOfDeletedLogon (IN PLUID LogonId)
Definition at line 1073 of file rmlogon.c.
References ASSERT, _SEP_LSA_WORK_ITEM::CleanupFunction, _SEP_LSA_WORK_ITEM::CleanupParameter, _SEP_LSA_WORK_ITEM::CommandNumber, _SEP_LSA_WORK_ITEM::CommandParams, _SEP_LSA_WORK_ITEM::CommandParamsLength, _SEP_LSA_WORK_ITEM::CommandParamsMemoryType, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SEP_LSA_WORK_ITEM::LogonId, LsapLogonSessionDeletedCommand, NULL, PAGED_CODE, PagedPool, _SEP_LSA_WORK_ITEM::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBufferLength, SepDeleteLogon, SepQueueWorkItem(), SepRmImmediateMemory, _SEP_LSA_WORK_ITEM::Tag, and TRUE.
Referenced by SepDeReferenceLogonSession().
VOID SepNotifyFileSystems (IN PVOID Context)
Definition at line 1407 of file rmlogon.c.
References _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::CallbackRoutine, ExFreePool(), _SEP_FILE_SYSTEM_NOTIFY_CONTEXT::LogonId, _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::Next, NULL, PAGED_CODE, SeFileSystemNotifyRoutinesHead, SepRmAcquireNotifyLock, and SepRmReleaseNotifyLock.
Referenced by SepInformFileSystemsOfDeletedLogon().
NTSTATUS SepReferenceLogonSession (IN PLUID LogonId, OUT PSEP_LOGON_SESSION_REFERENCES * ReturnSession)
Definition at line 299 of file rmlogon.c.
References InterlockedIncrement, _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_NO_SUCH_LOGON_SESSION, and STATUS_SUCCESS.
Referenced by SepCreateToken(), and SepDuplicateLogonSessionReference().
VOID SepRmCreateLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
Definition at line 144 of file rmlogon.c.
References ASSERT, PAGED_CODE, RmCreateLogonSession, SepCreateLogonSessionTrack(), Status, and UNALIGNED.
VOID SepRmDeleteLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
Definition at line 222 of file rmlogon.c.
References ASSERT, PAGED_CODE, RmDeleteLogonSession, SepDeleteLogonSessionTrack(), Status, and UNALIGNED.
NTSTATUS SeRegisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
Definition at line 1146 of file rmlogon.c.
References _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::CallbackRoutine, ExAllocatePoolWithTag, _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::Next, NULL, PAGED_CODE, PagedPool, POOL_COLD_ALLOCATION, SeFileSystemNotifyRoutinesHead, SepRmAcquireNotifyLock, SepRmReleaseNotifyLock, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS SeUnregisterLogonSessionTerminatedRoutine (IN PSE_LOGON_SESSION_TERMINATED_ROUTINE CallbackRoutine)
Definition at line 1205 of file rmlogon.c.
References _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::CallbackRoutine, ExFreePool(), _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION::Next, NULL, PAGED_CODE, SeFileSystemNotifyRoutinesHead, SepRmAcquireNotifyLock, SepRmReleaseNotifyLock, Status, STATUS_INVALID_PARAMETER, STATUS_NOT_FOUND, and STATUS_SUCCESS.
Variable Documentation
SEP_LOGON_SESSION_TERMINATED_NOTIFICATION SeFileSystemNotifyRoutinesHead = {0}
Definition at line 37 of file rmlogon.c.
Referenced by SepNotifyFileSystems(), SeRegisterLogonSessionTerminatedRoutine(), and SeUnregisterLogonSessionTerminatedRoutine().