Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/lazyrite.c File Reference
lazyrite.c File Reference
#include "cc.h"
Macros
#define BugCheckFileId (CACHE_BUG_CHECK_LAZYRITE)
#define me 0x00000020
Functions
LONG CcExceptionFilter (IN NTSTATUS ExceptionCode)
VOID CcLazyWriteScan ()
VOID FASTCALL CcPostWorkQueue (IN PWORK_QUEUE_ENTRY WorkQueueEntry, IN PLIST_ENTRY WorkQueue)
PWORK_QUEUE_ENTRY CcReadWorkQueue ()
VOID CcScanDpc (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID CcScheduleLazyWriteScan (IN BOOLEAN FastScan)
NTSTATUS CcWaitForCurrentLazyWriterActivity ()
VOID CcWorkerThread (PVOID ExWorkQueueItem)
Macro Definition Documentation
#define BugCheckFileId (CACHE_BUG_CHECK_LAZYRITE)
Definition at line 25 of file lazyrite.c.
#define me 0x00000020
Definition at line 31 of file lazyrite.c.
Referenced by CcLazyWriteScan(), CcPostWorkQueue(), and CcWorkerThread().
Function Documentation
LONG CcExceptionFilter (IN NTSTATUS ExceptionCode)
Definition at line 721 of file lazyrite.c.
References DebugTrace, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, and FsRtlIsNtstatusExpected().
Referenced by CcAcquireByteRangeForWrite(), CcLazyWriteScan(), and CcWorkerThread().
VOID CcLazyWriteScan ()
Definition at line 225 of file lazyrite.c.
References ASSERTMSG, CcAcquireMasterLock, CcAllocateWorkQueueEntry, CcBugCheck, CcCanIWrite(), CcCapturedSystemSize, CcDeferredWrites, CcDirtyPagesLastScan, CcDirtyPageTarget, CcDirtySharedCacheMapList, CcExceptionFilter(), CcExpressWorkQueue, CcLazyWriterCursor, CcPagesWrittenLastTime, CcPagesYetToWrite, CcPostDeferredWrites(), CcPostTickWorkQueue, CcPostWorkQueue(), CcRegularWorkQueue, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcTotalDirtyPages, ClearFlag, CONTAINING_RECORD, Count, DebugTrace, _SHARED_CACHE_MAP::DirtyPages, except, FALSE, _SHARED_CACHE_MAP::FileObject, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, _FILE_OBJECT::Flags, _LIST_ENTRY::Flink, FO_TEMPORARY_FILE, _WORK_QUEUE_ENTRY::Function, InitializeListHead(), InsertHeadList(), InsertTailList(), IS_CURSOR, IsListEmpty, LAZY_WRITER_MAX_AGE_TARGET, _SHARED_CACHE_MAP::LazyWritePassCount, LazyWriter, MAX_WRITE_BEHIND, MAXUCHAR, me, MmSmallSystem, MODIFIED_WRITE_DISABLED, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SIZE, _SHARED_CACHE_MAP::PagesToWrite, _WORK_QUEUE_ENTRY::Parameters, _LARGE_INTEGER::QuadPart, RemoveEntryList(), RemoveHeadList(), _LAZY_WRITER::ScanActive, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, WAITING_FOR_TEARDOWN, _WORK_QUEUE_ENTRY::Write, WRITE_CHARGE_THRESHOLD, WRITE_QUEUED, and WriteBehind.
Referenced by CcWorkerThread().
VOID FASTCALL CcPostWorkQueue (IN PWORK_QUEUE_ENTRY WorkQueueEntry, IN PLIST_ENTRY WorkQueue)
Definition at line 764 of file lazyrite.c.
References ASSERT, CcAcquireWorkQueueLock, CcIdleWorkerThreadList, CcNumberActiveWorkerThreads, CcQueueThrottle, CcReleaseWorkQueueLock, CriticalWorkQueue, DebugTrace, ExQueueWorkItem(), FIELD_OFFSET, InsertTailList(), IsListEmpty, List, me, NULL, and RemoveHeadList().
Referenced by CcLazyWriteScan(), CcScanDpc(), and CcScheduleReadAhead().
PWORK_QUEUE_ENTRY CcReadWorkQueue ()
VOID CcScanDpc (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 103 of file lazyrite.c.
References CcAllocateWorkQueueEntry, CcPostWorkQueue(), CcRegularWorkQueue, FALSE, _WORK_QUEUE_ENTRY::Function, LazyWriter, LazyWriteScan, NULL, _LAZY_WRITER::ScanActive, and UNREFERENCED_PARAMETER.
Referenced by CcInitializeCacheManager().
VOID CcScheduleLazyWriteScan (IN BOOLEAN FastScan)
Definition at line 47 of file lazyrite.c.
References CcFirstDelay, CcIdleDelay, CcNoDelay, KeSetTimer(), LazyWriter, _LAZY_WRITER::ScanActive, _LAZY_WRITER::ScanDpc, _LAZY_WRITER::ScanTimer, and TRUE.
Referenced by CcCanIWrite(), CcDeferWrite(), CcFlushCache(), CcGetFlushedValidData(), CcGetVacbMiss(), CcLazyWriteScan(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPerformReadAhead(), CcPurgeCacheSection(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcSetFileSizes(), CcUninitializeCacheMap(), CcWaitForCurrentLazyWriterActivity(), CcWaitForUninitializeCacheMap(), CcWriteBehind(), and CcZeroEndOfLastPage().
NTSTATUS CcWaitForCurrentLazyWriterActivity ()
Definition at line 162 of file lazyrite.c.
References CcAcquireMasterLock, CcAllocateWorkQueueEntry, CcPostTickWorkQueue, CcReleaseMasterLock, CcScheduleLazyWriteScan(), _WORK_QUEUE_ENTRY::Event, EventSet, Executive, FALSE, _WORK_QUEUE_ENTRY::Function, InsertTailList(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LazyWriter, NotificationEvent, NULL, _LAZY_WRITER::OtherWork, _WORK_QUEUE_ENTRY::Parameters, _LAZY_WRITER::ScanActive, STATUS_INSUFFICIENT_RESOURCES, TRUE, and _WORK_QUEUE_ENTRY::WorkQueueLinks.
Referenced by CcSetPrivateWriteFile().
VOID CcWorkerThread (PVOID ExWorkQueueItem)
Definition at line 839 of file lazyrite.c.
References ASSERT, CC_REQUEUE, CcAcquireWorkQueueLock, CcDeferredWrites, CcExceptionFilter(), CcExpressWorkQueue, CcFreeWorkQueueEntry, CcIdleWorkerThreadList, CcLazyWriteScan(), CcNumberActiveWorkerThreads, CcPerformReadAhead(), CcQueueThrottle, CcRegularWorkQueue, CcReleaseWorkQueueLock, CcTotalDirtyPages, CcWriteBehind(), CONTAINING_RECORD, DebugTrace, _WORK_QUEUE_ENTRY::Event, EventSet, except, FALSE, FIELD_OFFSET, _LIST_ENTRY::Flink, _WORK_QUEUE_ENTRY::Function, _IO_STATUS_BLOCK::Information, InsertTailList(), IsListEmpty, KeSetEvent(), LazyWriteScan, List, me, _ETHREAD::MemoryMaker, NT_SUCCESS, _WORK_QUEUE_ENTRY::Parameters, PsGetCurrentThread(), _WORK_QUEUE_ENTRY::Read, ReadAhead, RemoveHeadList(), _IO_STATUS_BLOCK::Status, STATUS_SUCCESS, TRUE, _WORK_QUEUE_ENTRY::WorkQueueLinks, _WORK_QUEUE_ENTRY::Write, and WriteBehind.
Referenced by CcInitializeCacheManager().