Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/raise.c File Reference
raise.c File Reference
#include "exp.h"
Functions
DECLSPEC_NOINLINE VOID ExRaiseAccessViolation (VOID)
DECLSPEC_NOINLINE VOID ExRaiseDatatypeMisalignment (VOID)
Function Documentation
DECLSPEC_NOINLINE VOID ExRaiseAccessViolation (VOID)
Definition at line 37 of file raise.c.
References ExRaiseStatus(), and STATUS_ACCESS_VIOLATION.
Referenced by ProbeForWrite().
DECLSPEC_NOINLINE VOID ExRaiseDatatypeMisalignment (VOID)
Definition at line 66 of file raise.c.
References ExRaiseStatus(), and STATUS_DATATYPE_MISALIGNMENT.
Referenced by ProbeForRead(), ProbeForWrite(), ProbeForWriteSmallStructure(), ProbeForWriteUlongAligned32(), and SeCaptureSecurityDescriptor().