Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/xipi.c File Reference
xipi.c File Reference
#include "ki.h"
Functions
ULONG_PTR KeIpiGenericCall (IN PKIPI_BROADCAST_WORKER BroadcastFunction, IN ULONG_PTR Context)
VOID KiIpiGenericCallTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID BroadcastFunction, IN PVOID Context, IN PVOID Parameter3)
Function Documentation
ULONG_PTR KeIpiGenericCall (IN PKIPI_BROADCAST_WORKER BroadcastFunction, IN ULONG_PTR Context)
Definition at line 34 of file xipi.c.
References Count, IPI_LEVEL, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KeNumberProcessors, KeReleaseSpinLockFromDpcLevel(), KeYieldProcessor, KfRaiseIrql(), KiIpiGenericCallTarget(), KiIpiSendPacket(), KiIpiStallOnPacketTargets(), KiReverseStallIpiLock, _KPRCB::SetMember, Status, and SYNCH_LEVEL.
Referenced by KeAdjustInterruptTime(), KeSetIntervalProfile(), KiInitMachineDependent(), KiOpPatchCode(), and KiRestoreFastSyscallReturnState().
VOID KiIpiGenericCallTarget (IN PKIPI_CONTEXT SignalDone, IN PVOID BroadcastFunction, IN PVOID Context, IN PVOID Parameter3)
Definition at line 155 of file xipi.c.
References InterlockedDecrement, KiIpiSignalPacketDone(), and KiPollFreezeExecution().
Referenced by KeIpiGenericCall().