Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/stackovf.c File Reference
stackovf.c File Reference
#include "FsRtlP.h"
Data Structures
struct _STACK_OVERFLOW_ITEM
Macros
#define MODULE_POOL_TAG ('srSF')
Typedefs
typedef STACK_OVERFLOW_ITEM * PSTACK_OVERFLOW_ITEM
typedef struct _STACK_OVERFLOW_ITEM STACK_OVERFLOW_ITEM
Functions
NTSTATUS FsRtlInitializeWorkerThread (VOID)
DECLSPEC_NOINLINE VOID FsRtlPostPagingFileStackOverflow (IN PVOID Context, IN PKEVENT Event, IN PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
DECLSPEC_NOINLINE VOID FsRtlPostStackOverflow (IN PVOID Context, IN PKEVENT Event, IN PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
VOID FsRtlpPostStackOverflow (IN PVOID Context, IN PKEVENT Event, IN PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine, IN BOOLEAN PagingFile)
VOID FsRtlStackOverflowRead (IN PVOID Context)
VOID FsRtlWorkerThread (IN PVOID StartContext)
Variables
KQUEUE FsRtlWorkerQueues [2]
STACK_OVERFLOW_ITEM StackOverflowFallback
KEVENT StackOverflowFallbackSerialEvent
Macro Definition Documentation
#define MODULE_POOL_TAG ('srSF')
Definition at line 36 of file stackovf.c.
Referenced by FsRtlpPostStackOverflow().
Typedef Documentation
typedef STACK_OVERFLOW_ITEM* PSTACK_OVERFLOW_ITEM
Definition at line 97 of file stackovf.c.
typedef struct _STACK_OVERFLOW_ITEM STACK_OVERFLOW_ITEM
Function Documentation
NTSTATUS FsRtlInitializeWorkerThread (VOID)
Definition at line 108 of file stackovf.c.
References FsRtlPostPagingFileStackOverflow(), FsRtlPostStackOverflow(), FsRtlWorkerThread(), InitializeObjectAttributes, KeInitializeEvent(), KeInitializeQueue(), NT_SUCCESS, NULL, PsCreateSystemThread(), Status, STATUS_SUCCESS, SynchronizationEvent, THREAD_ALL_ACCESS, TRUE, ULongToPtr, and ZwClose().
Referenced by FsRtlInitSystem().
DECLSPEC_NOINLINE VOID FsRtlPostPagingFileStackOverflow (IN PVOID Context, IN PKEVENT Event, IN PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
Definition at line 212 of file stackovf.c.
References FsRtlpPostStackOverflow(), and TRUE.
Referenced by FsRtlInitializeWorkerThread().
DECLSPEC_NOINLINE VOID FsRtlPostStackOverflow (IN PVOID Context, IN PKEVENT Event, IN PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine)
Definition at line 173 of file stackovf.c.
References FALSE, and FsRtlpPostStackOverflow().
Referenced by FsRtlInitializeWorkerThread().
VOID FsRtlpPostStackOverflow (IN PVOID Context, IN PKEVENT Event, IN PFSRTL_STACK_OVERFLOW_ROUTINE StackOverflowRoutine, IN BOOLEAN PagingFile)
Definition at line 250 of file stackovf.c.
References _STACK_OVERFLOW_ITEM::Context, _STACK_OVERFLOW_ITEM::Event, ExAllocatePoolWithTag, Executive, ExInitializeWorkItem, ExRaiseStatus(), FALSE, FsRtlStackOverflowRead(), _STACK_OVERFLOW_ITEM::Item, KeInsertQueue(), KernelMode, KeWaitForSingleObject(), _WORK_QUEUE_ITEM::List, MODULE_POOL_TAG, NonPagedPool, NULL, StackOverflowFallback, _STACK_OVERFLOW_ITEM::StackOverflowRoutine, and STATUS_INSUFFICIENT_RESOURCES.
Referenced by FsRtlPostPagingFileStackOverflow(), and FsRtlPostStackOverflow().
VOID FsRtlStackOverflowRead (IN PVOID Context)
Definition at line 351 of file stackovf.c.
References _STACK_OVERFLOW_ITEM::Context, _STACK_OVERFLOW_ITEM::Event, ExFreePool(), FALSE, FSRTL_FSP_TOP_LEVEL_IRP, KeSetEvent(), NULL, PsGetCurrentThread(), _STACK_OVERFLOW_ITEM::StackOverflowRoutine, and _ETHREAD::TopLevelIrp.
Referenced by FsRtlpPostStackOverflow().
VOID FsRtlWorkerThread (IN PVOID StartContext)
Definition at line 408 of file stackovf.c.
References CONTAINING_RECORD, IRQL_NOT_LESS_OR_EQUAL, KeBugCheckEx(), KeGetCurrentIrql(), KeRemoveQueue(), KernelMode, KeSetPriorityThread(), List, LOW_REALTIME_PRIORITY, NULL, _WORK_QUEUE_ITEM::Parameter, PsGetCurrentThread(), _ETHREAD::Tcb, TRUE, VOID, and _WORK_QUEUE_ITEM::WorkerRoutine.
Referenced by FsRtlInitializeWorkerThread().
Variable Documentation
KQUEUE FsRtlWorkerQueues[2]
Definition at line 29 of file stackovf.c.
STACK_OVERFLOW_ITEM StackOverflowFallback
Definition at line 100 of file stackovf.c.
Referenced by FsRtlpPostStackOverflow().
KEVENT StackOverflowFallbackSerialEvent
Definition at line 99 of file stackovf.c.