Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/dbcsname.c File Reference
dbcsname.c File Reference
#include "FsRtlP.h"
Macros
#define Dbg (0x10000000)
#define GetDbcs(BUF, OFFSET, DBCS_CHAR, LENGTH)
#define MATCHES_ARRAY_SIZE 16
#define MODULE_POOL_TAG ('drSF')
Functions
VOID FsRtlDissectDbcs (__in ANSI_STRING Path, __out PANSI_STRING FirstName, __out PANSI_STRING RemainingName)
BOOLEAN FsRtlDoesDbcsContainWildCards (__in PANSI_STRING Name)
BOOLEAN FsRtlIsDbcsInExpression (__in PANSI_STRING Expression, __in PANSI_STRING Name)
BOOLEAN FsRtlIsFatDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
BOOLEAN FsRtlIsHpfsDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
Macro Definition Documentation
#define Dbg (0x10000000)
Definition at line 45 of file dbcsname.c.
Referenced by FsRtlIsDbcsInExpression().
#define GetDbcs (BUF, OFFSET, DBCS_CHAR, LENGTH)
Value:
{               \
    if (FsRtlIsLeadDbcsCharacter( (BUF)[(OFFSET)] )) {       \
        *(DBCS_CHAR) = (WCHAR)((BUF)[(OFFSET)] +             \
                               0x100 * (BUF)[(OFFSET) + 1]); \
        *(LENGTH) = 2;                                       \
    } else {                                                 \
        *(DBCS_CHAR) = (WCHAR)(BUF)[(OFFSET)];               \
        *(LENGTH) = 1;                                       \
    }                                                        \
}
Definition at line 738 of file dbcsname.c.
Referenced by FsRtlIsDbcsInExpression().
#define MATCHES_ARRAY_SIZE 16
Definition at line 749 of file dbcsname.c.
Referenced by FsRtlIsDbcsInExpression().
#define MODULE_POOL_TAG ('drSF')
Definition at line 52 of file dbcsname.c.
Function Documentation
VOID FsRtlDissectDbcs (__in ANSI_STRING Path, __out PANSI_STRING FirstName, __out PANSI_STRING RemainingName)
Definition at line 523 of file dbcsname.c.
References FsRtlIsLeadDbcsCharacter, NULL, and PAGED_CODE.
Referenced by FsRtlIsFatDbcsLegal(), and FsRtlIsHpfsDbcsLegal().
BOOLEAN FsRtlDoesDbcsContainWildCards (__in PANSI_STRING Name)
Definition at line 675 of file dbcsname.c.
References FALSE, FsRtlIsAnsiCharacterWild, FsRtlIsLeadDbcsCharacter, PAGED_CODE, and TRUE.
Referenced by FsRtlIsDbcsInExpression(), and FsRtlIsFatDbcsLegal().
BOOLEAN FsRtlIsDbcsInExpression (__in PANSI_STRING Expression, __in PANSI_STRING Name)
Definition at line 752 of file dbcsname.c.
References ANSI_DOS_QM, ANSI_DOS_STAR, ASSERT, _STRING::Buffer, Dbg, DebugTrace, DOS_DOT, ExFreePool(), FALSE, FsRtlDoesDbcsContainWildCards(), FsRtlIsLeadDbcsCharacter, FsRtlpAllocatePool, GetDbcs, _STRING::Length, MATCHES_ARRAY_SIZE, NlsMbOemCodePageTag, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlEqualMemory, and TRUE.
BOOLEAN FsRtlIsFatDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
Definition at line 64 of file dbcsname.c.
References ANSI_DOS_DOT, ASSERT, _STRING::Buffer, FALSE, FsRtlDissectDbcs(), FsRtlDoesDbcsContainWildCards(), FsRtlIsAnsiCharacterLegalFat, FsRtlIsFatDbcsLegal(), FsRtlIsLeadDbcsCharacter, Index, _STRING::Length, PAGED_CODE, and TRUE.
Referenced by FsRtlIsFatDbcsLegal().
BOOLEAN FsRtlIsHpfsDbcsLegal (__in ANSI_STRING DbcsName, __in BOOLEAN WildCardsPermissible, __in BOOLEAN PathNamePermissible, __in BOOLEAN LeadingBackslashPermissible)
Definition at line 328 of file dbcsname.c.
References ANSI_DOS_DOT, _STRING::Buffer, FALSE, FsRtlDissectDbcs(), FsRtlIsAnsiCharacterLegalHpfs, FsRtlIsHpfsDbcsLegal(), FsRtlIsLeadDbcsCharacter, Index, _STRING::Length, PAGED_CODE, and TRUE.
Referenced by FsRtlIsHpfsDbcsLegal().