Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/extsect.c File Reference
extsect.c File Reference
#include "mi.h"
Functions
LOGICAL MiAppendSubsectionChain (IN PMSUBSECTION LastSubsection, IN PMSUBSECTION ExtendedSubsectionHead)
PMMPTE FASTCALL MiGetProtoPteAddressExtended (IN PMMVAD Vad, IN ULONG_PTR Vpn)
PSUBSECTION FASTCALL MiLocateSubsection (IN PMMVAD Vad, IN ULONG_PTR Vpn)
NTSTATUS MmExtendSection (IN PVOID SectionToExtend, IN OUT PLARGE_INTEGER NewSectionSize, IN ULONG IgnoreFileSizeChecking)
NTSTATUS NtExtendSection (__in HANDLE SectionHandle, __inout PLARGE_INTEGER NewSectionSize)
Variables
ULONG MiExtendedSubsectionsConvertedToDynamic
SIZE_T MmAllocationFragment
Function Documentation
LOGICAL MiAppendSubsectionChain (IN PMSUBSECTION LastSubsection, IN PMSUBSECTION ExtendedSubsectionHead)
Definition at line 192 of file extsect.c.
References ASSERT, FALSE, KeMemoryBarrier(), LOCK_PFN, MI_SNAP_SUB, MiExtendedSubsectionsConvertedToDynamic, MiRemoveViewsFromSection(), _MSUBSECTION::NextSubsection, NULL, _MSUBSECTION::NumberOfMappedViews, _MSUBSECTION::PtesInSubsection, _MMSUBSECTION_FLAGS::SectorEndOffset, _MSUBSECTION::SubsectionBase, _MMSUBSECTION_FLAGS2::SubsectionConverted, _SUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, TRUE, _SUBSECTION::u, _MSUBSECTION::u, _MSUBSECTION::u2, and UNLOCK_PFN.
Referenced by MmExtendSection().
PMMPTE FASTCALL MiGetProtoPteAddressExtended (IN PMMVAD Vad, IN ULONG_PTR Vpn)
Definition at line 963 of file extsect.c.
References ASSERT, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _SUBSECTION::NextSubsection, NULL, _SUBSECTION::PtesInSubsection, _SUBSECTION::SubsectionBase, and _CONTROL_AREA::u.
PSUBSECTION FASTCALL MiLocateSubsection (IN PMMVAD Vad, IN ULONG_PTR Vpn)
Definition at line 1062 of file extsect.c.
References ASSERT, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, _SUBSECTION::NextSubsection, NULL, _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _SUBSECTION::SubsectionBase, and _CONTROL_AREA::u.
Referenced by MiDeleteVirtualAddresses(), MiRemoveMappedView(), MiResolvePageFileFault(), MiUpControlAreaRefs(), and MmFlushVirtualMemory().
NTSTATUS MmExtendSection (IN PVOID SectionToExtend, IN OUT PLARGE_INTEGER NewSectionSize, IN ULONG IgnoreFileSizeChecking)
Definition at line 310 of file extsect.c.
References ASSERT, _LIST_ENTRY::Blink, _MMEXTEND_INFO::CommittedSize, _SEGMENT::ControlArea, _MSUBSECTION::ControlArea, _CONTROL_AREA::DereferenceList, _MSUBSECTION::DereferenceList, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExFreePool(), ExReleaseResourceLite(), _SEGMENT::ExtendInfo, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, FsRtlGetFileSize(), FsRtlSetFileSize(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _LARGE_INTEGER::HighPart, _MMSECTION_FLAGS::Image, _SECTION::InitialPageProtection, KeAcquireGuardedMutex(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseGuardedMutex(), _MMPTE::Long, _MSUBSECTION::LongFlags, _MSUBSECTION::LongFlags2, _LARGE_INTEGER::LowPart, Mi4KStartForSubsection, Mi4KStartFromSubsection, MI_CHECK_SUBSECTION, MI_MAXIMUM_SECTION_SIZE, MI_ROUND_TO_SIZE, MiAppendSubsectionChain(), MiFillMemoryPte, MiGetSubsectionAddressForPte, MM4K_MASK, MM4K_SHIFT, MmAllocationFragment, MMSECT, MmSectionBasedMutex, MmSectionExtendResource, MmSectionExtendSetResource, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NonPagedPool, NT_SUCCESS, NULL, _SUBSECTION::NumberOfFullSectors, _MSUBSECTION::NumberOfFullSectors, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfUserReferences, PAGE_EXECUTE_READWRITE, PAGE_READWRITE, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PagedPool, _MMSECTION_FLAGS::PhysicalMemory, POOL_MM_ALLOCATION, _MMPTE_SOFTWARE::Protection, _MMSUBSECTION_FLAGS::Protection, _MMPTE_SOFTWARE::Prototype, _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, _MMSECTION_FLAGS::Rom, SATISFY_OVERZEALOUS_COMPILER, _MMSUBSECTION_FLAGS::SectorEndOffset, _SECTION::Segment, _MAPPED_FILE_SEGMENT::SegmentFlags, _MAPPED_FILE_SEGMENT::SegmentPteTemplate, _SECTION::SizeOfSection, _MAPPED_FILE_SEGMENT::SizeOfSegment, _MMPTE::Soft, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SECTION_NOT_EXTENDED, STATUS_SECTION_TOO_BIG, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags, _MMSUBSECTION_FLAGS::SubsectionStatic, _MAPPED_FILE_SEGMENT::TotalNumberOfPtes, _SEGMENT_FLAGS::TotalNumberOfPtes4132, TRUE, _MMPTE::u, _CONTROL_AREA::u, _SUBSECTION::u, _MSUBSECTION::u, _MSUBSECTION::u2, _SUBSECTION::UnusedPtes, _MSUBSECTION::UnusedPtes, and _MMSECTION_FLAGS::WasPurged.
Referenced by CcInitializeCacheMap(), CcSetFileSizes(), MmCreateSection(), NtAllocateVirtualMemory(), and NtExtendSection().
NTSTATUS NtExtendSection (__in HANDLE SectionHandle, __inout PLARGE_INTEGER NewSectionSize)
Definition at line 86 of file extsect.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, MmExtendSection(), MmSectionObjectType, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROBE_ALIGNMENT, ProbeForWriteSmallStructure(), SECTION_EXTEND_SIZE, and Status.
Variable Documentation
ULONG MiExtendedSubsectionsConvertedToDynamic
Definition at line 29 of file extsect.c.
Referenced by MiAppendSubsectionChain().
SIZE_T MmAllocationFragment
Definition at line 243 of file mminit.c.
Referenced by MmExtendSection(), and MmInitSystem().