Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/create.c File Reference
create.c File Reference
#include "iomgr.h"
Functions
NTSTATUS NtCreateFile (__out PHANDLE FileHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER AllocationSize, __in ULONG FileAttributes, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in_bcount_opt(EaLength) PVOID EaBuffer, __in ULONG EaLength)
NTSTATUS NtCreateMailslotFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CreateOptions, __in ULONG MailslotQuota, __in ULONG MaximumMessageSize, __in PLARGE_INTEGER ReadTimeout)
NTSTATUS NtCreateNamedPipeFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in ULONG NamedPipeType, __in ULONG ReadMode, __in ULONG CompletionMode, __in ULONG MaximumInstances, __in ULONG InboundQuota, __in ULONG OutboundQuota, __in_opt PLARGE_INTEGER DefaultTimeout)
Function Documentation
NTSTATUS NtCreateFile (__out PHANDLE FileHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER AllocationSize, __in ULONG FileAttributes, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in_bcount_opt(EaLength) PVOID EaBuffer, __in ULONG EaLength)
Definition at line 28 of file create.c.
References CreateFileTypeNone, IoCreateFile(), NULL, and PAGED_CODE.
Referenced by RtlCreateSystemVolumeInformationFolder().
NTSTATUS NtCreateMailslotFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CreateOptions, __in ULONG MailslotQuota, __in ULONG MaximumMessageSize, __in PLARGE_INTEGER ReadTimeout)
Definition at line 276 of file create.c.
References ARGUMENT_PRESENT, CreateFileTypeMailslot, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FILE_CREATE, FILE_SHARE_READ, FILE_SHARE_WRITE, IoCreateFile(), KeGetPreviousMode, KernelMode, _MAILSLOT_CREATE_PARAMETERS::MailslotQuota, _MAILSLOT_CREATE_PARAMETERS::MaximumMessageSize, NULL, PAGED_CODE, ProbeForReadSmallStructure, _MAILSLOT_CREATE_PARAMETERS::ReadTimeout, _MAILSLOT_CREATE_PARAMETERS::TimeoutSpecified, and TRUE.
NTSTATUS NtCreateNamedPipeFile (__out PHANDLE FileHandle, __in ULONG DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG ShareAccess, __in ULONG CreateDisposition, __in ULONG CreateOptions, __in ULONG NamedPipeType, __in ULONG ReadMode, __in ULONG CompletionMode, __in ULONG MaximumInstances, __in ULONG InboundQuota, __in ULONG OutboundQuota, __in_opt PLARGE_INTEGER DefaultTimeout)
Definition at line 116 of file create.c.
References ARGUMENT_PRESENT, _NAMED_PIPE_CREATE_PARAMETERS::CompletionMode, CreateFileTypeNamedPipe, _NAMED_PIPE_CREATE_PARAMETERS::DefaultTimeout, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _NAMED_PIPE_CREATE_PARAMETERS::InboundQuota, IoCreateFile(), KeGetPreviousMode, KernelMode, _NAMED_PIPE_CREATE_PARAMETERS::MaximumInstances, _NAMED_PIPE_CREATE_PARAMETERS::NamedPipeType, NULL, _NAMED_PIPE_CREATE_PARAMETERS::OutboundQuota, PAGED_CODE, ProbeForReadSmallStructure, _NAMED_PIPE_CREATE_PARAMETERS::ReadMode, _NAMED_PIPE_CREATE_PARAMETERS::TimeoutSpecified, and TRUE.