Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/sertl.c File Reference
sertl.c File Reference
#include "ntrtlp.h"
#include <winerror.h>
#include <stdio.h>
#include "seopaque.h"
#include "sertlp.h"
#include <..\se\sep.h>
Macros
#define AceFlagsInAce(_Ace)
#define CREATOR_SID_SIZE 12
#define EFFECTIVE_ACE INHERIT_ONLY_ACE
#define max(a, b) (((a) > (b)) ? (a) : (b))
#define MAX_CHILD_SID_GROUP_SIZE 3
#define SE_VALID_CONTROL_BITS
Enumerations
enum ACE_TYPE_TO_COPY { CopyInheritedAces, CopyNonInheritedAces, CopyAllAces }
Functions
NTSTATUS RtlAdjustPrivilege (ULONG Privilege, BOOLEAN Enable, BOOLEAN Client, PBOOLEAN WasEnabled)
BOOLEAN RtlAreAllAccessesGranted (IN ACCESS_MASK GrantedAccess, IN ACCESS_MASK DesiredAccess)
BOOLEAN RtlAreAnyAccessesGranted (IN ACCESS_MASK GrantedAccess, IN ACCESS_MASK DesiredAccess)
NTSTATUS RtlConvertSidToUnicodeString (PUNICODE_STRING UnicodeString, PSID Sid, BOOLEAN AllocateDestinationString)
VOID RtlCopyLuid (OUT PLUID DestinationLuid, IN PLUID SourceLuid)
VOID RtlCopyLuidAndAttributesArray (IN ULONG ArrayLength, IN PLUID_AND_ATTRIBUTES Source, OUT PLUID_AND_ATTRIBUTES Target)
NTSTATUS RtlCopySid (IN ULONG DestinationSidLength, OUT PSID DestinationSid, IN PSID SourceSid)
NTSTATUS RtlCopySidAndAttributesArray (IN ULONG ArrayLength, IN PSID_AND_ATTRIBUTES Source, IN ULONG TargetSidBufferSize, OUT PSID_AND_ATTRIBUTES TargetArrayElement, OUT PSID TargetSid, OUT PSID *NextTargetSid, OUT PULONG RemainingTargetSidBufferSize)
NTSTATUS RtlCreateSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ULONG Revision)
NTSTATUS RtlCreateSecurityDescriptorRelative (IN PISECURITY_DESCRIPTOR_RELATIVE SecurityDescriptor, IN ULONG Revision)
NTSYSAPI BOOLEAN NTAPI RtlEqualLuid (PLUID Luid1, PLUID Luid2)
BOOLEAN RtlEqualLuid (IN PLUID Luid1, IN PLUID Luid2)
BOOLEAN RtlEqualPrefixSid (IN PSID Sid1, IN PSID Sid2)
BOOLEAN RtlEqualSid (IN PSID Sid1, IN PSID Sid2)
VOID RtlEraseUnicodeString (PUNICODE_STRING String)
NTSTATUS RtlGetControlSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSECURITY_DESCRIPTOR_CONTROL Control, OUT PULONG Revision)
NTSTATUS RtlGetDaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN DaclPresent, OUT PACL *Dacl, OUT PBOOLEAN DaclDefaulted)
NTSTATUS RtlGetGroupSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID *Group, OUT PBOOLEAN GroupDefaulted)
NTSTATUS RtlGetOwnerSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID *Owner, OUT PBOOLEAN OwnerDefaulted)
NTSTATUS RtlGetSaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN SaclPresent, OUT PACL *Sacl, OUT PBOOLEAN SaclDefaulted)
BOOLEAN RtlGetSecurityDescriptorRMControl (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PUCHAR RMControl)
PSID_IDENTIFIER_AUTHORITY RtlIdentifierAuthoritySid (IN PSID Sid)
NTSTATUS RtlImpersonateSelf (IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
NTSTATUS RtlInitializeSid (IN PSID Sid, IN PSID_IDENTIFIER_AUTHORITY IdentifierAuthority, IN UCHAR SubAuthorityCount)
ULONG RtlLengthRequiredSid (IN ULONG SubAuthorityCount)
ULONG RtlLengthSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor)
ULONG RtlLengthSid (IN PSID Sid)
NTSTATUS RtlLengthSidAsUnicodeString (PSID Sid, PULONG StringLength)
VOID RtlMapGenericMask (IN OUT PACCESS_MASK AccessMask, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS RtlMapSecurityErrorToNtStatus (IN SECURITY_STATUS Error)
VOID RtlpApplyAclToObject (IN PACL Acl, IN PGENERIC_MAPPING GenericMapping)
BOOLEAN RtlpCompareAces (IN PKNOWN_ACE InheritedAce, IN PKNOWN_ACE ChildAce, IN PSID OwnerSid, IN PSID GroupSid)
BOOLEAN RtlpCompareKnownAces (IN PKNOWN_ACE InheritedAce, IN PKNOWN_ACE ChildAce, IN PSID OwnerSid OPTIONAL, IN PSID GroupSid OPTIONAL)
BOOLEAN RtlpCompareKnownObjectAces (IN PKNOWN_OBJECT_ACE InheritedAce, IN PKNOWN_OBJECT_ACE ChildAce, IN PSID OwnerSid OPTIONAL, IN PSID GroupSid OPTIONAL)
NTSTATUS RtlpComputeMergedAcl (IN PACL CurrentAcl, IN ULONG CurrentGenericControl, IN PACL ModificationAcl, IN ULONG ModificationGenericControl, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, OUT PACL *NewAcl, OUT PULONG NewGenericControl)
NTSTATUS RtlpComputeMergedAcl2 (IN PACL CurrentAcl, IN ULONG CurrentGenericControl, IN PACL ModificationAcl, IN ULONG ModificationGenericControl, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN PULONG AclBufferSize, IN OUT PUCHAR AclBuffer, OUT PULONG NewGenericControl)
NTSTATUS RtlpConvertAclToAutoInherit (IN PACL ParentAcl OPTIONAL, IN PACL ChildAcl, IN GUID *ObjectType OPTIONAL, IN BOOLEAN IsDirectoryObject, IN PSID OwnerSid, IN PSID GroupSid, IN PGENERIC_MAPPING GenericMapping, OUT PACL *NewAcl, OUT PULONG NewGenericControl)
NTSTATUS RtlpConvertToAutoInheritSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CurrentSecurityDescriptor, OUT PSECURITY_DESCRIPTOR *NewSecurityDescriptor, IN GUID *ObjectType OPTIONAL, IN BOOLEAN IsDirectoryObject, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS RtlpCopyAces (IN PACL Acl, IN PGENERIC_MAPPING GenericMapping, IN ACE_TYPE_TO_COPY AceTypeToCopy, IN UCHAR AceFlagsToReset, IN BOOLEAN MapSids, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN BOOLEAN IsDirectoryObject, IN BOOLEAN RetainInheritedAceBit, OUT PULONG NewAclSizeParam, OUT PACL NewAcl)
BOOLEAN RtlpCopyEffectiveAce (IN PACE_HEADER OldAce, IN BOOLEAN AutoInherit, IN BOOLEAN WillGenerateInheritAce, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, IN OUT PVOID *AcePosition, OUT PULONG NewAceLength, OUT PACL NewAcl, OUT PBOOLEAN ObjectAceInherited OPTIONAL, OUT PBOOLEAN EffectiveAceMapped, OUT PBOOLEAN AclOverflowed)
NTSTATUS RtlpCreateServerAcl (IN PACL Acl, IN BOOLEAN AclUntrusted, IN PSID ServerSid, OUT PACL *ServerAcl, OUT BOOLEAN *ServerAclAllocated)
NTSTATUS RtlpGenerateInheritAcl (IN PACL Acl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PULONG NewAclSizeParam, OUT PACL NewAcl, OUT PBOOLEAN ObjectAceInherited)
NTSTATUS RtlpGenerateInheritedAce (IN PACE_HEADER OldAce, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PULONG NewAceLength, OUT PACL NewAcl, OUT PULONG NewAceExtraLength, OUT PBOOLEAN ObjectAceInherited)
NTSTATUS RtlpGetDefaultsSubjectContext (HANDLE ClientToken, OUT PTOKEN_OWNER *OwnerInfo, OUT PTOKEN_PRIMARY_GROUP *GroupInfo, OUT PTOKEN_DEFAULT_DACL *DefaultDaclInfo, OUT PTOKEN_OWNER *ServerOwner, OUT PTOKEN_PRIMARY_GROUP *ServerGroup)
BOOLEAN RtlpGuidPresentInGuidList (IN GUID *InheritedObjectType, IN GUID **pNewObjectType, IN ULONG GuidCount)
NTSTATUS RtlpImpersonateSelfEx (IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, IN ACCESS_MASK AdditionalAccess, OUT PHANDLE ThreadToken OPTIONAL)
NTSTATUS RtlpInheritAcl (IN PACL DirectoryAcl, IN PACL ChildAcl, IN ULONG ChildGenericControl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN BOOLEAN DefaultDescriptorForObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PACL *NewAcl, OUT PBOOLEAN NewAclExplicitlyAssigned, OUT PULONG NewGenericControl)
NTSTATUS RtlpInheritAcl2 (IN PACL DirectoryAcl, IN PACL ChildAcl, IN ULONG ChildGenericControl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN BOOLEAN DefaultDescriptorForObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, IN PULONG AclBufferSize, IN OUT PUCHAR AclBuffer, OUT PBOOLEAN NewAclExplicitlyAssigned, OUT PULONG NewGenericControl)
BOOLEAN RtlpIsDuplicateAce (IN PACL Acl, IN PKNOWN_ACE NewAce)
NTSTATUS RtlpNewSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CreatorDescriptor OPTIONAL, OUT PSECURITY_DESCRIPTOR *NewDescriptor, IN GUID **pObjectType OPTIONAL, IN ULONG GuidCount, IN BOOLEAN IsDirectoryObject, IN ULONG AutoInheritFlags, IN HANDLE Token OPTIONAL, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS RtlpSetSecurityObject (IN PVOID Object OPTIONAL, IN SECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR ModificationDescriptor, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN ULONG AutoInheritFlags, IN ULONG PoolType, IN PGENERIC_MAPPING GenericMapping, IN HANDLE Token OPTIONAL)
BOOLEAN RtlpValidateSDOffsetAndSize (IN ULONG Offset, IN ULONG Length, IN ULONG MinLength, OUT PULONG MaxLength)
VOID RtlRunDecodeUnicodeString (UCHAR Seed, PUNICODE_STRING String)
VOID RtlRunEncodeUnicodeString (PUCHAR Seed OPTIONAL, PUNICODE_STRING String)
NTSTATUS RtlSetAttributesSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL Control, OUT PULONG Revision)
NTSTATUS RtlSetControlSecurityDescriptor (IN PSECURITY_DESCRIPTOR pSecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsOfInterest, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsToSet)
NTSTATUS RtlSetDaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN DaclPresent, IN PACL Dacl OPTIONAL, IN BOOLEAN DaclDefaulted OPTIONAL)
NTSTATUS RtlSetGroupSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID Group OPTIONAL, IN BOOLEAN GroupDefaulted OPTIONAL)
NTSTATUS RtlSetOwnerSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID Owner OPTIONAL, IN BOOLEAN OwnerDefaulted OPTIONAL)
NTSTATUS RtlSetSaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN SaclPresent, IN PACL Sacl OPTIONAL, IN BOOLEAN SaclDefaulted OPTIONAL)
VOID RtlSetSecurityDescriptorRMControl (IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN PUCHAR RMControl OPTIONAL)
PUCHAR RtlSubAuthorityCountSid (IN PSID Sid)
PULONG RtlSubAuthoritySid (IN PSID Sid, IN ULONG SubAuthority)
BOOLEAN RtlValidRelativeSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptorInput, IN ULONG SecurityDescriptorLength, IN SECURITY_INFORMATION RequiredInformation)
BOOLEAN RtlValidSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor)
BOOLEAN RtlValidSid (IN PSID Sid)
Variables
const UCHAR RtlBaseAceType []
const UCHAR RtlIsSystemAceType []
Macro Definition Documentation
#define AceFlagsInAce (_Ace)
Value:
(((PACE_HEADER)(_Ace))->AceFlags & (OBJECT_INHERIT_ACE|CONTAINER_INHERIT_ACE) | \
             (((PACE_HEADER)(_Ace))->AceFlags & INHERIT_ONLY_ACE) ^ INHERIT_ONLY_ACE )
Definition at line 6490 of file sertl.c.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), and RtlpConvertAclToAutoInherit().
#define CREATOR_SID_SIZE 12
Definition at line 329 of file sertl.c.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), RtlpCopyEffectiveAce(), and RtlpGenerateInheritedAce().
#define EFFECTIVE_ACE INHERIT_ONLY_ACE
Definition at line 6489 of file sertl.c.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), and RtlpConvertAclToAutoInherit().
#define max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 331 of file sertl.c.
Referenced by RtlpComputeMergedAcl2(), RtlpConvertAclToAutoInherit(), RtlpGenerateInheritAcl(), RtlpGenerateInheritedAce(), and RtlpInheritAcl2().
#define MAX_CHILD_SID_GROUP_SIZE 3
Definition at line 6488 of file sertl.c.
#define SE_VALID_CONTROL_BITS
Value:
(SE_DACL_UNTRUSTED | \
                                SE_SERVER_SECURITY | \
                                SE_DACL_AUTO_INHERIT_REQ | \
                                SE_SACL_AUTO_INHERIT_REQ | \
                                SE_DACL_AUTO_INHERITED | \
                                SE_SACL_AUTO_INHERITED | \
                                SE_DACL_PROTECTED | \
                                SE_SACL_PROTECTED )
Definition at line 375 of file sertl.c.
Referenced by RtlSetAttributesSecurityDescriptor(), and RtlSetControlSecurityDescriptor().
Enumeration Type Documentation
enum ACE_TYPE_TO_COPY
Enumerator
CopyInheritedAces
CopyNonInheritedAces
CopyAllAces
Definition at line 70 of file sertl.c.
Function Documentation
NTSTATUS RtlAdjustPrivilege (ULONG Privilege, BOOLEAN Enable, BOOLEAN Client, PBOOLEAN WasEnabled)
Definition at line 659 of file sertl.c.
References ANYSIZE_ARRAY, ASSERT, _LUID_AND_ATTRIBUTES::Attributes, FALSE, _LUID_AND_ATTRIBUTES::Luid, NT_SUCCESS, NtAdjustPrivilegesToken(), NtClose(), NtCurrentProcess, NtCurrentThread, NtOpenProcessToken(), NtOpenThreadToken(), _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, RTL_PAGED_CODE, RtlConvertUlongToLuid(), SE_PRIVILEGE_ENABLED, Status, STATUS_NOT_ALL_ASSIGNED, STATUS_PRIVILEGE_NOT_HELD, TOKEN_ADJUST_PRIVILEGES, TOKEN_QUERY, and TRUE.
BOOLEAN RtlAreAllAccessesGranted (IN ACCESS_MASK GrantedAccess, IN ACCESS_MASK DesiredAccess)
Definition at line 3053 of file sertl.c.
References RTL_PAGED_CODE.
BOOLEAN RtlAreAnyAccessesGranted (IN ACCESS_MASK GrantedAccess, IN ACCESS_MASK DesiredAccess)
Definition at line 3088 of file sertl.c.
References RTL_PAGED_CODE.
NTSTATUS RtlConvertSidToUnicodeString (PUNICODE_STRING UnicodeString, PSID Sid, BOOLEAN AllocateDestinationString)
Definition at line 1472 of file sertl.c.
References _UNICODE_STRING::Buffer, _LARGE_INTEGER::HighPart, _SID::IdentifierAuthority, _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, _UNICODE_STRING::MaximumLength, NT_SUCCESS, _SID::Revision, RTL_PAGED_CODE, RtlCopyUnicodeString(), RtlCreateUnicodeString(), RtlIntegerToUnicode(), RtlLargeIntegerToUnicode(), RtlValidSid(), SID_REVISION, Status, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_SID, STATUS_NO_MEMORY, STATUS_SUCCESS, _SID::SubAuthority, _SID::SubAuthorityCount, TRUE, _SID_IDENTIFIER_AUTHORITY::Value, wcscat, and wcscpy.
Referenced by RtlFormatCurrentUserKeyPath().
VOID RtlCopyLuid (OUT PLUID DestinationLuid, IN PLUID SourceLuid)
Definition at line 1728 of file sertl.c.
References RTL_PAGED_CODE.
VOID RtlCopyLuidAndAttributesArray (IN ULONG ArrayLength, IN PLUID_AND_ATTRIBUTES Source, OUT PLUID_AND_ATTRIBUTES Target)
Definition at line 1761 of file sertl.c.
References Index, and RTL_PAGED_CODE.
NTSTATUS RtlCopySid (IN ULONG DestinationSidLength, OUT PSID DestinationSid, IN PSID SourceSid)
Definition at line 1241 of file sertl.c.
References RTL_PAGED_CODE, RtlMoveMemory, SeLengthSid, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by RtlCopySidAndAttributesArray(), and RtlpNewSecurityObject().
NTSTATUS RtlCopySidAndAttributesArray (IN ULONG ArrayLength, IN PSID_AND_ATTRIBUTES Source, IN ULONG TargetSidBufferSize, OUT PSID_AND_ATTRIBUTES TargetArrayElement, OUT PSID TargetSid, OUT PSID * NextTargetSid, OUT PULONG RemainingTargetSidBufferSize)
Definition at line 1297 of file sertl.c.
References Index, LongAlign, PtrToUlong, RTL_PAGED_CODE, RtlCopySid(), SeLengthSid, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
NTSTATUS RtlCreateSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ULONG Revision)
Definition at line 1810 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlZeroMemory, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by RtlpNewSecurityObject().
NTSTATUS RtlCreateSecurityDescriptorRelative (IN PISECURITY_DESCRIPTOR_RELATIVE SecurityDescriptor, IN ULONG Revision)
Definition at line 1869 of file sertl.c.
References RTL_PAGED_CODE, RtlZeroMemory, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), and RtlpSetSecurityObject().
NTSYSAPI BOOLEAN NTAPI RtlEqualLuid (PLUID Luid1, PLUID Luid2)
BOOLEAN RtlEqualLuid (IN PLUID Luid1, IN PLUID Luid2)
Definition at line 1689 of file sertl.c.
References RTL_PAGED_CODE, and UNALIGNED.
BOOLEAN RtlEqualPrefixSid (IN PSID Sid1, IN PSID Sid2)
Definition at line 926 of file sertl.c.
References FALSE, _SID::IdentifierAuthority, Index, _SID::Revision, RTL_PAGED_CODE, _SID::SubAuthority, _SID::SubAuthorityCount, TRUE, and _SID_IDENTIFIER_AUTHORITY::Value.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), and RtlpCopyEffectiveAce().
BOOLEAN RtlEqualSid (IN PSID Sid1, IN PSID Sid2)
Definition at line 878 of file sertl.c.
References C_ASSERT, FALSE, FIELD_OFFSET, RTL_PAGED_CODE, RtlEqualMemory, and SeLengthSid.
Referenced by RtlpCompareKnownAces(), and RtlpCompareKnownObjectAces().
VOID RtlEraseUnicodeString (PUNICODE_STRING String)
Definition at line 616 of file sertl.c.
References _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, RTL_PAGED_CODE, and RtlZeroMemory.
NTSTATUS RtlGetControlSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSECURITY_DESCRIPTOR_CONTROL Control, OUT PULONG Revision)
Definition at line 2159 of file sertl.c.
References RTL_PAGED_CODE, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
NTSTATUS RtlGetDaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN DaclPresent, OUT PACL * Dacl, OUT PBOOLEAN DaclDefaulted)
Definition at line 2409 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpDaclAddrSecurityDescriptor, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by ObpFreeDosDevicesProtection(), and RtlpSysVolCheckOwnerAndSecurity().
NTSTATUS RtlGetGroupSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID * Group, OUT PBOOLEAN GroupDefaulted)
Definition at line 2976 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpGroupAddrSecurityDescriptor, SE_GROUP_DEFAULTED, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
NTSTATUS RtlGetOwnerSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PSID * Owner, OUT PBOOLEAN OwnerDefaulted)
Definition at line 2803 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpOwnerAddrSecurityDescriptor, SE_OWNER_DEFAULTED, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
Referenced by RtlpSysVolCheckOwnerAndSecurity().
NTSTATUS RtlGetSaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PBOOLEAN SaclPresent, OUT PACL * Sacl, OUT PBOOLEAN SaclDefaulted)
Definition at line 2615 of file sertl.c.
References _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpAreControlBitsSet, RtlpSaclAddrSecurityDescriptor, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SECURITY_DESCRIPTOR_REVISION, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
BOOLEAN RtlGetSecurityDescriptorRMControl (IN PSECURITY_DESCRIPTOR SecurityDescriptor, OUT PUCHAR RMControl)
Definition at line 10300 of file sertl.c.
References _SECURITY_DESCRIPTOR::Control, FALSE, _SECURITY_DESCRIPTOR::Sbz1, SE_RM_CONTROL_VALID, and TRUE.
PSID_IDENTIFIER_AUTHORITY RtlIdentifierAuthoritySid (IN PSID Sid)
Definition at line 1114 of file sertl.c.
References _SID::IdentifierAuthority, and RTL_PAGED_CODE.
NTSTATUS RtlImpersonateSelf (IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel)
Definition at line 3284 of file sertl.c.
References NULL, RTL_PAGED_CODE, and RtlpImpersonateSelfEx().
NTSTATUS RtlInitializeSid (IN PSID Sid, IN PSID_IDENTIFIER_AUTHORITY IdentifierAuthority, IN UCHAR SubAuthorityCount)
Definition at line 1063 of file sertl.c.
References _SID::IdentifierAuthority, _SID::Revision, RTL_PAGED_CODE, SID_MAX_SUB_AUTHORITIES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and _SID::SubAuthorityCount.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), and RtlpCopyEffectiveAce().
ULONG RtlLengthRequiredSid (IN ULONG SubAuthorityCount)
Definition at line 1032 of file sertl.c.
References RTL_PAGED_CODE.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), RtlpCopyEffectiveAce(), and RtlpGenerateInheritedAce().
ULONG RtlLengthSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 2030 of file sertl.c.
References _SECURITY_DESCRIPTOR::Control, LongAlignSize, NULL, RTL_PAGED_CODE, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, SE_SELF_RELATIVE, and SeLengthSid.
ULONG RtlLengthSid (IN PSID Sid)
Definition at line 1211 of file sertl.c.
References RTL_PAGED_CODE, and SeLengthSid.
NTSTATUS RtlLengthSidAsUnicodeString (PSID Sid, PULONG StringLength)
Definition at line 1393 of file sertl.c.
References _SID::IdentifierAuthority, RTL_PAGED_CODE, RtlValidSid(), STATUS_INVALID_SID, STATUS_SUCCESS, _SID::SubAuthorityCount, TRUE, and _SID_IDENTIFIER_AUTHORITY::Value.
Referenced by RtlFormatCurrentUserKeyPath().
VOID RtlMapGenericMask (IN OUT PACCESS_MASK AccessMask, IN PGENERIC_MAPPING GenericMapping)
Definition at line 3125 of file sertl.c.
References GENERIC_ALL, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, and RTL_PAGED_CODE.
Referenced by RtlpConvertAclToAutoInherit().
NTSTATUS RtlMapSecurityErrorToNtStatus (IN SECURITY_STATUS Error)
Definition at line 10434 of file sertl.c.
References SEC_E_BAD_PKGID, SEC_E_CANNOT_INSTALL, SEC_E_CANNOT_PACK, SEC_E_INSUFFICIENT_MEMORY, SEC_E_INTERNAL_ERROR, SEC_E_INVALID_HANDLE, SEC_E_INVALID_TOKEN, SEC_E_LOGON_DENIED, SEC_E_MESSAGE_ALTERED, SEC_E_NO_AUTHENTICATING_AUTHORITY, SEC_E_NO_CREDENTIALS, SEC_E_NO_IMPERSONATION, SEC_E_NOT_OWNER, SEC_E_OUT_OF_SEQUENCE, SEC_E_QOP_NOT_SUPPORTED, SEC_E_SECPKG_NOT_FOUND, SEC_E_TARGET_UNKNOWN, SEC_E_TIME_SKEW, SEC_E_UNKNOWN_CREDENTIALS, SEC_E_UNSUPPORTED_FUNCTION, Status, STATUS_ACCESS_DENIED, STATUS_BAD_NETWORK_PATH, STATUS_CANNOT_IMPERSONATE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INTERNAL_ERROR, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_LOGON_FAILURE, STATUS_NO_LOGON_SERVERS, STATUS_NO_SUCH_LOGON_SESSION, STATUS_NO_SUCH_PACKAGE, STATUS_NOT_SUPPORTED, STATUS_PRIVILEGE_NOT_HELD, and STATUS_TIME_DIFFERENCE_AT_DC.
VOID RtlpApplyAclToObject (IN PACL Acl, IN PGENERIC_MAPPING GenericMapping)
Definition at line 3317 of file sertl.c.
References FirstAce, IsMSAceType, NextAce, NULL, RTL_PAGED_CODE, and RtlApplyAceToObject.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
BOOLEAN RtlpCompareAces (IN PKNOWN_ACE InheritedAce, IN PKNOWN_ACE ChildAce, IN PSID OwnerSid, IN PSID GroupSid)
Definition at line 6496 of file sertl.c.
References FALSE, IsObjectAceType, RtlpCompareKnownAces(), and RtlpCompareKnownObjectAces().
Referenced by RtlpConvertAclToAutoInherit(), and RtlpIsDuplicateAce().
BOOLEAN RtlpCompareKnownAces (IN PKNOWN_ACE InheritedAce, IN PKNOWN_ACE ChildAce, IN PSID OwnerSid OPTIONAL, IN PSID GroupSid OPTIONAL)
Definition at line 6557 of file sertl.c.
References _ACE_HEADER::AceFlags, AceFlagsInAce, _ACE_HEADER::AceType, ASSERT, CREATOR_SID_SIZE, EFFECTIVE_ACE, FAILED_ACCESS_ACE_FLAG, FALSE, IsObjectAceType, KdPrint, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlBaseAceType, RtlEqualPrefixSid(), RtlEqualSid(), RtlInitializeSid(), RtlIsSystemAceType, RtlLengthRequiredSid(), RtlpSubAuthoritySid(), SECURITY_CREATOR_GROUP_RID, SECURITY_CREATOR_OWNER_RID, SECURITY_CREATOR_SID_AUTHORITY, Status, SUCCESSFUL_ACCESS_ACE_FLAG, and TRUE.
Referenced by RtlpCompareAces().
BOOLEAN RtlpCompareKnownObjectAces (IN PKNOWN_OBJECT_ACE InheritedAce, IN PKNOWN_OBJECT_ACE ChildAce, IN PSID OwnerSid OPTIONAL, IN PSID GroupSid OPTIONAL)
Definition at line 6737 of file sertl.c.
References _ACE_HEADER::AceFlags, AceFlagsInAce, _ACE_HEADER::AceType, ASSERT, CREATOR_SID_SIZE, EFFECTIVE_ACE, FAILED_ACCESS_ACE_FLAG, FALSE, IsObjectAceType, KdPrint, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlBaseAceType, RtlEqualPrefixSid(), RtlEqualSid(), RtlInitializeSid(), RtlIsSystemAceType, RtlLengthRequiredSid(), RtlObjectAceInheritedObjectType, RtlObjectAceObjectType, RtlObjectAceSid, RtlpIsEqualGuid, RtlpSubAuthoritySid(), SECURITY_CREATOR_GROUP_RID, SECURITY_CREATOR_OWNER_RID, SECURITY_CREATOR_SID_AUTHORITY, Status, SUCCESSFUL_ACCESS_ACE_FLAG, and TRUE.
Referenced by RtlpCompareAces().
NTSTATUS RtlpComputeMergedAcl (IN PACL CurrentAcl, IN ULONG CurrentGenericControl, IN PACL ModificationAcl, IN ULONG ModificationGenericControl, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, OUT PACL * NewAcl, OUT PULONG NewGenericControl)
Definition at line 5846 of file sertl.c.
References ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, PagedPool, RTL_PAGED_CODE, RtlpComputeMergedAcl2(), Status, STATUS_BUFFER_TOO_SMALL, and STATUS_NO_MEMORY.
Referenced by RtlpSetSecurityObject().
NTSTATUS RtlpComputeMergedAcl2 (IN PACL CurrentAcl, IN ULONG CurrentGenericControl, IN PACL ModificationAcl, IN ULONG ModificationGenericControl, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN PULONG AclBufferSize, IN OUT PUCHAR AclBuffer, OUT PULONG NewGenericControl)
Definition at line 5465 of file sertl.c.
References ACL_REVISION, CopyAllAces, CopyInheritedAces, CopyNonInheritedAces, FALSE, INHERITED_ACE, max, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlCreateAcl(), RtlpCopyAces(), SEP_ACL_AUTO_INHERITED, SEP_ACL_PROTECTED, Status, STATUS_BAD_INHERITANCE_ACL, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_ACL, STATUS_SUCCESS, and TRUE.
Referenced by RtlpComputeMergedAcl().
NTSTATUS RtlpConvertAclToAutoInherit (IN PACL ParentAcl OPTIONAL, IN PACL ChildAcl, IN GUID *ObjectType OPTIONAL, IN BOOLEAN IsDirectoryObject, IN PSID OwnerSid, IN PSID GroupSid, IN PGENERIC_MAPPING GenericMapping, OUT PACL * NewAcl, OUT PULONG NewGenericControl)
Definition at line 6993 of file sertl.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_DENIED_ACE_TYPE, _ACL::AceCount, _ACE_HEADER::AceFlags, AceFlagsInAce, _ACE_HEADER::AceSize, _ACE_HEADER::AceType, _ACL::AclRevision, _ACL::AclSize, ASSERT, CONTAINER_INHERIT_ACE, CREATOR_SID_SIZE, EFFECTIVE_ACE, ExAllocatePoolWithTag, ExFreePool(), FALSE, FirstAce, GENERIC_ALL, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, _KNOWN_ACE::Header, INHERITED_ACE, IsCompoundAceType, IsV4AceType, KdPrint, _KNOWN_ACE::Mask, max, NextAce, NT_SUCCESS, NULL, OBJECT_INHERIT_ACE, PagedPool, RTL_PAGED_CODE, RtlApplyGenericMask, RtlBaseAceType, RtlCopyMemory, RtlCreateAcl(), RtlInitializeSid(), RtlLengthRequiredSid(), RtlMapGenericMask(), RtlpCompareAces(), RtlpInheritAcl(), RtlpSubAuthoritySid(), RtlValidAcl(), SECURITY_CREATOR_GROUP_RID, SECURITY_CREATOR_OWNER_RID, SECURITY_CREATOR_SID_AUTHORITY, SEP_ACL_AUTO_INHERITED, SEP_ACL_PROTECTED, Status, STATUS_INVALID_ACL, STATUS_NO_INHERITANCE, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by RtlpConvertToAutoInheritSecurityObject().
NTSTATUS RtlpConvertToAutoInheritSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CurrentSecurityDescriptor, OUT PSECURITY_DESCRIPTOR * NewSecurityDescriptor, IN GUID *ObjectType OPTIONAL, IN BOOLEAN IsDirectoryObject, IN PGENERIC_MAPPING GenericMapping)
Definition at line 6077 of file sertl.c.
References _ACL::AclSize, ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, LongAlignSize, NT_SUCCESS, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, PagedPool, RTL_PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlpAreControlBitsSet, RtlpConvertAclToAutoInherit(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, RtlValidSecurityDescriptor(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_DACL_AUTO_INHERITED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_SACL_AUTO_INHERITED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SeControlGenericToDacl, SeControlGenericToSacl, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, Status, STATUS_INVALID_SECURITY_DESCR, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
NTSTATUS RtlpCopyAces (IN PACL Acl, IN PGENERIC_MAPPING GenericMapping, IN ACE_TYPE_TO_COPY AceTypeToCopy, IN UCHAR AceFlagsToReset, IN BOOLEAN MapSids, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN BOOLEAN IsDirectoryObject, IN BOOLEAN RetainInheritedAceBit, OUT PULONG NewAclSizeParam, OUT PACL NewAcl)
Definition at line 3935 of file sertl.c.
References _ACE_HEADER::AceFlags, AceInherited, _ACE_HEADER::AceSize, CONTAINER_INHERIT_ACE, CopyAllAces, CopyInheritedAces, CopyNonInheritedAces, FALSE, FirstAce, INHERIT_ONLY_ACE, INHERITED_ACE, IsMSAceType, NextAce, NULL, OBJECT_INHERIT_ACE, RTL_PAGED_CODE, RtlApplyAceToObject, RtlCopyMemory, RtlFirstFreeAce(), RtlpCopyEffectiveAce(), Status, STATUS_BAD_INHERITANCE_ACL, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, STATUS_UNKNOWN_REVISION, TRUE, VALID_INHERIT_FLAGS, and ValidAclRevision.
Referenced by RtlpComputeMergedAcl2(), and RtlpInheritAcl2().
BOOLEAN RtlpCopyEffectiveAce (IN PACE_HEADER OldAce, IN BOOLEAN AutoInherit, IN BOOLEAN WillGenerateInheritAce, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, IN OUT PVOID * AcePosition, OUT PULONG NewAceLength, OUT PACL NewAcl, OUT PBOOLEAN ObjectAceInherited OPTIONAL, OUT PBOOLEAN EffectiveAceMapped, OUT PBOOLEAN AclOverflowed)
Definition at line 3385 of file sertl.c.
References ACCESS_SYSTEM_SECURITY, ACE_INHERITED_OBJECT_TYPE_PRESENT, _ACE_HEADER::AceType, ARGUMENT_PRESENT, ASSERT, CREATOR_SID_SIZE, FALSE, FIELD_OFFSET, INHERITED_ACE, IsCompoundAceType, IsKnownAceType, IsMSAceType, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlApplyGenericMask, RtlBaseAceType, RtlCompoundAceClientSid, RtlCompoundAceServerSid, RtlCopyMemory, RtlEqualPrefixSid(), RtlInitializeSid(), RtlLengthRequiredSid(), RtlObjectAceInheritedObjectType, RtlObjectAceObjectTypePresent, RtlObjectAceSid, RtlpGuidPresentInGuidList(), RtlpSubAuthoritySid(), SECURITY_CREATOR_GROUP_RID, SECURITY_CREATOR_GROUP_SERVER_RID, SECURITY_CREATOR_OWNER_RID, SECURITY_CREATOR_OWNER_SERVER_RID, SECURITY_CREATOR_SID_AUTHORITY, SeLengthSid, SPECIFIC_RIGHTS_ALL, STANDARD_RIGHTS_ALL, Status, TRUE, and VALID_INHERIT_FLAGS.
Referenced by RtlpCopyAces(), and RtlpGenerateInheritedAce().
NTSTATUS RtlpCreateServerAcl (IN PACL Acl, IN BOOLEAN AclUntrusted, IN PSID ServerSid, OUT PACL * ServerAcl, OUT BOOLEAN * ServerAclAllocated)
Definition at line 8072 of file sertl.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_ALLOWED_COMPOUND_ACE_TYPE, _ACE_HEADER::AceSize, _ACE_HEADER::AceType, ACL_REVISION3, ASSERT, COMPOUND_ACE_IMPERSONATION, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, FirstAce, NextAce, NT_SUCCESS, NULL, PagedPool, RTL_PAGED_CODE, RtlCompoundAceClientSid, RtlCompoundAceServerSid, RtlCopyMemory, RtlCreateAcl(), SeLengthSid, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
NTSTATUS RtlpGenerateInheritAcl (IN PACL Acl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PULONG NewAclSizeParam, OUT PACL NewAcl, OUT PBOOLEAN ObjectAceInherited)
Definition at line 5290 of file sertl.c.
References FALSE, FirstAce, max, NextAce, NT_SUCCESS, RTL_PAGED_CODE, RtlpGenerateInheritedAce(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and TRUE.
Referenced by RtlpInheritAcl2().
NTSTATUS RtlpGenerateInheritedAce (IN PACE_HEADER OldAce, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PULONG NewAceLength, OUT PACL NewAcl, OUT PULONG NewAceExtraLength, OUT PBOOLEAN ObjectAceInherited)
Definition at line 4949 of file sertl.c.
References ASSERT, CONTAINER_INHERIT_ACE, ContainerInherit, CREATOR_SID_SIZE, FALSE, INHERIT_ONLY_ACE, INHERITED_ACE, IsMSAceType, max, NULL, OBJECT_INHERIT_ACE, ObjectInherit, Propagate, RTL_PAGED_CODE, RtlCopyMemory, RtlFirstFreeAce(), RtlLengthRequiredSid(), RtlpCopyEffectiveAce(), RtlpIsDuplicateAce(), STATUS_BAD_INHERITANCE_ACL, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and TRUE.
Referenced by RtlpGenerateInheritAcl().
NTSTATUS RtlpGetDefaultsSubjectContext (HANDLE ClientToken, OUT PTOKEN_OWNER * OwnerInfo, OUT PTOKEN_PRIMARY_GROUP * GroupInfo, OUT PTOKEN_DEFAULT_DACL * DefaultDaclInfo, OUT PTOKEN_OWNER * ServerOwner, OUT PTOKEN_PRIMARY_GROUP * ServerGroup)
BOOLEAN RtlpGuidPresentInGuidList (IN GUID * InheritedObjectType, IN GUID ** pNewObjectType, IN ULONG GuidCount)
Definition at line 10347 of file sertl.c.
References FALSE, RtlEqualMemory, and TRUE.
Referenced by RtlpCopyEffectiveAce().
NTSTATUS RtlpImpersonateSelfEx (IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, IN ACCESS_MASK AdditionalAccess, OUT PHANDLE ThreadToken OPTIONAL)
Definition at line 3189 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, FALSE, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, InitializeObjectAttributes, _SECURITY_QUALITY_OF_SERVICE::Length, NT_SUCCESS, NtClose(), NtCurrentProcess, NtCurrentThread, NtDuplicateToken(), NtOpenProcessToken(), NtSetInformationThread(), NULL, RTL_PAGED_CODE, SECURITY_DYNAMIC_TRACKING, _OBJECT_ATTRIBUTES::SecurityQualityOfService, Status, STATUS_INVALID_PARAMETER_2, ThreadImpersonationToken, TOKEN_DUPLICATE, TOKEN_IMPERSONATE, and TokenImpersonation.
Referenced by RtlImpersonateSelf().
NTSTATUS RtlpInheritAcl (IN PACL DirectoryAcl, IN PACL ChildAcl, IN ULONG ChildGenericControl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN BOOLEAN DefaultDescriptorForObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PACL * NewAcl, OUT PBOOLEAN NewAclExplicitlyAssigned, OUT PULONG NewGenericControl)
Definition at line 4746 of file sertl.c.
References ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, PagedPool, RTL_PAGED_CODE, RtlpInheritAcl2(), Status, STATUS_BUFFER_TOO_SMALL, and STATUS_NO_MEMORY.
Referenced by RtlpConvertAclToAutoInherit(), RtlpNewSecurityObject(), and SepInheritAcl().
NTSTATUS RtlpInheritAcl2 (IN PACL DirectoryAcl, IN PACL ChildAcl, IN ULONG ChildGenericControl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN BOOLEAN DefaultDescriptorForObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, IN PULONG AclBufferSize, IN OUT PUCHAR AclBuffer, OUT PBOOLEAN NewAclExplicitlyAssigned, OUT PULONG NewGenericControl)
Definition at line 4302 of file sertl.c.
References ACL_REVISION, _ACL::AclSize, CopyAllAces, CopyNonInheritedAces, FALSE, FirstAce, INHERITED_ACE, max, NT_SUCCESS, NULL, RTL_PAGED_CODE, RtlCreateAcl(), RtlFirstFreeAce(), RtlMoveMemory, RtlpCopyAces(), RtlpGenerateInheritAcl(), SEP_ACL_AUTO_INHERITED, SEP_ACL_DEFAULTED, SEP_ACL_PRESENT, SEP_ACL_PROTECTED, Status, STATUS_BAD_INHERITANCE_ACL, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_ACL, STATUS_NO_INHERITANCE, STATUS_SUCCESS, STATUS_UNKNOWN_REVISION, TRUE, and ValidAclRevision.
Referenced by RtlpInheritAcl().
BOOLEAN RtlpIsDuplicateAce (IN PACL Acl, IN PKNOWN_ACE NewAce)
Definition at line 7851 of file sertl.c.
References _ACE_HEADER::AceFlags, CONTAINER_INHERIT_ACE, FALSE, FirstAce, _KNOWN_ACE::Header, INHERIT_ONLY_ACE, INHERITED_ACE, IsCompoundAceType, IsV4AceType, KdPrint, NextAce, NULL, OBJECT_INHERIT_ACE, RTL_PAGED_CODE, RtlpCompareAces(), Status, and TRUE.
Referenced by RtlpGenerateInheritedAce().
NTSTATUS RtlpNewSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CreatorDescriptor OPTIONAL, OUT PSECURITY_DESCRIPTOR * NewDescriptor, IN GUID **pObjectType OPTIONAL, IN ULONG GuidCount, IN BOOLEAN IsDirectoryObject, IN ULONG AutoInheritFlags, IN HANDLE Token OPTIONAL, IN PGENERIC_MAPPING GenericMapping)
Definition at line 8275 of file sertl.c.
References _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, _LUID_AND_ATTRIBUTES::Attributes, _SECURITY_DESCRIPTOR::Control, _PRIVILEGE_SET::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, KeGetPreviousMode, KernelMode, LongAlignSize, _LUID_AND_ATTRIBUTES::Luid, NT_SUCCESS, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, PagedPool, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, RTL_PAGED_CODE, RtlCopyMemory, RtlCopySid(), RtlCreateSecurityDescriptor(), RtlCreateSecurityDescriptorRelative(), RtlpApplyAclToObject(), RtlpAreControlBitsSet, RtlpCreateServerAcl(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpInheritAcl(), RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, RtlZeroMemory, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_DACL_AUTO_INHERITED, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_DACL_UNTRUSTED, SE_SACL_AUTO_INHERITED, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SE_SERVER_SECURITY, SeControlDaclToGeneric, SeControlGenericToDacl, SeControlGenericToSacl, SeControlSaclToGeneric, SECURITY_DESCRIPTOR_REVISION, SEF_AVOID_OWNER_CHECK, SEF_AVOID_PRIVILEGE_CHECK, SEF_DACL_AUTO_INHERIT, SEF_DEFAULT_DESCRIPTOR_FOR_OBJECT, SEF_DEFAULT_GROUP_FROM_PARENT, SEF_DEFAULT_OWNER_FROM_PARENT, SEF_SACL_AUTO_INHERIT, SeLengthSid, SeLockSubjectContext(), SepGetDefaultsSubjectContext(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), SepValidOwnerSubjectContext(), SeSecurityPrivilege, SeUnlockSubjectContext(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_OWNER, STATUS_INVALID_PRIMARY_GROUP, STATUS_NO_INHERITANCE, STATUS_NO_TOKEN, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TRUE, and UserMode.
Referenced by SeAssignSecurity(), and SeAssignSecurityEx().
NTSTATUS RtlpSetSecurityObject (IN PVOID Object OPTIONAL, IN SECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR ModificationDescriptor, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN ULONG AutoInheritFlags, IN ULONG PoolType, IN PGENERIC_MAPPING GenericMapping, IN HANDLE Token OPTIONAL)
Definition at line 9280 of file sertl.c.
References _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, DACL_SECURITY_INFORMATION, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, LongAlignSize, NT_SUCCESS, NULL, ObValidateSecurityQuota(), _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, RTL_PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlpApplyAclToObject(), RtlpAreControlBitsSet, RtlpComputeMergedAcl(), RtlpCreateServerAcl(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpPropagateControlBits, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, RtlValidSid(), RtlZeroMemory, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SACL_SECURITY_INFORMATION, _SECURITY_DESCRIPTOR_RELATIVE::Sbz1, _SECURITY_DESCRIPTOR::Sbz1, SE_DACL_AUTO_INHERIT_REQ, SE_DACL_AUTO_INHERITED, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_DACL_UNTRUSTED, SE_GROUP_DEFAULTED, SE_OWNER_DEFAULTED, SE_RM_CONTROL_VALID, SE_SACL_AUTO_INHERIT_REQ, SE_SACL_AUTO_INHERITED, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SE_SERVER_SECURITY, SeCaptureSubjectContext(), SeControlDaclToGeneric, SeControlGenericToDacl, SeControlGenericToSacl, SeControlSaclToGeneric, SECURITY_DESCRIPTOR_REVISION, SEF_AVOID_PRIVILEGE_CHECK, SEF_DACL_AUTO_INHERIT, SEF_SACL_AUTO_INHERIT, SeLengthSid, SepGetDefaultsSubjectContext(), SepValidOwnerSubjectContext(), SeReleaseSubjectContext(), Status, STATUS_BAD_DESCRIPTOR_FORMAT, STATUS_INVALID_OWNER, STATUS_INVALID_PRIMARY_GROUP, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by SeSetSecurityDescriptorInfo(), and SeSetSecurityDescriptorInfoEx().
BOOLEAN RtlpValidateSDOffsetAndSize (IN ULONG Offset, IN ULONG Length, IN ULONG MinLength, OUT PULONG MaxLength)
Definition at line 9997 of file sertl.c.
References FALSE, and TRUE.
Referenced by RtlValidRelativeSecurityDescriptor().
VOID RtlRunDecodeUnicodeString (UCHAR Seed, PUNICODE_STRING String)
Definition at line 540 of file sertl.c.
References _STRING::Buffer, _STRING::Length, and RTL_PAGED_CODE.
VOID RtlRunEncodeUnicodeString (PUCHAR Seed OPTIONAL, PUNICODE_STRING String)
Definition at line 409 of file sertl.c.
References ASSERT, _STRING::Buffer, _STRING::Length, NT_SUCCESS, NtQuerySystemTime(), RTL_PAGED_CODE, and Status.
NTSTATUS RtlSetAttributesSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL Control, OUT PULONG Revision)
Definition at line 2130 of file sertl.c.
References RTL_PAGED_CODE, RtlSetControlSecurityDescriptor(), SE_VALID_CONTROL_BITS, SECURITY_DESCRIPTOR_REVISION, and STATUS_UNKNOWN_REVISION.
NTSTATUS RtlSetControlSecurityDescriptor (IN PSECURITY_DESCRIPTOR pSecurityDescriptor, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsOfInterest, IN SECURITY_DESCRIPTOR_CONTROL ControlBitsToSet)
Definition at line 2216 of file sertl.c.
References SE_VALID_CONTROL_BITS, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by RtlSetAttributesSecurityDescriptor().
NTSTATUS RtlSetDaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN DaclPresent, IN PACL Dacl OPTIONAL, IN BOOLEAN DaclDefaulted OPTIONAL)
Definition at line 2287 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR::Dacl, NULL, _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, STATUS_INVALID_SECURITY_DESCR, STATUS_SUCCESS, STATUS_UNKNOWN_REVISION, and TRUE.
NTSTATUS RtlSetGroupSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID Group OPTIONAL, IN BOOLEAN GroupDefaulted OPTIONAL)
Definition at line 2879 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, Group, _SECURITY_DESCRIPTOR::Group, NULL, _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, SE_GROUP_DEFAULTED, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, STATUS_INVALID_SECURITY_DESCR, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
NTSTATUS RtlSetOwnerSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID Owner OPTIONAL, IN BOOLEAN OwnerDefaulted OPTIONAL)
Definition at line 2707 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, NULL, _SECURITY_DESCRIPTOR::Owner, _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, SE_OWNER_DEFAULTED, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, STATUS_INVALID_SECURITY_DESCR, STATUS_SUCCESS, STATUS_UNKNOWN_REVISION, and TRUE.
NTSTATUS RtlSetSaclSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN SaclPresent, IN PACL Sacl OPTIONAL, IN BOOLEAN SaclDefaulted OPTIONAL)
Definition at line 2500 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, NULL, _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, _SECURITY_DESCRIPTOR::Sacl, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, STATUS_INVALID_SECURITY_DESCR, STATUS_SUCCESS, and STATUS_UNKNOWN_REVISION.
VOID RtlSetSecurityDescriptorRMControl (IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN PUCHAR RMControl OPTIONAL)
Definition at line 10396 of file sertl.c.
References ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR::Sbz1, and SE_RM_CONTROL_VALID.
PUCHAR RtlSubAuthorityCountSid (IN PSID Sid)
Definition at line 1177 of file sertl.c.
References RTL_PAGED_CODE, and _SID::SubAuthorityCount.
PULONG RtlSubAuthoritySid (IN PSID Sid, IN ULONG SubAuthority)
Definition at line 1147 of file sertl.c.
References RTL_PAGED_CODE, and RtlpSubAuthoritySid().
BOOLEAN RtlValidRelativeSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptorInput, IN ULONG SecurityDescriptorLength, IN SECURITY_INFORMATION RequiredInformation)
Definition at line 10066 of file sertl.c.
References _SECURITY_DESCRIPTOR_RELATIVE::Dacl, FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, _SID::Revision, RtlOffsetToPointer, RtlpAreControlBitsSet, RtlpValidateSDOffsetAndSize(), RtlValidAcl(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_DACL_PRESENT, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SID_MAX_SUB_AUTHORITIES, SID_REVISION, _SID::SubAuthorityCount, and TRUE.
BOOLEAN RtlValidSecurityDescriptor (IN PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 1931 of file sertl.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, Group, NULL, _SECURITY_DESCRIPTOR::Revision, RTL_PAGED_CODE, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlValidAcl(), RtlValidSid(), SECURITY_DESCRIPTOR_REVISION, and TRUE.
Referenced by RtlpConvertToAutoInheritSecurityObject().
BOOLEAN RtlValidSid (IN PSID Sid)
Definition at line 830 of file sertl.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, NULL, _SID::Revision, RTL_PAGED_CODE, SID_MAX_SUB_AUTHORITIES, SID_REVISION, _SID::SubAuthorityCount, and TRUE.
Referenced by RtlConvertSidToUnicodeString(), RtlLengthSidAsUnicodeString(), RtlpSetSecurityObject(), and RtlValidSecurityDescriptor().
Variable Documentation
const UCHAR RtlBaseAceType[]
Initial value:
= {
    ACCESS_ALLOWED_ACE_TYPE,
    ACCESS_DENIED_ACE_TYPE,
    SYSTEM_AUDIT_ACE_TYPE,
    SYSTEM_ALARM_ACE_TYPE,
    ACCESS_ALLOWED_ACE_TYPE,
    ACCESS_ALLOWED_ACE_TYPE,
    ACCESS_DENIED_ACE_TYPE,
    SYSTEM_AUDIT_ACE_TYPE,
    SYSTEM_ALARM_ACE_TYPE
}
Definition at line 343 of file sertl.c.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), and RtlpCopyEffectiveAce().
const UCHAR RtlIsSystemAceType[]
Initial value:
= {
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    TRUE
}
Definition at line 359 of file sertl.c.
Referenced by RtlpCompareKnownAces(), and RtlpCompareKnownObjectAces().