Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmhook.c File Reference
cmhook.c File Reference
#include "cmp.h"
Data Structures
struct _CM_ACTIVE_NOTIFY_THREAD
struct _CM_CALLBACK_CONTEXT_BLOCK
Macros
#define CM_MAX_CALLBACKS 100
#define CmpLockContext(Context) ExAcquirePushLockExclusive(&((Context)->ThreadListLock))
#define CmpUnlockContext(Context) ExReleasePushLock(&((Context)->ThreadListLock))
Typedefs
typedef struct _CM_ACTIVE_NOTIFY_THREAD CM_ACTIVE_NOTIFY_THREAD
typedef struct _CM_CALLBACK_CONTEXT_BLOCK CM_CALLBACK_CONTEXT_BLOCK
typedef struct _CM_ACTIVE_NOTIFY_THREAD * PCM_ACTIVE_NOTIFY_THREAD
typedef struct _CM_CALLBACK_CONTEXT_BLOCK * PCM_CALLBACK_CONTEXT_BLOCK
Functions
NTSTATUS CmpCallCallBacks (IN REG_NOTIFY_CLASS Type, IN PVOID Argument, IN BOOLEAN Wind, IN REG_NOTIFY_CLASS PostType, IN PVOID Object)
BOOLEAN CmpCheckRecursionAndRecordThreadInfo (PCM_CALLBACK_CONTEXT_BLOCK CallbackBlock, PCM_ACTIVE_NOTIFY_THREAD ActiveThreadInfo)
VOID CmpInitCallback (VOID)
NTSTATUS CmRegisterCallback (__in PEX_CALLBACK_FUNCTION Function, __in_opt PVOID Context, __out PLARGE_INTEGER Cookie)
NTSTATUS CmUnRegisterCallback (__in LARGE_INTEGER Cookie)
Variables
ULONG CmpCallBackCount = 0
EX_CALLBACK CmpCallBackVector [CM_MAX_CALLBACKS] = {0}
Macro Definition Documentation
#define CM_MAX_CALLBACKS 100
Definition at line 22 of file cmhook.c.
Referenced by CmpCallCallBacks(), CmpInitCallback(), CmRegisterCallback(), and CmUnRegisterCallback().
#define CmpLockContext (Context) ExAcquirePushLockExclusive(&((Context)->ThreadListLock))
Definition at line 36 of file cmhook.c.
Referenced by CmpCallCallBacks(), and CmpCheckRecursionAndRecordThreadInfo().
#define CmpUnlockContext (Context) ExReleasePushLock(&((Context)->ThreadListLock))
Definition at line 37 of file cmhook.c.
Referenced by CmpCallCallBacks(), and CmpCheckRecursionAndRecordThreadInfo().
Typedef Documentation
typedef struct _CM_ACTIVE_NOTIFY_THREAD CM_ACTIVE_NOTIFY_THREAD
typedef struct _CM_CALLBACK_CONTEXT_BLOCK CM_CALLBACK_CONTEXT_BLOCK
typedef struct _CM_ACTIVE_NOTIFY_THREAD * PCM_ACTIVE_NOTIFY_THREAD
typedef struct _CM_CALLBACK_CONTEXT_BLOCK * PCM_CALLBACK_CONTEXT_BLOCK
Function Documentation
NTSTATUS CmpCallCallBacks (IN REG_NOTIFY_CLASS Type, IN PVOID Argument, IN BOOLEAN Wind, IN REG_NOTIFY_CLASS PostType, IN PVOID Object)
Definition at line 196 of file cmhook.c.
References ASSERT, _CM_CALLBACK_CONTEXT_BLOCK::CallerContext, CM_MAX_CALLBACKS, CmpCheckRecursionAndRecordThreadInfo(), CmpLockContext, CmpUnlockContext, ExDereferenceCallBackBlock(), ExGetCallBackBlockContext(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), FALSE, InitializeListHead(), IsListEmpty, NT_SUCCESS, NULL, _REG_POST_OPERATION_INFORMATION::Object, PAGED_CODE, PsGetCurrentThread(), RemoveEntryList(), Status, _REG_POST_OPERATION_INFORMATION::Status, STATUS_SUCCESS, _CM_ACTIVE_NOTIFY_THREAD::Thread, _CM_ACTIVE_NOTIFY_THREAD::ThreadList, and TRUE.
Referenced by CmpDeleteKeyObject(), CmpParseKey(), NtDeleteKey(), NtDeleteValueKey(), NtEnumerateKey(), NtEnumerateValueKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), NtRenameKey(), NtSetInformationKey(), and NtSetValueKey().
BOOLEAN CmpCheckRecursionAndRecordThreadInfo (PCM_CALLBACK_CONTEXT_BLOCK CallbackBlock, PCM_ACTIVE_NOTIFY_THREAD ActiveThreadInfo)
Definition at line 349 of file cmhook.c.
References CmpLockContext, CmpUnlockContext, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, InsertTailList(), PAGED_CODE, _CM_ACTIVE_NOTIFY_THREAD::Thread, _CM_ACTIVE_NOTIFY_THREAD::ThreadList, _CM_CALLBACK_CONTEXT_BLOCK::ThreadListHead, and TRUE.
Referenced by CmpCallCallBacks().
VOID CmpInitCallback (VOID)
Definition at line 322 of file cmhook.c.
References CM_MAX_CALLBACKS, CmpCallBackCount, ExInitializeCallBack(), and PAGED_CODE.
Referenced by CmInitSystem1().
NTSTATUS CmRegisterCallback (__in PEX_CALLBACK_FUNCTION Function, __in_opt PVOID Context, __out PLARGE_INTEGER Cookie)
Definition at line 70 of file cmhook.c.
References _CM_CALLBACK_CONTEXT_BLOCK::CallerContext, CM_MAX_CALLBACKS, CmpCallBackCount, _CM_CALLBACK_CONTEXT_BLOCK::Cookie, ExAllocateCallBack(), ExAllocatePoolWithTag, ExCompareExchangeCallBack(), ExFreeCallBack(), ExFreePool(), ExInitializePushLock(), InitializeListHead(), InterlockedExchangeAdd(), KeQuerySystemTime(), NULL, PAGED_CODE, PagedPool, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _CM_CALLBACK_CONTEXT_BLOCK::ThreadListHead, and _CM_CALLBACK_CONTEXT_BLOCK::ThreadListLock.
NTSTATUS CmUnRegisterCallback (__in LARGE_INTEGER Cookie)
Definition at line 137 of file cmhook.c.
References CM_MAX_CALLBACKS, CmpCallBackCount, _CM_CALLBACK_CONTEXT_BLOCK::Cookie, ExCompareExchangeCallBack(), ExDereferenceCallBackBlock(), ExFreeCallBack(), ExFreePool(), ExGetCallBackBlockContext(), ExReferenceCallBackBlock(), ExWaitForCallBacks(), InterlockedExchangeAdd(), NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Variable Documentation
ULONG CmpCallBackCount = 0
Definition at line 44 of file cmhook.c.
Referenced by CmpInitCallback(), CmRegisterCallback(), and CmUnRegisterCallback().
EX_CALLBACK CmpCallBackVector[CM_MAX_CALLBACKS] = {0}
Definition at line 45 of file cmhook.c.