Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/modwrite.c File Reference
modwrite.c File Reference
#include "mi.h"
Data Structures
struct _MI_PAGEFILE_TRACES
struct _MM_WRITE_CLUSTER
Macros
#define MI_MAXIMUM_PRIORITY_BURST 32
#define MI_PAGEFILE_WRITE(ModWriterEntry, CurrentTime, IrpPriority, Status) MiSnapPagefileWrite(ModWriterEntry,CurrentTime,IrpPriority,Status)
#define MI_SLOW_CLUSTER_WRITES 10
#define MI_TRACK_PAGEFILE_WRITES 0x100
#define MINIMUM_PAGE_FILE_SIZE ((ULONG)(256*PAGE_SIZE))
#define ONEMB_IN_PAGES ((1024 * 1024) / PAGE_SIZE)
#define ROUND64_TO_PAGES(Size) (((ULONG64)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))
#define ROUND_UP(VALUE, ROUND)
Typedefs
typedef struct _MI_PAGEFILE_TRACES MI_PAGEFILE_TRACES
typedef struct _MM_WRITE_CLUSTER MM_WRITE_CLUSTER
typedef enum _MODIFIED_WRITER_OBJECT MODIFIED_WRITER_OBJECT
typedef struct _MI_PAGEFILE_TRACES * PMI_PAGEFILE_TRACES
typedef struct _MM_WRITE_CLUSTER * PMM_WRITE_CLUSTER
Enumerations
enum _MODIFIED_WRITER_OBJECT { NormalCase, MappedPagesNeedWriting, ModifiedWriterMaximumObject }
Functions
SIZE_T MiAttemptPageFileExtension (IN ULONG PageFileNumber, IN SIZE_T SizeNeeded, IN LOGICAL Maximum)
VOID MiAttemptPageFileReduction (VOID)
LOGICAL MiCancelWriteOfMappedPfn (IN PFN_NUMBER PageToStop, IN KIRQL OldIrql)
NTSTATUS MiCheckPageFileMapping (IN PFILE_OBJECT File)
VOID MiClusterWritePages (IN PMMPFN Pfn1, IN PFN_NUMBER PageFrameIndex, IN PMM_WRITE_CLUSTER WriteCluster, IN ULONG Size)
VOID MiContractPagingFiles (VOID)
VOID MiExtendPagingFileMaximum (IN ULONG PageFileNumber, IN PRTL_BITMAP NewBitmap)
SIZE_T MiExtendPagingFiles (IN PMMPAGE_FILE_EXPANSION PageExpand)
VOID MiFinishPageFileExtension (IN ULONG PageFileNumber, IN PFN_NUMBER AdditionalAllocation)
VOID MiFlushAllPages (VOID)
VOID MiGatherMappedPages (IN KIRQL OldIrql)
VOID MiGatherPagefilePages (IN PMMMOD_WRITER_MDL_ENTRY ModWriterEntry, IN PRTL_BITMAP Bitmap)
VOID MiInsertPageFileInList (VOID)
LOGICAL MiIssuePageExtendRequest (IN PMMPAGE_FILE_EXPANSION PageExtend)
VOID MiIssuePageExtendRequestNoWait (IN PFN_NUMBER SizeInPages)
VOID MiLdwPopupWorker (IN PVOID Context)
VOID MiMappedPageWriter (IN PVOID StartContext)
VOID MiModifiedPageWriter (IN PVOID StartContext)
VOID MiModifiedPageWriterTimerDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID MiModifiedPageWriterWorker (VOID)
VOID MiPageFileFull (VOID)
VOID MiReleaseModifiedWriter (VOID)
VOID FORCEINLINE MiSnapPagefileWrite (IN PMMMOD_WRITER_MDL_ENTRY ModWriterEntry, IN PLARGE_INTEGER CurrentTime, IN IO_PAGING_PRIORITY IrpPriority, IN NTSTATUS Status)
VOID MiWriteComplete (IN PVOID Context, IN PIO_STATUS_BLOCK IoStatus, IN ULONG Reserved)
NTSTATUS MiZeroPageFileFirstPage (IN PFILE_OBJECT File)
BOOLEAN MmDisableModifiedWriteOfSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
BOOLEAN MmEnableModifiedWriteOfSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer)
NTSTATUS MmGetPageFileInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
HANDLE MmGetSystemPageFile (VOID)
LOGICAL MmIsFileObjectAPagingFile (IN PFILE_OBJECT FileObject)
NTSTATUS NtCreatePagingFile (__in PUNICODE_STRING PageFileName, __in PLARGE_INTEGER MinimumSize, __in PLARGE_INTEGER MaximumSize, __in ULONG Priority)
Variables
POBJECT_TYPE IoFileObjectType
LONG MiClusterWritesDisabled
LOGICAL MiDrainingMappedWrites = FALSE
LOGICAL MiFirstPageFileCreatedAndReady = FALSE
NTSTATUS MiLastMappedWriteError
NTSTATUS MiLastModifiedWriteError
ULONG MiMappedWriteBurstCount
ULONG MiModifiedWriteBurstCount
MMPAGE_FILE_EXPANSION MiPageFileContract
LONG MiPageFileTraceIndex
MI_PAGEFILE_TRACES MiPageFileTraces [MI_TRACK_PAGEFILE_WRITES]
KEVENT MmMappedFileIoComplete
KEVENT MmMappedPageWriterEvent
LIST_ENTRY MmMappedPageWriterList
ULONG MmNumberOfMappedMdls
SIZE_T MmSystemCommitReserve
BOOLEAN MmSystemPageFileLocated
ULONG MmSystemShutdown
LONG MmWriteAllModifiedPages
Macro Definition Documentation
#define MI_MAXIMUM_PRIORITY_BURST 32
Definition at line 66 of file modwrite.c.
Referenced by MiGatherPagefilePages(), and MiMappedPageWriter().
#define MI_PAGEFILE_WRITE (ModWriterEntry, CurrentTime, IrpPriority, Status) MiSnapPagefileWrite(ModWriterEntry,CurrentTime,IrpPriority,Status)
Definition at line 214 of file modwrite.c.
Referenced by MiGatherPagefilePages(), and MiWriteComplete().
#define MI_SLOW_CLUSTER_WRITES 10
Definition at line 54 of file modwrite.c.
Referenced by MiWriteComplete().
#define MI_TRACK_PAGEFILE_WRITES 0x100
Definition at line 160 of file modwrite.c.
Referenced by MiSnapPagefileWrite().
#define MINIMUM_PAGE_FILE_SIZE ((ULONG)(256*PAGE_SIZE))
Definition at line 153 of file modwrite.c.
Referenced by NtCreatePagingFile().
#define ONEMB_IN_PAGES ((1024 * 1024) / PAGE_SIZE)
Definition at line 56 of file modwrite.c.
Referenced by MiIssuePageExtendRequestNoWait().
#define ROUND64_TO_PAGES (Size) (((ULONG64)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))
Referenced by NtCreatePagingFile().
#define ROUND_UP (VALUE, ROUND)
Value:
((ULONG)(((ULONG)VALUE + \
                               ((ULONG)ROUND - 1L)) & (~((ULONG)ROUND - 1L))))
Definition at line 4649 of file modwrite.c.
Referenced by MmGetPageFileInformation().
Typedef Documentation
typedef struct _MI_PAGEFILE_TRACES MI_PAGEFILE_TRACES
typedef struct _MM_WRITE_CLUSTER MM_WRITE_CLUSTER
typedef enum _MODIFIED_WRITER_OBJECT MODIFIED_WRITER_OBJECT
typedef struct _MI_PAGEFILE_TRACES * PMI_PAGEFILE_TRACES
typedef struct _MM_WRITE_CLUSTER * PMM_WRITE_CLUSTER
Enumeration Type Documentation
enum _MODIFIED_WRITER_OBJECT
Enumerator
NormalCase
MappedPagesNeedWriting
ModifiedWriterMaximumObject
Definition at line 21 of file modwrite.c.
Function Documentation
SIZE_T MiAttemptPageFileExtension (IN ULONG PageFileNumber, IN SIZE_T SizeNeeded, IN LOGICAL Maximum)
Definition at line 1395 of file modwrite.c.
References ASSERT, _FILE_FS_SIZE_INFORMATION::AvailableAllocationUnits, _FILE_FS_SIZE_INFORMATION::BytesPerSector, DISPATCH_LEVEL, _FILE_END_OF_FILE_INFORMATION::EndOfFile, FALSE, FileEndOfFileInformation, FileFsSizeInformation, _LARGE_INTEGER::HighPart, IoQueryVolumeInformation(), IoSetInformation(), KdPrint, KeGetCurrentIrql(), _LARGE_INTEGER::LowPart, _MMPAGING_FILE::MaximumSize, MiFinishPageFileExtension(), MmMinimumFreeDiskSpace, MmPageFileExtension, MmPagingFile, NT_SUCCESS, PAGE_SHIFT, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlExtendedIntegerMultiply(), _FILE_FS_SIZE_INFORMATION::SectorsPerAllocationUnit, _MMPAGING_FILE::Size, and STATUS_SUCCESS.
Referenced by MiExtendPagingFiles().
VOID MiAttemptPageFileReduction (VOID)
Definition at line 1865 of file modwrite.c.
References _FILE_ALLOCATION_INFORMATION::AllocationSize, ASSERT, _MMPAGING_FILE::Bitmap, DbgPrintEx(), DISPATCH_LEVEL, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _MMPAGING_FILE::Entry, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _MMPAGING_FILE::File, FileAllocationInformation, _MMPAGING_FILE::FreeSpace, _LARGE_INTEGER::HighPart, InterlockedExchangeAddSizeT, IoSetInformation(), KeGetCurrentIrql(), _MMMOD_WRITER_MDL_ENTRY::LastPageToWrite, _MMDEREFERENCE_SEGMENT_HEADER::Lock, LOCK_PFN, _LARGE_INTEGER::LowPart, MI_CONTRACT_PAGEFILES, MiChargeTemporaryCommitmentForReduction(), _MMPAGING_FILE::MinimumSize, MiReturnCommitment, MM_PAGING_FILE_MDLS, MmDereferenceSegmentHeader, MmMinimumPageFileReduction, MmNumberOfPagingFiles, MmPagingFile, MmTotalCommitLimit, MmTotalCommittedPages, PAGE_SHIFT, PAGE_SIZE, _LARGE_INTEGER::QuadPart, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, RtlAreBitsClear(), RtlClearBits(), RtlSetBits(), _MMPAGING_FILE::Size, STATUS_SUCCESS, TRUE, and UNLOCK_PFN.
Referenced by MiDereferenceSegmentThread(), and MiRemoveUnusedSegments().
LOGICAL MiCancelWriteOfMappedPfn (IN PFN_NUMBER PageToStop, IN KIRQL OldIrql)
Definition at line 2753 of file modwrite.c.
References APC_LEVEL, _MDL::ByteCount, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _IO_STATUS_BLOCK::Information, _MMMOD_WRITER_MDL_ENTRY::IoStatus, KeLowerIrql, KeRaiseIrql, LOCK_PFN, _MMMOD_WRITER_MDL_ENTRY::Mdl, MiWriteComplete(), PAGE_SHIFT, RemoveEntryList(), _IO_STATUS_BLOCK::Status, STATUS_FILE_LOCK_CONFLICT, TRUE, _MMMOD_WRITER_MDL_ENTRY::u, and UNLOCK_PFN.
Referenced by MmPurgeSection().
NTSTATUS MiCheckPageFileMapping (IN PFILE_OBJECT File)
Definition at line 4749 of file modwrite.c.
References LOCK_PFN, NULL, STATUS_INCOMPATIBLE_FILE_MAP, STATUS_SUCCESS, and UNLOCK_PFN.
Referenced by NtCreatePagingFile().
VOID MiClusterWritePages (IN PMMPFN Pfn1, IN PFN_NUMBER PageFrameIndex, IN PMM_WRITE_CLUSTER WriteCluster, IN ULONG Size)
VOID MiContractPagingFiles (VOID)
Definition at line 1781 of file modwrite.c.
References _MMPAGE_FILE_EXPANSION::DereferenceList, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, InsertTailList(), KeReleaseSemaphore(), _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMDEREFERENCE_SEGMENT_HEADER::Lock, MI_CONTRACT_PAGEFILES, MiPageFileContract, MmDereferenceSegmentHeader, MmMinimumPageFileReduction, MmNumberOfPagingFiles, MmPagingFile, MmTotalCommitLimit, MmTotalCommittedPages, NULL, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, _MMPAGE_FILE_EXPANSION::Segment, and _MMDEREFERENCE_SEGMENT_HEADER::Semaphore.
Referenced by MmDeleteProcessAddressSpace().
VOID MiExtendPagingFileMaximum (IN ULONG PageFileNumber, IN PRTL_BITMAP NewBitmap)
Definition at line 1254 of file modwrite.c.
References ASSERT, _MMPAGING_FILE::Bitmap, _RTL_BITMAP::Buffer, InterlockedExchangeAddSizeT, IsListEmpty, LOCK_PFN, _MMPAGING_FILE::MaximumSize, MiRemoveBitMap, MiUpdateModifiedWriterMdls(), MmFreePagingSpaceLow, MmPagingFile, MmTotalCommitLimitMaximum, NULL, RtlCopyMemory, RtlSetAllBits(), _RTL_BITMAP::SizeOfBitMap, and UNLOCK_PFN.
Referenced by NtCreatePagingFile().
SIZE_T MiExtendPagingFiles (IN PMMPAGE_FILE_EXPANSION PageExpand)
Definition at line 1587 of file modwrite.c.
References ASSERT, FALSE, InterlockedExchange(), InterlockedExchangeAddSizeT, _MMPAGING_FILE::MaximumSize, MI_EXTEND_ANY_PAGEFILE, MiAttemptPageFileExtension(), MmNumberOfPagingFiles, MmPagingFile, MmSystemCommitReserve, MmTotalCommitLimit, MmTotalCommittedPages, _MMPAGING_FILE::Size, and TRUE.
Referenced by MiDereferenceSegmentThread(), and MiRemoveUnusedSegments().
VOID MiFinishPageFileExtension (IN ULONG PageFileNumber, IN PFN_NUMBER AdditionalAllocation)
Definition at line 1337 of file modwrite.c.
References ASSERT, _MMPAGING_FILE::Bitmap, _MMPAGING_FILE::FreeSpace, LOCK_PFN, MiUpdateModifiedWriterMdls(), MmPagingFile, RtlCheckBit, RtlClearBits(), _MMPAGING_FILE::Size, and UNLOCK_PFN.
Referenced by MiAttemptPageFileExtension().
VOID MiFlushAllPages (VOID)
Definition at line 4976 of file modwrite.c.
References FALSE, InterlockedDecrement, InterlockedIncrement, KeDelayExecutionThread(), KernelMode, KeSetEvent(), Mm30Milliseconds, MmModifiedPageListHead, MmModifiedPageWriterEvent, MmNumberOfPagingFiles, MmWriteAllModifiedPages, and _MMPFNLIST::Total.
Referenced by MiAllocateLargeZeroPages(), MiEmptyWorkingSet(), MiFindContiguousPages(), and MmGatherMemoryForHibernate().
VOID MiGatherMappedPages (IN KIRQL OldIrql)
Definition at line 3401 of file modwrite.c.
References APC_LEVEL, ASSERT, _MMSECTION_FLAGS::BeingPurged, BYTE_OFFSET, _MDL::ByteCount, BYTES_TO_PAGES, _SUBSECTION::ControlArea, _MMMOD_WRITER_MDL_ENTRY::ControlArea, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMPFN::e2, FALSE, _MMMOD_WRITER_MDL_ENTRY::File, _CONTROL_AREA::FilePointer, _MMMOD_WRITER_MDL_ENTRY::FileResource, _CONTROL_AREA::Flags, _MMPFNLIST::Flink, _MMPTE::Hard, _LARGE_INTEGER::HighPart, _MMSECTION_FLAGS::Image, _IO_STATUS_BLOCK::Information, InsertTailList(), _MMMOD_WRITER_MDL_ENTRY::IoStatus, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrql, KeSetEvent(), _MMMOD_WRITER_MDL_ENTRY::LastByte, _MMMOD_WRITER_MDL_ENTRY::Links, _MMMOD_WRITER_LISTHEAD::ListHead, _LARGE_INTEGER::LowPart, _MMMOD_WRITER_MDL_ENTRY::Mdl, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SET_MODIFIED, MiClusterWritesDisabled, MiGetSubsectionAddress, MiInsertPageInList(), MiIsProtoAddressValid(), MiMapPageInHyperSpaceAtDpc(), MiStartingOffset(), MiUnlinkPageFromList(), MiUnmapPageInHyperSpaceFromDpc, MiWriteComplete(), MM_EMPTY_LIST, MmInitializeMdl, MmMappedFileHeader, _KPRCB::MmMappedPagesWriteCount, _KPRCB::MmMappedWriteIoCount, MmModifiedNoWritePageListHead, MmModifiedPageListHead, MmModifiedWriteClusterSize, MmNumberOfMappedMdlsInUse, _MMPFNENTRY::Modified, _CONTROL_AREA::ModifiedWriteCount, _MMSECTION_FLAGS::NoModifiedWriting, NULL, _CONTROL_AREA::NumberOfPfnReferences, _MMPFN::OriginalPte, _MMMOD_WRITER_MDL_ENTRY::Page, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _SUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, RemoveHeadList(), _MDL::Size, _MMPTE::Soft, _IO_STATUS_BLOCK::Status, STATUS_FILE_LOCK_CONFLICT, _SUBSECTION::SubsectionBase, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _CONTROL_AREA::u, _MMMOD_WRITER_MDL_ENTRY::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _MMPFNENTRY::WriteInProgress, and _MMMOD_WRITER_MDL_ENTRY::WriteOffset.
Referenced by MiModifiedPageWriterWorker().
VOID MiGatherPagefilePages (IN PMMMOD_WRITER_MDL_ENTRY ModWriterEntry, IN PRTL_BITMAP Bitmap)
Definition at line 3836 of file modwrite.c.
References APC_LEVEL, ASSERT, _MMPAGING_FILE::Bitmap, _MMPAGING_FILE::CurrentUsage, _MMPFN::e1, FALSE, _MMPAGING_FILE::File, _MMPAGING_FILE::FreeSpace, InsertTailList(), InterlockedExchangeAdd(), InterlockedIncrement, IoAsynchronousPageWrite(), IoPagingPriorityHigh, IoPagingPriorityNormal, IsListEmpty, KdPrint, KeGetCurrentPrcb(), KeLowerIrql, KeQuerySystemTime(), KeRaiseIrql, KeSetEvent(), LOCK_PFN, MDL_PAGES_LOCKED, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_GET_MODIFIED_PAGE_ANY_COLOR, MI_GET_MODIFIED_PAGE_BY_COLOR, MI_GET_NEXT_COLOR, MI_MAXIMUM_PRIORITY_BURST, MI_PAGEFILE_WRITE, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PAGING_FILE_INFO, MiClusterWritesDisabled, MiModifiedWriteBurstCount, MiPageFileFull(), MiRemoveBitMap, MiUnlinkPageFromList(), MiWriteComplete(), MM_EMPTY_LIST, MM_HIGH_LIMIT, MM_PLENTY_FREE_LIMIT, MM_TIGHT_LIMIT, MmAvailablePages, _KPRCB::MmDirtyPagesWriteCount, _KPRCB::MmDirtyWriteIoCount, MmFreePagingSpaceLow, MmInitializeMdl, MmModifiedWriteClusterSize, MmNumberOfActiveMdlEntries, MmPagingFileDebug, MmTotalPagesForPagingFile, NO_BITS_FOUND, NT_ERROR, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPAGING_FILE::PageFileNumber, PASSIVE_LEVEL, _MMPAGING_FILE::PeakUsage, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteAddress, _LARGE_INTEGER::QuadPart, _MMPAGING_FILE::ReferenceCount, RtlClearBits(), RtlFindClearBits(), RtlFindClearBitsAndSet(), _MMPTE::Soft, Status, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, and _MMPFNENTRY::WriteInProgress.
Referenced by MiModifiedPageWriterWorker().
VOID MiInsertPageFileInList (VOID)
Definition at line 4793 of file modwrite.c.
References _MMMOD_WRITER_MDL_ENTRY::CurrentList, _MMPAGING_FILE::Entry, _MMMOD_WRITER_LISTHEAD::Event, FALSE, _MMPAGING_FILE::FreeSpace, InsertTailList(), InterlockedExchangeAddSizeT, IsListEmpty, KeSetEvent(), _MMMOD_WRITER_MDL_ENTRY::Links, _MMMOD_WRITER_LISTHEAD::ListHead, LOCK_PFN, _MMPAGING_FILE::MaximumSize, MM_PAGING_FILE_MDLS, MmNumberOfActiveMdlEntries, MmNumberOfPagingFiles, MmPagingFile, MmPagingFileHeader, MmTotalCommitLimit, MmTotalCommitLimitMaximum, _MMPAGING_FILE::ReferenceCount, and UNLOCK_PFN.
Referenced by NtCreatePagingFile().
LOGICAL MiIssuePageExtendRequest (IN PMMPAGE_FILE_EXPANSION PageExtend)
Definition at line 5028 of file modwrite.c.
References ExAcquireSpinLock, Executive, ExReleaseSpinLock, FALSE, _LIST_ENTRY::Flink, InsertHeadList(), KdPrint, KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMDEREFERENCE_SEGMENT_HEADER::Lock, MiDereferenceSegmentThread(), MmDereferenceSegmentHeader, MmNumberOfPagingFiles, MmOneSecond, MmPagingFile, MmTwentySeconds, NULL, PsGetCurrentThread(), RemoveEntryList(), _MMDEREFERENCE_SEGMENT_HEADER::Semaphore, _ETHREAD::StartAddress, STATUS_TIMEOUT, and TRUE.
Referenced by MiChargeCommitment(), and NtCreatePagingFile().
VOID MiIssuePageExtendRequestNoWait (IN PFN_NUMBER SizeInPages)
Definition at line 5170 of file modwrite.c.
References _MMPAGE_FILE_EXPANSION::ActualExpansion, ASSERT, _MMPAGE_FILE_EXPANSION::DereferenceList, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _MMPAGE_FILE_EXPANSION::InProgress, InsertHeadList(), InterlockedCompareExchange(), KeReleaseSemaphore(), _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMDEREFERENCE_SEGMENT_HEADER::Lock, MmAttemptForCantExtend, MmDereferenceSegmentHeader, ONEMB_IN_PAGES, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, and _MMDEREFERENCE_SEGMENT_HEADER::Semaphore.
Referenced by MiAllocatePoolPages(), MiChargeCommitment(), MiChargeCommitmentCantExpand(), and MmResourcesAvailable().
VOID MiLdwPopupWorker (IN PVOID Context)
Definition at line 2180 of file modwrite.c.
References _UNICODE_STRING::Buffer, ExFreePool(), FALSE, _FILE_OBJECT::FileName, _MM_LDW_WORK_CONTEXT::FileObject, IoQueryFileDosDeviceName(), IoRaiseInformationalHardError(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MiDereferenceLastChanceLdw(), _OBJECT_NAME_INFORMATION::Name, NULL, ObDereferenceObject(), PAGED_CODE, Status, STATUS_LOST_WRITEBEHIND_DATA, and STATUS_SUCCESS.
Referenced by MiNoPagesLastChance(), and MiWriteComplete().
VOID MiMappedPageWriter (IN PVOID StartContext)
Definition at line 4336 of file modwrite.c.
References APC_LEVEL, _MMMOD_WRITER_MDL_ENTRY::ControlArea, _MMSECTION_FLAGS::FailAllIo, FALSE, _MMMOD_WRITER_MDL_ENTRY::File, _MMMOD_WRITER_MDL_ENTRY::FileResource, _CONTROL_AREA::Flags, FsRtlAcquireFileForModWriteEx(), FsRtlSetTopLevelIrpForModWriter, _IO_STATUS_BLOCK::Information, IoAsynchronousPageWrite(), IoPagingPriorityHigh, IoPagingPriorityNormal, _MMMOD_WRITER_MDL_ENTRY::IoStatus, IsListEmpty, KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeSetPriorityThread(), KeWaitForSingleObject(), _MMMOD_WRITER_MDL_ENTRY::LastByte, LOCK_PFN, LOW_REALTIME_PRIORITY, _MMMOD_WRITER_MDL_ENTRY::Mdl, _ETHREAD::MemoryMaker, MI_MAXIMUM_PRIORITY_BURST, MiMappedWriteBurstCount, MiWriteComplete(), MM_HIGH_LIMIT, MM_PLENTY_FREE_LIMIT, MM_TIGHT_LIMIT, MmAvailablePages, NotificationEvent, NT_ERROR, NT_SUCCESS, NULL, PsGetCurrentThread(), RemoveHeadList(), Status, _IO_STATUS_BLOCK::Status, STATUS_FILE_LOCK_CONFLICT, STATUS_UNSUCCESSFUL, _ETHREAD::Tcb, TRUE, _CONTROL_AREA::u, _MMMOD_WRITER_MDL_ENTRY::u, UNLOCK_PFN, UNREFERENCED_PARAMETER, _MMMOD_WRITER_MDL_ENTRY::WriteOffset, and WrVirtualMemory.
Referenced by MiModifiedPageWriter().
VOID MiModifiedPageWriter (IN PVOID StartContext)
Definition at line 2847 of file modwrite.c.
References _MMMOD_WRITER_LISTHEAD::Event, ExAllocatePoolWithTag, FALSE, _LARGE_INTEGER::HighPart, InitializeListHead(), InitializeObjectAttributes, InsertTailList(), KeBugCheckEx(), KeDelayExecutionThread(), KeGetCurrentThread(), KeInitializeEvent(), KernelMode, KeSetPriorityThread(), _MMMOD_WRITER_MDL_ENTRY::Links, _MMMOD_WRITER_LISTHEAD::ListHead, LOW_REALTIME_PRIORITY, _LARGE_INTEGER::LowPart, MEMORY_MANAGEMENT, MiMappedPageWriter(), MiModifiedPageWriterWorker(), MmFreePagingSpaceLow, MmMappedFileHeader, MmModifiedWriteClusterSize, MmNumberOfMappedMdls, MmNumberOfPhysicalPages, MmPagingFileHeader, MmSystemShutdown, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _MMMOD_WRITER_MDL_ENTRY::PagingFile, _MMMOD_WRITER_MDL_ENTRY::PagingListHead, PsCreateSystemThread(), Status, THREAD_ALL_ACCESS, UNREFERENCED_PARAMETER, and ZwClose().
Referenced by MmInitSystem().
VOID MiModifiedPageWriterTimerDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 2988 of file modwrite.c.
References FALSE, KeSetEvent(), LOCK_PFN_AT_DPC, MiMappedPagesTooOldEvent, MiTimerPending, TRUE, UNLOCK_PFN_FROM_DPC, and UNREFERENCED_PARAMETER.
Referenced by MmInitSystem().
VOID MiModifiedPageWriterWorker (VOID)
Definition at line 3035 of file modwrite.c.
References ASSERT, _MMPAGING_FILE::Bitmap, _MMMOD_WRITER_LISTHEAD::Event, FALSE, _LIST_ENTRY::Flink, _MMPFNLIST::Flink, IsListEmpty, KeClearEvent(), KeDelayExecutionThread(), KernelMode, KeSetTimerEx(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), _MMMOD_WRITER_MDL_ENTRY::Links, _MMMOD_WRITER_LISTHEAD::ListHead, LOCK_PFN, MappedPagesNeedWriting, _ETHREAD::MemoryMaker, MiDrainingMappedWrites, MiFirstPageFileCreatedAndReady, MiGatherMappedPages(), MiGatherPagefilePages(), MiMappedPagesTooOldEvent, MiModifiedPageLife, MiModifiedPageWriterTimer, MiModifiedPageWriterTimerDpc, MiTimerPending, Mm30Milliseconds, MM_EMPTY_LIST, MmMappedFileHeader, MmModifiedPageListHead, MmModifiedPageWriterEvent, MmModifiedWriteClusterSize, MmNumberOfPagingFiles, MmPagingFileHeader, MmShortTime, MmSystemShutdown, MmTotalPagesForPagingFile, MmWriteAllModifiedPages, ModifiedWriterMaximumObject, NormalCase, NULL, _MMMOD_WRITER_MDL_ENTRY::PagingFile, PsGetCurrentThread(), _MMPAGING_FILE::ReferenceCount, RemoveHeadList(), _MMPFNLIST::Total, TRUE, UNLOCK_PFN, WaitAny, WrFreePage, and WrPageOut.
Referenced by MiModifiedPageWriter().
VOID MiPageFileFull (VOID)
Definition at line 4859 of file modwrite.c.
References _MMPAGING_FILE::FreeSpace, MiCauseOverCommitPopup(), MiChargeCommitmentCantExpand(), MiReturnCommitment, MM_DBG_COMMIT_PAGEFILE_FULL, MM_DBG_COMMIT_RETURN_PAGEFILE_FULL, MM_TRACK_COMMIT, MmNumberOfPagingFiles, MmPagingFile, MmTotalCommitLimit, MmTotalCommittedPages, _MMPAGING_FILE::Size, and TRUE.
Referenced by MiGatherPagefilePages().
VOID MiReleaseModifiedWriter (VOID)
Definition at line 227 of file modwrite.c.
References LOCK_PFN, MiFirstPageFileCreatedAndReady, TRUE, and UNLOCK_PFN.
Referenced by NtCreatePagingFile().
VOID FORCEINLINE MiSnapPagefileWrite (IN PMMMOD_WRITER_MDL_ENTRY ModWriterEntry, IN PLARGE_INTEGER CurrentTime, IN IO_PAGING_PRIORITY IrpPriority, IN NTSTATUS Status)
Definition at line 184 of file modwrite.c.
References _MI_PAGEFILE_TRACES::AvailablePages, _MI_PAGEFILE_TRACES::CurrentTime, Index, InterlockedIncrement, _MI_PAGEFILE_TRACES::IrpPriority, KeGetCurrentThread(), _MI_PAGEFILE_TRACES::MdlHack, MI_TRACK_PAGEFILE_WRITES, MiPageFileTraceIndex, MmAvailablePages, MmModifiedNoWritePageListHead, MmModifiedPageListHead, MmTotalPagesForPagingFile, _MI_PAGEFILE_TRACES::ModifiedNoWritePages, _MI_PAGEFILE_TRACES::ModifiedPagefilePages, _MI_PAGEFILE_TRACES::ModifiedPagesTotal, _MI_PAGEFILE_TRACES::Priority, _KTHREAD::Priority, RtlCopyMemory, Status, _MI_PAGEFILE_TRACES::Status, and _MMPFNLIST::Total.
VOID MiWriteComplete (IN PVOID Context, IN PIO_STATUS_BLOCK IoStatus, IN ULONG Reserved)
Definition at line 2260 of file modwrite.c.
References ASSERT, _MDL::ByteCount, _MMMOD_WRITER_MDL_ENTRY::ControlArea, _MMMOD_WRITER_MDL_ENTRY::CurrentList, DbgBreakPoint(), DbgPrintEx(), DelayedWorkQueue, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMMOD_WRITER_LISTHEAD::Event, ExAllocatePoolWithTag, ExInitializeWorkItem, ExQueueWorkItem(), _MMSECTION_FLAGS::FailAllIo, FALSE, _MMMOD_WRITER_MDL_ENTRY::File, _MM_LDW_WORK_CONTEXT::FileObject, _CONTROL_AREA::FilePointer, _MMMOD_WRITER_MDL_ENTRY::FileResource, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMPFNLIST::Flink, _MMPAGING_FILE::FreeSpace, FsRtlReleaseFileForModWrite(), GET_PAGING_FILE_NUMBER, GET_PAGING_FILE_OFFSET, InsertTailList(), InterlockedCompareExchange(), IsListEmpty, KdPrint, KeAreAllApcsDisabled(), KeDelayExecutionThread(), KePulseEvent(), KeQuerySystemTime(), KernelMode, KeSetEvent(), _MMMOD_WRITER_MDL_ENTRY::LastPageToWrite, _MMMOD_WRITER_MDL_ENTRY::Links, _MMMOD_WRITER_LISTHEAD::ListHead, LOCK_PFN, _MDL::MappedSystemVa, _MMMOD_WRITER_MDL_ENTRY::Mdl, MDL_MAPPED_TO_SYSTEM_VA, _MDL::MdlFlags, MI_IS_PFN_DELETED, MI_PAGEFILE_WRITE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MI_SLOW_CLUSTER_WRITES, MiCheckControlArea(), MiClusterWritesDisabled, MiDrainingMappedWrites, MiGetPteAddress, MiLastMappedWriteError, MiLastModifiedWriteError, MiLdwPopupWorker(), MiMappedPagesTooOldEvent, MiReleasePageFileSpace(), MiTimerPending, Mm30Milliseconds, MM_COPY_ON_WRITE_MASK, MM_EMPTY_LIST, MM_PROTECTION_WRITE_MASK, MM_USABLE_PAGES_FREE, MmFreePagingSpaceLow, MmIsRetryIoStatus, MmModifiedPageListHead, MmNumberOfActiveMdlEntries, MmNumberOfMappedMdlsInUse, MmPagingFileDebug, MmPagingFileHeader, MmUnmapLockedPages(), _MMPFNENTRY::Modified, _CONTROL_AREA::ModifiedWriteCount, _MMSECTION_FLAGS::Networked, NonPagedPool, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfPfnReferences, ObReferenceObject, _MMPFN::OriginalPte, _MMMOD_WRITER_MDL_ENTRY::Page, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMMOD_WRITER_MDL_ENTRY::PagingFile, _MMMOD_WRITER_MDL_ENTRY::PagingListHead, PDE_BASE, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, PTE_TOP, _MMPFN::PteAddress, ReadForWriteAccess, RemoveEntryList(), _MMSECTION_FLAGS::SetMappedFileIoComplete, _MMPTE::Soft, Status, STATUS_FILE_INVALID, STATUS_FILE_LOCK_CONFLICT, STATUS_MEDIA_WRITE_PROTECTED, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u3, UNLOCK_PFN, UNREFERENCED_PARAMETER, _MM_LDW_WORK_CONTEXT::WorkItem, and _MMPFNENTRY::WriteInProgress.
Referenced by MiCancelWriteOfMappedPfn(), MiGatherMappedPages(), MiGatherPagefilePages(), and MiMappedPageWriter().
NTSTATUS MiZeroPageFileFirstPage (IN PFILE_OBJECT File)
Definition at line 249 of file modwrite.c.
References FALSE, HighPagePriority, IoSynchronousPageWrite(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), KeZeroSinglePage, _MDL::MappedSystemVa, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, _MDL::MdlFlags, MiGetPageForHeader(), MiRemoveImageHeaderPage(), MiZeroPhysicalPage(), MmCreateMdl(), MmGetSystemAddressForMdlSafe, MmUnmapLockedPages(), NotificationEvent, NT_SUCCESS, NULL, PAGE_SIZE, Status, _IO_STATUS_BLOCK::Status, and WrVirtualMemory.
Referenced by NtCreatePagingFile().
BOOLEAN MmDisableModifiedWriteOfSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
Definition at line 4491 of file modwrite.c.
References _CONTROL_AREA::Flags, LOCK_PFN, _MMSECTION_FLAGS::NoModifiedWriting, NULL, _CONTROL_AREA::NumberOfMappedViews, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by CcInitializeCacheMap(), CcSetPrivateWriteFile(), and CmPrefetchHivePages().
BOOLEAN MmEnableModifiedWriteOfSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer)
Definition at line 4562 of file modwrite.c.
References _SUBSECTION::ControlArea, _CONTROL_AREA::Flags, _MMPFNLIST::Flink, _MMPFN::Flink, LOCK_PFN2, MI_PFN_ELEMENT, MiGetSubsectionAddress, MiInsertPageInList(), MiUnlinkPageFromList(), MM_EMPTY_LIST, MmModifiedNoWritePageListHead, MmModifiedPageListHead, _MMSECTION_FLAGS::NoModifiedWriting, NULL, _MMPFN::OriginalPte, _MMPFNLIST::Total, TRUE, _CONTROL_AREA::u, _MMPFN::u1, and UNLOCK_PFN2.
Referenced by CcUninitializeCacheMap().
NTSTATUS MmGetPageFileInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 4652 of file modwrite.c.
References _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MmNumberOfPagingFiles, MmPagingFile, PAGED_CODE, _MMPAGING_FILE::PageFileName, _MMPAGING_FILE::PeakUsage, ROUND_UP, RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtQuerySystemInformation().
HANDLE MmGetSystemPageFile (VOID)
Definition at line 1163 of file modwrite.c.
References _MMPAGING_FILE::FileHandle, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), MmNumberOfPagingFiles, MmPageFileCreationLock, MmPagingFile, NULL, and PAGED_CODE.
LOGICAL MmIsFileObjectAPagingFile (IN PFILE_OBJECT FileObject)
Definition at line 1206 of file modwrite.c.
References FALSE, _MMPAGING_FILE::File, MmNumberOfPagingFiles, MmPagingFile, and TRUE.
Referenced by FsRtlIsPagingFile(), and IoPageRead().
NTSTATUS NtCreatePagingFile (__in PUNICODE_STRING PageFileName, __in PLARGE_INTEGER MinimumSize, __in PLARGE_INTEGER MaximumSize, __in ULONG Priority)
Definition at line 329 of file modwrite.c.
References ACL_REVISION, _MMPAGE_FILE_EXPANSION::ActualExpansion, ASSERT, _MMPAGING_FILE::Bitmap, _MMPAGING_FILE::BootPartition, _UNICODE_STRING::Buffer, _FILE_FS_DEVICE_INFORMATION::Characteristics, CreateFileTypeNone, DACL_SECURITY_INFORMATION, DBG_UNREFERENCED_PARAMETER, DbgPrintEx(), _FILE_OBJECT::DeviceObject, DO_SYSTEM_BOOT_PARTITION, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _FILE_END_OF_FILE_INFORMATION::EndOfFile, _MMPAGING_FILE::Entry, _MMPAGE_FILE_EXPANSION::Event, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _MMPAGING_FILE::File, FILE_ALL_ACCESS, FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_SYSTEM, FILE_DELETE_ON_CLOSE, FILE_DEVICE_DFS_FILE_SYSTEM, FILE_DEVICE_DFS_VOLUME, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_FLOPPY_DISKETTE, FILE_NO_COMPRESSION, FILE_NO_INTERMEDIATE_BUFFERING, FILE_OPEN, FILE_READ_DATA, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SUPERSEDE, FILE_WRITE_DATA, FileEndOfFileInformation, FileFsDeviceInformation, _MMPAGING_FILE::FileHandle, _MMPAGING_FILE::FreeSpace, InitializeObjectAttributes, _MMPAGE_FILE_EXPANSION::InProgress, IO_NO_PARAMETER_CHECKING, IO_OPEN_PAGING_FILE, IoCreateFile(), IoGetRelatedDeviceObject(), IoInitializeCrashDump(), IoQueryVolumeInformation(), KdPrint, KeAcquireGuardedMutex(), KeGetPreviousMode, KeInitializeEvent(), KeReleaseGuardedMutex(), KernelMode, _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, MAX_PAGE_FILES, MAXIMUM_FILENAME_LENGTH, _UNICODE_STRING::MaximumLength, _MMPAGING_FILE::MaximumSize, MI_MAXIMUM_PAGEFILE_SIZE, MiChargeCommitment(), MiCheckPageFileMapping(), MiCreateBitMap, MiExtendPagingFileMaximum(), MiInsertPageFileInList(), MiIssuePageExtendRequest(), MINIMUM_PAGE_FILE_SIZE, _MMPAGING_FILE::MinimumSize, MiReleaseModifiedWriter(), MiRemoveBitMap, MiReturnCommitment, MiZeroPageFileFirstPage(), MM_PAGING_FILE_MDLS, MmModifiedWriteClusterSize, MmNumberOfPagingFiles, MmPageFileCreationLock, MmPagingFile, MmPagingFileHeader, MmSystemPageFileLocated, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTotalCommittedPages, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGE_SHIFT, PAGED_CODE, PagedPool, _MMPAGING_FILE::PageFileName, _MMPAGE_FILE_EXPANSION::PageFileNumber, _MMPAGING_FILE::PageFileNumber, _MMMOD_WRITER_MDL_ENTRY::PagingFile, _MMMOD_WRITER_MDL_ENTRY::PagingListHead, PpPagePathAssign(), PROBE_ALIGNMENT, ProbeForRead, ProbeForReadSmallStructure, _LARGE_INTEGER::QuadPart, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, ROUND64_TO_PAGES, RtlAddAccessAllowedAce(), RtlClearBits(), RtlCopyMemory, RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlLengthSid(), RtlSetAllBits(), RtlSetDaclSecurityDescriptor(), RtlZeroMemory, SeAliasAdminsSid, SeCreatePagefilePrivilege, _FILE_OBJECT::SectionObjectPointer, SECURITY_DESCRIPTOR_REVISION, _MMPAGE_FILE_EXPANSION::Segment, SeLocalSystemSid, SeSinglePrivilegeCheck(), _MMPAGING_FILE::Size, Status, _IO_STATUS_BLOCK::Status, STATUS_DISK_FULL, STATUS_FLOPPY_VOLUME, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_NOT_FOUND, STATUS_OBJECT_NAME_INVALID, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_TOO_MANY_PAGING_FILES, STATUS_UNRECOGNIZED_VOLUME, SYNCHRONIZE, TRUE, WRITE_DAC, ZwClose(), ZwSetInformationFile(), and ZwSetSecurityObject().
Variable Documentation
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.
LONG MiClusterWritesDisabled
Definition at line 52 of file modwrite.c.
Referenced by MiGatherMappedPages(), MiGatherPagefilePages(), and MiWriteComplete().
LOGICAL MiDrainingMappedWrites = FALSE
Definition at line 36 of file modwrite.c.
Referenced by MiModifiedPageWriterWorker(), and MiWriteComplete().
LOGICAL MiFirstPageFileCreatedAndReady = FALSE
Definition at line 34 of file modwrite.c.
Referenced by MiModifiedPageWriterWorker(), and MiReleaseModifiedWriter().
NTSTATUS MiLastMappedWriteError
Definition at line 59 of file modwrite.c.
Referenced by MiNoPagesLastChance(), and MiWriteComplete().
NTSTATUS MiLastModifiedWriteError
Definition at line 58 of file modwrite.c.
Referenced by MiNoPagesLastChance(), and MiWriteComplete().
ULONG MiMappedWriteBurstCount
Definition at line 68 of file modwrite.c.
Referenced by MiMappedPageWriter().
ULONG MiModifiedWriteBurstCount
Definition at line 69 of file modwrite.c.
Referenced by MiGatherPagefilePages().
MMPAGE_FILE_EXPANSION MiPageFileContract
Definition at line 1777 of file modwrite.c.
Referenced by MiContractPagingFiles().
LONG MiPageFileTraceIndex
Definition at line 178 of file modwrite.c.
Referenced by MiSnapPagefileWrite().
MI_PAGEFILE_TRACES MiPageFileTraces[MI_TRACK_PAGEFILE_WRITES]
Definition at line 180 of file modwrite.c.
KEVENT MmMappedFileIoComplete
Definition at line 117 of file modwrite.c.
Referenced by MiCleanSection(), MmInitSystem(), and MmPurgeSection().
KEVENT MmMappedPageWriterEvent
Definition at line 115 of file modwrite.c.
LIST_ENTRY MmMappedPageWriterList
Definition at line 113 of file modwrite.c.
ULONG MmNumberOfMappedMdls
Definition at line 38 of file modwrite.c.
Referenced by MiModifiedPageWriter(), and MiReleaseAllMemory().
SIZE_T MmSystemCommitReserve
Definition at line 37 of file mmquota.c.
Referenced by MiChargeCommitment(), MiExtendPagingFiles(), and MiInitializeCommitment().
BOOLEAN MmSystemPageFileLocated
Definition at line 121 of file modwrite.c.
Referenced by NtCreatePagingFile().
ULONG MmSystemShutdown
Definition at line 119 of file modwrite.c.
Referenced by MiModifiedPageWriter(), MiModifiedPageWriterWorker(), MiNoPagesLastChance(), MiShutdownSystem(), and MmShutdownSystem().
LONG MmWriteAllModifiedPages
Definition at line 33 of file modwrite.c.
Referenced by MiFlushAllPages(), and MiModifiedPageWriterWorker().