Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/po.h File Reference
po.h File Reference
Data Structures
struct _PO_DEVICE_NOTIFY
struct _PO_DEVICE_NOTIFY_ORDER
struct _PO_HIBER_PERF
struct _PO_MEMORY_RANGE_ARRAY
struct _PO_MEMORY_RANGE_ARRAY_LINK
struct _PO_MEMORY_RANGE_ARRAY_RANGE
struct _PO_NOTIFY_ORDER_LEVEL
struct PO_IMAGE_LINK
struct PO_MEMORY_IMAGE
struct PO_SET_STATE_FAILURE
Macros
#define PO_CB_AC_STATUS 1
#define PO_CB_BUTTON_COLLISION 2
#define PO_CB_LID_SWITCH_STATE 4
#define PO_CB_PROCESSOR_POWER_POLICY 5
#define PO_CB_SYSTEM_POWER_POLICY 0
#define PO_CB_SYSTEM_STATE_LOCK 3
#define PO_CLEAN_SHUTDOWN_GENERAL (0x1)
#define PO_CLEAN_SHUTDOWN_OB (0x10)
#define PO_CLEAN_SHUTDOWN_PAGING (0x2)
#define PO_CLEAN_SHUTDOWN_PNP (0x20)
#define PO_CLEAN_SHUTDOWN_REGISTRY (0x8)
#define PO_CLEAN_SHUTDOWN_WORKERS (0x4)
#define PO_COMPRESS_CHUNK_SIZE 4096
#define PO_ENTRIES_PER_PAGE (PO_MAX_RANGE_ARRAY-1)
#define PO_FIRST_RANGE_TABLE_PAGE 3
#define PO_FREE_MAP_PAGE 1
#define PO_HIBER_APM_RECONNECT 0x1
#define PO_HIBER_NO_EXECUTE 0x2
#define PO_IMAGE_HEADER_PAGE 0
#define PO_IMAGE_SIGNATURE 'rbih'
#define PO_IMAGE_SIGNATURE_BREAK 'pkrb'
#define PO_IMAGE_SIGNATURE_LINK 'knil'
#define PO_IMAGE_SIGNATURE_WAKE 'ekaw'
#define PO_MAX_RANGE_ARRAY (PAGE_SIZE / sizeof(PO_MEMORY_RANGE_ARRAY))
#define PO_MEM_CL_OR_NCHK 0x00000004
#define PO_MEM_CLONE 0x00000002
#define PO_MEM_DISCARD 0x00008000
#define PO_MEM_PAGE_ADDRESS 0x00004000
#define PO_MEM_PRESERVE 0x00000001
#define PO_NOTIFY_D0 0x00000001
#define PO_NOTIFY_INVALID 0x80000000
#define PO_NOTIFY_TRANSITIONING_FROM_D0 0x00000002
#define PO_ORDER_GDI_NOTIFICATION (PO_ORDER_PAGABLE)
#define PO_ORDER_MAXIMUM 0x0007
#define PO_ORDER_NOT_VIDEO 0x0001
#define PO_ORDER_PAGABLE 0x0004
#define PO_ORDER_ROOT_ENUM 0x0002
#define PO_PROCESSOR_CONTEXT_PAGE 2
#define PO_SHUTDOWN_QUEUE (CriticalWorkQueue)
#define PoPowerTrace(TracePoint, DevObj, Arg1, Arg2)
#define PoRundownProcess(Process) PopCleanupPowerState(&Process->Pcb.PowerState)
#define PoRundownThread(Thread) PopCleanupPowerState(&Thread->Tcb.PowerState)
#define PoSetDeviceBusy(IdlePointer) *IdlePointer = 0
#define PoWakeTimerSupported() (PopCapabilities.RtcWake >= PowerSystemSleeping1)
#define POWERTRACE_CALL 0x1
#define POWERTRACE_COMPLETE 0x10
#define POWERTRACE_PRESENT 0x2
#define POWERTRACE_SETSTATE 0x8
#define POWERTRACE_STARTNEXT 0x4
Typedefs
typedef struct _PO_DEVICE_NOTIFY PO_DEVICE_NOTIFY
typedef struct _PO_DEVICE_NOTIFY_ORDER PO_DEVICE_NOTIFY_ORDER
typedef struct _PO_HIBER_PERF PO_HIBER_PERF
typedef struct _PO_MEMORY_RANGE_ARRAY PO_MEMORY_RANGE_ARRAY
typedef struct _PO_MEMORY_RANGE_ARRAY_LINK PO_MEMORY_RANGE_ARRAY_LINK
typedef struct _PO_MEMORY_RANGE_ARRAY_RANGE PO_MEMORY_RANGE_ARRAY_RANGE
typedef struct _PO_NOTIFY_ORDER_LEVEL PO_NOTIFY_ORDER_LEVEL
typedef struct _PO_DEVICE_NOTIFY * PPO_DEVICE_NOTIFY
typedef struct _PO_DEVICE_NOTIFY_ORDER * PPO_DEVICE_NOTIFY_ORDER
typedef struct _PO_HIBER_PERF * PPO_HIBER_PERF
typedef struct PO_IMAGE_LINK * PPO_IMAGE_LINK
typedef struct PO_MEMORY_IMAGE * PPO_MEMORY_IMAGE
typedef struct _PO_MEMORY_RANGE_ARRAY * PPO_MEMORY_RANGE_ARRAY
typedef VOID(* PPO_NOTIFY) (IN PDEVICE_OBJECT DeviceObject, IN PVOID Context, IN ULONG Type, IN ULONG Reserved)
typedef struct _PO_NOTIFY_ORDER_LEVEL * PPO_NOTIFY_ORDER_LEVEL
typedef struct PO_SET_STATE_FAILURE * PPO_SET_STATE_FAILURE
typedef VOID(* PREQUEST_POWER_COMPLETE) (__in PDEVICE_OBJECT DeviceObject, __in UCHAR MinorFunction, __in POWER_STATE PowerState, __in_opt PVOID Context, __in PIO_STATUS_BLOCK IoStatus)
Functions
NTKERNELAPI NTSTATUS PoCallDriver (__in PDEVICE_OBJECT DeviceObject, __inout PIRP Irp)
NTKERNELAPI NTSTATUS PoCancelDeviceNotify (IN PVOID NotificationHandle)
ULONG FORCEINLINE PoCleanShutdownEnabled (VOID)
VOID PoGetDevicePowerState (IN PDEVICE_OBJECT PhysicalDeviceObject, OUT DEVICE_POWER_STATE *DevicePowerState)
NTSTATUS PoGetLightestSystemStateForEject (IN BOOLEAN DockBeingEjected, IN BOOLEAN HotEjectSupported, IN BOOLEAN WarmEjectSupported, OUT PSYSTEM_POWER_STATE LightestSleepState)
VOID PoInitDriverServices (IN ULONG Phase)
VOID PoInitHiberServices (IN BOOLEAN Setup)
VOID PoInitializeDeviceObject (IN PDEVOBJ_EXTENSION DeviceObjectExtension)
VOID FASTCALL PoInitializePrcb (PKPRCB Prcb)
BOOLEAN PoInitSystem (IN ULONG Phase)
VOID PoInvalidateDevicePowerRelations (PDEVICE_OBJECT DeviceObject)
VOID PoNotifySystemTimeSet (VOID)
NTKERNELAPI VOID PopCleanupPowerState (IN OUT PUCHAR PowerState)
NTKERNELAPI NTSTATUS PoQueueShutdownWorkItem (IN PWORK_QUEUE_ITEM WorkItem)
NTKERNELAPI PULONG PoRegisterDeviceForIdleDetection (__in PDEVICE_OBJECT DeviceObject, __in ULONG ConservationIdleTime, __in ULONG PerformanceIdleTime, __in DEVICE_POWER_STATE State)
NTKERNELAPI NTSTATUS PoRegisterDeviceNotify (IN PDEVICE_OBJECT DeviceObject, IN PPO_NOTIFY NotificationFunction, IN PVOID NotificationContext, IN ULONG NotificationType, OUT PDEVICE_POWER_STATE DeviceState, OUT PVOID *NotificationHandle)
NTKERNELAPI PVOID PoRegisterSystemState (__inout_opt PVOID StateHandle, __in EXECUTION_STATE Flags)
NTKERNELAPI NTSTATUS PoRequestPowerIrp (__in PDEVICE_OBJECT DeviceObject, __in UCHAR MinorFunction, __in POWER_STATE PowerState, __in_opt PREQUEST_POWER_COMPLETE CompletionFunction, __in_opt PVOID Context, __out_opt PIRP *Irp)
NTKERNELAPI NTSTATUS PoRequestShutdownEvent (OUT PVOID *Event)
NTKERNELAPI NTSTATUS PoRequestShutdownWait (IN PETHREAD Thread)
VOID PoRunDownDeviceObject (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI VOID PoSetHiberRange (IN PVOID MemoryMap, IN ULONG Flags, IN PVOID Address, IN ULONG_PTR Length, IN ULONG Tag)
NTKERNELAPI POWER_STATE PoSetPowerState (__in PDEVICE_OBJECT DeviceObject, __in POWER_STATE_TYPE Type, __in POWER_STATE State)
NTKERNELAPI VOID PoSetSystemState (__in EXECUTION_STATE Flags)
VOID PoSetWarmEjectDevice (IN PDEVICE_OBJECT DeviceObject)
VOID PoShutdownBugCheck (IN BOOLEAN AllowCrashDump, IN ULONG BugCheckCode, IN ULONG_PTR BugCheckParameter1, IN ULONG_PTR BugCheckParameter2, IN ULONG_PTR BugCheckParameter3, IN ULONG_PTR BugCheckParameter4)
ULONG PoSimpleCheck (IN ULONG PatialSum, IN PVOID StartVa, IN ULONG_PTR Length)
NTKERNELAPI VOID PoStartNextPowerIrp (__in PIRP Irp)
BOOLEAN PoSystemIdleWorker (IN BOOLEAN IdleWorker)
NTKERNELAPI VOID PoUnregisterSystemState (__in PVOID StateHandle)
VOID PoVolumeDevice (IN PDEVICE_OBJECT DeviceObject)
Variables
BOOLEAN PoEnabled
BOOLEAN PoHiberInProgress
BOOLEAN PoPageLockData
SYSTEM_POWER_CAPABILITIES PopCapabilities
ULONG PoPowerSequence
ULONG PopShutdownCleanly
KTIMER PoSystemIdleTimer
Macro Definition Documentation
#define PO_CB_AC_STATUS 1
Definition at line 280 of file po.h.
#define PO_CB_BUTTON_COLLISION 2
Definition at line 281 of file po.h.
#define PO_CB_LID_SWITCH_STATE 4
Definition at line 283 of file po.h.
#define PO_CB_PROCESSOR_POWER_POLICY 5
Definition at line 284 of file po.h.
#define PO_CB_SYSTEM_POWER_POLICY 0
Definition at line 279 of file po.h.
#define PO_CB_SYSTEM_STATE_LOCK 3
Definition at line 282 of file po.h.
#define PO_CLEAN_SHUTDOWN_GENERAL (0x1)
Definition at line 541 of file po.h.
#define PO_CLEAN_SHUTDOWN_OB (0x10)
Definition at line 558 of file po.h.
#define PO_CLEAN_SHUTDOWN_PAGING (0x2)
Definition at line 545 of file po.h.
Referenced by MmShutdownSystem().
#define PO_CLEAN_SHUTDOWN_PNP (0x20)
Definition at line 562 of file po.h.
#define PO_CLEAN_SHUTDOWN_REGISTRY (0x8)
Definition at line 554 of file po.h.
Referenced by CmShutdownSystem(), and NtCreateKey().
#define PO_CLEAN_SHUTDOWN_WORKERS (0x4)
Definition at line 550 of file po.h.
Referenced by ExpShutdownWorkerThreads().
#define PO_COMPRESS_CHUNK_SIZE 4096
Definition at line 409 of file po.h.
#define PO_ENTRIES_PER_PAGE (PO_MAX_RANGE_ARRAY-1)
Definition at line 397 of file po.h.
#define PO_FIRST_RANGE_TABLE_PAGE 3
Definition at line 407 of file po.h.
#define PO_FREE_MAP_PAGE 1
Definition at line 405 of file po.h.
#define PO_HIBER_APM_RECONNECT 0x1
Definition at line 434 of file po.h.
#define PO_HIBER_NO_EXECUTE 0x2
Definition at line 435 of file po.h.
#define PO_IMAGE_HEADER_PAGE 0
Definition at line 404 of file po.h.
#define PO_IMAGE_SIGNATURE 'rbih'
Definition at line 400 of file po.h.
#define PO_IMAGE_SIGNATURE_BREAK 'pkrb'
Definition at line 402 of file po.h.
#define PO_IMAGE_SIGNATURE_LINK 'knil'
Definition at line 403 of file po.h.
#define PO_IMAGE_SIGNATURE_WAKE 'ekaw'
Definition at line 401 of file po.h.
#define PO_MAX_RANGE_ARRAY (PAGE_SIZE / sizeof(PO_MEMORY_RANGE_ARRAY))
Definition at line 396 of file po.h.
#define PO_MEM_CL_OR_NCHK 0x00000004
Definition at line 140 of file po.h.
#define PO_MEM_CLONE 0x00000002
Definition at line 139 of file po.h.
Referenced by MmHibernateInformation().
#define PO_MEM_DISCARD 0x00008000
Definition at line 141 of file po.h.
#define PO_MEM_PAGE_ADDRESS 0x00004000
Definition at line 142 of file po.h.
#define PO_MEM_PRESERVE 0x00000001
Definition at line 138 of file po.h.
#define PO_NOTIFY_D0 0x00000001
Definition at line 311 of file po.h.
#define PO_NOTIFY_INVALID 0x80000000
Definition at line 313 of file po.h.
#define PO_NOTIFY_TRANSITIONING_FROM_D0 0x00000002
Definition at line 312 of file po.h.
#define PO_ORDER_GDI_NOTIFICATION (PO_ORDER_PAGABLE)
Definition at line 520 of file po.h.
#define PO_ORDER_MAXIMUM 0x0007
Definition at line 517 of file po.h.
#define PO_ORDER_NOT_VIDEO 0x0001
Definition at line 514 of file po.h.
#define PO_ORDER_PAGABLE 0x0004
Definition at line 516 of file po.h.
#define PO_ORDER_ROOT_ENUM 0x0002
Definition at line 515 of file po.h.
#define PO_PROCESSOR_CONTEXT_PAGE 2
Definition at line 406 of file po.h.
#define PO_SHUTDOWN_QUEUE (CriticalWorkQueue)
Definition at line 575 of file po.h.
Referenced by ExpCheckQueueShutdown(), ExpShutdownWorkerThreads(), and ExpWorkerThread().
#define PoPowerTrace (TracePoint, DevObj, Arg1, Arg2)
Definition at line 46 of file po.h.
#define PoRundownProcess (Process) PopCleanupPowerState(&Process->Pcb.PowerState)
Definition at line 102 of file po.h.
Referenced by PspExitProcess().
#define PoRundownThread (Thread) PopCleanupPowerState(&Thread->Tcb.PowerState)
Definition at line 99 of file po.h.
Referenced by PspExitThread().
#define PoSetDeviceBusy (IdlePointer) *IdlePointer = 0
Definition at line 272 of file po.h.
#define PoWakeTimerSupported () (PopCapabilities.RtcWake >= PowerSystemSleeping1)
Definition at line 146 of file po.h.
Referenced by NtSetTimer().
#define POWERTRACE_CALL 0x1
Definition at line 49 of file po.h.
#define POWERTRACE_COMPLETE 0x10
Definition at line 53 of file po.h.
#define POWERTRACE_PRESENT 0x2
Definition at line 50 of file po.h.
#define POWERTRACE_SETSTATE 0x8
Definition at line 52 of file po.h.
#define POWERTRACE_STARTNEXT 0x4
Definition at line 51 of file po.h.
Typedef Documentation
typedef struct _PO_DEVICE_NOTIFY PO_DEVICE_NOTIFY
typedef struct _PO_DEVICE_NOTIFY_ORDER PO_DEVICE_NOTIFY_ORDER
typedef struct _PO_HIBER_PERF PO_HIBER_PERF
typedef struct _PO_MEMORY_RANGE_ARRAY PO_MEMORY_RANGE_ARRAY
typedef struct _PO_MEMORY_RANGE_ARRAY_LINK PO_MEMORY_RANGE_ARRAY_LINK
typedef struct _PO_MEMORY_RANGE_ARRAY_RANGE PO_MEMORY_RANGE_ARRAY_RANGE
typedef struct _PO_NOTIFY_ORDER_LEVEL PO_NOTIFY_ORDER_LEVEL
typedef struct _PO_DEVICE_NOTIFY * PPO_DEVICE_NOTIFY
typedef struct _PO_DEVICE_NOTIFY_ORDER * PPO_DEVICE_NOTIFY_ORDER
typedef struct _PO_HIBER_PERF * PPO_HIBER_PERF
typedef struct PO_IMAGE_LINK * PPO_IMAGE_LINK
typedef struct PO_MEMORY_IMAGE * PPO_MEMORY_IMAGE
typedef struct _PO_MEMORY_RANGE_ARRAY * PPO_MEMORY_RANGE_ARRAY
typedef VOID(* PPO_NOTIFY) (IN PDEVICE_OBJECT DeviceObject, IN PVOID Context, IN ULONG Type, IN ULONG Reserved)
Definition at line 304 of file po.h.
typedef struct _PO_NOTIFY_ORDER_LEVEL * PPO_NOTIFY_ORDER_LEVEL
typedef struct PO_SET_STATE_FAILURE * PPO_SET_STATE_FAILURE
typedef VOID(* PREQUEST_POWER_COMPLETE) (__in PDEVICE_OBJECT DeviceObject, __in UCHAR MinorFunction, __in POWER_STATE PowerState, __in_opt PVOID Context, __in PIO_STATUS_BLOCK IoStatus)
Definition at line 200 of file po.h.
Function Documentation
NTKERNELAPI NTSTATUS PoCallDriver (__in PDEVICE_OBJECT DeviceObject, __inout PIRP Irp)
NTKERNELAPI NTSTATUS PoCancelDeviceNotify (IN PVOID NotificationHandle)
ULONG FORCEINLINE PoCleanShutdownEnabled (VOID)
Definition at line 567 of file po.h.
References PopShutdownCleanly.
Referenced by CmShutdownSystem(), ExpShutdownWorkerThreads(), MiShutdownSystem(), MmShutdownSystem(), NtCreateKey(), and PsShutdownSystem().
VOID PoGetDevicePowerState (IN PDEVICE_OBJECT PhysicalDeviceObject, OUT DEVICE_POWER_STATE * DevicePowerState)
NTSTATUS PoGetLightestSystemStateForEject (IN BOOLEAN DockBeingEjected, IN BOOLEAN HotEjectSupported, IN BOOLEAN WarmEjectSupported, OUT PSYSTEM_POWER_STATE LightestSleepState)
VOID PoInitDriverServices (IN ULONG Phase)
Referenced by IoInitSystem().
VOID PoInitHiberServices (IN BOOLEAN Setup)
Referenced by NtInitializeRegistry().
VOID PoInitializeDeviceObject (IN PDEVOBJ_EXTENSION DeviceObjectExtension)
Referenced by IoCreateDevice().
VOID FASTCALL PoInitializePrcb (PKPRCB Prcb)
Referenced by KiInitializeKernel().
BOOLEAN PoInitSystem (IN ULONG Phase)
Referenced by Phase1InitializationDiscard().
VOID PoInvalidateDevicePowerRelations (PDEVICE_OBJECT DeviceObject)
VOID PoNotifySystemTimeSet (VOID)
Referenced by Phase1InitializationDiscard().
NTKERNELAPI VOID PopCleanupPowerState (IN OUT PUCHAR PowerState)
NTKERNELAPI NTSTATUS PoQueueShutdownWorkItem (IN PWORK_QUEUE_ITEM WorkItem)
NTKERNELAPI PULONG PoRegisterDeviceForIdleDetection (__in PDEVICE_OBJECT DeviceObject, __in ULONG ConservationIdleTime, __in ULONG PerformanceIdleTime, __in DEVICE_POWER_STATE State)
NTKERNELAPI NTSTATUS PoRegisterDeviceNotify (IN PDEVICE_OBJECT DeviceObject, IN PPO_NOTIFY NotificationFunction, IN PVOID NotificationContext, IN ULONG NotificationType, OUT PDEVICE_POWER_STATE DeviceState, OUT PVOID * NotificationHandle)
NTKERNELAPI PVOID PoRegisterSystemState (__inout_opt PVOID StateHandle, __in EXECUTION_STATE Flags)
NTKERNELAPI NTSTATUS PoRequestPowerIrp (__in PDEVICE_OBJECT DeviceObject, __in UCHAR MinorFunction, __in POWER_STATE PowerState, __in_opt PREQUEST_POWER_COMPLETE CompletionFunction, __in_opt PVOID Context, __out_opt PIRP * Irp)
NTKERNELAPI NTSTATUS PoRequestShutdownEvent (OUT PVOID * Event)
Referenced by SepRmCommandServerThread().
NTKERNELAPI NTSTATUS PoRequestShutdownWait (IN PETHREAD Thread)
VOID PoRunDownDeviceObject (IN PDEVICE_OBJECT DeviceObject)
Referenced by IoDeleteDevice().
NTKERNELAPI VOID PoSetHiberRange (IN PVOID MemoryMap, IN ULONG Flags, IN PVOID Address, IN ULONG_PTR Length, IN ULONG Tag)
Referenced by MmHibernateInformation().
NTKERNELAPI POWER_STATE PoSetPowerState (__in PDEVICE_OBJECT DeviceObject, __in POWER_STATE_TYPE Type, __in POWER_STATE State)
NTKERNELAPI VOID PoSetSystemState (__in EXECUTION_STATE Flags)
VOID PoSetWarmEjectDevice (IN PDEVICE_OBJECT DeviceObject)
VOID PoShutdownBugCheck (IN BOOLEAN AllowCrashDump, IN ULONG BugCheckCode, IN ULONG_PTR BugCheckParameter1, IN ULONG_PTR BugCheckParameter2, IN ULONG_PTR BugCheckParameter3, IN ULONG_PTR BugCheckParameter4)
Referenced by ExpSystemErrorHandler().
ULONG PoSimpleCheck (IN ULONG PatialSum, IN PVOID StartVa, IN ULONG_PTR Length)
NTKERNELAPI VOID PoStartNextPowerIrp (__in PIRP Irp)
Referenced by IopInvalidDeviceRequest().
BOOLEAN PoSystemIdleWorker (IN BOOLEAN IdleWorker)
Referenced by MmZeroPageThread().
NTKERNELAPI VOID PoUnregisterSystemState (__in PVOID StateHandle)
VOID PoVolumeDevice (IN PDEVICE_OBJECT DeviceObject)
Referenced by IoCreateDevice(), and IoVerifyVolume().
Variable Documentation
BOOLEAN PoEnabled
BOOLEAN PoHiberInProgress
BOOLEAN PoPageLockData
SYSTEM_POWER_CAPABILITIES PopCapabilities
ULONG PoPowerSequence
ULONG PopShutdownCleanly
Referenced by MiShutdownSystem(), and PoCleanShutdownEnabled().
KTIMER PoSystemIdleTimer
Referenced by MmZeroPageThread().