Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psp.h File Reference
psp.h File Reference
#include "ntos.h"
#include "ntrtl.h"
#include "nturtl.h"
#include "zwapi.h"
#include "ki.h"
#include <vdmntos.h>
#include "wdbgexts.h"
#include "ntdbg.h"
#include <string.h>
Data Structures
struct _GETSETCONTEXT
struct _JOB_WORKING_SET_CHANGE_HEAD
struct _JOB_WORKING_SET_CHANGE_RECORD
struct _PRIV_CHECK_CTX
struct _SYSTEM_DLL
Macros
#define MAX_WS_CATCH_INDEX (((WS_CATCH_SIZE-WS_OVERHEAD)/sizeof(PROCESS_WS_WATCH_INFORMATION)) - 2)
#define NOEXTAPI
#define PSP_DEFAULT_SCHEDULING_CLASSES 5
#define PSP_MAX_CREATE_PROCESS_NOTIFY 8
#define PSP_MAX_CREATE_THREAD_NOTIFY 8
#define PSP_MAX_LOAD_IMAGE_NOTIFY 8
#define PSP_NUMBER_OF_SCHEDULING_CLASSES 10
#define PSP_PROCESS_NONPAGED_CHARGE (sizeof(EPROCESS))
#define PSP_PROCESS_PAGED_CHARGE (PAGE_SIZE)
#define PSP_THREAD_NONPAGED_CHARGE (sizeof(ETHREAD))
#define PSP_THREAD_PAGED_CHARGE (0)
#define PSPALIGN_DOWN(address, amt) ((ULONG)(address) & ~((amt) - 1))
#define PSPALIGN_UP(address, amt) (PSPALIGN_DOWN((address + (amt) - 1), (amt)))
#define PspGetBaseExceptionFrame(Thread) (NULL)
#define PspGetBaseTrapFrame(Thread)
#define WS_CATCH_SIZE 8192
#define WS_OVERHEAD 16
Typedefs
typedef struct _GETSETCONTEXT GETSETCONTEXT
typedef struct _JOB_WORKING_SET_CHANGE_HEAD JOB_WORKING_SET_CHANGE_HEAD
typedef struct _JOB_WORKING_SET_CHANGE_RECORD JOB_WORKING_SET_CHANGE_RECORD
typedef struct _GETSETCONTEXT * PGETSETCONTEXT
typedef struct _JOB_WORKING_SET_CHANGE_HEAD * PJOB_WORKING_SET_CHANGE_HEAD
typedef struct _JOB_WORKING_SET_CHANGE_RECORD * PJOB_WORKING_SET_CHANGE_RECORD
typedef struct _PRIV_CHECK_CTX * PPRIV_CHECK_CTX
typedef struct _PRIV_CHECK_CTX PRIV_CHECK_CTX
typedef struct _SYSTEM_DLL PSYSTEM_DLL
typedef struct _SYSTEM_DLL SYSTEM_DLL
Functions
NTSTATUS PspAddProcessToJob (PEJOB Job, PEPROCESS Process)
VOID PspApplyJobLimitsToProcess (PEJOB Job, PEPROCESS Process)
VOID PspApplyJobLimitsToProcessSet (PEJOB Job)
NTSTATUS PspAssignPrimaryToken (IN PEPROCESS Process, IN HANDLE Token OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL)
NTSTATUS PspCaptureTokenFilter (KPROCESSOR_MODE PreviousMode, PJOBOBJECT_SECURITY_LIMIT_INFORMATION SecurityLimitInfo, PPS_JOB_TOKEN_FILTER *TokenFilter)
KPRIORITY PspComputeQuantumAndPriority (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode, __out PSCHAR QuantumReset)
NTSTATUS PspCreateProcess (OUT PHANDLE ProcessHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ParentProcess OPTIONAL, IN ULONG Flags, IN HANDLE SectionHandle OPTIONAL, IN HANDLE DebugPort OPTIONAL, IN HANDLE ExceptionPort OPTIONAL, IN ULONG JobMemberLevel)
NTSTATUS PspCreateThread (OUT PHANDLE ThreadHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ProcessHandle, IN PEPROCESS ProcessPointer, OUT PCLIENT_ID ClientId OPTIONAL, IN PCONTEXT ThreadContext OPTIONAL, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN CreateSuspended, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext)
VOID PspDeleteLdt (IN PEPROCESS Process)
VOID PspDeleteProcessSecurity (IN PEPROCESS Process)
VOID PspDeleteThreadSecurity (IN PETHREAD Thread)
VOID PspDeleteVdmObjects (IN PEPROCESS Process)
VOID PspDereferenceQuota (IN PEPROCESS Process)
VOID PspExitApcRundown (IN PKAPC Apc)
VOID PspExitNormalApc (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID PspExitProcess (IN BOOLEAN TrimAddressSpace, IN PEPROCESS Process)
VOID PspExitProcessFromJob (PEJOB Job, PEPROCESS Process)
VOID PspExitSpecialApc (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE *NormalRoutine, IN OUT PVOID *NormalContext, IN OUT PVOID *SystemArgument1, IN OUT PVOID *SystemArgument2)
DECLSPEC_NORETURN VOID PspExitThread (IN NTSTATUS ExitStatus)
VOID PspFoldProcessAccountingIntoJob (PEJOB Job, PEPROCESS Process)
VOID PspGetContext (IN PKTRAP_FRAME TrapFrame, IN PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN OUT PCONTEXT Context)
NTSTATUS PspGetJobFromSet (IN PEJOB ParentJob, IN ULONG JobMemberLevel, OUT PEJOB *pJob)
PEPROCESS PspGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
VOID PspGetSetContextSpecialApc (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE *NormalRoutine, IN OUT PVOID *NormalContext, IN OUT PVOID *SystemArgument1, IN OUT PVOID *SystemArgument2)
VOID PspImageNotifyTest (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
VOID PspInheritQuota (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess)
VOID FORCEINLINE PspInitializeJobLimitsLock (IN PEJOB Job)
VOID FORCEINLINE PspInitializeJobListLock (VOID)
VOID PspInitializeJobStructures (VOID)
VOID PspInitializeJobStructuresPhase1 (VOID)
VOID FORCEINLINE PspInitializeJobTimeLimitsLock (VOID)
VOID FORCEINLINE PspInitializeProcessListLock (VOID)
VOID FORCEINLINE PspInitializeProcessLock (IN PEPROCESS Process)
NTSTATUS PspInitializeProcessSecurity (IN PEPROCESS Parent OPTIONAL, IN PEPROCESS Child)
NTSTATUS PspInitializeSystemDll (VOID)
VOID FORCEINLINE PspInitializeThreadLock (IN PETHREAD Thread)
VOID PspInitializeThreadSecurity (IN PEPROCESS Process, IN PETHREAD Thread)
VOID FORCEINLINE PspInitializeWorkingSetChangeLock (VOID)
BOOLEAN PspInitPhase0 (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN PspInitPhase1 (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID PspInsertQuotaBlock (IN PEPROCESS_QUOTA_BLOCK QuotaBlock)
VOID PspJobClose (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID PspJobDelete (IN PVOID Object)
VOID PspJobTimeLimitsDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID PspJobTimeLimitsWork (IN PVOID Context)
VOID FORCEINLINE PspLockJobLimitsExclusive (IN PEJOB Job, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockJobLimitsExclusiveUnsafe (IN PEJOB Job)
VOID FORCEINLINE PspLockJobLimitsShared (IN PEJOB Job, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockJobLimitsSharedUnsafe (IN PEJOB Job)
VOID FORCEINLINE PspLockJobListExclusive (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockJobListShared (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockJobTimeLimitsExclusive (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockJobTimeLimitsShared (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockProcessExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockProcessList (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockProcessSecurityExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockProcessSecurityShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockProcessShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockThreadSecurityExclusive (IN PETHREAD Thread, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockThreadSecurityShared (IN PETHREAD Thread, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockWorkingSetChangeExclusive (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspLockWorkingSetChangeExclusiveUnsafe (VOID)
NTSTATUS PspLookupKernelUserEntryPoints (VOID)
NTSTATUS PspLookupSystemDllEntryPoint (IN PSZ EntryPointName, OUT PVOID *EntryPointAddress)
USHORT PspNameToOrdinal (IN PSZ EntryPointName, IN ULONG DllBase, IN ULONG NumberOfNames, IN PULONG NameTableBase, IN PUSHORT OrdinalTableBase)
VOID PspNullSpecialApc (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE *NormalRoutine, IN OUT PVOID *NormalContext, IN OUT PVOID *SystemArgument1, IN OUT PVOID *SystemArgument2)
VOID PspProcessDelete (IN PVOID Object)
VOID PspProcessDump (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
NTSTATUS PspQueryDescriptorThread (PETHREAD Thread, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength)
NTSTATUS PspQueryLdtInformation (IN PEPROCESS Process, OUT PVOID LdtInformation, IN ULONG LdtInformationLength, OUT PULONG ReturnLength)
VOID PspQuitNextJobProcess (IN PEPROCESS Process)
VOID PspReaper (IN PVOID StartContext)
VOID PspRemoveProcessFromJob (PEJOB Job, PEPROCESS Process)
VOID PspSetContext (OUT PKTRAP_FRAME TrapFrame, OUT PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN PCONTEXT Context, KPROCESSOR_MODE Mode)
NTSTATUS PspSetLdtInformation (IN PEPROCESS Process, IN PVOID LdtInformation, IN ULONG LdtInformationLength)
NTSTATUS PspSetLdtSize (IN PEPROCESS Process, IN PVOID LdtSize, IN ULONG LdtSizeLength)
NTSTATUS PspSetPrimaryToken (IN HANDLE ProcessHandle, IN PEPROCESS ProcessPointer OPTIONAL, IN HANDLE TokenHandle OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL, IN BOOLEAN PrivilegeChecked)
NTSTATUS PspSetProcessIoHandlers (IN PEPROCESS Process, IN PVOID IoHandlerInformation, IN ULONG IoHandlerLength)
VOID PspShutdownJobLimits (VOID)
LOGICAL PspSinglePrivCheck (IN LUID PrivilegeValue, IN KPROCESSOR_MODE PreviousMode, OUT PPRIV_CHECK_CTX PrivCtx)
VOID PspSinglePrivCheckAudit (IN LOGICAL PrivUsed, IN PPRIV_CHECK_CTX PrivCtx)
VOID PspSystemThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
BOOLEAN PspTerminateAllProcessesInJob (PEJOB Job, NTSTATUS Status, BOOLEAN IncCounter)
NTSTATUS PspTerminateProcess (PEPROCESS Process, NTSTATUS Status)
NTSTATUS PspTerminateThreadByPointer (IN PETHREAD Thread, IN NTSTATUS ExitStatus, IN BOOLEAN DirectTerminate)
VOID PspThreadDelete (IN PVOID Object)
VOID PspThreadDump (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
VOID FORCEINLINE PspUnlockJobLimitsExclusive (IN PEJOB Job, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockJobLimitsExclusiveUnsafe (IN PEJOB Job)
VOID FORCEINLINE PspUnlockJobLimitsShared (IN PEJOB Job, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockJobLimitsSharedUnsafe (IN PEJOB Job)
VOID FORCEINLINE PspUnlockJobListExclusive (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockJobListShared (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockJobTimeLimitsExclusive (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockJobTimeLimitsShared (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockProcessExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockProcessList (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockProcessSecurityExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockProcessSecurityShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockProcessShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockThreadSecurityExclusive (IN PETHREAD Thread, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockThreadSecurityShared (IN PETHREAD Thread, IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockWorkingSetChangeExclusive (IN PETHREAD CurrentThread)
VOID FORCEINLINE PspUnlockWorkingSetChangeExclusiveUnsafe (VOID)
VOID PspUserThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
NTSTATUS PspWaitForUsermodeExit (IN PEPROCESS Process)
NTSTATUS PspWin32SessionCallout (IN PKWIN32_JOB_CALLOUT CalloutRoutine, IN PKWIN32_JOBCALLOUT_PARAMETERS Parameters, IN ULONG SessionId)
NTSTATUS PspWriteTebImpersonationInfo (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Variables
ULONG PsMinimumWorkingSet
KGUARDED_MUTEX PspActiveProcessMutex
PACCESS_TOKEN PspBootAccessToken
PHANDLE_TABLE PspCidTable
EX_CALLBACK PspCreateProcessNotifyRoutine [PSP_MAX_CREATE_PROCESS_NOTIFY]
ULONG PspCreateProcessNotifyRoutineCount
EX_CALLBACK PspCreateThreadNotifyRoutine [PSP_MAX_CREATE_THREAD_NOTIFY]
ULONG PspCreateThreadNotifyRoutineCount
ULONG PspDefaultNonPagedLimit
ULONG PspDefaultPagedLimit
ULONG PspDefaultPagefileLimit
EPROCESS_QUOTA_BLOCK PspDefaultQuotaBlock
BOOLEAN PspDoingGiveBacks
SCHAR PspForegroundQuantum [3]
HANDLE PspInitialSystemProcessHandle
KDPC PspJobLimeLimitsDpc
LIST_ENTRY PspJobList
KGUARDED_MUTEX PspJobListLock
const SCHAR PspJobSchedulingClasses [PSP_NUMBER_OF_SCHEDULING_CLASSES]
KGUARDED_MUTEX PspJobTimeLimitsLock
KTIMER PspJobTimeLimitsTimer
WORK_QUEUE_ITEM PspJobTimeLimitsWorkItem
EX_CALLBACK PspLoadImageNotifyRoutine [PSP_MAX_LOAD_IMAGE_NOTIFY]
ULONG PspLoadImageNotifyRoutineCount
KSPIN_LOCK PspQuotaLock
PETHREAD PspShutdownThread
SYSTEM_DLL PspSystemDll
BOOLEAN PspUseJobSchedulingClasses
PKWIN32_JOB_CALLOUT PspW32JobCallout
PKWIN32_PROCESS_CALLOUT PspW32ProcessCallout
ULONG PspW32ProcessSize
PKWIN32_THREAD_CALLOUT PspW32ThreadCallout
ULONG PspW32ThreadSize
JOB_WORKING_SET_CHANGE_HEAD PspWorkingSetChangeHead
Macro Definition Documentation
#define MAX_WS_CATCH_INDEX (((WS_CATCH_SIZE-WS_OVERHEAD)/sizeof(PROCESS_WS_WATCH_INFORMATION)) - 2)
Definition at line 56 of file psp.h.
Referenced by NtSetInformationProcess(), and PspQueryWorkingSetWatch().
#define NOEXTAPI
Definition at line 41 of file psp.h.
#define PSP_DEFAULT_SCHEDULING_CLASSES 5
Definition at line 1170 of file psp.h.
Referenced by NtCreateJobObject(), and NtSetInformationJobObject().
#define PSP_MAX_CREATE_PROCESS_NOTIFY 8
Definition at line 279 of file psp.h.
Referenced by PspCreateThread(), PspExitProcess(), PspInitPhase0(), and PsSetCreateProcessNotifyRoutine().
#define PSP_MAX_CREATE_THREAD_NOTIFY 8
Definition at line 288 of file psp.h.
Referenced by PspCreateThread(), PspExitThread(), PspInitPhase0(), PsRemoveCreateThreadNotifyRoutine(), and PsSetCreateThreadNotifyRoutine().
#define PSP_MAX_LOAD_IMAGE_NOTIFY 8
Definition at line 298 of file psp.h.
Referenced by PsCallImageNotifyRoutines(), PspInitPhase0(), PsRemoveLoadImageNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
#define PSP_NUMBER_OF_SCHEDULING_CLASSES 10
Definition at line 1169 of file psp.h.
Referenced by NtSetInformationJobObject(), and PspApplyJobLimitsToProcess().
#define PSP_PROCESS_NONPAGED_CHARGE (sizeof(EPROCESS))
Definition at line 69 of file psp.h.
Referenced by PspInitPhase0().
#define PSP_PROCESS_PAGED_CHARGE (PAGE_SIZE)
Definition at line 68 of file psp.h.
Referenced by PspInitPhase0().
#define PSP_THREAD_NONPAGED_CHARGE (sizeof(ETHREAD))
Definition at line 82 of file psp.h.
Referenced by PspInitPhase0().
#define PSP_THREAD_PAGED_CHARGE (0)
Definition at line 81 of file psp.h.
Referenced by PspInitPhase0().
#define PSPALIGN_DOWN (address, amt) ((ULONG)(address) & ~((amt) - 1))
Definition at line 88 of file psp.h.
#define PSPALIGN_UP (address, amt) (PSPALIGN_DOWN((address + (amt) - 1), (amt)))
Definition at line 90 of file psp.h.
#define PspGetBaseExceptionFrame (Thread) (NULL)
Definition at line 124 of file psp.h.
Referenced by PspUserThreadStartup().
#define PspGetBaseTrapFrame (Thread)
Value:
(PKTRAP_FRAME)((ULONG_PTR)Thread->Tcb.InitialStack - \
                                                   PSPALIGN_UP(sizeof(KTRAP_FRAME),KTRAP_FRAME_ALIGN) - \
                                                   sizeof(FX_SAVE_AREA))
Definition at line 120 of file psp.h.
Referenced by PspGetSetContextInternal(), PspGetSetContextSpecialApc(), and PspUserThreadStartup().
#define WS_CATCH_SIZE 8192
Definition at line 54 of file psp.h.
Referenced by NtSetInformationProcess(), and PspProcessDelete().
#define WS_OVERHEAD 16
Definition at line 55 of file psp.h.
Typedef Documentation
typedef struct _GETSETCONTEXT GETSETCONTEXT
typedef struct _JOB_WORKING_SET_CHANGE_HEAD JOB_WORKING_SET_CHANGE_HEAD
typedef struct _JOB_WORKING_SET_CHANGE_RECORD JOB_WORKING_SET_CHANGE_RECORD
typedef struct _GETSETCONTEXT * PGETSETCONTEXT
typedef struct _JOB_WORKING_SET_CHANGE_HEAD * PJOB_WORKING_SET_CHANGE_HEAD
typedef struct _JOB_WORKING_SET_CHANGE_RECORD * PJOB_WORKING_SET_CHANGE_RECORD
typedef struct _PRIV_CHECK_CTX * PPRIV_CHECK_CTX
typedef struct _PRIV_CHECK_CTX PRIV_CHECK_CTX
typedef struct _SYSTEM_DLL PSYSTEM_DLL
typedef struct _SYSTEM_DLL SYSTEM_DLL
Function Documentation
NTSTATUS PspAddProcessToJob (PEJOB Job, PEPROCESS Process)
Definition at line 457 of file psjob.c.
References _EJOB::ActiveProcesses, _EJOB::ActiveProcessLimit, _EJOB::CompletionKey, _EJOB::CompletionPort, _EJOB::Event, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, InsertTailList(), IoSetIoCompletion(), JOB_OBJECT_LIMIT_ACTIVE_PROCESS, JOB_OBJECT_LIMIT_JOB_TIME, JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, JOB_OBJECT_LIMIT_WORKINGSET, JOB_OBJECT_MSG_ACTIVE_PROCESS_LIMIT, JOB_OBJECT_MSG_NEW_PROCESS, _EJOB::JobFlags, _EPROCESS::JobLinks, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), KeReadStateEvent(), KeStackAttachProcess(), KeUnstackDetachProcess(), _EJOB::LimitFlags, _EJOB::MaximumWorkingSetSize, _EJOB::MinimumWorkingSetSize, MmAdjustWorkingSetSize(), MmAssignProcessToJob(), MmEnforceWorkingSetLimit(), NT_SUCCESS, NULL, PAGED_CODE, _EPROCESS::Pcb, _EJOB::ProcessListHead, PS_JOB_FLAGS_CLOSE_DONE, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PS_SET_CLEAR_BITS, PS_TEST_ALL_BITS_SET, PsGetCurrentThread(), PspApplyJobLimitsToProcess(), PspLockWorkingSetChangeExclusiveUnsafe(), PspUnlockWorkingSetChangeExclusiveUnsafe(), Status, STATUS_INVALID_PARAMETER, STATUS_QUOTA_EXCEEDED, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::TotalProcesses, TRUE, and _EPROCESS::UniqueProcessId.
Referenced by NtAssignProcessToJobObject(), and PspCreateProcess().
VOID PspApplyJobLimitsToProcess (PEJOB Job, PEPROCESS Process)
Definition at line 2340 of file psjob.c.
References _EJOB::Affinity, _EPROCESS::CommitChargeLimit, FALSE, _MMSUPPORT::Flags, JOB_OBJECT_LIMIT_AFFINITY, JOB_OBJECT_LIMIT_PRIORITY_CLASS, JOB_OBJECT_LIMIT_PROCESS_MEMORY, JOB_OBJECT_LIMIT_WORKINGSET, KeSetAffinityProcess(), KeSetDisableQuantumProcess(), KeSetQuantumProcess(), _EJOB::LimitFlags, MEMORY_PRIORITY_FOREGROUND, _MMSUPPORT_FLAGS::MemoryPriority, MmEnforceWorkingSetLimit(), PAGED_CODE, _EPROCESS::Pcb, _EPROCESS::PriorityClass, _EJOB::PriorityClass, PROCESS_PRIORITY_CLASS_IDLE, _EJOB::ProcessMemoryLimit, PsGetCurrentThread(), PSP_NUMBER_OF_SCHEDULING_CLASSES, PspJobSchedulingClasses, PspLockJobLimitsShared(), PspLockProcessExclusive(), PsProcessPriorityBackground, PsProcessPriorityForeground, PspUnlockJobLimitsShared(), PspUnlockProcessExclusive(), PspUseJobSchedulingClasses, PsSetProcessPriorityByClass(), _EJOB::SchedulingClass, TRUE, and _EPROCESS::Vm.
Referenced by PspAddProcessToJob(), and PspApplyJobLimitsToProcessSet().
VOID PspApplyJobLimitsToProcessSet (PEJOB Job)
Definition at line 2306 of file psjob.c.
References ExAllocatePoolWithTag, InsertTailList(), JOB_OBJECT_LIMIT_WORKINGSET, _EPROCESS::JobStatus, _EJOB::LimitFlags, _JOB_WORKING_SET_CHANGE_HEAD::Links, _JOB_WORKING_SET_CHANGE_RECORD::Links, NULL, ObReferenceObject, PAGED_CODE, PagedPool, _JOB_WORKING_SET_CHANGE_RECORD::Process, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PspApplyJobLimitsToProcess(), PspGetNextJobProcess(), and PspWorkingSetChangeHead.
Referenced by NtSetInformationJobObject().
NTSTATUS PspAssignPrimaryToken (IN PEPROCESS Process, IN HANDLE Token OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL)
Definition at line 1485 of file security.c.
References KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PspLockProcessSecurityExclusive(), PspUnlockProcessSecurityExclusive(), SeExchangePrimaryToken(), SeTokenObjectType, Status, _ETHREAD::Tcb, and TOKEN_ASSIGN_PRIMARY.
Referenced by PspSetPrimaryToken().
NTSTATUS PspCaptureTokenFilter (KPROCESSOR_MODE PreviousMode, PJOBOBJECT_SECURITY_LIMIT_INFORMATION SecurityLimitInfo, PPS_JOB_TOKEN_FILTER * TokenFilter)
Definition at line 2730 of file psjob.c.
References ARGUMENT_PRESENT, _PS_JOB_TOKEN_FILTER::CapturedGroupCount, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedGroupsLength, _PS_JOB_TOKEN_FILTER::CapturedPrivilegeCount, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedPrivilegesLength, _PS_JOB_TOKEN_FILTER::CapturedSidCount, _PS_JOB_TOKEN_FILTER::CapturedSids, _PS_JOB_TOKEN_FILTER::CapturedSidsLength, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _TOKEN_GROUPS::GroupCount, _TOKEN_GROUPS::Groups, NonPagedPool, NT_SUCCESS, NULL, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::PrivilegesToDelete, ProbeForReadSmallStructure, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::RestrictedSids, RtlZeroMemory, SeCaptureLuidAndAttributesArray(), SeCaptureSidAndAttributesArray(), _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SidsToDisable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationJobObject().
KPRIORITY PspComputeQuantumAndPriority (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode, __out PSCHAR QuantumReset)
Definition at line 4387 of file psquery.c.
References FALSE, MEMORY_PRIORITY_BACKGROUND, MEMORY_PRIORITY_FOREGROUND, MmSetMemoryPriorityProcess(), NULL, PAGED_CODE, PROCESS_PRIORITY_CLASS_IDLE, PspForegroundQuantum, PspJobSchedulingClasses, PspPriorityTable, PsPrioritySeparation, PsProcessPriorityForeground, PsProcessPrioritySpinning, PspUseJobSchedulingClasses, _EJOB::SchedulingClass, and THREAD_QUANTUM.
Referenced by PspCreateProcess(), and PsSetProcessPriorityByClass().
NTSTATUS PspCreateProcess (OUT PHANDLE ProcessHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ParentProcess OPTIONAL, IN ULONG Flags, IN HANDLE SectionHandle OPTIONAL, IN HANDLE DebugPort OPTIONAL, IN HANDLE ExceptionPort OPTIONAL, IN ULONG JobMemberLevel)
Definition at line 967 of file create.c.
References _EPROCESS::ActiveProcessLinks, _KPROCESS::Affinity, ARGUMENT_PRESENT, ASSERT, _KPROCESS::BasePriority, _UNICODE_STRING::Buffer, _SECURITY_SUBJECT_CONTEXT::ClientToken, _EPROCESS::CreateTime, DbgkCopyProcessDebugPort(), DbgkDebugObjectType, DEBUG_PROCESS_ASSIGN, _EPROCESS::DebugPort, _EPROCESS::DefaultHardErrorProcessing, ExAcquireRundownProtection(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExCreateHandle(), ExInitializeRundownProtection(), _EPROCESS::ExitStatus, ExReleaseRundownProtection(), ExSetHandleTableOwner, FALSE, FIELD_OFFSET, _EPROCESS::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _SE_AUDIT_PROCESS_CREATION_INFO::ImageFileName, _INITIAL_PEB::ImageUsesLargePages, _INITIAL_PEB::InheritedAddressSpace, _EPROCESS::InheritedFromUniqueProcessId, InitializeListHead(), InsertTailList(), IsListEmpty, _EPROCESS::Job, JOB_OBJECT_LIMIT_BREAKAWAY_OK, JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, KeActiveProcessors, KeGetPreviousModeByThread, KeInitializeProcess(), KeQuerySystemTime(), KernelMode, _EJOB::LimitFlags, LpcPortObjectType, MAXIMUM_ALLOWED, _UNICODE_STRING::MaximumLength, _MMSUPPORT::MaximumWorkingSetSize, MmCopyVirtualMemory(), MmCreatePeb(), MmCreateProcessAddressSpace(), MmInitializeHandBuiltProcess(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), MmSectionObjectType, _INITIAL_PEB::Mutant, _OBJECT_NAME_INFORMATION::Name, NORMAL_BASE_PRIORITY, NOTHING, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObGetObjectSecurity(), ObInheritDeviceMap(), ObInitProcess(), ObInsertObject(), _HANDLE_TABLE_ENTRY::Object, _EPROCESS::ObjectTable, ObReferenceObject, ObReferenceObjectByHandle, ObReleaseObjectSecurity(), PAGED_CODE, PagedPool, _EPROCESS::Pcb, _EPROCESS::Peb, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, _EPROCESS::PriorityClass, PROCESS_ALL_ACCESS, PROCESS_CREATE_FLAGS_ALL_LARGE_PAGE_FLAGS, PROCESS_CREATE_FLAGS_BREAKAWAY, PROCESS_CREATE_FLAGS_INHERIT_HANDLES, PROCESS_CREATE_FLAGS_LARGE_PAGES, PROCESS_CREATE_FLAGS_LEGAL_MASK, PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT, PROCESS_CREATE_FLAGS_OVERRIDE_ADDRESS_SPACE, PROCESS_CREATE_PROCESS, PROCESS_CREATE_THREAD, PROCESS_DUP_HANDLE, PROCESS_HARDERROR_ALIGNMENT_BIT, PROCESS_HARDERROR_DEFAULT, PROCESS_PRIORITY_CLASS_BELOW_NORMAL, PROCESS_PRIORITY_CLASS_IDLE, PROCESS_PRIORITY_CLASS_NORMAL, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION, PROCESS_SET_QUOTA, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, PS_PROCESS_FLAGS_HAS_ADDRESS_SPACE, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_PROCESS_FLAGS_OVERRIDE_ADDRESS_SPACE, PS_SET_BITS, PsActiveProcessHead, PsDereferencePrimaryTokenEx, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, PsMaximumWorkingSet, PsMinimumWorkingSet, PspAddProcessToJob(), PspCidTable, PspComputeQuantumAndPriority(), PspGetJobFromSet(), PspInheritQuota(), PspInitializeProcessLock(), PspInitializeProcessSecurity(), PspLockProcessList(), PsProcessPriorityBackground, PsProcessType, PspUnlockProcessList(), PsReferencePrimaryToken(), PsUseImpersonationToken, _KPROCESS::QuantumReset, RtlCopyMemory, RtlZeroMemory, _EPROCESS::RundownProtect, SeAccessCheck(), SeAssignPrimaryToken(), SeAuditProcessCreation(), _EPROCESS::SeAuditProcessCreationInfo, SeCreateAccessStateEx(), SECTION_MAP_EXECUTE, _EPROCESS::SectionBaseAddress, _EPROCESS::SectionObject, SeDeleteAccessState(), SeDetailedAuditingWithToken(), _EJOB::SessionId, SeSubProcessToken(), STANDARD_RIGHTS_ALL, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, _EPROCESS::ThreadListHead, _EJOB::Token, TRUE, _OBJECT_TYPE::TypeInfo, _EPROCESS::UniqueProcessId, and _EPROCESS::Vm.
Referenced by NtCreateProcessEx(), PsCreateSystemProcess(), and PspInitPhase0().
NTSTATUS PspCreateThread (OUT PHANDLE ThreadHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN HANDLE ProcessHandle, IN PEPROCESS ProcessPointer, OUT PCLIENT_ID ClientId OPTIONAL, IN PCONTEXT ThreadContext OPTIONAL, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN CreateSuspended, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext)
Definition at line 243 of file create.c.
References _EPROCESS::ActiveThreads, _ETHREAD::ActiveTimerListHead, _ETHREAD::ActiveTimerListLock, ARGUMENT_PRESENT, ASSERT, _ETHREAD::Cid, _SECURITY_SUBJECT_CONTEXT::ClientToken, _EJOB::CompletionKey, _EJOB::CompletionPort, CONTEXT_TO_PROGRAM_COUNTER, _ETHREAD::CrossThreadFlags, ExAcquireResourceSharedLite(), ExAcquireRundownProtection(), except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExCreateHandle(), ExDereferenceCallBackBlock(), ExGetCallBackBlockRoutine(), ExInitializeRundownProtection(), ExReferenceCallBackBlock(), ExReleaseResourceLite(), ExReleaseRundownProtection(), FALSE, _EPROCESS::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _ETHREAD::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _LARGE_INTEGER::HighPart, _EPROCESS::InheritedFromUniqueProcessId, InitializeListHead(), InsertTailList(), IoSetIoCompletion(), _ETHREAD::IrpList, _EPROCESS::Job, JOB_OBJECT_MSG_NEW_PROCESS, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeForceResumeThread(), KeGetPreviousModeByThread, KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitThread(), KeLeaveCriticalRegionThread(), KeQuerySystemTime(), KeReadyThread(), KeResumeThread(), KernelMode, KeStartThread(), KeSuspendThread(), KeUninitThread(), _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplySemaphore, MAXIMUM_ALLOWED, MmCreateTeb(), MmDeleteTeb(), MmReadClusterSize, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObDereferenceObjectEx(), ObGetObjectSecurity(), ObInsertObject(), _HANDLE_TABLE_ENTRY::Object, ObReferenceObject, ObReferenceObjectByHandle, ObReferenceObjectEx(), ObReleaseObjectSecurity(), PAGED_CODE, _EPROCESS::Pcb, PERFINFO_PROCESS_CREATE, PERFINFO_THREAD_CREATE, _ETHREAD::PostBlockList, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PROCESS_CREATE_THREAD, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_SYSTEM, PS_CROSS_THREAD_FLAGS_TERMINATED, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PS_SET_THREAD_CREATE_TIME, PsDereferencePrimaryTokenEx, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, PSP_MAX_CREATE_PROCESS_NOTIFY, PSP_MAX_CREATE_THREAD_NOTIFY, PspCidTable, PspCreateProcessNotifyRoutine, PspCreateProcessNotifyRoutineCount, PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, PspInitializeThreadLock(), PspLockProcessExclusive(), PsProcessType, PspSystemThreadStartup(), PspUnlockProcessExclusive(), PspUserThreadStartup(), PsReferencePrimaryToken(), PsThreadType, PsUseImpersonationToken, _ETHREAD::ReadClusterSize, RtlZeroMemory, _EPROCESS::RundownProtect, _ETHREAD::RundownProtect, SeAccessCheck(), SeCreateAccessStateEx(), SeDeleteAccessState(), _ETHREAD::StartAddress, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_SUSPEND_COUNT_EXCEEDED, _ETHREAD::Tcb, THREAD_ALL_ACCESS, THREAD_QUERY_INFORMATION, THREAD_SET_INFORMATION, THREAD_TERMINATE, THREAD_TO_PROCESS, _ETHREAD::ThreadListEntry, _EPROCESS::ThreadListHead, _ETHREAD::ThreadsProcess, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _EPROCESS::UniqueProcessId, _CLIENT_ID::UniqueThread, VOID, and _ETHREAD::Win32StartAddress.
Referenced by NtCreateThread(), and PsCreateSystemThread().
VOID PspDeleteLdt (IN PEPROCESS Process)
Definition at line 178 of file psldt.c.
References _LDTINFORMATION::AllocatedSize, ExFreePool(), _LDTINFORMATION::Ldt, NULL, PAGED_CODE, PsReturnProcessNonPagedPoolQuota(), and UNREFERENCED_PARAMETER.
Referenced by PspProcessDelete().
VOID PspDeleteProcessSecurity (IN PEPROCESS Process)
Definition at line 1436 of file security.c.
References ExFastRefObjectNull(), PAGED_CODE, and SeDeassignPrimaryToken().
Referenced by PspProcessDelete().
VOID PspDeleteThreadSecurity (IN PETHREAD Thread)
Definition at line 1650 of file security.c.
References ExFreePoolWithTag, NULL, ObDereferenceObject(), PAGED_CODE, PROTECTED_POOL, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, PS_IS_THREAD_IMPERSONATING, and _PS_IMPERSONATION_INFORMATION::Token.
Referenced by PspThreadDelete().
VOID PspDeleteVdmObjects (IN PEPROCESS Process)
Definition at line 56 of file psvdm.c.
References CONTAINING_RECORD, ExDeleteResourceLite(), ExFreePool(), _LIST_ENTRY::Flink, _VDM_IO_HANDLER::Next, NULL, PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), RemoveEntryList(), and UNREFERENCED_PARAMETER.
Referenced by PspProcessDelete().
VOID PspDereferenceQuota (IN PEPROCESS Process)
Definition at line 1006 of file psquota.c.
References ASSERT, InterlockedDecrement, _EPROCESS_QUOTA_BLOCK::ProcessCount, PsNonPagedPool, PsPagedPool, PsPageFile, and PspDereferenceQuotaBlock().
Referenced by PspProcessDelete().
VOID PspExitApcRundown (IN PKAPC Apc)
Definition at line 686 of file psdelete.c.
References ExFreePool(), and PAGED_CODE.
Referenced by PsExitSpecialApc(), PspExitNormalApc(), and PspTerminateThreadByPointer().
VOID PspExitNormalApc (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 696 of file psdelete.c.
References _KTHREAD::ApcState, ASSERT, KeInitializeApc(), KeInsertQueueApc(), OriginalApcEnvironment, PAGED_CODE, PsExitSpecialApc(), PsGetCurrentThread(), PsGetKernelThread(), PspExitApcRundown(), PspExitNormalApc(), _ETHREAD::Tcb, TRUE, _KAPC_STATE::UserApcPending, and UserMode.
Referenced by PspExitNormalApc(), and PspTerminateThreadByPointer().
VOID PspExitProcess (IN BOOLEAN TrimAddressSpace, IN PEPROCESS Process)
Definition at line 1345 of file psdelete.c.
References CCPF_IS_PREFETCHER_ACTIVE, CcPfProcessExitNotification(), _EJOB::CompletionKey, _EJOB::CompletionPort, ExAcquireResourceSharedLite(), ExDereferenceCallBackBlock(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExReleaseResourceLite(), FALSE, IoSetIoCompletion(), JOB_OBJECT_MSG_ABNORMAL_EXIT_PROCESS, JOB_OBJECT_MSG_EXIT_PROCESS, _EJOB::JobLock, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeMaximumIncrement, MmCleanProcessAddressSpace(), NULL, ObDereferenceObject(), PAGED_CODE, PERFINFO_PROCESS_DELETE, PoRundownProcess, PS_JOB_STATUS_EXIT_PROCESS_REPORTED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_PROCESS_FLAGS_PROCESS_EXITING, PS_PROCESS_FLAGS_SET_TIMER_RESOLUTION, PS_SET_BITS, PS_SET_CLEAR_BITS, PsGetCurrentThread(), PSP_MAX_CREATE_PROCESS_NOTIFY, PspCreateProcessNotifyRoutine, PspCreateProcessNotifyRoutineCount, STATUS_ACCESS_VIOLATION, STATUS_ARRAY_BOUNDS_EXCEEDED, STATUS_BREAKPOINT, STATUS_CONTROL_C_EXIT, STATUS_DATATYPE_MISALIGNMENT, STATUS_FLOAT_DENORMAL_OPERAND, STATUS_FLOAT_DIVIDE_BY_ZERO, STATUS_FLOAT_INEXACT_RESULT, STATUS_FLOAT_INVALID_OPERATION, STATUS_FLOAT_MULTIPLE_FAULTS, STATUS_FLOAT_MULTIPLE_TRAPS, STATUS_FLOAT_OVERFLOW, STATUS_FLOAT_STACK_CHECK, STATUS_FLOAT_UNDERFLOW, STATUS_GUARD_PAGE_VIOLATION, STATUS_ILLEGAL_INSTRUCTION, STATUS_IN_PAGE_ERROR, STATUS_INTEGER_DIVIDE_BY_ZERO, STATUS_INTEGER_OVERFLOW, STATUS_INVALID_DISPOSITION, STATUS_NONCONTINUABLE_EXCEPTION, STATUS_PRIVILEGED_INSTRUCTION, STATUS_REG_NAT_CONSUMPTION, STATUS_SINGLE_STEP, STATUS_STACK_OVERFLOW, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and ZwSetTimerResolution().
Referenced by PspExitThread(), and PspProcessDelete().
VOID PspExitProcessFromJob (PEJOB Job, PEPROCESS Process)
Definition at line 650 of file psjob.c.
References _EJOB::ActiveProcesses, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), PAGED_CODE, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PsGetCurrentThread(), PspFoldProcessAccountingIntoJob(), _ETHREAD::Tcb, and TRUE.
Referenced by PspExitThread().
VOID PspExitSpecialApc (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE * NormalRoutine, IN OUT PVOID * NormalContext, IN OUT PVOID * SystemArgument1, IN OUT PVOID * SystemArgument2)
DECLSPEC_NORETURN VOID PspExitThread (IN NTSTATUS ExitStatus)
Definition at line 794 of file psdelete.c.
References ACTIVE_EX_WORKER_THREAD_TERMINATION, _ETHREAD::ActiveExWorker, _EPROCESS::ActiveThreads, _KTHREAD::ApcQueueable, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, _KTHREAD::BBTData, _ETHREAD::Cid, CmNotifyRunDown(), _KTHREAD::CombinedApcDisable, CONTAINING_RECORD, _LPC_CLIENT_DIED_MSG::CreateTime, CRITICAL_PROCESS_DIED, _ETHREAD::CrossThreadFlags, DbgkExitProcess(), DbgkExitThread(), _EPROCESS::DebugPort, _KTHREAD::EnableStackSwap, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExDereferenceCallBackBlock(), Executive, ExFreePool(), ExFreePoolWithTag, ExGetCallBackBlockRoutine(), _EPROCESS::ExitStatus, _ETHREAD::ExitStatus, _EPROCESS::ExitTime, _ETHREAD::ExitTime, ExReferenceCallBackBlock(), ExTimerRundown(), ExWaitForRundownProtectionRelease(), FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _EPROCESS::ImageFileName, INVALID_PROCESS_ATTACH_ATTEMPT, IoCancelThreadIo(), IS_SYSTEM_THREAD, _EPROCESS::Job, KD_DEBUGGER_ENABLED, KeBugCheckEx(), KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeFlushQueueApc(), KeForceResumeThread(), KeGetCurrentIrql(), KeLeaveCriticalRegionThread(), KeLowerIrql, KeQuerySystemTime(), KeReadStateThread(), KERNEL_APC_PENDING_DURING_EXIT, KERNEL_STACK_LOCKED_AT_EXIT, KernelMode, KeRundownThread(), KeSetProcess(), KeTerminateThread(), KeWaitForSingleObject(), _EPROCESS::LastThreadExitStatus, LPC_CLIENT_DIED, LpcExitThread(), LpcRequestPort(), MEM_RELEASE, MmCleanProcessAddressSpace(), MmDeleteTeb(), _TERMINATION_PORT::Next, NtCurrentProcess, NULL, ObCloseHandle(), ObDereferenceObject(), ObKillProcess(), ObReferenceObjectSafe(), PAGED_CODE, PASSIVE_LEVEL, _EPROCESS::Pcb, _EPROCESS::Peb, PERFINFO_THREAD_DELETE, _TERMINATION_PORT::Port, _LPC_CLIENT_DIED_MSG::PortMsg, PoRundownThread, _KAPC_STATE::Process, PROTECTED_POOL, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_GET_THREAD_CREATE_TIME, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PsDereferencePrimaryTokenEx, PsGetCurrentProcessByThread, PsGetCurrentThread(), PSP_MAX_CREATE_THREAD_NOTIFY, PspBBTNotifyRoutine, PspCatchCriticalBreak(), PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, PspExitProcess(), PspExitProcessFromJob(), PspLockProcessExclusive(), PspUnlockProcessExclusive(), PspW32ProcessCallout, PspW32ThreadCallout, PsReferencePrimaryToken(), PsW32ThreadCalloutExit, _LARGE_INTEGER::QuadPart, _ETHREAD::RundownProtect, _KAPC::RundownRoutine, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SeAuditProcessExit(), _EPROCESS::SectionObject, SeDetailedAuditingWithToken(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_PENDING, STATUS_THREAD_IS_TERMINATING, _ETHREAD::Tcb, _KTHREAD::Teb, _ETHREAD::TerminationPort, THREAD_TO_PROCESS, _EPROCESS::ThreadListHead, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, UlongToPtr, _EPROCESS::UniqueProcessId, _CLIENT_ID::UniqueThread, UserMode, _EPROCESS::VdmObjects, _EPROCESS::Win32Process, _KTHREAD::Win32Thread, WOW64_GET_TEB32_SAFE, and ZwFreeVirtualMemory().
Referenced by PsExitSpecialApc(), and PspTerminateThreadByPointer().
VOID PspFoldProcessAccountingIntoJob (PEJOB Job, PEPROCESS Process)
Definition at line 2681 of file psjob.c.
References _EJOB::ActiveProcesses, _EPROCESS::CommitChargePeak, _EJOB::CompletionKey, _EJOB::CompletionPort, FALSE, IoSetIoCompletion(), JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO, _EPROCESS::JobStatus, KeQueryValuesProcess(), _KPROCESS_VALUES::KernelTime, NULL, _EJOB::OtherOperationCount, _KPROCESS_VALUES::OtherOperationCount, _EJOB::OtherTransferCount, _KPROCESS_VALUES::OtherTransferCount, _MMSUPPORT::PageFaultCount, _EPROCESS::Pcb, _EJOB::PeakProcessMemoryUsed, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_SET_CLEAR_BITS, _LARGE_INTEGER::QuadPart, _EJOB::ReadOperationCount, _KPROCESS_VALUES::ReadOperationCount, _EJOB::ReadTransferCount, _KPROCESS_VALUES::ReadTransferCount, STATUS_SUCCESS, _EJOB::ThisPeriodTotalKernelTime, _EJOB::ThisPeriodTotalUserTime, _EJOB::TotalKernelTime, _EJOB::TotalPageFaultCount, _EJOB::TotalUserTime, _KPROCESS_VALUES::UserTime, _EPROCESS::Vm, _EJOB::WriteOperationCount, _KPROCESS_VALUES::WriteOperationCount, _EJOB::WriteTransferCount, and _KPROCESS_VALUES::WriteTransferCount.
Referenced by NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), PspExitProcessFromJob(), PspRemoveProcessFromJob(), and PspTerminateAllProcessesInJob().
VOID PspGetContext (IN PKTRAP_FRAME TrapFrame, IN PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN OUT PCONTEXT Context)
Definition at line 43 of file psctxamd64.c.
References CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXCEPTION_FLAGS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, CONTEXT_SEGMENTS, DR7_ACTIVE, KeContextFromKframes(), NULL, PAGED_CODE, RPL_MASK, and UNREFERENCED_PARAMETER.
Referenced by PspGetSetContextInternal(), and PspGetSetContextSpecialApc().
NTSTATUS PspGetJobFromSet (IN PEJOB ParentJob, IN ULONG JobMemberLevel, OUT PEJOB * pJob)
Definition at line 3195 of file psjob.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, _EJOB::MemberLevel, ObReferenceObject, ObReferenceObjectSafe(), PsGetCurrentThread(), PspLockJobListShared(), PspUnlockJobListShared(), Status, STATUS_ACCESS_DENIED, and STATUS_SUCCESS.
Referenced by PspCreateProcess().
PEPROCESS PspGetNextJobProcess (IN PEJOB Job, IN PEPROCESS Process)
Definition at line 519 of file psenum.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, NULL, ObDereferenceObjectDeferDelete(), ObReferenceObjectSafe(), and PAGED_CODE.
Referenced by PspApplyJobLimitsToProcessSet().
VOID PspGetSetContextSpecialApc (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE * NormalRoutine, IN OUT PVOID * NormalContext, IN OUT PVOID * SystemArgument1, IN OUT PVOID * SystemArgument2)
VOID PspImageNotifyTest (IN PUNICODE_STRING FullImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
Definition at line 2441 of file create.c.
References UNREFERENCED_PARAMETER.
Referenced by PspInitPhase0().
VOID PspInheritQuota (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess)
Definition at line 987 of file psquota.c.
References InterlockedIncrement, _EPROCESS_QUOTA_BLOCK::ProcessCount, PspDefaultQuotaBlock, and _EPROCESS_QUOTA_BLOCK::ReferenceCount.
Referenced by PspCreateProcess().
VOID FORCEINLINE PspInitializeJobLimitsLock (IN PEJOB Job)
Definition at line 945 of file psp.h.
References KeInitializeGuardedMutex().
Referenced by NtCreateJobObject().
VOID FORCEINLINE PspInitializeJobListLock (VOID)
Definition at line 891 of file psp.h.
References KeInitializeGuardedMutex().
Referenced by PspInitializeJobStructures().
VOID PspInitializeJobStructures (VOID)
VOID PspInitializeJobStructuresPhase1 (VOID)
VOID FORCEINLINE PspInitializeJobTimeLimitsLock (VOID)
Definition at line 1043 of file psp.h.
References KeInitializeGuardedMutex().
Referenced by PspInitializeJobStructures().
VOID FORCEINLINE PspInitializeProcessListLock (VOID)
Definition at line 856 of file psp.h.
References KeInitializeGuardedMutex().
Referenced by PspInitPhase0().
VOID FORCEINLINE PspInitializeProcessLock (IN PEPROCESS Process)
Definition at line 697 of file psp.h.
References ExInitializePushLock().
Referenced by PspCreateProcess(), and PspInitPhase0().
NTSTATUS PspInitializeProcessSecurity (IN PEPROCESS Parent OPTIONAL, IN PEPROCESS Child)
Definition at line 1342 of file security.c.
References ARGUMENT_PRESENT, MmGetSessionId(), NT_SUCCESS, NULL, ObInitializeFastReference(), PAGED_CODE, PsDereferencePrimaryTokenEx, PspBootAccessToken, PsReferencePrimaryToken(), SeAssignPrimaryToken(), SeSubProcessToken(), Status, STATUS_SUCCESS, and TRUE.
Referenced by PspCreateProcess().
NTSTATUS PspInitializeSystemDll (VOID)
Definition at line 840 of file psinit.c.
References DbgPrint(), KdUpdateDataBlock(), KeBugCheckEx(), _SYSTEM_DLL::LoaderInitRoutine, NT_SUCCESS, NULL, PROCESS1_INITIALIZATION_FAILED, PspLookupKernelUserEntryPoints(), PspLookupSystemDllEntryPoint(), and STATUS_SUCCESS.
Referenced by PspInitPhase1().
VOID FORCEINLINE PspInitializeThreadLock (IN PETHREAD Thread)
Definition at line 796 of file psp.h.
References ExInitializePushLock().
Referenced by PspCreateThread().
VOID PspInitializeThreadSecurity (IN PEPROCESS Process, IN PETHREAD Thread)
Definition at line 1607 of file security.c.
References NULL, PAGED_CODE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_IMPERSONATING, and UNREFERENCED_PARAMETER.
VOID FORCEINLINE PspInitializeWorkingSetChangeLock (VOID)
Definition at line 1095 of file psp.h.
References KeInitializeGuardedMutex(), and _JOB_WORKING_SET_CHANGE_HEAD::Lock.
Referenced by PspInitPhase0().
BOOLEAN PspInitPhase0 (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 187 of file psinit.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExAllocatePoolWithTag, ExCreateHandleTable(), ExFastRefGetObject(), ExInitializeCallBack(), ExInitializeRundownProtection(), ExInitializeWorkItem, ExRemoveHandleTable(), ExSetHandleTableStrictFIFO(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _SE_AUDIT_PROCESS_CREATION_INFO::ImageFileName, _EPROCESS::ImageFileName, InitializeListHead(), InitializeObjectAttributes, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, JOB_OBJECT_ALL_ACCESS, KeBugCheckEx(), KernelMode, _KPROCESS::KernelTime, _OBJECT_TYPE_INITIALIZER::Length, _JOB_WORKING_SET_CHANGE_HEAD::Links, MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSmallSystem, _SINGLE_LIST_ENTRY::Next, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_EXCLUSIVE, OBJ_OPENIF, OBJ_PERMANENT, ObReferenceObjectByHandle, PagedPool, _EPROCESS::Pcb, Phase1Initialization(), _OBJECT_TYPE_INITIALIZER::PoolType, PROCESS_ALL_ACCESS, PROCESS_INITIALIZATION_FAILED, PsChangeQuantumTable(), PsCreateSystemThread(), PsGetCurrentProcess(), PsMaximumWorkingSet, PsMinimumWorkingSet, PSP_1MB, PSP_MAX_CREATE_PROCESS_NOTIFY, PSP_MAX_CREATE_THREAD_NOTIFY, PSP_MAX_LOAD_IMAGE_NOTIFY, PSP_PROCESS_NONPAGED_CHARGE, PSP_PROCESS_PAGED_CHARGE, PSP_THREAD_NONPAGED_CHARGE, PSP_THREAD_PAGED_CHARGE, PspCreateProcess(), PspCreateProcessNotifyRoutine, PspCreateThreadNotifyRoutine, PspImageNotifyTest(), PspInitializeJobStructures(), PspInitializeProcessListLock(), PspInitializeProcessLock(), PspInitializeWorkingSetChangeLock(), PspJobClose(), PspJobDelete(), PspJobMapping, PspLdtInitialize(), PspLoadImageNotifyRoutine, PspProcessDelete(), PspProcessMapping, PspReaper(), PspThreadDelete(), PspThreadMapping, PspVdmInitialize(), PspWorkingSetChangeHead, PsSetLoadImageNotifyRoutine(), RtlInitUnicodeString(), RtlZeroMemory, _EPROCESS::RundownProtect, _EPROCESS::SeAuditProcessCreationInfo, _OBJECT_TYPE_INITIALIZER::SecurityRequired, Status, strcpy(), THREAD_ALL_ACCESS, _EPROCESS::ThreadListHead, _EPROCESS::Token, TRUE, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, and ZwClose().
Referenced by PsInitSystem().
BOOLEAN PspInitPhase1 (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 540 of file psinit.c.
References FALSE, NT_SUCCESS, PspInitializeJobStructuresPhase1(), PspInitializeSystemDll(), TRUE, and UNREFERENCED_PARAMETER.
Referenced by PsInitSystem().
VOID PspInsertQuotaBlock (IN PEPROCESS_QUOTA_BLOCK QuotaBlock)
Definition at line 70 of file psquota.c.
References ExAcquireSpinLock, ExReleaseSpinLock, InsertTailList(), and PspQuotaLock.
Referenced by PspSetQuotaLimits().
VOID PspJobClose (IN PEPROCESS Process, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 780 of file psjob.c.
References _EJOB::CompletionPort, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, _EJOB::JobFlags, _EJOB::JobLock, KeEnterGuardedRegionThread(), KeLeaveGuardedRegionThread(), _EJOB::LimitFlags, NULL, ObDereferenceObject(), PAGED_CODE, PS_JOB_FLAGS_CLOSE_DONE, PS_SET_BITS, PsGetCurrentThread(), PspLockJobLimitsExclusiveUnsafe(), PspTerminateAllProcessesInJob(), PspUnlockJobLimitsExclusiveUnsafe(), STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and UNREFERENCED_PARAMETER.
Referenced by PspInitPhase0().
VOID PspJobDelete (IN PVOID Object)
Definition at line 681 of file psjob.c.
References _WIN32_JOBCALLOUT_PARAMETERS::CalloutType, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedSids, _EJOB::CompletionPort, CONTAINING_RECORD, _WIN32_JOBCALLOUT_PARAMETERS::Data, ExAcquireResourceExclusiveLite(), ExDeleteResourceLite(), ExFreePool(), ExReleaseResourceLite(), _EJOB::Filter, _LIST_ENTRY::Flink, IsListEmpty, _WIN32_JOBCALLOUT_PARAMETERS::Job, _EJOB::JobLinks, _EJOB::JobLock, _EJOB::JobSetLinks, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _EJOB::LimitFlags, NULL, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), PAGED_CODE, PsGetCurrentThread(), PspLockJobListExclusive(), PspUnlockJobListExclusive(), PspW32JobCallout, PspWin32SessionCallout(), PsW32JobCalloutTerminate, RemoveEntryList(), _EJOB::SessionId, _ETHREAD::Tcb, _EJOB::Token, and TRUE.
Referenced by PspInitPhase0().
VOID PspJobTimeLimitsDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 3034 of file psjob.c.
References DelayedWorkQueue, ExQueueWorkItem(), and UNREFERENCED_PARAMETER.
Referenced by PspInitializeJobStructures().
VOID PspJobTimeLimitsWork (IN PVOID Context)
Definition at line 3003 of file psjob.c.
References KeSetTimer(), PAGED_CODE, PsEnforceExecutionTimeLimits(), PsGetCurrentThread(), PspJobTimeLimitsShuttingDown, PspLockJobTimeLimitsShared(), PspUnlockJobTimeLimitsShared(), and UNREFERENCED_PARAMETER.
Referenced by PspInitializeJobStructures().
VOID FORCEINLINE PspLockJobLimitsExclusive (IN PEJOB Job, IN PETHREAD CurrentThread)
Definition at line 954 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
VOID FORCEINLINE PspLockJobLimitsExclusiveUnsafe (IN PEJOB Job)
Definition at line 965 of file psp.h.
References ASSERT, KeAcquireGuardedMutexUnsafe(), and KeAreAllApcsDisabled().
Referenced by NtSetInformationJobObject(), and PspJobClose().
VOID FORCEINLINE PspLockJobLimitsShared (IN PEJOB Job, IN PETHREAD CurrentThread)
Definition at line 975 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
Referenced by PsChangeJobMemoryUsage(), PspApplyJobLimitsToProcess(), and PsReportProcessMemoryLimitViolation().
VOID FORCEINLINE PspLockJobLimitsSharedUnsafe (IN PEJOB Job)
Definition at line 986 of file psp.h.
References ASSERT, KeAcquireGuardedMutexUnsafe(), and KeAreAllApcsDisabled().
Referenced by NtQueryInformationJobObject().
VOID FORCEINLINE PspLockJobListExclusive (IN PETHREAD CurrentThread)
Definition at line 901 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
Referenced by NtCreateJobObject(), NtCreateJobSet(), and PspJobDelete().
VOID FORCEINLINE PspLockJobListShared (IN PETHREAD CurrentThread)
Definition at line 911 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
Referenced by NtQueryInformationJobObject(), PsGetNextJob(), and PspGetJobFromSet().
VOID FORCEINLINE PspLockJobTimeLimitsExclusive (IN PETHREAD CurrentThread)
Definition at line 1052 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
Referenced by PspShutdownJobLimits().
VOID FORCEINLINE PspLockJobTimeLimitsShared (IN PETHREAD CurrentThread)
Definition at line 1072 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
Referenced by PspJobTimeLimitsWork().
VOID FORCEINLINE PspLockProcessExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 706 of file psp.h.
References ExAcquirePushLockExclusive(), and KeEnterCriticalRegionThread().
Referenced by NtSetInformationProcess(), PspApplyJobLimitsToProcess(), PspCreateThread(), PspExitThread(), PspLockProcessSecurityExclusive(), PspThreadDelete(), and PsSetProcessWin32Process().
VOID FORCEINLINE PspLockProcessList (IN PETHREAD CurrentThread)
Definition at line 865 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), and KeEnterGuardedRegionThread().
Referenced by PsChangeQuantumTable(), PsEnumProcesses(), PsGetNextProcess(), PspCreateProcess(), and PspProcessDelete().
VOID FORCEINLINE PspLockProcessSecurityExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 755 of file psp.h.
References PspLockProcessExclusive().
Referenced by PspAssignPrimaryToken().
VOID FORCEINLINE PspLockProcessSecurityShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 765 of file psp.h.
References PspLockProcessShared().
Referenced by PsReferenceEffectiveToken(), and PsReferencePrimaryToken().
VOID FORCEINLINE PspLockProcessShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 717 of file psp.h.
References ExAcquirePushLockShared(), and KeEnterCriticalRegionThread().
Referenced by NtSetInformationThread(), PsGetNextProcessThread(), and PspLockProcessSecurityShared().
VOID FORCEINLINE PspLockThreadSecurityExclusive (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Definition at line 805 of file psp.h.
References ExAcquirePushLockExclusive(), and KeEnterCriticalRegionThread().
Referenced by PsDisableImpersonation(), PsImpersonateClient(), PsRestoreImpersonation(), PsRevertThreadToSelf(), and PsRevertToSelf().
VOID FORCEINLINE PspLockThreadSecurityShared (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Definition at line 816 of file psp.h.
References ExAcquirePushLockShared(), and KeEnterCriticalRegionThread().
Referenced by PsReferenceEffectiveToken(), and PsReferenceImpersonationToken().
VOID FORCEINLINE PspLockWorkingSetChangeExclusive (IN PETHREAD CurrentThread)
Definition at line 1104 of file psp.h.
References KeAcquireGuardedMutexUnsafe(), KeEnterGuardedRegionThread(), and _JOB_WORKING_SET_CHANGE_HEAD::Lock.
VOID FORCEINLINE PspLockWorkingSetChangeExclusiveUnsafe (VOID)
Definition at line 1124 of file psp.h.
References ASSERT, KeAcquireGuardedMutexUnsafe(), KeAreAllApcsDisabled(), and _JOB_WORKING_SET_CHANGE_HEAD::Lock.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), and PspSetQuotaLimits().
NTSTATUS PspLookupKernelUserEntryPoints (VOID)
Definition at line 24 of file kulookup.c.
References KdPrint, KeFeatureBits, KeRaiseUserExceptionDispatcher, KeUserApcDispatcher, KeUserCallbackDispatcher, KeUserExceptionDispatcher, KeUserPopEntrySListEnd, KeUserPopEntrySListFault, KeUserPopEntrySListResume, KF_FAST_SYSCALL, NT_SUCCESS, PspLookupSystemDllEntryPoint(), SharedUserData, and Status.
Referenced by PspInitializeSystemDll().
NTSTATUS PspLookupSystemDllEntryPoint (IN PSZ EntryPointName, OUT PVOID * EntryPointAddress)
Definition at line 896 of file psinit.c.
References _SYSTEM_DLL::DllBase, and LookupEntryPoint().
Referenced by PspInitializeSystemDll(), and PspLookupKernelUserEntryPoints().
USHORT PspNameToOrdinal (IN PSZ EntryPointName, IN ULONG DllBase, IN ULONG NumberOfNames, IN PULONG NameTableBase, IN PUSHORT OrdinalTableBase)
VOID PspNullSpecialApc (IN PKAPC Apc, IN OUT PKNORMAL_ROUTINE * NormalRoutine, IN OUT PVOID * NormalContext, IN OUT PVOID * SystemArgument1, IN OUT PVOID * SystemArgument2)
VOID PspProcessDelete (IN PVOID Object)
Definition at line 1503 of file psdelete.c.
References _EPROCESS::ActiveProcessLinks, CID_HANDLE_DELETION, _EPROCESS::DebugPort, _EPROCESS::ExceptionPort, ExDestroyHandle(), ExFreePool(), FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _EPROCESS::GrantedAccess, _SE_AUDIT_PROCESS_CREATION_INFO::ImageFileName, _EPROCESS::Job, KeBugCheck(), KeStackAttachProcess(), KeTerminateProcess, KeUnstackDetachProcess(), MmDeleteProcessAddressSpace(), NULL, ObDereferenceDeviceMap(), ObDereferenceObject(), ObDereferenceObjectDeferDelete(), _EPROCESS::ObjectTable, ObKillProcess(), PAGED_CODE, _EPROCESS::Pcb, PS_PROCESS_FLAGS_HAS_ADDRESS_SPACE, PsGetCurrentThread(), PspCidTable, PspDeleteLdt(), PspDeleteProcessSecurity(), PspDeleteVdmObjects(), PspDereferenceQuota(), PspExitProcess(), PspLockProcessList(), PspRemoveProcessFromJob(), PspUnlockProcessList(), PsReturnProcessNonPagedPoolQuota(), RemoveEntryList(), _EPROCESS::SeAuditProcessCreationInfo, _EPROCESS::SectionObject, _EPROCESS::UniqueProcessId, _EPROCESS::WorkingSetWatch, and WS_CATCH_SIZE.
Referenced by PspInitPhase0().
VOID PspProcessDump (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
NTSTATUS PspQueryDescriptorThread (PETHREAD Thread, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength)
Definition at line 135 of file psldt.c.
References ARGUMENT_PRESENT, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, Ke386GetGdtEntryThread(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), KGDT_NUMBER, _EPROCESS::LdtInformation, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, _DESCRIPTOR_TABLE_ENTRY::Selector, SELECTOR_TABLE_INDEX, Status, STATUS_ACCESS_VIOLATION, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_LDT, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, and UNREFERENCED_PARAMETER.
Referenced by NtQueryInformationThread().
NTSTATUS PspQueryLdtInformation (IN PEPROCESS Process, OUT PVOID LdtInformation, IN ULONG LdtInformationLength, OUT PULONG ReturnLength)
Definition at line 22 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtQueryInformationProcess().
VOID PspQuitNextJobProcess (IN PEPROCESS Process)
Definition at line 572 of file psenum.c.
References ObDereferenceObjectDeferDelete().
VOID PspReaper (IN PVOID StartContext)
Definition at line 85 of file psdelete.c.
References ASSERT, CONTAINING_RECORD, _KTHREAD::InitialStack, InterlockedCompareExchangePointer, InterlockedExchangePointer, KeWaitForContextSwap(), _KTHREAD::LargeStack, MmDeleteKernelStack(), _SINGLE_LIST_ENTRY::Next, NULL, ObDereferenceObject(), PsReaperListHead, _KTHREAD::StackBase, _ETHREAD::Tcb, and UNREFERENCED_PARAMETER.
Referenced by PspInitPhase0().
VOID PspRemoveProcessFromJob (PEJOB Job, PEPROCESS Process)
Definition at line 617 of file psjob.c.
References _EJOB::ActiveProcesses, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _EPROCESS::JobLinks, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), PAGED_CODE, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PsGetCurrentThread(), PspFoldProcessAccountingIntoJob(), RemoveEntryList(), _ETHREAD::Tcb, and TRUE.
Referenced by PspProcessDelete().
VOID PspSetContext (OUT PKTRAP_FRAME TrapFrame, OUT PKNONVOLATILE_CONTEXT_POINTERS NonVolatileContext, IN PCONTEXT Context, KPROCESSOR_MODE Mode)
Definition at line 236 of file psctxamd64.c.
References CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, _DISPATCHER_HEADER::DebugActive, DR7_ACTIVE, _KTHREAD::Header, KeContextToKframes(), KeGetCurrentThread(), KernelMode, NULL, PAGED_CODE, RPL_MASK, SANITIZE_DR7, SANITIZE_DRADDR, SANITIZE_MXCSR, UNREFERENCED_PARAMETER, and UserMode.
Referenced by PspGetSetContextInternal(), and PspGetSetContextSpecialApc().
NTSTATUS PspSetLdtInformation (IN PEPROCESS Process, IN PVOID LdtInformation, IN ULONG LdtInformationLength)
Definition at line 99 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtSetInformationProcess().
NTSTATUS PspSetLdtSize (IN PEPROCESS Process, IN PVOID LdtSize, IN ULONG LdtSizeLength)
Definition at line 63 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtSetInformationProcess().
NTSTATUS PspSetPrimaryToken (IN HANDLE ProcessHandle, IN PEPROCESS ProcessPointer OPTIONAL, IN HANDLE TokenHandle OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL, IN BOOLEAN PrivilegeChecked)
Definition at line 389 of file psquery.c.
References _SECURITY_SUBJECT_CONTEXT::ClientToken, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, KeGetPreviousMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceDeviceMap(), ObDereferenceObject(), ObGetObjectSecurity(), ObIsLUIDDeviceMapsEnabled(), ObReferenceObjectByHandle, ObReleaseObjectSecurity(), _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PROCESS_CREATE_PROCESS, PROCESS_CREATE_THREAD, PROCESS_DUP_HANDLE, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION, PROCESS_SET_QUOTA, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, PsDereferencePrimaryTokenEx, PspAssignPrimaryToken(), PsProcessType, PsReferencePrimaryToken(), SeAccessCheck(), SeAssignPrimaryTokenPrivilege, SeCheckPrivilegedObject(), SeIsChildTokenByPointer(), SeIsSiblingTokenByPointer(), SeTokenObjectType, STANDARD_RIGHTS_ALL, Status, STATUS_PRIVILEGE_NOT_HELD, TOKEN_ASSIGN_PRIMARY, and _OBJECT_TYPE::TypeInfo.
Referenced by NtAssignProcessToJobObject(), and NtSetInformationProcess().
NTSTATUS PspSetProcessIoHandlers (IN PEPROCESS Process, IN PVOID IoHandlerInformation, IN ULONG IoHandlerLength)
Definition at line 23 of file psvdm.c.
References _EMULATOR_ACCESS_ENTRY::AccessType, _EMULATOR_ACCESS_ENTRY::BasePort, _PROCESS_IO_PORT_HANDLER_INFORMATION::Context, _PROCESS_IO_PORT_HANDLER_INFORMATION::EmulatorAccessEntries, _PROCESS_IO_PORT_HANDLER_INFORMATION::Install, KeGetPreviousMode, KernelMode, NT_SUCCESS, _EMULATOR_ACCESS_ENTRY::NumConsecutivePorts, PAGED_CODE, Psp386InstallIoHandler(), Psp386RemoveIoHandler(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, Uchar, Ulong, UNREFERENCED_PARAMETER, and Ushort.
Referenced by NtSetInformationProcess().
VOID PspShutdownJobLimits (VOID)
Definition at line 3096 of file psjob.c.
References KeCancelTimer(), PsGetCurrentThread(), PspJobTimeLimitsShuttingDown, PspLockJobTimeLimitsExclusive(), PspUnlockJobTimeLimitsExclusive(), and TRUE.
Referenced by PsShutdownSystem().
LOGICAL PspSinglePrivCheck (IN LUID PrivilegeValue, IN KPROCESSOR_MODE PreviousMode, OUT PPRIV_CHECK_CTX PrivCtx)
Definition at line 1979 of file security.c.
References KernelMode, PRIVILEGE_SET_ALL_NECESSARY, SeCaptureSubjectContext(), SePrivilegeCheck(), and TRUE.
Referenced by PspSetQuotaLimits().
VOID PspSinglePrivCheckAudit (IN LOGICAL PrivUsed, IN PPRIV_CHECK_CTX PrivCtx)
Definition at line 2025 of file security.c.
References KernelMode, NULL, SePrivilegedServiceAuditAlarm(), and SeReleaseSubjectContext().
Referenced by PspSetQuotaLimits().
VOID PspSystemThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
Definition at line 2182 of file create.c.
References _ETHREAD::CrossThreadFlags, except, KeBugCheck(), KeLowerIrql, KMODE_EXCEPTION_NOT_HANDLED, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_TERMINATED, PsGetCurrentThread(), PspTerminateThreadByPointer(), PspUnhandledExceptionInSystemThread(), STATUS_SUCCESS, and TRUE.
Referenced by PspCreateThread().
BOOLEAN PspTerminateAllProcessesInJob (PEJOB Job, NTSTATUS Status, BOOLEAN IncCounter)
Definition at line 2626 of file psjob.c.
References _EJOB::ActiveProcesses, _EJOB::Event, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, _EJOB::JobLock, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeSetEvent(), NT_SUCCESS, NULL, PAGED_CODE, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_BITS, PsGetCurrentThread(), PsGetNextJobProcess(), PspFoldProcessAccountingIntoJob(), PspTerminateProcess(), _ETHREAD::Tcb, _EJOB::TotalTerminatedProcesses, and TRUE.
Referenced by NtTerminateJobObject(), PsEnforceExecutionTimeLimits(), and PspJobClose().
NTSTATUS PspTerminateProcess (PEPROCESS Process, NTSTATUS Status)
Definition at line 405 of file psdelete.c.
References _EPROCESS::DebugPort, FALSE, _EPROCESS::Flags, _EPROCESS::ImageFileName, NULL, ObClearProcessHandleTable(), PAGED_CODE, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PsGetNextProcessThread(), PspCatchCriticalBreak(), PspTerminateThreadByPointer(), STATUS_NOTHING_TO_TERMINATE, and STATUS_SUCCESS.
Referenced by NtAssignProcessToJobObject(), PsEnforceExecutionTimeLimits(), PspTerminateAllProcessesInJob(), and PsTerminateProcess().
NTSTATUS PspTerminateThreadByPointer (IN PETHREAD Thread, IN NTSTATUS ExitStatus, IN BOOLEAN DirectTerminate)
Definition at line 164 of file psdelete.c.
References APC_LEVEL, ASSERT, ExAllocatePoolWithTag, ExFreePool(), FALSE, IS_SYSTEM_THREAD, KeDelayExecutionThread(), KeForceResumeThread(), KeGetCurrentIrql(), KeInitializeApc(), KeInsertQueueApc(), KernelMode, NonPagedPool, NULL, OriginalApcEnvironment, PAGED_CODE, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_CROSS_THREAD_FLAGS_TERMINATED, PS_SET_BITS, PS_TEST_SET_BITS, PsExitSpecialApc(), PsGetCurrentThread(), PsGetKernelThread(), PspCatchCriticalBreak(), PspExitApcRundown(), PspExitNormalApc(), PspExitThread(), Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_TO_PROCESS, and ULongToPtr.
Referenced by NtTerminateProcess(), NtTerminateThread(), PspSystemThreadStartup(), PspTerminateProcess(), PspUserThreadStartup(), and PsTerminateSystemThread().
VOID PspThreadDelete (IN PVOID Object)
Definition at line 1631 of file psdelete.c.
References ASSERT, _ETHREAD::Cid, CID_HANDLE_DELETION, ExDestroyHandle(), _LIST_ENTRY::Flink, _KTHREAD::InitialStack, KeBugCheck(), _KTHREAD::LargeStack, MmDeleteKernelStack(), NULL, ObDereferenceObject(), PAGED_CODE, PsGetCurrentThread(), PspCidTable, PspDeleteThreadSecurity(), PspLockProcessExclusive(), PspUnlockProcessExclusive(), RemoveEntryList(), _KTHREAD::StackBase, _ETHREAD::Tcb, THREAD_TO_PROCESS, _ETHREAD::ThreadListEntry, _CLIENT_ID::UniqueThread, and _KTHREAD::Win32Thread.
Referenced by PspInitPhase0().
VOID PspThreadDump (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
VOID FORCEINLINE PspUnlockJobLimitsExclusive (IN PEJOB Job, IN PETHREAD CurrentThread)
Definition at line 996 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
VOID FORCEINLINE PspUnlockJobLimitsExclusiveUnsafe (IN PEJOB Job)
Definition at line 1007 of file psp.h.
References ASSERT, KeAreAllApcsDisabled(), and KeReleaseGuardedMutexUnsafe().
Referenced by NtSetInformationJobObject(), and PspJobClose().
VOID FORCEINLINE PspUnlockJobLimitsShared (IN PEJOB Job, IN PETHREAD CurrentThread)
Definition at line 1017 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
Referenced by PsChangeJobMemoryUsage(), PspApplyJobLimitsToProcess(), and PsReportProcessMemoryLimitViolation().
VOID FORCEINLINE PspUnlockJobLimitsSharedUnsafe (IN PEJOB Job)
Definition at line 1028 of file psp.h.
References ASSERT, KeAreAllApcsDisabled(), and KeReleaseGuardedMutexUnsafe().
Referenced by NtQueryInformationJobObject().
VOID FORCEINLINE PspUnlockJobListExclusive (IN PETHREAD CurrentThread)
Definition at line 921 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
Referenced by NtCreateJobObject(), NtCreateJobSet(), and PspJobDelete().
VOID FORCEINLINE PspUnlockJobListShared (IN PETHREAD CurrentThread)
Definition at line 931 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
Referenced by NtQueryInformationJobObject(), PsGetNextJob(), and PspGetJobFromSet().
VOID FORCEINLINE PspUnlockJobTimeLimitsExclusive (IN PETHREAD CurrentThread)
Definition at line 1062 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
Referenced by PspShutdownJobLimits().
VOID FORCEINLINE PspUnlockJobTimeLimitsShared (IN PETHREAD CurrentThread)
Definition at line 1082 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
Referenced by PspJobTimeLimitsWork().
VOID FORCEINLINE PspUnlockProcessExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 739 of file psp.h.
References ExReleasePushLockExclusive(), and KeLeaveCriticalRegionThread().
Referenced by NtSetInformationProcess(), PspApplyJobLimitsToProcess(), PspCreateThread(), PspExitThread(), PspThreadDelete(), PspUnlockProcessSecurityExclusive(), and PsSetProcessWin32Process().
VOID FORCEINLINE PspUnlockProcessList (IN PETHREAD CurrentThread)
Definition at line 875 of file psp.h.
References KeLeaveGuardedRegionThread(), and KeReleaseGuardedMutexUnsafe().
Referenced by PsChangeQuantumTable(), PsEnumProcesses(), PsGetNextProcess(), PspCreateProcess(), and PspProcessDelete().
VOID FORCEINLINE PspUnlockProcessSecurityExclusive (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 785 of file psp.h.
References PspUnlockProcessExclusive().
Referenced by PspAssignPrimaryToken().
VOID FORCEINLINE PspUnlockProcessSecurityShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 775 of file psp.h.
References PspUnlockProcessShared().
Referenced by PsReferenceEffectiveToken(), and PsReferencePrimaryToken().
VOID FORCEINLINE PspUnlockProcessShared (IN PEPROCESS Process, IN PETHREAD CurrentThread)
Definition at line 728 of file psp.h.
References ExReleasePushLockShared(), and KeLeaveCriticalRegionThread().
Referenced by NtSetInformationThread(), PsGetNextProcessThread(), and PspUnlockProcessSecurityShared().
VOID FORCEINLINE PspUnlockThreadSecurityExclusive (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Definition at line 839 of file psp.h.
References ExReleasePushLockExclusive(), and KeLeaveCriticalRegionThread().
Referenced by PsDisableImpersonation(), PsImpersonateClient(), PsRestoreImpersonation(), PsRevertThreadToSelf(), and PsRevertToSelf().
VOID FORCEINLINE PspUnlockThreadSecurityShared (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Definition at line 828 of file psp.h.
References ExReleasePushLockShared(), and KeLeaveCriticalRegionThread().
Referenced by PsReferenceEffectiveToken(), and PsReferenceImpersonationToken().
VOID FORCEINLINE PspUnlockWorkingSetChangeExclusive (IN PETHREAD CurrentThread)
Definition at line 1114 of file psp.h.
References KeLeaveGuardedRegionThread(), KeReleaseGuardedMutexUnsafe(), and _JOB_WORKING_SET_CHANGE_HEAD::Lock.
VOID FORCEINLINE PspUnlockWorkingSetChangeExclusiveUnsafe (VOID)
Definition at line 1134 of file psp.h.
References ASSERT, KeAreAllApcsDisabled(), KeReleaseGuardedMutexUnsafe(), and _JOB_WORKING_SET_CHANGE_HEAD::Lock.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), and PspSetQuotaLimits().
VOID PspUserThreadStartup (IN PKSTART_ROUTINE StartRoutine, IN PVOID StartContext)
Definition at line 2003 of file create.c.
References APC_LEVEL, CCPF_IS_PREFETCHER_ENABLED, CcPfBeginAppLaunch(), _ETHREAD::CrossThreadFlags, DbgkCreateThread(), _SYSTEM_DLL::DllBase, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _EPROCESS::Flags, _LARGE_INTEGER::HighPart, _KTHREAD::IdealProcessor, InterlockedCompareExchange(), _KPRCB::InterruptTime, KeGetCurrentPrcb(), KeLowerIrql, KeQuerySystemTime(), KeRaiseIrql, KiInitializeUserApc(), _SYSTEM_DLL::LoaderInitRoutine, _LARGE_INTEGER::LowPart, MmGetSessionLocaleId(), _KPRCB::MmPageFaultCount, NtCurrentTeb(), NULL, PAGED_CODE, PASSIVE_LEVEL, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PS_PROCESS_FLAGS_LAUNCH_PREFETCHED, PS_TEST_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspGetBaseExceptionFrame, PspGetBaseTrapFrame, PspSystemDll, PspTerminateThreadByPointer(), _EPROCESS::SectionObject, SharedUserData, STATUS_THREAD_IS_TERMINATING, _ETHREAD::Tcb, TRUE, and UNREFERENCED_PARAMETER.
Referenced by PspCreateThread().
NTSTATUS PspWaitForUsermodeExit (IN PEPROCESS Process)
Definition at line 471 of file psdelete.c.
References Executive, FALSE, IS_SYSTEM_THREAD, KeReadStateThread(), KernelMode, KeWaitForSingleObject(), NULL, ObDereferenceObject(), ObReferenceObject, PsGetNextProcessThread(), PsQuitNextProcessThread(), STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
Referenced by PsShutdownSystem().
NTSTATUS PspWin32SessionCallout (IN PKWIN32_JOB_CALLOUT CalloutRoutine, IN PKWIN32_JOBCALLOUT_PARAMETERS Parameters, IN ULONG SessionId)
Definition at line 3416 of file psjob.c.
References ASSERT, DPFLTR_SYSTEM_ID, DPFLTR_WARNING_LEVEL, _EPROCESS::Flags, KdPrintEx, MmAttachSession(), MmDetachSession(), MmGetSessionById(), MmGetSessionId(), MmIsSessionAddress(), MmQuitNextSession(), NT_SUCCESS, NULL, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), Status, STATUS_INVALID_PARAMETER, STATUS_NOT_FOUND, and STATUS_SUCCESS.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PspJobDelete().
NTSTATUS PspWriteTebImpersonationInfo (IN PETHREAD Thread, IN PETHREAD CurrentThread)
Definition at line 1699 of file security.c.
References ASSERT, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), FALSE, KeMemoryBarrier(), KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, PAGED_CODE, _EPROCESS::Pcb, PS_IS_THREAD_IMPERSONATING, PsGetCurrentProcessByThread, PsGetCurrentThread(), STATUS_SUCCESS, THREAD_TO_PROCESS, and TRUE.
Referenced by PsImpersonateClient(), PsRevertThreadToSelf(), and PsRevertToSelf().
Variable Documentation
ULONG PsMinimumWorkingSet
Definition at line 62 of file create.c.
Referenced by NtSetInformationJobObject(), and PspCreateProcess().
KGUARDED_MUTEX PspActiveProcessMutex
Definition at line 138 of file psinit.c.
PACCESS_TOKEN PspBootAccessToken
Definition at line 40 of file psinit.c.
Referenced by PspInitializeProcessSecurity().
PHANDLE_TABLE PspCidTable
Definition at line 42 of file psinit.c.
Referenced by PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PspCreateProcess(), PspCreateThread(), PspProcessDelete(), and PspThreadDelete().
EX_CALLBACK PspCreateProcessNotifyRoutine[PSP_MAX_CREATE_PROCESS_NOTIFY]
Definition at line 286 of file psp.h.
Referenced by PspCreateThread(), PspExitProcess(), PspInitPhase0(), and PsSetCreateProcessNotifyRoutine().
ULONG PspCreateProcessNotifyRoutineCount
Definition at line 285 of file psp.h.
Referenced by PspCreateThread(), PspExitProcess(), and PsSetCreateProcessNotifyRoutine().
EX_CALLBACK PspCreateThreadNotifyRoutine[PSP_MAX_CREATE_THREAD_NOTIFY]
Definition at line 295 of file psp.h.
Referenced by PspCreateThread(), PspExitThread(), PspInitPhase0(), PsRemoveCreateThreadNotifyRoutine(), and PsSetCreateThreadNotifyRoutine().
ULONG PspCreateThreadNotifyRoutineCount
Definition at line 294 of file psp.h.
Referenced by PspCreateThread(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), and PsSetCreateThreadNotifyRoutine().
ULONG PspDefaultNonPagedLimit
Definition at line 118 of file psinit.c.
Referenced by PspExpandQuota(), and PspSetQuotaLimits().
ULONG PspDefaultPagedLimit
Definition at line 117 of file psinit.c.
Referenced by PspExpandQuota(), and PspSetQuotaLimits().
ULONG PspDefaultPagefileLimit
Definition at line 119 of file psinit.c.
Referenced by PspSetQuotaLimits().
EPROCESS_QUOTA_BLOCK PspDefaultQuotaBlock
Definition at line 122 of file psinit.c.
Referenced by PsInitializeQuotaSystem(), PspInheritQuota(), PspQueryQuotaLimits(), PspReturnQuota(), and PspSetQuotaLimits().
BOOLEAN PspDoingGiveBacks
Definition at line 123 of file psinit.c.
Referenced by PspReturnQuota().
SCHAR PspForegroundQuantum[3]
Definition at line 120 of file psinit.c.
Referenced by PspComputeQuantumAndPriority().
HANDLE PspInitialSystemProcessHandle
Definition at line 41 of file psinit.c.
Referenced by PsCreateSystemProcess(), and PsShutdownSystem().
KDPC PspJobLimeLimitsDpc
LIST_ENTRY PspJobList
Definition at line 127 of file psinit.c.
Referenced by NtCreateJobObject(), PsGetNextJob(), and PspInitializeJobStructures().
KGUARDED_MUTEX PspJobListLock
Definition at line 125 of file psinit.c.
const SCHAR PspJobSchedulingClasses[PSP_NUMBER_OF_SCHEDULING_CLASSES]
Definition at line 925 of file psinit.c.
Referenced by PspApplyJobLimitsToProcess(), and PspComputeQuantumAndPriority().
KGUARDED_MUTEX PspJobTimeLimitsLock
Definition at line 56 of file psjob.c.
KTIMER PspJobTimeLimitsTimer
Definition at line 54 of file psjob.c.
WORK_QUEUE_ITEM PspJobTimeLimitsWorkItem
Definition at line 55 of file psjob.c.
EX_CALLBACK PspLoadImageNotifyRoutine[PSP_MAX_LOAD_IMAGE_NOTIFY]
Definition at line 305 of file psp.h.
Referenced by PsCallImageNotifyRoutines(), PspInitPhase0(), PsRemoveLoadImageNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
ULONG PspLoadImageNotifyRoutineCount
Definition at line 304 of file psp.h.
Referenced by PsRemoveLoadImageNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
KSPIN_LOCK PspQuotaLock
Definition at line 126 of file psinit.c.
Referenced by PsInitializeQuotaSystem(), PspDereferenceQuotaBlock(), PspExpandQuota(), PspGivebackQuota(), and PspInsertQuotaBlock().
PETHREAD PspShutdownThread
Definition at line 141 of file psinit.c.
Referenced by PsShutdownSystem().
SYSTEM_DLL PspSystemDll
Definition at line 43 of file psinit.c.
Referenced by PspUserThreadStartup(), and PsShutdownSystem().
BOOLEAN PspUseJobSchedulingClasses
Definition at line 39 of file psinit.c.
Referenced by PspApplyJobLimitsToProcess(), and PspComputeQuantumAndPriority().
PKWIN32_JOB_CALLOUT PspW32JobCallout
Definition at line 4291 of file psquery.c.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PspJobDelete().
PKWIN32_PROCESS_CALLOUT PspW32ProcessCallout
Definition at line 4289 of file psquery.c.
Referenced by PsConvertToGuiThread(), and PspExitThread().
ULONG PspW32ProcessSize
PKWIN32_THREAD_CALLOUT PspW32ThreadCallout
Definition at line 4290 of file psquery.c.
Referenced by PsConvertToGuiThread(), and PspExitThread().
ULONG PspW32ThreadSize
JOB_WORKING_SET_CHANGE_HEAD PspWorkingSetChangeHead
Definition at line 159 of file psp.h.
Referenced by NtSetInformationJobObject(), PspApplyJobLimitsToProcessSet(), and PspInitPhase0().