Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/apcobj.c File Reference
apcobj.c File Reference
#include "ki.h"
Macros
#define ASSERT_APC(E) ASSERT((E)->Type == ApcObject)
Functions
PLIST_ENTRY KeFlushQueueApc (__inout PKTHREAD Thread, __in KPROCESSOR_MODE ApcMode)
VOID KeInitializeApc (__out PRKAPC Apc, __in PRKTHREAD Thread, __in KAPC_ENVIRONMENT Environment, __in PKKERNEL_ROUTINE KernelRoutine, __in_opt PKRUNDOWN_ROUTINE RundownRoutine, __in_opt PKNORMAL_ROUTINE NormalRoutine, __in_opt KPROCESSOR_MODE ApcMode, __in_opt PVOID NormalContext)
BOOLEAN KeInsertQueueApc (__inout PRKAPC Apc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2, __in KPRIORITY Increment)
BOOLEAN KeRemoveQueueApc (__inout PKAPC Apc)
Macro Definition Documentation
#define ASSERT_APC (E) ASSERT((E)->Type == ApcObject)
Definition at line 27 of file apcobj.c.
Referenced by KeInsertQueueApc(), and KeRemoveQueueApc().
Function Documentation
PLIST_ENTRY KeFlushQueueApc (__inout PKTHREAD Thread, __in KPROCESSOR_MODE ApcMode)
Definition at line 129 of file apcobj.c.
References ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, InitializeListHead(), _KAPC::Inserted, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), NULL, RemoveEntryList(), and UserMode.
Referenced by PspExitThread().
VOID KeInitializeApc (__out PRKAPC Apc, __in PRKTHREAD Thread, __in KAPC_ENVIRONMENT Environment, __in PKKERNEL_ROUTINE KernelRoutine, __in_opt PKRUNDOWN_ROUTINE RundownRoutine, __in_opt PKNORMAL_ROUTINE NormalRoutine, __in_opt KPROCESSOR_MODE ApcMode, __in_opt PVOID NormalContext)
Definition at line 30 of file apcobj.c.
References ApcObject, ARGUMENT_PRESENT, ASSERT, CurrentApcEnvironment, FALSE, InsertApcEnvironment, KernelMode, and NIL.
Referenced by ExSwapinWorkerThreads(), IopCompleteRequest(), IopfCompleteRequest(), IoRaiseHardError(), IoRaiseInformationalHardError(), KeInitThread(), NtNotifyChangeMultipleKeys(), NtQueueApcThread(), NtSetTimer(), PsGetContextThread(), PspExitNormalApc(), PspTerminateThreadByPointer(), PsSetContextThread(), and WmipCreatePumpThread().
BOOLEAN KeInsertQueueApc (__inout PRKAPC Apc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2, __in KPRIORITY Increment)
Definition at line 228 of file apcobj.c.
References _KTHREAD::ApcQueueable, _KTHREAD::ApcQueueLock, ASSERT, ASSERT_APC, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiInsertQueueApc(), _KLOCK_QUEUE_HANDLE::OldIrql, and TRUE.
Referenced by CmpPostNotify(), ExpTimerDpcRoutine(), ExSwapinWorkerThreads(), IopCompleteRequest(), IopfCompleteRequest(), IoRaiseHardError(), IoRaiseInformationalHardError(), NtQueueApcThread(), PsGetContextThread(), PspExitNormalApc(), PspTerminateThreadByPointer(), PsSetContextThread(), and WmipCreatePumpThread().
BOOLEAN KeRemoveQueueApc (__inout PKAPC Apc)
Definition at line 308 of file apcobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcStatePointer, ASSERT, ASSERT_APC, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), _KAPC_STATE::KernelApcPending, KernelMode, KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, RemoveEntryList(), and _KAPC_STATE::UserApcPending.
Referenced by CmNotifyRunDown(), ExTimerRundown(), NtCancelTimer(), and NtSetTimer().