Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/ldrreloc.c File Reference
ldrreloc.c File Reference
#include "ntrtlp.h"
Macros
#define LDRP_RELOCATION_FINAL 0x2
#define LDRP_RELOCATION_INCREMENT 0x1
Typedefs
typedef LDR_RELOCATE_IMAGE_RETURN_TYPE NTSTATUS
Functions
PIMAGE_BASE_RELOCATION LdrProcessRelocationBlock (IN ULONG_PTR VA, IN ULONG SizeOfBlock, IN PUSHORT NextOffset, IN LONG_PTR Diff)
PIMAGE_BASE_RELOCATION LdrProcessRelocationBlockLongLong (IN ULONG_PTR VA, IN ULONG SizeOfBlock, IN PUSHORT NextOffset, IN LONGLONG Diff)
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImage (__in PVOID NewBase, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImageWithBias (__in PVOID NewBase, __in LONGLONG AdditionalBias, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
Macro Definition Documentation
#define LDRP_RELOCATION_FINAL 0x2
Definition at line 31 of file ldrreloc.c.
Referenced by LdrProcessRelocationBlockLongLong().
#define LDRP_RELOCATION_INCREMENT 0x1
Definition at line 26 of file ldrreloc.c.
Typedef Documentation
typedef LDR_RELOCATE_IMAGE_RETURN_TYPE NTSTATUS
Definition at line 48 of file ldrreloc.c.
Function Documentation
PIMAGE_BASE_RELOCATION LdrProcessRelocationBlock (IN ULONG_PTR VA, IN ULONG SizeOfBlock, IN PUSHORT NextOffset, IN LONG_PTR Diff)
Definition at line 243 of file ldrreloc.c.
References LdrProcessRelocationBlockLongLong().
PIMAGE_BASE_RELOCATION LdrProcessRelocationBlockLongLong (IN ULONG_PTR VA, IN ULONG SizeOfBlock, IN PUSHORT NextOffset, IN LONGLONG Diff)
Definition at line 262 of file ldrreloc.c.
References EMARCH_ENC_I17_IC_INST_WORD_POS_X, EMARCH_ENC_I17_IC_INST_WORD_X, EMARCH_ENC_I17_IC_SIZE_X, EMARCH_ENC_I17_IC_VAL_POS_X, EMARCH_ENC_I17_IMM41a_INST_WORD_POS_X, EMARCH_ENC_I17_IMM41a_INST_WORD_X, EMARCH_ENC_I17_IMM41a_SIZE_X, EMARCH_ENC_I17_IMM41a_VAL_POS_X, EMARCH_ENC_I17_IMM41b_INST_WORD_POS_X, EMARCH_ENC_I17_IMM41b_INST_WORD_X, EMARCH_ENC_I17_IMM41b_SIZE_X, EMARCH_ENC_I17_IMM41b_VAL_POS_X, EMARCH_ENC_I17_IMM41c_INST_WORD_POS_X, EMARCH_ENC_I17_IMM41c_INST_WORD_X, EMARCH_ENC_I17_IMM41c_SIZE_X, EMARCH_ENC_I17_IMM41c_VAL_POS_X, EMARCH_ENC_I17_IMM5C_INST_WORD_POS_X, EMARCH_ENC_I17_IMM5C_INST_WORD_X, EMARCH_ENC_I17_IMM5C_SIZE_X, EMARCH_ENC_I17_IMM5C_VAL_POS_X, EMARCH_ENC_I17_IMM7B_INST_WORD_POS_X, EMARCH_ENC_I17_IMM7B_INST_WORD_X, EMARCH_ENC_I17_IMM7B_SIZE_X, EMARCH_ENC_I17_IMM7B_VAL_POS_X, EMARCH_ENC_I17_IMM9D_INST_WORD_POS_X, EMARCH_ENC_I17_IMM9D_INST_WORD_X, EMARCH_ENC_I17_IMM9D_SIZE_X, EMARCH_ENC_I17_IMM9D_VAL_POS_X, EMARCH_ENC_I17_SIGN_INST_WORD_POS_X, EMARCH_ENC_I17_SIGN_INST_WORD_X, EMARCH_ENC_I17_SIGN_SIZE_X, EMARCH_ENC_I17_SIGN_VAL_POS_X, EXT_IMM64, IMAGE_REL_BASED_ABSOLUTE, IMAGE_REL_BASED_DIR64, IMAGE_REL_BASED_HIGH, IMAGE_REL_BASED_HIGHADJ, IMAGE_REL_BASED_HIGHLOW, IMAGE_REL_BASED_IA64_IMM64, IMAGE_REL_BASED_LOW, IMAGE_REL_BASED_MIPS_JMPADDR, IMAGE_REL_BASED_REL32, IMAGE_REL_BASED_SECTION, INS_IMM64, LDRP_RELOCATION_FINAL, NULL, RTL_PAGED_CODE, and UNALIGNED.
Referenced by LdrProcessRelocationBlock(), and LdrRelocateImageWithBias().
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImage (__in PVOID NewBase, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
Definition at line 51 of file ldrreloc.c.
References LdrRelocateImageWithBias().
Referenced by MiReloadBootLoadedDrivers(), and MmLoadSystemImage().
LDR_RELOCATE_IMAGE_RETURN_TYPE LdrRelocateImageWithBias (__in PVOID NewBase, __in LONGLONG AdditionalBias, __in PCSTR LoaderName, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Success, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Conflict, __in LDR_RELOCATE_IMAGE_RETURN_TYPE Invalid)
Definition at line 100 of file ldrreloc.c.
References _IMAGE_FILE_HEADER::Characteristics, DbgPrint(), _IMAGE_NT_HEADERS::FileHeader, IMAGE_DIRECTORY_ENTRY_BASERELOC, IMAGE_FILE_RELOCS_STRIPPED, IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_NT_OPTIONAL_HDR64_MAGIC, LdrProcessRelocationBlockLongLong(), _IMAGE_OPTIONAL_HEADER::Magic, NULL, _IMAGE_NT_HEADERS::OptionalHeader, RTL_PAGED_CODE, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), Status, and TRUE.
Referenced by LdrRelocateImage().