Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/tunnel.c File Reference
tunnel.c File Reference
#include "FsRtlP.h"
Data Structures
struct TUNNEL_NODE
Macros
#define INLINE __inline
#define KEY_WORK_AREA ((sizeof(KEY_VALUE_FULL_INFORMATION) + sizeof(ULONG)) + 64)
#define LOOKASIDE_NODE_SIZE
#define MAX_LOOKASIDE_DEPTH 256
#define TUNNEL_AGE_VALUE_NAME L"MaximumTunnelEntryAgeInSeconds"
#define TUNNEL_FLAG_KEY_SHORT 0x2
#define TUNNEL_FLAG_NON_LOOKASIDE 0x1
#define TUNNEL_KEY_NAME L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\FileSystem"
#define TUNNEL_SIZE_VALUE_NAME L"MaximumTunnelEntries"
Typedefs
typedef struct TUNNEL_NODE * PTUNNEL_NODE
Functions
VOID FsRtlAddToTunnelCache (__in TUNNEL *Cache, __in ULONGLONG DirKey, __in UNICODE_STRING *ShortName, __in UNICODE_STRING *LongName, __in BOOLEAN KeyByShortName, __in ULONG DataLength, __in_bcount(DataLength) VOID *Data)
INLINE LONG FsRtlCompareNodeAndKey (TUNNEL_NODE *Node, ULONGLONG DirectoryKey, PUNICODE_STRING Name)
VOID FsRtlDeleteKeyFromTunnelCache (__in TUNNEL *Cache, __in ULONGLONG DirKey)
VOID FsRtlDeleteTunnelCache (__in TUNNEL *Cache)
INLINE VOID FsRtlEmptyFreePoolList (PLIST_ENTRY FreePoolList)
BOOLEAN FsRtlFindInTunnelCache (__in TUNNEL *Cache, __in ULONGLONG DirKey, __in UNICODE_STRING *Name, __out UNICODE_STRING *ShortName, __out UNICODE_STRING *LongName, __inout ULONG *DataLength, __out_bcount_part(*DataLength,*DataLength) VOID *Data)
INLINE VOID FsRtlFreeTunnelNode (PTUNNEL_NODE Node, PLIST_ENTRY FreePoolList OPTIONAL)
NTSTATUS FsRtlGetTunnelParameterValue (IN PUNICODE_STRING ValueName, IN OUT PULONG Value)
VOID FsRtlInitializeTunnelCache (__in TUNNEL *Cache)
VOID FsRtlInitializeTunnels (VOID)
VOID FsRtlPruneTunnelCache (IN PTUNNEL Cache, IN OUT PLIST_ENTRY FreePoolList)
INLINE VOID FsRtlRemoveNodeFromTunnel (IN PTUNNEL Cache, IN PTUNNEL_NODE Node, IN PLIST_ENTRY FreePoolList, IN PBOOLEAN Splay OPTIONAL)
Variables
PAGED_LOOKASIDE_LIST TunnelLookasideList
ULONG TunnelMaxAge = 15
ULONG TunnelMaxEntries = 256
Macro Definition Documentation
#define INLINE __inline
Definition at line 61 of file tunnel.c.
#define KEY_WORK_AREA ((sizeof(KEY_VALUE_FULL_INFORMATION) + sizeof(ULONG)) + 64)
Definition at line 71 of file tunnel.c.
Referenced by FsRtlGetTunnelParameterValue().
#define LOOKASIDE_NODE_SIZE
Value:
(sizeof(TUNNEL_NODE) +     \
                                  sizeof(WCHAR)*(8+1+3) +   \
                                  sizeof(WCHAR)*(16) +      \
                                  sizeof(ULONGLONG) )
Definition at line 97 of file tunnel.c.
Referenced by FsRtlAddToTunnelCache(), and FsRtlInitializeTunnels().
#define MAX_LOOKASIDE_DEPTH 256
Definition at line 95 of file tunnel.c.
Referenced by FsRtlInitializeTunnels().
#define TUNNEL_AGE_VALUE_NAME L"MaximumTunnelEntryAgeInSeconds"
Definition at line 69 of file tunnel.c.
Referenced by FsRtlInitializeTunnels().
#define TUNNEL_FLAG_KEY_SHORT 0x2
Definition at line 107 of file tunnel.c.
Referenced by FsRtlAddToTunnelCache(), and FsRtlCompareNodeAndKey().
#define TUNNEL_FLAG_NON_LOOKASIDE 0x1
Definition at line 106 of file tunnel.c.
Referenced by FsRtlAddToTunnelCache(), and FsRtlFreeTunnelNode().
#define TUNNEL_KEY_NAME L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\FileSystem"
Definition at line 68 of file tunnel.c.
Referenced by FsRtlGetTunnelParameterValue().
#define TUNNEL_SIZE_VALUE_NAME L"MaximumTunnelEntries"
Definition at line 70 of file tunnel.c.
Referenced by FsRtlInitializeTunnels().
Typedef Documentation
typedef struct TUNNEL_NODE * PTUNNEL_NODE
Function Documentation
VOID FsRtlAddToTunnelCache (__in TUNNEL * Cache, __in ULONGLONG DirKey, __in UNICODE_STRING * ShortName, __in UNICODE_STRING * LongName, __in BOOLEAN KeyByShortName, __in ULONG DataLength, __in_bcount(DataLength) VOID * Data)
Definition at line 557 of file tunnel.c.
References _UNICODE_STRING::Buffer, TUNNEL_NODE::CacheLinks, CONTAINING_RECORD, TUNNEL_NODE::CreateTime, TUNNEL_NODE::DirKey, ExAcquireFastMutex(), ExAllocateFromPagedLookasideList(), ExAllocatePoolWithTag, ExReleaseFastMutex(), FALSE, TUNNEL_NODE::Flags, FsRtlCompareNodeAndKey(), FsRtlEmptyFreePoolList(), FsRtlFreeTunnelNode(), FsRtlPruneTunnelCache(), InitializeListHead(), InsertTailList(), KeQuerySystemTime(), _UNICODE_STRING::Length, TUNNEL_NODE::ListLinks, TUNNEL_NODE::LongName, LOOKASIDE_NODE_SIZE, _UNICODE_STRING::MaximumLength, NULL, PAGED_CODE, PagedPool, _RTL_SPLAY_LINKS::Parent, POOL_COLD_ALLOCATION, RemoveEntryList(), RtlCopyMemory, RtlInitializeSplayLinks, RtlIsLeftChild, RtlIsRoot, RtlLeftChild, RtlParent, RtlRightChild, SetFlag, TUNNEL_NODE::ShortName, TRUE, TUNNEL_FLAG_KEY_SHORT, TUNNEL_FLAG_NON_LOOKASIDE, TUNNEL_NODE::TunnelData, TUNNEL_NODE::TunnelDataLength, TunnelLookasideList, and TunnelMaxEntries.
INLINE LONG FsRtlCompareNodeAndKey (TUNNEL_NODE * Node, ULONGLONG DirectoryKey, PUNICODE_STRING Name)
Definition at line 196 of file tunnel.c.
References TUNNEL_NODE::DirKey, FlagOn, TUNNEL_NODE::Flags, TUNNEL_NODE::LongName, RtlCompareUnicodeString(), TUNNEL_NODE::ShortName, TRUE, and TUNNEL_FLAG_KEY_SHORT.
Referenced by FsRtlAddToTunnelCache(), and FsRtlFindInTunnelCache().
VOID FsRtlDeleteKeyFromTunnelCache (__in TUNNEL * Cache, __in ULONGLONG DirKey)
Definition at line 1039 of file tunnel.c.
References TUNNEL_NODE::CacheLinks, CONTAINING_RECORD, TUNNEL_NODE::DirKey, ExAcquireFastMutex(), ExReleaseFastMutex(), FsRtlEmptyFreePoolList(), FsRtlRemoveNodeFromTunnel(), InitializeListHead(), NULL, PAGED_CODE, RtlLeftChild, RtlRealSuccessor(), RtlRightChild, TRUE, and TunnelMaxEntries.
VOID FsRtlDeleteTunnelCache (__in TUNNEL * Cache)
Definition at line 1168 of file tunnel.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, FsRtlFreeTunnelNode(), InitializeListHead(), NULL, PAGED_CODE, and TunnelMaxEntries.
INLINE VOID FsRtlEmptyFreePoolList (PLIST_ENTRY FreePoolList)
Definition at line 275 of file tunnel.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, FsRtlFreeTunnelNode(), IsListEmpty, NULL, and RemoveEntryList().
Referenced by FsRtlAddToTunnelCache(), FsRtlDeleteKeyFromTunnelCache(), and FsRtlFindInTunnelCache().
BOOLEAN FsRtlFindInTunnelCache (__in TUNNEL * Cache, __in ULONGLONG DirKey, __in UNICODE_STRING * Name, __out UNICODE_STRING * ShortName, __out UNICODE_STRING * LongName, __inout ULONG * DataLength, __out_bcount_part *,*DataLength VOID * Data)
Definition at line 877 of file tunnel.c.
References ASSERT, _UNICODE_STRING::Buffer, TUNNEL_NODE::CacheLinks, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, FsRtlAllocatePoolWithTag, FsRtlCompareNodeAndKey(), FsRtlEmptyFreePoolList(), FsRtlPruneTunnelCache(), InitializeListHead(), _UNICODE_STRING::Length, TUNNEL_NODE::LongName, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlCopyUnicodeString(), RtlLeftChild, RtlRightChild, TUNNEL_NODE::ShortName, Status, TRUE, TUNNEL_NODE::TunnelData, TUNNEL_NODE::TunnelDataLength, and TunnelMaxEntries.
INLINE VOID FsRtlFreeTunnelNode (PTUNNEL_NODE Node, PLIST_ENTRY FreePoolList OPTIONAL)
Definition at line 233 of file tunnel.c.
References ExFreePool(), ExFreeToPagedLookasideList(), FlagOn, TUNNEL_NODE::Flags, InsertHeadList(), TUNNEL_NODE::ListLinks, TUNNEL_FLAG_NON_LOOKASIDE, and TunnelLookasideList.
Referenced by FsRtlAddToTunnelCache(), FsRtlDeleteTunnelCache(), FsRtlEmptyFreePoolList(), and FsRtlRemoveNodeFromTunnel().
NTSTATUS FsRtlGetTunnelParameterValue (IN PUNICODE_STRING ValueName, IN OUT PULONG Value)
Definition at line 1304 of file tunnel.c.
References ASSERT, _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, ExAllocatePoolWithTag, ExFreePool(), Handle, InitializeObjectAttributes, KEY_READ, KEY_WORK_AREA, KeyName, KeyValueFullInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, PagedPool, Status, STATUS_BUFFER_OVERFLOW, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, TUNNEL_KEY_NAME, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by FsRtlInitializeTunnels().
VOID FsRtlInitializeTunnelCache (__in TUNNEL * Cache)
Definition at line 490 of file tunnel.c.
References ExInitializeFastMutex, InitializeListHead(), NULL, and PAGED_CODE.
VOID FsRtlInitializeTunnels (VOID)
Definition at line 360 of file tunnel.c.
References _UNICODE_STRING::Buffer, ExInitializePagedLookasideList(), FsRtlGetTunnelParameterValue(), _UNICODE_STRING::Length, LOOKASIDE_NODE_SIZE, MAX_LOOKASIDE_DEPTH, _UNICODE_STRING::MaximumLength, MAXUSHORT, MmIsThisAnNtAsSystem(), NULL, PAGED_CODE, TUNNEL_AGE_VALUE_NAME, TUNNEL_SIZE_VALUE_NAME, TunnelLookasideList, TunnelMaxAge, TunnelMaxEntries, and VOID.
Referenced by FsRtlInitSystem().
VOID FsRtlPruneTunnelCache (IN PTUNNEL Cache, IN OUT PLIST_ENTRY FreePoolList)
Definition at line 1223 of file tunnel.c.
References CONTAINING_RECORD, TUNNEL_NODE::CreateTime, FsRtlRemoveNodeFromTunnel(), IsListEmpty, KeQuerySystemTime(), PAGED_CODE, _LARGE_INTEGER::QuadPart, TRUE, TunnelMaxAge, and TunnelMaxEntries.
Referenced by FsRtlAddToTunnelCache(), and FsRtlFindInTunnelCache().
INLINE VOID FsRtlRemoveNodeFromTunnel (IN PTUNNEL Cache, IN PTUNNEL_NODE Node, IN PLIST_ENTRY FreePoolList, IN PBOOLEAN Splay OPTIONAL)
Definition at line 308 of file tunnel.c.
References FALSE, FsRtlFreeTunnelNode(), RemoveEntryList(), RtlDelete(), and RtlDeleteNoSplay().
Referenced by FsRtlDeleteKeyFromTunnelCache(), and FsRtlPruneTunnelCache().
Variable Documentation
PAGED_LOOKASIDE_LIST TunnelLookasideList
Definition at line 94 of file tunnel.c.
Referenced by FsRtlAddToTunnelCache(), FsRtlFreeTunnelNode(), and FsRtlInitializeTunnels().
ULONG TunnelMaxAge = 15
Definition at line 81 of file tunnel.c.
Referenced by FsRtlInitializeTunnels(), and FsRtlPruneTunnelCache().
ULONG TunnelMaxEntries = 256
Definition at line 80 of file tunnel.c.
Referenced by FsRtlAddToTunnelCache(), FsRtlDeleteKeyFromTunnelCache(), FsRtlDeleteTunnelCache(), FsRtlFindInTunnelCache(), FsRtlInitializeTunnels(), and FsRtlPruneTunnelCache().