Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/chunk.c File Reference
chunk.c File Reference
#include "wmikmp.h"
Functions
PENTRYHEADER WmipAllocEntry (PCHUNKINFO ChunkInfo)
PWCHAR WmipCountedToSz (PWCHAR Counted)
void WmipFreeEntry (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
ULONG WmipUnreferenceEntry (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
Function Documentation
PENTRYHEADER WmipAllocEntry (PCHUNKINFO ChunkInfo)
Definition at line 47 of file chunk.c.
References _ENTRYHEADER::Chunk, _CHUNKINFO::ChunkHead, CHUNKHEADER::ChunkList, CONTAINING_RECORD, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, CHUNKHEADER::EntriesInUse, _CHUNKINFO::EntriesPerChunk, _CHUNKINFO::EntrySize, ExAllocatePoolWithTag, FLAG_ENTRY_ON_FREE_LIST, _ENTRYHEADER::Flags, _LIST_ENTRY::Flink, CHUNKHEADER::FreeEntryHead, _CHUNKINFO::InitialFlags, InitializeListHead(), InsertHeadList(), InterlockedIncrement, IsListEmpty, memset(), NULL, PAGED_CODE, PagedPool, _ENTRYHEADER::RefCount, RemoveHeadList(), _CHUNKINFO::Signature, _ENTRYHEADER::Signature, WmipAssert, WmipDebugPrintEx, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
Referenced by WmipAllocDataSource(), and WmipAllocGuidEntryX().
PWCHAR WmipCountedToSz (PWCHAR Counted)
Definition at line 292 of file chunk.c.
References memcpy(), NULL, PAGED_CODE, UNICODE_NULL, and WmipAlloc.
Referenced by WmipAddDataSource(), and WmipPrepareWnodeSI().
void WmipFreeEntry (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
Definition at line 164 of file chunk.c.
References _LIST_ENTRY::Blink, _ENTRYHEADER::Chunk, _CHUNKINFO::ChunkHead, CHUNKHEADER::ChunkList, CHUNKHEADER::EntriesInUse, ExFreePoolWithTag, FLAG_ENTRY_INVALID, FLAG_ENTRY_ON_FREE_LIST, _ENTRYHEADER::Flags, CHUNKHEADER::FreeEntryHead, _ENTRYHEADER::FreeEntryList, InsertTailList(), NULL, PAGED_CODE, _ENTRYHEADER::RefCount, RemoveEntryList(), _CHUNKINFO::Signature, _ENTRYHEADER::Signature, WmipAssert, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
Referenced by WmipUnreferenceEntry().
ULONG WmipUnreferenceEntry (PCHUNKINFO ChunkInfo, PENTRYHEADER Entry)
Definition at line 225 of file chunk.c.
References _CHUNKINFO::EntryCleanup, FLAG_ENTRY_INVALID, FLAG_ENTRY_REMOVE_LIST, _ENTRYHEADER::Flags, _LIST_ENTRY::Flink, InterlockedDecrement, _ENTRYHEADER::InUseEntryList, NULL, PAGED_CODE, _ENTRYHEADER::RefCount, RemoveEntryList(), _CHUNKINFO::Signature, _ENTRYHEADER::Signature, WmipAssert, WmipEnterSMCritSection, WmipFreeEntry(), and WmipLeaveSMCritSection.