Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obwait.c File Reference
obwait.c File Reference
#include "obp.h"
Functions
NTSTATUS NtSignalAndWaitForSingleObject (__in HANDLE SignalHandle, __in HANDLE WaitHandle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSTATUS NtWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) HANDLE Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSTATUS NtWaitForMultipleObjects32 (__in ULONG Count, __in_ecount(Count) LONG Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSTATUS NtWaitForSingleObject (__in HANDLE Handle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSTATUS ObpWaitForMultipleObjects (IN ULONG Count, IN HANDLE Handles[], IN WAIT_TYPE WaitType, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL)
NTSTATUS ObWaitForSingleObject (IN HANDLE Handle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL)
Variables
POBJECT_TYPE ExEventObjectType
POBJECT_TYPE ExMutantObjectType
POBJECT_TYPE ExSemaphoreObjectType
Function Documentation
NTSTATUS NtSignalAndWaitForSingleObject (__in HANDLE SignalHandle, __in HANDLE WaitHandle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 45 of file obwait.c.
References ARGUMENT_PRESENT, _OBJECT_TYPE::DefaultObject, EVENT_INCREMENT, EVENT_MODIFY_STATE, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_HANDLE_INFORMATION::GrantedAccess, KeGetPreviousMode, KeReleaseMutant(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), MUTANT_INCREMENT, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, ProbeAndReadLargeInteger, SeComputeDeniedAccesses, SEMAPHORE_INCREMENT, SEMAPHORE_MODIFY_STATE, Status, STATUS_ABANDONED, STATUS_ACCESS_DENIED, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_MUTANT_NOT_OWNED, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SEMAPHORE_LIMIT_EXCEEDED, SYNCHRONIZE, TRUE, _OBJECT_HEADER::Type, and UserRequest.
NTSTATUS NtWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) HANDLE Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 422 of file obwait.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, MAXIMUM_WAIT_OBJECTS, ObpWaitForMultipleObjects(), PAGED_CODE, ProbeAndReadLargeInteger, ProbeForRead, RtlCopyMemory, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_3, WaitAll, and WaitAny.
NTSTATUS NtWaitForMultipleObjects32 (__in ULONG Count, __in_ecount(Count) LONG Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 519 of file obwait.c.
References ARGUMENT_PRESENT, Count, except, EXCEPTION_EXECUTE_HANDLER, Index, KeGetPreviousMode, KernelMode, LongToHandle, MAXIMUM_WAIT_OBJECTS, ObpWaitForMultipleObjects(), PAGED_CODE, ProbeAndReadLargeInteger, ProbeForRead, and STATUS_INVALID_PARAMETER_1.
NTSTATUS NtWaitForSingleObject (__in HANDLE Handle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 296 of file obwait.c.
References ARGUMENT_PRESENT, _OBJECT_TYPE::DefaultObject, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, PAGED_CODE, PERFINFO_DECLARE_OBJECT, ProbeAndReadLargeInteger, Status, STATUS_MUTANT_LIMIT_EXCEEDED, SYNCHRONIZE, _OBJECT_HEADER::Type, and UserRequest.
Referenced by FsRtlpRegisterProviderWithMUP().
NTSTATUS ObpWaitForMultipleObjects (IN ULONG Count, IN HANDLE Handles[], IN WAIT_TYPE WaitType, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL)
Definition at line 615 of file obwait.c.
References _OBJECT_HEADER::Body, Count, DecodeKernelHandle, _OBJECT_TYPE::DefaultObject, ExAllocatePoolWithTag, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExMapHandleToPointerEx(), ExUnlockHandleTableEntry(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, IsKernelHandle, KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KernelMode, KeWaitForMultipleObjects(), MAXIMUM_WAIT_OBJECTS, NonPagedPool, NtGlobalFlag, NULL, ObDereferenceObject(), OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, ObpDecodeGrantedAccess, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), PAGED_CODE, PERFINFO_DECLARE_OBJECT, PsGetCurrentProcessByThread, PsGetCurrentThread(), SeComputeDeniedAccesses, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER_MIX, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_SUCCESS, SYNCHRONIZE, _ETHREAD::Tcb, THREAD_WAIT_OBJECTS, TRUE, _OBJECT_HEADER::Type, UserRequest, and WaitAll.
Referenced by NtWaitForMultipleObjects(), and NtWaitForMultipleObjects32().
NTSTATUS ObWaitForSingleObject (IN HANDLE Handle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL)
Definition at line 939 of file obwait.c.
References _OBJECT_TYPE::DefaultObject, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, FALSE, KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, PAGED_CODE, Status, STATUS_MUTANT_LIMIT_EXCEEDED, SYNCHRONIZE, _OBJECT_HEADER::Type, and UserRequest.
Variable Documentation
POBJECT_TYPE ExEventObjectType
Definition at line 32 of file event.c.
POBJECT_TYPE ExMutantObjectType
Definition at line 26 of file mutant.c.
POBJECT_TYPE ExSemaphoreObjectType
Definition at line 32 of file semphore.c.