Windows Research Kernel v1.2: C:/Windows Research Kernel/raw/volinfo.c File Reference
volinfo.c File Reference
#include "RawProcs.h"
Functions
NTSTATUS RawQueryFsAttributeInfo (IN PVCB Vcb, IN PFILE_FS_ATTRIBUTE_INFORMATION Buffer, IN OUT PULONG Length)
NTSTATUS RawQueryFsDeviceInfo (IN PVCB Vcb, IN PFILE_FS_DEVICE_INFORMATION Buffer, IN OUT PULONG Length)
NTSTATUS RawQueryFsSizeInfo (IN PVCB Vcb, IN PFILE_FS_SIZE_INFORMATION Buffer, IN OUT PULONG Length)
NTSTATUS RawQueryFsVolumeInfo (IN PVCB Vcb, IN PFILE_FS_VOLUME_INFORMATION Buffer, IN OUT PULONG Length)
NTSTATUS RawQueryVolumeInformation (IN PVCB Vcb, IN PIRP Irp, IN PIO_STACK_LOCATION IrpSp)
Function Documentation
NTSTATUS RawQueryFsAttributeInfo (IN PVCB Vcb, IN PFILE_FS_ATTRIBUTE_INFORMATION Buffer, IN OUT PULONG Length)
Definition at line 528 of file volinfo.c.
References FIELD_OFFSET, PAGED_CODE, RtlCopyMemory, STATUS_BUFFER_OVERFLOW, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RawQueryVolumeInformation().
NTSTATUS RawQueryFsDeviceInfo (IN PVCB Vcb, IN PFILE_FS_DEVICE_INFORMATION Buffer, IN OUT PULONG Length)
Definition at line 459 of file volinfo.c.
References FILE_DEVICE_DISK, PAGED_CODE, RtlZeroMemory, STATUS_BUFFER_OVERFLOW, and STATUS_SUCCESS.
Referenced by RawQueryVolumeInformation().
NTSTATUS RawQueryFsSizeInfo (IN PVCB Vcb, IN PFILE_FS_SIZE_INFORMATION Buffer, IN OUT PULONG Length)
Definition at line 214 of file volinfo.c.
References _DISK_GEOMETRY::BytesPerSector, _DISK_GEOMETRY::Cylinders, Executive, FALSE, FILE_FLOPPY_DISKETTE, FlagOn, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_DISK_GET_DRIVE_GEOMETRY, IOCTL_DISK_GET_PARTITION_INFO, KeInitializeEvent(), KeResetEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _PARTITION_INFORMATION::PartitionLength, PIRP, _LARGE_INTEGER::QuadPart, RtlExtendedIntegerMultiply(), RtlExtendedLargeIntegerDivide(), RtlZeroMemory, _DISK_GEOMETRY::SectorsPerTrack, Status, _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, _DISK_GEOMETRY::TracksPerCylinder, TRUE, and VOID.
Referenced by RawQueryVolumeInformation().
NTSTATUS RawQueryFsVolumeInfo (IN PVCB Vcb, IN PFILE_FS_VOLUME_INFORMATION Buffer, IN OUT PULONG Length)
Definition at line 156 of file volinfo.c.
References FALSE, FIELD_OFFSET, PAGED_CODE, RtlZeroMemory, and STATUS_SUCCESS.
Referenced by RawQueryVolumeInformation().
NTSTATUS RawQueryVolumeInformation (IN PVCB Vcb, IN PIRP Irp, IN PIO_STACK_LOCATION IrpSp)
Definition at line 60 of file volinfo.c.
References FileFsAttributeInformation, FileFsDeviceInformation, FileFsSizeInformation, FileFsVolumeInformation, PAGED_CODE, RawCompleteRequest, RawQueryFsAttributeInfo(), RawQueryFsDeviceInfo(), RawQueryFsSizeInfo(), RawQueryFsVolumeInfo(), Status, and STATUS_INVALID_PARAMETER.