Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/sertlp.h File Reference
sertlp.h File Reference
#include "nt.h"
#include "zwapi.h"
#include "ntrtl.h"
Macros
#define LongAlign LongAlignPtr
#define LongAlignPtr(Ptr) ((PVOID)(((ULONG_PTR)(Ptr) + 3) & -4))
#define LongAlignSize(Size) (((ULONG)(Size) + 3) & -4)
#define RtlpAreControlBitsSet(SD, Bits)
#define RtlpClearControlBits(SD, Bits)
#define RtlpDaclAddrSecurityDescriptor(SD)
#define RtlpGroupAddrSecurityDescriptor(SD)
#define RtlpIdAssignableAsOwner(G)
#define RtlpOwnerAddrSecurityDescriptor(SD)
#define RtlpPropagateControlBits(NewSD, OldSD, Bits)
#define RtlpSaclAddrSecurityDescriptor(SD)
#define RtlpSetControlBits(SD, Bits)
Functions
VOID RtlpApplyAclToObject (IN PACL Acl, IN PGENERIC_MAPPING GenericMapping)
BOOLEAN RtlpContainsCreatorGroupSid (PKNOWN_ACE Ace)
BOOLEAN RtlpContainsCreatorOwnerSid (PKNOWN_ACE Ace)
NTSTATUS RtlpConvertToAutoInheritSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CurrentSecurityDescriptor, OUT PSECURITY_DESCRIPTOR *NewSecurityDescriptor, IN GUID *ObjectType OPTIONAL, IN BOOLEAN IsDirectoryObject, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS RtlpFreeVM (IN PVOID *Base)
NTSTATUS RtlpInheritAcl (IN PACL DirectoryAcl, IN PACL ChildAcl, IN ULONG ChildGenericControl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN BOOLEAN DefaultDescriptorForObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PACL *NewAcl, OUT PBOOLEAN NewAclExplicitlyAssigned, OUT PULONG NewGenericControl)
NTSTATUS RtlpInitializeAllowedAce (IN PACCESS_ALLOWED_ACE AllowedAce, IN USHORT AceSize, IN UCHAR InheritFlags, IN UCHAR AceFlags, IN ACCESS_MASK Mask, IN PSID AllowedSid)
NTSTATUS RtlpInitializeAuditAce (IN PACCESS_ALLOWED_ACE AuditAce, IN USHORT AceSize, IN UCHAR InheritFlags, IN UCHAR AceFlags, IN ACCESS_MASK Mask, IN PSID AuditSid)
NTSTATUS RtlpInitializeDeniedAce (IN PACCESS_DENIED_ACE DeniedAce, IN USHORT AceSize, IN UCHAR InheritFlags, IN UCHAR AceFlags, IN ACCESS_MASK Mask, IN PSID DeniedSid)
NTSTATUS RtlpNewSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CreatorDescriptor OPTIONAL, OUT PSECURITY_DESCRIPTOR *NewDescriptor, IN GUID **pObjectType OPTIONAL, IN ULONG GuidCOunt, IN BOOLEAN IsDirectoryObject, IN ULONG AutoInheritFlags, IN HANDLE Token OPTIONAL, IN PGENERIC_MAPPING GenericMapping)
VOID RtlpQuerySecurityDescriptor (__in PISECURITY_DESCRIPTOR SecurityDescriptor, __deref_out PSID *Owner, __out PULONG OwnerSize, __deref_out PSID *PrimaryGroup, __out PULONG PrimaryGroupSize, __deref_out PACL *Dacl, __out PULONG DaclSize, __deref_out PACL *Sacl, __out PULONG SaclSize)
NTSTATUS RtlpSetSecurityObject (IN PVOID Object OPTIONAL, IN SECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR ModificationDescriptor, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN ULONG AutoInheritFlags, IN ULONG PoolType, IN PGENERIC_MAPPING GenericMapping, IN HANDLE Token OPTIONAL)
FORCEINLINE PULONG RtlpSubAuthoritySid (IN PSID Sid, IN ULONG SubAuthority)
BOOLEAN RtlpValidOwnerSubjectContext (IN HANDLE Token, IN PSID Owner, IN BOOLEAN ServerObject, OUT PNTSTATUS ReturnStatus)
Macro Definition Documentation
#define LongAlign LongAlignPtr
Definition at line 40 of file sertlp.h.
#define LongAlignPtr (Ptr) ((PVOID)(((ULONG_PTR)(Ptr) + 3) & -4))
Definition at line 43 of file sertlp.h.
Referenced by NtAdjustGroupsToken(), and SeQuerySecurityDescriptorInfo().
#define LongAlignSize (Size) (((ULONG)(Size) + 3) & -4)
Definition at line 44 of file sertlp.h.
#define RtlpAreControlBitsSet (SD, Bits)
Value:
(BOOLEAN)                                                          \
            (                                                                  \
            (( SD )->Control & ( Bits )) == ( Bits )  \
            )
Definition at line 127 of file sertlp.h.
Referenced by RtlAbsoluteToSelfRelativeSD(), RtlGetDaclSecurityDescriptor(), RtlGetGroupSecurityDescriptor(), RtlGetOwnerSecurityDescriptor(), RtlGetSaclSecurityDescriptor(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), RtlSelfRelativeToAbsoluteSD(), RtlSelfRelativeToAbsoluteSD2(), RtlValidRelativeSecurityDescriptor(), and SepAccessCheck().
#define RtlpClearControlBits (SD, Bits)
Value:
(\
            ( SD )->Control &= ~( Bits )                                       \
            )
Definition at line 146 of file sertlp.h.
Referenced by RtlSelfRelativeToAbsoluteSD(), and RtlSelfRelativeToAbsoluteSD2().
#define RtlpDaclAddrSecurityDescriptor (SD)
Value:
((!((SD)->Control & SE_DACL_PRESENT)) ?                           \
             (PACL)NULL :                                                      \
               (  ((SD)->Control & SE_SELF_RELATIVE) ?                         \
                   (   (((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Dacl == 0) ? ((PACL) NULL) :            \
                           (PACL)RtlOffsetToPointer((SD), ((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Dacl) \
                   ) :                                                         \
                   (PACL)((SD)->Dacl)                                          \
               )                                                               \
           )
Definition at line 86 of file sertlp.h.
Referenced by RtlGetDaclSecurityDescriptor(), RtlLengthSecurityDescriptor(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpQuerySecurityDescriptor(), RtlpSetSecurityObject(), RtlValidSecurityDescriptor(), SeCaptureSecurityDescriptor(), SeComputeQuotaInformationSize(), SeFastTraverseCheck(), SepAccessCheck(), and SeQuerySecurityDescriptorInfo().
#define RtlpGroupAddrSecurityDescriptor (SD)
Value:
(((SD)->Control & SE_SELF_RELATIVE) ?                             \
               (   (((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Group == 0) ? ((PSID) NULL) :               \
                       (PSID)RtlOffsetToPointer((SD), ((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Group)    \
               ) :                                                             \
               (PSID)((SD)->Group)                                             \
           )
Definition at line 67 of file sertlp.h.
Referenced by RtlGetGroupSecurityDescriptor(), RtlLengthSecurityDescriptor(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpQuerySecurityDescriptor(), RtlpSetSecurityObject(), RtlValidSecurityDescriptor(), SeAccessCheckByType(), SeCaptureSecurityDescriptor(), SeComputeQuotaInformationSize(), SepAccessCheckAndAuditAlarm(), and SeQuerySecurityDescriptorInfo().
#define RtlpIdAssignableAsOwner (G)
Value:
((((G).Attributes & SE_GROUP_OWNER) != 0)  &&                         \
              (((G).Attributes & SE_GROUP_USE_FOR_DENY_ONLY) == 0) )
Definition at line 106 of file sertlp.h.
#define RtlpOwnerAddrSecurityDescriptor (SD)
Value:
(((SD)->Control & SE_SELF_RELATIVE) ?                             \
               (   (((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Owner == 0) ? ((PSID) NULL) :               \
                       (PSID)RtlOffsetToPointer((SD), ((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Owner)    \
               ) :                                                             \
               (PSID)((SD)->Owner)                                             \
           )
Definition at line 59 of file sertlp.h.
Referenced by RtlGetOwnerSecurityDescriptor(), RtlLengthSecurityDescriptor(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpQuerySecurityDescriptor(), RtlpSetSecurityObject(), RtlValidSecurityDescriptor(), SeAccessCheckByType(), SeCaptureSecurityDescriptor(), SepAccessCheckAndAuditAlarm(), SepTokenIsOwner(), and SeQuerySecurityDescriptorInfo().
#define RtlpPropagateControlBits (NewSD, OldSD, Bits)
Value:
(NewSD)->Control |=                     \
            (                                                                  \
            ( OldSD )->Control & ( Bits )             \
            )
Definition at line 115 of file sertlp.h.
Referenced by RtlpSetSecurityObject(), and SeQuerySecurityDescriptorInfo().
#define RtlpSaclAddrSecurityDescriptor (SD)
Value:
((!((SD)->Control & SE_SACL_PRESENT)) ?                           \
             (PACL)NULL :                                                      \
               (  ((SD)->Control & SE_SELF_RELATIVE) ?                         \
                   (   (((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Sacl == 0) ? ((PACL) NULL) :            \
                           (PACL)RtlOffsetToPointer((SD), ((SECURITY_DESCRIPTOR_RELATIVE *) (SD))->Sacl) \
                   ) :                                                         \
                   (PACL)((SD)->Sacl)                                          \
               )                                                               \
           )
Definition at line 75 of file sertlp.h.
Referenced by NtOpenObjectAuditAlarm(), RtlGetSaclSecurityDescriptor(), RtlLengthSecurityDescriptor(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpQuerySecurityDescriptor(), RtlpSetSecurityObject(), RtlValidSecurityDescriptor(), SeAuditingFileOrGlobalEvents(), SeAuditingHardLinkEvents(), SeAuditingHardLinkEventsWithContext(), SeCaptureSecurityDescriptor(), SeObjectReferenceAuditAlarm(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepAccessCheckAndAuditAlarm(), and SeQuerySecurityDescriptorInfo().
#define RtlpSetControlBits (SD, Bits)
Value:
(\
            ( SD )->Control |= ( Bits )                                        \
            )
Definition at line 137 of file sertlp.h.
Referenced by RtlMakeSelfRelativeSD(), RtlpConvertToAutoInheritSecurityObject(), RtlpNewSecurityObject(), RtlpSetSecurityObject(), SeAssignWorldSecurityDescriptor(), and SeQuerySecurityDescriptorInfo().
Function Documentation
VOID RtlpApplyAclToObject (IN PACL Acl, IN PGENERIC_MAPPING GenericMapping)
Definition at line 3317 of file sertl.c.
References FirstAce, IsMSAceType, NextAce, NULL, RTL_PAGED_CODE, and RtlApplyAceToObject.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
BOOLEAN RtlpContainsCreatorGroupSid (PKNOWN_ACE Ace)
BOOLEAN RtlpContainsCreatorOwnerSid (PKNOWN_ACE Ace)
NTSTATUS RtlpConvertToAutoInheritSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CurrentSecurityDescriptor, OUT PSECURITY_DESCRIPTOR * NewSecurityDescriptor, IN GUID *ObjectType OPTIONAL, IN BOOLEAN IsDirectoryObject, IN PGENERIC_MAPPING GenericMapping)
Definition at line 6077 of file sertl.c.
References _ACL::AclSize, ARGUMENT_PRESENT, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, LongAlignSize, NT_SUCCESS, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, PagedPool, RTL_PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlpAreControlBitsSet, RtlpConvertAclToAutoInherit(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, RtlValidSecurityDescriptor(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_DACL_AUTO_INHERITED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_SACL_AUTO_INHERITED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SeControlGenericToDacl, SeControlGenericToSacl, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, Status, STATUS_INVALID_SECURITY_DESCR, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
NTSTATUS RtlpFreeVM (IN PVOID * Base)
NTSTATUS RtlpInheritAcl (IN PACL DirectoryAcl, IN PACL ChildAcl, IN ULONG ChildGenericControl, IN BOOLEAN IsDirectoryObject, IN BOOLEAN AutoInherit, IN BOOLEAN DefaultDescriptorForObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN BOOLEAN IsSacl, IN GUID **pNewObjectType OPTIONAL, IN ULONG GuidCount, OUT PACL * NewAcl, OUT PBOOLEAN NewAclExplicitlyAssigned, OUT PULONG NewGenericControl)
Definition at line 4746 of file sertl.c.
References ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, PagedPool, RTL_PAGED_CODE, RtlpInheritAcl2(), Status, STATUS_BUFFER_TOO_SMALL, and STATUS_NO_MEMORY.
Referenced by RtlpConvertAclToAutoInherit(), RtlpNewSecurityObject(), and SepInheritAcl().
NTSTATUS RtlpInitializeAllowedAce (IN PACCESS_ALLOWED_ACE AllowedAce, IN USHORT AceSize, IN UCHAR InheritFlags, IN UCHAR AceFlags, IN ACCESS_MASK Mask, IN PSID AllowedSid)
NTSTATUS RtlpInitializeAuditAce (IN PACCESS_ALLOWED_ACE AuditAce, IN USHORT AceSize, IN UCHAR InheritFlags, IN UCHAR AceFlags, IN ACCESS_MASK Mask, IN PSID AuditSid)
NTSTATUS RtlpInitializeDeniedAce (IN PACCESS_DENIED_ACE DeniedAce, IN USHORT AceSize, IN UCHAR InheritFlags, IN UCHAR AceFlags, IN ACCESS_MASK Mask, IN PSID DeniedSid)
NTSTATUS RtlpNewSecurityObject (IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR CreatorDescriptor OPTIONAL, OUT PSECURITY_DESCRIPTOR * NewDescriptor, IN GUID **pObjectType OPTIONAL, IN ULONG GuidCOunt, IN BOOLEAN IsDirectoryObject, IN ULONG AutoInheritFlags, IN HANDLE Token OPTIONAL, IN PGENERIC_MAPPING GenericMapping)
Definition at line 8275 of file sertl.c.
References _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, _LUID_AND_ATTRIBUTES::Attributes, _SECURITY_DESCRIPTOR::Control, _PRIVILEGE_SET::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, KeGetPreviousMode, KernelMode, LongAlignSize, _LUID_AND_ATTRIBUTES::Luid, NT_SUCCESS, NULL, _SECURITY_DESCRIPTOR_RELATIVE::Owner, PagedPool, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, RTL_PAGED_CODE, RtlCopyMemory, RtlCopySid(), RtlCreateSecurityDescriptor(), RtlCreateSecurityDescriptorRelative(), RtlpApplyAclToObject(), RtlpAreControlBitsSet, RtlpCreateServerAcl(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpInheritAcl(), RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, RtlZeroMemory, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_DACL_AUTO_INHERITED, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_DACL_UNTRUSTED, SE_SACL_AUTO_INHERITED, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SE_SERVER_SECURITY, SeControlDaclToGeneric, SeControlGenericToDacl, SeControlGenericToSacl, SeControlSaclToGeneric, SECURITY_DESCRIPTOR_REVISION, SEF_AVOID_OWNER_CHECK, SEF_AVOID_PRIVILEGE_CHECK, SEF_DACL_AUTO_INHERIT, SEF_DEFAULT_DESCRIPTOR_FOR_OBJECT, SEF_DEFAULT_GROUP_FROM_PARENT, SEF_DEFAULT_OWNER_FROM_PARENT, SEF_SACL_AUTO_INHERIT, SeLengthSid, SeLockSubjectContext(), SepGetDefaultsSubjectContext(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), SepValidOwnerSubjectContext(), SeSecurityPrivilege, SeUnlockSubjectContext(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_OWNER, STATUS_INVALID_PRIMARY_GROUP, STATUS_NO_INHERITANCE, STATUS_NO_TOKEN, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TRUE, and UserMode.
Referenced by SeAssignSecurity(), and SeAssignSecurityEx().
VOID RtlpQuerySecurityDescriptor (__in PISECURITY_DESCRIPTOR SecurityDescriptor, __deref_out PSID * Owner, __out PULONG OwnerSize, __deref_out PSID * PrimaryGroup, __out PULONG PrimaryGroupSize, __deref_out PACL * Dacl, __out PULONG DaclSize, __deref_out PACL * Sacl, __out PULONG SaclSize)
Definition at line 385 of file rtlassig.c.
References LongAlignSize, NULL, RTL_PAGED_CODE, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, and SeLengthSid.
Referenced by RtlMakeSelfRelativeSD(), RtlSelfRelativeToAbsoluteSD(), and RtlSelfRelativeToAbsoluteSD2().
NTSTATUS RtlpSetSecurityObject (IN PVOID Object OPTIONAL, IN SECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR ModificationDescriptor, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN ULONG AutoInheritFlags, IN ULONG PoolType, IN PGENERIC_MAPPING GenericMapping, IN HANDLE Token OPTIONAL)
Definition at line 9280 of file sertl.c.
References _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, DACL_SECURITY_INFORMATION, ExAllocatePoolWithTag, ExFreePool(), FALSE, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, LongAlignSize, NT_SUCCESS, NULL, ObValidateSecurityQuota(), _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, RTL_PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlpApplyAclToObject(), RtlpAreControlBitsSet, RtlpComputeMergedAcl(), RtlpCreateServerAcl(), RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlPointerToOffset, RtlpOwnerAddrSecurityDescriptor, RtlpPropagateControlBits, RtlpSaclAddrSecurityDescriptor, RtlpSetControlBits, RtlValidSid(), RtlZeroMemory, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SACL_SECURITY_INFORMATION, _SECURITY_DESCRIPTOR_RELATIVE::Sbz1, _SECURITY_DESCRIPTOR::Sbz1, SE_DACL_AUTO_INHERIT_REQ, SE_DACL_AUTO_INHERITED, SE_DACL_DEFAULTED, SE_DACL_PRESENT, SE_DACL_PROTECTED, SE_DACL_UNTRUSTED, SE_GROUP_DEFAULTED, SE_OWNER_DEFAULTED, SE_RM_CONTROL_VALID, SE_SACL_AUTO_INHERIT_REQ, SE_SACL_AUTO_INHERITED, SE_SACL_DEFAULTED, SE_SACL_PRESENT, SE_SACL_PROTECTED, SE_SELF_RELATIVE, SE_SERVER_SECURITY, SeCaptureSubjectContext(), SeControlDaclToGeneric, SeControlGenericToDacl, SeControlGenericToSacl, SeControlSaclToGeneric, SECURITY_DESCRIPTOR_REVISION, SEF_AVOID_PRIVILEGE_CHECK, SEF_DACL_AUTO_INHERIT, SEF_SACL_AUTO_INHERIT, SeLengthSid, SepGetDefaultsSubjectContext(), SepValidOwnerSubjectContext(), SeReleaseSubjectContext(), Status, STATUS_BAD_DESCRIPTOR_FORMAT, STATUS_INVALID_OWNER, STATUS_INVALID_PRIMARY_GROUP, STATUS_NO_MEMORY, STATUS_SUCCESS, and TRUE.
Referenced by SeSetSecurityDescriptorInfo(), and SeSetSecurityDescriptorInfoEx().
FORCEINLINE PULONG RtlpSubAuthoritySid (IN PSID Sid, IN ULONG SubAuthority)
Definition at line 294 of file sertlp.h.
References _SID::SubAuthority.
Referenced by RtlpCompareKnownAces(), RtlpCompareKnownObjectAces(), RtlpConvertAclToAutoInherit(), RtlpCopyEffectiveAce(), and RtlSubAuthoritySid().
BOOLEAN RtlpValidOwnerSubjectContext (IN HANDLE Token, IN PSID Owner, IN BOOLEAN ServerObject, OUT PNTSTATUS ReturnStatus)