Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/spinlock.c File Reference
spinlock.c File Reference
#include "ki.h"
Functions
VOID KiAcquireSpinLockCheckForFreeze (IN PKSPIN_LOCK SpinLock, IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
DECLSPEC_NOINLINE ULONG64 KxWaitForSpinLockAndAcquire (__inout PKSPIN_LOCK SpinLock)
Function Documentation
VOID KiAcquireSpinLockCheckForFreeze (IN PKSPIN_LOCK SpinLock, IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 23 of file spinlock.c.
References FALSE, KiCheckForFreezeExecution(), KxTryToAcquireSpinLock(), TRUE, and UNREFERENCED_PARAMETER.
Referenced by KiProcessNMI().
DECLSPEC_NOINLINE ULONG64 KxWaitForSpinLockAndAcquire (__inout PKSPIN_LOCK SpinLock)
Definition at line 96 of file spinlock.c.
References InterlockedCompareExchange64, KeGetCurrentThread(), and KeYieldProcessor.
Referenced by KxAcquireSpinLock().