Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/wstree.c File Reference
wstree.c File Reference
#include "mi.h"
Functions
VOID MiCheckWsleHash (IN PMMWSL WorkingSetList)
VOID MiFillWsleHash (IN PMMWSL WorkingSetList)
VOID FASTCALL MiInsertWsleHash (IN WSLE_NUMBER Entry, IN PMMSUPPORT WsInfo)
WSLE_NUMBER FASTCALL MiLocateWsle (IN PVOID VirtualAddress, IN PMMWSL WorkingSetList, IN WSLE_NUMBER WsPfnIndex, IN LOGICAL Deletion)
VOID FASTCALL MiRemoveWsle (IN WSLE_NUMBER Entry, IN PMMWSL WorkingSetList)
VOID MiRemoveWsleFromFreeList (IN WSLE_NUMBER Entry, IN PMMWSLE Wsle, IN PMMWSL WorkingSetList)
VOID MiRepointWsleHashIndex (IN MMWSLE WsleEntry, IN PMMWSL WorkingSetList, IN WSLE_NUMBER NewWsIndex)
VOID MiSwapWslEntries (IN WSLE_NUMBER SwapEntry, IN WSLE_NUMBER Entry, IN PMMSUPPORT WsInfo, IN LOGICAL EntryNotInHash)
VOID FASTCALL MiTerminateWsle (IN PVOID VirtualAddress, IN PMMSUPPORT WsInfo, IN WSLE_NUMBER WsPfnIndex)
Variables
ULONG MmPagedPoolPage
ULONG MmSystemCachePage
ULONG MmSystemCodePage
ULONG MmSystemDriverPage
Function Documentation
VOID MiCheckWsleHash (IN PMMWSL WorkingSetList)
Referenced by MiFillWsleHash(), and MiInsertWsleHash().
VOID MiFillWsleHash (IN PMMWSL WorkingSetList)
Definition at line 300 of file wstree.c.
References ASSERT, Count, _MMWSLENTRY::Direct, _MMWSLE::e1, _MMPTE::Hard, _MMWSLENTRY::Hashed, Index, _MMWSLE_HASH::Index, _MMWSLE_HASH::Key, _MMWSLENTRY::LockedInMemory, _MMWSLENTRY::LockedInWs, _MMWSLE::Long, MI_GENERATE_VALID_WSLE, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_WSLE_HASH, MiCheckWsleHash(), MiGetPteAddress, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, and _MMPFN::WsIndex.
Referenced by MiGrowWsleHash().
VOID FASTCALL MiInsertWsleHash (IN WSLE_NUMBER Entry, IN PMMSUPPORT WsInfo)
Definition at line 50 of file wstree.c.
References _MMWSLENTRY::Age, ASSERT, _MMWSLENTRY::Direct, _MMWSLE::e1, _MMWSLENTRY::Hashed, _MMWSL::HashTable, _MMWSL::HashTableSize, _MMWSL::HighestPermittedHashAddress, Index, _MMWSLE_HASH::Index, _MMWSLE_HASH::Key, _MMWSLE::Long, MI_GENERATE_VALID_WSLE, MI_GET_ACCESSED_IN_PTE, MI_PASS0_TRIM_AGE, MI_WSLE_HASH, MiCheckWsleHash(), MiFreeWsle(), MiGetPteAddress, _MMWSL::NonDirectCount, NULL, PAGE_SIZE, TRUE, _MMWSLE::u1, _MMWSLENTRY::Valid, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiRemoveWorkingSetPages(), and MiUpdateWsle().
WSLE_NUMBER FASTCALL MiLocateWsle (IN PVOID VirtualAddress, IN PMMWSL WorkingSetList, IN WSLE_NUMBER WsPfnIndex, IN LOGICAL Deletion)
Definition at line 471 of file wstree.c.
References ASSERT, _MMWSLENTRY::Direct, _MMWSLE::e1, _MMWSLENTRY::Hashed, _MMWSLE_HASH::Index, KeBugCheckEx(), _MMWSLE_HASH::Key, MEMORY_MANAGEMENT, MI_GENERATE_VALID_WSLE, MI_GET_WORKING_SET_FROM_PTE, MI_MAXIMUM_PTE_WORKING_SET_INDEX, MI_WSLE_HASH, MiGetPteAddress, NULL, PAGE_ALIGN, and _MMWSLE::u1.
Referenced by MiCloneProcessAddressSpace(), MiCopyOnWrite(), MiDeleteAddressesInWorkingSet(), MiDeleteSystemPageableVm(), MiGetPageProtection(), MiGetWorkingSetInfoList(), MiLockCode(), MiRemovePageFromWorkingSet(), MiResetVirtualMemory(), MiSessionCommitPageTables(), MiSetProtectionOnSection(), MiTerminateWsle(), NtLockVirtualMemory(), and NtUnlockVirtualMemory().
VOID FASTCALL MiRemoveWsle (IN WSLE_NUMBER Entry, IN PMMWSL WorkingSetList)
Definition at line 625 of file wstree.c.
References ASSERT, _MMWSLENTRY::Direct, _MMWSLE::e1, _MMWSLENTRY::Hashed, KeBugCheckEx(), _MMWSLE_HASH::Key, _MMWSLE::Long, MEMORY_MANAGEMENT, MI_IS_SYSTEM_CACHE_ADDRESS, MI_LOG_WSLE_CHANGE, MI_WSLE_HASH, MiLowestSystemPteVirtualAddress, MmPagedPoolEnd, MmPagedPoolPage, MmPagedPoolStart, MmSpecialPoolEnd, MmSpecialPoolStart, MmSystemCachePage, MmSystemCacheWorkingSetList, MmSystemCodePage, MmSystemDriverPage, NULL, PAGE_ALIGN, _MMWSLE::u1, _MMWSLENTRY::Valid, and _MMWSLE::VirtualAddress.
Referenced by MiDecommitPages(), MiDeleteSystemPageableVm(), MiFreeWsle(), MiFreeWsleList(), MiLockCode(), MiRemovePageFromWorkingSet(), MiRemoveWorkingSetPages(), and MiTerminateWsle().
VOID MiRemoveWsleFromFreeList (IN WSLE_NUMBER Entry, IN PMMWSLE Wsle, IN PMMWSL WorkingSetList)
Definition at line 1192 of file wstree.c.
References ASSERT, MM_FREE_WSLE_SHIFT, and WSLE_NULL_INDEX.
Referenced by MiSwapWslEntries().
VOID MiRepointWsleHashIndex (IN MMWSLE WsleEntry, IN PMMWSL WorkingSetList, IN WSLE_NUMBER NewWsIndex)
Definition at line 1103 of file wstree.c.
References ASSERT, _MMWSLE_HASH::Index, MI_GENERATE_VALID_WSLE, MI_WSLE_HASH, and NULL.
Referenced by MiSwapWslEntries().
VOID MiSwapWslEntries (IN WSLE_NUMBER SwapEntry, IN WSLE_NUMBER Entry, IN PMMSUPPORT WsInfo, IN LOGICAL EntryNotInHash)
Definition at line 781 of file wstree.c.
References ASSERT, _MMWSLENTRY::Direct, _MMWSLE::e1, _MMWSL::FirstFree, _MMPTE::Hard, _MMWSL::HashTable, _MMWSL::HashTableSize, KeBugCheckEx(), _MMWSL::LastInitializedWsle, _MMPTE::Long, _MMWSLE::Long, MEMORY_MANAGEMENT, MI_GENERATE_VALID_WSLE, MI_LOG_WSLE_CHANGE, MI_PFN_ELEMENT, MI_SET_PTE_IN_WORKING_SET, MiCheckPdeForPagedPool(), MiGetPteAddress, MiRemoveWsleFromFreeList(), MiRepointWsleHashIndex(), MM_FREE_WSLE_SHIFT, NT_SUCCESS, NULL, _MMPTE_HARDWARE::PageFrameNumber, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MMPFN::WsIndex, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiAddWorkingSetPage(), MiAddWsleHash(), MiDecommitPages(), MiDeleteAddressesInWorkingSet(), MiDeleteSystemPageableVm(), MiLockCode(), MiRemovePageFromWorkingSet(), MiSessionCommitPageTables(), MiTerminateWsle(), MiUpdateWsle(), NtLockVirtualMemory(), and NtUnlockVirtualMemory().
VOID FASTCALL MiTerminateWsle (IN PVOID VirtualAddress, IN PMMSUPPORT WsInfo, IN WSLE_NUMBER WsPfnIndex)
Definition at line 1009 of file wstree.c.
References ASSERT, _MMWSLE::e1, FALSE, _MMWSL::FirstDynamic, _MMWSLENTRY::LockedInMemory, _MMWSLENTRY::LockedInWs, _MMWSLE::Long, MiLocateWsle(), MiReleaseWsle(), MiRemoveWsle(), MiSwapWslEntries(), PAGE_ALIGN, TRUE, _MMWSLE::u1, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiDeletePte(), MiDeleteValidSystemPte(), MiDeleteVirtualAddresses(), MiRemoveMappedPtes(), and MmUnmapViewInSystemCache().
Variable Documentation
ULONG MmPagedPoolPage
Definition at line 26 of file wslist.c.
Referenced by MiRemoveWsle(), and MiUpdateWsle().
ULONG MmSystemCachePage
Definition at line 25 of file wslist.c.
Referenced by MiRemoveWsle(), and MiUpdateWsle().
ULONG MmSystemCodePage
Definition at line 24 of file wslist.c.
Referenced by MiRemoveWsle(), and MiUpdateWsle().
ULONG MmSystemDriverPage
Definition at line 27 of file wslist.c.
Referenced by MiRemoveWsle(), and MiUpdateWsle().