Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/allocvm.c File Reference
allocvm.c File Reference
#include "mi.h"
Functions
LOGICAL MiCreatePageTablesForPhysicalRange (IN PEPROCESS Process, IN PVOID StartingAddress, IN PVOID EndingAddress)
VOID MiDeletePageTablesForPhysicalRange (IN PVOID StartingAddress, IN PVOID EndingAddress)
VOID MiFlushAcquire (IN PCONTROL_AREA ControlArea)
VOID MiFlushRelease (IN PCONTROL_AREA ControlArea)
NTSTATUS MiResetVirtualMemory (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN PEPROCESS Process)
PFN_NUMBER MiResidentPagesForSpan (IN PVOID StartingAddress, IN PVOID EndingAddress)
NTSTATUS MmCommitSessionMappedView (__in_bcount(ViewSize) PVOID MappedAddress, __in SIZE_T ViewSize)
NTSTATUS NtAllocateVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __in ULONG_PTR ZeroBits, __inout PSIZE_T RegionSize, __in ULONG AllocationType, __in ULONG Protect)
Variables
SIZE_T MmTotalProcessCommit
const ULONG MMVADKEY = ' daV'
Function Documentation
LOGICAL MiCreatePageTablesForPhysicalRange (IN PEPROCESS Process, IN PVOID StartingAddress, IN PVOID EndingAddress)
Definition at line 2906 of file allocvm.c.
References ASSERT, FALSE, _MMPTE::Hard, LOCK_PFN, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MiGetPteAddress, MiIsPteOnPdeBoundary, MiMakePdeExistAndMakeValid(), MiResidentPagesForSpan(), MM_NOIRQL, MM_RESAVAIL_ALLOCATE_USER_PAGE_TABLE, NULL, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u2, and UNLOCK_PFN.
Referenced by NtAllocateVirtualMemory().
VOID MiDeletePageTablesForPhysicalRange (IN PVOID StartingAddress, IN PVOID EndingAddress)
Definition at line 3025 of file allocvm.c.
References ASSERT, FALSE, _MMPTE::Hard, LOCK_PFN, _MMPTE::Long, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_GET_USED_PTES_FROM_HANDLE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MiDeletePte(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiResidentPagesForSpan(), MM_RESAVAIL_FREE_USER_PAGE_TABLE, NULL, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PsGetCurrentProcess(), _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u2, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmCleanProcessAddressSpace(), and NtFreeVirtualMemory().
VOID MiFlushAcquire (IN PCONTROL_AREA ControlArea)
Definition at line 207 of file flushsec.c.
References ASSERT, LOCK_PFN, and UNLOCK_PFN.
Referenced by NtAllocateVirtualMemory().
VOID MiFlushRelease (IN PCONTROL_AREA ControlArea)
Definition at line 242 of file flushsec.c.
References ASSERT, LOCK_PFN, and MiCheckControlArea().
Referenced by MmFlushVirtualMemory(), and NtAllocateVirtualMemory().
NTSTATUS MiResetVirtualMemory (IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN PEPROCESS Process)
Definition at line 2361 of file allocvm.c.
References ASSERT, _MMPTE_FLUSH_LIST::Count, _MMPFN::e1, _MMPFN::e2, ExPageLockHandle, FALSE, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_PFN, LOCK_WS_UNSAFE, MI_GET_ACCESSED_IN_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_PFN(), MI_IS_PTE_DIRTY, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_SET_ACCESSED_IN_PTE, MI_SET_MODIFIED, MI_SET_PTE_CLEAN, MI_VA_TO_VPN, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiFlushPteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInsertPageInList(), MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiLocateCloneAddress, MiLocateWsle(), MiMakeSystemAddressValidPfnWs(), MiPteToProto, MiReleasePageFileSpace(), MiUnlinkPageFromList(), MM_MAXIMUM_FLUSH_COUNT, MM_NOIRQL, MmLockPageableSectionByHandle(), MmStandbyPageListHead, MmUnlockPageableImageSection(), MmWorkingSetList, MmWsle, ModifiedPageList, NULL, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPTE::Soft, StandbyPageList, STATUS_SUCCESS, STATUS_USER_MAPPED_FILE, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS_UNSAFE, VadRotatePhysical, _MMPTE_HARDWARE::Valid, _MMPFN::WsIndex, and WSLE_NULL_INDEX.
Referenced by NtAllocateVirtualMemory().
PFN_NUMBER MiResidentPagesForSpan (IN PVOID StartingAddress, IN PVOID EndingAddress)
Definition at line 2825 of file allocvm.c.
References MI_COMPUTE_PAGES_SPANNED, MiGetPdeAddress, MiGetPpeAddress, and MiGetPteAddress.
Referenced by MiCreatePageTablesForPhysicalRange(), MiDeletePageTablesForPhysicalRange(), and MiPhysicalViewRemover().
NTSTATUS MmCommitSessionMappedView (__in_bcount(ViewSize) PVOID MappedAddress, __in SIZE_T ViewSize)
Definition at line 2036 of file allocvm.c.
References ASSERT, _MMVIEW::ControlArea, DRIVER_UNMAPPING_INVALID_VIEW, _MMVIEW::Entry, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, InterlockedExchangeAddSizeT, KeAcquireGuardedMutexUnsafe(), KeBugCheckEx(), KeReleaseGuardedMutexUnsafe(), LOCK_SYSTEM_VIEW_SPACE, _MMPTE::Long, MI_WRITE_INVALID_PTE, MiChargeCommitment(), MiGetPteAddress, MiReturnCommitment, MiSessionViewStart, MM_DBG_COMMIT_ALLOCVM_SEGMENT, MM_DBG_COMMIT_RETURN_ALLOCVM_SEGMENT, MM_TRACK_COMMIT, MmIsAddressValid(), MmSectionCommitMutex, MmSessionSpace, MmSessionViewSize, MmSharedCommit, NULL, _SEGMENT::NumberOfCommittedPages, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, _SEGMENT::SegmentPteTemplate, _MM_SESSION_SPACE::Session, STATUS_ALREADY_COMMITTED, STATUS_COMMITMENT_LIMIT, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_NOT_MAPPED_VIEW, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MMSESSION::SystemSpaceHashKey, _MMSESSION::SystemSpaceHashSize, _MMSESSION::SystemSpaceViewTable, TRUE, _MMPTE::u, _CONTROL_AREA::u, UNLOCK_SYSTEM_VIEW_SPACE, and X64K.
NTSTATUS NtAllocateVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __in ULONG_PTR ZeroBits, __inout PSIZE_T RegionSize, __in ULONG AllocationType, __in ULONG Protect)
Definition at line 54 of file allocvm.c.
References _4gb, ASSERT, _EPROCESS::AweInfo, _MI_PHYSICAL_VIEW::BitMap, BYTES_TO_PAGES, _EPROCESS::CommitCharge, _MMVAD_FLAGS::CommitCharge, _EPROCESS::CommitChargeLimit, _EPROCESS::CommitChargePeak, _MMVAD::ControlArea, _MMVAD::EndingVpn, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExSystemExceptionFilter(), _MMVAD_FLAGS2::ExtendableFile, FALSE, _MMVAD_FLAGS2::FileOffset, _CONTROL_AREA::FilePointer, _EPROCESS::Flags, _SECTION::InitialPageProtection, InterlockedExchangeAddSizeT, _EPROCESS::Job, _EPROCESS::JobStatus, KeAcquireGuardedMutexUnsafe(), KeFeatureBits, KeGetPreviousModeByThread, KeReleaseGuardedMutexUnsafe(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), KF_LARGE_PAGE, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _MMPTE::Long, _CONTROL_AREA::LongFlags, _SECTION::LongFlags, _MMVAD::LongFlags, MEM_COMMIT, MEM_LARGE_PAGES, MEM_PHYSICAL, MEM_RESERVE, MEM_RESET, MEM_TOP_DOWN, MEM_WRITE_WATCH, _MMVAD_FLAGS::MemCommit, MI_64K_ALIGN, MI_ALIGN_TO_SIZE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_PTE_PROTECTION_COPY_WRITE, MI_PHYSICAL_VIEW_KEY, MI_PTE_LOOKUP_NEEDED, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_WRITE_INVALID_PTE, MI_WRITEWATCH_VIEW_KEY, MiAllocateAweInfo(), MiAllocateLargePages(), MiAweViewInserter(), MiCalculatePageCommitment(), MiChargeCommitment(), MiCheckForConflictingVad, MiCheckForConflictingVadExistence(), MiCheckSecuredVad(), MiCreatePageTablesForPhysicalRange(), MiCreatePhysicalVadRoot(), MiFindEmptyAddressRange(), MiFindEmptyAddressRangeDown, MiFlushAcquire(), MiFlushRelease(), MiFreeAweInfo(), MiGetNextVad, MiGetPageProtection(), MiGetPdeAddress, MiGetPreviousVad, MiGetProtoPteAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInsertAweInfo(), MiInsertNode(), MiInsertVad(), MiInsertVadCharges(), MiIsPteOnPdeBoundary, MiMakePdeExistAndMakeValid(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MiRemoveVad(), MiRemoveVadCharges(), MiResetVirtualMemory(), MiReturnCommitment, MiReturnPageTablePageCommitment(), MiSetProtectionOnSection(), MM_DBG_COMMIT_ALLOCVM_PROCESS, MM_DBG_COMMIT_ALLOCVM_PROCESS2, MM_DBG_COMMIT_ALLOCVM_SEGMENT, MM_DBG_COMMIT_RETURN_ALLOCVM2, MM_DBG_COMMIT_RETURN_ALLOCVM_SEGMENT, MM_DECOMMIT, MM_HIGHEST_VAD_ADDRESS, MM_INVALID_PROTECTION, MM_MAX_COMMIT, MM_MAXIMUM_ZERO_BITS, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NOACCESS, MM_NOIRQL, MM_TRACK_COMMIT, MM_USER_ADDRESS_RANGE_LIMIT, MmExtendSection(), MmSectionCommitMutex, MmSharedCommit, _MMVAD_FLAGS::NoChange, NonPagedPool, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, _SEGMENT::NumberOfCommittedPages, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_EXECUTE_WRITECOPY, PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_READWRITE, PAGE_SIZE, PAGE_WRITECOMBINE, PAGE_WRITECOPY, PAGED_CODE, _EPROCESS::Pcb, _EPROCESS::PeakVirtualSize, _EPROCESS::PhysicalVadRoot, _MMVAD_FLAGS::PrivateMemory, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, _MMPTE_SOFTWARE::Protection, _MMVAD_FLAGS::Protection, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PS_PROCESS_FLAGS_VM_DELETED, PS_SET_BITS, PsChangeJobMemoryUsage(), PsChargeProcessNonPagedPoolQuota(), PsChargeProcessPageFileQuota(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, PsReportProcessMemoryLimitViolation(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPageFileQuota(), _LARGE_INTEGER::QuadPart, ROUND_TO_PAGES, RtlClearAllBits(), RtlFindMostSignificantBit(), RtlInitializeBitMap(), RtlZeroMemory, SATISFY_OVERZEALOUS_COMPILER, _CONTROL_AREA::Segment, _SECTION::Segment, _SEGMENT::SegmentPteTemplate, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_ALREADY_COMMITTED, STATUS_COMMITMENT_LIMIT, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_INVALID_PARAMETER_5, STATUS_INVALID_PARAMETER_6, STATUS_NO_MEMORY, STATUS_NOT_SUPPORTED, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPTE::u, _CONTROL_AREA::u, _SECTION::u, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MMVAD::u2, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD::VadFlags2, VadLargePages, VadLargePageSection, _EPROCESS::VadRoot, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, VadWriteWatch, _EPROCESS::VirtualSize, _EPROCESS::VmTopDown, and X64K.
Variable Documentation
SIZE_T MmTotalProcessCommit
Definition at line 50 of file allocvm.c.
const ULONG MMVADKEY = ' daV'
Definition at line 22 of file allocvm.c.
Referenced by MiMapViewOfDataSection(), and MiMapViewOfImageSection().