Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/i386/procx86.c File Reference
procx86.c File Reference
#include "mi.h"
Functions
VOID MiUpdateSystemPdes (IN PEPROCESS Process)
BOOLEAN MmCreateProcessAddressSpace (IN ULONG MinimumWorkingSetSize, IN PEPROCESS NewProcess, OUT PULONG_PTR DirectoryTableBase)
Variables
PMMPTE MiLargePageHyperPte
SIZE_T MmProcessCommit
Function Documentation
VOID MiUpdateSystemPdes (IN PEPROCESS Process)
Definition at line 368 of file procx86.c.
References ASSERT, _KPROCESS::DirectoryTableBase, DISPATCH_LEVEL, _MMPTE::Hard, KeGetCurrentIrql(), _MMPTE::Long, MI_FLUSH_CURRENT_TB_SINGLE, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiGetPdeOffset, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpaceAtDpc(), MiPteRangeIndex, MiPteRanges, MiUnmapPageInHyperSpaceFromDpc, NULL, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, PsGetCurrentProcess(), PsInitialSystemProcess, RtlCopyMemory, _MMPTE::u, and ValidKernelPte.
Referenced by MmInitializeProcessAddressSpace(), and MmInSwapProcess().
BOOLEAN MmCreateProcessAddressSpace (IN ULONG MinimumWorkingSetSize, IN PEPROCESS NewProcess, OUT PULONG_PTR DirectoryTableBase)
Definition at line 29 of file procx86.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, FALSE, _MMPTE::Hard, HYPER_SPACE, INITIALIZE_DIRECTORY_TABLE_BASE, InsertTailList(), InterlockedExchangeAddSizeT, KeInitializeSpinLock(), LOCK_EXPANSION, LOCK_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PAGE_COLOR_PTE_PROCESS, MI_PAGE_COLOR_VA_PROCESS, MI_PFN_ELEMENT, MI_SET_GLOBAL_STATE, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiCached, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPdeOffset, MiGetPteOffset, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiRemoveZeroPageMayReleaseLocks(), MiReserveSystemPtes(), MiReturnCommitment, MiSessionAddProcess(), MiUnmapPageInHyperSpace, MiZeroMemoryPte, MM_DBG_COMMIT_PROCESS_CREATE, MM_HIGH_LIMIT, MM_PROCESS_COMMIT_CHARGE, MM_READWRITE, MM_RESAVAIL_ALLOCATE_CREATE_PROCESS, MM_TRACK_COMMIT, MmAvailablePages, MmHyperSpaceEnd, MmProcessColorSeed, MmProcessCommit, MmProcessList, MmSystemRangeStart, MmWorkingSetList, _EPROCESS::NextPageColor, NULL, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PDE_BASE, PS_PROCESS_FLAGS_ADDRESS_SPACE1, PS_SET_BITS, PsGetCurrentProcess(), PTE_BASE, _MMPFN::PteAddress, RtlCopyMemory, RtlRandom(), SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, and ValidPdePde.
Referenced by MmInitializeHandBuiltProcess(), and PspCreateProcess().
Variable Documentation
PMMPTE MiLargePageHyperPte
Definition at line 364 of file procx86.c.
Referenced by MiInitializeLargePageSupport().
SIZE_T MmProcessCommit
Definition at line 77 of file procsup.c.
Referenced by MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmDeleteKernelStack(), and MmDeleteProcessAddressSpace().