Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmmapvw.c File Reference
cmmapvw.c File Reference
#include "cmp.h"
Functions
BOOLEAN CmIsFileLoadedAsHive (PFILE_OBJECT FileObject)
NTSTATUS CmpAcquireFileObjectForFile (IN PCMHIVE CmHive, IN HANDLE FileHandle, OUT PFILE_OBJECT *FileObject)
PCM_VIEW_OF_FILE CmpAllocateCmView (IN PCMHIVE CmHive)
VOID CmpDereferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
VOID CmpDereferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
VOID CmpDestroyHiveViewList (IN PCMHIVE CmHive)
VOID CmpDropFileObjectForHive (IN PCMHIVE CmHive)
VOID CmpFixHiveUsageCount (IN PCMHIVE CmHive)
VOID CmpFreeCmView (PCM_VIEW_OF_FILE CmView)
VOID CmpInitHiveViewList (IN PCMHIVE CmHive)
NTSTATUS CmpMapCmView (IN PCMHIVE CmHive, IN ULONG FileOffset, OUT PCM_VIEW_OF_FILE *CmView, IN BOOLEAN MapInited)
NTSTATUS CmpMapThisBin (PCMHIVE CmHive, HCELL_INDEX Cell, BOOLEAN Touch)
NTSTATUS CmpPinCmView (IN PCMHIVE CmHive, PCM_VIEW_OF_FILE CmView)
VOID CmpPrefetchHiveFile (IN PFILE_OBJECT FileObject, IN ULONG Length)
VOID CmpReferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
VOID CmpReferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
NTSTATUS CmPrefetchHivePages (__in PUNICODE_STRING FullHivePath, __inout PREAD_LIST ReadList)
VOID CmpTouchView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN ULONG Cell)
VOID CmpUnmapCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN MapIsValid, IN BOOLEAN MoveToEnd)
VOID CmpUnmapCmViewSurroundingOffset (IN PCMHIVE CmHive, IN ULONG FileOffset)
VOID CmpUnmapUnusedViews (IN PCMHIVE CmHive)
VOID CmpUnPinCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN SetClean, IN BOOLEAN MapValid)
Variables
ULONG CmMaxViewsPerHive = MAX_VIEWS_PER_HIVE
PUCHAR CmpStashBuffer
ULONG CmpStashBufferSize
BOOLEAN CmpTrackHiveClose = FALSE
Function Documentation
BOOLEAN CmIsFileLoadedAsHive (PFILE_OBJECT FileObject)
Definition at line 1875 of file cmmapvw.c.
References CmpHiveListHead, CmpLockHiveListShared, CmpUnlockHiveList, CONTAINING_RECORD, FALSE, _CMHIVE::FileObject, _LIST_ENTRY::Flink, and TRUE.
NTSTATUS CmpAcquireFileObjectForFile (IN PCMHIVE CmHive, IN HANDLE FileHandle, OUT PFILE_OBJECT * FileObject)
Definition at line 957 of file cmmapvw.c.
References ASSERT, _UNICODE_STRING::Buffer, CcSetPrivateWriteFile(), CM_PAGED_CODE, CmKdPrintEx, CmpDropFileObjectForHive(), CmpStashBuffer, CmpStashBufferSize, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, DPFLTR_TRACE_LEVEL, ExAllocatePoolWithTag, FILE_READ_DATA, FILE_WRITE_DATA, IoFileObjectType, KernelMode, _UNICODE_STRING::Length, LOCK_STASH_BUFFER, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObQueryNameString(), ObReferenceObjectByHandle, PagedPool, PROTECTED_POOL, RtlCopyMemory, Status, STATUS_RETRY, and UNLOCK_STASH_BUFFER.
Referenced by CmpSetupPrivateWrite(), and HvMapHive().
PCM_VIEW_OF_FILE CmpAllocateCmView (IN PCMHIVE CmHive)
Definition at line 683 of file cmmapvw.c.
References _CM_VIEW_OF_FILE::Bcb, CM_PAGED_CODE, ExAllocatePoolWithTag, _CM_VIEW_OF_FILE::FileOffset, InitializeListHead(), InsertTailList(), _CM_VIEW_OF_FILE::LRUViewList, NULL, PagedPool, _CM_VIEW_OF_FILE::PinViewList, PROTECTED_POOL, _CM_VIEW_OF_FILE::Size, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpMapCmView().
VOID CmpDereferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1938 of file cmmapvw.c.
References ASSERT_VIEW_LOCK_OWNED, and CM_PAGED_CODE.
Referenced by CmpDereferenceHiveViewWithLock(), and HvWriteHive().
VOID CmpDereferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1998 of file cmmapvw.c.
References CM_PAGED_CODE, CmLockHiveViews, CmpDereferenceHiveView(), and CmUnlockHiveViews.
Referenced by HvpScanForFreeCellInViewWindow(), and HvWriteHive().
VOID CmpDestroyHiveViewList (IN PCMHIVE CmHive)
Definition at line 772 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_PINNED, CcFlushCache(), CcPurgeCacheSection(), CM_PAGED_CODE, CmpUnmapCmView(), CONTAINING_RECORD, ExFreePoolWithTag, FALSE, InitializeListHead(), InsertTailList(), IsListEmpty, _CM_VIEW_OF_FILE::LRUViewList, NULL, _CM_VIEW_OF_FILE::PinViewList, PROTECTED_POOL, RemoveEntryList(), RemoveHeadList(), TRUE, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpInitializeHive(), CmpOverwriteHive(), CmShutdownSystem(), CmUnloadKey(), and HvpRecoverWholeHive().
VOID CmpDropFileObjectForHive (IN PCMHIVE CmHive)
Definition at line 899 of file cmmapvw.c.
References ASSERT, CM_PAGED_CODE, ExFreePoolWithTag, NULL, ObDereferenceObject(), and PROTECTED_POOL.
Referenced by CmLoadKey(), CmpAcquireFileObjectForFile(), CmpDestroyTemporaryHive(), CmpInitializeHive(), CmShutdownSystem(), and CmUnloadKey().
VOID CmpFixHiveUsageCount (IN PCMHIVE CmHive)
Definition at line 1510 of file cmmapvw.c.
References ASSERT, CM_PAGED_CODE, CmKdPrintEx, CmMaxViewsPerHive, CmpFreeCmView(), CmpUnmapCmView(), CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _LIST_ENTRY::Flink, InitializeListHead(), _CM_VIEW_OF_FILE::LRUViewList, _CM_VIEW_OF_FILE::PinViewList, RemoveEntryList(), TRUE, and _CM_VIEW_OF_FILE::UseCount.
Referenced by CmFlushKey(), CmpDoFlushAll(), and CmpDoFlushNextHive().
VOID CmpFreeCmView (PCM_VIEW_OF_FILE CmView)
Definition at line 1471 of file cmmapvw.c.
References ASSERT, _CM_VIEW_OF_FILE::Bcb, CM_BUGCHECK, CM_PAGED_CODE, CMVIEW_ERROR, ExFreePoolWithTag, _CM_VIEW_OF_FILE::FileOffset, IsListEmpty, _CM_VIEW_OF_FILE::LRUViewList, NULL, _CM_VIEW_OF_FILE::PinViewList, PROTECTED_POOL, REGISTRY_ERROR, _CM_VIEW_OF_FILE::Size, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpFixHiveUsageCount(), CmpUnPinCmView(), and HvRefreshHive().
VOID CmpInitHiveViewList (IN PCMHIVE CmHive)
Definition at line 741 of file cmmapvw.c.
References CM_PAGED_CODE, and InitializeListHead().
Referenced by CmGetSystemControlValues(), and CmpInitializeHive().
NTSTATUS CmpMapCmView (IN PCMHIVE CmHive, IN ULONG FileOffset, OUT PCM_VIEW_OF_FILE * CmView, IN BOOLEAN MapInited)
Definition at line 294 of file cmmapvw.c.
References ASSERT, ASSERT_BIN_INVALID, ASSERT_BIN_INVIEW, ASSERT_VIEW_LOCK_OWNED, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _UNICODE_STRING::Buffer, CcMapData(), CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_BIN_MAP, CmMaxViewsPerHive, CmpAllocateCmView(), CmpUnmapCmView(), CmpUnmapUnusedViews(), _HMAP_ENTRY::CmView, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HBIN_BASE, HBIN_FLAGS, HBLOCK_SIZE, _LARGE_INTEGER::HighPart, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HvpGetCellMap(), IsListEmpty, _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, MAP_NO_READ, MAP_WAIT, NT_SUCCESS, NULL, RtlInitUnicodeString(), _HBIN::Size, Stable, Status, STATUS_CANT_WAIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and VALIDATE_CELL_MAP.
Referenced by CmpMapThisBin(), HvMarkDirty(), HvpGetCellMapped(), HvpMapFileImageAndBuildMap(), HvpRecoverWholeHive(), and HvRefreshHive().
NTSTATUS CmpMapThisBin (PCMHIVE CmHive, HCELL_INDEX Cell, BOOLEAN Touch)
Definition at line 1074 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, CM_PAGED_CODE, CmpMapCmView(), CmpTouchView(), HvGetCellType, NT_SUCCESS, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by HvCheckHive(), HvCloneHive(), HvpAddBin(), HvpRecoverData(), HvpScanForFreeCellInViewWindow(), and HvWriteHive().
NTSTATUS CmpPinCmView (IN PCMHIVE CmHive, PCM_VIEW_OF_FILE CmView)
Definition at line 1129 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, ASSERT_VIEW_MAPPED, _CM_VIEW_OF_FILE::Bcb, _UNICODE_STRING::Buffer, CcPinMappedData(), CM_PAGED_CODE, CmKdPrintEx, CML_BIN_MAP, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CM_VIEW_OF_FILE::FileOffset, _LARGE_INTEGER::HighPart, InitializeListHead(), InsertTailList(), _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, _CM_VIEW_OF_FILE::LRUViewList, NT_SUCCESS, _CM_VIEW_OF_FILE::PinViewList, RemoveEntryList(), RtlInitUnicodeString(), _CM_VIEW_OF_FILE::Size, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by HvMarkCellDirty(), HvMarkDirty(), HvpRecoverData(), and HvpRecoverWholeHive().
VOID CmpPrefetchHiveFile (IN PFILE_OBJECT FileObject, IN ULONG Length)
Definition at line 1620 of file cmmapvw.c.
References _FILE_SEGMENT_ELEMENT::Alignment, ASSERT, CM_PAGED_CODE, ExAllocatePoolWithTag, ExFreePool(), FALSE, _READ_LIST::FileObject, _READ_LIST::IsImage, _READ_LIST::List, MmPrefetchPages(), NonPagedPool, NULL, _READ_LIST::NumberOfEntries, PAGE_SIZE, and ROUND_UP.
Referenced by HvMapHive().
VOID CmpReferenceHiveView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1905 of file cmmapvw.c.
References ASSERT_VIEW_LOCK_OWNED, and CM_PAGED_CODE.
Referenced by CmpReferenceHiveViewWithLock(), HvpScanForFreeCellInViewWindow(), and HvWriteHive().
VOID CmpReferenceHiveViewWithLock (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView)
Definition at line 1968 of file cmmapvw.c.
References CM_PAGED_CODE, CmLockHiveViews, CmpReferenceHiveView(), and CmUnlockHiveViews.
NTSTATUS CmPrefetchHivePages (__in PUNICODE_STRING FullHivePath, __inout PREAD_LIST ReadList)
Definition at line 1780 of file cmmapvw.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmpHiveListHead, CmpLockHiveListShared, CmpLockRegistry(), CmpUnlockHiveList, CmpUnlockRegistry(), CONTAINING_RECORD, FALSE, _CMHIVE::FileFullPath, _CMHIVE::FileObject, _LIST_ENTRY::Flink, MmDisableModifiedWriteOfSection(), MmPrefetchPages(), NULL, RtlCompareUnicodeString(), _FILE_OBJECT::SectionObjectPointer, Status, STATUS_INVALID_PARAMETER, and TRUE.
VOID CmpTouchView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN ULONG Cell)
Definition at line 212 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_BIN_MAP, DPFLTR_CONFIG_ID, FALSE, InsertHeadList(), IsListEmpty, _UNICODE_STRING::Length, RemoveEntryList(), RtlInitUnicodeString(), and UNREFERENCED_PARAMETER.
Referenced by CmpMapThisBin(), HvpGetCellMapped(), HvpMapFileImageAndBuildMap(), and HvRefreshHive().
VOID CmpUnmapCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN MapIsValid, IN BOOLEAN MoveToEnd)
Definition at line 91 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, _HMAP_ENTRY::BinAddress, CcUnpinData(), CM_PAGED_CODE, _HMAP_ENTRY::CmView, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvpGetCellMap(), InsertTailList(), NULL, RemoveEntryList(), Stable, TRUE, and VALIDATE_CELL_MAP.
Referenced by CmpDestroyHiveViewList(), CmpFixHiveUsageCount(), CmpMapCmView(), CmpUnmapCmViewSurroundingOffset(), CmpUnmapUnusedViews(), CmpUnPinCmView(), HvpDropPagedBins(), and HvRefreshHive().
VOID CmpUnmapCmViewSurroundingOffset (IN PCMHIVE CmHive, IN ULONG FileOffset)
Definition at line 616 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_LOCK_OWNED, ASSERT_VIEW_MAPPED, CM_PAGED_CODE, CmpUnmapCmView(), CONTAINING_RECORD, FALSE, _CM_VIEW_OF_FILE::FileOffset, _LIST_ENTRY::Flink, _CM_VIEW_OF_FILE::LRUViewList, _CM_VIEW_OF_FILE::Size, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpDoFileSetSize(), and HvRefreshHive().
VOID CmpUnmapUnusedViews (IN PCMHIVE CmHive)
Definition at line 1689 of file cmmapvw.c.
References ASSERT, _CM_VIEW_OF_FILE::Bcb, CM_PAGED_CODE, CmLockHiveViews, CmpHiveListHead, CmpLockHiveListShared, CmpUnlockHiveList, CmpUnmapCmView(), CmUnlockHiveViews, CONTAINING_RECORD, FALSE, _CM_VIEW_OF_FILE::FileOffset, _LIST_ENTRY::Flink, _CM_VIEW_OF_FILE::LRUViewList, _CMHIVE::LRUViewListHead, _CMHIVE::MappedViews, NOTHING, _CM_VIEW_OF_FILE::Size, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpMapCmView().
VOID CmpUnPinCmView (IN PCMHIVE CmHive, IN PCM_VIEW_OF_FILE CmView, IN BOOLEAN SetClean, IN BOOLEAN MapValid)
Definition at line 1251 of file cmmapvw.c.
References ASSERT, ASSERT_VIEW_PINNED, _LIST_ENTRY::Blink, CcFlushCache(), CcMapData(), CcPurgeCacheSection(), CcSetDirtyPinnedData(), CcUnpinData(), CM_PAGED_CODE, CmKdPrintEx, CmLockHiveViews, CmMaxViewsPerHive, CmpFreeCmView(), CmpUnmapCmView(), CmUnlockHiveViews, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FileOffset, _LARGE_INTEGER::HighPart, InitializeListHead(), InsertHeadList(), InsertTailList(), _LARGE_INTEGER::LowPart, MAP_NO_READ, MAP_WAIT, NT_SUCCESS, NULL, RemoveEntryList(), Status, STATUS_CANT_WAIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by HvpFlushMappedData().
Variable Documentation
ULONG CmMaxViewsPerHive = MAX_VIEWS_PER_HIVE
Definition at line 88 of file cmmapvw.c.
Referenced by CmpFixHiveUsageCount(), CmpMapCmView(), and CmpUnPinCmView().
PUCHAR CmpStashBuffer
Definition at line 64 of file cmdat2.c.
Referenced by CmpAcquireFileObjectForFile().
ULONG CmpStashBufferSize
Definition at line 65 of file cmdat2.c.
Referenced by CmpAcquireFileObjectForFile().
BOOLEAN CmpTrackHiveClose = FALSE
Definition at line 56 of file cmmapvw.c.
Referenced by CmpCmdHiveClose(), CmpInitHiveFromFile(), and CmpLoadHiveThread().