Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/balmgr.c File Reference
balmgr.c File Reference
#include "ki.h"
Macros
#define LARGE_SYSTEM_STACK_PROTECT_TIME (SMALL_SYSTEM_STACK_PROTECT_TIME * 5)
#define MAXIMUM_THREAD_STACKS 5
#define PERIODIC_INTERVAL (1 * 1000 * 1000 * 10)
#define READY_WITHOUT_RUNNING (4 * 75)
#define SMALL_SYSTEM_STACK_PROTECT_TIME (3 * 75)
#define STACK_SCAN_PERIOD 4
#define THREAD_BOOST_BIAS 1
#define THREAD_BOOST_PRIORITY (LOW_REALTIME_PRIORITY - THREAD_BOOST_BIAS)
#define THREAD_READY_COUNT 10
#define THREAD_SCAN_COUNT 16
#define THREAD_SCAN_PRIORITY (THREAD_BOOST_PRIORITY - 1)
Typedefs
typedef enum _BALANCE_OBJECT BALANCE_OBJECT
Enumerations
enum _BALANCE_OBJECT {
TimerExpiration, ThreadSetManagerEvent, ShutdownEvent, MaximumBalanceObject,
TimerExpiration, WorkingSetManagerEvent, MaximumObject
}
Functions
VOID KeBalanceSetManager (IN PVOID Context)
VOID KeSwapProcessOrStack (IN PVOID Context)
VOID KiAdjustIrpCredits (VOID)
VOID KiInSwapKernelStacks (IN PSINGLE_LIST_ENTRY SwapEntry)
VOID KiInSwapProcesses (IN PSINGLE_LIST_ENTRY SwapEntry)
VOID KiOutSwapKernelStacks (VOID)
VOID KiOutSwapProcesses (IN PSINGLE_LIST_ENTRY SwapEntry)
VOID KiScanReadyQueues (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Variables
ULONG KiLastProcessor = 0
ULONG KiReadyScanLast = 0
LONG KiStackOutSwapRequest = FALSE
ULONG KiStackProtectTime
Macro Definition Documentation
#define LARGE_SYSTEM_STACK_PROTECT_TIME (SMALL_SYSTEM_STACK_PROTECT_TIME * 5)
Definition at line 78 of file balmgr.c.
Referenced by KeBalanceSetManager().
#define MAXIMUM_THREAD_STACKS 5
Definition at line 57 of file balmgr.c.
Referenced by KiOutSwapKernelStacks().
#define PERIODIC_INTERVAL (1 * 1000 * 1000 * 10)
Definition at line 63 of file balmgr.c.
Referenced by KeBalanceSetManager().
#define READY_WITHOUT_RUNNING (4 * 75)
Definition at line 70 of file balmgr.c.
Referenced by KiScanReadyQueues().
#define SMALL_SYSTEM_STACK_PROTECT_TIME (3 * 75)
Definition at line 77 of file balmgr.c.
Referenced by KeBalanceSetManager().
#define STACK_SCAN_PERIOD 4
Definition at line 79 of file balmgr.c.
Referenced by KeBalanceSetManager().
#define THREAD_BOOST_BIAS 1
Definition at line 86 of file balmgr.c.
#define THREAD_BOOST_PRIORITY (LOW_REALTIME_PRIORITY - THREAD_BOOST_BIAS)
Definition at line 87 of file balmgr.c.
Referenced by KiScanReadyQueues().
#define THREAD_READY_COUNT 10
Definition at line 89 of file balmgr.c.
Referenced by KiScanReadyQueues().
#define THREAD_SCAN_COUNT 16
Definition at line 90 of file balmgr.c.
Referenced by KiScanReadyQueues().
#define THREAD_SCAN_PRIORITY (THREAD_BOOST_PRIORITY - 1)
Definition at line 88 of file balmgr.c.
Referenced by KiScanReadyQueues().
Typedef Documentation
typedef enum _BALANCE_OBJECT BALANCE_OBJECT
Enumeration Type Documentation
enum _BALANCE_OBJECT
Enumerator
TimerExpiration
ThreadSetManagerEvent
ShutdownEvent
MaximumBalanceObject
TimerExpiration
WorkingSetManagerEvent
MaximumObject
Definition at line 46 of file balmgr.c.
Function Documentation
VOID KeBalanceSetManager (IN PVOID Context)
Definition at line 143 of file balmgr.c.
References ExAdjustLookasideDepth(), Executive, FALSE, InterlockedCompareExchange(), KdPrint, KeGetCurrentThread(), KeInitializeDpc(), KeInitializeTimerEx(), KernelMode, KeSetPriorityThread(), KeSetTimerEx(), KeWaitForMultipleObjects(), KiAdjustIrpCredits(), KiLockDispatcherDatabase, KiReadyScanLast, KiScanReadyQueues(), KiSetInternalEvent(), KiStackOutSwapRequest, KiStackProtectTime, KiSwapEvent, KiSwappingThread, LARGE_SYSTEM_STACK_PROTECT_TIME, LOW_REALTIME_PRIORITY, MaximumObject, MmQuerySystemSize(), MmSmallSystem, MmWorkingSetManager(), MmWorkingSetManagerEvent, NULL, PERIODIC_INTERVAL, _LARGE_INTEGER::QuadPart, SMALL_SYSTEM_STACK_PROTECT_TIME, STACK_SCAN_PERIOD, Status, SynchronizationTimer, TimerExpiration, TRUE, UNREFERENCED_PARAMETER, WaitAny, _KTHREAD::WaitIrql, _KTHREAD::WaitNext, and WorkingSetManagerEvent.
Referenced by KeWaitForSingleObject(), and MmInitSystem().
VOID KeSwapProcessOrStack (IN PVOID Context)
Definition at line 329 of file balmgr.c.
References Executive, FALSE, InterlockedCompareExchange(), InterlockedFlushSingleList(), KeGetCurrentThread(), KernelMode, KeSetPriorityThread(), KeWaitForSingleObject(), KiInSwapKernelStacks(), KiInSwapProcesses(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), KiProcessInSwapListHead, KiProcessOutSwapListHead, KiStackInSwapListHead, KiStackOutSwapRequest, KiSwapEvent, KiSwappingThread, LOW_REALTIME_PRIORITY, NULL, TRUE, and UNREFERENCED_PARAMETER.
Referenced by MmInitSystem().
VOID KiAdjustIrpCredits (VOID)
Definition at line 440 of file balmgr.c.
References Index, InterlockedExchangeAdd(), KeNumberProcessors, KiProcessorBlock, and _KPRCB::LookasideIrpFloat.
Referenced by KeBalanceSetManager().
VOID KiInSwapKernelStacks (IN PSINGLE_LIST_ENTRY SwapEntry)
Definition at line 528 of file balmgr.c.
References ASSERT, CONTAINING_RECORD, FALSE, _KTHREAD::KernelStackResident, KiInsertDeferredReadyList(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), MmInPageKernelStack(), NULL, and TRUE.
Referenced by KeSwapProcessOrStack().
VOID KiInSwapProcesses (IN PSINGLE_LIST_ENTRY SwapEntry)
Definition at line 576 of file balmgr.c.
References CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, KiLockDispatcherDatabase, KiReadyThread(), KiUnlockDispatcherDatabase(), MmInSwapProcess(), NULL, ProcessInMemory, ProcessInSwap, _KTHREAD::ProcessReadyQueue, _KPROCESS::ReadyListHead, RemoveEntryList(), and _KPROCESS::State.
Referenced by KeSwapProcessOrStack().
VOID KiOutSwapKernelStacks (VOID)
Definition at line 631 of file balmgr.c.
References _KTHREAD::ApcState, ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KEVENT::Header, InterlockedPushEntrySingleList(), KeNumberProcessors, _KTHREAD::KernelStackResident, KeWaitForContextSwap(), KiIsThreadNumericStateSaved, KiLastProcessor, KiLockDispatcherDatabase, KiProcessorBlock, KiProcessOutSwapListHead, KiQueryLowTickCount, KiStackProtectTime, KiSwapEvent, KiUnlockDispatcherDatabase(), LOW_REALTIME_PRIORITY, MAXIMUM_THREAD_STACKS, MmOutPageKernelStack(), NULL, _KTHREAD::Priority, _KAPC_STATE::Process, ProcessInMemory, ProcessOutTransition, RemoveEntryList(), _DISPATCHER_HEADER::SignalState, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, UserMode, _KTHREAD::WaitListEntry, _KPRCB::WaitListHead, and _KTHREAD::WaitMode.
Referenced by KeSwapProcessOrStack().
VOID KiOutSwapProcesses (IN PSINGLE_LIST_ENTRY SwapEntry)
Definition at line 770 of file balmgr.c.
References CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KEVENT::Header, InterlockedPushEntrySingleList(), KiLockDispatcherDatabase, KiProcessInSwapListHead, KiReadyThread(), KiSwapEvent, KiUnlockDispatcherDatabase(), MmOutSwapProcess(), NULL, ProcessInMemory, ProcessInTransition, ProcessOutOfMemory, ProcessOutSwap, _KTHREAD::ProcessReadyQueue, _KPROCESS::ReadyListHead, RemoveEntryList(), _DISPATCHER_HEADER::SignalState, _KPROCESS::State, and _KPROCESS::SwapListEntry.
Referenced by KeSwapProcessOrStack().
VOID KiScanReadyQueues (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 860 of file balmgr.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, Count, _KPRCB::DispatcherReadyListHead, except, FALSE, _LIST_ENTRY::Flink, Index, IsListEmpty, KeNumberProcessors, KiAcquirePrcbLock(), KiInsertDeferredReadyList(), KiLockDispatcherDatabase, KiProcessorBlock, KiQueryLowTickCount, KiReleasePrcbLock(), KiUnlockDispatcherDatabase(), LOCK_OWNERSHIP_QUANTUM, _KTHREAD::Priority, PRIORITY_MASK, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, _KPRCB::QueueIndex, READY_WITHOUT_RUNNING, _KPRCB::ReadySummary, RemoveEntryList(), THREAD_BOOST_PRIORITY, THREAD_READY_COUNT, THREAD_SCAN_COUNT, THREAD_SCAN_PRIORITY, UNREFERENCED_PARAMETER, and _KTHREAD::WaitTime.
Referenced by KeBalanceSetManager().
Variable Documentation
ULONG KiLastProcessor = 0
Definition at line 96 of file balmgr.c.
Referenced by KiOutSwapKernelStacks().
ULONG KiReadyScanLast = 0
Definition at line 97 of file balmgr.c.
Referenced by KeBalanceSetManager().
LONG KiStackOutSwapRequest = FALSE
Definition at line 140 of file balmgr.c.
Referenced by KeBalanceSetManager(), and KeSwapProcessOrStack().
ULONG KiStackProtectTime
Definition at line 80 of file balmgr.c.
Referenced by KeBalanceSetManager(), and KiOutSwapKernelStacks().