Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/win32.c File Reference
win32.c File Reference
#include "exp.h"
Typedefs
typedef NTSTATUS(* PKWIN32_CALLOUT) (IN PKWIN32_CALLOUT_PARAMETERS)
typedef PVOID PKWIN32_CALLOUT_PARAMETERS
Functions
VOID ExpWin32CloseProcedure (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID ExpWin32DeleteProcedure (IN PVOID Object)
BOOLEAN ExpWin32Initialization ()
BOOLEAN ExpWin32OkayToCloseProcedure (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS ExpWin32OpenProcedure (IN OB_OPEN_REASON OpenReason, IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG HandleCount)
NTSTATUS ExpWin32ParseProcedure (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
NTSTATUS ExpWin32SessionCallout (IN PKWIN32_CALLOUT CalloutRoutine, IN PKWIN32_CALLOUT_PARAMETERS Parameters, IN ULONG SessionId, OUT PNTSTATUS CalloutStatus OPTIONAL)
Variables
PKWIN32_CLOSEMETHOD_CALLOUT ExDesktopCloseProcedureCallout
PKWIN32_DELETEMETHOD_CALLOUT ExDesktopDeleteProcedureCallout
POBJECT_TYPE ExDesktopObjectType
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExDesktopOkToCloseProcedureCallout
PKWIN32_OPENMETHOD_CALLOUT ExDesktopOpenProcedureCallout
const GENERIC_MAPPING ExpDesktopMapping
const GENERIC_MAPPING ExpWindowStationMapping
PKWIN32_CLOSEMETHOD_CALLOUT ExWindowStationCloseProcedureCallout
PKWIN32_DELETEMETHOD_CALLOUT ExWindowStationDeleteProcedureCallout
POBJECT_TYPE ExWindowStationObjectType
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExWindowStationOkToCloseProcedureCallout
PKWIN32_OPENMETHOD_CALLOUT ExWindowStationOpenProcedureCallout
PKWIN32_PARSEMETHOD_CALLOUT ExWindowStationParseProcedureCallout
Typedef Documentation
typedef NTSTATUS(* PKWIN32_CALLOUT) (IN PKWIN32_CALLOUT_PARAMETERS)
Definition at line 47 of file win32.c.
typedef PVOID PKWIN32_CALLOUT_PARAMETERS
Definition at line 43 of file win32.c.
Function Documentation
VOID ExpWin32CloseProcedure (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 153 of file win32.c.
References ASSERT, ExDesktopCloseProcedureCallout, ExpWin32SessionCallout(), ExWindowStationCloseProcedureCallout, _WIN32_CLOSEMETHOD_PARAMETERS::GrantedAccess, NT_SUCCESS, NULL, _WIN32_CLOSEMETHOD_PARAMETERS::Object, OBJECT_TO_OBJECT_HEADER, _WIN32_CLOSEMETHOD_PARAMETERS::Process, _WIN32_CLOSEMETHOD_PARAMETERS::ProcessHandleCount, Status, and _WIN32_CLOSEMETHOD_PARAMETERS::SystemHandleCount.
Referenced by ExpWin32Initialization().
VOID ExpWin32DeleteProcedure (IN PVOID Object)
Definition at line 272 of file win32.c.
References ASSERT, ExDesktopDeleteProcedureCallout, ExDesktopObjectType, ExpWin32SessionCallout(), ExWindowStationDeleteProcedureCallout, NT_SUCCESS, NULL, _WIN32_DELETEMETHOD_PARAMETERS::Object, OBJECT_TO_OBJECT_HEADER, and Status.
Referenced by ExpWin32Initialization().
BOOLEAN ExpWin32Initialization ()
Definition at line 437 of file win32.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExpDesktopMapping, ExpWin32CloseProcedure(), ExpWin32DeleteProcedure(), ExpWin32OkayToCloseProcedure(), ExpWin32OpenProcedure(), ExpWin32ParseProcedure(), ExpWindowStationMapping, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_EXCLUSIVE, OBJ_OPENLINK, OBJ_PERMANENT, _OBJECT_TYPE_INITIALIZER::OkayToCloseProcedure, _OBJECT_TYPE_INITIALIZER::OpenProcedure, _OBJECT_TYPE_INITIALIZER::ParseProcedure, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityRequired, STANDARD_RIGHTS_REQUIRED, Status, TRUE, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
BOOLEAN ExpWin32OkayToCloseProcedure (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
Definition at line 212 of file win32.c.
References ASSERT, ExDesktopObjectType, ExDesktopOkToCloseProcedureCallout, ExpWin32SessionCallout(), ExWindowStationOkToCloseProcedureCallout, Handle, _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS::Handle, NT_SUCCESS, _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS::Object, OBJECT_TO_OBJECT_HEADER, _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS::PreviousMode, _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS::Process, Status, and STATUS_UNSUCCESSFUL.
Referenced by ExpWin32Initialization().
NTSTATUS ExpWin32OpenProcedure (IN OB_OPEN_REASON OpenReason, IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG HandleCount)
Definition at line 327 of file win32.c.
References ASSERT, ExDesktopOpenProcedureCallout, ExpWin32SessionCallout(), ExWindowStationOpenProcedureCallout, _WIN32_OPENMETHOD_PARAMETERS::GrantedAccess, _WIN32_OPENMETHOD_PARAMETERS::HandleCount, NT_SUCCESS, _WIN32_OPENMETHOD_PARAMETERS::Object, OBJECT_TO_OBJECT_HEADER, _WIN32_OPENMETHOD_PARAMETERS::OpenReason, _WIN32_OPENMETHOD_PARAMETERS::Process, Status, and STATUS_UNSUCCESSFUL.
Referenced by ExpWin32Initialization().
NTSTATUS ExpWin32ParseProcedure (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 390 of file win32.c.
References _WIN32_PARSEMETHOD_PARAMETERS::AccessMode, _WIN32_PARSEMETHOD_PARAMETERS::AccessState, ASSERT, _WIN32_PARSEMETHOD_PARAMETERS::Attributes, _WIN32_PARSEMETHOD_PARAMETERS::CompleteName, ExpWin32SessionCallout(), ExWindowStationParseProcedureCallout, NT_SUCCESS, _WIN32_PARSEMETHOD_PARAMETERS::Object, _WIN32_PARSEMETHOD_PARAMETERS::ObjectType, _WIN32_PARSEMETHOD_PARAMETERS::ParseObject, _WIN32_PARSEMETHOD_PARAMETERS::RemainingName, _WIN32_PARSEMETHOD_PARAMETERS::SecurityQos, Status, and STATUS_UNSUCCESSFUL.
Referenced by ExpWin32Initialization().
NTSTATUS ExpWin32SessionCallout (IN PKWIN32_CALLOUT CalloutRoutine, IN PKWIN32_CALLOUT_PARAMETERS Parameters, IN ULONG SessionId, OUT PNTSTATUS CalloutStatus OPTIONAL)
Definition at line 537 of file win32.c.
References ARGUMENT_PRESENT, ASSERT, DPFLTR_SYSTEM_ID, DPFLTR_WARNING_LEVEL, KdPrintEx, MmAttachSession(), MmDetachSession(), MmGetSessionById(), MmIsSessionAddress(), MmQuitNextSession(), NT_SUCCESS, NULL, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), PsGetCurrentProcessSessionId(), Status, STATUS_INVALID_PARAMETER, STATUS_NOT_FOUND, and STATUS_SUCCESS.
Referenced by ExpWin32CloseProcedure(), ExpWin32DeleteProcedure(), ExpWin32OkayToCloseProcedure(), ExpWin32OpenProcedure(), and ExpWin32ParseProcedure().
Variable Documentation
PKWIN32_CLOSEMETHOD_CALLOUT ExDesktopCloseProcedureCallout
Definition at line 29 of file win32.c.
Referenced by ExpWin32CloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_DELETEMETHOD_CALLOUT ExDesktopDeleteProcedureCallout
Definition at line 34 of file win32.c.
Referenced by ExpWin32DeleteProcedure(), and PsEstablishWin32Callouts().
POBJECT_TYPE ExDesktopObjectType
Definition at line 27 of file win32.c.
Referenced by ExpWin32DeleteProcedure(), and ExpWin32OkayToCloseProcedure().
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExDesktopOkToCloseProcedureCallout
Definition at line 32 of file win32.c.
Referenced by ExpWin32OkayToCloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_OPENMETHOD_CALLOUT ExDesktopOpenProcedureCallout
Definition at line 31 of file win32.c.
Referenced by ExpWin32OpenProcedure(), and PsEstablishWin32Callouts().
const GENERIC_MAPPING ExpDesktopMapping
Initial value:
= {
    STANDARD_RIGHTS_READ,
    STANDARD_RIGHTS_WRITE,
    STANDARD_RIGHTS_EXECUTE,
    STANDARD_RIGHTS_REQUIRED
}
Definition at line 130 of file win32.c.
Referenced by ExpWin32Initialization().
const GENERIC_MAPPING ExpWindowStationMapping
Initial value:
= {
    STANDARD_RIGHTS_READ,
    STANDARD_RIGHTS_WRITE,
    STANDARD_RIGHTS_EXECUTE,
    STANDARD_RIGHTS_REQUIRED
}
Definition at line 120 of file win32.c.
Referenced by ExpWin32Initialization().
PKWIN32_CLOSEMETHOD_CALLOUT ExWindowStationCloseProcedureCallout
Definition at line 30 of file win32.c.
Referenced by ExpWin32CloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_DELETEMETHOD_CALLOUT ExWindowStationDeleteProcedureCallout
Definition at line 35 of file win32.c.
Referenced by ExpWin32DeleteProcedure(), and PsEstablishWin32Callouts().
POBJECT_TYPE ExWindowStationObjectType
Definition at line 26 of file win32.c.
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExWindowStationOkToCloseProcedureCallout
Definition at line 33 of file win32.c.
Referenced by ExpWin32OkayToCloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_OPENMETHOD_CALLOUT ExWindowStationOpenProcedureCallout
Definition at line 37 of file win32.c.
Referenced by ExpWin32OpenProcedure(), and PsEstablishWin32Callouts().
PKWIN32_PARSEMETHOD_CALLOUT ExWindowStationParseProcedureCallout
Definition at line 36 of file win32.c.
Referenced by ExpWin32ParseProcedure(), and PsEstablishWin32Callouts().