Windows Research Kernel v1.2: C:/Windows Research Kernel/se/accessck.c File Reference
accessck.c File Reference
#include "pch.h"
#include <sertlp.h>
Macros
#define WORLD_TRAVERSAL_INCLUDES_ANONYMOUS 1
Enumerations
enum ACCESS_MASK_FIELD_TO_UPDATE { UpdateRemaining, UpdateCurrentGranted, UpdateCurrentDenied }
Functions
NTSTATUS NtAccessCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in PGENERIC_MAPPING GenericMapping, __out_bcount(*PrivilegeSetLength) PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
NTSTATUS NtAccessCheckByType (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in_ecount(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __out_bcount(*PrivilegeSetLength) PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
NTSTATUS NtAccessCheckByTypeResultList (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in_ecount(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __out_bcount(*PrivilegeSetLength) PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out_ecount(ObjectTypeListLength) PACCESS_MASK GrantedAccess, __out_ecount(ObjectTypeListLength) PNTSTATUS AccessStatus)
BOOLEAN SeAccessCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in BOOLEAN SubjectContextLocked, __in ACCESS_MASK DesiredAccess, __in ACCESS_MASK PreviouslyGrantedAccess, __deref_out_opt PPRIVILEGE_SET *Privileges, __in PGENERIC_MAPPING GenericMapping, __in KPROCESSOR_MODE AccessMode, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
NTSTATUS SeAccessCheckByType (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN HANDLE ClientToken, IN ACCESS_MASK DesiredAccess, IN POBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, OUT PPRIVILEGE_SET PrivilegeSet, IN OUT PULONG PrivilegeSetLength, OUT PACCESS_MASK GrantedAccess, OUT PNTSTATUS AccessStatus, IN BOOLEAN ReturnResultList)
NTSTATUS SeAccessCheckByType (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __out_ecount_part(*PrivilegeSetLength,*PrivilegeSetLength) PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus, __in BOOLEAN ReturnResultList)
NTSTATUS SeCaptureObjectTypeList (__in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in KPROCESSOR_MODE RequestorMode, __out PIOBJECT_TYPE_LIST *CapturedObjectTypeList)
BOOLEAN SeFastTraverseCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in ACCESS_MASK TraverseAccess, __in KPROCESSOR_MODE AccessMode)
VOID SeFreeCapturedObjectTypeList (__in PVOID ObjectTypeList)
VOID SeFreePrivileges (__in PPRIVILEGE_SET Privileges)
VOID SeMaximumAuditMask (IN PACL Sacl, IN ACCESS_MASK GrantedAccess, IN PACCESS_TOKEN Token, OUT PACCESS_MASK pAuditMask)
BOOLEAN SepAccessCheck (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN PTOKEN PrimaryToken, IN PTOKEN ClientToken OPTIONAL, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, IN ACCESS_MASK PreviouslyGrantedAccess, IN KPROCESSOR_MODE PreviousMode, OUT PACCESS_MASK GrantedAccess, OUT PPRIVILEGE_SET *Privileges OPTIONAL, OUT PNTSTATUS AccessStatus, IN BOOLEAN ReturnResultList, OUT PBOOLEAN ReturnSomeAccessGranted, OUT PBOOLEAN ReturnSomeAccessDenied)
VOID SepAddAccessTypeList (IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN ULONG StartIndex, IN ACCESS_MASK AccessMask, IN ACCESS_MASK_FIELD_TO_UPDATE FieldToUpdate)
VOID SepMaximumAccessCheck (IN PTOKEN EToken, IN PTOKEN PrimaryToken, IN PACL Dacl, IN PSID PrincipalSelfSid, IN ULONG LocalTypeListLength, IN PIOBJECT_TYPE_LIST LocalTypeList, IN ULONG ObjectTypeListLength, IN BOOLEAN Restricted)
VOID SepNormalAccessCheck (IN ACCESS_MASK Remaining, IN PTOKEN EToken, IN PTOKEN PrimaryToken, IN PACL Dacl, IN PSID PrincipalSelfSid, IN ULONG LocalTypeListLength, IN PIOBJECT_TYPE_LIST LocalTypeList, IN ULONG ObjectTypeListLength, IN BOOLEAN Restricted)
BOOLEAN SepObjectInTypeList (IN GUID *ObjectType, IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, OUT PULONG ReturnedIndex)
NTSTATUS SePrivilegePolicyCheck (__inout PACCESS_MASK RemainingDesiredAccess, __inout PACCESS_MASK PreviouslyGrantedAccess, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in_opt PACCESS_TOKEN ExplicitToken, __deref_out PPRIVILEGE_SET *PrivilegeSet, __in KPROCESSOR_MODE PreviousMode)
BOOLEAN SepSidInToken (IN PACCESS_TOKEN AToken, IN PSID PrincipalSelfSid, IN PSID Sid, IN BOOLEAN DenyAce)
BOOLEAN SepSidInTokenEx (IN PACCESS_TOKEN AToken, IN PSID PrincipalSelfSid, IN PSID Sid, IN BOOLEAN DenyAce, IN BOOLEAN Restricted)
BOOLEAN SepTokenIsOwner (IN PACCESS_TOKEN EffectiveToken, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN TokenLocked)
VOID SepUpdateParentTypeList (IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN ULONG StartIndex)
Macro Definition Documentation
#define WORLD_TRAVERSAL_INCLUDES_ANONYMOUS 1
Definition at line 3785 of file accessck.c.
Enumeration Type Documentation
enum ACCESS_MASK_FIELD_TO_UPDATE
Enumerator
UpdateRemaining
UpdateCurrentGranted
UpdateCurrentDenied
Definition at line 51 of file accessck.c.
Function Documentation
NTSTATUS NtAccessCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in PGENERIC_MAPPING GenericMapping, __out_bcount *PrivilegeSetLength PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
Definition at line 2370 of file accessck.c.
References FALSE, NULL, PAGED_CODE, and SeAccessCheckByType().
NTSTATUS NtAccessCheckByType (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in_ecount(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __out_bcount *PrivilegeSetLength PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
Definition at line 2458 of file accessck.c.
References FALSE, PAGED_CODE, and SeAccessCheckByType().
NTSTATUS NtAccessCheckByTypeResultList (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in_ecount(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __out_bcount *PrivilegeSetLength PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out_ecount(ObjectTypeListLength) PACCESS_MASK GrantedAccess, __out_ecount(ObjectTypeListLength) PNTSTATUS AccessStatus)
Definition at line 2559 of file accessck.c.
References PAGED_CODE, SeAccessCheckByType(), and TRUE.
BOOLEAN SeAccessCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in BOOLEAN SubjectContextLocked, __in ACCESS_MASK DesiredAccess, __in ACCESS_MASK PreviouslyGrantedAccess, __deref_out_opt PPRIVILEGE_SET * Privileges, __in PGENERIC_MAPPING GenericMapping, __in KPROCESSOR_MODE AccessMode, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus)
Definition at line 3318 of file accessck.c.
References DbgPrint(), EffectiveToken, FALSE, KernelMode, MAXIMUM_ALLOWED, NULL, PAGED_CODE, READ_CONTROL, SeAssertMappedCanonicalAccess, SecurityImpersonation, SeLockSubjectContext(), SepAccessCheck(), SepTokenIsOwner(), SeUnlockSubjectContext(), STATUS_ACCESS_DENIED, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_SUCCESS, TRUE, and WRITE_DAC.
Referenced by CmpCheckCreateAccess(), CmpCheckKeyAccess(), CmpCheckNotifyAccess(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), PspCreateProcess(), PspCreateThread(), PspSetPrimaryToken(), and WmipCheckGuidAccess().
NTSTATUS SeAccessCheckByType (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN HANDLE ClientToken, IN ACCESS_MASK DesiredAccess, IN POBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, OUT PPRIVILEGE_SET PrivilegeSet, IN OUT PULONG PrivilegeSetLength, OUT PACCESS_MASK GrantedAccess, OUT PNTSTATUS AccessStatus, IN BOOLEAN ReturnResultList)
Referenced by NtAccessCheck(), NtAccessCheckByType(), and NtAccessCheckByTypeResultList().
NTSTATUS SeAccessCheckByType (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __out_ecount_part *,*PrivilegeSetLength PPRIVILEGE_SET PrivilegeSet, __inout PULONG PrivilegeSetLength, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus, __in BOOLEAN ReturnResultList)
Definition at line 2661 of file accessck.c.
References ASSERT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, GENERIC_ALL, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, _TOKEN::ImpersonationLevel, IsValidElementCount, KeGetPreviousMode, KernelMode, leave, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, ProbeAndReadUlong, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteUlong, READ_CONTROL, RtlCopyMemory, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSid(), SeCaptureSubjectContext(), SecurityIdentification, SeFreeCapturedObjectTypeList(), SeFreePrivileges(), SepAccessCheck(), SepAcquireTokenReadLock, SepPrivilegeSetSize, SepReleaseTokenReadLock, SePrivilegePolicyCheck(), SepTokenIsOwner(), SeReleaseSecurityDescriptor(), SeReleaseSid(), SeReleaseSubjectContext(), SeTokenObjectType, Status, STATUS_ACCESS_DENIED, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_BUFFER_TOO_SMALL, STATUS_GENERIC_NOT_MAPPED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_INVALID_SECURITY_DESCR, STATUS_NO_IMPERSONATION_TOKEN, STATUS_SUCCESS, TOKEN_QUERY, TokenImpersonation, _TOKEN::TokenType, TRUE, VOID, and WRITE_DAC.
NTSTATUS SeCaptureObjectTypeList (__in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList , __in ULONG ObjectTypeListLength, __in KPROCESSOR_MODE RequestorMode, __out PIOBJECT_TYPE_LIST * CapturedObjectTypeList)
Definition at line 142 of file accessck.c.
References ACCESS_MAX_LEVEL, ARGUMENT_PRESENT, _IOBJECT_TYPE_LIST::CurrentDenied, _IOBJECT_TYPE_LIST::CurrentGranted, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _IOBJECT_TYPE_LIST::Flags, IsValidElementCount, leave, _IOBJECT_TYPE_LIST::Level, NT_SUCCESS, NULL, _IOBJECT_TYPE_LIST::ObjectType, PAGED_CODE, PagedPool, _IOBJECT_TYPE_LIST::ParentIndex, ProbeForRead, ProbeForReadSmallStructure, _IOBJECT_TYPE_LIST::Remaining, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, and UserMode.
Referenced by SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SeFastTraverseCheck (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in ACCESS_MASK TraverseAccess, __in KPROCESSOR_MODE AccessMode)
Definition at line 3788 of file accessck.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_DENIED_ACE_TYPE, _ACL::AceCount, ASSERT, FALSE, FirstAce, INHERIT_ONLY_ACE, KernelMode, NextAce, NULL, PAGED_CODE, RtlEqualSid(), RtlpDaclAddrSecurityDescriptor, SeAnonymousLogonSid, SeWorldSid, TOKEN_IS_RESTRICTED, and TRUE.
VOID SeFreeCapturedObjectTypeList (__in PVOID ObjectTypeList)
Definition at line 357 of file accessck.c.
References ExFreePool(), NULL, and PAGED_CODE.
Referenced by SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
VOID SeFreePrivileges (__in PPRIVILEGE_SET Privileges)
Definition at line 3289 of file accessck.c.
References ExFreePool(), and PAGED_CODE.
Referenced by IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckTraverseAccess(), and SeAccessCheckByType().
VOID SeMaximumAuditMask (IN PACL Sacl, IN ACCESS_MASK GrantedAccess, IN PACCESS_TOKEN Token, OUT PACCESS_MASK pAuditMask)
Definition at line 1609 of file accessck.c.
References FALSE, FirstAce, INHERIT_ONLY_ACE, NextAce, NULL, SepSidInToken(), SUCCESSFUL_ACCESS_ACE_FLAG, and SYSTEM_AUDIT_ACE_TYPE.
Referenced by SeOpenObjectAuditAlarm().
BOOLEAN SepAccessCheck (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN PTOKEN PrimaryToken, IN PTOKEN ClientToken OPTIONAL, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, IN ACCESS_MASK PreviouslyGrantedAccess, IN KPROCESSOR_MODE PreviousMode, OUT PACCESS_MASK GrantedAccess, OUT PPRIVILEGE_SET *Privileges OPTIONAL, OUT PNTSTATUS AccessStatus, IN BOOLEAN ReturnResultList, OUT PBOOLEAN ReturnSomeAccessGranted, OUT PBOOLEAN ReturnSomeAccessDenied)
Definition at line 1702 of file accessck.c.
References ACCESS_SYSTEM_SECURITY, _ACL::AceCount, ARGUMENT_PRESENT, ASSERT, _IOBJECT_TYPE_LIST::CurrentGranted, FALSE, Index, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, PAGED_CODE, _IOBJECT_TYPE_LIST::ParentIndex, _IOBJECT_TYPE_LIST::Remaining, RtlpAreControlBitsSet, RtlpDaclAddrSecurityDescriptor, RtlZeroMemory, SE_DACL_PRESENT, SeAssertMappedCanonicalAccess, SepAssemblePrivileges(), SepMaximumAccessCheck(), SepNormalAccessCheck(), SepSinglePrivilegeCheck(), SeSecurityPrivilege, SeTakeOwnershipPrivilege, SeTokenIsRestricted(), Status, STATUS_ACCESS_DENIED, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TRUE, and WRITE_OWNER.
Referenced by SeAccessCheck(), SeAccessCheckByType(), SepAccessCheckAndAuditAlarm(), and SepCheckTokenForCoreSystemSids().
VOID SepAddAccessTypeList (IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN ULONG StartIndex, IN ACCESS_MASK AccessMask, IN ACCESS_MASK_FIELD_TO_UPDATE FieldToUpdate)
Definition at line 578 of file accessck.c.
References FALSE, Index, PAGED_CODE, SepUpdateParentTypeList(), TRUE, UpdateCurrentDenied, UpdateCurrentGranted, and UpdateRemaining.
Referenced by SepMaximumAccessCheck(), and SepNormalAccessCheck().
VOID SepMaximumAccessCheck (IN PTOKEN EToken, IN PTOKEN PrimaryToken, IN PACL Dacl, IN PSID PrincipalSelfSid, IN ULONG LocalTypeListLength, IN PIOBJECT_TYPE_LIST LocalTypeList, IN ULONG ObjectTypeListLength, IN BOOLEAN Restricted)
Definition at line 1026 of file accessck.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_ALLOWED_COMPOUND_ACE_TYPE, ACCESS_ALLOWED_OBJECT_ACE_TYPE, ACCESS_DENIED_ACE_TYPE, ACCESS_DENIED_OBJECT_ACE_TYPE, FALSE, FirstAce, Index, INHERIT_ONLY_ACE, NextAce, NULL, RtlCompoundAceClientSid, RtlCompoundAceServerSid, RtlObjectAceObjectType, RtlObjectAceSid, SepAddAccessTypeList(), SepObjectInTypeList(), SepSidInTokenEx(), TRUE, UpdateCurrentDenied, and UpdateCurrentGranted.
Referenced by SepAccessCheck().
VOID SepNormalAccessCheck (IN ACCESS_MASK Remaining, IN PTOKEN EToken, IN PTOKEN PrimaryToken, IN PACL Dacl, IN PSID PrincipalSelfSid, IN ULONG LocalTypeListLength, IN PIOBJECT_TYPE_LIST LocalTypeList, IN ULONG ObjectTypeListLength, IN BOOLEAN Restricted)
Definition at line 1351 of file accessck.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_ALLOWED_COMPOUND_ACE_TYPE, ACCESS_ALLOWED_OBJECT_ACE_TYPE, ACCESS_DENIED_ACE_TYPE, ACCESS_DENIED_OBJECT_ACE_TYPE, FALSE, FirstAce, Index, INHERIT_ONLY_ACE, NextAce, NULL, RtlCompoundAceClientSid, RtlCompoundAceServerSid, RtlObjectAceObjectType, RtlObjectAceSid, SepAddAccessTypeList(), SepObjectInTypeList(), SepSidInTokenEx(), TRUE, and UpdateRemaining.
Referenced by SepAccessCheck().
BOOLEAN SepObjectInTypeList (IN GUID * ObjectType, IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, OUT PULONG ReturnedIndex)
Definition at line 392 of file accessck.c.
References ASSERT, FALSE, Index, PAGED_CODE, RtlpIsEqualGuid, and TRUE.
Referenced by SepExamineSaclEx(), SepMaximumAccessCheck(), and SepNormalAccessCheck().
NTSTATUS SePrivilegePolicyCheck (__inout PACCESS_MASK RemainingDesiredAccess, __inout PACCESS_MASK PreviouslyGrantedAccess, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in_opt PACCESS_TOKEN ExplicitToken, __deref_out PPRIVILEGE_SET * PrivilegeSet, __in KPROCESSOR_MODE PreviousMode)
Definition at line 3568 of file accessck.c.
References ACCESS_SYSTEM_SECURITY, ANYSIZE_ARRAY, ARGUMENT_PRESENT, EffectiveToken, ExAllocatePoolWithTag, FALSE, NULL, PAGED_CODE, PagedPool, SE_PRIVILEGE_USED_FOR_ACCESS, SepSinglePrivilegeCheck(), SeSecurityPrivilege, SeTakeOwnershipPrivilege, STATUS_INSUFFICIENT_RESOURCES, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TRUE, and WRITE_OWNER.
Referenced by SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SepSidInToken (IN PACCESS_TOKEN AToken, IN PSID PrincipalSelfSid, IN PSID Sid, IN BOOLEAN DenyAce)
Definition at line 747 of file accessck.c.
References _SID_AND_ATTRIBUTES::Attributes, C_ASSERT, FALSE, FIELD_OFFSET, NULL, PAGED_CODE, _SID::Revision, RtlEqualMemory, RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_USE_FOR_DENY_ONLY, SePrincipalSelfSid, _SID_AND_ATTRIBUTES::Sid, TRUE, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
Referenced by SeMaximumAuditMask(), SepExamineSacl(), SepExamineSaclEx(), and SepTokenIsOwner().
BOOLEAN SepSidInTokenEx (IN PACCESS_TOKEN AToken, IN PSID PrincipalSelfSid, IN PSID Sid, IN BOOLEAN DenyAce, IN BOOLEAN Restricted)
Definition at line 878 of file accessck.c.
References _SID_AND_ATTRIBUTES::Attributes, C_ASSERT, FALSE, FIELD_OFFSET, NULL, PAGED_CODE, _TOKEN::RestrictedSidCount, _TOKEN::RestrictedSids, _SID::Revision, RtlEqualMemory, RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_USE_FOR_DENY_ONLY, SePrincipalSelfSid, _SID_AND_ATTRIBUTES::Sid, TRUE, _TOKEN::UserAndGroupCount, and _TOKEN::UserAndGroups.
Referenced by SepMaximumAccessCheck(), SepNormalAccessCheck(), and SepTokenIsOwner().
BOOLEAN SepTokenIsOwner (IN PACCESS_TOKEN EffectiveToken, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN BOOLEAN TokenLocked)
Definition at line 3712 of file accessck.c.
References ASSERT, FALSE, NULL, PAGED_CODE, RtlpOwnerAddrSecurityDescriptor, SepAcquireTokenReadLock, SepReleaseTokenReadLock, SepSidInToken(), SepSidInTokenEx(), TOKEN_IS_RESTRICTED, _TOKEN::TokenFlags, and TRUE.
Referenced by SeAccessCheck(), SeAccessCheckByType(), and SepAccessCheckAndAuditAlarm().
VOID SepUpdateParentTypeList (IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN ULONG StartIndex)
Definition at line 445 of file accessck.c.
References Index, and PAGED_CODE.
Referenced by SepAddAccessTypeList().