Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obse.c File Reference
obse.c File Reference
#include "obp.h"
Functions
NTSTATUS NtQuerySecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __out_bcount_opt(Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Length, __out PULONG LengthNeeded)
NTSTATUS NtSetSecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSTATUS ObAssignObjectSecurityDescriptor (IN PVOID Object, IN PSECURITY_DESCRIPTOR SecurityDescriptor OPTIONAL, IN POOL_TYPE PoolType)
NTSTATUS ObAssignSecurity (__in PACCESS_STATE AccessState, __in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in PVOID Object, __in POBJECT_TYPE ObjectType)
BOOLEAN ObCheckCreateObjectAccess (__in PVOID DirectoryObject, __in ACCESS_MASK CreateAccess, __in PACCESS_STATE AccessState, __in PUNICODE_STRING ComponentName, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE PreviousMode, __out PNTSTATUS AccessStatus)
BOOLEAN ObCheckObjectAccess (__in PVOID Object, __inout PACCESS_STATE AccessState, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE AccessMode, __out PNTSTATUS AccessStatus)
NTSTATUS ObGetObjectSecurity (__in PVOID Object, __out PSECURITY_DESCRIPTOR *SecurityDescriptor, __out PBOOLEAN MemoryAllocated)
BOOLEAN ObpCheckObjectReference (IN PVOID Object, IN OUT PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE AccessMode, OUT PNTSTATUS AccessStatus)
BOOLEAN ObpCheckTraverseAccess (IN PVOID DirectoryObject, IN ACCESS_MASK TraverseAccess, IN PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE PreviousMode, OUT PNTSTATUS AccessStatus)
NTSTATUS ObpValidateAccessMask (PACCESS_STATE AccessState)
NTSTATUS ObQuerySecurityDescriptorInfo (IN PVOID Object, IN PSECURITY_INFORMATION SecurityInformation, OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG Length, IN PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor)
VOID ObReleaseObjectSecurity (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in BOOLEAN MemoryAllocated)
NTSTATUS ObSetSecurityDescriptorInfo (__in PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __inout PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
NTSTATUS ObSetSecurityObjectByPointer (__in PVOID Object, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSTATUS ObValidateSecurityQuota (IN PVOID Object, IN ULONG NewSize)
Variables
ULONG ObpDefaultSecurityDescriptorLength = 256
Function Documentation
NTSTATUS NtQuerySecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __out_bcount_opt(Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Length, __out PULONG LengthNeeded)
Definition at line 251 of file obse.c.
References except, EXCEPTION_EXECUTE_HANDLER, _OBJECT_TYPE_INITIALIZER::GenericMapping, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, PAGED_CODE, _OBJECT_TYPE_INITIALIZER::PoolType, ProbeForWrite(), ProbeForWriteUlong, QuerySecurityDescriptor, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SeQuerySecurityAccessMask(), Status, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by CmpCloneControlSet(), CmpSaveBootControlSet(), and RtlpSysVolCheckOwnerAndSecurity().
NTSTATUS NtSetSecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 44 of file obse.c.
References ARGUMENT_PRESENT, ASSERT, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObSetSecurityObjectByPointer(), _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, PAGED_CODE, PagedPool, SE_SELF_RELATIVE, SeCaptureSecurityDescriptor(), SeReleaseSecurityDescriptor(), SeSetSecurityAccessMask(), Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_SECURITY_DESCR, and TRUE.
Referenced by RtlpSysVolCheckOwnerAndSecurity(), and RtlpSysVolTakeOwnership().
NTSTATUS ObAssignObjectSecurityDescriptor (IN PVOID Object, IN PSECURITY_DESCRIPTOR SecurityDescriptor OPTIONAL, IN POOL_TYPE PoolType)
Definition at line 1041 of file obse.c.
References ARGUMENT_PRESENT, ASSERT, ExFastRefGetAdditionalReferenceCount(), ExFastRefInitialize(), ExFreePool(), NT_SUCCESS, NULL, OBJECT_TO_OBJECT_HEADER, ObLogSecurityDescriptor(), PAGED_CODE, _OBJECT_HEADER::SecurityDescriptor, Status, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by CmpAssignSecurityDescriptorWrapper(), SeDefaultObjectMethod(), and WmipSecurityMethod().
NTSTATUS ObAssignSecurity (__in PACCESS_STATE AccessState, __in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in PVOID Object, __in POBJECT_TYPE ObjectType)
Definition at line 1478 of file obse.c.
References AssignSecurityDescriptor, NT_SUCCESS, NULL, ObpBeginTypeSpecificCallOut, ObpDirectoryObjectType, ObpEndTypeSpecificCallOut, PAGED_CODE, PagedPool, SeAssignSecurity(), SeDeassignSecurity(), and Status.
Referenced by ObInsertObject().
BOOLEAN ObCheckCreateObjectAccess (__in PVOID DirectoryObject, __in ACCESS_MASK CreateAccess, __in PACCESS_STATE AccessState, __in PUNICODE_STRING ComponentName, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE PreviousMode, __out PNTSTATUS AccessStatus)
Definition at line 877 of file obse.c.
References FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeAppendPrivileges(), SeFreePrivileges(), SeLockSubjectContext(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by ObpLookupObjectName().
BOOLEAN ObCheckObjectAccess (__in PVOID Object, __inout PACCESS_STATE AccessState, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE AccessMode, __out PNTSTATUS AccessStatus)
Definition at line 388 of file obse.c.
References FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, MAXIMUM_ALLOWED, _OBJECT_TYPE::Name, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeAppendPrivileges(), SeFreePrivileges(), SeLockSubjectContext(), SeOpenObjectAuditAlarm(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by CmpDoOpen(), and ObpIncrementHandleCount().
NTSTATUS ObGetObjectSecurity (__in PVOID Object, __out PSECURITY_DESCRIPTOR * SecurityDescriptor, __out PBOOLEAN MemoryAllocated)
Definition at line 1131 of file obse.c.
References DACL_SECURITY_INFORMATION, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, GROUP_SECURITY_INFORMATION, NT_SUCCESS, NULL, OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpCentralizedSecurity, ObpDefaultSecurityDescriptorLength, ObpEndTypeSpecificCallOut, ObpReferenceSecurityDescriptor(), OWNER_SECURITY_INFORMATION, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, QuerySecurityDescriptor, SACL_SECURITY_INFORMATION, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObInsertObject(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), PspCreateProcess(), PspCreateThread(), and PspSetPrimaryToken().
BOOLEAN ObpCheckObjectReference (IN PVOID Object, IN OUT PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE AccessMode, OUT PNTSTATUS AccessStatus)
Definition at line 568 of file obse.c.
References FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeLockSubjectContext(), SeObjectReferenceAuditAlarm(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by ObReferenceObjectByName().
BOOLEAN ObpCheckTraverseAccess (IN PVOID DirectoryObject, IN ACCESS_MASK TraverseAccess, IN PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE PreviousMode, OUT PNTSTATUS AccessStatus)
Definition at line 721 of file obse.c.
References DIRECTORY_TRAVERSE, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeAppendPrivileges(), SeFastTraverseCheck(), SeFreePrivileges(), SeLockSubjectContext(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by ObpLookupObjectName().
NTSTATUS ObpValidateAccessMask (PACCESS_STATE AccessState)
Definition at line 1803 of file obse.c.
References ACCESS_SYSTEM_SECURITY, _SECURITY_DESCRIPTOR::Control, NULL, PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, _ACCESS_STATE::RemainingDesiredAccess, SE_SACL_PRESENT, _ACCESS_STATE::SecurityDescriptor, and STATUS_SUCCESS.
Referenced by ObInsertObject(), and ObOpenObjectByName().
NTSTATUS ObQuerySecurityDescriptorInfo (IN PVOID Object, IN PSECURITY_INFORMATION SecurityInformation, OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG Length, IN PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor)
Definition at line 1585 of file obse.c.
References NULL, ObDereferenceSecurityDescriptor(), OBJECT_TO_OBJECT_HEADER, ObpReferenceSecurityDescriptor(), PAGED_CODE, SeQuerySecurityDescriptorInfo(), Status, and UNREFERENCED_PARAMETER.
Referenced by SeDefaultObjectMethod(), and WmipSecurityMethod().
VOID ObReleaseObjectSecurity (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in BOOLEAN MemoryAllocated)
Definition at line 1319 of file obse.c.
References ExFreePool(), NULL, ObDereferenceSecurityDescriptor(), and PAGED_CODE.
Referenced by ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObInsertObject(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), PspCreateProcess(), PspCreateThread(), and PspSetPrimaryToken().
NTSTATUS ObSetSecurityDescriptorInfo (__in PVOID Object, __in PSECURITY_INFORMATION SecurityInformation, __inout PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, __in POOL_TYPE PoolType, __in PGENERIC_MAPPING GenericMapping)
Definition at line 1663 of file obse.c.
References ExFastRefCompareSwapObject(), ExFastRefEqualObjects(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetUnusedReferences(), ExFreePool(), NT_SUCCESS, NULL, ObDereferenceSecurityDescriptor(), OBJECT_TO_OBJECT_HEADER, ObLogSecurityDescriptor(), ObpLockObject, ObpReferenceSecurityDescriptor(), ObpUnlockObject, PAGED_CODE, SeSetSecurityDescriptorInfo(), and Status.
Referenced by SeAddSaclToProcess(), SeDefaultObjectMethod(), and WmipSecurityMethod().
NTSTATUS ObSetSecurityObjectByPointer (__in PVOID Object, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 171 of file obse.c.
References ARGUMENT_PRESENT, ASSERT, _OBJECT_TYPE_INITIALIZER::GenericMapping, NULL, OBJECT_TO_OBJECT_HEADER, PAGED_CODE, _OBJECT_TYPE_INITIALIZER::PoolType, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SetSecurityDescriptor, Status, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by NtSetSecurityObject(), and WmipDriverEntry().
NTSTATUS ObValidateSecurityQuota (IN PVOID Object, IN ULONG NewSize)
Definition at line 1374 of file obse.c.
References _OBJECT_HEADER::Flags, NULL, OB_FLAG_DEFAULT_SECURITY_QUOTA, OBJECT_HEADER_TO_QUOTA_INFO(), OBJECT_TO_OBJECT_HEADER, PAGED_CODE, _OBJECT_HEADER::QuotaBlockCharged, SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, STATUS_QUOTA_EXCEEDED, and STATUS_SUCCESS.
Referenced by RtlpSetSecurityObject().
Variable Documentation
ULONG ObpDefaultSecurityDescriptorLength = 256
Definition at line 41 of file obse.c.
Referenced by ObGetObjectSecurity().