Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/pscid.c File Reference
pscid.c File Reference
#include "psp.h"
Functions
NTSTATUS PsLookupProcessByProcessId (__in HANDLE ProcessId, __deref_out PEPROCESS *Process)
NTSTATUS PsLookupProcessThreadByCid (__in PCLIENT_ID Cid, __deref_opt_out PEPROCESS *Process, __deref_out PETHREAD *Thread)
NTSTATUS PsLookupThreadByThreadId (__in HANDLE ThreadId, __deref_out PETHREAD *Thread)
Function Documentation
NTSTATUS PsLookupProcessByProcessId (__in HANDLE ProcessId, __deref_out PEPROCESS * Process)
Definition at line 118 of file pscid.c.
References ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _EPROCESS::GrantedAccess, _KPROCESS::Header, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, _HANDLE_TABLE_ENTRY::Object, ObReferenceObjectSafe(), PAGED_CODE, _EPROCESS::Pcb, ProcessObject, PsGetCurrentThread(), PspCidTable, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, and _DISPATCHER_HEADER::Type.
Referenced by CmpDumpOneKeyBody(), and NtOpenProcess().
NTSTATUS PsLookupProcessThreadByCid (__in PCLIENT_ID Cid, __deref_opt_out PEPROCESS * Process, __deref_out PETHREAD * Thread)
Definition at line 28 of file pscid.c.
References ARGUMENT_PRESENT, _ETHREAD::Cid, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _ETHREAD::GrantedAccess, _KTHREAD::Header, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, ObDereferenceObject(), _HANDLE_TABLE_ENTRY::Object, ObReferenceObject, ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), PspCidTable, Status, STATUS_INVALID_CID, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, ThreadObject, _DISPATCHER_HEADER::Type, and _CLIENT_ID::UniqueProcess.
Referenced by LpcpCopyRequestData(), LpcpRequestWaitReplyPort(), NtAcceptConnectPort(), NtImpersonateClientOfPort(), NtOpenProcess(), NtOpenThread(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
NTSTATUS PsLookupThreadByThreadId (__in HANDLE ThreadId, __deref_out PETHREAD * Thread)
Definition at line 180 of file pscid.c.
References ExMapHandleToPointer(), ExUnlockHandleTableEntry(), _ETHREAD::GrantedAccess, _KTHREAD::Header, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), NULL, _HANDLE_TABLE_ENTRY::Object, ObReferenceObjectSafe(), PAGED_CODE, PsGetCurrentThread(), PspCidTable, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, ThreadObject, and _DISPATCHER_HEADER::Type.
Referenced by NtOpenThread().