Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/register.c File Reference
register.c File Reference
#include "wmikmp.h"
Macros
#define INITIALREGINFOSIZE 8192
#define WmipAllocProviderId(DeviceObject) ((ULONG)(DeviceObject))
Functions
PREGENTRY WmipAllocRegEntry (PDEVICE_OBJECT DeviceObject, ULONG Flags)
void WmipDecrementIrpCount (IN PREGENTRY RegEntry)
NTSTATUS WmipDeregisterDevice (PDEVICE_OBJECT DeviceObject)
PREGENTRY WmipDoFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, ULONG InvalidFlags)
BOOLEAN WmipDoUnreferenceRegEntry (PREGENTRY RegEntry)
PREGENTRY WmipFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, BOOLEAN ReferenceIrp)
void WmipInitializeRegistration (ULONG Phase)
NTSTATUS WmipPDOToDeviceInstanceName (IN PDEVICE_OBJECT PDO, OUT PUNICODE_STRING DeviceInstanceName)
NTSTATUS WmipProcessWmiRegInfo (IN PREGENTRY RegEntry, IN PWMIREGINFO WmiRegInfo, IN ULONG BufferSize, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN Update, IN BOOLEAN IsUserMode)
NTSTATUS WmipQueueRegWork (REGOPERATION RegOperation, PREGENTRY RegEntry)
NTSTATUS WmipRegisterDevice (PDEVICE_OBJECT DeviceObject, ULONG RegistrationFlag)
NTSTATUS WmipRegisterDS (PREGENTRY RegEntry)
NTSTATUS WmipRegisterOrUpdateDS (PREGENTRY RegEntry, BOOLEAN Update)
void WmipRegistrationWorker (PVOID Context)
void WmipRemoveDS (PREGENTRY RegEntry)
void WmipTranslatePDOInstanceNames (IN OUT PIRP Irp, IN UCHAR MinorFunction, IN ULONG MaxBufferSize, IN OUT PREGENTRY RegEntry)
NTSTATUS WmipUpdateDS (PREGENTRY RegEntry)
NTSTATUS WmipUpdateRegistration (PDEVICE_OBJECT DeviceObject)
NTSTATUS WmipValidateWmiRegInfoString (PWMIREGINFO WmiRegInfo, ULONG BufferSize, ULONG Offset, PWCHAR *String)
void WmipWaitForIrpCompletion (PREGENTRY RegEntry)
Variables
const GUID WmipDataProviderPnpidGuid = DATA_PROVIDER_PNPID_GUID
const GUID WmipDataProviderPnPIdInstanceNamesGuid = DATA_PROVIDER_PNPID_INSTANCE_NAMES_GUID
LONG WmipInUseRegEntryCount = 0
LIST_ENTRY WmipInUseRegEntryHead = {&WmipInUseRegEntryHead,&WmipInUseRegEntryHead}
KMUTEX WmipRegistrationMutex
KSPIN_LOCK WmipRegistrationSpinLock
NPAGED_LOOKASIDE_LIST WmipRegLookaside
LONG WmipRegWorkItemCount = 1
LIST_ENTRY WmipRegWorkList = {&WmipRegWorkList, &WmipRegWorkList}
WORK_QUEUE_ITEM WmipRegWorkQueue
Macro Definition Documentation
#define INITIALREGINFOSIZE 8192
Definition at line 1396 of file register.c.
Referenced by WmipRegisterOrUpdateDS().
#define WmipAllocProviderId (DeviceObject) ((ULONG)(DeviceObject))
Definition at line 176 of file register.c.
Referenced by WmipAllocRegEntry().
Function Documentation
PREGENTRY WmipAllocRegEntry (PDEVICE_OBJECT DeviceObject, ULONG Flags)
Definition at line 179 of file register.c.
References _REGENTRY::DataSource, _REGENTRY::DeviceObject, _REGENTRY::Event, ExAllocateFromNPagedLookasideList(), ExInterlockedInsertTailList(), FALSE, _REGENTRY::Flags, InterlockedIncrement, _REGENTRY::InUseEntryList, _REGENTRY::IrpCount, KeInitializeEvent(), NULL, PAGED_CODE, _REGENTRY::PDO, _REGENTRY::ProviderId, _REGENTRY::RefCount, SynchronizationEvent, WmipAllocProviderId, WmipInUseRegEntryCount, WmipRegistrationSpinLock, and WmipRegLookaside.
Referenced by WmipInitializeDataStructs(), WmipRegisterDevice(), and WmipRegisterUMGuids().
void WmipDecrementIrpCount (IN PREGENTRY RegEntry)
Definition at line 811 of file register.c.
References FALSE, InterlockedDecrement, KeSetEvent(), REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, and WmipAssert.
Referenced by WmipForwardWmiIrp(), and WmipWmiIrpCompletion().
NTSTATUS WmipDeregisterDevice (PDEVICE_OBJECT DeviceObject)
Definition at line 546 of file register.c.
References DPFLTR_WMICORE_ID, FALSE, _REGENTRY::Flags, InterlockedExchange(), NULL, ObDereferenceObject(), PAGED_CODE, REGENTRY_FLAG_CALLBACK, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, WmipDebugPrintEx, WmipEnterSMCritSection, WmipFindRegEntryByDevice(), WmipLeaveSMCritSection, WmipUnreferenceRegEntry, and WmipWaitForIrpCompletion().
Referenced by IoWMIRegistrationControl().
PREGENTRY WmipDoFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, ULONG InvalidFlags)
Definition at line 735 of file register.c.
References CONTAINING_RECORD, _REGENTRY::DeviceObject, _REGENTRY::Flags, _LIST_ENTRY::Flink, and NULL.
Referenced by WmipFindRegEntryByDevice().
BOOLEAN WmipDoUnreferenceRegEntry (PREGENTRY RegEntry)
Definition at line 239 of file register.c.
References _LIST_ENTRY::Blink, DPFLTR_WMICORE_ID, ExFreeToNPagedLookasideList(), ExInterlockedRemoveHeadList(), FALSE, _REGENTRY::Flags, InterlockedDecrement, _REGENTRY::InUseEntryList, NULL, ObDereferenceObject(), PAGED_CODE, _REGENTRY::PDO, _REGENTRY::ProviderId, _REGENTRY::RefCount, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, TRUE, WmipAssert, WmipDebugPrintEx, WmipEnterSMCritSection, WmipInUseRegEntryCount, WmipLeaveSMCritSection, WmipRegistrationSpinLock, WmipRegLookaside, and WmipRemoveDS().
PREGENTRY WmipFindRegEntryByDevice (PDEVICE_OBJECT DeviceObject, BOOLEAN ReferenceIrp)
Definition at line 766 of file register.c.
References InterlockedIncrement, _REGENTRY::IrpCount, NULL, PAGED_CODE, REGENTRY_FLAG_RUNDOWN, WmipDoFindRegEntryByDevice(), WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipReferenceRegEntry.
Referenced by IoWMIRegistrationControl(), WmipDeregisterDevice(), WmipQueryWmiDataBlock(), WmipRegisterDevice(), and WmipUpdateRegistration().
void WmipInitializeRegistration (ULONG Phase)
Definition at line 121 of file register.c.
References DelayedWorkQueue, ExInitializeNPagedLookasideList(), ExInitializeWorkItem, ExQueueWorkItem(), InterlockedDecrement, KeInitializeSpinLock(), NULL, PAGED_CODE, WmipRegistrationSpinLock, WmipRegistrationWorker(), WmipRegLookaside, WmipRegWorkItemCount, and WMIREGPOOLTAG.
Referenced by WMIInitialize(), and WmipDriverEntry().
NTSTATUS WmipPDOToDeviceInstanceName (IN PDEVICE_OBJECT PDO, OUT PUNICODE_STRING DeviceInstanceName)
Definition at line 852 of file register.c.
References IoGetDeviceInstanceName(), NULL, PAGED_CODE, Status, and WmipAssert.
Referenced by WmipQueryWmiDataBlock(), WmipTranslateFileHandle(), and WmipTranslatePDOInstanceNames().
NTSTATUS WmipProcessWmiRegInfo (IN PREGENTRY RegEntry, IN PWMIREGINFO WmiRegInfo, IN ULONG BufferSize, IN PWMIGUIDOBJECT RequestObject, IN BOOLEAN Update, IN BOOLEAN IsUserMode)
Definition at line 1227 of file register.c.
References DPFLTR_WMICORE_ID, NT_SUCCESS, PAGED_CODE, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, WmipAddDataSource(), WmipDebugPrintEx, WmipUpdateDataSource(), and WmipValidateWmiRegInfoString().
Referenced by WmipRegisterOrUpdateDS(), and WmipRegisterUMGuids().
NTSTATUS WmipQueueRegWork (REGOPERATION RegOperation, PREGENTRY RegEntry)
Definition at line 1650 of file register.c.
References DelayedWorkQueue, DPFLTR_WMICORE_ID, ExQueueWorkItem(), InsertTailList(), InterlockedIncrement, _REGISTRATIONWORKITEM::ListEntry, NULL, PAGED_CODE, _REGISTRATIONWORKITEM::RegEntry, _REGISTRATIONWORKITEM::RegOperation, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, WmipAlloc, WmipDebugPrintEx, WmipEnterSMCritSection, WmipLeaveSMCritSection, WmipReferenceRegEntry, and WmipRegWorkItemCount.
Referenced by WmipRegisterDevice(), and WmipUpdateRegistration().
NTSTATUS WmipRegisterDevice (PDEVICE_OBJECT DeviceObject, ULONG RegistrationFlag)
Definition at line 345 of file register.c.
References _REGENTRY::DeviceObject, DPFLTR_WMICORE_ID, FALSE, _REGENTRY::Flags, KernelMode, NT_SUCCESS, NULL, ObReferenceObjectByPointer(), PAGED_CODE, REGENTRY_FLAG_CALLBACK, REGENTRY_FLAG_INUSE, REGENTRY_FLAG_NEWREGINFO, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_REG_IN_PROGRESS, REGENTRY_FLAG_RUNDOWN, REGENTRY_FLAG_TRACED, RegisterSingleDriver, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_EXISTS, STATUS_SUCCESS, TRUE, WmipAllocRegEntry(), WmipDebugPrintEx, WmipEnterSMCritSection, WmipFindRegEntryByDevice(), WmipLeaveSMCritSection, WmipQueueRegWork(), WmipReferenceRegEntry, WmipRegisterDS(), WmipUnreferenceRegEntry, WmipUpdateDeviceStackSize(), WMIREG_FLAG_CALLBACK, WMIREG_FLAG_TRACE_NOTIFY_MASK, and WMIREG_FLAG_TRACE_PROVIDER.
Referenced by IoWMIRegistrationControl().
NTSTATUS WmipRegisterDS (PREGENTRY RegEntry)
Definition at line 1506 of file register.c.
References FALSE, PAGED_CODE, and WmipRegisterOrUpdateDS().
Referenced by WmipRegisterDevice(), and WmipRegistrationWorker().
NTSTATUS WmipRegisterOrUpdateDS (PREGENTRY RegEntry, BOOLEAN Update)
Definition at line 1399 of file register.c.
References ExAllocatePoolWithTag, ExFreePool(), FALSE, _IO_STATUS_BLOCK::Information, INITIALREGINFOSIZE, IRP_MN_REGINFO, IRP_MN_REGINFO_EX, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, _REGENTRY::ProviderId, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, UlongToPtr, WmipProcessWmiRegInfo(), WmipRegisterDSPoolTag, WmipSendWmiIrp(), WMIREGISTER, and WMIUPDATE.
Referenced by WmipRegisterDS(), and WmipUpdateDS().
void WmipRegistrationWorker (PVOID Context)
Definition at line 1526 of file register.c.
References CONTAINING_RECORD, _REGENTRY::DeviceObject, DPFLTR_WMICORE_ID, FALSE, _REGENTRY::Flags, InterlockedDecrement, IoControlPnpDeviceActionQueue(), IsListEmpty, NT_SUCCESS, PAGED_CODE, _REGISTRATIONWORKITEM::RegEntry, REGENTRY_FLAG_REG_IN_PROGRESS, RegisterSingleDriver, RegisterUpdateSingleDriver, _REGISTRATIONWORKITEM::RegOperation, RemoveHeadList(), Status, TRUE, UNREFERENCED_PARAMETER, WmipAssert, WmipDebugPrintEx, WmipEnterSMCritSection, WmipFree, WmipLeaveSMCritSection, WmipRegisterDS(), WmipRegWorkItemCount, WmipUnreferenceRegEntry, and WmipUpdateDS().
Referenced by WmipInitializeRegistration().
void WmipRemoveDS (PREGENTRY RegEntry)
Definition at line 1516 of file register.c.
References PAGED_CODE, and WmipRemoveDataSource().
Referenced by WmipDoUnreferenceRegEntry().
void WmipTranslatePDOInstanceNames (IN OUT PIRP Irp, IN UCHAR MinorFunction, IN ULONG MaxBufferSize, IN OUT PREGENTRY RegEntry)
Definition at line 885 of file register.c.
References WMIREGGUIDW::BaseNameOffset, _UNICODE_STRING::Buffer, WMIREGINFOW::BufferSize, FALSE, WMIREGGUIDW::Flags, WMIREGGUIDW::Guid, WMIREGINFOW::GuidCount, WMIREGGUIDW::InstanceCount, IoGetCurrentIrpStackLocation, IRP_MN_REGINFO_EX, IsEqualGUID, _UNICODE_STRING::Length, WMIREGINFOW::NextWmiRegInfo, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, WMIREGGUIDW::Pdo, RtlCopyMemory, RtlFreeUnicodeString(), RtlZeroMemory, Status, TRUE, WmipAssert, WmipDataProviderPnpidGuid, WmipDataProviderPnPIdInstanceNamesGuid, WmipPDOToDeviceInstanceName(), WMIREG_FLAG_INSTANCE_BASENAME, WMIREG_FLAG_INSTANCE_LIST, WMIREG_FLAG_INSTANCE_PDO, and WMIREGINFOW::WmiRegGuid.
Referenced by WmipForwardWmiIrp().
NTSTATUS WmipUpdateDS (PREGENTRY RegEntry)
Definition at line 1496 of file register.c.
References PAGED_CODE, TRUE, and WmipRegisterOrUpdateDS().
Referenced by WmipRegistrationWorker().
NTSTATUS WmipUpdateRegistration (PDEVICE_OBJECT DeviceObject)
Definition at line 617 of file register.c.
References FALSE, NULL, PAGED_CODE, RegisterUpdateSingleDriver, Status, STATUS_INVALID_PARAMETER, WmipFindRegEntryByDevice(), WmipQueueRegWork(), and WmipUnreferenceRegEntry.
Referenced by IoWMIRegistrationControl().
NTSTATUS WmipValidateWmiRegInfoString (PWMIREGINFO WmiRegInfo, ULONG BufferSize, ULONG Offset, PWCHAR * String)
Definition at line 1187 of file register.c.
References NULL, OffsetToPtr, PAGED_CODE, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by WmipBuildInstanceSet(), and WmipProcessWmiRegInfo().
void WmipWaitForIrpCompletion (PREGENTRY RegEntry)
Definition at line 304 of file register.c.
References _REGENTRY::DeviceObject, DPFLTR_WMICORE_ID, _REGENTRY::Event, Executive, FALSE, _REGENTRY::Flags, _REGENTRY::IrpCount, KernelMode, KeWaitForSingleObject(), NULL, PAGED_CODE, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, WmipAssert, and WmipDebugPrintEx.
Referenced by WmipDeregisterDevice().
Variable Documentation
const GUID WmipDataProviderPnpidGuid = DATA_PROVIDER_PNPID_GUID
Definition at line 106 of file register.c.
Referenced by WmipForwardWmiIrp(), and WmipTranslatePDOInstanceNames().
const GUID WmipDataProviderPnPIdInstanceNamesGuid = DATA_PROVIDER_PNPID_INSTANCE_NAMES_GUID
Definition at line 107 of file register.c.
Referenced by WmipForwardWmiIrp(), and WmipTranslatePDOInstanceNames().
LONG WmipInUseRegEntryCount = 0
Definition at line 99 of file register.c.
Referenced by WmipAllocRegEntry(), WmipDisableKernelTrace(), WmipDoUnreferenceRegEntry(), and WmipEnableKernelTrace().
LIST_ENTRY WmipInUseRegEntryHead = {&WmipInUseRegEntryHead,&WmipInUseRegEntryHead}
Definition at line 98 of file register.c.
Referenced by WmipDisableKernelTrace(), and WmipEnableKernelTrace().
KMUTEX WmipRegistrationMutex
Definition at line 104 of file register.c.
KSPIN_LOCK WmipRegistrationSpinLock
Definition at line 101 of file register.c.
Referenced by IoWMIWriteEvent(), WmipAllocRegEntry(), WmipDoUnreferenceRegEntry(), and WmipInitializeRegistration().
NPAGED_LOOKASIDE_LIST WmipRegLookaside
Definition at line 103 of file register.c.
Referenced by WmipAllocRegEntry(), WmipDoUnreferenceRegEntry(), and WmipInitializeRegistration().
LONG WmipRegWorkItemCount = 1
Definition at line 118 of file register.c.
Referenced by WmipInitializeRegistration(), WmipQueueRegWork(), and WmipRegistrationWorker().
LIST_ENTRY WmipRegWorkList = {&WmipRegWorkList, &WmipRegWorkList}
Definition at line 119 of file register.c.
WORK_QUEUE_ITEM WmipRegWorkQueue
Definition at line 109 of file register.c.