Windows Research Kernel v1.2: C:/Windows Research Kernel/se/tokendup.c File Reference
tokendup.c File Reference
#include "pch.h"
Macros
#define MAX(_x_, _y_) ((_x_) > (_y_) ? (_x_) : (_y_))
Functions
NTSTATUS NtDuplicateToken (__in HANDLE ExistingTokenHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN EffectiveOnly, __in TOKEN_TYPE TokenType, __out PHANDLE NewTokenHandle)
NTSTATUS NtFilterToken (__in HANDLE ExistingTokenHandle, __in ULONG Flags, __in_opt PTOKEN_GROUPS SidsToDisable, __in_opt PTOKEN_PRIVILEGES PrivilegesToDelete, __in_opt PTOKEN_GROUPS RestrictedSids, __out PHANDLE NewTokenHandle)
NTSTATUS SeCopyClientToken (__in PACCESS_TOKEN ClientToken, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, __in KPROCESSOR_MODE RequestorMode, __deref_out PACCESS_TOKEN *DuplicateToken)
NTSTATUS SeFastFilterToken (__in PACCESS_TOKEN ExistingToken, __in KPROCESSOR_MODE RequestorMode, __in ULONG Flags, __in ULONG GroupCount, __in_ecount_opt(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount_opt(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete, __in ULONG SidCount, __in_ecount_opt(SidCount) PSID_AND_ATTRIBUTES RestrictedSids, __in ULONG SidLength, __deref_out PACCESS_TOKEN *FilteredToken)
NTSTATUS SeFilterToken (__in PACCESS_TOKEN ExistingToken, __in ULONG Flags, __in_opt PTOKEN_GROUPS SidsToDisable, __in_opt PTOKEN_PRIVILEGES PrivilegesToDelete, __in_opt PTOKEN_GROUPS RestrictedSids, __deref_out PACCESS_TOKEN *NewToken)
NTSTATUS SepDuplicateToken (__in PTOKEN ExistingToken, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN EffectiveOnly, __in TOKEN_TYPE TokenType, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, __in KPROCESSOR_MODE RequestorMode, __deref_out PTOKEN *DuplicateToken)
NTSTATUS SepFilterToken (__in PTOKEN ExistingToken, __in KPROCESSOR_MODE RequestorMode, __in ULONG Flags, __in ULONG GroupCount, __in_ecount_opt(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount_opt(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete, __in ULONG SidCount, __in_ecount_opt(SidCount) PSID_AND_ATTRIBUTES RestrictedSids, __in ULONG SidLength, __deref_out PTOKEN *FilteredToken)
VOID SepMakeTokenEffectiveOnly (__in PTOKEN Token)
VOID SepRemoveDisabledGroupsAndPrivileges (__in PTOKEN Token, __in ULONG Flags, __in ULONG GroupCount, __in_ecount(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete)
BOOLEAN SepSidInSidAndAttributes (__in_ecount(SidCount) PSID_AND_ATTRIBUTES SidAndAttributes, __in ULONG SidCount, __in_opt PSID PrincipalSelfSid, __in PSID Sid)
Macro Definition Documentation
#define MAX (_x_, _y_) ((_x_) > (_y_) ? (_x_) : (_y_))
Referenced by SepFilterToken().
Function Documentation
NTSTATUS NtDuplicateToken (__in HANDLE ExistingTokenHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN EffectiveOnly, __in TOKEN_TYPE TokenType, __out PHANDLE NewTokenHandle)
Definition at line 39 of file tokendup.c.
References ARGUMENT_PRESENT, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _TOKEN::ImpersonationLevel, _SECURITY_ADVANCED_QUALITY_OF_SERVICE::ImpersonationLevel, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObInsertObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteHandle, SeCaptureSecurityQos(), SecurityAnonymous, SecurityDelegation, SecurityIdentification, SecurityImpersonation, SeFreeCapturedSecurityQos(), SepDuplicateToken(), SeTokenObjectType, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INVALID_PARAMETER, TOKEN_DUPLICATE, TokenImpersonation, TokenPrimary, and _TOKEN::TokenType.
Referenced by RtlpImpersonateSelfEx().
NTSTATUS NtFilterToken (__in HANDLE ExistingTokenHandle, __in ULONG Flags, __in_opt PTOKEN_GROUPS SidsToDisable, __in_opt PTOKEN_PRIVILEGES PrivilegesToDelete, __in_opt PTOKEN_GROUPS RestrictedSids, __out PHANDLE NewTokenHandle)
Definition at line 1365 of file tokendup.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, _OBJECT_HANDLE_INFORMATION::GrantedAccess, Index, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObInsertObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, ProbeForReadSmallStructure, ProbeForWriteHandle, SeCaptureLuidAndAttributesArray(), SeCaptureSidAndAttributesArray(), SepFilterToken(), SeReleaseLuidAndAttributesArray(), SeReleaseSidAndAttributesArray(), SeTokenObjectType, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TOKEN_DUPLICATE, and TRUE.
NTSTATUS SeCopyClientToken (__in PACCESS_TOKEN ClientToken, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, __in KPROCESSOR_MODE RequestorMode, __deref_out PACCESS_TOKEN * DuplicateToken)
Definition at line 1266 of file tokendup.c.
References FALSE, InitializeObjectAttributes, NT_SUCCESS, NULL, ObInsertObject(), PAGED_CODE, SepDuplicateToken(), Status, and TokenImpersonation.
Referenced by PsImpersonateClient(), and SepCreateClientSecurity().
NTSTATUS SeFastFilterToken (__in PACCESS_TOKEN ExistingToken, __in KPROCESSOR_MODE RequestorMode, __in ULONG Flags, __in ULONG GroupCount, __in_ecount_opt(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount_opt(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete, __in ULONG SidCount, __in_ecount_opt(SidCount) PSID_AND_ATTRIBUTES RestrictedSids, __in ULONG SidLength, __deref_out PACCESS_TOKEN * FilteredToken)
Definition at line 1859 of file tokendup.c.
References NT_SUCCESS, NULL, ObInsertObject(), SepFilterToken(), and Status.
Referenced by PsImpersonateClient().
NTSTATUS SeFilterToken (__in PACCESS_TOKEN ExistingToken, __in ULONG Flags, __in_opt PTOKEN_GROUPS SidsToDisable, __in_opt PTOKEN_PRIVILEGES PrivilegesToDelete, __in_opt PTOKEN_GROUPS RestrictedSids, __deref_out PACCESS_TOKEN * NewToken)
Definition at line 1663 of file tokendup.c.
References ARGUMENT_PRESENT, Index, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObInsertObject(), PAGED_CODE, SepFilterToken(), Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS SepDuplicateToken (__in PTOKEN ExistingToken, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN EffectiveOnly, __in TOKEN_TYPE TokenType, __in SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, __in KPROCESSOR_MODE RequestorMode, __deref_out PTOKEN * DuplicateToken)
Definition at line 334 of file tokendup.c.
References ARGUMENT_PRESENT, ASSERT, _TOKEN::AuditData, _TOKEN::AuditPolicy, _TOKEN::AuthenticationId, _ETHREAD::Cid, DbgBreakPoint(), DbgPrint(), _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, DISPATCH_LEVEL, _TOKEN::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN::DynamicPart, ExAllocateLocallyUniqueId(), ExAllocatePool, ExAllocatePoolWithTag, ExFreePool(), ExInitializeResourceLite(), _TOKEN::ExpirationTime, FALSE, FIELD_OFFSET, _TOKEN::ImpersonationLevel, Index, InterlockedIncrement, KeGetCurrentIrql(), min, _TOKEN::ModifiedId, NonPagedPool, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), _TOKEN::OriginatingLogonSession, _SEP_AUDIT_POLICY::Overlay, PAGED_CODE, PagedPool, _TOKEN::ParentTokenId, _TOKEN::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN::Privileges, _TOKEN::ProxyData, PsGetCurrentProcess(), PsGetCurrentThread(), _TOKEN::RestrictedSidCount, _TOKEN::RestrictedSids, RtlCopyMemory, RtlWalkFrameChain(), SecurityAnonymous, SecurityDelegation, SecurityIdentification, SecurityImpersonation, SeLengthSid, SepAcquireTokenReadLock, SepCopyProxyData(), SepDuplicateLogonSessionReference(), SepFreeProxyData(), SepMakeTokenEffectiveOnly(), SepModifyTokenPolicyCounter(), SepReleaseTokenReadLock, _TOKEN::SessionId, SeTokenObjectType, _SID_AND_ATTRIBUTES::Sid, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INSUFFICIENT_RESOURCES, TOKEN_SESSION_NOT_REFERENCED, _TOKEN::TokenFlags, _TOKEN::TokenId, TokenImpersonation, _TOKEN::TokenInUse, _TOKEN::TokenLock, _TOKEN::TokenSource, _TOKEN::TokenType, TokenType, TRUE, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, _TOKEN::UserAndGroupCount, _TOKEN::UserAndGroups, _TOKEN::VariableLength, and _TOKEN::VariablePart.
Referenced by NtDuplicateToken(), NtOpenThreadTokenEx(), SeCopyClientToken(), and SeSubProcessToken().
NTSTATUS SepFilterToken (__in PTOKEN ExistingToken, __in KPROCESSOR_MODE RequestorMode, __in ULONG Flags, __in ULONG GroupCount, __in_ecount_opt(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount_opt(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete, __in ULONG SidCount, __in_ecount_opt(SidCount) PSID_AND_ATTRIBUTES RestrictedSids, __in ULONG SidLength, __deref_out PTOKEN * FilteredToken)
Definition at line 1971 of file tokendup.c.
References ARGUMENT_PRESENT, ASSERT, _SID_AND_ATTRIBUTES::Attributes, _TOKEN::AuditData, _TOKEN::AuditPolicy, _TOKEN::AuthenticationId, _ETHREAD::Cid, DbgBreakPoint(), DbgPrint(), _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, DISPATCH_LEVEL, _TOKEN::DynamicAvailable, _TOKEN::DynamicCharged, _TOKEN::DynamicPart, ExAllocateLocallyUniqueId(), ExAllocatePool, ExAllocatePoolWithTag, ExFreePool(), ExInitializeResourceLite(), _TOKEN::ExpirationTime, FALSE, FIELD_OFFSET, _TOKEN::ImpersonationLevel, Index, InitializeObjectAttributes, InterlockedIncrement, KeGetCurrentIrql(), MAX, min, _TOKEN::ModifiedId, NonPagedPool, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), _TOKEN::OriginatingLogonSession, _SEP_AUDIT_POLICY::Overlay, PAGED_CODE, PagedPool, _TOKEN::ParentTokenId, _TOKEN::PrimaryGroup, _TOKEN::PrivilegeCount, _TOKEN::Privileges, _TOKEN::ProxyData, PsGetCurrentProcess(), PsGetCurrentThread(), _TOKEN::RestrictedSidCount, _TOKEN::RestrictedSids, RtlCopyLuidAndAttributesArray(), RtlCopyMemory, RtlCopySidAndAttributesArray(), RtlWalkFrameChain(), SANDBOX_INERT, SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SeLengthSid, SepAcquireTokenReadLock, SepCopyProxyData(), SepDuplicateLogonSessionReference(), SepFreeProxyData(), SepModifyTokenPolicyCounter(), SepReleaseTokenReadLock, SepRemoveDisabledGroupsAndPrivileges(), SepSidInSidAndAttributes(), _TOKEN::SessionId, SeTokenObjectType, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, TOKEN_IS_RESTRICTED, TOKEN_SANDBOX_INERT, TOKEN_SESSION_NOT_REFERENCED, _TOKEN::TokenFlags, _TOKEN::TokenId, _TOKEN::TokenInUse, _TOKEN::TokenLock, _TOKEN::TokenSource, _TOKEN::TokenType, TRUE, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, _TOKEN::UserAndGroupCount, _TOKEN::UserAndGroups, _TOKEN::VariableLength, and _TOKEN::VariablePart.
Referenced by NtFilterToken(), SeFastFilterToken(), and SeFilterToken().
VOID SepMakeTokenEffectiveOnly (__in PTOKEN Token)
Definition at line 829 of file tokendup.c.
References ASSERT, Index, PAGED_CODE, RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_USE_FOR_DENY_ONLY, SE_PRIVILEGE_ENABLED, SeAliasAdminsSid, SepTokenGroupAttributes, SepTokenPrivilegeAttributes, and TOKEN_HAS_ADMIN_GROUP.
Referenced by SepDuplicateToken().
VOID SepRemoveDisabledGroupsAndPrivileges (__in PTOKEN Token, __in ULONG Flags, __in ULONG GroupCount, __in_ecount(GroupCount) PSID_AND_ATTRIBUTES GroupsToDisable, __in ULONG PrivilegeCount, __in_ecount(PrivilegeCount) PLUID_AND_ATTRIBUTES PrivilegesToDelete)
Definition at line 1064 of file tokendup.c.
References ASSERT, DISABLE_MAX_PRIVILEGE, FALSE, Index, NULL, PAGED_CODE, RtlEqualLuid, RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_USE_FOR_DENY_ONLY, SeAliasAdminsSid, SeChangeNotifyPrivilege, SeImpersonatePrivilege, SepSidInSidAndAttributes(), TOKEN_HAS_ADMIN_GROUP, TOKEN_HAS_IMPERSONATE_PRIVILEGE, TOKEN_HAS_TRAVERSE_PRIVILEGE, and TRUE.
Referenced by SepFilterToken().
BOOLEAN SepSidInSidAndAttributes (__in_ecount(SidCount) PSID_AND_ATTRIBUTES SidAndAttributes, __in ULONG SidCount, __in_opt PSID PrincipalSelfSid, __in PSID Sid)
Definition at line 956 of file tokendup.c.
References ARGUMENT_PRESENT, FALSE, NULL, PAGED_CODE, _SID::Revision, RtlEqualMemory, RtlEqualSid(), SePrincipalSelfSid, _SID_AND_ATTRIBUTES::Sid, _SID::SubAuthorityCount, and TRUE.
Referenced by SepFilterToken(), and SepRemoveDisabledGroupsAndPrivileges().