Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/allocpag.c File Reference
allocpag.c File Reference
#include "mi.h"
Data Structures
struct _MI_LARGE_PAGE_RANGES
Macros
#define ANY_COLOR_OK 0xFFFFFFFF
#define MI_MAX_LARGE_PAGE_RANGES 64
#define MiInsertContiguousTag(a, b, c) (c) = (c)
#define MM_SMALL_ALLOCATIONS 4
Typedefs
typedef struct _MI_LARGE_PAGE_RANGES MI_LARGE_PAGE_RANGES
typedef enum _MM_POOL_FAILURE_REASONS MM_POOL_FAILURE_REASONS
typedef enum _MM_POOL_PRIORITIES MM_POOL_PRIORITIES
typedef enum _MM_POOL_TYPES MM_POOL_TYPES
typedef enum _MM_PREEMPTIVE_TRIMS MM_PREEMPTIVE_TRIMS
typedef struct _MI_LARGE_PAGE_RANGES * PMI_LARGE_PAGE_RANGES
Enumerations
enum _MM_POOL_FAILURE_REASONS {
MmNonPagedNoPtes, MmPriorityTooLow, MmNonPagedNoPagesAvailable, MmPagedNoPtes,
MmSessionPagedNoPtes, MmPagedNoPagesAvailable, MmSessionPagedNoPagesAvailable, MmPagedNoCommit,
MmSessionPagedNoCommit, MmNonPagedNoResidentAvailable, MmNonPagedNoCommit, MmMaximumFailureReason
}
enum _MM_POOL_PRIORITIES { MmHighPriority, MmNormalPriority, MmLowPriority, MmMaximumPoolPriority }
enum _MM_POOL_TYPES { MmNonPagedPool, MmPagedPool, MmSessionPagedPool, MmMaximumPoolType }
enum _MM_PREEMPTIVE_TRIMS {
MmPreemptForNonPaged, MmPreemptForPaged, MmPreemptForNonPagedPriority, MmPreemptForPagedPriority,
MmMaximumPreempt
}
Functions
LOGICAL MiAddCachedRange (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER LastPageFrameIndex)
VOID MiAddExpansionNonPagedPool (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN LOGICAL PfnHeld)
PVOID MiAllocatePoolPages (IN POOL_TYPE PoolType, IN SIZE_T SizeInBytes)
VOID MiCheckSessionPoolAllocations (VOID)
PVOID MiFindContiguousMemory (IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN PFN_NUMBER SizeInPages, IN MEMORY_CACHING_TYPE CacheType, IN PVOID CallingAddress)
PVOID MiFindContiguousMemoryInPool (IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN PFN_NUMBER SizeInPages, IN PVOID CallingAddress)
PFN_NUMBER MiFindContiguousPages (IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN PFN_NUMBER SizeInPages, IN MEMORY_CACHING_TYPE CacheType)
PFN_NUMBER MiFindLargePageMemory (IN PCOLORED_PAGE_INFO ColoredPageInfoBase, IN PFN_NUMBER SizeInPages, IN MM_PROTECTION_MASK ProtectionMask, OUT PPFN_NUMBER OutZeroCount)
LOGICAL MiFreeAllExpansionNonPagedPool (VOID)
VOID MiFreeContiguousPages (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER SizeInPages)
VOID MiFreeLargePageMemory (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER SizeInPages)
VOID MiFreeNonPagedPool (IN PVOID StartingAddress, IN PFN_NUMBER NumberOfPages)
ULONG MiFreePoolPages (IN PVOID StartingAddress)
VOID MiFreeSessionPoolBitMaps (VOID)
NTSTATUS MiInitializeAndChargePfn (OUT PPFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PFN_NUMBER ContainingPageFrame, IN LOGICAL SessionAllocation)
VOID MiInitializeNonPagedPool (VOID)
VOID MiInitializePoolEvents (VOID)
NTSTATUS MiInitializeSessionPool (VOID)
LOGICAL MiIsPoolLargeSession (IN PVOID VirtualAddress)
VOID MiMarkPoolLargeSession (IN PVOID VirtualAddress)
LOGICAL MiMustFrameBeCached (IN PFN_NUMBER PageFrameIndex)
VOID MiProtectedPoolInsertList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY Entry, IN LOGICAL InsertHead)
VOID MiProtectedPoolRemoveEntryList (IN PLIST_ENTRY Entry)
VOID MiProtectFreeNonPagedPool (IN PVOID VirtualAddress, IN ULONG SizeInPages)
VOID MiRemoveCachedRange (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER LastPageFrameIndex)
VOID MiSessionPageTableRelease (IN PFN_NUMBER PageFrameIndex)
PVOID MiSessionPoolVector (VOID)
VOID MiSyncCachedRanges (VOID)
VOID MiTrimSegmentCache (VOID)
LOGICAL MiUnProtectFreeNonPagedPool (IN PVOID VirtualAddress, IN ULONG SizeInPages)
SIZE_T MmAvailablePoolInPages (IN POOL_TYPE PoolType)
POOL_TYPE MmDeterminePoolType (IN PVOID VirtualAddress)
ULONG MmGetSizeOfBigPoolAllocation (IN PVOID StartingAddress)
LOGICAL MmIsSessionAddress (IN PVOID VirtualAddress)
LOGICAL MmResourcesAvailable (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN EX_POOL_PRIORITY Priority)
Variables
PMMPFN MiCachedNonPagedPool
PFN_NUMBER MiCachedNonPagedPoolCount
PFN_NUMBER MiEndOfInitialPoolFrame
PFN_NUMBER MiExpansionPoolPagesInitialCharge
PFN_NUMBER MiExpansionPoolPagesInUse
ULONG MiLargePageRangeIndex
MI_LARGE_PAGE_RANGES MiLargePageRanges [MI_MAX_LARGE_PAGE_RANGES]
SLIST_HEADER MiNonPagedPoolSListHead
ULONG MiNonPagedPoolSListMaximum = 4
SLIST_HEADER MiPagedPoolSListHead
ULONG MiPagedPoolSListMaximum = 8
PFN_NUMBER MiStartOfInitialPoolFrame
PFN_NUMBER MmAllocatedNonPagedPool
PFN_NUMBER MmFreedExpansionPoolMaximum
PVOID MmNonPagedPoolEnd0
PVOID MmNonPagedPoolExpansionStart
LIST_ENTRY MmNonPagedPoolFreeListHead [MI_MAX_FREE_LIST_HEADS]
ULONG MmPagedPoolCommit
KGUARDED_MUTEX MmPagedPoolMutex
ULONG MmPoolFailureReasons [MmMaximumFailureReason]
ULONG MmPoolFailures [MmMaximumPoolType][MmMaximumPoolPriority]
ULONG MmPreemptiveTrims [MmMaximumPreempt]
ULONG MmUnusedSegmentForceFree
ULONG MmUnusedSegmentForceFreeDefault = 30
POOL_DESCRIPTOR NonPagedPoolDescriptor
Macro Definition Documentation
#define ANY_COLOR_OK 0xFFFFFFFF
Referenced by MiFindLargePageMemory().
#define MI_MAX_LARGE_PAGE_RANGES 64
Definition at line 6267 of file allocpag.c.
Referenced by MiAddCachedRange(), and MiRemoveCachedRange().
#define MiInsertContiguousTag (a, b, c) (c) = (c)
Definition at line 4248 of file allocpag.c.
Referenced by MiFindContiguousMemory(), and MiFindContiguousMemoryInPool().
#define MM_SMALL_ALLOCATIONS 4
Definition at line 82 of file allocpag.c.
Referenced by MiFreePoolPages().
Typedef Documentation
typedef struct _MI_LARGE_PAGE_RANGES MI_LARGE_PAGE_RANGES
typedef enum _MM_POOL_FAILURE_REASONS MM_POOL_FAILURE_REASONS
typedef enum _MM_POOL_PRIORITIES MM_POOL_PRIORITIES
typedef enum _MM_POOL_TYPES MM_POOL_TYPES
typedef enum _MM_PREEMPTIVE_TRIMS MM_PREEMPTIVE_TRIMS
typedef struct _MI_LARGE_PAGE_RANGES * PMI_LARGE_PAGE_RANGES
Enumeration Type Documentation
enum _MM_POOL_FAILURE_REASONS
Enumerator
MmNonPagedNoPtes
MmPriorityTooLow
MmNonPagedNoPagesAvailable
MmPagedNoPtes
MmSessionPagedNoPtes
MmPagedNoPagesAvailable
MmSessionPagedNoPagesAvailable
MmPagedNoCommit
MmSessionPagedNoCommit
MmNonPagedNoResidentAvailable
MmNonPagedNoCommit
MmMaximumFailureReason
Definition at line 128 of file allocpag.c.
enum _MM_POOL_PRIORITIES
Enumerator
MmHighPriority
MmNormalPriority
MmLowPriority
MmMaximumPoolPriority
Definition at line 121 of file allocpag.c.
enum _MM_POOL_TYPES
Enumerator
MmNonPagedPool
MmPagedPool
MmSessionPagedPool
MmMaximumPoolType
Definition at line 114 of file allocpag.c.
enum _MM_PREEMPTIVE_TRIMS
Enumerator
MmPreemptForNonPaged
MmPreemptForPaged
MmPreemptForNonPagedPriority
MmPreemptForPagedPriority
MmMaximumPreempt
Definition at line 146 of file allocpag.c.
Function Documentation
LOGICAL MiAddCachedRange (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER LastPageFrameIndex)
Definition at line 6389 of file allocpag.c.
References ASSERT, _RTL_BITMAP::Buffer, FALSE, _MI_LARGE_PAGE_RANGES::LastFrame, LOCK_PFN, MI_IS_PFN(), MI_MAX_LARGE_PAGE_RANGES, MI_PFN_ELEMENT, MiLargePageRangeIndex, MiPfnBitMap, _MMPFN::MustBeCached, NULL, _MI_LARGE_PAGE_RANGES::StartFrame, TRUE, _MMPFN::u4, and UNLOCK_PFN.
Referenced by MiComputeInitialLargePage(), MiReportPhysicalMemory(), and MiUseLargeDriverPage().
VOID MiAddExpansionNonPagedPool (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN LOGICAL PfnHeld)
Definition at line 3602 of file allocpag.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPFN::EntireFrame, _MMPFN::Event, FALSE, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MiCached, MiCachedNonPagedPool, MiCachedNonPagedPoolCount, MiGetPteAddress, MM_DEMAND_ZERO_WRITE_PTE, MM_NOIRQL, MmNonPagedPoolExpansionStart, _MMPFN::MustBeCached, _MMPFN::OriginalPte, _MMPFNENTRY::PageColor, _MMPFNENTRY::PageLocation, _MMPFN::PteAddress, _MMPFN::PteFrame, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, and _MMPFN::VerifierAllocation.
Referenced by MiFreeInitializationCode(), MiInitMachineDependent(), and MxConvertToLargePage().
PVOID MiAllocatePoolPages (IN POOL_TYPE PoolType, IN SIZE_T SizeInBytes)
Definition at line 1189 of file allocpag.c.
References _4gb, ActiveAndValid, _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, BASE_POOL_TYPE_MASK, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, _MM_SESSION_SPACE::CommittedPages, CONTAINING_RECORD, _MMPFN::e1, _MMPFN::e2, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MMPFN::Event, ExQueryDepthSList, FALSE, _MM_PAGED_POOL_INFO::FirstPteForPagedPool, _LIST_ENTRY::Flink, _MMPTE::Hard, _KEVENT::Header, Index, InsertTailList(), InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedPopEntrySList(), KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeClearEvent(), KeIsExecutingDpc(), KeQueryTickCount(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), _MM_PAGED_POOL_INFO::LastPteForPagedPool, List, _MMFREE_POOL_ENTRY::List, LOCK_PFN, LOCK_PFN2, LOCK_PFN_AT_DPC, LockQueueMmNonPagedPoolLock, _MMPTE::Long, _LARGE_INTEGER::LowPart, MI_ADD_EXECUTE_TO_INVALID_PTE_IF_PAE, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_CONVERT_PHYSICAL_TO_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_MAX_FREE_LIST_HEADS, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_UNUSED_SEGMENTS_SURPLUS, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiCached, MiCachedNonPagedPool, MiCachedNonPagedPoolCount, MiChargeCommitmentCantExpand(), MiCompareTbFlushTimeStamp(), MiExpansionPoolPagesInitialCharge, MiExpansionPoolPagesInUse, MiFreeAllExpansionNonPagedPool(), MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiHighNonPagedPoolEvent, MiHighNonPagedPoolThreshold, MiHighPagedPoolEvent, MiHighPagedPoolThreshold, MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), MiIssuePageExtendRequestNoWait(), MiLowNonPagedPoolEvent, MiLowNonPagedPoolThreshold, MiLowPagedPoolEvent, MiLowPagedPoolThreshold, MiProtectedPoolInsertList(), MiProtectedPoolRemoveEntryList(), MiProtectFreeNonPagedPool(), MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiReturnCommitment, MiTrimSegmentCache(), MiUnProtectFreeNonPagedPool(), MiZeroMemoryPte, MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_NONPAGED_POOL_EXPANSION, MM_DBG_COMMIT_PAGED_POOL_PAGES, MM_DBG_COMMIT_PAGED_POOL_PAGETABLE, MM_DBG_SESSION_COMMIT_PAGEDPOOL_PAGES, MM_DBG_SESSION_NP_PAGETABLE_ALLOC, MM_DBG_SESSION_PAGEDPOOL_PAGETABLE_ALLOC1, MM_DEMAND_ZERO_WRITE_PTE, MM_FREE_POOL_SIGNATURE, MM_KERNEL_DEMAND_ZERO_PTE, MM_MAXIMUM_FLUSH_COUNT, MM_PAGED_POOL_LOCKED_DOWN, MM_RESAVAIL_ALLOCATE_EXPANSION_NONPAGED_POOL, MM_RESAVAIL_ALLOCATE_PAGETABLES_FOR_PAGED_POOL, MM_TRACK_COMMIT, MmAllocatedNonPagedPool, MmAvailablePages, MmDisablePagingExecutive, MmHighPriority, MmMaximumNonPagedPoolInPages, MmNonPagedNoCommit, MmNonPagedNoPagesAvailable, MmNonPagedNoPtes, MmNonPagedNoResidentAvailable, MmNonPagedPool, MmNumberOfFreeNonPagedPool, MmPagedNoCommit, MmPagedNoPagesAvailable, MmPagedNoPtes, MmPagedPool, MmPagedPoolCommit, MmPagedPoolInfo, MmPagedPoolStart, MmPfnDatabase, MmPoolFailureReasons, MmPoolFailures, MmPreemptForNonPaged, MmPreemptForPaged, MmPreemptiveTrims, MmProtectFreedNonPagedPool, MmSessionBase, MmSessionPagedNoCommit, MmSessionPagedNoPagesAvailable, MmSessionPagedNoPtes, MmSessionPagedPool, MmSessionSpace, MmSizeOfPagedPoolInPages, MmSystemPageDirectory, MmSystemPagePtes, MmUnusedSegmentCleanup, _MMPFN::MustBeCached, _MM_PAGED_POOL_INFO::NextPdeForPagedPoolExpansion, NO_BITS_FOUND, _MM_SESSION_SPACE::NonPageablePages, NonPagedPool, NonPagedPoolExpansion, NOTHING, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_PAGED_POOL_INFO::PagedPoolCommit, _MM_PAGED_POOL_INFO::PagedPoolHint, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MM_SESSION_SPACE::PageTables, PD_PER_SYSTEM, PDE_PER_PAGE, POOL_VERIFIER_MASK, PsGetCurrentThread(), PTE_PER_PAGE, _MMPFN::PteAddress, _MMPFN::PteFrame, RemoveEntryList(), RtlClearBits(), RtlFindClearBitsAndSet(), RtlSetBit(), SESSION_GLOBAL, SESSION_POOL_MASK, _MM_SESSION_SPACE::SessionPageDirectoryIndex, _MM_SESSION_SPACE::SessionPoolAllocationFailures, _MMPFN::ShareCount, _DISPATCHER_HEADER::SignalState, _MMFREE_POOL_ENTRY::Signature, _MMFREE_POOL_ENTRY::Size, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_PFN2, UNLOCK_PFN_FROM_DPC, _MMPTE_HARDWARE::Valid, ValidKernelPde, ValidKernelPdeLocal, ValidKernelPte, _MMPFN::VerifierAllocation, and VerifierLargePagedPoolMap.
Referenced by __bcount(), ExGetBigPoolInfo(), ExpExpandBigPageTable(), ExpInsertPoolTrackerExpansion(), and InitializePool().
VOID MiCheckSessionPoolAllocations (VOID)
Definition at line 3668 of file allocpag.c.
References ASSERT, _MMPTE::Hard, KeBugCheckEx(), _POOL_TRACKER_TABLE::Key, _MMPTE::Long, MiGetPdeAddress, MiGetVirtualAddressMappedByPte, MiSessionPoolTrackTable(), MiSessionPoolTrackTableSize(), MM_NOACCESS, MmSessionSpace, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, PAGED_CODE, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, _MM_SESSION_SPACE::PagedPool, _MM_SESSION_SPACE::PagedPoolEnd, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_SOFTWARE::Protection, PTE_PER_PAGE, _POOL_DESCRIPTOR::RunningAllocs, _POOL_DESCRIPTOR::RunningDeAllocs, SESSION_HAS_VALID_POOL_ON_EXIT, _MM_SESSION_SPACE::SessionId, _MMPTE::Soft, _POOL_DESCRIPTOR::TotalBigPages, _POOL_DESCRIPTOR::TotalPages, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiDereferenceSessionFinal().
PVOID MiFindContiguousMemory (IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN PFN_NUMBER SizeInPages, IN MEMORY_CACHING_TYPE CacheType, IN PVOID CallingAddress)
Definition at line 5248 of file allocpag.c.
References ASSERT, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_TRANSLATE_CACHETYPE(), MiCached, MiFindContiguousMemoryInPool(), MiFindContiguousPages(), MiFreeContiguousPages(), MiGetPteAddress, MiInsertContiguousTag, MM_DBG_COMMIT_CONTIGUOUS_PAGES, MM_TRACK_COMMIT, NULL, PAGE_SHIFT, PAGED_CODE, _MMPFN::PteAddress, _MMPFN::PteFrame, _LARGE_INTEGER::QuadPart, and _MMPFN::u4.
Referenced by MiAllocateContiguousMemory().
PVOID MiFindContiguousMemoryInPool (IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN PFN_NUMBER SizeInPages, IN PVOID CallingAddress)
Definition at line 4253 of file allocpag.c.
References ASSERT, CONTAINING_RECORD, _MMPFN::e1, ExFreePool(), ExInsertPoolTag(), ExPageLockHandle, FALSE, _LIST_ENTRY::Flink, _MMPTE::Hard, _KEVENT::Header, Index, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, KeAcquireQueuedSpinLock(), KeClearEvent(), KeReleaseQueuedSpinLock(), KeSetEvent(), List, _MMFREE_POOL_ENTRY::List, LockQueueMmNonPagedPoolLock, MI_CONVERT_PHYSICAL_TO_PFN, MI_IS_PHYSICAL_ADDRESS, MI_MAX_FREE_LIST_HEADS, MI_PFN_ELEMENT, MiCached, MiCheckForContiguousMemory(), MiGetPteAddress, MiHighNonPagedPoolEvent, MiHighNonPagedPoolThreshold, MiInsertContiguousTag, MiLowNonPagedPoolEvent, MiLowNonPagedPoolThreshold, MiProtectedPoolRemoveEntryList(), MiProtectFreeNonPagedPool(), MiUnProtectFreeNonPagedPool(), MM_FREE_POOL_SIGNATURE, MmAllocatedNonPagedPool, MmLockPageableSectionByHandle(), MmMaximumNonPagedPoolInPages, MmNumberOfFreeNonPagedPool, MmProtectFreedNonPagedPool, MmUnlockPageableImageSection(), NonPagedPool, NULL, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, RemoveEntryList(), _DISPATCHER_HEADER::SignalState, _MMFREE_POOL_ENTRY::Signature, _MMFREE_POOL_ENTRY::Size, _POOL_DESCRIPTOR::TotalBigPages, _POOL_DESCRIPTOR::TotalBytes, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, _MMPTE_HARDWARE::Valid, and _MMPFN::VerifierAllocation.
Referenced by MiFindContiguousMemory().
PFN_NUMBER MiFindContiguousPages (IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN PFN_NUMBER SizeInPages, IN MEMORY_CACHING_TYPE CacheType)
Definition at line 4710 of file allocpag.c.
References ActiveAndValid, ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, _MMPFN::Blink, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFN::Flink, InitializationPhase, InterlockedDecrement, InterlockedIncrement, KeDelayExecutionThread(), KeEnterGuardedRegionThread(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), KernelMode, LOCK_PFN, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_DEFER_PFN_HELD, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_TRANSLATE_CACHETYPE(), MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MiCached, MiChargeCommitmentCantExpand(), MiDeferredUnlockPages(), MiDelayPageFaults, MiFlushAllPages(), MiGetPteAddress, MiPurgeTransitionList(), MiRestoreTransitionPte(), MiReturnCommitment, MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MM_DBG_COMMIT_CONTIGUOUS_PAGES, MM_DEMAND_ZERO_WRITE_PTE, MM_HIGH_LIMIT, MM_RESAVAIL_ALLOCATE_CONTIGUOUS, MM_RESAVAIL_FREE_CONTIGUOUS, MM_TRACK_COMMIT, MmAvailablePages, MmEmptyAllWorkingSets(), MmHalfSecond, MmNonPagedPoolExpansionStart, MmOneSecond, MmPfnDatabase, MmPhysicalMemoryBlock, _MMPFN::MustBeCached, NOTHING, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _MMPFN::OriginalPte, _PHYSICAL_MEMORY_RUN::PageCount, PAGED_CODE, _MMPFNENTRY::PageLocation, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _PHYSICAL_MEMORY_DESCRIPTOR::Run, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPFN::VerifierAllocation.
Referenced by MiFindContiguousMemory(), and MiUseLargeDriverPage().
PFN_NUMBER MiFindLargePageMemory (IN PCOLORED_PAGE_INFO ColoredPageInfoBase, IN PFN_NUMBER SizeInPages, IN MM_PROTECTION_MASK ProtectionMask, OUT PPFN_NUMBER OutZeroCount)
Definition at line 5375 of file allocpag.c.
References ActiveAndValid, ANY_COLOR_OK, ASSERT, _MMPFN::AweAllocation, _PHYSICAL_MEMORY_RUN::BasePage, _MMPFN::Blink, _MMPFNENTRY::CacheAttribute, CacheType, DbgBreakPoint(), DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMPFN::e2, _MMPFN::EntireFrame, FALSE, _MMPFN::Flink, KeEnterGuardedRegionThread(), KeFeatureBits, KeGetCurrentPrcb(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), KeNumberNodes, KF_LARGE_PAGE, LOCK_PFN, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_DEFER_PFN_HELD, MI_FLUSH_ENTIRE_TB_FOR_ATTRIBUTE_CHANGE, MI_GET_COLOR_FROM_LIST_ENTRY, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_NOCACHE, MI_IS_WRITECOMBINE, MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_MAGIC_AWE_PTEFRAME, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_ROUND_TO_SIZE, MI_SET_PFN_DELETED, MI_TRANSLATE_CACHETYPE(), MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MiDeferredUnlockPages(), MiRestoreTransitionPte(), MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MM_DBG_COMMIT_CHARGE_LARGE_PAGES, MM_DEMAND_ZERO_WRITE_PTE, MM_HIGH_LIMIT, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_RESAVAIL_ALLOCATE_LARGE_PAGES, MM_RESAVAIL_FREE_LARGE_PAGES, MM_TRACK_COMMIT, MM_VA_MAPPED_BY_PDE, MmAvailablePages, MmCached, MmNonCached, MmPhysicalMemoryBlock, MmWriteCombined, _KPRCB::NodeColor, NOTHING, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _MMPFN::OriginalPte, PAGE_SHIFT, _MMPFNENTRY::PageColor, _PHYSICAL_MEMORY_RUN::PageCount, PAGED_CODE, _MMPFNENTRY::PageLocation, _COLORED_PAGE_INFO::PagesQueued, _COLORED_PAGE_INFO::PfnAllocation, _MMPFNENTRY::PrototypePte, _MMPFN::PteFrame, _PHYSICAL_MEMORY_DESCRIPTOR::Run, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPFN::VerifierAllocation, and ZeroedPageList.
Referenced by MiAllocateLargeZeroPages().
LOGICAL MiFreeAllExpansionNonPagedPool (VOID)
Definition at line 968 of file allocpag.c.
References ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, Index, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), List, _MMFREE_POOL_ENTRY::List, LockQueueMmNonPagedPoolLock, MI_IS_PHYSICAL_ADDRESS, MI_MAX_FREE_LIST_HEADS, MiFreeNonPagedPool(), MiProtectedPoolRemoveEntryList(), MiProtectFreeNonPagedPool(), MiUnProtectFreeNonPagedPool(), MmNonPagedPoolExpansionStart, MmNumberOfFreeNonPagedPool, MmProtectFreedNonPagedPool, RemoveEntryList(), _MMFREE_POOL_ENTRY::Size, and TRUE.
Referenced by MiAllocatePoolPages().
VOID MiFreeContiguousPages (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER SizeInPages)
Definition at line 5183 of file allocpag.c.
References APC_LEVEL, ASSERT, _MMPFN::e1, KeGetCurrentIrql(), LOCK_PFN2, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), and _MMPFN::u3.
Referenced by MiFindContiguousMemory(), MiReloadBootLoadedDrivers(), MiUseLargeDriverPage(), and MmUnloadSystemImage().
VOID MiFreeLargePageMemory (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER SizeInPages)
Definition at line 5837 of file allocpag.c.
References ActiveAndValid, ASSERT, _MMPFN::AweAllocation, _MMPFN::AweReferenceCount, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, FALSE, InterlockedCompareExchange(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), LOCK_PFN, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_IS_PFN_DELETED, MI_PFN_ELEMENT, MiCached, MiChargeCommitmentCantExpand(), MiDecrementReferenceCountForAwePage(), PAGED_CODE, _MMPFNENTRY::PageLocation, _MMPFNENTRY::PrototypePte, ReadForWriteAccess, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPFN::VerifierAllocation.
Referenced by MiFreeLargePages().
VOID MiFreeNonPagedPool (IN PVOID StartingAddress, IN PFN_NUMBER NumberOfPages)
Definition at line 857 of file allocpag.c.
References ASSERT, _MMPFN::e1, LOCK_PFN_AT_DPC, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiDecrementReferenceCount(), MiExpansionPoolPagesInitialCharge, MiExpansionPoolPagesInUse, MiGetPteAddress, MiReleaseSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_RETURN_NONPAGED_POOL_EXPANSION, MM_RESAVAIL_FREE_EXPANSION_NONPAGED_POOL, MM_TRACK_COMMIT, NonPagedPoolExpansion, _MMPFNENTRY::PageLocation, _MMPFN::ShareCount, StandbyPageList, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN_FROM_DPC.
Referenced by MiFreeAllExpansionNonPagedPool(), and MiFreePoolPages().
ULONG MiFreePoolPages (IN PVOID StartingAddress)
Definition at line 2422 of file allocpag.c.
References ActiveAndValid, _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, BAD_POOL_CALLER, _RTL_BITMAP::Buffer, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, _MM_SESSION_SPACE::CommittedPages, _MMPFN::e1, _MMPFN::e2, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MMPFN::Event, ExQueryDepthSList, FALSE, _MM_PAGED_POOL_INFO::FirstPteForPagedPool, _MMPTE::Hard, _KEVENT::Header, Index, InsertTailList(), InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedPushEntrySList(), KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeBugCheckEx(), KeClearEvent(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), _MMFREE_POOL_ENTRY::List, LOCK_PFN2, LockQueueMmNonPagedPoolLock, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CHECK_BIT, MI_CLEAR_BIT, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_POOL_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_MAX_FREE_LIST_HEADS, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiBadRefCount(), MiCached, MiCachedNonPagedPoolCount, MiDeferredUnlockPages(), MiDeleteSystemPageableVm(), MiEndOfInitialPoolFrame, MiExpansionPoolPagesInitialCharge, MiExpansionPoolPagesInUse, MiFreeNonPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiHighNonPagedPoolEvent, MiHighNonPagedPoolThreshold, MiHighPagedPoolEvent, MiHighPagedPoolThreshold, MiLowNonPagedPoolEvent, MiLowNonPagedPoolThreshold, MiLowPagedPoolEvent, MiLowPagedPoolThreshold, MiNonPagedPoolSListMaximum, MiPagedPoolSListMaximum, MiProtectedPoolInsertList(), MiProtectedPoolRemoveEntryList(), MiProtectFreeNonPagedPool(), MiReleaseSystemPtes(), MiReturnCommitment, MiStartOfInitialPoolFrame, MiUnProtectFreeNonPagedPool(), MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_RETURN_PAGED_POOL_PAGES, MM_DBG_SESSION_COMMIT_POOL_FREED, MM_DEMAND_ZERO_WRITE_PTE, MM_FREE_POOL_SIGNATURE, MM_PAGED_POOL_LOCKED_DOWN, MM_SMALL_ALLOCATIONS, MM_SYSTEM_RANGE_START, MM_TRACK_COMMIT, MmAllocatedNonPagedPool, MmDisablePagingExecutive, MmFreedExpansionPoolMaximum, MmHighestPhysicalPage, MmMaximumNonPagedPoolInPages, MmNonPagedPoolEnd, MmNonPagedPoolEnd0, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmNumberOfFreeNonPagedPool, MmPagedPoolCommit, MmPagedPoolEnd, MmPagedPoolInfo, MmPagedPoolMutex, MmPagedPoolStart, MmPfnDeferredList, MmProtectFreedNonPagedPool, MmResidentAvailablePages, MmSessionSpace, MmSizeOfNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, MmSizeOfPagedPoolInPages, _MMPFN::MustBeCached, NonPagedPool, NonPagedPoolExpansion, NOTHING, NULL, _MMPFN::OriginalPte, _MMFREE_POOL_ENTRY::Owner, PAGE_SHIFT, PAGE_SIZE, PagedPool, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_PAGED_POOL_INFO::PagedPoolCommit, _MM_PAGED_POOL_INFO::PagedPoolHint, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PSLIST_ENTRY, _MMPFN::PteFrame, RemoveEntryList(), RtlCheckBit, RtlClearBit(), RtlClearBits(), RtlFillMemoryUlong(), SATISFY_OVERZEALOUS_COMPILER, SESSION_GLOBAL, _MMPFN::ShareCount, _DISPATCHER_HEADER::SignalState, _MMFREE_POOL_ENTRY::Signature, _MMFREE_POOL_ENTRY::Size, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, _MMPFN::VerifierAllocation, VerifierFreeTrackedPool(), VerifierLargePagedPoolMap, and _MMPFNENTRY::WriteInProgress.
Referenced by ExDeferredFreePool(), ExFreePoolWithTag(), ExGetBigPoolInfo(), ExpExpandBigPageTable(), and ExpInsertPoolTrackerExpansion().
VOID MiFreeSessionPoolBitMaps (VOID)
Definition at line 4165 of file allocpag.c.
References _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, ExFreePool(), MmSessionSpace, NULL, PAGED_CODE, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, and _MM_SESSION_SPACE::PagedPoolInfo.
Referenced by MiDereferenceSessionFinal(), MiInitializeSessionPool(), and MiSessionCreateInternal().
NTSTATUS MiInitializeAndChargePfn (OUT PPFN_NUMBER PageFrameIndex, IN PMMPTE PointerPde, IN PFN_NUMBER ContainingPageFrame, IN LOGICAL SessionAllocation)
Definition at line 3828 of file allocpag.c.
References ASSERT, _MMPTE::Hard, LOCK_PFN2, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_WRITE_VALID_PTE, MiInitializePfnForOtherProcess(), MiRemoveZeroPage(), MM_MEDIUM_LIMIT, MM_RESAVAIL_ALLOCATE_SINGLE_PFN, MmAvailablePages, _MMPTE_HARDWARE::PageFrameNumber, STATUS_NO_MEMORY, STATUS_RETRY, STATUS_SUCCESS, TRUE, _MMPTE::u, UNLOCK_PFN2, ValidKernelPde, and ValidKernelPdeLocal.
Referenced by MiInitializeSessionPool().
VOID MiInitializeNonPagedPool (VOID)
Definition at line 3400 of file allocpag.c.
References ASSERT, BYTES_TO_PAGES, _MMPTE::Hard, Index, InitializeListHead(), InitializeSListHead(), InsertHeadList(), _MMFREE_POOL_ENTRY::List, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_MAX_FREE_LIST_HEADS, MiEndOfInitialPoolFrame, MiExpansionPoolPagesInitialCharge, MiExpansionPoolPagesInUse, MiGetPteAddress, MiInitializeSystemPtes(), MiNonPagedPoolSListMaximum, MiPagedPoolSListMaximum, MiStartOfInitialPoolFrame, MM_FREE_POOL_SIGNATURE, MmMaximumNonPagedPoolInBytes, MmNonPagedPoolEnd, MmNonPagedPoolEnd0, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmNumberOfFreeNonPagedPool, MmNumberOfPhysicalPages, MmProtectFreedNonPagedPool, MmSizeOfNonPagedPoolInBytes, MmSpecialPoolTag, MmVerifyDriverBufferLength, NonPagedPoolExpansion, _MMFREE_POOL_ENTRY::Owner, PAGE_SIZE, PAGED_CODE, _MMFREE_POOL_ENTRY::Signature, _MMFREE_POOL_ENTRY::Size, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiInitMachineDependent().
VOID MiInitializePoolEvents (VOID)
Definition at line 3320 of file allocpag.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, FALSE, KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeClearEvent(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), LockQueueMmNonPagedPoolLock, MiHighNonPagedPoolEvent, MiHighNonPagedPoolThreshold, MiHighPagedPoolEvent, MiHighPagedPoolThreshold, MiLowNonPagedPoolEvent, MiLowNonPagedPoolThreshold, MiLowPagedPoolEvent, MiLowPagedPoolThreshold, MmAllocatedNonPagedPool, MmMaximumNonPagedPoolInPages, MmPagedPoolInfo, and MmSizeOfPagedPoolInPages.
Referenced by MiInitializeMemoryEvents().
NTSTATUS MiInitializeSessionPool (VOID)
Definition at line 3964 of file allocpag.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, _MM_SESSION_SPACE::CommittedPages, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, ExInitializePoolDescriptor(), FALSE, _MM_PAGED_POOL_INFO::FirstPteForPagedPool, Index, InterlockedDecrementSizeT, InterlockedIncrementSizeT, KeInitializeGuardedMutex(), _MM_PAGED_POOL_INFO::LastPteForPagedPool, _MMPTE::Long, MI_FLUSH_SINGLE_TB, MI_WRITE_ZERO_PTE, MiChargeCommitment(), MiCreateBitMap, MiFreeSessionPoolBitMaps(), MiGetPdeAddress, MiGetPdeSessionIndex, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInitializeAndChargePfn(), MiReturnCommitment, MiSessionPageTableRelease(), MiSessionPoolEnd, MiSessionPoolStart, MiZeroMemoryPte, MM_BUMP_SESS_COUNTER, MM_BUMP_SESSION_FAILURES, MM_DBG_COMMIT_SESSION_POOL_PAGE_TABLES, MM_DBG_SESSION_NP_POOL_CREATE, MM_DBG_SESSION_NP_POOL_CREATE_FAILED, MM_DBG_SESSION_PAGEDPOOL_PAGETABLE_ALLOC, MM_DBG_SESSION_PAGEDPOOL_PAGETABLE_FREE_FAIL1, MM_SESSION_FAILURE_NO_COMMIT, MM_SESSION_FAILURE_NO_NONPAGED_POOL, MM_SESSION_FAILURE_NO_RESIDENT, MM_TRACK_COMMIT, MM_TRACK_COMMIT_REDUCTION, MmSessionPoolSize, MmSessionSpace, _MM_PAGED_POOL_INFO::NextPdeForPagedPoolExpansion, _MM_SESSION_SPACE::NonPageablePages, NonPagedPool, NT_SUCCESS, NULL, PAGE_SHIFT, PAGED_CODE, _MM_SESSION_SPACE::PagedPool, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_SESSION_SPACE::PagedPoolBasePde, _MM_PAGED_POOL_INFO::PagedPoolCommit, _MM_SESSION_SPACE::PagedPoolEnd, _MM_PAGED_POOL_INFO::PagedPoolHint, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, PagedPoolSession, _MM_SESSION_SPACE::PagedPoolStart, _MM_SESSION_SPACE::PageTables, PTE_PER_PAGE, RtlClearAllBits(), RtlClearBits(), RtlSetAllBits(), SESSION_GLOBAL, _MM_SESSION_SPACE::SessionPageDirectoryIndex, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, TRUE, and _MMPTE::u.
Referenced by MiSessionCreateInternal().
LOGICAL MiIsPoolLargeSession (IN PVOID VirtualAddress)
Definition at line 1126 of file allocpag.c.
References ASSERT, _MMPFN::e1, FALSE, _MMPTE::Hard, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, PAGE_ALIGN, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
Referenced by ExFreePoolWithTag().
VOID MiMarkPoolLargeSession (IN PVOID VirtualAddress)
Definition at line 1059 of file allocpag.c.
References ASSERT, _MMPFN::e1, _MMPTE::Hard, LOCK_PFN2, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, PAGE_ALIGN, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, and _MMPTE_HARDWARE::Valid.
Referenced by __bcount().
LOGICAL MiMustFrameBeCached (IN PFN_NUMBER PageFrameIndex)
Definition at line 6279 of file allocpag.c.
References FALSE, MiLargePageRangeIndex, MiLargePageRanges, _MI_LARGE_PAGE_RANGES::StartFrame, and TRUE.
VOID MiProtectedPoolInsertList (IN PLIST_ENTRY ListHead, IN PLIST_ENTRY Entry, IN LOGICAL InsertHead)
Definition at line 310 of file allocpag.c.
References InsertHeadList(), InsertTailList(), IsListEmpty, MiProtectFreeNonPagedPool(), MiUnProtectFreeNonPagedPool(), and TRUE.
Referenced by MiAllocatePoolPages(), and MiFreePoolPages().
VOID MiProtectedPoolRemoveEntryList (IN PLIST_ENTRY Entry)
Definition at line 393 of file allocpag.c.
References IsListEmpty, MiProtectFreeNonPagedPool(), MiUnProtectFreeNonPagedPool(), RemoveEntryList(), and TRUE.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), and MiFreePoolPages().
VOID MiProtectFreeNonPagedPool (IN PVOID VirtualAddress, IN ULONG SizeInPages)
Definition at line 158 of file allocpag.c.
References _MMPTE::Hard, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_IS_PHYSICAL_ADDRESS, MI_WRITE_INVALID_PTE, MiGetPteAddress, MM_MAXIMUM_FLUSH_COUNT, PAGE_SIZE, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiProtectedPoolInsertList(), and MiProtectedPoolRemoveEntryList().
VOID MiRemoveCachedRange (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER LastPageFrameIndex)
Definition at line 6458 of file allocpag.c.
References ASSERT, _RTL_BITMAP::Buffer, FALSE, _MI_LARGE_PAGE_RANGES::LastFrame, LOCK_PFN, MI_IS_PFN(), MI_MAX_LARGE_PAGE_RANGES, MI_PFN_ELEMENT, MiLargePageRangeIndex, MiLargePageRanges, MiPfnBitMap, _MMPFN::MustBeCached, NULL, _MI_LARGE_PAGE_RANGES::StartFrame, _MMPFN::u4, and UNLOCK_PFN.
Referenced by MiReloadBootLoadedDrivers(), MiReportPhysicalMemory(), MiUseLargeDriverPage(), and MmUnloadSystemImage().
VOID MiSessionPageTableRelease (IN PFN_NUMBER PageFrameIndex)
Definition at line 3917 of file allocpag.c.
References ASSERT, LOCK_PFN, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MM_RESAVAIL_FREE_SESSION_PAGE_TABLE, MmSessionSpace, _MMPFN::PteFrame, _MM_SESSION_SPACE::SessionPageDirectoryIndex, _MMPFN::ShareCount, _MMPFN::u2, _MMPFN::u4, and UNLOCK_PFN.
Referenced by MiInitializeSessionPool().
PVOID MiSessionPoolVector (VOID)
Definition at line 588 of file allocpag.c.
References MmSessionSpace, PAGED_CODE, and _MM_SESSION_SPACE::PagedPool.
Referenced by ExInitializePoolDescriptor().
VOID MiSyncCachedRanges (VOID)
Definition at line 6331 of file allocpag.c.
References _MI_LARGE_PAGE_RANGES::LastFrame, LOCK_PFN, MI_IS_PFN(), MI_PFN_ELEMENT, MiLargePageRangeIndex, _MMPFN::MustBeCached, _MI_LARGE_PAGE_RANGES::StartFrame, _MMPFN::u4, and UNLOCK_PFN.
Referenced by MmInitSystem().
VOID MiTrimSegmentCache (VOID)
Definition at line 465 of file allocpag.c.
References CcHasInactiveViews(), FALSE, IsListEmpty, KeSetEvent(), LOCK_PFN2, MiUnusedSubsectionPagedPool, MmUnusedSegmentCleanup, MmUnusedSegmentForceFree, MmUnusedSegmentForceFreeDefault, MmUnusedSegmentList, MmUnusedSubsectionList, PAGE_SIZE, TRUE, and UNLOCK_PFN2.
Referenced by MiAllocatePoolPages(), MiChargeCommitment(), and MmResourcesAvailable().
LOGICAL MiUnProtectFreeNonPagedPool (IN PVOID VirtualAddress, IN ULONG SizeInPages)
Definition at line 237 of file allocpag.c.
References FALSE, _MMPTE::Hard, MI_IS_PHYSICAL_ADDRESS, MI_WRITE_VALID_PTE, MiGetPteAddress, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiProtectedPoolInsertList(), and MiProtectedPoolRemoveEntryList().
SIZE_T MmAvailablePoolInPages (IN POOL_TYPE PoolType)
Definition at line 616 of file allocpag.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, KeGetCurrentIrql(), MmPagedPoolInfo, MmSizeOfPagedPoolInPages, MmTotalCommitLimitMaximum, MmTotalCommittedPages, PagedPool, PASSIVE_LEVEL, and UNREFERENCED_PARAMETER.
Referenced by NtQuerySystemInformation().
POOL_TYPE MmDeterminePoolType (IN PVOID VirtualAddress)
Definition at line 547 of file allocpag.c.
References MI_IS_SESSION_POOL_ADDRESS, MmPagedPoolEnd, MmPagedPoolStart, NonPagedPool, PagedPool, PagedPoolSession, and TRUE.
Referenced by ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExGetBigPoolInfo(), ExInitializeResourceLite(), and ExReinitializeResourceLite().
ULONG MmGetSizeOfBigPoolAllocation (IN PVOID StartingAddress)
Definition at line 6042 of file allocpag.c.
References ASSERT, BAD_POOL_CALLER, _RTL_BITMAP::Buffer, BYTES_TO_PAGES, _MMPFN::e1, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MMPTE::Hard, KeAcquireGuardedMutex(), KeBugCheckEx(), KeReleaseGuardedMutex(), MEMORY_MANAGEMENT, MI_CHECK_BIT, MI_CONVERT_PHYSICAL_TO_PFN, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_POOL_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiGetPteAddress, MM_SYSTEM_RANGE_START, MmHighestPhysicalPage, MmNonPagedPoolEnd, MmNonPagedPoolEnd0, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmPagedPoolEnd, MmPagedPoolInfo, MmPagedPoolMutex, MmPagedPoolStart, MmSessionSpace, MmSizeOfNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, NonPagedPool, NOTHING, NULL, PAGE_SHIFT, PagedPool, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteFrame, RtlCheckBit, SESSION_GLOBAL, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPFN::u4.
Referenced by ExFreePoolWithTag().
LOGICAL MmIsSessionAddress (IN PVOID VirtualAddress)
Definition at line 6012 of file allocpag.c.
References MI_IS_SESSION_ADDRESS.
Referenced by ExpWin32SessionCallout(), KeBugCheck2(), PspWin32SessionCallout(), and RtlpWalkFrameChain().
LOGICAL MmResourcesAvailable (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN EX_POOL_PRIORITY Priority)
Definition at line 666 of file allocpag.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, BASE_POOL_TYPE_MASK, BYTES_TO_PAGES, FALSE, _KEVENT::Header, HighPoolPriority, Index, KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeIsExecutingDpc(), KePulseEvent(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), LockQueueMmNonPagedPoolLock, _ETHREAD::MemoryMaker, MI_UNUSED_SEGMENTS_SURPLUS, MiIssuePageExtendRequestNoWait(), MiLowNonPagedPoolEvent, MiLowPagedPoolEvent, MiTrimSegmentCache(), MmAllocatedNonPagedPool, MmLowPriority, MmMaximumNonPagedPoolInPages, MmNonPagedPool, MmNormalPriority, MmNumberOfPhysicalPages, MmPagedPool, MmPagedPoolInfo, MmPoolFailureReasons, MmPoolFailures, MmPreemptForNonPagedPriority, MmPreemptForPagedPriority, MmPreemptiveTrims, MmPriorityTooLow, MmSessionPagedPool, MmSessionPoolSize, MmSessionSpace, MmSizeOfPagedPoolInPages, MmTotalCommitLimitMaximum, MmTotalCommittedPages, MmUnusedSegmentCleanup, MUST_SUCCEED_POOL_TYPE_MASK, NonPagedPool, NormalPoolPriority, PAGE_SHIFT, PagedPool, _MM_SESSION_SPACE::PagedPoolInfo, PsGetCurrentThread(), SESSION_POOL_MASK, _MM_SESSION_SPACE::SessionPoolAllocationFailures, _DISPATCHER_HEADER::SignalState, Status, and TRUE.
Variable Documentation
PMMPFN MiCachedNonPagedPool
Definition at line 73 of file allocpag.c.
Referenced by MiAddExpansionNonPagedPool(), and MiAllocatePoolPages().
PFN_NUMBER MiCachedNonPagedPoolCount
Definition at line 74 of file allocpag.c.
Referenced by MiAddExpansionNonPagedPool(), MiAllocatePoolPages(), and MiFreePoolPages().
PFN_NUMBER MiEndOfInitialPoolFrame
Definition at line 66 of file allocpag.c.
Referenced by MiFreePoolPages(), MiIdentifyPfn(), MiInitializeNonPagedPool(), and MmAreMdlPagesLocked().
PFN_NUMBER MiExpansionPoolPagesInitialCharge
Definition at line 104 of file allocpag.c.
Referenced by MiAllocatePoolPages(), MiFreeNonPagedPool(), MiFreePoolPages(), MiInitializeNonPagedPool(), and MmInitSystem().
PFN_NUMBER MiExpansionPoolPagesInUse
Definition at line 103 of file allocpag.c.
Referenced by MiAllocatePoolPages(), MiFreeNonPagedPool(), MiFreePoolPages(), and MiInitializeNonPagedPool().
ULONG MiLargePageRangeIndex
Definition at line 6274 of file allocpag.c.
Referenced by MiAddCachedRange(), MiMustFrameBeCached(), MiRemoveCachedRange(), and MiSyncCachedRanges().
MI_LARGE_PAGE_RANGES MiLargePageRanges[MI_MAX_LARGE_PAGE_RANGES]
Definition at line 6275 of file allocpag.c.
Referenced by MiMustFrameBeCached(), and MiRemoveCachedRange().
SLIST_HEADER MiNonPagedPoolSListHead
Definition at line 58 of file allocpag.c.
ULONG MiNonPagedPoolSListMaximum = 4
Definition at line 59 of file allocpag.c.
Referenced by MiFreePoolPages(), and MiInitializeNonPagedPool().
SLIST_HEADER MiPagedPoolSListHead
Definition at line 61 of file allocpag.c.
ULONG MiPagedPoolSListMaximum = 8
Definition at line 62 of file allocpag.c.
Referenced by MiFreePoolPages(), and MiInitializeNonPagedPool().
PFN_NUMBER MiStartOfInitialPoolFrame
Definition at line 65 of file allocpag.c.
Referenced by MiFreePoolPages(), MiIdentifyPfn(), MiInitializeNonPagedPool(), and MmAreMdlPagesLocked().
PFN_NUMBER MmAllocatedNonPagedPool
Definition at line 64 of file allocpag.c.
Referenced by MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), MiInitializePoolEvents(), MmRaisePoolQuota(), and MmResourcesAvailable().
PFN_NUMBER MmFreedExpansionPoolMaximum
Definition at line 59 of file mminit.c.
Referenced by MiFreePoolPages(), and MmInitSystem().
PVOID MmNonPagedPoolEnd0
Definition at line 68 of file allocpag.c.
Referenced by MiFreePoolPages(), MiInitializeNonPagedPool(), and MmGetSizeOfBigPoolAllocation().
PVOID MmNonPagedPoolExpansionStart
Definition at line 69 of file allocpag.c.
Referenced by MiAddExpansionNonPagedPool(), MiComputeInitialLargePage(), MiFindContiguousPages(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiIdentifyPfn(), MiInitializeNonPagedPool(), MiInitMachineDependent(), MmAccessFault(), MmAreMdlPagesLocked(), MmFreeContiguousMemory(), and MmGetSizeOfBigPoolAllocation().
LIST_ENTRY MmNonPagedPoolFreeListHead[MI_MAX_FREE_LIST_HEADS]
Definition at line 71 of file allocpag.c.
ULONG MmPagedPoolCommit
Definition at line 56 of file allocpag.c.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), and MiFreePoolPages().
KGUARDED_MUTEX MmPagedPoolMutex
Definition at line 51 of file mminit.c.
Referenced by MiFreePoolPages(), and MmGetSizeOfBigPoolAllocation().
ULONG MmPoolFailureReasons[MmMaximumFailureReason]
Definition at line 144 of file allocpag.c.
Referenced by MiAllocatePoolPages(), and MmResourcesAvailable().
ULONG MmPoolFailures[MmMaximumPoolType][MmMaximumPoolPriority]
Definition at line 143 of file allocpag.c.
Referenced by MiAllocatePoolPages(), and MmResourcesAvailable().
ULONG MmPreemptiveTrims[MmMaximumPreempt]
Definition at line 154 of file allocpag.c.
Referenced by MiAllocatePoolPages(), and MmResourcesAvailable().
ULONG MmUnusedSegmentForceFree
Definition at line 43 of file sectsup.c.
Referenced by MiTrimSegmentCache().
ULONG MmUnusedSegmentForceFreeDefault = 30
Definition at line 106 of file allocpag.c.
Referenced by MiTrimSegmentCache().
POOL_DESCRIPTOR NonPagedPoolDescriptor
Definition at line 322 of file pool.c.