Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntdbg.h File Reference
ntdbg.h File Reference
#include <pshpack4.h>
#include <poppack.h>
Data Structures
struct _ALPHA_CONTEXT
struct _ALPHA_DBGKD_CONTROL_REPORT
struct _ALPHA_NT5_CONTEXT
struct _ALPHA_NT5_KPROCESSOR_STATE
struct _AMD64_CONTEXT
struct _AMD64_DBGKD_CONTROL_REPORT
struct _AMD64_DBGKD_CONTROL_SET
struct _AMD64_DESCRIPTOR
struct _AMD64_DYNAMIC_FUNCTION_TABLE
struct _AMD64_FIBER
struct _AMD64_KPROCESSOR_STATE
struct _AMD64_KSPECIAL_REGISTERS
struct _AMD64_KSWITCH_FRAME
struct _AMD64_KTRAP_FRAME
struct _AMD64_LEGACY_SAVE_AREA
struct _AMD64_M128
union _AMD64_UNWIND_CODE
struct _AMD64_UNWIND_INFO
struct _ARM_CONTEXT
struct _CROSS_PLATFORM_CONTEXT
struct _CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE
struct _CROSS_PLATFORM_FIBER
struct _CROSS_PLATFORM_KSPECIAL_REGISTERS
struct _DBGKD_ANY_CONTROL_REPORT
struct _DBGKD_ANY_CONTROL_SET
struct _DBGKD_ANY_WAIT_STATE_CHANGE
struct _DBGKD_BREAKPOINTEX
struct _DBGKD_CLOSE_FILE
struct _DBGKD_COMMAND_STRING
struct _DBGKD_CONTINUE
struct _DBGKD_CONTINUE2
struct _DBGKD_CONTROL_REQUEST
struct _DBGKD_CREATE_FILE
struct _DBGKD_DEBUG_IO
struct _DBGKD_FILE_IO
struct _DBGKD_FILL_MEMORY
struct _DBGKD_GET_CONTEXT
struct _DBGKD_GET_INTERNAL_BREAKPOINT32
struct _DBGKD_GET_INTERNAL_BREAKPOINT64
struct _DBGKD_GET_SET_BUS_DATA
struct _DBGKD_GET_STRING
struct _DBGKD_LOAD_SYMBOLS32
struct _DBGKD_LOAD_SYMBOLS64
struct _DBGKD_MANIPULATE_STATE32
struct _DBGKD_MANIPULATE_STATE64
struct _DBGKD_PRINT_STRING
struct _DBGKD_PRINT_TRACE
struct _DBGKD_QUERY_MEMORY
struct _DBGKD_QUERY_SPECIAL_CALLS
struct _DBGKD_READ_FILE
struct _DBGKD_READ_MEMORY32
struct _DBGKD_READ_MEMORY64
struct _DBGKD_READ_WRITE_IO32
struct _DBGKD_READ_WRITE_IO64
struct _DBGKD_READ_WRITE_IO_EXTENDED32
struct _DBGKD_READ_WRITE_IO_EXTENDED64
struct _DBGKD_READ_WRITE_MSR
struct _DBGKD_RELEASE_BREAKPOINT
struct _DBGKD_REQUEST_BREAKPOINT
struct _DBGKD_RESTORE_BREAKPOINT
struct _DBGKD_SEARCH_MEMORY
struct _DBGKD_SET_CONTEXT
struct _DBGKD_SET_INTERNAL_BREAKPOINT32
struct _DBGKD_SET_INTERNAL_BREAKPOINT64
struct _DBGKD_SET_SPECIAL_CALL32
struct _DBGKD_SET_SPECIAL_CALL64
struct _DBGKD_SWITCH_PARTITION
union _DBGKD_TRACE_DATA
struct _DBGKD_TRACE_IO
struct _DBGKD_WAIT_STATE_CHANGE32
struct _DBGKD_WAIT_STATE_CHANGE64
struct _DBGKD_WRITE_BREAKPOINT32
struct _DBGKD_WRITE_BREAKPOINT64
struct _DBGKD_WRITE_FILE
struct _DBGKD_WRITE_MEMORY32
struct _DBGKD_WRITE_MEMORY64
struct _DBGKM_APIMSG
struct _DBGKM_CREATE_PROCESS
struct _DBGKM_CREATE_THREAD
struct _DBGKM_EXCEPTION
struct _DBGKM_EXCEPTION32
struct _DBGKM_EXCEPTION64
struct _DBGKM_EXIT_PROCESS
struct _DBGKM_EXIT_THREAD
struct _DBGKM_LOAD_DLL
struct _DBGKM_UNLOAD_DLL
struct _DBGSRV_APIMSG
struct _DBGSS_APIMSG
struct _DBGSS_CREATE_PROCESS
struct _DBGUI_APIMSG
struct _DBGUI_CONTINUE
struct _DBGUI_CREATE_PROCESS
struct _DBGUI_CREATE_THREAD
struct _DBGUI_STOPDEBUG
struct _DBGUI_WAIT_STATE_CHANGE
struct _DISPATCHER_HEADER32
struct _DISPATCHER_HEADER64
struct _IA64_CONTEXT
struct _IA64_DBGKD_CONTROL_REPORT
struct _IA64_DBGKD_CONTROL_SET
struct _IA64_DYNAMIC_FUNCTION_TABLE
struct _IA64_FIBER
struct _IA64_KEXCEPTION_FRAME
struct _IA64_KNONVOLATILE_CONTEXT_POINTERS
struct _IA64_KPROCESSOR_STATE
struct _IA64_KSPECIAL_REGISTERS
struct _IA64_KSWITCH_FRAME
struct _IA64_KTRAP_FRAME
struct _IA64_UNWIND_INFO
struct _KAPC_STATE32
struct _KAPC_STATE64
struct _KD_PACKET
struct _KDPC32
struct _KDPC64
struct _KSPIN_LOCK_QUEUE32
struct _KSPIN_LOCK_QUEUE64
struct _PAE_ADDRESS
struct _PP_LOOKASIDE_LIST32
struct _PP_LOOKASIDE_LIST64
struct _X86_CONTEXT
struct _X86_DBGKD_CONTROL_REPORT
struct _X86_DBGKD_CONTROL_SET
struct _X86_DESCRIPTOR
struct _X86_DESCRIPTOR_TABLE_ENTRY
struct _X86_FIBER
struct _X86_FLOATING_SAVE_AREA
struct _X86_FXSAVE_FORMAT
struct _X86_KPROCESSOR_STATE
struct _X86_KSPECIAL_REGISTERS
struct _X86_KSWITCHFRAME
struct _X86_KTRAP_FRAME
struct _X86_KTSS
struct _X86_LDT_ENTRY
struct _X86_NT5_CONTEXT
struct _X86_NT5_KPROCESSOR_STATE
struct _X86PAE_HARDWARE_PDE
struct _X86PAE_HARDWARE_PTE
Macros
#define ALPHA_CONTEXT_ALPHA 0x00020000
#define ALPHA_CONTEXT_CONTROL (ALPHA_CONTEXT_ALPHA | 0x00000001L)
#define ALPHA_CONTEXT_FLOATING_POINT (ALPHA_CONTEXT_ALPHA | 0x00000002L)
#define ALPHA_CONTEXT_FULL
#define ALPHA_CONTEXT_INTEGER (ALPHA_CONTEXT_ALPHA | 0x00000004L)
#define ALPHA_DEBUG_CONTROL_SPACE_PCR 1
#define ALPHA_DEBUG_CONTROL_SPACE_PRCB 3
#define ALPHA_DEBUG_CONTROL_SPACE_TEB 6
#define ALPHA_DEBUG_CONTROL_SPACE_THREAD 2
#define ALPHA_PSR_IE 0x1
#define ALPHA_PSR_IE_MASK 0x1
#define ALPHA_PSR_IRQL 0x2
#define ALPHA_PSR_IRQL_MASK 0x7
#define ALPHA_PSR_MODE 0x0
#define ALPHA_PSR_MODE_MASK 0x1
#define ALPHA_PSR_USER_MODE 0x1
#define AMD64_BASE_VIRT 0xFFFFF6FB7DBED000UI64
#define AMD64_CONTEXT_AMD64 0x00100000
#define AMD64_CONTEXT_CONTROL (AMD64_CONTEXT_AMD64 | 0x1L)
#define AMD64_CONTEXT_DEBUG_REGISTERS (AMD64_CONTEXT_AMD64 | 0x10L)
#define AMD64_CONTEXT_FLOATING_POINT (AMD64_CONTEXT_AMD64 | 0x8L)
#define AMD64_CONTEXT_FULL (AMD64_CONTEXT_CONTROL | AMD64_CONTEXT_INTEGER | AMD64_CONTEXT_FLOATING_POINT)
#define AMD64_CONTEXT_INTEGER (AMD64_CONTEXT_AMD64 | 0x2L)
#define AMD64_CONTEXT_SEGMENTS (AMD64_CONTEXT_AMD64 | 0x4L)
#define AMD64_DEBUG_CONTROL_SPACE_KSPECIAL 2
#define AMD64_DEBUG_CONTROL_SPACE_PCR 0
#define AMD64_DEBUG_CONTROL_SPACE_PRCB 1
#define AMD64_DEBUG_CONTROL_SPACE_THREAD 3
#define AMD64_KGDT64_LAST (6 * 16)
#define AMD64_KGDT64_NULL (0 * 16)
#define AMD64_KGDT64_R0_CODE (1 * 16)
#define AMD64_KGDT64_R0_DATA (1 * 16) + 8
#define AMD64_KGDT64_R3_CMCODE (2 * 16)
#define AMD64_KGDT64_R3_CMTEB (5 * 16)
#define AMD64_KGDT64_R3_CODE (3 * 16)
#define AMD64_KGDT64_R3_DATA (2 * 16) + 8
#define AMD64_KGDT64_SYS_TSS (4 * 16)
#define AMD64_KI_USER_SHARED_DATA 0xfffff78000000000UI64
#define AMD64_KPCR_CURRENT_PRCB 0x38
#define AMD64_KPCR_KD_VERSION_BLOCK 0x108
#define AMD64_KPCR_PRCB 0x180
#define AMD64_KPCR_SELF 0x18
#define AMD64_KPCR_SIZE 0x12e0
#define AMD64_KPRCB_CONTEXT 0x120
#define AMD64_KPRCB_NUMBER 4
#define AMD64_KPRCB_SPECIAL_REG 0x40
#define AMD64_LARGE_PAGE_MASK 0x80
#define AMD64_LARGE_PAGE_SIZE (2 * 1024 * 1024)
#define AMD64_MM_PTE_PROTOTYPE_MASK 0x400
#define AMD64_MM_PTE_TRANSITION_MASK 0x800
#define AMD64_PAGE_SHIFT 12L
#define AMD64_PAGE_SIZE 0x1000
#define AMD64_PDBR_MASK AMD64_VALID_PFN_MASK
#define AMD64_PDE_MASK 0x1ff
#define AMD64_PDE_SHIFT 21
#define AMD64_PDPE_MASK 0x1ff
#define AMD64_PDPE_SHIFT 30
#define AMD64_PHYSICAL_END 0xFFFFF8FFFFFFFFFFUI64
#define AMD64_PHYSICAL_START 0xFFFFF80000000000UI64
#define AMD64_PML4E_MASK 0x1ff
#define AMD64_PML4E_SHIFT 39
#define AMD64_PTE_MASK 0x1ff
#define AMD64_PTE_SHIFT 12
#define AMD64_REPORT_INCLUDES_SEGS 0x0001
#define AMD64_REPORT_STANDARD_CS 0x0002
#define AMD64_TRIAGE_PRCB_ADDRESS 0xfffff780ffff0000UI64
#define AMD64_UNW_FLAG_CHAININFO 0x4
#define AMD64_UNW_FLAG_EHANDLER 0x1
#define AMD64_UNW_FLAG_NHANDLER 0x0
#define AMD64_UNW_FLAG_UHANDLER 0x2
#define AMD64_VALID_PFN_MASK 0x000000FFFFFFF000UI64
#define AMD64_VALID_PFN_SHIFT 12
#define ARM_CONTEXT_ARM 0x0000040
#define ARM_CONTEXT_CONTROL (ARM_CONTEXT_ARM | 0x00000001L)
#define ARM_CONTEXT_FULL (ARM_CONTEXT_CONTROL | ARM_CONTEXT_INTEGER)
#define ARM_CONTEXT_INTEGER (ARM_CONTEXT_ARM | 0x00000002L)
#define ARM_PAGE_SHIFT 12
#define ARM_PAGE_SIZE 4096
#define BREAKIN_PACKET 0x62626262
#define BREAKIN_PACKET_BYTE 0x62
#define BREAKPOINT_TABLE_SIZE 32
#define CONTROL_PACKET_LEADER 0x69696969
#define CONTROL_PACKET_LEADER_BYTE 0x69
#define COPYSE(p64, p32, f) p64->f = (ULONG64)(LONG64)(LONG)p32->f
#define DBGKD_64BIT_PROTOCOL_VERSION1 5
#define DBGKD_64BIT_PROTOCOL_VERSION2 6
#define DBGKD_CACHING_CACHED 1
#define DBGKD_CACHING_UNCACHED 2
#define DBGKD_CACHING_UNKNOWN 0
#define DBGKD_CACHING_WRITE_COMBINED 3
#define DBGKD_FILL_MEMORY_PHYSICAL 0x00000002
#define DBGKD_FILL_MEMORY_VIRTUAL 0x00000001
#define DBGKD_INTERNAL_BP_FLAG_COUNTONLY 0x00000001
#define DBGKD_INTERNAL_BP_FLAG_DYING 0x00000008
#define DBGKD_INTERNAL_BP_FLAG_INVALID 0x00000002
#define DBGKD_INTERNAL_BP_FLAG_SUSPENDED 0x00000004
#define DBGKD_MAX_INTERNAL_BREAKPOINTS 20
#define DBGKD_MAXSTREAM 16
#define DBGKD_PARTITION_ALTERNATE 0x00000001
#define DBGKD_PARTITION_DEFAULT 0x00000000
#define DBGKD_QUERY_MEMORY_EXECUTE 0x00000004
#define DBGKD_QUERY_MEMORY_FIXED 0x00000008
#define DBGKD_QUERY_MEMORY_KERNEL 0x00000002
#define DBGKD_QUERY_MEMORY_PROCESS 0x00000000
#define DBGKD_QUERY_MEMORY_READ 0x00000001
#define DBGKD_QUERY_MEMORY_SESSION 0x00000001
#define DBGKD_QUERY_MEMORY_VIRTUAL 0x00000000
#define DBGKD_QUERY_MEMORY_WRITE 0x00000002
#define DbgKdAlternateStateChange 0x00010000L
#define DbgKdCauseBugCheckApi 0x00003149L
#define DbgKdCheckLowMemoryApi 0x00003159L
#define DbgKdClearAllInternalBreakpointsApi 0x0000315AL
#define DbgKdClearSpecialCallsApi 0x00003141L
#define DbgKdCloseFileApi 0x00003433L
#define DbgKdCommandStringStateChange 0x00003032L
#define DbgKdContinueApi 0x00003136L
#define DbgKdContinueApi2 0x0000313CL
#define DbgKdCreateFileApi 0x00003430L
#define DbgKdExceptionStateChange 0x00003030L
#define DbgKdFillMemoryApi 0x0000315BL
#define DbgKdGetBusDataApi 0x00003157L
#define DbgKdGetContextApi 0x00003132L
#define DbgKdGetInternalBreakPointApi 0x00003143L
#define DbgKdGetStringApi 0x00003231L
#define DbgKdGetVersionApi 0x00003146L
#define DbgKdLoadSymbolsStateChange 0x00003031L
#define DbgKdMaximumManipulate 0x0000315EL
#define DbgKdMaximumStateChange 0x00003033L
#define DbgKdMinimumManipulate 0x00003130L
#define DbgKdMinimumStateChange 0x00003030L
#define DbgKdPageInApi 0x00003151L
#define DbgKdPrintStringApi 0x00003230L
#define DbgKdPrintTraceApi 0x00003330L
#define DbgKdQueryMemoryApi 0x0000315CL
#define DbgKdReadControlSpaceApi 0x00003137L
#define DbgKdReadFileApi 0x00003431L
#define DbgKdReadIoSpaceApi 0x00003139L
#define DbgKdReadIoSpaceExtendedApi 0x00003144L
#define DbgKdReadMachineSpecificRegister 0x00003152L
#define DbgKdReadPhysicalMemoryApi 0x0000313DL
#define DbgKdReadVirtualMemoryApi 0x00003130L
#define DbgKdRebootApi 0x0000313BL
#define DbgKdReleaseHardwareBp 0x00004301L
#define DbgKdRequestHardwareBp 0x00004300L
#define DbgKdRestoreBreakPointApi 0x00003135L
#define DbgKdRestoreBreakPointExApi 0x00003148L
#define DbgKdSearchMemoryApi 0x00003156L
#define DbgKdSetBusDataApi 0x00003158L
#define DbgKdSetContextApi 0x00003133L
#define DbgKdSetInternalBreakPointApi 0x00003142L
#define DbgKdSetSpecialCallApi 0x00003140L
#define DbgKdSwitchPartition 0x0000315DL
#define DbgKdSwitchProcessor 0x00003150L
#define DbgKdWriteBreakPointApi 0x00003134L
#define DbgKdWriteBreakPointExApi 0x00003147L
#define DbgKdWriteControlSpaceApi 0x00003138L
#define DbgKdWriteFileApi 0x00003432L
#define DbgKdWriteIoSpaceApi 0x0000313AL
#define DbgKdWriteIoSpaceExtendedApi 0x00003145L
#define DbgKdWriteMachineSpecificRegister 0x00003153L
#define DbgKdWritePhysicalMemoryApi 0x0000313EL
#define DbgKdWriteVirtualMemoryApi 0x00003131L
#define DBGKM_API_MSG_LENGTH(TypeSize) ((sizeof(DBGKM_APIMSG) << 16) | (DBGKM_MSG_OVERHEAD + (TypeSize)))
#define DBGKM_FORMAT_API_MSG(m, Number, TypeSize)
#define DBGKM_MSG_OVERHEAD (FIELD_OFFSET(DBGKM_APIMSG, u.Exception) - sizeof(PORT_MESSAGE))
#define DBGSRV_API_MSG_LENGTH(TypeSize) ((sizeof(DBGSRV_APIMSG) << 16) | (DBGSRV_MSG_OVERHEAD))
#define DBGSRV_FORMAT_API_MSG(m, Number, TypeSize, CKey)
#define DBGSRV_MSG_OVERHEAD (sizeof(DBGSRV_APIMSG) - sizeof(PORT_MESSAGE))
#define DBGSS_API_MSG_LENGTH(TypeSize) ((sizeof(DBGSS_APIMSG) << 16) | (DBGSS_MSG_OVERHEAD + (TypeSize)))
#define DBGSS_FORMAT_API_MSG(m, Number, TypeSize, pApp, CKey)
#define DBGSS_MSG_OVERHEAD (FIELD_OFFSET(DBGSS_APIMSG, u.Exception) - sizeof(PORT_MESSAGE))
#define DBGUI_API_MSG_LENGTH(TypeSize) ((sizeof(DBGUI_APIMSG) << 16) | (DBGUI_MSG_OVERHEAD + (TypeSize)))
#define DBGUI_FORMAT_API_MSG(m, Number, TypeSize)
#define DBGUI_MSG_OVERHEAD (FIELD_OFFSET(DBGUI_APIMSG, u.Continue) - sizeof(PORT_MESSAGE))
#define DEBUG_ALL_ACCESS
#define DEBUG_KILL_ON_CLOSE (0x1)
#define DEBUG_PROCESS_ASSIGN (0x0002)
#define DEBUG_QUERY_INFORMATION (0x0008)
#define DEBUG_READ_EVENT (0x0001)
#define DEBUG_SET_INFORMATION (0x0004)
#define DEF_KPRCB_CURRENT_THREAD_OFFSET_32 4
#define DEF_KPRCB_CURRENT_THREAD_OFFSET_64 8
#define IA64_2462_KPRCB_MHZ 0x1728
#define IA64_3555_ETHREAD_SIZE 0x440
#define IA64_3555_KTHREAD_APCPROCESS_OFFSET 0x090
#define IA64_3555_KTHREAD_BSTORE_OFFSET 0x040
#define IA64_3555_KTHREAD_BSTORELIMIT_OFFSET 0x048
#define IA64_3555_KTHREAD_KERNELSTACK_OFFSET 0x038
#define IA64_3555_KTHREAD_NEXTPROCESSOR_OFFSET 0x1F7
#define IA64_3555_KTHREAD_STATE_OFFSET 0x064
#define IA64_3555_KTHREAD_TEB_OFFSET 0x068
#define IA64_3555_PEB_IN_EPROCESS 0x300
#define IA64_BREAK_DEBUG_BASE 0x080000
#define IA64_BREAK_FASTSYS_BASE 0x1C0000
#define IA64_BREAK_SYSCALL_BASE 0x180000
#define IA64_CONTEXT_CONTROL (IA64_CONTEXT_IA64 | 0x00000001L)
#define IA64_CONTEXT_DEBUG (IA64_CONTEXT_IA64 | 0x00000010L)
#define IA64_CONTEXT_FLOATING_POINT (IA64_CONTEXT_LOWER_FLOATING_POINT | IA64_CONTEXT_HIGHER_FLOATING_POINT)
#define IA64_CONTEXT_FRAME 10
#define IA64_CONTEXT_FULL (IA64_CONTEXT_CONTROL | IA64_CONTEXT_FLOATING_POINT | IA64_CONTEXT_INTEGER | IA64_CONTEXT_IA32_CONTROL)
#define IA64_CONTEXT_HIGHER_FLOATING_POINT (IA64_CONTEXT_IA64 | 0x00000004L)
#define IA64_CONTEXT_IA32_CONTROL (IA64_CONTEXT_IA64 | 0x00000020L)
#define IA64_CONTEXT_IA64 0x00080000
#define IA64_CONTEXT_INTEGER (IA64_CONTEXT_IA64 | 0x00000008L)
#define IA64_CONTEXT_LOWER_FLOATING_POINT (IA64_CONTEXT_IA64 | 0x00000002L)
#define IA64_DBGKD_CONTROL_SET_CONTINUE_NONE 0x0000
#define IA64_DBGKD_CONTROL_SET_CONTINUE_TRACE_INSTRUCTION 0x0001
#define IA64_DBGKD_CONTROL_SET_CONTINUE_TRACE_TAKEN_BRANCH 0x0002
#define IA64_DEBUG_CONTROL_SPACE_KSPECIAL 3
#define IA64_DEBUG_CONTROL_SPACE_PCR 1
#define IA64_DEBUG_CONTROL_SPACE_PRCB 2
#define IA64_DEBUG_CONTROL_SPACE_THREAD 4
#define IA64_DEBUG_STOP_BREAKPOINT (IA64_BREAK_DEBUG_BASE+22)
#define IA64_DIRECTORY_TABLE_BASE_IN_EPROCESS 40
#define IA64_EPROCESS_SIZE 0x410
#define IA64_ETHREAD_SIZE 0x458
#define IA64_EXCEPTION_FRAME 2
#define IA64_FM_FROM_FS(Fs) (((Fs) >> IA64_IFS_IFM) & ((1UI64 << IA64_IFS_IFM_LEN) - 1))
#define IA64_FM_RRB_FR(Fm) (((Fm) >> 25) & 0x7f)
#define IA64_FM_RRB_GR(Fm) (((Fm) >> 18) & 0x7f)
#define IA64_FM_RRB_PR(Fm) (((Fm) >> 32) & 0x3f)
#define IA64_FM_SOF(Fm) ((Fm) & 0x7f)
#define IA64_FM_SOR(Fm) (((Fm) >> 14) & 0xf)
#define IA64_IFS_IFM 0
#define IA64_IFS_IFM_LEN 38
#define IA64_IFS_MBZ0 38
#define IA64_IFS_MBZ0_V 0x1ffffffi64
#define IA64_IFS_V 63
#define IA64_IFS_V_LEN 1
#define IA64_INTERRUPT_FRAME 1
#define IA64_IP_SLOT 2
#define IA64_KI_USER_SHARED_DATA 0xe0000000fffe0000UI64
#define IA64_KPCR_BSTORE_LIMIT 0xb78
#define IA64_KPCR_INITIAL_BSTORE 0xb68
#define IA64_KPCR_INITIAL_STACK 0xb60
#define IA64_KPCR_PRCB 0xb18
#define IA64_KPCR_SIZE 0xe28
#define IA64_KPCR_STACK_LIMIT 0xb70
#define IA64_KPRCB_CONTEXT 0x190
#define IA64_KPRCB_NUMBER 0x20
#define IA64_KPRCB_PCR_PAGE 0x38
#define IA64_KPRCB_PROCESSOR_MODEL 0x50
#define IA64_KPRCB_SIZE 0x1A40
#define IA64_KPRCB_SPECIAL_REG 0xc00
#define IA64_KPRCB_VENDOR_STRING 0x70
#define IA64_KTHREAD_APCPROCESS_OFFSET 0x098
#define IA64_KTHREAD_BSTORE_OFFSET 0x038
#define IA64_KTHREAD_BSTORELIMIT_OFFSET 0x040
#define IA64_KTHREAD_INITSTACK_OFFSET 0x028
#define IA64_KTHREAD_KERNELSTACK_OFFSET 0x060
#define IA64_KTHREAD_NEXTPROCESSOR_OFFSET 0x23b
#define IA64_KTHREAD_STATE_OFFSET 0x071
#define IA64_KTHREAD_TEB_OFFSET 0x050
#define IA64_KTRAP_FRAME_ARGUMENTS (8 * 8)
#define IA64_LARGE_PAGE_PDE_MARK 4
#define IA64_LARGE_PAGE_PDE_MASK 0x1c
#define IA64_LARGE_PAGE_SIZE 0x800000
#define IA64_MM_EPC_VA 0xe0000000ffa00000
#define IA64_MM_PTE_PROTOTYPE_MASK 0x02
#define IA64_MM_PTE_TRANSITION_MASK 0x80
#define IA64_NAT_BITS_PER_RNAT_REG 63
#define IA64_PAGE_SHIFT 13L
#define IA64_PAGE_SIZE 0x2000
#define IA64_PCID_IN_EPROCESS 0x260
#define IA64_PDE1_SHIFT 33
#define IA64_PDE2_SHIFT 23
#define IA64_PDE_MASK 0x3ff
#define IA64_PEB_IN_EPROCESS 0x2D0
#define IA64_PFS_EC_MASK 0x3F
#define IA64_PFS_EC_SHIFT 52
#define IA64_PFS_EC_SIZE 6
#define IA64_PFS_SIZE_MASK 0x7F
#define IA64_PFS_SIZE_SHIFT 7
#define IA64_PHYSICAL1_END 0x80000FFFFFFFFFFFUI64
#define IA64_PHYSICAL1_START 0x8000000000000000UI64
#define IA64_PHYSICAL2_END 0xA0000FFFFFFFFFFFUI64
#define IA64_PHYSICAL2_START 0xA000000000000000UI64
#define IA64_PHYSICAL3_END 0xE0000000BFFFFFFFUI64
#define IA64_PHYSICAL3_START 0xE000000080000000UI64
#define IA64_PTA_BASE_MASK 0x1FFFFFFFFFFF8000UI64
#define IA64_PTE_MASK 0x3ff
#define IA64_PTE_SHIFT 13
#define IA64_REGION_COUNT 8
#define IA64_REGION_KERNEL 7
#define IA64_REGION_MASK 0xE000000000000000UI64
#define IA64_REGION_SESSION 1
#define IA64_REGION_SHIFT 61
#define IA64_REGION_USER 0
#define IA64_RF_BEGIN_ADDRESS(Base, RF) (((ULONG64) Base + (RF)->BeginAddress) & (0xFFFFFFFFFFFFFFF0))
#define IA64_RF_END_ADDRESS(Base, RF) (((ULONG64) Base + (RF)->EndAddress+15) & (0xFFFFFFFFFFFFFFF0))
#define IA64_RNAT_ALIGNMENT (IA64_NAT_BITS_PER_RNAT_REG << 3)
#define IA64_STACK_SCRATCH_AREA 16
#define IA64_SYSCALL_FRAME 0
#define IA64_TEB_BSTORE_BASE 0x1788
#define IA64_TRIAGE_PRCB_ADDRESS 0xe0000000ffff0000UI64
#define IA64_VALID_PFN_MASK 0x0007FFFFFFFFE000UI64
#define IA64_VALID_PFN_SHIFT 13
#define IA64_VHPT_MASK 0x000000FFFFFF8000UI64
#define Ia64InsertIPSlotNumber(IP, SlotNumber)
#define INITIAL_PACKET_ID 0x80800000
#define KD_HIBERNATE (-2)
#define KD_REBOOT (-1)
#define MAXIMUM_SUPPORTED_EXTENSION 512
#define MODULE_LIST_FROM_PEBLDR32 12
#define MODULE_LIST_FROM_PEBLDR64 16
#define NT51_POOL_SMALL_LISTS 32
#define OldVlm1 0x00003154L
#define OldVlm2 0x00003155L
#define PACKET_LEADER 0x30303030
#define PACKET_LEADER_BYTE 0x30
#define PACKET_MAX_SIZE 4000
#define PACKET_TRAILING_BYTE 0xAA
#define PACKET_TYPE_KD_ACKNOWLEDGE 4
#define PACKET_TYPE_KD_CONTROL_REQUEST 10
#define PACKET_TYPE_KD_DEBUG_IO 3
#define PACKET_TYPE_KD_FILE_IO 11
#define PACKET_TYPE_KD_POLL_BREAKIN 8
#define PACKET_TYPE_KD_RESEND 5
#define PACKET_TYPE_KD_RESET 6
#define PACKET_TYPE_KD_STATE_CHANGE32 1
#define PACKET_TYPE_KD_STATE_CHANGE64 7
#define PACKET_TYPE_KD_STATE_MANIPULATE 2
#define PACKET_TYPE_KD_TRACE_IO 9
#define PACKET_TYPE_MAX 12
#define PACKET_TYPE_UNUSED 0
#define PEB_FROM_TEB32 48
#define PEB_FROM_TEB64 96
#define PEBLDR_FROM_PEB32 12
#define PEBLDR_FROM_PEB64 24
#define STACK_BASE_FROM_TEB32 4
#define STACK_BASE_FROM_TEB64 8
#define SYNC_PACKET_ID 0x00000800
#define TRACE_DATA_BUFFER_MAX_SIZE 40
#define TRACE_DATA_INSTRUCTIONS_BIG 0xffff
#define X86_1381_KPCR_SIZE 0x7f0
#define X86_1381_KPRCB_MHZ 0x53c
#define X86_1387_KPRCB_VENDOR_STRING 0x52D
#define X86_2087_KPRCB_VENDOR_STRING 0x72D
#define X86_2195_KPCR_SIZE 0xb10
#define X86_2195_KPRCB_MHZ 0x73c
#define X86_2230_KTHREAD_NEXTPROCESSOR_OFFSET 0x123
#define X86_2251_KPRCB_VENDOR_STRING 0x8AD
#define X86_2462_KPRCB_MHZ 0x8bc
#define X86_2474_KPRCB_VENDOR_STRING 0x900
#define X86_2505_KPRCB_MHZ 0x910
#define X86_3555_KTHREAD_APCPROCESS_OFFSET 0x040
#define X86_3555_KTHREAD_KERNELSTACK_OFFSET 0x020
#define X86_3555_KTHREAD_NEXTPROCESSOR_OFFSET 0x107
#define X86_3555_KTHREAD_STATE_OFFSET 0x028
#define X86_3555_KTHREAD_TEB_OFFSET 0x02C
#define X86_BASE_VIRT 0xc0300000
#define X86_BASE_VIRT_PAE 0xc0600000
#define X86_CONTEXT_X86 0x00010000
#define X86_DIRECTORY_TABLE_BASE_IN_EPROCESS 24
#define X86_EFLAGS_V86_MASK 0x00020000
#define X86_ETHREAD_SIZE 0x258
#define X86_FRAME_EDITED 0xfff8
#define X86_KGDT_DF_TSS 80
#define X86_KGDT_LDT 72
#define X86_KGDT_NMI_TSS 88
#define X86_KGDT_NULL 0
#define X86_KGDT_R0_CODE 8
#define X86_KGDT_R0_DATA 16
#define X86_KGDT_R0_PCR 48
#define X86_KGDT_R3_CODE 24
#define X86_KGDT_R3_DATA 32
#define X86_KGDT_R3_TEB 56
#define X86_KGDT_TSS 40
#define X86_KGDT_VDM_TILE 64
#define X86_KI_USER_SHARED_DATA 0xffdf0000U
#define X86_KPCR_PRCB 0x20
#define X86_KPCR_PRCB_DATA 0x120
#define X86_KPCR_SELF_PCR 0x1c
#define X86_KPCR_SIZE 0xd70
#define X86_KPRCB_CONTEXT 0x1c
#define X86_KPRCB_CPU_TYPE 0x18
#define X86_KPRCB_DPC_ROUTINE_ACTIVE 0x874
#define X86_KPRCB_NUMBER 0x10
#define X86_KPRCB_SPECIAL_REG 0x2e8
#define X86_KTHREAD_APCPROCESS_OFFSET 0x044
#define X86_KTHREAD_INITSTACK_OFFSET 0x018
#define X86_KTHREAD_KERNELSTACK_OFFSET 0x028
#define X86_KTHREAD_NEXTPROCESSOR_OFFSET 0x11f
#define X86_KTHREAD_STATE_OFFSET 0x02d
#define X86_KTHREAD_TEB_OFFSET 0x020
#define X86_LARGE_PAGE_MASK 0x80
#define X86_LARGE_PAGE_SIZE (4 * 1024 * 1024)
#define X86_LARGE_PAGE_SIZE_PAE (2 * 1024 * 1024)
#define X86_MAX_RING 3
#define X86_MM_PTE_PROTOTYPE_MASK 0x400
#define X86_MM_PTE_TRANSITION_MASK 0x800
#define X86_MODE_MASK 1
#define X86_NT4_KPRCB_SIZE 0x9F0
#define X86_NT4_PCID_IN_EPROCESS 0x1A4
#define X86_NT4_PEB_IN_EPROCESS 0x18C
#define X86_NT511_EPROCESS_SIZE 0x278
#define X86_NT51_EPROCESS_SIZE 0x258
#define X86_NT51_ETHREAD_SIZE 0x260
#define X86_NT51_KPRCB_SIZE 0xC50
#define X86_NT51_KTHREAD_NEXTPROCESSOR_OFFSET 0x12b
#define X86_NT5_EPROCESS_SIZE 0x288
#define X86_NT5_KPRCB_SIZE 0x9F0
#define X86_PAGE_SHIFT 12L
#define X86_PAGE_SIZE 0x1000
#define X86_PCID_IN_EPROCESS 0x14C
#define X86_PDBR_MASK 0xFFFFFFE0
#define X86_PDE_MASK_PAE 0x1ff
#define X86_PDE_SHIFT 22
#define X86_PDE_SHIFT_PAE 21
#define X86_PDPE_SHIFT 30
#define X86_PEB_IN_EPROCESS 0x1B0
#define X86_PTE_MASK 0x3ff
#define X86_PTE_MASK_PAE 0x1ff
#define X86_PTE_SHIFT 12
#define X86_REPORT_INCLUDES_SEGS 0x0001
#define X86_REPORT_STANDARD_CS 0x0002
#define X86_SHARED_SYSCALL_BASE_GTE2412 0x7ffe02f8
#define X86_SHARED_SYSCALL_BASE_GTE2492 0x7ffe0300
#define X86_SHARED_SYSCALL_BASE_LT2412 0x7ffe02e0
#define X86_SHARED_SYSCALL_SIZE 0x20
#define X86_SIZE_OF_80387_REGISTERS 80
#define X86_SIZE_OF_FX_REGISTERS 128
#define X86_TRIAGE_PRCB_ADDRESS 0xffdff120U
#define X86_VALID_PFN_MASK 0xFFFFF000
#define X86_VALID_PFN_MASK_PAE 0x0000000FFFFFF000UI64
#define X86_VALID_PFN_SHIFT 12
#define X86_VENDOR_STRING_SIZE 13
Typedefs
typedef struct _ALPHA_CONTEXT ALPHA_CONTEXT
typedef struct _ALPHA_DBGKD_CONTROL_REPORT ALPHA_DBGKD_CONTROL_REPORT
typedef ULONG ALPHA_DBGKD_CONTROL_SET
typedef struct _ALPHA_NT5_CONTEXT ALPHA_NT5_CONTEXT
typedef struct _ALPHA_NT5_KPROCESSOR_STATE ALPHA_NT5_KPROCESSOR_STATE
typedef struct _AMD64_CONTEXT AMD64_CONTEXT
typedef struct _AMD64_DBGKD_CONTROL_REPORT AMD64_DBGKD_CONTROL_REPORT
typedef struct _AMD64_DBGKD_CONTROL_SET AMD64_DBGKD_CONTROL_SET
typedef struct _AMD64_DESCRIPTOR AMD64_DESCRIPTOR
typedef struct _AMD64_DYNAMIC_FUNCTION_TABLE AMD64_DYNAMIC_FUNCTION_TABLE
typedef struct _AMD64_FIBER AMD64_FIBER
typedef enum _AMD64_FUNCTION_TABLE_TYPE AMD64_FUNCTION_TABLE_TYPE
typedef struct _AMD64_KPROCESSOR_STATE AMD64_KPROCESSOR_STATE
typedef struct _AMD64_KSPECIAL_REGISTERS AMD64_KSPECIAL_REGISTERS
typedef struct _AMD64_KSWITCH_FRAME AMD64_KSWITCH_FRAME
typedef struct _AMD64_KTRAP_FRAME AMD64_KTRAP_FRAME
typedef struct _AMD64_LEGACY_SAVE_AREA AMD64_LEGACY_SAVE_AREA
typedef struct _AMD64_M128 AMD64_M128
typedef union _AMD64_UNWIND_CODE AMD64_UNWIND_CODE
typedef struct _AMD64_UNWIND_INFO AMD64_UNWIND_INFO
typedef enum _AMD64_UNWIND_OP_CODES AMD64_UNWIND_OP_CODES
typedef struct _ARM_CONTEXT ARM_CONTEXT
typedef struct _CROSS_PLATFORM_CONTEXT CROSS_PLATFORM_CONTEXT
typedef struct _CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE
typedef struct _CROSS_PLATFORM_FIBER CROSS_PLATFORM_FIBER
typedef struct _CROSS_PLATFORM_KSPECIAL_REGISTERS CROSS_PLATFORM_KSPECIAL_REGISTERS
typedef enum _DBG_STATE DBG_STATE
typedef struct _DBGKD_ANY_CONTROL_REPORT DBGKD_ANY_CONTROL_REPORT
typedef struct _DBGKD_ANY_CONTROL_SET DBGKD_ANY_CONTROL_SET
typedef struct _DBGKD_ANY_WAIT_STATE_CHANGE DBGKD_ANY_WAIT_STATE_CHANGE
typedef struct _DBGKD_BREAKPOINTEX DBGKD_BREAKPOINTEX
typedef struct _DBGKD_CLOSE_FILE DBGKD_CLOSE_FILE
typedef struct _DBGKD_COMMAND_STRING DBGKD_COMMAND_STRING
typedef struct _DBGKD_CONTINUE DBGKD_CONTINUE
typedef struct _DBGKD_CONTINUE2 DBGKD_CONTINUE2
typedef X86_DBGKD_CONTROL_REPORT DBGKD_CONTROL_REPORT
typedef struct _DBGKD_CONTROL_REQUEST DBGKD_CONTROL_REQUEST
typedef X86_DBGKD_CONTROL_SET DBGKD_CONTROL_SET
typedef struct _DBGKD_CREATE_FILE DBGKD_CREATE_FILE
typedef struct _DBGKD_DEBUG_IO DBGKD_DEBUG_IO
typedef struct _DBGKD_FILE_IO DBGKD_FILE_IO
typedef struct _DBGKD_FILL_MEMORY DBGKD_FILL_MEMORY
typedef struct _DBGKD_GET_CONTEXT DBGKD_GET_CONTEXT
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT32 DBGKD_GET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT64 DBGKD_GET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_GET_SET_BUS_DATA DBGKD_GET_SET_BUS_DATA
typedef struct _DBGKD_GET_STRING DBGKD_GET_STRING
typedef struct _DBGKD_LOAD_SYMBOLS32 DBGKD_LOAD_SYMBOLS32
typedef struct _DBGKD_LOAD_SYMBOLS64 DBGKD_LOAD_SYMBOLS64
typedef struct _DBGKD_MANIPULATE_STATE32 DBGKD_MANIPULATE_STATE32
typedef struct _DBGKD_MANIPULATE_STATE64 DBGKD_MANIPULATE_STATE64
typedef struct _DBGKD_PRINT_STRING DBGKD_PRINT_STRING
typedef struct _DBGKD_PRINT_TRACE DBGKD_PRINT_TRACE
typedef struct _DBGKD_QUERY_MEMORY DBGKD_QUERY_MEMORY
typedef struct _DBGKD_QUERY_SPECIAL_CALLS DBGKD_QUERY_SPECIAL_CALLS
typedef struct _DBGKD_READ_FILE DBGKD_READ_FILE
typedef struct _DBGKD_READ_MEMORY32 DBGKD_READ_MEMORY32
typedef struct _DBGKD_READ_MEMORY64 DBGKD_READ_MEMORY64
typedef struct _DBGKD_READ_WRITE_IO32 DBGKD_READ_WRITE_IO32
typedef struct _DBGKD_READ_WRITE_IO64 DBGKD_READ_WRITE_IO64
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED32 DBGKD_READ_WRITE_IO_EXTENDED32
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED64 DBGKD_READ_WRITE_IO_EXTENDED64
typedef struct _DBGKD_READ_WRITE_MSR DBGKD_READ_WRITE_MSR
typedef struct _DBGKD_RELEASE_BREAKPOINT DBGKD_RELEASE_BREAKPOINT
typedef struct _DBGKD_REQUEST_BREAKPOINT DBGKD_REQUEST_BREAKPOINT
typedef struct _DBGKD_RESTORE_BREAKPOINT DBGKD_RESTORE_BREAKPOINT
typedef struct _DBGKD_SEARCH_MEMORY DBGKD_SEARCH_MEMORY
typedef struct _DBGKD_SET_CONTEXT DBGKD_SET_CONTEXT
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT32 DBGKD_SET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT64 DBGKD_SET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_SET_SPECIAL_CALL32 DBGKD_SET_SPECIAL_CALL32
typedef struct _DBGKD_SET_SPECIAL_CALL64 DBGKD_SET_SPECIAL_CALL64
typedef struct _DBGKD_SWITCH_PARTITION DBGKD_SWITCH_PARTITION
typedef union _DBGKD_TRACE_DATA DBGKD_TRACE_DATA
typedef struct _DBGKD_TRACE_IO DBGKD_TRACE_IO
typedef struct _DBGKD_WAIT_STATE_CHANGE32 DBGKD_WAIT_STATE_CHANGE32
typedef struct _DBGKD_WAIT_STATE_CHANGE64 DBGKD_WAIT_STATE_CHANGE64
typedef struct _DBGKD_WRITE_BREAKPOINT32 DBGKD_WRITE_BREAKPOINT32
typedef struct _DBGKD_WRITE_BREAKPOINT64 DBGKD_WRITE_BREAKPOINT64
typedef struct _DBGKD_WRITE_FILE DBGKD_WRITE_FILE
typedef struct _DBGKD_WRITE_MEMORY32 DBGKD_WRITE_MEMORY32
typedef struct _DBGKD_WRITE_MEMORY64 DBGKD_WRITE_MEMORY64
typedef struct _DBGKM_APIMSG DBGKM_APIMSG
typedef enum _DBGKM_APINUMBER DBGKM_APINUMBER
typedef struct _DBGKM_CREATE_PROCESS DBGKM_CREATE_PROCESS
typedef struct _DBGKM_CREATE_THREAD DBGKM_CREATE_THREAD
typedef struct _DBGKM_EXCEPTION DBGKM_EXCEPTION
typedef struct _DBGKM_EXCEPTION32 DBGKM_EXCEPTION32
typedef struct _DBGKM_EXCEPTION64 DBGKM_EXCEPTION64
typedef struct _DBGKM_EXIT_PROCESS DBGKM_EXIT_PROCESS
typedef struct _DBGKM_EXIT_THREAD DBGKM_EXIT_THREAD
typedef struct _DBGKM_LOAD_DLL DBGKM_LOAD_DLL
typedef struct _DBGKM_UNLOAD_DLL DBGKM_UNLOAD_DLL
typedef struct _DBGSRV_APIMSG DBGSRV_APIMSG
typedef enum _DBGSRV_APINUMBER DBGSRV_APINUMBER
typedef struct _DBGSS_APIMSG DBGSS_APIMSG
typedef enum _DBGSS_APINUMBER DBGSS_APINUMBER
typedef struct _DBGSS_CREATE_PROCESS DBGSS_CREATE_PROCESS
typedef struct _DBGUI_APIMSG DBGUI_APIMSG
typedef enum _DBGUI_APINUMBER DBGUI_APINUMBER
typedef struct _DBGUI_CONTINUE DBGUI_CONTINUE
typedef struct _DBGUI_CREATE_PROCESS DBGUI_CREATE_PROCESS
typedef struct _DBGUI_CREATE_THREAD DBGUI_CREATE_THREAD
typedef struct _DBGUI_STOPDEBUG DBGUI_STOPDEBUG
typedef struct _DBGUI_WAIT_STATE_CHANGE DBGUI_WAIT_STATE_CHANGE
typedef enum _DEBUGOBJECTINFOCLASS DEBUGOBJECTINFOCLASS
typedef struct _DISPATCHER_HEADER32 DISPATCHER_HEADER32
typedef struct _DISPATCHER_HEADER64 DISPATCHER_HEADER64
typedef struct _IA64_CONTEXT IA64_CONTEXT
typedef struct _IA64_DBGKD_CONTROL_REPORT IA64_DBGKD_CONTROL_REPORT
typedef struct _IA64_DBGKD_CONTROL_SET IA64_DBGKD_CONTROL_SET
typedef struct _IA64_DYNAMIC_FUNCTION_TABLE IA64_DYNAMIC_FUNCTION_TABLE
typedef struct _IA64_FIBER IA64_FIBER
typedef enum _IA64_FUNCTION_TABLE_TYPE IA64_FUNCTION_TABLE_TYPE
typedef struct _IA64_KEXCEPTION_FRAME IA64_KEXCEPTION_FRAME
typedef struct _IA64_KNONVOLATILE_CONTEXT_POINTERS IA64_KNONVOLATILE_CONTEXT_POINTERS
typedef struct _IA64_KPROCESSOR_STATE IA64_KPROCESSOR_STATE
typedef struct _IA64_KSPECIAL_REGISTERS IA64_KSPECIAL_REGISTERS
typedef struct _IA64_KSWITCH_FRAME IA64_KSWITCH_FRAME
typedef struct _IA64_KTRAP_FRAME IA64_KTRAP_FRAME
typedef struct _IA64_UNWIND_INFO IA64_UNWIND_INFO
typedef struct _KAPC_STATE32 KAPC_STATE32
typedef struct _KAPC_STATE64 KAPC_STATE64
typedef struct _KD_PACKET KD_PACKET
typedef struct _KDPC32 KDPC32
typedef struct _KDPC64 KDPC64
typedef struct _KSPIN_LOCK_QUEUE32 KSPIN_LOCK_QUEUE32
typedef struct _KSPIN_LOCK_QUEUE64 KSPIN_LOCK_QUEUE64
typedef struct _PAE_ADDRESS PAE_ADDRESS
typedef struct _ALPHA_CONTEXT * PALPHA_CONTEXT
typedef struct _ALPHA_DBGKD_CONTROL_REPORT * PALPHA_DBGKD_CONTROL_REPORT
typedef ULONG * PALPHA_DBGKD_CONTROL_SET
typedef struct _ALPHA_NT5_CONTEXT * PALPHA_NT5_CONTEXT
typedef struct _ALPHA_NT5_KPROCESSOR_STATE * PALPHA_NT5_KPROCESSOR_STATE
typedef struct _AMD64_CONTEXT * PAMD64_CONTEXT
typedef struct _AMD64_DBGKD_CONTROL_REPORT * PAMD64_DBGKD_CONTROL_REPORT
typedef struct _AMD64_DBGKD_CONTROL_SET * PAMD64_DBGKD_CONTROL_SET
typedef struct _AMD64_DESCRIPTOR * PAMD64_DESCRIPTOR
typedef struct _AMD64_DYNAMIC_FUNCTION_TABLE * PAMD64_DYNAMIC_FUNCTION_TABLE
typedef struct _AMD64_FIBER * PAMD64_FIBER
typedef struct _AMD64_KPROCESSOR_STATE * PAMD64_KPROCESSOR_STATE
typedef struct _AMD64_KSPECIAL_REGISTERS * PAMD64_KSPECIAL_REGISTERS
typedef struct _AMD64_KSWITCH_FRAME * PAMD64_KSWITCH_FRAME
typedef struct _AMD64_KTRAP_FRAME * PAMD64_KTRAP_FRAME
typedef struct _AMD64_LEGACY_SAVE_AREA * PAMD64_LEGACY_SAVE_AREA
typedef struct _AMD64_M128 * PAMD64_M128
typedef union _AMD64_UNWIND_CODE * PAMD64_UNWIND_CODE
typedef struct _AMD64_UNWIND_INFO * PAMD64_UNWIND_INFO
typedef enum _AMD64_UNWIND_OP_CODES * PAMD64_UNWIND_OP_CODES
typedef struct _ARM_CONTEXT * PARM_CONTEXT
typedef struct _CROSS_PLATFORM_CONTEXT * PCROSS_PLATFORM_CONTEXT
typedef struct _CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE * PCROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE
typedef struct _CROSS_PLATFORM_FIBER * PCROSS_PLATFORM_FIBER
typedef struct _CROSS_PLATFORM_KSPECIAL_REGISTERS * PCROSS_PLATFORM_KSPECIAL_REGISTERS
typedef enum _DBG_STATE * PDBG_STATE
typedef struct _DBGKD_ANY_CONTROL_REPORT * PDBGKD_ANY_CONTROL_REPORT
typedef struct _DBGKD_ANY_CONTROL_SET * PDBGKD_ANY_CONTROL_SET
typedef struct _DBGKD_ANY_WAIT_STATE_CHANGE * PDBGKD_ANY_WAIT_STATE_CHANGE
typedef struct _DBGKD_BREAKPOINTEX * PDBGKD_BREAKPOINTEX
typedef struct _DBGKD_CLOSE_FILE * PDBGKD_CLOSE_FILE
typedef struct _DBGKD_COMMAND_STRING * PDBGKD_COMMAND_STRING
typedef struct _DBGKD_CONTINUE * PDBGKD_CONTINUE
typedef struct _DBGKD_CONTINUE2 * PDBGKD_CONTINUE2
typedef struct _DBGKD_CONTROL_REQUEST * PDBGKD_CONTROL_REQUEST
typedef struct _DBGKD_CREATE_FILE * PDBGKD_CREATE_FILE
typedef struct _DBGKD_DEBUG_IO * PDBGKD_DEBUG_IO
typedef struct _DBGKD_FILE_IO * PDBGKD_FILE_IO
typedef struct _DBGKD_FILL_MEMORY * PDBGKD_FILL_MEMORY
typedef struct _DBGKD_GET_CONTEXT * PDBGKD_GET_CONTEXT
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT32 * PDBGKD_GET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT64 * PDBGKD_GET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_GET_SET_BUS_DATA * PDBGKD_GET_SET_BUS_DATA
typedef struct _DBGKD_GET_STRING * PDBGKD_GET_STRING
typedef struct _DBGKD_LOAD_SYMBOLS32 * PDBGKD_LOAD_SYMBOLS32
typedef struct _DBGKD_LOAD_SYMBOLS64 * PDBGKD_LOAD_SYMBOLS64
typedef struct _DBGKD_MANIPULATE_STATE32 * PDBGKD_MANIPULATE_STATE32
typedef struct _DBGKD_MANIPULATE_STATE64 * PDBGKD_MANIPULATE_STATE64
typedef struct _DBGKD_PRINT_STRING * PDBGKD_PRINT_STRING
typedef struct _DBGKD_PRINT_TRACE * PDBGKD_PRINT_TRACE
typedef struct _DBGKD_QUERY_MEMORY * PDBGKD_QUERY_MEMORY
typedef struct _DBGKD_QUERY_SPECIAL_CALLS * PDBGKD_QUERY_SPECIAL_CALLS
typedef struct _DBGKD_READ_FILE * PDBGKD_READ_FILE
typedef struct _DBGKD_READ_MEMORY32 * PDBGKD_READ_MEMORY32
typedef struct _DBGKD_READ_MEMORY64 * PDBGKD_READ_MEMORY64
typedef struct _DBGKD_READ_WRITE_IO32 * PDBGKD_READ_WRITE_IO32
typedef struct _DBGKD_READ_WRITE_IO64 * PDBGKD_READ_WRITE_IO64
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED32 * PDBGKD_READ_WRITE_IO_EXTENDED32
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED64 * PDBGKD_READ_WRITE_IO_EXTENDED64
typedef struct _DBGKD_READ_WRITE_MSR * PDBGKD_READ_WRITE_MSR
typedef struct _DBGKD_RELEASE_BREAKPOINT * PDBGKD_RELEASE_BREAKPOINT
typedef struct _DBGKD_REQUEST_BREAKPOINT * PDBGKD_REQUEST_BREAKPOINT
typedef struct _DBGKD_RESTORE_BREAKPOINT * PDBGKD_RESTORE_BREAKPOINT
typedef struct _DBGKD_SEARCH_MEMORY * PDBGKD_SEARCH_MEMORY
typedef struct _DBGKD_SET_CONTEXT * PDBGKD_SET_CONTEXT
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT32 * PDBGKD_SET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT64 * PDBGKD_SET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_SET_SPECIAL_CALL32 * PDBGKD_SET_SPECIAL_CALL32
typedef struct _DBGKD_SET_SPECIAL_CALL64 * PDBGKD_SET_SPECIAL_CALL64
typedef union _DBGKD_TRACE_DATA * PDBGKD_TRACE_DATA
typedef struct _DBGKD_TRACE_IO * PDBGKD_TRACE_IO
typedef struct _DBGKD_WAIT_STATE_CHANGE32 * PDBGKD_WAIT_STATE_CHANGE32
typedef struct _DBGKD_WAIT_STATE_CHANGE64 * PDBGKD_WAIT_STATE_CHANGE64
typedef struct _DBGKD_WRITE_BREAKPOINT32 * PDBGKD_WRITE_BREAKPOINT32
typedef struct _DBGKD_WRITE_BREAKPOINT64 * PDBGKD_WRITE_BREAKPOINT64
typedef struct _DBGKD_WRITE_FILE * PDBGKD_WRITE_FILE
typedef struct _DBGKD_WRITE_MEMORY32 * PDBGKD_WRITE_MEMORY32
typedef struct _DBGKD_WRITE_MEMORY64 * PDBGKD_WRITE_MEMORY64
typedef struct _DBGKM_APIMSG * PDBGKM_APIMSG
typedef struct _DBGKM_CREATE_PROCESS * PDBGKM_CREATE_PROCESS
typedef struct _DBGKM_CREATE_THREAD * PDBGKM_CREATE_THREAD
typedef struct _DBGKM_EXCEPTION * PDBGKM_EXCEPTION
typedef struct _DBGKM_EXCEPTION32 * PDBGKM_EXCEPTION32
typedef struct _DBGKM_EXCEPTION64 * PDBGKM_EXCEPTION64
typedef struct _DBGKM_EXIT_PROCESS * PDBGKM_EXIT_PROCESS
typedef struct _DBGKM_EXIT_THREAD * PDBGKM_EXIT_THREAD
typedef struct _DBGKM_LOAD_DLL * PDBGKM_LOAD_DLL
typedef struct _DBGKM_UNLOAD_DLL * PDBGKM_UNLOAD_DLL
typedef struct _DBGSRV_APIMSG * PDBGSRV_APIMSG
typedef struct _DBGSS_APIMSG * PDBGSS_APIMSG
typedef struct _DBGSS_CREATE_PROCESS * PDBGSS_CREATE_PROCESS
typedef NTSTATUS(* PDBGSS_DBGKM_APIMSG_FILTER) (IN OUT PDBGKM_APIMSG ApiMsg)
typedef VOID(* PDBGSS_HANDLE_MSG_ROUTINE) (IN PDBGKM_APIMSG ApiMsg, IN HANDLE ReplyEvent OPTIONAL)
typedef NTSTATUS(* PDBGSS_INITIALIZE_ROUTINE) (IN HANDLE KmReplyPort, IN PDBGSS_UI_LOOKUP UiLookUpRoutine, IN PDBGSS_SUBSYSTEMKEY_LOOKUP SubsystemKeyLookupRoutine OPTIONAL, IN PDBGSS_DBGKM_APIMSG_FILTER KmApiMsgFilter OPTIONAL)
typedef NTSTATUS(* PDBGSS_SUBSYSTEMKEY_LOOKUP) (IN PCLIENT_ID AppClientId, OUT PULONG SubsystemKey, IN BOOLEAN ProcessKey)
typedef NTSTATUS(* PDBGSS_UI_LOOKUP) (IN PCLIENT_ID AppClientId, OUT PCLIENT_ID DebugUiClientId)
typedef struct _DBGUI_APIMSG * PDBGUI_APIMSG
typedef struct _DBGUI_CONTINUE * PDBGUI_CONTINUE
typedef struct _DBGUI_CREATE_PROCESS * PDBGUI_CREATE_PROCESS
typedef struct _DBGUI_CREATE_THREAD * PDBGUI_CREATE_THREAD
typedef struct _DBGUI_STOPDEBUG * PDBGUI_STOPDEBUG
typedef struct _DBGUI_WAIT_STATE_CHANGE * PDBGUI_WAIT_STATE_CHANGE
typedef enum _DEBUGOBJECTINFOCLASS * PDEBUGOBJECTINFOCLASS
typedef struct _IA64_CONTEXT * PIA64_CONTEXT
typedef struct _IA64_DBGKD_CONTROL_REPORT * PIA64_DBGKD_CONTROL_REPORT
typedef struct _IA64_DBGKD_CONTROL_SET * PIA64_DBGKD_CONTROL_SET
typedef struct _IA64_DYNAMIC_FUNCTION_TABLE * PIA64_DYNAMIC_FUNCTION_TABLE
typedef struct _IA64_FIBER * PIA64_FIBER
typedef struct _IA64_KEXCEPTION_FRAME * PIA64_KEXCEPTION_FRAME
typedef struct _IA64_KNONVOLATILE_CONTEXT_POINTERS * PIA64_KNONVOLATILE_CONTEXT_POINTERS
typedef struct _IA64_KPROCESSOR_STATE * PIA64_KPROCESSOR_STATE
typedef struct _IA64_KSPECIAL_REGISTERS * PIA64_KSPECIAL_REGISTERS
typedef struct _IA64_KSWITCH_FRAME * PIA64_KSWITCH_FRAME
typedef struct _IA64_KTRAP_FRAME * PIA64_KTRAP_FRAME
typedef struct _IA64_UNWIND_INFO * PIA64_UNWIND_INFO
typedef struct _KD_PACKET * PKD_PACKET
typedef struct _KSPIN_LOCK_QUEUE32 * PKSPIN_LOCK_QUEUE32
typedef struct _KSPIN_LOCK_QUEUE64 * PKSPIN_LOCK_QUEUE64
typedef struct _PP_LOOKASIDE_LIST32 PP_LOOKASIDE_LIST32
typedef struct _PP_LOOKASIDE_LIST64 PP_LOOKASIDE_LIST64
typedef struct _PAE_ADDRESS * PPAE_ADDRESS
typedef struct _PP_LOOKASIDE_LIST32 * PPP_LOOKASIDE_LIST32
typedef struct _PP_LOOKASIDE_LIST64 * PPP_LOOKASIDE_LIST64
typedef struct _X86_CONTEXT * PX86_CONTEXT
typedef struct _X86_DBGKD_CONTROL_REPORT * PX86_DBGKD_CONTROL_REPORT
typedef struct _X86_DBGKD_CONTROL_SET * PX86_DBGKD_CONTROL_SET
typedef struct _X86_DESCRIPTOR * PX86_DESCRIPTOR
typedef struct _X86_DESCRIPTOR_TABLE_ENTRY * PX86_DESCRIPTOR_TABLE_ENTRY
typedef struct _X86_FIBER * PX86_FIBER
typedef struct _X86_FXSAVE_FORMAT * PX86_FXSAVE_FORMAT
typedef struct _X86_KPROCESSOR_STATE * PX86_KPROCESSOR_STATE
typedef struct _X86_KSPECIAL_REGISTERS * PX86_KSPECIAL_REGISTERS
typedef struct _X86_KSWITCHFRAME * PX86_KSWITCHFRAME
typedef struct _X86_KTRAP_FRAME * PX86_KTRAP_FRAME
typedef struct _X86_KTSS * PX86_KTSS
typedef struct _X86_LDT_ENTRY * PX86_LDT_ENTRY
typedef struct _X86_NT5_CONTEXT * PX86_NT5_CONTEXT
typedef struct _X86_NT5_KPROCESSOR_STATE * PX86_NT5_KPROCESSOR_STATE
typedef struct _X86PAE_HARDWARE_PTE * PX86PAE_HARDWARE_PTE
typedef struct _X86_CONTEXT X86_CONTEXT
typedef struct _X86_DBGKD_CONTROL_REPORT X86_DBGKD_CONTROL_REPORT
typedef struct _X86_DBGKD_CONTROL_SET X86_DBGKD_CONTROL_SET
typedef struct _X86_DESCRIPTOR X86_DESCRIPTOR
typedef struct _X86_DESCRIPTOR_TABLE_ENTRY X86_DESCRIPTOR_TABLE_ENTRY
typedef struct _X86_FIBER X86_FIBER
typedef struct _X86_FLOATING_SAVE_AREA X86_FLOATING_SAVE_AREA
typedef struct _X86_FXSAVE_FORMAT X86_FXSAVE_FORMAT
typedef struct _X86_KPROCESSOR_STATE X86_KPROCESSOR_STATE
typedef struct _X86_KSPECIAL_REGISTERS X86_KSPECIAL_REGISTERS
typedef struct _X86_KSWITCHFRAME X86_KSWITCHFRAME
typedef struct _X86_KTRAP_FRAME X86_KTRAP_FRAME
typedef struct _X86_KTSS X86_KTSS
typedef struct _X86_LDT_ENTRY X86_LDT_ENTRY
typedef struct _X86_NT5_CONTEXT X86_NT5_CONTEXT
typedef struct _X86_NT5_KPROCESSOR_STATE X86_NT5_KPROCESSOR_STATE
typedef struct _X86PAE_HARDWARE_PDE X86PAE_HARDWARE_PDE
typedef X86PAE_HARDWARE_PTE X86PAE_HARDWARE_PDPTE
typedef struct _X86PAE_HARDWARE_PTE X86PAE_HARDWARE_PTE
Enumerations
enum _AMD64_FUNCTION_TABLE_TYPE { AMD64_RF_SORTED, AMD64_RF_UNSORTED, AMD64_RF_CALLBACK }
enum _AMD64_UNWIND_OP_CODES {
AMD64_UWOP_PUSH_NONVOL = 0, AMD64_UWOP_ALLOC_LARGE, AMD64_UWOP_ALLOC_SMALL, AMD64_UWOP_SET_FPREG,
AMD64_UWOP_SAVE_NONVOL, AMD64_UWOP_SAVE_NONVOL_FAR, AMD64_UWOP_SAVE_XMM, AMD64_UWOP_SAVE_XMM_FAR,
AMD64_UWOP_SAVE_XMM128, AMD64_UWOP_SAVE_XMM128_FAR, AMD64_UWOP_PUSH_MACHFRAME
}
enum _DBG_STATE {
DbgIdle, DbgReplyPending, DbgCreateThreadStateChange, DbgCreateProcessStateChange,
DbgExitThreadStateChange, DbgExitProcessStateChange, DbgExceptionStateChange, DbgBreakpointStateChange,
DbgSingleStepStateChange, DbgLoadDllStateChange, DbgUnloadDllStateChange
}
enum _DBGKM_APINUMBER {
DbgKmExceptionApi, DbgKmCreateThreadApi, DbgKmCreateProcessApi, DbgKmExitThreadApi,
DbgKmExitProcessApi, DbgKmLoadDllApi, DbgKmUnloadDllApi, DbgKmMaxApiNumber
}
enum _DBGSRV_APINUMBER { DbgSrvContinueApi, DbgSrvMaxApiNumber }
enum _DBGSS_APINUMBER {
DbgSsExceptionApi, DbgSsCreateThreadApi, DbgSsCreateProcessApi, DbgSsExitThreadApi,
DbgSsExitProcessApi, DbgSsLoadDllApi, DbgSsUnloadDllApi, DbgSsMaxApiNumber
}
enum _DBGUI_APINUMBER { DbgUiWaitStateChangeApi, DbgUiContinueApi, DbgUiStopDebugApi, DbgUiMaxApiNumber }
enum _DEBUGOBJECTINFOCLASS { DebugObjectFlags = 1, MaxDebugObjectInfoClass }
enum _IA64_FUNCTION_TABLE_TYPE { IA64_RF_SORTED, IA64_RF_UNSORTED, IA64_RF_CALLBACK }
Functions
__inline void DbgkdGetInternalBreakpoint32To64 (IN PDBGKD_GET_INTERNAL_BREAKPOINT32 r32, OUT PDBGKD_GET_INTERNAL_BREAKPOINT64 r64)
__inline void DbgkdGetInternalBreakpoint64To32 (IN PDBGKD_GET_INTERNAL_BREAKPOINT64 r64, OUT PDBGKD_GET_INTERNAL_BREAKPOINT32 r32)
__inline void DbgkdLoadSymbols32To64 (IN PDBGKD_LOAD_SYMBOLS32 Ls32, OUT PDBGKD_LOAD_SYMBOLS64 Ls64)
__inline ULONG DbgkdManipulateState32To64 (IN PDBGKD_MANIPULATE_STATE32 r32, OUT PDBGKD_MANIPULATE_STATE64 r64, OUT PULONG AdditionalDataSize)
__inline ULONG DbgkdManipulateState64To32 (IN PDBGKD_MANIPULATE_STATE64 r64, OUT PDBGKD_MANIPULATE_STATE32 r32)
__inline void DbgkdReadMemory32To64 (IN PDBGKD_READ_MEMORY32 r32, OUT PDBGKD_READ_MEMORY64 r64)
__inline void DbgkdReadMemory64To32 (IN PDBGKD_READ_MEMORY64 r64, OUT PDBGKD_READ_MEMORY32 r32)
__inline void DbgkdReadWriteIo32To64 (IN PDBGKD_READ_WRITE_IO32 r32, OUT PDBGKD_READ_WRITE_IO64 r64)
__inline void DbgkdReadWriteIo64To32 (IN PDBGKD_READ_WRITE_IO64 r64, OUT PDBGKD_READ_WRITE_IO32 r32)
__inline void DbgkdReadWriteIoExtended32To64 (IN PDBGKD_READ_WRITE_IO_EXTENDED32 r32, OUT PDBGKD_READ_WRITE_IO_EXTENDED64 r64)
__inline void DbgkdReadWriteIoExtended64To32 (IN PDBGKD_READ_WRITE_IO_EXTENDED64 r64, OUT PDBGKD_READ_WRITE_IO_EXTENDED32 r32)
__inline void DbgkdSetInternalBreakpoint64To32 (IN PDBGKD_SET_INTERNAL_BREAKPOINT64 r64, OUT PDBGKD_SET_INTERNAL_BREAKPOINT32 r32)
__inline void DbgkdSetSpecialCall64To32 (IN PDBGKD_SET_SPECIAL_CALL64 r64, OUT PDBGKD_SET_SPECIAL_CALL32 r32)
__inline void DbgkdWriteBreakpoint32To64 (IN PDBGKD_WRITE_BREAKPOINT32 r32, OUT PDBGKD_WRITE_BREAKPOINT64 r64)
__inline void DbgkdWriteBreakpoint64To32 (IN PDBGKD_WRITE_BREAKPOINT64 r64, OUT PDBGKD_WRITE_BREAKPOINT32 r32)
__inline void DbgkdWriteMemory32To64 (IN PDBGKD_WRITE_MEMORY32 r32, OUT PDBGKD_WRITE_MEMORY64 r64)
__inline void DbgkdWriteMemory64To32 (IN PDBGKD_WRITE_MEMORY64 r64, OUT PDBGKD_WRITE_MEMORY32 r32)
__inline void DbgkmException32To64 (IN PDBGKM_EXCEPTION32 E32, OUT PDBGKM_EXCEPTION64 E64)
__inline void DbgkmException64To32 (IN PDBGKM_EXCEPTION64 E64, OUT PDBGKM_EXCEPTION32 E32)
VOID NTAPI DbgSsHandleKmApiMsg (IN PDBGKM_APIMSG ApiMsg, IN HANDLE ReplyEvent OPTIONAL)
NTSTATUS NTAPI DbgSsInitialize (IN HANDLE KmReplyPort, IN PDBGSS_UI_LOOKUP UiLookUpRoutine, IN PDBGSS_SUBSYSTEMKEY_LOOKUP SubsystemKeyLookupRoutine OPTIONAL, IN PDBGSS_DBGKM_APIMSG_FILTER KmApiMsgFilter OPTIONAL)
NTSTATUS NTAPI DbgUiConnectToDbg (VOID)
NTSTATUS NTAPI DbgUiContinue (IN PCLIENT_ID AppClientId, IN NTSTATUS ContinueStatus)
NTSTATUS DbgUiConvertStateChangeStructure (IN PDBGUI_WAIT_STATE_CHANGE StateChange, OUT struct _DEBUG_EVENT *DebugEvent)
NTSTATUS DbgUiDebugActiveProcess (IN HANDLE Process)
HANDLE NTAPI DbgUiGetThreadDebugObject ()
NTSTATUS DbgUiIssueRemoteBreakin (IN HANDLE Process)
VOID DbgUiRemoteBreakin (IN PVOID Context)
VOID NTAPI DbgUiSetThreadDebugObject (IN HANDLE DebugObject)
NTSTATUS NTAPI DbgUiStopDebugging (IN HANDLE Process)
NTSTATUS NTAPI DbgUiWaitStateChange (OUT PDBGUI_WAIT_STATE_CHANGE StateChange, IN PLARGE_INTEGER Timeout OPTIONAL)
__inline void ExceptionRecord32To64 (IN PEXCEPTION_RECORD32 Ex32, OUT PEXCEPTION_RECORD64 Ex64)
__inline void ExceptionRecord64To32 (IN PEXCEPTION_RECORD64 Ex64, OUT PEXCEPTION_RECORD32 Ex32)
__inline void LoadSymbols64To32 (IN PDBGKD_LOAD_SYMBOLS64 Ls64, OUT PDBGKD_LOAD_SYMBOLS32 Ls32)
NTSTATUS NtCreateDebugObject (OUT PHANDLE DebugObjectHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Flags)
NTSTATUS NtDebugActiveProcess (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
NTSTATUS NtDebugContinue (IN HANDLE DebugObjectHandle, IN PCLIENT_ID ClientId, IN NTSTATUS ContinueStatus)
NTSTATUS NtRemoveProcessDebug (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
NTSTATUS NtSetInformationDebugObject (IN HANDLE DebugObjectHandle, IN DEBUGOBJECTINFOCLASS DebugObjectInformationClass, IN PVOID DebugInformation, IN ULONG DebugInformationLength, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS NtWaitForDebugEvent (IN HANDLE DebugObjectHandle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL, OUT PDBGUI_WAIT_STATE_CHANGE WaitStateChange)
Macro Definition Documentation
#define ALPHA_CONTEXT_ALPHA 0x00020000
Definition at line 2608 of file ntdbg.h.
#define ALPHA_CONTEXT_CONTROL (ALPHA_CONTEXT_ALPHA | 0x00000001L)
Definition at line 2609 of file ntdbg.h.
#define ALPHA_CONTEXT_FLOATING_POINT (ALPHA_CONTEXT_ALPHA | 0x00000002L)
Definition at line 2610 of file ntdbg.h.
#define ALPHA_CONTEXT_FULL
Value:
(ALPHA_CONTEXT_CONTROL | ALPHA_CONTEXT_FLOATING_POINT | \
     ALPHA_CONTEXT_INTEGER)
Definition at line 2612 of file ntdbg.h.
#define ALPHA_CONTEXT_INTEGER (ALPHA_CONTEXT_ALPHA | 0x00000004L)
Definition at line 2611 of file ntdbg.h.
#define ALPHA_DEBUG_CONTROL_SPACE_PCR 1
Definition at line 2913 of file ntdbg.h.
#define ALPHA_DEBUG_CONTROL_SPACE_PRCB 3
Definition at line 2915 of file ntdbg.h.
#define ALPHA_DEBUG_CONTROL_SPACE_TEB 6
Definition at line 2916 of file ntdbg.h.
#define ALPHA_DEBUG_CONTROL_SPACE_THREAD 2
Definition at line 2914 of file ntdbg.h.
#define ALPHA_PSR_IE 0x1
Definition at line 2600 of file ntdbg.h.
#define ALPHA_PSR_IE_MASK 0x1
Definition at line 2601 of file ntdbg.h.
#define ALPHA_PSR_IRQL 0x2
Definition at line 2602 of file ntdbg.h.
#define ALPHA_PSR_IRQL_MASK 0x7
Definition at line 2603 of file ntdbg.h.
#define ALPHA_PSR_MODE 0x0
Definition at line 2598 of file ntdbg.h.
#define ALPHA_PSR_MODE_MASK 0x1
Definition at line 2599 of file ntdbg.h.
#define ALPHA_PSR_USER_MODE 0x1
Definition at line 2597 of file ntdbg.h.
#define AMD64_BASE_VIRT 0xFFFFF6FB7DBED000UI64
Definition at line 2884 of file ntdbg.h.
#define AMD64_CONTEXT_AMD64 0x00100000
Definition at line 2628 of file ntdbg.h.
#define AMD64_CONTEXT_CONTROL (AMD64_CONTEXT_AMD64 | 0x1L)
Definition at line 2629 of file ntdbg.h.
#define AMD64_CONTEXT_DEBUG_REGISTERS (AMD64_CONTEXT_AMD64 | 0x10L)
Definition at line 2633 of file ntdbg.h.
#define AMD64_CONTEXT_FLOATING_POINT (AMD64_CONTEXT_AMD64 | 0x8L)
Definition at line 2632 of file ntdbg.h.
#define AMD64_CONTEXT_FULL (AMD64_CONTEXT_CONTROL | AMD64_CONTEXT_INTEGER | AMD64_CONTEXT_FLOATING_POINT)
Definition at line 2634 of file ntdbg.h.
#define AMD64_CONTEXT_INTEGER (AMD64_CONTEXT_AMD64 | 0x2L)
Definition at line 2630 of file ntdbg.h.
#define AMD64_CONTEXT_SEGMENTS (AMD64_CONTEXT_AMD64 | 0x4L)
Definition at line 2631 of file ntdbg.h.
#define AMD64_DEBUG_CONTROL_SPACE_KSPECIAL 2
Definition at line 2920 of file ntdbg.h.
#define AMD64_DEBUG_CONTROL_SPACE_PCR 0
Definition at line 2918 of file ntdbg.h.
#define AMD64_DEBUG_CONTROL_SPACE_PRCB 1
Definition at line 2919 of file ntdbg.h.
#define AMD64_DEBUG_CONTROL_SPACE_THREAD 3
Definition at line 2921 of file ntdbg.h.
#define AMD64_KGDT64_LAST (6 * 16)
Definition at line 2824 of file ntdbg.h.
#define AMD64_KGDT64_NULL (0 * 16)
Definition at line 2816 of file ntdbg.h.
#define AMD64_KGDT64_R0_CODE (1 * 16)
Definition at line 2817 of file ntdbg.h.
#define AMD64_KGDT64_R0_DATA (1 * 16) + 8
Definition at line 2818 of file ntdbg.h.
#define AMD64_KGDT64_R3_CMCODE (2 * 16)
Definition at line 2819 of file ntdbg.h.
#define AMD64_KGDT64_R3_CMTEB (5 * 16)
Definition at line 2823 of file ntdbg.h.
#define AMD64_KGDT64_R3_CODE (3 * 16)
Definition at line 2821 of file ntdbg.h.
#define AMD64_KGDT64_R3_DATA (2 * 16) + 8
Definition at line 2820 of file ntdbg.h.
#define AMD64_KGDT64_SYS_TSS (4 * 16)
Definition at line 2822 of file ntdbg.h.
#define AMD64_KI_USER_SHARED_DATA 0xfffff78000000000UI64
Definition at line 2786 of file ntdbg.h.
#define AMD64_KPCR_CURRENT_PRCB 0x38
Definition at line 2695 of file ntdbg.h.
#define AMD64_KPCR_KD_VERSION_BLOCK 0x108
Definition at line 2700 of file ntdbg.h.
#define AMD64_KPCR_PRCB 0x180
Definition at line 2698 of file ntdbg.h.
#define AMD64_KPCR_SELF 0x18
Definition at line 2691 of file ntdbg.h.
#define AMD64_KPCR_SIZE 0x12e0
Definition at line 2688 of file ntdbg.h.
#define AMD64_KPRCB_CONTEXT 0x120
Definition at line 2678 of file ntdbg.h.
#define AMD64_KPRCB_NUMBER 4
Definition at line 2670 of file ntdbg.h.
#define AMD64_KPRCB_SPECIAL_REG 0x40
Definition at line 2682 of file ntdbg.h.
#define AMD64_LARGE_PAGE_MASK 0x80
Definition at line 2899 of file ntdbg.h.
#define AMD64_LARGE_PAGE_SIZE (2 * 1024 * 1024)
Definition at line 2900 of file ntdbg.h.
#define AMD64_MM_PTE_PROTOTYPE_MASK 0x400
Definition at line 2888 of file ntdbg.h.
#define AMD64_MM_PTE_TRANSITION_MASK 0x800
Definition at line 2887 of file ntdbg.h.
#define AMD64_PAGE_SHIFT 12L
Definition at line 2886 of file ntdbg.h.
#define AMD64_PAGE_SIZE 0x1000
Definition at line 2885 of file ntdbg.h.
#define AMD64_PDBR_MASK AMD64_VALID_PFN_MASK
Definition at line 2901 of file ntdbg.h.
#define AMD64_PDE_MASK 0x1ff
Definition at line 2896 of file ntdbg.h.
#define AMD64_PDE_SHIFT 21
Definition at line 2895 of file ntdbg.h.
#define AMD64_PDPE_MASK 0x1ff
Definition at line 2894 of file ntdbg.h.
#define AMD64_PDPE_SHIFT 30
Definition at line 2893 of file ntdbg.h.
#define AMD64_PHYSICAL_END 0xFFFFF8FFFFFFFFFFUI64
Definition at line 2903 of file ntdbg.h.
#define AMD64_PHYSICAL_START 0xFFFFF80000000000UI64
Definition at line 2902 of file ntdbg.h.
#define AMD64_PML4E_MASK 0x1ff
Definition at line 2892 of file ntdbg.h.
#define AMD64_PML4E_SHIFT 39
Definition at line 2891 of file ntdbg.h.
#define AMD64_PTE_MASK 0x1ff
Definition at line 2898 of file ntdbg.h.
#define AMD64_PTE_SHIFT 12
Definition at line 2897 of file ntdbg.h.
#define AMD64_REPORT_INCLUDES_SEGS 0x0001
Definition at line 1873 of file ntdbg.h.
#define AMD64_REPORT_STANDARD_CS 0x0002
Definition at line 1879 of file ntdbg.h.
#define AMD64_TRIAGE_PRCB_ADDRESS 0xfffff780ffff0000UI64
Definition at line 2797 of file ntdbg.h.
#define AMD64_UNW_FLAG_CHAININFO 0x4
Definition at line 2528 of file ntdbg.h.
#define AMD64_UNW_FLAG_EHANDLER 0x1
Definition at line 2526 of file ntdbg.h.
#define AMD64_UNW_FLAG_NHANDLER 0x0
Definition at line 2525 of file ntdbg.h.
#define AMD64_UNW_FLAG_UHANDLER 0x2
Definition at line 2527 of file ntdbg.h.
#define AMD64_VALID_PFN_MASK 0x000000FFFFFFF000UI64
Definition at line 2889 of file ntdbg.h.
#define AMD64_VALID_PFN_SHIFT 12
Definition at line 2890 of file ntdbg.h.
#define ARM_CONTEXT_ARM 0x0000040
Definition at line 2637 of file ntdbg.h.
#define ARM_CONTEXT_CONTROL (ARM_CONTEXT_ARM | 0x00000001L)
Definition at line 2638 of file ntdbg.h.
#define ARM_CONTEXT_FULL (ARM_CONTEXT_CONTROL | ARM_CONTEXT_INTEGER)
Definition at line 2641 of file ntdbg.h.
#define ARM_CONTEXT_INTEGER (ARM_CONTEXT_ARM | 0x00000002L)
Definition at line 2639 of file ntdbg.h.
#define ARM_PAGE_SHIFT 12
Definition at line 2906 of file ntdbg.h.
#define ARM_PAGE_SIZE 4096
Definition at line 2905 of file ntdbg.h.
#define BREAKIN_PACKET 0x62626262
Definition at line 3123 of file ntdbg.h.
#define BREAKIN_PACKET_BYTE 0x62
Definition at line 3124 of file ntdbg.h.
#define BREAKPOINT_TABLE_SIZE 32
Definition at line 3460 of file ntdbg.h.
#define CONTROL_PACKET_LEADER 0x69696969
Definition at line 3133 of file ntdbg.h.
#define CONTROL_PACKET_LEADER_BYTE 0x69
Definition at line 3134 of file ntdbg.h.
#define COPYSE (p64, p32, f) p64->f = (ULONG64)(LONG64)(LONG)p32->f
Definition at line 46 of file ntdbg.h.
Referenced by DbgkdGetInternalBreakpoint32To64(), DbgkdLoadSymbols32To64(), DbgkdReadMemory32To64(), DbgkdReadWriteIo32To64(), DbgkdReadWriteIoExtended32To64(), DbgkdWriteBreakpoint32To64(), DbgkdWriteMemory32To64(), and ExceptionRecord32To64().
#define DBGKD_64BIT_PROTOCOL_VERSION1 5
Definition at line 3732 of file ntdbg.h.
#define DBGKD_64BIT_PROTOCOL_VERSION2 6
Definition at line 3733 of file ntdbg.h.
#define DBGKD_CACHING_CACHED 1
Definition at line 3360 of file ntdbg.h.
#define DBGKD_CACHING_UNCACHED 2
Definition at line 3361 of file ntdbg.h.
#define DBGKD_CACHING_UNKNOWN 0
Definition at line 3359 of file ntdbg.h.
#define DBGKD_CACHING_WRITE_COMBINED 3
Definition at line 3362 of file ntdbg.h.
#define DBGKD_FILL_MEMORY_PHYSICAL 0x00000002
Definition at line 3756 of file ntdbg.h.
#define DBGKD_FILL_MEMORY_VIRTUAL 0x00000001
Definition at line 3755 of file ntdbg.h.
#define DBGKD_INTERNAL_BP_FLAG_COUNTONLY 0x00000001
Definition at line 3715 of file ntdbg.h.
#define DBGKD_INTERNAL_BP_FLAG_DYING 0x00000008
Definition at line 3718 of file ntdbg.h.
#define DBGKD_INTERNAL_BP_FLAG_INVALID 0x00000002
Definition at line 3716 of file ntdbg.h.
#define DBGKD_INTERNAL_BP_FLAG_SUSPENDED 0x00000004
Definition at line 3717 of file ntdbg.h.
#define DBGKD_MAX_INTERNAL_BREAKPOINTS 20
Definition at line 3640 of file ntdbg.h.
#define DBGKD_MAXSTREAM 16
Definition at line 1827 of file ntdbg.h.
#define DBGKD_PARTITION_ALTERNATE 0x00000001
Definition at line 3789 of file ntdbg.h.
#define DBGKD_PARTITION_DEFAULT 0x00000000
Definition at line 3788 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_EXECUTE 0x00000004
Definition at line 3777 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_FIXED 0x00000008
Definition at line 3778 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_KERNEL 0x00000002
Definition at line 3771 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_PROCESS 0x00000000
Definition at line 3769 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_READ 0x00000001
Definition at line 3775 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_SESSION 0x00000001
Definition at line 3770 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_VIRTUAL 0x00000000
Definition at line 3766 of file ntdbg.h.
#define DBGKD_QUERY_MEMORY_WRITE 0x00000002
Definition at line 3776 of file ntdbg.h.
#define DbgKdAlternateStateChange 0x00010000L
Definition at line 3175 of file ntdbg.h.
#define DbgKdCauseBugCheckApi 0x00003149L
Definition at line 3335 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdCheckLowMemoryApi 0x00003159L
Definition at line 3345 of file ntdbg.h.
#define DbgKdClearAllInternalBreakpointsApi 0x0000315AL
Definition at line 3346 of file ntdbg.h.
#define DbgKdClearSpecialCallsApi 0x00003141L
Definition at line 3327 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdCloseFileApi 0x00003433L
Definition at line 4236 of file ntdbg.h.
#define DbgKdCommandStringStateChange 0x00003032L
Definition at line 3169 of file ntdbg.h.
#define DbgKdContinueApi 0x00003136L
Definition at line 3316 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdContinueApi2 0x0000313CL
Definition at line 3322 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdCreateFileApi 0x00003430L
Definition at line 4233 of file ntdbg.h.
#define DbgKdExceptionStateChange 0x00003030L
Definition at line 3167 of file ntdbg.h.
#define DbgKdFillMemoryApi 0x0000315BL
Definition at line 3347 of file ntdbg.h.
#define DbgKdGetBusDataApi 0x00003157L
Definition at line 3343 of file ntdbg.h.
#define DbgKdGetContextApi 0x00003132L
Definition at line 3312 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdGetInternalBreakPointApi 0x00003143L
Definition at line 3329 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdGetStringApi 0x00003231L
Definition at line 4140 of file ntdbg.h.
#define DbgKdGetVersionApi 0x00003146L
Definition at line 3332 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdLoadSymbolsStateChange 0x00003031L
Definition at line 3168 of file ntdbg.h.
#define DbgKdMaximumManipulate 0x0000315EL
Definition at line 3351 of file ntdbg.h.
#define DbgKdMaximumStateChange 0x00003033L
Definition at line 3171 of file ntdbg.h.
#define DbgKdMinimumManipulate 0x00003130L
Definition at line 3308 of file ntdbg.h.
#define DbgKdMinimumStateChange 0x00003030L
Definition at line 3165 of file ntdbg.h.
#define DbgKdPageInApi 0x00003151L
Definition at line 3337 of file ntdbg.h.
#define DbgKdPrintStringApi 0x00003230L
Definition at line 4139 of file ntdbg.h.
#define DbgKdPrintTraceApi 0x00003330L
Definition at line 4179 of file ntdbg.h.
#define DbgKdQueryMemoryApi 0x0000315CL
Definition at line 3348 of file ntdbg.h.
#define DbgKdReadControlSpaceApi 0x00003137L
Definition at line 3317 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdReadFileApi 0x00003431L
Definition at line 4234 of file ntdbg.h.
#define DbgKdReadIoSpaceApi 0x00003139L
Definition at line 3319 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdReadIoSpaceExtendedApi 0x00003144L
Definition at line 3330 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdReadMachineSpecificRegister 0x00003152L
Definition at line 3338 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdReadPhysicalMemoryApi 0x0000313DL
Definition at line 3323 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdReadVirtualMemoryApi 0x00003130L
Definition at line 3310 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdRebootApi 0x0000313BL
Definition at line 3321 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdReleaseHardwareBp 0x00004301L
Definition at line 4206 of file ntdbg.h.
#define DbgKdRequestHardwareBp 0x00004300L
Definition at line 4205 of file ntdbg.h.
#define DbgKdRestoreBreakPointApi 0x00003135L
Definition at line 3315 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdRestoreBreakPointExApi 0x00003148L
Definition at line 3334 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdSearchMemoryApi 0x00003156L
Definition at line 3342 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdSetBusDataApi 0x00003158L
Definition at line 3344 of file ntdbg.h.
#define DbgKdSetContextApi 0x00003133L
Definition at line 3313 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdSetInternalBreakPointApi 0x00003142L
Definition at line 3328 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdSetSpecialCallApi 0x00003140L
Definition at line 3326 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdSwitchPartition 0x0000315DL
Definition at line 3349 of file ntdbg.h.
#define DbgKdSwitchProcessor 0x00003150L
Definition at line 3336 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteBreakPointApi 0x00003134L
Definition at line 3314 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteBreakPointExApi 0x00003147L
Definition at line 3333 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteControlSpaceApi 0x00003138L
Definition at line 3318 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteFileApi 0x00003432L
Definition at line 4235 of file ntdbg.h.
#define DbgKdWriteIoSpaceApi 0x0000313AL
Definition at line 3320 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteIoSpaceExtendedApi 0x00003145L
Definition at line 3331 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteMachineSpecificRegister 0x00003153L
Definition at line 3339 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWritePhysicalMemoryApi 0x0000313EL
Definition at line 3324 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DbgKdWriteVirtualMemoryApi 0x00003131L
Definition at line 3311 of file ntdbg.h.
Referenced by DbgkdManipulateState32To64(), and DbgkdManipulateState64To32().
#define DBGKM_API_MSG_LENGTH (TypeSize) ((sizeof(DBGKM_APIMSG) << 16) | (DBGKM_MSG_OVERHEAD + (TypeSize)))
Definition at line 93 of file ntdbg.h.
#define DBGKM_FORMAT_API_MSG (m, Number, TypeSize)
Value:
(m).h.u1.Length = DBGKM_API_MSG_LENGTH((TypeSize));     \
    (m).h.u2.ZeroInit = LPC_DEBUG_EVENT;                    \
    (m).ApiNumber = (Number)
Definition at line 96 of file ntdbg.h.
Referenced by DbgkCreateThread(), DbgkExitProcess(), DbgkExitThread(), DbgkForwardException(), DbgkMapViewOfSection(), and DbgkUnMapViewOfSection().
#define DBGKM_MSG_OVERHEAD (FIELD_OFFSET(DBGKM_APIMSG, u.Exception) - sizeof(PORT_MESSAGE))
Definition at line 90 of file ntdbg.h.
#define DBGSRV_API_MSG_LENGTH (TypeSize) ((sizeof(DBGSRV_APIMSG) << 16) | (DBGSRV_MSG_OVERHEAD))
Definition at line 217 of file ntdbg.h.
#define DBGSRV_FORMAT_API_MSG (m, Number, TypeSize, CKey)
Value:
(m).h.u1.Length = DBGSRV_API_MSG_LENGTH((TypeSize));  \
    (m).h.u2.ZeroInit = 0L;                               \
    (m).ApiNumber = (Number);                             \
    (m).ContinueKey = (PVOID)(CKey)
Definition at line 220 of file ntdbg.h.
#define DBGSRV_MSG_OVERHEAD (sizeof(DBGSRV_APIMSG) - sizeof(PORT_MESSAGE))
Definition at line 214 of file ntdbg.h.
#define DBGSS_API_MSG_LENGTH (TypeSize) ((sizeof(DBGSS_APIMSG) << 16) | (DBGSS_MSG_OVERHEAD + (TypeSize)))
Definition at line 261 of file ntdbg.h.
#define DBGSS_FORMAT_API_MSG (m, Number, TypeSize, pApp, CKey)
Value:
(m).h.u1.Length = DBGSS_API_MSG_LENGTH((TypeSize));   \
    (m).h.u2.ZeroInit = 0L;                               \
    (m).ApiNumber = (Number);                             \
    (m).AppClientId = *(pApp);                            \
    (m).ContinueKey = (PVOID)(CKey)
Definition at line 264 of file ntdbg.h.
#define DBGSS_MSG_OVERHEAD (FIELD_OFFSET(DBGSS_APIMSG, u.Exception) - sizeof(PORT_MESSAGE))
Definition at line 258 of file ntdbg.h.
#define DBGUI_API_MSG_LENGTH (TypeSize) ((sizeof(DBGUI_APIMSG) << 16) | (DBGUI_MSG_OVERHEAD + (TypeSize)))
Definition at line 307 of file ntdbg.h.
#define DBGUI_FORMAT_API_MSG (m, Number, TypeSize)
Value:
(m).h.u1.Length = DBGUI_API_MSG_LENGTH((TypeSize));     \
    (m).h.u2.ZeroInit = 0L;                               \
    (m).ApiNumber = (Number)
Definition at line 310 of file ntdbg.h.
#define DBGUI_MSG_OVERHEAD (FIELD_OFFSET(DBGUI_APIMSG, u.Continue) - sizeof(PORT_MESSAGE))
Definition at line 304 of file ntdbg.h.
#define DEBUG_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|DEBUG_READ_EVENT|DEBUG_PROCESS_ASSIGN|\
                              DEBUG_SET_INFORMATION|DEBUG_QUERY_INFORMATION)
Definition at line 4288 of file ntdbg.h.
Referenced by DbgkInitialize().
#define DEBUG_KILL_ON_CLOSE (0x1)
Definition at line 4291 of file ntdbg.h.
Referenced by NtCreateDebugObject(), and NtSetInformationDebugObject().
#define DEBUG_PROCESS_ASSIGN (0x0002)
Definition at line 4285 of file ntdbg.h.
Referenced by DbgkInitialize(), NtDebugActiveProcess(), NtRemoveProcessDebug(), and PspCreateProcess().
#define DEBUG_QUERY_INFORMATION (0x0008)
Definition at line 4287 of file ntdbg.h.
#define DEBUG_READ_EVENT (0x0001)
Definition at line 4284 of file ntdbg.h.
Referenced by DbgkInitialize(), NtDebugContinue(), and NtWaitForDebugEvent().
#define DEBUG_SET_INFORMATION (0x0004)
Definition at line 4286 of file ntdbg.h.
Referenced by NtSetInformationDebugObject().
#define DEF_KPRCB_CURRENT_THREAD_OFFSET_32 4
Definition at line 2649 of file ntdbg.h.
#define DEF_KPRCB_CURRENT_THREAD_OFFSET_64 8
Definition at line 2650 of file ntdbg.h.
#define IA64_2462_KPRCB_MHZ 0x1728
Definition at line 2666 of file ntdbg.h.
#define IA64_3555_ETHREAD_SIZE 0x440
Definition at line 2727 of file ntdbg.h.
#define IA64_3555_KTHREAD_APCPROCESS_OFFSET 0x090
Definition at line 2752 of file ntdbg.h.
#define IA64_3555_KTHREAD_BSTORE_OFFSET 0x040
Definition at line 2760 of file ntdbg.h.
#define IA64_3555_KTHREAD_BSTORELIMIT_OFFSET 0x048
Definition at line 2763 of file ntdbg.h.
#define IA64_3555_KTHREAD_KERNELSTACK_OFFSET 0x038
Definition at line 2747 of file ntdbg.h.
#define IA64_3555_KTHREAD_NEXTPROCESSOR_OFFSET 0x1F7
Definition at line 2734 of file ntdbg.h.
#define IA64_3555_KTHREAD_STATE_OFFSET 0x064
Definition at line 2757 of file ntdbg.h.
#define IA64_3555_KTHREAD_TEB_OFFSET 0x068
Definition at line 2739 of file ntdbg.h.
#define IA64_3555_PEB_IN_EPROCESS 0x300
Definition at line 2715 of file ntdbg.h.
#define IA64_BREAK_DEBUG_BASE 0x080000
Definition at line 2591 of file ntdbg.h.
#define IA64_BREAK_FASTSYS_BASE 0x1C0000
Definition at line 2593 of file ntdbg.h.
#define IA64_BREAK_SYSCALL_BASE 0x180000
Definition at line 2592 of file ntdbg.h.
#define IA64_CONTEXT_CONTROL (IA64_CONTEXT_IA64 | 0x00000001L)
Definition at line 2617 of file ntdbg.h.
#define IA64_CONTEXT_DEBUG (IA64_CONTEXT_IA64 | 0x00000010L)
Definition at line 2621 of file ntdbg.h.
#define IA64_CONTEXT_FLOATING_POINT (IA64_CONTEXT_LOWER_FLOATING_POINT | IA64_CONTEXT_HIGHER_FLOATING_POINT)
Definition at line 2623 of file ntdbg.h.
#define IA64_CONTEXT_FRAME 10
Definition at line 2568 of file ntdbg.h.
#define IA64_CONTEXT_FULL (IA64_CONTEXT_CONTROL | IA64_CONTEXT_FLOATING_POINT | IA64_CONTEXT_INTEGER | IA64_CONTEXT_IA32_CONTROL)
Definition at line 2625 of file ntdbg.h.
#define IA64_CONTEXT_HIGHER_FLOATING_POINT (IA64_CONTEXT_IA64 | 0x00000004L)
Definition at line 2619 of file ntdbg.h.
#define IA64_CONTEXT_IA32_CONTROL (IA64_CONTEXT_IA64 | 0x00000020L)
Definition at line 2622 of file ntdbg.h.
#define IA64_CONTEXT_IA64 0x00080000
Definition at line 2616 of file ntdbg.h.
#define IA64_CONTEXT_INTEGER (IA64_CONTEXT_IA64 | 0x00000008L)
Definition at line 2620 of file ntdbg.h.
#define IA64_CONTEXT_LOWER_FLOATING_POINT (IA64_CONTEXT_IA64 | 0x00000002L)
Definition at line 2618 of file ntdbg.h.
#define IA64_DBGKD_CONTROL_SET_CONTINUE_NONE 0x0000
Definition at line 1907 of file ntdbg.h.
#define IA64_DBGKD_CONTROL_SET_CONTINUE_TRACE_INSTRUCTION 0x0001
Definition at line 1908 of file ntdbg.h.
#define IA64_DBGKD_CONTROL_SET_CONTINUE_TRACE_TAKEN_BRANCH 0x0002
Definition at line 1909 of file ntdbg.h.
#define IA64_DEBUG_CONTROL_SPACE_KSPECIAL 3
Definition at line 2910 of file ntdbg.h.
#define IA64_DEBUG_CONTROL_SPACE_PCR 1
Definition at line 2908 of file ntdbg.h.
#define IA64_DEBUG_CONTROL_SPACE_PRCB 2
Definition at line 2909 of file ntdbg.h.
#define IA64_DEBUG_CONTROL_SPACE_THREAD 4
Definition at line 2911 of file ntdbg.h.
#define IA64_DEBUG_STOP_BREAKPOINT (IA64_BREAK_DEBUG_BASE+22)
Definition at line 2594 of file ntdbg.h.
#define IA64_DIRECTORY_TABLE_BASE_IN_EPROCESS 40
Definition at line 2721 of file ntdbg.h.
#define IA64_EPROCESS_SIZE 0x410
Definition at line 2710 of file ntdbg.h.
#define IA64_ETHREAD_SIZE 0x458
Definition at line 2726 of file ntdbg.h.
#define IA64_EXCEPTION_FRAME 2
Definition at line 2567 of file ntdbg.h.
#define IA64_FM_FROM_FS (Fs) (((Fs) >> IA64_IFS_IFM) & ((1UI64 << IA64_IFS_IFM_LEN) - 1))
Definition at line 2588 of file ntdbg.h.
#define IA64_FM_RRB_FR (Fm) (((Fm) >> 25) & 0x7f)
Definition at line 2584 of file ntdbg.h.
#define IA64_FM_RRB_GR (Fm) (((Fm) >> 18) & 0x7f)
Definition at line 2585 of file ntdbg.h.
#define IA64_FM_RRB_PR (Fm) (((Fm) >> 32) & 0x3f)
Definition at line 2583 of file ntdbg.h.
#define IA64_FM_SOF (Fm) ((Fm) & 0x7f)
Definition at line 2587 of file ntdbg.h.
#define IA64_FM_SOR (Fm) (((Fm) >> 14) & 0xf)
Definition at line 2586 of file ntdbg.h.
#define IA64_IFS_IFM 0
Definition at line 2570 of file ntdbg.h.
#define IA64_IFS_IFM_LEN 38
Definition at line 2571 of file ntdbg.h.
#define IA64_IFS_MBZ0 38
Definition at line 2572 of file ntdbg.h.
#define IA64_IFS_MBZ0_V 0x1ffffffi64
Definition at line 2573 of file ntdbg.h.
#define IA64_IFS_V 63
Definition at line 2574 of file ntdbg.h.
#define IA64_IFS_V_LEN 1
Definition at line 2575 of file ntdbg.h.
#define IA64_INTERRUPT_FRAME 1
Definition at line 2566 of file ntdbg.h.
#define IA64_IP_SLOT 2
Definition at line 2559 of file ntdbg.h.
#define IA64_KI_USER_SHARED_DATA 0xe0000000fffe0000UI64
Definition at line 2785 of file ntdbg.h.
#define IA64_KPCR_BSTORE_LIMIT 0xb78
Definition at line 2703 of file ntdbg.h.
#define IA64_KPCR_INITIAL_BSTORE 0xb68
Definition at line 2702 of file ntdbg.h.
#define IA64_KPCR_INITIAL_STACK 0xb60
Definition at line 2704 of file ntdbg.h.
#define IA64_KPCR_PRCB 0xb18
Definition at line 2694 of file ntdbg.h.
#define IA64_KPCR_SIZE 0xe28
Definition at line 2687 of file ntdbg.h.
#define IA64_KPCR_STACK_LIMIT 0xb70
Definition at line 2705 of file ntdbg.h.
#define IA64_KPRCB_CONTEXT 0x190
Definition at line 2677 of file ntdbg.h.
#define IA64_KPRCB_NUMBER 0x20
Definition at line 2669 of file ntdbg.h.
#define IA64_KPRCB_PCR_PAGE 0x38
Definition at line 2674 of file ntdbg.h.
#define IA64_KPRCB_PROCESSOR_MODEL 0x50
Definition at line 2653 of file ntdbg.h.
#define IA64_KPRCB_SIZE 0x1A40
Definition at line 2647 of file ntdbg.h.
#define IA64_KPRCB_SPECIAL_REG 0xc00
Definition at line 2681 of file ntdbg.h.
#define IA64_KPRCB_VENDOR_STRING 0x70
Definition at line 2660 of file ntdbg.h.
#define IA64_KTHREAD_APCPROCESS_OFFSET 0x098
Definition at line 2751 of file ntdbg.h.
#define IA64_KTHREAD_BSTORE_OFFSET 0x038
Definition at line 2759 of file ntdbg.h.
#define IA64_KTHREAD_BSTORELIMIT_OFFSET 0x040
Definition at line 2762 of file ntdbg.h.
#define IA64_KTHREAD_INITSTACK_OFFSET 0x028
Definition at line 2742 of file ntdbg.h.
#define IA64_KTHREAD_KERNELSTACK_OFFSET 0x060
Definition at line 2746 of file ntdbg.h.
#define IA64_KTHREAD_NEXTPROCESSOR_OFFSET 0x23b
Definition at line 2733 of file ntdbg.h.
#define IA64_KTHREAD_STATE_OFFSET 0x071
Definition at line 2756 of file ntdbg.h.
#define IA64_KTHREAD_TEB_OFFSET 0x050
Definition at line 2738 of file ntdbg.h.
#define IA64_KTRAP_FRAME_ARGUMENTS (8 * 8)
Definition at line 2388 of file ntdbg.h.
#define IA64_LARGE_PAGE_PDE_MARK 4
Definition at line 2877 of file ntdbg.h.
#define IA64_LARGE_PAGE_PDE_MASK 0x1c
Definition at line 2876 of file ntdbg.h.
#define IA64_LARGE_PAGE_SIZE 0x800000
Definition at line 2878 of file ntdbg.h.
#define IA64_MM_EPC_VA 0xe0000000ffa00000
Definition at line 2563 of file ntdbg.h.
#define IA64_MM_PTE_PROTOTYPE_MASK 0x02
Definition at line 2854 of file ntdbg.h.
#define IA64_MM_PTE_TRANSITION_MASK 0x80
Definition at line 2853 of file ntdbg.h.
#define IA64_NAT_BITS_PER_RNAT_REG 63
Definition at line 2581 of file ntdbg.h.
#define IA64_PAGE_SHIFT 13L
Definition at line 2852 of file ntdbg.h.
#define IA64_PAGE_SIZE 0x2000
Definition at line 2851 of file ntdbg.h.
#define IA64_PCID_IN_EPROCESS 0x260
Definition at line 2719 of file ntdbg.h.
#define IA64_PDE1_SHIFT 33
Definition at line 2857 of file ntdbg.h.
#define IA64_PDE2_SHIFT 23
Definition at line 2858 of file ntdbg.h.
#define IA64_PDE_MASK 0x3ff
Definition at line 2859 of file ntdbg.h.
#define IA64_PEB_IN_EPROCESS 0x2D0
Definition at line 2714 of file ntdbg.h.
#define IA64_PFS_EC_MASK 0x3F
Definition at line 2578 of file ntdbg.h.
#define IA64_PFS_EC_SHIFT 52
Definition at line 2576 of file ntdbg.h.
#define IA64_PFS_EC_SIZE 6
Definition at line 2577 of file ntdbg.h.
#define IA64_PFS_SIZE_MASK 0x7F
Definition at line 2580 of file ntdbg.h.
#define IA64_PFS_SIZE_SHIFT 7
Definition at line 2579 of file ntdbg.h.
#define IA64_PHYSICAL1_END 0x80000FFFFFFFFFFFUI64
Definition at line 2863 of file ntdbg.h.
#define IA64_PHYSICAL1_START 0x8000000000000000UI64
Definition at line 2862 of file ntdbg.h.
#define IA64_PHYSICAL2_END 0xA0000FFFFFFFFFFFUI64
Definition at line 2865 of file ntdbg.h.
#define IA64_PHYSICAL2_START 0xA000000000000000UI64
Definition at line 2864 of file ntdbg.h.
#define IA64_PHYSICAL3_END 0xE0000000BFFFFFFFUI64
Definition at line 2867 of file ntdbg.h.
#define IA64_PHYSICAL3_START 0xE000000080000000UI64
Definition at line 2866 of file ntdbg.h.
#define IA64_PTA_BASE_MASK 0x1FFFFFFFFFFF8000UI64
Definition at line 2868 of file ntdbg.h.
#define IA64_PTE_MASK 0x3ff
Definition at line 2861 of file ntdbg.h.
#define IA64_PTE_SHIFT 13
Definition at line 2860 of file ntdbg.h.
#define IA64_REGION_COUNT 8
Definition at line 2871 of file ntdbg.h.
#define IA64_REGION_KERNEL 7
Definition at line 2874 of file ntdbg.h.
#define IA64_REGION_MASK 0xE000000000000000UI64
Definition at line 2869 of file ntdbg.h.
#define IA64_REGION_SESSION 1
Definition at line 2873 of file ntdbg.h.
#define IA64_REGION_SHIFT 61
Definition at line 2870 of file ntdbg.h.
#define IA64_REGION_USER 0
Definition at line 2872 of file ntdbg.h.
#define IA64_RF_BEGIN_ADDRESS (Base, RF) (((ULONG64) Base + (RF)->BeginAddress) & (0xFFFFFFFFFFFFFFF0))
Definition at line 2945 of file ntdbg.h.
#define IA64_RF_END_ADDRESS (Base, RF) (((ULONG64) Base + (RF)->EndAddress+15) & (0xFFFFFFFFFFFFFFF0))
Definition at line 2946 of file ntdbg.h.
#define IA64_RNAT_ALIGNMENT (IA64_NAT_BITS_PER_RNAT_REG << 3)
Definition at line 2582 of file ntdbg.h.
#define IA64_STACK_SCRATCH_AREA 16
Definition at line 2564 of file ntdbg.h.
#define IA64_SYSCALL_FRAME 0
Definition at line 2565 of file ntdbg.h.
#define IA64_TEB_BSTORE_BASE 0x1788
Definition at line 2777 of file ntdbg.h.
#define IA64_TRIAGE_PRCB_ADDRESS 0xe0000000ffff0000UI64
Definition at line 2796 of file ntdbg.h.
#define IA64_VALID_PFN_MASK 0x0007FFFFFFFFE000UI64
Definition at line 2855 of file ntdbg.h.
#define IA64_VALID_PFN_SHIFT 13
Definition at line 2856 of file ntdbg.h.
#define IA64_VHPT_MASK 0x000000FFFFFF8000UI64
Definition at line 2875 of file ntdbg.h.
#define Ia64InsertIPSlotNumber (IP, SlotNumber)
Value:
/* Intel-IA64-Filler */  \
                ((IP) | (SlotNumber << IA64_IP_SLOT))
Definition at line 2560 of file ntdbg.h.
#define INITIAL_PACKET_ID 0x80800000
Definition at line 3115 of file ntdbg.h.
#define KD_HIBERNATE (-2)
Definition at line 3178 of file ntdbg.h.
#define KD_REBOOT (-1)
Definition at line 3177 of file ntdbg.h.
#define MAXIMUM_SUPPORTED_EXTENSION 512
Definition at line 640 of file ntdbg.h.
Referenced by KeContextFromKframes(), and KeContextToKframes().
#define MODULE_LIST_FROM_PEBLDR32 12
Definition at line 2774 of file ntdbg.h.
#define MODULE_LIST_FROM_PEBLDR64 16
Definition at line 2775 of file ntdbg.h.
#define NT51_POOL_SMALL_LISTS 32
Definition at line 547 of file ntdbg.h.
#define OldVlm1 0x00003154L
Definition at line 3340 of file ntdbg.h.
#define OldVlm2 0x00003155L
Definition at line 3341 of file ntdbg.h.
#define PACKET_LEADER 0x30303030
Definition at line 3130 of file ntdbg.h.
#define PACKET_LEADER_BYTE 0x30
Definition at line 3131 of file ntdbg.h.
#define PACKET_MAX_SIZE 4000
Definition at line 3114 of file ntdbg.h.
#define PACKET_TRAILING_BYTE 0xAA
Definition at line 3140 of file ntdbg.h.
#define PACKET_TYPE_KD_ACKNOWLEDGE 4
Definition at line 3150 of file ntdbg.h.
#define PACKET_TYPE_KD_CONTROL_REQUEST 10
Definition at line 3156 of file ntdbg.h.
#define PACKET_TYPE_KD_DEBUG_IO 3
Definition at line 3149 of file ntdbg.h.
#define PACKET_TYPE_KD_FILE_IO 11
Definition at line 3157 of file ntdbg.h.
#define PACKET_TYPE_KD_POLL_BREAKIN 8
Definition at line 3154 of file ntdbg.h.
#define PACKET_TYPE_KD_RESEND 5
Definition at line 3151 of file ntdbg.h.
#define PACKET_TYPE_KD_RESET 6
Definition at line 3152 of file ntdbg.h.
#define PACKET_TYPE_KD_STATE_CHANGE32 1
Definition at line 3147 of file ntdbg.h.
#define PACKET_TYPE_KD_STATE_CHANGE64 7
Definition at line 3153 of file ntdbg.h.
#define PACKET_TYPE_KD_STATE_MANIPULATE 2
Definition at line 3148 of file ntdbg.h.
#define PACKET_TYPE_KD_TRACE_IO 9
Definition at line 3155 of file ntdbg.h.
#define PACKET_TYPE_MAX 12
Definition at line 3158 of file ntdbg.h.
#define PACKET_TYPE_UNUSED 0
Definition at line 3146 of file ntdbg.h.
#define PEB_FROM_TEB32 48
Definition at line 2765 of file ntdbg.h.
#define PEB_FROM_TEB64 96
Definition at line 2766 of file ntdbg.h.
#define PEBLDR_FROM_PEB32 12
Definition at line 2771 of file ntdbg.h.
#define PEBLDR_FROM_PEB64 24
Definition at line 2772 of file ntdbg.h.
#define STACK_BASE_FROM_TEB32 4
Definition at line 2768 of file ntdbg.h.
#define STACK_BASE_FROM_TEB64 8
Definition at line 2769 of file ntdbg.h.
#define SYNC_PACKET_ID 0x00000800
Definition at line 3116 of file ntdbg.h.
#define TRACE_DATA_BUFFER_MAX_SIZE 40
Definition at line 4132 of file ntdbg.h.
#define TRACE_DATA_INSTRUCTIONS_BIG 0xffff
Definition at line 4130 of file ntdbg.h.
#define X86_1381_KPCR_SIZE 0x7f0
Definition at line 2684 of file ntdbg.h.
#define X86_1381_KPRCB_MHZ 0x53c
Definition at line 2662 of file ntdbg.h.
#define X86_1387_KPRCB_VENDOR_STRING 0x52D
Definition at line 2655 of file ntdbg.h.
#define X86_2087_KPRCB_VENDOR_STRING 0x72D
Definition at line 2656 of file ntdbg.h.
#define X86_2195_KPCR_SIZE 0xb10
Definition at line 2685 of file ntdbg.h.
#define X86_2195_KPRCB_MHZ 0x73c
Definition at line 2663 of file ntdbg.h.
#define X86_2230_KTHREAD_NEXTPROCESSOR_OFFSET 0x123
Definition at line 2730 of file ntdbg.h.
#define X86_2251_KPRCB_VENDOR_STRING 0x8AD
Definition at line 2657 of file ntdbg.h.
#define X86_2462_KPRCB_MHZ 0x8bc
Definition at line 2664 of file ntdbg.h.
#define X86_2474_KPRCB_VENDOR_STRING 0x900
Definition at line 2658 of file ntdbg.h.
#define X86_2505_KPRCB_MHZ 0x910
Definition at line 2665 of file ntdbg.h.
#define X86_3555_KTHREAD_APCPROCESS_OFFSET 0x040
Definition at line 2750 of file ntdbg.h.
#define X86_3555_KTHREAD_KERNELSTACK_OFFSET 0x020
Definition at line 2745 of file ntdbg.h.
#define X86_3555_KTHREAD_NEXTPROCESSOR_OFFSET 0x107
Definition at line 2732 of file ntdbg.h.
#define X86_3555_KTHREAD_STATE_OFFSET 0x028
Definition at line 2755 of file ntdbg.h.
#define X86_3555_KTHREAD_TEB_OFFSET 0x02C
Definition at line 2737 of file ntdbg.h.
#define X86_BASE_VIRT 0xc0300000
Definition at line 2830 of file ntdbg.h.
#define X86_BASE_VIRT_PAE 0xc0600000
Definition at line 2831 of file ntdbg.h.
#define X86_CONTEXT_X86 0x00010000
Definition at line 2606 of file ntdbg.h.
#define X86_DIRECTORY_TABLE_BASE_IN_EPROCESS 24
Definition at line 2722 of file ntdbg.h.
#define X86_EFLAGS_V86_MASK 0x00020000
Definition at line 2814 of file ntdbg.h.
#define X86_ETHREAD_SIZE 0x258
Definition at line 2724 of file ntdbg.h.
#define X86_FRAME_EDITED 0xfff8
Definition at line 2812 of file ntdbg.h.
#define X86_KGDT_DF_TSS 80
Definition at line 2809 of file ntdbg.h.
#define X86_KGDT_LDT 72
Definition at line 2808 of file ntdbg.h.
#define X86_KGDT_NMI_TSS 88
Definition at line 2810 of file ntdbg.h.
#define X86_KGDT_NULL 0
Definition at line 2799 of file ntdbg.h.
#define X86_KGDT_R0_CODE 8
Definition at line 2800 of file ntdbg.h.
#define X86_KGDT_R0_DATA 16
Definition at line 2801 of file ntdbg.h.
#define X86_KGDT_R0_PCR 48
Definition at line 2805 of file ntdbg.h.
#define X86_KGDT_R3_CODE 24
Definition at line 2802 of file ntdbg.h.
#define X86_KGDT_R3_DATA 32
Definition at line 2803 of file ntdbg.h.
#define X86_KGDT_R3_TEB 56
Definition at line 2806 of file ntdbg.h.
#define X86_KGDT_TSS 40
Definition at line 2804 of file ntdbg.h.
#define X86_KGDT_VDM_TILE 64
Definition at line 2807 of file ntdbg.h.
#define X86_KI_USER_SHARED_DATA 0xffdf0000U
Definition at line 2784 of file ntdbg.h.
#define X86_KPCR_PRCB 0x20
Definition at line 2693 of file ntdbg.h.
#define X86_KPCR_PRCB_DATA 0x120
Definition at line 2697 of file ntdbg.h.
#define X86_KPCR_SELF_PCR 0x1c
Definition at line 2690 of file ntdbg.h.
#define X86_KPCR_SIZE 0xd70
Definition at line 2686 of file ntdbg.h.
#define X86_KPRCB_CONTEXT 0x1c
Definition at line 2676 of file ntdbg.h.
#define X86_KPRCB_CPU_TYPE 0x18
Definition at line 2652 of file ntdbg.h.
#define X86_KPRCB_DPC_ROUTINE_ACTIVE 0x874
Definition at line 2672 of file ntdbg.h.
#define X86_KPRCB_NUMBER 0x10
Definition at line 2668 of file ntdbg.h.
#define X86_KPRCB_SPECIAL_REG 0x2e8
Definition at line 2680 of file ntdbg.h.
#define X86_KTHREAD_APCPROCESS_OFFSET 0x044
Definition at line 2749 of file ntdbg.h.
#define X86_KTHREAD_INITSTACK_OFFSET 0x018
Definition at line 2741 of file ntdbg.h.
#define X86_KTHREAD_KERNELSTACK_OFFSET 0x028
Definition at line 2744 of file ntdbg.h.
#define X86_KTHREAD_NEXTPROCESSOR_OFFSET 0x11f
Definition at line 2729 of file ntdbg.h.
#define X86_KTHREAD_STATE_OFFSET 0x02d
Definition at line 2754 of file ntdbg.h.
#define X86_KTHREAD_TEB_OFFSET 0x020
Definition at line 2736 of file ntdbg.h.
#define X86_LARGE_PAGE_MASK 0x80
Definition at line 2846 of file ntdbg.h.
#define X86_LARGE_PAGE_SIZE (4 * 1024 * 1024)
Definition at line 2847 of file ntdbg.h.
#define X86_LARGE_PAGE_SIZE_PAE (2 * 1024 * 1024)
Definition at line 2848 of file ntdbg.h.
#define X86_MAX_RING 3
Definition at line 1965 of file ntdbg.h.
#define X86_MM_PTE_PROTOTYPE_MASK 0x400
Definition at line 2835 of file ntdbg.h.
#define X86_MM_PTE_TRANSITION_MASK 0x800
Definition at line 2834 of file ntdbg.h.
#define X86_MODE_MASK 1
Definition at line 2813 of file ntdbg.h.
#define X86_NT4_KPRCB_SIZE 0x9F0
Definition at line 2644 of file ntdbg.h.
#define X86_NT4_PCID_IN_EPROCESS 0x1A4
Definition at line 2718 of file ntdbg.h.
#define X86_NT4_PEB_IN_EPROCESS 0x18C
Definition at line 2713 of file ntdbg.h.
#define X86_NT511_EPROCESS_SIZE 0x278
Definition at line 2709 of file ntdbg.h.
#define X86_NT51_EPROCESS_SIZE 0x258
Definition at line 2708 of file ntdbg.h.
#define X86_NT51_ETHREAD_SIZE 0x260
Definition at line 2725 of file ntdbg.h.
#define X86_NT51_KPRCB_SIZE 0xC50
Definition at line 2646 of file ntdbg.h.
#define X86_NT51_KTHREAD_NEXTPROCESSOR_OFFSET 0x12b
Definition at line 2731 of file ntdbg.h.
#define X86_NT5_EPROCESS_SIZE 0x288
Definition at line 2707 of file ntdbg.h.
#define X86_NT5_KPRCB_SIZE 0x9F0
Definition at line 2645 of file ntdbg.h.
#define X86_PAGE_SHIFT 12L
Definition at line 2833 of file ntdbg.h.
#define X86_PAGE_SIZE 0x1000
Definition at line 2832 of file ntdbg.h.
#define X86_PCID_IN_EPROCESS 0x14C
Definition at line 2717 of file ntdbg.h.
#define X86_PDBR_MASK 0xFFFFFFE0
Definition at line 2849 of file ntdbg.h.
#define X86_PDE_MASK_PAE 0x1ff
Definition at line 2842 of file ntdbg.h.
#define X86_PDE_SHIFT 22
Definition at line 2840 of file ntdbg.h.
#define X86_PDE_SHIFT_PAE 21
Definition at line 2841 of file ntdbg.h.
#define X86_PDPE_SHIFT 30
Definition at line 2839 of file ntdbg.h.
#define X86_PEB_IN_EPROCESS 0x1B0
Definition at line 2712 of file ntdbg.h.
#define X86_PTE_MASK 0x3ff
Definition at line 2844 of file ntdbg.h.
#define X86_PTE_MASK_PAE 0x1ff
Definition at line 2845 of file ntdbg.h.
#define X86_PTE_SHIFT 12
Definition at line 2843 of file ntdbg.h.
#define X86_REPORT_INCLUDES_SEGS 0x0001
Definition at line 1842 of file ntdbg.h.
#define X86_REPORT_STANDARD_CS 0x0002
Definition at line 1848 of file ntdbg.h.
#define X86_SHARED_SYSCALL_BASE_GTE2412 0x7ffe02f8
Definition at line 2780 of file ntdbg.h.
#define X86_SHARED_SYSCALL_BASE_GTE2492 0x7ffe0300
Definition at line 2781 of file ntdbg.h.
#define X86_SHARED_SYSCALL_BASE_LT2412 0x7ffe02e0
Definition at line 2779 of file ntdbg.h.
#define X86_SHARED_SYSCALL_SIZE 0x20
Definition at line 2782 of file ntdbg.h.
#define X86_SIZE_OF_80387_REGISTERS 80
Definition at line 593 of file ntdbg.h.
#define X86_SIZE_OF_FX_REGISTERS 128
Definition at line 645 of file ntdbg.h.
#define X86_TRIAGE_PRCB_ADDRESS 0xffdff120U
Definition at line 2795 of file ntdbg.h.
#define X86_VALID_PFN_MASK 0xFFFFF000
Definition at line 2836 of file ntdbg.h.
#define X86_VALID_PFN_MASK_PAE 0x0000000FFFFFF000UI64
Definition at line 2837 of file ntdbg.h.
#define X86_VALID_PFN_SHIFT 12
Definition at line 2838 of file ntdbg.h.
#define X86_VENDOR_STRING_SIZE 13
Definition at line 2659 of file ntdbg.h.
Typedef Documentation
typedef struct _ALPHA_CONTEXT ALPHA_CONTEXT
typedef struct _ALPHA_DBGKD_CONTROL_REPORT ALPHA_DBGKD_CONTROL_REPORT
typedef ULONG ALPHA_DBGKD_CONTROL_SET
Definition at line 1905 of file ntdbg.h.
typedef struct _ALPHA_NT5_CONTEXT ALPHA_NT5_CONTEXT
typedef struct _ALPHA_NT5_KPROCESSOR_STATE ALPHA_NT5_KPROCESSOR_STATE
typedef struct _AMD64_CONTEXT AMD64_CONTEXT
typedef struct _AMD64_DBGKD_CONTROL_REPORT AMD64_DBGKD_CONTROL_REPORT
typedef struct _AMD64_DBGKD_CONTROL_SET AMD64_DBGKD_CONTROL_SET
typedef struct _AMD64_DESCRIPTOR AMD64_DESCRIPTOR
typedef struct _AMD64_DYNAMIC_FUNCTION_TABLE AMD64_DYNAMIC_FUNCTION_TABLE
typedef struct _AMD64_FIBER AMD64_FIBER
typedef enum _AMD64_FUNCTION_TABLE_TYPE AMD64_FUNCTION_TABLE_TYPE
typedef struct _AMD64_KPROCESSOR_STATE AMD64_KPROCESSOR_STATE
typedef struct _AMD64_KSPECIAL_REGISTERS AMD64_KSPECIAL_REGISTERS
typedef struct _AMD64_KSWITCH_FRAME AMD64_KSWITCH_FRAME
typedef struct _AMD64_KTRAP_FRAME AMD64_KTRAP_FRAME
typedef struct _AMD64_LEGACY_SAVE_AREA AMD64_LEGACY_SAVE_AREA
typedef struct _AMD64_M128 AMD64_M128
typedef union _AMD64_UNWIND_CODE AMD64_UNWIND_CODE
typedef struct _AMD64_UNWIND_INFO AMD64_UNWIND_INFO
typedef enum _AMD64_UNWIND_OP_CODES AMD64_UNWIND_OP_CODES
typedef struct _ARM_CONTEXT ARM_CONTEXT
typedef struct _CROSS_PLATFORM_CONTEXT CROSS_PLATFORM_CONTEXT
typedef struct _CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE
typedef struct _CROSS_PLATFORM_FIBER CROSS_PLATFORM_FIBER
typedef struct _CROSS_PLATFORM_KSPECIAL_REGISTERS CROSS_PLATFORM_KSPECIAL_REGISTERS
typedef enum _DBG_STATE DBG_STATE
typedef struct _DBGKD_ANY_CONTROL_REPORT DBGKD_ANY_CONTROL_REPORT
typedef struct _DBGKD_ANY_CONTROL_SET DBGKD_ANY_CONTROL_SET
typedef struct _DBGKD_ANY_WAIT_STATE_CHANGE DBGKD_ANY_WAIT_STATE_CHANGE
typedef struct _DBGKD_BREAKPOINTEX DBGKD_BREAKPOINTEX
typedef struct _DBGKD_CLOSE_FILE DBGKD_CLOSE_FILE
typedef struct _DBGKD_COMMAND_STRING DBGKD_COMMAND_STRING
typedef struct _DBGKD_CONTINUE DBGKD_CONTINUE
typedef struct _DBGKD_CONTINUE2 DBGKD_CONTINUE2
typedef X86_DBGKD_CONTROL_REPORT DBGKD_CONTROL_REPORT
Definition at line 3056 of file ntdbg.h.
typedef struct _DBGKD_CONTROL_REQUEST DBGKD_CONTROL_REQUEST
typedef X86_DBGKD_CONTROL_SET DBGKD_CONTROL_SET
Definition at line 3057 of file ntdbg.h.
typedef struct _DBGKD_CREATE_FILE DBGKD_CREATE_FILE
typedef struct _DBGKD_DEBUG_IO DBGKD_DEBUG_IO
typedef struct _DBGKD_FILE_IO DBGKD_FILE_IO
typedef struct _DBGKD_FILL_MEMORY DBGKD_FILL_MEMORY
typedef struct _DBGKD_GET_CONTEXT DBGKD_GET_CONTEXT
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT32 DBGKD_GET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT64 DBGKD_GET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_GET_SET_BUS_DATA DBGKD_GET_SET_BUS_DATA
typedef struct _DBGKD_GET_STRING DBGKD_GET_STRING
typedef struct _DBGKD_LOAD_SYMBOLS32 DBGKD_LOAD_SYMBOLS32
typedef struct _DBGKD_LOAD_SYMBOLS64 DBGKD_LOAD_SYMBOLS64
typedef struct _DBGKD_MANIPULATE_STATE32 DBGKD_MANIPULATE_STATE32
typedef struct _DBGKD_MANIPULATE_STATE64 DBGKD_MANIPULATE_STATE64
typedef struct _DBGKD_PRINT_STRING DBGKD_PRINT_STRING
typedef struct _DBGKD_PRINT_TRACE DBGKD_PRINT_TRACE
typedef struct _DBGKD_QUERY_MEMORY DBGKD_QUERY_MEMORY
typedef struct _DBGKD_QUERY_SPECIAL_CALLS DBGKD_QUERY_SPECIAL_CALLS
typedef struct _DBGKD_READ_FILE DBGKD_READ_FILE
typedef struct _DBGKD_READ_MEMORY32 DBGKD_READ_MEMORY32
typedef struct _DBGKD_READ_MEMORY64 DBGKD_READ_MEMORY64
typedef struct _DBGKD_READ_WRITE_IO32 DBGKD_READ_WRITE_IO32
typedef struct _DBGKD_READ_WRITE_IO64 DBGKD_READ_WRITE_IO64
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED32 DBGKD_READ_WRITE_IO_EXTENDED32
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED64 DBGKD_READ_WRITE_IO_EXTENDED64
typedef struct _DBGKD_READ_WRITE_MSR DBGKD_READ_WRITE_MSR
typedef struct _DBGKD_RELEASE_BREAKPOINT DBGKD_RELEASE_BREAKPOINT
typedef struct _DBGKD_REQUEST_BREAKPOINT DBGKD_REQUEST_BREAKPOINT
typedef struct _DBGKD_RESTORE_BREAKPOINT DBGKD_RESTORE_BREAKPOINT
typedef struct _DBGKD_SEARCH_MEMORY DBGKD_SEARCH_MEMORY
typedef struct _DBGKD_SET_CONTEXT DBGKD_SET_CONTEXT
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT32 DBGKD_SET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT64 DBGKD_SET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_SET_SPECIAL_CALL32 DBGKD_SET_SPECIAL_CALL32
typedef struct _DBGKD_SET_SPECIAL_CALL64 DBGKD_SET_SPECIAL_CALL64
typedef struct _DBGKD_SWITCH_PARTITION DBGKD_SWITCH_PARTITION
typedef union _DBGKD_TRACE_DATA DBGKD_TRACE_DATA
typedef struct _DBGKD_TRACE_IO DBGKD_TRACE_IO
typedef struct _DBGKD_WAIT_STATE_CHANGE32 DBGKD_WAIT_STATE_CHANGE32
typedef struct _DBGKD_WAIT_STATE_CHANGE64 DBGKD_WAIT_STATE_CHANGE64
typedef struct _DBGKD_WRITE_BREAKPOINT32 DBGKD_WRITE_BREAKPOINT32
typedef struct _DBGKD_WRITE_BREAKPOINT64 DBGKD_WRITE_BREAKPOINT64
typedef struct _DBGKD_WRITE_FILE DBGKD_WRITE_FILE
typedef struct _DBGKD_WRITE_MEMORY32 DBGKD_WRITE_MEMORY32
typedef struct _DBGKD_WRITE_MEMORY64 DBGKD_WRITE_MEMORY64
typedef struct _DBGKM_APIMSG DBGKM_APIMSG
typedef enum _DBGKM_APINUMBER DBGKM_APINUMBER
typedef struct _DBGKM_CREATE_PROCESS DBGKM_CREATE_PROCESS
typedef struct _DBGKM_CREATE_THREAD DBGKM_CREATE_THREAD
typedef struct _DBGKM_EXCEPTION DBGKM_EXCEPTION
typedef struct _DBGKM_EXCEPTION32 DBGKM_EXCEPTION32
typedef struct _DBGKM_EXCEPTION64 DBGKM_EXCEPTION64
typedef struct _DBGKM_EXIT_PROCESS DBGKM_EXIT_PROCESS
typedef struct _DBGKM_EXIT_THREAD DBGKM_EXIT_THREAD
typedef struct _DBGKM_LOAD_DLL DBGKM_LOAD_DLL
typedef struct _DBGKM_UNLOAD_DLL DBGKM_UNLOAD_DLL
typedef struct _DBGSRV_APIMSG DBGSRV_APIMSG
typedef enum _DBGSRV_APINUMBER DBGSRV_APINUMBER
typedef struct _DBGSS_APIMSG DBGSS_APIMSG
typedef enum _DBGSS_APINUMBER DBGSS_APINUMBER
typedef struct _DBGSS_CREATE_PROCESS DBGSS_CREATE_PROCESS
typedef struct _DBGUI_APIMSG DBGUI_APIMSG
typedef enum _DBGUI_APINUMBER DBGUI_APINUMBER
typedef struct _DBGUI_CONTINUE DBGUI_CONTINUE
typedef struct _DBGUI_CREATE_PROCESS DBGUI_CREATE_PROCESS
typedef struct _DBGUI_CREATE_THREAD DBGUI_CREATE_THREAD
typedef struct _DBGUI_STOPDEBUG DBGUI_STOPDEBUG
typedef struct _DBGUI_WAIT_STATE_CHANGE DBGUI_WAIT_STATE_CHANGE
typedef enum _DEBUGOBJECTINFOCLASS DEBUGOBJECTINFOCLASS
typedef struct _DISPATCHER_HEADER32 DISPATCHER_HEADER32
typedef struct _DISPATCHER_HEADER64 DISPATCHER_HEADER64
typedef struct _IA64_CONTEXT IA64_CONTEXT
typedef struct _IA64_DBGKD_CONTROL_REPORT IA64_DBGKD_CONTROL_REPORT
typedef struct _IA64_DBGKD_CONTROL_SET IA64_DBGKD_CONTROL_SET
typedef struct _IA64_DYNAMIC_FUNCTION_TABLE IA64_DYNAMIC_FUNCTION_TABLE
typedef struct _IA64_FIBER IA64_FIBER
typedef enum _IA64_FUNCTION_TABLE_TYPE IA64_FUNCTION_TABLE_TYPE
typedef struct _IA64_KEXCEPTION_FRAME IA64_KEXCEPTION_FRAME
typedef struct _IA64_KNONVOLATILE_CONTEXT_POINTERS IA64_KNONVOLATILE_CONTEXT_POINTERS
typedef struct _IA64_KPROCESSOR_STATE IA64_KPROCESSOR_STATE
typedef struct _IA64_KSPECIAL_REGISTERS IA64_KSPECIAL_REGISTERS
typedef struct _IA64_KSWITCH_FRAME IA64_KSWITCH_FRAME
typedef struct _IA64_KTRAP_FRAME IA64_KTRAP_FRAME
typedef struct _IA64_UNWIND_INFO IA64_UNWIND_INFO
typedef struct _KAPC_STATE32 KAPC_STATE32
typedef struct _KAPC_STATE64 KAPC_STATE64
typedef struct _KD_PACKET KD_PACKET
typedef struct _KDPC32 KDPC32
typedef struct _KDPC64 KDPC64
typedef struct _KSPIN_LOCK_QUEUE32 KSPIN_LOCK_QUEUE32
typedef struct _KSPIN_LOCK_QUEUE64 KSPIN_LOCK_QUEUE64
typedef struct _PAE_ADDRESS PAE_ADDRESS
typedef struct _ALPHA_CONTEXT * PALPHA_CONTEXT
typedef struct _ALPHA_DBGKD_CONTROL_REPORT * PALPHA_DBGKD_CONTROL_REPORT
typedef ULONG * PALPHA_DBGKD_CONTROL_SET
Definition at line 1905 of file ntdbg.h.
typedef struct _ALPHA_NT5_CONTEXT * PALPHA_NT5_CONTEXT
typedef struct _ALPHA_NT5_KPROCESSOR_STATE * PALPHA_NT5_KPROCESSOR_STATE
typedef struct _AMD64_CONTEXT * PAMD64_CONTEXT
typedef struct _AMD64_DBGKD_CONTROL_REPORT * PAMD64_DBGKD_CONTROL_REPORT
typedef struct _AMD64_DBGKD_CONTROL_SET * PAMD64_DBGKD_CONTROL_SET
typedef struct _AMD64_DESCRIPTOR * PAMD64_DESCRIPTOR
typedef struct _AMD64_DYNAMIC_FUNCTION_TABLE * PAMD64_DYNAMIC_FUNCTION_TABLE
typedef struct _AMD64_FIBER * PAMD64_FIBER
typedef struct _AMD64_KPROCESSOR_STATE * PAMD64_KPROCESSOR_STATE
typedef struct _AMD64_KSPECIAL_REGISTERS * PAMD64_KSPECIAL_REGISTERS
typedef struct _AMD64_KSWITCH_FRAME * PAMD64_KSWITCH_FRAME
typedef struct _AMD64_KTRAP_FRAME * PAMD64_KTRAP_FRAME
typedef struct _AMD64_LEGACY_SAVE_AREA * PAMD64_LEGACY_SAVE_AREA
typedef struct _AMD64_M128 * PAMD64_M128
typedef union _AMD64_UNWIND_CODE * PAMD64_UNWIND_CODE
typedef struct _AMD64_UNWIND_INFO * PAMD64_UNWIND_INFO
typedef enum _AMD64_UNWIND_OP_CODES * PAMD64_UNWIND_OP_CODES
typedef struct _ARM_CONTEXT * PARM_CONTEXT
typedef struct _CROSS_PLATFORM_CONTEXT * PCROSS_PLATFORM_CONTEXT
typedef struct _CROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE * PCROSS_PLATFORM_DYNAMIC_FUNCTION_TABLE
typedef struct _CROSS_PLATFORM_FIBER * PCROSS_PLATFORM_FIBER
typedef struct _CROSS_PLATFORM_KSPECIAL_REGISTERS * PCROSS_PLATFORM_KSPECIAL_REGISTERS
typedef enum _DBG_STATE * PDBG_STATE
typedef struct _DBGKD_ANY_CONTROL_REPORT * PDBGKD_ANY_CONTROL_REPORT
typedef struct _DBGKD_ANY_CONTROL_SET * PDBGKD_ANY_CONTROL_SET
typedef struct _DBGKD_ANY_WAIT_STATE_CHANGE * PDBGKD_ANY_WAIT_STATE_CHANGE
typedef struct _DBGKD_BREAKPOINTEX * PDBGKD_BREAKPOINTEX
typedef struct _DBGKD_CLOSE_FILE * PDBGKD_CLOSE_FILE
typedef struct _DBGKD_COMMAND_STRING * PDBGKD_COMMAND_STRING
typedef struct _DBGKD_CONTINUE * PDBGKD_CONTINUE
typedef struct _DBGKD_CONTINUE2 * PDBGKD_CONTINUE2
typedef struct _DBGKD_CONTROL_REQUEST * PDBGKD_CONTROL_REQUEST
typedef struct _DBGKD_CREATE_FILE * PDBGKD_CREATE_FILE
typedef struct _DBGKD_DEBUG_IO * PDBGKD_DEBUG_IO
typedef struct _DBGKD_FILE_IO * PDBGKD_FILE_IO
typedef struct _DBGKD_FILL_MEMORY * PDBGKD_FILL_MEMORY
typedef struct _DBGKD_GET_CONTEXT * PDBGKD_GET_CONTEXT
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT32 * PDBGKD_GET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_GET_INTERNAL_BREAKPOINT64 * PDBGKD_GET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_GET_SET_BUS_DATA * PDBGKD_GET_SET_BUS_DATA
typedef struct _DBGKD_GET_STRING * PDBGKD_GET_STRING
typedef struct _DBGKD_LOAD_SYMBOLS32 * PDBGKD_LOAD_SYMBOLS32
typedef struct _DBGKD_LOAD_SYMBOLS64 * PDBGKD_LOAD_SYMBOLS64
typedef struct _DBGKD_MANIPULATE_STATE32 * PDBGKD_MANIPULATE_STATE32
typedef struct _DBGKD_MANIPULATE_STATE64 * PDBGKD_MANIPULATE_STATE64
typedef struct _DBGKD_PRINT_STRING * PDBGKD_PRINT_STRING
typedef struct _DBGKD_PRINT_TRACE * PDBGKD_PRINT_TRACE
typedef struct _DBGKD_QUERY_MEMORY * PDBGKD_QUERY_MEMORY
typedef struct _DBGKD_QUERY_SPECIAL_CALLS * PDBGKD_QUERY_SPECIAL_CALLS
typedef struct _DBGKD_READ_FILE * PDBGKD_READ_FILE
typedef struct _DBGKD_READ_MEMORY32 * PDBGKD_READ_MEMORY32
typedef struct _DBGKD_READ_MEMORY64 * PDBGKD_READ_MEMORY64
typedef struct _DBGKD_READ_WRITE_IO32 * PDBGKD_READ_WRITE_IO32
typedef struct _DBGKD_READ_WRITE_IO64 * PDBGKD_READ_WRITE_IO64
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED32 * PDBGKD_READ_WRITE_IO_EXTENDED32
typedef struct _DBGKD_READ_WRITE_IO_EXTENDED64 * PDBGKD_READ_WRITE_IO_EXTENDED64
typedef struct _DBGKD_READ_WRITE_MSR * PDBGKD_READ_WRITE_MSR
typedef struct _DBGKD_RELEASE_BREAKPOINT * PDBGKD_RELEASE_BREAKPOINT
typedef struct _DBGKD_REQUEST_BREAKPOINT * PDBGKD_REQUEST_BREAKPOINT
typedef struct _DBGKD_RESTORE_BREAKPOINT * PDBGKD_RESTORE_BREAKPOINT
typedef struct _DBGKD_SEARCH_MEMORY * PDBGKD_SEARCH_MEMORY
typedef struct _DBGKD_SET_CONTEXT * PDBGKD_SET_CONTEXT
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT32 * PDBGKD_SET_INTERNAL_BREAKPOINT32
typedef struct _DBGKD_SET_INTERNAL_BREAKPOINT64 * PDBGKD_SET_INTERNAL_BREAKPOINT64
typedef struct _DBGKD_SET_SPECIAL_CALL32 * PDBGKD_SET_SPECIAL_CALL32
typedef struct _DBGKD_SET_SPECIAL_CALL64 * PDBGKD_SET_SPECIAL_CALL64
typedef union _DBGKD_TRACE_DATA * PDBGKD_TRACE_DATA
typedef struct _DBGKD_TRACE_IO * PDBGKD_TRACE_IO
typedef struct _DBGKD_WAIT_STATE_CHANGE32 * PDBGKD_WAIT_STATE_CHANGE32
typedef struct _DBGKD_WAIT_STATE_CHANGE64 * PDBGKD_WAIT_STATE_CHANGE64
typedef struct _DBGKD_WRITE_BREAKPOINT32 * PDBGKD_WRITE_BREAKPOINT32
typedef struct _DBGKD_WRITE_BREAKPOINT64 * PDBGKD_WRITE_BREAKPOINT64
typedef struct _DBGKD_WRITE_FILE * PDBGKD_WRITE_FILE
typedef struct _DBGKD_WRITE_MEMORY32 * PDBGKD_WRITE_MEMORY32
typedef struct _DBGKD_WRITE_MEMORY64 * PDBGKD_WRITE_MEMORY64
typedef struct _DBGKM_APIMSG * PDBGKM_APIMSG
typedef struct _DBGKM_CREATE_PROCESS * PDBGKM_CREATE_PROCESS
typedef struct _DBGKM_CREATE_THREAD * PDBGKM_CREATE_THREAD
typedef struct _DBGKM_EXCEPTION * PDBGKM_EXCEPTION
typedef struct _DBGKM_EXCEPTION32 * PDBGKM_EXCEPTION32
typedef struct _DBGKM_EXCEPTION64 * PDBGKM_EXCEPTION64
typedef struct _DBGKM_EXIT_PROCESS * PDBGKM_EXIT_PROCESS
typedef struct _DBGKM_EXIT_THREAD * PDBGKM_EXIT_THREAD
typedef struct _DBGKM_LOAD_DLL * PDBGKM_LOAD_DLL
typedef struct _DBGKM_UNLOAD_DLL * PDBGKM_UNLOAD_DLL
typedef struct _DBGSRV_APIMSG * PDBGSRV_APIMSG
typedef struct _DBGSS_APIMSG * PDBGSS_APIMSG
typedef struct _DBGSS_CREATE_PROCESS * PDBGSS_CREATE_PROCESS
typedef NTSTATUS(* PDBGSS_DBGKM_APIMSG_FILTER) (IN OUT PDBGKM_APIMSG ApiMsg)
Definition at line 381 of file ntdbg.h.
typedef VOID(* PDBGSS_HANDLE_MSG_ROUTINE) (IN PDBGKM_APIMSG ApiMsg, IN HANDLE ReplyEvent OPTIONAL)
Definition at line 423 of file ntdbg.h.
typedef NTSTATUS(* PDBGSS_INITIALIZE_ROUTINE) (IN HANDLE KmReplyPort, IN PDBGSS_UI_LOOKUP UiLookUpRoutine, IN PDBGSS_SUBSYSTEMKEY_LOOKUP SubsystemKeyLookupRoutine OPTIONAL, IN PDBGSS_DBGKM_APIMSG_FILTER KmApiMsgFilter OPTIONAL)
Definition at line 414 of file ntdbg.h.
typedef NTSTATUS(* PDBGSS_SUBSYSTEMKEY_LOOKUP) (IN PCLIENT_ID AppClientId, OUT PULONG SubsystemKey, IN BOOLEAN ProcessKey)
Definition at line 387 of file ntdbg.h.
typedef NTSTATUS(* PDBGSS_UI_LOOKUP) (IN PCLIENT_ID AppClientId, OUT PCLIENT_ID DebugUiClientId)
Definition at line 374 of file ntdbg.h.
typedef struct _DBGUI_APIMSG * PDBGUI_APIMSG
typedef struct _DBGUI_CONTINUE * PDBGUI_CONTINUE
typedef struct _DBGUI_CREATE_PROCESS * PDBGUI_CREATE_PROCESS
typedef struct _DBGUI_CREATE_THREAD * PDBGUI_CREATE_THREAD
typedef struct _DBGUI_STOPDEBUG * PDBGUI_STOPDEBUG
typedef struct _DBGUI_WAIT_STATE_CHANGE * PDBGUI_WAIT_STATE_CHANGE
typedef enum _DEBUGOBJECTINFOCLASS * PDEBUGOBJECTINFOCLASS
typedef struct _IA64_CONTEXT * PIA64_CONTEXT
typedef struct _IA64_DBGKD_CONTROL_REPORT * PIA64_DBGKD_CONTROL_REPORT
typedef struct _IA64_DBGKD_CONTROL_SET * PIA64_DBGKD_CONTROL_SET
typedef struct _IA64_DYNAMIC_FUNCTION_TABLE * PIA64_DYNAMIC_FUNCTION_TABLE
typedef struct _IA64_FIBER * PIA64_FIBER
typedef struct _IA64_KEXCEPTION_FRAME * PIA64_KEXCEPTION_FRAME
typedef struct _IA64_KNONVOLATILE_CONTEXT_POINTERS * PIA64_KNONVOLATILE_CONTEXT_POINTERS
typedef struct _IA64_KPROCESSOR_STATE * PIA64_KPROCESSOR_STATE
typedef struct _IA64_KSPECIAL_REGISTERS * PIA64_KSPECIAL_REGISTERS
typedef struct _IA64_KSWITCH_FRAME * PIA64_KSWITCH_FRAME
typedef struct _IA64_KTRAP_FRAME * PIA64_KTRAP_FRAME
typedef struct _IA64_UNWIND_INFO * PIA64_UNWIND_INFO
typedef struct _KD_PACKET * PKD_PACKET
typedef struct _KSPIN_LOCK_QUEUE32 * PKSPIN_LOCK_QUEUE32
typedef struct _KSPIN_LOCK_QUEUE64 * PKSPIN_LOCK_QUEUE64
typedef struct _PP_LOOKASIDE_LIST32 PP_LOOKASIDE_LIST32
typedef struct _PP_LOOKASIDE_LIST64 PP_LOOKASIDE_LIST64
typedef struct _PAE_ADDRESS * PPAE_ADDRESS
typedef struct _PP_LOOKASIDE_LIST32 * PPP_LOOKASIDE_LIST32
typedef struct _PP_LOOKASIDE_LIST64 * PPP_LOOKASIDE_LIST64
typedef struct _X86_CONTEXT * PX86_CONTEXT
typedef struct _X86_DBGKD_CONTROL_REPORT * PX86_DBGKD_CONTROL_REPORT
typedef struct _X86_DBGKD_CONTROL_SET * PX86_DBGKD_CONTROL_SET
typedef struct _X86_DESCRIPTOR * PX86_DESCRIPTOR
typedef struct _X86_DESCRIPTOR_TABLE_ENTRY * PX86_DESCRIPTOR_TABLE_ENTRY
typedef struct _X86_FIBER * PX86_FIBER
typedef struct _X86_FXSAVE_FORMAT * PX86_FXSAVE_FORMAT
typedef struct _X86_KPROCESSOR_STATE * PX86_KPROCESSOR_STATE
typedef struct _X86_KSPECIAL_REGISTERS * PX86_KSPECIAL_REGISTERS
typedef struct _X86_KSWITCHFRAME * PX86_KSWITCHFRAME
typedef struct _X86_KTRAP_FRAME * PX86_KTRAP_FRAME
typedef struct _X86_KTSS * PX86_KTSS
typedef struct _X86_LDT_ENTRY * PX86_LDT_ENTRY
typedef struct _X86_NT5_CONTEXT * PX86_NT5_CONTEXT
typedef struct _X86_NT5_KPROCESSOR_STATE * PX86_NT5_KPROCESSOR_STATE
typedef struct _X86PAE_HARDWARE_PTE * PX86PAE_HARDWARE_PTE
typedef struct _X86_CONTEXT X86_CONTEXT
typedef struct _X86_DBGKD_CONTROL_REPORT X86_DBGKD_CONTROL_REPORT
typedef struct _X86_DBGKD_CONTROL_SET X86_DBGKD_CONTROL_SET
typedef struct _X86_DESCRIPTOR X86_DESCRIPTOR
typedef struct _X86_DESCRIPTOR_TABLE_ENTRY X86_DESCRIPTOR_TABLE_ENTRY
typedef struct _X86_FIBER X86_FIBER
typedef struct _X86_FLOATING_SAVE_AREA X86_FLOATING_SAVE_AREA
typedef struct _X86_FXSAVE_FORMAT X86_FXSAVE_FORMAT
typedef struct _X86_KPROCESSOR_STATE X86_KPROCESSOR_STATE
typedef struct _X86_KSPECIAL_REGISTERS X86_KSPECIAL_REGISTERS
typedef struct _X86_KSWITCHFRAME X86_KSWITCHFRAME
typedef struct _X86_KTRAP_FRAME X86_KTRAP_FRAME
typedef struct _X86_KTSS X86_KTSS
typedef struct _X86_LDT_ENTRY X86_LDT_ENTRY
typedef struct _X86_NT5_CONTEXT X86_NT5_CONTEXT
typedef struct _X86_NT5_KPROCESSOR_STATE X86_NT5_KPROCESSOR_STATE
typedef struct _X86PAE_HARDWARE_PDE X86PAE_HARDWARE_PDE
typedef X86PAE_HARDWARE_PTE X86PAE_HARDWARE_PDPTE
Definition at line 3026 of file ntdbg.h.
typedef struct _X86PAE_HARDWARE_PTE X86PAE_HARDWARE_PTE
Enumeration Type Documentation
enum _AMD64_FUNCTION_TABLE_TYPE
Enumerator
AMD64_RF_SORTED
AMD64_RF_UNSORTED
AMD64_RF_CALLBACK
Definition at line 2949 of file ntdbg.h.
enum _AMD64_UNWIND_OP_CODES
Enumerator
AMD64_UWOP_PUSH_NONVOL
AMD64_UWOP_ALLOC_LARGE
AMD64_UWOP_ALLOC_SMALL
AMD64_UWOP_SET_FPREG
AMD64_UWOP_SAVE_NONVOL
AMD64_UWOP_SAVE_NONVOL_FAR
AMD64_UWOP_SAVE_XMM
AMD64_UWOP_SAVE_XMM_FAR
AMD64_UWOP_SAVE_XMM128
AMD64_UWOP_SAVE_XMM128_FAR
AMD64_UWOP_PUSH_MACHFRAME
Definition at line 2493 of file ntdbg.h.
enum _DBG_STATE
Enumerator
DbgIdle
DbgReplyPending
DbgCreateThreadStateChange
DbgCreateProcessStateChange
DbgExitThreadStateChange
DbgExitProcessStateChange
DbgExceptionStateChange
DbgBreakpointStateChange
DbgSingleStepStateChange
DbgLoadDllStateChange
DbgUnloadDllStateChange
Definition at line 244 of file ntdbg.h.
enum _DBGKM_APINUMBER
Enumerator
DbgKmExceptionApi
DbgKmCreateThreadApi
DbgKmCreateProcessApi
DbgKmExitThreadApi
DbgKmExitProcessApi
DbgKmLoadDllApi
DbgKmUnloadDllApi
DbgKmMaxApiNumber
Definition at line 101 of file ntdbg.h.
enum _DBGSRV_APINUMBER
Enumerator
DbgSrvContinueApi
DbgSrvMaxApiNumber
Definition at line 226 of file ntdbg.h.
enum _DBGSS_APINUMBER
Enumerator
DbgSsExceptionApi
DbgSsCreateThreadApi
DbgSsCreateProcessApi
DbgSsExitThreadApi
DbgSsExitProcessApi
DbgSsLoadDllApi
DbgSsUnloadDllApi
DbgSsMaxApiNumber
Definition at line 271 of file ntdbg.h.
enum _DBGUI_APINUMBER
Enumerator
DbgUiWaitStateChangeApi
DbgUiContinueApi
DbgUiStopDebugApi
DbgUiMaxApiNumber
Definition at line 315 of file ntdbg.h.
enum _DEBUGOBJECTINFOCLASS
Enumerator
DebugObjectFlags
MaxDebugObjectInfoClass
Definition at line 4293 of file ntdbg.h.
enum _IA64_FUNCTION_TABLE_TYPE
Enumerator
IA64_RF_SORTED
IA64_RF_UNSORTED
IA64_RF_CALLBACK
Definition at line 2923 of file ntdbg.h.
Function Documentation
__inline void DbgkdGetInternalBreakpoint32To64 (IN PDBGKD_GET_INTERNAL_BREAKPOINT32 r32, OUT PDBGKD_GET_INTERNAL_BREAKPOINT64 r64)
Definition at line 3685 of file ntdbg.h.
References COPYSE.
Referenced by DbgkdManipulateState32To64().
__inline void DbgkdGetInternalBreakpoint64To32 (IN PDBGKD_GET_INTERNAL_BREAKPOINT64 r64, OUT PDBGKD_GET_INTERNAL_BREAKPOINT32 r32)
Definition at line 3701 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdLoadSymbols32To64 (IN PDBGKD_LOAD_SYMBOLS32 Ls32, OUT PDBGKD_LOAD_SYMBOLS64 Ls64)
Definition at line 3203 of file ntdbg.h.
References COPYSE.
__inline ULONG DbgkdManipulateState32To64 (IN PDBGKD_MANIPULATE_STATE32 r32, OUT PDBGKD_MANIPULATE_STATE64 r64, OUT PULONG AdditionalDataSize)
Definition at line 3863 of file ntdbg.h.
References DbgKdCauseBugCheckApi, DbgKdClearSpecialCallsApi, DbgKdContinueApi, DbgKdContinueApi2, DbgKdGetContextApi, DbgkdGetInternalBreakpoint32To64(), DbgKdGetInternalBreakPointApi, DbgKdGetVersionApi, DbgKdReadControlSpaceApi, DbgKdReadIoSpaceApi, DbgKdReadIoSpaceExtendedApi, DbgKdReadMachineSpecificRegister, DbgkdReadMemory32To64(), DbgKdReadPhysicalMemoryApi, DbgKdReadVirtualMemoryApi, DbgkdReadWriteIo32To64(), DbgkdReadWriteIoExtended32To64(), DbgKdRebootApi, DbgKdRestoreBreakPointApi, DbgKdRestoreBreakPointExApi, DbgKdSearchMemoryApi, DbgKdSetContextApi, DbgKdSetInternalBreakPointApi, DbgKdSetSpecialCallApi, DbgKdSwitchProcessor, DbgkdWriteBreakpoint32To64(), DbgKdWriteBreakPointApi, DbgKdWriteBreakPointExApi, DbgKdWriteControlSpaceApi, DbgKdWriteIoSpaceApi, DbgKdWriteIoSpaceExtendedApi, DbgKdWriteMachineSpecificRegister, DbgkdWriteMemory32To64(), DbgKdWritePhysicalMemoryApi, DbgKdWriteVirtualMemoryApi, and NT_SUCCESS.
__inline ULONG DbgkdManipulateState64To32 (IN PDBGKD_MANIPULATE_STATE64 r64, OUT PDBGKD_MANIPULATE_STATE32 r32)
Definition at line 3969 of file ntdbg.h.
References DbgKdCauseBugCheckApi, DbgKdClearSpecialCallsApi, DbgKdContinueApi, DbgKdContinueApi2, DbgKdGetContextApi, DbgkdGetInternalBreakpoint64To32(), DbgKdGetInternalBreakPointApi, DbgKdGetVersionApi, DbgKdReadControlSpaceApi, DbgKdReadIoSpaceApi, DbgKdReadIoSpaceExtendedApi, DbgKdReadMachineSpecificRegister, DbgkdReadMemory64To32(), DbgKdReadPhysicalMemoryApi, DbgKdReadVirtualMemoryApi, DbgkdReadWriteIo64To32(), DbgkdReadWriteIoExtended64To32(), DbgKdRebootApi, DbgKdRestoreBreakPointApi, DbgKdRestoreBreakPointExApi, DbgKdSearchMemoryApi, DbgKdSetContextApi, DbgkdSetInternalBreakpoint64To32(), DbgKdSetInternalBreakPointApi, DbgkdSetSpecialCall64To32(), DbgKdSetSpecialCallApi, DbgKdSwitchProcessor, DbgkdWriteBreakpoint64To32(), DbgKdWriteBreakPointApi, DbgKdWriteBreakPointExApi, DbgKdWriteControlSpaceApi, DbgKdWriteIoSpaceApi, DbgKdWriteIoSpaceExtendedApi, DbgKdWriteMachineSpecificRegister, DbgkdWriteMemory64To32(), DbgKdWritePhysicalMemoryApi, and DbgKdWriteVirtualMemoryApi.
__inline void DbgkdReadMemory32To64 (IN PDBGKD_READ_MEMORY32 r32, OUT PDBGKD_READ_MEMORY64 r64)
Definition at line 3382 of file ntdbg.h.
References COPYSE.
Referenced by DbgkdManipulateState32To64().
__inline void DbgkdReadMemory64To32 (IN PDBGKD_READ_MEMORY64 r64, OUT PDBGKD_READ_MEMORY32 r32)
Definition at line 3394 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdReadWriteIo32To64 (IN PDBGKD_READ_WRITE_IO32 r32, OUT PDBGKD_READ_WRITE_IO64 r64)
Definition at line 3540 of file ntdbg.h.
References COPYSE.
Referenced by DbgkdManipulateState32To64().
__inline void DbgkdReadWriteIo64To32 (IN PDBGKD_READ_WRITE_IO64 r64, OUT PDBGKD_READ_WRITE_IO32 r32)
Definition at line 3552 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdReadWriteIoExtended32To64 (IN PDBGKD_READ_WRITE_IO_EXTENDED32 r32, OUT PDBGKD_READ_WRITE_IO_EXTENDED64 r64)
Definition at line 3582 of file ntdbg.h.
References COPYSE.
Referenced by DbgkdManipulateState32To64().
__inline void DbgkdReadWriteIoExtended64To32 (IN PDBGKD_READ_WRITE_IO_EXTENDED64 r64, OUT PDBGKD_READ_WRITE_IO_EXTENDED32 r32)
Definition at line 3597 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdSetInternalBreakpoint64To32 (IN PDBGKD_SET_INTERNAL_BREAKPOINT64 r64, OUT PDBGKD_SET_INTERNAL_BREAKPOINT32 r32)
Definition at line 3654 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdSetSpecialCall64To32 (IN PDBGKD_SET_SPECIAL_CALL64 r64, OUT PDBGKD_SET_SPECIAL_CALL32 r32)
Definition at line 3632 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdWriteBreakpoint32To64 (IN PDBGKD_WRITE_BREAKPOINT32 r32, OUT PDBGKD_WRITE_BREAKPOINT64 r64)
Definition at line 3475 of file ntdbg.h.
References COPYSE.
Referenced by DbgkdManipulateState32To64().
__inline void DbgkdWriteBreakpoint64To32 (IN PDBGKD_WRITE_BREAKPOINT64 r64, OUT PDBGKD_WRITE_BREAKPOINT32 r32)
Definition at line 3486 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkdWriteMemory32To64 (IN PDBGKD_WRITE_MEMORY32 r32, OUT PDBGKD_WRITE_MEMORY64 r64)
Definition at line 3423 of file ntdbg.h.
References COPYSE.
Referenced by DbgkdManipulateState32To64().
__inline void DbgkdWriteMemory64To32 (IN PDBGKD_WRITE_MEMORY64 r64, OUT PDBGKD_WRITE_MEMORY32 r32)
Definition at line 3435 of file ntdbg.h.
Referenced by DbgkdManipulateState64To32().
__inline void DbgkmException32To64 (IN PDBGKM_EXCEPTION32 E32, OUT PDBGKM_EXCEPTION64 E64)
Definition at line 132 of file ntdbg.h.
References ExceptionRecord32To64().
__inline void DbgkmException64To32 (IN PDBGKM_EXCEPTION64 E64, OUT PDBGKM_EXCEPTION32 E32)
Definition at line 143 of file ntdbg.h.
References ExceptionRecord64To32().
VOID NTAPI DbgSsHandleKmApiMsg (IN PDBGKM_APIMSG ApiMsg, IN HANDLE ReplyEvent OPTIONAL)
NTSTATUS NTAPI DbgSsInitialize (IN HANDLE KmReplyPort, IN PDBGSS_UI_LOOKUP UiLookUpRoutine, IN PDBGSS_SUBSYSTEMKEY_LOOKUP SubsystemKeyLookupRoutine OPTIONAL, IN PDBGSS_DBGKM_APIMSG_FILTER KmApiMsgFilter OPTIONAL)
NTSTATUS NTAPI DbgUiConnectToDbg (VOID)
NTSTATUS NTAPI DbgUiContinue (IN PCLIENT_ID AppClientId, IN NTSTATUS ContinueStatus)
NTSTATUS DbgUiConvertStateChangeStructure (IN PDBGUI_WAIT_STATE_CHANGE StateChange, OUT struct _DEBUG_EVENT * DebugEvent)
NTSTATUS DbgUiDebugActiveProcess (IN HANDLE Process)
HANDLE NTAPI DbgUiGetThreadDebugObject ()
NTSTATUS DbgUiIssueRemoteBreakin (IN HANDLE Process)
VOID DbgUiRemoteBreakin (IN PVOID Context)
VOID NTAPI DbgUiSetThreadDebugObject (IN HANDLE DebugObject)
NTSTATUS NTAPI DbgUiStopDebugging (IN HANDLE Process)
NTSTATUS NTAPI DbgUiWaitStateChange (OUT PDBGUI_WAIT_STATE_CHANGE StateChange, IN PLARGE_INTEGER Timeout OPTIONAL)
__inline void ExceptionRecord32To64 (IN PEXCEPTION_RECORD32 Ex32, OUT PEXCEPTION_RECORD64 Ex64)
Definition at line 50 of file ntdbg.h.
References COPYSE, and EXCEPTION_MAXIMUM_PARAMETERS.
Referenced by DbgkmException32To64().
__inline void ExceptionRecord64To32 (IN PEXCEPTION_RECORD64 Ex64, OUT PEXCEPTION_RECORD32 Ex32)
Definition at line 68 of file ntdbg.h.
References EXCEPTION_MAXIMUM_PARAMETERS.
Referenced by DbgkmException64To32().
__inline void LoadSymbols64To32 (IN PDBGKD_LOAD_SYMBOLS64 Ls64, OUT PDBGKD_LOAD_SYMBOLS32 Ls32)
Definition at line 3218 of file ntdbg.h.
NTSTATUS NtCreateDebugObject (OUT PHANDLE DebugObjectHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG Flags)
Definition at line 458 of file dbgkobj.c.
References DEBUG_KILL_ON_CLOSE, DEBUG_OBJECT_KILL_ON_CLOSE, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, except, ExInitializeFastMutex, ExSystemExceptionFilter(), FALSE, _DEBUG_OBJECT::Flags, Handle, InitializeListHead(), KeGetPreviousMode, KeInitializeEvent(), KernelMode, _DEBUG_OBJECT::Mutex, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), PAGED_CODE, ProbeForWriteHandle, Status, and STATUS_INVALID_PARAMETER.
NTSTATUS NtDebugActiveProcess (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
Definition at line 1457 of file dbgkobj.c.
References DbgkpPostFakeProcessCreateMessages(), DbgkpSetProcessDebugObject(), DEBUG_PROCESS_ASSIGN, ExAcquireRundownProtection(), ExReleaseRundownProtection(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsGetCurrentProcess(), PsInitialSystemProcess, PsProcessType, _EPROCESS::RundownProtect, Status, STATUS_ACCESS_DENIED, and STATUS_PROCESS_IS_TERMINATING.
NTSTATUS NtDebugContinue (IN HANDLE DebugObjectHandle, IN PCLIENT_ID ClientId, IN NTSTATUS ContinueStatus)
Definition at line 2010 of file dbgkobj.c.
References _DEBUG_EVENT::ApiMsg, _DEBUG_EVENT::ClientId, CONTAINING_RECORD, DBG_CONTINUE, DBG_EXCEPTION_HANDLED, DBG_EXCEPTION_NOT_HANDLED, DBG_TERMINATE_PROCESS, DBG_TERMINATE_THREAD, DbgkpWakeTarget(), DEBUG_EVENT_INACTIVE, DEBUG_EVENT_READ, DEBUG_READ_EVENT, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), except, ExReleaseFastMutex(), ExSystemExceptionFilter(), FALSE, _DEBUG_EVENT::Flags, _LIST_ENTRY::Flink, KeGetPreviousMode, KernelMode, KeSetEvent(), _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForReadSmallStructure, RemoveEntryList(), _DBGKM_APIMSG::ReturnedStatus, _DEBUG_EVENT::Status, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, _CLIENT_ID::UniqueProcess, and _CLIENT_ID::UniqueThread.
NTSTATUS NtRemoveProcessDebug (IN HANDLE ProcessHandle, IN HANDLE DebugObjectHandle)
Definition at line 1548 of file dbgkobj.c.
References DbgkClearProcessDebugObject(), DEBUG_PROCESS_ASSIGN, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsProcessType, and Status.
NTSTATUS NtSetInformationDebugObject (IN HANDLE DebugObjectHandle, IN DEBUGOBJECTINFOCLASS DebugObjectInformationClass, IN PVOID DebugInformation, IN ULONG DebugInformationLength, OUT PULONG ReturnLength OPTIONAL)
Definition at line 2126 of file dbgkobj.c.
References ARGUMENT_PRESENT, DEBUG_KILL_ON_CLOSE, DEBUG_OBJECT_KILL_ON_CLOSE, DEBUG_SET_INFORMATION, DebugObjectFlags, ExAcquireFastMutex(), except, ExReleaseFastMutex(), ExSystemExceptionFilter(), _DEBUG_OBJECT::Flags, KeGetPreviousMode, KernelMode, _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForRead, ProbeForWriteUlong, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS NtWaitForDebugEvent (IN HANDLE DebugObjectHandle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL, OUT PDBGUI_WAIT_STATE_CHANGE WaitStateChange)
Definition at line 1812 of file dbgkobj.c.
References ARGUMENT_PRESENT, _DEBUG_EVENT::BackoutThread, _DEBUG_EVENT::ClientId, CONTAINING_RECORD, DbgkpConvertKernelToUserStateChange(), DbgkpOpenHandles(), DEBUG_EVENT_INACTIVE, DEBUG_EVENT_READ, DEBUG_OBJECT_DELETE_PENDING, DEBUG_READ_EVENT, _DEBUG_OBJECT::EventList, _DEBUG_OBJECT::EventsPresent, ExAcquireFastMutex(), except, Executive, ExReleaseFastMutex(), ExSystemExceptionFilter(), FALSE, _DEBUG_OBJECT::Flags, _DEBUG_EVENT::Flags, _LIST_ENTRY::Flink, KeClearEvent(), KeGetPreviousMode, KeQuerySystemTime(), KernelMode, KeWaitForSingleObject(), _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), _DEBUG_EVENT::Process, _LARGE_INTEGER::QuadPart, Status, STATUS_ALERTED, STATUS_DEBUGGER_INACTIVE, STATUS_SUCCESS, STATUS_TIMEOUT, STATUS_USER_APC, _DEBUG_EVENT::Thread, TRUE, and _CLIENT_ID::UniqueProcess.