Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/cachesub.c File Reference
cachesub.c File Reference
#include "cc.h"
Macros
#define BugCheckFileId (CACHE_BUG_CHECK_CACHESUB)
#define me 0x00000002
#define RetryError(STS) (((STS) == STATUS_VERIFY_REQUIRED) || ((STS) == STATUS_FILE_LOCK_CONFLICT) || ((STS) == STATUS_ENCOUNTERED_WRITE_IN_PROGRESS))
Functions
BOOLEAN CcAcquireByteRangeForWrite (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER TargetOffset OPTIONAL, IN ULONG TargetLength, OUT PLARGE_INTEGER FileOffset, OUT PULONG Length, OUT PBCB *FirstBcb)
PBCB CcAllocateInitializeBcb (IN OUT PSHARED_CACHE_MAP SharedCacheMap OPTIONAL, IN OUT PBCB AfterBcb, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length)
VOID FASTCALL CcDeallocateBcb (IN PBCB Bcb)
BOOLEAN CcFindBcb (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN OUT PLARGE_INTEGER BeyondLastByte, OUT PBCB *Bcb)
PBITMAP_RANGE CcFindBitmapRangeToClean (IN PMBCB Mbcb, IN LONGLONG Page)
PBITMAP_RANGE CcFindBitmapRangeToDirty (IN PMBCB Mbcb, IN LONGLONG Page, IN PULONG *FreePageForSetting)
VOID CcFlushCache (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __out_opt PIO_STATUS_BLOCK IoStatus)
VOID CcFreeActiveVacb (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVACB ActiveVacb OPTIONAL, IN ULONG ActivePage, IN ULONG PageIsDirty)
LARGE_INTEGER CcGetFlushedValidData (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN CcInternalCaller)
LOGICAL CcHasInactiveViews (VOID)
BOOLEAN CcLogError (IN PFILE_OBJECT FileObject, IN PUNICODE_STRING FileName, IN NTSTATUS Error, IN NTSTATUS DeviceError, IN UCHAR IrpMajorCode)
BOOLEAN CcMapAndCopy (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVOID UserBuffer, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG OptimizeFlags, IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER ValidDataLength, IN BOOLEAN Wait)
BOOLEAN CcMapAndRead (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG ZeroFlags, IN BOOLEAN Wait, IN PVOID BaseAddress)
VOID FASTCALL CcPerformReadAhead (IN PFILE_OBJECT FileObject)
BOOLEAN CcPinFileData (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN ReadOnly, IN BOOLEAN WriteOnly, IN ULONG Flags, OUT PBCB *Bcb, OUT PVOID *BaseAddress, OUT PLARGE_INTEGER BeyondLastByte)
VOID CcReleaseByteRangeFromWrite (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN PBCB FirstBcb, IN BOOLEAN VerifyRequired)
PVOID CcRemapBcb (__in PVOID Bcb)
VOID CcRepinBcb (__in PVOID Bcb)
VOID CcScheduleReadAhead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length)
VOID CcSetDirtyInMask (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN ULONG Length)
VOID CcSetDirtyPinnedData (__in PVOID BcbVoid, __in_opt PLARGE_INTEGER Lsn)
VOID CcSetReadAheadGranularity (__in PFILE_OBJECT FileObject, __in ULONG Granularity)
NTSTATUS CcSetValidData (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER ValidDataLength)
LOGICAL CcUnmapInactiveViews (IN ULONG NumberOfViewsToUnmap)
VOID FASTCALL CcUnpinFileDataEx (IN OUT PBCB Bcb, IN BOOLEAN ReadOnly, IN UNMAP_ACTIONS UnmapAction)
VOID CcUnpinRepinnedBcb (__in PVOID Bcb, __in BOOLEAN WriteThrough, __out PIO_STATUS_BLOCK IoStatus)
VOID FASTCALL CcWriteBehind (IN PSHARED_CACHE_MAP SharedCacheMap, IN PIO_STATUS_BLOCK IoStatus)
Variables
ULONG CcMaxDirtyWrite = 0x10000
Macro Definition Documentation
#define BugCheckFileId (CACHE_BUG_CHECK_CACHESUB)
Definition at line 25 of file cachesub.c.
#define me 0x00000002
Definition at line 31 of file cachesub.c.
Referenced by CcAcquireByteRangeForWrite(), CcFindBcb(), CcFlushCache(), CcMapAndCopy(), CcPerformReadAhead(), CcPinFileData(), CcReleaseByteRangeFromWrite(), CcScheduleReadAhead(), CcSetDirtyPinnedData(), CcSetValidData(), CcUnpinFileDataEx(), CcUnpinRepinnedBcb(), and CcWriteBehind().
#define RetryError (STS) (((STS) == STATUS_VERIFY_REQUIRED) || ((STS) == STATUS_FILE_LOCK_CONFLICT) || ((STS) == STATUS_ENCOUNTERED_WRITE_IN_PROGRESS))
Definition at line 42 of file cachesub.c.
Referenced by CcFlushCache(), CcUnpinRepinnedBcb(), and CcWriteBehind().
Function Documentation
BOOLEAN CcAcquireByteRangeForWrite (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER TargetOffset OPTIONAL, IN ULONG TargetLength, OUT PLARGE_INTEGER FileOffset, OUT PULONG Length, OUT PBCB * FirstBcb)
Definition at line 2857 of file cachesub.c.
References ARGUMENT_PRESENT, ASSERT, _BITMAP_RANGE::BasePage, _BCB::BcbLinks, _BCB::BeyondLastByte, _BITMAP_RANGE::Bitmap, _MBCB::BitmapRanges, _LIST_ENTRY::Blink, BooleanFlagOn, _BCB::ByteLength, CACHE_NTC_BCB, CcAcquireMasterLockAtDpcLevel, CcDeductDirtyPages, CcExceptionFilter(), CcFindBcb(), CcFindBitmapRangeToClean(), CcInsertIntoCleanSharedCacheMapList(), CcPagesYetToWrite, CcReleaseMasterLockFromDpcLevel, CcUnpinFileData, CONTAINING_RECORD, DebugTrace, DebugTrace2, _BCB::Dirty, _BITMAP_RANGE::DirtyPages, _MBCB::DirtyPages, DISABLE_WRITE_BEHIND, ExAcquireResourceExclusiveLite(), except, FALSE, _BCB::FileOffset, _BITMAP_RANGE::FirstDirtyPage, FlagOn, _LIST_ENTRY::Flink, IsListEmpty, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _BITMAP_RANGE::LastDirtyPage, _BITMAP_RANGE::Links, MAX_WRITE_BEHIND, MAXULONG, MBCB_BITMAP_BLOCK_SIZE, me, MODIFIED_WRITE_DISABLED, _BCB::NewestLsn, _BCB::NodeTypeCode, NULL, PAGE_SHIFT, PAGE_SIZE, _MBCB::PagesToWrite, _BCB::PinCount, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _BCB::Resource, _MBCB::ResumeWritePage, SET_CLEAN, TRUE, UNPIN, and VACB_SIZE_OF_FIRST_LEVEL.
Referenced by CcFlushCache().
PBCB CcAllocateInitializeBcb (IN OUT PSHARED_CACHE_MAP SharedCacheMap OPTIONAL, IN OUT PBCB AfterBcb, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length)
Definition at line 5683 of file cachesub.c.
References ASSERT, _BCB::BcbLinks, _BCB::BeyondLastByte, _BCB::ByteLength, CACHE_NTC_BCB, CcAcquireVacbLockAtDpcLevel, CcFindBcb(), CcLockVacbLevel, CcReleaseVacbLockFromDpcLevel, DISABLE_WRITE_BEHIND, ExAllocatePoolWithTag, ExDisableResourceBoost, ExInitializeResourceLite(), FileOffset, _BCB::FileOffset, _ERESOURCE::Flag, FlagOn, InsertTailList(), _BCB::NodeTypeCode, NonPagedPool, NULL, _BCB::PinCount, _LARGE_INTEGER::QuadPart, _BCB::Resource, ResourceNeverExclusive, RtlZeroMemory, SetFlag, _BCB::SharedCacheMap, and VACB_SIZE_OF_FIRST_LEVEL.
Referenced by CcPinFileData(), and CcSetDirtyInMask().
VOID FASTCALL CcDeallocateBcb (IN PBCB Bcb)
Definition at line 5793 of file cachesub.c.
References CACHE_NTC_BCB, ExDeleteResourceLite(), and ExFreePool().
Referenced by CcDeleteBcbs(), CcDeleteMbcb(), and CcUnpinFileDataEx().
BOOLEAN CcFindBcb (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN OUT PLARGE_INTEGER BeyondLastByte, OUT PBCB * Bcb)
Definition at line 5454 of file cachesub.c.
References ASSERT, _BCB::BcbLinks, _BCB::BeyondLastByte, CACHE_NTC_BCB, CcGetBcbListHead(), CONTAINING_RECORD, DebugTrace, DebugTrace2, FALSE, FIELD_OFFSET, _BCB::FileOffset, _LIST_ENTRY::Flink, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, me, _BCB::NodeTypeCode, _LARGE_INTEGER::QuadPart, SIZE_PER_BCB_LIST, and TRUE.
Referenced by CcAcquireByteRangeForWrite(), CcAllocateInitializeBcb(), and CcPinFileData().
PBITMAP_RANGE CcFindBitmapRangeToClean (IN PMBCB Mbcb, IN LONGLONG Page)
Definition at line 2146 of file cachesub.c.
References ASSERT, _BITMAP_RANGE::BasePage, _BITMAP_RANGE::DirtyPages, _LIST_ENTRY::Flink, _BITMAP_RANGE::LastDirtyPage, and _BITMAP_RANGE::Links.
Referenced by CcAcquireByteRangeForWrite(), and CcGetFlushedValidData().
PBITMAP_RANGE CcFindBitmapRangeToDirty (IN PMBCB Mbcb, IN LONGLONG Page, IN PULONG * FreePageForSetting)
Definition at line 1985 of file cachesub.c.
References ASSERT, _BITMAP_RANGE::BasePage, _BITMAP_RANGE::Bitmap, _BITMAP_RANGE::DirtyPages, ExAllocatePoolWithTag, _BITMAP_RANGE::FirstDirtyPage, _LIST_ENTRY::Flink, InsertHeadList(), _BITMAP_RANGE::LastDirtyPage, _BITMAP_RANGE::Links, MAXULONG, MBCB_BITMAP_BLOCK_SIZE, NonPagedPool, NULL, RemoveEntryList(), and RtlZeroMemory.
Referenced by CcSetDirtyInMask().
VOID CcFlushCache (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __out_opt PIO_STATUS_BLOCK IoStatus)
Definition at line 4453 of file cachesub.c.
References _SHARED_CACHE_MAP::ActivePage, _SHARED_CACHE_MAP::ActiveVacb, ARGUMENT_PRESENT, ASSERT, CALLER_TRACKS_DIRTY_DATA, CC_REQUEUE, CcAcquireByteRangeForWrite(), CcAcquireMasterLock, CcDecrementOpenCount, CcDeferredWrites, CcDirtySharedCacheMapList, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddressIfMapped(), CcIdleDelayTick, CcIncrementOpenCount, CcLazyWriteHotSpots, CcLazyWriteIos, CcLazyWritePages, CcNoDelay, CcPostDeferredWrites(), CcReleaseByteRangeFromWrite(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), ClearFlag, DebugTrace, DebugTrace2, _FILE_OBJECT::DeviceObject, _SHARED_CACHE_MAP::DirtyPages, FALSE, FILE_DEVICE_CD_ROM, _SHARED_CACHE_MAP::FileObject, FileOffset, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, _FILE_OBJECT::FsContext, FSRTL_FLAG_USER_MAPPED_FILE, GetActiveVacbAtDpcLevel, _LARGE_INTEGER::HighPart, InsertTailList(), IsListEmpty, KeQueryTickCount(), LAZY_WRITE_OCCURRED, _SHARED_CACHE_MAP::LazyWritePassCount, LazyWriter, _LARGE_INTEGER::LowPart, MAXULONG, me, mm, MM_FLUSH_ACQUIRE_FILE, MM_FLUSH_FAIL_COLLISIONS, MmFlushSection(), MmSetAddressRangeModified(), MODIFIED_WRITE_DISABLED, _SHARED_CACHE_MAP::NeedToZero, _SHARED_CACHE_MAP::NeedToZeroPage, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SHIFT, PAGE_SIZE, _SHARED_CACHE_MAP::PagesToWrite, PIN_ACCESS, PRIVATE_WRITE, _LARGE_INTEGER::QuadPart, RemoveEntryList(), RetryError, _LAZY_WRITER::ScanActive, _FILE_OBJECT::SectionObjectPointer, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, Status, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, STATUS_VERIFY_REQUIRED, TRUE, _SHARED_CACHE_MAP::ValidDataGoal, _SHARED_CACHE_MAP::ValidDataLength, WAITING_FOR_TEARDOWN, and WRITE_QUEUED.
Referenced by CcSetPrivateWriteFile(), CcWriteBehind(), CcZeroEndOfLastPage(), CmpDestroyHiveViewList(), CmpDoFileSetSize(), CmpFileFlush(), CmpFileWriteThroughCache(), CmpUnPinCmView(), and MiFlushDataSection().
VOID CcFreeActiveVacb (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVACB ActiveVacb OPTIONAL, IN ULONG ActivePage, IN ULONG PageIsDirty)
Definition at line 5973 of file cachesub.c.
References ACTIVE_PAGE_IS_DIRTY, ASSERT, CcAcquireMasterLock, CcDeductDirtyPages, CcFreeVirtualAddress(), CcReleaseMasterLock, CcSetDirtyInMask(), ClearFlag, ExAcquireFastLock, ExAcquireSpinLockAtDpcLevel, ExReleaseFastLock, ExReleaseSpinLockFromDpcLevel, FlagOn, _LARGE_INTEGER::LowPart, MmUnlockCachedPage(), NULL, PAGE_SHIFT, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlZeroBytes, and VACB_MAPPING_GRANULARITY.
Referenced by CcCopyRead(), CcCopyWrite(), CcDeleteSharedCacheMap(), CcFastCopyRead(), CcFastCopyWrite(), CcFlushCache(), CcGetVacbMiss(), CcMapAndCopy(), CcMdlRead(), CcPinFileData(), CcPrepareMdlWrite(), CcPurgeCacheSection(), CcSetActiveVacb(), CcSetFileSizes(), CcSetPrivateWriteFile(), CcUninitializeCacheMap(), CcWriteBehind(), and CcZeroEndOfLastPage().
LARGE_INTEGER CcGetFlushedValidData (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN CcInternalCaller)
Definition at line 4277 of file cachesub.c.
References ASSERT, _BITMAP_RANGE::BasePage, _BCB::BcbLinks, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_BCB, CcAcquireMasterLock, CcAcquireMasterLockAtDpcLevel, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFindBitmapRangeToClean(), CcIncrementOpenCount, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CONTAINING_RECORD, _BCB::Dirty, _SHARED_CACHE_MAP::DirtyPages, _MBCB::DirtyPages, FALSE, _BCB::FileOffset, _BITMAP_RANGE::FirstDirtyPage, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), LazyWriter, MAXULONG, _SHARED_CACHE_MAP::Mbcb, _BCB::NodeTypeCode, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, _SHARED_CACHE_MAP::ValidDataGoal, and WRITE_QUEUED.
Referenced by CcWriteBehind().
LOGICAL CcHasInactiveViews (VOID)
Definition at line 6789 of file cachesub.c.
References FALSE.
Referenced by MiTrimSegmentCache().
BOOLEAN CcLogError (IN PFILE_OBJECT FileObject, IN PUNICODE_STRING FileName, IN NTSTATUS Error, IN NTSTATUS DeviceError, IN UCHAR IrpMajorCode)
Definition at line 6643 of file cachesub.c.
References ASSERT, _IO_ERROR_LOG_PACKET::DumpData, _IO_ERROR_LOG_PACKET::DumpDataSize, ERROR_LOG_MAXIMUM_SIZE, _IO_ERROR_LOG_PACKET::ErrorCode, FALSE, _IO_ERROR_LOG_PACKET::FinalStatus, IoAllocateErrorLogEntry(), IoWriteErrorLogEntry(), _IO_ERROR_LOG_PACKET::MajorFunctionCode, NULL, _IO_ERROR_LOG_PACKET::NumberOfStrings, PAGED_CODE, RtlCopyMemory, _IO_ERROR_LOG_PACKET::StringOffset, and TRUE.
Referenced by CcWriteBehind().
BOOLEAN CcMapAndCopy (IN PSHARED_CACHE_MAP SharedCacheMap, IN PVOID UserBuffer, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG OptimizeFlags, IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER ValidDataLength, IN BOOLEAN Wait)
Definition at line 6113 of file cachesub.c.
References ACTIVE_PAGE_IS_DIRTY, ASSERT, _VACB::BaseAddress, BooleanFlagOn, CcCopyReadExceptionFilter(), CcForceWriteThrough(), CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMaxDirtyWrite, CcSetDirtyInMask(), DebugTrace, DebugTrace2, except, ExRaiseStatus(), FALSE, _VACB::FileOffset, FlagOn, FO_WRITE_THROUGH, FsRtlNormalizeNtstatus(), _LARGE_INTEGER::LowPart, me, MM_FLUSH_ACQUIRE_FILE, MmCheckCachedPageState(), MmCopyToCachedPage(), MmFlushSection(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetAddressRangeModified(), MmSetPageFaultReadAhead, NOTHING, NT_SUCCESS, NULL, OPTIMIZE_FIRST_PAGE, OPTIMIZE_LAST_PAGE, OPTIMIZE_MIDDLE_PAGES, _VACB::Overlay, PAGE_SHIFT, PAGE_SIZE, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, RtlCopyBytes, SetActiveVacb, Status, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_VIOLATION, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_INVALID_USER_BUFFER, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, TRUE, and try_return.
Referenced by CcCopyWrite(), and CcFastCopyWrite().
BOOLEAN CcMapAndRead (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG ZeroFlags, IN BOOLEAN Wait, IN PVOID BaseAddress)
Definition at line 5834 of file cachesub.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, FALSE, FlagOn, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, NOTHING, PAGE_SIZE, PsGetCurrentThread(), TRUE, try_return, UNREFERENCED_PARAMETER, ZERO_FIRST_PAGE, ZERO_LAST_PAGE, and ZERO_MIDDLE_PAGES.
Referenced by CcPinFileData(), and CcPrepareMdlWrite().
VOID FASTCALL CcPerformReadAhead (IN PFILE_OBJECT FileObject)
Definition at line 1621 of file cachesub.c.
References _CACHE_MANAGER_CALLBACKS::AcquireForReadAhead, ADDRESS_AND_SIZE_TO_SPAN_PAGES, _SHARED_CACHE_MAP::Callbacks, CC_CLEAR_PRIVATE_CACHE_MAP, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMissCounter, CcReadAheadIos, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcThrowAway, ClearFlag, DebugTrace, _SHARED_CACHE_MAP::DirtyPages, ExAcquireSpinLockAtDpcLevel, ExReleaseSpinLockFromDpcLevel, FALSE, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FO_SEQUENTIAL_ONLY, _LARGE_INTEGER::HighPart, InsertTailList(), _SHARED_CACHE_MAP::LazyWriteContext, LazyWriter, _LARGE_INTEGER::LowPart, MAX_READ_AHEAD, me, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, NOTHING, NULL, ObDereferenceObject(), _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SIZE, PRIVATE_CACHE_MAP_READ_AHEAD_ACTIVE, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, READ_AHEAD_QUEUED, _PRIVATE_CACHE_MAP::ReadAheadLength, _PRIVATE_CACHE_MAP::ReadAheadOffset, _PRIVATE_CACHE_MAP::ReadAheadSpinLock, _CACHE_MANAGER_CALLBACKS::ReleaseFromReadAhead, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, try_return, and WRITE_QUEUED.
Referenced by CcWorkerThread().
BOOLEAN CcPinFileData (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN ReadOnly, IN BOOLEAN WriteOnly, IN ULONG Flags, OUT PBCB * Bcb, OUT PVOID * BaseAddress, OUT PLARGE_INTEGER BeyondLastByte)
Definition at line 120 of file cachesub.c.
References ASSERT, _BCB::BaseAddress, _SHARED_CACHE_MAP::BcbSpinLock, _BCB::BeyondLastByte, _BCB::ByteLength, CcAllocateInitializeBcb(), CcDereferenceFileOffset(), CcFindBcb(), CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMapAndRead(), CcReferenceFileOffset(), CcUnpinFileData, DebugTrace, DebugTrace2, ExAcquireResourceExclusiveLite(), ExAcquireSharedStarveExclusive(), ExRaiseStatus(), FALSE, FileOffset, _BCB::FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, GetActiveVacb, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _LARGE_INTEGER::LowPart, me, MODIFIED_WRITE_DISABLED, _SHARED_CACHE_MAP::NeedToZero, NOTHING, NULL, PAGE_SIZE, PIN_ACCESS, PIN_EXCLUSIVE, PIN_IF_BCB, PIN_NO_READ, PIN_WAIT, _BCB::PinCount, _LARGE_INTEGER::QuadPart, _BCB::Resource, ROUND_TO_PAGES, _SHARED_CACHE_MAP::SectionSize, STATUS_INSUFFICIENT_RESOURCES, TRUE, try_return, UNPIN, _BCB::Vacb, VACB_MAPPING_GRANULARITY, VOID, ZERO_FIRST_PAGE, ZERO_LAST_PAGE, and ZERO_MIDDLE_PAGES.
Referenced by CcCopyRead(), CcMapDataCommon(), CcPinMappedData(), CcPinRead(), CcPreparePinWrite(), and CcZeroData().
VOID CcReleaseByteRangeFromWrite (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN PBCB FirstBcb, IN BOOLEAN VerifyRequired)
Definition at line 3751 of file cachesub.c.
References ASSERT, BooleanFlagOn, CACHE_NTC_BCB, CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcUnpinFileData, CcUnpinFileDataReleaseFromFlush, CONTAINING_RECORD, DebugTrace, DebugTrace2, DISABLE_WRITE_BEHIND, FlagOn, me, MODIFIED_WRITE_DISABLED, NULL, _LARGE_INTEGER::QuadPart, SET_CLEAN, TRUE, and UNPIN.
Referenced by CcFlushCache().
PVOID CcRemapBcb (__in PVOID Bcb)
Definition at line 5162 of file cachesub.c.
References _VACB::ActiveCount, ASSERT, CACHE_NTC_BCB, CACHE_NTC_OBCB, CcAcquireVacbLock, CcBeyondVacbs, CcReleaseVacbLock, CcVacbs, and _VACB::Overlay.
VOID CcRepinBcb (__in PVOID Bcb)
Definition at line 5239 of file cachesub.c.
References KeAcquireInStackQueuedSpinLock(), and KeReleaseInStackQueuedSpinLock().
VOID CcScheduleReadAhead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length)
Definition at line 1241 of file cachesub.c.
References ASSERT, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_CLEAR_PRIVATE_CACHE_MAP, CC_SET_PRIVATE_CACHE_MAP, CcAcquireMasterLock, CcAllocateWorkQueueEntry, CcExpressWorkQueue, CcIncrementOpenCount, CcPostWorkQueue(), CcReleaseMasterLock, DebugTrace, DebugTrace2, DISABLE_READ_AHEAD, ExAcquireFastLock, ExAcquireSpinLock, ExReleaseFastLock, ExReleaseSpinLock, FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, FlagOn, _PRIVATE_CACHE_MAP::Flags, _SHARED_CACHE_MAP::Flags, FO_SEQUENTIAL_ONLY, _WORK_QUEUE_ENTRY::Function, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, me, NOISE_BITS, NULL, ObReferenceObject, PAGE_SIZE, _WORK_QUEUE_ENTRY::Parameters, PRIVATE_CACHE_MAP_READ_AHEAD_ACTIVE, _LARGE_INTEGER::QuadPart, _WORK_QUEUE_ENTRY::Read, READ_AHEAD_QUEUED, ReadAhead, _PRIVATE_CACHE_MAP_FLAGS::ReadAheadActive, _PRIVATE_CACHE_MAP::ReadAheadLength, _PRIVATE_CACHE_MAP::ReadAheadMask, _PRIVATE_CACHE_MAP::ReadAheadOffset, _PRIVATE_CACHE_MAP::ReadAheadSpinLock, ROUND_TO_PAGES, SetFlag, and TRUE.
Referenced by CcCopyRead(), CcFastCopyRead(), and CcMdlRead().
VOID CcSetDirtyInMask (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset, IN ULONG Length)
Definition at line 2231 of file cachesub.c.
References ASSERT, _BITMAP_RANGE::BasePage, _BITMAP_RANGE::Bitmap, _MBCB::BitmapRange1, _MBCB::BitmapRange2, _MBCB::BitmapRange3, _MBCB::BitmapRanges, CACHE_NTC_MBCB, CACHE_NTC_MBCB_GRANDE, CcAcquireMasterLockAtDpcLevel, CcAcquireVacbLockAtDpcLevel, CcAllocateInitializeBcb(), CcAllocateVacbLevel(), CcChargeMaskDirtyPages, CcDeallocateVacbLevel(), CcDirtySharedCacheMapList, CcFindBitmapRangeToDirty(), CcPrefillVacbLevelZone(), CcReleaseMasterLockFromDpcLevel, CcReleaseVacbLock, CcReleaseVacbLockFromDpcLevel, CcScheduleLazyWriteScan(), _BITMAP_RANGE::DirtyPages, FALSE, _BITMAP_RANGE::FirstDirtyPage, InitializeListHead(), InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _BITMAP_RANGE::LastDirtyPage, LazyWriter, _BITMAP_RANGE::Links, MAXULONG, MBCB_BITMAP_INITIAL_SIZE, MBCB_BITMAP_RANGE, _MBCB::NodeTypeCode, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, PAGE_SHIFT, PAGE_SIZE, QuadAlign, RemoveEntryList(), _MBCB::ResumeWritePage, RtlCopyMemory, RtlZeroMemory, _LAZY_WRITER::ScanActive, and _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks.
Referenced by CcFreeActiveVacb(), CcMapAndCopy(), CcMdlWriteComplete2(), CcPrepareMdlWrite(), CcPurgeAndClearCacheSection(), and CcReleaseByteRangeFromWrite().
VOID CcSetDirtyPinnedData (__in PVOID BcbVoid, __in_opt PLARGE_INTEGER Lsn)
Definition at line 2557 of file cachesub.c.
References ARGUMENT_PRESENT, ASSERT, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_OBCB, CcAcquireMasterLockAtDpcLevel, CcChargePinDirtyPages, CcDirtySharedCacheMapList, CcReleaseMasterLockFromDpcLevel, CcScheduleLazyWriteScan(), DebugTrace, _SHARED_CACHE_MAP::DirtyPages, DISABLE_WRITE_BEHIND, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), LazyWriter, me, NULL, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, and _SHARED_CACHE_MAP::ValidDataGoal.
Referenced by CcPreparePinWrite(), CcReleaseByteRangeFromWrite(), CcUnpinRepinnedBcb(), CcZeroData(), CmpFileWriteThroughCache(), and CmpUnPinCmView().
VOID CcSetReadAheadGranularity (__in PFILE_OBJECT FileObject, __in ULONG Granularity)
Definition at line 1210 of file cachesub.c.
NTSTATUS CcSetValidData (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER ValidDataLength)
Definition at line 2713 of file cachesub.c.
References DebugTrace, DebugTrace2, _IO_STACK_LOCATION::DeviceObject, _FILE_END_OF_FILE_INFORMATION::EndOfFile, Executive, FALSE, FileEndOfFileInformation, _IO_STACK_LOCATION::FileObject, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_SET_INFORMATION, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, me, NotificationEvent, NT_SUCCESS, NULL, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and TRUE.
Referenced by CcWriteBehind().
LOGICAL CcUnmapInactiveViews (IN ULONG NumberOfViewsToUnmap)
Definition at line 6824 of file cachesub.c.
References FALSE, and UNREFERENCED_PARAMETER.
Referenced by MiRemoveUnusedSegments().
VOID FASTCALL CcUnpinFileDataEx (IN OUT PBCB Bcb, IN BOOLEAN ReadOnly, IN UNMAP_ACTIONS UnmapAction)
Definition at line 974 of file cachesub.c.
References ASSERT, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_BCB, CACHE_NTC_SHARED_CACHE_MAP, CcAcquireMasterLockAtDpcLevel, CcAcquireVacbLockAtDpcLevel, CcBeyondVacbs, CcBugCheck, CcDeallocateBcb(), CcDeductDirtyPages, CcFreeVirtualAddress(), CcInsertIntoCleanSharedCacheMapList(), CcPagesYetToWrite, CcReleaseMasterLockFromDpcLevel, CcReleaseVacbLockFromDpcLevel, CcUnlockVacbLevel, CcVacbs, DebugTrace, _SHARED_CACHE_MAP::DirtyPages, ExReleaseResourceLite(), FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), me, MODIFIED_WRITE_DISABLED, _SHARED_CACHE_MAP::NodeTypeCode, NULL, _SHARED_CACHE_MAP::OpenCount, PAGE_SHIFT, RemoveEntryList(), SET_CLEAN, _SHARED_CACHE_MAP::SharedCacheMapLinks, TRUE, UNPIN, and UNREF.
VOID CcUnpinRepinnedBcb (__in PVOID Bcb, __in BOOLEAN WriteThrough, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 5281 of file cachesub.c.
References ASSERT, CcDeferredWrites, CcPostDeferredWrites(), CcSetDirtyPinnedData(), CcUnpinFileData, DebugTrace, DebugTrace2, ExAcquireResourceExclusiveLite(), FALSE, _SHARED_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, IsListEmpty, me, MM_FLUSH_ACQUIRE_FILE, MmFlushSection(), MmSetAddressRangeModified(), MODIFIED_WRITE_DISABLED, NULL, RetryError, _FILE_OBJECT::SectionObjectPointer, SET_CLEAN, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, TRUE, and UNPIN.
VOID FASTCALL CcWriteBehind (IN PSHARED_CACHE_MAP SharedCacheMap, IN PIO_STATUS_BLOCK IoStatus)
Definition at line 3881 of file cachesub.c.
References CC_REQUEUE, CcAcquireMasterLock, CcAcquireMasterLockAtDpcLevel, CcCancelMmWaitForUninitializeCacheMap(), CcDecrementOpenCount, CcDeferredWrites, CcDeleteSharedCacheMap(), CcDirtySharedCacheMapList, CcFlushCache(), CcFreeActiveVacb(), CcGetFlushedValidData(), CcIncrementOpenCount, CcLogError(), CcLostDelayedWrites, CcNoDelay, CcPagesYetToWrite, CcPostDeferredWrites(), CcReleaseMasterLock, CcReleaseMasterLockFromDpcLevel, CcScheduleLazyWriteScan(), CcSetValidData(), ClearFlag, DebugTrace, _MBCB::DirtyPages, ExFreePool(), FALSE, FlagOn, FORCED_WRITE_THROUGH, FsRtlAcquireFileExclusive(), FsRtlReleaseFile(), GetActiveVacbAtDpcLevel, InsertTailList(), IO_LOST_DELAYED_WRITE, IoQueryFileDosDeviceName(), IoRaiseInformationalHardError(), IRP_MJ_WRITE, IsListEmpty, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), LAZY_WRITE_OCCURRED, LazyWriter, me, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _LAZY_WRITER::OtherWork, _MBCB::PagesToWrite, PIN_ACCESS, _LARGE_INTEGER::QuadPart, RemoveEntryList(), RetryError, _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, Status, STATUS_FILE_LOCK_CONFLICT, STATUS_INSUFFICIENT_RESOURCES, STATUS_LOST_WRITEBEHIND_DATA, STATUS_SUCCESS, STATUS_VERIFY_REQUIRED, TRUE, WAITING_FOR_TEARDOWN, and WRITE_QUEUED.
Referenced by CcWorkerThread().
Variable Documentation
ULONG CcMaxDirtyWrite = 0x10000
Definition at line 44 of file cachesub.c.
Referenced by CcMapAndCopy().