Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/fsfilter.c File Reference
fsfilter.c File Reference
#include "FsRtlP.h"
Data Structures
struct _FS_FILTER_RESERVE
Macros
#define FS_FILTER_MAX_COMPLETION_STACK_SIZE 30
Typedefs
typedef struct _FS_FILTER_RESERVE FS_FILTER_RESERVE
typedef struct _FS_FILTER_RESERVE * PFS_FILTER_RESERVE
Functions
NTSTATUS FsFilterAllocateCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN CanFail, OUT PULONG AllocationSize)
VOID FsFilterCtrlFree (IN PFS_FILTER_CTRL FsFilterCtrl)
NTSTATUS FsFilterCtrlInit (IN OUT PFS_FILTER_CTRL FsFilterCtrl, IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, IN PDEVICE_OBJECT BaseFsDeviceObject, IN PFILE_OBJECT FileObject, IN BOOLEAN CanFail)
VOID FsFilterFreeCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl)
VOID FsFilterGetCallbacks (IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, OUT PFS_FILTER_CALLBACK *PreOperationCallback, OUT PFS_FILTER_COMPLETION_CALLBACK *PostOperationCallback)
NTSTATUS FsFilterInit ()
NTSTATUS FsFilterPerformCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN AllowFilterToFail, IN BOOLEAN AllowBaseFsToFail, OUT BOOLEAN *BaseFsFailedOp)
VOID FsFilterPerformCompletionCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN NTSTATUS OperationStatus)
NTKERNELAPI NTSTATUS FsRtlCreateSectionForDataScan (OUT PHANDLE SectionHandle, OUT PVOID *SectionObject, OUT PLARGE_INTEGER SectionFileSize OPTIONAL, IN PFILE_OBJECT FileObject, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN PLARGE_INTEGER MaximumSize OPTIONAL, IN ULONG SectionPageProtection, IN ULONG AllocationAttributes, IN ULONG Flags)
Variables
KEVENT AcquireOpsEvent
PFS_FILTER_RESERVE AcquireOpsReservePool
const LARGE_INTEGER FsRtlHalfSecond = {(ULONG)(-5 * 100 * 1000 * 10), -1}
KEVENT ReleaseOpsEvent
PFS_FILTER_RESERVE ReleaseOpsReservePool
Macro Definition Documentation
#define FS_FILTER_MAX_COMPLETION_STACK_SIZE 30
Definition at line 23 of file fsfilter.c.
Typedef Documentation
typedef struct _FS_FILTER_RESERVE FS_FILTER_RESERVE
typedef struct _FS_FILTER_RESERVE * PFS_FILTER_RESERVE
Function Documentation
NTSTATUS FsFilterAllocateCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN CanFail, OUT PULONG AllocationSize)
Definition at line 108 of file fsfilter.c.
References AcquireOpsEvent, AcquireOpsReservePool, ASSERT, ASSERTMSG, ExAllocatePoolWithTag, Executive, FALSE, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_ALLOCATED_COMPLETION_STACK, FS_FILTER_RELEASE_FOR_CC_FLUSH, FS_FILTER_RELEASE_FOR_MOD_WRITE, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_USED_RESERVE_POOL, FSRTL_FILTER_MEMORY_TAG, KernelMode, KeWaitForSingleObject(), NonPagedPool, NULL, _FS_FILTER_RESERVE::Owner, PsGetCurrentThread(), ReleaseOpsEvent, ReleaseOpsReservePool, SetFlag, _FS_FILTER_RESERVE::Stack, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by FsFilterCtrlInit().
VOID FsFilterCtrlFree (IN PFS_FILTER_CTRL FsFilterCtrl)
Definition at line 434 of file fsfilter.c.
References ASSERT, FlagOn, FS_FILTER_ALLOCATED_COMPLETION_STACK, FsFilterFreeCompletionStack(), and NULL.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTSTATUS FsFilterCtrlInit (IN OUT PFS_FILTER_CTRL FsFilterCtrl, IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, IN PDEVICE_OBJECT BaseFsDeviceObject, IN PFILE_OBJECT FileObject, IN BOOLEAN CanFail)
Definition at line 324 of file fsfilter.c.
References ASSERT, _FS_FILTER_CALLBACK_DATA::DeviceObject, _FS_FILTER_CALLBACK_DATA::FileObject, FS_FILTER_DEFAULT_STACK_SIZE, FsFilterAllocateCompletionStack(), NT_SUCCESS, NULL, _FS_FILTER_CALLBACK_DATA::Operation, RtlZeroMemory, _FS_FILTER_CALLBACK_DATA::SizeOfFsFilterCallbackData, Status, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
VOID FsFilterFreeCompletionStack (IN PFS_FILTER_CTRL FsFilterCtrl)
Definition at line 231 of file fsfilter.c.
References AcquireOpsEvent, ASSERT, ASSERTMSG, CONTAINING_RECORD, ExFreePoolWithTag, FALSE, FlagOn, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_ALLOCATED_COMPLETION_STACK, FS_FILTER_RELEASE_FOR_CC_FLUSH, FS_FILTER_RELEASE_FOR_MOD_WRITE, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_USED_RESERVE_POOL, FSRTL_FILTER_MEMORY_TAG, IO_NO_INCREMENT, KeSetEvent(), NULL, _FS_FILTER_RESERVE::Owner, and ReleaseOpsEvent.
Referenced by FsFilterCtrlFree().
VOID FsFilterGetCallbacks (IN UCHAR Operation, IN PDEVICE_OBJECT DeviceObject, OUT PFS_FILTER_CALLBACK * PreOperationCallback, OUT PFS_FILTER_COMPLETION_CALLBACK * PostOperationCallback)
Definition at line 468 of file fsfilter.c.
References ASSERT, FALSE, FS_FILTER_ACQUIRE_FOR_CC_FLUSH, FS_FILTER_ACQUIRE_FOR_MOD_WRITE, FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION, FS_FILTER_RELEASE_FOR_CC_FLUSH, FS_FILTER_RELEASE_FOR_MOD_WRITE, FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION, NULL, _FS_FILTER_CALLBACKS::PostAcquireForCcFlush, _FS_FILTER_CALLBACKS::PostAcquireForModifiedPageWriter, _FS_FILTER_CALLBACKS::PostAcquireForSectionSynchronization, _FS_FILTER_CALLBACKS::PostReleaseForCcFlush, _FS_FILTER_CALLBACKS::PostReleaseForModifiedPageWriter, _FS_FILTER_CALLBACKS::PostReleaseForSectionSynchronization, _FS_FILTER_CALLBACKS::PreAcquireForCcFlush, _FS_FILTER_CALLBACKS::PreAcquireForModifiedPageWriter, _FS_FILTER_CALLBACKS::PreAcquireForSectionSynchronization, _FS_FILTER_CALLBACKS::PreReleaseForCcFlush, _FS_FILTER_CALLBACKS::PreReleaseForModifiedPageWriter, _FS_FILTER_CALLBACKS::PreReleaseForSectionSynchronization, and VALID_FS_FILTER_CALLBACK_HANDLER.
Referenced by FsFilterPerformCallbacks().
NTSTATUS FsFilterInit ()
Definition at line 56 of file fsfilter.c.
References ExAllocatePoolWithTag, ExFreePoolWithTag, FSRTL_FILTER_MEMORY_TAG, KeInitializeEvent(), NonPagedPool, NULL, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, SynchronizationEvent, and TRUE.
Referenced by FsRtlInitSystem().
NTSTATUS FsFilterPerformCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN BOOLEAN AllowFilterToFail, IN BOOLEAN AllowBaseFsToFail, OUT BOOLEAN * BaseFsFailedOp)
Definition at line 639 of file fsfilter.c.
References ASSERT, _FS_FILTER_COMPLETION_NODE::CompletionCallback, _FS_FILTER_COMPLETION_NODE::CompletionContext, _FS_FILTER_COMPLETION_NODE::DeviceObject, _FS_FILTER_CALLBACK_DATA::DeviceObject, FALSE, FILE_SYSTEM, _FS_FILTER_COMPLETION_NODE::FileObject, _FS_FILTER_CALLBACK_DATA::FileObject, FS_FILTER_CHANGED_DEVICE_STACKS, FsFilterGetCallbacks(), KdPrint, KeBugCheckEx(), NOTHING, NT_SUCCESS, NULL, _FS_FILTER_CALLBACK_DATA::Operation, POP_COMPLETION_NODE, PUSH_COMPLETION_NODE, SetFlag, Status, STATUS_FSFILTER_OP_COMPLETED_SUCCESSFULLY, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
VOID FsFilterPerformCompletionCallbacks (IN PFS_FILTER_CTRL FsFilterCtrl, IN NTSTATUS OperationStatus)
Definition at line 960 of file fsfilter.c.
References ASSERT, _FS_FILTER_COMPLETION_NODE::CompletionCallback, _FS_FILTER_COMPLETION_NODE::CompletionContext, _FS_FILTER_COMPLETION_NODE::DeviceObject, _FS_FILTER_CALLBACK_DATA::DeviceObject, _FS_FILTER_COMPLETION_NODE::FileObject, _FS_FILTER_CALLBACK_DATA::FileObject, GET_COMPLETION_NODE, _FS_FILTER_COMPLETION_STACK::NextStackPosition, NULL, and POP_COMPLETION_NODE.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTKERNELAPI NTSTATUS FsRtlCreateSectionForDataScan (OUT PHANDLE SectionHandle, OUT PVOID * SectionObject, OUT PLARGE_INTEGER SectionFileSize OPTIONAL, IN PFILE_OBJECT FileObject, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes OPTIONAL, IN PLARGE_INTEGER MaximumSize OPTIONAL, IN ULONG SectionPageProtection, IN ULONG AllocationAttributes, IN ULONG Flags)
Definition at line 998 of file fsfilter.c.
References ARGUMENT_PRESENT, ASSERT, CcZeroEndOfLastPage(), DISPATCH_LEVEL, FALSE, FlagOn, FSRTL_FSP_TOP_LEVEL_IRP, FsRtlAcquireToCreateMappedSection(), FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlGetFileSize(), FsRtlReleaseFile(), Handle, IoGetTopLevelIrp(), IoSetTopLevelIrp(), KeDelayExecutionThread(), KeGetCurrentIrql(), KernelMode, MmCreateSection(), NT_SUCCESS, NULL, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, PAGE_READONLY, PAGE_READWRITE, PIRP, _LARGE_INTEGER::QuadPart, SEC_COMMIT, SEC_FILE, Status, STATUS_END_OF_FILE, STATUS_FILE_LOCK_CONFLICT, STATUS_INVALID_PARAMETER_8, STATUS_INVALID_PARAMETER_9, and UNREFERENCED_PARAMETER.
Variable Documentation
KEVENT AcquireOpsEvent
Definition at line 49 of file fsfilter.c.
Referenced by FsFilterAllocateCompletionStack(), and FsFilterFreeCompletionStack().
PFS_FILTER_RESERVE AcquireOpsReservePool
Definition at line 50 of file fsfilter.c.
Referenced by FsFilterAllocateCompletionStack().
const LARGE_INTEGER FsRtlHalfSecond = {(ULONG)(-5 * 100 * 1000 * 10), -1}
Definition at line 994 of file fsfilter.c.
KEVENT ReleaseOpsEvent
Definition at line 52 of file fsfilter.c.
Referenced by FsFilterAllocateCompletionStack(), and FsFilterFreeCompletionStack().
PFS_FILTER_RESERVE ReleaseOpsReservePool
Definition at line 53 of file fsfilter.c.
Referenced by FsFilterAllocateCompletionStack().