Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/mmsup.c File Reference
mmsup.c File Reference
#include "mi.h"
Functions
PSUBSECTION MiGetSubsectionAndProtoFromPte (IN PMMPTE PointerPte, OUT PMMPTE *ProtoPte)
LOGICAL FASTCALL MiIsProtectionCompatible (IN WIN32_PROTECTION_MASK OldWin32Protect, IN WIN32_PROTECTION_MASK NewWin32Protect)
LOGICAL FASTCALL MiIsPteProtectionCompatible (IN MM_PROTECTION_MASK PteProtection, IN WIN32_PROTECTION_MASK NewProtect)
VOID FASTCALL MiLockPagedAddress (IN PVOID VirtualAddress)
VOID MiMakePdeExistAndMakeValid (IN PMMPTE PointerPde, IN PEPROCESS TargetProcess, IN KIRQL OldIrql)
MM_PROTECTION_MASK FASTCALL MiMakeProtectionMask (IN WIN32_PROTECTION_MASK Win32Protect)
ULONG FASTCALL MiMakeSystemAddressValid (IN PVOID PageTableVirtualAddress, IN PEPROCESS CurrentProcess)
ULONG FASTCALL MiMakeSystemAddressValidPfn (IN PVOID VirtualAddress, IN KIRQL OldIrql)
ULONG FASTCALL MiMakeSystemAddressValidPfnSystemWs (IN PVOID VirtualAddress, IN KIRQL OldIrql)
ULONG FASTCALL MiMakeSystemAddressValidPfnWs (IN PVOID VirtualAddress, IN PEPROCESS CurrentProcess, IN KIRQL OldIrql)
VOID FASTCALL MiRestoreTransitionPte (IN PMMPFN Pfn1)
VOID FASTCALL MiUnlockPagedAddress (IN PVOID VirtualAddress)
VOID FASTCALL MiZeroPhysicalPage (IN PFN_NUMBER PageFrameIndex)
VOID MmHibernateInformation (IN PVOID MemoryMap, OUT PULONG_PTR HiberVa, OUT PPHYSICAL_ADDRESS HiberPte)
BOOLEAN MmIsNonPagedSystemAddressValid (__in PVOID VirtualAddress)
Variables
WIN32_PROTECTION_MASK MmCompatibleProtectionMask [8]
CCHAR MmUserProtectionToMask1 [16]
CCHAR MmUserProtectionToMask2 [16]
Function Documentation
PSUBSECTION MiGetSubsectionAndProtoFromPte (IN PMMPTE PointerPte, OUT PMMPTE * ProtoPte)
Definition at line 1036 of file mmsup.c.
References ASSERT, _MMPTE::Hard, LOCK_PFN, MI_PFN_ELEMENT, MiGetPteAddress, MiGetSubsectionAddress, MiMakeSystemAddressValidPfn(), MiPteToProto, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteAddress, _MMPTE::Soft, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
LOGICAL FASTCALL MiIsProtectionCompatible (IN WIN32_PROTECTION_MASK OldWin32Protect, IN WIN32_PROTECTION_MASK NewWin32Protect)
Definition at line 53 of file mmsup.c.
References FALSE, MiMakeProtectionMask(), MM_INVALID_PROTECTION, MmCompatibleProtectionMask, PAGE_GUARD, PAGE_NOCACHE, PAGE_WRITECOMBINE, and TRUE.
Referenced by MmMapViewOfSection().
LOGICAL FASTCALL MiIsPteProtectionCompatible (IN MM_PROTECTION_MASK PteProtection, IN WIN32_PROTECTION_MASK NewProtect)
Definition at line 120 of file mmsup.c.
References FALSE, MmCompatibleProtectionMask, PAGE_GUARD, PAGE_NOCACHE, PAGE_WRITECOMBINE, and TRUE.
Referenced by MiProtectVirtualMemory().
VOID FASTCALL MiLockPagedAddress (IN PVOID VirtualAddress)
Definition at line 739 of file mmsup.c.
References _MMPTE::Hard, LOCK_PFN, MI_ADD_LOCKED_PAGE_CHARGE(), MI_PFN_ELEMENT, MiGetPteAddress, MiMakeSystemAddressValidPfn(), _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiCloneProcessAddressSpace().
VOID MiMakePdeExistAndMakeValid (IN PMMPTE PointerPde, IN PEPROCESS TargetProcess, IN KIRQL OldIrql)
Definition at line 307 of file mmsup.c.
References ASSERT, _MMPTE::Hard, KeAreAllApcsDisabled(), LOCK_PFN, MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiMakeSystemAddressValid(), MM_NOIRQL, TRUE, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiAllocateLargePages(), MiCloneProcessAddressSpace(), MiCreatePageTablesForPhysicalRange(), MiDecommitPages(), MiDeletePte(), MiMapLockedPagesInUserSpace(), MiMapViewOfPhysicalSection(), MiProtectVirtualMemory(), MiSetProtectionOnSection(), NtAllocateVirtualMemory(), and NtLockVirtualMemory().
MM_PROTECTION_MASK FASTCALL MiMakeProtectionMask (IN WIN32_PROTECTION_MASK Win32Protect)
Definition at line 182 of file mmsup.c.
References ASSERT, MI_ADD_GUARD, MI_ADD_NOCACHE, MI_ADD_WRITECOMBINE, MM_INVALID_PROTECTION, MM_NOACCESS, MmUserProtectionToMask1, MmUserProtectionToMask2, PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, and PAGE_WRITECOMBINE.
Referenced by MiIsProtectionCompatible(), MiProtectVirtualMemory(), MiSetProtectionOnSection(), MmCreateSection(), MmMapViewOfSection(), MmProtectMdlSystemAddress(), MmSetPageProtection(), NtAllocateVirtualMemory(), NtMapViewOfSection(), and NtProtectVirtualMemory().
ULONG FASTCALL MiMakeSystemAddressValid (IN PVOID PageTableVirtualAddress, IN PEPROCESS CurrentProcess)
Definition at line 421 of file mmsup.c.
References ASSERT, FALSE, KeAreAllApcsDisabled(), KeBugCheckEx(), KERNEL_DATA_INPAGE_ERROR, KernelMode, LOCK_WS_REGARDLESS, MiIsAddressValid(), MM_HIGHEST_USER_ADDRESS, MM_PAGED_POOL_START, MmAccessFault(), MmPagedPoolEnd, NT_SUCCESS, NULL, PsGetCurrentThread(), TRUE, and UNLOCK_WS_REGARDLESS.
Referenced by MiCloneProcessAddressSpace(), MiDoesPdeExistAndMakeValid(), and MiMakePdeExistAndMakeValid().
ULONG FASTCALL MiMakeSystemAddressValidPfn (IN PVOID VirtualAddress, IN KIRQL OldIrql)
Definition at line 675 of file mmsup.c.
References ASSERT, FALSE, KeBugCheckEx(), KERNEL_DATA_INPAGE_ERROR, KernelMode, LOCK_PFN, MiIsAddressValid(), MM_HIGHEST_USER_ADDRESS, MmAccessFault(), NT_SUCCESS, NULL, TRUE, and UNLOCK_PFN.
Referenced by MiCcPutPagesInTransition(), MiCheckProtoPtePageState(), MiCleanSection(), MiFlushSectionInternal(), MiGetPageProtection(), MiGetSubsectionAndProtoFromPte(), MiLockPagedAddress(), MiMarkSectionWritable(), MiPurgeImageSection(), MiQueryAddressState(), MiRemoveMappedPtes(), MiSegmentDelete(), MiSetProtectionOnSection(), MiUpdateImageHeaderPage(), MiUpdateLargeProtoPfns(), MmPurgeSection(), and MmUnmapViewInSystemCache().
ULONG FASTCALL MiMakeSystemAddressValidPfnSystemWs (IN PVOID VirtualAddress, IN KIRQL OldIrql)
Definition at line 588 of file mmsup.c.
References ASSERT, FALSE, _MM_SESSION_SPACE::GlobalVirtualAddress, KeBugCheckEx(), KERNEL_DATA_INPAGE_ERROR, KernelMode, LOCK_PFN, LOCK_WORKING_SET, MI_IS_SESSION_IMAGE_ADDRESS, MiIsAddressValid(), MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MmAccessFault(), MmSessionSpace, MmSystemCacheWs, NT_SUCCESS, NULL, PsGetCurrentThread(), TRUE, UNLOCK_PFN, UNLOCK_WORKING_SET, and _MM_SESSION_SPACE::Vm.
Referenced by MiEnablePagingTheExecutive(), MiLockCode(), MiSetProtectionOnSection(), MiSetSystemCodeProtection(), MmCheckCachedPageState(), MmCopyToCachedPage(), and MmUnmapViewInSystemCache().
ULONG FASTCALL MiMakeSystemAddressValidPfnWs (IN PVOID VirtualAddress, IN PEPROCESS CurrentProcess, IN KIRQL OldIrql)
Definition at line 507 of file mmsup.c.
References ASSERT, FALSE, KeBugCheckEx(), KERNEL_DATA_INPAGE_ERROR, KernelMode, LOCK_PFN, LOCK_WS_REGARDLESS, MiIsAddressValid(), MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MmAccessFault(), NT_SUCCESS, NULL, PsGetCurrentThread(), TRUE, UNLOCK_PFN, and UNLOCK_WS_REGARDLESS.
Referenced by MiDecrementCloneBlockReference(), and MiResetVirtualMemory().
VOID FASTCALL MiRestoreTransitionPte (IN PMMPFN Pfn1)
Definition at line 890 of file mmsup.c.
References ASSERT, _SUBSECTION::ControlArea, _MMPTE::Hard, MI_CAPTURE_USED_PAGETABLE_ENTRIES, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_SESSION_PTE, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_RESET_PFN_PRIORITY, MI_WRITE_INVALID_PTE_WITHOUT_WS, MiCheckForControlAreaDeletion(), MiDecrementShareCountInline, MiGetByteOffset, MiGetPteAddress, MiGetSubsectionAddress, MiIsProtoAddressValid(), MiMapPageInHyperSpaceAtDpc(), MiUnmapPageInHyperSpaceFromDpc, MM_SYSTEM_SPACE_START, NULL, _CONTROL_AREA::NumberOfPfnReferences, PsGetCurrentProcess(), StandbyPageList, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiAllocatePagesForMdl(), MiCcCompletePrefetchIos(), MiDecrementReferenceCount(), MiDispatchFault(), MiFindContiguousPages(), MiFindLargePageMemory(), MiInsertPageInList(), MiRemovePageFromList(), MiResolveTransitionFault(), and MmCopyToCachedPage().
VOID FASTCALL MiUnlockPagedAddress (IN PVOID VirtualAddress)
Definition at line 794 of file mmsup.c.
References ASSERT, _MMPFN::e2, _MMPTE::Hard, LOCK_PFN2, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, and _MMPTE_HARDWARE::Valid.
Referenced by MiCloneProcessAddressSpace().
VOID FASTCALL MiZeroPhysicalPage (IN PFN_NUMBER PageFrameIndex)
Definition at line 849 of file mmsup.c.
References KeZeroSinglePage, MiMapPageInHyperSpace(), MiUnmapPageInHyperSpace, and PsGetCurrentProcess().
Referenced by MiRemoveZeroPage(), MiRemoveZeroPageMayReleaseLocks(), MiResolveDemandZeroFault(), MiWaitForInPageComplete(), MiZeroAwePageWorker(), MiZeroPageFileFirstPage(), MmAccessFault(), and MmCopyToCachedPage().
VOID MmHibernateInformation (IN PVOID MemoryMap, OUT PULONG_PTR HiberVa, OUT PPHYSICAL_ADDRESS HiberPte)
Definition at line 1185 of file mmsup.c.
References MiGetVirtualAddressMappedByPte, MmCrashDumpPte, MmGetPhysicalAddress(), PO_MEM_CLONE, and PoSetHiberRange().
BOOLEAN MmIsNonPagedSystemAddressValid (__in PVOID VirtualAddress)
Definition at line 1124 of file mmsup.c.
References FALSE, MiSessionSpaceEnd, MmIsSpecialPoolAddress(), MmPagedPoolEnd, MmPagedPoolStart, MmQuerySpecialPoolBlockType(), MmSessionBase, PagedPool, and TRUE.
Referenced by MmBuildMdlForNonPagedPool().
Variable Documentation
WIN32_PROTECTION_MASK MmCompatibleProtectionMask[8]
Initial value:
= {
    PAGE_NOACCESS,
    PAGE_NOACCESS | PAGE_READONLY | PAGE_WRITECOPY,
    PAGE_NOACCESS | PAGE_EXECUTE,
    PAGE_NOACCESS | PAGE_READONLY | PAGE_WRITECOPY | PAGE_EXECUTE | PAGE_EXECUTE_READ,
    PAGE_NOACCESS | PAGE_READONLY | PAGE_WRITECOPY | PAGE_READWRITE,
    PAGE_NOACCESS | PAGE_READONLY | PAGE_WRITECOPY,
    PAGE_NOACCESS | PAGE_READONLY | PAGE_WRITECOPY | PAGE_READWRITE | PAGE_EXECUTE | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY,
    PAGE_NOACCESS | PAGE_READONLY | PAGE_WRITECOPY | PAGE_EXECUTE | PAGE_EXECUTE_READ | PAGE_EXECUTE_WRITECOPY
}
Definition at line 30 of file mmsup.c.
Referenced by MiIsProtectionCompatible(), and MiIsPteProtectionCompatible().
CCHAR MmUserProtectionToMask1[16]
Initial value:
= {
                                 0,
                                 MM_NOACCESS,
                                 MM_READONLY,
                                 -1,
                                 MM_READWRITE,
                                 -1,
                                 -1,
                                 -1,
                                 MM_WRITECOPY,
                                 -1,
                                 -1,
                                 -1,
                                 -1,
                                 -1,
                                 -1,
                                 -1 }
Definition at line 143 of file mmsup.c.
Referenced by MiMakeProtectionMask().
CCHAR MmUserProtectionToMask2[16]
Initial value:
= {
                                 0,
                                 MM_EXECUTE,
                                 MM_EXECUTE_READ,
                                 -1,
                                 MM_EXECUTE_READWRITE,
                                 -1,
                                 -1,
                                 -1,
                                 MM_EXECUTE_WRITECOPY,
                                 -1,
                                 -1,
                                 -1,
                                 -1,
                                 -1,
                                 -1,
                                 -1 }
Definition at line 161 of file mmsup.c.
Referenced by MiMakeProtectionMask().