Windows Research Kernel v1.2: C:/Windows Research Kernel/perf/perfsup.c File Reference
perfsup.c File Reference
#include "perfp.h"
Functions
NTSTATUS IoPerfInit ()
NTSTATUS IoPerfReset ()
VOID PerfInfoProfileInit ()
VOID PerfInfoProfileUninit ()
NTSTATUS PerfInfoStartLog (PERFINFO_GROUPMASK *PGroupMask, PERFINFO_START_LOG_LOCATION StartLogLocation)
NTSTATUS PerfInfoStopLog ()
Function Documentation
NTSTATUS IoPerfInit ()
Referenced by PerfInfoStartLog().
NTSTATUS IoPerfReset ()
Referenced by PerfInfoStartLog(), and PerfInfoStopLog().
VOID PerfInfoProfileInit ()
Definition at line 33 of file perfsup.c.
References _PERFINFO_SAMPLED_PROFILE_CACHE::Entries, FALSE, KeInitializeProfile(), KeSetIntervalProfile(), KeStartProfile(), NULL, PerfInfoProfileInterval, PerfInfoProfileObject, PerfInfoProfileSourceActive, PerfInfoProfileSourceRequested, PerfInfoSampledProfileCaching, PerfInfoSampledProfileFlushInProgress, PerfProfileCache, and TRUE.
Referenced by PerfInfoStartLog().
VOID PerfInfoProfileUninit ()
Definition at line 74 of file perfsup.c.
References KeStopProfile(), PerfInfoFlushProfileCache(), PerfInfoProfileObject, PerfInfoProfileSourceActive, and ProfileMaximum.
Referenced by PerfInfoStartLog(), and PerfInfoStopLog().
NTSTATUS PerfInfoStartLog (PERFINFO_GROUPMASK * PGroupMask, PERFINFO_START_LOG_LOCATION StartLogLocation)
Definition at line 98 of file perfsup.c.
References FALSE, IoPerfInit(), IoPerfReset(), KeGetPreviousMode, KernelMode, MmEmptyAllWorkingSets(), NT_SUCCESS, NULL, PERF_BIGFOOT, PERF_CONTEXT_SWITCH, PERF_DRIVERS, PERF_FILENAME, PERF_FILENAME_ALL, PERF_FOOTPRINT, PERF_MEMORY, PERF_PROC_THREAD, PERF_PROFILE, PerfGlobalGroupMask, PERFINFO_CLEAR_GROUPMASK, PERFINFO_OR_GROUP_WITH_GROUPMASK, PERFINFO_START_LOG_AT_BOOT, PERFINFO_START_LOG_FROM_GLOBAL_LOGGER, PerfInfoFileNameRunDown(), PerfInfoProcessRunDown(), PerfInfoProfileInit(), PerfInfoProfileUninit(), PerfInfoSysModuleRunDown(), PerfIsGroupOnInGroupMask(), PerfSetLogging(), PPerfGlobalGroupMask, SeSinglePrivilegeCheck(), SeSystemProfilePrivilege, Status, STATUS_NO_SUCH_PRIVILEGE, STATUS_SUCCESS, TRUE, UserMode, WmiStartContextSwapTrace(), and WmiStopContextSwapTrace().
Referenced by WmipStartLogger(), and WmiUpdateTrace().
NTSTATUS PerfInfoStopLog ()
Definition at line 254 of file perfsup.c.
References FALSE, IoPerfReset(), MmIdentifyPhysicalMemory(), NULL, PERF_CONTEXT_SWITCH, PERF_DRIVERS, PERF_MEMORY, PERF_PROFILE, PERFINFO_CLEAR_GROUPMASK, PERFINFO_IS_GROUP_ON, PerfInfoProfileUninit(), PerfSetLogging(), PPerfGlobalGroupMask, Status, STATUS_SUCCESS, TRUE, and WmiStopContextSwapTrace().