Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/splay.c File Reference
splay.c File Reference
#include <nt.h>
#include <ntrtl.h>
Macros
#define ParentsChildPointerAddress(Links)
#define SwapPointers(Ptr1, Ptr2)
Functions
PRTL_SPLAY_LINKS RtlDelete (IN PRTL_SPLAY_LINKS Links)
VOID RtlDeleteNoSplay (IN PRTL_SPLAY_LINKS Links, IN OUT PRTL_SPLAY_LINKS *Root)
PRTL_SPLAY_LINKS RtlRealPredecessor (IN PRTL_SPLAY_LINKS Links)
PRTL_SPLAY_LINKS RtlRealSuccessor (IN PRTL_SPLAY_LINKS Links)
PRTL_SPLAY_LINKS RtlSplay (IN PRTL_SPLAY_LINKS Links)
PRTL_SPLAY_LINKS RtlSubtreePredecessor (IN PRTL_SPLAY_LINKS Links)
PRTL_SPLAY_LINKS RtlSubtreeSuccessor (IN PRTL_SPLAY_LINKS Links)
VOID SwapSplayLinks (IN PRTL_SPLAY_LINKS Link1, IN PRTL_SPLAY_LINKS Link2)
Macro Definition Documentation
#define ParentsChildPointerAddress (Links)
Value:
(\
    RtlIsLeftChild(Links) ?                 \
        &(((Links)->Parent)->LeftChild)     \
    :                                       \
        &(((Links)->Parent)->RightChild)    \
    )
Definition at line 30 of file splay.c.
Referenced by RtlDelete(), RtlDeleteNoSplay(), RtlSplay(), and SwapSplayLinks().
#define SwapPointers (Ptr1, Ptr2)
Value:
{      \
    PVOID _SWAP_POINTER_TEMP;           \
    _SWAP_POINTER_TEMP = (PVOID)(Ptr1); \
    (Ptr1) = (Ptr2);                    \
    (Ptr2) = _SWAP_POINTER_TEMP; \
    }
Definition at line 23 of file splay.c.
Referenced by SwapSplayLinks().
Function Documentation
PRTL_SPLAY_LINKS RtlDelete (IN PRTL_SPLAY_LINKS Links)
Definition at line 379 of file splay.c.
References NULL, _RTL_SPLAY_LINKS::Parent, ParentsChildPointerAddress, RtlIsRoot, RtlLeftChild, RtlParent, RtlRightChild, RtlSplay(), RtlSubtreePredecessor(), and SwapSplayLinks().
VOID RtlDeleteNoSplay (IN PRTL_SPLAY_LINKS Links, IN OUT PRTL_SPLAY_LINKS * Root)
Definition at line 496 of file splay.c.
References NULL, _RTL_SPLAY_LINKS::Parent, ParentsChildPointerAddress, RtlIsRoot, RtlLeftChild, RtlRightChild, RtlSubtreePredecessor(), and SwapSplayLinks().
PRTL_SPLAY_LINKS RtlRealPredecessor (IN PRTL_SPLAY_LINKS Links)
Definition at line 836 of file splay.c.
References NULL, RtlIsLeftChild, RtlIsRightChild, RtlLeftChild, RtlParent, and RtlRightChild.
PRTL_SPLAY_LINKS RtlRealSuccessor (IN PRTL_SPLAY_LINKS Links)
Definition at line 753 of file splay.c.
References NULL, RtlIsLeftChild, RtlIsRightChild, RtlLeftChild, RtlParent, and RtlRightChild.
PRTL_SPLAY_LINKS RtlSplay (IN PRTL_SPLAY_LINKS Links)
Definition at line 45 of file splay.c.
References _RTL_SPLAY_LINKS::LeftChild, NULL, _RTL_SPLAY_LINKS::Parent, ParentsChildPointerAddress, _RTL_SPLAY_LINKS::RightChild, RtlIsLeftChild, RtlIsRightChild, RtlIsRoot, and RtlParent.
Referenced by RtlDelete().
PRTL_SPLAY_LINKS RtlSubtreePredecessor (IN PRTL_SPLAY_LINKS Links)
Definition at line 692 of file splay.c.
References NULL, RtlLeftChild, and RtlRightChild.
Referenced by RtlDelete(), and RtlDeleteNoSplay().
PRTL_SPLAY_LINKS RtlSubtreeSuccessor (IN PRTL_SPLAY_LINKS Links)
Definition at line 630 of file splay.c.
References NULL, RtlLeftChild, and RtlRightChild.
VOID SwapSplayLinks (IN PRTL_SPLAY_LINKS Link1, IN PRTL_SPLAY_LINKS Link2)
Definition at line 919 of file splay.c.
References NULL, _RTL_SPLAY_LINKS::Parent, ParentsChildPointerAddress, RtlIsRoot, RtlParent, and SwapPointers.
Referenced by RtlDelete(), and RtlDeleteNoSplay().