Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/callback.c File Reference
callback.c File Reference
#include "ki.h"
Functions
VOID KeCheckIfStackExpandCalloutActive (VOID)
NTSTATUS KeUserModeCallback (IN ULONG ApiNumber, IN PVOID InputBuffer, IN ULONG InputLength, OUT PVOID *OutputBuffer, IN PULONG OutputLength)
Function Documentation
VOID KeCheckIfStackExpandCalloutActive (VOID)
Definition at line 24 of file callback.c.
References _KTHREAD::InitialStack, KeBugCheckEx(), KeGetCurrentThread(), and KERNEL_EXPAND_STACK_ACTIVE.
Referenced by KeTerminateThread(), and KeUserModeCallback().
NTSTATUS KeUserModeCallback (IN ULONG ApiNumber, IN PVOID InputBuffer, IN ULONG InputLength, OUT PVOID * OutputBuffer, IN PULONG OutputLength)
Definition at line 60 of file callback.c.
References ASSERT, except, EXCEPTION_EXECUTE_HANDLER, KeCheckIfStackExpandCalloutActive(), KeGdiFlushUserBatch, KeGetCurrentThread(), KeGetPreviousMode, KiCallUserMode(), NOTHING, ProbeForWrite(), RtlCopyMemory, Status, _KTHREAD::Teb, _KTHREAD::TrapFrame, and UserMode.