Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntpsapi.h File Reference
ntpsapi.h File Reference
#include "pebteb.h"
Data Structures
struct _CLIENT_ID
struct _CLIENT_ID64
struct _FIBER
struct _GDI_TEB_BATCH
struct _INITIAL_TEB
struct _IO_COUNTERS
struct _JOB_SET_ARRAY
struct _JOBOBJECT_ASSOCIATE_COMPLETION_PORT
struct _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION
struct _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION
struct _JOBOBJECT_BASIC_LIMIT_INFORMATION
struct _JOBOBJECT_BASIC_PROCESS_ID_LIST
struct _JOBOBJECT_BASIC_UI_RESTRICTIONS
struct _JOBOBJECT_END_OF_JOB_TIME_INFORMATION
struct _JOBOBJECT_EXTENDED_LIMIT_INFORMATION
struct _JOBOBJECT_JOBSET_INFORMATION
struct _JOBOBJECT_SECURITY_LIMIT_INFORMATION
struct _KERNEL_USER_TIMES
struct _NT_TIB
struct _NT_TIB32
struct _NT_TIB64
struct _PEB_FREE_BLOCK
struct _PEB_LDR_DATA
struct _POOLED_USAGE_AND_LIMITS
struct _PROCESS_ACCESS_TOKEN
struct _PROCESS_BASIC_INFORMATION
struct _PROCESS_BASIC_INFORMATION64
struct _PROCESS_DEVICEMAP_INFORMATION
struct _PROCESS_DEVICEMAP_INFORMATION_EX
struct _PROCESS_FOREGROUND_BACKGROUND
struct _PROCESS_HANDLE_TRACING_ENABLE
struct _PROCESS_HANDLE_TRACING_ENABLE_EX
struct _PROCESS_HANDLE_TRACING_ENTRY
struct _PROCESS_HANDLE_TRACING_QUERY
struct _PROCESS_PRIORITY_CLASS
struct _PROCESS_SESSION_INFORMATION
struct _PROCESS_WS_WATCH_INFORMATION
struct _QUOTA_LIMITS
struct _QUOTA_LIMITS_EX
struct _THREAD_BASIC_INFORMATION
struct _VM_COUNTERS
struct _VM_COUNTERS_EX
struct _Wx86ThreadState
struct _Wx86TIB
Macros
#define CLIENT_ID64_DEFINED
#define EXCEPTION_CHAIN_END ((struct _EXCEPTION_REGISTRATION_RECORD * POINTER_32)-1)
#define FLS_MAXIMUM_AVAILABLE 128
#define FOREGROUND_BASE_PRIORITY 9
#define GDI_BATCH_BUFFER_SIZE 310
#define GDI_HANDLE_BUFFER_SIZE GDI_HANDLE_BUFFER_SIZE32
#define GDI_HANDLE_BUFFER_SIZE32 34
#define GDI_HANDLE_BUFFER_SIZE64 60
#define JOB_OBJECT_ALL_ACCESS
#define JOB_OBJECT_ASSIGN_PROCESS (0x0001)
#define JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS 0x000000ff
#define JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS 0x00003fff
#define JOB_OBJECT_LIMIT_ACTIVE_PROCESS 0x00000008
#define JOB_OBJECT_LIMIT_AFFINITY 0x00000010
#define JOB_OBJECT_LIMIT_BREAKAWAY_OK 0x00000800
#define JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION 0x00000400
#define JOB_OBJECT_LIMIT_JOB_MEMORY 0x00000200
#define JOB_OBJECT_LIMIT_JOB_TIME 0x00000004
#define JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE 0x00002000
#define JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME 0x00000040
#define JOB_OBJECT_LIMIT_PRIORITY_CLASS 0x00000020
#define JOB_OBJECT_LIMIT_PROCESS_MEMORY 0x00000100
#define JOB_OBJECT_LIMIT_PROCESS_TIME 0x00000002
#define JOB_OBJECT_LIMIT_RESERVED2 0x00004000
#define JOB_OBJECT_LIMIT_RESERVED3 0x00008000
#define JOB_OBJECT_LIMIT_RESERVED4 0x00010000
#define JOB_OBJECT_LIMIT_RESERVED5 0x00020000
#define JOB_OBJECT_LIMIT_RESERVED6 0x00040000
#define JOB_OBJECT_LIMIT_SCHEDULING_CLASS 0x00000080
#define JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK 0x00001000
#define JOB_OBJECT_LIMIT_VALID_FLAGS 0x0007ffff
#define JOB_OBJECT_LIMIT_WORKINGSET 0x00000001
#define JOB_OBJECT_MSG_ABNORMAL_EXIT_PROCESS 8
#define JOB_OBJECT_MSG_ACTIVE_PROCESS_LIMIT 3
#define JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO 4
#define JOB_OBJECT_MSG_END_OF_JOB_TIME 1
#define JOB_OBJECT_MSG_END_OF_PROCESS_TIME 2
#define JOB_OBJECT_MSG_EXIT_PROCESS 7
#define JOB_OBJECT_MSG_JOB_MEMORY_LIMIT 10
#define JOB_OBJECT_MSG_NEW_PROCESS 6
#define JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT 9
#define JOB_OBJECT_POST_AT_END_OF_JOB 1
#define JOB_OBJECT_QUERY (0x0004)
#define JOB_OBJECT_RESERVED_LIMIT_VALID_FLAGS 0x0007ffff
#define JOB_OBJECT_SECURITY_FILTER_TOKENS 0x00000008
#define JOB_OBJECT_SECURITY_NO_ADMIN 0x00000001
#define JOB_OBJECT_SECURITY_ONLY_TOKEN 0x00000004
#define JOB_OBJECT_SECURITY_RESTRICTED_TOKEN 0x00000002
#define JOB_OBJECT_SECURITY_VALID_FLAGS 0x0000000f
#define JOB_OBJECT_SET_ATTRIBUTES (0x0002)
#define JOB_OBJECT_SET_SECURITY_ATTRIBUTES (0x0010)
#define JOB_OBJECT_TERMINATE (0x0008)
#define JOB_OBJECT_TERMINATE_AT_END_OF_JOB 0
#define JOB_OBJECT_UI_VALID_FLAGS 0x000000FF
#define JOB_OBJECT_UILIMIT_ALL 0x000000FF
#define JOB_OBJECT_UILIMIT_DESKTOP 0x00000040
#define JOB_OBJECT_UILIMIT_DISPLAYSETTINGS 0x00000010
#define JOB_OBJECT_UILIMIT_EXITWINDOWS 0x00000080
#define JOB_OBJECT_UILIMIT_GLOBALATOMS 0x00000020
#define JOB_OBJECT_UILIMIT_HANDLES 0x00000001
#define JOB_OBJECT_UILIMIT_NONE 0x00000000
#define JOB_OBJECT_UILIMIT_READCLIPBOARD 0x00000002
#define JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS 0x00000008
#define JOB_OBJECT_UILIMIT_WRITECLIPBOARD 0x00000004
#define MAJOR_VERSION 30
#define MAXIMUM_PROCESSORS 32
#define MINOR_VERSION 00
#define NORMAL_BASE_PRIORITY 8
#define NtCurrentPeb() (NtCurrentTeb()->ProcessEnvironmentBlock)
#define NtCurrentProcess() ((HANDLE)(LONG_PTR) -1)
#define NtCurrentThread() ((HANDLE)(LONG_PTR) -2)
#define OS2_VERSION (MAJOR_VERSION << 8 | MINOR_VERSION)
#define PEB_STDIO_HANDLE_NATIVE 0
#define PEB_STDIO_HANDLE_PM 2
#define PEB_STDIO_HANDLE_RESERVED 3
#define PEB_STDIO_HANDLE_SUBSYS 1
#define PROCESS_ALL_ACCESS
#define PROCESS_CREATE_FLAGS_ALL_LARGE_PAGE_FLAGS (PROCESS_CREATE_FLAGS_LARGE_PAGES)
#define PROCESS_CREATE_FLAGS_BREAKAWAY 0x00000001
#define PROCESS_CREATE_FLAGS_INHERIT_HANDLES 0x00000004
#define PROCESS_CREATE_FLAGS_LARGE_PAGES 0x00000010
#define PROCESS_CREATE_FLAGS_LEGAL_MASK
#define PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT 0x00000002
#define PROCESS_CREATE_FLAGS_OVERRIDE_ADDRESS_SPACE 0x00000008
#define PROCESS_CREATE_PROCESS (0x0080)
#define PROCESS_CREATE_THREAD (0x0002)
#define PROCESS_DEBUG_INHERIT 0x00000001
#define PROCESS_DUP_HANDLE (0x0040)
#define PROCESS_HANDLE_TRACING_MAX_STACKS 16
#define PROCESS_HARDERROR_ALIGNMENT_BIT 0x0004
#define PROCESS_HARDERROR_DEFAULT 1
#define PROCESS_LUID_DOSDEVICES_ONLY 0x00000001
#define PROCESS_PRIORITY_CLASS_ABOVE_NORMAL 6
#define PROCESS_PRIORITY_CLASS_BELOW_NORMAL 5
#define PROCESS_PRIORITY_CLASS_HIGH 3
#define PROCESS_PRIORITY_CLASS_IDLE 1
#define PROCESS_PRIORITY_CLASS_NORMAL 2
#define PROCESS_PRIORITY_CLASS_REALTIME 4
#define PROCESS_PRIORITY_CLASS_UNKNOWN 0
#define PROCESS_PRIORITY_SEPARATION_MASK 0x00000003
#define PROCESS_PRIORITY_SEPARATION_MAX 0x00000002
#define PROCESS_QUANTUM_FIXED_VALUE 0x00000008
#define PROCESS_QUANTUM_LONG_DEF 0x00000000
#define PROCESS_QUANTUM_LONG_MASK 0x00000030
#define PROCESS_QUANTUM_LONG_VALUE 0x00000010
#define PROCESS_QUANTUM_SHORT_VALUE 0x00000020
#define PROCESS_QUANTUM_VARIABLE_DEF 0x00000000
#define PROCESS_QUANTUM_VARIABLE_MASK 0x0000000c
#define PROCESS_QUANTUM_VARIABLE_VALUE 0x00000004
#define PROCESS_QUERY_INFORMATION (0x0400)
#define PROCESS_SET_INFORMATION (0x0200)
#define PROCESS_SET_PORT (0x0800)
#define PROCESS_SET_QUOTA (0x0100)
#define PROCESS_SET_SESSIONID (0x0004)
#define PROCESS_SUSPEND_RESUME (0x0800)
#define PROCESS_TERMINATE (0x0001)
#define PROCESS_VM_OPERATION (0x0008)
#define PROCESS_VM_READ (0x0010)
#define PROCESS_VM_WRITE (0x0020)
#define QUOTA_LIMITS_HARDWS_MAX_DISABLE 0x00000008
#define QUOTA_LIMITS_HARDWS_MAX_ENABLE 0x00000004
#define QUOTA_LIMITS_HARDWS_MIN_DISABLE 0x00000002
#define QUOTA_LIMITS_HARDWS_MIN_ENABLE 0x00000001
#define STATIC_UNICODE_BUFFER_LENGTH 261
#define THREAD_ALERT (0x0004)
#define THREAD_ALL_ACCESS
#define THREAD_BASE_PRIORITY_IDLE (-15)
#define THREAD_BASE_PRIORITY_LOWRT 15
#define THREAD_BASE_PRIORITY_MAX 2
#define THREAD_BASE_PRIORITY_MIN (-2)
#define THREAD_DIRECT_IMPERSONATION (0x0200)
#define THREAD_GET_CONTEXT (0x0008)
#define THREAD_IMPERSONATE (0x0100)
#define THREAD_QUERY_INFORMATION (0x0040)
#define THREAD_SET_CONTEXT (0x0010)
#define THREAD_SET_INFORMATION (0x0020)
#define THREAD_SET_THREAD_TOKEN (0x0080)
#define THREAD_SUSPEND_RESUME (0x0002)
#define THREAD_TERMINATE (0x0001)
#define TLS_EXPANSION_SLOTS 1024
#define TLS_MINIMUM_AVAILABLE 64
#define WIN32_CLIENT_INFO_LENGTH 62
#define WIN32_CLIENT_INFO_SPIN_COUNT 1
#define Wx86CurrentTib() (NULL)
#define ZwCurrentProcess() NtCurrentProcess()
#define ZwCurrentThread() NtCurrentThread()
Typedefs
typedef struct _CLIENT_ID CLIENT_ID
typedef struct _CLIENT_ID64 CLIENT_ID64
typedef struct _FIBER FIBER
typedef ULONG GDI_HANDLE_BUFFER[GDI_HANDLE_BUFFER_SIZE]
typedef ULONG GDI_HANDLE_BUFFER32[GDI_HANDLE_BUFFER_SIZE32]
typedef ULONG GDI_HANDLE_BUFFER64[GDI_HANDLE_BUFFER_SIZE64]
typedef struct _GDI_TEB_BATCH GDI_TEB_BATCH
typedef struct _INITIAL_TEB INITIAL_TEB
typedef struct _IO_COUNTERS IO_COUNTERS
typedef struct _JOB_SET_ARRAY JOB_SET_ARRAY
typedef struct _JOBOBJECT_ASSOCIATE_COMPLETION_PORT JOBOBJECT_ASSOCIATE_COMPLETION_PORT
typedef struct _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION JOBOBJECT_BASIC_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_LIMIT_INFORMATION JOBOBJECT_BASIC_LIMIT_INFORMATION
typedef struct _JOBOBJECT_BASIC_PROCESS_ID_LIST JOBOBJECT_BASIC_PROCESS_ID_LIST
typedef struct _JOBOBJECT_BASIC_UI_RESTRICTIONS JOBOBJECT_BASIC_UI_RESTRICTIONS
typedef struct _JOBOBJECT_END_OF_JOB_TIME_INFORMATION JOBOBJECT_END_OF_JOB_TIME_INFORMATION
typedef struct _JOBOBJECT_EXTENDED_LIMIT_INFORMATION JOBOBJECT_EXTENDED_LIMIT_INFORMATION
typedef struct _JOBOBJECT_JOBSET_INFORMATION JOBOBJECT_JOBSET_INFORMATION
typedef struct _JOBOBJECT_SECURITY_LIMIT_INFORMATION JOBOBJECT_SECURITY_LIMIT_INFORMATION
typedef enum _JOBOBJECTINFOCLASS JOBOBJECTINFOCLASS
typedef struct _KERNEL_USER_TIMES KERNEL_USER_TIMES
typedef struct _NT_TIB NT_TIB
typedef struct _NT_TIB32 NT_TIB32
typedef struct _NT_TIB64 NT_TIB64
typedef CLIENT_ID * PCLIENT_ID
typedef CLIENT_ID64 * PCLIENT_ID64
typedef struct _PEB_FREE_BLOCK PEB_FREE_BLOCK
typedef struct _PEB_LDR_DATA PEB_LDR_DATA
typedef struct _FIBER * PFIBER
typedef struct _GDI_TEB_BATCH * PGDI_TEB_BATCH
typedef struct _INITIAL_TEB * PINITIAL_TEB
typedef IO_COUNTERS * PIO_COUNTERS
typedef struct _JOB_SET_ARRAY * PJOB_SET_ARRAY
typedef struct _JOBOBJECT_ASSOCIATE_COMPLETION_PORT * PJOBOBJECT_ASSOCIATE_COMPLETION_PORT
typedef struct _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION * PJOBOBJECT_BASIC_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION * PJOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_LIMIT_INFORMATION * PJOBOBJECT_BASIC_LIMIT_INFORMATION
typedef struct _JOBOBJECT_BASIC_PROCESS_ID_LIST * PJOBOBJECT_BASIC_PROCESS_ID_LIST
typedef struct _JOBOBJECT_BASIC_UI_RESTRICTIONS * PJOBOBJECT_BASIC_UI_RESTRICTIONS
typedef struct _JOBOBJECT_END_OF_JOB_TIME_INFORMATION * PJOBOBJECT_END_OF_JOB_TIME_INFORMATION
typedef struct _JOBOBJECT_EXTENDED_LIMIT_INFORMATION * PJOBOBJECT_EXTENDED_LIMIT_INFORMATION
typedef struct _JOBOBJECT_JOBSET_INFORMATION * PJOBOBJECT_JOBSET_INFORMATION
typedef struct _JOBOBJECT_SECURITY_LIMIT_INFORMATION * PJOBOBJECT_SECURITY_LIMIT_INFORMATION
typedef KERNEL_USER_TIMES * PKERNEL_USER_TIMES
typedef NT_TIB * PNT_TIB
typedef struct _NT_TIB32 * PNT_TIB32
typedef struct _NT_TIB64 * PNT_TIB64
typedef struct _POOLED_USAGE_AND_LIMITS POOLED_USAGE_AND_LIMITS
typedef struct _PEB_FREE_BLOCK * PPEB_FREE_BLOCK
typedef struct _PEB_LDR_DATA * PPEB_LDR_DATA
typedef POOLED_USAGE_AND_LIMITS * PPOOLED_USAGE_AND_LIMITS
typedef struct _PROCESS_ACCESS_TOKEN * PPROCESS_ACCESS_TOKEN
typedef PROCESS_BASIC_INFORMATION * PPROCESS_BASIC_INFORMATION
typedef PROCESS_BASIC_INFORMATION64 * PPROCESS_BASIC_INFORMATION64
typedef struct _PROCESS_DEVICEMAP_INFORMATION * PPROCESS_DEVICEMAP_INFORMATION
typedef struct _PROCESS_DEVICEMAP_INFORMATION_EX * PPROCESS_DEVICEMAP_INFORMATION_EX
typedef struct _PROCESS_FOREGROUND_BACKGROUND * PPROCESS_FOREGROUND_BACKGROUND
typedef struct _PROCESS_HANDLE_TRACING_ENABLE * PPROCESS_HANDLE_TRACING_ENABLE
typedef struct _PROCESS_HANDLE_TRACING_ENABLE_EX * PPROCESS_HANDLE_TRACING_ENABLE_EX
typedef struct _PROCESS_HANDLE_TRACING_ENTRY * PPROCESS_HANDLE_TRACING_ENTRY
typedef struct _PROCESS_HANDLE_TRACING_QUERY * PPROCESS_HANDLE_TRACING_QUERY
typedef struct _PROCESS_PRIORITY_CLASS * PPROCESS_PRIORITY_CLASS
typedef struct _PROCESS_SESSION_INFORMATION * PPROCESS_SESSION_INFORMATION
typedef struct _PROCESS_WS_WATCH_INFORMATION * PPROCESS_WS_WATCH_INFORMATION
typedef VOID(* PPS_APC_ROUTINE) (__in_opt PVOID ApcArgument1, __in_opt PVOID ApcArgument2, __in_opt PVOID ApcArgument3)
typedef VOID(* PPS_POST_PROCESS_INIT_ROUTINE) (VOID)
typedef PVOID * PPVOID
typedef struct _QUOTA_LIMITS * PQUOTA_LIMITS
typedef struct _QUOTA_LIMITS_EX * PQUOTA_LIMITS_EX
typedef struct _PROCESS_ACCESS_TOKEN PROCESS_ACCESS_TOKEN
typedef struct _PROCESS_BASIC_INFORMATION PROCESS_BASIC_INFORMATION
typedef struct _PROCESS_BASIC_INFORMATION64 PROCESS_BASIC_INFORMATION64
typedef struct _PROCESS_DEVICEMAP_INFORMATION PROCESS_DEVICEMAP_INFORMATION
typedef struct _PROCESS_DEVICEMAP_INFORMATION_EX PROCESS_DEVICEMAP_INFORMATION_EX
typedef struct _PROCESS_FOREGROUND_BACKGROUND PROCESS_FOREGROUND_BACKGROUND
typedef struct _PROCESS_HANDLE_TRACING_ENABLE PROCESS_HANDLE_TRACING_ENABLE
typedef struct _PROCESS_HANDLE_TRACING_ENABLE_EX PROCESS_HANDLE_TRACING_ENABLE_EX
typedef struct _PROCESS_HANDLE_TRACING_ENTRY PROCESS_HANDLE_TRACING_ENTRY
typedef struct _PROCESS_HANDLE_TRACING_QUERY PROCESS_HANDLE_TRACING_QUERY
typedef struct _PROCESS_PRIORITY_CLASS PROCESS_PRIORITY_CLASS
typedef struct _PROCESS_SESSION_INFORMATION PROCESS_SESSION_INFORMATION
typedef struct _PROCESS_WS_WATCH_INFORMATION PROCESS_WS_WATCH_INFORMATION
typedef enum _PROCESSINFOCLASS PROCESSINFOCLASS
typedef THREAD_BASIC_INFORMATION * PTHREAD_BASIC_INFORMATION
typedef VM_COUNTERS * PVM_COUNTERS
typedef VM_COUNTERS_EX * PVM_COUNTERS_EX
typedef struct _Wx86ThreadState * PWX86THREAD
typedef struct _Wx86TIB * PWX86TIB
typedef struct _QUOTA_LIMITS QUOTA_LIMITS
typedef struct _QUOTA_LIMITS_EX QUOTA_LIMITS_EX
typedef struct _THREAD_BASIC_INFORMATION THREAD_BASIC_INFORMATION
typedef enum _THREADINFOCLASS THREADINFOCLASS
typedef struct _VM_COUNTERS VM_COUNTERS
typedef struct _VM_COUNTERS_EX VM_COUNTERS_EX
typedef struct _Wx86ThreadState WX86THREAD
typedef struct _Wx86TIB WX86TIB
Enumerations
enum _JOBOBJECTINFOCLASS {
JobObjectBasicAccountingInformation = 1, JobObjectBasicLimitInformation, JobObjectBasicProcessIdList, JobObjectBasicUIRestrictions,
JobObjectSecurityLimitInformation, JobObjectEndOfJobTimeInformation, JobObjectAssociateCompletionPortInformation, JobObjectBasicAndIoAccountingInformation,
JobObjectExtendedLimitInformation, JobObjectJobSetInformation, MaxJobObjectInfoClass
}
enum _PROCESSINFOCLASS {
ProcessBasicInformation, ProcessQuotaLimits, ProcessIoCounters, ProcessVmCounters,
ProcessTimes, ProcessBasePriority, ProcessRaisePriority, ProcessDebugPort,
ProcessExceptionPort, ProcessAccessToken, ProcessLdtInformation, ProcessLdtSize,
ProcessDefaultHardErrorMode, ProcessIoPortHandlers, ProcessPooledUsageAndLimits, ProcessWorkingSetWatch,
ProcessUserModeIOPL, ProcessEnableAlignmentFaultFixup, ProcessPriorityClass, ProcessWx86Information,
ProcessHandleCount, ProcessAffinityMask, ProcessPriorityBoost, ProcessDeviceMap,
ProcessSessionInformation, ProcessForegroundInformation, ProcessWow64Information, ProcessImageFileName,
ProcessLUIDDeviceMapsEnabled, ProcessBreakOnTermination, ProcessDebugObjectHandle, ProcessDebugFlags,
ProcessHandleTracing, ProcessIoPriority, ProcessExecuteFlags, ProcessResourceManagement,
ProcessCookie, ProcessImageInformation, MaxProcessInfoClass
}
enum _THREADINFOCLASS {
ThreadBasicInformation, ThreadTimes, ThreadPriority, ThreadBasePriority,
ThreadAffinityMask, ThreadImpersonationToken, ThreadDescriptorTableEntry, ThreadEnableAlignmentFaultFixup,
ThreadEventPair_Reusable, ThreadQuerySetWin32StartAddress, ThreadZeroTlsCell, ThreadPerformanceCount,
ThreadAmILastThread, ThreadIdealProcessor, ThreadPriorityBoost, ThreadSetTlsArrayAddress,
ThreadIsIoPending, ThreadHideFromDebugger, ThreadBreakOnTermination, ThreadSwitchLegacyState,
ThreadIsTerminated, MaxThreadInfoClass
}
Functions
C_ASSERT (FIELD_OFFSET(TEB, GdiTebBatch)==0x1d4)
NTSYSCALLAPI NTSTATUS NTAPI NtAlertResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
NTSYSCALLAPI NTSTATUS NTAPI NtAlertThread (__in HANDLE ThreadHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtAssignProcessToJobObject (__in HANDLE JobHandle, __in HANDLE ProcessHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateJobSet (__in ULONG NumJob, __in_ecount(NumJob) PJOB_SET_ARRAY UserJobSet, __in ULONG Flags)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in BOOLEAN InheritObjectTable, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateProcessEx (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in ULONG Flags, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort, __in ULONG JobMemberLevel)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ProcessHandle, __out PCLIENT_ID ClientId, __in PCONTEXT ThreadContext, __in PINITIAL_TEB InitialTeb, __in BOOLEAN CreateSuspended)
NTSYSCALLAPI NTSTATUS NTAPI NtGetContextThread (__in HANDLE ThreadHandle, __inout PCONTEXT ThreadContext)
NTSYSCALLAPI ULONG NTAPI NtGetCurrentProcessorNumber (VOID)
NTSYSCALLAPI NTSTATUS NTAPI NtGetNextProcess (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewProcessHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtGetNextThread (__in HANDLE ProcessHandle, __in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewThreadHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtImpersonateThread (__in HANDLE ServerThreadHandle, __in HANDLE ClientThreadHandle, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos)
NTSYSCALLAPI NTSTATUS NTAPI NtIsProcessInJob (__in HANDLE ProcessHandle, __in_opt HANDLE JobHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationJobObject (__in_opt HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __out_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __out_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __out_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryPortInformationProcess (VOID)
NTSYSCALLAPI NTSTATUS NTAPI NtQueueApcThread (__in HANDLE ThreadHandle, __in PPS_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcArgument1, __in_opt PVOID ApcArgument2, __in_opt PVOID ApcArgument3)
NTSYSCALLAPI NTSTATUS NTAPI NtRegisterThreadTerminatePort (__in HANDLE PortHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtResumeProcess (__in HANDLE ProcessHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
NTSYSCALLAPI NTSTATUS NTAPI NtSetContextThread (__in HANDLE ThreadHandle, __in PCONTEXT ThreadContext)
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationJobObject (__in HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __in_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __in_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __in_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetLdtEntries (__in ULONG Selector0, __in ULONG Entry0Low, __in ULONG Entry0Hi, __in ULONG Selector1, __in ULONG Entry1Low, __in ULONG Entry1Hi)
NTSYSCALLAPI NTSTATUS NTAPI NtSuspendProcess (__in HANDLE ProcessHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSuspendThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
NTSYSCALLAPI NTSTATUS NTAPI NtTerminateJobObject (__in HANDLE JobHandle, __in NTSTATUS ExitStatus)
NTSYSCALLAPI NTSTATUS NTAPI NtTerminateProcess (__in_opt HANDLE ProcessHandle, __in NTSTATUS ExitStatus)
NTSYSCALLAPI NTSTATUS NTAPI NtTerminateThread (__in_opt HANDLE ThreadHandle, __in NTSTATUS ExitStatus)
NTSYSCALLAPI NTSTATUS NTAPI NtTestAlert (VOID)
Macro Definition Documentation
#define CLIENT_ID64_DEFINED
Definition at line 183 of file ntpsapi.h.
#define EXCEPTION_CHAIN_END ((struct _EXCEPTION_REGISTRATION_RECORD * POINTER_32)-1)
Definition at line 361 of file ntpsapi.h.
Referenced by KiInitializeContextThread(), KiInitializePcr(), MmCreateTeb(), RtlDispatchException(), and RtlUnwind().
#define FLS_MAXIMUM_AVAILABLE 128
Definition at line 187 of file ntpsapi.h.
Referenced by PEBTEB_STRUCT().
#define FOREGROUND_BASE_PRIORITY 9
Definition at line 153 of file ntpsapi.h.
#define GDI_BATCH_BUFFER_SIZE 310
Definition at line 269 of file ntpsapi.h.
#define GDI_HANDLE_BUFFER_SIZE GDI_HANDLE_BUFFER_SIZE32
Definition at line 144 of file ntpsapi.h.
#define GDI_HANDLE_BUFFER_SIZE32 34
Definition at line 140 of file ntpsapi.h.
#define GDI_HANDLE_BUFFER_SIZE64 60
Definition at line 141 of file ntpsapi.h.
#define JOB_OBJECT_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | \
                                        0x1F )
Definition at line 106 of file ntpsapi.h.
Referenced by PspInitPhase0().
#define JOB_OBJECT_ASSIGN_PROCESS (0x0001)
Definition at line 101 of file ntpsapi.h.
Referenced by NtAssignProcessToJobObject().
#define JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS 0x000000ff
Definition at line 1362 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS 0x00003fff
Definition at line 1363 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_LIMIT_ACTIVE_PROCESS 0x00000008
Definition at line 1337 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PspAddProcessToJob().
#define JOB_OBJECT_LIMIT_AFFINITY 0x00000010
Definition at line 1338 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), NtSetInformationProcess(), and PspApplyJobLimitsToProcess().
#define JOB_OBJECT_LIMIT_BREAKAWAY_OK 0x00000800
Definition at line 1349 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PspCreateProcess().
#define JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION 0x00000400
Definition at line 1348 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_LIMIT_JOB_MEMORY 0x00000200
Definition at line 1347 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PsChangeJobMemoryUsage().
#define JOB_OBJECT_LIMIT_JOB_TIME 0x00000004
Definition at line 1336 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), PsEnforceExecutionTimeLimits(), and PspAddProcessToJob().
#define JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE 0x00002000
Definition at line 1351 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), and PspJobClose().
#define JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME 0x00000040
Definition at line 1340 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_LIMIT_PRIORITY_CLASS 0x00000020
Definition at line 1339 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), NtSetInformationProcess(), NtSetInformationThread(), and PspApplyJobLimitsToProcess().
#define JOB_OBJECT_LIMIT_PROCESS_MEMORY 0x00000100
Definition at line 1346 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), PspApplyJobLimitsToProcess(), and PsReportProcessMemoryLimitViolation().
#define JOB_OBJECT_LIMIT_PROCESS_TIME 0x00000002
Definition at line 1335 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PsEnforceExecutionTimeLimits().
#define JOB_OBJECT_LIMIT_RESERVED2 0x00004000
Definition at line 1353 of file ntpsapi.h.
#define JOB_OBJECT_LIMIT_RESERVED3 0x00008000
Definition at line 1354 of file ntpsapi.h.
#define JOB_OBJECT_LIMIT_RESERVED4 0x00010000
Definition at line 1355 of file ntpsapi.h.
#define JOB_OBJECT_LIMIT_RESERVED5 0x00020000
Definition at line 1356 of file ntpsapi.h.
#define JOB_OBJECT_LIMIT_RESERVED6 0x00040000
Definition at line 1357 of file ntpsapi.h.
#define JOB_OBJECT_LIMIT_SCHEDULING_CLASS 0x00000080
Definition at line 1341 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK 0x00001000
Definition at line 1350 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PspCreateProcess().
#define JOB_OBJECT_LIMIT_VALID_FLAGS 0x0007ffff
Definition at line 1360 of file ntpsapi.h.
#define JOB_OBJECT_LIMIT_WORKINGSET 0x00000001
Definition at line 1334 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), PspApplyJobLimitsToProcess(), PspApplyJobLimitsToProcessSet(), and PspSetQuotaLimits().
#define JOB_OBJECT_MSG_ABNORMAL_EXIT_PROCESS 8
Definition at line 1326 of file ntpsapi.h.
Referenced by PspExitProcess().
#define JOB_OBJECT_MSG_ACTIVE_PROCESS_LIMIT 3
Definition at line 1322 of file ntpsapi.h.
Referenced by PspAddProcessToJob().
#define JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO 4
Definition at line 1323 of file ntpsapi.h.
Referenced by PspFoldProcessAccountingIntoJob().
#define JOB_OBJECT_MSG_END_OF_JOB_TIME 1
Definition at line 1320 of file ntpsapi.h.
Referenced by PsEnforceExecutionTimeLimits().
#define JOB_OBJECT_MSG_END_OF_PROCESS_TIME 2
Definition at line 1321 of file ntpsapi.h.
Referenced by PsEnforceExecutionTimeLimits().
#define JOB_OBJECT_MSG_EXIT_PROCESS 7
Definition at line 1325 of file ntpsapi.h.
Referenced by PspExitProcess().
#define JOB_OBJECT_MSG_JOB_MEMORY_LIMIT 10
Definition at line 1328 of file ntpsapi.h.
Referenced by PsChangeJobMemoryUsage().
#define JOB_OBJECT_MSG_NEW_PROCESS 6
Definition at line 1324 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), and PspCreateThread().
#define JOB_OBJECT_MSG_PROCESS_MEMORY_LIMIT 9
Definition at line 1327 of file ntpsapi.h.
Referenced by PsReportProcessMemoryLimitViolation().
#define JOB_OBJECT_POST_AT_END_OF_JOB 1
Definition at line 1312 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PsEnforceExecutionTimeLimits().
#define JOB_OBJECT_QUERY (0x0004)
Definition at line 103 of file ntpsapi.h.
Referenced by NtCreateJobSet(), NtIsProcessInJob(), NtQueryInformationJobObject(), and PsOpenTokenOfJobObject().
#define JOB_OBJECT_RESERVED_LIMIT_VALID_FLAGS 0x0007ffff
Definition at line 1364 of file ntpsapi.h.
#define JOB_OBJECT_SECURITY_FILTER_TOKENS 0x00000008
Definition at line 1388 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_SECURITY_NO_ADMIN 0x00000001
Definition at line 1385 of file ntpsapi.h.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PsImpersonateClient().
#define JOB_OBJECT_SECURITY_ONLY_TOKEN 0x00000004
Definition at line 1387 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_SECURITY_RESTRICTED_TOKEN 0x00000002
Definition at line 1386 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and PsImpersonateClient().
#define JOB_OBJECT_SECURITY_VALID_FLAGS 0x0000000f
Definition at line 1390 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_SET_ATTRIBUTES (0x0002)
Definition at line 102 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_SET_SECURITY_ATTRIBUTES (0x0010)
Definition at line 105 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_TERMINATE (0x0008)
Definition at line 104 of file ntpsapi.h.
Referenced by NtTerminateJobObject().
#define JOB_OBJECT_TERMINATE_AT_END_OF_JOB 0
Definition at line 1311 of file ntpsapi.h.
Referenced by PsEnforceExecutionTimeLimits().
#define JOB_OBJECT_UI_VALID_FLAGS 0x000000FF
Definition at line 1383 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define JOB_OBJECT_UILIMIT_ALL 0x000000FF
Definition at line 1381 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_DESKTOP 0x00000040
Definition at line 1378 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_DISPLAYSETTINGS 0x00000010
Definition at line 1376 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_EXITWINDOWS 0x00000080
Definition at line 1379 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_GLOBALATOMS 0x00000020
Definition at line 1377 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_HANDLES 0x00000001
Definition at line 1372 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_NONE 0x00000000
Definition at line 1370 of file ntpsapi.h.
Referenced by NtAssignProcessToJobObject().
#define JOB_OBJECT_UILIMIT_READCLIPBOARD 0x00000002
Definition at line 1373 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS 0x00000008
Definition at line 1375 of file ntpsapi.h.
#define JOB_OBJECT_UILIMIT_WRITECLIPBOARD 0x00000004
Definition at line 1374 of file ntpsapi.h.
#define MAJOR_VERSION 30
Definition at line 370 of file ntpsapi.h.
#define MAXIMUM_PROCESSORS 32
Definition at line 62 of file ntpsapi.h.
Referenced by IoDisconnectInterrupt(), KeGetPrcb(), KeInsertQueueDpc(), KeSetIdealProcessorThread(), KeSetTargetProcessorDpc(), KeStartAllProcessors(), KiTimerExpiration(), KiTimerListExpire(), MiAllocateAweInfo(), MiAweViewRemover(), NtSetInformationThread(), WmipFlushActiveBuffers(), and WmiStartContextSwapTrace().
#define MINOR_VERSION 00
Definition at line 371 of file ntpsapi.h.
#define NORMAL_BASE_PRIORITY 8
Definition at line 154 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define NtCurrentPeb () (NtCurrentTeb()->ProcessEnvironmentBlock)
Definition at line 943 of file ntpsapi.h.
Referenced by LdrFindEntryForAddress(), RtlCreateEnvironment(), RtlCreateProcessParameters(), RtlMakeStackTraceDataPresent(), RtlpCreateStack(), RtlQueryEnvironmentVariable_U(), RtlSetCurrentEnvironment(), RtlSetEnvironmentStrings(), and RtlSetEnvironmentVariable().
#define NtCurrentProcess () ((HANDLE)(LONG_PTR) -1)
Definition at line 934 of file ntpsapi.h.
Referenced by DbgkpSendApiMessage(), DbgkpSendApiMessageLpc(), ExRaiseHardError(), KiDispatchException(), KiOpPatchCode(), MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MmCheckSystemImage(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushInstructionCache(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtIsProcessInJob(), NtLockVirtualMemory(), NtQueryInformationProcess(), NtQueryVirtualMemory(), NtResetWriteWatch(), NtSetInformationProcess(), NtTerminateProcess(), NtUnlockVirtualMemory(), ObpCloseHandle(), ObpReferenceProcessObjectByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), Phase1InitializationDiscard(), PspExitThread(), RtlAdjustPrivilege(), RtlAssert(), RtlCreateEnvironment(), RtlCreateUserProcess(), RtlDestroyEnvironment(), RtlFormatCurrentUserKeyPath(), RtlInitializeStackTraceDataBase(), RtlpCreateStack(), RtlpExtendStackTraceDataBase(), RtlpImpersonateSelfEx(), RtlpSysVolTakeOwnership(), RtlSetEnvironmentStrings(), RtlSetEnvironmentVariable(), and RtlSetProcessIsCritical().
#define NtCurrentThread () ((HANDLE)(LONG_PTR) -2)
Definition at line 1044 of file ntpsapi.h.
Referenced by NtTerminateThread(), ObpCloseHandle(), ObpReferenceProcessObjectByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), RtlAdjustPrivilege(), RtlAssert(), RtlFormatCurrentUserKeyPath(), RtlpImpersonateSelfEx(), and RtlSetThreadIsCritical().
#define OS2_VERSION (MAJOR_VERSION << 8 | MINOR_VERSION)
Definition at line 372 of file ntpsapi.h.
Referenced by MmCreateTeb().
#define PEB_STDIO_HANDLE_NATIVE 0
Definition at line 135 of file ntpsapi.h.
#define PEB_STDIO_HANDLE_PM 2
Definition at line 137 of file ntpsapi.h.
#define PEB_STDIO_HANDLE_RESERVED 3
Definition at line 138 of file ntpsapi.h.
#define PEB_STDIO_HANDLE_SUBSYS 1
Definition at line 136 of file ntpsapi.h.
#define PROCESS_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | \
                                   0xFFF)
Definition at line 52 of file ntpsapi.h.
Referenced by NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), ObInitSystem(), PspCreateProcess(), PspInitPhase0(), and RtlCreateUserProcess().
#define PROCESS_CREATE_FLAGS_ALL_LARGE_PAGE_FLAGS (PROCESS_CREATE_FLAGS_LARGE_PAGES)
Definition at line 889 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define PROCESS_CREATE_FLAGS_BREAKAWAY 0x00000001
Definition at line 883 of file ntpsapi.h.
Referenced by NtCreateProcess(), and PspCreateProcess().
#define PROCESS_CREATE_FLAGS_INHERIT_HANDLES 0x00000004
Definition at line 885 of file ntpsapi.h.
Referenced by NtCreateProcess(), and PspCreateProcess().
#define PROCESS_CREATE_FLAGS_LARGE_PAGES 0x00000010
Definition at line 887 of file ntpsapi.h.
Referenced by MmInitializeProcessAddressSpace(), and PspCreateProcess().
#define PROCESS_CREATE_FLAGS_LEGAL_MASK
Value:
(PROCESS_CREATE_FLAGS_BREAKAWAY | PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT | \
     PROCESS_CREATE_FLAGS_INHERIT_HANDLES | PROCESS_CREATE_FLAGS_OVERRIDE_ADDRESS_SPACE | \
     PROCESS_CREATE_FLAGS_ALL_LARGE_PAGE_FLAGS)
Definition at line 892 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT 0x00000002
Definition at line 884 of file ntpsapi.h.
Referenced by NtCreateProcess(), and PspCreateProcess().
#define PROCESS_CREATE_FLAGS_OVERRIDE_ADDRESS_SPACE 0x00000008
Definition at line 886 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define PROCESS_CREATE_PROCESS (0x0080)
Definition at line 44 of file ntpsapi.h.
Referenced by PspCreateProcess(), and PspSetPrimaryToken().
#define PROCESS_CREATE_THREAD (0x0002)
Definition at line 36 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), PspCreateProcess(), PspCreateThread(), PspSetPrimaryToken(), and WmipReceiveNotifications().
#define PROCESS_DEBUG_INHERIT 0x00000001
Definition at line 420 of file ntpsapi.h.
Referenced by NtQueryInformationProcess(), and NtSetInformationProcess().
#define PROCESS_DUP_HANDLE (0x0040)
Definition at line 42 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtDuplicateObject(), PspCreateProcess(), and PspSetPrimaryToken().
#define PROCESS_HANDLE_TRACING_MAX_STACKS 16
Definition at line 633 of file ntpsapi.h.
#define PROCESS_HARDERROR_ALIGNMENT_BIT 0x0004
Definition at line 512 of file ntpsapi.h.
Referenced by NtSetInformationProcess(), and PspCreateProcess().
#define PROCESS_HARDERROR_DEFAULT 1
Definition at line 516 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define PROCESS_LUID_DOSDEVICES_ONLY 0x00000001
Definition at line 611 of file ntpsapi.h.
Referenced by NtQueryInformationProcess(), and ObQueryDeviceMapInformation().
#define PROCESS_PRIORITY_CLASS_ABOVE_NORMAL 6
Definition at line 405 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), and NtSetInformationProcess().
#define PROCESS_PRIORITY_CLASS_BELOW_NORMAL 5
Definition at line 404 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define PROCESS_PRIORITY_CLASS_HIGH 3
Definition at line 402 of file ntpsapi.h.
Referenced by NtSetInformationJobObject().
#define PROCESS_PRIORITY_CLASS_IDLE 1
Definition at line 400 of file ntpsapi.h.
Referenced by PsChangeQuantumTable(), PspApplyJobLimitsToProcess(), PspComputeQuantumAndPriority(), and PspCreateProcess().
#define PROCESS_PRIORITY_CLASS_NORMAL 2
Definition at line 401 of file ntpsapi.h.
Referenced by PspCreateProcess().
#define PROCESS_PRIORITY_CLASS_REALTIME 4
Definition at line 403 of file ntpsapi.h.
Referenced by NtSetInformationJobObject(), NtSetInformationProcess(), and NtSetInformationThread().
#define PROCESS_PRIORITY_CLASS_UNKNOWN 0
Definition at line 399 of file ntpsapi.h.
#define PROCESS_PRIORITY_SEPARATION_MASK 0x00000003
Definition at line 500 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_PRIORITY_SEPARATION_MAX 0x00000002
Definition at line 501 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_FIXED_VALUE 0x00000008
Definition at line 505 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_LONG_DEF 0x00000000
Definition at line 507 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_LONG_MASK 0x00000030
Definition at line 506 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_LONG_VALUE 0x00000010
Definition at line 508 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_SHORT_VALUE 0x00000020
Definition at line 509 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_VARIABLE_DEF 0x00000000
Definition at line 503 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_VARIABLE_MASK 0x0000000c
Definition at line 502 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUANTUM_VARIABLE_VALUE 0x00000004
Definition at line 504 of file ntpsapi.h.
Referenced by PsChangeQuantumTable().
#define PROCESS_QUERY_INFORMATION (0x0400)
Definition at line 47 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtCreateProfile(), NtGetNextThread(), NtIsProcessInJob(), NtQueryInformationProcess(), NtQueryVirtualMemory(), PsOpenTokenOfProcess(), PspCreateProcess(), PspQueryPooledQuotaLimits(), PspQueryQuotaLimits(), PspQueryWorkingSetWatch(), PspSetPrimaryToken(), and WmipReceiveNotifications().
#define PROCESS_SET_INFORMATION (0x0200)
Definition at line 46 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtAssignProcessToJobObject(), NtSetInformationProcess(), PspCreateProcess(), and PspSetPrimaryToken().
#define PROCESS_SET_PORT (0x0800)
Definition at line 48 of file ntpsapi.h.
Referenced by NtDebugActiveProcess(), NtRemoveProcessDebug(), NtResumeProcess(), NtSetInformationProcess(), and NtSuspendProcess().
#define PROCESS_SET_QUOTA (0x0100)
Definition at line 45 of file ntpsapi.h.
Referenced by NtAssignProcessToJobObject(), PspCreateProcess(), PspSetPrimaryToken(), and PspSetQuotaLimits().
#define PROCESS_SET_SESSIONID (0x0004)
Definition at line 37 of file ntpsapi.h.
Referenced by NtSetInformationProcess().
#define PROCESS_SUSPEND_RESUME (0x0800)
Definition at line 49 of file ntpsapi.h.
#define PROCESS_TERMINATE (0x0001)
Definition at line 35 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtAssignProcessToJobObject(), NtTerminateProcess(), PspCreateProcess(), and PspSetPrimaryToken().
#define PROCESS_VM_OPERATION (0x0008)
Definition at line 38 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), MmSetBankedSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFlushVirtualMemory(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtMapViewOfSection(), NtProtectVirtualMemory(), NtResetWriteWatch(), NtUnlockVirtualMemory(), NtUnmapViewOfSection(), PspCreateProcess(), PspSetPrimaryToken(), SepRmCommandServerThreadInit(), and WmipReceiveNotifications().
#define PROCESS_VM_READ (0x0010)
Definition at line 39 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtQueryInformationProcess(), NtReadVirtualMemory(), PspCreateProcess(), PspSetPrimaryToken(), and WmipReceiveNotifications().
#define PROCESS_VM_WRITE (0x0020)
Definition at line 40 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtFlushInstructionCache(), NtSetInformationProcess(), NtWriteVirtualMemory(), PspCreateProcess(), PspSetPrimaryToken(), SepRmCommandServerThreadInit(), and WmipReceiveNotifications().
#define QUOTA_LIMITS_HARDWS_MAX_DISABLE 0x00000008
Definition at line 669 of file ntpsapi.h.
Referenced by PspQueryQuotaLimits(), and PspSetQuotaLimits().
#define QUOTA_LIMITS_HARDWS_MAX_ENABLE 0x00000004
Definition at line 668 of file ntpsapi.h.
Referenced by PspQueryQuotaLimits(), and PspSetQuotaLimits().
#define QUOTA_LIMITS_HARDWS_MIN_DISABLE 0x00000002
Definition at line 667 of file ntpsapi.h.
Referenced by PspQueryQuotaLimits(), and PspSetQuotaLimits().
#define QUOTA_LIMITS_HARDWS_MIN_ENABLE 0x00000001
Definition at line 666 of file ntpsapi.h.
Referenced by PspQueryQuotaLimits(), and PspSetQuotaLimits().
#define STATIC_UNICODE_BUFFER_LENGTH 261
Definition at line 293 of file ntpsapi.h.
Referenced by PEBTEB_STRUCT().
#define THREAD_ALERT (0x0004)
Definition at line 77 of file ntpsapi.h.
Referenced by NtAlertThread().
#define THREAD_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | \
                                   0x3FF)
Definition at line 90 of file ntpsapi.h.
Referenced by CmpInitializeHiveList(), ExpCreateWorkerThread(), ExpWorkerInitialization(), FsRtlInitializeWorkerThread(), KeInitSystem(), MiModifiedPageWriter(), MiSectionInitialization(), MiZeroInParallel(), MmInitSystem(), NtOpenThread(), NtOpenThreadTokenEx(), ObInitSystem(), PspCreateThread(), PspInitPhase0(), RtlCreateUserThread(), WmipReceiveNotifications(), and WmipStartLogger().
#define THREAD_BASE_PRIORITY_IDLE (-15)
Definition at line 526 of file ntpsapi.h.
Referenced by NtSetInformationThread().
#define THREAD_BASE_PRIORITY_LOWRT 15
Definition at line 523 of file ntpsapi.h.
Referenced by NtSetInformationThread().
#define THREAD_BASE_PRIORITY_MAX 2
Definition at line 524 of file ntpsapi.h.
Referenced by NtSetInformationThread().
#define THREAD_BASE_PRIORITY_MIN (-2)
Definition at line 525 of file ntpsapi.h.
Referenced by NtSetInformationThread().
#define THREAD_DIRECT_IMPERSONATION (0x0200)
Definition at line 87 of file ntpsapi.h.
Referenced by NtImpersonateThread().
#define THREAD_GET_CONTEXT (0x0008)
Definition at line 78 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtGetContextThread(), and SeRmInitPhase1().
#define THREAD_IMPERSONATE (0x0100)
Definition at line 86 of file ntpsapi.h.
Referenced by NtImpersonateAnonymousToken(), and NtImpersonateThread().
#define THREAD_QUERY_INFORMATION (0x0040)
Definition at line 83 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtQueryInformationThread(), PsOpenTokenOfThread(), PspCreateThread(), and SepOpenTokenOfThread().
#define THREAD_SET_CONTEXT (0x0010)
Definition at line 79 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtQueueApcThread(), NtSetContextThread(), and SeRmInitPhase1().
#define THREAD_SET_INFORMATION (0x0020)
Definition at line 81 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), ExpCreateWorkerThread(), NtSetInformationThread(), PspCreateThread(), and SeRmInitPhase1().
#define THREAD_SET_THREAD_TOKEN (0x0080)
Definition at line 85 of file ntpsapi.h.
Referenced by NtSetInformationThread().
#define THREAD_SUSPEND_RESUME (0x0002)
Definition at line 76 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtAlertResumeThread(), NtResumeThread(), and NtSuspendThread().
#define THREAD_TERMINATE (0x0001)
Definition at line 74 of file ntpsapi.h.
Referenced by DbgkpOpenHandles(), NtTerminateThread(), and PspCreateThread().
#define TLS_EXPANSION_SLOTS 1024
Definition at line 189 of file ntpsapi.h.
Referenced by NtSetInformationThread().
#define TLS_MINIMUM_AVAILABLE 64
Definition at line 188 of file ntpsapi.h.
Referenced by NtSetInformationThread(), and PEBTEB_STRUCT().
#define WIN32_CLIENT_INFO_LENGTH 62
Definition at line 294 of file ntpsapi.h.
Referenced by PEBTEB_STRUCT().
#define WIN32_CLIENT_INFO_SPIN_COUNT 1
Definition at line 296 of file ntpsapi.h.
#define Wx86CurrentTib () (NULL)
Definition at line 320 of file ntpsapi.h.
#define ZwCurrentProcess () NtCurrentProcess()
Definition at line 935 of file ntpsapi.h.
#define ZwCurrentThread () NtCurrentThread()
Definition at line 1045 of file ntpsapi.h.
Typedef Documentation
typedef struct _CLIENT_ID CLIENT_ID
typedef struct _CLIENT_ID64 CLIENT_ID64
typedef struct _FIBER FIBER
typedef ULONG GDI_HANDLE_BUFFER[GDI_HANDLE_BUFFER_SIZE ]
Definition at line 151 of file ntpsapi.h.
typedef ULONG GDI_HANDLE_BUFFER32[GDI_HANDLE_BUFFER_SIZE32]
Definition at line 149 of file ntpsapi.h.
typedef ULONG GDI_HANDLE_BUFFER64[GDI_HANDLE_BUFFER_SIZE64]
Definition at line 150 of file ntpsapi.h.
typedef struct _GDI_TEB_BATCH GDI_TEB_BATCH
typedef struct _INITIAL_TEB INITIAL_TEB
typedef struct _IO_COUNTERS IO_COUNTERS
typedef struct _JOB_SET_ARRAY JOB_SET_ARRAY
typedef struct _JOBOBJECT_ASSOCIATE_COMPLETION_PORT JOBOBJECT_ASSOCIATE_COMPLETION_PORT
typedef struct _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION JOBOBJECT_BASIC_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_LIMIT_INFORMATION JOBOBJECT_BASIC_LIMIT_INFORMATION
typedef struct _JOBOBJECT_BASIC_PROCESS_ID_LIST JOBOBJECT_BASIC_PROCESS_ID_LIST
typedef struct _JOBOBJECT_BASIC_UI_RESTRICTIONS JOBOBJECT_BASIC_UI_RESTRICTIONS
typedef struct _JOBOBJECT_END_OF_JOB_TIME_INFORMATION JOBOBJECT_END_OF_JOB_TIME_INFORMATION
typedef struct _JOBOBJECT_EXTENDED_LIMIT_INFORMATION JOBOBJECT_EXTENDED_LIMIT_INFORMATION
typedef struct _JOBOBJECT_JOBSET_INFORMATION JOBOBJECT_JOBSET_INFORMATION
typedef struct _JOBOBJECT_SECURITY_LIMIT_INFORMATION JOBOBJECT_SECURITY_LIMIT_INFORMATION
typedef enum _JOBOBJECTINFOCLASS JOBOBJECTINFOCLASS
typedef struct _KERNEL_USER_TIMES KERNEL_USER_TIMES
typedef struct _NT_TIB NT_TIB
typedef struct _NT_TIB32 NT_TIB32
typedef struct _NT_TIB64 NT_TIB64
typedef CLIENT_ID* PCLIENT_ID
Definition at line 170 of file ntpsapi.h.
typedef CLIENT_ID64* PCLIENT_ID64
Definition at line 181 of file ntpsapi.h.
typedef struct _PEB_FREE_BLOCK PEB_FREE_BLOCK
typedef struct _PEB_LDR_DATA PEB_LDR_DATA
typedef struct _FIBER * PFIBER
typedef struct _GDI_TEB_BATCH* PGDI_TEB_BATCH
typedef struct _INITIAL_TEB * PINITIAL_TEB
typedef IO_COUNTERS* PIO_COUNTERS
Definition at line 702 of file ntpsapi.h.
typedef struct _JOB_SET_ARRAY * PJOB_SET_ARRAY
typedef struct _JOBOBJECT_ASSOCIATE_COMPLETION_PORT * PJOBOBJECT_ASSOCIATE_COMPLETION_PORT
typedef struct _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION * PJOBOBJECT_BASIC_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION * PJOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION
typedef struct _JOBOBJECT_BASIC_LIMIT_INFORMATION * PJOBOBJECT_BASIC_LIMIT_INFORMATION
typedef struct _JOBOBJECT_BASIC_PROCESS_ID_LIST * PJOBOBJECT_BASIC_PROCESS_ID_LIST
typedef struct _JOBOBJECT_BASIC_UI_RESTRICTIONS * PJOBOBJECT_BASIC_UI_RESTRICTIONS
typedef struct _JOBOBJECT_END_OF_JOB_TIME_INFORMATION * PJOBOBJECT_END_OF_JOB_TIME_INFORMATION
typedef struct _JOBOBJECT_EXTENDED_LIMIT_INFORMATION * PJOBOBJECT_EXTENDED_LIMIT_INFORMATION
typedef struct _JOBOBJECT_JOBSET_INFORMATION * PJOBOBJECT_JOBSET_INFORMATION
typedef struct _JOBOBJECT_SECURITY_LIMIT_INFORMATION * PJOBOBJECT_SECURITY_LIMIT_INFORMATION
typedef KERNEL_USER_TIMES* PKERNEL_USER_TIMES
Definition at line 800 of file ntpsapi.h.
typedef NT_TIB* PNT_TIB
Definition at line 232 of file ntpsapi.h.
typedef struct _NT_TIB32 * PNT_TIB32
typedef struct _NT_TIB64 * PNT_TIB64
typedef struct _POOLED_USAGE_AND_LIMITS POOLED_USAGE_AND_LIMITS
typedef struct _PEB_FREE_BLOCK * PPEB_FREE_BLOCK
typedef struct _PEB_LDR_DATA * PPEB_LDR_DATA
typedef POOLED_USAGE_AND_LIMITS* PPOOLED_USAGE_AND_LIMITS
Definition at line 758 of file ntpsapi.h.
typedef struct _PROCESS_ACCESS_TOKEN * PPROCESS_ACCESS_TOKEN
typedef PROCESS_BASIC_INFORMATION* PPROCESS_BASIC_INFORMATION
Definition at line 556 of file ntpsapi.h.
typedef PROCESS_BASIC_INFORMATION64* PPROCESS_BASIC_INFORMATION64
Definition at line 570 of file ntpsapi.h.
typedef struct _PROCESS_DEVICEMAP_INFORMATION * PPROCESS_DEVICEMAP_INFORMATION
typedef struct _PROCESS_DEVICEMAP_INFORMATION_EX * PPROCESS_DEVICEMAP_INFORMATION_EX
typedef struct _PROCESS_FOREGROUND_BACKGROUND * PPROCESS_FOREGROUND_BACKGROUND
typedef struct _PROCESS_HANDLE_TRACING_ENABLE * PPROCESS_HANDLE_TRACING_ENABLE
typedef struct _PROCESS_HANDLE_TRACING_ENABLE_EX * PPROCESS_HANDLE_TRACING_ENABLE_EX
typedef struct _PROCESS_HANDLE_TRACING_ENTRY * PPROCESS_HANDLE_TRACING_ENTRY
typedef struct _PROCESS_HANDLE_TRACING_QUERY * PPROCESS_HANDLE_TRACING_QUERY
typedef struct _PROCESS_PRIORITY_CLASS * PPROCESS_PRIORITY_CLASS
typedef struct _PROCESS_SESSION_INFORMATION * PPROCESS_SESSION_INFORMATION
typedef struct _PROCESS_WS_WATCH_INFORMATION * PPROCESS_WS_WATCH_INFORMATION
typedef VOID(* PPS_APC_ROUTINE) (__in_opt PVOID ApcArgument1, __in_opt PVOID ApcArgument2, __in_opt PVOID ApcArgument3)
Definition at line 1169 of file ntpsapi.h.
typedef VOID(* PPS_POST_PROCESS_INIT_ROUTINE) (VOID)
Definition at line 193 of file ntpsapi.h.
typedef PVOID* PPVOID
Definition at line 298 of file ntpsapi.h.
typedef struct _QUOTA_LIMITS * PQUOTA_LIMITS
typedef struct _QUOTA_LIMITS_EX * PQUOTA_LIMITS_EX
typedef struct _PROCESS_ACCESS_TOKEN PROCESS_ACCESS_TOKEN
typedef struct _PROCESS_BASIC_INFORMATION PROCESS_BASIC_INFORMATION
typedef struct _PROCESS_BASIC_INFORMATION64 PROCESS_BASIC_INFORMATION64
typedef struct _PROCESS_DEVICEMAP_INFORMATION PROCESS_DEVICEMAP_INFORMATION
typedef struct _PROCESS_DEVICEMAP_INFORMATION_EX PROCESS_DEVICEMAP_INFORMATION_EX
typedef struct _PROCESS_FOREGROUND_BACKGROUND PROCESS_FOREGROUND_BACKGROUND
typedef struct _PROCESS_HANDLE_TRACING_ENABLE PROCESS_HANDLE_TRACING_ENABLE
typedef struct _PROCESS_HANDLE_TRACING_ENABLE_EX PROCESS_HANDLE_TRACING_ENABLE_EX
typedef struct _PROCESS_HANDLE_TRACING_ENTRY PROCESS_HANDLE_TRACING_ENTRY
typedef struct _PROCESS_HANDLE_TRACING_QUERY PROCESS_HANDLE_TRACING_QUERY
typedef struct _PROCESS_PRIORITY_CLASS PROCESS_PRIORITY_CLASS
typedef struct _PROCESS_SESSION_INFORMATION PROCESS_SESSION_INFORMATION
typedef struct _PROCESS_WS_WATCH_INFORMATION PROCESS_WS_WATCH_INFORMATION
typedef enum _PROCESSINFOCLASS PROCESSINFOCLASS
typedef THREAD_BASIC_INFORMATION* PTHREAD_BASIC_INFORMATION
Definition at line 821 of file ntpsapi.h.
typedef VM_COUNTERS* PVM_COUNTERS
Definition at line 724 of file ntpsapi.h.
typedef VM_COUNTERS_EX* PVM_COUNTERS_EX
Definition at line 740 of file ntpsapi.h.
typedef struct _Wx86ThreadState * PWX86THREAD
typedef struct _Wx86TIB * PWX86TIB
typedef struct _QUOTA_LIMITS QUOTA_LIMITS
typedef struct _QUOTA_LIMITS_EX QUOTA_LIMITS_EX
typedef struct _THREAD_BASIC_INFORMATION THREAD_BASIC_INFORMATION
typedef enum _THREADINFOCLASS THREADINFOCLASS
typedef struct _VM_COUNTERS VM_COUNTERS
typedef struct _VM_COUNTERS_EX VM_COUNTERS_EX
typedef struct _Wx86ThreadState WX86THREAD
typedef struct _Wx86TIB WX86TIB
Enumeration Type Documentation
enum _JOBOBJECTINFOCLASS
Enumerator
JobObjectBasicAccountingInformation
JobObjectBasicLimitInformation
JobObjectBasicProcessIdList
JobObjectBasicUIRestrictions
JobObjectSecurityLimitInformation
JobObjectEndOfJobTimeInformation
JobObjectAssociateCompletionPortInformation
JobObjectBasicAndIoAccountingInformation
JobObjectExtendedLimitInformation
JobObjectJobSetInformation
MaxJobObjectInfoClass
Definition at line 1392 of file ntpsapi.h.
enum _PROCESSINFOCLASS
Enumerator
ProcessBasicInformation
ProcessQuotaLimits
ProcessIoCounters
ProcessVmCounters
ProcessTimes
ProcessBasePriority
ProcessRaisePriority
ProcessDebugPort
ProcessExceptionPort
ProcessAccessToken
ProcessLdtInformation
ProcessLdtSize
ProcessDefaultHardErrorMode
ProcessIoPortHandlers
ProcessPooledUsageAndLimits
ProcessWorkingSetWatch
ProcessUserModeIOPL
ProcessEnableAlignmentFaultFixup
ProcessPriorityClass
ProcessWx86Information
ProcessHandleCount
ProcessAffinityMask
ProcessPriorityBoost
ProcessDeviceMap
ProcessSessionInformation
ProcessForegroundInformation
ProcessWow64Information
ProcessImageFileName
ProcessLUIDDeviceMapsEnabled
ProcessBreakOnTermination
ProcessDebugObjectHandle
ProcessDebugFlags
ProcessHandleTracing
ProcessIoPriority
ProcessExecuteFlags
ProcessResourceManagement
ProcessCookie
ProcessImageInformation
MaxProcessInfoClass
Definition at line 428 of file ntpsapi.h.
enum _THREADINFOCLASS
Enumerator
ThreadBasicInformation
ThreadTimes
ThreadPriority
ThreadBasePriority
ThreadAffinityMask
ThreadImpersonationToken
ThreadDescriptorTableEntry
ThreadEnableAlignmentFaultFixup
ThreadEventPair_Reusable
ThreadQuerySetWin32StartAddress
ThreadZeroTlsCell
ThreadPerformanceCount
ThreadAmILastThread
ThreadIdealProcessor
ThreadPriorityBoost
ThreadSetTlsArrayAddress
ThreadIsIoPending
ThreadHideFromDebugger
ThreadBreakOnTermination
ThreadSwitchLegacyState
ThreadIsTerminated
MaxThreadInfoClass
Definition at line 474 of file ntpsapi.h.
Function Documentation
C_ASSERT (FIELD_OFFSET(TEB, GdiTebBatch) = =0x1d4)
NTSYSCALLAPI NTSTATUS NTAPI NtAlertResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
Definition at line 534 of file psspnd.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeAlertResumeThread(), KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong, PsThreadType, STATUS_SUCCESS, _ETHREAD::Tcb, and THREAD_SUSPEND_RESUME.
NTSYSCALLAPI NTSTATUS NTAPI NtAlertThread (__in HANDLE ThreadHandle)
Definition at line 483 of file psspnd.c.
References KeAlertThread(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsThreadType, STATUS_SUCCESS, _ETHREAD::Tcb, and THREAD_ALERT.
NTSYSCALLAPI NTSTATUS NTAPI NtAssignProcessToJobObject (__in HANDLE JobHandle, __in HANDLE ProcessHandle)
Definition at line 267 of file psjob.c.
References ASSERT, _WIN32_JOBCALLOUT_PARAMETERS::CalloutType, _WIN32_JOBCALLOUT_PARAMETERS::Data, ERROR_NOT_ENOUGH_QUOTA, ExAcquireResourceExclusiveLite(), ExAcquireRundownProtection(), ExReleaseResourceLite(), ExReleaseRundownProtection(), FALSE, InterlockedCompareExchangePointer, _EPROCESS::Job, _WIN32_JOBCALLOUT_PARAMETERS::Job, JOB_OBJECT_ASSIGN_PROCESS, JOB_OBJECT_SECURITY_NO_ADMIN, JOB_OBJECT_UILIMIT_NONE, _EJOB::JobLock, KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), MmGetSessionId(), NT_SUCCESS, NULL, ObDereferenceObject(), ObDereferenceObjectEx(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_INFORMATION, PROCESS_SET_QUOTA, PROCESS_TERMINATE, PsDereferencePrimaryTokenEx, PsGetCurrentThread(), PsJobType, PspAddProcessToJob(), PsProcessType, PspSetPrimaryToken(), PspTerminateProcess(), PspW32JobCallout, PspWin32SessionCallout(), PsReferencePrimaryToken(), PsW32JobCalloutAddProcess, _EPROCESS::RundownProtect, _EJOB::SecurityLimitFlags, _EJOB::SessionId, SeSubProcessToken(), SeTokenIsAdmin(), Status, STATUS_ACCESS_DENIED, STATUS_PROCESS_IS_TERMINATING, _ETHREAD::Tcb, _EJOB::Token, _EJOB::TotalTerminatedProcesses, TRUE, _EJOB::UIRestrictionsClass, and _EPROCESS::Win32Process.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 73 of file psjob.c.
References _EJOB::Event, except, ExInitializeResourceLite(), ExSystemExceptionFilter(), FALSE, Handle, InitializeListHead(), InsertTailList(), _EJOB::JobLinks, _EJOB::JobLock, _EJOB::JobSetLinks, KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, MmGetSessionId(), NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), PAGED_CODE, ProbeForWriteHandle, _EJOB::ProcessListHead, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsJobType, PSP_DEFAULT_SCHEDULING_CLASSES, PspInitializeJobLimitsLock(), PspJobList, PspLockJobListExclusive(), PspUnlockJobListExclusive(), RtlZeroMemory, _EJOB::SchedulingClass, _EJOB::SessionId, Status, and _ETHREAD::Tcb.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateJobSet (__in ULONG NumJob, __in_ecount(NumJob) PJOB_SET_ARRAY UserJobSet, __in ULONG Flags)
Definition at line 3260 of file psjob.c.
References CONTAINING_RECORD, ExAllocatePoolWithQuotaTag, except, ExFreePool(), ExSystemExceptionFilter(), InitializeListHead(), InsertTailList(), IsListEmpty, JOB_OBJECT_QUERY, _JOB_SET_ARRAY::JobHandle, _EJOB::JobSetLinks, KeGetPreviousModeByThread, MAXULONG_PTR, _JOB_SET_ARRAY::MemberLevel, _EJOB::MemberLevel, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, ProbeForRead, PsGetCurrentThread(), PsJobType, PspLockJobListExclusive(), PspUnlockJobListExclusive(), RemoveHeadList(), RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TYPE_ALIGNMENT, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in BOOLEAN InheritObjectTable, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort)
Definition at line 816 of file create.c.
References NtCreateProcessEx(), PROCESS_CREATE_FLAGS_BREAKAWAY, PROCESS_CREATE_FLAGS_INHERIT_HANDLES, and PROCESS_CREATE_FLAGS_NO_DEBUG_INHERIT.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateProcessEx (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ParentProcess, __in ULONG Flags, __in_opt HANDLE SectionHandle, __in_opt HANDLE DebugPort, __in_opt HANDLE ExceptionPort, __in ULONG JobMemberLevel)
Definition at line 853 of file create.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, PAGED_CODE, ProbeForWriteHandle, PspCreateProcess(), Status, and STATUS_INVALID_PARAMETER.
Referenced by NtCreateProcess().
NTSYSCALLAPI NTSTATUS NTAPI NtCreateThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in HANDLE ProcessHandle, __out PCLIENT_ID ClientId, __in PCONTEXT ThreadContext, __in PINITIAL_TEB InitialTeb, __in BOOLEAN CreateSuspended)
Definition at line 78 of file create.c.
References ARGUMENT_PRESENT, CONTEXT_ALIGN, except, ExSystemExceptionFilter(), KeGetPreviousMode, KernelMode, NULL, _INITIAL_TEB::OldInitialTeb, _INITIAL_TEB::OldStackBase, _INITIAL_TEB::OldStackLimit, PAGED_CODE, ProbeForReadSmallStructure, ProbeForWriteHandle, ProbeForWriteSmallStructure(), PspCreateThread(), Status, and STATUS_INVALID_PARAMETER.
NTSYSCALLAPI NTSTATUS NTAPI NtGetContextThread (__in HANDLE ThreadHandle, __inout PCONTEXT ThreadContext)
Definition at line 309 of file psctx.c.
References FALSE, IS_SYSTEM_THREAD, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetContextThread(), PsGetCurrentThread(), PsThreadType, Status, STATUS_INVALID_HANDLE, _ETHREAD::Tcb, and THREAD_GET_CONTEXT.
Referenced by RtlRemoteCall().
NTSYSCALLAPI ULONG NTAPI NtGetCurrentProcessorNumber (VOID)
Definition at line 4214 of file psquery.c.
References KeGetCurrentProcessorNumber().
NTSYSCALLAPI NTSTATUS NTAPI NtGetNextProcess (__in HANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewProcessHandle)
Definition at line 595 of file psenum.c.
References except, ExSystemExceptionFilter(), _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObReferenceObjectByHandle, ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForWriteHandle, PROCESS_ALL_ACCESS, PsGetNextProcess(), PsProcessType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_NO_MORE_ENTRIES, and _OBJECT_TYPE::TypeInfo.
NTSYSCALLAPI NTSTATUS NTAPI NtGetNextThread (__in HANDLE ProcessHandle, __in HANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Flags, __out PHANDLE NewThreadHandle)
Definition at line 742 of file psenum.c.
References except, ExSystemExceptionFilter(), _OBJECT_TYPE_INITIALIZER::GenericMapping, _ETHREAD::GrantedAccess, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObReferenceObjectByHandle, ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForWriteHandle, PROCESS_ALL_ACCESS, PROCESS_QUERY_INFORMATION, PsGetNextProcessThread(), PsProcessType, PsThreadType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_NO_MORE_ENTRIES, THREAD_TO_PROCESS, and _OBJECT_TYPE::TypeInfo.
NTSYSCALLAPI NTSTATUS NTAPI NtImpersonateThread (__in HANDLE ServerThreadHandle, __in HANDLE ClientThreadHandle, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos)
Definition at line 27 of file psimpers.c.
References except, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForReadSmallStructure, PsThreadType, SeCreateClientSecurity(), SeDeleteClientSecurity, SeImpersonateClientEx(), Status, THREAD_DIRECT_IMPERSONATION, and THREAD_IMPERSONATE.
NTSYSCALLAPI NTSTATUS NTAPI NtIsProcessInJob (__in HANDLE ProcessHandle, __in_opt HANDLE JobHandle)
Definition at line 3117 of file psjob.c.
References _EPROCESS::Job, JOB_OBJECT_QUERY, KeGetPreviousModeByThread, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PROCESS_QUERY_INFORMATION, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsJobType, PsProcessType, Status, STATUS_PROCESS_IN_JOB, STATUS_PROCESS_NOT_IN_JOB, and _ETHREAD::Tcb.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenJobObject (__out PHANDLE JobHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 191 of file psjob.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObOpenObjectByName(), PAGED_CODE, ProbeForWriteHandle, PsJobType, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
Definition at line 28 of file psopen.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForReadSmallStructure, ProbeForWriteHandle, PROCESS_ALL_ACCESS, PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsProcessType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_INVALID_PARAMETER_MIX, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
Definition at line 272 of file psopen.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForReadSmallStructure, ProbeForWriteHandle, PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PsProcessType, PsThreadType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_INVALID_PARAMETER_MIX, THREAD_ALL_ACCESS, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationJobObject (__in_opt HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __out_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength, __out_opt PULONG ReturnLength)
Definition at line 904 of file psjob.c.
References _EJOB::ActiveProcesses, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::ActiveProcesses, _EJOB::ActiveProcessLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::ActiveProcessLimit, _EJOB::Affinity, _JOBOBJECT_BASIC_LIMIT_INFORMATION::Affinity, ARGUMENT_PRESENT, _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION::BasicInfo, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::BasicLimitInformation, _PS_JOB_TOKEN_FILTER::CapturedGroupCount, _PS_JOB_TOKEN_FILTER::CapturedGroups, _PS_JOB_TOKEN_FILTER::CapturedGroupsLength, _PS_JOB_TOKEN_FILTER::CapturedPrivilegeCount, _PS_JOB_TOKEN_FILTER::CapturedPrivileges, _PS_JOB_TOKEN_FILTER::CapturedPrivilegesLength, _PS_JOB_TOKEN_FILTER::CapturedSidCount, _PS_JOB_TOKEN_FILTER::CapturedSids, _PS_JOB_TOKEN_FILTER::CapturedSidsLength, CONTAINING_RECORD, _EJOB::EndOfJobTimeAction, _JOBOBJECT_END_OF_JOB_TIME_INFORMATION::EndOfJobTimeAction, ExAcquireResourceSharedLite(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), ExSystemExceptionFilter(), FALSE, FIELD_OFFSET, _EJOB::Filter, _LIST_ENTRY::Flink, _TOKEN_GROUPS::GroupCount, _TOKEN_GROUPS::Groups, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::IoInfo, _JOBOBJECT_BASIC_AND_IO_ACCOUNTING_INFORMATION::IoInfo, _EPROCESS::Job, JOB_OBJECT_QUERY, _EJOB::JobLock, _EJOB::JobMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::JobMemoryLimit, JobObjectBasicAccountingInformation, JobObjectBasicAndIoAccountingInformation, JobObjectBasicLimitInformation, JobObjectBasicProcessIdList, JobObjectBasicUIRestrictions, JobObjectEndOfJobTimeInformation, JobObjectExtendedLimitInformation, JobObjectJobSetInformation, JobObjectSecurityLimitInformation, _EPROCESS::JobStatus, KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), KeQueryValuesProcess(), KernelMode, _KPROCESS_VALUES::KernelTime, leave, _EJOB::LimitFlags, _JOBOBJECT_BASIC_LIMIT_INFORMATION::LimitFlags, _EJOB::MaximumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MaximumWorkingSetSize, MaxJobObjectInfoClass, _EJOB::MemberLevel, _JOBOBJECT_JOBSET_INFORMATION::MemberLevel, _EJOB::MinimumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MinimumWorkingSetSize, NT_SUCCESS, NULL, _JOBOBJECT_BASIC_PROCESS_ID_LIST::NumberOfAssignedProcesses, _JOBOBJECT_BASIC_PROCESS_ID_LIST::NumberOfProcessIdsInList, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, _IO_COUNTERS::OtherOperationCount, _EJOB::OtherOperationCount, _KPROCESS_VALUES::OtherOperationCount, _IO_COUNTERS::OtherTransferCount, _EJOB::OtherTransferCount, _KPROCESS_VALUES::OtherTransferCount, PAGE_SHIFT, PAGED_CODE, _MMSUPPORT::PageFaultCount, _EPROCESS::Pcb, _EJOB::PeakJobMemoryUsed, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::PeakJobMemoryUsed, _EJOB::PeakProcessMemoryUsed, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::PeakProcessMemoryUsed, _EJOB::PerJobUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerJobUserTimeLimit, _EJOB::PerProcessUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerProcessUserTimeLimit, _EJOB::PriorityClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PriorityClass, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::PrivilegesToDelete, ProbeForRead, ProbeForWriteUlong, _JOBOBJECT_BASIC_PROCESS_ID_LIST::ProcessIdList, _EJOB::ProcessListHead, _EJOB::ProcessMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::ProcessMemoryLimit, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsJobType, PspJobInfoAlign, PspJobInfoLengths, PspLockJobLimitsSharedUnsafe(), PspLockJobListShared(), PspUnlockJobLimitsSharedUnsafe(), PspUnlockJobListShared(), _LARGE_INTEGER::QuadPart, _IO_COUNTERS::ReadOperationCount, _EJOB::ReadOperationCount, _KPROCESS_VALUES::ReadOperationCount, _IO_COUNTERS::ReadTransferCount, _EJOB::ReadTransferCount, _KPROCESS_VALUES::ReadTransferCount, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::RestrictedSids, RtlCopyMemory, RtlCopySidAndAttributesArray(), RtlZeroMemory, _EJOB::SchedulingClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::SchedulingClass, _EJOB::SecurityLimitFlags, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SecurityLimitFlags, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SidsToDisable, STATUS_ACCESS_DENIED, STATUS_BUFFER_OVERFLOW, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::ThisPeriodTotalKernelTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::ThisPeriodTotalKernelTime, _EJOB::ThisPeriodTotalUserTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::ThisPeriodTotalUserTime, _EJOB::TotalKernelTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalKernelTime, _EJOB::TotalPageFaultCount, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalPageFaultCount, _EJOB::TotalProcesses, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalProcesses, _EJOB::TotalTerminatedProcesses, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalTerminatedProcesses, _EJOB::TotalUserTime, _JOBOBJECT_BASIC_ACCOUNTING_INFORMATION::TotalUserTime, TRUE, _EJOB::UIRestrictionsClass, _JOBOBJECT_BASIC_UI_RESTRICTIONS::UIRestrictionsClass, _EPROCESS::UniqueProcessId, _KPROCESS_VALUES::UserTime, _EPROCESS::Vm, _IO_COUNTERS::WriteOperationCount, _EJOB::WriteOperationCount, _KPROCESS_VALUES::WriteOperationCount, _IO_COUNTERS::WriteTransferCount, _EJOB::WriteTransferCount, and _KPROCESS_VALUES::WriteTransferCount.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __out_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength, __out_opt PULONG ReturnLength)
Definition at line 590 of file psquery.c.
References _KPROCESS::Affinity, _PROCESS_BASIC_INFORMATION::AffinityMask, ARGUMENT_PRESENT, _PROCESS_BASIC_INFORMATION::BasePriority, _KPROCESS::BasePriority, _PROCESS_HANDLE_TRACING_ENTRY::ClientId, _HANDLE_TRACE_DB_ENTRY::ClientId, _EPROCESS::CommitCharge, _EPROCESS::Cookie, _EPROCESS::CreateTime, _KERNEL_USER_TIMES::CreateTime, _HANDLE_TRACE_DEBUG_INFO::CurrentStackIndex, DbgkOpenProcessDebugPort(), _EPROCESS::DebugPort, _EPROCESS::DefaultHardErrorProcessing, _KPROCESS::DisableBoost, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExDereferenceHandleDebugInfo(), ExFreePool(), _EPROCESS::ExitStatus, _PROCESS_BASIC_INFORMATION::ExitStatus, _EPROCESS::ExitTime, _KERNEL_USER_TIMES::ExitTime, ExReferenceHandleDebugInfo(), ExReleaseRundownProtection(), FALSE, FIELD_OFFSET, _EPROCESS::Flags, _PROCESS_PRIORITY_CLASS::Foreground, _PROCESS_HANDLE_TRACING_ENTRY::Handle, _PROCESS_HANDLE_TRACING_QUERY::Handle, _HANDLE_TRACE_DB_ENTRY::Handle, _PROCESS_HANDLE_TRACING_QUERY::HandleTrace, _LARGE_INTEGER::HighPart, _EPROCESS::InheritedFromUniqueProcessId, _PROCESS_BASIC_INFORMATION::InheritedFromUniqueProcessId, InterlockedCompareExchange(), _KPRCB::InterruptTime, KeGetCurrentPrcb(), KeGetPreviousMode, KeMaximumIncrement, KeQueryRuntimeProcess(), KeQuerySystemTime(), KeQueryValuesProcess(), KernelMode, _KERNEL_USER_TIMES::KernelTime, KeStackAttachProcess(), _KPRCB::KeSystemCalls, KeUnstackDetachProcess(), _LARGE_INTEGER::LowPart, _UNICODE_STRING::MaximumLength, min, MmGetExecuteOptions(), MmGetImageInformation(), MmGetSessionId(), MmQueryWorkingSetInformation(), NT_SUCCESS, NtCurrentProcess, NULL, ObCloseHandle(), ObDereferenceObject(), ObDereferenceProcessHandleTable(), ObGetProcessHandleCount(), ObIsLUIDDeviceMapsEnabled(), ObQueryDeviceMapInformation(), ObReferenceObjectByHandle, ObReferenceProcessHandleTable(), _IO_COUNTERS::OtherOperationCount, _KPROCESS_VALUES::OtherOperationCount, _IO_COUNTERS::OtherTransferCount, _KPROCESS_VALUES::OtherTransferCount, PAGE_SHIFT, PAGED_CODE, _MMSUPPORT::PageFaultCount, _VM_COUNTERS_EX::PageFaultCount, _VM_COUNTERS_EX::PagefileUsage, _EPROCESS::Pcb, _VM_COUNTERS_EX::PeakPagefileUsage, _EPROCESS::PeakVirtualSize, _VM_COUNTERS_EX::PeakVirtualSize, _VM_COUNTERS_EX::PeakWorkingSetSize, _EPROCESS::Peb, _PROCESS_BASIC_INFORMATION::PebBaseAddress, _PROCESS_PRIORITY_CLASS::PriorityClass, _EPROCESS::PriorityClass, _VM_COUNTERS_EX::PrivateUsage, ProbeForRead, ProbeForWriteUlong, PROCESS_DEBUG_INHERIT, PROCESS_LUID_DOSDEVICES_ONLY, PROCESS_QUERY_INFORMATION, PROCESS_VM_READ, ProcessBasicInformation, ProcessBreakOnTermination, ProcessCookie, ProcessDebugFlags, ProcessDebugObjectHandle, ProcessDebugPort, ProcessDefaultHardErrorMode, ProcessDeviceMap, ProcessExecuteFlags, ProcessHandleCount, ProcessHandleTracing, ProcessImageFileName, ProcessImageInformation, ProcessIoCounters, ProcessLdtInformation, ProcessLUIDDeviceMapsEnabled, ProcessPooledUsageAndLimits, ProcessPriorityBoost, ProcessPriorityClass, ProcessQuotaLimits, ProcessSessionInformation, ProcessTimes, ProcessVmCounters, ProcessWorkingSetWatch, ProcessWow64Information, ProcessWx86Information, PS_GET_WOW64_PROCESS, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_PROCESS_FLAGS_VDM_ALLOWED, PsGetCurrentProcess(), PsNonPagedPool, PsPagedPool, PsPageFile, PspQueryLdtInformation(), PspQueryPooledQuotaLimits(), PspQueryQuotaLimits(), PspQueryWorkingSetWatch(), PsProcessType, _LARGE_INTEGER::QuadPart, _PROCESS_DEVICEMAP_INFORMATION::Query, _VM_COUNTERS_EX::QuotaNonPagedPoolUsage, _VM_COUNTERS_EX::QuotaPagedPoolUsage, _EPROCESS::QuotaPeak, _VM_COUNTERS_EX::QuotaPeakNonPagedPoolUsage, _VM_COUNTERS_EX::QuotaPeakPagedPoolUsage, _EPROCESS::QuotaUsage, _IO_COUNTERS::ReadOperationCount, _KPROCESS_VALUES::ReadOperationCount, _IO_COUNTERS::ReadTransferCount, _KPROCESS_VALUES::ReadTransferCount, RtlCopyMemory, _EPROCESS::RundownProtect, SeLocateProcessImageName(), _PROCESS_SESSION_INFORMATION::SessionId, _PROCESS_HANDLE_TRACING_ENTRY::Stacks, _HANDLE_TRACE_DB_ENTRY::StackTrace, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _HANDLE_TRACE_DEBUG_INFO::TableSize, _PROCESS_HANDLE_TRACING_QUERY::TotalTraces, _HANDLE_TRACE_DEBUG_INFO::TraceDb, _PROCESS_HANDLE_TRACING_ENTRY::Type, _HANDLE_TRACE_DB_ENTRY::Type, UInt32x32To64, _EPROCESS::UniqueProcessId, _PROCESS_BASIC_INFORMATION::UniqueProcessId, _KERNEL_USER_TIMES::UserTime, _EPROCESS::VirtualSize, _VM_COUNTERS_EX::VirtualSize, _EPROCESS::Vm, _VM_COUNTERS_EX::WorkingSetSize, _WOW64_PROCESS::Wow64, _IO_COUNTERS::WriteOperationCount, _KPROCESS_VALUES::WriteOperationCount, _IO_COUNTERS::WriteTransferCount, and _KPROCESS_VALUES::WriteTransferCount.
Referenced by RtlSetProcessIsCritical().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __out_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength, __out_opt PULONG ReturnLength)
Definition at line 3041 of file psquery.c.
References _EPROCESS::ActiveThreads, _KTHREAD::Affinity, _THREAD_BASIC_INFORMATION::AffinityMask, ARGUMENT_PRESENT, _THREAD_BASIC_INFORMATION::BasePriority, _ETHREAD::Cid, _THREAD_BASIC_INFORMATION::ClientId, _KERNEL_USER_TIMES::CreateTime, _ETHREAD::CrossThreadFlags, _KTHREAD::DisableBoost, except, EXCEPTION_EXECUTE_HANDLER, _ETHREAD::ExitStatus, _THREAD_BASIC_INFORMATION::ExitStatus, _ETHREAD::ExitTime, _KERNEL_USER_TIMES::ExitTime, _LARGE_INTEGER::HighPart, _ETHREAD::IrpList, IsListEmpty, KeGetPreviousModeByThread, KeMaximumIncrement, KeQueryBasePriorityThread(), KeReadStateThread(), KernelMode, _KERNEL_USER_TIMES::KernelTime, _KTHREAD::KernelTime, _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _THREAD_BASIC_INFORMATION::Priority, _KTHREAD::Priority, ProbeForRead, ProbeForWriteUlong, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_GET_THREAD_CREATE_TIME, PsGetCurrentThread(), PsIsThreadTerminating(), PspQueryDescriptorThread(), PsThreadType, _LARGE_INTEGER::QuadPart, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_PENDING, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, _THREAD_BASIC_INFORMATION::TebBaseAddress, THREAD_QUERY_INFORMATION, THREAD_TO_PROCESS, ThreadAmILastThread, ThreadBasicInformation, ThreadBreakOnTermination, ThreadDescriptorTableEntry, ThreadIsIoPending, ThreadIsTerminated, ThreadPerformanceCount, ThreadPriorityBoost, ThreadQuerySetWin32StartAddress, ThreadTimes, TRUE, UInt32x32To64, _KERNEL_USER_TIMES::UserTime, _KTHREAD::UserTime, and _ETHREAD::Win32StartAddress.
Referenced by RtlFreeUserThreadStack(), and RtlSetThreadIsCritical().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryPortInformationProcess (VOID)
Definition at line 1668 of file psquery.c.
References TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtQueueApcThread (__in HANDLE ThreadHandle, __in PPS_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcArgument1, __in_opt PVOID ApcArgument2, __in_opt PVOID ApcArgument3)
Definition at line 61 of file psctx.c.
References ExAllocatePoolWithQuotaTag, ExFreePool(), IS_SYSTEM_THREAD, KeGetPreviousMode, KeInitializeApc(), KeInsertQueueApc(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OriginalApcEnvironment, PAGED_CODE, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, PspQueueApcSpecialApc(), PsThreadType, STATUS_INVALID_HANDLE, STATUS_NO_MEMORY, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _ETHREAD::Tcb, THREAD_SET_CONTEXT, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtRegisterThreadTerminatePort (__in HANDLE PortHandle)
Definition at line 1679 of file psdelete.c.
References ExAllocatePoolWithQuotaTag, KeGetPreviousModeByThread, LpcPortObjectType, _TERMINATION_PORT::Next, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _TERMINATION_PORT::Port, PROTECTED_POOL, PsGetCurrentThread(), STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _ETHREAD::Tcb, and _ETHREAD::TerminationPort.
NTSYSCALLAPI NTSTATUS NTAPI NtResumeProcess (__in HANDLE ProcessHandle)
Definition at line 441 of file psspnd.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsProcessType, PsResumeProcess(), and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtResumeThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
Definition at line 323 of file psspnd.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong, PsResumeThread(), PsThreadType, STATUS_SUCCESS, and THREAD_SUSPEND_RESUME.
Referenced by RtlRemoteCall().
NTSYSCALLAPI NTSTATUS NTAPI NtSetContextThread (__in HANDLE ThreadHandle, __in PCONTEXT ThreadContext)
Definition at line 529 of file psctx.c.
References FALSE, IS_SYSTEM_THREAD, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PsSetContextThread(), PsThreadType, Status, STATUS_INVALID_HANDLE, _ETHREAD::Tcb, and THREAD_SET_CONTEXT.
Referenced by RtlRemoteCall().
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationJobObject (__in HANDLE JobHandle, __in JOBOBJECTINFOCLASS JobObjectInformationClass, __in_bcount(JobObjectInformationLength) PVOID JobObjectInformation, __in ULONG JobObjectInformationLength)
Definition at line 1444 of file psjob.c.
References _EJOB::ActiveProcessLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::ActiveProcessLimit, _EJOB::Affinity, _JOBOBJECT_BASIC_LIMIT_INFORMATION::Affinity, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::BasicLimitInformation, _WIN32_JOBCALLOUT_PARAMETERS::CalloutType, _EJOB::CompletionKey, _JOBOBJECT_ASSOCIATE_COMPLETION_PORT::CompletionKey, _EJOB::CompletionPort, _JOBOBJECT_ASSOCIATE_COMPLETION_PORT::CompletionPort, CONTAINING_RECORD, _WIN32_JOBCALLOUT_PARAMETERS::Data, _EJOB::EndOfJobTimeAction, _JOBOBJECT_END_OF_JOB_TIME_INFORMATION::EndOfJobTimeAction, _EJOB::Event, ExAcquireResourceExclusiveLite(), except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExReleaseResourceLite(), FALSE, _EJOB::Filter, _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IO_COMPLETION_MODIFY_STATE, IoSetIoCompletion(), IsListEmpty, _WIN32_JOBCALLOUT_PARAMETERS::Job, JOB_OBJECT_BASIC_LIMIT_VALID_FLAGS, JOB_OBJECT_EXTENDED_LIMIT_VALID_FLAGS, JOB_OBJECT_LIMIT_ACTIVE_PROCESS, JOB_OBJECT_LIMIT_AFFINITY, JOB_OBJECT_LIMIT_BREAKAWAY_OK, JOB_OBJECT_LIMIT_DIE_ON_UNHANDLED_EXCEPTION, JOB_OBJECT_LIMIT_JOB_MEMORY, JOB_OBJECT_LIMIT_JOB_TIME, JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE, JOB_OBJECT_LIMIT_PRESERVE_JOB_TIME, JOB_OBJECT_LIMIT_PRIORITY_CLASS, JOB_OBJECT_LIMIT_PROCESS_MEMORY, JOB_OBJECT_LIMIT_PROCESS_TIME, JOB_OBJECT_LIMIT_SCHEDULING_CLASS, JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, JOB_OBJECT_LIMIT_WORKINGSET, JOB_OBJECT_MSG_NEW_PROCESS, JOB_OBJECT_POST_AT_END_OF_JOB, JOB_OBJECT_SECURITY_FILTER_TOKENS, JOB_OBJECT_SECURITY_NO_ADMIN, JOB_OBJECT_SECURITY_ONLY_TOKEN, JOB_OBJECT_SECURITY_RESTRICTED_TOKEN, JOB_OBJECT_SECURITY_VALID_FLAGS, JOB_OBJECT_SET_ATTRIBUTES, JOB_OBJECT_SET_SECURITY_ATTRIBUTES, JOB_OBJECT_UI_VALID_FLAGS, _EJOB::JobFlags, _EJOB::JobLock, _EJOB::JobMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::JobMemoryLimit, JobObjectAssociateCompletionPortInformation, JobObjectBasicLimitInformation, JobObjectBasicUIRestrictions, JobObjectEndOfJobTimeInformation, JobObjectExtendedLimitInformation, JobObjectSecurityLimitInformation, _EPROCESS::JobStatus, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::JobToken, KeActiveProcessors, KeClearEvent(), KeEnterGuardedRegionThread(), KeGetPreviousModeByThread, KeLeaveGuardedRegionThread(), KeMaximumIncrement, KeMemoryBarrier(), KeQueryRuntimeProcess(), KeReadStateProcess(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), _EJOB::LimitFlags, _JOBOBJECT_BASIC_LIMIT_INFORMATION::LimitFlags, _JOB_WORKING_SET_CHANGE_HEAD::Links, _JOB_WORKING_SET_CHANGE_HEAD::MaximumWorkingSetSize, _EJOB::MaximumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MaximumWorkingSetSize, MaxJobObjectInfoClass, _JOB_WORKING_SET_CHANGE_HEAD::MinimumWorkingSetSize, _EJOB::MinimumWorkingSetSize, _JOBOBJECT_BASIC_LIMIT_INFORMATION::MinimumWorkingSetSize, MmAdjustWorkingSetSize(), MmEnforceWorkingSetLimit(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _EPROCESS::Pcb, _EJOB::PerJobUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerJobUserTimeLimit, _EJOB::PerProcessUserTimeLimit, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PerProcessUserTimeLimit, _EJOB::PriorityClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::PriorityClass, ProbeForRead, _JOB_WORKING_SET_CHANGE_RECORD::Process, PROCESS_PRIORITY_CLASS_ABOVE_NORMAL, PROCESS_PRIORITY_CLASS_HIGH, PROCESS_PRIORITY_CLASS_REALTIME, _EJOB::ProcessListHead, _EJOB::ProcessMemoryLimit, _JOBOBJECT_EXTENDED_LIMIT_INFORMATION::ProcessMemoryLimit, PS_JOB_FLAGS_CLOSE_DONE, PS_JOB_STATUS_ACCOUNTING_FOLDED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NEW_PROCESS_REPORTED, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_SET_CLEAR_BITS, PsGetCurrentThread(), PsJobType, PsMinimumWorkingSet, PSP_DEFAULT_SCHEDULING_CLASSES, PSP_NUMBER_OF_SCHEDULING_CLASSES, PspApplyJobLimitsToProcessSet(), PspCaptureTokenFilter(), PspFoldProcessAccountingIntoJob(), PspJobInfoAlign, PspJobInfoLengths, PspLockJobLimitsExclusiveUnsafe(), PspLockWorkingSetChangeExclusiveUnsafe(), PspUnlockJobLimitsExclusiveUnsafe(), PspUnlockWorkingSetChangeExclusiveUnsafe(), PspW32JobCallout, PspWin32SessionCallout(), PspWorkingSetChangeHead, PsW32JobCalloutSetInformation, _LARGE_INTEGER::QuadPart, RemoveHeadList(), RtlCopyMemory, _EJOB::SchedulingClass, _JOBOBJECT_BASIC_LIMIT_INFORMATION::SchedulingClass, SeAssignPrimaryTokenPrivilege, SeCheckPrivilegedObject(), _EJOB::SecurityLimitFlags, _JOBOBJECT_SECURITY_LIMIT_INFORMATION::SecurityLimitFlags, SeIncreaseBasePriorityPrivilege, SeIsChildTokenByPointer(), SeSinglePrivilegeCheck(), _EJOB::SessionId, SeTokenIsAdmin(), SeTokenObjectType, SeTokenType(), STATUS_BAD_TOKEN_TYPE, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _ETHREAD::Tcb, _EJOB::ThisPeriodTotalKernelTime, _EJOB::ThisPeriodTotalUserTime, _EJOB::Token, TOKEN_ASSIGN_PRIMARY, TOKEN_DUPLICATE, TOKEN_IMPERSONATE, TokenPrimary, TRUE, UInt32x32To64, _EJOB::UIRestrictionsClass, _JOBOBJECT_BASIC_UI_RESTRICTIONS::UIRestrictionsClass, ULongToPtr, and _EPROCESS::UniqueProcessId.
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __in_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength)
Definition at line 1981 of file psquery.c.
References _EJOB::Affinity, _KPROCESS::BasePriority, CONTAINING_RECORD, _PAGEFAULT_HISTORY::CurrentIndex, _EPROCESS::DefaultHardErrorProcessing, ExAcquireResourceSharedLite(), ExAcquireRundownProtection(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExDisableHandleTracing(), ExEnableHandleTracing(), ExFreePool(), ExReleaseResourceLite(), ExReleaseRundownProtection(), FALSE, _EPROCESS::Flags, _PROCESS_HANDLE_TRACING_ENABLE_EX::Flags, _LIST_ENTRY::Flink, _PROCESS_PRIORITY_CLASS::Foreground, _PROCESS_FOREGROUND_BACKGROUND::Foreground, HIGH_PRIORITY, InterlockedCompareExchangePointer, _EPROCESS::Job, JOB_OBJECT_LIMIT_AFFINITY, JOB_OBJECT_LIMIT_PRIORITY_CLASS, _EJOB::JobLock, Ke386SetIOPL(), KeActiveProcessors, KeBoostPriorityThread(), KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeInitializeSpinLock(), KeLeaveCriticalRegionThread(), KernelMode, KeSetAffinityProcess(), KeSetAutoAlignmentProcess(), KeSetDisableBoostProcess(), KeSetDisableBoostThread(), KeSetPriorityAndQuantumProcess(), _EJOB::LimitFlags, LOW_PRIORITY, LpcPortObjectType, MAX_WS_CATCH_INDEX, _PAGEFAULT_HISTORY::MaxIndex, MEMORY_PRIORITY_BACKGROUND, MEMORY_PRIORITY_FOREGROUND, MmGetSessionId(), MmSetExecuteOptions(), MmSetMemoryPriorityProcess(), NonPagedPool, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObDereferenceProcessHandleTable(), ObReferenceObjectByHandle, ObReferenceProcessHandleTable(), ObSetDeviceMap(), PAGED_CODE, _EPROCESS::Pcb, _PROCESS_PRIORITY_CLASS::PriorityClass, _EPROCESS::PriorityClass, _EJOB::PriorityClass, ProbeForRead, PROCESS_DEBUG_INHERIT, PROCESS_HARDERROR_ALIGNMENT_BIT, PROCESS_PRIORITY_CLASS_ABOVE_NORMAL, PROCESS_PRIORITY_CLASS_REALTIME, PROCESS_SET_INFORMATION, PROCESS_SET_PORT, PROCESS_SET_SESSIONID, PROCESS_VM_WRITE, ProcessAccessToken, ProcessAffinityMask, ProcessBasePriority, ProcessBreakOnTermination, ProcessDebugFlags, ProcessDefaultHardErrorMode, ProcessDeviceMap, ProcessEnableAlignmentFaultFixup, ProcessExceptionPort, ProcessExecuteFlags, ProcessForegroundInformation, ProcessHandleTracing, ProcessIoPortHandlers, ProcessLdtInformation, ProcessLdtSize, ProcessPriorityBoost, ProcessPriorityClass, ProcessQuotaLimits, ProcessRaisePriority, ProcessSessionInformation, ProcessUserModeIOPL, ProcessWorkingSetWatch, ProcessWx86Information, PS_CLEAR_BITS, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_PROCESS_FLAGS_VDM_ALLOWED, PS_SET_BITS, PsChargeProcessNonPagedPoolQuota(), PsGetCurrentThread(), PsGetNextProcessThread(), PspLockProcessExclusive(), PsProcessPriorityBackground, PsProcessPriorityForeground, PsProcessType, PspSetLdtInformation(), PspSetLdtSize(), PspSetPrimaryToken(), PspSetProcessIoHandlers(), PspSetQuotaLimits(), PspUnlockProcessExclusive(), PsReturnProcessNonPagedPoolQuota(), PsSetProcessPriorityByClass(), PsWatchEnabled, _EPROCESS::RundownProtect, SeCheckPrivilegedObject(), SeDebugPrivilege, SeIncreaseBasePriorityPrivilege, SeSinglePrivilegeCheck(), _PROCESS_SESSION_INFORMATION::SessionId, _PROCESS_DEVICEMAP_INFORMATION::Set, SeTcbPrivilege, _PAGEFAULT_HISTORY::SpinLock, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_ALREADY_SET, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, _EPROCESS::ThreadListHead, _PROCESS_HANDLE_TRACING_ENABLE_EX::TotalSlots, TRUE, _EPROCESS::WorkingSetWatch, and WS_CATCH_SIZE.
Referenced by RtlSetProcessIsCritical().
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __in_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength)
Definition at line 3503 of file psquery.c.
References _KPROCESS::Affinity, _ETHREAD::CrossThreadFlags, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), FALSE, HIGH_PRIORITY, _KTHREAD::IdealProcessor, _EPROCESS::Job, JOB_OBJECT_LIMIT_PRIORITY_CLASS, KeGetPreviousModeByThread, KernelMode, KeSetAffinityThread(), KeSetAutoAlignmentThread(), KeSetBasePriorityThread(), KeSetDisableBoostThread(), KeSetIdealProcessorThread(), KeSetPriorityThread(), KeStackAttachProcess(), KeUnstackDetachProcess(), _EJOB::LimitFlags, LOW_PRIORITY, LOW_REALTIME_PRIORITY, MAXIMUM_PROCESSORS, _KTHREAD::NpxState, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _EPROCESS::Pcb, Priority, _EPROCESS::PriorityClass, ProbeAndReadUlong, ProbeAndWriteLong, ProbeAndWriteUlong, ProbeForRead, ProbeForReadSmallStructure, PROCESS_PRIORITY_CLASS_REALTIME, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PS_SET_BITS, PsAssignImpersonationToken(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsGetNextProcessThread(), PspLockProcessShared(), PspUnlockProcessShared(), PsThreadType, _EPROCESS::RundownProtect, _ETHREAD::RundownProtect, SeCheckPrivilegedObject(), SeDebugPrivilege, SeIncreaseBasePriorityPrivilege, SeSinglePrivilegeCheck(), STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, THREAD_BASE_PRIORITY_IDLE, THREAD_BASE_PRIORITY_LOWRT, THREAD_BASE_PRIORITY_MAX, THREAD_BASE_PRIORITY_MIN, THREAD_SET_INFORMATION, THREAD_SET_THREAD_TOKEN, THREAD_TO_PROCESS, ThreadAffinityMask, ThreadBasePriority, ThreadBreakOnTermination, ThreadEnableAlignmentFaultFixup, ThreadHideFromDebugger, ThreadIdealProcessor, ThreadImpersonationToken, ThreadPriority, ThreadPriorityBoost, ThreadQuerySetWin32StartAddress, ThreadSetTlsArrayAddress, ThreadSwitchLegacyState, ThreadZeroTlsCell, TLS_EXPANSION_SLOTS, TLS_MINIMUM_AVAILABLE, _KTHREAD::TlsArray, TRUE, ULongToPtr, _ETHREAD::Win32StartAddress, and WOW64_GET_TEB32.
Referenced by RtlpImpersonateSelfEx(), and RtlSetThreadIsCritical().
NTSYSCALLAPI NTSTATUS NTAPI NtSetLdtEntries (__in ULONG Selector0, __in ULONG Entry0Low, __in ULONG Entry0Hi, __in ULONG Selector1, __in ULONG Entry1Low, __in ULONG Entry1Hi)
Definition at line 206 of file psldt.c.
References PsSetLdtEntries(), STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
NTSYSCALLAPI NTSTATUS NTAPI NtSuspendProcess (__in HANDLE ProcessHandle)
Definition at line 398 of file psspnd.c.
References KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_SET_PORT, PsProcessType, PsSuspendProcess(), and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtSuspendThread (__in HANDLE ThreadHandle, __out_opt PULONG PreviousSuspendCount)
Definition at line 206 of file psspnd.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong, PsSuspendThread(), PsThreadType, and THREAD_SUSPEND_RESUME.
Referenced by RtlRemoteCall().
NTSYSCALLAPI NTSTATUS NTAPI NtTerminateJobObject (__in HANDLE JobHandle, __in NTSTATUS ExitStatus)
Definition at line 2412 of file psjob.c.
References FALSE, JOB_OBJECT_TERMINATE, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PsJobType, PspTerminateAllProcessesInJob(), and _ETHREAD::Tcb.
NTSYSCALLAPI NTSTATUS NTAPI NtTerminateProcess (__in_opt HANDLE ProcessHandle, __in NTSTATUS ExitStatus)
Definition at line 274 of file psdelete.c.
References ARGUMENT_PRESENT, DBG_TERMINATE_PROCESS, DbgkClearProcessDebugObject(), _EPROCESS::DebugPort, ExAcquireRundownProtection(), ExReleaseRundownProtection(), FALSE, _EPROCESS::Flags, _EPROCESS::ImageFileName, KeGetPreviousModeByThread, NT_SUCCESS, NtCurrentProcess, NULL, ObClearProcessHandleTable(), ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_TERMINATE, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsGetNextProcessThread(), PspCatchCriticalBreak(), PsProcessType, PspTerminateThreadByPointer(), _EPROCESS::RundownProtect, STATUS_NOTHING_TO_TERMINATE, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtTerminateThread (__in_opt HANDLE ThreadHandle, __in NTSTATUS ExitStatus)
Definition at line 528 of file psdelete.c.
References _EPROCESS::ActiveThreads, ARGUMENT_PRESENT, FALSE, KeGetPreviousModeByThread, NT_SUCCESS, NtCurrentThread, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspTerminateThreadByPointer(), PsThreadType, Status, STATUS_CANT_TERMINATE_SELF, STATUS_SUCCESS, THREAD_TERMINATE, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtTestAlert (VOID)
Definition at line 611 of file psspnd.c.
References KeGetPreviousMode, KeTestAlertThread(), PAGED_CODE, STATUS_ALERTED, and STATUS_SUCCESS.