Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/add2strt.h File Reference
add2strt.h File Reference
Data Structures
struct in6_addr
struct in_addr
Macros
#define AF_INET 2
#define AF_INET6 23
#define INET6_ADDRSTRLEN 65
#define INET_ADDRSTRLEN 22
#define s6_bytes u.Byte
#define s6_words u.Word
#define s_addr S_un.S_addr
Functions
NTSTATUS RtlIpv4AddressToStringExT (__in const struct in_addr *Address, __in USHORT Port, __out_ecount_part(*AddressStringLength,*AddressStringLength) LPTSTR AddressString, __inout PULONG AddressStringLength)
LPTSTR RtlIpv4AddressToStringT (__in const struct in_addr *Addr, __out_ecount(16) LPTSTR S)
NTSTATUS RtlIpv6AddressToStringExT (__in const struct in6_addr *Address, __in ULONG ScopeId, __in USHORT Port, __out_ecount_part(*AddressStringLength,*AddressStringLength) LPTSTR AddressString, __inout PULONG AddressStringLength)
LPTSTR RtlIpv6AddressToStringT (__in const struct in6_addr *Addr, __out_ecount(INET6_ADDRSTRLEN) LPTSTR S)
Macro Definition Documentation
#define AF_INET 2
Definition at line 36 of file add2strt.h.
#define AF_INET6 23
Definition at line 37 of file add2strt.h.
#define INET6_ADDRSTRLEN 65
Definition at line 39 of file add2strt.h.
Referenced by RtlIpv6AddressToStringExT().
#define INET_ADDRSTRLEN 22
Definition at line 38 of file add2strt.h.
Referenced by RtlIpv4AddressToStringExT().
#define s6_bytes u.Byte
Definition at line 25 of file add2strt.h.
#define s6_words u.Word
Definition at line 26 of file add2strt.h.
#define s_addr S_un.S_addr
Definition at line 35 of file add2strt.h.
Function Documentation
NTSTATUS RtlIpv4AddressToStringExT (__in const struct in_addr * Address, __in USHORT Port, __out_ecount_part *,*AddressStringLength LPTSTR AddressString, __inout PULONG AddressStringLength)
Definition at line 292 of file add2strt.h.
References _stprintf, _T, INET_ADDRSTRLEN, NULL, RtlCopyMemory, RtlIpv4AddressToStringT(), RtlUshortByteSwap(), STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
LPTSTR RtlIpv4AddressToStringT (__in const struct in_addr * Addr, __out_ecount(16) LPTSTR S)
Definition at line 255 of file add2strt.h.
References _stprintf, and _T.
Referenced by RtlIpv4AddressToStringExT().
NTSTATUS RtlIpv6AddressToStringExT (__in const struct in6_addr * Address, __in ULONG ScopeId, __in USHORT Port, __out_ecount_part *,*AddressStringLength LPTSTR AddressString, __inout PULONG AddressStringLength)
Definition at line 179 of file add2strt.h.
References _stprintf, _T, INET6_ADDRSTRLEN, NULL, RtlCopyMemory, RtlIpv6AddressToStringT(), RtlUshortByteSwap(), STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
LPTSTR RtlIpv6AddressToStringT (__in const struct in6_addr * Addr, __out_ecount(INET6_ADDRSTRLEN) LPTSTR S)
Definition at line 42 of file add2strt.h.
References _stprintf, _T, and RtlUshortByteSwap().
Referenced by RtlIpv6AddressToStringExT().