Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/resource.c File Reference
resource.c File Reference
#include "exp.h"
#include "nturtl.h"
Macros
#define ASSERT_RESOURCE(_Resource)
#define DisablePriorityBoost 0x08
#define EX_ENSURE_APCS_DISABLED(Irql, Resource, Thread)
#define EX_RESOURCE_CHECK_FREES 0x1
#define EX_RESOURCE_CHECK_ORPHANS 0x2
#define EXP_LOCK_HANDLE KLOCK_QUEUE_HANDLE
#define EXP_LOCK_RESOURCE(_resource_, _plockhandle_) KeAcquireInStackQueuedSpinLock(&(_resource_)->SpinLock, (_plockhandle_))
#define EXP_LOCK_RESOURCE_RAISE EXP_LOCK_RESOURCE
#define EXP_UNLOCK_RESOURCE(_resource_, _plockhandle_) KeReleaseInStackQueuedSpinLock(_plockhandle_)
#define EXP_UNLOCK_RESOURCE_RAISE EXP_UNLOCK_RESOURCE
#define ExpIncrementCounter(Member)
#define IsBoostAllowed(a) (((a)->Flag & DisablePriorityBoost) == 0)
#define IsExclusiveWaiting(a) ((a)->NumberOfExclusiveWaiters != 0)
#define IsOwnedExclusive(a) (((a)->Flag & ResourceOwnedExclusive) != 0)
#define IsSharedWaiting(a) ((a)->NumberOfSharedWaiters != 0)
#define PEXP_LOCK_HANDLE PKLOCK_QUEUE_HANDLE
Functions
BOOLEAN ExAcquireResourceExclusiveLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
BOOLEAN ExAcquireResourceSharedLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
BOOLEAN ExAcquireSharedStarveExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
BOOLEAN ExAcquireSharedWaitForExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
VOID ExConvertExclusiveToSharedLite (__inout PERESOURCE Resource)
NTSTATUS ExDeleteResourceLite (__inout PERESOURCE Resource)
VOID ExDisableResourceBoostLite (__in PERESOURCE Resource)
PVOID ExEnterCriticalRegionAndAcquireResourceExclusive (__inout PERESOURCE Resource)
PVOID ExEnterCriticalRegionAndAcquireResourceShared (__inout PERESOURCE Resource)
PVOID ExEnterCriticalRegionAndAcquireSharedWaitForExclusive (__inout PERESOURCE Resource)
ULONG ExGetExclusiveWaiterCount (__in PERESOURCE Resource)
ULONG ExGetSharedWaiterCount (__in PERESOURCE Resource)
NTSTATUS ExInitializeResourceLite (__out PERESOURCE Resource)
BOOLEAN ExIsResourceAcquiredExclusiveLite (__in PERESOURCE Resource)
ULONG ExIsResourceAcquiredSharedLite (__in PERESOURCE Resource)
VOID ExpAllocateExclusiveWaiterEvent (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle)
VOID ExpAllocateSharedWaiterSemaphore (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle)
VOID FASTCALL ExpBoostOwnerThread (IN PKTHREAD CurrentThread, IN PKTHREAD OwnerThread)
PVOID ExpCheckForResource (IN PVOID p, IN SIZE_T Size)
VOID ExpExpandResourceOwnerTable (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle)
POWNER_ENTRY FASTCALL ExpFindCurrentThread (IN PERESOURCE Resource, IN ERESOURCE_THREAD CurrentThread, IN PEXP_LOCK_HANDLE LockHandle OPTIONAL)
POWNER_ENTRY FASTCALL ExpFindEmptyEntry (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle OPTIONAL)
BOOLEAN ExpResourceInitialization (VOID)
VOID FASTCALL ExpWaitForResource (IN PERESOURCE Resource, IN PVOID Object)
NTSTATUS ExQuerySystemLockInformation (__out_bcount(LockInformationLength) PRTL_PROCESS_LOCKS LockInformation, __in ULONG LockInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS ExReinitializeResourceLite (__inout PERESOURCE Resource)
VOID FASTCALL ExReleaseResourceAndLeaveCriticalRegion (__inout PERESOURCE Resource)
VOID ExReleaseResourceForThreadLite (__inout PERESOURCE Resource, __in ERESOURCE_THREAD CurrentThread)
VOID FASTCALL ExReleaseResourceLite (__inout PERESOURCE Resource)
VOID ExSetResourceOwnerPointer (__inout PERESOURCE Resource, __in PVOID OwnerPointer)
BOOLEAN ExTryToAcquireResourceExclusiveLite (__inout PERESOURCE Resource)
Variables
ALIGNED_SPINLOCK ExpResourceSpinLock
LIST_ENTRY ExpSystemResourcesList
LARGE_INTEGER ExpTimeout
ULONG ExResourceCheckFlags = EX_RESOURCE_CHECK_FREES|EX_RESOURCE_CHECK_ORPHANS
ULONG ExResourceTimeoutCount = 648000
LARGE_INTEGER ExShortTime = {(ULONG)(-10 * 1000 * 10), -1}
Macro Definition Documentation
#define ASSERT_RESOURCE (_Resource)
Definition at line 69 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExDeleteResourceLite(), ExDisableResourceBoostLite(), ExIsResourceAcquiredExclusiveLite(), ExIsResourceAcquiredSharedLite(), ExpExpandResourceOwnerTable(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), and ExTryToAcquireResourceExclusiveLite().
#define DisablePriorityBoost 0x08
Definition at line 44 of file resource.c.
Referenced by ExDisableResourceBoostLite().
#define EX_ENSURE_APCS_DISABLED (Irql, Resource, Thread)
Definition at line 273 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExReleaseResourceForThreadLite(), and ExReleaseResourceLite().
#define EX_RESOURCE_CHECK_FREES 0x1
Definition at line 48 of file resource.c.
Referenced by ExpCheckForResource().
#define EX_RESOURCE_CHECK_ORPHANS 0x2
Definition at line 49 of file resource.c.
#define EXP_LOCK_HANDLE KLOCK_QUEUE_HANDLE
Definition at line 88 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExDisableResourceBoostLite(), ExIsResourceAcquiredSharedLite(), ExpWaitForResource(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), and ExTryToAcquireResourceExclusiveLite().
#define EXP_LOCK_RESOURCE (_resource_, _plockhandle_) KeAcquireInStackQueuedSpinLock(&(_resource_)->SpinLock, (_plockhandle_))
Definition at line 159 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExDisableResourceBoostLite(), ExIsResourceAcquiredSharedLite(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateSharedWaiterSemaphore(), ExpExpandResourceOwnerTable(), ExpWaitForResource(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), and ExTryToAcquireResourceExclusiveLite().
#define EXP_LOCK_RESOURCE_RAISE EXP_LOCK_RESOURCE
Definition at line 162 of file resource.c.
Referenced by ExpExpandResourceOwnerTable().
#define EXP_UNLOCK_RESOURCE (_resource_, _plockhandle_) KeReleaseInStackQueuedSpinLock(_plockhandle_)
Definition at line 160 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExDisableResourceBoostLite(), ExIsResourceAcquiredSharedLite(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateSharedWaiterSemaphore(), ExpExpandResourceOwnerTable(), ExpWaitForResource(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), and ExTryToAcquireResourceExclusiveLite().
#define EXP_UNLOCK_RESOURCE_RAISE EXP_UNLOCK_RESOURCE
Definition at line 163 of file resource.c.
Referenced by ExpExpandResourceOwnerTable().
#define ExpIncrementCounter (Member)
Definition at line 226 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExpExpandResourceOwnerTable(), and ExTryToAcquireResourceExclusiveLite().
#define IsBoostAllowed (a) (((a)->Flag & DisablePriorityBoost) == 0)
Definition at line 38 of file resource.c.
Referenced by ExpWaitForResource().
#define IsExclusiveWaiting (a) ((a)->NumberOfExclusiveWaiters != 0)
Definition at line 35 of file resource.c.
Referenced by ExAcquireResourceSharedLite(), ExAcquireSharedWaitForExclusive(), ExDeleteResourceLite(), ExpWaitForResource(), ExReleaseResourceForThreadLite(), and ExReleaseResourceLite().
#define IsOwnedExclusive (a) (((a)->Flag & ResourceOwnedExclusive) != 0)
Definition at line 37 of file resource.c.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExIsResourceAcquiredExclusiveLite(), ExIsResourceAcquiredSharedLite(), ExpWaitForResource(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExSetResourceOwnerPointer(), and ExTryToAcquireResourceExclusiveLite().
#define IsSharedWaiting (a) ((a)->NumberOfSharedWaiters != 0)
Definition at line 36 of file resource.c.
Referenced by ExConvertExclusiveToSharedLite(), ExDeleteResourceLite(), ExpWaitForResource(), ExReleaseResourceForThreadLite(), and ExReleaseResourceLite().
#define PEXP_LOCK_HANDLE PKLOCK_QUEUE_HANDLE
Definition at line 89 of file resource.c.
Function Documentation
BOOLEAN ExAcquireResourceExclusiveLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 619 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateExclusiveWaiterEvent(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsOwnedExclusive, KeGetCurrentThread(), KeIsExecutingDpc(), NULL, PsGetCurrentThread(), ResourceNeverExclusive, ResourceOwnedExclusive, and TRUE.
Referenced by CcAcquireByteRangeForWrite(), CcPinFileData(), CcUnpinRepinnedBcb(), CmpLockRegistryExclusive(), ExEnterCriticalRegionAndAcquireResourceExclusive(), ExpRegisterFirmwareTableInformationHandler(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlCopyWrite(), FsRtlPrepareMdlWriteDev(), IopBootLog(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopGetSetSecurityObject(), IopInitializeBootLogging(), IopLoadDriver(), IopSetDeviceSecurityDescriptor(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoShutdownSystem(), IoUnregisterFileSystem(), IoUnregisterFsRegistrationChange(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiProcessLoaderEntry(), MmExtendSection(), MmInitSystem(), NtAssignProcessToJobObject(), NtQuerySystemInformation(), NtSetInformationJobObject(), ObpLockAllObjects(), Ps386GetVdmIoHandler(), PsEnforceExecutionTimeLimits(), PsGetNextJobProcess(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspAddProcessToJob(), PspExitProcessFromJob(), PspJobClose(), PspJobDelete(), PspRemoveProcessFromJob(), PspSetQuotaLimits(), and PspTerminateAllProcessesInJob().
BOOLEAN ExAcquireResourceSharedLite (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 861 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateSharedWaiterSemaphore(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsExclusiveWaiting, IsOwnedExclusive, KeGetCurrentThread(), KeIsExecutingDpc(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and TRUE.
Referenced by CmpLockRegistry(), ExEnterCriticalRegionAndAcquireResourceShared(), ExpGetSystemFirmwareTableInformation(), FsRtlAcquireFileForCcFlushEx(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), IoEnumerateRegisteredFiltersList(), IopGetSetSecurityObject(), IopInitializeBootLogging(), IopInvalidateVolumesForDevice(), IopLoadDriver(), IopMountVolume(), IopParseDevice(), IopSetDeviceSecurityDescriptor(), MiLookupDataTableEntry(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmLockPageableDataSection(), NtQueryInformationJobObject(), NtSetInformationProcess(), PspCreateThread(), and PspExitProcess().
BOOLEAN ExAcquireSharedStarveExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 1062 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateSharedWaiterSemaphore(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsOwnedExclusive, KeIsExecutingDpc(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and TRUE.
Referenced by CcPinFileData(), CcPinMappedData(), and CmpLockRegistry().
BOOLEAN ExAcquireSharedWaitForExclusive (__inout PERESOURCE Resource, __in BOOLEAN Wait)
Definition at line 1216 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpAllocateSharedWaiterSemaphore(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpIncrementCounter, ExpWaitForResource(), FALSE, IsExclusiveWaiting, IsOwnedExclusive, KeIsExecutingDpc(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and TRUE.
Referenced by ExEnterCriticalRegionAndAcquireSharedWaitForExclusive(), and FsRtlAcquireFileForModWriteEx().
VOID ExConvertExclusiveToSharedLite (__inout PERESOURCE Resource)
Definition at line 2089 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, IsOwnedExclusive, IsSharedWaiting, KeIsExecutingDpc(), KeReleaseSemaphore(), PsGetCurrentThread(), and ResourceOwnedExclusive.
Referenced by FsRtlAcquireFileForModWriteEx().
NTSTATUS ExDeleteResourceLite (__inout PERESOURCE Resource)
Definition at line 2151 of file resource.c.
References ASSERT, ASSERT_RESOURCE, ExFreePool(), FALSE, IsExclusiveWaiting, IsSharedWaiting, KeAcquireInStackQueuedSpinLock(), KeIsExecutingDpc(), KeReleaseInStackQueuedSpinLock(), NULL, RemoveEntryList(), and STATUS_SUCCESS.
Referenced by CcDeallocateBcb(), ObpDeleteObjectType(), PspDeleteVdmObjects(), PspJobDelete(), and SepTokenDeleteMethod().
VOID ExDisableResourceBoostLite (__in PERESOURCE Resource)
Definition at line 578 of file resource.c.
References ASSERT_RESOURCE, DisablePriorityBoost, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, and EXP_UNLOCK_RESOURCE.
PVOID ExEnterCriticalRegionAndAcquireResourceExclusive (__inout PERESOURCE Resource)
Definition at line 759 of file resource.c.
References _PsGetCurrentThread, ExAcquireResourceExclusiveLite(), KeEnterCriticalRegion(), and TRUE.
PVOID ExEnterCriticalRegionAndAcquireResourceShared (__inout PERESOURCE Resource)
Definition at line 1030 of file resource.c.
References _PsGetCurrentThread, ExAcquireResourceSharedLite(), KeEnterCriticalRegion(), and TRUE.
PVOID ExEnterCriticalRegionAndAcquireSharedWaitForExclusive (__inout PERESOURCE Resource)
Definition at line 1448 of file resource.c.
References _PsGetCurrentThread, ExAcquireSharedWaitForExclusive(), KeEnterCriticalRegion(), and TRUE.
ULONG ExGetExclusiveWaiterCount (__in PERESOURCE Resource)
Definition at line 2221 of file resource.c.
ULONG ExGetSharedWaiterCount (__in PERESOURCE Resource)
Definition at line 2248 of file resource.c.
NTSTATUS ExInitializeResourceLite (__out PERESOURCE Resource)
Definition at line 435 of file resource.c.
References ASSERT, FLG_KERNEL_STACK_TRACE_DB, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeInitializeSpinLock(), KeReleaseInStackQueuedSpinLock(), MmDeterminePoolType(), NonPagedPool, NtGlobalFlag, RtlLogStackBackTrace(), RtlZeroMemory, and STATUS_SUCCESS.
Referenced by CcAllocateInitializeBcb(), CmInitSystem1(), CmpInitializeHive(), ExpInitSystemPhase0(), FsRtlInitSystem(), IoInitSystem(), IopInitializeBootLogging(), MiInitializeLoadedModuleList(), MmInitSystem(), NtCreateJobObject(), ObCreateObjectType(), Psp386CreateVdmIoListHead(), PspVdmInitialize(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), SepInitializeWorkList(), and SepRmDbInitialization().
BOOLEAN ExIsResourceAcquiredExclusiveLite (__in PERESOURCE Resource)
Definition at line 2277 of file resource.c.
References ASSERT_RESOURCE, FALSE, IsOwnedExclusive, PsGetCurrentThread(), and TRUE.
Referenced by CmpDoFileSetSize(), and CmpUnlockRegistry().
ULONG ExIsResourceAcquiredSharedLite (__in PERESOURCE Resource)
Definition at line 2326 of file resource.c.
References ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, Index, IsOwnedExclusive, NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and _OWNER_ENTRY::TableSize.
Referenced by FsRtlAcquireFileForCcFlushEx().
VOID ExpAllocateExclusiveWaiterEvent (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle)
Definition at line 313 of file resource.c.
References ExAllocatePoolWithTag, ExFreePool(), EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, InterlockedCompareExchangePointer, KeDelayExecutionThread(), KeInitializeEvent(), KernelMode, NonPagedPool, NULL, SynchronizationEvent, and TRUE.
Referenced by ExAcquireResourceExclusiveLite().
VOID ExpAllocateSharedWaiterSemaphore (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle)
Definition at line 374 of file resource.c.
References ExAllocatePoolWithTag, ExFreePool(), EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, InterlockedCompareExchangePointer, KeDelayExecutionThread(), KeInitializeSemaphore(), KernelMode, MAXLONG, NonPagedPool, NULL, and TRUE.
Referenced by ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), and ExAcquireSharedWaitForExclusive().
VOID FASTCALL ExpBoostOwnerThread (IN PKTHREAD CurrentThread, IN PKTHREAD OwnerThread)
Definition at line 2515 of file resource.c.
References KiAcquireThreadLock(), KiReleaseThreadLock(), and KiSetPriorityThread().
Referenced by ExpWaitForResource().
PVOID ExpCheckForResource (IN PVOID p, IN SIZE_T Size)
Definition at line 3104 of file resource.c.
References CONTAINING_RECORD, DbgBreakPoint(), DbgPrint(), EX_RESOURCE_CHECK_FREES, ExpSystemResourcesList, ExResourceCheckFlags, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLock(), KeNumberProcessors, KeReleaseInStackQueuedSpinLock(), and NULL.
Referenced by ExFreePoolSanityChecks().
VOID ExpExpandResourceOwnerTable (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle)
Definition at line 2942 of file resource.c.
References ASSERT_RESOURCE, ExAllocatePoolWithTag, ExFreePool(), EXP_LOCK_RESOURCE, EXP_LOCK_RESOURCE_RAISE, EXP_UNLOCK_RESOURCE, EXP_UNLOCK_RESOURCE_RAISE, ExpIncrementCounter, FALSE, KeDelayExecutionThread(), KeGetCurrentThread(), KernelMode, KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), NonPagedPool, NULL, _KTHREAD::ResourceIndex, RtlCopyMemory, RtlZeroMemory, and _OWNER_ENTRY::TableSize.
Referenced by ExpFindCurrentThread(), and ExpFindEmptyEntry().
POWNER_ENTRY FASTCALL ExpFindCurrentThread (IN PERESOURCE Resource, IN ERESOURCE_THREAD CurrentThread, IN PEXP_LOCK_HANDLE LockHandle OPTIONAL)
Definition at line 2823 of file resource.c.
References ARGUMENT_PRESENT, ExpExpandResourceOwnerTable(), KeGetCurrentThread(), NULL, _OWNER_ENTRY::OwnerThread, _KTHREAD::ResourceIndex, and _OWNER_ENTRY::TableSize.
Referenced by ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), and ExSetResourceOwnerPointer().
POWNER_ENTRY FASTCALL ExpFindEmptyEntry (IN PERESOURCE Resource, IN PEXP_LOCK_HANDLE LockHandle OPTIONAL)
Definition at line 2752 of file resource.c.
References ASSERT, ExpExpandResourceOwnerTable(), KeGetCurrentThread(), NULL, _OWNER_ENTRY::OwnerThread, _KTHREAD::ResourceIndex, and _OWNER_ENTRY::TableSize.
Referenced by ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), and ExAcquireSharedWaitForExclusive().
BOOLEAN ExpResourceInitialization (VOID)
Definition at line 279 of file resource.c.
References InitializeListHead(), Int32x32To64, KeInitializeSpinLock(), _LARGE_INTEGER::QuadPart, and TRUE.
Referenced by ExpInitSystemPhase0().
VOID FASTCALL ExpWaitForResource (IN PERESOURCE Resource, IN PVOID Object)
Definition at line 2570 of file resource.c.
References DbgBreakPoint(), DbgPrint(), EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpBoostOwnerThread(), ExpTimeout, FALSE, Index, IsBoostAllowed, IsExclusiveWaiting, IsOwnedExclusive, IsSharedWaiting, KeGetCurrentThread(), KernelMode, KeWaitForSingleObject(), KiLockDispatcherDatabase, NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, _LARGE_INTEGER::QuadPart, Status, STATUS_TIMEOUT, _OWNER_ENTRY::TableSize, TRUE, _KTHREAD::WaitIrql, _KTHREAD::WaitNext, and WrResource.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), and ExAcquireSharedWaitForExclusive().
NTSTATUS ExQuerySystemLockInformation (__out_bcount(LockInformationLength) PRTL_PROCESS_LOCKS LockInformation, __in ULONG LockInformationLength, __out_opt PULONG ReturnLength)
Definition at line 2436 of file resource.c.
References _ERESOURCE::ActiveCount, _RTL_PROCESS_LOCK_INFORMATION::Address, ARGUMENT_PRESENT, _ETHREAD::Cid, CONTAINING_RECORD, _RTL_PROCESS_LOCK_INFORMATION::ContentionCount, _ERESOURCE::ContentionCount, _RTL_PROCESS_LOCK_INFORMATION::CreatorBackTraceIndex, _ERESOURCE::CreatorBackTraceIndex, ExpSystemResourcesList, FIELD_OFFSET, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _RTL_PROCESS_LOCK_INFORMATION::LockCount, _ERESOURCE::NumberOfExclusiveWaiters, _ERESOURCE::NumberOfSharedWaiters, _RTL_PROCESS_LOCK_INFORMATION::NumberOfWaitingExclusive, _RTL_PROCESS_LOCK_INFORMATION::NumberOfWaitingShared, _OWNER_ENTRY::OwnerThread, _ERESOURCE::OwnerThreads, _RTL_PROCESS_LOCK_INFORMATION::OwningThread, RTL_RESOURCE_TYPE, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _RTL_PROCESS_LOCK_INFORMATION::Type, and _CLIENT_ID::UniqueThread.
Referenced by ExpGetLockInformation().
NTSTATUS ExReinitializeResourceLite (__inout PERESOURCE Resource)
Definition at line 486 of file resource.c.
References ASSERT, FALSE, Index, KeInitializeEvent(), KeInitializeSemaphore(), MAXLONG, MmDeterminePoolType(), NonPagedPool, NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, STATUS_SUCCESS, SynchronizationEvent, and _OWNER_ENTRY::TableSize.
VOID FASTCALL ExReleaseResourceAndLeaveCriticalRegion (__inout PERESOURCE Resource)
Definition at line 1722 of file resource.c.
References ExReleaseResourceLite(), and KeLeaveCriticalRegion().
VOID ExReleaseResourceForThreadLite (__inout PERESOURCE Resource, __in ERESOURCE_THREAD CurrentThread)
Definition at line 1751 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, Index, IsExclusiveWaiting, IsOwnedExclusive, IsSharedWaiting, KeBugCheckEx(), KeGetCurrentThread(), KeReleaseSemaphore(), KeSetEventBoostPriority(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, RESOURCE_NOT_OWNED, ResourceOwnedExclusive, and _OWNER_ENTRY::TableSize.
Referenced by CcUnpinDataForThread().
VOID FASTCALL ExReleaseResourceLite (__inout PERESOURCE Resource)
Definition at line 1485 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EX_ENSURE_APCS_DISABLED, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, FALSE, Index, IsExclusiveWaiting, IsOwnedExclusive, IsSharedWaiting, KeBugCheckEx(), KeGetCurrentThread(), KeReleaseSemaphore(), KeSetEventBoostPriority(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), RESOURCE_NOT_OWNED, ResourceOwnedExclusive, and _OWNER_ENTRY::TableSize.
Referenced by CcUnpinFileDataEx(), CmpUnlockRegistry(), ExpGetSystemFirmwareTableInformation(), ExpRegisterFirmwareTableInformationHandler(), ExReleaseResourceAndLeaveCriticalRegion(), FsRtlAcquireFileForModWriteEx(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), FsRtlPrepareMdlWriteDev(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), FsRtlReleaseFileForModWrite(), IoEnumerateRegisteredFiltersList(), IopBootLog(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopGetSetSecurityObject(), IopInitializeBootLogging(), IopInvalidateVolumesForDevice(), IopLoadDriver(), IopMountVolume(), IopParseDevice(), IopSetDeviceSecurityDescriptor(), IoRegisterFileSystem(), IoRegisterFsRegistrationChange(), IoUnregisterFileSystem(), IoUnregisterFsRegistrationChange(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiProcessLoaderEntry(), MmExtendSection(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmInitSystem(), MmLockPageableDataSection(), NtAssignProcessToJobObject(), NtQueryInformationJobObject(), NtQuerySystemInformation(), NtSetInformationJobObject(), NtSetInformationProcess(), ObpUnlockAllObjects(), Ps386GetVdmIoHandler(), PsEnforceExecutionTimeLimits(), PsGetNextJobProcess(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspAddProcessToJob(), PspCreateThread(), PspExitProcess(), PspExitProcessFromJob(), PspJobClose(), PspJobDelete(), PspRemoveProcessFromJob(), PspSetQuotaLimits(), and PspTerminateAllProcessesInJob().
VOID ExSetResourceOwnerPointer (__inout PERESOURCE Resource, __in PVOID OwnerPointer)
Definition at line 1980 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpFindCurrentThread(), IsOwnedExclusive, KeBugCheckEx(), NULL, _OWNER_ENTRY::OwnerCount, _OWNER_ENTRY::OwnerThread, PsGetCurrentThread(), and RESOURCE_NOT_OWNED.
Referenced by CcSetBcbOwnerPointer().
BOOLEAN ExTryToAcquireResourceExclusiveLite (__inout PERESOURCE Resource)
Definition at line 790 of file resource.c.
References ASSERT, ASSERT_RESOURCE, EXP_LOCK_HANDLE, EXP_LOCK_RESOURCE, EXP_UNLOCK_RESOURCE, ExpIncrementCounter, FALSE, IsOwnedExclusive, KeIsExecutingDpc(), PsGetCurrentThread(), ResourceNeverExclusive, ResourceOwnedExclusive, and TRUE.
Variable Documentation
ALIGNED_SPINLOCK ExpResourceSpinLock
Definition at line 44 of file hifreqlk.c.
LIST_ENTRY ExpSystemResourcesList
Definition at line 224 of file resource.c.
Referenced by ExpCheckForResource(), and ExQuerySystemLockInformation().
LARGE_INTEGER ExpTimeout
Definition at line 206 of file resource.c.
Referenced by ExpWaitForResource().
ULONG ExResourceCheckFlags = EX_RESOURCE_CHECK_FREES|EX_RESOURCE_CHECK_ORPHANS
Definition at line 51 of file resource.c.
Referenced by ExpCheckForResource().
ULONG ExResourceTimeoutCount = 648000
Definition at line 212 of file resource.c.
LARGE_INTEGER ExShortTime = {(ULONG)(-10 * 1000 * 10), -1}
Definition at line 46 of file resource.c.