Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmwmi.c File Reference
cmwmi.c File Reference
#include "cmp.h"
#include <evntrace.h>
Functions
VOID CmpWmiDumpKcb (PCM_KEY_CONTROL_BLOCK kcb)
VOID CmpWmiDumpKcbTable (VOID)
NTSTATUS CmSetTraceNotifyRoutine (__in_opt PCM_TRACE_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
Variables
PCM_TRACE_NOTIFY_ROUTINE CmpTraceRoutine = NULL
Function Documentation
VOID CmpWmiDumpKcb (PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 118 of file cmwmi.c.
References CM_PAGED_CODE, CmpConstructName(), CmpTraceRoutine, ExFreePoolWithTag, KeyName, NULL, PROTECTED_POOL, and STATUS_SUCCESS.
VOID CmpWmiDumpKcbTable (VOID)
Definition at line 60 of file cmwmi.c.
References CM_PAGED_CODE, CmpCacheTable, CmpConstructName(), CmpHashTableSize, CmpLockHashEntryByIndexShared, CmpLockRegistry(), CmpTraceRoutine, CmpUnlockHashEntryByIndex, CmpUnlockRegistry(), CONTAINING_RECORD, _CM_KEY_HASH_TABLE_ENTRY::Entry, ExFreePoolWithTag, KeyName, _CM_KEY_HASH::NextHash, NULL, PROTECTED_POOL, and STATUS_SUCCESS.
Referenced by CmSetTraceNotifyRoutine().
NTSTATUS CmSetTraceNotifyRoutine (__in_opt PCM_TRACE_NOTIFY_ROUTINE NotifyRoutine, __in BOOLEAN Remove)
Definition at line 41 of file cmwmi.c.
References CmpTraceRoutine, CmpWmiDumpKcbTable(), NULL, and STATUS_SUCCESS.
Referenced by WmipDisableKernelTrace(), and WmipEnableKernelTrace().
Variable Documentation
PCM_TRACE_NOTIFY_ROUTINE CmpTraceRoutine = NULL
Definition at line 31 of file cmwmi.c.
Referenced by CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), and CmSetTraceNotifyRoutine().