Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/filtrctx.c File Reference
filtrctx.c File Reference
#include "FsRtlP.h"
Data Structures
struct _PER_FILEOBJECT_CTXCTRL
Macros
#define MySearchList(pHdr, Ptr) for (Ptr = (pHdr)->Flink; Ptr != (pHdr); Ptr = Ptr->Flink)
Typedefs
typedef struct _PER_FILEOBJECT_CTXCTRL PER_FILEOBJECT_CTXCTRL
typedef struct _PER_FILEOBJECT_CTXCTRL * PPER_FILEOBJECT_CTXCTRL
Functions
NTKERNELAPI NTSTATUS FsRtlInsertPerFileObjectContext (__in PFILE_OBJECT FileObject, __in PFSRTL_PER_FILEOBJECT_CONTEXT Ptr)
NTKERNELAPI NTSTATUS FsRtlInsertPerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader, __in PFSRTL_PER_STREAM_CONTEXT Ptr)
NTKERNELAPI LOGICAL FsRtlIsPagingFile (__in PFILE_OBJECT FileObject)
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlLookupPerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlLookupPerStreamContextInternal (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
VOID FsRtlPTeardownPerFileObjectContexts (__in PFILE_OBJECT FileObject)
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlRemovePerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlRemovePerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
NTKERNELAPI VOID FsRtlTeardownFilterContexts (IN PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader)
NTKERNELAPI VOID FsRtlTeardownPerStreamContexts (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader)
Macro Definition Documentation
#define MySearchList (pHdr, Ptr) for (Ptr = (pHdr)->Flink; Ptr != (pHdr); Ptr = Ptr->Flink)
Definition at line 44 of file filtrctx.c.
Referenced by FsRtlLookupPerFileObjectContext(), FsRtlLookupPerStreamContextInternal(), FsRtlRemovePerFileObjectContext(), and FsRtlRemovePerStreamContext().
Typedef Documentation
typedef struct _PER_FILEOBJECT_CTXCTRL PER_FILEOBJECT_CTXCTRL
typedef struct _PER_FILEOBJECT_CTXCTRL * PPER_FILEOBJECT_CTXCTRL
Function Documentation
NTKERNELAPI NTSTATUS FsRtlInsertPerFileObjectContext (__in PFILE_OBJECT FileObject, __in PFSRTL_PER_FILEOBJECT_CONTEXT Ptr)
Definition at line 404 of file filtrctx.c.
References ASSERT, ExAcquireFastMutex(), ExAllocatePoolWithTag, ExFreePool(), ExInitializeFastMutex, ExReleaseFastMutex(), _PER_FILEOBJECT_CTXCTRL::FastMutex, _PER_FILEOBJECT_CTXCTRL::FilterContexts, FsRtlSupportsPerFileObjectContexts, InitializeListHead(), InsertHeadList(), IoChangeFileObjectFilterContext(), IoGetFileObjectFilterContext(), NonPagedPool, NT_SUCCESS, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
NTKERNELAPI NTSTATUS FsRtlInsertPerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader, __in PFSRTL_PER_STREAM_CONTEXT Ptr)
Definition at line 73 of file filtrctx.c.
References ExAcquireFastMutex(), ExReleaseFastMutex(), FlagOn, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS, InsertHeadList(), STATUS_INVALID_DEVICE_REQUEST, and STATUS_SUCCESS.
NTKERNELAPI LOGICAL FsRtlIsPagingFile (__in PFILE_OBJECT FileObject)
Definition at line 776 of file filtrctx.c.
References MmIsFileObjectAPagingFile().
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlLookupPerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 517 of file filtrctx.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), _PER_FILEOBJECT_CTXCTRL::FastMutex, _PER_FILEOBJECT_CTXCTRL::FilterContexts, _LIST_ENTRY::Flink, _FSRTL_PER_FILEOBJECT_CONTEXT::InstanceId, IoGetFileObjectFilterContext(), IsListEmpty, MySearchList, NULL, and _FSRTL_PER_FILEOBJECT_CONTEXT::OwnerId.
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlLookupPerStreamContextInternal (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 119 of file filtrctx.c.
References ARGUMENT_PRESENT, ASSERT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FlagOn, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS, _FSRTL_PER_STREAM_CONTEXT::InstanceId, IsListEmpty, MySearchList, NULL, and _FSRTL_PER_STREAM_CONTEXT::OwnerId.
VOID FsRtlPTeardownPerFileObjectContexts (__in PFILE_OBJECT FileObject)
Definition at line 731 of file filtrctx.c.
References ASSERT, ExFreePool(), FALSE, _PER_FILEOBJECT_CTXCTRL::FilterContexts, IoChangeFileObjectFilterContext(), IoGetFileObjectFilterContext(), IsListEmpty, NULL, and STATUS_SUCCESS.
Referenced by IopDeleteFile().
NTKERNELAPI PFSRTL_PER_FILEOBJECT_CONTEXT FsRtlRemovePerFileObjectContext (__in PFILE_OBJECT FileObject, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 620 of file filtrctx.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), _PER_FILEOBJECT_CTXCTRL::FastMutex, _PER_FILEOBJECT_CTXCTRL::FilterContexts, _LIST_ENTRY::Flink, _FSRTL_PER_FILEOBJECT_CONTEXT::InstanceId, IoGetFileObjectFilterContext(), IsListEmpty, _FSRTL_PER_FILEOBJECT_CONTEXT::Links, MySearchList, NULL, _FSRTL_PER_FILEOBJECT_CONTEXT::OwnerId, and RemoveEntryList().
NTKERNELAPI PFSRTL_PER_STREAM_CONTEXT FsRtlRemovePerStreamContext (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader, __in_opt PVOID OwnerId, __in_opt PVOID InstanceId)
Definition at line 205 of file filtrctx.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FlagOn, FSRTL_FLAG2_SUPPORTS_FILTER_CONTEXTS, _FSRTL_PER_STREAM_CONTEXT::InstanceId, IsListEmpty, _FSRTL_PER_STREAM_CONTEXT::Links, MySearchList, NULL, _FSRTL_PER_STREAM_CONTEXT::OwnerId, and RemoveEntryList().
NTKERNELAPI VOID FsRtlTeardownFilterContexts (IN PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader)
NTKERNELAPI VOID FsRtlTeardownPerStreamContexts (__in PFSRTL_ADVANCED_FCB_HEADER AdvFcbHeader)
Definition at line 295 of file filtrctx.c.
References ASSERT, CONTAINING_RECORD, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, _FSRTL_PER_STREAM_CONTEXT::FreeCallback, IsListEmpty, RemoveHeadList(), and TRUE.