Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/wsmanage.c File Reference
wsmanage.c File Reference
#include "mi.h"
Data Structures
struct _MMWS_TRIM_CRITERIA
Macros
#define MI_AGE_ALL_WORKING_SETS 0x02
#define MI_CAPTURE_ALL_ACCESS_BITS 0x08
#define MI_CAPTURE_AND_RESET_ALL_ACCESS_BITS 0x10
#define MI_EMPTY_ALL_WORKING_SETS 0x04
#define MI_MAXIMUM_AGING_SHIFT 7
#define MI_MAXIMUM_SAMPLE 8192
#define MI_MINIMUM_SAMPLE 64
#define MI_MINIMUM_SAMPLE_SHIFT 7
#define MI_TRIM_ALL_WORKING_SETS 0x01
#define MI_WORKING_SET_FLAGS
#define MM_WS_REORG_BUCKETS_MAX 7
Typedefs
typedef struct _MMWS_TRIM_CRITERIA MMWS_TRIM_CRITERIA
typedef struct _MMWS_TRIM_CRITERIA * PMMWS_TRIM_CRITERIA
Functions
VOID MiAdjustClaimParameters (IN LOGICAL EnoughPages)
VOID MiAdjustWorkingSetManagerParameters (IN LOGICAL WorkStation)
VOID MiAgeWorkingSet (IN PMMSUPPORT VmSupport, IN LOGICAL DoAging, IN PWSLE_NUMBER WslesScanned, IN OUT PPFN_NUMBER TotalClaim, IN OUT PPFN_NUMBER TotalEstimatedAvailable)
LOGICAL MiAttachAndLockWorkingSet (IN PMMSUPPORT VmSupport)
VOID MiCaptureAndResetWorkingSetAccessBits (IN PMMSUPPORT WsInfo, IN ULONG Flags)
LOGICAL MiCheckSystemTrimEndCriteria (IN OUT PMMWS_TRIM_CRITERIA Criteria, IN KIRQL OldIrql)
LOGICAL MiCheckSystemTrimEndCriteria (IN PMMWS_TRIM_CRITERIA Criteria, IN KIRQL OldIrql)
ULONG MiComputeSystemTrimCriteria (IN OUT PMMWS_TRIM_CRITERIA Criteria)
ULONG MiComputeSystemTrimCriteria (IN PMMWS_TRIM_CRITERIA Criteria)
VOID MiDetachAndUnlockWorkingSet (IN PMMSUPPORT VmSupport)
WSLE_NUMBER MiDetermineTrimAmount (IN PMMWS_TRIM_CRITERIA Criteria, IN PMMSUPPORT VmSupport)
WSLE_NUMBER MiDetermineTrimAmount (PMMWS_TRIM_CRITERIA Criteria, PMMSUPPORT VmSupport)
VOID MiObtainFreePages (VOID)
VOID MiProcessWorkingSets (IN ULONG WorkingSetRequest, IN PMMWS_TRIM_CRITERIA TrimCriteria)
VOID MiQueueWorkingSetRequest (IN ULONG RequestFlags)
VOID MiRearrangeWorkingSetExpansionList (VOID)
LOGICAL MiTrimAllSystemPageableMemory (IN ULONG MemoryType, IN LOGICAL PurgeTransition)
VOID MmCaptureAllWorkingSetAccessBits (IN LOGICAL ResetAccessed)
VOID MmEmptyAllWorkingSets (VOID)
LOGICAL MmIsMemoryAvailable (IN PFN_NUMBER PagesDesired)
LOGICAL MmTrimAllSystemPageableMemory (__in LOGICAL PurgeTransition)
VOID MmWorkingSetManager (VOID)
Variables
ULONG MiActiveVerifies
ULONG MiAgingShift = 4
ULONG MiClaimAdjustmentThreshold [8] = { 0, 0, 4000, 8000, 12000, 24000, 32000, 32000}
ULONG MiEstimationShift = 5
LOGICAL MiHardTrim = FALSE
LARGE_INTEGER MiLastAdjustmentOfClaimParams
ULONG MiLastStandbyRePurposed
WSLE_NUMBER MiMaximumWslesPerSweep = (1024 * 1024 * 1024) / PAGE_SIZE
LOGICAL MiReplacing = FALSE
ULONG MiTrimAllPageFaultCount
LONG MiTrimInProgressCount = 1
KEVENT MiWorkingSetRequestEvent
ULONG MiWorkingSetRequestFlags
const LARGE_INTEGER MmClaimParameterAdjustDownTime = {2 * 1000 * 1000 * 10, 0}
const LARGE_INTEGER MmClaimParameterAdjustUpTime = {60 * 1000 * 1000 * 10, 0}
PFN_NUMBER MmPlentyFreePages = 400
PFN_NUMBER MmPlentyFreePagesValue
ULONG MmStandbyRePurposed
PFN_NUMBER MmTotalClaim = 0
PFN_NUMBER MmTotalEstimatedAvailable = 0
Macro Definition Documentation
#define MI_AGE_ALL_WORKING_SETS 0x02
Definition at line 58 of file wsmanage.c.
Referenced by MiComputeSystemTrimCriteria(), MiProcessWorkingSets(), and MiQueueWorkingSetRequest().
#define MI_CAPTURE_ALL_ACCESS_BITS 0x08
Definition at line 60 of file wsmanage.c.
Referenced by MiProcessWorkingSets(), and MmCaptureAllWorkingSetAccessBits().
#define MI_CAPTURE_AND_RESET_ALL_ACCESS_BITS 0x10
Definition at line 61 of file wsmanage.c.
Referenced by MiCaptureAndResetWorkingSetAccessBits(), MiProcessWorkingSets(), and MmCaptureAllWorkingSetAccessBits().
#define MI_EMPTY_ALL_WORKING_SETS 0x04
Definition at line 59 of file wsmanage.c.
Referenced by MiProcessWorkingSets(), MmEmptyAllWorkingSets(), and MmWorkingSetManager().
#define MI_MAXIMUM_AGING_SHIFT 7
Definition at line 83 of file wsmanage.c.
Referenced by MiAdjustClaimParameters().
#define MI_MAXIMUM_SAMPLE 8192
Definition at line 108 of file wsmanage.c.
Referenced by MiAgeWorkingSet().
#define MI_MINIMUM_SAMPLE 64
Definition at line 110 of file wsmanage.c.
Referenced by MiAgeWorkingSet().
#define MI_MINIMUM_SAMPLE_SHIFT 7
Definition at line 111 of file wsmanage.c.
Referenced by MiAgeWorkingSet().
#define MI_TRIM_ALL_WORKING_SETS 0x01
Definition at line 57 of file wsmanage.c.
Referenced by MiComputeSystemTrimCriteria(), MiProcessWorkingSets(), MiQueueWorkingSetRequest(), and MmWorkingSetManager().
#define MI_WORKING_SET_FLAGS
Value:
(MI_AGE_ALL_WORKING_SETS |                  \
         MI_TRIM_ALL_WORKING_SETS |                 \
         MI_EMPTY_ALL_WORKING_SETS |                \
         MI_CAPTURE_ALL_ACCESS_BITS |               \
         MI_CAPTURE_AND_RESET_ALL_ACCESS_BITS)
Definition at line 63 of file wsmanage.c.
Referenced by MiComputeSystemTrimCriteria(), MiProcessWorkingSets(), and MiQueueWorkingSetRequest().
#define MM_WS_REORG_BUCKETS_MAX 7
Definition at line 1934 of file wsmanage.c.
Referenced by MiRearrangeWorkingSetExpansionList().
Typedef Documentation
typedef struct _MMWS_TRIM_CRITERIA MMWS_TRIM_CRITERIA
typedef struct _MMWS_TRIM_CRITERIA * PMMWS_TRIM_CRITERIA
Function Documentation
VOID MiAdjustClaimParameters (IN LOGICAL EnoughPages)
Definition at line 1846 of file wsmanage.c.
References FALSE, KeQuerySystemTime(), MI_MAXIMUM_AGING_SHIFT, MiAgingShift, MiClaimAdjustmentThreshold, MiEstimationShift, MmAvailablePages, MmTotalClaim, _LARGE_INTEGER::QuadPart, and TRUE.
Referenced by MiCheckSystemTrimEndCriteria(), and MiProcessWorkingSets().
VOID MiAdjustWorkingSetManagerParameters (IN LOGICAL WorkStation)
Definition at line 167 of file wsmanage.c.
References KeInitializeEvent(), MiAgingShift, MiEstimationShift, MiWorkingSetRequestFlags, MmNumberOfPhysicalPages, MmPlentyFreePages, MmPlentyFreePagesValue, NotificationEvent, PAGE_SIZE, and TRUE.
Referenced by MmInitSystem().
VOID MiAgeWorkingSet (IN PMMSUPPORT VmSupport, IN LOGICAL DoAging, IN PWSLE_NUMBER WslesScanned, IN OUT PPFN_NUMBER TotalClaim, IN OUT PPFN_NUMBER TotalEstimatedAvailable)
Definition at line 1543 of file wsmanage.c.
References ASSERT, _MMWSLE::e1, FALSE, _MMWSL::FirstDynamic, _MMWSL::LastEntry, MEMORY_PRIORITY_FOREGROUND, MI_BACKGROUND_CLAIM_AVAILABLE_SHIFT, MI_CALC_NEXT_ESTIMATION_SLOT_CONST, MI_CALCULATE_USAGE_ESTIMATE, MI_CLAIM_INCR, MI_FOREGROUND_CLAIM_AVAILABLE_SHIFT, MI_GET_ACCESSED_IN_PTE, MI_INC_WSLE_AGE, MI_MAXIMUM_SAMPLE, MI_MINIMUM_SAMPLE, MI_MINIMUM_SAMPLE_SHIFT, MI_NEXT_VALID_AGING_SLOT, MI_NEXT_VALID_ESTIMATION_SLOT, MI_PTE_LOG_ACCESS(), MI_RESET_WSLE_AGE, MI_SET_ACCESSED_IN_PTE, MI_UPDATE_USE_ESTIMATE, MI_USE_AGE_COUNT, MiAgingShift, MiEstimationShift, MiGetPteAddress, MiMaximumWslesPerSweep, NULL, TRUE, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, and _MMWSL::Wsle.
Referenced by MiDoReplacement(), and MiProcessWorkingSets().
LOGICAL MiAttachAndLockWorkingSet (IN PMMSUPPORT VmSupport)
Definition at line 363 of file wsmanage.c.
References ASSERT, CONTAINING_RECORD, ExTryAcquirePushLockExclusive(), FALSE, _EPROCESS::Flags, KeDelayExecutionThread(), KeDetachProcess(), KeEnterGuardedRegionThread(), KeForceAttachProcess(), KeGetCurrentIrql(), KeLeaveGuardedRegionThread(), KernelMode, LOCK_WS_TIMESTAMP, MiAttachSession(), MiDetachSession(), MiSessionInSwapProcess(), MM_SYSTEM_WS_LOCK_TIMESTAMP, MM_WS_TRIMMING, MmShortTime, MmSystemCacheWs, _ETHREAD::OwnsProcessWorkingSetExclusive, _ETHREAD::OwnsSessionWorkingSetExclusive, _ETHREAD::OwnsSystemWorkingSetExclusive, PASSIVE_LEVEL, _EPROCESS::Pcb, PS_CLEAR_BITS, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_OUTSWAP_ENABLED, PS_PROCESS_FLAGS_OUTSWAPPED, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsInitialSystemProcess, _ETHREAD::Tcb, and TRUE.
Referenced by MiProcessWorkingSets().
VOID MiCaptureAndResetWorkingSetAccessBits (IN PMMSUPPORT WsInfo, IN ULONG Flags)
Definition at line 1430 of file wsmanage.c.
References _MMWSLE::e1, FALSE, _MMWSL::LastEntry, MI_CAPTURE_AND_RESET_ALL_ACCESS_BITS, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_PROCESS_TB, MI_FLUSH_SINGLE_TB, MI_GET_ACCESSED_IN_PTE, MI_PTE_LOG_ACCESS(), MI_RESET_WSLE_AGE, MI_SET_ACCESSED_IN_PTE, MiGetPteAddress, MM_MAXIMUM_FLUSH_COUNT, MmWsle, TRUE, _MMWSLE::u1, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, and _MMWSL::Wsle.
Referenced by MiProcessWorkingSets().
LOGICAL MiCheckSystemTrimEndCriteria (IN OUT PMMWS_TRIM_CRITERIA Criteria, IN KIRQL OldIrql)
Referenced by MiProcessWorkingSets().
LOGICAL MiCheckSystemTrimEndCriteria (IN PMMWS_TRIM_CRITERIA Criteria, IN KIRQL OldIrql)
Definition at line 866 of file wsmanage.c.
References FALSE, KeDelayExecutionThread(), KernelMode, LOCK_EXPANSION, MI_MAX_TRIM_PASSES, MiAdjustClaimParameters(), MmAvailablePages, MmShortTime, MmTotalClaim, MmTotalEstimatedAvailable, TRUE, and UNLOCK_EXPANSION.
ULONG MiComputeSystemTrimCriteria (IN OUT PMMWS_TRIM_CRITERIA Criteria)
Referenced by MmWorkingSetManager().
ULONG MiComputeSystemTrimCriteria (IN PMMWS_TRIM_CRITERIA Criteria)
Definition at line 680 of file wsmanage.c.
References ASSERT, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, FALSE, _KEVENT::Header, KePulseEvent(), LOCK_PFN, MI_AGE_ALL_WORKING_SETS, MI_TRIM_ALL_WORKING_SETS, MI_WORKING_SET_FLAGS, MiLastStandbyRePurposed, MiLowMemoryEvent, MiRearrangeWorkingSetExpansionList(), MiReplacing, MiWorkingSetRequestFlags, MM_DBG_WS_EXPANSION, MM_ENORMOUS_LIMIT, MmAvailablePages, MmPlentyFreePages, MmStandbyRePurposed, _DISPATCHER_HEADER::SignalState, TRUE, and UNLOCK_PFN.
VOID MiDetachAndUnlockWorkingSet (IN PMMSUPPORT VmSupport)
Definition at line 538 of file wsmanage.c.
References ASSERT, CONTAINING_RECORD, KeAreAllApcsDisabled(), KeDetachProcess(), KeGetCurrentIrql(), MiDetachSession(), MmSystemCacheWs, PASSIVE_LEVEL, PsGetCurrentThread(), PsInitialSystemProcess, TRUE, and UNLOCK_WORKING_SET.
Referenced by MiProcessWorkingSets().
WSLE_NUMBER MiDetermineTrimAmount (IN PMMWS_TRIM_CRITERIA Criteria, IN PMMSUPPORT VmSupport)
Referenced by MiProcessWorkingSets().
WSLE_NUMBER MiDetermineTrimAmount (PMMWS_TRIM_CRITERIA Criteria, PMMSUPPORT VmSupport)
Definition at line 1266 of file wsmanage.c.
References _MMSUPPORT::Claim, CONTAINING_RECORD, DbgPrintEx(), _MMWS_TRIM_CRITERIA::DoAging, DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, _MMSUPPORT::EstimatedAvailable, FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _EPROCESS::ImageFileName, MEMORY_PRIORITY_FOREGROUND, _MMSUPPORT_FLAGS::MemoryPriority, MI_BACKGROUND_CLAIM_AVAILABLE_SHIFT, MI_FOREGROUND_CLAIM_AVAILABLE_SHIFT, MI_PASS0_TRIM_AGE, MI_PASS1_TRIM_AGE, MI_PASS2_TRIM_AGE, MI_PASS3_TRIM_AGE, MI_PASS4_TRIM_AGE, MiHardTrim, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MM_DBG_WS_EXPANSION, MM_HIGH_LIMIT, MmAvailablePages, MmSystemCacheWs, _MMWS_TRIM_CRITERIA::NumPasses, PS_PROCESS_FLAGS_OUTSWAP_ENABLED, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionSpace, _MMWS_TRIM_CRITERIA::TrimAge, _MMSUPPORT_FLAGS::TrimHard, TRUE, _MMSUPPORT::VmWorkingSetList, and _MMSUPPORT::WorkingSetSize.
VOID MiObtainFreePages (VOID)
Definition at line 213 of file wsmanage.c.
References FALSE, KeSetEvent(), MmAvailablePages, MmModifiedPageListHead, MmModifiedPageWriterEvent, MmModifiedWriteClusterSize, MmPagesAboveWsMinimum, MmPagesAboveWsThreshold, MmWorkingSetManagerEvent, and _MMPFNLIST::Total.
Referenced by MiRemovePageByColor(), MiRemovePageFromList(), MiUnlinkFreeOrZeroedPage(), and MiUnlinkPageFromList().
VOID MiProcessWorkingSets (IN ULONG WorkingSetRequest, IN PMMWS_TRIM_CRITERIA TrimCriteria)
Definition at line 969 of file wsmanage.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, FALSE, _MMSUPPORT::Flags, _LIST_ENTRY::Flink, _MMSUPPORT_FLAGS::ForceTrim, InsertHeadList(), InsertTailList(), IsListEmpty, KeQuerySystemTime(), KeSetEvent(), _MMSUPPORT::LastTrimTime, _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, MI_AGE_ALL_WORKING_SETS, MI_CAPTURE_ALL_ACCESS_BITS, MI_CAPTURE_AND_RESET_ALL_ACCESS_BITS, MI_EMPTY_ALL_WORKING_SETS, MI_TRIM_ALL_WORKING_SETS, MI_WORKING_SET_FLAGS, MiAdjustClaimParameters(), MiAgeWorkingSet(), MiAttachAndLockWorkingSet(), MiCaptureAndResetWorkingSetAccessBits(), MiCheckSystemTrimEndCriteria(), MiDetachAndUnlockWorkingSet(), MiDetermineTrimAmount(), MiEmptyWorkingSet(), MiTrimWorkingSet(), MiWorkingSetRequestFlags, MM_PROCESS_COMMIT_CHARGE, MM_WS_NOT_LISTED, MM_WS_TRIMMING, MmSystemCacheWs, MmTotalClaim, MmTotalEstimatedAvailable, MmWorkingSetExpansionHead, NULL, _LARGE_INTEGER::QuadPart, RemoveHeadList(), _MMSUPPORT_FLAGS::SessionSpace, TRUE, UNLOCK_EXPANSION, _MMSUPPORT::WorkingSetExpansionLinks, and _MMSUPPORT::WorkingSetSize.
Referenced by MmWorkingSetManager().
VOID MiQueueWorkingSetRequest (IN ULONG RequestFlags)
Definition at line 2169 of file wsmanage.c.
References APC_LEVEL, ASSERT, FALSE, KeClearEvent(), KeGetCurrentIrql(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LOCK_EXPANSION, MI_AGE_ALL_WORKING_SETS, MI_TRIM_ALL_WORKING_SETS, MI_WORKING_SET_FLAGS, MiWorkingSetRequestFlags, MmWorkingSetManagerEvent, NULL, PsGetCurrentThread(), UNLOCK_EXPANSION, and WrVirtualMemory.
Referenced by MmCaptureAllWorkingSetAccessBits(), and MmEmptyAllWorkingSets().
VOID MiRearrangeWorkingSetExpansionList (VOID)
Definition at line 1941 of file wsmanage.c.
References _LIST_ENTRY::Blink, _MMSUPPORT::Claim, CONTAINING_RECORD, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, _MMSUPPORT::Flags, _LIST_ENTRY::Flink, InitializeListHead(), InsertHeadList(), IsListEmpty, KeQuerySystemTime(), _MM_SESSION_SPACE::LastProcessSwappedOutTime, _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, MEMORY_PRIORITY_FOREGROUND, _MMSUPPORT_FLAGS::MemoryPriority, MM_DBG_SESSIONS, MM_DBG_WS_EXPANSION, MM_WS_REORG_BUCKETS_MAX, MmWorkingSetExpansionHead, _LARGE_INTEGER::QuadPart, _MM_SESSION_SPACE::ReferenceCount, RemoveHeadList(), _MM_SESSION_SPACE::ResidentProcessCount, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionSpace, _MMSUPPORT_FLAGS::TrimHard, UNLOCK_EXPANSION, _MMSUPPORT::WorkingSetExpansionLinks, and _MMSUPPORT::WorkingSetSize.
Referenced by MiComputeSystemTrimCriteria().
LOGICAL MiTrimAllSystemPageableMemory (IN ULONG MemoryType, IN LOGICAL PurgeTransition)
Definition at line 2391 of file wsmanage.c.
References APC_LEVEL, ASSERT, _LIST_ENTRY::Blink, EFLAGS_IF_MASK, EFLAGS_INTERRUPT_MASK, ExTryAcquirePushLockExclusive(), FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _LIST_ENTRY::Flink, InsertTailList(), InterlockedDecrement, InterlockedIncrement, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeLeaveGuardedRegionThread(), KeSetEvent(), KeTryToAcquireSpinLock(), _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, LOCK_WS_TIMESTAMP, MI_IS_WS_UNSAFE, MI_SESSION_LOCAL, MI_SYSTEM_GLOBAL, MI_USER_LOCAL, MiEmptyWorkingSet(), MiPurgeTransitionList(), MiTrimAllPageFaultCount, MiTrimInProgressCount, MM_SET_EXPANSION_OWNER, MM_SYSTEM_WS_LOCK_TIMESTAMP, MM_WS_NOT_LISTED, MM_WS_SWAPPED_OUT, MM_WS_TRIMMING, MmExpansionLock, MmSessionSpace, MmSystemCacheWs, MmWorkingSetExpansionHead, NULL, _ETHREAD::OwnsProcessWorkingSetExclusive, _ETHREAD::OwnsSessionWorkingSetExclusive, _ETHREAD::OwnsSystemWorkingSetExclusive, _MMSUPPORT::PageFaultCount, _KTHREAD::Priority, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), RemoveEntryList(), SESSION_GLOBAL, _MMSUPPORT_FLAGS::SessionLeader, Status, _ETHREAD::Tcb, TRUE, UNLOCK_EXPANSION, UNLOCK_WORKING_SET, UNLOCK_WS, _EPROCESS::Vm, _MM_SESSION_SPACE::Vm, _MMSUPPORT::WorkingSetExpansionLinks, _MMSUPPORT::WorkingSetMutex, and _MMSUPPORT::WorkingSetSize.
Referenced by MmTrimAllSystemPageableMemory().
VOID MmCaptureAllWorkingSetAccessBits (IN LOGICAL ResetAccessed)
Definition at line 2271 of file wsmanage.c.
References MI_CAPTURE_ALL_ACCESS_BITS, MI_CAPTURE_AND_RESET_ALL_ACCESS_BITS, MiQueueWorkingSetRequest(), and TRUE.
VOID MmEmptyAllWorkingSets (VOID)
Definition at line 2236 of file wsmanage.c.
References MI_EMPTY_ALL_WORKING_SETS, MiFullyInitialized, and MiQueueWorkingSetRequest().
Referenced by MiAllocateLargeZeroPages(), MiFindContiguousPages(), MmGatherMemoryForHibernate(), PerfInfoStartLog(), and WmiSetMark().
LOGICAL MmIsMemoryAvailable (IN PFN_NUMBER PagesDesired)
Definition at line 273 of file wsmanage.c.
References ASSERT, FALSE, KeDelayExecutionThread(), KeGetCurrentIrql(), KernelMode, KeSetEvent(), MiHardTrim, Mm30Milliseconds, MmAvailablePages, MmPlentyFreePages, MmPlentyFreePagesValue, MmTotalClaim, MmWorkingSetManagerEvent, PASSIVE_LEVEL, Status, and TRUE.
LOGICAL MmTrimAllSystemPageableMemory (__in LOGICAL PurgeTransition)
Definition at line 2317 of file wsmanage.c.
References MI_SYSTEM_GLOBAL, and MiTrimAllSystemPageableMemory().
Referenced by MmShutdownSystem().
VOID MmWorkingSetManager (VOID)
Definition at line 595 of file wsmanage.c.
References ASSERT, FALSE, Initialized, KeSetEvent(), _ETHREAD::MemoryMaker, MI_EMPTY_ALL_WORKING_SETS, MI_TRIM_ALL_WORKING_SETS, MiComputeSystemTrimCriteria(), MiDeferredUnlockPages(), MiProcessWorkingSets(), MmIsAddressValid(), MmModifiedPageListHead, MmModifiedPageMaximum, MmModifiedPageWriterEvent, MmSessionSpace, PsGetCurrentThread(), and _MMPFNLIST::Total.
Referenced by KeBalanceSetManager().
Variable Documentation
ULONG MiActiveVerifies
ULONG MiAgingShift = 4
Definition at line 85 of file wsmanage.c.
Referenced by MiAdjustClaimParameters(), MiAdjustWorkingSetManagerParameters(), and MiAgeWorkingSet().
ULONG MiClaimAdjustmentThreshold[8] = { 0, 0, 4000, 8000, 12000, 24000, 32000, 32000}
Definition at line 1843 of file wsmanage.c.
Referenced by MiAdjustClaimParameters().
ULONG MiEstimationShift = 5
Definition at line 86 of file wsmanage.c.
Referenced by MiAdjustClaimParameters(), MiAdjustWorkingSetManagerParameters(), and MiAgeWorkingSet().
LOGICAL MiHardTrim = FALSE
Definition at line 104 of file wsmanage.c.
Referenced by MiDetermineTrimAmount(), and MmIsMemoryAvailable().
LARGE_INTEGER MiLastAdjustmentOfClaimParams
Definition at line 90 of file wsmanage.c.
ULONG MiLastStandbyRePurposed
Definition at line 75 of file wsmanage.c.
Referenced by MiComputeSystemTrimCriteria().
WSLE_NUMBER MiMaximumWslesPerSweep = (1024 * 1024 * 1024) / PAGE_SIZE
Definition at line 106 of file wsmanage.c.
Referenced by MiAgeWorkingSet().
LOGICAL MiReplacing = FALSE
Definition at line 72 of file wsmanage.c.
Referenced by MiComputeSystemTrimCriteria(), and MiDoReplacement().
ULONG MiTrimAllPageFaultCount
Definition at line 2313 of file wsmanage.c.
Referenced by MiTrimAllSystemPageableMemory().
LONG MiTrimInProgressCount = 1
Definition at line 2311 of file wsmanage.c.
Referenced by MiTrimAllSystemPageableMemory(), and MmInitSystem().
KEVENT MiWorkingSetRequestEvent
Definition at line 55 of file wsmanage.c.
ULONG MiWorkingSetRequestFlags
Definition at line 70 of file wsmanage.c.
Referenced by MiAdjustWorkingSetManagerParameters(), MiComputeSystemTrimCriteria(), MiProcessWorkingSets(), and MiQueueWorkingSetRequest().
const LARGE_INTEGER MmClaimParameterAdjustDownTime = {2 * 1000 * 1000 * 10, 0}
Definition at line 102 of file wsmanage.c.
const LARGE_INTEGER MmClaimParameterAdjustUpTime = {60 * 1000 * 1000 * 10, 0}
Definition at line 96 of file wsmanage.c.
PFN_NUMBER MmPlentyFreePages = 400
Definition at line 79 of file wsmanage.c.
Referenced by MiAdjustWorkingSetManagerParameters(), MiComputeSystemTrimCriteria(), MiInitializeMemoryEvents(), and MmIsMemoryAvailable().
PFN_NUMBER MmPlentyFreePagesValue
Definition at line 81 of file wsmanage.c.
Referenced by MiAdjustWorkingSetManagerParameters(), and MmIsMemoryAvailable().
ULONG MmStandbyRePurposed
Definition at line 58 of file pfnlist.c.
Referenced by MiComputeSystemTrimCriteria(), MiRemoveAnyPage(), and MiRemoveZeroPage().
PFN_NUMBER MmTotalClaim = 0
Definition at line 87 of file wsmanage.c.
Referenced by MiAdjustClaimParameters(), MiCheckSystemTrimEndCriteria(), MiProcessWorkingSets(), and MmIsMemoryAvailable().
PFN_NUMBER MmTotalEstimatedAvailable = 0
Definition at line 88 of file wsmanage.c.
Referenced by MiCheckSystemTrimEndCriteria(), and MiProcessWorkingSets().