Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmclose.c File Reference
cmclose.c File Reference
#include "cmp.h"
Functions
VOID CmpCloseKeyObject (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID CmpDelayedDerefKeys (PLIST_ENTRY DelayedDeref)
Function Documentation
VOID CmpCloseKeyObject (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 31 of file cmclose.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_POOL, CmLockHive, CmpDelayedDerefKeys(), CmpLockRegistry(), CmpPostNotify(), CmpUnlockRegistry(), CmUnlockHive, DBG, DPFLTR_CONFIG_ID, FALSE, InitializeListHead(), IsListEmpty, KEY_BODY_TYPE, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_BODY::NotifyBlock, NULL, _CM_NOTIFY_BLOCK::PostList, STATUS_NOTIFY_CLEANUP, _CM_KEY_BODY::Type, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateObjectTypes().
VOID CmpDelayedDerefKeys (PLIST_ENTRY DelayedDeref)
Definition at line 1885 of file cmnotify.c.
References ASSERT, CM_PAGED_CODE, CONTAINING_RECORD, ExFreePool(), FALSE, IsListEmpty, KEY_BODY_TYPE, _CM_POST_KEY_BODY::KeyBody, NULL, ObDereferenceObjectDeferDelete(), RemoveHeadList(), and _CM_KEY_BODY::Type.
Referenced by CmpCloseKeyObject(), CmpPostNotify(), and CmpReportNotifyHelper().