Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/eventpr.c File Reference
eventpr.c File Reference
#include "exp.h"
Functions
BOOLEAN ExpEventPairInitialization (VOID)
NTSTATUS NtCreateEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtOpenEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtSetHighEventPair (__in HANDLE EventPairHandle)
NTSTATUS NtSetHighWaitLowEventPair (__in HANDLE EventPairHandle)
NTSTATUS NtSetLowEventPair (__in HANDLE EventPairHandle)
NTSTATUS NtSetLowWaitHighEventPair (__in HANDLE EventPairHandle)
NTSTATUS NtWaitHighEventPair (__in HANDLE EventPairHandle)
NTSTATUS NtWaitLowEventPair (__in HANDLE EventPairHandle)
Variables
POBJECT_TYPE ExEventPairObjectType
const GENERIC_MAPPING ExpEventPairMapping
Function Documentation
BOOLEAN ExpEventPairInitialization (VOID)
Definition at line 60 of file eventpr.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, EVENT_PAIR_ALL_ACCESS, ExpEventPairMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, Status, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
NTSTATUS NtCreateEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 121 of file eventpr.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KeInitializeEventPair(), _EEVENT_PAIR::KernelEventPair, KernelMode, NOTHING, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, and Status.
NTSTATUS NtOpenEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 233 of file eventpr.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSTATUS NtSetHighEventPair (__in HANDLE EventPairHandle)
Definition at line 621 of file eventpr.c.
References EVENT_PAIR_INCREMENT, FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetHighEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSTATUS NtSetHighWaitLowEventPair (__in HANDLE EventPairHandle)
Definition at line 504 of file eventpr.c.
References KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetHighWaitLowEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSTATUS NtSetLowEventPair (__in HANDLE EventPairHandle)
Definition at line 563 of file eventpr.c.
References EVENT_PAIR_INCREMENT, FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetLowEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSTATUS NtSetLowWaitHighEventPair (__in HANDLE EventPairHandle)
Definition at line 445 of file eventpr.c.
References KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetLowWaitHighEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSTATUS NtWaitHighEventPair (__in HANDLE EventPairHandle)
Definition at line 385 of file eventpr.c.
References FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeWaitForHighEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSTATUS NtWaitLowEventPair (__in HANDLE EventPairHandle)
Definition at line 325 of file eventpr.c.
References FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeWaitForLowEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
Variable Documentation
POBJECT_TYPE ExEventPairObjectType
Definition at line 27 of file eventpr.c.
const GENERIC_MAPPING ExpEventPairMapping
Initial value:
= {
    STANDARD_RIGHTS_READ | SYNCHRONIZE,
    STANDARD_RIGHTS_WRITE | SYNCHRONIZE,
    STANDARD_RIGHTS_EXECUTE | SYNCHRONIZE,
    EVENT_PAIR_ALL_ACCESS
}
Definition at line 38 of file eventpr.c.
Referenced by ExpEventPairInitialization().