Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/i386/getcalr.c File Reference
getcalr.c File Reference
#include <ntos.h>
#include <ntrtl.h>
#include "ntrtlp.h"
#include <nturtl.h>
#include <zwapi.h>
#include <stktrace.h>
Macros
#define PAGE_START(address) (((ULONG_PTR)address) & ~((ULONG_PTR)PAGE_SIZE - 1))
#define ROUND_DOWN(a, b) ((ULONG_PTR)(a) & ~((ULONG_PTR)(b) - 1))
#define ROUND_UP(a, b) (((ULONG_PTR)(a) + ((ULONG_PTR)(b) - 1)) & ~((ULONG_PTR)(b) - 1))
#define SIZE_1_GB ((ULONG_PTR) 0x40000000)
#define SIZE_1_KB ((ULONG_PTR) 0x400)
#define SIZE_1_MB 0x100000
Functions
BOOLEAN NtdllOkayToLockRoutine (IN PVOID Lock)
USHORT RtlCaptureStackBackTrace (IN ULONG FramesToSkip, IN ULONG FramesToCapture, OUT PVOID *BackTrace, OUT PULONG BackTraceHash)
ULONG RtlCaptureStackContext (OUT PULONG_PTR Callers, OUT PRTL_STACK_CONTEXT Context, IN ULONG Limit)
VOID RtlpCaptureContext (OUT PCONTEXT ContextRecord)
BOOLEAN RtlpCaptureStackLimits (ULONG_PTR HintAddress, PULONG_PTR StartStack, PULONG_PTR EndStack)
BOOLEAN RtlpStkIsPointerInDllRange (ULONG_PTR Value)
BOOLEAN RtlpStkIsPointerInNtdllRange (ULONG_PTR Value)
VOID RtlpStkMarkDllRange (PLDR_DATA_TABLE_ENTRY DllEntry)
ULONG RtlpWalkFrameChainExceptionFilter (ULONG ExceptionCode, PVOID ExceptionRecord)
ULONG RtlpWalkFrameChainFuzzy (OUT PVOID *Callers, IN ULONG Count)
ULONG RtlWalkFrameChain (OUT PVOID *Callers, IN ULONG Count, IN ULONG Flags)
Variables
UCHAR RtlpStkDllRanges [2048/8]
Macro Definition Documentation
#define PAGE_START (address) (((ULONG_PTR)address) & ~((ULONG_PTR)PAGE_SIZE - 1))
Definition at line 191 of file getcalr.c.
#define ROUND_DOWN (a, b) ((ULONG_PTR)(a) & ~((ULONG_PTR)(b) - 1))
Definition at line 619 of file getcalr.c.
Referenced by RtlpStkMarkDllRange().
#define ROUND_UP (a, b) (((ULONG_PTR)(a) + ((ULONG_PTR)(b) - 1)) & ~((ULONG_PTR)(b) - 1))
Definition at line 620 of file getcalr.c.
Referenced by RtlpStkMarkDllRange().
#define SIZE_1_GB ((ULONG_PTR) 0x40000000)
Definition at line 189 of file getcalr.c.
#define SIZE_1_KB ((ULONG_PTR) 0x400)
Definition at line 188 of file getcalr.c.
#define SIZE_1_MB 0x100000
Definition at line 609 of file getcalr.c.
Referenced by RtlpStkMarkDllRange().
Function Documentation
BOOLEAN NtdllOkayToLockRoutine (IN PVOID Lock)
USHORT RtlCaptureStackBackTrace (IN ULONG FramesToSkip, IN ULONG FramesToCapture, OUT PVOID * BackTrace, OUT PULONG BackTraceHash)
Definition at line 80 of file getcalr.c.
References Count, Index, MAX_STACK_DEPTH, NULL, PtrToUlong, and RtlWalkFrameChain().
Referenced by ExFreePoolWithTag(), MiCheckCacheAttributes(), MiInsertIoSpaceMap(), and RtlpCaptureStackTraceForLogging().
ULONG RtlCaptureStackContext (OUT PULONG_PTR Callers, OUT PRTL_STACK_CONTEXT Context, IN ULONG Limit)
Definition at line 388 of file getcalr.c.
References DISPATCH_LEVEL, Index, KeGetCurrentIrql(), RtlpCaptureStackLimits(), and RtlpStkIsPointerInDllRange().
VOID RtlpCaptureContext (OUT PCONTEXT ContextRecord)
Referenced by RtlUnwind().
BOOLEAN RtlpCaptureStackLimits (ULONG_PTR HintAddress, PULONG_PTR StartStack, PULONG_PTR EndStack)
Definition at line 680 of file getcalr.c.
References DISPATCH_LEVEL, _KPRCB::DpcStack, FALSE, KeGetCurrentIrql(), KeGetCurrentThread(), KeGetPcr(), KERNEL_STACK_SIZE, PAGE_SIZE, _KPCR::Prcb, _KTHREAD::StackBase, _KTHREAD::StackLimit, and TRUE.
Referenced by RtlCaptureStackContext(), and RtlWalkFrameChain().
BOOLEAN RtlpStkIsPointerInDllRange (ULONG_PTR Value)
Definition at line 590 of file getcalr.c.
References FALSE, Index, RtlpStkDllRanges, and TRUE.
Referenced by RtlCaptureStackContext().
BOOLEAN RtlpStkIsPointerInNtdllRange (ULONG_PTR Value)
VOID RtlpStkMarkDllRange (PLDR_DATA_TABLE_ENTRY DllEntry)
Definition at line 623 of file getcalr.c.
References _LDR_DATA_TABLE_ENTRY::DllBase, Index, ROUND_DOWN, ROUND_UP, RtlpStkDllRanges, SIZE_1_MB, and _LDR_DATA_TABLE_ENTRY::SizeOfImage.
ULONG RtlpWalkFrameChainExceptionFilter (ULONG ExceptionCode, PVOID ExceptionRecord)
Definition at line 922 of file stktrace.c.
References DbgBreakPoint(), DbgPrint(), EXCEPTION_EXECUTE_HANDLER, and STATUS_IN_PAGE_ERROR.
Referenced by RtlWalkFrameChain().
ULONG RtlpWalkFrameChainFuzzy (OUT PVOID * Callers, IN ULONG Count)
ULONG RtlWalkFrameChain (OUT PVOID * Callers, IN ULONG Count, IN ULONG Flags)
Definition at line 198 of file getcalr.c.
References Count, DISPATCH_LEVEL, except, FALSE, Index, IS_SYSTEM_ADDRESS, KeGetCurrentIrql(), KeGetCurrentThread(), KeIsAttachedProcess(), NULL, ProbeForRead, RtlpCaptureStackLimits(), RtlpWalkFrameChainExceptionFilter(), _KTHREAD::StackBase, _KTHREAD::Teb, _KTHREAD::TrapFrame, and TRUE.
Referenced by ExpUpdateDebugInfo(), RtlCaptureStackBackTrace(), RtlpCaptureStackTraceForLogging(), SepCreateToken(), SepDuplicateToken(), and SepFilterToken().
Variable Documentation
UCHAR RtlpStkDllRanges[2048/8]
Definition at line 587 of file getcalr.c.
Referenced by RtlpStkIsPointerInDllRange(), and RtlpStkMarkDllRange().