Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/kernlini.c File Reference
kernlini.c File Reference
#include "ki.h"
#include "fastsys.inc"
Macros
#define CCR1 0xc1
#define CPUID_REG_COUNT 4
#define CRC_DAT (CRC_NDX + 1)
#define CRC_NDX (PUCHAR)0x22
#define IDT_SKIP (7 * sizeof (KIDTENTRY))
#define MAX_ATTEMPTS 10
#define RET 0xc3
#define TRAP332_GATE 0xEF00
#define XMMI_ZEROING_ALLOW_OVERRIDE 1
#define XMMI_ZEROING_DISALLOW_OVERRIDE 2
Enumerations
enum CPU_VENDORS {
CPU_NONE, CPU_INTEL, CPU_AMD, CPU_CYRIX,
CPU_TRANSMETA, CPU_CENTAUR, CPU_RISE, CPU_UNKNOWN
}
Functions
VOID KeOptimizeProcessorControlState (VOID)
VOID KeSetup80387OrEmulate (IN PVOID *R3EmulatorTable)
VOID Ki386EnableDE (IN volatile PLONG Number)
VOID Ki386EnableFxsr (IN volatile PLONG Number)
VOID Ki386EnableGlobalPage (IN volatile PLONG Number)
VOID Ki386EnableXMMIExceptions (IN volatile PLONG Number)
VOID KiAmdK6InitializeMTRR (VOID)
VOID KiChainedDispatch2ndLvl (VOID)
VOID KiGetCacheInformation (VOID)
ULONG KiGetCpuVendor (VOID)
ULONG KiGetFeatureBits (VOID)
VOID KiGetInterruptDispatchPatchAddresses (PULONG_PTR Address1, PULONG_PTR Address2)
VOID KiI386PentiumLockErrataFixup (VOID)
VOID KiInitializeDblFaultTSS (IN PKTSS Tss, IN ULONG Stack, IN PKGDTENTRY TssDescriptor)
VOID KiInitializeKernel (IN PKPROCESS Process, IN PKTHREAD Thread, IN PVOID IdleStack, IN PKPRCB Prcb, IN CCHAR Number, PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID KiInitializeMTRR (IN BOOLEAN LastProcessor)
VOID KiInitializePAT (VOID)
VOID KiInitializePcr (IN ULONG Processor, IN PKPCR Pcr, IN PKIDTENTRY Idt, IN PKGDTENTRY Gdt, IN PKTSS Tss, IN PKTHREAD Thread, IN PVOID DpcStack)
VOID KiInitializeTSS (IN PKTSS Tss)
VOID KiInitializeTSS2 (IN PKTSS Tss, IN PKGDTENTRY TssDescriptor)
BOOLEAN KiInitMachineDependent (VOID)
BOOLEAN KiIsNpxPresent (VOID)
VOID KiLockStepOtherProcessors (PULONG Proceed)
VOID KiLockStepProcessor (PKIPI_CONTEXT SignalDone, IN PVOID Arg1, IN PVOID Arg2, IN PVOID Proceed)
NTSTATUS KiMoveRegTree (HANDLE Source, HANDLE Dest)
VOID KiRestoreFastSyscallReturnState (VOID)
VOID KiSetCR0Bits (VOID)
VOID KiSetProcessorType (VOID)
VOID KiSwapIDT (VOID)
VOID FASTCALL KiTimedChainedDispatch2ndLvl (PVOID)
VOID FASTCALL KiTimedInterruptDispatch (PVOID)
VOID KiUnlockStepOtherProcessors (PULONG Proceed)
VOID FASTCALL KiXMMIZeroPages (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
VOID FASTCALL KiXMMIZeroPagesNoSave (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
VOID FASTCALL KiZeroPages (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
VOID FASTCALL RtlPrefetchMemoryNonTemporal (PVOID Memory, SIZE_T Length)
Variables
WCHAR CmDisabledFloatingPointProcessor []
CHAR CmpAmdID []
CHAR CmpCentaurID []
CHAR CmpCyrixID []
CHAR CmpIntelID []
CHAR CmpRiseID []
CHAR CmpTransmetaID []
KIDTENTRY IDT []
ULONG KeI386ForceNpxEmulation
BOOLEAN KeI386XMMIPresent
ULONG KePrefetchNTAGranularity = 32
KE_ZERO_PAGE_ROUTINE KeZeroPages = KiZeroPages
KE_ZERO_PAGE_ROUTINE KeZeroPagesFromIdleThread = KiZeroPages
PVOID Ki386IopmSaveArea
PVOID Ki387RoundModeTable
ULONG Ki486CompatibilityLock
ULONG KiFastSystemCallDisable
BOOLEAN KiFastSystemCallIsIA32
BOOLEAN KiI386PentiumLockErrataPresent = FALSE
BOOLEAN KiIgnoreUnexpectedTrap07 = FALSE
BOOLEAN KiSMTProcessorsPresent
ULONG KiTimeLimitIsrMicroseconds
ULONG KiXMMIZeroingEnable
PVOID ScPatchFxb
PVOID ScPatchFxe
Macro Definition Documentation
#define CCR1 0xc1
Referenced by KiGetFeatureBits().
#define CPUID_REG_COUNT 4
Referenced by KiGetCacheInformation().
#define CRC_DAT (CRC_NDX + 1)
Referenced by KiGetFeatureBits().
#define CRC_NDX (PUCHAR)0x22
Referenced by KiGetFeatureBits().
#define IDT_SKIP (7 * sizeof (KIDTENTRY))
Referenced by KiI386PentiumLockErrataFixup().
#define MAX_ATTEMPTS 10
Definition at line 2209 of file kernlini.c.
Referenced by KiInitMachineDependent().
#define RET 0xc3
Referenced by KiInitializeKernel().
#define TRAP332_GATE 0xEF00
Definition at line 28 of file kernlini.c.
Referenced by KeSetup80387OrEmulate().
#define XMMI_ZEROING_ALLOW_OVERRIDE 1
#define XMMI_ZEROING_DISALLOW_OVERRIDE 2
Enumeration Type Documentation
enum CPU_VENDORS
Enumerator
CPU_NONE
CPU_INTEL
CPU_AMD
CPU_CYRIX
CPU_TRANSMETA
CPU_CENTAUR
CPU_RISE
CPU_UNKNOWN
Definition at line 198 of file kernlini.c.
Function Documentation
VOID KeOptimizeProcessorControlState (VOID)
Definition at line 2891 of file kernlini.c.
References Ke386ConfigureCyrixProcessor().
Referenced by CmpConfigureProcessors().
VOID KeSetup80387OrEmulate (IN PVOID * R3EmulatorTable)
Definition at line 2899 of file kernlini.c.
References _KIDTENTRY::Access, CmDisabledFloatingPointProcessor, CmRegistryMachineHardwareDescriptionSystemName, CmTypeName, FloatingPointProcessor, I386_80387_NP_VECTOR, _KPCR::IDT, InitializeObjectAttributes, KeActiveProcessors, KeGetPcr(), KeI386NpxPresent, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KEY_ALL_ACCESS, KGDT_R3_CODE, Ki387RoundModeTable, KiLockDispatcherDatabase, KiMoveRegTree(), KiSetHandlerAddressToIDT, KiUnlockDispatcherDatabase(), NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, REG_OPTION_VOLATILE, RtlInitUnicodeString(), _KIDTENTRY::Selector, Status, TRAP332_GATE, ZwClose(), ZwCreateKey(), and ZwOpenKey().
VOID Ki386EnableDE (IN volatile PLONG Number)
VOID Ki386EnableFxsr (IN volatile PLONG Number)
VOID Ki386EnableGlobalPage (IN volatile PLONG Number)
Referenced by KiInitMachineDependent().
VOID Ki386EnableXMMIExceptions (IN volatile PLONG Number)
VOID KiAmdK6InitializeMTRR (VOID)
Definition at line 175 of file mtrramd.c.
References AMDK6_MTRR_MSR, AMDK6_MTRR_TYPE_DISABLED, AMDK6_REGION_UNUSED, AmdK6RegionCount, AmdMtrrHwUsageCount, _AMDK6_MTRR_REGION::BaseAddress, DBGMSG, _AMDK6_MTRR_MSR_IMAGE::hw, KeAcquireSpinLock, KeInitializeSpinLock(), KeReleaseSpinLock(), KiAmdK6MTRRAddRegionFromHW(), KiRangeLock, MAX_K6_REGIONS, _AMDK6_MTRR_MSR_IMAGE::QuadPart, RDMSR(), _AMDK6_MTRR_REGION::RegionFlags, and _AMDK6_MTRR_MSR_IMAGE::u.
Referenced by KiInitMachineDependent().
VOID KiChainedDispatch2ndLvl (VOID)
Referenced by KiInitMachineDependent().
VOID KiGetCacheInformation (VOID)
Definition at line 1828 of file kernlini.c.
References CPU_AMD, CPU_INTEL, CPU_NONE, CPUID(), CPUID_REG_COUNT, _KPRCB::CpuStep, _KPRCB::CpuType, FALSE, KeGetPcr(), KeLargestCacheLine, KePrefetchNTAGranularity, KiGetCpuVendor(), _KPCR::PrcbData, _KPCR::SecondLevelCacheAssociativity, _KPCR::SecondLevelCacheSize, and TRUE.
Referenced by KiInitializeKernel().
ULONG KiGetCpuVendor (VOID)
Definition at line 1271 of file kernlini.c.
References CmpAmdID, CmpCentaurID, CmpCyrixID, CmpIntelID, CmpRiseID, CmpTransmetaID, CPU_AMD, CPU_CENTAUR, CPU_CYRIX, CPU_INTEL, CPU_NONE, CPU_RISE, CPU_TRANSMETA, CPU_UNKNOWN, _KPRCB::CpuID, CPUID(), KeGetCurrentPrcb(), RtlCopyMemory, strcmp(), and _KPRCB::VendorString.
Referenced by KiGetCacheInformation(), and KiGetFeatureBits().
ULONG KiGetFeatureBits (VOID)
Definition at line 1342 of file kernlini.c.
References CCR1, CPU_AMD, CPU_CENTAUR, CPU_CYRIX, CPU_INTEL, CPU_NONE, CPU_RISE, CPU_TRANSMETA, CPUID(), _KPRCB::CpuStep, _KPRCB::CpuType, CRC_DAT, CRC_NDX, FALSE, _KPRCB::InitialApicId, KeGetCurrentPrcb(), KF_3DNOW, KF_AMDK6MTRR, KF_CMOV, KF_CMPXCHG8B, KF_CR4, KF_DTS, KF_FAST_SYSCALL, KF_FXSR, KF_GLOBAL_PAGE, KF_LARGE_PAGE, KF_MMX, KF_MTRR, KF_NOEXECUTE, KF_PAT, KF_RDTSC, KF_V86_VIS, KF_WORKING_PTE, KF_XMMI, KF_XMMI64, KiFastSystemCallIsIA32, KiGetCpuVendor(), KiI386PentiumLockErrataPresent, KiIgnoreUnexpectedTrap07, KiMtrrMaskBase, KiMtrrMaskMask, KiMtrrMaxRangeShift, KiMtrrOverflowMask, KiMtrrResBitMask, KiSMTProcessorsPresent, _KPRCB::LogicalProcessorsPerPhysicalProcessor, _LARGE_INTEGER::QuadPart, RDMSR(), READ_PORT_UCHAR(), TRUE, _KPRCB::UpdateSignature, WRITE_PORT_UCHAR(), and WRMSR().
Referenced by KiInitializeKernel().
VOID KiGetInterruptDispatchPatchAddresses (PULONG_PTR Address1, PULONG_PTR Address2)
Referenced by KiInitMachineDependent().
VOID KiI386PentiumLockErrataFixup (VOID)
Definition at line 3232 of file kernlini.c.
References ASSERT, _DESCRIPTOR::Base, _KPCR::IDT, IDT_SKIP, KeDisableInterrupts(), KeEnableInterrupts(), KeGetPcr(), _DESCRIPTOR::Limit, MmAllocateIndependentPages(), MmSetPageProtection(), PAGE_READONLY, PAGE_SIZE, RtlCopyMemory, and Status.
Referenced by KiInitMachineDependent().
VOID KiInitializeDblFaultTSS (IN PKTSS Tss, IN ULONG Stack, IN PKGDTENTRY TssDescriptor)
VOID KiInitializeKernel (IN PKPROCESS Process, IN PKTHREAD Thread, IN PVOID IdleStack, IN PKPRCB Prcb, IN CCHAR Number, PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 330 of file kernlini.c.
References APC_LEVEL, DISPATCH_LEVEL, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExpInitializeExecutive(), FALSE, HIGH_LEVEL, HIGH_PRIORITY, Index, InitializeListHead(), KeAcquireQueuedSpinLockAtDpcLevel(), KeBugCheckEx(), KeComputeReciprocal(), KeFeatureBits, KeGetPcr(), KeI386CpuStep, KeI386CpuType, KeI386FxsrPresent, KeI386NpxPresent, KeI386XMMIPresent, KeInitializeProcess(), KeInitializeSpinLock(), KeInitializeThread(), KeLoaderBlock, KeLowerIrql, KeMaximumIncrement, KeNodeBlock, KeProcessorArchitecture, KeProcessorLevel, KeProcessorRevision, KeRaiseIrql, KeReleaseQueuedSpinLockFromDpcLevel(), KeReleaseSpinLock(), KeSetPriorityThread(), KeTryToAcquireQueuedSpinLockAtRaisedIrql(), KF_3DNOW, KF_CMPXCHG8B, KF_FAST_SYSCALL, KF_FXSR, KF_GLOBAL_32BIT_EXECUTE, KF_GLOBAL_32BIT_NOEXECUTE, KF_GLOBAL_PAGE, KF_MMX, KF_MTRR, KF_NOEXECUTE, KF_PAT, KF_RDTSC, KF_XMMI, KF_XMMI64, KfAcquireSpinLock(), Ki386IopmSaveArea, Ki486CompatibilityLock, KiAcquirePrcbLock(), KiAdjustDpcThreshold, KiBootFeatureBits, KiFastSystemCallDisable, KiFreezeExecutionLock, KiGetCacheInformation(), KiGetFeatureBits(), KiIdleSummary, KiInitSpinLocks(), KiInitSystem(), KiIsNpxPresent(), KiMaximumDpcQueueDepth, KiMinimumDpcRate, KiNode0, KiNodeInit, KiProcessListHead, KiReleasePrcbLock(), KiSaveProcessorControlState(), KiSetCR0Bits(), KiSetProcessorType(), KiTimeIncrementReciprocal, KiTimeIncrementShiftCount, _LOADER_PARAMETER_BLOCK::LoadOptions, MAXCHAR, MAXIMUM_CCNUMA_NODES, MmCreateKernelStack(), MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED, NO_PAGES_AVAILABLE, NULL, NX_SUPPORT_POLICY_ALWAYSOFF, NX_SUPPORT_POLICY_ALWAYSON, NX_SUPPORT_POLICY_OPTIN, NX_SUPPORT_POLICY_OPTOUT, PAGE_SIZE, PagedPool, PF_3DNOW_INSTRUCTIONS_AVAILABLE, PF_COMPARE_EXCHANGE_DOUBLE, PF_MMX_INSTRUCTIONS_AVAILABLE, PF_RDTSC_INSTRUCTION_AVAILABLE, PF_XMMI64_INSTRUCTIONS_AVAILABLE, PF_XMMI_INSTRUCTIONS_AVAILABLE, PHASE0_EXCEPTION, PoInitializePrcb(), _LOADER_PARAMETER_BLOCK::Prcb, PROCESSOR_ARCHITECTURE_INTEL, RET, RtlCopyMemory, Running, SetMember, SharedUserData, strstr(), TRUE, and UNSUPPORTED_PROCESSOR.
VOID KiInitializeMTRR (IN BOOLEAN LastProcessor)
Definition at line 276 of file mtrr.c.
References _RANGE_INFO::Capabilities, _KPRCB::CpuStep, _KPRCB::CpuType, DBGMSG, _RANGE_INFO::Default, _RANGE_INFO::DefaultCachedType, ExAllocatePoolWithTag, ExFreePool(), FALSE, GROW_RANGE_TABLE, _MTRR_CAPABILITIES::hw, _MTRR_DEFAULT::hw, _MTRR_VARIABLE_BASE::hw, _MTRR_VARIABLE_MASK::hw, Index, KeFeatureBits, KeGetCurrentPrcb(), KeGetPcr(), KeInitializeSpinLock(), KF_MTRR, KiAddRange(), KiMaskToLength(), KiMtrrMaskBase, KiMtrrMaskMask, KiMtrrOverflowMask, KiRangeLock, _RANGE_INFO::MaxRange, MTRR_MSR_CAPABILITIES, MTRR_MSR_DEFAULT, MTRR_MSR_VARIABLE_BASE, MTRR_MSR_VARIABLE_MASK, MTRR_TYPE_MAX, MTRR_TYPE_UC, MTRR_TYPE_WB, MTRR_TYPE_WT, _RANGE_INFO::MtrrWorkaround, NonPagedPool, _RANGE_INFO::NoRange, NT_SUCCESS, NULL, _MTRR_CAPABILITIES::QuadPart, _MTRR_DEFAULT::QuadPart, _MTRR_VARIABLE_BASE::QuadPart, _MTRR_VARIABLE_MASK::QuadPart, _RANGE_INFO::Ranges, _RANGE_INFO::RangesValid, RDMSR(), RtlZeroMemory, Status, _NEW_RANGE::Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, strcmp(), TRUE, _MTRR_CAPABILITIES::u, _MTRR_DEFAULT::u, _MTRR_VARIABLE_BASE::u, _MTRR_VARIABLE_MASK::u, and _KPRCB::VendorString.
Referenced by KiInitMachineDependent().
VOID KiInitializePAT (VOID)
Definition at line 115 of file pat.c.
References ASSERT, _NEW_PAT::Attributes, HIGH_LEVEL, _PAT::hw, KeAcquireSpinLock, KeActiveProcessors, KeFeatureBits, KeGetCurrentPrcb(), KeRaiseIrql, KeReleaseSpinLock(), KF_PAT, KiIpiSendSynchronousPacket, KiIpiStallOnPacketTargets(), KiLoadPAT(), KiLoadPATTarget(), KiReverseStallIpiLock, MmEnablePAT(), NULL, _KPRCB::Number, _PAT::Pat, PAT_TYPE_STRONG_UC, PAT_TYPE_USWC, PAT_TYPE_WB, PAT_TYPE_WEAK_UC, _PROCESSOR_LOCKSTEP::Processor, _KPRCB::ReverseStall, _KPRCB::SetMember, _NEW_PAT::Synchronize, _PROCESSOR_LOCKSTEP::TargetCount, and _PROCESSOR_LOCKSTEP::TargetPhase.
Referenced by KeRestorePAT(), and KiInitMachineDependent().
VOID KiInitializePcr (IN ULONG Processor, IN PKPCR Pcr, IN PKIDTENTRY Idt, IN PKGDTENTRY Gdt, IN PKTSS Tss, IN PKTHREAD Thread, IN PVOID DpcStack)
Definition at line 969 of file kernlini.c.
References _KPRCB::DpcStack, EXCEPTION_CHAIN_END, KiProcessorBlock, NULL, PCR_MAJOR_VERSION, PCR_MINOR_VERSION, PF_PAE_ENABLED, PRCB_BUILD_DEBUG, PRCB_BUILD_UNIPROCESSOR, PRCB_MAJOR_VERSION, PRCB_MINOR_VERSION, SharedUserData, and TRUE.
VOID KiInitializeTSS (IN PKTSS Tss)
Definition at line 1092 of file kernlini.c.
References IO_ACCESS_MAP_NONE, KGDT_R0_DATA, and KiComputeIopmOffset.
VOID KiInitializeTSS2 (IN PKTSS Tss, IN PKGDTENTRY TssDescriptor)
Definition at line 1144 of file kernlini.c.
References INT_DIRECTION_MAP_SIZE, IOPM_COUNT, NULL, and PIOPM_SIZE.
BOOLEAN KiInitMachineDependent (VOID)
Definition at line 2271 of file kernlini.c.
References CPUID(), DbgBreakPoint(), FALSE, _FX_SAVE_AREA::FxArea, HalFrameBufferCachingInformation, HalQuerySystemInformation, HIGH_LEVEL, Index, KeActiveProcessors, KeBugCheck(), KeBugCheckEx(), KeDelayExecutionThread(), KeFeatureBits, KeGetCurrentPrcb(), KeGetCurrentThread(), KeI386ForceNpxEmulation, KeI386NpxPresent, KeIpiGenericCall(), KeNumberProcessors, KeQueryPerformanceCounter(), KeRevertToUserAffinityThread(), KernelMode, KeSetSystemAffinityThread(), KF_AMDK6MTRR, KF_FXSR, KF_GLOBAL_PAGE, KF_LARGE_PAGE, KF_MTRR, KF_PAT, KF_RDTSC, KfLowerIrql(), KfRaiseIrql(), Ki386ClearIdentityMap(), Ki386CreateIdentityMap(), Ki386EnableCurrentLargePage(), Ki386EnableCurrentLargePageEnd, Ki386EnableGlobalPage(), Ki386EnableTargetLargePage(), KiAmdK6InitializeMTRR(), KiChainedDispatch2ndLvl(), KiDivide6432(), KiGetInterruptDispatchPatchAddresses(), KiI386PentiumLockErrataFixup(), KiI386PentiumLockErrataPresent, KiInitializeMTRR(), KiInitializePAT(), KiLargePageSafetyCheck(), KiLockStepOtherProcessors(), KiMXCsrMask, KiRestoreFastSyscallReturnState(), KiTestDividend, KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), KiTimeLimitIsrMicroseconds, KiUnlockStepOtherProcessors(), Kix86FxSave(), MAX_ATTEMPTS, _KPRCB::MHz, MmEnablePAT(), MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED, _FXSAVE_FORMAT::MXCsrMask, NT_SUCCESS, NULL, PF_FLOATING_POINT_PRECISION_ERRATA, RDTSC(), SharedUserData, Status, SYNCH_LEVEL, TRUE, _FX_SAVE_AREA::U, UNSUPPORTED_PROCESSOR, and VOID.
BOOLEAN KiIsNpxPresent (VOID)
Referenced by KiInitializeKernel().
VOID KiLockStepOtherProcessors (PULONG Proceed)
Definition at line 2234 of file kernlini.c.
References ASSERT, DISPATCH_LEVEL, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeReleaseSpinLockFromDpcLevel(), KiIpiSendSynchronousPacket, KiIpiStallOnPacketTargets(), KiLockStepProcessor(), KiReverseStallIpiLock, NULL, and _KPRCB::SetMember.
Referenced by KiInitMachineDependent().
VOID KiLockStepProcessor (PKIPI_CONTEXT SignalDone, IN PVOID Arg1, IN PVOID Arg2, IN PVOID Proceed)
Definition at line 2212 of file kernlini.c.
References KiIpiSignalPacketDoneAndStall(), and UNREFERENCED_PARAMETER.
Referenced by KiLockStepOtherProcessors().
NTSTATUS KiMoveRegTree (HANDLE Source, HANDLE Dest)
Definition at line 3073 of file kernlini.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, InitializeObjectAttributes, KEY_ALL_ACCESS, KeyBasicInformation, KeyName, KeyValueFullInformation, _UNICODE_STRING::Length, _KEY_BASIC_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::Name, _KEY_BASIC_INFORMATION::NameLength, _KEY_VALUE_FULL_INFORMATION::NameLength, NT_SUCCESS, NtDeleteKey(), NULL, OBJ_CASE_INSENSITIVE, REG_OPTION_VOLATILE, Status, _KEY_VALUE_FULL_INFORMATION::TitleIndex, _KEY_VALUE_FULL_INFORMATION::Type, ZwClose(), ZwCreateKey(), ZwDeleteValueKey(), ZwEnumerateKey(), ZwEnumerateValueKey(), ZwOpenKey(), and ZwSetValueKey().
Referenced by KeSetup80387OrEmulate().
VOID KiRestoreFastSyscallReturnState (VOID)
Definition at line 703 of file misc.c.
References KeFeatureBits, KeIpiGenericCall(), KF_FAST_SYSCALL, KiEnableFastSyscallReturn(), KiFastSystemCallDisable, KiLoadFastSyscallMachineSpecificRegisters(), KiSystemCallExit, KiSystemCallExit2, and KiSystemCallExitAdjust.
Referenced by KeRestoreProcessorSpecificFeatures(), and KiInitMachineDependent().
VOID KiSetCR0Bits (VOID)
Referenced by KiInitializeKernel().
VOID KiSetProcessorType (VOID)
Definition at line 1659 of file initkr.c.
References CPU_AMD, CPU_INTEL, _KPRCB::CpuID, _KPRCB::CpuStep, _KPRCB::CpuType, KeGetCurrentPrcb(), KiPrefetchRetry, _LARGE_INTEGER::QuadPart, TRUE, and _KPRCB::UpdateSignature.
Referenced by KiInitializeKernel().
VOID KiSwapIDT (VOID)
Definition at line 1230 of file kernlini.c.
References _KIDTENTRY::ExtendedOffset, Index, MAXIMUM_IDTVECTOR, and _KIDTENTRY::Selector.
VOID FASTCALL KiTimedChainedDispatch2ndLvl (PVOID)
Referenced by KiInitMachineDependent().
VOID FASTCALL KiTimedInterruptDispatch (PVOID)
Referenced by KiInitMachineDependent().
VOID KiUnlockStepOtherProcessors (PULONG Proceed)
Definition at line 2261 of file kernlini.c.
Referenced by KiInitMachineDependent().
VOID FASTCALL KiXMMIZeroPages (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
VOID FASTCALL KiXMMIZeroPagesNoSave (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
VOID FASTCALL KiZeroPages (IN PVOID PageBase, IN SIZE_T NumberOfBytes)
VOID FASTCALL RtlPrefetchMemoryNonTemporal (PVOID Memory, SIZE_T Length)
Variable Documentation
WCHAR CmDisabledFloatingPointProcessor[]
Referenced by KeSetup80387OrEmulate().
CHAR CmpAmdID[]
Referenced by KiGetCpuVendor().
CHAR CmpCentaurID[]
Referenced by KiGetCpuVendor().
CHAR CmpCyrixID[]
Referenced by KiGetCpuVendor().
CHAR CmpIntelID[]
Referenced by KiGetCpuVendor().
CHAR CmpRiseID[]
Referenced by KiGetCpuVendor().
CHAR CmpTransmetaID[]
Referenced by KiGetCpuVendor().
KIDTENTRY IDT[]
ULONG KeI386ForceNpxEmulation
Definition at line 33 of file i386init.c.
Referenced by KiInitMachineDependent().
BOOLEAN KeI386XMMIPresent
Definition at line 215 of file kernlini.c.
Referenced by KeRestoreFloatingPointState(), KeSaveFloatingPointState(), KiDispatchException(), and KiInitializeKernel().
ULONG KePrefetchNTAGranularity = 32
Definition at line 251 of file kernlini.c.
Referenced by KiGetCacheInformation().
KE_ZERO_PAGE_ROUTINE KeZeroPages = KiZeroPages
Definition at line 243 of file kernlini.c.
Referenced by MiMapBBTMemory(), MiZeroAwePageWorker(), and MiZeroPageWorker().
KE_ZERO_PAGE_ROUTINE KeZeroPagesFromIdleThread = KiZeroPages
Definition at line 244 of file kernlini.c.
PVOID Ki386IopmSaveArea
Definition at line 44 of file biosc.c.
Referenced by Ke386CallBios(), and KiInitializeKernel().
PVOID Ki387RoundModeTable
Definition at line 37 of file i386init.c.
Referenced by KeSetup80387OrEmulate().
ULONG Ki486CompatibilityLock
Definition at line 267 of file kernlini.c.
Referenced by KiInitializeKernel().
ULONG KiFastSystemCallDisable
Definition at line 157 of file kernlini.c.
Referenced by KiInitializeKernel(), and KiRestoreFastSyscallReturnState().
BOOLEAN KiFastSystemCallIsIA32
Definition at line 37 of file misc.c.
Referenced by KiGetFeatureBits(), and KiLoadFastSyscallMachineSpecificRegisters().
BOOLEAN KiI386PentiumLockErrataPresent = FALSE
Definition at line 154 of file kernlini.c.
Referenced by KiGetFeatureBits(), and KiInitMachineDependent().
BOOLEAN KiIgnoreUnexpectedTrap07 = FALSE
Definition at line 155 of file kernlini.c.
Referenced by KiGetFeatureBits().
BOOLEAN KiSMTProcessorsPresent
Referenced by KiGetFeatureBits().
ULONG KiTimeLimitIsrMicroseconds
Definition at line 30 of file intobj.c.
Referenced by KiInitializeInterruptTimers(), KiInitializeInterruptTimersDpc(), and KiInitMachineDependent().
ULONG KiXMMIZeroingEnable
Definition at line 158 of file kernlini.c.
PVOID ScPatchFxb
PVOID ScPatchFxe