Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psctx.c File Reference
psctx.c File Reference
#include "psp.h"
Functions
NTSTATUS NtGetContextThread (__in HANDLE ThreadHandle, __inout PCONTEXT ThreadContext)
NTSYSAPI NTSTATUS NTAPI NtQueueApcThread (__in HANDLE ThreadHandle, __in PPS_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcArgument1, __in_opt PVOID ApcArgument2, __in_opt PVOID ApcArgument3)
NTSTATUS NtSetContextThread (__in HANDLE ThreadHandle, __in PCONTEXT ThreadContext)
NTSTATUS PsGetContextThread (__in PETHREAD Thread, __inout PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
VOID PspQueueApcSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
NTSTATUS PsSetContextThread (__in PETHREAD Thread, __in PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
NTSTATUS PsWrapApcWow64Thread (__inout PVOID *ApcContext, __inout PVOID *ApcRoutine)
Function Documentation
NTSTATUS NtGetContextThread (__in HANDLE ThreadHandle, __inout PCONTEXT ThreadContext)
Definition at line 309 of file psctx.c.
References FALSE, IS_SYSTEM_THREAD, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetContextThread(), PsGetCurrentThread(), PsThreadType, Status, STATUS_INVALID_HANDLE, _ETHREAD::Tcb, and THREAD_GET_CONTEXT.
Referenced by RtlRemoteCall().
NTSYSAPI NTSTATUS NTAPI NtQueueApcThread (__in HANDLE ThreadHandle, __in PPS_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcArgument1, __in_opt PVOID ApcArgument2, __in_opt PVOID ApcArgument3)
Definition at line 61 of file psctx.c.
References ExAllocatePoolWithQuotaTag, ExFreePool(), IS_SYSTEM_THREAD, KeGetPreviousMode, KeInitializeApc(), KeInsertQueueApc(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OriginalApcEnvironment, PAGED_CODE, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, PspQueueApcSpecialApc(), PsThreadType, STATUS_INVALID_HANDLE, STATUS_NO_MEMORY, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _ETHREAD::Tcb, THREAD_SET_CONTEXT, and UserMode.
NTSTATUS NtSetContextThread (__in HANDLE ThreadHandle, __in PCONTEXT ThreadContext)
Definition at line 529 of file psctx.c.
References FALSE, IS_SYSTEM_THREAD, KeGetPreviousModeByThread, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentThread(), PsSetContextThread(), PsThreadType, Status, STATUS_INVALID_HANDLE, _ETHREAD::Tcb, and THREAD_SET_CONTEXT.
Referenced by RtlRemoteCall().
NTSTATUS PsGetContextThread (__in PETHREAD Thread, __inout PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
Definition at line 147 of file psctx.c.
References _GETSETCONTEXT::Apc, ASSERT, _GETSETCONTEXT::Context, CONTEXT_ALIGN, CONTEXT_EXTENDED_REGISTERS, _CONTEXT::ContextFlags, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, FIELD_OFFSET, KeEnterGuardedRegionThread(), KeInitializeApc(), KeInitializeEvent(), KeInsertQueueApc(), KeLeaveGuardedRegionThread(), KernelMode, KeWaitForSingleObject(), _GETSETCONTEXT::Mode, NotificationEvent, NULL, _GETSETCONTEXT::OperationComplete, OriginalApcEnvironment, PAGED_CODE, ProbeForReadSmallStructure, PsGetCurrentThread(), PspGetSetContextSpecialApc(), RtlCopyMemory, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _KAPC::SystemArgument1, _KAPC::SystemArgument2, and _ETHREAD::Tcb.
Referenced by NtGetContextThread().
VOID PspQueueApcSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 40 of file psctx.c.
References ExFreePool(), PAGED_CODE, and UNREFERENCED_PARAMETER.
Referenced by NtQueueApcThread().
NTSTATUS PsSetContextThread (__in PETHREAD Thread, __in PCONTEXT ThreadContext, __in KPROCESSOR_MODE Mode)
Definition at line 389 of file psctx.c.
References _GETSETCONTEXT::Apc, ASSERT, _GETSETCONTEXT::Context, CONTEXT_ALIGN, CONTEXT_EXTENDED_REGISTERS, _CONTEXT::ContextFlags, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, FIELD_OFFSET, KeEnterGuardedRegionThread(), KeInitializeApc(), KeInitializeEvent(), KeInsertQueueApc(), KeLeaveGuardedRegionThread(), KernelMode, KeWaitForSingleObject(), _GETSETCONTEXT::Mode, NotificationEvent, NULL, _GETSETCONTEXT::OperationComplete, OriginalApcEnvironment, PAGED_CODE, ProbeForReadSmallStructure, PsGetCurrentThread(), PspGetSetContextSpecialApc(), RtlCopyMemory, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _KAPC::SystemArgument1, _KAPC::SystemArgument2, and _ETHREAD::Tcb.
Referenced by NtSetContextThread().
NTSTATUS PsWrapApcWow64Thread (__inout PVOID * ApcContext, __inout PVOID * ApcRoutine)
Definition at line 607 of file psctx.c.
References except, EXCEPTION_EXECUTE_HANDLER, NULL, PsGetCurrentProcess(), STATUS_SUCCESS, UNREFERENCED_PARAMETER, and Wow64KiWrapApcProc.