Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/str2addt.h File Reference
str2addt.h File Reference
Data Structures
struct in6_addr
struct in_addr
Macros
#define INADDR_NONE 0xffffffff
#define ISDIGIT(c) (_istascii(c) && _istdigit(c))
#define ISLOWER(c) (_istascii(c) && _istlower(c))
#define ISXDIGIT(c) (_istascii(c) && _istxdigit(c))
#define s6_bytes u.Byte
#define s6_words u.Word
#define s_addr S_un.S_addr
Functions
NTSTATUS RtlIpv4StringToAddressExT (IN LPCTSTR AddressString, IN BOOLEAN Strict, OUT struct in_addr *Address, OUT PUSHORT Port)
NTSTATUS RtlIpv4StringToAddressT (IN LPCTSTR String, IN BOOLEAN Strict, OUT LPCTSTR *Terminator, OUT struct in_addr *Addr)
NTSTATUS RtlIpv6StringToAddressExT (IN LPCTSTR AddressString, OUT struct in6_addr *Address, OUT PULONG ScopeId, OUT PUSHORT Port)
NTSTATUS RtlIpv6StringToAddressT (IN LPCTSTR S, OUT LPCTSTR *Terminator, OUT struct in6_addr *Addr)
Macro Definition Documentation
#define INADDR_NONE 0xffffffff
Definition at line 44 of file str2addt.h.
#define ISDIGIT (c) (_istascii(c) && _istdigit(c))
Definition at line 40 of file str2addt.h.
Referenced by RtlIpv4StringToAddressExT(), RtlIpv4StringToAddressT(), RtlIpv6StringToAddressExT(), and RtlIpv6StringToAddressT().
#define ISLOWER (c) (_istascii(c) && _istlower(c))
Definition at line 41 of file str2addt.h.
Referenced by RtlIpv4StringToAddressExT(), RtlIpv4StringToAddressT(), and RtlIpv6StringToAddressExT().
#define ISXDIGIT (c) (_istascii(c) && _istxdigit(c))
Definition at line 42 of file str2addt.h.
Referenced by RtlIpv4StringToAddressExT(), RtlIpv4StringToAddressT(), RtlIpv6StringToAddressExT(), and RtlIpv6StringToAddressT().
#define s6_bytes u.Byte
Definition at line 25 of file str2addt.h.
#define s6_words u.Word
Definition at line 26 of file str2addt.h.
#define s_addr S_un.S_addr
Definition at line 35 of file str2addt.h.
Function Documentation
NTSTATUS RtlIpv4StringToAddressExT (IN LPCTSTR AddressString, IN BOOLEAN Strict, OUT struct in_addr * Address, OUT PUSHORT Port)
Definition at line 684 of file str2addt.h.
References _T, FALSE, ISDIGIT, ISLOWER, ISXDIGIT, NT_SUCCESS, NULL, RtlIpv4StringToAddressT(), RtlUshortByteSwap(), STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
NTSTATUS RtlIpv4StringToAddressT (IN LPCTSTR String, IN BOOLEAN Strict, OUT LPCTSTR * Terminator, OUT struct in_addr * Addr)
Definition at line 462 of file str2addt.h.
References _T, FALSE, ISDIGIT, ISLOWER, ISXDIGIT, RtlUlongByteSwap(), STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by RtlIpv4StringToAddressExT().
NTSTATUS RtlIpv6StringToAddressExT (IN LPCTSTR AddressString, OUT struct in6_addr * Address, OUT PULONG ScopeId, OUT PUSHORT Port)
Definition at line 294 of file str2addt.h.
References _T, FALSE, ISDIGIT, ISLOWER, ISXDIGIT, NT_SUCCESS, NULL, RtlIpv6StringToAddressT(), RtlUshortByteSwap(), STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
NTSTATUS RtlIpv6StringToAddressT (IN LPCTSTR S, OUT LPCTSTR * Terminator, OUT struct in6_addr * Addr)
Definition at line 47 of file str2addt.h.
References _T, _tcstol, FALSE, ISDIGIT, ISXDIGIT, NULL, RtlMoveMemory, RtlUshortByteSwap(), RtlZeroMemory, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by RtlIpv6StringToAddressExT().