Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivecell.c File Reference
hivecell.c File Reference
#include "cmp.h"
Macros
#define HvpAdjustCellSize(Size)
#define SIXTEEN_K 0x4000
Functions
HCELL_INDEX HvAllocateCell (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
BOOLEAN HvAutoCompressCheck (PHHIVE Hive)
HCELL_INDEX HvDuplicateCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type, BOOLEAN CopyData)
VOID HvFreeCell (PHHIVE Hive, HCELL_INDEX Cell)
LONG HvGetCellSize (IN PHHIVE Hive, IN PVOID Address)
BOOLEAN HvIsCellAllocated (PHHIVE Hive, HCELL_INDEX Cell)
VOID HvpDelistBinFreeCells (PHHIVE Hive, PHBIN Bin, HSTORAGE_TYPE Type)
VOID HvpDelistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type)
HCELL_INDEX HvpDoAllocateCell (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
VOID HvpEnlistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG Size, HSTORAGE_TYPE Type, BOOLEAN CoalesceForward)
struct _CELL_DATA * HvpGetCellFlat (PHHIVE Hive, HCELL_INDEX Cell)
PHMAP_ENTRY HvpGetCellMap (PHHIVE Hive, HCELL_INDEX Cell)
struct _CELL_DATA * HvpGetCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
struct _CELL_DATA * HvpGetCellPaged (PHHIVE Hive, HCELL_INDEX Cell)
PHCELL HvpGetHCell (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN HvpIsFreeNeighbor (PHHIVE Hive, PHBIN Bin, PHCELL FreeCell, PHCELL *FreeNeighbor, HSTORAGE_TYPE Type)
VOID HvpReleaseCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
HCELL_INDEX HvReallocateCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG NewSize)
VOID HvReleaseFreeCellRefArray (PHV_TRACK_CELL_REF CellRef)
HCELL_INDEX HvShiftCell (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN HvTrackCellRef (PHV_TRACK_CELL_REF CellRef, PHHIVE Hive, HCELL_INDEX Cell)
Variables
BOOLEAN HvShutdownComplete
Macro Definition Documentation
#define HvpAdjustCellSize (Size)
Value:
{                                                                   \
        ULONG   onek = SIXTEEN_K;                                       \
        ULONG   Limit = 0;                                              \
                                                                        \
        while( Size > onek ) {                                          \
            onek<<=1;                                                   \
            Limit++;                                                    \
        }                                                               \
                                                                        \
        Size = Limit?onek:Size;                                         \
    }
Definition at line 75 of file hivecell.c.
Referenced by HvAllocateCell(), and HvReallocateCell().
#define SIXTEEN_K 0x4000
Definition at line 56 of file hivecell.c.
Function Documentation
HCELL_INDEX HvAllocateCell (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
Definition at line 858 of file hivecell.c.
References ASSERT, CmKdPrintEx, CML_HIVE, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, HCELL_NIL, HCELL_PAD, HHIVE_SIGNATURE, HSANE_CELL_MAX, HvIsCellAllocated(), HvpAdjustCellSize, HvpDoAllocateCell(), _HHIVE::ReadOnly, ROUND_UP, _HHIVE::Signature, _CELL_DATA::u, and USE_OLD_CELL.
Referenced by CmpAddSubKey(), CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreateChild(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmRenameKey(), and HvDuplicateCell().
BOOLEAN HvAutoCompressCheck (PHHIVE Hive)
Definition at line 2094 of file hivecell.c.
References ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CM_HIVE_COMPRESS_LEVEL, CM_PAGED_CODE, CONTAINING_RECORD, FALSE, _CMHIVE::FileHandles, _LIST_ENTRY::Flink, _HHIVE::_DUAL::FreeBins, HFILE_TYPE_PRIMARY, IsListEmpty, _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, NULL, _FREE_HBIN::Size, Stable, _HHIVE::Storage, and TRUE.
Referenced by CmCompressKey().
HCELL_INDEX HvDuplicateCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type, BOOLEAN CopyData)
Definition at line 1996 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, CM_PAGED_CODE, FALSE, HCELL_NIL, HHIVE_SIGNATURE, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellSize(), HvGetCellType, HvIsCellAllocated(), HvReleaseCell, NULL, _HHIVE::ReadOnly, RtlCopyMemory, RtlZeroMemory, _HHIVE::Signature, and TRUE.
Referenced by CmpDuplicateIndex().
VOID HvFreeCell (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1529 of file hivecell.c.
References ASSERT, ASSERT_BIN_VALID, ASSERT_CELL_DIRTY, ASSERT_HIVE_FLUSHER_LOCKED, Bin, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_HIVE, CmpLockHiveWriter, CmpUnlockHiveWriter, DHvCheckBin, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _HBIN::FileOffset, HBIN_BASE, HCELL_FREE_FILL, HCELL_TYPE_MASK, HvGetCellType, HvpEnlistFreeCell(), HvpGetCellMap(), HvpGetHCell(), HvpIsFreeNeighbor(), HvReleaseCell, NULL, _HHIVE::ReadOnly, RtlFillMemory, _HCELL::Size, _HBIN::Size, TRUE, _HCELL::u, _CELL_DATA::u, USE_OLD_CELL, and VALIDATE_CELL_MAP.
Referenced by CmMoveKey(), CmpAddSubKey(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCopyKeyPartial(), CmpCopyValue(), CmpCreateLinkNode(), CmpDoCreateChild(), CmpDuplicateIndex(), CmpFreeKeyBody(), CmpFreeKeyByCell(), CmpFreeKeyValues(), CmpFreeSecurityDescriptor(), CmpFreeValue(), CmpFreeValueData(), CmpRemoveSubKey(), CmpRemoveValueFromList(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmRenameKey(), HvDuplicateCell(), and HvReallocateCell().
LONG HvGetCellSize (IN PHHIVE Hive, IN PVOID Address)
Definition at line 1482 of file hivecell.c.
References CmKdPrintEx, CML_FLOW, CONTAINING_RECORD, DPFLTR_CONFIG_ID, FIELD_OFFSET, _CELL_DATA::u, and USE_OLD_CELL.
Referenced by HvDuplicateCell(), and HvReallocateCell().
BOOLEAN HvIsCellAllocated (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1156 of file hivecell.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, FALSE, _HHIVE::Flat, HBIN_BASE, HBIN_NIL, HCELL_PAD, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_DISCARDABLE, HvGetCellType, HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, leave, _HHIVE::_DUAL::Length, NULL, _HHIVE::Signature, _HCELL::Size, _HHIVE::Storage, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by CmpCheckKey(), CmpCheckValueList(), CmpFindSubKeyByName(), CmpFreeValueData(), CmpMarkIndexDirty(), CmpRebuildSecurityCache(), CmpRemoveSubKey(), CmpValidateHiveSecurityDescriptors(), HvAllocateCell(), HvDuplicateCell(), and HvReallocateCell().
VOID HvpDelistBinFreeCells (PHHIVE Hive, PHBIN Bin, HSTORAGE_TYPE Type)
Definition at line 1264 of file hivecell.c.
References ASSERT, ASSERT_LISTENTRY, BAD_FREE_BINS_LIST, _HMAP_ENTRY::BinAddress, Cell, CM_BUGCHECK, CONTAINING_RECORD, _FREE_DISPLAY::Display, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _LIST_ENTRY::Flink, _HHIVE::Free, _HHIVE::_DUAL::FreeBins, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HHIVE_FREE_DISPLAY_SIZE, HMAP_DISCARDABLE, HMAP_NEWALLOC, HvpGetCellMap(), _FREE_HBIN::ListEntry, REGISTRY_ERROR, RemoveEntryList(), RtlClearBits(), RtlNumberOfSetBits(), _FREE_HBIN::Size, _HHIVE::Storage, and VALIDATE_CELL_MAP.
Referenced by HvpRecoverData().
VOID HvpDelistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type)
Definition at line 804 of file hivecell.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, FALSE, HvpComputeIndex, HvpGetHCell(), HvpRemoveFreeCellHint(), HvReleaseCell, Index, NULL, and _HCELL::Size.
Referenced by HvpEnlistFreeCell(), HvpFindFreeCellInBin(), and HvpIsFreeNeighbor().
HCELL_INDEX HvpDoAllocateCell (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
Definition at line 934 of file hivecell.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, Bin, _HMAP_ENTRY::BinAddress, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_FREECELL, CML_HIVE, CmpLockHiveWriter, CmpUnlockHiveWriter, DHvCheckBin, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _HBIN::FileOffset, HBIN_BASE, HCELL_ALLOCATE_FILL, HCELL_NIL, HCELL_TYPE_MASK, HvpAddBin(), HvpComputeIndex, HvpEnlistFreeCell(), HvpFindFreeCell(), HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, Index, _UNICODE_STRING::Length, NULL, _HHIVE::ReadOnly, RtlFillMemory, RtlInitUnicodeString(), _HCELL::Size, TRUE, _HCELL::u, _CELL_DATA::u, USE_OLD_CELL, and VALIDATE_CELL_MAP.
Referenced by HvAllocateCell(), and HvReallocateCell().
VOID HvpEnlistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG Size, HSTORAGE_TYPE Type, BOOLEAN CoalesceForward)
Definition at line 556 of file hivecell.c.
References ASSERT, ASSERT_BIN_VALID, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_LISTENTRY, Bin, BIN_MAP_ALLOCATION_TYPE, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, FALSE, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _FREE_HBIN::Flags, _LIST_ENTRY::Flink, FREE_HBIN_DISCARDABLE, HBIN_BASE, HBIN_NIL, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HvMarkDirty(), HvpAddFreeCellHint(), HvpComputeIndex, HvpDelistFreeCell(), HvpGetBinMemAlloc(), HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, Index, InsertHeadList(), _FREE_HBIN::ListEntry, NULL, _HCELL::Size, _HBIN::Size, _FREE_HBIN::Size, TRUE, _HCELL::u, USE_OLD_CELL, and VALIDATE_CELL_MAP.
Referenced by HvFreeCell(), HvpDoAllocateCell(), and HvpEnlistFreeCells().
struct _CELL_DATA* HvpGetCellFlat (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1370 of file hivecell.c.
References ASSERT, _HHIVE::BaseBlock, CmKdPrintEx, CML_FLOW, DPFLTR_CONFIG_ID, _HHIVE::Flat, HBLOCK_SIZE, HCELL_NIL, HHIVE_SIGNATURE, HvGetCellType, PERFINFO_HIVECELL_REFERENCE_FLAT, _HHIVE::Signature, Stable, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by HvInitializeHive().
PHMAP_ENTRY HvpGetCellMap (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1434 of file hivecell.c.
References ASSERT, CmKdPrintEx, CML_FLOW, DPFLTR_CONFIG_ID, FALSE, _HHIVE::Flat, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HvGetCellType, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, _HHIVE::Signature, _HHIVE::Storage, and _HMAP_TABLE::Table.
Referenced by CmpMapCmView(), CmpUnmapCmView(), HvCheckHive(), HvCloneHive(), HvFreeCell(), HvFreeHive(), HvFreeHivePartial(), HvHiveWillShrink(), HvIsCellAllocated(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpAddFreeCellHint(), HvpBuildMapAndCopy(), HvpCoalesceDiscardedBins(), HvpDelistBinFreeCells(), HvpDoAllocateCell(), HvpDoWriteHive(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistBinInMap(), HvpEnlistFreeCell(), HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpGetBinMemAlloc(), HvpMapFileImageAndBuildMap(), HvpRecoverData(), HvpRecoverWholeHive(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), HvpTruncateBins(), HvRefreshHive(), HvShiftCell(), HvShrinkHive(), and HvWriteHive().
struct _CELL_DATA* HvpGetCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 258 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CML_FLOW, CmLockHiveViews, CmLogCellDeRef, CmLogCellRef, CmpMapCmView(), CmpTouchView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HHIVE::Flat, HBIN_BASE, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_NIL, HCELL_OFFSET_MASK, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvGetCellType, HvShutdownComplete, _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, PAGE_SIZE, PERFINFO_HIVECELL_REFERENCE_PAGED, ROUND_UP, _HHIVE::Signature, _HCELL::Size, _HBIN::Size, Stable, _HHIVE::Storage, TRUE, _HCELL::u, USE_OLD_CELL, and _CM_VIEW_OF_FILE::UseCount.
Referenced by CmpSetupPrivateWrite(), and HvInitializeHive().
struct _CELL_DATA* HvpGetCellPaged (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 465 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CML_FLOW, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FALSE, _HHIVE::Flat, HBIN_BASE, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_NIL, HCELL_OFFSET_MASK, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HvGetCellType, HvShutdownComplete, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, PERFINFO_HIVECELL_REFERENCE_PAGED, _HHIVE::Signature, Stable, _HHIVE::Storage, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by HvInitializeHive().
PHCELL HvpGetHCell (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 119 of file hivecell.c.
References CONTAINING_RECORD, HvGetCell, _HCELL::NewCell, NULL, _HCELL::OldCell, and USE_OLD_CELL.
Referenced by HvFreeCell(), HvIsCellAllocated(), HvMarkCellDirty(), HvpDelistFreeCell(), HvpDoAllocateCell(), and HvpEnlistFreeCell().
BOOLEAN HvpIsFreeNeighbor (PHHIVE Hive, PHBIN Bin, PHCELL FreeCell, PHCELL * FreeNeighbor, HSTORAGE_TYPE Type)
Definition at line 1706 of file hivecell.c.
References ASSERT, ASSERT_HIVE_WRITER_LOCK_OWNED, CmKdPrintEx, CML_HIVE, DPFLTR_CONFIG_ID, FALSE, HBIN_NIL, HCELL_NIL, HCELL_TYPE_MASK, HvMarkCellDirty(), HvpDelistFreeCell(), NULL, _HHIVE::ReadOnly, _HCELL::Size, TRUE, _HCELL::u, USE_OLD_CELL, and Volatile.
Referenced by HvFreeCell().
VOID HvpReleaseCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 160 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_FLOW, CmLockHiveViews, CmLogCellDeRef, CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FALSE, _HHIVE::Flat, HBIN_BASE, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_NIL, HCELL_OFFSET_MASK, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvGetCellType, HvShutdownComplete, _HHIVE::_DUAL::Length, NULL, _HHIVE::Signature, Stable, _HHIVE::Storage, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpSetupPrivateWrite(), and HvInitializeHive().
HCELL_INDEX HvReallocateCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG NewSize)
Definition at line 1825 of file hivecell.c.
References ASSERT, Cell, CmKdPrintEx, CML_HIVE, CmpLockHiveWriter, CmpUnlockHiveWriter, DHvCheckHive, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, HCELL_NIL, HCELL_PAD, HHIVE_SIGNATURE, HSANE_CELL_MAX, HvFreeCell(), HvGetCell, HvGetCellSize(), HvGetCellType, HvIsCellAllocated(), HvpAdjustCellSize, HvpDoAllocateCell(), HvReleaseCell, NULL, _HHIVE::ReadOnly, ROUND_UP, RtlMoveMemory, _HHIVE::Signature, _CELL_DATA::u, and USE_OLD_CELL.
Referenced by CmpAddToLeaf(), CmpAddValueToList(), CmpRemoveValueFromList(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueKeyExisting(), CmpSplitLeaf(), and CmRestoreKey().
VOID HvReleaseFreeCellRefArray (PHV_TRACK_CELL_REF CellRef)
Definition at line 2274 of file hivecell.c.
References ASSERT, _HV_HIVE_CELL_PAIR::Cell, _HV_TRACK_CELL_REF::CellArray, CM_PAGED_CODE, _HV_TRACK_CELL_REF::Count, ExFreePool(), _HV_HIVE_CELL_PAIR::Hive, HvReleaseCell, _HV_TRACK_CELL_REF::Max, NULL, STATIC_CELL_PAIR_COUNT, _HV_TRACK_CELL_REF::StaticArray, and _HV_TRACK_CELL_REF::StaticCount.
Referenced by CmEnumerateKey(), CmpDoCreate(), CmpDuplicateIndex(), CmpInsertSecurityCellList(), CmpMarkKeyValuesDirty(), CmpMergeKeyValues(), CmpSelectLeaf(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmQueryKey(), and CmSaveMergedKeys().
HCELL_INDEX HvShiftCell (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2168 of file hivecell.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, HBIN_BASE, HBIN_SIGNATURE, HMAP_INPAGEDPOOL, HvGetCellType, HvpGetCellMap(), _HBIN::Signature, _HBIN::Spare, and Stable.
Referenced by CmpShiftAllCells(), CmpShiftAllCells2(), CmpShiftHiveFreeBins(), CmpShiftIndex(), CmpShiftKey(), CmpShiftSecurityCells(), and CmpShiftValueList().
BOOLEAN HvTrackCellRef (PHV_TRACK_CELL_REF CellRef, PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2187 of file hivecell.c.
References ASSERT, Cell, _HV_HIVE_CELL_PAIR::Cell, _HV_TRACK_CELL_REF::CellArray, CM_PAGED_CODE, _HV_TRACK_CELL_REF::Count, ExAllocatePool, ExFreePool(), FALSE, HCELL_NIL, Hive, _HV_HIVE_CELL_PAIR::Hive, HvReleaseCell, _HV_TRACK_CELL_REF::Max, NULL, PagedPool, RtlCopyMemory, STATIC_CELL_PAIR_COUNT, _HV_TRACK_CELL_REF::StaticArray, _HV_TRACK_CELL_REF::StaticCount, and TRUE.
Referenced by CmEnumerateKey(), CmpDoCreate(), CmpDuplicateIndex(), CmpInsertSecurityCellList(), CmpMarkKeyValuesDirty(), CmpMergeKeyValues(), CmpSelectLeaf(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmQueryKey(), and CmSaveMergedKeys().
Variable Documentation
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by HvpGetCellMapped(), HvpGetCellPaged(), and HvpReleaseCellMapped().