Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmsubs3.c File Reference
cmsubs3.c File Reference
#include "cmp.h"
Functions
BOOLEAN CmpKCBLockForceAcquireAllowed (ULONG Index1, ULONG Index2, ULONG NewIndex)
VOID CmpLockRegistry (VOID)
VOID CmpLockRegistryExclusive (VOID)
VOID CmpLockTwoHashEntriesExclusive (ULONG ConvKey1, ULONG ConvKey2)
VOID CmpLockTwoHashEntriesShared (ULONG ConvKey1, ULONG ConvKey2)
BOOLEAN CmpTryConvertKCBLockSharedToExclusive (PCM_KEY_CONTROL_BLOCK Kcb)
BOOLEAN CmpTryToLockHashEntryByIndexExclusive (ULONG Index)
VOID CmpUnlockRegistry ()
VOID CmpUnlockTwoHashEntries (ULONG ConvKey1, ULONG ConvKey2)
Variables
BOOLEAN CmpFlushOnLockRelease = FALSE
LONG CmpFlushStarveWriters = 0
ERESOURCE CmpRegistryLock
BOOLEAN CmpSpecialBootCondition
LONG CmRegistryLogSizeLimit = -1
Function Documentation
BOOLEAN CmpKCBLockForceAcquireAllowed (ULONG Index1, ULONG Index2, ULONG NewIndex)
Definition at line 498 of file cmsubs3.c.
References ASSERT, CmpHashTableSize, FALSE, and TRUE.
Referenced by CmpCleanUpKCBCacheTable(), CmpRunDownDelayDerefKCBEngine(), and CmpSearchForOpenSubKeys().
VOID CmpLockRegistry (VOID)
Definition at line 70 of file cmsubs3.c.
References CmKdPrintEx, CML_LOCKING, CmpFlushStarveWriters, DPFLTR_CONFIG_ID, ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), KeEnterCriticalRegion(), RtlGetCallersAddress(), and TRUE.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmLoadKey(), CmNotifyRunDown(), CmpBuildHashStackAndLookupCache(), CmpCloseKeyObject(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpLateUnloadHiveWorker(), CmpLazyFlushWorker(), CmpQueryKeyName(), CmPrefetchHivePages(), CmpSecurityMethod(), CmpWmiDumpKcbTable(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), NtFlushKey(), NtLockRegistryKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), and NtUnloadKey2().
VOID CmpLockRegistryExclusive (VOID)
Definition at line 116 of file cmsubs3.c.
References ASSERT, CmpFlushStarveWriters, ExAcquireResourceExclusiveLite(), KeEnterCriticalRegion(), RtlGetCallersAddress(), and TRUE.
Referenced by CmFlushKey(), CmGetSystemDriverList(), CmInitSystem1(), CmLoadKey(), CmpCloneControlSet(), CmpLateUnloadHiveWorker(), CmpLazyFlushWorker(), CmpLoadHiveVolatile(), CmpRefreshHive(), CmpSaveBootControlSet(), CmpSaveKeyByFileCopy(), CmRestoreKey(), CmSaveKey(), CmShutdownSystem(), NtCompactKeys(), NtCompressKey(), NtInitializeRegistry(), NtRenameKey(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpLockTwoHashEntriesExclusive (ULONG ConvKey1, ULONG ConvKey2)
Definition at line 267 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, CmpLockHashEntryExclusive, and GET_HASH_INDEX.
Referenced by CmDeleteKey(), CmpCreateKeyControlBlock(), CmpGetSymbolicLink(), CmUnloadKey(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), and NtUnloadKey2().
VOID CmpLockTwoHashEntriesShared (ULONG ConvKey1, ULONG ConvKey2)
Definition at line 311 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, CmpLockHashEntryShared, and GET_HASH_INDEX.
Referenced by CmSaveMergedKeys(), and NtNotifyChangeMultipleKeys().
BOOLEAN CmpTryConvertKCBLockSharedToExclusive (PCM_KEY_CONTROL_BLOCK Kcb)
Definition at line 203 of file cmsubs3.c.
References ASSERT, ASSERT_KCB_LOCKED, CmpIsKCBLockedExclusive, ExTryConvertPushLockSharedToExclusive(), FALSE, GET_KCB_HASH_ENTRY_LOCK, GET_KCB_HASH_ENTRY_OWNER, and KeGetCurrentThread().
Referenced by CmEnumerateValueKey(), CmpCompareNewValueDataAgainstKCBCache(), CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpReferenceKeyControlBlock(), CmQueryValueKey(), and CmSetValueKey().
BOOLEAN CmpTryToLockHashEntryByIndexExclusive (ULONG Index)
Definition at line 232 of file cmsubs3.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, CmpCacheTable, ExTryAcquirePushLockExclusive(), Index, KeGetCurrentThread(), NULL, and _CM_KEY_HASH_TABLE_ENTRY::Owner.
Referenced by CmpCleanUpKCBCacheTable(), CmpRunDownDelayDerefKCBEngine(), and CmpSearchForOpenSubKeys().
VOID CmpUnlockRegistry ()
Definition at line 149 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmpDoFlushAll(), CmpFlushOnLockRelease, ExIsResourceAcquiredExclusiveLite(), ExReleaseResourceLite(), FALSE, KeLeaveCriticalRegion(), _OWNER_ENTRY::OwnerCount, _ERESOURCE::OwnerThreads, and TRUE.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmDumpKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmFlushKey(), CmGetSystemDriverList(), CmInitSystem1(), CmLoadKey(), CmNotifyRunDown(), CmpCloneControlSet(), CmpCloseKeyObject(), CmpDelayCloseWorker(), CmpDelayDerefKCBWorker(), CmpDeleteKeyObject(), CmpLateUnloadHiveWorker(), CmpLazyFlushWorker(), CmpLoadHiveVolatile(), CmpParseKey(), CmpQueryKeyName(), CmPrefetchHivePages(), CmpRefreshHive(), CmpSaveBootControlSet(), CmpSaveKeyByFileCopy(), CmpSecurityMethod(), CmpWmiDumpKcbTable(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRestoreKey(), CmSaveKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), CmShutdownSystem(), CmUnloadKey(), NtCompactKeys(), NtCompressKey(), NtFlushKey(), NtInitializeRegistry(), NtLockRegistryKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtRenameKey(), NtUnloadKey2(), and NtUnloadKeyEx().
VOID CmpUnlockTwoHashEntries (ULONG ConvKey1, ULONG ConvKey2)
Definition at line 355 of file cmsubs3.c.
References ASSERT_CM_LOCK_OWNED, ASSERT_HASH_ENTRY_LOCKED, CmpUnlockHashEntry, and GET_HASH_INDEX.
Referenced by CmDeleteKey(), CmpCreateKeyControlBlock(), CmpGetSymbolicLink(), CmSaveMergedKeys(), CmUnloadKey(), NtNotifyChangeMultipleKeys(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), and NtUnloadKey2().
Variable Documentation
BOOLEAN CmpFlushOnLockRelease = FALSE
Definition at line 56 of file cmsubs3.c.
Referenced by CmpDoFileSetSize(), CmpUnlockRegistry(), HvpGrowLog1(), and HvpGrowLog2().
LONG CmpFlushStarveWriters = 0
Definition at line 55 of file cmsubs3.c.
Referenced by CmpLockRegistry(), and CmpLockRegistryExclusive().
ERESOURCE CmpRegistryLock
Definition at line 52 of file cmsubs3.c.
Referenced by CmpDoFileSetSize().
BOOLEAN CmpSpecialBootCondition
Definition at line 347 of file cmdat.c.
Referenced by CmpInitializeHiveList().
LONG CmRegistryLogSizeLimit = -1
Definition at line 57 of file cmsubs3.c.
Referenced by HvpGrowLog1(), and HvpGrowLog2().