Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/kiamd64.h File Reference
kiamd64.h File Reference
Data Structures
struct _REQUEST_SUMMARY
Macros
#define IPI_FLUSH_ALL 4
#define IPI_FLUSH_MULTIPLE 5
#define IPI_FLUSH_MULTIPLE_IMMEDIATE 1
#define IPI_FLUSH_PROCESS 2
#define IPI_FLUSH_SINGLE 3
#define IPI_INVALIDATE_ALL 7
#define IPI_PACKET_READY 6
#define IPI_REQUEST_SUMMARY 0xf
#define KiGetCurrentReadySummary() __readgsdword(FIELD_OFFSET(KPCR, Prcb.ReadySummary))
#define KiGetPdeIndex(va) ((((ULONG)(va)) >> PDI_SHIFT) & PDI_MASK)
#define KiGetPpeIndex(va) ((((ULONG)(va)) >> PPI_SHIFT) & PPI_MASK)
#define KiGetPteIndex(va) ((((ULONG)(va)) >> PTI_SHIFT) & PTI_MASK)
#define PDI_BITS 9
#define PDI_MASK ((1 << PDI_BITS) - 1)
#define PPI_BITS 2
#define PTI_BITS 9
#define PTI_MASK ((1 << PTI_BITS) - 1)
Typedefs
typedef struct _REQUEST_SUMMARY * PREQUEST_SUMMARY
typedef struct _REQUEST_SUMMARY REQUEST_SUMMARY
Functions
typedef DECLSPEC_ALIGN (16) struct _UNEXPECTED_INTERRUPT
VOID KiAcquireSpinLockCheckForFreeze (IN PKSPIN_LOCK SpinLock, IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
VOID KiAlignmentFault (VOID)
VOID KiApcInterrupt (VOID)
VOID KiBoundFault (VOID)
VOID KiBreakpointTrap (VOID)
FORCEINLINE BOOLEAN KiCheckForFreezeExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
VOID KiDebugServiceTrap (VOID)
VOID KiDebugTrapOrFault (VOID)
ULONG KiDivide6432 (ULONG64 Dividend, ULONG Divisor)
VOID KiDivideErrorFault (VOID)
VOID KiDoubleFaultAbort (VOID)
VOID KiDpcInterrupt (VOID)
VOID KiFloatingErrorFault (VOID)
VOID KiFreezeInterrupt (VOID)
VOID KiGeneralProtectionFault (VOID)
FORCEINLINE ULONG64 KiGetActualStackLimit (IN PKTHREAD Thread)
VOID KiInitializeBootStructures (PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID KiInterruptDispatchLBControl (VOID)
VOID KiInterruptDispatchNoEOI (VOID)
VOID KiInterruptDispatchNoLock (VOID)
VOID KiInvalidOpcodeFault (VOID)
VOID KiInvalidTssFault (VOID)
VOID KiIpiInterrupt (VOID)
VOID KiIpiProcessRequests (VOID)
PKAFFINITY KiIpiSendRequest (IN KAFFINITY TargetSet, IN ULONG64 Parameter, IN ULONG64 Count, IN ULONG64 RequestType)
__forceinline VOID KiIpiWaitForRequestBarrier (KAFFINITY volatile *Barrier)
VOID KiMcheckAbort (VOID)
VOID KiNmiInterrupt (VOID)
VOID KiNpxNotAvailableFault (VOID)
VOID KiNpxSegmentOverrunAbort (VOID)
VOID KiOverflowTrap (VOID)
VOID KiPageFault (VOID)
VOID KiRaiseAssertion (VOID)
VOID KiSaveInitialProcessorControlState (IN PKPROCESSOR_STATE ProcessorState)
VOID KiSecondaryClockInterrupt (VOID)
VOID KiSegmentNotPresentFault (VOID)
VOID KiSetPageAttributesTable (VOID)
VOID KiStackFault (VOID)
VOID KiStartSystemThread (VOID)
VOID KiStartUserThread (VOID)
VOID KiStartUserThreadReturn (VOID)
__forceinline BOOLEAN KiSwapProcess (IN PKPROCESS NewProcess, IN PKPROCESS OldProcess)
VOID KiSystemCall32 (VOID)
VOID KiSystemCall64 (VOID)
VOID KiWaitForReboot (VOID)
VOID KiXmmException (VOID)
PXMM_SAVE_AREA32 KxContextToKframes (IN OUT PKTRAP_FRAME TrapFrame, IN OUT PKEXCEPTION_FRAME ExceptionFrame, IN PCONTEXT ContextRecord, IN ULONG ContextFlags, IN KPROCESSOR_MODE PreviousMode)
Variables
ULONG KeAmd64MachineType
ULONG KiLogicalProcessors
ULONG KiMxCsrMask
KSPIN_LOCK KiNMILock
ULONG KiPhysicalProcessors
UCHAR KiPrefetchRetry
KIRQL KiProfileIrql
BOOLEAN KiResumeForReboot
ULONG64 KiTestDividend
UNEXPECTED_INTERRUPT KxUnexpectedInterrupt0 [256]
* PUNEXPECTED_INTERRUPT
UNEXPECTED_INTERRUPT
Macro Definition Documentation
#define IPI_FLUSH_ALL 4
Definition at line 34 of file kiamd64.h.
Referenced by KiIpiProcessRequests(), and KxFlushEntireTb().
#define IPI_FLUSH_MULTIPLE 5
Definition at line 35 of file kiamd64.h.
Referenced by KeFlushMultipleTb(), KiIpiProcessRequests(), and KiIpiSendRequest().
#define IPI_FLUSH_MULTIPLE_IMMEDIATE 1
Definition at line 31 of file kiamd64.h.
Referenced by KiIpiProcessRequests(), and KiIpiSendRequest().
#define IPI_FLUSH_PROCESS 2
Definition at line 32 of file kiamd64.h.
Referenced by KeFlushProcessTb(), and KiIpiProcessRequests().
#define IPI_FLUSH_SINGLE 3
Definition at line 33 of file kiamd64.h.
Referenced by KeFlushSingleTb(), KeStartAllProcessors(), and KiIpiProcessRequests().
#define IPI_INVALIDATE_ALL 7
Definition at line 37 of file kiamd64.h.
Referenced by KeInvalidateAllCaches(), and KiIpiProcessRequests().
#define IPI_PACKET_READY 6
Definition at line 36 of file kiamd64.h.
Referenced by KiIpiProcessRequests(), KiIpiSendPacket(), and KiIpiSendRequest().
#define IPI_REQUEST_SUMMARY 0xf
Definition at line 39 of file kiamd64.h.
#define KiGetCurrentReadySummary () __readgsdword(FIELD_OFFSET(KPCR, Prcb.ReadySummary))
Definition at line 60 of file kiamd64.h.
Referenced by NtYieldExecution().
#define KiGetPdeIndex (va) ((((ULONG)(va)) >> PDI_SHIFT) & PDI_MASK)
Definition at line 521 of file kiamd64.h.
Referenced by Ki386MapAddress().
#define KiGetPpeIndex (va) ((((ULONG)(va)) >> PPI_SHIFT) & PPI_MASK)
Definition at line 520 of file kiamd64.h.
Referenced by Ki386MapAddress().
#define KiGetPteIndex (va) ((((ULONG)(va)) >> PTI_SHIFT) & PTI_MASK)
Definition at line 522 of file kiamd64.h.
Referenced by Ki386MapAddress().
#define PDI_BITS 9
Definition at line 514 of file kiamd64.h.
#define PDI_MASK ((1 << PDI_BITS) - 1)
Definition at line 517 of file kiamd64.h.
#define PPI_BITS 2
Definition at line 513 of file kiamd64.h.
Referenced by Ki386CreateIdentityMap().
#define PTI_BITS 9
Definition at line 515 of file kiamd64.h.
#define PTI_MASK ((1 << PTI_BITS) - 1)
Definition at line 518 of file kiamd64.h.
Typedef Documentation
typedef struct _REQUEST_SUMMARY * PREQUEST_SUMMARY
typedef struct _REQUEST_SUMMARY REQUEST_SUMMARY
Function Documentation
typedef DECLSPEC_ALIGN (16)
Definition at line 502 of file kiamd64.h.
VOID KiAcquireSpinLockCheckForFreeze (IN PKSPIN_LOCK SpinLock, IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 23 of file spinlock.c.
References FALSE, KiCheckForFreezeExecution(), KxTryToAcquireSpinLock(), TRUE, and UNREFERENCED_PARAMETER.
Referenced by KiProcessNMI().
VOID KiAlignmentFault (VOID)
VOID KiApcInterrupt (VOID)
VOID KiBoundFault (VOID)
VOID KiBreakpointTrap (VOID)
FORCEINLINE BOOLEAN KiCheckForFreezeExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 412 of file kiamd64.h.
References FALSE, _KPRCB::IpiFrozen, KeGetCurrentPrcb(), KiFreezeTargetExecution(), KiResumeForReboot, KiWaitForReboot(), and TRUE.
Referenced by KiAcquireSpinLockCheckForFreeze(), and KiProcessNMI().
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
Definition at line 821 of file exceptn.c.
VOID KiDebugServiceTrap (VOID)
VOID KiDebugTrapOrFault (VOID)
ULONG KiDivide6432 (ULONG64 Dividend, ULONG Divisor)
Referenced by KiInitMachineDependent().
VOID KiDivideErrorFault (VOID)
VOID KiDoubleFaultAbort (VOID)
VOID KiDpcInterrupt (VOID)
VOID KiFloatingErrorFault (VOID)
VOID KiFreezeInterrupt (VOID)
VOID KiGeneralProtectionFault (VOID)
FORCEINLINE ULONG64 KiGetActualStackLimit (IN PKTHREAD Thread)
Definition at line 95 of file kiamd64.h.
VOID KiInitializeBootStructures (PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 750 of file initkr.c.
References AFFINITY_MASK, _KAPC_STATE::ApcListHead, _KTHREAD::ApcState, _KPRCB::BuildType, _KPRCB::CurrentThread, _KPRCB::DpcStack, _KI_INTINIT_REC::Dpl, ExInitPoolLookasidePointers(), FALSE, HalInitializeProcessor(), _KI_INTINIT_REC::Handler, _KPRCB::IdleThread, Index, InitializeListHead(), _KI_INTINIT_REC::IstIndex, KeActiveProcessors, KeFindFirstSetLeftMember(), KeGetCurrentPrcb(), KeGetPcr(), KeNumberProcessors, KernelMode, _LOADER_PARAMETER_BLOCK::KernelStack, KiApicMask, KiComputeIopmOffset, KiInitializeIdtEntry, KiInitialProcess, KiInitialThread, KiInitSpinLocks(), KiInterruptInitTable, KiLogicalProcessors, KiPhysicalProcessors, KiProcessorBlock, KiSaveInitialProcessorControlState(), KiSecondaryClockInterrupt(), KiSetFeatureBits(), KiSystemCall32(), KiSystemCall64(), KiUnexpectedInterrupt(), _KPRCB::LogicalProcessorsPerPhysicalProcessor, _KPRCB::MajorVersion, _KPCR::MajorVersion, MAXIMUM_IDTVECTOR, _KPRCB::MinorVersion, _KPCR::MinorVersion, _KPRCB::NextThread, NULL, _KPRCB::Number, PCR_MAJOR_VERSION, PCR_MINOR_VERSION, _KPCR::Prcb, PRCB_BUILD_DEBUG, PRCB_BUILD_UNIPROCESSOR, PRCB_MAJOR_VERSION, PRCB_MINOR_VERSION, _LOADER_PARAMETER_BLOCK::Process, _KAPC_STATE::Process, _KPRCB::ProcessorState, PUNEXPECTED_INTERRUPT, RPL_MASK, RTL_SIZEOF_THROUGH_FIELD, _KPRCB::SetMember, _LOADER_PARAMETER_BLOCK::Thread, UNEXPECTED_INTERRUPT, and _KI_INTINIT_REC::Vector.
VOID KiInterruptDispatchLBControl (VOID)
Referenced by KeInitializeInterrupt().
VOID KiInterruptDispatchNoEOI (VOID)
VOID KiInterruptDispatchNoLock (VOID)
Referenced by KeInitializeInterrupt().
VOID KiInvalidOpcodeFault (VOID)
VOID KiInvalidTssFault (VOID)
VOID KiIpiInterrupt (VOID)
VOID KiIpiProcessRequests (VOID)
Definition at line 142 of file ipi.c.
References AFFINITY_MASK, ASSERT, _REQUEST_SUMMARY::Count, _KPRCB::CurrentPacket, FALSE, IPI_FLUSH_ALL, IPI_FLUSH_MULTIPLE, IPI_FLUSH_MULTIPLE_IMMEDIATE, IPI_FLUSH_PROCESS, IPI_FLUSH_SINGLE, IPI_INVALIDATE_ALL, IPI_PACKET_READY, _REQUEST_SUMMARY::IpiRequest, _REQUEST_SUMMARY::IpiSynchType, KeFlushCurrentTb(), KeGetCurrentPrcb(), KiFlushProcessTb(), KiFlushSingleTb(), KiProcessorBlock, _KPRCB::PacketBarrier, _REQUEST_SUMMARY::Parameter, ReadForWriteAccess, SetMember, _KPRCB::SetMember, _REQUEST_SUMMARY::Summary, and _KPRCB::TargetSet.
PKAFFINITY KiIpiSendRequest (IN KAFFINITY TargetSet, IN ULONG64 Parameter, IN ULONG64 Count, IN ULONG64 RequestType)
Definition at line 323 of file ipi.c.
References AFFINITY_MASK, ASSERT, Count, _REQUEST_SUMMARY::Count, DISPATCH_LEVEL, FALSE, HalRequestIpi(), IPI_FLUSH_MULTIPLE, IPI_FLUSH_MULTIPLE_IMMEDIATE, IPI_PACKET_READY, _REQUEST_SUMMARY::IpiRequest, _REQUEST_SUMMARY::IpiSynchType, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeYieldProcessor, KiProcessorBlock, NULL, _KPRCB::Number, _KPRCB::PacketBarrier, _REQUEST_SUMMARY::Parameter, SetMember, _KPRCB::SetMember, _REQUEST_SUMMARY::Summary, _KPRCB::TargetSet, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeInvalidateAllCaches(), KeStartAllProcessors(), KiIpiSendPacket(), and KxFlushEntireTb().
__forceinline VOID KiIpiWaitForRequestBarrier (KAFFINITY volatile * Barrier)
Definition at line 267 of file kiamd64.h.
References KeYieldProcessor.
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeInvalidateAllCaches(), and KxFlushEntireTb().
VOID KiMcheckAbort (VOID)
VOID KiNmiInterrupt (VOID)
VOID KiNpxNotAvailableFault (VOID)
VOID KiNpxSegmentOverrunAbort (VOID)
VOID KiOverflowTrap (VOID)
VOID KiPageFault (VOID)
VOID KiRaiseAssertion (VOID)
VOID KiSaveInitialProcessorControlState (IN PKPROCESSOR_STATE ProcessorState)
Referenced by KiInitializeBootStructures().
VOID KiSecondaryClockInterrupt (VOID)
Referenced by KiInitializeBootStructures().
VOID KiSegmentNotPresentFault (VOID)
VOID KiSetPageAttributesTable (VOID)
Definition at line 24 of file pat.c.
References PAT_TYPE_STRONG_UC, PAT_TYPE_USWC, PAT_TYPE_WB, and PAT_TYPE_WEAK_UC.
Referenced by KeRestoreProcessorSpecificFeatures(), and KiInitializeKernel().
VOID KiStackFault (VOID)
VOID KiStartSystemThread (VOID)
Referenced by KiInitializeContextThread().
VOID KiStartUserThread (VOID)
Referenced by KiInitializeContextThread().
VOID KiStartUserThreadReturn (VOID)
Referenced by KiInitializeContextThread().
__forceinline BOOLEAN KiSwapProcess (IN PKPROCESS NewProcess, IN PKPROCESS OldProcess)
Definition at line 337 of file kiamd64.h.
References ASSERT, KeGetCurrentPrcb(), SetMember, _KPRCB::SetMember, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeDetachProcess(), KeUnstackDetachProcess(), and KiAttachProcess().
VOID KiSystemCall32 (VOID)
Referenced by KiInitializeBootStructures().
VOID KiSystemCall64 (VOID)
Referenced by KiInitializeBootStructures().
VOID KiWaitForReboot (VOID)
Definition at line 215 of file misc.c.
References NOTHING, and TRUE.
Referenced by KiCheckForFreezeExecution().
VOID KiXmmException (VOID)
PXMM_SAVE_AREA32 KxContextToKframes (IN OUT PKTRAP_FRAME TrapFrame, IN OUT PKEXCEPTION_FRAME ExceptionFrame, IN PCONTEXT ContextRecord, IN ULONG ContextFlags, IN KPROCESSOR_MODE PreviousMode)
Variable Documentation
ULONG KeAmd64MachineType
ULONG KiLogicalProcessors
Definition at line 42 of file initkr.c.
Referenced by KeStartAllProcessors(), KiInitializeBootStructures(), and KiInitializeKernel().
ULONG KiMxCsrMask
Definition at line 55 of file initkr.c.
Referenced by KiInitializeKernel().
KSPIN_LOCK KiNMILock
Referenced by KiProcessNMI().
ULONG KiPhysicalProcessors
Definition at line 43 of file initkr.c.
Referenced by KiInitializeBootStructures(), and KiInitializeKernel().
UCHAR KiPrefetchRetry
Definition at line 65 of file initkr.c.
Referenced by KeStartAllProcessors(), and KiSetProcessorType().
KIRQL KiProfileIrql
Definition at line 28 of file initkr.c.
BOOLEAN KiResumeForReboot
Referenced by KeBugCheck2(), and KiCheckForFreezeExecution().
ULONG64 KiTestDividend
Referenced by KiInitMachineDependent().
UNEXPECTED_INTERRUPT KxUnexpectedInterrupt0[256]
Definition at line 124 of file initkr.c.
Referenced by KeConnectInterrupt(), and KeDisconnectInterrupt().
* PUNEXPECTED_INTERRUPT
Definition at line 508 of file kiamd64.h.
Referenced by KiInitializeBootStructures().
UNEXPECTED_INTERRUPT
Definition at line 508 of file kiamd64.h.
Referenced by KiInitializeBootStructures().