Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obsdata.c File Reference
obsdata.c File Reference
#include "obp.h"
Data Structures
struct _OB_SD_CACHE_LIST
Macros
#define IF_OB_GLOBAL(FlagName) if (FALSE)
#define ObPrint(FlagName, _Text_) ;
#define OBS_DEBUG_ALLOC_TRACKING ((ULONG) 0x00000001L)
#define OBS_DEBUG_BREAK_ON_INIT ((ULONG) 0x00000004L)
#define OBS_DEBUG_CACHE_FREES ((ULONG) 0x00000002L)
#define OBS_DEBUG_SHOW_COLLISIONS ((ULONG) 0x00000008L)
#define OBS_DEBUG_SHOW_DEASSIGN ((ULONG) 0x00000040L)
#define OBS_DEBUG_SHOW_HEADER_FREE ((ULONG) 0x00000100L)
#define OBS_DEBUG_SHOW_REFERENCES ((ULONG) 0x00000020L)
#define OBS_DEBUG_SHOW_STATISTICS ((ULONG) 0x00000010L)
#define OBS_DEBUG_STOP_INVALID_DESCRIPTOR ((ULONG) 0x00000080L)
Typedefs
typedef struct _OB_SD_CACHE_LIST OB_SD_CACHE_LIST
typedef struct _OB_SD_CACHE_LIST * POB_SD_CACHE_LIST
Functions
NTSTATUS ObDeassignSecurity (IN OUT PSECURITY_DESCRIPTOR *pSecurityDescriptor)
VOID ObDereferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
NTSTATUS ObLogSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __out PSECURITY_DESCRIPTOR *OutputSecurityDescriptor, __in ULONG RefBias)
BOOLEAN ObpCompareSecurityDescriptors (IN PSECURITY_DESCRIPTOR SD1, IN ULONG Length1, IN PSECURITY_DESCRIPTOR SD2)
PSECURITY_DESCRIPTOR_HEADER ObpCreateCacheEntry (PSECURITY_DESCRIPTOR InputSecurityDescriptor, ULONG SecurityDescriptorLength, ULONG FullHash, ULONG RefBias)
PVOID ObpDestroySecurityDescriptorHeader (IN PSECURITY_DESCRIPTOR_HEADER Header)
ULONG ObpHashBuffer (PVOID Data, ULONG Length)
ULONG ObpHashSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Length)
NTSTATUS ObpInitSecurityDescriptorCache (VOID)
PSECURITY_DESCRIPTOR ObpReferenceSecurityDescriptor (POBJECT_HEADER ObjectHeader)
VOID ObReferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
Variables
OB_SD_CACHE_LIST ObsSecurityDescriptorCache [SECURITY_DESCRIPTOR_CACHE_ENTRIES]
Macro Definition Documentation
#define IF_OB_GLOBAL (FlagName) if (FALSE)
Definition at line 59 of file obsdata.c.
Referenced by ObpInitSecurityDescriptorCache(), and ObpReferenceSecurityDescriptor().
#define ObPrint (FlagName, _Text_) ;
Definition at line 65 of file obsdata.c.
Referenced by ObDeassignSecurity(), ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), ObpDestroySecurityDescriptorHeader(), ObpReferenceSecurityDescriptor(), and ObReferenceSecurityDescriptor().
#define OBS_DEBUG_ALLOC_TRACKING ((ULONG) 0x00000001L)
Definition at line 77 of file obsdata.c.
#define OBS_DEBUG_BREAK_ON_INIT ((ULONG) 0x00000004L)
Definition at line 79 of file obsdata.c.
#define OBS_DEBUG_CACHE_FREES ((ULONG) 0x00000002L)
Definition at line 78 of file obsdata.c.
#define OBS_DEBUG_SHOW_COLLISIONS ((ULONG) 0x00000008L)
Definition at line 80 of file obsdata.c.
#define OBS_DEBUG_SHOW_DEASSIGN ((ULONG) 0x00000040L)
Definition at line 83 of file obsdata.c.
#define OBS_DEBUG_SHOW_HEADER_FREE ((ULONG) 0x00000100L)
Definition at line 85 of file obsdata.c.
#define OBS_DEBUG_SHOW_REFERENCES ((ULONG) 0x00000020L)
Definition at line 82 of file obsdata.c.
#define OBS_DEBUG_SHOW_STATISTICS ((ULONG) 0x00000010L)
Definition at line 81 of file obsdata.c.
#define OBS_DEBUG_STOP_INVALID_DESCRIPTOR ((ULONG) 0x00000080L)
Definition at line 84 of file obsdata.c.
Typedef Documentation
typedef struct _OB_SD_CACHE_LIST OB_SD_CACHE_LIST
typedef struct _OB_SD_CACHE_LIST * POB_SD_CACHE_LIST
Function Documentation
NTSTATUS ObDeassignSecurity (IN OUT PSECURITY_DESCRIPTOR * pSecurityDescriptor)
Definition at line 660 of file obsdata.c.
References ExFastRefGetObject(), ExFastRefGetUnusedReferences(), NULL, ObDereferenceSecurityDescriptor(), ObPrint, and STATUS_SUCCESS.
Referenced by SepDefaultDeleteMethod(), and WmipSecurityMethod().
VOID ObDereferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
Definition at line 702 of file obsdata.c.
References ASSERT, ExAcquirePushLockExclusive(), ExFreePool(), ExReleasePushLockExclusive(), _SECURITY_DESCRIPTOR_HEADER::FullHash, InterlockedCompareExchange(), InterlockedExchangeAdd(), KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), ObpDestroySecurityDescriptorHeader(), ObPrint, PsGetCurrentThread(), _OB_SD_CACHE_LIST::PushLock, _SECURITY_DESCRIPTOR_HEADER::RefCount, SD_TO_SD_HEADER, SECURITY_DESCRIPTOR_CACHE_ENTRIES, and _ETHREAD::Tcb.
Referenced by IopCompleteUnloadOrDelete(), IopGetSetSecurityObject(), IopSetDeviceSecurityDescriptor(), ObDeassignSecurity(), ObQuerySecurityDescriptorInfo(), ObReleaseObjectSecurity(), and ObSetSecurityDescriptorInfo().
NTSTATUS ObLogSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __out PSECURITY_DESCRIPTOR * OutputSecurityDescriptor, __in ULONG RefBias)
Definition at line 276 of file obsdata.c.
References ExAcquirePushLockExclusive(), ExAcquirePushLockShared(), ExFreePool(), ExReleasePushLock(), ExReleasePushLockExclusive(), ExReleasePushLockShared(), FALSE, _LIST_ENTRY::Flink, _SECURITY_DESCRIPTOR_HEADER::FullHash, _OB_SD_CACHE_LIST::Head, InsertTailList(), InterlockedExchangeAdd(), InterlockedIncrement, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _SECURITY_DESCRIPTOR_HEADER::Link, LINK_TO_SD_HEADER, NULL, ObpCompareSecurityDescriptors(), ObpCreateCacheEntry(), ObpHashSecurityDescriptor(), ObPrint, PsGetCurrentThread(), _OB_SD_CACHE_LIST::PushLock, _SECURITY_DESCRIPTOR_HEADER::RefCount, RtlLengthSecurityDescriptor(), SECURITY_DESCRIPTOR_CACHE_ENTRIES, _SECURITY_DESCRIPTOR_HEADER::SecurityDescriptor, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by IopGetSetSecurityObject(), IopSetDeviceSecurityDescriptor(), ObAssignObjectSecurityDescriptor(), and ObSetSecurityDescriptorInfo().
BOOLEAN ObpCompareSecurityDescriptors (IN PSECURITY_DESCRIPTOR SD1, IN ULONG Length1, IN PSECURITY_DESCRIPTOR SD2)
Definition at line 851 of file obsdata.c.
References ASSERT, FALSE, RtlEqualMemory, and RtlLengthSecurityDescriptor().
Referenced by ObLogSecurityDescriptor().
PSECURITY_DESCRIPTOR_HEADER ObpCreateCacheEntry (PSECURITY_DESCRIPTOR InputSecurityDescriptor, ULONG SecurityDescriptorLength, ULONG FullHash, ULONG RefBias)
Definition at line 459 of file obsdata.c.
References ASSERT, ExAllocatePoolWithTag, NULL, PagedPool, RtlCopyMemory, and RtlLengthSecurityDescriptor().
Referenced by ObLogSecurityDescriptor().
PVOID ObpDestroySecurityDescriptorHeader (IN PSECURITY_DESCRIPTOR_HEADER Header)
Definition at line 802 of file obsdata.c.
References ASSERT, InterlockedDecrement, ObPrint, and RemoveEntryList().
Referenced by ObDereferenceSecurityDescriptor().
ULONG ObpHashBuffer (PVOID Data, ULONG Length)
Definition at line 210 of file obsdata.c.
References _rotl().
Referenced by ObpHashSecurityDescriptor().
ULONG ObpHashSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Length)
Definition at line 178 of file obsdata.c.
References ObpHashBuffer().
Referenced by ObLogSecurityDescriptor().
NTSTATUS ObpInitSecurityDescriptorCache (VOID)
Definition at line 133 of file obsdata.c.
References DbgBreakPoint(), ExInitializePushLock(), IF_OB_GLOBAL, InitializeListHead(), SECURITY_DESCRIPTOR_CACHE_ENTRIES, and STATUS_SUCCESS.
Referenced by ObInitSystem().
PSECURITY_DESCRIPTOR ObpReferenceSecurityDescriptor (POBJECT_HEADER ObjectHeader)
Definition at line 564 of file obsdata.c.
References DbgBreakPoint(), ExFastRefAddAdditionalReferenceCounts(), ExFastReference(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefGetUnusedReferences(), _SECURITY_DESCRIPTOR_HEADER::FullHash, IF_OB_GLOBAL, InterlockedExchangeAdd(), InterlockedIncrement, NULL, ObpLockObjectShared, ObPrint, ObpUnlockObject, _SECURITY_DESCRIPTOR_HEADER::RefCount, RtlValidSecurityDescriptor(), SD_TO_SD_HEADER, and _OBJECT_HEADER::SecurityDescriptor.
Referenced by ObGetObjectSecurity(), ObQuerySecurityDescriptorInfo(), and ObSetSecurityDescriptorInfo().
VOID ObReferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
Definition at line 529 of file obsdata.c.
References _SECURITY_DESCRIPTOR_HEADER::FullHash, InterlockedExchangeAdd(), ObPrint, _SECURITY_DESCRIPTOR_HEADER::RefCount, and SD_TO_SD_HEADER.
Referenced by IopGetSetSecurityObject(), and IopSetDeviceSecurityDescriptor().
Variable Documentation
OB_SD_CACHE_LIST ObsSecurityDescriptorCache[SECURITY_DESCRIPTOR_CACHE_ENTRIES]
Definition at line 102 of file obsdata.c.