Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/stdlib.h File Reference
stdlib.h File Reference
Data Structures
struct _div_t
struct _ldiv_t
Macros
#define __cdecl
#define __max(a, b) (((a) > (b)) ? (a) : (b))
#define __min(a, b) (((a) < (b)) ? (a) : (b))
#define _CRTIMP
#define _CRTNOALIAS
#define _CRTRESTRICT
#define _DIV_T_DEFINED
#define _INC_STDLIB
#define _MAX_DIR 256 /* max. length of path component */
#define _MAX_DRIVE 3 /* max. length of drive component */
#define _MAX_EXT 256 /* max. length of extension component */
#define _MAX_FNAME 256 /* max. length of file name component */
#define _MAX_PATH 260 /* max. length of full pathname */
#define _ONEXIT_T_DEFINED
#define _OUT_TO_DEFAULT 0
#define _OUT_TO_MSGBOX 2
#define _OUT_TO_STDERR 1
#define _REPORT_ERRMODE 3
#define _SECERR_BUFFER_OVERRUN 1 /* void* arg ignored */
#define _SIZE_T_DEFINED
#define _W64
#define _WCHAR_T_DEFINED
#define _WSTDLIB_DEFINED
#define _WSTDLIBP_DEFINED
#define environ _environ
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define max(a, b) (((a) > (b)) ? (a) : (b))
#define MB_CUR_MAX __mb_cur_max
#define min(a, b) (((a) < (b)) ? (a) : (b))
#define NULL ((void *)0)
#define onexit_t _onexit_t
#define RAND_MAX 0x7fff
#define sys_errlist _sys_errlist
#define sys_nerr _sys_nerr
Typedefs
typedef int(__cdecl * _onexit_t) (void)
typedef void(__cdecl * _purecall_handler) (void)
typedef void(__cdecl * _secerr_handler_func) (int, void *)
typedef struct _div_t div_t
typedef struct _ldiv_t ldiv_t
typedef _W64 unsigned int size_t
typedef unsigned short wchar_t
Functions
_CRTIMP int __cdecl ___mb_cur_max_func (void)
__int64 __cdecl _abs64 (__int64)
_CRTIMP void __cdecl _beep (unsigned, unsigned)
unsigned __int64 __cdecl _byteswap_uint64 (unsigned __int64)
unsigned long __cdecl _byteswap_ulong (unsigned long)
unsigned short __cdecl _byteswap_ushort (unsigned short)
_CRTIMP char *__cdecl _ecvt (double, int, int *, int *)
_CRTIMP void __cdecl _exit (int)
_CRTIMP char *__cdecl _fcvt (double, int, int *, int *)
_CRTIMP char *__cdecl _fullpath (char *, const char *, size_t)
_CRTIMP char *__cdecl _gcvt (double, int, char *)
_CRTIMP char *__cdecl _itoa (int, char *, int)
_CRTIMP wchar_t *__cdecl _itow (int, wchar_t *, int)
unsigned long __cdecl _lrotl (unsigned long, int)
unsigned long __cdecl _lrotr (unsigned long, int)
_CRTIMP char *__cdecl _ltoa (long, char *, int)
_CRTIMP wchar_t *__cdecl _ltow (long, wchar_t *, int)
_CRTIMP void __cdecl _makepath (char *, const char *, const char *, const char *, const char *)
_CRTIMP size_t __cdecl _mbstrlen (const char *s)
_onexit_t __cdecl _onexit (_onexit_t)
_CRTIMP int __cdecl _putenv (const char *)
unsigned int __cdecl _rotl (unsigned int, int)
unsigned __int64 __cdecl _rotl64 (unsigned __int64, int)
unsigned int __cdecl _rotr (unsigned int, int)
unsigned __int64 __cdecl _rotr64 (unsigned __int64, int)
_CRTIMP void __cdecl _searchenv (const char *, const char *, char *)
_CRTIMP int __cdecl _set_error_mode (int)
_CRTIMP _purecall_handler __cdecl _set_purecall_handler (_purecall_handler)
_CRTIMP _secerr_handler_func __cdecl _set_security_error_handler (_secerr_handler_func)
_CRTIMP void __cdecl _seterrormode (int)
_CRTIMP void __cdecl _sleep (unsigned long)
_CRTIMP void __cdecl _splitpath (const char *, char *, char *, char *, char *)
_CRTIMP void __cdecl _swab (char *, char *, int)
_CRTIMP char *__cdecl _ultoa (unsigned long, char *, int)
_CRTIMP wchar_t *__cdecl _ultow (unsigned long, wchar_t *, int)
_CRTIMP wchar_t *__cdecl _wfullpath (wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl _wgetenv (const wchar_t *)
_CRTIMP void __cdecl _wmakepath (wchar_t *, const wchar_t *, const wchar_t *, const wchar_t *, const wchar_t *)
_CRTIMP void __cdecl _wperror (const wchar_t *)
_CRTIMP int __cdecl _wputenv (const wchar_t *)
_CRTIMP void __cdecl _wsearchenv (const wchar_t *, const wchar_t *, wchar_t *)
_CRTIMP void __cdecl _wsplitpath (const wchar_t *, wchar_t *, wchar_t *, wchar_t *, wchar_t *)
_CRTIMP int __cdecl _wsystem (const wchar_t *)
_CRTIMP double __cdecl _wtof (const wchar_t *)
_CRTIMP int __cdecl _wtoi (const wchar_t *)
_CRTIMP long __cdecl _wtol (const wchar_t *)
_CRTIMP void __cdecl abort (void)
int __cdecl abs (int)
int __cdecl atexit (void(__cdecl *)(void))
_CRTIMP double __cdecl atof (const char *)
_CRTIMP int __cdecl atoi (const char *)
_CRTIMP long __cdecl atol (const char *)
_CRTIMP void *__cdecl bsearch (const void *, const void *, size_t, size_t, int(__cdecl *)(const void *, const void *))
_CRTIMP _CRTNOALIAS _CRTRESTRICT void *__cdecl calloc (size_t, size_t)
_CRTIMP div_t __cdecl div (int, int)
_CRTIMP char *__cdecl ecvt (double, int, int *, int *)
_CRTIMP void __cdecl exit (int)
_CRTIMP char *__cdecl fcvt (double, int, int *, int *)
_CRTIMP _CRTNOALIAS void __cdecl free (void *)
_CRTIMP char *__cdecl gcvt (double, int, char *)
_CRTIMP char *__cdecl getenv (const char *)
_CRTIMP char *__cdecl itoa (int, char *, int)
long __cdecl labs (long)
_CRTIMP ldiv_t __cdecl ldiv (long, long)
_CRTIMP char *__cdecl ltoa (long, char *, int)
_CRTIMP _CRTNOALIAS _CRTRESTRICT void *__cdecl malloc (size_t)
_CRTIMP int __cdecl mblen (const char *, size_t)
_CRTIMP size_t __cdecl mbstowcs (wchar_t *, const char *, size_t)
_CRTIMP int __cdecl mbtowc (wchar_t *, const char *, size_t)
onexit_t __cdecl onexit (onexit_t)
_CRTIMP void __cdecl perror (const char *)
_CRTIMP int __cdecl putenv (const char *)
_CRTIMP void __cdecl qsort (void *, size_t, size_t, int(__cdecl *)(const void *, const void *))
_CRTIMP int __cdecl rand (void)
_CRTIMP _CRTNOALIAS _CRTRESTRICT void *__cdecl realloc (void *, size_t)
_CRTIMP void __cdecl srand (unsigned int)
_CRTIMP double __cdecl strtod (const char *, char **)
_CRTIMP long __cdecl strtol (const char *, char **, int)
_CRTIMP unsigned long __cdecl strtoul (const char *, char **, int)
_CRTIMP void __cdecl swab (char *, char *, int)
_CRTIMP int __cdecl system (const char *)
_CRTIMP int __cdecl tolower (int)
_CRTIMP int __cdecl toupper (int)
_CRTIMP char *__cdecl ultoa (unsigned long, char *, int)
_CRTIMP double __cdecl wcstod (const wchar_t *, wchar_t **)
_CRTIMP long __cdecl wcstol (const wchar_t *, wchar_t **, int)
_CRTIMP size_t __cdecl wcstombs (char *, const wchar_t *, size_t)
_CRTIMP unsigned long __cdecl wcstoul (const wchar_t *, wchar_t **, int)
_CRTIMP int __cdecl wctomb (char *, wchar_t)
Variables
_CRTIMP int __argc
_CRTIMP char ** __argv
_CRTIMP int __mb_cur_max
_CRTIMP wchar_t ** __wargv
_CRTIMP unsigned long _doserrno
_CRTIMP char ** _environ
_CRTIMP int _fileinfo
_CRTIMP int _fmode
_CRTIMP unsigned int _osplatform
_CRTIMP unsigned int _osver
_CRTIMP char * _pgmptr
_CRTIMP char * _sys_errlist []
_CRTIMP int _sys_nerr
_CRTIMP wchar_t ** _wenviron
_CRTIMP unsigned int _winmajor
_CRTIMP unsigned int _winminor
_CRTIMP unsigned int _winver
_CRTIMP wchar_t * _wpgmptr
_CRTIMP int errno
Macro Definition Documentation
#define __cdecl
Definition at line 90 of file stdlib.h.
#define __max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 175 of file stdlib.h.
#define __min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 176 of file stdlib.h.
#define _CRTIMP
Definition at line 59 of file stdlib.h.
#define _CRTNOALIAS
Definition at line 78 of file stdlib.h.
#define _CRTRESTRICT
Definition at line 82 of file stdlib.h.
#define _DIV_T_DEFINED
Definition at line 151 of file stdlib.h.
#define _INC_STDLIB
Definition at line 30 of file stdlib.h.
#define _MAX_DIR 256 /* max. length of path component */
Definition at line 184 of file stdlib.h.
#define _MAX_DRIVE 3 /* max. length of drive component */
Definition at line 183 of file stdlib.h.
#define _MAX_EXT 256 /* max. length of extension component */
Definition at line 186 of file stdlib.h.
#define _MAX_FNAME 256 /* max. length of file name component */
Definition at line 185 of file stdlib.h.
#define _MAX_PATH 260 /* max. length of full pathname */
Definition at line 182 of file stdlib.h.
#define _ONEXIT_T_DEFINED
Definition at line 133 of file stdlib.h.
#define _OUT_TO_DEFAULT 0
Definition at line 191 of file stdlib.h.
#define _OUT_TO_MSGBOX 2
Definition at line 193 of file stdlib.h.
#define _OUT_TO_STDERR 1
Definition at line 192 of file stdlib.h.
#define _REPORT_ERRMODE 3
Definition at line 194 of file stdlib.h.
#define _SECERR_BUFFER_OVERRUN 1 /* void* arg ignored */
Definition at line 199 of file stdlib.h.
#define _SIZE_T_DEFINED
Definition at line 100 of file stdlib.h.
#define _W64
Definition at line 49 of file stdlib.h.
#define _WCHAR_T_DEFINED
Definition at line 106 of file stdlib.h.
#define _WSTDLIB_DEFINED
Definition at line 334 of file stdlib.h.
#define _WSTDLIBP_DEFINED
Definition at line 376 of file stdlib.h.
#define environ _environ
Definition at line 416 of file stdlib.h.
#define EXIT_FAILURE 1
Definition at line 124 of file stdlib.h.
#define EXIT_SUCCESS 0
Definition at line 123 of file stdlib.h.
#define max (a, b) (((a) > (b)) ? (a) : (b))
Definition at line 410 of file stdlib.h.
#define MB_CUR_MAX __mb_cur_max
Definition at line 167 of file stdlib.h.
#define min (a, b) (((a) < (b)) ? (a) : (b))
Definition at line 411 of file stdlib.h.
#define NULL ((void *)0)
Definition at line 116 of file stdlib.h.
#define onexit_t _onexit_t
Definition at line 131 of file stdlib.h.
#define RAND_MAX 0x7fff
Definition at line 157 of file stdlib.h.
#define sys_errlist _sys_errlist
Definition at line 414 of file stdlib.h.
#define sys_nerr _sys_nerr
Definition at line 415 of file stdlib.h.
Typedef Documentation
typedef int(__cdecl * _onexit_t) (void)
Definition at line 128 of file stdlib.h.
typedef void(__cdecl * _purecall_handler) (void)
Definition at line 203 of file stdlib.h.
typedef void(__cdecl * _secerr_handler_func) (int, void *)
Definition at line 200 of file stdlib.h.
typedef struct _div_t div_t
typedef struct _ldiv_t ldiv_t
typedef _W64 unsigned int size_t
Definition at line 98 of file stdlib.h.
typedef unsigned short wchar_t
Definition at line 105 of file stdlib.h.
Function Documentation
_CRTIMP int __cdecl ___mb_cur_max_func (void)
__int64 __cdecl _abs64 (__int64)
_CRTIMP void __cdecl _beep (unsigned , unsigned)
unsigned __int64 __cdecl _byteswap_uint64 (unsigned __int64)
unsigned long __cdecl _byteswap_ulong (unsigned long)
unsigned short __cdecl _byteswap_ushort (unsigned short)
_CRTIMP char* __cdecl _ecvt (double , int , int * , int *)
_CRTIMP void __cdecl _exit (int)
_CRTIMP char* __cdecl _fcvt (double , int , int * , int *)
_CRTIMP char* __cdecl _fullpath (char * , const char * , size_t)
_CRTIMP char* __cdecl _gcvt (double , int , char *)
_CRTIMP char* __cdecl _itoa (int , char * , int)
_CRTIMP wchar_t* __cdecl _itow (int , wchar_t * , int)
unsigned long __cdecl _lrotl (unsigned long, int)
unsigned long __cdecl _lrotr (unsigned long, int)
_CRTIMP char* __cdecl _ltoa (long , char * , int)
_CRTIMP wchar_t* __cdecl _ltow (long , wchar_t * , int)
_CRTIMP void __cdecl _makepath (char * , const char * , const char * , const char * , const char *)
_CRTIMP size_t __cdecl _mbstrlen (const char * s)
_onexit_t __cdecl _onexit (_onexit_t)
_CRTIMP int __cdecl _putenv (const char *)
unsigned int __cdecl _rotl (unsigned int, int)
Referenced by ObpHashBuffer().
unsigned __int64 __cdecl _rotl64 (unsigned __int64, int)
unsigned int __cdecl _rotr (unsigned int, int)
unsigned __int64 __cdecl _rotr64 (unsigned __int64, int)
_CRTIMP void __cdecl _searchenv (const char * , const char * , char *)
_CRTIMP int __cdecl _set_error_mode (int)
_CRTIMP _purecall_handler __cdecl _set_purecall_handler (_purecall_handler)
_CRTIMP _secerr_handler_func __cdecl _set_security_error_handler (_secerr_handler_func)
_CRTIMP void __cdecl _seterrormode (int)
_CRTIMP void __cdecl _sleep (unsigned long)
_CRTIMP void __cdecl _splitpath (const char * , char * , char * , char * , char *)
_CRTIMP void __cdecl _swab (char * , char * , int)
_CRTIMP char* __cdecl _ultoa (unsigned long, char * , int)
_CRTIMP wchar_t* __cdecl _ultow (unsigned long, wchar_t * , int)
_CRTIMP wchar_t* __cdecl _wfullpath (wchar_t * , const wchar_t * , size_t)
_CRTIMP wchar_t* __cdecl _wgetenv (const wchar_t *)
_CRTIMP void __cdecl _wmakepath (wchar_t * , const wchar_t * , const wchar_t * , const wchar_t * , const wchar_t *)
_CRTIMP void __cdecl _wperror (const wchar_t *)
_CRTIMP int __cdecl _wputenv (const wchar_t *)
_CRTIMP void __cdecl _wsearchenv (const wchar_t * , const wchar_t * , wchar_t *)
_CRTIMP void __cdecl _wsplitpath (const wchar_t * , wchar_t * , wchar_t * , wchar_t * , wchar_t *)
_CRTIMP int __cdecl _wsystem (const wchar_t *)
_CRTIMP double __cdecl _wtof (const wchar_t *)
_CRTIMP int __cdecl _wtoi (const wchar_t *)
Referenced by WmipFindISinGEbyName(), and WmipPrepareWnodeSI().
_CRTIMP long __cdecl _wtol (const wchar_t *)
_CRTIMP void __cdecl abort (void)
int __cdecl abs (int)
Referenced by KeSetBasePriorityThread(), and PerfInfoCalcHashValue().
int __cdecl atexit (void(__cdecl *)(void))
_CRTIMP double __cdecl atof (const char *)
_CRTIMP int __cdecl atoi (const char *)
_CRTIMP long __cdecl atol (const char *)
Referenced by ExpInitializeExecutive(), MmInitSystem(), and Phase1InitializationDiscard().
_CRTIMP void* __cdecl bsearch (const void * , const void * , size_t , size_t , int(__cdecl *)(const void *, const void *))
_CRTIMP _CRTNOALIAS _CRTRESTRICT void* __cdecl calloc (size_t , size_t)
_CRTIMP div_t __cdecl div (int , int)
_CRTIMP char* __cdecl ecvt (double , int , int * , int *)
_CRTIMP void __cdecl exit (int)
Referenced by CcWaitForUninitializeCacheMap(), IopInitializeBuiltinDriver(), ObSwapObjectNames(), and SepValidOwnerSubjectContext().
_CRTIMP char* __cdecl fcvt (double , int , int * , int *)
_CRTIMP _CRTNOALIAS void __cdecl free (void *)
_CRTIMP char* __cdecl gcvt (double , int , char *)
_CRTIMP char* __cdecl getenv (const char *)
_CRTIMP char* __cdecl itoa (int , char * , int)
long __cdecl labs (long)
_CRTIMP ldiv_t __cdecl ldiv (long , long)
_CRTIMP char* __cdecl ltoa (long , char * , int)
_CRTIMP _CRTNOALIAS _CRTRESTRICT void* __cdecl malloc (size_t)
_CRTIMP int __cdecl mblen (const char * , size_t)
_CRTIMP size_t __cdecl mbstowcs (wchar_t * , const char * , size_t)
_CRTIMP int __cdecl mbtowc (wchar_t * , const char * , size_t)
onexit_t __cdecl onexit (onexit_t)
_CRTIMP void __cdecl perror (const char *)
_CRTIMP int __cdecl putenv (const char *)
_CRTIMP void __cdecl qsort (void * , size_t , size_t , int(__cdecl *)(const void *, const void *))
_CRTIMP int __cdecl rand (void)
_CRTIMP _CRTNOALIAS _CRTRESTRICT void* __cdecl realloc (void * , size_t)
_CRTIMP void __cdecl srand (unsigned int)
_CRTIMP double __cdecl strtod (const char * , char **)
_CRTIMP long __cdecl strtol (const char * , char ** , int)
_CRTIMP unsigned long __cdecl strtoul (const char * , char ** , int)
_CRTIMP void __cdecl swab (char * , char * , int)
_CRTIMP int __cdecl system (const char *)
_CRTIMP int __cdecl tolower (int)
_CRTIMP int __cdecl toupper (int)
_CRTIMP char* __cdecl ultoa (unsigned long, char * , int)
_CRTIMP double __cdecl wcstod (const wchar_t * , wchar_t **)
_CRTIMP long __cdecl wcstol (const wchar_t * , wchar_t ** , int)
_CRTIMP size_t __cdecl wcstombs (char * , const wchar_t * , size_t)
_CRTIMP unsigned long __cdecl wcstoul (const wchar_t * , wchar_t ** , int)
_CRTIMP int __cdecl wctomb (char * , wchar_t)
Variable Documentation
_CRTIMP int __argc
_CRTIMP char** __argv
_CRTIMP int __mb_cur_max
_CRTIMP wchar_t** __wargv
_CRTIMP unsigned long _doserrno
_CRTIMP char** _environ
_CRTIMP int _fileinfo
_CRTIMP int _fmode
_CRTIMP unsigned int _osplatform
_CRTIMP unsigned int _osver
_CRTIMP char* _pgmptr
_CRTIMP char* _sys_errlist[]
_CRTIMP int _sys_nerr
_CRTIMP wchar_t** _wenviron
_CRTIMP unsigned int _winmajor
_CRTIMP unsigned int _winminor
_CRTIMP unsigned int _winver
_CRTIMP wchar_t* _wpgmptr
_CRTIMP int errno