Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psopen.c File Reference
psopen.c File Reference
#include "psp.h"
Functions
NTSTATUS NtOpenProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
NTSTATUS NtOpenThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
Function Documentation
NTSTATUS NtOpenProcess (__out PHANDLE ProcessHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
Definition at line 28 of file psopen.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForReadSmallStructure, ProbeForWriteHandle, PROCESS_ALL_ACCESS, PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsProcessType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_INVALID_PARAMETER_MIX, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, and UserMode.
NTSTATUS NtOpenThread (__out PHANDLE ThreadHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PCLIENT_ID ClientId)
Definition at line 272 of file psopen.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, Handle, KeGetPreviousMode, KernelMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObSanitizeHandleAttributes(), PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, ProbeForReadSmallStructure, ProbeForWriteHandle, PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PsProcessType, PsThreadType, _ACCESS_STATE::RemainingDesiredAccess, SeCreateAccessState(), SeDebugPrivilege, SeDeleteAccessState(), SeSinglePrivilegeCheck(), Status, STATUS_INVALID_PARAMETER_MIX, THREAD_ALL_ACCESS, TRUE, _OBJECT_TYPE::TypeInfo, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, and UserMode.