Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/ki.h File Reference
ki.h File Reference
#include "ntos.h"
#include "stdio.h"
#include "stdlib.h"
#include "wow64t.h"
#include "zwapi.h"
#include "i386\kix86.h"
Data Structures
struct _ALIGNED_SPINLOCK_STRUCT
struct _KAPC_RECORD
struct _KTIMER_TABLE_ENTRY
struct ADJUST_INTERRUPT_TIME_CONTEXT
Macros
#define ALERT_INCREMENT 2
#define BALANCE_INCREMENT 10
#define ClearMember(Member, Set) Set = Set & (~((ULONG_PTR)1 << (Member)))
#define FREEZE_OWNER 0x04
#define FrozenState(a) ((a) & 0xF)
#define IPI_APC 1
#define IPI_DPC 2
#define IPI_FREEZE 4
#define IPI_INSTRUMENT_COUNT(a, b)
#define IPI_PACKET_READY 8
#define IPI_SYNCH_REQUEST 16
#define KI_EXCEPTION_ACCESS_VIOLATION (KI_EXCEPTION_INTERNAL | 0x4)
#define KI_EXCEPTION_GP_FAULT (KI_EXCEPTION_INTERNAL | 0x1)
#define KI_EXCEPTION_INTEGER_DIVIDE_BY_ZERO (KI_EXCEPTION_INTERNAL | 0x3)
#define KI_EXCEPTION_INTERNAL 0x10000000
#define KI_EXCEPTION_INVALID_OP (KI_EXCEPTION_INTERNAL | 0x2)
#define KiDisableAlignmentExceptions()
#define KiEnableAlignmentExceptions()
#define KiIncrementSwitchCounter(Member)
#define KiQueryNxThunkEmulationState() KeGetCurrentThread()->ApcState.Process->Flags.DisableThunkEmulation
#define KiRequestApcInterrupt(Processor)
#define KiRequestDispatchInterrupt(Processor)
#define KiWaitSatisfyAny(_Object_, _Thread_)
#define KiWaitSatisfyMutant(_Object_, _Thread_)
#define KiWaitSatisfyOther(_Object_)
#define NIL (PVOID)NULL
#define RESUME_INCREMENT 0
#define RUNNING 0x00
#define SetMember(Member, Set) Set = Set | ((ULONG_PTR)1 << (Member))
#define TARGET_FROZEN 0x02
#define TARGET_THAW 0x03
#define TIME_CRITICAL_PRIORITY_BOUND 14
#define TIMER_EXPIRE_INCREMENT 0
Typedefs
typedef struct _ALIGNED_SPINLOCK_STRUCT ALIGNED_SPINLOCK_STRUCT
typedef struct _KAPC_RECORD KAPC_RECORD
typedef ULONG KIPI_REQUEST
typedef struct _KTIMER_TABLE_ENTRY KTIMER_TABLE_ENTRY
typedef struct ADJUST_INTERRUPT_TIME_CONTEXT * PADJUST_INTERRUPT_TIME_CONTEXT
typedef struct _ALIGNED_SPINLOCK_STRUCT * PALIGNED_SPINLOCK_STRUCT
typedef struct _KAPC_RECORD * PKAPC_RECORD
typedef struct _KTIMER_TABLE_ENTRY * PKTIMER_TABLE_ENTRY
Functions
VOID ExpInitializeExecutive (IN ULONG Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID ExpInterlockedPopEntrySListEnd (VOID)
VOID ExpInterlockedPopEntrySListFault (VOID)
VOID ExpInterlockedPopEntrySListResume (VOID)
FORCEINLINE VOID FASTCALL KiAcquireInStackQueuedSpinLockForDpc (IN PKSPIN_LOCK SpinLock, IN PKLOCK_QUEUE_HANDLE LockHandle)
FORCEINLINE VOID KiAcquireKobjectLock (IN PVOID Object)
FORCEINLINE VOID KiAcquirePrcbLock (IN PKPRCB Prcb)
FORCEINLINE KIRQL FASTCALL KiAcquireSpinLockForDpc (IN PKSPIN_LOCK SpinLock)
FORCEINLINE VOID KiAcquireThreadLock (IN PKTHREAD Thread)
FORCEINLINE PKSPIN_LOCK_QUEUE KiAcquireTimerTableLock (__in ULONG Hand)
FORCEINLINE VOID KiAcquireTwoPrcbLocks (IN PKPRCB FirstPrcb, IN PKPRCB SecondPrcb)
FORCEINLINE VOID KiActivateWaiterQueue (IN PRKQUEUE Queue)
VOID KiAllProcessorsStarted (VOID)
VOID KiApcInterrupt (VOID)
FORCEINLINE VOID KiBoostPriorityThread (IN PKTHREAD Thread, IN KPRIORITY Increment)
VOID KiCalibrateTimeAdjustment (PADJUST_INTERRUPT_TIME_CONTEXT Adjust)
NTSTATUS KiCallUserMode (IN PVOID *OutputBuffer, IN PULONG OutputLength)
VOID KiChainedDispatch (VOID)
FORCEINLINE LOGICAL FASTCALL KiCheckDueTime (IN PKTIMER Timer)
VOID FASTCALL KiCheckForSListAddress (PKTRAP_FRAME TrapFrame)
FORCEINLINE VOID KiClearIdleSummary (IN KAFFINITY Mask)
FORCEINLINE VOID KiClearSMTSummary (IN KAFFINITY Mask)
FORCEINLINE VOID KiClearTbFlushTimeStampBusy (VOID)
VOID FASTCALL KiCompleteTimer (__inout PKTIMER Timer, __inout PKSPIN_LOCK_QUEUE LockQueue)
FORCEINLINE LOGICAL FASTCALL KiComputeDueTime (IN PKTIMER Timer, IN LARGE_INTEGER Interval, OUT PULONG Hand)
FORCEINLINE SCHAR KiComputeNewPriority (IN PKTHREAD Thread, IN SCHAR Adjustment)
ULONG KiComputeTimerTableIndex (IN ULONG64 DueTime)
PLARGE_INTEGER FASTCALL KiComputeWaitInterval (IN PLARGE_INTEGER OriginalTime, IN PLARGE_INTEGER DueTime, IN OUT PLARGE_INTEGER NewTime)
NTSTATUS KiContinue (IN PCONTEXT ContextRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
VOID FASTCALL KiDeferredReadyThread (IN PKTHREAD Thread)
VOID KiDeliverApc (IN KPROCESSOR_MODE PreviousMode, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
VOID KiDispatchInterrupt (VOID)
LOGICAL KiEmulateAtlThunk (IN OUT ULONG *InstructionPointer, IN OUT ULONG *StackPointer, IN OUT ULONG *Eax, IN OUT ULONG *Ecx, IN OUT ULONG *Edx)
VOID KiExecuteDpc (IN PVOID Context)
VOID FASTCALL KiExitDispatcher (IN KIRQL OldIrql)
PKTHREAD FASTCALL KiFindReadyThread (IN ULONG Processor, IN PKPRCB Prcb)
VOID KiFloatingDispatch (VOID)
VOID KiFreezeTargetExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
PULONG KiGetUserModeStackAddress (VOID)
BOOLEAN KiHandleAlignmentFault (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance, OUT BOOLEAN *ExceptionForwarded)
BOOLEAN KiHandleNmi (VOID)
VOID KiInitializeContextThread (IN PKTHREAD Thread, IN PKSYSTEM_ROUTINE SystemRoutine, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext OPTIONAL, IN PCONTEXT ContextFrame OPTIONAL)
VOID KiInitializeKernel (IN PKPROCESS Process, IN PKTHREAD Thread, IN PVOID IdleStack, IN PKPRCB Prcb, IN CCHAR Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID KiInitializeUserApc (IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN PKNORMAL_ROUTINE NormalRoutine, IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
BOOLEAN KiInitMachineDependent (VOID)
VOID KiInitSpinLocks (PKPRCB Prcb, ULONG Number)
VOID KiInitSystem (VOID)
FORCEINLINE VOID FASTCALL KiInsertDeferredReadyList (IN PKTHREAD Thread)
FORCEINLINE VOID KiInsertOrSignalTimer (__inout PKTIMER Timer, __in ULONG Hand)
LONG FASTCALL KiInsertQueue (__inout PKQUEUE Queue, __inout PLIST_ENTRY Entry, __in BOOLEAN Head)
VOID FASTCALL KiInsertQueueApc (IN PKAPC Apc, IN KPRIORITY Increment)
LOGICAL FASTCALL KiInsertTimerTable (IN PKTIMER Timer, IN ULONG Hand)
FORCEINLINE LOGICAL FASTCALL KiInsertTreeTimer (IN PKTIMER Timer, IN LARGE_INTEGER Interval)
VOID KiInterruptDispatch (VOID)
VOID KiInterruptDispatchRaise (IN PKINTERRUPT Interrupt)
VOID KiInterruptDispatchSame (IN PKINTERRUPT Interrupt)
VOID FASTCALL KiIpiSend (IN KAFFINITY TargetProcessors, IN KIPI_REQUEST Request)
VOID KiIpiSendPacket (IN KAFFINITY TargetProcessors, IN PKIPI_WORKER WorkerFunction, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
VOID FASTCALL KiIpiSignalPacketDone (IN PKIPI_CONTEXT SignalDone)
FORCEINLINE VOID KiIpiStallOnPacketTargets (KAFFINITY TargetSet)
FORCEINLINE VOID KiIpiStallOnPacketTargetsPrcb (KAFFINITY TargetSet, PKPRCB Prcb)
FORCEINLINE LOGICAL KiIsKernelStackSwappable (IN KPROCESSOR_MODE WaitMode, IN PKTHREAD Thread)
VOID KiLargePageSafetyCheck (VOID)
VOID KiPassiveRelease (VOID)
VOID KiPollFreezeExecution (VOID)
VOID FASTCALL KiProcessDeferredReadyList (IN PKPRCB CurrentPrcb)
VOID KiQuantumEnd (VOID)
NTSTATUS KiRaiseException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN BOOLEAN FirstChance)
VOID FASTCALL KiReadyThread (IN PKTHREAD Thread)
LOGICAL FASTCALL KiReinsertTreeTimer (IN PKTIMER Timer, IN ULARGE_INTEGER DueTime)
FORCEINLINE VOID FASTCALL KiReleaseInStackQueuedSpinLockForDpc (IN PKLOCK_QUEUE_HANDLE LockHandle)
FORCEINLINE VOID KiReleaseKobjectLock (IN PVOID Object)
FORCEINLINE VOID KiReleasePrcbLock (IN PKPRCB Prcb)
FORCEINLINE VOID FASTCALL KiReleaseSpinLockForDpc (IN PKSPIN_LOCK SpinLock, IN KIRQL OldIrql)
FORCEINLINE VOID KiReleaseThreadLock (IN PKTHREAD Thread)
FORCEINLINE VOID KiReleaseTimerTableLock (__inout PKSPIN_LOCK_QUEUE LockQueue)
FORCEINLINE VOID KiReleaseTwoPrcbLocks (IN PKPRCB FirstPrcb, IN PKPRCB SecondPrcb)
FORCEINLINE VOID KiRemoveEntryTimer (__inout PKTIMER Timer)
FORCEINLINE VOID KiRemoveTreeTimer (IN PKTIMER Timer)
VOID KiRestoreProcessorControlState (IN PKPROCESSOR_STATE ProcessorState)
VOID KiRestoreProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
VOID FASTCALL KiRetireDpcList (PKPRCB Prcb)
VOID KiSaveProcessorControlState (IN PKPROCESSOR_STATE ProcessorState)
VOID KiSaveProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
PKTHREAD FASTCALL KiSelectNextThread (IN PKPRCB Prcb)
FORCEINLINE PKTHREAD KiSelectReadyThread (IN KPRIORITY LowPriority, IN PKPRCB Prcb)
FORCEINLINE VOID KiSendFreeze (IN OUT KAFFINITY *Affinity, IN BOOLEAN Wait)
FORCEINLINE VOID KiSendSoftwareInterrupt (IN KAFFINITY Affinity, IN KIRQL Level)
FORCEINLINE VOID KiSendThawExecution (IN BOOLEAN Wait)
KAFFINITY FASTCALL KiSetAffinityThread (IN PKTHREAD Thread, IN KAFFINITY Affinity)
FORCEINLINE VOID KiSetContextSwapBusy (IN PKTHREAD Thread)
FORCEINLINE VOID KiSetContextSwapIdle (IN PKTHREAD Thread)
KCONTINUE_STATUS KiSetDebugProcessor (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame, IN KPROCESSOR_MODE PreviousMode)
FORCEINLINE VOID FASTCALL KiSetDueTime (IN PKTIMER Timer, IN LARGE_INTEGER Interval, OUT PULONG Hand)
FORCEINLINE VOID KiSetIdleSummary (IN KAFFINITY Mask)
VOID KiSetInternalEvent (IN PKEVENT Event, IN PKTHREAD Thread)
FORCEINLINE VOID KiSetSMTSummary (IN KAFFINITY Mask)
VOID KiSetSystemTime (IN PLARGE_INTEGER NewTime, OUT PLARGE_INTEGER OldTime)
FORCEINLINE VOID KiSetTbFlushTimeStampBusy (VOID)
BOOLEAN FASTCALL KiSignalTimer (__inout PKTIMER Timer)
VOID KiSuspendNop (IN struct _KAPC *Apc, IN OUT PKNORMAL_ROUTINE *NormalRoutine, IN OUT PVOID *NormalContext, IN OUT PVOID *SystemArgument1, IN OUT PVOID *SystemArgument2)
VOID KiSuspendRundown (IN PKAPC Apc)
VOID KiSuspendThread (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
BOOLEAN FASTCALL KiSwapContext (IN PKTHREAD OldThread, IN PKTHREAD NewThread)
BOOLEAN KiSwapProcess (IN PKPROCESS NewProcess, IN PKPROCESS OldProcess)
LONG_PTR FASTCALL KiSwapThread (IN PKTHREAD OldThread, IN PKPRCB CurrentPrcb)
VOID KiThreadStartup (IN PVOID StartContext)
VOID KiTimerExpiration (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID FASTCALL KiTimerListExpire (IN PLIST_ENTRY ExpiredListHead, IN KIRQL OldIrql)
FORCEINLINE BOOLEAN KiTryToAcquireThreadLock (IN PKTHREAD Thread)
VOID KiUnexpectedInterrupt (VOID)
FORCEINLINE VOID FASTCALL KiUnlinkThread (IN PRKTHREAD Thread, IN LONG_PTR WaitStatus)
FORCEINLINE VOID FASTCALL KiUnlockDispatcherDatabase (IN KIRQL OldIrql)
VOID FASTCALL KiUnwaitThread (IN PKTHREAD Thread, IN LONG_PTR WaitStatus, IN KPRIORITY Increment)
VOID KiUserApcDispatcher (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2, IN PKNORMAL_ROUTINE NormalRoutine)
VOID KiUserExceptionDispatcher (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextFrame)
VOID KiVerifyReadySummary (PKPRCB Prcb)
VOID FASTCALL KiWaitTest (IN PVOID Object, IN KPRIORITY Increment)
FORCEINLINE VOID KiWaitTestSynchronizationObject (IN PVOID Object, IN KPRIORITY Increment)
FORCEINLINE VOID KiWaitTestWithoutSideEffects (IN PVOID Object, IN KPRIORITY Increment)
FORCEINLINE VOID KxQueueReadyThread (IN PKTHREAD Thread, IN PKPRCB Prcb)
FORCEINLINE VOID KzAcquireSpinLock (IN PKSPIN_LOCK SpinLock)
FORCEINLINE BOOLEAN KzTryToAcquireSpinLock (IN PKSPIN_LOCK SpinLock)
Variables
ULONG KiAdjustDpcThreshold
UCHAR KiArgumentTable []
PMESSAGE_RESOURCE_DATA KiBugCodeMessages
PKDEBUG_ROUTINE KiDebugRoutine
PKDEBUG_SWITCH_ROUTINE KiDebugSwitchRoutine
ULONG KiDmaIoCoherency
ULONG KiEnableTimerWatchdog
CALL_PERFORMANCE_DATA KiFlushSingleCallData
ALIGNED_SPINLOCK KiFreezeExecutionLock
ULONG KiFreezeFlag
ALIGNED_SPINLOCK KiFreezeLockBackup
FAST_MUTEX KiGenericCallDpcMutex
volatile LONG KiHardwareTrigger
ULONG KiIdealDpcRate
volatile KAFFINITY KiIdleSMTSummary
DECLSPEC_CACHEALIGN EPROCESS KiInitialProcess
DECLSPEC_CACHEALIGN ETHREAD KiInitialThread
LONG KiMaximumDpcQueueDepth
ULONG KiMinimumDpcRate
KNODE KiNode0
KNODE KiNodeInit []
SINGLE_LIST_ENTRY KiProcessInSwapListHead
LIST_ENTRY KiProcessListHead
ALIGNED_SPINLOCK KiProcessListLock
SINGLE_LIST_ENTRY KiProcessOutSwapListHead
BOOLEAN KiProfileAlignmentFixup
ULONG KiProfileAlignmentFixupCount
ULONG KiProfileAlignmentFixupInterval
ULONG KiProfileInterval
LIST_ENTRY KiProfileListHead
ALIGNED_SPINLOCK KiProfileLock
LIST_ENTRY KiProfileSourceListHead
ALIGNED_SPINLOCK KiReverseStallIpiLock
ULONG KiServiceLimit
ULONG_PTR KiServiceTable []
CALL_PERFORMANCE_DATA KiSetEventCallData
SINGLE_LIST_ENTRY KiStackInSwapListHead
volatile ULONG KiSuspendState
KEVENT KiSwapEvent
PKTHREAD KiSwappingThread
ULONG KiTickOffset
ULARGE_INTEGER KiTimeIncrementReciprocal
CCHAR KiTimeIncrementShiftCount
KAFFINITY KiTimeProcessor
KDPC KiTimerExpireDpc
DECLSPEC_CACHEALIGN KTIMER_TABLE_ENTRY KiTimerTableListHead [TIMER_TABLE_SIZE]
ALIGNED_SPINLOCK_STRUCT KiTimerTableLock [LOCK_QUEUE_TIMER_TABLE_LOCKS]
CALL_PERFORMANCE_DATA KiWaitSingleCallData
Macro Definition Documentation
#define ALERT_INCREMENT 2
Definition at line 81 of file ki.h.
Referenced by KeAlertResumeThread(), and KeAlertThread().
#define BALANCE_INCREMENT 10
Definition at line 82 of file ki.h.
Referenced by KiSetInternalEvent().
#define ClearMember (Member, Set) Set = Set & (~((ULONG_PTR)1 << (Member)))
Definition at line 104 of file ki.h.
Referenced by KeFreezeExecution(), KeI386SetGdtSelector(), KiSendFreeze(), and KiSendThawExecution().
#define FREEZE_OWNER 0x04
Definition at line 2691 of file ki.h.
Referenced by KeFreezeExecution(), and KeSwitchFrozenProcessor().
#define FrozenState (a) ((a) & 0xF)
Definition at line 2693 of file ki.h.
Referenced by KeFreezeExecution(), KeSwitchFrozenProcessor(), KiFreezeTargetExecution(), and KiSendThawExecution().
#define IPI_APC 1
Definition at line 1658 of file ki.h.
Referenced by KiSendSoftwareInterrupt().
#define IPI_DPC 2
Definition at line 1659 of file ki.h.
Referenced by KiSendSoftwareInterrupt().
#define IPI_FREEZE 4
Definition at line 1660 of file ki.h.
Referenced by KiAcquireQueuedSpinLockCheckForFreeze(), KiPollFreezeExecution(), and KiSendFreeze().
#define IPI_INSTRUMENT_COUNT (a, b)
Definition at line 1676 of file ki.h.
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), and KxFlushEntireTb().
#define IPI_PACKET_READY 8
Definition at line 1661 of file ki.h.
#define IPI_SYNCH_REQUEST 16
Definition at line 1662 of file ki.h.
#define KI_EXCEPTION_ACCESS_VIOLATION (KI_EXCEPTION_INTERNAL | 0x4)
Definition at line 123 of file ki.h.
Referenced by KiDispatchException(), and KiPreprocessFault().
#define KI_EXCEPTION_GP_FAULT (KI_EXCEPTION_INTERNAL | 0x1)
Definition at line 120 of file ki.h.
Referenced by KiPreprocessFault().
#define KI_EXCEPTION_INTEGER_DIVIDE_BY_ZERO (KI_EXCEPTION_INTERNAL | 0x3)
Definition at line 122 of file ki.h.
Referenced by KiPreprocessFault().
#define KI_EXCEPTION_INTERNAL 0x10000000
Definition at line 119 of file ki.h.
Referenced by KiRaiseException().
#define KI_EXCEPTION_INVALID_OP (KI_EXCEPTION_INTERNAL | 0x2)
Definition at line 121 of file ki.h.
Referenced by KiPreprocessFault().
#define KiDisableAlignmentExceptions ()
Definition at line 3448 of file ki.h.
Referenced by KeStopProfile(), and KiStopProfileInterrupt().
#define KiEnableAlignmentExceptions ()
Definition at line 3447 of file ki.h.
Referenced by KeStartProfile(), and KiStartProfileInterrupt().
#define KiIncrementSwitchCounter (Member)
Definition at line 3518 of file ki.h.
#define KiQueryNxThunkEmulationState () KeGetCurrentThread()->ApcState.Process->Flags.DisableThunkEmulation
Definition at line 129 of file ki.h.
Referenced by KiEmulateAtlThunk().
#define KiRequestApcInterrupt (Processor)
Value:
if (KeGetCurrentProcessorNumber() == Processor) {     \
        KiRequestSoftwareInterrupt(APC_LEVEL);            \
    } else {                                              \
        KiSendSoftwareInterrupt(AFFINITY_MASK(Processor), APC_LEVEL);     \
    }
Definition at line 2865 of file ki.h.
Referenced by KiInsertQueueApc().
#define KiRequestDispatchInterrupt (Processor)
Value:
if (KeGetCurrentProcessorNumber() != Processor) {     \
        KiSendSoftwareInterrupt(AFFINITY_MASK(Processor), DISPATCH_LEVEL);     \
    }
Definition at line 2880 of file ki.h.
Referenced by KiDeferredReadyThread(), KiSetAffinityThread(), and KiSetPriorityThread().
#define KiWaitSatisfyAny (_Object_, _Thread_)
Value:
{                               \
    if (((_Object_)->Header.Type & DISPATCHER_OBJECT_TYPE_MASK) == EventSynchronizationObject) { \
        (_Object_)->Header.SignalState = 0;                                  \
                                                                             \
    } else if ((_Object_)->Header.Type == SemaphoreObject) {                 \
        (_Object_)->Header.SignalState -= 1;                                 \
                                                                             \
    } else if ((_Object_)->Header.Type == MutantObject) {                    \
        (_Object_)->Header.SignalState -= 1;                                 \
        if ((_Object_)->Header.SignalState == 0) {                           \
            (_Thread_)->KernelApcDisable = (_Thread_)->KernelApcDisable - (_Object_)->ApcDisable; \
            (_Object_)->OwnerThread = (_Thread_);                            \
            if ((_Object_)->Abandoned == TRUE) {                             \
                (_Object_)->Abandoned = FALSE;                               \
                (_Thread_)->WaitStatus = STATUS_ABANDONED;                   \
            }                                                                \
                                                                             \
            InsertHeadList((_Thread_)->MutantListHead.Blink,                 \
                           &(_Object_)->MutantListEntry);                    \
        }                                                                    \
    }                                                                        \
}
Definition at line 3165 of file ki.h.
Referenced by KeWaitForMultipleObjects(), and KiWaitTest().
#define KiWaitSatisfyMutant (_Object_, _Thread_)
Value:
{                            \
    (_Object_)->Header.SignalState -= 1;                                     \
    if ((_Object_)->Header.SignalState == 0) {                               \
        (_Thread_)->KernelApcDisable = (_Thread_)->KernelApcDisable - (_Object_)->ApcDisable; \
        (_Object_)->OwnerThread = (_Thread_);                                \
        if ((_Object_)->Abandoned == TRUE) {                                 \
            (_Object_)->Abandoned = FALSE;                                   \
            (_Thread_)->WaitStatus = STATUS_ABANDONED;                       \
        }                                                                    \
                                                                             \
        InsertHeadList((_Thread_)->MutantListHead.Blink,                     \
                       &(_Object_)->MutantListEntry);                        \
    }                                                                        \
}
Definition at line 3212 of file ki.h.
Referenced by KeWaitForMultipleObjects(), and KeWaitForSingleObject().
#define KiWaitSatisfyOther (_Object_)
Value:
{                                       \
    if (((_Object_)->Header.Type & DISPATCHER_OBJECT_TYPE_MASK) == EventSynchronizationObject) { \
        (_Object_)->Header.SignalState = 0;                                  \
                                                                             \
    } else if ((_Object_)->Header.Type == SemaphoreObject) {                 \
        (_Object_)->Header.SignalState -= 1;                                 \
                                                                             \
    }                                                                        \
}
Definition at line 3249 of file ki.h.
Referenced by KeWaitForMultipleObjects(), and KeWaitForSingleObject().
#define NIL (PVOID)NULL
Definition at line 96 of file ki.h.
Referenced by KeInitializeApc().
#define RESUME_INCREMENT 0
Definition at line 83 of file ki.h.
Referenced by KeAlertResumeThread(), KeForceResumeThread(), KeFreezeAllThreads(), KeResumeThread(), KeSuspendThread(), and KeThawAllThreads().
#define RUNNING 0x00
Definition at line 2688 of file ki.h.
Referenced by KiFreezeTargetExecution(), KiSendFreeze(), and KiSendThawExecution().
#define SetMember (Member, Set) Set = Set | ((ULONG_PTR)1 << (Member))
Definition at line 111 of file ki.h.
Referenced by KiInitializeKernel(), KiIpiProcessRequests(), KiIpiSendRequest(), KiIpiSignalPacketDone(), and KiSwapProcess().
#define TARGET_FROZEN 0x02
Definition at line 2689 of file ki.h.
Referenced by KeFreezeExecution(), KeSwitchFrozenProcessor(), KiFreezeTargetExecution(), and KiSendThawExecution().
#define TARGET_THAW 0x03
Definition at line 2690 of file ki.h.
Referenced by KiSendThawExecution().
#define TIME_CRITICAL_PRIORITY_BOUND 14
Definition at line 90 of file ki.h.
Referenced by KiAdjustQuantumThread(), and KiDeferredReadyThread().
#define TIMER_EXPIRE_INCREMENT 0
Definition at line 84 of file ki.h.
Referenced by KiSignalTimer(), KiTimerExpiration(), and KiTimerListExpire().
Typedef Documentation
typedef struct _ALIGNED_SPINLOCK_STRUCT ALIGNED_SPINLOCK_STRUCT
typedef struct _KAPC_RECORD KAPC_RECORD
typedef ULONG KIPI_REQUEST
Definition at line 1674 of file ki.h.
typedef struct _KTIMER_TABLE_ENTRY KTIMER_TABLE_ENTRY
typedef struct ADJUST_INTERRUPT_TIME_CONTEXT * PADJUST_INTERRUPT_TIME_CONTEXT
typedef struct _ALIGNED_SPINLOCK_STRUCT * PALIGNED_SPINLOCK_STRUCT
typedef struct _KAPC_RECORD * PKAPC_RECORD
typedef struct _KTIMER_TABLE_ENTRY * PKTIMER_TABLE_ENTRY
Function Documentation
VOID ExpInitializeExecutive (IN ULONG Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 242 of file initos.c.
References _enable(), _memicmp(), _strupr(), ANSI_NULL, ASSERT, atol(), _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CmpInitSystemVersion(), CONTAINING_RECORD, Count, _KSERVICE_TABLE_DESCRIPTOR::Count, DBG_STATUS_CONTROL_C, DbgBreakPointWithStatus(), DbgkInitialize(), DbgLoadImageSymbols(), _KLDR_DATA_TABLE_ENTRY::DllBase, ExAllocatePoolWithTag, ExBurnMemory(), ExComputeTickCountMultiplier(), ExInitializeHandleTablePackage(), ExInitPoolLookasidePointers(), ExInitSystem(), ExpInTextModeSetup, ExpIsLoaderValid(), ExpTickCountMultiplier, FALSE, FLG_ENABLE_CLOSE_EXCEPTIONS, FLG_ENABLE_EXCEPTION_LOGGING, FLG_ENABLE_KDEBUG_SYMBOL_LOAD, FLG_KERNEL_STACK_TRACE_DB, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, HAL_INITIALIZATION_FAILED, HalInitSystem(), HeadlessInit(), IMAGE_FILE_MACHINE_AMD64, IMAGE_FILE_MACHINE_I386, InitAnsiCodePageDataOffset, InitializationPhase, InitOemCodePageDataOffset, InitUnicodeCaseTableDataOffset, IoRemoteBootClient, KdBreakAfterSymbolLoad, KdPrint, KeAdjustInterruptTime(), KeBugCheck(), KeBugCheckEx(), KeMaximumIncrement, KeNumaInitialize(), KeServiceDescriptorTable, KeServiceDescriptorTableShadow, KiServiceLimit, LdrAccessResource(), LdrFindResource_U(), _STRING::Length, _UNICODE_STRING::Length, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderBad, LoaderBBTMemory, LoaderNlsData, MAX_EXCEPTION_LOG, _UNICODE_STRING::MaximumLength, MAXULONG, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MISMATCHED_HAL, MM_HIGHEST_USER_ADDRESS, MmInitSystem(), MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSystemRangeStart, MmVerifyImageIsOkForMpUse(), NonPagedPool, NT_SUCCESS, NtGlobalFlag, NtMajorVersion, NtMinorVersion, NULL, ObInitSystem(), OBJECT_INITIALIZATION_FAILED, PAGE_SIZE, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, PERFINFO_INIT_TRACEFLAGS, PHASE0_INITIALIZATION_FAILED, PP0_INITIALIZATION_FAILED, PpInitSystem(), PROCESS_INITIALIZATION_FAILED, PsInitSystem(), RtlAnsiStringToUnicodeString(), RtlCopyMemory, RtlFormatBuffer2(), RtlInitializeExceptionLog(), RtlInitializeStackTraceDataBase(), RtlInitNlsTables(), RtlInitString(), RtlResetRtlTranslations(), RtlZeroMemory, SECURITY_INITIALIZATION_FAILED, SeInitSystem(), SESSION3_INITIALIZATION_FAILED, SETUPBLK_FLAGS_IS_REMOTE_BOOT, SETUPBLK_FLAGS_IS_TEXTMODE, SharedUserData, Status, STATUS_NO_MEMORY, strstr(), TRUE, UP_DRIVER_ON_MP_SYSTEM, and VOID.
Referenced by KiInitializeKernel().
VOID ExpInterlockedPopEntrySListEnd (VOID)
Referenced by KiCheckForSListAddress().
VOID ExpInterlockedPopEntrySListFault (VOID)
Referenced by KeInvalidAccessAllowed(), and KiOpPreprocessAccessViolation().
VOID ExpInterlockedPopEntrySListResume (VOID)
Referenced by KiCheckForSListAddress(), and KiOpPreprocessAccessViolation().
FORCEINLINE VOID FASTCALL KiAcquireInStackQueuedSpinLockForDpc (IN PKSPIN_LOCK SpinLock, IN PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 470 of file ki.h.
References ASSERT, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLock(), KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeGetCurrentIrql(), and KeGetCurrentPrcb().
Referenced by KeAcquireInStackQueuedSpinLockForDpc(), KeInsertByKeyDeviceQueue(), KeInsertDeviceQueue(), KeRemoveByKeyDeviceQueue(), KeRemoveByKeyDeviceQueueIfBusy(), and KeRemoveDeviceQueue().
FORCEINLINE VOID KiAcquireKobjectLock (IN PVOID Object)
Definition at line 248 of file ki.h.
References ASSERT, DISPATCH_LEVEL, _KEVENT::Header, InterlockedBitTestAndSet(), InterlockedCompareExchange(), KeGetCurrentIrql(), KeYieldProcessor, KOBJECT_LOCK_BIT, KOBJECT_LOCK_BIT_NUMBER, _DISPATCHER_HEADER::Lock, and UNREFERENCED_PARAMETER.
Referenced by KeSignalGateBoostPriority(), KeWaitForGate(), and KiInsertQueueApc().
FORCEINLINE VOID KiAcquirePrcbLock (IN PKPRCB Prcb)
Definition at line 678 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), and KzAcquireSpinLock().
Referenced by KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiAdjustQuantumThread(), KiExitDispatcher(), KiIdleSchedule(), KiInitializeKernel(), KiQuantumEnd(), KiScanReadyQueues(), KiSetAffinityThread(), KiSetPriorityThread(), KiSwapThread(), and NtYieldExecution().
FORCEINLINE KIRQL FASTCALL KiAcquireSpinLockForDpc (IN PKSPIN_LOCK SpinLock)
Definition at line 367 of file ki.h.
References ASSERT, DISPATCH_LEVEL, FALSE, KeAcquireSpinLock, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), and KeGetCurrentPrcb().
Referenced by KeAcquireSpinLockForDpc().
FORCEINLINE VOID KiAcquireThreadLock (IN PKTHREAD Thread)
Definition at line 866 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), and KzAcquireSpinLock().
Referenced by ExpBoostOwnerThread(), KeQueryBasePriorityThread(), KeSetBasePriorityThread(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeWaitForGate(), KiAdjustQuantumThread(), KiBoostPriorityThread(), KiDeferredReadyThread(), KiInsertQueueApc(), KiQuantumEnd(), KiSetAffinityThread(), and NtYieldExecution().
FORCEINLINE PKSPIN_LOCK_QUEUE KiAcquireTimerTableLock (__in ULONG Hand)
Definition at line 989 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeAcquireQueuedSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeQueuedSpinLockContext, LOCK_QUEUE_TIMER_LOCK_SHIFT, LOCK_QUEUE_TIMER_TABLE_LOCKS, LockQueueTimerTableLock, NULL, and UNREFERENCED_PARAMETER.
Referenced by KeCheckForTimer(), KeSetSystemTime(), KiInsertOrSignalTimer(), KiInsertTreeTimer(), KiRemoveTreeTimer(), and KiTimerExpiration().
FORCEINLINE VOID KiAcquireTwoPrcbLocks (IN PKPRCB FirstPrcb, IN PKPRCB SecondPrcb)
Definition at line 711 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KzAcquireSpinLock(), and _KPRCB::PrcbLock.
Referenced by KiDeferredReadyThread(), KiIdleSchedule(), and KiSwapThread().
FORCEINLINE VOID KiActivateWaiterQueue (IN PRKQUEUE Queue)
Definition at line 1821 of file ki.h.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _LIST_ENTRY::Flink, KiUnwaitThread(), NULL, RemoveEntryList(), and _KWAIT_BLOCK::Thread.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeTerminateThread(), KeWaitForGate(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
VOID KiAllProcessorsStarted (VOID)
Definition at line 854 of file allproc.c.
References ExAllocatePoolWithTag, KeActiveProcessors, KeNodeBlock, KeNumberNodes, KeNumberProcessors, KiAdjustSimultaneousMultiThreadingCharacteristics(), KiNodeInit, KiProcessorBlock, MAXIMUM_CCNUMA_NODES, MmSecondaryColorMask, _KPRCB::NodeColor, _KPRCB::NodeShiftedColor, NonPagedPool, NULL, _KPRCB::ParentNode, and _KPRCB::SecondaryColorMask.
Referenced by KeStartAllProcessors().
VOID KiApcInterrupt (VOID)
FORCEINLINE VOID KiBoostPriorityThread (IN PKTHREAD Thread, IN KPRIORITY Increment)
Definition at line 1498 of file ki.h.
References KiAcquireThreadLock(), KiReleaseThreadLock(), KiSetPriorityThread(), and LOW_REALTIME_PRIORITY.
Referenced by KeBoostPriorityThread().
VOID KiCalibrateTimeAdjustment (PADJUST_INTERRUPT_TIME_CONTEXT Adjust)
Definition at line 471 of file miscc.c.
References ADJUST_INTERRUPT_TIME_CONTEXT::Adjustment, ADJUST_INTERRUPT_TIME_CONTEXT::Barrier, HalCalibratePerformanceCounter(), ADJUST_INTERRUPT_TIME_CONTEXT::HalNumber, _KSYSTEM_TIME::High1Time, _KSYSTEM_TIME::High2Time, _LARGE_INTEGER::HighPart, _ULARGE_INTEGER::HighPart, InterlockedDecrement, KeDisableInterrupts(), KeEnableInterrupts(), KeGetCurrentPrcb(), KeInsertQueueDpc(), KeInterruptTimeBias, KeMaximumIncrement, KeQueryInterruptTime(), KeQueryPerformanceCounter(), KeRemoveQueueDpc(), KeTickCount, ADJUST_INTERRUPT_TIME_CONTEXT::KiNumber, KiPollFreezeExecution(), KiQueryLowTickCount, KiTickOffset, KiTimerExpireDpc, _KSYSTEM_TIME::LowPart, _LARGE_INTEGER::LowPart, _ULARGE_INTEGER::LowPart, ADJUST_INTERRUPT_TIME_CONTEXT::NewCount, NULL, PERF_POWER, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_PO_CALIBRATED_PERFCOUNTER, PerfInfoLogBytes(), _PERFINFO_PO_CALIBRATED_PERFCOUNTER::PerformanceCounter, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, RtlEnlargedUnsignedDivide(), RtlEnlargedUnsignedMultiply(), RtlExtendedLargeIntegerDivide(), SharedUserData, _KPRCB::TickOffset, TIMER_TABLE_SIZE, and ULongToPtr.
Referenced by KeAdjustInterruptTime().
NTSTATUS KiCallUserMode (IN PVOID * OutputBuffer, IN PULONG OutputLength)
Referenced by KeUserModeCallback().
VOID KiChainedDispatch (VOID)
Referenced by KeConnectInterrupt(), KeDisconnectInterrupt(), and KiGetVectorInfo().
FORCEINLINE LOGICAL FASTCALL KiCheckDueTime (IN PKTIMER Timer)
Definition at line 144 of file ki.h.
References FALSE, KiQueryInterruptTime, _LARGE_INTEGER::QuadPart, and TRUE.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
VOID FASTCALL KiCheckForSListAddress (PKTRAP_FRAME TrapFrame)
FORCEINLINE VOID KiClearIdleSummary (IN KAFFINITY Mask)
Definition at line 1226 of file ki.h.
References InterlockedAnd(), and KiIdleSummary.
Referenced by KiDeferredReadyThread(), KiIdleSchedule(), and KiSwapThread().
FORCEINLINE VOID KiClearSMTSummary (IN KAFFINITY Mask)
Definition at line 1406 of file ki.h.
References InterlockedAnd(), and UNREFERENCED_PARAMETER.
Referenced by KiDeferredReadyThread(), KiIdleSchedule(), and KiSwapThread().
FORCEINLINE VOID KiClearTbFlushTimeStampBusy (VOID)
Definition at line 2328 of file ki.h.
References ASSERT, InterlockedIncrement, and KiTbFlushTimeStamp.
Referenced by KxFlushEntireTb().
VOID FASTCALL KiCompleteTimer (__inout PKTIMER Timer, __inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 24 of file timersup.c.
References _LIST_ENTRY::Blink, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, KiLockDispatcherDatabaseAtSynchLevel, KiReleaseTimerTableLock(), KiRemoveEntryTimer(), KiRequestSoftwareInterrupt, KiSignalTimer(), KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
Referenced by KiInsertOrSignalTimer().
FORCEINLINE LOGICAL FASTCALL KiComputeDueTime (IN PKTIMER Timer, IN LARGE_INTEGER Interval, OUT PULONG Hand)
Definition at line 1146 of file ki.h.
References FALSE, _LARGE_INTEGER::HighPart, KiComputeTimerTableIndex(), KiQueryInterruptTime, KiQuerySystemTime, _LARGE_INTEGER::QuadPart, and TRUE.
Referenced by KeSetTimerEx(), and KiInsertTreeTimer().
FORCEINLINE SCHAR KiComputeNewPriority (IN PKTHREAD Thread, IN SCHAR Adjustment)
Definition at line 188 of file ki.h.
References ASSERT, LOW_REALTIME_PRIORITY, Priority, and TRUE.
Referenced by KeSetBasePriorityThread(), KeSetEventBoostPriority(), KiAdjustQuantumThread(), KiDeferredReadyThread(), KiQuantumEnd(), and NtYieldExecution().
ULONG KiComputeTimerTableIndex (IN ULONG64 DueTime)
Referenced by KeSetSystemTime(), KiComputeDueTime(), KiInsertTimerTable(), and KiSetDueTime().
PLARGE_INTEGER FASTCALL KiComputeWaitInterval (IN PLARGE_INTEGER OriginalTime, IN PLARGE_INTEGER DueTime, IN OUT PLARGE_INTEGER NewTime)
Definition at line 161 of file wait.c.
References KiQueryInterruptTime.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
NTSTATUS KiContinue (IN PCONTEXT ContextRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
Definition at line 83 of file raisexcp.c.
References APC_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, KeContextToKframes(), KeGetCurrentIrql(), KeGetPreviousMode, KeLowerIrql, KernelMode, KfRaiseIrql(), KiContinuePreviousModeUser(), Status, and STATUS_SUCCESS.
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
Definition at line 821 of file exceptn.c.
References EXCEPTION_EXECUTE_HANDLER, and RtlCopyMemory.
Referenced by Ki386CheckDelayedNpxTrap(), KiDispatchException(), and KiInitializeUserApc().
VOID FASTCALL KiDeferredReadyThread (IN PKTHREAD Thread)
Definition at line 114 of file thredsup.c.
References AdjustBoost, AdjustNone, AdjustUnwait, AFFINITY_MASK, ASSERT, _KPRCB::CurrentThread, _KTHREAD::DeferredProcessor, DeferredReady, DISPATCH_LEVEL, _KPRCB::DispatcherReadyListHead, FALSE, HIGH_PRIORITY, _KPRCB::IdleThread, InsertHeadList(), InsertTailList(), KeFindFirstSetLeftAffinity, KeGetCurrentPrcb(), KeIsIdleHaltSet, KiAcquireThreadLock(), KiAcquireTwoPrcbLocks(), KiClearIdleSummary(), KiClearSMTSummary(), KiComputeNewPriority(), KiIdleSMTSummary, KiIdleSummary, KiProcessorBlock, KiQueryLowTickCount, KiReleaseThreadLock(), KiReleaseTwoPrcbLocks(), KiRequestDispatchInterrupt, KiSendSoftwareInterrupt(), LOCK_OWNERSHIP_QUANTUM, LOW_REALTIME_PRIORITY, MEMORY_PRIORITY_FOREGROUND, min, _KPRCB::MultiThreadProcessorSet, _KPRCB::NextThread, NOTHING, NULL, _KPRCB::Number, _KPRCB::ParentNode, _KTHREAD::Preempted, Priority, _KTHREAD::Priority, PRIORITY_MASK, _KNODE::ProcessorMask, PsPrioritySeparation, ReadForWriteAccess, Ready, _KPRCB::ReadySummary, Running, _KPRCB::SetMember, Standby, _KTHREAD::State, STATUS_KERNEL_APC, ThreadPriority, TIME_CRITICAL_PRIORITY_BOUND, TRUE, and WAIT_QUANTUM_DECREMENT.
Referenced by KeSignalGateBoostPriority(), KiInsertDeferredReadyList(), KiProcessDeferredReadyList(), and KxQueueReadyThread().
VOID KiDeliverApc (IN KPROCESSOR_MODE PreviousMode, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
Definition at line 78 of file apcsup.c.
References APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KAPC::Inserted, INVALID_PROCESS_ATTACH_ATTEMPT, IRQL_UNEXPECTED_VALUE, IsListEmpty, KeAcquireInStackQueuedSpinLock(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KeLowerIrql, KeMemoryBarrier(), KeRaiseIrql, KeReleaseInStackQueuedSpinLock(), _KTHREAD::KernelApcDisable, _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, _KAPC::KernelRoutine, KeTestAlertThread(), KiCheckForSListAddress(), KiInitializeUserApc(), _KAPC::NormalContext, _KAPC::NormalRoutine, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, ReadForWriteAccess, RemoveEntryList(), _KTHREAD::SpecialApcDisable, _KAPC::SystemArgument1, _KAPC::SystemArgument2, _KTHREAD::TrapFrame, TRUE, _KAPC_STATE::UserApcPending, and UserMode.
Referenced by KiCheckForKernelApcDelivery(), KiContinueEx(), and KiExitDispatcher().
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
Definition at line 431 of file exceptn.c.
VOID KiDispatchInterrupt (VOID)
LOGICAL KiEmulateAtlThunk (IN OUT ULONG * InstructionPointer, IN OUT ULONG * StackPointer, IN OUT ULONG * Eax, IN OUT ULONG * Ecx, IN OUT ULONG * Edx)
Definition at line 23 of file thkemul.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KiQueryNxThunkEmulationState, MmCheckForSafeExecution(), NOTHING, NtCurrentTeb(), NtCurrentTeb32, ProbeAndReadUchar, ProbeAndReadUlong, ProbeAndWriteUlong, PtrToUlong, TRUE, and UlongToPtr.
Referenced by KiCheckForAtlThunk().
VOID KiExecuteDpc (IN PVOID Context)
Definition at line 48 of file dpcsup.c.
References _KTHREAD::Affinity, ASSERT, CONTAINING_RECORD, _KDPC::DeferredContext, _KDPC::DeferredRoutine, DPC_THREADED, _KDPC::DpcData, _KPRCB::DpcData, _KPRCB::DpcEvent, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _PERFINFO_DPC_INFORMATION::DpcRoutine, _KPRCB::DpcThread, _KPRCB::DpcThreadActive, _KPRCB::DpcThreadRequested, FALSE, _LIST_ENTRY::Flink, HIGH_LEVEL, HIGH_PRIORITY, _PERFINFO_DPC_INFORMATION::InitialTime, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, KeMemoryBarrier(), KeRaiseIrql, KeReleaseSpinLockFromDpcLevel(), KernelMode, KeSetPriorityThread(), KeSetSystemAffinityThread(), KeWaitForSingleObject(), NULL, PASSIVE_LEVEL, PERF_DPC, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_DPC, PerfInfoLogBytes(), PerfTimeStamp, _KTHREAD::Priority, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _KPRCB::SetMember, Suspended, _KDPC::SystemArgument1, _KDPC::SystemArgument2, _KPRCB::ThreadDpcEnable, and TRUE.
Referenced by KeInitSystem().
VOID FASTCALL KiExitDispatcher (IN KIRQL OldIrql)
Definition at line 25 of file waitsup.c.
References APC_LEVEL, ASSERT, _KPRCB::CurrentThread, _KPRCB::DeferredReadyListHead, DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, FALSE, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLowerIrql, KernelMode, KiAcquirePrcbLock(), KiDeliverApc(), KiProcessDeferredReadyList(), KiRequestSoftwareInterrupt, KiSetContextSwapBusy(), KiSwapContext(), KxQueueReadyThread(), _SINGLE_LIST_ENTRY::Next, _KPRCB::NextThread, NULL, Running, _KTHREAD::State, SYNCH_LEVEL, and _KTHREAD::WaitIrql.
Referenced by KeAlertResumeThread(), KeAlertThread(), KeDetachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertHeadQueue(), KeInsertQueue(), KeInsertQueueApc(), KeRemoveQueue(), KeResumeThread(), KeRundownQueue(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeSetTimerEx(), KeSignalGateBoostPriority(), KeSuspendThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KiAdjustQuantumThread(), KiAttachProcess(), and KiUnlockDispatcherDatabase().
PKTHREAD FASTCALL KiFindReadyThread (IN ULONG Processor, IN PKPRCB Prcb)
Definition at line 688 of file thredsup.c.
References _KTHREAD::Affinity, AFFINITY_MASK, ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeFindFirstSetLeftMember(), _KTHREAD::NextProcessor, NULL, _KTHREAD::Priority, PRIORITY_MASK, RemoveEntryList(), and _KTHREAD::WaitListEntry.
Referenced by KiIdleSchedule(), and KiSwapThread().
VOID KiFloatingDispatch (VOID)
Referenced by KiGetVectorInfo().
VOID KiFreezeTargetExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 255 of file debug.c.
References CONTEXT_TO_PROGRAM_COUNTER, _KPROCESSOR_STATE::ContextFrame, ContinueError, ContinueNextProcessor, DbgBreakPoint(), _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionRecord, FALSE, FREEZE_ACTIVE, FrozenState, HIGH_LEVEL, _KPRCB::IpiFrozen, KeBugCheckActive, KeDisableInterrupts(), KeEnableInterrupts(), KeFlushCurrentTb(), KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrql, KeSweepCurrentDcache, KeSweepCurrentIcache, KeYieldProcessor, KiDebugSwitchRoutine, KiFreezeExecutionLock, KiFreezeLockBackup, KiRestoreProcessorState(), KiSaveProcessorState(), NULL, _KPRCB::ProcessorState, RtlZeroMemory, RUNNING, _KPRCB::SkipTick, Status, STATUS_WAKE_SYSTEM_DEBUGGER, TARGET_FROZEN, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KiAcquireQueuedSpinLockCheckForFreeze(), KiCheckForFreezeExecution(), and KiPollFreezeExecution().
PULONG KiGetUserModeStackAddress (VOID)
Referenced by KeUserModeCallback().
BOOLEAN KiHandleAlignmentFault (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance, OUT BOOLEAN * ExceptionForwarded)
BOOLEAN KiHandleNmi (VOID)
Definition at line 1216 of file miscc.c.
References _KNMI_HANDLER_CALLBACK::Callback, _KNMI_HANDLER_CALLBACK::Context, FALSE, KiNmiCallbackListHead, _KNMI_HANDLER_CALLBACK::Next, and NULL.
Referenced by KiProcessNMI().
VOID KiInitializeContextThread (IN PKTHREAD Thread, IN PKSYSTEM_ROUTINE SystemRoutine, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext OPTIONAL, IN PCONTEXT ContextFrame OPTIONAL)
Definition at line 32 of file thredini.c.
References _KSWITCHFRAME::ApcBypassDisable, ARGUMENT_PRESENT, CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXTENDED_REGISTERS, CONTEXT_FLOATING_POINT, _CONTEXT::ContextFlags, _FLOATING_SAVE_AREA::ControlWord, _FXSAVE_FORMAT::ControlWord, CR0_EM, CR0_MP, _FLOATING_SAVE_AREA::Cr0NpxState, _FX_SAVE_AREA::Cr0NpxState, _FLOATING_SAVE_AREA::DataOffset, _FXSAVE_FORMAT::DataOffset, _FLOATING_SAVE_AREA::DataSelector, _FXSAVE_FORMAT::DataSelector, _KTRAP_FRAME::DbgArgMark, _KTRAP_FRAME::Dr7, _FLOATING_SAVE_AREA::ErrorOffset, _FXSAVE_FORMAT::ErrorOffset, _FLOATING_SAVE_AREA::ErrorSelector, _FXSAVE_FORMAT::ErrorSelector, EXCEPTION_CHAIN_END, _KTRAP_FRAME::ExceptionList, _KSWITCHFRAME::ExceptionList, _CONTEXT::ExtendedRegisters, _CONTEXT::FloatSave, _KTRAP_FRAME::HardwareSegSs, KeContextToKframes(), KeI386FxsrPresent, KeI386NpxPresent, KernelMode, KiThreadStartup(), KTRAP_FRAME_LENGTH, _FXSAVE_FORMAT::MXCsr, NPX_STATE_NOT_LOADED, _FX_SAVE_AREA::NpxSavedCpu, NULL, PASSIVE_LEVEL, _KTRAP_FRAME::PreviousPreviousMode, _KSWITCHFRAME::RetAddr, RPL_MASK, RtlCopyMemory, RtlZeroMemory, _KTRAP_FRAME::SegDs, _KTRAP_FRAME::SegEs, _FLOATING_SAVE_AREA::StatusWord, _FXSAVE_FORMAT::StatusWord, _FLOATING_SAVE_AREA::TagWord, _FXSAVE_FORMAT::TagWord, TRUE, and UserMode.
VOID KiInitializeKernel (IN PKPROCESS Process, IN PKTHREAD Thread, IN PVOID IdleStack, IN PKPRCB Prcb, IN CCHAR Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID KiInitializeUserApc (IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN PKNORMAL_ROUTINE NormalRoutine, IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 223 of file apcuser.c.
References ASSERT, C_ASSERT, CONTEXT_ALIGN, CONTEXT_ALIGNED_SIZE, CONTEXT_DEBUG_REGISTERS, CONTEXT_FULL, CONTEXT_LENGTH, CONTEXT_ROUND, _CONTEXT::ContextFlags, _CONTEXT::EFlags, EFLAGS_IOPL_MASK, EFLAGS_V86_MASK, _CONTEXT::Esp, except, _EXCEPTION_RECORD::ExceptionAddress, KeContextFromKframes(), KeGetCurrentThread(), KeLowerIrql, KernelMode, KeUserApcDispatcher, KGDT_R3_CODE, KGDT_R3_DATA, KGDT_R3_TEB, KiCopyInformation(), KiDispatchException(), MODE_MASK, _KAPC_RECORD::NormalContext, _KAPC_RECORD::NormalRoutine, NULL, PASSIVE_LEVEL, ProbeForWrite(), ProbeForWriteSmallStructure(), RtlCopyMemory, SANITIZE_FLAGS, SANITIZE_SEG, _KAPC_RECORD::SystemArgument1, _KAPC_RECORD::SystemArgument2, TRUE, and UserMode.
Referenced by KiDeliverApc(), and PspUserThreadStartup().
BOOLEAN KiInitMachineDependent (VOID)
Definition at line 1045 of file initkr.c.
References CPUID(), DbgBreakPoint(), FALSE, _FX_SAVE_AREA::FxArea, HalFrameBufferCachingInformation, HalQuerySystemInformation, HIGH_LEVEL, Index, KeActiveProcessors, KeBugCheck(), KeBugCheckEx(), KeDelayExecutionThread(), KeFeatureBits, KeGetCurrentPrcb(), KeGetCurrentThread(), KeI386ForceNpxEmulation, KeI386NpxPresent, KeIpiGenericCall(), KeNumberProcessors, KeQueryPerformanceCounter(), KeRevertToUserAffinityThread(), KernelMode, KeSetSystemAffinityThread(), KF_AMDK6MTRR, KF_FXSR, KF_GLOBAL_PAGE, KF_LARGE_PAGE, KF_MTRR, KF_PAT, KF_RDTSC, KfLowerIrql(), KfRaiseIrql(), Ki386ClearIdentityMap(), Ki386CreateIdentityMap(), Ki386EnableCurrentLargePage(), Ki386EnableCurrentLargePageEnd, Ki386EnableGlobalPage(), Ki386EnableTargetLargePage(), KiAmdK6InitializeMTRR(), KiChainedDispatch2ndLvl(), KiDivide6432(), KiGetInterruptDispatchPatchAddresses(), KiI386PentiumLockErrataFixup(), KiI386PentiumLockErrataPresent, KiInitializeMTRR(), KiInitializePAT(), KiLargePageSafetyCheck(), KiLockStepOtherProcessors(), KiMXCsrMask, KiRestoreFastSyscallReturnState(), KiTestDividend, KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), KiTimeLimitIsrMicroseconds, KiUnlockStepOtherProcessors(), Kix86FxSave(), MAX_ATTEMPTS, _KPRCB::MHz, MmEnablePAT(), MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED, _FXSAVE_FORMAT::MXCsrMask, NT_SUCCESS, NULL, PF_FLOATING_POINT_PRECISION_ERRATA, RDTSC(), SharedUserData, Status, SYNCH_LEVEL, TRUE, _FX_SAVE_AREA::U, UNSUPPORTED_PROCESSOR, and VOID.
Referenced by KeInitSystem().
VOID KiInitSpinLocks (PKPRCB Prcb, ULONG Number)
Definition at line 131 of file kiinit.c.
References _KPRCB::AdjustDpcThreshold, AfdWorkQueueSpinLock, _KPRCB::CallDpc, CcBcbSpinLock, CcMasterSpinLock, CcVacbSpinLock, CcWorkQueueSpinLock, _KPRCB::DeferredReadyListHead, _KPRCB::DispatcherReadyListHead, DPC_NORMAL, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _KPRCB::DpcRoutineActive, HighImportance, Index, InitializeListHead(), IopCancelSpinLock, IopCompletionLock, IopDatabaseLock, IopVpbSpinLock, KeGetPcr(), KeInitializeDpc(), KeInitializeSpinLock(), KeSetImportanceDpc(), KeSetTargetProcessorDpc(), KiAdjustDpcThreshold, KiDispatcherLock, KiMaximumDpcQueueDepth, KiMinimumDpcRate, KiReverseStallIpiLock, KiTimerTableLock, _ALIGNED_SPINLOCK_STRUCT::Lock, _KSPIN_LOCK_QUEUE::Lock, LOCK_QUEUE_TIMER_TABLE_LOCKS, _KPRCB::LockQueue, LockQueueAfdWorkQueueLock, LockQueueBcbLock, LockQueueDispatcherLock, LockQueueIoCancelLock, LockQueueIoCompletionLock, LockQueueIoDatabaseLock, LockQueueIoVpbLock, LockQueueMasterLock, LockQueueMmNonPagedPoolLock, LockQueueNonPagedPoolLock, LockQueueNtfsStructLock, LockQueuePfnLock, LockQueueSystemSpaceLock, LockQueueTimerTableLock, LockQueueUnusedSpare1, LockQueueUnusedSpare16, LockQueueVacbLock, LockQueueWorkQueueLock, MAXIMUM_PRIORITY, _KPRCB::MaximumDpcQueueDepth, _KPRCB::MinimumDpcRate, MmNonPagedPoolLock, MmPfnLock, MmSystemSpaceLock, _KSPIN_LOCK_QUEUE::Next, _SINGLE_LIST_ENTRY::Next, NonPagedPoolLock, NtfsStructLock, NULL, _KPRCB::PrcbLock, _KPRCB::QueueIndex, _KPRCB::ReadySummary, and _KPRCB::WaitListHead.
Referenced by KiInitializeBootStructures(), and KiInitializeKernel().
VOID KiInitSystem (VOID)
Definition at line 304 of file kiinit.c.
References _KSERVICE_TABLE_DESCRIPTOR::Base, _KSERVICE_TABLE_DESCRIPTOR::Count, ExInitializeFastMutex, FALSE, _ULARGE_INTEGER::HighPart, Index, InitializeListHead(), KeBugCheckCallbackListHead, KeBugCheckCallbackLock, KeBugCheckReasonCallbackListHead, KeInitializeDpc(), KeInitializeEvent(), KeInitializeSpinLock(), KeServiceDescriptorTable, KeServiceDescriptorTableShadow, KeSetTargetProcessorDpc(), KiArgumentTable, KiGenericCallDpcMutex, KiProcessInSwapListHead, KiProcessOutSwapListHead, KiProfileListHead, KiProfileLock, KiProfileSourceListHead, KiServiceLimit, KiServiceTable, KiStackInSwapListHead, KiSwapEvent, KiTimerExpiration(), KiTimerExpireDpc, KiTimerTableListHead, _KSERVICE_TABLE_DESCRIPTOR::Limit, _ULARGE_INTEGER::LowPart, _SINGLE_LIST_ENTRY::Next, NULL, _KSERVICE_TABLE_DESCRIPTOR::Number, NUMBER_SERVICE_TABLES, RtlCopyMemory, SynchronizationEvent, _KTIMER_TABLE_ENTRY::Time, and TIMER_TABLE_SIZE.
Referenced by KiInitializeKernel().
FORCEINLINE VOID FASTCALL KiInsertDeferredReadyList (IN PKTHREAD Thread)
Definition at line 2419 of file ki.h.
References DeferredReady, _KPRCB::DeferredReadyListHead, KeGetCurrentPrcb(), KiDeferredReadyThread(), _KPRCB::Number, and PushEntryList.
Referenced by KiInsertQueueApc(), KiInSwapKernelStacks(), KiReadyThread(), KiScanReadyQueues(), KiSetAffinityThread(), and KiSetPriorityThread().
FORCEINLINE VOID KiInsertOrSignalTimer (__inout PKTIMER Timer, __in ULONG Hand)
Definition at line 2135 of file ki.h.
References KiAcquireTimerTableLock(), KiCompleteTimer(), KiInsertTimerTable(), KiReleaseTimerTableLock(), KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeSetTimerEx(), KeWaitForMultipleObjects(), and KeWaitForSingleObject().
LONG FASTCALL KiInsertQueue (__inout PKQUEUE Queue, __inout PLIST_ENTRY Entry, __in BOOLEAN Head)
Definition at line 656 of file queueobj.c.
References ASSERT_QUEUE, _LIST_ENTRY::Blink, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, _DISPATCHER_HEADER::Inserted, InsertHeadList(), InsertTailList(), KeGetCurrentThread(), KiReadyThread(), KiRemoveTreeTimer(), NULL, _KTHREAD::Queue, RemoveEntryList(), _KWAIT_BLOCK::Thread, _KTHREAD::Timer, TRUE, _KTHREAD::WaitListEntry, _KTHREAD::WaitReason, _KTHREAD::WaitStatus, and WrQueue.
Referenced by KeInsertHeadQueue(), KeInsertQueue(), and KeTerminateThread().
VOID FASTCALL KiInsertQueueApc (IN PKAPC Apc, IN KPRIORITY Increment)
Definition at line 382 of file apcsup.c.
References _KTHREAD::Alertable, APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, _KTHREAD::ApcStatePointer, ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _KQUEUE::CurrentCount, FALSE, GateObject, _KTHREAD::GateObject, GateWait, InsertApcEnvironment, InsertHeadList(), InsertTailList(), KeGetCurrentThread(), KeMemoryBarrier(), _KTHREAD::KernelApcDisable, _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, KiAcquireKobjectLock(), KiAcquireThreadLock(), KiInsertDeferredReadyList(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseKobjectLock(), KiReleaseThreadLock(), KiRequestApcInterrupt, KiRequestSoftwareInterrupt, KiUnlockDispatcherDatabaseFromSynchLevel, KiUnwaitThread(), _KTHREAD::NextProcessor, _KAPC::NormalRoutine, NULL, PsExitSpecialApc(), _KTHREAD::Queue, RemoveEntryList(), Running, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_USER_APC, TRUE, _KAPC_STATE::UserApcPending, UserMode, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitMode, and _KTHREAD::WaitStatus.
Referenced by KeFreezeAllThreads(), KeInsertQueueApc(), and KeSuspendThread().
LOGICAL FASTCALL KiInsertTimerTable (IN PKTIMER Timer, IN ULONG Hand)
Definition at line 96 of file timersup.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _KTIMER::DueTime, _KTIMER_TABLE_ENTRY::Entry, FALSE, InsertHeadList(), KeMemoryBarrier(), KiComputeTimerTableIndex(), KiQueryInterruptTime, KiTimerTableListHead, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, _KTIMER_TABLE_ENTRY::Time, and TRUE.
Referenced by KeSetSystemTime(), KiInsertOrSignalTimer(), and KiInsertTreeTimer().
FORCEINLINE LOGICAL FASTCALL KiInsertTreeTimer (IN PKTIMER Timer, IN LARGE_INTEGER Interval)
Definition at line 2065 of file ki.h.
References FALSE, KiAcquireTimerTableLock(), KiComputeDueTime(), KiInsertTimerTable(), KiReleaseTimerTableLock(), KiRemoveEntryTimer(), and TRUE.
Referenced by KiSignalTimer(), KiTimerExpiration(), and KiTimerListExpire().
VOID KiInterruptDispatch (VOID)
Referenced by KeConnectInterrupt(), KeDisconnectInterrupt(), KeInitializeInterrupt(), and KiGetVectorInfo().
VOID KiInterruptDispatchRaise (IN PKINTERRUPT Interrupt)
VOID KiInterruptDispatchSame (IN PKINTERRUPT Interrupt)
VOID FASTCALL KiIpiSend (IN KAFFINITY TargetProcessors, IN KIPI_REQUEST Request)
Referenced by KiSendFreeze(), and KiSendSoftwareInterrupt().
VOID KiIpiSendPacket (IN KAFFINITY TargetProcessors, IN PKIPI_WORKER WorkerFunction, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 521 of file ipi.c.
References ASSERT, DISPATCH_LEVEL, IPI_PACKET_READY, KeGetCurrentIrql(), KiIpiSendRequest(), and UNREFERENCED_PARAMETER.
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeIpiGenericCall(), KeStartProfile(), KeStopProfile(), and KxFlushEntireTb().
VOID FASTCALL KiIpiSignalPacketDone (IN PKIPI_CONTEXT SignalDone)
Definition at line 590 of file ipi.c.
References KeGetCurrentPrcb(), _KPRCB::PacketBarrier, SetMember, _KPRCB::SetMember, _KPRCB::TargetSet, and UNREFERENCED_PARAMETER.
Referenced by KiFlushTargetEntireTb(), KiFlushTargetMultipleTb(), KiFlushTargetProcessTb(), KiFlushTargetSingleTb(), KiIpiGenericCallTarget(), KiStartProfileInterrupt(), and KiStopProfileInterrupt().
FORCEINLINE VOID KiIpiStallOnPacketTargets (KAFFINITY TargetSet)
Definition at line 1780 of file ki.h.
References KeGetCurrentPrcb(), and KiIpiStallOnPacketTargetsPrcb().
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeInvalidateAllCaches(), KeIpiGenericCall(), KiCompleteEffectiveRangeChange(), KiInitializePAT(), KiLockStepOtherProcessors(), and KxFlushEntireTb().
FORCEINLINE VOID KiIpiStallOnPacketTargetsPrcb (KAFFINITY TargetSet, PKPRCB Prcb)
Definition at line 1706 of file ki.h.
References ASSERT, KeGetCurrentPrcb(), KeYieldProcessor, _KPRCB::PacketBarrier, and _KPRCB::TargetSet.
Referenced by KeStartProfile(), KeStopProfile(), and KiIpiStallOnPacketTargets().
FORCEINLINE LOGICAL KiIsKernelStackSwappable (IN KPROCESSOR_MODE WaitMode, IN PKTHREAD Thread)
Definition at line 1559 of file ki.h.
References FALSE, KernelMode, and LOW_REALTIME_PRIORITY.
VOID KiLargePageSafetyCheck (VOID)
Referenced by KiInitMachineDependent().
VOID KiPassiveRelease (VOID)
VOID KiPollFreezeExecution (VOID)
Definition at line 529 of file debug.c.
References InterlockedExchangeAdd(), IPI_FREEZE, KeGetCurrentPrcb(), KeYieldProcessor, KiFreezeTargetExecution(), NULL, and _KPRCB::RequestSummary.
Referenced by KeBugCheck2(), KiCalibrateTimeAdjustment(), and KiIpiGenericCallTarget().
VOID FASTCALL KiProcessDeferredReadyList (IN PKPRCB CurrentPrcb)
Definition at line 795 of file thredsup.c.
References ASSERT, CONTAINING_RECORD, KiDeferredReadyThread(), _SINGLE_LIST_ENTRY::Next, and NULL.
Referenced by KiExitDispatcher(), KiRetireDpcList(), and KiSwapThread().
VOID KiQuantumEnd (VOID)
Definition at line 221 of file dpcsup.c.
References APC_LEVEL, _KTHREAD::ApcState, _KPRCB::CurrentThread, _KPROCESS::DisableQuantum, DISPATCH_LEVEL, _KPRCB::DpcEvent, _KPRCB::DpcSetEventRequest, FALSE, InterlockedExchange(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KeSetEvent(), KiAcquirePrcbLock(), KiAcquireThreadLock(), KiComputeNewPriority(), KiReleasePrcbLock(), KiReleaseThreadLock(), KiSelectReadyThread(), KiSetContextSwapBusy(), KiSwapContext(), KxQueueReadyThread(), LOW_REALTIME_PRIORITY, MAXCHAR, _KPRCB::NextThread, NULL, _KTHREAD::Preempted, _KTHREAD::Priority, _KAPC_STATE::Process, _KTHREAD::Quantum, _KTHREAD::QuantumReset, Running, Standby, _KTHREAD::State, TRUE, _KTHREAD::WaitIrql, _KTHREAD::WaitReason, and WrQuantumEnd.
NTSTATUS KiRaiseException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN BOOLEAN FirstChance)
Definition at line 173 of file raisexcp.c.
References except, EXCEPTION_EXECUTE_HANDLER, EXCEPTION_MAXIMUM_PARAMETERS, FIELD_OFFSET, KeContextToKframes(), KeGetPreviousMode, KernelMode, KI_EXCEPTION_INTERNAL, KiDispatchException(), _EXCEPTION_RECORD::NumberParameters, ProbeAndReadUlong, ProbeForRead, ProbeForReadSmallStructure, RtlCopyMemory, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
VOID FASTCALL KiReadyThread (IN PKTHREAD Thread)
Definition at line 896 of file thredsup.c.
References ASSERT, FALSE, InsertTailList(), InterlockedPushEntrySingleList(), KiInsertDeferredReadyList(), KiProcessInSwapListHead, KiSetInternalEvent(), KiStackInSwapListHead, KiSwapEvent, KiSwappingThread, MAXULONG_PTR, ProcessInMemory, ProcessInTransition, ProcessOutOfMemory, Ready, _KPROCESS::ReadyListHead, _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, Transition, and TRUE.
Referenced by KeReadyThread(), KeSetEventBoostPriority(), KiAttachProcess(), KiInsertQueue(), KiInSwapProcesses(), KiOutSwapProcesses(), and KiUnwaitThread().
LOGICAL FASTCALL KiReinsertTreeTimer (IN PKTIMER Timer, IN ULARGE_INTEGER DueTime)
FORCEINLINE VOID FASTCALL KiReleaseInStackQueuedSpinLockForDpc (IN PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 520 of file ki.h.
References ASSERT, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeReleaseInStackQueuedSpinLock(), and KeReleaseInStackQueuedSpinLockFromDpcLevel().
Referenced by KeInsertByKeyDeviceQueue(), KeInsertDeviceQueue(), KeReleaseInStackQueuedSpinLockForDpc(), KeRemoveByKeyDeviceQueue(), KeRemoveByKeyDeviceQueueIfBusy(), and KeRemoveDeviceQueue().
FORCEINLINE VOID KiReleaseKobjectLock (IN PVOID Object)
Definition at line 319 of file ki.h.
References ASSERT, DISPATCH_LEVEL, _KEVENT::Header, InterlockedAnd(), KeGetCurrentIrql(), KOBJECT_LOCK_BIT, _DISPATCHER_HEADER::Lock, and UNREFERENCED_PARAMETER.
Referenced by KeSignalGateBoostPriority(), KeWaitForGate(), and KiInsertQueueApc().
FORCEINLINE VOID KiReleasePrcbLock (IN PKPRCB Prcb)
Definition at line 761 of file ki.h.
References ASSERT, DISPATCH_LEVEL, InterlockedAnd(), KeGetCurrentIrql(), and UNREFERENCED_PARAMETER.
Referenced by KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiAdjustQuantumThread(), KiIdleSchedule(), KiInitializeKernel(), KiQuantumEnd(), KiReleaseTwoPrcbLocks(), KiScanReadyQueues(), KiSetAffinityThread(), KiSetPriorityThread(), KiSwapThread(), KxQueueReadyThread(), and NtYieldExecution().
FORCEINLINE VOID FASTCALL KiReleaseSpinLockForDpc (IN PKSPIN_LOCK SpinLock, IN KIRQL OldIrql)
Definition at line 419 of file ki.h.
References ASSERT, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeReleaseSpinLock(), and KeReleaseSpinLockFromDpcLevel().
Referenced by KeReleaseSpinLockForDpc().
FORCEINLINE VOID KiReleaseThreadLock (IN PKTHREAD Thread)
Definition at line 931 of file ki.h.
References ASSERT, DISPATCH_LEVEL, InterlockedAnd(), KeGetCurrentIrql(), KeMemoryBarrierWithoutFence, and UNREFERENCED_PARAMETER.
Referenced by ExpBoostOwnerThread(), KeQueryBasePriorityThread(), KeSetBasePriorityThread(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeSignalGateBoostPriority(), KeWaitForGate(), KiAdjustQuantumThread(), KiBoostPriorityThread(), KiDeferredReadyThread(), KiInsertQueueApc(), KiQuantumEnd(), KiSetAffinityThread(), and NtYieldExecution().
FORCEINLINE VOID KiReleaseTimerTableLock (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 1041 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KeReleaseQueuedSpinLockFromDpcLevel(), and UNREFERENCED_PARAMETER.
Referenced by KeCheckForTimer(), KeSetSystemTime(), KiCompleteTimer(), KiInsertOrSignalTimer(), KiInsertTreeTimer(), KiRemoveTreeTimer(), and KiTimerExpiration().
FORCEINLINE VOID KiReleaseTwoPrcbLocks (IN PKPRCB FirstPrcb, IN PKPRCB SecondPrcb)
Definition at line 817 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KiReleasePrcbLock(), and UNREFERENCED_PARAMETER.
Referenced by KiDeferredReadyThread().
FORCEINLINE VOID KiRemoveEntryTimer (__inout PKTIMER Timer)
Definition at line 1944 of file ki.h.
References _KTIMER_TABLE_ENTRY::Entry, FALSE, _LIST_ENTRY::Flink, _ULARGE_INTEGER::HighPart, NULL, RemoveEntryList(), and _KTIMER_TABLE_ENTRY::Time.
Referenced by KeSetSystemTime(), KiCompleteTimer(), KiInsertTreeTimer(), and KiTimerExpiration().
FORCEINLINE VOID KiRemoveTreeTimer (IN PKTIMER Timer)
Definition at line 1999 of file ki.h.
References _KTIMER_TABLE_ENTRY::Entry, FALSE, _LIST_ENTRY::Flink, _ULARGE_INTEGER::HighPart, KiAcquireTimerTableLock(), KiReleaseTimerTableLock(), NULL, RemoveEntryList(), and _KTIMER_TABLE_ENTRY::Time.
Referenced by KeCancelTimer(), KeSetTimerEx(), KiInsertQueue(), and KiUnlinkThread().
VOID KiRestoreProcessorControlState (IN PKPROCESSOR_STATE ProcessorState)
Referenced by KiRestoreProcessorState().
VOID KiRestoreProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 23 of file ipi.c.
References CONTEXT_FULL, _KPROCESSOR_STATE::ContextFrame, KeContextToKframes(), KeGetCurrentPrcb(), KernelMode, KiRestoreProcessorControlState(), MODE_MASK, _KPRCB::ProcessorState, UNREFERENCED_PARAMETER, and UserMode.
Referenced by KiFreezeTargetExecution().
VOID FASTCALL KiRetireDpcList (PKPRCB Prcb)
Definition at line 1043 of file dpcsup.c.
References _disable(), _enable(), ASSERT, CONTAINING_RECORD, _KPRCB::DebugDpcTime, _KDPC::DeferredContext, _KPRCB::DeferredReadyListHead, _KDPC::DeferredRoutine, DISPATCH_LEVEL, DPC_NORMAL, _KDPC::DpcData, _KPRCB::DpcData, _KPRCB::DpcInterruptRequested, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _PERFINFO_DPC_INFORMATION::DpcRoutine, _KPRCB::DpcRoutineActive, FALSE, _LIST_ENTRY::Flink, _PERFINFO_DPC_INFORMATION::InitialTime, KeAcquireSpinLockAtDpcLevel(), KeGetCurrentIrql(), KeLowerIrql, KeMemoryBarrier(), KeRaiseIrqlToSynchLevel(), KeReleaseSpinLockFromDpcLevel(), KiProcessDeferredReadyList(), KiTimerExpiration(), _SINGLE_LIST_ENTRY::Next, NULL, PERF_DPC, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_DPC, PerfInfoLogBytes(), PerfTimeStamp, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _KDPC::SystemArgument1, _KDPC::SystemArgument2, _KPRCB::TimerHand, _KPRCB::TimerRequest, and TRUE.
VOID KiSaveProcessorControlState (IN PKPROCESSOR_STATE ProcessorState)
Referenced by ExpSystemErrorHandler(), KeBugCheck2(), KeSaveStateForHibernate(), KiInitializeKernel(), and KiSaveProcessorState().
VOID KiSaveProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 86 of file ipi.c.
References CONTEXT_FULL, _CONTEXT::ContextFlags, _KPROCESSOR_STATE::ContextFrame, KeContextFromKframes(), KeGetCurrentPrcb(), KiSaveProcessorControlState(), _KPRCB::ProcessorState, and UNREFERENCED_PARAMETER.
Referenced by KiFreezeTargetExecution().
PKTHREAD FASTCALL KiSelectNextThread (IN PKPRCB Prcb)
Definition at line 985 of file thredsup.c.
References ASSERT, _KTHREAD::BasePriority, KeIsSMTSetIdle(), KiSelectReadyThread(), KiSetIdleSummary(), KiSetSMTSummary(), NULL, _KTHREAD::Priority, and TRUE.
Referenced by KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), and KiSetAffinityThread().
FORCEINLINE PKTHREAD KiSelectReadyThread (IN KPRIORITY LowPriority, IN PKPRCB Prcb)
Definition at line 3522 of file ki.h.
References _KTHREAD::Affinity, AFFINITY_MASK, ASSERT, _KTHREAD::BasePriority, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeFindFirstSetLeftMember(), _KTHREAD::NextProcessor, NULL, _KTHREAD::Priority, PRIORITY_MASK, RemoveEntryList(), and _KTHREAD::WaitListEntry.
Referenced by KiAdjustQuantumThread(), KiIdleSchedule(), KiQuantumEnd(), KiSelectNextThread(), KiSetPriorityThread(), KiSwapThread(), and NtYieldExecution().
FORCEINLINE VOID KiSendFreeze (IN OUT KAFFINITY * Affinity, IN BOOLEAN Wait)
Definition at line 2697 of file ki.h.
References ClearMember, InterlockedCompareExchange(), IPI_FREEZE, _KPRCB::IpiFrozen, KeFindFirstSetLeftAffinity, KeYieldProcessor, KiIpiSend(), KiProcessorBlock, RUNNING, and UNREFERENCED_PARAMETER.
Referenced by KeBugCheck2(), and KeFreezeExecution().
FORCEINLINE VOID KiSendSoftwareInterrupt (IN KAFFINITY Affinity, IN KIRQL Level)
Definition at line 2628 of file ki.h.
References APC_LEVEL, IPI_APC, IPI_DPC, and KiIpiSend().
Referenced by KeFlushQueuedDpcs(), KeInsertQueueDpc(), and KiDeferredReadyThread().
FORCEINLINE VOID KiSendThawExecution (IN BOOLEAN Wait)
Definition at line 2792 of file ki.h.
References AFFINITY_MASK, ClearMember, FrozenState, _KPRCB::IpiFrozen, KeActiveProcessors, KeFindFirstSetLeftAffinity, KeGetCurrentPrcb(), KeGetCurrentProcessorNumber(), KeYieldProcessor, KiProcessorBlock, RUNNING, TARGET_FROZEN, TARGET_THAW, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeBugCheck2(), and KeThawExecution().
KAFFINITY FASTCALL KiSetAffinityThread (IN PKTHREAD Thread, IN KAFFINITY Affinity)
Definition at line 1057 of file thredsup.c.
References _KPROCESS::Affinity, AFFINITY_MASK, ASSERT, _KPRCB::CurrentThread, DeferredReady, FALSE, Index, INVALID_AFFINITY_SET, KeBugCheck(), KeFindNextRightSetAffinity(), KeNodeBlock, KeNumberNodes, KeProcessNodeSeed, KiAcquirePrcbLock(), KiAcquireThreadLock(), KiInsertDeferredReadyList(), KiProcessorBlock, KiReleasePrcbLock(), KiReleaseThreadLock(), KiRequestDispatchInterrupt, KiSelectNextThread(), _KPRCB::NextThread, NULL, _KPRCB::Number, PRIORITY_MASK, Ready, _KPRCB::ReadySummary, RemoveEntryList(), Running, _KPRCB::SetMember, Standby, _KTHREAD::State, TRUE, and _KTHREAD::UserAffinity.
Referenced by KeSetAffinityProcess(), and KeSetAffinityThread().
FORCEINLINE VOID KiSetContextSwapBusy (IN PKTHREAD Thread)
Definition at line 2902 of file ki.h.
References ASSERT, FALSE, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeTerminateThread(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiAttachProcess(), KiExitDispatcher(), KiIdleSchedule(), KiQuantumEnd(), and NtYieldExecution().
FORCEINLINE VOID KiSetContextSwapIdle (IN PKTHREAD Thread)
Definition at line 2941 of file ki.h.
References ASSERT, FALSE, TRUE, and UNREFERENCED_PARAMETER.
KCONTINUE_STATUS KiSetDebugProcessor (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame, IN KPROCESSOR_MODE PreviousMode)
FORCEINLINE VOID FASTCALL KiSetDueTime (IN PKTIMER Timer, IN LARGE_INTEGER Interval, OUT PULONG Hand)
Definition at line 1273 of file ki.h.
References FALSE, _LARGE_INTEGER::HighPart, KiComputeTimerTableIndex(), KiQueryInterruptTime, KiQuerySystemTime, _LARGE_INTEGER::QuadPart, and TRUE.
FORCEINLINE VOID KiSetIdleSummary (IN KAFFINITY Mask)
Definition at line 1358 of file ki.h.
References InterlockedOr(), and KiIdleSummary.
Referenced by KiSelectNextThread(), and KiSwapThread().
VOID KiSetInternalEvent (IN PKEVENT Event, IN PKTHREAD Thread)
Definition at line 1385 of file thredsup.c.
References BALANCE_INCREMENT, _LIST_ENTRY::Flink, and KiUnwaitThread().
Referenced by KeBalanceSetManager(), KeDetachProcess(), KeTerminateThread(), KeUnstackDetachProcess(), KiAttachProcess(), and KiReadyThread().
FORCEINLINE VOID KiSetSMTSummary (IN KAFFINITY Mask)
Definition at line 1452 of file ki.h.
References InterlockedOr(), and UNREFERENCED_PARAMETER.
Referenced by KiSelectNextThread(), and KiSwapThread().
VOID KiSetSystemTime (IN PLARGE_INTEGER NewTime, OUT PLARGE_INTEGER OldTime)
FORCEINLINE VOID KiSetTbFlushTimeStampBusy (VOID)
Definition at line 2262 of file ki.h.
References InterlockedBitTestAndSet(), InterlockedCompareExchange(), KeYieldProcessor, and KiTbFlushTimeStamp.
Referenced by KxFlushEntireTb().
BOOLEAN FASTCALL KiSignalTimer (__inout PKTIMER Timer)
Definition at line 199 of file timersup.c.
References FALSE, _LARGE_INTEGER::HighPart, Int32x32To64, IsListEmpty, KeInsertQueueDpc(), KiInsertTreeTimer(), KiQuerySystemTime, KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), _LARGE_INTEGER::LowPart, NULL, _LARGE_INTEGER::QuadPart, TIMER_EXPIRE_INCREMENT, TimerNotificationObject, TRUE, and ULongToPtr.
Referenced by KeSetTimerEx(), and KiCompleteTimer().
VOID KiSuspendNop (IN struct _KAPC * Apc, IN OUT PKNORMAL_ROUTINE * NormalRoutine, IN OUT PVOID * NormalContext, IN OUT PVOID * SystemArgument1, IN OUT PVOID * SystemArgument2)
Referenced by KeInitThread().
VOID KiSuspendRundown (IN PKAPC Apc)
Definition at line 80 of file thredsup.c.
References UNREFERENCED_PARAMETER.
Referenced by KeInitThread().
VOID KiSuspendThread (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 1636 of file thredsup.c.
References FALSE, KeGetCurrentThread(), KernelMode, KeWaitForSingleObject(), NULL, Suspended, _KTHREAD::SuspendSemaphore, and UNREFERENCED_PARAMETER.
Referenced by KeInitThread().
BOOLEAN FASTCALL KiSwapContext (IN PKTHREAD OldThread, IN PKTHREAD NewThread)
Referenced by KiExitDispatcher(), KiQuantumEnd(), and NtYieldExecution().
BOOLEAN KiSwapProcess (IN PKPROCESS NewProcess, IN PKPROCESS OldProcess)
Definition at line 337 of file kiamd64.h.
References ASSERT, KeGetCurrentPrcb(), SetMember, _KPRCB::SetMember, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeDetachProcess(), KeUnstackDetachProcess(), and KiAttachProcess().
LONG_PTR FASTCALL KiSwapThread (IN PKTHREAD OldThread, IN PKPRCB CurrentPrcb)
Definition at line 1691 of file thredsup.c.
References AFFINITY_MASK, ASSERT, FALSE, Index, KeFindFirstSetLeftAffinity, KeIsSMTSetIdle(), KeNumberNodes, KeNumberProcessors, KiAcquirePrcbLock(), KiAcquireTwoPrcbLocks(), KiClearIdleSummary(), KiClearSMTSummary(), KiFindReadyThread(), KiProcessDeferredReadyList(), KiProcessorBlock, KiReleasePrcbLock(), KiSelectReadyThread(), KiSetIdleSummary(), KiSetSMTSummary(), NULL, _KPRCB::ReadySummary, Running, _KTHREAD::State, and TRUE.
Referenced by KeDelayExecutionThread(), KeRemoveQueue(), KeTerminateThread(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), and KiAttachProcess().
VOID KiThreadStartup (IN PVOID StartContext)
Referenced by KiInitializeContextThread().
VOID KiTimerExpiration (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 504 of file dpcsup.c.
References _disable(), _enable(), ASSERT, CONTAINING_RECORD, _DPC_ENTRY::Context, _KDPC::DeferredContext, _KDPC::DeferredRoutine, DISPATCH_LEVEL, _DPC_ENTRY::Dpc, _KTIMER::Dpc, _KTIMER::DueTime, _KTIMER_TABLE_ENTRY::Entry, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, _LARGE_INTEGER::HighPart, Index, _DISPATCHER_HEADER::Inserted, Int32x32To64, IsListEmpty, KeGetCurrentPrcb(), KeInsertQueueDpc(), KeLowerIrql, KeNumberProcessors, KiAcquireTimerTableLock(), KiInsertTreeTimer(), KiLockDispatcherDatabase, KiProcessTimerDpcTable(), KiQueryInterruptTime, KiQueryLowTickCount, KiQuerySystemTime, KiReleaseTimerTableLock(), KiRemoveEntryTimer(), KiTimerTableListHead, KiTryToLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), _LARGE_INTEGER::LowPart, MAXIMUM_PROCESSORS, MAXIMUM_TIMERS_EXAMINED, MAXIMUM_TIMERS_PROCESSED, NULL, _KDPC::Number, _KPRCB::Number, _KTIMER::Period, PtrToLong, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, _DPC_ENTRY::Routine, _DISPATCHER_HEADER::SignalState, _KPRCB::ThreadDpcEnable, ThreadedDpcObject, _KTIMER_TABLE_ENTRY::Time, TIMER_EXPIRE_INCREMENT, TIMER_TABLE_SIZE, _KPRCB::TimerHand, TimerNotificationObject, _KDPC::Type, _DISPATCHER_HEADER::Type, ULongToPtr, UNREFERENCED_PARAMETER, and _DISPATCHER_HEADER::WaitListHead.
Referenced by KiInitSystem(), and KiRetireDpcList().
VOID FASTCALL KiTimerListExpire (IN PLIST_ENTRY ExpiredListHead, IN KIRQL OldIrql)
Definition at line 856 of file dpcsup.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _DPC_ENTRY::Context, Count, _KDPC::DeferredContext, _KDPC::DeferredRoutine, _DPC_ENTRY::Dpc, _KTIMER::Dpc, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, _LARGE_INTEGER::HighPart, _DISPATCHER_HEADER::Inserted, Int32x32To64, IsListEmpty, KeGetCurrentPrcb(), KeInsertQueueDpc(), KeLowerIrql, KiInsertTreeTimer(), KiLockDispatcherDatabase, KiProcessTimerDpcTable(), KiQuerySystemTime, KiUnlockDispatcherDatabase(), KiWaitTestSynchronizationObject(), KiWaitTestWithoutSideEffects(), _LARGE_INTEGER::LowPart, MAXIMUM_DPC_TABLE_SIZE, MAXIMUM_PROCESSORS, NULL, _KDPC::Number, _KPRCB::Number, _KTIMER::Period, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _DPC_ENTRY::Routine, _DISPATCHER_HEADER::SignalState, _KPRCB::ThreadDpcEnable, ThreadedDpcObject, TIMER_EXPIRE_INCREMENT, _KTIMER::TimerListEntry, TimerNotificationObject, _KDPC::Type, _DISPATCHER_HEADER::Type, ULongToPtr, and _DISPATCHER_HEADER::WaitListHead.
Referenced by KeSetSystemTime().
FORCEINLINE BOOLEAN KiTryToAcquireThreadLock (IN PKTHREAD Thread)
Definition at line 899 of file ki.h.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), and KzTryToAcquireSpinLock().
Referenced by KeSignalGateBoostPriority().
VOID KiUnexpectedInterrupt (VOID)
Referenced by KiInitializeBootStructures().
FORCEINLINE VOID FASTCALL KiUnlinkThread (IN PRKTHREAD Thread, IN LONG_PTR WaitStatus)
Definition at line 3046 of file ki.h.
References _KQUEUE::CurrentCount, FALSE, _KTIMER::Header, _DISPATCHER_HEADER::Inserted, KiRemoveTreeTimer(), _KWAIT_BLOCK::NextWaitBlock, NULL, RemoveEntryList(), and _KWAIT_BLOCK::WaitListEntry.
Referenced by KeSetEventBoostPriority(), and KiUnwaitThread().
FORCEINLINE VOID FASTCALL KiUnlockDispatcherDatabase (IN KIRQL OldIrql)
Definition at line 1600 of file ki.h.
References KiExitDispatcher(), and KiUnlockDispatcherDatabaseFromSynchLevel.
Referenced by ExpCheckForWorker(), ExpExpandResourceOwnerTable(), KeBoostPriorityThread(), KeCancelTimer(), KeCheckForTimer(), KeConnectInterrupt(), KeDelayExecutionThread(), KeDisconnectInterrupt(), KeInitializeMutant(), KePulseEvent(), KeQueryTimerDueTime(), KeReadyThread(), KeReleaseMutant(), KeReleaseSemaphore(), KeResetEvent(), KeRevertToUserAffinityThread(), KeRundownThread(), KeSetAffinityThread(), KeSetBasePriorityThread(), KeSetEvent(), KeSetEventBoostPriority(), KeSetIdealProcessorThread(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeSetProcess(), KeSetSystemAffinityThread(), KeSetSystemTime(), KeSetup80387OrEmulate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiInSwapKernelStacks(), KiInSwapProcesses(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), KiProcessTimerDpcTable(), KiScanReadyQueues(), KiTimerExpiration(), and KiTimerListExpire().
VOID FASTCALL KiUnwaitThread (IN PKTHREAD Thread, IN LONG_PTR WaitStatus, IN KPRIORITY Increment)
Definition at line 116 of file waitsup.c.
References AdjustUnwait, ASSERT, KiReadyThread(), and KiUnlinkThread().
Referenced by KeAlertResumeThread(), KeAlertThread(), KiActivateWaiterQueue(), KiInsertQueueApc(), KiSetInternalEvent(), KiWaitTest(), KiWaitTestSynchronizationObject(), and KiWaitTestWithoutSideEffects().
VOID KiUserApcDispatcher (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2, IN PKNORMAL_ROUTINE NormalRoutine)
VOID KiUserExceptionDispatcher (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextFrame)
VOID KiVerifyReadySummary (PKPRCB Prcb)
VOID FASTCALL KiWaitTest (IN PVOID Object, IN KPRIORITY Increment)
Definition at line 173 of file waitsup.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, _KEVENT::Header, KiUnwaitThread(), KiWaitSatisfyAny, _DISPATCHER_HEADER::SignalState, STATUS_KERNEL_APC, _KWAIT_BLOCK::Thread, WaitAny, _KWAIT_BLOCK::WaitKey, _DISPATCHER_HEADER::WaitListHead, and _KWAIT_BLOCK::WaitType.
Referenced by KeAlertResumeThread(), KeForceResumeThread(), KePulseEvent(), KeReleaseMutant(), KeReleaseSemaphore(), KeResumeThread(), KeRundownThread(), and KeThawAllThreads().
FORCEINLINE VOID KiWaitTestSynchronizationObject (IN PVOID Object, IN KPRIORITY Increment)
Definition at line 3268 of file ki.h.
References ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KEVENT::Header, IsListEmpty, KiUnwaitThread(), _DISPATCHER_HEADER::SignalState, STATUS_KERNEL_APC, _KWAIT_BLOCK::Thread, WaitAny, _KWAIT_BLOCK::WaitKey, _DISPATCHER_HEADER::WaitListHead, and _KWAIT_BLOCK::WaitType.
Referenced by KeSetEvent(), KeSetEventBoostPriority(), KiSignalTimer(), KiTimerExpiration(), and KiTimerListExpire().
FORCEINLINE VOID KiWaitTestWithoutSideEffects (IN PVOID Object, IN KPRIORITY Increment)
Definition at line 3341 of file ki.h.
References ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KEVENT::Header, IsListEmpty, KiUnwaitThread(), STATUS_KERNEL_APC, _KWAIT_BLOCK::Thread, WaitAny, _KWAIT_BLOCK::WaitKey, _DISPATCHER_HEADER::WaitListHead, and _KWAIT_BLOCK::WaitType.
Referenced by KeSetEvent(), KeSetProcess(), KeTerminateThread(), KiSignalTimer(), KiTimerExpiration(), and KiTimerListExpire().
FORCEINLINE VOID KxQueueReadyThread (IN PKTHREAD Thread, IN PKPRCB Prcb)
Definition at line 2531 of file ki.h.
References ASSERT, DeferredReady, FALSE, HIGH_PRIORITY, InsertHeadList(), InsertTailList(), KeGetCurrentPrcb(), KiDeferredReadyThread(), KiQueryLowTickCount, KiReleasePrcbLock(), Priority, PRIORITY_MASK, Ready, and Running.
Referenced by KiExitDispatcher(), KiQuantumEnd(), KiQueueReadyThread(), and NtYieldExecution().
FORCEINLINE VOID KzAcquireSpinLock (IN PKSPIN_LOCK SpinLock)
Definition at line 567 of file ki.h.
References InterlockedExchange(), InterlockedExchangeAcquire64, KeYieldProcessor, and UNREFERENCED_PARAMETER.
Referenced by KiAcquirePrcbLock(), KiAcquireThreadLock(), and KiAcquireTwoPrcbLocks().
FORCEINLINE BOOLEAN KzTryToAcquireSpinLock (IN PKSPIN_LOCK SpinLock)
Definition at line 619 of file ki.h.
References FALSE, FORCEINLINE, InterlockedExchange(), TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by KiTryToAcquireThreadLock().
Variable Documentation
ULONG KiAdjustDpcThreshold
Referenced by KeUpdateRunTime(), KiInitializeKernel(), KiInitSpinLocks(), NtQuerySystemInformation(), and NtSetSystemInformation().
UCHAR KiArgumentTable[]
Referenced by KiInitSystem().
PMESSAGE_RESOURCE_DATA KiBugCodeMessages
Definition at line 305 of file kernldat.c.
PKDEBUG_ROUTINE KiDebugRoutine
Definition at line 28 of file debug.c.
Referenced by KiDispatchException().
PKDEBUG_SWITCH_ROUTINE KiDebugSwitchRoutine
Definition at line 326 of file kernldat.c.
Referenced by KiFreezeTargetExecution().
ULONG KiDmaIoCoherency
Definition at line 312 of file kernldat.c.
Referenced by KeSetDmaIoCoherency().
ULONG KiEnableTimerWatchdog
Definition at line 505 of file kernldat.c.
CALL_PERFORMANCE_DATA KiFlushSingleCallData
ALIGNED_SPINLOCK KiFreezeExecutionLock
Definition at line 69 of file hifreqlk.c.
Referenced by KeFreezeExecution(), KeThawExecution(), KiFreezeTargetExecution(), and KiInitializeKernel().
ULONG KiFreezeFlag
Definition at line 339 of file kernldat.c.
Referenced by KeFreezeExecution(), and KeThawExecution().
ALIGNED_SPINLOCK KiFreezeLockBackup
Definition at line 70 of file hifreqlk.c.
Referenced by KeFreezeExecution(), KeThawExecution(), and KiFreezeTargetExecution().
FAST_MUTEX KiGenericCallDpcMutex
Definition at line 332 of file kernldat.c.
Referenced by KeGenericCallDpc(), and KiInitSystem().
volatile LONG KiHardwareTrigger
Definition at line 120 of file hifreqlk.c.
Referenced by KeBugCheck2(), and KeEnterKernelDebugger().
ULONG KiIdealDpcRate
Referenced by KeUpdateRunTime(), NtQuerySystemInformation(), and NtSetSystemInformation().
volatile KAFFINITY KiIdleSMTSummary
Referenced by KiDeferredReadyThread().
DECLSPEC_CACHEALIGN EPROCESS KiInitialProcess
Definition at line 346 of file kernldat.c.
Referenced by KeStartThread(), and KiInitializeBootStructures().
DECLSPEC_CACHEALIGN ETHREAD KiInitialThread
Definition at line 353 of file kernldat.c.
Referenced by KiInitializeBootStructures().
LONG KiMaximumDpcQueueDepth
Referenced by KeUpdateRunTime(), KiInitializeKernel(), KiInitSpinLocks(), NtQuerySystemInformation(), and NtSetSystemInformation().
ULONG KiMinimumDpcRate
Referenced by KiInitializeKernel(), KiInitSpinLocks(), NtQuerySystemInformation(), and NtSetSystemInformation().
KNODE KiNode0
Definition at line 390 of file kernldat.c.
Referenced by KeStartAllProcessors(), and KiInitializeKernel().
KNODE KiNodeInit[]
Definition at line 69 of file allproc.c.
Referenced by KeStartAllProcessors(), KiAllProcessorsStarted(), and KiInitializeKernel().
SINGLE_LIST_ENTRY KiProcessInSwapListHead
Definition at line 429 of file kernldat.c.
Referenced by KeSwapProcessOrStack(), KiAttachProcess(), KiInitSystem(), KiOutSwapProcesses(), and KiReadyThread().
LIST_ENTRY KiProcessListHead
Definition at line 422 of file kernldat.c.
Referenced by KeStartThread(), and KiInitializeKernel().
ALIGNED_SPINLOCK KiProcessListLock
Definition at line 71 of file hifreqlk.c.
Referenced by KeStartThread(), and KeTerminateThread().
SINGLE_LIST_ENTRY KiProcessOutSwapListHead
Definition at line 436 of file kernldat.c.
Referenced by KeDetachProcess(), KeSwapProcessOrStack(), KeTerminateThread(), KeUnstackDetachProcess(), KiInitSystem(), and KiOutSwapKernelStacks().
BOOLEAN KiProfileAlignmentFixup
Definition at line 459 of file kernldat.c.
Referenced by KeStartProfile(), and KeStopProfile().
ULONG KiProfileAlignmentFixupCount
Definition at line 473 of file kernldat.c.
ULONG KiProfileAlignmentFixupInterval
Definition at line 466 of file kernldat.c.
Referenced by KeQueryIntervalProfile(), and KeSetIntervalProfile().
ULONG KiProfileInterval
Definition at line 479 of file kernldat.c.
Referenced by KeQueryIntervalProfile(), and KeSetIntervalProfile().
LIST_ENTRY KiProfileListHead
Definition at line 485 of file kernldat.c.
Referenced by KeStartProfile(), and KiInitSystem().
ALIGNED_SPINLOCK KiProfileLock
Definition at line 72 of file hifreqlk.c.
Referenced by KeStartProfile(), KeStopProfile(), and KiInitSystem().
LIST_ENTRY KiProfileSourceListHead
Definition at line 452 of file kernldat.c.
Referenced by KeStartProfile(), KeStopProfile(), and KiInitSystem().
ALIGNED_SPINLOCK KiReverseStallIpiLock
Definition at line 73 of file hifreqlk.c.
Referenced by KeInvalidateAllCaches(), KeIpiGenericCall(), KiCompleteEffectiveRangeChange(), KiInitializePAT(), KiInitSpinLocks(), and KiLockStepOtherProcessors().
ULONG KiServiceLimit
ULONG_PTR KiServiceTable[]
Referenced by KiInitializeKernel(), and KiInitSystem().
CALL_PERFORMANCE_DATA KiSetEventCallData
SINGLE_LIST_ENTRY KiStackInSwapListHead
Definition at line 445 of file kernldat.c.
Referenced by KeSwapProcessOrStack(), KiInitSystem(), and KiReadyThread().
volatile ULONG KiSuspendState
Definition at line 366 of file kernldat.c.
KEVENT KiSwapEvent
Definition at line 410 of file kernldat.c.
Referenced by KeBalanceSetManager(), KeDetachProcess(), KeSwapProcessOrStack(), KeTerminateThread(), KeUnstackDetachProcess(), KiAttachProcess(), KiInitSystem(), KiOutSwapKernelStacks(), KiOutSwapProcesses(), and KiReadyThread().
PKTHREAD KiSwappingThread
Definition at line 416 of file kernldat.c.
Referenced by KeBalanceSetManager(), KeDetachProcess(), KeSwapProcessOrStack(), KeTerminateThread(), KeUnstackDetachProcess(), KiAttachProcess(), and KiReadyThread().
ULONG KiTickOffset
Referenced by KeSetTimeIncrement(), and KiCalibrateTimeAdjustment().
ULARGE_INTEGER KiTimeIncrementReciprocal
Referenced by KiInitializeKernel().
CCHAR KiTimeIncrementShiftCount
Referenced by KiInitializeKernel().
KAFFINITY KiTimeProcessor
KDPC KiTimerExpireDpc
Definition at line 492 of file kernldat.c.
Referenced by KiCalibrateTimeAdjustment(), and KiInitSystem().
DECLSPEC_CACHEALIGN KTIMER_TABLE_ENTRY KiTimerTableListHead[TIMER_TABLE_SIZE]
Definition at line 27 of file kernldat.c.
Referenced by KeCheckForTimer(), KeSetSystemTime(), KiInitSystem(), KiInsertTimerTable(), and KiTimerExpiration().
ALIGNED_SPINLOCK_STRUCT KiTimerTableLock[LOCK_QUEUE_TIMER_TABLE_LOCKS]
Definition at line 74 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
CALL_PERFORMANCE_DATA KiWaitSingleCallData