Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmsysini.c File Reference
cmsysini.c File Reference
#include "cmp.h"
#include "arc.h"
#include "arccodes.h"
Macros
#define CMP_KEY_INVALID_ATTRIBUTES
#define HKEY_PERFORMANCE_NLSTEXT ((HANDLE) (ULONG_PTR)((LONG)0x80000060))
#define HKEY_PERFORMANCE_TEXT ((HANDLE) (ULONG_PTR)((LONG)0x80000050))
#define INIT_REGISTRY_MASTERPATH L"\\REGISTRY\\"
#define MAX_NAME 128
#define SYSTEM_PATH L"\\registry\\machine\\system"
Functions
VOID CmBootLastKnownGood (__in ULONG ErrorLevel)
PHANDLE CmGetSystemDriverList (VOID)
BOOLEAN CmInitSystem1 (__in PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN CmIsLastKnownGoodBoot (VOID)
NTSTATUS CmpAddAliasEntry (IN HANDLE IDConfigDB, IN PROFILE_PARAMETER_BLOCK *ProfileBlock, IN ULONG ProfileNumber)
NTSTATUS CmpAddDockingInfo (IN HANDLE Key, IN PROFILE_PARAMETER_BLOCK *ProfileBlock)
NTSTATUS CmpCloneControlSet (VOID)
VOID CmpConfigureProcessors (VOID)
NTSTATUS CmpCreateControlSet (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS CmpCreateObjectTypes (VOID)
VOID CmpCreatePerfKeys (VOID)
VOID CmpCreatePredefined (IN HANDLE Root, IN PWSTR KeyName, IN HANDLE PredefinedHandle)
BOOLEAN CmpCreateRegistryRoot (VOID)
BOOLEAN CmpCreateRootNode (IN PHHIVE Hive, IN PWSTR Name, OUT PHCELL_INDEX RootCellIndex)
NTSTATUS CmpDeleteCloneTree (VOID)
NTSTATUS CmpDeleteCloneTree ()
VOID CmpDiskFullWarning (VOID)
VOID CmpFreeDriverList (IN PHHIVE Hive, IN PLIST_ENTRY DriverList)
NTSTATUS CmpHwprofileDefaultSelect (IN PCM_HARDWARE_PROFILE_LIST ProfileList, OUT PULONG ProfileIndexToUse, IN PVOID Context)
VOID CmpInitCallback (VOID)
NTSTATUS CmpInitHiveFromFile (IN PUNICODE_STRING FileName, IN ULONG HiveFlags, OUT PCMHIVE *CmHive, IN OUT PBOOLEAN Allocate, IN ULONG CheckFlags)
VOID CmpInitializeHiveList (VOID)
BOOLEAN CmpInitializeSystemHive (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS CmpInterlockedFunction (PWCHAR RegistryValueKey, VOID(*InterlockedFunction)(VOID))
NTSTATUS CmpLinkHiveToMaster (PUNICODE_STRING LinkName, HANDLE RootDirectory, PCMHIVE CmHive, BOOLEAN Allocate, PSECURITY_DESCRIPTOR SecurityDescriptor)
BOOLEAN CmpLinkKeyToHive (PWSTR KeyPath, PWSTR HivePath)
VOID CmpLoadHiveThread (IN PVOID StartContext)
VOID CmpMarkCurrentValueDirty (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell)
NTSTATUS CmpSaveBootControlSet (USHORT ControlSetNum)
NTSTATUS CmpSetNetworkValue (IN PNETWORK_LOADER_BLOCK NetworkLoaderBlock)
NTSTATUS CmpSetSystemValues (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS CmpSetupPrivateWrite (PCMHIVE CmHive)
Variables
BOOLEAN CmFirstTime
BOOLEAN CmpCannotWriteConfiguration
ULONG CmpCheckHiveIndex
PWCHAR CmpControlSessionManager
LIST_ENTRY CmpHiveListHead
POBJECT_TYPE CmpKeyObjectType
UNICODE_STRING CmpLoadOptions
KEVENT CmpLoadWorkerDebugEvent
KEVENT CmpLoadWorkerEvent
LONG CmpLoadWorkerIncrement = 0
HIVE_LIST_ENTRY CmpMachineHiveList []
PCMHIVE CmpMasterHive
BOOLEAN CmpNoMasterCreates
BOOLEAN CmpNoWrite
EX_PUSH_LOCK CmpPostLock
PWCHAR CmpProcessorControl
ERESOURCE CmpRegistryLock
LIST_ENTRY CmpSelfHealQueueListHead
KGUARDED_MUTEX CmpSelfHealQueueLock
PUCHAR CmpStashBuffer
ULONG CmpStashBufferSize
UNICODE_STRING CmpSystemFileName
BOOLEAN CmpSystemHiveConversionFailed = FALSE
PKPROCESS CmpSystemProcess
BOOLEAN CmpTrackHiveClose
ULONG CmSelfHeal = 1
UNICODE_STRING CmSymbolicLinkValueName
BOOLEAN HvShutdownComplete
const UNICODE_STRING nullclass
UCHAR SystemHiveFullPathBuffer []
UNICODE_STRING SystemHiveFullPathName
Macro Definition Documentation
#define CMP_KEY_INVALID_ATTRIBUTES
Value:
(OBJ_EXCLUSIVE  |\
                                     OBJ_PERMANENT)
Definition at line 105 of file cmsysini.c.
Referenced by CmpCreateObjectTypes().
#define HKEY_PERFORMANCE_NLSTEXT ((HANDLE) (ULONG_PTR)((LONG)0x80000060))
Definition at line 62 of file cmsysini.c.
Referenced by CmpCreatePerfKeys().
#define HKEY_PERFORMANCE_TEXT ((HANDLE) (ULONG_PTR)((LONG)0x80000050))
Definition at line 61 of file cmsysini.c.
Referenced by CmpCreatePerfKeys().
#define INIT_REGISTRY_MASTERPATH L"\\REGISTRY\\"
Definition at line 39 of file cmsysini.c.
Referenced by CmpInitializeHiveList(), and CmpLoadHiveThread().
#define MAX_NAME 128
Referenced by CmpInitializeHiveList(), and CmpLoadHiveThread().
#define SYSTEM_PATH L"\\registry\\machine\\system"
Definition at line 56 of file cmsysini.c.
Function Documentation
VOID CmBootLastKnownGood (__in ULONG ErrorLevel)
Definition at line 3331 of file cmsysini.c.
References BAD_LAST_KNOWN_GOOD, CM_BUGCHECK, CM_PAGED_CODE, CmFirstTime, CmIsLastKnownGoodBoot(), CRITICAL_SERVICE_FAILED, CriticalError, ESUCCESS, HalRebootRoutine, HalReturnToFirmware(), HalSetEnvironmentVariable(), IgnoreError, NormalError, SET_ENV_VAR_FAILED, SevereError, Status, and TRUE.
Referenced by IopLoadDriver().
PHANDLE CmGetSystemDriverList (VOID)
Definition at line 1747 of file cmsysini.c.
References CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpFindControlSet(), CmpFindDrivers(), CmpFreeDriverList(), CmpLockRegistryExclusive(), CmpResolveDriverDependencies(), CmpSortDriverList(), CmpUnlockRegistry(), CONFIG_INITIALIZATION_FAILED, CONTAINING_RECORD, DPFLTR_CONFIG_ID, DriverEntry(), ExAllocatePool, _LIST_ENTRY::Flink, Handle, HCELL_NIL, Hive, INIT_SYSTEM_DRIVER_LIST, InitializeListHead(), InitializeObjectAttributes, KernelMode, KEY_QUERY_VALUE, KEY_READ, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NonPagedPool, NT_SUCCESS, NtClose(), NtOpenKey(), NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByHandle, _BOOT_DRIVER_LIST_ENTRY::RegistryPath, RtlInitUnicodeString(), Status, and SystemLoad.
BOOLEAN CmInitSystem1 (__in PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 311 of file cmsysini.c.
References _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_PAGED_CODE, CM_TRACK_QUOTA_START, _HIVE_LIST_ENTRY::CmHive, CmKdPrintEx, CML_BUGCHECK, CML_INIT, CmpAddToHiveFileList(), CmpComputeGlobalQuotaAllowed(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreateRegistryRoot(), CmpHiveListHeadLock, CmpHiveRootSecurityDescriptor(), CmpInitCallback(), CmpInitCmPrivateAlloc(), CmpInitCmPrivateDelayAlloc(), CmpInitDelayDerefKCBEngine(), CmpInitializeCache(), CmpInitializeHardwareConfiguration(), CmpInitializeHive(), CmpInitializeMachineDependentConfiguration(), CmpInitializeRegistryNames(), CmpInitializeSystemHive(), CmpLinkHiveToMaster(), CmpLoadHiveLock, CmpLockRegistryExclusive(), CmpMiniNTBoot, CmpNoMasterCreates, CmpSetNetworkValue(), CmpSetSystemValues(), CmpShareSystemHives, CmpStashBuffer, CmpStashBufferLock, CmpStashBufferSize, CmpUnlockRegistry(), CmRegistryMachineHardwareName, CmRegistryMachineName, CmRegistryUserName, CONFIG_INITIALIZATION_FAILED, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, ExAllocatePoolWithTag, ExFreePool(), ExInitializePushLock(), ExInitializeResourceLite(), HFILE_TYPE_PRIMARY, HINIT_CREATE, HIVE_VOLATILE, INIT_SYSTEM1, InitializeListHead(), InitializeObjectAttributes, InitIsWinPEMode, KeInitializeGuardedMutex(), KEY_READ, KEY_WRITE, NT_SUCCESS, NtClose(), NtCreateKey(), NULL, OBJ_CASE_INSENSITIVE, PAGE_SIZE, PagedPool, _EPROCESS::Pcb, PsGetCurrentProcess(), RTL_SIZEOF_THROUGH_FIELD, STATUS_SUCCESS, and TRUE.
Referenced by Phase1InitializationDiscard().
BOOLEAN CmIsLastKnownGoodBoot (VOID)
Definition at line 3416 of file cmsysini.c.
References ASSERT, CM_PAGED_CODE, CmKdPrintEx, CML_INIT, DPFLTR_CONFIG_ID, FALSE, NT_SUCCESS, NULL, REG_DWORD, REG_NONE, RTL_QUERY_REGISTRY_DIRECT, RTL_REGISTRY_ABSOLUTE, RtlQueryRegistryValues(), Status, and TRUE.
Referenced by CmBootLastKnownGood().
NTSTATUS CmpAddAliasEntry (IN HANDLE IDConfigDB, IN PROFILE_PARAMETER_BLOCK * ProfileBlock, IN ULONG ProfileNumber)
Definition at line 2255 of file cmsysini.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_HARDWARE_PROFILE_STR_ALIAS, CM_HARDWARE_PROFILE_STR_PROFILE_NUMBER, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpAddDockingInfo(), DPFLTR_CONFIG_ID, FALSE, InitializeObjectAttributes, KEY_READ, KEY_WRITE, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NtCreateKey(), NtOpenKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, REG_DWORD, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), sprintf(), STATUS_OBJECT_NAME_NOT_FOUND, and STATUS_SUCCESS.
Referenced by CmpCreateControlSet().
NTSTATUS CmpAddDockingInfo (IN HANDLE Key, IN PROFILE_PARAMETER_BLOCK * ProfileBlock)
Definition at line 2179 of file cmsysini.c.
References CM_HARDWARE_PROFILE_STR_CAPABILITIES, CM_HARDWARE_PROFILE_STR_DOCKID, CM_HARDWARE_PROFILE_STR_DOCKING_STATE, CM_HARDWARE_PROFILE_STR_SERIAL_NUMBER, CM_PAGED_CODE, NT_SUCCESS, NtSetValueKey(), REG_DWORD, RtlInitUnicodeString(), and STATUS_SUCCESS.
Referenced by CmpAddAliasEntry(), and CmpCreateControlSet().
NTSTATUS CmpCloneControlSet (VOID)
Definition at line 2855 of file cmsysini.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpCopyTree, CmpLockRegistryExclusive(), CmpRebuildKcbCache(), CmpUnlockRegistry(), DACL_SECURITY_INFORMATION, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), InitializeObjectAttributes, KernelMode, KEY_READ, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NtClose(), NtCreateKey(), NtOpenKey(), NtQuerySecurityObject(), NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByHandle, PagedPool, REG_CREATED_NEW_KEY, REG_OPTION_VOLATILE, RtlInitUnicodeString(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_REGISTRY_CORRUPT, and STATUS_SUCCESS.
VOID CmpConfigureProcessors (VOID)
Definition at line 1533 of file cmsysini.c.
References AFFINITY_MASK, CM_PAGED_CODE, KeNumberProcessors, KeOptimizeProcessorControlState(), KeRevertToUserAffinityThread(), and KeSetSystemAffinityThread().
NTSTATUS CmpCreateControlSet (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 2435 of file cmsysini.c.
References ASSERT, ASSERTMSG, _UNICODE_STRING::Buffer, CM_HARDWARE_PROFILE_STR_CURRENT_DOCK_INFO, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpAddAliasEntry(), CmpAddDockingInfo(), CmpCloneHwProfile(), CmpHwprofileDefaultSelect(), CmSetAcpiHwProfile(), _KEY_VALUE_FULL_INFORMATION::DataOffset, _PROFILE_PARAMETER_BLOCK::DockingState, _PROFILE_ACPI_DOCKING_STATE::DockingState, DPFLTR_CONFIG_ID, FALSE, HW_PROFILE_DOCKSTATE_UNDOCKED, HW_PROFILE_STATUS_ALIAS_MATCH, HW_PROFILE_STATUS_FAILURE, HW_PROFILE_STATUS_PRISTINE_MATCH, HW_PROFILE_STATUS_SUCCESS, HW_PROFILE_STATUS_TRUE_MATCH, InitializeObjectAttributes, KEY_CREATE_LINK, KEY_READ, KEY_WRITE, KeyValueFullInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NtCreateKey(), NtOpenKey(), NtQueryValueKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, _LOADER_PARAMETER_EXTENSION::Profile, REG_CREATED_NEW_KEY, REG_DWORD, REG_LINK, REG_OPTION_CREATE_LINK, REG_OPTION_VOLATILE, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), _PROFILE_ACPI_DOCKING_STATE::SerialLength, _PROFILE_ACPI_DOCKING_STATE::SerialNumber, sprintf(), _PROFILE_PARAMETER_BLOCK::Status, Status, STATUS_SUCCESS, and TRUE.
Referenced by CmInitSystem1().
NTSTATUS CmpCreateObjectTypes (VOID)
Definition at line 915 of file cmsysini.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CMP_KEY_INVALID_ATTRIBUTES, CmpCloseKeyObject(), CmpDeleteKeyObject(), CmpParseKey(), CmpQueryKeyName(), CmpSecurityMethod(), _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, DPFLTR_CONFIG_ID, _OBJECT_TYPE_INITIALIZER::DumpProcedure, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KEY_ALL_ACCESS, KEY_EXECUTE, KEY_READ, KEY_WRITE, _OBJECT_TYPE_INITIALIZER::Length, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, NT_SUCCESS, NULL, ObCreateObjectType(), _OBJECT_TYPE_INITIALIZER::OpenProcedure, PagedPool, _OBJECT_TYPE_INITIALIZER::ParseProcedure, _OBJECT_TYPE_INITIALIZER::PoolType, _OBJECT_TYPE_INITIALIZER::QueryNameProcedure, RtlInitUnicodeString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, _OBJECT_TYPE_INITIALIZER::SecurityRequired, Status, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by CmInitSystem1().
VOID CmpCreatePerfKeys (VOID)
Definition at line 3580 of file cmsysini.c.
References CmpCreatePredefined(), CmpRegistryPerflibString, HKEY_PERFORMANCE_NLSTEXT, HKEY_PERFORMANCE_TEXT, InitializeObjectAttributes, KEY_WRITE, LANGIDFROMLCID, NT_SUCCESS, NtOpenKey(), NULL, OBJ_CASE_INSENSITIVE, PsDefaultSystemLocaleId, PsDefaultUILanguageId, RtlInitUnicodeString(), and Status.
Referenced by CmpInitializeHiveList().
VOID CmpCreatePredefined (IN HANDLE Root, IN PWSTR KeyName, IN HANDLE PredefinedHandle)
Definition at line 3657 of file cmsysini.c.
References ASSERT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CmpMiniNTBoot, _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _CM_PARSE_CONTEXT::Disposition, FALSE, Handle, InitializeObjectAttributes, KernelMode, KEY_READ, _UNICODE_STRING::Length, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObOpenObjectByName(), _CM_PARSE_CONTEXT::OriginatingPoint, _CM_PARSE_CONTEXT::PredefinedHandle, REG_OPTION_PREDEF_HANDLE, REG_OPTION_VOLATILE, RtlInitUnicodeString(), Status, _CM_PARSE_CONTEXT::TitleIndex, TRUE, and ZwClose().
Referenced by CmpCreatePerfKeys().
BOOLEAN CmpCreateRegistryRoot (VOID)
Definition at line 1003 of file cmsysini.c.
References ASSERT, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpCreateKeyControlBlock(), CmpCreateRootNode(), CmpHiveRootSecurityDescriptor(), CmpRegistryRootHandle, CmRegistryRootName, DPFLTR_CONFIG_ID, EnlistKeyBodyWithKCB(), ExFreePool(), FALSE, _CMHIVE::Hive, HvGetCell, InitializeObjectAttributes, KernelMode, KEY_BODY_TYPE, KEY_READ, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_BODY::NotifyBlock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByHandle, _CM_KEY_BODY::ProcessID, PsGetCurrentProcessId(), Status, TRUE, _CM_KEY_BODY::Type, and UserMode.
Referenced by CmInitSystem1().
BOOLEAN CmpCreateRootNode (IN PHHIVE Hive, IN PWSTR Name, OUT PHCELL_INDEX RootCellIndex)
Definition at line 1167 of file cmsysini.c.
References _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CM_KEY_NODE_SIGNATURE, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpCopyName(), CmpHKeyNodeSize, _CHILD_LIST::Count, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, Hive, HvAllocateCell(), HvGetCell, HvReleaseCell, KeQuerySystemTime(), KEY_COMP_NAME, KEY_HIVE_ENTRY, KEY_NO_DELETE, _CM_KEY_REFERENCE::KeyCell, _CM_KEY_REFERENCE::KeyHive, _CELL_DATA::_u::KeyNode, _CM_KEY_NODE::LastWriteTime, _UNICODE_STRING::Length, _CHILD_LIST::List, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, _CM_KEY_NODE::Parent, RtlInitUnicodeString(), _CM_KEY_NODE::Security, _CM_KEY_NODE::Signature, Stable, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpCreateRegistryRoot().
NTSTATUS CmpDeleteCloneTree (VOID)
NTSTATUS CmpDeleteCloneTree ()
Definition at line 3300 of file cmsysini.c.
References CmRegistrySystemCloneName, InitializeObjectAttributes, NtUnloadKey(), NULL, and OBJ_CASE_INSENSITIVE.
VOID CmpDiskFullWarning (VOID)
Definition at line 701 of file cmworker.c.
References CmpCannotWriteConfiguration, CmpDiskFullWarningWorker(), CmpDiskFullWorkerPopupDisplayed, CmpProfileLoaded, DelayedWorkQueue, ExAllocatePool, ExInitializeWorkItem, ExQueueWorkItem(), ExReadyForErrors, NonPagedPool, NULL, and TRUE.
Referenced by CmpLazyFlushWorker(), and CmpLoadHiveThread().
VOID CmpFreeDriverList (IN PHHIVE Hive, IN PLIST_ENTRY DriverList)
Definition at line 1958 of file cmsysini.c.
References _UNICODE_STRING::Buffer, CM_PAGED_CODE, _BOOT_DRIVER_LIST_ENTRY::FilePath, _LIST_ENTRY::Flink, _UNICODE_STRING::Length, _BOOT_DRIVER_NODE::ListEntry, _UNICODE_STRING::MaximumLength, _BOOT_DRIVER_NODE::Name, NULL, and _BOOT_DRIVER_LIST_ENTRY::RegistryPath.
Referenced by CmGetSystemDriverList().
NTSTATUS CmpHwprofileDefaultSelect (IN PCM_HARDWARE_PROFILE_LIST ProfileList, OUT PULONG ProfileIndexToUse, IN PVOID Context)
Definition at line 2417 of file cmsysini.c.
References STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateControlSet().
VOID CmpInitCallback (VOID)
Definition at line 322 of file cmhook.c.
References CM_MAX_CALLBACKS, CmpCallBackCount, ExInitializeCallBack(), and PAGED_CODE.
Referenced by CmInitSystem1().
NTSTATUS CmpInitHiveFromFile (IN PUNICODE_STRING FileName, IN ULONG HiveFlags, OUT PCMHIVE * CmHive, IN OUT PBOOLEAN Allocate, IN ULONG CheckFlags)
Definition at line 2011 of file cmsysini.c.
References CM_PAGED_CODE, CmpInitializeHive(), CmpOpenHiveFiles(), CmpRaiseSelfHealWarning(), CmpSetHandleProtection, CmpShareSystemHives, CmpTrackHiveClose, ExAllocatePoolWithTag, FALSE, FILE_CREATED, HBOOT_SELFHEAL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, HINIT_CREATE, HINIT_FILE, HINIT_MAPFILE, HvShutdownComplete, NT_SUCCESS, NULL, PagedPool, PROTECTED_POOL, RtlCopyMemory, Status, STATUS_RETRY, STATUS_SUCCESS, STATUS_TOO_LATE, TRUE, and ZwClose().
Referenced by CmpCmdHiveOpen(), and CmpLoadHiveThread().
VOID CmpInitializeHiveList (VOID)
Definition at line 687 of file cmsysini.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, BAD_CORE_HIVE, BAD_HIVE_LIST, BAD_SYSTEM_CONFIG_INFO, _STRING::Buffer, _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_NUMBER_OF_MACHINE_HIVES, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CML_INIT, CmpAddToHiveFileList(), CmpCreatePerfKeys(), CmpHiveRootSecurityDescriptor(), CmpLinkHiveToMaster(), CmpLinkKeyToHive(), CmpLoadHiveThread(), CmpNoMasterCreates, CmpNoWrite, CmpShareSystemHives, CmpSpecialBootCondition, CONFIG_LIST_FAILED, DPFLTR_CONFIG_ID, Executive, ExFreePool(), FALSE, _HIVE_LIST_ENTRY::HHiveFlags, HIVE_VOLATILE, HvSyncHive(), INIT_REGISTRY_MASTERPATH, INIT_SYSTEMROOT_HIVEPATH, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _STRING::Length, _UNICODE_STRING::Length, MAX_NAME, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, PsCreateSystemThread(), RtlAppendStringToString(), RtlInitUnicodeString(), Status, STATUS_SUCCESS, SynchronizationEvent, THREAD_ALL_ACCESS, TRUE, and ZwClose().
Referenced by CmpCmdInit().
BOOLEAN CmpInitializeSystemHive (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 1574 of file cmsysini.c.
References BAD_SYSTEM_CONFIG_INFO, BAD_SYSTEM_HIVE, _HHIVE::BaseBlock, _HBASE_BLOCK::BootType, _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_CHECK_REGISTRY_SYSTEM_CLEAN, CM_PAGED_CODE, _HIVE_LIST_ENTRY::CmHive, CmKdPrintEx, CML_BUGCHECK, CmpBootType, CmpHiveRootSecurityDescriptor(), CmpInitializeHive(), CmpLinkHiveToMaster(), CmpSelfHeal, CmpShareSystemHives, CmRegistryMachineSystemName, CmSelfHeal, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, HBOOT_SELFHEAL, HFILE_TYPE_LOG, HINIT_CREATE, HINIT_MEMORY, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, HIVE_VOLATILE, _HHIVE::HiveFlags, _STRING::Length, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, PagedPool, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), Status, SYSTEM_HIVE_INDEX, TRUE, and UNICODE_NULL.
Referenced by CmInitSystem1().
NTSTATUS CmpInterlockedFunction (PWCHAR RegistryValueKey, VOID(*)(VOID) InterlockedFunction)
Definition at line 1392 of file cmsysini.c.
References CM_PAGED_CODE, CmpControlSessionManager, CmRegistryMachineSystemCurrentControlSet, InitializeObjectAttributes, KEY_READ, KEY_WRITE, KeyValuePartialInformation, NT_SUCCESS, NtClose(), NtFlushKey(), NtOpenKey(), NtQueryValueKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, REG_DWORD, RtlInitUnicodeString(), and STATUS_UNSUCCESSFUL.
NTSTATUS CmpLinkHiveToMaster (PUNICODE_STRING LinkName, HANDLE RootDirectory, PCMHIVE CmHive, BOOLEAN Allocate, PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 1267 of file cmsysini.c.
References ASSERT, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::ChildHive, _CM_PARSE_CONTEXT::Class, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CmpReportNotify(), _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _HHIVE::DirtyFlag, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, _CMHIVE::Hive, InitializeObjectAttributes, KernelMode, KEY_READ, KEY_WRITE, _CM_KEY_REFERENCE::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_REFERENCE::KeyHive, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, REG_NOTIFY_CHANGE_NAME, _HBASE_BLOCK::RootCell, Status, STATUS_SUCCESS, _CM_PARSE_CONTEXT::TitleIndex, TRUE, and ZwClose().
Referenced by CmInitSystem1(), CmLoadKey(), CmpInitializeHiveList(), CmpInitializeSystemHive(), and CmpLoadHiveVolatile().
BOOLEAN CmpLinkKeyToHive (PWSTR KeyPath, PWSTR HivePath)
Definition at line 3494 of file cmsysini.c.
References _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, DPFLTR_CONFIG_ID, FALSE, InitializeObjectAttributes, KEY_CREATE_LINK, KeyName, _UNICODE_STRING::Length, NT_SUCCESS, NtClose(), NtCreateKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, REG_CREATED_NEW_KEY, REG_LINK, REG_OPTION_CREATE_LINK, REG_OPTION_VOLATILE, RtlInitUnicodeString(), Status, and TRUE.
Referenced by CmpInitializeHiveList().
VOID CmpLoadHiveThread (IN PVOID StartContext)
Definition at line 3792 of file cmsysini.c.
References _HIVE_LIST_ENTRY::Allocate, ASSERT, BAD_HIVE_LIST, BAD_SYSTEM_CONFIG_INFO, _HHIVE::BaseBlock, _HBASE_BLOCK::BootRecover, _STRING::Buffer, _UNICODE_STRING::Buffer, _HHIVE::Cluster, CM_BUGCHECK, CM_CHECK_REGISTRY_CHECK_CLEAN, CM_NUMBER_OF_MACHINE_HIVES, CM_PAGED_CODE, _HIVE_LIST_ENTRY::CmHive, _HIVE_LIST_ENTRY::CmHive2, _HIVE_LIST_ENTRY::CmHiveFlags, CmKdPrintEx, CML_INIT, CmpCannotWriteConfiguration, CmpDiskFullWarning(), CmpFileSetSize(), CmpInitHiveFromFile(), CmpMarkCurrentValueDirty(), CmpMiniNTBoot, CmpOpenHiveFiles(), CmpSetupPrivateWrite(), CmpShareSystemHives, CmpTrackHiveClose, DbgBreakPoint(), DbgPrintEx(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, Executive, ExRaiseHardError(), FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, _CMHIVE::Flags, HBLOCK_SIZE, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, Hive, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, HIVE_VOLATILE, _HHIVE::HiveFlags, HvSyncHive(), Index, INIT_REGISTRY_MASTERPATH, INIT_SYSTEMROOT_HIVEPATH, InterlockedIncrement, KernelMode, KeSetEvent(), KeWaitForSingleObject(), _HHIVE::_DUAL::Length, _STRING::Length, _UNICODE_STRING::Length, MAX_NAME, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, OptionOk, PsTerminateSystemThread(), _HBASE_BLOCK::RootCell, RtlAppendStringToString(), RtlAreBitsClear(), RtlInitUnicodeString(), RtlNumberOfSetBits(), RtlSetAllBits(), RtlSetBits(), _RTL_BITMAP::SizeOfBitMap, Stable, STATUS_CANNOT_LOAD_REGISTRY_FILE, STATUS_RETRY, STATUS_SUCCESS, _HHIVE::Storage, SYSTEM_HIVE_INDEX, SystemHiveFullPathBuffer, _HIVE_LIST_ENTRY::ThreadFinished, _HIVE_LIST_ENTRY::ThreadStarted, TRUE, and ZwClose().
Referenced by CmpInitializeHiveList().
VOID CmpMarkCurrentValueDirty (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell)
Definition at line 4378 of file cmsysini.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_PAGED_CODE, CmpFindSubKeyByName(), CmpFindValueByName(), FALSE, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, NULL, and RtlInitUnicodeString().
Referenced by CmpLoadHiveThread().
NTSTATUS CmpSaveBootControlSet (USHORT ControlSetNum)
Definition at line 3036 of file cmsysini.c.
References CmpCopyTreeEx, CmpLockRegistryExclusive(), CmpRebuildKcbCache(), CmpSyncTrees, CmpUnlockRegistry(), CmRegistryMachineSystemCurrentControlSet, DACL_SECURITY_INFORMATION, ExAllocatePool, ExFreePool(), FALSE, HvGetCell, HvMarkCellDirty(), HvReleaseCell, InitializeObjectAttributes, KernelMode, KEY_READ, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_NODE::MaxNameLen, NT_SUCCESS, NtClose(), NtCreateKey(), NtOpenKey(), NtQuerySecurityObject(), NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, ObReferenceObjectByHandle, PagedPool, REG_CREATED_NEW_KEY, REG_OPTION_NON_VOLATILE, RtlInitUnicodeString(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, and swprintf.
NTSTATUS CmpSetNetworkValue (IN PNETWORK_LOADER_BLOCK NetworkLoaderBlock)
Definition at line 4173 of file cmsysini.c.
References ASSERT, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, InitializeObjectAttributes, KEY_ALL_ACCESS, NT_SUCCESS, NtClose(), NtCreateKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, REG_BINARY, RtlInitUnicodeString(), and STATUS_SUCCESS.
Referenced by CmInitSystem1().
NTSTATUS CmpSetSystemValues (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 4269 of file cmsysini.c.
References ASSERT, _UNICODE_STRING::Buffer, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, InitializeObjectAttributes, KEY_ALL_ACCESS, _UNICODE_STRING::Length, NT_SUCCESS, NtClose(), NtOpenKey(), NtSetValueKey(), NULL, OBJ_CASE_INSENSITIVE, REG_SZ, RtlCreateUnicodeStringFromAsciiz(), RtlFreeUnicodeString(), RtlInitUnicodeString(), and STATUS_SUCCESS.
Referenced by CmInitSystem1().
NTSTATUS CmpSetupPrivateWrite (PCMHIVE CmHive)
Definition at line 3727 of file cmsysini.c.
References CM_PAGED_CODE, CmpAcquireFileObjectForFile(), FileOffset, _HHIVE::GetCellRoutine, HFILE_TYPE_PRIMARY, HvpGetCellMapped(), HvpReleaseCellMapped(), NT_SUCCESS, _HHIVE::ReleaseCellRoutine, Status, STATUS_REGISTRY_IO_FAILED, and STATUS_SUCCESS.
Referenced by CmpLoadHiveThread().
Variable Documentation
BOOLEAN CmFirstTime
Definition at line 342 of file cmdat.c.
Referenced by CmBootLastKnownGood().
BOOLEAN CmpCannotWriteConfiguration
Definition at line 52 of file cmdat2.c.
Referenced by CmpLoadHiveThread().
ULONG CmpCheckHiveIndex
Definition at line 147 of file cmdat2.c.
PWCHAR CmpControlSessionManager
Definition at line 270 of file cmdat.c.
Referenced by CmpInterlockedFunction().
LIST_ENTRY CmpHiveListHead
Definition at line 312 of file cmdat.c.
POBJECT_TYPE CmpKeyObjectType
Definition at line 320 of file cmdat.c.
UNICODE_STRING CmpLoadOptions
Definition at line 36 of file cmdat.c.
KEVENT CmpLoadWorkerDebugEvent
Definition at line 684 of file cmsysini.c.
KEVENT CmpLoadWorkerEvent
Definition at line 682 of file cmsysini.c.
LONG CmpLoadWorkerIncrement = 0
Definition at line 683 of file cmsysini.c.
HIVE_LIST_ENTRY CmpMachineHiveList[]
Definition at line 284 of file cmdat.c.
PCMHIVE CmpMasterHive
Definition at line 305 of file cmdat.c.
BOOLEAN CmpNoMasterCreates
Definition at line 306 of file cmdat.c.
Referenced by CmInitSystem1(), and CmpInitializeHiveList().
BOOLEAN CmpNoWrite
Definition at line 330 of file cmdat.c.
Referenced by CmpInitializeHiveList().
EX_PUSH_LOCK CmpPostLock
Definition at line 24 of file cmsubs.c.
PWCHAR CmpProcessorControl
Definition at line 269 of file cmdat.c.
ERESOURCE CmpRegistryLock
Definition at line 52 of file cmsubs3.c.
LIST_ENTRY CmpSelfHealQueueListHead
Definition at line 693 of file cmgquota.c.
KGUARDED_MUTEX CmpSelfHealQueueLock
Definition at line 694 of file cmgquota.c.
PUCHAR CmpStashBuffer
Definition at line 64 of file cmdat2.c.
Referenced by CmInitSystem1().
ULONG CmpStashBufferSize
Definition at line 65 of file cmdat2.c.
Referenced by CmInitSystem1().
UNICODE_STRING CmpSystemFileName
Definition at line 221 of file cmdat.c.
BOOLEAN CmpSystemHiveConversionFailed = FALSE
Definition at line 3724 of file cmsysini.c.
PKPROCESS CmpSystemProcess
Definition at line 56 of file cmworker.c.
BOOLEAN CmpTrackHiveClose
Definition at line 56 of file cmmapvw.c.
Referenced by CmpInitHiveFromFile(), and CmpLoadHiveThread().
ULONG CmSelfHeal = 1
Definition at line 141 of file cmsysini.c.
Referenced by CmpInitializeSystemHive().
UNICODE_STRING CmSymbolicLinkValueName
Definition at line 222 of file cmdat.c.
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by CmpInitHiveFromFile().
const UNICODE_STRING nullclass
Definition at line 193 of file cmdat.c.
UCHAR SystemHiveFullPathBuffer[]
Definition at line 295 of file cmdat.c.
Referenced by CmpLoadHiveThread().
UNICODE_STRING SystemHiveFullPathName
Definition at line 296 of file cmdat.c.