Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/queueobj.c File Reference
queueobj.c File Reference
#include "ki.h"
Macros
#define InitializeRemoveQueue()
Functions
VOID KeInitializeQueue (__out PRKQUEUE Queue, __in ULONG Count)
LONG KeInsertHeadQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
LONG KeInsertQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
LONG KeReadStateQueue (__in PRKQUEUE Queue)
PLIST_ENTRY KeRemoveQueue (__inout PRKQUEUE Queue, __in KPROCESSOR_MODE WaitMode, __in_opt PLARGE_INTEGER Timeout)
PLIST_ENTRY KeRundownQueue (__inout PRKQUEUE Queue)
LONG FASTCALL KiInsertQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry, __in BOOLEAN Head)
Macro Definition Documentation
#define InitializeRemoveQueue ()
Value:
Thread->WaitBlockList = WaitBlock;                                      \
    WaitBlock->Object = (PVOID)Queue;                                       \
    WaitBlock->WaitKey = (CSHORT)(STATUS_SUCCESS);                          \
    WaitBlock->WaitType = WaitAny;                                          \
    WaitBlock->Thread = Thread;                                             \
    Thread->WaitStatus = 0;                                                 \
    if (ARGUMENT_PRESENT(Timeout)) {                                        \
        KiSetDueTime(Timer, *Timeout, &Hand);                               \
        DueTime.QuadPart = Timer->DueTime.QuadPart;                         \
        WaitBlock->NextWaitBlock = WaitTimer;                               \
        WaitTimer->NextWaitBlock = WaitBlock;                               \
        Timer->Header.WaitListHead.Flink = &WaitTimer->WaitListEntry;       \
        Timer->Header.WaitListHead.Blink = &WaitTimer->WaitListEntry;       \
    } else {                                                                \
        WaitBlock->NextWaitBlock = WaitBlock;                               \
    }                                                                       \
    Thread->Alertable = FALSE;                                              \
    Thread->WaitMode = WaitMode;                                            \
    Thread->WaitReason = WrQueue;                                           \
    Thread->WaitListEntry.Flink = NULL;                                     \
    StackSwappable = KiIsKernelStackSwappable(WaitMode, Thread);            \
    Thread->WaitTime= KiQueryLowTickCount()
Definition at line 233 of file queueobj.c.
Referenced by KeRemoveQueue().
Function Documentation
VOID KeInitializeQueue (__out PRKQUEUE Queue, __in ULONG Count)
Definition at line 23 of file queueobj.c.
References ARGUMENT_PRESENT, Count, InitializeListHead(), KeNumberProcessors, and QueueObject.
Referenced by ExpWorkerInitialization(), FsRtlInitializeWorkerThread(), and NtCreateIoCompletion().
LONG KeInsertHeadQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
Definition at line 165 of file queueobj.c.
References ASSERT, ASSERT_QUEUE, DISPATCH_LEVEL, KeGetCurrentIrql(), KiExitDispatcher(), KiInsertQueue(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabaseFromSynchLevel, and TRUE.
LONG KeInsertQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry)
Definition at line 107 of file queueobj.c.
References ASSERT, ASSERT_QUEUE, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KiExitDispatcher(), KiInsertQueue(), KiLockDispatcherDatabase, and KiUnlockDispatcherDatabaseFromSynchLevel.
Referenced by ExpCheckQueueShutdown(), ExpShutdownWorkerThreads(), ExQueueWorkItem(), FsRtlpPostStackOverflow(), IopCompleteRequest(), and IoSetIoCompletion().
LONG KeReadStateQueue (__in PRKQUEUE Queue)
Definition at line 79 of file queueobj.c.
References ASSERT_QUEUE.
Referenced by ExpDetectWorkerThreadDeadlock(), and NtQueryIoCompletion().
PLIST_ENTRY KeRemoveQueue (__inout PRKQUEUE Queue, __in KPROCESSOR_MODE WaitMode, __in_opt PLARGE_INTEGER Timeout)
Definition at line 258 of file queueobj.c.
References APC_LEVEL, _KTHREAD::ApcState, ARGUMENT_PRESENT, ASSERT, ASSERT_QUEUE, _LIST_ENTRY::Blink, DISPATCH_LEVEL, ExWorkerQueue, FALSE, _LIST_ENTRY::Flink, InitializeRemoveQueue, InsertTailList(), INVALID_WORK_QUEUE_ITEM, KeBugCheckEx(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeRaiseIrqlToSynchLevel(), _KAPC_STATE::KernelApcPending, KernelMode, KiActivateWaiterQueue(), KiCheckDueTime(), KiComputeWaitInterval(), KiExitDispatcher(), KiInsertOrSignalTimer(), KiLockDispatcherDatabaseAtSynchLevel, KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KTHREAD::Queue, _KTHREAD::QueueListEntry, RemoveEntryList(), _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_TIMEOUT, STATUS_USER_APC, _KTHREAD::Timer, TIMER_WAIT_BLOCK, TRUE, ULongToPtr, _KAPC_STATE::UserApcPending, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitListEntry, _KPRCB::WaitListHead, _KTHREAD::WaitNext, and _KTHREAD::WaitReason.
Referenced by ExpWorkerThread(), FsRtlWorkerThread(), and NtRemoveIoCompletion().
PLIST_ENTRY KeRundownQueue (__inout PRKQUEUE Queue)
Definition at line 567 of file queueobj.c.
References ASSERT, ASSERT_QUEUE, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, IsListEmpty, KeGetCurrentIrql(), KiExitDispatcher(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KTHREAD::Queue, and RemoveEntryList().
Referenced by IopDeleteIoCompletion().
LONG FASTCALL KiInsertQueue (__inout PRKQUEUE Queue, __inout PLIST_ENTRY Entry, __in BOOLEAN Head)
Definition at line 656 of file queueobj.c.
References ASSERT_QUEUE, _LIST_ENTRY::Blink, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, _DISPATCHER_HEADER::Inserted, InsertHeadList(), InsertTailList(), KeGetCurrentThread(), KiReadyThread(), KiRemoveTreeTimer(), NULL, _KTHREAD::Queue, RemoveEntryList(), _KWAIT_BLOCK::Thread, _KTHREAD::Timer, TRUE, _KTHREAD::WaitListEntry, _KTHREAD::WaitReason, _KTHREAD::WaitStatus, and WrQueue.
Referenced by KeInsertHeadQueue(), KeInsertQueue(), and KeTerminateThread().