Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/secure.c File Reference
secure.c File Reference
#include "strsafe.h"
#include "wmikmp.h"
Functions
NTSTATUS WmipCheckGuidAccess (IN LPGUID Guid, IN ACCESS_MASK DesiredAccess, IN PSECURITY_DESCRIPTOR UserDefaultSecurity)
VOID WmipCloseMethod (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
NTSTATUS WmipCreateAdminSD (PSECURITY_DESCRIPTOR *Sd)
NTSTATUS WmipCreateGuidObject (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN LPGUID Guid, OUT PHANDLE CreatorHandle, OUT PWMIGUIDOBJECT *Object)
NTSTATUS WmipCreateGuidObject (IN OUT POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN LPGUID Guid, OUT PHANDLE CreatorHandle, OUT PWMIGUIDOBJECT *Object)
VOID WmipDeleteMethod (IN PVOID Object)
NTSTATUS WmipGetGuidSecurityDescriptor (IN PUNICODE_STRING GuidName, IN PSECURITY_DESCRIPTOR *SecurityDescriptor, IN PSECURITY_DESCRIPTOR UserDefaultSecurity)
BOOLEAN WmipHexStringToDword (IN PWCHAR lpsz, OUT PULONG RetValue, IN ULONG cDigits, IN WCHAR chDelim)
NTSTATUS WmipInitializeSecurity (void)
NTSTATUS WmipOpenGuidObject (IN POBJECT_ATTRIBUTES CapturedObjectAttributes, IN ACCESS_MASK DesiredAccess, IN KPROCESSOR_MODE AccessMode, OUT PHANDLE Handle, OUT PWMIGUIDOBJECT *ObjectPtr)
NTSTATUS WmipSaveGuidSecurityDescriptor (PUNICODE_STRING GuidName, PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSTATUS WmipSDRegistryQueryRoutine (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
NTSTATUS WmipSecurityMethod (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS WmipUuidFromString (IN PWCHAR StringUuid, OUT LPGUID Uuid)
Variables
PSECURITY_DESCRIPTOR WmipDefaultAccessSd
SECURITY_DESCRIPTOR WmipDefaultAccessSecurityDescriptor
const GENERIC_MAPPING WmipGenericMapping
POBJECT_TYPE WmipGuidObjectType
SECURITY_SUBJECT_CONTEXT WmipSystemSubjectContext
Function Documentation
NTSTATUS WmipCheckGuidAccess (IN LPGUID Guid, IN ACCESS_MASK DesiredAccess, IN PSECURITY_DESCRIPTOR UserDefaultSecurity)
Definition at line 1589 of file secure.c.
References ExFreePool(), FALSE, NT_SUCCESS, NULL, PAGED_CODE, RtlInitUnicodeString(), SeAccessCheck(), SeCaptureSubjectContext(), SeReleaseSubjectContext(), Status, StringCbPrintf, UserMode, WmipDefaultAccessSd, and WmipGetGuidSecurityDescriptor().
Referenced by WmiFlushTrace(), WmipEnableDisableTrace(), WmipNtDllLoggerInfo(), WmipQueryLogger(), WmipStartLogger(), WmiStopTrace(), and WmiUpdateTrace().
VOID WmipCloseMethod (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 1099 of file secure.c.
References ASSERT, CONTAINING_RECORD, _WMIGUIDOBJECT::Flags, _LIST_ENTRY::Flink, _WMIGUIDOBJECT::GuidEntry, NULL, ObDereferenceObject(), PAGED_CODE, RemoveEntryList(), MBREQUESTS::ReplyObject, MBREQUESTS::RequestListEntry, _WMIGUIDOBJECT::RequestListHead, UNREFERENCED_PARAMETER, WMIGUID_FLAG_REPLY_OBJECT, WmipEnterSMCritSection, and WmipLeaveSMCritSection.
Referenced by WmipInitializeSecurity().
NTSTATUS WmipCreateAdminSD (PSECURITY_DESCRIPTOR * Sd)
Definition at line 1667 of file secure.c.
References ACL_REVISION2, ExAllocatePoolWithTag, ExFreePool(), FALSE, FILE_ALL_ACCESS, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION1, SeLengthSid, SeLocalSystemSid, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, and WMIPOOLTAG.
Referenced by WmipDriverEntry().
NTSTATUS WmipCreateGuidObject (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN LPGUID Guid, OUT PHANDLE CreatorHandle, OUT PWMIGUIDOBJECT * Object)
Referenced by WmipOpenGuidObject().
NTSTATUS WmipCreateGuidObject (IN OUT POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN LPGUID Guid, OUT PHANDLE CreatorHandle, OUT PWMIGUIDOBJECT * Object)
Definition at line 950 of file secure.c.
References _OBJECT_ATTRIBUTES::Attributes, ExFreePool(), FALSE, KeAttachProcess(), KeDetachProcess(), KeInitializeEvent(), KernelMode, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), OBJ_OPENIF, _OBJECT_ATTRIBUTES::ObjectName, PAGED_CODE, _EPROCESS::Pcb, PsInitialSystemProcess, RtlInitUnicodeString(), RtlZeroMemory, SeCreateAccessState(), _OBJECT_ATTRIBUTES::SecurityDescriptor, SeDeleteAccessState(), Status, STATUS_OBJECT_NAME_EXISTS, _ACCESS_STATE::SubjectSecurityContext, WmiGuidGuidPosition, WmipAssert, WmipDefaultAccessSd, WmipGetGuidSecurityDescriptor(), and WmipSystemSubjectContext.
VOID WmipDeleteMethod (IN PVOID Object)
Definition at line 1185 of file secure.c.
References ASSERT, WMIEVENTQUEUE::Buffer, _WNODE_HEADER::BufferSize, _REGENTRY::DataSource, _WMIGUIDOBJECT::EnableRequestSent, _WMIGUIDOBJECT::EventQueueAction, _WNODE_HEADER::Flags, _REGENTRY::Flags, _WMIGUIDOBJECT::Flags, _WMIGUIDOBJECT::GEObjectList, _WMIGUIDOBJECT::GuidEntry, _WMIGUIDOBJECT::HiPriority, IO_NO_INCREMENT, IoCompleteRequest(), IoSetCancelRoutine, _WMIGUIDOBJECT::Irp, _WMIGUIDOBJECT::LoPriority, MAXREQREPLYSLOTS, _WMIGUIDOBJECT::MBRequests, NULL, ObDereferenceObject(), PAGED_CODE, PIRP, _WNODE_HEADER::ProviderId, RECEIVE_ACTION_CREATE_THREAD, RECEIVE_ACTION_NONE, _WMIGUIDOBJECT::RegEntry, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, REGENTRY_FLAG_RUNDOWN, RemoveEntryList(), MBREQUESTS::ReplyObject, MBREQUESTS::RequestListEntry, tagDATASOURCE::RequestObject, RtlZeroMemory, STATUS_INVALID_HANDLE, TRUE, _WMIGUIDOBJECT::Type, _WMIGUIDOBJECT::UserModeCallback, _WMIGUIDOBJECT::UserModeProcess, WMIGUID_FLAG_KERNEL_NOTIFICATION, WMIGUID_FLAG_REPLY_OBJECT, WMIGUID_FLAG_REQUEST_OBJECT, WmipAssert, WmipClearIrpObjectList(), WmipClearObjectFromThreadList(), WmipDisableCollectOrEvent(), WmipEnterSMCritSection, WmipFree, WmipLeaveSMCritSection, WmipUnreferenceGE, WmipUnreferenceRegEntry, WmipWriteWnodeToObject(), and WNODE_FLAG_INTERNAL.
Referenced by WmipInitializeSecurity().
NTSTATUS WmipGetGuidSecurityDescriptor (IN PUNICODE_STRING GuidName, IN PSECURITY_DESCRIPTOR * SecurityDescriptor, IN PSECURITY_DESCRIPTOR UserDefaultSecurity)
Definition at line 746 of file secure.c.
References DefaultSecurityGuidName, _RTL_QUERY_REGISTRY_TABLE::DefaultType, _RTL_QUERY_REGISTRY_TABLE::EntryContext, ExFreePool(), _RTL_QUERY_REGISTRY_TABLE::Flags, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, PAGED_CODE, _RTL_QUERY_REGISTRY_TABLE::QueryRoutine, REG_BINARY, RTL_REGISTRY_CONTROL, RtlQueryRegistryValues(), RtlZeroMemory, Status, STATUS_SUCCESS, WmipDefaultAccessSd, and WmipSDRegistryQueryRoutine().
Referenced by WmipCheckGuidAccess(), WmipCreateGuidObject(), and WmipStartGlobalLogger().
BOOLEAN WmipHexStringToDword (IN PWCHAR lpsz, OUT PULONG RetValue, IN ULONG cDigits, IN WCHAR chDelim)
Definition at line 1362 of file secure.c.
References Count, FALSE, PAGED_CODE, and TRUE.
Referenced by WmipUuidFromString().
NTSTATUS WmipInitializeSecurity (void)
Definition at line 426 of file secure.c.
References ACCESS_SYSTEM_SECURITY, ACL_REVISION2, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlInitUnicodeString(), RtlSetDaclSecurityDescriptor(), RtlSetGroupSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), RtlZeroMemory, SeAliasAdminsSid, SeAliasUsersSid, SeCaptureSubjectContext(), SECURITY_DESCRIPTOR_REVISION1, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, _OBJECT_TYPE_INITIALIZER::SecurityRequired, SeExports, SeLengthSid, _SE_EXPORTS::SeLocalServiceSid, SeLocalSystemSid, _SE_EXPORTS::SeNetworkServiceSid, SPECIFIC_RIGHTS_ALL, STANDARD_RIGHTS_ALL, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, WmipCloseMethod(), WmipDefaultAccessSd, WmipDefaultAccessSecurityDescriptor, WmipDeleteMethod(), WmipGenericMapping, WMIPOOLTAG, and WmipSecurityMethod().
Referenced by WmipDriverEntry().
NTSTATUS WmipOpenGuidObject (IN POBJECT_ATTRIBUTES CapturedObjectAttributes, IN ACCESS_MASK DesiredAccess, IN KPROCESSOR_MODE AccessMode, OUT PHANDLE Handle, OUT PWMIGUIDOBJECT * ObjectPtr)
Definition at line 842 of file secure.c.
References _UNICODE_STRING::Buffer, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, KeAttachProcess(), KeDetachProcess(), NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), PAGED_CODE, _EPROCESS::Pcb, PsInitialSystemProcess, RtlEqualMemory, Status, STATUS_INVALID_PARAMETER, WmiGuidGuidPosition, WmiGuidObjectDirectory, WmiGuidObjectDirectoryLength, WmipCreateGuidObject(), WmipDebugPrintEx, WmipUuidFromString(), and ZwClose().
Referenced by WmipCreateUMLogger(), WmipOpenBlock(), and WmipRegisterUMGuids().
NTSTATUS WmipSaveGuidSecurityDescriptor (PUNICODE_STRING GuidName, PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 703 of file secure.c.
References _UNICODE_STRING::Buffer, PAGED_CODE, REG_BINARY, RTL_REGISTRY_CONTROL, RtlLengthSecurityDescriptor(), RtlWriteRegistryValue(), and Status.
Referenced by WmipSecurityMethod().
NTSTATUS WmipSDRegistryQueryRoutine (IN PWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN PVOID Context, IN PVOID EntryContext)
Definition at line 632 of file secure.c.
References ExAllocatePoolWithTag, NULL, PAGED_CODE, PagedPool, REG_BINARY, RtlCopyMemory, SeValidSecurityDescriptor(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, UNREFERENCED_PARAMETER, and WMIPOOLTAG.
Referenced by WmipGetGuidSecurityDescriptor().
NTSTATUS WmipSecurityMethod (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 171 of file secure.c.
References ASSERT, AssignSecurityDescriptor, _GUID::Data1, _GUID::Data2, _GUID::Data3, _GUID::Data4, DeleteSecurityDescriptor, ExAllocatePoolWithTag, ExFreePool(), KeBugCheckEx(), NonPagedPool, NT_SUCCESS, NULL, ObAssignObjectSecurityDescriptor(), ObDeassignSecurity(), ObQuerySecurityDescriptorInfo(), ObSetSecurityDescriptorInfo(), PAGED_CODE, PagedPool, QuerySecurityDescriptor, RtlInitUnicodeString(), SECURITY_SYSTEM, SetSecurityDescriptor, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, StringCbPrintf, TRUE, WMIPOOLTAG, and WmipSaveGuidSecurityDescriptor().
Referenced by WmipInitializeSecurity().
NTSTATUS WmipUuidFromString (IN PWCHAR StringUuid, OUT LPGUID Uuid)
Definition at line 1397 of file secure.c.
References PAGED_CODE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and WmipHexStringToDword().
Referenced by WmipOpenGuidObject().
Variable Documentation
PSECURITY_DESCRIPTOR WmipDefaultAccessSd
Definition at line 154 of file secure.c.
Referenced by WmipCheckGuidAccess(), WmipCreateGuidObject(), WmipGetGuidSecurityDescriptor(), and WmipInitializeSecurity().
SECURITY_DESCRIPTOR WmipDefaultAccessSecurityDescriptor
Definition at line 153 of file secure.c.
Referenced by WmipInitializeSecurity().
const GENERIC_MAPPING WmipGenericMapping
Initial value:
=
{
        WMIGUID_QUERY,
        WMIGUID_SET,
        WMIGUID_EXECUTE,
    WMIGUID_ALL_ACCESS | STANDARD_RIGHTS_READ
}
Definition at line 158 of file secure.c.
Referenced by WmipInitializeSecurity().
POBJECT_TYPE WmipGuidObjectType
Definition at line 147 of file secure.c.
Referenced by IoWMIOpenBlock(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipQueryAllData(), WmipQueryGuidInfo(), WmipQuerySetExecuteSI(), WmipReceiveNotifications(), WmipTranslateFileHandle(), and WmipWriteMBToObject().
SECURITY_SUBJECT_CONTEXT WmipSystemSubjectContext
Definition at line 143 of file secure.c.
Referenced by WmipCreateGuidObject().