Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/verifier.h File Reference
verifier.h File Reference
#include "..\verifier\vfzwapi.h"
#include "..\verifier\vftriage.h"
Typedefs
typedef enum VF_FAILURE_CLASS * PVF_FAILURE_CLASS
typedef enum _VI_DEADLOCK_RESOURCE_TYPE * PVI_DEADLOCK_RESOURCE_TYPE
typedef enum _VI_DEADLOCK_RESOURCE_TYPE VI_DEADLOCK_RESOURCE_TYPE
Enumerations
enum _VI_DEADLOCK_RESOURCE_TYPE {
VfDeadlockUnknown = 0, VfDeadlockMutex, VfDeadlockMutexAbandoned, VfDeadlockFastMutex,
VfDeadlockFastMutexUnsafe, VfDeadlockSpinLock, VfDeadlockQueuedSpinLock, VfDeadlockTypeMaximum
}
enum VERIFIER_MODE {
VERIFIER_MODE_DISABLED = 0, VERIFIER_MODE_TRIAGE, VERIFIER_MODE_FIELD, VERIFIER_MODE_LOGO,
VERIFIER_MODE_TEST, VERIFIER_MODE_MAX
}
enum VF_FAILURE_CLASS { VFFAILURE_FAIL_IN_FIELD = 0, VFFAILURE_FAIL_LOGO = 1, VFFAILURE_FAIL_UNDER_DEBUGGER = 2 }
enum VF_OBJECT_TYPE { VFOBJTYPE_DRIVER = 0, VFOBJTYPE_DEVICE, VFOBJTYPE_SYSTEM_BIOS }
Functions
VOID VerifierDeadlockFreePool (IN PVOID Address, IN SIZE_T NumberOfBytes)
NTSTATUS VerifierNtCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG CreateDisposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength)
NTSTATUS VerifierNtReadFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PVOID Buffer, IN ULONG Length, IN PLARGE_INTEGER ByteOffset OPTIONAL, IN PULONG Key OPTIONAL)
NTSTATUS VerifierNtWriteFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PVOID Buffer, IN ULONG Length, IN PLARGE_INTEGER ByteOffset OPTIONAL, IN PULONG Key OPTIONAL)
NTSTATUS VfAllocateAdapterChannel (IN struct _DMA_ADAPTER *DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
PVOID VfAllocateCommonBuffer (IN struct _DMA_ADAPTER *DmaAdapter, IN ULONG Length, OUT PPHYSICAL_ADDRESS LogicalAddress, IN BOOLEAN CacheEnabled)
PVOID VfAllocateCrashDumpRegisters (IN PADAPTER_OBJECT AdapterObject, IN PULONG NumberOfMapRegisters)
VOID VfDeadlockAcquireResource (IN PVOID Resource, IN VI_DEADLOCK_RESOURCE_TYPE Type, IN PKTHREAD Thread, IN BOOLEAN TryAcquire, IN PVOID Caller)
VOID VfDeadlockDeleteMemoryRange (IN PVOID Address, IN SIZE_T Size)
VOID VfDeadlockDetectionCleanup (VOID)
VOID VfDeadlockDetectionInitialize (IN LOGICAL VerifyAllDrivers, IN LOGICAL VerifyKernel)
BOOLEAN VfDeadlockInitializeResource (IN PVOID Resource, IN VI_DEADLOCK_RESOURCE_TYPE Type, IN PVOID Caller, IN BOOLEAN DoNotAcquireLock)
VOID VfDeadlockReleaseResource (IN PVOID Resource, IN VI_DEADLOCK_RESOURCE_TYPE Type, IN PKTHREAD Thread, IN PVOID Caller)
VOID VfDisableHalVerifier (VOID)
VOID VfFailDeviceNode (IN PDEVICE_OBJECT PhysicalDeviceObject, IN ULONG BugCheckMajorCode, IN ULONG BugCheckMinorCode, IN VF_FAILURE_CLASS FailureClass, IN OUT PULONG AssertionControl, IN PSTR DebuggerMessageText, IN PSTR ParameterFormatString,...)
VOID VfFailDriver (IN ULONG BugCheckMajorCode, IN ULONG BugCheckMinorCode, IN VF_FAILURE_CLASS FailureClass, IN OUT PULONG AssertionControl, IN PSTR DebuggerMessageText, IN PSTR ParameterFormatString,...)
VOID VfFailSystemBIOS (IN ULONG BugCheckMajorCode, IN ULONG BugCheckMinorCode, IN VF_FAILURE_CLASS FailureClass, IN OUT PULONG AssertionControl, IN PSTR DebuggerMessageText, IN PSTR ParameterFormatString,...)
BOOLEAN VfFlushAdapterBuffers (IN struct _DMA_ADAPTER *DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN ULONG Length, IN BOOLEAN WriteToDevice)
VOID VfFreeAdapterChannel (IN struct _DMA_ADAPTER *DmaAdapter)
VOID VfFreeCommonBuffer (IN struct _DMA_ADAPTER *DmaAdapter, IN ULONG Length, IN PHYSICAL_ADDRESS LogicalAddress, IN PVOID VirtualAddress, IN BOOLEAN CacheEnabled)
VOID VfFreeMapRegisters (IN struct _DMA_ADAPTER *DmaAdapter, PVOID MapRegisterBase, ULONG NumberOfMapRegisters)
struct _DMA_ADAPTER * VfGetDmaAdapter (IN PDEVICE_OBJECT PhysicalDeviceObject, IN struct _DEVICE_DESCRIPTION *DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
ULONG VfGetDmaAlignment (IN struct _DMA_ADAPTER *DmaAdapter)
NTSTATUS VfGetScatterGatherList (IN struct _DMA_ADAPTER *DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PVOID ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice)
VOID VfHalDeleteDevice (IN PDEVICE_OBJECT DeviceObject)
BOOLEAN VfIsVerificationEnabled (IN VF_OBJECT_TYPE VfObjectType, IN PVOID Object OPTIONAL)
LOGICAL VfIsVerifierEnabled (VOID)
PADAPTER_OBJECT VfLegacyGetAdapter (IN struct _DEVICE_DESCRIPTION *DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
PHYSICAL_ADDRESS VfMapTransfer (IN struct _DMA_ADAPTER *DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN OUT PULONG Length, IN BOOLEAN WriteToDevice)
VOID VfPutDmaAdapter (struct _DMA_ADAPTER *DmaAdapter)
VOID VfPutScatterGatherList (IN struct _DMA_ADAPTER *DmaAdapter, IN struct _SCATTER_GATHER_LIST *ScatterGather, IN BOOLEAN WriteToDevice)
LARGE_INTEGER VfQueryPerformanceCounter (IN PLARGE_INTEGER PerformanceFrequency OPTIONAL)
ULONG VfReadDmaCounter (IN struct _DMA_ADAPTER *DmaAdapter)
VERIFIER_MODE VfVerifierRunningMode (VOID)
Typedef Documentation
typedef enum VF_FAILURE_CLASS * PVF_FAILURE_CLASS
typedef enum _VI_DEADLOCK_RESOURCE_TYPE * PVI_DEADLOCK_RESOURCE_TYPE
typedef enum _VI_DEADLOCK_RESOURCE_TYPE VI_DEADLOCK_RESOURCE_TYPE
Enumeration Type Documentation
enum _VI_DEADLOCK_RESOURCE_TYPE
Enumerator
VfDeadlockUnknown
VfDeadlockMutex
VfDeadlockMutexAbandoned
VfDeadlockFastMutex
VfDeadlockFastMutexUnsafe
VfDeadlockSpinLock
VfDeadlockQueuedSpinLock
VfDeadlockTypeMaximum
Definition at line 40 of file verifier.h.
enum VERIFIER_MODE
Enumerator
VERIFIER_MODE_DISABLED
VERIFIER_MODE_TRIAGE
VERIFIER_MODE_FIELD
VERIFIER_MODE_LOGO
VERIFIER_MODE_TEST
VERIFIER_MODE_MAX
Definition at line 424 of file verifier.h.
enum VF_FAILURE_CLASS
Enumerator
VFFAILURE_FAIL_IN_FIELD
VFFAILURE_FAIL_LOGO
VFFAILURE_FAIL_UNDER_DEBUGGER
Definition at line 293 of file verifier.h.
enum VF_OBJECT_TYPE
Enumerator
VFOBJTYPE_DRIVER
VFOBJTYPE_DEVICE
VFOBJTYPE_SYSTEM_BIOS
Definition at line 394 of file verifier.h.
Function Documentation
VOID VerifierDeadlockFreePool (IN PVOID Address, IN SIZE_T NumberOfBytes)
Referenced by ExFreePoolWithTag(), MmFreeContiguousMemory(), and MmUnloadSystemImage().
NTSTATUS VerifierNtCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG CreateDisposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength)
NTSTATUS VerifierNtReadFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PVOID Buffer, IN ULONG Length, IN PLARGE_INTEGER ByteOffset OPTIONAL, IN PULONG Key OPTIONAL)
NTSTATUS VerifierNtWriteFile (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PVOID Buffer, IN ULONG Length, IN PLARGE_INTEGER ByteOffset OPTIONAL, IN PULONG Key OPTIONAL)
NTSTATUS VfAllocateAdapterChannel (IN struct _DMA_ADAPTER * DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
PVOID VfAllocateCommonBuffer (IN struct _DMA_ADAPTER * DmaAdapter, IN ULONG Length, OUT PPHYSICAL_ADDRESS LogicalAddress, IN BOOLEAN CacheEnabled)
PVOID VfAllocateCrashDumpRegisters (IN PADAPTER_OBJECT AdapterObject, IN PULONG NumberOfMapRegisters)
VOID VfDeadlockAcquireResource (IN PVOID Resource, IN VI_DEADLOCK_RESOURCE_TYPE Type, IN PKTHREAD Thread, IN BOOLEAN TryAcquire, IN PVOID Caller)
VOID VfDeadlockDeleteMemoryRange (IN PVOID Address, IN SIZE_T Size)
VOID VfDeadlockDetectionCleanup (VOID)
VOID VfDeadlockDetectionInitialize (IN LOGICAL VerifyAllDrivers, IN LOGICAL VerifyKernel)
BOOLEAN VfDeadlockInitializeResource (IN PVOID Resource, IN VI_DEADLOCK_RESOURCE_TYPE Type, IN PVOID Caller, IN BOOLEAN DoNotAcquireLock)
VOID VfDeadlockReleaseResource (IN PVOID Resource, IN VI_DEADLOCK_RESOURCE_TYPE Type, IN PKTHREAD Thread, IN PVOID Caller)
VOID VfDisableHalVerifier (VOID)
VOID VfFailDeviceNode (IN PDEVICE_OBJECT PhysicalDeviceObject, IN ULONG BugCheckMajorCode, IN ULONG BugCheckMinorCode, IN VF_FAILURE_CLASS FailureClass, IN OUT PULONG AssertionControl, IN PSTR DebuggerMessageText, IN PSTR ParameterFormatString, ...)
VOID VfFailDriver (IN ULONG BugCheckMajorCode, IN ULONG BugCheckMinorCode, IN VF_FAILURE_CLASS FailureClass, IN OUT PULONG AssertionControl, IN PSTR DebuggerMessageText, IN PSTR ParameterFormatString, ...)
VOID VfFailSystemBIOS (IN ULONG BugCheckMajorCode, IN ULONG BugCheckMinorCode, IN VF_FAILURE_CLASS FailureClass, IN OUT PULONG AssertionControl, IN PSTR DebuggerMessageText, IN PSTR ParameterFormatString, ...)
BOOLEAN VfFlushAdapterBuffers (IN struct _DMA_ADAPTER * DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN ULONG Length, IN BOOLEAN WriteToDevice)
VOID VfFreeAdapterChannel (IN struct _DMA_ADAPTER * DmaAdapter)
VOID VfFreeCommonBuffer (IN struct _DMA_ADAPTER * DmaAdapter, IN ULONG Length, IN PHYSICAL_ADDRESS LogicalAddress, IN PVOID VirtualAddress, IN BOOLEAN CacheEnabled)
VOID VfFreeMapRegisters (IN struct _DMA_ADAPTER * DmaAdapter, PVOID MapRegisterBase, ULONG NumberOfMapRegisters)
struct _DMA_ADAPTER* VfGetDmaAdapter (IN PDEVICE_OBJECT PhysicalDeviceObject, IN struct _DEVICE_DESCRIPTION * DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
ULONG VfGetDmaAlignment (IN struct _DMA_ADAPTER * DmaAdapter)
NTSTATUS VfGetScatterGatherList (IN struct _DMA_ADAPTER * DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PVOID ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice)
VOID VfHalDeleteDevice (IN PDEVICE_OBJECT DeviceObject)
BOOLEAN VfIsVerificationEnabled (IN VF_OBJECT_TYPE VfObjectType, IN PVOID Object OPTIONAL)
LOGICAL VfIsVerifierEnabled (VOID)
PADAPTER_OBJECT VfLegacyGetAdapter (IN struct _DEVICE_DESCRIPTION * DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
PHYSICAL_ADDRESS VfMapTransfer (IN struct _DMA_ADAPTER * DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN OUT PULONG Length, IN BOOLEAN WriteToDevice)
VOID VfPutDmaAdapter (struct _DMA_ADAPTER * DmaAdapter)
VOID VfPutScatterGatherList (IN struct _DMA_ADAPTER * DmaAdapter, IN struct _SCATTER_GATHER_LIST * ScatterGather, IN BOOLEAN WriteToDevice)
LARGE_INTEGER VfQueryPerformanceCounter (IN PLARGE_INTEGER PerformanceFrequency OPTIONAL)
ULONG VfReadDmaCounter (IN struct _DMA_ADAPTER * DmaAdapter)
VERIFIER_MODE VfVerifierRunningMode (VOID)