Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/dpcobj.c File Reference
dpcobj.c File Reference
#include "ki.h"
Data Structures
struct _DEFERRED_REVERSE_BARRIER
Macros
#define DEFERRED_REVERSE_BARRIER_SYNCHRONIZED 0x80000000
Typedefs
typedef struct _DEFERRED_REVERSE_BARRIER DEFERRED_REVERSE_BARRIER
typedef struct _DEFERRED_REVERSE_BARRIER * PDEFERRED_REVERSE_BARRIER
Functions
VOID KeFlushQueuedDpcs (VOID)
VOID KeGenericCallDpc (__in PKDEFERRED_ROUTINE Routine, __in_opt PVOID Context)
VOID KeInitializeDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
VOID KeInitializeThreadedDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
BOOLEAN KeInsertQueueDpc (__inout PRKDPC Dpc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2)
BOOLEAN KeRemoveQueueDpc (__inout PRKDPC Dpc)
VOID KeSignalCallDpcDone (__in PVOID SystemArgument1)
LOGICAL KeSignalCallDpcSynchronize (__in PVOID SystemArgument2)
VOID KiInitializeDpc (IN PRKDPC Dpc, IN PKDEFERRED_ROUTINE DeferredRoutine, IN PVOID DeferredContext, IN KOBJECTS DpcType)
FORCEINLINE PKDPC_DATA KiSelectDpcData (IN PKPRCB Prcb, IN PKDPC Dpc)
Macro Definition Documentation
#define DEFERRED_REVERSE_BARRIER_SYNCHRONIZED 0x80000000
Definition at line 26 of file dpcobj.c.
Referenced by KeSignalCallDpcSynchronize().
Typedef Documentation
typedef struct _DEFERRED_REVERSE_BARRIER DEFERRED_REVERSE_BARRIER
typedef struct _DEFERRED_REVERSE_BARRIER * PDEFERRED_REVERSE_BARRIER
Function Documentation
VOID KeFlushQueuedDpcs (VOID)
Definition at line 553 of file dpcobj.c.
References AFFINITY_MASK, DISPATCH_LEVEL, DPC_NORMAL, DPC_THREADED, _KPRCB::DpcData, _KDPC_DATA::DpcQueueDepth, FALSE, HIGH_PRIORITY, KeActiveProcessors, KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetPriorityThread(), KeSetSystemAffinityThread(), KiRequestSoftwareInterrupt, KiSendSoftwareInterrupt(), _KPRCB::Number, PAGED_CODE, and TRUE.
Referenced by ExpDeleteTimer(), IopDeleteDriver(), and MmPageEntireDriver().
VOID KeGenericCallDpc (__in PKDEFERRED_ROUTINE Routine, __in_opt PVOID Context)
Definition at line 691 of file dpcobj.c.
References ASSERT, _DEFERRED_REVERSE_BARRIER::Barrier, _KPRCB::CallDpc, _KDPC::DeferredContext, _KDPC::DeferredRoutine, DISPATCH_LEVEL, ExAcquireFastMutex(), ExReleaseFastMutex(), Index, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentProcessorNumber(), KeInsertQueueDpc(), KeLowerIrql, KeNumberProcessors, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KeYieldProcessor, KiGenericCallDpcMutex, KiProcessorBlock, and _DEFERRED_REVERSE_BARRIER::TotalProcessors.
Referenced by ExGetPoolTagInfo(), Ke386IoSetAccessProcess(), Ke386SetDescriptorProcess(), Ke386SetIoAccessMap(), and Ke386SetLdtProcess().
VOID KeInitializeDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
Definition at line 133 of file dpcobj.c.
References DpcObject, and KiInitializeDpc().
Referenced by CcInitializeCacheManager(), CmpCmdInit(), CmpInitDelayDerefKCBEngine(), CmpInitializeDelayedCloseTable(), InitializePool(), IoInitSystem(), IopErrorLogQueueRequest(), IopInitializeIrpStackProfiler(), KeBalanceSetManager(), KiInitializeInterruptTimers(), KiInitSpinLocks(), KiInitSystem(), MmInitSystem(), NtCreateTimer(), PspInitializeJobStructures(), WmipRegisterMcaHandler(), and WmipSetupWaitForWbem().
VOID KeInitializeThreadedDpc (__out PRKDPC Dpc, __in PKDEFERRED_ROUTINE DeferredRoutine, __in_opt PVOID DeferredContext)
Definition at line 168 of file dpcobj.c.
References KiInitializeDpc(), and ThreadedDpcObject.
BOOLEAN KeInsertQueueDpc (__inout PRKDPC Dpc, __in_opt PVOID SystemArgument1, __in_opt PVOID SystemArgument2)
Definition at line 203 of file dpcobj.c.
References AFFINITY_MASK, ASSERT_DPC, DISPATCH_LEVEL, DPC_THREADED, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KPRCB::DpcInterruptRequested, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _KPRCB::DpcRequestRate, _KPRCB::DpcRoutineActive, _KPRCB::DpcSetEventRequest, _KPRCB::DpcThreadActive, _KPRCB::DpcThreadRequested, FALSE, HIGH_LEVEL, HighImportance, InsertHeadList(), InsertTailList(), InterlockedCompareExchangePointer, InterlockedExchange(), KeGetCurrentPrcb(), KeIsIdleHaltSet, KeLowerIrql, KeMemoryBarrier(), KeRaiseIrql, KiAcquireSpinLock(), KiIdleSummary, KiProcessorBlock, KiReleaseSpinLock(), KiRequestSoftwareInterrupt, KiSelectDpcData(), KiSendSoftwareInterrupt(), LowImportance, MAXIMUM_PROCESSORS, _KPRCB::MaximumDpcQueueDepth, _KPRCB::MinimumDpcRate, NULL, _KPRCB::Number, _KPRCB::QuantumEnd, and TRUE.
Referenced by KeGenericCallDpc(), KiCalibrateTimeAdjustment(), KiSignalTimer(), KiTimerExpiration(), KiTimerListExpire(), WmipInsertQueueMCEDpc(), WmipMceDelivery(), and WmipMceEventDelivery().
BOOLEAN KeRemoveQueueDpc (__inout PRKDPC Dpc)
Definition at line 466 of file dpcobj.c.
References ASSERT_DPC, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, FALSE, KeDisableInterrupts(), KeEnableInterrupts(), KiAcquireSpinLock(), KiReleaseSpinLock(), NULL, RemoveEntryList(), and TRUE.
Referenced by ExTimerRundown(), KiCalibrateTimeAdjustment(), NtCancelTimer(), and NtSetTimer().
VOID KeSignalCallDpcDone (__in PVOID SystemArgument1)
Definition at line 826 of file dpcobj.c.
References InterlockedDecrement.
Referenced by ExpGetPoolTagInfoTarget(), Ki386FlushTargetDescriptors(), Ki386LoadTargetLdtr(), KiLoadIopmOffset(), and KiSetIoMap().
LOGICAL KeSignalCallDpcSynchronize (__in PVOID SystemArgument2)
Definition at line 857 of file dpcobj.c.
References _DEFERRED_REVERSE_BARRIER::Barrier, DEFERRED_REVERSE_BARRIER_SYNCHRONIZED, FALSE, InterlockedDecrement, InterlockedExchange(), InterlockedIncrement, KeYieldProcessor, _DEFERRED_REVERSE_BARRIER::TotalProcessors, TRUE, and UNREFERENCED_PARAMETER.
Referenced by ExpGetPoolTagInfoTarget(), Ki386FlushTargetDescriptors(), and Ki386LoadTargetLdtr().
VOID KiInitializeDpc (IN PRKDPC Dpc, IN PKDEFERRED_ROUTINE DeferredRoutine, IN PVOID DeferredContext, IN KOBJECTS DpcType)
Definition at line 79 of file dpcobj.c.
References MediumImportance, and NULL.
Referenced by KeInitializeDpc(), and KeInitializeThreadedDpc().
FORCEINLINE PKDPC_DATA KiSelectDpcData (IN PKPRCB Prcb, IN PKDPC Dpc)
Definition at line 35 of file dpcobj.c.
References DPC_NORMAL, DPC_THREADED, FALSE, and ThreadedDpcObject.
Referenced by KeInsertQueueDpc().