Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/miscc.c File Reference
miscc.c File Reference
#include "ki.h"
Data Structures
struct _KNMI_HANDLER_CALLBACK
Typedefs
typedef struct _KNMI_HANDLER_CALLBACK KNMI_HANDLER_CALLBACK
typedef struct _KNMI_HANDLER_CALLBACK * PKNMI_HANDLER_CALLBACK
Functions
BOOLEAN KeAddSystemServiceTable (IN PULONG_PTR Base, IN PULONG Count OPTIONAL, IN ULONG Limit, IN PUCHAR Number, IN ULONG Index)
BOOLEAN KeAdjustInterruptTime (IN LONGLONG TimeDelta)
NTSTATUS KeDeregisterNmiCallback (__in PVOID Handle)
PKPRCB KeGetPrcb (ULONG ProcessorNumber)
ULONG KeGetRecommendedSharedDataAlignment (VOID)
BOOLEAN KeIsAttachedProcess (VOID)
KAFFINITY KeQueryActiveProcessors (VOID)
ULONGLONG KeQueryInterruptTime (VOID)
NTSTATUS KeQueryLogicalProcessorInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnedLength)
VOID KeQuerySystemTime (OUT PLARGE_INTEGER CurrentTime)
VOID KeQueryTickCount (OUT PLARGE_INTEGER CurrentCount)
ULONG KeQueryTimeIncrement (VOID)
PVOID KeRegisterNmiCallback (__in PNMI_CALLBACK CallbackRoutine, __in_opt PVOID Context)
BOOLEAN KeRemoveSystemServiceTable (IN ULONG Index)
VOID KeSetDmaIoCoherency (IN ULONG Attributes)
VOID KeSetProfileIrql (IN KIRQL ProfileIrql)
VOID KeSetSystemTime (IN PLARGE_INTEGER NewTime, OUT PLARGE_INTEGER OldTime, IN BOOLEAN AdjustInterruptTime, IN PLARGE_INTEGER HalTimeToSet OPTIONAL)
VOID KeSetTimeIncrement (IN ULONG MaximumIncrement, IN ULONG MinimumIncrement)
VOID KiCalibrateTimeAdjustment (PADJUST_INTERRUPT_TIME_CONTEXT Adjust)
BOOLEAN KiHandleNmi (VOID)
Variables
PKNMI_HANDLER_CALLBACK KiNmiCallbackListHead
KSPIN_LOCK KiNmiCallbackListLock
Typedef Documentation
typedef struct _KNMI_HANDLER_CALLBACK KNMI_HANDLER_CALLBACK
typedef struct _KNMI_HANDLER_CALLBACK * PKNMI_HANDLER_CALLBACK
Function Documentation
BOOLEAN KeAddSystemServiceTable (IN PULONG_PTR Base, IN PULONG Count OPTIONAL, IN ULONG Limit, IN PUCHAR Number, IN ULONG Index)
Definition at line 729 of file miscc.c.
References _KSERVICE_TABLE_DESCRIPTOR::Base, Count, _KSERVICE_TABLE_DESCRIPTOR::Count, FALSE, Index, KeServiceDescriptorTable, KeServiceDescriptorTableShadow, _KSERVICE_TABLE_DESCRIPTOR::Limit, NULL, _KSERVICE_TABLE_DESCRIPTOR::Number, NUMBER_SERVICE_TABLES, PAGED_CODE, TRUE, and WIN32K_SERVICE_INDEX.
BOOLEAN KeAdjustInterruptTime (IN LONGLONG TimeDelta)
Definition at line 425 of file miscc.c.
References ADJUST_INTERRUPT_TIME_CONTEXT::Adjustment, ADJUST_INTERRUPT_TIME_CONTEXT::Barrier, FALSE, ADJUST_INTERRUPT_TIME_CONTEXT::HalNumber, KeIpiGenericCall(), KeNumberProcessors, KiCalibrateTimeAdjustment(), ADJUST_INTERRUPT_TIME_CONTEXT::KiNumber, and TRUE.
Referenced by ExpInitializeExecutive(), KeSetSystemTime(), and KeStartAllProcessors().
NTSTATUS KeDeregisterNmiCallback (__in PVOID Handle)
Definition at line 1349 of file miscc.c.
References ASSERT, DISPATCH_LEVEL, ExFreePoolWithTag, _KNMI_HANDLER_CALLBACK::Handle, KeAcquireSpinLock, KeActiveProcessors, KeGetCurrentIrql(), KeReleaseSpinLock(), KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiNmiCallbackListHead, KiNmiCallbackListLock, _KNMI_HANDLER_CALLBACK::Next, NULL, STATUS_INVALID_HANDLE, and STATUS_SUCCESS.
PKPRCB KeGetPrcb (ULONG ProcessorNumber)
Definition at line 1171 of file miscc.c.
References ASSERT, KeNumberProcessors, KiProcessorBlock, MAXIMUM_PROCESSORS, and NULL.
ULONG KeGetRecommendedSharedDataAlignment (VOID)
Definition at line 1143 of file miscc.c.
References KeLargestCacheLine.
Referenced by ExAllocateCacheAwareRundownProtection(), ExInitializeRundownProtectionCacheAware(), ExSizeOfRundownProtectionCacheAware(), and NtQuerySystemInformation().
BOOLEAN KeIsAttachedProcess (VOID)
Definition at line 1117 of file miscc.c.
References FALSE, KiIsAttachedProcess, and TRUE.
Referenced by ExMapHandleToPointerEx(), MiAccessCheck(), MiCheckForUserStackOverflow(), MiProtectVirtualMemory(), NtNotifyChangeMultipleKeys(), ObpCloseHandle(), ObpCloseHandleTableEntry(), RtlWalkFrameChain(), and WmipQueueNotification().
KAFFINITY KeQueryActiveProcessors (VOID)
Definition at line 856 of file miscc.c.
References KeActiveProcessors, and PAGED_CODE.
ULONGLONG KeQueryInterruptTime (VOID)
Definition at line 37 of file miscc.c.
References KiQueryInterruptTime, and _LARGE_INTEGER::QuadPart.
Referenced by ExGetNextWakeTime(), and KiCalibrateTimeAdjustment().
NTSTATUS KeQueryLogicalProcessorInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnedLength)
Definition at line 884 of file miscc.c.
References _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::Cache, Index, KeActiveProcessors, KeNodeBlock, KeNumberNodes, KiProcessorBlock, LTP_PC_SMT, _KPRCB::MultiThreadProcessorSet, _KPRCB::MultiThreadSetMaster, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::NumaNode, PAGED_CODE, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::ProcessorCore, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::ProcessorMask, RelationCache, RelationNumaNode, RelationProcessorCore, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::Relationship, _SYSTEM_LOGICAL_PROCESSOR_INFORMATION::Reserved, _KPRCB::SetMember, Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
VOID KeQuerySystemTime (OUT PLARGE_INTEGER CurrentTime)
Definition at line 68 of file miscc.c.
References KiQuerySystemTime.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmpCmdHiveClose(), CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreate(), CmpDoCreateChild(), CmpSetSecurityDescriptorInfo(), CmRegisterCallback(), CmRenameKey(), CmSetKeyUserFlags(), CmSetValueKey(), DbgkExitProcess(), ExGetNextWakeTime(), ExHandleTest(), ExpAllocateUuids(), ExpRaiseHardError(), ExpUuidInitialization(), FsRtlAddToTunnelCache(), FsRtlPruneTunnelCache(), HvpWriteLog(), IopInitializeBuiltinDriver(), IopLoadDriver(), IoWMICompleteRequest(), IoWriteErrorLogEntry(), MiAdjustClaimParameters(), MiDoReplacement(), MiGatherPagefilePages(), MiProcessWorkingSets(), MiRearrangeWorkingSetExpansionList(), MiRememberUnloadedDriver(), MiSessionOutSwapProcess(), MiWriteComplete(), MmInitializeHandBuiltProcess(), MmInitializeProcessAddressSpace(), NtCreateSymbolicLinkObject(), NtQueryInformationProcess(), NtQuerySystemInformation(), NtWaitForDebugEvent(), PspCreateProcess(), PspCreateThread(), PspExitThread(), PspUserThreadStartup(), WmiGetClock(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipBuildMcaCmcEvent(), WmipFinalizeHeader(), WmipFireOffWmiEvent(), WmipInitContext(), WmipLogger(), WmipPrepareHeader(), WmipSendNotification(), and WmipStartLogger().
VOID KeQueryTickCount (OUT PLARGE_INTEGER CurrentCount)
Definition at line 97 of file miscc.c.
References KiQueryTickCount.
Referenced by CcFlushCache(), MiAllocatePoolPages(), and MiCreatePebOrTeb().
ULONG KeQueryTimeIncrement (VOID)
Definition at line 128 of file miscc.c.
References KeMaximumIncrement.
Referenced by CcInitializeCacheManager().
PVOID KeRegisterNmiCallback (__in PNMI_CALLBACK CallbackRoutine, __in_opt PVOID Context)
Definition at line 1260 of file miscc.c.
References ASSERT, _KNMI_HANDLER_CALLBACK::Callback, _KNMI_HANDLER_CALLBACK::Context, DISPATCH_LEVEL, ExAllocatePoolWithTag, _KNMI_HANDLER_CALLBACK::Handle, InterlockedCompareExchangePointer, KeAcquireSpinLock, KeGetCurrentIrql(), KeReleaseSpinLock(), KiNmiCallbackListHead, KiNmiCallbackListLock, _KNMI_HANDLER_CALLBACK::Next, NonPagedPool, and NULL.
BOOLEAN KeRemoveSystemServiceTable (IN ULONG Index)
Definition at line 807 of file miscc.c.
References _KSERVICE_TABLE_DESCRIPTOR::Base, _KSERVICE_TABLE_DESCRIPTOR::Count, FALSE, Index, KeServiceDescriptorTable, KeServiceDescriptorTableShadow, _KSERVICE_TABLE_DESCRIPTOR::Limit, NULL, _KSERVICE_TABLE_DESCRIPTOR::Number, NUMBER_SERVICE_TABLES, PAGED_CODE, TRUE, and WIN32K_SERVICE_INDEX.
VOID KeSetDmaIoCoherency (IN ULONG Attributes)
Definition at line 156 of file miscc.c.
References KiDmaIoCoherency.
VOID KeSetProfileIrql (IN KIRQL ProfileIrql)
Definition at line 189 of file miscc.c.
References ASSERT, HIGH_LEVEL, KiProfileIrql, and PROFILE_LEVEL.
VOID KeSetSystemTime (IN PLARGE_INTEGER NewTime, OUT PLARGE_INTEGER OldTime, IN BOOLEAN AdjustInterruptTime, IN PLARGE_INTEGER HalTimeToSet OPTIONAL)
Definition at line 223 of file miscc.c.
References _DISPATCHER_HEADER::Absolute, ARGUMENT_PRESENT, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _KTIMER::DueTime, _KTIMER_TABLE_ENTRY::Entry, ExCmosClockIsSane, FALSE, _LIST_ENTRY::Flink, HalSetRealTimeClock(), _DISPATCHER_HEADER::Hand, _KTIMER::Header, HIGH_LEVEL, Index, InitializeListHead(), InsertTailList(), KeAdjustInterruptTime(), KeBootTime, KeBootTimeBias, KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiAcquireTimerTableLock(), KiComputeTimerTableIndex(), KiInsertTimerTable(), KiLockDispatcherDatabase, KiQuerySystemTime, KiReleaseTimerTableLock(), KiRemoveEntryTimer(), KiTimerListExpire(), KiTimerTableListHead, KiUnlockDispatcherDatabase(), _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, RemoveEntryList(), RtlTimeToTimeFields(), SharedUserData, TIMER_TABLE_SIZE, _KTIMER::TimerListEntry, and TRUE.
Referenced by KeLoopTbFlushTimeStampUnlocked(), and Phase1InitializationDiscard().
VOID KeSetTimeIncrement (IN ULONG MaximumIncrement, IN ULONG MinimumIncrement)
Definition at line 685 of file miscc.c.
References KeMaximumIncrement, KeMinimumIncrement, KeTimeAdjustment, KeTimeIncrement, KiProcessorBlock, KiTickOffset, and max.
VOID KiCalibrateTimeAdjustment (PADJUST_INTERRUPT_TIME_CONTEXT Adjust)
Definition at line 471 of file miscc.c.
References ADJUST_INTERRUPT_TIME_CONTEXT::Adjustment, ADJUST_INTERRUPT_TIME_CONTEXT::Barrier, HalCalibratePerformanceCounter(), ADJUST_INTERRUPT_TIME_CONTEXT::HalNumber, _KSYSTEM_TIME::High1Time, _KSYSTEM_TIME::High2Time, _LARGE_INTEGER::HighPart, _ULARGE_INTEGER::HighPart, InterlockedDecrement, KeDisableInterrupts(), KeEnableInterrupts(), KeGetCurrentPrcb(), KeInsertQueueDpc(), KeInterruptTimeBias, KeMaximumIncrement, KeQueryInterruptTime(), KeQueryPerformanceCounter(), KeRemoveQueueDpc(), KeTickCount, ADJUST_INTERRUPT_TIME_CONTEXT::KiNumber, KiPollFreezeExecution(), KiQueryLowTickCount, KiTickOffset, KiTimerExpireDpc, _KSYSTEM_TIME::LowPart, _LARGE_INTEGER::LowPart, _ULARGE_INTEGER::LowPart, ADJUST_INTERRUPT_TIME_CONTEXT::NewCount, NULL, PERF_POWER, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_PO_CALIBRATED_PERFCOUNTER, PerfInfoLogBytes(), _PERFINFO_PO_CALIBRATED_PERFCOUNTER::PerformanceCounter, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, RtlEnlargedUnsignedDivide(), RtlEnlargedUnsignedMultiply(), RtlExtendedLargeIntegerDivide(), SharedUserData, _KPRCB::TickOffset, TIMER_TABLE_SIZE, and ULongToPtr.
Referenced by KeAdjustInterruptTime().
BOOLEAN KiHandleNmi (VOID)
Definition at line 1216 of file miscc.c.
References _KNMI_HANDLER_CALLBACK::Callback, _KNMI_HANDLER_CALLBACK::Context, FALSE, KiNmiCallbackListHead, _KNMI_HANDLER_CALLBACK::Next, and NULL.
Referenced by KiProcessNMI().
Variable Documentation
PKNMI_HANDLER_CALLBACK KiNmiCallbackListHead
Definition at line 1212 of file miscc.c.
Referenced by KeDeregisterNmiCallback(), KeRegisterNmiCallback(), and KiHandleNmi().
KSPIN_LOCK KiNmiCallbackListLock
Definition at line 1213 of file miscc.c.
Referenced by KeDeregisterNmiCallback(), and KeRegisterNmiCallback().