Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/deleteva.c File Reference
deleteva.c File Reference
#include "mi.h"
Functions
ULONG MiDeletePte (IN PMMPTE PointerPte, IN PVOID VirtualAddress, IN ULONG AddressSpaceDeletion, IN PEPROCESS CurrentProcess, IN PMMPTE PrototypePte, IN PMMPTE_FLUSH_LIST PteFlushList OPTIONAL, IN KIRQL OldIrql)
VOID MiDeleteValidSystemPte (IN PMMPTE PointerPte, IN PVOID VirtualAddress, IN PMMSUPPORT WsInfo, IN PMMPTE_FLUSH_LIST PteFlushList OPTIONAL)
VOID MiDeleteVirtualAddresses (IN PUCHAR Va, IN PUCHAR EndingAddress, IN PMMVAD Vad)
ULONG FASTCALL MiReleasePageFileSpace (IN MMPTE PteContents)
VOID FASTCALL MiUpdateModifiedWriterMdls (IN ULONG PageFileNumber)
Function Documentation
ULONG MiDeletePte (IN PMMPTE PointerPte, IN PVOID VirtualAddress, IN ULONG AddressSpaceDeletion, IN PEPROCESS CurrentProcess, IN PMMPTE PrototypePte, IN PMMPTE_FLUSH_LIST PteFlushList OPTIONAL, IN KIRQL OldIrql)
Definition at line 807 of file deleteva.c.
References ARGUMENT_PRESENT, ASSERT, _MMPTE_HARDWARE::Dirty, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE::Hard, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiCheckPdeForPagedPool(), MiDecrementCloneBlockReference(), MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiHighestUserPte, MiInsertPageInFreeList(), MiLocateCloneAddress, MiMakePdeExistAndMakeValid(), MiPteToProto, MiReleasePageFileSpace(), MiTerminateWsle(), MiUnlinkPageFromList(), MM_MAXIMUM_FLUSH_COUNT, MM_PFN_LOCK_ASSERT, MM_SHARED_USER_DATA_VA, MmHighestUserAddress, NOTHING, NT_SUCCESS, NULL, _MMPFN::OriginalPte, PAGE_ALIGN, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, _MMPTE_HARDWARE::Valid, _MMPTE_HARDWARE::Writable, and _MMPFN::WsIndex.
Referenced by MiDecommitPages(), MiDeletePageTablesForPhysicalRange(), MiDeletePteRange(), MiDeleteVirtualAddresses(), MiFreeLargePages(), MiGrowWsleHash(), MiRemoveMappedView(), and MiUnmapLockedPagesInUserSpace().
VOID MiDeleteValidSystemPte (IN PMMPTE PointerPte, IN PVOID VirtualAddress, IN PMMSUPPORT WsInfo, IN PMMPTE_FLUSH_LIST PteFlushList OPTIONAL)
Definition at line 1235 of file deleteva.c.
References ARGUMENT_PRESENT, ASSERT, _MM_SESSION_SPACE::CommittedPages, _MMPTE_HARDWARE::Dirty, _MMPFN::e1, _MMPTE::Hard, InterlockedDecrementSizeT, KeBugCheckEx(), MEMORY_MANAGEMENT, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiDecrementShareCount(), MiDecrementShareCountInline, MiTerminateWsle(), MM_BUMP_SESS_COUNTER, MM_DBG_SESSION_NP_HASH_SHRINK, MM_DBG_SESSION_WS_HASHPAGE_FREE, MM_MAXIMUM_FLUSH_COUNT, MM_PFN_LOCK_ASSERT, MmSessionSpace, _MM_SESSION_SPACE::NonPageablePages, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, _MMPTE_HARDWARE::Valid, _MMPTE_HARDWARE::Writable, and _MMPFN::WsIndex.
Referenced by MiDeletePteRange(), and MiGrowWsleHash().
VOID MiDeleteVirtualAddresses (IN PUCHAR Va, IN PUCHAR EndingAddress, IN PMMVAD Vad)
Definition at line 160 of file deleteva.c.
References ASSERT, ASSERT64, _EPROCESS::CloneRoot, _MMPTE_FLUSH_LIST::Count, DbgBreakPoint(), DbgPrintEx(), _MMPTE_HARDWARE::Dirty, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, FALSE, _MMPTE::Hard, IS_PTE_NOT_DEMAND_ZERO, LOCK_PFN, _MMPTE::Long, MI_CHECK_USED_PTES_HANDLE, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_USED_PTES_FROM_HANDLE, MI_GET_USED_PTES_HANDLE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_VA_TO_VPN, MI_WRITE_ZERO_PTE, MiDeletePte(), MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiFlushPteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiHighestUserPte, MiIsPteOnPdeBoundary, MiIsVirtualAddressOnPdeBoundary, MiLocateCloneAddress, MiLocateSubsection(), MiPteToProto, MiTerminateWsle(), MM_NOIRQL, NULL, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, PrototypePte, PsGetCurrentProcess(), _SUBSECTION::PtesInSubsection, SATISFY_OVERZEALOUS_COMPILER, _MMPTE::Soft, _SUBSECTION::SubsectionBase, TRUE, _MMPTE::u, _MMPFN::u1, UNLOCK_PFN, VadImageMap, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMPTE_HARDWARE::Writable, and _MMPFN::WsIndex.
Referenced by MiRemoveMappedView(), MmCleanProcessAddressSpace(), MmDeleteTeb(), and NtFreeVirtualMemory().
ULONG FASTCALL MiReleasePageFileSpace (IN MMPTE PteContents)
Definition at line 1373 of file deleteva.c.
References ASSERT, _MMPAGING_FILE::Bitmap, _RTL_BITMAP::Buffer, _MMPAGING_FILE::CurrentUsage, FALSE, _MMPAGING_FILE::FreeSpace, GET_PAGING_FILE_NUMBER, GET_PAGING_FILE_OFFSET, MI_CLEAR_BIT, MI_PTE_LOOKUP_NEEDED, MiUpdateModifiedWriterMdls(), MM_PFN_LOCK_ASSERT, MM_USABLE_PAGES_FREE, MmNumberOfActiveMdlEntries, MmPagingFile, MmPagingFileDebug, RtlCheckBit, and TRUE.
Referenced by MiCleanSection(), MiDecommitPages(), MiDecrementCloneBlockReference(), MiDeletePte(), MiDeleteSystemPageableVm(), MiMakeOutswappedPageResident(), MiPurgeImageSection(), MiRemoveUnusedSegments(), MiResetVirtualMemory(), MiSegmentDelete(), MiSetDirtyBit(), MiSetPageModified(), MiWriteComplete(), MmPurgeSection(), and MmSetAddressRangeModified().
VOID FASTCALL MiUpdateModifiedWriterMdls (IN ULONG PageFileNumber)
Definition at line 1458 of file deleteva.c.
References ASSERT, _MMMOD_WRITER_MDL_ENTRY::CurrentList, _MMPAGING_FILE::Entry, _MMMOD_WRITER_LISTHEAD::Event, FALSE, InsertTailList(), KeSetEvent(), _MMMOD_WRITER_MDL_ENTRY::Links, _MMMOD_WRITER_LISTHEAD::ListHead, MM_PAGING_FILE_MDLS, MmFreePagingSpaceLow, MmNumberOfActiveMdlEntries, MmPagingFile, MmPagingFileHeader, _MMMOD_WRITER_MDL_ENTRY::PagingListHead, and RemoveEntryList().
Referenced by MiExtendPagingFileMaximum(), MiFinishPageFileExtension(), MiReleaseConfirmedPageFileSpace(), and MiReleasePageFileSpace().