Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/fmutexc.c File Reference
fmutexc.c File Reference
#include "exp.h"
Functions
VOID FASTCALL ExAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
VOID FASTCALL ExAcquireFastMutexUnsafe (__inout PFAST_MUTEX FastMutex)
VOID FASTCALL ExEnterCriticalRegionAndAcquireFastMutexUnsafe (__inout PFAST_MUTEX FastMutex)
VOID FASTCALL ExReleaseFastMutex (__inout PFAST_MUTEX FastMutex)
VOID FASTCALL ExReleaseFastMutexUnsafe (__inout PFAST_MUTEX FastMutex)
VOID FASTCALL ExReleaseFastMutexUnsafeAndLeaveCriticalRegion (__inout PFAST_MUTEX FastMutex)
BOOLEAN FASTCALL ExTryToAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
Function Documentation
VOID FASTCALL ExAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
Definition at line 26 of file fmutexc.c.
References xxAcquireFastMutex().
Referenced by CcCopyWrite(), CcZeroEndOfLastPage(), DbgkClearProcessDebugObject(), DbgkCopyProcessDebugPort(), DbgkOpenProcessDebugPort(), DbgkpCloseObject(), DbgkpMarkProcessPeb(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), ExpUpdateDebugInfo(), ExSwapinWorkerThreads(), FsRtlAddToTunnelCache(), FsRtlCancelExclusiveIrp(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFindInTunnelCache(), FsRtlInsertPerFileObjectContext(), FsRtlInsertPerStreamContext(), FsRtlLookupPerFileObjectContext(), FsRtlLookupPerStreamContextInternal(), FsRtlRemovePerFileObjectContext(), FsRtlRemovePerStreamContext(), FsRtlTeardownPerStreamContexts(), KeGenericCallDpc(), NtDebugContinue(), NtSetInformationDebugObject(), NtWaitForDebugEvent(), and RtlpTraceDatabaseAcquireLock().
VOID FASTCALL ExAcquireFastMutexUnsafe (__inout PFAST_MUTEX FastMutex)
Definition at line 120 of file fmutexc.c.
References xxAcquireFastMutexUnsafe().
Referenced by ExUuidCreate(), FsRtlAcknowledgeOplockBreak(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeOplock(), and NtAllocateUuids().
VOID FASTCALL ExEnterCriticalRegionAndAcquireFastMutexUnsafe (__inout PFAST_MUTEX FastMutex)
Definition at line 149 of file fmutexc.c.
References KeEnterCriticalRegion(), and xxAcquireFastMutexUnsafe().
VOID FASTCALL ExReleaseFastMutex (__inout PFAST_MUTEX FastMutex)
Definition at line 57 of file fmutexc.c.
References xxReleaseFastMutex().
Referenced by CcCopyWrite(), CcZeroEndOfLastPage(), DbgkClearProcessDebugObject(), DbgkCopyProcessDebugPort(), DbgkOpenProcessDebugPort(), DbgkpCloseObject(), DbgkpMarkProcessPeb(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), ExpUpdateDebugInfo(), ExSwapinWorkerThreads(), FsRtlAddToTunnelCache(), FsRtlCancelExclusiveIrp(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlDeleteKeyFromTunnelCache(), FsRtlFindInTunnelCache(), FsRtlInsertPerFileObjectContext(), FsRtlInsertPerStreamContext(), FsRtlLookupPerFileObjectContext(), FsRtlLookupPerStreamContextInternal(), FsRtlRemovePerFileObjectContext(), FsRtlRemovePerStreamContext(), FsRtlTeardownPerStreamContexts(), KeGenericCallDpc(), NtDebugContinue(), NtSetInformationDebugObject(), NtWaitForDebugEvent(), and RtlpTraceDatabaseReleaseLock().
VOID FASTCALL ExReleaseFastMutexUnsafe (__inout PFAST_MUTEX FastMutex)
Definition at line 183 of file fmutexc.c.
References xxReleaseFastMutexUnsafe().
Referenced by ExUuidCreate(), FsRtlAcknowledgeOplockBreak(), FsRtlOpBatchBreakClosePending(), FsRtlOplockBreakNotify(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeOplock(), FsRtlWaitOnIrp(), and NtAllocateUuids().
VOID FASTCALL ExReleaseFastMutexUnsafeAndLeaveCriticalRegion (__inout PFAST_MUTEX FastMutex)
Definition at line 212 of file fmutexc.c.
References KeLeaveCriticalRegion(), and xxReleaseFastMutexUnsafe().
BOOLEAN FASTCALL ExTryToAcquireFastMutex (__inout PFAST_MUTEX FastMutex)
Definition at line 88 of file fmutexc.c.
References xxTryToAcquireFastMutex().