Windows Research Kernel v1.2: C:/Windows Research Kernel/se/rmp.h File Reference
rmp.h File Reference
#include <nt.h>
#include <ntlsa.h>
#include "sep.h"
Data Structures
struct _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION
struct _SEP_LOGON_SESSION_TOKEN
struct _SEP_RM_CONNECT_INFO
struct _SEP_RM_STATE
Macros
#define SEP_LOGON_TRACK_ARRAY_SIZE (0x00000010L)
#define SEP_LOGON_TRACK_INDEX_MASK (0x0000000FL)
#define SEP_LOGON_TRACK_LOCK_ARRAY_SIZE (0x00000004L)
#define SEP_LOGON_TRACK_LOCK_INDEX_MASK (0x00000003L)
#define SEP_RM_COMMAND_MAX 4
#define SEP_RM_LSA_SHARED_MEMORY_SIZE ((ULONG) PAGE_SIZE)
#define SEP_TERMINATION_NOTIFY 0x1
#define SepRmAcquireDbReadLock(i)
#define SepRmAcquireDbWriteLock(i)
#define SepRmAcquireNotifyLock()
#define SepRmReleaseDbReadLock(i)
#define SepRmReleaseDbWriteLock(i)
#define SepRmReleaseNotifyLock()
Typedefs
typedef struct _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION * PSEP_LOGON_SESSION_TERMINATED_NOTIFICATION
typedef struct _SEP_LOGON_SESSION_TOKEN * PSEP_LOGON_SESSION_TOKEN
typedef struct SEP_RM_CONNECT_INFO * PSEP_RM_CONNECT_INFO
typedef struct _SEP_RM_STATE * PSEP_RM_STATE
typedef struct _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION SEP_LOGON_SESSION_TERMINATED_NOTIFICATION
typedef struct _SEP_LOGON_SESSION_TOKEN SEP_LOGON_SESSION_TOKEN
typedef VOID(* SEP_RM_COMMAND_WORKER) (PRM_COMMAND_MESSAGE, PRM_REPLY_MESSAGE)
typedef struct _SEP_RM_CONNECT_INFO SEP_RM_CONNECT_INFO
typedef struct _SEP_RM_STATE SEP_RM_STATE
Functions
NTSTATUS SepCreateLogonSessionTrack (IN PLUID LogonId)
NTSTATUS SepDeleteLogonSessionTrack (IN PLUID LogonId)
VOID SepRmCommandServerThread (IN PVOID StartContext)
BOOLEAN SepRmCommandServerThreadInit ()
VOID SepRmComponentTestCommandWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
VOID SepRmCreateLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
BOOLEAN SepRmDbInitialization (VOID)
VOID SepRmDeleteLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
VOID SepRmSendCommandToLsaWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
VOID SepRmSetAuditEventWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
Variables
SEP_LOGON_SESSION_TERMINATED_NOTIFICATION SeFileSystemNotifyRoutinesHead
PSEP_LOGON_SESSION_REFERENCES * SepLogonSessions
ERESOURCE SepRmDbLock []
PEPROCESS SepRmLsaCallProcess
FAST_MUTEX SepRmNotifyMutex
SEP_RM_STATE SepRmState
Macro Definition Documentation
#define SEP_LOGON_TRACK_ARRAY_SIZE (0x00000010L)
Definition at line 40 of file rmp.h.
Referenced by SepRmDbInitialization().
#define SEP_LOGON_TRACK_INDEX_MASK (0x0000000FL)
Definition at line 39 of file rmp.h.
#define SEP_LOGON_TRACK_LOCK_ARRAY_SIZE (0x00000004L)
Definition at line 51 of file rmp.h.
Referenced by SepRmDbInitialization().
#define SEP_LOGON_TRACK_LOCK_INDEX_MASK (0x00000003L)
Definition at line 50 of file rmp.h.
#define SEP_RM_COMMAND_MAX 4
Definition at line 131 of file rmp.h.
#define SEP_RM_LSA_SHARED_MEMORY_SIZE ((ULONG) PAGE_SIZE)
Definition at line 90 of file rmp.h.
Referenced by SepRmCallLsa().
#define SEP_TERMINATION_NOTIFY 0x1
Definition at line 141 of file rmp.h.
Referenced by SeMarkLogonSessionForTerminationNotification(), and SepDeReferenceLogonSession().
#define SepRmAcquireDbReadLock (i)
Value:
KeEnterCriticalRegion();         \
                                   ExAcquireResourceSharedLite(&(SepRmDbLock[(i) & SEP_LOGON_TRACK_LOCK_INDEX_MASK]), TRUE)
Definition at line 65 of file rmp.h.
#define SepRmAcquireDbWriteLock (i)
Value:
KeEnterCriticalRegion();         \
                                   ExAcquireResourceExclusiveLite(&(SepRmDbLock[(i) & SEP_LOGON_TRACK_LOCK_INDEX_MASK]), TRUE)
Definition at line 68 of file rmp.h.
Referenced by SeGetLogonIdDeviceMap(), SeMarkLogonSessionForTerminationNotification(), SepCreateLogonSessionTrack(), SepDeleteLogonSessionTrack(), SepDeReferenceLogonSession(), and SepReferenceLogonSession().
#define SepRmAcquireNotifyLock ()
Value:
KeEnterCriticalRegion();         \
                                  ExAcquireFastMutexUnsafe(&SepRmNotifyMutex)
Definition at line 77 of file rmp.h.
Referenced by SepNotifyFileSystems(), SeRegisterLogonSessionTerminatedRoutine(), and SeUnregisterLogonSessionTerminatedRoutine().
#define SepRmReleaseDbReadLock (i)
Value:
ExReleaseResourceLite(&(SepRmDbLock[(i) & SEP_LOGON_TRACK_LOCK_INDEX_MASK])); \
                                   KeLeaveCriticalRegion()
Definition at line 71 of file rmp.h.
#define SepRmReleaseDbWriteLock (i)
Value:
ExReleaseResourceLite(&(SepRmDbLock[(i) & SEP_LOGON_TRACK_LOCK_INDEX_MASK])); \
                                   KeLeaveCriticalRegion()
Definition at line 74 of file rmp.h.
Referenced by SeGetLogonIdDeviceMap(), SeMarkLogonSessionForTerminationNotification(), SepCreateLogonSessionTrack(), SepDeleteLogonSessionTrack(), SepDeReferenceLogonSession(), and SepReferenceLogonSession().
#define SepRmReleaseNotifyLock ()
Value:
ExReleaseFastMutexUnsafe(&SepRmNotifyMutex); \
                                  KeLeaveCriticalRegion()
Definition at line 80 of file rmp.h.
Referenced by SepNotifyFileSystems(), SeRegisterLogonSessionTerminatedRoutine(), and SeUnregisterLogonSessionTerminatedRoutine().
Typedef Documentation
typedef struct _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION * PSEP_LOGON_SESSION_TERMINATED_NOTIFICATION
typedef struct _SEP_LOGON_SESSION_TOKEN * PSEP_LOGON_SESSION_TOKEN
typedef struct SEP_RM_CONNECT_INFO* PSEP_RM_CONNECT_INFO
Definition at line 124 of file rmp.h.
typedef struct _SEP_RM_STATE * PSEP_RM_STATE
typedef struct _SEP_LOGON_SESSION_TERMINATED_NOTIFICATION SEP_LOGON_SESSION_TERMINATED_NOTIFICATION
typedef struct _SEP_LOGON_SESSION_TOKEN SEP_LOGON_SESSION_TOKEN
typedef VOID(* SEP_RM_COMMAND_WORKER) (PRM_COMMAND_MESSAGE, PRM_REPLY_MESSAGE)
Definition at line 133 of file rmp.h.
typedef struct _SEP_RM_CONNECT_INFO SEP_RM_CONNECT_INFO
typedef struct _SEP_RM_STATE SEP_RM_STATE
Function Documentation
NTSTATUS SepCreateLogonSessionTrack (IN PLUID LogonId)
Definition at line 800 of file rmlogon.c.
References DbgPrint(), ExAllocatePoolWithTag, ExFreePool(), InitializeListHead(), _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, PAGED_CODE, PagedPool, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, RtlZeroMemory, SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_INSUFFICIENT_RESOURCES, STATUS_LOGON_SESSION_EXISTS, and STATUS_SUCCESS.
Referenced by SepRmCreateLogonSessionWrkr(), and SepRmDbInitialization().
NTSTATUS SepDeleteLogonSessionTrack (IN PLUID LogonId)
Definition at line 925 of file rmlogon.c.
References ExFreePool(), _SEP_LOGON_SESSION_REFERENCES::LogonId, _SEP_LOGON_SESSION_REFERENCES::Next, NULL, ObfDereferenceDeviceMap(), PAGED_CODE, _SEP_LOGON_SESSION_REFERENCES::pDeviceMap, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, RtlEqualLuid, SepCleanupLUIDDeviceMapDirectory(), SepLogonSessionIndex, SepLogonSessions, SepRmAcquireDbWriteLock, SepRmReleaseDbWriteLock, STATUS_BAD_LOGON_SESSION_STATE, STATUS_NO_SUCH_LOGON_SESSION, and STATUS_SUCCESS.
Referenced by SepRmDeleteLogonSessionWrkr().
VOID SepRmCommandServerThread (IN PVOID StartContext)
Definition at line 291 of file rmmain.c.
References ASSERT, _PORT_MESSAGE::ClientId, Executive, FALSE, KdPrint, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPC_PORT_CLOSED, LPC_REQUEST, _SEP_RM_STATE::LsaCommandPortHandle, _RM_COMMAND_MESSAGE::MessageHeader, _RM_REPLY_MESSAGE::MessageHeader, _PORT_MESSAGE::MessageId, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, PoRequestShutdownEvent(), RmAuditSetCommand, _SEP_RM_STATE::RmCommandPortHandle, _SEP_RM_STATE::RmCommandServerPortHandle, RmDeleteLogonSession, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SepAdtLsaDeadEvent, SepLockLsaQueue, SepLsaHandle, SepRmCommandDispatch, SepRmCommandServerThreadInit(), SepRmState, SepUnlockLsaQueue, SepWorkListEmpty, Status, STATUS_INVALID_CID, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_UNSUCCESSFUL, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, UNREFERENCED_PARAMETER, _PORT_MESSAGE::ZeroInit, ZwAcceptConnectPort(), ZwClose(), and ZwReplyWaitReceivePort().
Referenced by SeRmInitPhase1().
BOOLEAN SepRmCommandServerThreadInit ()
VOID SepRmComponentTestCommandWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
VOID SepRmCreateLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
Definition at line 144 of file rmlogon.c.
References ASSERT, PAGED_CODE, RmCreateLogonSession, SepCreateLogonSessionTrack(), Status, and UNALIGNED.
BOOLEAN SepRmDbInitialization (VOID)
Definition at line 99 of file rmvars.c.
References ASSERT, _SEP_RM_STATE::AuditingEnabled, ExAllocatePoolWithTag, ExInitializeFastMutex, ExInitializeResourceLite(), FALSE, LSA_MODE_PASSWORD_PROTECTED, NT_SUCCESS, NULL, _SEP_RM_STATE::OperationalMode, PagedPool, SeAnonymousAuthenticationId, SEP_LOGON_TRACK_ARRAY_SIZE, SEP_LOGON_TRACK_LOCK_ARRAY_SIZE, SepCreateLogonSessionTrack(), SeSystemAuthenticationId, Status, and TRUE.
Referenced by SepRmInitPhase0().
VOID SepRmDeleteLogonSessionWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
Definition at line 222 of file rmlogon.c.
References ASSERT, PAGED_CODE, RmDeleteLogonSession, SepDeleteLogonSessionTrack(), Status, and UNALIGNED.
VOID SepRmSendCommandToLsaWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
VOID SepRmSetAuditEventWrkr (IN PRM_COMMAND_MESSAGE CommandMessage, OUT PRM_REPLY_MESSAGE ReplyMessage)
Definition at line 39 of file rmaudit.c.
References ASSERT, AuditEventMaxType, AuditEventMinType, _SE_AUDITING_STATE::AuditOnFailure, _SE_AUDITING_STATE::AuditOnSuccess, FALSE, PAGED_CODE, POLICY_AUDIT_EVENT_FAILURE, POLICY_AUDIT_EVENT_SUCCESS, RmAuditSetCommand, SeAuditingState, SepAdtAuditingEnabled, SepAdtInitializeBounds(), STATUS_SUCCESS, and TRUE.
Variable Documentation
SEP_LOGON_SESSION_TERMINATED_NOTIFICATION SeFileSystemNotifyRoutinesHead
Definition at line 37 of file rmlogon.c.
Referenced by SepNotifyFileSystems(), SeRegisterLogonSessionTerminatedRoutine(), and SeUnregisterLogonSessionTerminatedRoutine().
PSEP_LOGON_SESSION_REFERENCES* SepLogonSessions
Definition at line 88 of file rmvars.c.
Referenced by SeGetLogonIdDeviceMap(), SeMarkLogonSessionForTerminationNotification(), SepCreateLogonSessionTrack(), SepDeleteLogonSessionTrack(), SepDeReferenceLogonSession(), and SepReferenceLogonSession().
ERESOURCE SepRmDbLock[]
Definition at line 45 of file rmvars.c.
PEPROCESS SepRmLsaCallProcess
Definition at line 72 of file rmvars.c.
Referenced by SepRmCallLsa(), and SepRmCommandServerThreadInit().
FAST_MUTEX SepRmNotifyMutex
Definition at line 52 of file rmvars.c.
SEP_RM_STATE SepRmState
Definition at line 78 of file rmvars.c.
Referenced by SepRmCallLsa(), SepRmCommandServerThread(), SepRmCommandServerThreadInit(), and SeRmInitPhase1().