Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/largemcb.c File Reference
largemcb.c File Reference
#include "FsRtlP.h"
Data Structures
struct _MAPPING
struct _NONOPAQUE_BASE_MCB
Macros
#define Dbg (0x80000000)
#define EndingLbn(MCB, I)
#define EndingVbn(MCB, I)
#define FsRtlAllocateFastMutex() ExAllocateFromNPagedLookasideList(&FsRtlFastMutexLookasideList)
#define FsRtlAllocateFirstMapping() (PVOID)ExAllocateFromPagedLookasideList(&FsRtlFirstMappingLookasideList)
#define FsRtlFreeFastMutex(FastMutex) ExFreeToNPagedLookasideList(&FsRtlFastMutexLookasideList, (FastMutex))
#define FsRtlFreeFirstMapping(Mapping) ExFreeToPagedLookasideList(&FsRtlFirstMappingLookasideList, (Mapping))
#define INITIAL_MAXIMUM_PAIR_COUNT (15)
#define MODULE_POOL_TAG ('mrSF')
#define NextStartingLbn(MCB, I)
#define NextStartingVbn(MCB, I)
#define PreviousEndingLbn(MCB, I)
#define PreviousEndingVbn(MCB, I)
#define SectorsWithinRun(MCB, I)
#define SizeOfMapping(MCB) ((sizeof(MAPPING) * (MCB)->MaximumPairCount))
#define StartingLbn(MCB, I)
#define StartingVbn(MCB, I)
#define UNUSED_LBN (-1)
Typedefs
typedef struct _MAPPING MAPPING
typedef struct _NONOPAQUE_BASE_MCB NONOPAQUE_BASE_MCB
typedef MAPPING * PMAPPING
typedef struct _NONOPAQUE_BASE_MCB * PNONOPAQUE_BASE_MCB
Functions
BOOLEAN FsRtlAddBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeLbn, __in LONGLONG LargeSectorCount)
VOID FsRtlAddLargeEntry (IN PBASE_MCB Mcb, IN ULONG WhereToAddIndex, IN ULONG AmountToAdd)
BOOLEAN FsRtlAddLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeLbn, __in LONGLONG LargeSectorCount)
BOOLEAN FsRtlAddMcbEntry (__in PMCB Mcb, __in VBN Vbn, __in LBN Lbn, __in ULONG SectorCount)
BOOLEAN FsRtlFindLargeIndex (IN PBASE_MCB Mcb, IN VBN Vbn, OUT PULONG Index)
BOOLEAN FsRtlGetNextBaseMcbEntry (__in PBASE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PLONGLONG LargeSectorCount)
BOOLEAN FsRtlGetNextLargeMcbEntry (__in PLARGE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PLONGLONG LargeSectorCount)
BOOLEAN FsRtlGetNextMcbEntry (__in PMCB Mcb, __in ULONG RunIndex, __out PVBN Vbn, __out PLBN Lbn, __out PULONG SectorCount)
VOID FsRtlInitializeBaseMcb (__in PBASE_MCB Mcb, __in POOL_TYPE PoolType)
VOID FsRtlInitializeLargeMcb (__in PLARGE_MCB Mcb, __in POOL_TYPE PoolType)
VOID FsRtlInitializeLargeMcbs (VOID)
VOID FsRtlInitializeMcb (__in PMCB Mcb, __in POOL_TYPE PoolType)
BOOLEAN FsRtlLookupBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn, __out_opt PLONGLONG LargeLbn, __out_opt PLONGLONG LargeSectorCount, __out_opt PLONGLONG LargeStartingLbn, __out_opt PLONGLONG LargeCountFromStartingLbn, __out_opt PULONG Index)
BOOLEAN FsRtlLookupLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __out_opt PLONGLONG LargeLbn, __out_opt PLONGLONG LargeSectorCount, __out_opt PLONGLONG LargeStartingLbn, __out_opt PLONGLONG LargeCountFromStartingLbn, __out_opt PULONG Index)
BOOLEAN FsRtlLookupLastBaseMcbEntry (__in PBASE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn)
BOOLEAN FsRtlLookupLastBaseMcbEntryAndIndex (__in PBASE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
BOOLEAN FsRtlLookupLastLargeMcbEntry (__in PLARGE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn)
BOOLEAN FsRtlLookupLastLargeMcbEntryAndIndex (__in PLARGE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
BOOLEAN FsRtlLookupLastMcbEntry (__in PMCB Mcb, __out PVBN Vbn, __out PLBN Lbn)
BOOLEAN FsRtlLookupMcbEntry (__in PMCB Mcb, __in VBN Vbn, __out PLBN Lbn, __out_opt PULONG SectorCount, __out PULONG Index)
ULONG FsRtlNumberOfRunsInBaseMcb (__in PBASE_MCB Mcb)
ULONG FsRtlNumberOfRunsInLargeMcb (__in PLARGE_MCB Mcb)
ULONG FsRtlNumberOfRunsInMcb (__in PMCB Mcb)
VOID FsRtlRemoveBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG SectorCount)
VOID FsRtlRemoveLargeEntry (IN PBASE_MCB Mcb, IN ULONG WhereToRemoveIndex, IN ULONG AmountToRemove)
VOID FsRtlRemoveLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeSectorCount)
VOID FsRtlRemoveMcbEntry (__in PMCB OpaqueMcb, __in VBN Vbn, __in ULONG SectorCount)
NTKERNELAPI VOID FsRtlResetBaseMcb (__in PBASE_MCB Mcb)
NTKERNELAPI VOID FsRtlResetLargeMcb (__in PLARGE_MCB Mcb, __in BOOLEAN SelfSynchronized)
BOOLEAN FsRtlSplitBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeAmount)
BOOLEAN FsRtlSplitLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeAmount)
VOID FsRtlTruncateBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn)
VOID FsRtlTruncateLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn)
VOID FsRtlTruncateMcb (__in PMCB Mcb, __in VBN Vbn)
VOID FsRtlUninitializeBaseMcb (__in PBASE_MCB Mcb)
VOID FsRtlUninitializeLargeMcb (__in PLARGE_MCB Mcb)
VOID FsRtlUninitializeMcb (__in PMCB Mcb)
Variables
NPAGED_LOOKASIDE_LIST FsRtlFastMutexLookasideList
PAGED_LOOKASIDE_LIST FsRtlFirstMappingLookasideList
Macro Definition Documentation
#define Dbg (0x80000000)
Definition at line 82 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlAddLargeMcbEntry(), FsRtlGetNextBaseMcbEntry(), FsRtlGetNextLargeMcbEntry(), FsRtlInitializeBaseMcb(), FsRtlInitializeLargeMcb(), FsRtlLookupBaseMcbEntry(), FsRtlLookupLargeMcbEntry(), FsRtlLookupLastBaseMcbEntry(), FsRtlLookupLastBaseMcbEntryAndIndex(), FsRtlLookupLastLargeMcbEntry(), FsRtlLookupLastLargeMcbEntryAndIndex(), FsRtlNumberOfRunsInLargeMcb(), FsRtlRemoveBaseMcbEntry(), FsRtlRemoveLargeMcbEntry(), FsRtlSplitBaseMcb(), FsRtlSplitLargeMcb(), FsRtlTruncateBaseMcb(), FsRtlTruncateLargeMcb(), FsRtlUninitializeBaseMcb(), and FsRtlUninitializeLargeMcb().
#define EndingLbn (MCB, I)
Value:
(\
    (LBN)(StartingLbn(MCB,I) == UNUSED_LBN ?                     \
          UNUSED_LBN :                                           \
          ((MCB)->Mapping[(I)].Lbn +                             \
           (MCB)->Mapping[(I)].NextVbn - StartingVbn(MCB,I) - 1) \
         )                                                       \
)
Definition at line 210 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlLookupLastBaseMcbEntry(), and FsRtlLookupLastBaseMcbEntryAndIndex().
#define EndingVbn (MCB, I)
Value:
(\
    (VBN)((((MCB)->Mapping)[(I)].NextVbn) - 1) \
)
Definition at line 191 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlFindLargeIndex(), FsRtlLookupBaseMcbEntry(), FsRtlLookupLastBaseMcbEntry(), FsRtlLookupLastBaseMcbEntryAndIndex(), and FsRtlRemoveBaseMcbEntry().
#define FsRtlAllocateFastMutex () ExAllocateFromNPagedLookasideList(&FsRtlFastMutexLookasideList)
Definition at line 268 of file largemcb.c.
Referenced by FsRtlInitializeLargeMcb().
#define FsRtlAllocateFirstMapping () (PVOID)ExAllocateFromPagedLookasideList(&FsRtlFirstMappingLookasideList)
Definition at line 262 of file largemcb.c.
Referenced by FsRtlInitializeBaseMcb(), and FsRtlTruncateBaseMcb().
#define FsRtlFreeFastMutex (FastMutex) ExFreeToNPagedLookasideList(&FsRtlFastMutexLookasideList, (FastMutex))
Definition at line 271 of file largemcb.c.
Referenced by FsRtlInitializeLargeMcb(), and FsRtlUninitializeLargeMcb().
#define FsRtlFreeFirstMapping (Mapping) ExFreeToPagedLookasideList(&FsRtlFirstMappingLookasideList, (Mapping))
Definition at line 265 of file largemcb.c.
Referenced by FsRtlAddLargeEntry(), and FsRtlUninitializeBaseMcb().
#define INITIAL_MAXIMUM_PAIR_COUNT (15)
Definition at line 284 of file largemcb.c.
Referenced by FsRtlAddLargeEntry(), FsRtlInitializeBaseMcb(), FsRtlInitializeLargeMcbs(), FsRtlTruncateBaseMcb(), and FsRtlUninitializeBaseMcb().
#define MODULE_POOL_TAG ('mrSF')
Definition at line 231 of file largemcb.c.
#define NextStartingLbn (MCB, I)
Value:
(\
    (LBN)((I) >= (MCB)->PairCount - 1 ? UNUSED_LBN : StartingLbn(MCB,(I)+1)) \
)
Definition at line 218 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), and FsRtlRemoveBaseMcbEntry().
#define NextStartingVbn (MCB, I)
Value:
(\
    (VBN)((I) >= (MCB)->PairCount ? 0 : StartingVbn(MCB,(I)+1)) \
)
Definition at line 195 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), and FsRtlTruncateBaseMcb().
#define PreviousEndingLbn (MCB, I)
Value:
(\
    (LBN)((I) == 0 ? UNUSED_LBN : EndingLbn(MCB,(I)-1)) \
)
Definition at line 202 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlRemoveBaseMcbEntry(), and FsRtlSplitBaseMcb().
#define PreviousEndingVbn (MCB, I)
Value:
(\
    (VBN)((I) == 0 ? 0xffffffff : EndingVbn(MCB,(I)-1)) \
)
Definition at line 183 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry().
#define SectorsWithinRun (MCB, I)
Value:
(\
    (ULONG)(EndingVbn(MCB,I) - StartingVbn(MCB,I) + 1) \
)
Definition at line 222 of file largemcb.c.
Referenced by FsRtlGetNextBaseMcbEntry(), and FsRtlRemoveBaseMcbEntry().
#define SizeOfMapping (MCB) ((sizeof(MAPPING) * (MCB)->MaximumPairCount))
Definition at line 166 of file largemcb.c.
#define StartingLbn (MCB, I)
Value:
(\
    (LBN)(((MCB)->Mapping)[(I)].Lbn) \
)
Definition at line 206 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlGetNextBaseMcbEntry(), FsRtlLookupBaseMcbEntry(), FsRtlRemoveBaseMcbEntry(), FsRtlSplitBaseMcb(), and FsRtlTruncateBaseMcb().
#define StartingVbn (MCB, I)
Value:
(\
    (VBN)((I) == 0 ? 0 : (((MCB)->Mapping))[(I)-1].NextVbn) \
)
Definition at line 187 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlFindLargeIndex(), FsRtlGetNextBaseMcbEntry(), FsRtlLookupBaseMcbEntry(), FsRtlRemoveBaseMcbEntry(), and FsRtlSplitBaseMcb().
#define UNUSED_LBN (-1)
Definition at line 147 of file largemcb.c.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlGetNextBaseMcbEntry(), FsRtlLookupBaseMcbEntry(), FsRtlLookupLastBaseMcbEntryAndIndex(), FsRtlRemoveBaseMcbEntry(), FsRtlSplitBaseMcb(), and FsRtlTruncateBaseMcb().
Typedef Documentation
typedef struct _MAPPING MAPPING
typedef struct _NONOPAQUE_BASE_MCB NONOPAQUE_BASE_MCB
typedef MAPPING* PMAPPING
Definition at line 153 of file largemcb.c.
typedef struct _NONOPAQUE_BASE_MCB * PNONOPAQUE_BASE_MCB
Function Documentation
BOOLEAN FsRtlAddBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeLbn, __in LONGLONG LargeSectorCount)
Definition at line 1045 of file largemcb.c.
References ASSERT, ASSERTMSG, Dbg, DebugTrace, EndingLbn, EndingVbn, FALSE, FsRtlAddLargeEntry(), FsRtlFindLargeIndex(), FsRtlRemoveLargeEntry(), Index, _NONOPAQUE_BASE_MCB::Mapping, NextStartingLbn, NextStartingVbn, NOTHING, PreviousEndingLbn, PreviousEndingVbn, StartingLbn, StartingVbn, TRUE, try_return, and UNUSED_LBN.
Referenced by FsRtlAddLargeMcbEntry().
VOID FsRtlAddLargeEntry (IN PBASE_MCB Mcb, IN ULONG WhereToAddIndex, IN ULONG AmountToAdd)
Definition at line 3227 of file largemcb.c.
References ExFreePool(), FsRtlFreeFirstMapping, FsRtlpAllocatePool, INITIAL_MAXIMUM_PAIR_COUNT, _NONOPAQUE_BASE_MCB::Mapping, _NONOPAQUE_BASE_MCB::MaximumPairCount, PagedPool, _NONOPAQUE_BASE_MCB::PairCount, _NONOPAQUE_BASE_MCB::PoolType, RtlCopyMemory, and RtlMoveMemory.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlRemoveBaseMcbEntry(), and FsRtlSplitBaseMcb().
BOOLEAN FsRtlAddLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeLbn, __in LONGLONG LargeSectorCount)
Definition at line 1583 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlAddBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlAddMcbEntry().
BOOLEAN FsRtlAddMcbEntry (__in PMCB Mcb, __in VBN Vbn, __in LBN Lbn, __in ULONG SectorCount)
Definition at line 346 of file largemcb.c.
References FsRtlAddLargeMcbEntry(), and PAGED_CODE.
BOOLEAN FsRtlFindLargeIndex (IN PBASE_MCB Mcb, IN VBN Vbn, OUT PULONG Index)
Definition at line 3122 of file largemcb.c.
References EndingVbn, FALSE, _NONOPAQUE_BASE_MCB::PairCount, StartingVbn, and TRUE.
Referenced by FsRtlAddBaseMcbEntry(), FsRtlLookupBaseMcbEntry(), FsRtlRemoveBaseMcbEntry(), FsRtlSplitBaseMcb(), and FsRtlTruncateBaseMcb().
BOOLEAN FsRtlGetNextBaseMcbEntry (__in PBASE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PLONGLONG LargeSectorCount)
Definition at line 2680 of file largemcb.c.
References Dbg, DebugTrace, FALSE, SectorsWithinRun, StartingLbn, StartingVbn, TRUE, and UNUSED_LBN.
Referenced by FsRtlGetNextLargeMcbEntry().
BOOLEAN FsRtlGetNextLargeMcbEntry (__in PLARGE_MCB Mcb, __in ULONG RunIndex, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PLONGLONG LargeSectorCount)
Definition at line 2757 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlGetNextBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlGetNextMcbEntry().
BOOLEAN FsRtlGetNextMcbEntry (__in PMCB Mcb, __in ULONG RunIndex, __out PVBN Vbn, __out PLBN Lbn, __out PULONG SectorCount)
Definition at line 448 of file largemcb.c.
References FsRtlGetNextLargeMcbEntry(), and PAGED_CODE.
VOID FsRtlInitializeBaseMcb (__in PBASE_MCB Mcb, __in POOL_TYPE PoolType)
Definition at line 532 of file largemcb.c.
References Dbg, DebugTrace, FsRtlAllocateFirstMapping, FsRtlpAllocatePool, INITIAL_MAXIMUM_PAIR_COUNT, and PagedPool.
Referenced by FsRtlInitializeLargeMcb().
VOID FsRtlInitializeLargeMcb (__in PLARGE_MCB Mcb, __in POOL_TYPE PoolType)
Definition at line 594 of file largemcb.c.
References Dbg, DebugTrace, FsRtlAllocateFastMutex, FsRtlFreeFastMutex, FsRtlInitializeBaseMcb(), KeInitializeGuardedMutex(), and NULL.
Referenced by FsRtlInitializeMcb().
VOID FsRtlInitializeLargeMcbs (VOID)
Definition at line 481 of file largemcb.c.
References ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), FsRtlFastMutexLookasideList, FsRtlFirstMappingLookasideList, INITIAL_MAXIMUM_PAIR_COUNT, NULL, and POOL_RAISE_IF_ALLOCATION_FAILURE.
Referenced by FsRtlInitSystem().
VOID FsRtlInitializeMcb (__in PMCB Mcb, __in POOL_TYPE PoolType)
Definition at line 305 of file largemcb.c.
References FsRtlInitializeLargeMcb(), and PAGED_CODE.
BOOLEAN FsRtlLookupBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn, __out_opt PLONGLONG LargeLbn, __out_opt PLONGLONG LargeSectorCount, __out_opt PLONGLONG LargeStartingLbn, __out_opt PLONGLONG LargeCountFromStartingLbn, __out_opt PULONG Index)
Definition at line 2169 of file largemcb.c.
References ARGUMENT_PRESENT, ASSERTMSG, Dbg, DebugTrace, EndingVbn, FALSE, FsRtlFindLargeIndex(), NOTHING, StartingLbn, StartingVbn, TRUE, try_return, and UNUSED_LBN.
Referenced by FsRtlLookupLargeMcbEntry().
BOOLEAN FsRtlLookupLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __out_opt PLONGLONG LargeLbn, __out_opt PLONGLONG LargeSectorCount, __out_opt PLONGLONG LargeStartingLbn, __out_opt PLONGLONG LargeCountFromStartingLbn, __out_opt PULONG Index)
Definition at line 2304 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlLookupBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlLookupMcbEntry().
BOOLEAN FsRtlLookupLastBaseMcbEntry (__in PBASE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn)
Definition at line 2369 of file largemcb.c.
References Dbg, DebugTrace, EndingLbn, EndingVbn, FALSE, _NONOPAQUE_BASE_MCB::PairCount, and TRUE.
Referenced by FsRtlLookupLastLargeMcbEntry().
BOOLEAN FsRtlLookupLastBaseMcbEntryAndIndex (__in PBASE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
Definition at line 2483 of file largemcb.c.
References Dbg, DebugTrace, EndingLbn, EndingVbn, FALSE, PAGED_CODE, _NONOPAQUE_BASE_MCB::PairCount, TRUE, and UNUSED_LBN.
Referenced by FsRtlLookupLastLargeMcbEntryAndIndex().
BOOLEAN FsRtlLookupLastLargeMcbEntry (__in PLARGE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn)
Definition at line 2430 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlLookupLastBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlLookupLastMcbEntry().
BOOLEAN FsRtlLookupLastLargeMcbEntryAndIndex (__in PLARGE_MCB Mcb, __out PLONGLONG LargeVbn, __out PLONGLONG LargeLbn, __out PULONG Index)
Definition at line 2551 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlLookupLastBaseMcbEntryAndIndex(), KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), and PAGED_CODE.
BOOLEAN FsRtlLookupLastMcbEntry (__in PMCB Mcb, __out PVBN Vbn, __out PLBN Lbn)
Definition at line 411 of file largemcb.c.
References FsRtlLookupLastLargeMcbEntry(), and PAGED_CODE.
BOOLEAN FsRtlLookupMcbEntry (__in PMCB Mcb, __in VBN Vbn, __out PLBN Lbn, __out_opt PULONG SectorCount, __out PULONG Index)
Definition at line 379 of file largemcb.c.
References ARGUMENT_PRESENT, FsRtlLookupLargeMcbEntry(), and NULL.
ULONG FsRtlNumberOfRunsInBaseMcb (__in PBASE_MCB Mcb)
Definition at line 2609 of file largemcb.c.
Referenced by FsRtlNumberOfRunsInLargeMcb().
ULONG FsRtlNumberOfRunsInLargeMcb (__in PLARGE_MCB Mcb)
Definition at line 2640 of file largemcb.c.
References Count, Dbg, DebugTrace, FsRtlNumberOfRunsInBaseMcb(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlNumberOfRunsInMcb().
ULONG FsRtlNumberOfRunsInMcb (__in PMCB Mcb)
Definition at line 437 of file largemcb.c.
References FsRtlNumberOfRunsInLargeMcb(), and PAGED_CODE.
VOID FsRtlRemoveBaseMcbEntry (__in PBASE_MCB Mcb, __in LONGLONG Vbn, __in LONGLONG SectorCount)
Definition at line 1655 of file largemcb.c.
References Dbg, DebugTrace, EndingVbn, FsRtlAddLargeEntry(), FsRtlFindLargeIndex(), FsRtlRemoveLargeEntry(), Index, _NONOPAQUE_BASE_MCB::Mapping, NextStartingLbn, _MAPPING::NextVbn, NOTHING, PreviousEndingLbn, SectorsWithinRun, StartingLbn, StartingVbn, and UNUSED_LBN.
Referenced by FsRtlRemoveLargeMcbEntry().
VOID FsRtlRemoveLargeEntry (IN PBASE_MCB Mcb, IN ULONG WhereToRemoveIndex, IN ULONG AmountToRemove)
Definition at line 3361 of file largemcb.c.
References _NONOPAQUE_BASE_MCB::Mapping, _NONOPAQUE_BASE_MCB::PairCount, and RtlMoveMemory.
Referenced by FsRtlAddBaseMcbEntry(), and FsRtlRemoveBaseMcbEntry().
VOID FsRtlRemoveLargeMcbEntry (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeSectorCount)
Definition at line 2101 of file largemcb.c.
References ASSERTMSG, Dbg, DebugTrace, FsRtlRemoveBaseMcbEntry(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlRemoveMcbEntry().
VOID FsRtlRemoveMcbEntry (__in PMCB OpaqueMcb, __in VBN Vbn, __in ULONG SectorCount)
Definition at line 363 of file largemcb.c.
References FsRtlRemoveLargeMcbEntry(), and PAGED_CODE.
NTKERNELAPI VOID FsRtlResetBaseMcb (__in PBASE_MCB Mcb)
Definition at line 962 of file largemcb.c.
NTKERNELAPI VOID FsRtlResetLargeMcb (__in PLARGE_MCB Mcb, __in BOOLEAN SelfSynchronized)
Definition at line 992 of file largemcb.c.
References KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
BOOLEAN FsRtlSplitBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeAmount)
Definition at line 2820 of file largemcb.c.
References ASSERTMSG, Dbg, DebugTrace, FALSE, FsRtlAddLargeEntry(), FsRtlFindLargeIndex(), Index, _NONOPAQUE_BASE_MCB::Mapping, NOTHING, PAGED_CODE, _NONOPAQUE_BASE_MCB::PairCount, PreviousEndingLbn, StartingLbn, StartingVbn, TRUE, try_return, and UNUSED_LBN.
Referenced by FsRtlSplitLargeMcb().
BOOLEAN FsRtlSplitLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn, __in LONGLONG LargeAmount)
Definition at line 3037 of file largemcb.c.
References Dbg, DebugTrace, FALSE, FsRtlSplitBaseMcb(), KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), and PAGED_CODE.
VOID FsRtlTruncateBaseMcb (__in PBASE_MCB Mcb, __in LONGLONG LargeVbn)
Definition at line 750 of file largemcb.c.
References ASSERTMSG, Dbg, DebugTrace, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FsRtlAllocateFirstMapping, FsRtlFindLargeIndex(), FsRtlpAllocatePool, Index, INITIAL_MAXIMUM_PAIR_COUNT, _NONOPAQUE_BASE_MCB::Mapping, _NONOPAQUE_BASE_MCB::MaximumPairCount, NextStartingVbn, NULL, PagedPool, _NONOPAQUE_BASE_MCB::PairCount, _NONOPAQUE_BASE_MCB::PoolType, RtlCopyMemory, StartingLbn, and UNUSED_LBN.
Referenced by FsRtlTruncateLargeMcb().
VOID FsRtlTruncateLargeMcb (__in PLARGE_MCB Mcb, __in LONGLONG LargeVbn)
Definition at line 917 of file largemcb.c.
References Dbg, DebugTrace, FsRtlTruncateBaseMcb(), KeAcquireGuardedMutex(), and KeReleaseGuardedMutex().
Referenced by FsRtlTruncateMcb().
VOID FsRtlTruncateMcb (__in PMCB Mcb, __in VBN Vbn)
Definition at line 332 of file largemcb.c.
References FsRtlTruncateLargeMcb(), and PAGED_CODE.
VOID FsRtlUninitializeBaseMcb (__in PBASE_MCB Mcb)
Definition at line 663 of file largemcb.c.
References Dbg, DebugTrace, ExFreePool(), FsRtlFreeFirstMapping, INITIAL_MAXIMUM_PAIR_COUNT, and PagedPool.
Referenced by FsRtlUninitializeLargeMcb().
VOID FsRtlUninitializeLargeMcb (__in PLARGE_MCB Mcb)
Definition at line 705 of file largemcb.c.
References Dbg, DebugTrace, FsRtlFreeFastMutex, FsRtlUninitializeBaseMcb(), and NULL.
Referenced by FsRtlUninitializeMcb().
VOID FsRtlUninitializeMcb (__in PMCB Mcb)
Definition at line 319 of file largemcb.c.
References FsRtlUninitializeLargeMcb(), and PAGED_CODE.
Variable Documentation
NPAGED_LOOKASIDE_LIST FsRtlFastMutexLookasideList
Definition at line 293 of file largemcb.c.
Referenced by FsRtlInitializeLargeMcbs().
PAGED_LOOKASIDE_LIST FsRtlFirstMappingLookasideList
Definition at line 286 of file largemcb.c.
Referenced by FsRtlInitializeLargeMcbs().