Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ob.h File Reference
ob.h File Reference
Data Structures
struct _DEVICE_MAP
struct _OBJECT_CREATE_INFORMATION
struct _OBJECT_DIRECTORY
struct _OBJECT_DIRECTORY_ENTRY
struct _OBJECT_DUMP_CONTROL
struct _OBJECT_HANDLE_COUNT_DATABASE
struct _OBJECT_HANDLE_COUNT_ENTRY
struct _OBJECT_HANDLE_INFORMATION
struct _OBJECT_HEADER
struct _OBJECT_HEADER_CREATOR_INFO
struct _OBJECT_HEADER_HANDLE_INFO
struct _OBJECT_HEADER_NAME_INFO
struct _OBJECT_HEADER_QUOTA_INFO
struct _OBJECT_SYMBOLIC_LINK
struct _OBJECT_TYPE
struct _OBJECT_TYPE_INITIALIZER
struct _WIN32_CLOSEMETHOD_PARAMETERS
struct _WIN32_DELETEMETHOD_PARAMETERS
struct _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS
struct _WIN32_OPENMETHOD_PARAMETERS
struct _WIN32_PARSEMETHOD_PARAMETERS
Macros
#define NUMBER_HASH_BUCKETS 37
#define OB_FLAG_CREATOR_INFO 0x04
#define OB_FLAG_DEFAULT_SECURITY_QUOTA 0x20
#define OB_FLAG_DELETED_INLINE 0x80
#define OB_FLAG_EXCLUSIVE_OBJECT 0x08
#define OB_FLAG_KERNEL_OBJECT 0x02
#define OB_FLAG_NEW_OBJECT 0x01
#define OB_FLAG_PERMANENT_OBJECT 0x10
#define OB_FLAG_SINGLE_HANDLE_ENTRY 0x40
#define ObCreateObject _ObCreateObject
#define ObDereferenceObject(a) ObfDereferenceObject(a)
#define OBJ_ALL_VALID_ATTRIBUTES (OBJ_VALID_PRIVATE_ATTRIBUTES | OBJ_VALID_ATTRIBUTES)
#define OBJ_INVALID_SESSION_ID 0xFFFFFFFF
#define OBJ_KERNEL_EXCLUSIVE 0x00010000L
#define OBJ_PROTECT_CLOSE 0x00000001L
#define OBJ_VALID_PRIVATE_ATTRIBUTES 0x00010000L
#define OBJECT_HEADER_TO_EXCLUSIVE_PROCESS(oh)
#define OBJECT_LOCK_COUNT 4
#define OBJECT_TO_OBJECT_HEADER(o) CONTAINING_RECORD((o), OBJECT_HEADER, Body)
#define ObReferenceObject(Object) ObfReferenceObject(Object)
#define ObReferenceObjectByHandle _ObReferenceObjectByHandle
Typedefs
typedef struct _DEVICE_MAP DEVICE_MAP
typedef VOID(* OB_CLOSE_METHOD) (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
typedef VOID(* OB_DELETE_METHOD) (IN PVOID Object)
typedef struct _OBJECT_DUMP_CONTROL OB_DUMP_CONTROL
typedef VOID(* OB_DUMP_METHOD) (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
typedef BOOLEAN(* OB_OKAYTOCLOSE_METHOD) (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
typedef NTSTATUS(* OB_OPEN_METHOD) (IN OB_OPEN_REASON OpenReason, IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG HandleCount)
typedef enum _OB_OPEN_REASON OB_OPEN_REASON
typedef NTSTATUS(* OB_PARSE_METHOD) (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
typedef NTSTATUS(* OB_QUERYNAME_METHOD) (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
typedef NTSTATUS(* OB_SECURITY_METHOD) (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
typedef struct _OBJECT_CREATE_INFORMATION OBJECT_CREATE_INFORMATION
typedef struct _OBJECT_DIRECTORY OBJECT_DIRECTORY
typedef struct _OBJECT_DIRECTORY_ENTRY OBJECT_DIRECTORY_ENTRY
typedef struct _OBJECT_HANDLE_COUNT_DATABASE OBJECT_HANDLE_COUNT_DATABASE
typedef struct _OBJECT_HANDLE_COUNT_ENTRY OBJECT_HANDLE_COUNT_ENTRY
typedef struct _OBJECT_HANDLE_INFORMATION OBJECT_HANDLE_INFORMATION
typedef struct _OBJECT_HEADER OBJECT_HEADER
typedef struct _OBJECT_HEADER_CREATOR_INFO OBJECT_HEADER_CREATOR_INFO
typedef struct _OBJECT_HEADER_HANDLE_INFO OBJECT_HEADER_HANDLE_INFO
typedef struct _OBJECT_HEADER_NAME_INFO OBJECT_HEADER_NAME_INFO
typedef struct _OBJECT_HEADER_QUOTA_INFO OBJECT_HEADER_QUOTA_INFO
typedef struct _OBJECT_SYMBOLIC_LINK OBJECT_SYMBOLIC_LINK
typedef struct _OBJECT_TYPE OBJECT_TYPE
typedef struct _OBJECT_TYPE_INITIALIZER OBJECT_TYPE_INITIALIZER
typedef struct _DEVICE_MAP * PDEVICE_MAP
typedef NTSTATUS(* PKWIN32_CLOSEMETHOD_CALLOUT) (PKWIN32_CLOSEMETHOD_PARAMETERS)
typedef struct _WIN32_CLOSEMETHOD_PARAMETERS * PKWIN32_CLOSEMETHOD_PARAMETERS
typedef NTSTATUS(* PKWIN32_DELETEMETHOD_CALLOUT) (PKWIN32_DELETEMETHOD_PARAMETERS)
typedef struct _WIN32_DELETEMETHOD_PARAMETERS * PKWIN32_DELETEMETHOD_PARAMETERS
typedef struct _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS * PKWIN32_OKAYTOCLOSEMETHOD_PARAMETERS
typedef NTSTATUS(* PKWIN32_OKTOCLOSEMETHOD_CALLOUT) (PKWIN32_OKAYTOCLOSEMETHOD_PARAMETERS)
typedef NTSTATUS(* PKWIN32_OPENMETHOD_CALLOUT) (PKWIN32_OPENMETHOD_PARAMETERS)
typedef struct _WIN32_OPENMETHOD_PARAMETERS * PKWIN32_OPENMETHOD_PARAMETERS
typedef NTSTATUS(* PKWIN32_PARSEMETHOD_CALLOUT) (PKWIN32_PARSEMETHOD_PARAMETERS)
typedef struct _WIN32_PARSEMETHOD_PARAMETERS * PKWIN32_PARSEMETHOD_PARAMETERS
typedef struct _OBJECT_DUMP_CONTROL * POB_DUMP_CONTROL
typedef struct _OBJECT_CREATE_INFORMATION * POBJECT_CREATE_INFORMATION
typedef struct _OBJECT_DIRECTORY * POBJECT_DIRECTORY
typedef struct _OBJECT_DIRECTORY_ENTRY * POBJECT_DIRECTORY_ENTRY
typedef struct _OBJECT_HANDLE_COUNT_DATABASE * POBJECT_HANDLE_COUNT_DATABASE
typedef struct _OBJECT_HANDLE_COUNT_ENTRY * POBJECT_HANDLE_COUNT_ENTRY
typedef struct _OBJECT_HANDLE_INFORMATION * POBJECT_HANDLE_INFORMATION
typedef struct _OBJECT_HEADER * POBJECT_HEADER
typedef struct _OBJECT_HEADER_CREATOR_INFO * POBJECT_HEADER_CREATOR_INFO
typedef struct _OBJECT_HEADER_HANDLE_INFO * POBJECT_HEADER_HANDLE_INFO
typedef struct _OBJECT_HEADER_NAME_INFO * POBJECT_HEADER_NAME_INFO
typedef struct _OBJECT_HEADER_QUOTA_INFO * POBJECT_HEADER_QUOTA_INFO
typedef struct _OBJECT_SYMBOLIC_LINK * POBJECT_SYMBOLIC_LINK
typedef struct _OBJECT_TYPE * POBJECT_TYPE
typedef struct _OBJECT_TYPE_INITIALIZER * POBJECT_TYPE_INITIALIZER
typedef struct _WIN32_CLOSEMETHOD_PARAMETERS WIN32_CLOSEMETHOD_PARAMETERS
typedef struct _WIN32_DELETEMETHOD_PARAMETERS WIN32_DELETEMETHOD_PARAMETERS
typedef struct _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS WIN32_OKAYTOCLOSEMETHOD_PARAMETERS
typedef struct _WIN32_OPENMETHOD_PARAMETERS WIN32_OPENMETHOD_PARAMETERS
typedef struct _WIN32_PARSEMETHOD_PARAMETERS WIN32_PARSEMETHOD_PARAMETERS
Enumerations
enum _OB_OPEN_REASON {
ObCreateHandle, ObOpenHandle, ObDuplicateHandle, ObInheritHandle,
ObMaxOpenReason
}
Functions
FORCEINLINE NTSTATUS _ObCreateObject (__in KPROCESSOR_MODE ProbeMode, __in POBJECT_TYPE ObjectType, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE OwnershipMode, __inout_opt PVOID ParseContext, __in ULONG ObjectBodySize, __in ULONG PagedPoolCharge, __in ULONG NonPagedPoolCharge, __out PVOID *pObject)
FORCEINLINE NTSTATUS _ObReferenceObjectByHandle (__in HANDLE Handle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PVOID *pObject, __out_opt POBJECT_HANDLE_INFORMATION pHandleInformation)
NTSTATUS ObAssignObjectSecurityDescriptor (IN PVOID Object, IN PSECURITY_DESCRIPTOR SecurityDescriptor OPTIONAL, IN POOL_TYPE PoolType)
NTKERNELAPI NTSTATUS ObAssignSecurity (__in PACCESS_STATE AccessState, __in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in PVOID Object, __in POBJECT_TYPE ObjectType)
NTKERNELAPI BOOLEAN ObCheckCreateObjectAccess (__in PVOID DirectoryObject, __in ACCESS_MASK CreateAccess, __in PACCESS_STATE AccessState, __in PUNICODE_STRING ComponentName, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE PreviousMode, __out PNTSTATUS AccessStatus)
NTKERNELAPI BOOLEAN ObCheckObjectAccess (__in PVOID Object, __inout PACCESS_STATE AccessState, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE AccessMode, __out PNTSTATUS AccessStatus)
VOID ObClearProcessHandleTable (PEPROCESS Process)
NTKERNELAPI NTSTATUS ObCloseHandle (__in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
NTKERNELAPI NTSTATUS ObCreateObject (__in KPROCESSOR_MODE ProbeMode, __in POBJECT_TYPE ObjectType, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE OwnershipMode, __inout_opt PVOID ParseContext, __in ULONG ObjectBodySize, __in ULONG PagedPoolCharge, __in ULONG NonPagedPoolCharge, __out PVOID *Object)
NTKERNELAPI NTSTATUS ObCreateObjectType (__in PUNICODE_STRING TypeName, __in POBJECT_TYPE_INITIALIZER ObjectTypeInitializer, __in_opt PSECURITY_DESCRIPTOR SecurityDescriptor, __out POBJECT_TYPE *ObjectType)
NTKERNELAPI VOID ObDeleteCapturedInsertInfo (__in PVOID Object)
VOID ObDereferenceDeviceMap (IN PEPROCESS Process)
VOID ObDereferenceObjectDeferDelete (IN PVOID Object)
LONG_PTR FASTCALL ObDereferenceObjectEx (IN PVOID Object, IN ULONG Count)
VOID ObDereferenceProcessHandleTable (PEPROCESS SourceProcess)
NTKERNELAPI VOID ObDereferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
NTSTATUS ObDumpObjectByHandle (IN HANDLE Handle, IN POB_DUMP_CONTROL Control OPTIONAL)
NTSTATUS ObDumpObjectByPointer (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
NTSTATUS ObDuplicateObject (IN PEPROCESS SourceProcess, IN HANDLE SourceHandle, IN PEPROCESS TargetProcess OPTIONAL, OUT PHANDLE TargetHandle OPTIONAL, IN ACCESS_MASK DesiredAccess, IN ULONG HandleAttributes, IN ULONG Options, IN KPROCESSOR_MODE PreviousMode)
NTKERNELAPI LONG_PTR FASTCALL ObfDereferenceObject (__in PVOID Object)
NTKERNELAPI BOOLEAN ObFindHandleForObject (__in PEPROCESS Process, __in PVOID Object, __in_opt POBJECT_TYPE ObjectType, __in_opt POBJECT_HANDLE_INFORMATION MatchCriteria, __out PHANDLE Handle)
VOID FASTCALL ObFreeObjectCreateInfoBuffer (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo)
NTKERNELAPI LONG_PTR FASTCALL ObfReferenceObject (__in PVOID Object)
NTKERNELAPI NTSTATUS ObGetObjectSecurity (__in PVOID Object, __out PSECURITY_DESCRIPTOR *SecurityDescriptor, __out PBOOLEAN MemoryAllocated)
ULONG ObGetProcessHandleCount (PEPROCESS Process)
ULONG ObGetSecurityMode ()
VOID ObInheritDeviceMap (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess)
NTSTATUS ObInitProcess (PEPROCESS ParentProcess OPTIONAL, PEPROCESS NewProcess)
VOID ObInitProcess2 (PEPROCESS NewProcess)
BOOLEAN ObInitSystem (VOID)
NTKERNELAPI NTSTATUS ObInsertObject (__in PVOID Object, __in_opt PACCESS_STATE PassedAccessState, __in_opt ACCESS_MASK DesiredAccess, __in ULONG ObjectPointerBias, __out_opt PVOID *NewObject, __out_opt PHANDLE Handle)
ULONG ObIsLUIDDeviceMapsEnabled ()
BOOLEAN ObIsObjectDeletionInline (IN PVOID Object)
FORCEINLINE POBJECT_HEADER_CREATOR_INFO OBJECT_HEADER_TO_CREATOR_INFO (IN POBJECT_HEADER ObjectHeader)
FORCEINLINE POBJECT_HEADER_HANDLE_INFO OBJECT_HEADER_TO_HANDLE_INFO (IN POBJECT_HEADER ObjectHeader)
FORCEINLINE POBJECT_HEADER_HANDLE_INFO OBJECT_HEADER_TO_HANDLE_INFO_EXISTS (IN POBJECT_HEADER ObjectHeader)
FORCEINLINE POBJECT_HEADER_NAME_INFO OBJECT_HEADER_TO_NAME_INFO (IN POBJECT_HEADER ObjectHeader)
FORCEINLINE POBJECT_HEADER_NAME_INFO OBJECT_HEADER_TO_NAME_INFO_EXISTS (IN POBJECT_HEADER ObjectHeader)
FORCEINLINE POBJECT_HEADER_QUOTA_INFO OBJECT_HEADER_TO_QUOTA_INFO (IN POBJECT_HEADER ObjectHeader)
FORCEINLINE POBJECT_HEADER_QUOTA_INFO OBJECT_HEADER_TO_QUOTA_INFO_EXISTS (IN POBJECT_HEADER ObjectHeader)
VOID ObKillProcess (PEPROCESS Process)
NTKERNELAPI NTSTATUS ObLogSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __out PSECURITY_DESCRIPTOR *OutputSecurityDescriptor, __in ULONG RefBias)
NTKERNELAPI VOID ObMakeTemporaryObject (__in PVOID Object)
NTKERNELAPI NTSTATUS ObOpenObjectByName (__in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __inout_opt PVOID ParseContext, __out PHANDLE Handle)
NTKERNELAPI NTSTATUS ObOpenObjectByPointer (__in PVOID Object, __in ULONG HandleAttributes, __in_opt PACCESS_STATE PassedAccessState, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PHANDLE Handle)
NTSTATUS ObQueryDeviceMapInformation (IN PEPROCESS TargetProcess, OUT PPROCESS_DEVICEMAP_INFORMATION DeviceMapInformation, IN ULONG Flags)
NTKERNELAPI NTSTATUS ObQueryNameString (__in PVOID Object, __out_bcount(Length) POBJECT_NAME_INFORMATION ObjectNameInfo, __in ULONG Length, __out PULONG ReturnLength)
NTKERNELAPI NTSTATUS ObQueryObjectAuditingByHandle (__in HANDLE Handle, __out PBOOLEAN GenerateOnClose)
NTSTATUS ObQueryTypeInfo (IN POBJECT_TYPE ObjectType, OUT POBJECT_TYPE_INFORMATION ObjectTypeInfo, IN ULONG Length, OUT PULONG ReturnLength)
NTSTATUS ObQueryTypeName (IN PVOID Object, PUNICODE_STRING ObjectTypeName, IN ULONG Length, OUT PULONG ReturnLength)
NTKERNELAPI NTSTATUS ObReferenceFileObjectForWrite (IN HANDLE Handle, IN KPROCESSOR_MODE AccessMode, OUT PVOID *FileObject, OUT POBJECT_HANDLE_INFORMATION HandleInformation)
NTKERNELAPI NTSTATUS ObReferenceObjectByHandle (__in HANDLE Handle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PVOID *Object, __out_opt POBJECT_HANDLE_INFORMATION HandleInformation)
NTKERNELAPI NTSTATUS ObReferenceObjectByName (__in PUNICODE_STRING ObjectName, __in ULONG Attributes, __in_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __in POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PVOID ParseContext, __out PVOID *Object)
NTKERNELAPI NTSTATUS ObReferenceObjectByPointer (__in PVOID Object, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode)
NTKERNELAPI LONG_PTR FASTCALL ObReferenceObjectEx (IN PVOID Object, IN ULONG Count)
NTKERNELAPI BOOLEAN FASTCALL ObReferenceObjectSafe (IN PVOID Object)
PHANDLE_TABLE ObReferenceProcessHandleTable (PEPROCESS SourceProcess)
VOID ObReferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
NTKERNELAPI VOID ObReleaseObjectSecurity (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in BOOLEAN MemoryAllocated)
FORCEINLINE ULONG ObSanitizeHandleAttributes (IN ULONG HandleAttributes, IN KPROCESSOR_MODE Mode)
NTSTATUS ObSetDeviceMap (IN PEPROCESS TargetProcess, IN HANDLE DirectoryHandle)
NTSTATUS ObSetDirectoryDeviceMap (OUT PDEVICE_MAP *ppDeviceMap OPTIONAL, IN HANDLE DirectoryHandle)
NTKERNELAPI NTSTATUS ObSetHandleAttributes (__in HANDLE Handle, __in POBJECT_HANDLE_FLAG_INFORMATION HandleFlags, __in KPROCESSOR_MODE PreviousMode)
NTKERNELAPI NTSTATUS ObSetSecurityObjectByPointer (__in PVOID Object, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
VOID ObShutdownSystem (IN ULONG Phase)
NTKERNELAPI NTSTATUS ObSwapObjectNames (IN HANDLE DirectoryHandle, IN HANDLE Handle1, IN HANDLE Handle2, IN ULONG Flags)
NTSTATUS ObValidateSecurityQuota (IN PVOID Object, IN ULONG NewSize)
NTSTATUS ObWaitForSingleObject (IN HANDLE Handle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL)
Variables
PKWIN32_CLOSEMETHOD_CALLOUT ExDesktopCloseProcedureCallout
PKWIN32_DELETEMETHOD_CALLOUT ExDesktopDeleteProcedureCallout
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExDesktopOkToCloseProcedureCallout
PKWIN32_OPENMETHOD_CALLOUT ExDesktopOpenProcedureCallout
PKWIN32_CLOSEMETHOD_CALLOUT ExWindowStationCloseProcedureCallout
PKWIN32_DELETEMETHOD_CALLOUT ExWindowStationDeleteProcedureCallout
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExWindowStationOkToCloseProcedureCallout
PKWIN32_OPENMETHOD_CALLOUT ExWindowStationOpenProcedureCallout
PKWIN32_PARSEMETHOD_CALLOUT ExWindowStationParseProcedureCallout
PDEVICE_MAP ObSystemDeviceMap
Macro Definition Documentation
#define NUMBER_HASH_BUCKETS 37
Definition at line 323 of file ob.h.
Referenced by NtQueryDirectoryObject(), ObpLookupDirectoryEntry(), and ObShutdownSystem().
#define OB_FLAG_CREATOR_INFO 0x04
Definition at line 482 of file ob.h.
Referenced by OBJECT_HEADER_TO_CREATOR_INFO(), and ObpAllocateObject().
#define OB_FLAG_DEFAULT_SECURITY_QUOTA 0x20
Definition at line 485 of file ob.h.
Referenced by ObpChargeQuotaForObject(), ObpFreeObject(), and ObValidateSecurityQuota().
#define OB_FLAG_DELETED_INLINE 0x80
Definition at line 487 of file ob.h.
Referenced by ObIsObjectDeletionInline(), and ObpRemoveObjectRoutine().
#define OB_FLAG_EXCLUSIVE_OBJECT 0x08
Definition at line 483 of file ob.h.
Referenced by NtQueryObject(), ObpAllocateObject(), ObpDecrementHandleCount(), ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
#define OB_FLAG_KERNEL_OBJECT 0x02
Definition at line 481 of file ob.h.
Referenced by ObCreateObjectType(), ObInsertObject(), and ObpAllocateObject().
#define OB_FLAG_NEW_OBJECT 0x01
Definition at line 480 of file ob.h.
Referenced by ObDeleteCapturedInsertInfo(), ObInsertObject(), ObOpenObjectByName(), ObpAllocateObject(), ObpChargeQuotaForObject(), and ObpFreeObject().
#define OB_FLAG_PERMANENT_OBJECT 0x10
Definition at line 484 of file ob.h.
Referenced by NtMakePermanentObject(), NtQueryObject(), ObCreateObject(), ObCreateObjectType(), ObMakeTemporaryObject(), ObpAllocateObject(), ObpDeleteNameCheck(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObShutdownSystem(), and ObSwapObjectNames().
#define OB_FLAG_SINGLE_HANDLE_ENTRY 0x40
Definition at line 486 of file ob.h.
Referenced by ObpAllocateObject(), ObpDecrementHandleCount(), ObpFreeObject(), ObpIncrementHandleDataBase(), and ObpInsertHandleCount().
#define ObCreateObject _ObCreateObject
Definition at line 731 of file ob.h.
Referenced by _ObCreateObject(), CmpCreateRegistryRoot(), CmpDoCreateChild(), CmpDoOpen(), ExCreateCallback(), IoCreateController(), IoCreateDevice(), IoCreateDriver(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopInitializeAttributesAndCreateObject(), IopLoadDriver(), IopParseDevice(), LpcpCreatePort(), MiSectionInitialization(), MmCreateSection(), NtAcceptConnectPort(), NtCreateDebugObject(), NtCreateDirectoryObject(), NtCreateEvent(), NtCreateEventPair(), NtCreateIoCompletion(), NtCreateJobObject(), NtCreateKeyedEvent(), NtCreateMutant(), NtCreateProfile(), NtCreateSemaphore(), NtCreateSymbolicLinkObject(), NtCreateTimer(), NtSecureConnectPort(), PspCreateProcess(), PspCreateThread(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), and WmipCreateGuidObject().
#define ObDereferenceObject (a) ObfDereferenceObject(a)
Definition at line 854 of file ob.h.
#define OBJ_ALL_VALID_ATTRIBUTES (OBJ_VALID_PRIVATE_ATTRIBUTES | OBJ_VALID_ATTRIBUTES)
Definition at line 654 of file ob.h.
Referenced by ObCreateObjectType(), ObpCaptureObjectCreateInformation(), and ObSanitizeHandleAttributes().
#define OBJ_INVALID_SESSION_ID 0xFFFFFFFF
Definition at line 324 of file ob.h.
Referenced by NtCreateDirectoryObject(), and ObpLookupObjectName().
#define OBJ_KERNEL_EXCLUSIVE 0x00010000L
Definition at line 650 of file ob.h.
Referenced by MiSectionInitialization(), ObpAllocateObject(), and ObSanitizeHandleAttributes().
#define OBJ_PROTECT_CLOSE 0x00000001L
Definition at line 617 of file ob.h.
Referenced by NtQueryObject(), and ObpCloseHandleTableEntry().
#define OBJ_VALID_PRIVATE_ATTRIBUTES 0x00010000L
Definition at line 652 of file ob.h.
#define OBJECT_HEADER_TO_EXCLUSIVE_PROCESS (oh)
Value:
((oh->Flags & OB_FLAG_EXCLUSIVE_OBJECT) == 0 ? \
    NULL : (((POBJECT_HEADER_QUOTA_INFO)((PCHAR)(oh) - (oh)->QuotaInfoOffset))->ExclusiveProcess))
Definition at line 494 of file ob.h.
Referenced by ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
#define OBJECT_LOCK_COUNT 4
Definition at line 300 of file ob.h.
Referenced by ObCreateObjectType(), ObpDeleteObjectType(), ObpLockAllObjects(), and ObpUnlockAllObjects().
#define OBJECT_TO_OBJECT_HEADER (o) CONTAINING_RECORD((o), OBJECT_HEADER, Body)
Definition at line 490 of file ob.h.
Referenced by ExpWin32CloseProcedure(), ExpWin32DeleteProcedure(), ExpWin32OkayToCloseProcedure(), ExpWin32OpenProcedure(), IoComputeDesiredAccessFileObject(), IoCreateStreamFileObjectLite(), NtMakePermanentObject(), NtQueryDirectoryObject(), NtQueryObject(), NtQuerySecurityObject(), NtQuerySymbolicLinkObject(), NtSignalAndWaitForSingleObject(), NtWaitForSingleObject(), ObAssignObjectSecurityDescriptor(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObDeleteCapturedInsertInfo(), ObDereferenceObjectDeferDelete(), ObDereferenceObjectEx(), ObDuplicateObject(), ObfDereferenceObject(), ObFindHandleForObject(), ObfReferenceObject(), ObGetObjectSecurity(), ObInsertObject(), ObIsObjectDeletionInline(), ObMakeTemporaryObject(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), ObpCreateHandle(), ObpCreateSymbolicLinkName(), ObpCreateUnnamedHandle(), ObpDeleteNameCheck(), ObpFreeObject(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpLookupDirectoryEntry(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), ObpQueryNameString(), ObpReferenceProcessObjectByHandle(), ObpReleaseLookupContext(), ObpReleaseLookupContextObject(), ObpRemoveObjectRoutine(), ObQuerySecurityDescriptorInfo(), ObQueryTypeName(), ObReferenceObjectByHandle(), ObReferenceObjectByPointer(), ObReferenceObjectEx(), ObReferenceObjectSafe(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObSetSecurityDescriptorInfo(), ObSetSecurityObjectByPointer(), ObShutdownSystem(), ObSwapObjectNames(), ObValidateSecurityQuota(), ObWaitForSingleObject(), and SeAddSaclToProcess().
#define ObReferenceObject (Object) ObfReferenceObject(Object)
Definition at line 857 of file ob.h.
Referenced by CcInitializeCacheMap(), CcScheduleReadAhead(), DbgkCopyProcessDebugPort(), DbgkOpenProcessDebugPort(), DbgkpPostFakeThreadMessages(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), ExpCheckQueueShutdown(), ExpRegisterFirmwareTableInformationHandler(), ExpShutdownWorker(), ExRegisterCallback(), ExTimerRundown(), FsRtlCreateSectionForDataScan(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateLock(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), IoCreateDevice(), IoEnumerateDeviceObjectList(), IoEnumerateRegisteredFiltersList(), IoGetAttachedDeviceReference(), IoGetDeviceAttachmentBaseRef(), IoGetDiskDeviceObject(), IoGetLowerDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateErrorLogEntry(), IopCloseFile(), IopGetDevicePDO(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopMarkBootPartition(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopSetDeviceSecurityDescriptors(), IopSetRemoteLink(), IopShutdownBaseFileSystems(), IopUnloadSafeCompletion(), IoQueueWorkItem(), IoRegisterFsRegistrationChange(), IoRegisterLastChanceShutdownNotification(), IoRegisterShutdownNotification(), IoSetInformation(), LpcpCreatePort(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiNoPagesLastChance(), MiWriteComplete(), MmCreateSection(), MmGetFileNameForAddress(), MmGetNextSession(), MmGetPreviousSession(), MmGetSessionById(), MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), NtAcceptConnectPort(), NtAssignProcessToJobObject(), NtOpenThreadTokenEx(), NtQueryInformationJobObject(), NtQueryVirtualMemory(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSetDefaultHardErrorPort(), NtWaitForDebugEvent(), ObCreateObjectType(), ObFastReferenceObjectLocked(), ObpLookupDirectoryEntry(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), PerfInfoAddToFileHash(), PsImpersonateClient(), PsLookupProcessThreadByCid(), PsMapSystemDll(), PsOpenTokenOfJobObject(), PspApplyJobLimitsToProcessSet(), PspCreateProcess(), PspCreateThread(), PspGetJobFromSet(), PspWaitForUsermodeExit(), PsReferenceEffectiveToken(), PsReferenceImpersonationToken(), PsReferenceProcessFilePointer(), PsShutdownSystem(), PsWaitForAllProcesses(), RawInitialize(), SeAssignPrimaryToken(), SeCreateClientSecurityFromSubjectContext(), SeExchangePrimaryToken(), SepRmCommandServerThreadInit(), WmiGetClock(), and WmipTranslatePDOInstanceNames().
#define ObReferenceObjectByHandle _ObReferenceObjectByHandle
Definition at line 783 of file ob.h.
Referenced by _ObReferenceObjectByHandle(), BuildQueryDirectoryIrp(), CmGetSystemDriverList(), CmpAcquireFileObjectForFile(), CmpCloneControlSet(), CmpCreateEvent(), CmpCreateRegistryRoot(), CmpIsHiveAlreadyLoaded(), CmpLinkHiveToMaster(), CmpSaveBootControlSet(), CmShutdownSystem(), ExCreateCallback(), ExpCreateWorkerThread(), ExpWorkerInitialization(), IoAttachDevice(), IoCreateDriver(), IoCreateNotificationEvent(), IoCreateSynchronizationEvent(), IoGetDeviceObjectPointer(), IoInitSystem(), IopConnectLinkTrackingPort(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopMarkBootPartition(), IopOpenLinkOrRenameTarget(), IopReferenceDriverObjectByName(), IopSetEaOrQuotaInformationFile(), IopTrackLink(), IopUnloadDriver(), IopXxxControlFile(), IoWMIOpenBlock(), MiCreateMemoryEvent(), MiSessionWideReserveImageAddress(), MmCheckSystemImage(), MmCreateSection(), MmLoadSystemImage(), MmSetBankedSection(), NtAcceptConnectPort(), NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtAlertResumeThread(), NtAlertThread(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtAssignProcessToJobObject(), NtCancelIoFile(), NtCancelTimer(), NtClearEvent(), NtCompactKeys(), NtCompareTokens(), NtCompressKey(), NtCreateJobSet(), NtCreateKey(), NtCreatePagingFile(), NtCreateProfile(), NtDebugActiveProcess(), NtDebugContinue(), NtDeleteKey(), NtDeleteValueKey(), NtDuplicateObject(), NtDuplicateToken(), NtEnumerateKey(), NtEnumerateValueKey(), NtExtendSection(), NtFilterToken(), NtFlushBuffersFile(), NtFlushInstructionCache(), NtFlushKey(), NtFlushVirtualMemory(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetContextThread(), NtGetNextProcess(), NtGetNextThread(), NtGetWriteWatch(), NtImpersonateAnonymousToken(), NtImpersonateThread(), NtIsProcessInJob(), NtLoadKeyEx(), NtLockFile(), NtLockRegistryKey(), NtLockVirtualMemory(), NtMakePermanentObject(), NtMakeTemporaryObject(), NtMapViewOfSection(), NtNotifyChangeDirectoryFile(), NtNotifyChangeMultipleKeys(), NtOpenKey(), NtOpenObjectAuditAlarm(), NtOpenThreadTokenEx(), NtPrivilegeCheck(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtProtectVirtualMemory(), NtPulseEvent(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryEvent(), NtQueryInformationFile(), NtQueryInformationJobObject(), NtQueryInformationPort(), NtQueryInformationProcess(), NtQueryInformationThread(), NtQueryInformationToken(), NtQueryIoCompletion(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryMutant(), NtQueryObject(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtQueryQuotaInformationFile(), NtQuerySection(), NtQuerySecurityObject(), NtQuerySemaphore(), NtQuerySymbolicLinkObject(), NtQueryTimer(), NtQueryValueKey(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtQueueApcThread(), NtReadFile(), NtReadFileScatter(), NtReadVirtualMemory(), NtRegisterThreadTerminatePort(), NtReleaseKeyedEvent(), NtReleaseMutant(), NtReleaseSemaphore(), NtRemoveIoCompletion(), NtRemoveProcessDebug(), NtRenameKey(), NtReplaceKey(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtResetEvent(), NtResetWriteWatch(), NtRestoreKey(), NtResumeProcess(), NtResumeThread(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSecureConnectPort(), NtSetContextThread(), NtSetDefaultHardErrorPort(), NtSetEaFile(), NtSetEvent(), NtSetEventBoostPriority(), NtSetHighEventPair(), NtSetHighWaitLowEventPair(), NtSetInformationDebugObject(), NtSetInformationFile(), NtSetInformationJobObject(), NtSetInformationKey(), NtSetInformationObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetInformationToken(), NtSetIoCompletion(), NtSetLowEventPair(), NtSetLowWaitHighEventPair(), NtSetSecurityObject(), NtSetSystemInformation(), NtSetTimer(), NtSetValueKey(), NtSetVolumeInformationFile(), NtSignalAndWaitForSingleObject(), NtStartProfile(), NtStopProfile(), NtSuspendProcess(), NtSuspendThread(), NtTerminateJobObject(), NtTerminateProcess(), NtTerminateThread(), NtUnloadKey2(), NtUnloadKeyEx(), NtUnlockFile(), NtUnlockVirtualMemory(), NtUnmapViewOfSection(), NtWaitForDebugEvent(), NtWaitForKeyedEvent(), NtWaitForSingleObject(), NtWaitHighEventPair(), NtWaitLowEventPair(), NtWriteFile(), NtWriteFileGather(), NtWriteVirtualMemory(), ObInitSystem(), ObpLookupObjectName(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObSwapObjectNames(), ObWaitForSingleObject(), Phase1InitializationDiscard(), PsAssignImpersonationToken(), PsLocateSystemDll(), PsOpenTokenOfJobObject(), PsOpenTokenOfProcess(), PsOpenTokenOfThread(), PspAssignPrimaryToken(), PspCreateProcess(), PspCreateThread(), PspInitPhase0(), PspQueryPooledQuotaLimits(), PspQueryQuotaLimits(), PspQueryWorkingSetWatch(), PspSetPrimaryToken(), PspSetQuotaLimits(), SeAccessCheckByType(), SeIsChildToken(), SeIsSiblingToken(), SepAccessCheckAndAuditAlarm(), SepOpenTokenOfThread(), WmipCreatePumpThread(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipQueryAllData(), WmipQueryGuidInfo(), WmipQuerySetExecuteSI(), WmipReceiveNotifications(), WmipStartLogger(), WmipTranslateFileHandle(), and WmiUpdateTrace().
Typedef Documentation
typedef struct _DEVICE_MAP DEVICE_MAP
typedef VOID(* OB_CLOSE_METHOD) (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 130 of file ob.h.
typedef VOID(* OB_DELETE_METHOD) (IN PVOID Object)
Definition at line 138 of file ob.h.
typedef struct _OBJECT_DUMP_CONTROL OB_DUMP_CONTROL
typedef VOID(* OB_DUMP_METHOD) (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
Definition at line 101 of file ob.h.
typedef BOOLEAN(* OB_OKAYTOCLOSE_METHOD) (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
Definition at line 123 of file ob.h.
typedef NTSTATUS(* OB_OPEN_METHOD) (IN OB_OPEN_REASON OpenReason, IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG HandleCount)
Definition at line 115 of file ob.h.
typedef enum _OB_OPEN_REASON OB_OPEN_REASON
typedef NTSTATUS(* OB_PARSE_METHOD) (IN PVOID ParseObject, IN PVOID ObjectType, IN OUT PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
Definition at line 142 of file ob.h.
typedef NTSTATUS(* OB_QUERYNAME_METHOD) (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 166 of file ob.h.
typedef NTSTATUS(* OB_SECURITY_METHOD) (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 155 of file ob.h.
typedef struct _OBJECT_CREATE_INFORMATION OBJECT_CREATE_INFORMATION
typedef struct _OBJECT_DIRECTORY OBJECT_DIRECTORY
typedef struct _OBJECT_DIRECTORY_ENTRY OBJECT_DIRECTORY_ENTRY
typedef struct _OBJECT_HANDLE_COUNT_DATABASE OBJECT_HANDLE_COUNT_DATABASE
typedef struct _OBJECT_HANDLE_COUNT_ENTRY OBJECT_HANDLE_COUNT_ENTRY
typedef struct _OBJECT_HANDLE_INFORMATION OBJECT_HANDLE_INFORMATION
typedef struct _OBJECT_HEADER OBJECT_HEADER
typedef struct _OBJECT_HEADER_CREATOR_INFO OBJECT_HEADER_CREATOR_INFO
typedef struct _OBJECT_HEADER_HANDLE_INFO OBJECT_HEADER_HANDLE_INFO
typedef struct _OBJECT_HEADER_NAME_INFO OBJECT_HEADER_NAME_INFO
typedef struct _OBJECT_HEADER_QUOTA_INFO OBJECT_HEADER_QUOTA_INFO
typedef struct _OBJECT_SYMBOLIC_LINK OBJECT_SYMBOLIC_LINK
typedef struct _OBJECT_TYPE OBJECT_TYPE
typedef struct _OBJECT_TYPE_INITIALIZER OBJECT_TYPE_INITIALIZER
typedef struct _DEVICE_MAP * PDEVICE_MAP
typedef NTSTATUS(* PKWIN32_CLOSEMETHOD_CALLOUT) (PKWIN32_CLOSEMETHOD_PARAMETERS)
Definition at line 239 of file ob.h.
typedef struct _WIN32_CLOSEMETHOD_PARAMETERS * PKWIN32_CLOSEMETHOD_PARAMETERS
typedef NTSTATUS(* PKWIN32_DELETEMETHOD_CALLOUT) (PKWIN32_DELETEMETHOD_PARAMETERS)
Definition at line 250 of file ob.h.
typedef struct _WIN32_DELETEMETHOD_PARAMETERS * PKWIN32_DELETEMETHOD_PARAMETERS
typedef struct _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS * PKWIN32_OKAYTOCLOSEMETHOD_PARAMETERS
typedef NTSTATUS(* PKWIN32_OKTOCLOSEMETHOD_CALLOUT) (PKWIN32_OKAYTOCLOSEMETHOD_PARAMETERS)
Definition at line 224 of file ob.h.
typedef NTSTATUS(* PKWIN32_OPENMETHOD_CALLOUT) (PKWIN32_OPENMETHOD_PARAMETERS)
Definition at line 209 of file ob.h.
typedef struct _WIN32_OPENMETHOD_PARAMETERS * PKWIN32_OPENMETHOD_PARAMETERS
typedef NTSTATUS(* PKWIN32_PARSEMETHOD_CALLOUT) (PKWIN32_PARSEMETHOD_PARAMETERS)
Definition at line 269 of file ob.h.
typedef struct _WIN32_PARSEMETHOD_PARAMETERS * PKWIN32_PARSEMETHOD_PARAMETERS
typedef struct _OBJECT_DUMP_CONTROL * POB_DUMP_CONTROL
typedef struct _OBJECT_CREATE_INFORMATION* POBJECT_CREATE_INFORMATION
Definition at line 417 of file ob.h.
typedef struct _OBJECT_DIRECTORY * POBJECT_DIRECTORY
typedef struct _OBJECT_DIRECTORY_ENTRY * POBJECT_DIRECTORY_ENTRY
typedef struct _OBJECT_HANDLE_COUNT_DATABASE * POBJECT_HANDLE_COUNT_DATABASE
typedef struct _OBJECT_HANDLE_COUNT_ENTRY * POBJECT_HANDLE_COUNT_ENTRY
typedef struct _OBJECT_HANDLE_INFORMATION * POBJECT_HANDLE_INFORMATION
typedef struct _OBJECT_HEADER * POBJECT_HEADER
typedef struct _OBJECT_HEADER_CREATOR_INFO * POBJECT_HEADER_CREATOR_INFO
typedef struct _OBJECT_HEADER_HANDLE_INFO * POBJECT_HEADER_HANDLE_INFO
typedef struct _OBJECT_HEADER_NAME_INFO * POBJECT_HEADER_NAME_INFO
typedef struct _OBJECT_HEADER_QUOTA_INFO * POBJECT_HEADER_QUOTA_INFO
typedef struct _OBJECT_SYMBOLIC_LINK * POBJECT_SYMBOLIC_LINK
typedef struct _OBJECT_TYPE * POBJECT_TYPE
typedef struct _OBJECT_TYPE_INITIALIZER * POBJECT_TYPE_INITIALIZER
typedef struct _WIN32_CLOSEMETHOD_PARAMETERS WIN32_CLOSEMETHOD_PARAMETERS
typedef struct _WIN32_DELETEMETHOD_PARAMETERS WIN32_DELETEMETHOD_PARAMETERS
typedef struct _WIN32_OKAYTOCLOSEMETHOD_PARAMETERS WIN32_OKAYTOCLOSEMETHOD_PARAMETERS
typedef struct _WIN32_OPENMETHOD_PARAMETERS WIN32_OPENMETHOD_PARAMETERS
typedef struct _WIN32_PARSEMETHOD_PARAMETERS WIN32_PARSEMETHOD_PARAMETERS
Enumeration Type Documentation
enum _OB_OPEN_REASON
Enumerator
ObCreateHandle
ObOpenHandle
ObDuplicateHandle
ObInheritHandle
ObMaxOpenReason
Definition at line 106 of file ob.h.
Function Documentation
FORCEINLINE NTSTATUS _ObCreateObject (__in KPROCESSOR_MODE ProbeMode, __in POBJECT_TYPE ObjectType, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE OwnershipMode, __inout_opt PVOID ParseContext, __in ULONG ObjectBodySize, __in ULONG PagedPoolCharge, __in ULONG NonPagedPoolCharge, __out PVOID * pObject)
Definition at line 703 of file ob.h.
References ObCreateObject, and Status.
FORCEINLINE NTSTATUS _ObReferenceObjectByHandle (__in HANDLE Handle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PVOID * pObject, __out_opt POBJECT_HANDLE_INFORMATION pHandleInformation)
Definition at line 761 of file ob.h.
References ObReferenceObjectByHandle, and Status.
NTSTATUS ObAssignObjectSecurityDescriptor (IN PVOID Object, IN PSECURITY_DESCRIPTOR SecurityDescriptor OPTIONAL, IN POOL_TYPE PoolType)
Definition at line 1041 of file obse.c.
References ARGUMENT_PRESENT, ASSERT, ExFastRefGetAdditionalReferenceCount(), ExFastRefInitialize(), ExFreePool(), NT_SUCCESS, NULL, OBJECT_TO_OBJECT_HEADER, ObLogSecurityDescriptor(), PAGED_CODE, _OBJECT_HEADER::SecurityDescriptor, Status, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by CmpAssignSecurityDescriptorWrapper(), SeDefaultObjectMethod(), and WmipSecurityMethod().
NTKERNELAPI NTSTATUS ObAssignSecurity (__in PACCESS_STATE AccessState, __in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in PVOID Object, __in POBJECT_TYPE ObjectType)
Definition at line 1478 of file obse.c.
References AssignSecurityDescriptor, NT_SUCCESS, NULL, ObpBeginTypeSpecificCallOut, ObpDirectoryObjectType, ObpEndTypeSpecificCallOut, PAGED_CODE, PagedPool, SeAssignSecurity(), SeDeassignSecurity(), and Status.
Referenced by ObInsertObject().
NTKERNELAPI BOOLEAN ObCheckCreateObjectAccess (__in PVOID DirectoryObject, __in ACCESS_MASK CreateAccess, __in PACCESS_STATE AccessState, __in PUNICODE_STRING ComponentName, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE PreviousMode, __out PNTSTATUS AccessStatus)
Definition at line 877 of file obse.c.
References FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeAppendPrivileges(), SeFreePrivileges(), SeLockSubjectContext(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by ObpLookupObjectName().
NTKERNELAPI BOOLEAN ObCheckObjectAccess (__in PVOID Object, __inout PACCESS_STATE AccessState, __in BOOLEAN TypeMutexLocked, __in KPROCESSOR_MODE AccessMode, __out PNTSTATUS AccessStatus)
Definition at line 388 of file obse.c.
References FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, MAXIMUM_ALLOWED, _OBJECT_TYPE::Name, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeAppendPrivileges(), SeFreePrivileges(), SeLockSubjectContext(), SeOpenObjectAuditAlarm(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by CmpDoOpen(), and ObpIncrementHandleCount().
VOID ObClearProcessHandleTable (PEPROCESS Process)
Definition at line 1318 of file obinit.c.
References ExSweepHandleTable(), FALSE, _OBP_SWEEP_CONTEXT::HandleTable, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, ObDereferenceProcessHandleTable(), ObpCloseHandleProcedure(), ObReferenceProcessHandleTable(), _EPROCESS::Pcb, _OBP_SWEEP_CONTEXT::PreviousMode, PsGetCurrentProcessByThread, PsGetCurrentThread(), _ETHREAD::Tcb, TRUE, and UserMode.
Referenced by NtTerminateProcess(), and PspTerminateProcess().
NTKERNELAPI NTSTATUS ObCloseHandle (__in HANDLE Handle, __in KPROCESSOR_MODE PreviousMode)
Definition at line 373 of file obclose.c.
References ObpCloseHandle().
Referenced by CmShutdownSystem(), DbgkCreateThread(), DbgkMapViewOfSection(), DbgkpFreeDebugEvent(), DbgkpOpenHandles(), DbgkpPostFakeModuleMessages(), DbgkpPostFakeThreadMessages(), IoCreateController(), IoCreateDevice(), IoCreateStreamFileObjectEx(), IoInitSystem(), IopCreateRootDirectories(), IopLoadDriver(), IopMarkBootPartition(), IopOpenLinkOrRenameTarget(), IopReassignSystemRoot(), IopSafebootDriverLoad(), IopStoreSystemPartitionInformation(), IopUnloadDriver(), IoSetInformation(), NtQueryInformationProcess(), NtSetInformationFile(), PspCreateProcess(), PspCreateThread(), and PspExitThread().
NTKERNELAPI NTSTATUS ObCreateObject (__in KPROCESSOR_MODE ProbeMode, __in POBJECT_TYPE ObjectType, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in KPROCESSOR_MODE OwnershipMode, __inout_opt PVOID ParseContext, __in ULONG ObjectBodySize, __in ULONG PagedPoolCharge, __in ULONG NonPagedPoolCharge, __out PVOID * Object)
NTKERNELAPI NTSTATUS ObCreateObjectType (__in PUNICODE_STRING TypeName, __in POBJECT_TYPE_INITIALIZER ObjectTypeInitializer, __in_opt PSECURITY_DESCRIPTOR SecurityDescriptor, __out POBJECT_TYPE * ObjectType)
Definition at line 87 of file obtype.c.
References _OBJECT_HEADER::Body, _STRING::Buffer, _UNICODE_STRING::Buffer, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE::DefaultObject, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExAllocatePoolWithTag, ExFreePool(), ExInitializeResourceLite(), FALSE, FIELD_OFFSET, _OBJECT_HEADER::Flags, FLG_MAINTAIN_OBJECT_TYPELIST, _OBJECT_TYPE::Index, InitializeListHead(), InsertTailList(), KernelMode, _STRING::Length, _UNICODE_STRING::Length, _OBJECT_TYPE_INITIALIZER::MaintainTypeList, _UNICODE_STRING::MaximumLength, _OBJECT_TYPE::Mutex, _OBJECT_TYPE::Name, NonPagedPool, NT_SUCCESS, NtGlobalFlag, NULL, OB_FLAG_KERNEL_OBJECT, OB_FLAG_PERMANENT_OBJECT, OBJ_ALL_VALID_ATTRIBUTES, OBJ_CASE_INSENSITIVE, OBJ_NAME_PATH_SEPARATOR, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_LOCK_COUNT, _OBJECT_TYPE::ObjectLocks, OBP_MAX_DEFINED_OBJECT_TYPES, ObpAllocateObject(), ObpDefaultObject, ObpEnterObjectTypeMutex, ObpInitializeLookupContext(), ObpInsertDirectoryEntry(), ObpLeaveObjectTypeMutex, ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpObjectTypes, ObpReleaseLookupContext(), ObpTypeDirectoryObject, ObpTypeObjectType, ObpValidateIrql, ObReferenceObject, PagedPool, PERFINFO_INITIALIZE_OBJECT_ALLOCATED_TYPE_LIST_HEAD, _OBJECT_TYPE_INITIALIZER::PoolType, RtlCopyUnicodeString(), RtlUnicodeStringToAnsiString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SeDefaultObjectMethod(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, SYNCHRONIZE, _OBJECT_TYPE::TotalNumberOfObjects, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_HEADER_CREATOR_INFO::TypeList, ULongToPtr, UNREFERENCED_PARAMETER, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, and wcscmp().
Referenced by CmpCreateObjectTypes(), DbgkInitialize(), ExpEventInitialization(), ExpEventPairInitialization(), ExpInitializeCallbacks(), ExpKeyedEventInitialization(), ExpMutantInitialization(), ExpProfileInitialization(), ExpSemaphoreInitialization(), ExpTimerInitialization(), ExpWin32Initialization(), IopCreateObjectTypes(), LpcInitSystem(), MiSectionInitialization(), ObInitSystem(), PspInitPhase0(), SepTokenInitialization(), and WmipInitializeSecurity().
NTKERNELAPI VOID ObDeleteCapturedInsertInfo (__in PVOID Object)
Definition at line 757 of file obcreate.c.
References _OBJECT_HEADER::Flags, NULL, OB_FLAG_NEW_OBJECT, OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, ObpFreeObjectCreateInformation, and PAGED_CODE.
Referenced by CcInitializeCacheMap().
VOID ObDereferenceDeviceMap (IN PEPROCESS Process)
Definition at line 640 of file obdevmap.c.
References NULL, ObfDereferenceDeviceMap(), ObpLockDeviceMap, and ObpUnlockDeviceMap.
Referenced by PspProcessDelete(), and PspSetPrimaryToken().
VOID ObDereferenceObjectDeferDelete (IN PVOID Object)
Definition at line 2521 of file obref.c.
References InterlockedDecrement, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDecrPointerCount, and ObpDeferObjectDeletion().
Referenced by CmpCreateLinkNode(), CmpDelayedDerefKeys(), CmpDoCreate(), CmpDoCreateChild(), CmpDoOpen(), CmpFlushNotifiesOnKeyBodyList(), CmpFreePostBlock(), IopCompleteRequest(), MmCreateSection(), ObpDereferenceNameInfo(), PspGetNextJobProcess(), PspJobDelete(), PspProcessDelete(), and PspQuitNextJobProcess().
LONG_PTR FASTCALL ObDereferenceObjectEx (IN PVOID Object, IN ULONG Count)
Definition at line 2335 of file obref.c.
References OBJECT_TO_OBJECT_HEADER, ObpDecrPointerCountEx, and ObpDeferObjectDeletion().
Referenced by ExpTimerApcRoutine(), ExTimerRundown(), IopDropIrp(), NtAssignProcessToJobObject(), NtCancelTimer(), NtSetTimer(), ObFastReferenceObject(), ObFastReplaceObject(), and PspCreateThread().
VOID ObDereferenceProcessHandleTable (PEPROCESS SourceProcess)
Definition at line 150 of file obhandle.c.
References ExReleaseRundownProtection(), and _EPROCESS::RundownProtect.
Referenced by NtQueryInformationProcess(), NtSetInformationProcess(), ObClearProcessHandleTable(), ObDuplicateObject(), ObFindHandleForObject(), ObGetProcessHandleCount(), and ObInitProcess().
NTKERNELAPI VOID ObDereferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
Definition at line 702 of file obsdata.c.
References ASSERT, ExAcquirePushLockExclusive(), ExFreePool(), ExReleasePushLockExclusive(), _SECURITY_DESCRIPTOR_HEADER::FullHash, InterlockedCompareExchange(), InterlockedExchangeAdd(), KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), ObpDestroySecurityDescriptorHeader(), ObPrint, PsGetCurrentThread(), _OB_SD_CACHE_LIST::PushLock, _SECURITY_DESCRIPTOR_HEADER::RefCount, SD_TO_SD_HEADER, SECURITY_DESCRIPTOR_CACHE_ENTRIES, and _ETHREAD::Tcb.
Referenced by IopCompleteUnloadOrDelete(), IopGetSetSecurityObject(), IopSetDeviceSecurityDescriptor(), ObDeassignSecurity(), ObQuerySecurityDescriptorInfo(), ObReleaseObjectSecurity(), and ObSetSecurityDescriptorInfo().
NTSTATUS ObDumpObjectByHandle (IN HANDLE Handle, IN POB_DUMP_CONTROL Control OPTIONAL)
NTSTATUS ObDumpObjectByPointer (IN PVOID Object, IN POB_DUMP_CONTROL Control OPTIONAL)
NTSTATUS ObDuplicateObject (IN PEPROCESS SourceProcess, IN HANDLE SourceHandle, IN PEPROCESS TargetProcess OPTIONAL, OUT PHANDLE TargetHandle OPTIONAL, IN ACCESS_MASK DesiredAccess, IN ULONG HandleAttributes, IN ULONG Options, IN KPROCESSOR_MODE PreviousMode)
Definition at line 210 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _ACCESS_STATE::AuxData, _HANDLE_TABLE_ENTRY::CreatorBackTraceIndex, DUPLICATE_CLOSE_SOURCE, DUPLICATE_SAME_ACCESS, DUPLICATE_SAME_ATTRIBUTES, ExCreateHandle(), ExMapHandleToPointer(), ExSetHandleInfo(), ExUnlockHandleTableEntry(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _ACCESS_STATE::GenerateOnClose, GENERIC_ACCESS, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, _OBJECT_HANDLE_INFORMATION::HandleAttributes, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NtClose(), NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, ObDereferenceObject(), ObDereferenceProcessHandleTable(), ObDuplicateHandle, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, OBP_CREATOR_BACKTRACE_LIMIT, ObpComputeGrantedAccessIndex(), ObpDecrementHandleCount(), ObpEncodeProtectClose, ObpIncrementHandleCount(), ObpReferenceProcessObjectByHandle(), ObpValidateDesiredAccess(), ObReferenceProcessHandleTable(), PsGetCurrentProcess(), RtlLogStackBackTrace(), RtlLogUmodeStackBackTrace(), RtlMapGenericMask(), RtlZeroMemory, SeAuditHandleCreation(), SeAuditHandleDuplication(), SeCreateAccessState(), _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SeDefaultObjectMethod(), SeDeleteAccessState(), SeDetailedAuditingWithToken(), SeQuerySubjectContextToken, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ACCESS_STATE::SubjectSecurityContext, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by DbgkpOpenHandles(), and NtDuplicateObject().
NTKERNELAPI LONG_PTR FASTCALL ObfDereferenceObject (__in PVOID Object)
Definition at line 2418 of file obref.c.
References ASSERT, FALSE, _OBJECT_HEADER::HandleCount, InterlockedDecrement, KeAreAllApcsDisabled(), KeGetCurrentIrql(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDecrPointerCount, ObpDeferObjectDeletion(), ObpRemoveObjectRoutine(), ObpTraceEnabled, ObpTraceNoDeregister, ReadForWriteAccess, and _OBJECT_HEADER::Type.
Referenced by ObDereferenceObject().
NTKERNELAPI BOOLEAN ObFindHandleForObject (__in PEPROCESS Process, __in PVOID Object, __in_opt POBJECT_TYPE ObjectType, __in_opt POBJECT_HANDLE_INFORMATION MatchCriteria, __out PHANDLE Handle)
VOID FASTCALL ObFreeObjectCreateInfoBuffer (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo)
Definition at line 1350 of file obcreate.c.
References ObpFreeObjectCreateInfoBuffer.
Referenced by IoCreateStreamFileObjectLite().
NTKERNELAPI LONG_PTR FASTCALL ObfReferenceObject (__in PVOID Object)
Definition at line 2268 of file obref.c.
References ASSERT, OBJECT_TO_OBJECT_HEADER, and ObpIncrPointerCount.
Referenced by NtQueryObject(), and ObpQueryNameString().
NTKERNELAPI NTSTATUS ObGetObjectSecurity (__in PVOID Object, __out PSECURITY_DESCRIPTOR * SecurityDescriptor, __out PBOOLEAN MemoryAllocated)
Definition at line 1131 of file obse.c.
References DACL_SECURITY_INFORMATION, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, GROUP_SECURITY_INFORMATION, NT_SUCCESS, NULL, OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpCentralizedSecurity, ObpDefaultSecurityDescriptorLength, ObpEndTypeSpecificCallOut, ObpReferenceSecurityDescriptor(), OWNER_SECURITY_INFORMATION, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, QuerySecurityDescriptor, SACL_SECURITY_INFORMATION, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObInsertObject(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), PspCreateProcess(), PspCreateThread(), and PspSetPrimaryToken().
ULONG ObGetProcessHandleCount (PEPROCESS Process)
Definition at line 173 of file obhandle.c.
References _HANDLE_TABLE::HandleCount, ObDereferenceProcessHandleTable(), and ObReferenceProcessHandleTable().
Referenced by ExpCopyProcessInfo(), and NtQueryInformationProcess().
ULONG ObGetSecurityMode ()
Definition at line 2614 of file obinit.c.
References ObpObjectSecurityMode.
Referenced by NtQuerySystemInformation().
VOID ObInheritDeviceMap (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess OPTIONAL)
Definition at line 571 of file obdevmap.c.
References NULL, ObpLockDeviceMap, ObpUnlockDeviceMap, ObSystemDeviceMap, and _DEVICE_MAP::ReferenceCount.
Referenced by PspCreateProcess().
NTSTATUS ObInitProcess (PEPROCESS ParentProcess OPTIONAL, PEPROCESS NewProcess)
Definition at line 1089 of file obinit.c.
References ARGUMENT_PRESENT, ExCreateHandleTable(), ExDupHandleTable(), ExEnumHandleTable(), NULL, ObAuditInheritedHandleProcedure(), ObDereferenceProcessHandleTable(), ObDupHandleProcedure(), OBJ_INHERIT, _EPROCESS::ObjectTable, ObReferenceProcessHandleTable(), _SE_PROCESS_AUDIT_INFO::Parent, _SE_PROCESS_AUDIT_INFO::Process, SeDetailedAuditingWithToken(), STATUS_INSUFFICIENT_RESOURCES, STATUS_PROCESS_IS_TERMINATING, and STATUS_SUCCESS.
Referenced by PspCreateProcess().
VOID ObInitProcess2 (PEPROCESS NewProcess)
Definition at line 1214 of file obinit.c.
References ExSetHandleTableOrder, _EPROCESS::ObjectTable, and _EPROCESS::SubSystemVersion.
BOOLEAN ObInitSystem (VOID)
Definition at line 224 of file obinit.c.
References ACL_REVISION, ACL_REVISION2, ASSERT, _OBJECT_TYPE_INITIALIZER::CaseInsensitive, CONTAINER_INHERIT_ACE, CONTAINING_RECORD, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_ALL_ACCESS, DIRECTORY_QUERY, DIRECTORY_TRAVERSE, ExAllocatePoolWithTag, ExCreateHandleTable(), ExFreePool(), ExInitializePushLock(), ExInitializeSystemLookasideList(), ExInitializeWorkItem, ExSetHandleTableStrictFIFO(), ExSystemLookasideListHead, FALSE, FLG_KERNEL_STACK_TRACE_DB, _LIST_ENTRY::Flink, GENERIC_ALL, _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, _ETHREAD::GrantedAccess, Index, INHERIT_ONLY_ACE, InitializationPhase, InitializeObjectAttributes, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KeGetCurrentPrcb(), KeInitializeEvent(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeNumberProcessors, KernelMode, KiProcessorBlock, _PP_LOOKASIDE_LIST::L, _OBJECT_TYPE_INITIALIZER::Length, LookasideCreateInfoList, LookasideNameBufferList, _OBJECT_TYPE_INITIALIZER::MaintainTypeList, MmIsThisAnNtAsSystem(), MmLargeSystem, MmQuerySystemSize(), _OBJECT_HEADER_NAME_INFO::Name, NonPagedPool, NotificationEvent, NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NtGlobalFlag, NULL, OB_NAMESPACE_POOL_TYPE, ObCreateObjectType(), OBJ_CASE_INSENSITIVE, OBJ_OPENLINK, OBJ_PERMANENT, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_INHERIT_ACE, OBJECT_NAME_BUFFER_SIZE, OBJECT_TYPE_ALL_ACCESS, _EPROCESS::ObjectTable, OBP_PAGEDPOOL_NAMESPACE, ObpAccessProtectCloseBit, ObpAuditBaseDirectories, ObpAuditBaseObjects, ObpCreateDosDevicesDirectory(), ObpCreateInfoLookasideList, ObpDefaultObject, ObpDeleteObjectType(), ObpDeleteSymbolicLink(), ObpDeviceMapLock, ObpDirectoryMapping, ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpInitSecurityDescriptorCache(), ObpInsertDirectoryEntry(), ObpKernelHandleTable, ObpLock, ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpNameBufferLookasideList, ObpParseSymbolicLink(), ObpProcessRemoveObjectQueue(), ObpReleaseLookupContext(), ObpRemoveObjectList, ObpRemoveObjectWorkItem, ObpRootDirectoryObject, ObpSymbolicLinkMapping, ObpSymbolicLinkObjectType, ObpTypeDirectoryObject, ObpTypeMapping, ObpTypeObjectType, ObReferenceObjectByHandle, _PP_LOOKASIDE_LIST::P, PAGE_SIZE, PagedPool, _OBJECT_TYPE_INITIALIZER::ParseProcedure, _OBJECT_TYPE_INITIALIZER::PoolType, _KPRCB::PPLookasideList, PROCESS_ALL_ACCESS, PsGetCurrentProcess(), PsGetCurrentThread(), PsInitializeQuotaSystem(), READ_CONTROL, RtlAddAccessAllowedAce(), RtlAddAuditAccessAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlGetAce(), RtlInitUnicodeString(), RtlLengthSid(), RtlSetDaclSecurityDescriptor(), RtlSetSaclSecurityDescriptor(), RtlZeroMemory, SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SECURITY_DESCRIPTOR_REVISION1, SeLengthSid, SeLocalSystemSid, SePublicDefaultUnrestrictedDacl, SePublicDefaultUnrestrictedSd, SeWorldSid, Status, SYMBOLIC_LINK_ALL_ACCESS, SYNCHRONIZE, THREAD_ALL_ACCESS, TRUE, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTKERNELAPI NTSTATUS ObInsertObject (__in PVOID Object, __in_opt PACCESS_STATE PassedAccessState, __in_opt ACCESS_MASK DesiredAccess, __in ULONG ObjectPointerBias, __out_opt PVOID * NewObject, __out_opt PHANDLE Handle)
Definition at line 27 of file obinsert.c.
References ARGUMENT_PRESENT, ASSERT, _OBJECT_CREATE_INFORMATION::Attributes, _UNICODE_STRING::Buffer, _OBJECT_HEADER_NAME_INFO::Directory, _OBP_LOOKUP_CONTEXT::DirectoryLocked, FALSE, _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, KdBreakPoint, KdPrint, KeGetPreviousMode, KernelMode, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, OB_FLAG_KERNEL_OBJECT, OB_FLAG_NEW_OBJECT, ObAssignSecurity(), ObCreateHandle, ObDereferenceObject(), ObGetObjectSecurity(), OBJ_OPENIF, OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, ObOpenHandle, ObpChargeQuotaForObject(), ObpCreateHandle(), ObpCreateSymbolicLinkName(), ObpCreateUnnamedHandle(), ObpDeleteDirectoryEntry(), ObpDeleteNameCheck(), ObpDereferenceNameInfo(), ObpFreeObjectCreateInformation, ObpInitializeLookupContext(), ObpLockObject, ObpLookupObjectName(), ObpReferenceNameInfo(), ObpReleaseLookupContext(), ObpSymbolicLinkObjectType, ObpUnlockObject, ObpValidateAccessMask(), ObpValidateIrql, ObReleaseObjectSecurity(), PAGED_CODE, _OBJECT_CREATE_INFORMATION::ParseContext, _OBJECT_CREATE_INFORMATION::ProbeMode, _OBJECT_CREATE_INFORMATION::RootDirectory, SeCreateAccessState(), _OBJECT_CREATE_INFORMATION::SecurityDescriptor, _OBJECT_CREATE_INFORMATION::SecurityQos, _OBJECT_TYPE_INITIALIZER::SecurityRequired, SeDeleteAccessState(), SeReleaseSecurityDescriptor(), Status, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_EXISTS, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UserMode.
Referenced by CmpCreateRegistryRoot(), ExCreateCallback(), FsRtlCreateSectionForDataScan(), IoCreateController(), IoCreateDevice(), IoCreateDriver(), IoCreateStreamFileObjectEx(), IopInitializeBuiltinDriver(), IopLoadDriver(), LpcpCreatePort(), MiSectionInitialization(), NtAcceptConnectPort(), NtCreateDebugObject(), NtCreateDirectoryObject(), NtCreateEvent(), NtCreateEventPair(), NtCreateIoCompletion(), NtCreateJobObject(), NtCreateKeyedEvent(), NtCreateMutant(), NtCreateProfile(), NtCreateSection(), NtCreateSemaphore(), NtCreateSymbolicLinkObject(), NtCreateTimer(), NtDuplicateToken(), NtFilterToken(), NtOpenThreadTokenEx(), NtSecureConnectPort(), PspCreateProcess(), PspCreateThread(), SeCopyClientToken(), SeFastFilterToken(), SeFilterToken(), SepCreateToken(), SepInitializationPhase1(), SeSubProcessToken(), and WmipCreateGuidObject().
ULONG ObIsLUIDDeviceMapsEnabled ()
Definition at line 701 of file obdevmap.c.
References ObpLUIDDeviceMapsEnabled.
Referenced by IoDeleteSymbolicLink(), NtQueryInformationProcess(), and PspSetPrimaryToken().
BOOLEAN ObIsObjectDeletionInline (IN PVOID Object)
Definition at line 2952 of file obref.c.
References _OBJECT_HEADER::Flags, OB_FLAG_DELETED_INLINE, and OBJECT_TO_OBJECT_HEADER.
Referenced by IopDeleteFile().
FORCEINLINE POBJECT_HEADER_CREATOR_INFO OBJECT_HEADER_TO_CREATOR_INFO (IN POBJECT_HEADER ObjectHeader)
Definition at line 590 of file ob.h.
References NULL, and OB_FLAG_CREATOR_INFO.
Referenced by ObCreateObjectType(), ObpFreeObject(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), and ObpRemoveObjectRoutine().
FORCEINLINE POBJECT_HEADER_HANDLE_INFO OBJECT_HEADER_TO_HANDLE_INFO (IN POBJECT_HEADER ObjectHeader)
Definition at line 539 of file ob.h.
References NULL, and OBJECT_HEADER_TO_HANDLE_INFO_EXISTS().
Referenced by ObpFreeObject(), and ObpInsertHandleCount().
FORCEINLINE POBJECT_HEADER_HANDLE_INFO OBJECT_HEADER_TO_HANDLE_INFO_EXISTS (IN POBJECT_HEADER ObjectHeader)
Definition at line 528 of file ob.h.
References ASSERT.
Referenced by OBJECT_HEADER_TO_HANDLE_INFO(), ObpDecrementHandleCount(), and ObpIncrementHandleDataBase().
FORCEINLINE POBJECT_HEADER_NAME_INFO OBJECT_HEADER_TO_NAME_INFO (IN POBJECT_HEADER ObjectHeader)
Definition at line 570 of file ob.h.
References NULL, and OBJECT_HEADER_TO_NAME_INFO_EXISTS().
Referenced by NtQueryDirectoryObject(), ObDereferenceObjectDeferDelete(), ObEnumerateObjectsByType(), ObfDereferenceObject(), ObInitSystem(), ObpFreeObject(), ObpIsKernelExclusiveObject(), ObpLookupDirectoryEntry(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceNameInfo(), ObpReleaseLookupContext(), ObpReleaseLookupContextObject(), ObpRemoveObjectRoutine(), and ObShutdownSystem().
FORCEINLINE POBJECT_HEADER_NAME_INFO OBJECT_HEADER_TO_NAME_INFO_EXISTS (IN POBJECT_HEADER ObjectHeader)
Definition at line 559 of file ob.h.
References ASSERT.
Referenced by OBJECT_HEADER_TO_NAME_INFO(), ObpInsertDirectoryEntry(), ObpLookupDirectoryEntry(), ObpLookupObjectName(), ObpReleaseExclusiveNameLock(), and ObpTryReferenceNameInfoExclusive().
FORCEINLINE POBJECT_HEADER_QUOTA_INFO OBJECT_HEADER_TO_QUOTA_INFO (IN POBJECT_HEADER ObjectHeader)
Definition at line 510 of file ob.h.
References NULL, and OBJECT_HEADER_TO_QUOTA_INFO_EXISTS().
Referenced by NtQueryObject(), ObGetObjectInformation(), ObpChargeQuotaForObject(), ObpFreeObject(), and ObValidateSecurityQuota().
FORCEINLINE POBJECT_HEADER_QUOTA_INFO OBJECT_HEADER_TO_QUOTA_INFO_EXISTS (IN POBJECT_HEADER ObjectHeader)
Definition at line 499 of file ob.h.
References ASSERT.
Referenced by OBJECT_HEADER_TO_QUOTA_INFO(), ObpDecrementHandleCount(), ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
VOID ObKillProcess (PEPROCESS Process)
Definition at line 1376 of file obinit.c.
References ASSERT, ExDestroyHandleTable(), ExRundownCompleted(), ExSweepHandleTable(), ExWaitForRundownProtectionRelease(), FALSE, _HANDLE_TABLE::HandleCount, _OBP_SWEEP_CONTEXT::HandleTable, IoSetThreadHardErrorMode(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, NULL, _EPROCESS::ObjectTable, ObpCloseHandleProcedure(), ObpValidateIrql, PAGED_CODE, _OBP_SWEEP_CONTEXT::PreviousMode, and _EPROCESS::RundownProtect.
Referenced by PspExitThread(), and PspProcessDelete().
NTKERNELAPI NTSTATUS ObLogSecurityDescriptor (__in PSECURITY_DESCRIPTOR InputSecurityDescriptor, __out PSECURITY_DESCRIPTOR * OutputSecurityDescriptor, __in ULONG RefBias)
Definition at line 276 of file obsdata.c.
References ExAcquirePushLockExclusive(), ExAcquirePushLockShared(), ExFreePool(), ExReleasePushLock(), ExReleasePushLockExclusive(), ExReleasePushLockShared(), FALSE, _LIST_ENTRY::Flink, _SECURITY_DESCRIPTOR_HEADER::FullHash, _OB_SD_CACHE_LIST::Head, InsertTailList(), InterlockedExchangeAdd(), InterlockedIncrement, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _SECURITY_DESCRIPTOR_HEADER::Link, LINK_TO_SD_HEADER, NULL, ObpCompareSecurityDescriptors(), ObpCreateCacheEntry(), ObpHashSecurityDescriptor(), ObPrint, PsGetCurrentThread(), _OB_SD_CACHE_LIST::PushLock, _SECURITY_DESCRIPTOR_HEADER::RefCount, RtlLengthSecurityDescriptor(), SECURITY_DESCRIPTOR_CACHE_ENTRIES, _SECURITY_DESCRIPTOR_HEADER::SecurityDescriptor, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by IopGetSetSecurityObject(), IopSetDeviceSecurityDescriptor(), ObAssignObjectSecurityDescriptor(), and ObSetSecurityDescriptorInfo().
NTKERNELAPI VOID ObMakeTemporaryObject (__in PVOID Object)
Definition at line 495 of file obclose.c.
References _OBJECT_HEADER::Flags, OB_FLAG_PERMANENT_OBJECT, OBJECT_TO_OBJECT_HEADER, ObpDeleteNameCheck(), ObpLockObject, ObpUnlockObject, PAGED_CODE, and _OBJECT_HEADER::Type.
Referenced by IoCreateDriver(), IoDeleteDevice(), IopCompleteUnloadOrDelete(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopUnloadDriver(), NtMakeTemporaryObject(), ObfDereferenceDeviceMap(), and ObShutdownSystem().
NTKERNELAPI NTSTATUS ObOpenObjectByName (__in POBJECT_ATTRIBUTES ObjectAttributes, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __inout_opt PVOID ParseContext, __out PHANDLE Handle)
Definition at line 592 of file obref.c.
References ARGUMENT_PRESENT, _OBJECT_CREATE_INFORMATION::Attributes, _OB_TEMP_BUFFER::AuxData, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OB_TEMP_BUFFER::LocalAccessState, _OB_TEMP_BUFFER::LookupContext, NonPagedPool, NT_SUCCESS, NULL, OB_FLAG_NEW_OBJECT, ObCreateHandle, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, _OB_TEMP_BUFFER::ObjectCreateInfo, ObOpenHandle, ObpCaptureObjectCreateInformation(), ObpCreateHandle(), ObpFreeObjectCreateInformation, ObpFreeObjectNameBuffer(), ObpLookupObjectName(), ObpReleaseLookupContext(), ObpReleaseObjectCreateInformation, ObpValidateAccessMask(), ObpValidateIrql, PAGED_CODE, _OBJECT_CREATE_INFORMATION::RootDirectory, SeCreateAccessState(), _OBJECT_CREATE_INFORMATION::SecurityDescriptor, _OBJECT_CREATE_INFORMATION::SecurityQos, SeDeleteAccessState(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by CmLoadKey(), CmpCreatePredefined(), CmpLinkHiveToMaster(), ExCreateCallback(), IoFastQueryNetworkAttributes(), IopCreateFile(), IopLoadDriver(), IopReferenceDriverObjectByName(), IopUnloadDriver(), NtCreateKey(), NtDeleteFile(), NtNotifyChangeMultipleKeys(), NtOpenDirectoryObject(), NtOpenEvent(), NtOpenEventPair(), NtOpenIoCompletion(), NtOpenJobObject(), NtOpenKey(), NtOpenKeyedEvent(), NtOpenMutant(), NtOpenProcess(), NtOpenSection(), NtOpenSemaphore(), NtOpenSymbolicLinkObject(), NtOpenThread(), NtOpenTimer(), NtQueryAttributesFile(), NtQueryFullAttributesFile(), NtQueryOpenSubKeys(), NtQueryOpenSubKeysEx(), NtUnloadKey2(), and NtUnloadKeyEx().
NTKERNELAPI NTSTATUS ObOpenObjectByPointer (__in PVOID Object, __in ULONG HandleAttributes, __in_opt PACCESS_STATE PassedAccessState, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PHANDLE Handle)
Definition at line 886 of file obref.c.
References ARGUMENT_PRESENT, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObOpenHandle, ObpCreateHandle(), ObpValidateIrql, ObReferenceObjectByPointer(), PAGED_CODE, SeCreateAccessState(), SeDeleteAccessState(), Status, STATUS_INVALID_PARAMETER, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by DbgkOpenProcessDebugPort(), DbgkpOpenHandles(), IopInvalidateVolumesForDevice(), NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenProcessTokenEx(), NtOpenThread(), NtOpenThreadTokenEx(), WmipOpenGuidObject(), and WmipReceiveNotifications().
NTSTATUS ObQueryDeviceMapInformation (IN PEPROCESS TargetProcess OPTIONAL, OUT PPROCESS_DEVICEMAP_INFORMATION DeviceMapInformation, IN ULONG Flags)
Definition at line 393 of file obdevmap.c.
References ARGUMENT_PRESENT, _OBJECT_DIRECTORY::DeviceMap, DOSDEVICE_DRIVE_CALCULATE, DOSDEVICE_DRIVE_REMOTE, _DEVICE_MAP::DriveMap, _DEVICE_MAP::DriveType, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _DEVICE_MAP::GlobalDosDevicesDirectory, NULL, ObfDereferenceDeviceMap(), ObpLockDeviceMap, ObpLUIDDeviceMapsEnabled, ObpReferenceDeviceMap(), ObpUnlockDeviceMap, ObSystemDeviceMap, PROCESS_LUID_DOSDEVICES_ONLY, PsGetCurrentProcess(), _PROCESS_DEVICEMAP_INFORMATION::Query, RtlCopyMemory, Status, STATUS_END_OF_FILE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by NtQueryInformationProcess().
NTKERNELAPI NTSTATUS ObQueryNameString (__in PVOID Object, __out_bcount(Length) POBJECT_NAME_INFORMATION ObjectNameInfo, __in ULONG Length, __out PULONG ReturnLength)
Definition at line 794 of file obquery.c.
References KernelMode, and ObpQueryNameString().
Referenced by CmpAcquireFileObjectForFile(), IopErrorLogThread(), IopQueryNameInternal(), IopRaiseHardError(), MmGetFileNameForAddress(), MmGetFileNameForSection(), NtQueryVirtualMemory(), ObGetObjectInformation(), PerfInfoFileNameRunDown(), SeInitializeProcessAuditName(), SepQueryNameString(), and WmipTraceFile().
NTKERNELAPI NTSTATUS ObQueryObjectAuditingByHandle (__in HANDLE Handle, __out PBOOLEAN GenerateOnClose)
Definition at line 1618 of file obquery.c.
References DecodeKernelHandle, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), FALSE, IsKernelHandle, KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, ObpKernelHandleTable, ObpValidateIrql, PAGED_CODE, PsGetCurrentProcessByThread, PsGetCurrentThread(), Status, STATUS_INVALID_HANDLE, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
NTSTATUS ObQueryTypeInfo (IN POBJECT_TYPE ObjectType, OUT POBJECT_TYPE_INFORMATION ObjectTypeInfo, IN ULONG Length, OUT PULONG ReturnLength)
Definition at line 1515 of file obquery.c.
References ALIGN_UP, except, EXCEPTION_EXECUTE_HANDLER, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtQueryObject().
NTSTATUS ObQueryTypeName (IN PVOID Object, PUNICODE_STRING ObjectTypeName, IN ULONG Length, OUT PULONG ReturnLength)
Definition at line 1392 of file obquery.c.
References _UNICODE_STRING::Buffer, except, EXCEPTION_EXECUTE_HANDLER, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_TYPE::Name, OBJECT_TO_OBJECT_HEADER, PAGED_CODE, RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _OBJECT_HEADER::Type, and UNICODE_NULL.
Referenced by ObGetObjectInformation(), and SepQueryTypeString().
NTKERNELAPI NTSTATUS ObReferenceFileObjectForWrite (IN HANDLE Handle, IN KPROCESSOR_MODE AccessMode, OUT PVOID * FileObject, OUT POBJECT_HANDLE_INFORMATION HandleInformation)
Definition at line 1580 of file obref.c.
References ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _OBJECT_HEADER::Body, DecodeKernelHandle, ExGetHandleInfo, ExMapHandleToPointerEx(), ExUnlockHandleTableEntry(), FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, IoComputeDesiredAccessFileObject(), KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KernelMode, _OBJECT_TYPE::Name, NT_SUCCESS, NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, ObpAuditObjectAccess(), ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), ObpValidateIrql, PsGetCurrentProcessByThread, PsGetCurrentThread(), SeComputeGrantedAccesses, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_HANDLE, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and _OBJECT_HEADER::Type.
Referenced by NtWriteFile().
NTKERNELAPI NTSTATUS ObReferenceObjectByHandle (__in HANDLE Handle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __out PVOID * Object, __out_opt POBJECT_HANDLE_INFORMATION HandleInformation)
Definition at line 1061 of file obref.c.
References ARGUMENT_PRESENT, ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _OBJECT_HEADER::Body, DecodeKernelHandle, ExGetHandleInfo, ExMapHandleToPointerEx(), ExUnlockHandleTableEntry(), FLG_KERNEL_STACK_TRACE_DB, _EPROCESS::GrantedAccess, _ETHREAD::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KernelMode, _OBJECT_TYPE::Name, NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, ObpAuditObjectAccess(), ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), ObpValidateIrql, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, PsThreadType, ReadForWriteAccess, SeComputeDeniedAccesses, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_HANDLE, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and _OBJECT_HEADER::Type.
NTKERNELAPI NTSTATUS ObReferenceObjectByName (__in PUNICODE_STRING ObjectName, __in ULONG Attributes, __in_opt PACCESS_STATE AccessState, __in_opt ACCESS_MASK DesiredAccess, __in POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode, __inout_opt PVOID ParseContext, __out PVOID * Object)
Definition at line 1991 of file obref.c.
References ARGUMENT_PRESENT, FALSE, _AUX_ACCESS_DATA::GenericMapping, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), ObpCaptureObjectName(), ObpCheckObjectReference(), ObpFreeObjectNameBuffer(), ObpLookupObjectName(), ObpReleaseLookupContext(), ObpValidateIrql, PAGED_CODE, SeCreateAccessState(), SeDeleteAccessState(), Status, STATUS_OBJECT_NAME_INVALID, and TRUE.
Referenced by IopGetDriverPathInformation(), NtSecureConnectPort(), and ObShutdownSystem().
NTKERNELAPI NTSTATUS ObReferenceObjectByPointer (__in PVOID Object, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_TYPE ObjectType, __in KPROCESSOR_MODE AccessMode)
Definition at line 2169 of file obref.c.
References KernelMode, OBJECT_TO_OBJECT_HEADER, ObpIncrPointerCount, ObpSymbolicLinkObjectType, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, _OBJECT_HEADER::Type, and UNREFERENCED_PARAMETER.
Referenced by NtImpersonateAnonymousToken(), ObOpenObjectByPointer(), ObpLookupObjectName(), ObpParseSymbolicLink(), WmipQueryAllData(), WmipQuerySetExecuteSI(), WmipQueueNotification(), WmipRegisterDevice(), WmipTraceIo(), WmipTranslateFileHandle(), and WmipWriteMBToObject().
NTKERNELAPI LONG_PTR FASTCALL ObReferenceObjectEx (IN PVOID Object, IN ULONG Count)
Definition at line 2305 of file obref.c.
References OBJECT_TO_OBJECT_HEADER, and ObpIncrPointerCountEx.
Referenced by ObFastReferenceObject(), ObFastReplaceObject(), ObInitializeFastReference(), and PspCreateThread().
NTKERNELAPI BOOLEAN FASTCALL ObReferenceObjectSafe (IN PVOID Object)
Definition at line 2372 of file obref.c.
References FALSE, OBJECT_TO_OBJECT_HEADER, ObpPushStackInfo, ObpSafeInterlockedIncrement(), ObpTraceEnabled, _OBJECT_HEADER::PointerCount, and TRUE.
Referenced by CmpFlushNotifiesOnKeyBodyList(), ExpTimerDpcRoutine(), NtImpersonateClientOfPort(), NtRequestPort(), ObpCreateTypeArray(), PsEnumProcesses(), PsGetNextJob(), PsGetNextJobProcess(), PsGetNextProcess(), PsGetNextProcessThread(), PsLookupProcessByProcessId(), PsLookupProcessThreadByCid(), PsLookupThreadByThreadId(), PspExitThread(), PspGetJobFromSet(), PspGetNextJobProcess(), SepCleanupLUIDDeviceMapDirectory(), WmipCreatePumpThreadRoutine(), and WmipProcessEvent().
PHANDLE_TABLE ObReferenceProcessHandleTable (PEPROCESS SourceProcess)
Definition at line 107 of file obhandle.c.
References ExAcquireRundownProtection(), ExReleaseRundownProtection(), NULL, _EPROCESS::ObjectTable, and _EPROCESS::RundownProtect.
Referenced by NtQueryInformationProcess(), NtSetInformationProcess(), ObClearProcessHandleTable(), ObDuplicateObject(), ObFindHandleForObject(), ObGetProcessHandleCount(), and ObInitProcess().
VOID ObReferenceSecurityDescriptor (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Count)
Definition at line 529 of file obsdata.c.
References _SECURITY_DESCRIPTOR_HEADER::FullHash, InterlockedExchangeAdd(), ObPrint, _SECURITY_DESCRIPTOR_HEADER::RefCount, and SD_TO_SD_HEADER.
Referenced by IopGetSetSecurityObject(), and IopSetDeviceSecurityDescriptor().
NTKERNELAPI VOID ObReleaseObjectSecurity (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __in BOOLEAN MemoryAllocated)
Definition at line 1319 of file obse.c.
References ExFreePool(), NULL, ObDereferenceSecurityDescriptor(), and PAGED_CODE.
Referenced by ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObInsertObject(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), PspCreateProcess(), PspCreateThread(), and PspSetPrimaryToken().
FORCEINLINE ULONG ObSanitizeHandleAttributes (IN ULONG HandleAttributes, IN KPROCESSOR_MODE Mode)
Definition at line 659 of file ob.h.
References KernelMode, OBJ_ALL_VALID_ATTRIBUTES, OBJ_KERNEL_EXCLUSIVE, and OBJ_KERNEL_HANDLE.
Referenced by NtGetNextProcess(), NtGetNextThread(), NtOpenProcess(), NtOpenProcessTokenEx(), NtOpenThread(), and NtOpenThreadTokenEx().
NTSTATUS ObSetDeviceMap (IN PEPROCESS TargetProcess OPTIONAL, IN HANDLE DirectoryHandle)
Definition at line 227 of file obdevmap.c.
References _EPROCESS::DeviceMap, _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_TRAVERSE, _DEVICE_MAP::DosDevicesDirectory, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_HEADER::Flags, _DEVICE_MAP::GlobalDosDevicesDirectory, KeGetPreviousMode, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, OB_NAMESPACE_POOL_TYPE, ObDereferenceObject(), ObfDereferenceDeviceMap(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpLockDeviceMap, ObpLockObject, ObpReferenceNameInfo(), ObpUnlockDeviceMap, ObpUnlockObject, ObReferenceObjectByHandle, ObSystemDeviceMap, PAGED_CODE, PsGetCurrentProcess(), _DEVICE_MAP::ReferenceCount, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, and TRUE.
Referenced by NtSetInformationProcess(), and ObpCreateDosDevicesDirectory().
NTSTATUS ObSetDirectoryDeviceMap (OUT PDEVICE_MAP *ppDeviceMap OPTIONAL, IN HANDLE DirectoryHandle)
Definition at line 76 of file obdevmap.c.
References _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_TRAVERSE, _DEVICE_MAP::DosDevicesDirectory, ExAllocatePoolWithTag, ExFreePool(), _OBJECT_HEADER::Flags, _DEVICE_MAP::GlobalDosDevicesDirectory, KernelMode, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, OB_NAMESPACE_POOL_TYPE, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpLockDeviceMap, ObpLockObject, ObpReferenceNameInfo(), ObpUnlockDeviceMap, ObpUnlockObject, ObReferenceObjectByHandle, ObSystemDeviceMap, PAGED_CODE, _DEVICE_MAP::ReferenceCount, RtlZeroMemory, Status, and STATUS_INSUFFICIENT_RESOURCES.
Referenced by SeGetLogonIdDeviceMap().
NTKERNELAPI NTSTATUS ObSetHandleAttributes (__in HANDLE Handle, __in POBJECT_HANDLE_FLAG_INFORMATION HandleFlags, __in KPROCESSOR_MODE PreviousMode)
Definition at line 573 of file obquery.c.
References DecodeKernelHandle, ExChangeHandle(), FALSE, Handle, IsKernelHandle, KeStackAttachProcess(), KeUnstackDetachProcess(), __OBP_SET_HANDLE_ATTRIBUTES::ObjectInformation, ObpGetObjectTable, ObpKernelHandleTable, ObpSetHandleAttributes(), PAGED_CODE, _EPROCESS::Pcb, __OBP_SET_HANDLE_ATTRIBUTES::PreviousMode, PsGetCurrentProcess(), PsInitialSystemProcess, Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationObject().
NTKERNELAPI NTSTATUS ObSetSecurityObjectByPointer (__in PVOID Object, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 171 of file obse.c.
References ARGUMENT_PRESENT, ASSERT, _OBJECT_TYPE_INITIALIZER::GenericMapping, NULL, OBJECT_TO_OBJECT_HEADER, PAGED_CODE, _OBJECT_TYPE_INITIALIZER::PoolType, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SetSecurityDescriptor, Status, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by NtSetSecurityObject(), and WmipDriverEntry().
VOID ObShutdownSystem (IN ULONG Phase)
Definition at line 2253 of file obinit.c.
References ASSERT, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, _OBJECT_DIRECTORY_ENTRY::ChainLink, CONTAINING_RECORD, DeleteSecurityDescriptor, _OBJECT_HEADER_NAME_INFO::Directory, ExEnumHandleTable(), ExFreePool(), _OBJECT_HEADER::Flags, _LIST_ENTRY::Flink, _OBJECT_HEADER::HandleCount, _OBJECT_DIRECTORY::HashBuckets, KdPrint, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MmNumberOfPagingFiles, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, NUMBER_HASH_BUCKETS, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, _EPROCESS::ObjectTable, ObMakeTemporaryObject(), ObpBeginTypeSpecificCallOut, ObpDeleteSymbolicLinkName(), ObpDirectoryObjectType, ObpEndTypeSpecificCallOut, ObpLockObject, ObpRootDirectoryObject, ObpShutdownCloseHandleProcedure(), ObpSymbolicLinkObjectType, ObpTypeDirectoryObject, ObpTypeObjectType, ObpUnlockObject, ObReferenceObjectByName(), _OBJECT_TYPE_INITIALIZER::PoolType, PsInitialSystemProcess, RtlInitUnicodeString(), _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, _OBJECT_TYPE_INITIALIZER::SecurityRequired, Status, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE::TypeList.
NTKERNELAPI NTSTATUS ObSwapObjectNames (IN HANDLE DirectoryHandle, IN HANDLE Handle1, IN HANDLE Handle2, IN ULONG Flags)
Definition at line 3209 of file obdir.c.
References DELETE, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_CREATE_OBJECT, DIRECTORY_CREATE_SUBDIRECTORY, exit(), FALSE, _OBJECT_HEADER::Flags, _OBP_LOOKUP_CONTEXT::HashIndex, _OBJECT_DIRECTORY_ENTRY::HashValue, INVALID_HASH_INDEX, KeGetPreviousMode, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpDeleteNameCheck(), ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpLinkDirectoryEntry(), ObpLockAllObjects(), ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpReferenceNameInfo(), ObpReleaseExclusiveNameLock(), ObpReleaseLookupContext(), ObpReleaseLookupContextObject(), ObpTryReferenceNameInfoExclusive(), ObpUnlinkDirectoryEntry(), ObpUnlockAllObjects(), ObReferenceObjectByHandle, Status, STATUS_LOCK_NOT_GRANTED, STATUS_OBJECT_NAME_COLLISION, STATUS_OBJECT_NAME_INVALID, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, _OBJECT_HEADER::Type, and UNREFERENCED_PARAMETER.
NTSTATUS ObValidateSecurityQuota (IN PVOID Object, IN ULONG NewSize)
Definition at line 1374 of file obse.c.
References _OBJECT_HEADER::Flags, NULL, OB_FLAG_DEFAULT_SECURITY_QUOTA, OBJECT_HEADER_TO_QUOTA_INFO(), OBJECT_TO_OBJECT_HEADER, PAGED_CODE, _OBJECT_HEADER::QuotaBlockCharged, SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, STATUS_QUOTA_EXCEEDED, and STATUS_SUCCESS.
Referenced by RtlpSetSecurityObject().
NTSTATUS ObWaitForSingleObject (IN HANDLE Handle, IN BOOLEAN Alertable, IN PLARGE_INTEGER Timeout OPTIONAL)
Definition at line 939 of file obwait.c.
References _OBJECT_TYPE::DefaultObject, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, FALSE, KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, PAGED_CODE, Status, STATUS_MUTANT_LIMIT_EXCEEDED, SYNCHRONIZE, _OBJECT_HEADER::Type, and UserRequest.
Variable Documentation
PKWIN32_CLOSEMETHOD_CALLOUT ExDesktopCloseProcedureCallout
Definition at line 29 of file win32.c.
Referenced by ExpWin32CloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_DELETEMETHOD_CALLOUT ExDesktopDeleteProcedureCallout
Definition at line 34 of file win32.c.
Referenced by ExpWin32DeleteProcedure(), and PsEstablishWin32Callouts().
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExDesktopOkToCloseProcedureCallout
Definition at line 32 of file win32.c.
Referenced by ExpWin32OkayToCloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_OPENMETHOD_CALLOUT ExDesktopOpenProcedureCallout
Definition at line 31 of file win32.c.
Referenced by ExpWin32OpenProcedure(), and PsEstablishWin32Callouts().
PKWIN32_CLOSEMETHOD_CALLOUT ExWindowStationCloseProcedureCallout
Definition at line 30 of file win32.c.
Referenced by ExpWin32CloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_DELETEMETHOD_CALLOUT ExWindowStationDeleteProcedureCallout
Definition at line 35 of file win32.c.
Referenced by ExpWin32DeleteProcedure(), and PsEstablishWin32Callouts().
PKWIN32_OKTOCLOSEMETHOD_CALLOUT ExWindowStationOkToCloseProcedureCallout
Definition at line 33 of file win32.c.
Referenced by ExpWin32OkayToCloseProcedure(), and PsEstablishWin32Callouts().
PKWIN32_OPENMETHOD_CALLOUT ExWindowStationOpenProcedureCallout
Definition at line 37 of file win32.c.
Referenced by ExpWin32OpenProcedure(), and PsEstablishWin32Callouts().
PKWIN32_PARSEMETHOD_CALLOUT ExWindowStationParseProcedureCallout
Definition at line 36 of file win32.c.
Referenced by ExpWin32ParseProcedure(), and PsEstablishWin32Callouts().
PDEVICE_MAP ObSystemDeviceMap
Definition at line 158 of file obinit.c.
Referenced by ObInheritDeviceMap(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceDeviceMap(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), and ObSetDirectoryDeviceMap().