Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/error.c File Reference
error.c File Reference
#include <ntrtlp.h>
#include "winerror.h"
#include "error.h"
Functions
NTSTATUS NTAPI RtlGetLastNtStatus (VOID)
LONG NTAPI RtlGetLastWin32Error (VOID)
ULONG RtlNtStatusToDosError (IN NTSTATUS Status)
ULONG RtlNtStatusToDosErrorNoTeb (IN NTSTATUS Status)
VOID NTAPI RtlRestoreLastWin32Error (LONG Win32Error)
VOID NTAPI RtlSetLastWin32Error (LONG Win32Error)
VOID NTAPI RtlSetLastWin32ErrorAndNtStatusFromNtStatus (NTSTATUS Status)
Function Documentation
NTSTATUS NTAPI RtlGetLastNtStatus (VOID)
Definition at line 188 of file error.c.
References NtCurrentTeb().
LONG NTAPI RtlGetLastWin32Error (VOID)
Definition at line 197 of file error.c.
References NtCurrentTeb().
ULONG RtlNtStatusToDosError (IN NTSTATUS Status)
Definition at line 43 of file error.c.
References except, EXCEPTION_EXECUTE_HANDLER, NtCurrentTeb(), RtlNtStatusToDosErrorNoTeb(), and Status.
Referenced by RtlSetLastWin32ErrorAndNtStatusFromNtStatus().
ULONG RtlNtStatusToDosErrorNoTeb (IN NTSTATUS Status)
Definition at line 80 of file error.c.
References _RUN_ENTRY::CodeSize, ERROR_MR_MID_NOT_FOUND, Index, RtlpRunTable, RtlpStatusTable, _RUN_ENTRY::RunLength, and Status.
Referenced by RtlNtStatusToDosError().
VOID NTAPI RtlRestoreLastWin32Error (LONG Win32Error)
Definition at line 231 of file error.c.
References NtCurrentTeb().
VOID NTAPI RtlSetLastWin32Error (LONG Win32Error)
Definition at line 218 of file error.c.
References NtCurrentTeb().
Referenced by RtlSetLastWin32ErrorAndNtStatusFromNtStatus().
VOID NTAPI RtlSetLastWin32ErrorAndNtStatusFromNtStatus (NTSTATUS Status)
Definition at line 206 of file error.c.
References RtlNtStatusToDosError(), and RtlSetLastWin32Error().