Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/wrtfault.c File Reference
wrtfault.c File Reference
#include "mi.h"
Functions
LOGICAL FASTCALL MiCopyOnWrite (IN PVOID FaultingAddress, IN PMMPTE PointerPte)
LOGICAL MiSetDirtyBit (IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN ULONG PfnHeld)
Function Documentation
LOGICAL FASTCALL MiCopyOnWrite (IN PVOID FaultingAddress, IN PMMPTE PointerPte)
Definition at line 24 of file wrtfault.c.
References _IMAGE_ENTRY_IN_SESSION::Address, ASSERT, _MMPFNENTRY::CacheAttribute, CONTAINING_RECORD, _MMPTE_HARDWARE::CopyOnWrite, _MMPFN::e1, FALSE, _LIST_ENTRY::Flink, _EPROCESS::ForkInProgress, _MMPTE::Hard, HYDRA_PROCESS, _MM_SESSION_SPACE::ImageList, _IMAGE_ENTRY_IN_SESSION::ImageLoading, _MM_SESSION_SPACE::ImageLoadingCount, InterlockedIncrement, KeCopyPage, KeGetCurrentPrcb(), LOCK_PFN, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_DISABLE_CACHING, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_COLOR_FROM_SESSION, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PTE_DIRTY, MI_MAKE_VALID_KERNEL_PTE, MI_PAGE_COLOR_PTE_PROCESS, MI_PFN_ELEMENT, MI_SET_ACCESSED_IN_PTE, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PAGE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiDecrementCloneBlockReference(), MiDecrementShareCount(), MiEnsureAvailablePageOrWait(), MiGetVirtualAddressMappedByPte, MiInitializeCopyOnWritePfn(), MiLocateCloneAddress, MiLocateWsle(), MiMapPageInHyperSpace(), MiNonCached, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiUnmapPageInHyperSpace, MiWaitForForkToComplete(), MiWriteCombined, MM_HIGH_LIMIT, MM_READWRITE, MM_SESSION_SPACE_WS_LOCK_ASSERT, MmAvailablePages, MmSessionBase, MmSessionSpace, MmWorkingSetList, NULL, PAGE_ALIGN, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), _MMPFN::PteAddress, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _MM_SESSION_SPACE::Vm, _MMSUPPORT::VmWorkingSetList, _MMPTE_HARDWARE::Write, and _MMPFN::WsIndex.
Referenced by MiProtectVirtualMemory(), MiSetProtectionOnSection(), and MmAccessFault().
LOGICAL MiSetDirtyBit (IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN ULONG PfnHeld)
Definition at line 382 of file wrtfault.c.
References _MMPFN::e1, FALSE, KeFillEntryTb, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_PFN_ELEMENT, MI_SET_ACCESSED_IN_PTE, MI_SET_MODIFIED, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiReleasePageFileSpace(), _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPFNENTRY::WriteInProgress.
Referenced by MmAccessFault().