Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/zone.c File Reference
zone.c File Reference
#include "exp.h"
Functions
NTSTATUS ExExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize)
NTSTATUS ExInitializeZone (__out PZONE_HEADER Zone, __in ULONG BlockSize, __inout PVOID InitialSegment, __in ULONG InitialSegmentSize)
NTSTATUS ExInterlockedExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize, __inout PKSPIN_LOCK Lock)
Function Documentation
NTSTATUS ExExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize)
Definition at line 129 of file zone.c.
References STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
Referenced by ExInterlockedExtendZone().
NTSTATUS ExInitializeZone (__out PZONE_HEADER Zone, __in ULONG BlockSize, __inout PVOID InitialSegment, __in ULONG InitialSegmentSize)
Definition at line 46 of file zone.c.
References DbgBreakPoint(), DbgPrint(), NULL, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS ExInterlockedExtendZone (__inout PZONE_HEADER Zone, __inout PVOID Segment, __in ULONG SegmentSize, __inout PKSPIN_LOCK Lock)
Definition at line 197 of file zone.c.
References ExAcquireSpinLock, ExExtendZone(), ExReleaseSpinLock, Status, and UNREFERENCED_PARAMETER.