Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/dir.c File Reference
dir.c File Reference
#include "iomgr.h"
Functions
NTSTATUS BuildQueryDirectoryIrp (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PVOID FileInformation, IN ULONG Length, IN FILE_INFORMATION_CLASS FileInformationClass, IN BOOLEAN ReturnSingleEntry, IN PUNICODE_STRING FileName OPTIONAL, IN BOOLEAN RestartScan, IN UCHAR MinorFunction, OUT BOOLEAN *SynchronousIo, OUT PDEVICE_OBJECT *DeviceObject, OUT PIRP *Irp, OUT PFILE_OBJECT *FileObject, OUT KPROCESSOR_MODE *RequestorMode)
NTSTATUS NtNotifyChangeDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in ULONG CompletionFilter, __in BOOLEAN WatchTree)
NTSTATUS NtQueryDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass, __in BOOLEAN ReturnSingleEntry, __in PUNICODE_STRING FileName OPTIONAL, __in BOOLEAN RestartScan)
Function Documentation
NTSTATUS BuildQueryDirectoryIrp (IN HANDLE FileHandle, IN HANDLE Event OPTIONAL, IN PIO_APC_ROUTINE ApcRoutine OPTIONAL, IN PVOID ApcContext OPTIONAL, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PVOID FileInformation, IN ULONG Length, IN FILE_INFORMATION_CLASS FileInformationClass, IN BOOLEAN ReturnSingleEntry, IN PUNICODE_STRING FileName OPTIONAL, IN BOOLEAN RestartScan, IN UCHAR MinorFunction, OUT BOOLEAN * SynchronousIo, OUT PDEVICE_OBJECT * DeviceObject, OUT PIRP * Irp, OUT PFILE_OBJECT * FileObject, OUT KPROCESSOR_MODE * RequestorMode)
Definition at line 48 of file dir.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _FILE_OBJECT::CompletionContext, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExFreePool(), ExRaiseStatus(), FALSE, FILE_LIST_DIRECTORY, FileBothDirectoryInformation, FileDirectoryInformation, FileFullDirectoryInformation, FileIdBothDirectoryInformation, FileIdFullDirectoryInformation, FileNamesInformation, _IO_STACK_LOCATION::FileObject, FileObjectIdInformation, FileQuotaInformation, FileReparsePointInformation, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopMarkApcRoutineIfAsyncronousIo32, IopQuerySetAlignmentRequirement, IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_INPUT_OPERATION, IRP_MJ_DIRECTORY_CONTROL, IRP_MN_QUERY_DIRECTORY, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, _UNICODE_STRING::Length, _IO_STACK_LOCATION::MajorFunction, MAXIMUM_FILENAME_LENGTH, _UNICODE_STRING::MaximumLength, _IO_STACK_LOCATION::MinorFunction, MmProbeAndLockPages(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentProcessByThread, PsGetCurrentThread(), RtlCopyMemory, SL_RESTART_SCAN, SL_RETURN_SINGLE_ENTRY, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
Referenced by NtQueryDirectoryFile().
NTSTATUS NtNotifyChangeDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in ULONG CompletionFilter, __in BOOLEAN WatchTree)
Definition at line 859 of file dir.c.
References ARGUMENT_PRESENT, _FILE_OBJECT::CompletionContext, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, FILE_LIST_DIRECTORY, FILE_NOTIFY_VALID_MASK, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopMarkApcRoutineIfAsyncronousIo32, IopSynchronousServiceTail(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_DIRECTORY_CONTROL, IRP_MN_NOTIFY_CHANGE_DIRECTORY, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, MmProbeAndLockPages(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), SL_WATCH_TREE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _ETHREAD::Tcb, and TRUE.
NTSTATUS NtQueryDirectoryFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID FileInformation, __in ULONG Length, __in FILE_INFORMATION_CLASS FileInformationClass, __in BOOLEAN ReturnSingleEntry, __in PUNICODE_STRING FileName OPTIONAL, __in BOOLEAN RestartScan)
Definition at line 716 of file dir.c.
References BuildQueryDirectoryIrp(), IopSynchronousServiceTail(), IRP_MN_QUERY_DIRECTORY, OtherTransfer, PAGED_CODE, PIRP, STATUS_SUCCESS, and TRUE.