Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cminit.c File Reference
cminit.c File Reference
#include "cmp.h"
Functions
LOGICAL CmpDestroyHive (IN PHHIVE Hive, IN HCELL_INDEX Cell)
NTSTATUS CmpInitializeHive (PCMHIVE *CmHive, ULONG OperationType, ULONG HiveFlags, ULONG FileType, PVOID HiveData OPTIONAL, HANDLE Primary, HANDLE Log, HANDLE External, PUNICODE_STRING FileName OPTIONAL, ULONG CheckFlags)
NTSTATUS CmpOpenFileWithExtremePrejudice (OUT PHANDLE Primary, IN POBJECT_ATTRIBUTES Obja, IN ULONG IoFlags, IN ULONG AttributeFlags)
NTSTATUS CmpOpenHiveFiles (PUNICODE_STRING BaseName, PWSTR Extension OPTIONAL, PHANDLE Primary, PHANDLE Secondary, PULONG PrimaryDisposition, PULONG SecondaryDisposition, BOOLEAN CreateAllowed, BOOLEAN MarkAsSystemHive, BOOLEAN NoBuffering, OUT OPTIONAL PULONG ClusterSize)
Variables
LIST_ENTRY CmpHiveListHead
PCMHIVE CmpMasterHive
Function Documentation
LOGICAL CmpDestroyHive (IN PHHIVE Hive, IN HCELL_INDEX Cell)
Definition at line 803 of file cminit.c.
References ASSERT, CmpFreeKeyByCell(), CmpLockHiveFlusherExclusive, CmpLockHiveListExclusive, CmpRemoveEntryList, CmpUnlockHiveFlusher, CmpUnlockHiveList, FALSE, FIELD_OFFSET, HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyNode, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, Status, TRUE, and _CELL_DATA::u.
Referenced by CmUnloadKey().
NTSTATUS CmpInitializeHive (PCMHIVE * CmHive, ULONG OperationType, ULONG HiveFlags, ULONG FileType, PVOID HiveData OPTIONAL, HANDLE Primary, HANDLE Log, HANDLE External, PUNICODE_STRING FileName OPTIONAL, ULONG CheckFlags)
Definition at line 511 of file cminit.c.
References ARGUMENT_PRESENT, ASSERT, ASSERT_PASSIVE_LEVEL, _LIST_ENTRY::Blink, _UNICODE_STRING::Buffer, _FILE_FS_SIZE_INFORMATION::BytesPerSector, _CMHIVE::CellRemapArray, CM_DONT_ADD_TO_HIVE_LIST, CmCheckRegistry(), CmKdPrintEx, CML_BUGCHECK, CML_INIT, CmpAllocate(), CmpCheckForOrphanedKcbs, CmpDestroyHiveViewList(), CmpDestroySecurityCache(), CmpDropFileObjectForHive(), CmpFileFlush(), CmpFileRead(), CmpFileSetSize(), CmpFileWrite(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpInitHiveViewList(), CmpInitSecurityCache(), CmpLockHiveListExclusive, CmpShareSystemHives, CmpUnJoinClassOfTrust, CmpUnlockHiveList, _CMHIVE::CreatorOwner, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, ExAllocatePoolWithTag, ExInitializePushLock(), ExInitializeResourceLite(), FALSE, FileFsSizeInformation, _CMHIVE::FileFullPath, _CMHIVE::FileHandles, _CMHIVE::FileObject, _CMHIVE::FileUserName, _CMHIVE::Flags, _LIST_ENTRY::Flink, _CMHIVE::FlushCount, _CMHIVE::FlusherLock, _CMHIVE::Frozen, _CMHIVE::GrowOffset, _CMHIVE::GrowOnlyMode, HBLOCK_SIZE, HFILE_TYPE_EXTERNAL, HFILE_TYPE_LOG, HFILE_TYPE_MAX, HFILE_TYPE_PRIMARY, HINIT_FILE, HINIT_MAPFILE, HINIT_MEMORY, HINIT_MEMORY_INPLACE, _CMHIVE::Hive, HIVE_HAS_BEEN_FREED, HIVE_VOLATILE, _HHIVE::HiveFlags, _CMHIVE::HiveList, _CMHIVE::HiveLock, HSECTOR_SIZE, HvFreeHive(), HvInitializeHive(), HvpCleanMap(), HvpFreeHiveFreeDisplay(), InitializeListHead(), InsertTailList(), _CMHIVE::KcbConvertListHead, KeInitializeGuardedMutex(), _CMHIVE::KnodeConvertListHead, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NonPagedPool, _CMHIVE::NotifyList, NT_SUCCESS, NULL, _CMHIVE::RootKcb, _CMHIVE::SecurityLock, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, TRUE, _CMHIVE::TrustClassEntry, _CMHIVE::UnloadEvent, _CMHIVE::UnloadWorkItem, _CMHIVE::ViewLock, _CMHIVE::WriterLock, and ZwQueryVolumeInformationFile().
Referenced by CmInitSystem1(), CmpCreateTemporaryHive(), CmpInitHiveFromFile(), CmpInitializeSystemHive(), CmpLoadHiveVolatile(), and CmRestoreKey().
NTSTATUS CmpOpenFileWithExtremePrejudice (OUT PHANDLE Primary, IN POBJECT_ATTRIBUTES Obja, IN ULONG IoFlags, IN ULONG AttributeFlags)
Definition at line 868 of file cminit.c.
References ASSERT_PASSIVE_LEVEL, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FILE_ATTRIBUTE_READONLY, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_READ_DATA, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_ATTRIBUTES, FILE_WRITE_DATA, _FILE_BASIC_INFORMATION::FileAttributes, FileBasicInformation, Handle, NT_SUCCESS, NULL, RtlZeroMemory, Status, ZwClose(), ZwCreateFile(), ZwOpenFile(), ZwQueryAttributesFile(), and ZwSetInformationFile().
Referenced by CmpOpenHiveFiles().
NTSTATUS CmpOpenHiveFiles (PUNICODE_STRING BaseName, PWSTR Extension OPTIONAL, PHANDLE Primary, PHANDLE Secondary, PULONG PrimaryDisposition, PULONG SecondaryDisposition, BOOLEAN CreateAllowed, BOOLEAN MarkAsSystemHive, BOOLEAN NoBuffering, OUT OPTIONAL PULONG ClusterSize)
Definition at line 45 of file cminit.c.
References _wcsnicmp(), ARGUMENT_PRESENT, ASSERT_PASSIVE_LEVEL, _UNICODE_STRING::Buffer, _FILE_FS_SIZE_INFORMATION::BytesPerSector, CmKdPrintEx, CML_BUGCHECK, CmpCreateEvent(), CmpMiniNTBoot, CmpOpenFileWithExtremePrejudice(), CmpShareSystemHives, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, ExAllocatePool, Executive, ExFreePool(), FALSE, FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_NORMAL, FILE_CREATED, FILE_NO_COMPRESSION, FILE_NO_INTERMEDIATE_BUFFERING, FILE_OPEN, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_IF, FILE_RANDOM_ACCESS, FILE_READ_DATA, FILE_SHARE_READ, FILE_SUPERSEDE, FILE_WRITE_DATA, FileFsSizeInformation, FileStandardInformation, FSCTL_MARK_AS_SYSTEM_HIVE, FSCTL_SET_COMPRESSION, HBLOCK_SIZE, HSECTOR_SIZE, _IO_STATUS_BLOCK::Information, InitializeObjectAttributes, KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PagedPool, RtlAppendStringToString(), RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, STATUS_ACCESS_DENIED, STATUS_CANNOT_LOAD_REGISTRY_FILE, STATUS_INVALID_DEVICE_REQUEST, STATUS_NO_MEMORY, STATUS_PENDING, STATUS_SUCCESS, TRUE, wcslen(), ZwClose(), ZwCreateFile(), ZwFsControlFile(), ZwQueryInformationFile(), and ZwQueryVolumeInformationFile().
Referenced by CmpInitHiveFromFile(), and CmpLoadHiveThread().
Variable Documentation
LIST_ENTRY CmpHiveListHead
Definition at line 312 of file cmdat.c.
PCMHIVE CmpMasterHive
Definition at line 305 of file cmdat.c.