Windows Research Kernel v1.2: C:/Windows Research Kernel/se/privileg.c File Reference
privileg.c File Reference
#include "pch.h"
Functions
NTSTATUS NtPrivilegeCheck (__in HANDLE ClientToken, __inout PPRIVILEGE_SET RequiredPrivileges, __out PBOOLEAN Result)
BOOLEAN SeCheckPrivilegedObject (__in LUID PrivilegeValue, __in HANDLE ObjectHandle, __in ACCESS_MASK DesiredAccess, __in KPROCESSOR_MODE PreviousMode)
BOOLEAN SepPrivilegeCheck (IN PTOKEN Token, IN OUT PLUID_AND_ATTRIBUTES RequiredPrivileges, IN ULONG RequiredPrivilegeCount, IN ULONG PrivilegeSetControl, IN KPROCESSOR_MODE PreviousMode)
BOOLEAN SePrivilegeCheck (__inout PPRIVILEGE_SET RequiredPrivileges, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE AccessMode)
BOOLEAN SeSinglePrivilegeCheck (__in LUID PrivilegeValue, __in KPROCESSOR_MODE PreviousMode)
Function Documentation
NTSTATUS NtPrivilegeCheck (__in HANDLE ClientToken, __inout PPRIVILEGE_SET RequiredPrivileges, __out PBOOLEAN Result)
Definition at line 228 of file privileg.c.
References ANYSIZE_ARRAY, except, EXCEPTION_EXECUTE_HANDLER, _TOKEN::ImpersonationLevel, IsValidElementCount, KeGetPreviousMode, leave, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, ProbeForWrite(), ProbeForWriteBoolean, ProbeForWriteSmallStructure(), RtlCopyMemory, SeCaptureLuidAndAttributesArray(), SecurityIdentification, SepPrivilegeCheck(), SeReleaseLuidAndAttributesArray(), SeTokenObjectType, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TOKEN_QUERY, TokenImpersonation, _TOKEN::TokenType, TRUE, and UserMode.
BOOLEAN SeCheckPrivilegedObject (__in LUID PrivilegeValue, __in HANDLE ObjectHandle, __in ACCESS_MASK DesiredAccess, __in KPROCESSOR_MODE PreviousMode)
Definition at line 496 of file privileg.c.
References _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, KernelMode, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, SeCaptureSubjectContext(), SePrivilegeCheck(), SePrivilegeObjectAuditAlarm(), and SeReleaseSubjectContext().
Referenced by NtSetInformationJobObject(), NtSetInformationProcess(), NtSetInformationThread(), and PspSetPrimaryToken().
BOOLEAN SepPrivilegeCheck (IN PTOKEN Token, IN OUT PLUID_AND_ATTRIBUTES RequiredPrivileges, IN ULONG RequiredPrivilegeCount, IN ULONG PrivilegeSetControl, IN KPROCESSOR_MODE PreviousMode)
Definition at line 34 of file privileg.c.
References _LUID_AND_ATTRIBUTES::Attributes, FALSE, KernelMode, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, PRIVILEGE_SET_ALL_NECESSARY, RtlEqualLuid, SE_PRIVILEGE_ENABLED, SE_PRIVILEGE_USED_FOR_ACCESS, SepAcquireTokenReadLock, SepReleaseTokenReadLock, and TRUE.
Referenced by NtPrivilegeCheck(), SeCheckAuditPrivilege(), SePrivilegeCheck(), and SepSinglePrivilegeCheck().
BOOLEAN SePrivilegeCheck (__inout PPRIVILEGE_SET RequiredPrivileges, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE AccessMode)
Definition at line 155 of file privileg.c.
References EffectiveToken, FALSE, NULL, PAGED_CODE, SecurityImpersonation, SepPrivilegeCheck(), and Status.
Referenced by IopCheckBackupRestorePrivilege(), ObpIncrementHandleCount(), PspSinglePrivCheck(), RtlpNewSecurityObject(), SeCheckPrivilegedObject(), and SeSinglePrivilegeCheck().
BOOLEAN SeSinglePrivilegeCheck (__in LUID PrivilegeValue, __in KPROCESSOR_MODE PreviousMode)
Definition at line 428 of file privileg.c.
References _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, KernelMode, _LUID_AND_ATTRIBUTES::Luid, NULL, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, SeCaptureSubjectContext(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), and SeReleaseSubjectContext().
Referenced by CmpDoCreate(), CmpDoOpen(), CmpRefreshHive(), ExpRaiseHardError(), IopUnloadDriver(), MiMapViewOfImageSection(), MmCreateSection(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtCompactKeys(), NtCompressKey(), NtCreatePagingFile(), NtCreateProfile(), NtGetNextProcess(), NtGetNextThread(), NtLoadDriver(), NtLoadKeyEx(), NtLockRegistryKey(), NtLockVirtualMemory(), NtMakePermanentObject(), NtOpenProcess(), NtOpenThread(), NtQueryInformationToken(), NtQueryOpenSubKeysEx(), NtReplaceKey(), NtRestoreKey(), NtSaveKey(), NtSaveKeyEx(), NtSaveMergedKeys(), NtSetDefaultHardErrorPort(), NtSetInformationJobObject(), NtSetInformationObject(), NtSetInformationProcess(), NtSetInformationThread(), NtSetInformationToken(), NtSetSystemInformation(), NtUnloadKey2(), NtUnloadKeyEx(), NtUnlockVirtualMemory(), ObCreateObject(), ObpLookupObjectName(), PerfInfoStartLog(), PspSetQuotaLimits(), SepCreateToken(), and SepValidOwnerSubjectContext().