Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/sessload.c File Reference
sessload.c File Reference
#include "mi.h"
Functions
LOGICAL MiMarkImageInSystem (IN PCONTROL_AREA ControlArea)
VOID MiRemoveImageSessionWide (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry OPTIONAL, IN PVOID BaseAddress, IN ULONG_PTR NumberOfBytes)
NTSTATUS MiSessionInsertImage (IN PVOID BaseAddress)
PIMAGE_ENTRY_IN_SESSION MiSessionLookupImage (IN PVOID BaseAddress)
NTSTATUS MiSessionRemoveImage (IN PVOID BaseAddress)
NTSTATUS MiSessionRemoveImage (PVOID BaseAddr)
VOID MiSessionUnloadAllImages (VOID)
VOID MiSessionWideInitializeAddresses (VOID)
NTSTATUS MiSessionWideReserveImageAddress (IN PSECTION Section, OUT PVOID *AssignedAddress, OUT PSECTION *NewSectionPointer)
NTSTATUS MiShareSessionImage (IN PVOID MappedBase, IN PSECTION Section)
Variables
ULONG MiSessionUserCollisions
RTL_BITMAP MiSessionWideVaBitMap
Function Documentation
LOGICAL MiMarkImageInSystem (IN PCONTROL_AREA ControlArea)
Definition at line 56 of file sessload.c.
References ASSERT, FALSE, LOCK_PFN, Status, TRUE, and UNLOCK_PFN.
Referenced by MiSessionWideReserveImageAddress().
VOID MiRemoveImageSessionWide (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry OPTIONAL, IN PVOID BaseAddress, IN ULONG_PTR NumberOfBytes)
Definition at line 1199 of file sessload.c.
References ASSERT, MiSessionImageStart, MiSessionRemoveImage(), MmIsAddressValid(), MmSessionSpace, NULL, PAGE_SHIFT, PAGED_CODE, RtlAreBitsSet(), RtlClearBits(), SYSLOAD_LOCK_OWNED_BY_ME, and TRUE.
Referenced by MiLoadImageSection(), and MmUnloadSystemImage().
NTSTATUS MiSessionInsertImage (IN PVOID BaseAddress)
Definition at line 355 of file sessload.c.
References _IMAGE_ENTRY_IN_SESSION::Address, CONTAINING_RECORD, ExAllocatePoolWithTag, ExFreePool(), _LIST_ENTRY::Flink, _MM_SESSION_SPACE::GlobalVirtualAddress, _IMAGE_ENTRY_IN_SESSION::ImageCountInThisSession, _MM_SESSION_SPACE::ImageList, InsertTailList(), _IMAGE_ENTRY_IN_SESSION::Link, LOCK_WORKING_SET, MM_BUMP_SESSION_FAILURES, MM_SESSION_FAILURE_NO_NONPAGED_POOL, MmSessionSpace, NonPagedPool, NULL, PAGED_CODE, PsGetCurrentThread(), RtlZeroMemory, STATUS_ALREADY_COMMITTED, STATUS_NO_MEMORY, STATUS_SUCCESS, SYSLOAD_LOCK_OWNED_BY_ME, UNLOCK_WORKING_SET, and _MM_SESSION_SPACE::Vm.
Referenced by MiSessionWideReserveImageAddress(), and MmLoadSystemImage().
PIMAGE_ENTRY_IN_SESSION MiSessionLookupImage (IN PVOID BaseAddress)
Definition at line 530 of file sessload.c.
References _IMAGE_ENTRY_IN_SESSION::Address, CONTAINING_RECORD, _LIST_ENTRY::Flink, _MM_SESSION_SPACE::ImageList, MmSessionSpace, NULL, and SYSLOAD_LOCK_OWNED_BY_ME.
Referenced by MiSessionProcessGlobalSubsections(), MiSessionWideReserveImageAddress(), MiShareSessionImage(), and MmUnloadSystemImage().
NTSTATUS MiSessionRemoveImage (IN PVOID BaseAddress)
Referenced by MiRemoveImageSessionWide(), and MiSessionWideReserveImageAddress().
NTSTATUS MiSessionRemoveImage (PVOID BaseAddr)
Definition at line 452 of file sessload.c.
References _IMAGE_ENTRY_IN_SESSION::Address, ASSERT, CONTAINING_RECORD, ExFreePool(), _LIST_ENTRY::Flink, _MM_SESSION_SPACE::GlobalVirtualAddress, _MM_SESSION_SPACE::ImageList, _IMAGE_ENTRY_IN_SESSION::ImageLoading, _MM_SESSION_SPACE::ImageLoadingCount, InterlockedDecrement, LOCK_WORKING_SET, MmSessionSpace, PAGED_CODE, PsGetCurrentThread(), RemoveEntryList(), STATUS_NOT_FOUND, STATUS_SUCCESS, SYSLOAD_LOCK_OWNED_BY_ME, TRUE, UNLOCK_WORKING_SET, and _MM_SESSION_SPACE::Vm.
VOID MiSessionUnloadAllImages (VOID)
Definition at line 583 of file sessload.c.
References _IMAGE_ENTRY_IN_SESSION::Address, ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _MM_SESSION_SPACE::ImageList, MiLookupDataTableEntry(), MmSessionSpace, MmUnloadSystemImage(), _MM_SESSION_SPACE::ReferenceCount, and Status.
Referenced by MiDereferenceSessionFinal().
VOID MiSessionWideInitializeAddresses (VOID)
Definition at line 667 of file sessload.c.
References ExAllocatePoolWithTag, INSTALL_MORE_MEMORY, KeBugCheckEx(), MiSessionImageEnd, MiSessionImageStart, MmHighestPhysicalPage, MmLowestPhysicalPage, MmNumberOfPhysicalPages, NULL, PAGE_SHIFT, PagedPool, RtlClearAllBits(), and RtlInitializeBitMap().
Referenced by MmInitSystem().
NTSTATUS MiSessionWideReserveImageAddress (IN PSECTION Section, OUT PVOID * AssignedAddress, OUT PSECTION * NewSectionPointer)
Definition at line 720 of file sessload.c.
References ASSERT, BYTE_OFFSET, _SEGMENT::ControlArea, Count, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CONTROL_AREA::Flags, _MMSUBSECTION_FLAGS::GlobalMemory, _MMSECTION_FLAGS::GlobalOnlyPerSession, _IMAGE_ENTRY_IN_SESSION::GlobalSubs, _MMPTE::Hard, _IMAGE_ENTRY_IN_SESSION::ImageLoading, _MM_SESSION_SPACE::ImageLoadingCount, _MMSECTION_FLAGS::ImageMappedInSystemSpace, InitializeObjectAttributes, InterlockedIncrement, KeDelayExecutionThread(), KernelMode, MI_DELETE_FLUSH_TB, MI_INCREMENT_RESIDENT_AVAILABLE, MiDeleteSystemPageableVm(), MiGetPteAddress, MiMarkImageInSystem(), MiSessionImageEnd, MiSessionImageStart, MiSessionInsertImage(), MiSessionLookupImage(), MiSessionRemoveImage(), MM_BUMP_SESSION_FAILURES, MM_NOACCESS, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE, MM_SESSION_FAILURE_IMAGE_ZOMBIE, MM_SESSION_FAILURE_NO_IMAGE_VA_SPACE, MmIsAddressValid(), MmMapViewInSessionSpace(), MmMapViewInSystemSpace(), MmSectionObjectType, MmSessionSpace, MmShortTime, MmUnmapViewInSessionSpace(), MmUnmapViewInSystemSpace(), _SUBSECTION::NextSubsection, NO_BITS_FOUND, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGE_EXECUTE_READWRITE, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PagedPool, _MMPTE_SOFTWARE::Protection, _MMSUBSECTION_FLAGS::Protection, _SESSION_GLOBAL_SUBSECTION_INFO::Protection, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _SESSION_GLOBAL_SUBSECTION_INFO::PteCount, _SESSION_GLOBAL_SUBSECTION_INFO::PteIndex, _SUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, _MMSECTION_FLAGS::Rom, RtlAreBitsClear(), RtlAreBitsSet(), RtlClearBits(), RtlCopyMemory, RtlFindClearBitsAndSet(), RtlSetBits(), SEC_COMMIT, SECTION_ALL_ACCESS, SECTION_MAP_EXECUTE, _CONTROL_AREA::Segment, _MMPTE::Soft, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, SYSLOAD_LOCK_OWNED_BY_ME, TRUE, _MMPTE::u, _CONTROL_AREA::u, _SUBSECTION::u, _MMPTE_HARDWARE::Valid, ZwClose(), and ZwCreateSection().
Referenced by MiLoadImageSection().
NTSTATUS MiShareSessionImage (IN PVOID MappedBase, IN PSECTION Section)
Definition at line 138 of file sessload.c.
References ASSERT, BYTE_OFFSET, _MM_SESSION_SPACE::CommittedPages, _SEGMENT::ControlArea, FALSE, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, InterlockedExchangeAddSizeT, _IMAGE_ENTRY_IN_SESSION::LastAddress, _MMPTE::Long, MiAddMappedPtes(), MiChargeCommitment(), MiCheckPurgeAndUpMapCount(), MiDereferenceControlArea(), MiGetPteAddress, MiReturnCommitment, MiSessionCommitPageTables(), MiSessionLookupImage(), MM_BUMP_SESS_COUNTER, MM_BUMP_SESSION_FAILURES, MM_DBG_COMMIT_SESSION_SHARED_IMAGE, MM_DBG_SESSION_SYSMAPPED_PAGES_ALLOC, MM_DBG_SESSION_SYSMAPPED_PAGES_COMMITTED, MM_SESSION_FAILURE_NO_COMMIT, MM_TRACK_COMMIT, MmIsAddressValid(), MmSessionSpace, NT_SUCCESS, NULL, PAGE_SHIFT, PAGED_CODE, _IMAGE_ENTRY_IN_SESSION::PrototypePtes, _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, SYSLOAD_LOCK_OWNED_BY_ME, TRUE, _MMPTE::u, and _CONTROL_AREA::u.
Referenced by MiLoadImageSection().
Variable Documentation
ULONG MiSessionUserCollisions
Definition at line 36 of file sessload.c.
RTL_BITMAP MiSessionWideVaBitMap
Definition at line 34 of file sessload.c.