Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/qsea.c File Reference
qsea.c File Reference
#include "iomgr.h"
Macros
#define GET_OFFSET_LENGTH(CurrentEa, EaBase)
Functions
NTSTATUS NtQueryEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(EaListLength) PVOID EaList, __in ULONG EaListLength, __in_opt PULONG EaIndex, __in BOOLEAN RestartScan)
NTSTATUS NtSetEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
Macro Definition Documentation
#define GET_OFFSET_LENGTH (CurrentEa, EaBase)
Value:
(\
    (ULONG) ((PCHAR) CurrentEa - (PCHAR) EaBase) )
Referenced by NtQueryEaFile().
Function Documentation
NTSTATUS NtQueryEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __out_bcount(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in_bcount_opt(EaListLength) PVOID EaList, __in ULONG EaListLength, __in_opt PULONG EaIndex , __in BOOLEAN RestartScan)
Definition at line 26 of file qsea.c.
References ARGUMENT_PRESENT, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_GET_EA_INFORMATION::EaNameLength, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FIELD_OFFSET, FILE_READ_EA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, GET_OFFSET_LENGTH, IoAllocateIrp(), IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_QUERY_EA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), _FILE_GET_EA_INFORMATION::NextEntryOffset, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUlong, ProbeForRead, ProbeForWrite(), ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, SL_INDEX_SPECIFIED, SL_RESTART_SCAN, SL_RETURN_SINGLE_ENTRY, STATUS_EA_LIST_INCONSISTENT, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.
NTSTATUS NtSetEaFile (__in HANDLE FileHandle, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length)
Definition at line 645 of file qsea.c.
References DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, ExAllocatePool, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), FALSE, FILE_WRITE_EA, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_SYNCHRONOUS_IO, IoAllocateIrp(), IoAllocateMdl(), IoCheckEaBufferValidity(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopExceptionCleanup(), IopSynchronousApiServiceTail(), IopSynchronousServiceTail(), IoReadAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_MJ_SET_EA, IRP_SYNCHRONOUS_API, KeClearEvent(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, OtherTransfer, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, ProbeForRead, ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, SynchronizationEvent, _ETHREAD::Tcb, and TRUE.