Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmquery.c File Reference
cmquery.c File Reference
#include "cmp.h"
Functions
NTSTATUS CmpQueryKeyName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Function Documentation
NTSTATUS CmpQueryKeyName (IN PVOID Object, IN BOOLEAN HasObjectName, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 26 of file cmquery.c.
References ASSERT_KCB_LOCKED, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CmKdPrintEx, CML_PARSE, CmpConstructName(), CmpLockKCBShared, CmpLockRegistry(), CmpUnlockKCB, CmpUnlockRegistry(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, ExFreePoolWithTag, FALSE, _UNICODE_STRING::Length, NULL, PROTECTED_POOL, RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_KEY_DELETED, STATUS_SUCCESS, TRUE, UNICODE_NULL, and UNREFERENCED_PARAMETER.
Referenced by CmpCreateObjectTypes().