Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/i386/debug3.c File Reference
debug3.c File Reference
#include "stdarg.h"
#include "stdio.h"
#include "string.h"
#include "ntrtlp.h"
Functions
NTSTATUS DebugPrint (IN PSTRING Output, IN ULONG ComponentId, IN ULONG Level)
ULONG DebugPrompt (IN PSTRING Output, IN PSTRING Input)
NTSTATUS DebugService (ULONG ServiceClass, PVOID Arg1, PVOID Arg2, PVOID Arg3, PVOID Arg4)
VOID DebugService2 (PVOID Arg1, PVOID Arg2, ULONG ServiceClass)
Function Documentation
NTSTATUS DebugPrint (IN PSTRING Output, IN ULONG ComponentId, IN ULONG Level)
Definition at line 161 of file debug3.c.
References BREAKPOINT_PRINT, and DebugService().
Referenced by vDbgPrintExWithPrefixInternal().
ULONG DebugPrompt (IN PSTRING Output, IN PSTRING Input)
Definition at line 176 of file debug3.c.
References BREAKPOINT_PROMPT, and DebugService().
Referenced by DbgPrompt().
NTSTATUS DebugService (ULONG ServiceClass, PVOID Arg1, PVOID Arg2, PVOID Arg3, PVOID Arg4)
Definition at line 38 of file debug3.c.
Referenced by DebugPrint(), DebugPrompt(), and KiDispatchException().
VOID DebugService2 (PVOID Arg1, PVOID Arg2, ULONG ServiceClass)
Definition at line 100 of file debug3.c.
Referenced by DbgCommandString(), DbgLoadImageSymbols(), and DbgUnLoadImageSymbols().