Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/allproc.c File Reference
allproc.c File Reference
#include "ki.h"
#include "pool.h"
Macros
#define ROUNDUP64(x) (((x) + 63) & ~63)
Functions
VOID KeStartAllProcessors (VOID)
VOID KiCopyDescriptorMemory (IN PKDESCRIPTOR Source, IN PKDESCRIPTOR Destination, IN PVOID Base)
VOID KiSetDescriptorBase (IN USHORT Selector, IN PKGDTENTRY64 GdtBase, IN PVOID Base)
Variables
ULONG KeRegisteredProcessors
ULONG KiBarrierWait = 0
KNODE KiNodeInit [MAXIMUM_CCNUMA_NODES]
PHALNUMAQUERYPROCESSORNODE KiQueryProcessorNode
Macro Definition Documentation
#define ROUNDUP64 (x) (((x) + 63) & ~63)
Definition at line 29 of file allproc.c.
Referenced by KeStartAllProcessors().
Function Documentation
VOID KeStartAllProcessors (VOID)
Definition at line 82 of file allproc.c.
References AFFINITY_MASK, _DESCRIPTOR::Base, _KPROCESSOR_STATE::ContextFrame, _KSPECIAL_REGISTERS::Cr0, _KSPECIAL_REGISTERS::Cr3, _KSPECIAL_REGISTERS::Cr4, DOUBLE_FAULT_STACK_SIZE, _CONTEXT::EFlags, ExAllocatePoolWithTag, ExCreatePoolTagTable(), ExDeletePoolTagTable(), FALSE, _KSPECIAL_REGISTERS::Gdtr, HalStartNextProcessor(), _KSPECIAL_REGISTERS::Idtr, Index, IPI_FLUSH_SINGLE, KeActiveProcessors, KeAdjustInterruptTime(), KeBugCheckEx(), KeGetCurrentPrcb(), KeGetPcr(), KeLoaderBlock, KeLowerIrql, KeNodeBlock, KeNumberNodes, KeNumberProcessors, KeNumprocSpecified, KeRaiseIrqlToSynchLevel(), KeRegisteredProcessors, _LOADER_PARAMETER_BLOCK::KernelStack, KeYieldProcessor, KiBarrierWait, KiCopyDescriptorMemory(), KiIpiSendRequest(), KiLogicalProcessors, KiNode0, KiNodeInit, KiPrefetchRetry, KiProcessorBlock, KiQueryProcessorNode, KiSetDescriptorBase(), KiSystemStartup(), _DESCRIPTOR::Limit, _LOADER_PARAMETER_BLOCK::LoadOptions, MAXIMUM_CCNUMA_NODES, MAXIMUM_PROCESSORS, _KPRCB::MHz, MmAllocateIndependentPages(), MmCreateKernelStack(), MmDeleteKernelStack(), MmFreeIndependentPages(), MmSecondaryColorMask, _KPRCB::NodeColor, _KPRCB::NodeShiftedColor, NonPagedPool, NT_SUCCESS, NULL, _KPRCB::Number, _KPRCB::ParentNode, PHASE1_INITIALIZATION_FAILED, _LOADER_PARAMETER_BLOCK::Prcb, _KPCR::Prcb, _KPRCB::ProcessorState, ROUNDUP64, RPL_MASK, RtlZeroMemory, _KPRCB::SecondaryColorMask, _CONTEXT::SegCs, _CONTEXT::SegDs, _CONTEXT::SegEs, _CONTEXT::SegFs, _CONTEXT::SegGs, _CONTEXT::SegSs, _KPROCESSOR_STATE::SpecialRegisters, strstr(), _LOADER_PARAMETER_BLOCK::Thread, and _KSPECIAL_REGISTERS::Tr.
VOID KiCopyDescriptorMemory (IN PKDESCRIPTOR Source, IN PKDESCRIPTOR Destination, IN PVOID Base)
Definition at line 637 of file allproc.c.
References RtlCopyMemory.
Referenced by KeStartAllProcessors().
VOID KiSetDescriptorBase (IN USHORT Selector, IN PKGDTENTRY64 GdtBase, IN PVOID Base)
Definition at line 599 of file allproc.c.
Referenced by KeStartAllProcessors().
Variable Documentation
ULONG KeRegisteredProcessors
Definition at line 78 of file allproc.c.
Referenced by KeStartAllProcessors().
ULONG KiBarrierWait = 0
Definition at line 77 of file allproc.c.
Referenced by KeStartAllProcessors().
KNODE KiNodeInit[MAXIMUM_CCNUMA_NODES]
Definition at line 69 of file allproc.c.
Referenced by KeStartAllProcessors(), KiAllProcessorsStarted(), and KiInitializeKernel().
PHALNUMAQUERYPROCESSORNODE KiQueryProcessorNode
Definition at line 58 of file allproc.c.
Referenced by KeNumaInitialize(), and KeStartAllProcessors().