Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/dmpaddr.c File Reference
dmpaddr.c File Reference
#include "mi.h"
Macros
#define MI_INCREMENT_IDENTIFY_COUNTER(x)
#define MI_MAXIMUM_PFNID_RUN 4096
#define PFN_ID_BUFFERS 128
Functions
VOID FASTCALL MiIdentifyPfn (IN PMMPFN Pfn1, OUT PMMPFN_IDENTITY PfnIdentity)
VOID MiSnapCopyMemory (IN PVOID Destination, IN PFN_NUMBER PageFrameIndex, IN SIZE_T NumberOfBytes)
NTSTATUS MmIdentifyPhysicalMemory (VOID)
NTSTATUS MmMemoryUsage (IN PVOID Buffer, IN ULONG Size, IN ULONG Type, OUT PULONG OutLength)
NTSTATUS MmPerfSnapShotValidPhysicalMemory (VOID)
Variables
PFN_NUMBER MiEndOfInitialPoolFrame
PFN_NUMBER MiStartOfInitialPoolFrame
PMMPTE MmSystemPtesEnd [MaximumPtePoolTypes]
Macro Definition Documentation
#define MI_INCREMENT_IDENTIFY_COUNTER (x)
Definition at line 47 of file dmpaddr.c.
Referenced by MiIdentifyPfn().
#define MI_MAXIMUM_PFNID_RUN 4096
Definition at line 592 of file dmpaddr.c.
Referenced by MmPerfSnapShotValidPhysicalMemory().
#define PFN_ID_BUFFERS 128
Definition at line 740 of file dmpaddr.c.
Referenced by MmIdentifyPhysicalMemory().
Function Documentation
VOID FASTCALL MiIdentifyPfn (IN PMMPFN Pfn1, OUT PMMPFN_IDENTITY PfnIdentity)
Definition at line 883 of file dmpaddr.c.
References _MI_PAGING_LEVELS, ActiveAndValid, ASSERT, BadPageList, BASE_POOL_TYPE_MASK, _SUBSECTION::ControlArea, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, _MMSECTION_FLAGS::File, _FILE_OBJECT::FileName, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, FreePageList, _MMSECTION_FLAGS::Image, _UNICODE_STRING::Length, MI_INCREMENT_IDENTIFY_COUNTER, MI_IS_PFN_DELETED, MI_IS_SESSION_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiDereferenceSegmentThread(), MiEndOfInitialPoolFrame, MiGetSubsectionAddress, MiGetVirtualAddressMappedByPte, MiPteRangeIndex, MiPteRanges, MiStartingOffset(), MiStartOfInitialPoolFrame, MM_PFN_LOCK_ASSERT, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmPagedPoolEnd, MmPagedPoolStart, MMPFNLIST_ACTIVE, MMPFNUSE_AWEPAGE, MMPFNUSE_DRIVERLOCKPAGE, MMPFNUSE_FILE, MMPFNUSE_METAFILE, MMPFNUSE_NONPAGEDPOOL, MMPFNUSE_PAGEDPOOL, MMPFNUSE_PAGEFILEMAPPED, MMPFNUSE_PAGETABLE, MMPFNUSE_PROCESSPRIVATE, MMPFNUSE_SESSIONPRIVATE, MMPFNUSE_SYSTEMPTE, MmQuerySpecialPoolBlockType(), MMSECTOR_SHIFT, MmSpecialPoolEnd, MmSpecialPoolStart, ModifiedNoWritePageList, ModifiedPageList, _MMSECTION_FLAGS::NoModifiedWriting, NonPagedPool, NULL, PAGE_ALIGN, PAGE_SHIFT, PsGetCurrentThread(), PTE_BASE, PTE_TOP, StandbyPageList, _SUBSECTION::SubsectionBase, TransitionPage, _CONTROL_AREA::u, and ZeroedPageList.
Referenced by MiLogPfnInformation(), and MmIdentifyPhysicalMemory().
VOID MiSnapCopyMemory (IN PVOID Destination, IN PFN_NUMBER PageFrameIndex, IN SIZE_T NumberOfBytes)
Definition at line 1428 of file dmpaddr.c.
References DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), MiMapPageInHyperSpace(), MiMapPageInHyperSpaceAtDpc(), MiUnmapPageInHyperSpace, MiUnmapPageInHyperSpaceFromDpc, MM_NOIRQL, PsGetCurrentProcess(), RtlCopyMemory, and TRUE.
NTSTATUS MmIdentifyPhysicalMemory (VOID)
Definition at line 744 of file dmpaddr.c.
References ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), LOCK_PFN, MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_PFN_ELEMENT, MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MiIdentifyPfn(), MmPhysicalMemoryBlock, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _PHYSICAL_MEMORY_RUN::PageCount, PASSIVE_LEVEL, PERFINFO_LOG_TYPE_PAGEINMEMORY, PerfInfoLogBytes(), PFN_ID_BUFFERS, RtlZeroMemory, _PHYSICAL_MEMORY_DESCRIPTOR::Run, STATUS_SUCCESS, and UNLOCK_PFN.
Referenced by PerfInfoStopLog().
NTSTATUS MmMemoryUsage (IN PVOID Buffer, IN ULONG Size, IN ULONG Type, OUT PULONG OutLength)
Definition at line 569 of file dmpaddr.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtQuerySystemInformation().
NTSTATUS MmPerfSnapShotValidPhysicalMemory (VOID)
Definition at line 596 of file dmpaddr.c.
References ActiveAndValid, ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, _MMPFN_MEMSNAP_INFORMATION::Count, _MMPFN::e1, _MMPFN_MEMSNAP_INFORMATION::InitialPageFrameIndex, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_MAXIMUM_PFNID_RUN, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MmPhysicalMemoryBlock, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _PHYSICAL_MEMORY_RUN::PageCount, _MMPFNENTRY::PageLocation, PASSIVE_LEVEL, PERFINFO_LOG_TYPE_MEMORYSNAPLITE, PerfInfoLogBytes(), RtlClearAllBits(), RtlInitializeBitMap(), RtlSetBit(), _PHYSICAL_MEMORY_DESCRIPTOR::Run, STATUS_SUCCESS, and _MMPFN::u3.
Referenced by WmiSetMark().
Variable Documentation
PFN_NUMBER MiEndOfInitialPoolFrame
Definition at line 66 of file allocpag.c.
Referenced by MiIdentifyPfn().
PFN_NUMBER MiStartOfInitialPoolFrame
Definition at line 65 of file allocpag.c.
Referenced by MiIdentifyPfn().
PMMPTE MmSystemPtesEnd[MaximumPtePoolTypes]
Definition at line 67 of file sysptes.c.