Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/bitmap.c File Reference
bitmap.c File Reference
#include "ntrtlp.h"
Macros
#define BitScanForwardChunk _BitScanForward
#define BitScanReverseChunk _BitScanReverse
#define BM_0 0x00000000000000FFUI64
#define BM_01 0x000000000000FFFFUI64
#define BM_0123 0x00000000FFFFFFFFUI64
#define BM_1 0x000000000000FF00UI64
#define BM_2 0x0000000000FF0000UI64
#define BM_23 0x00000000FFFF0000UI64
#define BM_3 0x00000000FF000000UI64
#define BM_4 0x000000FF00000000UI64
#define BM_45 0x0000FFFF00000000UI64
#define BM_4567 0xFFFFFFFF00000000UI64
#define BM_5 0x0000FF0000000000UI64
#define BM_6 0x00FF000000000000UI64
#define BM_67 0xFFFF000000000000UI64
#define BM_7 0xFF00000000000000UI64
#define CHUNK_BITS (CHUNK_BYTES * 8)
#define CHUNK_BYTES (sizeof(CHUNK))
#define CHUNK_CLEAR ((CHUNK)0)
#define CHUNK_HIGH_BIT ((CHUNK)1 << (CHUNK_BITS - 1))
#define CHUNK_SET ((CHUNK)-1)
#define GET_BYTE(THIS_BYTE)
#define GET_BYTE_DECLARATIONS() PUCHAR _CURRENT_POSITION;
#define GET_BYTE_INITIALIZATION(RTL_BITMAP, BYTE_INDEX)
#define GET_CHUNK(THIS_CHUNK)
#define READ_CHUNK(n) (Invert ? ~(*(chunkPtr+(n))) : (*(chunkPtr+(n))))
#define RTL_INVALID_INDEX ((ULONG)-1)
Typedefs
typedef ULONG_PTR CHUNK
typedef ULONG_PTR * PCHUNK
Functions
BOOLEAN RtlAreBitsClear (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG Length)
BOOLEAN RtlAreBitsSet (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG Length)
VOID RtlClearAllBits (IN PRTL_BITMAP BitMapHeader)
VOID RtlClearBit (IN PRTL_BITMAP BitMapHeader, IN ULONG BitNumber)
VOID RtlClearBits (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG NumberToClear)
ULONG RtlFindClearBits (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
ULONG RtlFindClearBitsAndSet (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
ULONG RtlFindClearRuns (IN PRTL_BITMAP BitMapHeader, PRTL_BITMAP_RUN RunArray, ULONG SizeOfRunArray, BOOLEAN LocateLongestRuns)
ULONG RtlFindFirstRunClear (IN PRTL_BITMAP BitMapHeader, OUT PULONG StartingIndex)
ULONG RtlFindLastBackwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
CCHAR RtlFindLeastSignificantBit (IN ULONGLONG Set)
ULONG RtlFindLongestRunClear (IN PRTL_BITMAP BitMapHeader, OUT PULONG StartingIndex)
CCHAR RtlFindMostSignificantBit (IN ULONGLONG Set)
ULONG RtlFindNextForwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
ULONG RtlFindSetBits (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
ULONG RtlFindSetBitsAndClear (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
VOID RtlInitializeBitMap (IN PRTL_BITMAP BitMapHeader, IN PULONG BitMapBuffer, IN ULONG SizeOfBitMap)
ULONG RtlNumberOfClearBits (IN PRTL_BITMAP BitMapHeader)
ULONG RtlNumberOfSetBits (IN PRTL_BITMAP BitMapHeader)
ULONG FORCEINLINE RtlpClearLSBInChunk (IN CHUNK Chunk)
ULONG FORCEINLINE RtlpClearMSBInChunk (IN CHUNK Chunk)
ULONG FORCEINLINE RtlpFindClearBitsRange (IN PULONG BitMap, IN ULONG NumberToFind, IN ULONG RangeStart, IN ULONG RangeEnd, IN LOGICAL Invert)
LOGICAL FORCEINLINE RtlpFindClearRunInChunk (IN CHUNK Chunk, IN ULONG RunLength, OUT ULONG *StartBit)
FORCEINLINE ULONG RtlpNumberOfSetBitsInChunk (IN CHUNK Target)
VOID RtlSetAllBits (IN PRTL_BITMAP BitMapHeader)
VOID RtlSetBit (IN PRTL_BITMAP BitMapHeader, IN ULONG BitNumber)
VOID RtlSetBits (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG NumberToSet)
BOOLEAN RtlTestBit (IN PRTL_BITMAP BitMapHeader, IN ULONG BitNumber)
Variables
static CONST UCHAR FillMask [] = { 0x00, 0x01, 0x03, 0x07, 0x0F, 0x1F, 0x3F, 0x7F, 0xFF }
static CONST ULONG FillMaskUlong []
CONST CCHAR RtlpBitsClearAnywhere []
CONST CCHAR RtlpBitsClearHigh []
CONST CCHAR RtlpBitsClearLow []
CONST CCHAR RtlpBitsClearTotal []
static CONST UCHAR ZeroMask [] = { 0xFF, 0xFE, 0xFC, 0xF8, 0xf0, 0xe0, 0xc0, 0x80, 0x00 }
Macro Definition Documentation
#define BitScanForwardChunk _BitScanForward
Definition at line 491 of file bitmap.c.
Referenced by RtlpClearLSBInChunk(), RtlpFindClearBitsRange(), and RtlpFindClearRunInChunk().
#define BitScanReverseChunk _BitScanReverse
Definition at line 492 of file bitmap.c.
Referenced by RtlpClearMSBInChunk().
#define BM_0 0x00000000000000FFUI64
Definition at line 2931 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_01 0x000000000000FFFFUI64
Definition at line 2930 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_0123 0x00000000FFFFFFFFUI64
Definition at line 2929 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_1 0x000000000000FF00UI64
Definition at line 2927 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define BM_2 0x0000000000FF0000UI64
Definition at line 2932 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_23 0x00000000FFFF0000UI64
Definition at line 2925 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define BM_3 0x00000000FF000000UI64
Definition at line 2926 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define BM_4 0x000000FF00000000UI64
Definition at line 2934 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_45 0x0000FFFF00000000UI64
Definition at line 2933 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_4567 0xFFFFFFFF00000000UI64
Definition at line 2921 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define BM_5 0x0000FF0000000000UI64
Definition at line 2924 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define BM_6 0x00FF000000000000UI64
Definition at line 2935 of file bitmap.c.
Referenced by RtlFindLeastSignificantBit().
#define BM_67 0xFFFF000000000000UI64
Definition at line 2922 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define BM_7 0xFF00000000000000UI64
Definition at line 2923 of file bitmap.c.
Referenced by RtlFindMostSignificantBit().
#define CHUNK_BITS (CHUNK_BYTES * 8)
Definition at line 480 of file bitmap.c.
Referenced by RtlpClearLSBInChunk(), RtlpClearMSBInChunk(), RtlpFindClearBitsRange(), and RtlpFindClearRunInChunk().
#define CHUNK_BYTES (sizeof(CHUNK))
Definition at line 479 of file bitmap.c.
#define CHUNK_CLEAR ((CHUNK)0)
Definition at line 481 of file bitmap.c.
Referenced by RtlpFindClearBitsRange().
#define CHUNK_HIGH_BIT ((CHUNK)1 << (CHUNK_BITS - 1))
Definition at line 483 of file bitmap.c.
Referenced by RtlpFindClearBitsRange().
#define CHUNK_SET ((CHUNK)-1)
Definition at line 482 of file bitmap.c.
Referenced by RtlpFindClearBitsRange().
#define GET_BYTE (THIS_BYTE)
Value:
(\
    THIS_BYTE = *(_CURRENT_POSITION++) \
)
Definition at line 108 of file bitmap.c.
Referenced by RtlAreBitsClear(), RtlAreBitsSet(), RtlFindClearRuns(), and RtlNumberOfSetBits().
#define GET_BYTE_DECLARATIONS () PUCHAR _CURRENT_POSITION;
Definition at line 101 of file bitmap.c.
Referenced by RtlAreBitsClear(), RtlAreBitsSet(), RtlFindClearRuns(), and RtlNumberOfSetBits().
#define GET_BYTE_INITIALIZATION (RTL_BITMAP, BYTE_INDEX)
Value:
{               \
    _CURRENT_POSITION = &((PUCHAR)((RTL_BITMAP)->Buffer))[BYTE_INDEX]; \
}
Definition at line 104 of file bitmap.c.
Referenced by RtlAreBitsClear(), RtlAreBitsSet(), RtlFindClearRuns(), and RtlNumberOfSetBits().
#define GET_CHUNK (THIS_CHUNK)
Value:
{                     \
    THIS_CHUNK = *((CHUNK *)_CURRENT_POSITION);     \
    _CURRENT_POSITION += sizeof(CHUNK); }
Definition at line 2070 of file bitmap.c.
Referenced by RtlNumberOfSetBits().
#define READ_CHUNK (n) (Invert ? ~(*(chunkPtr+(n))) : (*(chunkPtr+(n))))
Referenced by RtlpFindClearBitsRange().
#define RTL_INVALID_INDEX ((ULONG)-1)
Definition at line 485 of file bitmap.c.
Referenced by RtlFindClearBits(), RtlFindSetBits(), and RtlpFindClearBitsRange().
Typedef Documentation
typedef ULONG_PTR CHUNK
Definition at line 478 of file bitmap.c.
typedef ULONG_PTR * PCHUNK
Definition at line 478 of file bitmap.c.
Function Documentation
BOOLEAN RtlAreBitsClear (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG Length)
Definition at line 2320 of file bitmap.c.
References FALSE, GET_BYTE, GET_BYTE_DECLARATIONS, GET_BYTE_INITIALIZATION, and TRUE.
BOOLEAN RtlAreBitsSet (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG Length)
Definition at line 2479 of file bitmap.c.
References FALSE, GET_BYTE, GET_BYTE_DECLARATIONS, GET_BYTE_INITIALIZATION, and TRUE.
VOID RtlClearAllBits (IN PRTL_BITMAP BitMapHeader)
Definition at line 403 of file bitmap.c.
References RtlZeroMemory.
VOID RtlClearBit (IN PRTL_BITMAP BitMapHeader, IN ULONG BitNumber)
Definition at line 260 of file bitmap.c.
References ASSERT.
VOID RtlClearBits (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG NumberToClear)
Definition at line 1464 of file bitmap.c.
References ASSERT, and RtlZeroMemory.
Referenced by RtlFindSetBitsAndClear().
ULONG RtlFindClearBits (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
Definition at line 1113 of file bitmap.c.
References FALSE, RTL_INVALID_INDEX, RtlpFindClearBitsRange(), and TRUE.
Referenced by RtlFindClearBitsAndSet().
ULONG RtlFindClearBitsAndSet (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
Definition at line 1342 of file bitmap.c.
References RtlFindClearBits(), and RtlSetBits().
ULONG RtlFindClearRuns (IN PRTL_BITMAP BitMapHeader, PRTL_BITMAP_RUN RunArray, ULONG SizeOfRunArray, BOOLEAN LocateLongestRuns)
Definition at line 1686 of file bitmap.c.
References DbgPrint(), GET_BYTE, GET_BYTE_DECLARATIONS, GET_BYTE_INITIALIZATION, _RTL_BITMAP_RUN::NumberOfBits, and _RTL_BITMAP_RUN::StartingIndex.
Referenced by RtlFindLongestRunClear().
ULONG RtlFindFirstRunClear (IN PRTL_BITMAP BitMapHeader, OUT PULONG StartingIndex)
Definition at line 2039 of file bitmap.c.
References RtlFindNextForwardRunClear().
ULONG RtlFindLastBackwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
Definition at line 2794 of file bitmap.c.
References MAXULONG, RTL_PAGED_CODE, and RtlCheckBit.
CCHAR RtlFindLeastSignificantBit (IN ULONGLONG Set)
Definition at line 3031 of file bitmap.c.
References BM_0, BM_01, BM_0123, BM_2, BM_4, BM_45, and BM_6.
ULONG RtlFindLongestRunClear (IN PRTL_BITMAP BitMapHeader, OUT PULONG StartingIndex)
Definition at line 1993 of file bitmap.c.
References _RTL_BITMAP_RUN::NumberOfBits, RtlFindClearRuns(), _RTL_BITMAP_RUN::StartingIndex, and TRUE.
CCHAR RtlFindMostSignificantBit (IN ULONGLONG Set)
Definition at line 2938 of file bitmap.c.
References BM_1, BM_23, BM_3, BM_4567, BM_5, BM_67, and BM_7.
Referenced by NtAllocateVirtualMemory(), and NtMapViewOfSection().
ULONG RtlFindNextForwardRunClear (IN PRTL_BITMAP BitMapHeader, IN ULONG FromIndex, IN PULONG StartingRunIndex)
Definition at line 2650 of file bitmap.c.
References RtlCheckBit.
Referenced by RtlFindFirstRunClear().
ULONG RtlFindSetBits (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
Definition at line 1229 of file bitmap.c.
References RTL_INVALID_INDEX, RtlpFindClearBitsRange(), and TRUE.
Referenced by RtlFindSetBitsAndClear().
ULONG RtlFindSetBitsAndClear (IN PRTL_BITMAP BitMapHeader, IN ULONG NumberToFind, IN ULONG HintIndex)
Definition at line 1404 of file bitmap.c.
References RtlClearBits(), and RtlFindSetBits().
VOID RtlInitializeBitMap (IN PRTL_BITMAP BitMapHeader, IN PULONG BitMapBuffer, IN ULONG SizeOfBitMap)
Definition at line 215 of file bitmap.c.
References RTL_PAGED_CODE.
ULONG RtlNumberOfClearBits (IN PRTL_BITMAP BitMapHeader)
Definition at line 2292 of file bitmap.c.
References RtlNumberOfSetBits().
ULONG RtlNumberOfSetBits (IN PRTL_BITMAP BitMapHeader)
Definition at line 2190 of file bitmap.c.
References GET_BYTE, GET_BYTE_DECLARATIONS, GET_BYTE_INITIALIZATION, GET_CHUNK, RtlpBitsSetTotal, and RtlpNumberOfSetBitsInChunk().
Referenced by RtlNumberOfClearBits().
ULONG FORCEINLINE RtlpClearLSBInChunk (IN CHUNK Chunk)
Definition at line 610 of file bitmap.c.
References BitScanForwardChunk, CHUNK_BITS, FALSE, and Index.
Referenced by RtlpFindClearBitsRange().
ULONG FORCEINLINE RtlpClearMSBInChunk (IN CHUNK Chunk)
Definition at line 575 of file bitmap.c.
References BitScanReverseChunk, CHUNK_BITS, FALSE, and Index.
Referenced by RtlpFindClearBitsRange().
ULONG FORCEINLINE RtlpFindClearBitsRange (IN PULONG BitMap, IN ULONG NumberToFind, IN ULONG RangeStart, IN ULONG RangeEnd, IN LOGICAL Invert)
Definition at line 643 of file bitmap.c.
References ASSERT, BitScanForwardChunk, CHUNK_BITS, CHUNK_CLEAR, CHUNK_HIGH_BIT, CHUNK_SET, FALSE, READ_CHUNK, RTL_INVALID_INDEX, RtlpClearLSBInChunk(), RtlpClearMSBInChunk(), RtlpFindClearRunInChunk(), and TRUE.
Referenced by RtlFindClearBits(), and RtlFindSetBits().
LOGICAL FORCEINLINE RtlpFindClearRunInChunk (IN CHUNK Chunk, IN ULONG RunLength, OUT ULONG * StartBit)
Definition at line 498 of file bitmap.c.
References ASSERT, BitScanForwardChunk, CHUNK_BITS, FALSE, and TRUE.
Referenced by RtlpFindClearBitsRange().
FORCEINLINE ULONG RtlpNumberOfSetBitsInChunk (IN CHUNK Target)
Definition at line 2149 of file bitmap.c.
Referenced by RtlNumberOfSetBits().
VOID RtlSetAllBits (IN PRTL_BITMAP BitMapHeader)
Definition at line 441 of file bitmap.c.
References RtlFillMemoryUlong().
VOID RtlSetBit (IN PRTL_BITMAP BitMapHeader, IN ULONG BitNumber)
Definition at line 308 of file bitmap.c.
References ASSERT.
VOID RtlSetBits (IN PRTL_BITMAP BitMapHeader, IN ULONG StartingIndex, IN ULONG NumberToSet)
Definition at line 1573 of file bitmap.c.
References ASSERT, and RtlFillMemory.
Referenced by RtlFindClearBitsAndSet().
BOOLEAN RtlTestBit (IN PRTL_BITMAP BitMapHeader, IN ULONG BitNumber)
Definition at line 356 of file bitmap.c.
References ASSERT.
Variable Documentation
CONST UCHAR FillMask[] = { 0x00, 0x01, 0x03, 0x07, 0x0F, 0x1F, 0x3F, 0x7F, 0xFF } static
Definition at line 209 of file bitmap.c.
CONST ULONG FillMaskUlong[] static
Initial value:
= {
    0x00000000, 0x00000001, 0x00000003, 0x00000007,
    0x0000000f, 0x0000001f, 0x0000003f, 0x0000007f,
    0x000000ff, 0x000001ff, 0x000003ff, 0x000007ff,
    0x00000fff, 0x00001fff, 0x00003fff, 0x00007fff,
    0x0000ffff, 0x0001ffff, 0x0003ffff, 0x0007ffff,
    0x000fffff, 0x001fffff, 0x003fffff, 0x007fffff,
    0x00ffffff, 0x01ffffff, 0x03ffffff, 0x07ffffff,
    0x0fffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff,
    0xffffffff
}
Definition at line 2636 of file bitmap.c.
CONST CCHAR RtlpBitsClearAnywhere[]
Initial value:
=
         { 8,7,6,6,5,5,5,5,4,4,4,4,4,4,4,4,
           4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
           5,4,3,3,2,2,2,2,3,2,2,2,2,2,2,2,
           4,3,2,2,2,2,2,2,3,2,2,2,2,2,2,2,
           6,5,4,4,3,3,3,3,3,2,2,2,2,2,2,2,
           4,3,2,2,2,1,1,1,3,2,1,1,2,1,1,1,
           5,4,3,3,2,2,2,2,3,2,1,1,2,1,1,1,
           4,3,2,2,2,1,1,1,3,2,1,1,2,1,1,1,
           7,6,5,5,4,4,4,4,3,3,3,3,3,3,3,3,
           4,3,2,2,2,2,2,2,3,2,2,2,2,2,2,2,
           5,4,3,3,2,2,2,2,3,2,1,1,2,1,1,1,
           4,3,2,2,2,1,1,1,3,2,1,1,2,1,1,1,
           6,5,4,4,3,3,3,3,3,2,2,2,2,2,2,2,
           4,3,2,2,2,1,1,1,3,2,1,1,2,1,1,1,
           5,4,3,3,2,2,2,2,3,2,1,1,2,1,1,1,
           4,3,2,2,2,1,1,1,3,2,1,1,2,1,1,0 }
Definition at line 118 of file bitmap.c.
CONST CCHAR RtlpBitsClearHigh[]
Initial value:
=
          { 8,7,6,6,5,5,5,5,4,4,4,4,4,4,4,4,
            3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
            2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
            2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
            1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
            1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
            1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
            1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
            0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 }
Definition at line 164 of file bitmap.c.
CONST CCHAR RtlpBitsClearLow[]
Initial value:
=
          { 8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,
            4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0 }
Definition at line 141 of file bitmap.c.
CONST CCHAR RtlpBitsClearTotal[]
Initial value:
=
          { 8,7,7,6,7,6,6,5,7,6,6,5,6,5,5,4,
            7,6,6,5,6,5,5,4,6,5,5,4,5,4,4,3,
            7,6,6,5,6,5,5,4,6,5,5,4,5,4,4,3,
            6,5,5,4,5,4,4,3,5,4,4,3,4,3,3,2,
            7,6,6,5,6,5,5,4,6,5,5,4,5,4,4,3,
            6,5,5,4,5,4,4,3,5,4,4,3,4,3,3,2,
            6,5,5,4,5,4,4,3,5,4,4,3,4,3,3,2,
            5,4,4,3,4,3,3,2,4,3,3,2,3,2,2,1,
            7,6,6,5,6,5,5,4,6,5,5,4,5,4,4,3,
            6,5,5,4,5,4,4,3,5,4,4,3,4,3,3,2,
            6,5,5,4,5,4,4,3,5,4,4,3,4,3,3,2,
            5,4,4,3,4,3,3,2,4,3,3,2,3,2,2,1,
            6,5,5,4,5,4,4,3,5,4,4,3,4,3,3,2,
            5,4,4,3,4,3,3,2,4,3,3,2,3,2,2,1,
            5,4,4,3,4,3,3,2,4,3,3,2,3,2,2,1,
            4,3,3,2,3,2,2,1,3,2,2,1,2,1,1,0 }
Definition at line 186 of file bitmap.c.
CONST UCHAR ZeroMask[] = { 0xFF, 0xFE, 0xFC, 0xF8, 0xf0, 0xe0, 0xc0, 0x80, 0x00 } static
Definition at line 211 of file bitmap.c.