Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/kiinit.c File Reference
kiinit.c File Reference
#include "ki.h"
Functions
ULARGE_INTEGER KeComputeReciprocal (IN LONG Divisor, OUT PCCHAR Shift)
ULONG KeComputeReciprocal32 (IN LONG Divisor, OUT PCCHAR Shift)
BOOLEAN KeInitSystem (VOID)
VOID KeNumaInitialize (VOID)
VOID KiInitSpinLocks (PKPRCB Prcb, ULONG Number)
VOID KiInitSystem (VOID)
Variables
ALIGNED_SPINLOCK AfdWorkQueueSpinLock
ALIGNED_SPINLOCK CcBcbSpinLock
ALIGNED_SPINLOCK CcMasterSpinLock
ALIGNED_SPINLOCK CcVacbSpinLock
ALIGNED_SPINLOCK CcWorkQueueSpinLock
ALIGNED_SPINLOCK IopCancelSpinLock
ALIGNED_SPINLOCK IopCompletionLock
ALIGNED_SPINLOCK IopDatabaseLock
ALIGNED_SPINLOCK IopVpbSpinLock
ALIGNED_SPINLOCK MmNonPagedPoolLock
ALIGNED_SPINLOCK MmPfnLock
ALIGNED_SPINLOCK MmSystemSpaceLock
ALIGNED_SPINLOCK NonPagedPoolLock
ALIGNED_SPINLOCK NtfsStructLock
Function Documentation
ULARGE_INTEGER KeComputeReciprocal (IN LONG Divisor, OUT PCCHAR Shift)
Definition at line 416 of file kiinit.c.
References _LARGE_INTEGER::HighPart, and _LARGE_INTEGER::LowPart.
Referenced by KiInitializeKernel().
ULONG KeComputeReciprocal32 (IN LONG Divisor, OUT PCCHAR Shift)
Definition at line 492 of file kiinit.c.
BOOLEAN KeInitSystem (VOID)
Definition at line 58 of file kiinit.c.
References DPC_THREADED, _KPRCB::DpcData, _KPRCB::DpcEvent, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, FALSE, Handle, Index, InitializeListHead(), InitializeObjectAttributes, KeInitializeEvent(), KeInitializeSpinLock(), KeNumberProcessors, KeThreadDpcEnable, KiExecuteDpc(), KiInitMachineDependent(), KiProcessorBlock, NT_SUCCESS, NULL, PsCreateSystemThread(), Status, SynchronizationEvent, THREAD_ALL_ACCESS, and ZwClose().
Referenced by Phase1InitializationDiscard().
VOID KeNumaInitialize (VOID)
Definition at line 559 of file kiinit.c.
References ASSERT, HalNumaTopologyInterface, HalQuerySystemInformation, KeNumberNodes, KiQueryProcessorNode, MAXIMUM_CCNUMA_NODES, NT_SUCCESS, NULL, _HAL_NUMA_TOPOLOGY_INTERFACE::NumberOfNodes, _HAL_NUMA_TOPOLOGY_INTERFACE::PageToNode, _HAL_NUMA_TOPOLOGY_INTERFACE::QueryProcessorNode, and Status.
Referenced by ExpInitializeExecutive().
VOID KiInitSpinLocks (PKPRCB Prcb, ULONG Number)
Definition at line 131 of file kiinit.c.
References _KPRCB::AdjustDpcThreshold, AfdWorkQueueSpinLock, _KPRCB::CallDpc, CcBcbSpinLock, CcMasterSpinLock, CcVacbSpinLock, CcWorkQueueSpinLock, _KPRCB::DeferredReadyListHead, _KPRCB::DispatcherReadyListHead, DPC_NORMAL, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KDPC_DATA::DpcListHead, _KDPC_DATA::DpcLock, _KDPC_DATA::DpcQueueDepth, _KPRCB::DpcRoutineActive, HighImportance, Index, InitializeListHead(), IopCancelSpinLock, IopCompletionLock, IopDatabaseLock, IopVpbSpinLock, KeGetPcr(), KeInitializeDpc(), KeInitializeSpinLock(), KeSetImportanceDpc(), KeSetTargetProcessorDpc(), KiAdjustDpcThreshold, KiDispatcherLock, KiMaximumDpcQueueDepth, KiMinimumDpcRate, KiReverseStallIpiLock, KiTimerTableLock, _ALIGNED_SPINLOCK_STRUCT::Lock, _KSPIN_LOCK_QUEUE::Lock, LOCK_QUEUE_TIMER_TABLE_LOCKS, _KPRCB::LockQueue, LockQueueAfdWorkQueueLock, LockQueueBcbLock, LockQueueDispatcherLock, LockQueueIoCancelLock, LockQueueIoCompletionLock, LockQueueIoDatabaseLock, LockQueueIoVpbLock, LockQueueMasterLock, LockQueueMmNonPagedPoolLock, LockQueueNonPagedPoolLock, LockQueueNtfsStructLock, LockQueuePfnLock, LockQueueSystemSpaceLock, LockQueueTimerTableLock, LockQueueUnusedSpare1, LockQueueUnusedSpare16, LockQueueVacbLock, LockQueueWorkQueueLock, MAXIMUM_PRIORITY, _KPRCB::MaximumDpcQueueDepth, _KPRCB::MinimumDpcRate, MmNonPagedPoolLock, MmPfnLock, MmSystemSpaceLock, _KSPIN_LOCK_QUEUE::Next, _SINGLE_LIST_ENTRY::Next, NonPagedPoolLock, NtfsStructLock, NULL, _KPRCB::PrcbLock, _KPRCB::QueueIndex, _KPRCB::ReadySummary, and _KPRCB::WaitListHead.
Referenced by KiInitializeBootStructures(), and KiInitializeKernel().
VOID KiInitSystem (VOID)
Definition at line 304 of file kiinit.c.
References _KSERVICE_TABLE_DESCRIPTOR::Base, _KSERVICE_TABLE_DESCRIPTOR::Count, ExInitializeFastMutex, FALSE, _ULARGE_INTEGER::HighPart, Index, InitializeListHead(), KeBugCheckCallbackListHead, KeBugCheckCallbackLock, KeBugCheckReasonCallbackListHead, KeInitializeDpc(), KeInitializeEvent(), KeInitializeSpinLock(), KeServiceDescriptorTable, KeServiceDescriptorTableShadow, KeSetTargetProcessorDpc(), KiArgumentTable, KiGenericCallDpcMutex, KiProcessInSwapListHead, KiProcessOutSwapListHead, KiProfileListHead, KiProfileLock, KiProfileSourceListHead, KiServiceLimit, KiServiceTable, KiStackInSwapListHead, KiSwapEvent, KiTimerExpiration(), KiTimerExpireDpc, KiTimerTableListHead, _KSERVICE_TABLE_DESCRIPTOR::Limit, _ULARGE_INTEGER::LowPart, _SINGLE_LIST_ENTRY::Next, NULL, _KSERVICE_TABLE_DESCRIPTOR::Number, NUMBER_SERVICE_TABLES, RtlCopyMemory, SynchronizationEvent, _KTIMER_TABLE_ENTRY::Time, and TIMER_TABLE_SIZE.
Referenced by KiInitializeKernel().
Variable Documentation
ALIGNED_SPINLOCK AfdWorkQueueSpinLock
Definition at line 106 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK CcBcbSpinLock
Definition at line 37 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK CcMasterSpinLock
Definition at line 32 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK CcVacbSpinLock
Definition at line 34 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK CcWorkQueueSpinLock
Definition at line 33 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK IopCancelSpinLock
Definition at line 51 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK IopCompletionLock
Definition at line 50 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK IopDatabaseLock
Definition at line 53 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK IopVpbSpinLock
Definition at line 52 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK MmNonPagedPoolLock
Definition at line 88 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK MmPfnLock
Definition at line 86 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK MmSystemSpaceLock
Definition at line 87 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK NonPagedPoolLock
Definition at line 43 of file hifreqlk.c.
Referenced by KiInitSpinLocks().
ALIGNED_SPINLOCK NtfsStructLock
Definition at line 100 of file hifreqlk.c.
Referenced by KiInitSpinLocks().