Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/apcsup.c File Reference
apcsup.c File Reference
#include "ki.h"
Functions
VOID KiCheckForKernelApcDelivery (VOID)
VOID KiDeliverApc (IN KPROCESSOR_MODE PreviousMode, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
VOID FASTCALL KiInsertQueueApc (IN PKAPC Apc, IN KPRIORITY Increment)
Function Documentation
VOID KiCheckForKernelApcDelivery (VOID)
Definition at line 24 of file apcsup.c.
References APC_LEVEL, _KTHREAD::ApcState, KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, _KAPC_STATE::KernelApcPending, KernelMode, KfRaiseIrql(), KiDeliverApc(), KiRequestSoftwareInterrupt, NULL, PASSIVE_LEVEL, and TRUE.
Referenced by KeLeaveCriticalRegionThread(), and KeLeaveGuardedRegionThread().
VOID KiDeliverApc (IN KPROCESSOR_MODE PreviousMode, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
Definition at line 78 of file apcsup.c.
References APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _KAPC::Inserted, INVALID_PROCESS_ATTACH_ATTEMPT, IRQL_UNEXPECTED_VALUE, IsListEmpty, KeAcquireInStackQueuedSpinLock(), KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KeLowerIrql, KeMemoryBarrier(), KeRaiseIrql, KeReleaseInStackQueuedSpinLock(), _KTHREAD::KernelApcDisable, _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, _KAPC::KernelRoutine, KeTestAlertThread(), KiCheckForSListAddress(), KiInitializeUserApc(), _KAPC::NormalContext, _KAPC::NormalRoutine, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, ReadForWriteAccess, RemoveEntryList(), _KTHREAD::SpecialApcDisable, _KAPC::SystemArgument1, _KAPC::SystemArgument2, _KTHREAD::TrapFrame, TRUE, _KAPC_STATE::UserApcPending, and UserMode.
Referenced by KiCheckForKernelApcDelivery(), KiContinueEx(), and KiExitDispatcher().
VOID FASTCALL KiInsertQueueApc (IN PKAPC Apc, IN KPRIORITY Increment)
Definition at line 382 of file apcsup.c.
References _KTHREAD::Alertable, APC_LEVEL, _KAPC_STATE::ApcListHead, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, _KTHREAD::ApcStatePointer, ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _KQUEUE::CurrentCount, FALSE, GateObject, _KTHREAD::GateObject, GateWait, InsertApcEnvironment, InsertHeadList(), InsertTailList(), KeGetCurrentThread(), KeMemoryBarrier(), _KTHREAD::KernelApcDisable, _KAPC_STATE::KernelApcInProgress, _KAPC_STATE::KernelApcPending, KernelMode, KiAcquireKobjectLock(), KiAcquireThreadLock(), KiInsertDeferredReadyList(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseKobjectLock(), KiReleaseThreadLock(), KiRequestApcInterrupt, KiRequestSoftwareInterrupt, KiUnlockDispatcherDatabaseFromSynchLevel, KiUnwaitThread(), _KTHREAD::NextProcessor, _KAPC::NormalRoutine, NULL, PsExitSpecialApc(), _KTHREAD::Queue, RemoveEntryList(), Running, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_KERNEL_APC, STATUS_USER_APC, TRUE, _KAPC_STATE::UserApcPending, UserMode, _KTHREAD::WaitBlock, Waiting, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitMode, and _KTHREAD::WaitStatus.
Referenced by KeFreezeAllThreads(), KeInsertQueueApc(), and KeSuspendThread().