Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmboot.c File Reference
cmboot.c File Reference
#include "cmp.h"
#include <profiles.h>
Macros
#define LOAD_LAST 0xffffffff
#define LOAD_NEXT_TO_LAST (LOAD_LAST-1)
#define TempAlias AliasList->Alias[i]
Functions
VOID BlPrint (PCHAR cp,...)
BOOLEAN CmpAddDriverToList (IN PHHIVE Hive, IN HCELL_INDEX DriverCell, IN HCELL_INDEX GroupOrderCell, IN PUNICODE_STRING RegistryPath, IN PLIST_ENTRY BootDriverListHead)
BOOLEAN CmpDoSort (IN PLIST_ENTRY DriverListHead, IN PUNICODE_STRING OrderList)
HCELL_INDEX CmpFindControlSet (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell, IN PUNICODE_STRING SelectName, OUT PBOOLEAN AutoSelect)
BOOLEAN CmpFindDrivers (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN SERVICE_LOAD_TYPE LoadType, IN PWSTR BootFileSystem OPTIONAL, IN PLIST_ENTRY DriverListHead)
BOOLEAN CmpFindNLSData (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, OUT PUNICODE_STRING AnsiFilename, OUT PUNICODE_STRING OemFilename, OUT PUNICODE_STRING CaseTableFilename, OUT PUNICODE_STRING OemHalFont)
HCELL_INDEX CmpFindProfileOption (IN PHHIVE SystemHive, IN HCELL_INDEX ControlSet, OUT OPTIONAL PCM_HARDWARE_PROFILE_LIST *ReturnedProfileList, OUT OPTIONAL PCM_HARDWARE_PROFILE_ALIAS_LIST *ReturnedAliasList, OUT OPTIONAL PULONG ProfileTimeout)
ULONG CmpFindTagIndex (IN PHHIVE Hive, IN HCELL_INDEX TagCell, IN HCELL_INDEX GroupOrderCell, IN PUNICODE_STRING GroupName)
BOOLEAN CmpIsLoadType (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN SERVICE_LOAD_TYPE LoadType)
BOOLEAN CmpOrderGroup (IN PBOOT_DRIVER_NODE GroupStart, IN PBOOT_DRIVER_NODE GroupEnd)
BOOLEAN CmpResolveDriverDependencies (IN PLIST_ENTRY DriverListHead)
VOID CmpSetCurrentProfile (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PCM_HARDWARE_PROFILE Profile)
BOOLEAN CmpSortDriverList (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PLIST_ENTRY DriverListHead)
BOOLEAN CmpValidateSelect (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell)
Macro Definition Documentation
#define LOAD_LAST 0xffffffff
Definition at line 28 of file cmboot.c.
Referenced by CmpAddDriverToList().
#define LOAD_NEXT_TO_LAST (LOAD_LAST-1)
Definition at line 29 of file cmboot.c.
Referenced by CmpFindTagIndex().
#define TempAlias AliasList->Alias[i]
Referenced by CmpFindProfileOption().
Function Documentation
VOID BlPrint (PCHAR cp, ...)
BOOLEAN CmpAddDriverToList (IN PHHIVE Hive, IN HCELL_INDEX DriverCell, IN HCELL_INDEX GroupOrderCell, IN PUNICODE_STRING RegistryPath, IN PLIST_ENTRY BootDriverListHead)
Definition at line 760 of file cmboot.c.
References ASSERT, _UNICODE_STRING::Buffer, CmpCompressedNameSize(), CmpCopyCompressedName(), CmpFindTagIndex(), CmpFindValueByName(), CmpValueToData(), DriverEntry(), _BOOT_DRIVER_NODE::ErrorControl, FALSE, _BOOT_DRIVER_LIST_ENTRY::FilePath, _CM_KEY_NODE::Flags, _BOOT_DRIVER_NODE::Group, HCELL_NIL, HvGetCell, InsertHeadList(), KEY_COMP_NAME, _UNICODE_STRING::Length, _BOOT_DRIVER_LIST_ENTRY::Link, _BOOT_DRIVER_NODE::ListEntry, LOAD_LAST, _UNICODE_STRING::MaximumLength, _BOOT_DRIVER_NODE::Name, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NormalError, NT_SUCCESS, NULL, _BOOT_DRIVER_LIST_ENTRY::RegistryPath, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyMemory, RtlInitUnicodeString(), Tag, _BOOT_DRIVER_NODE::Tag, and TRUE.
Referenced by CmpFindDrivers().
BOOLEAN CmpDoSort (IN PLIST_ENTRY DriverListHead, IN PUNICODE_STRING OrderList)
Definition at line 1162 of file cmboot.c.
References ASSERT, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _LIST_ENTRY::Flink, _BOOT_DRIVER_NODE::Group, InsertHeadList(), _UNICODE_STRING::Length, _BOOT_DRIVER_LIST_ENTRY::Link, _BOOT_DRIVER_NODE::ListEntry, _UNICODE_STRING::MaximumLength, NULL, RemoveEntryList(), RtlEqualUnicodeString(), TRUE, and UNICODE_NULL.
Referenced by CmpSortDriverList().
HCELL_INDEX CmpFindControlSet (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell, IN PUNICODE_STRING SelectName, OUT PBOOLEAN AutoSelect)
Definition at line 1524 of file cmboot.c.
References ASSERT, _STRING::Buffer, _UNICODE_STRING::Buffer, CmpFindSubKeyByName(), CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, _STRING::Length, _STRING::MaximumLength, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, REG_DWORD, RtlAnsiStringToUnicodeString(), RtlInitUnicodeString(), sprintf(), Status, strlen(), TRUE, and _CM_KEY_VALUE::Type.
Referenced by CmGetSystemControlValues(), and CmGetSystemDriverList().
BOOLEAN CmpFindDrivers (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN SERVICE_LOAD_TYPE LoadType, IN PWSTR BootFileSystem OPTIONAL, IN PLIST_ENTRY DriverListHead)
Definition at line 505 of file cmboot.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CmpAddDriverToList(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpIsLoadType(), CONTAINING_RECORD, _BOOT_DRIVER_NODE::ErrorControl, FALSE, HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, RtlAppendUnicodeToString(), RtlInitUnicodeString(), SERVICE_ERROR_CRITICAL, and TRUE.
Referenced by CmGetSystemDriverList().
BOOLEAN CmpFindNLSData (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, OUT PUNICODE_STRING AnsiFilename, OUT PUNICODE_STRING OemFilename, OUT PUNICODE_STRING CaseTableFilename, OUT PUNICODE_STRING OemHalFont)
Definition at line 97 of file cmboot.c.
References ASSERT, _UNICODE_STRING::Buffer, CmpFindSubKeyByName(), CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, RtlInitUnicodeString(), TRUE, and UNICODE_NULL.
HCELL_INDEX CmpFindProfileOption (IN PHHIVE SystemHive, IN HCELL_INDEX ControlSet, OUT OPTIONAL PCM_HARDWARE_PROFILE_LIST * ReturnedProfileList, OUT OPTIONAL PCM_HARDWARE_PROFILE_ALIAS_LIST * ReturnedAliasList, OUT OPTIONAL PULONG ProfileTimeout)
Definition at line 1838 of file cmboot.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CM_HARDWARE_PROFILE_STR_ALIASABLE, CM_HARDWARE_PROFILE_STR_FRIENDLY_NAME, CM_HARDWARE_PROFILE_STR_PREFERENCE_ORDER, CM_HARDWARE_PROFILE_STR_PRISTINE, CM_HP_FLAGS_ALIASABLE, CM_HP_FLAGS_PRISTINE, CmpCompressedNameSize(), CmpCopyCompressedName(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpFindValueByName(), CmpValueToData(), _CM_HARDWARE_PROFILE_ALIAS_LIST::CurrentAliasCount, _CM_HARDWARE_PROFILE_LIST::CurrentProfileCount, FALSE, _CM_KEY_NODE::Flags, _CM_HARDWARE_PROFILE::Flags, _CM_HARDWARE_PROFILE::FriendlyName, HCELL_NIL, HvGetCell, _CM_HARDWARE_PROFILE::Id, KEY_COMP_NAME, KeyName, _UNICODE_STRING::Length, _CM_HARDWARE_PROFILE_ALIAS_LIST::MaxAliasCount, _UNICODE_STRING::MaximumLength, _CM_HARDWARE_PROFILE_LIST::MaxProfileCount, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, _CM_HARDWARE_PROFILE::NameLength, NULL, _CM_HARDWARE_PROFILE::PreferenceOrder, _CM_HARDWARE_PROFILE_LIST::Profile, REG_DWORD, RtlInitUnicodeString(), RtlMoveMemory, RtlUnicodeStringToInteger(), Stable, _CM_KEY_NODE::SubKeyCounts, TempAlias, _CM_KEY_VALUE::Type, and wcslen().
Referenced by CmpSetCurrentProfile().
ULONG CmpFindTagIndex (IN PHHIVE Hive, IN HCELL_INDEX TagCell, IN HCELL_INDEX GroupOrderCell, IN PUNICODE_STRING GroupName)
Definition at line 2421 of file cmboot.c.
References ASSERT, CmpFindValueByName(), CmpGetValueData(), CmpValueToData(), ExFreePool(), HCELL_NIL, HvGetCell, LOAD_NEXT_TO_LAST, and NULL.
Referenced by CmpAddDriverToList().
BOOLEAN CmpIsLoadType (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN SERVICE_LOAD_TYPE LoadType)
Definition at line 671 of file cmboot.c.
References ASSERT, CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, NULL, RtlInitUnicodeString(), and TRUE.
Referenced by CmpFindDrivers().
BOOLEAN CmpOrderGroup (IN PBOOT_DRIVER_NODE GroupStart, IN PBOOT_DRIVER_NODE GroupEnd)
Definition at line 1323 of file cmboot.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _LIST_ENTRY::Flink, InsertTailList(), _BOOT_DRIVER_LIST_ENTRY::Link, _BOOT_DRIVER_NODE::ListEntry, RemoveEntryList(), _BOOT_DRIVER_NODE::Tag, and TRUE.
Referenced by CmpResolveDriverDependencies().
BOOLEAN CmpResolveDriverDependencies (IN PLIST_ENTRY DriverListHead)
Definition at line 1246 of file cmboot.c.
References CmpOrderGroup(), CONTAINING_RECORD, _LIST_ENTRY::Flink, _BOOT_DRIVER_NODE::Group, RtlEqualUnicodeString(), and TRUE.
Referenced by CmGetSystemDriverList().
VOID CmpSetCurrentProfile (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PCM_HARDWARE_PROFILE Profile)
Definition at line 1751 of file cmboot.c.
References ASSERT, CmpFindProfileOption(), CmpFindValueByName(), CmpValueToData(), HCELL_NIL, HvGetCell, NULL, REG_DWORD, RtlInitUnicodeString(), and _CM_KEY_VALUE::Type.
BOOLEAN CmpSortDriverList (IN PHHIVE Hive, IN HCELL_INDEX ControlSet, IN PLIST_ENTRY DriverListHead)
Definition at line 1029 of file cmboot.c.
References ASSERT, _UNICODE_STRING::Buffer, CmpDoSort(), CmpFindSubKeyByName(), CmpFindValueByName(), CmpValueToData(), FALSE, HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, REG_MULTI_SZ, RtlInitUnicodeString(), and _CM_KEY_VALUE::Type.
Referenced by CmGetSystemDriverList().
BOOLEAN CmpValidateSelect (IN PHHIVE SystemHive, IN HCELL_INDEX RootCell)
Definition at line 1406 of file cmboot.c.
References ASSERT, CmpFindSubKeyByName(), CmpFindValueByName(), FALSE, HCELL_NIL, HvGetCell, NULL, RtlInitUnicodeString(), and TRUE.