Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/procsup.c File Reference
procsup.c File Reference
#include "mi.h"
Data Structures
struct _MMPTE_DELETE_LIST
Macros
#define DONTASSERT(x)
#define KERNEL_BSTORE_SIZE 0
#define KERNEL_LARGE_BSTORE_COMMIT 0
#define KERNEL_LARGE_BSTORE_SIZE 0
#define KERNEL_STACK_GUARD_PAGES 1
#define MI_INIT_PEB_FROM_IMAGE(Hdrs, ImgConfig)
#define MI_LARGE_STACK_SIZE MmLargeStackSize
#define MI_STACK_IS_TRIMMABLE(_THREAD) (_THREAD->LargeStack)
#define MM_PROCESS_CREATE_CHARGE 6
Typedefs
typedef struct _MMPTE_DELETE_LIST MMPTE_DELETE_LIST
typedef struct _MMPTE_DELETE_LIST * PMMPTE_DELETE_LIST
Functions
PMMVAD MiAllocateVad (IN ULONG_PTR StartingVirtualAddress, IN ULONG_PTR EndingVirtualAddress, IN LOGICAL Deletable)
VOID MiAllowWorkingSetExpansion (IN PMMSUPPORT WsInfo)
NTSTATUS MiCreatePebOrTeb (IN PEPROCESS TargetProcess, IN ULONG Size, OUT PVOID *Base)
VOID MiDeleteAddressesInWorkingSet (IN PEPROCESS Process)
VOID MiDeletePteList (IN PMMPTE_DELETE_LIST PteDeleteList, IN PEPROCESS CurrentProcess)
VOID MiDeletePteRange (IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte, IN PMMPTE LastPte, IN LOGICAL AddressSpaceDeletion)
VOID MiInPageSingleKernelStack (IN PKTHREAD Thread, IN PKERNEL_STACK_SEGMENT StackInfo)
VOID MiInsertHandBuiltProcessIntoList (IN PEPROCESS ProcessToInitialize)
PFN_NUMBER MiMakeOutswappedPageResident (IN PMMPTE ActualPteAddress, IN PMMPTE PointerTempPte, IN ULONG Global, IN PFN_NUMBER ContainingPage, IN KIRQL OldIrql)
PFN_NUMBER MiMakeOutswappedPageResident (IN PMMPTE ActualPteAddress, IN OUT PMMPTE PointerTempPte, IN ULONG Global, IN PFN_NUMBER ContainingPage, IN KIRQL OldIrql)
VOID MiOutPageSingleKernelStack (IN PKTHREAD Thread, IN PKERNEL_STACK_SEGMENT StackInfo, IN PMMPTE_FLUSH_LIST PteFlushList)
UCHAR MiSetMemoryPriorityProcess (IN PEPROCESS Process, IN UCHAR MemoryPriority)
VOID MiUnlinkWorkingSet (IN PMMSUPPORT WsInfo)
VOID MiUpdateSystemPdes (IN PEPROCESS Process)
VOID MmCleanProcessAddressSpace (IN PEPROCESS Process)
PVOID MmCreateKernelStack (IN BOOLEAN LargeStack, IN UCHAR PreferredNode)
NTSTATUS MmCreatePeb (IN PEPROCESS TargetProcess, IN PINITIAL_PEB InitialPeb, OUT PPEB *Base)
NTSTATUS MmCreateTeb (IN PEPROCESS TargetProcess, IN PINITIAL_TEB InitialTeb, IN PCLIENT_ID ClientId, OUT PTEB *Base)
VOID MmDeleteKernelStack (IN PVOID PointerKernelStack, IN BOOLEAN LargeStack)
VOID MmDeleteProcessAddressSpace (IN PEPROCESS Process)
VOID MmDeleteTeb (IN PEPROCESS TargetProcess, IN PVOID TebBase)
PFN_NUMBER MmGetDirectoryFrameFromProcess (IN PEPROCESS Process)
NTSTATUS MmGrowKernelStack (__in PVOID CurrentStack)
NTSTATUS MmGrowKernelStackEx (__in PVOID CurrentStack, __in SIZE_T CommitSize)
NTSTATUS MmInitializeHandBuiltProcess (IN PEPROCESS ProcessToInitialize, OUT PULONG_PTR DirectoryTableBase)
NTSTATUS MmInitializeHandBuiltProcess2 (IN PEPROCESS ProcessToInitialize)
NTSTATUS MmInitializeProcessAddressSpace (IN PEPROCESS ProcessToInitialize, IN PEPROCESS ProcessToClone OPTIONAL, IN PVOID SectionToMap OPTIONAL, IN OUT PULONG CreateFlags, OUT POBJECT_NAME_INFORMATION *AuditName OPTIONAL)
VOID MmInPageKernelStack (IN PKTHREAD Thread)
VOID MmInSwapProcess (IN PKPROCESS Process)
VOID MmOutPageKernelStack (IN PKTHREAD Thread)
VOID MmOutSwapProcess (IN PKPROCESS Process)
VOID MmSetMemoryPriorityProcess (IN PEPROCESS Process, IN UCHAR MemoryPriority)
VOID VadTreeWalk (VOID)
Variables
PVOID BBTBuffer
MMPTE KernelDemandZeroPte = {MM_KERNEL_DEMAND_ZERO_PTE}
LOGICAL MiSafeBooted
ULONG MiStackGrowthFailures [1]
ULONG MmAllocationPreference
LONG MmKernelStackPages
PFN_NUMBER MmKernelStackResident
LONG MmLargeStacks
ULONG MmLargeStackSize = KERNEL_LARGE_STACK_SIZE
PFN_NUMBER MmLeakedLockedPages
ULONG MmMinimumStackCommitInBytes
SIZE_T MmProcessCommit
LIST_ENTRY MmProcessList
CCHAR MmRotatingUniprocessorNumber
LONG MmSmallStacks
MM_SYSTEMSIZE MmSystemSize
Macro Definition Documentation
#define DONTASSERT (x)
Definition at line 69 of file procsup.c.
Referenced by MmCreatePeb(), and MmCreateTeb().
#define KERNEL_BSTORE_SIZE 0
Definition at line 3111 of file procsup.c.
Referenced by MmCreateKernelStack(), and MmDeleteKernelStack().
#define KERNEL_LARGE_BSTORE_COMMIT 0
Definition at line 3113 of file procsup.c.
Referenced by MmCreateKernelStack().
#define KERNEL_LARGE_BSTORE_SIZE 0
Definition at line 3112 of file procsup.c.
Referenced by MmCreateKernelStack(), and MmDeleteKernelStack().
#define KERNEL_STACK_GUARD_PAGES 1
Definition at line 3114 of file procsup.c.
Referenced by MmCreateKernelStack(), and MmDeleteKernelStack().
#define MI_INIT_PEB_FROM_IMAGE (Hdrs, ImgConfig)
Definition at line 5630 of file procsup.c.
Referenced by MmCreatePeb().
#define MI_LARGE_STACK_SIZE MmLargeStackSize
Definition at line 43 of file procsup.c.
Referenced by MiOutPageSingleKernelStack(), MmCreateKernelStack(), MmDeleteKernelStack(), MmGrowKernelStackEx(), MmInPageKernelStack(), and MmOutPageKernelStack().
#define MI_STACK_IS_TRIMMABLE (_THREAD) (_THREAD->LargeStack)
Definition at line 66 of file procsup.c.
Referenced by MiInPageSingleKernelStack(), and MiOutPageSingleKernelStack().
#define MM_PROCESS_CREATE_CHARGE 6
Definition at line 46 of file procsup.c.
Referenced by MmCleanProcessAddressSpace(), and MmDeleteProcessAddressSpace().
Typedef Documentation
typedef struct _MMPTE_DELETE_LIST MMPTE_DELETE_LIST
typedef struct _MMPTE_DELETE_LIST * PMMPTE_DELETE_LIST
Function Documentation
PMMVAD MiAllocateVad (IN ULONG_PTR StartingVirtualAddress, IN ULONG_PTR EndingVirtualAddress, IN LOGICAL Deletable)
Definition at line 7162 of file procsup.c.
References ASSERT, _MMVAD_FLAGS::CommitCharge, _MMVAD_LONG::EndingVpn, _MMADDRESS_LIST::EndVpn, ExAllocatePoolWithTag, _MMVAD_LONG::LongFlags, _MMVAD_LONG::LongFlags2, _MMVAD_FLAGS2::LongVad, MI_VA_TO_VPN, MM_MAX_COMMIT, MM_READONLY, _MMVAD_FLAGS::NoChange, NonPagedPool, NULL, _MMVAD_FLAGS2::OneSecured, _MMVAD_FLAGS::PrivateMemory, _MMVAD_FLAGS::Protection, _MMVAD_FLAGS2::ReadOnly, _MMVAD_LONG::Secured, _MMVAD_LONG::StartingVpn, _MMADDRESS_LIST::StartVpn, TRUE, _MMVAD_LONG::u, _MMVAD_LONG::u2, _MMVAD_LONG::u3, _MMVAD_LONG::VadFlags, and _MMVAD_LONG::VadFlags2.
Referenced by MmInitializeHandBuiltProcess2(), and MmInitializeProcessAddressSpace().
VOID MiAllowWorkingSetExpansion (IN PMMSUPPORT WsInfo)
Definition at line 6314 of file procsup.c.
References ASSERT, InsertTailList(), _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, MM_WS_NOT_LISTED, MmWorkingSetExpansionHead, and UNLOCK_EXPANSION.
Referenced by MiInitializeSystemCache(), MmInitializeHandBuiltProcess(), and MmInitializeProcessAddressSpace().
NTSTATUS MiCreatePebOrTeb (IN PEPROCESS TargetProcess, IN ULONG Size, OUT PVOID * Base)
Definition at line 5246 of file procsup.c.
References BYTES_TO_PAGES, _MMVAD_FLAGS::CommitCharge, _MMVAD_LONG::EndingVpn, _MMADDRESS_LIST::EndVpn, ExAllocatePoolWithTag, ExFreePool(), FALSE, KeQueryTickCount(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _MMVAD_LONG::LongFlags, _MMVAD_LONG::LongFlags2, _MMVAD_FLAGS2::LongVad, _LARGE_INTEGER::LowPart, _MMVAD_FLAGS::MemCommit, MI_VA_TO_VPN, MI_VPN_TO_VA_ENDING, MiCheckForConflictingVadExistence(), MiFindEmptyAddressRangeDown, MiInsertVad(), MiInsertVadCharges(), MM_HIGHEST_VAD_ADDRESS, MM_READWRITE, _MMVAD_FLAGS::NoChange, NonPagedPool, NT_SUCCESS, NULL, _MMVAD_FLAGS2::OneSecured, PAGE_SHIFT, PAGE_SIZE, _MMVAD_FLAGS::PrivateMemory, _MMVAD_FLAGS::Protection, PsGetCurrentThread(), _MMVAD_FLAGS2::ReadOnly, ROUND_TO_PAGES, _MMVAD_LONG::Secured, _MMVAD_LONG::StartingVpn, _MMADDRESS_LIST::StartVpn, Status, STATUS_NO_MEMORY, _MMVAD_LONG::u, _MMVAD_LONG::u2, _MMVAD_LONG::u3, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, _MMVAD_LONG::VadFlags, _MMVAD_LONG::VadFlags2, and X64K.
Referenced by MmCreatePeb(), and MmCreateTeb().
VOID MiDeleteAddressesInWorkingSet (IN PEPROCESS Process)
Definition at line 6360 of file procsup.c.
References ASSERT, _MMPTE_DELETE_LIST::Count, _MMWSLENTRY::Direct, _MMWSLE::e1, FALSE, _MMPTE::Hard, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_PFN_ELEMENT, MiDeletePteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiLocateWsle(), MiReleaseWsle(), MiSwapWslEntries(), MM_HIGHEST_USER_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, MmWorkingSetList, MmWsle, NULL, PAGE_ALIGN, _MMPTE_DELETE_LIST::PointerPte, _MMPTE_DELETE_LIST::PteContents, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, and _MMPFN::WsIndex.
Referenced by MmCleanProcessAddressSpace().
VOID MiDeletePteList (IN PMMPTE_DELETE_LIST PteDeleteList, IN PEPROCESS CurrentProcess)
Definition at line 6535 of file procsup.c.
References ASSERT, _MMPTE_FLUSH_LIST::Count, _MMPFN::e1, FALSE, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_PFN, _MMPTE::Long, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_PROCESS_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_INVALID_PTE, MiDecrementCloneBlockReference(), MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiLocateCloneAddress, MM_DEMAND_ZERO_WRITE_PTE, MM_HIGHEST_USER_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, NULL, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiDeleteAddressesInWorkingSet().
VOID MiDeletePteRange (IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte, IN PMMPTE LastPte, IN LOGICAL AddressSpaceDeletion)
Definition at line 2160 of file procsup.c.
References _MI_PAGING_LEVELS, ASSERT, CONTAINING_RECORD, _MMPTE_FLUSH_LIST::Count, _MMPFN::e2, FALSE, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_PROCESS_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MiDeletePte(), MiDeleteValidSystemPte(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiReturnCommitment, MM_DBG_COMMIT_RETURN_PTE_RANGE, MM_MAXIMUM_FLUSH_COUNT, MM_RESAVAIL_FREE_CLEAN_PROCESS_WS, MM_TRACK_COMMIT, MmWorkingSetList, NOTHING, NULL, _EPROCESS::NumberOfPrivatePages, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and _MMPFN::WsIndex.
Referenced by MiRemoveWorkingSetPages(), and MmCleanProcessAddressSpace().
VOID MiInPageSingleKernelStack (IN PKTHREAD Thread, IN PKERNEL_STACK_SEGMENT StackInfo)
Definition at line 4046 of file procsup.c.
References ASSERT, _MMPTE::Hard, InterlockedExchangeAddSizeT, KeBugCheckEx(), KERNEL_LARGE_STACK_COMMIT, KERNEL_STACK_INPAGE_ERROR, LOCK_PFN, _MMPTE::Long, MEMORY_MANAGEMENT, MI_GET_PAGE_FRAME_FROM_PTE, MI_STACK_IS_TRIMMABLE, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiMakeOutswappedPageResident(), MM_KERNEL_DEMAND_ZERO_PTE, MM_NOACCESS, MmKernelStackResident, PAGE_READWRITE, PAGE_SIZE, _MMPTE_SOFTWARE::Protection, ROUND_TO_PAGES, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmInPageKernelStack().
VOID MiInsertHandBuiltProcessIntoList (IN PEPROCESS ProcessToInitialize)
Definition at line 1470 of file procsup.c.
References ASSERT, InsertTailList(), LOCK_EXPANSION, NULL, and UNLOCK_EXPANSION.
Referenced by MmInitializeHandBuiltProcess().
PFN_NUMBER MiMakeOutswappedPageResident (IN PMMPTE ActualPteAddress, IN PMMPTE PointerTempPte, IN ULONG Global, IN PFN_NUMBER ContainingPage, IN KIRQL OldIrql)
Referenced by MiInPageSingleKernelStack(), and MmInSwapProcess().
PFN_NUMBER MiMakeOutswappedPageResident (IN PMMPTE ActualPteAddress, IN OUT PMMPTE PointerTempPte, IN ULONG Global, IN PFN_NUMBER ContainingPage, IN KIRQL OldIrql)
Definition at line 6738 of file procsup.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, FALSE, GET_PAGING_FILE_NUMBER, GET_PAGING_FILE_OFFSET, _IO_STATUS_BLOCK::Information, _MMPFN::InPageError, InterlockedIncrementPfn, IoPageRead(), KeBugCheckEx(), KeClearEvent(), KeDelayExecutionThread(), KeInitializeEvent(), KERNEL_STACK_INPAGE_ERROR, KernelMode, KeWaitForSingleObject(), LOCK_PFN, _MMPTE::Long, _LARGE_INTEGER::LowPart, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_MAKE_TRANSITION_KERNELPTE_VALID, MI_MAKE_TRANSITION_PTE_VALID, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_SET_GLOBAL_STATE, MI_SET_MODIFIED, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiCached, MiEnsureAvailablePageOrWait(), MiFaultRetryMask, MiGetVirtualAddressMappedByPte, MiInitializePfnForOtherProcess(), MiMapPageInHyperSpace(), MiReleasePageFileSpace(), MiRemoveAnyPage(), MiUnlinkPageFromList(), MiUnmapPageInHyperSpace, MM_HIGH_LIMIT, MM_KERNEL_DEMAND_ZERO_PTE, MM_PFN_LOCK_ASSERT, MM_READWRITE, MmAvailablePages, MmHalfSecond, MmInitializeMdl, MmIsRetryIoStatus, MmPagingFile, MmUnmapLockedPages(), NotificationEvent, NT_SUCCESS, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPFNENTRY::PageLocation, PsGetCurrentProcess(), _LARGE_INTEGER::QuadPart, _MMPFNENTRY::ReadInProgress, RtlFillMemoryUlong(), _MMPFN::ShareCount, Status, _IO_STATUS_BLOCK::Status, STATUS_PENDING, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPFNENTRY::WriteInProgress, and WrPageIn.
VOID MiOutPageSingleKernelStack (IN PKTHREAD Thread, IN PKERNEL_STACK_SEGMENT StackInfo, IN PMMPTE_FLUSH_LIST PteFlushList)
Definition at line 3712 of file procsup.c.
References ASSERT, BYTE_OFFSET, Count, _MMPTE::Hard, InterlockedExchangeAddSizeT, KERNEL_LARGE_STACK_COMMIT, KERNEL_LARGE_STACK_SIZE, KernelDemandZeroPte, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_LARGE_STACK_SIZE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_STACK_IS_TRIMMABLE, MI_WRITE_INVALID_PTE, MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MM_MAXIMUM_FLUSH_COUNT, MM_NOACCESS, MM_RESAVAIL_FREE_OUTPAGE_STACK, MmKernelStackResident, NULL, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_SOFTWARE::Protection, _MMPFN::PteFrame, ROUND_TO_PAGES, _MMPTE::Soft, _MMPTE::u, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmOutPageKernelStack().
UCHAR MiSetMemoryPriorityProcess (IN PEPROCESS Process, IN UCHAR MemoryPriority)
Definition at line 7084 of file procsup.c.
References LOCK_EXPANSION, and UNLOCK_EXPANSION.
Referenced by MmSetMemoryPriorityProcess().
VOID MiUnlinkWorkingSet (IN PMMSUPPORT WsInfo)
Definition at line 2467 of file procsup.c.
References ASSERT, FALSE, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeWaitForSingleObject(), LOCK_EXPANSION, MM_WS_NOT_LISTED, MM_WS_TRIMMING, NotificationEvent, NULL, RemoveEntryList(), UNLOCK_EXPANSION, and WrVirtualMemory.
Referenced by MmCleanProcessAddressSpace().
VOID MiUpdateSystemPdes (IN PEPROCESS Process)
Definition at line 368 of file procx86.c.
References ASSERT, _KPROCESS::DirectoryTableBase, DISPATCH_LEVEL, _MMPTE::Hard, KeGetCurrentIrql(), _MMPTE::Long, MI_FLUSH_CURRENT_TB_SINGLE, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiGetPdeOffset, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpaceAtDpc(), MiPteRangeIndex, MiPteRanges, MiUnmapPageInHyperSpaceFromDpc, NULL, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, PsGetCurrentProcess(), PsInitialSystemProcess, RtlCopyMemory, _MMPTE::u, and ValidKernelPte.
Referenced by MmInitializeProcessAddressSpace(), and MmInSwapProcess().
VOID MmCleanProcessAddressSpace (IN PEPROCESS Process)
Definition at line 2563 of file procsup.c.
References ASSERT, _LOCK_TRACKER::CallersCaller, _LOCK_TRACKER::CallingAddress, CONTAINING_RECORD, _MMVAD::ControlArea, _LOCK_HEADER::Count, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS, _MMVAD::EndingVpn, _MMVAD_SHORT::EndingVpn, ERROR_LOG_MAXIMUM_SIZE, _IO_ERROR_LOG_PACKET::ErrorCode, ExFreePool(), FALSE, _IO_ERROR_LOG_PACKET::FinalStatus, _LIST_ENTRY::Flink, InterlockedExchangeAddSizeT, IoAllocateGenericErrorLogEntry(), IoWriteErrorLogEntry(), IsListEmpty, KdDebuggerEnabled, KdDebuggerNotPresent, KeBugCheckEx(), _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _LOCK_TRACKER::Mdl, MI_INCREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiAweViewRemover(), MiCleanPhysicalProcessPages(), MiDeleteAddressesInWorkingSet(), MiDeletePageTablesForPhysicalRange(), MiDeletePteRange(), MiDeleteVirtualAddresses(), MiFreeLargePages(), MiGetPteAddress, MiPhysicalViewRemover(), MiReleasePhysicalCharges(), MiRemoveMappedView(), MiRemoveUserPhysicalPagesVad(), MiRemoveVad(), MiRemoveVadCharges(), MiRemoveWorkingSetPages(), MiReturnCommitment, MiSafeBooted, MiSessionRemoveProcess(), MiUnlinkWorkingSet(), MM_DBG_COMMIT_RETURN_PROCESS_CLEAN_PAGETABLES, MM_DBG_PRIVATE_PAGES, MM_HIGHEST_VAD_ADDRESS, MM_MAXIMUM_WORKING_SET, MM_PROCESS_CREATE_CHARGE, MM_RESAVAIL_FREE_CLEAN_PROCESS1, MM_RESAVAIL_FREE_CLEAN_PROCESS2, MM_SHARED_USER_DATA_VA, MM_TRACK_COMMIT, MM_WS_NOT_LISTED, MmHighestUserAddress, MmLeakedLockedPages, MmPagesAboveWsMinimum, MmTrackLockedPages, MmWorkingSetList, MmWsle, NULL, PAGE_SHIFT, _MMVAD_FLAGS::PrivateMemory, PS_CLEAR_BITS, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_PROCESS_FLAGS_ADDRESS_SPACE1, PS_PROCESS_FLAGS_VM_DELETED, PS_SET_BITS, PsChangeJobMemoryUsage(), PsGetCurrentThread(), PsReturnProcessPageFileQuota(), RemoveEntryList(), _MMVAD::RightChild, _MMVAD::StartingVpn, _MMVAD_SHORT::StartingVpn, STATUS_DRIVERS_LEAKING_LOCKED_PAGES, TRUE, _MMVAD::u, _IO_ERROR_LOG_PACKET::UniqueErrorValue, UNLOCK_WS_AND_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, VadWriteWatch, and _LOCK_HEADER::Valid.
Referenced by PspExitProcess(), and PspExitThread().
PVOID MmCreateKernelStack (IN BOOLEAN LargeStack, IN UCHAR PreferredNode)
Definition at line 3118 of file procsup.c.
References ASSERT, BYTES_TO_PAGES, DemandZeroPte, ExQueryDepthSList, FALSE, _MMPTE::Hard, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedIncrement, InterlockedPopEntrySList(), KeNodeBlock, KERNEL_BSTORE_SIZE, KERNEL_LARGE_BSTORE_COMMIT, KERNEL_LARGE_BSTORE_SIZE, KERNEL_LARGE_STACK_COMMIT, KERNEL_STACK_GUARD_PAGES, KERNEL_STACK_SIZE, LOCK_PFN, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_NODE, MI_LARGE_STACK_SIZE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_KERNEL_STACK_CREATE, MM_HIGH_LIMIT, MM_KERNEL_DEMAND_ZERO_PTE, MM_NOACCESS, MM_READWRITE, MM_RESAVAIL_ALLOCATE_CREATE_STACK, MM_TRACK_COMMIT, MmAvailablePages, MmDeadStackSListHead, MmKernelStackPages, MmKernelStackResident, MmLargeStacks, MmProcessCommit, MmSmallStacks, NULL, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPFN::PteAddress, _MMPTE::Soft, SystemPteSpace, _MMPTE::u, UNLOCK_PFN, UNREFERENCED_PARAMETER, and _MMPTE_HARDWARE::Valid.
NTSTATUS MmCreatePeb (IN PEPROCESS TargetProcess, IN PINITIAL_PEB InitialPeb, OUT PPEB * Base)
Definition at line 5928 of file procsup.c.
References _IMAGE_FILE_HEADER::Characteristics, CmNtCSDVersion, DONTASSERT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _IMAGE_NT_HEADERS::FileHeader, _LARGE_INTEGER::HighPart, IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG, IMAGE_FILE_UP_SYSTEM_ONLY, InitAnsiCodePageDataOffset, InitNlsSectionPointer, InitOemCodePageDataOffset, InitUnicodeCaseTableDataOffset, KeActiveProcessors, KeAttachProcess(), KeDetachProcess(), KeNumberProcessors, _LARGE_INTEGER::LowPart, _IMAGE_OPTIONAL_HEADER::Magic, MEM_TOP_DOWN, MI_INIT_PEB_FROM_IMAGE, MiCreatePebOrTeb(), MmCriticalSectionTimeout, MmGetSessionId(), MmHeapDeCommitFreeBlockThreshold, MmHeapDeCommitTotalFreeThreshold, MmHeapSegmentCommit, MmHeapSegmentReserve, MmMapViewOfSection(), MmMinimumStackCommitInBytes, MmRotatingUniprocessorNumber, NT_SUCCESS, NtBuildNumber, NtGlobalFlag, NtMajorVersion, NtMinorVersion, NULL, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_READONLY, PAGE_SIZE, PROBE_ALIGNMENT, ProbeForReadSmallStructure, ProcessAffinityMask, IMAGE_LOAD_CONFIG_DIRECTORY32::ProcessAffinityMask, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), SEC_NO_CHANGE, Status, STATUS_INVALID_IMAGE_PROTECT, STATUS_SUCCESS, TRUE, and ViewShare.
Referenced by PspCreateProcess().
NTSTATUS MmCreateTeb (IN PEPROCESS TargetProcess, IN PINITIAL_TEB InitialTeb, IN PCLIENT_ID ClientId, OUT PTEB * Base)
Definition at line 5421 of file procsup.c.
References ASSERT, BBTBuffer, DONTASSERT, except, EXCEPTION_CHAIN_END, EXCEPTION_EXECUTE_HANDLER, KeAttachProcess(), KeDetachProcess(), MiCreatePebOrTeb(), NT_SUCCESS, NULL, OS2_VERSION, PROBE_ALIGNMENT, ProbeForReadSmallStructure, PsGetCurrentProcess(), PtrToUlong, ROUND_TO_PAGES, RtlCopyMemory, _INITIAL_TEB::StackAllocationBase, _INITIAL_TEB::StackBase, _INITIAL_TEB::StackLimit, Status, and _WOW64_PROCESS::Wow64.
Referenced by PspCreateThread().
VOID MmDeleteKernelStack (IN PVOID PointerKernelStack, IN BOOLEAN LargeStack)
Definition at line 3307 of file procsup.c.
References ASSERT, BYTES_TO_PAGES, _MMPFN::e1, ExQueryDepthSList, _MMPTE::Hard, InterlockedDecrement, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedPushEntrySList(), KeNodeBlock, KeNumberNodes, KERNEL_BSTORE_SIZE, KERNEL_LARGE_BSTORE_SIZE, KERNEL_STACK_GUARD_PAGES, KERNEL_STACK_SIZE, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_LARGE_STACK_SIZE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiReleaseSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_RETURN_KERNEL_STACK_DELETE, MM_RESAVAIL_FREE_DELETE_STACK, MM_TRACK_COMMIT, MmDeadStackSListHead, MmKernelStackPages, MmKernelStackResident, MmLargeStacks, MmMaximumDeadKernelStacks, MmProcessCommit, MmSmallStacks, _MMPFN::NextStackPfn, _MMPFNENTRY::PageColor, _MMPTE_HARDWARE::PageFrameNumber, PSLIST_ENTRY, _MMPFN::PteFrame, SystemPteSpace, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by KeInitThread(), KeStartAllProcessors(), KeUninitThread(), PsConvertToGuiThread(), PspReaper(), and PspThreadDelete().
VOID MmDeleteProcessAddressSpace (IN PEPROCESS Process)
Definition at line 1802 of file procsup.c.
References ASSERT, _MMPFN::e1, _MMPFN::e2, HYPER_SPACE, InterlockedExchangeAddSizeT, LOCK_EXPANSION, LOCK_PFN, MI_GET_DIRECTORY_FRAME_FROM_PROCESS, MI_GET_HYPER_PAGE_TABLE_FRAME_FROM_PROCESS, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiContractPagingFiles(), MiDecrementShareCount(), MiGetPpeOffset, MiGetPteOffset, MiGetPxeOffset, MiInsertPageInFreeList(), MiMapPageInHyperSpaceAtDpc(), MiReleaseProcessReferenceToSessionDataPage(), MiReturnCommitment, MiUnmapPageInHyperSpaceFromDpc, MM_DBG_COMMIT_RETURN_PROCESS_DELETE, MM_PROCESS_COMMIT_CHARGE, MM_PROCESS_CREATE_CHARGE, MM_RESAVAIL_FREE_DELETE_PROCESS, MM_TRACK_COMMIT, MmProcessCommit, NULL, PD_PER_SYSTEM, PsGetCurrentProcess(), _MMPFN::PteFrame, RemoveEntryList(), _MMPFN::u3, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, and _MMPFNENTRY::WriteInProgress.
Referenced by PspProcessDelete().
VOID MmDeleteTeb (IN PEPROCESS TargetProcess, IN PVOID TebBase)
Definition at line 6175 of file procsup.c.
References ASSERT, CONTAINING_RECORD, _MMVAD_LONG::EndingVpn, ExFreePool(), _LIST_ENTRY::Flink, IsListEmpty, KeAttachProcess(), KeDetachProcess(), List, _MMSECURE_ENTRY::List, _MMVAD_LONG::List, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_VA_TO_VPN, MiDeleteVirtualAddresses(), MiGetNextVad, MiGetPreviousVad, MiLocateAddress(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), _MMVAD_FLAGS2::MultipleSecured, _MMVAD_FLAGS::NoChange, NT_SUCCESS, NULL, _MMVAD_FLAGS2::OneSecured, PsGetCurrentThread(), ROUND_TO_PAGES, _MMVAD_LONG::StartingVpn, Status, STATUS_NOT_FOUND, STATUS_SUCCESS, _MMVAD_LONG::u, _MMVAD_LONG::u2, _MMVAD_LONG::u3, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_AND_ADDRESS_SPACE, _MMVAD_LONG::VadFlags, and _MMVAD_LONG::VadFlags2.
Referenced by PspCreateThread(), and PspExitThread().
PFN_NUMBER MmGetDirectoryFrameFromProcess (IN PEPROCESS Process)
Definition at line 7239 of file procsup.c.
References ASSERT, KeGetCurrentIrql(), MI_GET_DIRECTORY_FRAME_FROM_PROCESS, and PASSIVE_LEVEL.
Referenced by ExpCopyProcessInfo(), MmInSwapProcess(), and WmiTraceProcess().
NTSTATUS MmGrowKernelStack (__in PVOID CurrentStack)
Definition at line 3531 of file procsup.c.
References KERNEL_LARGE_STACK_COMMIT, and MmGrowKernelStackEx().
NTSTATUS MmGrowKernelStackEx (__in PVOID CurrentStack, __in SIZE_T CommitSize)
Definition at line 3564 of file procsup.c.
References ASSERT, DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _MMPTE::Hard, InterlockedExchangeAddSizeT, KeGetCurrentThread(), LOCK_PFN, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_LARGE_STACK_SIZE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_SET_PTE_DIRTY, MiEnsureAvailablePageOrWait(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiRemoveAnyPage(), MM_HIGH_LIMIT, MM_KERNEL_DEMAND_ZERO_PTE, MM_NOACCESS, MM_READWRITE, MM_RESAVAIL_ALLOCATE_GROW_STACK, MmAvailablePages, MmKernelStackResident, NULL, PAGE_SIZE, PERFINFO_GROW_STACK, _MMPTE_SOFTWARE::Protection, _MMPTE::Soft, _KTHREAD::StackBase, _KTHREAD::StackLimit, STATUS_NO_MEMORY, STATUS_STACK_OVERFLOW, STATUS_SUCCESS, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmGrowKernelStack().
NTSTATUS MmInitializeHandBuiltProcess (IN PEPROCESS ProcessToInitialize, OUT PULONG_PTR DirectoryTableBase)
Definition at line 1498 of file procsup.c.
References ASSERT, _KPROCESS::DirectoryTableBase, ExInitializePushLock(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeQuerySystemTime(), MiAllowWorkingSetExpansion(), MiInsertHandBuiltProcessIntoList(), MmCreateProcessAddressSpace(), MmWorkingSetList, _EPROCESS::Pcb, PsGetCurrentProcess(), STATUS_SUCCESS, _EPROCESS::Vm, and _MMSUPPORT::WorkingSetSize.
Referenced by PspCreateProcess().
NTSTATUS MmInitializeHandBuiltProcess2 (IN PEPROCESS ProcessToInitialize)
Definition at line 1586 of file procsup.c.
References ASSERT, CODE_END, CODE_START, _LOCK_HEADER::Count, ExAllocatePoolWithTag, FALSE, InitializeListHead(), KeAttachProcess(), KeDetachProcess(), KeInitializeSpinLock(), _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, LOCK_WS, MI_GET_DIRECTORY_FRAME_FROM_PROCESS, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiAllocateVad(), MiGetPdeAddress, MiGetPdeOffset, MiGetVirtualAddressMappedByPte, MiInsertVad(), MiInsertVadCharges(), MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiUnmapPageInHyperSpace, MM_HIGHEST_VAD_ADDRESS, MM_NOIRQL, MM_READWRITE, MM_SHARED_USER_DATA_VA, MM_VA_MAPPED_BY_PDE, MmInitializeProcessAddressSpace(), MmTrackLockedPages, MmVirtualBias, NonPagedPool, NT_SUCCESS, NULL, PsGetCurrentProcess(), PsGetCurrentThread(), PsInitialSystemProcess, RtlCopyMemory, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, SystemPteSpace, TRUE, UNLOCK_WS, _LOCK_HEADER::Valid, and X64K.
Referenced by PspCreateProcess().
NTSTATUS MmInitializeProcessAddressSpace (IN PEPROCESS ProcessToInitialize, IN PEPROCESS ProcessToClone OPTIONAL, IN PVOID SectionToMap OPTIONAL, IN OUT PULONG CreateFlags, OUT POBJECT_NAME_INFORMATION *AuditName OPTIONAL)
Definition at line 603 of file procsup.c.
References _2gb, _4gb, _MI_PAGING_LEVELS, ASSERT, _UNICODE_STRING::Buffer, _MMVAD_FLAGS::CommitCharge, _LOCK_HEADER::Count, DemandZeroPte, ExAllocatePoolWithTag, ExFreePool(), ExInitializePushLock(), FALSE, _FILE_OBJECT::FileName, _MMPTE::Hard, HYPER_SPACE, IMAGE_FILE_LARGE_ADDRESS_AWARE, IMAGE_FILE_MACHINE_I386, _SECTION_IMAGE_INFORMATION::ImageCharacteristics, InitializeListHead(), KeAttachProcess(), KeDetachProcess(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeQuerySystemTime(), _UNICODE_STRING::Length, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, LOCK_EXPANSION, LOCK_PFN, LOCK_WS, _MMPTE::Long, _SECTION_IMAGE_INFORMATION::Machine, MEM_LARGE_PAGES, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE, MI_PDE_MAPS_LARGE_PAGE, MI_ROUND_TO_SIZE, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiAllocateVad(), MiAllowWorkingSetExpansion(), MiCheckForConflictingVad, MiCloneProcessAddressSpace(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiInitializeWorkingSetList(), MiInsertVad(), MiInsertVadCharges(), MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiUnmapPageInHyperSpace, MiUpdateSystemPdes(), MM_HIGHEST_VAD_ADDRESS, MM_KERNEL_DEMAND_ZERO_PTE, MM_READWRITE, MM_SHARED_USER_DATA_VA, MM_SYSTEM_RANGE_START, MM_USER_PAGE_DIRECTORY_PAGES, MM_USER_PAGE_DIRECTORY_PARENT_PAGES, MM_USER_PAGE_TABLE_PAGES, MM_VA_MAPPED_BY_PDE, MM_VA_MAPPED_BY_PPE, MmAllocationPreference, MmMapViewOfSection(), MmPagedPoolEnd, MmTrackLockedPages, MmWorkingSetList, NonPagedPool, NOTHING, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, PAGE_READWRITE, PAGE_SHIFT, PAGE_SIZE, PagedPool, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PROCESS_CREATE_FLAGS_LARGE_PAGES, PS_CLEAR_BITS, PS_PROCESS_FLAGS_ADDRESS_SPACE1, PS_PROCESS_FLAGS_ADDRESS_SPACE2, PS_PROCESS_FLAGS_OVERRIDE_ADDRESS_SPACE, PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED, PS_PROCESS_FLAGS_VM_TOP_DOWN, PS_PROCESS_FLAGS_WOW64_4GB_VA_SPACE, PS_SET_BITS, PsGetCurrentThread(), PsMapSystemDll(), PTE_PER_PAGE, RtlZeroMemory, SeInitializeProcessAuditName(), Status, STATUS_NO_MEMORY, STATUS_SECTION_NOT_IMAGE, STATUS_SUCCESS, strcpy(), _SECTION_IMAGE_INFORMATION::SubSystemMajorVersion, _SECTION_IMAGE_INFORMATION::SubSystemMinorVersion, SystemPteSpace, TRUE, _MMPTE::u, _MMVAD::u, UNLOCK_EXPANSION, UNLOCK_PFN, UNLOCK_WS, VAD_BITMAP_SPACE, _MMVAD::VadFlags, _MMPTE_HARDWARE::Valid, _LOCK_HEADER::Valid, ViewShare, _WOW64_PROCESS::Wow64, X64K, and ZERO_LARGE.
Referenced by MiInitMachineDependent(), MmInitializeHandBuiltProcess2(), and PspCreateProcess().
VOID MmInPageKernelStack (IN PKTHREAD Thread)
Definition at line 4179 of file procsup.c.
References ASSERT, FLG_DISABLE_PAGE_KERNEL_STACKS, _KERNEL_STACK_SEGMENT::InitialStack, _KERNEL_STACK_SEGMENT::KernelStack, MI_LARGE_STACK_SIZE, MiInPageSingleKernelStack(), NtGlobalFlag, PAGE_SIZE, _KERNEL_STACK_SEGMENT::StackBase, _KERNEL_STACK_SEGMENT::StackLimit, and TRUE.
Referenced by KiInSwapKernelStacks().
VOID MmInSwapProcess (IN PKPROCESS Process)
Definition at line 4842 of file procsup.c.
References _MI_PAGING_LEVELS, ASSERT, CONTAINING_RECORD, _MMPFN::Event, FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MMPTE::Flush, HandleToUlong, _MMPTE::Hard, HYPER_SPACE, INITIALIZE_DIRECTORY_TABLE_BASE, InsertTailList(), _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, LOCK_PFN, _MMPTE::Long, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPdeAddress, MiGetPdeOffset, MiGetPpeAddress, MiGetPpeOffset, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetPxeOffset, MiMakeOutswappedPageResident(), MiMapPageInHyperSpaceAtDpc(), MiSessionInSwapProcess(), MiUnmapPageInHyperSpaceFromDpc, MiUpdateSystemPdes(), MM_PROCESS_COMMIT_CHARGE, MM_WS_SWAPPED_OUT, MmGetDirectoryFrameFromProcess(), MmPaeMask, MmWorkingSetExpansionHead, MmWorkingSetList, _EPROCESS::PaeTop, PAGE_SHIFT, _PERFINFO_SWAPPROCESS_INFORMATION::PageDirectoryBase, _EPROCESS::PageDirectoryPte, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, _EPROCESS::PdeUpdateNeeded, PERF_MEMORY, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_INSWAPPROCESS, PerfInfoLogBytes(), _PERFINFO_SWAPPROCESS_INFORMATION::ProcessId, PS_CLEAR_BITS, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_OUTSWAP_ENABLED, PS_PROCESS_FLAGS_OUTSWAPPED, PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, _EPROCESS::Vm, _MMSUPPORT::WorkingSetExpansionLinks, _EPROCESS::WorkingSetPage, _MMSUPPORT::WorkingSetSize, and _MMPFN::WsIndex.
Referenced by KiInSwapProcesses().
VOID MmOutPageKernelStack (IN PKTHREAD Thread)
Definition at line 3917 of file procsup.c.
References _KERNEL_STACK_SEGMENT::ActualLimit, ASSERT, _MMPTE_FLUSH_LIST::Count, FLG_DISABLE_PAGE_KERNEL_STACKS, _MMPTE_FLUSH_LIST::FlushVa, KERNEL_LARGE_STACK_SIZE, KERNEL_STACK_SIZE, _KERNEL_STACK_SEGMENT::KernelStack, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_LARGE_STACK_SIZE, MiOutPageSingleKernelStack(), MM_MAXIMUM_FLUSH_COUNT, NtGlobalFlag, NULL, PAGE_SIZE, SATISFY_OVERZEALOUS_COMPILER, _KERNEL_STACK_SEGMENT::StackBase, _KERNEL_STACK_SEGMENT::StackLimit, and TRUE.
Referenced by KiOutSwapKernelStacks().
VOID MmOutSwapProcess (IN PKPROCESS Process)
Definition at line 4475 of file procsup.c.
References ASSERT, CONTAINING_RECORD, _MMPFN::e1, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MMPTE::Flush, _MMPTE::Hard, LOCK_EXPANSION, LOCK_PFN, _MMPTE::Long, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_HYPER_PAGE_TABLE_FRAME_FROM_PROCESS, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiDecrementShareCount(), MiGetPdeOffset, MiGetPteAddress, MiGetPteOffset, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiSessionOutSwapProcess(), MiUnmapPageInHyperSpace, MM_DBG_SWAP_PROCESS, MM_PROCESS_COMMIT_CHARGE, MM_READWRITE, MM_WS_SWAPPED_OUT, MM_WS_TRIMMING, MmWorkingSetList, _MMPFNENTRY::Modified, NOTHING, NULL, _EPROCESS::Outswapped, _EPROCESS::PaeTop, _EPROCESS::PageDirectoryPte, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_OUTSWAP_ENABLED, PS_PROCESS_FLAGS_OUTSWAPPED, PS_SET_BITS, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, RemoveEntryList(), _MMPFN::ShareCount, SystemPteSpace, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMSUPPORT::WorkingSetExpansionLinks, _EPROCESS::WorkingSetPage, and _MMSUPPORT::WorkingSetSize.
Referenced by KiOutSwapProcesses().
VOID MmSetMemoryPriorityProcess (IN PEPROCESS Process, IN UCHAR MemoryPriority)
Definition at line 7122 of file procsup.c.
References MEMORY_PRIORITY_BACKGROUND, MiSetMemoryPriorityProcess(), MmNumberOfPhysicalPages, MmSmallSystem, MmSystemSize, and PAGE_SIZE.
Referenced by NtSetInformationProcess(), and PspComputeQuantumAndPriority().
VOID VadTreeWalk (VOID)
Variable Documentation
PVOID BBTBuffer
Referenced by MmCreateTeb().
MMPTE KernelDemandZeroPte = {MM_KERNEL_DEMAND_ZERO_PTE}
Definition at line 84 of file procsup.c.
Referenced by MiOutPageSingleKernelStack().
LOGICAL MiSafeBooted
Definition at line 57 of file mminit.c.
Referenced by MmCleanProcessAddressSpace(), and MmInitSystem().
ULONG MiStackGrowthFailures[1]
Definition at line 3528 of file procsup.c.
ULONG MmAllocationPreference
Definition at line 38 of file mminit.c.
Referenced by MmInitializeProcessAddressSpace(), and MmInitSystem().
LONG MmKernelStackPages
Definition at line 79 of file procsup.c.
Referenced by MmCreateKernelStack(), and MmDeleteKernelStack().
PFN_NUMBER MmKernelStackResident
Definition at line 80 of file procsup.c.
Referenced by MiInPageSingleKernelStack(), MiOutPageSingleKernelStack(), MmCreateKernelStack(), MmDeleteKernelStack(), and MmGrowKernelStackEx().
LONG MmLargeStacks
Definition at line 81 of file procsup.c.
Referenced by MmCreateKernelStack(), and MmDeleteKernelStack().
ULONG MmLargeStackSize = KERNEL_LARGE_STACK_SIZE
Definition at line 41 of file procsup.c.
Referenced by MiInitMachineDependent().
PFN_NUMBER MmLeakedLockedPages
Definition at line 88 of file procsup.c.
Referenced by MmCleanProcessAddressSpace().
ULONG MmMinimumStackCommitInBytes
Definition at line 96 of file procsup.c.
Referenced by MmCreatePeb().
SIZE_T MmProcessCommit
Definition at line 77 of file procsup.c.
Referenced by MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmDeleteKernelStack(), and MmDeleteProcessAddressSpace().
LIST_ENTRY MmProcessList
Definition at line 154 of file procsup.c.
Referenced by MiInitializeLargePageSupport(), MiMapWithLargePages(), MiUnmapLargePages(), and MmCreateProcessAddressSpace().
CCHAR MmRotatingUniprocessorNumber
Definition at line 86 of file procsup.c.
Referenced by MmCreatePeb().
LONG MmSmallStacks
Definition at line 82 of file procsup.c.
Referenced by MmCreateKernelStack(), and MmDeleteKernelStack().
MM_SYSTEMSIZE MmSystemSize
Definition at line 220 of file mminit.c.
Referenced by MmInitSystem(), MmQuerySystemSize(), and MmSetMemoryPriorityProcess().