Windows Research Kernel v1.2: C:/Windows Research Kernel/se/adtlog.c File Reference
adtlog.c File Reference
#include "pch.h"
#include <msaudite.h>
Functions
NTSTATUS SepAdtCopyToLsaSharedMemory (IN HANDLE LsaProcessHandle, IN PVOID Buffer, IN ULONG BufferLength, OUT PVOID *LsaBufferAddress)
VOID SepAdtLogAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters)
NTSTATUS SepAdtMarshallAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters, OUT PSE_ADT_PARAMETER_ARRAY *MarshalledAuditParameters, OUT PSEP_RM_LSA_MEMORY_TYPE RecordMemoryType)
VOID SepAuditFailed (IN NTSTATUS AuditStatus)
PSEP_LSA_WORK_ITEM SepDequeueWorkItem (VOID)
BOOLEAN SepQueueWorkItem (IN PSEP_LSA_WORK_ITEM LsaWorkItem, IN BOOLEAN ForceQueue)
Function Documentation
NTSTATUS SepAdtCopyToLsaSharedMemory (IN HANDLE LsaProcessHandle, IN PVOID Buffer, IN ULONG BufferLength, OUT PVOID * LsaBufferAddress)
Definition at line 472 of file adtlog.c.
References ASSERT, FALSE, MEM_COMMIT, MEM_RELEASE, NT_SUCCESS, NULL, PAGE_READWRITE, PAGED_CODE, Status, TRUE, ZwAllocateVirtualMemory(), ZwFreeVirtualMemory(), and ZwWriteVirtualMemory().
Referenced by SepRmCallLsa().
VOID SepAdtLogAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters)
Definition at line 42 of file adtlog.c.
References _SEP_LSA_WORK_ITEM::BaseAddress, _SEP_LSA_WORK_ITEM::CleanupFunction, _SEP_LSA_WORK_ITEM::CommandNumber, _SEP_LSA_WORK_ITEM::CommandParams, _SEP_LSA_WORK_ITEM::CommandParamsLength, _SEP_LSA_WORK_ITEM::CommandParamsMemoryType, ExAllocatePoolWithTag, ExFreePool(), FALSE, LsapWriteAuditMessageCommand, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _SEP_LSA_WORK_ITEM::ReplyBuffer, _SEP_LSA_WORK_ITEM::ReplyBufferLength, SE_AUDITID_AUDITS_DISCARDED, SepAdtMarshallAuditRecord(), SepAuditFailed(), SepAuditRecord, SepCrashOnAuditFail, SepQueueWorkItem(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_UNSUCCESSFUL, _SEP_LSA_WORK_ITEM::Tag, and TRUE.
Referenced by SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtGenerateDiscardAudit(), SepAdtObjectReferenceAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and SeReportSecurityEvent().
NTSTATUS SepAdtMarshallAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters, OUT PSE_ADT_PARAMETER_ARRAY * MarshalledAuditParameters, OUT PSEP_RM_LSA_MEMORY_TYPE RecordMemoryType)
Definition at line 261 of file adtlog.c.
References _SE_ADT_PARAMETER_ARRAY_ENTRY::Address, ASSERT, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, FALSE, IsValidParameterCount, _UNICODE_STRING::Length, NULL, PAGED_CODE, PagedPool, PtrAlignSize, RtlCopyMemory, SE_ADT_PARAMETERS_SELF_RELATIVE, SeAdtParmTypeAccessMask, SeAdtParmTypeDateTime, SeAdtParmTypeDuration, SeAdtParmTypeFileSpec, SeAdtParmTypeGuid, SeAdtParmTypeHexInt64, SeAdtParmTypeHexUlong, SeAdtParmTypeLogonId, SeAdtParmTypeLuid, SeAdtParmTypeMessage, SeAdtParmTypeNoLogonId, SeAdtParmTypeNone, SeAdtParmTypeObjectTypes, SeAdtParmTypePrivs, SeAdtParmTypePtr, SeAdtParmTypeSid, SeAdtParmTypeSockAddr, SeAdtParmTypeString, SeAdtParmTypeTime, SeAdtParmTypeUlong, SepRmNoMemory, SepRmPagedPoolMemory, _RTL_TRACE_BLOCK::Size, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by SepAdtLogAuditRecord().
VOID SepAuditFailed (IN NTSTATUS AuditStatus)
Definition at line 150 of file adtlog.c.
References ASSERT, CRASH_ON_AUDIT_FAIL_VALUE, FALSE, InitializeObjectAttributes, KeBugCheckEx(), KEY_SET_VALUE, KeyName, LSAP_ALLOW_ADIMIN_LOGONS_ONLY, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_DWORD, RtlInitUnicodeString(), SepCrashOnAuditFail, Status, STATUS_AUDIT_FAILED, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, ZwFlushKey(), ZwOpenKey(), and ZwSetValueKey().
Referenced by SeAddSaclToProcess(), SeDetailedAuditingWithToken(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepAuditAssignPrimaryToken(), and SepInitProcessAuditSd().
PSEP_LSA_WORK_ITEM SepDequeueWorkItem (VOID)
Definition at line 699 of file adtlog.c.
References ExFreePool(), FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeSetEvent(), _SEP_LSA_WORK_ITEM::List, NULL, PAGED_CODE, RemoveHeadList(), SepAdtCurrentListLength, SepAdtLsaDeadEvent, SepLockLsaQueue, SepLsaQueue, and SepUnlockLsaQueue.
Referenced by SepRmCallLsa().
BOOLEAN SepQueueWorkItem (IN PSEP_LSA_WORK_ITEM LsaWorkItem, IN BOOLEAN ForceQueue)
Definition at line 570 of file adtlog.c.
References DelayedWorkQueue, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, InsertTailList(), NULL, PAGED_CODE, SepAdtCountEventsDiscarded, SepAdtCurrentListLength, SepAdtDiscardingAudits, SepAdtGenerateDiscardAudit(), SepAdtLsaDeadEvent, SepAdtMaxListLength, SepAdtMinListLength, SepExWorkItem, SepLockLsaQueue, SepLsaQueue, SepRmCallLsa(), SepUnlockLsaQueue, TRUE, and _SEP_WORK_ITEM::WorkItem.
Referenced by SepAdtLogAuditRecord(), and SepInformLsaOfDeletedLogon().