Windows Research Kernel v1.2: C:/Windows Research Kernel/se/tokenp.h File Reference
tokenp.h File Reference
#include "ntos.h"
#include "sep.h"
#include "seopaque.h"
Data Structures
struct _IOBJECT_TYPE_LIST
struct _SEP_AUDIT_POLICY
struct _SEP_AUDIT_POLICY_CATEGORIES
struct _SEP_AUDIT_POLICY_OVERLAY
struct _TOKEN
Macros
#define IF_TOKEN_GLOBAL(FlagName) if (FALSE)
#define OBJECT_FAILURE_AUDIT 0x2
#define OBJECT_SUCCESS_AUDIT 0x1
#define SepAcquireTokenReadLock(T)
#define SepAcquireTokenWriteLock(T)
#define SepArrayGroupAttributes(G, I) ((G)[I].Attributes)
#define SepArrayPrivilegeAttributes(P, I) ((P)[I].Attributes)
#define SepReleaseTokenReadLock(T)
#define SepReleaseTokenWriteLock(T, M)
#define SepTokenGroupAttributes(T, I) ((T)->UserAndGroups[I].Attributes)
#define SepTokenPrivilegeAttributes(T, I) ((T)->Privileges[I].Attributes)
#define TOKEN_DEFAULT_DYNAMIC_CHARGE 500
#define TOKEN_DIAG_TOKEN_LOCKS ((ULONG) 0x00000001L)
#define TokenDiagPrint(FlagName, _Text_) ;
Typedefs
typedef struct _IOBJECT_TYPE_LIST IOBJECT_TYPE_LIST
typedef struct _IOBJECT_TYPE_LIST * PIOBJECT_TYPE_LIST
typedef struct _SEP_AUDIT_POLICY * PSEP_AUDIT_POLICY
typedef struct _SEP_AUDIT_POLICY_CATEGORIES * PSEP_AUDIT_POLICY_CATEGORIES
typedef struct _SEP_AUDIT_POLICY_OVERLAY * PSEP_AUDIT_POLICY_OVERLAY
typedef struct _TOKEN * PTOKEN
typedef struct _SEP_AUDIT_POLICY SEP_AUDIT_POLICY
typedef struct _SEP_AUDIT_POLICY_CATEGORIES SEP_AUDIT_POLICY_CATEGORIES
typedef struct _SEP_AUDIT_POLICY_OVERLAY SEP_AUDIT_POLICY_OVERLAY
typedef struct _TOKEN TOKEN
Functions
NTSTATUS SeCaptureObjectTypeList (IN POBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN KPROCESSOR_MODE RequestorMode, OUT PIOBJECT_TYPE_LIST *CapturedObjectTypeList)
VOID SeFreeCapturedObjectTypeList (IN PVOID ObjectTypeList)
BOOLEAN SepAccessCheck (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN PTOKEN PrimaryToken, IN PTOKEN ClientToken OPTIONAL, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, IN ACCESS_MASK PreviouslyGrantedAccess, IN KPROCESSOR_MODE PreviousMode, OUT PACCESS_MASK GrantedAccess, OUT PPRIVILEGE_SET *Privileges OPTIONAL, OUT PNTSTATUS AccessStatus, IN BOOLEAN ReturnResultList, OUT PBOOLEAN ReturnSomeAccessGranted, OUT PBOOLEAN ReturnSomeAccessDenied)
NTSTATUS SepAdjustGroups (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN ResetToDefault, IN ULONG GroupCount OPTIONAL, IN PSID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_GROUPS PreviousState OPTIONAL, OUT PSID SidBuffer OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
NTSTATUS SepAdjustPrivileges (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN DisableAllPrivileges, IN ULONG PrivilegeCount OPTIONAL, IN PLUID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_PRIVILEGES PreviousState OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
VOID SepAppendDefaultDacl (IN PTOKEN Token, IN PACL PAcl)
VOID SepAppendPrimaryGroup (IN PTOKEN Token, IN PSID PSid)
VOID FORCEINLINE SepDeReferenceLogonSessionDirect (IN PSEP_LOGON_SESSION_REFERENCES LogonSession)
NTSTATUS FORCEINLINE SepDuplicateLogonSessionReference (IN PTOKEN NewToken, IN PTOKEN ExistingToken)
NTSTATUS SepDuplicateToken (IN PTOKEN ExistingToken, IN POBJECT_ATTRIBUTES ObjectAttributes, IN BOOLEAN EffectiveOnly, IN TOKEN_TYPE TokenType, IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel OPTIONAL, IN KPROCESSOR_MODE RequestorMode, OUT PTOKEN *DuplicateToken)
NTSTATUS SepExpandDynamic (IN PTOKEN Token, IN ULONG NewLength)
NTSTATUS SepFilterToken (IN PTOKEN ExistingToken, IN KPROCESSOR_MODE RequestorMode, IN ULONG Flags, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES GroupsToDisable OPTIONAL, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES PrivilegesToDelete OPTIONAL, IN ULONG SidCount, IN PSID_AND_ATTRIBUTES RestrictedSids OPTIONAL, IN ULONG SidLength, OUT PTOKEN *FilteredToken)
VOID SepFreeDefaultDacl (IN PTOKEN Token)
VOID SepFreePrimaryGroup (IN PTOKEN Token)
BOOLEAN SepIdAssignableAsOwner (IN PTOKEN Token, IN ULONG Index)
VOID SepMakeTokenEffectiveOnly (IN PTOKEN Token)
VOID SepModifyTokenPolicyCounter (PSEP_AUDIT_POLICY TokenPolicy, BOOLEAN bIncrement)
BOOLEAN SepObjectInTypeList (IN GUID *ObjectType, IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, OUT PULONG ReturnedIndex)
BOOLEAN SepPrivilegeCheck (IN PTOKEN Token, IN OUT PLUID_AND_ATTRIBUTES RequiredPrivileges, IN ULONG RequiredPrivilegeCount, IN ULONG PrivilegeSetControl, IN KPROCESSOR_MODE PreviousMode)
VOID SepRemoveDisabledGroupsAndPrivileges (IN PTOKEN Token, IN ULONG Flags, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES GroupsToDisable, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES PrivilegesToDelete)
BOOLEAN SepSidInSidAndAttributes (IN PSID_AND_ATTRIBUTES SidAndAttributes, IN ULONG SidCount, IN PSID PrincipalSelfSid, IN PSID Sid)
VOID SepTokenDeleteMethod (IN PVOID Token)
BOOLEAN SepTokenInitialization (VOID)
Variables
const GENERIC_MAPPING SepTokenMapping
POBJECT_TYPE SeTokenObjectType
Macro Definition Documentation
#define IF_TOKEN_GLOBAL (FlagName) if (FALSE)
Definition at line 78 of file tokenp.h.
#define OBJECT_FAILURE_AUDIT 0x2
Definition at line 435 of file tokenp.h.
Referenced by SepAdtOpenObjectAuditAlarm(), SepAuditTypeList(), and SepSetAuditInfoForObjectType().
#define OBJECT_SUCCESS_AUDIT 0x1
Definition at line 434 of file tokenp.h.
Referenced by SepAdtOpenObjectAuditAlarm(), SepAuditTypeList(), and SepSetAuditInfoForObjectType().
#define SepAcquireTokenReadLock (T)
Value:
KeEnterCriticalRegion();          \
                                    ExAcquireResourceSharedLite((T)->TokenLock, TRUE)
Definition at line 471 of file tokenp.h.
Referenced by NtCompareTokens(), NtQueryInformationToken(), NtSetInformationToken(), SeAccessCheckByType(), SeGetTokenControlInformation(), SeLockSubjectContext(), SepDuplicateToken(), SepFilterToken(), SepIdAssignableAsGroup(), SepPrivilegeCheck(), SepTokenIsOwner(), SepValidOwnerSubjectContext(), SeQueryInformationToken(), SeQuerySessionIdToken(), and SeTokenCanImpersonate().
#define SepAcquireTokenWriteLock (T)
Value:
KeEnterCriticalRegion();          \
                                    ExAcquireResourceExclusiveLite((T)->TokenLock, TRUE)
Definition at line 474 of file tokenp.h.
Referenced by NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtSetInformationToken(), SeExchangePrimaryToken(), and SeSetSessionIdToken().
#define SepArrayGroupAttributes (G, I) ((G)[I].Attributes)
Definition at line 537 of file tokenp.h.
Referenced by SepAdjustGroups(), and SepCreateToken().
#define SepArrayPrivilegeAttributes (P, I) ((P)[I].Attributes)
Definition at line 518 of file tokenp.h.
Referenced by SepAdjustPrivileges().
#define SepReleaseTokenReadLock (T)
Value:
ExReleaseResourceLite((T)->TokenLock);  \
                                    KeLeaveCriticalRegion()
Definition at line 477 of file tokenp.h.
Referenced by NtCompareTokens(), NtQueryInformationToken(), NtSetInformationToken(), SeAccessCheckByType(), SeGetTokenControlInformation(), SepDuplicateToken(), SepFilterToken(), SepIdAssignableAsGroup(), SepPrivilegeCheck(), SepTokenIsOwner(), SepValidOwnerSubjectContext(), SeQueryInformationToken(), SeQuerySessionIdToken(), SeTokenCanImpersonate(), and SeUnlockSubjectContext().
#define SepReleaseTokenWriteLock (T, M)
Value:
{                                                                    \
      if ((M)) {                                                         \
          ExAllocateLocallyUniqueId( &((PTOKEN)(T))->ModifiedId  );      \
      }                                                                  \
      SepReleaseTokenReadLock( T );                                      \
    }
Definition at line 502 of file tokenp.h.
Referenced by NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtSetInformationToken(), SeExchangePrimaryToken(), and SeSetSessionIdToken().
#define SepTokenGroupAttributes (T, I) ((T)->UserAndGroups[I].Attributes)
Definition at line 547 of file tokenp.h.
Referenced by SepAdjustGroups(), SepIdAssignableAsOwner(), and SepMakeTokenEffectiveOnly().
#define SepTokenPrivilegeAttributes (T, I) ((T)->Privileges[I].Attributes)
Definition at line 528 of file tokenp.h.
Referenced by SepAdjustPrivileges(), and SepMakeTokenEffectiveOnly().
#define TOKEN_DEFAULT_DYNAMIC_CHARGE 500
Definition at line 115 of file tokenp.h.
Referenced by SepCreateToken().
#define TOKEN_DIAG_TOKEN_LOCKS ((ULONG) 0x00000001L)
Definition at line 99 of file tokenp.h.
#define TokenDiagPrint (FlagName, _Text_) ;
Definition at line 84 of file tokenp.h.
Typedef Documentation
typedef struct _IOBJECT_TYPE_LIST IOBJECT_TYPE_LIST
typedef struct _IOBJECT_TYPE_LIST * PIOBJECT_TYPE_LIST
typedef struct _SEP_AUDIT_POLICY * PSEP_AUDIT_POLICY
typedef struct _SEP_AUDIT_POLICY_CATEGORIES * PSEP_AUDIT_POLICY_CATEGORIES
typedef struct _SEP_AUDIT_POLICY_OVERLAY * PSEP_AUDIT_POLICY_OVERLAY
typedef struct _TOKEN * PTOKEN
typedef struct _SEP_AUDIT_POLICY SEP_AUDIT_POLICY
typedef struct _SEP_AUDIT_POLICY_CATEGORIES SEP_AUDIT_POLICY_CATEGORIES
typedef struct _SEP_AUDIT_POLICY_OVERLAY SEP_AUDIT_POLICY_OVERLAY
typedef struct _TOKEN TOKEN
Function Documentation
NTSTATUS SeCaptureObjectTypeList (IN POBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN KPROCESSOR_MODE RequestorMode, OUT PIOBJECT_TYPE_LIST * CapturedObjectTypeList)
VOID SeFreeCapturedObjectTypeList (IN PVOID ObjectTypeList)
BOOLEAN SepAccessCheck (IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN PTOKEN PrimaryToken, IN PTOKEN ClientToken OPTIONAL, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, IN ACCESS_MASK PreviouslyGrantedAccess, IN KPROCESSOR_MODE PreviousMode, OUT PACCESS_MASK GrantedAccess, OUT PPRIVILEGE_SET *Privileges OPTIONAL, OUT PNTSTATUS AccessStatus, IN BOOLEAN ReturnResultList, OUT PBOOLEAN ReturnSomeAccessGranted, OUT PBOOLEAN ReturnSomeAccessDenied)
Definition at line 1702 of file accessck.c.
References ACCESS_SYSTEM_SECURITY, _ACL::AceCount, ARGUMENT_PRESENT, ASSERT, _IOBJECT_TYPE_LIST::CurrentGranted, FALSE, Index, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, PAGED_CODE, _IOBJECT_TYPE_LIST::ParentIndex, _IOBJECT_TYPE_LIST::Remaining, RtlpAreControlBitsSet, RtlpDaclAddrSecurityDescriptor, RtlZeroMemory, SE_DACL_PRESENT, SeAssertMappedCanonicalAccess, SepAssemblePrivileges(), SepMaximumAccessCheck(), SepNormalAccessCheck(), SepSinglePrivilegeCheck(), SeSecurityPrivilege, SeTakeOwnershipPrivilege, SeTokenIsRestricted(), Status, STATUS_ACCESS_DENIED, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TRUE, and WRITE_OWNER.
Referenced by SeAccessCheck(), SeAccessCheckByType(), SepAccessCheckAndAuditAlarm(), and SepCheckTokenForCoreSystemSids().
NTSTATUS SepAdjustGroups (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN ResetToDefault, IN ULONG GroupCount OPTIONAL, IN PSID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_GROUPS PreviousState OPTIONAL, OUT PSID SidBuffer OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
Definition at line 1170 of file tokenadj.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, _SID_AND_ATTRIBUTES::Attributes, FALSE, LongAlignSize, PAGED_CODE, RtlCopySid(), RtlEqualSid(), SE_GROUP_ENABLED, SE_GROUP_ENABLED_BY_DEFAULT, SE_GROUP_MANDATORY, SE_GROUP_USE_FOR_DENY_ONLY, SeLengthSid, SepArrayGroupAttributes, SepTokenGroupAttributes, _SID_AND_ATTRIBUTES::Sid, STATUS_CANT_DISABLE_MANDATORY, STATUS_CANT_ENABLE_DENY_ONLY, STATUS_NOT_ALL_ASSIGNED, STATUS_SUCCESS, and TRUE.
Referenced by NtAdjustGroupsToken().
NTSTATUS SepAdjustPrivileges (IN PTOKEN Token, IN BOOLEAN MakeChanges, IN BOOLEAN DisableAllPrivileges, IN ULONG PrivilegeCount OPTIONAL, IN PLUID_AND_ATTRIBUTES NewState OPTIONAL, OUT PTOKEN_PRIVILEGES PreviousState OPTIONAL, OUT PULONG ReturnLength, OUT PULONG ChangeCount, OUT PBOOLEAN ChangesMade)
Definition at line 820 of file tokenadj.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, FALSE, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, RtlEqualLuid, SE_PRIVILEGE_ENABLED, SE_PRIVILEGE_REMOVED, SeBackupPrivilege, SeChangeNotifyPrivilege, SeImpersonatePrivilege, SepArrayPrivilegeAttributes, SepTokenPrivilegeAttributes, SeRestorePrivilege, STATUS_NOT_ALL_ASSIGNED, STATUS_SUCCESS, TOKEN_HAS_BACKUP_PRIVILEGE, TOKEN_HAS_IMPERSONATE_PRIVILEGE, TOKEN_HAS_RESTORE_PRIVILEGE, TOKEN_HAS_TRAVERSE_PRIVILEGE, and TRUE.
Referenced by NtAdjustPrivilegesToken().
VOID SepAppendDefaultDacl (IN PTOKEN Token, IN PACL PAcl)
VOID SepAppendPrimaryGroup (IN PTOKEN Token, IN PSID PSid)
VOID FORCEINLINE SepDeReferenceLogonSessionDirect (IN PSEP_LOGON_SESSION_REFERENCES LogonSession)
Definition at line 761 of file tokenp.h.
References ASSERT, InterlockedCompareExchange(), and SepDeReferenceLogonSession().
Referenced by NtSetInformationToken(), SeGetLogonIdDeviceMap(), and SepTokenDeleteMethod().
NTSTATUS FORCEINLINE SepDuplicateLogonSessionReference (IN PTOKEN NewToken, IN PTOKEN ExistingToken)
Definition at line 728 of file tokenp.h.
References ASSERT, InterlockedIncrement, NT_SUCCESS, NULL, _SEP_LOGON_SESSION_REFERENCES::ReferenceCount, SepReferenceLogonSession(), Status, STATUS_SUCCESS, and TOKEN_SESSION_NOT_REFERENCED.
Referenced by SepDuplicateToken(), and SepFilterToken().
NTSTATUS SepDuplicateToken (IN PTOKEN ExistingToken, IN POBJECT_ATTRIBUTES ObjectAttributes, IN BOOLEAN EffectiveOnly, IN TOKEN_TYPE TokenType, IN SECURITY_IMPERSONATION_LEVEL ImpersonationLevel OPTIONAL, IN KPROCESSOR_MODE RequestorMode, OUT PTOKEN * DuplicateToken)
NTSTATUS SepExpandDynamic (IN PTOKEN Token, IN ULONG NewLength)
NTSTATUS SepFilterToken (IN PTOKEN ExistingToken, IN KPROCESSOR_MODE RequestorMode, IN ULONG Flags, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES GroupsToDisable OPTIONAL, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES PrivilegesToDelete OPTIONAL, IN ULONG SidCount, IN PSID_AND_ATTRIBUTES RestrictedSids OPTIONAL, IN ULONG SidLength, OUT PTOKEN * FilteredToken)
VOID SepFreeDefaultDacl (IN PTOKEN Token)
VOID SepFreePrimaryGroup (IN PTOKEN Token)
BOOLEAN SepIdAssignableAsOwner (IN PTOKEN Token, IN ULONG Index)
Definition at line 3173 of file token.c.
References PAGED_CODE, SE_GROUP_OWNER, SepTokenGroupAttributes, and TRUE.
Referenced by NtSetInformationToken(), and SepValidOwnerSubjectContext().
VOID SepMakeTokenEffectiveOnly (IN PTOKEN Token)
VOID SepModifyTokenPolicyCounter (PSEP_AUDIT_POLICY TokenPolicy, BOOLEAN bIncrement)
Referenced by SepDuplicateToken(), SepFilterToken(), and SepTokenDeleteMethod().
BOOLEAN SepObjectInTypeList (IN GUID * ObjectType, IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, OUT PULONG ReturnedIndex)
Definition at line 392 of file accessck.c.
References ASSERT, FALSE, Index, PAGED_CODE, RtlpIsEqualGuid, and TRUE.
Referenced by SepExamineSaclEx(), SepMaximumAccessCheck(), and SepNormalAccessCheck().
BOOLEAN SepPrivilegeCheck (IN PTOKEN Token, IN OUT PLUID_AND_ATTRIBUTES RequiredPrivileges, IN ULONG RequiredPrivilegeCount, IN ULONG PrivilegeSetControl, IN KPROCESSOR_MODE PreviousMode)
Definition at line 34 of file privileg.c.
References _LUID_AND_ATTRIBUTES::Attributes, FALSE, KernelMode, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, PRIVILEGE_SET_ALL_NECESSARY, RtlEqualLuid, SE_PRIVILEGE_ENABLED, SE_PRIVILEGE_USED_FOR_ACCESS, SepAcquireTokenReadLock, SepReleaseTokenReadLock, and TRUE.
Referenced by NtPrivilegeCheck(), SeCheckAuditPrivilege(), SePrivilegeCheck(), and SepSinglePrivilegeCheck().
VOID SepRemoveDisabledGroupsAndPrivileges (IN PTOKEN Token, IN ULONG Flags, IN ULONG GroupCount, IN PSID_AND_ATTRIBUTES GroupsToDisable, IN ULONG PrivilegeCount, IN PLUID_AND_ATTRIBUTES PrivilegesToDelete)
BOOLEAN SepSidInSidAndAttributes (IN PSID_AND_ATTRIBUTES SidAndAttributes, IN ULONG SidCount, IN PSID PrincipalSelfSid, IN PSID Sid)
VOID SepTokenDeleteMethod (IN PVOID Token)
Definition at line 2423 of file token.c.
References ARGUMENT_PRESENT, ASSERT, ExDeleteResourceLite(), ExFreePool(), FALSE, PAGED_CODE, SepDeReferenceLogonSessionDirect(), SepFreeProxyData(), SepModifyTokenPolicyCounter(), SepTokenPolicyCounter, and TOKEN_SESSION_NOT_REFERENCED.
Referenced by SepTokenInitialization().
BOOLEAN SepTokenInitialization (VOID)
Definition at line 1864 of file token.c.
References _OBJECT_TYPE_INITIALIZER::DeleteProcedure, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, _OBJECT_TYPE_INITIALIZER::SecurityRequired, SepTokenDeleteMethod(), SepTokenMapping, Status, TOKEN_ALL_ACCESS, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by SepInitializationPhase0().
Variable Documentation
const GENERIC_MAPPING SepTokenMapping
Definition at line 87 of file token.c.
Referenced by SepTokenInitialization().
POBJECT_TYPE SeTokenObjectType
Definition at line 97 of file token.c.