Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/thredobj.c File Reference
thredobj.c File Reference
#include "ki.h"
Functions
ULONG KeAlertResumeThread (__inout PKTHREAD Thread)
BOOLEAN KeAlertThread (__inout PKTHREAD Thread, __in KPROCESSOR_MODE AlertMode)
VOID KeBoostPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Increment)
ULONG KeForceResumeThread (__inout PKTHREAD Thread)
VOID KeFreezeAllThreads (VOID)
NTSTATUS KeInitializeThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
NTSTATUS KeInitThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
LOGICAL KeQueryAutoAlignmentThread (__in PKTHREAD Thread)
LONG KeQueryBasePriorityThread (__in PKTHREAD Thread)
KPRIORITY KeQueryPriorityThread (__in PKTHREAD Thread)
ULONG KeQueryRuntimeThread (__in PKTHREAD Thread, __out PULONG UserTime)
BOOLEAN KeReadStateThread (__in PKTHREAD Thread)
VOID KeReadyThread (__inout PKTHREAD Thread)
ULONG KeResumeThread (__inout PKTHREAD Thread)
VOID KeRevertToUserAffinityThread (VOID)
VOID KeRundownThread (VOID)
KAFFINITY KeSetAffinityThread (__inout PKTHREAD Thread, __in KAFFINITY Affinity)
LOGICAL KeSetAutoAlignmentThread (__inout PKTHREAD Thread, __in LOGICAL Enable)
LONG KeSetBasePriorityThread (__inout PKTHREAD Thread, __in LONG Increment)
LOGICAL KeSetDisableBoostThread (__inout PKTHREAD Thread, __in LOGICAL Disable)
UCHAR KeSetIdealProcessorThread (__inout PKTHREAD Thread, __in UCHAR Processor)
BOOLEAN KeSetKernelStackSwapEnable (__in BOOLEAN Enable)
KPRIORITY KeSetPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Priority)
VOID KeSetPriorityZeroPageThread (__in KPRIORITY Priority)
VOID KeSetSystemAffinityThread (__in KAFFINITY Affinity)
VOID KeStartThread (__inout PKTHREAD Thread)
ULONG KeSuspendThread (__inout PKTHREAD Thread)
VOID KeTerminateThread (__in KPRIORITY Increment)
BOOLEAN KeTestAlertThread (__in KPROCESSOR_MODE AlertMode)
VOID KeThawAllThreads (VOID)
VOID KeUninitThread (__inout PKTHREAD Thread)
Function Documentation
ULONG KeAlertResumeThread (__inout PKTHREAD Thread)
Definition at line 656 of file thredobj.c.
References ALERT_INCREMENT, ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KernelMode, KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiUnwaitThread(), KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, RESUME_INCREMENT, STATUS_ALERTED, TRUE, and Waiting.
Referenced by NtAlertResumeThread().
BOOLEAN KeAlertThread (__inout PKTHREAD Thread, __in KPROCESSOR_MODE AlertMode)
Definition at line 571 of file thredobj.c.
References ALERT_INCREMENT, ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, FALSE, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiUnwaitThread(), _KLOCK_QUEUE_HANDLE::OldIrql, STATUS_ALERTED, TRUE, and Waiting.
Referenced by NtAlertThread().
VOID KeBoostPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Increment)
Definition at line 752 of file thredobj.c.
References ASSERT, DISPATCH_LEVEL, KeGetCurrentIrql(), KiBoostPriorityThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), and LOW_REALTIME_PRIORITY.
Referenced by NtReadFile(), and NtSetInformationProcess().
ULONG KeForceResumeThread (__inout PKTHREAD Thread)
Definition at line 808 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, and RESUME_INCREMENT.
Referenced by PspCreateThread(), PspExitThread(), PspTerminateThreadByPointer(), and PsSuspendThread().
VOID KeFreezeAllThreads (VOID)
Definition at line 876 of file thredobj.c.
References _KTHREAD::ApcQueueable, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, _KTHREAD::FreezeCount, _KSEMAPHORE::Header, _KAPC::Inserted, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeEnterCriticalRegion(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiInsertQueueApc(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, MAXIMUM_SUSPEND_COUNT, _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, _KPROCESS::ProcessLock, RESUME_INCREMENT, _DISPATCHER_HEADER::SignalState, _KTHREAD::SuspendApc, _KTHREAD::SuspendCount, _KTHREAD::SuspendSemaphore, _KPROCESS::ThreadListHead, and TRUE.
Referenced by DbgkpSuspendProcess().
NTSTATUS KeInitializeThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
Definition at line 483 of file thredobj.c.
References KeInitThread(), KeStartThread(), NT_SUCCESS, Status, and STATUS_SUCCESS.
Referenced by KiInitializeKernel().
NTSTATUS KeInitThread (__out PKTHREAD Thread, __in_opt PVOID KernelStack, __in PKSYSTEM_ROUTINE SystemRoutine, __in_opt PKSTART_ROUTINE StartRoutine, __in_opt PVOID StartContext, __in_opt PCONTEXT ContextFrame, __in_opt PVOID Teb, __in PKPROCESS Process)
Definition at line 32 of file thredobj.c.
References AdjustNone, _KSERVICE_TABLE_DESCRIPTOR::Base, _LIST_ENTRY::Blink, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LIST_ENTRY::Flink, _KTIMER::Header, Index, Initialized, InitializeListHead(), KeInitializeApc(), KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitializeTimer(), KERNEL_STACK_SIZE, KernelMode, KeServiceDescriptorTable, KiInitializeContextThread(), KiSuspendNop(), KiSuspendRundown(), KiSuspendThread(), _KSERVICE_TABLE_DESCRIPTOR::Limit, MmCreateKernelStack(), MmDeleteKernelStack(), NULL, _KWAIT_BLOCK::Object, OriginalApcEnvironment, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_TIMEOUT, SYSTEM_SERVICE_INDEX, THREAD_WAIT_OBJECTS, ThreadObject, TIMER_WAIT_BLOCK, TRUE, UserMode, WaitAny, _KWAIT_BLOCK::WaitKey, _KWAIT_BLOCK::WaitListEntry, _DISPATCHER_HEADER::WaitListHead, and _KWAIT_BLOCK::WaitType.
Referenced by KeInitializeThread(), and PspCreateThread().
LOGICAL KeQueryAutoAlignmentThread (__in PKTHREAD Thread)
Definition at line 1014 of file thredobj.c.
References ASSERT_THREAD.
LONG KeQueryBasePriorityThread (__in PKTHREAD Thread)
Definition at line 1045 of file thredobj.c.
References ASSERT, ASSERT_THREAD, _KPROCESS::BasePriority, DISPATCH_LEVEL, HIGH_PRIORITY, KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiAcquireThreadLock(), and KiReleaseThreadLock().
Referenced by NtQueryInformationThread().
KPRIORITY KeQueryPriorityThread (__in PKTHREAD Thread)
Definition at line 1106 of file thredobj.c.
References ASSERT_THREAD.
ULONG KeQueryRuntimeThread (__in PKTHREAD Thread, __out PULONG UserTime)
Definition at line 1134 of file thredobj.c.
References ASSERT_THREAD.
BOOLEAN KeReadStateThread (__in PKTHREAD Thread)
Definition at line 1168 of file thredobj.c.
References ASSERT_THREAD.
Referenced by NtQueryInformationThread(), PspExitThread(), and PspWaitForUsermodeExit().
VOID KeReadyThread (__inout PKTHREAD Thread)
Definition at line 1200 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiReadyThread(), and KiUnlockDispatcherDatabase().
Referenced by PspCreateThread().
ULONG KeResumeThread (__inout PKTHREAD Thread)
Definition at line 1245 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, and RESUME_INCREMENT.
Referenced by PspCreateThread(), PsResumeProcess(), and PsResumeThread().
VOID KeRevertToUserAffinityThread (VOID)
Definition at line 1318 of file thredobj.c.
References _KTHREAD::Affinity, ASSERT, DISPATCH_LEVEL, FALSE, _KTHREAD::IdealProcessor, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KiAcquirePrcbLock(), KiLockDispatcherDatabase, KiReleasePrcbLock(), KiSelectNextThread(), KiUnlockDispatcherDatabase(), _KPRCB::NextThread, NULL, _KPRCB::SetMember, Standby, _KTHREAD::State, _KTHREAD::SystemAffinityActive, _KTHREAD::UserAffinity, and _KTHREAD::UserIdealProcessor.
Referenced by CmpConfigureProcessors(), ExAllocateCacheAwarePushLock(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), Ke386CallBios(), KeConnectInterrupt(), KeDeregisterNmiCallback(), KeDisconnectInterrupt(), KeFlushQueuedDpcs(), KeGenericCallDpc(), KeSetSystemTime(), KeSetup80387OrEmulate(), KiInitMachineDependent(), MiZeroPageWorker(), and WmiStopContextSwapTrace().
VOID KeRundownThread (VOID)
Definition at line 1400 of file thredobj.c.
References _KMUTANT::Abandoned, _KMUTANT::ApcDisable, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, _KMUTANT::Header, IsListEmpty, KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), MUTANT_INCREMENT, _KMUTANT::MutantListEntry, _KTHREAD::MutantListHead, NULL, _KMUTANT::OwnerThread, RemoveEntryList(), _DISPATCHER_HEADER::SignalState, THREAD_TERMINATE_HELD_MUTEX, TRUE, and _DISPATCHER_HEADER::WaitListHead.
Referenced by PspExitThread().
KAFFINITY KeSetAffinityThread (__inout PKTHREAD Thread, __in KAFFINITY Affinity)
Definition at line 1482 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, KeGetCurrentIrql(), KiLockDispatcherDatabase, KiSetAffinityThread(), and KiUnlockDispatcherDatabase().
Referenced by NtSetInformationThread().
LOGICAL KeSetAutoAlignmentThread (__inout PKTHREAD Thread, __in LOGICAL Enable)
Definition at line 1785 of file thredobj.c.
References ASSERT_THREAD, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KTHREAD_AUTO_ALIGNMENT_BIT.
Referenced by NtSetInformationThread().
LONG KeSetBasePriorityThread (__inout PKTHREAD Thread, __in LONG Increment)
Definition at line 1642 of file thredobj.c.
References abs(), ASSERT, ASSERT_THREAD, _KPROCESS::BasePriority, DISPATCH_LEVEL, FALSE, HIGH_PRIORITY, KeGetCurrentIrql(), KiAcquireThreadLock(), KiComputeNewPriority(), KiLockDispatcherDatabase, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabase(), LOW_PRIORITY, and LOW_REALTIME_PRIORITY.
Referenced by ExpCreateWorkerThread(), ExpWorkerThreadBalanceManager(), NtSetInformationThread(), and WmipLogger().
LOGICAL KeSetDisableBoostThread (__inout PKTHREAD Thread, __in LOGICAL Disable)
Definition at line 1831 of file thredobj.c.
References ASSERT_THREAD, FALSE, InterlockedBitTestAndReset(), InterlockedBitTestAndSet(), and KTHREAD_DISABLE_BOOST_BIT.
Referenced by NtSetInformationProcess(), and NtSetInformationThread().
UCHAR KeSetIdealProcessorThread (__inout PKTHREAD Thread, __in UCHAR Processor)
Definition at line 1877 of file thredobj.c.
References AFFINITY_MASK, ASSERT, FALSE, KeNumberProcessors, KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), and MAXIMUM_PROCESSORS.
Referenced by MiZeroAwePageWorker(), MmZeroPageThread(), and NtSetInformationThread().
BOOLEAN KeSetKernelStackSwapEnable (__in BOOLEAN Enable)
Definition at line 1947 of file thredobj.c.
References _KTHREAD::EnableStackSwap, and KeGetCurrentThread().
Referenced by ExpSetSwappingKernelApc(), ExpShutdownWorker(), ExpWorkerThread(), and ExSwapinWorkerThreads().
KPRIORITY KeSetPriorityThread (__inout PKTHREAD Thread, __in KPRIORITY Priority)
Definition at line 1986 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, FALSE, HIGH_PRIORITY, KeGetCurrentIrql(), KeIsExecutingDpc(), KiAcquireThreadLock(), KiLockDispatcherDatabase, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabase(), and LOW_PRIORITY.
Referenced by FsRtlWorkerThread(), KeBalanceSetManager(), KeFlushQueuedDpcs(), KeSwapProcessOrStack(), KiExecuteDpc(), KiInitializeKernel(), MiDereferenceSegmentThread(), MiMappedPageWriter(), MiModifiedPageWriter(), MiZeroAwePageWorker(), MiZeroInParallel(), MiZeroPageWorker(), NtSetInformationThread(), and Phase1InitializationDiscard().
VOID KeSetPriorityZeroPageThread (__in KPRIORITY Priority)
Definition at line 2060 of file thredobj.c.
References ASSERT, _KTHREAD::BasePriority, DISPATCH_LEVEL, FALSE, KeGetCurrentIrql(), KeGetCurrentThread(), KeIsExecutingDpc(), KiAcquireThreadLock(), KiLockDispatcherDatabase, KiReleaseThreadLock(), KiSetPriorityThread(), KiUnlockDispatcherDatabase(), _KTHREAD::Priority, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, and _KTHREAD::QuantumReset.
Referenced by MmZeroPageThread().
VOID KeSetSystemAffinityThread (__in KAFFINITY Affinity)
Definition at line 1536 of file thredobj.c.
References _KTHREAD::Affinity, AFFINITY_MASK, ASSERT, DISPATCH_LEVEL, _KTHREAD::IdealProcessor, KeActiveProcessors, KeFindFirstSetLeftAffinity, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KiAcquirePrcbLock(), KiLockDispatcherDatabase, KiProcessorBlock, KiReleasePrcbLock(), KiSelectNextThread(), KiUnlockDispatcherDatabase(), _KPRCB::NextThread, NULL, _KPRCB::ParentNode, _KNODE::ProcessorMask, _KPRCB::SetMember, Standby, _KTHREAD::State, _KTHREAD::SystemAffinityActive, and TRUE.
Referenced by CmpConfigureProcessors(), ExAllocateCacheAwarePushLock(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), Ke386CallBios(), KeConnectInterrupt(), KeDeregisterNmiCallback(), KeDisconnectInterrupt(), KeFlushQueuedDpcs(), KeGenericCallDpc(), KeSetSystemTime(), KeSetup80387OrEmulate(), KiExecuteDpc(), KiInitMachineDependent(), MiZeroPageWorker(), and WmiStopContextSwapTrace().
VOID KeStartThread (__inout PKTHREAD Thread)
Definition at line 297 of file thredobj.c.
References _KPROCESS::Affinity, AFFINITY_MASK, ASSERT, _KPROCESS::BasePriority, _KPROCESS::DisableBoost, FALSE, _KPROCESS::IdealNode, InsertTailList(), _KPROCESS::Iopl, IsListEmpty, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeFindNextRightSetAffinity(), KeNodeBlock, KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiInitialProcess, KiLockDispatcherDatabaseAtSynchLevel, KiProcessListHead, KiProcessListLock, KiProcessorBlock, KiUnlockDispatcherDatabaseFromSynchLevel, MAXULONG_PTR, _KPRCB::MultiThreadProcessorSet, _EPROCESS::Pcb, _KPROCESS::ProcessListEntry, _KPROCESS::ProcessLock, _KPROCESS::QuantumReset, _KPROCESS::StackCount, _KPROCESS::ThreadListHead, _KPROCESS::ThreadSeed, and TRUE.
Referenced by KeInitializeThread(), and PspCreateThread().
ULONG KeSuspendThread (__inout PKTHREAD Thread)
Definition at line 2129 of file thredobj.c.
References ASSERT, ASSERT_THREAD, DISPATCH_LEVEL, ExRaiseStatus(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiInsertQueueApc(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, MAXIMUM_SUSPEND_COUNT, _KLOCK_QUEUE_HANDLE::OldIrql, RESUME_INCREMENT, STATUS_SUSPEND_COUNT_EXCEEDED, and TRUE.
Referenced by PspCreateThread(), and PsSuspendThread().
VOID KeTerminateThread (__in KPRIORITY Increment)
Definition at line 2218 of file thredobj.c.
References _KTHREAD::ApcState, ASSERT, _LIST_ENTRY::Blink, DISPATCH_LEVEL, ExWorkerQueue, FALSE, _LIST_ENTRY::Flink, HyperCriticalWorkQueue, InterlockedPushEntrySingleList(), IsListEmpty, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeCheckIfStackExpandCalloutActive(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KPROCESS::KernelTime, _KTHREAD::KernelTime, KiActivateWaiterQueue(), KiInsertQueue(), KiLockDispatcherDatabaseAtSynchLevel, KiProcessListLock, KiProcessOutSwapListHead, KiRundownThread, KiSetContextSwapBusy(), KiSetInternalEvent(), KiSwapEvent, KiSwappingThread, KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTestWithoutSideEffects(), _WORK_QUEUE_ITEM::List, NULL, _KAPC_STATE::Process, ProcessInMemory, _KPROCESS::ProcessListEntry, _KPROCESS::ProcessLock, ProcessOutTransition, PsReaperListHead, PsReaperWorkItem, RemoveEntryList(), _KPROCESS::StackCount, _KPROCESS::State, _KPROCESS::SwapListEntry, Terminated, _ETHREAD::ThreadListEntry, _KTHREAD::ThreadListEntry, _KPROCESS::ThreadListHead, TRUE, _KPROCESS::UserTime, and _KTHREAD::UserTime.
Referenced by PspExitThread().
BOOLEAN KeTestAlertThread (__in KPROCESSOR_MODE AlertMode)
Definition at line 2415 of file thredobj.c.
References _KTHREAD::Alerted, _KAPC_STATE::ApcListHead, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, DISPATCH_LEVEL, FALSE, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), TRUE, _KAPC_STATE::UserApcPending, and UserMode.
Referenced by KiContinueEx(), KiDeliverApc(), and NtTestAlert().
VOID KeThawAllThreads (VOID)
Definition at line 2482 of file thredobj.c.
References _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _LIST_ENTRY::Flink, _KTHREAD::FreezeCount, _KSEMAPHORE::Header, KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveCriticalRegion(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, KiWaitTest(), _KLOCK_QUEUE_HANDLE::OldIrql, _KAPC_STATE::Process, _KPROCESS::ProcessLock, RESUME_INCREMENT, _DISPATCHER_HEADER::SignalState, _KTHREAD::SuspendCount, _KTHREAD::SuspendSemaphore, and _KPROCESS::ThreadListHead.
Referenced by DbgkpResumeProcess().
VOID KeUninitThread (__inout PKTHREAD Thread)
Definition at line 269 of file thredobj.c.
References FALSE, MmDeleteKernelStack(), and NULL.
Referenced by PspCreateThread().