Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpccreat.c File Reference
lpccreat.c File Reference
#include "lpcp.h"
Functions
NTSTATUS LpcpCreatePort (OUT PHANDLE PortHandle, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG MaxConnectionInfoLength, IN ULONG MaxMessageLength, IN ULONG MaxPoolUsage, IN BOOLEAN Waitable)
NTSTATUS NtCreatePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
NTSTATUS NtCreateWaitablePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
Function Documentation
NTSTATUS LpcpCreatePort (OUT PHANDLE PortHandle, IN POBJECT_ATTRIBUTES ObjectAttributes, IN ULONG MaxConnectionInfoLength, IN ULONG MaxMessageLength, IN ULONG MaxPoolUsage, IN BOOLEAN Waitable)
Definition at line 134 of file lpccreat.c.
References _UNICODE_STRING::Buffer, _ETHREAD::Cid, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_PORT_OBJECT::Creator, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, _LPCP_PORT_OBJECT::Flags, Handle, InitializeListHead(), KeGetPreviousMode, KeInitializeEvent(), KernelMode, _UNICODE_STRING::Length, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LpcpGetMaxMessageLength, LpcpInitializePortQueue(), LpcPortObjectType, LpcpPrint, LpcpTrace, _LPCP_PORT_OBJECT::LpcReplyChainHead, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MaxConnectionInfoLength, _LPCP_PORT_OBJECT::MaxMessageLength, NotificationEvent, NT_SUCCESS, NtClose(), NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, PAGED_CODE, PORT_ALL_ACCESS, PORT_WAITABLE, ProbeAndReadStructure, ProbeForReadSmallStructure, ProbeForWriteHandle, PsGetCurrentProcess(), PsGetCurrentThread(), RtlInitUnicodeString(), RtlZeroMemory, SERVER_CONNECTION_PORT, _LPCP_PORT_OBJECT::ServerProcess, Status, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, UNCONNECTED_COMMUNICATION_PORT, UNREFERENCED_PARAMETER, and _LPCP_PORT_OBJECT::WaitEvent.
Referenced by NtCreatePort(), and NtCreateWaitablePort().
NTSTATUS NtCreatePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
Definition at line 43 of file lpccreat.c.
References FALSE, LpcpCreatePort(), PAGED_CODE, and Status.
NTSTATUS NtCreateWaitablePort (__out PHANDLE PortHandle, __in POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG MaxConnectionInfoLength, __in ULONG MaxMessageLength, __in_opt ULONG MaxPoolUsage)
Definition at line 85 of file lpccreat.c.
References LpcpCreatePort(), PAGED_CODE, Status, and TRUE.