Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/intobj.c File Reference
intobj.c File Reference
#include "ki.h"
Data Structures
struct DISPATCH_INFO
struct KISRTIMERINIT
Typedefs
typedef enum CONNECT_TYPE * PCONNECT_TYPE
typedef struct DISPATCH_INFO * PDISPATCH_INFO
typedef struct KISRTIMERINIT * PKISRTIMERINIT
Enumerations
enum CONNECT_TYPE { NoConnect, NormalConnect, ChainConnect, UnknownConnect }
Functions
BOOLEAN KeConnectInterrupt (__inout PKINTERRUPT Interrupt)
BOOLEAN KeDisconnectInterrupt (__inout PKINTERRUPT Interrupt)
VOID KeInitializeInterrupt (__out PKINTERRUPT Interrupt, __in PKSERVICE_ROUTINE ServiceRoutine, __in_opt PVOID ServiceContext, __out_opt PKSPIN_LOCK SpinLock, __in ULONG Vector, __in KIRQL Irql, __in KIRQL SynchronizeIrql, __in KINTERRUPT_MODE InterruptMode, __in BOOLEAN ShareVector, __in CCHAR ProcessorNumber, __in BOOLEAN FloatingSave)
VOID KiChainedDispatch2ndLvl (VOID)
VOID KiConnectVectorAndInterruptObject (IN PKINTERRUPT Interrupt, IN CONNECT_TYPE Type)
ULONG KiEndUnexpectedRange (VOID)
VOID KiGetVectorInfo (IN ULONG Vector, OUT PDISPATCH_INFO DispatchInfo)
VOID KiInitializeInterruptTimers (VOID)
VOID KiInitializeInterruptTimersDpc (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID KiInterruptDispatch2ndLvl (VOID)
ULONG KiStartUnexpectedRange (VOID)
VOID FASTCALL KiTimedChainedDispatch2ndLvl (PKINTERRUPT Interrupt)
VOID FASTCALL KiTimedInterruptDispatch (PKINTERRUPT Interrupt)
Variables
PKISRTIMERINIT KiIsrTimerInit
ULONGLONG KiIsrTscLimit = 0xFFFFFFFFFFFFFFFF
ULONG KiTimeLimitDpcMicroseconds
ULONG KiTimeLimitIsrMicroseconds
ULONG KiUnexpectedEntrySize
Typedef Documentation
typedef enum CONNECT_TYPE * PCONNECT_TYPE
typedef struct DISPATCH_INFO * PDISPATCH_INFO
typedef struct KISRTIMERINIT * PKISRTIMERINIT
Enumeration Type Documentation
enum CONNECT_TYPE
Enumerator
NoConnect
NormalConnect
ChainConnect
UnknownConnect
Definition at line 52 of file intobj.c.
Function Documentation
BOOLEAN KeConnectInterrupt (__inout PKINTERRUPT Interrupt)
Definition at line 229 of file intobj.c.
References ASSERT, ChainConnect, DbgPrint(), Enabled, FALSE, HalEnableSystemInterrupt(), HIGH_LEVEL, InitializeListHead(), InsertTailList(), DISPATCH_INFO::Interrupt, _KINTERRUPT::InterruptListEntry, KeDisconnectInterrupt(), KeNumberProcessors, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiConnectVectorAndInterruptObject(), KiGetVectorInfo(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), _KINTERRUPT::Mode, NoConnect, NormalConnect, _KINTERRUPT::ShareVector, SYNCH_LEVEL, TRUE, DISPATCH_INFO::Type, and UnknownConnect.
Referenced by IoConnectInterrupt().
BOOLEAN KeDisconnectInterrupt (__inout PKINTERRUPT Interrupt)
Definition at line 404 of file intobj.c.
References ASSERT, ChainConnect, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, HalDisableSystemInterrupt(), DISPATCH_INFO::Interrupt, _KINTERRUPT::InterruptListEntry, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KeSweepIcache, KiConnectVectorAndInterruptObject(), KiGetVectorInfo(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), NoConnect, NormalConnect, RemoveEntryList(), SYNCH_LEVEL, TRUE, and DISPATCH_INFO::Type.
Referenced by IoDisconnectInterrupt().
VOID KeInitializeInterrupt (__out PKINTERRUPT Interrupt, __in PKSERVICE_ROUTINE ServiceRoutine, __in_opt PVOID ServiceContext, __out_opt PKSPIN_LOCK SpinLock, __in ULONG Vector, __in KIRQL Irql, __in KIRQL SynchronizeIrql, __in KINTERRUPT_MODE InterruptMode, __in BOOLEAN ShareVector, __in CCHAR ProcessorNumber, __in BOOLEAN FloatingSave)
Definition at line 83 of file intobj.c.
References ARGUMENT_PRESENT, FALSE, Index, InterruptObject, KeInitializeSpinLock(), KeSweepDcache, KiInterruptTemplate, KiInterruptTemplateObject, and NORMAL_DISPATCH_LENGTH.
Referenced by IoConnectInterrupt().
VOID KiChainedDispatch2ndLvl (VOID)
Referenced by KiGetVectorInfo().
VOID KiConnectVectorAndInterruptObject (IN PKINTERRUPT Interrupt, IN CONNECT_TYPE Type)
Definition at line 678 of file intobj.c.
References DISPATCH_INFO::ChainedDispatch, DISPATCH_INFO::FlatDispatch, DISPATCH_INFO::FloatingDispatch, DISPATCH_INFO::InterruptDispatch, KiGetVectorInfo(), KiInterruptTemplate, KiInterruptTemplate2ndDispatch, KiInterruptTemplateDispatch, KiSetHandlerAddressToIDT, NoConnect, DISPATCH_INFO::NoDispatch, and NormalConnect.
Referenced by KeConnectInterrupt(), and KeDisconnectInterrupt().
ULONG KiEndUnexpectedRange (VOID)
VOID KiGetVectorInfo (IN ULONG Vector, OUT PDISPATCH_INFO DispatchInfo)
Definition at line 563 of file intobj.c.
References ChainConnect, CONTAINING_RECORD, DbgPrint(), HalSystemVectorDispatchEntry(), HalVectorToIDTEntry, KeBugCheck(), KiChainedDispatch(), KiChainedDispatch2ndLvl(), KiFloatingDispatch(), KiInterruptDispatch(), KiInterruptDispatch2ndLvl(), KiInterruptTemplate, KiInterruptTemplate2ndDispatch, KiReturnHandlerAddressFromIDT, KiStartUnexpectedRange(), KiUnexpectedEntrySize, MISMATCHED_HAL, NoConnect, NormalConnect, NULL, PRIMARY_VECTOR_BASE, and UnknownConnect.
Referenced by KeConnectInterrupt(), KeDisconnectInterrupt(), and KiConnectVectorAndInterruptObject().
VOID KiInitializeInterruptTimers (VOID)
Definition at line 1149 of file intobj.c.
References KISRTIMERINIT::Dpc, ExAllocatePoolWithTag, KeFeatureBits, KeInitializeDpc(), KeInitializeTimerEx(), KeSetTimerEx(), KF_RDTSC, KiInitializeInterruptTimersDpc(), KiTimeLimitIsrMicroseconds, NonPagedPool, NULL, _LARGE_INTEGER::QuadPart, KISRTIMERINIT::SampleTimer, and SynchronizationTimer.
Referenced by Phase1InitializationDiscard().
VOID KiInitializeInterruptTimersDpc (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 1072 of file intobj.c.
References ExFreePool(), KISRTIMERINIT::InitialTime, KeCancelTimer(), KiIsrTscLimit, KiTimeLimitIsrMicroseconds, RDTSC(), KISRTIMERINIT::SampleTimer, and UNREFERENCED_PARAMETER.
Referenced by KiInitializeInterruptTimers().
VOID KiInterruptDispatch2ndLvl (VOID)
Referenced by KiGetVectorInfo().
ULONG KiStartUnexpectedRange (VOID)
Referenced by KiGetVectorInfo().
VOID FASTCALL KiTimedChainedDispatch2ndLvl (PKINTERRUPT Interrupt)
Definition at line 778 of file intobj.c.
References _KINTERRUPT::ActualLock, ASSERT, CONTAINING_RECORD, DbgBreakPoint(), DbgPrint(), FALSE, _LIST_ENTRY::Flink, _KINTERRUPT::InterruptListEntry, _KINTERRUPT::Irql, _KPRCB::IsrTime, KdDebuggerEnabled, KeGetCurrentPrcb(), KfLowerIrql(), KfRaiseIrql(), KiAcquireSpinLock(), KiIsrTscLimit, KiReleaseSpinLock(), LevelSensitive, _KINTERRUPT::Mode, RDTSC(), _KINTERRUPT::ServiceContext, _KINTERRUPT::ServiceRoutine, _KINTERRUPT::SynchronizeIrql, and TRUE.
VOID FASTCALL KiTimedInterruptDispatch (PKINTERRUPT Interrupt)
Definition at line 960 of file intobj.c.
References _KINTERRUPT::ActualLock, DbgBreakPoint(), DbgPrint(), _KPRCB::IsrTime, KdDebuggerEnabled, KeGetCurrentPrcb(), KiAcquireSpinLock(), KiIsrTscLimit, KiReleaseSpinLock(), RDTSC(), _KINTERRUPT::ServiceContext, and _KINTERRUPT::ServiceRoutine.
Variable Documentation
PKISRTIMERINIT KiIsrTimerInit
Definition at line 1069 of file intobj.c.
ULONGLONG KiIsrTscLimit = 0xFFFFFFFFFFFFFFFF
Definition at line 28 of file intobj.c.
Referenced by KiInitializeInterruptTimersDpc(), KiTimedChainedDispatch2ndLvl(), and KiTimedInterruptDispatch().
ULONG KiTimeLimitDpcMicroseconds
Definition at line 29 of file intobj.c.
ULONG KiTimeLimitIsrMicroseconds
Definition at line 30 of file intobj.c.
Referenced by KiInitializeInterruptTimers(), KiInitializeInterruptTimersDpc(), and KiInitMachineDependent().
ULONG KiUnexpectedEntrySize
Referenced by KiGetVectorInfo().