Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/avltable.c File Reference
avltable.c File Reference
#include <nt.h>
#include <ntrtl.h>
Data Structures
struct _TABLE_ENTRY_HEADER
Macros
#define checkit(p) (p)
Typedefs
typedef struct _TABLE_ENTRY_HEADER * PTABLE_ENTRY_HEADER
typedef struct _TABLE_ENTRY_HEADER TABLE_ENTRY_HEADER
Functions
VOID DeleteNodeFromTree (IN PRTL_AVL_TABLE Table, IN PRTL_BALANCED_LINKS NodeToDelete)
TABLE_SEARCH_RESULT FindNodeOrParent (IN PRTL_AVL_TABLE Table, IN PVOID Buffer, OUT PRTL_BALANCED_LINKS *NodeOrParent)
NTSTATUS MatchAll (IN PRTL_AVL_TABLE Table, IN PVOID P1, IN PVOID P2)
VOID PromoteNode (IN PRTL_BALANCED_LINKS C)
PRTL_BALANCED_LINKS RealPredecessor (IN PRTL_BALANCED_LINKS Links)
PRTL_BALANCED_LINKS RealSuccessor (IN PRTL_BALANCED_LINKS Links)
ULONG RebalanceNode (IN PRTL_BALANCED_LINKS S)
BOOLEAN RtlDeleteElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer)
PVOID RtlEnumerateGenericTableAvl (IN PRTL_AVL_TABLE Table, IN BOOLEAN Restart)
PVOID NTAPI RtlEnumerateGenericTableLikeADirectory (IN PRTL_AVL_TABLE Table, IN PRTL_AVL_MATCH_FUNCTION MatchFunction OPTIONAL, IN PVOID MatchData OPTIONAL, IN ULONG NextFlag, IN OUT PVOID *RestartKey, IN OUT PULONG DeleteCount, IN PVOID Buffer)
PVOID RtlEnumerateGenericTableWithoutSplayingAvl (IN PRTL_AVL_TABLE Table, IN PVOID *RestartKey)
PVOID RtlGetElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN ULONG I)
VOID RtlInitializeGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PRTL_AVL_COMPARE_ROUTINE CompareRoutine, IN PRTL_AVL_ALLOCATE_ROUTINE AllocateRoutine, IN PRTL_AVL_FREE_ROUTINE FreeRoutine, IN PVOID TableContext)
PVOID RtlInsertElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL)
PVOID RtlInsertElementGenericTableFullAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL, IN PVOID NodeOrParent, IN TABLE_SEARCH_RESULT SearchResult)
BOOLEAN RtlIsGenericTableEmptyAvl (IN PRTL_AVL_TABLE Table)
PVOID RtlLookupElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer)
PVOID NTAPI RtlLookupElementGenericTableFullAvl (PRTL_AVL_TABLE Table, PVOID Buffer, OUT PVOID *NodeOrParent, OUT TABLE_SEARCH_RESULT *SearchResult)
ULONG RtlNumberGenericTableElementsAvl (IN PRTL_AVL_TABLE Table)
Variables
ULONG BestCaseFill [33]
ULONG WorstCaseFill [33]
Macro Definition Documentation
#define checkit (p) (p)
Definition at line 35 of file avltable.c.
Referenced by DeleteNodeFromTree(), PromoteNode(), and RtlInsertElementGenericTableFullAvl().
Typedef Documentation
typedef struct _TABLE_ENTRY_HEADER * PTABLE_ENTRY_HEADER
typedef struct _TABLE_ENTRY_HEADER TABLE_ENTRY_HEADER
Function Documentation
VOID DeleteNodeFromTree (IN PRTL_AVL_TABLE Table, IN PRTL_BALANCED_LINKS NodeToDelete)
Definition at line 582 of file avltable.c.
References ASSERT, _RTL_BALANCED_LINKS::Balance, checkit, _RTL_BALANCED_LINKS::LeftChild, NULL, _RTL_BALANCED_LINKS::Parent, RebalanceNode(), _RTL_BALANCED_LINKS::RightChild, RtlIsLeftChild, RtlIsRightChild, and TRUE.
Referenced by RtlDeleteElementGenericTableAvl().
TABLE_SEARCH_RESULT FindNodeOrParent (IN PRTL_AVL_TABLE Table, IN PVOID Buffer, OUT PRTL_BALANCED_LINKS * NodeOrParent)
Definition at line 115 of file avltable.c.
References ASSERT, GenericEqual, GenericGreaterThan, GenericLessThan, _RTL_BALANCED_LINKS::RightChild, RtlIsGenericTableEmptyAvl(), TableEmptyTree, TableFoundNode, TableInsertAsLeft, TableInsertAsRight, and TRUE.
Referenced by RtlDeleteElementGenericTableAvl(), RtlEnumerateGenericTableLikeADirectory(), RtlInsertElementGenericTableAvl(), and RtlLookupElementGenericTableFullAvl().
NTSTATUS MatchAll (IN PRTL_AVL_TABLE Table, IN PVOID P1, IN PVOID P2)
Definition at line 100 of file avltable.c.
References STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RtlEnumerateGenericTableLikeADirectory().
VOID PromoteNode (IN PRTL_BALANCED_LINKS C)
Definition at line 267 of file avltable.c.
References ASSERT, checkit, _RTL_BALANCED_LINKS::LeftChild, NULL, _RTL_BALANCED_LINKS::Parent, and _RTL_BALANCED_LINKS::RightChild.
Referenced by RebalanceNode().
PRTL_BALANCED_LINKS RealPredecessor (IN PRTL_BALANCED_LINKS Links)
Definition at line 885 of file avltable.c.
References _RTL_BALANCED_LINKS::LeftChild, NULL, _RTL_BALANCED_LINKS::Parent, _RTL_BALANCED_LINKS::RightChild, RtlIsLeftChild, and RtlIsRightChild.
Referenced by RtlDeleteElementGenericTableAvl(), and RtlGetElementGenericTableAvl().
PRTL_BALANCED_LINKS RealSuccessor (IN PRTL_BALANCED_LINKS Links)
Definition at line 794 of file avltable.c.
References ASSERT, _RTL_BALANCED_LINKS::LeftChild, NULL, _RTL_BALANCED_LINKS::Parent, _RTL_BALANCED_LINKS::RightChild, RtlIsLeftChild, and RtlIsRightChild.
Referenced by RtlEnumerateGenericTableLikeADirectory(), RtlEnumerateGenericTableWithoutSplayingAvl(), and RtlGetElementGenericTableAvl().
ULONG RebalanceNode (IN PRTL_BALANCED_LINKS S)
Definition at line 390 of file avltable.c.
References _RTL_BALANCED_LINKS::Balance, FALSE, _RTL_BALANCED_LINKS::LeftChild, PromoteNode(), _RTL_BALANCED_LINKS::RightChild, and TRUE.
Referenced by DeleteNodeFromTree(), and RtlInsertElementGenericTableFullAvl().
BOOLEAN RtlDeleteElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer)
Definition at line 1375 of file avltable.c.
References ASSERT, BestCaseFill, DeleteNodeFromTree(), FALSE, FindNodeOrParent(), NULL, RealPredecessor(), TableFoundNode, TRUE, and WorstCaseFill.
PVOID RtlEnumerateGenericTableAvl (IN PRTL_AVL_TABLE Table, IN BOOLEAN Restart)
Definition at line 1597 of file avltable.c.
References NULL, and RtlEnumerateGenericTableWithoutSplayingAvl().
PVOID NTAPI RtlEnumerateGenericTableLikeADirectory (IN PRTL_AVL_TABLE Table, IN PRTL_AVL_MATCH_FUNCTION MatchFunction OPTIONAL, IN PVOID MatchData OPTIONAL, IN ULONG NextFlag, IN OUT PVOID * RestartKey, IN OUT PULONG DeleteCount, IN PVOID Buffer)
Definition at line 2075 of file avltable.c.
References ASSERT, FALSE, FIELD_OFFSET, FindNodeOrParent(), MatchAll(), NULL, RealSuccessor(), RtlIsGenericTableEmptyAvl(), Status, STATUS_NO_MATCH, STATUS_NO_MORE_MATCHES, STATUS_SUCCESS, TableFoundNode, TableInsertAsRight, and _TABLE_ENTRY_HEADER::UserData.
PVOID RtlEnumerateGenericTableWithoutSplayingAvl (IN PRTL_AVL_TABLE Table, IN PVOID * RestartKey)
Definition at line 1966 of file avltable.c.
References _RTL_BALANCED_LINKS::LeftChild, NULL, RealSuccessor(), _RTL_BALANCED_LINKS::RightChild, and RtlIsGenericTableEmptyAvl().
Referenced by RtlEnumerateGenericTableAvl().
PVOID RtlGetElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN ULONG I)
Definition at line 1685 of file avltable.c.
References _RTL_BALANCED_LINKS::LeftChild, MAXULONG, NOTHING, NULL, RealPredecessor(), RealSuccessor(), and _RTL_BALANCED_LINKS::RightChild.
VOID RtlInitializeGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PRTL_AVL_COMPARE_ROUTINE CompareRoutine, IN PRTL_AVL_ALLOCATE_ROUTINE AllocateRoutine, IN PRTL_AVL_FREE_ROUTINE FreeRoutine, IN PVOID TableContext)
Definition at line 972 of file avltable.c.
References ASSERT, RtlZeroMemory, and WorstCaseFill.
PVOID RtlInsertElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL)
Definition at line 1035 of file avltable.c.
References FindNodeOrParent(), and RtlInsertElementGenericTableFullAvl().
PVOID RtlInsertElementGenericTableFullAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer, IN CLONG BufferSize, OUT PBOOLEAN NewElement OPTIONAL, IN PVOID NodeOrParent, IN TABLE_SEARCH_RESULT SearchResult)
Definition at line 1123 of file avltable.c.
References ARGUMENT_PRESENT, ASSERT, _RTL_BALANCED_LINKS::Balance, _TABLE_ENTRY_HEADER::BalancedLinks, BestCaseFill, checkit, FALSE, FIELD_OFFSET, _RTL_BALANCED_LINKS::LeftChild, MAXULONG, NULL, _RTL_BALANCED_LINKS::Parent, RebalanceNode(), RtlCopyMemory, RtlIsLeftChild, RtlZeroMemory, TableEmptyTree, TableFoundNode, TableInsertAsLeft, TRUE, _TABLE_ENTRY_HEADER::UserData, and WorstCaseFill.
Referenced by RtlInsertElementGenericTableAvl().
BOOLEAN RtlIsGenericTableEmptyAvl (IN PRTL_AVL_TABLE Table)
Definition at line 1653 of file avltable.c.
References FALSE, and TRUE.
Referenced by FindNodeOrParent(), RtlEnumerateGenericTableLikeADirectory(), and RtlEnumerateGenericTableWithoutSplayingAvl().
PVOID RtlLookupElementGenericTableAvl (IN PRTL_AVL_TABLE Table, IN PVOID Buffer)
Definition at line 1484 of file avltable.c.
References RtlLookupElementGenericTableFullAvl().
PVOID NTAPI RtlLookupElementGenericTableFullAvl (PRTL_AVL_TABLE Table, PVOID Buffer, OUT PVOID * NodeOrParent, OUT TABLE_SEARCH_RESULT * SearchResult)
Definition at line 1534 of file avltable.c.
References FindNodeOrParent(), NULL, and TableFoundNode.
Referenced by RtlLookupElementGenericTableAvl().
ULONG RtlNumberGenericTableElementsAvl (IN PRTL_AVL_TABLE Table)
Definition at line 1936 of file avltable.c.
Variable Documentation
ULONG BestCaseFill[33]
Initial value:
= {  0,          1,          3,          7,          0xf,        0x1f,       0x3f,       0x7f,
                            0xff,       0x1ff,      0x3ff,      0x7ff,      0xfff,      0x1fff,     0x3fff,     0x7fff,
                            0xffff,     0x1ffff,    0x3ffff,    0x7ffff,    0xfffff,    0x1fffff,   0x3fffff,   0x7fffff,
                            0xffffff,   0x1ffffff,  0x3ffffff,  0x7ffffff,  0xfffffff,  0x1fffffff, 0x3fffffff, 0x7fffffff,
                            0xffffffff  }
Definition at line 45 of file avltable.c.
Referenced by RtlDeleteElementGenericTableAvl(), and RtlInsertElementGenericTableFullAvl().
ULONG WorstCaseFill[33]
Initial value:
= { 0,          1,          2,          4,          7,          12,         20,         33,
                            54,         88,         143,        232,        376,        609,        986,        1596,
                            2583,       4180,       6764,       10945,      17710,      28656,      46367,      75024,
                            121392,     196417,     317810,     514228,     832039,     1346268,    2178308,    3524577,
                            5702886     }
Definition at line 74 of file avltable.c.
Referenced by RtlDeleteElementGenericTableAvl(), RtlInitializeGenericTableAvl(), and RtlInsertElementGenericTableFullAvl().