Windows Research Kernel v1.2: C:/Windows Research Kernel/dbgk/dbgkproc.c File Reference
dbgkproc.c File Reference
#include "dbgkp.h"
Functions
VOID DbgkCreateThread (PETHREAD Thread, PVOID StartAddress)
VOID DbgkExitProcess (NTSTATUS ExitStatus)
VOID DbgkExitThread (NTSTATUS ExitStatus)
VOID DbgkMapViewOfSection (IN PVOID SectionObject, IN PVOID BaseAddress, IN ULONG SectionOffset, IN ULONG_PTR ViewSize)
VOID DbgkpResumeProcess (VOID)
HANDLE DbgkpSectionToFileHandle (IN PVOID SectionObject)
BOOLEAN DbgkpSuspendProcess (VOID)
VOID DbgkUnMapViewOfSection (IN PVOID BaseAddress)
Function Documentation
VOID DbgkCreateThread (PETHREAD Thread, PVOID StartAddress)
Definition at line 175 of file dbgkproc.c.
References _DBGKM_LOAD_DLL::BaseOfDll, _DBGKM_CREATE_PROCESS::BaseOfImage, _DBGKM_APIMSG::CreateProcessInfo, _DBGKM_APIMSG::CreateThread, DBGKM_FORMAT_API_MSG, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgKmLoadDllApi, DBGKP_FIELD_FROM_IMAGE_OPTIONAL_HEADER, DbgkpSectionToFileHandle(), DbgkpSendApiMessage(), _DBGKM_CREATE_PROCESS::DebugInfoFileOffset, _DBGKM_LOAD_DLL::DebugInfoFileOffset, _DBGKM_CREATE_PROCESS::DebugInfoSize, _DBGKM_LOAD_DLL::DebugInfoSize, _EPROCESS::DebugPort, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, _DBGKM_CREATE_PROCESS::FileHandle, _DBGKM_LOAD_DLL::FileHandle, _IMAGE_NT_HEADERS::FileHeader, _EPROCESS::Flags, GENERIC_READ, IMAGE_ADDRESSING_MODE_32BIT, _IMAGE_INFO::ImageAddressingMode, _IMAGE_INFO::ImageBase, _IMAGE_INFO::ImageSectionNumber, _IMAGE_INFO::ImageSelector, _IMAGE_INFO::ImageSize, InitializeObjectAttributes, _DBGKM_CREATE_PROCESS::InitialThread, KernelMode, _DBGKM_APIMSG::LoadDll, MmGetFileNameForSection(), _OBJECT_NAME_INFORMATION::Name, _DBGKM_LOAD_DLL::NamePointer, NT_SUCCESS, NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, _IMAGE_INFO::Properties, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_PROCESS_FLAGS_IMAGE_NOTIFY_DONE, PS_TEST_SET_BITS, PsCallImageNotifyRoutines(), PsGetCurrentProcessByThread, PsImageNotifyEnabled, PsNtDllPathName, PsSystemDllBase, RtlImageNtHeader(), RtlInitUnicodeString(), _EPROCESS::SectionBaseAddress, _EPROCESS::SectionObject, _DBGKM_CREATE_THREAD::StartAddress, Status, _DBGKM_CREATE_THREAD::SubSystemKey, _DBGKM_CREATE_PROCESS::SubSystemKey, SYNCHRONIZE, _ETHREAD::Tcb, _KTHREAD::Teb, TRUE, _DBGKM_APIMSG::u, UlongToPtr, _EPROCESS::UniqueProcessId, wcsncpy(), and ZwOpenFile().
Referenced by PspUserThreadStartup().
VOID DbgkExitProcess (NTSTATUS ExitStatus)
Definition at line 534 of file dbgkproc.c.
References DBGKM_FORMAT_API_MSG, DbgKmExitProcessApi, DbgkpSendApiMessage(), _EPROCESS::DebugPort, _DBGKM_APIMSG::ExitProcess, _DBGKM_EXIT_PROCESS::ExitStatus, _EPROCESS::ExitTime, FALSE, KeQuerySystemTime(), NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), and _DBGKM_APIMSG::u.
Referenced by PspExitThread().
VOID DbgkExitThread (NTSTATUS ExitStatus)
Definition at line 470 of file dbgkproc.c.
References DBGKM_FORMAT_API_MSG, DbgKmExitThreadApi, DbgkpResumeProcess(), DbgkpSendApiMessage(), DbgkpSuspendProcess(), _EPROCESS::DebugPort, _DBGKM_EXIT_THREAD::ExitStatus, _DBGKM_APIMSG::ExitThread, FALSE, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), and _DBGKM_APIMSG::u.
Referenced by PspExitThread().
VOID DbgkMapViewOfSection (IN PVOID SectionObject, IN PVOID BaseAddress, IN ULONG SectionOffset, IN ULONG_PTR ViewSize)
Definition at line 597 of file dbgkproc.c.
References _DBGKM_LOAD_DLL::BaseOfDll, DBGKM_FORMAT_API_MSG, DbgKmLoadDllApi, DbgkpSectionToFileHandle(), DbgkpSendApiMessage(), _DBGKM_LOAD_DLL::DebugInfoFileOffset, _DBGKM_LOAD_DLL::DebugInfoSize, _EPROCESS::DebugPort, except, EXCEPTION_EXECUTE_HANDLER, _DBGKM_LOAD_DLL::FileHandle, _IMAGE_NT_HEADERS::FileHeader, KeGetPreviousMode, KernelMode, _DBGKM_APIMSG::LoadDll, _DBGKM_LOAD_DLL::NamePointer, NtCurrentTeb(), NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), RtlImageNtHeader(), TRUE, _DBGKM_APIMSG::u, and UNREFERENCED_PARAMETER.
Referenced by NtMapViewOfSection().
VOID DbgkpResumeProcess (VOID)
Definition at line 73 of file dbgkproc.c.
References KeThawAllThreads(), and PAGED_CODE.
Referenced by DbgkExitThread(), DbgkpSendApiMessage(), and DbgkpSendApiMessageLpc().
HANDLE DbgkpSectionToFileHandle (IN PVOID SectionObject)
Definition at line 109 of file dbgkproc.c.
References ExFreePool(), FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, GENERIC_READ, Handle, InitializeObjectAttributes, MmGetFileNameForSection(), _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, Status, SYNCHRONIZE, and ZwOpenFile().
Referenced by DbgkCreateThread(), DbgkMapViewOfSection(), and DbgkpPostFakeThreadMessages().
BOOLEAN DbgkpSuspendProcess (VOID)
Definition at line 36 of file dbgkproc.c.
References FALSE, KeFreezeAllThreads(), PAGED_CODE, PS_PROCESS_FLAGS_PROCESS_DELETE, PsGetCurrentProcess(), and TRUE.
Referenced by DbgkExitThread(), DbgkpSendApiMessage(), and DbgkpSendApiMessageLpc().
VOID DbgkUnMapViewOfSection (IN PVOID BaseAddress)
Definition at line 699 of file dbgkproc.c.
References _DBGKM_UNLOAD_DLL::BaseAddress, DBGKM_FORMAT_API_MSG, DbgKmUnloadDllApi, DbgkpSendApiMessage(), _EPROCESS::DebugPort, KeGetPreviousMode, KernelMode, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), TRUE, _DBGKM_APIMSG::u, and _DBGKM_APIMSG::UnloadDll.
Referenced by MiUnmapViewOfSection().