Windows Research Kernel v1.2: C:/Windows Research Kernel/raw/rawprocs.h File Reference
rawprocs.h File Reference
#include <string.h>
#include <ntos.h>
#include <zwapi.h>
#include <FsRtl.h>
#include <ntdddisk.h>
#include "nodetype.h"
#include "RawStruc.h"
Macros
#define BooleanFlagOn(Flags, SingleFlag)
#define FlagOn(F, SF)
#define RawCompleteRequest(IRP, STATUS)
Functions
BOOLEAN RawCheckForDismount (PVCB Vcb, BOOLEAN CalledFromCreate)
NTSTATUS RawCleanup (IN PVCB Vcb, IN PIRP Irp, IN PIO_STACK_LOCATION IrpSp)
NTSTATUS RawClose (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawCompletionRoutine (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
NTSTATUS RawCreate (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawDispatch (IN PVOLUME_DEVICE_OBJECT VolumeDeviceObject, IN PIRP Irp)
NTSTATUS RawFileSystemControl (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawInitializeVcb (IN OUT PVCB Vcb, IN PDEVICE_OBJECT TargetDeviceObject, IN PVPB Vpb)
NTSTATUS RawQueryInformation (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawQueryVolumeInformation (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawReadWriteDeviceControl (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawSetInformation (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
Macro Definition Documentation
#define BooleanFlagOn (Flags, SingleFlag)
Value:
(\
    ((Flags) & (SingleFlag)) != 0 ? TRUE : FALSE)
Definition at line 153 of file rawprocs.h.
#define FlagOn (F, SF)
Value:
(\
    (((F) & (SF)))     \
)
Definition at line 160 of file rawprocs.h.
#define RawCompleteRequest (IRP, STATUS)
Value:
{           \
                                                   \
    (IRP)->IoStatus.Status = (STATUS);             \
                                                   \
    IoCompleteRequest( (IRP), IO_DISK_INCREMENT ); \
}
Definition at line 169 of file rawprocs.h.
Referenced by RawCleanup(), RawClose(), RawCreate(), RawDispatch(), RawFileSystemControl(), RawQueryInformation(), RawQueryVolumeInformation(), RawReadWriteDeviceControl(), RawSetInformation(), and RawShutdown().
Function Documentation
BOOLEAN RawCheckForDismount (PVCB Vcb, BOOLEAN CalledFromCreate)
Definition at line 111 of file strucsup.c.
References ASSERT, CONTAINING_RECORD, _VPB::DeviceObject, ExFreePool(), FALSE, FlagOn, _VPB::Flags, IO_TYPE_VPB, IoAcquireVpbSpinLock(), IoDeleteDevice(), IoReleaseVpbSpinLock(), KeReadStateMutant(), KeReleaseMutex(), _VCB::Mutex, NULL, ObDereferenceObject(), _VPB::RealDevice, _VPB::ReferenceCount, RtlZeroMemory, _VPB::Size, _VCB::SpareVpb, _VCB::TargetDeviceObject, TRUE, _VPB::Type, VCB_STATE_FLAG_DISMOUNTED, _VCB::VcbState, VOID, _VCB::Vpb, VPB_MOUNTED, VPB_PERSISTENT, and VPB_REMOVE_PENDING.
Referenced by RawCleanup(), RawClose(), RawCreate(), and RawVerifyVolume().
NTSTATUS RawCleanup (IN PVCB Vcb, IN PIRP Irp, IN PIO_STACK_LOCATION IrpSp)
Definition at line 28 of file cleanup.c.
References ASSERT, Executive, FALSE, FlagOn, IoRemoveShareAccess(), KeReleaseMutex(), KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, PAGED_CODE, RawCheckForDismount(), RawCompleteRequest, Status, STATUS_SUCCESS, VCB_STATE_FLAG_DISMOUNTED, and VOID.
Referenced by RawDispatch().
NTSTATUS RawClose (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawCompletionRoutine (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
Definition at line 200 of file rawdisp.c.
References _FILE_OBJECT::CurrentByteOffset, _IO_STACK_LOCATION::FileObject, FlagOn, _FILE_OBJECT::Flags, FO_SYNCHRONOUS_IO, IoGetCurrentIrpStackLocation, IoMarkIrpPending, IRP_MJ_READ, IRP_MJ_WRITE, _IO_STACK_LOCATION::MajorFunction, NT_SUCCESS, NULL, _LARGE_INTEGER::QuadPart, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RawReadWriteDeviceControl().
NTSTATUS RawCreate (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawDispatch (IN PVOLUME_DEVICE_OBJECT VolumeDeviceObject, IN PIRP Irp)
Definition at line 29 of file rawdisp.c.
References DEVICE_OBJECT, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, FILE_SYSTEM, FsRtlEnterFileSystem, FsRtlExitFileSystem, FsRtlIsNtstatusExpected(), IoGetCurrentIrpStackLocation, IRP_MJ_CLEANUP, IRP_MJ_CLOSE, IRP_MJ_CREATE, IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MJ_PNP, IRP_MJ_QUERY_INFORMATION, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_MJ_READ, IRP_MJ_SET_INFORMATION, IRP_MJ_WRITE, IRP_MN_MOUNT_VOLUME, IRP_MN_QUERY_REMOVE_DEVICE, KdPrint, KeBugCheckEx(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, PAGED_CODE, RawCleanup(), RawClose(), RawCompleteRequest, RawCreate(), RawFileSystemControl(), RawQueryInformation(), RawQueryVolumeInformation(), RawReadWriteDeviceControl(), RawSetInformation(), Status, STATUS_DEVICE_BUSY, STATUS_INVALID_DEVICE_REQUEST, and STATUS_SUCCESS.
Referenced by RawInitialize().
NTSTATUS RawFileSystemControl (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
NTSTATUS RawInitializeVcb (IN OUT PVCB Vcb, IN PDEVICE_OBJECT TargetDeviceObject, IN PVPB Vpb)
Definition at line 28 of file strucsup.c.
References ExAllocatePoolWithTag, KeInitializeMutex(), MUTEX_LEVEL_FILESYSTEM_RAW_VCB, NonPagedPool, NULL, PAGED_CODE, RAW_NTC_VCB, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by RawMountVolume().
NTSTATUS RawQueryInformation (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
Definition at line 28 of file fileinfo.c.
References _FILE_POSITION_INFORMATION::CurrentByteOffset, _FILE_OBJECT::CurrentByteOffset, _IO_STACK_LOCATION::FileObject, FilePositionInformation, PAGED_CODE, _IO_STACK_LOCATION::Parameters, RawCompleteRequest, Status, STATUS_BUFFER_OVERFLOW, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RawDispatch().
NTSTATUS RawQueryVolumeInformation (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
Referenced by RawDispatch().
NTSTATUS RawReadWriteDeviceControl (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
Referenced by RawDispatch().
NTSTATUS RawSetInformation (IN PVCB Vcb, IN PIRP Irp, PIO_STACK_LOCATION IrpSp)
Definition at line 121 of file fileinfo.c.
References _FILE_POSITION_INFORMATION::CurrentByteOffset, _FILE_OBJECT::CurrentByteOffset, _IO_STACK_LOCATION::FileObject, FilePositionInformation, IoGetRelatedDeviceObject(), _LARGE_INTEGER::LowPart, PAGED_CODE, _IO_STACK_LOCATION::Parameters, RawCompleteRequest, Status, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RawDispatch().