Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/stdio.h File Reference
stdio.h File Reference
Data Structures
struct _iobuf
struct fpos_t
Macros
#define __cdecl
#define _CRTIMP
#define _FILE_DEFINED
#define _fileno(_stream) ((_stream)->_file)
#define _FPOS_T_DEFINED
#define _FPOSOFF(fp) ((long)(fp).lopart)
#define _INC_STDIO
#define _IOB_ENTRIES 20
#define _IOEOF 0x0010
#define _IOERR 0x0020
#define _IOFBF 0x0000
#define _IOLBF 0x0040
#define _IOMYBUF 0x0008
#define _IONBF 0x0004
#define _IOREAD 0x0001
#define _IORW 0x0080
#define _IOSTRG 0x0040
#define _IOWRT 0x0002
#define _NFILE _NSTREAM_
#define _NSTREAM_ 512
#define _P_tmpdir "\\"
#define _SIZE_T_DEFINED
#define _STDIO_DEFINED
#define _SYS_OPEN 20
#define _VA_LIST_DEFINED
#define _W64
#define _WCHAR_T_DEFINED
#define _WCTYPE_T_DEFINED
#define _wP_tmpdir L"\\"
#define _WSTDIO_DEFINED
#define BUFSIZ 512
#define EOF (-1)
#define feof(_stream) ((_stream)->_flag & _IOEOF)
#define ferror(_stream) ((_stream)->_flag & _IOERR)
#define FILENAME_MAX 260
#define FOPEN_MAX 20
#define getc(_stream)
#define getchar() getc(stdin)
#define getwc(_stm) fgetwc(_stm)
#define getwchar() fgetwc(stdin)
#define L_tmpnam sizeof(_P_tmpdir)+12
#define NULL ((void *)0)
#define P_tmpdir _P_tmpdir
#define putc(_c, _stream)
#define putchar(_c) putc((_c),stdout)
#define putwc(_c, _stm) fputwc(_c,_stm)
#define putwchar(_c) fputwc((_c),stdout)
#define SEEK_CUR 1
#define SEEK_END 2
#define SEEK_SET 0
#define stderr (&_iob[2])
#define stdin (&_iob[0])
#define stdout (&_iob[1])
#define SYS_OPEN _SYS_OPEN
#define TMP_MAX 32767
#define WEOF (wint_t)(0xFFFF)
Typedefs
typedef struct _iobuf FILE
typedef struct fpos_t fpos_t
typedef _W64 unsigned int size_t
typedef char * va_list
typedef unsigned short wchar_t
typedef unsigned short wctype_t
typedef unsigned short wint_t
Functions
_CRTIMP int __cdecl _fcloseall (void)
_CRTIMP FILE *__cdecl _fdopen (int, const char *)
_CRTIMP int __cdecl _fgetchar (void)
_CRTIMP wint_t __cdecl _fgetwchar (void)
_CRTIMP int __cdecl _filbuf (FILE *)
_CRTIMP int __cdecl _fileno (FILE *)
_CRTIMP int __cdecl _flsbuf (int, FILE *)
_CRTIMP int __cdecl _flushall (void)
_CRTIMP int __cdecl _fputchar (int)
_CRTIMP wint_t __cdecl _fputwchar (wchar_t)
_CRTIMP FILE *__cdecl _fsopen (const char *, const char *, int)
_CRTIMP int __cdecl _getmaxstdio (void)
_CRTIMP int __cdecl _getw (FILE *)
_CRTIMP wchar_t *__cdecl _getws (wchar_t *)
_CRTIMP int __cdecl _pclose (FILE *)
_CRTIMP FILE *__cdecl _popen (const char *, const char *)
_CRTIMP int __cdecl _putw (int, FILE *)
_CRTIMP int __cdecl _putws (const wchar_t *)
_CRTIMP int __cdecl _rmtmp (void)
_CRTIMP int __cdecl _scprintf (const char *,...)
_CRTIMP int __cdecl _scwprintf (const wchar_t *,...)
_CRTIMP int __cdecl _setmaxstdio (int)
_CRTIMP int __cdecl _snprintf (char *, size_t, const char *,...)
_CRTIMP int __cdecl _snscanf (const char *, size_t, const char *,...)
_CRTIMP int __cdecl _snwprintf (wchar_t *, size_t, const wchar_t *,...)
_CRTIMP int __cdecl _snwscanf (const wchar_t *, size_t, const wchar_t *,...)
_CRTIMP char *__cdecl _tempnam (const char *, const char *)
_CRTIMP int __cdecl _unlink (const char *)
_CRTIMP int __cdecl _vscprintf (const char *, va_list)
_CRTIMP int __cdecl _vscwprintf (const wchar_t *, va_list)
_CRTIMP int __cdecl _vsnprintf (char *, size_t, const char *, va_list)
_CRTIMP int __cdecl _vsnwprintf (wchar_t *, size_t, const wchar_t *, va_list)
_CRTIMP FILE *__cdecl _wfdopen (int, const wchar_t *)
_CRTIMP FILE *__cdecl _wfopen (const wchar_t *, const wchar_t *)
_CRTIMP FILE *__cdecl _wfreopen (const wchar_t *, const wchar_t *, FILE *)
_CRTIMP FILE *__cdecl _wfsopen (const wchar_t *, const wchar_t *, int)
_CRTIMP void __cdecl _wperror (const wchar_t *)
_CRTIMP FILE *__cdecl _wpopen (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl _wremove (const wchar_t *)
_CRTIMP wchar_t *__cdecl _wtempnam (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl _wtmpnam (wchar_t *)
_CRTIMP void __cdecl clearerr (FILE *)
_CRTIMP int __cdecl fclose (FILE *)
_CRTIMP int __cdecl fcloseall (void)
_CRTIMP FILE *__cdecl fdopen (int, const char *)
_CRTIMP int __cdecl feof (FILE *)
_CRTIMP int __cdecl ferror (FILE *)
_CRTIMP int __cdecl fflush (FILE *)
_CRTIMP int __cdecl fgetc (FILE *)
_CRTIMP int __cdecl fgetchar (void)
_CRTIMP int __cdecl fgetpos (FILE *, fpos_t *)
_CRTIMP char *__cdecl fgets (char *, int, FILE *)
_CRTIMP wint_t __cdecl fgetwc (FILE *)
_CRTIMP wchar_t *__cdecl fgetws (wchar_t *, int, FILE *)
_CRTIMP int __cdecl fileno (FILE *)
_CRTIMP int __cdecl flushall (void)
_CRTIMP FILE *__cdecl fopen (const char *, const char *)
_CRTIMP int __cdecl fprintf (FILE *, const char *,...)
_CRTIMP int __cdecl fputc (int, FILE *)
_CRTIMP int __cdecl fputchar (int)
_CRTIMP int __cdecl fputs (const char *, FILE *)
_CRTIMP wint_t __cdecl fputwc (wchar_t, FILE *)
_CRTIMP int __cdecl fputws (const wchar_t *, FILE *)
_CRTIMP size_t __cdecl fread (void *, size_t, size_t, FILE *)
_CRTIMP FILE *__cdecl freopen (const char *, const char *, FILE *)
_CRTIMP int __cdecl fscanf (FILE *, const char *,...)
_CRTIMP int __cdecl fseek (FILE *, long, int)
_CRTIMP int __cdecl fsetpos (FILE *, const fpos_t *)
_CRTIMP long __cdecl ftell (FILE *)
_CRTIMP int __cdecl fwprintf (FILE *, const wchar_t *,...)
_CRTIMP size_t __cdecl fwrite (const void *, size_t, size_t, FILE *)
_CRTIMP int __cdecl fwscanf (FILE *, const wchar_t *,...)
_CRTIMP int __cdecl getc (FILE *)
_CRTIMP char *__cdecl gets (char *)
_CRTIMP int __cdecl getw (FILE *)
_CRTIMP wint_t __cdecl getwc (FILE *)
_CRTIMP void __cdecl perror (const char *)
_CRTIMP int __cdecl printf (const char *,...)
_CRTIMP int __cdecl putc (int, FILE *)
_CRTIMP int __cdecl putchar (int)
_CRTIMP int __cdecl puts (const char *)
_CRTIMP int __cdecl putw (int, FILE *)
_CRTIMP wint_t __cdecl putwc (wchar_t, FILE *)
_CRTIMP wint_t __cdecl putwchar (wchar_t)
_CRTIMP int __cdecl remove (const char *)
_CRTIMP int __cdecl rename (const char *, const char *)
_CRTIMP void __cdecl rewind (FILE *)
_CRTIMP int __cdecl rmtmp (void)
_CRTIMP int __cdecl scanf (const char *,...)
_CRTIMP void __cdecl setbuf (FILE *, char *)
_CRTIMP int __cdecl setvbuf (FILE *, char *, int, size_t)
_CRTIMP int __cdecl sprintf (char *, const char *,...)
_CRTIMP int __cdecl sscanf (const char *, const char *,...)
_CRTIMP int __cdecl swprintf (wchar_t *, const wchar_t *,...)
_CRTIMP int __cdecl swscanf (const wchar_t *, const wchar_t *,...)
_CRTIMP char *__cdecl tempnam (const char *, const char *)
_CRTIMP FILE *__cdecl tmpfile (void)
_CRTIMP char *__cdecl tmpnam (char *)
_CRTIMP int __cdecl ungetc (int, FILE *)
_CRTIMP wint_t __cdecl ungetwc (wint_t, FILE *)
_CRTIMP int __cdecl unlink (const char *)
_CRTIMP int __cdecl vfprintf (FILE *, const char *, va_list)
_CRTIMP int __cdecl vfwprintf (FILE *, const wchar_t *, va_list)
_CRTIMP int __cdecl vprintf (const char *, va_list)
_CRTIMP int __cdecl vsprintf (char *, const char *, va_list)
_CRTIMP int __cdecl vswprintf (wchar_t *, const wchar_t *, va_list)
_CRTIMP int __cdecl vwprintf (const wchar_t *, va_list)
_CRTIMP int __cdecl wprintf (const wchar_t *,...)
_CRTIMP int __cdecl wscanf (const wchar_t *,...)
Variables
_CRTIMP FILE _iob []
Macro Definition Documentation
#define __cdecl
Definition at line 66 of file stdio.h.
#define _CRTIMP
Definition at line 58 of file stdio.h.
#define _FILE_DEFINED
Definition at line 143 of file stdio.h.
#define _fileno (_stream) ((_stream)->_file)
Definition at line 407 of file stdio.h.
#define _FPOS_T_DEFINED
Definition at line 224 of file stdio.h.
#define _FPOSOFF (fp) ((long)(fp).lopart)
Definition at line 220 of file stdio.h.
#define _INC_STDIO
Definition at line 29 of file stdio.h.
#define _IOB_ENTRIES 20
Definition at line 126 of file stdio.h.
#define _IOEOF 0x0010
Definition at line 241 of file stdio.h.
#define _IOERR 0x0020
Definition at line 242 of file stdio.h.
#define _IOFBF 0x0000
Definition at line 236 of file stdio.h.
#define _IOLBF 0x0040
Definition at line 237 of file stdio.h.
#define _IOMYBUF 0x0008
Definition at line 240 of file stdio.h.
#define _IONBF 0x0004
Definition at line 238 of file stdio.h.
#define _IOREAD 0x0001
Definition at line 233 of file stdio.h.
#define _IORW 0x0080
Definition at line 244 of file stdio.h.
#define _IOSTRG 0x0040
Definition at line 243 of file stdio.h.
#define _IOWRT 0x0002
Definition at line 234 of file stdio.h.
#define _NFILE _NSTREAM_
Definition at line 118 of file stdio.h.
#define _NSTREAM_ 512
Definition at line 120 of file stdio.h.
#define _P_tmpdir "\\"
Definition at line 153 of file stdio.h.
#define _SIZE_T_DEFINED
Definition at line 76 of file stdio.h.
#define _STDIO_DEFINED
Definition at line 399 of file stdio.h.
#define _SYS_OPEN 20
Definition at line 180 of file stdio.h.
#define _VA_LIST_DEFINED
Definition at line 105 of file stdio.h.
#define _W64
Definition at line 48 of file stdio.h.
#define _WCHAR_T_DEFINED
Definition at line 82 of file stdio.h.
#define _WCTYPE_T_DEFINED
Definition at line 89 of file stdio.h.
#define _wP_tmpdir L"\\"
Definition at line 154 of file stdio.h.
#define _WSTDIO_DEFINED
Definition at line 396 of file stdio.h.
#define BUFSIZ 512
Definition at line 111 of file stdio.h.
#define EOF (-1)
Definition at line 128 of file stdio.h.
Referenced by StringGetsExWorkerA().
#define feof (_stream) ((_stream)->_flag & _IOEOF)
Definition at line 405 of file stdio.h.
#define ferror (_stream) ((_stream)->_flag & _IOERR)
Definition at line 406 of file stdio.h.
#define FILENAME_MAX 260
Definition at line 178 of file stdio.h.
#define FOPEN_MAX 20
Definition at line 179 of file stdio.h.
#define getc (_stream)
Value:
(--(_stream)->_cnt >= 0 \
                ? 0xff & *(_stream)->_ptr++ : _filbuf(_stream))
Definition at line 408 of file stdio.h.
_CRTIMP int __cdecl getchar () getc(stdin)
Definition at line 412 of file stdio.h.
#define getwc (_stm) fgetwc(_stm)
Definition at line 383 of file stdio.h.
Referenced by StringGetsExWorkerW().
_CRTIMP wint_t __cdecl getwchar () fgetwc(stdin)
Definition at line 381 of file stdio.h.
#define L_tmpnam sizeof(_P_tmpdir)+12
Definition at line 162 of file stdio.h.
#define NULL ((void *)0)
Definition at line 190 of file stdio.h.
#define P_tmpdir _P_tmpdir
Definition at line 430 of file stdio.h.
#define putc (_c, _stream)
Value:
(--(_stream)->_cnt >= 0 \
                ? 0xff & (*(_stream)->_ptr++ = (char)(_c)) :  _flsbuf((_c),(_stream)))
Definition at line 410 of file stdio.h.
#define putchar (_c) putc((_c),stdout)
Definition at line 413 of file stdio.h.
#define putwc (_c, _stm) fputwc(_c,_stm)
Definition at line 384 of file stdio.h.
#define putwchar (_c) fputwc((_c),stdout)
Definition at line 382 of file stdio.h.
#define SEEK_CUR 1
Definition at line 173 of file stdio.h.
#define SEEK_END 2
Definition at line 174 of file stdio.h.
#define SEEK_SET 0
Definition at line 175 of file stdio.h.
#define stderr (&_iob[2])
Definition at line 230 of file stdio.h.
#define stdin (&_iob[0])
Definition at line 228 of file stdio.h.
Referenced by StringGetsExWorkerA(), and StringGetsExWorkerW().
#define stdout (&_iob[1])
Definition at line 229 of file stdio.h.
#define SYS_OPEN _SYS_OPEN
Definition at line 431 of file stdio.h.
#define TMP_MAX 32767
Definition at line 181 of file stdio.h.
#define WEOF (wint_t)(0xFFFF)
Definition at line 342 of file stdio.h.
Typedef Documentation
typedef struct _iobuf FILE
Definition at line 142 of file stdio.h.
typedef struct fpos_t fpos_t
typedef _W64 unsigned int size_t
Definition at line 74 of file stdio.h.
typedef char* va_list
Definition at line 103 of file stdio.h.
typedef unsigned short wchar_t
Definition at line 81 of file stdio.h.
typedef unsigned short wctype_t
Definition at line 88 of file stdio.h.
typedef unsigned short wint_t
Definition at line 87 of file stdio.h.
Function Documentation
_CRTIMP int __cdecl _fcloseall (void)
_CRTIMP FILE* __cdecl _fdopen (int , const char *)
_CRTIMP int __cdecl _fgetchar (void)
_CRTIMP wint_t __cdecl _fgetwchar (void)
_CRTIMP int __cdecl _filbuf (FILE *)
_CRTIMP int __cdecl _fileno (FILE *)
_CRTIMP int __cdecl _flsbuf (int , FILE *)
_CRTIMP int __cdecl _flushall (void)
_CRTIMP int __cdecl _fputchar (int)
_CRTIMP wint_t __cdecl _fputwchar (wchar_t)
_CRTIMP FILE* __cdecl _fsopen (const char * , const char * , int)
_CRTIMP int __cdecl _getmaxstdio (void)
_CRTIMP int __cdecl _getw (FILE *)
_CRTIMP wchar_t* __cdecl _getws (wchar_t *)
_CRTIMP int __cdecl _pclose (FILE *)
_CRTIMP FILE* __cdecl _popen (const char * , const char *)
_CRTIMP int __cdecl _putw (int , FILE *)
_CRTIMP int __cdecl _putws (const wchar_t *)
_CRTIMP int __cdecl _rmtmp (void)
_CRTIMP int __cdecl _scprintf (const char * , ...)
_CRTIMP int __cdecl _scwprintf (const wchar_t * , ...)
_CRTIMP int __cdecl _setmaxstdio (int)
_CRTIMP int __cdecl _snprintf (char * , size_t , const char * , ...)
Referenced by ExpSystemErrorHandler().
_CRTIMP int __cdecl _snscanf (const char * , size_t , const char * , ...)
_CRTIMP int __cdecl _snwprintf (wchar_t * , size_t , const wchar_t * , ...)
_CRTIMP int __cdecl _snwscanf (const wchar_t * , size_t , const wchar_t * , ...)
_CRTIMP char* __cdecl _tempnam (const char * , const char *)
_CRTIMP int __cdecl _unlink (const char *)
_CRTIMP int __cdecl _vscprintf (const char * , va_list)
_CRTIMP int __cdecl _vscwprintf (const wchar_t * , va_list)
_CRTIMP int __cdecl _vsnprintf (char * , size_t , const char * , va_list)
Referenced by vDbgPrintExWithPrefixInternal().
_CRTIMP int __cdecl _vsnwprintf (wchar_t * , size_t , const wchar_t * , va_list)
_CRTIMP FILE* __cdecl _wfdopen (int , const wchar_t *)
_CRTIMP FILE* __cdecl _wfopen (const wchar_t * , const wchar_t *)
_CRTIMP FILE* __cdecl _wfreopen (const wchar_t * , const wchar_t * , FILE *)
_CRTIMP FILE* __cdecl _wfsopen (const wchar_t * , const wchar_t * , int)
_CRTIMP void __cdecl _wperror (const wchar_t *)
_CRTIMP FILE* __cdecl _wpopen (const wchar_t * , const wchar_t *)
_CRTIMP int __cdecl _wremove (const wchar_t *)
_CRTIMP wchar_t* __cdecl _wtempnam (const wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl _wtmpnam (wchar_t *)
_CRTIMP void __cdecl clearerr (FILE *)
_CRTIMP int __cdecl fclose (FILE *)
_CRTIMP int __cdecl fcloseall (void)
_CRTIMP FILE* __cdecl fdopen (int , const char *)
_CRTIMP int __cdecl feof (FILE *)
_CRTIMP int __cdecl ferror (FILE *)
_CRTIMP int __cdecl fflush (FILE *)
_CRTIMP int __cdecl fgetc (FILE *)
_CRTIMP int __cdecl fgetchar (void)
_CRTIMP int __cdecl fgetpos (FILE * , fpos_t *)
_CRTIMP char* __cdecl fgets (char * , int , FILE *)
_CRTIMP wint_t __cdecl fgetwc (FILE *)
_CRTIMP wchar_t* __cdecl fgetws (wchar_t * , int , FILE *)
_CRTIMP int __cdecl fileno (FILE *)
_CRTIMP int __cdecl flushall (void)
_CRTIMP FILE* __cdecl fopen (const char * , const char *)
_CRTIMP int __cdecl fprintf (FILE * , const char * , ...)
_CRTIMP int __cdecl fputc (int , FILE *)
_CRTIMP int __cdecl fputchar (int)
_CRTIMP int __cdecl fputs (const char * , FILE *)
_CRTIMP wint_t __cdecl fputwc (wchar_t , FILE *)
_CRTIMP int __cdecl fputws (const wchar_t * , FILE *)
_CRTIMP size_t __cdecl fread (void * , size_t , size_t , FILE *)
_CRTIMP FILE* __cdecl freopen (const char * , const char * , FILE *)
_CRTIMP int __cdecl fscanf (FILE * , const char * , ...)
_CRTIMP int __cdecl fseek (FILE * , long , int)
_CRTIMP int __cdecl fsetpos (FILE * , const fpos_t *)
_CRTIMP long __cdecl ftell (FILE *)
_CRTIMP int __cdecl fwprintf (FILE * , const wchar_t * , ...)
_CRTIMP size_t __cdecl fwrite (const void * , size_t , size_t , FILE *)
_CRTIMP int __cdecl fwscanf (FILE * , const wchar_t * , ...)
_CRTIMP int __cdecl getc (FILE *)
Referenced by StringGetsExWorkerA().
_CRTIMP char* __cdecl gets (char *)
_CRTIMP int __cdecl getw (FILE *)
_CRTIMP wint_t __cdecl getwc (FILE *)
_CRTIMP void __cdecl perror (const char *)
_CRTIMP int __cdecl printf (const char * , ...)
_CRTIMP int __cdecl putc (int , FILE *)
_CRTIMP int __cdecl putchar (int)
_CRTIMP int __cdecl puts (const char *)
_CRTIMP int __cdecl putw (int , FILE *)
_CRTIMP wint_t __cdecl putwc (wchar_t , FILE *)
_CRTIMP wint_t __cdecl putwchar (wchar_t)
_CRTIMP int __cdecl remove (const char *)
_CRTIMP int __cdecl rename (const char * , const char *)
_CRTIMP void __cdecl rewind (FILE *)
_CRTIMP int __cdecl rmtmp (void)
_CRTIMP int __cdecl scanf (const char * , ...)
_CRTIMP void __cdecl setbuf (FILE * , char *)
_CRTIMP int __cdecl setvbuf (FILE * , char * , int , size_t)
_CRTIMP int __cdecl sprintf (char * , const char * , ...)
Referenced by CmpAddAliasEntry(), CmpCreateControlSet(), CmpFindControlSet(), IoAssignDriveLetters(), IoGetBootDiskInformation(), IopCopyBootLogRegistryToFile(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopMarkBootPartition(), IopReassignSystemRoot(), and MmLoadSystemImage().
_CRTIMP int __cdecl sscanf (const char * , const char * , ...)
_CRTIMP int __cdecl swprintf (wchar_t * , const wchar_t * , ...)
_CRTIMP int __cdecl swscanf (const wchar_t * , const wchar_t * , ...)
_CRTIMP char* __cdecl tempnam (const char * , const char *)
_CRTIMP FILE* __cdecl tmpfile (void)
_CRTIMP char* __cdecl tmpnam (char *)
_CRTIMP int __cdecl ungetc (int , FILE *)
_CRTIMP wint_t __cdecl ungetwc (wint_t , FILE *)
_CRTIMP int __cdecl unlink (const char *)
_CRTIMP int __cdecl vfprintf (FILE * , const char * , va_list)
_CRTIMP int __cdecl vfwprintf (FILE * , const wchar_t * , va_list)
_CRTIMP int __cdecl vprintf (const char * , va_list)
_CRTIMP int __cdecl vsprintf (char * , const char * , va_list)
_CRTIMP int __cdecl vswprintf (wchar_t * , const wchar_t * , va_list)
_CRTIMP int __cdecl vwprintf (const wchar_t * , va_list)
_CRTIMP int __cdecl wprintf (const wchar_t * , ...)
_CRTIMP int __cdecl wscanf (const wchar_t * , ...)
Variable Documentation
_CRTIMP FILE _iob[]