Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/nbqueue.c File Reference
nbqueue.c File Reference
#include "exp.h"
Data Structures
struct _NBQUEUE_HEADER
struct _NBQUEUE_NODE
union _NBQUEUE_POINTER
Typedefs
typedef struct _NBQUEUE_HEADER NBQUEUE_HEADER
typedef struct _NBQUEUE_NODE NBQUEUE_NODE
typedef union _NBQUEUE_POINTER NBQUEUE_POINTER
typedef struct _NBQUEUE_HEADER * PNBQUEUE_HEADER
typedef struct _NBQUEUE_NODE * PNBQUEUE_NODE
typedef union _NBQUEUE_POINTER * PNBQUEUE_POINTER
Functions
PVOID ExInitializeNBQueueHead (IN PSLIST_HEADER SlistHead)
BOOLEAN ExInsertTailNBQueue (IN PVOID Header, IN ULONG64 Value)
BOOLEAN ExRemoveHeadNBQueue (IN PVOID Header, OUT PULONG64 Value)
__inline VOID PackNBQPointer (IN PNBQUEUE_POINTER Entry, IN PNBQUEUE_NODE Node)
__inline PNBQUEUE_NODE UnpackNBQPointer (IN PNBQUEUE_POINTER Entry)
Typedef Documentation
typedef struct _NBQUEUE_HEADER NBQUEUE_HEADER
typedef struct _NBQUEUE_NODE NBQUEUE_NODE
typedef union _NBQUEUE_POINTER NBQUEUE_POINTER
typedef struct _NBQUEUE_HEADER * PNBQUEUE_HEADER
typedef struct _NBQUEUE_NODE * PNBQUEUE_NODE
typedef union _NBQUEUE_POINTER * PNBQUEUE_POINTER
Function Documentation
PVOID ExInitializeNBQueueHead (IN PSLIST_HEADER SlistHead)
Definition at line 136 of file nbqueue.c.
References _NBQUEUE_POINTER::Count, _NBQUEUE_POINTER::Data, ExAllocatePoolWithTag, ExFreePool(), _NBQUEUE_HEADER::Head, InterlockedPopEntrySList(), _NBQUEUE_NODE::Next, NonPagedPool, NULL, PackNBQPointer(), _NBQUEUE_HEADER::SlistHead, _NBQUEUE_HEADER::Tail, and _NBQUEUE_NODE::Value.
Referenced by MiInitializeSystemPtes().
BOOLEAN ExInsertTailNBQueue (IN PVOID Header, IN ULONG64 Value)
Definition at line 214 of file nbqueue.c.
References _NBQUEUE_POINTER::Count, _NBQUEUE_POINTER::Data, FALSE, InterlockedCompareExchange64, InterlockedPopEntrySList(), _NBQUEUE_NODE::Next, NULL, PackNBQPointer(), ReadForWriteAccess, _NBQUEUE_HEADER::SlistHead, _NBQUEUE_HEADER::Tail, TRUE, UnpackNBQPointer(), and _NBQUEUE_NODE::Value.
Referenced by MiReleaseSystemPtes(), and MmUnmapLockedPages().
BOOLEAN ExRemoveHeadNBQueue (IN PVOID Header, OUT PULONG64 Value)
Definition at line 339 of file nbqueue.c.
References _NBQUEUE_POINTER::Count, _NBQUEUE_POINTER::Data, FALSE, _NBQUEUE_HEADER::Head, InterlockedCompareExchange64, InterlockedPushEntrySList(), _NBQUEUE_NODE::Next, NULL, PackNBQPointer(), PSLIST_ENTRY, ReadForWriteAccess, _NBQUEUE_HEADER::SlistHead, _NBQUEUE_HEADER::Tail, TRUE, UnpackNBQPointer(), and _NBQUEUE_NODE::Value.
Referenced by MiReserveSystemPtes(), and MmMapLockedPagesSpecifyCache().
__inline VOID PackNBQPointer (IN PNBQUEUE_POINTER Entry, IN PNBQUEUE_NODE Node)
Definition at line 96 of file nbqueue.c.
Referenced by ExInitializeNBQueueHead(), ExInsertTailNBQueue(), and ExRemoveHeadNBQueue().
__inline PNBQUEUE_NODE UnpackNBQPointer (IN PNBQUEUE_POINTER Entry)
Definition at line 109 of file nbqueue.c.
Referenced by ExInsertTailNBQueue(), and ExRemoveHeadNBQueue().