Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/mtrramd.c File Reference
mtrramd.c File Reference
#include "ki.h"
Data Structures
struct _AMDK6_MTRR
struct _AMDK6_MTRR_MSR_IMAGE
struct _AMDK6_MTRR_REGION
Macros
#define AMDK6_MAX_MTRR 2
#define AMDK6_MTRR_MSR 0xC0000085
#define AMDK6_MTRR_TYPE_DISABLED 0
#define AMDK6_MTRR_TYPE_MASK 3
#define AMDK6_MTRR_TYPE_UC 1
#define AMDK6_MTRR_TYPE_WC 2
#define AMDK6_REGION_FLAGS_BIOS 0x00000001
#define AMDK6_REGION_UNUSED 0xFFFFFFFF
#define DBGMSG(a)
#define IDBG 0
#define MAX_K6_REGIONS 2
#define STATIC
Typedefs
typedef struct _AMDK6_MTRR AMDK6_MTRR
typedef struct _AMDK6_MTRR_MSR_IMAGE AMDK6_MTRR_MSR_IMAGE
typedef struct _AMDK6_MTRR_REGION AMDK6_MTRR_REGION
typedef struct _AMDK6_MTRR * PAMDK6_MTRR
typedef struct _AMDK6_MTRR_MSR_IMAGE * PAMDK6_MTRR_MSR_IMAGE
typedef struct _AMDK6_MTRR_REGION * PAMDK6_MTRR_REGION
Functions
BOOLEAN KiAmdK6AddRegion (ULONG BaseAddress, ULONG Size, MEMORY_CACHING_TYPE Type, ULONG Flags)
PAMDK6_MTRR_REGION KiAmdK6FindFreeRegion (MEMORY_CACHING_TYPE Type)
NTSTATUS KiAmdK6HandleWcRegionRequest (ULONG BaseAddress, ULONG Size)
VOID KiAmdK6InitializeMTRR (VOID)
VOID KiAmdK6MTRRAddRegionFromHW (AMDK6_MTRR RegImage)
NTSTATUS KiAmdK6MtrrCommitChanges (VOID)
NTSTATUS KiAmdK6MtrrSetMemoryType (ULONG BaseAddress, ULONG Size, MEMORY_CACHING_TYPE Type)
VOID KiAmdK6MtrrWRMSR (VOID)
NTSTATUS KiAmdK6RestoreMTRR ()
NTSTATUS KiLoadMTRR (PVOID Context)
Variables
ULONG AmdK6RegionCount
AMDK6_MTRR_REGION AmdK6Regions [MAX_K6_REGIONS]
ULONG AmdMtrrHwUsageCount
AMDK6_MTRR_MSR_IMAGE KiAmdK6Mtrr
KSPIN_LOCK KiRangeLock
Macro Definition Documentation
#define AMDK6_MAX_MTRR 2
Definition at line 95 of file mtrramd.c.
Referenced by KiAmdK6FindFreeRegion().
#define AMDK6_MTRR_MSR 0xC0000085
Definition at line 62 of file mtrramd.c.
Referenced by KiAmdK6InitializeMTRR(), and KiAmdK6MtrrWRMSR().
#define AMDK6_MTRR_TYPE_DISABLED 0
Definition at line 55 of file mtrramd.c.
Referenced by KiAmdK6InitializeMTRR(), KiAmdK6MTRRAddRegionFromHW(), and KiAmdK6MtrrCommitChanges().
#define AMDK6_MTRR_TYPE_MASK 3
Definition at line 58 of file mtrramd.c.
#define AMDK6_MTRR_TYPE_UC 1
Definition at line 56 of file mtrramd.c.
Referenced by KiAmdK6MTRRAddRegionFromHW().
#define AMDK6_MTRR_TYPE_WC 2
Definition at line 57 of file mtrramd.c.
Referenced by KiAmdK6MtrrCommitChanges().
#define AMDK6_REGION_FLAGS_BIOS 0x00000001
Definition at line 89 of file mtrramd.c.
Referenced by KiAmdK6FindFreeRegion(), KiAmdK6HandleWcRegionRequest(), and KiAmdK6MTRRAddRegionFromHW().
#define AMDK6_REGION_UNUSED 0xFFFFFFFF
Definition at line 83 of file mtrramd.c.
Referenced by KiAmdK6FindFreeRegion(), KiAmdK6HandleWcRegionRequest(), KiAmdK6InitializeMTRR(), and KiAmdK6MtrrCommitChanges().
#define DBGMSG (a)
Definition at line 17 of file mtrramd.c.
Referenced by KiAmdK6FindFreeRegion(), KiAmdK6InitializeMTRR(), KiAmdK6MtrrCommitChanges(), and KiAmdK6MtrrSetMemoryType().
#define IDBG 0
Definition at line 12 of file mtrramd.c.
#define MAX_K6_REGIONS 2
Definition at line 77 of file mtrramd.c.
Referenced by KiAmdK6InitializeMTRR().
#define STATIC
Definition at line 10 of file mtrramd.c.
Typedef Documentation
typedef struct _AMDK6_MTRR AMDK6_MTRR
typedef struct _AMDK6_MTRR_MSR_IMAGE AMDK6_MTRR_MSR_IMAGE
typedef struct _AMDK6_MTRR_REGION AMDK6_MTRR_REGION
typedef struct _AMDK6_MTRR * PAMDK6_MTRR
typedef struct _AMDK6_MTRR_MSR_IMAGE * PAMDK6_MTRR_MSR_IMAGE
typedef struct _AMDK6_MTRR_REGION * PAMDK6_MTRR_REGION
Function Documentation
BOOLEAN KiAmdK6AddRegion (ULONG BaseAddress, ULONG Size, MEMORY_CACHING_TYPE Type, ULONG Flags)
Definition at line 567 of file mtrramd.c.
References _AMDK6_MTRR_REGION::BaseAddress, FALSE, KiAmdK6FindFreeRegion(), NULL, _AMDK6_MTRR_REGION::RegionFlags, _AMDK6_MTRR_REGION::RegionType, _AMDK6_MTRR_REGION::Size, and TRUE.
Referenced by KiAmdK6HandleWcRegionRequest(), and KiAmdK6MTRRAddRegionFromHW().
PAMDK6_MTRR_REGION KiAmdK6FindFreeRegion (MEMORY_CACHING_TYPE Type)
Definition at line 588 of file mtrramd.c.
References AMDK6_MAX_MTRR, AMDK6_REGION_FLAGS_BIOS, AMDK6_REGION_UNUSED, AmdK6RegionCount, AmdMtrrHwUsageCount, DBGMSG, FALSE, MmWriteCombined, and NULL.
Referenced by KiAmdK6AddRegion().
NTSTATUS KiAmdK6HandleWcRegionRequest (ULONG BaseAddress, ULONG Size)
Definition at line 382 of file mtrramd.c.
References AMDK6_REGION_FLAGS_BIOS, AMDK6_REGION_UNUSED, AmdK6RegionCount, _AMDK6_MTRR_REGION::BaseAddress, FALSE, KiAmdK6AddRegion(), KiAmdK6MtrrCommitChanges(), MmWriteCombined, _AMDK6_MTRR_REGION::RegionFlags, _AMDK6_MTRR_REGION::RegionType, _AMDK6_MTRR_REGION::Size, STATUS_NOT_SUPPORTED, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by KiAmdK6MtrrSetMemoryType().
VOID KiAmdK6InitializeMTRR (VOID)
Definition at line 175 of file mtrramd.c.
References AMDK6_MTRR_MSR, AMDK6_MTRR_TYPE_DISABLED, AMDK6_REGION_UNUSED, AmdK6RegionCount, AmdMtrrHwUsageCount, _AMDK6_MTRR_REGION::BaseAddress, DBGMSG, _AMDK6_MTRR_MSR_IMAGE::hw, KeAcquireSpinLock, KeInitializeSpinLock(), KeReleaseSpinLock(), KiAmdK6MTRRAddRegionFromHW(), KiRangeLock, MAX_K6_REGIONS, _AMDK6_MTRR_MSR_IMAGE::QuadPart, RDMSR(), _AMDK6_MTRR_REGION::RegionFlags, and _AMDK6_MTRR_MSR_IMAGE::u.
Referenced by KiInitMachineDependent().
VOID KiAmdK6MTRRAddRegionFromHW (AMDK6_MTRR RegImage)
Definition at line 237 of file mtrramd.c.
References AMDK6_MTRR_TYPE_DISABLED, AMDK6_MTRR_TYPE_UC, AMDK6_REGION_FLAGS_BIOS, AmdMtrrHwUsageCount, ASSERT, _AMDK6_MTRR::base, KiAmdK6AddRegion(), _AMDK6_MTRR::mask, MmWriteCombined, and _AMDK6_MTRR::type.
Referenced by KiAmdK6InitializeMTRR().
NTSTATUS KiAmdK6MtrrCommitChanges (VOID)
Definition at line 642 of file mtrramd.c.
References AMDK6_MTRR_TYPE_DISABLED, AMDK6_MTRR_TYPE_WC, AMDK6_REGION_UNUSED, AmdK6RegionCount, _AMDK6_MTRR_REGION::BaseAddress, DBGMSG, _AMDK6_MTRR_MSR_IMAGE::hw, KiLoadMTRR(), MmWriteCombined, NULL, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, and _AMDK6_MTRR_MSR_IMAGE::u.
Referenced by KiAmdK6HandleWcRegionRequest().
NTSTATUS KiAmdK6MtrrSetMemoryType (ULONG BaseAddress, ULONG Size, MEMORY_CACHING_TYPE Type)
Definition at line 301 of file mtrramd.c.
References DBGMSG, DISPATCH_LEVEL, ExPageLockHandle, KeAcquireSpinLock, KeGetCurrentIrql(), KeReleaseSpinLock(), KiAmdK6HandleWcRegionRequest(), KiRangeLock, MmCached, MmLockPageableSectionByHandle(), MmNonCached, MmUnlockPageableImageSection(), MmWriteCombined, Status, STATUS_INVALID_PARAMETER, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
VOID KiAmdK6MtrrWRMSR (VOID)
Definition at line 761 of file mtrramd.c.
References AMDK6_MTRR_MSR, _AMDK6_MTRR_MSR_IMAGE::QuadPart, _AMDK6_MTRR_MSR_IMAGE::u, and WRMSR().
Referenced by KiLoadMTRR().
NTSTATUS KiAmdK6RestoreMTRR ()
NTSTATUS KiLoadMTRR (PVOID Context)
Referenced by KiAmdK6MtrrCommitChanges().
Variable Documentation
ULONG AmdK6RegionCount
Definition at line 162 of file mtrramd.c.
Referenced by KiAmdK6FindFreeRegion(), KiAmdK6HandleWcRegionRequest(), KiAmdK6InitializeMTRR(), and KiAmdK6MtrrCommitChanges().
AMDK6_MTRR_REGION AmdK6Regions[MAX_K6_REGIONS]
Definition at line 161 of file mtrramd.c.
ULONG AmdMtrrHwUsageCount
Definition at line 166 of file mtrramd.c.
Referenced by KiAmdK6FindFreeRegion(), KiAmdK6InitializeMTRR(), and KiAmdK6MTRRAddRegionFromHW().
AMDK6_MTRR_MSR_IMAGE KiAmdK6Mtrr
Definition at line 170 of file mtrramd.c.
KSPIN_LOCK KiRangeLock
Definition at line 266 of file mtrr.c.
Referenced by KeRestoreMtrr(), KeSetPhysicalCacheTypeRange(), KiAmdK6InitializeMTRR(), KiAmdK6MtrrSetMemoryType(), and KiInitializeMTRR().