Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/provider.c File Reference
provider.c File Reference
#include "wmikmp.h"
Functions
NTSTATUS __cdecl WmipFirmwareTableHandler (PSYSTEM_FIRMWARE_TABLE_INFORMATION TableInfo)
NTSTATUS __cdecl WmipRawSMBiosTableHandler (PSYSTEM_FIRMWARE_TABLE_INFORMATION TableInfo)
VOID WmipRegisterFirmwareProviders ()
Variables
ULONG WmipFirmwareTableArray []
Function Documentation
NTSTATUS __cdecl WmipFirmwareTableHandler (PSYSTEM_FIRMWARE_TABLE_INFORMATION TableInfo)
Definition at line 104 of file provider.c.
References _SYSTEM_FIRMWARE_TABLE_INFORMATION::Action, ASSERT, MmNonCached, MmUnmapIoSpace(), NULL, _LARGE_INTEGER::QuadPart, RtlCopyMemory, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER_1, STATUS_NOT_FOUND, STATUS_SUCCESS, SystemFirmwareTable_Enumerate, SystemFirmwareTable_Get, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableBuffer, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableBufferLength, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableID, and WmipFirmwareTableArray.
Referenced by WmipRegisterFirmwareProviders().
NTSTATUS __cdecl WmipRawSMBiosTableHandler (PSYSTEM_FIRMWARE_TABLE_INFORMATION TableInfo)
Definition at line 252 of file provider.c.
References _SYSTEM_FIRMWARE_TABLE_INFORMATION::Action, ASSERT, NT_SUCCESS, NULL, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER_1, STATUS_SUCCESS, SystemFirmwareTable_Enumerate, SystemFirmwareTable_Get, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableBuffer, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableBufferLength, and WmipGetSMBiosTableData().
Referenced by WmipRegisterFirmwareProviders().
VOID WmipRegisterFirmwareProviders ()
Definition at line 39 of file provider.c.
References _SYSTEM_FIRMWARE_TABLE_HANDLER::DriverObject, _SYSTEM_FIRMWARE_TABLE_HANDLER::FirmwareTableHandler, IoPnpDriverObject, NtSetSystemInformation(), _SYSTEM_FIRMWARE_TABLE_HANDLER::ProviderSignature, _SYSTEM_FIRMWARE_TABLE_HANDLER::Register, SystemRegisterFirmwareTableInformationHandler, TRUE, WmipFirmwareTableHandler(), and WmipRawSMBiosTableHandler().
Referenced by WMIInitialize().
Variable Documentation
ULONG WmipFirmwareTableArray[]
Initial value:
= {
    0xC0000,    0x20000,
    0xE0000,    0x20000,
}
Definition at line 97 of file provider.c.
Referenced by WmipFirmwareTableHandler().