Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntobapi.h File Reference
ntobapi.h File Reference
Data Structures
struct _OBJECT_BASIC_INFORMATION
struct _OBJECT_DIRECTORY_INFORMATION
struct _OBJECT_HANDLE_FLAG_INFORMATION
struct _OBJECT_NAME_INFORMATION
struct _OBJECT_TYPE_INFORMATION
struct _OBJECT_TYPES_INFORMATION
Macros
#define DIRECTORY_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0xF)
#define DIRECTORY_CREATE_OBJECT (0x0004)
#define DIRECTORY_CREATE_SUBDIRECTORY (0x0008)
#define DIRECTORY_QUERY (0x0001)
#define DIRECTORY_TRAVERSE (0x0002)
#define DUPLICATE_CLOSE_SOURCE 0x00000001
#define DUPLICATE_SAME_ACCESS 0x00000002
#define DUPLICATE_SAME_ATTRIBUTES 0x00000004
#define OBJ_MAX_REPARSE_ATTEMPTS 32
#define OBJ_NAME_PATH_SEPARATOR ((WCHAR)L'\\')
#define OBJECT_TYPE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0x1)
#define OBJECT_TYPE_CREATE (0x0001)
#define SYMBOLIC_LINK_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0x1)
#define SYMBOLIC_LINK_QUERY (0x0001)
Typedefs
typedef struct _OBJECT_BASIC_INFORMATION OBJECT_BASIC_INFORMATION
typedef struct _OBJECT_DIRECTORY_INFORMATION OBJECT_DIRECTORY_INFORMATION
typedef struct _OBJECT_HANDLE_FLAG_INFORMATION OBJECT_HANDLE_FLAG_INFORMATION
typedef enum _OBJECT_INFORMATION_CLASS OBJECT_INFORMATION_CLASS
typedef struct _OBJECT_NAME_INFORMATION OBJECT_NAME_INFORMATION
typedef struct _OBJECT_TYPE_INFORMATION OBJECT_TYPE_INFORMATION
typedef struct _OBJECT_TYPES_INFORMATION OBJECT_TYPES_INFORMATION
typedef struct _OBJECT_BASIC_INFORMATION * POBJECT_BASIC_INFORMATION
typedef struct _OBJECT_DIRECTORY_INFORMATION * POBJECT_DIRECTORY_INFORMATION
typedef struct _OBJECT_HANDLE_FLAG_INFORMATION * POBJECT_HANDLE_FLAG_INFORMATION
typedef struct _OBJECT_NAME_INFORMATION * POBJECT_NAME_INFORMATION
typedef struct _OBJECT_TYPE_INFORMATION * POBJECT_TYPE_INFORMATION
typedef struct _OBJECT_TYPES_INFORMATION * POBJECT_TYPES_INFORMATION
Enumerations
enum _OBJECT_INFORMATION_CLASS {
ObjectBasicInformation, ObjectNameInformation, ObjectTypeInformation, ObjectTypesInformation,
ObjectHandleFlagInformation, ObjectSessionInformation, MaxObjectInfoClass
}
Functions
NTSYSCALLAPI NTSTATUS NTAPI NtClose (__in HANDLE Handle)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in PUNICODE_STRING LinkTarget)
NTSYSCALLAPI NTSTATUS NTAPI NtDuplicateObject (__in HANDLE SourceProcessHandle, __in HANDLE SourceHandle, __in_opt HANDLE TargetProcessHandle, __out_opt PHANDLE TargetHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Options)
NTSYSCALLAPI NTSTATUS NTAPI NtMakePermanentObject (__in HANDLE Handle)
NTSYSCALLAPI NTSTATUS NTAPI NtMakeTemporaryObject (__in HANDLE Handle)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDirectoryObject (__in HANDLE DirectoryHandle, __out_bcount_opt(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in BOOLEAN RestartScan, __inout PULONG Context, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __out_bcount_opt(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __out_bcount_opt(Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Length, __out PULONG LengthNeeded)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySymbolicLinkObject (__in HANDLE LinkHandle, __inout PUNICODE_STRING LinkTarget, __out_opt PULONG ReturnedLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __in_bcount(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSYSCALLAPI NTSTATUS NTAPI NtSignalAndWaitForSingleObject (__in HANDLE SignalHandle, __in HANDLE WaitHandle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) HANDLE Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForMultipleObjects32 (__in ULONG Count, __in_ecount(Count) LONG Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForSingleObject (__in HANDLE Handle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Macro Definition Documentation
#define DIRECTORY_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0xF)
Definition at line 56 of file ntobapi.h.
Referenced by CreateSystemRootLink(), ExpInitializeCallbacks(), IopCreateRootDirectories(), ObInitSystem(), ObpCreateDosDevicesDirectory(), SeGetLogonIdDeviceMap(), and SepInitializationPhase1().
#define DIRECTORY_CREATE_OBJECT (0x0004)
Definition at line 53 of file ntobapi.h.
Referenced by ObpLookupObjectName(), and ObSwapObjectNames().
#define DIRECTORY_CREATE_SUBDIRECTORY (0x0008)
Definition at line 54 of file ntobapi.h.
Referenced by ObpLookupObjectName(), and ObSwapObjectNames().
#define DIRECTORY_QUERY (0x0001)
Definition at line 51 of file ntobapi.h.
Referenced by IopDeleteSessionSymLinks(), NtQueryDirectoryObject(), ObInitSystem(), SepCleanupLUIDDeviceMapDirectory(), and SepInitializationPhase1().
#define DIRECTORY_TRAVERSE (0x0002)
Definition at line 52 of file ntobapi.h.
Referenced by ObInitSystem(), ObpCheckTraverseAccess(), ObpLookupObjectName(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), and SepInitializationPhase1().
#define DUPLICATE_CLOSE_SOURCE 0x00000001
Definition at line 170 of file ntobapi.h.
Referenced by ObDuplicateObject().
#define DUPLICATE_SAME_ACCESS 0x00000002
Definition at line 171 of file ntobapi.h.
Referenced by DbgkpOpenHandles(), ObDuplicateObject(), and RtlCreateUserProcess().
#define DUPLICATE_SAME_ATTRIBUTES 0x00000004
Definition at line 172 of file ntobapi.h.
Referenced by ObDuplicateObject(), and RtlCreateUserProcess().
#define OBJ_MAX_REPARSE_ATTEMPTS 32
Definition at line 36 of file ntobapi.h.
Referenced by ObpLookupObjectName(), and ObpProcessDosDeviceSymbolicLink().
#define OBJ_NAME_PATH_SEPARATOR ((WCHAR)L'\\')
Definition at line 32 of file ntobapi.h.
Referenced by CmpCacheLookup(), CmpComputeHashKey(), CmpComputeHashValue(), CmpComputeKcbConvKey(), CmpConstructName(), CmpCreateKeyControlBlock(), CmpCreateLinkNode(), CmpDoCreate(), CmpGetHiveName(), CmpGetNameControlBlock(), CmpGetNextName(), CmpGetSymbolicLink(), CmpNameFromAttributes(), CmpParseKey(), ExpQueryModuleInformation(), IopInitializeBuiltinDriver(), IopQueryNameInternal(), IoSetInformation(), MmInitializeProcessAddressSpace(), MmLoadSystemImage(), NtQueryObject(), NtRenameKey(), NtSetInformationFile(), ObCreateObjectType(), ObpLookupObjectName(), ObpParseSymbolicLink(), ObpProcessDosDeviceSymbolicLink(), and ObpQueryNameString().
#define OBJECT_TYPE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0x1)
Definition at line 45 of file ntobapi.h.
Referenced by ObInitSystem().
#define OBJECT_TYPE_CREATE (0x0001)
Definition at line 43 of file ntobapi.h.
#define SYMBOLIC_LINK_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | 0x1)
Definition at line 64 of file ntobapi.h.
Referenced by CreateSystemRootLink(), IoCreateSymbolicLink(), IoCreateUnprotectedSymbolicLink(), IopReassignSystemRoot(), ObInitSystem(), ObpCreateDosDevicesDirectory(), SeGetLogonIdDeviceMap(), and SepCleanupLUIDDeviceMapDirectory().
#define SYMBOLIC_LINK_QUERY (0x0001)
Definition at line 62 of file ntobapi.h.
Referenced by IoIsValidNameGraftingBuffer(), IopStoreSystemPartitionInformation(), and NtQuerySymbolicLinkObject().
Typedef Documentation
typedef struct _OBJECT_BASIC_INFORMATION OBJECT_BASIC_INFORMATION
typedef struct _OBJECT_DIRECTORY_INFORMATION OBJECT_DIRECTORY_INFORMATION
typedef struct _OBJECT_HANDLE_FLAG_INFORMATION OBJECT_HANDLE_FLAG_INFORMATION
typedef enum _OBJECT_INFORMATION_CLASS OBJECT_INFORMATION_CLASS
typedef struct _OBJECT_NAME_INFORMATION OBJECT_NAME_INFORMATION
typedef struct _OBJECT_TYPE_INFORMATION OBJECT_TYPE_INFORMATION
typedef struct _OBJECT_TYPES_INFORMATION OBJECT_TYPES_INFORMATION
typedef struct _OBJECT_BASIC_INFORMATION * POBJECT_BASIC_INFORMATION
typedef struct _OBJECT_DIRECTORY_INFORMATION * POBJECT_DIRECTORY_INFORMATION
typedef struct _OBJECT_HANDLE_FLAG_INFORMATION * POBJECT_HANDLE_FLAG_INFORMATION
typedef struct _OBJECT_NAME_INFORMATION * POBJECT_NAME_INFORMATION
typedef struct _OBJECT_TYPE_INFORMATION * POBJECT_TYPE_INFORMATION
typedef struct _OBJECT_TYPES_INFORMATION * POBJECT_TYPES_INFORMATION
Enumeration Type Documentation
enum _OBJECT_INFORMATION_CLASS
Enumerator
ObjectBasicInformation
ObjectNameInformation
ObjectTypeInformation
ObjectTypesInformation
ObjectHandleFlagInformation
ObjectSessionInformation
MaxObjectInfoClass
Definition at line 73 of file ntobapi.h.
Function Documentation
NTSYSCALLAPI NTSTATUS NTAPI NtClose (__in HANDLE Handle)
Definition at line 399 of file obclose.c.
References KeGetPreviousMode, and ObpCloseHandle().
Referenced by CmGetSystemDriverList(), CmInitSystem1(), CmpAddAliasEntry(), CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpLinkKeyToHive(), CmpRemoveFromHiveFileList(), CmpSaveBootControlSet(), CmpSetNetworkValue(), CmpSetSystemValues(), CmpSetupConfigurationTree(), CreateSystemRootLink(), ExpInitializeCallbacks(), IopConnectLinkTrackingPort(), IopErrorLogConnectPort(), IopErrorLogThread(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopReferenceDriverObjectByName(), IoSetSystemPartition(), LpcpCreatePort(), MiSectionInitialization(), NtAcceptConnectPort(), NtCreateKey(), NtOpenKey(), NtSecureConnectPort(), ObDuplicateObject(), ObInitSystem(), ObpCreateDosDevicesDirectory(), RtlAdjustPrivilege(), RtlCreateSystemVolumeInformationFolder(), RtlpImpersonateSelfEx(), RtlpSysVolTakeOwnership(), RtlQueryRegistryValues(), SepAdtInitializePrivilegeAuditing(), SepInitializationPhase1(), and SepRmCommandServerThreadInit().
NTSYSCALLAPI NTSTATUS NTAPI NtCreateDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 145 of file obdir.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExInitializePushLock(), Handle, KeGetPreviousMode, KernelMode, _OBJECT_DIRECTORY::Lock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), OBJ_INVALID_SESSION_ID, ObpDirectoryObjectType, ObpValidateIrql, PAGED_CODE, ProbeForWriteHandle, RtlZeroMemory, _OBJECT_DIRECTORY::SessionId, and Status.
Referenced by CreateSystemRootLink(), ExpInitializeCallbacks(), IopCreateRootDirectories(), ObInitSystem(), ObpCreateDosDevicesDirectory(), and SepInitializationPhase1().
NTSYSCALLAPI NTSTATUS NTAPI NtCreateSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __in PUNICODE_STRING LinkTarget)
Definition at line 57 of file oblink.c.
References _UNICODE_STRING::Buffer, _OBJECT_SYMBOLIC_LINK::CreationTime, _OBJECT_SYMBOLIC_LINK::DosDeviceDriveIndex, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Handle, KdPrint, KeGetPreviousMode, KeQuerySystemTime(), KernelMode, _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _OBJECT_SYMBOLIC_LINK::LinkTargetObject, _OBJECT_SYMBOLIC_LINK::LinkTargetRemaining, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObpSymbolicLinkObjectType, PAGED_CODE, PagedPool, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteHandle, RtlCopyMemory, RtlInitUnicodeString(), Status, STATUS_INVALID_PARAMETER, and STATUS_NO_MEMORY.
Referenced by CreateSystemRootLink(), IopReassignSystemRoot(), and ObpCreateDosDevicesDirectory().
NTSYSCALLAPI NTSTATUS NTAPI NtDuplicateObject (__in HANDLE SourceProcessHandle, __in HANDLE SourceHandle, __in_opt HANDLE TargetProcessHandle, __out_opt PHANDLE TargetHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Options)
Definition at line 727 of file obhandle.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObDuplicateObject(), ObReferenceObjectByHandle, ProbeForWriteHandle, PROCESS_DUP_HANDLE, PsProcessType, Status, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtMakePermanentObject (__in HANDLE Handle)
Definition at line 2881 of file obdir.c.
References _OBJECT_HEADER::Flags, KeGetPreviousMode, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpLockObject, ObpUnlockObject, ObReferenceObjectByHandle, PAGED_CODE, SeCreatePermanentPrivilege, SeSinglePrivilegeCheck(), Status, and STATUS_PRIVILEGE_NOT_HELD.
NTSYSCALLAPI NTSTATUS NTAPI NtMakeTemporaryObject (__in HANDLE Handle)
Definition at line 425 of file obclose.c.
References DELETE, _OBJECT_HANDLE_INFORMATION::HandleAttributes, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, ObMakeTemporaryObject(), ObReferenceObjectByHandle, PAGED_CODE, SeDeleteObjectAuditAlarm(), and Status.
Referenced by IopReassignSystemRoot().
NTSYSCALLAPI NTSTATUS NTAPI NtOpenDirectoryObject (__out PHANDLE DirectoryHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 259 of file obdir.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NULL, ObOpenObjectByName(), ObpDirectoryObjectType, ObpValidateIrql, PAGED_CODE, ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenSymbolicLinkObject (__out PHANDLE LinkHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 246 of file oblink.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NULL, ObOpenObjectByName(), ObpSymbolicLinkObjectType, PAGED_CODE, ProbeForWriteHandle, and Status.
Referenced by IopReassignSystemRoot(), and IopStoreSystemPartitionInformation().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDirectoryObject (__in HANDLE DirectoryHandle, __out_bcount_opt(Length) PVOID Buffer, __in ULONG Length, __in BOOLEAN ReturnSingleEntry, __in BOOLEAN RestartScan, __inout PULONG Context, __out_opt PULONG ReturnLength)
Definition at line 343 of file obdir.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _OBJECT_DIRECTORY_ENTRY::ChainLink, DIRECTORY_QUERY, ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _OBJECT_DIRECTORY::HashBuckets, KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_DIRECTORY_INFORMATION::Name, _OBJECT_TYPE::Name, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, NUMBER_HASH_BUCKETS, ObDereferenceObject(), _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpIsOverflow, ObpLockDirectoryShared(), ObpUnlockDirectory(), ObpValidateIrql, ObReferenceObjectByHandle, PAGED_CODE, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, ProbeForWrite(), ProbeForWriteUlong, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_MORE_ENTRIES, STATUS_NO_MORE_ENTRIES, STATUS_SUCCESS, _OBJECT_HEADER::Type, _OBJECT_DIRECTORY_INFORMATION::TypeName, and UNICODE_NULL.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __out_bcount_opt(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength, __out_opt PULONG ReturnLength)
Definition at line 53 of file obquery.c.
References ALIGN_UP, ARGUMENT_PRESENT, ASSERT, _OBJECT_BASIC_INFORMATION::Attributes, _OBJECT_BASIC_INFORMATION::CreationTime, DACL_SECURITY_INFORMATION, _OBJECT_HEADER_NAME_INFO::Directory, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_BASIC_INFORMATION::GrantedAccess, _OBJECT_HANDLE_INFORMATION::GrantedAccess, GROUP_SECURITY_INFORMATION, _OBJECT_HANDLE_INFORMATION::HandleAttributes, _OBJECT_BASIC_INFORMATION::HandleCount, _OBJECT_HEADER::HandleCount, _OBJECT_HANDLE_FLAG_INFORMATION::Inherit, KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_TYPE::Name, _OBJECT_HEADER_NAME_INFO::Name, _OBJECT_BASIC_INFORMATION::NameInfoSize, _OBJECT_BASIC_INFORMATION::NonPagedPoolCharge, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NT_SUCCESS, NULL, _OBJECT_TYPES_INFORMATION::NumberOfTypes, OB_FLAG_EXCLUSIVE_OBJECT, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), ObfReferenceObject(), OBJ_EXCLUSIVE, OBJ_INHERIT, OBJ_NAME_PATH_SEPARATOR, OBJ_PERMANENT, OBJ_PROTECT_CLOSE, OBJECT_HEADER_TO_QUOTA_INFO(), OBJECT_TO_OBJECT_HEADER, ObjectBasicInformation, ObjectHandleFlagInformation, ObjectNameInformation, ObjectTypeInformation, ObjectTypesInformation, OBP_MAX_DEFINED_OBJECT_TYPES, ObpDereferenceNameInfo(), ObpObjectTypes, ObpQueryNameString(), ObpReferenceNameInfo(), ObpSymbolicLinkObjectType, ObQueryTypeInfo(), ObReferenceObjectByHandle, OWNER_SECURITY_INFORMATION, PAGED_CODE, _OBJECT_BASIC_INFORMATION::PagedPoolCharge, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, _OBJECT_BASIC_INFORMATION::PointerCount, _OBJECT_HEADER::PointerCount, _OBJECT_TYPE_INITIALIZER::PoolType, ProbeForWrite(), ProbeForWriteUlong, _OBJECT_HANDLE_FLAG_INFORMATION::ProtectFromClose, QuerySecurityDescriptor, READ_CONTROL, RtlZeroMemory, SACL_SECURITY_INFORMATION, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_BASIC_INFORMATION::SecurityDescriptorSize, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, _OBJECT_BASIC_INFORMATION::TypeInfoSize, _OBJECT_TYPE_INFORMATION::TypeName, and UNICODE_NULL.
Referenced by IopLoadDriver().
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __out_bcount_opt(Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __in ULONG Length, __out PULONG LengthNeeded)
Definition at line 251 of file obse.c.
References except, EXCEPTION_EXECUTE_HANDLER, _OBJECT_TYPE_INITIALIZER::GenericMapping, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, PAGED_CODE, _OBJECT_TYPE_INITIALIZER::PoolType, ProbeForWrite(), ProbeForWriteUlong, QuerySecurityDescriptor, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SeQuerySecurityAccessMask(), Status, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by CmpCloneControlSet(), CmpSaveBootControlSet(), and RtlpSysVolCheckOwnerAndSecurity().
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySymbolicLinkObject (__in HANDLE LinkHandle, __inout PUNICODE_STRING LinkTarget, __out_opt PULONG ReturnedLength)
Definition at line 331 of file oblink.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpLockObject, ObpSymbolicLinkObjectType, ObpUnlockObject, ObReferenceObjectByHandle, PAGED_CODE, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteUlong, ProbeForWriteUshort, RtlCopyMemory, Status, STATUS_BUFFER_TOO_SMALL, and SYMBOLIC_LINK_QUERY.
Referenced by IopReassignSystemRoot(), and IopStoreSystemPartitionInformation().
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __in_bcount(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength)
Definition at line 657 of file obquery.c.
References except, ExSystemExceptionFilter(), KeGetPreviousMode, KernelMode, NT_SUCCESS, ObDereferenceObject(), ObjectHandleFlagInformation, ObjectSessionInformation, ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpLockDirectoryExclusive(), ObpUnlockDirectory(), ObReferenceObjectByHandle, ObSetHandleAttributes(), PAGED_CODE, ProbeForRead, PsGetCurrentProcessSessionId(), SeSinglePrivilegeCheck(), _OBJECT_DIRECTORY::SessionId, SeTcbPrivilege, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and STATUS_PRIVILEGE_NOT_HELD.
NTSYSCALLAPI NTSTATUS NTAPI NtSetSecurityObject (__in HANDLE Handle, __in SECURITY_INFORMATION SecurityInformation, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 44 of file obse.c.
References ARGUMENT_PRESENT, ASSERT, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObSetSecurityObjectByPointer(), _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, PAGED_CODE, PagedPool, SE_SELF_RELATIVE, SeCaptureSecurityDescriptor(), SeReleaseSecurityDescriptor(), SeSetSecurityAccessMask(), Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_SECURITY_DESCR, and TRUE.
Referenced by RtlpSysVolCheckOwnerAndSecurity(), and RtlpSysVolTakeOwnership().
NTSYSCALLAPI NTSTATUS NTAPI NtSignalAndWaitForSingleObject (__in HANDLE SignalHandle, __in HANDLE WaitHandle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 45 of file obwait.c.
References ARGUMENT_PRESENT, _OBJECT_TYPE::DefaultObject, EVENT_INCREMENT, EVENT_MODIFY_STATE, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_HANDLE_INFORMATION::GrantedAccess, KeGetPreviousMode, KeReleaseMutant(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), MUTANT_INCREMENT, NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, ProbeAndReadLargeInteger, SeComputeDeniedAccesses, SEMAPHORE_INCREMENT, SEMAPHORE_MODIFY_STATE, Status, STATUS_ABANDONED, STATUS_ACCESS_DENIED, STATUS_MUTANT_LIMIT_EXCEEDED, STATUS_MUTANT_NOT_OWNED, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SEMAPHORE_LIMIT_EXCEEDED, SYNCHRONIZE, TRUE, _OBJECT_HEADER::Type, and UserRequest.
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForMultipleObjects (__in ULONG Count, __in_ecount(Count) HANDLE Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 422 of file obwait.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, MAXIMUM_WAIT_OBJECTS, ObpWaitForMultipleObjects(), PAGED_CODE, ProbeAndReadLargeInteger, ProbeForRead, RtlCopyMemory, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_3, WaitAll, and WaitAny.
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForMultipleObjects32 (__in ULONG Count, __in_ecount(Count) LONG Handles[], __in WAIT_TYPE WaitType, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 519 of file obwait.c.
References ARGUMENT_PRESENT, Count, except, EXCEPTION_EXECUTE_HANDLER, Index, KeGetPreviousMode, KernelMode, LongToHandle, MAXIMUM_WAIT_OBJECTS, ObpWaitForMultipleObjects(), PAGED_CODE, ProbeAndReadLargeInteger, ProbeForRead, and STATUS_INVALID_PARAMETER_1.
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForSingleObject (__in HANDLE Handle, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 296 of file obwait.c.
References ARGUMENT_PRESENT, _OBJECT_TYPE::DefaultObject, except, EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObReferenceObjectByHandle, PAGED_CODE, PERFINFO_DECLARE_OBJECT, ProbeAndReadLargeInteger, Status, STATUS_MUTANT_LIMIT_EXCEEDED, SYNCHRONIZE, _OBJECT_HEADER::Type, and UserRequest.
Referenced by FsRtlpRegisterProviderWithMUP().