Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/amd64/initamd.c File Reference
initamd.c File Reference
#include "mi.h"
Data Structures
struct _MI_LARGE_VA_RANGES
Macros
#define _x16mb (1024*1024*16)
#define _x16mbnp ((1024*1024*16) >> PAGE_SHIFT)
#define _x1mb (1024*1024)
#define _x1mbnp ((1024*1024) >> PAGE_SHIFT)
#define _x4gb (0x100000000UI64)
#define MI_IS_PTE_VALID(PTE) ((PTE)->u.Hard.Valid == 1)
#define MI_MAX_LARGE_VA_RANGES 3
#define MM_LARGE_PAGE_MINIMUM ((255*1024*1024) >> PAGE_SHIFT)
#define MM_PFN_MAPPED_BY_PDE (MM_VA_MAPPED_BY_PDE >> PAGE_SHIFT)
Typedefs
typedef struct _MI_LARGE_VA_RANGES MI_LARGE_VA_RANGES
typedef struct _MI_LARGE_VA_RANGES * PMI_LARGE_VA_RANGES
Functions
VOID MiComputeInitialLargePage (VOID)
PMEMORY_ALLOCATION_DESCRIPTOR MiFindDescriptor (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
DECLSPEC_NOINLINE VOID MiGetStackPointer (OUT PULONG_PTR StackPointer)
VOID MiInitMachineDependent (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
LOGICAL MiIsRegularMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
VOID MiReportPhysicalMemory (VOID)
VOID MxConvertToLargePage (IN PVOID VirtualAddress, IN PVOID EndVirtualAddress)
PFN_NUMBER MxGetNextPage (IN PFN_NUMBER PagesNeeded, IN LOGICAL UseSlush)
PFN_NUMBER MxPagesAvailable (VOID)
VOID MxPopulatePageDirectories (IN PMMPTE StartPde, IN PMMPTE EndPde)
Variables
PFN_NUMBER MiInitialLargePage
PFN_NUMBER MiInitialLargePageSize
ULONG MiLargeVaRangeIndex
MI_LARGE_VA_RANGES MiLargeVaRanges [MI_MAX_LARGE_VA_RANGES]
PFN_NUMBER MiSlushDescriptorBase
PFN_NUMBER MiSlushDescriptorCount
PMEMORY_ALLOCATION_DESCRIPTOR MxFreeDescriptor
ULONG MxMapLargePages = 1
MEMORY_ALLOCATION_DESCRIPTOR MxOldFreeDescriptor
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor1
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor2
PFN_NUMBER MxPfnAllocation
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor1
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor2
PFN_NUMBER MxTotalFreePages
Macro Definition Documentation
#define _x16mb (1024*1024*16)
Definition at line 79 of file initamd.c.
#define _x16mbnp ((1024*1024*16) >> PAGE_SHIFT)
Definition at line 80 of file initamd.c.
Referenced by MiComputeInitialLargePage().
#define _x1mb (1024*1024)
Definition at line 77 of file initamd.c.
#define _x1mbnp ((1024*1024) >> PAGE_SHIFT)
Definition at line 78 of file initamd.c.
Referenced by MiComputeInitialLargePage().
#define _x4gb (0x100000000UI64)
Definition at line 81 of file initamd.c.
Referenced by MiInitMachineDependent().
#define MI_IS_PTE_VALID (PTE) ((PTE)->u.Hard.Valid == 1)
Definition at line 83 of file initamd.c.
Referenced by MiInitMachineDependent().
#define MI_MAX_LARGE_VA_RANGES 3
Definition at line 122 of file initamd.c.
#define MM_LARGE_PAGE_MINIMUM ((255*1024*1024) >> PAGE_SHIFT)
Definition at line 75 of file initamd.c.
Referenced by MiInitMachineDependent().
#define MM_PFN_MAPPED_BY_PDE (MM_VA_MAPPED_BY_PDE >> PAGE_SHIFT)
Definition at line 127 of file initamd.c.
Referenced by MiFindDescriptor(), MiInitMachineDependent(), MiReportPhysicalMemory(), and MxConvertToLargePage().
Typedef Documentation
typedef struct _MI_LARGE_VA_RANGES MI_LARGE_VA_RANGES
typedef struct _MI_LARGE_VA_RANGES * PMI_LARGE_VA_RANGES
Function Documentation
VOID MiComputeInitialLargePage (VOID)
Definition at line 724 of file initamd.c.
References _x16mbnp, _x1mbnp, ASSERT, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, BYTE_OFFSET, FALSE, InitializeSListHead(), INSTALL_MORE_MEMORY, KeBugCheckEx(), KeGetCurrentPrcb(), KeGetPcr(), KeNodeBlock, KeNumberNodes, MI_ROUND_TO_SIZE, MiAddCachedRange(), MiInitialLargePage, MiInitialLargePageSize, MiSlushDescriptorBase, MiSlushDescriptorCount, MM_MAX_ADDITIONAL_NONPAGED_POOL, MM_MAX_INITIAL_NONPAGED_POOL, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_SECONDARY_COLORS_DEFAULT, MM_SECONDARY_COLORS_MAX, MM_SECONDARY_COLORS_MIN, MmDefaultMaximumNonPagedPool, MmHighestPossiblePhysicalPage, MmMaxAdditionNonPagedPoolPerMb, MmMaximumNonPagedPoolInBytes, MmMaximumNonPagedPoolInPages, MmMaximumNonPagedPoolPercent, MmMinAdditionNonPagedPoolPerMb, MmMinimumNonPagedPoolSize, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmPfnDatabase, MmProtectFreedNonPagedPool, MmSecondaryColorMask, MmSecondaryColorNodeShift, MmSecondaryColors, MmSizeOfNonPagedPoolInBytes, MxMapLargePages, MxPfnAllocation, MxTotalFreePages, NumberOfBytes, PAGE_SHIFT, PAGE_SIZE, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _KPRCB::SecondaryColorMask, _KPCR::SecondLevelCacheAssociativity, and _KPCR::SecondLevelCacheSize.
Referenced by MiInitMachineDependent().
PMEMORY_ALLOCATION_DESCRIPTOR MiFindDescriptor (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
Definition at line 1086 of file initamd.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, CONTAINING_RECORD, _LIST_ENTRY::Flink, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderFirmwareTemporary, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MM_PFN_MAPPED_BY_PDE, NULL, and _MEMORY_ALLOCATION_DESCRIPTOR::PageCount.
Referenced by MiInitMachineDependent().
DECLSPEC_NOINLINE VOID MiGetStackPointer (OUT PULONG_PTR StackPointer)
Definition at line 2992 of file initamd.c.
Referenced by MiInsertPageInFreeList().
VOID MiInitMachineDependent (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 1131 of file initamd.c.
Referenced by MmInitSystem().
LOGICAL MiIsRegularMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
Definition at line 375 of file initamd.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderBBTMemory, LoaderFirmwarePermanent, LoaderSpecialMemory, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MiSlushDescriptorBase, MiSlushDescriptorCount, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, and TRUE.
Referenced by MiInitMachineDependent().
VOID MiReportPhysicalMemory (VOID)
Definition at line 483 of file initamd.c.
Referenced by MmInitSystem().
VOID MxConvertToLargePage (IN PVOID VirtualAddress, IN PVOID EndVirtualAddress)
Definition at line 242 of file initamd.c.
References ASSERT, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE_HARDWARE::Global, _MMPTE::Hard, _MMPTE_HARDWARE::LargePage, LOCK_PFN, _MMPTE::Long, MI_FLUSH_ENTIRE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_VALID_PTE_NEW_PAGE, MiAddExpansionNonPagedPool(), MiDecrementReferenceCount(), MiGetPdeAddress, MiGetVirtualAddressMappedByPte, MM_PFN_MAPPED_BY_PDE, MxMapLargePages, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PTE_PER_PAGE, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and ValidKernelPde.
Referenced by MiInitMachineDependent().
PFN_NUMBER MxGetNextPage (IN PFN_NUMBER PagesNeeded, IN LOGICAL UseSlush)
Definition at line 131 of file initamd.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, INSTALL_MORE_MEMORY, KeBugCheckEx(), MmNumberOfPhysicalPages, NULL, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, and TRUE.
Referenced by MiInitMachineDependent(), and MxPopulatePageDirectories().
PFN_NUMBER MxPagesAvailable (VOID)
Definition at line 212 of file initamd.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::PageCount.
VOID MxPopulatePageDirectories (IN PMMPTE StartPde, IN PMMPTE EndPde)
Definition at line 636 of file initamd.c.
References FALSE, _MMPTE::Hard, MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MxGetNextPage(), PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, RtlZeroMemory, TRUE, _MMPTE::u, _MMPTE_HARDWARE::Valid, and ValidKernelPte.
Referenced by MiInitMachineDependent().
Variable Documentation
PFN_NUMBER MiInitialLargePage
Definition at line 89 of file initamd.c.
Referenced by MiComputeInitialLargePage(), and MiInitMachineDependent().
PFN_NUMBER MiInitialLargePageSize
Definition at line 90 of file initamd.c.
Referenced by MiComputeInitialLargePage(), and MiInitMachineDependent().
ULONG MiLargeVaRangeIndex
Definition at line 124 of file initamd.c.
Referenced by MiInitMachineDependent(), and MiReportPhysicalMemory().
MI_LARGE_VA_RANGES MiLargeVaRanges[MI_MAX_LARGE_VA_RANGES]
Definition at line 125 of file initamd.c.
PFN_NUMBER MiSlushDescriptorBase
Definition at line 95 of file initamd.c.
Referenced by MiComputeInitialLargePage(), MiInitMachineDependent(), and MiIsRegularMemory().
PFN_NUMBER MiSlushDescriptorCount
Definition at line 96 of file initamd.c.
Referenced by MiComputeInitialLargePage(), MiInitMachineDependent(), and MiIsRegularMemory().
PMEMORY_ALLOCATION_DESCRIPTOR MxFreeDescriptor
Definition at line 98 of file initamd.c.
ULONG MxMapLargePages = 1
Definition at line 120 of file initamd.c.
Referenced by MiComputeInitialLargePage(), MiInitMachineDependent(), MiReportPhysicalMemory(), and MxConvertToLargePage().
MEMORY_ALLOCATION_DESCRIPTOR MxOldFreeDescriptor
Definition at line 99 of file initamd.c.
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor1
Definition at line 102 of file initamd.c.
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor2
Definition at line 105 of file initamd.c.
PFN_NUMBER MxPfnAllocation
Definition at line 92 of file initamd.c.
Referenced by MiComputeInitialLargePage(), and MiInitMachineDependent().
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor1
Definition at line 101 of file initamd.c.
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor2
Definition at line 104 of file initamd.c.
PFN_NUMBER MxTotalFreePages
Definition at line 93 of file initamd.c.
Referenced by MiComputeInitialLargePage(), and MiInitMachineDependent().