Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/readwrt.c File Reference
readwrt.c File Reference
#include "mi.h"
Macros
#define COPY_STACK_SIZE 64
#define MAX_LOCK_SIZE ((ULONG)(14 * PAGE_SIZE))
#define MAX_MOVE_SIZE (LONG)0x10000
#define MINIMUM_ALLOCATION (LONG)128
#define POOL_MOVE_THRESHOLD 511
Functions
NTSTATUS MiDoMappedCopy (IN PEPROCESS FromProcess, IN CONST VOID *FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesRead)
NTSTATUS MiDoPoolCopy (IN PEPROCESS FromProcess, IN CONST VOID *FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesRead)
ULONG MiGetExceptionInfo (IN PEXCEPTION_POINTERS ExceptionPointers, IN PLOGICAL ExceptionAddressConfirmed, IN PULONG_PTR BadVa)
ULONG MiGetExceptionInfo (IN PEXCEPTION_POINTERS ExceptionPointers, IN OUT PLOGICAL ExceptionAddressConfirmed, IN OUT PULONG_PTR BadVa)
NTSTATUS MmCopyVirtualMemory (IN PEPROCESS FromProcess, IN CONST VOID *FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesCopied)
NTSTATUS NtReadVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
NTSTATUS NtWriteVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in_bcount(BufferSize) CONST VOID *Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Macro Definition Documentation
#define COPY_STACK_SIZE 64
Definition at line 89 of file readwrt.c.
Referenced by MiDoPoolCopy().
#define MAX_LOCK_SIZE ((ULONG)(14 * PAGE_SIZE))
Definition at line 27 of file readwrt.c.
Referenced by MiDoMappedCopy().
#define MAX_MOVE_SIZE (LONG)0x10000
Definition at line 33 of file readwrt.c.
Referenced by MiDoPoolCopy().
#define MINIMUM_ALLOCATION (LONG)128
Definition at line 39 of file readwrt.c.
#define POOL_MOVE_THRESHOLD 511
Definition at line 45 of file readwrt.c.
Referenced by MmCopyVirtualMemory().
Function Documentation
NTSTATUS MiDoMappedCopy (IN PEPROCESS FromProcess, IN CONST VOID * FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesRead)
Definition at line 518 of file readwrt.c.
References ASSERT, CONST, except, ExRaiseStatus(), FALSE, HighPagePriority, IoReadAccess, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), MAX_LOCK_SIZE, MiGetExceptionInfo(), MmCached, MmInitializeMdl, MmMapLockedPagesSpecifyCache(), MmProbeAndLockPages(), MmUnlockPages(), MmUnmapLockedPages(), NULL, PAGE_SHIFT, PAGED_CODE, ProbeForRead, ProbeForWrite(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_PARTIAL_COPY, STATUS_SUCCESS, STATUS_WORKING_SET_QUOTA, TRUE, and VOID.
Referenced by MmCopyVirtualMemory().
NTSTATUS MiDoPoolCopy (IN PEPROCESS FromProcess, IN CONST VOID * FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesRead)
Definition at line 751 of file readwrt.c.
References ASSERT, CONST, COPY_STACK_SIZE, ExAllocatePoolWithTag, except, ExFreePool(), FALSE, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), MAX_MOVE_SIZE, MiGetExceptionInfo(), NonPagedPool, NULL, PAGED_CODE, ProbeForRead, ProbeForWrite(), PsGetCurrentProcess(), RtlCopyMemory, STATUS_PARTIAL_COPY, STATUS_SUCCESS, TRUE, and VOID.
Referenced by MmCopyVirtualMemory().
ULONG MiGetExceptionInfo (IN PEXCEPTION_POINTERS ExceptionPointers, IN PLOGICAL ExceptionAddressConfirmed, IN PULONG_PTR BadVa)
Referenced by MiDoMappedCopy(), and MiDoPoolCopy().
ULONG MiGetExceptionInfo (IN PEXCEPTION_POINTERS ExceptionPointers, IN OUT PLOGICAL ExceptionAddressConfirmed, IN OUT PULONG_PTR BadVa)
Definition at line 451 of file readwrt.c.
References EXCEPTION_EXECUTE_HANDLER, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionInformation, _EXCEPTION_RECORD::ExceptionRecord, FALSE, _EXCEPTION_RECORD::NumberParameters, PAGED_CODE, STATUS_ACCESS_VIOLATION, STATUS_GUARD_PAGE_VIOLATION, STATUS_IN_PAGE_ERROR, and TRUE.
NTSTATUS MmCopyVirtualMemory (IN PEPROCESS FromProcess, IN CONST VOID * FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesCopied)
Definition at line 361 of file readwrt.c.
References ASSERT, ExAcquireRundownProtection(), ExReleaseRundownProtection(), FALSE, MiDoMappedCopy(), MiDoPoolCopy(), POOL_MOVE_THRESHOLD, PsGetCurrentProcess(), _EPROCESS::RundownProtect, Status, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, and STATUS_WORKING_SET_QUOTA.
Referenced by IoRaiseHardError(), LpcpCopyRequestData(), NtReadVirtualMemory(), NtWriteVirtualMemory(), and PspCreateProcess().
NTSTATUS NtReadVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
Definition at line 92 of file readwrt.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousModeByThread, KernelMode, MM_HIGHEST_USER_ADDRESS, MmCopyVirtualMemory(), NOTHING, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong_ptr, PROCESS_VM_READ, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, Status, STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by RtlFreeUserThreadStack().
NTSTATUS NtWriteVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in_bcount(BufferSize) CONST VOID * Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Definition at line 226 of file readwrt.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousModeByThread, KernelMode, MM_HIGHEST_USER_ADDRESS, MmCopyVirtualMemory(), NOTHING, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong_ptr, PROCESS_VM_WRITE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, Status, STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by RtlRemoteCall().