Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/pinsup.c File Reference
pinsup.c File Reference
#include "cc.h"
Macros
#define me 0x00000008
Functions
POBCB CcAllocateObcb (IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN PBCB FirstBcb)
BOOLEAN CcMapData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID *Bcb, __deref_out_bcount(Length) PVOID *Buffer)
BOOLEAN CcMapDataCommon (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG Flags, OUT PVOID *Bcb, OUT PVOID *Buffer)
VOID CcMapDataForOverwrite (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, OUT PVOID *Bcb, OUT PVOID *Buffer)
BOOLEAN CcPinMappedData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __inout PVOID *Bcb)
BOOLEAN CcPinRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID *Bcb, __deref_out_bcount(Length) PVOID *Buffer)
BOOLEAN CcPreparePinWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Zero, __in ULONG Flags, __out PVOID *Bcb, __deref_out_bcount(Length) PVOID *Buffer)
VOID CcSetBcbOwnerPointer (__in PVOID Bcb, __in PVOID OwnerPointer)
VOID CcUnpinData (__in PVOID Bcb)
VOID CcUnpinDataForThread (__in PVOID Bcb, __in ERESOURCE_THREAD ResourceThreadId)
Macro Definition Documentation
#define me 0x00000008
Definition at line 26 of file pinsup.c.
Referenced by CcMapData(), CcMapDataCommon(), CcMapDataForOverwrite(), CcPinMappedData(), CcPinRead(), CcPreparePinWrite(), CcUnpinData(), and CcUnpinDataForThread().
Function Documentation
POBCB CcAllocateObcb (IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN PBCB FirstBcb)
Definition at line 1498 of file pinsup.c.
References _OBCB::Bcbs, _BCB::ByteLength, _OBCB::ByteLength, CACHE_NTC_OBCB, ExAllocatePoolWithTag, ExRaiseStatus(), FIELD_OFFSET, FileOffset, _BCB::FileOffset, _OBCB::FileOffset, _LARGE_INTEGER::LowPart, _OBCB::NodeByteSize, _OBCB::NodeTypeCode, NonPagedPool, NULL, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlZeroMemory, and STATUS_INSUFFICIENT_RESOURCES.
Referenced by CcPinMappedData(), CcPinRead(), and CcPreparePinWrite().
BOOLEAN CcMapData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID * Bcb, __deref_out_bcount(Length) PVOID * Buffer)
Definition at line 73 of file pinsup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, CcMapDataCommon(), CcMissCounter, CcThrowAway, CcUnpinFileData, DebugTrace, FALSE, FlagOn, MAP_NO_READ, me, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, NULL, PAGE_SIZE, PsGetCurrentThread(), TRUE, ULongToPtr, and UNPIN.
Referenced by CmpMapCmView(), and CmpUnPinCmView().
BOOLEAN CcMapDataCommon (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG Flags, OUT PVOID * Bcb, OUT PVOID * Buffer)
Definition at line 242 of file pinsup.c.
References ASSERT, CcGetVirtualAddress(), CcMapDataNoWait, CcMapDataNoWaitMiss, CcMapDataWait, CcMapDataWaitMiss, CcMissCounter, CcPinFileData(), DebugTrace, FALSE, FlagOn, MAP_WAIT, me, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, and TRUE.
Referenced by CcMapData(), and CcMapDataForOverwrite().
VOID CcMapDataForOverwrite (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, OUT PVOID * Bcb, OUT PVOID * Buffer)
Definition at line 1101 of file pinsup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERTMSG, CALLER_TRACKS_DIRTY_DATA, CcAcquireMasterLock, CcMapDataCommon(), CcMissCounter, CcReleaseMasterLock, CcThrowAway, CcUnpinFileData, DebugTrace, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, MAP_WAIT, me, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, NULL, PAGE_SIZE, PsGetCurrentThread(), SetFlag, TRUE, ULongToPtr, and UNPIN.
Referenced by CcPreparePinWrite().
BOOLEAN CcPinMappedData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __inout PVOID * Bcb)
Definition at line 408 of file pinsup.c.
References BooleanFlagOn, CACHE_NTC_BCB, CcAllocateObcb(), CcFreeVirtualAddress(), CcPinFileData(), CcPinMappedDataCount, CcUnpinData(), DebugTrace, ExAcquireSharedStarveExclusive(), FALSE, FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, me, MODIFIED_WRITE_DISABLED, NOTHING, NULL, PIN_WAIT, _LARGE_INTEGER::QuadPart, TRUE, and try_return.
Referenced by CmpPinCmView().
BOOLEAN CcPinRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID * Bcb, __deref_out_bcount(Length) PVOID * Buffer)
Definition at line 640 of file pinsup.c.
References CcAllocateObcb(), CcMissCounter, CcPinFileData(), CcPinReadNoWait, CcPinReadNoWaitMiss, CcPinReadWait, CcPinReadWaitMiss, CcThrowAway, CcUnpinData(), DebugTrace, FALSE, FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, me, MODIFIED_WRITE_DISABLED, NOTHING, NULL, PIN_WAIT, _LARGE_INTEGER::QuadPart, TRUE, and try_return.
Referenced by CmpFileWriteThroughCache().
BOOLEAN CcPreparePinWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Zero, __in ULONG Flags, __out PVOID * Bcb, __deref_out_bcount(Length) PVOID * Buffer)
Definition at line 859 of file pinsup.c.
References CcAllocateObcb(), CcMapDataForOverwrite(), CcMissCounter, CcPinFileData(), CcSetDirtyPinnedData(), CcThrowAway, CcUnpinData(), DebugTrace, FALSE, FileOffset, FlagOn, me, NOTHING, NULL, PIN_CALLER_TRACKS_DIRTY_DATA, _LARGE_INTEGER::QuadPart, RtlZeroMemory, TRUE, and try_return.
VOID CcSetBcbOwnerPointer (__in PVOID Bcb, __in PVOID OwnerPointer)
Definition at line 1346 of file pinsup.c.
References ASSERT, CACHE_NTC_OBCB, ExSetResourceOwnerPointer(), and NULL.
VOID CcUnpinData (__in PVOID Bcb)
Definition at line 1268 of file pinsup.c.
References CACHE_NTC_OBCB, CcUnpinData(), CcUnpinFileData, DebugTrace, ExFreePool(), FALSE, me, NULL, TRUE, and UNPIN.
Referenced by CcPinMappedData(), CcPinRead(), CcPreparePinWrite(), CcUnpinData(), CmpFileWriteThroughCache(), CmpUnmapCmView(), and CmpUnPinCmView().
VOID CcUnpinDataForThread (__in PVOID Bcb, __in ERESOURCE_THREAD ResourceThreadId)
Definition at line 1410 of file pinsup.c.
References CACHE_NTC_OBCB, CcUnpinDataForThread(), CcUnpinFileData, DebugTrace, ExFreePool(), ExReleaseResourceForThreadLite(), me, NULL, TRUE, and UNPIN.
Referenced by CcUnpinDataForThread().