Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/sysvol.c File Reference
sysvol.c File Reference
#include "ntrtlp.h"
Functions
NTSTATUS RtlCreateSystemVolumeInformationFolder (IN PUNICODE_STRING VolumeRootPath)
VOID RtlpSysVolAdminSid (IN OUT SID *Sid)
PVOID RtlpSysVolAllocate (IN ULONG Size)
NTSTATUS RtlpSysVolCheckOwnerAndSecurity (IN HANDLE Handle, IN PACL StandardAcl)
NTSTATUS RtlpSysVolCreateSecurityDescriptor (OUT PSECURITY_DESCRIPTOR *SecurityDescriptor, OUT PACL *Acl)
VOID RtlpSysVolFree (IN PVOID Buffer)
VOID RtlpSysVolSystemSid (IN OUT SID *Sid)
VOID RtlpSysVolTakeOwnership (IN PUNICODE_STRING DirectoryName)
Variables
static const SID_IDENTIFIER_AUTHORITY ntAuthority = SECURITY_NT_AUTHORITY
Function Documentation
NTSTATUS RtlCreateSystemVolumeInformationFolder (IN PUNICODE_STRING VolumeRootPath)
Definition at line 441 of file sysvol.c.
References _UNICODE_STRING::Buffer, FALSE, FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_SYSTEM, FILE_DIRECTORY_FILE, FILE_OPEN_IF, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, InitializeObjectAttributes, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NtCreateFile(), NULL, OBJ_CASE_INSENSITIVE, READ_CONTROL, RTL_SYSTEM_VOLUME_INFORMATION_FOLDER, RtlCopyMemory, RtlInitUnicodeString(), RtlpSysVolAllocate(), RtlpSysVolCheckOwnerAndSecurity(), RtlpSysVolCreateSecurityDescriptor(), RtlpSysVolFree(), RtlpSysVolTakeOwnership(), STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, SYNCHRONIZE, TRUE, WRITE_DAC, and WRITE_OWNER.
VOID RtlpSysVolAdminSid (IN OUT SID * Sid)
Definition at line 83 of file sysvol.c.
References DOMAIN_ALIAS_RID_ADMINS, ntAuthority, SECURITY_BUILTIN_DOMAIN_RID, and SID_REVISION.
Referenced by RtlpSysVolCheckOwnerAndSecurity(), and RtlpSysVolTakeOwnership().
PVOID RtlpSysVolAllocate (IN ULONG Size)
Definition at line 61 of file sysvol.c.
References ExAllocatePoolWithTag, and PagedPool.
Referenced by RtlCreateSystemVolumeInformationFolder(), RtlpSysVolCheckOwnerAndSecurity(), and RtlpSysVolCreateSecurityDescriptor().
NTSTATUS RtlpSysVolCheckOwnerAndSecurity (IN HANDLE Handle, IN PACL StandardAcl)
Definition at line 175 of file sysvol.c.
References ACCESS_ALLOWED_ACE_TYPE, _ACE_HEADER::AceFlags, _ACE_HEADER::AceType, CONTAINER_INHERIT_ACE, DACL_SECURITY_INFORMATION, FALSE, _ACCESS_ALLOWED_ACE::Header, NT_SUCCESS, NtQuerySecurityObject(), NtSetSecurityObject(), NULL, OBJECT_INHERIT_ACE, OWNER_SECURITY_INFORMATION, RtlCopyMemory, RtlEqualSid(), RtlGetAce(), RtlGetDaclSecurityDescriptor(), RtlGetOwnerSecurityDescriptor(), RtlMakeSelfRelativeSD(), RtlpSysVolAdminSid(), RtlpSysVolAllocate(), RtlpSysVolFree(), RtlpSysVolSystemSid(), RtlSelfRelativeToAbsoluteSD2(), RtlSetDaclSecurityDescriptor(), RtlSetOwnerSecurityDescriptor(), _ACCESS_ALLOWED_ACE::SidStart, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by RtlCreateSystemVolumeInformationFolder().
NTSTATUS RtlpSysVolCreateSecurityDescriptor (OUT PSECURITY_DESCRIPTOR * SecurityDescriptor, OUT PACL * Acl)
Definition at line 108 of file sysvol.c.
References ACL_REVISION, CONTAINER_INHERIT_ACE, FALSE, NT_SUCCESS, OBJECT_INHERIT_ACE, RtlAddAccessAllowedAceEx(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlLengthSid(), RtlpSysVolAllocate(), RtlpSysVolFree(), RtlpSysVolSystemSid(), RtlSetDaclSecurityDescriptor(), SECURITY_DESCRIPTOR_REVISION, SPECIFIC_RIGHTS_ALL, STANDARD_RIGHTS_ALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by RtlCreateSystemVolumeInformationFolder().
VOID RtlpSysVolFree (IN PVOID Buffer)
Definition at line 74 of file sysvol.c.
References ExFreePool().
Referenced by RtlCreateSystemVolumeInformationFolder(), RtlpSysVolCheckOwnerAndSecurity(), and RtlpSysVolCreateSecurityDescriptor().
VOID RtlpSysVolSystemSid (IN OUT SID * Sid)
Definition at line 96 of file sysvol.c.
References ntAuthority, SECURITY_LOCAL_SYSTEM_RID, and SID_REVISION.
Referenced by RtlpSysVolCheckOwnerAndSecurity(), and RtlpSysVolCreateSecurityDescriptor().
VOID RtlpSysVolTakeOwnership (IN PUNICODE_STRING DirectoryName)
Definition at line 358 of file sysvol.c.
References _LUID_AND_ATTRIBUTES::Attributes, FALSE, FILE_DIRECTORY_FILE, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, InitializeObjectAttributes, _LUID_AND_ATTRIBUTES::Luid, NT_SUCCESS, NtAdjustPrivilegesToken(), NtClose(), NtCurrentProcess, NtOpenFile(), NtOpenProcessToken(), NtSetSecurityObject(), NULL, OBJ_CASE_INSENSITIVE, OWNER_SECURITY_INFORMATION, _TOKEN_PRIVILEGES::PrivilegeCount, _TOKEN_PRIVILEGES::Privileges, RtlConvertLongToLuid(), RtlCreateSecurityDescriptor(), RtlpSysVolAdminSid(), RtlSetOwnerSecurityDescriptor(), SE_PRIVILEGE_ENABLED, SE_TAKE_OWNERSHIP_PRIVILEGE, SECURITY_DESCRIPTOR_REVISION, SYNCHRONIZE, TOKEN_ADJUST_PRIVILEGES, TOKEN_QUERY, and WRITE_OWNER.
Referenced by RtlCreateSystemVolumeInformationFolder().
Variable Documentation
const SID_IDENTIFIER_AUTHORITY ntAuthority = SECURITY_NT_AUTHORITY static
Definition at line 49 of file sysvol.c.
Referenced by RtlpSysVolAdminSid(), and RtlpSysVolSystemSid().