Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/wslist.c File Reference
wslist.c File Reference
#include "mi.h"
Macros
#define MI_ALLOCATED_PAGE_DIRECTORY 0x2
#define MI_ALLOCATED_PAGE_TABLE 0x1
#define MI_INITIALIZE_SESSION_WSLE(_VirtualAddress, _WslEntry)
#define MI_INITIALIZE_WSLE(_VirtualAddress, _WslEntry)
#define MM_RETRY_COUNT 2
Typedefs
typedef enum _WSLE_ALLOCATION_TYPE * PWSLE_ALLOCATION_TYPE
typedef enum _WSLE_ALLOCATION_TYPE WSLE_ALLOCATION_TYPE
Enumerations
enum _WSLE_ALLOCATION_TYPE { WsleAllocationAny = 0, WsleAllocationReplace = 1, WsleAllocationDontTrim = 2 }
Functions
ULONG MiAddWorkingSetPage (IN PMMSUPPORT WsInfo)
LOGICAL MiAddWsleHash (IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte)
WSLE_NUMBER MiAllocateWsle (IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN ULONG_PTR WsleMask)
VOID MiCheckNullIndex (IN PMMWSL WorkingSetList)
VOID MiCheckWsleHash (IN PMMWSL WorkingSetList)
VOID MiDoReplacement (IN PMMSUPPORT WsInfo, IN WSLE_ALLOCATION_TYPE Flags)
LOGICAL MiEliminateWorkingSetEntry (IN WSLE_NUMBER WorkingSetIndex, IN PMMPTE PointerPte, IN PMMPFN Pfn, IN PMMSUPPORT WsInfo, IN LOGICAL Force)
NTSTATUS MiEmptyWorkingSet (IN PMMSUPPORT WsInfo, IN LOGICAL NeedLock)
ULONG MiFreeWsle (IN WSLE_NUMBER WorkingSetIndex, IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte)
WSLE_NUMBER MiFreeWsleList (IN PMMSUPPORT WsInfo, IN PMMWSLE_FLUSH_LIST WsleFlushList)
VOID MiGrowWsleHash (IN PMMSUPPORT WsInfo)
VOID MiInitializeSessionWsSupport (VOID)
VOID MiInitializeWorkingSetList (IN PEPROCESS CurrentProcess)
VOID MiReleaseWsle (IN WSLE_NUMBER WorkingSetIndex, IN PMMSUPPORT WsInfo)
ULONG MiRemovePageFromWorkingSet (IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN PMMSUPPORT WsInfo)
VOID MiRemoveWorkingSetPages (IN PMMSUPPORT WsInfo)
VOID MiReplaceWorkingSetEntry (IN PMMSUPPORT WsInfo, IN WSLE_ALLOCATION_TYPE Flags)
NTSTATUS MiSessionInitializeWorkingSetList (VOID)
WSLE_NUMBER MiTrimWorkingSet (IN WSLE_NUMBER Reduction, IN PMMSUPPORT WsInfo, IN ULONG TrimAge)
VOID MiUpdateWsle (IN OUT PWSLE_NUMBER DesiredIndex, IN PVOID VirtualAddress, IN PMMSUPPORT WsInfo, IN PMMPFN Pfn, IN ULONG_PTR WsleMask)
NTSTATUS MmAdjustWorkingSetSize (__in SIZE_T WorkingSetMinimumInBytes, __in SIZE_T WorkingSetMaximumInBytes, __in ULONG SystemCache, __in BOOLEAN IncreaseOkay)
NTSTATUS MmAdjustWorkingSetSizeEx (IN SIZE_T WorkingSetMinimumInBytes, IN SIZE_T WorkingSetMaximumInBytes, IN ULONG SystemCache, IN BOOLEAN IncreaseOkay, IN ULONG Flags, OUT PBOOLEAN IncreaseRequested)
LOGICAL MmAssignProcessToJob (IN PEPROCESS Process)
NTSTATUS MmEnforceWorkingSetLimit (IN PEPROCESS Process, IN ULONG Flags)
VOID MmQuerySystemCacheWorkingSetInformation (OUT PSYSTEM_FILECACHE_INFORMATION Info)
NTSTATUS MmQueryWorkingSetInformation (IN PSIZE_T PeakWorkingSetSize, IN PSIZE_T WorkingSetSize, IN PSIZE_T MinimumWorkingSetSize, IN PSIZE_T MaximumWorkingSetSize, IN PULONG HardEnforcementFlags)
Variables
LOGICAL MiReplacing
LOGICAL MiTrimRemovalPagesOnly
ULONG MiWsleFailures
WSLE_NUMBER MmMaximumWorkingSetSize
ULONG MmPagedPoolPage
ULONG MmStandbyRePurposed
ULONG MmSystemCachePage
ULONG MmSystemCodePage
ULONG MmSystemDriverPage
PFN_NUMBER MmTransitionSharedPages
PFN_NUMBER MmTransitionSharedPagesPeak
Macro Definition Documentation
#define MI_ALLOCATED_PAGE_DIRECTORY 0x2
Definition at line 2646 of file wslist.c.
Referenced by MiAddWorkingSetPage().
#define MI_ALLOCATED_PAGE_TABLE 0x1
Definition at line 2645 of file wslist.c.
Referenced by MiAddWorkingSetPage().
#define MI_INITIALIZE_SESSION_WSLE (_VirtualAddress, _WslEntry)
Value:
{   \
    PMMPFN _Pfn1;                                                   \
    _WslEntry->u1.VirtualAddress = (PVOID)(_VirtualAddress);        \
    _WslEntry->u1.e1.Valid = 1;                                     \
    _WslEntry->u1.e1.LockedInWs = 1;                                \
    _WslEntry->u1.e1.Direct = 1;                                    \
    _Pfn1 = MI_PFN_ELEMENT (MiGetPteAddress ((PVOID)(_VirtualAddress))->u.Hard.PageFrameNumber); \
    ASSERT (_Pfn1->u1.WsIndex == 0);                                \
    _Pfn1->u1.WsIndex = (WSLE_NUMBER)(_WslEntry - MmSessionSpace->Wsle); \
    (_WslEntry) += 1;                                               \
}
Referenced by MiSessionInitializeWorkingSetList().
#define MI_INITIALIZE_WSLE (_VirtualAddress, _WslEntry)
Value:
{           \
    PMMPFN _Pfn1;                                                   \
    _WslEntry->u1.VirtualAddress = (PVOID)(_VirtualAddress);        \
    _WslEntry->u1.e1.Valid = 1;                                     \
    _WslEntry->u1.e1.LockedInWs = 1;                                \
    _WslEntry->u1.e1.Direct = 1;                                    \
    _Pfn1 = MI_PFN_ELEMENT (MiGetPteAddress ((PVOID)(_VirtualAddress))->u.Hard.PageFrameNumber); \
    ASSERT (_Pfn1->u1.WsIndex == 0);                                \
    _Pfn1->u1.WsIndex = (WSLE_NUMBER)(_WslEntry - MmWsle);          \
    (_WslEntry) += 1;                                               \
}
Definition at line 1379 of file wslist.c.
Referenced by MiInitializeWorkingSetList().
#define MM_RETRY_COUNT 2
Definition at line 32 of file wslist.c.
Typedef Documentation
typedef enum _WSLE_ALLOCATION_TYPE * PWSLE_ALLOCATION_TYPE
typedef enum _WSLE_ALLOCATION_TYPE WSLE_ALLOCATION_TYPE
Enumeration Type Documentation
enum _WSLE_ALLOCATION_TYPE
Enumerator
WsleAllocationAny
WsleAllocationReplace
WsleAllocationDontTrim
Definition at line 39 of file wslist.c.
Function Documentation
ULONG MiAddWorkingSetPage (IN PMMSUPPORT WsInfo)
Definition at line 2650 of file wslist.c.
References _MI_PAGING_LEVELS, ASSERT, _MM_SESSION_SPACE::CommittedPages, _MMWSLE::e1, _MMPFN::Event, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMPTE::Hard, _MMWSL::HashTable, _MMWSL::HashTableStart, InterlockedExchangeAddSizeT, InterlockedIncrementSizeT, _MMWSL::LastEntry, _MMWSL::LastInitializedWsle, LOCK_PFN, _MMWSLENTRY::LockedInWs, _MMPTE::Long, _MMWSLE::Long, MI_ALLOCATED_PAGE_DIRECTORY, MI_ALLOCATED_PAGE_TABLE, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_MAKE_VALID_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_SET_PTE_IN_WORKING_SET, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiChargeCommitmentCantExpand(), MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiRemoveZeroPage(), MiReturnCommitment, MiSwapWslEntries(), MiUpdateWsle(), MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_SESSION_ADDITIONAL_WS_PAGES, MM_DBG_SESSION_NP_WS_GROW, MM_DBG_SESSION_WS_PAGE_ALLOC_GROWTH, MM_DEMAND_ZERO_WRITE_PTE, MM_FREE_WSLE_SHIFT, MM_HIGH_LIMIT, MM_READWRITE, MM_RESAVAIL_ALLOCATE_ADD_WS_PAGE, MM_TRACK_COMMIT, MM_TRACK_COMMIT_REDUCTION, MM_WS_LOCK_ASSERT, MmAvailablePages, MmPagesAboveWsMinimum, MmSessionSpace, _MM_SESSION_SPACE::NonPageablePages, NULL, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, SATISFY_OVERZEALOUS_COMPILER, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiAllocateWsle().
LOGICAL MiAddWsleHash (IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte)
Definition at line 3128 of file wslist.c.
References ASSERT, _MM_SESSION_SPACE::CommittedPages, _MMPFN::e1, _MMWSLE::e1, _MMPFN::Event, FALSE, _MMWSL::FirstDynamic, InterlockedIncrementSizeT, LOCK_PFN, _MMWSLENTRY::LockedInWs, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_MAKE_VALID_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiAllocateWsle(), MiChargeCommitmentCantExpand(), MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiRemoveZeroPage(), MiReturnCommitment, MiSwapWslEntries(), MiTrimPte(), MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_SESSION_ADDITIONAL_WS_HASHPAGES, MM_DBG_SESSION_NP_HASH_GROW, MM_DBG_SESSION_WS_HASHPAGE_ALLOC, MM_DEMAND_ZERO_WRITE_PTE, MM_HIGH_LIMIT, MM_READWRITE, MM_RESAVAIL_ALLOCATE_WSLE_HASH, MM_RESAVAIL_FREE_WSLE_HASH, MM_TRACK_COMMIT, MmAvailablePages, MmSessionSpace, _MM_SESSION_SPACE::NonPageablePages, NULL, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u3, UNLOCK_PFN, _MMWSLENTRY::Valid, _MMWSL::Wsle, and ZeroPte.
Referenced by MiGrowWsleHash().
WSLE_NUMBER MiAllocateWsle (IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN ULONG_PTR WsleMask)
Definition at line 113 of file wslist.c.
References ASSERT, _MMWSLE::e1, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, InterlockedIncrement, InterlockedIncrementSizeT, KeGetCurrentPrcb(), _MMWSL::LastEntry, _MMWSL::LastInitializedWsle, _MMWSLE::Long, MI_IS_SYSTEM_CACHE_ADDRESS, MI_SET_PTE_IN_WORKING_SET, MiAddWorkingSetPage(), MiDoReplacement(), MiGetVirtualAddressMappedByPte, MiUpdateWsle(), MiWsleFailures, MM_FREE_WSLE_SHIFT, MM_ZERO_ACCESS, MmPagesAboveWsMinimum, MmSystemCacheWs, MmSystemCacheWsle, MmTransitionSharedPages, MmTransitionSharedPagesPeak, _MMWSLENTRY::Protection, _MMWSLE::u1, _MMWSLENTRY::Valid, _MMWSL::Wsle, WSLE_NULL_INDEX, WsleAllocationAny, WsleAllocationDontTrim, and WsleAllocationReplace.
Referenced by MiAddValidPageToWorkingSet(), MiAddWsleHash(), MiDispatchFault(), MiLockCode(), MmAccessFault(), MmCheckCachedPageState(), and MmCopyToCachedPage().
VOID MiCheckNullIndex (IN PMMWSL WorkingSetList)
Referenced by MiRemoveWorkingSetPages().
VOID MiCheckWsleHash (IN PMMWSL WorkingSetList)
VOID MiDoReplacement (IN PMMSUPPORT WsInfo, IN WSLE_ALLOCATION_TYPE Flags)
Definition at line 271 of file wslist.c.
References ASSERT, KeQuerySystemTime(), _MMWSL::LastInitializedWsle, LOCK_EXPANSION, MEMORY_PRIORITY_FOREGROUND, _ETHREAD::MemoryMaker, MI_BACKGROUND_CLAIM_AVAILABLE_SHIFT, MI_FOREGROUND_CLAIM_AVAILABLE_SHIFT, MI_PASS0_TRIM_AGE, MI_PASS4_TRIM_AGE, MI_WS_GROWING_TOO_FAST, MiAgeWorkingSet(), MiReplaceWorkingSetEntry(), MiReplacing, MiTrimWorkingSet(), MM_HIGH_LIMIT, MM_VERY_HIGH_LIMIT, MmAvailablePages, NULL, PsGetCurrentThread(), TRUE, UNLOCK_EXPANSION, WsleAllocationDontTrim, and WsleAllocationReplace.
Referenced by MiAllocateWsle().
LOGICAL MiEliminateWorkingSetEntry (IN WSLE_NUMBER WorkingSetIndex, IN PMMPTE PointerPte, IN PMMPFN Pfn, IN PMMSUPPORT WsInfo, IN LOGICAL Force)
Definition at line 4153 of file wslist.c.
References ASSERT, ASSERT32, _MMPTE_HARDWARE::Dirty, _MMWSLE::e1, FALSE, _EPROCESS::Flags, _MMPTE::Hard, KeBugCheckEx(), LOCK_PFN, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_WSLE, MI_IS_PFN_DELETED, MI_IS_PTE_DIRTY, MI_IS_SESSION_ADDRESS, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_WRITE_INVALID_PTE, MI_ZERO_WSINDEX, MiCaptureWriteWatchDirtyBit(), MiCheckPdeForPagedPool(), MiDecrementShareCountInline, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiProtoAddressForPte, MM_HIGHEST_USER_ADDRESS, MM_ZERO_ACCESS, MmSystemCacheWs, MmWsle, NT_SUCCESS, NULL, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE::Proto, _MMPTE_PROTOTYPE::Prototype, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcess(), PTE_BASE, PTE_TOP, SATISFY_OVERZEALOUS_COMPILER, _MMPTE::Soft, TRUE, _MMPTE::u, _MMWSLE::u1, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _MMWSLE::VirtualAddress, and _MMPTE_HARDWARE::Writable.
Referenced by MiFreeWsle(), and MiRemovePageFromWorkingSet().
NTSTATUS MiEmptyWorkingSet (IN PMMSUPPORT WsInfo, IN LOGICAL NeedLock)
Definition at line 4870 of file wslist.c.
References ASSERT, _MMWSLE_FLUSH_LIST::Count, _MMPFN::e1, _MMWSLE::e1, _MMWSL::FirstDynamic, _MMWSLE_FLUSH_LIST::FlushIndex, _MMPTE::Hard, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _MMWSL::LastEntry, LOCK_WORKING_SET, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MiFlushAllPages(), MiFreeWsleList(), MiGetPteAddress, MiPurgeTransitionList(), MiRemoveWorkingSetPages(), MiTrimRemovalPagesOnly, MM_MAXIMUM_FLUSH_COUNT, MM_WS_LOCK_ASSERT, MmWorkingSetList, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcess(), PsGetCurrentThread(), _MMPFN::PteFrame, _MMPFNENTRY::RemovalRequested, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, and _MMWSL::Wsle.
Referenced by MiProcessWorkingSets(), MiTrimAllSystemPageableMemory(), and MmAdjustWorkingSetSizeEx().
ULONG MiFreeWsle (IN WSLE_NUMBER WorkingSetIndex, IN PMMSUPPORT WsInfo, IN PMMPTE PointerPte)
Definition at line 1258 of file wslist.c.
References ASSERT, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, InterlockedDecrementSizeT, _MMWSL::LastInitializedWsle, _MMWSLE::Long, MI_PFN_ELEMENT, MiEliminateWorkingSetEntry(), MiRemoveWsle(), MM_FREE_WSLE_SHIFT, MM_WS_LOCK_ASSERT, MmPagesAboveWsMinimum, MmSystemCacheWs, _MMPFNENTRY::PrototypePte, _MMPFN::ShareCount, TRUE, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, _MMWSLENTRY::Valid, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiInsertWsleHash(), MiReplaceWorkingSetEntry(), and NtUnlockVirtualMemory().
WSLE_NUMBER MiFreeWsleList (IN PMMSUPPORT WsInfo, IN PMMWSLE_FLUSH_LIST WsleFlushList)
Definition at line 3675 of file wslist.c.
References ASSERT, ASSERT32, CONTAINING_RECORD, _MMPTE_FLUSH_LIST::Count, _MMPTE_HARDWARE::Dirty, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedDecrementSizeT, KeBugCheckEx(), _MMWSL::LastInitializedWsle, LOCK_PFN, _MMPTE::Long, _MMWSLE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_PROCESS_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_WSLE, MI_IS_PFN_DELETED, MI_IS_PTE_DIRTY, MI_IS_SESSION_ADDRESS, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_WRITE_INVALID_PTE, MI_ZERO_WSINDEX, MiCaptureWriteWatchDirtyBit(), MiCheckPdeForPagedPool(), MiDecrementShareCountInline, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiProtoAddressForPte, MiRemoveWsle(), MM_FREE_WSLE_SHIFT, MM_HIGHEST_USER_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, MM_WS_LOCK_ASSERT, MM_ZERO_ACCESS, MmPagesAboveWsMinimum, MmSystemCacheWs, MmWsle, NOTHING, NT_SUCCESS, NULL, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE::Proto, _MMPTE_PROTOTYPE::Prototype, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcess(), PTE_BASE, PTE_TOP, _MMPFN::PteAddress, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MMPTE_HARDWARE::Writable, _MMPFN::WsIndex, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiEmptyWorkingSet(), and MiTrimWorkingSet().
VOID MiGrowWsleHash (IN PMMSUPPORT WsInfo)
Definition at line 3291 of file wslist.c.
References ASSERT, ASSERT32, ASSERT64, FALSE, _MMPTE::Hard, _MMWSL::HashTable, _MMWSL::HashTableSize, _MMWSL::HashTableStart, _MMWSL::HighestPermittedHashAddress, _MMWSL::LastInitializedWsle, LOCK_PFN, MI_INCREMENT_RESIDENT_AVAILABLE, MI_ROUND_TO_SIZE, MiAddWsleHash(), MiDeletePte(), MiDeleteValidSystemPte(), MiFillWsleHash(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsAddressValid(), MiIsPteOnPdeBoundary, MiReturnCommitment, MM_RESAVAIL_FREE_WSLE_HASH, MmWorkingSetList, _MMWSL::NonDirectCount, NULL, _EPROCESS::NumberOfPrivatePages, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PsGetCurrentProcess(), PtrToUlong, RtlZeroMemory, TRUE, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmAccessFault().
VOID MiInitializeSessionWsSupport (VOID)
Definition at line 1558 of file wslist.c.
References InitializeListHead(), and MiSessionWsList.
Referenced by MmInitSystem().
VOID MiInitializeWorkingSetList (IN PEPROCESS CurrentProcess)
Definition at line 1393 of file wslist.c.
References ASSERT, BYTE_OFFSET, _MMPFN::Event, HYPER_SPACE, HYPER_SPACE_END, _MMWSLE::Long, MI_INITIALIZE_WSLE, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MM_FREE_WSLE_SHIFT, MM_MAXIMUM_WORKING_SET, MmHyperSpaceEnd, MmWorkingSetList, MmWsle, NULL, PAGE_ALIGN, PAGE_SIZE, PD_PER_SYSTEM, PDE_BASE, _MMPFN::PteFrame, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u4, VAD_BITMAP_SPACE, and WSLE_NULL_INDEX.
Referenced by MmInitializeProcessAddressSpace().
VOID MiReleaseWsle (IN WSLE_NUMBER WorkingSetIndex, IN PMMSUPPORT WsInfo)
Definition at line 893 of file wslist.c.
References ASSERT, _MMWSL::FirstFree, InterlockedDecrementSizeT, _MMWSL::LastInitializedWsle, _MMWSLE::Long, MI_LOG_WSLE_CHANGE, MM_FREE_WSLE_SHIFT, MM_WS_LOCK_ASSERT, MmPagesAboveWsMinimum, _MMWSLE::u1, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiDecommitPages(), MiDeleteAddressesInWorkingSet(), MiDeleteSystemPageableVm(), MiLockCode(), MiRemovePageFromWorkingSet(), and MiTerminateWsle().
ULONG MiRemovePageFromWorkingSet (IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN PMMSUPPORT WsInfo)
Definition at line 781 of file wslist.c.
References ASSERT, _MMWSLE::e1, FALSE, _MMWSL::FirstDynamic, _MMWSLENTRY::LockedInMemory, _MMWSLENTRY::LockedInWs, MI_PFN_ELEMENT, MiEliminateWorkingSetEntry(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiLocateWsle(), MiReleaseWsle(), MiRemoveWsle(), MiSwapWslEntries(), PAGE_ALIGN, TRUE, _MMWSLE::u1, _MMWSLE::VirtualAddress, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiProtectVirtualMemory(), and MiSetProtectionOnSection().
VOID MiRemoveWorkingSetPages (IN PMMSUPPORT WsInfo)
Definition at line 4446 of file wslist.c.
References ASSERT, BYTE_OFFSET, _MMWSLENTRY::Direct, _MMWSLE::e1, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMPTE::Hard, _MMWSLENTRY::Hashed, _MMWSL::HashTable, _MMWSL::HashTableSize, _MMWSL::HighestPermittedHashAddress, _MMWSL::LastEntry, _MMWSL::LastInitializedWsle, _MMWSLE::Long, MI_GET_PAGE_FRAME_FROM_PTE, MI_LOG_WSLE_CHANGE, MI_PFN_ELEMENT, MI_SET_PTE_IN_WORKING_SET, MiCheckNullIndex(), MiDeletePteRange(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiInsertWsleHash(), MiIsAddressValid(), MiRemoveWsle(), MM_FREE_WSLE_SHIFT, MmSystemCacheWs, _MMWSL::NextSlot, _MMWSL::NonDirectCount, NULL, PAGE_ALIGN, PAGE_SIZE, PtrToUlong, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MMPFN::WsIndex, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiEmptyWorkingSet(), MiTrimWorkingSet(), and MmCleanProcessAddressSpace().
VOID MiReplaceWorkingSetEntry (IN PMMSUPPORT WsInfo, IN WSLE_ALLOCATION_TYPE Flags)
Definition at line 591 of file wslist.c.
References _MMWSLE::e1, _MMWSL::FirstDynamic, _MMWSL::LastEntry, MI_GET_ACCESSED_IN_PTE, MI_GET_WSLE_AGE, MI_IMMEDIATE_REPLACEMENT_AGE, MiFreeWsle(), MiGetPteAddress, MM_WORKING_SET_LIST_SEARCH, _MMWSL::NextSlot, TRUE, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MMWSL::Wsle, WSLE_NULL_INDEX, WsleAllocationAny, and WsleAllocationReplace.
Referenced by MiDoReplacement().
NTSTATUS MiSessionInitializeWorkingSetList (VOID)
Definition at line 1592 of file wslist.c.
References ASSERT, _LIST_ENTRY::Blink, _MM_SESSION_SPACE::CommittedPages, ExInitializePushLock(), ExPageLockHandle, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMSUPPORT::Flags, _LIST_ENTRY::Flink, _MMPTE_HARDWARE::Global, _MMPTE::Hard, _MMWSL::HashTable, _MMWSL::HashTableSize, _MMWSL::HashTableStart, _MMWSL::HighestPermittedHashAddress, Index, InsertTailList(), InterlockedExchangeAddSizeT, KeZeroSinglePage, _MMWSL::LastEntry, _MMWSL::LastInitializedWsle, _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, LOCK_PFN, _MMPTE::Long, _MMWSLE::Long, _MMSUPPORT::MaximumWorkingSetSize, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_VA, MI_INITIALIZE_SESSION_WSLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_SESSION_SPACE_STRUCT_SIZE, MI_SESSION_SPACE_WORKING_SET_MAXIMUM, MI_SESSION_SPACE_WORKING_SET_MINIMUM, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPdeSessionIndex, MiGetPteAddress, MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), _MMSUPPORT::MinimumWorkingSetSize, MiRemoveZeroPageMayReleaseLocks(), MiReturnCommitment, MiSessionImageStart, MiSessionSpaceEnd, MiSessionSpaceWs, MiSessionWsList, MM_BUMP_SESS_COUNTER, MM_BUMP_SESSION_FAILURES, MM_DBG_COMMIT_SESSION_WS_INIT, MM_DBG_SESSION_NP_INIT_WS, MM_DBG_SESSION_WS_PAGE_ALLOC, MM_DBG_SESSION_WS_PAGETABLE_ALLOC, MM_DEMAND_ZERO_WRITE_PTE, MM_FREE_WSLE_SHIFT, MM_HIGH_LIMIT, MM_RESAVAIL_ALLOCATE_INIT_SESSION_WS, MM_SESSION_FAILURE_NO_COMMIT, MM_SESSION_FAILURE_NO_RESIDENT, MM_TRACK_COMMIT, MM_VA_MAPPED_BY_PDE, MmAvailablePages, MmLockPageableSectionByHandle(), MmSessionBase, MmSessionSpace, MmUnlockPageableImageSection(), MmWorkingSetExpansionHead, _MMWSL::NextSlot, _MM_SESSION_SPACE::NonPageablePages, NULL, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_HARDWARE::PageFrameNumber, _MM_SESSION_SPACE::PageTables, PTE_PER_PAGE, SESSION_GLOBAL, _MM_SESSION_SPACE::SessionPageDirectoryIndex, _MMSUPPORT_FLAGS::SessionSpace, STATUS_NO_MEMORY, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, UNLOCK_EXPANSION, UNLOCK_PFN, _MMWSL::UsedPageTableEntries, _MMPTE_HARDWARE::Valid, ValidKernelPdeLocal, ValidKernelPteLocal, _MM_SESSION_SPACE::Vm, _MMSUPPORT::VmWorkingSetList, _MMSUPPORT::WorkingSetExpansionLinks, _MMSUPPORT::WorkingSetMutex, _MMSUPPORT::WorkingSetSize, _MMPFN::WsIndex, _MMWSL::Wsle, _MM_SESSION_SPACE::Wsle, WSLE_NULL_INDEX, and _MM_SESSION_SPACE::WsListEntry.
Referenced by MmSessionCreate().
WSLE_NUMBER MiTrimWorkingSet (IN WSLE_NUMBER Reduction, IN PMMSUPPORT WsInfo, IN ULONG TrimAge)
Definition at line 4022 of file wslist.c.
References ASSERT, _MMWSLE_FLUSH_LIST::Count, _MMWSLE::e1, _MMWSL::FirstDynamic, _MMWSLE_FLUSH_LIST::FlushIndex, _MMPTE::Hard, _MMWSL::LastEntry, MI_GET_ACCESSED_IN_PTE, MI_GET_WSLE_AGE, MiFreeWsleList(), MiGetPteAddress, MiRemoveWorkingSetPages(), MM_MAXIMUM_FLUSH_COUNT, MM_WS_LOCK_ASSERT, _MMWSL::NextSlot, PAGE_SIZE, _MMPTE::u, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, and _MMWSL::Wsle.
Referenced by MiDoReplacement(), MiProcessWorkingSets(), and MmAdjustWorkingSetSizeEx().
VOID MiUpdateWsle (IN OUT PWSLE_NUMBER DesiredIndex, IN PVOID VirtualAddress, IN PMMSUPPORT WsInfo, IN PMMPFN Pfn, IN ULONG_PTR WsleMask)
Definition at line 958 of file wslist.c.
References ASSERT, ASSERT32, _MMWSLENTRY::Direct, _MMWSLE::e1, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMWSLENTRY::Hashed, _MMWSL::HashTable, Index, InterlockedCompareExchange(), InterlockedCompareExchange64, _MMWSL::LastEntry, _MMWSL::LastInitializedWsle, _MMWSLE::Long, MI_IS_SESSION_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_LOG_WSLE_CHANGE, MiInsertWsleHash(), MiLowestSystemPteVirtualAddress, MiSwapWslEntries(), MM_FREE_WSLE_SHIFT, MM_SYSTEM_SPACE_START, MM_WS_LOCK_ASSERT, MmPagedPoolEnd, MmPagedPoolPage, MmPagedPoolStart, MmSpecialPoolEnd, MmSpecialPoolStart, MmSystemCachePage, MmSystemCacheWorkingSetList, MmSystemCodePage, MmSystemDriverPage, _MMWSL::NonDirectCount, NOTHING, NULL, PAGE_ALIGN, PTE_BASE, TRUE, _MMWSLE::u1, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MiAddWorkingSetPage(), and MiAllocateWsle().
NTSTATUS MmAdjustWorkingSetSize (__in SIZE_T WorkingSetMinimumInBytes, __in SIZE_T WorkingSetMaximumInBytes, __in ULONG SystemCache, __in BOOLEAN IncreaseOkay)
Definition at line 2591 of file wslist.c.
References MmAdjustWorkingSetSizeEx().
Referenced by NtSetInformationJobObject(), and PspAddProcessToJob().
NTSTATUS MmAdjustWorkingSetSizeEx (IN SIZE_T WorkingSetMinimumInBytes, IN SIZE_T WorkingSetMaximumInBytes, IN ULONG SystemCache, IN BOOLEAN IncreaseOkay, IN ULONG Flags, OUT PBOOLEAN IncreaseRequested)
Definition at line 2198 of file wslist.c.
References ASSERT, ExPageLockHandle, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMSUPPORT::Flags, _EPROCESS::Flags, InterlockedExchangeAddSizeT, _MMWSL::LastInitializedWsle, LOCK_EXPANSION, LOCK_PFN, LOCK_SYSTEM_WS, LOCK_WS, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, MI_DECREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PASS0_TRIM_AGE, MiEmptyWorkingSet(), _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MiTrimWorkingSet(), MM_FLUID_WORKING_SET, MM_HIGH_LIMIT, MM_RESAVAIL_ALLOCATEORFREE_WS_ADJUST, MM_RESAVAIL_ALLOCATEORFREE_WS_ADJUST2, MM_RESAVAIL_ALLOCATEORFREE_WS_ADJUST3, MmAvailablePages, MmLockPageableSectionByHandle(), MmMaximumWorkingSetSize, MmMinimumWorkingSetSize, MmPagesAboveWsMinimum, MmSystemCacheWs, MmUnlockPageableImageSection(), NULL, PAGE_SHIFT, PAGE_SIZE, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), STATUS_BAD_WORKING_SET_LIMIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_WORKING_SET_LIMIT_RANGE, TRUE, UNLOCK_EXPANSION, UNLOCK_PFN, UNLOCK_SYSTEM_WS, UNLOCK_WS, _EPROCESS::Vm, _MMSUPPORT::VmWorkingSetList, _MMSUPPORT::WorkingSetSize, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MmAdjustWorkingSetSize(), NtSetSystemInformation(), and PspSetQuotaLimits().
LOGICAL MmAssignProcessToJob (IN PEPROCESS Process)
Definition at line 1980 of file wslist.c.
References FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, PAGED_CODE, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_SET_BITS, PsChangeJobMemoryUsage(), PsGetCurrentProcess(), Status, TRUE, and UNLOCK_ADDRESS_SPACE.
Referenced by PspAddProcessToJob().
NTSTATUS MmEnforceWorkingSetLimit (IN PEPROCESS Process, IN ULONG Flags)
Definition at line 464 of file wslist.c.
References FALSE, _MMSUPPORT::Flags, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_EXPANSION, LOCK_WS, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MM_FLUID_WORKING_SET, PsGetCurrentProcess(), PsGetCurrentThread(), Status, STATUS_BAD_WORKING_SET_LIMIT, STATUS_SUCCESS, TRUE, UNLOCK_EXPANSION, and UNLOCK_WS.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), PspApplyJobLimitsToProcess(), and PspSetQuotaLimits().
VOID MmQuerySystemCacheWorkingSetInformation (OUT PSYSTEM_FILECACHE_INFORMATION Info)
Definition at line 2127 of file wslist.c.
References APC_LEVEL, ASSERT, _MMSUPPORT::Flags, KeGetCurrentIrql(), LOCK_SYSTEM_WS, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MmStandbyRePurposed, MmSystemCacheWs, MmTransitionSharedPages, MmTransitionSharedPagesPeak, PAGE_SHIFT, _MMSUPPORT::PageFaultCount, _MMSUPPORT::PeakWorkingSetSize, PsGetCurrentThread(), UNLOCK_SYSTEM_WS, and _MMSUPPORT::WorkingSetSize.
Referenced by NtQuerySystemInformation().
NTSTATUS MmQueryWorkingSetInformation (IN PSIZE_T PeakWorkingSetSize, IN PSIZE_T WorkingSetSize, IN PSIZE_T MinimumWorkingSetSize, IN PSIZE_T MaximumWorkingSetSize, IN PULONG HardEnforcementFlags)
Definition at line 2053 of file wslist.c.
References APC_LEVEL, ASSERT, _MMSUPPORT::Flags, KeGetCurrentIrql(), LOCK_WS_SHARED, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, PAGE_SHIFT, _MMSUPPORT::PeakWorkingSetSize, PsGetCurrentProcessByThread, PsGetCurrentThread(), STATUS_SUCCESS, UNLOCK_WS_SHARED, _EPROCESS::Vm, and _MMSUPPORT::WorkingSetSize.
Referenced by NtQueryInformationProcess(), and PspQueryQuotaLimits().
Variable Documentation
LOGICAL MiReplacing
Definition at line 72 of file wsmanage.c.
Referenced by MiComputeSystemTrimCriteria(), and MiDoReplacement().
LOGICAL MiTrimRemovalPagesOnly
Referenced by MiEmptyWorkingSet().
ULONG MiWsleFailures
Definition at line 109 of file wslist.c.
Referenced by MiAllocateWsle().
WSLE_NUMBER MmMaximumWorkingSetSize
Definition at line 538 of file miglobal.c.
Referenced by MmAdjustWorkingSetSizeEx().
ULONG MmPagedPoolPage
Definition at line 26 of file wslist.c.
Referenced by MiRemoveWsle(), MiUpdateWsle(), and NtQuerySystemInformation().
ULONG MmStandbyRePurposed
Definition at line 58 of file pfnlist.c.
Referenced by MmQuerySystemCacheWorkingSetInformation().
ULONG MmSystemCachePage
Definition at line 25 of file wslist.c.
Referenced by MiRemoveWsle(), MiUpdateWsle(), and NtQuerySystemInformation().
ULONG MmSystemCodePage
Definition at line 24 of file wslist.c.
Referenced by MiRemoveWsle(), MiUpdateWsle(), and NtQuerySystemInformation().
ULONG MmSystemDriverPage
Definition at line 27 of file wslist.c.
Referenced by MiRemoveWsle(), MiUpdateWsle(), and NtQuerySystemInformation().
PFN_NUMBER MmTransitionSharedPages
Definition at line 35 of file pfnlist.c.
Referenced by MiAllocateWsle(), MiInsertStandbyListAtFront(), and MmQuerySystemCacheWorkingSetInformation().
PFN_NUMBER MmTransitionSharedPagesPeak
Definition at line 35 of file wslist.c.
Referenced by MiAllocateWsle(), and MmQuerySystemCacheWorkingSetInformation().