Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/string.c File Reference
string.c File Reference
#include "string.h"
#include "nt.h"
#include "ntrtlp.h"
Functions
NTSTATUS RtlAppendAsciizToString (IN PSTRING Destination, IN PCSZ Source OPTIONAL)
NTSTATUS RtlAppendStringToString (IN PSTRING Destination, IN const STRING *Source)
LONG RtlCompareString (IN const STRING *String1, IN const STRING *String2, IN BOOLEAN CaseInSensitive)
VOID RtlCopyString (OUT PSTRING DestinationString, IN const STRING *SourceString OPTIONAL)
BOOLEAN RtlCreateUnicodeStringFromAsciiz (OUT PUNICODE_STRING DestinationString, IN PCSZ SourceString)
BOOLEAN RtlEqualString (IN const STRING *String1, IN const STRING *String2, IN BOOLEAN CaseInSensitive)
NTSTATUS RtlInitAnsiStringEx (OUT PANSI_STRING DestinationString, IN PCSZ SourceString OPTIONAL)
NTSTATUS RtlInitUnicodeStringEx (OUT PUNICODE_STRING DestinationString, IN PCWSTR SourceString OPTIONAL)
BOOLEAN RtlPrefixString (const STRING *String1, const STRING *String2, IN BOOLEAN CaseInSensitive)
CHAR RtlUpperChar (register IN CHAR Character)
VOID RtlUpperString (IN PSTRING DestinationString, IN const STRING *SourceString)
Variables
PUSHORT NlsAnsiToUnicodeData
const PUSHORT NlsLeadByteInfo
BOOLEAN NlsMbCodePageTag
PCH NlsUnicodeToAnsiData
PUSHORT NlsUnicodeToMbAnsiData
Function Documentation
NTSTATUS RtlAppendAsciizToString (IN PSTRING Destination, IN PCSZ Source OPTIONAL)
Definition at line 719 of file string.c.
References ARGUMENT_PRESENT, MAXUSHORT, RTL_PAGED_CODE, RtlMoveMemory, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and strlen().
NTSTATUS RtlAppendStringToString (IN PSTRING Destination, IN const STRING * Source)
Definition at line 772 of file string.c.
References RTL_PAGED_CODE, RtlMoveMemory, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
LONG RtlCompareString (IN const STRING * String1, IN const STRING * String2, IN BOOLEAN CaseInSensitive)
Definition at line 400 of file string.c.
References RTL_PAGED_CODE, and RtlUpperChar().
VOID RtlCopyString (OUT PSTRING DestinationString, IN const STRING *SourceString OPTIONAL)
Definition at line 276 of file string.c.
References ARGUMENT_PRESENT, and memcpy().
BOOLEAN RtlCreateUnicodeStringFromAsciiz (OUT PUNICODE_STRING DestinationString, IN PCSZ SourceString)
Definition at line 641 of file string.c.
References ASSERT_WELL_FORMED_UNICODE_STRING_OUT, FALSE, NT_SUCCESS, RTL_PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlInitAnsiStringEx(), Status, and TRUE.
Referenced by CmpSetSystemValues(), and IopInitializeBootLogging().
BOOLEAN RtlEqualString (IN const STRING * String1, IN const STRING * String2, IN BOOLEAN CaseInSensitive)
Definition at line 485 of file string.c.
References FALSE, RtlUpperChar(), and TRUE.
NTSTATUS RtlInitAnsiStringEx (OUT PANSI_STRING DestinationString, IN PCSZ SourceString OPTIONAL)
Definition at line 246 of file string.c.
References ARGUMENT_PRESENT, MAXUSHORT, STATUS_NAME_TOO_LONG, STATUS_SUCCESS, and strlen().
Referenced by RtlCreateUnicodeStringFromAsciiz().
NTSTATUS RtlInitUnicodeStringEx (OUT PUNICODE_STRING DestinationString, IN PCWSTR SourceString OPTIONAL)
Definition at line 214 of file string.c.
References ARGUMENT_PRESENT, STATUS_NAME_TOO_LONG, STATUS_SUCCESS, and wcslen().
BOOLEAN RtlPrefixString (const STRING * String1, const STRING * String2, IN BOOLEAN CaseInSensitive)
Definition at line 566 of file string.c.
References _STRING::Buffer, FALSE, _STRING::Length, RTL_PAGED_CODE, RtlUpperChar(), and TRUE.
CHAR RtlUpperChar (register IN CHAR Character)
Definition at line 325 of file string.c.
References HIBYTE, LOBYTE, NLS_UPCASE, NlsAnsiToUnicodeData, NlsLeadByteInfo, NlsMbCodePageTag, NlsUnicodeToAnsiData, NlsUnicodeToMbAnsiData, and RTL_PAGED_CODE.
Referenced by RtlCompareString(), RtlEqualString(), RtlPrefixString(), and RtlUpperString().
VOID RtlUpperString (IN PSTRING DestinationString, IN const STRING * SourceString)
Definition at line 668 of file string.c.
References RTL_PAGED_CODE, and RtlUpperChar().
Variable Documentation
PUSHORT NlsAnsiToUnicodeData
Definition at line 82 of file nlsxlat.c.
Referenced by RtlConsoleMultiByteToUnicodeN(), RtlMultiByteToUnicodeN(), RtlResetRtlTranslations(), RtlUpcaseUnicodeToMultiByteN(), and RtlUpperChar().
const PUSHORT NlsLeadByteInfo
Definition at line 80 of file nlsxlat.c.
Referenced by RtlConsoleMultiByteToUnicodeN(), RtlMultiByteToUnicodeN(), RtlMultiByteToUnicodeSize(), RtlResetRtlTranslations(), RtlUpcaseUnicodeToMultiByteN(), and RtlUpperChar().
BOOLEAN NlsMbCodePageTag
Definition at line 85 of file nlsxlat.c.
Referenced by CompareNamesCaseSensitive(), ComputeNameLength(), ExpSystemErrorHandler(), RtlConsoleMultiByteToUnicodeN(), RtlIsTextUnicode(), RtlMultiByteToUnicodeN(), RtlMultiByteToUnicodeSize(), RtlResetRtlTranslations(), RtlUnicodeToMultiByteN(), RtlUnicodeToMultiByteSize(), RtlUpcaseUnicodeToMultiByteN(), and RtlUpperChar().
PCH NlsUnicodeToAnsiData
Definition at line 83 of file nlsxlat.c.
Referenced by RtlResetRtlTranslations(), RtlUnicodeToMultiByteN(), RtlUpcaseUnicodeToMultiByteN(), and RtlUpperChar().
PUSHORT NlsUnicodeToMbAnsiData
Definition at line 84 of file nlsxlat.c.
Referenced by RtlResetRtlTranslations(), RtlUnicodeToMultiByteN(), RtlUnicodeToMultiByteSize(), RtlUpcaseUnicodeToMultiByteN(), and RtlUpperChar().