Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/misc.c File Reference
misc.c File Reference
#include "ki.h"
#include "fastsys.inc"
Data Structures
struct _CONTROL_WORD
struct FLOAT_SAVE
Macros
#define ALIGN_ADJUST 8
#define FLOAT_SAVE_ALIGN_ADJUSTED 0x08
#define FLOAT_SAVE_COMPLETE_CONTEXT 0x01
#define FLOAT_SAVE_FREE_CONTEXT_HEAP 0x02
#define FLOAT_SAVE_RESERVED 0xF0
#define FLOAT_SAVE_VALID 0x04
Typedefs
typedef struct _CONTROL_WORD CONTROL_WORD
typedef struct _CONTROL_WORD * PCONTROL_WORD
typedef struct FLOAT_SAVE * PFLOAT_SAVE
Functions
VOID KePrepareToLoseProcessorSpecificState (VOID)
NTSTATUS KeRestoreFloatingPointState (IN PKFLOATING_SAVE PublicFloatSave)
VOID KeRestoreMtrr (VOID)
VOID KeRestorePAT (VOID)
VOID KeRestoreProcessorSpecificFeatures (VOID)
NTSTATUS KeSaveFloatingPointState (OUT PKFLOATING_SAVE PublicFloatSave)
VOID __cdecl KeSaveStateForHibernate (__out PKPROCESSOR_STATE ProcessorState)
VOID FASTCALL KiAcquireQueuedSpinLockCheckForFreeze (IN PKSPIN_LOCK_QUEUE QueuedLock, IN PKTRAP_FRAME TrapFrame)
VOID KiDisableFastSyscallReturn (VOID)
VOID KiEnableFastSyscallReturn (VOID)
VOID KiLoadFastSyscallMachineSpecificRegisters (IN PLONG Context)
BOOLEAN FASTCALL KiProcessDebugRegister (IN OUT PKTRAP_FRAME TrapFrame, IN ULONG Register)
BOOLEAN FASTCALL KiRecordDr7 (IN OUT PULONG Dr7Ptr, IN OUT PUCHAR Mask OPTIONAL)
VOID KiRestoreFastSyscallReturnState (VOID)
ULONG FASTCALL KiUpdateDr7 (IN ULONG Dr7)
Variables
BOOLEAN KeI386FxsrPresent
BOOLEAN KeI386XMMIPresent
const ULONG KiDebugRegisterContextOffsets []
const ULONG KiDebugRegisterTrapOffsets []
UCHAR KiDefaultSystemCall []
BOOLEAN KiFastCallCopyDoneOnce = FALSE
UCHAR KiFastCallEntry []
UCHAR KiFastSystemCallAmdK6 []
ULONG KiFastSystemCallDisable
UCHAR KiFastSystemCallIa32 []
BOOLEAN KiFastSystemCallIsIA32
UCHAR KiSystemCallExit []
UCHAR KiSystemCallExit2 []
UCHAR KiSystemCallExit3 []
ULONG_PTR KiSystemCallExitAdjust
UCHAR KiSystemCallExitAdjusted
UCHAR KiSystemCallExitBranch []
Macro Definition Documentation
#define ALIGN_ADJUST 8
Definition at line 90 of file misc.c.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
#define FLOAT_SAVE_ALIGN_ADJUSTED 0x08
Definition at line 80 of file misc.c.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
#define FLOAT_SAVE_COMPLETE_CONTEXT 0x01
Definition at line 77 of file misc.c.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
#define FLOAT_SAVE_FREE_CONTEXT_HEAP 0x02
Definition at line 78 of file misc.c.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
#define FLOAT_SAVE_RESERVED 0xF0
Definition at line 81 of file misc.c.
Referenced by KeRestoreFloatingPointState().
#define FLOAT_SAVE_VALID 0x04
Definition at line 79 of file misc.c.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
Typedef Documentation
typedef struct _CONTROL_WORD CONTROL_WORD
typedef struct _CONTROL_WORD * PCONTROL_WORD
typedef struct FLOAT_SAVE * PFLOAT_SAVE
Function Documentation
VOID KePrepareToLoseProcessorSpecificState (VOID)
Definition at line 647 of file misc.c.
NTSTATUS KeRestoreFloatingPointState (IN PKFLOATING_SAVE PublicFloatSave)
Definition at line 337 of file misc.c.
References ALIGN_ADJUST, ASSERT, FLOAT_SAVE::Context, FLOAT_SAVE::ContextAddressAsULONG, _CONTROL_WORD::ControlWord, _FNSAVE_FORMAT::ControlWord, _FXSAVE_FORMAT::ControlWord, CR0_EM, CR0_MP, CR0_TS, FLOAT_SAVE::Cr0NpxState, _FX_SAVE_AREA::Cr0NpxState, ExFreePool(), FLOAT_SAVE::Fcw, FLOAT_SAVE::Flags, FLOAT_SAVE_ALIGN_ADJUSTED, FLOAT_SAVE_COMPLETE_CONTEXT, FLOAT_SAVE_FREE_CONTEXT_HEAP, FLOAT_SAVE_RESERVED, FLOAT_SAVE_VALID, _FX_SAVE_AREA::FnArea, _FX_SAVE_AREA::FxArea, _KTHREAD::Header, _KTHREAD::InitialStack, INVALID_FLOATING_POINT_STATE, FLOAT_SAVE::Irql, KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeI386FxsrPresent, KeI386NpxPresent, KeI386XMMIPresent, Kix86LdMXCsr(), _CONTROL_WORD::MXCsr, _FXSAVE_FORMAT::MXCsr, NPX_STATE_LOADED, NPX_STATE_NOT_LOADED, _DISPATCHER_HEADER::NpxIrql, _FX_SAVE_AREA::NpxSavedCpu, _KTHREAD::NpxState, _KPRCB::NpxThread, NULL, FLOAT_SAVE::PreviousNpxIrql, RtlCopyMemory, STATUS_SUCCESS, _FNSAVE_FORMAT::StatusWord, _FXSAVE_FORMAT::StatusWord, _FNSAVE_FORMAT::TagWord, _FXSAVE_FORMAT::TagWord, FLOAT_SAVE::Thread, FLOAT_SAVE::u, and _FX_SAVE_AREA::U.
VOID KeRestoreMtrr (VOID)
Definition at line 537 of file mtrr.c.
References ASSERT, KeAcquireSpinLock, KeFeatureBits, KeReleaseSpinLock(), KF_AMDK6MTRR, KiCompleteEffectiveRangeChange(), KiLoadMTRR(), KiRangeLock, KiStartEffectiveRangeChange(), NT_SUCCESS, NULL, _RANGE_INFO::RangesValid, RtlZeroMemory, and _NEW_RANGE::Status.
Referenced by KeRestoreProcessorSpecificFeatures().
VOID KeRestorePAT (VOID)
Definition at line 90 of file pat.c.
References KeFeatureBits, KF_PAT, and KiInitializePAT().
Referenced by KeRestoreProcessorSpecificFeatures().
VOID KeRestoreProcessorSpecificFeatures (VOID)
Definition at line 750 of file misc.c.
References KeRestoreMtrr(), KeRestorePAT(), and KiRestoreFastSyscallReturnState().
NTSTATUS KeSaveFloatingPointState (OUT PKFLOATING_SAVE PublicFloatSave)
Definition at line 94 of file misc.c.
References ALIGN_ADJUST, APC_LEVEL, ASSERT, FLOAT_SAVE::Context, FLOAT_SAVE::ContextAddressAsULONG, _CONTROL_WORD::ControlWord, _FNSAVE_FORMAT::ControlWord, _FXSAVE_FORMAT::ControlWord, CR0_EM, CR0_MP, CR0_TS, FLOAT_SAVE::Cr0NpxState, _FX_SAVE_AREA::Cr0NpxState, DISPATCH_LEVEL, ExAllocatePoolWithTag, FLOAT_SAVE::Fcw, FLOAT_SAVE::Flags, FLOAT_SAVE_ALIGN_ADJUSTED, FLOAT_SAVE_COMPLETE_CONTEXT, FLOAT_SAVE_FREE_CONTEXT_HEAP, FLOAT_SAVE_VALID, _FX_SAVE_AREA::FnArea, _FX_SAVE_AREA::FxArea, _KTHREAD::Header, _KTHREAD::InitialStack, FLOAT_SAVE::Irql, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeI386FxsrPresent, KeI386NpxPresent, KeI386XMMIPresent, Kix86FnSave(), Kix86FxSave(), Kix86LdMXCsr(), Kix86StMXCsr(), _CONTROL_WORD::MXCsr, _FXSAVE_FORMAT::MXCsr, NonPagedPool, NPX_STATE_LOADED, NPX_STATE_NOT_LOADED, _DISPATCHER_HEADER::NpxIrql, _KPRCB::NpxSaveArea, _FX_SAVE_AREA::NpxSavedCpu, _KTHREAD::NpxState, _KPRCB::NpxThread, FLOAT_SAVE::PreviousNpxIrql, RtlCopyMemory, STATUS_ILLEGAL_FLOAT_CONTEXT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, FLOAT_SAVE::Thread, FLOAT_SAVE::u, and _FX_SAVE_AREA::U.
VOID __cdecl KeSaveStateForHibernate (__out PKPROCESSOR_STATE ProcessorState)
Definition at line 1820 of file misc.c.
References KiSaveProcessorControlState(), and RtlCaptureContext().
VOID FASTCALL KiAcquireQueuedSpinLockCheckForFreeze (IN PKSPIN_LOCK_QUEUE QueuedLock, IN PKTRAP_FRAME TrapFrame)
Definition at line 785 of file misc.c.
References InterlockedCompareExchange(), InterlockedExchangePointer, IPI_FREEZE, KeGetCurrentPrcb(), KeYieldProcessor, KiFreezeTargetExecution(), LOCK_QUEUE_OWNER, LOCK_QUEUE_WAIT, _KSPIN_LOCK_QUEUE::Next, NULL, and _KPRCB::RequestSummary.
VOID KiDisableFastSyscallReturn (VOID)
Definition at line 540 of file misc.c.
References KiSystemCallExitAdjusted, and KiSystemCallExitBranch.
Referenced by KiEnableFastSyscallReturn().
VOID KiEnableFastSyscallReturn (VOID)
Definition at line 576 of file misc.c.
References KiDisableFastSyscallReturn(), KiFastCallCopyDoneOnce, KiSystemCallExitAdjust, KiSystemCallExitAdjusted, KiSystemCallExitBranch, and TRUE.
Referenced by KiRestoreFastSyscallReturnState().
VOID KiLoadFastSyscallMachineSpecificRegisters (IN PLONG Context)
Definition at line 661 of file misc.c.
References _KPRCB::DpcStack, KeGetCurrentPrcb(), KGDT_R0_CODE, KiFastCallEntry, KiFastSystemCallIsIA32, UNREFERENCED_PARAMETER, and WRMSR().
Referenced by KiRestoreFastSyscallReturnState().
BOOLEAN FASTCALL KiProcessDebugRegister (IN OUT PKTRAP_FRAME TrapFrame, IN ULONG Register)
Definition at line 1686 of file misc.c.
References ASSERT, _DISPATCHER_HEADER::DebugActive, DR7_OVERRIDE_MASK, DR7_OVERRIDE_V, DR7_RESERVED_MASK, DR_MASK, DR_REG_MASK, FALSE, _KTHREAD::Header, and KeGetCurrentThread().
BOOLEAN FASTCALL KiRecordDr7 (IN OUT PULONG Dr7Ptr, IN OUT PUCHAR Mask OPTIONAL)
Definition at line 1587 of file misc.c.
References ARGUMENT_PRESENT, ASSERT, _DISPATCHER_HEADER::DebugActive, DR7_OVERRIDE_MASK, DR7_OVERRIDE_V, DR7_RESERVED_MASK, DR_MASK, DR_REG_MASK, FALSE, _KTHREAD::Header, and KeGetCurrentThread().
Referenced by KeContextToKframes().
VOID KiRestoreFastSyscallReturnState (VOID)
Definition at line 703 of file misc.c.
References KeFeatureBits, KeIpiGenericCall(), KF_FAST_SYSCALL, KiEnableFastSyscallReturn(), KiFastSystemCallDisable, KiLoadFastSyscallMachineSpecificRegisters(), KiSystemCallExit, KiSystemCallExit2, and KiSystemCallExitAdjust.
Referenced by KeRestoreProcessorSpecificFeatures(), and KiInitMachineDependent().
ULONG FASTCALL KiUpdateDr7 (IN ULONG Dr7)
Definition at line 1779 of file misc.c.
References ASSERT, _DISPATCHER_HEADER::DebugActive, DR7_OVERRIDE_MASK, DR7_OVERRIDE_V, DR7_RESERVED_MASK, DR_MASK, DR_REG_MASK, _KTHREAD::Header, and KeGetCurrentThread().
Referenced by KeContextFromKframes().
Variable Documentation
BOOLEAN KeI386FxsrPresent
Definition at line 32 of file i386init.c.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
BOOLEAN KeI386XMMIPresent
Definition at line 215 of file kernlini.c.
Referenced by KeRestoreFloatingPointState(), KeSaveFloatingPointState(), and KiInitializeKernel().
const ULONG KiDebugRegisterContextOffsets[]
Initial value:
=
    {
        FIELD_OFFSET (CONTEXT, Dr0),
        FIELD_OFFSET (CONTEXT, Dr1),
        FIELD_OFFSET (CONTEXT, Dr2),
        FIELD_OFFSET (CONTEXT, Dr3),
        0,
        0,
        FIELD_OFFSET (CONTEXT, Dr6),
    }
Definition at line 1573 of file misc.c.
Referenced by KeContextToKframes().
const ULONG KiDebugRegisterTrapOffsets[]
Initial value:
=
    {
        FIELD_OFFSET (KTRAP_FRAME, Dr0),
        FIELD_OFFSET (KTRAP_FRAME, Dr1),
        FIELD_OFFSET (KTRAP_FRAME, Dr2),
        FIELD_OFFSET (KTRAP_FRAME, Dr3),
        0,
        0,
        FIELD_OFFSET (KTRAP_FRAME, Dr6),
    }
Definition at line 1561 of file misc.c.
Referenced by KeContextToKframes().
UCHAR KiDefaultSystemCall[]
BOOLEAN KiFastCallCopyDoneOnce = FALSE
Definition at line 38 of file misc.c.
Referenced by KiEnableFastSyscallReturn().
UCHAR KiFastCallEntry[]
Referenced by KiLoadFastSyscallMachineSpecificRegisters().
UCHAR KiFastSystemCallAmdK6[]
ULONG KiFastSystemCallDisable
Definition at line 157 of file kernlini.c.
Referenced by KiInitializeKernel(), and KiRestoreFastSyscallReturnState().
UCHAR KiFastSystemCallIa32[]
BOOLEAN KiFastSystemCallIsIA32
Definition at line 37 of file misc.c.
Referenced by KiGetFeatureBits(), and KiLoadFastSyscallMachineSpecificRegisters().
UCHAR KiSystemCallExit[]
Referenced by KiRestoreFastSyscallReturnState().
UCHAR KiSystemCallExit2[]
Referenced by KiRestoreFastSyscallReturnState().
UCHAR KiSystemCallExit3[]
ULONG_PTR KiSystemCallExitAdjust
Definition at line 35 of file misc.c.
Referenced by KiEnableFastSyscallReturn(), and KiRestoreFastSyscallReturnState().
UCHAR KiSystemCallExitAdjusted
Definition at line 36 of file misc.c.
Referenced by KiDisableFastSyscallReturn(), and KiEnableFastSyscallReturn().
UCHAR KiSystemCallExitBranch[]
Referenced by KiDisableFastSyscallReturn(), and KiEnableFastSyscallReturn().