Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/loadunld.c File Reference
loadunld.c File Reference
#include "iomgr.h"
Functions
NTSTATUS IopCheckUnloadDriver (IN PDRIVER_OBJECT driverObject, OUT PBOOLEAN unloadDriver)
NTSTATUS IopUnloadDriver (IN PUNICODE_STRING DriverServiceName, IN BOOLEAN InvokedByPnpMgr)
NTSTATUS NtLoadDriver (__in PUNICODE_STRING DriverServiceName)
NTSTATUS NtUnloadDriver (__in PUNICODE_STRING DriverServiceName)
Function Documentation
NTSTATUS IopCheckUnloadDriver (IN PDRIVER_OBJECT driverObject, OUT PBOOLEAN unloadDriver)
Definition at line 175 of file loadunld.c.
References DOE_UNLOAD_PENDING, DRVO_BASE_FILESYSTEM_DRIVER, DRVO_UNLOAD_INVOKED, FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, ObDereferenceObject(), STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by IopUnloadDriver().
NTSTATUS IopUnloadDriver (IN PUNICODE_STRING DriverServiceName, IN BOOLEAN InvokedByPnpMgr)
Definition at line 255 of file loadunld.c.
References _UNICODE_STRING::Buffer, DelayedWorkQueue, _LOAD_PACKET::DriverObject, _DRIVER_OBJECT::DriverSection, _DRIVER_OBJECT::DriverUnload, _LOAD_PACKET::Event, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), FALSE, FILE_READ_DATA, InitializeObjectAttributes, IoDriverObjectType, IopCheckUnloadDriver(), IopGetDriverNameFromKeyNode(), IopIsLegacyDriver(), IopLoadUnloadDriver(), IopOpenRegistryKey(), KeGetPreviousMode, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), KEY_READ, _UNICODE_STRING::Length, NotificationEvent, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObMakeTemporaryObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, PsGetCurrentProcess(), PsInitialSystemProcess, RtlCopyMemory, SeLoadDriverPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, VOID, _LOAD_PACKET::WorkQueueItem, and ZwUnloadDriver().
Referenced by NtUnloadDriver().
NTSTATUS NtLoadDriver (__in PUNICODE_STRING DriverServiceName)
Definition at line 27 of file loadunld.c.
References _UNICODE_STRING::Buffer, DelayedWorkQueue, _LOAD_PACKET::DriverObject, _LOAD_PACKET::DriverServiceName, _LOAD_PACKET::Event, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), FALSE, _LOAD_PACKET::FinalStatus, IopLoadUnloadDriver(), KeGetPreviousModeByThread, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, NotificationEvent, NULL, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, RtlCopyMemory, SeLoadDriverPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, _ETHREAD::Tcb, UserRequest, and _LOAD_PACKET::WorkQueueItem.
NTSTATUS NtUnloadDriver (__in PUNICODE_STRING DriverServiceName)
Definition at line 247 of file loadunld.c.
References FALSE, and IopUnloadDriver().