Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/objsup.c File Reference
objsup.c File Reference
#include "iomgr.h"
Functions
VOID IopCloseFile (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ULONG GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID IopDeleteDevice (IN PVOID Object)
VOID IopDeleteDriver (IN PVOID Object)
VOID IopDeleteFile (IN PVOID Object)
PDEVICE_OBJECT IopGetDevicePDO (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopGetSetSecurityObject (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS IopSetDeviceSecurityDescriptor (IN PDEVICE_OBJECT DeviceObject, IN PSECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS IopSetDeviceSecurityDescriptors (IN PDEVICE_OBJECT OriginalDeviceObject, IN PDEVICE_OBJECT DeviceObject, IN PSECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Function Documentation
VOID IopCloseFile (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ULONG GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 51 of file objsup.c.
References APC_LEVEL, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, FALSE, _FAST_IO_DISPATCH::FastIoUnlockAll, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_DIRECT_DEVICE_OPEN, FO_HANDLE_CREATED, FO_SYNCHRONOUS_IO, IoCallDriver(), IoFreeIrp(), IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpMustSucceed(), IopDequeueThreadIrp, IopQueueThreadIrp(), IopReleaseFileObjectLock, IopUpdateOtherOperationCount(), IRP_CLOSE_OPERATION, IRP_MJ_CLEANUP, IRP_MJ_LOCK_CONTROL, IRP_MN_UNLOCK_ALL, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _FILE_OBJECT::LockOperation, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NOTHING, NULL, ObReferenceObject, PAGED_CODE, PIRP, PsGetCurrentProcess(), PsGetCurrentThread(), STATUS_PENDING, SynchronizationEvent, UNREFERENCED_PARAMETER, UserRequest, and VOID.
Referenced by IopCreateObjectTypes(), and IopDeleteFile().
VOID IopDeleteDevice (IN PVOID Object)
Definition at line 824 of file objsup.c.
References ASSERT, ASSERTMSG, ExFreePool(), _VPB::Flags, InterlockedExchangePointer, IopDestroyDeviceNode(), NULL, ObDereferenceObject(), PAGED_CODE, _VPB::ReferenceCount, VPB_LOCKED, and VPB_MOUNTED.
Referenced by IopCreateObjectTypes().
VOID IopDeleteDriver (IN PVOID Object)
Definition at line 738 of file objsup.c.
References ASSERT, _UNICODE_STRING::Buffer, _DRIVER_EXTENSION::ClientDriverExtension, _DRIVER_OBJECT::DeviceObject, _DRIVER_OBJECT::DriverExtension, _DRIVER_OBJECT::DriverName, _DRIVER_OBJECT::DriverSection, ExFreePool(), _DRIVER_EXTENSION::FsFilterCallbacks, KeFlushQueuedDpcs(), MmUnloadSystemImage(), _IO_CLIENT_EXTENSION::NextExtension, NULL, PAGED_CODE, PpDriverObjectDereferenceComplete(), and _DRIVER_EXTENSION::ServiceKeyName.
Referenced by IopCreateObjectTypes().
VOID IopDeleteFile (IN PVOID Object)
Definition at line 435 of file objsup.c.
References APC_LEVEL, ASSERT, _UNICODE_STRING::Buffer, _FILE_OBJECT::Busy, _FILE_OBJECT::CompletionContext, _VPB::DeviceObject, _FILE_OBJECT::DeviceObject, DO_NEVER_LAST_DEVICE, _FILE_OBJECT::Event, Executive, ExFreePool(), FALSE, _FILE_OBJECT::FileName, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, FO_DIRECT_DEVICE_OPEN, FO_FILE_OBJECT_HAS_EXTENSION, FO_FILE_OPEN_CANCELLED, FO_HANDLE_CREATED, FO_SYNCHRONOUS_IO, FsRtlPTeardownPerFileObjectContexts(), InterlockedExchange(), IoAllocateIrp(), IoCallDriver(), IoFreeIrp(), IoGetAttachedDevice(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAllocateIrpMustSucceed(), IopCloseFile(), IopDecrementDeviceObjectRef(), IopDequeueThreadIrp, IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopQueueThreadIrp(), IRP_CLOSE_OPERATION, IRP_MJ_CLOSE, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, LockQueueIoDatabaseLock, LockQueueIoVpbLock, _IO_STACK_LOCATION::MajorFunction, NULL, ObDereferenceObject(), ObIsObjectDeletionInline(), PIRP, _IO_COMPLETION_CONTEXT::Port, PsGetCurrentThread(), _VPB::ReferenceCount, STATUS_PENDING, SynchronizationEvent, TRUE, VOID, and _FILE_OBJECT::Vpb.
Referenced by IopCreateObjectTypes(), and IopParseDevice().
PDEVICE_OBJECT IopGetDevicePDO (IN PDEVICE_OBJECT DeviceObject)
Definition at line 877 of file objsup.c.
References ASSERT, DO_BUS_ENUMERATED_DEVICE, IopGetDeviceAttachmentBase(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and ObReferenceObject.
Referenced by IopGetSetSecurityObject().
NTSTATUS IopGetSetSecurityObject (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 1167 of file objsup.c.
References AssignSecurityDescriptor, DeleteSecurityDescriptor, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExReleaseResourceLite(), FALSE, _FILE_OBJECT::FileName, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::FinalStatus, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_DIRECT_DEVICE_OPEN, FO_STREAM_FILE, FO_SYNCHRONOUS_IO, _IO_STATUS_BLOCK::Information, IO_TYPE_DEVICE, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopGetDevicePDO(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IopSecurityResource, IopSetDeviceSecurityDescriptor(), IopSetDeviceSecurityDescriptors(), IopUpdateOtherOperationCount(), IRP_MJ_QUERY_SECURITY, IRP_MJ_SET_SECURITY, IRP_SYNCHRONOUS_API, KeClearEvent(), KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeWaitForSingleObject(), _UNICODE_STRING::Length, _IO_STACK_LOCATION::MajorFunction, NT_SUCCESS, NULL, ObDereferenceObject(), ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), ObReferenceObject, ObReferenceSecurityDescriptor(), PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), QuerySecurityDescriptor, _FILE_OBJECT::RelatedFileObject, SeAssignWorldSecurityDescriptor(), SeQuerySecurityDescriptorInfo(), SetSecurityDescriptor, _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_PENDING, STATUS_SUCCESS, SynchronizationEvent, _ETHREAD::Tcb, TRUE, UNREFERENCED_PARAMETER, and VOID.
Referenced by IopCreateObjectTypes().
NTSTATUS IopSetDeviceSecurityDescriptor (IN PDEVICE_OBJECT DeviceObject, IN PSECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 923 of file objsup.c.
References ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExFreePool(), ExReleaseResourceLite(), IopSecurityResource, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NT_SUCCESS, NULL, ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), ObReferenceSecurityDescriptor(), PAGED_CODE, SeSetSecurityDescriptorInfo(), Status, and TRUE.
Referenced by IopGetSetSecurityObject(), and IopSetDeviceSecurityDescriptors().
NTSTATUS IopSetDeviceSecurityDescriptors (IN PDEVICE_OBJECT OriginalDeviceObject, IN PDEVICE_OBJECT DeviceObject, IN PSECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 1063 of file objsup.c.
References ASSERT, IopSetDeviceSecurityDescriptor(), NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, and STATUS_SUCCESS.
Referenced by IopGetSetSecurityObject().