Windows Research Kernel v1.2: C:/Windows Research Kernel/raw/strucsup.c File Reference
strucsup.c File Reference
#include "RawProcs.h"
Functions
BOOLEAN RawCheckForDismount (PVCB Vcb, BOOLEAN CalledFromCreate)
NTSTATUS RawInitializeVcb (IN OUT PVCB Vcb, IN PDEVICE_OBJECT TargetDeviceObject, IN PVPB Vpb)
Function Documentation
BOOLEAN RawCheckForDismount (PVCB Vcb, BOOLEAN CalledFromCreate)
Definition at line 111 of file strucsup.c.
References ASSERT, CONTAINING_RECORD, _VPB::DeviceObject, ExFreePool(), FALSE, FlagOn, _VPB::Flags, IO_TYPE_VPB, IoAcquireVpbSpinLock(), IoDeleteDevice(), IoReleaseVpbSpinLock(), KeReadStateMutant(), KeReleaseMutex(), _VCB::Mutex, NULL, ObDereferenceObject(), _VPB::RealDevice, _VPB::ReferenceCount, RtlZeroMemory, _VPB::Size, _VCB::SpareVpb, _VCB::TargetDeviceObject, TRUE, _VPB::Type, VCB_STATE_FLAG_DISMOUNTED, _VCB::VcbState, VOID, _VCB::Vpb, VPB_MOUNTED, VPB_PERSISTENT, and VPB_REMOVE_PENDING.
Referenced by RawCleanup(), RawClose(), RawCreate(), and RawVerifyVolume().
NTSTATUS RawInitializeVcb (IN OUT PVCB Vcb, IN PDEVICE_OBJECT TargetDeviceObject, IN PVPB Vpb)
Definition at line 28 of file strucsup.c.
References ExAllocatePoolWithTag, KeInitializeMutex(), MUTEX_LEVEL_FILESYSTEM_RAW_VCB, NonPagedPool, NULL, PAGED_CODE, RAW_NTC_VCB, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by RawMountVolume().