Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/dev2dos.c File Reference
dev2dos.c File Reference
#include <iomgr.h>
#include <mountdev.h>
Functions
NTSTATUS IoVolumeDeviceToDosName (IN PVOID VolumeDeviceObject, OUT PUNICODE_STRING DosName)
Function Documentation
NTSTATUS IoVolumeDeviceToDosName (IN PVOID VolumeDeviceObject, OUT PUNICODE_STRING DosName)
Definition at line 40 of file dev2dos.c.
References ASSERT, ExAllocatePool, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTDEV_QUERY_DEVICE_NAME, IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH, IoGetDeviceObjectPointer(), KeGetCurrentIrql(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), MAXUSHORT, MOUNTMGR_DEVICE_NAME, _MOUNTMGR_VOLUME_PATHS::MultiSz, _MOUNTMGR_VOLUME_PATHS::MultiSzLength, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PagedPool, PASSIVE_LEVEL, PIRP, RtlCopyMemory, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_BUFFER_SIZE, STATUS_PENDING, and STATUS_SUCCESS.
Referenced by IopQueryNameInternal().