Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/probe.c File Reference
probe.c File Reference
#include "exp.h"
Macros
#define PageSize PAGE_SIZE
Functions
VOID ProbeForRead (__in CONST VOID *Address, __in SIZE_T Length, __in ULONG Alignment)
VOID ProbeForRead (__in_bcount(Length) VOID *Address, __in SIZE_T Length, __in ULONG Alignment)
VOID ProbeForWrite (__inout_bcount(Length) PVOID Address, __in SIZE_T Length, __in ULONG Alignment)
Macro Definition Documentation
#define PageSize PAGE_SIZE
Referenced by MiCheckForUserStackOverflow(), MiClearStackGuardBits(), and ProbeForWrite().
Function Documentation
VOID ProbeForRead (__in CONST VOID * Address, __in SIZE_T Length, __in ULONG Alignment)
VOID ProbeForRead (__in_bcount(Length) VOID * Address, __in SIZE_T Length, __in ULONG Alignment)
Definition at line 136 of file probe.c.
References ASSERT, ExRaiseDatatypeMisalignment(), MM_USER_PROBE_ADDRESS, and PAGED_CODE.
VOID ProbeForWrite (__inout_bcount(Length) PVOID Address, __in SIZE_T Length, __in ULONG Alignment)
Definition at line 40 of file probe.c.
References ASSERT, ExRaiseAccessViolation(), ExRaiseDatatypeMisalignment(), MM_USER_PROBE_ADDRESS, and PageSize.
Referenced by BuildQueryDirectoryIrp(), ExpGetSystemFirmwareTableInformation(), IopXxxControlFile(), KeUserModeCallback(), KiDispatchException(), KiInitializeUserApc(), LpcpCopyRequestData(), MiDoMappedCopy(), MiDoPoolCopy(), MiSecureVirtualMemory(), NtAdjustGroupsToken(), NtAdjustPrivilegesToken(), NtAllocateUserPhysicalPages(), NtCreateProfile(), NtEnumerateKey(), NtEnumerateValueKey(), NtGetWriteWatch(), NtNotifyChangeDirectoryFile(), NtNotifyChangeMultipleKeys(), NtPrivilegeCheck(), NtQueryDirectoryObject(), NtQueryEaFile(), NtQueryEvent(), NtQueryInformationAtom(), NtQueryInformationFile(), NtQueryInformationPort(), NtQueryInformationToken(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryObject(), NtQueryOpenSubKeysEx(), NtQueryQuotaInformationFile(), NtQuerySection(), NtQuerySecurityObject(), NtQuerySymbolicLinkObject(), NtQuerySystemInformation(), NtQueryVirtualMemory(), NtQueryVolumeInformationFile(), NtReadFile(), NtSecureConnectPort(), ProbeForWriteSmallStructure(), SeAccessCheckByType(), SepAccessCheckAndAuditAlarm(), WmipNtDllLoggerInfo(), WmipQueryLogger(), and WmipStartLogger().