Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/ldrrsrc.c File Reference
ldrrsrc.c File Reference
#include "ntrtlp.h"
Macros
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
#define DPFLTR_LEVEL_STATUS(x)
#define IS_INTRESOURCE(_r) (((ULONG_PTR)(_r) >> 16) == 0)
#define ISOLATIONAWARE_MANIFEST_RESOURCE_ID 2
#define LDRP_MIN(x, y) (((x)<(y)) ? (x) : (y))
#define MAXIMUM_RESERVED_MANIFEST_RESOURCE_ID 16
#define MINIMUM_RESERVED_MANIFEST_RESOURCE_ID 1
#define RT_MANIFEST 24
#define RT_VERSION 16
#define USE_FIRSTAVAILABLE_LANGID (0xFFFFFFFF & ~LDR_RESOURCE_ID_NAME_MASK)
#define USE_RC_CHECKSUM
Functions
NTSTATUS LdrAccessResource (IN PVOID DllHandle, IN const IMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
NTSTATUS LdrEnumResources (IN PVOID DllHandle, IN const ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, IN OUT PULONG NumberOfResources, OUT PLDR_ENUM_RESOURCE_ENTRY Resources OPTIONAL)
NTSTATUS LdrFindEntryForAddress (IN PVOID Address, OUT PLDR_DATA_TABLE_ENTRY *TableEntry)
NTSTATUS LdrFindResource_U (IN PVOID DllHandle, IN const ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry)
NTSTATUS LdrFindResourceDirectory_U (IN PVOID DllHandle, IN const ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DIRECTORY *ResourceDirectory)
NTSTATUS LdrFindResourceEx_U (IN ULONG Flags, IN PVOID DllHandle, IN const ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry)
NTSTATUS LdrpAccessResourceData (IN PVOID DllHandle, IN const IMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
NTSTATUS LdrpAccessResourceDataNoMultipleLanguage (IN PVOID DllHandle, IN const IMAGE_RESOURCE_DATA_ENTRY *ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
LONG LdrpCompareResourceNames_U (IN ULONG_PTR ResourceName, IN const IMAGE_RESOURCE_DIRECTORY *ResourceDirectory, IN const IMAGE_RESOURCE_DIRECTORY_ENTRY *ResourceDirectoryEntry)
NTSTATUS LdrpSearchResourceSection_U (IN PVOID DllHandle, IN const ULONG_PTR *ResourceIdPath, IN ULONG ResourceIdPathLength, IN ULONG Flags, OUT PVOID *ResourceDirectoryOrData)
Macro Definition Documentation
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
Definition at line 40 of file ldrrsrc.c.
#define DPFLTR_LEVEL_STATUS (x)
Value:
((NT_SUCCESS(x) \
                                    || (x) == STATUS_OBJECT_NAME_NOT_FOUND    \
                                    || (x) == STATUS_RESOURCE_DATA_NOT_FOUND  \
                                    || (x) == STATUS_RESOURCE_TYPE_NOT_FOUND  \
                                    || (x) == STATUS_RESOURCE_NAME_NOT_FOUND  \
                                    ) \
                                ? DPFLTR_TRACE_LEVEL : DPFLTR_WARNING_LEVEL)
Definition at line 47 of file ldrrsrc.c.
Referenced by LdrAccessResource(), LdrFindEntryForAddress(), LdrpAccessResourceData(), and LdrpAccessResourceDataNoMultipleLanguage().
#define IS_INTRESOURCE (_r) (((ULONG_PTR)(_r) >> 16) == 0)
Definition at line 37 of file ldrrsrc.c.
#define ISOLATIONAWARE_MANIFEST_RESOURCE_ID 2
Definition at line 41 of file ldrrsrc.c.
#define LDRP_MIN (x, y) (((x)<(y)) ? (x) : (y))
Definition at line 45 of file ldrrsrc.c.
#define MAXIMUM_RESERVED_MANIFEST_RESOURCE_ID 16
Definition at line 43 of file ldrrsrc.c.
#define MINIMUM_RESERVED_MANIFEST_RESOURCE_ID 1
Definition at line 42 of file ldrrsrc.c.
#define RT_MANIFEST 24
Definition at line 39 of file ldrrsrc.c.
#define RT_VERSION 16
Definition at line 38 of file ldrrsrc.c.
#define USE_FIRSTAVAILABLE_LANGID (0xFFFFFFFF & ~LDR_RESOURCE_ID_NAME_MASK)
Definition at line 586 of file ldrrsrc.c.
Referenced by LdrpSearchResourceSection_U().
#define USE_RC_CHECKSUM
Definition at line 34 of file ldrrsrc.c.
Function Documentation
NTSTATUS LdrAccessResource (IN PVOID DllHandle, IN const IMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
Definition at line 56 of file ldrrsrc.c.
References DPFLTR_LDR_ID, DPFLTR_LEVEL_STATUS, KdPrintEx, LdrpAccessResourceData(), NT_SUCCESS, RTL_PAGED_CODE, and Status.
NTSTATUS LdrEnumResources (IN PVOID DllHandle, IN const ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, IN OUT PULONG NumberOfResources, OUT PLDR_ENUM_RESOURCE_ENTRY Resources OPTIONAL)
Definition at line 920 of file ldrrsrc.c.
References ARGUMENT_PRESENT, _LDR_ENUM_RESOURCE_ENTRY::Data, _IMAGE_RESOURCE_DIRECTORY_ENTRY::DataIsDirectory, _IMAGE_RESOURCE_DIRECTORY_ENTRY::Id, IMAGE_DIRECTORY_ENTRY_RESOURCE, LdrpCompareResourceNames_U(), _IMAGE_RESOURCE_DIRECTORY_ENTRY::NameIsString, _IMAGE_RESOURCE_DIRECTORY_ENTRY::NameOffset, _LDR_ENUM_RESOURCE_ENTRY::NameOrId, _IMAGE_RESOURCE_DIRECTORY::NumberOfIdEntries, _IMAGE_RESOURCE_DIRECTORY::NumberOfNamedEntries, _IMAGE_RESOURCE_DIRECTORY_ENTRY::OffsetToData, _IMAGE_RESOURCE_DATA_ENTRY::OffsetToData, _IMAGE_RESOURCE_DIRECTORY_ENTRY::OffsetToDirectory, _LDR_ENUM_RESOURCE_ENTRY::Path, _LDR_ENUM_RESOURCE_ENTRY::Reserved, RtlImageDirectoryEntryToData(), _LDR_ENUM_RESOURCE_ENTRY::Size, _IMAGE_RESOURCE_DATA_ENTRY::Size, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_IMAGE_FORMAT, STATUS_RESOURCE_DATA_NOT_FOUND, STATUS_SUCCESS, and TRUE.
NTSTATUS LdrFindEntryForAddress (IN PVOID Address, OUT PLDR_DATA_TABLE_ENTRY * TableEntry)
Definition at line 294 of file ldrrsrc.c.
References CONTAINING_RECORD, _LDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_LDR_ID, DPFLTR_LEVEL_STATUS, _PEB_LDR_DATA::EntryInProgress, _LIST_ENTRY::Flink, _PEB_LDR_DATA::InMemoryOrderModuleList, KdPrintEx, NT_SUCCESS, NtCurrentPeb, NULL, _IMAGE_NT_HEADERS::OptionalHeader, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SizeOfImage, Status, STATUS_NO_MORE_ENTRIES, and STATUS_SUCCESS.
NTSTATUS LdrFindResource_U (IN PVOID DllHandle, IN const ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry)
Definition at line 382 of file ldrrsrc.c.
References LdrpSearchResourceSection_U(), and RTL_PAGED_CODE.
NTSTATUS LdrFindResourceDirectory_U (IN PVOID DllHandle, IN const ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DIRECTORY * ResourceDirectory)
Definition at line 494 of file ldrrsrc.c.
References LDRP_FIND_RESOURCE_DIRECTORY, LdrpSearchResourceSection_U(), and RTL_PAGED_CODE.
NTSTATUS LdrFindResourceEx_U (IN ULONG Flags, IN PVOID DllHandle, IN const ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, OUT PIMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry)
Definition at line 430 of file ldrrsrc.c.
References LdrpSearchResourceSection_U(), and RTL_PAGED_CODE.
NTSTATUS LdrpAccessResourceData (IN PVOID DllHandle, IN const IMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
Definition at line 238 of file ldrrsrc.c.
References DPFLTR_LDR_ID, DPFLTR_LEVEL_STATUS, KdPrintEx, LdrpAccessResourceDataNoMultipleLanguage(), NT_SUCCESS, RTL_PAGED_CODE, Status, and STATUS_SUCCESS.
Referenced by LdrAccessResource(), and RtlFindMessage().
NTSTATUS LdrpAccessResourceDataNoMultipleLanguage (IN PVOID DllHandle, IN const IMAGE_RESOURCE_DATA_ENTRY * ResourceDataEntry, OUT PVOID *Address OPTIONAL, OUT PULONG Size OPTIONAL)
Definition at line 110 of file ldrrsrc.c.
References ARGUMENT_PRESENT, DPFLTR_LDR_ID, DPFLTR_LEVEL_STATUS, except, EXCEPTION_EXECUTE_HANDLER, IMAGE_DIRECTORY_ENTRY_RESOURCE, IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_NT_OPTIONAL_HDR64_MAGIC, KdPrintEx, LDR_DATAFILE_TO_VIEW, LDR_IS_DATAFILE, _IMAGE_OPTIONAL_HEADER::Magic, _IMAGE_SECTION_HEADER::Misc, NT_SUCCESS, _IMAGE_NT_HEADERS::OptionalHeader, RTL_PAGED_CODE, RtlAddressInSectionTable(), RtlImageDirectoryEntryToData(), RtlImageNtHeader(), RtlSectionTableFromVirtualAddress(), Status, STATUS_RESOURCE_DATA_NOT_FOUND, STATUS_SUCCESS, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by LdrpAccessResourceData().
LONG LdrpCompareResourceNames_U (IN ULONG_PTR ResourceName, IN const IMAGE_RESOURCE_DIRECTORY * ResourceDirectory, IN const IMAGE_RESOURCE_DIRECTORY_ENTRY * ResourceDirectoryEntry)
Definition at line 543 of file ldrrsrc.c.
References LDR_RESOURCE_ID_NAME_MASK, _IMAGE_RESOURCE_DIR_STRING_U::Length, _IMAGE_RESOURCE_DIR_STRING_U::NameString, wcslen(), and wcsncmp().
Referenced by LdrEnumResources(), and LdrpSearchResourceSection_U().
NTSTATUS LdrpSearchResourceSection_U (IN PVOID DllHandle, IN const ULONG_PTR * ResourceIdPath, IN ULONG ResourceIdPathLength, IN ULONG Flags, OUT PVOID * ResourceDirectoryOrData)
Definition at line 589 of file ldrrsrc.c.
References _IMAGE_RESOURCE_DIRECTORY_ENTRY::DataIsDirectory, except, EXCEPTION_EXECUTE_HANDLER, FALSE, IMAGE_DIRECTORY_ENTRY_RESOURCE, LANG_ENGLISH, LANG_NEUTRAL, LANGIDFROMLCID, LDR_RESOURCE_ID_NAME_MASK, LDRP_FIND_RESOURCE_DIRECTORY, LdrpCompareResourceNames_U(), MAKELANGID, _IMAGE_RESOURCE_DIRECTORY_ENTRY::Name, NULL, _IMAGE_RESOURCE_DIRECTORY::NumberOfIdEntries, _IMAGE_RESOURCE_DIRECTORY::NumberOfNamedEntries, _IMAGE_RESOURCE_DIRECTORY_ENTRY::OffsetToData, _IMAGE_RESOURCE_DIRECTORY_ENTRY::OffsetToDirectory, PRIMARYLANGID, PsDefaultSystemLocaleId, PsInstallUILanguageId, RTL_PAGED_CODE, RtlImageDirectoryEntryToData(), Status, STATUS_INVALID_PARAMETER, STATUS_RESOURCE_DATA_NOT_FOUND, STATUS_RESOURCE_LANG_NOT_FOUND, STATUS_RESOURCE_NAME_NOT_FOUND, STATUS_RESOURCE_TYPE_NOT_FOUND, STATUS_SUCCESS, SUBLANG_ENGLISH_US, TRUE, and USE_FIRSTAVAILABLE_LANGID.
Referenced by LdrFindResource_U(), LdrFindResourceDirectory_U(), LdrFindResourceEx_U(), and RtlFindMessage().