Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmgquota.c File Reference
cmgquota.c File Reference
#include "cmp.h"
Data Structures
struct CM_SELF_HEAL_WORK_ITEM_PARAMETER
Macros
#define _200MB (200 *1024 * 1024)
#define CM_DEFAULT_RATIO (3)
#define CM_LIMIT_RATIO(x) ((x / 10) * 8)
#define CM_MINIMUM_GLOBAL_QUOTA (16 *1024 * 1024)
#define CM_REGISTRY_WARNING_LEVEL (95)
#define CM_SYSTEM_HIVE_LIMIT_SIZE (min(MmNumberOfPhysicalPages / 4, _200MB >> PAGE_SHIFT) * PAGE_SIZE)
#define CM_SYSTEM_HIVE_WARNING_SIZE ((CM_SYSTEM_HIVE_LIMIT_SIZE*9)/10)
#define LOCK_SELF_HEAL_QUEUE() KeAcquireGuardedMutex(&CmpSelfHealQueueLock)
#define UNLOCK_SELF_HEAL_QUEUE() KeReleaseGuardedMutex(&CmpSelfHealQueueLock)
Typedefs
typedef struct CM_SELF_HEAL_WORK_ITEM_PARAMETER * PCM_SELF_HEAL_WORK_ITEM_PARAMETER
Functions
BOOLEAN CmpCanGrowSystemHive (IN PHHIVE Hive, IN ULONG NewLength)
BOOLEAN CmpClaimGlobalQuota (IN ULONG Size)
VOID CmpComputeGlobalQuotaAllowed (VOID)
VOID CmpHysteresisTest (PVOID Ref, ULONG Level)
VOID CmpQuotaWarningWorker (IN PVOID WorkItem)
VOID CmpRaiseSelfHealWarning (IN PUNICODE_STRING HiveName)
VOID CmpRaiseSelfHealWarningForSystemHives ()
VOID CmpRaiseSelfHealWarningWorker (IN PVOID Arg)
VOID CmpReleaseGlobalQuota (IN ULONG Size)
VOID CmpSetGlobalQuotaAllowed (VOID)
VOID CmpSystemHiveHysteresisWorker (IN PVOID WorkItem)
VOID CmpSystemQuotaWarningWorker (IN PVOID WorkItem)
VOID CmpUpdateSystemHiveHysteresis (PHHIVE Hive, ULONG NewLength, ULONG OldLength)
VOID CmQueryRegistryQuotaInformation (__inout PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
ULONG CmRegisterSystemHiveLimitCallback (__in ULONG Low, __in ULONG High, __in PVOID Ref, __in PCM_HYSTERESIS_CALLBACK Callback)
VOID CmSetRegistryQuotaInformation (__in PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
Variables
SIZE_T CmpGlobalQuota
SIZE_T CmpGlobalQuotaAllowed
SIZE_T CmpGlobalQuotaUsed
SIZE_T CmpGlobalQuotaWarning
HIVE_LIST_ENTRY CmpMachineHiveList []
BOOLEAN CmpQuotaWarningPopupDisplayed
LIST_ENTRY CmpSelfHealQueueListHead
KGUARDED_MUTEX CmpSelfHealQueueLock
BOOLEAN CmpSelfHealWorkerActive = FALSE
PCM_HYSTERESIS_CALLBACK CmpSystemHiveHysteresisCallback = NULL
PVOID CmpSystemHiveHysteresisContext = NULL
ULONG CmpSystemHiveHysteresisHigh = 0
BOOLEAN CmpSystemHiveHysteresisHighSeen = FALSE
ULONG CmpSystemHiveHysteresisHitRatio = 0
ULONG CmpSystemHiveHysteresisLow = 0
BOOLEAN CmpSystemHiveHysteresisLowSeen = FALSE
BOOLEAN CmpSystemQuotaWarningPopupDisplayed
ULONG CmRegistrySizeLimit
ULONG CmRegistrySizeLimitLength
ULONG CmRegistrySizeLimitType
SIZE_T MmSizeOfPagedPoolInBytes
Macro Definition Documentation
#define _200MB (200 *1024 * 1024)
Definition at line 86 of file cmgquota.c.
#define CM_DEFAULT_RATIO (3)
Definition at line 67 of file cmgquota.c.
Referenced by CmpComputeGlobalQuotaAllowed().
#define CM_LIMIT_RATIO (x) ((x / 10) * 8)
Definition at line 68 of file cmgquota.c.
Referenced by CmpComputeGlobalQuotaAllowed().
#define CM_MINIMUM_GLOBAL_QUOTA (16 *1024 * 1024)
Definition at line 69 of file cmgquota.c.
Referenced by CmpComputeGlobalQuotaAllowed(), and CmSetRegistryQuotaInformation().
#define CM_REGISTRY_WARNING_LEVEL (95)
Definition at line 75 of file cmgquota.c.
Referenced by CmpComputeGlobalQuotaAllowed(), and CmSetRegistryQuotaInformation().
#define CM_SYSTEM_HIVE_LIMIT_SIZE (min(MmNumberOfPhysicalPages / 4, _200MB >> PAGE_SHIFT) * PAGE_SIZE)
Definition at line 89 of file cmgquota.c.
Referenced by CmpCanGrowSystemHive(), CmpUpdateSystemHiveHysteresis(), and CmRegisterSystemHiveLimitCallback().
#define CM_SYSTEM_HIVE_WARNING_SIZE ((CM_SYSTEM_HIVE_LIMIT_SIZE*9)/10)
Definition at line 94 of file cmgquota.c.
Referenced by CmpCanGrowSystemHive().
#define LOCK_SELF_HEAL_QUEUE () KeAcquireGuardedMutex(&CmpSelfHealQueueLock)
Definition at line 697 of file cmgquota.c.
Referenced by CmpRaiseSelfHealWarning(), and CmpRaiseSelfHealWarningWorker().
#define UNLOCK_SELF_HEAL_QUEUE () KeReleaseGuardedMutex(&CmpSelfHealQueueLock)
Definition at line 698 of file cmgquota.c.
Referenced by CmpRaiseSelfHealWarning(), and CmpRaiseSelfHealWarningWorker().
Typedef Documentation
typedef struct CM_SELF_HEAL_WORK_ITEM_PARAMETER * PCM_SELF_HEAL_WORK_ITEM_PARAMETER
Function Documentation
BOOLEAN CmpCanGrowSystemHive (IN PHHIVE Hive, IN ULONG NewLength)
Definition at line 382 of file cmgquota.c.
References CM_SYSTEM_HIVE_LIMIT_SIZE, CM_SYSTEM_HIVE_WARNING_SIZE, CmpSystemQuotaWarningPopupDisplayed, CmpSystemQuotaWarningWorker(), CONTAINING_RECORD, DelayedWorkQueue, ExAllocatePool, ExInitializeWorkItem, ExQueueWorkItem(), ExReadyForErrors, FALSE, HBLOCK_SIZE, NonPagedPool, NULL, PAGED_CODE, SYSTEM_HIVE_INDEX, and TRUE.
Referenced by HvpAddBin().
BOOLEAN CmpClaimGlobalQuota (IN ULONG Size)
Definition at line 240 of file cmgquota.c.
References CmpGlobalQuotaUsed, InterlockedExchangeAdd(), and TRUE.
Referenced by CmpAllocate().
VOID CmpComputeGlobalQuotaAllowed (VOID)
Definition at line 298 of file cmgquota.c.
References CM_DEFAULT_RATIO, CM_LIMIT_RATIO, CM_MINIMUM_GLOBAL_QUOTA, CM_REGISTRY_WARNING_LEVEL, CM_WRAP_LIMIT, CmpGlobalQuota, CmpGlobalQuotaWarning, CmRegistrySizeLimit, CmRegistrySizeLimitLength, CmRegistrySizeLimitType, MmSizeOfPagedPoolInBytes, and REG_DWORD.
Referenced by CmInitSystem1().
VOID CmpHysteresisTest (PVOID Ref, ULONG Level)
Definition at line 686 of file cmgquota.c.
References DbgPrint(), and UNREFERENCED_PARAMETER.
VOID CmpQuotaWarningWorker (IN PVOID WorkItem)
Definition at line 202 of file cmgquota.c.
References ExFreePool(), ExRaiseHardError(), NULL, OptionOk, Status, and STATUS_REGISTRY_QUOTA_LIMIT.
VOID CmpRaiseSelfHealWarning (IN PUNICODE_STRING HiveName)
Definition at line 757 of file cmgquota.c.
References _UNICODE_STRING::Buffer, CmpRaiseSelfHealWarningWorker(), CmpSelfHealWorkerActive, DelayedWorkQueue, ExAllocatePool, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), CM_SELF_HEAL_WORK_ITEM_PARAMETER::HiveName, InsertTailList(), _UNICODE_STRING::Length, LOCK_SELF_HEAL_QUEUE, _UNICODE_STRING::MaximumLength, NonPagedPool, NULL, PAGED_CODE, RtlCopyMemory, TRUE, UNLOCK_SELF_HEAL_QUEUE, and CM_SELF_HEAL_WORK_ITEM_PARAMETER::WorkItem.
Referenced by CmpInitHiveFromFile(), and CmpRaiseSelfHealWarningForSystemHives().
VOID CmpRaiseSelfHealWarningForSystemHives ()
Definition at line 819 of file cmgquota.c.
References CM_NUMBER_OF_MACHINE_HIVES, CmpRaiseSelfHealWarning(), HBOOT_SELFHEAL, HIVE_VOLATILE, PAGED_CODE, and RtlInitUnicodeString().
Referenced by NtInitializeRegistry().
VOID CmpRaiseSelfHealWarningWorker (IN PVOID Arg)
Definition at line 710 of file cmgquota.c.
References CmpSelfHealWorkerActive, CONTAINING_RECORD, DelayedWorkQueue, ExFreePool(), ExQueueWorkItem(), ExRaiseHardError(), FALSE, CM_SELF_HEAL_WORK_ITEM_PARAMETER::HiveName, IsListEmpty, LOCK_SELF_HEAL_QUEUE, OptionOk, RemoveHeadList(), STATUS_REGISTRY_HIVE_RECOVERED, TRUE, UNLOCK_SELF_HEAL_QUEUE, and CM_SELF_HEAL_WORK_ITEM_PARAMETER::WorkItem.
Referenced by CmpRaiseSelfHealWarning().
VOID CmpReleaseGlobalQuota (IN ULONG Size)
Definition at line 270 of file cmgquota.c.
References CM_BUGCHECK, CmpGlobalQuotaUsed, InterlockedExchangeAdd(), QUOTA_ERROR, and REGISTRY_ERROR.
Referenced by CmpAllocate(), CmpFree(), HvFreeHive(), and HvFreeHivePartial().
VOID CmpSetGlobalQuotaAllowed (VOID)
Definition at line 359 of file cmgquota.c.
References CmpGlobalQuota, and CmpGlobalQuotaAllowed.
Referenced by CmLoadKey(), CmpLoadHiveVolatile(), and CmRestoreKey().
VOID CmpSystemHiveHysteresisWorker (IN PVOID WorkItem)
Definition at line 495 of file cmgquota.c.
References CmpSystemHiveHysteresisCallback, CmpSystemHiveHysteresisContext, CmpSystemHiveHysteresisHitRatio, and ExFreePool().
Referenced by CmpUpdateSystemHiveHysteresis().
VOID CmpSystemQuotaWarningWorker (IN PVOID WorkItem)
Definition at line 447 of file cmgquota.c.
References ExFreePool(), ExRaiseHardError(), NULL, OptionOk, Status, and STATUS_REGISTRY_QUOTA_LIMIT.
Referenced by CmpCanGrowSystemHive().
VOID CmpUpdateSystemHiveHysteresis (PHHIVE Hive, ULONG NewLength, ULONG OldLength)
Definition at line 530 of file cmgquota.c.
References ASSERT, CM_SYSTEM_HIVE_LIMIT_SIZE, _HIVE_LIST_ENTRY::CmHive, CmpSystemHiveHysteresisCallback, CmpSystemHiveHysteresisHigh, CmpSystemHiveHysteresisHighSeen, CmpSystemHiveHysteresisHitRatio, CmpSystemHiveHysteresisLow, CmpSystemHiveHysteresisLowSeen, CmpSystemHiveHysteresisWorker(), CONTAINING_RECORD, DelayedWorkQueue, ExAllocatePool, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, HBLOCK_SIZE, NonPagedPool, NULL, PAGED_CODE, SYSTEM_HIVE_INDEX, and TRUE.
Referenced by CmCompressKey(), HvFreeHivePartial(), and HvpAddBin().
VOID CmQueryRegistryQuotaInformation (__inout PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
Definition at line 129 of file cmgquota.c.
References CmpGlobalQuota, CmpGlobalQuotaUsed, and MmSizeOfPagedPoolInBytes.
Referenced by NtQuerySystemInformation().
ULONG CmRegisterSystemHiveLimitCallback (__in ULONG Low, __in ULONG High, __in PVOID Ref, __in PCM_HYSTERESIS_CALLBACK Callback)
Definition at line 616 of file cmgquota.c.
References _HHIVE::BaseBlock, CM_SYSTEM_HIVE_LIMIT_SIZE, _HIVE_LIST_ENTRY::CmHive, CmpSystemHiveHysteresisCallback, CmpSystemHiveHysteresisContext, CmpSystemHiveHysteresisHigh, CmpSystemHiveHysteresisHighSeen, CmpSystemHiveHysteresisLow, CmpSystemHiveHysteresisLowSeen, FALSE, HBLOCK_SIZE, _CMHIVE::Hive, _HBASE_BLOCK::Length, NULL, PAGED_CODE, SYSTEM_HIVE_INDEX, and TRUE.
VOID CmSetRegistryQuotaInformation (__in PSYSTEM_REGISTRY_QUOTA_INFORMATION RegistryQuotaInformation)
Definition at line 158 of file cmgquota.c.
References CM_MINIMUM_GLOBAL_QUOTA, CM_REGISTRY_WARNING_LEVEL, CM_WRAP_LIMIT, CmpGlobalQuota, CmpGlobalQuotaAllowed, and CmpGlobalQuotaWarning.
Referenced by NtSetSystemInformation().
Variable Documentation
SIZE_T CmpGlobalQuota
Definition at line 43 of file cmdat2.c.
Referenced by CmpComputeGlobalQuotaAllowed(), CmpSetGlobalQuotaAllowed(), CmQueryRegistryQuotaInformation(), and CmSetRegistryQuotaInformation().
SIZE_T CmpGlobalQuotaAllowed
Definition at line 42 of file cmdat2.c.
Referenced by CmpSetGlobalQuotaAllowed(), and CmSetRegistryQuotaInformation().
SIZE_T CmpGlobalQuotaUsed
Definition at line 57 of file cmdat2.c.
Referenced by CmpClaimGlobalQuota(), CmpReleaseGlobalQuota(), and CmQueryRegistryQuotaInformation().
SIZE_T CmpGlobalQuotaWarning
Definition at line 44 of file cmdat2.c.
Referenced by CmpComputeGlobalQuotaAllowed(), and CmSetRegistryQuotaInformation().
HIVE_LIST_ENTRY CmpMachineHiveList[]
Definition at line 284 of file cmdat.c.
BOOLEAN CmpQuotaWarningPopupDisplayed
Definition at line 45 of file cmdat2.c.
LIST_ENTRY CmpSelfHealQueueListHead
Definition at line 693 of file cmgquota.c.
KGUARDED_MUTEX CmpSelfHealQueueLock
Definition at line 694 of file cmgquota.c.
BOOLEAN CmpSelfHealWorkerActive = FALSE
Definition at line 695 of file cmgquota.c.
Referenced by CmpRaiseSelfHealWarning(), and CmpRaiseSelfHealWarningWorker().
PCM_HYSTERESIS_CALLBACK CmpSystemHiveHysteresisCallback = NULL
Definition at line 489 of file cmgquota.c.
Referenced by CmpSystemHiveHysteresisWorker(), CmpUpdateSystemHiveHysteresis(), and CmRegisterSystemHiveLimitCallback().
PVOID CmpSystemHiveHysteresisContext = NULL
Definition at line 488 of file cmgquota.c.
Referenced by CmpSystemHiveHysteresisWorker(), and CmRegisterSystemHiveLimitCallback().
ULONG CmpSystemHiveHysteresisHigh = 0
Definition at line 487 of file cmgquota.c.
Referenced by CmpUpdateSystemHiveHysteresis(), and CmRegisterSystemHiveLimitCallback().
BOOLEAN CmpSystemHiveHysteresisHighSeen = FALSE
Definition at line 492 of file cmgquota.c.
Referenced by CmpUpdateSystemHiveHysteresis(), and CmRegisterSystemHiveLimitCallback().
ULONG CmpSystemHiveHysteresisHitRatio = 0
Definition at line 490 of file cmgquota.c.
Referenced by CmpSystemHiveHysteresisWorker(), and CmpUpdateSystemHiveHysteresis().
ULONG CmpSystemHiveHysteresisLow = 0
Definition at line 486 of file cmgquota.c.
Referenced by CmpUpdateSystemHiveHysteresis(), and CmRegisterSystemHiveLimitCallback().
BOOLEAN CmpSystemHiveHysteresisLowSeen = FALSE
Definition at line 491 of file cmgquota.c.
Referenced by CmpUpdateSystemHiveHysteresis(), and CmRegisterSystemHiveLimitCallback().
BOOLEAN CmpSystemQuotaWarningPopupDisplayed
Definition at line 46 of file cmdat2.c.
Referenced by CmpCanGrowSystemHive().
ULONG CmRegistrySizeLimit
Definition at line 33 of file cmdat2.c.
Referenced by CmpComputeGlobalQuotaAllowed().
ULONG CmRegistrySizeLimitLength
Definition at line 34 of file cmdat2.c.
Referenced by CmpComputeGlobalQuotaAllowed().
ULONG CmRegistrySizeLimitType
Definition at line 35 of file cmdat2.c.
Referenced by CmpComputeGlobalQuotaAllowed().
SIZE_T MmSizeOfPagedPoolInBytes
Definition at line 287 of file miglobal.c.
Referenced by CmpComputeGlobalQuotaAllowed(), CmQueryRegistryQuotaInformation(), MiBuildPagedPool(), MiFreePoolPages(), MiInitMachineDependent(), MmGetSizeOfBigPoolAllocation(), and MmInitSystem().