Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/amd64/stkwalk.c File Reference
stkwalk.c File Reference
#include "ntrtlp.h"
Functions
DECLSPEC_NOINLINE USHORT RtlCaptureStackBackTrace (IN ULONG FramesToSkip, IN ULONG FramesToCapture, OUT PVOID *BackTrace, OUT PULONG BackTraceHash OPTIONAL)
DECLSPEC_NOINLINE VOID RtlGetCallersAddress (OUT PVOID *CallersPc, OUT PVOID *CallersCallersPc)
PRUNTIME_FUNCTION RtlpConvertFunctionEntry (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase)
PRUNTIME_FUNCTION RtlpLookupFunctionEntryForStackWalks (IN ULONG64 ControlPc, OUT PULONG64 ImageBase)
DECLSPEC_NOINLINE ULONG RtlpWalkFrameChain (OUT PVOID *Callers, IN ULONG Count, IN ULONG Flags, IN ULONG FramesToSkip)
ULONG RtlpWalkFrameChainExceptionFilter (ULONG ExceptionCode, PVOID ExceptionRecord)
DECLSPEC_NOINLINE ULONG RtlWalkFrameChain (OUT PVOID *Callers, IN ULONG Count, IN ULONG Flags)
Variables
LONG RtlpStackWalksInProgress
Function Documentation
DECLSPEC_NOINLINE USHORT RtlCaptureStackBackTrace (IN ULONG FramesToSkip, IN ULONG FramesToCapture, OUT PVOID * BackTrace, OUT PULONG BackTraceHash OPTIONAL)
Definition at line 151 of file stkwalk.c.
References ARGUMENT_PRESENT, FALSE, Index, MAX_STACK_DEPTH, MmCanThreadFault(), PsGetCurrentThread(), PtrToUlong, and RtlWalkFrameChain().
DECLSPEC_NOINLINE VOID RtlGetCallersAddress (OUT PVOID * CallersPc, OUT PVOID * CallersCallersPc)
Definition at line 262 of file stkwalk.c.
References FALSE, MmCanThreadFault(), NULL, PsGetCurrentThread(), RtlCaptureContext(), RtlpGetStackLimits(), RtlpIsFrameInBounds(), RtlpLookupFunctionEntryForStackWalks(), RtlVirtualUnwind(), TRUE, and UNW_FLAG_NHANDLER.
Referenced by __bcount(), __out_bcount(), CmpAllocate(), CmpFree(), CmpLockRegistry(), CmpLockRegistryExclusive(), MmMapLockedPagesSpecifyCache(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
PRUNTIME_FUNCTION RtlpConvertFunctionEntry (IN PRUNTIME_FUNCTION FunctionEntry, IN ULONG64 ImageBase)
Definition at line 1794 of file exdsptch.c.
References NULL, and RUNTIME_FUNCTION_INDIRECT.
Referenced by RtlLookupFunctionEntry(), and RtlpLookupFunctionEntryForStackWalks().
PRUNTIME_FUNCTION RtlpLookupFunctionEntryForStackWalks (IN ULONG64 ControlPc, OUT PULONG64 ImageBase)
Definition at line 42 of file stkwalk.c.
References _RUNTIME_FUNCTION::EndAddress, Index, NULL, RtlLookupFunctionTable(), and RtlpConvertFunctionEntry().
Referenced by RtlGetCallersAddress(), and RtlpWalkFrameChain().
DECLSPEC_NOINLINE ULONG RtlpWalkFrameChain (OUT PVOID * Callers, IN ULONG Count, IN ULONG Flags, IN ULONG FramesToSkip)
Definition at line 409 of file stkwalk.c.
References except, FALSE, Index, InterlockedDecrement, InterlockedIncrement, MmGetSessionId(), MmIsAddressValid(), MmIsSessionAddress(), NULL, PsGetCurrentProcess(), RtlCaptureContext(), RtlpGetStackLimits(), RtlpIsFrameInBounds(), RtlpLookupFunctionEntryForStackWalks(), RtlpStackWalksInProgress, RtlpWalkFrameChainExceptionFilter(), RtlVirtualUnwind(), TRUE, and UNW_FLAG_NHANDLER.
Referenced by RtlWalkFrameChain().
ULONG RtlpWalkFrameChainExceptionFilter (ULONG ExceptionCode, PVOID ExceptionRecord)
Definition at line 922 of file stktrace.c.
Referenced by RtlpWalkFrameChain().
DECLSPEC_NOINLINE ULONG RtlWalkFrameChain (OUT PVOID * Callers, IN ULONG Count, IN ULONG Flags)
Definition at line 544 of file stkwalk.c.
References FALSE, MmCanThreadFault(), PsGetCurrentThread(), and RtlpWalkFrameChain().
Referenced by RtlCaptureStackBackTrace().
Variable Documentation
LONG RtlpStackWalksInProgress
Definition at line 27 of file stkwalk.c.
Referenced by MiResolveTransitionFault(), and RtlpWalkFrameChain().