Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/errorlog.c File Reference
errorlog.c File Reference
#include "iomgr.h"
#include "elfkrnl.h"
Data Structures
struct _IOP_ERROR_LOG_CONTEXT
Macros
#define IO_ERROR_NAME_LENGTH 100
Typedefs
typedef struct _IOP_ERROR_LOG_CONTEXT IOP_ERROR_LOG_CONTEXT
typedef struct _IOP_ERROR_LOG_CONTEXT * PIOP_ERROR_LOG_CONTEXT
Functions
BOOLEAN IopErrorLogConnectPort (VOID)
VOID IopErrorLogDpc (IN struct _KDPC *Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
PLIST_ENTRY IopErrorLogGetEntry ()
VOID IopErrorLogQueueRequest (VOID)
VOID IopErrorLogRequeueEntry (IN PLIST_ENTRY ListEntry)
VOID IopErrorLogThread (IN PVOID StartContext)
Variables
HANDLE ErrorLogPort
BOOLEAN ErrorLogPortConnected
BOOLEAN IopErrorLogDisabledThisBoot
BOOLEAN IopErrorLogPortPending
WORK_QUEUE_ITEM IopErrorLogWorkItem
Macro Definition Documentation
#define IO_ERROR_NAME_LENGTH 100
Definition at line 84 of file errorlog.c.
Referenced by IopErrorLogThread().
Typedef Documentation
typedef struct _IOP_ERROR_LOG_CONTEXT IOP_ERROR_LOG_CONTEXT
typedef struct _IOP_ERROR_LOG_CONTEXT * PIOP_ERROR_LOG_CONTEXT
Function Documentation
BOOLEAN IopErrorLogConnectPort (VOID)
Definition at line 609 of file errorlog.c.
References _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _SECURITY_QUALITY_OF_SERVICE::EffectiveOnly, ELF_PORT_NAME_U, ErrorLogPort, ErrorLogPortConnected, FALSE, _SECURITY_QUALITY_OF_SERVICE::ImpersonationLevel, IO_ERROR_LOG_MESSAGE_LENGTH, IopErrorLogQueueRequest(), NT_SUCCESS, NtClose(), NtConnectPort(), NULL, PAGED_CODE, RtlInitUnicodeString(), SECURITY_DYNAMIC_TRACKING, SecurityImpersonation, and TRUE.
Referenced by IopErrorLogThread().
VOID IopErrorLogDpc (IN struct _KDPC * Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 703 of file errorlog.c.
References DelayedWorkQueue, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), IopErrorLogThread(), NULL, and UNREFERENCED_PARAMETER.
Referenced by IopErrorLogQueueRequest().
PLIST_ENTRY IopErrorLogGetEntry ()
Definition at line 754 of file errorlog.c.
References ExAcquireSpinLock, ExReleaseSpinLock, FALSE, IopErrorLogListHead, IopErrorLogLock, IopErrorLogPortPending, IsListEmpty, NULL, and RemoveHeadList().
Referenced by IopErrorLogThread().
VOID IopErrorLogQueueRequest (VOID)
Definition at line 807 of file errorlog.c.
References _IOP_ERROR_LOG_CONTEXT::ErrorLogDpc, _IOP_ERROR_LOG_CONTEXT::ErrorLogTimer, ExAllocatePool, FALSE, IopErrorLogDpc(), IopErrorLogPortPending, KeInitializeDpc(), KeInitializeTimer(), KeSetTimer(), NonPagedPool, NULL, PAGED_CODE, and _LARGE_INTEGER::QuadPart.
Referenced by IopErrorLogConnectPort(), and IopErrorLogThread().
VOID IopErrorLogRequeueEntry (IN PLIST_ENTRY ListEntry)
Definition at line 876 of file errorlog.c.
References ErrorLogPortConnected, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, InsertHeadList(), IopErrorLogListHead, and IopErrorLogLock.
Referenced by IopErrorLogThread().
VOID IopErrorLogThread (IN PVOID StartContext)
Definition at line 87 of file errorlog.c.
References _UNICODE_STRING::Buffer, CONTAINING_RECORD, _ERROR_LOG_ENTRY::DeviceObject, _IO_ERROR_LOG_MESSAGE::DriverNameLength, _IO_ERROR_LOG_MESSAGE::DriverNameOffset, _ERROR_LOG_ENTRY::DriverObject, _IO_ERROR_LOG_MESSAGE::EntryData, ErrorLogPort, ExAllocatePool, ExFreePool(), FIELD_OFFSET, InterlockedExchangeAdd(), IO_ERROR_LOG, IO_ERROR_LOG_MESSAGE_LENGTH, IO_ERROR_NAME_LENGTH, IO_TYPE_ERROR_MESSAGE, ELF_PORT_MSG::IoErrorLogMessage, IopErrorLogAllocation, IopErrorLogConnectPort(), IopErrorLogGetEntry(), IopErrorLogQueueRequest(), IopErrorLogRequeueEntry(), _UNICODE_STRING::Length, _ERROR_LOG_ENTRY::ListEntry, ELF_PORT_MSG::MessageType, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NtClose(), NtRequestPort(), NULL, _IO_ERROR_LOG_PACKET::NumberOfStrings, ObDereferenceObject(), ObQueryNameString(), PAGED_CODE, PagedPool, ELF_PORT_MSG::PortMessage, RtlCopyMemory, RtlZeroMemory, _PORT_MESSAGE::s1, _IO_ERROR_LOG_MESSAGE::Size, _ERROR_LOG_ENTRY::Size, STATUS_INFO_LENGTH_MISMATCH, _IO_ERROR_LOG_PACKET::StringOffset, _IO_ERROR_LOG_MESSAGE::TimeStamp, _ERROR_LOG_ENTRY::TimeStamp, _IO_ERROR_LOG_MESSAGE::Type, ELF_PORT_MSG::u, _PORT_MESSAGE::u1, UNREFERENCED_PARAMETER, and wcslen().
Referenced by IopErrorLogDpc(), and IoWriteErrorLogEntry().
Variable Documentation
HANDLE ErrorLogPort
Definition at line 72 of file errorlog.c.
Referenced by IopErrorLogConnectPort(), and IopErrorLogThread().
BOOLEAN ErrorLogPortConnected
Definition at line 76 of file errorlog.c.
Referenced by IopErrorLogConnectPort(), and IopErrorLogRequeueEntry().
BOOLEAN IopErrorLogDisabledThisBoot
Definition at line 78 of file errorlog.c.
Referenced by IoInitSystem(), and IoWriteErrorLogEntry().
BOOLEAN IopErrorLogPortPending
Definition at line 77 of file errorlog.c.
Referenced by IopErrorLogGetEntry(), IopErrorLogQueueRequest(), and IoWriteErrorLogEntry().
WORK_QUEUE_ITEM IopErrorLogWorkItem
Definition at line 68 of file errorlog.c.
Referenced by IoWriteErrorLogEntry().