Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/lookasid.c File Reference
lookasid.c File Reference
#include "exp.h"
Macros
#define MINIMUM_ALLOCATION_THRESHOLD 25
#define MINIMUM_LOOKASIDE_DEPTH 4
Functions
VOID ExAdjustLookasideDepth (VOID)
VOID ExDeleteNPagedLookasideList (__inout PNPAGED_LOOKASIDE_LIST Lookaside)
VOID ExDeletePagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside)
VOID ExInitializeNPagedLookasideList (__out PNPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
VOID ExInitializePagedLookasideList (__out PPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
FORCEINLINE VOID ExpComputeLookasideDepth (IN PGENERAL_LOOKASIDE Lookaside, IN ULONG Misses, IN ULONG ScanPeriod)
PVOID ExpDummyAllocate (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag)
VOID ExpScanGeneralLookasideList (IN PLIST_ENTRY ListHead, IN PKSPIN_LOCK SpinLock)
VOID ExpScanSystemLookasideList (VOID)
Variables
USHORT ExMinimumLookasideDepth = MINIMUM_LOOKASIDE_DEPTH
LIST_ENTRY ExNPagedLookasideListHead
KSPIN_LOCK ExNPagedLookasideLock
LIST_ENTRY ExPagedLookasideListHead
KSPIN_LOCK ExPagedLookasideLock
LIST_ENTRY ExPoolLookasideListHead
ULONG ExpPoolScanCount = 0
ULONG ExpScanCount = 0
LIST_ENTRY ExSystemLookasideListHead
Macro Definition Documentation
#define MINIMUM_ALLOCATION_THRESHOLD 25
Definition at line 33 of file lookasid.c.
Referenced by ExpComputeLookasideDepth().
#define MINIMUM_LOOKASIDE_DEPTH 4
Definition at line 27 of file lookasid.c.
Referenced by ExpComputeLookasideDepth().
Function Documentation
VOID ExAdjustLookasideDepth (VOID)
Definition at line 82 of file lookasid.c.
References ExNPagedLookasideLock, ExPagedLookasideLock, ExpScanCount, ExpScanGeneralLookasideList(), and ExpScanSystemLookasideList().
Referenced by KeBalanceSetManager().
VOID ExDeleteNPagedLookasideList (__inout PNPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 579 of file lookasid.c.
References ExAcquireSpinLock, ExAllocateFromNPagedLookasideList(), ExNPagedLookasideLock, ExpDummyAllocate(), ExReleaseSpinLock, NULL, and RemoveEntryList().
VOID ExDeletePagedLookasideList (__inout PPAGED_LOOKASIDE_LIST Lookaside)
Definition at line 716 of file lookasid.c.
References ExAcquireSpinLock, ExAllocateFromPagedLookasideList(), ExPagedLookasideLock, ExpDummyAllocate(), ExReleaseSpinLock, NULL, and RemoveEntryList().
Referenced by MiDereferenceSessionFinal().
VOID ExInitializeNPagedLookasideList (__out PNPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
Definition at line 493 of file lookasid.c.
References ExAllocatePoolWithTag, ExFreePool(), ExInterlockedInsertTailList(), ExMinimumLookasideDepth, ExNPagedLookasideLock, InitializeSListHead(), NonPagedPool, NULL, Tag, and UNREFERENCED_PARAMETER.
Referenced by FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcbs(), and WmipInitializeRegistration().
VOID ExInitializePagedLookasideList (__out PPAGED_LOOKASIDE_LIST Lookaside, __in_opt PALLOCATE_FUNCTION Allocate, __in_opt PFREE_FUNCTION Free, __in ULONG Flags, __in SIZE_T Size, __in ULONG Tag, __in USHORT Depth)
Definition at line 628 of file lookasid.c.
References ExAllocatePoolWithTag, ExFreePool(), ExInterlockedInsertTailList(), ExMinimumLookasideDepth, ExPagedLookasideLock, InitializeSListHead(), NULL, PAGED_CODE, PagedPool, Tag, and UNREFERENCED_PARAMETER.
Referenced by FsRtlInitializeFileLocks(), FsRtlInitializeLargeMcbs(), FsRtlInitializeTunnels(), LpcpInitializePortZone(), and MmSessionCreate().
FORCEINLINE VOID ExpComputeLookasideDepth (IN PGENERAL_LOOKASIDE Lookaside, IN ULONG Misses, IN ULONG ScanPeriod)
Definition at line 159 of file lookasid.c.
References ExMinimumLookasideDepth, MINIMUM_ALLOCATION_THRESHOLD, and MINIMUM_LOOKASIDE_DEPTH.
Referenced by ExpScanGeneralLookasideList(), and ExpScanSystemLookasideList().
PVOID ExpDummyAllocate (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN ULONG Tag)
Definition at line 765 of file lookasid.c.
References NULL, and UNREFERENCED_PARAMETER.
Referenced by ExDeleteNPagedLookasideList(), ExDeletePagedLookasideList(), and ExDrainPoolLookasideList().
VOID ExpScanGeneralLookasideList (IN PLIST_ENTRY ListHead, IN PKSPIN_LOCK SpinLock)
Definition at line 261 of file lookasid.c.
References CONTAINING_RECORD, ExAcquireSpinLock, ExpComputeLookasideDepth(), ExReleaseSpinLock, _LIST_ENTRY::Flink, and UNREFERENCED_PARAMETER.
Referenced by ExAdjustLookasideDepth().
VOID ExpScanSystemLookasideList (VOID)
Definition at line 341 of file lookasid.c.
References _GENERAL_LOOKASIDE::AllocateHits, _GENERAL_LOOKASIDE::AllocateMisses, ExpComputeLookasideDepth(), ExpPoolScanCount, ExpSmallNPagedPoolLookasideLists, ExpSmallPagedPoolLookasideLists, Index, KeGetCurrentPrcb(), KeNumberProcessors, KiProcessorBlock, _PP_LOOKASIDE_LIST::L, LookasideMaximumList, NULL, _PP_LOOKASIDE_LIST::P, POOL_SMALL_LISTS, _KPRCB::PPLookasideList, _KPRCB::PPNPagedLookasideList, and _KPRCB::PPPagedLookasideList.
Referenced by ExAdjustLookasideDepth().
Variable Documentation
USHORT ExMinimumLookasideDepth = MINIMUM_LOOKASIDE_DEPTH
Definition at line 79 of file lookasid.c.
Referenced by ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), and ExpComputeLookasideDepth().
LIST_ENTRY ExNPagedLookasideListHead
Definition at line 61 of file lookasid.c.
Referenced by ExpGetLookasideInformation(), and ExpInitSystemPhase0().
KSPIN_LOCK ExNPagedLookasideLock
Definition at line 62 of file lookasid.c.
Referenced by ExAdjustLookasideDepth(), ExDeleteNPagedLookasideList(), ExInitializeNPagedLookasideList(), ExpGetLookasideInformation(), and ExpInitSystemPhase0().
LIST_ENTRY ExPagedLookasideListHead
Definition at line 63 of file lookasid.c.
Referenced by ExpGetLookasideInformation(), and ExpInitSystemPhase0().
KSPIN_LOCK ExPagedLookasideLock
Definition at line 64 of file lookasid.c.
Referenced by ExAdjustLookasideDepth(), ExDeletePagedLookasideList(), ExInitializePagedLookasideList(), ExpGetLookasideInformation(), and ExpInitSystemPhase0().
LIST_ENTRY ExPoolLookasideListHead
Definition at line 65 of file lookasid.c.
Referenced by ExpGetLookasideInformation(), ExpInitSystemPhase0(), ExpInitSystemPhase1(), and ExQueryPoolUsage().
ULONG ExpPoolScanCount = 0
Definition at line 72 of file lookasid.c.
Referenced by ExpScanSystemLookasideList().
ULONG ExpScanCount = 0
Definition at line 73 of file lookasid.c.
Referenced by ExAdjustLookasideDepth().
LIST_ENTRY ExSystemLookasideListHead
Definition at line 66 of file lookasid.c.
Referenced by CcInitializeCacheManager(), ExpGetLookasideInformation(), ExpInitSystemPhase0(), IoInitSystem(), and ObInitSystem().