Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcqueue.c File Reference
lpcqueue.c File Reference
#include "lpcp.h"
Functions
NTSTATUS LpcDisconnectPort (IN PVOID Port)
VOID LpcpDestroyPortQueue (IN PLPCP_PORT_OBJECT Port, IN BOOLEAN CleanupAndDestroy)
PLPCP_MESSAGE LpcpFindDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
VOID LpcpFreeDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
VOID FASTCALL LpcpFreeToPortZone (IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
NTSTATUS LpcpInitializePortQueue (IN PLPCP_PORT_OBJECT Port)
VOID LpcpInitializePortZone (IN ULONG MaxEntrySize)
VOID LpcpSaveDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
Variables
ULONG LpcpMaxMessageSize = 0
PAGED_LOOKASIDE_LIST LpcpMessagesLookaside
ULONG LpcpTotalNumberOfMessages = 0
Function Documentation
NTSTATUS LpcDisconnectPort (IN PVOID Port)
Definition at line 310 of file lpcqueue.c.
References FALSE, LpcpDestroyPortQueue(), and STATUS_SUCCESS.
Referenced by PspFreezeProcessWorker().
VOID LpcpDestroyPortQueue (IN PLPCP_PORT_OBJECT Port, IN BOOLEAN CleanupAndDestroy)
Definition at line 115 of file lpcqueue.c.
References _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, CONTAINING_RECORD, _LPCP_MESSAGE::Entry, ExFreePool(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), IsListEmpty, KeReadStateSemaphore(), KeReleaseSemaphore(), LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LpcpAcquireLpcpLock, LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpReleaseLpcpLock, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, NULL, ObDereferenceObject(), PAGED_CODE, PORT_NAME_DELETED, PORT_TYPE, RemoveEntryList(), _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _LPCP_CONNECTION_MESSAGE::SectionToMap, SERVER_CONNECTION_PORT, _PORT_MESSAGE::u2, and UNCONNECTED_COMMUNICATION_PORT.
Referenced by LpcDisconnectPort(), LpcpClosePort(), and LpcpDeletePort().
PLPCP_MESSAGE LpcpFindDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
Definition at line 640 of file lpcqueue.c.
References _PORT_MESSAGE::CallbackId, _PORT_MESSAGE::ClientId, CONTAINING_RECORD, _LIST_ENTRY::Flink, LpcpTrace, _PORT_MESSAGE::MessageId, NULL, PAGED_CODE, PORT_TYPE, PsGetCurrentProcess(), _LPCP_MESSAGE::Request, and UNCONNECTED_COMMUNICATION_PORT.
Referenced by LpcpCopyRequestData().
VOID LpcpFreeDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
Definition at line 532 of file lpcqueue.c.
References _PORT_MESSAGE::CallbackId, _PORT_MESSAGE::ClientId, CONTAINING_RECORD, _LPCP_MESSAGE::Entry, _LIST_ENTRY::Flink, InitializeListHead(), LPCP_MUTEX_OWNED, LpcpFreeToPortZone(), LpcpTrace, _PORT_MESSAGE::MessageId, NULL, PAGED_CODE, PORT_TYPE, PsGetCurrentProcess(), RemoveEntryList(), _LPCP_MESSAGE::Request, and UNCONNECTED_COMMUNICATION_PORT.
Referenced by NtReplyPort(), NtReplyWaitReceivePortEx(), and NtReplyWaitReplyPort().
VOID FASTCALL LpcpFreeToPortZone (IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
Definition at line 356 of file lpcqueue.c.
References _LPCP_CONNECTION_MESSAGE::ClientPort, ExFreeToPagedLookasideList(), InitializeListHead(), IsListEmpty, LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLock, LpcpMessagesLookaside, LpcpReleaseLpcpLock, NULL, ObDereferenceObject(), PAGED_CODE, and RemoveEntryList().
Referenced by LpcExitThread(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeDataInfoMessage(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
NTSTATUS LpcpInitializePortQueue (IN PLPCP_PORT_OBJECT Port)
Definition at line 48 of file lpcqueue.c.
References _LPCP_NONPAGED_PORT_QUEUE::BackPointer, ExAllocatePoolWithTag, InitializeListHead(), KeInitializeSemaphore(), _LPCP_PORT_OBJECT::MsgQueue, NonPagedPool, NULL, PAGED_CODE, _LPCP_NONPAGED_PORT_QUEUE::Semaphore, _LPCP_PORT_QUEUE::Semaphore, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by LpcpCreatePort(), and NtSecureConnectPort().
VOID LpcpInitializePortZone (IN ULONG MaxEntrySize)
Definition at line 337 of file lpcqueue.c.
References ExInitializePagedLookasideList(), LpcpMaxMessageSize, LpcpMessagesLookaside, and NULL.
Referenced by LpcInitSystem().
VOID LpcpSaveDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
Definition at line 446 of file lpcqueue.c.
References InsertTailList(), LPCP_MUTEX_OWNED, LpcpAcquireLpcpLock, LpcpReleaseLpcpLock, LpcpTrace, NULL, PAGED_CODE, PORT_TYPE, PsGetCurrentProcess(), and UNCONNECTED_COMMUNICATION_PORT.
Referenced by NtReplyWaitReceivePortEx(), and NtRequestWaitReplyPort().
Variable Documentation
ULONG LpcpMaxMessageSize = 0
Definition at line 38 of file lpcqueue.c.
Referenced by LpcpInitializePortZone().
PAGED_LOOKASIDE_LIST LpcpMessagesLookaside
Definition at line 39 of file lpcqueue.c.
Referenced by LpcpFreeToPortZone(), and LpcpInitializePortZone().
ULONG LpcpTotalNumberOfMessages = 0
Definition at line 37 of file lpcqueue.c.