Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/wrtwatch.c File Reference
wrtwatch.c File Reference
#include "mi.h"
Macros
#define COPY_STACK_SIZE 256
Functions
VOID MiCaptureWriteWatchDirtyBit (IN PEPROCESS Process, IN PVOID VirtualAddress)
NTSTATUS NtGetWriteWatch (__in HANDLE ProcessHandle, __in ULONG Flags, __in PVOID BaseAddress, __in SIZE_T RegionSize, __out_ecount(*EntriesInUserAddressArray) PVOID *UserAddressArray, __inout PULONG_PTR EntriesInUserAddressArray, __out PULONG Granularity)
NTSTATUS NtResetWriteWatch (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in SIZE_T RegionSize)
Macro Definition Documentation
#define COPY_STACK_SIZE 256
Definition at line 21 of file wrtwatch.c.
Referenced by NtGetWriteWatch().
Function Documentation
VOID MiCaptureWriteWatchDirtyBit (IN PEPROCESS Process, IN PVOID VirtualAddress)
Definition at line 919 of file wrtwatch.c.
References ASSERT, _MI_PHYSICAL_VIEW::BitMap, _RTL_BITMAP::Buffer, _MI_PHYSICAL_VIEW::EndingVpn, MI_SET_BIT, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiFindNodeOrParent(), MM_PFN_LOCK_ASSERT, NULL, PAGE_SHIFT, PS_PROCESS_FLAGS_USING_WRITE_WATCH, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, TableFoundNode, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MI_PHYSICAL_VIEW::Vad, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, and VadWriteWatch.
Referenced by MiEliminateWorkingSetEntry(), MiFlushTbAndCapture(), MiFreeWsleList(), and MiTrimPte().
NTSTATUS NtGetWriteWatch (__in HANDLE ProcessHandle, __in ULONG Flags, __in PVOID BaseAddress, __in SIZE_T RegionSize, __out_ecount *EntriesInUserAddressArray PVOID * UserAddressArray, __inout PULONG_PTR EntriesInUserAddressArray, __out PULONG Granularity)
Definition at line 25 of file wrtwatch.c.
References ASSERT, _MI_PHYSICAL_VIEW::BitMap, COPY_STACK_SIZE, _MMPTE_FLUSH_LIST::Count, _MMPFN::e1, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, except, ExFreePool(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, KeGetCurrentIrql(), KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_PFN, LOCK_WS, MAXULONG_PTR, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_WORKING_SET_FROM_PTE, MI_IS_PTE_DIRTY, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_SET_PTE_IN_WORKING_SET, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiFindNodeOrParent(), MiFlushPteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MM_HIGHEST_VAD_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, NO_BITS_FOUND, NonPagedPool, NT_SUCCESS, NtCurrentProcess, NULL, NumberOfBytes, ObDereferenceObject(), ObReferenceObjectByHandle, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, PASSIVE_LEVEL, _EPROCESS::Pcb, _EPROCESS::PhysicalVadRoot, ProbeForWrite(), ProbeForWriteUlong, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, RtlCheckBit, RtlClearBit(), RtlCopyMemory, RtlFindSetBits(), SATISFY_OVERZEALOUS_COMPILER, _RTL_BITMAP::SizeOfBitMap, _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_INVALID_PARAMETER_5, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS, _MI_PHYSICAL_VIEW::Vad, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, VadWriteWatch, _MMPTE_HARDWARE::Valid, and WRITE_WATCH_FLAG_RESET.
NTSTATUS NtResetWriteWatch (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in SIZE_T RegionSize)
Definition at line 607 of file wrtwatch.c.
References ASSERT, _MI_PHYSICAL_VIEW::BitMap, _MMPTE_FLUSH_LIST::Count, _MMPFN::e1, _MI_PHYSICAL_VIEW::EndingVpn, FALSE, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_PFN, LOCK_WS, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_WORKING_SET_FROM_PTE, MI_IS_PTE_DIRTY, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_SET_PTE_IN_WORKING_SET, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiFindNodeOrParent(), MiFlushPteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MM_HIGHEST_VAD_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, PASSIVE_LEVEL, _EPROCESS::Pcb, _EPROCESS::PhysicalVadRoot, PROCESS_VM_OPERATION, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, RtlClearBits(), SATISFY_OVERZEALOUS_COMPILER, _RTL_BITMAP::SizeOfBitMap, _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS, _MI_PHYSICAL_VIEW::Vad, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, VadWriteWatch, and _MMPTE_HARDWARE::Valid.