Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/semphobj.c File Reference
semphobj.c File Reference
#include "ki.h"
Macros
#define ASSERT_SEMAPHORE(E)
Functions
VOID KeInitializeSemaphore (__out PRKSEMAPHORE Semaphore, __in LONG Count, __in LONG Limit)
LONG KeReadStateSemaphore (__in PRKSEMAPHORE Semaphore)
LONG KeReleaseSemaphore (__inout PRKSEMAPHORE Semaphore, __in KPRIORITY Increment, __in LONG Adjustment, __in BOOLEAN Wait)
Macro Definition Documentation
#define ASSERT_SEMAPHORE (E)
Value:
{                    \
    ASSERT((E)->Header.Type == SemaphoreObject); \
}
Definition at line 27 of file semphobj.c.
Referenced by KeReadStateSemaphore(), and KeReleaseSemaphore().
Function Documentation
VOID KeInitializeSemaphore (__out PRKSEMAPHORE Semaphore, __in LONG Count, __in LONG Limit)
Definition at line 32 of file semphobj.c.
References Count, InitializeListHead(), and SemaphoreObject.
Referenced by ExpAllocateSharedWaiterSemaphore(), ExReinitializeResourceLite(), FsRtlInitSystem(), IoInitSystem(), KeInitThread(), LpcpInitializePortQueue(), MmInitSystem(), NtCreateSemaphore(), PspCreateThread(), and WmipInitContext().
LONG KeReadStateSemaphore (__in PRKSEMAPHORE Semaphore)
Definition at line 78 of file semphobj.c.
References ASSERT_SEMAPHORE.
Referenced by IoRaiseInformationalHardError(), LpcpDestroyPortQueue(), LpcpRequestWaitReplyPort(), NtQuerySemaphore(), NtReplyWaitReplyPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), and WmipNotifyLogger().
LONG KeReleaseSemaphore (__inout PRKSEMAPHORE Semaphore, __in KPRIORITY Increment, __in LONG Adjustment, __in BOOLEAN Wait)
Definition at line 111 of file semphobj.c.
References ASSERT, ASSERT_SEMAPHORE, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), ReadForWriteAccess, STATUS_SEMAPHORE_LIMIT_EXCEEDED, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by ExConvertExclusiveToSharedLite(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), FsRtlDeregisterUncProvider(), FsRtlRegisterUncProvider(), IoRaiseInformationalHardError(), LpcpDestroyPortQueue(), LpcpRequestWaitReplyPort(), LpcRequestPort(), MiCheckForControlAreaDeletion(), MiContractPagingFiles(), MiIssuePageExtendRequest(), MiIssuePageExtendRequestNoWait(), NtAcceptConnectPort(), NtCompleteConnectPort(), NtReleaseKeyedEvent(), NtReleaseSemaphore(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), NtSecureConnectPort(), NtSignalAndWaitForSingleObject(), NtWaitForKeyedEvent(), and WmipNotifyLogger().