Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/thkemul.c File Reference
thkemul.c File Reference
#include "ki.h"
Functions
LOGICAL KiEmulateAtlThunk (IN OUT ULONG *InstructionPointer, IN OUT ULONG *StackPointer, IN OUT ULONG *Eax, IN OUT ULONG *Ecx, IN OUT ULONG *Edx)
Function Documentation
LOGICAL KiEmulateAtlThunk (IN OUT ULONG * InstructionPointer, IN OUT ULONG * StackPointer, IN OUT ULONG * Eax, IN OUT ULONG * Ecx, IN OUT ULONG * Edx)
Definition at line 23 of file thkemul.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KiQueryNxThunkEmulationState, MmCheckForSafeExecution(), NOTHING, NtCurrentTeb(), NtCurrentTeb32, ProbeAndReadUchar, ProbeAndReadUlong, ProbeAndWriteUlong, PtrToUlong, TRUE, and UlongToPtr.
Referenced by KiCheckForAtlThunk().