Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmalloc.c File Reference
cmalloc.c File Reference
#include "cmp.h"
Data Structures
struct _CM_ALLOC_PAGE
Macros
#define CM_DELAY_ALLOC_ENTRY_SIZE sizeof(CM_DELAY_ALLOC)
#define CM_DELAYS_PER_PAGE ((PAGE_SIZE - FIELD_OFFSET(CM_ALLOC_PAGE,AllocPage)) / CM_DELAY_ALLOC_ENTRY_SIZE)
#define CM_KCB_ENTRY_SIZE sizeof(CM_KEY_CONTROL_BLOCK)
#define CM_KCBS_PER_PAGE ((PAGE_SIZE - FIELD_OFFSET(CM_ALLOC_PAGE,AllocPage)) / CM_KCB_ENTRY_SIZE)
#define DELAY_ALLOC_TO_ALLOC_PAGE(delay) ((PCM_ALLOC_PAGE)DELAY_ALLOC_TO_PAGE_ADDRESS(delay))
#define DELAY_ALLOC_TO_PAGE_ADDRESS(delay) (PVOID)(((ULONG_PTR)(delay)) & ~(PAGE_SIZE - 1))
#define KCB_TO_ALLOC_PAGE(kcb) ((PCM_ALLOC_PAGE)KCB_TO_PAGE_ADDRESS(kcb))
#define KCB_TO_PAGE_ADDRESS(kcb) (PVOID)(((ULONG_PTR)(kcb)) & ~(PAGE_SIZE - 1))
#define LOCK_ALLOC_BUCKET() KeAcquireGuardedMutex(&CmpAllocBucketLock)
#define LOCK_DELAY_ALLOC_BUCKET() KeAcquireGuardedMutex(&CmpDelayAllocBucketLock)
#define LogKCBFree(kcb)
#define UNLOCK_ALLOC_BUCKET() KeReleaseGuardedMutex(&CmpAllocBucketLock)
#define UNLOCK_DELAY_ALLOC_BUCKET() KeReleaseGuardedMutex(&CmpDelayAllocBucketLock)
Typedefs
typedef struct _CM_ALLOC_PAGE CM_ALLOC_PAGE
typedef struct _CM_ALLOC_PAGE * PCM_ALLOC_PAGE
Functions
PVOID CmpAllocateDelayItem ()
PCM_KEY_CONTROL_BLOCK CmpAllocateKeyControlBlock ()
VOID CmpDestroyCmPrivateAlloc ()
VOID CmpDestroyCmPrivateDelayAlloc ()
VOID CmpFreeDelayItem (PVOID Item)
VOID CmpFreeKeyControlBlock (PCM_KEY_CONTROL_BLOCK kcb)
VOID CmpInitCmPrivateAlloc ()
VOID CmpInitCmPrivateDelayAlloc ()
Variables
KGUARDED_MUTEX CmpAllocBucketLock
BOOLEAN CmpAllocInited = FALSE
KGUARDED_MUTEX CmpDelayAllocBucketLock
LIST_ENTRY CmpDelayDerefKCBListHead
LIST_ENTRY CmpDelayedLRUListHead
LIST_ENTRY CmpFreeDelayItemsListHead
LIST_ENTRY CmpFreeKCBListHead
Macro Definition Documentation
#define CM_DELAY_ALLOC_ENTRY_SIZE sizeof(CM_DELAY_ALLOC)
Definition at line 340 of file cmalloc.c.
Referenced by CmpAllocateDelayItem(), and CmpFreeDelayItem().
#define CM_DELAYS_PER_PAGE ((PAGE_SIZE - FIELD_OFFSET(CM_ALLOC_PAGE,AllocPage)) / CM_DELAY_ALLOC_ENTRY_SIZE)
Definition at line 341 of file cmalloc.c.
Referenced by CmpAllocateDelayItem(), and CmpFreeDelayItem().
#define CM_KCB_ENTRY_SIZE sizeof(CM_KEY_CONTROL_BLOCK)
Definition at line 38 of file cmalloc.c.
Referenced by CmpAllocateKeyControlBlock(), and CmpFreeKeyControlBlock().
#define CM_KCBS_PER_PAGE ((PAGE_SIZE - FIELD_OFFSET(CM_ALLOC_PAGE,AllocPage)) / CM_KCB_ENTRY_SIZE)
Definition at line 39 of file cmalloc.c.
Referenced by CmpAllocateKeyControlBlock(), and CmpFreeKeyControlBlock().
#define DELAY_ALLOC_TO_ALLOC_PAGE (delay) ((PCM_ALLOC_PAGE)DELAY_ALLOC_TO_PAGE_ADDRESS(delay))
Definition at line 344 of file cmalloc.c.
Referenced by CmpAllocateDelayItem(), and CmpFreeDelayItem().
#define DELAY_ALLOC_TO_PAGE_ADDRESS (delay) (PVOID)(((ULONG_PTR)(delay)) & ~(PAGE_SIZE - 1))
Definition at line 343 of file cmalloc.c.
#define KCB_TO_ALLOC_PAGE (kcb) ((PCM_ALLOC_PAGE)KCB_TO_PAGE_ADDRESS(kcb))
Definition at line 42 of file cmalloc.c.
Referenced by CmpAllocateKeyControlBlock(), and CmpFreeKeyControlBlock().
#define KCB_TO_PAGE_ADDRESS (kcb) (PVOID)(((ULONG_PTR)(kcb)) & ~(PAGE_SIZE - 1))
Definition at line 41 of file cmalloc.c.
#define LOCK_ALLOC_BUCKET () KeAcquireGuardedMutex(&CmpAllocBucketLock)
Definition at line 49 of file cmalloc.c.
Referenced by CmpAllocateKeyControlBlock(), and CmpFreeKeyControlBlock().
#define LOCK_DELAY_ALLOC_BUCKET () KeAcquireGuardedMutex(&CmpDelayAllocBucketLock)
Definition at line 335 of file cmalloc.c.
Referenced by CmpAllocateDelayItem(), and CmpFreeDelayItem().
#define LogKCBFree (kcb)
Definition at line 238 of file cmalloc.c.
Referenced by CmpFreeKeyControlBlock().
#define UNLOCK_ALLOC_BUCKET () KeReleaseGuardedMutex(&CmpAllocBucketLock)
Definition at line 50 of file cmalloc.c.
Referenced by CmpAllocateKeyControlBlock(), and CmpFreeKeyControlBlock().
#define UNLOCK_DELAY_ALLOC_BUCKET () KeReleaseGuardedMutex(&CmpDelayAllocBucketLock)
Definition at line 336 of file cmalloc.c.
Referenced by CmpAllocateDelayItem(), and CmpFreeDelayItem().
Typedef Documentation
typedef struct _CM_ALLOC_PAGE CM_ALLOC_PAGE
typedef struct _CM_ALLOC_PAGE * PCM_ALLOC_PAGE
Function Documentation
PVOID CmpAllocateDelayItem ()
Definition at line 396 of file cmalloc.c.
References ASSERT, CM_DELAY_ALLOC_ENTRY_SIZE, CM_DELAYS_PER_PAGE, CM_PAGED_CODE, CmpClearListEntry, CmpIsListEmpty, CONTAINING_RECORD, DELAY_ALLOC_TO_ALLOC_PAGE, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, InsertTailList(), _CM_DELAY_ALLOC::Kcb, _CM_DELAY_ALLOC::ListEntry, LOCK_DELAY_ALLOC_BUCKET, NULL, PAGE_SIZE, PagedPool, PROTECTED_POOL, RemoveHeadList(), and UNLOCK_DELAY_ALLOC_BUCKET.
PCM_KEY_CONTROL_BLOCK CmpAllocateKeyControlBlock ()
Definition at line 114 of file cmalloc.c.
References ASSERT, CM_KCB_ENTRY_SIZE, CM_KCBS_PER_PAGE, CmpAllocInited, CONTAINING_RECORD, _CM_KEY_CONTROL_BLOCK::DelayCloseEntry, ExAllocatePoolWithTag, FALSE, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, _CM_KEY_CONTROL_BLOCK::FreeListEntry, InsertTailList(), IsListEmpty, KCB_TO_ALLOC_PAGE, LOCK_ALLOC_BUCKET, NULL, PAGE_SIZE, PAGED_CODE, PagedPool, _CM_KEY_CONTROL_BLOCK::PrivateAlloc, PROTECTED_POOL, RemoveHeadList(), and UNLOCK_ALLOC_BUCKET.
Referenced by CmpCreateKeyControlBlock().
VOID CmpDestroyCmPrivateAlloc ()
Definition at line 88 of file cmalloc.c.
References CmpAllocInited, and PAGED_CODE.
Referenced by CmpFreeAllMemory().
VOID CmpDestroyCmPrivateDelayAlloc ()
Definition at line 374 of file cmalloc.c.
References CM_PAGED_CODE.
Referenced by CmpFreeAllMemory().
VOID CmpFreeDelayItem (PVOID Item)
Definition at line 492 of file cmalloc.c.
References ASSERT, CM_DELAY_ALLOC_ENTRY_SIZE, CM_DELAYS_PER_PAGE, CM_PAGED_CODE, CmpRemoveEntryList, DELAY_ALLOC_TO_ALLOC_PAGE, ExFreePoolWithTag, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, InsertTailList(), _CM_DELAY_ALLOC::ListEntry, LOCK_DELAY_ALLOC_BUCKET, PROTECTED_POOL, and UNLOCK_DELAY_ALLOC_BUCKET.
VOID CmpFreeKeyControlBlock (PCM_KEY_CONTROL_BLOCK kcb)
Definition at line 241 of file cmalloc.c.
References ASSERT, ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE, ASSERT_KEYBODY_LIST_EMPTY, CM_KCB_ENTRY_SIZE, CM_KCBS_PER_PAGE, CMP_KCB_REAL_NAME_UPCASE, _CM_KEY_CONTROL_BLOCK::ConvKey, ExFreePoolWithTag, FIELD_OFFSET, _CM_ALLOC_PAGE::FreeCount, _CM_KEY_CONTROL_BLOCK::FreeListEntry, InsertTailList(), KCB_TO_ALLOC_PAGE, LOCK_ALLOC_BUCKET, LogKCBFree, NULL, PAGED_CODE, _CM_KEY_CONTROL_BLOCK::PrivateAlloc, PROTECTED_POOL, RemoveEntryList(), and UNLOCK_ALLOC_BUCKET.
Referenced by CmpCleanUpKcbCacheWithLock(), and CmpCreateKeyControlBlock().
VOID CmpInitCmPrivateAlloc ()
Definition at line 53 of file cmalloc.c.
References CmpAllocInited, InitializeListHead(), KeInitializeGuardedMutex(), and TRUE.
Referenced by CmInitSystem1().
VOID CmpInitCmPrivateDelayAlloc ()
Definition at line 348 of file cmalloc.c.
References InitializeListHead(), and KeInitializeGuardedMutex().
Referenced by CmInitSystem1().
Variable Documentation
KGUARDED_MUTEX CmpAllocBucketLock
Definition at line 47 of file cmalloc.c.
BOOLEAN CmpAllocInited = FALSE
Definition at line 45 of file cmalloc.c.
Referenced by CmpAllocateKeyControlBlock(), CmpDestroyCmPrivateAlloc(), and CmpInitCmPrivateAlloc().
KGUARDED_MUTEX CmpDelayAllocBucketLock
Definition at line 333 of file cmalloc.c.
LIST_ENTRY CmpDelayDerefKCBListHead
Definition at line 522 of file cmdelay.c.
LIST_ENTRY CmpDelayedLRUListHead
Definition at line 89 of file cmdelay.c.
LIST_ENTRY CmpFreeDelayItemsListHead
Definition at line 331 of file cmalloc.c.
LIST_ENTRY CmpFreeKCBListHead
Definition at line 44 of file cmalloc.c.