Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/exp.h File Reference
exp.h File Reference
#include "ntos.h"
#include "zwapi.h"
#include "wdbgexts.h"
#include "ntdbg.h"
#include "ki.h"
#include "stdio.h"
#include "pool.h"
Data Structures
struct EXP_INITIALIZE_GLOBAL_CALLBACKS
Macros
#define EX_FIELD_ADDRESS(Type, Base, Member) ((PUCHAR)Base + FIELD_OFFSET(Type, Member))
#define EX_FOR_EACH_IN_LIST(_Type, _Link, _Head, _Current)
#define NOEXTAPI
Functions
NTSTATUS ExApplyCodePatch (IN PVOID PatchInfoPtr, IN SIZE_T PatchSize)
VOID ExInitializeTimeRefresh (VOID)
PVOID ExpCheckForResource (IN PVOID p, IN SIZE_T Size)
VOID ExpCheckForWorker (IN PVOID p, IN SIZE_T Size)
VOID ExpCheckSystemInformation (PVOID Context, PVOID InformationClass, PVOID Argument2)
VOID ExpCheckSystemInfoWork (IN PVOID Context)
BOOLEAN ExpEventInitialization (VOID)
BOOLEAN ExpEventPairInitialization (VOID)
NTSTATUS ExpGetSystemProcessorInformation (OUT PSYSTEM_PROCESSOR_INFORMATION ProcessorInformation)
BOOLEAN ExpInitializeCallbacks (VOID)
VOID ExpInitializePushLocks (VOID)
BOOLEAN ExpInitSystemPhase0 (VOID)
BOOLEAN ExpInitSystemPhase1 (VOID)
NTSTATUS ExpKeyedEventInitialization (VOID)
BOOLEAN ExpMutantInitialization (VOID)
VOID ExpProfileDelete (IN PVOID Object)
BOOLEAN ExpProfileInitialization ()
BOOLEAN ExpResourceInitialization (VOID)
BOOLEAN ExpSemaphoreInitialization (VOID)
VOID ExpShutdownWorkerThreads (VOID)
BOOLEAN ExpSysEventInitialization (VOID)
BOOLEAN ExpSystemOK (IN int safelevel, IN BOOLEAN evalflag)
VOID ExpTimeRefreshDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID ExpTimeRefreshWork (IN PVOID Context)
BOOLEAN ExpTimerInitialization (VOID)
VOID ExpTimeZoneDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID ExpTimeZoneWork (IN PVOID Context)
BOOLEAN ExpUuidInitialization ()
BOOLEAN ExpWin32Initialization (VOID)
NTSTATUS ExpWorkerInitialization (VOID)
Variables
LIST_ENTRY ExNPagedLookasideListHead
KSPIN_LOCK ExNPagedLookasideLock
LIST_ENTRY ExPagedLookasideListHead
KSPIN_LOCK ExPagedLookasideLock
PVOID ExpControlKey [2]
HANDLE ExpDefaultErrorPort
PEPROCESS ExpDefaultErrorPortProcess
FAST_MUTEX ExpEnvironmentLock
LIST_ENTRY ExpFirmwareTableProviderListHead
ERESOURCE ExpFirmwareTableResource
const EXP_INITIALIZE_GLOBAL_CALLBACKS ExpInitializeCallback []
BOOLEAN ExpInTextModeSetup
ERESOURCE ExpKeyManipLock
ULONG ExpNtExpirationData [3]
LIST_ENTRY ExPoolLookasideListHead
HANDLE ExpProductTypeKey
HANDLE ExpSetupKey
BOOLEAN ExpSetupModeDetected
LARGE_INTEGER ExpSetupSystemPrefix
GENERAL_LOOKASIDE ExpSmallNPagedPoolLookasideLists [POOL_SMALL_LISTS]
GENERAL_LOOKASIDE ExpSmallPagedPoolLookasideLists [POOL_SMALL_LISTS]
BOOLEAN ExpSystemPrefixValid
BOOLEAN ExpTooLateForErrors
const WCHAR ExpWstrCallback []
Macro Definition Documentation
#define EX_FIELD_ADDRESS (Type, Base, Member) ((PUCHAR)Base + FIELD_OFFSET(Type, Member))
Definition at line 62 of file exp.h.
#define EX_FOR_EACH_IN_LIST (_Type, _Link, _Head, _Current)
Value:
for((_Current) = CONTAINING_RECORD((_Head)->Flink, _Type, _Link);                                   \
       (_Head) != (PLIST_ENTRY)EX_FIELD_ADDRESS(_Type, _Current, _Link);                               \
       (_Current) = CONTAINING_RECORD(((PLIST_ENTRY)EX_FIELD_ADDRESS(_Type, _Current, _Link))->Flink,  \
                                     _Type,                                                          \
                                     _Link)                                                          \
       )
Definition at line 82 of file exp.h.
Referenced by ExpGetSystemFirmwareTableInformation(), and ExpRegisterFirmwareTableInformationHandler().
#define NOEXTAPI
Definition at line 35 of file exp.h.
Function Documentation
NTSTATUS ExApplyCodePatch (IN PVOID PatchInfoPtr, IN SIZE_T PatchSize)
Referenced by NtSetSystemInformation().
VOID ExInitializeTimeRefresh (VOID)
PVOID ExpCheckForResource (IN PVOID p, IN SIZE_T Size)
Definition at line 3104 of file resource.c.
References CONTAINING_RECORD, DbgBreakPoint(), DbgPrint(), EX_RESOURCE_CHECK_FREES, ExpSystemResourcesList, ExResourceCheckFlags, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLock(), KeNumberProcessors, KeReleaseInStackQueuedSpinLock(), and NULL.
Referenced by ExFreePoolSanityChecks().
VOID ExpCheckForWorker (IN PVOID p, IN SIZE_T Size)
Definition at line 952 of file worker.c.
References CriticalWorkQueue, _KQUEUE::EntryListHead, _LIST_ENTRY::Flink, KeBugCheckEx(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), MaximumWorkQueue, WORKER_INVALID, and _EX_WORK_QUEUE::WorkerQueue.
Referenced by ExFreePoolSanityChecks().
VOID ExpCheckSystemInformation (PVOID Context, PVOID InformationClass, PVOID Argument2)
VOID ExpCheckSystemInfoWork (IN PVOID Context)
BOOLEAN ExpEventInitialization (VOID)
Definition at line 65 of file event.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, EVENT_ALL_ACCESS, ExpEventMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
BOOLEAN ExpEventPairInitialization (VOID)
Definition at line 60 of file eventpr.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, EVENT_PAIR_ALL_ACCESS, ExpEventPairMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, Status, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
NTSTATUS ExpGetSystemProcessorInformation (OUT PSYSTEM_PROCESSOR_INFORMATION ProcessorInformation)
Definition at line 1330 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeFeatureBits, KeProcessorArchitecture, KeProcessorLevel, KeProcessorRevision, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
BOOLEAN ExpInitializeCallbacks (VOID)
VOID ExpInitializePushLocks (VOID)
Definition at line 151 of file pushlock.c.
References ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExInitializePushLock(), ExPushLockSpinCount, and KeNumberProcessors.
Referenced by ExpInitSystemPhase1().
BOOLEAN ExpInitSystemPhase0 (VOID)
Definition at line 137 of file exinit.c.
References ExInitializeFastMutex, ExInitializeResourceLite(), ExInitializeSystemLookasideList(), ExNPagedLookasideListHead, ExNPagedLookasideLock, ExPagedLookasideListHead, ExPagedLookasideLock, ExpEnvironmentLock, ExpFirmwareTableProviderListHead, ExpFirmwareTableResource, ExpKeyManipLock, ExPoolLookasideListHead, ExpResourceInitialization(), ExpSmallNPagedPoolLookasideLists, ExpSmallPagedPoolLookasideLists, ExpSystemOK(), ExSystemLookasideListHead, FALSE, Index, Initialized, InitializeListHead(), KdPrint, KeInitializeSpinLock(), NonPagedPool, PagedPool, POOL_SMALL_LISTS, and TRUE.
Referenced by ExInitSystem().
BOOLEAN ExpInitSystemPhase1 (VOID)
Definition at line 240 of file exinit.c.
References ExAllocatePoolWithTag, ExInitializeSystemLookasideList(), ExpEventInitialization(), ExpEventPairInitialization(), ExpInitializeCallbacks(), ExpInitializePushLocks(), ExpKeyedEventInitialization(), ExpMutantInitialization(), ExPoolLookasideListHead, ExpProfileInitialization(), ExpSemaphoreInitialization(), ExpTimerInitialization(), ExpUuidInitialization(), ExpWin32Initialization(), ExpWorkerInitialization(), FALSE, Index, Initialized, KdPrint, KeNumberProcessors, KiProcessorBlock, List, NonPagedPool, NT_SUCCESS, NULL, _PP_LOOKASIDE_LIST::P, PagedPool, POOL_SMALL_LISTS, _KPRCB::PPNPagedLookasideList, _KPRCB::PPPagedLookasideList, RtlInitializeAtomPackage(), and TRUE.
Referenced by ExInitSystem().
NTSTATUS ExpKeyedEventInitialization (VOID)
Definition at line 60 of file keyedevent.c.
References ACL_REVISION, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, InitializeObjectAttributes, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KEYEDEVENT_ALL_ACCESS, KEYEDEVENT_WAIT, KEYEDEVENT_WAKE, _OBJECT_TYPE_INITIALIZER::Length, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_PERMANENT, PAGED_CODE, PagedPool, _OBJECT_TYPE_INITIALIZER::PoolType, READ_CONTROL, RtlAddAccessAllowedAce(), RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlInitUnicodeString(), RtlLengthSid(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SeLocalSystemSid, SeWorldSid, STANDARD_RIGHTS_EXECUTE, STANDARD_RIGHTS_READ, STANDARD_RIGHTS_WRITE, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, ZwClose(), and ZwCreateKeyedEvent().
Referenced by ExpInitSystemPhase1().
BOOLEAN ExpMutantInitialization (VOID)
Definition at line 90 of file mutant.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExpDeleteMutant(), ExpMutantMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KdDumpEnableOffset, _OBJECT_TYPE_INITIALIZER::Length, MUTANT_ALL_ACCESS, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, PsGetCurrentProcess(), RtlInitUnicodeString(), RtlZeroMemory, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
VOID ExpProfileDelete (IN PVOID Object)
Definition at line 150 of file profile.c.
References ASSERT, CONTAINING_RECORD, ExFreePool(), FALSE, KeStopProfile(), _EPROFILE::LockedBufferAddress, _EPROFILE::Mdl, MmUnlockPages(), MmUnmapLockedPages(), NULL, ObDereferenceObject(), _EPROFILE::Process, and _EPROFILE::ProfileObject.
Referenced by ExpProfileInitialization().
BOOLEAN ExpProfileInitialization ()
Referenced by ExpInitSystemPhase1().
BOOLEAN ExpResourceInitialization (VOID)
Definition at line 279 of file resource.c.
References InitializeListHead(), Int32x32To64, KeInitializeSpinLock(), _LARGE_INTEGER::QuadPart, and TRUE.
Referenced by ExpInitSystemPhase0().
BOOLEAN ExpSemaphoreInitialization (VOID)
Definition at line 61 of file semphore.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, ExpSemaphoreMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, SEMAPHORE_ALL_ACCESS, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
VOID ExpShutdownWorkerThreads (VOID)
Definition at line 1545 of file worker.c.
References ASSERT, CriticalWorkQueue, DelayedWorkQueue, EX_WORKER_QUEUE_DISABLED, Executive, ExInitializeWorkItem, ExpShutdownWorker(), FALSE, KeGetCurrentThread(), KeInsertQueue(), KernelMode, KeWaitForSingleObject(), _WORK_QUEUE_ITEM::List, NULL, ObDereferenceObject(), PO_CLEAN_SHUTDOWN_WORKERS, PO_SHUTDOWN_QUEUE, PoCleanShutdownEnabled(), SHUTDOWN_WORK_ITEM::PrevThread, SHUTDOWN_WORK_ITEM::QueueType, RtlInterlockedSetBitsDiscardReturn, and SHUTDOWN_WORK_ITEM::WorkItem.
BOOLEAN ExpSysEventInitialization (VOID)
BOOLEAN ExpSystemOK (IN int safelevel, IN BOOLEAN evalflag)
Referenced by ExInitSystem(), and ExpInitSystemPhase0().
VOID ExpTimeRefreshDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID ExpTimeRefreshWork (IN PVOID Context)
BOOLEAN ExpTimerInitialization (VOID)
Definition at line 324 of file timer.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExpDeleteTimer(), ExpTimerMapping, ExpWakeTimerListLock, _OBJECT_TYPE_INITIALIZER::GenericMapping, InitializeListHead(), _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KeInitializeSpinLock(), _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, Status, TIMER_ALL_ACCESS, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
VOID ExpTimeZoneDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID ExpTimeZoneWork (IN PVOID Context)
BOOLEAN ExpUuidInitialization ()
Referenced by ExpInitSystemPhase1().
BOOLEAN ExpWin32Initialization (VOID)
Referenced by ExpInitSystemPhase1().
NTSTATUS ExpWorkerInitialization (VOID)
Definition at line 286 of file worker.c.
References CriticalWorkQueue, DelayedWorkQueue, ExCriticalWorkerThreads, ExDelayedWorkerThreads, ExInitializeFastMutex, ExpAdditionalCriticalWorkerThreads, ExpAdditionalDelayedWorkerThreads, ExpCreateWorkerThread(), ExpWorkersCanSwap, ExpWorkerThreadBalanceManager(), FALSE, HyperCriticalWorkQueue, Index, _EX_WORK_QUEUE::Info, InitializeListHead(), InitializeObjectAttributes, KeInitializeEvent(), KeInitializeQueue(), KernelMode, LARGE_NUMBER_OF_THREADS, EX_QUEUE_WORKER_INFO::MakeThreadsAsNecessary, MAX_ADDITIONAL_THREADS, MaximumWorkQueue, MEDIUM_NUMBER_OF_THREADS, MmIsThisAnNtAsSystem(), MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSmallSystem, NT_SUCCESS, NULL, ObReferenceObjectByHandle, PsCreateSystemThread(), RtlZeroMemory, Status, SynchronizationEvent, SYNCHRONIZE, _EXP_WORKER_LINK::Thread, THREAD_ALL_ACCESS, TRUE, UserMode, EX_QUEUE_WORKER_INFO::WaitMode, and ZwClose().
Referenced by ExpInitSystemPhase1().
Variable Documentation
LIST_ENTRY ExNPagedLookasideListHead
Definition at line 61 of file lookasid.c.
Referenced by ExpGetLookasideInformation(), and ExpInitSystemPhase0().
KSPIN_LOCK ExNPagedLookasideLock
Definition at line 62 of file lookasid.c.
Referenced by ExAdjustLookasideDepth(), ExDeleteNPagedLookasideList(), ExInitializeNPagedLookasideList(), ExpGetLookasideInformation(), and ExpInitSystemPhase0().
LIST_ENTRY ExPagedLookasideListHead
Definition at line 63 of file lookasid.c.
Referenced by ExpGetLookasideInformation(), and ExpInitSystemPhase0().
KSPIN_LOCK ExPagedLookasideLock
Definition at line 64 of file lookasid.c.
Referenced by ExAdjustLookasideDepth(), ExDeletePagedLookasideList(), ExInitializePagedLookasideList(), ExpGetLookasideInformation(), and ExpInitSystemPhase0().
PVOID ExpControlKey[2]
HANDLE ExpDefaultErrorPort
Definition at line 73 of file harderr.c.
Referenced by ExpRaiseHardError(), and NtSetDefaultHardErrorPort().
PEPROCESS ExpDefaultErrorPortProcess
Definition at line 63 of file harderr.c.
FAST_MUTEX ExpEnvironmentLock
Referenced by ExpInitSystemPhase0().
LIST_ENTRY ExpFirmwareTableProviderListHead
Definition at line 106 of file sysinfo.c.
Referenced by ExpInitSystemPhase0().
ERESOURCE ExpFirmwareTableResource
Definition at line 112 of file sysinfo.c.
Referenced by ExpInitSystemPhase0().
const EXP_INITIALIZE_GLOBAL_CALLBACKS ExpInitializeCallback[]
Definition at line 65 of file exdata.c.
Referenced by ExpInitializeCallbacks().
BOOLEAN ExpInTextModeSetup
Referenced by ExpInitializeExecutive().
ERESOURCE ExpKeyManipLock
Referenced by ExpInitSystemPhase0().
ULONG ExpNtExpirationData[3]
Definition at line 266 of file exp.h.
LIST_ENTRY ExPoolLookasideListHead
Definition at line 65 of file lookasid.c.
Referenced by ExpGetLookasideInformation(), ExpInitSystemPhase0(), ExpInitSystemPhase1(), and ExQueryPoolUsage().
HANDLE ExpProductTypeKey
HANDLE ExpSetupKey
Definition at line 269 of file exp.h.
BOOLEAN ExpSetupModeDetected
Definition at line 267 of file exp.h.
LARGE_INTEGER ExpSetupSystemPrefix
Definition at line 268 of file exp.h.
GENERAL_LOOKASIDE ExpSmallNPagedPoolLookasideLists[POOL_SMALL_LISTS]
Definition at line 367 of file pool.c.
Referenced by ExInitPoolLookasidePointers(), ExpInitSystemPhase0(), and ExpScanSystemLookasideList().
GENERAL_LOOKASIDE ExpSmallPagedPoolLookasideLists[POOL_SMALL_LISTS]
Definition at line 369 of file pool.c.
Referenced by ExInitPoolLookasidePointers(), ExpInitSystemPhase0(), and ExpScanSystemLookasideList().
BOOLEAN ExpSystemPrefixValid
Definition at line 270 of file exp.h.
BOOLEAN ExpTooLateForErrors
Definition at line 72 of file harderr.c.
Referenced by ExRaiseHardError().
const WCHAR ExpWstrCallback[]
Definition at line 63 of file exdata.c.
Referenced by ExpInitializeCallbacks().