Windows Research Kernel v1.2: C:/Windows Research Kernel/se/seassign.c File Reference
seassign.c File Reference
#include "pch.h"
Functions
NTSTATUS SeAssignSecurity (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR *NewDescriptor, __in BOOLEAN IsDirectoryObject, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
NTSTATUS SeAssignSecurityEx (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR *NewDescriptor, __in_opt GUID *ObjectType, __in BOOLEAN IsDirectoryObject, __in ULONG AutoInheritFlags, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
NTSTATUS SeAssignWorldSecurityDescriptor (__inout_bcount_part(*Length,*Length) PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __in PSECURITY_INFORMATION SecurityInformation)
NTSTATUS SeDeassignSecurity (__deref_inout PSECURITY_DESCRIPTOR *SecurityDescriptor)
NTSTATUS SepInheritAcl (IN PACL Acl, IN BOOLEAN IsDirectoryObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerSid OPTIONAL, IN PSID ClientSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN POOL_TYPE PoolType, OUT PACL *NewAcl)
NTSTATUS SepInheritAcl (IN PACL Acl, IN BOOLEAN IsDirectoryObject, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN POOL_TYPE PoolType, OUT PACL *NewAcl)
Function Documentation
NTSTATUS SeAssignSecurity (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR * NewDescriptor, __in BOOLEAN IsDirectoryObject, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
Definition at line 76 of file seassign.c.
References ARGUMENT_PRESENT, NT_SUCCESS, NULL, PAGED_CODE, RtlpNewSecurityObject(), SE_DACL_AUTO_INHERITED, SE_DACL_PRESENT, SE_SACL_AUTO_INHERITED, SE_SACL_PRESENT, SEF_DACL_AUTO_INHERIT, SEF_SACL_AUTO_INHERIT, Status, and UNREFERENCED_PARAMETER.
Referenced by CmpDoCreateChild(), and ObAssignSecurity().
NTSTATUS SeAssignSecurityEx (__in_opt PSECURITY_DESCRIPTOR ParentDescriptor, __in_opt PSECURITY_DESCRIPTOR ExplicitDescriptor, __out PSECURITY_DESCRIPTOR * NewDescriptor, __in_opt GUID * ObjectType, __in BOOLEAN IsDirectoryObject, __in ULONG AutoInheritFlags, __in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PGENERIC_MAPPING GenericMapping, __in POOL_TYPE PoolType)
Definition at line 216 of file seassign.c.
References ARGUMENT_PRESENT, NT_SUCCESS, NULL, PAGED_CODE, RtlpNewSecurityObject(), Status, and UNREFERENCED_PARAMETER.
NTSTATUS SeAssignWorldSecurityDescriptor (__inout_bcount_part *,*Length PSECURITY_DESCRIPTOR SecurityDescriptor, __inout PULONG Length, __in PSECURITY_INFORMATION SecurityInformation)
Definition at line 519 of file seassign.c.
References ARGUMENT_PRESENT, DACL_SECURITY_INFORMATION, _SECURITY_DESCRIPTOR_RELATIVE::Group, GROUP_SECURITY_INFORMATION, NT_SUCCESS, _SECURITY_DESCRIPTOR_RELATIVE::Owner, OWNER_SECURITY_INFORMATION, PAGED_CODE, RtlCopyMemory, RtlCreateSecurityDescriptorRelative(), RtlPointerToOffset, RtlpSetControlBits, SACL_SECURITY_INFORMATION, SE_DACL_PRESENT, SE_SACL_PRESENT, SE_SELF_RELATIVE, SECURITY_DESCRIPTOR_REVISION, SeLengthSid, SeWorldSid, Status, STATUS_ACCESS_DENIED, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by IopGetSetSecurityObject().
NTSTATUS SeDeassignSecurity (__deref_inout PSECURITY_DESCRIPTOR * SecurityDescriptor)
Definition at line 362 of file seassign.c.
References ExFreePool(), NULL, PAGED_CODE, and STATUS_SUCCESS.
Referenced by CmpDoCreateChild(), and ObAssignSecurity().
NTSTATUS SepInheritAcl (IN PACL Acl, IN BOOLEAN IsDirectoryObject, IN PSID OwnerSid, IN PSID GroupSid, IN PSID ServerSid OPTIONAL, IN PSID ClientSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN POOL_TYPE PoolType, OUT PACL * NewAcl)
NTSTATUS SepInheritAcl (IN PACL Acl, IN BOOLEAN IsDirectoryObject, IN PSID ClientOwnerSid, IN PSID ClientGroupSid, IN PSID ServerOwnerSid OPTIONAL, IN PSID ServerGroupSid OPTIONAL, IN PGENERIC_MAPPING GenericMapping, IN POOL_TYPE PoolType, OUT PACL * NewAcl)
Definition at line 405 of file seassign.c.
References ASSERT, FALSE, NULL, PAGED_CODE, PagedPool, RtlpInheritAcl(), Status, and STATUS_NO_INHERITANCE.