Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/gateobj.c File Reference
gateobj.c File Reference
#include "ki.h"
Functions
VOID FASTCALL KeInitializeGate (__out PKGATE Gate)
VOID FASTCALL KeSignalGateBoostPriority (__inout PKGATE Gate)
VOID FASTCALL KeWaitForGate (__inout PKGATE Gate, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode)
Function Documentation
VOID FASTCALL KeInitializeGate (__out PKGATE Gate)
Definition at line 24 of file gateobj.c.
References GateObject, and InitializeListHead().
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), and KeInitializeGuardedMutex().
VOID FASTCALL KeSignalGateBoostPriority (__inout PKGATE Gate)
Definition at line 59 of file gateobj.c.
References AdjustBoost, _KTHREAD::AdjustIncrement, _KTHREAD::AdjustReason, ASSERT, ASSERT_GATE, _KTHREAD::BasePriority, CLOCK_QUANTUM_DECREMENT, CONTAINING_RECORD, _KQUEUE::CurrentCount, _KTHREAD::DeferredProcessor, DeferredReady, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiAcquireKobjectLock(), KiDeferredReadyThread(), KiExitDispatcher(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseKobjectLock(), KiReleaseThreadLock(), KiTryToAcquireThreadLock(), KiUnlockDispatcherDatabaseFromSynchLevel, LOW_REALTIME_PRIORITY, NULL, _KPRCB::Number, Priority, _KTHREAD::Priority, _KTHREAD::PriorityDecrement, _KTHREAD::Quantum, _KTHREAD::Queue, RemoveEntryList(), _KTHREAD::State, STATUS_SUCCESS, _KWAIT_BLOCK::Thread, TRUE, and _KTHREAD::WaitStatus.
Referenced by ExfWakePushLock(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
VOID FASTCALL KeWaitForGate (__inout PKGATE Gate, __in KWAIT_REASON WaitReason, __in KPROCESSOR_MODE WaitMode)
Definition at line 204 of file gateobj.c.
References APC_LEVEL, _KTHREAD::ApcQueueLock, _KTHREAD::ApcState, ASSERT, ASSERT_GATE, DISPATCH_LEVEL, _KTHREAD::GateObject, GateWait, InsertTailList(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), _KAPC_STATE::KernelApcPending, KiAcquireKobjectLock(), KiAcquireThreadLock(), KiActivateWaiterQueue(), KiLockDispatcherDatabaseAtSynchLevel, KiReleaseKobjectLock(), KiReleaseThreadLock(), KiSetContextSwapBusy(), KiSwapThread(), KiUnlockDispatcherDatabaseFromSynchLevel, NULL, _KWAIT_BLOCK::Object, _KLOCK_QUEUE_HANDLE::OldIrql, _KTHREAD::Queue, _KTHREAD::SpecialApcDisable, _KTHREAD::State, STATUS_SUCCESS, _KWAIT_BLOCK::Thread, TRUE, _KTHREAD::WaitBlock, _KTHREAD::WaitIrql, _KWAIT_BLOCK::WaitListEntry, _KTHREAD::WaitMode, and _KTHREAD::WaitReason.
Referenced by ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), KiAcquireFastMutex(), and KiAcquireGuardedMutex().