Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/callback.c File Reference
callback.c File Reference
#include "exp.h"
Data Structures
struct _CALLBACK_OBJECT
struct _CALLBACK_REGISTRATION
Macros
#define CALLBACK_ALL_ACCESS
#define CALLBACK_MODIFY_STATE 0x0001
Typedefs
typedef struct _CALLBACK_OBJECT CALLBACK_OBJECT
typedef struct _CALLBACK_REGISTRATION CALLBACK_REGISTRATION
typedef struct _CALLBACK_OBJECT * PCALLBACK_OBJECT
typedef struct _CALLBACK_REGISTRATION * PCALLBACK_REGISTRATION
Functions
PEX_CALLBACK_ROUTINE_BLOCK ExAllocateCallBack (IN PEX_CALLBACK_FUNCTION Function, IN PVOID Context)
NTSTATUS ExCallCallBack (IN OUT PEX_CALLBACK CallBack, IN PVOID Argument1, IN PVOID Argument2)
BOOLEAN ExCompareExchangeCallBack (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK NewBlock, IN PEX_CALLBACK_ROUTINE_BLOCK OldBlock)
NTSTATUS ExCreateCallback (__deref_out PCALLBACK_OBJECT *CallbackObject, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN Create, __in BOOLEAN AllowMultipleCallbacks)
VOID ExDereferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
VOID ExFreeCallBack (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
PVOID ExGetCallBackBlockContext (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
PEX_CALLBACK_FUNCTION ExGetCallBackBlockRoutine (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
VOID ExInitializeCallBack (IN OUT PEX_CALLBACK CallBack)
VOID ExNotifyCallback (__in PCALLBACK_OBJECT CallbackObject, __in_opt PVOID Argument1, __in_opt PVOID Argument2)
VOID ExpDeleteCallback (IN PCALLBACK_OBJECT CallbackObject)
BOOLEAN ExpInitializeCallbacks ()
PEX_CALLBACK_ROUTINE_BLOCK ExReferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack)
PVOID ExRegisterCallback (__inout PCALLBACK_OBJECT CallbackObject, __in PCALLBACK_FUNCTION CallbackFunction, __in_opt PVOID CallbackContext)
VOID ExUnregisterCallback (__inout PVOID CbRegistration)
VOID ExWaitForCallBacks (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Variables
POBJECT_TYPE ExCallbackObjectType
KEVENT ExpCallbackEvent
EX_PUSH_LOCK ExpCallBackFlush
const GENERIC_MAPPING ExpCallbackMapping
const BOOLEAN ExpCallBackReturnRefs = FALSE
Macro Definition Documentation
#define CALLBACK_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|\
                             CALLBACK_MODIFY_STATE )
Definition at line 35 of file callback.c.
Referenced by ExpInitializeCallbacks().
#define CALLBACK_MODIFY_STATE 0x0001
Definition at line 33 of file callback.c.
Typedef Documentation
typedef struct _CALLBACK_OBJECT CALLBACK_OBJECT
typedef struct _CALLBACK_REGISTRATION CALLBACK_REGISTRATION
typedef struct _CALLBACK_OBJECT * PCALLBACK_OBJECT
typedef struct _CALLBACK_REGISTRATION * PCALLBACK_REGISTRATION
Function Documentation
PEX_CALLBACK_ROUTINE_BLOCK ExAllocateCallBack (IN PEX_CALLBACK_FUNCTION Function, IN PVOID Context)
Definition at line 801 of file callback.c.
References _EX_CALLBACK_ROUTINE_BLOCK::Context, ExAllocatePoolWithTag, ExInitializeRundownProtection(), _EX_CALLBACK_ROUTINE_BLOCK::Function, NULL, PagedPool, and _EX_CALLBACK_ROUTINE_BLOCK::RundownProtect.
Referenced by CmRegisterCallback(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
NTSTATUS ExCallCallBack (IN OUT PEX_CALLBACK CallBack, IN PVOID Argument1, IN PVOID Argument2)
Definition at line 1138 of file callback.c.
References _EX_CALLBACK_ROUTINE_BLOCK::Context, ExDereferenceCallBackBlock(), ExReferenceCallBackBlock(), _EX_CALLBACK_ROUTINE_BLOCK::Function, Status, and STATUS_SUCCESS.
BOOLEAN ExCompareExchangeCallBack (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK NewBlock, IN PEX_CALLBACK_ROUTINE_BLOCK OldBlock)
Definition at line 888 of file callback.c.
References ASSERTMSG, ExAcquireReleasePushLockExclusive(), ExAcquireRundownProtectionEx(), ExFastRefCompareSwapObject(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefGetUnusedReferences(), ExReleaseRundownProtectionEx(), FALSE, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, _EX_CALLBACK_ROUTINE_BLOCK::RundownProtect, and TRUE.
Referenced by CmRegisterCallback(), CmUnRegisterCallback(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
NTSTATUS ExCreateCallback (__deref_out PCALLBACK_OBJECT * CallbackObject, __in POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN Create, __in BOOLEAN AllowMultipleCallbacks)
Definition at line 264 of file callback.c.
References _CALLBACK_OBJECT::AllowMultipleCallbacks, FILE_READ_DATA, Handle, InitializeListHead(), KeInitializeSpinLock(), KernelMode, _CALLBACK_OBJECT::Lock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, PAGED_CODE, _CALLBACK_OBJECT::RegisteredCallbacks, _CALLBACK_OBJECT::Signature, Status, STATUS_UNSUCCESSFUL, and ZwClose().
Referenced by ExpInitializeCallbacks().
VOID ExDereferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack, IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 1111 of file callback.c.
References ExFastRefDereference(), ExpCallBackReturnRefs, and ExReleaseRundownProtection().
Referenced by CmpCallCallBacks(), CmUnRegisterCallback(), ExCallCallBack(), PsCallImageNotifyRoutines(), PspCreateThread(), PspExitProcess(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
VOID ExFreeCallBack (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 836 of file callback.c.
References ExFreePool().
Referenced by CmRegisterCallback(), CmUnRegisterCallback(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), and PsSetLoadImageNotifyRoutine().
PVOID ExGetCallBackBlockContext (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 1087 of file callback.c.
Referenced by CmpCallCallBacks(), and CmUnRegisterCallback().
PEX_CALLBACK_FUNCTION ExGetCallBackBlockRoutine (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 1064 of file callback.c.
Referenced by CmpCallCallBacks(), PsCallImageNotifyRoutines(), PspCreateThread(), PspExitProcess(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
VOID ExInitializeCallBack (IN OUT PEX_CALLBACK CallBack)
Definition at line 777 of file callback.c.
References ExFastRefInitialize(), and NULL.
Referenced by CmpInitCallback(), and PspInitPhase0().
VOID ExNotifyCallback (__in PCALLBACK_OBJECT CallbackObject, __in_opt PVOID Argument1, __in_opt PVOID Argument2)
Definition at line 621 of file callback.c.
References _CALLBACK_REGISTRATION::Busy, _CALLBACK_REGISTRATION::CallbackContext, _CALLBACK_REGISTRATION::CallbackFunction, CONTAINING_RECORD, DISPATCH_LEVEL, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeAcquireSpinLock, KeReleaseSpinLock(), KeSetEvent(), NULL, and _CALLBACK_REGISTRATION::UnregisterWaiting.
VOID ExpDeleteCallback (IN PCALLBACK_OBJECT CallbackObject)
Definition at line 422 of file callback.c.
References ASSERT, IsListEmpty, and UNREFERENCED_PARAMETER.
Referenced by ExpInitializeCallbacks().
BOOLEAN ExpInitializeCallbacks ()
Definition at line 138 of file callback.c.
References CALLBACK_ALL_ACCESS, EXP_INITIALIZE_GLOBAL_CALLBACKS::CallBackObject, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, DIRECTORY_ALL_ACCESS, ExCreateCallback(), ExInitializePushLock(), ExpCallbackMapping, ExpDeleteCallback(), ExpInitializeCallback, ExpWstrCallback, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, InitializeObjectAttributes, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KeInitializeEvent(), _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NotificationEvent, NT_SUCCESS, NtClose(), NtCreateDirectoryObject(), NULL, ObCreateObjectType(), OBJ_CASE_INSENSITIVE, OBJ_OPENLINK, OBJ_PERMANENT, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, SePublicDefaultSd, Status, TRUE, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
PEX_CALLBACK_ROUTINE_BLOCK ExReferenceCallBackBlock (IN OUT PEX_CALLBACK CallBack)
Definition at line 973 of file callback.c.
References ExAcquirePushLockExclusive(), ExAcquireRundownProtection(), ExAcquireRundownProtectionEx(), ExFastRefAddAdditionalReferenceCounts(), ExFastRefCanBeReferenced(), ExFastReference(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefIsLastReference(), ExFastRefObjectNull(), ExpCallBackReturnRefs, ExReleasePushLockExclusive(), ExReleaseRundownProtectionEx(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, and _EX_CALLBACK_ROUTINE_BLOCK::RundownProtect.
Referenced by CmpCallCallBacks(), CmUnRegisterCallback(), ExCallCallBack(), PsCallImageNotifyRoutines(), PspCreateThread(), PspExitProcess(), PspExitThread(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
PVOID ExRegisterCallback (__inout PCALLBACK_OBJECT CallbackObject, __in PCALLBACK_FUNCTION CallbackFunction, __in_opt PVOID CallbackContext)
Definition at line 434 of file callback.c.
References ASSERT, _CALLBACK_REGISTRATION::Busy, _CALLBACK_REGISTRATION::CallbackContext, _CALLBACK_REGISTRATION::CallbackFunction, _CALLBACK_REGISTRATION::CallbackObject, DISPATCH_LEVEL, ExAllocatePoolWithTag, ExFreePool(), FALSE, InsertTailList(), IsListEmpty, KeAcquireSpinLock, KeGetCurrentIrql(), KeReleaseSpinLock(), _CALLBACK_REGISTRATION::Link, NonPagedPool, NULL, ObDereferenceObject(), ObReferenceObject, TRUE, and _CALLBACK_REGISTRATION::UnregisterWaiting.
VOID ExUnregisterCallback (__inout PVOID CbRegistration)
Definition at line 537 of file callback.c.
References ASSERT, _CALLBACK_REGISTRATION::Busy, _CALLBACK_REGISTRATION::CallbackObject, DISPATCH_LEVEL, Executive, ExFreePool(), FALSE, KeAcquireSpinLock, KeClearEvent(), KeGetCurrentIrql(), KeReleaseSpinLock(), KernelMode, KeWaitForSingleObject(), _CALLBACK_REGISTRATION::Link, _CALLBACK_OBJECT::Lock, NULL, ObDereferenceObject(), RemoveEntryList(), TRUE, and _CALLBACK_REGISTRATION::UnregisterWaiting.
VOID ExWaitForCallBacks (IN PEX_CALLBACK_ROUTINE_BLOCK CallBackBlock)
Definition at line 860 of file callback.c.
References ExWaitForRundownProtectionRelease().
Referenced by CmUnRegisterCallback(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), and PsSetCreateProcessNotifyRoutine().
Variable Documentation
POBJECT_TYPE ExCallbackObjectType
Definition at line 70 of file callback.c.
KEVENT ExpCallbackEvent
Definition at line 44 of file callback.c.
EX_PUSH_LOCK ExpCallBackFlush
Definition at line 50 of file callback.c.
const GENERIC_MAPPING ExpCallbackMapping
Initial value:
= {
    STANDARD_RIGHTS_READ ,
    STANDARD_RIGHTS_WRITE | CALLBACK_MODIFY_STATE,
    STANDARD_RIGHTS_EXECUTE | SYNCHRONIZE,
    CALLBACK_ALL_ACCESS
}
Definition at line 80 of file callback.c.
Referenced by ExpInitializeCallbacks().
const BOOLEAN ExpCallBackReturnRefs = FALSE
Definition at line 62 of file callback.c.
Referenced by ExDereferenceCallBackBlock(), and ExReferenceCallBackBlock().