Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obquery.c File Reference
obquery.c File Reference
#include "obp.h"
Data Structures
struct __OBP_SET_HANDLE_ATTRIBUTES
Macros
#define OBP_MISSING_NAME_LITERAL L"..."
#define OBP_MISSING_NAME_LITERAL_SIZE (sizeof(OBP_MISSING_NAME_LITERAL) - sizeof(UNICODE_NULL))
Typedefs
typedef struct __OBP_SET_HANDLE_ATTRIBUTES OBP_SET_HANDLE_ATTRIBUTES
typedef struct __OBP_SET_HANDLE_ATTRIBUTES * POBP_SET_HANDLE_ATTRIBUTES
Functions
NTSTATUS NtQueryObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __out_bcount_opt(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NTAPI NtSetInformationObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __in_bcount(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength)
NTSTATUS ObpQueryNameString (IN PVOID Object, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
BOOLEAN ObpSetHandleAttributes (IN OUT PVOID TableEntry, IN ULONG_PTR Parameter)
BOOLEAN ObpSetHandleAttributes (IN OUT PHANDLE_TABLE_ENTRY ObjectTableEntry, IN ULONG_PTR Parameter)
NTSTATUS ObQueryNameString (__in PVOID Object, __out_bcount(Length) POBJECT_NAME_INFORMATION ObjectNameInfo, __in ULONG Length, __out PULONG ReturnLength)
NTSTATUS ObQueryObjectAuditingByHandle (__in HANDLE Handle, __out PBOOLEAN GenerateOnClose)
NTSTATUS ObQueryTypeInfo (IN POBJECT_TYPE ObjectType, OUT POBJECT_TYPE_INFORMATION ObjectTypeInfo, IN ULONG Length, OUT PULONG ReturnLength)
NTSTATUS ObQueryTypeName (IN PVOID Object, PUNICODE_STRING ObjectTypeName, IN ULONG Length, OUT PULONG ReturnLength)
NTSTATUS ObSetHandleAttributes (__in HANDLE Handle, __in POBJECT_HANDLE_FLAG_INFORMATION HandleFlags, __in KPROCESSOR_MODE PreviousMode)
Macro Definition Documentation
#define OBP_MISSING_NAME_LITERAL L"..."
Definition at line 790 of file obquery.c.
Referenced by ObpQueryNameString().
#define OBP_MISSING_NAME_LITERAL_SIZE (sizeof(OBP_MISSING_NAME_LITERAL) - sizeof(UNICODE_NULL))
Definition at line 791 of file obquery.c.
Referenced by ObpQueryNameString().
Typedef Documentation
typedef struct __OBP_SET_HANDLE_ATTRIBUTES OBP_SET_HANDLE_ATTRIBUTES
typedef struct __OBP_SET_HANDLE_ATTRIBUTES * POBP_SET_HANDLE_ATTRIBUTES
Function Documentation
NTSTATUS NtQueryObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __out_bcount_opt(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength, __out_opt PULONG ReturnLength)
Definition at line 53 of file obquery.c.
References ALIGN_UP, ARGUMENT_PRESENT, ASSERT, _OBJECT_BASIC_INFORMATION::Attributes, _OBJECT_BASIC_INFORMATION::CreationTime, DACL_SECURITY_INFORMATION, _OBJECT_HEADER_NAME_INFO::Directory, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _OBJECT_HEADER::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_BASIC_INFORMATION::GrantedAccess, _OBJECT_HANDLE_INFORMATION::GrantedAccess, GROUP_SECURITY_INFORMATION, _OBJECT_HANDLE_INFORMATION::HandleAttributes, _OBJECT_BASIC_INFORMATION::HandleCount, _OBJECT_HEADER::HandleCount, _OBJECT_HANDLE_FLAG_INFORMATION::Inherit, KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_TYPE::Name, _OBJECT_HEADER_NAME_INFO::Name, _OBJECT_BASIC_INFORMATION::NameInfoSize, _OBJECT_BASIC_INFORMATION::NonPagedPoolCharge, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NT_SUCCESS, NULL, _OBJECT_TYPES_INFORMATION::NumberOfTypes, OB_FLAG_EXCLUSIVE_OBJECT, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), ObfReferenceObject(), OBJ_EXCLUSIVE, OBJ_INHERIT, OBJ_NAME_PATH_SEPARATOR, OBJ_PERMANENT, OBJ_PROTECT_CLOSE, OBJECT_HEADER_TO_QUOTA_INFO(), OBJECT_TO_OBJECT_HEADER, ObjectBasicInformation, ObjectHandleFlagInformation, ObjectNameInformation, ObjectTypeInformation, ObjectTypesInformation, OBP_MAX_DEFINED_OBJECT_TYPES, ObpDereferenceNameInfo(), ObpObjectTypes, ObpQueryNameString(), ObpReferenceNameInfo(), ObpSymbolicLinkObjectType, ObQueryTypeInfo(), ObReferenceObjectByHandle, OWNER_SECURITY_INFORMATION, PAGED_CODE, _OBJECT_BASIC_INFORMATION::PagedPoolCharge, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, _OBJECT_BASIC_INFORMATION::PointerCount, _OBJECT_HEADER::PointerCount, _OBJECT_TYPE_INITIALIZER::PoolType, ProbeForWrite(), ProbeForWriteUlong, _OBJECT_HANDLE_FLAG_INFORMATION::ProtectFromClose, QuerySecurityDescriptor, READ_CONTROL, RtlZeroMemory, SACL_SECURITY_INFORMATION, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_BASIC_INFORMATION::SecurityDescriptorSize, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, _OBJECT_BASIC_INFORMATION::TypeInfoSize, _OBJECT_TYPE_INFORMATION::TypeName, and UNICODE_NULL.
Referenced by IopLoadDriver().
NTSTATUS NTAPI NtSetInformationObject (__in HANDLE Handle, __in OBJECT_INFORMATION_CLASS ObjectInformationClass, __in_bcount(ObjectInformationLength) PVOID ObjectInformation, __in ULONG ObjectInformationLength)
Definition at line 657 of file obquery.c.
References except, ExSystemExceptionFilter(), KeGetPreviousMode, KernelMode, NT_SUCCESS, ObDereferenceObject(), ObjectHandleFlagInformation, ObjectSessionInformation, ObpDirectoryObjectType, ObpInitializeLookupContext(), ObpLockDirectoryExclusive(), ObpUnlockDirectory(), ObReferenceObjectByHandle, ObSetHandleAttributes(), PAGED_CODE, ProbeForRead, PsGetCurrentProcessSessionId(), SeSinglePrivilegeCheck(), _OBJECT_DIRECTORY::SessionId, SeTcbPrivilege, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and STATUS_PRIVILEGE_NOT_HELD.
NTSTATUS ObpQueryNameString (IN PVOID Object, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 839 of file obquery.c.
References _UNICODE_STRING::Buffer, _OBJECT_HEADER_NAME_INFO::Directory, except, EXCEPTION_EXECUTE_HANDLER, FALSE, leave, _UNICODE_STRING::Length, MAXUSHORT, _OBJECT_HEADER_NAME_INFO::Name, NULL, ObDereferenceObject(), ObfReferenceObject(), OBJ_NAME_PATH_SEPARATOR, OBJECT_TO_OBJECT_HEADER, OBP_MISSING_NAME_LITERAL, OBP_MISSING_NAME_LITERAL_SIZE, ObpBeginTypeSpecificCallOut, ObpDereferenceNameInfo(), ObpEndTypeSpecificCallOut, ObpReferenceNameInfo(), ObpRootDirectoryObject, PAGED_CODE, _OBJECT_TYPE_INITIALIZER::QueryNameProcedure, RtlCopyMemory, RtlMoveMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NAME_TOO_LONG, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNICODE_NULL.
Referenced by NtQueryObject(), and ObQueryNameString().
BOOLEAN ObpSetHandleAttributes (IN OUT PVOID TableEntry, IN ULONG_PTR Parameter)
Referenced by ObSetHandleAttributes().
BOOLEAN ObpSetHandleAttributes (IN OUT PHANDLE_TABLE_ENTRY ObjectTableEntry, IN ULONG_PTR Parameter)
Definition at line 1772 of file obquery.c.
References FALSE, _OBJECT_HANDLE_FLAG_INFORMATION::Inherit, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, OBJ_HANDLE_ATTRIBUTES, OBJ_INHERIT, __OBP_SET_HANDLE_ATTRIBUTES::ObjectInformation, ObpAccessProtectCloseBit, _OBJECT_HANDLE_FLAG_INFORMATION::ProtectFromClose, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
NTSTATUS ObQueryNameString (__in PVOID Object, __out_bcount(Length) POBJECT_NAME_INFORMATION ObjectNameInfo, __in ULONG Length, __out PULONG ReturnLength)
Definition at line 794 of file obquery.c.
References KernelMode, and ObpQueryNameString().
Referenced by CmpAcquireFileObjectForFile(), IopErrorLogThread(), IopQueryNameInternal(), IopRaiseHardError(), MmGetFileNameForAddress(), MmGetFileNameForSection(), NtQueryVirtualMemory(), ObGetObjectInformation(), PerfInfoFileNameRunDown(), SeInitializeProcessAuditName(), SepQueryNameString(), and WmipTraceFile().
NTSTATUS ObQueryObjectAuditingByHandle (__in HANDLE Handle, __out PBOOLEAN GenerateOnClose)
Definition at line 1618 of file obquery.c.
References DecodeKernelHandle, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), FALSE, IsKernelHandle, KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_AUDIT_OBJECT_CLOSE, ObpKernelHandleTable, ObpValidateIrql, PAGED_CODE, PsGetCurrentProcessByThread, PsGetCurrentThread(), Status, STATUS_INVALID_HANDLE, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
NTSTATUS ObQueryTypeInfo (IN POBJECT_TYPE ObjectType, OUT POBJECT_TYPE_INFORMATION ObjectTypeInfo, IN ULONG Length, OUT PULONG ReturnLength)
Definition at line 1515 of file obquery.c.
References ALIGN_UP, except, EXCEPTION_EXECUTE_HANDLER, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtQueryObject().
NTSTATUS ObQueryTypeName (IN PVOID Object, PUNICODE_STRING ObjectTypeName, IN ULONG Length, OUT PULONG ReturnLength)
Definition at line 1392 of file obquery.c.
References _UNICODE_STRING::Buffer, except, EXCEPTION_EXECUTE_HANDLER, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_TYPE::Name, OBJECT_TO_OBJECT_HEADER, PAGED_CODE, RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _OBJECT_HEADER::Type, and UNICODE_NULL.
Referenced by ObGetObjectInformation(), and SepQueryTypeString().
NTSTATUS ObSetHandleAttributes (__in HANDLE Handle, __in POBJECT_HANDLE_FLAG_INFORMATION HandleFlags, __in KPROCESSOR_MODE PreviousMode)
Definition at line 573 of file obquery.c.
References DecodeKernelHandle, ExChangeHandle(), FALSE, Handle, IsKernelHandle, KeStackAttachProcess(), KeUnstackDetachProcess(), __OBP_SET_HANDLE_ATTRIBUTES::ObjectInformation, ObpGetObjectTable, ObpKernelHandleTable, ObpSetHandleAttributes(), PAGED_CODE, _EPROCESS::Pcb, __OBP_SET_HANDLE_ATTRIBUTES::PreviousMode, PsGetCurrentProcess(), PsInitialSystemProcess, Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, and TRUE.
Referenced by NtSetInformationObject().