Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/event.c File Reference
event.c File Reference
#include "exp.h"
Functions
BOOLEAN ExpEventInitialization (VOID)
NTSTATUS NtClearEvent (__in HANDLE EventHandle)
NTSTATUS NtCreateEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in EVENT_TYPE EventType, __in BOOLEAN InitialState)
NTSTATUS NtOpenEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtPulseEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
NTSTATUS NtQueryEvent (__in HANDLE EventHandle, __in EVENT_INFORMATION_CLASS EventInformationClass, __out_bcount(EventInformationLength) PVOID EventInformation, __in ULONG EventInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtResetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
NTSTATUS NtSetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
NTSTATUS NtSetEventBoostPriority (__in HANDLE EventHandle)
Variables
POBJECT_TYPE ExEventObjectType
ULONG ExpEventBoost = EVENT_INCREMENT
const GENERIC_MAPPING ExpEventMapping
Function Documentation
BOOLEAN ExpEventInitialization (VOID)
Definition at line 65 of file event.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, EVENT_ALL_ACCESS, ExpEventMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), RtlZeroMemory, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
NTSTATUS NtClearEvent (__in HANDLE EventHandle)
Definition at line 125 of file event.c.
References EVENT_MODIFY_STATE, KeClearEvent(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, and Status.
NTSTATUS NtCreateEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in EVENT_TYPE EventType, __in BOOLEAN InitialState)
Definition at line 180 of file event.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KeInitializeEvent(), KernelMode, NOTHING, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, Status, STATUS_INVALID_PARAMETER, and SynchronizationEvent.
Referenced by IoInitSystem(), and SepInitializationPhase1().
NTSTATUS NtOpenEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 305 of file event.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSTATUS NtPulseEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
Definition at line 395 of file event.c.
References ARGUMENT_PRESENT, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, ExpEventBoost, FALSE, KeGetPreviousMode, KePulseEvent(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSTATUS NtQueryEvent (__in HANDLE EventHandle, __in EVENT_INFORMATION_CLASS EventInformationClass, __out_bcount(EventInformationLength) PVOID EventInformation, __in ULONG EventInformationLength, __out_opt PULONG ReturnLength)
Definition at line 489 of file event.c.
References ARGUMENT_PRESENT, EVENT_QUERY_STATE, EventBasicInformation, _EVENT_BASIC_INFORMATION::EventState, _EVENT_BASIC_INFORMATION::EventType, except, EXCEPTION_EXECUTE_HANDLER, _KEVENT::Header, KeGetPreviousMode, KeReadStateEvent(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and _DISPATCHER_HEADER::Type.
NTSTATUS NtResetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
Definition at line 620 of file event.c.
References ARGUMENT_PRESENT, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeResetEvent(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSTATUS NtSetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
Definition at line 712 of file event.c.
References ARGUMENT_PRESENT, EVENT_MODIFY_STATE, except, ExpEventBoost, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KernelMode, KeSetEvent(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSTATUS NtSetEventBoostPriority (__in HANDLE EventHandle)
Definition at line 800 of file event.c.
References EVENT_MODIFY_STATE, _KEVENT::Header, KeGetPreviousMode, KeSetEventBoostPriority(), NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, STATUS_OBJECT_TYPE_MISMATCH, and _DISPATCHER_HEADER::Type.
Variable Documentation
POBJECT_TYPE ExEventObjectType
Definition at line 32 of file event.c.
Referenced by BuildQueryDirectoryIrp(), IoCreateNotificationEvent(), IoCreateSynchronizationEvent(), IoInitSystem(), IopXxxControlFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
ULONG ExpEventBoost = EVENT_INCREMENT
Definition at line 26 of file event.c.
Referenced by NtPulseEvent(), and NtSetEvent().
const GENERIC_MAPPING ExpEventMapping
Initial value:
= {
    STANDARD_RIGHTS_READ | EVENT_QUERY_STATE,
    STANDARD_RIGHTS_WRITE | EVENT_MODIFY_STATE,
    STANDARD_RIGHTS_EXECUTE | SYNCHRONIZE,
    EVENT_ALL_ACCESS
}
Definition at line 43 of file event.c.
Referenced by ExpEventInitialization().