Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/imagedir.c File Reference
imagedir.c File Reference
#include "ntrtlp.h"
Functions
PVOID RtlAddressInSectionTable (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Address)
PVOID RtlImageDirectoryEntryToData (IN PVOID Base, IN BOOLEAN MappedAsImage, IN USHORT DirectoryEntry, OUT PULONG Size)
VOID RtlMakeStackTraceDataPresent (VOID)
PVOID RtlpImageDirectoryEntryToData32 (IN PVOID Base, IN BOOLEAN MappedAsImage, IN USHORT DirectoryEntry, OUT PULONG Size, PIMAGE_NT_HEADERS32 NtHeaders)
PVOID RtlpImageDirectoryEntryToData64 (IN PVOID Base, IN BOOLEAN MappedAsImage, IN USHORT DirectoryEntry, OUT PULONG Size, PIMAGE_NT_HEADERS64 NtHeaders)
VOID RtlpMakeStackTraceDataPresentForImage (IN PVOID ImageBase)
VOID RtlpTouchMemory (IN PVOID Address, IN ULONG Length)
PIMAGE_SECTION_HEADER RtlSectionTableFromVirtualAddress (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Address)
Function Documentation
PVOID RtlAddressInSectionTable (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Address)
Definition at line 89 of file imagedir.c.
References NULL, _IMAGE_SECTION_HEADER::PointerToRawData, RtlSectionTableFromVirtualAddress(), and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by LdrpAccessResourceDataNoMultipleLanguage(), RtlpImageDirectoryEntryToData32(), and RtlpImageDirectoryEntryToData64().
PVOID RtlImageDirectoryEntryToData (IN PVOID Base, IN BOOLEAN MappedAsImage, IN USHORT DirectoryEntry, OUT PULONG Size)
Definition at line 204 of file imagedir.c.
References FALSE, IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_NT_OPTIONAL_HDR64_MAGIC, LDR_DATAFILE_TO_VIEW, LDR_IS_DATAFILE, _IMAGE_OPTIONAL_HEADER::Magic, NULL, _IMAGE_NT_HEADERS::OptionalHeader, RtlImageNtHeader(), RtlpImageDirectoryEntryToData32(), and RtlpImageDirectoryEntryToData64().
Referenced by RtlpMakeStackTraceDataPresentForImage().
VOID RtlMakeStackTraceDataPresent (VOID)
Definition at line 270 of file imagedir.c.
References CONTAINING_RECORD, except, EXCEPTION_EXECUTE_HANDLER, _LIST_ENTRY::Flink, NOTHING, NtCurrentPeb, PROBE_ALIGNMENT, ProbeForReadSmallStructure, RTL_PAGED_CODE, RtlpMakeStackTraceDataPresentForImage(), and UNALIGNED.
PVOID RtlpImageDirectoryEntryToData32 (IN PVOID Base, IN BOOLEAN MappedAsImage, IN USHORT DirectoryEntry, OUT PULONG Size, PIMAGE_NT_HEADERS32 NtHeaders)
Definition at line 136 of file imagedir.c.
References _IMAGE_OPTIONAL_HEADER::DataDirectory, MM_HIGHEST_USER_ADDRESS, NULL, _IMAGE_OPTIONAL_HEADER::NumberOfRvaAndSizes, _IMAGE_NT_HEADERS::OptionalHeader, RtlAddressInSectionTable(), _IMAGE_DATA_DIRECTORY::Size, and _IMAGE_DATA_DIRECTORY::VirtualAddress.
Referenced by RtlImageDirectoryEntryToData().
PVOID RtlpImageDirectoryEntryToData64 (IN PVOID Base, IN BOOLEAN MappedAsImage, IN USHORT DirectoryEntry, OUT PULONG Size, PIMAGE_NT_HEADERS64 NtHeaders)
Definition at line 170 of file imagedir.c.
References _IMAGE_OPTIONAL_HEADER64::DataDirectory, MM_HIGHEST_USER_ADDRESS, NULL, _IMAGE_OPTIONAL_HEADER64::NumberOfRvaAndSizes, _IMAGE_NT_HEADERS64::OptionalHeader, RtlAddressInSectionTable(), _IMAGE_DATA_DIRECTORY::Size, and _IMAGE_DATA_DIRECTORY::VirtualAddress.
Referenced by RtlImageDirectoryEntryToData().
VOID RtlpMakeStackTraceDataPresentForImage (IN PVOID ImageBase)
Definition at line 368 of file imagedir.c.
References IMAGE_DIRECTORY_ENTRY_EXCEPTION, NULL, RTL_PAGED_CODE, RtlImageDirectoryEntryToData(), RtlpTouchMemory(), and TRUE.
Referenced by RtlMakeStackTraceDataPresent().
VOID RtlpTouchMemory (IN PVOID Address, IN ULONG Length)
Definition at line 414 of file imagedir.c.
References PAGE_ALIGN, PAGE_SIZE, and RTL_PAGED_CODE.
Referenced by RtlpMakeStackTraceDataPresentForImage().
PIMAGE_SECTION_HEADER RtlSectionTableFromVirtualAddress (IN PIMAGE_NT_HEADERS NtHeaders, IN PVOID Base, IN ULONG Address)
Definition at line 40 of file imagedir.c.
References IMAGE_FIRST_SECTION, NULL, _IMAGE_SECTION_HEADER::SizeOfRawData, and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by LdrpAccessResourceDataNoMultipleLanguage(), and RtlAddressInSectionTable().