Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/protect.c File Reference
protect.c File Reference
#include "mi.h"
Functions
ULONG MiChangeNoAccessForkPte (IN PMMPTE PointerPte, IN ULONG ProtectionMask)
NTSTATUS MiCheckSecuredVad (IN PMMVAD Vad, IN PVOID Base, IN SIZE_T Size, IN ULONG ProtectionMask)
VOID MiFlushTbAndCapture (IN PMMVAD FoundVad, IN PMMPTE PtePointer, IN ULONG ProtectionMask, IN PMMPFN Pfn1, IN LOGICAL CaptureDirtyBit)
WIN32_PROTECTION_MASK MiGetPageProtection (IN PMMPTE PointerPte)
NTSTATUS MiProtectVirtualMemory (IN PEPROCESS Process, IN PVOID *BaseAddress, IN PSIZE_T RegionSize, IN WIN32_PROTECTION_MASK NewProtectWin32, IN PWIN32_PROTECTION_MASK LastProtect)
NTSTATUS MiSetProtectionOnSection (IN PEPROCESS Process, IN PMMVAD FoundVad, IN PVOID StartingAddress, IN PVOID EndingAddress, IN ULONG NewProtect, OUT PULONG CapturedOldProtect, IN ULONG DontCharge, OUT PULONG Locked)
ULONG MiSetProtectionOnTransitionPte (IN PMMPTE PointerPte, IN ULONG ProtectionMask)
NTSTATUS NtProtectVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in WIN32_PROTECTION_MASK NewProtectWin32, __out PULONG OldProtect)
Variables
CCHAR MmReadWrite [32]
Function Documentation
ULONG MiChangeNoAccessForkPte (IN PMMPTE PointerPte, IN ULONG ProtectionMask)
Definition at line 2265 of file protect.c.
References FALSE, MM_NOACCESS, PAGED_CODE, and TRUE.
Referenced by MiProtectVirtualMemory(), and MiSetProtectionOnSection().
NTSTATUS MiCheckSecuredVad (IN PMMVAD Vad, IN PVOID Base, IN SIZE_T Size, IN ULONG ProtectionMask)
Definition at line 2585 of file protect.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, List, _MMSECURE_ENTRY::List, MI_IS_GUARD, MM_SECURE_DELETE_CHECK, MmReadWrite, _MMVAD_FLAGS2::ReadOnly, _MMSECURE_ENTRY::StartVpn, Status, STATUS_INVALID_PAGE_PROTECTION, STATUS_SUCCESS, _MMSECURE_ENTRY::u2, and _MMSECURE_ENTRY::VadFlags2.
Referenced by MiProtectVirtualMemory(), MiUnmapViewOfSection(), NtAllocateVirtualMemory(), and NtFreeVirtualMemory().
VOID MiFlushTbAndCapture (IN PMMVAD FoundVad, IN PMMPTE PtePointer, IN ULONG ProtectionMask, IN PMMPFN Pfn1, IN LOGICAL CaptureDirtyBit)
Definition at line 2309 of file protect.c.
References ASSERT, CacheType, FALSE, _MMPTE::Hard, LOCK_PFN, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_DISABLE_CACHING, MI_ENABLE_CACHING, MI_FLUSH_SINGLE_TB, MI_GET_WORKING_SET_FROM_PTE, MI_IS_NOCACHE, MI_IS_PTE_DIRTY, MI_IS_WRITECOMBINE, MI_MAKE_VALID_USER_PTE, MI_SET_PTE_DIRTY, MI_SET_PTE_IN_WORKING_SET, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE_NEW_PROTECTION, MiCached, MiCaptureWriteWatchDirtyBit(), MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MM_NOCACHE, MM_PROTECTION_WRITE_MASK, MM_WRITECOMBINE, MmCached, MmNonCached, MmWriteCombined, NULL, _MMPTE_HARDWARE::PageFrameNumber, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcess(), TRUE, _MMPTE::u, UNLOCK_PFN, VadWriteWatch, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Writable.
Referenced by MiProtectVirtualMemory(), and MiSetProtectionOnSection().
WIN32_PROTECTION_MASK MiGetPageProtection (IN PMMPTE PointerPte)
Definition at line 2039 of file protect.c.
References ASSERT, _MMPFN::AweAllocation, _MMPFN::e1, FALSE, _MMPTE::Hard, Index, LOCK_PFN, LOCK_WS_REGARDLESS, _MMPTE::Long, MI_CONVERT_FROM_PTE_PROTECTION, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_IS_PTE_PROTOTYPE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_PTE_OWNER_KERNEL, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiLocateWsle(), MiMakeSystemAddressValidPfn(), MiPteToProto, MM_ZERO_ACCESS, MmWorkingSetList, MmWsle, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, PAGE_NOACCESS, PAGE_READONLY, PAGE_READWRITE, PAGED_CODE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPTE::Soft, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WS_REGARDLESS, _MMPTE_SOFTWARE::Valid, _MMPTE_HARDWARE::Valid, _MMPTE_HARDWARE::Write, and _MMPFN::WsIndex.
Referenced by MiProtectVirtualMemory(), MiQueryAddressState(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
NTSTATUS MiProtectVirtualMemory (IN PEPROCESS Process, IN PVOID * BaseAddress, IN PSIZE_T RegionSize, IN WIN32_PROTECTION_MASK NewProtectWin32, IN PWIN32_PROTECTION_MASK LastProtect)
Definition at line 293 of file protect.c.
References _MI_PAGING_LEVELS, ASSERT, _MMVAD::ControlArea, _MMPFN::e1, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _MMSECTION_FLAGS::File, _CONTROL_AREA::Flags, _MMPTE::Hard, _MMSECTION_FLAGS::Image, KeAcquireGuardedMutexUnsafe(), KeGetCurrentThread(), KeIsAttachedProcess(), KeReleaseGuardedMutexUnsafe(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _MMPTE::Long, MI_CONVERT_FROM_PTE_PROTECTION, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_GUARD, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_VA_TO_VPN, MI_VPN_TO_VA, MiChangeNoAccessForkPte(), MiCheckForConflictingVad, MiCheckSecuredVad(), MiCopyOnWrite(), MiFlushTbAndCapture(), MiGetPageProtection(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsEntireRangeCommitted(), MiIsPteOnPdeBoundary, MiIsPteProtectionCompatible(), MiMakePdeExistAndMakeValid(), MiMakeProtectionMask(), MiProtectAweRegion(), MiRemovePageFromWorkingSet(), MiSetProtectionOnSection(), MiSetProtectionOnTransitionPte(), MM_INVALID_PROTECTION, MM_NOACCESS, MM_NOIRQL, MM_READONLY, MM_READWRITE, MmSectionCommitMutex, _MMVAD_FLAGS::NoChange, NOTHING, NT_SUCCESS, NULL, _MMPFN::OriginalPte, PAGE_ALIGN, PAGE_EXECUTE_READWRITE, PAGE_EXECUTE_WRITECOPY, PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_READWRITE, PAGE_SIZE, PAGE_WRITECOMBINE, PAGE_WRITECOPY, _MMPTE_HARDWARE::PageFrameNumber, _MMVAD_FLAGS::PrivateMemory, _MMPTE_SOFTWARE::Protection, _MMVAD_FLAGS::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), _MMPTE::Soft, _MMVAD::StartingVpn, Status, STATUS_ACCESS_VIOLATION, STATUS_CONFLICTING_ADDRESSES, STATUS_IN_PAGE_ERROR, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_4, STATUS_NOT_COMMITTED, STATUS_PROCESS_IS_TERMINATING, STATUS_SECTION_PROTECTION, STATUS_SUCCESS, STATUS_WAS_UNLOCKED, _KTHREAD::Teb, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMVAD::u, _MMPFN::u3, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadImageMap, VadLargePages, VadLargePageSection, VadRotatePhysical, _MMVAD_FLAGS::VadType, and _MMPTE_HARDWARE::Valid.
Referenced by NtAllocateVirtualMemory(), and NtProtectVirtualMemory().
NTSTATUS MiSetProtectionOnSection (IN PEPROCESS Process, IN PMMVAD FoundVad, IN PVOID StartingAddress, IN PVOID EndingAddress, IN ULONG NewProtect, OUT PULONG CapturedOldProtect, IN ULONG DontCharge, OUT PULONG Locked)
Definition at line 1050 of file protect.c.
References ASSERT, _MMPTE_HARDWARE::CopyOnWrite, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _MMPTE::Hard, Index, LOCK_PFN, LOCK_SYSTEM_WS, LOCK_WS_UNSAFE, _MMPTE::Long, MI_CONVERT_FROM_PTE_PROTECTION, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_PFN(), MI_IS_PTE_PROTECTION_COPY_WRITE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_SNAP_DATA, MI_VA_TO_VPN, MI_WRITE_INVALID_PTE, MiChangeNoAccessForkPte(), MiChargeCommitment(), MiCopyOnWrite(), MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiFlushTbAndCapture(), MiGetPageProtection(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiLocateWsle(), MiMakePdeExistAndMakeValid(), MiMakeProtectionMask(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiPteToProto, MiRemovePageFromWorkingSet(), MiReturnCommitment, MiSetProtectionOnTransitionPte(), MM_COPY_ON_WRITE_MASK, MM_DBG_COMMIT_RETURN_PROTECTION, MM_DBG_COMMIT_SET_PROTECTION, MM_INVALID_PROTECTION, MM_NOIRQL, MM_PROTECTION_COPY_MASK, MM_TRACK_COMMIT, MM_ZERO_ACCESS, MmWorkingSetList, MmWsle, NT_SUCCESS, NULL, _MMPFN::OriginalPte, PAGE_EXECUTE_READWRITE, PAGE_EXECUTE_WRITECOPY, PAGE_GUARD, PAGE_NOACCESS, PAGE_READWRITE, PAGE_WRITECOPY, PAGED_CODE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, PrototypePte, _MMPFNENTRY::PrototypePte, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PsChangeJobMemoryUsage(), PsChargeProcessPageFileQuota(), PsGetCurrentThread(), PsReportProcessMemoryLimitViolation(), PsReturnProcessPageFileQuota(), _MMPFN::PteAddress, SATISFY_OVERZEALOUS_COMPILER, _MMPTE::Soft, Status, STATUS_COMMITMENT_LIMIT, STATUS_GUARD_PAGE_VIOLATION, STATUS_INVALID_PAGE_PROTECTION, STATUS_PAGEFILE_QUOTA_EXCEEDED, STATUS_SUCCESS, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, UNLOCK_SYSTEM_WS, UNLOCK_WS_UNSAFE, VadImageMap, VadRotatePhysical, _MMPTE_HARDWARE::Valid, and _MMPFN::WsIndex.
Referenced by MiProtectVirtualMemory(), and NtAllocateVirtualMemory().
ULONG MiSetProtectionOnTransitionPte (IN PMMPTE PointerPte, IN ULONG ProtectionMask)
Definition at line 2521 of file protect.c.
References FALSE, LOCK_PFN, MI_PFN_ELEMENT, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, _MMPTE::Trans, TRUE, _MMPTE::u, and UNLOCK_PFN.
Referenced by MiMakeEntireImageCopyOnWrite(), MiProtectVirtualMemory(), and MiSetProtectionOnSection().
NTSTATUS NtProtectVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in WIN32_PROTECTION_MASK NewProtectWin32, __out PULONG OldProtect)
Definition at line 50 of file protect.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MM_HIGHEST_USER_ADDRESS, MM_INVALID_PROTECTION, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _EPROCESS::Pcb, ProbeForWritePointer, ProbeForWriteUlong, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, Status, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, _ETHREAD::Tcb, and TRUE.
Variable Documentation
CCHAR MmReadWrite[32]
Definition at line 42 of file acceschk.c.
Referenced by MiAccessCheck(), and MiCheckSecuredVad().