Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/apcuser.c File Reference
apcuser.c File Reference
#include "ki.h"
Functions
VOID KiInitializeUserApc (IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN PKNORMAL_ROUTINE NormalRoutine, IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Function Documentation
VOID KiInitializeUserApc (IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN PKNORMAL_ROUTINE NormalRoutine, IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 29 of file apcuser.c.
References ASSERT, C_ASSERT, CONTEXT_ALIGN, CONTEXT_ALIGNED_SIZE, CONTEXT_DEBUG_REGISTERS, CONTEXT_FULL, CONTEXT_LENGTH, CONTEXT_ROUND, _CONTEXT::ContextFlags, _CONTEXT::EFlags, EFLAGS_IOPL_MASK, EFLAGS_V86_MASK, _CONTEXT::Esp, except, _EXCEPTION_RECORD::ExceptionAddress, KeContextFromKframes(), KeGetCurrentThread(), KeLowerIrql, KernelMode, KeUserApcDispatcher, KGDT_R3_CODE, KGDT_R3_DATA, KGDT_R3_TEB, KiCopyInformation(), KiDispatchException(), MODE_MASK, _KAPC_RECORD::NormalContext, _KAPC_RECORD::NormalRoutine, NULL, PASSIVE_LEVEL, ProbeForWrite(), ProbeForWriteSmallStructure(), RtlCopyMemory, SANITIZE_FLAGS, SANITIZE_SEG, _KAPC_RECORD::SystemArgument1, _KAPC_RECORD::SystemArgument2, TRUE, and UserMode.