Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/queuelock.c File Reference
queuelock.c File Reference
#include "ki.h"
Functions
VOID KeAcquireInStackQueuedSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
VOID KeAcquireInStackQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
VOID KeAcquireInStackQueuedSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
KIRQL KeAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number)
VOID KeAcquireQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
KIRQL KeAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number)
VOID KeReleaseInStackQueuedSpinLock (__in PKLOCK_QUEUE_HANDLE LockHandle)
VOID KeReleaseInStackQueuedSpinLockFromDpcLevel (__in PKLOCK_QUEUE_HANDLE LockHandle)
VOID KeReleaseQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __in KIRQL OldIrql)
VOID KeReleaseQueuedSpinLockFromDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
LOGICAL KeTryToAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
LOGICAL KeTryToAcquireQueuedSpinLockAtRaisedIrql (__inout PKSPIN_LOCK_QUEUE LockQueue)
LOGICAL KeTryToAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
VOID KiAcquireDispatcherLockAtSynchLevel (VOID)
KIRQL KiAcquireDispatcherLockRaiseToSynch (VOID)
VOID KiReleaseDispatcherLockFromSynchLevel (VOID)
LOGICAL KiTryToAcquireDispatcherLockRaiseToSynch (__out PKIRQL OldIrql)
__forceinline VOID KxAcquireQueuedSpinLock (__inout PKSPIN_LOCK_QUEUE LockQueue, __inout PKSPIN_LOCK SpinLock)
__forceinline VOID KxReleaseQueuedSpinLock (__inout PKSPIN_LOCK_QUEUE LockQueue)
__forceinline LOGICAL KxTryToAcquireQueuedSpinLock (__inout PKSPIN_LOCK_QUEUE LockQueue, __inout PKSPIN_LOCK SpinLock)
DECLSPEC_NOINLINE PKSPIN_LOCK_QUEUE KxWaitForLockChainValid (__inout PKSPIN_LOCK_QUEUE LockQueue)
DECLSPEC_NOINLINE ULONG64 KxWaitForLockOwnerShip (__inout PKSPIN_LOCK_QUEUE LockQueue, __inout PKSPIN_LOCK_QUEUE TailQueue)
Function Documentation
VOID KeAcquireInStackQueuedSpinLock (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 609 of file queuelock.c.
References DISPATCH_LEVEL, KfRaiseIrql(), KxAcquireQueuedSpinLock(), NULL, and UNREFERENCED_PARAMETER.
Referenced by CcAcquireBcbSpinLockAndVacbLock(), CcAcquireByteRangeForWrite(), CcDeleteMbcb(), CcGetDirtyPages(), CcGetFlushedValidData(), CcGetLsnForFileObject(), CcPinFileData(), CcPrepareMdlWrite(), CcRepinBcb(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcUnpinFileDataEx(), CcWriteBehind(), ExDeleteResourceLite(), ExInitializeResourceLite(), ExpCheckForResource(), ExQuerySystemLockInformation(), KeRemoveEntryDeviceQueue(), KiAcquireInStackQueuedSpinLockForDpc(), KiDeliverApc(), MiAddMdlTracker(), MiFreeMdlTracker(), MiUpdateMdlTracker(), and MmUpdateMdlTracker().
VOID KeAcquireInStackQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 705 of file queuelock.c.
References KxAcquireQueuedSpinLock(), NULL, and UNREFERENCED_PARAMETER.
Referenced by KeFreezeAllThreads(), KeStartThread(), KeTerminateThread(), KeThawAllThreads(), and KiAcquireInStackQueuedSpinLockForDpc().
VOID KeAcquireInStackQueuedSpinLockRaiseToSynch (__inout PKSPIN_LOCK SpinLock, __out PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 657 of file queuelock.c.
References KfRaiseIrql(), KxAcquireQueuedSpinLock(), NULL, SYNCH_LEVEL, and UNREFERENCED_PARAMETER.
Referenced by ExpGetProcessInformation(), KeAlertResumeThread(), KeAlertThread(), KeAttachProcess(), KeDetachProcess(), KeFlushQueueApc(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertQueueApc(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeRemoveQueueApc(), KeResumeThread(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeSetQuantumProcess(), KeStackAttachProcess(), KeStartThread(), KeSuspendThread(), KeTerminateThread(), KeTestAlertThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KeWaitForGate(), KiAttachProcess(), and MmSetExecuteOptions().
KIRQL KeAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number)
Definition at line 287 of file queuelock.c.
References DISPATCH_LEVEL, KfRaiseIrql(), KiGetLockQueue(), KxAcquireQueuedSpinLock(), and _KSPIN_LOCK_QUEUE::Lock.
Referenced by IoAcquireCancelSpinLock(), IoAcquireVpbSpinLock(), IoAllocateDriverObjectExtension(), IoDeleteDevice(), IoDetachDevice(), IoEnumerateDeviceObjectList(), IoGetAttachedDeviceReference(), IoGetDeviceAttachmentBaseRef(), IoGetDriverObjectExtension(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCheckUnloadDriver(), IopCheckVpbMounted(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), IopDereferenceVpbAndFree(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopGetDevicePDO(), IopGetDriverPathInformation(), IopGetMountFlag(), IopInsertRemoveDevice(), IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopInterlockedInsertHeadList(), IopInterlockedInsertTailList(), IopInterlockedRemoveHeadList(), IopResurrectDriver(), IopVerifyDeviceObjectOnStack(), IoUnregisterShutdownNotification(), MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiInitializePoolEvents(), and MmResourcesAvailable().
VOID KeAcquireQueuedSpinLockAtDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 371 of file queuelock.c.
References KxAcquireQueuedSpinLock().
Referenced by KiAcquireTimerTableLock(), and KiInitializeKernel().
KIRQL KeAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number)
Definition at line 329 of file queuelock.c.
References KfRaiseIrql(), KiGetLockQueue(), KxAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, and SYNCH_LEVEL.
VOID KeReleaseInStackQueuedSpinLock (__in PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 752 of file queuelock.c.
References KeLowerIrql, and KxReleaseQueuedSpinLock().
Referenced by CcAcquireByteRangeForWrite(), CcDeleteMbcb(), CcGetDirtyPages(), CcGetLsnForFileObject(), CcPinFileData(), CcPrepareMdlWrite(), CcReleaseBcbSpinLockAndVacbLock(), CcRepinBcb(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcUnpinFileDataEx(), CcWriteBehind(), ExDeleteResourceLite(), ExInitializeResourceLite(), ExpCheckForResource(), ExpGetProcessInformation(), ExQuerySystemLockInformation(), KeDetachProcess(), KeFlushQueueApc(), KeForceAttachProcess(), KeFreezeAllThreads(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeRemoveEntryDeviceQueue(), KeRemoveQueueApc(), KeSetQuantumProcess(), KeStartThread(), KeSuspendThread(), KeTestAlertThread(), KeUnstackDetachProcess(), KeWaitForGate(), KiDeliverApc(), KiReleaseInStackQueuedSpinLockForDpc(), MiAddMdlTracker(), MiFreeMdlTracker(), MiUpdateMdlTracker(), MmSetExecuteOptions(), and MmUpdateMdlTracker().
VOID KeReleaseInStackQueuedSpinLockFromDpcLevel (__in PKLOCK_QUEUE_HANDLE LockHandle)
Definition at line 785 of file queuelock.c.
References KxReleaseQueuedSpinLock().
Referenced by CcGetFlushedValidData(), KeAlertResumeThread(), KeAlertThread(), KeDetachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeInsertQueueApc(), KeResumeThread(), KeSetAffinityProcess(), KeSetPriorityAndQuantumProcess(), KeStartThread(), KeSuspendThread(), KeTerminateThread(), KeThawAllThreads(), KeUnstackDetachProcess(), KeWaitForGate(), KiAttachProcess(), and KiReleaseInStackQueuedSpinLockForDpc().
VOID KeReleaseQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __in KIRQL OldIrql)
Definition at line 540 of file queuelock.c.
References KeLowerIrql, KiGetLockQueue(), and KxReleaseQueuedSpinLock().
Referenced by IoAllocateDriverObjectExtension(), IoDeleteDevice(), IoDetachDevice(), IoEnumerateDeviceObjectList(), IoGetAttachedDeviceReference(), IoGetDeviceAttachmentBaseRef(), IoGetDriverObjectExtension(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCheckUnloadDriver(), IopCheckVpbMounted(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), IopDereferenceVpbAndFree(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopGetDevicePDO(), IopGetDriverPathInformation(), IopGetMountFlag(), IopInsertRemoveDevice(), IopInterlockedDecrementUlong(), IopInterlockedIncrementUlong(), IopInterlockedInsertHeadList(), IopInterlockedInsertTailList(), IopInterlockedRemoveHeadList(), IopResurrectDriver(), IopVerifyDeviceObjectOnStack(), IoReleaseCancelSpinLock(), IoReleaseVpbSpinLock(), IoUnregisterShutdownNotification(), MiAllocatePoolPages(), MiFindContiguousMemoryInPool(), MiFreeAllExpansionNonPagedPool(), MiFreePoolPages(), MiInitializePoolEvents(), and MmResourcesAvailable().
VOID KeReleaseQueuedSpinLockFromDpcLevel (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 578 of file queuelock.c.
References KxReleaseQueuedSpinLock().
Referenced by KiInitializeKernel(), and KiReleaseTimerTableLock().
LOGICAL KeTryToAcquireQueuedSpinLock (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
Definition at line 405 of file queuelock.c.
References DISPATCH_LEVEL, FALSE, KeLowerIrql, KfRaiseIrql(), KiGetLockQueue(), KxTryToAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, and TRUE.
LOGICAL KeTryToAcquireQueuedSpinLockAtRaisedIrql (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 506 of file queuelock.c.
References KxTryToAcquireQueuedSpinLock().
Referenced by KiInitializeKernel().
LOGICAL KeTryToAcquireQueuedSpinLockRaiseToSynch (__in KSPIN_LOCK_QUEUE_NUMBER Number, __out PKIRQL OldIrql)
Definition at line 455 of file queuelock.c.
References FALSE, KeLowerIrql, KfRaiseIrql(), KiGetLockQueue(), KxTryToAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, SYNCH_LEVEL, and TRUE.
VOID KiAcquireDispatcherLockAtSynchLevel (VOID)
Definition at line 856 of file queuelock.c.
References KiGetLockQueue(), KxAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, and LockQueueDispatcherLock.
KIRQL KiAcquireDispatcherLockRaiseToSynch (VOID)
Definition at line 816 of file queuelock.c.
References KfRaiseIrql(), KiGetLockQueue(), KxAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, LockQueueDispatcherLock, and SYNCH_LEVEL.
VOID KiReleaseDispatcherLockFromSynchLevel (VOID)
Definition at line 893 of file queuelock.c.
References KiGetLockQueue(), KxReleaseQueuedSpinLock(), and LockQueueDispatcherLock.
LOGICAL KiTryToAcquireDispatcherLockRaiseToSynch (__out PKIRQL OldIrql)
Definition at line 925 of file queuelock.c.
References FALSE, KeLowerIrql, KfRaiseIrql(), KiGetLockQueue(), KxTryToAcquireQueuedSpinLock(), _KSPIN_LOCK_QUEUE::Lock, LockQueueDispatcherLock, SYNCH_LEVEL, and TRUE.
__forceinline VOID KxAcquireQueuedSpinLock (__inout PKSPIN_LOCK_QUEUE LockQueue, __inout PKSPIN_LOCK SpinLock)
Definition at line 114 of file queuelock.c.
References InterlockedExchangePointer, KxWaitForLockOwnerShip(), NULL, and UNREFERENCED_PARAMETER.
Referenced by KeAcquireInStackQueuedSpinLock(), KeAcquireInStackQueuedSpinLockAtDpcLevel(), KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeAcquireQueuedSpinLock(), KeAcquireQueuedSpinLockAtDpcLevel(), KeAcquireQueuedSpinLockRaiseToSynch(), KiAcquireDispatcherLockAtSynchLevel(), and KiAcquireDispatcherLockRaiseToSynch().
__forceinline VOID KxReleaseQueuedSpinLock (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 227 of file queuelock.c.
References ASSERT, InterlockedCompareExchangePointer, KxWaitForLockChainValid(), _KSPIN_LOCK_QUEUE::Lock, LOCK_QUEUE_WAIT, NULL, ReadForWriteAccess, and UNREFERENCED_PARAMETER.
Referenced by KeReleaseInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), KeReleaseQueuedSpinLock(), KeReleaseQueuedSpinLockFromDpcLevel(), and KiReleaseDispatcherLockFromSynchLevel().
__forceinline LOGICAL KxTryToAcquireQueuedSpinLock (__inout PKSPIN_LOCK_QUEUE LockQueue, __inout PKSPIN_LOCK SpinLock)
Definition at line 168 of file queuelock.c.
References FALSE, InterlockedCompareExchangePointer, KeYieldProcessor, NULL, ReadForWriteAccess, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeTryToAcquireQueuedSpinLock(), KeTryToAcquireQueuedSpinLockAtRaisedIrql(), KeTryToAcquireQueuedSpinLockRaiseToSynch(), and KiTryToAcquireDispatcherLockRaiseToSynch().
DECLSPEC_NOINLINE PKSPIN_LOCK_QUEUE KxWaitForLockChainValid (__inout PKSPIN_LOCK_QUEUE LockQueue)
Definition at line 24 of file queuelock.c.
References KeYieldProcessor, _KSPIN_LOCK_QUEUE::Next, and NULL.
Referenced by KxReleaseQueuedSpinLock().
DECLSPEC_NOINLINE ULONG64 KxWaitForLockOwnerShip (__inout PKSPIN_LOCK_QUEUE LockQueue, __inout PKSPIN_LOCK_QUEUE TailQueue)
Definition at line 64 of file queuelock.c.
References KeMemoryBarrier(), KeYieldProcessor, and LOCK_QUEUE_WAIT.
Referenced by KxAcquireQueuedSpinLock().