Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hiveinit.c File Reference
hiveinit.c File Reference
#include "cmp.h"
Functions
NTSTATUS HvInitializeHive (PHHIVE Hive, ULONG OperationType, ULONG HiveFlags, ULONG FileType, PVOID HiveData OPTIONAL, PALLOCATE_ROUTINE AllocateRoutine, PFREE_ROUTINE FreeRoutine, PFILE_SET_SIZE_ROUTINE FileSetSizeRoutine, PFILE_WRITE_ROUTINE FileWriteRoutine, PFILE_READ_ROUTINE FileReadRoutine, PFILE_FLUSH_ROUTINE FileFlushRoutine, ULONG Cluster, PUNICODE_STRING FileName OPTIONAL)
VOID HvpFillFileName (PHBASE_BLOCK BaseBlock, PUNICODE_STRING FileName)
VOID HvpFreeAllocatedBins (PHHIVE Hive)
Function Documentation
NTSTATUS HvInitializeHive (PHHIVE Hive, ULONG OperationType, ULONG HiveFlags, ULONG FileType, PVOID HiveData OPTIONAL, PALLOCATE_ROUTINE AllocateRoutine, PFREE_ROUTINE FreeRoutine, PFILE_SET_SIZE_ROUTINE FileSetSizeRoutine, PFILE_WRITE_ROUTINE FileWriteRoutine, PFILE_READ_ROUTINE FileReadRoutine, PFILE_FLUSH_ROUTINE FileFlushRoutine, ULONG Cluster, PUNICODE_STRING FileName OPTIONAL)
Definition at line 115 of file hiveinit.c.
References _HHIVE::Allocate, ARGUMENT_PRESENT, _HHIVE::BaseBlock, _HHIVE::BaseBlockAlloc, _HBASE_BLOCK::BootRecover, _HBASE_BLOCK::BootType, _HBASE_BLOCK::CheckSum, _HBASE_BLOCK::Cluster, _HHIVE::Cluster, CmKdPrintEx, CML_BIN_MAP, CML_INIT, _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyFlag, _HHIVE::DirtyVector, _FREE_DISPLAY::Display, DPFLTR_CONFIG_ID, FALSE, _HHIVE::FileFlush, _HHIVE::FileRead, _HHIVE::FileSetSize, _HHIVE::FileWrite, _HHIVE::Flat, _HBASE_BLOCK::Format, _HHIVE::Free, _HHIVE::_DUAL::FreeBins, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, _HHIVE::GetCellRoutine, _HHIVE::_DUAL::Guard, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBLOCK_SIZE, HCELL_NIL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, HHIVE_FREE_DISPLAY_SIZE, HHIVE_SIGNATURE, _LARGE_INTEGER::HighPart, HINIT_CREATE, HINIT_FILE, HINIT_FLAT, HINIT_MAPFILE, HINIT_MEMORY, HINIT_MEMORY_INPLACE, HIVE_VOLATILE, _HHIVE::HiveFlags, HSECTOR_COUNT, HSECTOR_SIZE, HSYS_MAJOR, HSYS_MINOR, HSYS_MINOR_SUPPORTED, HTYPE_COUNT, HvLoadHive(), HvMapHive(), HvpAdjustHiveFreeDisplay(), HvpBuildMap(), HvpBuildMapAndCopy(), HvpDoWriteHive(), HvpFillFileName(), HvpFreeAllocatedBins(), HvpGetCellFlat(), HvpGetCellMapped(), HvpGetCellPaged(), HvpHeaderCheckSum(), HvpReleaseCellMapped(), InitializeListHead(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::Log, _HHIVE::LogSize, _LARGE_INTEGER::LowPart, _HBASE_BLOCK::Major, _HHIVE::_DUAL::Map, _HBASE_BLOCK::Minor, NT_SUCCESS, NULL, PAGE_SIZE, _HHIVE::ReadOnly, _FREE_DISPLAY::RealVectorSize, _HHIVE::RefreshCount, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, RtlClearAllBits(), RtlCopyMemory, RtlInitializeBitMap(), _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBASE_BLOCK::Signature, _HHIVE::Signature, _HHIVE::_DUAL::SmallDir, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_IO_FAILED, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, _HHIVE::Storage, _HHIVE::StorageTypeCount, _HBASE_BLOCK::TimeStamp, TRUE, _HBASE_BLOCK::Type, _HHIVE::Version, and Volatile.
Referenced by CmGetSystemControlValues(), and CmpInitializeHive().
VOID HvpFillFileName (PHBASE_BLOCK BaseBlock, PUNICODE_STRING FileName)
Definition at line 618 of file hiveinit.c.
References _UNICODE_STRING::Buffer, CmKdPrintEx, CML_HIVE, DPFLTR_CONFIG_ID, _HBASE_BLOCK::FileName, HBASE_NAME_ALLOC, _UNICODE_STRING::Length, NULL, RtlCopyMemory, and RtlZeroMemory.
Referenced by HvInitializeHive().
VOID HvpFreeAllocatedBins (PHHIVE Hive)
Definition at line 39 of file hiveinit.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_DIRECTORY::Directory, _HHIVE::Free, HBIN_BASE, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HTABLE_SLOTS, HvpGetBinMemAlloc(), _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, Stable, _HHIVE::Storage, and _HMAP_TABLE::Table.
Referenced by HvInitializeHive(), HvLoadHive(), HvMapHive(), and HvpRecoverWholeHive().