Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/uuid.c File Reference
uuid.c File Reference
#include "exp.h"
Data Structures
struct _UUID_CACHED_VALUES_STRUCT
struct _UUID_GENERATE
Macros
#define CACHE_LOCAL_ONLY 0
#define CACHE_VALID 1
#define RPC_SEQUENCE_NUMBER_NAME L"UuidSequenceNumber"
#define RPC_SEQUENCE_NUMBER_PATH L"\\Registry\\Machine\\Software\\Microsoft\\Rpc"
#define SEED_SIZE 6 * sizeof(CHAR)
#define UUID_CLOCK_SEQ_HI_MASK 0x3F
#define UUID_RESERVED 0x80
#define UUID_TIME_HIGH_MASK 0x0FFF
#define UUID_VERSION 0x1000
Typedefs
typedef struct _UUID_CACHED_VALUES_STRUCT UUID_CACHED_VALUES_STRUCT
typedef struct _UUID_GENERATE UUID_GENERATE
Functions
NTSTATUS ExpAllocateUuids (OUT PLARGE_INTEGER Time, OUT PULONG Range, OUT PULONG Sequence)
NTSTATUS ExpUuidGetValues (OUT UUID_CACHED_VALUES_STRUCT *Values)
BOOLEAN ExpUuidInitialization (VOID)
NTSTATUS ExpUuidLoadSequenceNumber (OUT PULONG)
NTSTATUS ExpUuidSaveSequenceNumber (IN ULONG)
NTSTATUS ExpUuidSaveSequenceNumberIf (VOID)
NTSTATUS ExUuidCreate (__out UUID *Uuid)
NTSTATUS NtAllocateUuids (__out PULARGE_INTEGER Time, __out PULONG Range, __out PULONG Sequence, __out PCHAR Seed)
NTSTATUS NtSetUuidSeed (__in PCHAR Seed)
Variables
UUID_CACHED_VALUES_STRUCT ExpUuidCachedValues = { 0, -1, 0, 0, { 0x80, 'n', 'o', 'n', 'i', 'c' }}
BOOLEAN ExpUuidCacheValid = CACHE_LOCAL_ONLY
LARGE_INTEGER ExpUuidLastTimeAllocated = {0,0}
FAST_MUTEX ExpUuidLock
ULONG ExpUuidSequenceNumber = 0
BOOLEAN ExpUuidSequenceNumberNotSaved = FALSE
BOOLEAN ExpUuidSequenceNumberValid = FALSE
Macro Definition Documentation
#define CACHE_LOCAL_ONLY 0
Definition at line 49 of file uuid.c.
Referenced by ExUuidCreate(), and NtSetUuidSeed().
#define CACHE_VALID 1
Definition at line 50 of file uuid.c.
Referenced by NtSetUuidSeed().
#define RPC_SEQUENCE_NUMBER_NAME L"UuidSequenceNumber"
Definition at line 40 of file uuid.c.
Referenced by ExpUuidLoadSequenceNumber(), and ExpUuidSaveSequenceNumber().
#define RPC_SEQUENCE_NUMBER_PATH L"\\Registry\\Machine\\Software\\Microsoft\\Rpc"
Definition at line 39 of file uuid.c.
Referenced by ExpUuidLoadSequenceNumber(), and ExpUuidSaveSequenceNumber().
#define SEED_SIZE 6 * sizeof(CHAR)
Definition at line 538 of file uuid.c.
Referenced by NtAllocateUuids(), and NtSetUuidSeed().
#define UUID_CLOCK_SEQ_HI_MASK 0x3F
Definition at line 46 of file uuid.c.
Referenced by ExpUuidGetValues().
#define UUID_RESERVED 0x80
Definition at line 45 of file uuid.c.
Referenced by ExpUuidGetValues().
#define UUID_TIME_HIGH_MASK 0x0FFF
Definition at line 43 of file uuid.c.
Referenced by ExUuidCreate().
#define UUID_VERSION 0x1000
Definition at line 44 of file uuid.c.
Referenced by ExUuidCreate().
Typedef Documentation
typedef struct _UUID_CACHED_VALUES_STRUCT UUID_CACHED_VALUES_STRUCT
typedef struct _UUID_GENERATE UUID_GENERATE
Function Documentation
NTSTATUS ExpAllocateUuids (OUT PLARGE_INTEGER Time, OUT PULONG Range, OUT PULONG Sequence)
Definition at line 387 of file uuid.c.
References DPFLTR_SYSTEM_ID, DPFLTR_WARNING_LEVEL, ExpUuidLoadSequenceNumber(), ExpUuidSequenceNumber, ExpUuidSequenceNumberNotSaved, ExpUuidSequenceNumberValid, FALSE, _LARGE_INTEGER::HighPart, KdPrintEx, KeQueryPerformanceCounter(), KeQuerySystemTime(), _LARGE_INTEGER::LowPart, NT_SUCCESS, PAGED_CODE, _LARGE_INTEGER::QuadPart, Status, STATUS_RETRY, STATUS_SUCCESS, and TRUE.
Referenced by ExpUuidGetValues(), and NtAllocateUuids().
NTSTATUS ExpUuidGetValues (OUT UUID_CACHED_VALUES_STRUCT * Values)
Definition at line 758 of file uuid.c.
References ASSERT, ExpAllocateUuids(), NT_SUCCESS, PAGED_CODE, _LARGE_INTEGER::QuadPart, Status, STATUS_NO_MEMORY, STATUS_RETRY, STATUS_SUCCESS, UUID_CLOCK_SEQ_HI_MASK, and UUID_RESERVED.
Referenced by ExUuidCreate().
BOOLEAN ExpUuidInitialization (VOID)
Definition at line 351 of file uuid.c.
References ExInitializeFastMutex, ExpUuidSequenceNumberValid, FALSE, KeQuerySystemTime(), PAGED_CODE, and TRUE.
NTSTATUS ExpUuidLoadSequenceNumber (OUT PULONG Sequence)
Definition at line 145 of file uuid.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, GENERIC_READ, InitializeObjectAttributes, KeyName, KeyValuePartialInformation, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_DWORD, RPC_SEQUENCE_NUMBER_NAME, RPC_SEQUENCE_NUMBER_PATH, RtlInitUnicodeString(), Status, STATUS_UNSUCCESSFUL, _KEY_VALUE_PARTIAL_INFORMATION::Type, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by ExpAllocateUuids().
NTSTATUS ExpUuidSaveSequenceNumber (IN ULONG Sequence)
Definition at line 230 of file uuid.c.
References GENERIC_READ, GENERIC_WRITE, InitializeObjectAttributes, KeyName, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_DWORD, RPC_SEQUENCE_NUMBER_NAME, RPC_SEQUENCE_NUMBER_PATH, RtlInitUnicodeString(), Status, ZwClose(), ZwOpenKey(), and ZwSetValueKey().
Referenced by ExpUuidSaveSequenceNumberIf().
NTSTATUS ExpUuidSaveSequenceNumberIf (VOID)
Definition at line 298 of file uuid.c.
References DPFLTR_SYSTEM_ID, DPFLTR_WARNING_LEVEL, ExpUuidSaveSequenceNumber(), ExpUuidSequenceNumber, ExpUuidSequenceNumberNotSaved, FALSE, KdPrintEx, NT_SUCCESS, PAGED_CODE, Status, STATUS_SUCCESS, and TRUE.
Referenced by ExUuidCreate(), and NtAllocateUuids().
NTSTATUS ExUuidCreate (__out UUID * Uuid)
Definition at line 849 of file uuid.c.
References _UUID_CACHED_VALUES_STRUCT::AllocatedCount, ASSERT, CACHE_LOCAL_ONLY, _UUID_GENERATE::ClockSeqHiAndReserved, _UUID_CACHED_VALUES_STRUCT::ClockSeqHiAndReserved, ExAcquireFastMutexUnsafe(), ExpUuidCacheValid, ExpUuidGetValues(), ExpUuidSaveSequenceNumberIf(), ExReleaseFastMutexUnsafe(), InterlockedDecrement, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), _UUID_GENERATE::NodeId, _UUID_CACHED_VALUES_STRUCT::NodeId, PAGED_CODE, RPC_NT_UUID_LOCAL_ONLY, Status, STATUS_SUCCESS, _UUID_CACHED_VALUES_STRUCT::Time, _UUID_GENERATE::TimeHiAndVersion, _UUID_GENERATE::TimeLow, _UUID_GENERATE::TimeMid, UUID_TIME_HIGH_MASK, and UUID_VERSION.
Referenced by WmipStartLogger().
NTSTATUS NtAllocateUuids (__out PULARGE_INTEGER Time, __out PULONG Range, __out PULONG Sequence, __out PCHAR Seed)
Definition at line 628 of file uuid.c.
References ExAcquireFastMutexUnsafe(), except, ExpAllocateUuids(), ExpUuidSaveSequenceNumberIf(), ExReleaseFastMutexUnsafe(), ExSystemExceptionFilter(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KernelMode, _UUID_CACHED_VALUES_STRUCT::NodeId, NT_SUCCESS, PAGED_CODE, ProbeForWriteSmallStructure(), ProbeForWriteUlongAligned32(), _LARGE_INTEGER::QuadPart, RtlCopyMemory, SEED_SIZE, Status, and STATUS_SUCCESS.
NTSTATUS NtSetUuidSeed (__in PCHAR Seed)
Definition at line 541 of file uuid.c.
References ASSERT, CACHE_LOCAL_ONLY, CACHE_VALID, except, EXCEPTION_EXECUTE_HANDLER, ExpUuidCacheValid, ExRaiseStatus(), FALSE, KeGetPreviousMode, KernelMode, _UUID_CACHED_VALUES_STRUCT::NodeId, NT_SUCCESS, PAGED_CODE, ProbeForReadSmallStructure, RtlCompareMemory(), RtlCopyMemory, SeCaptureSubjectContext(), SEED_SIZE, SeQueryAuthenticationIdToken(), SeQuerySubjectContextToken, SeReleaseSubjectContext(), Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SYSTEM_LUID, and TRUE.
Variable Documentation
UUID_CACHED_VALUES_STRUCT ExpUuidCachedValues = { 0, -1, 0, 0, { 0x80, 'n', 'o', 'n', 'i', 'c' }}
Definition at line 89 of file uuid.c.
BOOLEAN ExpUuidCacheValid = CACHE_LOCAL_ONLY
Definition at line 85 of file uuid.c.
Referenced by ExUuidCreate(), and NtSetUuidSeed().
LARGE_INTEGER ExpUuidLastTimeAllocated = {0,0}
Definition at line 84 of file uuid.c.
FAST_MUTEX ExpUuidLock
Definition at line 101 of file uuid.c.
ULONG ExpUuidSequenceNumber = 0
Definition at line 92 of file uuid.c.
Referenced by ExpAllocateUuids(), and ExpUuidSaveSequenceNumberIf().
BOOLEAN ExpUuidSequenceNumberNotSaved = FALSE
Definition at line 94 of file uuid.c.
Referenced by ExpAllocateUuids(), and ExpUuidSaveSequenceNumberIf().
BOOLEAN ExpUuidSequenceNumberValid = FALSE
Definition at line 93 of file uuid.c.
Referenced by ExpAllocateUuids(), and ExpUuidInitialization().