Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/flushtb.c File Reference
flushtb.c File Reference
#include "ki.h"
Functions
VOID KeFlushMultipleTb (IN ULONG Number, IN PVOID *Virtual, IN BOOLEAN AllProcessors)
VOID KeFlushProcessTb (VOID)
VOID FASTCALL KeFlushSingleTb (IN PVOID Virtual, IN BOOLEAN AllProcessors)
VOID KiFlushTargetEntireTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
VOID KiFlushTargetMultipleTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
VOID KiFlushTargetProcessTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
VOID KiFlushTargetSingleTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
VOID KxFlushEntireTb (VOID)
Function Documentation
VOID KeFlushMultipleTb (IN ULONG Number, IN PVOID * Virtual, IN BOOLEAN AllProcessors)
Definition at line 311 of file flushtb.c.
References _KPROCESS::ActiveProcessors, _KTHREAD::ApcState, ASSERT, _KPRCB::CurrentThread, FALSE, IPI_INSTRUMENT_COUNT, KeActiveProcessors, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiFlushSingleTb(), KiFlushTargetMultipleTb(), KiIpiSendPacket(), KiIpiStallOnPacketTargets(), NULL, _KPRCB::Number, _KAPC_STATE::Process, and _KPRCB::SetMember.
VOID KeFlushProcessTb (VOID)
Definition at line 192 of file flushtb.c.
References _KPROCESS::ActiveProcessors, _KTHREAD::ApcState, _KPRCB::CurrentThread, IPI_INSTRUMENT_COUNT, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiFlushProcessTb(), KiFlushTargetProcessTb(), KiIpiSendPacket(), KiIpiStallOnPacketTargets(), NULL, _KPRCB::Number, _KAPC_STATE::Process, and _KPRCB::SetMember.
VOID FASTCALL KeFlushSingleTb (IN PVOID Virtual, IN BOOLEAN AllProcessors)
Definition at line 471 of file flushtb.c.
References _KPROCESS::ActiveProcessors, _KTHREAD::ApcState, _KPRCB::CurrentThread, FALSE, IPI_INSTRUMENT_COUNT, KeActiveProcessors, KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiFlushSingleTb(), KiFlushTargetSingleTb(), KiIpiSendPacket(), KiIpiStallOnPacketTargets(), NULL, _KPRCB::Number, _KAPC_STATE::Process, and _KPRCB::SetMember.
VOID KiFlushTargetEntireTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 150 of file flushtb.c.
References KeFlushCurrentTb(), KiIpiSignalPacketDone(), and UNREFERENCED_PARAMETER.
Referenced by KxFlushEntireTb().
VOID KiFlushTargetMultipleTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 413 of file flushtb.c.
References KiFlushSingleTb(), KiIpiSignalPacketDone(), and UNREFERENCED_PARAMETER.
Referenced by KeFlushMultipleTb().
VOID KiFlushTargetProcessTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 269 of file flushtb.c.
References KiFlushProcessTb(), KiIpiSignalPacketDone(), and UNREFERENCED_PARAMETER.
Referenced by KeFlushProcessTb().
VOID KiFlushTargetSingleTb (IN PKIPI_CONTEXT SignalDone, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 561 of file flushtb.c.
References KiFlushSingleTb(), KiIpiSignalPacketDone(), and UNREFERENCED_PARAMETER.
Referenced by KeFlushSingleTb().
VOID KxFlushEntireTb (VOID)
Definition at line 55 of file flushtb.c.
References IPI_INSTRUMENT_COUNT, KeActiveProcessors, KeFlushCurrentTb(), KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), KiClearTbFlushTimeStampBusy(), KiFlushTargetEntireTb(), KiIpiSendPacket(), KiIpiStallOnPacketTargets(), KiSetTbFlushTimeStampBusy(), NULL, _KPRCB::Number, and _KPRCB::SetMember.
Referenced by KeFlushEntireTb().