Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/time.c File Reference
time.c File Reference
#include "ntrtlp.h"
Macros
#define Convert100nsToMilliseconds(LARGE_INTEGER)
#define Convert100nsToSeconds(LARGE_INTEGER)
#define ConvertDaysToMilliseconds(DAYS)
#define ConvertMillisecondsTo100ns(MILLISECONDS)
#define ConvertMillisecondsToDays(LARGE_INTEGER)
#define ConvertSecondsTo100ns(SECONDS)
#define ElapsedYearsToDays(YEARS)
#define IsLeapYear(YEARS)
#define MaxDaysInMonth(YEAR, MONTH)
#define NumberOfLeapYears(YEARS)
#define SHIFT10000 13
#define SHIFT10000000 23
#define SHIFT86400000 26
#define WEEKDAY_OF_1601 1
Functions
VOID DaysAndFractionToTime (IN ULONG ElapsedDays, IN ULONG Milliseconds, OUT PLARGE_INTEGER Time)
ULONG ElapsedDaysToYears (IN ULONG ElapsedDays)
BOOLEAN RtlCutoverTimeToSystemTime (PTIME_FIELDS CutoverTime, PLARGE_INTEGER SystemTime, PLARGE_INTEGER CurrentSystemTime, BOOLEAN ThisYear)
ULONG RtlGetTickCount (VOID)
NTSTATUS RtlLocalTimeToSystemTime (IN PLARGE_INTEGER LocalTime, OUT PLARGE_INTEGER SystemTime)
VOID RtlSecondsSince1970ToTime (IN ULONG ElapsedSeconds, OUT PLARGE_INTEGER Time)
VOID RtlSecondsSince1980ToTime (IN ULONG ElapsedSeconds, OUT PLARGE_INTEGER Time)
NTSTATUS RtlSystemTimeToLocalTime (IN PLARGE_INTEGER SystemTime, OUT PLARGE_INTEGER LocalTime)
BOOLEAN RtlTimeFieldsToTime (IN PTIME_FIELDS TimeFields, OUT PLARGE_INTEGER Time)
VOID RtlTimeToElapsedTimeFields (IN PLARGE_INTEGER Time, OUT PTIME_FIELDS TimeFields)
BOOLEAN RtlTimeToSecondsSince1970 (IN PLARGE_INTEGER Time, OUT PULONG ElapsedSeconds)
BOOLEAN RtlTimeToSecondsSince1980 (IN PLARGE_INTEGER Time, OUT PULONG ElapsedSeconds)
VOID RtlTimeToTimeFields (IN PLARGE_INTEGER Time, OUT PTIME_FIELDS TimeFields)
static VOID TimeToDaysAndFraction (IN PLARGE_INTEGER Time, OUT PULONG ElapsedDays, OUT PULONG Milliseconds)
Variables
CONST CSHORT LeapYearDaysPrecedingMonth [13]
CONST UCHAR LeapYearDayToMonth [366]
const LARGE_INTEGER Magic10000 = {0xe219652c, 0xd1b71758}
const LARGE_INTEGER Magic10000000 = {0xe57a42bd, 0xd6bf94d5}
const LARGE_INTEGER Magic86400000 = {0xfa67b90e, 0xc6d750eb}
CONST CSHORT NormalYearDaysPrecedingMonth [13]
CONST UCHAR NormalYearDayToMonth [365]
const LARGE_INTEGER SecondsToStartOf1970 = {0xb6109100, 0x00000002}
const LARGE_INTEGER SecondsToStartOf1980 = {0xc8df3700, 0x00000002}
Macro Definition Documentation
#define Convert100nsToMilliseconds (LARGE_INTEGER)
Value:
(\
    RtlExtendedMagicDivide( (LARGE_INTEGER), Magic10000, SHIFT10000 )       \
    )
Definition at line 199 of file time.c.
Referenced by TimeToDaysAndFraction().
#define Convert100nsToSeconds (LARGE_INTEGER)
Value:
(\
    RtlExtendedMagicDivide( (LARGE_INTEGER), Magic10000000, SHIFT10000000 ) \
    )
Definition at line 207 of file time.c.
Referenced by RtlTimeToSecondsSince1970(), and RtlTimeToSecondsSince1980().
#define ConvertDaysToMilliseconds (DAYS)
Value:
(\
    Int32x32To64( (DAYS), 86400000 )                               \
    )
Definition at line 219 of file time.c.
Referenced by DaysAndFractionToTime(), and TimeToDaysAndFraction().
#define ConvertMillisecondsTo100ns (MILLISECONDS)
Value:
(\
    RtlExtendedIntegerMultiply( (MILLISECONDS), 10000 )            \
    )
Definition at line 203 of file time.c.
Referenced by DaysAndFractionToTime().
#define ConvertMillisecondsToDays (LARGE_INTEGER)
Value:
(\
    RtlExtendedMagicDivide( (LARGE_INTEGER), Magic86400000, SHIFT86400000 ) \
    )
Definition at line 215 of file time.c.
Referenced by TimeToDaysAndFraction().
#define ConvertSecondsTo100ns (SECONDS)
Value:
(\
    RtlExtendedIntegerMultiply( (SECONDS), 10000000 )              \
    )
Definition at line 211 of file time.c.
Referenced by RtlSecondsSince1970ToTime(), and RtlSecondsSince1980ToTime().
#define ElapsedYearsToDays (YEARS)
Value:
(\
    ((YEARS) * 365) + NumberOfLeapYears(YEARS) \
    )
Definition at line 331 of file time.c.
Referenced by RtlTimeFieldsToTime(), and RtlTimeToTimeFields().
#define IsLeapYear (YEARS)
Value:
(\
    (((YEARS) % 400 == 0) ||                       \
     ((YEARS) % 100 != 0) && ((YEARS) % 4 == 0)) ? \
        TRUE                                       \
    :                                              \
        FALSE                                      \
    )
Definition at line 345 of file time.c.
Referenced by RtlTimeFieldsToTime(), and RtlTimeToTimeFields().
#define MaxDaysInMonth (YEAR, MONTH)
Value:
(\
    IsLeapYear(YEAR) ?                                                    \
        LeapYearDaysPrecedingMonth[(MONTH) + 1] -                         \
                                    LeapYearDaysPrecedingMonth[(MONTH)]   \
    :                                                                     \
        NormalYearDaysPrecedingMonth[(MONTH) + 1] -                       \
                                    NormalYearDaysPrecedingMonth[(MONTH)] \
    )
Definition at line 365 of file time.c.
Referenced by RtlTimeFieldsToTime().
#define NumberOfLeapYears (YEARS)
Value:
(\
    ((YEARS) / 4) - ((YEARS) / 100) + ((YEARS) / 400) \
    )
Definition at line 316 of file time.c.
#define SHIFT10000 13
Definition at line 186 of file time.c.
#define SHIFT10000000 23
Definition at line 189 of file time.c.
#define SHIFT86400000 26
Definition at line 192 of file time.c.
#define WEEKDAY_OF_1601 1
Definition at line 159 of file time.c.
Referenced by RtlTimeToTimeFields().
Function Documentation
VOID DaysAndFractionToTime (IN ULONG ElapsedDays, IN ULONG Milliseconds, OUT PLARGE_INTEGER Time)
Definition at line 464 of file time.c.
References ConvertDaysToMilliseconds, ConvertMillisecondsTo100ns, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, and _LARGE_INTEGER::QuadPart.
Referenced by RtlTimeFieldsToTime().
ULONG ElapsedDaysToYears (IN ULONG ElapsedDays)
Definition at line 229 of file time.c.
Referenced by RtlTimeToTimeFields().
BOOLEAN RtlCutoverTimeToSystemTime (PTIME_FIELDS CutoverTime, PLARGE_INTEGER SystemTime, PLARGE_INTEGER CurrentSystemTime, BOOLEAN ThisYear)
Definition at line 676 of file time.c.
References _TIME_FIELDS::Day, FALSE, _TIME_FIELDS::Hour, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, _LARGE_INTEGER::QuadPart, RtlTimeFieldsToTime(), RtlTimeToTimeFields(), _TIME_FIELDS::Second, TRUE, _TIME_FIELDS::Weekday, and _TIME_FIELDS::Year.
ULONG RtlGetTickCount (VOID)
Definition at line 1373 of file time.c.
NTSTATUS RtlLocalTimeToSystemTime (IN PLARGE_INTEGER LocalTime, OUT PLARGE_INTEGER SystemTime)
Definition at line 1343 of file time.c.
References NT_SUCCESS, NULL, _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, SystemTimeOfDayInformation, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneBias, and ZwQuerySystemInformation().
VOID RtlSecondsSince1970ToTime (IN ULONG ElapsedSeconds, OUT PLARGE_INTEGER Time)
Definition at line 1260 of file time.c.
References ConvertSecondsTo100ns, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, and _LARGE_INTEGER::QuadPart.
VOID RtlSecondsSince1980ToTime (IN ULONG ElapsedSeconds, OUT PLARGE_INTEGER Time)
Definition at line 1135 of file time.c.
References ConvertSecondsTo100ns, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, and _LARGE_INTEGER::QuadPart.
NTSTATUS RtlSystemTimeToLocalTime (IN PLARGE_INTEGER SystemTime, OUT PLARGE_INTEGER LocalTime)
Definition at line 1315 of file time.c.
References NT_SUCCESS, NULL, _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, SystemTimeOfDayInformation, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneBias, and ZwQuerySystemInformation().
BOOLEAN RtlTimeFieldsToTime (IN PTIME_FIELDS TimeFields, OUT PLARGE_INTEGER Time)
Definition at line 843 of file time.c.
References DaysAndFractionToTime(), ElapsedYearsToDays, FALSE, IsLeapYear, LeapYearDaysPrecedingMonth, MaxDaysInMonth, NormalYearDaysPrecedingMonth, and TRUE.
Referenced by RtlCutoverTimeToSystemTime().
VOID RtlTimeToElapsedTimeFields (IN PLARGE_INTEGER Time, OUT PTIME_FIELDS TimeFields)
Definition at line 974 of file time.c.
References TimeToDaysAndFraction().
BOOLEAN RtlTimeToSecondsSince1970 (IN PLARGE_INTEGER Time, OUT PULONG ElapsedSeconds)
Definition at line 1191 of file time.c.
References Convert100nsToSeconds, FALSE, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, _LARGE_INTEGER::QuadPart, and TRUE.
BOOLEAN RtlTimeToSecondsSince1980 (IN PLARGE_INTEGER Time, OUT PULONG ElapsedSeconds)
Definition at line 1066 of file time.c.
References Convert100nsToSeconds, FALSE, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, _LARGE_INTEGER::QuadPart, and TRUE.
VOID RtlTimeToTimeFields (IN PLARGE_INTEGER Time, OUT PTIME_FIELDS TimeFields)
Definition at line 529 of file time.c.
References ElapsedDaysToYears(), ElapsedYearsToDays, IsLeapYear, LeapYearDaysPrecedingMonth, LeapYearDayToMonth, NormalYearDaysPrecedingMonth, NormalYearDayToMonth, TimeToDaysAndFraction(), and WEEKDAY_OF_1601.
Referenced by RtlCutoverTimeToSystemTime().
static VOID TimeToDaysAndFraction (IN PLARGE_INTEGER Time, OUT PULONG ElapsedDays, OUT PULONG Milliseconds) static
Definition at line 382 of file time.c.
References Convert100nsToMilliseconds, ConvertDaysToMilliseconds, ConvertMillisecondsToDays, _LARGE_INTEGER::LowPart, and _LARGE_INTEGER::QuadPart.
Referenced by RtlTimeToElapsedTimeFields(), and RtlTimeToTimeFields().
Variable Documentation
CONST CSHORT LeapYearDaysPrecedingMonth[13]
Initial value:
= {
    0,
    31,
    31+29,
    31+29+31,
    31+29+31+30,
    31+29+31+30+31,
    31+29+31+30+31+30,
    31+29+31+30+31+30+31,
    31+29+31+30+31+30+31+31,
    31+29+31+30+31+30+31+31+30,
    31+29+31+30+31+30+31+31+30+31,
    31+29+31+30+31+30+31+31+30+31+30,
    31+29+31+30+31+30+31+31+30+31+30+31}
Definition at line 119 of file time.c.
Referenced by RtlTimeFieldsToTime(), and RtlTimeToTimeFields().
CONST UCHAR LeapYearDayToMonth[366]
Initial value:
= {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
     3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
     4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
     6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
     7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
     8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,
    11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11}
Definition at line 83 of file time.c.
Referenced by RtlTimeToTimeFields().
const LARGE_INTEGER Magic10000 = {0xe219652c, 0xd1b71758}
Definition at line 185 of file time.c.
const LARGE_INTEGER Magic10000000 = {0xe57a42bd, 0xd6bf94d5}
Definition at line 188 of file time.c.
const LARGE_INTEGER Magic86400000 = {0xfa67b90e, 0xc6d750eb}
Definition at line 191 of file time.c.
CONST CSHORT NormalYearDaysPrecedingMonth[13]
Initial value:
= {
    0,
    31,
    31+28,
    31+28+31,
    31+28+31+30,
    31+28+31+30+31,
    31+28+31+30+31+30,
    31+28+31+30+31+30+31,
    31+28+31+30+31+30+31+31,
    31+28+31+30+31+30+31+31+30,
    31+28+31+30+31+30+31+31+30+31,
    31+28+31+30+31+30+31+31+30+31+30,
    31+28+31+30+31+30+31+31+30+31+30+31}
Definition at line 134 of file time.c.
Referenced by RtlTimeFieldsToTime(), and RtlTimeToTimeFields().
CONST UCHAR NormalYearDayToMonth[365]
Initial value:
= {
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
     3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
     4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
     6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
     7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
     8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
     9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,
    11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11}
Definition at line 97 of file time.c.
Referenced by RtlTimeToTimeFields().
const LARGE_INTEGER SecondsToStartOf1970 = {0xb6109100, 0x00000002}
Definition at line 170 of file time.c.
const LARGE_INTEGER SecondsToStartOf1980 = {0xc8df3700, 0x00000002}
Definition at line 172 of file time.c.