Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/environ.c File Reference
environ.c File Reference
#include "ntrtlp.h"
#include "zwapi.h"
#include "nturtl.h"
#include "string.h"
#include "ntrtlpath.h"
#include "wow64t.h"
Functions
NTSTATUS RtlCreateEnvironment (IN BOOLEAN CloneCurrentEnvironment OPTIONAL, OUT PVOID *Environment)
NTSTATUS RtlDestroyEnvironment (IN PVOID Environment)
NTSTATUS RtlQueryEnvironmentVariable_U (IN PVOID Environment OPTIONAL, IN PCUNICODE_STRING Name, IN OUT PUNICODE_STRING Value)
NTSTATUS RtlSetCurrentEnvironment (IN PVOID Environment, OUT PVOID *PreviousEnvironment OPTIONAL)
NTSTATUS NTAPI RtlSetEnvironmentStrings (IN PWCHAR NewEnvironment, IN SIZE_T NewEnvironmentSize)
NTSTATUS RtlSetEnvironmentVariable (IN OUT PVOID *Environment OPTIONAL, IN PCUNICODE_STRING Name, IN PCUNICODE_STRING Value OPTIONAL)
Variables
UNICODE_STRING RtlpEnvironCacheName
BOOLEAN RtlpEnvironCacheValid
UNICODE_STRING RtlpEnvironCacheValue
Function Documentation
NTSTATUS RtlCreateEnvironment (IN BOOLEAN CloneCurrentEnvironment OPTIONAL, OUT PVOID * Environment)
Definition at line 38 of file environ.c.
References _RTL_USER_PROCESS_PARAMETERS::Environment, except, EXCEPTION_EXECUTE_HANDLER, leave, MEM_COMMIT, MEM_RELEASE, MemoryBasicInformation, NT_SUCCESS, NtCurrentPeb, NtCurrentProcess, NULL, PAGE_READWRITE, _MEMORY_BASIC_INFORMATION::RegionSize, RtlAcquirePebLock(), RtlCopyMemory, RtlReleasePebLock(), Status, STATUS_ACCESS_VIOLATION, ZwAllocateVirtualMemory(), ZwFreeVirtualMemory(), and ZwQueryVirtualMemory().
NTSTATUS RtlDestroyEnvironment (IN PVOID Environment)
Definition at line 156 of file environ.c.
References FALSE, MEM_RELEASE, NtCurrentProcess, RtlpEnvironCacheValid, Status, and ZwFreeVirtualMemory().
Referenced by RtlSetCurrentEnvironment().
NTSTATUS RtlQueryEnvironmentVariable_U (IN PVOID Environment OPTIONAL, IN PCUNICODE_STRING Name, IN OUT PUNICODE_STRING Value)
Definition at line 260 of file environ.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _RTL_USER_PROCESS_PARAMETERS::CurrentDirectory, _CURDIR::DosPath, _RTL_USER_PROCESS_PARAMETERS::Environment, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _RTL_USER_PROCESS_PARAMETERS::ImagePathName, leave, _UNICODE_STRING::Length, NT_SUCCESS, NtCurrentPeb, NULL, RTL_CONSTANT_STRING, RTL_FIND_CHAR_IN_UNICODE_STRING_START_AT_END, RtlAcquirePebLock(), RtlCopyMemory, RtlDosPathSeparatorsString, RtlEqualUnicodeString(), RtlFindCharInUnicodeString(), RtlpEnvironCacheValid, RtlReleasePebLock(), Status, STATUS_ACCESS_VIOLATION, STATUS_BUFFER_TOO_SMALL, STATUS_NOT_FOUND, STATUS_SUCCESS, STATUS_VARIABLE_NOT_FOUND, TRUE, UNICODE_NULL, wcschr(), and wcslen().
NTSTATUS RtlSetCurrentEnvironment (IN PVOID Environment, OUT PVOID *PreviousEnvironment OPTIONAL)
Definition at line 184 of file environ.c.
References ARGUMENT_PRESENT, _RTL_USER_PROCESS_PARAMETERS::Environment, FALSE, NtCurrentPeb, NULL, RtlAcquirePebLock(), RtlDestroyEnvironment(), RtlpEnvironCacheValid, RtlReleasePebLock(), Status, and STATUS_SUCCESS.
NTSTATUS NTAPI RtlSetEnvironmentStrings (IN PWCHAR NewEnvironment, IN SIZE_T NewEnvironmentSize)
Definition at line 944 of file environ.c.
References ASSERT, _RTL_USER_PROCESS_PARAMETERS::Environment, FALSE, MEM_COMMIT, MEM_RELEASE, MemoryBasicInformation, NT_SUCCESS, NtCurrentPeb, NtCurrentPeb64, NtCurrentProcess, NULL, PAGE_READWRITE, _MEMORY_BASIC_INFORMATION::RegionSize, RtlAcquirePebLock(), RtlCopyMemory, RtlpEnvironCacheValid, RtlReleasePebLock(), Status, STATUS_SUCCESS, ZwAllocateVirtualMemory(), ZwFreeVirtualMemory(), and ZwQueryVirtualMemory().
NTSTATUS RtlSetEnvironmentVariable (IN OUT PVOID *Environment OPTIONAL, IN PCUNICODE_STRING Name, IN PCUNICODE_STRING Value OPTIONAL)
Definition at line 518 of file environ.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _RTL_USER_PROCESS_PARAMETERS::Environment, except, EXCEPTION_EXECUTE_HANDLER, FALSE, leave, _UNICODE_STRING::Length, _RTL_USER_PROCESS_PARAMETERS::Length, _UNICODE_STRING::MaximumLength, MEM_COMMIT, MEM_RELEASE, MemoryBasicInformation, NT_SUCCESS, NtCurrentPeb, NtCurrentPeb64, NtCurrentProcess, NULL, PAGE_READWRITE, _MEMORY_BASIC_INFORMATION::RegionSize, RtlAcquirePebLock(), RtlCompareUnicodeString(), RtlMoveMemory, RtlpEnvironCacheValid, RtlReleasePebLock(), Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_VARIABLE_NOT_FOUND, TRUE, ZwAllocateVirtualMemory(), ZwFreeVirtualMemory(), and ZwQueryVirtualMemory().
Variable Documentation
UNICODE_STRING RtlpEnvironCacheName
Definition at line 256 of file environ.c.
BOOLEAN RtlpEnvironCacheValid
Definition at line 35 of file environ.c.
Referenced by RtlDestroyEnvironment(), RtlQueryEnvironmentVariable_U(), RtlSetCurrentEnvironment(), RtlSetEnvironmentStrings(), and RtlSetEnvironmentVariable().
UNICODE_STRING RtlpEnvironCacheValue
Definition at line 257 of file environ.c.