Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/unc.c File Reference
unc.c File Reference
#include "fsrtlp.h"
#include <zwapi.h>
#include <ntddmup.h>
#include <ntddnull.h>
Macros
#define DevMup DD_MUP_DEVICE_NAME
#define DevNull L"\\Device\\Null"
#define DISABLE_DFS_VALUE_NAME L"DisableDfs"
#define MODULE_POOL_TAG ('nuSF')
#define MupRegKey L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\Mup"
#define UNCSymbolicLink L"\\DosDevices\\UNC"
Functions
VOID FsRtlDeregisterUncProvider (__in HANDLE Handle)
BOOLEAN FsRtlpIsDfsEnabled ()
NTSTATUS FsRtlpOpenDev (IN OUT PHANDLE Handle, IN LPWSTR DevNameStr)
NTSTATUS FsRtlpRegisterProviderWithMUP (IN HANDLE mupHandle, IN PUNICODE_STRING RedirDevName, IN BOOLEAN MailslotsSupported)
VOID FsRtlpSetSymbolicLink (IN PUNICODE_STRING DevName OPTIONAL)
NTSTATUS FsRtlRegisterUncProvider (__inout PHANDLE MupHandle, __in PUNICODE_STRING RedirDevName, __in BOOLEAN MailslotsSupported)
Variables
struct {
BOOLEAN MailslotsSupported
HANDLE MupHandle
UNICODE_STRING RedirDevName
HANDLE ReturnedHandle
} FsRtlpDRD = {0}
ULONG FsRtlpRedirs = 0
KSEMAPHORE FsRtlpUncSemaphore
Macro Definition Documentation
#define DevMup DD_MUP_DEVICE_NAME
Definition at line 28 of file unc.c.
Referenced by FsRtlRegisterUncProvider().
#define DevNull L"\\Device\\Null"
Definition at line 27 of file unc.c.
Referenced by FsRtlRegisterUncProvider().
#define DISABLE_DFS_VALUE_NAME L"DisableDfs"
Referenced by FsRtlpIsDfsEnabled().
#define MODULE_POOL_TAG ('nuSF')
Definition at line 35 of file unc.c.
Referenced by FsRtlpRegisterProviderWithMUP(), and FsRtlRegisterUncProvider().
#define MupRegKey L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\Mup"
Definition at line 25 of file unc.c.
Referenced by FsRtlpIsDfsEnabled(), and FsRtlRegisterUncProvider().
#define UNCSymbolicLink L"\\DosDevices\\UNC"
Definition at line 26 of file unc.c.
Referenced by FsRtlpSetSymbolicLink().
Function Documentation
VOID FsRtlDeregisterUncProvider (__in HANDLE Handle)
Definition at line 417 of file unc.c.
References ASSERT, Executive, ExFreePool(), FALSE, FsRtlpDRD, FsRtlpRedirs, FsRtlpSetSymbolicLink(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), NT_SUCCESS, NULL, PAGED_CODE, and ZwClose().
BOOLEAN FsRtlpIsDfsEnabled ()
Definition at line 486 of file unc.c.
References DISABLE_DFS_VALUE_NAME, FALSE, InitializeObjectAttributes, KEY_READ, KeyValuePartialInformation, MupRegKey, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, REG_DWORD, TRUE, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by FsRtlRegisterUncProvider().
NTSTATUS FsRtlpOpenDev (IN OUT PHANDLE Handle, IN LPWSTR DevNameStr)
Definition at line 182 of file unc.c.
References FILE_ATTRIBUTE_NORMAL, FILE_OPEN, FILE_SHARE_READ, FILE_SHARE_WRITE, GENERIC_WRITE, InitializeObjectAttributes, NT_SUCCESS, NULL, PAGED_CODE, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, and ZwCreateFile().
Referenced by FsRtlRegisterUncProvider().
NTSTATUS FsRtlpRegisterProviderWithMUP (IN HANDLE mupHandle, IN PUNICODE_STRING RedirDevName, IN BOOLEAN MailslotsSupported)
Definition at line 103 of file unc.c.
References ASSERT, _REDIRECTOR_REGISTRATION::DeviceNameLength, _REDIRECTOR_REGISTRATION::DeviceNameOffset, ExAllocatePoolWithTag, ExFreePool(), FSCTL_MUP_REGISTER_UNC_PROVIDER, _REDIRECTOR_REGISTRATION::MailslotsSupported, MailslotsSupported, MODULE_POOL_TAG, NonPagedPool, NT_SUCCESS, NtFsControlFile(), NtWaitForSingleObject(), NULL, PAGED_CODE, RtlCopyMemory, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and TRUE.
Referenced by FsRtlRegisterUncProvider().
VOID FsRtlpSetSymbolicLink (IN PUNICODE_STRING DevName OPTIONAL)
Definition at line 230 of file unc.c.
References ARGUMENT_PRESENT, ASSERT, IoCreateSymbolicLink(), IoDeleteSymbolicLink(), NT_SUCCESS, PAGED_CODE, RtlInitUnicodeString(), UNCSymbolicLink, and VOID.
Referenced by FsRtlDeregisterUncProvider(), and FsRtlRegisterUncProvider().
NTSTATUS FsRtlRegisterUncProvider (__inout PHANDLE MupHandle, __in PUNICODE_STRING RedirDevName, __in BOOLEAN MailslotsSupported)
Definition at line 246 of file unc.c.
References DevMup, DevNull, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, FsRtlpDRD, FsRtlpIsDfsEnabled(), FsRtlpOpenDev(), FsRtlpRedirs, FsRtlpRegisterProviderWithMUP(), FsRtlpSetSymbolicLink(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), MailslotsSupported, MODULE_POOL_TAG, MupRegKey, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, STATUS_INSUFFICIENT_RESOURCES, VOID, ZwClose(), and ZwLoadDriver().
Variable Documentation
struct { ... } FsRtlpDRD
Referenced by FsRtlDeregisterUncProvider(), and FsRtlRegisterUncProvider().
ULONG FsRtlpRedirs = 0
Definition at line 90 of file unc.c.
Referenced by FsRtlDeregisterUncProvider(), and FsRtlRegisterUncProvider().
KSEMAPHORE FsRtlpUncSemaphore
Definition at line 98 of file unc.c.
Referenced by FsRtlInitSystem().
BOOLEAN MailslotsSupported
Definition at line 84 of file unc.c.
Referenced by FsRtlpRegisterProviderWithMUP(), and FsRtlRegisterUncProvider().
HANDLE MupHandle
Definition at line 81 of file unc.c.
UNICODE_STRING RedirDevName
Definition at line 83 of file unc.c.
HANDLE ReturnedHandle
Definition at line 82 of file unc.c.