Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/dataprov.c File Reference
dataprov.c File Reference
#include "wmikmp.h"
Macros
#define WmipGuidCount (sizeof(WmipGuidList) / sizeof(GUIDREGINFO))
Enumerations
enum WMIGUIDINDEXES {
PnPIdGuidIndex = 0, PnPIdInstanceNamesGuidIndex, MSAcpiInfoGuidIndex, MCARawDataGuidIndex,
RawMCAEventGuidIndex, RawCMCEventGuidIndex, RawCPEEventGuidIndex
}
Functions
NTSTATUS IoWMICompleteRequest (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN NTSTATUS Status, IN ULONG BufferUsed, IN CCHAR PriorityBoost)
NTSTATUS IoWMISystemControl (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS WmipExecuteWmiMethod (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG MethodId, IN ULONG InBufferSize, IN ULONG OutBufferSize, IN OUT PUCHAR Buffer)
BOOLEAN WmipFindGuid (IN PGUIDREGINFO GuidList, IN ULONG GuidCount, IN LPGUID Guid, OUT PULONG GuidIndex, OUT PULONG InstanceCount)
NTSTATUS WmipQueryWmiDataBlock (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG InstanceCount, IN OUT PULONG InstanceLengthArray, IN ULONG BufferAvail, OUT PUCHAR Buffer)
NTSTATUS WmipQueryWmiRegInfo (IN PDEVICE_OBJECT DeviceObject, OUT ULONG *RegFlags, OUT PUNICODE_STRING InstanceName, OUT PUNICODE_STRING *RegistryPath)
NTSTATUS WmipSetWmiDataBlock (PDEVICE_OBJECT DeviceObject, PIRP Irp, ULONG GuidIndex, ULONG InstanceIndex, ULONG BufferSize, PUCHAR Buffer)
Variables
const GUIDREGINFO WmipGuidList []
const WMILIB_INFO WmipWmiLibInfo
Macro Definition Documentation
#define WmipGuidCount (sizeof(WmipGuidList) / sizeof(GUIDREGINFO))
Definition at line 175 of file dataprov.c.
Enumeration Type Documentation
enum WMIGUIDINDEXES
Enumerator
PnPIdGuidIndex
PnPIdInstanceNamesGuidIndex
MSAcpiInfoGuidIndex
MCARawDataGuidIndex
RawMCAEventGuidIndex
RawCMCEventGuidIndex
RawCPEEventGuidIndex
Definition at line 177 of file dataprov.c.
Function Documentation
NTSTATUS IoWMICompleteRequest (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN NTSTATUS Status, IN ULONG BufferUsed, IN CCHAR PriorityBoost)
Definition at line 1292 of file dataprov.c.
References _WNODE_HEADER::BufferSize, tagWNODE_ALL_DATA::DataBlockOffset, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, tagWNODE_METHOD_ITEM::DataBlockOffset, _WNODE_HEADER::Flags, tagWNODE_ALL_DATA::InstanceCount, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_ALL_DATA, IRP_MN_QUERY_SINGLE_INSTANCE, KeQuerySystemTime(), OFFSETINSTANCEDATAANDLENGTH::LengthInstanceData, _IO_STACK_LOCATION::MinorFunction, NT_SUCCESS, OFFSETINSTANCEDATAANDLENGTH::OffsetInstanceData, tagWNODE_ALL_DATA::OffsetInstanceDataAndLength, PAGED_CODE, _IO_STACK_LOCATION::Parameters, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, tagWNODE_METHOD_ITEM::SizeDataBlock, tagWNODE_TOO_SMALL::SizeNeeded, Status, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, _WNODE_HEADER::TimeStamp, UNREFERENCED_PARAMETER, WmipAssert, WNODE_FLAG_TOO_SMALL, tagWNODE_ALL_DATA::WnodeHeader, tagWNODE_SINGLE_INSTANCE::WnodeHeader, tagWNODE_METHOD_ITEM::WnodeHeader, and tagWNODE_TOO_SMALL::WnodeHeader.
Referenced by IoWMISystemControl(), and WmipQueryWmiDataBlock().
NTSTATUS IoWMISystemControl (IN PWMILIB_INFO WmiLibInfo, IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 720 of file dataprov.c.
References _UNICODE_STRING::Buffer, WMIREGINFOW::BufferSize, tagWNODE_ALL_DATA::DataBlockOffset, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, tagWNODE_SINGLE_ITEM::DataBlockOffset, tagWNODE_METHOD_ITEM::DataBlockOffset, _REGENTRY::DeviceObject, ExFreePool(), FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, WMIREGGUIDW::Flags, GUIDREGINFO::Flags, WMIREGGUIDW::Guid, GUIDREGINFO::Guid, WMIREGINFOW::GuidCount, tagWNODE_ALL_DATA::InstanceCount, WMIREGGUIDW::InstanceCount, GUIDREGINFO::InstanceCount, WMIREGGUIDW::InstanceInfo, IO_NO_INCREMENT, IoCallDriver(), IoCompleteRequest(), IoGetCurrentIrpStackLocation, IoSkipCurrentIrpStackLocation, IoWMICompleteRequest(), IRP_MN_CHANGE_SINGLE_INSTANCE, IRP_MN_CHANGE_SINGLE_ITEM, IRP_MN_DISABLE_COLLECTION, IRP_MN_DISABLE_EVENTS, IRP_MN_ENABLE_COLLECTION, IRP_MN_ENABLE_EVENTS, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_ALL_DATA, IRP_MN_QUERY_SINGLE_INSTANCE, IRP_MN_REGINFO, IRP_MN_REGINFO_EX, tagWNODE_SINGLE_ITEM::ItemId, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _REGENTRY::MaxInstanceNames, tagWNODE_METHOD_ITEM::MethodId, _IO_STACK_LOCATION::MinorFunction, WMIREGINFOW::MofResourceName, WMIREGINFOW::NextWmiRegInfo, NT_SUCCESS, NULL, tagWNODE_ALL_DATA::OffsetInstanceDataAndLength, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PnPIdGuidIndex, PnPIdInstanceNamesGuidIndex, _WNODE_HEADER::ProviderId, WMIREGINFOW::RegistryPath, RtlCopyMemory, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, tagWNODE_METHOD_ITEM::SizeDataBlock, tagWNODE_SINGLE_ITEM::SizeDataItem, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, STATUS_WMI_GUID_NOT_FOUND, STATUS_WMI_INSTANCE_NOT_FOUND, STATUS_WMI_READ_ONLY, TRUE, WmiDataBlockCollection, WmiEventGeneration, WmipAssert, WmipFindGuid(), WmipFindRegEntryByProviderId, WmipUnreferenceRegEntry, WMIREG_FLAG_INSTANCE_LIST, WMIREG_FLAG_INSTANCE_PDO, WMIREGINFOW::WmiRegGuid, WNODE_FLAG_FIXED_INSTANCE_SIZE, WNODE_FLAG_STATIC_INSTANCE_NAMES, tagWNODE_ALL_DATA::WnodeHeader, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipSystemControl().
NTSTATUS WmipExecuteWmiMethod (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG MethodId, IN ULONG InBufferSize, IN ULONG OutBufferSize, IN OUT PUCHAR Buffer)
BOOLEAN WmipFindGuid (IN PGUIDREGINFO GuidList, IN ULONG GuidCount, IN LPGUID Guid, OUT PULONG GuidIndex, OUT PULONG InstanceCount)
Definition at line 669 of file dataprov.c.
References FALSE, IsEqualGUID, PAGED_CODE, and TRUE.
Referenced by IoWMISystemControl().
NTSTATUS WmipQueryWmiDataBlock (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN ULONG GuidIndex, IN ULONG InstanceIndex, IN ULONG InstanceCount, IN OUT PULONG InstanceLengthArray, IN ULONG BufferAvail, OUT PUCHAR Buffer)
Definition at line 282 of file dataprov.c.
References _MSAcpiInfo::BootArchitecture, _UNICODE_STRING::Buffer, _MSAcpiInfo::Capabilities, _RTL_QUERY_REGISTRY_TABLE::DefaultType, _RTL_QUERY_REGISTRY_TABLE::EntryContext, FALSE, _RTL_QUERY_REGISTRY_TABLE::Flags, IO_NO_INCREMENT, IoWMICompleteRequest(), _UNICODE_STRING::Length, MCARawDataGuidIndex, MSAcpiInfoGuidIndex, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, PAGED_CODE, _REGENTRY::PDO, PnPIdGuidIndex, PnPIdInstanceNamesGuidIndex, _MSAcpiInfo::PreferredProfile, _RTL_QUERY_REGISTRY_TABLE::QueryRoutine, REG_NONE, RTL_QUERY_REGISTRY_DIRECT, RTL_QUERY_REGISTRY_REQUIRED, RTL_REGISTRY_ABSOLUTE, RtlCopyMemory, RtlFreeUnicodeString(), RtlQueryRegistryValues(), RtlZeroMemory, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WMI_GUID_NOT_FOUND, WmipAssert, WmipFindRegEntryByDevice(), WmipGetRawMCAInfo(), WmipGetSMBiosEventlog(), WmipGetSMBiosTableData(), WmipGetSysIds(), WmipPDOToDeviceInstanceName(), and WmipUnreferenceRegEntry.
NTSTATUS WmipQueryWmiRegInfo (IN PDEVICE_OBJECT DeviceObject, OUT ULONG * RegFlags, OUT PUNICODE_STRING InstanceName, OUT PUNICODE_STRING * RegistryPath)
Definition at line 223 of file dataprov.c.
References PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), Status, TRUE, UNREFERENCED_PARAMETER, and WmipRegistryPath.
NTSTATUS WmipSetWmiDataBlock (PDEVICE_OBJECT DeviceObject, PIRP Irp, ULONG GuidIndex, ULONG InstanceIndex, ULONG BufferSize, PUCHAR Buffer)
Variable Documentation
const GUIDREGINFO WmipGuidList[]
Definition at line 95 of file dataprov.c.
const WMILIB_INFO WmipWmiLibInfo
Initial value:
=
{
    NULL,
    NULL,
    WmipGuidCount,
    (PGUIDREGINFO)WmipGuidList,
    WmipQueryWmiRegInfo,
    WmipQueryWmiDataBlock,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 197 of file dataprov.c.
Referenced by WmipSystemControl().