Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmdown.c File Reference
cmdown.c File Reference
#include "cmp.h"
Functions
VOID CmpDereferenceNameControlBlockWithLock (PCM_NAME_CONTROL_BLOCK Ncb)
VOID CmpDumpKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN PULONG Count, IN PVOID Context)
VOID CmpFreeAllMemory (VOID)
VOID CmShutdownSystem (VOID)
Variables
BOOLEAN CmFirstTime
ULONG CmpDelayedCloseSize
HIVE_LIST_ENTRY CmpMachineHiveList []
PUCHAR CmpStashBuffer
BOOLEAN HvShutdownComplete
Function Documentation
VOID CmpDereferenceNameControlBlockWithLock (PCM_NAME_CONTROL_BLOCK Ncb)
Definition at line 1125 of file cmsubs.c.
References ASSERT, CmpLockNameHashEntryExclusive, CmpUnlockNameHashEntry, _CM_NAME_CONTROL_BLOCK::ConvKey, ExFreePoolWithTag, GET_HASH_ENTRY, _CM_NAME_CONTROL_BLOCK::NameHash, _CM_NAME_HASH::NextHash, NULL, PROTECTED_POOL, _CM_NAME_CONTROL_BLOCK::RefCount, and TRUE.
Referenced by CmpCleanUpKcbCacheWithLock().
VOID CmpDumpKeyBodyList (IN PCM_KEY_CONTROL_BLOCK kcb, IN PULONG Count, IN PVOID Context)
Definition at line 223 of file cmsubs.c.
References ASSERT, ASSERT_KCB_LOCKED_EXCLUSIVE, CMP_FAST_KEY_BODY_ARRAY_DUMP, CMP_FAST_KEY_BODY_ARRAY_FLUSH, CMP_LOCK_FREE_KEY_BODY_ARRAY_SIZE, CmpConstructName(), CmpDelayedCloseSize, CmpDumpOneKeyBody(), CONTAINING_RECORD, ExFreePoolWithTag, FALSE, _LIST_ENTRY::Flink, InterlockedCompareExchangePointer, IsListEmpty, _CM_KEY_BODY::KeyBodyList, NULL, PROTECTED_POOL, STATUS_INSUFFICIENT_RESOURCES, and TRUE.
Referenced by CmpFreeAllMemory(), and CmpSearchForOpenSubKeys().
VOID CmpFreeAllMemory (VOID)
Definition at line 61 of file cmdown.c.
References ASSERT, _HHIVE::BaseBlock, CM_BUGCHECK, CmpCacheTable, CmpDestroyCmPrivateAlloc(), CmpDestroyCmPrivateDelayAlloc(), CmpDestroySecurityCache(), CmpDumpKeyBodyList(), CmpFree(), CmpFreeMutex, CmpFreeResource, CmpHashTableSize, CmpHiveListHead, CmpNameCacheTable, CmpRunDownDelayDerefKCBEngine(), CmpStashBuffer, CONTAINING_RECORD, Count, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, _CM_KEY_HASH_TABLE_ENTRY::Entry, ExFreePool(), FALSE, _CMHIVE::FileHandles, _HBASE_BLOCK::FileName, _LIST_ENTRY::Flink, _CMHIVE::FlusherLock, HANDLES_STILL_OPEN_AT_SHUTDOWN, HBASE_NAME_ALLOC, HFILE_TYPE_MAX, _CMHIVE::Hive, HvFreeHive(), IsListEmpty, _CM_POST_KEY_BODY::KeyBody, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_HASH::NextHash, _CM_POST_BLOCK::NotifyList, _CMHIVE::NotifyList, NULL, PostAsyncKernel, PostAsyncUser, PostBlockType, _CM_POST_BLOCK::PostKeyBody, _CM_NOTIFY_BLOCK::PostList, PostSynchronous, REGISTRY_ERROR, RemoveHeadList(), TRUE, and _CMHIVE::ViewLock.
Referenced by CmShutdownSystem().
VOID CmShutdownSystem (VOID)
Definition at line 249 of file cmdown.c.
References CM_PAGED_CODE, CmCompressKey(), CmFirstTime, CmpCmdHiveClose(), CmpDestroyHiveViewList(), CmpDoFlushAll(), CmpDropFileObjectForHive(), CmpFreeAllMemory(), CmpHiveListHead, CmpLockRegistryExclusive(), CmpRegistryRootHandle, CmpShutdownWorkers(), CmpUnJoinClassOfTrust, CmpUnlockRegistry(), CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _CMHIVE::Hive, HvShutdownComplete, KernelMode, KEY_READ, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), ObReferenceObjectByHandle, PO_CLEAN_SHUTDOWN_REGISTRY, PoCleanShutdownEnabled(), Status, SYSTEM_HIVE_INDEX, and TRUE.
Variable Documentation
BOOLEAN CmFirstTime
Definition at line 342 of file cmdat.c.
Referenced by CmShutdownSystem().
ULONG CmpDelayedCloseSize
Definition at line 31 of file cmdelay.c.
HIVE_LIST_ENTRY CmpMachineHiveList[]
Definition at line 284 of file cmdat.c.
PUCHAR CmpStashBuffer
Definition at line 64 of file cmdat2.c.
Referenced by CmpFreeAllMemory().
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by CmShutdownSystem().