Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hive.h File Reference
hive.h File Reference
#include "hivedata.h"
Data Structures
struct _HV_HIVE_CELL_PAIR
struct _HV_TRACK_CELL_REF
Macros
#define ASSERT_CELL_DIRTY(_Hive_, _Cell_)
#define ASSERT_LISTENTRY(ListEntry)
#define CmpFindFirstSetLeft KiFindFirstSetLeft
#define CmpFindFirstSetRight KiFindFirstSetRight
#define DHvCheckBin(h, a)
#define DHvCheckHive(a)
#define HINIT_CREATE 0
#define HINIT_FILE 2
#define HINIT_FLAT 4
#define HINIT_MAPFILE 5
#define HINIT_MEMORY 1
#define HINIT_MEMORY_INPLACE 3
#define HIVE_HAS_BEEN_FREED 8
#define HIVE_HAS_BEEN_REPLACED 4
#define HIVE_IS_UNLOADING 0x20
#define HIVE_NOLAZYFLUSH 2
#define HIVE_VOLATILE 1
#define HvGetCell(Hive, Cell) (((Hive)->GetCellRoutine)(Hive, Cell))
#define HvpComputeIndex(Index, Size)
#define HvReleaseCell(Hive, Cell) if((Hive)->ReleaseCellRoutine) ((Hive)->ReleaseCellRoutine)(Hive, Cell)
#define ROUND_UP(a, b) (((ULONG)(a) + (ULONG)(b) - 1) & ~((ULONG)(b) - 1))
#define STATIC_CELL_PAIR_COUNT 4
Typedefs
typedef struct _HV_HIVE_CELL_PAIR HV_HIVE_CELL_PAIR
typedef struct _HV_TRACK_CELL_REF HV_TRACK_CELL_REF
typedef struct _HV_HIVE_CELL_PAIR * PHV_HIVE_CELL_PAIR
typedef struct _HV_TRACK_CELL_REF * PHV_TRACK_CELL_REF
Functions
HCELL_INDEX HvAllocateCell (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
BOOLEAN HvAutoCompressCheck (PHHIVE Hive)
ULONG HvCheckBin (PHHIVE Hive, PHBIN Bin, PULONG Storage)
ULONG HvCheckHive (PHHIVE Hive, PULONG Storage OPTIONAL)
NTSTATUS HvCloneHive (PHHIVE SourceHive, PHHIVE DestHive, PULONG NewLength)
HCELL_INDEX HvDuplicateCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type, BOOLEAN CopyData)
VOID HvFreeCell (PHHIVE Hive, HCELL_INDEX Cell)
VOID HvFreeHive (PHHIVE Hive)
VOID HvFreeHivePartial (PHHIVE Hive, HCELL_INDEX Start, HSTORAGE_TYPE Type)
LONG HvGetCellSize (PHHIVE Hive, PVOID Address)
BOOLEAN HvHiveWillShrink (IN PHHIVE Hive)
NTSTATUS HvInitializeHive (PHHIVE Hive, ULONG OperationType, ULONG HiveFlags, ULONG FileTypes, PVOID HiveData OPTIONAL, PALLOCATE_ROUTINE AllocateRoutine, PFREE_ROUTINE FreeRoutine, PFILE_SET_SIZE_ROUTINE FileSetSizeRoutine, PFILE_WRITE_ROUTINE FileWriteRoutine, PFILE_READ_ROUTINE FileReadRoutine, PFILE_FLUSH_ROUTINE FileFlushRoutine, ULONG Cluster, PUNICODE_STRING FileName)
BOOLEAN HvIsCellAllocated (PHHIVE Hive, HCELL_INDEX Cell)
NTSTATUS HvLoadHive (PHHIVE Hive)
NTSTATUS HvMapHive (PHHIVE Hive)
BOOLEAN HvMarkCellDirty (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN LockHeld)
BOOLEAN HvMarkDirty (PHHIVE Hive, HCELL_INDEX Start, ULONG Length, BOOLEAN DirtyAndPin)
PHBIN HvpAddBin (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type)
VOID HvpAddFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
NTSTATUS HvpAdjustHiveFreeDisplay (IN PHHIVE Hive, IN ULONG HiveLength, IN HSTORAGE_TYPE Type)
BOOLEAN HvpAllocateMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
NTSTATUS HvpBuildMap (PHHIVE Hive, PVOID Image)
NTSTATUS HvpBuildMapAndCopy (PHHIVE Hive, PVOID Image)
BOOLEAN HvpCheckViewBoundary (IN ULONG Start, IN ULONG End)
VOID HvpCleanMap (PHHIVE Hive)
VOID HvpDelistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type)
BOOLEAN HvpDoWriteHive (PHHIVE Hive, ULONG FileType)
VOID HvpDropAllPagedBins (IN PHHIVE Hive)
VOID HvpDropPagedBins (PHHIVE Hive)
NTSTATUS HvpEnlistBinInMap (PHHIVE Hive, ULONG Length, PHBIN Bin, ULONG Offset, PVOID CmView OPTIONAL)
VOID HvpEnlistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG Size, HSTORAGE_TYPE Type, BOOLEAN CoalesceForward)
BOOLEAN HvpEnlistFreeCells (PHHIVE Hive, PHBIN Bin, ULONG BinOffset)
HCELL_INDEX HvpFindFreeCell (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
VOID HvpFreeAllocatedBins (PHHIVE Hive)
VOID HvpFreeHiveFreeDisplay (IN PHHIVE Hive)
VOID HvpFreeMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
ULONG HvpGetBinMemAlloc (IN PHHIVE Hive, PHBIN Bin, IN HSTORAGE_TYPE Type)
struct _CELL_DATA * HvpGetCellFlat (PHHIVE Hive, HCELL_INDEX Cell)
PHMAP_ENTRY HvpGetCellMap (PHHIVE Hive, HCELL_INDEX Cell)
struct _CELL_DATA * HvpGetCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
struct _CELL_DATA * HvpGetCellPaged (PHHIVE Hive, HCELL_INDEX Cell)
PHCELL HvpGetHCell (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN HvpGrowLog1 (PHHIVE Hive, ULONG Count)
BOOLEAN HvpGrowLog2 (PHHIVE Hive, ULONG Size)
ULONG HvpHeaderCheckSum (PHBASE_BLOCK BaseBlock)
NTSTATUS HvpInitMap (PHHIVE Hive)
VOID HvpReleaseCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
VOID HvpRemoveFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
BOOLEAN HvpWriteLog (PHHIVE Hive)
NTSTATUS HvReadInMemoryHive (PHHIVE Hive, PVOID *HiveImage)
HCELL_INDEX HvReallocateCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG NewSize)
VOID HvRefreshHive (PHHIVE Hive)
VOID HvReleaseFreeCellRefArray (PHV_TRACK_CELL_REF CellRef)
HCELL_INDEX HvShiftCell (PHHIVE Hive, HCELL_INDEX Cell)
NTSTATUS HvShrinkHive (PHHIVE Hive, ULONG NewLength)
BOOLEAN HvSyncHive (PHHIVE Hive)
BOOLEAN HvTrackCellRef (PHV_TRACK_CELL_REF CellRef, PHHIVE Hive, HCELL_INDEX Cell)
NTSTATUS HvWriteHive (PHHIVE Hive, BOOLEAN DontGrow, BOOLEAN WriteThroughCache, BOOLEAN CrashSafe)
Macro Definition Documentation
#define ASSERT_CELL_DIRTY (_Hive_, _Cell_)
Definition at line 293 of file hive.h.
Referenced by CmDeleteKey(), CmDeleteValueKey(), CmpAddValueToList(), CmpCopyKeyPartial(), CmpRemoveSubKey(), CmpRemoveValueFromList(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), and HvFreeCell().
#define ASSERT_LISTENTRY (ListEntry)
Value:
ASSERT((ListEntry)->Flink->Blink==ListEntry); \
    ASSERT((ListEntry)->Blink->Flink==ListEntry);
Definition at line 46 of file hive.h.
Referenced by HvpAddBin(), HvpDelistBinFreeCells(), and HvpEnlistFreeCell().
#define CmpFindFirstSetLeft KiFindFirstSetLeft
Definition at line 363 of file hive.h.
#define CmpFindFirstSetRight KiFindFirstSetRight
Definition at line 362 of file hive.h.
Referenced by HvpFindFreeCellInThisViewWindow().
#define DHvCheckBin (h, a)
Definition at line 34 of file hive.h.
Referenced by HvFreeCell(), and HvpDoAllocateCell().
#define DHvCheckHive (a)
Definition at line 33 of file hive.h.
Referenced by HvReallocateCell().
#define HINIT_CREATE 0
Definition at line 192 of file hive.h.
Referenced by CmInitSystem1(), CmpCreateTemporaryHive(), CmpInitHiveFromFile(), CmpInitializeSystemHive(), CmpLoadHiveVolatile(), and HvInitializeHive().
#define HINIT_FILE 2
Definition at line 194 of file hive.h.
Referenced by CmpInitHiveFromFile(), CmpInitializeHive(), CmpLoadHiveVolatile(), CmRestoreKey(), and HvInitializeHive().
#define HINIT_FLAT 4
Definition at line 196 of file hive.h.
Referenced by CmGetSystemControlValues(), and HvInitializeHive().
#define HINIT_MAPFILE 5
Definition at line 197 of file hive.h.
Referenced by CmpInitHiveFromFile(), CmpInitializeHive(), and HvInitializeHive().
#define HINIT_MEMORY 1
Definition at line 193 of file hive.h.
Referenced by CmpInitializeHive(), CmpInitializeSystemHive(), and HvInitializeHive().
#define HINIT_MEMORY_INPLACE 3
Definition at line 195 of file hive.h.
Referenced by CmpInitializeHive(), and HvInitializeHive().
#define HIVE_HAS_BEEN_FREED 8
Definition at line 202 of file hive.h.
Referenced by CmpInitializeHive().
#define HIVE_HAS_BEEN_REPLACED 4
Definition at line 201 of file hive.h.
#define HIVE_IS_UNLOADING 0x20
Definition at line 203 of file hive.h.
Referenced by CmLoadKey(), CmpCreateKeyControlBlock(), CmpDoOpen(), CmpLateUnloadHiveWorker(), and CmUnloadKey().
#define HIVE_NOLAZYFLUSH 2
Definition at line 200 of file hive.h.
Referenced by CmLoadKey(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpInitializeSystemHive(), CmpLoadHiveThread(), CmpRefreshHive(), CmpShiftHiveFreeBins(), CmSaveKey(), CmSaveMergedKeys(), HvMarkDirty(), and HvRefreshHive().
#define HIVE_VOLATILE 1
Definition at line 199 of file hive.h.
Referenced by CmGetSystemControlValues(), CmInitSystem1(), CmpAddToHiveFileList(), CmpCreateTemporaryHive(), CmpDoFlushNextHive(), CmpInitializeHive(), CmpInitializeHiveList(), CmpInitializeSystemHive(), CmpLoadHiveThread(), CmpLoadHiveVolatile(), CmpRaiseSelfHealWarningForSystemHives(), HvInitializeHive(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), and HvSyncHive().
#define HvGetCell (Hive, Cell) (((Hive)->GetCellRoutine)(Hive, Cell))
Definition at line 309 of file hive.h.
Referenced by CmCompressKey(), CmDeleteKey(), CmDeleteValueKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmGetSystemControlValues(), CmMoveKey(), CmpAddDriverToList(), CmpAddInfoAfterParseFailure(), CmpAddSecurityCellToCache(), CmpAddSubKey(), CmpAddToLeaf(), CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpAssignSecurityDescriptorWrapper(), CmpCheckKey(), CmpCheckKeyAccess(), CmpCheckLexicographicalOrder(), CmpCheckRegistry2(), CmpCheckValueList(), CmpCleanUpSubKeyInfo(), CmpCompareNewValueDataAgainstKCBCache(), CmpConstructName(), CmpCopyCell(), CmpCopyKeyPartial(), CmpCopySyncTree2(), CmpCopyValue(), CmpCreateLinkNode(), CmpCreateRegistryRoot(), CmpCreateRootNode(), CmpDeleteTree(), CmpDestroyHive(), CmpDoAccessCheckOnSubtree(), CmpDoCompareKeyName(), CmpDoCreate(), CmpDoCreateChild(), CmpDoFindSubKeyByNumber(), CmpDuplicateIndex(), CmpDuplicateKey(), CmpFindControlSet(), CmpFindDrivers(), CmpFindNameInList(), CmpFindNLSData(), CmpFindProfileOption(), CmpFindReusableCellFromCache(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpFindSubKeyInRoot(), CmpFindTagIndex(), CmpFreeKeyBody(), CmpFreeKeyByCell(), CmpFreeKeyValues(), CmpFreeSecurityDescriptor(), CmpFreeValue(), CmpFreeValueData(), CmpGetHiveName(), CmpGetKeySecurity(), CmpGetSymbolicLink(), CmpGetValueData(), CmpGetValueDataFromCache(), CmpGetValueKeyFromCache(), CmpGetValueListFromCache(), CmpInsertSecurityCellList(), CmpIsLoadType(), CmpLoadHiveVolatile(), CmpMarkCurrentValueDirty(), CmpMarkIndexDirty(), CmpMarkKeyDirty(), CmpMarkKeyParentDirty(), CmpMarkKeyValuesDirty(), CmpMarkValueDataDirty(), CmpMergeKeyValues(), CmpNotifyChangeKey(), CmpOverwriteHive(), CmpParseKey(), CmpQueryKeyData(), CmpQueryKeyDataFromCache(), CmpRebuildKcbCache(), CmpRebuildSecurityCache(), CmpRemoveSecurityCellList(), CmpRemoveSubKey(), CmpRemoveSubKeyCellNoCellRef(), CmpRemoveValueFromList(), CmpReportNotify(), CmpReportNotifyHelper(), CmpSaveBootControlSet(), CmpSelectLeaf(), CmpSetCurrentProfile(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpShiftAllCells2(), CmpShiftIndex(), CmpShiftKey(), CmpShiftSecurityCells(), CmpShiftValueList(), CmpSortDriverList(), CmpSplitLeaf(), CmpSyncKeyValues(), CmpSyncSubKeysAfterDelete(), CmpUpdateParentForEachSon(), CmpValidateHiveSecurityDescriptors(), CmpValidateSelect(), CmpWalkPath(), CmQueryKey(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRenameKey(), CmRestoreKey(), CmSaveMergedKeys(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), HvDuplicateCell(), HvpGetHCell(), HvReallocateCell(), and HvRefreshHive().
#define HvpComputeIndex (Index, Size)
Value:
{                                                                   \
        Index = (Size >> HHIVE_FREE_DISPLAY_SHIFT) - 1;                 \
        if (Index >= HHIVE_LINEAR_INDEX ) {                             \
                                                                        \
            /*                                                          \
            ** Too big for the linear lists, compute the exponential    \
            ** list. Shift the index to make sure we cover the whole    \
            ** range.                                                   \
            */                                                          \
            Index >>= 4;                                                \
                                                                        \
            if (Index > 255) {                                          \
                /*                                                      \
                ** Too big for all the lists, use the last index.       \
                */                                                      \
                Index = HHIVE_FREE_DISPLAY_SIZE-1;                      \
            } else {                                                    \
                Index = CmpFindFirstSetLeft[Index] +                    \
                        HHIVE_LINEAR_INDEX;                             \
            }                                                           \
        }                                                               \
    }
Definition at line 365 of file hive.h.
Referenced by HvpDelistFreeCell(), HvpDoAllocateCell(), HvpEnlistFreeCell(), HvpFindFreeCellInBin(), and HvpRemoveFreeCellHint().
#define HvReleaseCell (Hive, Cell) if((Hive)->ReleaseCellRoutine) ((Hive)->ReleaseCellRoutine)(Hive, Cell)
Definition at line 310 of file hive.h.
Referenced by CmCompressKey(), CmDeleteKey(), CmDeleteValueKey(), CmEnumerateKey(), CmEnumerateValueKey(), CmGetSystemControlValues(), CmMoveKey(), CmpAddInfoAfterParseFailure(), CmpAddSecurityCellToCache(), CmpAddSubKey(), CmpAddToLeaf(), CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpAssignSecurityDescriptorWrapper(), CmpCheckKeyAccess(), CmpCheckValueList(), CmpCleanUpSubKeyInfo(), CmpCompareNewValueDataAgainstKCBCache(), CmpConstructName(), CmpCopyCell(), CmpCopyKeyPartial(), CmpCopySyncTree2(), CmpCopyValue(), CmpCreateLinkNode(), CmpCreateRootNode(), CmpDeleteTree(), CmpDestroyHive(), CmpDoCompareKeyName(), CmpDoCreate(), CmpDoCreateChild(), CmpDoFindSubKeyByNumber(), CmpDuplicateIndex(), CmpDuplicateKey(), CmpFindNameInList(), CmpFindReusableCellFromCache(), CmpFindSubKeyByName(), CmpFindSubKeyByNumber(), CmpFindSubKeyInRoot(), CmpFindValueByNameFromCache(), CmpFreeKeyBody(), CmpFreeKeyByCell(), CmpFreeKeyValues(), CmpFreeSecurityDescriptor(), CmpFreeValue(), CmpFreeValueData(), CmpGetHiveName(), CmpGetSymbolicLink(), CmpGetValueData(), CmpLoadHiveVolatile(), CmpMarkCurrentValueDirty(), CmpMarkIndexDirty(), CmpMarkKeyDirty(), CmpMarkKeyValuesDirty(), CmpMarkValueDataDirty(), CmpNotifyChangeKey(), CmpOverwriteHive(), CmpQueryKeyData(), CmpQueryKeyDataFromCache(), CmpQueryKeyValueData(), CmpRebuildKcbCache(), CmpRemoveSecurityCellList(), CmpRemoveSubKey(), CmpRemoveSubKeyCellNoCellRef(), CmpRemoveValueFromList(), CmpReportNotify(), CmpReportNotifyHelper(), CmpSaveBootControlSet(), CmpSetValueDataExisting(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmpSyncSubKeysAfterDelete(), CmpUpdateParentForEachSon(), CmQueryMultipleValueKey(), CmQueryValueKey(), CmRenameKey(), CmRestoreKey(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), HvDuplicateCell(), HvFreeCell(), HvIsCellAllocated(), HvMarkCellDirty(), HvpDelistFreeCell(), HvpDoAllocateCell(), HvpEnlistFreeCell(), HvReallocateCell(), HvRefreshHive(), HvReleaseFreeCellRefArray(), and HvTrackCellRef().
#define ROUND_UP (a, b) (((ULONG)(a) + (ULONG)(b) - 1) & ~((ULONG)(b) - 1))
Definition at line 37 of file hive.h.
Referenced by CmpAddValueToList(), CmpDoFileSetSize(), CmpOverwriteHive(), CmpPrefetchHiveFile(), HvAllocateCell(), HvMarkDirty(), HvpAddBin(), HvpBuildMapAndCopy(), HvpCleanMap(), HvpDoWriteHive(), HvpFindNextDirtyBlock(), HvpGetCellMapped(), HvpGrowLog1(), HvpGrowLog2(), HvpInitMap(), HvpRecoverData(), HvpWriteLog(), HvReallocateCell(), HvRefreshHive(), and HvWriteHive().
#define STATIC_CELL_PAIR_COUNT 4
Definition at line 486 of file hive.h.
Referenced by HvReleaseFreeCellRefArray(), and HvTrackCellRef().
Typedef Documentation
typedef struct _HV_HIVE_CELL_PAIR HV_HIVE_CELL_PAIR
typedef struct _HV_TRACK_CELL_REF HV_TRACK_CELL_REF
typedef struct _HV_HIVE_CELL_PAIR* PHV_HIVE_CELL_PAIR
typedef struct _HV_TRACK_CELL_REF* PHV_TRACK_CELL_REF
Function Documentation
HCELL_INDEX HvAllocateCell (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
Definition at line 858 of file hivecell.c.
References ASSERT, CmKdPrintEx, CML_HIVE, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, HCELL_NIL, HCELL_PAD, HHIVE_SIGNATURE, HSANE_CELL_MAX, HvIsCellAllocated(), HvpAdjustCellSize, HvpDoAllocateCell(), _HHIVE::ReadOnly, ROUND_UP, _HHIVE::Signature, _CELL_DATA::u, and USE_OLD_CELL.
Referenced by CmpAddSubKey(), CmpAddValueToList(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCreateLinkNode(), CmpCreateRootNode(), CmpDoCreateChild(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmRenameKey(), and HvDuplicateCell().
BOOLEAN HvAutoCompressCheck (PHHIVE Hive)
Definition at line 2094 of file hivecell.c.
References ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CM_HIVE_COMPRESS_LEVEL, CM_PAGED_CODE, CONTAINING_RECORD, FALSE, _CMHIVE::FileHandles, _LIST_ENTRY::Flink, _HHIVE::_DUAL::FreeBins, HFILE_TYPE_PRIMARY, IsListEmpty, _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, NULL, _FREE_HBIN::Size, Stable, _HHIVE::Storage, and TRUE.
Referenced by CmCompressKey().
ULONG HvCheckBin (PHHIVE Hive, PHBIN Bin, PULONG Storage)
Definition at line 204 of file hivechek.c.
References ARGUMENT_PRESENT, Bin, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FIELD_OFFSET, HBIN_NIL, HvCheckBinDebug, _HCELL::NewCell, _HCELL::OldCell, _HCELL::Size, _HBIN::Size, _HCELL::u, and USE_OLD_CELL.
Referenced by HvCheckHive().
ULONG HvCheckHive (PHHIVE Hive, PULONG Storage OPTIONAL)
Definition at line 49 of file hivechek.c.
References ARGUMENT_PRESENT, ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CmpMapThisBin(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HCELL_NIL, Hive, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvCheckBin(), HvCheckHiveDebug, HvpGetCellMap(), _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, Stable, _HHIVE::Storage, and Volatile.
Referenced by CmCheckRegistry(), and HvRefreshHive().
NTSTATUS HvCloneHive (PHHIVE SourceHive, PHHIVE DestHive, PULONG NewLength)
Definition at line 2283 of file hiveload.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmpMapThisBin(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, FileOffset, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HTABLE_SLOTS, HvpAllocateMap(), HvpEnlistBinInMap(), HvpGetCellMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NT_SUCCESS, NULL, _HHIVE::ReadOnly, RtlCopyMemory, RtlZeroMemory, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, _HHIVE::_DUAL::SmallDir, _HBIN::Spare, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, _HHIVE::Storage, and TRUE.
Referenced by CmpShiftHiveFreeBins().
HCELL_INDEX HvDuplicateCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type, BOOLEAN CopyData)
Definition at line 1996 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED, CM_PAGED_CODE, FALSE, HCELL_NIL, HHIVE_SIGNATURE, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellSize(), HvGetCellType, HvIsCellAllocated(), HvReleaseCell, NULL, _HHIVE::ReadOnly, RtlCopyMemory, RtlZeroMemory, _HHIVE::Signature, and TRUE.
Referenced by CmpDuplicateIndex().
VOID HvFreeCell (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1529 of file hivecell.c.
References ASSERT, ASSERT_BIN_VALID, ASSERT_CELL_DIRTY, ASSERT_HIVE_FLUSHER_LOCKED, Bin, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_HIVE, CmpLockHiveWriter, CmpUnlockHiveWriter, DHvCheckBin, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _HBIN::FileOffset, HBIN_BASE, HCELL_FREE_FILL, HCELL_TYPE_MASK, HvGetCellType, HvpEnlistFreeCell(), HvpGetCellMap(), HvpGetHCell(), HvpIsFreeNeighbor(), HvReleaseCell, NULL, _HHIVE::ReadOnly, RtlFillMemory, _HCELL::Size, _HBIN::Size, TRUE, _HCELL::u, _CELL_DATA::u, USE_OLD_CELL, and VALIDATE_CELL_MAP.
Referenced by CmMoveKey(), CmpAddSubKey(), CmpAssignSecurityDescriptor(), CmpCopyCell(), CmpCopyKeyPartial(), CmpCopyValue(), CmpCreateLinkNode(), CmpDoCreateChild(), CmpDuplicateIndex(), CmpFreeKeyBody(), CmpFreeKeyByCell(), CmpFreeKeyValues(), CmpFreeSecurityDescriptor(), CmpFreeValue(), CmpFreeValueData(), CmpRemoveSubKey(), CmpRemoveValueFromList(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmRenameKey(), HvDuplicateCell(), and HvReallocateCell().
VOID HvFreeHive (PHHIVE Hive)
Definition at line 34 of file hivefree.c.
References ASSERT, _HHIVE::BaseBlock, _HHIVE::BaseBlockAlloc, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, CmKdPrintEx, CML_BIN_MAP, CmpFree(), CmpReleaseGlobalQuota(), _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, _HBASE_BLOCK::FileName, _FREE_HBIN::Flags, _HHIVE::Flat, _HHIVE::Free, FREE_HBIN_DISCARDABLE, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HTABLE_SLOTS, HvpFreeHiveFreeDisplay(), HvpFreeMap(), HvpGetBinMemAlloc(), HvpGetCellMap(), _HHIVE::_DUAL::Length, LogHiveFree, _HHIVE::_DUAL::Map, NULL, _HHIVE::ReadOnly, _FREE_HBIN::Size, Stable, _HHIVE::Storage, VALIDATE_CELL_MAP, and Volatile.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), and CmUnloadKey().
VOID HvFreeHivePartial (PHHIVE Hive, HCELL_INDEX Start, HSTORAGE_TYPE Type)
Definition at line 167 of file hivefree.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmpFree(), CmpReleaseGlobalQuota(), CmpUpdateSystemHiveHysteresis(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, FALSE, _FREE_HBIN::Flags, _HHIVE::Flat, FREE_HBIN_DISCARDABLE, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HSECTOR_SIZE, HTABLE_SLOTS, HvpAdjustHiveFreeDisplay(), HvpFreeMap(), HvpGetBinMemAlloc(), HvpGetCellMap(), _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, _HHIVE::_DUAL::Map, _HHIVE::ReadOnly, RemoveEntryList(), RtlClearBits(), RtlNumberOfSetBits(), _FREE_HBIN::Size, _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, and VALIDATE_CELL_MAP.
Referenced by HvpTruncateBins(), and HvRefreshHive().
LONG HvGetCellSize (PHHIVE Hive, PVOID Address)
Referenced by CmpAddToLeaf(), CmpCheckKey(), CmpCheckValueList(), CmpCopyCell(), CmpGetValueKeyFromCache(), CmpSetValueKeyExisting(), and CmpSplitLeaf().
BOOLEAN HvHiveWillShrink (IN PHHIVE Hive)
Definition at line 2759 of file hivesync.c.
References ASSERT, _HMAP_ENTRY::BinAddress, FALSE, HBLOCK_SIZE, HMAP_DISCARDABLE, HvpGetCellMap(), Stable, TRUE, and VALIDATE_CELL_MAP.
Referenced by CmFlushKey(), CmpDoFlushAll(), and CmpDoFlushNextHive().
NTSTATUS HvInitializeHive (PHHIVE Hive, ULONG OperationType, ULONG HiveFlags, ULONG FileTypes, PVOID HiveData OPTIONAL, PALLOCATE_ROUTINE AllocateRoutine, PFREE_ROUTINE FreeRoutine, PFILE_SET_SIZE_ROUTINE FileSetSizeRoutine, PFILE_WRITE_ROUTINE FileWriteRoutine, PFILE_READ_ROUTINE FileReadRoutine, PFILE_FLUSH_ROUTINE FileFlushRoutine, ULONG Cluster, PUNICODE_STRING FileName)
Definition at line 115 of file hiveinit.c.
References _HHIVE::Allocate, ARGUMENT_PRESENT, _HHIVE::BaseBlock, _HHIVE::BaseBlockAlloc, _HBASE_BLOCK::BootRecover, _HBASE_BLOCK::BootType, _HBASE_BLOCK::CheckSum, _HBASE_BLOCK::Cluster, _HHIVE::Cluster, CmKdPrintEx, CML_BIN_MAP, CML_INIT, _HHIVE::DirtyAlloc, _HHIVE::DirtyCount, _HHIVE::DirtyFlag, _HHIVE::DirtyVector, _FREE_DISPLAY::Display, DPFLTR_CONFIG_ID, FALSE, _HHIVE::FileFlush, _HHIVE::FileRead, _HHIVE::FileSetSize, _HHIVE::FileWrite, _HHIVE::Flat, _HBASE_BLOCK::Format, _HHIVE::Free, _HHIVE::_DUAL::FreeBins, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, _HHIVE::GetCellRoutine, _HHIVE::_DUAL::Guard, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBLOCK_SIZE, HCELL_NIL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, HHIVE_FREE_DISPLAY_SIZE, HHIVE_SIGNATURE, _LARGE_INTEGER::HighPart, HINIT_CREATE, HINIT_FILE, HINIT_FLAT, HINIT_MAPFILE, HINIT_MEMORY, HINIT_MEMORY_INPLACE, HIVE_VOLATILE, _HHIVE::HiveFlags, HSECTOR_COUNT, HSECTOR_SIZE, HSYS_MAJOR, HSYS_MINOR, HSYS_MINOR_SUPPORTED, HTYPE_COUNT, HvLoadHive(), HvMapHive(), HvpAdjustHiveFreeDisplay(), HvpBuildMap(), HvpBuildMapAndCopy(), HvpDoWriteHive(), HvpFillFileName(), HvpFreeAllocatedBins(), HvpGetCellFlat(), HvpGetCellMapped(), HvpGetCellPaged(), HvpHeaderCheckSum(), HvpReleaseCellMapped(), InitializeListHead(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::Log, _HHIVE::LogSize, _LARGE_INTEGER::LowPart, _HBASE_BLOCK::Major, _HHIVE::_DUAL::Map, _HBASE_BLOCK::Minor, NT_SUCCESS, NULL, PAGE_SIZE, _HHIVE::ReadOnly, _FREE_DISPLAY::RealVectorSize, _HHIVE::RefreshCount, _HHIVE::ReleaseCellRoutine, _HBASE_BLOCK::RootCell, RtlClearAllBits(), RtlCopyMemory, RtlInitializeBitMap(), _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBASE_BLOCK::Signature, _HHIVE::Signature, _HHIVE::_DUAL::SmallDir, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_IO_FAILED, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, _HHIVE::Storage, _HHIVE::StorageTypeCount, _HBASE_BLOCK::TimeStamp, TRUE, _HBASE_BLOCK::Type, _HHIVE::Version, and Volatile.
Referenced by CmGetSystemControlValues(), and CmpInitializeHive().
BOOLEAN HvIsCellAllocated (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1156 of file hivecell.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, FALSE, _HHIVE::Flat, HBIN_BASE, HBIN_NIL, HCELL_PAD, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_DISCARDABLE, HvGetCellType, HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, leave, _HHIVE::_DUAL::Length, NULL, _HHIVE::Signature, _HCELL::Size, _HHIVE::Storage, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by CmpCheckKey(), CmpCheckValueList(), CmpFindSubKeyByName(), CmpFreeValueData(), CmpMarkIndexDirty(), CmpRebuildSecurityCache(), CmpRemoveSubKey(), CmpValidateHiveSecurityDescriptors(), HvAllocateCell(), HvDuplicateCell(), and HvReallocateCell().
NTSTATUS HvLoadHive (PHHIVE Hive)
Definition at line 375 of file hiveload.c.
References ASSERT, _HHIVE::BaseBlock, _HHIVE::BaseBlockAlloc, _HBASE_BLOCK::BootType, CmDoSelfHeal, _HHIVE::DirtyCount, Fail, FALSE, _HHIVE::Free, HBOOT_SELFHEAL, HFILE_TYPE_PRIMARY, HHIVE_SIGNATURE, HvpAdjustHiveFreeDisplay(), HvpCleanMap(), HvpFreeAllocatedBins(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), _HBASE_BLOCK::Length, _HHIVE::Log, _HBASE_BLOCK::Minor, NoMemory, NotHive, NT_SUCCESS, NULL, RecoverData, RecoverHeader, SelfHeal, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HHIVE::Signature, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_REGISTRY_FILE, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, _HBASE_BLOCK::Type, and _HHIVE::Version.
Referenced by HvInitializeHive().
NTSTATUS HvMapHive (PHHIVE Hive)
Definition at line 113 of file hiveload.c.
References ASSERT, _HHIVE::BaseBlock, _HBASE_BLOCK::BootType, _UNICODE_STRING::Buffer, CmDoSelfHeal, CmKdPrintEx, CmpAcquireFileObjectForFile(), CmpPrefetchHiveFile(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, DPFLTR_TRACE_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, Fail, FALSE, _HBASE_BLOCK::FileName, HBOOT_SELFHEAL, HFILE_TYPE_PRIMARY, HHIVE_SIGNATURE, HvpAdjustHiveFreeDisplay(), HvpCleanMap(), HvpFreeAllocatedBins(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpMapFileImageAndBuildMap(), HvpRecoverData(), _HBASE_BLOCK::Length, _UNICODE_STRING::Length, _HHIVE::Log, _HBASE_BLOCK::Minor, NoMemory, NotHive, NT_SUCCESS, NULL, RecoverData, RecoverHeader, RtlInitUnicodeString(), SelfHeal, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HHIVE::Signature, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_REGISTRY_FILE, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, _HBASE_BLOCK::Type, and _HHIVE::Version.
Referenced by HvInitializeHive().
BOOLEAN HvMarkCellDirty (PHHIVE Hive, HCELL_INDEX Cell, BOOLEAN LockHeld)
Definition at line 135 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_VIEW_MAPPED, ASSERT_VIEW_PINNED, Bin, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_IO, CmLockHiveViews, CmpLockHiveWriter, CmpPinCmView(), CmpUnlockHiveWriter, CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HHIVE_SIGNATURE, HIVE_VOLATILE, HMAP_INVIEW, HvGetCellType, HvMarkDirty(), HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, IsListEmpty, _HCELL::NewCell, NT_SUCCESS, NULL, _CM_VIEW_OF_FILE::PinViewList, _HHIVE::ReadOnly, RtlNumberOfSetBits(), _HBIN::Signature, _HHIVE::Signature, _HCELL::Size, _HBIN::Size, TRUE, USE_OLD_CELL, VALIDATE_CELL_MAP, and Volatile.
Referenced by CmDeleteValueKey(), CmMoveKey(), CmpAddSubKey(), CmpAddToLeaf(), CmpAssignSecurityDescriptor(), CmpCheckKey(), CmpCheckValueList(), CmpCopySyncTree2(), CmpCreateLinkNode(), CmpDoCreate(), CmpInsertSecurityCellList(), CmpMarkCurrentValueDirty(), CmpMarkIndexDirty(), CmpMarkKeyDirty(), CmpMarkKeyParentDirty(), CmpMarkKeyValuesDirty(), CmpMarkValueDataDirty(), CmpOverwriteHive(), CmpRemoveSubKeyCellNoCellRef(), CmpSaveBootControlSet(), CmpSelectLeaf(), CmpSetSecurityDescriptorInfo(), CmpSetValueKeyExisting(), CmpSetValueKeyNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmpUpdateParentForEachSon(), CmpValidateHiveSecurityDescriptors(), CmRenameKey(), CmRestoreKey(), CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), CmSetValueKey(), HvpFindFreeCellInBin(), and HvpIsFreeNeighbor().
BOOLEAN HvMarkDirty (PHHIVE Hive, HCELL_INDEX Start, ULONG Length, BOOLEAN DirtyAndPin)
Definition at line 293 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_VIEW_MAPPED, ASSERT_VIEW_PINNED, BIN_MAP_ALLOCATION_TYPE, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_IO, CmLockHiveViews, CmpLazyFlush(), CmpMapCmView(), CmpPinCmView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, HHIVE_SIGNATURE, HIVE_NOLAZYFLUSH, HIVE_VOLATILE, _HHIVE::HiveFlags, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_COUNT, HSECTOR_PER_PAGE_COUNT, HSECTOR_SIZE, HvGetCellType, HvpGetCellMap(), HvpGrowLog1(), HvpMarkBinReadWrite, IsListEmpty, NT_SUCCESS, NULL, PAGE_SIZE, _CM_VIEW_OF_FILE::PinViewList, _HHIVE::ReadOnly, ROUND_UP, RtlCheckBit, RtlNumberOfSetBits(), RtlSetBits(), _HHIVE::Signature, Stable, TRUE, VALIDATE_CELL_MAP, and Volatile.
Referenced by HvMarkCellDirty(), HvpAddBin(), HvpEnlistFreeCell(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), and HvpRecoverData().
PHBIN HvpAddBin (PHHIVE Hive, ULONG NewSize, HSTORAGE_TYPE Type)
Referenced by HvpDoAllocateCell().
VOID HvpAddFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
Definition at line 256 of file hivehint.c.
References ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, Bin, _HMAP_ENTRY::BinAddress, CM_PAGED_CODE, _HBIN::FileOffset, HBIN_BASE, HBLOCK_SIZE, HvpGetCellMap(), Index, RtlSetBits(), _HBIN::Size, and VALIDATE_CELL_MAP.
Referenced by HvpEnlistFreeCell().
NTSTATUS HvpAdjustHiveFreeDisplay (IN PHHIVE Hive, IN ULONG HiveLength, IN HSTORAGE_TYPE Type)
Definition at line 69 of file hivehint.c.
References CM_PAGED_CODE, HHIVE_FREE_DISPLAY_SIZE, HvpAdjustBitmap(), NT_SUCCESS, Status, and STATUS_SUCCESS.
Referenced by HvFreeHivePartial(), HvInitializeHive(), HvLoadHive(), HvMapHive(), HvpAddBin(), HvRefreshHive(), and HvShrinkHive().
BOOLEAN HvpAllocateMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
Definition at line 899 of file hivemap.c.
References _HHIVE::Allocate, ASSERT, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::CmView, _HMAP_DIRECTORY::Directory, FALSE, HTABLE_SLOTS, NULL, RtlZeroMemory, _HMAP_TABLE::Table, and TRUE.
Referenced by HvCloneHive(), HvpAddBin(), HvpBuildMapAndCopy(), and HvpInitMap().
NTSTATUS HvpBuildMap (PHHIVE Hive, PVOID Image)
Definition at line 519 of file hivemap.c.
References Bin, CmDoSelfHeal, CmKdPrintEx, CML_HIVE, CmMarkSelfHeal, DPFLTR_CONFIG_ID, _HBIN::FileOffset, HBIN_SIGNATURE, HBLOCK_SIZE, Hive, HvCheckHiveDebug, HvpCleanMap(), HvpEnlistBinInMap(), HvpInitMap(), _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, _HBIN::Signature, _HBIN::Size, Stable, Status, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, and _HHIVE::Storage.
Referenced by HvInitializeHive().
NTSTATUS HvpBuildMapAndCopy (PHHIVE Hive, PVOID Image)
Definition at line 46 of file hivemap.c.
References _HHIVE::Allocate, ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, CmKdPrintEx, CML_HIVE, _HMAP_ENTRY::CmView, _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, _HBIN::FileOffset, _HHIVE::Free, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HSECTOR_SIZE, HTABLE_SLOTS, HvpAllocateMap(), HvpEnlistFreeCells(), HvpFreeMap(), HvpGetCellMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, _HMAP_ENTRY::MemAlloc, NULL, _HHIVE::ReadOnly, ROUND_UP, RtlCopyMemory, RtlInitializeBitMap(), RtlZeroMemory, _HBIN::Signature, _HBIN::Size, _HHIVE::_DUAL::SmallDir, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, _HHIVE::Storage, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvInitializeHive().
BOOLEAN HvpCheckViewBoundary (IN ULONG Start, IN ULONG End)
Definition at line 995 of file hivehint.c.
References CM_PAGED_CODE, CM_VIEW_SIZE, FALSE, HBLOCK_SIZE, and TRUE.
Referenced by HvpAddBin(), HvpCoalesceDiscardedBins(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpFindFreeCell(), HvpFindNextDirtyBlock(), HvpMapFileImageAndBuildMap(), HvpRecoverWholeHive(), and HvWriteHive().
VOID HvpCleanMap (PHHIVE Hive)
Definition at line 785 of file hivemap.c.
References _RTL_BITMAP::Buffer, _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, _HHIVE::Free, HBLOCK_SIZE, HSECTOR_SIZE, HTABLE_SLOTS, HvpFreeMap(), _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, ROUND_UP, _HHIVE::_DUAL::SmallDir, Stable, and _HHIVE::Storage.
Referenced by CmpInitializeHive(), HvLoadHive(), HvMapHive(), HvpBuildMap(), and HvpReadFileImageAndBuildMap().
VOID HvpDelistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, HSTORAGE_TYPE Type)
Definition at line 804 of file hivecell.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, FALSE, HvpComputeIndex, HvpGetHCell(), HvpRemoveFreeCellHint(), HvReleaseCell, Index, NULL, and _HCELL::Size.
Referenced by HvpEnlistFreeCell(), HvpFindFreeCellInBin(), and HvpIsFreeNeighbor().
BOOLEAN HvpDoWriteHive (PHHIVE Hive, ULONG FileType)
Definition at line 1857 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED_EXCLUSIVE, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, _HBASE_BLOCK::CheckSum, _HBASE_BLOCK::Cluster, CM_BUGCHECK, CmKdPrintEx, CML_IO, CmpDoFileSetSize(), CmpFileWriteThroughCache(), CmpFree(), Count, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FATAL_MAPPING_ERROR, FileEndOfFileInformation, FileOffset, CMP_OFFSET_ARRAY::FileOffset, _HBASE_BLOCK::Format, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBLOCK_SIZE, HCELL_NIL, HFILE_TYPE_LOG, HFILE_TYPE_PRIMARY, _LARGE_INTEGER::HighPart, HiveWritesThroughCache, HLOG_MINSIZE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_SIZE, HSYS_MAJOR, HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpGetCellMap(), HvpHeaderCheckSum(), _HBASE_BLOCK::Length, _LARGE_INTEGER::LowPart, _HBASE_BLOCK::Major, NT_SUCCESS, NtQueryInformationFile(), NULL, PagedPool, REGISTRY_ERROR, ROUND_UP, RtlCheckBit, RtlCopyMemory, RtlInitializeBitMap(), RtlNumberOfSetBits(), _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBASE_BLOCK::Signature, _RTL_BITMAP::SizeOfBitMap, Stable, Status, _IO_STATUS_BLOCK::Status, _HBIN::TimeStamp, _HBASE_BLOCK::TimeStamp, TRUE, _HBASE_BLOCK::Type, VALIDATE_CELL_MAP, and ZwFlushBuffersFile().
Referenced by HvInitializeHive(), and HvSyncHive().
VOID HvpDropAllPagedBins (IN PHHIVE Hive)
Definition at line 3048 of file hivesync.c.
References ASSERT, ASSERT_BIN_INPAGEDPOOL, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CmpFree(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, _HBIN::FileOffset, _FREE_HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HvpCheckViewBoundary(), HvpGetBinMemAlloc(), HvpGetCellMap(), NULL, PAGED_CODE, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, Stable, and VALIDATE_CELL_MAP.
Referenced by CmCompressKey().
VOID HvpDropPagedBins (PHHIVE Hive)
NTSTATUS HvpEnlistBinInMap (PHHIVE Hive, ULONG Length, PHBIN Bin, ULONG Offset, PVOID CmView OPTIONAL)
Definition at line 410 of file hivemap.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmDoSelfHeal, CmKdPrintEx, CML_BIN_MAP, CML_HIVE, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, FALSE, HBLOCK_SIZE, Hive, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HvCheckHiveDebug, HvpEnlistFreeCells(), HvpGetCellMap(), _HMAP_ENTRY::MemAlloc, NULL, _HHIVE::ReadOnly, _HBIN::Size, Status, STATUS_REGISTRY_CORRUPT, STATUS_REGISTRY_RECOVERED, STATUS_SUCCESS, and VALIDATE_CELL_MAP.
Referenced by HvCloneHive(), HvpBuildMap(), HvpMapFileImageAndBuildMap(), HvpReadFileImageAndBuildMap(), HvpRecoverData(), HvpRecoverWholeHive(), and HvShrinkHive().
VOID HvpEnlistFreeCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG Size, HSTORAGE_TYPE Type, BOOLEAN CoalesceForward)
Definition at line 556 of file hivecell.c.
References ASSERT, ASSERT_BIN_VALID, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_LISTENTRY, Bin, BIN_MAP_ALLOCATION_TYPE, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, FALSE, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _FREE_HBIN::Flags, _LIST_ENTRY::Flink, FREE_HBIN_DISCARDABLE, HBIN_BASE, HBIN_NIL, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HvMarkDirty(), HvpAddFreeCellHint(), HvpComputeIndex, HvpDelistFreeCell(), HvpGetBinMemAlloc(), HvpGetCellMap(), HvpGetHCell(), HvReleaseCell, Index, InsertHeadList(), _FREE_HBIN::ListEntry, NULL, _HCELL::Size, _HBIN::Size, _FREE_HBIN::Size, TRUE, _HCELL::u, USE_OLD_CELL, and VALIDATE_CELL_MAP.
Referenced by HvFreeCell(), HvpDoAllocateCell(), and HvpEnlistFreeCells().
BOOLEAN HvpEnlistFreeCells (PHHIVE Hive, PHBIN Bin, ULONG BinOffset)
Definition at line 658 of file hivemap.c.
References ASSERT, Bin, CmDoSelfHeal, CmMarkSelfHeal, FALSE, HCELL_PAD, HvpEnlistFreeCell(), RtlZeroMemory, _HCELL::Size, _HBIN::Size, Stable, and TRUE.
Referenced by HvpBuildMapAndCopy(), HvpEnlistBinInMap(), and HvRefreshHive().
HCELL_INDEX HvpFindFreeCell (PHHIVE Hive, ULONG Index, ULONG NewSize, HSTORAGE_TYPE Type, HCELL_INDEX Vicinity)
Definition at line 866 of file hivehint.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, _HHIVE::BaseBlock, _UNICODE_STRING::Buffer, Cell, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_FREECELL, CONTAINING_RECORD, DPFLTR_CONFIG_ID, FALSE, _HBASE_BLOCK::FileName, FileOffset, _CMHIVE::GrowOffset, _CMHIVE::GrowOnlyMode, HBLOCK_SIZE, HCELL_NIL, HCELL_TYPE_MASK, HvGetCellType, HvpCheckViewBoundary(), HvpFindFreeCellInThisViewWindow(), _UNICODE_STRING::Length, RtlInitUnicodeString(), TRUE, and Volatile.
Referenced by HvpDoAllocateCell().
VOID HvpFreeAllocatedBins (PHHIVE Hive)
Definition at line 39 of file hiveinit.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_DIRECTORY::Directory, _HHIVE::Free, HBIN_BASE, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HMAP_NEWALLOC, HTABLE_SLOTS, HvpGetBinMemAlloc(), _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, Stable, _HHIVE::Storage, and _HMAP_TABLE::Table.
Referenced by HvInitializeHive(), HvLoadHive(), HvMapHive(), and HvpRecoverWholeHive().
VOID HvpFreeHiveFreeDisplay (IN PHHIVE Hive)
Definition at line 115 of file hivehint.c.
References ASSERT, CM_PAGED_CODE, HHIVE_FREE_DISPLAY_SIZE, NULL, RtlInitializeBitMap(), Stable, and Volatile.
Referenced by CmpInitializeHive(), and HvFreeHive().
VOID HvpFreeMap (PHHIVE Hive, PHMAP_DIRECTORY Dir, ULONG Start, ULONG End)
Definition at line 850 of file hivemap.c.
References _HMAP_DIRECTORY::Directory, _HHIVE::Free, HDIRECTORY_SLOTS, and NULL.
Referenced by HvFreeHive(), HvFreeHivePartial(), HvpAddBin(), HvpBuildMapAndCopy(), HvpCleanMap(), HvpInitMap(), and HvShrinkHive().
ULONG HvpGetBinMemAlloc (IN PHHIVE Hive, PHBIN Bin, IN HSTORAGE_TYPE Type)
Definition at line 957 of file hivemap.c.
References ASSERT, Cell, _HBIN::FileOffset, HBIN_SIGNATURE, HBLOCK_SIZE, HCELL_TYPE_MASK, HvpGetCellMap(), _HMAP_ENTRY::MemAlloc, PAGED_CODE, _HBIN::Signature, _HBIN::Size, and VALIDATE_CELL_MAP.
Referenced by HvFreeHive(), HvFreeHivePartial(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistFreeCell(), and HvpFreeAllocatedBins().
struct _CELL_DATA* HvpGetCellFlat (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1370 of file hivecell.c.
References ASSERT, _HHIVE::BaseBlock, CmKdPrintEx, CML_FLOW, DPFLTR_CONFIG_ID, _HHIVE::Flat, HBLOCK_SIZE, HCELL_NIL, HHIVE_SIGNATURE, HvGetCellType, PERFINFO_HIVECELL_REFERENCE_FLAT, _HHIVE::Signature, Stable, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by HvInitializeHive().
PHMAP_ENTRY HvpGetCellMap (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 1434 of file hivecell.c.
References ASSERT, CmKdPrintEx, CML_FLOW, DPFLTR_CONFIG_ID, FALSE, _HHIVE::Flat, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HvGetCellType, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, _HHIVE::Signature, _HHIVE::Storage, and _HMAP_TABLE::Table.
Referenced by CmpMapCmView(), CmpUnmapCmView(), HvCheckHive(), HvCloneHive(), HvFreeCell(), HvFreeHive(), HvFreeHivePartial(), HvHiveWillShrink(), HvIsCellAllocated(), HvMarkCellDirty(), HvMarkDirty(), HvpAddBin(), HvpAddFreeCellHint(), HvpBuildMapAndCopy(), HvpCoalesceDiscardedBins(), HvpDelistBinFreeCells(), HvpDoAllocateCell(), HvpDoWriteHive(), HvpDropAllPagedBins(), HvpDropPagedBins(), HvpEnlistBinInMap(), HvpEnlistFreeCell(), HvpFindNextDirtyBlock(), HvpFlushMappedData(), HvpGetBinMemAlloc(), HvpMapFileImageAndBuildMap(), HvpRecoverData(), HvpRecoverWholeHive(), HvpRemoveFreeCellHint(), HvpScanForFreeCellInViewWindow(), HvpTruncateBins(), HvRefreshHive(), HvShiftCell(), HvShrinkHive(), and HvWriteHive().
struct _CELL_DATA* HvpGetCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 258 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CML_FLOW, CmLockHiveViews, CmLogCellDeRef, CmLogCellRef, CmpMapCmView(), CmpTouchView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HHIVE::Flat, HBIN_BASE, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_NIL, HCELL_OFFSET_MASK, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvGetCellType, HvShutdownComplete, _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, PAGE_SIZE, PERFINFO_HIVECELL_REFERENCE_PAGED, ROUND_UP, _HHIVE::Signature, _HCELL::Size, _HBIN::Size, Stable, _HHIVE::Storage, TRUE, _HCELL::u, USE_OLD_CELL, and _CM_VIEW_OF_FILE::UseCount.
Referenced by CmpSetupPrivateWrite(), and HvInitializeHive().
struct _CELL_DATA* HvpGetCellPaged (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 465 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmKdPrintEx, CML_FLOW, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FALSE, _HHIVE::Flat, HBIN_BASE, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_NIL, HCELL_OFFSET_MASK, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HvGetCellType, HvShutdownComplete, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, PERFINFO_HIVECELL_REFERENCE_PAGED, _HHIVE::Signature, Stable, _HHIVE::Storage, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by HvInitializeHive().
PHCELL HvpGetHCell (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 119 of file hivecell.c.
References CONTAINING_RECORD, HvGetCell, _HCELL::NewCell, NULL, _HCELL::OldCell, and USE_OLD_CELL.
Referenced by HvFreeCell(), HvIsCellAllocated(), HvMarkCellDirty(), HvpDelistFreeCell(), HvpDoAllocateCell(), and HvpEnlistFreeCell().
BOOLEAN HvpGrowLog1 (PHHIVE Hive, ULONG Count)
Definition at line 605 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, _HHIVE::Cluster, CmKdPrintEx, CML_IO, CmpDontGrowLogFile, CmpFlushOnLockRelease, CmRegistryLogSizeLimit, Count, DbgPrintEx(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _HHIVE::FileSetSize, HFILE_TYPE_LOG, HLOG_GROW, HSECTOR_SIZE, _HHIVE::Log, _HHIVE::LogSize, ONE_K, _HHIVE::ReadOnly, ROUND_UP, RtlNumberOfSetBits(), _RTL_BITMAP::SizeOfBitMap, and TRUE.
Referenced by HvMarkDirty().
BOOLEAN HvpGrowLog2 (PHHIVE Hive, ULONG Size)
Definition at line 1472 of file hivesync.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, _HHIVE::Cluster, CmKdPrintEx, CML_IO, CmpFlushOnLockRelease, CmRegistryLogSizeLimit, DbgPrintEx(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _HHIVE::FileSetSize, HFILE_TYPE_LOG, HLOG_GROW, HSECTOR_SIZE, _HHIVE::_DUAL::Length, _HHIVE::Log, _HHIVE::LogSize, ONE_K, _HHIVE::ReadOnly, ROUND_UP, RtlNumberOfSetBits(), _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, and TRUE.
Referenced by CmpOverwriteHive(), and HvpAddBin().
ULONG HvpHeaderCheckSum (PHBASE_BLOCK BaseBlock)
Definition at line 26 of file hivesum.c.
Referenced by HvInitializeHive(), HvpDoWriteHive(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpWriteLog(), and HvWriteHive().
NTSTATUS HvpInitMap (PHHIVE Hive)
Definition at line 273 of file hivemap.c.
References _HHIVE::Allocate, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, CmKdPrintEx, CML_HIVE, _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, _HHIVE::Free, HBLOCK_SIZE, HSECTOR_SIZE, HTABLE_SLOTS, HvpAllocateMap(), HvpFreeMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NULL, ROUND_UP, RtlInitializeBitMap(), RtlZeroMemory, _HHIVE::_DUAL::SmallDir, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_REGISTRY_CORRUPT, STATUS_SUCCESS, _HHIVE::Storage, and TRUE.
Referenced by HvpBuildMap(), HvpMapFileImageAndBuildMap(), and HvpReadFileImageAndBuildMap().
VOID HvpReleaseCellMapped (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 160 of file hivecell.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_OR_HIVE_LOADING, _HMAP_ENTRY::BinAddress, CmKdPrintEx, CML_FLOW, CmLockHiveViews, CmLogCellDeRef, CmUnlockHiveViews, _HMAP_ENTRY::CmView, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, FALSE, _HHIVE::Flat, HBIN_BASE, HCELL_BLOCK_MASK, HCELL_BLOCK_SHIFT, HCELL_NIL, HCELL_OFFSET_MASK, HCELL_PAD, HCELL_TABLE_MASK, HCELL_TABLE_SHIFT, HCELL_TYPE_MASK, HHIVE_SIGNATURE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HvGetCellType, HvShutdownComplete, _HHIVE::_DUAL::Length, NULL, _HHIVE::Signature, Stable, _HHIVE::Storage, TRUE, _CM_VIEW_OF_FILE::UseCount, and _CM_VIEW_OF_FILE::ViewAddress.
Referenced by CmpSetupPrivateWrite(), and HvInitializeHive().
VOID HvpRemoveFreeCellHint (PHHIVE Hive, HCELL_INDEX Cell, ULONG Index, HSTORAGE_TYPE Type)
Definition at line 308 of file hivehint.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, Bin, _HMAP_ENTRY::BinAddress, CM_PAGED_CODE, CmKdPrintEx, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBIN::FileOffset, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HvpComputeIndex, HvpGetCellMap(), Index, RtlClearBits(), RtlNumberOfSetBits(), _HCELL::Size, _HBIN::Size, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvpDelistFreeCell().
BOOLEAN HvpWriteLog (PHHIVE Hive)
Definition at line 2260 of file hivesync.c.
References ASSERT, _HHIVE::BaseBlock, _RTL_BITMAP::Buffer, _HBASE_BLOCK::CheckSum, _HBASE_BLOCK::Cluster, _HHIVE::Cluster, CmKdPrintEx, CML_IO, CmpDoFileSetSize(), CmpStashBuffer, CmpStashBufferSize, Count, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, ExAllocatePool, ExAllocatePoolWithTag, ExFreePool(), FALSE, _HHIVE::FileFlush, CMP_OFFSET_ARRAY::FileOffset, _HHIVE::FileWrite, _HBASE_BLOCK::Format, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HFILE_TYPE_LOG, Hive, HLOG_DV_SIGNATURE, HLOG_GROW, HLOG_HEADER_SIZE, HSECTOR_SIZE, HSYS_MAJOR, HvpFindNextDirtyBlock(), HvpHeaderCheckSum(), KeQuerySystemTime(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, LOCK_STASH_BUFFER, _HHIVE::LogSize, _HBASE_BLOCK::Major, NOTHING, NT_SUCCESS, NULL, PAGE_SIZE, PagedPool, _HHIVE::ReadOnly, ROUND_UP, RtlCopyMemory, RtlNumberOfSetBits(), _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBASE_BLOCK::Signature, _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, _HBASE_BLOCK::TimeStamp, TRUE, _HBASE_BLOCK::Type, and UNLOCK_STASH_BUFFER.
Referenced by CmpOverwriteHive(), and HvSyncHive().
NTSTATUS HvReadInMemoryHive (PHHIVE Hive, PVOID * HiveImage)
HCELL_INDEX HvReallocateCell (PHHIVE Hive, HCELL_INDEX Cell, ULONG NewSize)
Definition at line 1825 of file hivecell.c.
References ASSERT, Cell, CmKdPrintEx, CML_HIVE, CmpLockHiveWriter, CmpUnlockHiveWriter, DHvCheckHive, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, HCELL_NIL, HCELL_PAD, HHIVE_SIGNATURE, HSANE_CELL_MAX, HvFreeCell(), HvGetCell, HvGetCellSize(), HvGetCellType, HvIsCellAllocated(), HvpAdjustCellSize, HvpDoAllocateCell(), HvReleaseCell, NULL, _HHIVE::ReadOnly, ROUND_UP, RtlMoveMemory, _HHIVE::Signature, _CELL_DATA::u, and USE_OLD_CELL.
Referenced by CmpAddToLeaf(), CmpAddValueToList(), CmpRemoveValueFromList(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueKeyExisting(), CmpSplitLeaf(), and CmRestoreKey().
VOID HvRefreshHive (PHHIVE Hive)
Definition at line 685 of file hivesync.c.
References _256K, ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CcPurgeCacheSection(), CM_BUGCHECK, CM_CHECK_REGISTRY_FORCE_CLEAN, CM_VIEW_SIZE, CmCheckRegistry(), CmpFreeCmView(), CmpMapCmView(), CmpRebuildSecurityCache(), CmpStashBuffer, CmpStashBufferSize, CmpTouchView(), CmpUnmapCmView(), CmpUnmapCmViewSurroundingOffset(), CONTAINING_RECORD, _HHIVE::DirtyCount, _HHIVE::DirtyVector, _FREE_DISPLAY::Display, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CMHIVE::FileObject, FileOffset, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _CM_VIEW_OF_FILE::FileOffset, _HHIVE::FileRead, _HHIVE::FileSetSize, _CM_KEY_NODE::Flags, _FREE_HBIN::Flags, _LIST_ENTRY::Flink, _HHIVE::Free, FREE_HBIN_DISCARDABLE, _HHIVE::_DUAL::FreeDisplay, _HHIVE::_DUAL::FreeSummary, HBIN_BASE, HBIN_FLAGS, HBIN_SIGNATURE, HBLOCK_SIZE, HFILE_TYPE_PRIMARY, HHIVE_FREE_DISPLAY_SIZE, _LARGE_INTEGER::HighPart, HIVE_NOLAZYFLUSH, _HHIVE::HiveFlags, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HSECTOR_SIZE, HvCheckHive(), HvFreeHivePartial(), HvGetCell, HvpAdjustHiveFreeDisplay(), HvpEnlistFreeCells(), HvpFindNextDirtyBlock(), HvpGetCellMap(), HvReleaseCell, InitializeListHead(), InsertTailList(), IsListEmpty, KEY_HIVE_ENTRY, KEY_NO_DELETE, _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, LOCK_STASH_BUFFER, _LARGE_INTEGER::LowPart, _CM_VIEW_OF_FILE::LRUViewList, _HMAP_ENTRY::MemAlloc, NT_SUCCESS, NULL, PAGE_SIZE, PagedPool, _CM_KEY_NODE::Parent, _CMHIVE::PinnedViews, _CM_VIEW_OF_FILE::PinViewList, _CMHIVE::PinViewListHead, REFRESH_HIVE, _HHIVE::RefreshCount, REGISTRY_ERROR, RemoveEntryList(), RemoveHeadList(), _HBASE_BLOCK::RootCell, ROUND_UP, RtlCheckBit, RtlClearBits(), RtlCopyMemory, RtlNumberOfSetBits(), _FILE_OBJECT::SectionObjectPointer, _HBIN::Signature, _HBIN::Size, _FREE_HBIN::Size, _CM_VIEW_OF_FILE::Size, _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, TRUE, UNLOCK_STASH_BUFFER, _CM_VIEW_OF_FILE::UseCount, VALIDATE_CELL_MAP, and Volatile.
Referenced by CmpRefreshHive().
VOID HvReleaseFreeCellRefArray (PHV_TRACK_CELL_REF CellRef)
Definition at line 2274 of file hivecell.c.
References ASSERT, _HV_HIVE_CELL_PAIR::Cell, _HV_TRACK_CELL_REF::CellArray, CM_PAGED_CODE, _HV_TRACK_CELL_REF::Count, ExFreePool(), _HV_HIVE_CELL_PAIR::Hive, HvReleaseCell, _HV_TRACK_CELL_REF::Max, NULL, STATIC_CELL_PAIR_COUNT, _HV_TRACK_CELL_REF::StaticArray, and _HV_TRACK_CELL_REF::StaticCount.
Referenced by CmEnumerateKey(), CmpDoCreate(), CmpDuplicateIndex(), CmpInsertSecurityCellList(), CmpMarkKeyValuesDirty(), CmpMergeKeyValues(), CmpSelectLeaf(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmQueryKey(), and CmSaveMergedKeys().
HCELL_INDEX HvShiftCell (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2168 of file hivecell.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, HBIN_BASE, HBIN_SIGNATURE, HMAP_INPAGEDPOOL, HvGetCellType, HvpGetCellMap(), _HBIN::Signature, _HBIN::Spare, and Stable.
Referenced by CmpShiftAllCells(), CmpShiftAllCells2(), CmpShiftHiveFreeBins(), CmpShiftIndex(), CmpShiftKey(), CmpShiftSecurityCells(), and CmpShiftValueList().
NTSTATUS HvShrinkHive (PHHIVE Hive, ULONG NewLength)
Definition at line 2469 of file hiveload.c.
References ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HBIN::FileOffset, HBIN_BASE, HBIN_SIGNATURE, HBLOCK_SIZE, HMAP_INPAGEDPOOL, HTABLE_SLOTS, HvpAdjustHiveFreeDisplay(), HvpEnlistBinInMap(), HvpFreeMap(), HvpGetCellMap(), _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HHIVE::_DUAL::Map, NT_SUCCESS, NULL, PAGED_CODE, _HBIN::Signature, _HBIN::Size, _HBIN::Spare, Stable, Status, and _HHIVE::Storage.
Referenced by CmpShiftHiveFreeBins().
BOOLEAN HvSyncHive (PHHIVE Hive)
Definition at line 1558 of file hivesync.c.
References ASSERT, CM_NUMBER_OF_MACHINE_HIVES, _HIVE_LIST_ENTRY::CmHive, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmpLogError(), CmpMiniNTBoot, DBG, _HHIVE::DirtyCount, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, HFILE_TYPE_PRIMARY, HHIVE_SIGNATURE, HIVE_VOLATILE, _HHIVE::HiveFlags, HvpDoWriteHive(), HvpDropPagedBins(), HvpTruncateBins(), HvpWriteLog(), HvShutdownComplete, Index, IoSetThreadHardErrorMode(), _HHIVE::Log, NULL, _HHIVE::ReadOnly, RtlClearAllBits(), _HHIVE::Signature, STATUS_REGISTRY_IO_FAILED, and TRUE.
Referenced by CmFlushKey(), CmLoadKey(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpInitializeHiveList(), CmpLoadHiveThread(), and CmpShiftHiveFreeBins().
BOOLEAN HvTrackCellRef (PHV_TRACK_CELL_REF CellRef, PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 2187 of file hivecell.c.
References ASSERT, Cell, _HV_HIVE_CELL_PAIR::Cell, _HV_TRACK_CELL_REF::CellArray, CM_PAGED_CODE, _HV_TRACK_CELL_REF::Count, ExAllocatePool, ExFreePool(), FALSE, HCELL_NIL, Hive, _HV_HIVE_CELL_PAIR::Hive, HvReleaseCell, _HV_TRACK_CELL_REF::Max, NULL, PagedPool, RtlCopyMemory, STATIC_CELL_PAIR_COUNT, _HV_TRACK_CELL_REF::StaticArray, _HV_TRACK_CELL_REF::StaticCount, and TRUE.
Referenced by CmEnumerateKey(), CmpDoCreate(), CmpDuplicateIndex(), CmpInsertSecurityCellList(), CmpMarkKeyValuesDirty(), CmpMergeKeyValues(), CmpSelectLeaf(), CmpSetSecurityDescriptorInfo(), CmpSetValueDataExisting(), CmpSetValueDataNew(), CmpSplitLeaf(), CmpSyncKeyValues(), CmQueryKey(), and CmSaveMergedKeys().
NTSTATUS HvWriteHive (PHHIVE Hive, BOOLEAN DontGrow, BOOLEAN WriteThroughCache, BOOLEAN CrashSafe)
Definition at line 3170 of file hivesync.c.
References ASSERT, _HHIVE::BaseBlock, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _HBASE_BLOCK::CheckSum, _HHIVE::Cluster, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmLockHiveViews, CmpDereferenceHiveView(), CmpDereferenceHiveViewWithLock(), CmpDoFileSetSize(), CmpFileWriteThroughCache(), CmpMapThisBin(), CmpReferenceHiveView(), CmUnlockHiveViews, _HMAP_ENTRY::CmView, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DPFLTR_CONFIG_ID, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _HHIVE::FileFlush, _HBIN::FileOffset, CMP_OFFSET_ARRAY::FileOffset, _HHIVE::FileWrite, _FREE_HBIN::Flags, _HBASE_BLOCK::Format, FREE_HBIN_DISCARDABLE, HBASE_BLOCK_SIGNATURE, HBASE_FORMAT_MEMORY, HBIN_BASE, HBIN_NIL, HBIN_SIGNATURE, HBLOCK_SIZE, HCELL_NIL, HFILE_TYPE_EXTERNAL, HHIVE_SIGNATURE, Hive, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HSECTOR_SIZE, HSYS_MAJOR, HvpCheckViewBoundary(), HvpGetCellMap(), HvpHeaderCheckSum(), HvShutdownComplete, _HBASE_BLOCK::Length, _HHIVE::_DUAL::Length, _HBASE_BLOCK::Major, NT_SUCCESS, NULL, PagedPool, _HHIVE::ReadOnly, _HBASE_BLOCK::RootCell, ROUND_UP, RtlZeroMemory, _HBASE_BLOCK::Sequence1, _HBASE_BLOCK::Sequence2, _HBIN::Signature, _HBASE_BLOCK::Signature, _HHIVE::Signature, _HCELL::Size, _HBIN::Size, _FREE_HBIN::Size, Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_REGISTRY_IO_FAILED, STATUS_SUCCESS, _HHIVE::Storage, TRUE, _HCELL::u, and USE_OLD_CELL.
Referenced by CmDumpKey(), CmpOverwriteHive(), CmSaveKey(), and CmSaveMergedKeys().