Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/rundown.c File Reference
rundown.c File Reference
#include "exp.h"
Data Structures
struct _EX_RUNDOWN_WAIT_BLOCK
Macros
#define EXP_ALIGN_UP_PTR_ON_BOUNDARY(_length, _alignment)
#define EXP_IS_ALIGNED_ON_BOUNDARY(_pointer, _alignment) ((((ULONG_PTR) (_pointer)) & ((_alignment) - 1)) == 0)
Typedefs
typedef struct _EX_RUNDOWN_WAIT_BLOCK EX_RUNDOWN_WAIT_BLOCK
typedef struct _EX_RUNDOWN_WAIT_BLOCK * PEX_RUNDOWN_WAIT_BLOCK
Functions
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in ULONG Count)
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
NTKERNELAPI PEX_RUNDOWN_REF_CACHE_AWARE ExAllocateCacheAwareRundownProtection (__in POOL_TYPE PoolType, __in ULONG PoolTag)
NTKERNELAPI BOOLEAN FASTCALL ExfAcquireRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExfInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID ExFreeCacheAwareRundownProtection (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI VOID FASTCALL ExfReInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExfReleaseRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExfRundownCompleted (__out PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID FASTCALL ExfWaitForRundownProtectionRelease (__inout PEX_RUNDOWN_REF RunRef)
NTKERNELAPI VOID ExInitializeRundownProtectionCacheAware (__out PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in SIZE_T RunRefSize)
PEX_RUNDOWN_REF FORCEINLINE EXP_GET_CURRENT_RUNDOWN_REF (IN PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
PEX_RUNDOWN_REF FORCEINLINE EXP_GET_PROCESSOR_RUNDOWN_REF (IN PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, IN ULONG Index)
NTKERNELAPI VOID FASTCALL ExReInitializeRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in ULONG Count)
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
NTKERNELAPI VOID FASTCALL ExRundownCompletedCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
NTKERNELAPI SIZE_T ExSizeOfRundownProtectionCacheAware (VOID)
NTKERNELAPI VOID FASTCALL ExWaitForRundownProtectionReleaseCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Macro Definition Documentation
#define EXP_ALIGN_UP_PTR_ON_BOUNDARY (_length, _alignment)
Value:
(PVOID) ((((ULONG_PTR) (_length)) + ((_alignment)-1)) &              \
                              ~(ULONG_PTR)((_alignment) - 1))
Definition at line 76 of file rundown.c.
Referenced by ExAllocateCacheAwareRundownProtection(), and ExInitializeRundownProtectionCacheAware().
#define EXP_IS_ALIGNED_ON_BOUNDARY (_pointer, _alignment) ((((ULONG_PTR) (_pointer)) & ((_alignment) - 1)) == 0)
Definition at line 84 of file rundown.c.
Referenced by ExAllocateCacheAwareRundownProtection().
Typedef Documentation
typedef struct _EX_RUNDOWN_WAIT_BLOCK EX_RUNDOWN_WAIT_BLOCK
typedef struct _EX_RUNDOWN_WAIT_BLOCK * PEX_RUNDOWN_WAIT_BLOCK
Function Documentation
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 879 of file rundown.c.
References ExAcquireRundownProtection(), and EXP_GET_CURRENT_RUNDOWN_REF().
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in ULONG Count)
Definition at line 931 of file rundown.c.
References ExAcquireRundownProtectionEx(), and EXP_GET_CURRENT_RUNDOWN_REF().
NTKERNELAPI BOOLEAN FASTCALL ExAcquireRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
Definition at line 231 of file rundown.c.
References Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, InterlockedCompareExchangePointer, and TRUE.
Referenced by ExAcquireRundownProtectionCacheAwareEx(), ExCompareExchangeCallBack(), and ExReferenceCallBackBlock().
NTKERNELAPI PEX_RUNDOWN_REF_CACHE_AWARE ExAllocateCacheAwareRundownProtection (__in POOL_TYPE PoolType, __in ULONG PoolTag)
Definition at line 600 of file rundown.c.
References ASSERT, ExAllocatePoolWithTag, ExFreePool(), ExInitializeRundownProtection(), EXP_ALIGN_UP_PTR_ON_BOUNDARY, EXP_GET_PROCESSOR_RUNDOWN_REF(), EXP_IS_ALIGNED_ON_BOUNDARY, Index, KeGetRecommendedSharedDataAlignment(), KeNumberProcessors, NULL, _EX_RUNDOWN_REF_CACHE_AWARE::Number, PAGED_CODE, _EX_RUNDOWN_REF_CACHE_AWARE::PoolToFree, _EX_RUNDOWN_REF_CACHE_AWARE::RunRefs, and _EX_RUNDOWN_REF_CACHE_AWARE::RunRefSize.
NTKERNELAPI BOOLEAN FASTCALL ExfAcquireRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 178 of file rundown.c.
References EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, InterlockedCompareExchangePointer, and TRUE.
Referenced by ExAcquireRundownProtection().
NTKERNELAPI VOID FASTCALL ExfInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
Definition at line 99 of file rundown.c.
NTKERNELAPI VOID ExFreeCacheAwareRundownProtection (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 848 of file rundown.c.
References ASSERT, ExFreePool(), PAGED_CODE, and UintToPtr.
NTKERNELAPI VOID FASTCALL ExfReInitializeRundownProtection (__out PEX_RUNDOWN_REF RunRef)
Definition at line 124 of file rundown.c.
References ASSERT, EX_RUNDOWN_ACTIVE, InterlockedExchangePointer, NULL, and PAGED_CODE.
NTKERNELAPI VOID FASTCALL ExfReleaseRundownProtection (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 287 of file rundown.c.
References ASSERT, _EX_RUNDOWN_WAIT_BLOCK::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, FASTCALL, InterlockedCompareExchangePointer, InterlockedDecrement, KeNumberProcessors, KeSetEvent(), NTKERNELAPI, TRUE, VOID, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
Referenced by ExReleaseRundownProtection().
NTKERNELAPI VOID FASTCALL ExfRundownCompleted (__out PEX_RUNDOWN_REF RunRef)
Definition at line 152 of file rundown.c.
References ASSERT, EX_RUNDOWN_ACTIVE, InterlockedExchangePointer, and PAGED_CODE.
NTKERNELAPI VOID FASTCALL ExfWaitForRundownProtectionRelease (__inout PEX_RUNDOWN_REF RunRef)
Definition at line 457 of file rundown.c.
References ASSERT, _EX_RUNDOWN_WAIT_BLOCK::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_SHIFT, Executive, FALSE, InterlockedCompareExchangePointer, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NULL, PAGED_CODE, SynchronizationEvent, TRUE, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
Referenced by ExWaitForRundownProtectionRelease().
NTKERNELAPI VOID ExInitializeRundownProtectionCacheAware (__out PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in SIZE_T RunRefSize)
Definition at line 771 of file rundown.c.
References ExInitializeRundownProtection(), EXP_ALIGN_UP_PTR_ON_BOUNDARY, EXP_GET_PROCESSOR_RUNDOWN_REF(), Index, KeGetRecommendedSharedDataAlignment(), PAGED_CODE, and UintToPtr.
PEX_RUNDOWN_REF FORCEINLINE EXP_GET_CURRENT_RUNDOWN_REF (IN PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 549 of file rundown.c.
References KeGetCurrentProcessorNumber().
Referenced by ExAcquireRundownProtectionCacheAware(), ExAcquireRundownProtectionCacheAwareEx(), ExReleaseRundownProtectionCacheAware(), and ExReleaseRundownProtectionCacheAwareEx().
PEX_RUNDOWN_REF FORCEINLINE EXP_GET_PROCESSOR_RUNDOWN_REF (IN PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, IN ULONG Index)
Definition at line 574 of file rundown.c.
Referenced by ExAllocateCacheAwareRundownProtection(), ExInitializeRundownProtectionCacheAware(), ExReInitializeRundownProtectionCacheAware(), ExRundownCompletedCacheAware(), and ExWaitForRundownProtectionReleaseCacheAware().
NTKERNELAPI VOID FASTCALL ExReInitializeRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 1114 of file rundown.c.
References ASSERT, _EX_RUNDOWN_REF::Count, EX_RUNDOWN_ACTIVE, EXP_GET_PROCESSOR_RUNDOWN_REF(), Index, InterlockedExchangePointer, NULL, and _EX_RUNDOWN_REF::Ptr.
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 905 of file rundown.c.
References EXP_GET_CURRENT_RUNDOWN_REF(), and ExReleaseRundownProtection().
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionCacheAwareEx (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware, __in ULONG Count)
Definition at line 959 of file rundown.c.
References EXP_GET_CURRENT_RUNDOWN_REF(), and ExReleaseRundownProtectionEx().
NTKERNELAPI VOID FASTCALL ExReleaseRundownProtectionEx (__inout PEX_RUNDOWN_REF RunRef, __in ULONG Count)
Definition at line 369 of file rundown.c.
References ASSERT, Count, _EX_RUNDOWN_WAIT_BLOCK::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_INC, FALSE, FASTCALL, InterlockedCompareExchangePointer, InterlockedExchangeAdd(), KeNumberProcessors, KeSetEvent(), NTKERNELAPI, TRUE, VOID, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.
Referenced by ExCompareExchangeCallBack(), ExReferenceCallBackBlock(), and ExReleaseRundownProtectionCacheAwareEx().
NTKERNELAPI VOID FASTCALL ExRundownCompletedCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 1147 of file rundown.c.
References ASSERT, _EX_RUNDOWN_REF::Count, EX_RUNDOWN_ACTIVE, EXP_GET_PROCESSOR_RUNDOWN_REF(), Index, InterlockedExchangePointer, and _EX_RUNDOWN_REF::Ptr.
NTKERNELAPI SIZE_T ExSizeOfRundownProtectionCacheAware (VOID)
Definition at line 719 of file rundown.c.
References KeGetRecommendedSharedDataAlignment(), KeNumberProcessors, and PAGED_CODE.
NTKERNELAPI VOID FASTCALL ExWaitForRundownProtectionReleaseCacheAware (__inout PEX_RUNDOWN_REF_CACHE_AWARE RunRefCacheAware)
Definition at line 987 of file rundown.c.
References ASSERT, _EX_RUNDOWN_WAIT_BLOCK::Count, _EX_RUNDOWN_REF::Count, EX_RUNDOWN_ACTIVE, EX_RUNDOWN_COUNT_SHIFT, Executive, EXP_GET_PROCESSOR_RUNDOWN_REF(), FALSE, FASTCALL, Index, InterlockedCompareExchangePointer, InterlockedExchangeAdd(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NTKERNELAPI, NULL, _EX_RUNDOWN_REF::Ptr, SynchronizationEvent, TRUE, VOID, and _EX_RUNDOWN_WAIT_BLOCK::WakeEvent.