Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obp.h File Reference
obp.h File Reference
#include "ntos.h"
#include "seopaque.h"
#include <zwapi.h>
Data Structures
struct _OBP_LOOKUP_CONTEXT
struct _OBP_SWEEP_CONTEXT
struct _SECURITY_DESCRIPTOR_HEADER
union ALIGNEDNAME
Macros
#define DecodeKernelHandle(H) (HANDLE)(KERNEL_HANDLE_MASK ^ (ULONG_PTR)(H))
#define EncodeKernelHandle(H) (HANDLE)(KERNEL_HANDLE_MASK | (ULONG_PTR)(H))
#define IsKernelHandle(H, M)
#define KERNEL_HANDLE_MASK ((ULONG_PTR)((LONG)0x80000000))
#define LINK_TO_SD_HEADER(_link) CONTAINING_RECORD((_link), SECURITY_DESCRIPTOR_HEADER, Link)
#define LOCK_HASH_MASK (OBJECT_LOCK_COUNT - 1)
#define OB_NAMESPACE_POOL_TYPE PagedPool
#define OBJ_AUDIT_OBJECT_CLOSE 0x00000004L
#define OBJ_HANDLE_ATTRIBUTES (OBJ_PROTECT_CLOSE | OBJ_INHERIT | OBJ_AUDIT_OBJECT_CLOSE)
#define OBJECT_NAME_BUFFER_SIZE 248
#define OBP_DECLARE_OLDIRQL
#define OBP_LOCK_OWNEDEXCLUSIVE_SIGNATURE 0xCCCC1234
#define OBP_LOCK_OWNEDSHARED_SIGNATURE 0xDDDD1234
#define OBP_LOCK_RELEASED_SIGNATURE 0xEEEE1234
#define OBP_LOCK_UNUSED_SIGNATURE 0xFFFF1234
#define OBP_LOCK_WAITEXCLUSIVE_SIGNATURE 0xAAAA1234
#define OBP_LOCK_WAITSHARED_SIGNATURE 0xBBBB1234
#define OBP_MAX_DEFINED_OBJECT_TYPES 48
#define OBP_NAME_KERNEL_PROTECTED ((LONG)0x40000000)
#define OBP_NAME_LOCKED ((LONG)0x80000000)
#define OBP_PAGEDPOOL_NAMESPACE
#define ObpAllocateObjectCreateInfoBuffer() (POBJECT_CREATE_INFORMATION)ExAllocateFromPPLookasideList(LookasideCreateInfoList)
#define ObpBeginTypeSpecificCallOut(IRQL)
#define ObpCentralizedSecurity(_ObjectType) ((_ObjectType)->TypeInfo.SecurityProcedure == SeDefaultObjectMethod)
#define ObpDecodeGrantedAccess(Access) ((Access) & ~ObpAccessProtectCloseBit)
#define ObpDecrHandleCount(np) (ObpInterlockedDecrement(&np->HandleCount) == 0)
#define ObpDecrPointerCount(np) ObpInterlockedDecrement(&np->PointerCount)
#define ObpDecrPointerCountEx(np, Count) (ObpInterlockedExchangeAdd (&np->PointerCount, -(LONG_PTR)(Count)) - Count)
#define ObpDecrPointerCountWithResult(np) (ObpInterlockedDecrement(&np->PointerCount) == 0)
#define ObpEncodeProtectClose(ObjectTableEntry)
#define ObpEndTypeSpecificCallOut(IRQL, str, ot, o)
#define ObpEnterObjectTypeMutex(_ObjectType)
#define ObpFreeObjectCreateInfoBuffer(ObjectCreateInfo) ExFreeToPPLookasideList(LookasideCreateInfoList, ObjectCreateInfo)
#define ObpFreeObjectCreateInformation(_ObjectCreateInfo)
#define ObpGetHandleAttributes(HandleTableEntry)
#define ObpGetObjectTable() (PsGetCurrentProcess()->ObjectTable)
#define ObpHashObjectHeader(_ObjectHeader) ((((ULONG_PTR)(_ObjectHeader)) >> 8) & LOCK_HASH_MASK)
#define ObpIncrHandleCount(np) ObpInterlockedIncrement(&np->HandleCount)
#define ObpIncrPointerCount(np) ObpInterlockedIncrement(&np->PointerCount)
#define ObpIncrPointerCountEx(np, Count) (ObpInterlockedExchangeAdd (&np->PointerCount, Count) + Count)
#define ObpInterlockedCompareExchange InterlockedCompareExchange
#define ObpInterlockedDecrement InterlockedDecrement
#define ObpInterlockedExchangeAdd InterlockedExchangeAdd
#define ObpInterlockedIncrement InterlockedIncrement
#define ObpIsOverflow(A, B) ((A) > ((A) + (B)))
#define ObpLeaveObjectTypeMutex(_ObjectType)
#define ObpLockDeviceMap() KeAcquireGuardedMutex(&ObpDeviceMapLock)
#define ObpLockObject(_ObjectHeader)
#define ObpLockObjectShared(_ObjectHeader)
#define ObpPushStackInfo(np, inc)
#define ObpReleaseObjectCreateInformation(_ObjectCreateInfo)
#define ObpUnlockDeviceMap() KeReleaseGuardedMutex(&ObpDeviceMapLock)
#define ObpUnlockObject(_ObjectHeader)
#define ObpValidateIrql(str)
#define SD_TO_SD_HEADER(_sd) CONTAINING_RECORD((_sd), SECURITY_DESCRIPTOR_HEADER, SecurityDescriptor)
#define SECURITY_DESCRIPTOR_CACHE_ENTRIES 257
Typedefs
typedef struct _OBP_LOOKUP_CONTEXT OBP_LOOKUP_CONTEXT
typedef struct _OBP_SWEEP_CONTEXT OBP_SWEEP_CONTEXT
typedef struct _OBP_LOOKUP_CONTEXT * POBP_LOOKUP_CONTEXT
typedef struct _OBP_SWEEP_CONTEXT * POBP_SWEEP_CONTEXT
typedef struct _SECURITY_DESCRIPTOR_HEADER * PSECURITY_DESCRIPTOR_HEADER
typedef struct _SECURITY_DESCRIPTOR_HEADER SECURITY_DESCRIPTOR_HEADER
Functions
VOID FASTCALL ObfDereferenceDeviceMap (IN PDEVICE_MAP DeviceMap)
NTSTATUS ObpAllocateObject (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN KPROCESSOR_MODE OwnershipMode, IN POBJECT_TYPE ObjectType, IN PUNICODE_STRING ObjectName, IN ULONG ObjectBodySize, OUT POBJECT_HEADER *ReturnedObjectHeader)
PWCHAR ObpAllocateObjectNameBuffer (IN ULONG Length, IN LOGICAL UseLookaside, IN OUT PUNICODE_STRING ObjectName)
VOID ObpAuditObjectAccess (IN HANDLE Handle, IN PHANDLE_TABLE_ENTRY_INFO ObjectTableEntryInfo, IN PUNICODE_STRING ObjectTypeName, IN ACCESS_MASK DesiredAccess)
NTSTATUS ObpCaptureObjectCreateInformation (IN POBJECT_TYPE ObjectType OPTIONAL, IN KPROCESSOR_MODE ProbeMode, IN KPROCESSOR_MODE CreatorMode, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PUNICODE_STRING CapturedObjectName, IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN LOGICAL UseLookaside)
NTSTATUS ObpCaptureObjectName (IN KPROCESSOR_MODE ProbeMode, IN PUNICODE_STRING ObjectName, IN OUT PUNICODE_STRING CapturedObjectName, IN LOGICAL UseLookaside)
NTSTATUS ObpChargeQuotaForObject (IN POBJECT_HEADER ObjectHeader, IN POBJECT_TYPE ObjectType, OUT PBOOLEAN NewObject)
BOOLEAN ObpCheckObjectReference (IN PVOID Object, IN OUT PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE AccessMode, OUT PNTSTATUS AccessStatus)
BOOLEAN ObpCheckPseudoHandleAccess (IN PVOID Object, IN ACCESS_MASK DesiredAccess, OUT PNTSTATUS AccessStatus, IN BOOLEAN TypeMutexLocked)
BOOLEAN ObpCheckTraverseAccess (IN PVOID DirectoryObject, IN ACCESS_MASK TraverseAccess, IN PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE PreviousMode, OUT PNTSTATUS AccessStatus)
NTSTATUS ObpCloseHandle (IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS ObpCloseHandleTableEntry (IN PHANDLE_TABLE ObjectTable, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN Rundown)
BOOLEAN ObpCompareSecurityDescriptors (IN PSECURITY_DESCRIPTOR SD1, ULONG Length, IN PSECURITY_DESCRIPTOR SD2)
PSECURITY_DESCRIPTOR_HEADER ObpCreateCacheEntry (PSECURITY_DESCRIPTOR InputSecurityDescriptor, ULONG Length, ULONG FullHash, ULONG RefBias)
NTSTATUS ObpCreateHandle (IN OB_OPEN_REASON OpenReason, IN PVOID Object, IN POBJECT_TYPE ExpectedObjectType OPTIONAL, IN PACCESS_STATE AccessState, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN POBP_LOOKUP_CONTEXT LookupContext, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
VOID ObpCreateSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
NTSTATUS ObpCreateUnnamedHandle (IN PVOID Object, IN ACCESS_MASK DesiredAccess, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
VOID ObpDecrementHandleCount (PEPROCESS Process, POBJECT_HEADER ObjectHeader, POBJECT_TYPE ObjectType, ACCESS_MASK GrantedAccess)
BOOLEAN ObpDeleteDirectoryEntry (IN POBP_LOOKUP_CONTEXT LookupContext)
VOID ObpDeleteNameCheck (IN PVOID Object)
VOID ObpDeleteObjectType (IN PVOID Object)
VOID ObpDeleteSymbolicLink (IN PVOID Object)
VOID ObpDeleteSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
VOID FORCEINLINE ObpDereferenceNameInfo (IN POBJECT_HEADER_NAME_INFO NameInfo)
PVOID ObpDestroySecurityDescriptorHeader (IN PSECURITY_DESCRIPTOR_HEADER Header)
VOID FASTCALL ObpFreeObject (IN PVOID Object)
VOID FASTCALL ObpFreeObjectNameBuffer (IN PUNICODE_STRING ObjectName)
ULONG ObpHashBuffer (PVOID Data, ULONG Length)
ULONG ObpHashSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Length)
NTSTATUS ObpIncrementHandleCount (OB_OPEN_REASON OpenReason, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, PACCESS_STATE AccessState OPTIONAL, KPROCESSOR_MODE AccessMode, ULONG Attributes)
NTSTATUS ObpIncrementUnnamedHandleCount (PACCESS_MASK DesiredAccess, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, KPROCESSOR_MODE AccessMode, ULONG Attributes)
VOID FORCEINLINE ObpInitializeLookupContext (IN POBP_LOOKUP_CONTEXT LookupContext)
NTSTATUS ObpInitSecurityDescriptorCache (VOID)
BOOLEAN ObpInsertDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LookupContext, IN POBJECT_HEADER ObjectHeader)
POBJECT_HANDLE_COUNT_ENTRY ObpInsertHandleCount (POBJECT_HEADER ObjectHeader)
FORCEINLINE LOGICAL ObpIsKernelExclusiveObject (IN POBJECT_HEADER ObjectHeader)
VOID FORCEINLINE ObpLockAllObjects (IN POBJECT_TYPE ObjectType)
VOID FORCEINLINE ObpLockDirectoryExclusive (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LockContext)
VOID FORCEINLINE ObpLockDirectoryShared (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LockContext)
VOID FORCEINLINE ObpLockLookupContext (IN POBP_LOOKUP_CONTEXT LookupContext, IN POBJECT_DIRECTORY Directory)
PVOID ObpLookupDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN PUNICODE_STRING Name, IN ULONG Attributes, IN BOOLEAN SearchShadow, OUT POBP_LOOKUP_CONTEXT LookupContext)
NTSTATUS ObpLookupObjectName (IN HANDLE RootDirectoryHandle, IN PUNICODE_STRING ObjectName, IN ULONG Attributes, IN POBJECT_TYPE ObjectType, IN KPROCESSOR_MODE AccessMode, IN PVOID ParseContext OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, IN PVOID InsertObject OPTIONAL, IN OUT PACCESS_STATE AccessState, OUT POBP_LOOKUP_CONTEXT LookupContext, OUT PVOID *FoundObject)
NTSTATUS ObpParseSymbolicLink (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID *Object)
VOID ObpProcessRemoveObjectQueue (PVOID Parameter)
NTSTATUS ObpQueryNameString (IN PVOID Object, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
PDEVICE_MAP ObpReferenceDeviceMap ()
POBJECT_HEADER_NAME_INFO FORCEINLINE ObpReferenceNameInfo (IN POBJECT_HEADER ObjectHeader)
NTSTATUS ObpReferenceProcessObjectByHandle (IN HANDLE Handle, IN PEPROCESS Process, IN PHANDLE_TABLE HandleTable, IN KPROCESSOR_MODE AccessMode, OUT PVOID *Object, OUT POBJECT_HANDLE_INFORMATION HandleInformation, OUT PACCESS_MASK AuditMask)
PSECURITY_DESCRIPTOR ObpReferenceSecurityDescriptor (POBJECT_HEADER ObjectHeader)
VOID FORCEINLINE ObpReleaseLookupContext (IN POBP_LOOKUP_CONTEXT LookupContext)
VOID ObpRemoveObjectRoutine (IN PVOID Object, IN BOOLEAN CalledOnWorkerThread)
FORCEINLINE BOOLEAN ObpSafeInterlockedIncrement (IN OUT LONG_PTR volatile *lpValue)
FORCEINLINE BOOLEAN ObpSafeInterlockedIncrementLong (IN OUT LONG volatile *lpValue)
VOID FORCEINLINE ObpUnlockAllObjects (IN POBJECT_TYPE ObjectType)
VOID FORCEINLINE ObpUnlockDirectory (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LockContext)
VOID ObpUnlockObjectDirectoryPath (IN POBJECT_DIRECTORY LockedDirectory)
NTSTATUS ObpValidateAccessMask (PACCESS_STATE AccessState)
NTSTATUS ObpValidateDesiredAccess (IN ACCESS_MASK DesiredAccess)
Variables
ULONG ObpAccessProtectCloseBit
GENERAL_LOOKASIDE ObpCreateInfoLookasideList
KEVENT ObpDefaultObject
KGUARDED_MUTEX ObpDeviceMapLock
POBJECT_TYPE ObpDeviceMapObjectType
POBJECT_TYPE ObpDirectoryObjectType
const UNICODE_STRING ObpDosDevicesShortName
const ALIGNEDNAME ObpDosDevicesShortNamePrefix
const ALIGNEDNAME ObpDosDevicesShortNameRoot
PHANDLE_TABLE ObpKernelHandleTable
EX_PUSH_LOCK ObpLock
GENERAL_LOOKASIDE ObpNameBufferLookasideList
POBJECT_TYPE ObpObjectTypes [OBP_MAX_DEFINED_OBJECT_TYPES]
PVOID ObpRemoveObjectList
WORK_QUEUE_ITEM ObpRemoveObjectWorkItem
POBJECT_DIRECTORY ObpRootDirectoryObject
POBJECT_TYPE ObpSymbolicLinkObjectType
POBJECT_DIRECTORY ObpTypeDirectoryObject
POBJECT_TYPE ObpTypeObjectType
ERESOURCE SecurityDescriptorCacheLock
Macro Definition Documentation
#define DecodeKernelHandle (H) (HANDLE)(KERNEL_HANDLE_MASK ^ (ULONG_PTR)(H))
Definition at line 481 of file obp.h.
Referenced by ObpCloseHandle(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), and ObSetHandleAttributes().
#define EncodeKernelHandle (H) (HANDLE)(KERNEL_HANDLE_MASK | (ULONG_PTR)(H))
Definition at line 479 of file obp.h.
Referenced by ObpCreateHandle(), and ObpCreateUnnamedHandle().
#define IsKernelHandle (H, M)
Value:
(((KERNEL_HANDLE_MASK & (ULONG_PTR)(H)) == KERNEL_HANDLE_MASK) && \
     ((M) == KernelMode) &&                                \
     ((H) != NtCurrentThread()) &&                         \
     ((H) != NtCurrentProcess()))
Definition at line 473 of file obp.h.
Referenced by ObpCloseHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), and ObSetHandleAttributes().
#define KERNEL_HANDLE_MASK ((ULONG_PTR)((LONG)0x80000000))
Definition at line 471 of file obp.h.
#define LINK_TO_SD_HEADER (_link) CONTAINING_RECORD((_link), SECURITY_DESCRIPTOR_HEADER, Link)
Definition at line 374 of file obp.h.
Referenced by ObLogSecurityDescriptor().
#define LOCK_HASH_MASK (OBJECT_LOCK_COUNT - 1)
Definition at line 217 of file obp.h.
#define OB_NAMESPACE_POOL_TYPE PagedPool
Definition at line 117 of file obp.h.
Referenced by ObInitSystem(), ObpAllocateObjectNameBuffer(), ObpParseSymbolicLink(), ObSetDeviceMap(), and ObSetDirectoryDeviceMap().
#define OBJ_AUDIT_OBJECT_CLOSE 0x00000004L
Definition at line 319 of file obp.h.
#define OBJ_HANDLE_ATTRIBUTES (OBJ_PROTECT_CLOSE | OBJ_INHERIT | OBJ_AUDIT_OBJECT_CLOSE)
Definition at line 327 of file obp.h.
Referenced by ObAuditObjectAccess(), ObDupHandleProcedure(), ObDuplicateObject(), ObpCaptureHandleInformation(), ObpCaptureHandleInformationEx(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObpEnumFindHandleProcedure(), ObpReferenceProcessObjectByHandle(), ObpSetHandleAttributes(), ObpShutdownCloseHandleProcedure(), ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
#define OBJECT_NAME_BUFFER_SIZE 248
Definition at line 453 of file obp.h.
#define OBP_DECLARE_OLDIRQL
Definition at line 121 of file obp.h.
#define OBP_LOCK_OWNEDEXCLUSIVE_SIGNATURE 0xCCCC1234
Definition at line 392 of file obp.h.
Referenced by ObpLockDirectoryExclusive().
#define OBP_LOCK_OWNEDSHARED_SIGNATURE 0xDDDD1234
Definition at line 393 of file obp.h.
Referenced by ObpLockDirectoryShared().
#define OBP_LOCK_RELEASED_SIGNATURE 0xEEEE1234
Definition at line 394 of file obp.h.
Referenced by ObpUnlockDirectory().
#define OBP_LOCK_UNUSED_SIGNATURE 0xFFFF1234
Definition at line 395 of file obp.h.
Referenced by ObpInitializeLookupContext().
#define OBP_LOCK_WAITEXCLUSIVE_SIGNATURE 0xAAAA1234
Definition at line 390 of file obp.h.
Referenced by ObpLockDirectoryExclusive().
#define OBP_LOCK_WAITSHARED_SIGNATURE 0xBBBB1234
Definition at line 391 of file obp.h.
Referenced by ObpLockDirectoryShared().
#define OBP_MAX_DEFINED_OBJECT_TYPES 48
Definition at line 263 of file obp.h.
Referenced by NtQueryObject(), and ObCreateObjectType().
#define OBP_NAME_KERNEL_PROTECTED ((LONG)0x40000000)
Definition at line 1002 of file obp.h.
Referenced by ObpAllocateObject(), ObpDeleteNameCheck(), ObpIsKernelExclusiveObject(), and ObpTryReferenceNameInfoExclusive().
#define OBP_NAME_LOCKED ((LONG)0x80000000)
Definition at line 1001 of file obp.h.
Referenced by ObpReferenceNameInfo(), ObpReleaseExclusiveNameLock(), and ObpTryReferenceNameInfoExclusive().
#define OBP_PAGEDPOOL_NAMESPACE
Definition at line 47 of file obp.h.
Referenced by ObInitSystem().
#define ObpAllocateObjectCreateInfoBuffer () (POBJECT_CREATE_INFORMATION)ExAllocateFromPPLookasideList(LookasideCreateInfoList)
Definition at line 583 of file obp.h.
Referenced by ObCreateObject().
#define ObpBeginTypeSpecificCallOut (IRQL)
Definition at line 80 of file obp.h.
Referenced by ObAssignSecurity(), ObGetObjectSecurity(), ObpCloseHandleTableEntry(), ObpDecrementHandleCount(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpLookupObjectName(), ObpQueryNameString(), ObpRemoveObjectRoutine(), and ObShutdownSystem().
#define ObpCentralizedSecurity (_ObjectType) ((_ObjectType)->TypeInfo.SecurityProcedure == SeDefaultObjectMethod)
Definition at line 256 of file obp.h.
Referenced by ObGetObjectSecurity().
#define ObpDecodeGrantedAccess (Access) ((Access) & ~ObpAccessProtectCloseBit)
Definition at line 329 of file obp.h.
Referenced by ObDupHandleProcedure(), ObpCaptureHandleInformation(), ObpCaptureHandleInformationEx(), ObpCloseHandleTableEntry(), ObpEnumFindHandleProcedure(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
#define ObpDecrHandleCount (np) (ObpInterlockedDecrement(&np->HandleCount) == 0)
Definition at line 184 of file obp.h.
Referenced by ObpDecrementHandleCount(), ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
#define ObpDecrPointerCount (np) ObpInterlockedDecrement(&np->PointerCount)
Definition at line 149 of file obp.h.
Referenced by ObDereferenceObjectDeferDelete(), and ObfDereferenceObject().
#define ObpDecrPointerCountEx (np, Count) (ObpInterlockedExchangeAdd (&np->PointerCount, -(LONG_PTR)(Count)) - Count)
Definition at line 144 of file obp.h.
Referenced by ObDereferenceObjectEx(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
#define ObpDecrPointerCountWithResult (np) (ObpInterlockedDecrement(&np->PointerCount) == 0)
Definition at line 150 of file obp.h.
#define ObpEncodeProtectClose (ObjectTableEntry)
Value:
if ((ObjectTableEntry).ObAttributes & OBJ_PROTECT_CLOSE) {        \
                                                                        \
        (ObjectTableEntry).ObAttributes &= ~OBJ_PROTECT_CLOSE;          \
        (ObjectTableEntry).GrantedAccess |= ObpAccessProtectCloseBit;   \
    }
Definition at line 337 of file obp.h.
Referenced by ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
#define ObpEndTypeSpecificCallOut (IRQL, str, ot, o)
Definition at line 81 of file obp.h.
Referenced by ObAssignSecurity(), ObGetObjectSecurity(), ObpCloseHandleTableEntry(), ObpDecrementHandleCount(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpLookupObjectName(), ObpQueryNameString(), ObpRemoveObjectRoutine(), and ObShutdownSystem().
#define ObpEnterObjectTypeMutex (_ObjectType)
Value:
{                   \
    ObpValidateIrql("ObpEnterObjectTypeMutex");                  \
    KeEnterCriticalRegion();                                     \
    ExAcquireResourceExclusiveLite(&(_ObjectType)->Mutex, TRUE); \
}
Definition at line 198 of file obp.h.
Referenced by ObCreateObjectType(), ObpCreateTypeArray(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), and ObpRemoveObjectRoutine().
#define ObpFreeObjectCreateInfoBuffer (ObjectCreateInfo) ExFreeToPPLookasideList(LookasideCreateInfoList, ObjectCreateInfo)
Definition at line 611 of file obp.h.
Referenced by ObCreateObject(), and ObFreeObjectCreateInfoBuffer().
#define ObpFreeObjectCreateInformation (_ObjectCreateInfo)
Value:
{ \
    ObpReleaseObjectCreateInformation((_ObjectCreateInfo)); \
    ObpFreeObjectCreateInfoBuffer((_ObjectCreateInfo));     \
}
Definition at line 494 of file obp.h.
Referenced by ObDeleteCapturedInsertInfo(), ObInsertObject(), ObOpenObjectByName(), and ObpFreeObject().
#define ObpGetHandleAttributes (HandleTableEntry)
Value:
((((HandleTableEntry)->GrantedAccess) & ObpAccessProtectCloseBit) ?            \
     ((((HandleTableEntry)->ObAttributes) & OBJ_HANDLE_ATTRIBUTES) | OBJ_PROTECT_CLOSE) : \
     (((HandleTableEntry)->ObAttributes) & (OBJ_INHERIT | OBJ_AUDIT_OBJECT_CLOSE)) )
Definition at line 332 of file obp.h.
Referenced by ObpCaptureHandleInformation(), ObpCaptureHandleInformationEx(), ObpCloseHandleTableEntry(), ObpEnumFindHandleProcedure(), ObpReferenceProcessObjectByHandle(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
#define ObpGetObjectTable () (PsGetCurrentProcess()->ObjectTable)
Definition at line 248 of file obp.h.
Referenced by ObAuditObjectAccess(), ObpCreateHandle(), ObpCreateUnnamedHandle(), and ObSetHandleAttributes().
#define ObpHashObjectHeader (_ObjectHeader) ((((ULONG_PTR)(_ObjectHeader)) >> 8) & LOCK_HASH_MASK)
Definition at line 219 of file obp.h.
#define ObpIncrHandleCount (np) ObpInterlockedIncrement(&np->HandleCount)
Definition at line 183 of file obp.h.
Referenced by ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
#define ObpIncrPointerCount (np) ObpInterlockedIncrement(&np->PointerCount)
Definition at line 148 of file obp.h.
Referenced by ObDupHandleProcedure(), ObfReferenceObject(), ObpLookupObjectName(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), and ObReferenceObjectByPointer().
#define ObpIncrPointerCountEx (np, Count) (ObpInterlockedExchangeAdd (&np->PointerCount, Count) + Count)
Definition at line 143 of file obp.h.
Referenced by ObpCreateHandle(), ObpCreateUnnamedHandle(), and ObReferenceObjectEx().
#define ObpInterlockedCompareExchange InterlockedCompareExchange
Definition at line 43 of file obp.h.
Referenced by ObpSafeInterlockedIncrement().
#define ObpInterlockedDecrement InterlockedDecrement
Definition at line 42 of file obp.h.
#define ObpInterlockedExchangeAdd InterlockedExchangeAdd
Definition at line 40 of file obp.h.
#define ObpInterlockedIncrement InterlockedIncrement
Definition at line 41 of file obp.h.
#define ObpIsOverflow (A, B) ((A) > ((A) + (B)))
Definition at line 487 of file obp.h.
Referenced by NtQueryDirectoryObject().
#define ObpLeaveObjectTypeMutex (_ObjectType)
Value:
{  \
    ExReleaseResourceLite(&(_ObjectType)->Mutex);   \
    KeLeaveCriticalRegion();                    \
    ObpValidateIrql("ObpLeaveObjectTypeMutex"); \
}
Definition at line 211 of file obp.h.
Referenced by ObCreateObjectType(), ObpCreateTypeArray(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), and ObpRemoveObjectRoutine().
#define ObpLockDeviceMap () KeAcquireGuardedMutex(&ObpDeviceMapLock)
Definition at line 123 of file obp.h.
Referenced by ObDereferenceDeviceMap(), ObfDereferenceDeviceMap(), ObInheritDeviceMap(), ObpGetShadowDirectory(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceDeviceMap(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), and ObSetDirectoryDeviceMap().
#define ObpLockObject (_ObjectHeader)
Value:
{                           \
    ULONG_PTR LockIndex = ObpHashObjectHeader(_ObjectHeader);    \
    ObpValidateIrql("ObpEnterObjectTypeMutex");                  \
    KeEnterCriticalRegion();                                     \
    ExAcquireResourceExclusiveLite(&((_ObjectHeader)->Type->ObjectLocks[LockIndex]), TRUE); \
}
Definition at line 222 of file obp.h.
Referenced by NtMakePermanentObject(), NtQuerySymbolicLinkObject(), ObInsertObject(), ObMakeTemporaryObject(), ObpDecrementHandleCount(), ObpDeleteNameCheck(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObSetSecurityDescriptorInfo(), and ObShutdownSystem().
#define ObpLockObjectShared (_ObjectHeader)
Value:
{                     \
    ULONG_PTR LockIndex = ObpHashObjectHeader(_ObjectHeader);    \
    ObpValidateIrql("ObpEnterObjectTypeMutex");                  \
    KeEnterCriticalRegion();                                     \
    ExAcquireResourceSharedLite(&((_ObjectHeader)->Type->ObjectLocks[LockIndex]), TRUE); \
}
Definition at line 229 of file obp.h.
Referenced by ObpReferenceSecurityDescriptor().
#define ObpPushStackInfo (np, inc)
Definition at line 152 of file obp.h.
Referenced by ObCreateObject(), and ObReferenceObjectSafe().
#define ObpReleaseObjectCreateInformation (_ObjectCreateInfo)
Value:
{               \
    if ((_ObjectCreateInfo)->SecurityDescriptor != NULL) {                   \
        SeReleaseSecurityDescriptor((_ObjectCreateInfo)->SecurityDescriptor, \
                                    (_ObjectCreateInfo)->ProbeMode,          \
                                     TRUE);                                  \
        (_ObjectCreateInfo)->SecurityDescriptor = NULL;                      \
    }                                                                        \
}
Definition at line 499 of file obp.h.
Referenced by ObCreateObject(), ObOpenObjectByName(), and ObpCaptureObjectCreateInformation().
#define ObpUnlockDeviceMap () KeReleaseGuardedMutex(&ObpDeviceMapLock)
Definition at line 126 of file obp.h.
Referenced by ObDereferenceDeviceMap(), ObfDereferenceDeviceMap(), ObInheritDeviceMap(), ObpGetShadowDirectory(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceDeviceMap(), ObpSetCurrentProcessDeviceMap(), ObQueryDeviceMapInformation(), ObSetDeviceMap(), and ObSetDirectoryDeviceMap().
#define ObpUnlockObject (_ObjectHeader)
Value:
{                                        \
    ULONG_PTR LockIndex = ObpHashObjectHeader(_ObjectHeader);                   \
    ExReleaseResourceLite(&((_ObjectHeader)->Type->ObjectLocks[LockIndex]));        \
    KeLeaveCriticalRegion();                                                    \
    ObpValidateIrql("ObpLeaveObjectTypeMutex");                                 \
}
Definition at line 236 of file obp.h.
Referenced by NtMakePermanentObject(), NtQuerySymbolicLinkObject(), ObInsertObject(), ObMakeTemporaryObject(), ObpDecrementHandleCount(), ObpDeleteNameCheck(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpReferenceSecurityDescriptor(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObSetSecurityDescriptorInfo(), and ObShutdownSystem().
#define ObpValidateIrql (str)
Definition at line 95 of file obp.h.
Referenced by NtCreateDirectoryObject(), NtOpenDirectoryObject(), NtQueryDirectoryObject(), ObCreateObjectType(), ObInsertObject(), ObKillProcess(), ObOpenObjectByName(), ObOpenObjectByPointer(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObpDeleteNameCheck(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpLookupObjectName(), ObpReferenceProcessObjectByHandle(), ObpRemoveObjectRoutine(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), and ObReferenceObjectByName().
#define SD_TO_SD_HEADER (_sd) CONTAINING_RECORD((_sd), SECURITY_DESCRIPTOR_HEADER, SecurityDescriptor)
Definition at line 367 of file obp.h.
Referenced by ObDereferenceSecurityDescriptor(), ObpReferenceSecurityDescriptor(), and ObReferenceSecurityDescriptor().
#define SECURITY_DESCRIPTOR_CACHE_ENTRIES 257
Definition at line 382 of file obp.h.
Referenced by ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), and ObpInitSecurityDescriptorCache().
Typedef Documentation
typedef struct _OBP_LOOKUP_CONTEXT OBP_LOOKUP_CONTEXT
typedef struct _OBP_SWEEP_CONTEXT OBP_SWEEP_CONTEXT
typedef struct _OBP_LOOKUP_CONTEXT * POBP_LOOKUP_CONTEXT
typedef struct _OBP_SWEEP_CONTEXT * POBP_SWEEP_CONTEXT
typedef struct _SECURITY_DESCRIPTOR_HEADER * PSECURITY_DESCRIPTOR_HEADER
typedef struct _SECURITY_DESCRIPTOR_HEADER SECURITY_DESCRIPTOR_HEADER
Function Documentation
VOID FASTCALL ObfDereferenceDeviceMap (IN PDEVICE_MAP DeviceMap)
Definition at line 1661 of file obdir.c.
NTSTATUS ObpAllocateObject (IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN KPROCESSOR_MODE OwnershipMode, IN POBJECT_TYPE ObjectType, IN PUNICODE_STRING ObjectName, IN ULONG ObjectBodySize, OUT POBJECT_HEADER * ReturnedObjectHeader)
Definition at line 805 of file obcreate.c.
References _OBJECT_HEADER_CREATOR_INFO::CreatorBackTraceIndex, _OBJECT_HEADER_CREATOR_INFO::CreatorUniqueProcess, DbgPrint(), _OBJECT_HEADER_NAME_INFO::Directory, ExAllocatePoolWithTag, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, FIELD_OFFSET, _OBJECT_HEADER::Flags, _OBJECT_HANDLE_COUNT_ENTRY::HandleCount, _OBJECT_HEADER::HandleCount, _OBJECT_HEADER::HandleInfoOffset, InitializeListHead(), InterlockedIncrement, KernelMode, _OBJECT_HEADER_NAME_INFO::Name, _OBJECT_HEADER::NameInfoOffset, NonPagedPool, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NULL, OB_FLAG_CREATOR_INFO, OB_FLAG_EXCLUSIVE_OBJECT, OB_FLAG_KERNEL_OBJECT, OB_FLAG_NEW_OBJECT, OB_FLAG_PERMANENT_OBJECT, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJ_EXCLUSIVE, OBJ_KERNEL_EXCLUSIVE, OBJ_PERMANENT, _OBJECT_HEADER::ObjectCreateInfo, OBP_NAME_KERNEL_PROTECTED, PAGED_CODE, PagedPool, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, PERFINFO_ADD_OBJECT_TO_ALLOCATED_TYPE_LIST, _OBJECT_HEADER::PointerCount, PROTECTED_POOL, PsGetCurrentProcess(), PsInitialSystemProcess, _OBJECT_HEADER_NAME_INFO::QueryReferences, _OBJECT_HEADER::QuotaInfoOffset, SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER::SecurityDescriptor, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, _OBJECT_HEADER_HANDLE_INFO::SingleEntry, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _OBJECT_HEADER::Type, _OBJECT_HEADER_CREATOR_INFO::TypeList, and _EPROCESS::UniqueProcessId.
Referenced by ObCreateObject(), and ObCreateObjectType().
PWCHAR ObpAllocateObjectNameBuffer (IN ULONG Length, IN LOGICAL UseLookaside, IN OUT PUNICODE_STRING ObjectName)
Definition at line 633 of file obcreate.c.
References ExAllocateFromPPLookasideList(), ExAllocatePoolWithTag, FALSE, LookasideNameBufferList, OB_NAMESPACE_POOL_TYPE, and OBJECT_NAME_BUFFER_SIZE.
Referenced by ObpCaptureObjectName().
VOID ObpAuditObjectAccess (IN HANDLE Handle, IN PHANDLE_TABLE_ENTRY_INFO ObjectTableEntryInfo, IN PUNICODE_STRING ObjectTypeName, IN ACCESS_MASK DesiredAccess)
Definition at line 1894 of file obref.c.
References InterlockedCompareExchange(), NULL, and SeOperationAuditAlarm().
Referenced by ObAuditObjectAccess(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
NTSTATUS ObpCaptureObjectCreateInformation (IN POBJECT_TYPE ObjectType OPTIONAL, IN KPROCESSOR_MODE ProbeMode, IN KPROCESSOR_MODE CreatorMode, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PUNICODE_STRING CapturedObjectName, IN POBJECT_CREATE_INFORMATION ObjectCreateInfo, IN LOGICAL UseLookaside)
NTSTATUS ObpCaptureObjectName (IN KPROCESSOR_MODE ProbeMode, IN PUNICODE_STRING ObjectName, IN OUT PUNICODE_STRING CapturedObjectName, IN LOGICAL UseLookaside)
Definition at line 488 of file obcreate.c.
References _UNICODE_STRING::Buffer, except, ExFreePool(), ExSystemExceptionFilter(), KernelMode, _UNICODE_STRING::Length, MAXUSHORT, NULL, ObpAllocateObjectNameBuffer(), PAGED_CODE, ProbeAndReadUnicodeStringEx, ProbeForRead, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_INVALID, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by ObpCaptureObjectCreateInformation(), and ObReferenceObjectByName().
NTSTATUS ObpChargeQuotaForObject (IN POBJECT_HEADER ObjectHeader, IN POBJECT_TYPE ObjectType, OUT PBOOLEAN NewObject)
Definition at line 2201 of file obhandle.c.
References FALSE, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NULL, OB_FLAG_DEFAULT_SECURITY_QUOTA, OB_FLAG_NEW_OBJECT, OBJECT_HEADER_TO_QUOTA_INFO(), _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, PsChargeSharedPoolQuota(), PsGetCurrentProcess(), SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, STATUS_QUOTA_EXCEEDED, STATUS_SUCCESS, and TRUE.
Referenced by ObInsertObject(), ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
BOOLEAN ObpCheckObjectReference (IN PVOID Object, IN OUT PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE AccessMode, OUT PNTSTATUS AccessStatus)
Definition at line 568 of file obse.c.
References FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeLockSubjectContext(), SeObjectReferenceAuditAlarm(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by ObReferenceObjectByName().
BOOLEAN ObpCheckPseudoHandleAccess (IN PVOID Object, IN ACCESS_MASK DesiredAccess, OUT PNTSTATUS AccessStatus, IN BOOLEAN TypeMutexLocked)
BOOLEAN ObpCheckTraverseAccess (IN PVOID DirectoryObject, IN ACCESS_MASK TraverseAccess, IN PACCESS_STATE AccessState, IN BOOLEAN TypeMutexLocked, IN KPROCESSOR_MODE PreviousMode, OUT PNTSTATUS AccessStatus)
Definition at line 721 of file obse.c.
References DIRECTORY_TRAVERSE, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, NT_SUCCESS, NULL, ObGetObjectSecurity(), OBJECT_TO_OBJECT_HEADER, ObReleaseObjectSecurity(), PAGED_CODE, SeAccessCheck(), SeAppendPrivileges(), SeFastTraverseCheck(), SeFreePrivileges(), SeLockSubjectContext(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by ObpLookupObjectName().
NTSTATUS ObpCloseHandle (IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode)
Definition at line 211 of file obclose.c.
References _HANDLE_TABLE::DebugInfo, _EPROCESS::DebugPort, DecodeKernelHandle, ExMapHandleToPointer(), FALSE, FLG_ENABLE_CLOSE_EXCEPTIONS, INVALID_KERNEL_HANDLE, IsKernelHandle, KdDebuggerEnabled, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeIsAttachedProcess(), KeLeaveCriticalRegionThread(), KeRaiseUserException(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, _EPROCESS::ObjectTable, ObpCloseHandleTableEntry(), ObpKernelHandleTable, ObpValidateIrql, _EPROCESS::Pcb, _EPROCESS::Peb, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsInitialSystemProcess, PsIsThreadTerminating(), Status, STATUS_INVALID_HANDLE, _ETHREAD::Tcb, and TRUE.
Referenced by NtClose(), and ObCloseHandle().
NTSTATUS ObpCloseHandleTableEntry (IN PHANDLE_TABLE ObjectTable, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE Handle, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN Rundown)
Definition at line 38 of file obclose.c.
References _OBJECT_HEADER::Body, ExDestroyHandle(), ExUnlockHandleTableEntry(), FALSE, FLG_ENABLE_CLOSE_EXCEPTIONS, FLG_KERNEL_STACK_TRACE_DB, INVALID_KERNEL_HANDLE, KeBugCheckEx(), KeIsAttachedProcess(), KeRaiseUserException(), KernelMode, NtGlobalFlag, NULL, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, OBJ_HANDLE_TAGBITS, OBJ_PROTECT_CLOSE, ObpBeginTypeSpecificCallOut, ObpDecodeGrantedAccess, ObpDecrementHandleCount(), ObpEndTypeSpecificCallOut, ObpGetHandleAttributes, ObpTranslateGrantedAccessIndex(), _OBJECT_TYPE_INITIALIZER::OkayToCloseProcedure, PsGetCurrentProcess(), SeCloseObjectAuditAlarm(), SepAdtAuditingEnabled, STATUS_HANDLE_NOT_CLOSABLE, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, and _OBJECT_TYPE::TypeInfo.
Referenced by ObpCloseHandle(), and ObpCloseHandleProcedure().
BOOLEAN ObpCompareSecurityDescriptors (IN PSECURITY_DESCRIPTOR SD1, ULONG Length, IN PSECURITY_DESCRIPTOR SD2)
PSECURITY_DESCRIPTOR_HEADER ObpCreateCacheEntry (PSECURITY_DESCRIPTOR InputSecurityDescriptor, ULONG Length, ULONG FullHash, ULONG RefBias)
Definition at line 459 of file obsdata.c.
References ASSERT, ExAllocatePoolWithTag, NULL, PagedPool, RtlCopyMemory, and RtlLengthSecurityDescriptor().
Referenced by ObLogSecurityDescriptor().
NTSTATUS ObpCreateHandle (IN OB_OPEN_REASON OpenReason, IN PVOID Object, IN POBJECT_TYPE ExpectedObjectType OPTIONAL, IN PACCESS_STATE AccessState, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN POBP_LOOKUP_CONTEXT LookupContext, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
Definition at line 2475 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _HANDLE_TABLE_ENTRY::CreatorBackTraceIndex, EncodeKernelHandle, ExCreateHandle(), ExMapHandleToPointer(), ExSetHandleInfo(), ExUnlockHandleTableEntry(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, ObCreateHandle, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, OBJ_KERNEL_HANDLE, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, OBP_CREATOR_BACKTRACE_LIMIT, ObpComputeGrantedAccessIndex(), ObpDecrementHandleCount(), ObpDecrPointerCountEx, ObpEncodeProtectClose, ObpGetObjectTable, ObpIncrementHandleCount(), ObpIncrPointerCountEx, ObpKernelHandleTable, ObpReleaseLookupContext(), ObpValidateIrql, PAGED_CODE, _EPROCESS::Pcb, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, PsGetCurrentProcess(), PsInitialSystemProcess, RtlLogStackBackTrace(), RtlLogUmodeStackBackTrace(), SeAuditHandleCreation(), SePrivilegeObjectAuditAlarm(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ObInsertObject(), ObOpenObjectByName(), and ObOpenObjectByPointer().
VOID ObpCreateSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
Definition at line 995 of file oblink.c.
References _UNICODE_STRING::Buffer, CREATE_SYMBOLIC_LINK, _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, _OBJECT_SYMBOLIC_LINK::DosDeviceDriveIndex, _UNICODE_STRING::Length, _OBJECT_HEADER_NAME_INFO::Name, NULL, OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpProcessDosDeviceSymbolicLink(), ObpReferenceNameInfo(), and RtlUpcaseUnicodeChar().
Referenced by ObInsertObject().
NTSTATUS ObpCreateUnnamedHandle (IN PVOID Object, IN ACCESS_MASK DesiredAccess, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
Definition at line 2886 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _HANDLE_TABLE_ENTRY::CreatorBackTraceIndex, EncodeKernelHandle, ExCreateHandle(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_HANDLE_ATTRIBUTES, OBJ_KERNEL_HANDLE, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, OBP_CREATOR_BACKTRACE_LIMIT, ObpComputeGrantedAccessIndex(), ObpDecrementHandleCount(), ObpDecrPointerCountEx, ObpEncodeProtectClose, ObpGetObjectTable, ObpIncrementUnnamedHandleCount(), ObpIncrPointerCountEx, ObpKernelHandleTable, ObpValidateIrql, PAGED_CODE, _EPROCESS::Pcb, PsGetCurrentProcess(), PsInitialSystemProcess, RtlLogStackBackTrace(), RtlLogUmodeStackBackTrace(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ObInsertObject().
VOID ObpDecrementHandleCount (PEPROCESS Process, POBJECT_HEADER ObjectHeader, POBJECT_TYPE ObjectType, ACCESS_MASK GrantedAccess)
Definition at line 2307 of file obhandle.c.
References ASSERT, _OBJECT_HEADER::Body, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_HANDLE_COUNT_DATABASE::CountEntries, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, _OBJECT_HEADER::Flags, _OBJECT_HANDLE_COUNT_ENTRY::HandleCount, _OBJECT_HEADER::HandleCount, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, _OBJECT_HANDLE_COUNT_DATABASE::HandleCountEntries, InterlockedDecrement, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, NULL, OB_FLAG_EXCLUSIVE_OBJECT, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_HANDLE_INFO_EXISTS(), OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), ObpBeginTypeSpecificCallOut, ObpDecrHandleCount, ObpDeleteNameCheck(), ObpEndTypeSpecificCallOut, ObpLockObject, ObpUnlockObject, PAGED_CODE, _OBJECT_HANDLE_COUNT_ENTRY::Process, ProcessHandleCount, _OBJECT_HEADER_HANDLE_INFO::SingleEntry, _OBJECT_TYPE::TotalNumberOfHandles, and _OBJECT_TYPE::TypeInfo.
Referenced by ObDuplicateObject(), ObpCloseHandleTableEntry(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
BOOLEAN ObpDeleteDirectoryEntry (IN POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 1291 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, ExFreePool(), FALSE, IN, NULL, and TRUE.
Referenced by ObInsertObject(), and ObpDeleteNameCheck().
VOID ObpDeleteNameCheck (IN PVOID Object)
Definition at line 2767 of file obref.c.
References _OBJECT_HEADER_NAME_INFO::Directory, FALSE, _OBJECT_HEADER::Flags, _OBJECT_HEADER::HandleCount, InterlockedExchangeAdd(), _UNICODE_STRING::Length, _OBJECT_HEADER_NAME_INFO::Name, NULL, OB_FLAG_PERMANENT_OBJECT, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, OBP_NAME_KERNEL_PROTECTED, ObpDeleteDirectoryEntry(), ObpDeleteSymbolicLinkName(), ObpDereferenceNameInfo(), ObpInitializeLookupContext(), ObpIsKernelExclusiveObject(), ObpLockLookupContext(), ObpLockObject, ObpLookupDirectoryEntry(), ObpReferenceNameInfo(), ObpReleaseLookupContext(), ObpSymbolicLinkObjectType, ObpUnlockObject, ObpValidateIrql, PAGED_CODE, _OBJECT_HEADER_NAME_INFO::QueryReferences, and _OBJECT_HEADER::Type.
Referenced by ObInsertObject(), ObMakeTemporaryObject(), ObpDecrementHandleCount(), and ObSwapObjectNames().
VOID ObpDeleteObjectType (IN PVOID Object)
Definition at line 499 of file obtype.c.
References ExDeleteResourceLite(), _OBJECT_TYPE::Mutex, OBJECT_LOCK_COUNT, and _OBJECT_TYPE::ObjectLocks.
Referenced by ObInitSystem().
VOID ObpDeleteSymbolicLink (IN PVOID Object)
Definition at line 915 of file oblink.c.
References _UNICODE_STRING::Buffer, ExFreePool(), _OBJECT_SYMBOLIC_LINK::LinkTarget, NULL, and PAGED_CODE.
Referenced by ObInitSystem().
VOID ObpDeleteSymbolicLinkName (POBJECT_SYMBOLIC_LINK SymbolicLink)
Definition at line 962 of file oblink.c.
References DELETE_SYMBOLIC_LINK, and ObpProcessDosDeviceSymbolicLink().
Referenced by ObpDeleteNameCheck(), and ObShutdownSystem().
VOID FORCEINLINE ObpDereferenceNameInfo (IN POBJECT_HEADER_NAME_INFO NameInfo)
Definition at line 1119 of file obp.h.
References ExFreePool(), InterlockedDecrement, NULL, and ObDereferenceObjectDeferDelete().
Referenced by NtQueryObject(), ObInsertObject(), ObpCreateSymbolicLinkName(), ObpDeleteNameCheck(), ObpLookupDirectoryEntry(), ObpProcessDosDeviceSymbolicLink(), ObpQueryNameString(), ObpReleaseLookupContext(), ObpReleaseLookupContextObject(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), and ObSwapObjectNames().
PVOID ObpDestroySecurityDescriptorHeader (IN PSECURITY_DESCRIPTOR_HEADER Header)
Definition at line 802 of file obsdata.c.
References ASSERT, InterlockedDecrement, ObPrint, and RemoveEntryList().
Referenced by ObDereferenceSecurityDescriptor().
VOID FASTCALL ObpFreeObject (IN PVOID Object)
Definition at line 1165 of file obcreate.c.
References _UNICODE_STRING::Buffer, DbgPrint(), _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, ExFreePool(), ExFreePoolWithTag, _OBJECT_HEADER::Flags, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, InterlockedDecrement, _OBJECT_TYPE::Name, _OBJECT_HEADER_NAME_INFO::Name, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NULL, OB_FLAG_DEFAULT_SECURITY_QUOTA, OB_FLAG_NEW_OBJECT, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_HANDLE_INFO(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_HEADER_TO_QUOTA_INFO(), OBJECT_TO_OBJECT_HEADER, _OBJECT_HEADER::ObjectCreateInfo, ObpFreeObjectCreateInformation, PAGED_CODE, _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, PERFINFO_REMOVE_OBJECT_FROM_ALLOCATED_TYPE_LIST, PROTECTED_POOL, PsReturnSharedPoolQuota(), _OBJECT_HEADER::QuotaBlockCharged, SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, _OBJECT_TYPE::TotalNumberOfObjects, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UIntToPtr.
Referenced by ObCreateObject(), and ObpRemoveObjectRoutine().
VOID FASTCALL ObpFreeObjectNameBuffer (IN PUNICODE_STRING ObjectName)
ULONG ObpHashBuffer (PVOID Data, ULONG Length)
Definition at line 210 of file obsdata.c.
References _rotl().
Referenced by ObpHashSecurityDescriptor().
ULONG ObpHashSecurityDescriptor (PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG Length)
Definition at line 178 of file obsdata.c.
References ObpHashBuffer().
Referenced by ObLogSecurityDescriptor().
NTSTATUS ObpIncrementHandleCount (OB_OPEN_REASON OpenReason, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, PACCESS_STATE AccessState OPTIONAL, KPROCESSOR_MODE AccessMode, ULONG Attributes)
Definition at line 1532 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _LUID_AND_ATTRIBUTES::Attributes, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _PRIVILEGE_SET::Control, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, FALSE, _OBJECT_HEADER::Flags, GENERIC_ACCESS, GENERIC_ALL, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HEADER::HandleCount, _OBJECT_TYPE::HighWaterNumberOfHandles, InsertTailList(), InterlockedIncrement, KernelMode, leave, _LUID_AND_ATTRIBUTES::Luid, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, OB_FLAG_EXCLUSIVE_OBJECT, ObCheckObjectAccess(), ObCreateHandle, ObDuplicateHandle, OBJ_EXCLUSIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_INHERIT, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_EXCLUSIVE_PROCESS, OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObOpenHandle, ObpBeginTypeSpecificCallOut, ObpChargeQuotaForObject(), ObpDecrHandleCount, ObpEndTypeSpecificCallOut, ObpEnterObjectTypeMutex, ObpIncrementHandleDataBase(), ObpIncrHandleCount, ObpIsKernelExclusiveObject(), ObpLeaveObjectTypeMutex, ObpLockObject, ObpUnlockObject, ObpValidateIrql, _OBJECT_TYPE_INITIALIZER::OpenProcedure, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, ProcessHandleCount, PsGetCurrentProcess(), RtlMapGenericMask(), SeAppendPrivileges(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), SeSecurityPrivilege, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _OBJECT_TYPE::TotalNumberOfHandles, TRUE, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_HEADER_CREATOR_INFO::TypeList, UserMode, and VOID.
Referenced by ObDupHandleProcedure(), ObDuplicateObject(), and ObpCreateHandle().
NTSTATUS ObpIncrementUnnamedHandleCount (PACCESS_MASK DesiredAccess, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, KPROCESSOR_MODE AccessMode, ULONG Attributes)
Definition at line 1918 of file obhandle.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, FALSE, _OBJECT_HEADER::Flags, GENERIC_ACCESS, GENERIC_ALL, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HEADER::HandleCount, _OBJECT_TYPE::HighWaterNumberOfHandles, InsertTailList(), InterlockedIncrement, leave, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, OB_FLAG_EXCLUSIVE_OBJECT, ObCreateHandle, OBJ_EXCLUSIVE, OBJ_INHERIT, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_EXCLUSIVE_PROCESS, OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpChargeQuotaForObject(), ObpDecrHandleCount, ObpEndTypeSpecificCallOut, ObpEnterObjectTypeMutex, ObpIncrementHandleDataBase(), ObpIncrHandleCount, ObpLeaveObjectTypeMutex, ObpLockObject, ObpUnlockObject, ObpValidateIrql, _OBJECT_TYPE_INITIALIZER::OpenProcedure, PAGED_CODE, ProcessHandleCount, PsGetCurrentProcess(), RtlMapGenericMask(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _OBJECT_TYPE::TotalNumberOfHandles, TRUE, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_HEADER_CREATOR_INFO::TypeList, UNREFERENCED_PARAMETER, and VOID.
Referenced by ObpCreateUnnamedHandle().
VOID FORCEINLINE ObpInitializeLookupContext (IN POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 1289 of file obp.h.
References FALSE, NULL, and OBP_LOCK_UNUSED_SIGNATURE.
Referenced by NtQueryDirectoryObject(), NtSetInformationObject(), ObCreateObjectType(), ObInitSystem(), ObInsertObject(), ObpDeleteNameCheck(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), and ObSwapObjectNames().
NTSTATUS ObpInitSecurityDescriptorCache (VOID)
Definition at line 133 of file obsdata.c.
References DbgBreakPoint(), ExInitializePushLock(), IF_OB_GLOBAL, InitializeListHead(), SECURITY_DESCRIPTOR_CACHE_ENTRIES, and STATUS_SUCCESS.
Referenced by ObInitSystem().
BOOLEAN ObpInsertDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LookupContext, IN POBJECT_HEADER ObjectHeader)
Definition at line 1186 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, DbgBreakPoint(), DbgPrint(), _OBJECT_HEADER_NAME_INFO::Directory, ExAllocatePoolWithTag, FALSE, _OBJECT_DIRECTORY_ENTRY::HashValue, NULL, _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO_EXISTS(), PagedPool, and TRUE.
Referenced by ObCreateObjectType(), ObInitSystem(), and ObpLookupObjectName().
POBJECT_HANDLE_COUNT_ENTRY ObpInsertHandleCount (POBJECT_HEADER ObjectHeader)
Definition at line 1214 of file obhandle.c.
References _OBJECT_HANDLE_COUNT_DATABASE::CountEntries, ExAllocatePoolWithTag, ExFreePool(), _OBJECT_HEADER::Flags, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, _OBJECT_HANDLE_COUNT_DATABASE::HandleCountEntries, NULL, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_HANDLE_INFO(), PAGED_CODE, PagedPool, RtlCopyMemory, RtlZeroMemory, and _OBJECT_HEADER_HANDLE_INFO::SingleEntry.
Referenced by ObpIncrementHandleDataBase().
FORCEINLINE LOGICAL ObpIsKernelExclusiveObject (IN POBJECT_HEADER ObjectHeader)
Definition at line 1173 of file obp.h.
References NULL, OBJECT_HEADER_TO_NAME_INFO(), OBP_NAME_KERNEL_PROTECTED, and _OBJECT_HEADER_NAME_INFO::QueryReferences.
Referenced by ObpDeleteNameCheck(), and ObpIncrementHandleCount().
VOID FORCEINLINE ObpLockAllObjects (IN POBJECT_TYPE ObjectType)
Definition at line 1417 of file obp.h.
References ExAcquireResourceExclusiveLite(), KeEnterCriticalRegion(), OBJECT_LOCK_COUNT, and TRUE.
Referenced by ObSwapObjectNames().
VOID FORCEINLINE ObpLockDirectoryExclusive (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LockContext)
Definition at line 1201 of file obp.h.
References ExAcquirePushLockExclusive(), KeEnterCriticalRegion(), OBP_LOCK_OWNEDEXCLUSIVE_SIGNATURE, and OBP_LOCK_WAITEXCLUSIVE_SIGNATURE.
Referenced by NtSetInformationObject(), and ObpLockLookupContext().
VOID FORCEINLINE ObpLockDirectoryShared (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LockContext)
Definition at line 1231 of file obp.h.
References ExAcquirePushLockShared(), KeEnterCriticalRegion(), OBP_LOCK_OWNEDSHARED_SIGNATURE, and OBP_LOCK_WAITSHARED_SIGNATURE.
Referenced by NtQueryDirectoryObject(), and ObpLookupDirectoryEntry().
VOID FORCEINLINE ObpLockLookupContext (IN POBP_LOOKUP_CONTEXT LookupContext, IN POBJECT_DIRECTORY Directory)
Definition at line 1317 of file obp.h.
References ObpLockDirectoryExclusive(), and TRUE.
Referenced by ObCreateObjectType(), ObInitSystem(), ObpDeleteNameCheck(), ObpLookupObjectName(), and ObSwapObjectNames().
PVOID ObpLookupDirectoryEntry (IN POBJECT_DIRECTORY Directory, IN PUNICODE_STRING Name, IN ULONG Attributes, IN BOOLEAN SearchShadow, OUT POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 822 of file obdir.c.
References _OBJECT_DIRECTORY_ENTRY::ChainLink, ExTryConvertPushLockSharedToExclusive(), FALSE, _OBJECT_DIRECTORY_ENTRY::HashValue, Index, _OBJECT_HEADER_NAME_INFO::Name, NOTHING, NULL, NUMBER_HASH_BUCKETS, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, _OBJECT_DIRECTORY_ENTRY::Object, OBJECT_HEADER_TO_NAME_INFO(), OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpGetShadowDirectory(), ObpLockDirectoryShared(), ObpLUIDDeviceMapsEnabled, ObpReferenceNameInfo(), ObpUnlockDirectory(), ObReferenceObject, PAGED_CODE, RtlEqualUnicodeString(), RtlUpcaseUnicodeChar(), and TRUE.
Referenced by ObCreateObjectType(), ObInitSystem(), ObpDeleteNameCheck(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), and ObSwapObjectNames().
NTSTATUS ObpLookupObjectName (IN HANDLE RootDirectoryHandle, IN PUNICODE_STRING ObjectName, IN ULONG Attributes, IN POBJECT_TYPE ObjectType, IN KPROCESSOR_MODE AccessMode, IN PVOID ParseContext OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, IN PVOID InsertObject OPTIONAL, IN OUT PACCESS_STATE AccessState, OUT POBP_LOOKUP_CONTEXT LookupContext, OUT PVOID * FoundObject)
Definition at line 1691 of file obdir.c.
References ALIGNEDNAME::Alignment, ARGUMENT_PRESENT, ASSERT, _OBJECT_HEADER::Body, _UNICODE_STRING::Buffer, DIRECTORY_CREATE_OBJECT, DIRECTORY_CREATE_SUBDIRECTORY, DIRECTORY_TRAVERSE, _DEVICE_MAP::DosDevicesDirectory, ExAllocatePoolWithTag, ExFreePool(), FALSE, _ULARGE_INTEGER::HighPart, IoFileObjectType, KernelMode, _UNICODE_STRING::Length, _ULARGE_INTEGER::LowPart, _UNICODE_STRING::MaximumLength, MmSectionObjectType, _OBJECT_HEADER_NAME_INFO::Name, NT_SUCCESS, NULL, ObCheckCreateObjectAccess(), ObDereferenceObject(), ObfDereferenceDeviceMap(), OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_INVALID_SESSION_ID, OBJ_MAX_REPARSE_ATTEMPTS, OBJ_NAME_PATH_SEPARATOR, OBJECT_HEADER_TO_NAME_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpCaseInsensitive, ObpCheckTraverseAccess(), ObpDirectoryObjectType, ObpDosDevicesShortName, ObpDosDevicesShortNamePrefix, ObpDosDevicesShortNameRoot, ObpEndTypeSpecificCallOut, ObpIncrPointerCount, ObpInitializeLookupContext(), ObpInsertDirectoryEntry(), ObpIsUnsecureName(), ObpLockLookupContext(), ObpLookupDirectoryEntry(), ObpParseSymbolicLink(), ObpReferenceDeviceMap(), ObpReleaseLookupContext(), ObpRootDirectoryObject, ObpSymbolicLinkObjectType, ObpValidateIrql, ObReferenceObject, ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PagedPool, _OBJECT_TYPE_INITIALIZER::ParseProcedure, PsGetCurrentProcessSessionId(), _ULARGE_INTEGER::QuadPart, RtlCopyMemory, SeCreateGlobalPrivilege, SeSinglePrivilegeCheck(), _OBJECT_DIRECTORY::SessionId, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_INVALID, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_PATH_NOT_FOUND, STATUS_OBJECT_PATH_SYNTAX_BAD, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE, STATUS_REPARSE_OBJECT, STATUS_SUCCESS, TOKEN_HAS_TRAVERSE_PRIVILEGE, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UserMode.
Referenced by ObInsertObject(), ObOpenObjectByName(), and ObReferenceObjectByName().
NTSTATUS ObpParseSymbolicLink (IN PVOID ParseObject, IN PVOID ObjectType, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE AccessMode, IN ULONG Attributes, IN OUT PUNICODE_STRING CompleteName, IN OUT PUNICODE_STRING RemainingName, IN OUT PVOID Context OPTIONAL, IN PSECURITY_QUALITY_OF_SERVICE SecurityQos OPTIONAL, OUT PVOID * Object)
Definition at line 503 of file oblink.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), _UNICODE_STRING::Length, _OBJECT_SYMBOLIC_LINK::LinkTarget, _OBJECT_SYMBOLIC_LINK::LinkTargetObject, _OBJECT_SYMBOLIC_LINK::LinkTargetRemaining, NT_SUCCESS, NULL, OB_NAMESPACE_POOL_TYPE, OBJ_NAME_PATH_SEPARATOR, ObReferenceObjectByPointer(), PAGED_CODE, RtlCopyMemory, RtlMoveMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NAME_TOO_LONG, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE, STATUS_REPARSE_OBJECT, UNICODE_NULL, and UNREFERENCED_PARAMETER.
Referenced by ObInitSystem(), and ObpLookupObjectName().
VOID ObpProcessRemoveObjectQueue (PVOID Parameter)
Definition at line 2562 of file obref.c.
References _OBJECT_HEADER::Body, InterlockedCompareExchangePointer, InterlockedExchangePointer, _OBJECT_HEADER::NextToFree, NULL, ObpRemoveObjectList, ObpRemoveObjectRoutine(), ObpTraceEnabled, ObpTraceNoDeregister, TRUE, and UNREFERENCED_PARAMETER.
Referenced by ObInitSystem().
NTSTATUS ObpQueryNameString (IN PVOID Object, OUT POBJECT_NAME_INFORMATION ObjectNameInfo, IN ULONG Length, OUT PULONG ReturnLength, IN KPROCESSOR_MODE Mode)
Definition at line 839 of file obquery.c.
References _UNICODE_STRING::Buffer, _OBJECT_HEADER_NAME_INFO::Directory, except, EXCEPTION_EXECUTE_HANDLER, FALSE, leave, _UNICODE_STRING::Length, MAXUSHORT, _OBJECT_HEADER_NAME_INFO::Name, NULL, ObDereferenceObject(), ObfReferenceObject(), OBJ_NAME_PATH_SEPARATOR, OBJECT_TO_OBJECT_HEADER, OBP_MISSING_NAME_LITERAL, OBP_MISSING_NAME_LITERAL_SIZE, ObpBeginTypeSpecificCallOut, ObpDereferenceNameInfo(), ObpEndTypeSpecificCallOut, ObpReferenceNameInfo(), ObpRootDirectoryObject, PAGED_CODE, _OBJECT_TYPE_INITIALIZER::QueryNameProcedure, RtlCopyMemory, RtlMoveMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NAME_TOO_LONG, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and UNICODE_NULL.
Referenced by NtQueryObject(), and ObQueryNameString().
PDEVICE_MAP ObpReferenceDeviceMap ()
Definition at line 1471 of file obdir.c.
References _EPROCESS::DeviceMap, FALSE, _LUID::HighPart, _LUID::LowPart, NT_SUCCESS, NULL, ObpLockDeviceMap, ObpLUIDDeviceMapsEnabled, ObpSetCurrentProcessDeviceMap(), ObpUnlockDeviceMap, ObSystemDeviceMap, PS_IS_THREAD_IMPERSONATING, PsDereferenceImpersonationToken, PsGetCurrentProcess(), PsGetCurrentThread(), PsReferenceImpersonationToken(), _DEVICE_MAP::ReferenceCount, RtlEqualLuid, SeGetLogonIdDeviceMap(), SeQueryAuthenticationIdToken(), Status, STATUS_NO_TOKEN, SYSTEM_LUID, and TRUE.
Referenced by ObpLookupObjectName(), and ObQueryDeviceMapInformation().
POBJECT_HEADER_NAME_INFO FORCEINLINE ObpReferenceNameInfo (IN POBJECT_HEADER ObjectHeader)
Definition at line 1070 of file obp.h.
References _OBJECT_HEADER_NAME_INFO::Directory, ExAcquireReleasePushLockExclusive(), _OBJECT_DIRECTORY::Lock, NULL, OBJECT_HEADER_TO_NAME_INFO(), OBP_NAME_LOCKED, ObpSafeInterlockedIncrementLong(), and _OBJECT_HEADER_NAME_INFO::QueryReferences.
Referenced by NtQueryObject(), ObInsertObject(), ObpCreateSymbolicLinkName(), ObpDeleteNameCheck(), ObpLookupDirectoryEntry(), ObpProcessDosDeviceSymbolicLink(), ObpQueryNameString(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), and ObSwapObjectNames().
NTSTATUS ObpReferenceProcessObjectByHandle (IN HANDLE Handle, IN PEPROCESS Process, IN PHANDLE_TABLE HandleTable, IN KPROCESSOR_MODE AccessMode, OUT PVOID * Object, OUT POBJECT_HANDLE_INFORMATION HandleInformation, OUT PACCESS_MASK AuditMask)
Definition at line 1355 of file obref.c.
References ASSERT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _OBJECT_HEADER::Body, DecodeKernelHandle, ExGetHandleInfo, ExMapHandleToPointer(), ExUnlockHandleTableEntry(), FLG_KERNEL_STACK_TRACE_DB, _ETHREAD::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KernelMode, NtCurrentProcess, NtCurrentThread, NtGlobalFlag, NULL, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpIncrPointerCount, ObpKernelHandleTable, ObpTranslateGrantedAccessIndex(), ObpValidateIrql, PsGetCurrentThread(), Status, STATUS_INVALID_HANDLE, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
Referenced by ObDuplicateObject().
PSECURITY_DESCRIPTOR ObpReferenceSecurityDescriptor (POBJECT_HEADER ObjectHeader)
Definition at line 564 of file obsdata.c.
References DbgBreakPoint(), ExFastRefAddAdditionalReferenceCounts(), ExFastReference(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefGetUnusedReferences(), _SECURITY_DESCRIPTOR_HEADER::FullHash, IF_OB_GLOBAL, InterlockedExchangeAdd(), InterlockedIncrement, NULL, ObpLockObjectShared, ObPrint, ObpUnlockObject, _SECURITY_DESCRIPTOR_HEADER::RefCount, RtlValidSecurityDescriptor(), SD_TO_SD_HEADER, and _OBJECT_HEADER::SecurityDescriptor.
Referenced by ObGetObjectSecurity(), ObQuerySecurityDescriptorInfo(), and ObSetSecurityDescriptorInfo().
VOID FORCEINLINE ObpReleaseLookupContext (IN POBP_LOOKUP_CONTEXT LookupContext)
Definition at line 1354 of file obp.h.
References FALSE, NULL, ObDereferenceObject(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), and ObpUnlockDirectory().
Referenced by ObCreateObjectType(), ObInitSystem(), ObInsertObject(), ObOpenObjectByName(), ObpCreateHandle(), ObpDeleteNameCheck(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), ObReferenceObjectByName(), and ObSwapObjectNames().
VOID ObpRemoveObjectRoutine (IN PVOID Object, IN BOOLEAN CalledOnWorkerThread)
Definition at line 2625 of file obref.c.
References _UNICODE_STRING::Buffer, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, DeleteSecurityDescriptor, ExFreePool(), _OBJECT_HEADER::Flags, IsListEmpty, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _OBJECT_HEADER_NAME_INFO::Name, NULL, OB_FLAG_DELETED_INLINE, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_NAME_INFO(), OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpEndTypeSpecificCallOut, ObpEnterObjectTypeMutex, ObpFreeObject(), ObpLeaveObjectTypeMutex, ObpValidateIrql, PAGED_CODE, RemoveEntryList(), _OBJECT_HEADER::SecurityDescriptor, _OBJECT_TYPE_INITIALIZER::SecurityProcedure, Status, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_HEADER_CREATOR_INFO::TypeList.
Referenced by ObfDereferenceObject(), and ObpProcessRemoveObjectQueue().
FORCEINLINE BOOLEAN ObpSafeInterlockedIncrement (IN OUT LONG_PTR volatile * lpValue)
Definition at line 940 of file obp.h.
References FALSE, ObpInterlockedCompareExchange, ReadForWriteAccess, and TRUE.
Referenced by ObReferenceObjectSafe().
FORCEINLINE BOOLEAN ObpSafeInterlockedIncrementLong (IN OUT LONG volatile * lpValue)
Definition at line 1006 of file obp.h.
References FALSE, InterlockedCompareExchange(), ReadForWriteAccess, and TRUE.
Referenced by ObpReferenceNameInfo().
VOID FORCEINLINE ObpUnlockAllObjects (IN POBJECT_TYPE ObjectType)
Definition at line 1433 of file obp.h.
References ExReleaseResourceLite(), KeLeaveCriticalRegion(), and OBJECT_LOCK_COUNT.
Referenced by ObSwapObjectNames().
VOID FORCEINLINE ObpUnlockDirectory (IN POBJECT_DIRECTORY Directory, IN POBP_LOOKUP_CONTEXT LockContext)
Definition at line 1261 of file obp.h.
References ExReleasePushLock(), KeLeaveCriticalRegion(), and OBP_LOCK_RELEASED_SIGNATURE.
Referenced by NtQueryDirectoryObject(), NtSetInformationObject(), ObpLookupDirectoryEntry(), and ObpReleaseLookupContext().
VOID ObpUnlockObjectDirectoryPath (IN POBJECT_DIRECTORY LockedDirectory)
NTSTATUS ObpValidateAccessMask (PACCESS_STATE AccessState)
Definition at line 1803 of file obse.c.
References ACCESS_SYSTEM_SECURITY, _SECURITY_DESCRIPTOR::Control, NULL, PAGED_CODE, _ACCESS_STATE::PreviouslyGrantedAccess, _ACCESS_STATE::RemainingDesiredAccess, SE_SACL_PRESENT, _ACCESS_STATE::SecurityDescriptor, and STATUS_SUCCESS.
Referenced by ObInsertObject(), and ObOpenObjectByName().
NTSTATUS ObpValidateDesiredAccess (IN ACCESS_MASK DesiredAccess)
Definition at line 3152 of file obhandle.c.
References STATUS_ACCESS_DENIED, and STATUS_SUCCESS.
Referenced by ObDuplicateObject().
Variable Documentation
ULONG ObpAccessProtectCloseBit
Definition at line 155 of file obinit.c.
Referenced by ObInitSystem(), and ObpSetHandleAttributes().
GENERAL_LOOKASIDE ObpCreateInfoLookasideList
Definition at line 25 of file obinit.c.
Referenced by ObInitSystem().
KEVENT ObpDefaultObject
Definition at line 105 of file obp.h.
Referenced by ObCreateObjectType(), and ObInitSystem().
KGUARDED_MUTEX ObpDeviceMapLock
Definition at line 119 of file obp.h.
Referenced by ObInitSystem().
POBJECT_TYPE ObpDeviceMapObjectType
Definition at line 428 of file obp.h.
POBJECT_TYPE ObpDirectoryObjectType
Definition at line 426 of file obp.h.
Referenced by NtCreateDirectoryObject(), NtOpenDirectoryObject(), NtQueryDirectoryObject(), NtSetInformationObject(), ObAssignSecurity(), ObInitSystem(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), ObSetDeviceMap(), ObSetDirectoryDeviceMap(), ObShutdownSystem(), and ObSwapObjectNames().
const UNICODE_STRING ObpDosDevicesShortName
Definition at line 210 of file obinit.c.
Referenced by ObpLookupObjectName(), and ObpProcessDosDeviceSymbolicLink().
const ALIGNEDNAME ObpDosDevicesShortNamePrefix
Definition at line 208 of file obinit.c.
Referenced by ObpLookupObjectName(), and ObpProcessDosDeviceSymbolicLink().
const ALIGNEDNAME ObpDosDevicesShortNameRoot
Definition at line 209 of file obinit.c.
Referenced by ObpLookupObjectName().
PHANDLE_TABLE ObpKernelHandleTable
Definition at line 462 of file obp.h.
Referenced by ObInitSystem(), ObpCloseHandle(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObQueryObjectAuditingByHandle(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle(), and ObSetHandleAttributes().
EX_PUSH_LOCK ObpLock
Definition at line 103 of file obp.h.
Referenced by ObInitSystem().
GENERAL_LOOKASIDE ObpNameBufferLookasideList
Definition at line 33 of file obinit.c.
Referenced by ObInitSystem().
POBJECT_TYPE ObpObjectTypes[OBP_MAX_DEFINED_OBJECT_TYPES]
Definition at line 264 of file obp.h.
Referenced by NtQueryObject(), and ObCreateObjectType().
PVOID ObpRemoveObjectList
Definition at line 107 of file obp.h.
Referenced by ObInitSystem(), ObpDeferObjectDeletion(), and ObpProcessRemoveObjectQueue().
WORK_QUEUE_ITEM ObpRemoveObjectWorkItem
Definition at line 106 of file obp.h.
Referenced by ObInitSystem(), and ObpDeferObjectDeletion().
POBJECT_DIRECTORY ObpRootDirectoryObject
Definition at line 429 of file obp.h.
Referenced by ObInitSystem(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), ObpQueryNameString(), and ObShutdownSystem().
POBJECT_TYPE ObpSymbolicLinkObjectType
Definition at line 427 of file obp.h.
Referenced by NtCreateSymbolicLinkObject(), NtOpenSymbolicLinkObject(), NtQueryObject(), NtQuerySymbolicLinkObject(), ObInitSystem(), ObInsertObject(), ObpDeleteNameCheck(), ObpLookupObjectName(), ObpProcessDosDeviceSymbolicLink(), ObReferenceObjectByPointer(), and ObShutdownSystem().
POBJECT_DIRECTORY ObpTypeDirectoryObject
Definition at line 430 of file obp.h.
Referenced by ObCreateObjectType(), ObInitSystem(), and ObShutdownSystem().
POBJECT_TYPE ObpTypeObjectType
Definition at line 425 of file obp.h.
Referenced by ObCreateObjectType(), ObGetObjectInformation(), ObInitSystem(), and ObShutdownSystem().
ERESOURCE SecurityDescriptorCacheLock
Definition at line 441 of file obp.h.