Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/mcaevent.h File Reference
mcaevent.h File Reference
Data Structures
struct MCECORRECTEDEVENT
Typedefs
typedef struct MCECORRECTEDEVENT * PMCECORRECTEDEVENT
typedef enum MCECORRECTEDTYPE * PMCECORRECTEDTYPE
Enumerations
enum {
CpuStateCheckCache = 0, CpuStateCheckTLB = 1, CpuStateCheckBus = 2, CpuStateCheckRegFile = 3,
CpuStateCheckMS = 4
}
enum MCECORRECTEDTYPE {
SingleBitEcc, CpuCache, CpuTlb, CpuBus,
CpuRegFile
}
Functions
NTSTATUS WmipConstructMCAErrorEvent (IN PMCA_EXCEPTION McaException, IN ULONG ErrorLogSize, IN OUT PWNODE_SINGLE_INSTANCE Wnode, IN OUT PMSMCAEvent_Header Header, IN OUT PUCHAR *RawPtr, IN OUT BOOLEAN *IsFatal)
NTSTATUS WmipFireOffWmiEvent (LPGUID Guid, ULONG DataSize, PVOID DataPtr)
Variables
ULONG WmipCoalesceCorrectedErrorInterval
ULONG WmipCorrectedEventlogCounter
ULONG WmipCorrectedMCECount
LIST_ENTRY WmipCorrectedMCEHead
ULONG WmipDisableMCAPopups
ULONG WmipMaxCorrectedMCEOutstanding
ULONG WmipSingleBitEccErrorThreshold
Typedef Documentation
typedef struct MCECORRECTEDEVENT * PMCECORRECTEDEVENT
typedef enum MCECORRECTEDTYPE * PMCECORRECTEDTYPE
Enumeration Type Documentation
anonymous enum
Enumerator
CpuStateCheckCache
CpuStateCheckTLB
CpuStateCheckBus
CpuStateCheckRegFile
CpuStateCheckMS
Definition at line 47 of file mcaevent.h.
enum MCECORRECTEDTYPE
Enumerator
SingleBitEcc
CpuCache
CpuTlb
CpuBus
CpuRegFile
Definition at line 14 of file mcaevent.h.
Function Documentation
NTSTATUS WmipConstructMCAErrorEvent (IN PMCA_EXCEPTION McaException, IN ULONG ErrorLogSize, IN OUT PWNODE_SINGLE_INSTANCE Wnode, IN OUT PMSMCAEvent_Header Header, IN OUT PUCHAR * RawPtr, IN OUT BOOLEAN * IsFatal)
Definition at line 69 of file mcaevent.c.
References _MSMCAEvent_BusError::Address, _MSMCAEvent_TLBError::Address, _MSMCAEvent_MemoryHierarchyError::Address, CPU_AMD, CPU_INTEL, FALSE, FIELD_OFFSET, HAL_MCA_RECORD, KeGetCurrentPrcb(), MCA_BUS_ERROR, MCA_BUS_TIMEOUT_ERROR, MCA_CODE_BUS_ERR_MASK, MCA_CODE_EXTERNAL_ERROR, MCA_CODE_FRC_ERROR, MCA_CODE_INTERNAL_TIMER_ERROR, MCA_CODE_MEM_HIERARCHY_ERR_MASK, MCA_CODE_MICROCODE_ROM_PARITY_ERROR, MCA_CODE_TLB_ERR_MASK, MCA_EXTERNAL_ERROR, MCA_FRC_ERROR, MCA_INTERNALTIMER_ERROR, MCA_MEMORYHIERARCHY_ERROR, MCA_MICROCODE_ROM_PARITY_ERROR, MCA_TLB_ERROR, _MSMCAEvent_BusError::MemOrIo, _MSMCAEvent_BusError::MemoryHierarchyLevel, _MSMCAEvent_TLBError::MemoryHierarchyLevel, _MSMCAEvent_MemoryHierarchyError::MemoryHierarchyLevel, PAGED_CODE, _MSMCAEvent_BusError::Participation, _MSMCAEvent_BusError::RawRecord, _MSMCAEvent_TLBError::RawRecord, _MSMCAEvent_MemoryHierarchyError::RawRecord, _MSMCAEvent_InvalidError::RawRecord, _MSMCAEvent_BusError::RequestType, _MSMCAEvent_MemoryHierarchyError::RequestType, _MSMCAEvent_BusError::Size, _MSMCAEvent_TLBError::Size, _MSMCAEvent_MemoryHierarchyError::Size, _MSMCAEvent_InvalidError::Size, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, _MSMCAEvent_TLBError::TransactionType, _MSMCAEvent_MemoryHierarchyError::TransactionType, _MSMCAEvent_BusError::Type, _MSMCAEvent_TLBError::Type, _MSMCAEvent_MemoryHierarchyError::Type, _MSMCAEvent_InvalidError::Type, WmipAssert, WmipConstructMCAErrorEventAMD(), WmipConstructMCAErrorEventIntel(), WmipMSMCAEvent_BusErrorGuid, WmipMSMCAEvent_InvalidErrGuid, WmipMSMCAEvent_MemoryHierarchyErrorGuid, and WmipMSMCAEvent_TLBErrorGuid.
Referenced by WmipGenerateMCAEventlog().
NTSTATUS WmipFireOffWmiEvent (LPGUID Guid, ULONG DataSize, PVOID DataPtr)
Definition at line 340 of file mca.c.
References _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, ExAllocatePoolWithTag, ExFreePool(), _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, IoWMIWriteEvent(), KeQuerySystemTime(), MCA_EVENT_INSTANCE_NAME, memcpy(), NonPagedPool, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, RtlCopyMemory, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, Status, STATUS_INSUFFICIENT_RESOURCES, _WNODE_HEADER::TimeStamp, WmipMCAPoolTag, WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipPollingDpcRoutine().
Variable Documentation
ULONG WmipCoalesceCorrectedErrorInterval
Definition at line 264 of file mca.c.
ULONG WmipCorrectedEventlogCounter
Definition at line 294 of file mca.c.
Referenced by WmipGenerateMCAEventlog(), and WmipRegisterMcaHandler().
ULONG WmipCorrectedMCECount
Definition at line 287 of file mca.c.
LIST_ENTRY WmipCorrectedMCEHead
Definition at line 286 of file mca.c.
ULONG WmipDisableMCAPopups
Definition at line 131 of file mca.c.
Referenced by WmipGenerateMCAEventlog().
ULONG WmipMaxCorrectedMCEOutstanding
Definition at line 281 of file mca.c.
ULONG WmipSingleBitEccErrorThreshold
Definition at line 272 of file mca.c.