Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/mm.h File Reference
mm.h File Reference
Data Structures
struct _MM_KERNEL_DUMP_CONTEXT
struct _MMPFNLIST
struct _PHYSICAL_MEMORY_DESCRIPTOR
struct _PHYSICAL_MEMORY_RANGE
struct _PHYSICAL_MEMORY_RUN
struct _READ_LIST
struct _UNLOADED_DRIVERS
Macros
#define ADDRESS_AND_SIZE_TO_SPAN_PAGES(Va, Size) ((ULONG)((((ULONG_PTR)(Va) & (PAGE_SIZE -1)) + (Size) + (PAGE_SIZE - 1)) >> PAGE_SHIFT))
#define BYTE_OFFSET(Va) ((ULONG)((LONG_PTR)(Va) & (PAGE_SIZE - 1)))
#define BYTES_TO_PAGES(Size)
#define COMPUTE_PAGES_SPANNED(Va, Size) ADDRESS_AND_SIZE_TO_SPAN_PAGES(Va,Size)
#define IS_SYSTEM_ADDRESS(VA) ((VA) >= MM_SYSTEM_RANGE_START)
#define MM_ALLOCATE_FROM_LOCAL_NODE_ONLY 0x00000002
#define MM_ALLOCATION_GRANULARITY ((ULONG)0x10000)
#define MM_DONT_ZERO_ALLOCATION 0x00000001
#define MM_FLUSH_ACQUIRE_FILE 0x1
#define MM_FLUSH_ASYNCHRONOUS 0x8
#define MM_FLUSH_FAIL_COLLISIONS 0x2
#define MM_FLUSH_IN_PARALLEL 0x4
#define MM_FLUSH_SEG_DEREF 0x80000000
#define MM_LOAD_IMAGE_AND_LOCKDOWN 0x2
#define MM_LOAD_IMAGE_IN_SESSION 0x1
#define MM_MAXIMUM_DISK_IO_SIZE (0x10000)
#define MM_MAXIMUM_READ_CLUSTER_SIZE (15)
#define MMDBG_COPY_CACHED 0x00000008
#define MMDBG_COPY_MAX_SIZE 8
#define MMDBG_COPY_PHYSICAL 0x00000002
#define MMDBG_COPY_UNCACHED 0x00000010
#define MMDBG_COPY_UNSAFE 0x00000004
#define MMDBG_COPY_WRITE 0x00000001
#define MMDBG_COPY_WRITE_COMBINED 0x00000020
#define MmDisablePageFaultClustering(SavedState)
#define MmEnablePageFaultClustering(SavedState)
#define MmEnoughMemoryForWrite()
#define MmGetMdlBaseVa(Mdl) ((Mdl)->StartVa)
#define MmGetMdlByteCount(Mdl) ((Mdl)->ByteCount)
#define MmGetMdlByteOffset(Mdl) ((Mdl)->ByteOffset)
#define MmGetMdlPfnArray(Mdl) ((PPFN_NUMBER)(Mdl + 1))
#define MmGetMdlVirtualAddress(Mdl) ((PVOID) ((PCHAR) ((Mdl)->StartVa) + (Mdl)->ByteOffset))
#define MmGetSystemAddressForMdl(MDL)
#define MmGetSystemAddressForMdlSafe(MDL, PRIORITY)
#define MmInitializeMdl(MemoryDescriptorList, BaseVa, Length)
#define MmIsRecursiveIoFault()
#define MmIsSessionLeaderProcess(Process) ((Process)->Vm.Flags.SessionLeader == 1)
#define MMNONPAGED_QUOTA_CHECK (256*1024)
#define MMNONPAGED_QUOTA_INCREASE (64*1024)
#define MMPAGED_QUOTA_CHECK (1*1024*1024)
#define MMPAGED_QUOTA_INCREASE (512*1024)
#define MmPrepareMdlForReuse(MDL)
#define MmResetPageFaultReadAhead(Thread, SavedState)
#define MmSavePageFaultReadAhead(Thread, SavedState)
#define MmSetPageFaultReadAhead(Thread, ReadAhead)
#define NUMBER_OF_PAGE_LISTS 8
#define PAGE_ALIGN(Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))
#define ROUND_TO_PAGES(Size) (((ULONG_PTR)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))
Typedefs
typedef struct _MM_KERNEL_DUMP_CONTEXT MM_KERNEL_DUMP_CONTEXT
typedef enum _MM_PAGE_PRIORITY MM_PAGE_PRIORITY
typedef enum _MM_SYSTEM_SIZE MM_SYSTEMSIZE
typedef enum _MMFLUSH_TYPE MMFLUSH_TYPE
typedef enum _MMLISTS MMLISTS
typedef struct _MMPFNLIST MMPFNLIST
typedef enum _MMSYSTEM_PTE_POOL_TYPE MMSYSTEM_PTE_POOL_TYPE
typedef VOID(* PBANKED_SECTION_ROUTINE) (IN ULONG ReadBank, IN ULONG WriteBank, IN PVOID Context)
typedef struct _PHYSICAL_MEMORY_DESCRIPTOR PHYSICAL_MEMORY_DESCRIPTOR
typedef struct _PHYSICAL_MEMORY_RANGE PHYSICAL_MEMORY_RANGE
typedef struct _PHYSICAL_MEMORY_RUN PHYSICAL_MEMORY_RUN
typedef NTSTATUS(* PMM_DLL_INITIALIZE) (IN PUNICODE_STRING RegistryPath)
typedef NTSTATUS(* PMM_DLL_UNLOAD) (VOID)
typedef NTSTATUS(* PMM_FREE_DUMP_RANGE) (IN struct _MM_KERNEL_DUMP_CONTEXT *Context, IN PVOID StartVa, IN PFN_NUMBER Pages, IN ULONG AddressFlags)
typedef struct _MM_KERNEL_DUMP_CONTEXT * PMM_KERNEL_DUMP_CONTEXT
typedef NTSTATUS(* PMM_SET_DUMP_RANGE) (IN struct _MM_KERNEL_DUMP_CONTEXT *Context, IN PVOID StartVa, IN PFN_NUMBER Pages, IN ULONG AddressFlags)
typedef MMPFNLIST * PMMPFNLIST
typedef struct _PHYSICAL_MEMORY_DESCRIPTOR * PPHYSICAL_MEMORY_DESCRIPTOR
typedef struct _PHYSICAL_MEMORY_RANGE * PPHYSICAL_MEMORY_RANGE
typedef struct _PHYSICAL_MEMORY_RUN * PPHYSICAL_MEMORY_RUN
typedef struct _READ_LIST * PREAD_LIST
typedef struct _UNLOADED_DRIVERS * PUNLOADED_DRIVERS
typedef struct _READ_LIST READ_LIST
typedef IN PVOID IN PVOID TrapInformation
typedef struct _UNLOADED_DRIVERS UNLOADED_DRIVERS
typedef IN PVOID VirtualAddress
Enumerations
enum _MM_PAGE_PRIORITY { LowPagePriority, NormalPagePriority = 16, HighPagePriority = 32 }
enum _MM_SYSTEM_SIZE { MmSmallSystem, MmMediumSystem, MmLargeSystem }
enum _MMFLUSH_TYPE { MmFlushForDelete, MmFlushForWrite }
enum _MMLISTS {
ZeroedPageList, FreePageList, StandbyPageList, ModifiedPageList,
ModifiedNoWritePageList, BadPageList, ActiveAndValid, TransitionPage
}
enum _MMSYSTEM_PTE_POOL_TYPE { SystemPteSpace, NonPagedPoolExpansion, MaximumPtePoolTypes }
Functions
NTKERNELAPI __bcount (NumberOfBytes) PVOID MmAllocateMappingAddress(__in SIZE_T NumberOfBytes
NTKERNELAPI __out_bcount (NumberOfBytes) PVOID MmMapIoSpace(__in PHYSICAL_ADDRESS PhysicalAddress
PVOID MiAllocatePoolPages (IN POOL_TYPE PoolType, IN SIZE_T SizeInBytes)
ULONG MiFreePoolPages (IN PVOID StartingAddress)
LOGICAL MiIsPoolLargeSession (IN PVOID VirtualAddress)
VOID MiMarkPoolLargeSession (IN PVOID VirtualAddress)
PVOID MiSessionPoolBigPageTable (VOID)
SIZE_T MiSessionPoolBigPageTableSize (VOID)
PGENERAL_LOOKASIDE MiSessionPoolLookaside (VOID)
PVOID MiSessionPoolMutex (VOID)
ULONG MiSessionPoolSmallLists (VOID)
PVOID MiSessionPoolTrackTable (VOID)
SIZE_T MiSessionPoolTrackTableSize (VOID)
PVOID MiSessionPoolVector (VOID)
NTSTATUS MmAccessFault (IN ULONG_PTR FaultStatus, IN PVOID VirtualAddress, IN KPROCESSOR_MODE PreviousMode, IN PVOID TrapInformation)
NTKERNELAPI NTSTATUS MmAddPhysicalMemory (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
NTKERNELAPI NTSTATUS MmAddPhysicalMemoryEx (IN PPHYSICAL_ADDRESS StartAddress, IN OUT PLARGE_INTEGER NumberOfBytes, IN ULONG Flags)
NTSTATUS MmAddVerifierEntry (IN PUNICODE_STRING ImageFileName)
NTKERNELAPI NTSTATUS MmAddVerifierThunks (__in_bcount(ThunkBufferSize) PVOID ThunkBuffer, __in ULONG ThunkBufferSize)
NTKERNELAPI NTSTATUS MmAdjustWorkingSetSize (__in SIZE_T WorkingSetMinimumInBytes, __in SIZE_T WorkingSetMaximumInBytes, __in ULONG SystemCache, __in BOOLEAN IncreaseOkay)
NTSTATUS MmAdjustWorkingSetSizeEx (IN SIZE_T WorkingSetMinimum, IN SIZE_T WorkingSetMaximum, IN ULONG SystemCache, IN BOOLEAN IncreaseOkay, IN ULONG Flags, OUT PBOOLEAN IncreaseRequested)
NTKERNELAPI NTSTATUS MmAdvanceMdl (__inout PMDL Mdl, __in ULONG NumberOfBytes)
PVOID MmAllocateIndependentPages (IN SIZE_T NumberOfBytes, IN ULONG NodeNumber)
NTKERNELAPI PMDL MmAllocatePagesForMdl (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes)
NTKERNELAPI PMDL MmAllocatePagesForMdlEx (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes, __in MEMORY_CACHING_TYPE CacheType, __in ULONG Flags)
PVOID MmAllocateSpecialPool (IN SIZE_T NumberOfBytes, IN ULONG Tag, IN POOL_TYPE Type, IN ULONG SpecialPoolType)
LOGICAL MmAreMdlPagesLocked (IN PMDL MemoryDescriptorList)
LOGICAL MmAssignProcessToJob (IN PEPROCESS Process)
NTSTATUS MmAttachSession (IN PVOID OpaqueSession, OUT PRKAPC_STATE ApcState)
SIZE_T MmAvailablePoolInPages (IN POOL_TYPE PoolType)
NTKERNELAPI VOID MmBuildMdlForNonPagedPool (__inout PMDL MemoryDescriptorList)
NTSTATUS MmCallDllInitialize (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry, IN PLIST_ENTRY ModuleListHead)
NTKERNELAPI BOOLEAN MmCanFileBeTruncated (__in PSECTION_OBJECT_POINTERS SectionPointer, __in_opt PLARGE_INTEGER NewFileSize)
LOGICAL MmCanThreadFault (VOID)
BOOLEAN MmCheckCachedPageState (IN PVOID Address, IN BOOLEAN SetToZero)
BOOLEAN MmCheckForSafeExecution (IN PVOID InstructionPointer, IN PVOID StackPointer, IN PVOID BranchTarget, IN BOOLEAN PermitStackExecution)
NTSTATUS MmCheckSystemImage (IN HANDLE ImageFileHandle, IN LOGICAL PurgeSection)
VOID MmCleanProcessAddressSpace (IN PEPROCESS Process)
NTKERNELAPI NTSTATUS MmCommitSessionMappedView (__in_bcount(ViewSize) PVOID MappedAddress, __in SIZE_T ViewSize)
NTSTATUS MmCopyToCachedPage (IN PVOID Address, IN PVOID UserBuffer, IN ULONG Offset, IN SIZE_T CountInBytes, IN LOGICAL ExposeZeroPageOk)
NTSTATUS MmCopyVirtualMemory (IN PEPROCESS FromProcess, IN CONST VOID *FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesCopied)
PVOID MmCreateKernelStack (BOOLEAN LargeStack, UCHAR Processor)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI PMDL MmCreateMdl (__in_opt PMDL MemoryDescriptorList, __in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
NTKERNELAPI NTSTATUS MmCreateMirror (VOID)
NTSTATUS MmCreatePeb (IN PEPROCESS TargetProcess, IN PINITIAL_PEB InitialPeb, OUT PPEB *Base)
BOOLEAN MmCreateProcessAddressSpace (IN ULONG MinimumWorkingSetSize, IN PEPROCESS NewProcess, OUT PULONG_PTR DirectoryTableBase)
NTKERNELAPI NTSTATUS MmCreateSection (__deref_out PVOID *SectionObject, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in PLARGE_INTEGER InputMaximumSize, __in ULONG SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle, __in_opt PFILE_OBJECT FileObject)
NTSTATUS MmCreateTeb (IN PEPROCESS TargetProcess, IN PINITIAL_TEB InitialTeb, IN PCLIENT_ID ClientId, OUT PTEB *Base)
NTSTATUS MmDbgCopyMemory (IN ULONG64 UntrustedAddress, IN PVOID Buffer, IN ULONG Size, IN ULONG Flags)
LOGICAL MmDbgIsLowMemOk (IN PFN_NUMBER PageFrameIndex, OUT PPFN_NUMBER NextPageFrameIndex, IN OUT PULONG CorruptionOffset)
VOID MmDeleteKernelStack (IN PVOID PointerKernelStack, IN BOOLEAN LargeStack)
VOID MmDeleteProcessAddressSpace (IN PEPROCESS Process)
VOID MmDeleteTeb (IN PEPROCESS TargetProcess, IN PVOID TebBase)
NTSTATUS MmDetachSession (IN PVOID OpaqueSession, IN PRKAPC_STATE ApcState)
POOL_TYPE MmDeterminePoolType (IN PVOID VirtualAddress)
NTKERNELAPI BOOLEAN MmDisableModifiedWriteOfSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
ULONG MmDoesFileHaveUserWritableReferences (IN PSECTION_OBJECT_POINTERS SectionPointer)
VOID MmEmptyAllWorkingSets (VOID)
BOOLEAN MmEnableModifiedWriteOfSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer)
VOID MmEnablePAT (VOID)
NTSTATUS MmEnforceWorkingSetLimit (IN PEPROCESS Process, IN ULONG Flags)
NTSTATUS MmExtendSection (IN PVOID SectionToExtend, IN OUT PLARGE_INTEGER NewSectionSize, IN ULONG IgnoreFileSizeChecking)
NTKERNELAPI BOOLEAN MmFlushImageSection (__in PSECTION_OBJECT_POINTERS SectionPointer, __in MMFLUSH_TYPE FlushType)
NTSTATUS MmFlushSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset OPTIONAL, IN SIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus, IN ULONG Flags)
NTSTATUS MmFlushVirtualMemory (IN PEPROCESS Process, IN OUT PVOID *BaseAddress, IN OUT PSIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI BOOLEAN MmForceSectionClosed (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN DelayClose)
NTKERNELAPI VOID MmFreeContiguousMemory (__in PVOID BaseAddress)
NTKERNELAPI VOID MmFreeContiguousMemorySpecifyCache (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in MEMORY_CACHING_TYPE CacheType)
VOID MmFreeDriverInitialization (IN PVOID Section)
VOID MmFreeIndependentPages (IN PVOID VirtualAddress, IN SIZE_T NumberOfBytes)
VOID MmFreeLoaderBlock (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTKERNELAPI VOID MmFreeMappingAddress (__in PVOID BaseAddress, __in ULONG PoolTag)
NTKERNELAPI VOID MmFreeNonCachedMemory (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
NTKERNELAPI VOID MmFreePagesFromMdl (__in PMDL MemoryDescriptorList)
VOID MmFreeSpecialPool (IN PVOID P)
NTKERNELAPI ULONG MmGatherMemoryForHibernate (IN PMDL Mdl, IN BOOLEAN Wait)
PFN_NUMBER MmGetDirectoryFrameFromProcess (IN PEPROCESS Process)
NTSTATUS MmGetExecuteOptions (IN PULONG ExecuteOptions)
NTSTATUS MmGetFileNameForAddress (IN PVOID ProcessVa, OUT PUNICODE_STRING FileName)
NTSTATUS MmGetFileNameForSection (IN PVOID SectionObject, OUT POBJECT_NAME_INFORMATION *FileNameInfo)
PFILE_OBJECT MmGetFileObjectForSection (IN PVOID Section)
VOID MmGetImageInformation (OUT PSECTION_IMAGE_INFORMATION Imageinformation)
VOID MmGetKernelDumpRange (IN PMM_KERNEL_DUMP_CONTEXT Callback)
PVOID MmGetNextSession (IN PVOID OpaqueSession)
ULONG MmGetNumberOfFreeSystemPtes (VOID)
NTSTATUS MmGetPageFileInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTKERNELAPI PHYSICAL_ADDRESS MmGetPhysicalAddress (__in PVOID BaseAddress)
NTKERNELAPI PPHYSICAL_MEMORY_RANGE MmGetPhysicalMemoryRanges (VOID)
PVOID MmGetPreviousSession (IN PVOID OpaqueSession)
NTSTATUS MmGetSectionRange (IN PVOID AddressWithinSection, OUT PVOID *StartingSectionAddress, OUT PULONG SizeofSection)
PVOID MmGetSessionById (IN ULONG SessionId)
ULONG MmGetSessionId (IN PEPROCESS Process)
ULONG MmGetSessionIdEx (IN PEPROCESS Process)
LCID MmGetSessionLocaleId (VOID)
NTSTATUS MmGetSessionMappedViewInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length, IN PULONG SessionId OPTIONAL)
ULONG MmGetSizeOfBigPoolAllocation (IN PVOID StartingAddress)
HANDLE MmGetSystemPageFile (VOID)
NTKERNELAPI PVOID MmGetSystemRoutineAddress (__in PUNICODE_STRING SystemRoutineName)
NTSTATUS MmGetVerifierInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTKERNELAPI PVOID MmGetVirtualForPhysical (__in PHYSICAL_ADDRESS PhysicalAddress)
NTKERNELAPI NTSTATUS MmGrowKernelStack (__in PVOID CurrentStack)
NTKERNELAPI NTSTATUS MmGrowKernelStackEx (__in PVOID CurrentStack, __in SIZE_T CommitSize)
VOID MmHibernateInformation (IN PVOID MemoryMap, OUT PULONG_PTR HiberVa, OUT PPHYSICAL_ADDRESS HiberPte)
NTSTATUS MmHotPatchRoutine (PSYSTEM_HOTPATCH_CODE_INFORMATION RemoteInfo)
NTSTATUS MmIdentifyPhysicalMemory (VOID)
NTSTATUS MmInitializeHandBuiltProcess (IN PEPROCESS Process, OUT PULONG_PTR DirectoryTableBase)
NTSTATUS MmInitializeHandBuiltProcess2 (IN PEPROCESS Process)
PPHYSICAL_MEMORY_DESCRIPTOR MmInitializeMemoryLimits (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PBOOLEAN IncludedType, IN OUT PPHYSICAL_MEMORY_DESCRIPTOR Memory OPTIONAL)
NTSTATUS MmInitializeProcessAddressSpace (IN PEPROCESS ProcessToInitialize, IN PEPROCESS ProcessToClone OPTIONAL, IN PVOID SectionToMap OPTIONAL, IN OUT PULONG CreateFlags, OUT POBJECT_NAME_INFORMATION *AuditName OPTIONAL)
BOOLEAN MmInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID MmInPageKernelStack (IN PKTHREAD Thread)
VOID MmInSwapProcess (IN PKPROCESS Process)
NTKERNELAPI BOOLEAN MmIsAddressValid (__in PVOID VirtualAddress)
NTKERNELAPI LOGICAL MmIsDriverVerifying (__in struct _DRIVER_OBJECT *DriverObject)
LOGICAL MmIsFileObjectAPagingFile (IN PFILE_OBJECT FileObject)
NTKERNELAPI LOGICAL MmIsIoSpaceActive (__in PHYSICAL_ADDRESS StartAddress, __in SIZE_T NumberOfBytes)
LOGICAL MmIsMemoryAvailable (IN PFN_NUMBER PagesDesired)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI BOOLEAN MmIsNonPagedSystemAddressValid (__in PVOID VirtualAddress)
LOGICAL MmIsSessionAddress (IN PVOID VirtualAddress)
LOGICAL MmIsSpecialPoolAddress (IN PVOID VirtualAddress)
LOGICAL MmIsSpecialPoolAddressFree (IN PVOID VirtualAddress)
LOGICAL MmIsSystemAddressLocked (IN PVOID VirtualAddress)
NTKERNELAPI BOOLEAN MmIsThisAnNtAsSystem (VOID)
NTKERNELAPI NTSTATUS MmIsVerifierEnabled (__out PULONG VerifierFlags)
NTSTATUS MmLoadSystemImage (IN PUNICODE_STRING ImageFileName, IN PUNICODE_STRING NamePrefix OPTIONAL, IN PUNICODE_STRING LoadedBaseName OPTIONAL, IN ULONG LoadFlags, OUT PVOID *Section, OUT PVOID *ImageBaseAddress)
PUNICODE_STRING MmLocateUnloadedDriver (IN PVOID VirtualAddress)
NTSTATUS MmLockAndCopyMemory (IN PSYSTEM_HOTPATCH_CODE_INFORMATION PatchInfo, IN KPROCESSOR_MODE ProbeMode)
NTKERNELAPI PVOID MmLockPageableDataSection (__in PVOID AddressWithinSection)
NTKERNELAPI VOID MmLockPageableSectionByHandle (__in PVOID ImageSectionHandle)
NTKERNELAPI VOID MmLockPagedPool (IN PVOID Address, IN SIZE_T Size)
VOID MmMakeKernelResourceSectionWritable (VOID)
NTKERNELAPI PVOID MmMapLockedPages (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode)
NTKERNELAPI PVOID MmMapLockedPagesSpecifyCache (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in MEMORY_CACHING_TYPE CacheType, __in_opt PVOID RequestedAddress, __in ULONG BugCheckOnFailure, __in MM_PAGE_PRIORITY Priority)
NTKERNELAPI PVOID MmMapLockedPagesWithReservedMapping (__in PVOID MappingAddress, __in ULONG PoolTag, __in PMDL MemoryDescriptorList, __in MEMORY_CACHING_TYPE CacheType)
NTKERNELAPI VOID MmMapMemoryDumpMdl (__inout PMDL MemoryDumpMdl)
NTKERNELAPI NTSTATUS MmMapUserAddressesToPage (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in PVOID PageAddress)
NTKERNELAPI NTSTATUS MmMapViewInSessionSpace (__in PVOID Section, __deref_inout_bcount(*ViewSize) PVOID *MappedBase, __inout PSIZE_T ViewSize)
NTSTATUS MmMapViewInSystemCache (IN PVOID SectionToMap, OUT PVOID *CapturedBase, IN OUT PLARGE_INTEGER SectionOffset, IN OUT PULONG CapturedViewSize)
NTKERNELAPI NTSTATUS MmMapViewInSystemSpace (__in PVOID Section, __deref_inout_bcount(*ViewSize) PVOID *MappedBase, __inout PSIZE_T ViewSize)
NTKERNELAPI NTSTATUS MmMapViewOfSection (__in PVOID SectionToMap, __in PEPROCESS Process, __deref_inout_bcount(*CapturedViewSize) PVOID *CapturedBase, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout PLARGE_INTEGER SectionOffset, __inout PSIZE_T CapturedViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in ULONG Win32Protect)
NTKERNELAPI NTSTATUS MmMarkPhysicalMemoryAsBad (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
NTKERNELAPI NTSTATUS MmMarkPhysicalMemoryAsGood (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
LOGICAL MmMemoryIsLow (VOID)
NTSTATUS MmMemoryUsage (IN PVOID Buffer, IN ULONG Size, IN ULONG Type, OUT PULONG Length)
VOID MmOutPageKernelStack (IN PKTHREAD Thread)
VOID MmOutSwapProcess (IN PKPROCESS Process)
NTKERNELAPI PVOID MmPageEntireDriver (__in PVOID AddressWithinSection)
NTSTATUS MmPerfSnapShotValidPhysicalMemory (VOID)
PFILE_OBJECT * MmPerfUnusedSegmentsEnumerate (VOID)
PFILE_OBJECT * MmPerfVadTreeWalk (PEPROCESS Process)
LOGICAL MmPrefetchForCacheManager (IN PFILE_OBJECT FileObject, IN LARGE_INTEGER SectionOffset, IN SIZE_T NumberOfBytes)
NTKERNELAPI NTSTATUS MmPrefetchPages (__in ULONG NumberOfLists, __in_ecount(NumberOfLists) PREAD_LIST *ReadLists)
NTSTATUS MmPrefetchPagesIntoLockedMdl (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN SIZE_T Length, OUT PMDL *MdlOut)
NTKERNELAPI VOID MmProbeAndLockPages (__inout PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
NTKERNELAPI VOID MmProbeAndLockProcessPages (__inout PMDL MemoryDescriptorList, __in PEPROCESS Process, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
NTKERNELAPI VOID MmProbeAndLockSelectedPages (__inout PMDL MemoryDescriptorList, __in PFILE_SEGMENT_ELEMENT PagedSegmentArray, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
NTKERNELAPI NTSTATUS MmProtectMdlSystemAddress (__in PMDL MemoryDescriptorList, __in ULONG NewProtect)
LOGICAL MmProtectSpecialPool (IN PVOID VirtualAddress, IN ULONG NewProtect)
BOOLEAN MmPurgeSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset OPTIONAL, IN SIZE_T RegionSize, IN ULONG IgnoreCacheViews)
VOID MmPurgeWorkingSet (IN PEPROCESS Process, IN PVOID BaseAddress, IN SIZE_T RegionSize)
SIZE_T MmQuerySpecialPoolBlockSize (IN PVOID P)
VOID MmQuerySystemCacheWorkingSetInformation (OUT PSYSTEM_FILECACHE_INFORMATION Info)
NTKERNELAPI MM_SYSTEMSIZE MmQuerySystemSize (VOID)
NTSTATUS MmQueryWorkingSetInformation (IN PSIZE_T PeakWorkingSetSize, IN PSIZE_T WorkingSetSize, IN PSIZE_T MinimumWorkingSetSize, IN PSIZE_T MaximumWorkingSetSize, IN PULONG HardEnforcementFlags)
NTSTATUS MmQuitNextSession (IN PVOID OpaqueSession)
BOOLEAN MmRaisePoolQuota (IN POOL_TYPE PoolType, IN SIZE_T OldQuotaLimit, OUT PSIZE_T NewQuotaLimit)
VOID MmReleaseDumpAddresses (IN PFN_NUMBER Pages)
NTKERNELAPI NTSTATUS MmRemovePhysicalMemory (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
NTKERNELAPI NTSTATUS MmRemovePhysicalMemoryEx (IN PPHYSICAL_ADDRESS StartAddress, IN OUT PLARGE_INTEGER NumberOfBytes, IN ULONG Flags)
NTSTATUS MmRemoveVerifierEntry (IN PUNICODE_STRING ImageFileName)
NTKERNELAPI VOID MmResetDriverPaging (__in PVOID AddressWithinSection)
LOGICAL MmResourcesAvailable (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN EX_POOL_PRIORITY Priority)
NTKERNELAPI VOID MmReturnMemoryForHibernate (IN PMDL Mdl)
VOID MmReturnPoolQuota (IN POOL_TYPE PoolType, IN SIZE_T ReturnedQuota)
NTKERNELAPI HANDLE MmSecureVirtualMemory (__in_bcount(Size) PVOID Address, __in SIZE_T Size, __in ULONG ProbeMode)
NTSTATUS MmSessionCreate (OUT PULONG SessionId)
NTSTATUS MmSessionDelete (IN ULONG SessionId)
VOID MmSessionSetUnloadAddress (IN PDRIVER_OBJECT pWin32KDevice)
NTKERNELAPI BOOLEAN MmSetAddressRangeModified (__in_bcount(Length) PVOID Address, __in SIZE_T Length)
NTKERNELAPI NTSTATUS MmSetBankedSection (__in HANDLE ProcessHandle, __in_bcount(BankLength) PVOID VirtualAddress, __in ULONG BankLength, __in BOOLEAN ReadWriteBank, __in PBANKED_SECTION_ROUTINE BankRoutine, __in PVOID Context)
NTSTATUS MmSetExecuteOptions (IN ULONG ExecuteOptions)
VOID MmSetMemoryPriorityProcess (IN PEPROCESS Process, IN UCHAR MemoryPriority)
NTKERNELAPI VOID FASTCALL MmSetPageFaultNotifyRoutine (IN PPAGE_FAULT_NOTIFY_ROUTINE NotifyRoutine)
NTKERNELAPI BOOLEAN MmSetPageProtection (__in_bcount(NumberOfBytes) PVOID VirtualAddress, __in SIZE_T NumberOfBytes, __in ULONG NewProtect)
PFN_NUMBER MmSetPhysicalPagesLimit (IN PFN_NUMBER NewPhysicalPagesLimit)
VOID MmSetSessionLocaleId (IN LCID LocaleId)
NTSTATUS MmSetVerifierInformation (IN OUT PVOID SystemInformation, IN ULONG SystemInformationLength)
BOOLEAN MmShutdownSystem (IN ULONG)
NTKERNELAPI SIZE_T MmSizeOfMdl (__in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
ULONG MmSizeOfTriageInformation (VOID)
ULONG MmSizeOfUnloadedDriverInformation (VOID)
NTKERNELAPI LOGICAL MmTrimAllSystemPageableMemory (__in LOGICAL PurgeTransition)
NTSTATUS MmUnloadSystemImage (IN PVOID Section)
VOID MmUnlockCachedPage (IN PVOID AddressInCache)
NTKERNELAPI VOID MmUnlockPageableImageSection (__in PVOID ImageSectionHandle)
NTKERNELAPI VOID MmUnlockPagedPool (IN PVOID Address, IN SIZE_T Size)
NTKERNELAPI VOID MmUnlockPages (__inout PMDL MemoryDescriptorList)
NTKERNELAPI VOID MmUnmapIoSpace (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
NTKERNELAPI VOID MmUnmapLockedPages (__in PVOID BaseAddress, __in PMDL MemoryDescriptorList)
NTKERNELAPI VOID MmUnmapReservedMapping (IN PVOID BaseAddress, IN ULONG PoolTag, IN PMDL MemoryDescriptorList)
NTKERNELAPI VOID MmUnmapVideoDisplay (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
NTKERNELAPI NTSTATUS MmUnmapViewInSessionSpace (__in PVOID MappedBase)
VOID MmUnmapViewInSystemCache (IN PVOID BaseAddress, IN PVOID SectionToUnmap, IN ULONG AddToFront)
NTKERNELAPI NTSTATUS MmUnmapViewInSystemSpace (__in PVOID MappedBase)
NTKERNELAPI NTSTATUS MmUnmapViewOfSection (__in PEPROCESS Process, __in PVOID BaseAddress)
NTKERNELAPI VOID MmUnsecureVirtualMemory (__in HANDLE SecureHandle)
LOGICAL MmUpdateMdlTracker (IN PMDL MemoryDescriptorList, IN PVOID CallingAddress, IN PVOID CallersCaller)
LOGICAL MmUseSpecialPool (IN SIZE_T NumberOfBytes, IN ULONG Tag)
BOOLEAN MmVerifyImageIsOkForMpUse (IN PVOID BaseAddress)
VOID MmWorkingSetManager (VOID)
VOID MmWriteTriageInformation (IN PVOID)
VOID MmWriteUnloadedDriverInformation (IN PVOID)
VOID MmZeroPageThread (VOID)
VOID VerifierFreeTrackedPool (IN PVOID VirtualAddress, IN SIZE_T ChargedBytes, IN LOGICAL CheckType, IN LOGICAL SpecialPool)
typedef VOID (FASTCALL *PPAGE_FAULT_NOTIFY_ROUTINE)(IN NTSTATUS Status
Variables
NTKERNELAPI __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS BoundaryAddressMultiple
NTKERNELAPI __in SIZE_T __in MEMORY_CACHING_TYPE CacheType
NTKERNELAPI __in PHYSICAL_ADDRESS HighestAcceptableAddress
NTKERNELAPI __in PHYSICAL_ADDRESS LowestAcceptableAddress
BOOLEAN Mm64BitPhysicalAddress
PFN_NUMBER MmAvailablePages
PFN_NUMBER MmHighestPhysicalPage
PFN_NUMBER MmLowestPhysicalPage
MMPFNLIST MmModifiedPageListHead
ULONG MmNumberOfColors
PFN_COUNT MmNumberOfPhysicalPages
ULONG MmPaeErrMask
ULONGLONG MmPaeMask
SIZE_T MmPeakCommitment
PPHYSICAL_MEMORY_DESCRIPTOR MmPhysicalMemoryBlock
ULONG MmProductType
ULONG MmReadClusterSize
ULONG MmSecondaryColorMask
POBJECT_TYPE MmSectionObjectType
ULONG_PTR MmSizeOfSystemCacheInPages
MMSUPPORT MmSystemCacheWs
PFN_NUMBER MmThrottleBottom
PFN_NUMBER MmThrottleTop
SIZE_T MmTotalCommitLimit
SIZE_T MmTotalCommittedPages
ULONG MmTotalFreeSystemPtes [MaximumPtePoolTypes]
ULONG_PTR MmVirtualBias
KEVENT MmWorkingSetManagerEvent
NTKERNELAPI __in SIZE_T NumberOfBytes
NTKERNELAPI __in ULONG PoolTag
Macro Definition Documentation
#define ADDRESS_AND_SIZE_TO_SPAN_PAGES (Va, Size) ((ULONG)((((ULONG_PTR)(Va) & (PAGE_SIZE -1)) + (Size) + (PAGE_SIZE - 1)) >> PAGE_SHIFT))
Definition at line 217 of file mm.h.
Referenced by __bcount(), __out_bcount(), CcCopyRead(), CcFastCopyRead(), CcMapAndRead(), CcMapData(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), CcZeroData(), FsRtlCopyRead(), IoAllocateMdl(), IoBuildPartialMdl(), Ki386BuildIdentityBuffer(), KiInvokeBugCheckEntryCallbacks(), MiAllocatePagesForMdl(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiInitializeSystemCache(), MiInsertPteTracker(), MiIsProbeActive(), MiMapLockedPagesInUserSpace(), MiUnmapLockedPagesInUserSpace(), MmAdvanceMdl(), MmAreMdlPagesLocked(), MmBuildMdlForNonPagedPool(), MmFreeNonCachedMemory(), MmFreePagesFromMdl(), MmIsIoSpaceActive(), MmMapLockedPagesSpecifyCache(), MmMapLockedPagesWithReservedMapping(), MmProbeAndLockPages(), MmProtectMdlSystemAddress(), MmSizeOfMdl(), MmUnlockPages(), MmUnmapIoSpace(), MmUnmapLockedPages(), and MmUnmapReservedMapping().
#define BYTE_OFFSET (Va) ((ULONG)((LONG_PTR)(Va) & (PAGE_SIZE - 1)))
Definition at line 166 of file mm.h.
Referenced by __bcount(), __out_bcount(), ExFreePoolSanityChecks(), IoBuildPartialMdl(), MiAllocatePagesForMdl(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiCloneProcessAddressSpace(), MiComputeInitialLargePage(), MiCreateImageFileMap(), MiDispatchFault(), MiGatherMappedPages(), MiInitializeWorkingSetList(), MiInitMachineDependent(), MiInsertPageInFreeList(), MiMapLockedPagesInUserSpace(), MiMapWithLargePages(), MiOutPageSingleKernelStack(), MiRemoveWorkingSetPages(), MiResolvePageFileFault(), MiSessionWideReserveImageAddress(), MiShareSessionImage(), MiUnmapLargePages(), MiWaitForInPageComplete(), MmAdvanceMdl(), MmFlushSection(), MmGetPhysicalAddress(), MmGetVirtualForPhysical(), and MmPurgeSection().
#define BYTES_TO_PAGES (Size)
Value:
(((Size) >> PAGE_SHIFT) + \
                               (((Size) & (PAGE_SIZE - 1)) != 0))
Definition at line 141 of file mm.h.
Referenced by __bcount(), __out_bcount(), ExInsertPoolTag(), MiAllocateContiguousMemory(), MiAllocateLargePages(), MiAllocatePoolPages(), MiBuildPagedPool(), MiCalculatePageCommitment(), MiCcPutPagesInTransition(), MiCreateImageFileMap(), MiCreatePebOrTeb(), MiFreePoolPages(), MiGatherMappedPages(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiInitializeNonPagedPool(), MiInitMachineDependent(), MiMapViewInSystemSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiWriteProtectSystemImage(), MmAllocateIndependentPages(), MmCreateKernelStack(), MmDeleteKernelStack(), MmFreeIndependentPages(), MmFreeNonCachedMemory(), MmGetSizeOfBigPoolAllocation(), MmMapMemoryDumpMdl(), MmMapViewInSystemCache(), MmProbeAndLockSelectedPages(), MmResourcesAvailable(), MmSetPageProtection(), NtAllocateVirtualMemory(), NtReadFileScatter(), and NtWriteFileGather().
#define COMPUTE_PAGES_SPANNED (Va, Size) ADDRESS_AND_SIZE_TO_SPAN_PAGES(Va,Size)
Definition at line 224 of file mm.h.
#define IS_SYSTEM_ADDRESS (VA) ((VA) >= MM_SYSTEM_RANGE_START)
Definition at line 251 of file mm.h.
Referenced by KeBugCheck2(), MmIsSystemAddressLocked(), and RtlWalkFrameChain().
#define MM_ALLOCATE_FROM_LOCAL_NODE_ONLY 0x00000002
Definition at line 1912 of file mm.h.
Referenced by MiAllocatePagesForMdl(), and MmAllocatePagesForMdlEx().
#define MM_ALLOCATION_GRANULARITY ((ULONG)0x10000)
Definition at line 54 of file mm.h.
Referenced by ExpGetSystemBasicInformation().
#define MM_DONT_ZERO_ALLOCATION 0x00000001
Definition at line 1911 of file mm.h.
Referenced by MiAllocatePagesForMdl(), and MmAllocatePagesForMdlEx().
#define MM_FLUSH_ACQUIRE_FILE 0x1
Definition at line 1547 of file mm.h.
Referenced by CcFlushCache(), CcMapAndCopy(), CcMdlWriteComplete2(), CcUnpinRepinnedBcb(), and MmFlushSection().
#define MM_FLUSH_ASYNCHRONOUS 0x8
Definition at line 1551 of file mm.h.
Referenced by MiFlushSectionInternal(), and MmFlushVirtualMemory().
#define MM_FLUSH_FAIL_COLLISIONS 0x2
Definition at line 1548 of file mm.h.
Referenced by CcFlushCache(), MiFlushSectionInternal(), and MiRemoveUnusedSegments().
#define MM_FLUSH_IN_PARALLEL 0x4
Definition at line 1550 of file mm.h.
Referenced by MiFlushSectionInternal(), and MiRemoveUnusedSegments().
#define MM_FLUSH_SEG_DEREF 0x80000000
Definition at line 1553 of file mm.h.
Referenced by MiFlushSectionInternal(), and MiRemoveUnusedSegments().
#define MM_LOAD_IMAGE_AND_LOCKDOWN 0x2
Definition at line 1018 of file mm.h.
Referenced by MmLoadSystemImage().
#define MM_LOAD_IMAGE_IN_SESSION 0x1
Definition at line 1017 of file mm.h.
Referenced by MmLoadSystemImage(), and NtSetSystemInformation().
#define MM_MAXIMUM_DISK_IO_SIZE (0x10000)
Definition at line 91 of file mm.h.
Referenced by MiFlushSectionInternal().
#define MM_MAXIMUM_READ_CLUSTER_SIZE (15)
Definition at line 60 of file mm.h.
Referenced by MiCcPutPagesInTransition(), MiResolveMappedFileFault(), and MiResolvePageFileFault().
#define MMDBG_COPY_CACHED 0x00000008
Definition at line 1642 of file mm.h.
#define MMDBG_COPY_MAX_SIZE 8
Definition at line 1646 of file mm.h.
#define MMDBG_COPY_PHYSICAL 0x00000002
Definition at line 1640 of file mm.h.
#define MMDBG_COPY_UNCACHED 0x00000010
Definition at line 1643 of file mm.h.
#define MMDBG_COPY_UNSAFE 0x00000004
Definition at line 1641 of file mm.h.
Referenced by KiOpSingleProcCopy().
#define MMDBG_COPY_WRITE 0x00000001
Definition at line 1639 of file mm.h.
Referenced by KiOpSingleProcCopy().
#define MMDBG_COPY_WRITE_COMBINED 0x00000020
Definition at line 1644 of file mm.h.
#define MmDisablePageFaultClustering (SavedState)
Value:
{                                          \
                *(SavedState) = 2 + (ULONG)PsGetCurrentThread()->DisablePageFaultClustering;\
                PsGetCurrentThread()->DisablePageFaultClustering = TRUE; }
Definition at line 1187 of file mm.h.
Referenced by CcPrepareMdlWrite(), and CcZeroData().
#define MmEnablePageFaultClustering (SavedState)
Value:
{                                               \
                PsGetCurrentThread()->DisablePageFaultClustering = (BOOLEAN)(SavedState - 2); }
Definition at line 1216 of file mm.h.
Referenced by CcPrepareMdlWrite(), and CcZeroData().
#define MmEnoughMemoryForWrite ()
Value:
((MmAvailablePages > MmThrottleTop)          \
                        ||                               \
             (((MmModifiedPageListHead.Total < 1000)) && \
               (MmAvailablePages > MmThrottleBottom)))
Definition at line 1387 of file mm.h.
Referenced by CcCanIWrite().
#define MmGetMdlBaseVa (Mdl) ((Mdl)->StartVa)
Definition at line 377 of file mm.h.
Referenced by IoBuildPartialMdl().
#define MmGetMdlByteCount (Mdl) ((Mdl)->ByteCount)
Definition at line 328 of file mm.h.
Referenced by IoBuildPartialMdl().
#define MmGetMdlByteOffset (Mdl) ((Mdl)->ByteOffset)
Definition at line 352 of file mm.h.
Referenced by IoBuildPartialMdl().
#define MmGetMdlPfnArray (Mdl) ((PPFN_NUMBER)(Mdl + 1))
Definition at line 279 of file mm.h.
Referenced by CcZeroData(), and IoBuildPartialMdl().
#define MmGetMdlVirtualAddress (Mdl) ((PVOID) ((PCHAR) ((Mdl)->StartVa) + (Mdl)->ByteOffset))
Definition at line 303 of file mm.h.
#define MmGetSystemAddressForMdl (MDL)
Value:
(((MDL)->MdlFlags & (MDL_MAPPED_TO_SYSTEM_VA |                    \
                        MDL_SOURCE_IS_NONPAGED_POOL)) ?                \
                             ((MDL)->MappedSystemVa) :                 \
                             (MmMapLockedPages((MDL),KernelMode)))
Definition at line 2324 of file mm.h.
Referenced by CcZeroData(), ExLockUserBuffer(), FsRtlCancelNotify(), FsRtlNotifyCompleteIrp(), and FsRtlNotifyFilterReportChange().
#define MmGetSystemAddressForMdlSafe (MDL, PRIORITY)
Value:
(((MDL)->MdlFlags & (MDL_MAPPED_TO_SYSTEM_VA |                    \
                        MDL_SOURCE_IS_NONPAGED_POOL)) ?                \
                             ((MDL)->MappedSystemVa) :                 \
                             (MmMapLockedPagesSpecifyCache((MDL),      \
                                                           KernelMode, \
                                                           MmCached,   \
                                                           NULL,       \
                                                           FALSE,      \
                                                           (PRIORITY))))
Definition at line 2279 of file mm.h.
Referenced by CcZeroData(), KiOpPatchCode(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), and MiZeroPageFileFirstPage().
#define MmInitializeMdl (MemoryDescriptorList, BaseVa, Length)
Value:
{ \
    (MemoryDescriptorList)->Next = (PMDL) NULL; \
    (MemoryDescriptorList)->Size = (CSHORT)(sizeof(MDL) +  \
            (sizeof(PFN_NUMBER) * ADDRESS_AND_SIZE_TO_SPAN_PAGES((BaseVa), (Length)))); \
    (MemoryDescriptorList)->MdlFlags = 0; \
    (MemoryDescriptorList)->StartVa = (PVOID) PAGE_ALIGN((BaseVa)); \
    (MemoryDescriptorList)->ByteOffset = BYTE_OFFSET((BaseVa)); \
    (MemoryDescriptorList)->ByteCount = (ULONG)(Length); \
    }
Definition at line 2235 of file mm.h.
Referenced by ExLockUserBuffer(), IoAllocateMdl(), KiOpPatchCode(), MiCleanPhysicalProcessPages(), MiCloneProcessAddressSpace(), MiCreateImageFileMap(), MiDoMappedCopy(), MiGatherMappedPages(), MiGatherPagefilePages(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiMakeOutswappedPageResident(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiShutdownSystem(), MiZeroPageFile(), MmCreateMdl(), NtFreeUserPhysicalPages(), and NtStartProfile().
#define MmIsRecursiveIoFault ()
Value:
((PsGetCurrentThread()->DisablePageFaultClustering) | \
                  (PsGetCurrentThread()->ForwardClusterOnly))
Definition at line 1156 of file mm.h.
#define MmIsSessionLeaderProcess (Process) ((Process)->Vm.Flags.SessionLeader == 1)
Definition at line 686 of file mm.h.
Referenced by NtSetSystemInformation().
#define MMNONPAGED_QUOTA_CHECK (256*1024)
Definition at line 2457 of file mm.h.
#define MMNONPAGED_QUOTA_INCREASE (64*1024)
Definition at line 2453 of file mm.h.
Referenced by MmRaisePoolQuota(), and PspReturnQuota().
#define MMPAGED_QUOTA_CHECK (1*1024*1024)
Definition at line 2459 of file mm.h.
Referenced by MmRaisePoolQuota().
#define MMPAGED_QUOTA_INCREASE (512*1024)
Definition at line 2455 of file mm.h.
Referenced by MmRaisePoolQuota(), and PspReturnQuota().
#define MmPrepareMdlForReuse (MDL)
Value:
if (((MDL)->MdlFlags & MDL_PARTIAL_HAS_BEEN_MAPPED) != 0) {         \
        ASSERT(((MDL)->MdlFlags & MDL_PARTIAL) != 0);                   \
        MmUnmapLockedPages( (MDL)->MappedSystemVa, (MDL) );             \
    } else if (((MDL)->MdlFlags & MDL_PARTIAL) == 0) {                  \
        ASSERT(((MDL)->MdlFlags & MDL_MAPPED_TO_SYSTEM_VA) == 0);       \
    }
Definition at line 2352 of file mm.h.
Referenced by IoFreeMdl().
#define MmResetPageFaultReadAhead (Thread, SavedState)
Value:
{                     \
                (Thread)->ForwardClusterOnly = (BOOLEAN)((SavedState) & 1); \
                (Thread)->ReadClusterSize = (SavedState) / 2; }
Definition at line 1316 of file mm.h.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapAndCopy(), CcMapAndRead(), CcMapData(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), MmCopyToCachedPage(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
#define MmSavePageFaultReadAhead (Thread, SavedState)
Value:
{               \
                *(SavedState) = (Thread)->ReadClusterSize * 2 +     \
                                (Thread)->ForwardClusterOnly; }
Definition at line 1246 of file mm.h.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapAndCopy(), CcMapAndRead(), CcMapData(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), MmCopyToCachedPage(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
#define MmSetPageFaultReadAhead (Thread, ReadAhead)
Value:
{                          \
                (Thread)->ForwardClusterOnly = TRUE;                         \
                if ((ReadAhead) > MM_MAXIMUM_READ_CLUSTER_SIZE) {            \
                    (Thread)->ReadClusterSize = MM_MAXIMUM_READ_CLUSTER_SIZE;\
                } else {                                                     \
                    (Thread)->ReadClusterSize = (ReadAhead);                 \
                } }
Definition at line 1281 of file mm.h.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapAndCopy(), CcMapAndRead(), CcMapData(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), MmCopyToCachedPage(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
#define NUMBER_OF_PAGE_LISTS 8
Definition at line 1329 of file mm.h.
#define PAGE_ALIGN (Va) ((PVOID)((ULONG_PTR)(Va) & ~(PAGE_SIZE - 1)))
Definition at line 190 of file mm.h.
Referenced by __out_bcount(), ExCheckPoolHeader(), ExFreePoolWithTag(), IoBuildPartialMdl(), KeBugCheck2(), KiInvokeBugCheckEntryCallbacks(), MiCheckForUserStackOverflow(), MiCheckVirtualAddress(), MiCloneProcessAddressSpace(), MiCopyOnWrite(), MiCreateImageFileMap(), MiDecommitPages(), MiDeleteAddressesInWorkingSet(), MiDeletePte(), MiDeleteSystemPageableVm(), MiDispatchFault(), MiEnablePagingTheExecutive(), MiFindContiguousMemoryInPool(), MiFindInitializationCode(), MiGatherMappedPages(), MiGrowWsleHash(), MiIdentifyPfn(), MiInitializeSystemCache(), MiInitializeWorkingSetList(), MiInitMachineDependent(), MiIsPoolLargeSession(), MiLocateWsle(), MiMarkPoolLargeSession(), MiProtectVirtualMemory(), MiRemoveIoSpaceMap(), MiRemovePageFromWorkingSet(), MiRemovePteTracker(), MiRemoveWorkingSetPages(), MiRemoveWsle(), MiResolvePageFileFault(), MiSessionCommitPageTables(), MiSessionInitializeWorkingSetList(), MiTerminateWsle(), MiUpdateWsle(), MmAccessFault(), MmCommitSessionMappedView(), MmFlushVirtualMemory(), MmFreeNonCachedMemory(), MmProtectMdlSystemAddress(), NtAllocateVirtualMemory(), NtFlushVirtualMemory(), NtFreeVirtualMemory(), NtLockVirtualMemory(), NtMapUserPhysicalPages(), NtQueryVirtualMemory(), NtUnlockVirtualMemory(), and RtlpTouchMemory().
#define ROUND_TO_PAGES (Size) (((ULONG_PTR)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))
Definition at line 117 of file mm.h.
Referenced by __bcount(), CcCopyRead(), CcFastCopyRead(), CcPinFileData(), CcScheduleReadAhead(), ExpExpandBigPageTable(), InitializePool(), MiCheckForUserStackOverflow(), MiCreateDataFileMap(), MiCreatePebOrTeb(), MiEnablePagingOfDriver(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiFlushRangeFilter(), MiInitializeSessionIds(), MiInPageSingleKernelStack(), MiLocateKernelSections(), MiOutPageSingleKernelStack(), MiReloadBootLoadedDrivers(), MmCreateTeb(), MmDeleteTeb(), MmFreeDriverInitialization(), MmInitSystem(), NtAllocateVirtualMemory(), PspSetLdtInformation(), PspSetLdtSize(), PsSetLdtEntries(), PsSetProcessLdtInfo(), and RtlInitializeStackTraceDataBase().
Typedef Documentation
typedef struct _MM_KERNEL_DUMP_CONTEXT MM_KERNEL_DUMP_CONTEXT
typedef enum _MM_PAGE_PRIORITY MM_PAGE_PRIORITY
typedef enum _MM_SYSTEM_SIZE MM_SYSTEMSIZE
typedef enum _MMFLUSH_TYPE MMFLUSH_TYPE
typedef enum _MMLISTS MMLISTS
typedef struct _MMPFNLIST MMPFNLIST
typedef enum _MMSYSTEM_PTE_POOL_TYPE MMSYSTEM_PTE_POOL_TYPE
typedef VOID(* PBANKED_SECTION_ROUTINE) (IN ULONG ReadBank, IN ULONG WriteBank, IN PVOID Context)
Definition at line 2518 of file mm.h.
typedef struct _PHYSICAL_MEMORY_DESCRIPTOR PHYSICAL_MEMORY_DESCRIPTOR
typedef struct _PHYSICAL_MEMORY_RANGE PHYSICAL_MEMORY_RANGE
typedef struct _PHYSICAL_MEMORY_RUN PHYSICAL_MEMORY_RUN
typedef NTSTATUS(* PMM_DLL_INITIALIZE) (IN PUNICODE_STRING RegistryPath)
Definition at line 2360 of file mm.h.
typedef NTSTATUS(* PMM_DLL_UNLOAD) (VOID)
Definition at line 2364 of file mm.h.
typedef NTSTATUS(* PMM_FREE_DUMP_RANGE) (IN struct _MM_KERNEL_DUMP_CONTEXT *Context, IN PVOID StartVa, IN PFN_NUMBER Pages, IN ULONG AddressFlags)
Definition at line 2590 of file mm.h.
typedef struct _MM_KERNEL_DUMP_CONTEXT * PMM_KERNEL_DUMP_CONTEXT
typedef NTSTATUS(* PMM_SET_DUMP_RANGE) (IN struct _MM_KERNEL_DUMP_CONTEXT *Context, IN PVOID StartVa, IN PFN_NUMBER Pages, IN ULONG AddressFlags)
Definition at line 2581 of file mm.h.
typedef MMPFNLIST* PMMPFNLIST
Definition at line 1349 of file mm.h.
typedef struct _PHYSICAL_MEMORY_DESCRIPTOR * PPHYSICAL_MEMORY_DESCRIPTOR
typedef struct _PHYSICAL_MEMORY_RANGE * PPHYSICAL_MEMORY_RANGE
typedef struct _PHYSICAL_MEMORY_RUN * PPHYSICAL_MEMORY_RUN
typedef struct _READ_LIST * PREAD_LIST
typedef struct _UNLOADED_DRIVERS * PUNLOADED_DRIVERS
typedef struct _READ_LIST READ_LIST
typedef IN PVOID IN PVOID TrapInformation
Definition at line 2556 of file mm.h.
typedef struct _UNLOADED_DRIVERS UNLOADED_DRIVERS
typedef IN PVOID VirtualAddress
Definition at line 2556 of file mm.h.
Enumeration Type Documentation
enum _MM_PAGE_PRIORITY
Enumerator
LowPagePriority
NormalPagePriority
HighPagePriority
Definition at line 1786 of file mm.h.
enum _MM_SYSTEM_SIZE
Enumerator
MmSmallSystem
MmMediumSystem
MmLargeSystem
Definition at line 480 of file mm.h.
enum _MMFLUSH_TYPE
Enumerator
MmFlushForDelete
MmFlushForWrite
Definition at line 1567 of file mm.h.
enum _MMLISTS
Enumerator
ZeroedPageList
FreePageList
StandbyPageList
ModifiedPageList
ModifiedNoWritePageList
BadPageList
ActiveAndValid
TransitionPage
Definition at line 1331 of file mm.h.
enum _MMSYSTEM_PTE_POOL_TYPE
Enumerator
SystemPteSpace
NonPagedPoolExpansion
MaximumPtePoolTypes
Definition at line 451 of file mm.h.
Function Documentation
NTKERNELAPI __bcount (NumberOfBytes)
__out_bcount (NumberOfBytes)
Definition at line 12176 of file iosup.c.
References _4gb, ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, _MDL::ByteOffset, BYTES_TO_PAGES, ExFreePool(), FALSE, _MMPTE::Hard, MI_DISABLE_CACHING, MI_MAKE_VALID_KERNEL_PTE, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiAllocatePagesForMdl(), MiCached, MiGetVirtualAddressMappedByPte, MiNonCached, MiReserveSystemPtes(), MiWriteCombined, MM_READWRITE, MmFreePagesFromMdl(), MmNonCached, NULL, _MMPTE_HARDWARE::PageFrameNumber, _LARGE_INTEGER::QuadPart, _MDL::StartVa, SystemPteSpace, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
PVOID MiAllocatePoolPages (IN POOL_TYPE PoolType, IN SIZE_T SizeInBytes)
Definition at line 1189 of file allocpag.c.
References _4gb, ActiveAndValid, _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, BASE_POOL_TYPE_MASK, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, _MM_SESSION_SPACE::CommittedPages, CONTAINING_RECORD, _MMPFN::e1, _MMPFN::e2, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MMPFN::Event, ExQueryDepthSList, FALSE, _MM_PAGED_POOL_INFO::FirstPteForPagedPool, _LIST_ENTRY::Flink, _MMPTE::Hard, _KEVENT::Header, Index, InsertTailList(), InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedPopEntrySList(), KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeClearEvent(), KeIsExecutingDpc(), KeQueryTickCount(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), _MM_PAGED_POOL_INFO::LastPteForPagedPool, List, _MMFREE_POOL_ENTRY::List, LOCK_PFN, LOCK_PFN2, LOCK_PFN_AT_DPC, LockQueueMmNonPagedPoolLock, _MMPTE::Long, _LARGE_INTEGER::LowPart, MI_ADD_EXECUTE_TO_INVALID_PTE_IF_PAE, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_CONVERT_PHYSICAL_TO_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_MAX_FREE_LIST_HEADS, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_UNUSED_SEGMENTS_SURPLUS, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiCached, MiCachedNonPagedPool, MiCachedNonPagedPoolCount, MiChargeCommitmentCantExpand(), MiCompareTbFlushTimeStamp(), MiExpansionPoolPagesInitialCharge, MiExpansionPoolPagesInUse, MiFreeAllExpansionNonPagedPool(), MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiHighNonPagedPoolEvent, MiHighNonPagedPoolThreshold, MiHighPagedPoolEvent, MiHighPagedPoolThreshold, MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), MiIssuePageExtendRequestNoWait(), MiLowNonPagedPoolEvent, MiLowNonPagedPoolThreshold, MiLowPagedPoolEvent, MiLowPagedPoolThreshold, MiProtectedPoolInsertList(), MiProtectedPoolRemoveEntryList(), MiProtectFreeNonPagedPool(), MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiReturnCommitment, MiTrimSegmentCache(), MiUnProtectFreeNonPagedPool(), MiZeroMemoryPte, MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_NONPAGED_POOL_EXPANSION, MM_DBG_COMMIT_PAGED_POOL_PAGES, MM_DBG_COMMIT_PAGED_POOL_PAGETABLE, MM_DBG_SESSION_COMMIT_PAGEDPOOL_PAGES, MM_DBG_SESSION_NP_PAGETABLE_ALLOC, MM_DBG_SESSION_PAGEDPOOL_PAGETABLE_ALLOC1, MM_DEMAND_ZERO_WRITE_PTE, MM_FREE_POOL_SIGNATURE, MM_KERNEL_DEMAND_ZERO_PTE, MM_MAXIMUM_FLUSH_COUNT, MM_PAGED_POOL_LOCKED_DOWN, MM_RESAVAIL_ALLOCATE_EXPANSION_NONPAGED_POOL, MM_RESAVAIL_ALLOCATE_PAGETABLES_FOR_PAGED_POOL, MM_TRACK_COMMIT, MmAllocatedNonPagedPool, MmAvailablePages, MmDisablePagingExecutive, MmHighPriority, MmMaximumNonPagedPoolInPages, MmNonPagedNoCommit, MmNonPagedNoPagesAvailable, MmNonPagedNoPtes, MmNonPagedNoResidentAvailable, MmNonPagedPool, MmNumberOfFreeNonPagedPool, MmPagedNoCommit, MmPagedNoPagesAvailable, MmPagedNoPtes, MmPagedPool, MmPagedPoolCommit, MmPagedPoolInfo, MmPagedPoolStart, MmPfnDatabase, MmPoolFailureReasons, MmPoolFailures, MmPreemptForNonPaged, MmPreemptForPaged, MmPreemptiveTrims, MmProtectFreedNonPagedPool, MmSessionBase, MmSessionPagedNoCommit, MmSessionPagedNoPagesAvailable, MmSessionPagedNoPtes, MmSessionPagedPool, MmSessionSpace, MmSizeOfPagedPoolInPages, MmSystemPageDirectory, MmSystemPagePtes, MmUnusedSegmentCleanup, _MMPFN::MustBeCached, _MM_PAGED_POOL_INFO::NextPdeForPagedPoolExpansion, NO_BITS_FOUND, _MM_SESSION_SPACE::NonPageablePages, NonPagedPool, NonPagedPoolExpansion, NOTHING, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_PAGED_POOL_INFO::PagedPoolCommit, _MM_PAGED_POOL_INFO::PagedPoolHint, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MM_SESSION_SPACE::PageTables, PD_PER_SYSTEM, PDE_PER_PAGE, POOL_VERIFIER_MASK, PsGetCurrentThread(), PTE_PER_PAGE, _MMPFN::PteAddress, _MMPFN::PteFrame, RemoveEntryList(), RtlClearBits(), RtlFindClearBitsAndSet(), RtlSetBit(), SESSION_GLOBAL, SESSION_POOL_MASK, _MM_SESSION_SPACE::SessionPageDirectoryIndex, _MM_SESSION_SPACE::SessionPoolAllocationFailures, _MMPFN::ShareCount, _DISPATCHER_HEADER::SignalState, _MMFREE_POOL_ENTRY::Signature, _MMFREE_POOL_ENTRY::Size, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_PFN2, UNLOCK_PFN_FROM_DPC, _MMPTE_HARDWARE::Valid, ValidKernelPde, ValidKernelPdeLocal, ValidKernelPte, _MMPFN::VerifierAllocation, and VerifierLargePagedPoolMap.
Referenced by __bcount(), ExGetBigPoolInfo(), ExpExpandBigPageTable(), ExpInsertPoolTrackerExpansion(), and InitializePool().
ULONG MiFreePoolPages (IN PVOID StartingAddress)
Definition at line 2422 of file allocpag.c.
References ActiveAndValid, _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, BAD_POOL_CALLER, _RTL_BITMAP::Buffer, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, _MM_SESSION_SPACE::CommittedPages, _MMPFN::e1, _MMPFN::e2, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MMPFN::Event, ExQueryDepthSList, FALSE, _MM_PAGED_POOL_INFO::FirstPteForPagedPool, _MMPTE::Hard, _KEVENT::Header, Index, InsertTailList(), InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedPushEntrySList(), KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeBugCheckEx(), KeClearEvent(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), _MMFREE_POOL_ENTRY::List, LOCK_PFN2, LockQueueMmNonPagedPoolLock, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CHECK_BIT, MI_CLEAR_BIT, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_POOL_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_MAX_FREE_LIST_HEADS, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiBadRefCount(), MiCached, MiCachedNonPagedPoolCount, MiDeferredUnlockPages(), MiDeleteSystemPageableVm(), MiEndOfInitialPoolFrame, MiExpansionPoolPagesInitialCharge, MiExpansionPoolPagesInUse, MiFreeNonPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiHighNonPagedPoolEvent, MiHighNonPagedPoolThreshold, MiHighPagedPoolEvent, MiHighPagedPoolThreshold, MiLowNonPagedPoolEvent, MiLowNonPagedPoolThreshold, MiLowPagedPoolEvent, MiLowPagedPoolThreshold, MiNonPagedPoolSListMaximum, MiPagedPoolSListMaximum, MiProtectedPoolInsertList(), MiProtectedPoolRemoveEntryList(), MiProtectFreeNonPagedPool(), MiReleaseSystemPtes(), MiReturnCommitment, MiStartOfInitialPoolFrame, MiUnProtectFreeNonPagedPool(), MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_RETURN_PAGED_POOL_PAGES, MM_DBG_SESSION_COMMIT_POOL_FREED, MM_DEMAND_ZERO_WRITE_PTE, MM_FREE_POOL_SIGNATURE, MM_PAGED_POOL_LOCKED_DOWN, MM_SMALL_ALLOCATIONS, MM_SYSTEM_RANGE_START, MM_TRACK_COMMIT, MmAllocatedNonPagedPool, MmDisablePagingExecutive, MmFreedExpansionPoolMaximum, MmHighestPhysicalPage, MmMaximumNonPagedPoolInPages, MmNonPagedPoolEnd, MmNonPagedPoolEnd0, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmNumberOfFreeNonPagedPool, MmPagedPoolCommit, MmPagedPoolEnd, MmPagedPoolInfo, MmPagedPoolMutex, MmPagedPoolStart, MmPfnDeferredList, MmProtectFreedNonPagedPool, MmResidentAvailablePages, MmSessionSpace, MmSizeOfNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, MmSizeOfPagedPoolInPages, _MMPFN::MustBeCached, NonPagedPool, NonPagedPoolExpansion, NOTHING, NULL, _MMPFN::OriginalPte, _MMFREE_POOL_ENTRY::Owner, PAGE_SHIFT, PAGE_SIZE, PagedPool, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_PAGED_POOL_INFO::PagedPoolCommit, _MM_PAGED_POOL_INFO::PagedPoolHint, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PSLIST_ENTRY, _MMPFN::PteFrame, RemoveEntryList(), RtlCheckBit, RtlClearBit(), RtlClearBits(), RtlFillMemoryUlong(), SATISFY_OVERZEALOUS_COMPILER, SESSION_GLOBAL, _MMPFN::ShareCount, _DISPATCHER_HEADER::SignalState, _MMFREE_POOL_ENTRY::Signature, _MMFREE_POOL_ENTRY::Size, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, _MMPFN::VerifierAllocation, VerifierFreeTrackedPool(), VerifierLargePagedPoolMap, and _MMPFNENTRY::WriteInProgress.
Referenced by ExDeferredFreePool(), ExFreePoolWithTag(), ExGetBigPoolInfo(), ExpExpandBigPageTable(), and ExpInsertPoolTrackerExpansion().
LOGICAL MiIsPoolLargeSession (IN PVOID VirtualAddress)
Definition at line 1126 of file allocpag.c.
References ASSERT, _MMPFN::e1, FALSE, _MMPTE::Hard, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, PAGE_ALIGN, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
Referenced by ExFreePoolWithTag().
VOID MiMarkPoolLargeSession (IN PVOID VirtualAddress)
Definition at line 1059 of file allocpag.c.
References ASSERT, _MMPFN::e1, _MMPTE::Hard, LOCK_PFN2, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, PAGE_ALIGN, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, and _MMPTE_HARDWARE::Valid.
Referenced by __bcount().
PVOID MiSessionPoolBigPageTable (VOID)
Definition at line 618 of file session.c.
References ASSERT, KeGetCurrentIrql(), MiSessionDataPages, MiSessionTagSizePages, MmSessionSpace, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor().
SIZE_T MiSessionPoolBigPageTableSize (VOID)
Definition at line 628 of file session.c.
References ASSERT, FALSE, KeGetCurrentIrql(), MiSessionBigPoolPages, NumberOfBytes, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor().
PGENERAL_LOOKASIDE MiSessionPoolLookaside (VOID)
Definition at line 569 of file session.c.
References ASSERT, KeGetCurrentIrql(), _MM_SESSION_SPACE::Lookaside, MmSessionSpace, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor().
PVOID MiSessionPoolMutex (VOID)
ULONG MiSessionPoolSmallLists (VOID)
Definition at line 561 of file session.c.
References SESSION_POOL_SMALL_LISTS.
Referenced by ExInitializePoolDescriptor().
PVOID MiSessionPoolTrackTable (VOID)
Definition at line 579 of file session.c.
References ASSERT, KeGetCurrentIrql(), MiSessionDataPages, MmSessionSpace, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor(), and MiCheckSessionPoolAllocations().
SIZE_T MiSessionPoolTrackTableSize (VOID)
Definition at line 589 of file session.c.
References ASSERT, FALSE, KeGetCurrentIrql(), MiSessionTagSizePages, NumberOfBytes, PAGE_SHIFT, and PASSIVE_LEVEL.
Referenced by ExInitializePoolDescriptor(), and MiCheckSessionPoolAllocations().
PVOID MiSessionPoolVector (VOID)
Definition at line 588 of file allocpag.c.
References MmSessionSpace, PAGED_CODE, and _MM_SESSION_SPACE::PagedPool.
Referenced by ExInitializePoolDescriptor().
NTSTATUS MmAccessFault (IN ULONG_PTR FaultStatus, IN PVOID VirtualAddress, IN KPROCESSOR_MODE PreviousMode, IN PVOID TrapInformation)
Definition at line 51 of file mmfault.c.
References _MI_PAGING_LEVELS, _ETHREAD::ActiveFaultCount, _IMAGE_ENTRY_IN_SESSION::Address, APC_LEVEL, _ETHREAD::ApcNeeded, ASSERT, ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY, ATTEMPTED_WRITE_TO_READONLY_MEMORY, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _KPROCESS::BasePriority, _MMPFNENTRY::CacheAttribute, _EPROCESS::CloneRoot, CONTAINING_RECORD, _MMPTE_HARDWARE::CopyOnWrite, DbgBreakPoint(), DbgPrintEx(), DemandZeroPde, _MMPTE_HARDWARE::Dirty, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, DRIVER_CAUGHT_MODIFYING_FREED_POOL, _MMPFN::e1, _MMPFN::Event, _KEXECUTE_OPTIONS::ExecuteDisable, _KEXECUTE_OPTIONS::ExecuteEnable, FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _KPROCESS::Flags, _LIST_ENTRY::Flink, _EPROCESS::ForkInProgress, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMSUPPORT_FLAGS::GrowWsleHash, _MMPTE::Hard, HYDRA_PROCESS, HYPER_SPACE, _MM_SESSION_SPACE::ImageList, _IMAGE_ENTRY_IN_SESSION::ImageLoading, InterlockedCompareExchangePte, InterlockedIncrement, IoRetryIrpCompletions(), IsListEmpty, KdPrint, KeAreAllApcsDisabled(), KeBugCheckEx(), KeDelayExecutionThread(), KeFeatureBits, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeInvalidAccessAllowed(), KeLowerIrql, KeRaiseIrql, KernelMode, KeZeroSinglePage, KF_GLOBAL_32BIT_EXECUTE, KF_GLOBAL_32BIT_NOEXECUTE, LOCK_PFN, LOCK_WORKING_SET, LOCK_WS, _MMPTE::Long, LOW_REALTIME_PRIORITY, MI_BARRIER_STAMP_ZEROED_PAGE, MI_BARRIER_SYNCHRONIZE, MI_BREAK_ON_AV, MI_DISABLE_CACHING, MI_DISPLAY_TRAP_INFORMATION, MI_FAULT_STATUS_INDICATES_EXECUTION, MI_FAULT_STATUS_INDICATES_WRITE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_GUARD, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_PAGE_TABLE_OR_HYPER_ADDRESS, MI_IS_PFN(), MI_IS_PTE_EXECUTABLE, MI_IS_SESSION_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MI_IS_SESSION_PTE, MI_MAKE_VALID_PTE, MI_MAKE_VALID_USER_PTE, MI_NO_FAULT_FOUND, MI_PAGE_COLOR_VA_PROCESS, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_PTE_OWNER_KERNEL, MI_RESERVED_BITS_CANONICAL(), MI_SET_PAGE_DIRTY, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiAccessCheck(), MiAllocateWsle(), MiCheckForUserStackOverflow(), MiCheckPdeForPagedPool(), MiCheckPdeForSessionSpace(), MiCheckSystemPteProtection(), MiCheckVirtualAddress(), MiCopyOnWrite(), MiDelayPageFaults, MiDispatchFault(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPde, MiGetVirtualAddressMappedByPte, MiGrowWsleHash(), MiHighestUserPte, MiInitializePfn(), _MMSUPPORT::MinimumWorkingSetSize, MiNonCached, MiProtoAddressForPte, MiPteToProto, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiRemoveZeroPageIfAny, MiReserveSystemPtes(), MiResolveDemandZeroFault(), MiSetDirtyBit(), MiTrimPte(), MiWaitForForkToComplete(), MiWriteCombined, MiZeroPhysicalPage(), Mm30Milliseconds, MM_DEMAND_ZERO_WRITE_PTE, MM_GUARD_PAGE, MM_HIGH_LIMIT, MM_HIGHEST_USER_ADDRESS, MM_NOACCESS, MM_NOIRQL, MM_PLENTY_FREE_LIMIT, MM_PTE_WRITE_MASK, MM_READONLY, MM_READWRITE, MM_SHARED_USER_DATA_VA, MM_UNKNOWN_PROTECTION, MM_ZERO_KERNEL_PTE, MM_ZERO_PTE, MmAvailablePages, MmHalfSecond, MmHighestUserAddress, MmIsRetryIoStatus, MmModifiedPageListHead, MmModifiedPageMaximum, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmPaeMask, MmPageFaultNotifyRoutine, MmProtectedPteList, MmProtectFreedNonPagedPool, MmSessionSpace, MmShortTime, MmSizeOfNonPagedPoolInBytes, MmSystemCacheWs, MmSystemRangeStart, _EPROCESS::ModifiedPageCount, _EPROCESS::NextPageColor, _MMPTE_HARDWARE::NoExecute, NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfPrivatePages, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, _ETHREAD::OwnsSessionWorkingSetExclusive, _ETHREAD::OwnsSessionWorkingSetShared, PAGE_ALIGN, PAGE_FAULT_IN_NONPAGED_AREA, PAGE_SIZE, _MMSUPPORT::PageFaultCount, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _EPROCESS::Pcb, Priority, PROCESS_FOREGROUND_PRIORITY, _MMPTE_SOFTWARE::Protection, _MMPTE_TRANSITION::Protection, _MMPTE::Proto, _MMPTE_SOFTWARE::Prototype, PrototypePte, _MMPFNENTRY::PrototypePte, PS_PROCESS_INJECT_INPAGE_ERRORS, PS_SAME_THREAD_FLAGS_OWNS_A_WORKING_SET, PsGetCurrentProcessByThread, PsGetCurrentThread(), PTE_BASE, _MMPFN::PteFrame, _MMPTE_PROTOTYPE::ReadOnly, _ETHREAD::SameThreadApcFlags, _MMPTE::Soft, STATUS_ACCESS_VIOLATION, STATUS_DEVICE_NOT_CONNECTED, STATUS_GUARD_PAGE_VIOLATION, STATUS_IN_PAGE_ERROR, STATUS_PAGE_FAULT_COPY_ON_WRITE, STATUS_PAGE_FAULT_DEMAND_ZERO, STATUS_SUCCESS, STATUS_WAIT_1, SystemPteSpace, _MMPFNLIST::Total, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WORKING_SET, UNLOCK_WS, UserMode, _MMPTE_HARDWARE::Valid, ValidKernelPte, _EPROCESS::Vm, _MM_SESSION_SPACE::Vm, _MMSUPPORT::WorkingSetSize, _MMPTE_HARDWARE::Write, and ZeroPte.
Referenced by MiDispatchFault(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MmCheckCachedPageState(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
NTKERNELAPI NTSTATUS MmAddPhysicalMemory (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
NTKERNELAPI NTSTATUS MmAddPhysicalMemoryEx (IN PPHYSICAL_ADDRESS StartAddress, IN OUT PLARGE_INTEGER NumberOfBytes, IN ULONG Flags)
NTSTATUS MmAddVerifierEntry (IN PUNICODE_STRING ImageFileName)
Referenced by NtSetSystemInformation().
NTKERNELAPI NTSTATUS MmAddVerifierThunks (__in_bcount(ThunkBufferSize) PVOID ThunkBuffer, __in ULONG ThunkBufferSize)
Referenced by NtSetSystemInformation().
NTKERNELAPI NTSTATUS MmAdjustWorkingSetSize (__in SIZE_T WorkingSetMinimumInBytes, __in SIZE_T WorkingSetMaximumInBytes, __in ULONG SystemCache, __in BOOLEAN IncreaseOkay)
Definition at line 2591 of file wslist.c.
References MmAdjustWorkingSetSizeEx().
Referenced by NtSetInformationJobObject(), and PspAddProcessToJob().
NTSTATUS MmAdjustWorkingSetSizeEx (IN SIZE_T WorkingSetMinimum, IN SIZE_T WorkingSetMaximum, IN ULONG SystemCache, IN BOOLEAN IncreaseOkay, IN ULONG Flags, OUT PBOOLEAN IncreaseRequested)
Definition at line 2198 of file wslist.c.
References ASSERT, ExPageLockHandle, FALSE, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMSUPPORT::Flags, _EPROCESS::Flags, InterlockedExchangeAddSizeT, _MMWSL::LastInitializedWsle, LOCK_EXPANSION, LOCK_PFN, LOCK_SYSTEM_WS, LOCK_WS, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, MI_DECREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PASS0_TRIM_AGE, MiEmptyWorkingSet(), _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MiTrimWorkingSet(), MM_FLUID_WORKING_SET, MM_HIGH_LIMIT, MM_RESAVAIL_ALLOCATEORFREE_WS_ADJUST, MM_RESAVAIL_ALLOCATEORFREE_WS_ADJUST2, MM_RESAVAIL_ALLOCATEORFREE_WS_ADJUST3, MmAvailablePages, MmLockPageableSectionByHandle(), MmMaximumWorkingSetSize, MmMinimumWorkingSetSize, MmPagesAboveWsMinimum, MmSystemCacheWs, MmUnlockPageableImageSection(), NULL, PAGE_SHIFT, PAGE_SIZE, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), STATUS_BAD_WORKING_SET_LIMIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_WORKING_SET_LIMIT_RANGE, TRUE, UNLOCK_EXPANSION, UNLOCK_PFN, UNLOCK_SYSTEM_WS, UNLOCK_WS, _EPROCESS::Vm, _MMSUPPORT::VmWorkingSetList, _MMSUPPORT::WorkingSetSize, _MMWSL::Wsle, and WSLE_NULL_INDEX.
Referenced by MmAdjustWorkingSetSize(), NtSetSystemInformation(), and PspSetQuotaLimits().
NTKERNELAPI NTSTATUS MmAdvanceMdl (__inout PMDL Mdl, __in ULONG NumberOfBytes)
Definition at line 6092 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, BYTE_OFFSET, DISPATCH_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, GET_PAGING_FILE_OFFSET, InterlockedCompareExchange(), InterlockedExchangeAddSizeT, KeGetCurrentIrql(), LOCK_PFN2, MDL_DESCRIBES_AWE, MDL_FREE_EXTRA_PTES, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_IS_PFN(), MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiDecrementReferenceCountForAwePage(), MiMdlsAdjusted, MiReleaseConfirmedPageFileSpace(), MiUpdateMdlTracker(), MM_EMPTY_LIST, MmHighestPhysicalPage, MmTrackLockedPages, NULL, NumberOfBytes, _EPROCESS::NumberOfLockedPages, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, ReadForWriteAccess, _MMPTE::Soft, STATUS_INVALID_PARAMETER_2, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, and _MMPFNENTRY::WriteInProgress.
PVOID MmAllocateIndependentPages (IN SIZE_T NumberOfBytes, IN ULONG NodeNumber)
Definition at line 9582 of file iosup.c.
References ASSERT, BYTES_TO_PAGES, FALSE, _MMPTE::Hard, KeNumberNodes, LOCK_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_SET_PTE_DIRTY, MI_SYSTEM_PAGE_COLOR, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetVirtualAddressMappedByPte, MiInitializePfnAndMakePteValid(), MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_INDEPENDENT_PAGES, MM_HIGH_LIMIT, MM_READWRITE, MM_RESAVAIL_ALLOCATE_INDEPENDENT, MM_TRACK_COMMIT, MmAvailablePages, MmSecondaryColorMask, MmSecondaryColorNodeShift, NULL, _MMPTE_HARDWARE::PageFrameNumber, SystemPteSpace, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by ExCreatePoolTagTable(), InitializePool(), KeStartAllProcessors(), and KiI386PentiumLockErrataFixup().
NTKERNELAPI PMDL MmAllocatePagesForMdl (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes)
Definition at line 11476 of file iosup.c.
References MiAllocatePagesForMdl(), and MiNotMapped.
NTKERNELAPI PMDL MmAllocatePagesForMdlEx (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes, __in MEMORY_CACHING_TYPE CacheType, __in ULONG Flags)
Definition at line 11546 of file iosup.c.
References FALSE, MI_TRANSLATE_CACHETYPE(), MiAllocatePagesForMdl(), MiNotMapped, MM_ALLOCATE_FROM_LOCAL_NODE_ONLY, MM_DONT_ZERO_ALLOCATION, MmWriteCombined, and NULL.
PVOID MmAllocateSpecialPool (IN SIZE_T NumberOfBytes, IN ULONG Tag, IN POOL_TYPE Type, IN ULONG SpecialPoolType)
Referenced by __bcount().
LOGICAL MmAreMdlPagesLocked (IN PMDL MemoryDescriptorList)
Definition at line 14960 of file iosup.c.
References ActiveAndValid, ADDRESS_AND_SIZE_TO_SPAN_PAGES, BASE_POOL_TYPE_MASK, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, FALSE, LOCK_PFN2, MDL_IO_SPACE, MDL_SOURCE_IS_NONPAGED_POOL, MI_IS_PFN(), MI_PFN_ELEMENT, MiEndOfInitialPoolFrame, MiGetVirtualAddressMappedByPte, MiStartOfInitialPoolFrame, MM_EMPTY_LIST, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmQuerySpecialPoolBlockType(), MmSpecialPoolEnd, MmSpecialPoolStart, NonPagedPool, NOTHING, NULL, _MMPFNENTRY::PageLocation, _MMPFN::PteAddress, _MMPFN::ShareCount, TRUE, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN2.
Referenced by MmBuildMdlForNonPagedPool().
LOGICAL MmAssignProcessToJob (IN PEPROCESS Process)
Definition at line 1980 of file wslist.c.
References FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, PAGED_CODE, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_SET_BITS, PsChangeJobMemoryUsage(), PsGetCurrentProcess(), Status, TRUE, and UNLOCK_ADDRESS_SPACE.
Referenced by PspAddProcessToJob().
NTSTATUS MmAttachSession (IN PVOID OpaqueSession, OUT PRKAPC_STATE ApcState)
Definition at line 3834 of file session.c.
References APC_LEVEL, ASSERT, _MM_SESSION_SPACE::AttachCount, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, KeGetCurrentIrql(), KeStackAttachProcess(), LOCK_EXPANSION, NULL, _EPROCESS::Pcb, PsGetCurrentProcess(), _EPROCESS::Session, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by ExGetSessionPoolTagInformation(), ExpWin32SessionCallout(), MmGetSessionMappedViewInformation(), and PspWin32SessionCallout().
SIZE_T MmAvailablePoolInPages (IN POOL_TYPE PoolType)
Definition at line 616 of file allocpag.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, KeGetCurrentIrql(), MmPagedPoolInfo, MmSizeOfPagedPoolInPages, MmTotalCommitLimitMaximum, MmTotalCommittedPages, PagedPool, PASSIVE_LEVEL, and UNREFERENCED_PARAMETER.
Referenced by NtQuerySystemInformation().
NTKERNELAPI VOID MmBuildMdlForNonPagedPool (__inout PMDL MemoryDescriptorList)
Definition at line 4193 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MiGetPteAddress, MmAreMdlPagesLocked(), MmIsNonPagedSystemAddressValid(), and NULL.
Referenced by CcZeroData(), and MiCreateImageFileMap().
NTSTATUS MmCallDllInitialize (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry, IN PLIST_ENTRY ModuleListHead)
Definition at line 8150 of file sysload.c.
References _UNICODE_STRING::Buffer, CmRegistryMachineSystemCurrentControlSetServices, ExAllocatePoolWithTag, ExFreePool(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MiFirstDriverLoadEver, MiLocateExportName(), MiReApplyVerifierToLoadedModules(), MiVerifierThunksAdded, NonPagedPool, NT_SUCCESS, NULL, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and wcschr().
Referenced by MiResolveImageReferences().
NTKERNELAPI BOOLEAN MmCanFileBeTruncated (__in PSECTION_OBJECT_POINTERS SectionPointer, __in_opt PLARGE_INTEGER NewFileSize)
Definition at line 3008 of file sectsup.c.
References ARGUMENT_PRESENT, FALSE, MiCanFileBeTruncatedInternal(), TRUE, and UNLOCK_PFN.
Referenced by CcPurgeCacheSection().
LOGICAL MmCanThreadFault (VOID)
Referenced by KiOpPatchCode(), RtlCaptureStackBackTrace(), RtlGetCallersAddress(), and RtlWalkFrameChain().
BOOLEAN MmCheckCachedPageState (IN PVOID Address, IN BOOLEAN SetToZero)
Definition at line 1434 of file mapcache.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, CCPF_IS_PREFETCHER_ACTIVE, CCPF_TYPE_ROM, CcPfLogPageFault(), _SUBSECTION::ControlArea, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, FALSE, FileOffset, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _MMPFN::InPageError, InterlockedIncrementPfn, KernelMode, LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, _MMWSLE::Long, MI_BARRIER_SYNCHRONIZE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_SET_GLOBAL_STATE, MI_SNAP_DATA, MI_WRITE_VALID_PTE, MiAllocateWsle(), MiCached, MiGetPteAddress, MiGetSubsectionAddress, MiHighestUserPte, MiInitializePfn(), MiMakeSystemAddressValidPfnSystemWs(), MiNonCached, MiProtoAddressForPte, MiPteToProto, MiRemoveZeroPage(), MiStartingOffset(), MiTrimPte(), MiUnlinkPageFromList(), MiWriteCombined, MM_HIGH_LIMIT, MM_NOCACHE, MM_WRITECOMBINE, MM_ZERO_ACCESS, MmAccessFault(), MmAvailablePages, MmSystemCacheWs, NOTHING, NULL, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, _MMSECTION_FLAGS::Rom, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_SYSTEM_WS, and _MMPTE_HARDWARE::Valid.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapAndCopy(), CcMapAndRead(), CcMapDataForOverwrite(), and CcPerformReadAhead().
BOOLEAN MmCheckForSafeExecution (IN PVOID InstructionPointer, IN PVOID StackPointer, IN PVOID BranchTarget, IN BOOLEAN PermitStackExecution)
Definition at line 803 of file vadtree.c.
References FALSE, LOCK_ADDRESS_SPACE, MiLocateAddress(), NULL, PsGetCurrentProcess(), TRUE, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNREFERENCED_PARAMETER, _MMVAD::VadFlags, VadImageMap, and _MMVAD_FLAGS::VadType.
Referenced by KiEmulateAtlThunk().
NTSTATUS MmCheckSystemImage (IN HANDLE ImageFileHandle, IN LOGICAL PurgeSection)
Definition at line 5474 of file sysload.c.
References _SEGMENT::ControlArea, _FILE_STANDARD_INFORMATION::EndOfFile, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _IMAGE_NT_HEADERS::FileHeader, _CONTROL_AREA::FilePointer, FileStandardInformation, IMAGE_FILE_MACHINE_NATIVE, IMAGE_NT_OPTIONAL_HDR_MAGIC, InitializeObjectAttributes, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LdrVerifyMappedImageMatchesChecksum(), _LARGE_INTEGER::LowPart, _IMAGE_FILE_HEADER::Machine, _IMAGE_OPTIONAL_HEADER::Magic, MmPurgeSection(), MmSectionObjectType, MmVerifyImageIsOkForMpUse(), NT_SUCCESS, NtCurrentProcess, NULL, NumberOfBytes, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_EXECUTE, PAGED_CODE, _EPROCESS::Pcb, PsInitialSystemProcess, RtlImageNtHeader(), SEC_COMMIT, SEC_IMAGE, SECTION_MAP_EXECUTE, _FILE_OBJECT::SectionObjectPointer, _SECTION::Segment, Status, STATUS_IMAGE_CHECKSUM_MISMATCH, STATUS_IMAGE_MP_UP_MISMATCH, STATUS_INVALID_IMAGE_PROTECT, TRUE, ViewShare, ZwClose(), ZwCreateSection(), ZwMapViewOfSection(), ZwQueryInformationFile(), and ZwUnmapViewOfSection().
Referenced by MmLoadSystemImage(), and PsLocateSystemDll().
VOID MmCleanProcessAddressSpace (IN PEPROCESS Process)
Definition at line 2563 of file procsup.c.
References ASSERT, _LOCK_TRACKER::CallersCaller, _LOCK_TRACKER::CallingAddress, CONTAINING_RECORD, _MMVAD::ControlArea, _LOCK_HEADER::Count, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS, _MMVAD::EndingVpn, _MMVAD_SHORT::EndingVpn, ERROR_LOG_MAXIMUM_SIZE, _IO_ERROR_LOG_PACKET::ErrorCode, ExFreePool(), FALSE, _IO_ERROR_LOG_PACKET::FinalStatus, _LIST_ENTRY::Flink, InterlockedExchangeAddSizeT, IoAllocateGenericErrorLogEntry(), IoWriteErrorLogEntry(), IsListEmpty, KdDebuggerEnabled, KdDebuggerNotPresent, KeBugCheckEx(), _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _LOCK_TRACKER::Mdl, MI_INCREMENT_RESIDENT_AVAILABLE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiAweViewRemover(), MiCleanPhysicalProcessPages(), MiDeleteAddressesInWorkingSet(), MiDeletePageTablesForPhysicalRange(), MiDeletePteRange(), MiDeleteVirtualAddresses(), MiFreeLargePages(), MiGetPteAddress, MiPhysicalViewRemover(), MiReleasePhysicalCharges(), MiRemoveMappedView(), MiRemoveUserPhysicalPagesVad(), MiRemoveVad(), MiRemoveVadCharges(), MiRemoveWorkingSetPages(), MiReturnCommitment, MiSafeBooted, MiSessionRemoveProcess(), MiUnlinkWorkingSet(), MM_DBG_COMMIT_RETURN_PROCESS_CLEAN_PAGETABLES, MM_DBG_PRIVATE_PAGES, MM_HIGHEST_VAD_ADDRESS, MM_MAXIMUM_WORKING_SET, MM_PROCESS_CREATE_CHARGE, MM_RESAVAIL_FREE_CLEAN_PROCESS1, MM_RESAVAIL_FREE_CLEAN_PROCESS2, MM_SHARED_USER_DATA_VA, MM_TRACK_COMMIT, MM_WS_NOT_LISTED, MmHighestUserAddress, MmLeakedLockedPages, MmPagesAboveWsMinimum, MmTrackLockedPages, MmWorkingSetList, MmWsle, NULL, PAGE_SHIFT, _MMVAD_FLAGS::PrivateMemory, PS_CLEAR_BITS, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_PROCESS_FLAGS_ADDRESS_SPACE1, PS_PROCESS_FLAGS_VM_DELETED, PS_SET_BITS, PsChangeJobMemoryUsage(), PsGetCurrentThread(), PsReturnProcessPageFileQuota(), RemoveEntryList(), _MMVAD::RightChild, _MMVAD::StartingVpn, _MMVAD_SHORT::StartingVpn, STATUS_DRIVERS_LEAKING_LOCKED_PAGES, TRUE, _MMVAD::u, _IO_ERROR_LOG_PACKET::UniqueErrorValue, UNLOCK_WS_AND_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, VadWriteWatch, and _LOCK_HEADER::Valid.
Referenced by PspExitProcess(), and PspExitThread().
NTKERNELAPI NTSTATUS MmCommitSessionMappedView (__in_bcount(ViewSize) PVOID MappedAddress, __in SIZE_T ViewSize)
Definition at line 2036 of file allocvm.c.
References ASSERT, _MMVIEW::ControlArea, DRIVER_UNMAPPING_INVALID_VIEW, _MMVIEW::Entry, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, InterlockedExchangeAddSizeT, KeAcquireGuardedMutexUnsafe(), KeBugCheckEx(), KeReleaseGuardedMutexUnsafe(), LOCK_SYSTEM_VIEW_SPACE, _MMPTE::Long, MI_WRITE_INVALID_PTE, MiChargeCommitment(), MiGetPteAddress, MiReturnCommitment, MiSessionViewStart, MM_DBG_COMMIT_ALLOCVM_SEGMENT, MM_DBG_COMMIT_RETURN_ALLOCVM_SEGMENT, MM_TRACK_COMMIT, MmIsAddressValid(), MmSectionCommitMutex, MmSessionSpace, MmSessionViewSize, MmSharedCommit, NULL, _SEGMENT::NumberOfCommittedPages, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, _SEGMENT::SegmentPteTemplate, _MM_SESSION_SPACE::Session, STATUS_ALREADY_COMMITTED, STATUS_COMMITMENT_LIMIT, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_NOT_MAPPED_VIEW, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MMSESSION::SystemSpaceHashKey, _MMSESSION::SystemSpaceHashSize, _MMSESSION::SystemSpaceViewTable, TRUE, _MMPTE::u, _CONTROL_AREA::u, UNLOCK_SYSTEM_VIEW_SPACE, and X64K.
NTSTATUS MmCopyToCachedPage (IN PVOID Address, IN PVOID UserBuffer, IN ULONG Offset, IN SIZE_T CountInBytes, IN LOGICAL ExposeZeroPageOk)
Referenced by CcMapAndCopy().
NTSTATUS MmCopyVirtualMemory (IN PEPROCESS FromProcess, IN CONST VOID * FromAddress, IN PEPROCESS ToProcess, OUT PVOID ToAddress, IN SIZE_T BufferSize, IN KPROCESSOR_MODE PreviousMode, OUT PSIZE_T NumberOfBytesCopied)
Definition at line 361 of file readwrt.c.
References ASSERT, ExAcquireRundownProtection(), ExReleaseRundownProtection(), FALSE, MiDoMappedCopy(), MiDoPoolCopy(), POOL_MOVE_THRESHOLD, PsGetCurrentProcess(), _EPROCESS::RundownProtect, Status, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, and STATUS_WORKING_SET_QUOTA.
Referenced by IoRaiseHardError(), LpcpCopyRequestData(), NtReadVirtualMemory(), NtWriteVirtualMemory(), and PspCreateProcess().
PVOID MmCreateKernelStack (BOOLEAN LargeStack, UCHAR Processor)
Referenced by KeInitThread(), KeStartAllProcessors(), KiInitializeKernel(), and PsConvertToGuiThread().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI PMDL MmCreateMdl (__in_opt PMDL MemoryDescriptorList, __in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
Definition at line 12444 of file iosup.c.
References _4gb, ARGUMENT_PRESENT, ExAllocatePoolWithTag, MmInitializeMdl, MmSizeOfMdl(), NonPagedPool, and NULL.
Referenced by MiAllocatePagesForMdl(), MiCcPrepareReadInfo(), MiZeroPageFileFirstPage(), and NtFreeUserPhysicalPages().
NTKERNELAPI NTSTATUS MmCreateMirror (VOID)
Referenced by NtSetSystemInformation().
NTSTATUS MmCreatePeb (IN PEPROCESS TargetProcess, IN PINITIAL_PEB InitialPeb, OUT PPEB * Base)
Definition at line 5928 of file procsup.c.
References _IMAGE_FILE_HEADER::Characteristics, CmNtCSDVersion, DONTASSERT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _IMAGE_NT_HEADERS::FileHeader, _LARGE_INTEGER::HighPart, IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG, IMAGE_FILE_UP_SYSTEM_ONLY, InitAnsiCodePageDataOffset, InitNlsSectionPointer, InitOemCodePageDataOffset, InitUnicodeCaseTableDataOffset, KeActiveProcessors, KeAttachProcess(), KeDetachProcess(), KeNumberProcessors, _LARGE_INTEGER::LowPart, _IMAGE_OPTIONAL_HEADER::Magic, MEM_TOP_DOWN, MI_INIT_PEB_FROM_IMAGE, MiCreatePebOrTeb(), MmCriticalSectionTimeout, MmGetSessionId(), MmHeapDeCommitFreeBlockThreshold, MmHeapDeCommitTotalFreeThreshold, MmHeapSegmentCommit, MmHeapSegmentReserve, MmMapViewOfSection(), MmMinimumStackCommitInBytes, MmRotatingUniprocessorNumber, NT_SUCCESS, NtBuildNumber, NtGlobalFlag, NtMajorVersion, NtMinorVersion, NULL, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_READONLY, PAGE_SIZE, PROBE_ALIGNMENT, ProbeForReadSmallStructure, ProcessAffinityMask, IMAGE_LOAD_CONFIG_DIRECTORY32::ProcessAffinityMask, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), SEC_NO_CHANGE, Status, STATUS_INVALID_IMAGE_PROTECT, STATUS_SUCCESS, TRUE, and ViewShare.
Referenced by PspCreateProcess().
BOOLEAN MmCreateProcessAddressSpace (IN ULONG MinimumWorkingSetSize, IN PEPROCESS NewProcess, OUT PULONG_PTR DirectoryTableBase)
Definition at line 29 of file procx86.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, FALSE, _MMPTE::Hard, HYPER_SPACE, INITIALIZE_DIRECTORY_TABLE_BASE, InsertTailList(), InterlockedExchangeAddSizeT, KeInitializeSpinLock(), LOCK_EXPANSION, LOCK_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PAGE_COLOR_PTE_PROCESS, MI_PAGE_COLOR_VA_PROCESS, MI_PFN_ELEMENT, MI_SET_GLOBAL_STATE, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiCached, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPdeOffset, MiGetPteOffset, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiRemoveZeroPageMayReleaseLocks(), MiReserveSystemPtes(), MiReturnCommitment, MiSessionAddProcess(), MiUnmapPageInHyperSpace, MiZeroMemoryPte, MM_DBG_COMMIT_PROCESS_CREATE, MM_HIGH_LIMIT, MM_PROCESS_COMMIT_CHARGE, MM_READWRITE, MM_RESAVAIL_ALLOCATE_CREATE_PROCESS, MM_TRACK_COMMIT, MmAvailablePages, MmHyperSpaceEnd, MmProcessColorSeed, MmProcessCommit, MmProcessList, MmSystemRangeStart, MmWorkingSetList, _EPROCESS::NextPageColor, NULL, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PDE_BASE, PS_PROCESS_FLAGS_ADDRESS_SPACE1, PS_SET_BITS, PsGetCurrentProcess(), PTE_BASE, _MMPFN::PteAddress, RtlCopyMemory, RtlRandom(), SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, and ValidPdePde.
Referenced by MmInitializeHandBuiltProcess(), and PspCreateProcess().
NTKERNELAPI NTSTATUS MmCreateSection (__deref_out PVOID * SectionObject, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in PLARGE_INTEGER InputMaximumSize, __in ULONG SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle, __in_opt PFILE_OBJECT FileObject)
Definition at line 403 of file creasect.c.
References _MMSECTION_FLAGS::Accessed, _SECTION::Address, ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::Based, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _LIST_ENTRY::Blink, CcWaitForUninitializeCacheMap(), _SEGMENT::ControlArea, _MMSECTION_FLAGS::CopyOnWrite, _SECTION_OBJECT_POINTERS::DataSectionObject, _CONTROL_AREA::DereferenceList, _MMADDRESS_NODE::EndingVpn, _EVENT_COUNTER::Event, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CONTROL_AREA::FilePointer, _MMSECTION_FLAGS::FilePointerNull, _CONTROL_AREA::Flags, _SECTION::Flags, _LIST_ENTRY::Flink, FSRTL_FSP_TOP_LEVEL_IRP, FsRtlAcquireToCreateMappedSection(), FsRtlGetFileSize(), FsRtlReleaseFile(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, _MMSECTION_FLAGS::ImageMappedInSystemSpace, _SECTION::InitialPageProtection, InterlockedDecrement, InterlockedIncrement, IoSetTopLevelIrp(), KeAcquireGuardedMutex(), KeGetPreviousMode, KeReleaseGuardedMutex(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LOCK_PFN, _CONTROL_AREA::LongFlags, _SECTION::LongFlags, _LARGE_INTEGER::LowPart, MI_UNUSED_SEGMENTS_REMOVE_CHARGE, MiCheckControlArea(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreatePagingFileMap(), MiFindEmptyAddressRangeDownBasedTree(), MiFindImageSectionObject(), MiFlushDataSection(), MiFreeEventCounter(), MiGetEventCounter(), MiInsertBasedSection(), MiInsertImageSectionObject(), MiMakeProtectionMask(), MiRemoveImageSectionObject(), MM_INVALID_PROTECTION, MMCONTROL, MmExtendSection(), MmHighSectionBase, MmMakeFileAccess, MmSectionBasedMutex, MmSectionBasedRoot, MmSectionObjectType, _CONTROL_AREA::ModifiedWriteCount, _SUBSECTION::NextSubsection, _MMSECTION_FLAGS::NoChange, NonPagedPool, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfUserReferences, ObCreateObject, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), ObReferenceObject, ObReferenceObjectByHandle, PAGE_EXECUTE_READWRITE, PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_READWRITE, PAGE_WRITECOMBINE, PIRP, _LARGE_INTEGER::QuadPart, _EVENT_COUNTER::RefCount, RemoveEntryList(), _MMSECTION_FLAGS::Rom, RtlCopyMemory, RtlZeroMemory, SEC_BASED, SEC_COMMIT, SEC_IMAGE, SEC_LARGE_PAGES, SEC_NO_CHANGE, SEC_NOCACHE, SEC_RESERVE, _FILE_OBJECT::SectionObjectPointer, _CONTROL_AREA::Segment, _SECTION::Segment, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _SECTION::SizeOfSection, _SEGMENT::SizeOfSegment, _MMADDRESS_NODE::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_FILE_FOR_SECTION, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_6, STATUS_MAPPED_FILE_SIZE_ZERO, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, STATUS_SECTION_TOO_BIG, _SEGMENT::TotalNumberOfPtes, TRUE, _CONTROL_AREA::u, _SECTION::u, UNLOCK_PFN, UNREFERENCED_PARAMETER, _MMSECTION_FLAGS::UserReference, _MMSECTION_FLAGS::UserWritable, _CONTROL_AREA::WaitingForDeletion, _MMSECTION_FLAGS::WasPurged, _CONTROL_AREA::WritableUserReferences, WrVirtualMemory, and X64K.
Referenced by CcInitializeCacheMap(), FsRtlCreateSectionForDataScan(), and NtCreateSection().
NTSTATUS MmCreateTeb (IN PEPROCESS TargetProcess, IN PINITIAL_TEB InitialTeb, IN PCLIENT_ID ClientId, OUT PTEB * Base)
Definition at line 5421 of file procsup.c.
References ASSERT, BBTBuffer, DONTASSERT, except, EXCEPTION_CHAIN_END, EXCEPTION_EXECUTE_HANDLER, KeAttachProcess(), KeDetachProcess(), MiCreatePebOrTeb(), NT_SUCCESS, NULL, OS2_VERSION, PROBE_ALIGNMENT, ProbeForReadSmallStructure, PsGetCurrentProcess(), PtrToUlong, ROUND_TO_PAGES, RtlCopyMemory, _INITIAL_TEB::StackAllocationBase, _INITIAL_TEB::StackBase, _INITIAL_TEB::StackLimit, Status, and _WOW64_PROCESS::Wow64.
Referenced by PspCreateThread().
NTSTATUS MmDbgCopyMemory (IN ULONG64 UntrustedAddress, IN PVOID Buffer, IN ULONG Size, IN ULONG Flags)
Referenced by KiOpSingleProcCopy().
LOGICAL MmDbgIsLowMemOk (IN PFN_NUMBER PageFrameIndex, OUT PPFN_NUMBER NextPageFrameIndex, IN OUT PULONG CorruptionOffset)
VOID MmDeleteKernelStack (IN PVOID PointerKernelStack, IN BOOLEAN LargeStack)
Definition at line 3307 of file procsup.c.
References ASSERT, BYTES_TO_PAGES, _MMPFN::e1, ExQueryDepthSList, _MMPTE::Hard, InterlockedDecrement, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, InterlockedPushEntrySList(), KeNodeBlock, KeNumberNodes, KERNEL_BSTORE_SIZE, KERNEL_LARGE_BSTORE_SIZE, KERNEL_STACK_GUARD_PAGES, KERNEL_STACK_SIZE, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_LARGE_STACK_SIZE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiReleaseSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_RETURN_KERNEL_STACK_DELETE, MM_RESAVAIL_FREE_DELETE_STACK, MM_TRACK_COMMIT, MmDeadStackSListHead, MmKernelStackPages, MmKernelStackResident, MmLargeStacks, MmMaximumDeadKernelStacks, MmProcessCommit, MmSmallStacks, _MMPFN::NextStackPfn, _MMPFNENTRY::PageColor, _MMPTE_HARDWARE::PageFrameNumber, PSLIST_ENTRY, _MMPFN::PteFrame, SystemPteSpace, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by KeInitThread(), KeStartAllProcessors(), KeUninitThread(), PsConvertToGuiThread(), PspReaper(), and PspThreadDelete().
VOID MmDeleteProcessAddressSpace (IN PEPROCESS Process)
Definition at line 1802 of file procsup.c.
References ASSERT, _MMPFN::e1, _MMPFN::e2, HYPER_SPACE, InterlockedExchangeAddSizeT, LOCK_EXPANSION, LOCK_PFN, MI_GET_DIRECTORY_FRAME_FROM_PROCESS, MI_GET_HYPER_PAGE_TABLE_FRAME_FROM_PROCESS, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiContractPagingFiles(), MiDecrementShareCount(), MiGetPpeOffset, MiGetPteOffset, MiGetPxeOffset, MiInsertPageInFreeList(), MiMapPageInHyperSpaceAtDpc(), MiReleaseProcessReferenceToSessionDataPage(), MiReturnCommitment, MiUnmapPageInHyperSpaceFromDpc, MM_DBG_COMMIT_RETURN_PROCESS_DELETE, MM_PROCESS_COMMIT_CHARGE, MM_PROCESS_CREATE_CHARGE, MM_RESAVAIL_FREE_DELETE_PROCESS, MM_TRACK_COMMIT, MmProcessCommit, NULL, PD_PER_SYSTEM, PsGetCurrentProcess(), _MMPFN::PteFrame, RemoveEntryList(), _MMPFN::u3, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, and _MMPFNENTRY::WriteInProgress.
Referenced by PspProcessDelete().
VOID MmDeleteTeb (IN PEPROCESS TargetProcess, IN PVOID TebBase)
Definition at line 6175 of file procsup.c.
References ASSERT, CONTAINING_RECORD, _MMVAD_LONG::EndingVpn, ExFreePool(), _LIST_ENTRY::Flink, IsListEmpty, KeAttachProcess(), KeDetachProcess(), List, _MMSECURE_ENTRY::List, _MMVAD_LONG::List, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_VA_TO_VPN, MiDeleteVirtualAddresses(), MiGetNextVad, MiGetPreviousVad, MiLocateAddress(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), _MMVAD_FLAGS2::MultipleSecured, _MMVAD_FLAGS::NoChange, NT_SUCCESS, NULL, _MMVAD_FLAGS2::OneSecured, PsGetCurrentThread(), ROUND_TO_PAGES, _MMVAD_LONG::StartingVpn, Status, STATUS_NOT_FOUND, STATUS_SUCCESS, _MMVAD_LONG::u, _MMVAD_LONG::u2, _MMVAD_LONG::u3, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_AND_ADDRESS_SPACE, _MMVAD_LONG::VadFlags, and _MMVAD_LONG::VadFlags2.
Referenced by PspCreateThread(), and PspExitThread().
NTSTATUS MmDetachSession (IN PVOID OpaqueSession, IN PRKAPC_STATE ApcState)
Definition at line 3933 of file session.c.
References APC_LEVEL, ASSERT, _MM_SESSION_SPACE::AttachCount, _MM_SESSION_SPACE::AttachEvent, _MM_SESSION_SPACE_FLAGS::DeletePending, FALSE, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, KeGetCurrentIrql(), KeSetEvent(), KeUnstackDetachProcess(), LOCK_EXPANSION, NULL, _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, STATUS_SUCCESS, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by ExGetSessionPoolTagInformation(), ExpWin32SessionCallout(), MmGetSessionMappedViewInformation(), and PspWin32SessionCallout().
POOL_TYPE MmDeterminePoolType (IN PVOID VirtualAddress)
Definition at line 547 of file allocpag.c.
References MI_IS_SESSION_POOL_ADDRESS, MmPagedPoolEnd, MmPagedPoolStart, NonPagedPool, PagedPool, PagedPoolSession, and TRUE.
Referenced by ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExGetBigPoolInfo(), ExInitializeResourceLite(), and ExReinitializeResourceLite().
NTKERNELAPI BOOLEAN MmDisableModifiedWriteOfSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
Definition at line 4491 of file modwrite.c.
References _CONTROL_AREA::Flags, LOCK_PFN, _MMSECTION_FLAGS::NoModifiedWriting, NULL, _CONTROL_AREA::NumberOfMappedViews, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by CcInitializeCacheMap(), CcSetPrivateWriteFile(), and CmPrefetchHivePages().
ULONG MmDoesFileHaveUserWritableReferences (IN PSECTION_OBJECT_POINTERS SectionPointer)
Definition at line 610 of file sectsup.c.
References LOCK_PFN, NULL, UNLOCK_PFN, and _CONTROL_AREA::WritableUserReferences.
VOID MmEmptyAllWorkingSets (VOID)
Definition at line 2236 of file wsmanage.c.
References MI_EMPTY_ALL_WORKING_SETS, MiFullyInitialized, and MiQueueWorkingSetRequest().
Referenced by MiAllocateLargeZeroPages(), MiFindContiguousPages(), MmGatherMemoryForHibernate(), PerfInfoStartLog(), and WmiSetMark().
BOOLEAN MmEnableModifiedWriteOfSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer)
Definition at line 4562 of file modwrite.c.
References _SUBSECTION::ControlArea, _CONTROL_AREA::Flags, _MMPFNLIST::Flink, _MMPFN::Flink, LOCK_PFN2, MI_PFN_ELEMENT, MiGetSubsectionAddress, MiInsertPageInList(), MiUnlinkPageFromList(), MM_EMPTY_LIST, MmModifiedNoWritePageListHead, MmModifiedPageListHead, _MMSECTION_FLAGS::NoModifiedWriting, NULL, _MMPFN::OriginalPte, _MMPFNLIST::Total, TRUE, _CONTROL_AREA::u, _MMPFN::u1, and UNLOCK_PFN2.
Referenced by CcUninitializeCacheMap().
VOID MmEnablePAT (VOID)
Definition at line 14799 of file iosup.c.
References _MMPTE::Long, MI_SET_PTE_WRITE_COMBINE, MiAllMainMemoryMustBeCached, MiWriteCombiningPtes, MM_WRITECOMBINE, MmProtectToPteMask, TRUE, and _MMPTE::u.
Referenced by KiInitializePAT(), and KiInitMachineDependent().
NTSTATUS MmEnforceWorkingSetLimit (IN PEPROCESS Process, IN ULONG Flags)
Definition at line 464 of file wslist.c.
References FALSE, _MMSUPPORT::Flags, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_EXPANSION, LOCK_WS, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MM_FLUID_WORKING_SET, PsGetCurrentProcess(), PsGetCurrentThread(), Status, STATUS_BAD_WORKING_SET_LIMIT, STATUS_SUCCESS, TRUE, UNLOCK_EXPANSION, and UNLOCK_WS.
Referenced by NtSetInformationJobObject(), PspAddProcessToJob(), PspApplyJobLimitsToProcess(), and PspSetQuotaLimits().
NTSTATUS MmExtendSection (IN PVOID SectionToExtend, IN OUT PLARGE_INTEGER NewSectionSize, IN ULONG IgnoreFileSizeChecking)
Definition at line 310 of file extsect.c.
References ASSERT, _LIST_ENTRY::Blink, _MMEXTEND_INFO::CommittedSize, _SEGMENT::ControlArea, _MSUBSECTION::ControlArea, _CONTROL_AREA::DereferenceList, _MSUBSECTION::DereferenceList, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExFreePool(), ExReleaseResourceLite(), _SEGMENT::ExtendInfo, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, FsRtlGetFileSize(), FsRtlSetFileSize(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _LARGE_INTEGER::HighPart, _MMSECTION_FLAGS::Image, _SECTION::InitialPageProtection, KeAcquireGuardedMutex(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseGuardedMutex(), _MMPTE::Long, _MSUBSECTION::LongFlags, _MSUBSECTION::LongFlags2, _LARGE_INTEGER::LowPart, Mi4KStartForSubsection, Mi4KStartFromSubsection, MI_CHECK_SUBSECTION, MI_MAXIMUM_SECTION_SIZE, MI_ROUND_TO_SIZE, MiAppendSubsectionChain(), MiFillMemoryPte, MiGetSubsectionAddressForPte, MM4K_MASK, MM4K_SHIFT, MmAllocationFragment, MMSECT, MmSectionBasedMutex, MmSectionExtendResource, MmSectionExtendSetResource, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NonPagedPool, NT_SUCCESS, NULL, _SUBSECTION::NumberOfFullSectors, _MSUBSECTION::NumberOfFullSectors, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfUserReferences, PAGE_EXECUTE_READWRITE, PAGE_READWRITE, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, PagedPool, _MMSECTION_FLAGS::PhysicalMemory, POOL_MM_ALLOCATION, _MMPTE_SOFTWARE::Protection, _MMSUBSECTION_FLAGS::Protection, _MMPTE_SOFTWARE::Prototype, _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, _MMSECTION_FLAGS::Rom, SATISFY_OVERZEALOUS_COMPILER, _MMSUBSECTION_FLAGS::SectorEndOffset, _SECTION::Segment, _MAPPED_FILE_SEGMENT::SegmentFlags, _MAPPED_FILE_SEGMENT::SegmentPteTemplate, _SECTION::SizeOfSection, _MAPPED_FILE_SEGMENT::SizeOfSegment, _MMPTE::Soft, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SECTION_NOT_EXTENDED, STATUS_SECTION_TOO_BIG, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags, _MMSUBSECTION_FLAGS::SubsectionStatic, _MAPPED_FILE_SEGMENT::TotalNumberOfPtes, _SEGMENT_FLAGS::TotalNumberOfPtes4132, TRUE, _MMPTE::u, _CONTROL_AREA::u, _SUBSECTION::u, _MSUBSECTION::u, _MSUBSECTION::u2, _SUBSECTION::UnusedPtes, _MSUBSECTION::UnusedPtes, and _MMSECTION_FLAGS::WasPurged.
Referenced by CcInitializeCacheMap(), CcSetFileSizes(), MmCreateSection(), NtAllocateVirtualMemory(), and NtExtendSection().
NTKERNELAPI BOOLEAN MmFlushImageSection (__in PSECTION_OBJECT_POINTERS SectionPointer, __in MMFLUSH_TYPE FlushType)
Definition at line 3106 of file flushsec.c.
References ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, CheckImageSection, CONTAINING_RECORD, FALSE, _CONTROL_AREA::Flags, _LARGE_CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, IsListEmpty, LOCK_PFN, MiCheckControlArea(), MiCheckControlAreaStatus(), MiCleanSection(), MmFlushForDelete, NOTHING, NULL, _CONTROL_AREA::NumberOfMappedViews, _LARGE_CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfUserReferences, TRUE, _CONTROL_AREA::u, _LARGE_CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by MiCanFileBeTruncatedInternal().
NTSTATUS MmFlushSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset OPTIONAL, IN SIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus, IN ULONG Flags)
Definition at line 715 of file flushsec.c.
References ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, BYTE_OFFSET, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _ETHREAD::ForwardClusterOnly, FsRtlAcquireFileForCcFlushEx(), FsRtlReleaseFileForCcFlush(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, KeDelayExecutionThread(), KernelMode, _MAPPED_FILE_SEGMENT::LastSubsectionHint, LOCK_PFN, MiCheckControlArea(), MiDecrementSubsections(), MiFlushSectionInternal(), MiIsAddressValid(), MiReferenceSubsection(), MM_FLUSH_ACQUIRE_FILE, MmShortTime, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, PAGE_SHIFT, _MMSECTION_FLAGS::PhysicalMemory, PsGetCurrentThread(), _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, STATUS_FILE_LOCK_CONFLICT, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by CcFlushCache(), CcMapAndCopy(), CcMdlWriteComplete2(), CcPurgeAndClearCacheSection(), CcSetFileSizes(), CcUnpinRepinnedBcb(), and MiFlushDataSection().
NTSTATUS MmFlushVirtualMemory (IN PEPROCESS Process, IN OUT PVOID * BaseAddress, IN OUT PSIZE_T RegionSize, OUT PIO_STATUS_BLOCK IoStatus)
Definition at line 281 of file flushsec.c.
References ASSERT, _MMVAD::ControlArea, _MMVAD::EndingVpn, FALSE, _CONTROL_AREA::FilePointer, FsRtlAcquireFileForCcFlushEx(), FsRtlReleaseFileForCcFlush(), KeAreAllApcsDisabled(), KeDelayExecutionThread(), KeMemoryBarrier(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_IS_SESSION_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_VA_TO_VPN, MI_VPN_TO_VA_ENDING, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiFlushDirtyBitsToPfn(), MiFlushRelease(), MiFlushSectionInternal(), MiGetPdeAddress, MiGetPpeAddress, MiGetProtoPteAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiLocateAddress(), MiLocateSubsection(), MM_FLUSH_ASYNCHRONOUS, MM_NOIRQL, MmShortTime, MmWorkingSetList, MmWsle, _SUBSECTION::NextSubsection, NT_SUCCESS, NULL, PAGE_ALIGN, PAGE_SIZE, PAGED_CODE, _MMVAD_FLAGS::PrivateMemory, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _SUBSECTION::PtesInSubsection, Status, STATUS_FILE_LOCK_CONFLICT, STATUS_NOT_MAPPED_DATA, STATUS_NOT_MAPPED_VIEW, STATUS_PROCESS_IS_TERMINATING, _SUBSECTION::SubsectionBase, TRUE, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, _MMVAD::VadFlags, VadImageMap, and _MMVAD_FLAGS::VadType.
Referenced by NtFlushVirtualMemory().
NTKERNELAPI BOOLEAN MmForceSectionClosed (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN DelayClose)
Definition at line 1143 of file sectsup.c.
References ASSERT, _MMSECTION_FLAGS::BeingDeleted, CheckBothSection, _CONTROL_AREA::Flags, MiCheckControlAreaStatus(), MiCleanSection(), NULL, _CONTROL_AREA::NumberOfMappedViews, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
NTKERNELAPI VOID MmFreeContiguousMemory (__in PVOID BaseAddress)
Definition at line 9396 of file iosup.c.
References ActiveAndValid, ASSERT, BAD_POOL_CALLER, DRIVER_VERIFIER_DEADLOCK_DETECTION, _MMPFN::e1, _MMPFN::e2, ExFreePool(), KeBugCheckEx(), _MM_DRIVER_VERIFIER_DATA::Level, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiDeferredUnlockPages(), MiFreeLowMemory(), MiGetPteAddress, MiNoLowMemory, MiReturnCommitment, MM_DEMAND_ZERO_WRITE_PTE, MM_RESAVAIL_FREE_CONTIGUOUS2, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmSizeOfNonPagedPoolInBytes, MmUnmapIoSpace(), MmVerifierData, _MMPFN::OriginalPte, PAGE_SHIFT, PAGED_CODE, _MMPFNENTRY::PageLocation, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, SPECIAL_POOL_ADDRESS, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPFN::VerifierAllocation, and VerifierDeadlockFreePool().
Referenced by Ki386ClearIdentityMap(), and MmFreeContiguousMemorySpecifyCache().
NTKERNELAPI VOID MmFreeContiguousMemorySpecifyCache (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in MEMORY_CACHING_TYPE CacheType)
Definition at line 9538 of file iosup.c.
References MmFreeContiguousMemory(), and UNREFERENCED_PARAMETER.
VOID MmFreeDriverInitialization (IN PVOID Section)
Definition at line 2575 of file sysload.c.
References ASSERT, _IMAGE_SECTION_HEADER::Characteristics, _KLDR_DATA_TABLE_ENTRY::DllBase, FALSE, _IMAGE_NT_HEADERS::FileHeader, IMAGE_SCN_MEM_DISCARDABLE, InterlockedExchangeAdd(), MI_DELETE_FLUSH_TB, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_ADDRESS, MiDeleteSystemPageableVm(), MiGetPteAddress, MiReturnCommitment, MM_DBG_COMMIT_RETURN_DRIVER_INIT_CODE, MM_RESAVAIL_FREE_DRIVER_INITIALIZATION, MM_TRACK_COMMIT, MmDriverCommit, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGE_SHIFT, ROUND_TO_PAGES, RtlImageNtHeader(), _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by IopLoadDriver().
VOID MmFreeIndependentPages (IN PVOID VirtualAddress, IN SIZE_T NumberOfBytes)
Definition at line 9788 of file iosup.c.
References APC_LEVEL, ASSERT, BYTES_TO_PAGES, _MMPTE::Hard, KeGetCurrentIrql(), LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiGetPteAddress, MiReleaseSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_INDEPENDENT_PAGES, MM_RESAVAIL_FREE_INDEPENDENT, MM_TRACK_COMMIT, _MMPFN::PteFrame, SystemPteSpace, _MMPTE::u, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by ExDeletePoolTagTable(), and KeStartAllProcessors().
VOID MmFreeLoaderBlock (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 2886 of file mminit.c.
References _MI_MORE_THAN_4GB_, ActiveAndValid, ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, _REGISTRY_MEMORY_RUN::BasePage, _MMPFNENTRY::CacheAttribute, CONTAINING_RECORD, _MMPFN::e1, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), _LIST_ENTRY::Flink, _MMPFN::Flink, _MMPTE::Hard, InterlockedExchangeAddSizeT, KSEG0_BASE, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderNlsData, LoaderOsloaderHeap, LoaderRegistryData, LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MI_FLUSH_ENTIRE_TB, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PFN_DELETED, MI_WRITE_INVALID_PTE, MI_WRITE_ZERO_PTE, MiBootRegistryRuns, MiCached, MiDecrementShareCount(), MiDetermineNode, MiGetPdeAddress, MiGetVirtualAddressMappedByPte, MiInsertPageInFreeList(), MiNoLowMemory, MM_DEMAND_ZERO_WRITE_PTE, MM_READWRITE, MM_VA_MAPPED_BY_PDE, MmBootImageSize, MmFreeBootRegistry(), MmKeepBootRegistry, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmVirtualBias, NonPagedPool, NOTHING, NULL, _MMPFN::OriginalPte, PAGE_SIZE, _PHYSICAL_MEMORY_RUN::PageCount, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _REGISTRY_MEMORY_RUN::PageCount, _MMPFNENTRY::PageLocation, _REGISTRY_MEMORY_RUN::PointerPte, PsGetCurrentThread(), PTE_SHIFT, _MMPFN::PteAddress, RtlZeroMemory, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, UNLOCK_SYSTEM_WS, and _MMPTE_HARDWARE::Valid.
Referenced by Phase1InitializationDiscard().
NTKERNELAPI VOID MmFreeMappingAddress (__in PVOID BaseAddress, __in ULONG PoolTag)
Definition at line 5471 of file iosup.c.
References ASSERT, KeBugCheckEx(), KeGetCurrentIrql(), _MMPTE::Long, MI_IS_PHYSICAL_ADDRESS, MiGetPteAddress, MiReleaseSystemPtes(), MiRemovePteTracker(), MM_HIGHEST_USER_ADDRESS, MmTrackPtes, NULL, PASSIVE_LEVEL, SYSTEM_PTE_MISUSE, SystemPteSpace, and _MMPTE::u.
NTKERNELAPI VOID MmFreeNonCachedMemory (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
Definition at line 12338 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, _MDL::ByteOffset, BYTES_TO_PAGES, ExFreePool(), MiGetPteAddress, MiReleaseSystemPtes(), MmFreePagesFromMdl(), PAGE_ALIGN, _MDL::StartVa, and SystemPteSpace.
NTKERNELAPI VOID MmFreePagesFromMdl (__in PMDL MemoryDescriptorList)
Definition at line 11642 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, APC_LEVEL, ASSERT, _MMPFN::AweAllocation, _MMPFN::AweReferenceCount, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, ExPageLockHandle, InterlockedCompareExchange(), InterlockedExchangeAddSizeT, KeBugCheckEx(), KeGetCurrentIrql(), LOCK_PFN, MDL_IO_SPACE, MDL_PAGES_LOCKED, MEMORY_MANAGEMENT, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PFN(), MI_IS_PFN_DELETED, MI_MAGIC_AWE_PTEFRAME, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MiCached, MiDecrementReferenceCountForAwePage(), MiDecrementReferenceCountInline, MiNotMapped, MiReturnCommitment, MM_DBG_COMMIT_RETURN_MDL_PAGES, MM_EMPTY_LIST, MM_RESAVAIL_FREE_FROM_MDL, MM_TRACK_COMMIT, MmHighestPhysicalPage, MmLockPageableSectionByHandle(), MmMdlPagesAllocated, MmUnlockPageableImageSection(), PAGE_SIZE, _MMPFNENTRY::PageLocation, _MMPFN::PteFrame, ReadForWriteAccess, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and UNLOCK_PFN.
Referenced by __out_bcount(), MiCleanPhysicalProcessPages(), MmFreeNonCachedMemory(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
VOID MmFreeSpecialPool (IN PVOID P)
Referenced by ExFreePoolWithTag().
NTKERNELAPI ULONG MmGatherMemoryForHibernate (IN PMDL Mdl, IN BOOLEAN Wait)
Definition at line 14613 of file iosup.c.
References APC_LEVEL, _MMPFN::e2, FALSE, InterlockedDecrement, InterlockedIncrement, KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, LOCK_PFN2, _MMPTE::Long, MDL_PAGES_LOCKED, MI_DEFER_PFN_HELD, MI_GET_PAGE_COLOR_FROM_PTE, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MI_SET_PFN_DELETED, MiDeferredUnlockPages(), MiDelayPageFaults, MiFlushAllPages(), MiRemoveAnyPage(), Mm30Milliseconds, MM_DEMAND_ZERO_WRITE_PTE, MmEmptyAllWorkingSets(), MmFreePageListHead, MmStandbyPageListByPriority, MmZeroedPageListHead, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, _MMPFN::PteAddress, _MMPFNLIST::Total, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, and X64K.
PFN_NUMBER MmGetDirectoryFrameFromProcess (IN PEPROCESS Process)
Definition at line 7239 of file procsup.c.
References ASSERT, KeGetCurrentIrql(), MI_GET_DIRECTORY_FRAME_FROM_PROCESS, and PASSIVE_LEVEL.
Referenced by ExpCopyProcessInfo(), MmInSwapProcess(), and WmiTraceProcess().
NTSTATUS MmGetExecuteOptions (IN PULONG ExecuteOptions)
Definition at line 2165 of file mmfault.c.
References ASSERT, _KEXECUTE_OPTIONS::DisableThunkEmulation, _KEXECUTE_OPTIONS::ExecuteDisable, _KEXECUTE_OPTIONS::ExecuteDispatchEnable, _KEXECUTE_OPTIONS::ExecuteEnable, _KPROCESS::ExecuteOptions, _KEXECUTE_OPTIONS::ImageDispatchEnable, KeGetCurrentIrql(), MEM_EXECUTE_OPTION_DISABLE, MEM_EXECUTE_OPTION_DISABLE_THUNK_EMULATION, MEM_EXECUTE_OPTION_ENABLE, MEM_EXECUTE_OPTION_EXECUTE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_IMAGE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_PERMANENT, NULL, PASSIVE_LEVEL, _EPROCESS::Pcb, _KEXECUTE_OPTIONS::Permanent, PsGetCurrentProcess(), STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtQueryInformationProcess().
NTSTATUS MmGetFileNameForAddress (IN PVOID ProcessVa, OUT PUNICODE_STRING FileName)
Definition at line 2129 of file sectsup.c.
References ASSERT, _UNICODE_STRING::Buffer, _MMVAD::ControlArea, ExAllocatePoolWithTag, ExFreePool(), _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::Image, _UNICODE_STRING::Length, LOCK_ADDRESS_SPACE, MiLocateAddress(), _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObDereferenceObject(), ObQueryNameString(), ObReferenceObject, PAGED_CODE, PagedPool, _MMVAD_FLAGS::PrivateMemory, PsGetCurrentProcess(), RtlMoveMemory, Status, STATUS_INVALID_ADDRESS, STATUS_NO_MEMORY, STATUS_SECTION_NOT_IMAGE, TRUE, _CONTROL_AREA::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, and _MMVAD::VadFlags.
Referenced by DbgkpPostFakeModuleMessages().
NTSTATUS MmGetFileNameForSection (IN PVOID SectionObject, OUT POBJECT_NAME_INFORMATION * FileNameInfo)
Referenced by DbgkCreateThread(), and DbgkpSectionToFileHandle().
PFILE_OBJECT MmGetFileObjectForSection (IN PVOID Section)
Definition at line 2262 of file sectsup.c.
References ASSERT, KeGetCurrentIrql(), NULL, and PASSIVE_LEVEL.
Referenced by PsReferenceProcessFilePointer().
VOID MmGetImageInformation (OUT PSECTION_IMAGE_INFORMATION Imageinformation)
Definition at line 2349 of file mmfault.c.
References ASSERT, _SEGMENT::ImageInformation, NULL, PsGetCurrentProcess(), _EPROCESS::SectionObject, _SECTION::Segment, and _SEGMENT::u2.
Referenced by NtQueryInformationProcess().
VOID MmGetKernelDumpRange (IN PMM_KERNEL_DUMP_CONTEXT Callback)
PVOID MmGetNextSession (IN PVOID OpaqueSession)
Definition at line 3454 of file session.c.
References APC_LEVEL, ASSERT, CONTAINING_RECORD, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_EXPANSION, MiSessionWsList, NULL, ObDereferenceObject(), ObReferenceObject, _MM_SESSION_SPACE::ProcessList, _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, _EPROCESS::Vm, _MMSUPPORT::VmWorkingSetList, and _MM_SESSION_SPACE::WsListEntry.
Referenced by ExGetSessionPoolTagInformation(), and MmGetSessionMappedViewInformation().
ULONG MmGetNumberOfFreeSystemPtes (VOID)
Definition at line 3234 of file sysptes.c.
References _MMPTE::List, MiAddPtesList, MiLockSystemSpace, MiSpecialPoolExtraCount, MiUnlockSystemSpace, MM_EMPTY_PTE_LIST, MmSystemPteBase, MmTotalFreeSystemPtes, _MMPTE_LIST::NextEntry, and _MMPTE::u.
Referenced by NtQuerySystemInformation().
NTSTATUS MmGetPageFileInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 4652 of file modwrite.c.
References _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MmNumberOfPagingFiles, MmPagingFile, PAGED_CODE, _MMPAGING_FILE::PageFileName, _MMPAGING_FILE::PeakUsage, ROUND_UP, RtlCopyMemory, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by NtQuerySystemInformation().
NTKERNELAPI PHYSICAL_ADDRESS MmGetPhysicalAddress (__in PVOID BaseAddress)
Definition at line 12050 of file iosup.c.
References BYTE_OFFSET, _MMPTE::Hard, KdPrint, _LARGE_INTEGER::LowPart, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, _MMPTE::u, _MMPTE_HARDWARE::Valid, and ZERO_LARGE.
Referenced by Ki386BuildIdentityBuffer(), Ki386ConvertPte(), Ki386CreateIdentityMap(), MmHibernateInformation(), and MmMapUserAddressesToPage().
NTKERNELAPI PPHYSICAL_MEMORY_RANGE MmGetPhysicalMemoryRanges (VOID)
PVOID MmGetPreviousSession (IN PVOID OpaqueSession)
Definition at line 3676 of file session.c.
References APC_LEVEL, ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_EXPANSION, MiSessionWsList, NULL, ObDereferenceObject(), ObReferenceObject, _MM_SESSION_SPACE::ProcessList, _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, _EPROCESS::Vm, and _MM_SESSION_SPACE::WsListEntry.
NTSTATUS MmGetSectionRange (IN PVOID AddressWithinSection, OUT PVOID * StartingSectionAddress, OUT PULONG SizeofSection)
Definition at line 13574 of file iosup.c.
References _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _IMAGE_NT_HEADERS::FileHeader, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), MiLookupDataTableEntry(), _IMAGE_SECTION_HEADER::Misc, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGED_CODE, PsLoadedModuleResource, RtlImageNtHeader(), _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, Status, STATUS_NOT_FOUND, STATUS_SUCCESS, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
PVOID MmGetSessionById (IN ULONG SessionId)
Definition at line 4002 of file session.c.
References APC_LEVEL, ASSERT, CONTAINING_RECORD, _MM_SESSION_SPACE_FLAGS::DeletePending, _MMSUPPORT::Flags, _MM_SESSION_SPACE::Flags, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_EXPANSION, MiSessionWsList, NULL, ObReferenceObject, _MM_SESSION_SPACE::ProcessList, _MM_SESSION_SPACE::SessionId, _MMSUPPORT_FLAGS::SessionLeader, _MM_SESSION_SPACE::u, UNLOCK_EXPANSION, and _EPROCESS::Vm.
Referenced by ExpWin32SessionCallout(), and PspWin32SessionCallout().
ULONG MmGetSessionId (IN PEPROCESS Process)
Definition at line 3333 of file session.c.
References NULL, _MM_SESSION_SPACE::Session, and _MM_SESSION_SPACE::SessionId.
Referenced by ExGetSessionPoolTagInformation(), ExpGetProcessInformation(), IoGetRequestorSessionId(), MiFindImageSectionObject(), MiInsertImageSectionObject(), MmCreatePeb(), MmGetSessionMappedViewInformation(), NtAssignProcessToJobObject(), NtCreateJobObject(), NtQueryInformationProcess(), NtSetInformationProcess(), PsGetCurrentProcessSessionId(), PsGetProcessSessionId(), PsGetThreadSessionId(), PspInitializeProcessSecurity(), PspWin32SessionCallout(), PsShutdownSystem(), RtlpWalkFrameChain(), SeExchangePrimaryToken(), and WmiTraceProcess().
ULONG MmGetSessionIdEx (IN PEPROCESS Process)
Definition at line 3393 of file session.c.
References NULL, _MM_SESSION_SPACE::Session, and _MM_SESSION_SPACE::SessionId.
Referenced by PsGetProcessSessionIdEx().
LCID MmGetSessionLocaleId (VOID)
Definition at line 360 of file session.c.
References _MMSUPPORT::Flags, _MM_SESSION_SPACE::LocaleId, NULL, PAGED_CODE, PsDefaultThreadLocaleId, PsGetCurrentProcess(), _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, and _EPROCESS::Vm.
Referenced by NtQueryDefaultLocale(), and PspUserThreadStartup().
NTSTATUS MmGetSessionMappedViewInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length, IN PULONG SessionId OPTIONAL)
Definition at line 4970 of file mapview.c.
References _MMSESSION::BitmapFailures, ExLockUserBuffer(), ExUnlockUserBuffer(), Index, IoWriteAccess, KeGetPreviousMode, LOCK_SYSTEM_VIEW_SPACE, MmAttachSession(), MmDetachSession(), MmGetNextSession(), MmGetSessionId(), MmQuitNextSession(), MmSessionSpace, NO_BITS_FOUND, NT_SUCCESS, NULL, RtlFindClearBits(), RtlFindLongestRunClear(), _MM_SESSION_SPACE::Session, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _MMSESSION::SystemSpaceBitMap, TRUE, UNLOCK_SYSTEM_VIEW_SPACE, and X64K.
Referenced by NtQuerySystemInformation().
ULONG MmGetSizeOfBigPoolAllocation (IN PVOID StartingAddress)
Definition at line 6042 of file allocpag.c.
References ASSERT, BAD_POOL_CALLER, _RTL_BITMAP::Buffer, BYTES_TO_PAGES, _MMPFN::e1, _MM_PAGED_POOL_INFO::EndOfPagedPoolBitmap, _MMPTE::Hard, KeAcquireGuardedMutex(), KeBugCheckEx(), KeReleaseGuardedMutex(), MEMORY_MANAGEMENT, MI_CHECK_BIT, MI_CONVERT_PHYSICAL_TO_PFN, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_POOL_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiGetPteAddress, MM_SYSTEM_RANGE_START, MmHighestPhysicalPage, MmNonPagedPoolEnd, MmNonPagedPoolEnd0, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmPagedPoolEnd, MmPagedPoolInfo, MmPagedPoolMutex, MmPagedPoolStart, MmSessionSpace, MmSizeOfNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, NonPagedPool, NOTHING, NULL, PAGE_SHIFT, PagedPool, _MM_PAGED_POOL_INFO::PagedPoolAllocationMap, _MM_SESSION_SPACE::PagedPoolInfo, _MM_SESSION_SPACE::PagedPoolMutex, _MM_SESSION_SPACE::PagedPoolStart, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteFrame, RtlCheckBit, SESSION_GLOBAL, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPFN::u4.
Referenced by ExFreePoolWithTag().
HANDLE MmGetSystemPageFile (VOID)
Definition at line 1163 of file modwrite.c.
References _MMPAGING_FILE::FileHandle, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), MmNumberOfPagingFiles, MmPageFileCreationLock, MmPagingFile, NULL, and PAGED_CODE.
NTKERNELAPI PVOID MmGetSystemRoutineAddress (__in PUNICODE_STRING SystemRoutineName)
Definition at line 8276 of file sysload.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), FALSE, _LIST_ENTRY::Flink, HAL_NAME, KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KERNEL_NAME, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MiFindExportedRoutineByName(), MmShortTime, NT_SUCCESS, NULL, PASSIVE_LEVEL, RtlEqualUnicodeString(), RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), Status, and TRUE.
NTSTATUS MmGetVerifierInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Referenced by NtQuerySystemInformation().
NTKERNELAPI PVOID MmGetVirtualForPhysical (__in PHYSICAL_ADDRESS PhysicalAddress)
Definition at line 12137 of file iosup.c.
References BYTE_OFFSET, MI_PFN_ELEMENT, MiGetVirtualAddressMappedByPte, PAGE_SHIFT, and _MMPFN::PteAddress.
NTKERNELAPI NTSTATUS MmGrowKernelStack (__in PVOID CurrentStack)
Definition at line 3531 of file procsup.c.
References KERNEL_LARGE_STACK_COMMIT, and MmGrowKernelStackEx().
NTKERNELAPI NTSTATUS MmGrowKernelStackEx (__in PVOID CurrentStack, __in SIZE_T CommitSize)
Definition at line 3564 of file procsup.c.
References ASSERT, DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _MMPTE::Hard, InterlockedExchangeAddSizeT, KeGetCurrentThread(), LOCK_PFN, _MMPTE::Long, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_LARGE_STACK_SIZE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_SET_PTE_DIRTY, MiEnsureAvailablePageOrWait(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiRemoveAnyPage(), MM_HIGH_LIMIT, MM_KERNEL_DEMAND_ZERO_PTE, MM_NOACCESS, MM_READWRITE, MM_RESAVAIL_ALLOCATE_GROW_STACK, MmAvailablePages, MmKernelStackResident, NULL, PAGE_SIZE, PERFINFO_GROW_STACK, _MMPTE_SOFTWARE::Protection, _MMPTE::Soft, _KTHREAD::StackBase, _KTHREAD::StackLimit, STATUS_NO_MEMORY, STATUS_STACK_OVERFLOW, STATUS_SUCCESS, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MmGrowKernelStack().
VOID MmHibernateInformation (IN PVOID MemoryMap, OUT PULONG_PTR HiberVa, OUT PPHYSICAL_ADDRESS HiberPte)
Definition at line 1185 of file mmsup.c.
References MiGetVirtualAddressMappedByPte, MmCrashDumpPte, MmGetPhysicalAddress(), PO_MEM_CLONE, and PoSetHiberRange().
NTSTATUS MmHotPatchRoutine (PSYSTEM_HOTPATCH_CODE_INFORMATION RemoteInfo)
NTSTATUS MmIdentifyPhysicalMemory (VOID)
Definition at line 744 of file dmpaddr.c.
References ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), LOCK_PFN, MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_PFN_ELEMENT, MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MiIdentifyPfn(), MmPhysicalMemoryBlock, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _PHYSICAL_MEMORY_RUN::PageCount, PASSIVE_LEVEL, PERFINFO_LOG_TYPE_PAGEINMEMORY, PerfInfoLogBytes(), PFN_ID_BUFFERS, RtlZeroMemory, _PHYSICAL_MEMORY_DESCRIPTOR::Run, STATUS_SUCCESS, and UNLOCK_PFN.
Referenced by PerfInfoStopLog().
NTSTATUS MmInitializeHandBuiltProcess (IN PEPROCESS Process, OUT PULONG_PTR DirectoryTableBase)
Definition at line 1498 of file procsup.c.
References ASSERT, _KPROCESS::DirectoryTableBase, ExInitializePushLock(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeQuerySystemTime(), MiAllowWorkingSetExpansion(), MiInsertHandBuiltProcessIntoList(), MmCreateProcessAddressSpace(), MmWorkingSetList, _EPROCESS::Pcb, PsGetCurrentProcess(), STATUS_SUCCESS, _EPROCESS::Vm, and _MMSUPPORT::WorkingSetSize.
Referenced by PspCreateProcess().
NTSTATUS MmInitializeHandBuiltProcess2 (IN PEPROCESS Process)
Definition at line 1586 of file procsup.c.
References ASSERT, CODE_END, CODE_START, _LOCK_HEADER::Count, ExAllocatePoolWithTag, FALSE, InitializeListHead(), KeAttachProcess(), KeDetachProcess(), KeInitializeSpinLock(), _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, LOCK_WS, MI_GET_DIRECTORY_FRAME_FROM_PROCESS, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiAllocateVad(), MiGetPdeAddress, MiGetPdeOffset, MiGetVirtualAddressMappedByPte, MiInsertVad(), MiInsertVadCharges(), MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiUnmapPageInHyperSpace, MM_HIGHEST_VAD_ADDRESS, MM_NOIRQL, MM_READWRITE, MM_SHARED_USER_DATA_VA, MM_VA_MAPPED_BY_PDE, MmInitializeProcessAddressSpace(), MmTrackLockedPages, MmVirtualBias, NonPagedPool, NT_SUCCESS, NULL, PsGetCurrentProcess(), PsGetCurrentThread(), PsInitialSystemProcess, RtlCopyMemory, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, SystemPteSpace, TRUE, UNLOCK_WS, _LOCK_HEADER::Valid, and X64K.
Referenced by PspCreateProcess().
PPHYSICAL_MEMORY_DESCRIPTOR MmInitializeMemoryLimits (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PBOOLEAN IncludedType, IN OUT PPHYSICAL_MEMORY_DESCRIPTOR Memory OPTIONAL)
NTSTATUS MmInitializeProcessAddressSpace (IN PEPROCESS ProcessToInitialize, IN PEPROCESS ProcessToClone OPTIONAL, IN PVOID SectionToMap OPTIONAL, IN OUT PULONG CreateFlags, OUT POBJECT_NAME_INFORMATION *AuditName OPTIONAL)
Definition at line 603 of file procsup.c.
References _2gb, _4gb, _MI_PAGING_LEVELS, ASSERT, _UNICODE_STRING::Buffer, _MMVAD_FLAGS::CommitCharge, _LOCK_HEADER::Count, DemandZeroPte, ExAllocatePoolWithTag, ExFreePool(), ExInitializePushLock(), FALSE, _FILE_OBJECT::FileName, _MMPTE::Hard, HYPER_SPACE, IMAGE_FILE_LARGE_ADDRESS_AWARE, IMAGE_FILE_MACHINE_I386, _SECTION_IMAGE_INFORMATION::ImageCharacteristics, InitializeListHead(), KeAttachProcess(), KeDetachProcess(), KeInitializeGuardedMutex(), KeInitializeSpinLock(), KeQuerySystemTime(), _UNICODE_STRING::Length, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, LOCK_EXPANSION, LOCK_PFN, LOCK_WS, _MMPTE::Long, _SECTION_IMAGE_INFORMATION::Machine, MEM_LARGE_PAGES, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE, MI_PDE_MAPS_LARGE_PAGE, MI_ROUND_TO_SIZE, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiAllocateVad(), MiAllowWorkingSetExpansion(), MiCheckForConflictingVad, MiCloneProcessAddressSpace(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiInitializeWorkingSetList(), MiInsertVad(), MiInsertVadCharges(), MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiUnmapPageInHyperSpace, MiUpdateSystemPdes(), MM_HIGHEST_VAD_ADDRESS, MM_KERNEL_DEMAND_ZERO_PTE, MM_READWRITE, MM_SHARED_USER_DATA_VA, MM_SYSTEM_RANGE_START, MM_USER_PAGE_DIRECTORY_PAGES, MM_USER_PAGE_DIRECTORY_PARENT_PAGES, MM_USER_PAGE_TABLE_PAGES, MM_VA_MAPPED_BY_PDE, MM_VA_MAPPED_BY_PPE, MmAllocationPreference, MmMapViewOfSection(), MmPagedPoolEnd, MmTrackLockedPages, MmWorkingSetList, NonPagedPool, NOTHING, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, PAGE_READWRITE, PAGE_SHIFT, PAGE_SIZE, PagedPool, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PROCESS_CREATE_FLAGS_LARGE_PAGES, PS_CLEAR_BITS, PS_PROCESS_FLAGS_ADDRESS_SPACE1, PS_PROCESS_FLAGS_ADDRESS_SPACE2, PS_PROCESS_FLAGS_OVERRIDE_ADDRESS_SPACE, PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED, PS_PROCESS_FLAGS_VM_TOP_DOWN, PS_PROCESS_FLAGS_WOW64_4GB_VA_SPACE, PS_SET_BITS, PsGetCurrentThread(), PsMapSystemDll(), PTE_PER_PAGE, RtlZeroMemory, SeInitializeProcessAuditName(), Status, STATUS_NO_MEMORY, STATUS_SECTION_NOT_IMAGE, STATUS_SUCCESS, strcpy(), _SECTION_IMAGE_INFORMATION::SubSystemMajorVersion, _SECTION_IMAGE_INFORMATION::SubSystemMinorVersion, SystemPteSpace, TRUE, _MMPTE::u, _MMVAD::u, UNLOCK_EXPANSION, UNLOCK_PFN, UNLOCK_WS, VAD_BITMAP_SPACE, _MMVAD::VadFlags, _MMPTE_HARDWARE::Valid, _LOCK_HEADER::Valid, ViewShare, _WOW64_PROCESS::Wow64, X64K, and ZERO_LARGE.
Referenced by MiInitMachineDependent(), MmInitializeHandBuiltProcess2(), and PspCreateProcess().
BOOLEAN MmInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 337 of file mminit.c.
References _1gb, _2gb, _4gb, _MMPAGE_FILE_EXPANSION::ActualExpansion, ASSERT, atol(), _PHYSICAL_MEMORY_RUN::BasePage, BBTPagesToReserve, _MMPFNLIST::Blink, CODE_START, CONTAINING_RECORD, DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPAGE_FILE_EXPANSION::Event, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExInitializePushLock(), ExInitializeResourceLite(), ExPageLockHandle, ExpMultiUserTS, ExReleaseResourceLite(), FALSE, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, _MMPFNLIST::Flink, _MMPTE::Hard, InitializeListHead(), InitializeObjectAttributes, InitializeSListHead(), _MMPAGE_FILE_EXPANSION::InProgress, INSTALL_MORE_MEMORY, Int32x32To64, InterlockedDecrement, InterlockedPushEntrySList(), KeBalanceSetManager(), KeBugCheckEx(), KeFeatureBits, KeInitializeDpc(), KeInitializeEvent(), KeInitializeGuardedMutex(), KeInitializeMutant(), KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitializeTimerEx(), KeNodeBlock, KeNumberNodes, KeSwapProcessOrStack(), KF_LARGE_PAGE, KI_USER_SHARED_DATA, KSEG0_BASE, LDRP_ENTRY_NATIVE, _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMWORKING_SET_EXPANSION_HEAD::ListHead, _MMPFNLIST::ListName, LoaderBad, LoaderBBTMemory, LoaderFirmwarePermanent, LoaderMaximum, LoaderSpecialMemory, _MMDEREFERENCE_SEGMENT_HEADER::Lock, LOCK_PFN, _MMPTE::Long, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, MAXLONG, MI_EXTEND_ANY_PAGEFILE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_INITIALIZE_DYNAMIC_MEMORY_LOCK, MI_MAKE_VALID_KERNEL_PTE, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MI_ROUND_TO_SIZE, MI_SESSION_DEFAULT_IMAGE_SIZE, MI_SESSION_DEFAULT_POOL_SIZE, MI_SESSION_DEFAULT_VIEW_SIZE, MI_SESSION_SPACE_DEFAULT_TOTAL_SIZE, MI_SESSION_SPACE_MAXIMUM_TOTAL_SIZE, MI_SESSION_SPACE_STRUCT_SIZE, MI_SESSION_SPACE_WS_SIZE, MI_SYSTEM_PAGE_COLOR, MI_WRITE_VALID_PTE, MiAddExtraSystemPteRanges(), MiAddHalIoMappings(), MiAddSystemPtes(), MiAdjustWorkingSetManagerParameters(), MiBuildPagedPool(), MiChargeCommitmentCantExpand(), MiEnableKernelVerifier(), MiEnablePagingTheExecutive(), MiExpansionPoolPagesInitialCharge, MiFullyInitialized, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetSubsectionAddress, MiGetSubsectionAddressForPte, MiGetVirtualAddressMappedByPte, MiHighestUserPde, MiHighestUserPte, MiHotPatchList, MiIncrementSystemPtes(), MiInitializeCacheOverrides(), MiInitializeCommitment(), MiInitializeDriverLargePageList(), MiInitializeDriverVerifierList(), MiInitializeIoTrackers(), MiInitializeLargePageSupport(), MiInitializeLoadedModuleList(), MiInitializeMemoryEvents(), MiInitializePfnAndMakePteValid(), MiInitializePfnTracing(), MiInitializeSessionIds(), MiInitializeSessionWsSupport(), MiInitializeSystemCache(), MiInitializeVerifyingComponents(), MiInitialSystemPageDirectory, MiInitMachineDependent(), MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiMapBBTMemory(), MiMaximumSystemCacheSizeExtra, MiMaximumWorkingSet, MiMemorySan(), MiModifiedPageWriter(), MiModifiedPageWriterTimerDispatch(), MiNoLowMemory, MiPagesInLoaderBlock(), MiProtoAddressForPte, MiPteRanges, MiPteToProto, MiReloadBootLoadedDrivers(), MiRemoveLowPages(), MiRemoveZeroPage(), MiReportPhysicalMemory(), MiRequestedSystemPtes, MiSafeBooted, MiSectionInitialization(), MiSessionBasePte, MiSessionImageEnd, MiSessionImagePteEnd, MiSessionImagePteStart, MiSessionImageStart, MiSessionLastPte, MiSessionPoolEnd, MiSessionPoolStart, MiSessionSpaceEnd, MiSessionSpacePageTables, MiSessionSpaceWs, MiSessionViewStart, MiSessionWideInitializeAddresses(), MiStartZeroPageWorkers(), MiSyncCachedRanges(), MiSystemCacheEndExtra, MiSystemCacheStartExtra, MiSystemViewStart, MiTempEvent, MiTriageSystem(), MiTrimInProgressCount, MiUseMaximumSystemSpace, MiUseMaximumSystemSpaceEnd, MiVerifyAllDrivers, MiWriteProtectSystemImage(), MM_ALLOCATION_FRAGMENT, MM_ALLOCATION_FRAGMENT_MAX, MM_DBG_COMMIT_EXTRA_SYSTEM_PTES, MM_DEFAULT_SYSTEM_PTES, MM_DEMAND_ZERO_WRITE_PTE, MM_EMPTY_LIST, MM_FLUID_PHYSICAL_PAGES, MM_MAXIMUM_SYSTEM_PTES, MM_MAXIMUM_WORKING_SET, MM_MB_MAPPED_BY_PDE, MM_MEDIUM_SYSTEM, MM_MINIMUM_SYSTEM_PTES, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NONPAGED_POOL_END, MM_READONLY, MM_SESSION_SPACE_DEFAULT, MM_SESSION_SPACE_DEFAULT_END, MM_SHARED_USER_DATA_VA, MM_SMALL_SYSTEM, MM_SPECIAL_POOL_PTES, MM_SYSTEM_CACHE_END, MM_SYSTEM_VIEW_SIZE, MM_TRACK_COMMIT, MM_VA_MAPPED_BY_PDE, MmAllocationFragment, MmAllocationPreference, MmAttemptForCantExtend, MmAvailablePages, MmAvailablePagesEvent, MmAvailablePagesEventHigh, MmBootImageSize, MmCodeClusterSize, MmCollidedFlushEvent, MmCollidedLockEvent, MmConsumedPoolPercentage, MmCriticalSectionTimeout, MmCritsectTimeoutSeconds, MmDataClusterSize, MmDeadStackSListHead, MmDereferenceSegmentHeader, MmEnforceWriteProtection, MmEventCountSListHead, MmExpansionLock, MmFreedExpansionPoolMaximum, MmHeapDeCommitFreeBlockThreshold, MmHeapDeCommitTotalFreeThreshold, MmHeapSegmentCommit, MmHeapSegmentReserve, MmHighestPhysicalPage, MmHighestPossiblePhysicalPage, MmHighestUserAddress, MmHighSectionBase, MmInitializeMemoryLimits(), MmInPageSupportMinimum, MmInPageSupportSListHead, MmIsVerifierEnabled(), MmLargePageDriverBufferLength, MmLargeSystem, MmLockPageableCodeSection, MmLowestPhysicalPage, MmMappedFileIoComplete, MmMaximumDeadKernelStacks, MmMaximumWorkingSetSize, MmMediumSystem, MmMinimumFreePages, MmModifiedPageLifeInSeconds, MmModifiedPageMaximum, MmModifiedPageWriterEvent, MmNonPagedSystemStart, MmNumberOfPhysicalPages, MmNumberOfSystemPtes, MmPagedPoolEnd, MmPagedPoolMaximumDesired, MmPagedPoolStart, MmPageFaultNotifyRoutine, MmPageFileCreationLock, MmPfnDereferenceSListHead, MmProductType, MmProtectedPteLock, MmProtectFreedNonPagedPool, MmReadClusterSize, MmResidentAvailableAtInit, MmResidentAvailablePages, MmSecondaryColors, MmSectionBasedMutex, MmSectionCommitMutex, MmSectionExtendResource, MmSectionExtendSetResource, MmSessionBase, MmSessionImageSize, MmSessionPoolSize, MmSessionSize, MmSessionSpace, MmSessionSpecialPoolEnd, MmSessionSpecialPoolStart, MmSessionViewSize, MmShutdownSystem(), MmSizeOfPagedPoolInBytes, MmSizeOfSystemCacheInPages, MmSmallSystem, MmSnapUnloads, MmSpecialPoolTag, MmStandbyPageListByPriority, MmSystemCacheEnd, MmSystemCacheStart, MmSystemCacheWorkingSetList, MmSystemCacheWs, MmSystemCacheWsMinimum, MmSystemLoadLock, MmSystemRangeStart, MmSystemSize, MmSystemViewSize, MmThrottleBottom, MmThrottleTop, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTrackLockedPages, MmTrackPtes, MmUnlockPageableImageSection(), MmUnusedSegmentCleanup, MmUnusedSegmentList, MmUnusedSubsectionList, MmUserProbeAddress, MmVerifyDriverBufferLength, MmVerifyDriverLevel, MmVirtualBias, MmWorkingSetExpansionHead, MmWorkingSetManagerEvent, MmZeroingPageEvent, MmZeroingPageThreadActive, NON_PAGED_SYSTEM_END, NonPagedPool, NotificationEvent, NT_SUCCESS, NtProductLanManNt, NtProductServer, NtProductWinNt, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _IMAGE_NT_HEADERS::OptionalHeader, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, PAGE_SHIFT, PAGE_SIZE, _PHYSICAL_MEMORY_RUN::PageCount, PagedPool, _MMPAGE_FILE_EXPANSION::PageFileNumber, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PsCreateSystemThread(), PSLIST_ENTRY, PsLoadedModuleList, PsLoadedModuleResource, PTE_PER_PAGE, PTE_SHIFT, _LARGE_INTEGER::QuadPart, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, ROUND_TO_PAGES, RtlClearAllBits(), RtlCopyMemory, RtlImageNtHeader(), RtlInitializeBitMap(), RtlSetBits(), _PHYSICAL_MEMORY_DESCRIPTOR::Run, SAFEBOOT_LOAD_OPTION_A, _MMPAGE_FILE_EXPANSION::Segment, _MMDEREFERENCE_SEGMENT_HEADER::Semaphore, SharedUserData, StandbyPageList, _MI_PTE_RANGES::StartingVa, strstr(), SynchronizationEvent, SynchronizationTimer, SystemPteSpace, THREAD_ALL_ACCESS, _MMPFNLIST::Total, TRUE, _MMPTE::u, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, ValidKernelPde, ValidKernelPte, _MMSUPPORT::WorkingSetMutex, and ZwClose().
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
VOID MmInPageKernelStack (IN PKTHREAD Thread)
Definition at line 4179 of file procsup.c.
References ASSERT, FLG_DISABLE_PAGE_KERNEL_STACKS, _KERNEL_STACK_SEGMENT::InitialStack, _KERNEL_STACK_SEGMENT::KernelStack, MI_LARGE_STACK_SIZE, MiInPageSingleKernelStack(), NtGlobalFlag, PAGE_SIZE, _KERNEL_STACK_SEGMENT::StackBase, _KERNEL_STACK_SEGMENT::StackLimit, and TRUE.
Referenced by KiInSwapKernelStacks().
VOID MmInSwapProcess (IN PKPROCESS Process)
Definition at line 4842 of file procsup.c.
References _MI_PAGING_LEVELS, ASSERT, CONTAINING_RECORD, _MMPFN::Event, FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MMPTE::Flush, HandleToUlong, _MMPTE::Hard, HYPER_SPACE, INITIALIZE_DIRECTORY_TABLE_BASE, InsertTailList(), _MMWORKING_SET_EXPANSION_HEAD::ListHead, LOCK_EXPANSION, LOCK_PFN, _MMPTE::Long, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPdeAddress, MiGetPdeOffset, MiGetPpeAddress, MiGetPpeOffset, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetPxeOffset, MiMakeOutswappedPageResident(), MiMapPageInHyperSpaceAtDpc(), MiSessionInSwapProcess(), MiUnmapPageInHyperSpaceFromDpc, MiUpdateSystemPdes(), MM_PROCESS_COMMIT_CHARGE, MM_WS_SWAPPED_OUT, MmGetDirectoryFrameFromProcess(), MmPaeMask, MmWorkingSetExpansionHead, MmWorkingSetList, _EPROCESS::PaeTop, PAGE_SHIFT, _PERFINFO_SWAPPROCESS_INFORMATION::PageDirectoryBase, _EPROCESS::PageDirectoryPte, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, _EPROCESS::PdeUpdateNeeded, PERF_MEMORY, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_INSWAPPROCESS, PerfInfoLogBytes(), _PERFINFO_SWAPPROCESS_INFORMATION::ProcessId, PS_CLEAR_BITS, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_OUTSWAP_ENABLED, PS_PROCESS_FLAGS_OUTSWAPPED, PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, _EPROCESS::Vm, _MMSUPPORT::WorkingSetExpansionLinks, _EPROCESS::WorkingSetPage, _MMSUPPORT::WorkingSetSize, and _MMPFN::WsIndex.
Referenced by KiInSwapProcesses().
NTKERNELAPI BOOLEAN MmIsAddressValid (__in PVOID VirtualAddress)
Definition at line 6157 of file pagfault.c.
References FALSE, and MiIsAddressValid().
Referenced by KiInvokeBugCheckEntryCallbacks(), KiPcToFileHeader(), KiScanBugCheckCallbackList(), MiDetachSession(), MiInitMachineDependent(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiRemoveImageSessionWide(), MiSessionAddProcess(), MiSessionCreateInternal(), MiSessionRemoveProcess(), MiSessionWideReserveImageAddress(), MiShareSessionImage(), MmCommitSessionMappedView(), MmMapViewInSessionSpace(), MmSessionCreate(), MmSessionDelete(), MmSessionSetUnloadAddress(), MmUnmapViewInSessionSpace(), MmWorkingSetManager(), and RtlpWalkFrameChain().
NTKERNELAPI LOGICAL MmIsDriverVerifying (__in struct _DRIVER_OBJECT * DriverObject)
LOGICAL MmIsFileObjectAPagingFile (IN PFILE_OBJECT FileObject)
Definition at line 1206 of file modwrite.c.
References FALSE, _MMPAGING_FILE::File, MmNumberOfPagingFiles, MmPagingFile, and TRUE.
Referenced by FsRtlIsPagingFile(), and IoPageRead().
NTKERNELAPI LOGICAL MmIsIoSpaceActive (__in PHYSICAL_ADDRESS StartAddress, __in SIZE_T NumberOfBytes)
Definition at line 3078 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, _MDL::ByteOffset, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, InterlockedIncrement, MI_IS_PFN(), MiActiveIoCounter, MiTrackIoLock, MM_EMPTY_LIST, _MDL::Next, _SINGLE_LIST_ENTRY::Next, NULL, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, _MDL::StartVa, and TRUE.
LOGICAL MmIsMemoryAvailable (IN PFN_NUMBER PagesDesired)
Definition at line 273 of file wsmanage.c.
References ASSERT, FALSE, KeDelayExecutionThread(), KeGetCurrentIrql(), KernelMode, KeSetEvent(), MiHardTrim, Mm30Milliseconds, MmAvailablePages, MmPlentyFreePages, MmPlentyFreePagesValue, MmTotalClaim, MmWorkingSetManagerEvent, PASSIVE_LEVEL, Status, and TRUE.
DECLSPEC_DEPRECATED_DDK NTKERNELAPI BOOLEAN MmIsNonPagedSystemAddressValid (__in PVOID VirtualAddress)
Definition at line 1124 of file mmsup.c.
References FALSE, MiSessionSpaceEnd, MmIsSpecialPoolAddress(), MmPagedPoolEnd, MmPagedPoolStart, MmQuerySpecialPoolBlockType(), MmSessionBase, PagedPool, and TRUE.
Referenced by MmBuildMdlForNonPagedPool().
LOGICAL MmIsSessionAddress (IN PVOID VirtualAddress)
Definition at line 6012 of file allocpag.c.
References MI_IS_SESSION_ADDRESS.
Referenced by ExpWin32SessionCallout(), KeBugCheck2(), PspWin32SessionCallout(), and RtlpWalkFrameChain().
LOGICAL MmIsSpecialPoolAddress (IN PVOID VirtualAddress)
Referenced by ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExQueryPoolBlockSize(), ExReturnPoolQuota(), KeBugCheck2(), and MmIsNonPagedSystemAddressValid().
LOGICAL MmIsSpecialPoolAddressFree (IN PVOID VirtualAddress)
Referenced by KeBugCheck2().
LOGICAL MmIsSystemAddressLocked (IN PVOID VirtualAddress)
Definition at line 14858 of file iosup.c.
References _MMPFN::e2, _MMPFN::Event, FALSE, IS_SYSTEM_ADDRESS, LOCK_PFN2, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_PROCESS_SPACE_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, MiIsAddressValid(), NULL, _MMPFN::ShareCount, TRUE, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN2.
NTKERNELAPI BOOLEAN MmIsThisAnNtAsSystem (VOID)
Definition at line 4818 of file mminit.c.
References MmProductType.
Referenced by CcInitializeCacheManager(), ExpWorkerInitialization(), FsRtlInitializeTunnels(), IoInitSystem(), MiBuildPagedPool(), ObInitSystem(), and PsChangeQuantumTable().
NTKERNELAPI NTSTATUS MmIsVerifierEnabled (__out PULONG VerifierFlags)
Referenced by InitializePool(), and MmInitSystem().
NTSTATUS MmLoadSystemImage (IN PUNICODE_STRING ImageFileName, IN PUNICODE_STRING NamePrefix OPTIONAL, IN PUNICODE_STRING LoadedBaseName OPTIONAL, IN ULONG LoadFlags, OUT PVOID * Section, OUT PVOID * ImageBaseAddress)
Definition at line 761 of file sysload.c.
References _wcsnicmp(), _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _SEGMENT::BasedAddress, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, _IMAGE_FILE_HEADER::Characteristics, _NON_PAGED_DEBUG_INFO::Characteristics, _KLDR_DATA_TABLE_ENTRY::CheckSum, _IMAGE_OPTIONAL_HEADER::CheckSum, _NON_PAGED_DEBUG_INFO::CheckSum, CONTAINING_RECORD, _SEGMENT::ControlArea, _IMAGE_OPTIONAL_HEADER::DataDirectory, DbgBreakPoint(), DbgLoadImageSymbols(), DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, DPFLTR_WARNING_LEVEL, _KLDR_DATA_TABLE_ENTRY::EntryPoint, _IO_ERROR_LOG_PACKET::ErrorCode, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FILE_ATTRIBUTE_NORMAL, FILE_EXECUTE, FILE_OVERWRITE_IF, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SYNCHRONOUS_IO_NONALERT, _IMAGE_NT_HEADERS::FileHeader, _CONTROL_AREA::FilePointer, _IO_ERROR_LOG_PACKET::FinalStatus, _KLDR_DATA_TABLE_ENTRY::Flags, _NON_PAGED_DEBUG_INFO::Flags, _CONTROL_AREA::Flags, FLG_SHOW_LDR_SNAPS, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::FloppyMedia, _KLDR_DATA_TABLE_ENTRY::FullDllName, IMAGE_ADDRESSING_MODE_32BIT, IMAGE_DIRECTORY_ENTRY_DEBUG, _IMAGE_INFO::ImageAddressingMode, _IMAGE_INFO::ImageBase, _NON_PAGED_DEBUG_INFO::ImageBase, _IMAGE_INFO::ImageSectionNumber, _IMAGE_INFO::ImageSelector, _IMAGE_INFO::ImageSize, InitializeObjectAttributes, InterlockedCompareExchange(), InterlockedOr(), IoAllocateGenericErrorLogEntry(), IoWriteErrorLogEntry(), KdDebuggerEnabled, KdDebuggerNotPresent, KdPrint, KdPullRemoteFile(), KeCompactServiceTable(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseMutant(), KernelMode, KeSweepIcache, KeWaitForSingleObject(), LDRP_DEBUG_SYMBOLS_LOADED, LDRP_ENTRY_NATIVE, LDRP_ENTRY_PROCESSED, LDRP_LOAD_IN_PROGRESS, LDRP_MM_LOADED, LDRP_NON_PAGED_DEBUG_INFO, LDRP_SYSTEM_MAPPED, LdrRelocateImage(), _UNICODE_STRING::Length, _KLDR_DATA_TABLE_ENTRY::LoadCount, _KLDR_DATA_TABLE_ENTRY::LoadedImports, LookupEntryPoint(), _IMAGE_FILE_HEADER::Machine, _NON_PAGED_DEBUG_INFO::Machine, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, MAXIMUM_FILENAME_LENGTH, _UNICODE_STRING::MaximumLength, MAXUCHAR, MI_IS_SESSION_ADDRESS, MI_LOG_SESSION_DATA_START, MI_ROUND_TO_SIZE, MiApplyDriverVerifier(), MiCacheImageSymbols(), MiCaptureImageExceptionValues(), MiEnablePagingOfDriver(), MiFirstDriverLoadEver, MiGetPteAddress, MiLoadImageSection(), MiProcessLoaderEntry(), MiResolveImageReferences(), MiSessionInsertImage(), MiSessionProcessGlobalSubsections(), MiSetSystemCodeProtection(), MiUseLargeDriverPage(), MiWriteProtectSystemImage(), MM_EXECUTE_WRITECOPY, MM_LOAD_IMAGE_AND_LOCKDOWN, MM_LOAD_IMAGE_IN_SESSION, MmCheckSystemImage(), MmIsRetryIoStatus, MmSectionObjectType, MmUnloadSystemImage(), NO_IMPORTS_USED, NON_PAGED_DEBUG_SIGNATURE, _KLDR_DATA_TABLE_ENTRY::NonPagedDebugInfo, NonPagedPool, NT_SUCCESS, NtGlobalFlag, NULL, _IMAGE_OPTIONAL_HEADER::NumberOfRvaAndSizes, _IO_ERROR_LOG_PACKET::NumberOfStrings, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_NAME_PATH_SEPARATOR, ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_EXECUTE, PAGE_SHIFT, PAGED_CODE, PagedPool, _KLDR_DATA_TABLE_ENTRY::PatchInformation, POOL_COLD_ALLOCATION, PpPagePathAssign(), _IMAGE_INFO::Properties, PS_PROCESS_FLAGS_IN_SESSION, PsCallImageNotifyRoutines(), PsGetCurrentProcess(), PsImageNotifyEnabled, PsLoadedModuleList, PtrToUlong, RtlAnsiStringToUnicodeString(), RtlAppendUnicodeStringToString(), RtlCopyMemory, RtlEqualUnicodeString(), RtlFreeUnicodeString(), RtlImageNtHeader(), RtlInitAnsiString(), RtlInitString(), RtlInitUnicodeString(), RtlZeroMemory, SATISFY_OVERZEALOUS_COMPILER, SEC_IMAGE, SECTION_ALL_ACCESS, SECTION_MAP_EXECUTE, SECTION_MAP_READ, _KLDR_DATA_TABLE_ENTRY::SectionPointer, _SECTION::Segment, SharedUserData, _NON_PAGED_DEBUG_INFO::Signature, _IMAGE_DATA_DIRECTORY::Size, _NON_PAGED_DEBUG_INFO::Size, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _IMAGE_OPTIONAL_HEADER::SizeOfImage, _NON_PAGED_DEBUG_INFO::SizeOfImage, sprintf(), Status, STATUS_ALREADY_COMMITTED, STATUS_CONFLICTING_ADDRESSES, STATUS_DRIVER_ENTRYPOINT_NOT_FOUND, STATUS_DRIVER_ORDINAL_NOT_FOUND, STATUS_DRIVER_UNABLE_TO_LOAD, STATUS_IMAGE_ALREADY_LOADED, STATUS_IMAGE_CHECKSUM_MISMATCH, STATUS_IMAGE_MP_UP_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_IMAGE_PROTECT, STATUS_LOG_HARD_ERROR, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PROCEDURE_NOT_FOUND, STATUS_SUCCESS, _IO_ERROR_LOG_PACKET::StringOffset, _IMAGE_INFO::SystemModeImage, _IMAGE_FILE_HEADER::TimeDateStamp, _NON_PAGED_DEBUG_INFO::TimeDateStamp, _SEGMENT::TotalNumberOfPtes, TRUE, _CONTROL_AREA::u, UNICODE_NULL, _IO_ERROR_LOG_PACKET::UniqueErrorValue, _IMAGE_DATA_DIRECTORY::VirtualAddress, wcslen(), WrVirtualMemory, X64K, ZwClose(), ZwCreateSection(), and ZwOpenFile().
Referenced by IopLoadDriver(), MiResolveImageReferences(), and NtSetSystemInformation().
PUNICODE_STRING MmLocateUnloadedDriver (IN PVOID VirtualAddress)
Definition at line 3464 of file sysload.c.
References _UNICODE_STRING::Buffer, Index, MI_UNLOADED_DRIVERS, MmLastUnloadedDriver, _UNLOADED_DRIVERS::Name, NULL, and _UNLOADED_DRIVERS::StartAddress.
Referenced by KeBugCheck2().
NTSTATUS MmLockAndCopyMemory (IN PSYSTEM_HOTPATCH_CODE_INFORMATION PatchInfo, IN KPROCESSOR_MODE ProbeMode)
NTKERNELAPI PVOID MmLockPageableDataSection (__in PVOID AddressWithinSection)
Definition at line 13665 of file iosup.c.
References _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _IMAGE_NT_HEADERS::FileHeader, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), MEMORY_MANAGEMENT, MI_IS_PHYSICAL_ADDRESS, MiLookupDataTableEntry(), _IMAGE_SECTION_HEADER::Misc, MmLockPageableSectionByHandle(), NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGED_CODE, PsLoadedModuleResource, RtlImageNtHeader(), SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
NTKERNELAPI VOID MmLockPageableSectionByHandle (__in PVOID ImageSectionHandle)
Definition at line 12937 of file iosup.c.
References ASSERT, FALSE, InterlockedCompareExchange(), InterlockedDecrement, InterlockedIncrement, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KePulseEvent(), KernelMode, KeWaitForSingleObject(), MI_IS_PHYSICAL_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MiGetPteAddress, MiLockCode(), _IMAGE_SECTION_HEADER::Misc, MM_LOCK_BY_REFCOUNT, MmCollidedLockWait, MmShortTime, MmSystemRangeStart, SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualSize, and WrVirtualMemory.
Referenced by ExpGetLockInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpSystemErrorHandler(), IoUnregisterShutdownNotification(), KeSetPhysicalCacheTypeRange(), KiAmdK6MtrrSetMemoryType(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiResetVirtualMemory(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiShutdownSystem(), MiUnmapLockedPagesInUserSpace(), MmAdjustWorkingSetSizeEx(), MmFreePagesFromMdl(), MmLockPagableSectionByHandle(), MmLockPageableDataSection(), MmMapUserAddressesToPage(), MmUnlockPagedPool(), PspQueryWorkingSetWatch(), and WmipStartLogger().
NTKERNELAPI VOID MmLockPagedPool (IN PVOID Address, IN SIZE_T Size)
Definition at line 14510 of file iosup.c.
References MiGetPteAddress, MiLockCode(), and MM_LOCK_BY_REFCOUNT.
Referenced by MiMakeEntireImageCopyOnWrite().
VOID MmMakeKernelResourceSectionWritable (VOID)
Definition at line 7864 of file sysload.c.
References _MMPTE::Hard, MI_FLUSH_CURRENT_TB, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_KERNEL_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetVirtualAddressMappedByPte, MiKernelResourceStartPte, MM_READWRITE, NULL, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPTE_HARDWARE::Writable, and _MMPTE_HARDWARE::Write.
Referenced by KeGetBugMessageText().
NTKERNELAPI PVOID MmMapLockedPages (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode)
Definition at line 5251 of file iosup.c.
References HighPagePriority, MmCached, MmMapLockedPagesSpecifyCache(), NULL, and TRUE.
NTKERNELAPI PVOID MmMapLockedPagesSpecifyCache (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in MEMORY_CACHING_TYPE CacheType, __in_opt PVOID RequestedAddress, __in ULONG BugCheckOnFailure, __in MM_PAGE_PRIORITY Priority)
Definition at line 1176 of file sysptes.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, ExRemoveHeadNBQueue(), FALSE, _MMPTE::Hard, HIGH_LEVEL, HighPagePriority, Index, InterlockedDecrement, KeBugCheckEx(), KeIsExecutingDpc(), KernelMode, _MMPTE::List, LOCK_PFN2, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_MAPPING_CAN_FAIL, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_PARTIAL_HAS_BEEN_MAPPED, MDL_SOURCE_IS_NONPAGED_POOL, MEMORY_MANAGEMENT, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DISABLE_CACHING, MI_FLUSH_ENTIRE_TB, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiCheckPteReserve(), MiCompareTbFlushTimeStamp(), MiFeedSysPtePool(), MiGetSystemPteAvailability(), MiGetVirtualAddressMappedByPte, MiInsertPteTracker(), MiIssueNoPtesBugcheck(), MiMapLockedPagesInUserSpace(), MiNonCached, MiNonCachedCollisions, MiNotMapped, MiReserveSystemPtes(), MiSystemPteNBHead, MiWriteCombined, MM_EMPTY_LIST, MM_PTE_TABLE_LIMIT, MmMaximumCacheType, MmSysPteIndex, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmTotalFreeSystemPtes, MmTrackPtes, _MMPTE_LIST::NextEntry, NULL, _MMPTE_HARDWARE::PageFrameNumber, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, RtlGetCallersAddress(), SYSPTES_FLUSH_COUNTER_MASK, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, UnpackPTEPointer(), UnpackPTETimeStamp(), _MMPTE_HARDWARE::Valid, ValidKernelPte, and X64K.
Referenced by MiCloneProcessAddressSpace(), MiDoMappedCopy(), MmMapLockedPages(), and NtStartProfile().
NTKERNELAPI PVOID MmMapLockedPagesWithReservedMapping (__in PVOID MappingAddress, __in ULONG PoolTag, __in PMDL MemoryDescriptorList, __in MEMORY_CACHING_TYPE CacheType)
Definition at line 5565 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFNENTRY::CacheAttribute, DISPATCH_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE::Hard, HIGH_LEVEL, KeBugCheckEx(), KeGetCurrentIrql(), LOCK_PFN2, _MMPTE::Long, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_PARTIAL_HAS_BEEN_MAPPED, MDL_SOURCE_IS_NONPAGED_POOL, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DISABLE_CACHING, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiGetPteAddress, MiNonCached, MiNonCachedCollisions, MiNotMapped, MiWriteCombined, MM_EMPTY_LIST, NULL, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteAddress, _MMPFN::PteFrame, SYSTEM_PTE_MISUSE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, ValidKernelPte, and X64K.
NTKERNELAPI VOID MmMapMemoryDumpMdl (__inout PMDL MemoryDumpMdl)
Definition at line 14077 of file iosup.c.
References ASSERT, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPTE::Hard, KiFlushSingleTb(), _MMPTE::Long, MI_DISABLE_CACHING, MI_PFN_ELEMENT, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PAGE, MI_WRITE_ZERO_PTE, MiCached, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MmCrashDumpPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPFN::u3, _MMPTE_HARDWARE::Valid, and ValidKernelPte.
NTKERNELAPI NTSTATUS MmMapUserAddressesToPage (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in PVOID PageAddress)
Definition at line 11834 of file iosup.c.
References ASSERT, _MMVAD::EndingVpn, ExPageLockHandle, FALSE, _EPROCESS::Flags, _MMPTE::Hard, InterlockedExchangePte, LOCK_ADDRESS_SPACE, LOCK_PFN, LOCK_WS_UNSAFE, _MMPTE::Long, MI_FLUSH_PROCESS_TB, MI_FLUSH_SINGLE_TB, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiFillMemoryPte, MiGetPteAddress, MiLocateAddress(), MM_HIGHEST_USER_ADDRESS, MmGetPhysicalAddress(), MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), NULL, PAGE_SHIFT, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _MMVAD::StartingVpn, Status, STATUS_FREE_VM_NOT_AT_BASE, STATUS_INVALID_ADDRESS, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_MEMORY_NOT_ALLOCATED, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MMPTE::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_PFN, UNLOCK_WS_UNSAFE, VadDevicePhysicalMemory, _MMVAD::VadFlags, and _MMVAD_FLAGS::VadType.
NTKERNELAPI NTSTATUS MmMapViewInSessionSpace (__in PVOID Section, __deref_inout_bcount *ViewSize PVOID * MappedBase, __inout PSIZE_T ViewSize)
Definition at line 4747 of file mapview.c.
References ASSERT, _NTSYM::Flags, MiMapViewInSystemSpace(), MmIsAddressValid(), MmSessionSpace, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _MM_SESSION_SPACE::Session, STATUS_NOT_MAPPED_VIEW, and TRUE.
Referenced by MiSessionWideReserveImageAddress().
NTSTATUS MmMapViewInSystemCache (IN PVOID SectionToMap, OUT PVOID * CapturedBase, IN OUT PLARGE_INTEGER SectionOffset, IN OUT PULONG CapturedViewSize)
Definition at line 47 of file mapcache.c.
References APC_LEVEL, ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _MMSECTION_FLAGS::BeingPurged, BYTES_TO_PAGES, _SEGMENT::ControlArea, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _SECTION::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _MMSECTION_FLAGS::Image, KeBugCheckEx(), KeGetCurrentIrql(), KeReadTbFlushTimeStamp(), _MMPTE::List, LOCK_PFN, _MMPTE::Long, MEMORY_MANAGEMENT, MI_FLUSH_ENTIRE_TB, MI_WRITE_INVALID_PTE, MiAddViewsForSection(), MiCheckControlArea(), MiCompareTbFlushTimeStamp(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiMapCacheFailures, MiProtoAddressForKernelPte, MM_COLOR_MASK, MM_EMPTY_LIST, MM_EMPTY_PTE_LIST, MM_FLUSH_COUNTER_MASK, MmFirstFreeSystemCache, MmSystemCacheEnd, MmSystemCachePteBase, _MMPTE_LIST::NextEntry, _SUBSECTION::NextSubsection, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfSystemCacheViews, PAGE_SHIFT, PTE_SHIFT, _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _SECTION::Segment, Status, STATUS_NO_MEMORY, STATUS_NOT_MAPPED_DATA, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MMPTE::u, _CONTROL_AREA::u, _SECTION::u, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and X256K.
Referenced by CcGetVacbMiss(), and Phase1InitializationDiscard().
NTKERNELAPI NTSTATUS MmMapViewInSystemSpace (__in PVOID Section, __deref_inout_bcount *ViewSize PVOID * MappedBase, __inout PSIZE_T ViewSize)
Definition at line 4700 of file mapview.c.
References MiMapViewInSystemSpace(), MmSession, and PAGED_CODE.
Referenced by MiSessionWideReserveImageAddress().
NTKERNELAPI NTSTATUS MmMapViewOfSection (__in PVOID SectionToMap, __in PEPROCESS Process, __deref_inout_bcount *CapturedViewSize PVOID * CapturedBase, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout PLARGE_INTEGER SectionOffset, __inout PSIZE_T CapturedViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in ULONG Win32Protect)
Definition at line 619 of file mapview.c.
References _SEGMENT::ControlArea, FALSE, _CONTROL_AREA::Flags, _SECTION::Flags, _LARGE_INTEGER::HighPart, _MMSECTION_FLAGS::Image, _SEGMENT::ImageCommitment, _SECTION::InitialPageProtection, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, MEM_RESERVE, MiIsProtectionCompatible(), MiMakeProtectionMask(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MM_HIGHEST_VAD_ADDRESS, MM_INVALID_PROTECTION, _MMSECTION_FLAGS::NoCache, PAGE_EXECUTE_READWRITE, PAGE_NOCACHE, PAGE_READWRITE, PAGE_WRITECOMBINE, PAGED_CODE, _MMSECTION_FLAGS::PhysicalMemory, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcess(), _LARGE_INTEGER::QuadPart, _SECTION::Segment, _SECTION::SizeOfSection, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_10, STATUS_INVALID_PARAMETER_5, STATUS_INVALID_PARAMETER_9, STATUS_INVALID_VIEW_SIZE, STATUS_PROCESS_IS_TERMINATING, STATUS_SECTION_PROTECTION, TRUE, _CONTROL_AREA::u, _SECTION::u, _SEGMENT::u1, UNLOCK_ADDRESS_SPACE, and _MMSECTION_FLAGS::WriteCombined.
Referenced by MiLoadImageSection(), MmCreatePeb(), MmInitializeProcessAddressSpace(), NtAcceptConnectPort(), NtMapViewOfSection(), NtSecureConnectPort(), Phase1InitializationDiscard(), and PsMapSystemDll().
NTKERNELAPI NTSTATUS MmMarkPhysicalMemoryAsBad (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
NTKERNELAPI NTSTATUS MmMarkPhysicalMemoryAsGood (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
LOGICAL MmMemoryIsLow (VOID)
NTSTATUS MmMemoryUsage (IN PVOID Buffer, IN ULONG Size, IN ULONG Type, OUT PULONG Length)
Definition at line 569 of file dmpaddr.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtQuerySystemInformation().
VOID MmOutPageKernelStack (IN PKTHREAD Thread)
Definition at line 3917 of file procsup.c.
References _KERNEL_STACK_SEGMENT::ActualLimit, ASSERT, _MMPTE_FLUSH_LIST::Count, FLG_DISABLE_PAGE_KERNEL_STACKS, _MMPTE_FLUSH_LIST::FlushVa, KERNEL_LARGE_STACK_SIZE, KERNEL_STACK_SIZE, _KERNEL_STACK_SEGMENT::KernelStack, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_LARGE_STACK_SIZE, MiOutPageSingleKernelStack(), MM_MAXIMUM_FLUSH_COUNT, NtGlobalFlag, NULL, PAGE_SIZE, SATISFY_OVERZEALOUS_COMPILER, _KERNEL_STACK_SEGMENT::StackBase, _KERNEL_STACK_SEGMENT::StackLimit, and TRUE.
Referenced by KiOutSwapKernelStacks().
VOID MmOutSwapProcess (IN PKPROCESS Process)
Definition at line 4475 of file procsup.c.
References ASSERT, CONTAINING_RECORD, _MMPFN::e1, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MMPTE::Flush, _MMPTE::Hard, LOCK_EXPANSION, LOCK_PFN, _MMPTE::Long, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_HYPER_PAGE_TABLE_FRAME_FROM_PROCESS, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiDecrementShareCount(), MiGetPdeOffset, MiGetPteAddress, MiGetPteOffset, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpace(), MiReleaseSystemPtes(), MiReserveSystemPtes(), MiSessionOutSwapProcess(), MiUnmapPageInHyperSpace, MM_DBG_SWAP_PROCESS, MM_PROCESS_COMMIT_CHARGE, MM_READWRITE, MM_WS_SWAPPED_OUT, MM_WS_TRIMMING, MmWorkingSetList, _MMPFNENTRY::Modified, NOTHING, NULL, _EPROCESS::Outswapped, _EPROCESS::PaeTop, _EPROCESS::PageDirectoryPte, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_BASE, PS_PROCESS_FLAGS_IN_SESSION, PS_PROCESS_FLAGS_OUTSWAP_ENABLED, PS_PROCESS_FLAGS_OUTSWAPPED, PS_SET_BITS, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, RemoveEntryList(), _MMPFN::ShareCount, SystemPteSpace, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_EXPANSION, UNLOCK_PFN, VAD_BITMAP_SPACE, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMSUPPORT::WorkingSetExpansionLinks, _EPROCESS::WorkingSetPage, and _MMSUPPORT::WorkingSetSize.
Referenced by KiOutSwapProcesses().
NTKERNELAPI PVOID MmPageEntireDriver (__in PVOID AddressWithinSection)
Definition at line 3088 of file sysload.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::DllBase, FALSE, KeFlushQueuedDpcs(), MI_IS_SESSION_IMAGE_ADDRESS, MiGetPteAddress, MiLookupDataTableEntry(), MiSetPagingOfDriver(), MM_SYSTEM_CODE_LOCKED_DOWN, MmDisablePagingExecutive, NULL, PAGE_SHIFT, PAGED_CODE, _KLDR_DATA_TABLE_ENTRY::SectionPointer, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, and TRUE.
NTSTATUS MmPerfSnapShotValidPhysicalMemory (VOID)
Definition at line 596 of file dmpaddr.c.
References ActiveAndValid, ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, _MMPFN_MEMSNAP_INFORMATION::Count, _MMPFN::e1, _MMPFN_MEMSNAP_INFORMATION::InitialPageFrameIndex, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_MAXIMUM_PFNID_RUN, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MmPhysicalMemoryBlock, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _PHYSICAL_MEMORY_RUN::PageCount, _MMPFNENTRY::PageLocation, PASSIVE_LEVEL, PERFINFO_LOG_TYPE_MEMORYSNAPLITE, PerfInfoLogBytes(), RtlClearAllBits(), RtlInitializeBitMap(), RtlSetBit(), _PHYSICAL_MEMORY_DESCRIPTOR::Run, STATUS_SUCCESS, and _MMPFN::u3.
Referenced by WmiSetMark().
PFILE_OBJECT* MmPerfUnusedSegmentsEnumerate (VOID)
Definition at line 3213 of file sectsup.c.
References ASSERT, CONTAINING_RECORD, ExAllocatePoolWithTag, ExFreePool(), _CONTROL_AREA::FilePointer, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_PFN, MmUnusedSegmentCount, MmUnusedSegmentList, NonPagedPool, NULL, ObReferenceObject, PASSIVE_LEVEL, and UNLOCK_PFN.
Referenced by PerfInfoFileNameRunDown().
PFILE_OBJECT* MmPerfVadTreeWalk (PEPROCESS Process)
Referenced by PerfInfoFileNameRunDown().
LOGICAL MmPrefetchForCacheManager (IN PFILE_OBJECT FileObject, IN LARGE_INTEGER SectionOffset, IN SIZE_T NumberOfBytes)
NTKERNELAPI NTSTATUS MmPrefetchPages (__in ULONG NumberOfLists, __in_ecount(NumberOfLists) PREAD_LIST * ReadLists)
Referenced by CmpPrefetchHiveFile(), and CmPrefetchHivePages().
NTSTATUS MmPrefetchPagesIntoLockedMdl (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN SIZE_T Length, OUT PMDL * MdlOut)
Definition at line 98 of file buildmdl.c.
References _ETHREAD::ActiveFaultCount, _ETHREAD::ApcNeeded, _MI_READ_INFO::ApiMdl, ASSERT, FALSE, _MI_READ_INFO::FileObject, _MI_READ_INFO::FileOffset, FileOffset, _MI_READ_INFO::InPageSupport, IoRetryIrpCompletions(), KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), _MI_READ_INFO::LengthInBytes, MiCcCompletePrefetchIos(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiCcReleasePrefetchResources(), NT_SUCCESS, NULL, PASSIVE_LEVEL, PsGetCurrentThread(), RtlZeroMemory, STATUS_ISSUE_PAGING_IO, _ETHREAD::Tcb, and TRUE.
NTKERNELAPI VOID MmProbeAndLockPages (__inout PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
Definition at line 256 of file iosup.c.
References _MI_PAGING_LEVELS, ActiveAndValid, ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _AWEINFO::AweVadRoot, DbgBreakPoint(), DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _MMPFN::e1, _MMPFN::e2, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), ExReleaseCacheAwarePushLockShared(), FALSE, _MMPTE::Hard, InterlockedCompareExchangePte, InterlockedExchangeAddSizeT, InterlockedIncrement, IoReadAccess, KeEnterGuardedRegionThread(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KernelMode, LOCK_PFN, LOCK_PFN2, LOCK_TYPE_AWE, LOCK_TYPE_PFN, LOCK_TYPE_WS, LOCK_WS_SHARED, _MMPTE::Long, MDL_DESCRIBES_AWE, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INSTRUMENT_PROBE_RAISES, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_SNAP_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiActiveIoCounter, MiAddMdlTracker(), MiDereferenceIoSpace(), MiFindNodeOrParent(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiReferenceIoSpace(), MM_EMPTY_LIST, MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MM_PTE_COPY_ON_WRITE_MASK, MM_PTE_WRITE_MASK, MM_USER_PROBE_ADDRESS, MmAccessFault(), MmHighestPhysicalPage, MmPagedPoolEnd, MmPagedPoolStart, MmReferenceCountCheck, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmTrackLockedPages, MmUnlockPages(), NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfLockedPages, _MMPTE_HARDWARE::Owner, PAGE_SIZE, _MMPFNENTRY::PageLocation, _EPROCESS::PhysicalVadRoot, _AWEINFO::PhysicalViewHint, ProbeForWriteChar, PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), _AWEINFO::PushLock, RtlGetCallersAddress(), SATISFY_OVERZEALOUS_COMPILER, _MI_PHYSICAL_VIEW::StartingVpn, STATUS_ACCESS_VIOLATION, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_WORKING_SET_QUOTA, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_PFN2, UNLOCK_WS_SHARED, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by BuildQueryDirectoryIrp(), CcMdlRead(), CcPrepareMdlWrite(), CcZeroData(), ExLockUserBuffer(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopProbeAndLockPages(), KiOpPatchCode(), MiDoMappedCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MmProbeAndLockProcessPages(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtReadFile(), NtSetEaFile(), NtStartProfile(), and NtWriteFile().
NTKERNELAPI VOID MmProbeAndLockProcessPages (__inout PMDL MemoryDescriptorList, __in PEPROCESS Process, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
Definition at line 1315 of file iosup.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), MmProbeAndLockPages(), PsGetCurrentProcess(), Status, STATUS_SUCCESS, and TRUE.
NTKERNELAPI VOID MmProbeAndLockSelectedPages (__inout PMDL MemoryDescriptorList, __in PFILE_SEGMENT_ELEMENT PagedSegmentArray, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
Definition at line 1815 of file iosup.c.
References _MI_PAGING_LEVELS, ActiveAndValid, ASSERT, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _AWEINFO::AweVadRoot, _FILE_SEGMENT_ELEMENT::Buffer, BYTES_TO_PAGES, COPY_STACK_SIZE, DbgBreakPoint(), DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _MMPFN::e1, _MMPFN::e2, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), ExAllocatePoolWithTag, ExFreePool(), ExRaiseStatus(), ExReleaseCacheAwarePushLockShared(), FALSE, _MMPTE::Hard, InterlockedCompareExchangePte, InterlockedExchangeAddSizeT, InterlockedIncrement, IoReadAccess, KeEnterGuardedRegionThread(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KernelMode, LOCK_PFN, LOCK_PFN2, LOCK_TYPE_AWE, LOCK_TYPE_NONE, LOCK_TYPE_PFN, LOCK_TYPE_WS, LOCK_WS_SHARED, _MMPTE::Long, MAXULONG_PTR, MDL_DESCRIBES_AWE, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INSTRUMENT_PROBE_RAISES, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_SNAP_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiActiveIoCounter, MiAddMdlTracker(), MiDereferenceIoSpace(), MiFindNodeOrParent(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiReferenceIoSpace(), MM_EMPTY_LIST, MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MM_PTE_COPY_ON_WRITE_MASK, MM_PTE_WRITE_MASK, MmAccessFault(), MmPagedPoolEnd, MmPagedPoolStart, MmReferenceCountCheck, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmTrackLockedPages, MmUnlockPages(), NonPagedPool, NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfLockedPages, _MMPTE_HARDWARE::Owner, PAGE_SIZE, PAGED_CODE, _MMPFNENTRY::PageLocation, _EPROCESS::PhysicalVadRoot, _AWEINFO::PhysicalViewHint, PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), Ptr64ToPtr(), _AWEINFO::PushLock, RtlCopyMemory, RtlGetCallersAddress(), SATISFY_OVERZEALOUS_COMPILER, _MI_PHYSICAL_VIEW::StartingVpn, STATUS_ACCESS_VIOLATION, STATUS_INSUFFICIENT_RESOURCES, STATUS_WORKING_SET_QUOTA, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_PFN2, UNLOCK_WS_SHARED, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by NtReadFileScatter(), and NtWriteFileGather().
NTKERNELAPI NTSTATUS MmProtectMdlSystemAddress (__in PMDL MemoryDescriptorList, __in ULONG NewProtect)
Definition at line 6455 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPTE_HARDWARE::CacheDisable, CONTAINING_RECORD, DISPATCH_LEVEL, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), FALSE, _LIST_ENTRY::Flink, _MMPTE::Hard, InsertHeadList(), IsListEmpty, KeAcquireSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeReleaseSpinLock(), _MM_PTE_MAPPING::ListEntry, _MMPTE::Long, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MEMORY_MANAGEMENT, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_GUARD, MI_IS_NOCACHE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_WRITECOMBINE, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiMakeProtectionMask(), MM_EXECUTE_WRITECOPY, MM_HIGHEST_USER_ADDRESS, MM_INVALID_PROTECTION, MM_MAXIMUM_FLUSH_COUNT, MM_NOACCESS, MM_READWRITE, MM_WRITECOPY, MmProtectedPteList, MmProtectedPteLock, NonPagedPool, NOTHING, NULL, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileLow, _MMPTE_SOFTWARE::Protection, _MM_PTE_MAPPING::Protection, RemoveEntryList(), _MMPTE::Soft, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PAGE_PROTECTION, STATUS_NOT_MAPPED_VIEW, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, _MM_PTE_MAPPING::SystemEndVa, _MM_PTE_MAPPING::SystemVa, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u3, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::WriteThrough.
LOGICAL MmProtectSpecialPool (IN PVOID VirtualAddress, IN ULONG NewProtect)
BOOLEAN MmPurgeSection (IN PSECTION_OBJECT_POINTERS SectionObjectPointer, IN PLARGE_INTEGER Offset OPTIONAL, IN SIZE_T RegionSize, IN ULONG IgnoreCacheViews)
Definition at line 2366 of file flushsec.c.
References APC_LEVEL, ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::BeingDeleted, _MMSECTION_FLAGS::BeingPurged, BYTE_OFFSET, _MSUBSECTION::DereferenceList, DISPATCH_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, InsertTailList(), KeBugCheckEx(), KeGetCurrentIrql(), KeLowerIrql, KernelMode, KeWaitForSingleObject(), _MAPPED_FILE_SEGMENT::LastSubsectionHint, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MI_WRITE_INVALID_PTE, MiCancelWriteOfMappedPfn(), MiCanFileBeTruncatedInternal(), MiCheckControlArea(), MiCheckProtoPtePageState(), MiDecrementShareCountInline, MiDecrementSubsections(), MiGetPteAddress, MiInsertPageInFreeList(), MiIsAddressValid(), MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), MiReferenceSubsection(), MiReleasePageFileSpace(), MiUnlinkPageFromList(), MM_NOIRQL, MmMappedFileIoComplete, MmUnusedSubsectionList, _CONTROL_AREA::ModifiedWriteCount, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, NULL, _CONTROL_AREA::NumberOfMappedViews, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, _CONTROL_AREA::NumberOfSystemCacheViews, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, POOL_CORRUPTION_IN_FILE_AREA, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteAddress, _MMPFN::PteFrame, _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, _MMPFNENTRY::ReadInProgress, RemoveEntryList(), _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, _MMSECTION_FLAGS::SetMappedFileIoComplete, _MMPTE::Soft, _MMSUBSECTION_FLAGS2::SubsectionAccessed, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MSUBSECTION::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_PFN_AND_THEN_WAIT, _MMPTE_HARDWARE::Valid, _MMSECTION_FLAGS::WasPurged, _MMPFNENTRY::WriteInProgress, and WrPageOut.
Referenced by CcPurgeCacheSection(), MiLoadImageSection(), and MmCheckSystemImage().
VOID MmPurgeWorkingSet (IN PEPROCESS Process, IN PVOID BaseAddress, IN SIZE_T RegionSize)
SIZE_T MmQuerySpecialPoolBlockSize (IN PVOID P)
Referenced by ExQueryPoolBlockSize().
VOID MmQuerySystemCacheWorkingSetInformation (OUT PSYSTEM_FILECACHE_INFORMATION Info)
Definition at line 2127 of file wslist.c.
References APC_LEVEL, ASSERT, _MMSUPPORT::Flags, KeGetCurrentIrql(), LOCK_SYSTEM_WS, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, MmStandbyRePurposed, MmSystemCacheWs, MmTransitionSharedPages, MmTransitionSharedPagesPeak, PAGE_SHIFT, _MMSUPPORT::PageFaultCount, _MMSUPPORT::PeakWorkingSetSize, PsGetCurrentThread(), UNLOCK_SYSTEM_WS, and _MMSUPPORT::WorkingSetSize.
Referenced by NtQuerySystemInformation().
NTKERNELAPI MM_SYSTEMSIZE MmQuerySystemSize (VOID)
Definition at line 4804 of file mminit.c.
References MmSystemSize.
Referenced by CcInitializeCacheManager(), ExpInitializeExecutive(), ExpWorkerInitialization(), IoInitSystem(), KeBalanceSetManager(), ObInitSystem(), and PspInitPhase0().
NTSTATUS MmQueryWorkingSetInformation (IN PSIZE_T PeakWorkingSetSize, IN PSIZE_T WorkingSetSize, IN PSIZE_T MinimumWorkingSetSize, IN PSIZE_T MaximumWorkingSetSize, IN PULONG HardEnforcementFlags)
Definition at line 2053 of file wslist.c.
References APC_LEVEL, ASSERT, _MMSUPPORT::Flags, KeGetCurrentIrql(), LOCK_WS_SHARED, _MMSUPPORT_FLAGS::MaximumWorkingSetHard, _MMSUPPORT::MaximumWorkingSetSize, _MMSUPPORT_FLAGS::MinimumWorkingSetHard, _MMSUPPORT::MinimumWorkingSetSize, PAGE_SHIFT, _MMSUPPORT::PeakWorkingSetSize, PsGetCurrentProcessByThread, PsGetCurrentThread(), STATUS_SUCCESS, UNLOCK_WS_SHARED, _EPROCESS::Vm, and _MMSUPPORT::WorkingSetSize.
Referenced by NtQueryInformationProcess(), and PspQueryQuotaLimits().
NTSTATUS MmQuitNextSession (IN PVOID OpaqueSession)
Definition at line 3790 of file session.c.
References APC_LEVEL, ASSERT, _MMSUPPORT::Flags, KeGetCurrentIrql(), NULL, ObDereferenceObject(), _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, STATUS_SUCCESS, and _EPROCESS::Vm.
Referenced by ExGetSessionPoolTagInformation(), ExpWin32SessionCallout(), MmGetSessionMappedViewInformation(), and PspWin32SessionCallout().
BOOLEAN MmRaisePoolQuota (IN POOL_TYPE PoolType, IN SIZE_T OldQuotaLimit, OUT PSIZE_T NewQuotaLimit)
Definition at line 1311 of file mmquota.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, FALSE, MmAllocatedNonPagedPool, MmAvailablePages, MmMaximumNonPagedPoolInPages, MMNONPAGED_QUOTA_INCREASE, MMPAGED_QUOTA_CHECK, MMPAGED_QUOTA_INCREASE, MmPagedPoolInfo, MmSizeOfPagedPoolInPages, MmTotalNonPagedPoolQuota, MmTotalPagedPoolQuota, PAGE_SHIFT, PagedPool, and TRUE.
Referenced by PspExpandQuota().
VOID MmReleaseDumpAddresses (IN PFN_NUMBER Pages)
Definition at line 14177 of file iosup.c.
References KiFlushSingleTb(), MiGetVirtualAddressMappedByPte, MiZeroMemoryPte, MmCrashDumpPte, and PAGE_SIZE.
NTKERNELAPI NTSTATUS MmRemovePhysicalMemory (__in PPHYSICAL_ADDRESS StartAddress, __inout PLARGE_INTEGER NumberOfBytes)
NTKERNELAPI NTSTATUS MmRemovePhysicalMemoryEx (IN PPHYSICAL_ADDRESS StartAddress, IN OUT PLARGE_INTEGER NumberOfBytes, IN ULONG Flags)
NTSTATUS MmRemoveVerifierEntry (IN PUNICODE_STRING ImageFileName)
Referenced by NtSetSystemInformation().
NTKERNELAPI VOID MmResetDriverPaging (__in PVOID AddressWithinSection)
Definition at line 3170 of file sysload.c.
References ASSERT, _IMAGE_SECTION_HEADER::Characteristics, DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, FALSE, _IMAGE_NT_HEADERS::FileHeader, _KLDR_DATA_TABLE_ENTRY::FullDllName, IMAGE_SCN_MEM_DISCARDABLE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MiGetPteAddress, MiLockCode(), MiLookupDataTableEntry(), _IMAGE_SECTION_HEADER::Misc, MM_LOCK_BY_NONPAGE, MM_SYSTEM_CODE_LOCKED_DOWN, MmDisablePagingExecutive, _IMAGE_SECTION_HEADER::Name, NOTHING, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGED_CODE, RtlImageNtHeader(), _KLDR_DATA_TABLE_ENTRY::SectionPointer, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
LOGICAL MmResourcesAvailable (IN POOL_TYPE PoolType, IN SIZE_T NumberOfBytes, IN EX_POOL_PRIORITY Priority)
Definition at line 666 of file allocpag.c.
References _MM_PAGED_POOL_INFO::AllocatedPagedPool, ASSERT, BASE_POOL_TYPE_MASK, BYTES_TO_PAGES, FALSE, _KEVENT::Header, HighPoolPriority, Index, KeAcquireGuardedMutex(), KeAcquireQueuedSpinLock(), KeIsExecutingDpc(), KePulseEvent(), KeReleaseGuardedMutex(), KeReleaseQueuedSpinLock(), KeSetEvent(), LockQueueMmNonPagedPoolLock, _ETHREAD::MemoryMaker, MI_UNUSED_SEGMENTS_SURPLUS, MiIssuePageExtendRequestNoWait(), MiLowNonPagedPoolEvent, MiLowPagedPoolEvent, MiTrimSegmentCache(), MmAllocatedNonPagedPool, MmLowPriority, MmMaximumNonPagedPoolInPages, MmNonPagedPool, MmNormalPriority, MmNumberOfPhysicalPages, MmPagedPool, MmPagedPoolInfo, MmPoolFailureReasons, MmPoolFailures, MmPreemptForNonPagedPriority, MmPreemptForPagedPriority, MmPreemptiveTrims, MmPriorityTooLow, MmSessionPagedPool, MmSessionPoolSize, MmSessionSpace, MmSizeOfPagedPoolInPages, MmTotalCommitLimitMaximum, MmTotalCommittedPages, MmUnusedSegmentCleanup, MUST_SUCCEED_POOL_TYPE_MASK, NonPagedPool, NormalPoolPriority, PAGE_SHIFT, PagedPool, _MM_SESSION_SPACE::PagedPoolInfo, PsGetCurrentThread(), SESSION_POOL_MASK, _MM_SESSION_SPACE::SessionPoolAllocationFailures, _DISPATCHER_HEADER::SignalState, Status, and TRUE.
NTKERNELAPI VOID MmReturnMemoryForHibernate (IN PMDL Mdl)
Definition at line 14751 of file iosup.c.
References LOCK_PFN2, MI_PFN_ELEMENT, MiDecrementReferenceCount(), PAGE_SHIFT, and UNLOCK_PFN2.
VOID MmReturnPoolQuota (IN POOL_TYPE PoolType, IN SIZE_T ReturnedQuota)
Definition at line 1404 of file mmquota.c.
References MmTotalNonPagedPoolQuota, MmTotalPagedPoolQuota, and PagedPool.
Referenced by PspDereferenceQuotaBlock(), PspGivebackQuota(), and PspReleaseReturnedQuota().
NTKERNELAPI HANDLE MmSecureVirtualMemory (__in_bcount(Size) PVOID Address, __in SIZE_T Size, __in ULONG ProbeMode)
Definition at line 5928 of file mapview.c.
References FALSE, and MiSecureVirtualMemory().
Referenced by CmpSetValueKeyExisting().
NTSTATUS MmSessionCreate (OUT PULONG SessionId)
Definition at line 1441 of file session.c.
References ASSERT, ExInitializePagedLookasideList(), FALSE, _MMSUPPORT::Flags, _EPROCESS::Flags, _MM_SESSION_SPACE::Flags, _MM_SESSION_SPACE_FLAGS::Initialized, InterlockedCompareExchange(), KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), _MMPTE::Long, _MM_SESSION_SPACE::Lookaside, MiDereferenceSession(), MiGetPdeAddress, MiGetPxeAddress, MiInitializeSpecialPool(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiSessionLeader(), MiSessionLeaderExists, MiSessionSpaceEnd, MmIsAddressValid(), MmSessionBase, MmSessionSpace, NT_SUCCESS, NULL, PagedPoolSession, PS_PROCESS_FLAGS_IN_SESSION, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), SESSION_GLOBAL, SESSION_POOL_SMALL_LISTS, _MMSUPPORT_FLAGS::SessionLeader, Status, STATUS_ALREADY_COMMITTED, STATUS_INVALID_SYSTEM_SERVICE, _ETHREAD::Tcb, _MMPTE::u, _MM_SESSION_SPACE::u, and _EPROCESS::Vm.
Referenced by NtSetSystemInformation().
NTSTATUS MmSessionDelete (IN ULONG SessionId)
Referenced by NtSetSystemInformation().
VOID MmSessionSetUnloadAddress (IN PDRIVER_OBJECT pWin32KDevice)
Definition at line 166 of file session.c.
References ASSERT, MmIsAddressValid(), MmSessionSpace, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), TRUE, and _MM_SESSION_SPACE::Win32KDriverUnload.
Referenced by NtSetSystemInformation().
NTKERNELAPI BOOLEAN MmSetAddressRangeModified (__in_bcount(Length) PVOID Address, __in SIZE_T Length)
Definition at line 12508 of file iosup.c.
References Count, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_PFN2, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_IS_PTE_DIRTY, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PTE_CLEAN, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiReleasePageFileSpace(), MM_MAXIMUM_FLUSH_COUNT, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, and _MMPFNENTRY::WriteInProgress.
Referenced by CcFlushCache(), CcMapAndCopy(), CcPurgeAndClearCacheSection(), CcUnpinRepinnedBcb(), and CcZeroData().
NTKERNELAPI NTSTATUS MmSetBankedSection (__in HANDLE ProcessHandle, __in_bcount(BankLength) PVOID VirtualAddress, __in ULONG BankLength, __in BOOLEAN ReadWriteBank, __in PBANKED_SECTION_ROUTINE BankRoutine, __in PVOID Context)
Definition at line 14218 of file iosup.c.
References ASSERT, _MMBANKED_SECTION::BankedRoutine, _MMBANKED_SECTION::BankShift, _MMBANKED_SECTION::BankSize, _MMBANKED_SECTION::BankTemplate, _MMBANKED_SECTION::BasedPte, _MMBANKED_SECTION::BasePhysicalPage, _MMBANKED_SECTION::Context, _MMBANKED_SECTION::CurrentMappedPte, _MMVAD::EndingVpn, ExAllocatePoolWithTag, FALSE, _EPROCESS::Flags, _MMPTE::Hard, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_FLUSH_PROCESS_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_USER_PTE, MI_SET_PTE_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MiGetPteAddress, MiLocateAddress(), MiZeroMemoryPte, MM_READWRITE, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, PROCESS_VM_OPERATION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsProcessType, PTE_SHIFT, _MMVAD::StartingVpn, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_VIEW_SIZE, STATUS_NOT_MAPPED_DATA, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MMPTE::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, UNREFERENCED_PARAMETER, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
NTSTATUS MmSetExecuteOptions (IN ULONG ExecuteOptions)
Definition at line 2244 of file mmfault.c.
References ASSERT, _KEXECUTE_OPTIONS::DisableThunkEmulation, _KEXECUTE_OPTIONS::ExecuteDisable, _KEXECUTE_OPTIONS::ExecuteDispatchEnable, _KEXECUTE_OPTIONS::ExecuteEnable, _KPROCESS::Flags, _KEXECUTE_OPTIONS::ImageDispatchEnable, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetCurrentIrql(), KeReleaseInStackQueuedSpinLock(), MEM_EXECUTE_OPTION_DISABLE, MEM_EXECUTE_OPTION_DISABLE_THUNK_EMULATION, MEM_EXECUTE_OPTION_ENABLE, MEM_EXECUTE_OPTION_EXECUTE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_IMAGE_DISPATCH_ENABLE, MEM_EXECUTE_OPTION_PERMANENT, MEM_EXECUTE_OPTION_VALID_FLAGS, NULL, PASSIVE_LEVEL, _EPROCESS::Pcb, _KEXECUTE_OPTIONS::Permanent, _KPROCESS::ProcessLock, PsGetCurrentProcess(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtSetInformationProcess().
VOID MmSetMemoryPriorityProcess (IN PEPROCESS Process, IN UCHAR MemoryPriority)
Definition at line 7122 of file procsup.c.
References MEMORY_PRIORITY_BACKGROUND, MiSetMemoryPriorityProcess(), MmNumberOfPhysicalPages, MmSmallSystem, MmSystemSize, and PAGE_SIZE.
Referenced by NtSetInformationProcess(), and PspComputeQuantumAndPriority().
NTKERNELAPI VOID FASTCALL MmSetPageFaultNotifyRoutine (IN PPAGE_FAULT_NOTIFY_ROUTINE NotifyRoutine)
Referenced by WmipDisableKernelTrace(), and WmipEnableKernelTrace().
NTKERNELAPI BOOLEAN MmSetPageProtection (__in_bcount(NumberOfBytes) PVOID VirtualAddress, __in SIZE_T NumberOfBytes, __in ULONG NewProtect)
Definition at line 9692 of file iosup.c.
References APC_LEVEL, ASSERT, BYTES_TO_PAGES, _MMPTE_HARDWARE::Dirty, FALSE, _MMPTE::Hard, KeGetCurrentIrql(), LOCK_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_KERNEL_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiMakeProtectionMask(), MM_INVALID_PROTECTION, MM_MAXIMUM_FLUSH_COUNT, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, TRUE, _MMPTE::u, and UNLOCK_PFN.
Referenced by KiI386PentiumLockErrataFixup().
PFN_NUMBER MmSetPhysicalPagesLimit (IN PFN_NUMBER NewPhysicalPagesLimit)
Definition at line 3856 of file physical.c.
References _EPROCESS::AweInfo, LOCK_ADDRESS_SPACE, NULL, PAGED_CODE, PsGetCurrentProcessByThread, PsGetCurrentThread(), UNLOCK_ADDRESS_SPACE, and _AWEINFO::VadPhysicalPagesLimit.
VOID MmSetSessionLocaleId (IN LCID LocaleId)
Definition at line 424 of file session.c.
References _MMSUPPORT::Flags, _MM_SESSION_SPACE::LocaleId, NULL, PAGED_CODE, PsDefaultThreadLocaleId, PsGetCurrentProcess(), _EPROCESS::Session, _MMSUPPORT_FLAGS::SessionLeader, and _EPROCESS::Vm.
Referenced by NtSetDefaultLocale().
NTSTATUS MmSetVerifierInformation (IN OUT PVOID SystemInformation, IN ULONG SystemInformationLength)
Referenced by NtSetSystemInformation().
BOOLEAN MmShutdownSystem (IN ULONG)
Definition at line 791 of file shutdown.c.
References ASSERT, MiReleaseAllMemory(), MiShutdownSystem(), MmModifiedPageListHead, MmNumberOfPagingFiles, MmPagingFile, MmSystemShutdown, MmTotalPagesForPagingFile, MmTrimAllSystemPageableMemory(), ObDereferenceObject(), PO_CLEAN_SHUTDOWN_PAGING, PoCleanShutdownEnabled(), _MMPFNLIST::Total, and TRUE.
Referenced by MmInitSystem().
NTKERNELAPI SIZE_T MmSizeOfMdl (__in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
Definition at line 12407 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES.
Referenced by ExLockUserBuffer(), MmCreateMdl(), and NtStartProfile().
ULONG MmSizeOfTriageInformation (VOID)
ULONG MmSizeOfUnloadedDriverInformation (VOID)
NTKERNELAPI LOGICAL MmTrimAllSystemPageableMemory (__in LOGICAL PurgeTransition)
Definition at line 2317 of file wsmanage.c.
References MI_SYSTEM_GLOBAL, and MiTrimAllSystemPageableMemory().
Referenced by MmShutdownSystem().
NTSTATUS MmUnloadSystemImage (IN PVOID Section)
Definition at line 3524 of file sysload.c.
References ASSERT, _SEGMENT::BasedAddress, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, _MM_SESSION_SPACE::CommittedPages, DbgUnLoadImageSymbols(), _KLDR_DATA_TABLE_ENTRY::DllBase, DRIVER_VERIFIER_DEADLOCK_DETECTION, ExFreePool(), FALSE, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _SEGMENT::ImageCommitment, _IMAGE_ENTRY_IN_SESSION::ImageCountInThisSession, _KLDR_DATA_TABLE_ENTRY::InLoadOrderLinks, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseMutant(), KernelMode, KeWaitForSingleObject(), LDRP_DEBUG_SYMBOLS_LOADED, LDRP_IMAGE_VERIFYING, LDRP_SYSTEM_MAPPED, _MM_DRIVER_VERIFIER_DATA::Level, _KLDR_DATA_TABLE_ENTRY::LoadCount, LOADED_AT_BOOT, _KLDR_DATA_TABLE_ENTRY::LoadedImports, MI_DELETE_FLUSH_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_SESSION_IMAGE_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_ROUND_TO_SIZE, MiActiveVerifierThunks, MiClearImports(), MiDeleteSystemPageableVm(), MiDereferenceImports(), MiFreeContiguousPages(), MiGetPdeAddress, MiGetPteAddress, MiGetPteOffset, MiProcessLoaderEntry(), MiReleaseSystemPtes(), MiRememberUnloadedDriver(), MiRemoveCachedRange(), MiRemoveImageSessionWide(), MiReturnCommitment, MiRundownHotpatchList(), MiSessionLookupImage(), MiUnmapLargePages(), MiVerifierCheckThunks(), MiVerifyingDriverUnloading(), MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_RETURN_DRIVER_UNLOAD, MM_DBG_COMMIT_RETURN_DRIVER_UNLOAD1, MM_DBG_SESSION_COMMIT_IMAGE_UNLOAD, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE1, MM_TRACK_COMMIT, MmDriverCommit, MmSessionSpace, MmSnapUnloads, MmTotalSystemDriverPages, MmVerifierData, NT_SUCCESS, NULL, NumberOfBytes, ObDereferenceObject(), PAGE_SHIFT, _KLDR_DATA_TABLE_ENTRY::PatchInformation, RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), _KLDR_DATA_TABLE_ENTRY::SectionPointer, _SECTION::Segment, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, Status, STATUS_SUCCESS, SystemPteSpace, _SEGMENT::TotalNumberOfPtes, TRUE, _SEGMENT::u1, VerifierDeadlockFreePool(), and WrVirtualMemory.
Referenced by IopDeleteDriver(), IopLoadDriver(), MiCallDllUnloadAndUnloadDll(), MiResolveImageReferences(), MiSessionUnloadAllImages(), MmLoadSystemImage(), and NtSetSystemInformation().
VOID MmUnlockCachedPage (IN PVOID AddressInCache)
Definition at line 2681 of file mapcache.c.
References ASSERT, _MMPFN::e2, _MMPTE::Hard, KeBugCheckEx(), LOCK_PFN, MEMORY_MANAGEMENT, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by CcFreeActiveVacb().
NTKERNELAPI VOID MmUnlockPageableImageSection (__in PVOID ImageSectionHandle)
Definition at line 13908 of file iosup.c.
References ASSERT, Count, _MMPFN::e2, FALSE, _MMPTE::Hard, InterlockedDecrement, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KePulseEvent(), LOCK_PFN2, MEMORY_MANAGEMENT, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, _IMAGE_SECTION_HEADER::Misc, MmCollidedLockWait, SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_SECTION_HEADER::SizeOfRawData, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by ExpGetLockInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), IoUnregisterShutdownNotification(), KeSetPhysicalCacheTypeRange(), KiAmdK6MtrrSetMemoryType(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiResetVirtualMemory(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiShutdownSystem(), MiUnmapLockedPagesInUserSpace(), MmAdjustWorkingSetSizeEx(), MmFreePagesFromMdl(), MmInitSystem(), MmMapUserAddressesToPage(), MmUnlockPagableImageSection(), MmUnlockPagedPool(), PspQueryWorkingSetWatch(), WmipFreeLoggerContext(), and WmipStartGlobalLogger().
NTKERNELAPI VOID MmUnlockPagedPool (IN PVOID Address, IN SIZE_T Size)
Definition at line 14552 of file iosup.c.
References ASSERT, _MMPFN::e2, ExPageLockHandle, _MMPTE::Hard, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiMakeEntireImageCopyOnWrite().
NTKERNELAPI VOID MmUnlockPages (__inout PMDL MemoryDescriptorList)
Definition at line 3287 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, CONTAINING_RECORD, _MMPFN::e1, _MMPFN::e2, FALSE, _MI_PFN_DEREFERENCE_CHUNK::Flags, GET_PAGING_FILE_OFFSET, _MMPTE::Hard, InterlockedCompareExchange(), InterlockedCompareExchangePointer, InterlockedExchangeAddSizeT, InterlockedPopEntrySList(), KeGetCurrentIrql(), KeGetCurrentNode, LOCK_PFN2, LOCK_WS_SHARED, LOCK_WS_SHARED_CROSS_PROCESS, MDL_DESCRIBES_AWE, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_DEFER_DRAIN_LOCAL_ONLY, MI_DEFER_PFN_HELD, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_MAX_DEREFERENCE_CHUNK, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiDecrementReferenceCountForAwePage(), MiDeferredUnlockPages(), MiDereferenceIoSpace(), MiFreeMdlTracker(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiReleaseConfirmedPageFileSpace(), MM_EMPTY_LIST, MmHighestPhysicalPage, MmPfnDeferredList, MmPfnDereferenceSListHead, MmTrackLockedPages, MmUnmapLockedPages(), NOTHING, NULL, _EPROCESS::NumberOfLockedPages, _MI_PFN_DEREFERENCE_CHUNK::NumberOfPages, _MMPFN::OriginalPte, PAGE_SHIFT, _MMPTE_SOFTWARE::PageFileHigh, PASSIVE_LEVEL, _MI_PFN_DEREFERENCE_CHUNK::Pfns, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcessByThread, PsGetCurrentThread(), PSLIST_ENTRY, ReadForWriteAccess, RtlCopyMemory, _MMPFN::ShareCount, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, UNLOCK_WS_SHARED, UNLOCK_WS_SHARED_CROSS_PROCESS, _MMPTE_HARDWARE::Valid, and _MMPFNENTRY::WriteInProgress.
Referenced by CcMdlRead(), CcMdlReadComplete2(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPrepareMdlWrite(), CcZeroData(), ExpProfileDelete(), ExUnlockUserBuffer(), IopfCompleteRequest(), KiOpPatchCode(), MiDoMappedCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtStartProfile(), and NtStopProfile().
NTKERNELAPI VOID MmUnmapIoSpace (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
Definition at line 8954 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_PDE_MAPS_LARGE_PAGE, MiGetPdeAddress, MiGetPteAddress, MiGetPteOffset, MiReleaseSystemPtes(), MiRemoveIoSpaceMap(), MiRemovePteTracker(), MiUnmapLargePages(), MiZeroMemoryPte, MM_MAXIMUM_FLUSH_COUNT, MmTrackPtes, NULL, PAGE_SIZE, SystemPteSpace, and TRUE.
Referenced by MmFreeContiguousMemory(), MmUnmapVideoDisplay(), and WmipFirmwareTableHandler().
NTKERNELAPI VOID MmUnmapLockedPages (__in PVOID BaseAddress, __in PMDL MemoryDescriptorList)
Definition at line 1634 of file sysptes.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _PTE_QUEUE_POINTER::Data, _MMPFN::e2, ExInsertTailNBQueue(), _MMPTE::Hard, Index, InterlockedExchangeAddSizeT, InterlockedIncrement, KeReadTbFlushTimeStamp(), MDL_FREE_EXTRA_PTES, MDL_MAPPED_TO_SYSTEM_VA, MDL_PARENT_MAPPED_SYSTEM_VA, MDL_PARTIAL_HAS_BEEN_MAPPED, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiCheckPteRelease(), MiGetPteAddress, MiReleaseSystemPtes(), MiRemovePteTracker(), MiSystemPteNBHead, MiUnmapLockedPagesInUserSpace(), MiZeroMemoryPte, MM_HIGHEST_USER_ADDRESS, MM_MAX_SYSPTE_FREE, MM_MIN_SYSPTE_FREE, MM_PTE_TABLE_LIMIT, MmSysPteIndex, MmSysPteListBySizeCount, MmSysPteMinimumFree, MmSysPteTables, MmTotalFreeSystemPtes, MmTrackPtes, PackPTEValue(), PAGE_SHIFT, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
Referenced by CcZeroData(), ExpProfileDelete(), MiCleanSection(), MiCloneProcessAddressSpace(), MiCreateImageFileMap(), MiDoMappedCopy(), MiFlushComplete(), MiFlushSectionInternal(), MiMakeOutswappedPageResident(), MiShutdownSystem(), MiWaitForInPageComplete(), MiWriteComplete(), MiZeroPageFile(), MiZeroPageFileFirstPage(), MmUnlockPages(), and NtStopProfile().
NTKERNELAPI VOID MmUnmapReservedMapping (IN PVOID BaseAddress, IN ULONG PoolTag, IN PMDL MemoryDescriptorList)
Definition at line 5907 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, DISPATCH_LEVEL, _MMPFN::e2, _MMPTE::Hard, InterlockedExchangeAddSizeT, KeBugCheckEx(), KeGetCurrentIrql(), _MMPTE::Long, MDL_FREE_EXTRA_PTES, MDL_MAPPED_TO_SYSTEM_VA, MDL_PARENT_MAPPED_SYSTEM_VA, MDL_PARTIAL_HAS_BEEN_MAPPED, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, MiZeroMemoryPte, MM_HIGHEST_USER_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, PAGE_SIZE, SYSTEM_PTE_MISUSE, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
NTKERNELAPI VOID MmUnmapVideoDisplay (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
Definition at line 14474 of file iosup.c.
References MmUnmapIoSpace().
NTKERNELAPI NTSTATUS MmUnmapViewInSessionSpace (__in PVOID MappedBase)
Definition at line 5429 of file mapview.c.
References ASSERT, _NTSYM::Flags, MiUnmapViewInSystemSpace(), MmIsAddressValid(), MmSessionSpace, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _MM_SESSION_SPACE::Session, STATUS_NOT_MAPPED_VIEW, and TRUE.
Referenced by MiSessionWideReserveImageAddress().
VOID MmUnmapViewInSystemCache (IN PVOID BaseAddress, IN PVOID SectionToUnmap, IN ULONG AddToFront)
Definition at line 455 of file mapcache.c.
References APC_LEVEL, ASSERT, _SEGMENT::ControlArea, _MSUBSECTION::ControlArea, _MMPFN::e1, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _MMSECTION_FLAGS::Image, KeBugCheckEx(), KeGetCurrentIrql(), KeReadTbFlushTimeStamp(), _MMPTE::List, LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_WRITE_ZERO_PTE, MiCheckControlArea(), MiDecrementShareCountInline, MiGetPteAddress, MiGetSubsectionAddress, MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiPteToProto, MiRemoveViewsFromSection(), MiTerminateWsle(), MM_EMPTY_PTE_LIST, MM_FLUSH_COUNTER_MASK, MmFrontOfList, MmSystemCachePteBase, MmSystemCacheWs, _MMPTE_LIST::NextEntry, _MSUBSECTION::NextSubsection, NULL, _CONTROL_AREA::NumberOfMappedViews, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfSystemCacheViews, _MMPFN::OriginalPte, PAGE_SIZE, _MMSECTION_FLAGS::PhysicalMemory, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MSUBSECTION::PtesInSubsection, RtlCompareMemoryUlong(), _CONTROL_AREA::Segment, _MMPFN::ShareCount, _MMPTE::Soft, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, UNLOCK_SYSTEM_WS, _MMPTE_HARDWARE::Valid, _MMPFN::WsIndex, and X256K.
Referenced by CcUnmapVacb(), and Phase1InitializationDiscard().
NTKERNELAPI NTSTATUS MmUnmapViewInSystemSpace (__in PVOID MappedBase)
Definition at line 5398 of file mapview.c.
References MiUnmapViewInSystemSpace(), and PAGED_CODE.
Referenced by MiSessionWideReserveImageAddress().
NTKERNELAPI NTSTATUS MmUnmapViewOfSection (__in PEPROCESS Process, __in PVOID BaseAddress)
Definition at line 295 of file umapview.c.
References MiUnmapViewOfSection().
Referenced by LpcpDeletePort(), and PsShutdownSystem().
NTKERNELAPI VOID MmUnsecureVirtualMemory (__in HANDLE SecureHandle)
Definition at line 6596 of file mapview.c.
References FALSE, and MiUnsecureVirtualMemory().
Referenced by CmpSetValueKeyExisting().
LOGICAL MmUpdateMdlTracker (IN PMDL MemoryDescriptorList, IN PVOID CallingAddress, IN PVOID CallersCaller)
Definition at line 1631 of file iosup.c.
References ASSERT, _LIST_ENTRY::Blink, _LOCK_TRACKER::CallersCaller, _LOCK_TRACKER::CallingAddress, CONTAINING_RECORD, FALSE, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, _EPROCESS::LockedPagesList, _LOCK_TRACKER::Mdl, MmTrackLockedPages, NULL, _LOCK_TRACKER::Page, PsInitialSystemProcess, and TRUE.
Referenced by IopProbeAndLockPages().
LOGICAL MmUseSpecialPool (IN SIZE_T NumberOfBytes, IN ULONG Tag)
Referenced by __bcount().
BOOLEAN MmVerifyImageIsOkForMpUse (IN PVOID BaseAddress)
Definition at line 5686 of file sysload.c.
References _IMAGE_FILE_HEADER::Characteristics, FALSE, _IMAGE_NT_HEADERS::FileHeader, IMAGE_FILE_UP_SYSTEM_ONLY, KeNumberProcessors, NULL, PAGED_CODE, RtlImageNtHeader(), and TRUE.
Referenced by ExpInitializeExecutive(), and MmCheckSystemImage().
VOID MmWorkingSetManager (VOID)
Definition at line 595 of file wsmanage.c.
References ASSERT, FALSE, Initialized, KeSetEvent(), _ETHREAD::MemoryMaker, MI_EMPTY_ALL_WORKING_SETS, MI_TRIM_ALL_WORKING_SETS, MiComputeSystemTrimCriteria(), MiDeferredUnlockPages(), MiProcessWorkingSets(), MmIsAddressValid(), MmModifiedPageListHead, MmModifiedPageMaximum, MmModifiedPageWriterEvent, MmSessionSpace, PsGetCurrentThread(), and _MMPFNLIST::Total.
Referenced by KeBalanceSetManager().
VOID MmWriteTriageInformation (IN PVOID)
VOID MmWriteUnloadedDriverInformation (IN PVOID)
VOID MmZeroPageThread (VOID)
Definition at line 44 of file zeropage.c.
References ASSERT, BadPageList, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, KeBugCheckEx(), KeDelayExecutionThread(), KeFindFirstSetLeftAffinity, KeGetCurrentThread(), KeNodeBlock, KeNumberNodes, KernelMode, KeSetIdealProcessorThread(), KeSetPriorityZeroPageThread(), KeWaitForMultipleObjects(), LOCK_PFN, MACHINE_ZERO_PAGE, MI_DECREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MiChargeCommitment(), MiFindInitializationCode(), MiFreeInitializationCode(), MiInsertPageInList(), MiMapPagesToZeroInHyperSpace(), MiRemoveAnyPage(), MiUnmapPagesInZeroSpace(), MiZeroingDisabled, MM_EMPTY_LIST, MM_RESAVAIL_ALLOCATE_ZERO_PAGE_CLUSTERS, MM_ZERO_PAGE_OBJECT, MmFreePageListHead, MmFreePagesByColor, MmHalfSecond, MmSecondaryColorMask, MmZeroedPageListHead, MmZeroingPageEvent, MmZeroingPageThreadActive, NO_BITS_FOUND, NULL, NUMBER_OF_ZEROING_PTES, NUMBER_WAIT_OBJECTS, PAGE_SHIFT, _MMPFNENTRY::PageLocation, PFN_LIST_CORRUPT, PO_SYS_IDLE_OBJECT, PoSystemIdleTimer, PoSystemIdleWorker(), _MMPFN::PteAddress, Status, _MMPFNLIST::Total, TRUE, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, WaitAny, and WrFreePage.
Referenced by Phase1Initialization().
VOID VerifierFreeTrackedPool (IN PVOID VirtualAddress, IN SIZE_T ChargedBytes, IN LOGICAL CheckType, IN LOGICAL SpecialPool)
Referenced by ExFreePoolWithTag(), and MiFreePoolPages().
typedef VOID (FASTCALL * PPAGE_FAULT_NOTIFY_ROUTINE)
Variable Documentation
NTKERNELAPI __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS BoundaryAddressMultiple
Definition at line 2006 of file mm.h.
NTKERNELAPI __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS __in MEMORY_CACHING_TYPE CacheType
Definition at line 1944 of file mm.h.
Referenced by MiFindLargePageMemory(), MiFlushTbAndCapture(), and MiMapViewOfPhysicalSection().
NTKERNELAPI __in PHYSICAL_ADDRESS __in PHYSICAL_ADDRESS HighestAcceptableAddress
Definition at line 2000 of file mm.h.
NTKERNELAPI __in PHYSICAL_ADDRESS LowestAcceptableAddress
Definition at line 2006 of file mm.h.
BOOLEAN Mm64BitPhysicalAddress
Definition at line 580 of file miglobal.c.
PFN_NUMBER MmAvailablePages
Definition at line 60 of file miglobal.c.
PFN_NUMBER MmHighestPhysicalPage
Referenced by ExpGetSystemBasicInformation(), MiAllocatePagesForMdl(), MiFreePoolPages(), MiInitializeSessionIds(), MiInitMachineDependent(), MiInsertFrontModifiedNoWrite(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiIsAddressValid(), MiRemovePageFromList(), MiSessionWideInitializeAddresses(), MiUnlinkPageFromList(), MmAdvanceMdl(), MmFreePagesFromMdl(), MmGetSizeOfBigPoolAllocation(), MmInitSystem(), MmProbeAndLockPages(), MmUnlockPages(), and NtMapViewOfSection().
PFN_NUMBER MmLowestPhysicalPage
Definition at line 47 of file miglobal.c.
Referenced by ExpGetSystemBasicInformation(), MiInitializeSessionIds(), MiInitMachineDependent(), MiInsertFrontModifiedNoWrite(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiInsertZeroListAtBack(), MiRemovePageFromList(), MiSessionWideInitializeAddresses(), and MmInitSystem().
MMPFNLIST MmModifiedPageListHead
Definition at line 133 of file miglobal.c.
Referenced by MiDecrementReferenceCount(), MiFlushAllPages(), MiGatherMappedPages(), MiInsertPageInList(), MiModifiedPageWriterWorker(), MiNoPagesLastChance(), MiObtainFreePages(), MiShutdownSystem(), MiSnapPagefileWrite(), MiUnlinkPageFromList(), MiWriteComplete(), MmAccessFault(), MmEnableModifiedWriteOfSection(), MmShutdownSystem(), and MmWorkingSetManager().
ULONG MmNumberOfColors
PFN_COUNT MmNumberOfPhysicalPages
Definition at line 41 of file miglobal.c.
Referenced by CcInitializeCacheManager(), ExpGetSystemBasicInformation(), InitializePool(), MiAdjustWorkingSetManagerParameters(), MiAllocatePagesForMdl(), MiBuildPagedPool(), MiInitializeCommitment(), MiInitializeMemoryEvents(), MiInitializeNonPagedPool(), MiInitializeSessionIds(), MiInitMachineDependent(), MiModifiedPageWriter(), MiSessionWideInitializeAddresses(), MmInitSystem(), MmResourcesAvailable(), MmSetMemoryPriorityProcess(), and MxGetNextPage().
ULONG MmPaeErrMask
Referenced by KiInitializeKernel().
ULONGLONG MmPaeMask
Referenced by KiInitializeKernel(), MiInitializePfn(), MiInitializePfnAndMakePteValid(), MiInitMachineDependent(), MmAccessFault(), and MmInSwapProcess().
SIZE_T MmPeakCommitment
Definition at line 24 of file mmquota.c.
Referenced by MiChargeCommitment(), MiChargeTemporaryCommitmentForReduction(), and NtQuerySystemInformation().
PPHYSICAL_MEMORY_DESCRIPTOR MmPhysicalMemoryBlock
Definition at line 45 of file mminit.c.
Referenced by MiFindContiguousPages(), MiFindLargePageMemory(), MiReleaseAllMemory(), MiReportPhysicalMemory(), MmIdentifyPhysicalMemory(), and MmPerfSnapShotValidPhysicalMemory().
ULONG MmProductType
Definition at line 224 of file mminit.c.
Referenced by MmInitSystem(), and MmIsThisAnNtAsSystem().
ULONG MmReadClusterSize
Definition at line 520 of file miglobal.c.
Referenced by MmInitSystem(), and PspCreateThread().
ULONG MmSecondaryColorMask
Referenced by KeStartAllProcessors(), KiAllProcessorsStarted(), MiAllocatePagesForMdl(), MiComputeInitialLargePage(), MiInitMachineDependent(), MiRemoveAnyPage(), MiRemoveZeroPage(), MiZeroPageWorker(), MmAllocateIndependentPages(), MmGetNodeColor(), and MmZeroPageThread().
POBJECT_TYPE MmSectionObjectType
Definition at line 366 of file miglobal.c.
Referenced by MiSectionInitialization(), MiSessionWideReserveImageAddress(), MmCheckSystemImage(), MmCreateSection(), MmLoadSystemImage(), NtAcceptConnectPort(), NtExtendSection(), NtMapViewOfSection(), NtOpenSection(), NtQuerySection(), NtSecureConnectPort(), ObpLookupObjectName(), Phase1InitializationDiscard(), PsLocateSystemDll(), and PspCreateProcess().
ULONG_PTR MmSizeOfSystemCacheInPages
Definition at line 326 of file miglobal.c.
Referenced by CcInitializeVacbs(), and MmInitSystem().
MMSUPPORT MmSystemCacheWs
Definition at line 318 of file miglobal.c.
PFN_NUMBER MmThrottleBottom
Definition at line 62 of file miglobal.c.
Referenced by MmInitSystem().
PFN_NUMBER MmThrottleTop
Definition at line 61 of file miglobal.c.
Referenced by MmInitSystem().
SIZE_T MmTotalCommitLimit
Definition at line 460 of file miglobal.c.
Referenced by MiAttemptPageFileReduction(), MiCauseOverCommitPopup(), MiChargeCommitment(), MiChargeCommitmentCantExpand(), MiChargeTemporaryCommitmentForReduction(), MiContractPagingFiles(), MiExtendPagingFiles(), MiInitializeLoadedModuleList(), MiInsertPageFileInList(), MiPageFileFull(), MmFreeBootRegistry(), MmFreeLoaderBlock(), MmInitSystem(), NtCreatePagingFile(), and NtQuerySystemInformation().
SIZE_T MmTotalCommittedPages
Definition at line 449 of file miglobal.c.
Referenced by MiAttemptPageFileReduction(), MiBuildPagedPool(), MiCauseOverCommitPopup(), MiChargeCommitment(), MiChargeCommitmentCantExpand(), MiChargeTemporaryCommitmentForReduction(), MiContractPagingFiles(), MiExtendPagingFiles(), MiInitializeLoadedModuleList(), MiPageFileFull(), MmAvailablePoolInPages(), MmResourcesAvailable(), NtCreatePagingFile(), and NtQuerySystemInformation().
ULONG MmTotalFreeSystemPtes[MaximumPtePoolTypes]
Definition at line 65 of file sysptes.c.
Referenced by MiFeedSysPtePool(), MiGetSystemPteAvailability(), MiInitializeSystemPtes(), MiIssueNoPtesBugcheck(), MiReleaseSystemPtes(), MiReserveAlignedSystemPtes(), MiUseLargeDriverPage(), MmGetNumberOfFreeSystemPtes(), MmMapLockedPagesSpecifyCache(), and MmUnmapLockedPages().
ULONG_PTR MmVirtualBias
Definition at line 27 of file miglobal.c.
Referenced by MiInitMachineDependent(), MiMapViewOfImageSection(), MmFreeLoaderBlock(), MmInitializeHandBuiltProcess2(), MmInitSystem(), and MxConvertToLargePage().
KEVENT MmWorkingSetManagerEvent
Definition at line 441 of file miglobal.c.
Referenced by KeBalanceSetManager(), MiObtainFreePages(), MiQueueWorkingSetRequest(), MmInitSystem(), and MmIsMemoryAvailable().
NTKERNELAPI __in SIZE_T NumberOfBytes
Definition at line 1944 of file mm.h.
NTKERNELAPI __in ULONG PoolTag
Definition at line 1820 of file mm.h.
Referenced by __bcount().