Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/worker.c File Reference
worker.c File Reference
#include "exp.h"
Data Structures
struct _EXP_WORKER_LINK
struct SHUTDOWN_WORK_ITEM
Macros
#define CRITICAL_WORK_QUEUE_PRIORITY (13 - NORMAL_BASE_PRIORITY)
#define DELAYED_WORK_QUEUE_PRIORITY (12 - NORMAL_BASE_PRIORITY)
#define DYNAMIC_THREAD_TIMEOUT ((LONGLONG)10 * 60 * 1000 * 1000 * 10)
#define DYNAMIC_WORKER_THREAD 0x80000000
#define HYPER_CRITICAL_WORK_QUEUE_PRIORITY (15 - NORMAL_BASE_PRIORITY)
#define LARGE_NUMBER_OF_THREADS 5
#define MAX_ADDITIONAL_DYNAMIC_THREADS 16
#define MAX_ADDITIONAL_THREADS 16
#define MEDIUM_NUMBER_OF_THREADS 3
#define SMALL_NUMBER_OF_THREADS 2
#define THREAD_SET_INTERVAL (1 * 1000 * 1000 * 10)
Typedefs
typedef enum _BALANCE_OBJECT BALANCE_OBJECT
typedef struct _EXP_WORKER_LINK EXP_WORKER_LINK
typedef struct _EXP_WORKER_LINK * PEXP_WORKER_LINK
typedef struct SHUTDOWN_WORK_ITEM * PSHUTDOWN_WORK_ITEM
Enumerations
enum _BALANCE_OBJECT {
TimerExpiration, ThreadSetManagerEvent, ShutdownEvent, MaximumBalanceObject,
TimerExpiration, WorkingSetManagerEvent, MaximumObject
}
Functions
C_ASSERT (MaximumBalanceObject<=THREAD_WAIT_OBJECTS)
VOID ExpCheckDynamicThreadCount (VOID)
VOID ExpCheckForWorker (IN PVOID p, IN SIZE_T Size)
LOGICAL ExpCheckQueueShutdown (IN WORK_QUEUE_TYPE QueueType, IN PSHUTDOWN_WORK_ITEM ShutdownItem)
NTSTATUS ExpCreateWorkerThread (WORK_QUEUE_TYPE QueueType, BOOLEAN Dynamic)
NTSTATUS ExpCreateWorkerThread (IN WORK_QUEUE_TYPE QueueType, IN BOOLEAN Dynamic)
VOID ExpDebuggerWorker (IN PVOID Context)
VOID ExpDetectWorkerThreadDeadlock (VOID)
LOGICAL __forceinline ExpNewThreadNecessary (IN PEX_WORK_QUEUE Queue)
VOID ExpSetSwappingKernelApc (IN PKAPC Apc, OUT PKNORMAL_ROUTINE *NormalRoutine, IN OUT PVOID NormalContext, IN OUT PVOID *SystemArgument1, IN OUT PVOID *SystemArgument2)
VOID ExpShutdownWorker (IN PVOID Parameter)
VOID ExpShutdownWorkerThreads (VOID)
NTSTATUS ExpWorkerInitialization (VOID)
VOID ExpWorkerThread (IN PVOID StartContext)
VOID ExpWorkerThreadBalanceManager (IN PVOID StartContext)
VOID ExQueueWorkItem (__inout PWORK_QUEUE_ITEM WorkItem, __in WORK_QUEUE_TYPE QueueType)
VOID ExSwapinWorkerThreads (IN BOOLEAN AllowSwap)
Variables
ULONG ExCriticalWorkerThreads
ULONG ExDelayedWorkerThreads
ULONG ExpAdditionalCriticalWorkerThreads
ULONG ExpAdditionalDelayedWorkerThreads
PVOID ExpDebuggerPageIn
PVOID ExpDebuggerProcessAttach
PVOID ExpDebuggerProcessKill
ULONG ExpDebuggerWork
WORK_QUEUE_ITEM ExpDebuggerWorkItem
PETHREAD ExpLastWorkerThread
KEVENT ExpThreadSetManagerEvent
KEVENT ExpThreadSetManagerShutdownEvent
const char ExpWorkerApcDisabledMessage []
LIST_ENTRY ExpWorkerListHead
BOOLEAN ExpWorkersCanSwap
FAST_MUTEX ExpWorkerSwapinMutex
PETHREAD ExpWorkerThreadBalanceManagerPtr
EX_WORK_QUEUE ExWorkerQueue [MaximumWorkQueue]
Macro Definition Documentation
#define CRITICAL_WORK_QUEUE_PRIORITY (13 - NORMAL_BASE_PRIORITY)
Definition at line 68 of file worker.c.
Referenced by ExpCreateWorkerThread(), and ExpWorkerThreadBalanceManager().
#define DELAYED_WORK_QUEUE_PRIORITY (12 - NORMAL_BASE_PRIORITY)
Definition at line 67 of file worker.c.
Referenced by ExpCreateWorkerThread().
#define DYNAMIC_THREAD_TIMEOUT ((LONGLONG)10 * 60 * 1000 * 1000 * 10)
Definition at line 86 of file worker.c.
Referenced by ExpWorkerThread().
#define DYNAMIC_WORKER_THREAD 0x80000000
Definition at line 99 of file worker.c.
Referenced by ExpCreateWorkerThread(), and ExpWorkerThread().
#define HYPER_CRITICAL_WORK_QUEUE_PRIORITY (15 - NORMAL_BASE_PRIORITY)
Definition at line 69 of file worker.c.
Referenced by ExpCreateWorkerThread().
#define LARGE_NUMBER_OF_THREADS 5
Definition at line 80 of file worker.c.
Referenced by ExpWorkerInitialization().
#define MAX_ADDITIONAL_DYNAMIC_THREADS 16
Definition at line 76 of file worker.c.
Referenced by ExpDetectWorkerThreadDeadlock(), and ExpNewThreadNecessary().
#define MAX_ADDITIONAL_THREADS 16
Definition at line 75 of file worker.c.
Referenced by ExpWorkerInitialization().
#define MEDIUM_NUMBER_OF_THREADS 3
Definition at line 79 of file worker.c.
Referenced by ExpWorkerInitialization().
#define SMALL_NUMBER_OF_THREADS 2
Definition at line 78 of file worker.c.
#define THREAD_SET_INTERVAL (1 * 1000 * 1000 * 10)
Definition at line 92 of file worker.c.
Referenced by ExpWorkerThreadBalanceManager().
Typedef Documentation
typedef enum _BALANCE_OBJECT BALANCE_OBJECT
typedef struct _EXP_WORKER_LINK EXP_WORKER_LINK
typedef struct _EXP_WORKER_LINK * PEXP_WORKER_LINK
typedef struct SHUTDOWN_WORK_ITEM * PSHUTDOWN_WORK_ITEM
Enumeration Type Documentation
enum _BALANCE_OBJECT
Enumerator
TimerExpiration
ThreadSetManagerEvent
ShutdownEvent
MaximumBalanceObject
TimerExpiration
WorkingSetManagerEvent
MaximumObject
Definition at line 26 of file worker.c.
Function Documentation
C_ASSERT (MaximumBalanceObject<= THREAD_WAIT_OBJECTS)
VOID ExpCheckDynamicThreadCount (VOID)
Definition at line 721 of file worker.c.
References ExpCreateWorkerThread(), ExpNewThreadNecessary(), MaximumWorkQueue, PAGED_CODE, and TRUE.
Referenced by ExpWorkerThreadBalanceManager().
VOID ExpCheckForWorker (IN PVOID p, IN SIZE_T Size)
Definition at line 952 of file worker.c.
References CriticalWorkQueue, _KQUEUE::EntryListHead, _LIST_ENTRY::Flink, KeBugCheckEx(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), MaximumWorkQueue, WORKER_INVALID, and _EX_WORK_QUEUE::WorkerQueue.
Referenced by ExFreePoolSanityChecks().
LOGICAL ExpCheckQueueShutdown (IN WORK_QUEUE_TYPE QueueType, IN PSHUTDOWN_WORK_ITEM ShutdownItem)
Definition at line 1444 of file worker.c.
References FALSE, KeInsertQueue(), ObReferenceObject, PO_SHUTDOWN_QUEUE, PsGetCurrentThread(), and TRUE.
Referenced by ExpShutdownWorker().
NTSTATUS ExpCreateWorkerThread (WORK_QUEUE_TYPE QueueType, BOOLEAN Dynamic)
Referenced by ExpCheckDynamicThreadCount(), ExpDetectWorkerThreadDeadlock(), and ExpWorkerInitialization().
NTSTATUS ExpCreateWorkerThread (IN WORK_QUEUE_TYPE QueueType, IN BOOLEAN Dynamic)
Definition at line 846 of file worker.c.
References CRITICAL_WORK_QUEUE_PRIORITY, CriticalWorkQueue, DELAYED_WORK_QUEUE_PRIORITY, DelayedWorkQueue, DYNAMIC_WORKER_THREAD, ExpWorkerThread(), FALSE, HYPER_CRITICAL_WORK_QUEUE_PRIORITY, HyperCriticalWorkQueue, InitializeObjectAttributes, InterlockedIncrement, KernelMode, KeSetBasePriorityThread(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PsCreateSystemThread(), PsThreadType, Status, _ETHREAD::Tcb, _EXP_WORKER_LINK::Thread, THREAD_ALL_ACCESS, THREAD_SET_INFORMATION, and ZwClose().
VOID ExpDebuggerWorker (IN PVOID Context)
Definition at line 1606 of file worker.c.
References DBG_STATUS_WORKER, DBG_TERMINATE_PROCESS, DbgBreakPointWithStatus(), DbgPrint(), except, EXCEPTION_EXECUTE_HANDLER, ExpDebuggerPageIn, ExpDebuggerProcessAttach, ExpDebuggerProcessKill, ExpDebuggerWork, KeStackAttachProcess(), KeUnstackDetachProcess(), NULL, PageIn, _EPROCESS::Pcb, ProbeAndReadUchar, PsGetNextProcess(), PsQuitNextProcess(), PsTerminateProcess(), Status, and UNREFERENCED_PARAMETER.
Referenced by ExpWorkerThreadBalanceManager().
VOID ExpDetectWorkerThreadDeadlock (VOID)
Definition at line 774 of file worker.c.
References ASSERT, _EX_WORK_QUEUE::DynamicThreadCount, ExpCreateWorkerThread(), Index, KeReadStateQueue(), MAX_ADDITIONAL_DYNAMIC_THREADS, MaximumWorkQueue, PAGED_CODE, _EX_WORK_QUEUE::QueueDepthLastPass, TRUE, _EX_WORK_QUEUE::WorkerQueue, _EX_WORK_QUEUE::WorkItemsProcessed, and _EX_WORK_QUEUE::WorkItemsProcessedLastPass.
Referenced by ExpWorkerThreadBalanceManager().
LOGICAL __forceinline ExpNewThreadNecessary (IN PEX_WORK_QUEUE Queue)
Definition at line 231 of file worker.c.
References FALSE, IsListEmpty, MAX_ADDITIONAL_DYNAMIC_THREADS, and TRUE.
Referenced by ExpCheckDynamicThreadCount(), and ExQueueWorkItem().
VOID ExpSetSwappingKernelApc (IN PKAPC Apc, OUT PKNORMAL_ROUTINE * NormalRoutine, IN OUT PVOID NormalContext, IN OUT PVOID * SystemArgument1, IN OUT PVOID * SystemArgument2)
Definition at line 1299 of file worker.c.
References _ETHREAD::ActiveExWorker, FALSE, KeSetEvent(), KeSetKernelStackSwapEnable(), PsGetCurrentThread(), and UNREFERENCED_PARAMETER.
Referenced by ExSwapinWorkerThreads().
VOID ExpShutdownWorker (IN PVOID Parameter)
Definition at line 1487 of file worker.c.
References _ETHREAD::ActiveExWorker, ASSERT, CriticalWorkQueue, DelayedWorkQueue, Executive, ExpCheckQueueShutdown(), FALSE, _EX_WORK_QUEUE::Info, InterlockedDecrement, KernelMode, KeSetEvent(), KeSetKernelStackSwapEnable(), KeWaitForSingleObject(), NULL, ObDereferenceObject(), ObReferenceObject, SHUTDOWN_WORK_ITEM::PrevThread, PsGetCurrentThread(), PsTerminateSystemThread(), SHUTDOWN_WORK_ITEM::QueueType, EX_QUEUE_WORKER_INFO::QueueWorkerInfo, STATUS_SYSTEM_SHUTDOWN, and TRUE.
Referenced by ExpShutdownWorkerThreads().
VOID ExpShutdownWorkerThreads (VOID)
Definition at line 1545 of file worker.c.
References ASSERT, CriticalWorkQueue, DelayedWorkQueue, EX_WORKER_QUEUE_DISABLED, Executive, ExInitializeWorkItem, ExpShutdownWorker(), FALSE, KeGetCurrentThread(), KeInsertQueue(), KernelMode, KeWaitForSingleObject(), _WORK_QUEUE_ITEM::List, NULL, ObDereferenceObject(), PO_CLEAN_SHUTDOWN_WORKERS, PO_SHUTDOWN_QUEUE, PoCleanShutdownEnabled(), SHUTDOWN_WORK_ITEM::PrevThread, SHUTDOWN_WORK_ITEM::QueueType, RtlInterlockedSetBitsDiscardReturn, and SHUTDOWN_WORK_ITEM::WorkItem.
NTSTATUS ExpWorkerInitialization (VOID)
Definition at line 286 of file worker.c.
References CriticalWorkQueue, DelayedWorkQueue, ExCriticalWorkerThreads, ExDelayedWorkerThreads, ExInitializeFastMutex, ExpAdditionalCriticalWorkerThreads, ExpAdditionalDelayedWorkerThreads, ExpCreateWorkerThread(), ExpWorkersCanSwap, ExpWorkerThreadBalanceManager(), FALSE, HyperCriticalWorkQueue, Index, _EX_WORK_QUEUE::Info, InitializeListHead(), InitializeObjectAttributes, KeInitializeEvent(), KeInitializeQueue(), KernelMode, LARGE_NUMBER_OF_THREADS, EX_QUEUE_WORKER_INFO::MakeThreadsAsNecessary, MAX_ADDITIONAL_THREADS, MaximumWorkQueue, MEDIUM_NUMBER_OF_THREADS, MmIsThisAnNtAsSystem(), MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSmallSystem, NT_SUCCESS, NULL, ObReferenceObjectByHandle, PsCreateSystemThread(), RtlZeroMemory, Status, SynchronizationEvent, SYNCHRONIZE, _EXP_WORKER_LINK::Thread, THREAD_ALL_ACCESS, TRUE, UserMode, EX_QUEUE_WORKER_INFO::WaitMode, and ZwClose().
Referenced by ExpInitSystemPhase1().
VOID ExpWorkerThread (IN PVOID StartContext)
Definition at line 996 of file worker.c.
References _ETHREAD::ActiveExWorker, ASSERT, _KTHREAD::CombinedApcDisable, CONTAINING_RECORD, DbgPrint(), DYNAMIC_THREAD_TIMEOUT, DYNAMIC_WORKER_THREAD, _EX_WORK_QUEUE::DynamicThreadCount, ExpWorkerApcDisabledMessage, ExpWorkersCanSwap, _ETHREAD::ExWorkerCanWaitUser, FALSE, IMPERSONATING_WORKER_THREAD, _EX_WORK_QUEUE::Info, InterlockedCompareExchange(), InterlockedDecrement, InterlockedIncrement, IoRemoteBootClient, _ETHREAD::IrpList, IsListEmpty, KeBugCheckEx(), KeGetCurrentIrql(), KeRemoveQueue(), KeSetKernelStackSwapEnable(), List, MmUserProbeAddress, NULL, _WORK_QUEUE_ITEM::Parameter, PASSIVE_LEVEL, PO_SHUTDOWN_QUEUE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), PsTerminateSystemThread(), _LARGE_INTEGER::QuadPart, EX_QUEUE_WORKER_INFO::QueueDisabled, EX_QUEUE_WORKER_INFO::QueueWorkerInfo, ReadForWriteAccess, STATUS_SYSTEM_SHUTDOWN, STATUS_TIMEOUT, _ETHREAD::Tcb, _EXP_WORKER_LINK::Thread, TRUE, UserMode, EX_QUEUE_WORKER_INFO::WaitMode, WORKER_THREAD_RETURNED_AT_BAD_IRQL, EX_QUEUE_WORKER_INFO::WorkerCount, _EX_WORK_QUEUE::WorkerQueue, _WORK_QUEUE_ITEM::WorkerRoutine, and _EX_WORK_QUEUE::WorkItemsProcessed.
Referenced by ExpCreateWorkerThread().
VOID ExpWorkerThreadBalanceManager (IN PVOID StartContext)
Definition at line 571 of file worker.c.
References ASSERT, CRITICAL_WORK_QUEUE_PRIORITY, DelayedWorkQueue, Executive, ExInitializeWorkItem, ExpCheckDynamicThreadCount(), ExpDebuggerWork, ExpDebuggerWorker(), ExpDetectWorkerThreadDeadlock(), ExQueueWorkItem(), FALSE, KeCancelTimer(), KeGetCurrentThread(), KeInitializeTimer(), KernelMode, KeSetBasePriorityThread(), KeSetTimer(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), MaximumBalanceObject, NULL, ObDereferenceObject(), PAGED_CODE, PsTerminateSystemThread(), _LARGE_INTEGER::QuadPart, ShutdownEvent, Status, STATUS_SYSTEM_SHUTDOWN, THREAD_SET_INTERVAL, ThreadSetManagerEvent, TimerExpiration, TRUE, UNREFERENCED_PARAMETER, and WaitAny.
Referenced by ExpWorkerInitialization().
VOID ExQueueWorkItem (__inout PWORK_QUEUE_ITEM WorkItem, __in WORK_QUEUE_TYPE QueueType)
Definition at line 489 of file worker.c.
References ASSERT, ExpNewThreadNecessary(), FALSE, _EX_WORK_QUEUE::Info, KeBugCheckEx(), KeInsertQueue(), KeSetEvent(), MaximumWorkQueue, MmUserProbeAddress, NULL, EX_QUEUE_WORKER_INFO::QueueDisabled, WORKER_INVALID, and _EX_WORK_QUEUE::WorkerQueue.
Referenced by CcPostWorkQueue(), CmpCanGrowSystemHive(), CmpDelayCloseDpcRoutine(), CmpDelayDerefKCBDpcRoutine(), CmpDiskFullWarning(), CmpDoQueueLateUnloadWorker(), CmpLazyFlushDpcRoutine(), CmpPostNotify(), CmpRaiseSelfHealWarning(), CmpRaiseSelfHealWarningWorker(), CmpUpdateSystemHiveHysteresis(), ExpWorkerThreadBalanceManager(), IopCompleteUnloadOrDelete(), IopErrorLogDpc(), IopSendMessageToTrackService(), IopUnloadDriver(), IoQueueWorkItem(), IoRaiseHardError(), IoRaiseInformationalHardError(), IoWMIWriteEvent(), IoWriteErrorLogEntry(), MiNoPagesLastChance(), MiReleaseSystemPtes(), MiStartZeroPageWorkers(), MiWriteComplete(), MiZeroAllPageFiles(), NtLoadDriver(), ObpDeferObjectDeletion(), PspJobTimeLimitsDpcRoutine(), SepInformFileSystemsOfDeletedLogon(), SepQueueWorkItem(), WmipInitializeRegistration(), WmipIsWbemRunningDispatch(), WmipMceDispatchRoutine(), WmipQueueNotification(), WmipQueueRegWork(), and WmipTraceIo().
VOID ExSwapinWorkerThreads (IN BOOLEAN AllowSwap)
Definition at line 1336 of file worker.c.
References ExAcquireFastMutex(), Executive, ExpSetSwappingKernelApc(), ExpWorkersCanSwap, ExReleaseFastMutex(), _ETHREAD::ExWorkerCanWaitUser, FALSE, InsertApcEnvironment, KeClearEvent(), KeInitializeApc(), KeInitializeEvent(), KeInsertQueueApc(), KernelMode, KeSetKernelStackSwapEnable(), KeWaitForSingleObject(), NotificationEvent, NULL, PAGED_CODE, PsGetCurrentThread(), PsGetNextProcessThread(), PsInitialSystemProcess, _ETHREAD::Tcb, and _EXP_WORKER_LINK::Thread.
Variable Documentation
ULONG ExCriticalWorkerThreads
Definition at line 114 of file worker.c.
Referenced by CcInitializeCacheManager(), and ExpWorkerInitialization().
ULONG ExDelayedWorkerThreads
Definition at line 115 of file worker.c.
Referenced by ExpWorkerInitialization().
ULONG ExpAdditionalCriticalWorkerThreads
Definition at line 111 of file worker.c.
Referenced by ExpWorkerInitialization().
ULONG ExpAdditionalDelayedWorkerThreads
Definition at line 112 of file worker.c.
Referenced by ExpWorkerInitialization().
PVOID ExpDebuggerPageIn
Definition at line 157 of file worker.c.
Referenced by ExpDebuggerWorker().
PVOID ExpDebuggerProcessAttach
Definition at line 156 of file worker.c.
Referenced by ExpDebuggerWorker().
PVOID ExpDebuggerProcessKill
Definition at line 155 of file worker.c.
Referenced by ExpDebuggerWorker().
ULONG ExpDebuggerWork
Definition at line 158 of file worker.c.
Referenced by ExpDebuggerWorker(), and ExpWorkerThreadBalanceManager().
WORK_QUEUE_ITEM ExpDebuggerWorkItem
Definition at line 154 of file worker.c.
PETHREAD ExpLastWorkerThread
Definition at line 136 of file worker.c.
KEVENT ExpThreadSetManagerEvent
Definition at line 121 of file worker.c.
KEVENT ExpThreadSetManagerShutdownEvent
Definition at line 122 of file worker.c.
const char ExpWorkerApcDisabledMessage[]
Initial value:
=
    "EXWORKER: worker exit with APCs disabled, worker routine %x, parameter %x, item %x\n"
Definition at line 989 of file worker.c.
Referenced by ExpWorkerThread().
LIST_ENTRY ExpWorkerListHead
Definition at line 146 of file worker.c.
BOOLEAN ExpWorkersCanSwap
Definition at line 147 of file worker.c.
Referenced by ExpWorkerInitialization(), ExpWorkerThread(), and ExSwapinWorkerThreads().
FAST_MUTEX ExpWorkerSwapinMutex
Definition at line 145 of file worker.c.
PETHREAD ExpWorkerThreadBalanceManagerPtr
Definition at line 129 of file worker.c.
EX_WORK_QUEUE ExWorkerQueue[MaximumWorkQueue]
Definition at line 105 of file worker.c.
Referenced by KeRemoveQueue(), and KeTerminateThread().