Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/i386/psvdm.c File Reference
psvdm.c File Reference
#include "psp.h"
Macros
#define ASSERTEQUAL(value1, value2, string)
#define ASSERTEQUALBREAK(value1, value2, string)
Functions
BOOLEAN Ps386GetVdmIoHandler (IN PEPROCESS Process, IN ULONG PortNumber, OUT PVDM_IO_HANDLER VdmIoHandler, OUT PULONG Context)
NTSTATUS Psp386CreateVdmIoListHead (IN PEPROCESS Process)
PVDM_IO_HANDLER Psp386GetVdmIoHandler (IN PEPROCESS Process, IN ULONG PortNumber)
NTSTATUS Psp386InsertVdmIoHandlerBlock (IN PEPROCESS Process, IN PVDM_IO_HANDLER VdmIoHandler)
NTSTATUS Psp386InstallIoHandler (IN PEPROCESS Process, IN PEMULATOR_ACCESS_ENTRY EmulatorAccessEntry, IN ULONG PortNumber, IN ULONG Context)
NTSTATUS Psp386RemoveIoHandler (IN PEPROCESS Process, IN PEMULATOR_ACCESS_ENTRY EmulatorAccessEntry, IN ULONG PortNumber)
VOID PspDeleteVdmObjects (IN PEPROCESS Process)
NTSTATUS PspSetProcessIoHandlers (IN PEPROCESS Process, IN PVOID IoHandlerInformation, IN ULONG IoHandlerLength)
NTSTATUS PspVdmInitialize ()
Variables
ERESOURCE VdmIoListCreationResource
Macro Definition Documentation
#define ASSERTEQUAL (value1, value2, string)
Definition at line 35 of file psvdm.c.
Referenced by Psp386RemoveIoHandler().
#define ASSERTEQUALBREAK (value1, value2, string)
Definition at line 36 of file psvdm.c.
Referenced by Psp386InstallIoHandler(), and Psp386RemoveIoHandler().
Function Documentation
BOOLEAN Ps386GetVdmIoHandler (IN PEPROCESS Process, IN ULONG PortNumber, OUT PVDM_IO_HANDLER VdmIoHandler, OUT PULONG Context)
Definition at line 882 of file psvdm.c.
References APC_LEVEL, DbgPrint(), ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FALSE, KeLowerIrql, KeRaiseIrql, NULL, PAGED_CODE, Psp386GetVdmIoHandler(), and TRUE.
NTSTATUS Psp386CreateVdmIoListHead (IN PEPROCESS Process)
Definition at line 744 of file psvdm.c.
References APC_LEVEL, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExInitializeResourceLite(), ExReleaseResourceLite(), KeLowerIrql, KeRaiseIrql, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by Psp386InstallIoHandler().
PVDM_IO_HANDLER Psp386GetVdmIoHandler (IN PEPROCESS Process, IN ULONG PortNumber)
Definition at line 956 of file psvdm.c.
References DbgPrint(), _VDM_IO_HANDLER::Next, NULL, PAGED_CODE, and _VDM_IO_HANDLER::PortNumber.
Referenced by Ps386GetVdmIoHandler(), Psp386InstallIoHandler(), and Psp386RemoveIoHandler().
NTSTATUS Psp386InsertVdmIoHandlerBlock (IN PEPROCESS Process, IN PVDM_IO_HANDLER VdmIoHandler)
Definition at line 827 of file psvdm.c.
References DbgPrint(), HandlerList, _VDM_IO_HANDLER::Next, NULL, PAGED_CODE, _VDM_IO_HANDLER::PortNumber, and STATUS_SUCCESS.
Referenced by Psp386InstallIoHandler().
NTSTATUS Psp386InstallIoHandler (IN PEPROCESS Process, IN PEMULATOR_ACCESS_ENTRY EmulatorAccessEntry, IN ULONG PortNumber, IN ULONG Context)
Definition at line 492 of file psvdm.c.
References APC_LEVEL, ASSERTEQUALBREAK, DbgPrint(), EMULATOR_READ_ACCESS, EMULATOR_WRITE_ACCESS, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExReleaseResourceLite(), _VDM_IO_HANDLER::IoFunctions, KeLowerIrql, KeRaiseIrql, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _VDM_IO_HANDLER::PortNumber, Psp386CreateVdmIoListHead(), Psp386GetVdmIoHandler(), Psp386InsertVdmIoHandlerBlock(), RtlZeroMemory, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, Uchar, _VDM_IO_HANDLER_FUNCTIONS::UcharIo, _VDM_IO_HANDLER_FUNCTIONS::UcharStringIo, Ulong, _VDM_IO_HANDLER_FUNCTIONS::UlongIo, _VDM_IO_HANDLER_FUNCTIONS::UlongStringIo, Ushort, _VDM_IO_HANDLER_FUNCTIONS::UshortIo, and _VDM_IO_HANDLER_FUNCTIONS::UshortStringIo.
Referenced by PspSetProcessIoHandlers().
NTSTATUS Psp386RemoveIoHandler (IN PEPROCESS Process, IN PEMULATOR_ACCESS_ENTRY EmulatorAccessEntry, IN ULONG PortNumber)
Definition at line 295 of file psvdm.c.
References APC_LEVEL, ASSERTEQUAL, ASSERTEQUALBREAK, DbgPrint(), EMULATOR_READ_ACCESS, EMULATOR_WRITE_ACCESS, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _VDM_IO_HANDLER::IoFunctions, KeLowerIrql, KeRaiseIrql, NULL, PAGED_CODE, _VDM_IO_HANDLER::PortNumber, Psp386GetVdmIoHandler(), STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, Uchar, _VDM_IO_HANDLER_FUNCTIONS::UcharIo, _VDM_IO_HANDLER_FUNCTIONS::UcharStringIo, Ulong, _VDM_IO_HANDLER_FUNCTIONS::UlongIo, _VDM_IO_HANDLER_FUNCTIONS::UlongStringIo, Ushort, _VDM_IO_HANDLER_FUNCTIONS::UshortIo, and _VDM_IO_HANDLER_FUNCTIONS::UshortStringIo.
Referenced by PspSetProcessIoHandlers().
VOID PspDeleteVdmObjects (IN PEPROCESS Process)
Definition at line 203 of file psvdm.c.
References CONTAINING_RECORD, ExDeleteResourceLite(), ExFreePool(), _LIST_ENTRY::Flink, _VDM_IO_HANDLER::Next, NULL, PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPagedPoolQuota(), RemoveEntryList(), and UNREFERENCED_PARAMETER.
NTSTATUS PspSetProcessIoHandlers (IN PEPROCESS Process, IN PVOID IoHandlerInformation, IN ULONG IoHandlerLength)
Definition at line 100 of file psvdm.c.
References _EMULATOR_ACCESS_ENTRY::AccessType, _EMULATOR_ACCESS_ENTRY::BasePort, _PROCESS_IO_PORT_HANDLER_INFORMATION::Context, _PROCESS_IO_PORT_HANDLER_INFORMATION::EmulatorAccessEntries, _PROCESS_IO_PORT_HANDLER_INFORMATION::Install, KeGetPreviousMode, KernelMode, NT_SUCCESS, _EMULATOR_ACCESS_ENTRY::NumConsecutivePorts, PAGED_CODE, Psp386InstallIoHandler(), Psp386RemoveIoHandler(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, Uchar, Ulong, UNREFERENCED_PARAMETER, and Ushort.
NTSTATUS PspVdmInitialize ()
Definition at line 1002 of file psvdm.c.
References ExInitializeResourceLite().
Referenced by PspInitPhase0().
Variable Documentation
ERESOURCE VdmIoListCreationResource
Definition at line 94 of file psvdm.c.