Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/fastref.c File Reference
fastref.c File Reference
#include "obp.h"
Functions
NTKERNELAPI VOID FASTCALL ObFastDereferenceObject (IN PEX_FAST_REF FastRef, IN PVOID Object)
NTKERNELAPI PVOID FASTCALL ObFastReferenceObject (IN PEX_FAST_REF FastRef)
NTKERNELAPI PVOID FASTCALL ObFastReferenceObjectLocked (IN PEX_FAST_REF FastRef)
NTKERNELAPI PVOID FASTCALL ObFastReplaceObject (IN PEX_FAST_REF FastRef, IN PVOID Object)
NTKERNELAPI VOID FASTCALL ObInitializeFastReference (IN PEX_FAST_REF FastRef, IN PVOID Object)
Function Documentation
NTKERNELAPI VOID FASTCALL ObFastDereferenceObject (IN PEX_FAST_REF FastRef, IN PVOID Object)
Definition at line 222 of file fastref.c.
References ExFastRefDereference(), and ObDereferenceObject().
NTKERNELAPI PVOID FASTCALL ObFastReferenceObject (IN PEX_FAST_REF FastRef)
Definition at line 127 of file fastref.c.
References ExFastRefAddAdditionalReferenceCounts(), ExFastReference(), ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefGetUnusedReferences(), NULL, ObDereferenceObjectEx(), and ObReferenceObjectEx().
Referenced by PsReferenceEffectiveToken(), and PsReferencePrimaryToken().
NTKERNELAPI PVOID FASTCALL ObFastReferenceObjectLocked (IN PEX_FAST_REF FastRef)
Definition at line 188 of file fastref.c.
References ExFastRefGetObject(), NULL, and ObReferenceObject.
Referenced by PsReferenceEffectiveToken(), and PsReferencePrimaryToken().
NTKERNELAPI PVOID FASTCALL ObFastReplaceObject (IN PEX_FAST_REF FastRef, IN PVOID Object)
Definition at line 254 of file fastref.c.
References ExFastRefGetAdditionalReferenceCount(), ExFastRefGetObject(), ExFastRefGetUnusedReferences(), ExFastRefSwapObject(), NULL, ObDereferenceObjectEx(), and ObReferenceObjectEx().
Referenced by SeDeassignPrimaryToken(), and SeExchangePrimaryToken().
NTKERNELAPI VOID FASTCALL ObInitializeFastReference (IN PEX_FAST_REF FastRef, IN PVOID Object)
Definition at line 95 of file fastref.c.
References ExFastRefGetAdditionalReferenceCount(), ExFastRefInitialize(), NULL, and ObReferenceObjectEx().
Referenced by PspInitializeProcessSecurity(), SeAssignPrimaryToken(), and SepInitializationPhase0().