Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/amd64/psldt.c File Reference
psldt.c File Reference
#include "psp.h"
Functions
NTSTATUS NtSetLdtEntries (__in ULONG Selector0, __in ULONG Entry0Low, __in ULONG Entry0Hi, __in ULONG Selector1, __in ULONG Entry1Low, __in ULONG Entry1Hi)
VOID PspDeleteLdt (IN PEPROCESS Process)
NTSTATUS PspQueryDescriptorThread (PETHREAD Thread, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength)
NTSTATUS PspQueryLdtInformation (IN PEPROCESS Process, OUT PVOID LdtInformation, IN ULONG LdtInformationLength, OUT PULONG ReturnLength)
NTSTATUS PspSetLdtInformation (IN PEPROCESS Process, IN PVOID LdtInformation, IN ULONG LdtInformationLength)
NTSTATUS PspSetLdtSize (IN PEPROCESS Process, IN PVOID LdtSize, IN ULONG LdtSizeLength)
Function Documentation
NTSTATUS NtSetLdtEntries (__in ULONG Selector0, __in ULONG Entry0Low, __in ULONG Entry0Hi, __in ULONG Selector1, __in ULONG Entry1Low, __in ULONG Entry1Hi)
Definition at line 206 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
VOID PspDeleteLdt (IN PEPROCESS Process)
Definition at line 178 of file psldt.c.
Referenced by PspProcessDelete().
NTSTATUS PspQueryDescriptorThread (PETHREAD Thread, PVOID ThreadInformation, ULONG ThreadInformationLength, PULONG ReturnLength)
Definition at line 135 of file psldt.c.
Referenced by NtQueryInformationThread().
NTSTATUS PspQueryLdtInformation (IN PEPROCESS Process, OUT PVOID LdtInformation, IN ULONG LdtInformationLength, OUT PULONG ReturnLength)
Definition at line 22 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtQueryInformationProcess().
NTSTATUS PspSetLdtInformation (IN PEPROCESS Process, IN PVOID LdtInformation, IN ULONG LdtInformationLength)
Definition at line 99 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtSetInformationProcess().
NTSTATUS PspSetLdtSize (IN PEPROCESS Process, IN PVOID LdtSize, IN ULONG LdtSizeLength)
Definition at line 63 of file psldt.c.
References STATUS_NOT_IMPLEMENTED, and UNREFERENCED_PARAMETER.
Referenced by NtSetInformationProcess().