Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iopcmn.h File Reference
iopcmn.h File Reference
#include "pnpmgr\pplastgood.h"
Macros
#define ALIGN_POINTER(Offset)
#define ALIGN_POINTER_OFFSET(Offset) (ULONG_PTR) ALIGN_POINTER(Offset)
#define IopInitializeIrp(Irp, PacketSize, StackSize)
#define IopWstrToUnicodeString(u, p)
#define KEY_VALUE_DATA(k) ((PCHAR)(k) + (k)->DataOffset)
#define TITLE_INDEX_VALUE 0
Typedefs
typedef struct _DEVICE_NODE DEVICE_NODE
typedef struct _DEVICE_NODE * PDEVICE_NODE
Functions
NTSTATUS IopAddRemoteBootValuesToRegistry (PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopBuildFullDriverPath (IN PUNICODE_STRING KeyName, IN HANDLE KeyHandle, OUT PUNICODE_STRING FullPath)
BOOLEAN IopCallBootDriverReinitializationRoutines ()
BOOLEAN IopCallDriverReinitializationRoutines ()
VOID IopChainDereferenceComplete (IN PDEVICE_OBJECT PhysicalDeviceObject, IN BOOLEAN OnCleanStack)
NTSTATUS IopCreateArcNames (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
PSECURITY_DESCRIPTOR IopCreateDefaultDeviceSecurityDescriptor (IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN DeviceHasName, IN PUCHAR Buffer, OUT PACL *AllocatedAcl, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
NTSTATUS IopCreateRegistryKeyEx (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess, IN ULONG CreateOptions, OUT PULONG Disposition OPTIONAL)
VOID IopDecrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
VOID IopDestroyDeviceNode (PDEVICE_NODE DeviceNode)
NTSTATUS IopDriverLoadingFailed (IN HANDLE KeyHandle OPTIONAL, IN PUNICODE_STRING KeyName OPTIONAL)
NTSTATUS IopGetDriverNameFromKeyNode (IN HANDLE KeyHandle, OUT PUNICODE_STRING DriverName)
NTSTATUS IopGetRegistryKeyInformation (IN HANDLE KeyHandle, OUT PKEY_FULL_INFORMATION *Information)
NTSTATUS IopGetRegistryValue (IN HANDLE KeyHandle, IN PWSTR ValueName, OUT PKEY_VALUE_FULL_INFORMATION *Information)
VOID IopIncrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
BOOLEAN IopInitializeBootDrivers (IN PLOADER_PARAMETER_BLOCK LoaderBlock, OUT PDRIVER_OBJECT *PreviousDriver)
NTSTATUS IopInitializeBuiltinDriver (IN PUNICODE_STRING DriverName, IN PUNICODE_STRING RegistryPath, IN PDRIVER_INITIALIZE DriverInitializeRoutine, IN PKLDR_DATA_TABLE_ENTRY TableEntry, IN BOOLEAN IsFilter, OUT PDRIVER_OBJECT *DriverObject)
NTSTATUS IopInitializePlugPlayServices (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN ULONG Phase)
BOOLEAN IopInitializeSystemDrivers (VOID)
NTSTATUS IopInvalidateVolumesForDevice (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopInvalidDeviceRequest (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
BOOLEAN IopIsLegacyDriver (IN PDRIVER_OBJECT DriverObject)
BOOLEAN IopIsRemoteBootCard (IN PIO_RESOURCE_REQUIREMENTS_LIST ResourceRequirements, IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PWCHAR HwIds)
NTSTATUS IopLoadDriver (IN HANDLE KeyHandle, IN BOOLEAN CheckForSafeBoot, IN BOOLEAN IsFilter, OUT NTSTATUS *DriverEntryStatus)
BOOLEAN IopMarkBootPartition (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID IopMarkHalDeviceNode (VOID)
NTSTATUS IopOpenRegistryKeyEx (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess)
NTSTATUS IopPnpDriverStarted (IN PDRIVER_OBJECT DriverObject, IN HANDLE KeyHandle, IN PUNICODE_STRING ServiceName)
NTSTATUS IopPrepareDriverLoading (IN PUNICODE_STRING KeyName, IN HANDLE KeyHandle, IN PVOID ImageBase, IN BOOLEAN IsFilter)
VOID FORCEINLINE IopQueueThreadIrp (IN PIRP Irp)
PDRIVER_OBJECT IopReferenceDriverObjectByName (IN PUNICODE_STRING DriverName)
BOOLEAN IopSafebootDriverLoad (PUNICODE_STRING DriverId)
NTSTATUS IopSetupRemoteBootCard (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN HANDLE UniqueIdHandle, IN PUNICODE_STRING UnicodeDeviceInstance)
NTSTATUS IopStartNetworkForRemoteBoot (PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopStartTcpIpForRemoteBoot (PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopSynchronousCall (IN PDEVICE_OBJECT DeviceObject, IN PIO_STACK_LOCATION TopStackLocation, OUT PULONG_PTR Information)
NTSTATUS IopUnloadDriver (IN PUNICODE_STRING DriverServiceName, IN BOOLEAN InvokedByPnpMgr)
NTSTATUS PpDriverObjectDereferenceComplete (IN PDRIVER_OBJECT DriverObject)
Variables
POBJECT_TYPE IoDeviceObjectType
POBJECT_TYPE IoDriverObjectType
POBJECT_TYPE IoFileObjectType
PVOID IopLoaderBlock
Macro Definition Documentation
#define ALIGN_POINTER (Offset)
Value:
(PVOID) \
        ((((ULONG_PTR)(Offset) + sizeof(ULONG_PTR)-1)) & (~(sizeof(ULONG_PTR) - 1)))
Definition at line 31 of file iopcmn.h.
#define ALIGN_POINTER_OFFSET (Offset) (ULONG_PTR) ALIGN_POINTER(Offset)
Definition at line 34 of file iopcmn.h.
Referenced by IopGetRegistryValue().
#define IopInitializeIrp (Irp, PacketSize, StackSize)
Value:
{          \
    RtlZeroMemory( (Irp), (PacketSize) );                         \
    (Irp)->Type = (CSHORT) IO_TYPE_IRP;                           \
    (Irp)->Size = (USHORT) ((PacketSize));                        \
    (Irp)->StackCount = (CCHAR) ((StackSize));                    \
    (Irp)->CurrentLocation = (CCHAR) ((StackSize) + 1);           \
    (Irp)->ApcEnvironment = KeGetCurrentApcEnvironment();         \
    InitializeListHead (&(Irp)->ThreadListEntry);                 \
    (Irp)->Tail.Overlay.CurrentStackLocation =                    \
        ((PIO_STACK_LOCATION) ((UCHAR *) (Irp) +                  \
            sizeof( IRP ) +                                       \
            ( (StackSize) * sizeof( IO_STACK_LOCATION )))); }
Definition at line 76 of file iopcmn.h.
Referenced by IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), and IoReuseIrp().
#define IopWstrToUnicodeString (u, p)
Value:
\
    (u)->Length = ((u)->MaximumLength = sizeof((p))) - sizeof(WCHAR);   \
    (u)->Buffer = (p)
Definition at line 245 of file iopcmn.h.
#define KEY_VALUE_DATA (k) ((PCHAR)(k) + (k)->DataOffset)
Definition at line 29 of file iopcmn.h.
Referenced by IopBuildFullDriverPath().
#define TITLE_INDEX_VALUE 0
Definition at line 234 of file iopcmn.h.
Typedef Documentation
typedef struct _DEVICE_NODE DEVICE_NODE
Definition at line 276 of file iopcmn.h.
typedef struct _DEVICE_NODE * PDEVICE_NODE
Definition at line 276 of file iopcmn.h.
Function Documentation
NTSTATUS IopAddRemoteBootValuesToRegistry (PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by IoInitSystem().
NTSTATUS IopBuildFullDriverPath (IN PUNICODE_STRING KeyName, IN HANDLE KeyHandle, OUT PUNICODE_STRING FullPath)
Definition at line 3340 of file internal.c.
References _KEY_VALUE_FULL_INFORMATION::DataLength, ExAllocatePool, ExFreePool(), IopGetRegistryValue(), KEY_VALUE_DATA, NT_SUCCESS, NULL, PagedPool, RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by IopLoadDriver().
BOOLEAN IopCallBootDriverReinitializationRoutines ()
BOOLEAN IopCallDriverReinitializationRoutines ()
VOID IopChainDereferenceComplete (IN PDEVICE_OBJECT PhysicalDeviceObject, IN BOOLEAN OnCleanStack)
Referenced by IopCompleteUnloadOrDelete().
NTSTATUS IopCreateArcNames (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 1919 of file ioinit.c.
References DbgPrint(), _ARC_DISK_INFORMATION::DiskSignatures, ExAllocatePool, FALSE, _LIST_ENTRY::Flink, IoArcBootDeviceName, IoArcHalDeviceName, IoCreateSymbolicLink(), IoLoaderArcBootDeviceName, IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopStoreSystemPartitionInformation(), IoRemoteBootClient, memcpy(), NT_SUCCESS, PagedPool, RtlAnsiStringToUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), sprintf(), strlen(), strstr(), and TRUE.
PSECURITY_DESCRIPTOR IopCreateDefaultDeviceSecurityDescriptor (IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN DeviceHasName, IN PUCHAR Buffer, OUT PACL * AllocatedAcl, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
Definition at line 13270 of file iosubs.c.
References _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, DACL_SECURITY_INFORMATION, ExAllocatePoolWithTag, FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DFS_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_MASS_STORAGE, FILE_DEVICE_NETWORK, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_DEVICE_VIRTUAL_DISK, FILE_FLOPPY_DISKETTE, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, IO_SD_SYS_ALL_ADM_ALL_WORLD_E_RES_E, IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE_RES_RE, IopCreateSecurityDescriptorPerType(), _ACCESS_ALLOWED_ACE::Mask, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlCreateSecurityDescriptor(), RtlEqualSid(), RtlGetAce(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SePublicDefaultUnrestrictedDacl, SeWorldSid, _ACCESS_ALLOWED_ACE::SidStart, STATUS_SUCCESS, and TRUE.
Referenced by IoCreateDevice().
NTSTATUS IopCreateRegistryKeyEx (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess, IN ULONG CreateOptions, OUT PULONG Disposition OPTIONAL)
Referenced by IopStoreSystemPartitionInformation(), and IoSetSystemPartition().
VOID IopDecrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10711 of file internal.c.
References FALSE, and IopDecrementDeviceObjectRef().
VOID IopDestroyDeviceNode (PDEVICE_NODE DeviceNode)
Referenced by IopDeleteDevice().
NTSTATUS IopDriverLoadingFailed (IN HANDLE KeyHandle OPTIONAL, IN PUNICODE_STRING KeyName OPTIONAL)
Referenced by IopInitializeBuiltinDriver(), and IopLoadDriver().
NTSTATUS IopGetDriverNameFromKeyNode (IN HANDLE KeyHandle, OUT PUNICODE_STRING DriverName)
Definition at line 2127 of file internal.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, ExAllocatePool, ExFreePool(), FileSystemType, IopGetRegistryValue(), KeyBasicInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _KEY_BASIC_INFORMATION::Name, _KEY_BASIC_INFORMATION::NameLength, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, RecognizerType, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), STATUS_ILL_FORMED_SERVICE_ENTRY, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and ZwQueryKey().
Referenced by IopLoadDriver(), and IopUnloadDriver().
NTSTATUS IopGetRegistryKeyInformation (IN HANDLE KeyHandle, OUT PKEY_FULL_INFORMATION * Information)
Definition at line 2522 of file internal.c.
References ExAllocatePool, ExFreePool(), KeyFullInformation, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and ZwQueryKey().
NTSTATUS IopGetRegistryValue (IN HANDLE KeyHandle, IN PWSTR ValueName, OUT PKEY_VALUE_FULL_INFORMATION * Information)
Definition at line 2606 of file internal.c.
References ALIGN_POINTER_OFFSET, ASSERT, ExAllocatePool, ExFreePool(), KeyValueFullInformation, NonPagedPool, NT_SUCCESS, PAGED_CODE, RtlInitUnicodeString(), STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, wcslen(), and ZwQueryValueKey().
Referenced by IopBuildFullDriverPath(), IopCopyBootLogRegistryToFile(), IopGetDriverNameFromKeyNode(), IopGetRegistryValues(), and IopLoadDriver().
VOID IopIncrementDeviceObjectHandleCount (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10702 of file internal.c.
References IopInterlockedIncrementUlong(), and LockQueueIoDatabaseLock.
BOOLEAN IopInitializeBootDrivers (IN PLOADER_PARAMETER_BLOCK LoaderBlock, OUT PDRIVER_OBJECT * PreviousDriver)
Referenced by IoInitSystem().
NTSTATUS IopInitializeBuiltinDriver (IN PUNICODE_STRING DriverName, IN PUNICODE_STRING RegistryPath, IN PDRIVER_INITIALIZE DriverInitializeRoutine, IN PKLDR_DATA_TABLE_ENTRY TableEntry, IN BOOLEAN IsFilter, OUT PDRIVER_OBJECT * DriverObject)
NTSTATUS IopInitializePlugPlayServices (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN ULONG Phase)
Referenced by IoInitSystem().
BOOLEAN IopInitializeSystemDrivers (VOID)
Referenced by IoInitSystem().
NTSTATUS IopInvalidateVolumesForDevice (IN PDEVICE_OBJECT DeviceObject)
Definition at line 5164 of file internal.c.
References CONTAINING_RECORD, DEVICE_OBJECT, ExAcquireResourceSharedLite(), except, EXCEPTION_EXECUTE_HANDLER, Executive, ExReleaseResourceLite(), FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_DISK, FILE_DEVICE_VIRTUAL_DISK, _LIST_ENTRY::Flink, FSCTL_INVALIDATE_VOLUMES, _IO_STATUS_BLOCK::Information, IO_NO_INCREMENT, IoBuildDeviceIoControlRequest(), IoCallDriver(), IoCreateStreamFileObjectLite(), IoFileObjectType, IoGetNextIrpStackLocation, IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopTapeFileSystemQueueHead, IRP_MJ_FILE_SYSTEM_CONTROL, KeClearEvent(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeInitializeEvent(), KeLeaveCriticalRegionThread(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, ObOpenObjectByPointer(), PAGED_CODE, PIRP, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_NOT_IMPLEMENTED, STATUS_PENDING, STATUS_SUCCESS, TRUE, VOID, _FILE_OBJECT::Vpb, and ZwClose().
NTSTATUS IopInvalidDeviceRequest (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 3227 of file internal.c.
References IO_NO_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IRP_MJ_POWER, PoStartNextPowerIrp(), STATUS_INVALID_DEVICE_REQUEST, and UNREFERENCED_PARAMETER.
Referenced by IoCreateDriver(), and IopLoadDriver().
BOOLEAN IopIsLegacyDriver (IN PDRIVER_OBJECT DriverObject)
Referenced by IopLoadDriver(), and IopUnloadDriver().
BOOLEAN IopIsRemoteBootCard (IN PIO_RESOURCE_REQUIREMENTS_LIST ResourceRequirements, IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PWCHAR HwIds)
NTSTATUS IopLoadDriver (IN HANDLE KeyHandle, IN BOOLEAN CheckForSafeBoot, IN BOOLEAN IsFilter, OUT NTSTATUS * DriverEntryStatus)
Definition at line 3689 of file internal.c.
References _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _UNICODE_STRING::Buffer, CmBootLastKnownGood(), CmRegistryMachineHardwareDescriptionSystemName, CONTAINING_RECORD, _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DbgPrint(), _IMAGE_OPTIONAL_HEADER::DllCharacteristics, _DRIVER_OBJECT::DriverExtension, _DRIVER_OBJECT::DriverInit, _DRIVER_OBJECT::DriverName, _DRIVER_EXTENSION::DriverObject, _DRIVER_OBJECT::DriverSection, _DRIVER_OBJECT::DriverSize, _DRIVER_OBJECT::DriverStart, _DRIVER_OBJECT::DriverUnload, DRVO_LEGACY_DRIVER, DRVO_UNLOAD_INVOKED, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAllocatePool, ExFreePool(), ExReleaseResourceLite(), FALSE, FIELD_OFFSET, FILE_READ_DATA, _DRIVER_OBJECT::Flags, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _DRIVER_OBJECT::HardwareDatabase, HEADLESS_LOG_LOAD_FAILED, HEADLESS_LOG_LOAD_SUCCESSFUL, HEADLESS_LOG_LOADING_FILENAME, HeadlessKernelAddLogEntry(), IMAGE_DLLCHARACTERISTICS_WDM_DRIVER, InitializeObjectAttributes, InitSafeBootMode, IO_TYPE_DRIVER, IoDriverObjectType, IopBootLog(), IopBuildFullDriverPath(), IopDriverLoadingFailed(), IopDriverLoadResource, IopGetDriverNameFromKeyNode(), IopGetRegistryValue(), IopInvalidDeviceRequest(), IopIsLegacyDriver(), IopPnpDriverStarted(), IopPrepareDriverLoading(), IopReadyDeviceObjects(), IopResurrectDriver(), IopSafebootDriverLoad(), IRP_MJ_MAXIMUM_FUNCTION, KeGetPreviousMode, KeQuerySystemTime(), KernelMode, KeyBasicInformation, KeyValuePartialInformation, _UNICODE_STRING::Length, _DRIVER_OBJECT::MajorFunction, _UNICODE_STRING::MaximumLength, MmFreeDriverInitialization(), MmLoadSystemImage(), MmUnloadSystemImage(), _OBJECT_NAME_INFORMATION::Name, _KEY_BASIC_INFORMATION::Name, _KEY_BASIC_INFORMATION::NameLength, NonPagedPool, NT_SUCCESS, NtClose(), NtQueryKey(), NtQueryObject(), NtQueryValueKey(), NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_PERMANENT, ObjectNameInformation, ObMakeTemporaryObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_SIZE, PAGED_CODE, PagedPool, PsLoadedModuleList, PsLoadedModuleResource, _LARGE_INTEGER::QuadPart, RtlAppendUnicodeToString(), RtlCopyMemory, RtlEqualUnicodeString(), RtlImageNtHeader(), RtlInitUnicodeString(), RtlZeroMemory, _DRIVER_EXTENSION::ServiceKeyName, _DRIVER_OBJECT::Size, _IMAGE_OPTIONAL_HEADER::SizeOfImage, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_DRIVER_BLOCKED, STATUS_DRIVER_BLOCKED_CRITICAL, STATUS_DRIVER_FAILED_PRIOR_UNLOAD, STATUS_FAILED_DRIVER_ENTRY, STATUS_ILL_FORMED_SERVICE_ENTRY, STATUS_IMAGE_ALREADY_LOADED, STATUS_INCOMPATIBLE_DRIVER_BLOCKED, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PLUGPLAY_NO_DEVICE, STATUS_SUCCESS, TRUE, _DRIVER_OBJECT::Type, and UNICODE_NULL.
Referenced by IopLoadUnloadDriver().
BOOLEAN IopMarkBootPartition (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 2743 of file ioinit.c.
References _FILE_OBJECT::DeviceObject, DO_SYSTEM_BOOT_PARTITION, FALSE, FILE_NON_DIRECTORY_FILE, FILE_READ_ATTRIBUTES, FILE_READ_ONLY_DEVICE, FILE_REMOVABLE_MEDIA, INACCESSIBLE_BOOT_DEVICE, INIT_WINPEMODE_READONLY_MEDIA, INIT_WINPEMODE_REMOVABLE_MEDIA, InitializeObjectAttributes, InitIsWinPEMode, InitWinPEModeType, IoFileObjectType, IopErrorLogObject, KeBugCheckEx(), KernelMode, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObject, ObReferenceObjectByHandle, RtlAnsiStringToUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), sprintf(), TRUE, and ZwOpenFile().
VOID IopMarkHalDeviceNode (VOID)
Referenced by IoInitSystem().
NTSTATUS IopOpenRegistryKeyEx (OUT PHANDLE Handle, IN HANDLE BaseHandle OPTIONAL, IN PUNICODE_STRING KeyName, IN ACCESS_MASK DesiredAccess)
Referenced by IopInitializeBuiltinDriver(), IopStoreSystemPartitionInformation(), and IoSetSystemPartition().
NTSTATUS IopPnpDriverStarted (IN PDRIVER_OBJECT DriverObject, IN HANDLE KeyHandle, IN PUNICODE_STRING ServiceName)
Referenced by IopLoadDriver().
NTSTATUS IopPrepareDriverLoading (IN PUNICODE_STRING KeyName, IN HANDLE KeyHandle, IN PVOID ImageBase, IN BOOLEAN IsFilter)
Referenced by IopInitializeBuiltinDriver(), and IopLoadDriver().
VOID FORCEINLINE IopQueueThreadIrp (IN PIRP Irp)
Definition at line 172 of file iopcmn.h.
References InsertHeadList(), _ETHREAD::IrpList, KeEnterGuardedRegionThread(), KeLeaveGuardedRegionThread(), and _ETHREAD::Tcb.
Referenced by IoBuildDeviceIoControlRequest(), IoBuildSynchronousFsdRequest(), IoCancelFileOpen(), IoEnqueueIrp(), IopCloseFile(), IopDeleteFile(), IopGetFileInformation(), IopGetSetSecurityObject(), IopParseDevice(), IopQueryXxxInformation(), IopSynchronousServiceTail(), IoQueueThreadIrp(), IoSetInformation(), NtQueryInformationFile(), and NtSetInformationFile().
PDRIVER_OBJECT IopReferenceDriverObjectByName (IN PUNICODE_STRING DriverName)
Definition at line 10214 of file internal.c.
References FILE_READ_ATTRIBUTES, InitializeObjectAttributes, IoDriverObjectType, KernelMode, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObOpenObjectByName(), and ObReferenceObjectByHandle.
BOOLEAN IopSafebootDriverLoad (PUNICODE_STRING DriverId)
Definition at line 9318 of file internal.c.
References _UNICODE_STRING::Buffer, CmRegistryMachineSystemCurrentControlSetControlSafeBoot, ExAllocatePool, ExFreePool(), FALSE, InitSafeBootMode, IopOpenRegistryKey(), KdPrint, KernelMode, KEY_ALL_ACCESS, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCloseHandle(), PagedPool, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyUnicodeString(), RtlInitUnicodeString(), SAFEBOOT_DSREPAIR, SAFEBOOT_MINIMAL, SAFEBOOT_MINIMAL_STR_W, SAFEBOOT_NETWORK, SAFEBOOT_NETWORK_STR_W, and TRUE.
Referenced by IopLoadDriver().
NTSTATUS IopSetupRemoteBootCard (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN HANDLE UniqueIdHandle, IN PUNICODE_STRING UnicodeDeviceInstance)
NTSTATUS IopStartNetworkForRemoteBoot (PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by IoInitSystem().
NTSTATUS IopStartTcpIpForRemoteBoot (PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS IopSynchronousCall (IN PDEVICE_OBJECT DeviceObject, IN PIO_STACK_LOCATION TopStackLocation, OUT PULONG_PTR Information)
NTSTATUS IopUnloadDriver (IN PUNICODE_STRING DriverServiceName, IN BOOLEAN InvokedByPnpMgr)
Definition at line 255 of file loadunld.c.
References _UNICODE_STRING::Buffer, DelayedWorkQueue, _LOAD_PACKET::DriverObject, _DRIVER_OBJECT::DriverSection, _DRIVER_OBJECT::DriverUnload, _LOAD_PACKET::Event, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), FALSE, FILE_READ_DATA, InitializeObjectAttributes, IoDriverObjectType, IopCheckUnloadDriver(), IopGetDriverNameFromKeyNode(), IopIsLegacyDriver(), IopLoadUnloadDriver(), IopOpenRegistryKey(), KeGetPreviousMode, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), KEY_READ, _UNICODE_STRING::Length, NotificationEvent, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObMakeTemporaryObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, PsGetCurrentProcess(), PsInitialSystemProcess, RtlCopyMemory, SeLoadDriverPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, VOID, _LOAD_PACKET::WorkQueueItem, and ZwUnloadDriver().
Referenced by NtUnloadDriver().
NTSTATUS PpDriverObjectDereferenceComplete (IN PDRIVER_OBJECT DriverObject)
Referenced by IopDeleteDriver().
Variable Documentation
POBJECT_TYPE IoDeviceObjectType
Definition at line 240 of file iodata.c.
POBJECT_TYPE IoDriverObjectType
Definition at line 241 of file iodata.c.
Referenced by IoCreateDriver(), IopCreateObjectTypes(), IopGetDriverPathInformation(), IopInitializeAttributesAndCreateObject(), IopInitializeBuiltinDriver(), IopLoadDriver(), IopReferenceDriverObjectByName(), and IopUnloadDriver().
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.
PVOID IopLoaderBlock
Definition at line 746 of file iodata.c.
Referenced by IoGetBootDiskInformation(), and IoInitSystem().