Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/iosup.c File Reference
iosup.c File Reference
#include "mi.h"
Data Structures
struct _PTE_TRACKER
struct _SYSPTES_HEADER
Macros
#define COPY_STACK_SIZE 512
#define MI_INSTRUMENT_PROBE_RAISES(i)
#define MI_LARGE_PAGE_VA_SPACE ((ULONG64)8 * 1024 * 1024 * 1024)
#define MI_PROBE_RAISE_SIZE 34
#define SPECIAL_POOL_ADDRESS(p) (((p) >= MmSpecialPoolStart) && ((p) < MmSpecialPoolEnd))
Typedefs
typedef enum _MI_LOCK_USED_FOR_PROBE MI_LOCK_USED_FOR_PROBE
typedef enum _MI_LOCK_USED_FOR_PROBE * PMI_LOCK_USED_FOR_PROBE
typedef struct _PTE_TRACKER * PPTE_TRACKER
typedef struct _SYSPTES_HEADER * PSYSPTES_HEADER
typedef struct _PTE_TRACKER PTE_TRACKER
typedef struct _SYSPTES_HEADER SYSPTES_HEADER
Enumerations
enum _MI_LOCK_USED_FOR_PROBE { LOCK_TYPE_NONE = 0, LOCK_TYPE_AWE = 1, LOCK_TYPE_WS = 2, LOCK_TYPE_PFN = 3 }
Functions
__bcount (PVOIDMmAllocateMappingAddress(__in SIZE_T NumberOfBytes)
__bcount (PVOIDMmAllocateContiguousMemorySpecifyCache(__in SIZE_T NumberOfBytes)
__bcount (PVOIDMmAllocateContiguousMemory(__in SIZE_T NumberOfBytes)
__out_bcount (NumberOfBytes)
VOID MiAddMdlTracker (IN PMDL MemoryDescriptorList, IN PVOID CallingAddress, IN PVOID CallersCaller, IN PFN_NUMBER NumberOfPagesToLock, IN ULONG Who)
PVOID MiAllocateContiguousMemory (IN SIZE_T NumberOfBytes, IN PFN_NUMBER LowestAcceptablePfn, IN PFN_NUMBER HighestAcceptablePfn, IN PFN_NUMBER BoundaryPfn, IN MEMORY_CACHING_TYPE CacheType, PVOID CallingAddress)
PMDL MiAllocatePagesForMdl (IN PHYSICAL_ADDRESS LowAddress, IN PHYSICAL_ADDRESS HighAddress, IN PHYSICAL_ADDRESS SkipBytes, IN SIZE_T TotalBytes, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute, IN ULONG Flags)
PVOID MiCheckForContiguousMemory (IN PVOID BaseAddress, IN PFN_NUMBER BaseAddressPages, IN PFN_NUMBER SizeInPages, IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute)
LOGICAL MiCheckSystemPteProtection (IN ULONG_PTR StoreInstruction, IN PVOID VirtualAddress)
PVOID MiCreatePhysicalVadRoot (IN PEPROCESS Process, IN LOGICAL WsHeld)
VOID MiDecrementReferenceCountForAwePage (IN PMMPFN Pfn1, IN LOGICAL PfnHeld)
VOID MiDeferredUnlockPages (ULONG Flags)
NTKERNELAPI LOGICAL MiDereferenceIoSpace (IN OUT PMDL MemoryDescriptorList)
LOGICAL MiFreeMdlTracker (IN OUT PMDL MemoryDescriptorList, IN PFN_NUMBER NumberOfPages)
PVOID MiGetHighestPteConsumer (OUT PULONG_PTR NumberOfPtes)
VOID MiInitializeIoTrackers (VOID)
VOID MiInitializeLargePageSupport (VOID)
MI_PFN_CACHE_ATTRIBUTE MiInsertIoSpaceMap (IN PVOID BaseVa, IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute)
VOID MiInsertPteTracker (IN PMDL MemoryDescriptorList, IN ULONG Flags, IN LOGICAL IoMapping, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute, IN PVOID MyCaller, IN PVOID MyCallersCaller)
LOGICAL MiIsProbeActive (IN PMMPTE InputPte, IN PFN_NUMBER InputPages)
VOID MiLockCode (IN PMMPTE FirstPte, IN PMMPTE LastPte, IN ULONG LockType)
PKLDR_DATA_TABLE_ENTRY MiLookupDataTableEntry (IN PVOID AddressWithinSection, IN ULONG ResourceHeld)
PVOID MiMapLockedPagesInUserSpace (IN PMDL MemoryDescriptorList, IN PVOID StartingVa, IN MEMORY_CACHING_TYPE CacheType, IN PVOID BaseVa)
PVOID MiMapSinglePage (IN PVOID VirtualAddress OPTIONAL, IN PFN_NUMBER PageFrameIndex, IN MEMORY_CACHING_TYPE CacheType, IN MM_PAGE_PRIORITY Priority)
PVOID MiMapWithLargePages (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN ULONG Protection, IN MEMORY_CACHING_TYPE CacheType)
VOID MiPhysicalViewAdjuster (IN PEPROCESS Process, IN PMMVAD OldVad, IN PMMVAD NewVad)
VOID MiPhysicalViewRemover (IN PEPROCESS Process, IN PMMVAD Vad)
LOGICAL MiReferenceIoSpace (IN PMDL MemoryDescriptorList, IN PPFN_NUMBER Page)
LOGICAL MiReferenceIoSpace (IN OUT PMDL MemoryDescriptorList, IN PPFN_NUMBER Page)
VOID MiRemoveIoSpaceMap (IN PVOID BaseVa, IN PFN_NUMBER NumberOfPages)
VOID MiRemovePteTracker (IN PMDL MemoryDescriptorList OPTIONAL, IN PVOID VirtualAddress, IN PFN_NUMBER NumberOfPtes)
VOID MiUnmapLargePages (IN PVOID BaseAddress, IN SIZE_T NumberOfBytes)
VOID MiUnmapLockedPagesInUserSpace (IN PVOID BaseAddress, IN PMDL MemoryDescriptorList)
VOID MiUnmapSinglePage (IN PVOID VirtualAddress)
LOGICAL MiUpdateMdlTracker (IN PMDL MemoryDescriptorList, IN ULONG AdvancePages)
VOID MiZeroAwePageWorker (IN PVOID Context)
VOID MiZeroInParallel (IN PCOLORED_PAGE_INFO ColoredPageInfoBase)
NTKERNELAPI NTSTATUS MmAdvanceMdl (__inout PMDL Mdl, __in ULONG NumberOfBytes)
PVOID MmAllocateIndependentPages (IN SIZE_T NumberOfBytes, IN ULONG Node)
PMDL MmAllocatePagesForMdl (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes)
PMDL MmAllocatePagesForMdlEx (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes, __in MEMORY_CACHING_TYPE CacheType, __in ULONG Flags)
LOGICAL MmAreMdlPagesLocked (IN PMDL MemoryDescriptorList)
VOID MmBuildMdlForNonPagedPool (__inout PMDL MemoryDescriptorList)
PMDL MmCreateMdl (__in_opt PMDL MemoryDescriptorList, __in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
VOID MmEnablePAT (VOID)
VOID MmFreeContiguousMemory (__in PVOID BaseAddress)
VOID MmFreeContiguousMemorySpecifyCache (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in MEMORY_CACHING_TYPE CacheType)
VOID MmFreeIndependentPages (IN PVOID VirtualAddress, IN SIZE_T NumberOfBytes)
VOID MmFreeMappingAddress (__in PVOID BaseAddress, __in ULONG PoolTag)
VOID MmFreeNonCachedMemory (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
VOID MmFreePagesFromMdl (__in PMDL MemoryDescriptorList)
NTKERNELAPI ULONG MmGatherMemoryForHibernate (IN PMDL Mdl, IN BOOLEAN Wait)
PHYSICAL_ADDRESS MmGetPhysicalAddress (__in PVOID BaseAddress)
NTSTATUS MmGetSectionRange (IN PVOID AddressWithinSection, OUT PVOID *StartingSectionAddress, OUT PULONG SizeofSection)
PVOID MmGetVirtualForPhysical (__in PHYSICAL_ADDRESS PhysicalAddress)
LOGICAL MmIsIoSpaceActive (__in PHYSICAL_ADDRESS StartAddress, __in SIZE_T NumberOfBytes)
BOOLEAN MmIsRecursiveIoFault (VOID)
LOGICAL MmIsSystemAddressLocked (IN PVOID VirtualAddress)
VOID MmLockPagableSectionByHandle (__in PVOID ImageSectionHandle)
PVOID MmLockPageableDataSection (__in PVOID AddressWithinSection)
VOID MmLockPageableSectionByHandle (__in PVOID ImageSectionHandle)
VOID MmLockPagedPool (IN PVOID Address, IN SIZE_T SizeInBytes)
PVOID MmMapLockedPages (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode)
PVOID MmMapLockedPagesWithReservedMapping (__in PVOID MappingAddress, __in ULONG PoolTag, __in PMDL MemoryDescriptorList, __in MEMORY_CACHING_TYPE CacheType)
VOID MmMapMemoryDumpMdl (__inout PMDL MemoryDumpMdl)
NTSTATUS MmMapUserAddressesToPage (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in PVOID PageAddress)
VOID MmProbeAndLockPages (__inout PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
NTKERNELAPI VOID MmProbeAndLockProcessPages (__inout PMDL MemoryDescriptorList, __in PEPROCESS Process, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
NTKERNELAPI VOID MmProbeAndLockSelectedPages (__inout PMDL MemoryDescriptorList, __in PFILE_SEGMENT_ELEMENT PagedSegmentArray, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
NTKERNELAPI NTSTATUS MmProtectMdlSystemAddress (__in PMDL MemoryDescriptorList, __in ULONG NewProtect)
VOID MmReleaseDumpAddresses (IN PFN_NUMBER NumberOfPages)
NTKERNELAPI VOID MmReturnMemoryForHibernate (IN PMDL Mdl)
BOOLEAN MmSetAddressRangeModified (__in_bcount(Length) PVOID Address, __in SIZE_T Length)
NTSTATUS MmSetBankedSection (__in HANDLE ProcessHandle, __in_bcount(BankLength) PVOID VirtualAddress, __in ULONG BankLength, __in BOOLEAN ReadWriteBank, __in PBANKED_SECTION_ROUTINE BankRoutine, __in PVOID Context)
BOOLEAN MmSetPageProtection (__in_bcount(NumberOfBytes) PVOID VirtualAddress, __in SIZE_T NumberOfBytes, __in ULONG NewProtect)
SIZE_T MmSizeOfMdl (__in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
VOID MmUnlockPagableImageSection (__in PVOID ImageSectionHandle)
VOID MmUnlockPageableImageSection (__in PVOID ImageSectionHandle)
NTKERNELAPI VOID MmUnlockPagedPool (IN PVOID Address, IN SIZE_T SizeInBytes)
VOID MmUnlockPages (__inout PMDL MemoryDescriptorList)
VOID MmUnmapIoSpace (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
VOID MmUnmapReservedMapping (IN PVOID BaseAddress, IN ULONG PoolTag, IN PMDL MemoryDescriptorList)
VOID MmUnmapVideoDisplay (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
LOGICAL MmUpdateMdlTracker (IN PMDL MemoryDescriptorList, IN PVOID CallingAddress, IN PVOID CallersCaller)
Variables
LONG MiActiveIoCounter
ULONG MiCacheOverride [4]
PCHAR MiCacheStrings []
SLIST_HEADER MiDeadPteTrackerSListHead
PFN_NUMBER MiEndOfInitialPoolFrame
PMMPTE MiInitialSystemPageDirectory
ULONG MiMdlsAdjusted = FALSE
ULONG MiNonCachedCollisions
ULONG MiProbeRaises [MI_PROBE_RAISE_SIZE]
SYSPTES_HEADER MiPteHeader
KSPIN_LOCK MiPteTrackerLock
PFN_NUMBER MiStartOfInitialPoolFrame
KSPIN_LOCK MiTrackIoLock
BOOLEAN MiTrackPtesAborted = FALSE
BOOLEAN MiWriteCombiningPtes = FALSE
KEVENT MmCollidedLockEvent
LONG MmCollidedLockWait
LIST_ENTRY MmIoHeader
KSPIN_LOCK MmIoTrackerLock
SINGLE_LIST_ENTRY MmLockedIoPagesHead
PFN_NUMBER MmMdlPagesAllocated
ULONG MmReferenceCountCheck = MAXUSHORT / 2
LONG MmTotalSystemDriverPages
ULONG MmTrackPtes = 0
POOL_DESCRIPTOR NonPagedPoolDescriptor
Macro Definition Documentation
#define COPY_STACK_SIZE 512
Definition at line 1809 of file iosup.c.
Referenced by MmProbeAndLockSelectedPages().
#define MI_INSTRUMENT_PROBE_RAISES (i)
Value:
ASSERT (i < MI_PROBE_RAISE_SIZE);   \
        MiProbeRaises[i] += 1;
Definition at line 234 of file iosup.c.
Referenced by MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
#define MI_LARGE_PAGE_VA_SPACE ((ULONG64)8 * 1024 * 1024 * 1024)
Definition at line 7800 of file iosup.c.
Referenced by MiInitializeLargePageSupport().
#define MI_PROBE_RAISE_SIZE 34
Definition at line 230 of file iosup.c.
#define SPECIAL_POOL_ADDRESS (p) (((p) >= MmSpecialPoolStart) && ((p) < MmSpecialPoolEnd))
Definition at line 9390 of file iosup.c.
Referenced by MmFreeContiguousMemory().
Typedef Documentation
typedef enum _MI_LOCK_USED_FOR_PROBE MI_LOCK_USED_FOR_PROBE
typedef enum _MI_LOCK_USED_FOR_PROBE * PMI_LOCK_USED_FOR_PROBE
typedef struct _PTE_TRACKER * PPTE_TRACKER
typedef struct _SYSPTES_HEADER * PSYSPTES_HEADER
typedef struct _PTE_TRACKER PTE_TRACKER
typedef struct _SYSPTES_HEADER SYSPTES_HEADER
Enumeration Type Documentation
enum _MI_LOCK_USED_FOR_PROBE
Enumerator
LOCK_TYPE_NONE
LOCK_TYPE_AWE
LOCK_TYPE_WS
LOCK_TYPE_PFN
Definition at line 247 of file iosup.c.
Function Documentation
__bcount (PVOIDMmAllocateMappingAddress (__in SIZE_T NumberOfBytes)
Definition at line 5341 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, FALSE, KeBugCheckEx(), KeGetCurrentIrql(), MiCached, MiGetVirtualAddressMappedByPte, MiInsertPteTracker(), MiReserveSystemPtes(), MiZeroMemoryPte, MmTrackPtes, NULL, PAGE_SIZE, PASSIVE_LEVEL, PoolTag, RtlGetCallersAddress(), SYSTEM_PTE_MISUSE, and SystemPteSpace.
__bcount (PVOIDMmAllocateContiguousMemorySpecifyCache (__in SIZE_T NumberOfBytes)
Definition at line 9214 of file iosup.c.
References ASSERT, BYTE_OFFSET, MiAllocateContiguousMemory(), MmHighestPossiblePhysicalPage, NULL, PAGE_SHIFT, and RtlGetCallersAddress().
__bcount (PVOIDMmAllocateContiguousMemory (__in SIZE_T NumberOfBytes)
Definition at line 9321 of file iosup.c.
References MiAllocateContiguousMemory(), MmCached, MmHighestPossiblePhysicalPage, PAGE_SHIFT, and RtlGetCallersAddress().
__out_bcount (NumberOfBytes)
Definition at line 8529 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, BYTE_OFFSET, _MDL::ByteCount, _MDL::ByteOffset, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE::Hard, HIGH_LEVEL, KeSetPhysicalCacheTypeRange(), LOCK_PFN2, _MDL::MappedSystemVa, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DISABLE_CACHING, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiGetVirtualAddressMappedByPte, MiInsertIoSpaceMap(), MiInsertPteTracker(), MiMapWithLargePages(), MiNonCached, MiNonCachedCollisions, MiNotMapped, MiReleaseSystemPtes(), MiRemoveIoSpaceMap(), MiReserveSystemPtes(), MiWriteCombined, MiWriteCombiningPtes, MM_EXECUTE_READWRITE, MM_MINIMUM_VA_FOR_LARGE_PAGE, MmCached, MmMaximumCacheType, MmTrackPtes, MmWriteCombined, NT_SUCCESS, NULL, PAGE_ALIGN, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::Rom, RtlGetCallersAddress(), _MDL::StartVa, Status, SystemPteSpace, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, ValidKernelPte, and X64K.
VOID MiAddMdlTracker (IN PMDL MemoryDescriptorList, IN PVOID CallingAddress, IN PVOID CallersCaller, IN PFN_NUMBER NumberOfPagesToLock, IN ULONG Who)
Definition at line 1383 of file iosup.c.
References ASSERT, _LOCK_TRACKER::CallersCaller, _LOCK_TRACKER::CallingAddress, CONTAINING_RECORD, _LOCK_TRACKER::Count, _LOCK_HEADER::Count, ExAllocatePoolWithTag, FALSE, _LIST_ENTRY::Flink, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeBugCheckEx(), KeReleaseInStackQueuedSpinLock(), _LOCK_TRACKER::Length, _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, LOCKED_PAGES_TRACKER_CORRUPTION, _EPROCESS::LockedPagesList, _LOCK_TRACKER::Mdl, MmTrackLockedPages, NonPagedPool, NULL, _LOCK_TRACKER::Offset, _LOCK_TRACKER::Page, _LOCK_TRACKER::Process, PsInitialSystemProcess, _LOCK_TRACKER::StartVa, TRUE, _LOCK_HEADER::Valid, and _LOCK_TRACKER::Who.
Referenced by MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
PVOID MiAllocateContiguousMemory (IN SIZE_T NumberOfBytes, IN PFN_NUMBER LowestAcceptablePfn, IN PFN_NUMBER HighestAcceptablePfn, IN PFN_NUMBER BoundaryPfn, IN MEMORY_CACHING_TYPE CacheType, PVOID CallingAddress)
Definition at line 9074 of file iosup.c.
References APC_LEVEL, ASSERT, BYTES_TO_PAGES, ExAllocatePoolWithTag, ExFreePool(), KeGetCurrentIrql(), MI_TRANSLATE_CACHETYPE(), MiAllocateLowMemory(), MiCached, MiCheckForContiguousMemory(), MiFindContiguousMemory(), MiNoLowMemory, NonPagedPoolCacheAligned, and NULL.
Referenced by __bcount().
PMDL MiAllocatePagesForMdl (IN PHYSICAL_ADDRESS LowAddress, IN PHYSICAL_ADDRESS HighAddress, IN PHYSICAL_ADDRESS SkipBytes, IN SIZE_T TotalBytes, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute, IN ULONG Flags)
Definition at line 10322 of file iosup.c.
References ActiveAndValid, ADDRESS_AND_SIZE_TO_SPAN_PAGES, APC_LEVEL, ASSERT, _MMPFNLIST::Blink, _MMPFN::Blink, _MMCOLOR_TABLES::Blink, BYTE_OFFSET, _MDL::ByteCount, _MMPFNENTRY::CacheAttribute, _MMCOLOR_TABLES::Count, DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), ExPageLockHandle, FALSE, _MMPFNLIST::Flink, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, InterlockedExchangeAddSizeT, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentNode, KeGetCurrentPrcb(), KeGetCurrentThread(), KeLeaveGuardedRegionThread(), KeNumberNodes, LOCK_PFN, _MMPTE::Long, MAXULONG, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_ALLOCATION_IS_AWE, MI_DECREMENT_RESIDENT_AVAILABLE, MI_DEFER_PFN_HELD, MI_FLUSH_ENTIRE_TB_FOR_ATTRIBUTE_CHANGE, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_GET_COLOR_FROM_LIST_ENTRY, MI_INCREMENT_RESIDENT_AVAILABLE, MI_LOCK_DYNAMIC_MEMORY_SHARED, MI_MAGIC_AWE_PTEFRAME, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_PFN_PRIORITIES, MI_SET_PFN_DELETED, MI_SYSTEM_PAGE_COLOR, MI_UNLOCK_DYNAMIC_MEMORY_SHARED, MiCached, MiChargeCommitment(), MiDeferredUnlockPages(), MiNonCached, MiNotMapped, MiRestoreTransitionPte(), MiReturnCommitment, MiUnlinkFreeOrZeroedPage(), MiUnlinkPageFromList(), MiZeroInParallel(), MM_ALLOCATE_FROM_LOCAL_NODE_ONLY, MM_DBG_COMMIT_MDL_PAGES, MM_DBG_COMMIT_RETURN_AWE_EXCESS, MM_DEMAND_ZERO_WRITE_PTE, MM_DONT_ZERO_ALLOCATION, MM_EMPTY_LIST, MM_HIGH_LIMIT, MM_RESAVAIL_ALLOCATE_FOR_MDL, MM_RESAVAIL_FREE_FOR_MDL_EXCESS, MM_TRACK_COMMIT, MmAvailablePages, MmCreateMdl(), MmFreePagesByColor, MmHighestPhysicalPage, MmHighestPossiblePhysicalPage, MmLockPageableSectionByHandle(), MmMdlPagesAllocated, MmNumberOfPhysicalPages, MmPageLocationList, MmSecondaryColorMask, MmSecondaryColors, MmStandbyPageListByPriority, MmUnlockPageableImageSection(), _MMPFN::MustBeCached, NonPagedPool, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _KPRCB::PageColor, _MMPFNENTRY::PageColor, _MMPFNENTRY::PageLocation, _COLORED_PAGE_INFO::PagesLeftToScan, _COLORED_PAGE_INFO::PagesQueued, _COLORED_PAGE_INFO::PfnAllocation, _MDL::Process, PsGetCurrentProcess(), _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, RtlCopyMemory, _MMPFN::ShareCount, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPFN::VerifierAllocation, and ZeroedPageList.
Referenced by __out_bcount(), MmAllocatePagesForMdl(), MmAllocatePagesForMdlEx(), and NtAllocateUserPhysicalPages().
PVOID MiCheckForContiguousMemory (IN PVOID BaseAddress, IN PFN_NUMBER BaseAddressPages, IN PFN_NUMBER SizeInPages, IN PFN_NUMBER LowestPfn, IN PFN_NUMBER HighestPfn, IN PFN_NUMBER BoundaryPfn, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute)
Definition at line 12627 of file iosup.c.
References ASSERT, _MMPTE::Hard, LOCK_PFN2, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiCached, MiGetPteAddress, MiGetVirtualAddressMappedByPte, NULL, PAGE_SHIFT, _MMPTE::u, UNLOCK_PFN2, and _MMPTE_HARDWARE::Valid.
Referenced by MiAllocateContiguousMemory(), and MiFindContiguousMemoryInPool().
LOGICAL MiCheckSystemPteProtection (IN ULONG_PTR StoreInstruction, IN PVOID VirtualAddress)
Definition at line 6775 of file iosup.c.
References ATTEMPTED_WRITE_TO_READONLY_MEMORY, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, IsListEmpty, KeAcquireSpinLockRaiseToSynch(), KeBugCheckEx(), KeReleaseSpinLock(), _MMPTE::Long, MI_NO_FAULT_FOUND, MiGetPteAddress, MM_READWRITE, MmProtectedPteList, MmProtectedPteLock, _MM_PTE_MAPPING::Protection, _MM_PTE_MAPPING::SystemVa, TRUE, and _MMPTE::u.
Referenced by MmAccessFault().
PVOID MiCreatePhysicalVadRoot (IN PEPROCESS Process, IN LOGICAL WsHeld)
Definition at line 6871 of file iosup.c.
References ASSERT, _MM_AVL_TABLE::BalancedRoot, ExAllocatePoolWithTag, ExFreePool(), FALSE, LOCK_WS, MI_PHYSICAL_VIEW_ROOT_KEY, NonPagedPool, NULL, _MM_AVL_TABLE::NumberGenericTableElements, _MMADDRESS_NODE::Parent, PsGetCurrentThread(), RtlZeroMemory, _MMADDRESS_NODE::u1, and UNLOCK_WS.
Referenced by MiCloneProcessAddressSpace(), MiMapLockedPagesInUserSpace(), MiMapViewOfPhysicalSection(), and NtAllocateVirtualMemory().
VOID MiDecrementReferenceCountForAwePage (IN PMMPFN Pfn1, IN LOGICAL PfnHeld)
Definition at line 2854 of file iosup.c.
References ActiveAndValid, ASSERT, FALSE, InterlockedDecrement16(), InterlockedDecrementSizeT, LOCK_PFN2, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT_TO_INDEX, MiDecrementReferenceCount(), MiReturnCommitment, MM_DBG_COMMIT_RETURN_MDL_PAGES, MM_RESAVAIL_FREE_AWE, MM_TRACK_COMMIT, MmMdlPagesAllocated, PASSIVE_LEVEL, and UNLOCK_PFN2.
Referenced by MiFreeLargePageMemory(), MmAdvanceMdl(), MmFreePagesFromMdl(), and MmUnlockPages().
VOID MiDeferredUnlockPages (ULONG Flags)
Definition at line 3935 of file iosup.c.
References ASSERT, CONTAINING_RECORD, _MMPFN::e1, _MI_PFN_DEREFERENCE_CHUNK::Flags, GET_PAGING_FILE_OFFSET, InterlockedCompareExchangePointer, InterlockedPushListSList(), KeGetCurrentNode, KeNodeBlock, KeNumberNodes, LOCK_PFN2, MDL_WRITE_OPERATION, MI_DEFER_DRAIN_LOCAL_ONLY, MI_DEFER_PFN_HELD, MI_MAX_DEREFERENCE_CHUNK, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiReleaseConfirmedPageFileSpace(), MM_PFN_LOCK_ASSERT, MmPfnDeferredList, MmPfnDereferenceSListHead, NULL, _MI_PFN_DEREFERENCE_CHUNK::NumberOfPages, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MI_PFN_DEREFERENCE_CHUNK::Pfns, _MMPTE_SOFTWARE::Prototype, PSLIST_ENTRY, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, and _MMPFNENTRY::WriteInProgress.
Referenced by MiAllocatePagesForMdl(), MiCleanSection(), MiFindContiguousPages(), MiFindLargePageMemory(), MiFlushSectionInternal(), MiFreePoolPages(), MiPurgeImageSection(), MmFreeContiguousMemory(), MmGatherMemoryForHibernate(), MmUnlockPages(), and MmWorkingSetManager().
NTKERNELAPI LOGICAL MiDereferenceIoSpace (IN OUT PMDL MemoryDescriptorList)
Definition at line 3005 of file iosup.c.
References ExAcquireSpinLock, ExFreePool(), ExReleaseSpinLock, FALSE, _MDL::MappedSystemVa, MiTrackIoLock, _MDL::Next, _SINGLE_LIST_ENTRY::Next, NULL, and TRUE.
Referenced by MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), and MmUnlockPages().
LOGICAL MiFreeMdlTracker (IN OUT PMDL MemoryDescriptorList, IN PFN_NUMBER NumberOfPages)
Definition at line 1520 of file iosup.c.
References ASSERT, CONTAINING_RECORD, _LOCK_TRACKER::Count, _LOCK_HEADER::Count, ExFreePool(), FALSE, _LIST_ENTRY::Flink, KeAcquireInStackQueuedSpinLock(), KeBugCheckEx(), KeReleaseInStackQueuedSpinLock(), _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, LOCKED_PAGES_TRACKER_CORRUPTION, _EPROCESS::LockedPagesList, _LOCK_TRACKER::Mdl, NULL, _EPROCESS::NumberOfLockedPages, _LOCK_TRACKER::Page, PROCESS_HAS_LOCKED_PAGES, PsInitialSystemProcess, RemoveEntryList(), TRUE, and _LOCK_HEADER::Valid.
Referenced by MmUnlockPages().
PVOID MiGetHighestPteConsumer (OUT PULONG_PTR NumberOfPtes)
Definition at line 4653 of file iosup.c.
References _LIST_ENTRY::Blink, _PTE_TRACKER::CallersCaller, _PTE_TRACKER::CallingAddress, CONTAINING_RECORD, _PTE_TRACKER::Count, _KLDR_DATA_TABLE_ENTRY::DllBase, _LIST_ENTRY::Flink, IsListEmpty, _SYSPTES_HEADER::ListHead, _PTE_TRACKER::Matched, MiTrackPtesAborted, MmTrackPtes, NOTHING, NULL, PsLoadedModuleList, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, and TRUE.
Referenced by MiIssueNoPtesBugcheck().
VOID MiInitializeIoTrackers (VOID)
Definition at line 4306 of file iosup.c.
References InitializeListHead(), InitializeSListHead(), KeInitializeSpinLock(), _SYSPTES_HEADER::ListHead, MiPteTrackerLock, MiTrackIoLock, and MmIoTrackerLock.
Referenced by MmInitSystem().
VOID MiInitializeLargePageSupport (VOID)
Definition at line 7810 of file iosup.c.
References ASSERT, FALSE, InitializeListHead(), InsertTailList(), KeInitializeSpinLock(), LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_COLOR_FROM_VA, MI_LARGE_PAGE_VA_SPACE, MI_MAKE_VALID_PTE, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetPpeAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPpe, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiIssueNoPtesBugcheck(), MiLargePageHyperPte, MiRemoveZeroPage(), MiReserveSystemPtes(), MM_DBG_COMMIT_LARGE_VA_PAGES, MM_DEMAND_ZERO_WRITE_PTE, MM_HIGH_LIMIT, MM_READWRITE, MM_TRACK_COMMIT, MM_VA_MAPPED_BY_PPE, MmAvailablePages, MmNonPagedPoolEnd, MmProcessList, NULL, PsGetCurrentProcess(), RtlClearAllBits(), RtlInitializeBitMap(), RtlSetAllBits(), SystemPteSpace, _MMPTE::u, and UNLOCK_PFN.
Referenced by MmInitSystem().
MI_PFN_CACHE_ATTRIBUTE MiInsertIoSpaceMap (IN PVOID BaseVa, IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute)
Definition at line 4793 of file iosup.c.
References ASSERT, _MMIO_TRACKER::BaseVa, _MMIO_TRACKER::CacheAttribute, CONTAINING_RECORD, DbgBreakPoint(), DbgPrintEx(), DISPATCH_LEVEL, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, ExAcquireSpinLock, ExAllocatePoolWithTag, ExReleaseSpinLock, _LIST_ENTRY::Flink, InsertHeadList(), KeGetCurrentIrql(), _MMIO_TRACKER::ListEntry, MI_IO_BACKTRACE_LENGTH, MI_IS_PFN(), MiCacheOverride, MiCacheStrings, MiNotMapped, MmIoTrackerLock, NonPagedPool, NULL, _MMIO_TRACKER::NumberOfPages, PAGE_SHIFT, _MMIO_TRACKER::PageFrameIndex, RtlCaptureStackBackTrace(), RtlZeroMemory, and _MMIO_TRACKER::StackTrace.
Referenced by __out_bcount(), MiAddHalIoMappings(), and MiMapWithLargePages().
VOID MiInsertPteTracker (IN PMDL MemoryDescriptorList, IN ULONG Flags, IN LOGICAL IoMapping, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute, IN PVOID MyCaller, IN PVOID MyCallersCaller)
Definition at line 4321 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _PTE_TRACKER::CacheAttribute, _PTE_TRACKER::CallersCaller, _PTE_TRACKER::CallingAddress, _PTE_TRACKER::Count, _SYSPTES_HEADER::Count, DISPATCH_LEVEL, ExAcquireSpinLock, ExAllocatePoolWithTag, ExFreePool(), ExInterlockedFlushSList(), ExQueryDepthSList, ExReleaseSpinLock, FALSE, InsertHeadList(), InterlockedPopEntrySList(), _PTE_TRACKER::IoMapping, KeGetCurrentIrql(), _PTE_TRACKER::Length, _PTE_TRACKER::ListEntry, _SYSPTES_HEADER::ListHead, _PTE_TRACKER::Matched, _PTE_TRACKER::Mdl, MiPteTrackerLock, MiTrackPtesAborted, NonPagedPool, NULL, _SYSPTES_HEADER::NumberOfEntries, _SYSPTES_HEADER::NumberOfEntriesPeak, _PTE_TRACKER::Offset, _PTE_TRACKER::Page, PAGE_SHIFT, PSLIST_ENTRY, _PTE_TRACKER::StartVa, _PTE_TRACKER::SystemVa, and TRUE.
Referenced by __bcount(), __out_bcount(), and MmMapLockedPagesSpecifyCache().
LOGICAL MiIsProbeActive (IN PMMPTE InputPte, IN PFN_NUMBER InputPages)
Definition at line 3190 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, _MDL::ByteOffset, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _MMPTE::Hard, InterlockedIncrement, MI_GET_PAGE_FRAME_FROM_PTE, MiActiveIoCounter, MiTrackIoLock, MM_EMPTY_LIST, _MDL::Next, _SINGLE_LIST_ENTRY::Next, NULL, _MDL::StartVa, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
VOID MiLockCode (IN PMMPTE FirstPte, IN PMMPTE LastPte, IN ULONG LockType)
Definition at line 13139 of file iosup.c.
References ActiveAndValid, ASSERT, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, _MMPFN::Event, FALSE, _MMWSL::FirstDynamic, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMPTE::Hard, _MMPFN::InPageError, InterlockedDecrement, InterlockedIncrement16(), InterlockedIncrementSizeT, KeDelayExecutionThread(), KernelMode, LOCK_PFN, LOCK_WORKING_SET, _MMWSLENTRY::LockedInWs, _MMPTE::Long, MI_ADD_LOCKED_PAGE_CHARGE(), MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_PTE_IN_WORKING_SET, MI_WRITE_VALID_PTE, MI_ZERO_WSINDEX, MiAllocateWsle(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiLocateWsle(), MiMakeSystemAddressValidPfnSystemWs(), MiReleaseWsle(), MiRemoveWsle(), MiSwapWslEntries(), MiTrimPte(), MiUnlinkPageFromList(), Mm30Milliseconds, MM_BUMP_SESS_COUNTER, MM_DBG_SESSION_NP_LOCK_CODE1, MM_DBG_SESSION_NP_LOCK_CODE2, MM_LOCK_BY_REFCOUNT, MM_RESAVAIL_ALLOCATE_LOCK_CODE1, MM_RESAVAIL_ALLOCATE_LOCK_CODE2, MM_RESAVAIL_ALLOCATE_LOCK_CODE3, MmAvailablePages, MmPagedPoolEnd, MmPagedPoolStart, MmSessionSpace, MmSpecialPoolEnd, MmSpecialPoolStart, MmSystemCacheWorkingSetList, MmSystemCacheWs, MmTotalSystemDriverPages, _MM_SESSION_SPACE::NonPageablePages, NULL, _MMPFN::OriginalPte, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFNENTRY::ReadInProgress, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, _MM_SESSION_SPACE::Vm, _MMSUPPORT::VmWorkingSetList, _MMPFN::WsIndex, _MM_SESSION_SPACE::Wsle, and ZeroPte.
Referenced by MmLockPageableSectionByHandle(), MmLockPagedPool(), and MmResetDriverPaging().
PKLDR_DATA_TABLE_ENTRY MiLookupDataTableEntry (IN PVOID AddressWithinSection, IN ULONG ResourceHeld)
Definition at line 13817 of file iosup.c.
References ASSERT, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), NULL, PAGED_CODE, PsLoadedModuleList, PsLoadedModuleResource, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, and TRUE.
Referenced by MiCheckCacheAttributes(), MiSessionUnloadAllImages(), MmGetSectionRange(), MmLockPageableDataSection(), MmPageEntireDriver(), and MmResetDriverPaging().
PVOID MiMapLockedPagesInUserSpace (IN PMDL MemoryDescriptorList, IN PVOID StartingVa, IN MEMORY_CACHING_TYPE CacheType, IN PVOID BaseVa)
Definition at line 7081 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, BYTE_OFFSET, _MMPFNENTRY::CacheAttribute, _MMVAD_LONG::ControlArea, _MMPFN::e1, _MMPFN::e2, _MMVAD_LONG::EndingVpn, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, ExFreePool(), ExRaiseStatus(), FALSE, _MMVAD_LONG::FirstPrototypePte, _EPROCESS::Flags, _MMPTE::Hard, LOCK_ADDRESS_SPACE, LOCK_PFN, LOCK_WS_UNSAFE, _MMVAD_LONG::LongFlags, _MMVAD_FLAGS2::LongVad, MDL_IO_SPACE, MI_DISABLE_CACHING, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PHYSICAL_VIEW_KEY, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_VA_TO_VPN, MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiCheckForConflictingVadExistence(), MiCreatePhysicalVadRoot(), MiFindEmptyAddressRange(), MiGetPteAddress, MiInsertNode(), MiInsertVad(), MiInsertVadCharges(), MiMakePdeExistAndMakeValid(), MiNonCached, MiNonCachedCollisions, MiNotMapped, MiWriteCombined, MM_EMPTY_LIST, MM_HIGHEST_VAD_ADDRESS, MM_NOIRQL, MM_READWRITE, NonPagedPool, NT_SUCCESS, NULL, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::PhysicalVadRoot, _MMVAD_FLAGS::PrivateMemory, _MMVAD_FLAGS::Protection, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, RtlZeroMemory, _MMPFN::ShareCount, _MMVAD_LONG::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_ADDRESS, STATUS_PROCESS_IS_TERMINATING, TRUE, _MMPTE::u, _MMVAD_LONG::u, _MMPFN::u2, _MMVAD_LONG::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, UNLOCK_PFN, UNLOCK_WS_AND_ADDRESS_SPACE, _MI_PHYSICAL_VIEW::Vad, VadDevicePhysicalMemory, _MMVAD_LONG::VadFlags, _MMVAD_LONG::VadFlags2, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, ValidUserPte, and X64K.
Referenced by MmMapLockedPagesSpecifyCache().
PVOID MiMapSinglePage (IN PVOID VirtualAddress OPTIONAL, IN PFN_NUMBER PageFrameIndex, IN MEMORY_CACHING_TYPE CacheType, IN MM_PAGE_PRIORITY Priority)
Definition at line 5039 of file iosup.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_PFN2, MI_DISABLE_CACHING, MI_FLUSH_SINGLE_TB, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiCached, MiCacheOverride, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiNonCached, MiNotMapped, MiReserveSystemPtes(), MiWriteCombined, MM_SYSTEM_RANGE_START, NULL, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteAddress, _MMPFN::PteFrame, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, UNREFERENCED_PARAMETER, _MMPTE_HARDWARE::Valid, ValidKernelPte, and X64K.
Referenced by MiCloneProcessAddressSpace().
PVOID MiMapWithLargePages (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN ULONG Protection, IN MEMORY_CACHING_TYPE CacheType)
Definition at line 7986 of file iosup.c.
References ASSERT, BYTE_OFFSET, CONTAINING_RECORD, _KPROCESS::DirectoryTableBase, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MMPTE::Hard, KeFeatureBits, KF_LARGE_PAGE, LOCK_EXPANSION2, _MMPTE::Long, MI_DISABLE_LARGE_PTE_CACHING, MI_FLUSH_ENTIRE_TB, MI_IS_PFN(), MI_MAKE_PDE_MAP_LARGE_PAGE, MI_MAKE_VALID_PTE, MI_PREPARE_FOR_NONCACHED, MI_SET_ACCESSED_IN_PTE, MI_SET_GLOBAL_STATE, MI_SET_LARGE_PTE_WRITE_COMBINE, MI_SET_PTE_DIRTY, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInsertIoSpaceMap(), MiMapPageInHyperSpaceAtDpc(), MiNonCached, MiNotMapped, MiReleaseSystemPtes(), MiReserveAlignedSystemPtes(), MiUnmapPageInHyperSpaceFromDpc, MiWriteCombined, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_VA_MAPPED_BY_PDE, MmProcessList, NO_BITS_FOUND, NOTHING, NULL, _EPROCESS::PaeTop, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, PDE_BASE, PS_PROCESS_FLAGS_OUTSWAPPED, PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED, PS_SET_BITS, PsGetCurrentProcess(), RtlClearBits(), RtlFindClearBitsAndSet(), SystemPteSpace, TRUE, _MMPTE::u, UNLOCK_EXPANSION2, and _MMPTE_HARDWARE::Valid.
Referenced by __out_bcount(), and MiUseLargeDriverPage().
VOID MiPhysicalViewAdjuster (IN PEPROCESS Process, IN PMMVAD OldVad, IN PMMVAD NewVad)
Definition at line 7029 of file iosup.c.
References ASSERT, MiFindNodeOrParent(), NULL, TableFoundNode, and _MI_PHYSICAL_VIEW::Vad.
Referenced by MiSecureVirtualMemory().
VOID MiPhysicalViewRemover (IN PEPROCESS Process, IN PMMVAD Vad)
Definition at line 6954 of file iosup.c.
References ASSERT, ExFreePool(), LOCK_WS_UNSAFE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiFindNodeOrParent(), MiFreeInPageSupportBlock(), MiReleaseSystemPtes(), MiRemoveNode(), MiResidentPagesForSpan(), MM_RESAVAIL_FREE_ROTATE_VAD, NULL, PsGetCurrentThread(), PsReturnProcessNonPagedPoolQuota(), _RTL_BITMAP::SizeOfBitMap, SystemPteSpace, TableFoundNode, UNLOCK_WS_UNSAFE, _MI_PHYSICAL_VIEW::Vad, VadRotatePhysical, and VadWriteWatch.
Referenced by MiRemoveMappedView(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MmCleanProcessAddressSpace(), and NtFreeVirtualMemory().
LOGICAL MiReferenceIoSpace (IN PMDL MemoryDescriptorList, IN PPFN_NUMBER Page)
Referenced by MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
LOGICAL MiReferenceIoSpace (IN OUT PMDL MemoryDescriptorList, IN PPFN_NUMBER Page)
Definition at line 2934 of file iosup.c.
References ExAcquireSpinLock, ExAllocatePoolWithTag, ExReleaseSpinLock, FALSE, MiTrackIoLock, NonPagedPool, NULL, PushEntryList, RtlCopyMemory, and TRUE.
VOID MiRemoveIoSpaceMap (IN PVOID BaseVa, IN PFN_NUMBER NumberOfPages)
Definition at line 4964 of file iosup.c.
References _MMIO_TRACKER::BaseVa, CONTAINING_RECORD, ExAcquireSpinLock, ExFreePool(), ExReleaseSpinLock, _LIST_ENTRY::Flink, KeBugCheckEx(), _MMIO_TRACKER::ListEntry, MmIoTrackerLock, _MMIO_TRACKER::NumberOfPages, PAGE_ALIGN, RemoveEntryList(), and SYSTEM_PTE_MISUSE.
Referenced by __out_bcount(), and MmUnmapIoSpace().
VOID MiRemovePteTracker (IN PMDL MemoryDescriptorList OPTIONAL, IN PVOID VirtualAddress, IN PFN_NUMBER NumberOfPtes)
Definition at line 4492 of file iosup.c.
References ARGUMENT_PRESENT, CONTAINING_RECORD, _PTE_TRACKER::Count, _SYSPTES_HEADER::Count, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _LIST_ENTRY::Flink, InterlockedPushEntrySList(), KeBugCheckEx(), _PTE_TRACKER::ListEntry, _SYSPTES_HEADER::ListHead, MDL_FREE_EXTRA_PTES, MiMdlsAdjusted, MiPteTrackerLock, MiTrackPtesAborted, NULL, _SYSPTES_HEADER::NumberOfEntries, _PTE_TRACKER::Page, PAGE_ALIGN, PSLIST_ENTRY, RemoveEntryList(), _PTE_TRACKER::StartVa, SYSTEM_PTE_MISUSE, and _PTE_TRACKER::SystemVa.
Referenced by MmFreeMappingAddress(), MmUnmapIoSpace(), and MmUnmapLockedPages().
VOID MiUnmapLargePages (IN PVOID BaseAddress, IN SIZE_T NumberOfBytes)
Definition at line 8307 of file iosup.c.
References ASSERT, BYTE_OFFSET, CONTAINING_RECORD, _KPROCESS::DirectoryTableBase, ExAcquireSpinLock, ExReleaseSpinLock, _EPROCESS::Flags, _LIST_ENTRY::Flink, _MMPTE::Hard, LOCK_EXPANSION2, _MMPTE::Long, MI_FLUSH_ENTIRE_TB, MI_PDE_MAPS_LARGE_PAGE, MI_WRITE_ZERO_PTE, MiGetPdeAddress, MiGetVirtualAddressMappedByPte, MiMapPageInHyperSpaceAtDpc(), MiReleaseSystemPtes(), MiUnmapPageInHyperSpaceFromDpc, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_VA_MAPPED_BY_PDE, MmProcessList, NOTHING, _EPROCESS::PaeTop, PAGE_SHIFT, _EPROCESS::Pcb, PDE_BASE, PS_PROCESS_FLAGS_OUTSWAPPED, PS_PROCESS_FLAGS_PDE_UPDATE_NEEDED, PS_SET_BITS, PsGetCurrentProcess(), RtlAreBitsSet(), RtlClearBits(), SystemPteSpace, TRUE, _MMPTE::u, UNLOCK_EXPANSION2, and _MMPTE_HARDWARE::Valid.
Referenced by MiReloadBootLoadedDrivers(), MmUnloadSystemImage(), and MmUnmapIoSpace().
VOID MiUnmapLockedPagesInUserSpace (IN PVOID BaseAddress, IN PMDL MemoryDescriptorList)
Definition at line 7536 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, ASSERT64, _MMPTE_FLUSH_LIST::Count, _MMVAD::EndingVpn, ExFreePool(), ExPageLockHandle, FALSE, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, LOCK_ADDRESS_SPACE, LOCK_PFN, LOCK_WS_UNSAFE, _MMPTE::Long, MI_DECREMENT_USED_PTES_BY_HANDLE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_USED_PTES_FROM_HANDLE, MI_GET_USED_PTES_HANDLE, MI_PFN_ELEMENT, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_ZERO_PTE, MiDecrementShareCountInline, MiDeletePte(), MiFlushPteList(), MiGetNextVad, MiGetPdeAddress, MiGetPreviousVad, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiLocateAddress(), MiPhysicalViewRemover(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MM_EMPTY_LIST, MM_MAXIMUM_FLUSH_COUNT, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), NULL, PAGE_SIZE, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMVAD::StartingVpn, _MMPTE::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_PFN, UNLOCK_WS_AND_ADDRESS_SPACE, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, and _MMPTE_HARDWARE::Valid.
Referenced by MmUnmapLockedPages().
VOID MiUnmapSinglePage (IN PVOID VirtualAddress)
Definition at line 5300 of file iosup.c.
References ASSERT, MI_IS_PHYSICAL_ADDRESS, MiGetPteAddress, MiReleaseSystemPtes(), MM_SYSTEM_RANGE_START, PAGED_CODE, and SystemPteSpace.
Referenced by MiCloneProcessAddressSpace().
LOGICAL MiUpdateMdlTracker (IN PMDL MemoryDescriptorList, IN ULONG AdvancePages)
Definition at line 1718 of file iosup.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _LOCK_TRACKER::Count, FALSE, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, _EPROCESS::LockedPagesList, _LOCK_TRACKER::Mdl, MmTrackLockedPages, NULL, _LOCK_TRACKER::Page, PsInitialSystemProcess, and TRUE.
Referenced by MmAdvanceMdl().
VOID MiZeroAwePageWorker (IN PVOID Context)
Definition at line 9877 of file iosup.c.
References _KPROCESS::Affinity, ASSERT, _KTHREAD::BasePriority, _COLORED_PAGE_INFO::BasePriority, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _COLORED_PAGE_INFO::Event, FALSE, _MMPTE::Hard, KeFindFirstSetLeftAffinity, KeGetCurrentThread(), KeSetEvent(), KeSetIdealProcessorThread(), KeSetPriorityThread(), KeZeroPages, _MMPTE::Long, MI_DISABLE_CACHING, MI_MAKE_VALID_KERNEL_PTE, MI_PFN_ELEMENT_TO_INDEX, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MiCached, MiGetVirtualAddressMappedByPte, MiNonCached, MiReleaseSystemPtes(), MiReserveSystemPtes(), MiWriteCombined, MiZeroPhysicalPage(), MM_DEMAND_ZERO_WRITE_PTE, MM_EMPTY_LIST, MM_READWRITE, NO_BITS_FOUND, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _COLORED_PAGE_INFO::PagesQueued, _EPROCESS::Pcb, _COLORED_PAGE_INFO::PfnAllocation, PsIdleProcess, PsInitialSystemProcess, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
Referenced by MiZeroInParallel().
VOID MiZeroInParallel (IN PCOLORED_PAGE_INFO ColoredPageInfoBase)
Definition at line 10113 of file iosup.c.
References _KPROCESS::Affinity, ASSERT, _KTHREAD::BasePriority, _COLORED_PAGE_INFO::BasePriority, _COLORED_PAGE_INFO::Event, Executive, FALSE, InitializationPhase, InitializeObjectAttributes, IS_SYSTEM_THREAD, KeInitializeEvent(), KeNodeBlock, KeNumberNodes, KernelMode, KeSetPriorityThread(), KeWaitForMultipleObjects(), LOW_REALTIME_PRIORITY, MAXIMUM_WAIT_OBJECTS, MiZeroAwePageWorker(), MM_EMPTY_LIST, MmSecondaryColorNodeShift, MmSecondaryColors, NT_SUCCESS, NULL, _EPROCESS::Pcb, _COLORED_PAGE_INFO::PfnAllocation, PsCreateSystemThread(), PsGetCurrentThread(), PsIdleProcess, PsInitialSystemProcess, Status, STATUS_SUCCESS, SynchronizationEvent, _ETHREAD::Tcb, THREAD_ALL_ACCESS, WaitAll, and ZwClose().
Referenced by MiAllocateLargeZeroPages(), and MiAllocatePagesForMdl().
NTKERNELAPI NTSTATUS MmAdvanceMdl (__inout PMDL Mdl, __in ULONG NumberOfBytes)
Definition at line 6092 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, BYTE_OFFSET, DISPATCH_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, GET_PAGING_FILE_OFFSET, InterlockedCompareExchange(), InterlockedExchangeAddSizeT, KeGetCurrentIrql(), LOCK_PFN2, MDL_DESCRIBES_AWE, MDL_FREE_EXTRA_PTES, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_IS_PFN(), MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiDecrementReferenceCountForAwePage(), MiMdlsAdjusted, MiReleaseConfirmedPageFileSpace(), MiUpdateMdlTracker(), MM_EMPTY_LIST, MmHighestPhysicalPage, MmTrackLockedPages, NULL, NumberOfBytes, _EPROCESS::NumberOfLockedPages, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, ReadForWriteAccess, _MMPTE::Soft, STATUS_INVALID_PARAMETER_2, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, and _MMPFNENTRY::WriteInProgress.
PVOID MmAllocateIndependentPages (IN SIZE_T NumberOfBytes, IN ULONG Node)
Definition at line 9582 of file iosup.c.
References ASSERT, BYTES_TO_PAGES, FALSE, _MMPTE::Hard, KeNumberNodes, LOCK_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_GET_PAGE_COLOR_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_NONPAGEABLE_MEMORY_AVAILABLE, MI_SET_PTE_DIRTY, MI_SYSTEM_PAGE_COLOR, MiChargeCommitment(), MiEnsureAvailablePageOrWait(), MiGetVirtualAddressMappedByPte, MiInitializePfnAndMakePteValid(), MiReleaseSystemPtes(), MiRemoveAnyPage(), MiReserveSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_INDEPENDENT_PAGES, MM_HIGH_LIMIT, MM_READWRITE, MM_RESAVAIL_ALLOCATE_INDEPENDENT, MM_TRACK_COMMIT, MmAvailablePages, MmSecondaryColorMask, MmSecondaryColorNodeShift, NULL, _MMPTE_HARDWARE::PageFrameNumber, SystemPteSpace, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by ExCreatePoolTagTable(), InitializePool(), KeStartAllProcessors(), and KiI386PentiumLockErrataFixup().
PMDL MmAllocatePagesForMdl (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes)
Definition at line 11476 of file iosup.c.
References MiAllocatePagesForMdl(), and MiNotMapped.
PMDL MmAllocatePagesForMdlEx (__in PHYSICAL_ADDRESS LowAddress, __in PHYSICAL_ADDRESS HighAddress, __in PHYSICAL_ADDRESS SkipBytes, __in SIZE_T TotalBytes, __in MEMORY_CACHING_TYPE CacheType, __in ULONG Flags)
Definition at line 11546 of file iosup.c.
References FALSE, MI_TRANSLATE_CACHETYPE(), MiAllocatePagesForMdl(), MiNotMapped, MM_ALLOCATE_FROM_LOCAL_NODE_ONLY, MM_DONT_ZERO_ALLOCATION, MmWriteCombined, and NULL.
LOGICAL MmAreMdlPagesLocked (IN PMDL MemoryDescriptorList)
Definition at line 14960 of file iosup.c.
References ActiveAndValid, ADDRESS_AND_SIZE_TO_SPAN_PAGES, BASE_POOL_TYPE_MASK, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, FALSE, LOCK_PFN2, MDL_IO_SPACE, MDL_SOURCE_IS_NONPAGED_POOL, MI_IS_PFN(), MI_PFN_ELEMENT, MiEndOfInitialPoolFrame, MiGetVirtualAddressMappedByPte, MiStartOfInitialPoolFrame, MM_EMPTY_LIST, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmQuerySpecialPoolBlockType(), MmSpecialPoolEnd, MmSpecialPoolStart, NonPagedPool, NOTHING, NULL, _MMPFNENTRY::PageLocation, _MMPFN::PteAddress, _MMPFN::ShareCount, TRUE, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN2.
Referenced by MmBuildMdlForNonPagedPool().
VOID MmBuildMdlForNonPagedPool (__inout PMDL MemoryDescriptorList)
Definition at line 4193 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MiGetPteAddress, MmAreMdlPagesLocked(), MmIsNonPagedSystemAddressValid(), and NULL.
Referenced by CcZeroData(), and MiCreateImageFileMap().
PMDL MmCreateMdl (__in_opt PMDL MemoryDescriptorList, __in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
Definition at line 12444 of file iosup.c.
References _4gb, ARGUMENT_PRESENT, ExAllocatePoolWithTag, MmInitializeMdl, MmSizeOfMdl(), NonPagedPool, and NULL.
Referenced by MiAllocatePagesForMdl(), MiCcPrepareReadInfo(), MiZeroPageFileFirstPage(), and NtFreeUserPhysicalPages().
VOID MmEnablePAT (VOID)
Definition at line 14799 of file iosup.c.
References _MMPTE::Long, MI_SET_PTE_WRITE_COMBINE, MiAllMainMemoryMustBeCached, MiWriteCombiningPtes, MM_WRITECOMBINE, MmProtectToPteMask, TRUE, and _MMPTE::u.
Referenced by KiInitializePAT(), and KiInitMachineDependent().
VOID MmFreeContiguousMemory (__in PVOID BaseAddress)
Definition at line 9396 of file iosup.c.
References ActiveAndValid, ASSERT, BAD_POOL_CALLER, DRIVER_VERIFIER_DEADLOCK_DETECTION, _MMPFN::e1, _MMPFN::e2, ExFreePool(), KeBugCheckEx(), _MM_DRIVER_VERIFIER_DATA::Level, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiDeferredUnlockPages(), MiFreeLowMemory(), MiGetPteAddress, MiNoLowMemory, MiReturnCommitment, MM_DEMAND_ZERO_WRITE_PTE, MM_RESAVAIL_FREE_CONTIGUOUS2, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmSizeOfNonPagedPoolInBytes, MmUnmapIoSpace(), MmVerifierData, _MMPFN::OriginalPte, PAGE_SHIFT, PAGED_CODE, _MMPFNENTRY::PageLocation, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, SPECIAL_POOL_ADDRESS, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPFN::VerifierAllocation, and VerifierDeadlockFreePool().
Referenced by Ki386ClearIdentityMap(), and MmFreeContiguousMemorySpecifyCache().
VOID MmFreeContiguousMemorySpecifyCache (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in MEMORY_CACHING_TYPE CacheType)
Definition at line 9538 of file iosup.c.
References MmFreeContiguousMemory(), and UNREFERENCED_PARAMETER.
VOID MmFreeIndependentPages (IN PVOID VirtualAddress, IN SIZE_T NumberOfBytes)
Definition at line 9788 of file iosup.c.
References APC_LEVEL, ASSERT, BYTES_TO_PAGES, _MMPTE::Hard, KeGetCurrentIrql(), LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MiDecrementShareCount(), MiGetPteAddress, MiReleaseSystemPtes(), MiReturnCommitment, MM_DBG_COMMIT_INDEPENDENT_PAGES, MM_RESAVAIL_FREE_INDEPENDENT, MM_TRACK_COMMIT, _MMPFN::PteFrame, SystemPteSpace, _MMPTE::u, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by ExDeletePoolTagTable(), and KeStartAllProcessors().
VOID MmFreeMappingAddress (__in PVOID BaseAddress, __in ULONG PoolTag)
Definition at line 5471 of file iosup.c.
References ASSERT, KeBugCheckEx(), KeGetCurrentIrql(), _MMPTE::Long, MI_IS_PHYSICAL_ADDRESS, MiGetPteAddress, MiReleaseSystemPtes(), MiRemovePteTracker(), MM_HIGHEST_USER_ADDRESS, MmTrackPtes, NULL, PASSIVE_LEVEL, SYSTEM_PTE_MISUSE, SystemPteSpace, and _MMPTE::u.
VOID MmFreeNonCachedMemory (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
Definition at line 12338 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, _MDL::ByteOffset, BYTES_TO_PAGES, ExFreePool(), MiGetPteAddress, MiReleaseSystemPtes(), MmFreePagesFromMdl(), PAGE_ALIGN, _MDL::StartVa, and SystemPteSpace.
VOID MmFreePagesFromMdl (__in PMDL MemoryDescriptorList)
Definition at line 11642 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, APC_LEVEL, ASSERT, _MMPFN::AweAllocation, _MMPFN::AweReferenceCount, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, ExPageLockHandle, InterlockedCompareExchange(), InterlockedExchangeAddSizeT, KeBugCheckEx(), KeGetCurrentIrql(), LOCK_PFN, MDL_IO_SPACE, MDL_PAGES_LOCKED, MEMORY_MANAGEMENT, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PFN(), MI_IS_PFN_DELETED, MI_MAGIC_AWE_PTEFRAME, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MiCached, MiDecrementReferenceCountForAwePage(), MiDecrementReferenceCountInline, MiNotMapped, MiReturnCommitment, MM_DBG_COMMIT_RETURN_MDL_PAGES, MM_EMPTY_LIST, MM_RESAVAIL_FREE_FROM_MDL, MM_TRACK_COMMIT, MmHighestPhysicalPage, MmLockPageableSectionByHandle(), MmMdlPagesAllocated, MmUnlockPageableImageSection(), PAGE_SIZE, _MMPFNENTRY::PageLocation, _MMPFN::PteFrame, ReadForWriteAccess, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and UNLOCK_PFN.
Referenced by __out_bcount(), MiCleanPhysicalProcessPages(), MmFreeNonCachedMemory(), NtAllocateUserPhysicalPages(), and NtFreeUserPhysicalPages().
NTKERNELAPI ULONG MmGatherMemoryForHibernate (IN PMDL Mdl, IN BOOLEAN Wait)
Definition at line 14613 of file iosup.c.
References APC_LEVEL, _MMPFN::e2, FALSE, InterlockedDecrement, InterlockedIncrement, KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, LOCK_PFN2, _MMPTE::Long, MDL_PAGES_LOCKED, MI_DEFER_PFN_HELD, MI_GET_PAGE_COLOR_FROM_PTE, MI_PFN_ELEMENT, MI_PFN_PRIORITIES, MI_SET_PFN_DELETED, MiDeferredUnlockPages(), MiDelayPageFaults, MiFlushAllPages(), MiRemoveAnyPage(), Mm30Milliseconds, MM_DEMAND_ZERO_WRITE_PTE, MmEmptyAllWorkingSets(), MmFreePageListHead, MmStandbyPageListByPriority, MmZeroedPageListHead, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, _MMPFN::PteAddress, _MMPFNLIST::Total, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, and X64K.
PHYSICAL_ADDRESS MmGetPhysicalAddress (__in PVOID BaseAddress)
Definition at line 12050 of file iosup.c.
References BYTE_OFFSET, _MMPTE::Hard, KdPrint, _LARGE_INTEGER::LowPart, MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, _MMPTE::u, _MMPTE_HARDWARE::Valid, and ZERO_LARGE.
Referenced by Ki386BuildIdentityBuffer(), Ki386ConvertPte(), Ki386CreateIdentityMap(), MmHibernateInformation(), and MmMapUserAddressesToPage().
NTSTATUS MmGetSectionRange (IN PVOID AddressWithinSection, OUT PVOID * StartingSectionAddress, OUT PULONG SizeofSection)
Definition at line 13574 of file iosup.c.
References _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _IMAGE_NT_HEADERS::FileHeader, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), MiLookupDataTableEntry(), _IMAGE_SECTION_HEADER::Misc, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGED_CODE, PsLoadedModuleResource, RtlImageNtHeader(), _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, Status, STATUS_NOT_FOUND, STATUS_SUCCESS, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
PVOID MmGetVirtualForPhysical (__in PHYSICAL_ADDRESS PhysicalAddress)
Definition at line 12137 of file iosup.c.
References BYTE_OFFSET, MI_PFN_ELEMENT, MiGetVirtualAddressMappedByPte, PAGE_SHIFT, and _MMPFN::PteAddress.
LOGICAL MmIsIoSpaceActive (__in PHYSICAL_ADDRESS StartAddress, __in SIZE_T NumberOfBytes)
Definition at line 3078 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, _MDL::ByteOffset, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, InterlockedIncrement, MI_IS_PFN(), MiActiveIoCounter, MiTrackIoLock, MM_EMPTY_LIST, _MDL::Next, _SINGLE_LIST_ENTRY::Next, NULL, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, _MDL::StartVa, and TRUE.
BOOLEAN MmIsRecursiveIoFault (VOID)
Definition at line 14043 of file iosup.c.
References _ETHREAD::DisablePageFaultClustering, _ETHREAD::ForwardClusterOnly, and PsGetCurrentThread().
Referenced by IoPageRead().
LOGICAL MmIsSystemAddressLocked (IN PVOID VirtualAddress)
Definition at line 14858 of file iosup.c.
References _MMPFN::e2, _MMPFN::Event, FALSE, IS_SYSTEM_ADDRESS, LOCK_PFN2, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_PROCESS_SPACE_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, MiIsAddressValid(), NULL, _MMPFN::ShareCount, TRUE, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, and UNLOCK_PFN2.
VOID MmLockPagableSectionByHandle (__in PVOID ImageSectionHandle)
Definition at line 12929 of file iosup.c.
References MmLockPageableSectionByHandle().
PVOID MmLockPageableDataSection (__in PVOID AddressWithinSection)
Definition at line 13665 of file iosup.c.
References _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _IMAGE_NT_HEADERS::FileHeader, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), MEMORY_MANAGEMENT, MI_IS_PHYSICAL_ADDRESS, MiLookupDataTableEntry(), _IMAGE_SECTION_HEADER::Misc, MmLockPageableSectionByHandle(), NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGED_CODE, PsLoadedModuleResource, RtlImageNtHeader(), SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
VOID MmLockPageableSectionByHandle (__in PVOID ImageSectionHandle)
Definition at line 12937 of file iosup.c.
References ASSERT, FALSE, InterlockedCompareExchange(), InterlockedDecrement, InterlockedIncrement, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KePulseEvent(), KernelMode, KeWaitForSingleObject(), MI_IS_PHYSICAL_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MiGetPteAddress, MiLockCode(), _IMAGE_SECTION_HEADER::Misc, MM_LOCK_BY_REFCOUNT, MmCollidedLockWait, MmShortTime, MmSystemRangeStart, SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualSize, and WrVirtualMemory.
Referenced by ExpGetLockInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpSystemErrorHandler(), IoUnregisterShutdownNotification(), KeSetPhysicalCacheTypeRange(), KiAmdK6MtrrSetMemoryType(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiResetVirtualMemory(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiShutdownSystem(), MiUnmapLockedPagesInUserSpace(), MmAdjustWorkingSetSizeEx(), MmFreePagesFromMdl(), MmLockPagableSectionByHandle(), MmLockPageableDataSection(), MmMapUserAddressesToPage(), MmUnlockPagedPool(), PspQueryWorkingSetWatch(), and WmipStartLogger().
VOID MmLockPagedPool (IN PVOID Address, IN SIZE_T SizeInBytes)
Definition at line 14510 of file iosup.c.
References MiGetPteAddress, MiLockCode(), and MM_LOCK_BY_REFCOUNT.
Referenced by MiMakeEntireImageCopyOnWrite().
PVOID MmMapLockedPages (__in PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode)
Definition at line 5251 of file iosup.c.
References HighPagePriority, MmCached, MmMapLockedPagesSpecifyCache(), NULL, and TRUE.
PVOID MmMapLockedPagesWithReservedMapping (__in PVOID MappingAddress, __in ULONG PoolTag, __in PMDL MemoryDescriptorList, __in MEMORY_CACHING_TYPE CacheType)
Definition at line 5565 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFNENTRY::CacheAttribute, DISPATCH_LEVEL, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE::Hard, HIGH_LEVEL, KeBugCheckEx(), KeGetCurrentIrql(), LOCK_PFN2, _MMPTE::Long, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_PARTIAL_HAS_BEEN_MAPPED, MDL_SOURCE_IS_NONPAGED_POOL, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DISABLE_CACHING, MI_IS_PFN(), MI_MAGIC_AWE_PTEFRAME, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PREPARE_FOR_NONCACHED, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiCacheOverride, MiGetPteAddress, MiNonCached, MiNonCachedCollisions, MiNotMapped, MiWriteCombined, MM_EMPTY_LIST, NULL, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteAddress, _MMPFN::PteFrame, SYSTEM_PTE_MISUSE, _MMPTE::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, ValidKernelPte, and X64K.
VOID MmMapMemoryDumpMdl (__inout PMDL MemoryDumpMdl)
Definition at line 14077 of file iosup.c.
References ASSERT, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPTE::Hard, KiFlushSingleTb(), _MMPTE::Long, MI_DISABLE_CACHING, MI_PFN_ELEMENT, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PAGE, MI_WRITE_ZERO_PTE, MiCached, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MmCrashDumpPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPFN::u3, _MMPTE_HARDWARE::Valid, and ValidKernelPte.
NTSTATUS MmMapUserAddressesToPage (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes, __in PVOID PageAddress)
Definition at line 11834 of file iosup.c.
References ASSERT, _MMVAD::EndingVpn, ExPageLockHandle, FALSE, _EPROCESS::Flags, _MMPTE::Hard, InterlockedExchangePte, LOCK_ADDRESS_SPACE, LOCK_PFN, LOCK_WS_UNSAFE, _MMPTE::Long, MI_FLUSH_PROCESS_TB, MI_FLUSH_SINGLE_TB, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiFillMemoryPte, MiGetPteAddress, MiLocateAddress(), MM_HIGHEST_USER_ADDRESS, MmGetPhysicalAddress(), MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), NULL, PAGE_SHIFT, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcessByThread, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _MMVAD::StartingVpn, Status, STATUS_FREE_VM_NOT_AT_BASE, STATUS_INVALID_ADDRESS, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_MEMORY_NOT_ALLOCATED, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MMPTE::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_PFN, UNLOCK_WS_UNSAFE, VadDevicePhysicalMemory, _MMVAD::VadFlags, and _MMVAD_FLAGS::VadType.
VOID MmProbeAndLockPages (__inout PMDL MemoryDescriptorList, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
Definition at line 256 of file iosup.c.
References _MI_PAGING_LEVELS, ActiveAndValid, ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _AWEINFO::AweVadRoot, DbgBreakPoint(), DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _MMPFN::e1, _MMPFN::e2, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), ExReleaseCacheAwarePushLockShared(), FALSE, _MMPTE::Hard, InterlockedCompareExchangePte, InterlockedExchangeAddSizeT, InterlockedIncrement, IoReadAccess, KeEnterGuardedRegionThread(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KernelMode, LOCK_PFN, LOCK_PFN2, LOCK_TYPE_AWE, LOCK_TYPE_PFN, LOCK_TYPE_WS, LOCK_WS_SHARED, _MMPTE::Long, MDL_DESCRIBES_AWE, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INSTRUMENT_PROBE_RAISES, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_SNAP_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiActiveIoCounter, MiAddMdlTracker(), MiDereferenceIoSpace(), MiFindNodeOrParent(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsPteOnPxeBoundary, MiReferenceIoSpace(), MM_EMPTY_LIST, MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MM_PTE_COPY_ON_WRITE_MASK, MM_PTE_WRITE_MASK, MM_USER_PROBE_ADDRESS, MmAccessFault(), MmHighestPhysicalPage, MmPagedPoolEnd, MmPagedPoolStart, MmReferenceCountCheck, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmTrackLockedPages, MmUnlockPages(), NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfLockedPages, _MMPTE_HARDWARE::Owner, PAGE_SIZE, _MMPFNENTRY::PageLocation, _EPROCESS::PhysicalVadRoot, _AWEINFO::PhysicalViewHint, ProbeForWriteChar, PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), _AWEINFO::PushLock, RtlGetCallersAddress(), SATISFY_OVERZEALOUS_COMPILER, _MI_PHYSICAL_VIEW::StartingVpn, STATUS_ACCESS_VIOLATION, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_WORKING_SET_QUOTA, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_PFN2, UNLOCK_WS_SHARED, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by BuildQueryDirectoryIrp(), CcMdlRead(), CcPrepareMdlWrite(), CcZeroData(), ExLockUserBuffer(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopProbeAndLockPages(), KiOpPatchCode(), MiDoMappedCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MmProbeAndLockProcessPages(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtReadFile(), NtSetEaFile(), NtStartProfile(), and NtWriteFile().
NTKERNELAPI VOID MmProbeAndLockProcessPages (__inout PMDL MemoryDescriptorList, __in PEPROCESS Process, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
Definition at line 1315 of file iosup.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), FALSE, KeStackAttachProcess(), KeUnstackDetachProcess(), MmProbeAndLockPages(), PsGetCurrentProcess(), Status, STATUS_SUCCESS, and TRUE.
NTKERNELAPI VOID MmProbeAndLockSelectedPages (__inout PMDL MemoryDescriptorList, __in PFILE_SEGMENT_ELEMENT PagedSegmentArray, __in KPROCESSOR_MODE AccessMode, __in LOCK_OPERATION Operation)
Definition at line 1815 of file iosup.c.
References _MI_PAGING_LEVELS, ActiveAndValid, ASSERT, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _AWEINFO::AweVadRoot, _FILE_SEGMENT_ELEMENT::Buffer, BYTES_TO_PAGES, COPY_STACK_SIZE, DbgBreakPoint(), DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _MMPFN::e1, _MMPFN::e2, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), ExAllocatePoolWithTag, ExFreePool(), ExRaiseStatus(), ExReleaseCacheAwarePushLockShared(), FALSE, _MMPTE::Hard, InterlockedCompareExchangePte, InterlockedExchangeAddSizeT, InterlockedIncrement, IoReadAccess, KeEnterGuardedRegionThread(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KernelMode, LOCK_PFN, LOCK_PFN2, LOCK_TYPE_AWE, LOCK_TYPE_NONE, LOCK_TYPE_PFN, LOCK_TYPE_WS, LOCK_WS_SHARED, _MMPTE::Long, MAXULONG_PTR, MDL_DESCRIBES_AWE, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MI_CONVERT_PHYSICAL_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_INSTRUMENT_PROBE_RAISES, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_SYSTEM_CACHE_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_SNAP_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiActiveIoCounter, MiAddMdlTracker(), MiDereferenceIoSpace(), MiFindNodeOrParent(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiReferenceIoSpace(), MM_EMPTY_LIST, MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MM_PTE_COPY_ON_WRITE_MASK, MM_PTE_WRITE_MASK, MmAccessFault(), MmPagedPoolEnd, MmPagedPoolStart, MmReferenceCountCheck, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmTrackLockedPages, MmUnlockPages(), NonPagedPool, NOTHING, NT_SUCCESS, NULL, _EPROCESS::NumberOfLockedPages, _MMPTE_HARDWARE::Owner, PAGE_SIZE, PAGED_CODE, _MMPFNENTRY::PageLocation, _EPROCESS::PhysicalVadRoot, _AWEINFO::PhysicalViewHint, PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), Ptr64ToPtr(), _AWEINFO::PushLock, RtlCopyMemory, RtlGetCallersAddress(), SATISFY_OVERZEALOUS_COMPILER, _MI_PHYSICAL_VIEW::StartingVpn, STATUS_ACCESS_VIOLATION, STATUS_INSUFFICIENT_RESOURCES, STATUS_WORKING_SET_QUOTA, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_PFN2, UNLOCK_WS_SHARED, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by NtReadFileScatter(), and NtWriteFileGather().
NTKERNELAPI NTSTATUS MmProtectMdlSystemAddress (__in PMDL MemoryDescriptorList, __in ULONG NewProtect)
Definition at line 6455 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPTE_HARDWARE::CacheDisable, CONTAINING_RECORD, DISPATCH_LEVEL, _MMPFN::e2, ExAllocatePoolWithTag, ExFreePool(), FALSE, _LIST_ENTRY::Flink, _MMPTE::Hard, InsertHeadList(), IsListEmpty, KeAcquireSpinLockRaiseToSynch(), KeBugCheckEx(), KeGetCurrentIrql(), KeReleaseSpinLock(), _MM_PTE_MAPPING::ListEntry, _MMPTE::Long, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MEMORY_MANAGEMENT, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_GUARD, MI_IS_NOCACHE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_IS_WRITECOMBINE, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiMakeProtectionMask(), MM_EXECUTE_WRITECOPY, MM_HIGHEST_USER_ADDRESS, MM_INVALID_PROTECTION, MM_MAXIMUM_FLUSH_COUNT, MM_NOACCESS, MM_READWRITE, MM_WRITECOPY, MmProtectedPteList, MmProtectedPteLock, NonPagedPool, NOTHING, NULL, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileLow, _MMPTE_SOFTWARE::Protection, _MM_PTE_MAPPING::Protection, RemoveEntryList(), _MMPTE::Soft, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PAGE_PROTECTION, STATUS_NOT_MAPPED_VIEW, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, _MM_PTE_MAPPING::SystemEndVa, _MM_PTE_MAPPING::SystemVa, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u3, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::WriteThrough.
VOID MmReleaseDumpAddresses (IN PFN_NUMBER NumberOfPages)
Definition at line 14177 of file iosup.c.
References KiFlushSingleTb(), MiGetVirtualAddressMappedByPte, MiZeroMemoryPte, MmCrashDumpPte, and PAGE_SIZE.
NTKERNELAPI VOID MmReturnMemoryForHibernate (IN PMDL Mdl)
Definition at line 14751 of file iosup.c.
References LOCK_PFN2, MI_PFN_ELEMENT, MiDecrementReferenceCount(), PAGE_SHIFT, and UNLOCK_PFN2.
BOOLEAN MmSetAddressRangeModified (__in_bcount(Length) PVOID Address, __in SIZE_T Length)
Definition at line 12508 of file iosup.c.
References Count, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_PFN2, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_IS_PTE_DIRTY, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PTE_CLEAN, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiReleasePageFileSpace(), MM_MAXIMUM_FLUSH_COUNT, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, and _MMPFNENTRY::WriteInProgress.
Referenced by CcFlushCache(), CcMapAndCopy(), CcPurgeAndClearCacheSection(), CcUnpinRepinnedBcb(), and CcZeroData().
NTSTATUS MmSetBankedSection (__in HANDLE ProcessHandle, __in_bcount(BankLength) PVOID VirtualAddress, __in ULONG BankLength, __in BOOLEAN ReadWriteBank, __in PBANKED_SECTION_ROUTINE BankRoutine, __in PVOID Context)
Definition at line 14218 of file iosup.c.
References ASSERT, _MMBANKED_SECTION::BankedRoutine, _MMBANKED_SECTION::BankShift, _MMBANKED_SECTION::BankSize, _MMBANKED_SECTION::BankTemplate, _MMBANKED_SECTION::BasedPte, _MMBANKED_SECTION::BasePhysicalPage, _MMBANKED_SECTION::Context, _MMBANKED_SECTION::CurrentMappedPte, _MMVAD::EndingVpn, ExAllocatePoolWithTag, FALSE, _EPROCESS::Flags, _MMPTE::Hard, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MI_FLUSH_PROCESS_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_USER_PTE, MI_SET_PTE_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MiGetPteAddress, MiLocateAddress(), MiZeroMemoryPte, MM_READWRITE, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, PROCESS_VM_OPERATION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsProcessType, PTE_SHIFT, _MMVAD::StartingVpn, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_VIEW_SIZE, STATUS_NOT_MAPPED_DATA, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _MMPTE::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, UNREFERENCED_PARAMETER, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
BOOLEAN MmSetPageProtection (__in_bcount(NumberOfBytes) PVOID VirtualAddress, __in SIZE_T NumberOfBytes, __in ULONG NewProtect)
Definition at line 9692 of file iosup.c.
References APC_LEVEL, ASSERT, BYTES_TO_PAGES, _MMPTE_HARDWARE::Dirty, FALSE, _MMPTE::Hard, KeGetCurrentIrql(), LOCK_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_KERNEL_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiMakeProtectionMask(), MM_INVALID_PROTECTION, MM_MAXIMUM_FLUSH_COUNT, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, TRUE, _MMPTE::u, and UNLOCK_PFN.
Referenced by KiI386PentiumLockErrataFixup().
SIZE_T MmSizeOfMdl (__in_bcount_opt(Length) PVOID Base, __in SIZE_T Length)
Definition at line 12407 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES.
Referenced by ExLockUserBuffer(), MmCreateMdl(), and NtStartProfile().
VOID MmUnlockPagableImageSection (__in PVOID ImageSectionHandle)
Definition at line 13900 of file iosup.c.
References MmUnlockPageableImageSection().
VOID MmUnlockPageableImageSection (__in PVOID ImageSectionHandle)
Definition at line 13908 of file iosup.c.
References ASSERT, Count, _MMPFN::e2, FALSE, _MMPTE::Hard, InterlockedDecrement, KeBugCheckEx(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KePulseEvent(), LOCK_PFN2, MEMORY_MANAGEMENT, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, _IMAGE_SECTION_HEADER::Misc, MmCollidedLockWait, SECTION_BASE_ADDRESS, SECTION_LOCK_COUNT_POINTER, _IMAGE_SECTION_HEADER::SizeOfRawData, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN2, _MMPTE_HARDWARE::Valid, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by ExpGetLockInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), IoUnregisterShutdownNotification(), KeSetPhysicalCacheTypeRange(), KiAmdK6MtrrSetMemoryType(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiDereferenceSessionFinal(), MiFindContiguousMemoryInPool(), MiResetVirtualMemory(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MiShutdownSystem(), MiUnmapLockedPagesInUserSpace(), MmAdjustWorkingSetSizeEx(), MmFreePagesFromMdl(), MmInitSystem(), MmMapUserAddressesToPage(), MmUnlockPagableImageSection(), MmUnlockPagedPool(), PspQueryWorkingSetWatch(), WmipFreeLoggerContext(), and WmipStartGlobalLogger().
NTKERNELAPI VOID MmUnlockPagedPool (IN PVOID Address, IN SIZE_T SizeInBytes)
Definition at line 14552 of file iosup.c.
References ASSERT, _MMPFN::e2, ExPageLockHandle, _MMPTE::Hard, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiMakeEntireImageCopyOnWrite().
VOID MmUnlockPages (__inout PMDL MemoryDescriptorList)
Definition at line 3287 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, CONTAINING_RECORD, _MMPFN::e1, _MMPFN::e2, FALSE, _MI_PFN_DEREFERENCE_CHUNK::Flags, GET_PAGING_FILE_OFFSET, _MMPTE::Hard, InterlockedCompareExchange(), InterlockedCompareExchangePointer, InterlockedExchangeAddSizeT, InterlockedPopEntrySList(), KeGetCurrentIrql(), KeGetCurrentNode, LOCK_PFN2, LOCK_WS_SHARED, LOCK_WS_SHARED_CROSS_PROCESS, MDL_DESCRIBES_AWE, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MDL_WRITE_OPERATION, MI_DEFER_DRAIN_LOCAL_ONLY, MI_DEFER_PFN_HELD, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_MAX_DEREFERENCE_CHUNK, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MiDecrementReferenceCountForAwePage(), MiDeferredUnlockPages(), MiDereferenceIoSpace(), MiFreeMdlTracker(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiReleaseConfirmedPageFileSpace(), MM_EMPTY_LIST, MmHighestPhysicalPage, MmPfnDeferredList, MmPfnDereferenceSListHead, MmTrackLockedPages, MmUnmapLockedPages(), NOTHING, NULL, _EPROCESS::NumberOfLockedPages, _MI_PFN_DEREFERENCE_CHUNK::NumberOfPages, _MMPFN::OriginalPte, PAGE_SHIFT, _MMPTE_SOFTWARE::PageFileHigh, PASSIVE_LEVEL, _MI_PFN_DEREFERENCE_CHUNK::Pfns, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcessByThread, PsGetCurrentThread(), PSLIST_ENTRY, ReadForWriteAccess, RtlCopyMemory, _MMPFN::ShareCount, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN2, UNLOCK_WS_SHARED, UNLOCK_WS_SHARED_CROSS_PROCESS, _MMPTE_HARDWARE::Valid, and _MMPFNENTRY::WriteInProgress.
Referenced by CcMdlRead(), CcMdlReadComplete2(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPrepareMdlWrite(), CcZeroData(), ExpProfileDelete(), ExUnlockUserBuffer(), IopfCompleteRequest(), KiOpPatchCode(), MiDoMappedCopy(), MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtStartProfile(), and NtStopProfile().
VOID MmUnmapIoSpace (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
Definition at line 8954 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_PDE_MAPS_LARGE_PAGE, MiGetPdeAddress, MiGetPteAddress, MiGetPteOffset, MiReleaseSystemPtes(), MiRemoveIoSpaceMap(), MiRemovePteTracker(), MiUnmapLargePages(), MiZeroMemoryPte, MM_MAXIMUM_FLUSH_COUNT, MmTrackPtes, NULL, PAGE_SIZE, SystemPteSpace, and TRUE.
Referenced by MmFreeContiguousMemory(), MmUnmapVideoDisplay(), and WmipFirmwareTableHandler().
VOID MmUnmapReservedMapping (IN PVOID BaseAddress, IN ULONG PoolTag, IN PMDL MemoryDescriptorList)
Definition at line 5907 of file iosup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, DISPATCH_LEVEL, _MMPFN::e2, _MMPTE::Hard, InterlockedExchangeAddSizeT, KeBugCheckEx(), KeGetCurrentIrql(), _MMPTE::Long, MDL_FREE_EXTRA_PTES, MDL_MAPPED_TO_SYSTEM_VA, MDL_PARENT_MAPPED_SYSTEM_VA, MDL_PARTIAL_HAS_BEEN_MAPPED, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_IS_PHYSICAL_ADDRESS, MI_PFN_ELEMENT, MiGetPteAddress, MiZeroMemoryPte, MM_HIGHEST_USER_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, PAGE_SIZE, SYSTEM_PTE_MISUSE, TRUE, _MMPTE::u, _MMPFN::u3, and _MMPTE_HARDWARE::Valid.
VOID MmUnmapVideoDisplay (__in_bcount(NumberOfBytes) PVOID BaseAddress, __in SIZE_T NumberOfBytes)
Definition at line 14474 of file iosup.c.
References MmUnmapIoSpace().
LOGICAL MmUpdateMdlTracker (IN PMDL MemoryDescriptorList, IN PVOID CallingAddress, IN PVOID CallersCaller)
Definition at line 1631 of file iosup.c.
References ASSERT, _LIST_ENTRY::Blink, _LOCK_TRACKER::CallersCaller, _LOCK_TRACKER::CallingAddress, CONTAINING_RECORD, FALSE, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _LOCK_TRACKER::ListEntry, _LOCK_HEADER::ListHead, _LOCK_HEADER::Lock, _EPROCESS::LockedPagesList, _LOCK_TRACKER::Mdl, MmTrackLockedPages, NULL, _LOCK_TRACKER::Page, PsInitialSystemProcess, and TRUE.
Referenced by IopProbeAndLockPages().
Variable Documentation
LONG MiActiveIoCounter
Definition at line 112 of file iosup.c.
Referenced by MiIsProbeActive(), MmIsIoSpaceActive(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
ULONG MiCacheOverride[4]
Definition at line 23 of file iosup.c.
Referenced by __out_bcount(), MiInsertIoSpaceMap(), MiMapLockedPagesInUserSpace(), MiMapSinglePage(), MmMapLockedPagesSpecifyCache(), and MmMapLockedPagesWithReservedMapping().
PCHAR MiCacheStrings[]
Initial value:
= {
    "noncached",
    "cached",
    "writecombined",
    "None"
}
Definition at line 71 of file iosup.c.
Referenced by MiInsertIoSpaceMap().
SLIST_HEADER MiDeadPteTrackerSListHead
Definition at line 107 of file iosup.c.
PFN_NUMBER MiEndOfInitialPoolFrame
Definition at line 66 of file allocpag.c.
Referenced by MiFreePoolPages(), MiInitializeNonPagedPool(), and MmAreMdlPagesLocked().
PMMPTE MiInitialSystemPageDirectory
Definition at line 7981 of file iosup.c.
Referenced by MmInitSystem().
ULONG MiMdlsAdjusted = FALSE
Definition at line 245 of file iosup.c.
Referenced by MiRemovePteTracker(), and MmAdvanceMdl().
ULONG MiNonCachedCollisions
Definition at line 119 of file iosup.c.
Referenced by __out_bcount(), MiMapLockedPagesInUserSpace(), MiMapViewOfPhysicalSection(), MmMapLockedPagesSpecifyCache(), and MmMapLockedPagesWithReservedMapping().
ULONG MiProbeRaises[MI_PROBE_RAISE_SIZE]
Definition at line 232 of file iosup.c.
SYSPTES_HEADER MiPteHeader
Definition at line 106 of file iosup.c.
KSPIN_LOCK MiPteTrackerLock
Definition at line 108 of file iosup.c.
Referenced by MiCheckPteRelease(), MiCheckPteReserve(), MiInitializeIoTrackers(), MiInsertPteTracker(), MiReleaseSplitSystemPtes(), and MiRemovePteTracker().
PFN_NUMBER MiStartOfInitialPoolFrame
Definition at line 65 of file allocpag.c.
Referenced by MiFreePoolPages(), MiInitializeNonPagedPool(), and MmAreMdlPagesLocked().
KSPIN_LOCK MiTrackIoLock
Definition at line 110 of file iosup.c.
Referenced by MiDereferenceIoSpace(), MiInitializeIoTrackers(), MiIsProbeActive(), MiReferenceIoSpace(), and MmIsIoSpaceActive().
BOOLEAN MiTrackPtesAborted = FALSE
Definition at line 105 of file iosup.c.
Referenced by MiGetHighestPteConsumer(), MiInsertPteTracker(), and MiRemovePteTracker().
BOOLEAN MiWriteCombiningPtes = FALSE
Definition at line 223 of file iosup.c.
Referenced by __out_bcount(), MI_IS_WRITE_COMBINE_ENABLED(), MiAddHalIoMappings(), and MmEnablePAT().
KEVENT MmCollidedLockEvent
Definition at line 220 of file iosup.c.
Referenced by MmInitSystem().
LONG MmCollidedLockWait
Definition at line 221 of file iosup.c.
Referenced by MmLockPageableSectionByHandle(), and MmUnlockPageableImageSection().
LIST_ENTRY MmIoHeader
Definition at line 63 of file iosup.c.
KSPIN_LOCK MmIoTrackerLock
Definition at line 62 of file iosup.c.
Referenced by MiInitializeIoTrackers(), MiInsertIoSpaceMap(), and MiRemoveIoSpaceMap().
SINGLE_LIST_ENTRY MmLockedIoPagesHead
Definition at line 2931 of file iosup.c.
PFN_NUMBER MmMdlPagesAllocated
Definition at line 218 of file iosup.c.
Referenced by MiAllocatePagesForMdl(), MiDecrementReferenceCountForAwePage(), and MmFreePagesFromMdl().
ULONG MmReferenceCountCheck = MAXUSHORT / 2
Definition at line 243 of file iosup.c.
Referenced by MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MmProbeAndLockPages(), and MmProbeAndLockSelectedPages().
LONG MmTotalSystemDriverPages
Definition at line 24 of file sysload.c.
Referenced by MiLockCode(), MiSetPagingOfDriver(), MiUseLargeDriverPage(), and MmUnloadSystemImage().
ULONG MmTrackPtes = 0
Definition at line 104 of file iosup.c.
Referenced by __bcount(), __out_bcount(), MiAddSystemPtes(), MiCheckPteRelease(), MiCheckPteReserve(), MiGetHighestPteConsumer(), MiInitializeSystemPtes(), MiReleaseSplitSystemPtes(), MiReleaseSystemPtes(), MiReserveAlignedSystemPtes(), MiReserveSystemPtes(), MmFreeMappingAddress(), MmInitSystem(), MmMapLockedPagesSpecifyCache(), MmUnmapIoSpace(), and MmUnmapLockedPages().
POOL_DESCRIPTOR NonPagedPoolDescriptor
Definition at line 322 of file pool.c.
Referenced by ExQueryPoolUsage(), and InitializePool().