Windows Research Kernel v1.2: C:/Windows Research Kernel/se/adtp.h File Reference
adtp.h File Reference
#include "tokenp.h"
Data Structures
struct _SEP_AUDIT_BOUNDS
struct _SEP_AUDIT_OPTIONS
Macros
#define FULL_PRIVILEGE_AUDITING L"FullPrivilegeAuditing"
#define SEP_QUERY_MEMBERSHIP 1
#define SepAdtAuditThisEvent(AuditType, AccessGranted)
Typedefs
typedef struct _SEP_AUDIT_BOUNDS * PSEP_AUDIT_BOUNDS
typedef struct _SEP_AUDIT_BOUNDS SEP_AUDIT_BOUNDS
typedef struct _SEP_AUDIT_OPTIONS SEP_AUDIT_OPTIONS
Functions
VOID SepAdtCloseObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
VOID SepAdtCreateInstanceAuditAlarm (IN PLUID OperationID, IN PVOID Object, IN PSID UserSid, IN LUID AuthenticationId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, IN BOOLEAN GenerateAudit, IN BOOLEAN GenerateAlarm)
VOID SepAdtCreateObjectAuditAlarm (IN PLUID OperationID, IN PUNICODE_STRING DirectoryName, IN PUNICODE_STRING ComponentName, IN PSID UserSid, IN LUID AuthenticationId, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, IN BOOLEAN GenerateAudit, IN BOOLEAN GenerateAlarm)
VOID SepAdtDeleteObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
VOID SepAdtInitializeAuditingOptions (VOID)
VOID SepAdtInitializeBounds (VOID)
NTSTATUS SepAdtInitializeCrashOnFail (VOID)
BOOLEAN SepAdtInitializePrivilegeAuditing (VOID)
NTSTATUS SepAdtMarshallAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters, OUT PSE_ADT_PARAMETER_ARRAY *MarshalledAuditParameters, OUT PSEP_RM_LSA_MEMORY_TYPE RecordMemoryType)
VOID SepAdtObjectReferenceAuditAlarm (IN PVOID Object, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted)
BOOLEAN SepAdtOpenObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId OPTIONAL, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName OPTIONAL, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID, IN POLICY_AUDIT_EVENT_TYPE AuditType, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PACCESS_MASK GrantedAccessArray OPTIONAL)
BOOLEAN SepAdtOpenObjectForDeleteAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID)
VOID SepAdtPrivilegedServiceAuditAlarm (IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN PUNICODE_STRING CapturedSubsystemName, IN PUNICODE_STRING CapturedServiceName, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
BOOLEAN SepAdtPrivilegeObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName OPTIONAL, IN PVOID HandleId, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PVOID ProcessId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
VOID SepAdtTraverseAuditAlarm (IN PLUID OperationID, IN PVOID DirectoryObject, IN PSID UserSid, IN LUID AuthenticationId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, IN BOOLEAN GenerateAudit, IN BOOLEAN GenerateAlarm)
VOID SepAuditFailed (IN NTSTATUS AuditStatus)
BOOLEAN SepInitializePrivilegeFilter (BOOLEAN Verbose)
Variables
GENERIC_MAPPING GenericMappingForMembershipCheck
BOOLEAN SepAdtAuditingEnabled
ULONG SepAdtCountEventsDiscarded
ULONG SepAdtCurrentListLength
BOOLEAN SepAdtDiscardingAudits
POLICY_AUDIT_LOG_INFO SepAdtLogInformation
PKEVENT SepAdtLsaDeadEvent
ULONG SepAdtMaxListLength
ULONG SepAdtMinListLength
SEP_AUDIT_OPTIONS SepAuditOptions
BOOLEAN SepCrashOnAuditFail
PSECURITY_DESCRIPTOR SepImportantProcessSd
PSECURITY_DESCRIPTOR SepProcessAuditSd
Macro Definition Documentation
#define FULL_PRIVILEGE_AUDITING L"FullPrivilegeAuditing"
Definition at line 84 of file adtp.h.
Referenced by SepAdtInitializePrivilegeAuditing().
#define SEP_QUERY_MEMBERSHIP 1
Definition at line 106 of file adtp.h.
Referenced by SepCheckTokenForCoreSystemSids(), and SepInitProcessAuditSd().
#define SepAdtAuditThisEvent (AuditType, AccessGranted)
Value:
(SepAdtAuditingEnabled &&                                           \
    ((SeAuditingState[AuditType].AuditOnSuccess && *AccessGranted) ||   \
    (SeAuditingState[AuditType].AuditOnFailure && !(*AccessGranted))))
Definition at line 243 of file adtp.h.
Referenced by SeAuditingFileEvents(), and SeAuditingHardLinkEvents().
Typedef Documentation
typedef struct _SEP_AUDIT_BOUNDS * PSEP_AUDIT_BOUNDS
typedef struct _SEP_AUDIT_BOUNDS SEP_AUDIT_BOUNDS
typedef struct _SEP_AUDIT_OPTIONS SEP_AUDIT_OPTIONS
Function Documentation
VOID SepAdtCloseObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
Definition at line 1742 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryObjectAccess, _SEP_AUDIT_OPTIONS::DoNotAuditCloseObjectEvents, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_CLOSE_HANDLE, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepAuditOptions, SepSetParmTypeFileSpec, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SeSubsystemName, Status, and TRUE.
Referenced by NtCloseObjectAuditAlarm(), and SeCloseObjectAuditAlarm().
VOID SepAdtCreateInstanceAuditAlarm (IN PLUID OperationID, IN PVOID Object, IN PSID UserSid, IN LUID AuthenticationId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, IN BOOLEAN GenerateAudit, IN BOOLEAN GenerateAlarm)
VOID SepAdtCreateObjectAuditAlarm (IN PLUID OperationID, IN PUNICODE_STRING DirectoryName, IN PUNICODE_STRING ComponentName, IN PSID UserSid, IN LUID AuthenticationId, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, IN BOOLEAN GenerateAudit, IN BOOLEAN GenerateAlarm)
VOID SepAdtDeleteObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID HandleId, IN PSID UserSid)
Definition at line 1924 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryObjectAccess, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), FALSE, NT_SUCCESS, NULL, NullString, PAGED_CODE, PsGetCurrentProcess(), PsProcessAuditId, RtlZeroMemory, SE_AUDITID_DELETE_OBJECT, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepSetParmTypeFileSpec, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SeSubsystemName, Status, STATUS_SUCCESS, and TRUE.
Referenced by NtDeleteObjectAuditAlarm(), and SeDeleteObjectAuditAlarm().
VOID SepAdtInitializeAuditingOptions (VOID)
Definition at line 305 of file adtinit.c.
References _SEP_AUDIT_OPTIONS::DoNotAuditCloseObjectEvents, FALSE, NT_SUCCESS, PAGED_CODE, SepAuditOptions, SepRegQueryDwordValue(), Status, and TRUE.
Referenced by SeRmInitPhase1().
VOID SepAdtInitializeBounds (VOID)
Definition at line 81 of file adtinit.c.
References _SEP_AUDIT_BOUNDS::LowerBound, NT_SUCCESS, NULL, PAGED_CODE, REG_BINARY, SepAdtMaxListLength, SepAdtMinListLength, SepAdtValidateAuditBounds(), SepRegQueryHelper(), Status, and _SEP_AUDIT_BOUNDS::UpperBound.
Referenced by SepRmSetAuditEventWrkr().
NTSTATUS SepAdtInitializeCrashOnFail (VOID)
Definition at line 150 of file adtinit.c.
BOOLEAN SepAdtInitializePrivilegeAuditing (VOID)
Definition at line 209 of file adtinit.c.
NTSTATUS SepAdtMarshallAuditRecord (IN PSE_ADT_PARAMETER_ARRAY AuditParameters, OUT PSE_ADT_PARAMETER_ARRAY * MarshalledAuditParameters, OUT PSEP_RM_LSA_MEMORY_TYPE RecordMemoryType)
Definition at line 261 of file adtlog.c.
References _SE_ADT_PARAMETER_ARRAY_ENTRY::Address, ASSERT, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, FALSE, IsValidParameterCount, _UNICODE_STRING::Length, NULL, PAGED_CODE, PagedPool, PtrAlignSize, RtlCopyMemory, SE_ADT_PARAMETERS_SELF_RELATIVE, SeAdtParmTypeAccessMask, SeAdtParmTypeDateTime, SeAdtParmTypeDuration, SeAdtParmTypeFileSpec, SeAdtParmTypeGuid, SeAdtParmTypeHexInt64, SeAdtParmTypeHexUlong, SeAdtParmTypeLogonId, SeAdtParmTypeLuid, SeAdtParmTypeMessage, SeAdtParmTypeNoLogonId, SeAdtParmTypeNone, SeAdtParmTypeObjectTypes, SeAdtParmTypePrivs, SeAdtParmTypePtr, SeAdtParmTypeSid, SeAdtParmTypeSockAddr, SeAdtParmTypeString, SeAdtParmTypeTime, SeAdtParmTypeUlong, SepRmNoMemory, SepRmPagedPoolMemory, _RTL_TRACE_BLOCK::Size, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by SepAdtLogAuditRecord().
VOID SepAdtObjectReferenceAuditAlarm (IN PVOID Object, IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted)
Definition at line 2306 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, ExFreePool(), _OBJECT_NAME_INFORMATION::Name, NULL, ObjectNameInformation, ObjectTypeInformation, PAGED_CODE, RtlZeroMemory, SE_AUDITID_INDIRECT_REFERENCE, SE_CATEGID_DETAILED_TRACKING, SeAdtParmTypeNone, SepAdtLogAuditRecord(), SepQueryNameString(), SepQueryTypeString(), SepSetParmTypeAccessMask, SepSetParmTypeHexUlong, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, and SeSubsystemName.
Referenced by SeObjectReferenceAuditAlarm().
BOOLEAN SepAdtOpenObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID *HandleId OPTIONAL, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName OPTIONAL, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID, IN POLICY_AUDIT_EVENT_TYPE AuditType, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PACCESS_MASK GrantedAccessArray OPTIONAL)
Definition at line 910 of file sepaudit.c.
References _SE_ADT_OBJECT_TYPE::AccessMask, ARGUMENT_PRESENT, ASSERT, AuditCategoryDirectoryServiceAccess, AuditCategoryObjectAccess, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, ExAllocatePoolWithTag, ExFreePool(), _SE_ADT_OBJECT_TYPE::Flags, _SE_ADT_OBJECT_TYPE::Level, NT_SUCCESS, NULL, NullString, OBJECT_FAILURE_AUDIT, OBJECT_SUCCESS_AUDIT, _SE_ADT_OBJECT_TYPE::ObjectType, PAGED_CODE, PagedPool, PsGetCurrentProcess(), RtlZeroMemory, SE_ADT_OBJECT_ONLY, SE_AUDITID_OPEN_HANDLE, SE_AUDITID_OPEN_HANDLE_OBJECT_TYPE, SE_CATEGID_DS_ACCESS, SE_CATEGID_OBJECT_ACCESS, SeAdtParmTypeNone, SeLocateProcessImageName(), SepAdtLogAuditRecord(), SepSetParmTypeAccessMask, SepSetParmTypeFileSpec, SepSetParmTypeHexUlong, SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypeObjectTypes, SepSetParmTypePrivileges, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepSetParmTypeUlong, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, Status, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtOpenObjectAuditAlarm(), SeAuditHandleCreation(), SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SepAdtOpenObjectForDeleteAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName, IN PVOID * HandleId, IN PUNICODE_STRING CapturedObjectTypeName, IN PUNICODE_STRING CapturedObjectName, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN ACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess, IN PLUID OperationId, IN PPRIVILEGE_SET CapturedPrivileges OPTIONAL, IN BOOLEAN AccessGranted, IN HANDLE ProcessID)
Referenced by SeOpenObjectForDeleteAuditAlarm().
VOID SepAdtPrivilegedServiceAuditAlarm (IN PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, IN PUNICODE_STRING CapturedSubsystemName, IN PUNICODE_STRING CapturedServiceName, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
Definition at line 682 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryPrivilegeUse, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, NULL, PAGED_CODE, RtlZeroMemory, SE_AUDITID_PRIVILEGED_SERVICE, SE_CATEGID_PRIVILEGE_USE, SeAdtParmTypeNone, SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepFilterPrivilegeAudits(), SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePrivileges, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, and SeSubsystemName.
Referenced by NtPrivilegedServiceAuditAlarm(), and SePrivilegedServiceAuditAlarm().
BOOLEAN SepAdtPrivilegeObjectAuditAlarm (IN PUNICODE_STRING CapturedSubsystemName OPTIONAL, IN PVOID HandleId, IN PTOKEN ClientToken OPTIONAL, IN PTOKEN PrimaryToken, IN PVOID ProcessId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET CapturedPrivileges, IN BOOLEAN AccessGranted)
Definition at line 449 of file sepaudit.c.
References ARGUMENT_PRESENT, ASSERT, AuditCategoryPrivilegeUse, EVENTLOG_AUDIT_FAILURE, EVENTLOG_AUDIT_SUCCESS, FALSE, NULL, PAGED_CODE, RtlEqualSid(), RtlZeroMemory, SE_AUDITID_PRIVILEGED_OBJECT, SE_CATEGID_PRIVILEGE_USE, SeAdtParmTypeNone, SeLocalSystemSid, SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepFilterPrivilegeAudits(), SepSetParmTypeLogonId, SepSetParmTypeNoLogon, SepSetParmTypePrivileges, SepSetParmTypePtr, SepSetParmTypeSid, SepSetParmTypeString, SepTokenAuthenticationId, SepTokenUserSid, SeSubsystemName, TRUE, and UNREFERENCED_PARAMETER.
Referenced by NtOpenObjectAuditAlarm(), NtPrivilegeObjectAuditAlarm(), SeAuditHandleCreation(), SepAccessCheckAndAuditAlarm(), and SePrivilegeObjectAuditAlarm().
VOID SepAdtTraverseAuditAlarm (IN PLUID OperationID, IN PVOID DirectoryObject, IN PSID UserSid, IN LUID AuthenticationId, IN ACCESS_MASK DesiredAccess, IN PPRIVILEGE_SET Privileges OPTIONAL, IN BOOLEAN AccessGranted, IN BOOLEAN GenerateAudit, IN BOOLEAN GenerateAlarm)
VOID SepAuditFailed (IN NTSTATUS AuditStatus)
Definition at line 150 of file adtlog.c.
References ASSERT, CRASH_ON_AUDIT_FAIL_VALUE, FALSE, InitializeObjectAttributes, KeBugCheckEx(), KEY_SET_VALUE, KeyName, LSAP_ALLOW_ADIMIN_LOGONS_ONLY, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_DWORD, RtlInitUnicodeString(), SepCrashOnAuditFail, Status, STATUS_AUDIT_FAILED, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, ZwFlushKey(), ZwOpenKey(), and ZwSetValueKey().
Referenced by SeAddSaclToProcess(), SeDetailedAuditingWithToken(), SepAdtAuditThisEventWithContext(), SepAdtLogAuditRecord(), SepAuditAssignPrimaryToken(), and SepInitProcessAuditSd().
BOOLEAN SepInitializePrivilegeFilter (BOOLEAN Verbose)
Definition at line 4422 of file seaudit.c.
References SepFilterPrivilegesLong, SepFilterPrivilegesShort, and TRUE.
Referenced by SepAdtInitializePrivilegeAuditing().
Variable Documentation
GENERIC_MAPPING GenericMappingForMembershipCheck
Definition at line 182 of file seglobal.c.
Referenced by SepCheckTokenForCoreSystemSids().
BOOLEAN SepAdtAuditingEnabled
Definition at line 302 of file seglobal.c.
ULONG SepAdtCountEventsDiscarded
Definition at line 56 of file adtvars.c.
Referenced by SepAdtGenerateDiscardAudit(), and SepQueueWorkItem().
ULONG SepAdtCurrentListLength
Definition at line 50 of file adtvars.c.
Referenced by SepDequeueWorkItem(), and SepQueueWorkItem().
BOOLEAN SepAdtDiscardingAudits
Definition at line 62 of file adtvars.c.
Referenced by SepQueueWorkItem().
POLICY_AUDIT_LOG_INFO SepAdtLogInformation
Definition at line 28 of file adtp.h.
PKEVENT SepAdtLsaDeadEvent
Definition at line 75 of file adtvars.c.
Referenced by SepDequeueWorkItem(), SepQueueWorkItem(), and SepRmCommandServerThread().
ULONG SepAdtMaxListLength
Definition at line 47 of file adtvars.c.
Referenced by SepAdtInitializeBounds(), and SepQueueWorkItem().
ULONG SepAdtMinListLength
Definition at line 48 of file adtvars.c.
Referenced by SepAdtInitializeBounds(), and SepQueueWorkItem().
SEP_AUDIT_OPTIONS SepAuditOptions
Definition at line 68 of file adtvars.c.
Referenced by SepAdtCloseObjectAuditAlarm(), and SepAdtInitializeAuditingOptions().
BOOLEAN SepCrashOnAuditFail
Definition at line 309 of file seglobal.c.
Referenced by SepAdtInitializeCrashOnFail(), SepAdtLogAuditRecord(), and SepAuditFailed().
PSECURITY_DESCRIPTOR SepImportantProcessSd
Definition at line 176 of file seglobal.c.
Referenced by SepCheckTokenForCoreSystemSids(), and SepInitProcessAuditSd().
PSECURITY_DESCRIPTOR SepProcessAuditSd
Definition at line 160 of file seglobal.c.
Referenced by SeAddSaclToProcess(), and SepInitProcessAuditSd().