Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmworker.c File Reference
cmworker.c File Reference
#include "cmp.h"
Macros
#define ENABLE_LAZY_FLUSH_INTERVAL_IN_SECONDS 600
#define LAZY_FLUSH_TIMEOUT_IN_SECONDS 1
Functions
VOID CmpCmdHiveClose (PCMHIVE CmHive)
NTSTATUS CmpCmdHiveOpen (POBJECT_ATTRIBUTES FileAttributes, PSECURITY_CLIENT_CONTEXT ImpersonationContext, PBOOLEAN Allocate, PCMHIVE *NewHive, ULONG CheckFlags)
VOID CmpCmdInit (BOOLEAN SetupBoot)
NTSTATUS CmpCmdRenameHive (PCMHIVE CmHive, POBJECT_NAME_INFORMATION OldName, PUNICODE_STRING NewName, ULONG NameInfoLength)
VOID CmpDiskFullWarning (VOID)
VOID CmpDiskFullWarningWorker (IN PVOID WorkItem)
BOOLEAN CmpDoFlushNextHive (BOOLEAN ForceFlush, PBOOLEAN PostWarning, PULONG DirtyCount)
VOID CmpEnableLazyFlushDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID CmpInitializeHiveList (VOID)
VOID CmpLazyFlush (VOID)
VOID CmpLazyFlushDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID CmpLazyFlushWorker (IN PVOID Parameter)
VOID CmpShutdownWorkers (VOID)
VOID CmSetLazyFlushState (__in BOOLEAN Enable)
Variables
BOOLEAN CmpCannotWriteConfiguration
BOOLEAN CmpDiskFullWorkerPopupDisplayed
BOOLEAN CmpDontGrowLogFile = FALSE
KDPC CmpEnableLazyFlushDpc
KTIMER CmpEnableLazyFlushTimer
BOOLEAN CmpForceForceFlush = FALSE
LIST_ENTRY CmpHiveListHead
BOOLEAN CmpHoldLazyFlush = TRUE
ULONG CmpLazyFlushCount = 1
KDPC CmpLazyFlushDpc
ULONG CmpLazyFlushHiveCount = 7
ULONG CmpLazyFlushIntervalInSeconds = 5
BOOLEAN CmpLazyFlushPending = FALSE
KTIMER CmpLazyFlushTimer
WORK_QUEUE_ITEM CmpLazyWorkItem
HIVE_LIST_ENTRY CmpMachineHiveList []
BOOLEAN CmpNoWrite
BOOLEAN CmpProfileLoaded
PKPROCESS CmpSystemProcess
BOOLEAN CmpTrackHiveClose
BOOLEAN CmpWasSetupBoot
BOOLEAN HvShutdownComplete
UNICODE_STRING SystemHiveFullPathName
Macro Definition Documentation
#define ENABLE_LAZY_FLUSH_INTERVAL_IN_SECONDS 600
Definition at line 54 of file cmworker.c.
Referenced by CmpCmdInit().
#define LAZY_FLUSH_TIMEOUT_IN_SECONDS 1
Definition at line 49 of file cmworker.c.
Function Documentation
VOID CmpCmdHiveClose (PCMHIVE CmHive)
Definition at line 143 of file cmworker.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE_OR_HIVE_LOADING, CM_PAGED_CODE, CmCloseHandle, CmpTrackHiveClose, _HHIVE::DirtyFlag, FALSE, FileBasicInformation, _CMHIVE::FileHandles, HFILE_TYPE_MAX, HFILE_TYPE_PRIMARY, _CMHIVE::Hive, IoSetThreadHardErrorMode(), KeQuerySystemTime(), _FILE_BASIC_INFORMATION::LastAccessTime, _FILE_BASIC_INFORMATION::LastWriteTime, NT_SUCCESS, NULL, TRUE, ZwQueryInformationFile(), and ZwSetInformationFile().
Referenced by CmLoadKey(), CmShutdownSystem(), and CmUnloadKey().
NTSTATUS CmpCmdHiveOpen (POBJECT_ATTRIBUTES FileAttributes, PSECURITY_CLIENT_CONTEXT ImpersonationContext, PBOOLEAN Allocate, PCMHIVE * NewHive, ULONG CheckFlags)
Definition at line 369 of file cmworker.c.
References CM_PAGED_CODE, CmpInitHiveFromFile(), NT_SUCCESS, NULL, _OBJECT_ATTRIBUTES::ObjectName, PsRevertToSelf(), SeImpersonateClientEx(), Status, STATUS_ACCESS_DENIED, STATUS_ACCOUNT_DISABLED, STATUS_ACCOUNT_EXPIRED, STATUS_ACCOUNT_RESTRICTION, STATUS_NO_SUCH_USER, and STATUS_WRONG_PASSWORD.
Referenced by CmLoadKey().
VOID CmpCmdInit (BOOLEAN SetupBoot)
Definition at line 224 of file cmworker.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_PAGED_CODE, CmpEnableLazyFlushDpcRoutine(), CmpInitializeHiveList(), CmpLazyFlushDpcRoutine(), CmpLazyFlushWorker(), CmpMiniNTBoot, CmpNoWrite, CmpShareSystemHives, CmpWasSetupBoot, ENABLE_LAZY_FLUSH_INTERVAL_IN_SECONDS, ExInitializeWorkItem, FALSE, Int32x32To64, KeInitializeDpc(), KeInitializeTimer(), KeSetTimer(), NULL, _LARGE_INTEGER::QuadPart, and SECOND_MULT.
Referenced by NtInitializeRegistry().
NTSTATUS CmpCmdRenameHive (PCMHIVE CmHive, POBJECT_NAME_INFORMATION OldName, PUNICODE_STRING NewName, ULONG NameInfoLength)
Definition at line 291 of file cmworker.c.
References ASSERT_PASSIVE_LEVEL, _UNICODE_STRING::Buffer, CM_PAGED_CODE, ExAllocatePool, ExFreePool(), FALSE, _CMHIVE::FileHandles, _FILE_RENAME_INFORMATION::FileName, _FILE_RENAME_INFORMATION::FileNameLength, FileRenameInformation, Handle, HFILE_TYPE_PRIMARY, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObjectNameInformation, PagedPool, _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, ZwQueryObject(), and ZwSetInformationFile().
VOID CmpDiskFullWarning (VOID)
Definition at line 701 of file cmworker.c.
References CmpCannotWriteConfiguration, CmpDiskFullWarningWorker(), CmpDiskFullWorkerPopupDisplayed, CmpProfileLoaded, DelayedWorkQueue, ExAllocatePool, ExInitializeWorkItem, ExQueueWorkItem(), ExReadyForErrors, NonPagedPool, NULL, and TRUE.
Referenced by CmpLazyFlushWorker(), and CmpLoadHiveThread().
VOID CmpDiskFullWarningWorker (IN PVOID WorkItem)
Definition at line 663 of file cmworker.c.
References ExFreePool(), ExRaiseHardError(), NULL, OptionOk, Status, and STATUS_DISK_FULL.
Referenced by CmpDiskFullWarning().
BOOLEAN CmpDoFlushNextHive (BOOLEAN ForceFlush, PBOOLEAN PostWarning, PULONG DirtyCount)
Definition at line 3357 of file cmapi.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CmKdPrintEx, CML_IO, CmpDoQueueLateUnloadWorker(), CmpFixHiveUsageCount(), CmpHiveListHead, CmpLazyFlushCount, CmpLazyFlushHiveCount, CmpLockHiveFlusherExclusive, CmpLockHiveListShared, CmpNoWrite, CmpUnlockHiveFlusher, CmpUnlockHiveList, CONTAINING_RECORD, _HHIVE::DirtyCount, DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, _LIST_ENTRY::Flink, _CMHIVE::FlushCount, _CMHIVE::Hive, HIVE_NOLAZYFLUSH, HIVE_VOLATILE, _HHIVE::HiveFlags, HvHiveWillShrink(), HvSyncHive(), IsHiveFrozen, NT_SUCCESS, Stable, Status, TRUE, and _CMHIVE::UseCount.
Referenced by CmpLazyFlushWorker().
VOID CmpEnableLazyFlushDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 491 of file cmworker.c.
References CmpHoldLazyFlush, FALSE, and UNREFERENCED_PARAMETER.
Referenced by CmpCmdInit().
VOID CmpInitializeHiveList (VOID)
Definition at line 687 of file cmsysini.c.
References ASSERT, ASSERT_CM_LOCK_OWNED_EXCLUSIVE, BAD_CORE_HIVE, BAD_HIVE_LIST, BAD_SYSTEM_CONFIG_INFO, _STRING::Buffer, _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_NUMBER_OF_MACHINE_HIVES, CM_PAGED_CODE, CmKdPrintEx, CML_BUGCHECK, CML_INIT, CmpAddToHiveFileList(), CmpCreatePerfKeys(), CmpHiveRootSecurityDescriptor(), CmpLinkHiveToMaster(), CmpLinkKeyToHive(), CmpLoadHiveThread(), CmpNoMasterCreates, CmpNoWrite, CmpShareSystemHives, CmpSpecialBootCondition, CONFIG_LIST_FAILED, DPFLTR_CONFIG_ID, Executive, ExFreePool(), FALSE, _HIVE_LIST_ENTRY::HHiveFlags, HIVE_VOLATILE, HvSyncHive(), INIT_REGISTRY_MASTERPATH, INIT_SYSTEMROOT_HIVEPATH, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _STRING::Length, _UNICODE_STRING::Length, MAX_NAME, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, PsCreateSystemThread(), RtlAppendStringToString(), RtlInitUnicodeString(), Status, STATUS_SUCCESS, SynchronizationEvent, THREAD_ALL_ACCESS, TRUE, and ZwClose().
Referenced by CmpCmdInit().
VOID CmpLazyFlush (VOID)
Definition at line 446 of file cmworker.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_IO, CmpHoldLazyFlush, CmpLazyFlushIntervalInSeconds, CmpNoWrite, DPFLTR_CONFIG_ID, Int32x32To64, KeSetTimer(), _LARGE_INTEGER::QuadPart, and SECOND_MULT.
Referenced by CmpLazyFlushWorker(), HvMarkDirty(), and NtInitializeRegistry().
VOID CmpLazyFlushDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 508 of file cmworker.c.
References CmKdPrintEx, CML_IO, CmpHoldLazyFlush, CmpLazyFlushPending, DelayedWorkQueue, DPFLTR_CONFIG_ID, ExQueueWorkItem(), TRUE, and UNREFERENCED_PARAMETER.
Referenced by CmpCmdInit().
VOID CmpLazyFlushWorker (IN PVOID Parameter)
Definition at line 557 of file cmworker.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_IO, CmpCannotWriteConfiguration, CmpDiskFullWarning(), CmpDoFlushNextHive(), CmpForceForceFlush, CmpHoldLazyFlush, CmpLazyFlush(), CmpLazyFlushCount, CmpLazyFlushPending, CmpLockRegistry(), CmpLockRegistryExclusive(), CmpUnlockRegistry(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, ENTER_FLUSH_MODE, EXIT_FLUSH_MODE, FALSE, HvShutdownComplete, InterlockedIncrement, LOCK_HIVE_LOAD, TRUE, UNLOCK_HIVE_LOAD, and UNREFERENCED_PARAMETER.
Referenced by CmpCmdInit().
VOID CmpShutdownWorkers (VOID)
Definition at line 740 of file cmworker.c.
References CM_PAGED_CODE, and KeCancelTimer().
Referenced by CmShutdownSystem().
VOID CmSetLazyFlushState (__in BOOLEAN Enable)
Definition at line 765 of file cmworker.c.
References CM_PAGED_CODE, CmpDontGrowLogFile, and CmpHoldLazyFlush.
Variable Documentation
BOOLEAN CmpCannotWriteConfiguration
Definition at line 52 of file cmdat2.c.
Referenced by CmpDiskFullWarning(), and CmpLazyFlushWorker().
BOOLEAN CmpDiskFullWorkerPopupDisplayed
Definition at line 51 of file cmdat2.c.
Referenced by CmpDiskFullWarning().
BOOLEAN CmpDontGrowLogFile = FALSE
Definition at line 67 of file cmworker.c.
Referenced by CmSetLazyFlushState(), and HvpGrowLog1().
KDPC CmpEnableLazyFlushDpc
Definition at line 62 of file cmworker.c.
KTIMER CmpEnableLazyFlushTimer
Definition at line 61 of file cmworker.c.
BOOLEAN CmpForceForceFlush = FALSE
Definition at line 65 of file cmworker.c.
Referenced by CmpLazyFlushWorker().
LIST_ENTRY CmpHiveListHead
Definition at line 312 of file cmdat.c.
Referenced by CmIsFileLoadedAsHive(), CmpDoFlushAll(), CmpDoFlushNextHive(), CmpFreeAllMemory(), CmPrefetchHivePages(), CmpUnmapUnusedViews(), and CmShutdownSystem().
BOOLEAN CmpHoldLazyFlush = TRUE
Definition at line 66 of file cmworker.c.
Referenced by CmpDereferenceKeyControlBlockWithLock(), CmpEnableLazyFlushDpcRoutine(), CmpLazyFlush(), CmpLazyFlushDpcRoutine(), CmpLazyFlushWorker(), CmSetLazyFlushState(), and NtInitializeRegistry().
ULONG CmpLazyFlushCount = 1
Definition at line 554 of file cmworker.c.
Referenced by CmpDoFlushNextHive(), and CmpLazyFlushWorker().
KDPC CmpLazyFlushDpc
Definition at line 58 of file cmworker.c.
ULONG CmpLazyFlushHiveCount = 7
Definition at line 42 of file cmworker.c.
Referenced by CmpDoFlushNextHive().
ULONG CmpLazyFlushIntervalInSeconds = 5
Definition at line 38 of file cmworker.c.
Referenced by CmpLazyFlush().
BOOLEAN CmpLazyFlushPending = FALSE
Definition at line 64 of file cmworker.c.
Referenced by CmpLazyFlushDpcRoutine(), and CmpLazyFlushWorker().
KTIMER CmpLazyFlushTimer
Definition at line 57 of file cmworker.c.
WORK_QUEUE_ITEM CmpLazyWorkItem
Definition at line 59 of file cmworker.c.
HIVE_LIST_ENTRY CmpMachineHiveList[]
Definition at line 284 of file cmdat.c.
BOOLEAN CmpNoWrite
Definition at line 330 of file cmdat.c.
Referenced by CmpCmdInit(), and CmpLazyFlush().
BOOLEAN CmpProfileLoaded
Definition at line 62 of file cmdat2.c.
Referenced by CmpDiskFullWarning().
PKPROCESS CmpSystemProcess
Definition at line 56 of file cmworker.c.
BOOLEAN CmpTrackHiveClose
Definition at line 56 of file cmmapvw.c.
Referenced by CmpCmdHiveClose().
BOOLEAN CmpWasSetupBoot
Definition at line 363 of file cmdat.c.
Referenced by CmpCmdInit().
BOOLEAN HvShutdownComplete
Definition at line 71 of file cmdat2.c.
Referenced by CmpLazyFlushWorker().
UNICODE_STRING SystemHiveFullPathName
Definition at line 296 of file cmdat.c.