Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/io.h File Reference
io.h File Reference
#include "pshpack4.h"
#include "poppack.h"
Data Structures
struct _BOOT_LOG_RECORD
struct _BOOTDISK_INFORMATION
struct _BOOTDISK_INFORMATION_EX
struct _CONFIGURATION_INFORMATION
struct _CONTROLLER_OBJECT
struct _DEVICE_CAPABILITIES
struct _DEVICE_HANDLER_OBJECT
struct _DEVICE_RELATIONS
struct _DEVOBJ_EXTENSION
struct _DISK_SIGNATURE
struct _DRIVER_EXTENSION
struct _DRIVER_OBJECT
struct _DUMP_INITIALIZATION_CONTEXT
struct _DUMP_STACK_CONTEXT
struct _FAST_IO_DISPATCH
struct _FILE_OBJECT
struct _FS_FILTER_CALLBACK_DATA
struct _FS_FILTER_CALLBACKS
union _FS_FILTER_PARAMETERS
struct _INTERFACE
struct _IO_CLIENT_EXTENSION
struct _IO_COMPLETION_CONTEXT
struct _IO_CSQ
struct _IO_CSQ_IRP_CONTEXT
struct _IO_INTERRUPT_STRUCTURE
struct _IO_REMOVE_LOCK
struct _IO_REMOVE_LOCK_COMMON_BLOCK
struct _IO_REMOVE_LOCK_DBG_BLOCK
struct _IO_SECURITY_CONTEXT
struct _IO_STACK_LOCATION
struct _IO_TIMER
struct _MAILSLOT_CREATE_PARAMETERS
struct _NAMED_PIPE_CREATE_PARAMETERS
struct _POWER_SEQUENCE
struct _SECTION_OBJECT_POINTERS
struct _SHARE_ACCESS
struct _VPB
struct _WAIT_CONTEXT_BLOCK
struct DUMP_STACK_IMAGE
Macros
#define _WMIKM_
#define DO_BUFFERED_IO 0x00000004
#define DO_BUS_ENUMERATED_DEVICE 0x00001000
#define DO_DEVICE_HAS_NAME 0x00000040
#define DO_DEVICE_INITIALIZING 0x00000080
#define DO_DIRECT_IO 0x00000010
#define DO_EXCLUSIVE 0x00000008
#define DO_LONG_TERM_REQUESTS 0x00000200
#define DO_LOW_PRIORITY_FILESYSTEM 0x00010000
#define DO_MAP_IO_BUFFER 0x00000020
#define DO_NEVER_LAST_DEVICE 0x00000400
#define DO_POWER_INRUSH 0x00004000
#define DO_POWER_NOOP 0x00008000
#define DO_POWER_PAGABLE 0x00002000
#define DO_SHUTDOWN_REGISTERED 0x00000800
#define DO_SYSTEM_BOOT_PARTITION 0x00000100
#define DO_VERIFY_VOLUME 0x00000002
#define DO_XIP 0x00020000
#define DOE_DELETE_PENDING 0x00000002
#define DOE_REMOVE_PENDING 0x00000004
#define DOE_REMOVE_PROCESSED 0x00000008
#define DOE_START_PENDING 0x00000010
#define DOE_STARTIO_CANCELABLE 0x00000080
#define DOE_STARTIO_DEFERRED 0x00000100
#define DOE_STARTIO_NO_CANCEL 0x00000200
#define DOE_STARTIO_REQUESTED 0x00000020
#define DOE_STARTIO_REQUESTED_BYKEY 0x00000040
#define DOE_UNLOAD_PENDING 0x00000001
#define DRVO_BASE_FILESYSTEM_DRIVER 0x00000080
#define DRVO_BOOTREINIT_REGISTERED 0x00000020
#define DRVO_BUILTIN_DRIVER 0x00000004
#define DRVO_INITIALIZED 0x00000010
#define DRVO_LEGACY_DRIVER 0x00000002
#define DRVO_LEGACY_RESOURCES 0x00000040
#define DRVO_REINIT_REGISTERED 0x00000008
#define DRVO_UNLOAD_INVOKED 0x00000001
#define FO_ALERTABLE_IO 0x00000004
#define FO_CACHE_SUPPORTED 0x00000040
#define FO_CLEANUP_COMPLETE 0x00004000
#define FO_DELETE_ON_CLOSE 0x00010000
#define FO_DIRECT_DEVICE_OPEN 0x00000800
#define FO_FILE_FAST_IO_READ 0x00080000
#define FO_FILE_MODIFIED 0x00001000
#define FO_FILE_OBJECT_HAS_EXTENSION 0x00800000
#define FO_FILE_OPEN 0x00000001
#define FO_FILE_OPEN_CANCELLED 0x00200000
#define FO_FILE_SIZE_CHANGED 0x00002000
#define FO_GENERATE_AUDIT_ON_CLOSE 0x00000400
#define FO_HANDLE_CREATED 0x00040000
#define FO_MAILSLOT 0x00000200
#define FO_NAMED_PIPE 0x00000080
#define FO_NO_INTERMEDIATE_BUFFERING 0x00000008
#define FO_OPENED_CASE_SENSITIVE 0x00020000
#define FO_RANDOM_ACCESS 0x00100000
#define FO_REMOTE_ORIGIN 0x01000000
#define FO_SEQUENTIAL_ONLY 0x00000020
#define FO_STREAM_FILE 0x00000100
#define FO_SYNCHRONOUS_IO 0x00000002
#define FO_TEMPORARY_FILE 0x00008000
#define FO_VOLUME_OPEN 0x00400000
#define FO_WRITE_THROUGH 0x00000010
#define FS_FILTER_ACQUIRE_FOR_CC_FLUSH (UCHAR)-5
#define FS_FILTER_ACQUIRE_FOR_MOD_WRITE (UCHAR)-3
#define FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION (UCHAR)-1
#define FS_FILTER_RELEASE_FOR_CC_FLUSH (UCHAR)-6
#define FS_FILTER_RELEASE_FOR_MOD_WRITE (UCHAR)-4
#define FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION (UCHAR)-2
#define IO_ATTACH_DEVICE 0x0400
#define IO_ATTACH_DEVICE_API 0x80000000
#define IO_CHECK_CREATE_PARAMETERS 0x0200
#define IO_DUMP_COMMON_BUFFER_SIZE 0x2000
#define IO_DUMP_MAX_MDL_PAGES 8
#define IO_DUMP_MEMORY_BLOCK_PAGES 16
#define IO_DUMP_WRITE_DATA_PAGES 2
#define IO_DUMP_WRITE_DATA_SIZE (IO_DUMP_WRITE_DATA_PAGES << PAGE_SHIFT)
#define IO_DUMP_WRITE_FINISH 3
#define IO_DUMP_WRITE_FULFILL 0
#define IO_DUMP_WRITE_INIT 4
#define IO_DUMP_WRITE_RESUME 2
#define IO_DUMP_WRITE_START 1
#define IO_FILE_OBJECT_NON_PAGED_POOL_CHARGE 64
#define IO_FILE_OBJECT_PAGED_POOL_CHARGE 1024
#define IO_FORCE_ACCESS_CHECK 0x0001
#define IO_IGNORE_SHARE_ACCESS_CHECK 0x0800
#define IO_NO_PARAMETER_CHECKING 0x0100
#define IO_OPEN_PAGING_FILE 0x0002
#define IO_OPEN_TARGET_DIRECTORY 0x0004
#define IO_REMOUNT 0x1
#define IO_REPARSE 0x0
#define IO_TYPE_ADAPTER 0x00000001
#define IO_TYPE_CONTROLLER 0x00000002
#define IO_TYPE_CSQ 2
#define IO_TYPE_CSQ_EX 3
#define IO_TYPE_CSQ_IRP_CONTEXT 1
#define IO_TYPE_DEVICE 0x00000003
#define IO_TYPE_DEVICE_OBJECT_EXTENSION 0x0000000d
#define IO_TYPE_DRIVER 0x00000004
#define IO_TYPE_ERROR_LOG 0x0000000b
#define IO_TYPE_ERROR_MESSAGE 0x0000000c
#define IO_TYPE_FILE 0x00000005
#define IO_TYPE_IRP 0x00000006
#define IO_TYPE_MASTER_ADAPTER 0x00000007
#define IO_TYPE_OPEN_PACKET 0x00000008
#define IO_TYPE_TIMER 0x00000009
#define IO_TYPE_VPB 0x0000000a
#define IoAcquireRemoveLock(RemoveLock, Tag) IoAcquireRemoveLockEx(RemoveLock, Tag, __FILE__, __LINE__, sizeof (IO_REMOVE_LOCK))
#define IoAssignArcName(ArcName, DeviceName)
#define IoCallDriver(a, b) IofCallDriver(a,b)
#define IoCompleteRequest(a, b) IofCompleteRequest(a,b)
#define IoCopyCurrentIrpStackLocationToNext(Irp)
#define IoDeassignArcName(ArcName)
#define IoForwardAndCatchIrp IoForwardIrpSynchronously
#define IoGetCurrentIrpStackLocation(Irp) ((Irp)->Tail.Overlay.CurrentStackLocation)
#define IoGetFunctionCodeFromCtlCode(ControlCode)
#define IoGetNextIrpStackLocation(Irp)
#define IoInitializeDpcRequest(DeviceObject, DpcRoutine)
#define IoInitializeRemoveLock(Lock, Tag, Maxmin, HighWater) IoInitializeRemoveLockEx (Lock, Tag, Maxmin, HighWater, sizeof (IO_REMOVE_LOCK))
#define IoInitializeThreadedDpcRequest(DeviceObject, DpcRoutine)
#define IoIsErrorUserInduced(Status)
#define IoIsFileOpenedExclusively(FileObject)
#define IoMarkIrpPending(Irp)
#define IoReleaseRemoveLock(RemoveLock, Tag) IoReleaseRemoveLockEx(RemoveLock, Tag, sizeof (IO_REMOVE_LOCK))
#define IoReleaseRemoveLockAndWait(RemoveLock, Tag) IoReleaseRemoveLockAndWaitEx(RemoveLock, Tag, sizeof (IO_REMOVE_LOCK))
#define IoRequestDpc(DeviceObject, Irp, Context)
#define IoSetCancelRoutine(Irp, NewCancelRoutine)
#define IoSetCompletionRoutine(Irp, Routine, CompletionContext, Success, Error, Cancel)
#define IoSetNextIrpStackLocation(Irp)
#define IoSizeOfIrp(StackSize) ((USHORT) (sizeof(IRP) + ((StackSize) * (sizeof(IO_STACK_LOCATION)))))
#define IoSkipCurrentIrpStackLocation(Irp)
#define IoWMIDeviceObjectToProviderId(DeviceObject) ((ULONG)(DeviceObject))
#define IRP_ALLOCATED_FIXED_SIZE 0x04
#define IRP_ALLOCATED_MUST_SUCCEED 0x02
#define IRP_ASSOCIATED_IRP 0x00000008
#define IRP_BUFFERED_IO 0x00000010
#define IRP_CLOSE_OPERATION 0x00000400
#define IRP_CREATE_OPERATION 0x00000080
#define IRP_DEALLOCATE_BUFFER 0x00000020
#define IRP_DEFER_IO_COMPLETION 0x00000800
#define IRP_HIGH_PRIORITY_PAGING_IO 0x00008000
#define IRP_HOLD_DEVICE_QUEUE 0x00002000
#define IRP_INPUT_OPERATION 0x00000040
#define IRP_LOOKASIDE_ALLOCATION 0x08
#define IRP_MJ_CLEANUP 0x12
#define IRP_MJ_CLOSE 0x02
#define IRP_MJ_CREATE 0x00
#define IRP_MJ_CREATE_MAILSLOT 0x13
#define IRP_MJ_CREATE_NAMED_PIPE 0x01
#define IRP_MJ_DEVICE_CHANGE 0x18
#define IRP_MJ_DEVICE_CONTROL 0x0e
#define IRP_MJ_DIRECTORY_CONTROL 0x0c
#define IRP_MJ_FILE_SYSTEM_CONTROL 0x0d
#define IRP_MJ_FLUSH_BUFFERS 0x09
#define IRP_MJ_INTERNAL_DEVICE_CONTROL 0x0f
#define IRP_MJ_LOCK_CONTROL 0x11
#define IRP_MJ_MAXIMUM_FUNCTION 0x1b
#define IRP_MJ_PNP 0x1b
#define IRP_MJ_PNP_POWER IRP_MJ_PNP
#define IRP_MJ_POWER 0x16
#define IRP_MJ_QUERY_EA 0x07
#define IRP_MJ_QUERY_INFORMATION 0x05
#define IRP_MJ_QUERY_QUOTA 0x19
#define IRP_MJ_QUERY_SECURITY 0x14
#define IRP_MJ_QUERY_VOLUME_INFORMATION 0x0a
#define IRP_MJ_READ 0x03
#define IRP_MJ_SCSI IRP_MJ_INTERNAL_DEVICE_CONTROL
#define IRP_MJ_SET_EA 0x08
#define IRP_MJ_SET_INFORMATION 0x06
#define IRP_MJ_SET_QUOTA 0x1a
#define IRP_MJ_SET_SECURITY 0x15
#define IRP_MJ_SET_VOLUME_INFORMATION 0x0b
#define IRP_MJ_SHUTDOWN 0x10
#define IRP_MJ_SYSTEM_CONTROL 0x17
#define IRP_MJ_WRITE 0x04
#define IRP_MN_CANCEL_REMOVE_DEVICE 0x03
#define IRP_MN_CANCEL_STOP_DEVICE 0x06
#define IRP_MN_CHANGE_SINGLE_INSTANCE 0x02
#define IRP_MN_CHANGE_SINGLE_ITEM 0x03
#define IRP_MN_COMPLETE 0x04
#define IRP_MN_COMPLETE_MDL (IRP_MN_COMPLETE | IRP_MN_MDL)
#define IRP_MN_COMPLETE_MDL_DPC (IRP_MN_COMPLETE_MDL | IRP_MN_DPC)
#define IRP_MN_COMPRESSED 0x08
#define IRP_MN_DEVICE_USAGE_NOTIFICATION 0x16
#define IRP_MN_DISABLE_COLLECTION 0x07
#define IRP_MN_DISABLE_EVENTS 0x05
#define IRP_MN_DPC 0x01
#define IRP_MN_EJECT 0x11
#define IRP_MN_ENABLE_COLLECTION 0x06
#define IRP_MN_ENABLE_EVENTS 0x04
#define IRP_MN_EXECUTE_METHOD 0x09
#define IRP_MN_FILTER_RESOURCE_REQUIREMENTS 0x0D
#define IRP_MN_KERNEL_CALL 0x04
#define IRP_MN_LOAD_FILE_SYSTEM 0x03
#define IRP_MN_LOCK 0x01
#define IRP_MN_MDL 0x02
#define IRP_MN_MDL_DPC (IRP_MN_MDL | IRP_MN_DPC)
#define IRP_MN_MOUNT_VOLUME 0x01
#define IRP_MN_NORMAL 0x00
#define IRP_MN_NOTIFY_CHANGE_DIRECTORY 0x02
#define IRP_MN_POWER_SEQUENCE 0x01
#define IRP_MN_QUERY_ALL_DATA 0x00
#define IRP_MN_QUERY_BUS_INFORMATION 0x15
#define IRP_MN_QUERY_CAPABILITIES 0x09
#define IRP_MN_QUERY_DEVICE_RELATIONS 0x07
#define IRP_MN_QUERY_DEVICE_TEXT 0x0C
#define IRP_MN_QUERY_DIRECTORY 0x01
#define IRP_MN_QUERY_ID 0x13
#define IRP_MN_QUERY_INTERFACE 0x08
#define IRP_MN_QUERY_LEGACY_BUS_INFORMATION 0x18
#define IRP_MN_QUERY_PNP_DEVICE_STATE 0x14
#define IRP_MN_QUERY_POWER 0x03
#define IRP_MN_QUERY_REMOVE_DEVICE 0x01
#define IRP_MN_QUERY_RESOURCE_REQUIREMENTS 0x0B
#define IRP_MN_QUERY_RESOURCES 0x0A
#define IRP_MN_QUERY_SINGLE_INSTANCE 0x01
#define IRP_MN_QUERY_STOP_DEVICE 0x05
#define IRP_MN_READ_CONFIG 0x0F
#define IRP_MN_REGINFO 0x08
#define IRP_MN_REGINFO_EX 0x0b
#define IRP_MN_REMOVE_DEVICE 0x02
#define IRP_MN_SCSI_CLASS 0x01
#define IRP_MN_SET_LOCK 0x12
#define IRP_MN_SET_POWER 0x02
#define IRP_MN_SET_TRACE_NOTIFY 0x0A
#define IRP_MN_START_DEVICE 0x00
#define IRP_MN_STOP_DEVICE 0x04
#define IRP_MN_SURPRISE_REMOVAL 0x17
#define IRP_MN_TRACK_LINK 0x04
#define IRP_MN_UNLOCK_ALL 0x03
#define IRP_MN_UNLOCK_ALL_BY_KEY 0x04
#define IRP_MN_UNLOCK_SINGLE 0x02
#define IRP_MN_USER_FS_REQUEST 0x00
#define IRP_MN_VERIFY_VOLUME 0x02
#define IRP_MN_WAIT_WAKE 0x00
#define IRP_MN_WRITE_CONFIG 0x10
#define IRP_MOUNT_COMPLETION 0x00000002
#define IRP_NOCACHE 0x00000001
#define IRP_OB_QUERY_NAME 0x00001000
#define IRP_PAGING_IO 0x00000002
#define IRP_QUOTA_CHARGED 0x01
#define IRP_READ_OPERATION 0x00000100
#define IRP_RETRY_IO_COMPLETION 0x00004000
#define IRP_SET_USER_EVENT IRP_CLOSE_OPERATION
#define IRP_SYNCHRONOUS_API 0x00000004
#define IRP_SYNCHRONOUS_PAGING_IO 0x00000040
#define IRP_VERIFIER_MASK 0xC0000000
#define IRP_WRITE_OPERATION 0x00000200
#define MAXIMUM_VOLUME_LABEL_LENGTH (32 * sizeof(WCHAR))
#define PNP_DEVICE_DISABLED 0x00000001
#define PNP_DEVICE_DONT_DISPLAY_IN_UI 0x00000002
#define PNP_DEVICE_FAILED 0x00000004
#define PNP_DEVICE_NOT_DISABLEABLE 0x00000020
#define PNP_DEVICE_REMOVED 0x00000008
#define PNP_DEVICE_RESOURCE_REQUIREMENTS_CHANGED 0x00000010
#define POINTER_ALIGNMENT
#define SL_ALLOW_RAW_MOUNT 0x01
#define SL_CASE_SENSITIVE 0x80
#define SL_ERROR_RETURNED 0x02
#define SL_EXCLUSIVE_LOCK 0x02
#define SL_FAIL_IMMEDIATELY 0x01
#define SL_FORCE_ACCESS_CHECK 0x01
#define SL_FT_SEQUENTIAL_WRITE 0x08
#define SL_INDEX_SPECIFIED 0x04
#define SL_INVOKE_ON_CANCEL 0x20
#define SL_INVOKE_ON_ERROR 0x80
#define SL_INVOKE_ON_SUCCESS 0x40
#define SL_KEY_SPECIFIED 0x01
#define SL_OPEN_PAGING_FILE 0x02
#define SL_OPEN_TARGET_DIRECTORY 0x04
#define SL_OVERRIDE_VERIFY_VOLUME 0x02
#define SL_PENDING_RETURNED 0x01
#define SL_READ_ACCESS_GRANTED 0x01
#define SL_RESTART_SCAN 0x01
#define SL_RETURN_SINGLE_ENTRY 0x02
#define SL_WATCH_TREE 0x01
#define SL_WRITE_ACCESS_GRANTED 0x04
#define SL_WRITE_THROUGH 0x04
#define STATUS_CONTINUE_COMPLETION STATUS_SUCCESS
#define VPB_LOCKED 0x00000002
#define VPB_MOUNTED 0x00000001
#define VPB_PERSISTENT 0x00000004
#define VPB_RAW_MOUNT 0x00000010
#define VPB_REMOVE_PENDING 0x00000008
#define WDM_MAJORVERSION 0x01
#define WDM_MINORVERSION 0x30
#define WMIREG_ACTION_BLOCK_IRPS 5
#define WMIREG_ACTION_DEREGISTER 2
#define WMIREG_ACTION_REGISTER 1
#define WMIREG_ACTION_REREGISTER 3
#define WMIREG_ACTION_UPDATE_GUIDS 4
#define WMIREG_FLAG_CALLBACK 0x80000000
#define WMIREG_FLAG_TRACE_NOTIFY_MASK 0x00F00000
#define WMIREG_FLAG_TRACE_PROVIDER 0x00010000
#define WMIREG_NOTIFY_DISK_IO 1 << 20
#define WMIREG_NOTIFY_TDI_IO 2 << 20
#define WMIREG_NOTIFY_VOLMGR_IO 3 << 20
#define WMIREGISTER 0
#define WMIUPDATE 1
Typedefs
typedef struct _BOOT_LOG_RECORD BOOT_LOG_RECORD
typedef struct _BOOTDISK_INFORMATION BOOTDISK_INFORMATION
typedef struct _BOOTDISK_INFORMATION_EX BOOTDISK_INFORMATION_EX
typedef struct _CONFIGURATION_INFORMATION CONFIGURATION_INFORMATION
typedef struct _CONTROLLER_OBJECT CONTROLLER_OBJECT
typedef enum _CRASHDUMP_CONFIGURATION CRASHDUMP_CONFIGURATION
typedef enum _CREATE_FILE_TYPE CREATE_FILE_TYPE
typedef struct _DEVICE_CAPABILITIES DEVICE_CAPABILITIES
typedef struct _DEVICE_HANDLER_OBJECT DEVICE_HANDLER_OBJECT
typedef enum _DEVICE_RELATION_TYPE DEVICE_RELATION_TYPE
typedef struct _DEVICE_RELATIONS DEVICE_RELATIONS
typedef enum _DEVICE_USAGE_NOTIFICATION_TYPE DEVICE_USAGE_NOTIFICATION_TYPE
typedef struct _DEVOBJ_EXTENSION DEVOBJ_EXTENSION
typedef struct _DISK_SIGNATURE DISK_SIGNATURE
typedef struct _DRIVER_EXTENSION DRIVER_EXTENSION
typedef struct _DRIVER_OBJECT DRIVER_OBJECT
typedef struct _DUMP_INITIALIZATION_CONTEXT DUMP_INITIALIZATION_CONTEXT
typedef struct _DUMP_STACK_CONTEXT DUMP_STACK_CONTEXT
typedef struct DUMP_STACK_IMAGE DUMP_STACK_IMAGE
typedef struct _FAST_IO_DISPATCH FAST_IO_DISPATCH
typedef struct _FILE_OBJECT FILE_OBJECT
typedef struct _FS_FILTER_CALLBACK_DATA FS_FILTER_CALLBACK_DATA
typedef struct _FS_FILTER_CALLBACKS FS_FILTER_CALLBACKS
typedef union _FS_FILTER_PARAMETERS FS_FILTER_PARAMETERS
typedef enum _FS_FILTER_SECTION_SYNC_TYPE FS_FILTER_SECTION_SYNC_TYPE
typedef struct _INTERFACE INTERFACE
typedef enum _IO_ALLOCATION_ACTION IO_ALLOCATION_ACTION
typedef struct _IO_CLIENT_EXTENSION IO_CLIENT_EXTENSION
typedef struct _IO_COMPLETION_CONTEXT IO_COMPLETION_CONTEXT
typedef enum _IO_COMPLETION_ROUTINE_RESULT IO_COMPLETION_ROUTINE_RESULT
typedef struct _IO_CSQ IO_CSQ
typedef struct _IO_CSQ_IRP_CONTEXT IO_CSQ_IRP_CONTEXT
typedef struct _IO_INTERRUPT_STRUCTURE IO_INTERRUPT_STRUCTURE
typedef enum _IO_PAGING_PRIORITY IO_PAGING_PRIORITY
typedef enum _IO_QUERY_DEVICE_DATA_FORMAT IO_QUERY_DEVICE_DATA_FORMAT
typedef struct _IO_REMOVE_LOCK IO_REMOVE_LOCK
typedef struct _IO_REMOVE_LOCK_COMMON_BLOCK IO_REMOVE_LOCK_COMMON_BLOCK
typedef struct _IO_REMOVE_LOCK_DBG_BLOCK IO_REMOVE_LOCK_DBG_BLOCK
typedef struct _IO_SECURITY_CONTEXT IO_SECURITY_CONTEXT
typedef struct _IO_STACK_LOCATION IO_STACK_LOCATION
typedef struct _IO_TIMER IO_TIMER
typedef struct _MAILSLOT_CREATE_PARAMETERS MAILSLOT_CREATE_PARAMETERS
typedef struct _NAMED_PIPE_CREATE_PARAMETERS NAMED_PIPE_CREATE_PARAMETERS
typedef struct _ADAPTER_OBJECT * PADAPTER_OBJECT
typedef struct _BOOT_LOG_RECORD * PBOOT_LOG_RECORD
typedef struct _BOOTDISK_INFORMATION * PBOOTDISK_INFORMATION
typedef struct _BOOTDISK_INFORMATION_EX * PBOOTDISK_INFORMATION_EX
typedef enum BUS_QUERY_ID_TYPE * PBUS_QUERY_ID_TYPE
typedef struct _CONFIGURATION_INFORMATION * PCONFIGURATION_INFORMATION
typedef struct _CONTROLLER_OBJECT * PCONTROLLER_OBJECT
typedef struct _DEVICE_CAPABILITIES * PDEVICE_CAPABILITIES
typedef struct _DEVICE_HANDLER_OBJECT * PDEVICE_HANDLER_OBJECT
typedef struct _DEVICE_OBJECT * PDEVICE_OBJECT
typedef enum _DEVICE_RELATION_TYPE * PDEVICE_RELATION_TYPE
typedef struct _DEVICE_RELATIONS * PDEVICE_RELATIONS
typedef enum DEVICE_TEXT_TYPE * PDEVICE_TEXT_TYPE
typedef struct _DEVOBJ_EXTENSION * PDEVOBJ_EXTENSION
typedef struct _DISK_SIGNATURE * PDISK_SIGNATURE
typedef NTSTATUS(* PDRIVER_ADD_DEVICE) (IN struct _DRIVER_OBJECT *DriverObject, IN struct _DEVICE_OBJECT *PhysicalDeviceObject)
typedef VOID(* PDRIVER_CANCEL) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp)
typedef IO_ALLOCATION_ACTION(* PDRIVER_CONTROL) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp, IN PVOID MapRegisterBase, IN PVOID Context)
typedef NTSTATUS(* PDRIVER_DISPATCH) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp)
typedef struct _DRIVER_EXTENSION * PDRIVER_EXTENSION
typedef VOID(* PDRIVER_FS_NOTIFICATION) (IN struct _DEVICE_OBJECT *DeviceObject, IN BOOLEAN FsActive)
typedef NTSTATUS(* PDRIVER_INITIALIZE) (IN struct _DRIVER_OBJECT *DriverObject, IN PUNICODE_STRING RegistryPath)
typedef struct _DRIVER_OBJECT * PDRIVER_OBJECT
typedef VOID(* PDRIVER_REINITIALIZE) (IN struct _DRIVER_OBJECT *DriverObject, IN PVOID Context, IN ULONG Count)
typedef VOID(* PDRIVER_STARTIO) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp)
typedef VOID(* PDRIVER_UNLOAD) (IN struct _DRIVER_OBJECT *DriverObject)
typedef VOID(* PDUMP_DRIVER_FINISH) (VOID)
typedef BOOLEAN(* PDUMP_DRIVER_OPEN) (IN LARGE_INTEGER PartitionOffset)
typedef NTSTATUS(* PDUMP_DRIVER_WRITE) (IN PLARGE_INTEGER DiskByteOffset, IN PMDL Mdl)
typedef NTSTATUS(* PDUMP_DRIVER_WRITE_PENDING) (IN LONG Action, IN PLARGE_INTEGER DiskByteOffset, IN PMDL Mdl, IN PVOID LocalData)
typedef struct _DUMP_INITIALIZATION_CONTEXT * PDUMP_INITIALIZATION_CONTEXT
typedef struct _DUMP_STACK_CONTEXT * PDUMP_STACK_CONTEXT
typedef struct DUMP_STACK_IMAGE * PDUMP_STACK_IMAGE
typedef VOID(* PFAST_IO_ACQUIRE_FILE) (IN struct _FILE_OBJECT *FileObject)
typedef NTSTATUS(* PFAST_IO_ACQUIRE_FOR_CCFLUSH) (IN struct _FILE_OBJECT *FileObject, IN struct _DEVICE_OBJECT *DeviceObject)
typedef NTSTATUS(* PFAST_IO_ACQUIRE_FOR_MOD_WRITE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER EndingOffset, OUT struct _ERESOURCE **ResourceToRelease, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_CHECK_IF_POSSIBLE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN Wait, IN ULONG LockKey, IN BOOLEAN CheckForReadOperation, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef VOID(* PFAST_IO_DETACH_DEVICE) (IN struct _DEVICE_OBJECT *SourceDevice, IN struct _DEVICE_OBJECT *TargetDevice)
typedef BOOLEAN(* PFAST_IO_DEVICE_CONTROL) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN ULONG IoControlCode, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef struct _FAST_IO_DISPATCH * PFAST_IO_DISPATCH
typedef BOOLEAN(* PFAST_IO_LOCK) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length, PEPROCESS ProcessId, ULONG Key, BOOLEAN FailImmediately, BOOLEAN ExclusiveLock, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_MDL_READ) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_MDL_READ_COMPLETE) (IN struct _FILE_OBJECT *FileObject, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_MDL_READ_COMPLETE_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_MDL_WRITE_COMPLETE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_MDL_WRITE_COMPLETE_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_PREPARE_MDL_WRITE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_QUERY_BASIC_INFO) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, OUT PFILE_BASIC_INFORMATION Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_QUERY_NETWORK_OPEN_INFO) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, OUT struct _FILE_NETWORK_OPEN_INFORMATION *Buffer, OUT struct _IO_STATUS_BLOCK *IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_QUERY_OPEN) (IN struct _IRP *Irp, OUT PFILE_NETWORK_OPEN_INFORMATION NetworkInformation, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_QUERY_STANDARD_INFO) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, OUT PFILE_STANDARD_INFORMATION Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_READ) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN Wait, IN ULONG LockKey, OUT PVOID Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_READ_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, OUT PVOID Buffer, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, OUT struct _COMPRESSED_DATA_INFO *CompressedDataInfo, IN ULONG CompressedDataInfoLength, IN struct _DEVICE_OBJECT *DeviceObject)
typedef VOID(* PFAST_IO_RELEASE_FILE) (IN struct _FILE_OBJECT *FileObject)
typedef NTSTATUS(* PFAST_IO_RELEASE_FOR_CCFLUSH) (IN struct _FILE_OBJECT *FileObject, IN struct _DEVICE_OBJECT *DeviceObject)
typedef NTSTATUS(* PFAST_IO_RELEASE_FOR_MOD_WRITE) (IN struct _FILE_OBJECT *FileObject, IN struct _ERESOURCE *ResourceToRelease, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_UNLOCK_ALL) (IN struct _FILE_OBJECT *FileObject, PEPROCESS ProcessId, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_UNLOCK_ALL_BY_KEY) (IN struct _FILE_OBJECT *FileObject, PVOID ProcessId, ULONG Key, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_UNLOCK_SINGLE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length, PEPROCESS ProcessId, ULONG Key, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_WRITE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN Wait, IN ULONG LockKey, IN PVOID Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
typedef BOOLEAN(* PFAST_IO_WRITE_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, IN PVOID Buffer, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, IN struct _COMPRESSED_DATA_INFO *CompressedDataInfo, IN ULONG CompressedDataInfoLength, IN struct _DEVICE_OBJECT *DeviceObject)
typedef struct _FILE_OBJECT * PFILE_OBJECT
typedef NTSTATUS(* PFS_FILTER_CALLBACK) (IN PFS_FILTER_CALLBACK_DATA Data, OUT PVOID *CompletionContext)
typedef struct _FS_FILTER_CALLBACK_DATA * PFS_FILTER_CALLBACK_DATA
typedef struct _FS_FILTER_CALLBACKS * PFS_FILTER_CALLBACKS
typedef VOID(* PFS_FILTER_COMPLETION_CALLBACK) (IN PFS_FILTER_CALLBACK_DATA Data, IN NTSTATUS OperationStatus, IN PVOID CompletionContext)
typedef union _FS_FILTER_PARAMETERS * PFS_FILTER_PARAMETERS
typedef enum _FS_FILTER_SECTION_SYNC_TYPE * PFS_FILTER_SECTION_SYNC_TYPE
typedef struct _INTERFACE * PINTERFACE
typedef enum _IO_ALLOCATION_ACTION * PIO_ALLOCATION_ACTION
typedef struct _IO_CLIENT_EXTENSION * PIO_CLIENT_EXTENSION
typedef struct _IO_COMPLETION_CONTEXT * PIO_COMPLETION_CONTEXT
typedef NTSTATUS(* PIO_COMPLETION_ROUTINE) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
typedef enum _IO_COMPLETION_ROUTINE_RESULT * PIO_COMPLETION_ROUTINE_RESULT
typedef struct _IO_CSQ * PIO_CSQ
typedef VOID(* PIO_CSQ_ACQUIRE_LOCK) (IN PIO_CSQ Csq, OUT PKIRQL Irql)
typedef VOID(* PIO_CSQ_COMPLETE_CANCELED_IRP) (IN PIO_CSQ Csq, IN PIRP Irp)
typedef VOID(* PIO_CSQ_INSERT_IRP) (IN struct _IO_CSQ *Csq, IN PIRP Irp)
typedef NTSTATUS(* PIO_CSQ_INSERT_IRP_EX) (IN struct _IO_CSQ *Csq, IN PIRP Irp, IN OUT PVOID InsertContext)
typedef struct _IO_CSQ_IRP_CONTEXT * PIO_CSQ_IRP_CONTEXT
typedef PIRP(* PIO_CSQ_PEEK_NEXT_IRP) (IN PIO_CSQ Csq, IN PIRP Irp, IN PVOID PeekContext)
typedef VOID(* PIO_CSQ_RELEASE_LOCK) (IN PIO_CSQ Csq, IN KIRQL Irql)
typedef VOID(* PIO_CSQ_REMOVE_IRP) (IN PIO_CSQ Csq, IN PIRP Irp)
typedef VOID(* PIO_DPC_ROUTINE) (IN PKDPC Dpc, IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp, IN PVOID Context)
typedef struct _IO_INTERRUPT_STRUCTURE * PIO_INTERRUPT_STRUCTURE
typedef BOOLEAN(* PIO_LEVEL_END_WORKER) (IN ULONG Level, IN PVOID Context)
typedef enum _IO_QUERY_DEVICE_DATA_FORMAT * PIO_QUERY_DEVICE_DATA_FORMAT
typedef NTSTATUS(* PIO_QUERY_DEVICE_ROUTINE) (IN PVOID Context, IN PUNICODE_STRING PathName, IN INTERFACE_TYPE BusType, IN ULONG BusNumber, IN PKEY_VALUE_FULL_INFORMATION *BusInformation, IN CONFIGURATION_TYPE ControllerType, IN ULONG ControllerNumber, IN PKEY_VALUE_FULL_INFORMATION *ControllerInformation, IN CONFIGURATION_TYPE PeripheralType, IN ULONG PeripheralNumber, IN PKEY_VALUE_FULL_INFORMATION *PeripheralInformation)
typedef struct _IO_REMOVE_LOCK * PIO_REMOVE_LOCK
typedef struct _IO_REMOVE_LOCK_TRACKING_BLOCK * PIO_REMOVE_LOCK_TRACKING_BLOCK
typedef struct _IO_SECURITY_CONTEXT * PIO_SECURITY_CONTEXT
typedef struct _IO_STACK_LOCATION * PIO_STACK_LOCATION
typedef struct _IO_TIMER * PIO_TIMER
typedef VOID(* PIO_TIMER_ROUTINE) (IN struct _DEVICE_OBJECT *DeviceObject, IN PVOID Context)
typedef BOOLEAN(* PIO_TRAVERSE_WORKER) (IN ULONG Level, IN PVOID DeviceNode, IN PDEVICE_OBJECT DeviceObject, IN PVOID Context)
typedef struct _IO_WORKITEM * PIO_WORKITEM
typedef VOID(* PIO_WORKITEM_ROUTINE) (IN PDEVICE_OBJECT DeviceObject, IN PVOID Context)
typedef struct _MAILSLOT_CREATE_PARAMETERS * PMAILSLOT_CREATE_PARAMETERS
typedef struct _NAMED_PIPE_CREATE_PARAMETERS * PNAMED_PIPE_CREATE_PARAMETERS
typedef ULONG PNP_DEVICE_STATE
typedef struct _POWER_SEQUENCE POWER_SEQUENCE
typedef ULONG * PPNP_DEVICE_STATE
typedef struct _POWER_SEQUENCE * PPOWER_SEQUENCE
typedef SECTION_OBJECT_POINTERS * PSECTION_OBJECT_POINTERS
typedef struct _SHARE_ACCESS * PSHARE_ACCESS
typedef VOID(* PSTALL_ROUTINE) (IN ULONG Delay)
typedef struct _VPB * PVPB
typedef struct _WAIT_CONTEXT_BLOCK * PWAIT_CONTEXT_BLOCK
typedef struct _SECTION_OBJECT_POINTERS SECTION_OBJECT_POINTERS
typedef struct _SHARE_ACCESS SHARE_ACCESS
typedef struct _VPB VPB
typedef struct _WAIT_CONTEXT_BLOCK WAIT_CONTEXT_BLOCK
typedef VOID(* WMI_NOTIFICATION_CALLBACK) (PVOID Wnode, PVOID Context)
typedef enum tagWMIACTIONCODE WMIACTIONCODE
typedef NTSTATUS(* WMIENTRY) (IN WMIACTIONCODE ActionCode, IN PVOID DataPath, IN ULONG BufferSize, IN OUT PVOID Buffer, IN PVOID Context, OUT PULONG Size)
Enumerations
enum _CRASHDUMP_CONFIGURATION { CrashDumpDisable = 0, CrashDumpReconfigure }
enum _CREATE_FILE_TYPE { CreateFileTypeNone, CreateFileTypeNamedPipe, CreateFileTypeMailslot }
enum _DEVICE_RELATION_TYPE {
BusRelations, EjectionRelations, PowerRelations, RemovalRelations,
TargetDeviceRelation, SingleBusRelations
}
enum _DEVICE_USAGE_NOTIFICATION_TYPE { DeviceUsageTypeUndefined, DeviceUsageTypePaging, DeviceUsageTypeHibernation, DeviceUsageTypeDumpFile }
enum _FS_FILTER_SECTION_SYNC_TYPE { SyncTypeOther = 0, SyncTypeCreateSection }
enum _IO_ALLOCATION_ACTION { KeepObject = 1, DeallocateObject, DeallocateObjectKeepRegisters }
enum _IO_COMPLETION_ROUTINE_RESULT { ContinueCompletion = STATUS_CONTINUE_COMPLETION, StopCompletion = STATUS_MORE_PROCESSING_REQUIRED }
enum _IO_PAGING_PRIORITY {
IoPagingPriorityInvalid, IoPagingPriorityNormal, IoPagingPriorityHigh, IoPagingPriorityReserved1,
IoPagingPriorityReserved2
}
enum _IO_QUERY_DEVICE_DATA_FORMAT { IoQueryDeviceIdentifier = 0, IoQueryDeviceConfigurationData, IoQueryDeviceComponentInformation, IoQueryDeviceMaxData }
enum BUS_QUERY_ID_TYPE {
BusQueryDeviceID = 0, BusQueryHardwareIDs = 1, BusQueryCompatibleIDs = 2, BusQueryInstanceID = 3,
BusQueryDeviceSerialNumber = 4
}
enum DEVICE_TEXT_TYPE { DeviceTextDescription = 0, DeviceTextLocationInformation = 1 }
enum tagWMIACTIONCODE {
WmiGetAllData = IRP_MN_QUERY_ALL_DATA, WmiGetSingleInstance = IRP_MN_QUERY_SINGLE_INSTANCE, WmiChangeSingleInstance = IRP_MN_CHANGE_SINGLE_INSTANCE, WmiChangeSingleItem = IRP_MN_CHANGE_SINGLE_ITEM,
WmiEnableEvents = IRP_MN_ENABLE_EVENTS, WmiDisableEvents = IRP_MN_DISABLE_EVENTS, WmiEnableCollection = IRP_MN_ENABLE_COLLECTION, WmiDisableCollection = IRP_MN_DISABLE_COLLECTION,
WmiRegisterInfo = IRP_MN_REGINFO, WmiExecuteMethodCall = IRP_MN_EXECUTE_METHOD, WmiGetAllData = 0, WmiGetSingleInstance = 1,
WmiChangeSingleInstance = 2, WmiChangeSingleItem = 3, WmiEnableEvents = 4, WmiDisableEvents = 5,
WmiEnableCollection = 6, WmiDisableCollection = 7, WmiRegisterInfo = 8, WmiExecuteMethodCall = 9,
WmiSetTraceNotify = 10
}
Functions
struct DECLSPEC_ALIGN (MEMORY_ALLOCATION_ALIGNMENT) _IRP
NTKERNELAPI NTSTATUS FsRtlRegisterFileSystemFilterCallbacks (__in struct _DRIVER_OBJECT *FilterDriverObject, __in PFS_FILTER_CALLBACKS Callbacks)
NTKERNELAPI VOID FASTCALL HalExamineMBR (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG MBRTypeIdentifier, OUT PVOID *Buffer)
NTKERNELAPI VOID IoAcquireCancelSpinLock (OUT PKIRQL Irql)
NTKERNELAPI NTSTATUS NTAPI IoAcquireRemoveLockEx (IN PIO_REMOVE_LOCK RemoveLock, IN OPTIONAL PVOID Tag, IN PCSTR File, IN ULONG Line, IN ULONG RemlockSize)
NTKERNELAPI VOID IoAcquireVpbSpinLock (OUT PKIRQL Irql)
BOOLEAN IoAddTriageDumpDataBlock (IN PVOID Address, IN ULONG Length)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoAllocateAdapterChannel (IN PADAPTER_OBJECT AdapterObject, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
NTKERNELAPI VOID IoAllocateController (IN PCONTROLLER_OBJECT ControllerObject, IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
NTKERNELAPI NTSTATUS IoAllocateDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress, IN ULONG DriverObjectExtensionSize, OUT PVOID *DriverObjectExtension)
NTKERNELAPI PVOID IoAllocateErrorLogEntry (IN PVOID IoObject, IN UCHAR EntrySize)
NTKERNELAPI PVOID IoAllocateGenericErrorLogEntry (IN UCHAR EntrySize)
NTKERNELAPI PIRP IoAllocateIrp (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
NTKERNELAPI PMDL IoAllocateMdl (IN PVOID VirtualAddress, IN ULONG Length, IN BOOLEAN SecondaryBuffer, IN BOOLEAN ChargeQuota, IN OUT PIRP Irp OPTIONAL)
NTKERNELAPI PIO_WORKITEM IoAllocateWorkItem (PDEVICE_OBJECT DeviceObject)
NTKERNELAPI VOID FASTCALL IoAssignDriveLetters (PLOADER_PARAMETER_BLOCK LoaderBlock, PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, OUT PSTRING NtSystemPathString)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoAssignResources (IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN PIO_RESOURCE_REQUIREMENTS_LIST RequestedResources, IN OUT PCM_RESOURCE_LIST *AllocatedResources)
NTKERNELAPI NTSTATUS IoAsynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PIO_APC_ROUTINE ApcRoutine, IN PVOID ApcContext, IN IO_PAGING_PRIORITY Priority, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PIRP *Irp OPTIONAL)
NTKERNELAPI NTSTATUS IoAttachDevice (IN PDEVICE_OBJECT SourceDevice, IN PUNICODE_STRING TargetDevice, OUT PDEVICE_OBJECT *AttachedDevice)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoAttachDeviceByPointer (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
NTKERNELAPI PDEVICE_OBJECT IoAttachDeviceToDeviceStack (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
NTKERNELAPI NTSTATUS IoAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, OUT PDEVICE_OBJECT *AttachedToDeviceObject)
NTKERNELAPI PIRP IoBuildAsynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PIO_STATUS_BLOCK IoStatusBlock OPTIONAL)
NTKERNELAPI PIRP IoBuildDeviceIoControlRequest (IN ULONG IoControlCode, IN PDEVICE_OBJECT DeviceObject, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN InternalDeviceIoControl, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTKERNELAPI VOID IoBuildPartialMdl (IN PMDL SourceMdl, IN OUT PMDL TargetMdl, IN PVOID VirtualAddress, IN ULONG Length)
NTSTATUS IoBuildPoDeviceNotifyList (IN OUT PVOID Order)
NTKERNELAPI PIRP IoBuildSynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTKERNELAPI VOID IoCancelFileOpen (IN PDEVICE_OBJECT DeviceObject, IN PFILE_OBJECT FileObject)
NTKERNELAPI BOOLEAN IoCancelIrp (IN PIRP Irp)
NTKERNELAPI VOID IoCancelThreadIo (IN PETHREAD Thread)
NTSTATUS IoChangeFileObjectFilterContext (IN PFILE_OBJECT FileObject, IN PVOID FilterContext, IN BOOLEAN Set)
NTKERNELAPI NTSTATUS IoCheckDesiredAccess (IN OUT PACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess)
NTKERNELAPI NTSTATUS IoCheckEaBufferValidity (IN PFILE_FULL_EA_INFORMATION EaBuffer, IN ULONG EaLength, OUT PULONG ErrorOffset)
NTKERNELAPI NTSTATUS IoCheckFunctionAccess (IN ACCESS_MASK GrantedAccess, IN UCHAR MajorFunction, IN UCHAR MinorFunction, IN ULONG IoControlCode, IN PVOID Arg1 OPTIONAL, IN PVOID Arg2 OPTIONAL)
NTKERNELAPI NTSTATUS IoCheckQuerySetFileInformation (IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
NTKERNELAPI NTSTATUS IoCheckQuerySetVolumeInformation (IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
NTKERNELAPI NTSTATUS IoCheckQuotaBufferValidity (IN PFILE_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG ErrorOffset)
NTKERNELAPI NTSTATUS IoCheckShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess, IN BOOLEAN Update)
NTSTATUS IoComputeDesiredAccessFileObject (IN PFILE_OBJECT FileObject, OUT PNTSTATUS DesiredAccess)
NTSTATUS IoConfigureCrashDump (CRASHDUMP_CONFIGURATION Config)
NTKERNELAPI NTSTATUS IoConnectInterrupt (OUT PKINTERRUPT *InterruptObject, IN PKSERVICE_ROUTINE ServiceRoutine, IN PVOID ServiceContext, IN PKSPIN_LOCK SpinLock OPTIONAL, IN ULONG Vector, IN KIRQL Irql, IN KIRQL SynchronizeIrql, IN KINTERRUPT_MODE InterruptMode, IN BOOLEAN ShareVector, IN KAFFINITY ProcessorEnableMask, IN BOOLEAN FloatingSave)
VOID IoControlPnpDeviceActionQueue (BOOLEAN Lock)
NTKERNELAPI PCONTROLLER_OBJECT IoCreateController (IN ULONG Size)
NTKERNELAPI NTSTATUS IoCreateDevice (IN PDRIVER_OBJECT DriverObject, IN ULONG DeviceExtensionSize, IN PUNICODE_STRING DeviceName OPTIONAL, IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN Exclusive, OUT PDEVICE_OBJECT *DeviceObject)
NTKERNELAPI NTSTATUS IoCreateDisk (IN PDEVICE_OBJECT DeviceObject, IN struct _CREATE_DISK *Disk)
NTKERNELAPI NTSTATUS IoCreateDriver (IN PUNICODE_STRING DriverName, OPTIONAL IN PDRIVER_INITIALIZE InitializationFunction)
NTKERNELAPI NTSTATUS IoCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options)
NTKERNELAPI NTSTATUS IoCreateFileSpecifyDeviceObjectHint (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN PVOID DeviceObject)
NTKERNELAPI PKEVENT IoCreateNotificationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
NTKERNELAPI PFILE_OBJECT IoCreateStreamFileObject (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
NTKERNELAPI PFILE_OBJECT IoCreateStreamFileObjectEx (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, OUT PHANDLE FileObjectHandle OPTIONAL)
NTKERNELAPI PFILE_OBJECT IoCreateStreamFileObjectLite (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
NTKERNELAPI NTSTATUS IoCreateSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
NTKERNELAPI PKEVENT IoCreateSynchronizationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
NTKERNELAPI NTSTATUS IoCreateUnprotectedSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
NTKERNELAPI NTSTATUS IoCsqInitialize (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
NTKERNELAPI NTSTATUS IoCsqInitializeEx (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP_EX CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
NTKERNELAPI VOID IoCsqInsertIrp (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context)
NTKERNELAPI NTSTATUS IoCsqInsertIrpEx (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context, IN PVOID InsertContext)
NTKERNELAPI PIRP IoCsqRemoveIrp (IN PIO_CSQ Csq, IN PIO_CSQ_IRP_CONTEXT Context)
NTKERNELAPI PIRP IoCsqRemoveNextIrp (IN PIO_CSQ Csq, IN PVOID PeekContext)
NTKERNELAPI VOID IoDeleteController (IN PCONTROLLER_OBJECT ControllerObject)
NTKERNELAPI VOID IoDeleteDevice (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI VOID IoDeleteDriver (IN PDRIVER_OBJECT DriverObject)
NTKERNELAPI NTSTATUS IoDeleteSymbolicLink (IN PUNICODE_STRING SymbolicLinkName)
NTKERNELAPI VOID IoDetachDevice (IN OUT PDEVICE_OBJECT TargetDevice)
NTKERNELAPI VOID IoDisconnectInterrupt (IN PKINTERRUPT InterruptObject)
NTKERNELAPI VOID IoEnqueueIrp (IN PIRP Irp)
NTKERNELAPI NTSTATUS IoEnumerateDeviceObjectList (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT *DeviceObjectList, IN ULONG DeviceObjectListSize, OUT PULONG ActualNumberDeviceObjects)
NTKERNELAPI NTSTATUS IoEnumerateRegisteredFiltersList (IN PDRIVER_OBJECT *DriverObjectList, IN ULONG DriverObjectListSize, OUT PULONG ActualNumberDriverObjects)
NTKERNELAPI BOOLEAN IoFastQueryNetworkAttributes (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN ULONG OpenOptions, OUT PIO_STATUS_BLOCK IoStatus, OUT PFILE_NETWORK_OPEN_INFORMATION Buffer)
NTKERNELAPI NTSTATUS FASTCALL IofCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
NTSTATUS FASTCALL IofCallDriverSpecifyReturn (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp, IN PVOID ReturnAddress OPTIONAL)
NTKERNELAPI VOID FASTCALL IofCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
PDEVICE_OBJECT IoFindDeviceThatFailedIrp (IN PIRP Irp)
NTKERNELAPI BOOLEAN IoForwardIrpSynchronously (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTKERNELAPI VOID IoFreeController (IN PCONTROLLER_OBJECT ControllerObject)
VOID IoFreeDumpStack (IN PDUMP_STACK_CONTEXT DumpStack)
NTKERNELAPI VOID IoFreeErrorLogEntry (PVOID ElEntry)
NTKERNELAPI VOID IoFreeIrp (IN PIRP Irp)
NTKERNELAPI VOID IoFreeMdl (IN PMDL Mdl)
VOID IoFreePoDeviceNotifyList (IN OUT PVOID Order)
NTKERNELAPI VOID IoFreeWorkItem (PIO_WORKITEM IoWorkItem)
NTKERNELAPI PDEVICE_OBJECT IoGetAttachedDevice (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI PDEVICE_OBJECT IoGetAttachedDeviceReference (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI PDEVICE_OBJECT IoGetBaseFileSystemDeviceObject (IN PFILE_OBJECT FileObject)
NTKERNELAPI NTSTATUS IoGetBootDiskInformation (IN OUT PBOOTDISK_INFORMATION BootDiskInformation, IN ULONG Size)
NTKERNELAPI PCONFIGURATION_INFORMATION IoGetConfigurationInformation (VOID)
NTKERNELAPI PEPROCESS IoGetCurrentProcess (VOID)
NTKERNELAPI PDEVICE_OBJECT IoGetDeviceAttachmentBaseRef (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IoGetDeviceInstanceName (IN PDEVICE_OBJECT PhysicalDeviceObject, OUT PUNICODE_STRING InstanceName)
NTKERNELAPI NTSTATUS IoGetDeviceObjectPointer (IN PUNICODE_STRING ObjectName, IN ACCESS_MASK DesiredAccess, OUT PFILE_OBJECT *FileObject, OUT PDEVICE_OBJECT *DeviceObject)
NTKERNELAPI PDEVICE_OBJECT IoGetDeviceToVerify (IN PETHREAD Thread)
NTKERNELAPI NTSTATUS IoGetDiskDeviceObject (IN PDEVICE_OBJECT FileSystemDeviceObject, OUT PDEVICE_OBJECT *DiskDeviceObject)
NTKERNELAPI struct _DMA_ADAPTER * IoGetDmaAdapter (IN PDEVICE_OBJECT PhysicalDeviceObject, OPTIONAL IN struct _DEVICE_DESCRIPTION *DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
NTKERNELAPI PVOID IoGetDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress)
VOID IoGetDumpHiberRanges (IN PVOID HiberContext, IN PDUMP_STACK_CONTEXT DumpStack)
NTSTATUS IoGetDumpStack (IN PWCHAR ModulePrefix, OUT PDUMP_STACK_CONTEXT *DumpStack, IN enum _DEVICE_USAGE_NOTIFICATION_TYPE UsageType, IN ULONG IgnoreDeviceUsageFailure)
PVOID IoGetFileObjectFilterContext (IN PFILE_OBJECT FileObject)
NTKERNELAPI PGENERIC_MAPPING IoGetFileObjectGenericMapping (VOID)
NTKERNELAPI PVOID IoGetInitialStack (VOID)
NTSTATUS IoGetLegacyVetoList (OUT PWSTR *VetoList OPTIONAL, OUT PPNP_VETO_TYPE VetoType)
NTKERNELAPI PDEVICE_OBJECT IoGetLowerDeviceObject (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI IO_PAGING_PRIORITY FASTCALL IoGetPagingIoPriority (IN PIRP IRP)
PVOID IoGetPoNotifyParent (PVOID Notify)
NTKERNELAPI PDEVICE_OBJECT IoGetRelatedDeviceObject (IN PFILE_OBJECT FileObject)
NTSTATUS IoGetRelatedTargetDevice (IN PFILE_OBJECT FileObject, OUT PDEVICE_OBJECT *DeviceObject)
FORCEINLINE ULONG_PTR IoGetRemainingStackSize (VOID)
NTKERNELAPI PEPROCESS IoGetRequestorProcess (IN PIRP Irp)
NTKERNELAPI ULONG IoGetRequestorProcessId (IN PIRP Irp)
NTKERNELAPI NTSTATUS IoGetRequestorSessionId (IN PIRP Irp, OUT PULONG pSessionId)
NTKERNELAPI VOID IoGetStackLimits (OUT PULONG_PTR LowLimit, OUT PULONG_PTR HighLimit)
NTKERNELAPI PIRP IoGetTopLevelIrp (VOID)
BOOLEAN IoInitializeCrashDump (IN HANDLE Pagefile)
NTSTATUS IoInitializeDumpStack (IN PDUMP_STACK_CONTEXT DumpStack, IN PUCHAR MessageBuffer OPTIONAL)
NTKERNELAPI VOID IoInitializeIrp (IN OUT PIRP Irp, IN USHORT PacketSize, IN CCHAR StackSize)
NTKERNELAPI VOID NTAPI IoInitializeRemoveLockEx (IN PIO_REMOVE_LOCK Lock, IN ULONG AllocateTag, IN ULONG MaxLockedMinutes, IN ULONG HighWatermark, IN ULONG RemlockSize)
NTKERNELAPI NTSTATUS IoInitializeTimer (IN PDEVICE_OBJECT DeviceObject, IN PIO_TIMER_ROUTINE TimerRoutine, IN PVOID Context)
NTKERNELAPI BOOLEAN IoInitSystem (PLOADER_PARAMETER_BLOCK LoaderBlock)
BOOLEAN IoIsDeviceEjectable (IN PDEVICE_OBJECT)
NTKERNELAPI BOOLEAN IoIsFileOriginRemote (IN PFILE_OBJECT FileObject)
NTKERNELAPI BOOLEAN IoIsOperationSynchronous (IN PIRP Irp)
NTKERNELAPI BOOLEAN IoIsSystemThread (IN PETHREAD Thread)
BOOLEAN IoIsTriageDumpEnabled (VOID)
NTKERNELAPI BOOLEAN IoIsValidNameGraftingBuffer (IN PIRP Irp, IN PREPARSE_DATA_BUFFER ReparseBuffer)
NTKERNELAPI BOOLEAN IoIsWdmVersionAvailable (IN UCHAR MajorVersion, IN UCHAR MinorVersion)
NTKERNELAPI PIRP IoMakeAssociatedIrp (IN PIRP Irp, IN CCHAR StackSize)
VOID IoMovePoNotifyChildren (IN PVOID Notify, IN PVOID Order)
NTSTATUS IoNotifyPowerOperationVetoed (IN POWER_ACTION VetoedPowerOperation, IN PDEVICE_OBJECT TargetedDeviceObject OPTIONAL, IN PDEVICE_OBJECT VetoingDeviceObject)
NTKERNELAPI BOOLEAN IoPageFileCreated (IN HANDLE FileHandle)
NTKERNELAPI NTSTATUS IoPageRead (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
VOID IopBootLog (PUNICODE_STRING LogEntry, BOOLEAN Loaded)
VOID IopCopyBootLogRegistryToFile (VOID)
VOID IopInitializeBootLogging (PLOADER_PARAMETER_BLOCK LoaderBlock, PCHAR HeaderString)
NTSTATUS IopSetRegistryStringValue (IN HANDLE KeyHandle, IN PUNICODE_STRING ValueName, IN PUNICODE_STRING ValueData)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoQueryDeviceDescription (IN PINTERFACE_TYPE BusType OPTIONAL, IN PULONG BusNumber OPTIONAL, IN PCONFIGURATION_TYPE ControllerType OPTIONAL, IN PULONG ControllerNumber OPTIONAL, IN PCONFIGURATION_TYPE PeripheralType OPTIONAL, IN PULONG PeripheralNumber OPTIONAL, IN PIO_QUERY_DEVICE_ROUTINE CalloutRoutine, IN PVOID Context)
NTKERNELAPI NTSTATUS IoQueryFileDosDeviceName (IN PFILE_OBJECT FileObject, OUT POBJECT_NAME_INFORMATION *ObjectNameInformation)
NTKERNELAPI NTSTATUS IoQueryFileInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
NTKERNELAPI NTSTATUS IoQueryVolumeInformation (IN PFILE_OBJECT FileObject, IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, OUT PVOID FsInformation, OUT PULONG ReturnedLength)
NTKERNELAPI VOID IoQueueThreadIrp (IN PIRP Irp)
NTKERNELAPI VOID IoQueueWorkItem (IN PIO_WORKITEM IoWorkItem, IN PIO_WORKITEM_ROUTINE WorkerRoutine, IN WORK_QUEUE_TYPE QueueType, IN PVOID Context)
NTKERNELAPI VOID IoRaiseHardError (IN PIRP Irp, IN PVPB Vpb OPTIONAL, IN PDEVICE_OBJECT RealDeviceObject)
NTKERNELAPI BOOLEAN IoRaiseInformationalHardError (IN NTSTATUS ErrorStatus, IN PUNICODE_STRING String OPTIONAL, IN PKTHREAD Thread OPTIONAL)
NTKERNELAPI NTSTATUS IoReadDiskSignature (IN PDEVICE_OBJECT DeviceObject, IN ULONG BytesPerSector, OUT PDISK_SIGNATURE Signature)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS FASTCALL IoReadPartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN BOOLEAN ReturnRecognizedPartitions, OUT struct _DRIVE_LAYOUT_INFORMATION **PartitionBuffer)
NTKERNELAPI NTSTATUS IoReadPartitionTableEx (IN PDEVICE_OBJECT DeviceObject, IN struct _DRIVE_LAYOUT_INFORMATION_EX **DriveLayout)
NTKERNELAPI VOID IoRegisterBootDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
NTKERNELAPI VOID IoRegisterDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
NTKERNELAPI VOID IoRegisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS IoRegisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
NTKERNELAPI NTSTATUS IoRegisterLastChanceShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS IoRegisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI VOID IoReleaseCancelSpinLock (IN KIRQL Irql)
NTKERNELAPI VOID NTAPI IoReleaseRemoveLockAndWaitEx (IN PIO_REMOVE_LOCK RemoveLock, IN PVOID Tag, IN ULONG RemlockSize)
NTKERNELAPI VOID NTAPI IoReleaseRemoveLockEx (IN PIO_REMOVE_LOCK RemoveLock, IN PVOID Tag, IN ULONG RemlockSize)
NTKERNELAPI VOID IoReleaseVpbSpinLock (IN KIRQL Irql)
NTKERNELAPI VOID IoRemoveShareAccess (IN PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
NTKERNELAPI NTSTATUS IoReportHalResourceUsage (IN PUNICODE_STRING HalName, IN PCM_RESOURCE_LIST RawResourceList, IN PCM_RESOURCE_LIST TranslatedResourceList, IN ULONG ResourceListSize)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoReportResourceUsage (IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PCM_RESOURCE_LIST DriverList OPTIONAL, IN ULONG DriverListSize OPTIONAL, IN PDEVICE_OBJECT DeviceObject, IN PCM_RESOURCE_LIST DeviceList OPTIONAL, IN ULONG DeviceListSize OPTIONAL, IN BOOLEAN OverrideConflict, OUT PBOOLEAN ConflictDetected)
VOID IoRetryIrpCompletions (VOID)
NTKERNELAPI VOID IoReuseIrp (IN OUT PIRP Irp, IN NTSTATUS Iostatus)
NTKERNELAPI NTSTATUS IoSetCompletionRoutineEx (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PIO_COMPLETION_ROUTINE CompletionRoutine, IN PVOID Context, IN BOOLEAN InvokeOnSuccess, IN BOOLEAN InvokeOnError, IN BOOLEAN InvokeOnCancel)
NTKERNELAPI VOID IoSetDeviceToVerify (IN PETHREAD Thread, IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS IoSetFileOrigin (IN PFILE_OBJECT FileObject, IN BOOLEAN Remote)
NTKERNELAPI VOID IoSetHardErrorOrVerifyDevice (IN PIRP Irp, IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS IoSetInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN PVOID FileInformation)
NTKERNELAPI NTSTATUS IoSetIoCompletion (IN PVOID IoCompletion, IN PVOID KeyContext, IN PVOID ApcContext, IN NTSTATUS IoStatus, IN ULONG_PTR IoStatusInformation, IN BOOLEAN Quota)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS FASTCALL IoSetPartitionInformation (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG PartitionNumber, IN ULONG PartitionType)
NTKERNELAPI NTSTATUS IoSetPartitionInformationEx (IN PDEVICE_OBJECT DeviceObject, IN ULONG PartitionNumber, IN struct _SET_PARTITION_INFORMATION_EX *PartitionInfo)
NTKERNELAPI VOID IoSetShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, OUT PSHARE_ACCESS ShareAccess)
VOID IoSetStartIoAttributes (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN DeferredStartIo, IN BOOLEAN NonCancelable)
NTKERNELAPI NTSTATUS IoSetSystemPartition (PUNICODE_STRING VolumeNameString)
NTKERNELAPI BOOLEAN IoSetThreadHardErrorMode (IN BOOLEAN EnableHardErrors)
NTKERNELAPI VOID IoSetTopLevelIrp (IN PIRP Irp)
NTSTATUS IoShutdownPnpDevices (VOID)
NTKERNELAPI VOID IoShutdownSystem (IN ULONG Phase)
NTKERNELAPI VOID IoStartNextPacket (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable)
NTKERNELAPI VOID IoStartNextPacketByKey (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable, IN ULONG Key)
NTKERNELAPI VOID IoStartPacket (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PULONG Key OPTIONAL, IN PDRIVER_CANCEL CancelFunction OPTIONAL)
NTKERNELAPI VOID IoStartTimer (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI VOID IoStopTimer (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS IoSynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTKERNELAPI PEPROCESS IoThreadToProcess (IN PETHREAD Thread)
BOOLEAN IoTranslateBusAddress (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
VOID IoTraverseDeviceTree (IN BOOLEAN Inverted, IN LONG CurrentLevel, IN PIO_TRAVERSE_WORKER WorkerFunction, IN PIO_LEVEL_END_WORKER LevelEndFunction, IN PVOID Context)
NTKERNELAPI VOID IoUnregisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
NTKERNELAPI VOID IoUnregisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
NTKERNELAPI VOID IoUnregisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
NTKERNELAPI NTSTATUS IoUpdateDiskGeometry (IN PDEVICE_OBJECT DeviceObject, IN struct _DISK_GEOMETRY_EX *OldDiskGeometry, IN struct _DISK_GEOMETRY_EX *NewDiskGeometry)
NTKERNELAPI VOID IoUpdateShareAccess (IN PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
NTKERNELAPI NTSTATUS IoValidateDeviceIoControlAccess (IN PIRP Irp, IN ULONG RequiredAccess)
PIRP IovAllocateIrp (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
PIRP IovBuildAsynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PIO_STATUS_BLOCK IoStatusBlock OPTIONAL)
PIRP IovBuildDeviceIoControlRequest (IN ULONG IoControlCode, IN PDEVICE_OBJECT DeviceObject, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN InternalDeviceIoControl, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS FASTCALL IovCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp, IN PVOID ReturnAddress)
VOID FASTCALL IovCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
VOID IoVerifierInit (IN ULONG VerifierFlags)
NTKERNELAPI NTSTATUS IoVerifyPartitionTable (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN FixErrors)
NTKERNELAPI NTSTATUS IoVerifyVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount)
VOID IovFreeIrp (IN PIRP Irp)
NTSTATUS IovInitializeTimer (IN PDEVICE_OBJECT DeviceObject, IN PIO_TIMER_ROUTINE TimerRoutine, IN PVOID Context)
NTKERNELAPI NTSTATUS IoVolumeDeviceToDosName (IN PVOID VolumeDeviceObject, OUT PUNICODE_STRING DosName)
NTKERNELAPI NTSTATUS IoWMIAllocateInstanceIds (__in GUID *Guid, __in ULONG InstanceCount, __out ULONG *FirstInstanceId)
NTKERNELAPI NTSTATUS IoWMIDeviceObjectToInstanceName (__in PVOID DataBlockObject, __in PDEVICE_OBJECT DeviceObject, __out PUNICODE_STRING InstanceName)
NTKERNELAPI NTSTATUS IoWMIExecuteMethod (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG MethodId, __in ULONG InBufferSize, __inout PULONG OutBufferSize, __inout_bcount_part_opt(*OutBufferSize, InBufferSize) PUCHAR InOutBuffer)
NTKERNELAPI NTSTATUS IoWMIHandleToInstanceName (__in PVOID DataBlockObject, __in HANDLE FileHandle, __out PUNICODE_STRING InstanceName)
NTKERNELAPI NTSTATUS IoWMIOpenBlock (__in GUID *DataBlockGuid, __in ULONG DesiredAccess, __out PVOID *DataBlockObject)
NTKERNELAPI NTSTATUS IoWMIQueryAllData (__in PVOID DataBlockObject, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTKERNELAPI NTSTATUS IoWMIQueryAllDataMultiple (__in_ecount(ObjectCount) PVOID *DataBlockObjectList, __in ULONG ObjectCount, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTKERNELAPI NTSTATUS IoWMIQuerySingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTKERNELAPI NTSTATUS IoWMIQuerySingleInstanceMultiple (__in_ecount(ObjectCount) PVOID *DataBlockObjectList, __in_ecount(ObjectCount) PUNICODE_STRING InstanceNames, __in ULONG ObjectCount, __inout ULONG *InOutBufferSize, __out_bcount_opt(*InOutBufferSize) PVOID OutBuffer)
NTKERNELAPI NTSTATUS IoWMIRegistrationControl (__in PDEVICE_OBJECT DeviceObject, __in ULONG Action)
NTKERNELAPI NTSTATUS IoWMISetNotificationCallback (__in PVOID Object, __in WMI_NOTIFICATION_CALLBACK Callback, __in_opt PVOID Context)
NTKERNELAPI NTSTATUS IoWMISetSingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
NTKERNELAPI NTSTATUS IoWMISetSingleItem (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG DataItemId, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
NTKERNELAPI NTSTATUS IoWMISuggestInstanceName (__in_opt PDEVICE_OBJECT PhysicalDeviceObject, __in_opt PUNICODE_STRING SymbolicLinkName, __in BOOLEAN CombineNames, __out PUNICODE_STRING SuggestedInstanceName)
NTKERNELAPI NTSTATUS IoWMIWriteEvent (__in PVOID WnodeEventItem)
NTKERNELAPI BOOLEAN IoWriteCrashDump (IN ULONG BugCheckCode, IN ULONG_PTR BugCheckParameter1, IN ULONG_PTR BugCheckParameter2, IN ULONG_PTR BugCheckParameter3, IN ULONG_PTR BugCheckParameter4, IN PVOID ContextSave, IN PKTHREAD Thread, OUT PBOOLEAN Reboot)
NTKERNELAPI VOID IoWriteErrorLogEntry (IN PVOID ElEntry)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS FASTCALL IoWritePartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG SectorsPerTrack, IN ULONG NumberOfHeads, IN struct _DRIVE_LAYOUT_INFORMATION *PartitionBuffer)
NTKERNELAPI NTSTATUS IoWritePartitionTableEx (IN PDEVICE_OBJECT DeviceObject, IN struct _DRIVE_LAYOUT_INFORMATION_EX *DriveLayout)
NTKERNELAPI BOOLEAN WMIInitialize (ULONG Phase, PVOID LoaderBlock)
Variables
DEVICE_OBJECT
ULONG IoOtherOperationCount
LARGE_INTEGER IoOtherTransferCount
ULONG IoReadOperationCount
LARGE_INTEGER IoReadTransferCount
BOOLEAN IoRemoteBootClient
KSPIN_LOCK IoStatisticsLock
ULONG IoWriteOperationCount
LARGE_INTEGER IoWriteTransferCount
IRP
* PIRP
Macro Definition Documentation
#define _WMIKM_
Definition at line 4858 of file io.h.
#define DO_BUFFERED_IO 0x00000004
Definition at line 1375 of file io.h.
Referenced by BuildQueryDirectoryIrp(), IoBuildAsynchronousFsdRequest(), IopSetEaOrQuotaInformationFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtWriteFile(), and NtWriteFileGather().
#define DO_BUS_ENUMERATED_DEVICE 0x00001000
Definition at line 1385 of file io.h.
Referenced by IopGetDevicePDO().
#define DO_DEVICE_HAS_NAME 0x00000040
Definition at line 1379 of file io.h.
Referenced by IoCreateDevice(), and IoDeleteDevice().
#define DO_DEVICE_INITIALIZING 0x00000080
Definition at line 1380 of file io.h.
Referenced by IoCreateDevice(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopReadyDeviceObjects(), IoRegisterFileSystem(), RawMountVolume(), and WmipDriverEntry().
#define DO_DIRECT_IO 0x00000010
Definition at line 1377 of file io.h.
Referenced by BuildQueryDirectoryIrp(), IoBuildAsynchronousFsdRequest(), IopSetEaOrQuotaInformationFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtReadFile(), NtSetEaFile(), NtWriteFile(), RawInitialize(), and RawMountVolume().
#define DO_EXCLUSIVE 0x00000008
Definition at line 1376 of file io.h.
Referenced by IoCreateDevice(), and IopCheckDeviceAndDriver().
#define DO_LONG_TERM_REQUESTS 0x00000200
Definition at line 1382 of file io.h.
#define DO_LOW_PRIORITY_FILESYSTEM 0x00010000
Definition at line 1389 of file io.h.
Referenced by IoRegisterFileSystem().
#define DO_MAP_IO_BUFFER 0x00000020
Definition at line 1378 of file io.h.
#define DO_NEVER_LAST_DEVICE 0x00000400
Definition at line 1383 of file io.h.
Referenced by IopDeleteFile().
#define DO_POWER_INRUSH 0x00004000
Definition at line 1387 of file io.h.
#define DO_POWER_NOOP 0x00008000
Definition at line 1388 of file io.h.
#define DO_POWER_PAGABLE 0x00002000
Definition at line 1386 of file io.h.
#define DO_SHUTDOWN_REGISTERED 0x00000800
Definition at line 1384 of file io.h.
Referenced by IoDeleteDevice(), IoRegisterLastChanceShutdownNotification(), IoRegisterShutdownNotification(), and IoUnregisterShutdownNotification().
#define DO_SYSTEM_BOOT_PARTITION 0x00000100
Definition at line 1381 of file io.h.
Referenced by IopMarkBootPartition(), IopMountVolume(), and NtCreatePagingFile().
#define DO_VERIFY_VOLUME 0x00000002
Definition at line 1374 of file io.h.
Referenced by IopMountVolume(), IoVerifyVolume(), and RawVerifyVolume().
#define DO_XIP 0x00020000
Definition at line 1390 of file io.h.
#define DOE_DELETE_PENDING 0x00000002
Definition at line 1444 of file io.h.
Referenced by IoDeleteDevice(), IoDetachDevice(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), and IoStartTimer().
#define DOE_REMOVE_PENDING 0x00000004
Definition at line 1445 of file io.h.
Referenced by IoDetachDevice(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), and IoStartTimer().
#define DOE_REMOVE_PROCESSED 0x00000008
Definition at line 1446 of file io.h.
Referenced by IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCompleteUnloadOrDelete(), and IoStartTimer().
#define DOE_START_PENDING 0x00000010
Definition at line 1447 of file io.h.
Referenced by IopAttachDeviceToDeviceStackSafe(), and IopCheckDeviceAndDriver().
#define DOE_STARTIO_CANCELABLE 0x00000080
Definition at line 1450 of file io.h.
Referenced by IopStartNextPacketByKeyEx(), IoStartNextPacket(), and IoStartNextPacketByKey().
#define DOE_STARTIO_DEFERRED 0x00000100
Definition at line 1451 of file io.h.
Referenced by IoSetStartIoAttributes(), IoStartNextPacket(), and IoStartNextPacketByKey().
#define DOE_STARTIO_NO_CANCEL 0x00000200
Definition at line 1452 of file io.h.
Referenced by IopStartNextPacket(), IopStartNextPacketByKey(), IoSetStartIoAttributes(), and IoStartPacket().
#define DOE_STARTIO_REQUESTED 0x00000020
Definition at line 1448 of file io.h.
Referenced by IopStartNextPacketByKeyEx(), and IoStartNextPacket().
#define DOE_STARTIO_REQUESTED_BYKEY 0x00000040
Definition at line 1449 of file io.h.
Referenced by IopStartNextPacketByKeyEx(), and IoStartNextPacketByKey().
#define DOE_UNLOAD_PENDING 0x00000001
Definition at line 1443 of file io.h.
Referenced by IoDetachDevice(), IoGetLowerDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCheckDeviceAndDriver(), IopCheckUnloadDriver(), IopCompleteUnloadOrDelete(), IopDecrementDeviceObjectRef(), IopResurrectDriver(), and IoStartTimer().
#define DRVO_BASE_FILESYSTEM_DRIVER 0x00000080
Definition at line 1542 of file io.h.
Referenced by IopCheckUnloadDriver(), IopCompleteUnloadOrDelete(), and IoRegisterFileSystem().
#define DRVO_BOOTREINIT_REGISTERED 0x00000020
Definition at line 1539 of file io.h.
Referenced by IopCallBootDriverReinitializationRoutines(), and IoRegisterBootDriverReinitialization().
#define DRVO_BUILTIN_DRIVER 0x00000004
Definition at line 1535 of file io.h.
Referenced by IoCreateDriver().
#define DRVO_INITIALIZED 0x00000010
Definition at line 1538 of file io.h.
Referenced by IopReadyDeviceObjects().
#define DRVO_LEGACY_DRIVER 0x00000002
Definition at line 1534 of file io.h.
Referenced by IopInitializeBuiltinDriver(), and IopLoadDriver().
#define DRVO_LEGACY_RESOURCES 0x00000040
Definition at line 1540 of file io.h.
#define DRVO_REINIT_REGISTERED 0x00000008
Definition at line 1537 of file io.h.
Referenced by IopCallDriverReinitializationRoutines(), and IoRegisterDriverReinitialization().
#define DRVO_UNLOAD_INVOKED 0x00000001
Definition at line 1533 of file io.h.
Referenced by IoCreateDevice(), IopCheckUnloadDriver(), IopCompleteUnloadOrDelete(), IopLoadDriver(), and IopResurrectDriver().
#define FO_ALERTABLE_IO 0x00000004
Definition at line 1739 of file io.h.
Referenced by BuildQueryDirectoryIrp(), IopGetModeInformation(), IopGetSetSecurityObject(), IopParseDevice(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopSynchronousServiceTail(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), and NtWriteFileGather().
#define FO_CACHE_SUPPORTED 0x00000040
Definition at line 1743 of file io.h.
#define FO_CLEANUP_COMPLETE 0x00004000
Definition at line 1751 of file io.h.
Referenced by FsRtlNotifyFilterChangeDirectory(), and FsRtlOplockFsctrl().
#define FO_DELETE_ON_CLOSE 0x00010000
Definition at line 1753 of file io.h.
Referenced by IopGetModeInformation().
#define FO_DIRECT_DEVICE_OPEN 0x00000800
Definition at line 1748 of file io.h.
Referenced by IoGetBaseFileSystemDeviceObject(), IoGetRelatedDeviceObject(), IopCloseFile(), IopDeleteFile(), IopGetSetSecurityObject(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopXxxControlFile(), NtQueryInformationFile(), NtQueryVolumeInformationFile(), NtSetInformationFile(), and NtUnlockFile().
#define FO_FILE_FAST_IO_READ 0x00080000
Definition at line 1756 of file io.h.
Referenced by FsRtlCopyRead(), and FsRtlMdlReadDev().
#define FO_FILE_MODIFIED 0x00001000
Definition at line 1749 of file io.h.
Referenced by FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
#define FO_FILE_OBJECT_HAS_EXTENSION 0x00800000
Definition at line 1760 of file io.h.
Referenced by IoChangeFileObjectFilterContext(), IoCheckShareAccess(), IoGetFileObjectFilterContext(), IoGetRelatedDeviceObject(), IopDeleteFile(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IoRemoveShareAccess(), IoSetShareAccess(), and IoUpdateShareAccess().
#define FO_FILE_OPEN 0x00000001
Definition at line 1737 of file io.h.
#define FO_FILE_OPEN_CANCELLED 0x00200000
Definition at line 1758 of file io.h.
Referenced by IoCancelFileOpen(), IopDeleteFile(), and IopParseDevice().
#define FO_FILE_SIZE_CHANGED 0x00002000
Definition at line 1750 of file io.h.
Referenced by FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
#define FO_GENERATE_AUDIT_ON_CLOSE 0x00000400
Definition at line 1747 of file io.h.
#define FO_HANDLE_CREATED 0x00040000
Definition at line 1755 of file io.h.
Referenced by IoCancelFileOpen(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopCloseFile(), IopCreateFile(), and IopDeleteFile().
#define FO_MAILSLOT 0x00000200
Definition at line 1746 of file io.h.
Referenced by NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define FO_NAMED_PIPE 0x00000080
Definition at line 1744 of file io.h.
Referenced by IoComputeDesiredAccessFileObject(), NtFlushBuffersFile(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define FO_NO_INTERMEDIATE_BUFFERING 0x00000008
Definition at line 1740 of file io.h.
Referenced by IopGetModeInformation(), IopParseDevice(), IoSetInformation(), NtReadFile(), NtReadFileScatter(), NtSetInformationFile(), NtWriteFile(), NtWriteFileGather(), and RawCreate().
#define FO_OPENED_CASE_SENSITIVE 0x00020000
Definition at line 1754 of file io.h.
Referenced by IopOpenLinkOrRenameTarget(), and IopParseDevice().
#define FO_RANDOM_ACCESS 0x00100000
Definition at line 1757 of file io.h.
Referenced by CcCopyRead(), CcFastCopyRead(), CcInitializeCacheMap(), CcMdlRead(), and IopParseDevice().
#define FO_REMOTE_ORIGIN 0x01000000
Definition at line 1761 of file io.h.
Referenced by IoIsFileOriginRemote(), and IoSetFileOrigin().
#define FO_SEQUENTIAL_ONLY 0x00000020
Definition at line 1742 of file io.h.
Referenced by CcInitializeCacheMap(), CcPerformReadAhead(), CcScheduleReadAhead(), IopGetModeInformation(), IopParseDevice(), IoSetInformation(), and NtSetInformationFile().
#define FO_STREAM_FILE 0x00000100
Definition at line 1745 of file io.h.
Referenced by IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopGetSetSecurityObject(), and RawClose().
#define FO_SYNCHRONOUS_IO 0x00000002
Definition at line 1738 of file io.h.
Referenced by BuildQueryDirectoryIrp(), IoIsOperationSynchronous(), IopAllocateIrpCleanup(), IopCloseFile(), IopCompleteRequest(), IopDeleteFile(), IopExceptionCleanup(), IopGetBasicInformationFile(), IopGetModeInformation(), IopGetSetSecurityObject(), IopParseDevice(), IopQueryNameInternal(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), and RawCompletionRoutine().
#define FO_TEMPORARY_FILE 0x00008000
Definition at line 1752 of file io.h.
Referenced by CcIsThereDirtyData(), and CcLazyWriteScan().
#define FO_VOLUME_OPEN 0x00400000
Definition at line 1759 of file io.h.
Referenced by IopParseDevice().
#define FO_WRITE_THROUGH 0x00000010
Definition at line 1741 of file io.h.
Referenced by CcCanIWrite(), CcCopyWrite(), CcFastCopyWrite(), CcMapAndCopy(), CcMdlWriteComplete2(), CcPrepareMdlWrite(), CcZeroData(), FsRtlCopyWrite(), FsRtlMdlWriteCompleteDev(), FsRtlPrepareMdlWriteDev(), IopGetModeInformation(), IopParseDevice(), IoSetInformation(), NtSetInformationFile(), NtWriteFile(), and NtWriteFileGather().
#define FS_FILTER_ACQUIRE_FOR_CC_FLUSH (UCHAR)-5
Definition at line 1116 of file io.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), and FsRtlAcquireFileForCcFlushEx().
#define FS_FILTER_ACQUIRE_FOR_MOD_WRITE (UCHAR)-3
Definition at line 1114 of file io.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), and FsRtlAcquireFileForModWriteEx().
#define FS_FILTER_ACQUIRE_FOR_SECTION_SYNCHRONIZATION (UCHAR)-1
Definition at line 1112 of file io.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), and FsRtlAcquireFileExclusiveCommon().
#define FS_FILTER_RELEASE_FOR_CC_FLUSH (UCHAR)-6
Definition at line 1117 of file io.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), and FsRtlReleaseFileForCcFlush().
#define FS_FILTER_RELEASE_FOR_MOD_WRITE (UCHAR)-4
Definition at line 1115 of file io.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), and FsRtlReleaseFileForModWrite().
#define FS_FILTER_RELEASE_FOR_SECTION_SYNCHRONIZATION (UCHAR)-2
Definition at line 1113 of file io.h.
Referenced by FsFilterAllocateCompletionStack(), FsFilterFreeCompletionStack(), FsFilterGetCallbacks(), and FsRtlReleaseFile().
#define IO_ATTACH_DEVICE 0x0400
Definition at line 255 of file io.h.
Referenced by IopCheckDeviceAndDriver(), and IopCreateFile().
#define IO_ATTACH_DEVICE_API 0x80000000
Definition at line 274 of file io.h.
Referenced by IoAttachDevice(), and IopCreateFile().
#define IO_CHECK_CREATE_PARAMETERS 0x0200
Definition at line 254 of file io.h.
Referenced by IopCreateFile().
#define IO_DUMP_COMMON_BUFFER_SIZE 0x2000
Definition at line 483 of file io.h.
#define IO_DUMP_MAX_MDL_PAGES 8
Definition at line 481 of file io.h.
#define IO_DUMP_MEMORY_BLOCK_PAGES 16
Definition at line 482 of file io.h.
#define IO_DUMP_WRITE_DATA_PAGES 2
Definition at line 321 of file io.h.
#define IO_DUMP_WRITE_DATA_SIZE (IO_DUMP_WRITE_DATA_PAGES << PAGE_SHIFT)
Definition at line 322 of file io.h.
#define IO_DUMP_WRITE_FINISH 3
Definition at line 316 of file io.h.
#define IO_DUMP_WRITE_FULFILL 0
Definition at line 313 of file io.h.
#define IO_DUMP_WRITE_INIT 4
Definition at line 317 of file io.h.
#define IO_DUMP_WRITE_RESUME 2
Definition at line 315 of file io.h.
#define IO_DUMP_WRITE_START 1
Definition at line 314 of file io.h.
#define IO_FILE_OBJECT_NON_PAGED_POOL_CHARGE 64
Definition at line 2891 of file io.h.
Referenced by IopCreateObjectTypes().
#define IO_FILE_OBJECT_PAGED_POOL_CHARGE 1024
Definition at line 2892 of file io.h.
Referenced by IopCreateObjectTypes().
#define IO_FORCE_ACCESS_CHECK 0x0001
Definition at line 231 of file io.h.
Referenced by IoFastQueryNetworkAttributes(), IopOpenLinkOrRenameTarget(), and IopParseDevice().
#define IO_IGNORE_SHARE_ACCESS_CHECK 0x0800
Definition at line 267 of file io.h.
Referenced by IoCreateFileSpecifyDeviceObjectHint().
#define IO_NO_PARAMETER_CHECKING 0x0100
Definition at line 242 of file io.h.
Referenced by IoCreateFileSpecifyDeviceObjectHint(), IopCreateFile(), IopOpenLinkOrRenameTarget(), and NtCreatePagingFile().
#define IO_OPEN_PAGING_FILE 0x0002
Definition at line 234 of file io.h.
Referenced by NtCreatePagingFile().
#define IO_OPEN_TARGET_DIRECTORY 0x0004
Definition at line 235 of file io.h.
Referenced by IopOpenLinkOrRenameTarget().
#define IO_REMOUNT 0x1
Definition at line 250 of file io.h.
Referenced by IopParseDevice().
#define IO_REPARSE 0x0
Definition at line 249 of file io.h.
Referenced by IopParseDevice().
#define IO_TYPE_ADAPTER 0x00000001
Definition at line 31 of file io.h.
#define IO_TYPE_CONTROLLER 0x00000002
Definition at line 32 of file io.h.
Referenced by IoCreateController().
#define IO_TYPE_CSQ 2
Definition at line 5530 of file io.h.
Referenced by IoCsqInitialize(), and IopCsqCancelRoutine().
#define IO_TYPE_CSQ_EX 3
Definition at line 5531 of file io.h.
Referenced by IoCsqInitializeEx(), IoCsqInsertIrpEx(), and IopCsqCancelRoutine().
#define IO_TYPE_CSQ_IRP_CONTEXT 1
Definition at line 5529 of file io.h.
Referenced by IoCsqInsertIrpEx(), IoCsqRemoveNextIrp(), and IopCsqCancelRoutine().
#define IO_TYPE_DEVICE 0x00000003
Definition at line 33 of file io.h.
Referenced by IoAllocateErrorLogEntry(), IoCreateDevice(), and IopGetSetSecurityObject().
#define IO_TYPE_DEVICE_OBJECT_EXTENSION 0x0000000d
Definition at line 43 of file io.h.
Referenced by IoCreateDevice().
#define IO_TYPE_DRIVER 0x00000004
Definition at line 34 of file io.h.
Referenced by IoAllocateErrorLogEntry(), IoCreateDriver(), and IopLoadDriver().
#define IO_TYPE_ERROR_LOG 0x0000000b
Definition at line 41 of file io.h.
Referenced by IopAllocateErrorLogEntry().
#define IO_TYPE_ERROR_MESSAGE 0x0000000c
Definition at line 42 of file io.h.
Referenced by IopErrorLogThread().
#define IO_TYPE_FILE 0x00000005
Definition at line 35 of file io.h.
Referenced by IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IopCreateFile(), and IopParseDevice().
#define IO_TYPE_IRP 0x00000006
Definition at line 36 of file io.h.
Referenced by IoCancelIrp(), IoInitializeIrp(), IopfCallDriver(), IopfCompleteRequest(), and IopFreeIrp().
#define IO_TYPE_MASTER_ADAPTER 0x00000007
Definition at line 37 of file io.h.
#define IO_TYPE_OPEN_PACKET 0x00000008
Definition at line 38 of file io.h.
Referenced by IoFastQueryNetworkAttributes(), IopCreateFile(), IopParseDevice(), IopParseFile(), NtDeleteFile(), NtQueryAttributesFile(), and NtQueryFullAttributesFile().
#define IO_TYPE_TIMER 0x00000009
Definition at line 39 of file io.h.
Referenced by IoInitializeTimer().
#define IO_TYPE_VPB 0x0000000a
Definition at line 40 of file io.h.
Referenced by IopCreateVpb(), and RawCheckForDismount().
#define IoAcquireRemoveLock (RemoveLock, Tag) IoAcquireRemoveLockEx(RemoveLock, Tag, __FILE__, __LINE__, sizeof (IO_REMOVE_LOCK))
Definition at line 4547 of file io.h.
#define IoAssignArcName (ArcName, DeviceName)
Value:
(\
    IoCreateSymbolicLink( (ArcName), (DeviceName) ) )
Definition at line 3002 of file io.h.
#define IoCallDriver (a, b) IofCallDriver(a,b)
Definition at line 3186 of file io.h.
#define IoCompleteRequest (a, b) IofCompleteRequest(a,b)
Definition at line 3306 of file io.h.
#define IoCopyCurrentIrpStackLocationToNext (Irp)
Value:
{ \
    PIO_STACK_LOCATION __irpSp; \
    PIO_STACK_LOCATION __nextIrpSp; \
    __irpSp = IoGetCurrentIrpStackLocation( (Irp) ); \
    __nextIrpSp = IoGetNextIrpStackLocation( (Irp) ); \
    RtlCopyMemory( __nextIrpSp, __irpSp, FIELD_OFFSET(IO_STACK_LOCATION, CompletionRoutine)); \
    __nextIrpSp->Control = 0; }
Definition at line 4434 of file io.h.
#define IoDeassignArcName (ArcName)
Value:
(\
    IoDeleteSymbolicLink( (ArcName) ) )
Definition at line 3461 of file io.h.
#define IoForwardAndCatchIrp IoForwardIrpSynchronously
Definition at line 3660 of file io.h.
#define IoGetCurrentIrpStackLocation (Irp) ((Irp)->Tail.Overlay.CurrentStackLocation)
Definition at line 3609 of file io.h.
Referenced by FsRtlCancelNotify(), FsRtlCheckLockForReadAccess(), FsRtlCheckLockForWriteAccess(), FsRtlCheckOplock(), FsRtlNotifyCompleteIrp(), FsRtlNotifyFilterChangeDirectory(), FsRtlNotifyFilterReportChange(), FsRtlOplockCleanup(), FsRtlOplockFsctrl(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlProcessFileLock(), FsRtlRemoveAndCompleteIrp(), FsRtlUninitializeOplock(), IoIsOperationSynchronous(), IoIsValidNameGraftingBuffer(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopInvalidDeviceRequest(), IopRaiseHardError(), IoRaiseHardError(), IoValidateDeviceIoControlAccess(), IoWMICompleteRequest(), IoWMISystemControl(), RawCompletionRoutine(), RawDispatch(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipForwardWmiIrp(), WmipIoControl(), WmipSendWmiIrp(), WmipSetTraceNotify(), WmipTraceIo(), WmipTranslatePDOInstanceNames(), and WmipWriteWnodeToObject().
#define IoGetFunctionCodeFromCtlCode (ControlCode)
Value:
(\
    ( ControlCode >> 2) & 0x00000FFF )
Definition at line 3704 of file io.h.
#define IoGetNextIrpStackLocation (Irp)
Value:
(\
    (Irp)->Tail.Overlay.CurrentStackLocation - 1 )
Definition at line 3761 of file io.h.
Referenced by BuildQueryDirectoryIrp(), CcSetValidData(), FsRtlGetFileSize(), FsRtlSetFileSize(), HalExamineMBR(), IoAsynchronousPageWrite(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoCancelFileOpen(), IoPageRead(), IopCloseFile(), IopDeleteFile(), IopfCallDriver(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IopXxxControlFile(), IoReadPartitionTable(), IoSetInformation(), IoSetPartitionInformation(), IoSynchronousPageWrite(), IoVerifyVolume(), IoWritePartitionTable(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), RawReadWriteDeviceControl(), WmipForwardWmiIrp(), and WmipGetDevicePDO().
#define IoInitializeDpcRequest (DeviceObject, DpcRoutine)
Value:
(\
    KeInitializeDpc( &(DeviceObject)->Dpc,                  \
                     (PKDEFERRED_ROUTINE) (DpcRoutine),     \
                     (DeviceObject) ) )
Definition at line 3830 of file io.h.
#define IoInitializeRemoveLock (Lock, Tag, Maxmin, HighWater) IoInitializeRemoveLockEx (Lock, Tag, Maxmin, HighWater, sizeof (IO_REMOVE_LOCK))
Definition at line 4526 of file io.h.
#define IoInitializeThreadedDpcRequest (DeviceObject, DpcRoutine)
Value:
(\
    KeInitializeThreadedDpc( &(DeviceObject)->Dpc,                  \
                     (PKDEFERRED_ROUTINE) (DpcRoutine),           \
                     (DeviceObject) ) )
Definition at line 3836 of file io.h.
#define IoIsErrorUserInduced (Status)
Value:
((BOOLEAN)  \
    (((Status) == STATUS_DEVICE_NOT_READY) ||      \
     ((Status) == STATUS_IO_TIMEOUT) ||            \
     ((Status) == STATUS_MEDIA_WRITE_PROTECTED) || \
     ((Status) == STATUS_NO_MEDIA_IN_DEVICE) ||    \
     ((Status) == STATUS_VERIFY_REQUIRED) ||       \
     ((Status) == STATUS_UNRECOGNIZED_MEDIA) ||    \
     ((Status) == STATUS_WRONG_VOLUME)))
Definition at line 3909 of file io.h.
Referenced by IopMountVolume().
#define IoIsFileOpenedExclusively (FileObject)
Value:
(\
    (BOOLEAN) !((FileObject)->SharedRead || (FileObject)->SharedWrite || (FileObject)->SharedDelete))
Definition at line 3944 of file io.h.
#define IoMarkIrpPending (Irp)
Value:
(\
    IoGetCurrentIrpStackLocation( (Irp) )->Control |= SL_PENDING_RETURNED )
Definition at line 4001 of file io.h.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCancelNotify(), FsRtlNotifyCompleteIrp(), FsRtlNotifyFilterChangeDirectory(), FsRtlPrivateLock(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlWaitOnIrp(), IoCsqInsertIrpEx(), IopfCompleteRequest(), RawCompletionRoutine(), WmipForwardWmiIrp(), and WmipReceiveNotifications().
#define IoReleaseRemoveLock (RemoveLock, Tag) IoReleaseRemoveLockEx(RemoveLock, Tag, sizeof (IO_REMOVE_LOCK))
Definition at line 4596 of file io.h.
#define IoReleaseRemoveLockAndWait (RemoveLock, Tag) IoReleaseRemoveLockAndWaitEx(RemoveLock, Tag, sizeof (IO_REMOVE_LOCK))
Definition at line 4632 of file io.h.
#define IoRequestDpc (DeviceObject, Irp, Context)
Value:
(\
    KeInsertQueueDpc( &(DeviceObject)->Dpc, (Irp), (Context) ) )
Definition at line 4248 of file io.h.
#define IoSetCancelRoutine (Irp, NewCancelRoutine)
Value:
(\
    (PDRIVER_CANCEL) (ULONG_PTR) InterlockedExchangePointer( (PVOID *) &(Irp)->CancelRoutine, (PVOID) (ULONG_PTR)(NewCancelRoutine) ) )
Definition at line 4277 of file io.h.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCancelExclusiveIrp(), FsRtlCancelNotify(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlNotifySetCancelRoutine(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlPrivateLock(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeFileLock(), FsRtlUninitializeOplock(), FsRtlWaitOnIrp(), IoCsqInsertIrpEx(), IoCsqRemoveIrp(), IoCsqRemoveNextIrp(), WmipCompleteGuidIrpWithError(), WmipDeleteMethod(), WmipReceiveNotifications(), and WmipWriteWnodeToObject().
#define IoSetCompletionRoutine (Irp, Routine, CompletionContext, Success, Error, Cancel)
Value:
{ \
    PIO_STACK_LOCATION __irpSp;                                               \
    ASSERT( ((Success) | (Error) | (Cancel)) ? (Routine) != NULL : TRUE );    \
    __irpSp = IoGetNextIrpStackLocation( (Irp) );                             \
    __irpSp->CompletionRoutine = (Routine);                                   \
    __irpSp->Context = (CompletionContext);                                   \
    __irpSp->Control = 0;                                                     \
    if ((Success)) { __irpSp->Control = SL_INVOKE_ON_SUCCESS; }               \
    if ((Error)) { __irpSp->Control |= SL_INVOKE_ON_ERROR; }                  \
    if ((Cancel)) { __irpSp->Control |= SL_INVOKE_ON_CANCEL; } }
Definition at line 4323 of file io.h.
Referenced by IoSetCompletionRoutineEx(), RawReadWriteDeviceControl(), and WmipForwardWmiIrp().
#define IoSetNextIrpStackLocation (Irp)
Value:
{      \
    (Irp)->CurrentLocation--;                   \
    (Irp)->Tail.Overlay.CurrentStackLocation--; }
Definition at line 4402 of file io.h.
Referenced by IopParseDevice(), IoSetInformation(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipSendWmiIrp(), and WmipSetTraceNotify().
#define IoSizeOfIrp (StackSize) ((USHORT) (sizeof(IRP) + ((StackSize) * (sizeof(IO_STACK_LOCATION)))))
Definition at line 4694 of file io.h.
Referenced by IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), IopAllocateReserveIrp(), IopFreeIrp(), IoReuseIrp(), WmipDisableKernelTrace(), and WmipEnableKernelTrace().
#define IoSkipCurrentIrpStackLocation (Irp)
Value:
{ \
    (Irp)->CurrentLocation++; \
    (Irp)->Tail.Overlay.CurrentStackLocation++; }
Definition at line 4469 of file io.h.
Referenced by IoWMISystemControl().
#define IoWMIDeviceObjectToProviderId (DeviceObject) ((ULONG)(DeviceObject))
Definition at line 5001 of file io.h.
Referenced by WmipBuildMcaCmcEvent(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
#define IRP_ALLOCATED_FIXED_SIZE 0x04
Definition at line 1839 of file io.h.
Referenced by IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), and IopFreeIrp().
#define IRP_ALLOCATED_MUST_SUCCEED 0x02
Definition at line 1838 of file io.h.
Referenced by IopFreeIrp().
#define IRP_ASSOCIATED_IRP 0x00000008
Definition at line 1802 of file io.h.
Referenced by IoMakeAssociatedIrp(), IopfCompleteRequest(), and WmipTraceIo().
#define IRP_BUFFERED_IO 0x00000010
Definition at line 1803 of file io.h.
Referenced by BuildQueryDirectoryIrp(), FsRtlNotifyCompleteIrp(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopCompleteRequest(), IopGetFileInformation(), IopParseDevice(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), IoSetInformation(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), and NtWriteFile().
#define IRP_CLOSE_OPERATION 0x00000400
Definition at line 1810 of file io.h.
Referenced by IoCancelFileOpen(), IopCloseFile(), IopDeleteFile(), and IopfCompleteRequest().
#define IRP_CREATE_OPERATION 0x00000080
Definition at line 1807 of file io.h.
Referenced by IopCompleteRequest(), IopDropIrp(), IopParseDevice(), and IoRetryIrpCompletions().
#define IRP_DEALLOCATE_BUFFER 0x00000020
Definition at line 1804 of file io.h.
Referenced by BuildQueryDirectoryIrp(), FsRtlNotifyCompleteIrp(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopCompleteRequest(), IopDropIrp(), IopParseDevice(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), and NtWriteFile().
#define IRP_DEFER_IO_COMPLETION 0x00000800
Definition at line 1813 of file io.h.
Referenced by BuildQueryDirectoryIrp(), IopfCompleteRequest(), IopParseDevice(), IopXxxControlFile(), NtQueryInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetInformationFile(), NtWriteFile(), and NtWriteFileGather().
#define IRP_HIGH_PRIORITY_PAGING_IO 0x00008000
Definition at line 1820 of file io.h.
Referenced by IoAsynchronousPageWrite(), IoGetPagingIoPriority(), and IoMakeAssociatedIrp().
#define IRP_HOLD_DEVICE_QUEUE 0x00002000
Definition at line 1815 of file io.h.
#define IRP_INPUT_OPERATION 0x00000040
Definition at line 1805 of file io.h.
Referenced by BuildQueryDirectoryIrp(), FsRtlNotifyCompleteIrp(), FsRtlOplockFsctrl(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoPageRead(), IopCompleteRequest(), IopRaiseHardError(), IopXxxControlFile(), IoRaiseHardError(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), and NtReadFile().
#define IRP_LOOKASIDE_ALLOCATION 0x08
Definition at line 1840 of file io.h.
Referenced by IopAllocateIrpPrivate(), and IopFreeIrp().
#define IRP_MJ_CLEANUP 0x12
Definition at line 69 of file io.h.
Referenced by FsRtlCheckOplock(), IoCancelFileOpen(), IopCloseFile(), IoRaiseHardError(), RawDispatch(), RawInitialize(), and WmipDriverEntry().
#define IRP_MJ_CLOSE 0x02
Definition at line 53 of file io.h.
Referenced by IoCheckFunctionAccess(), IopDeleteFile(), RawDispatch(), RawInitialize(), and WmipDriverEntry().
#define IRP_MJ_CREATE 0x00
Definition at line 51 of file io.h.
Referenced by FsRtlCheckOplock(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockFsctrl(), IoCheckFunctionAccess(), IopParseDevice(), RawDispatch(), RawInitialize(), and WmipDriverEntry().
#define IRP_MJ_CREATE_MAILSLOT 0x13
Definition at line 70 of file io.h.
Referenced by IopParseDevice().
#define IRP_MJ_CREATE_NAMED_PIPE 0x01
Definition at line 52 of file io.h.
Referenced by IopParseDevice().
#define IRP_MJ_DEVICE_CHANGE 0x18
Definition at line 75 of file io.h.
#define IRP_MJ_DEVICE_CONTROL 0x0e
Definition at line 65 of file io.h.
Referenced by IoBuildDeviceIoControlRequest(), IoCheckFunctionAccess(), IopLoadFileSystemDriver(), IopXxxControlFile(), IoValidateDeviceIoControlAccess(), RawDispatch(), RawInitialize(), and WmipDriverEntry().
#define IRP_MJ_DIRECTORY_CONTROL 0x0c
Definition at line 63 of file io.h.
Referenced by BuildQueryDirectoryIrp(), IoCheckFunctionAccess(), and NtNotifyChangeDirectoryFile().
#define IRP_MJ_FILE_SYSTEM_CONTROL 0x0d
Definition at line 64 of file io.h.
Referenced by FsRtlCheckOplock(), IoCheckFunctionAccess(), IopGetSetObjectId(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopRaiseHardError(), IopSetRemoteLink(), IopXxxControlFile(), IoRaiseHardError(), IoValidateDeviceIoControlAccess(), IoVerifyVolume(), RawDispatch(), and RawInitialize().
#define IRP_MJ_FLUSH_BUFFERS 0x09
Definition at line 60 of file io.h.
Referenced by FsRtlCheckOplock(), IoBuildAsynchronousFsdRequest(), IoCheckFunctionAccess(), and NtFlushBuffersFile().
#define IRP_MJ_INTERNAL_DEVICE_CONTROL 0x0f
Definition at line 66 of file io.h.
Referenced by IoBuildDeviceIoControlRequest(), and IoCheckFunctionAccess().
#define IRP_MJ_LOCK_CONTROL 0x11
Definition at line 68 of file io.h.
Referenced by FsRtlCheckOplock(), FsRtlProcessFileLock(), IoCheckFunctionAccess(), IopCloseFile(), NtLockFile(), and NtUnlockFile().
#define IRP_MJ_MAXIMUM_FUNCTION 0x1b
Definition at line 80 of file io.h.
Referenced by IoCreateDriver(), and IopLoadDriver().
#define IRP_MJ_PNP 0x1b
Definition at line 78 of file io.h.
Referenced by IoBuildAsynchronousFsdRequest(), RawDispatch(), RawInitialize(), and WmipGetDevicePDO().
#define IRP_MJ_PNP_POWER IRP_MJ_PNP
Definition at line 79 of file io.h.
#define IRP_MJ_POWER 0x16
Definition at line 73 of file io.h.
Referenced by IoBuildAsynchronousFsdRequest(), and IopInvalidDeviceRequest().
#define IRP_MJ_QUERY_EA 0x07
Definition at line 58 of file io.h.
Referenced by IoCheckFunctionAccess(), and NtQueryEaFile().
#define IRP_MJ_QUERY_INFORMATION 0x05
Definition at line 56 of file io.h.
Referenced by FsRtlGetFileSize(), IoCheckFunctionAccess(), IopGetFileInformation(), IopQueryXxxInformation(), NtQueryInformationFile(), RawDispatch(), and RawInitialize().
#define IRP_MJ_QUERY_QUOTA 0x19
Definition at line 76 of file io.h.
Referenced by NtQueryQuotaInformationFile().
#define IRP_MJ_QUERY_SECURITY 0x14
Definition at line 71 of file io.h.
Referenced by IoCheckFunctionAccess(), and IopGetSetSecurityObject().
#define IRP_MJ_QUERY_VOLUME_INFORMATION 0x0a
Definition at line 61 of file io.h.
Referenced by IoCheckFunctionAccess(), IopGetVolumeId(), IopQueryXxxInformation(), NtQueryVolumeInformationFile(), RawDispatch(), and RawInitialize().
#define IRP_MJ_READ 0x03
Definition at line 54 of file io.h.
Referenced by FsRtlCheckOplock(), HalExamineMBR(), IoBuildAsynchronousFsdRequest(), IoCheckFunctionAccess(), IoPageRead(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IoReadPartitionTable(), IoSetPartitionInformation(), IoWritePartitionTable(), NtReadFile(), NtReadFileScatter(), RawCompletionRoutine(), RawDispatch(), RawInitialize(), RawReadWriteDeviceControl(), and WmipTraceIo().
#define IRP_MJ_SCSI IRP_MJ_INTERNAL_DEVICE_CONTROL
Definition at line 86 of file io.h.
#define IRP_MJ_SET_EA 0x08
Definition at line 59 of file io.h.
Referenced by IoCheckFunctionAccess(), IopSetEaOrQuotaInformationFile(), and NtSetEaFile().
#define IRP_MJ_SET_INFORMATION 0x06
Definition at line 57 of file io.h.
Referenced by CcSetValidData(), FsRtlCheckOplock(), FsRtlSetFileSize(), IoCheckFunctionAccess(), IoSetInformation(), NtSetInformationFile(), RawDispatch(), and RawInitialize().
#define IRP_MJ_SET_QUOTA 0x1a
Definition at line 77 of file io.h.
Referenced by IopSetEaOrQuotaInformationFile().
#define IRP_MJ_SET_SECURITY 0x15
Definition at line 72 of file io.h.
Referenced by IoCheckFunctionAccess(), and IopGetSetSecurityObject().
#define IRP_MJ_SET_VOLUME_INFORMATION 0x0b
Definition at line 62 of file io.h.
Referenced by IoCheckFunctionAccess(), and NtSetVolumeInformationFile().
#define IRP_MJ_SHUTDOWN 0x10
Definition at line 67 of file io.h.
Referenced by IoBuildAsynchronousFsdRequest(), IopShutdownBaseFileSystems(), IoShutdownSystem(), RawInitialize(), and WmipDriverEntry().
#define IRP_MJ_SYSTEM_CONTROL 0x17
Definition at line 74 of file io.h.
Referenced by WmipDriverEntry(), and WmipForwardWmiIrp().
#define IRP_MJ_WRITE 0x04
Definition at line 55 of file io.h.
Referenced by CcWriteBehind(), FsRtlCheckOplock(), IoAsynchronousPageWrite(), IoBuildAsynchronousFsdRequest(), IoCheckFunctionAccess(), IoSetPartitionInformation(), IoSynchronousPageWrite(), IoWritePartitionTable(), NtWriteFile(), NtWriteFileGather(), RawCompletionRoutine(), RawDispatch(), RawInitialize(), and RawReadWriteDeviceControl().
#define IRP_MN_CANCEL_REMOVE_DEVICE 0x03
Definition at line 159 of file io.h.
#define IRP_MN_CANCEL_STOP_DEVICE 0x06
Definition at line 162 of file io.h.
#define IRP_MN_CHANGE_SINGLE_INSTANCE 0x02
Definition at line 200 of file io.h.
Referenced by IoWMISetSingleInstance(), IoWMISystemControl(), WmipForwardWmiIrp(), and WmipIoControl().
#define IRP_MN_CHANGE_SINGLE_ITEM 0x03
Definition at line 201 of file io.h.
Referenced by IoWMISetSingleItem(), IoWMISystemControl(), WmipIoControl(), and WmipQuerySetExecuteSI().
#define IRP_MN_COMPLETE 0x04
Definition at line 137 of file io.h.
#define IRP_MN_COMPLETE_MDL (IRP_MN_COMPLETE | IRP_MN_MDL)
Definition at line 141 of file io.h.
#define IRP_MN_COMPLETE_MDL_DPC (IRP_MN_COMPLETE_MDL | IRP_MN_DPC)
Definition at line 142 of file io.h.
#define IRP_MN_COMPRESSED 0x08
Definition at line 138 of file io.h.
#define IRP_MN_DEVICE_USAGE_NOTIFICATION 0x16
Definition at line 179 of file io.h.
#define IRP_MN_DISABLE_COLLECTION 0x07
Definition at line 205 of file io.h.
Referenced by IoWMISystemControl(), WmipDisableCollectionForRemovedGuid(), WmipDoDisableRequest(), and WmipSendEnableRequest().
#define IRP_MN_DISABLE_EVENTS 0x05
Definition at line 203 of file io.h.
Referenced by IoWMISystemControl(), WmipDisableCollectionForRemovedGuid(), WmipDoDisableRequest(), and WmipSendEnableRequest().
#define IRP_MN_DPC 0x01
Definition at line 135 of file io.h.
#define IRP_MN_EJECT 0x11
Definition at line 174 of file io.h.
#define IRP_MN_ENABLE_COLLECTION 0x06
Definition at line 204 of file io.h.
Referenced by IoWMISystemControl(), WmipDoDisableRequest(), WmipEnableCollectionForNewGuid(), WmipSendEnableDisableRequest(), and WmipSendEnableRequest().
#define IRP_MN_ENABLE_EVENTS 0x04
Definition at line 202 of file io.h.
Referenced by IoWMISystemControl(), WmipDoDisableRequest(), WmipEnableCollectionForNewGuid(), WmipSendEnableDisableRequest(), and WmipSendEnableRequest().
#define IRP_MN_EXECUTE_METHOD 0x09
Definition at line 207 of file io.h.
Referenced by IoWMICompleteRequest(), IoWMIExecuteMethod(), IoWMISystemControl(), WmipIoControl(), and WmipQuerySetExecuteSI().
#define IRP_MN_FILTER_RESOURCE_REQUIREMENTS 0x0D
Definition at line 170 of file io.h.
#define IRP_MN_KERNEL_CALL 0x04
Definition at line 113 of file io.h.
Referenced by IopGetSetObjectId(), and IopSetRemoteLink().
#define IRP_MN_LOAD_FILE_SYSTEM 0x03
Definition at line 111 of file io.h.
Referenced by IopLoadFileSystemDriver().
#define IRP_MN_LOCK 0x01
Definition at line 119 of file io.h.
Referenced by FsRtlProcessFileLock(), and NtLockFile().
#define IRP_MN_MDL 0x02
Definition at line 136 of file io.h.
#define IRP_MN_MDL_DPC (IRP_MN_MDL | IRP_MN_DPC)
Definition at line 140 of file io.h.
#define IRP_MN_MOUNT_VOLUME 0x01
Definition at line 109 of file io.h.
Referenced by IopMountVolume(), IopRaiseHardError(), IoRaiseHardError(), RawDispatch(), and RawFileSystemControl().
#define IRP_MN_NORMAL 0x00
Definition at line 134 of file io.h.
#define IRP_MN_NOTIFY_CHANGE_DIRECTORY 0x02
Definition at line 100 of file io.h.
Referenced by NtNotifyChangeDirectoryFile().
#define IRP_MN_POWER_SEQUENCE 0x01
Definition at line 189 of file io.h.
#define IRP_MN_QUERY_ALL_DATA 0x00
Definition at line 198 of file io.h.
Referenced by IoWMICompleteRequest(), IoWMISystemControl(), WmipForwardWmiIrp(), WmipQueryAllData(), and WmipQuerySetExecuteSI().
#define IRP_MN_QUERY_BUS_INFORMATION 0x15
Definition at line 178 of file io.h.
#define IRP_MN_QUERY_CAPABILITIES 0x09
Definition at line 166 of file io.h.
#define IRP_MN_QUERY_DEVICE_RELATIONS 0x07
Definition at line 164 of file io.h.
Referenced by WmipGetDevicePDO().
#define IRP_MN_QUERY_DEVICE_TEXT 0x0C
Definition at line 169 of file io.h.
#define IRP_MN_QUERY_DIRECTORY 0x01
Definition at line 99 of file io.h.
Referenced by BuildQueryDirectoryIrp(), and NtQueryDirectoryFile().
#define IRP_MN_QUERY_ID 0x13
Definition at line 176 of file io.h.
#define IRP_MN_QUERY_INTERFACE 0x08
Definition at line 165 of file io.h.
#define IRP_MN_QUERY_LEGACY_BUS_INFORMATION 0x18
Definition at line 182 of file io.h.
#define IRP_MN_QUERY_PNP_DEVICE_STATE 0x14
Definition at line 177 of file io.h.
#define IRP_MN_QUERY_POWER 0x03
Definition at line 191 of file io.h.
#define IRP_MN_QUERY_REMOVE_DEVICE 0x01
Definition at line 157 of file io.h.
Referenced by RawDispatch().
#define IRP_MN_QUERY_RESOURCE_REQUIREMENTS 0x0B
Definition at line 168 of file io.h.
#define IRP_MN_QUERY_RESOURCES 0x0A
Definition at line 167 of file io.h.
#define IRP_MN_QUERY_SINGLE_INSTANCE 0x01
Definition at line 199 of file io.h.
Referenced by IoWMICompleteRequest(), IoWMIQuerySingleInstance(), IoWMISystemControl(), WmipDereferenceEvent(), WmipForwardWmiIrp(), WmipIoControl(), and WmipQuerySingleMultiple().
#define IRP_MN_QUERY_STOP_DEVICE 0x05
Definition at line 161 of file io.h.
#define IRP_MN_READ_CONFIG 0x0F
Definition at line 172 of file io.h.
#define IRP_MN_REGINFO 0x08
Definition at line 206 of file io.h.
Referenced by IoWMISystemControl(), WmipForwardWmiIrp(), and WmipRegisterOrUpdateDS().
#define IRP_MN_REGINFO_EX 0x0b
Definition at line 209 of file io.h.
Referenced by IoWMISystemControl(), WmipForwardWmiIrp(), WmipRegisterOrUpdateDS(), and WmipTranslatePDOInstanceNames().
#define IRP_MN_REMOVE_DEVICE 0x02
Definition at line 158 of file io.h.
#define IRP_MN_SCSI_CLASS 0x01
Definition at line 150 of file io.h.
#define IRP_MN_SET_LOCK 0x12
Definition at line 175 of file io.h.
#define IRP_MN_SET_POWER 0x02
Definition at line 190 of file io.h.
#define IRP_MN_SET_TRACE_NOTIFY 0x0A
Definition at line 218 of file io.h.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
#define IRP_MN_START_DEVICE 0x00
Definition at line 156 of file io.h.
#define IRP_MN_STOP_DEVICE 0x04
Definition at line 160 of file io.h.
#define IRP_MN_SURPRISE_REMOVAL 0x17
Definition at line 180 of file io.h.
#define IRP_MN_TRACK_LINK 0x04
Definition at line 112 of file io.h.
#define IRP_MN_UNLOCK_ALL 0x03
Definition at line 121 of file io.h.
Referenced by FsRtlProcessFileLock(), and IopCloseFile().
#define IRP_MN_UNLOCK_ALL_BY_KEY 0x04
Definition at line 122 of file io.h.
Referenced by FsRtlProcessFileLock().
#define IRP_MN_UNLOCK_SINGLE 0x02
Definition at line 120 of file io.h.
Referenced by FsRtlProcessFileLock(), and NtUnlockFile().
#define IRP_MN_USER_FS_REQUEST 0x00
Definition at line 108 of file io.h.
Referenced by RawFileSystemControl().
#define IRP_MN_VERIFY_VOLUME 0x02
Definition at line 110 of file io.h.
Referenced by IoVerifyVolume(), and RawFileSystemControl().
#define IRP_MN_WAIT_WAKE 0x00
Definition at line 188 of file io.h.
#define IRP_MN_WRITE_CONFIG 0x10
Definition at line 173 of file io.h.
#define IRP_MOUNT_COMPLETION 0x00000002
Definition at line 1800 of file io.h.
Referenced by IopMountVolume(), and IoVerifyVolume().
#define IRP_NOCACHE 0x00000001
Definition at line 1798 of file io.h.
Referenced by IoAsynchronousPageWrite(), IoPageRead(), IoRaiseHardError(), IoSynchronousPageWrite(), NtReadFile(), NtReadFileScatter(), NtWriteFile(), and NtWriteFileGather().
#define IRP_OB_QUERY_NAME 0x00001000
Definition at line 1814 of file io.h.
Referenced by IopCompleteRequest(), and IopGetFileInformation().
#define IRP_PAGING_IO 0x00000002
Definition at line 1799 of file io.h.
Referenced by CcSetValidData(), FsRtlCheckOplock(), FsRtlGetFileSize(), FsRtlSetFileSize(), IoAsynchronousPageWrite(), IoGetPagingIoPriority(), IoIsOperationSynchronous(), IoPageRead(), IopfCompleteRequest(), IoRaiseHardError(), IoSynchronousPageWrite(), and WmipTraceIo().
#define IRP_QUOTA_CHARGED 0x01
Definition at line 1837 of file io.h.
Referenced by IopAllocateIrpPrivate(), and IopFreeIrp().
#define IRP_READ_OPERATION 0x00000100
Definition at line 1808 of file io.h.
Referenced by IopCompleteRequest(), NtReadFile(), and NtReadFileScatter().
#define IRP_RETRY_IO_COMPLETION 0x00004000
Definition at line 1819 of file io.h.
Referenced by IopCompleteRequest(), and IoRetryIrpCompletions().
#define IRP_SET_USER_EVENT IRP_CLOSE_OPERATION
Definition at line 1828 of file io.h.
Referenced by IoPageRead(), and IopfCompleteRequest().
#define IRP_SYNCHRONOUS_API 0x00000004
Definition at line 1801 of file io.h.
Referenced by IoCancelFileOpen(), IoIsOperationSynchronous(), IopCloseFile(), IopCompleteRequest(), IopDeleteFile(), IopDropIrp(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopParseDevice(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IoSetInformation(), NtFlushBuffersFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), and NtUnlockFile().
#define IRP_SYNCHRONOUS_PAGING_IO 0x00000040
Definition at line 1806 of file io.h.
Referenced by CcSetValidData(), FsRtlGetFileSize(), FsRtlSetFileSize(), IoIsOperationSynchronous(), IoPageRead(), IopfCompleteRequest(), IopMountVolume(), IoRaiseHardError(), IoSynchronousPageWrite(), and IoVerifyVolume().
#define IRP_VERIFIER_MASK 0xC0000000
Definition at line 1827 of file io.h.
Referenced by IoRaiseHardError().
#define IRP_WRITE_OPERATION 0x00000200
Definition at line 1809 of file io.h.
Referenced by IopCompleteRequest(), NtWriteFile(), and NtWriteFileGather().
#define MAXIMUM_VOLUME_LABEL_LENGTH (32 * sizeof(WCHAR))
Definition at line 1286 of file io.h.
Referenced by IopRaiseHardError().
#define PNP_DEVICE_DISABLED 0x00000001
Definition at line 2273 of file io.h.
#define PNP_DEVICE_DONT_DISPLAY_IN_UI 0x00000002
Definition at line 2274 of file io.h.
#define PNP_DEVICE_FAILED 0x00000004
Definition at line 2275 of file io.h.
#define PNP_DEVICE_NOT_DISABLEABLE 0x00000020
Definition at line 2278 of file io.h.
#define PNP_DEVICE_REMOVED 0x00000008
Definition at line 2276 of file io.h.
#define PNP_DEVICE_RESOURCE_REQUIREMENTS_CHANGED 0x00000010
Definition at line 2277 of file io.h.
#define POINTER_ALIGNMENT
Definition at line 2298 of file io.h.
#define SL_ALLOW_RAW_MOUNT 0x01
Definition at line 2179 of file io.h.
Referenced by IoVerifyVolume().
#define SL_CASE_SENSITIVE 0x80
Definition at line 2131 of file io.h.
Referenced by IopParseDevice().
#define SL_ERROR_RETURNED 0x02
Definition at line 2109 of file io.h.
Referenced by IoFindDeviceThatFailedIrp(), and IopfCompleteRequest().
#define SL_EXCLUSIVE_LOCK 0x02
Definition at line 2157 of file io.h.
Referenced by FsRtlPrivateCheckWaitingLocks(), FsRtlProcessFileLock(), and NtLockFile().
#define SL_FAIL_IMMEDIATELY 0x01
Definition at line 2156 of file io.h.
Referenced by FsRtlProcessFileLock(), and NtLockFile().
#define SL_FORCE_ACCESS_CHECK 0x01
Definition at line 2127 of file io.h.
#define SL_FT_SEQUENTIAL_WRITE 0x08
Definition at line 2140 of file io.h.
#define SL_INDEX_SPECIFIED 0x04
Definition at line 2165 of file io.h.
Referenced by NtQueryEaFile(), and NtQueryQuotaInformationFile().
#define SL_INVOKE_ON_CANCEL 0x20
Definition at line 2110 of file io.h.
Referenced by IopfCompleteRequest().
#define SL_INVOKE_ON_ERROR 0x80
Definition at line 2112 of file io.h.
Referenced by IopfCompleteRequest().
#define SL_INVOKE_ON_SUCCESS 0x40
Definition at line 2111 of file io.h.
Referenced by IopfCompleteRequest().
#define SL_KEY_SPECIFIED 0x01
Definition at line 2137 of file io.h.
#define SL_OPEN_PAGING_FILE 0x02
Definition at line 2128 of file io.h.
#define SL_OPEN_TARGET_DIRECTORY 0x04
Definition at line 2129 of file io.h.
#define SL_OVERRIDE_VERIFY_VOLUME 0x02
Definition at line 2138 of file io.h.
Referenced by HalExamineMBR(), IoReadPartitionTable(), IoSetPartitionInformation(), IoWritePartitionTable(), and RawReadWriteDeviceControl().
#define SL_PENDING_RETURNED 0x01
Definition at line 2108 of file io.h.
Referenced by FsRtlNotifyCompleteIrp(), and IopfCompleteRequest().
#define SL_READ_ACCESS_GRANTED 0x01
Definition at line 2149 of file io.h.
Referenced by IopXxxControlFile(), and IoValidateDeviceIoControlAccess().
#define SL_RESTART_SCAN 0x01
Definition at line 2163 of file io.h.
Referenced by BuildQueryDirectoryIrp(), NtQueryEaFile(), and NtQueryQuotaInformationFile().
#define SL_RETURN_SINGLE_ENTRY 0x02
Definition at line 2164 of file io.h.
Referenced by BuildQueryDirectoryIrp(), NtQueryEaFile(), and NtQueryQuotaInformationFile().
#define SL_WATCH_TREE 0x01
Definition at line 2171 of file io.h.
Referenced by NtNotifyChangeDirectoryFile().
#define SL_WRITE_ACCESS_GRANTED 0x04
Definition at line 2150 of file io.h.
Referenced by IopXxxControlFile(), and IoValidateDeviceIoControlAccess().
#define SL_WRITE_THROUGH 0x04
Definition at line 2139 of file io.h.
Referenced by NtWriteFile(), and NtWriteFileGather().
#define STATUS_CONTINUE_COMPLETION STATUS_SUCCESS
Definition at line 3286 of file io.h.
#define VPB_LOCKED 0x00000002
Definition at line 1276 of file io.h.
Referenced by IopCheckVpbMounted(), and IopDeleteDevice().
#define VPB_MOUNTED 0x00000001
Definition at line 1275 of file io.h.
Referenced by IoGetDiskDeviceObject(), IopCheckVpbMounted(), IopDeleteDevice(), IopGetMountFlag(), IopMountInitializeVpb(), IopMountVolume(), IopRaiseHardError(), IopReferenceVerifyVpb(), RawCheckForDismount(), and RawVerifyVolume().
#define VPB_PERSISTENT 0x00000004
Definition at line 1277 of file io.h.
Referenced by IopDereferenceVpbAndFree(), and RawCheckForDismount().
#define VPB_RAW_MOUNT 0x00000010
Definition at line 1279 of file io.h.
Referenced by IopMountInitializeVpb(), and IopMountVolume().
#define VPB_REMOVE_PENDING 0x00000008
Definition at line 1278 of file io.h.
Referenced by IopMountVolume(), and RawCheckForDismount().
#define WDM_MAJORVERSION 0x01
Definition at line 3350 of file io.h.
#define WDM_MINORVERSION 0x30
Definition at line 3351 of file io.h.
#define WMIREG_ACTION_BLOCK_IRPS 5
Definition at line 4962 of file io.h.
Referenced by IoWMIRegistrationControl().
#define WMIREG_ACTION_DEREGISTER 2
Definition at line 4959 of file io.h.
Referenced by IoWMIRegistrationControl().
#define WMIREG_ACTION_REGISTER 1
Definition at line 4958 of file io.h.
Referenced by IoWMIRegistrationControl(), and WmipDriverEntry().
#define WMIREG_ACTION_REREGISTER 3
Definition at line 4960 of file io.h.
Referenced by IoWMIRegistrationControl().
#define WMIREG_ACTION_UPDATE_GUIDS 4
Definition at line 4961 of file io.h.
Referenced by IoWMIRegistrationControl().
#define WMIREG_FLAG_CALLBACK 0x80000000
Definition at line 4892 of file io.h.
Referenced by IoWMIRegistrationControl(), WmipInitializeDataStructs(), WmipRegisterDevice(), and WmipRegisterUMGuids().
#define WMIREG_FLAG_TRACE_NOTIFY_MASK 0x00F00000
Definition at line 4903 of file io.h.
Referenced by IoWMIRegistrationControl(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipRegisterDevice().
#define WMIREG_FLAG_TRACE_PROVIDER 0x00010000
Definition at line 4898 of file io.h.
Referenced by IoWMIRegistrationControl(), and WmipRegisterDevice().
#define WMIREG_NOTIFY_DISK_IO 1 << 20
Definition at line 4908 of file io.h.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
#define WMIREG_NOTIFY_TDI_IO 2 << 20
Definition at line 4909 of file io.h.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
#define WMIREG_NOTIFY_VOLMGR_IO 3 << 20
Definition at line 4910 of file io.h.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
#define WMIREGISTER 0
Definition at line 4968 of file io.h.
Referenced by WmipRegisterOrUpdateDS().
#define WMIUPDATE 1
Definition at line 4969 of file io.h.
Referenced by WmipRegisterOrUpdateDS().
Typedef Documentation
typedef struct _BOOT_LOG_RECORD BOOT_LOG_RECORD
typedef struct _BOOTDISK_INFORMATION BOOTDISK_INFORMATION
typedef struct _BOOTDISK_INFORMATION_EX BOOTDISK_INFORMATION_EX
typedef struct _CONFIGURATION_INFORMATION CONFIGURATION_INFORMATION
typedef struct _CONTROLLER_OBJECT CONTROLLER_OBJECT
typedef enum _CRASHDUMP_CONFIGURATION CRASHDUMP_CONFIGURATION
typedef enum _CREATE_FILE_TYPE CREATE_FILE_TYPE
typedef struct _DEVICE_CAPABILITIES DEVICE_CAPABILITIES
typedef struct _DEVICE_HANDLER_OBJECT DEVICE_HANDLER_OBJECT
typedef enum _DEVICE_RELATION_TYPE DEVICE_RELATION_TYPE
typedef struct _DEVICE_RELATIONS DEVICE_RELATIONS
typedef enum _DEVICE_USAGE_NOTIFICATION_TYPE DEVICE_USAGE_NOTIFICATION_TYPE
typedef struct _DEVOBJ_EXTENSION DEVOBJ_EXTENSION
typedef struct _DISK_SIGNATURE DISK_SIGNATURE
typedef struct _DRIVER_EXTENSION DRIVER_EXTENSION
typedef struct _DRIVER_OBJECT DRIVER_OBJECT
typedef struct _DUMP_INITIALIZATION_CONTEXT DUMP_INITIALIZATION_CONTEXT
typedef struct _DUMP_STACK_CONTEXT DUMP_STACK_CONTEXT
typedef struct DUMP_STACK_IMAGE DUMP_STACK_IMAGE
typedef struct _FAST_IO_DISPATCH FAST_IO_DISPATCH
typedef struct _FILE_OBJECT FILE_OBJECT
typedef struct _FS_FILTER_CALLBACK_DATA FS_FILTER_CALLBACK_DATA
typedef struct _FS_FILTER_CALLBACKS FS_FILTER_CALLBACKS
typedef union _FS_FILTER_PARAMETERS FS_FILTER_PARAMETERS
typedef enum _FS_FILTER_SECTION_SYNC_TYPE FS_FILTER_SECTION_SYNC_TYPE
typedef struct _INTERFACE INTERFACE
typedef enum _IO_ALLOCATION_ACTION IO_ALLOCATION_ACTION
typedef struct _IO_CLIENT_EXTENSION IO_CLIENT_EXTENSION
typedef struct _IO_COMPLETION_CONTEXT IO_COMPLETION_CONTEXT
typedef enum _IO_COMPLETION_ROUTINE_RESULT IO_COMPLETION_ROUTINE_RESULT
typedef struct _IO_CSQ IO_CSQ
Definition at line 5527 of file io.h.
typedef struct _IO_CSQ_IRP_CONTEXT IO_CSQ_IRP_CONTEXT
typedef struct _IO_INTERRUPT_STRUCTURE IO_INTERRUPT_STRUCTURE
typedef enum _IO_PAGING_PRIORITY IO_PAGING_PRIORITY
typedef enum _IO_QUERY_DEVICE_DATA_FORMAT IO_QUERY_DEVICE_DATA_FORMAT
typedef struct _IO_REMOVE_LOCK IO_REMOVE_LOCK
typedef struct _IO_REMOVE_LOCK_COMMON_BLOCK IO_REMOVE_LOCK_COMMON_BLOCK
typedef struct _IO_REMOVE_LOCK_DBG_BLOCK IO_REMOVE_LOCK_DBG_BLOCK
typedef struct _IO_SECURITY_CONTEXT IO_SECURITY_CONTEXT
typedef struct _IO_STACK_LOCATION IO_STACK_LOCATION
typedef struct _IO_TIMER IO_TIMER
typedef struct _MAILSLOT_CREATE_PARAMETERS MAILSLOT_CREATE_PARAMETERS
typedef struct _NAMED_PIPE_CREATE_PARAMETERS NAMED_PIPE_CREATE_PARAMETERS
typedef struct _ADAPTER_OBJECT* PADAPTER_OBJECT
Definition at line 1336 of file io.h.
typedef struct _BOOT_LOG_RECORD * PBOOT_LOG_RECORD
typedef struct _BOOTDISK_INFORMATION * PBOOTDISK_INFORMATION
typedef struct _BOOTDISK_INFORMATION_EX * PBOOTDISK_INFORMATION_EX
typedef enum BUS_QUERY_ID_TYPE * PBUS_QUERY_ID_TYPE
typedef struct _CONFIGURATION_INFORMATION * PCONFIGURATION_INFORMATION
typedef struct _CONTROLLER_OBJECT * PCONTROLLER_OBJECT
typedef struct _DEVICE_CAPABILITIES * PDEVICE_CAPABILITIES
typedef struct _DEVICE_HANDLER_OBJECT * PDEVICE_HANDLER_OBJECT
typedef struct _DEVICE_OBJECT* PDEVICE_OBJECT
Definition at line 1436 of file io.h.
typedef enum _DEVICE_RELATION_TYPE * PDEVICE_RELATION_TYPE
typedef struct _DEVICE_RELATIONS * PDEVICE_RELATIONS
typedef enum DEVICE_TEXT_TYPE * PDEVICE_TEXT_TYPE
typedef struct _DEVOBJ_EXTENSION * PDEVOBJ_EXTENSION
typedef struct _DISK_SIGNATURE * PDISK_SIGNATURE
typedef NTSTATUS(* PDRIVER_ADD_DEVICE) (IN struct _DRIVER_OBJECT *DriverObject, IN struct _DEVICE_OBJECT *PhysicalDeviceObject)
Definition at line 666 of file io.h.
typedef VOID(* PDRIVER_CANCEL) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp)
Definition at line 625 of file io.h.
typedef IO_ALLOCATION_ACTION(* PDRIVER_CONTROL) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp, IN PVOID MapRegisterBase, IN PVOID Context)
Definition at line 1213 of file io.h.
typedef NTSTATUS(* PDRIVER_DISPATCH) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp)
Definition at line 636 of file io.h.
typedef struct _DRIVER_EXTENSION * PDRIVER_EXTENSION
typedef VOID(* PDRIVER_FS_NOTIFICATION) (IN struct _DEVICE_OBJECT *DeviceObject, IN BOOLEAN FsActive)
Definition at line 679 of file io.h.
typedef NTSTATUS(* PDRIVER_INITIALIZE) (IN struct _DRIVER_OBJECT *DriverObject, IN PUNICODE_STRING RegistryPath)
Definition at line 600 of file io.h.
typedef struct _DRIVER_OBJECT* PDRIVER_OBJECT
Definition at line 1664 of file io.h.
typedef VOID(* PDRIVER_REINITIALIZE) (IN struct _DRIVER_OBJECT *DriverObject, IN PVOID Context, IN ULONG Count)
Definition at line 612 of file io.h.
typedef VOID(* PDRIVER_STARTIO) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp)
Definition at line 647 of file io.h.
typedef VOID(* PDRIVER_UNLOAD) (IN struct _DRIVER_OBJECT *DriverObject)
Definition at line 657 of file io.h.
typedef VOID(* PDUMP_DRIVER_FINISH) (VOID)
Definition at line 336 of file io.h.
typedef BOOLEAN(* PDUMP_DRIVER_OPEN) (IN LARGE_INTEGER PartitionOffset)
Definition at line 299 of file io.h.
typedef NTSTATUS(* PDUMP_DRIVER_WRITE) (IN PLARGE_INTEGER DiskByteOffset, IN PMDL Mdl)
Definition at line 305 of file io.h.
typedef NTSTATUS(* PDUMP_DRIVER_WRITE_PENDING) (IN LONG Action, IN PLARGE_INTEGER DiskByteOffset, IN PMDL Mdl, IN PVOID LocalData)
Definition at line 326 of file io.h.
typedef struct _DUMP_INITIALIZATION_CONTEXT * PDUMP_INITIALIZATION_CONTEXT
typedef struct _DUMP_STACK_CONTEXT * PDUMP_STACK_CONTEXT
typedef struct DUMP_STACK_IMAGE * PDUMP_STACK_IMAGE
typedef VOID(* PFAST_IO_ACQUIRE_FILE) (IN struct _FILE_OBJECT *FileObject)
Definition at line 830 of file io.h.
typedef NTSTATUS(* PFAST_IO_ACQUIRE_FOR_CCFLUSH) (IN struct _FILE_OBJECT *FileObject, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 944 of file io.h.
typedef NTSTATUS(* PFAST_IO_ACQUIRE_FOR_MOD_WRITE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER EndingOffset, OUT struct _ERESOURCE **ResourceToRelease, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 922 of file io.h.
typedef BOOLEAN(* PFAST_IO_CHECK_IF_POSSIBLE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN Wait, IN ULONG LockKey, IN BOOLEAN CheckForReadOperation, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 694 of file io.h.
typedef VOID(* PFAST_IO_DETACH_DEVICE) (IN struct _DEVICE_OBJECT *SourceDevice, IN struct _DEVICE_OBJECT *TargetDevice)
Definition at line 848 of file io.h.
typedef BOOLEAN(* PFAST_IO_DEVICE_CONTROL) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN ULONG IoControlCode, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 810 of file io.h.
typedef struct _FAST_IO_DISPATCH * PFAST_IO_DISPATCH
typedef BOOLEAN(* PFAST_IO_LOCK) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length, PEPROCESS ProcessId, ULONG Key, BOOLEAN FailImmediately, BOOLEAN ExclusiveLock, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 761 of file io.h.
typedef BOOLEAN(* PFAST_IO_MDL_READ) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 876 of file io.h.
typedef BOOLEAN(* PFAST_IO_MDL_READ_COMPLETE) (IN struct _FILE_OBJECT *FileObject, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 888 of file io.h.
typedef BOOLEAN(* PFAST_IO_MDL_READ_COMPLETE_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 988 of file io.h.
typedef BOOLEAN(* PFAST_IO_MDL_WRITE_COMPLETE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 908 of file io.h.
typedef BOOLEAN(* PFAST_IO_MDL_WRITE_COMPLETE_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 996 of file io.h.
typedef BOOLEAN(* PFAST_IO_PREPARE_MDL_WRITE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 896 of file io.h.
typedef BOOLEAN(* PFAST_IO_QUERY_BASIC_INFO) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, OUT PFILE_BASIC_INFORMATION Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 737 of file io.h.
typedef BOOLEAN(* PFAST_IO_QUERY_NETWORK_OPEN_INFO) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, OUT struct _FILE_NETWORK_OPEN_INFORMATION *Buffer, OUT struct _IO_STATUS_BLOCK *IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 862 of file io.h.
typedef BOOLEAN(* PFAST_IO_QUERY_OPEN) (IN struct _IRP *Irp, OUT PFILE_NETWORK_OPEN_INFORMATION NetworkInformation, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 1005 of file io.h.
typedef BOOLEAN(* PFAST_IO_QUERY_STANDARD_INFO) (IN struct _FILE_OBJECT *FileObject, IN BOOLEAN Wait, OUT PFILE_STANDARD_INFORMATION Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 747 of file io.h.
typedef BOOLEAN(* PFAST_IO_READ) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN Wait, IN ULONG LockKey, OUT PVOID Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 707 of file io.h.
typedef BOOLEAN(* PFAST_IO_READ_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, OUT PVOID Buffer, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, OUT struct _COMPRESSED_DATA_INFO *CompressedDataInfo, IN ULONG CompressedDataInfoLength, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 958 of file io.h.
typedef VOID(* PFAST_IO_RELEASE_FILE) (IN struct _FILE_OBJECT *FileObject)
Definition at line 836 of file io.h.
typedef NTSTATUS(* PFAST_IO_RELEASE_FOR_CCFLUSH) (IN struct _FILE_OBJECT *FileObject, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 951 of file io.h.
typedef NTSTATUS(* PFAST_IO_RELEASE_FOR_MOD_WRITE) (IN struct _FILE_OBJECT *FileObject, IN struct _ERESOURCE *ResourceToRelease, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 931 of file io.h.
typedef BOOLEAN(* PFAST_IO_UNLOCK_ALL) (IN struct _FILE_OBJECT *FileObject, PEPROCESS ProcessId, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 787 of file io.h.
typedef BOOLEAN(* PFAST_IO_UNLOCK_ALL_BY_KEY) (IN struct _FILE_OBJECT *FileObject, PVOID ProcessId, ULONG Key, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 796 of file io.h.
typedef BOOLEAN(* PFAST_IO_UNLOCK_SINGLE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN PLARGE_INTEGER Length, PEPROCESS ProcessId, ULONG Key, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 775 of file io.h.
typedef BOOLEAN(* PFAST_IO_WRITE) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN BOOLEAN Wait, IN ULONG LockKey, IN PVOID Buffer, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 720 of file io.h.
typedef BOOLEAN(* PFAST_IO_WRITE_COMPRESSED) (IN struct _FILE_OBJECT *FileObject, IN PLARGE_INTEGER FileOffset, IN ULONG Length, IN ULONG LockKey, IN PVOID Buffer, OUT PMDL *MdlChain, OUT PIO_STATUS_BLOCK IoStatus, IN struct _COMPRESSED_DATA_INFO *CompressedDataInfo, IN ULONG CompressedDataInfoLength, IN struct _DEVICE_OBJECT *DeviceObject)
Definition at line 973 of file io.h.
typedef struct _FILE_OBJECT* PFILE_OBJECT
Definition at line 1792 of file io.h.
typedef NTSTATUS(* PFS_FILTER_CALLBACK) (IN PFS_FILTER_CALLBACK_DATA Data, OUT PVOID *CompletionContext)
Definition at line 1142 of file io.h.
typedef struct _FS_FILTER_CALLBACK_DATA * PFS_FILTER_CALLBACK_DATA
typedef struct _FS_FILTER_CALLBACKS * PFS_FILTER_CALLBACKS
typedef VOID(* PFS_FILTER_COMPLETION_CALLBACK) (IN PFS_FILTER_CALLBACK_DATA Data, IN NTSTATUS OperationStatus, IN PVOID CompletionContext)
Definition at line 1154 of file io.h.
typedef union _FS_FILTER_PARAMETERS * PFS_FILTER_PARAMETERS
typedef enum _FS_FILTER_SECTION_SYNC_TYPE * PFS_FILTER_SECTION_SYNC_TYPE
typedef struct _INTERFACE * PINTERFACE
typedef enum _IO_ALLOCATION_ACTION * PIO_ALLOCATION_ACTION
typedef struct _IO_CLIENT_EXTENSION * PIO_CLIENT_EXTENSION
typedef struct _IO_COMPLETION_CONTEXT * PIO_COMPLETION_CONTEXT
typedef NTSTATUS(* PIO_COMPLETION_ROUTINE) (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
Definition at line 2098 of file io.h.
typedef enum _IO_COMPLETION_ROUTINE_RESULT * PIO_COMPLETION_ROUTINE_RESULT
typedef struct _IO_CSQ * PIO_CSQ
Definition at line 5527 of file io.h.
typedef VOID(* PIO_CSQ_ACQUIRE_LOCK) (IN PIO_CSQ Csq, OUT PKIRQL Irql)
Definition at line 5588 of file io.h.
typedef VOID(* PIO_CSQ_COMPLETE_CANCELED_IRP) (IN PIO_CSQ Csq, IN PIRP Irp)
Definition at line 5606 of file io.h.
typedef VOID(* PIO_CSQ_INSERT_IRP) (IN struct _IO_CSQ *Csq, IN PIRP Irp)
Definition at line 5550 of file io.h.
typedef NTSTATUS(* PIO_CSQ_INSERT_IRP_EX) (IN struct _IO_CSQ *Csq, IN PIRP Irp, IN OUT PVOID InsertContext)
Definition at line 5556 of file io.h.
typedef struct _IO_CSQ_IRP_CONTEXT * PIO_CSQ_IRP_CONTEXT
typedef PIRP(* PIO_CSQ_PEEK_NEXT_IRP) (IN PIO_CSQ Csq, IN PIRP Irp, IN PVOID PeekContext)
Definition at line 5577 of file io.h.
typedef VOID(* PIO_CSQ_RELEASE_LOCK) (IN PIO_CSQ Csq, IN KIRQL Irql)
Definition at line 5594 of file io.h.
typedef VOID(* PIO_CSQ_REMOVE_IRP) (IN PIO_CSQ Csq, IN PIRP Irp)
Definition at line 5563 of file io.h.
typedef VOID(* PIO_DPC_ROUTINE) (IN PKDPC Dpc, IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp, IN PVOID Context)
Definition at line 577 of file io.h.
typedef struct _IO_INTERRUPT_STRUCTURE * PIO_INTERRUPT_STRUCTURE
typedef BOOLEAN(* PIO_LEVEL_END_WORKER) (IN ULONG Level, IN PVOID Context)
Definition at line 4823 of file io.h.
typedef enum _IO_QUERY_DEVICE_DATA_FORMAT * PIO_QUERY_DEVICE_DATA_FORMAT
typedef NTSTATUS(* PIO_QUERY_DEVICE_ROUTINE) (IN PVOID Context, IN PUNICODE_STRING PathName, IN INTERFACE_TYPE BusType, IN ULONG BusNumber, IN PKEY_VALUE_FULL_INFORMATION *BusInformation, IN CONFIGURATION_TYPE ControllerType, IN ULONG ControllerNumber, IN PKEY_VALUE_FULL_INFORMATION *ControllerInformation, IN CONFIGURATION_TYPE PeripheralType, IN ULONG PeripheralNumber, IN PKEY_VALUE_FULL_INFORMATION *PeripheralInformation)
Definition at line 383 of file io.h.
typedef struct _IO_REMOVE_LOCK * PIO_REMOVE_LOCK
typedef struct _IO_REMOVE_LOCK_TRACKING_BLOCK* PIO_REMOVE_LOCK_TRACKING_BLOCK
Definition at line 4496 of file io.h.
typedef struct _IO_SECURITY_CONTEXT * PIO_SECURITY_CONTEXT
typedef struct _IO_STACK_LOCATION * PIO_STACK_LOCATION
typedef struct _IO_TIMER * PIO_TIMER
typedef VOID(* PIO_TIMER_ROUTINE) (IN struct _DEVICE_OBJECT *DeviceObject, IN PVOID Context)
Definition at line 590 of file io.h.
typedef BOOLEAN(* PIO_TRAVERSE_WORKER) (IN ULONG Level, IN PVOID DeviceNode, IN PDEVICE_OBJECT DeviceObject, IN PVOID Context)
Definition at line 4816 of file io.h.
typedef struct _IO_WORKITEM* PIO_WORKITEM
Definition at line 4916 of file io.h.
typedef VOID(* PIO_WORKITEM_ROUTINE) (IN PDEVICE_OBJECT DeviceObject, IN PVOID Context)
Definition at line 4920 of file io.h.
typedef struct _MAILSLOT_CREATE_PARAMETERS * PMAILSLOT_CREATE_PARAMETERS
typedef struct _NAMED_PIPE_CREATE_PARAMETERS * PNAMED_PIPE_CREATE_PARAMETERS
typedef ULONG PNP_DEVICE_STATE
Definition at line 2271 of file io.h.
typedef struct _POWER_SEQUENCE POWER_SEQUENCE
typedef ULONG * PPNP_DEVICE_STATE
Definition at line 2271 of file io.h.
typedef struct _POWER_SEQUENCE * PPOWER_SEQUENCE
typedef SECTION_OBJECT_POINTERS* PSECTION_OBJECT_POINTERS
Definition at line 1722 of file io.h.
typedef struct _SHARE_ACCESS * PSHARE_ACCESS
typedef VOID(* PSTALL_ROUTINE) (IN ULONG Delay)
Definition at line 289 of file io.h.
typedef struct _VPB * PVPB
typedef struct _WAIT_CONTEXT_BLOCK * PWAIT_CONTEXT_BLOCK
typedef struct _SECTION_OBJECT_POINTERS SECTION_OBJECT_POINTERS
typedef struct _SHARE_ACCESS SHARE_ACCESS
typedef struct _VPB VPB
typedef struct _WAIT_CONTEXT_BLOCK WAIT_CONTEXT_BLOCK
typedef VOID(* WMI_NOTIFICATION_CALLBACK) (PVOID Wnode, PVOID Context)
Definition at line 5083 of file io.h.
typedef enum tagWMIACTIONCODE WMIACTIONCODE
typedef NTSTATUS(* WMIENTRY) (IN WMIACTIONCODE ActionCode, IN PVOID DataPath, IN ULONG BufferSize, IN OUT PVOID Buffer, IN PVOID Context, OUT PULONG Size)
Definition at line 4883 of file io.h.
Enumeration Type Documentation
enum _CRASHDUMP_CONFIGURATION
Enumerator
CrashDumpDisable
CrashDumpReconfigure
Definition at line 499 of file io.h.
enum _CREATE_FILE_TYPE
Enumerator
CreateFileTypeNone
CreateFileTypeNamedPipe
CreateFileTypeMailslot
Definition at line 414 of file io.h.
enum _DEVICE_RELATION_TYPE
Enumerator
BusRelations
EjectionRelations
PowerRelations
RemovalRelations
TargetDeviceRelation
SingleBusRelations
Definition at line 2185 of file io.h.
enum _DEVICE_USAGE_NOTIFICATION_TYPE
Enumerator
DeviceUsageTypeUndefined
DeviceUsageTypePaging
DeviceUsageTypeHibernation
DeviceUsageTypeDumpFile
Definition at line 2199 of file io.h.
enum _FS_FILTER_SECTION_SYNC_TYPE
Enumerator
SyncTypeOther
SyncTypeCreateSection
Definition at line 1054 of file io.h.
enum _IO_ALLOCATION_ACTION
Enumerator
KeepObject
DeallocateObject
DeallocateObjectKeepRegisters
Definition at line 1201 of file io.h.
enum _IO_COMPLETION_ROUTINE_RESULT
Enumerator
ContinueCompletion
StopCompletion
Definition at line 3291 of file io.h.
enum _IO_PAGING_PRIORITY
Enumerator
IoPagingPriorityInvalid
IoPagingPriorityNormal
IoPagingPriorityHigh
IoPagingPriorityReserved1
IoPagingPriorityReserved2
Definition at line 3020 of file io.h.
enum _IO_QUERY_DEVICE_DATA_FORMAT
Enumerator
IoQueryDeviceIdentifier
IoQueryDeviceConfigurationData
IoQueryDeviceComponentInformation
IoQueryDeviceMaxData
Definition at line 402 of file io.h.
enum BUS_QUERY_ID_TYPE
Enumerator
BusQueryDeviceID
BusQueryHardwareIDs
BusQueryCompatibleIDs
BusQueryInstanceID
BusQueryDeviceSerialNumber
Definition at line 2263 of file io.h.
enum DEVICE_TEXT_TYPE
Enumerator
DeviceTextDescription
DeviceTextLocationInformation
Definition at line 2280 of file io.h.
enum tagWMIACTIONCODE
Enumerator
WmiGetAllData
WmiGetSingleInstance
WmiChangeSingleInstance
WmiChangeSingleItem
WmiEnableEvents
WmiDisableEvents
WmiEnableCollection
WmiDisableCollection
WmiRegisterInfo
WmiExecuteMethodCall
WmiGetAllData
WmiGetSingleInstance
WmiChangeSingleInstance
WmiChangeSingleItem
WmiEnableEvents
WmiDisableEvents
WmiEnableCollection
WmiDisableCollection
WmiRegisterInfo
WmiExecuteMethodCall
WmiSetTraceNotify
Definition at line 4864 of file io.h.
Function Documentation
struct DECLSPEC_ALIGN (MEMORY_ALLOCATION_ALIGNMENT)
Definition at line 1397 of file io.h.
References DEVICE_TYPE.
NTKERNELAPI NTSTATUS FsRtlRegisterFileSystemFilterCallbacks (__in struct _DRIVER_OBJECT * FilterDriverObject, __in PFS_FILTER_CALLBACKS Callbacks)
NTKERNELAPI VOID FASTCALL HalExamineMBR (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG MBRTypeIdentifier, OUT PVOID * Buffer)
Definition at line 212 of file drivesup.c.
References ASSERT, BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, PAGE_SIZE, PARTITION_TABLE_OFFSET, _PARTITION_DESCRIPTOR::PartitionType, PIRP, RtlConvertUlongToLargeInteger(), SL_OVERRIDE_VERIFY_VOLUME, _IO_STATUS_BLOCK::Status, STATUS_PENDING, STATUS_SUCCESS, and VOID.
Referenced by IopCreateArcNamesDisk(), IoReadPartitionTable(), IoSetPartitionInformation(), and IoWritePartitionTable().
NTKERNELAPI VOID IoAcquireCancelSpinLock (OUT PKIRQL Irql)
Definition at line 148 of file iosubs.c.
References KeAcquireQueuedSpinLock(), and LockQueueIoCancelLock.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlNotifySetCancelRoutine(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeFileLock(), FsRtlUninitializeOplock(), FsRtlWaitOnIrp(), IoCancelIrp(), IopStartNextPacket(), IopStartNextPacketByKey(), and IoStartPacket().
NTKERNELAPI NTSTATUS NTAPI IoAcquireRemoveLockEx (IN PIO_REMOVE_LOCK RemoveLock, IN OPTIONAL PVOID Tag, IN PCSTR File, IN ULONG Line, IN ULONG RemlockSize)
NTKERNELAPI VOID IoAcquireVpbSpinLock (OUT PKIRQL Irql)
Definition at line 180 of file iosubs.c.
References KeAcquireQueuedSpinLock(), and LockQueueIoVpbLock.
Referenced by IoGetDiskDeviceObject(), IopMountInitializeVpb(), IopReferenceVerifyVpb(), RawCheckForDismount(), and RawVerifyVolume().
BOOLEAN IoAddTriageDumpDataBlock (IN PVOID Address, IN ULONG Length)
Referenced by KeBugCheck2().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoAllocateAdapterChannel (IN PADAPTER_OBJECT AdapterObject, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
Definition at line 214 of file iosubs.c.
References _WAIT_CONTEXT_BLOCK::CurrentIrp, _WAIT_CONTEXT_BLOCK::DeviceContext, _WAIT_CONTEXT_BLOCK::DeviceObject, and HalAllocateAdapterChannel().
NTKERNELAPI VOID IoAllocateController (IN PCONTROLLER_OBJECT ControllerObject, IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
Definition at line 285 of file iosubs.c.
References DeallocateObject, IoFreeController(), and KeInsertDeviceQueue().
NTKERNELAPI NTSTATUS IoAllocateDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress, IN ULONG DriverObjectExtensionSize, OUT PVOID * DriverObjectExtension)
Definition at line 373 of file iosubs.c.
References _IO_CLIENT_EXTENSION::ClientIdentificationAddress, ExAllocatePoolWithTag, ExFreePool(), FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, _IO_CLIENT_EXTENSION::NextExtension, NonPagedPool, NULL, RtlZeroMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_COLLISION, STATUS_SUCCESS, and TRUE.
NTKERNELAPI PVOID IoAllocateErrorLogEntry (IN PVOID IoObject, IN UCHAR EntrySize)
Definition at line 473 of file iosubs.c.
References IO_TYPE_DEVICE, IO_TYPE_DRIVER, IopAllocateErrorLogEntry(), and NULL.
Referenced by CcLogError(), IopDisassociateThreadIrp(), IopLogErrorEvent(), and WmipWriteToEventlog().
NTKERNELAPI PVOID IoAllocateGenericErrorLogEntry (IN UCHAR EntrySize)
Definition at line 551 of file iosubs.c.
References IopAllocateErrorLogEntry(), and NULL.
Referenced by CmpLogError(), MmCleanProcessAddressSpace(), MmLoadSystemImage(), and Phase1InitializationDiscard().
NTKERNELAPI PIRP IoAllocateIrp (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
Definition at line 735 of file iosubs.c.
References pIoAllocateIrp.
Referenced by BuildQueryDirectoryIrp(), CcSetValidData(), FsRtlGetFileSize(), FsRtlSetFileSize(), IoAsynchronousPageWrite(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoPageRead(), IopAllocateIrpMustSucceed(), IopDeleteFile(), IopGetFileInformation(), IopGetSetSecurityObject(), IopInitializeReserveIrp(), IopMountVolume(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IoSetInformation(), IoSynchronousPageWrite(), IoVerifyVolume(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipSendWmiIrp(), and WmipSetTraceNotify().
NTKERNELAPI PMDL IoAllocateMdl (IN PVOID VirtualAddress, IN ULONG Length, IN BOOLEAN SecondaryBuffer, IN BOOLEAN ChargeQuota, IN OUT PIRP Irp OPTIONAL)
Definition at line 912 of file iosubs.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, ExAllocateFromPPLookasideList(), ExAllocatePoolWithTag, IOP_FIXED_SIZE_MDL_PFNS, LookasideMdlList, MAXUSHORT, MDL_ALLOCATED_FIXED_SIZE, _MDL::MdlFlags, MmInitializeMdl, _MDL::Next, NonPagedPool, NULL, and UNREFERENCED_PARAMETER.
Referenced by BuildQueryDirectoryIrp(), CcMdlRead(), CcPrepareMdlWrite(), CcZeroData(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtWriteFile(), and NtWriteFileGather().
NTKERNELAPI PIO_WORKITEM IoAllocateWorkItem (PDEVICE_OBJECT DeviceObject)
Definition at line 902 of file misc.c.
References _IO_WORKITEM::DeviceObject, ExAllocatePool, ExInitializeWorkItem, IopProcessWorkItem(), NonPagedPool, NULL, and _IO_WORKITEM::WorkItem.
NTKERNELAPI VOID FASTCALL IoAssignDriveLetters (PLOADER_PARAMETER_BLOCK LoaderBlock, PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, OUT PSTRING NtSystemPathString)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoAssignResources (IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN PIO_RESOURCE_REQUIREMENTS_LIST RequestedResources, IN OUT PCM_RESOURCE_LIST * AllocatedResources)
NTKERNELAPI NTSTATUS IoAsynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PIO_APC_ROUTINE ApcRoutine, IN PVOID ApcContext, IN IO_PAGING_PRIORITY Priority, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PIRP *Irp OPTIONAL)
Definition at line 1033 of file iosubs.c.
References APC_LEVEL, ARGUMENT_PRESENT, CcDataFlushes, CcDataPages, CcIsFileCached, _IO_STACK_LOCATION::FileObject, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoPagingPriorityHigh, IRP_HIGH_PRIORITY_PAGING_IO, IRP_MJ_WRITE, IRP_NOCACHE, IRP_PAGING_IO, KeLowerIrql, KeRaiseIrql, KernelMode, _IO_STACK_LOCATION::MajorFunction, NT_ERROR, PAGE_SHIFT, PAGE_SIZE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by MiFlushSectionInternal(), MiGatherPagefilePages(), and MiMappedPageWriter().
NTKERNELAPI NTSTATUS IoAttachDevice (IN PDEVICE_OBJECT SourceDevice, IN PUNICODE_STRING TargetDevice, OUT PDEVICE_OBJECT * AttachedDevice)
Definition at line 1187 of file iosubs.c.
References FILE_NON_DIRECTORY_FILE, FILE_READ_ATTRIBUTES, InitializeObjectAttributes, IO_ATTACH_DEVICE_API, IoAttachDeviceToDeviceStackSafe(), IoFileObjectType, IoGetRelatedDeviceObject(), KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGED_CODE, VOID, ZwClose(), and ZwOpenFile().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoAttachDeviceByPointer (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
Definition at line 1310 of file iosubs.c.
References IoAttachDeviceToDeviceStack(), NULL, STATUS_NO_SUCH_DEVICE, and STATUS_SUCCESS.
NTKERNELAPI PDEVICE_OBJECT IoAttachDeviceToDeviceStack (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
Definition at line 1360 of file iosubs.c.
References IopAttachDeviceToDeviceStackSafe(), and NULL.
Referenced by IoAttachDeviceByPointer().
NTKERNELAPI NTSTATUS IoAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, OUT PDEVICE_OBJECT * AttachedToDeviceObject)
NTKERNELAPI PIRP IoBuildAsynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PIO_STATUS_BLOCK IoStatusBlock OPTIONAL)
Definition at line 1569 of file iosubs.c.
References DO_BUFFERED_IO, DO_DIRECT_IO, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, IoAllocateIrp(), IoAllocateMdl(), IoFreeIrp(), IoFreeMdl(), IoGetNextIrpStackLocation, IoReadAccess, IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_FLUSH_BUFFERS, IRP_MJ_PNP, IRP_MJ_POWER, IRP_MJ_READ, IRP_MJ_SHUTDOWN, IRP_MJ_WRITE, KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NULL, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and RtlCopyMemory.
Referenced by IoBuildSynchronousFsdRequest().
NTKERNELAPI PIRP IoBuildDeviceIoControlRequest (IN ULONG IoControlCode, IN PDEVICE_OBJECT DeviceObject, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN InternalDeviceIoControl, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 1762 of file iosubs.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), IoAllocateIrp(), IoAllocateMdl(), IoFreeIrp(), IoFreeMdl(), IoGetNextIrpStackLocation, IopQueueThreadIrp(), IoReadAccess, IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_DEVICE_CONTROL, IRP_MJ_INTERNAL_DEVICE_CONTROL, KernelMode, _IO_STACK_LOCATION::MajorFunction, METHOD_BUFFERED, METHOD_IN_DIRECT, METHOD_NEITHER, METHOD_OUT_DIRECT, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NULL, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and RtlCopyMemory.
Referenced by FsRtlBalanceReads(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoGetBootDiskInformation(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopGetSetObjectId(), IopGetVolumeId(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopSetRemoteLink(), IoVolumeDeviceToDosName(), RawQueryFsSizeInfo(), and xHalGetPartialGeometry().
NTKERNELAPI VOID IoBuildPartialMdl (IN PMDL SourceMdl, IN OUT PMDL TargetMdl, IN PVOID VirtualAddress, IN ULONG Length)
Definition at line 2014 of file iosubs.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, BYTE_OFFSET, KeBugCheck(), MDL_ALLOCATED_FIXED_SIZE, MDL_ALLOCATED_MUST_SUCCEED, MDL_IO_PAGE_READ, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PARENT_MAPPED_SYSTEM_VA, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MmGetMdlBaseVa, MmGetMdlByteCount, MmGetMdlByteOffset, MmGetMdlPfnArray, PAGE_ALIGN, PAGE_SHIFT, and TARGET_MDL_TOO_SMALL.
NTSTATUS IoBuildPoDeviceNotifyList (IN OUT PVOID Order)
NTKERNELAPI PIRP IoBuildSynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 2143 of file iosubs.c.
References IoBuildAsynchronousFsdRequest(), IopQueueThreadIrp(), NULL, and PIRP.
Referenced by HalExamineMBR(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopShutdownBaseFileSystems(), IoReadPartitionTable(), IoSetPartitionInformation(), IoShutdownSystem(), IoWritePartitionTable(), and WmipGetDevicePDO().
NTKERNELAPI VOID IoCancelFileOpen (IN PDEVICE_OBJECT DeviceObject, IN PFILE_OBJECT FileObject)
Definition at line 13582 of file iosubs.c.
References APC_LEVEL, ASSERT, _IO_STACK_LOCATION::FileObject, FO_FILE_OPEN_CANCELLED, FO_HANDLE_CREATED, INVALID_CANCEL_OF_FILE_OPEN, IoCallDriver(), IoFreeIrp(), IoGetNextIrpStackLocation, IopAllocateIrpMustSucceed(), IopDequeueThreadIrp, IopQueueThreadIrp(), IRP_CLOSE_OPERATION, IRP_MJ_CLEANUP, IRP_SYNCHRONOUS_API, KeBugCheckEx(), KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NULL, PIRP, PsGetCurrentThread(), STATUS_PENDING, SynchronizationEvent, UserRequest, and VOID.
NTKERNELAPI BOOLEAN IoCancelIrp (IN PIRP Irp)
Definition at line 2278 of file iosubs.c.
References ASSERT, CANCEL_STATE_IN_COMPLETED_IRP, InterlockedExchangePointer, IO_TYPE_IRP, IoAcquireCancelSpinLock(), IopVerifierOn, IoReleaseCancelSpinLock(), IOV_CANCEL_IRP, KeBugCheckEx(), NULL, and TRUE.
Referenced by IoCancelThreadIo(), IopCancelAlertedRequest(), and NtCancelIoFile().
NTKERNELAPI VOID IoCancelThreadIo (IN PETHREAD Thread)
Definition at line 2373 of file iosubs.c.
References APC_LEVEL, CONTAINING_RECORD, DBG_UNREFERENCED_PARAMETER, _LIST_ENTRY::Flink, IoCancelIrp(), IopDisassociateThreadIrp(), IRP, _ETHREAD::IrpList, IsListEmpty, KeDelayExecutionThread(), KeLowerIrql, KeRaiseIrql, KernelMode, PAGED_CODE, PIRP, PsGetCurrentThread(), and _LARGE_INTEGER::QuadPart.
Referenced by PspExitThread().
NTSTATUS IoChangeFileObjectFilterContext (IN PFILE_OBJECT FileObject, IN PVOID FilterContext, IN BOOLEAN Set)
Definition at line 14714 of file iosubs.c.
References _IOP_FILE_OBJECT_EXTENSION::FilterContext, FO_FILE_OBJECT_HAS_EXTENSION, InterlockedCompareExchangePointer, NULL, STATUS_ALREADY_COMMITTED, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by FsRtlInsertPerFileObjectContext(), and FsRtlPTeardownPerFileObjectContexts().
NTKERNELAPI NTSTATUS IoCheckDesiredAccess (IN OUT PACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess)
Definition at line 2476 of file iosubs.c.
References _OBJECT_TYPE_INITIALIZER::GenericMapping, IoFileObjectType, PAGED_CODE, RtlMapGenericMask(), SeComputeDeniedAccesses, STATUS_ACCESS_DENIED, STATUS_SUCCESS, and _OBJECT_TYPE::TypeInfo.
NTKERNELAPI NTSTATUS IoCheckEaBufferValidity (IN PFILE_FULL_EA_INFORMATION EaBuffer, IN ULONG EaLength, OUT PULONG ErrorOffset)
Definition at line 2528 of file iosubs.c.
References ALIGN_LONG, _FILE_FULL_EA_INFORMATION::EaName, _FILE_FULL_EA_INFORMATION::EaNameLength, _FILE_FULL_EA_INFORMATION::EaValueLength, FIELD_OFFSET, GET_OFFSET_LENGTH, _FILE_FULL_EA_INFORMATION::NextEntryOffset, PAGED_CODE, STATUS_EA_LIST_INCONSISTENT, and STATUS_SUCCESS.
Referenced by IopCreateFile(), IopSetEaOrQuotaInformationFile(), and NtSetEaFile().
NTKERNELAPI NTSTATUS IoCheckFunctionAccess (IN ACCESS_MASK GrantedAccess, IN UCHAR MajorFunction, IN UCHAR MinorFunction, IN ULONG IoControlCode, IN PVOID Arg1 OPTIONAL, IN PVOID Arg2 OPTIONAL)
Definition at line 2683 of file iosubs.c.
References FILE_ANY_ACCESS, FILE_APPEND_DATA, FILE_LIST_DIRECTORY, FILE_READ_DATA, FILE_READ_EA, FILE_WRITE_DATA, FILE_WRITE_EA, IopQueryFsOperationAccess, IopQueryOperationAccess, IopSetFsOperationAccess, IopSetOperationAccess, IRP_MJ_CLOSE, IRP_MJ_CREATE, IRP_MJ_DEVICE_CONTROL, IRP_MJ_DIRECTORY_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MJ_FLUSH_BUFFERS, IRP_MJ_INTERNAL_DEVICE_CONTROL, IRP_MJ_LOCK_CONTROL, IRP_MJ_QUERY_EA, IRP_MJ_QUERY_INFORMATION, IRP_MJ_QUERY_SECURITY, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_MJ_READ, IRP_MJ_SET_EA, IRP_MJ_SET_INFORMATION, IRP_MJ_SET_SECURITY, IRP_MJ_SET_VOLUME_INFORMATION, IRP_MJ_WRITE, PAGED_CODE, SeComputeDeniedAccesses, SeComputeGrantedAccesses, SeQuerySecurityAccessMask(), SeSetSecurityAccessMask(), STATUS_ACCESS_DENIED, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
NTKERNELAPI NTSTATUS IoCheckQuerySetFileInformation (IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
Definition at line 2896 of file iosubs.c.
References FileMaximumInformation, IopQueryOperationLength, IopSetOperationLength, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS IoCheckQuerySetVolumeInformation (IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
Definition at line 2961 of file iosubs.c.
References FileFsMaximumInformation, IopQueryFsOperationLength, IopSetFsOperationLength, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS IoCheckQuotaBufferValidity (IN PFILE_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG ErrorOffset)
Definition at line 3020 of file iosubs.c.
References FIELD_OFFSET, GET_OFFSET_LENGTH, _FILE_QUOTA_INFORMATION::NextEntryOffset, PAGED_CODE, REQUIRED_QUOTA_ALIGNMENT, RtlLengthSid(), RtlValidSid(), _FILE_QUOTA_INFORMATION::Sid, _FILE_QUOTA_INFORMATION::SidLength, STATUS_DATATYPE_MISALIGNMENT, STATUS_QUOTA_LIST_INCONSISTENT, and STATUS_SUCCESS.
Referenced by IopSetEaOrQuotaInformationFile().
NTKERNELAPI NTSTATUS IoCheckShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess, IN BOOLEAN Update)
Definition at line 3178 of file iosubs.c.
References DELETE, FILE_APPEND_DATA, FILE_EXECUTE, FILE_READ_DATA, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_DATA, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, PAGED_CODE, STATUS_SHARING_VIOLATION, and STATUS_SUCCESS.
Referenced by RawCreate().
NTSTATUS IoComputeDesiredAccessFileObject (IN PFILE_OBJECT FileObject, OUT PNTSTATUS DesiredAccess)
Definition at line 7847 of file iosubs.c.
References FILE_APPEND_DATA, FILE_WRITE_DATA, FO_NAMED_PIPE, IoFileObjectType, NULL, OBJECT_TO_OBJECT_HEADER, Status, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, and _OBJECT_HEADER::Type.
Referenced by ObReferenceFileObjectForWrite().
NTSTATUS IoConfigureCrashDump (CRASHDUMP_CONFIGURATION Config)
Referenced by NtSetSystemInformation().
NTKERNELAPI NTSTATUS IoConnectInterrupt (OUT PKINTERRUPT * InterruptObject, IN PKSERVICE_ROUTINE ServiceRoutine, IN PVOID ServiceContext, IN PKSPIN_LOCK SpinLock OPTIONAL, IN ULONG Vector, IN KIRQL Irql, IN KIRQL SynchronizeIrql, IN KINTERRUPT_MODE InterruptMode, IN BOOLEAN ShareVector, IN KAFFINITY ProcessorEnableMask, IN BOOLEAN FloatingSave)
Definition at line 3862 of file iosubs.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, ExFreePool(), FALSE, _IO_INTERRUPT_STRUCTURE::InterruptArray, _IO_INTERRUPT_STRUCTURE::InterruptObject, IoDisconnectInterrupt(), KeActiveProcessors, KeConnectInterrupt(), KeInitializeInterrupt(), NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, RtlZeroMemory, _IO_INTERRUPT_STRUCTURE::SpinLock, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
VOID IoControlPnpDeviceActionQueue (BOOLEAN Lock)
Referenced by WmipRegistrationWorker().
NTKERNELAPI PCONTROLLER_OBJECT IoCreateController (IN ULONG Size)
Definition at line 4115 of file iosubs.c.
References _CONTROLLER_OBJECT::ControllerExtension, _CONTROLLER_OBJECT::DeviceWaitQueue, FILE_READ_DATA, FILE_WRITE_DATA, InitializeObjectAttributes, IO_TYPE_CONTROLLER, IoControllerObjectType, KeInitializeDeviceQueue(), KernelMode, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObInsertObject(), OBJ_KERNEL_HANDLE, PAGED_CODE, RtlZeroMemory, _CONTROLLER_OBJECT::Size, _CONTROLLER_OBJECT::Type, and VOID.
NTKERNELAPI NTSTATUS IoCreateDevice (IN PDRIVER_OBJECT DriverObject, IN ULONG DeviceExtensionSize, IN PUNICODE_STRING DeviceName OPTIONAL, IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN Exclusive, OUT PDEVICE_OBJECT * DeviceObject)
Definition at line 4276 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, _OBJECT_ATTRIBUTES::Attributes, DEVICE_OBJECT, _DEVOBJ_EXTENSION::DeviceObject, DO_DEVICE_HAS_NAME, DO_DEVICE_INITIALIZING, DO_EXCLUSIVE, DRVO_UNLOAD_INVOKED, ExFreePool(), FALSE, FILE_AUTOGENERATED_DEVICE_NAME, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_DEVICE_VIRTUAL_DISK, FILE_READ_DATA, FILE_WRITE_DATA, HalGetDmaAlignmentRequirement, InitializeListHead(), InitializeObjectAttributes, InterlockedIncrement, IO_TYPE_DEVICE, IO_TYPE_DEVICE_OBJECT_EXTENSION, IoDeviceObjectType, IopCreateDefaultDeviceSecurityDescriptor(), IopCreateVpb(), IopInsertRemoveDevice(), IopUniqueDeviceObjectNumber, KeInitializeDeviceQueue(), KeInitializeEvent(), KernelMode, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_EXCLUSIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, ObReferenceObject, PAGED_CODE, PoInitializeDeviceObject(), PoVolumeDevice(), RtlInitUnicodeString(), RtlZeroMemory, SECURITY_DESCRIPTOR_MIN_LENGTH, _DEVOBJ_EXTENSION::Size, STATUS_OBJECT_NAME_COLLISION, swprintf, SynchronizationEvent, TRUE, _DEVOBJ_EXTENSION::Type, and VOID.
Referenced by RawInitialize(), RawMountVolume(), and WmipDriverEntry().
NTKERNELAPI NTSTATUS IoCreateDisk (IN PDEVICE_OBJECT DeviceObject, IN struct _CREATE_DISK * Disk)
NTKERNELAPI NTSTATUS IoCreateDriver (IN PUNICODE_STRING DriverName, OPTIONAL IN PDRIVER_INITIALIZE InitializationFunction)
Referenced by WMIInitialize().
NTKERNELAPI NTSTATUS IoCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options)
Definition at line 4716 of file iosubs.c.
References ASSERT, ExHotpSyncRenameSequence, ExSyncRenameOwner, IOP_CREATE_FILE_TIMEOUT, IopCreateFile(), KeDelayExecutionThread(), KeGetCurrentThread(), KernelMode, NT_SUCCESS, NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, and STATUS_SUCCESS.
Referenced by IopOpenLinkOrRenameTarget(), NtCreateFile(), NtCreateMailslotFile(), NtCreateNamedPipeFile(), NtCreatePagingFile(), and NtOpenFile().
NTKERNELAPI NTSTATUS IoCreateFileSpecifyDeviceObjectHint (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN PVOID DeviceObject)
Definition at line 4898 of file iosubs.c.
References IO_IGNORE_SHARE_ACCESS_CHECK, IO_NO_PARAMETER_CHECKING, IOP_CREATE_DEVICE_OBJECT_EXTENSION, IOP_CREATE_IGNORE_SHARE_ACCESS_CHECK, IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT, IopCreateFile(), and NULL.
Referenced by IopOpenLinkOrRenameTarget().
NTKERNELAPI PKEVENT IoCreateNotificationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
Definition at line 5779 of file iosubs.c.
References EVENT_ALL_ACCESS, ExEventObjectType, InitializeObjectAttributes, KernelMode, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, OBJ_OPENIF, ObReferenceObjectByHandle, PAGED_CODE, TRUE, VOID, and ZwCreateEvent().
NTKERNELAPI PFILE_OBJECT IoCreateStreamFileObject (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
Definition at line 5858 of file iosubs.c.
References IoCreateStreamFileObjectEx(), and NULL.
NTKERNELAPI PFILE_OBJECT IoCreateStreamFileObjectEx (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, OUT PHANDLE FileObjectHandle OPTIONAL)
NTKERNELAPI PFILE_OBJECT IoCreateStreamFileObjectLite (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
Definition at line 6038 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExRaiseStatus(), _FILE_OBJECT::Flags, FO_HANDLE_CREATED, FO_STREAM_FILE, InitializeObjectAttributes, IO_TYPE_FILE, IoFileObjectType, IopDecrementDeviceObjectRef(), IopInterlockedIncrementUlong(), KeInitializeEvent(), KernelMode, LockQueueIoDatabaseLock, LockQueueIoVpbLock, NT_SUCCESS, NULL, ObCreateObject, ObFreeObjectCreateInfoBuffer(), OBJECT_TO_OBJECT_HEADER, PAGED_CODE, RtlZeroMemory, _FILE_OBJECT::Size, SynchronizationEvent, and _FILE_OBJECT::Type.
Referenced by IopInvalidateVolumesForDevice(), and RawMountVolume().
NTKERNELAPI NTSTATUS IoCreateSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
Definition at line 6174 of file iosubs.c.
References InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, PAGED_CODE, SePublicDefaultUnrestrictedSd, SYMBOLIC_LINK_ALL_ACCESS, ZwClose(), and ZwCreateSymbolicLinkObject().
Referenced by FsRtlpSetSymbolicLink(), HalpNextDriveLetter(), IoAssignDriveLetters(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), and WmipDriverEntry().
NTKERNELAPI PKEVENT IoCreateSynchronizationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
Definition at line 6232 of file iosubs.c.
References EVENT_ALL_ACCESS, ExEventObjectType, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, OBJ_OPENIF, ObReferenceObjectByHandle, PAGED_CODE, SynchronizationEvent, TRUE, VOID, and ZwCreateEvent().
NTKERNELAPI NTSTATUS IoCreateUnprotectedSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
Definition at line 6312 of file iosubs.c.
References InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, PAGED_CODE, SYMBOLIC_LINK_ALL_ACCESS, ZwClose(), and ZwCreateSymbolicLinkObject().
NTKERNELAPI NTSTATUS IoCsqInitialize (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
Definition at line 110 of file cancelapi.c.
References IO_TYPE_CSQ, NULL, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS IoCsqInitializeEx (IN PIO_CSQ Csq, IN PIO_CSQ_INSERT_IRP_EX CsqInsertIrp, IN PIO_CSQ_REMOVE_IRP CsqRemoveIrp, IN PIO_CSQ_PEEK_NEXT_IRP CsqPeekNextIrp, IN PIO_CSQ_ACQUIRE_LOCK CsqAcquireLock, IN PIO_CSQ_RELEASE_LOCK CsqReleaseLock, IN PIO_CSQ_COMPLETE_CANCELED_IRP CsqCompleteCanceledIrp)
Definition at line 150 of file cancelapi.c.
References IO_TYPE_CSQ_EX, NULL, and STATUS_SUCCESS.
NTKERNELAPI VOID IoCsqInsertIrp (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context)
Definition at line 460 of file cancelapi.c.
References CSQLIB_DDI, IoCsqInsertIrpEx(), NULL, and VOID.
NTKERNELAPI NTSTATUS IoCsqInsertIrpEx (IN PIO_CSQ Csq, IN PIRP Irp, IN PIO_CSQ_IRP_CONTEXT Context, IN PVOID InsertContext)
Definition at line 190 of file cancelapi.c.
References ASSERT, IO_TYPE_CSQ_EX, IO_TYPE_CSQ_IRP_CONTEXT, IoMarkIrpPending, IopCsqCancelRoutine(), IoSetCancelRoutine, NT_SUCCESS, NULL, and STATUS_SUCCESS.
Referenced by IoCsqInsertIrp().
NTKERNELAPI PIRP IoCsqRemoveIrp (IN PIO_CSQ Csq, IN PIO_CSQ_IRP_CONTEXT Context)
Definition at line 389 of file cancelapi.c.
References ASSERT, IoSetCancelRoutine, NULL, and PIRP.
NTKERNELAPI PIRP IoCsqRemoveNextIrp (IN PIO_CSQ Csq, IN PVOID PeekContext)
Definition at line 314 of file cancelapi.c.
References ASSERT, _IO_CSQ_IRP_CONTEXT::Csq, IO_TYPE_CSQ_IRP_CONTEXT, IoSetCancelRoutine, _IO_CSQ_IRP_CONTEXT::Irp, NULL, PIRP, and _IO_CSQ_IRP_CONTEXT::Type.
NTKERNELAPI VOID IoDeleteController (IN PCONTROLLER_OBJECT ControllerObject)
Definition at line 6380 of file iosubs.c.
References ObDereferenceObject(), and PAGED_CODE.
NTKERNELAPI VOID IoDeleteDevice (IN PDEVICE_OBJECT DeviceObject)
Definition at line 6437 of file iosubs.c.
References DO_DEVICE_HAS_NAME, DO_SHUTDOWN_REGISTERED, DOE_DELETE_PENDING, ExFreePool(), IopCompleteUnloadOrDelete(), IopRemoveTimerFromTimerList(), IoUnregisterShutdownNotification(), IOV_DELETE_DEVICE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, ObMakeTemporaryObject(), and PoRunDownDeviceObject().
Referenced by RawCheckForDismount(), RawInitialize(), RawMountVolume(), RawShutdown(), and WmipDriverEntry().
NTKERNELAPI VOID IoDeleteDriver (IN PDRIVER_OBJECT DriverObject)
Definition at line 14205 of file iosubs.c.
References ObDereferenceObject().
NTKERNELAPI NTSTATUS IoDeleteSymbolicLink (IN PUNICODE_STRING SymbolicLinkName)
Definition at line 6715 of file iosubs.c.
References DELETE, ExVerifySuite(), InitializeObjectAttributes, IopDeleteSessionSymLinks(), NT_SUCCESS, NULL, ObIsLUIDDeviceMapsEnabled(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, TerminalServer, TRUE, ZwClose(), ZwMakeTemporaryObject(), and ZwOpenSymbolicLinkObject().
Referenced by FsRtlpSetSymbolicLink(), and WmipDriverEntry().
NTKERNELAPI VOID IoDetachDevice (IN OUT PDEVICE_OBJECT TargetDevice)
Definition at line 6796 of file iosubs.c.
References ASSERT, _DEVOBJ_EXTENSION::AttachedTo, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_UNLOAD_PENDING, IopCompleteUnloadOrDelete(), IOV_DETACH_DEVICE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
NTKERNELAPI VOID IoDisconnectInterrupt (IN PKINTERRUPT InterruptObject)
Definition at line 6862 of file iosubs.c.
References CONTAINING_RECORD, ExFreePool(), _IO_INTERRUPT_STRUCTURE::InterruptArray, _IO_INTERRUPT_STRUCTURE::InterruptObject, KeDisconnectInterrupt(), MAXIMUM_PROCESSORS, NULL, and PAGED_CODE.
Referenced by IoConnectInterrupt().
NTKERNELAPI VOID IoEnqueueIrp (IN PIRP Irp)
Definition at line 6927 of file iosubs.c.
References IopQueueThreadIrp(), and PAGED_CODE.
NTKERNELAPI NTSTATUS IoEnumerateDeviceObjectList (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT * DeviceObjectList, IN ULONG DeviceObjectListSize, OUT PULONG ActualNumberDeviceObjects)
Definition at line 14279 of file iosubs.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, ObReferenceObject, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS IoEnumerateRegisteredFiltersList (IN PDRIVER_OBJECT * DriverObjectList, IN ULONG DriverObjectListSize, OUT PULONG ActualNumberDriverObjects)
Definition at line 14924 of file iosubs.c.
References CONTAINING_RECORD, _NOTIFICATION_PACKET::DriverObject, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, IopDatabaseResource, IopFsNotifyChangeQueueHead, ObReferenceObject, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and TRUE.
NTKERNELAPI BOOLEAN IoFastQueryNetworkAttributes (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN ULONG OpenOptions, OUT PIO_STATUS_BLOCK IoStatus, OUT PFILE_NETWORK_OPEN_INFORMATION Buffer)
Definition at line 6961 of file iosubs.c.
References _OPEN_PACKET::CreateOptions, _OPEN_PACKET::Disposition, FILE_OPEN, FILE_OPEN_REPARSE_POINT, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, _OPEN_PACKET::FullAttributes, _OPEN_PACKET::Information, IO_FORCE_ACCESS_CHECK, IO_TYPE_OPEN_PACKET, KernelMode, _OPEN_PACKET::LocalFileObject, _OPEN_PACKET::NetworkInformation, NT_SUCCESS, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, _OPEN_PACKET::Options, _OPEN_PACKET::ParseCheck, _OPEN_PACKET::QueryOnly, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, TRUE, _OPEN_PACKET::Type, and ZwClose().
NTKERNELAPI NTSTATUS FASTCALL IofCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
Definition at line 2239 of file iosubs.c.
References IopfCallDriver(), NULL, and pIofCallDriver.
Referenced by IoCallDriver().
NTSTATUS FASTCALL IofCallDriverSpecifyReturn (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp, IN PVOID ReturnAddress OPTIONAL)
Definition at line 2258 of file iosubs.c.
References IopfCallDriver(), NULL, and pIofCallDriver.
NTKERNELAPI VOID FASTCALL IofCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
Definition at line 3325 of file iosubs.c.
References pIofCompleteRequest.
Referenced by IoCompleteRequest().
PDEVICE_OBJECT IoFindDeviceThatFailedIrp (IN PIRP Irp)
Definition at line 14878 of file iosubs.c.
References _IO_STACK_LOCATION::Control, _IO_STACK_LOCATION::DeviceObject, IRP, NT_SUCCESS, NULL, and SL_ERROR_RETURNED.
NTKERNELAPI BOOLEAN IoForwardIrpSynchronously (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTKERNELAPI VOID IoFreeController (IN PCONTROLLER_OBJECT ControllerObject)
Definition at line 7077 of file iosubs.c.
References CONTAINING_RECORD, DeallocateObject, DEVICE_OBJECT, KeRemoveDeviceQueue(), and NULL.
Referenced by IoAllocateController().
VOID IoFreeDumpStack (IN PDUMP_STACK_CONTEXT DumpStack)
NTKERNELAPI VOID IoFreeErrorLogEntry (PVOID ElEntry)
NTKERNELAPI VOID IoFreeIrp (IN PIRP Irp)
Definition at line 7135 of file iosubs.c.
References pIoFreeIrp.
Referenced by IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoCancelFileOpen(), IopCloseFile(), IopCompletePageWrite(), IopCompleteRequest(), IopDeleteFile(), IopDeleteIoCompletion(), IopDropIrp(), IopExceptionCleanup(), IopfCompleteRequest(), IopFreeIrpAndMdls(), IopParseDevice(), IopUserCompletion(), IopUserRundown(), NtRemoveIoCompletion(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipSendWmiIrp(), and WmipSetTraceNotify().
NTKERNELAPI VOID IoFreeMdl (IN PMDL Mdl)
Definition at line 7260 of file iosubs.c.
References ExFreePool(), ExFreeToPPLookasideList(), LookasideMdlList, MDL_ALLOCATED_FIXED_SIZE, MDL_ALLOCATED_MUST_SUCCEED, and MmPrepareMdlForReuse.
Referenced by CcMdlRead(), CcMdlReadComplete2(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPrepareMdlWrite(), CcZeroData(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopCompleteRequest(), IopDropIrp(), IopExceptionCleanup(), and IopFreeIrpAndMdls().
VOID IoFreePoDeviceNotifyList (IN OUT PVOID Order)
NTKERNELAPI VOID IoFreeWorkItem (PIO_WORKITEM IoWorkItem)
Definition at line 935 of file misc.c.
References ASSERT, and ExFreePool().
NTKERNELAPI PDEVICE_OBJECT IoGetAttachedDevice (IN PDEVICE_OBJECT DeviceObject)
Definition at line 7301 of file iosubs.c.
Referenced by IoGetAttachedDeviceReference(), IoGetRelatedDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCloseFile(), IopDeleteFile(), IopParseDevice(), IopShutdownBaseFileSystems(), IopXxxControlFile(), NtQueryInformationFile(), NtSetInformationFile(), and NtUnlockFile().
NTKERNELAPI PDEVICE_OBJECT IoGetAttachedDeviceReference (IN PDEVICE_OBJECT DeviceObject)
Definition at line 7344 of file iosubs.c.
References IoGetAttachedDevice(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and ObReferenceObject.
Referenced by HalpIsOldStyleFloppy(), HalpQueryDriveLayout(), HalpQueryPartitionType(), IopComputeHarddiskDerangements(), IoShutdownSystem(), and WmipForwardWmiIrp().
NTKERNELAPI PDEVICE_OBJECT IoGetBaseFileSystemDeviceObject (IN PFILE_OBJECT FileObject)
Definition at line 7377 of file iosubs.c.
References ASSERT, FO_DIRECT_DEVICE_OPEN, and NULL.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlMdlRead(), FsRtlMdlReadComplete(), FsRtlMdlWriteComplete(), FsRtlPrepareMdlWrite(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTKERNELAPI NTSTATUS IoGetBootDiskInformation (IN OUT PBOOTDISK_INFORMATION BootDiskInformation, IN ULONG Size)
Definition at line 12810 of file iosubs.c.
References _LOADER_PARAMETER_BLOCK::ArcBootDeviceName, _LOADER_PARAMETER_BLOCK::ArcDiskInformation, _LOADER_PARAMETER_BLOCK::ArcHalDeviceName, _ARC_DISK_SIGNATURE::ArcName, _BOOTDISK_INFORMATION_EX::BootDeviceGuid, _BOOTDISK_INFORMATION_EX::BootDeviceIsGpt, _DISK_GEOMETRY::BytesPerSector, CONTAINING_RECORD, _CONFIGURATION_INFORMATION::DiskCount, _ARC_DISK_INFORMATION::DiskSignatures, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, _LIST_ENTRY::Flink, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_DISK_GET_DRIVE_GEOMETRY, IoGetConfigurationInformation(), IoGetDeviceObjectPointer(), IopLoaderBlock, IopVerifyDiskSignature(), IoReadPartitionTableEx(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PIRP, RtlAnsiStringToUnicodeString(), RtlEqualString(), RtlFreeUnicodeString(), RtlInitAnsiString(), sprintf(), _IO_STATUS_BLOCK::Status, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_SUCCESS, STATUS_TOO_LATE, Suspended, _BOOTDISK_INFORMATION_EX::SystemDeviceGuid, _BOOTDISK_INFORMATION_EX::SystemDeviceIsGpt, and TRUE.
NTKERNELAPI PCONFIGURATION_INFORMATION IoGetConfigurationInformation (VOID)
Definition at line 7442 of file iosubs.c.
References PAGED_CODE.
Referenced by IoAssignDriveLetters(), IoGetBootDiskInformation(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), and NtQuerySystemInformation().
NTKERNELAPI PEPROCESS IoGetCurrentProcess (VOID)
Definition at line 7475 of file iosubs.c.
References PsGetCurrentProcess().
NTKERNELAPI PDEVICE_OBJECT IoGetDeviceAttachmentBaseRef (IN PDEVICE_OBJECT DeviceObject)
Definition at line 14348 of file iosubs.c.
References IopGetDeviceAttachmentBase(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and ObReferenceObject.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTSTATUS IoGetDeviceInstanceName (IN PDEVICE_OBJECT PhysicalDeviceObject, OUT PUNICODE_STRING InstanceName)
Referenced by WmipPDOToDeviceInstanceName().
NTKERNELAPI NTSTATUS IoGetDeviceObjectPointer (IN PUNICODE_STRING ObjectName, IN ACCESS_MASK DesiredAccess, OUT PFILE_OBJECT * FileObject, OUT PDEVICE_OBJECT * DeviceObject)
Definition at line 7513 of file iosubs.c.
References FILE_NON_DIRECTORY_FILE, InitializeObjectAttributes, IoFileObjectType, IoGetRelatedDeviceObject(), KernelMode, NT_SUCCESS, NULL, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGED_CODE, VOID, ZwClose(), and ZwOpenFile().
Referenced by HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoGetBootDiskInformation(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), and IoVolumeDeviceToDosName().
NTKERNELAPI PDEVICE_OBJECT IoGetDeviceToVerify (IN PETHREAD Thread)
Definition at line 7608 of file iosubs.c.
NTKERNELAPI NTSTATUS IoGetDiskDeviceObject (IN PDEVICE_OBJECT FileSystemDeviceObject, OUT PDEVICE_OBJECT * DiskDeviceObject)
Definition at line 14403 of file iosubs.c.
References _VPB::Flags, IoAcquireVpbSpinLock(), IoReleaseVpbSpinLock(), ObReferenceObject, _VPB::RealDevice, _VPB::ReferenceCount, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_VOLUME_DISMOUNTED, and VPB_MOUNTED.
NTKERNELAPI struct _DMA_ADAPTER* IoGetDmaAdapter (IN PDEVICE_OBJECT PhysicalDeviceObject, OPTIONAL IN struct _DEVICE_DESCRIPTION * DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
NTKERNELAPI PVOID IoGetDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress)
Definition at line 7646 of file iosubs.c.
References _IO_CLIENT_EXTENSION::ClientIdentificationAddress, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, _IO_CLIENT_EXTENSION::NextExtension, and NULL.
VOID IoGetDumpHiberRanges (IN PVOID HiberContext, IN PDUMP_STACK_CONTEXT DumpStack)
NTSTATUS IoGetDumpStack (IN PWCHAR ModulePrefix, OUT PDUMP_STACK_CONTEXT * DumpStack, IN enum _DEVICE_USAGE_NOTIFICATION_TYPE UsageType, IN ULONG IgnoreDeviceUsageFailure)
PVOID IoGetFileObjectFilterContext (IN PFILE_OBJECT FileObject)
Definition at line 14684 of file iosubs.c.
References _IOP_FILE_OBJECT_EXTENSION::FilterContext, FO_FILE_OBJECT_HAS_EXTENSION, and NULL.
Referenced by FsRtlInsertPerFileObjectContext(), FsRtlLookupPerFileObjectContext(), FsRtlPTeardownPerFileObjectContexts(), and FsRtlRemovePerFileObjectContext().
NTKERNELAPI PGENERIC_MAPPING IoGetFileObjectGenericMapping (VOID)
Definition at line 7698 of file iosubs.c.
References IopFileMapping, and PAGED_CODE.
NTKERNELAPI PVOID IoGetInitialStack (VOID)
Definition at line 7729 of file iosubs.c.
References _KTHREAD::InitialStack, PsGetCurrentThread(), and _ETHREAD::Tcb.
NTSTATUS IoGetLegacyVetoList (OUT PWSTR *VetoList OPTIONAL, OUT PPNP_VETO_TYPE VetoType)
Referenced by ExpQueryLegacyDriverInformation().
NTKERNELAPI PDEVICE_OBJECT IoGetLowerDeviceObject (IN PDEVICE_OBJECT DeviceObject)
Definition at line 14232 of file iosubs.c.
References DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_UNLOAD_PENDING, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and ObReferenceObject.
NTKERNELAPI IO_PAGING_PRIORITY FASTCALL IoGetPagingIoPriority (IN PIRP IRP)
Definition at line 14847 of file iosubs.c.
References IoPagingPriorityHigh, IoPagingPriorityInvalid, IoPagingPriorityNormal, IRP_HIGH_PRIORITY_PAGING_IO, and IRP_PAGING_IO.
PVOID IoGetPoNotifyParent (PVOID Notify)
NTKERNELAPI PDEVICE_OBJECT IoGetRelatedDeviceObject (IN PFILE_OBJECT FileObject)
Definition at line 7895 of file iosubs.c.
References ASSERT, FO_DIRECT_DEVICE_OPEN, FO_FILE_OBJECT_HAS_EXTENSION, IoGetAttachedDevice(), IopVerifyDeviceObjectOnStack(), NULL, and _IOP_FILE_OBJECT_EXTENSION::TopDeviceObjectHint.
Referenced by BuildQueryDirectoryIrp(), CcMdlReadComplete(), CcMdlWriteComplete(), CcSetValidData(), CcZeroData(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlGetFileSize(), FsRtlMdlRead(), FsRtlMdlReadComplete(), FsRtlMdlReadDev(), FsRtlMdlWriteComplete(), FsRtlPrepareMdlWrite(), FsRtlPrepareMdlWriteDev(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), FsRtlReleaseFileForModWrite(), FsRtlSetFileSize(), IoAsynchronousPageWrite(), IoAttachDevice(), IoGetDeviceObjectPointer(), IoPageRead(), IopCloseFile(), IopDeleteFile(), IopGetBasicInformationFile(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopIsSameMachine(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopParseFile(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IopXxxControlFile(), IoSetInformation(), IoSynchronousPageWrite(), NtCreatePagingFile(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), RawSetInformation(), and WmipObjectToPDO().
NTSTATUS IoGetRelatedTargetDevice (IN PFILE_OBJECT FileObject, OUT PDEVICE_OBJECT * DeviceObject)
Referenced by FsRtlNotifyVolumeEvent(), and NtSetVolumeInformationFile().
FORCEINLINE ULONG_PTR IoGetRemainingStackSize (VOID)
Definition at line 3728 of file io.h.
References IoGetStackLimits().
NTKERNELAPI PEPROCESS IoGetRequestorProcess (IN PIRP Irp)
Definition at line 8034 of file iosubs.c.
References AttachedApcEnvironment, CONTAINING_RECORD, NULL, OriginalApcEnvironment, and THREAD_TO_PROCESS.
Referenced by FsRtlCheckLockForReadAccess(), FsRtlCheckLockForWriteAccess(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlProcessFileLock(), and IoGetRequestorProcessId().
NTKERNELAPI ULONG IoGetRequestorProcessId (IN PIRP Irp)
Definition at line 7990 of file iosubs.c.
References HandleToUlong, IoGetRequestorProcess(), NULL, and _EPROCESS::UniqueProcessId.
NTKERNELAPI NTSTATUS IoGetRequestorSessionId (IN PIRP Irp, OUT PULONG pSessionId)
Definition at line 13539 of file iosubs.c.
References MmGetSessionId(), STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and THREAD_TO_PROCESS.
NTKERNELAPI VOID IoGetStackLimits (OUT PULONG_PTR LowLimit, OUT PULONG_PTR HighLimit)
Definition at line 7764 of file iosubs.c.
References DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, _KPRCB::DpcStack, KeGetCurrentIrql(), KeGetCurrentPrcb(), KERNEL_STACK_SIZE, and RtlpGetStackLimits().
Referenced by IoGetRemainingStackSize().
NTKERNELAPI PIRP IoGetTopLevelIrp (VOID)
Definition at line 8092 of file iosubs.c.
References PIRP, PsGetCurrentThread(), and _ETHREAD::TopLevelIrp.
Referenced by FsRtlCreateSectionForDataScan().
BOOLEAN IoInitializeCrashDump (IN HANDLE Pagefile)
Referenced by NtCreatePagingFile().
NTSTATUS IoInitializeDumpStack (IN PDUMP_STACK_CONTEXT DumpStack, IN PUCHAR MessageBuffer OPTIONAL)
NTKERNELAPI VOID IoInitializeIrp (IN OUT PIRP Irp, IN USHORT PacketSize, IN CCHAR StackSize)
Definition at line 8127 of file iosubs.c.
References InitializeListHead(), IO_TYPE_IRP, IOV_INITIALIZE_IRP, IRP, KeGetCurrentApcEnvironment, and RtlZeroMemory.
Referenced by IopAllocateReserveIrp(), WmipDisableKernelTrace(), and WmipEnableKernelTrace().
NTKERNELAPI VOID NTAPI IoInitializeRemoveLockEx (IN PIO_REMOVE_LOCK Lock, IN ULONG AllocateTag, IN ULONG MaxLockedMinutes, IN ULONG HighWatermark, IN ULONG RemlockSize)
NTKERNELAPI NTSTATUS IoInitializeTimer (IN PDEVICE_OBJECT DeviceObject, IN PIO_TIMER_ROUTINE TimerRoutine, IN PVOID Context)
Definition at line 8226 of file iosubs.c.
References _IO_TIMER::Context, _IO_TIMER::DeviceObject, ExAllocatePoolWithTag, ExInterlockedInsertTailList(), IO_TYPE_TIMER, IopTimerLock, IopTimerQueueHead, NonPagedPool, PAGED_CODE, RtlZeroMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _IO_TIMER::TimerList, _IO_TIMER::TimerRoutine, and _IO_TIMER::Type.
NTKERNELAPI BOOLEAN IoInitSystem (PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 141 of file ioinit.c.
References ASSERT, _STRING::Buffer, CcPfBeginBootPhase(), CmRegistryMachineSystemCurrentControlSetServicesEventLog, _KEY_VALUE_PARTIAL_INFORMATION::Data, DbgPrint(), DEFAULT_LARGE_IRP_LOCATIONS, DEFAULT_LOOKASIDE_IRP_LIMIT, DEVICENAME_BUFFER_LENGTH, _LINK_TRACKING_PACKET::Event, EVENT_ALL_ACCESS, ExAllocatePoolWithTag, ExEventObjectType, ExFreePool(), ExInitializeResourceLite(), ExInitializeSystemLookasideList(), ExInitializeWorkItem, ExSystemLookasideListHead, _IOP_HARD_ERROR_QUEUE::ExWorkItem, FALSE, FileFsMaximumInformation, FileMaximumInformation, _IOP_IRP_STACK_PROFILER::Flags, FLG_ENABLE_KDEBUG_SYMBOL_LOAD, HalInitPnpDriver, HEADLESS_LOG_ANSI_TO_UNICODE_FAILED, HEADLESS_LOG_ASSIGN_SYSTEM_ROOT_FAILED, HEADLESS_LOG_BOOT_DRIVERS_INIT_FAILED, HEADLESS_LOG_EVENT_CREATE_FAILED, HEADLESS_LOG_LOCATE_SYSTEM_DLL_FAILED, HEADLESS_LOG_OBJECT_TYPE_CREATE_FAILED, HEADLESS_LOG_PNP_PHASE0_INIT_FAILED, HEADLESS_LOG_PNP_PHASE1_INIT_FAILED, HEADLESS_LOG_PROTECT_SYSTEM_ROOT_FAILED, HEADLESS_LOG_ROOT_DIR_CREATE_FAILED, HEADLESS_LOG_SYSTEM_DRIVERS_INIT_FAILED, HEADLESS_LOG_UNICODE_TO_ANSI_FAILED, HeadlessKernelAddLogEntry(), Index, InitializeListHead(), InitializeObjectAttributes, IoAssignDriveLetters(), IOP_ENABLE_AUTO_SIZING, IOP_FIXED_SIZE_MDL_PFNS, IopAddRemoteBootValuesToRegistry(), IopBootDriverReinitializeQueueHead, IopCallDriverReinitializationRoutines(), IopCdRomFileSystemQueueHead, IopCompletionLookasideList, IopCrashDumpLock, IopCreateObjectTypes(), IopCreateRootDirectories(), IopCurrentHardError, IopDatabaseResource, IopDiskFileSystemQueueHead, IopDriverLoadResource, IopDriverReinitializeQueueHead, IopErrorLogDisabledThisBoot, IopErrorLogListHead, IopErrorLogLock, IopFsNotifyChangeQueueHead, IopHardError, IopHardErrorThread(), IopInitFailCode, IopInitializeBootDrivers(), IopInitializeIrpStackProfiler(), IopInitializePlugPlayServices(), IopInitializeReserveIrp(), IopInitializeSystemDrivers(), IopIrpAutoSizingEnabled, IopIrpStackProfiler, IopLargeIrpLookasideList, IopLargeIrpStackLocations, IopLinkTrackingPacket, IopLinkTrackingPortObject, IopLinkTrackingServiceEvent, IopLoaderBlock, IopMarkHalDeviceNode(), IopMdlLookasideList, IopNetworkFileSystemQueueHead, IopNotifyLastChanceShutdownQueueHead, IopNotifyShutdownQueueHead, IopProtectSystemPartition(), IopQueryFsOperationAccess, IopQueryFsOperationLength, IopQueryOperationAccess, IopQueryOperationLength, IopReassignSystemRoot(), IopReserveIrpAllocator, IopSecurityResource, IopSetFsOperationAccess, IopSetFsOperationLength, IopSetIoRoutines(), IopSetOperationAccess, IopSetOperationLength, IopSmallIrpLookasideList, IopStartNetworkForRemoteBoot(), IopTapeFileSystemQueueHead, IopTimer, IopTimerDispatch(), IopTimerDpc, IopTimerLock, IopTimerQueueHead, IopUniqueDeviceObjectNumber, IoRemoteBootClient, IoStatisticsLock, IRP, KeBugCheckEx(), KeInitializeDpc(), KeInitializeEvent(), KeInitializeSemaphore(), KeInitializeSpinLock(), KeInitializeTimerEx(), KeNumberProcessors, KernelMode, KeSetTimerEx(), KEY_READ, KeyValuePartialInformation, KiProcessorBlock, _PP_LOOKASIDE_LIST::L, _STRING::Length, LookasideCompletionList, _KPRCB::LookasideIrpFloat, LookasideLargeIrpList, LookasideMdlList, LookasideSmallIrpList, _STRING::MaximumLength, _UNICODE_STRING::MaximumLength, MAXLONG, MmIsThisAnNtAsSystem(), MmLargeSystem, MmMediumSystem, MmQuerySystemSize(), MmSmallSystem, NETWORK_BOOT_INITIALIZATION_FAILED, NonPagedPool, NotificationEvent, NT_SUCCESS, NtCreateEvent(), NtGlobalFlag, NtQueryValueKey(), NtSystemRoot, NULL, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, ObReferenceObjectByHandle, _PP_LOOKASIDE_LIST::P, PfSystemDriverInitPhase, PoInitDriverServices(), PpLastGoodDoBootProcessing(), _KPRCB::PPLookasideList, PsLocateSystemDll(), _LARGE_INTEGER::QuadPart, REG_DWORD, RtlAllocateStringRoutine, RtlAnsiStringToUnicodeString(), RtlInitUnicodeString(), RtlUnicodeStringToAnsiString(), SERVICE_DISABLED, SynchronizationEvent, SynchronizationTimer, _IOP_HARD_ERROR_QUEUE::ThreadStarted, TRUE, _KEY_VALUE_PARTIAL_INFORMATION::Type, VALUE_BUFFER_LENGTH, VOID, WMIInitialize(), _IOP_HARD_ERROR_QUEUE::WorkQueue, _IOP_HARD_ERROR_QUEUE::WorkQueueSemaphore, _IOP_HARD_ERROR_QUEUE::WorkQueueSpinLock, and ZwOpenKey().
Referenced by Phase1InitializationDiscard().
BOOLEAN IoIsDeviceEjectable (IN PDEVICE_OBJECT)
Definition at line 14757 of file iosubs.c.
References FALSE, FILE_FLOPPY_DISKETTE, INIT_WINPEMODE_INRAM, InitWinPEModeType, and TRUE.
Referenced by MiCreateImageFileMap().
NTKERNELAPI BOOLEAN IoIsFileOriginRemote (IN PFILE_OBJECT FileObject)
Definition at line 14581 of file iosubs.c.
References FALSE, FO_REMOTE_ORIGIN, and TRUE.
Referenced by CcCanIWrite(), and CcForceWriteThrough().
NTKERNELAPI BOOLEAN IoIsOperationSynchronous (IN PIRP Irp)
Definition at line 8298 of file iosubs.c.
References FALSE, FO_SYNCHRONOUS_IO, IoGetCurrentIrpStackLocation, IRP_PAGING_IO, IRP_SYNCHRONOUS_API, IRP_SYNCHRONOUS_PAGING_IO, and TRUE.
Referenced by FsRtlAcknowledgeOplockBreak(), and FsRtlOplockFsctrl().
NTKERNELAPI BOOLEAN IoIsSystemThread (IN PETHREAD Thread)
Definition at line 8356 of file iosubs.c.
References IS_SYSTEM_THREAD.
BOOLEAN IoIsTriageDumpEnabled (VOID)
Referenced by KeBugCheck2().
NTKERNELAPI BOOLEAN IoIsValidNameGraftingBuffer (IN PIRP Irp, IN PREPARSE_DATA_BUFFER ReparseBuffer)
Definition at line 8388 of file iosubs.c.
References ASSERT, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, InitializeObjectAttributes, IO_REPARSE_TAG_MOUNT_POINT, IoGetCurrentIrpStackLocation, _UNICODE_STRING::Length, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, _UNICODE_STRING::MaximumLength, MOUNTMGR_IS_VOLUME_NAME, NonPagedPool, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, _IO_STACK_LOCATION::Parameters, _REPARSE_DATA_BUFFER::PathBuffer, REPARSE_DATA_BUFFER_HEADER_SIZE, RtlCopyMemory, RtlInitUnicodeString(), SYMBOLIC_LINK_QUERY, TRUE, UNICODE_NULL, ZwClose(), ZwOpenSymbolicLinkObject(), and ZwQuerySymbolicLinkObject().
NTKERNELAPI BOOLEAN IoIsWdmVersionAvailable (IN UCHAR MajorVersion, IN UCHAR MinorVersion)
NTKERNELAPI PIRP IoMakeAssociatedIrp (IN PIRP Irp, IN CCHAR StackSize)
Definition at line 8976 of file iosubs.c.
References ExAllocatePoolWithTag, ExFreePool(), InterlockedPopEntrySList(), IopInitializeIrp, IopIrpAutoSizingEnabled, IopLargeIrpStackLocations, IoSizeOfIrp, IRP_ALLOCATED_FIXED_SIZE, IRP_ASSOCIATED_IRP, IRP_HIGH_PRIORITY_PAGING_IO, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, LookasideLargeIrpList, LookasideSmallIrpList, NonPagedPool, NULL, _PP_LOOKASIDE_LIST::P, PIRP, _KPRCB::PPLookasideList, and _GENERAL_LOOKASIDE::TotalAllocates.
VOID IoMovePoNotifyChildren (IN PVOID Notify, IN PVOID Order)
NTSTATUS IoNotifyPowerOperationVetoed (IN POWER_ACTION VetoedPowerOperation, IN PDEVICE_OBJECT TargetedDeviceObject OPTIONAL, IN PDEVICE_OBJECT VetoingDeviceObject)
NTKERNELAPI BOOLEAN IoPageFileCreated (IN HANDLE FileHandle)
NTKERNELAPI NTSTATUS IoPageRead (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 9122 of file iosubs.c.
References CcMissCounter, _IO_STACK_LOCATION::FileObject, InterlockedIncrement, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAllocateReserveIrp(), IRP_INPUT_OPERATION, IRP_MJ_READ, IRP_NOCACHE, IRP_PAGING_IO, IRP_SET_USER_EVENT, IRP_SYNCHRONOUS_PAGING_IO, KernelMode, _IO_STACK_LOCATION::MajorFunction, MmIsFileObjectAPagingFile(), MmIsRecursiveIoFault(), PAGE_SHIFT, PAGE_SIZE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and STATUS_INSUFFICIENT_RESOURCES.
Referenced by MiCcPutPagesInTransition(), MiCreateImageFileMap(), MiDispatchFault(), and MiMakeOutswappedPageResident().
VOID IopBootLog (PUNICODE_STRING LogEntry, BOOLEAN Loaded)
Definition at line 9549 of file internal.c.
References BOOTLOG_STRSIZE, CmRegistryMachineSystemCurrentControlSetControlBootLog, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _BOOT_LOG_RECORD::FileLogging, IopBootLogToFile(), IopOpenRegistryKey(), IopSetRegistryStringValue(), KEY_ALL_ACCESS, KeyName, _BOOT_LOG_RECORD::LoadedString, _BOOT_LOG_RECORD::NextKey, _BOOT_LOG_RECORD::NotLoadedString, NT_SUCCESS, NULL, PAGED_CODE, _BOOT_LOG_RECORD::Resource, RtlAppendUnicodeStringToString(), RtlCopyUnicodeString(), RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitUnicodeString(), Space, Status, swprintf, TRUE, and ZwClose().
Referenced by IopInitializeBootLogging(), and IopLoadDriver().
VOID IopCopyBootLogRegistryToFile (VOID)
Definition at line 9664 of file internal.c.
References BOOTLOG_STRSIZE, CmRegistryMachineSystemCurrentControlSetControlBootLog, _KEY_VALUE_FULL_INFORMATION::DataOffset, _TIME_FIELDS::Day, ExAcquireResourceExclusiveLite(), ExFreePool(), ExReleaseResourceLite(), ExSystemTimeToLocalTime(), FALSE, _BOOT_LOG_RECORD::FileLogging, _BOOT_LOG_RECORD::HeaderString, _TIME_FIELDS::Hour, Index, IopBootLogToFile(), IopGetRegistryValue(), IopOpenRegistryKey(), KeBootTime, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KEY_ALL_ACCESS, KeyName, _TIME_FIELDS::Milliseconds, _TIME_FIELDS::Minute, _TIME_FIELDS::Month, _BOOT_LOG_RECORD::NextKey, NT_SUCCESS, NULL, PAGED_CODE, _BOOT_LOG_RECORD::Resource, RtlAnsiStringToUnicodeString(), RtlCreateUnicodeString(), RtlFreeUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), RtlTimeToTimeFields(), _TIME_FIELDS::Second, sprintf(), Status, swprintf, TRUE, _TIME_FIELDS::Year, ZwClose(), and ZwDeleteKey().
Referenced by NtInitializeRegistry().
VOID IopInitializeBootLogging (PLOADER_PARAMETER_BLOCK LoaderBlock, PCHAR HeaderString)
Definition at line 9430 of file internal.c.
References BOOTLOG_LOADED, BOOTLOG_NOT_LOADED, _STRING::Buffer, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAllocatePool, ExInitializeResourceLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _BOOT_LOG_RECORD::HeaderString, IopBootLog(), _STRING::Length, _UNICODE_STRING::Length, _BOOT_LOG_RECORD::LoadedString, _LOADER_PARAMETER_BLOCK::LoadOrderListHead, _STRING::MaximumLength, NonPagedPool, _BOOT_LOG_RECORD::NotLoadedString, NT_SUCCESS, NULL, PAGED_CODE, PsLoadedModuleList, PsLoadedModuleResource, _BOOT_LOG_RECORD::Resource, RtlAnsiStringToUnicodeString(), RtlCreateUnicodeStringFromAsciiz(), RtlFindMessage(), RtlZeroMemory, Status, strlen(), _MESSAGE_RESOURCE_ENTRY::Text, TRUE, and UNICODE_NULL.
NTSTATUS IopSetRegistryStringValue (IN HANDLE KeyHandle, IN PUNICODE_STRING ValueName, IN PUNICODE_STRING ValueData)
Referenced by IopBootLog().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoQueryDeviceDescription (IN PINTERFACE_TYPE BusType OPTIONAL, IN PULONG BusNumber OPTIONAL, IN PCONFIGURATION_TYPE ControllerType OPTIONAL, IN PULONG ControllerNumber OPTIONAL, IN PCONFIGURATION_TYPE PeripheralType OPTIONAL, IN PULONG PeripheralNumber OPTIONAL, IN PIO_QUERY_DEVICE_ROUTINE CalloutRoutine, IN PVOID Context)
NTKERNELAPI NTSTATUS IoQueryFileDosDeviceName (IN PFILE_OBJECT FileObject, OUT POBJECT_NAME_INFORMATION * ObjectNameInformation)
Definition at line 13862 of file iosubs.c.
References ExAllocatePoolWithTag, ExFreePool(), IopQueryNameInternal(), KernelMode, NULL, PagedPool, Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by CcWriteBehind(), and MiLdwPopupWorker().
NTKERNELAPI NTSTATUS IoQueryFileInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
Definition at line 9271 of file iosubs.c.
References IopQueryXxxInformation(), KernelMode, PAGED_CODE, and TRUE.
Referenced by IopGetNetworkOpenInformation(), and IopParseDevice().
NTKERNELAPI NTSTATUS IoQueryVolumeInformation (IN PFILE_OBJECT FileObject, IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, OUT PVOID FsInformation, OUT PULONG ReturnedLength)
Definition at line 9327 of file iosubs.c.
References IopQueryXxxInformation(), KernelMode, and PAGED_CODE.
Referenced by MiAttemptPageFileExtension(), and NtCreatePagingFile().
NTKERNELAPI VOID IoQueueThreadIrp (IN PIRP Irp)
Definition at line 9383 of file iosubs.c.
References IopQueueThreadIrp().
NTKERNELAPI VOID IoQueueWorkItem (IN PIO_WORKITEM IoWorkItem, IN PIO_WORKITEM_ROUTINE WorkerRoutine, IN WORK_QUEUE_TYPE QueueType, IN PVOID Context)
Definition at line 964 of file misc.c.
References ASSERT, DISPATCH_LEVEL, ExQueueWorkItem(), KeGetCurrentIrql(), and ObReferenceObject.
NTKERNELAPI VOID IoRaiseHardError (IN PIRP Irp, IN PVPB Vpb OPTIONAL, IN PDEVICE_OBJECT RealDeviceObject)
Definition at line 9414 of file iosubs.c.
References CriticalWorkQueue, _ETHREAD::CrossThreadFlags, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, FIELD_OFFSET, IO_DISK_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IopAbortRequest(), IopDeallocateApc(), IopRaiseHardError(), IopStartApcHardError(), _IOP_APC_HARD_ERROR_PACKET::Irp, IRP_INPUT_OPERATION, IRP_MJ_CLEANUP, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_MOUNT_VOLUME, IRP_NOCACHE, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, IRP_VERIFIER_MASK, IS_SYSTEM_THREAD, _IOP_APC_HARD_ERROR_PACKET::Item, KeInitializeApc(), KeInsertQueueApc(), KernelMode, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, MmCopyVirtualMemory(), NonPagedPool, NT_SUCCESS, NULL, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PsGetCurrentProcess(), _IOP_APC_HARD_ERROR_PACKET::RealDeviceObject, RTL_ERRORMODE_FAILCRITICALERRORS, _ETHREAD::Tcb, _KTHREAD::Teb, THREAD_TO_PROCESS, TRUE, VOID, and _IOP_APC_HARD_ERROR_PACKET::Vpb.
NTKERNELAPI BOOLEAN IoRaiseInformationalHardError (IN NTSTATUS ErrorStatus, IN PUNICODE_STRING String OPTIONAL, IN PKTHREAD Thread OPTIONAL)
Definition at line 9615 of file iosubs.c.
References ArePacketsEquivalent, ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, CONTAINING_RECORD, DelayedWorkQueue, _IOP_HARD_ERROR_PACKET::ErrorStatus, ExAcquireSpinLock, ExAllocatePoolWithTag, ExFreePool(), ExQueueWorkItem(), ExReleaseSpinLock, _IOP_HARD_ERROR_QUEUE::ExWorkItem, FALSE, _LIST_ENTRY::Flink, InsertTailList(), InterlockedIncrement, IOP_MAXIMUM_OUTSTANDING_HARD_ERRORS, IopCurrentHardError, IopDeallocateApc(), IopHardError, IopRaiseInformationalHardError(), KeInitializeApc(), KeInsertQueueApc(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NonPagedPool, NULL, _IOP_HARD_ERROR_QUEUE::NumPendingApcPopups, OriginalApcEnvironment, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PsGetCurrentThread(), RtlCopyMemory, RtlZeroMemory, STATUS_SERVICE_NOTIFICATION, STATUS_UNHANDLED_EXCEPTION, STATUS_VDM_HARD_ERROR, _IOP_HARD_ERROR_PACKET::String, _IOP_HARD_ERROR_QUEUE::ThreadStarted, TRUE, VOID, _IOP_HARD_ERROR_QUEUE::WorkQueue, _IOP_HARD_ERROR_PACKET::WorkQueueLinks, _IOP_HARD_ERROR_QUEUE::WorkQueueSemaphore, and _IOP_HARD_ERROR_QUEUE::WorkQueueSpinLock.
Referenced by CcWriteBehind(), MiCauseOverCommitPopup(), MiLdwPopupWorker(), and WmipGenerateMCAEventlog().
NTKERNELAPI NTSTATUS IoReadDiskSignature (IN PDEVICE_OBJECT DeviceObject, IN ULONG BytesPerSector, OUT PDISK_SIGNATURE Signature)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS FASTCALL IoReadPartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN BOOLEAN ReturnRecognizedPartitions, OUT struct _DRIVE_LAYOUT_INFORMATION ** PartitionBuffer)
Definition at line 2136 of file drivesup.c.
References _PARTITION_DESCRIPTOR::ActiveFlag, BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, _PARTITION_INFORMATION::BootIndicator, _DISK_GEOMETRY::BytesPerSector, DPFLTR_ERROR_LEVEL, DPFLTR_FSTUB_ID, DPFLTR_TRACE_LEVEL, DPFLTR_WARNING_LEVEL, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, FstubDbgPrintDriveLayout, FstubFixupEfiPartition(), GET_PARTITION_LENGTH, GET_STARTING_SECTOR, HalExamineMBR(), HalpGetFullGeometry(), HalpIsValidPartitionEntry(), _PARTITION_INFORMATION::HiddenSectors, _LARGE_INTEGER::HighPart, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, IsContainerPartition, _BOOT_SECTOR_INFO::JumpByte, KdPrintEx, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, _DISK_GEOMETRY::MediaType, NonPagedPool, NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, NUM_PARTITION_TABLE_ENTRIES, PAGED_CODE, PARTITION_ACTIVE_FLAG, PARTITION_BUFFER_SIZE, PARTITION_ENTRY_UNUSED, PARTITION_FAT_16, PARTITION_TABLE_OFFSET, _PARTITION_INFORMATION::PartitionLength, _PARTITION_DESCRIPTOR::PartitionType, _PARTITION_INFORMATION::PartitionType, PIRP, _LARGE_INTEGER::QuadPart, _PARTITION_INFORMATION::RecognizedPartition, RemovableMedia, _PARTITION_INFORMATION::RewritePartition, RtlCopyMemory, RtlZeroMemory, SL_OVERRIDE_VERIFY_VOLUME, _PARTITION_INFORMATION::StartingOffset, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_DATA_DETECTED, STATUS_PENDING, STATUS_SUCCESS, TRUE, UInt32x32To64, and VOID.
NTKERNELAPI NTSTATUS IoReadPartitionTableEx (IN PDEVICE_OBJECT DeviceObject, IN struct _DRIVE_LAYOUT_INFORMATION_EX ** DriveLayout)
Referenced by IoGetBootDiskInformation(), and IopCreateArcNamesDisk().
NTKERNELAPI VOID IoRegisterBootDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
Definition at line 9906 of file iosubs.c.
References _REINIT_PACKET::Context, _REINIT_PACKET::DriverObject, _REINIT_PACKET::DriverReinitializationRoutine, DRVO_BOOTREINIT_REGISTERED, ExAllocatePoolWithTag, IopBootDriverReinitializeQueueHead, IopInterlockedInsertTailList(), _REINIT_PACKET::ListEntry, NonPagedPool, and PAGED_CODE.
NTKERNELAPI VOID IoRegisterDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
Definition at line 9967 of file iosubs.c.
References _REINIT_PACKET::Context, _REINIT_PACKET::DriverObject, _REINIT_PACKET::DriverReinitializationRoutine, DRVO_REINIT_REGISTERED, ExAllocatePoolWithTag, IopDriverReinitializeQueueHead, IopInterlockedInsertTailList(), _REINIT_PACKET::ListEntry, NonPagedPool, and PAGED_CODE.
NTKERNELAPI VOID IoRegisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
Definition at line 10028 of file iosubs.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, DO_DEVICE_INITIALIZING, DO_LOW_PRIORITY_FILESYSTEM, DRVO_BASE_FILESYSTEM_DRIVER, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, _LIST_ENTRY::Flink, InsertHeadList(), InsertTailList(), IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopFsNotifyChangeQueueHead, IopFsRegistrationOps, IopInterlockedIncrementUlong(), IopNetworkFileSystemQueueHead, IopTapeFileSystemQueueHead, LockQueueIoDatabaseLock, _NOTIFICATION_PACKET::NotificationRoutine, NULL, PAGED_CODE, TRUE, and VOID.
Referenced by RawInitialize().
NTKERNELAPI NTSTATUS IoRegisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
Definition at line 10176 of file iosubs.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _NOTIFICATION_PACKET::DriverObject, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExReleaseResourceLite(), InsertTailList(), IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopFsNotifyChangeQueueHead, IopNetworkFileSystemQueueHead, IopNotifyAlreadyRegisteredFileSystems(), IopTapeFileSystemQueueHead, IsListEmpty, _NOTIFICATION_PACKET::ListEntry, _NOTIFICATION_PACKET::NotificationRoutine, ObReferenceObject, PAGED_CODE, PagedPool, POOL_COLD_ALLOCATION, STATUS_DEVICE_ALREADY_ATTACHED, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
NTKERNELAPI NTSTATUS IoRegisterLastChanceShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10278 of file iosubs.c.
References _SHUTDOWN_PACKET::DeviceObject, DO_SHUTDOWN_REGISTERED, ExAllocatePoolWithTag, IopInterlockedInsertHeadList(), IopNotifyLastChanceShutdownQueueHead, _SHUTDOWN_PACKET::ListEntry, NonPagedPool, ObReferenceObject, PAGED_CODE, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS IoRegisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10341 of file iosubs.c.
References _SHUTDOWN_PACKET::DeviceObject, DO_SHUTDOWN_REGISTERED, ExAllocatePoolWithTag, IopInterlockedInsertHeadList(), IopNotifyShutdownQueueHead, _SHUTDOWN_PACKET::ListEntry, NonPagedPool, ObReferenceObject, PAGED_CODE, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by RawInitialize(), and WmipDriverEntry().
NTKERNELAPI VOID IoReleaseCancelSpinLock (IN KIRQL Irql)
Definition at line 10404 of file iosubs.c.
References KeReleaseQueuedSpinLock(), and LockQueueIoCancelLock.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCancelExclusiveIrp(), FsRtlCancelNotify(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlNotifySetCancelRoutine(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeFileLock(), FsRtlUninitializeOplock(), FsRtlWaitOnIrp(), IoCancelIrp(), IopCsqCancelRoutine(), IopStartNextPacket(), IopStartNextPacketByKey(), IoStartPacket(), and WmipNotificationIrpCancel().
NTKERNELAPI VOID NTAPI IoReleaseRemoveLockAndWaitEx (IN PIO_REMOVE_LOCK RemoveLock, IN PVOID Tag, IN ULONG RemlockSize)
NTKERNELAPI VOID NTAPI IoReleaseRemoveLockEx (IN PIO_REMOVE_LOCK RemoveLock, IN PVOID Tag, IN ULONG RemlockSize)
NTKERNELAPI VOID IoReleaseVpbSpinLock (IN KIRQL Irql)
Definition at line 10435 of file iosubs.c.
References KeReleaseQueuedSpinLock(), and LockQueueIoVpbLock.
Referenced by IoGetDiskDeviceObject(), IopMountInitializeVpb(), IopReferenceVerifyVpb(), RawCheckForDismount(), and RawVerifyVolume().
NTKERNELAPI VOID IoRemoveShareAccess (IN PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
Definition at line 10466 of file iosubs.c.
References _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, and PAGED_CODE.
Referenced by RawCleanup().
NTKERNELAPI NTSTATUS IoReportHalResourceUsage (IN PUNICODE_STRING HalName, IN PCM_RESOURCE_LIST RawResourceList, IN PCM_RESOURCE_LIST TranslatedResourceList, IN ULONG ResourceListSize)
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS IoReportResourceUsage (IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PCM_RESOURCE_LIST DriverList OPTIONAL, IN ULONG DriverListSize OPTIONAL, IN PDEVICE_OBJECT DeviceObject, IN PCM_RESOURCE_LIST DeviceList OPTIONAL, IN ULONG DeviceListSize OPTIONAL, IN BOOLEAN OverrideConflict, OUT PBOOLEAN ConflictDetected)
VOID IoRetryIrpCompletions (VOID)
Definition at line 13734 of file iosubs.c.
References APC_LEVEL, ASSERT, CONTAINING_RECORD, _LIST_ENTRY::Flink, IopCompleteRequest(), IRP, IRP_CREATE_OPERATION, IRP_RETRY_IO_COMPLETION, _ETHREAD::IrpList, KeLowerIrql, KeRaiseIrql, NULL, PIRP, and PsGetCurrentThread().
Referenced by MmAccessFault(), MmCopyToCachedPage(), and MmPrefetchPagesIntoLockedMdl().
NTKERNELAPI VOID IoReuseIrp (IN OUT PIRP Irp, IN NTSTATUS Iostatus)
NTKERNELAPI NTSTATUS IoSetCompletionRoutineEx (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PIO_COMPLETION_ROUTINE CompletionRoutine, IN PVOID Context, IN BOOLEAN InvokeOnSuccess, IN BOOLEAN InvokeOnError, IN BOOLEAN InvokeOnCancel)
Definition at line 13954 of file iosubs.c.
References _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::CompletionRoutine, _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::Context, _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::DeviceObject, ExAllocatePoolWithTag, IopUnloadSafeCompletion(), IoSetCompletionRoutine, NonPagedPool, NULL, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
NTKERNELAPI VOID IoSetDeviceToVerify (IN PETHREAD Thread, IN PDEVICE_OBJECT DeviceObject)
Definition at line 10560 of file iosubs.c.
NTKERNELAPI NTSTATUS IoSetFileOrigin (IN PFILE_OBJECT FileObject, IN BOOLEAN Remote)
Definition at line 14626 of file iosubs.c.
References FO_REMOTE_ORIGIN, Status, STATUS_INVALID_PARAMETER_MIX, and STATUS_SUCCESS.
NTKERNELAPI VOID IoSetHardErrorOrVerifyDevice (IN PIRP Irp, IN PDEVICE_OBJECT DeviceObject)
Definition at line 10599 of file iosubs.c.
NTKERNELAPI NTSTATUS IoSetInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN PVOID FileInformation)
Definition at line 10650 of file iosubs.c.
References Executive, FALSE, FILE_SEQUENTIAL_ONLY, FILE_SYNCHRONOUS_IO_ALERT, FILE_WRITE_THROUGH, FileLinkInformation, FileModeInformation, FileMoveClusterInformation, _FILE_RENAME_INFORMATION::FileName, _IO_STACK_LOCATION::FileObject, FileRenameInformation, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_NO_INTERMEDIATE_BUFFERING, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, IoAllocateIrp(), IoCallDriver(), IoCompleteRequest(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopOpenLinkOrRenameTarget(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IoSetNextIrpStackLocation, IRP_BUFFERED_IO, IRP_MJ_SET_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _FILE_MODE_INFORMATION::Mode, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_NAME_PATH_SEPARATOR, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, SynchronizationEvent, TRUE, and VOID.
Referenced by MiAttemptPageFileExtension(), and MiAttemptPageFileReduction().
NTKERNELAPI NTSTATUS IoSetIoCompletion (IN PVOID IoCompletion, IN PVOID KeyContext, IN PVOID ApcContext, IN NTSTATUS IoStatus, IN ULONG_PTR IoStatusInformation, IN BOOLEAN Quota)
Definition at line 665 of file complete.c.
References _IOP_MINI_COMPLETION_PACKET::ApcContext, ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InterlockedPopEntrySList(), IopCompletionPacketMini, IopCompletionPacketQuota, _IOP_MINI_COMPLETION_PACKET::IoStatus, _IOP_MINI_COMPLETION_PACKET::IoStatusInformation, KeGetCurrentPrcb(), KeInsertQueue(), _IOP_MINI_COMPLETION_PACKET::KeyContext, _PP_LOOKASIDE_LIST::L, _IOP_MINI_COMPLETION_PACKET::ListEntry, LookasideCompletionList, LowPoolPriority, NonPagedPool, NOTHING, NULL, _PP_LOOKASIDE_LIST::P, _IOP_MINI_COMPLETION_PACKET::PacketType, PAGED_CODE, _KPRCB::PPLookasideList, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _GENERAL_LOOKASIDE::TotalAllocates.
Referenced by IopXxxControlFile(), NtLockFile(), NtSetInformationJobObject(), NtSetIoCompletion(), PsChangeJobMemoryUsage(), PsEnforceExecutionTimeLimits(), PspAddProcessToJob(), PspCreateThread(), PspExitProcess(), PspFoldProcessAccountingIntoJob(), and PsReportProcessMemoryLimitViolation().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS FASTCALL IoSetPartitionInformation (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG PartitionNumber, IN ULONG PartitionType)
Definition at line 2911 of file drivesup.c.
References BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, GET_STARTING_SECTOR, HalExamineMBR(), IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, IRP_MJ_WRITE, IsContainerPartition, KeInitializeEvent(), KeResetEvent(), KernelMode, KeWaitForSingleObject(), NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, NUM_PARTITION_TABLE_ENTRIES, PAGE_SIZE, PAGED_CODE, PARTITION_ENTRY_UNUSED, PARTITION_TABLE_OFFSET, _PARTITION_DESCRIPTOR::PartitionType, PIRP, _LARGE_INTEGER::QuadPart, SL_OVERRIDE_VERIFY_VOLUME, _IO_STATUS_BLOCK::Status, STATUS_BAD_MASTER_BOOT_RECORD, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, TRUE, UInt32x32To64, and VOID.
NTKERNELAPI NTSTATUS IoSetPartitionInformationEx (IN PDEVICE_OBJECT DeviceObject, IN ULONG PartitionNumber, IN struct _SET_PARTITION_INFORMATION_EX * PartitionInfo)
NTKERNELAPI VOID IoSetShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, OUT PSHARE_ACCESS ShareAccess)
Definition at line 10990 of file iosubs.c.
References DELETE, FALSE, FILE_APPEND_DATA, FILE_EXECUTE, FILE_READ_DATA, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_DATA, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, PAGED_CODE, and TRUE.
Referenced by RawCreate().
VOID IoSetStartIoAttributes (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN DeferredStartIo, IN BOOLEAN NonCancelable)
Definition at line 11934 of file iosubs.c.
References DOE_STARTIO_DEFERRED, and DOE_STARTIO_NO_CANCEL.
NTKERNELAPI NTSTATUS IoSetSystemPartition (PUNICODE_STRING VolumeNameString)
Definition at line 14467 of file iosubs.c.
References ASSERT, _UNICODE_STRING::Buffer, IopCreateRegistryKeyEx(), IopOpenRegistryKeyEx(), KEY_ALL_ACCESS, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NULL, REG_OPTION_NON_VOLATILE, REG_SZ, RtlInitUnicodeString(), TITLE_INDEX_VALUE, and ZwSetValueKey().
NTKERNELAPI BOOLEAN IoSetThreadHardErrorMode (IN BOOLEAN EnableHardErrors)
Definition at line 11123 of file iosubs.c.
References _ETHREAD::CrossThreadFlags, FALSE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PS_SET_BITS, PsGetCurrentThread(), and TRUE.
Referenced by CmpCmdHiveClose(), CmpDoFileSetSize(), FsRtlGetFileSize(), FsRtlSetFileSize(), HvSyncHive(), and ObKillProcess().
NTKERNELAPI VOID IoSetTopLevelIrp (IN PIRP Irp)
Definition at line 11174 of file iosubs.c.
References PsGetCurrentThread(), and _ETHREAD::TopLevelIrp.
Referenced by FsRtlCreateSectionForDataScan(), MiRemoveUnusedSegments(), and MmCreateSection().
NTSTATUS IoShutdownPnpDevices (VOID)
Referenced by IoShutdownSystem().
NTKERNELAPI VOID IoShutdownSystem (IN ULONG Phase)
Definition at line 11212 of file iosubs.c.
References CONTAINING_RECORD, DbgPrint(), _SHUTDOWN_PACKET::DeviceObject, ExAcquireResourceExclusiveLite(), Executive, ExFreePool(), IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetAttachedDeviceReference(), IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopInterlockedRemoveHeadList(), IopLinkTrackingServiceEventHandle, IopNotifyLastChanceShutdownQueueHead, IopNotifyShutdownQueueHead, IopShutdownBaseFileSystems(), IopTapeFileSystemQueueHead, IoShutdownPnpDevices(), IOV_UNLOAD_DRIVERS, IRP_MJ_SHUTDOWN, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NULL, ObDereferenceObject(), PAGED_CODE, PIRP, STATUS_PENDING, TRUE, VOID, and ZwClose().
NTKERNELAPI VOID IoStartNextPacket (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable)
Definition at line 11870 of file iosubs.c.
References DOE_STARTIO_CANCELABLE, DOE_STARTIO_DEFERRED, DOE_STARTIO_REQUESTED, IopStartNextPacket(), and IopStartNextPacketByKeyEx().
NTKERNELAPI VOID IoStartNextPacketByKey (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable, IN ULONG Key)
Definition at line 11900 of file iosubs.c.
References DOE_STARTIO_CANCELABLE, DOE_STARTIO_DEFERRED, DOE_STARTIO_REQUESTED_BYKEY, IopStartNextPacketByKey(), and IopStartNextPacketByKeyEx().
NTKERNELAPI VOID IoStartPacket (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PULONG Key OPTIONAL, IN PDRIVER_CANCEL CancelFunction OPTIONAL)
Definition at line 11674 of file iosubs.c.
References DISPATCH_LEVEL, DOE_STARTIO_NO_CANCEL, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), KeInsertByKeyDeviceQueue(), KeInsertDeviceQueue(), KeLowerIrql, KeRaiseIrql, NULL, and PASSIVE_LEVEL.
NTKERNELAPI VOID IoStartTimer (IN PDEVICE_OBJECT DeviceObject)
Definition at line 11972 of file iosubs.c.
References DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_UNLOAD_PENDING, ExAcquireFastLock, ExReleaseFastLock, IopTimerCount, IopTimerLock, _IO_TIMER::TimerFlag, TRUE, and UNREFERENCED_PARAMETER.
NTKERNELAPI VOID IoStopTimer (IN PDEVICE_OBJECT DeviceObject)
Definition at line 12029 of file iosubs.c.
References ExAcquireFastLock, ExReleaseFastLock, FALSE, IopTimerCount, IopTimerLock, _IO_TIMER::TimerFlag, and UNREFERENCED_PARAMETER.
NTKERNELAPI NTSTATUS IoSynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 12074 of file iosubs.c.
References CcDataFlushes, CcDataPages, CcIsFileCached, _IO_STACK_LOCATION::FileObject, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_WRITE, IRP_NOCACHE, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KernelMode, _IO_STACK_LOCATION::MajorFunction, PAGE_SHIFT, PAGE_SIZE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and STATUS_INSUFFICIENT_RESOURCES.
Referenced by CcZeroData(), MiCleanSection(), MiFlushSectionInternal(), MiShutdownSystem(), MiZeroPageFile(), and MiZeroPageFileFirstPage().
NTKERNELAPI PEPROCESS IoThreadToProcess (IN PETHREAD Thread)
Definition at line 12188 of file iosubs.c.
References THREAD_TO_PROCESS.
BOOLEAN IoTranslateBusAddress (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
VOID IoTraverseDeviceTree (IN BOOLEAN Inverted, IN LONG CurrentLevel, IN PIO_TRAVERSE_WORKER WorkerFunction, IN PIO_LEVEL_END_WORKER LevelEndFunction, IN PVOID Context)
NTKERNELAPI VOID IoUnregisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
Definition at line 12223 of file iosubs.c.
References CONTAINING_RECORD, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, IopDatabaseResource, IopFsNotifyChangeQueueHead, IopFsRegistrationOps, IopInterlockedDecrementUlong(), LockQueueIoDatabaseLock, _NOTIFICATION_PACKET::NotificationRoutine, NULL, PAGED_CODE, RemoveEntryList(), TRUE, and VOID.
Referenced by RawShutdown().
NTKERNELAPI VOID IoUnregisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
Definition at line 12297 of file iosubs.c.
References CONTAINING_RECORD, _NOTIFICATION_PACKET::DriverObject, ExAcquireResourceExclusiveLite(), ExFreePool(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, IopDatabaseResource, IopFsNotifyChangeQueueHead, _NOTIFICATION_PACKET::NotificationRoutine, ObDereferenceObject(), PAGED_CODE, RemoveEntryList(), and TRUE.
NTKERNELAPI VOID IoUnregisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
Definition at line 12358 of file iosubs.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _SHUTDOWN_PACKET::DeviceObject, DO_SHUTDOWN_REGISTERED, ExFreePool(), ExPageLockHandle, _LIST_ENTRY::Flink, IopNotifyLastChanceShutdownQueueHead, IopNotifyShutdownQueueHead, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), ObDereferenceObject(), PAGED_CODE, and RemoveEntryList().
Referenced by IoDeleteDevice().
NTKERNELAPI NTSTATUS IoUpdateDiskGeometry (IN PDEVICE_OBJECT DeviceObject, IN struct _DISK_GEOMETRY_EX * OldDiskGeometry, IN struct _DISK_GEOMETRY_EX * NewDiskGeometry)
NTKERNELAPI VOID IoUpdateShareAccess (IN PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
NTKERNELAPI NTSTATUS IoValidateDeviceIoControlAccess (IN PIRP Irp, IN ULONG RequiredAccess)
Definition at line 14772 of file iosubs.c.
References FILE_READ_ACCESS, FILE_READ_DATA, FILE_WRITE_ACCESS, FILE_WRITE_DATA, _IO_STACK_LOCATION::Flags, IoGetCurrentIrpStackLocation, IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, KernelMode, _IO_STACK_LOCATION::MajorFunction, SeComputeGrantedAccesses, SL_READ_ACCESS_GRANTED, SL_WRITE_ACCESS_GRANTED, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
PIRP IovAllocateIrp (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
PIRP IovBuildAsynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PIO_STATUS_BLOCK IoStatusBlock OPTIONAL)
PIRP IovBuildDeviceIoControlRequest (IN ULONG IoControlCode, IN PDEVICE_OBJECT DeviceObject, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN InternalDeviceIoControl, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS FASTCALL IovCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp, IN PVOID ReturnAddress)
VOID FASTCALL IovCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
VOID IoVerifierInit (IN ULONG VerifierFlags)
NTKERNELAPI NTSTATUS IoVerifyPartitionTable (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN FixErrors)
NTKERNELAPI NTSTATUS IoVerifyVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount)
Definition at line 12532 of file iosubs.c.
References ASSERT, DO_VERIFY_VOLUME, Executive, FALSE, _IO_STACK_LOCATION::Flags, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IopCreateVpb(), IopDereferenceVpbAndFree(), IopInterlockedDecrementUlong(), IopMountVolume(), IopReferenceVerifyVpb(), IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_VERIFY_VOLUME, IRP_MOUNT_COMPLETION, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LockQueueIoVpbLock, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PoVolumeDevice(), PsGetCurrentThread(), _VPB::ReferenceCount, SL_ALLOW_RAW_MOUNT, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WRONG_VOLUME, TRUE, and VOID.
VOID IovFreeIrp (IN PIRP Irp)
NTSTATUS IovInitializeTimer (IN PDEVICE_OBJECT DeviceObject, IN PIO_TIMER_ROUTINE TimerRoutine, IN PVOID Context)
NTSTATUS IoVolumeDeviceToDosName (IN PVOID VolumeDeviceObject, OUT PUNICODE_STRING DosName)
Definition at line 40 of file dev2dos.c.
References ASSERT, ExAllocatePool, Executive, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_MOUNTDEV_QUERY_DEVICE_NAME, IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH, IoGetDeviceObjectPointer(), KeGetCurrentIrql(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), MAXUSHORT, MOUNTMGR_DEVICE_NAME, _MOUNTMGR_VOLUME_PATHS::MultiSz, _MOUNTMGR_VOLUME_PATHS::MultiSzLength, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PagedPool, PASSIVE_LEVEL, PIRP, RtlCopyMemory, RtlInitUnicodeString(), _IO_STATUS_BLOCK::Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_BUFFER_SIZE, STATUS_PENDING, and STATUS_SUCCESS.
Referenced by IopQueryNameInternal().
NTKERNELAPI NTSTATUS IoWMIAllocateInstanceIds (__in GUID * Guid, __in ULONG InstanceCount, __out ULONG * FirstInstanceId)
Definition at line 261 of file api.c.
References INSTID::BaseId, ExAllocatePoolWithTag, INSTID::Guid, tagINSTIDCHUNK::InstId, INSTIDSPERCHUNK, IsEqualGUID, tagINSTIDCHUNK::Next, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlFillMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, WMIIIPOOLTAG, WmipEnterSMCritSection, WmipInstIdChunkHead, WmipIsWmiNotSetupProperly, and WmipLeaveSMCritSection.
NTKERNELAPI NTSTATUS IoWMIDeviceObjectToInstanceName (__in PVOID DataBlockObject, __in PDEVICE_OBJECT DeviceObject, __out PUNICODE_STRING InstanceName)
Definition at line 1495 of file api.c.
References NULL, PAGED_CODE, Status, and WmipTranslateFileHandle().
NTKERNELAPI NTSTATUS IoWMIExecuteMethod (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG MethodId, __in ULONG InBufferSize, __inout PULONG OutBufferSize, __inout_bcount_part_opt *, InBufferSize PUCHAR InOutBuffer)
Definition at line 1340 of file api.c.
References tagWNODE_METHOD_ITEM::DataBlockOffset, FIELD_OFFSET, _WNODE_HEADER::Flags, IRP_MN_EXECUTE_METHOD, KernelMode, tagWNODE_METHOD_ITEM::MethodId, NT_SUCCESS, NULL, tagWNODE_METHOD_ITEM::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, tagWNODE_METHOD_ITEM::SizeDataBlock, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_METHOD_ITEM, and WNODE_FLAG_TOO_SMALL.
NTKERNELAPI NTSTATUS IoWMIHandleToInstanceName (__in PVOID DataBlockObject, __in HANDLE FileHandle, __out PUNICODE_STRING InstanceName)
Definition at line 1476 of file api.c.
References NULL, PAGED_CODE, Status, and WmipTranslateFileHandle().
NTKERNELAPI NTSTATUS IoWMIOpenBlock (__in GUID * DataBlockGuid, __in ULONG DesiredAccess, __out PVOID * DataBlockObject)
Definition at line 758 of file api.c.
References _OBJECT_ATTRIBUTES::Attributes, Ioctl, IOCTL_WMI_OPEN_GUID, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, KernelMode, _OBJECT_ATTRIBUTES::Length, NT_SUCCESS, NULL, OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObReferenceObjectByHandle, PAGED_CODE, RtlInitUnicodeString(), RtlZeroMemory, Status, StringCchCopyW(), StringCchPrintfW(), WmiGuidObjectDirectory, WmiGuidObjectDirectoryLength, WmiGuidObjectNameLength, WmipGuidObjectType, WmipOpenBlock(), WRITE_DAC, and ZwClose().
NTKERNELAPI NTSTATUS IoWMIQueryAllData (__in PVOID DataBlockObject, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 833 of file api.c.
References _WNODE_HEADER::Flags, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_NOT_SUPPORTED, WmipBuildWnodeHeader, WmipQueryAllData(), WNODE_FLAG_ALL_DATA, WNODE_FLAG_INTERNAL, WNODE_FLAG_TOO_SMALL, and tagWNODE_ALL_DATA::WnodeHeader.
NTKERNELAPI NTSTATUS IoWMIQueryAllDataMultiple (__in_ecount(ObjectCount) PVOID * DataBlockObjectList, __in ULONG ObjectCount, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 913 of file api.c.
References ARGUMENT_PRESENT, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, WmipQueryAllDataMultiple(), and WNODE_FLAG_TOO_SMALL.
NTKERNELAPI NTSTATUS IoWMIQuerySingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 992 of file api.c.
References tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FIELD_OFFSET, _WNODE_HEADER::Flags, IRP_MN_QUERY_SINGLE_INSTANCE, KernelMode, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_SUPPORTED, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_INTERNAL, WNODE_FLAG_SINGLE_INSTANCE, and WNODE_FLAG_TOO_SMALL.
NTKERNELAPI NTSTATUS IoWMIQuerySingleInstanceMultiple (__in_ecount(ObjectCount) PVOID * DataBlockObjectList, __in_ecount(ObjectCount) PUNICODE_STRING InstanceNames, __in ULONG ObjectCount, __inout ULONG * InOutBufferSize, __out_bcount_opt *InOutBufferSize PVOID OutBuffer)
Definition at line 1106 of file api.c.
References ARGUMENT_PRESENT, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, WmipQuerySingleMultiple(), and WNODE_FLAG_TOO_SMALL.
NTKERNELAPI NTSTATUS IoWMIRegistrationControl (__in PDEVICE_OBJECT DeviceObject, __in ULONG Action)
Definition at line 121 of file api.c.
References FALSE, _REGENTRY::Flags, NT_SUCCESS, NULL, PAGED_CODE, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, WmipDeregisterDevice(), WmipEnterSMCritSection, WmipFindRegEntryByDevice(), WmipIsWmiNotSetupProperly, WmipLeaveSMCritSection, WmipRegisterDevice(), WmipSetTraceNotify(), WmipUnreferenceRegEntry, WmipUpdateRegistration(), WMIREG_ACTION_BLOCK_IRPS, WMIREG_ACTION_DEREGISTER, WMIREG_ACTION_REGISTER, WMIREG_ACTION_REREGISTER, WMIREG_ACTION_UPDATE_GUIDS, WMIREG_FLAG_CALLBACK, WMIREG_FLAG_TRACE_NOTIFY_MASK, and WMIREG_FLAG_TRACE_PROVIDER.
Referenced by WmipDriverEntry().
NTKERNELAPI NTSTATUS IoWMISetNotificationCallback (__in PVOID Object, __in WMI_NOTIFICATION_CALLBACK Callback, __in_opt PVOID Context)
NTKERNELAPI NTSTATUS IoWMISetSingleInstance (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
Definition at line 1187 of file api.c.
References tagWNODE_SINGLE_INSTANCE::DataBlockOffset, FIELD_OFFSET, IRP_MN_CHANGE_SINGLE_INSTANCE, KernelMode, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, Status, STATUS_INSUFFICIENT_RESOURCES, _WNODE_HEADER::Version, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
NTKERNELAPI NTSTATUS IoWMISetSingleItem (__in PVOID DataBlockObject, __in PUNICODE_STRING InstanceName, __in ULONG DataItemId, __in ULONG Version, __in ULONG ValueBufferSize, __in_bcount(ValueBufferSize) PVOID ValueBuffer)
Definition at line 1263 of file api.c.
References tagWNODE_SINGLE_ITEM::DataBlockOffset, FIELD_OFFSET, IRP_MN_CHANGE_SINGLE_ITEM, tagWNODE_SINGLE_ITEM::ItemId, KernelMode, NULL, tagWNODE_SINGLE_ITEM::OffsetInstanceName, OffsetToPtr, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, tagWNODE_SINGLE_ITEM::SizeDataItem, Status, STATUS_INSUFFICIENT_RESOURCES, _WNODE_HEADER::Version, WmipAllocNP, WmipBuildWnodeHeader, WmipFree, WmipQuerySetExecuteSI(), WNODE_FLAG_SINGLE_ITEM, and tagWNODE_SINGLE_ITEM::WnodeHeader.
NTKERNELAPI NTSTATUS IoWMISuggestInstanceName (__in_opt PDEVICE_OBJECT PhysicalDeviceObject, __in_opt PUNICODE_STRING SymbolicLinkName, __in BOOLEAN CombineNames, __out PUNICODE_STRING SuggestedInstanceName)
Definition at line 362 of file api.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DevicePropertyDeviceDescription, ExAllocatePoolWithTag, ExFreePool(), IoGetDeviceProperty(), IoOpenDeviceInterfaceRegistryKey(), KEY_ALL_ACCESS, KeyValueFullInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlAppendUnicodeToString(), Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_MIX, STATUS_UNSUCCESSFUL, WmipIsWmiNotSetupProperly, WMIPOOLTAG, ZwClose(), and ZwQueryValueKey().
NTKERNELAPI NTSTATUS IoWMIWriteEvent (__in PVOID WnodeEventItem)
Referenced by WmipCheckIsWbemRunning(), WmipFireOffWmiEvent(), WmipQueryLogAndFireEvent(), and WmipWriteMCAEventLogEvent().
NTKERNELAPI BOOLEAN IoWriteCrashDump (IN ULONG BugCheckCode, IN ULONG_PTR BugCheckParameter1, IN ULONG_PTR BugCheckParameter2, IN ULONG_PTR BugCheckParameter3, IN ULONG_PTR BugCheckParameter4, IN PVOID ContextSave, IN PKTHREAD Thread, OUT PBOOLEAN Reboot)
Referenced by KeBugCheck2().
NTKERNELAPI VOID IoWriteErrorLogEntry (IN PVOID ElEntry)
Referenced by CcLogError(), CmpLogError(), IopDisassociateThreadIrp(), IopLogErrorEvent(), MmCleanProcessAddressSpace(), MmLoadSystemImage(), Phase1InitializationDiscard(), and WmipWriteToEventlog().
DECLSPEC_DEPRECATED_DDK NTKERNELAPI NTSTATUS FASTCALL IoWritePartitionTable (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG SectorsPerTrack, IN ULONG NumberOfHeads, IN struct _DRIVE_LAYOUT_INFORMATION * PartitionBuffer)
Definition at line 3305 of file drivesup.c.
References BOOT_RECORD_SIGNATURE, BOOT_SIGNATURE_OFFSET, _PARTITION_INFORMATION::BootIndicator, ExAllocatePoolWithTag, Executive, ExFreePool(), FALSE, _IO_STACK_LOCATION::Flags, FstubDbgPrintDriveLayout, HalExamineMBR(), HalpCalculateChsValues(), _PARTITION_INFORMATION::HiddenSectors, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_READ, IRP_MJ_WRITE, IsContainerPartition, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, NonPagedPoolCacheAligned, NotificationEvent, NT_SUCCESS, NULL, NUM_PARTITION_TABLE_ENTRIES, PAGE_SIZE, PAGED_CODE, PARTITION_ACTIVE_FLAG, PARTITION_ENTRY_UNUSED, PARTITION_FAT_16, PARTITION_TABLE_OFFSET, _PARTITION_TABLE::PartitionEntry, _PARTITION_INFORMATION::PartitionLength, _PARTITION_INFORMATION::PartitionNumber, _DISK_LAYOUT::PartitionTable, _PARTITION_INFORMATION::PartitionType, PIRP, _LARGE_INTEGER::QuadPart, _PARTITION_INFORMATION::RewritePartition, SL_OVERRIDE_VERIFY_VOLUME, _PARTITION_INFORMATION::StartingOffset, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_SUCCESS, _DISK_LAYOUT::TableCount, TRUE, VOID, WHICH_BIT, and xHalGetPartialGeometry().
NTKERNELAPI NTSTATUS IoWritePartitionTableEx (IN PDEVICE_OBJECT DeviceObject, IN struct _DRIVE_LAYOUT_INFORMATION_EX * DriveLayout)
BOOLEAN WMIInitialize (ULONG Phase, PVOID LoaderBlock)
Definition at line 57 of file api.c.
References FALSE, IoCreateDriver(), NT_SUCCESS, NULL, RtlInitUnicodeString(), Status, STATUS_SUCCESS, TRUE, UNREFERENCED_PARAMETER, WMIDRIVERNAME, WmipAssert, WmipDriverEntry(), WmipInitializeRegistration(), WmipRegisterFirmwareProviders(), WmipRegisterMcaHandler(), and WmipServiceDeviceObject.
Referenced by IoInitSystem().
Variable Documentation
DEVICE_OBJECT
Definition at line 1434 of file io.h.
Referenced by IoCreateDevice(), IoFreeController(), IopCreateObjectTypes(), IopInvalidateVolumesForDevice(), IopMountVolume(), IopNotifyAlreadyRegisteredFileSystems(), IopShutdownBaseFileSystems(), RawDispatch(), and RawMountVolume().
ULONG IoOtherOperationCount
Definition at line 257 of file iodata.c.
Referenced by IopUpdateOtherOperationCount(), and NtQuerySystemInformation().
LARGE_INTEGER IoOtherTransferCount
Definition at line 260 of file iodata.c.
Referenced by IopUpdateOtherTransferCount(), and NtQuerySystemInformation().
ULONG IoReadOperationCount
Definition at line 255 of file iodata.c.
Referenced by IopUpdateReadOperationCount(), and NtQuerySystemInformation().
LARGE_INTEGER IoReadTransferCount
Definition at line 258 of file iodata.c.
Referenced by IopUpdateReadTransferCount(), and NtQuerySystemInformation().
BOOLEAN IoRemoteBootClient
Definition at line 292 of file iodata.c.
Referenced by ExpInitializeExecutive(), ExpWorkerThread(), IoAssignDriveLetters(), IoInitSystem(), IopCreateArcNames(), MiEnablePagingTheExecutive(), and ObpProcessDosDeviceSymbolicLink().
KSPIN_LOCK IoStatisticsLock
Definition at line 56 of file hifreqlk.c.
Referenced by IoInitSystem().
ULONG IoWriteOperationCount
Definition at line 256 of file iodata.c.
Referenced by IopUpdateWriteOperationCount(), and NtQuerySystemInformation().
LARGE_INTEGER IoWriteTransferCount
Definition at line 259 of file iodata.c.
Referenced by IopUpdateWriteTransferCount(), and NtQuerySystemInformation().
IRP
Definition at line 2090 of file io.h.
Referenced by FsRtlCancelNotify(), FsRtlCancelOplockIIIrp(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyFilterReportChange(), FsRtlOplockCleanup(), FsRtlRemoveAndCompleteIrp(), FsRtlUninitializeOplock(), IoCancelThreadIo(), IoFindDeviceThatFailedIrp(), IoInitializeIrp(), IoInitSystem(), IopCompletePageWrite(), IopCompleteRequest(), IopDeleteIoCompletion(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopStartNextPacket(), IopStartNextPacketByKey(), IopUserCompletion(), IopUserRundown(), IoRetryIrpCompletions(), NtCancelIoFile(), and NtRemoveIoCompletion().
* PIRP
Definition at line 2090 of file io.h.
Referenced by BuildQueryDirectoryIrp(), CcSetValidData(), FsRtlBalanceReads(), FsRtlCancelNotify(), FsRtlCancelOplockIIIrp(), FsRtlCreateSectionForDataScan(), FsRtlGetFileSize(), FsRtlNotifyCompleteIrpList(), FsRtlNotifyFilterReportChange(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlSetFileSize(), FsRtlUninitializeFileLock(), FsRtlUninitializeOplock(), HalExamineMBR(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoAsynchronousPageWrite(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoBuildSynchronousFsdRequest(), IoCancelFileOpen(), IoCancelThreadIo(), IoCsqRemoveIrp(), IoCsqRemoveNextIrp(), IoGetBootDiskInformation(), IoGetTopLevelIrp(), IoMakeAssociatedIrp(), IoPageRead(), IopAllocateIrpMustSucceed(), IopAllocateIrpPrivate(), IopCloseFile(), IopCompletePageWrite(), IopCompleteRequest(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopDeleteFile(), IopDeleteIoCompletion(), IopDisassociateThreadIrp(), IopfCompleteRequest(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopRaiseHardError(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IopShutdownBaseFileSystems(), IopStartNextPacket(), IopStartNextPacketByKey(), IopXxxControlFile(), IoReadPartitionTable(), IoRetryIrpCompletions(), IoSetInformation(), IoSetPartitionInformation(), IoShutdownSystem(), IoSynchronousPageWrite(), IoVerifyVolume(), IoVolumeDeviceToDosName(), IoWritePartitionTable(), MiRemoveUnusedSegments(), MmCreateSection(), NtCancelIoFile(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtRemoveIoCompletion(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), RawQueryFsSizeInfo(), WmipCompleteGuidIrpWithError(), WmipDeleteMethod(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipGetDevicePDO(), WmipSendWmiIrp(), WmipSetTraceNotify(), WmipTraceIo(), WmipWriteWnodeToObject(), and xHalGetPartialGeometry().