Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/mutant.c File Reference
mutant.c File Reference
#include "exp.h"
Functions
VOID ExpDeleteMutant (IN PVOID Mutant)
BOOLEAN ExpMutantInitialization (VOID)
NTSTATUS NtCreateMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN InitialOwner)
NTSTATUS NtOpenMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQueryMutant (__in HANDLE MutantHandle, __in MUTANT_INFORMATION_CLASS MutantInformationClass, __out_bcount(MutantInformationLength) PVOID MutantInformation, __in ULONG MutantInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtReleaseMutant (__in HANDLE MutantHandle, __out_opt PLONG PreviousCount)
Variables
POBJECT_TYPE ExMutantObjectType
const GENERIC_MAPPING ExpMutantMapping
Function Documentation
VOID ExpDeleteMutant (IN PVOID Mutant)
Definition at line 55 of file mutant.c.
References FALSE, KeReleaseMutant(), MUTANT_INCREMENT, and TRUE.
Referenced by ExpMutantInitialization().
BOOLEAN ExpMutantInitialization (VOID)
Definition at line 90 of file mutant.c.
References _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExpDeleteMutant(), ExpMutantMapping, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KdDumpEnableOffset, _OBJECT_TYPE_INITIALIZER::Length, MUTANT_ALL_ACCESS, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), OBJ_OPENLINK, _OBJECT_TYPE_INITIALIZER::PoolType, PsGetCurrentProcess(), RtlInitUnicodeString(), RtlZeroMemory, Status, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitSystemPhase1().
NTSTATUS NtCreateMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN InitialOwner)
Definition at line 152 of file mutant.c.
References except, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KeInitializeMutant(), KernelMode, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, and Status.
NTSTATUS NtOpenMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 272 of file mutant.c.
References except, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSTATUS NtQueryMutant (__in HANDLE MutantHandle, __in MUTANT_INFORMATION_CLASS MutantInformationClass, __out_bcount(MutantInformationLength) PVOID MutantInformation, __in ULONG MutantInformationLength, __out_opt PULONG ReturnLength)
Definition at line 368 of file mutant.c.
References ARGUMENT_PRESENT, Count, except, ExSystemExceptionFilter(), KeGetCurrentThread(), KeGetPreviousMode, KeReadStateMutant(), KernelMode, MUTANT_QUERY_STATE, MutantBasicInformation, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_INVALID_INFO_CLASS.
NTSTATUS NtReleaseMutant (__in HANDLE MutantHandle, __out_opt PLONG PreviousCount)
Definition at line 505 of file mutant.c.
References ARGUMENT_PRESENT, Count, except, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KeReleaseMutant(), KernelMode, MUTANT_INCREMENT, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
Variable Documentation
POBJECT_TYPE ExMutantObjectType
Definition at line 26 of file mutant.c.
const GENERIC_MAPPING ExpMutantMapping
Initial value:
= {
    STANDARD_RIGHTS_READ | MUTANT_QUERY_STATE,
    STANDARD_RIGHTS_WRITE,
    STANDARD_RIGHTS_EXECUTE | SYNCHRONIZE,
    MUTANT_ALL_ACCESS
}
Definition at line 37 of file mutant.c.
Referenced by ExpMutantInitialization().