Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/exatom.c File Reference
exatom.c File Reference
#include "exp.h"
Macros
#define COPY_STACK_SIZE (RTL_ATOM_MAXIMUM_NAME_LENGTH * sizeof(WCHAR))
Functions
C_ASSERT (COPY_STACK_SIZE<=1024)
PVOID ExpDummyGetAtomTable (VOID)
NTSTATUS NtAddAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
NTSTATUS NtDeleteAtom (__in RTL_ATOM Atom)
NTSTATUS NtFindAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
NTSTATUS NtQueryInformationAtom (__in RTL_ATOM Atom, __in ATOM_INFORMATION_CLASS InformationClass, __out_bcount(AtomInformationLength) PVOID AtomInformation, __in ULONG AtomInformationLength, __out_opt PULONG ReturnLength)
Variables
PKWIN32_GLOBALATOMTABLE_CALLOUT ExGlobalAtomTableCallout = ExpDummyGetAtomTable
Macro Definition Documentation
#define COPY_STACK_SIZE (RTL_ATOM_MAXIMUM_NAME_LENGTH * sizeof(WCHAR))
Definition at line 27 of file exatom.c.
Referenced by NtAddAtom(), and NtFindAtom().
Function Documentation
C_ASSERT (COPY_STACK_SIZE<= 1024)
PVOID ExpDummyGetAtomTable (VOID)
Definition at line 441 of file exatom.c.
References NULL.
NTSTATUS NtAddAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
Definition at line 53 of file exatom.c.
References ARGUMENT_PRESENT, COPY_STACK_SIZE, except, EXCEPTION_EXECUTE_HANDLER, ExGlobalAtomTableCallout, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, ProbeForWriteUshort, RtlAddAtomToAtomTable(), RtlCopyMemory, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and UNICODE_NULL.
NTSTATUS NtDeleteAtom (__in RTL_ATOM Atom)
Definition at line 263 of file exatom.c.
References ExGlobalAtomTableCallout, NULL, PAGED_CODE, RtlDeleteAtomFromAtomTable(), and STATUS_ACCESS_DENIED.
NTSTATUS NtFindAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
Definition at line 158 of file exatom.c.
References ARGUMENT_PRESENT, COPY_STACK_SIZE, except, EXCEPTION_EXECUTE_HANDLER, ExGlobalAtomTableCallout, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, ProbeForWriteUshort, RtlCopyMemory, RtlLookupAtomInAtomTable(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and UNICODE_NULL.
NTSTATUS NtQueryInformationAtom (__in RTL_ATOM Atom, __in ATOM_INFORMATION_CLASS InformationClass, __out_bcount(AtomInformationLength) PVOID AtomInformation, __in ULONG AtomInformationLength, __out_opt PULONG ReturnLength)
Definition at line 301 of file exatom.c.
References ARGUMENT_PRESENT, AtomBasicInformation, _ATOM_TABLE_INFORMATION::Atoms, AtomTableInformation, except, EXCEPTION_EXECUTE_HANDLER, ExGlobalAtomTableCallout, FIELD_OFFSET, _ATOM_BASIC_INFORMATION::Flags, KeGetPreviousMode, KernelMode, _ATOM_BASIC_INFORMATION::Name, _ATOM_BASIC_INFORMATION::NameLength, NT_SUCCESS, NULL, _ATOM_TABLE_INFORMATION::NumberOfAtoms, PAGED_CODE, ProbeForWrite(), ProbeForWriteUlong, RtlQueryAtomInAtomTable(), RtlQueryAtomsInAtomTable(), Status, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, UNICODE_NULL, and _ATOM_BASIC_INFORMATION::UsageCount.
Variable Documentation
PKWIN32_GLOBALATOMTABLE_CALLOUT ExGlobalAtomTableCallout = ExpDummyGetAtomTable
Definition at line 50 of file exatom.c.
Referenced by NtAddAtom(), NtDeleteAtom(), NtFindAtom(), NtQueryInformationAtom(), and PsEstablishWin32Callouts().