Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/string.h File Reference
string.h File Reference
Macros
#define __cdecl
#define _CRTIMP
#define _INC_STRING
#define _NLSCMP_DEFINED
#define _NLSCMPERROR 2147483647 /* currently == INT_MAX */
#define _SIZE_T_DEFINED
#define _W64
#define _WCHAR_T_DEFINED
#define _WSTRING_DEFINED
#define NULL ((void *)0)
#define wcswcs wcsstr
Typedefs
typedef _W64 unsigned int size_t
typedef unsigned short wchar_t
Functions
_CRTIMP wchar_t *__cdecl __wcserror (const wchar_t *)
_CRTIMP void *__cdecl _memccpy (void *, const void *, int, size_t)
_CRTIMP int __cdecl _memicmp (const void *, const void *, size_t)
_CRTIMP int __cdecl _strcmpi (const char *, const char *)
_CRTIMP char *__cdecl _strdup (const char *)
_CRTIMP char *__cdecl _strerror (const char *)
_CRTIMP int __cdecl _stricmp (const char *, const char *)
_CRTIMP int __cdecl _stricoll (const char *, const char *)
_CRTIMP char *__cdecl _strlwr (char *)
_CRTIMP int __cdecl _strncoll (const char *, const char *, size_t)
_CRTIMP int __cdecl _strnicmp (const char *, const char *, size_t)
_CRTIMP int __cdecl _strnicoll (const char *, const char *, size_t)
_CRTIMP char *__cdecl _strnset (char *, int, size_t)
_CRTIMP char *__cdecl _strrev (char *)
char *__cdecl _strset (char *, int)
_CRTIMP char *__cdecl _strupr (char *)
_CRTIMP wchar_t *__cdecl _wcsdup (const wchar_t *)
_CRTIMP wchar_t *__cdecl _wcserror (int)
_CRTIMP int __cdecl _wcsicmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl _wcsicoll (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl _wcslwr (wchar_t *)
_CRTIMP int __cdecl _wcsncoll (const wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl _wcsnicmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl _wcsnicoll (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl _wcsnset (wchar_t *, wchar_t, size_t)
_CRTIMP wchar_t *__cdecl _wcsrev (wchar_t *)
_CRTIMP wchar_t *__cdecl _wcsset (wchar_t *, wchar_t)
_CRTIMP wchar_t *__cdecl _wcsupr (wchar_t *)
_CRTIMP void *__cdecl memccpy (void *, const void *, int, size_t)
_CRTIMP void *__cdecl memchr (const void *, int, size_t)
int __cdecl memcmp (const void *, const void *, size_t)
void *__cdecl memcpy (void *, const void *, size_t)
_CRTIMP int __cdecl memicmp (const void *, const void *, size_t)
_CRTIMP void *__cdecl memmove (void *, const void *, size_t)
void *__cdecl memset (void *, int, size_t)
char *__cdecl strcat (char *, const char *)
_CRTIMP char *__cdecl strchr (const char *, int)
int __cdecl strcmp (const char *, const char *)
_CRTIMP int __cdecl strcmpi (const char *, const char *)
_CRTIMP int __cdecl strcoll (const char *, const char *)
char *__cdecl strcpy (char *, const char *)
_CRTIMP size_t __cdecl strcspn (const char *, const char *)
_CRTIMP char *__cdecl strdup (const char *)
_CRTIMP char *__cdecl strerror (int)
_CRTIMP int __cdecl stricmp (const char *, const char *)
size_t __cdecl strlen (const char *)
_CRTIMP char *__cdecl strlwr (char *)
_CRTIMP char *__cdecl strncat (char *, const char *, size_t)
_CRTIMP int __cdecl strncmp (const char *, const char *, size_t)
_CRTIMP char *__cdecl strncpy (char *, const char *, size_t)
_CRTIMP int __cdecl strnicmp (const char *, const char *, size_t)
_CRTIMP char *__cdecl strnset (char *, int, size_t)
_CRTIMP char *__cdecl strpbrk (const char *, const char *)
_CRTIMP char *__cdecl strrchr (const char *, int)
_CRTIMP char *__cdecl strrev (char *)
char *__cdecl strset (char *, int)
_CRTIMP size_t __cdecl strspn (const char *, const char *)
_CRTIMP char *__cdecl strstr (const char *, const char *)
_CRTIMP char *__cdecl strtok (char *, const char *)
_CRTIMP char *__cdecl strupr (char *)
_CRTIMP size_t __cdecl strxfrm (char *, const char *, size_t)
_CRTIMP wchar_t *__cdecl wcscat (wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcschr (const wchar_t *, wchar_t)
_CRTIMP int __cdecl wcscmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl wcscoll (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcscpy (wchar_t *, const wchar_t *)
_CRTIMP size_t __cdecl wcscspn (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcsdup (const wchar_t *)
_CRTIMP int __cdecl wcsicmp (const wchar_t *, const wchar_t *)
_CRTIMP int __cdecl wcsicoll (const wchar_t *, const wchar_t *)
_CRTIMP size_t __cdecl wcslen (const wchar_t *)
_CRTIMP wchar_t *__cdecl wcslwr (wchar_t *)
_CRTIMP wchar_t *__cdecl wcsncat (wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl wcsncmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl wcsncpy (wchar_t *, const wchar_t *, size_t)
_CRTIMP int __cdecl wcsnicmp (const wchar_t *, const wchar_t *, size_t)
_CRTIMP wchar_t *__cdecl wcsnset (wchar_t *, wchar_t, size_t)
_CRTIMP wchar_t *__cdecl wcspbrk (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcsrchr (const wchar_t *, wchar_t)
_CRTIMP wchar_t *__cdecl wcsrev (wchar_t *)
_CRTIMP wchar_t *__cdecl wcsset (wchar_t *, wchar_t)
_CRTIMP size_t __cdecl wcsspn (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcsstr (const wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcstok (wchar_t *, const wchar_t *)
_CRTIMP wchar_t *__cdecl wcsupr (wchar_t *)
_CRTIMP size_t __cdecl wcsxfrm (wchar_t *, const wchar_t *, size_t)
Macro Definition Documentation
#define __cdecl
Definition at line 57 of file string.h.
#define _CRTIMP
Definition at line 50 of file string.h.
#define _INC_STRING
Definition at line 29 of file string.h.
#define _NLSCMP_DEFINED
Definition at line 78 of file string.h.
#define _NLSCMPERROR 2147483647 /* currently == INT_MAX */
Definition at line 77 of file string.h.
#define _SIZE_T_DEFINED
Definition at line 67 of file string.h.
#define _W64
Definition at line 40 of file string.h.
#define _WCHAR_T_DEFINED
Definition at line 73 of file string.h.
#define _WSTRING_DEFINED
Definition at line 213 of file string.h.
#define NULL ((void *)0)
Definition at line 87 of file string.h.
#define wcswcs wcsstr
Definition at line 198 of file string.h.
Typedef Documentation
typedef _W64 unsigned int size_t
Definition at line 65 of file string.h.
typedef unsigned short wchar_t
Definition at line 72 of file string.h.
Function Documentation
_CRTIMP wchar_t* __cdecl __wcserror (const wchar_t *)
_CRTIMP void* __cdecl _memccpy (void * , const void * , int , size_t)
_CRTIMP int __cdecl _memicmp (const void * , const void * , size_t)
Referenced by ExpInitializeExecutive().
_CRTIMP int __cdecl _strcmpi (const char * , const char *)
_CRTIMP char* __cdecl _strdup (const char *)
_CRTIMP char* __cdecl _strerror (const char *)
_CRTIMP int __cdecl _stricmp (const char * , const char *)
Referenced by CmpSetupConfigurationTree().
_CRTIMP int __cdecl _stricoll (const char * , const char *)
_CRTIMP char* __cdecl _strlwr (char *)
_CRTIMP int __cdecl _strncoll (const char * , const char * , size_t)
_CRTIMP int __cdecl _strnicmp (const char * , const char * , size_t)
Referenced by MiResolveImageReferences().
_CRTIMP int __cdecl _strnicoll (const char * , const char * , size_t)
_CRTIMP char* __cdecl _strnset (char * , int , size_t)
_CRTIMP char* __cdecl _strrev (char *)
char* __cdecl _strset (char * , int)
_CRTIMP char* __cdecl _strupr (char *)
Referenced by ExpInitializeExecutive(), IoAssignDriveLetters(), and Phase1InitializationDiscard().
_CRTIMP wchar_t* __cdecl _wcsdup (const wchar_t *)
_CRTIMP wchar_t* __cdecl _wcserror (int)
_CRTIMP int __cdecl _wcsicmp (const wchar_t * , const wchar_t *)
Referenced by RtlpHashStringToAtom(), and WmipPrepareWnodeSI().
_CRTIMP int __cdecl _wcsicoll (const wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl _wcslwr (wchar_t *)
_CRTIMP int __cdecl _wcsncoll (const wchar_t * , const wchar_t * , size_t)
_CRTIMP int __cdecl _wcsnicmp (const wchar_t * , const wchar_t * , size_t)
Referenced by CmpOpenHiveFiles(), MmLoadSystemImage(), WmipPrepareWnodeSI(), and WmipTranslateFileHandle().
_CRTIMP int __cdecl _wcsnicoll (const wchar_t * , const wchar_t * , size_t)
_CRTIMP wchar_t* __cdecl _wcsnset (wchar_t * , wchar_t , size_t)
_CRTIMP wchar_t* __cdecl _wcsrev (wchar_t *)
_CRTIMP wchar_t* __cdecl _wcsset (wchar_t * , wchar_t)
_CRTIMP wchar_t* __cdecl _wcsupr (wchar_t *)
_CRTIMP void* __cdecl memccpy (void * , const void * , int , size_t)
_CRTIMP void* __cdecl memchr (const void * , int , size_t)
int __cdecl memcmp (const void * , const void * , size_t)
Referenced by NtSetSystemInformation().
void* __cdecl memcpy (void * , const void * , size_t)
Referenced by IopCreateArcNames(), KeCompactServiceTable(), ReadIoSpace(), ReadIoSpace32(), ReadIoSpace64(), RtlCopyString(), WmipAddProviderIdToPIList(), WmipCachePtrs(), WmipCountedToSz(), WmipDereferenceEvent(), WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), WmipFireOffWmiEvent(), WmipGenerateBinaryMofNotification(), WmipGenerateMofResourceNotification(), WmipIncludeStaticNames(), WmipLinkDataSourceToList(), WmipOpenBlock(), WmipQueueNotification(), and WmipRealloc().
_CRTIMP int __cdecl memicmp (const void * , const void * , size_t)
_CRTIMP void* __cdecl memmove (void * , const void * , size_t)
void* __cdecl memset (void * , int , size_t)
Referenced by KeSetPhysicalCacheTypeRange(), KiOpPatchCode(), RtlFreeAnsiString(), RtlFreeUnicodeString(), StringCatExWorkerA(), StringCatExWorkerW(), StringCatNExWorkerA(), StringCatNExWorkerW(), StringCopyExWorkerA(), StringCopyExWorkerW(), StringCopyNExWorkerA(), StringCopyNExWorkerW(), StringGetsExWorkerA(), StringGetsExWorkerW(), StringVPrintfExWorkerA(), StringVPrintfExWorkerW(), WmipAllocDataSource(), WmipAllocEntry(), WmipDereferenceEvent(), WmipDisableCollectionForRemovedGuid(), WmipEnableCollectionForNewGuid(), WmipRealloc(), WmipSendEnableDisableRequest(), and WmipSendGuidUpdateNotifications().
char* __cdecl strcat (char * , const char *)
Referenced by ExpSystemErrorHandler().
_CRTIMP char* __cdecl strchr (const char * , int)
Referenced by MiSnapThunk().
int __cdecl strcmp (const char * , const char *)
Referenced by IopCreateArcNamesCd(), KiGetCpuVendor(), KiInitializeMTRR(), MiFindExportedRoutineByName(), MiLocateExportName(), MiSnapThunk(), and NameToOrdinal().
_CRTIMP int __cdecl strcmpi (const char * , const char *)
_CRTIMP int __cdecl strcoll (const char * , const char *)
char* __cdecl strcpy (char * , const char *)
Referenced by ExpSystemErrorHandler(), IoAssignDriveLetters(), LookupEntryPoint(), MmInitializeProcessAddressSpace(), and PspInitPhase0().
_CRTIMP size_t __cdecl strcspn (const char * , const char *)
_CRTIMP char* __cdecl strdup (const char *)
_CRTIMP char* __cdecl strerror (int)
_CRTIMP int __cdecl stricmp (const char * , const char *)
size_t __cdecl strlen (const char *)
Referenced by CmpFindControlSet(), DbgCommandString(), DbgPrompt(), ExpGetProcessInformation(), ExpSystemErrorHandler(), IoAssignDriveLetters(), IopCreateArcNames(), IopInitializeBootLogging(), IopReassignSystemRoot(), KeGetBugMessageText(), LookupEntryPoint(), MiSnapThunk(), ReloadSymbols(), RtlAppendAsciizToString(), RtlInitAnsiStringEx(), RtlInt64ToUnicodeString(), RtlIntegerToUnicodeString(), vDbgPrintExWithPrefixInternal(), and WmiTraceProcess().
_CRTIMP char* __cdecl strlwr (char *)
_CRTIMP char* __cdecl strncat (char * , const char * , size_t)
_CRTIMP int __cdecl strncmp (const char * , const char * , size_t)
Referenced by KiSetCpuVendor().
_CRTIMP char* __cdecl strncpy (char * , const char * , size_t)
Referenced by MiSnapThunk(), and vDbgPrintExWithPrefixInternal().
_CRTIMP int __cdecl strnicmp (const char * , const char * , size_t)
_CRTIMP char* __cdecl strnset (char * , int , size_t)
_CRTIMP char* __cdecl strpbrk (const char * , const char *)
_CRTIMP char* __cdecl strrchr (const char * , int)
Referenced by IoAssignDriveLetters().
_CRTIMP char* __cdecl strrev (char *)
char* __cdecl strset (char * , int)
_CRTIMP size_t __cdecl strspn (const char * , const char *)
Referenced by _strspnp().
_CRTIMP char* __cdecl strstr (const char * , const char *)
Referenced by ExpInitializeExecutive(), IoAssignDriveLetters(), IopCreateArcNames(), KeStartAllProcessors(), KiInitializeKernel(), MiInitMachineDependent(), MmInitSystem(), and Phase1InitializationDiscard().
_CRTIMP char* __cdecl strtok (char * , const char *)
_CRTIMP char* __cdecl strupr (char *)
_CRTIMP size_t __cdecl strxfrm (char * , const char * , size_t)
_CRTIMP wchar_t* __cdecl wcscat (wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl wcschr (const wchar_t * , wchar_t)
Referenced by MmCallDllInitialize(), RtlQueryEnvironmentVariable_U(), and WmipGenerateFileName().
_CRTIMP int __cdecl wcscmp (const wchar_t * , const wchar_t *)
Referenced by ObCreateObjectType(), SepCleanupLUIDDeviceMapDirectory(), WmipDetermineInstanceBaseIndex(), WmipFindISinGEbyName(), WmipFindMRByNames(), and WmipIsEqualInstanceSets().
_CRTIMP int __cdecl wcscoll (const wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl wcscpy (wchar_t * , const wchar_t *)
_CRTIMP size_t __cdecl wcscspn (const wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl wcsdup (const wchar_t *)
_CRTIMP int __cdecl wcsicmp (const wchar_t * , const wchar_t *)
_CRTIMP int __cdecl wcsicoll (const wchar_t * , const wchar_t *)
_CRTIMP size_t __cdecl wcslen (const wchar_t *)
Referenced by CmpFindProfileOption(), CmpGetHiveName(), CmpOpenHiveFiles(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopErrorLogThread(), IopFetchConfigurationInformation(), IopGetRegistryValue(), LdrpCompareResourceNames_U(), MmLoadSystemImage(), RtlCreateUnicodeString(), RtlInitUnicodeStringEx(), RtlQueryEnvironmentVariable_U(), RtlSetTimeZoneInformation(), WmipAddMofResource(), WmipBuildInstanceSet(), WmipCreateNtFileName(), WmipDelayCreate(), WmipEnumerateMofResources(), WmipFindISinGEbyName(), WmipGenerateBinaryMofNotification(), WmipGenerateMofResourceNotification(), WmipIncludeStaticNames(), WmipInsertStaticNames(), WmipMangleInstanceName(), WmipPrepareWnodeSI(), WmipStaticInstanceNameSize(), and WmipTranslateFileHandle().
_CRTIMP wchar_t* __cdecl wcslwr (wchar_t *)
_CRTIMP wchar_t* __cdecl wcsncat (wchar_t * , const wchar_t * , size_t)
_CRTIMP int __cdecl wcsncmp (const wchar_t * , const wchar_t * , size_t)
Referenced by LdrpCompareResourceNames_U(), and WmipFindISinGEbyName().
_CRTIMP wchar_t* __cdecl wcsncpy (wchar_t * , const wchar_t * , size_t)
Referenced by DbgkCreateThread(), IopDeleteSessionSymLinks(), WmipBuildInstanceSet(), and WmipMangleInstanceName().
_CRTIMP int __cdecl wcsnicmp (const wchar_t * , const wchar_t * , size_t)
_CRTIMP wchar_t* __cdecl wcsnset (wchar_t * , wchar_t , size_t)
_CRTIMP wchar_t* __cdecl wcspbrk (const wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl wcsrchr (const wchar_t * , wchar_t)
Referenced by WmipGenerateFileName().
_CRTIMP wchar_t* __cdecl wcsrev (wchar_t *)
_CRTIMP wchar_t* __cdecl wcsset (wchar_t * , wchar_t)
_CRTIMP size_t __cdecl wcsspn (const wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl wcsstr (const wchar_t * , const wchar_t *)
Referenced by DbgkpPostFakeModuleMessages(), RtlCreateUserProcess(), and WmipGenerateFileName().
_CRTIMP wchar_t* __cdecl wcstok (wchar_t * , const wchar_t *)
_CRTIMP wchar_t* __cdecl wcsupr (wchar_t *)
_CRTIMP size_t __cdecl wcsxfrm (wchar_t * , const wchar_t * , size_t)