Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/wmi.c File Reference
wmi.c File Reference
#include "wmikmp.h"
#include "evntrace.h"
#include "tracep.h"
Functions
NTSTATUS DriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
NTSTATUS WmipDriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
BOOLEAN WmipFastIoDeviceControl (IN PFILE_OBJECT FileObject, IN BOOLEAN Wait, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN ULONG IoControlCode, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT *DeviceObject)
NTSTATUS WmipForwardWmiIrp (PIRP Irp, UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer)
NTSTATUS WmipGetDevicePDO (PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT *PDO)
NTSTATUS WmipIoControl (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS WmipObjectToPDO (PFILE_OBJECT FileObject, PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT *PDO)
NTSTATUS WmipOpenCloseCleanup (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS WmipProbeAndCaptureGuidObjectAttributes (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS WmipProbeWmiOpenGuidBlock (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, PULONG DesiredAccess, PWMIOPENGUIDBLOCK InGuidBlock, ULONG InBufferLen, ULONG OutBufferLen)
NTSTATUS WmipProbeWmiRegRequest (IN PDEVICE_OBJECT DeviceObject, IN PWMIREGREQUEST Buffer, IN ULONG InBufferLen, IN ULONG OutBufferLen, OUT PBOOLEAN MofIgnored)
NTSTATUS WmipProbeWmiRegRequest (PDEVICE_OBJECT DeviceObject, PWMIREGREQUEST Buffer, ULONG InBufferLen, ULONG OutBufferLen, PBOOLEAN pMofIgnored)
NTSTATUS WmipProbeWnodeAllData (PWNODE_ALL_DATA Wnode, ULONG InBufferLen, ULONG OutBufferLen)
NTSTATUS WmipProbeWnodeMethodItem (PWNODE_METHOD_ITEM Wnode, ULONG InBufferLen, ULONG OutBufferLen)
NTSTATUS WmipProbeWnodeSingleInstance (PWNODE_SINGLE_INSTANCE Wnode, ULONG InBufferLen, ULONG OutBufferLen, BOOLEAN OutBound)
NTSTATUS WmipProbeWnodeSingleItem (PWNODE_SINGLE_ITEM Wnode, ULONG InBufferLen)
NTSTATUS WmipProbeWnodeWorker (PWNODE_HEADER WnodeHeader, ULONG MinWnodeSize, ULONG InstanceNameOffset, ULONG DataBlockOffset, ULONG DataBlockSize, ULONG InBufferLen, ULONG OutBufferLen, BOOLEAN CheckOutBound, BOOLEAN CheckInBound)
NTSTATUS WmipSendWmiIrp (UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer, PIO_STATUS_BLOCK Iosb)
NTSTATUS WmipSystemControl (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
NTSTATUS WmipTranslateFileHandle (IN OUT PWMIFHTOINSTANCENAME FhToInstanceName, IN OUT PULONG OutBufferLen, IN HANDLE FileHandle, IN PDEVICE_OBJECT DeviceObject, IN PWMIGUIDOBJECT GuidObject, OUT PUNICODE_STRING InstanceNameString)
void WmipUpdateDeviceStackSize (CCHAR NewStackSize)
NTSTATUS WmipWmiIrpCompletion (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
Variables
PDEVICE_OBJECT WmipAdminDeviceObject
FAST_IO_DISPATCH WmipFastIoDispatch
ULONG WmipMaxKmWnodeEventSize = DEFAULTMAXKMWNODEEVENTSIZE
UNICODE_STRING WmipRegistryPath
PDEVICE_OBJECT WmipServiceDeviceObject
KMUTEX WmipSMMutex
KMUTEX WmipTLMutex
Function Documentation
NTSTATUS DriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Definition at line 180 of file wmi.c.
References STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by CmGetSystemDriverList(), and CmpAddDriverToList().
NTSTATUS WmipDriverEntry (IN PDRIVER_OBJECT DriverObject, IN PUNICODE_STRING RegistryPath)
Definition at line 193 of file wmi.c.
References DACL_SECURITY_INFORMATION, DO_DEVICE_INITIALIZING, EventCategoryHardwareProfileChange, ExFreePool(), FALSE, _FAST_IO_DISPATCH::FastIoDeviceControl, FILE_DEVICE_SECURE_OPEN, FILE_DEVICE_UNKNOWN, IoCreateDevice(), IoCreateSymbolicLink(), IoDeleteDevice(), IoDeleteSymbolicLink(), IoRegisterPlugPlayNotification(), IoRegisterShutdownNotification(), IoWMIRegistrationControl(), IRP_MJ_CLEANUP, IRP_MJ_CLOSE, IRP_MJ_CREATE, IRP_MJ_DEVICE_CONTROL, IRP_MJ_SHUTDOWN, IRP_MJ_SYSTEM_CONTROL, KeInitializeMutex(), MAXLOGGERS, NT_SUCCESS, NULL, ObSetSecurityObjectByPointer(), OWNER_SECURITY_INFORMATION, PAGED_CODE, RtlAnsiStringToUnicodeString(), RtlInitAnsiString(), RtlInitUnicodeString(), RtlZeroMemory, SharedUserData, _FAST_IO_DISPATCH::SizeOfFastIoDispatch, Status, TRUE, UNREFERENCED_PARAMETER, WMIAdminDeviceObjectName, WMIAdminSymbolicLinkName, WmiDeviceStackSize, WmipAdminDeviceObject, WmipCreateAdminSD(), WmipDockUndockEventCallback(), WmipFastIoDeviceControl(), WmipFastIoDispatch, WmipInitializeDataStructs(), WmipInitializeNotifications(), WmipInitializeRegistration(), WmipInitializeSecurity(), WmipIoControl(), WmipLoggerContext, WmipOpenCloseCleanup(), WmipRefCount, WmipServiceDeviceObject, WmipShutdown(), WmipStartGlobalLogger(), WmipSystemControl(), WMIREG_ACTION_REGISTER, WMIServiceDeviceObjectName, and WMIServiceSymbolicLinkName.
Referenced by WMIInitialize().
BOOLEAN WmipFastIoDeviceControl (IN PFILE_OBJECT FileObject, IN BOOLEAN Wait, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN ULONG IoControlCode, OUT PIO_STATUS_BLOCK IoStatus, IN struct _DEVICE_OBJECT * DeviceObject)
Definition at line 2229 of file wmi.c.
References FALSE, KeGetPreviousMode, PAGED_CODE, TRUE, UNREFERENCED_PARAMETER, WmiTraceEvent(), and WmiTraceUserMessage().
Referenced by WmipDriverEntry().
NTSTATUS WmipForwardWmiIrp (PIRP Irp, UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer)
Definition at line 1688 of file wmi.c.
References _REGENTRY::DeviceObject, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, IRPCOMPCTX::Event, Executive, FALSE, FIELD_OFFSET, _REGENTRY::Flags, _WNODE_HEADER::Guid, IoCallDriver(), IoGetAttachedDeviceReference(), IoGetCurrentIrpStackLocation, IoGetNextIrpStackLocation, IoMarkIrpPending, IoSetCompletionRoutine, IRP_MJ_SYSTEM_CONTROL, IRP_MN_CHANGE_SINGLE_INSTANCE, IRP_MN_QUERY_ALL_DATA, IRP_MN_QUERY_SINGLE_INSTANCE, IRP_MN_REGINFO, IRP_MN_REGINFO_EX, IsEqualGUID, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _IO_STACK_LOCATION::Parameters, _REGENTRY::PDO, IRPCOMPCTX::RegEntry, REGENTRY_FLAG_CALLBACK, REGENTRY_FLAG_NOT_ACCEPTING_IRPS, Status, STATUS_NOT_SUPPORTED, STATUS_PENDING, STATUS_UNSUCCESSFUL, STATUS_WMI_GUID_NOT_FOUND, STATUS_WMI_INSTANCE_NOT_FOUND, STATUS_WMI_TRY_AGAIN, SynchronizationEvent, TRUE, _REGENTRY::WmiEntry, WmipAssert, WmipDataProviderPnpidGuid, WmipDataProviderPnPIdInstanceNamesGuid, WmipDebugPrintEx, WmipDecrementIrpCount(), WmipFindRegEntryByProviderId, WmipServiceDeviceObject, WmipTranslatePDOInstanceNames(), WmipUnreferenceRegEntry, WmipUpdateDeviceStackSize(), and WmipWmiIrpCompletion().
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipQueryAllData(), WmipQuerySetExecuteSI(), WmipSendWmiIrp(), and WmipSetTraceNotify().
NTSTATUS WmipGetDevicePDO (PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT * PDO)
Definition at line 1580 of file wmi.c.
References ASSERT, _DEVICE_RELATIONS::Count, Executive, ExFreePool(), FALSE, _IO_STATUS_BLOCK::Information, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetNextIrpStackLocation, IRP_MJ_PNP, IRP_MN_QUERY_DEVICE_RELATIONS, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NT_SUCCESS, NULL, _DEVICE_RELATIONS::Objects, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_SUPPORTED, STATUS_PENDING, and TargetDeviceRelation.
Referenced by WmipObjectToPDO().
NTSTATUS WmipIoControl (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 465 of file wmi.c.
References _UNICODE_STRING::Buffer, _WNODE_HEADER::BufferSize, WMIREGINFOW::BufferSize, DPFLTR_INFO_LEVEL, DPFLTR_WMICORE_ID, FALSE, FIELD_OFFSET, _WNODE_HEADER::Flags, WMILANGUAGECHANGE::Flags, GUID_MOF_RESOURCE_ADDED_NOTIFICATION, GUID_MOF_RESOURCE_REMOVED_NOTIFICATION, WMIREGINFOW::GuidCount, Handle, HANDLE3264::Handle, WMIMARKASCLOSED::Handle, WMIOPENGUIDBLOCK::Handle, WMIQADMULTIPLE::HandleCount, WMIRECEIVENOTIFICATION::HandleCount, WMIREGGUIDW::InstanceCount, WMIREGGUIDW::InstanceNameList, IO_NO_INCREMENT, IoCompleteRequest(), Ioctl, IOCTL_WMI_ENUMERATE_GUIDS, IOCTL_WMI_ENUMERATE_GUIDS_AND_PROPERTIES, IOCTL_WMI_ENUMERATE_MOF_RESOURCES, IOCTL_WMI_EXECUTE_METHOD, IOCTL_WMI_GET_VERSION, IOCTL_WMI_MARK_HANDLE_AS_CLOSED, IOCTL_WMI_NOTIFY_LANGUAGE_CHANGE, IOCTL_WMI_OPEN_GUID, IOCTL_WMI_OPEN_GUID_FOR_EVENTS, IOCTL_WMI_OPEN_GUID_FOR_QUERYSET, IOCTL_WMI_QAD_MULTIPLE, IOCTL_WMI_QSI_MULTIPLE, IOCTL_WMI_QUERY_ALL_DATA, IOCTL_WMI_QUERY_GUID_INFO, IOCTL_WMI_QUERY_SINGLE_INSTANCE, IOCTL_WMI_RECEIVE_NOTIFICATIONS, IOCTL_WMI_SET_SINGLE_INSTANCE, IOCTL_WMI_SET_SINGLE_ITEM, IOCTL_WMI_TRANSLATE_FILE_HANDLE, IoGetCurrentIrpStackLocation, IRP_MN_CHANGE_SINGLE_INSTANCE, IRP_MN_CHANGE_SINGLE_ITEM, IRP_MN_EXECUTE_METHOD, IRP_MN_QUERY_SINGLE_INSTANCE, KeGetPreviousMode, WMILANGUAGECHANGE::Language, _WMI_LOGGER_INFORMATION::LogFileName, _WMI_LOGGER_INFORMATION::LoggerName, MAX_LANGUAGE_SIZE, MOFEVENT_ACTION_LANGUAGE_CHANGE, WMIREGINFOW::MofResourceName, NT_SUCCESS, NULL, OffsetToPtr, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PtrToUlong, WMIQSIMULTIPLE::QueryCount, QUERYMULIPLEHANDLELIMIT, WMIREGINFOW::RegistryPath, RTL_CONTAINS_FIELD, RtlCopyMemory, RtlZeroMemory, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, UlongToPtr, UserMode, WMI_CURRENT_VERSION, WmiFlushTrace(), WmiGuidObjectNameLength, WMILANGUAGECHANGE_FLAG_ADDED, WMILANGUAGECHANGE_FLAG_REMOVED, WmiMBReply, WmipAdminDeviceObject, WmipAlloc, WmipAssert, WmipCreateUMLogger(), WmipDebugPrintEx, WmipEnableDisableTrace(), WmipEnumerateGuids(), WmipEnumerateMofResources(), WmipFree, WmipGenerateMofResourceNotification(), WmipMarkHandleAsClosed(), WmipMBReply(), WmipNtDllLoggerInfo(), WmipOpenBlock(), WmipProbeWmiOpenGuidBlock(), WmipProbeWmiRegRequest(), WmipProbeWnodeAllData(), WmipProbeWnodeMethodItem(), WmipProbeWnodeSingleInstance(), WmipProbeWnodeSingleItem(), WmipQueryAllData(), WmipQueryAllDataMultiple(), WmipQueryGuidInfo(), WmipQueryLogger(), WmipQuerySetExecuteSI(), WmipQuerySingleMultiple(), WmipReceiveNotifications(), WmipRegisterUMGuids(), WmipStartLogger(), WmipTranslateFileHandle(), WmipUnregisterGuids(), WmipValidateClockType(), WmiSetMark(), WmiStopTrace(), WmiTraceEvent(), WmiTraceUserMessage(), WmiUpdateTrace(), WNODE_FLAG_TRACED_GUID, and _WMI_LOGGER_INFORMATION::Wow.
Referenced by WmipDriverEntry().
NTSTATUS WmipObjectToPDO (PFILE_OBJECT FileObject, PDEVICE_OBJECT DeviceObject, PDEVICE_OBJECT * PDO)
Definition at line 1638 of file wmi.c.
References IoGetRelatedDeviceObject(), NULL, PAGED_CODE, Status, STATUS_NO_SUCH_DEVICE, and WmipGetDevicePDO().
Referenced by WmipTranslateFileHandle().
NTSTATUS WmipOpenCloseCleanup (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 410 of file wmi.c.
References IO_NO_INCREMENT, IoCompleteRequest(), PAGED_CODE, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by WmipDriverEntry().
NTSTATUS WmipProbeAndCaptureGuidObjectAttributes (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 2865 of file wmi.c.
References _OBJECT_ATTRIBUTES32::Attributes, _OBJECT_ATTRIBUTES::Attributes, _UNICODE_STRING::Buffer, _STRING32::Buffer, except, EXCEPTION_EXECUTE_HANDLER, _UNICODE_STRING::Length, _STRING32::Length, _OBJECT_ATTRIBUTES::Length, _UNICODE_STRING::MaximumLength, _STRING32::MaximumLength, NULL, _OBJECT_ATTRIBUTES32::ObjectName, _OBJECT_ATTRIBUTES::ObjectName, PAGED_CODE, ProbeAndReadStructure, ProbeAndReadUnicodeString, ProbeForRead, _OBJECT_ATTRIBUTES32::RootDirectory, _OBJECT_ATTRIBUTES::RootDirectory, RtlCopyMemory, _OBJECT_ATTRIBUTES32::SecurityDescriptor, _OBJECT_ATTRIBUTES::SecurityDescriptor, _OBJECT_ATTRIBUTES32::SecurityQualityOfService, _OBJECT_ATTRIBUTES::SecurityQualityOfService, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, UlongToPtr, UNICODE_NULL, and WmiGuidObjectNameLength.
Referenced by WmipCreateUMLogger(), WmipProbeWmiOpenGuidBlock(), and WmipRegisterUMGuids().
NTSTATUS WmipProbeWmiOpenGuidBlock (POBJECT_ATTRIBUTES CapturedObjectAttributes, PUNICODE_STRING CapturedGuidString, PWCHAR CapturedGuidBuffer, PULONG DesiredAccess, PWMIOPENGUIDBLOCK InGuidBlock, ULONG InBufferLen, ULONG OutBufferLen)
Definition at line 2980 of file wmi.c.
References _OBJECT_ATTRIBUTES::Attributes, WMIOPENGUIDBLOCK::DesiredAccess, WMIOPENGUIDBLOCK32::DesiredAccess, NT_SUCCESS, NULL, WMIOPENGUIDBLOCK::ObjectAttributes, WMIOPENGUIDBLOCK32::ObjectAttributes, PAGED_CODE, _OBJECT_ATTRIBUTES::RootDirectory, _OBJECT_ATTRIBUTES::SecurityDescriptor, _OBJECT_ATTRIBUTES::SecurityQualityOfService, Status, STATUS_INVALID_PARAMETER, STATUS_UNSUCCESSFUL, ULongToPtr, and WmipProbeAndCaptureGuidObjectAttributes().
Referenced by WmipIoControl().
NTSTATUS WmipProbeWmiRegRequest (IN PDEVICE_OBJECT DeviceObject, IN PWMIREGREQUEST Buffer, IN ULONG InBufferLen, IN ULONG OutBufferLen, OUT PBOOLEAN MofIgnored)
Referenced by WmipIoControl().
NTSTATUS WmipProbeWmiRegRequest (PDEVICE_OBJECT DeviceObject, PWMIREGREQUEST Buffer, ULONG InBufferLen, ULONG OutBufferLen, PBOOLEAN pMofIgnored)
Definition at line 3051 of file wmi.c.
References WMIREGINFOW::BufferSize, FALSE, WMIREGINFOW::GuidCount, WMIREGGUIDW::InstanceCount, WMIREGGUIDW::InstanceNameList, WMIREGINFOW::MofResourceName, NULL, OffsetToPtr, PAGED_CODE, WMIREGINFOW::RegistryPath, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TRUE, and WmipAdminDeviceObject.
NTSTATUS WmipProbeWnodeAllData (PWNODE_ALL_DATA Wnode, ULONG InBufferLen, ULONG OutBufferLen)
Definition at line 2452 of file wmi.c.
References PAGED_CODE, Status, STATUS_UNSUCCESSFUL, WmipAssert, WmipIsAligned, WmipValidateWnodeHeader, and WNODE_FLAG_ALL_DATA.
Referenced by WmipIoControl().
NTSTATUS WmipProbeWnodeMethodItem (PWNODE_METHOD_ITEM Wnode, ULONG InBufferLen, ULONG OutBufferLen)
Definition at line 2753 of file wmi.c.
References FIELD_OFFSET, NT_SUCCESS, PAGED_CODE, Status, STATUS_UNSUCCESSFUL, TRUE, WmipAssert, WmipIsAligned, WmipProbeWnodeWorker(), WmipValidateWnodeHeader, and WNODE_FLAG_METHOD_ITEM.
Referenced by WmipIoControl().
NTSTATUS WmipProbeWnodeSingleInstance (PWNODE_SINGLE_INSTANCE Wnode, ULONG InBufferLen, ULONG OutBufferLen, BOOLEAN OutBound)
Definition at line 2520 of file wmi.c.
References FIELD_OFFSET, NT_SUCCESS, PAGED_CODE, Status, STATUS_UNSUCCESSFUL, WmipAssert, WmipIsAligned, WmipProbeWnodeWorker(), WmipValidateWnodeHeader, and WNODE_FLAG_SINGLE_INSTANCE.
Referenced by WmipIoControl().
NTSTATUS WmipProbeWnodeSingleItem (PWNODE_SINGLE_ITEM Wnode, ULONG InBufferLen)
Definition at line 2644 of file wmi.c.
References FALSE, FIELD_OFFSET, NT_SUCCESS, PAGED_CODE, Status, STATUS_UNSUCCESSFUL, TRUE, WmipAssert, WmipIsAligned, WmipProbeWnodeWorker(), WmipValidateWnodeHeader, and WNODE_FLAG_SINGLE_ITEM.
Referenced by WmipIoControl().
NTSTATUS WmipProbeWnodeWorker (PWNODE_HEADER WnodeHeader, ULONG MinWnodeSize, ULONG InstanceNameOffset, ULONG DataBlockOffset, ULONG DataBlockSize, ULONG InBufferLen, ULONG OutBufferLen, BOOLEAN CheckOutBound, BOOLEAN CheckInBound)
Definition at line 2265 of file wmi.c.
References OffsetToPtr, PAGED_CODE, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and WmipIsAligned.
Referenced by WmipProbeWnodeMethodItem(), WmipProbeWnodeSingleInstance(), and WmipProbeWnodeSingleItem().
NTSTATUS WmipSendWmiIrp (UCHAR MinorFunction, ULONG ProviderId, PVOID DataPath, ULONG BufferLength, PVOID Buffer, PIO_STATUS_BLOCK Iosb)
Definition at line 1937 of file wmi.c.
References _IO_STACK_LOCATION::DeviceObject, FALSE, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoSetNextIrpStackLocation, NULL, PAGED_CODE, PIRP, PsGetCurrentThread(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_WMI_TRY_AGAIN, WmipForwardWmiIrp(), and WmipServiceDeviceObject.
Referenced by WmipDeliverWnodeToDS(), WmipQueryAllData(), WmipQuerySetExecuteSI(), and WmipRegisterOrUpdateDS().
NTSTATUS WmipSystemControl (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 1523 of file wmi.c.
References IoWMISystemControl(), PAGED_CODE, and WmipWmiLibInfo.
Referenced by WmipDriverEntry().
NTSTATUS WmipTranslateFileHandle (IN OUT PWMIFHTOINSTANCENAME FhToInstanceName, IN OUT PULONG OutBufferLen, IN HANDLE FileHandle, IN PDEVICE_OBJECT DeviceObject, IN PWMIGUIDOBJECT GuidObject, OUT PUNICODE_STRING InstanceNameString)
Definition at line 2003 of file wmi.c.
References _wcsnicmp(), ISBASENAME::BaseIndex, ISBASENAME::BaseName, _UNICODE_STRING::Buffer, CONTAINING_RECORD, ExAllocatePoolWithTag, FIELD_OFFSET, FILE_ALL_ACCESS, tagInstanceSet::Flags, _LIST_ENTRY::Flink, IoFileObjectType, IS_INSTANCE_BASENAME, tagInstanceSet::IsBaseName, tagGUIDENTRY::ISCount, tagGUIDENTRY::ISHead, KernelMode, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ObReferenceObjectByPointer(), PAGED_CODE, PagedPool, RtlCopyMemory, RtlFreeUnicodeString(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_HANDLE, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WMI_INSTANCE_NOT_FOUND, StringCbPrintf, UNICODE_NULL, UserMode, wcslen(), WmipAssert, WmipEnterSMCritSection, WmipGuidObjectType, WmipInstanceNameTag, WmipLeaveSMCritSection, WmipObjectToPDO(), and WmipPDOToDeviceInstanceName().
Referenced by IoWMIDeviceObjectToInstanceName(), IoWMIHandleToInstanceName(), and WmipIoControl().
void WmipUpdateDeviceStackSize (CCHAR NewStackSize)
Definition at line 426 of file wmi.c.
References PAGED_CODE, WmipEnterSMCritSection, WmipLeaveSMCritSection, and WmipServiceDeviceObject.
Referenced by WmipForwardWmiIrp(), and WmipRegisterDevice().
NTSTATUS WmipWmiIrpCompletion (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
Definition at line 1536 of file wmi.c.
References IRPCOMPCTX::Event, FALSE, IO_NO_INCREMENT, KeSetEvent(), IRPCOMPCTX::RegEntry, STATUS_MORE_PROCESSING_REQUIRED, UNREFERENCED_PARAMETER, and WmipDecrementIrpCount().
Referenced by WmipForwardWmiIrp().
Variable Documentation
PDEVICE_OBJECT WmipAdminDeviceObject
Definition at line 150 of file wmi.c.
Referenced by WmipDriverEntry(), WmipIoControl(), and WmipProbeWmiRegRequest().
FAST_IO_DISPATCH WmipFastIoDispatch
Definition at line 173 of file wmi.c.
Referenced by WmipDriverEntry().
ULONG WmipMaxKmWnodeEventSize = DEFAULTMAXKMWNODEEVENTSIZE
Definition at line 154 of file wmi.c.
Referenced by IoWMIWriteEvent().
UNICODE_STRING WmipRegistryPath
Definition at line 171 of file wmi.c.
Referenced by WmipQueryWmiRegInfo().
PDEVICE_OBJECT WmipServiceDeviceObject
Definition at line 149 of file wmi.c.
Referenced by WMIInitialize(), WmipBuildMcaCmcEvent(), WmipDisableKernelTrace(), WmipDriverEntry(), WmipEnableKernelTrace(), WmipForwardWmiIrp(), WmipSendWmiIrp(), WmipSetTraceNotify(), WmipUpdateDeviceStackSize(), and WmipWriteToEventlog().
KMUTEX WmipSMMutex
Definition at line 166 of file wmi.c.
KMUTEX WmipTLMutex
Definition at line 167 of file wmi.c.