Windows Research Kernel v1.2: C:/Windows Research Kernel/se/seclient.c File Reference
seclient.c File Reference
#include "pch.h"
Functions
NTSTATUS SeCreateClientSecurity (__in PETHREAD ClientThread, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN ServerIsRemote, __out PSECURITY_CLIENT_CONTEXT ClientContext)
NTSTATUS SeCreateClientSecurityFromSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN ServerIsRemote, __out PSECURITY_CLIENT_CONTEXT ClientContext)
VOID SeImpersonateClient (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
NTSTATUS SeImpersonateClientEx (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
NTSTATUS SepCreateClientSecurity (IN PACCESS_TOKEN Token, IN PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, IN BOOLEAN ServerIsRemote, TOKEN_TYPE TokenType, BOOLEAN ThreadEffectiveOnly, SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, OUT PSECURITY_CLIENT_CONTEXT ClientContext)
Function Documentation
NTSTATUS SeCreateClientSecurity (__in PETHREAD ClientThread, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN ServerIsRemote, __out PSECURITY_CLIENT_CONTEXT ClientContext)
Definition at line 231 of file seclient.c.
References NT_SUCCESS, ObDereferenceObject(), PAGED_CODE, PsReferenceEffectiveToken(), SECURITY_STATIC_TRACKING, SepCreateClientSecurity(), Status, STATUS_SUCCESS, and TokenType.
Referenced by CmLoadKey(), NtImpersonateThread(), NtSecureConnectPort(), WmipStartLogger(), and WmiUpdateTrace().
NTSTATUS SeCreateClientSecurityFromSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext, __in PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, __in BOOLEAN ServerIsRemote, __out PSECURITY_CLIENT_CONTEXT ClientContext)
Definition at line 456 of file seclient.c.
References FALSE, NT_SUCCESS, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, SECURITY_STATIC_TRACKING, SepCreateClientSecurity(), SeQuerySubjectContextToken, Status, STATUS_SUCCESS, TokenImpersonation, and TokenPrimary.
VOID SeImpersonateClient (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
Definition at line 337 of file seclient.c.
References DbgPrint(), PAGED_CODE, SeImpersonateClientEx(), and VOID.
NTSTATUS SeImpersonateClientEx (__in PSECURITY_CLIENT_CONTEXT ClientContext, __in_opt PETHREAD ServerThread)
Definition at line 380 of file seclient.c.
References ARGUMENT_PRESENT, PAGED_CODE, PsGetCurrentThread(), PsImpersonateClient(), Status, and TRUE.
Referenced by CmpCmdHiveOpen(), NtImpersonateClientOfPort(), NtImpersonateThread(), SeImpersonateClient(), and WmipCreateLogFile().
NTSTATUS SepCreateClientSecurity (IN PACCESS_TOKEN Token, IN PSECURITY_QUALITY_OF_SERVICE ClientSecurityQos, IN BOOLEAN ServerIsRemote, TOKEN_TYPE TokenType, BOOLEAN ThreadEffectiveOnly, SECURITY_IMPERSONATION_LEVEL ImpersonationLevel, OUT PSECURITY_CLIENT_CONTEXT ClientContext)
Definition at line 65 of file seclient.c.
References FALSE, KernelMode, NT_SUCCESS, PAGED_CODE, SeCopyClientToken(), SECURITY_STATIC_TRACKING, SeGetTokenControlInformation(), SepBadImpersonationLevel, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TokenImpersonation, TRUE, and VALID_IMPERSONATION_LEVEL.
Referenced by SeCreateClientSecurity(), and SeCreateClientSecurityFromSubjectContext().