Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/write.c File Reference
write.c File Reference
#include "iomgr.h"
Functions
NTSTATUS NtWriteFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
NTSTATUS NtWriteFileGather (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PFILE_SEGMENT_ELEMENT SegmentArray, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Function Documentation
NTSTATUS NtWriteFile (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_bcount(Length) PVOID Buffer, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Definition at line 25 of file write.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::CurrentByteOffset, DO_BUFFERED_IO, DO_DIRECT_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExRaiseStatus(), FALSE, _FAST_IO_DISPATCH::FastIoWrite, FILE_APPEND_DATA, FILE_USE_FILE_POINTER_POSITION, FILE_WRITE_DATA, FILE_WRITE_TO_END_OF_FILE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_MAILSLOT, FO_NAMED_PIPE, FO_NO_INTERMEDIATE_BUFFERING, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _LARGE_INTEGER::HighPart, _IO_STATUS_BLOCK::Information, IoAllocateMdl(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopExceptionFilter(), IopMarkApcRoutineIfAsyncronousIo32, IopReleaseFileObjectLock, IopSynchronousServiceTail(), IopUpdateWriteOperationCount(), IopUpdateWriteTransferCount(), IoReadAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_DEFER_IO_COMPLETION, IRP_MJ_WRITE, IRP_NOCACHE, IRP_WRITE_OPERATION, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, KeSetEvent(), _LARGE_INTEGER::LowPart, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceFileObjectForWrite(), ObReferenceObjectByHandle, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_OBJECT::PrivateCacheMap, ProbeAndReadUlong, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentThread(), RtlCopyMemory, SeComputeGrantedAccesses, SL_WRITE_THROUGH, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and WriteTransfer.
NTSTATUS NtWriteFileGather (__in HANDLE FileHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in PFILE_SEGMENT_ELEMENT SegmentArray, __in ULONG Length, __in_opt PLARGE_INTEGER ByteOffset, __in_opt PULONG Key)
Definition at line 788 of file write.c.
References ARGUMENT_PRESENT, ASSERT, BYTES_TO_PAGES, _FILE_OBJECT::CompletionContext, _FILE_OBJECT::CurrentByteOffset, DO_BUFFERED_IO, _FILE_OBJECT::Event, EVENT_MODIFY_STATE, ExAllocatePoolWithQuota, except, EXCEPTION_EXECUTE_HANDLER, ExEventObjectType, ExFreePool(), ExRaiseStatus(), FALSE, FILE_APPEND_DATA, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DFS, FILE_DEVICE_DFS_VOLUME, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_USE_FILE_POINTER_POSITION, FILE_WRITE_DATA, FILE_WRITE_TO_END_OF_FILE, _IO_STACK_LOCATION::FileObject, _FILE_OBJECT::Flags, _IO_STACK_LOCATION::Flags, FO_ALERTABLE_IO, FO_MAILSLOT, FO_NAMED_PIPE, FO_NO_INTERMEDIATE_BUFFERING, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _LARGE_INTEGER::HighPart, IoAllocateMdl(), IoFileObjectType, IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrp, IopAllocateIrpCleanup(), IopApcRoutinePresent, IopExceptionCleanup(), IopExceptionFilter(), IopMarkApcRoutineIfAsyncronousIo32, IopReleaseFileObjectLock, IopSynchronousServiceTail(), IoReadAccess, IRP_DEFER_IO_COMPLETION, IRP_MJ_WRITE, IRP_NOCACHE, IRP_WRITE_OPERATION, KeClearEvent(), KeGetPreviousModeByThread, KernelMode, _LARGE_INTEGER::LowPart, MmProbeAndLockSelectedPages(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SIZE, PAGED_CODE, PagedPool, _IO_STACK_LOCATION::Parameters, PIRP, ProbeAndReadUlong, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, PsGetCurrentProcess(), PsGetCurrentThread(), Ptr64ToPtr(), RtlCopyMemory, SeComputeGrantedAccesses, SL_WRITE_THROUGH, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, TYPE_ALIGNMENT, and WriteTransfer.