Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/rtlexec.c File Reference
rtlexec.c File Reference
#include "ntrtlp.h"
#include <nturtl.h>
#include <string.h>
#include "init.h"
#include "ntos.h"
Macros
#define ISTERMINALSERVER() (USER_SHARED_DATA->SuiteMask & (1 << TerminalServer))
#define ROUND_UP(x, y) ((ULONG)(x) + ((y)-1) & ~((y)-1))
#define RtlpDeNormalizeProcessParam(Base, p)
#define RtlpNormalizeProcessParam(Base, p)
#define VALIDATE_OPTIONAL_STRING_PARAMETER(_x)
#define VALIDATE_STRING_PARAMETER(_x)
Functions
NTSTATUS RtlCreateProcessParameters (OUT PRTL_USER_PROCESS_PARAMETERS *pProcessParameters, IN PUNICODE_STRING ImagePathName, IN PUNICODE_STRING DllPath OPTIONAL, IN PUNICODE_STRING CurrentDirectory OPTIONAL, IN PUNICODE_STRING CommandLine OPTIONAL, IN PVOID Environment OPTIONAL, IN PUNICODE_STRING WindowTitle OPTIONAL, IN PUNICODE_STRING DesktopInfo OPTIONAL, IN PUNICODE_STRING ShellInfo OPTIONAL, IN PUNICODE_STRING RuntimeData OPTIONAL)
NTSTATUS RtlCreateUserProcess (IN PUNICODE_STRING NtImagePathName, IN ULONG Attributes, IN PRTL_USER_PROCESS_PARAMETERS ProcessParameters, IN PSECURITY_DESCRIPTOR ProcessSecurityDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR ThreadSecurityDescriptor OPTIONAL, IN HANDLE ParentProcess OPTIONAL, IN BOOLEAN InheritHandles, IN HANDLE DebugPort OPTIONAL, IN HANDLE ExceptionPort OPTIONAL, OUT PRTL_USER_PROCESS_INFORMATION ProcessInformation)
NTSTATUS RtlCreateUserThread (IN HANDLE Process, IN PSECURITY_DESCRIPTOR ThreadSecurityDescriptor OPTIONAL, IN BOOLEAN CreateSuspended, IN ULONG ZeroBits OPTIONAL, IN SIZE_T MaximumStackSize OPTIONAL, IN SIZE_T CommittedStackSize OPTIONAL, IN PUSER_THREAD_START_ROUTINE StartAddress, IN PVOID Parameter OPTIONAL, OUT PHANDLE Thread OPTIONAL, OUT PCLIENT_ID ClientId OPTIONAL)
PRTL_USER_PROCESS_PARAMETERS RtlDeNormalizeProcessParams (IN OUT PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
NTSTATUS RtlDestroyProcessParameters (IN PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
VOID RtlFreeUserThreadStack (HANDLE hProcess, HANDLE hThread)
PRTL_USER_PROCESS_PARAMETERS RtlNormalizeProcessParams (IN OUT PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
VOID RtlpCopyProcString (IN OUT PWSTR *pDst, OUT PUNICODE_STRING DestString, IN PUNICODE_STRING SourceString, IN ULONG DstAlloc OPTIONAL)
NTSTATUS RtlpCreateStack (IN HANDLE Process, IN SIZE_T MaximumStackSize OPTIONAL, IN SIZE_T CommittedStackSize OPTIONAL, IN ULONG ZeroBits OPTIONAL, OUT PINITIAL_TEB InitialTeb)
NTSTATUS RtlpFreeStack (IN HANDLE Process, IN PINITIAL_TEB InitialTeb)
NTSTATUS RtlpOpenImageFile (IN PUNICODE_STRING ImagePathName, IN ULONG Attributes, OUT PHANDLE FileHandle, IN BOOLEAN ReportErrors)
Variables
const UNICODE_STRING NullString = RTL_CONSTANT_STRING(L"")
Macro Definition Documentation
#define ISTERMINALSERVER () (USER_SHARED_DATA->SuiteMask & (1 << TerminalServer))
Definition at line 28 of file rtlexec.c.
Referenced by RtlCreateUserProcess().
#define ROUND_UP (x, y) ((ULONG)(x) + ((y)-1) & ~((y)-1))
Definition at line 24 of file rtlexec.c.
Referenced by RtlCreateProcessParameters(), RtlpCopyProcString(), and RtlpCreateStack().
#define RtlpDeNormalizeProcessParam (Base, p)
Value:
if ((p) != NULL) {                              \
        (p) = (PWSTR)((PCHAR)(p) - (ULONG_PTR)(Base));  \
        }                                           \
Definition at line 431 of file rtlexec.c.
Referenced by RtlDeNormalizeProcessParams().
#define RtlpNormalizeProcessParam (Base, p)
Value:
if ((p) != NULL) {                              \
        (p) = (PWSTR)((PCHAR)(p) + (ULONG_PTR)(Base));  \
        }                                           \
Definition at line 426 of file rtlexec.c.
Referenced by RtlNormalizeProcessParams().
#define VALIDATE_OPTIONAL_STRING_PARAMETER (_x)
Value:
do { \
        if (ARGUMENT_PRESENT((_x))) { \
            ASSERT((_x)->MaximumLength >= (_x)->Length); \
            ASSERT(((_x)->Length == 0) || ((_x)->Buffer != NULL)); \
            if (((_x)->MaximumLength < (_x)->Length) || \
                (((_x)->Length != 0) && ((_x)->Buffer == NULL))) { \
                Status = STATUS_INVALID_PARAMETER; \
                leave; \
            } \
        } \
    } while (0)
Referenced by RtlCreateProcessParameters().
#define VALIDATE_STRING_PARAMETER (_x)
Value:
do { \
        ASSERT(ARGUMENT_PRESENT((_x))); \
        if (!ARGUMENT_PRESENT((_x))) { \
            Status = STATUS_INVALID_PARAMETER; \
            leave; \
        } \
        if (ARGUMENT_PRESENT((_x))) { \
            ASSERT((_x)->MaximumLength >= (_x)->Length); \
            ASSERT(((_x)->Length == 0) || ((_x)->Buffer != NULL)); \
            if (((_x)->MaximumLength < (_x)->Length) || \
                (((_x)->Length != 0) && ((_x)->Buffer == NULL))) { \
                Status = STATUS_INVALID_PARAMETER; \
                leave; \
            } \
        } \
    } while (0)
Referenced by RtlCreateProcessParameters().
Function Documentation
NTSTATUS RtlCreateProcessParameters (OUT PRTL_USER_PROCESS_PARAMETERS * pProcessParameters, IN PUNICODE_STRING ImagePathName, IN PUNICODE_STRING DllPath OPTIONAL, IN PUNICODE_STRING CurrentDirectory OPTIONAL, IN PUNICODE_STRING CommandLine OPTIONAL, IN PVOID Environment OPTIONAL, IN PUNICODE_STRING WindowTitle OPTIONAL, IN PUNICODE_STRING DesktopInfo OPTIONAL, IN PUNICODE_STRING ShellInfo OPTIONAL, IN PUNICODE_STRING RuntimeData OPTIONAL)
Definition at line 114 of file rtlexec.c.
References ARGUMENT_PRESENT, ASSERT, _RTL_USER_PROCESS_PARAMETERS::CommandLine, _RTL_USER_PROCESS_PARAMETERS::ConsoleFlags, _RTL_USER_PROCESS_PARAMETERS::CurrentDirectory, _RTL_USER_PROCESS_PARAMETERS::DebugFlags, _RTL_USER_PROCESS_PARAMETERS::DesktopInfo, _RTL_USER_PROCESS_PARAMETERS::DllPath, DOS_MAX_PATH_LENGTH, _CURDIR::DosPath, _RTL_USER_PROCESS_PARAMETERS::Environment, FALSE, _RTL_USER_PROCESS_PARAMETERS::Flags, _CURDIR::Handle, _RTL_USER_PROCESS_PARAMETERS::ImagePathName, _UNICODE_STRING::Length, _RTL_USER_PROCESS_PARAMETERS::Length, _RTL_USER_PROCESS_PARAMETERS::MaximumLength, NtCurrentPeb, NULL, OBJ_HANDLE_TAGBITS, ROUND_UP, RTL_USER_PROC_CURDIR_CLOSE, RTL_USER_PROC_CURDIR_INHERIT, RTL_USER_PROC_PARAMS_NORMALIZED, RtlAcquirePebLock(), RtlAllocateHeap(), RtlDeNormalizeProcessParams(), RtlDestroyProcessParameters(), RtlpCopyProcString(), RtlProcessHeap, RtlReleasePebLock(), RtlZeroMemory, _RTL_USER_PROCESS_PARAMETERS::RuntimeData, _RTL_USER_PROCESS_PARAMETERS::ShellInfo, Status, STATUS_ACCESS_VIOLATION, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, UNICODE_NULL, VALIDATE_OPTIONAL_STRING_PARAMETER, VALIDATE_STRING_PARAMETER, and _RTL_USER_PROCESS_PARAMETERS::WindowTitle.
NTSTATUS RtlCreateUserProcess (IN PUNICODE_STRING NtImagePathName, IN ULONG Attributes, IN PRTL_USER_PROCESS_PARAMETERS ProcessParameters, IN PSECURITY_DESCRIPTOR ProcessSecurityDescriptor OPTIONAL, IN PSECURITY_DESCRIPTOR ThreadSecurityDescriptor OPTIONAL, IN HANDLE ParentProcess OPTIONAL, IN BOOLEAN InheritHandles, IN HANDLE DebugPort OPTIONAL, IN HANDLE ExceptionPort OPTIONAL, OUT PRTL_USER_PROCESS_INFORMATION ProcessInformation)
Definition at line 774 of file rtlexec.c.
References ARGUMENT_PRESENT, DUPLICATE_SAME_ACCESS, DUPLICATE_SAME_ATTRIBUTES, FLG_ENABLE_CSRDEBUG, IMAGE_SUBSYSTEM_NATIVE, InitializeObjectAttributes, ISTERMINALSERVER, _RTL_USER_PROCESS_PARAMETERS::Length, MEM_COMMIT, MEM_RESERVE, NT_SUCCESS, NtCurrentProcess, NULL, OBJ_CASE_INSENSITIVE, OBJ_INHERIT, PAGE_EXECUTE, PAGE_READWRITE, _PROCESS_BASIC_INFORMATION::PebBaseAddress, PROCESS_ALL_ACCESS, ProcessBasicInformation, RTL_USER_PROC_RESERVE_1MB, RtlCreateUserThread(), RtlGetNtGlobalFlags(), RtlInitUnicodeString(), RtlpOpenImageFile(), RtlZeroMemory, SEC_IMAGE, SECTION_ALL_ACCESS, SectionImageInformation, Status, STATUS_SUCCESS, TRUE, wcsstr(), ZwAllocateVirtualMemory(), ZwClose(), ZwCreateProcess(), ZwCreateSection(), ZwDuplicateObject(), ZwQueryInformationProcess(), ZwQuerySection(), and ZwWriteVirtualMemory().
NTSTATUS RtlCreateUserThread (IN HANDLE Process, IN PSECURITY_DESCRIPTOR ThreadSecurityDescriptor OPTIONAL, IN BOOLEAN CreateSuspended, IN ULONG ZeroBits OPTIONAL, IN SIZE_T MaximumStackSize OPTIONAL, IN SIZE_T CommittedStackSize OPTIONAL, IN PUSER_THREAD_START_ROUTINE StartAddress, IN PVOID Parameter OPTIONAL, OUT PHANDLE Thread OPTIONAL, OUT PCLIENT_ID ClientId OPTIONAL)
Definition at line 1198 of file rtlexec.c.
References ARGUMENT_PRESENT, DbgPrint(), except, EXCEPTION_EXECUTE_HANDLER, InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_KERNEL_HANDLE, RtlInitializeContext(), RtlpCreateStack(), RtlpFreeStack(), _INITIAL_TEB::StackBase, Status, THREAD_ALL_ACCESS, ZwClose(), and ZwCreateThread().
Referenced by RtlCreateUserProcess().
PRTL_USER_PROCESS_PARAMETERS RtlDeNormalizeProcessParams (IN OUT PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
Definition at line 487 of file rtlexec.c.
References ARGUMENT_PRESENT, NULL, RTL_USER_PROC_PARAMS_NORMALIZED, and RtlpDeNormalizeProcessParam.
Referenced by RtlCreateProcessParameters().
NTSTATUS RtlDestroyProcessParameters (IN PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
Definition at line 417 of file rtlexec.c.
References RtlFreeHeap(), RtlProcessHeap, and STATUS_SUCCESS.
Referenced by RtlCreateProcessParameters().
VOID RtlFreeUserThreadStack (HANDLE hProcess, HANDLE hThread)
Definition at line 1343 of file rtlexec.c.
References MEM_RELEASE, NT_SUCCESS, NtFreeVirtualMemory(), NtQueryInformationThread(), NtReadVirtualMemory(), NULL, Status, _THREAD_BASIC_INFORMATION::TebBaseAddress, and ThreadBasicInformation.
PRTL_USER_PROCESS_PARAMETERS RtlNormalizeProcessParams (IN OUT PRTL_USER_PROCESS_PARAMETERS ProcessParameters)
Definition at line 438 of file rtlexec.c.
References ARGUMENT_PRESENT, NULL, RTL_USER_PROC_PARAMS_NORMALIZED, and RtlpNormalizeProcessParam.
VOID RtlpCopyProcString (IN OUT PWSTR * pDst, OUT PUNICODE_STRING DestString, IN PUNICODE_STRING SourceString, IN ULONG DstAlloc OPTIONAL)
Definition at line 81 of file rtlexec.c.
References ARGUMENT_PRESENT, ASSERT, NULL, ROUND_UP, RtlCopyMemory, and RtlZeroMemory.
Referenced by RtlCreateProcessParameters().
NTSTATUS RtlpCreateStack (IN HANDLE Process, IN SIZE_T MaximumStackSize OPTIONAL, IN SIZE_T CommittedStackSize OPTIONAL, IN ULONG ZeroBits OPTIONAL, OUT PINITIAL_TEB InitialTeb)
Definition at line 582 of file rtlexec.c.
References DbgPrint(), FALSE, MEM_COMMIT, MEM_RESERVE, NT_SUCCESS, NtCurrentPeb, NtCurrentProcess, NULL, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_GUARD, PAGE_READWRITE, ROUND_UP, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SizeOfStackCommit, _IMAGE_OPTIONAL_HEADER::SizeOfStackReserve, Status, STATUS_INVALID_IMAGE_FORMAT, STATUS_SUCCESS, SystemBasicInformation, TRUE, ZwAllocateVirtualMemory(), ZwProtectVirtualMemory(), and ZwQuerySystemInformation().
Referenced by RtlCreateUserThread().
NTSTATUS RtlpFreeStack (IN HANDLE Process, IN PINITIAL_TEB InitialTeb)
Definition at line 744 of file rtlexec.c.
References DbgPrint(), MEM_RELEASE, NT_SUCCESS, RtlZeroMemory, Status, STATUS_SUCCESS, and ZwFreeVirtualMemory().
Referenced by RtlCreateUserThread().
NTSTATUS RtlpOpenImageFile (IN PUNICODE_STRING ImagePathName, IN ULONG Attributes, OUT PHANDLE FileHandle, IN BOOLEAN ReportErrors)
Definition at line 536 of file rtlexec.c.
References DbgPrint(), FILE_EXECUTE, FILE_NON_DIRECTORY_FILE, FILE_SHARE_DELETE, FILE_SHARE_READ, InitializeObjectAttributes, NT_SUCCESS, NULL, Status, STATUS_SUCCESS, SYNCHRONIZE, and ZwOpenFile().
Referenced by RtlCreateUserProcess().
Variable Documentation
const UNICODE_STRING NullString = RTL_CONSTANT_STRING(L"")
Definition at line 78 of file rtlexec.c.
Referenced by Phase1InitializationDiscard(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditProcessExit(), SeAuditSystemTimeChange(), SeOperationAuditAlarm(), SepAdtCloseObjectAuditAlarm(), SepAdtDeleteObjectAuditAlarm(), SepAdtOpenObjectAuditAlarm(), SepAuditAssignPrimaryToken(), and WmipStartGlobalLogger().