Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/iosubs.c File Reference
iosubs.c File Reference
#include "iomgr.h"
Macros
#define ALIGN_LONG(Address) ((ULONG) ((Address + 3) & ~3))
#define ALIGN_QUAD(Address) ((ULONG) ((Address + 7) & ~7))
#define ArePacketsEquivalent(P1, P2)
#define GET_OFFSET_LENGTH(CurrentEa, EaBase)
#define GET_OFFSET_LENGTH(CurrentEntry, QuotaBase)
#define IOP_CREATE_FILE_TIMEOUT 1000
#define IopAllocateOpenPacket()
#define IopFreeOpenPacket(p) ExFreePool(p)
#define PREFIX_STRING_LENGTH (sizeof(L"\\DosDevices\\")/sizeof(WCHAR))
#define REQUIRED_QUOTA_ALIGNMENT sizeof(ULONG)
#define ZeroIrpStackLocation(IrpSp)
Functions
VOID IoAcquireCancelSpinLock (OUT PKIRQL Irql)
VOID IoAcquireVpbSpinLock (OUT PKIRQL Irql)
NTSTATUS IoAllocateAdapterChannel (IN PADAPTER_OBJECT AdapterObject, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
VOID IoAllocateController (IN PCONTROLLER_OBJECT ControllerObject, IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
NTSTATUS IoAllocateDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress, IN ULONG DriverObjectExtensionSize, OUT PVOID *DriverObjectExtension)
PVOID IoAllocateErrorLogEntry (IN PVOID IoObject, IN UCHAR EntrySize)
PVOID IoAllocateGenericErrorLogEntry (IN UCHAR EntrySize)
PIRP IoAllocateIrp (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
PMDL IoAllocateMdl (IN PVOID VirtualAddress, IN ULONG Length, IN BOOLEAN SecondaryBuffer, IN BOOLEAN ChargeQuota, IN OUT PIRP Irp OPTIONAL)
NTSTATUS IoAsynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PIO_APC_ROUTINE ApcRoutine, IN PVOID ApcContext, IN IO_PAGING_PRIORITY Priority, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PIRP *Irp OPTIONAL)
NTSTATUS IoAttachDevice (IN PDEVICE_OBJECT SourceDevice, IN PUNICODE_STRING TargetDevice, OUT PDEVICE_OBJECT *AttachedDevice)
NTSTATUS IoAttachDeviceByPointer (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
PDEVICE_OBJECT IoAttachDeviceToDeviceStack (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
NTSTATUS IoAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, IN OUT PDEVICE_OBJECT *AttachedToDeviceObject)
PIRP IoBuildAsynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PIO_STATUS_BLOCK IoStatusBlock OPTIONAL)
PIRP IoBuildDeviceIoControlRequest (IN ULONG IoControlCode, IN PDEVICE_OBJECT DeviceObject, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN InternalDeviceIoControl, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
VOID IoBuildPartialMdl (IN PMDL SourceMdl, IN OUT PMDL TargetMdl, IN PVOID VirtualAddress, IN ULONG Length)
PIRP IoBuildSynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
NTSTATUS IoCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
VOID IoCancelFileOpen (IN PDEVICE_OBJECT DeviceObject, IN PFILE_OBJECT FileObject)
BOOLEAN IoCancelIrp (IN PIRP Irp)
VOID IoCancelThreadIo (IN PETHREAD Thread)
NTSTATUS IoChangeFileObjectFilterContext (IN PFILE_OBJECT FileObject, IN PVOID FilterContext, IN BOOLEAN Set)
NTSTATUS IoCheckDesiredAccess (IN OUT PACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess)
NTSTATUS IoCheckEaBufferValidity (IN PFILE_FULL_EA_INFORMATION EaBuffer, IN ULONG EaLength, OUT PULONG ErrorOffset)
NTSTATUS IoCheckFunctionAccess (IN ACCESS_MASK GrantedAccess, IN UCHAR MajorFunction, IN UCHAR MinorFunction, IN ULONG IoControlCode, IN PVOID Arg1 OPTIONAL, IN PVOID Arg2 OPTIONAL)
NTKERNELAPI NTSTATUS IoCheckQuerySetFileInformation (IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
NTKERNELAPI NTSTATUS IoCheckQuerySetVolumeInformation (IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
NTSTATUS IoCheckQuotaBufferValidity (IN PFILE_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG ErrorOffset)
NTSTATUS IoCheckShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess, IN BOOLEAN Update)
VOID IoCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
NTSTATUS IoComputeDesiredAccessFileObject (IN PFILE_OBJECT FileObject, OUT PNTSTATUS DesiredAccess)
NTSTATUS IoConnectInterrupt (OUT PKINTERRUPT *InterruptObject, IN PKSERVICE_ROUTINE ServiceRoutine, IN PVOID ServiceContext, IN PKSPIN_LOCK SpinLock OPTIONAL, IN ULONG Vector, IN KIRQL Irql, IN KIRQL SynchronizeIrql, IN KINTERRUPT_MODE InterruptMode, IN BOOLEAN ShareVector, IN KAFFINITY ProcessorEnableMask, IN BOOLEAN FloatingSave)
PCONTROLLER_OBJECT IoCreateController (IN ULONG Size)
NTSTATUS IoCreateDevice (IN PDRIVER_OBJECT DriverObject, IN ULONG DeviceExtensionSize, IN PUNICODE_STRING DeviceName OPTIONAL, IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN Exclusive, OUT PDEVICE_OBJECT *DeviceObject)
NTSTATUS IoCreateDriver (IN PUNICODE_STRING DriverName OPTIONAL, IN PDRIVER_INITIALIZE InitializationFunction)
NTSTATUS IoCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options)
NTSTATUS IoCreateFileSpecifyDeviceObjectHint (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN PVOID DeviceObject)
PKEVENT IoCreateNotificationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
PFILE_OBJECT IoCreateStreamFileObject (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
PFILE_OBJECT IoCreateStreamFileObjectEx (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, OUT PHANDLE FileHandle OPTIONAL)
PFILE_OBJECT IoCreateStreamFileObjectLite (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
NTSTATUS IoCreateSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
PKEVENT IoCreateSynchronizationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
NTSTATUS IoCreateUnprotectedSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
VOID IoDeleteController (IN PCONTROLLER_OBJECT ControllerObject)
VOID IoDeleteDevice (IN PDEVICE_OBJECT DeviceObject)
VOID IoDeleteDriver (IN PDRIVER_OBJECT DriverObject)
NTSTATUS IoDeleteSymbolicLink (IN PUNICODE_STRING SymbolicLinkName)
VOID IoDetachDevice (IN OUT PDEVICE_OBJECT TargetDevice)
VOID IoDisconnectInterrupt (IN PKINTERRUPT InterruptObject)
VOID IoEnqueueIrp (IN PIRP Irp)
NTSTATUS IoEnumerateDeviceObjectList (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT *DeviceObjectList, IN ULONG DeviceObjectListSize, OUT PULONG ActualNumberDeviceObjects)
NTSTATUS IoEnumerateRegisteredFiltersList (IN PDRIVER_OBJECT *DriverObjectList, IN ULONG DriverObjectListSize, OUT PULONG ActualNumberDriverObjects)
BOOLEAN IoFastQueryNetworkAttributes (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN ULONG OpenOptions, OUT PIO_STATUS_BLOCK IoStatus, OUT PFILE_NETWORK_OPEN_INFORMATION Buffer)
NTSTATUS FASTCALL IofCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
NTSTATUS FASTCALL IofCallDriverSpecifyReturn (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp, IN PVOID ReturnAddress OPTIONAL)
VOID FASTCALL IofCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
PDEVICE_OBJECT IoFindDeviceThatFailedIrp (IN PIRP Irp)
VOID IoFreeController (IN PCONTROLLER_OBJECT ControllerObject)
VOID IoFreeErrorLogEntry (IN PVOID ElEntry)
VOID IoFreeIrp (IN PIRP Irp)
VOID IoFreeMdl (IN PMDL Mdl)
PDEVICE_OBJECT IoGetAttachedDevice (IN PDEVICE_OBJECT DeviceObject)
PDEVICE_OBJECT IoGetAttachedDeviceReference (IN PDEVICE_OBJECT DeviceObject)
PDEVICE_OBJECT IoGetBaseFileSystemDeviceObject (IN PFILE_OBJECT FileObject)
NTSTATUS IoGetBootDiskInformation (IN OUT PBOOTDISK_INFORMATION BootDiskInformation, IN ULONG Size)
PCONFIGURATION_INFORMATION IoGetConfigurationInformation (VOID)
PEPROCESS IoGetCurrentProcess (VOID)
PDEVICE_OBJECT IoGetDeviceAttachmentBaseRef (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IoGetDeviceObjectPointer (IN PUNICODE_STRING ObjectName, IN ACCESS_MASK DesiredAccess, OUT PFILE_OBJECT *FileObject, OUT PDEVICE_OBJECT *DeviceObject)
PDEVICE_OBJECT IoGetDeviceToVerify (IN PETHREAD Thread)
NTSTATUS IoGetDiskDeviceObject (IN PDEVICE_OBJECT FileSystemDeviceObject, OUT PDEVICE_OBJECT *DiskDeviceObject)
NTKERNELAPI PVOID IoGetDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress)
PVOID IoGetFileObjectFilterContext (IN PFILE_OBJECT FileObject)
PGENERIC_MAPPING IoGetFileObjectGenericMapping (VOID)
PVOID IoGetInitialStack (VOID)
PDEVICE_OBJECT IoGetLowerDeviceObject (IN PDEVICE_OBJECT DeviceObject)
IO_PAGING_PRIORITY FASTCALL IoGetPagingIoPriority (IN PIRP Irp)
PDEVICE_OBJECT IoGetRelatedDeviceObject (IN PFILE_OBJECT FileObject)
PEPROCESS IoGetRequestorProcess (IN PIRP Irp)
ULONG IoGetRequestorProcessId (IN PIRP Irp)
NTSTATUS IoGetRequestorSessionId (IN PIRP Irp, OUT PULONG pSessionId)
VOID IoGetStackLimits (OUT PULONG_PTR LowLimit, OUT PULONG_PTR HighLimit)
PIRP IoGetTopLevelIrp (VOID)
VOID IoInitializeIrp (IN OUT PIRP Irp, IN USHORT PacketSize, IN CCHAR StackSize)
NTSTATUS IoInitializeTimer (IN PDEVICE_OBJECT DeviceObject, IN PIO_TIMER_ROUTINE TimerRoutine, IN PVOID Context)
BOOLEAN IoIsDeviceEjectable (IN PDEVICE_OBJECT DeviceObject)
BOOLEAN IoIsFileOriginRemote (IN PFILE_OBJECT FileObject)
BOOLEAN IoIsOperationSynchronous (IN PIRP Irp)
BOOLEAN IoIsSystemThread (IN PETHREAD Thread)
BOOLEAN IoIsValidNameGraftingBuffer (IN PIRP Irp, IN PREPARSE_DATA_BUFFER ReparseBuffer)
PIRP IoMakeAssociatedIrp (IN PIRP Irp, IN CCHAR StackSize)
NTSTATUS IoPageRead (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
PVOID IopAllocateErrorLogEntry (IN PDEVICE_OBJECT deviceObject, IN PDRIVER_OBJECT driverObject, IN UCHAR EntrySize)
PIRP IopAllocateIrpPrivate (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
PDEVICE_OBJECT IopAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, OUT PDEVICE_OBJECT *AttachedToDeviceObject OPTIONAL)
PSECURITY_DESCRIPTOR IopCreateDefaultDeviceSecurityDescriptor (IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN DeviceHasName, IN PUCHAR Buffer, OUT PACL *AllocatedAcl, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
NTSTATUS IopCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN ULONG InternalFlags, IN PVOID DeviceObject)
NTSTATUS IopCreateSecurityDescriptorPerType (IN PSECURITY_DESCRIPTOR Descriptor, IN ULONG SecurityDescriptorFlavor, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
NTSTATUS IopCreateVpb (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IopDeleteSessionSymLinks (IN PUNICODE_STRING LinkName)
VOID IopDoNameTransmogrify (IN PIRP Irp, IN PFILE_OBJECT FileObject, IN PREPARSE_DATA_BUFFER ReparseBuffer)
VOID FASTCALL IopfCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
VOID IopFreeIrp (IN PIRP Irp)
VOID IopInsertRemoveDevice (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Insert)
VOID IopNotifyAlreadyRegisteredFileSystems (IN PLIST_ENTRY ListHead, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine, IN BOOLEAN SkipRaw)
VOID IopRemoveTimerFromTimerList (IN PIO_TIMER timer)
VOID IopShutdownBaseFileSystems (IN PLIST_ENTRY ListHead)
VOID IopStartNextPacket (IN PDEVICE_OBJECT DeviceObject, IN LOGICAL Cancelable)
VOID IopStartNextPacketByKey (IN PDEVICE_OBJECT DeviceObject, IN LOGICAL Cancelable, IN ULONG Key)
VOID IopStartNextPacketByKeyEx (IN PDEVICE_OBJECT DeviceObject, IN ULONG Key, IN int Flags)
NTSTATUS IopUnloadSafeCompletion (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
NTSTATUS IoQueryFileDosDeviceName (IN PFILE_OBJECT FileObject, OUT POBJECT_NAME_INFORMATION *ObjectNameInformation)
NTSTATUS IoQueryFileInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
NTSTATUS IoQueryVolumeInformation (IN PFILE_OBJECT FileObject, IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, OUT PVOID FsInformation, OUT PULONG ReturnedLength)
VOID IoQueueThreadIrp (IN PIRP Irp)
VOID IoRaiseHardError (IN PIRP Irp, IN PVPB Vpb OPTIONAL, IN PDEVICE_OBJECT RealDeviceObject)
BOOLEAN IoRaiseInformationalHardError (IN NTSTATUS ErrorStatus, IN PUNICODE_STRING String OPTIONAL, IN PKTHREAD Thread OPTIONAL)
VOID IoRegisterBootDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
VOID IoRegisterDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
VOID IoRegisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
NTSTATUS IoRegisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
NTSTATUS IoRegisterLastChanceShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IoRegisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
VOID IoReleaseCancelSpinLock (IN KIRQL Irql)
VOID IoReleaseVpbSpinLock (IN KIRQL Irql)
VOID IoRemoveShareAccess (IN PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
VOID IoRetryIrpCompletions (VOID)
VOID IoReuseIrp (PIRP Irp, NTSTATUS Status)
NTSTATUS IoSetCompletionRoutineEx (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PIO_COMPLETION_ROUTINE CompletionRoutine, IN PVOID Context, IN BOOLEAN InvokeOnSuccess, IN BOOLEAN InvokeOnError, IN BOOLEAN InvokeOnCancel)
VOID IoSetDeviceToVerify (IN PETHREAD Thread, IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IoSetFileOrigin (IN PFILE_OBJECT FileObject, IN BOOLEAN Remote)
VOID IoSetHardErrorOrVerifyDevice (IN PIRP Irp, IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IoSetInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN PVOID FileInformation)
VOID IoSetShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, OUT PSHARE_ACCESS ShareAccess)
VOID IoSetStartIoAttributes (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN DeferredStartIo, IN BOOLEAN NonCancelable)
NTSTATUS IoSetSystemPartition (PUNICODE_STRING VolumeNameString)
BOOLEAN IoSetThreadHardErrorMode (IN BOOLEAN EnableHardErrors)
VOID IoSetTopLevelIrp (IN PIRP Irp)
VOID IoShutdownSystem (IN ULONG Phase)
VOID IoStartNextPacket (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable)
VOID IoStartNextPacketByKey (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable, IN ULONG Key)
VOID IoStartPacket (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PULONG Key OPTIONAL, IN PDRIVER_CANCEL CancelFunction OPTIONAL)
VOID IoStartTimer (IN PDEVICE_OBJECT DeviceObject)
VOID IoStopTimer (IN PDEVICE_OBJECT DeviceObject)
NTSTATUS IoSynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
PEPROCESS IoThreadToProcess (IN PETHREAD Thread)
VOID IoUnregisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
VOID IoUnregisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
VOID IoUnregisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
VOID IoUpdateShareAccess (IN OUT PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
NTSTATUS IoValidateDeviceIoControlAccess (IN PIRP Irp, IN ULONG RequiredAccess)
NTSTATUS IoVerifyVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount)
VOID IoWriteErrorLogEntry (IN OUT PVOID ElEntry)
Variables
static CONFIGURATION_INFORMATION ConfigurationInformation
LOGICAL IoCountOperations = TRUE
LONG IoPageReadIrpAllocationFailure
LONG IoPageReadNonPagefileIrpAllocationFailure
Macro Definition Documentation
#define ALIGN_LONG (Address) ((ULONG) ((Address + 3) & ~3))
Referenced by IoCheckEaBufferValidity().
#define ALIGN_QUAD (Address) ((ULONG) ((Address + 7) & ~7))
#define ArePacketsEquivalent (P1, P2)
Value:
(\
    (P1->ErrorStatus == P2->ErrorStatus) &&                        \
    ((!P1->String.Buffer && !P2->String.Buffer) ||                 \
     ((P1->String.Length == P2->String.Length) &&                  \
      (RtlEqualMemory(P1->String.Buffer,                           \
                        P2->String.Buffer,                         \
                        P1->String.Length))))                      \
)
Referenced by IoRaiseInformationalHardError().
#define GET_OFFSET_LENGTH (CurrentEa, EaBase)
Value:
(\
    (ULONG) ((PCHAR) CurrentEa - (PCHAR) EaBase) )
Referenced by IoCheckEaBufferValidity(), and IoCheckQuotaBufferValidity().
#define GET_OFFSET_LENGTH (CurrentEntry, QuotaBase)
Value:
(\
    (ULONG) ((PCHAR) CurrentEntry - (PCHAR) QuotaBase) )
#define IOP_CREATE_FILE_TIMEOUT 1000
Referenced by IoCreateFile().
#define IopAllocateOpenPacket ()
Value:
ExAllocatePoolWithTag(NonPagedPool,                                     \
                           sizeof(OPEN_PACKET),                              \
                           'pOoI')
Definition at line 137 of file iosubs.c.
Referenced by IopCreateFile().
#define IopFreeOpenPacket (p) ExFreePool(p)
Definition at line 142 of file iosubs.c.
Referenced by IopCreateFile().
#define PREFIX_STRING_LENGTH (sizeof(L"\\DosDevices\\")/sizeof(WCHAR))
Referenced by IopDeleteSessionSymLinks().
#define REQUIRED_QUOTA_ALIGNMENT sizeof(ULONG)
Referenced by IoCheckQuotaBufferValidity().
#define ZeroIrpStackLocation (IrpSp)
Value:
{         \
    (IrpSp)->MinorFunction = 0;                 \
    (IrpSp)->Flags = 0;                         \
    (IrpSp)->Control &= SL_ERROR_RETURNED ;     \
    (IrpSp)->Parameters.Others.Argument1 = 0;   \
    (IrpSp)->Parameters.Others.Argument2 = 0;   \
    (IrpSp)->Parameters.Others.Argument3 = 0;   \
    (IrpSp)->FileObject = (PFILE_OBJECT) NULL; }
Referenced by IopfCompleteRequest().
Function Documentation
VOID IoAcquireCancelSpinLock (OUT PKIRQL Irql)
Definition at line 148 of file iosubs.c.
References KeAcquireQueuedSpinLock(), and LockQueueIoCancelLock.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlNotifySetCancelRoutine(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeFileLock(), FsRtlUninitializeOplock(), FsRtlWaitOnIrp(), IoCancelIrp(), IopStartNextPacket(), IopStartNextPacketByKey(), and IoStartPacket().
VOID IoAcquireVpbSpinLock (OUT PKIRQL Irql)
Definition at line 180 of file iosubs.c.
References KeAcquireQueuedSpinLock(), and LockQueueIoVpbLock.
Referenced by IoGetDiskDeviceObject(), IopMountInitializeVpb(), IopReferenceVerifyVpb(), RawCheckForDismount(), and RawVerifyVolume().
NTSTATUS IoAllocateAdapterChannel (IN PADAPTER_OBJECT AdapterObject, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
Definition at line 214 of file iosubs.c.
References _WAIT_CONTEXT_BLOCK::CurrentIrp, _WAIT_CONTEXT_BLOCK::DeviceContext, _WAIT_CONTEXT_BLOCK::DeviceObject, and HalAllocateAdapterChannel().
VOID IoAllocateController (IN PCONTROLLER_OBJECT ControllerObject, IN PDEVICE_OBJECT DeviceObject, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
Definition at line 285 of file iosubs.c.
References DeallocateObject, IoFreeController(), and KeInsertDeviceQueue().
NTSTATUS IoAllocateDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress, IN ULONG DriverObjectExtensionSize, OUT PVOID * DriverObjectExtension)
Definition at line 373 of file iosubs.c.
References _IO_CLIENT_EXTENSION::ClientIdentificationAddress, ExAllocatePoolWithTag, ExFreePool(), FALSE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, _IO_CLIENT_EXTENSION::NextExtension, NonPagedPool, NULL, RtlZeroMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_COLLISION, STATUS_SUCCESS, and TRUE.
PVOID IoAllocateErrorLogEntry (IN PVOID IoObject, IN UCHAR EntrySize)
Definition at line 473 of file iosubs.c.
References IO_TYPE_DEVICE, IO_TYPE_DRIVER, IopAllocateErrorLogEntry(), and NULL.
Referenced by CcLogError(), IopDisassociateThreadIrp(), IopLogErrorEvent(), and WmipWriteToEventlog().
PVOID IoAllocateGenericErrorLogEntry (IN UCHAR EntrySize)
Definition at line 551 of file iosubs.c.
References IopAllocateErrorLogEntry(), and NULL.
Referenced by CmpLogError(), MmCleanProcessAddressSpace(), MmLoadSystemImage(), and Phase1InitializationDiscard().
PIRP IoAllocateIrp (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
Definition at line 735 of file iosubs.c.
References pIoAllocateIrp.
Referenced by BuildQueryDirectoryIrp(), CcSetValidData(), FsRtlGetFileSize(), FsRtlSetFileSize(), IoAsynchronousPageWrite(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoPageRead(), IopAllocateIrpMustSucceed(), IopDeleteFile(), IopGetFileInformation(), IopGetSetSecurityObject(), IopInitializeReserveIrp(), IopMountVolume(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IoSetInformation(), IoSynchronousPageWrite(), IoVerifyVolume(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipSendWmiIrp(), and WmipSetTraceNotify().
PMDL IoAllocateMdl (IN PVOID VirtualAddress, IN ULONG Length, IN BOOLEAN SecondaryBuffer, IN BOOLEAN ChargeQuota, IN OUT PIRP Irp OPTIONAL)
Definition at line 912 of file iosubs.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, ExAllocateFromPPLookasideList(), ExAllocatePoolWithTag, IOP_FIXED_SIZE_MDL_PFNS, LookasideMdlList, MAXUSHORT, MDL_ALLOCATED_FIXED_SIZE, _MDL::MdlFlags, MmInitializeMdl, _MDL::Next, NonPagedPool, NULL, and UNREFERENCED_PARAMETER.
Referenced by BuildQueryDirectoryIrp(), CcMdlRead(), CcPrepareMdlWrite(), CcZeroData(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopSetEaOrQuotaInformationFile(), IopXxxControlFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryQuotaInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtWriteFile(), and NtWriteFileGather().
NTSTATUS IoAsynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PIO_APC_ROUTINE ApcRoutine, IN PVOID ApcContext, IN IO_PAGING_PRIORITY Priority, OUT PIO_STATUS_BLOCK IoStatusBlock, OUT PIRP *Irp OPTIONAL)
Definition at line 1033 of file iosubs.c.
References APC_LEVEL, ARGUMENT_PRESENT, CcDataFlushes, CcDataPages, CcIsFileCached, _IO_STACK_LOCATION::FileObject, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IoPagingPriorityHigh, IRP_HIGH_PRIORITY_PAGING_IO, IRP_MJ_WRITE, IRP_NOCACHE, IRP_PAGING_IO, KeLowerIrql, KeRaiseIrql, KernelMode, _IO_STACK_LOCATION::MajorFunction, NT_ERROR, PAGE_SHIFT, PAGE_SIZE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), STATUS_INSUFFICIENT_RESOURCES, and STATUS_PENDING.
Referenced by MiFlushSectionInternal(), MiGatherPagefilePages(), and MiMappedPageWriter().
NTSTATUS IoAttachDevice (IN PDEVICE_OBJECT SourceDevice, IN PUNICODE_STRING TargetDevice, OUT PDEVICE_OBJECT * AttachedDevice)
Definition at line 1187 of file iosubs.c.
References FILE_NON_DIRECTORY_FILE, FILE_READ_ATTRIBUTES, InitializeObjectAttributes, IO_ATTACH_DEVICE_API, IoAttachDeviceToDeviceStackSafe(), IoFileObjectType, IoGetRelatedDeviceObject(), KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGED_CODE, VOID, ZwClose(), and ZwOpenFile().
NTSTATUS IoAttachDeviceByPointer (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
Definition at line 1310 of file iosubs.c.
References IoAttachDeviceToDeviceStack(), NULL, STATUS_NO_SUCH_DEVICE, and STATUS_SUCCESS.
PDEVICE_OBJECT IoAttachDeviceToDeviceStack (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice)
Definition at line 1360 of file iosubs.c.
References IopAttachDeviceToDeviceStackSafe(), and NULL.
Referenced by IoAttachDeviceByPointer().
NTSTATUS IoAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, IN OUT PDEVICE_OBJECT * AttachedToDeviceObject)
Definition at line 1397 of file iosubs.c.
References IopAttachDeviceToDeviceStackSafe(), NULL, STATUS_NO_SUCH_DEVICE, and STATUS_SUCCESS.
Referenced by IoAttachDevice().
PIRP IoBuildAsynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PIO_STATUS_BLOCK IoStatusBlock OPTIONAL)
Definition at line 1569 of file iosubs.c.
References DO_BUFFERED_IO, DO_DIRECT_IO, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, IoAllocateIrp(), IoAllocateMdl(), IoFreeIrp(), IoFreeMdl(), IoGetNextIrpStackLocation, IoReadAccess, IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_FLUSH_BUFFERS, IRP_MJ_PNP, IRP_MJ_POWER, IRP_MJ_READ, IRP_MJ_SHUTDOWN, IRP_MJ_WRITE, KernelMode, _IO_STACK_LOCATION::MajorFunction, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NULL, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and RtlCopyMemory.
Referenced by IoBuildSynchronousFsdRequest().
PIRP IoBuildDeviceIoControlRequest (IN ULONG IoControlCode, IN PDEVICE_OBJECT DeviceObject, IN PVOID InputBuffer OPTIONAL, IN ULONG InputBufferLength, OUT PVOID OutputBuffer OPTIONAL, IN ULONG OutputBufferLength, IN BOOLEAN InternalDeviceIoControl, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 1762 of file iosubs.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), IoAllocateIrp(), IoAllocateMdl(), IoFreeIrp(), IoFreeMdl(), IoGetNextIrpStackLocation, IopQueueThreadIrp(), IoReadAccess, IoWriteAccess, IRP_BUFFERED_IO, IRP_DEALLOCATE_BUFFER, IRP_INPUT_OPERATION, IRP_MJ_DEVICE_CONTROL, IRP_MJ_INTERNAL_DEVICE_CONTROL, KernelMode, _IO_STACK_LOCATION::MajorFunction, METHOD_BUFFERED, METHOD_IN_DIRECT, METHOD_NEITHER, METHOD_OUT_DIRECT, MmProbeAndLockPages(), NonPagedPoolCacheAligned, NULL, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and RtlCopyMemory.
Referenced by FsRtlBalanceReads(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoGetBootDiskInformation(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopGetSetObjectId(), IopGetVolumeId(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopSetRemoteLink(), IoVolumeDeviceToDosName(), RawQueryFsSizeInfo(), and xHalGetPartialGeometry().
VOID IoBuildPartialMdl (IN PMDL SourceMdl, IN OUT PMDL TargetMdl, IN PVOID VirtualAddress, IN ULONG Length)
Definition at line 2014 of file iosubs.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, BYTE_OFFSET, KeBugCheck(), MDL_ALLOCATED_FIXED_SIZE, MDL_ALLOCATED_MUST_SUCCEED, MDL_IO_PAGE_READ, MDL_IO_SPACE, MDL_MAPPED_TO_SYSTEM_VA, MDL_PARENT_MAPPED_SYSTEM_VA, MDL_PARTIAL, MDL_SOURCE_IS_NONPAGED_POOL, MmGetMdlBaseVa, MmGetMdlByteCount, MmGetMdlByteOffset, MmGetMdlPfnArray, PAGE_ALIGN, PAGE_SHIFT, and TARGET_MDL_TOO_SMALL.
PIRP IoBuildSynchronousFsdRequest (IN ULONG MajorFunction, IN PDEVICE_OBJECT DeviceObject, IN OUT PVOID Buffer OPTIONAL, IN ULONG Length OPTIONAL, IN PLARGE_INTEGER StartingOffset OPTIONAL, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 2143 of file iosubs.c.
References IoBuildAsynchronousFsdRequest(), IopQueueThreadIrp(), NULL, and PIRP.
Referenced by HalExamineMBR(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopShutdownBaseFileSystems(), IoReadPartitionTable(), IoSetPartitionInformation(), IoShutdownSystem(), IoWritePartitionTable(), and WmipGetDevicePDO().
NTSTATUS IoCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
Definition at line 15028 of file iosubs.c.
References IofCallDriver().
Referenced by CcSetValidData(), FsRtlBalanceReads(), FsRtlGetFileSize(), FsRtlSetFileSize(), HalExamineMBR(), HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpGetFullGeometry(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoAsynchronousPageWrite(), IoCancelFileOpen(), IoGetBootDiskInformation(), IoPageRead(), IopCloseFile(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), IopDeleteFile(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopInvalidateVolumesForDevice(), IopLoadFileSystemDriver(), IopMountVolume(), IopParseDevice(), IopQueryXxxInformation(), IopSetRemoteLink(), IopShutdownBaseFileSystems(), IopSynchronousServiceTail(), IoReadPartitionTable(), IoSetInformation(), IoSetPartitionInformation(), IoShutdownSystem(), IoSynchronousPageWrite(), IoVerifyVolume(), IoVolumeDeviceToDosName(), IoWMISystemControl(), IoWritePartitionTable(), NtQueryInformationFile(), NtSetInformationFile(), RawQueryFsSizeInfo(), RawReadWriteDeviceControl(), WmipForwardWmiIrp(), WmipGetDevicePDO(), and xHalGetPartialGeometry().
VOID IoCancelFileOpen (IN PDEVICE_OBJECT DeviceObject, IN PFILE_OBJECT FileObject)
Definition at line 13582 of file iosubs.c.
References APC_LEVEL, ASSERT, _IO_STACK_LOCATION::FileObject, FO_FILE_OPEN_CANCELLED, FO_HANDLE_CREATED, INVALID_CANCEL_OF_FILE_OPEN, IoCallDriver(), IoFreeIrp(), IoGetNextIrpStackLocation, IopAllocateIrpMustSucceed(), IopDequeueThreadIrp, IopQueueThreadIrp(), IRP_CLOSE_OPERATION, IRP_MJ_CLEANUP, IRP_SYNCHRONOUS_API, KeBugCheckEx(), KeClearEvent(), KeInitializeEvent(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, NULL, PIRP, PsGetCurrentThread(), STATUS_PENDING, SynchronizationEvent, UserRequest, and VOID.
BOOLEAN IoCancelIrp (IN PIRP Irp)
Definition at line 2278 of file iosubs.c.
References ASSERT, CANCEL_STATE_IN_COMPLETED_IRP, InterlockedExchangePointer, IO_TYPE_IRP, IoAcquireCancelSpinLock(), IopVerifierOn, IoReleaseCancelSpinLock(), IOV_CANCEL_IRP, KeBugCheckEx(), NULL, and TRUE.
Referenced by IoCancelThreadIo(), IopCancelAlertedRequest(), and NtCancelIoFile().
VOID IoCancelThreadIo (IN PETHREAD Thread)
Definition at line 2373 of file iosubs.c.
References APC_LEVEL, CONTAINING_RECORD, DBG_UNREFERENCED_PARAMETER, _LIST_ENTRY::Flink, IoCancelIrp(), IopDisassociateThreadIrp(), IRP, _ETHREAD::IrpList, IsListEmpty, KeDelayExecutionThread(), KeLowerIrql, KeRaiseIrql, KernelMode, PAGED_CODE, PIRP, PsGetCurrentThread(), and _LARGE_INTEGER::QuadPart.
Referenced by PspExitThread().
NTSTATUS IoChangeFileObjectFilterContext (IN PFILE_OBJECT FileObject, IN PVOID FilterContext, IN BOOLEAN Set)
Definition at line 14714 of file iosubs.c.
References _IOP_FILE_OBJECT_EXTENSION::FilterContext, FO_FILE_OBJECT_HAS_EXTENSION, InterlockedCompareExchangePointer, NULL, STATUS_ALREADY_COMMITTED, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by FsRtlInsertPerFileObjectContext(), and FsRtlPTeardownPerFileObjectContexts().
NTSTATUS IoCheckDesiredAccess (IN OUT PACCESS_MASK DesiredAccess, IN ACCESS_MASK GrantedAccess)
Definition at line 2476 of file iosubs.c.
References _OBJECT_TYPE_INITIALIZER::GenericMapping, IoFileObjectType, PAGED_CODE, RtlMapGenericMask(), SeComputeDeniedAccesses, STATUS_ACCESS_DENIED, STATUS_SUCCESS, and _OBJECT_TYPE::TypeInfo.
NTSTATUS IoCheckEaBufferValidity (IN PFILE_FULL_EA_INFORMATION EaBuffer, IN ULONG EaLength, OUT PULONG ErrorOffset)
Definition at line 2528 of file iosubs.c.
References ALIGN_LONG, _FILE_FULL_EA_INFORMATION::EaName, _FILE_FULL_EA_INFORMATION::EaNameLength, _FILE_FULL_EA_INFORMATION::EaValueLength, FIELD_OFFSET, GET_OFFSET_LENGTH, _FILE_FULL_EA_INFORMATION::NextEntryOffset, PAGED_CODE, STATUS_EA_LIST_INCONSISTENT, and STATUS_SUCCESS.
Referenced by IopCreateFile(), IopSetEaOrQuotaInformationFile(), and NtSetEaFile().
NTSTATUS IoCheckFunctionAccess (IN ACCESS_MASK GrantedAccess, IN UCHAR MajorFunction, IN UCHAR MinorFunction, IN ULONG IoControlCode, IN PVOID Arg1 OPTIONAL, IN PVOID Arg2 OPTIONAL)
Definition at line 2683 of file iosubs.c.
References FILE_ANY_ACCESS, FILE_APPEND_DATA, FILE_LIST_DIRECTORY, FILE_READ_DATA, FILE_READ_EA, FILE_WRITE_DATA, FILE_WRITE_EA, IopQueryFsOperationAccess, IopQueryOperationAccess, IopSetFsOperationAccess, IopSetOperationAccess, IRP_MJ_CLOSE, IRP_MJ_CREATE, IRP_MJ_DEVICE_CONTROL, IRP_MJ_DIRECTORY_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MJ_FLUSH_BUFFERS, IRP_MJ_INTERNAL_DEVICE_CONTROL, IRP_MJ_LOCK_CONTROL, IRP_MJ_QUERY_EA, IRP_MJ_QUERY_INFORMATION, IRP_MJ_QUERY_SECURITY, IRP_MJ_QUERY_VOLUME_INFORMATION, IRP_MJ_READ, IRP_MJ_SET_EA, IRP_MJ_SET_INFORMATION, IRP_MJ_SET_SECURITY, IRP_MJ_SET_VOLUME_INFORMATION, IRP_MJ_WRITE, PAGED_CODE, SeComputeDeniedAccesses, SeComputeGrantedAccesses, SeQuerySecurityAccessMask(), SeSetSecurityAccessMask(), STATUS_ACCESS_DENIED, STATUS_INVALID_DEVICE_REQUEST, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
NTKERNELAPI NTSTATUS IoCheckQuerySetFileInformation (IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
Definition at line 2896 of file iosubs.c.
References FileMaximumInformation, IopQueryOperationLength, IopSetOperationLength, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and STATUS_SUCCESS.
NTKERNELAPI NTSTATUS IoCheckQuerySetVolumeInformation (IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, IN BOOLEAN SetOperation)
Definition at line 2961 of file iosubs.c.
References FileFsMaximumInformation, IopQueryFsOperationLength, IopSetFsOperationLength, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and STATUS_SUCCESS.
NTSTATUS IoCheckQuotaBufferValidity (IN PFILE_QUOTA_INFORMATION QuotaBuffer, IN ULONG QuotaLength, OUT PULONG ErrorOffset)
Definition at line 3020 of file iosubs.c.
References FIELD_OFFSET, GET_OFFSET_LENGTH, _FILE_QUOTA_INFORMATION::NextEntryOffset, PAGED_CODE, REQUIRED_QUOTA_ALIGNMENT, RtlLengthSid(), RtlValidSid(), _FILE_QUOTA_INFORMATION::Sid, _FILE_QUOTA_INFORMATION::SidLength, STATUS_DATATYPE_MISALIGNMENT, STATUS_QUOTA_LIST_INCONSISTENT, and STATUS_SUCCESS.
Referenced by IopSetEaOrQuotaInformationFile().
NTSTATUS IoCheckShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess, IN BOOLEAN Update)
Definition at line 3178 of file iosubs.c.
References DELETE, FILE_APPEND_DATA, FILE_EXECUTE, FILE_READ_DATA, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_DATA, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, PAGED_CODE, STATUS_SHARING_VIOLATION, and STATUS_SUCCESS.
Referenced by RawCreate().
VOID IoCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
Definition at line 15041 of file iosubs.c.
References IofCompleteRequest().
Referenced by IopfCompleteRequest(), IopInvalidDeviceRequest(), IopRaiseHardError(), IopStartApcHardError(), IoRaiseHardError(), IoSetInformation(), IoWMICompleteRequest(), IoWMISystemControl(), WmipCompleteGuidIrpWithError(), WmipDeleteMethod(), WmipIoControl(), WmipNotificationIrpCancel(), WmipOpenCloseCleanup(), WmipShutdown(), and WmipWriteWnodeToObject().
NTSTATUS IoComputeDesiredAccessFileObject (IN PFILE_OBJECT FileObject, OUT PNTSTATUS DesiredAccess)
Definition at line 7847 of file iosubs.c.
References FILE_APPEND_DATA, FILE_WRITE_DATA, FO_NAMED_PIPE, IoFileObjectType, NULL, OBJECT_TO_OBJECT_HEADER, Status, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, and _OBJECT_HEADER::Type.
Referenced by ObReferenceFileObjectForWrite().
NTSTATUS IoConnectInterrupt (OUT PKINTERRUPT * InterruptObject, IN PKSERVICE_ROUTINE ServiceRoutine, IN PVOID ServiceContext, IN PKSPIN_LOCK SpinLock OPTIONAL, IN ULONG Vector, IN KIRQL Irql, IN KIRQL SynchronizeIrql, IN KINTERRUPT_MODE InterruptMode, IN BOOLEAN ShareVector, IN KAFFINITY ProcessorEnableMask, IN BOOLEAN FloatingSave)
Definition at line 3862 of file iosubs.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, ExFreePool(), FALSE, _IO_INTERRUPT_STRUCTURE::InterruptArray, _IO_INTERRUPT_STRUCTURE::InterruptObject, IoDisconnectInterrupt(), KeActiveProcessors, KeConnectInterrupt(), KeInitializeInterrupt(), NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, RtlZeroMemory, _IO_INTERRUPT_STRUCTURE::SpinLock, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
PCONTROLLER_OBJECT IoCreateController (IN ULONG Size)
Definition at line 4115 of file iosubs.c.
References _CONTROLLER_OBJECT::ControllerExtension, _CONTROLLER_OBJECT::DeviceWaitQueue, FILE_READ_DATA, FILE_WRITE_DATA, InitializeObjectAttributes, IO_TYPE_CONTROLLER, IoControllerObjectType, KeInitializeDeviceQueue(), KernelMode, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObInsertObject(), OBJ_KERNEL_HANDLE, PAGED_CODE, RtlZeroMemory, _CONTROLLER_OBJECT::Size, _CONTROLLER_OBJECT::Type, and VOID.
NTSTATUS IoCreateDevice (IN PDRIVER_OBJECT DriverObject, IN ULONG DeviceExtensionSize, IN PUNICODE_STRING DeviceName OPTIONAL, IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN Exclusive, OUT PDEVICE_OBJECT * DeviceObject)
Definition at line 4276 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, _OBJECT_ATTRIBUTES::Attributes, DEVICE_OBJECT, _DEVOBJ_EXTENSION::DeviceObject, DO_DEVICE_HAS_NAME, DO_DEVICE_INITIALIZING, DO_EXCLUSIVE, DRVO_UNLOAD_INVOKED, ExFreePool(), FALSE, FILE_AUTOGENERATED_DEVICE_NAME, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_DEVICE_VIRTUAL_DISK, FILE_READ_DATA, FILE_WRITE_DATA, HalGetDmaAlignmentRequirement, InitializeListHead(), InitializeObjectAttributes, InterlockedIncrement, IO_TYPE_DEVICE, IO_TYPE_DEVICE_OBJECT_EXTENSION, IoDeviceObjectType, IopCreateDefaultDeviceSecurityDescriptor(), IopCreateVpb(), IopInsertRemoveDevice(), IopUniqueDeviceObjectNumber, KeInitializeDeviceQueue(), KeInitializeEvent(), KernelMode, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_EXCLUSIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, ObReferenceObject, PAGED_CODE, PoInitializeDeviceObject(), PoVolumeDevice(), RtlInitUnicodeString(), RtlZeroMemory, SECURITY_DESCRIPTOR_MIN_LENGTH, _DEVOBJ_EXTENSION::Size, STATUS_OBJECT_NAME_COLLISION, swprintf, SynchronizationEvent, TRUE, _DEVOBJ_EXTENSION::Type, and VOID.
Referenced by RawInitialize(), RawMountVolume(), and WmipDriverEntry().
NTSTATUS IoCreateDriver (IN PUNICODE_STRING DriverName OPTIONAL, IN PDRIVER_INITIALIZE InitializationFunction)
Definition at line 14012 of file iosubs.c.
References _snwprintf, _UNICODE_STRING::Buffer, _DRIVER_OBJECT::DriverExtension, _DRIVER_OBJECT::DriverInit, _DRIVER_OBJECT::DriverName, _DRIVER_EXTENSION::DriverObject, DRVO_BUILTIN_DRIVER, ExAllocatePool, FILE_READ_DATA, _DRIVER_OBJECT::Flags, InitializeObjectAttributes, IO_TYPE_DRIVER, IoDriverObjectType, IopInvalidDeviceRequest(), IRP_MJ_MAXIMUM_FUNCTION, KernelMode, KiQueryLowTickCount, _UNICODE_STRING::Length, _DRIVER_OBJECT::MajorFunction, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, ObMakeTemporaryObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, RtlCopyMemory, RtlZeroMemory, _DRIVER_EXTENSION::ServiceKeyName, _DRIVER_OBJECT::Size, STATUS_INSUFFICIENT_RESOURCES, _DRIVER_OBJECT::Type, UNICODE_NULL, ZwClose(), and ZwMakeTemporaryObject().
NTSTATUS IoCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options)
Definition at line 4716 of file iosubs.c.
References ASSERT, ExHotpSyncRenameSequence, ExSyncRenameOwner, IOP_CREATE_FILE_TIMEOUT, IopCreateFile(), KeDelayExecutionThread(), KeGetCurrentThread(), KernelMode, NT_SUCCESS, NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, and STATUS_SUCCESS.
Referenced by IopOpenLinkOrRenameTarget(), NtCreateFile(), NtCreateMailslotFile(), NtCreateNamedPipeFile(), NtCreatePagingFile(), and NtOpenFile().
NTSTATUS IoCreateFileSpecifyDeviceObjectHint (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN PVOID DeviceObject)
Definition at line 4898 of file iosubs.c.
References IO_IGNORE_SHARE_ACCESS_CHECK, IO_NO_PARAMETER_CHECKING, IOP_CREATE_DEVICE_OBJECT_EXTENSION, IOP_CREATE_IGNORE_SHARE_ACCESS_CHECK, IOP_CREATE_USE_TOP_DEVICE_OBJECT_HINT, IopCreateFile(), and NULL.
Referenced by IopOpenLinkOrRenameTarget().
PKEVENT IoCreateNotificationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
Definition at line 5779 of file iosubs.c.
References EVENT_ALL_ACCESS, ExEventObjectType, InitializeObjectAttributes, KernelMode, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, OBJ_OPENIF, ObReferenceObjectByHandle, PAGED_CODE, TRUE, VOID, and ZwCreateEvent().
PFILE_OBJECT IoCreateStreamFileObject (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
Definition at line 5858 of file iosubs.c.
References IoCreateStreamFileObjectEx(), and NULL.
PFILE_OBJECT IoCreateStreamFileObjectEx (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL, OUT PHANDLE FileHandle OPTIONAL)
Definition at line 5868 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExRaiseStatus(), FILE_READ_DATA, _FILE_OBJECT::Flags, FO_HANDLE_CREATED, FO_STREAM_FILE, InitializeObjectAttributes, IO_TYPE_FILE, IoFileObjectType, IopDecrementDeviceObjectRef(), IopInterlockedIncrementUlong(), KeInitializeEvent(), KernelMode, LockQueueIoDatabaseLock, LockQueueIoVpbLock, NT_SUCCESS, NULL, ObCloseHandle(), ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_KERNEL_HANDLE, PAGED_CODE, RtlZeroMemory, _FILE_OBJECT::Size, SynchronizationEvent, and _FILE_OBJECT::Type.
Referenced by IoCreateStreamFileObject().
PFILE_OBJECT IoCreateStreamFileObjectLite (IN PFILE_OBJECT FileObject OPTIONAL, IN PDEVICE_OBJECT DeviceObject OPTIONAL)
Definition at line 6038 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, _FILE_OBJECT::DeviceObject, _FILE_OBJECT::Event, ExRaiseStatus(), _FILE_OBJECT::Flags, FO_HANDLE_CREATED, FO_STREAM_FILE, InitializeObjectAttributes, IO_TYPE_FILE, IoFileObjectType, IopDecrementDeviceObjectRef(), IopInterlockedIncrementUlong(), KeInitializeEvent(), KernelMode, LockQueueIoDatabaseLock, LockQueueIoVpbLock, NT_SUCCESS, NULL, ObCreateObject, ObFreeObjectCreateInfoBuffer(), OBJECT_TO_OBJECT_HEADER, PAGED_CODE, RtlZeroMemory, _FILE_OBJECT::Size, SynchronizationEvent, and _FILE_OBJECT::Type.
Referenced by IopInvalidateVolumesForDevice(), and RawMountVolume().
NTSTATUS IoCreateSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
Definition at line 6174 of file iosubs.c.
References InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, PAGED_CODE, SePublicDefaultUnrestrictedSd, SYMBOLIC_LINK_ALL_ACCESS, ZwClose(), and ZwCreateSymbolicLinkObject().
Referenced by FsRtlpSetSymbolicLink(), HalpNextDriveLetter(), IoAssignDriveLetters(), IopCreateArcNames(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), and WmipDriverEntry().
PKEVENT IoCreateSynchronizationEvent (IN PUNICODE_STRING EventName, OUT PHANDLE EventHandle)
Definition at line 6232 of file iosubs.c.
References EVENT_ALL_ACCESS, ExEventObjectType, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, OBJ_OPENIF, ObReferenceObjectByHandle, PAGED_CODE, SynchronizationEvent, TRUE, VOID, and ZwCreateEvent().
NTSTATUS IoCreateUnprotectedSymbolicLink (IN PUNICODE_STRING SymbolicLinkName, IN PUNICODE_STRING DeviceName)
Definition at line 6312 of file iosubs.c.
References InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_PERMANENT, PAGED_CODE, SYMBOLIC_LINK_ALL_ACCESS, ZwClose(), and ZwCreateSymbolicLinkObject().
VOID IoDeleteController (IN PCONTROLLER_OBJECT ControllerObject)
Definition at line 6380 of file iosubs.c.
References ObDereferenceObject(), and PAGED_CODE.
VOID IoDeleteDevice (IN PDEVICE_OBJECT DeviceObject)
Definition at line 6437 of file iosubs.c.
References DO_DEVICE_HAS_NAME, DO_SHUTDOWN_REGISTERED, DOE_DELETE_PENDING, ExFreePool(), IopCompleteUnloadOrDelete(), IopRemoveTimerFromTimerList(), IoUnregisterShutdownNotification(), IOV_DELETE_DEVICE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, ObMakeTemporaryObject(), and PoRunDownDeviceObject().
Referenced by RawCheckForDismount(), RawInitialize(), RawMountVolume(), RawShutdown(), and WmipDriverEntry().
VOID IoDeleteDriver (IN PDRIVER_OBJECT DriverObject)
Definition at line 14205 of file iosubs.c.
References ObDereferenceObject().
NTSTATUS IoDeleteSymbolicLink (IN PUNICODE_STRING SymbolicLinkName)
Definition at line 6715 of file iosubs.c.
References DELETE, ExVerifySuite(), InitializeObjectAttributes, IopDeleteSessionSymLinks(), NT_SUCCESS, NULL, ObIsLUIDDeviceMapsEnabled(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, TerminalServer, TRUE, ZwClose(), ZwMakeTemporaryObject(), and ZwOpenSymbolicLinkObject().
Referenced by FsRtlpSetSymbolicLink(), and WmipDriverEntry().
VOID IoDetachDevice (IN OUT PDEVICE_OBJECT TargetDevice)
Definition at line 6796 of file iosubs.c.
References ASSERT, _DEVOBJ_EXTENSION::AttachedTo, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_UNLOAD_PENDING, IopCompleteUnloadOrDelete(), IOV_DETACH_DEVICE, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
VOID IoDisconnectInterrupt (IN PKINTERRUPT InterruptObject)
Definition at line 6862 of file iosubs.c.
References CONTAINING_RECORD, ExFreePool(), _IO_INTERRUPT_STRUCTURE::InterruptArray, _IO_INTERRUPT_STRUCTURE::InterruptObject, KeDisconnectInterrupt(), MAXIMUM_PROCESSORS, NULL, and PAGED_CODE.
Referenced by IoConnectInterrupt().
VOID IoEnqueueIrp (IN PIRP Irp)
Definition at line 6927 of file iosubs.c.
References IopQueueThreadIrp(), and PAGED_CODE.
NTSTATUS IoEnumerateDeviceObjectList (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT * DeviceObjectList, IN ULONG DeviceObjectListSize, OUT PULONG ActualNumberDeviceObjects)
Definition at line 14279 of file iosubs.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, ObReferenceObject, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
NTSTATUS IoEnumerateRegisteredFiltersList (IN PDRIVER_OBJECT * DriverObjectList, IN ULONG DriverObjectListSize, OUT PULONG ActualNumberDriverObjects)
Definition at line 14924 of file iosubs.c.
References CONTAINING_RECORD, _NOTIFICATION_PACKET::DriverObject, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, IopDatabaseResource, IopFsNotifyChangeQueueHead, ObReferenceObject, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and TRUE.
BOOLEAN IoFastQueryNetworkAttributes (IN POBJECT_ATTRIBUTES ObjectAttributes, IN ACCESS_MASK DesiredAccess, IN ULONG OpenOptions, OUT PIO_STATUS_BLOCK IoStatus, OUT PFILE_NETWORK_OPEN_INFORMATION Buffer)
Definition at line 6961 of file iosubs.c.
References _OPEN_PACKET::CreateOptions, _OPEN_PACKET::Disposition, FILE_OPEN, FILE_OPEN_REPARSE_POINT, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, _OPEN_PACKET::FinalStatus, _OPEN_PACKET::FullAttributes, _OPEN_PACKET::Information, IO_FORCE_ACCESS_CHECK, IO_TYPE_OPEN_PACKET, KernelMode, _OPEN_PACKET::LocalFileObject, _OPEN_PACKET::NetworkInformation, NT_SUCCESS, NULL, ObOpenObjectByName(), OPEN_PACKET_PATTERN, _OPEN_PACKET::Options, _OPEN_PACKET::ParseCheck, _OPEN_PACKET::QueryOnly, RtlZeroMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_OBJECT_TYPE_MISMATCH, TRUE, _OPEN_PACKET::Type, and ZwClose().
NTSTATUS FASTCALL IofCallDriver (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp)
Definition at line 2239 of file iosubs.c.
References IopfCallDriver(), NULL, and pIofCallDriver.
Referenced by IoCallDriver().
NTSTATUS FASTCALL IofCallDriverSpecifyReturn (IN PDEVICE_OBJECT DeviceObject, IN OUT PIRP Irp, IN PVOID ReturnAddress OPTIONAL)
Definition at line 2258 of file iosubs.c.
References IopfCallDriver(), NULL, and pIofCallDriver.
VOID FASTCALL IofCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
Definition at line 3325 of file iosubs.c.
References pIofCompleteRequest.
Referenced by IoCompleteRequest().
PDEVICE_OBJECT IoFindDeviceThatFailedIrp (IN PIRP Irp)
Definition at line 14878 of file iosubs.c.
References _IO_STACK_LOCATION::Control, _IO_STACK_LOCATION::DeviceObject, IRP, NT_SUCCESS, NULL, and SL_ERROR_RETURNED.
VOID IoFreeController (IN PCONTROLLER_OBJECT ControllerObject)
Definition at line 7077 of file iosubs.c.
References CONTAINING_RECORD, DeallocateObject, DEVICE_OBJECT, KeRemoveDeviceQueue(), and NULL.
Referenced by IoAllocateController().
VOID IoFreeErrorLogEntry (IN PVOID ElEntry)
Definition at line 688 of file iosubs.c.
References _ERROR_LOG_ENTRY::DeviceObject, _ERROR_LOG_ENTRY::DriverObject, ExFreePool(), InterlockedExchangeAdd(), IopErrorLogAllocation, NULL, ObDereferenceObject(), and _ERROR_LOG_ENTRY::Size.
VOID IoFreeIrp (IN PIRP Irp)
Definition at line 7135 of file iosubs.c.
References pIoFreeIrp.
Referenced by IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IoCancelFileOpen(), IopCloseFile(), IopCompletePageWrite(), IopCompleteRequest(), IopDeleteFile(), IopDeleteIoCompletion(), IopDropIrp(), IopExceptionCleanup(), IopfCompleteRequest(), IopFreeIrpAndMdls(), IopParseDevice(), IopUserCompletion(), IopUserRundown(), NtRemoveIoCompletion(), WmipDisableKernelTrace(), WmipEnableKernelTrace(), WmipSendWmiIrp(), and WmipSetTraceNotify().
VOID IoFreeMdl (IN PMDL Mdl)
Definition at line 7260 of file iosubs.c.
References ExFreePool(), ExFreeToPPLookasideList(), LookasideMdlList, MDL_ALLOCATED_FIXED_SIZE, MDL_ALLOCATED_MUST_SUCCEED, and MmPrepareMdlForReuse.
Referenced by CcMdlRead(), CcMdlReadComplete2(), CcMdlWriteAbort(), CcMdlWriteComplete2(), CcPrepareMdlWrite(), CcZeroData(), IoBuildAsynchronousFsdRequest(), IoBuildDeviceIoControlRequest(), IopCompleteRequest(), IopDropIrp(), IopExceptionCleanup(), and IopFreeIrpAndMdls().
PDEVICE_OBJECT IoGetAttachedDevice (IN PDEVICE_OBJECT DeviceObject)
Definition at line 7301 of file iosubs.c.
Referenced by IoGetAttachedDeviceReference(), IoGetRelatedDeviceObject(), IopAttachDeviceToDeviceStackSafe(), IopCloseFile(), IopDeleteFile(), IopParseDevice(), IopShutdownBaseFileSystems(), IopXxxControlFile(), NtQueryInformationFile(), NtSetInformationFile(), and NtUnlockFile().
PDEVICE_OBJECT IoGetAttachedDeviceReference (IN PDEVICE_OBJECT DeviceObject)
Definition at line 7344 of file iosubs.c.
References IoGetAttachedDevice(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and ObReferenceObject.
Referenced by HalpIsOldStyleFloppy(), HalpQueryDriveLayout(), HalpQueryPartitionType(), IopComputeHarddiskDerangements(), IoShutdownSystem(), and WmipForwardWmiIrp().
PDEVICE_OBJECT IoGetBaseFileSystemDeviceObject (IN PFILE_OBJECT FileObject)
Definition at line 7377 of file iosubs.c.
References ASSERT, FO_DIRECT_DEVICE_OPEN, and NULL.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlMdlRead(), FsRtlMdlReadComplete(), FsRtlMdlWriteComplete(), FsRtlPrepareMdlWrite(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTSTATUS IoGetBootDiskInformation (IN OUT PBOOTDISK_INFORMATION BootDiskInformation, IN ULONG Size)
Definition at line 12810 of file iosubs.c.
References _LOADER_PARAMETER_BLOCK::ArcBootDeviceName, _LOADER_PARAMETER_BLOCK::ArcDiskInformation, _LOADER_PARAMETER_BLOCK::ArcHalDeviceName, _ARC_DISK_SIGNATURE::ArcName, _BOOTDISK_INFORMATION_EX::BootDeviceGuid, _BOOTDISK_INFORMATION_EX::BootDeviceIsGpt, _DISK_GEOMETRY::BytesPerSector, CONTAINING_RECORD, _CONFIGURATION_INFORMATION::DiskCount, _ARC_DISK_INFORMATION::DiskSignatures, ExFreePool(), FALSE, FILE_READ_ATTRIBUTES, _LIST_ENTRY::Flink, IoBuildDeviceIoControlRequest(), IoCallDriver(), IOCTL_DISK_GET_DRIVE_GEOMETRY, IoGetConfigurationInformation(), IoGetDeviceObjectPointer(), IopLoaderBlock, IopVerifyDiskSignature(), IoReadPartitionTableEx(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, PIRP, RtlAnsiStringToUnicodeString(), RtlEqualString(), RtlFreeUnicodeString(), RtlInitAnsiString(), sprintf(), _IO_STATUS_BLOCK::Status, STATUS_INVALID_PARAMETER, STATUS_PENDING, STATUS_SUCCESS, STATUS_TOO_LATE, Suspended, _BOOTDISK_INFORMATION_EX::SystemDeviceGuid, _BOOTDISK_INFORMATION_EX::SystemDeviceIsGpt, and TRUE.
PCONFIGURATION_INFORMATION IoGetConfigurationInformation (VOID)
Definition at line 7442 of file iosubs.c.
References PAGED_CODE.
Referenced by IoAssignDriveLetters(), IoGetBootDiskInformation(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), and NtQuerySystemInformation().
PEPROCESS IoGetCurrentProcess (VOID)
Definition at line 7475 of file iosubs.c.
References PsGetCurrentProcess().
PDEVICE_OBJECT IoGetDeviceAttachmentBaseRef (IN PDEVICE_OBJECT DeviceObject)
Definition at line 14348 of file iosubs.c.
References IopGetDeviceAttachmentBase(), KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and ObReferenceObject.
Referenced by FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), and FsRtlReleaseFileForModWrite().
NTSTATUS IoGetDeviceObjectPointer (IN PUNICODE_STRING ObjectName, IN ACCESS_MASK DesiredAccess, OUT PFILE_OBJECT * FileObject, OUT PDEVICE_OBJECT * DeviceObject)
Definition at line 7513 of file iosubs.c.
References FILE_NON_DIRECTORY_FILE, InitializeObjectAttributes, IoFileObjectType, IoGetRelatedDeviceObject(), KernelMode, NT_SUCCESS, NULL, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGED_CODE, VOID, ZwClose(), and ZwOpenFile().
Referenced by HalpDeleteMountLetter(), HalpEnableAutomaticDriveLetterAssignment(), HalpIsOldStyleFloppy(), HalpNextMountLetter(), HalpQueryDriveLayout(), HalpQueryPartitionType(), HalpSetMountLetter(), IoGetBootDiskInformation(), IopComputeHarddiskDerangements(), IopCreateArcNamesCd(), IopCreateArcNamesDisk(), and IoVolumeDeviceToDosName().
PDEVICE_OBJECT IoGetDeviceToVerify (IN PETHREAD Thread)
Definition at line 7608 of file iosubs.c.
NTSTATUS IoGetDiskDeviceObject (IN PDEVICE_OBJECT FileSystemDeviceObject, OUT PDEVICE_OBJECT * DiskDeviceObject)
Definition at line 14403 of file iosubs.c.
References _VPB::Flags, IoAcquireVpbSpinLock(), IoReleaseVpbSpinLock(), ObReferenceObject, _VPB::RealDevice, _VPB::ReferenceCount, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_VOLUME_DISMOUNTED, and VPB_MOUNTED.
NTKERNELAPI PVOID IoGetDriverObjectExtension (IN PDRIVER_OBJECT DriverObject, IN PVOID ClientIdentificationAddress)
Definition at line 7646 of file iosubs.c.
References _IO_CLIENT_EXTENSION::ClientIdentificationAddress, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, _IO_CLIENT_EXTENSION::NextExtension, and NULL.
PVOID IoGetFileObjectFilterContext (IN PFILE_OBJECT FileObject)
Definition at line 14684 of file iosubs.c.
References _IOP_FILE_OBJECT_EXTENSION::FilterContext, FO_FILE_OBJECT_HAS_EXTENSION, and NULL.
Referenced by FsRtlInsertPerFileObjectContext(), FsRtlLookupPerFileObjectContext(), FsRtlPTeardownPerFileObjectContexts(), and FsRtlRemovePerFileObjectContext().
PGENERIC_MAPPING IoGetFileObjectGenericMapping (VOID)
Definition at line 7698 of file iosubs.c.
References IopFileMapping, and PAGED_CODE.
PVOID IoGetInitialStack (VOID)
Definition at line 7729 of file iosubs.c.
References _KTHREAD::InitialStack, PsGetCurrentThread(), and _ETHREAD::Tcb.
PDEVICE_OBJECT IoGetLowerDeviceObject (IN PDEVICE_OBJECT DeviceObject)
Definition at line 14232 of file iosubs.c.
References DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_UNLOAD_PENDING, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, NULL, and ObReferenceObject.
IO_PAGING_PRIORITY FASTCALL IoGetPagingIoPriority (IN PIRP Irp)
Definition at line 14847 of file iosubs.c.
References IoPagingPriorityHigh, IoPagingPriorityInvalid, IoPagingPriorityNormal, IRP_HIGH_PRIORITY_PAGING_IO, and IRP_PAGING_IO.
PDEVICE_OBJECT IoGetRelatedDeviceObject (IN PFILE_OBJECT FileObject)
Definition at line 7895 of file iosubs.c.
References ASSERT, FO_DIRECT_DEVICE_OPEN, FO_FILE_OBJECT_HAS_EXTENSION, IoGetAttachedDevice(), IopVerifyDeviceObjectOnStack(), NULL, and _IOP_FILE_OBJECT_EXTENSION::TopDeviceObjectHint.
Referenced by BuildQueryDirectoryIrp(), CcMdlReadComplete(), CcMdlWriteComplete(), CcSetValidData(), CcZeroData(), FsRtlAcquireFileExclusiveCommon(), FsRtlAcquireFileForCcFlushEx(), FsRtlAcquireFileForModWriteEx(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlGetFileSize(), FsRtlMdlRead(), FsRtlMdlReadComplete(), FsRtlMdlReadDev(), FsRtlMdlWriteComplete(), FsRtlPrepareMdlWrite(), FsRtlPrepareMdlWriteDev(), FsRtlReleaseFile(), FsRtlReleaseFileForCcFlush(), FsRtlReleaseFileForModWrite(), FsRtlSetFileSize(), IoAsynchronousPageWrite(), IoAttachDevice(), IoGetDeviceObjectPointer(), IoPageRead(), IopCloseFile(), IopDeleteFile(), IopGetBasicInformationFile(), IopGetFileInformation(), IopGetSetObjectId(), IopGetSetSecurityObject(), IopGetVolumeId(), IopIsSameMachine(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopParseFile(), IopQueryXxxInformation(), IopSetEaOrQuotaInformationFile(), IopSetRemoteLink(), IopXxxControlFile(), IoSetInformation(), IoSynchronousPageWrite(), NtCreatePagingFile(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFile(), NtWriteFileGather(), RawSetInformation(), and WmipObjectToPDO().
PEPROCESS IoGetRequestorProcess (IN PIRP Irp)
Definition at line 8034 of file iosubs.c.
References AttachedApcEnvironment, CONTAINING_RECORD, NULL, OriginalApcEnvironment, and THREAD_TO_PROCESS.
Referenced by FsRtlCheckLockForReadAccess(), FsRtlCheckLockForWriteAccess(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlProcessFileLock(), and IoGetRequestorProcessId().
ULONG IoGetRequestorProcessId (IN PIRP Irp)
Definition at line 7990 of file iosubs.c.
References HandleToUlong, IoGetRequestorProcess(), NULL, and _EPROCESS::UniqueProcessId.
NTSTATUS IoGetRequestorSessionId (IN PIRP Irp, OUT PULONG pSessionId)
Definition at line 13539 of file iosubs.c.
References MmGetSessionId(), STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and THREAD_TO_PROCESS.
VOID IoGetStackLimits (OUT PULONG_PTR LowLimit, OUT PULONG_PTR HighLimit)
Definition at line 7764 of file iosubs.c.
References DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, _KPRCB::DpcStack, KeGetCurrentIrql(), KeGetCurrentPrcb(), KERNEL_STACK_SIZE, and RtlpGetStackLimits().
Referenced by IoGetRemainingStackSize().
PIRP IoGetTopLevelIrp (VOID)
Definition at line 8092 of file iosubs.c.
References PIRP, PsGetCurrentThread(), and _ETHREAD::TopLevelIrp.
Referenced by FsRtlCreateSectionForDataScan().
VOID IoInitializeIrp (IN OUT PIRP Irp, IN USHORT PacketSize, IN CCHAR StackSize)
Definition at line 8127 of file iosubs.c.
References InitializeListHead(), IO_TYPE_IRP, IOV_INITIALIZE_IRP, IRP, KeGetCurrentApcEnvironment, and RtlZeroMemory.
Referenced by IopAllocateReserveIrp(), WmipDisableKernelTrace(), and WmipEnableKernelTrace().
NTSTATUS IoInitializeTimer (IN PDEVICE_OBJECT DeviceObject, IN PIO_TIMER_ROUTINE TimerRoutine, IN PVOID Context)
Definition at line 8226 of file iosubs.c.
References _IO_TIMER::Context, _IO_TIMER::DeviceObject, ExAllocatePoolWithTag, ExInterlockedInsertTailList(), IO_TYPE_TIMER, IopTimerLock, IopTimerQueueHead, NonPagedPool, PAGED_CODE, RtlZeroMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _IO_TIMER::TimerList, _IO_TIMER::TimerRoutine, and _IO_TIMER::Type.
BOOLEAN IoIsDeviceEjectable (IN PDEVICE_OBJECT DeviceObject)
Definition at line 14757 of file iosubs.c.
References FALSE, FILE_FLOPPY_DISKETTE, INIT_WINPEMODE_INRAM, InitWinPEModeType, and TRUE.
Referenced by MiCreateImageFileMap().
BOOLEAN IoIsFileOriginRemote (IN PFILE_OBJECT FileObject)
Definition at line 14581 of file iosubs.c.
References FALSE, FO_REMOTE_ORIGIN, and TRUE.
Referenced by CcCanIWrite(), and CcForceWriteThrough().
BOOLEAN IoIsOperationSynchronous (IN PIRP Irp)
Definition at line 8298 of file iosubs.c.
References FALSE, FO_SYNCHRONOUS_IO, IoGetCurrentIrpStackLocation, IRP_PAGING_IO, IRP_SYNCHRONOUS_API, IRP_SYNCHRONOUS_PAGING_IO, and TRUE.
Referenced by FsRtlAcknowledgeOplockBreak(), and FsRtlOplockFsctrl().
BOOLEAN IoIsSystemThread (IN PETHREAD Thread)
Definition at line 8356 of file iosubs.c.
References IS_SYSTEM_THREAD.
BOOLEAN IoIsValidNameGraftingBuffer (IN PIRP Irp, IN PREPARSE_DATA_BUFFER ReparseBuffer)
Definition at line 8388 of file iosubs.c.
References ASSERT, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, ExFreePool(), FALSE, FIELD_OFFSET, InitializeObjectAttributes, IO_REPARSE_TAG_MOUNT_POINT, IoGetCurrentIrpStackLocation, _UNICODE_STRING::Length, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, _UNICODE_STRING::MaximumLength, MOUNTMGR_IS_VOLUME_NAME, NonPagedPool, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, _IO_STACK_LOCATION::Parameters, _REPARSE_DATA_BUFFER::PathBuffer, REPARSE_DATA_BUFFER_HEADER_SIZE, RtlCopyMemory, RtlInitUnicodeString(), SYMBOLIC_LINK_QUERY, TRUE, UNICODE_NULL, ZwClose(), ZwOpenSymbolicLinkObject(), and ZwQuerySymbolicLinkObject().
PIRP IoMakeAssociatedIrp (IN PIRP Irp, IN CCHAR StackSize)
Definition at line 8976 of file iosubs.c.
References ExAllocatePoolWithTag, ExFreePool(), InterlockedPopEntrySList(), IopInitializeIrp, IopIrpAutoSizingEnabled, IopLargeIrpStackLocations, IoSizeOfIrp, IRP_ALLOCATED_FIXED_SIZE, IRP_ASSOCIATED_IRP, IRP_HIGH_PRIORITY_PAGING_IO, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, LookasideLargeIrpList, LookasideSmallIrpList, NonPagedPool, NULL, _PP_LOOKASIDE_LIST::P, PIRP, _KPRCB::PPLookasideList, and _GENERAL_LOOKASIDE::TotalAllocates.
NTSTATUS IoPageRead (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 9122 of file iosubs.c.
References CcMissCounter, _IO_STACK_LOCATION::FileObject, InterlockedIncrement, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAllocateReserveIrp(), IRP_INPUT_OPERATION, IRP_MJ_READ, IRP_NOCACHE, IRP_PAGING_IO, IRP_SET_USER_EVENT, IRP_SYNCHRONOUS_PAGING_IO, KernelMode, _IO_STACK_LOCATION::MajorFunction, MmIsFileObjectAPagingFile(), MmIsRecursiveIoFault(), PAGE_SHIFT, PAGE_SIZE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and STATUS_INSUFFICIENT_RESOURCES.
Referenced by MiCcPutPagesInTransition(), MiCreateImageFileMap(), MiDispatchFault(), and MiMakeOutswappedPageResident().
PVOID IopAllocateErrorLogEntry (IN PDEVICE_OBJECT deviceObject, IN PDRIVER_OBJECT driverObject, IN UCHAR EntrySize)
Definition at line 587 of file iosubs.c.
References _ERROR_LOG_ENTRY::DeviceObject, _ERROR_LOG_ENTRY::DriverObject, ERROR_LOG_MAXIMUM_SIZE, ExAllocatePoolWithTag, InterlockedExchangeAdd(), IO_TYPE_ERROR_LOG, IOP_MAXIMUM_LOG_ALLOCATION, IopErrorLogAllocation, NonPagedPool, NULL, ObReferenceObject, RtlZeroMemory, _ERROR_LOG_ENTRY::Size, and _ERROR_LOG_ENTRY::Type.
Referenced by IoAllocateErrorLogEntry(), and IoAllocateGenericErrorLogEntry().
PIRP IopAllocateIrpPrivate (IN CCHAR StackSize, IN BOOLEAN ChargeQuota)
Definition at line 745 of file iosubs.c.
References ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, ExFreePool(), FALSE, InterlockedDecrement, InterlockedPopEntrySList(), IopInitializeIrp, IopIrpAutoSizingEnabled, IopIrpProfileStackCountEnabled, IopLargeIrpStackLocations, IopProfileIrpStackCount, IoSizeOfIrp, IRP_ALLOCATED_FIXED_SIZE, IRP_LOOKASIDE_ALLOCATION, IRP_QUOTA_CHARGED, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, _KPRCB::LookasideIrpFloat, LookasideLargeIrpList, LookasideSmallIrpList, NonPagedPool, NULL, _PP_LOOKASIDE_LIST::P, PIRP, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _KPRCB::PPLookasideList, and _GENERAL_LOOKASIDE::TotalAllocates.
Referenced by IopSetIoRoutines().
PDEVICE_OBJECT IopAttachDeviceToDeviceStackSafe (IN PDEVICE_OBJECT SourceDevice, IN PDEVICE_OBJECT TargetDevice, OUT PDEVICE_OBJECT *AttachedToDeviceObject OPTIONAL)
Definition at line 1435 of file iosubs.c.
References ASSERT, _DEVOBJ_EXTENSION::AttachedTo, DO_DEVICE_INITIALIZING, DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_START_PENDING, DOE_UNLOAD_PENDING, IoGetAttachedDevice(), IOV_ATTACH_DEVICE_TO_DEVICE_STACK, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, and NULL.
Referenced by IoAttachDeviceToDeviceStack(), and IoAttachDeviceToDeviceStackSafe().
PSECURITY_DESCRIPTOR IopCreateDefaultDeviceSecurityDescriptor (IN DEVICE_TYPE DeviceType, IN ULONG DeviceCharacteristics, IN BOOLEAN DeviceHasName, IN PUCHAR Buffer, OUT PACL * AllocatedAcl, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
Definition at line 13270 of file iosubs.c.
References _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, DACL_SECURITY_INFORMATION, ExAllocatePoolWithTag, FALSE, FILE_DEVICE_CD_ROM, FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DFS_FILE_SYSTEM, FILE_DEVICE_DISK, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_FILE_SYSTEM, FILE_DEVICE_MASS_STORAGE, FILE_DEVICE_NETWORK, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, FILE_DEVICE_VIRTUAL_DISK, FILE_FLOPPY_DISKETTE, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, IO_SD_SYS_ALL_ADM_ALL_WORLD_E_RES_E, IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE_RES_RE, IopCreateSecurityDescriptorPerType(), _ACCESS_ALLOWED_ACE::Mask, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlCopyMemory, RtlCreateSecurityDescriptor(), RtlEqualSid(), RtlGetAce(), RtlSetDaclSecurityDescriptor(), SeAliasAdminsSid, SECURITY_DESCRIPTOR_REVISION, SePublicDefaultUnrestrictedDacl, SeWorldSid, _ACCESS_ALLOWED_ACE::SidStart, STATUS_SUCCESS, and TRUE.
Referenced by IoCreateDevice().
NTSTATUS IopCreateFile (OUT PHANDLE FileHandle, IN ACCESS_MASK DesiredAccess, IN POBJECT_ATTRIBUTES ObjectAttributes, OUT PIO_STATUS_BLOCK IoStatusBlock, IN PLARGE_INTEGER AllocationSize OPTIONAL, IN ULONG FileAttributes, IN ULONG ShareAccess, IN ULONG Disposition, IN ULONG CreateOptions, IN PVOID EaBuffer OPTIONAL, IN ULONG EaLength, IN CREATE_FILE_TYPE CreateFileType, IN PVOID ExtraCreateParameters OPTIONAL, IN ULONG Options, IN ULONG InternalFlags, IN PVOID DeviceObject)
Definition at line 4948 of file iosubs.c.
References _OPEN_PACKET::AllocationSize, ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, _NAMED_PIPE_CREATE_PARAMETERS::CompletionMode, _OPEN_PACKET::CreateFileType, CreateFileTypeMailslot, CreateFileTypeNamedPipe, CreateFileTypeNone, _OPEN_PACKET::CreateOptions, DELETE, _OPEN_PACKET::DeleteOnly, _FILE_OBJECT::DeviceObject, _OPEN_PACKET::Disposition, _OPEN_PACKET::EaBuffer, _OPEN_PACKET::EaLength, ExAllocatePoolWithQuotaTag, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExRaiseStatus(), _OPEN_PACKET::ExtraCreateParameters, FALSE, FILE_APPEND_DATA, FILE_ATTRIBUTE_VALID_FLAGS, FILE_COMPLETE_IF_OPLOCKED, FILE_CREATE, FILE_DELETE_ON_CLOSE, FILE_DIRECTORY_FILE, FILE_MAXIMUM_DISPOSITION, FILE_NO_COMPRESSION, FILE_NO_INTERMEDIATE_BUFFERING, FILE_NON_DIRECTORY_FILE, FILE_OPEN, FILE_OPEN_BY_FILE_ID, FILE_OPEN_FOR_BACKUP_INTENT, FILE_OPEN_FOR_FREE_SPACE_QUERY, FILE_OPEN_IF, FILE_OPEN_REPARSE_POINT, FILE_PIPE_COMPLETE_OPERATION, FILE_PIPE_MESSAGE_MODE, FILE_PIPE_MESSAGE_TYPE, FILE_RESERVE_OPFILTER, FILE_SHARE_DELETE, FILE_SHARE_VALID_FLAGS, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_ALERT, FILE_SYNCHRONOUS_IO_NONALERT, FILE_VALID_MAILSLOT_OPTION_FLAGS, FILE_VALID_OPTION_FLAGS, FILE_VALID_PIPE_OPTION_FLAGS, FILE_WRITE_THROUGH, _OPEN_PACKET::FileAttributes, _FILE_OBJECT::FileName, _OPEN_PACKET::FileObject, _OPEN_PACKET::FinalStatus, _FILE_OBJECT::Flags, FO_HANDLE_CREATED, _OPEN_PACKET::Information, _OPEN_PACKET::InternalFlags, IO_ATTACH_DEVICE, IO_ATTACH_DEVICE_API, IO_CHECK_CREATE_PARAMETERS, IO_NO_PARAMETER_CHECKING, IO_REPARSE_TAG_MOUNT_POINT, IO_TYPE_FILE, IO_TYPE_OPEN_PACKET, IoCheckEaBufferValidity(), IopAllocateOpenPacket, IopFailZeroAccessCreate, IopFreeOpenPacket, IopUpdateOtherOperationCount(), KeGetPreviousMode, KernelMode, _UNICODE_STRING::Length, _NAMED_PIPE_CREATE_PARAMETERS::NamedPipeType, NonPagedPool, NOTHING, NT_SUCCESS, NT_WARNING, NULL, ObDereferenceObject(), ObOpenObjectByName(), OPEN_PACKET_PATTERN, _OPEN_PACKET::Options, _OPEN_PACKET::Override, PAGED_CODE, _OPEN_PACKET::ParseCheck, ProbeAndWriteHandle, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteIoStatus, _LARGE_INTEGER::QuadPart, _OPEN_PACKET::QueryOnly, _NAMED_PIPE_CREATE_PARAMETERS::ReadMode, _OPEN_PACKET::RelatedFileObject, RtlCopyMemory, _OPEN_PACKET::ShareAccess, _OPEN_PACKET::Size, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, STATUS_REPARSE_POINT_NOT_RESOLVED, STATUS_SUCCESS, SYNCHRONIZE, _OPEN_PACKET::TopDeviceObjectHint, _OPEN_PACKET::TraversedMountPoint, _OPEN_PACKET::Type, _FILE_OBJECT::Type, and ZwClose().
Referenced by IoCreateFile(), and IoCreateFileSpecifyDeviceObjectHint().
NTSTATUS IopCreateSecurityDescriptorPerType (IN PSECURITY_DESCRIPTOR Descriptor, IN ULONG SecurityDescriptorFlavor, OUT PSECURITY_INFORMATION SecurityInformation OPTIONAL)
Definition at line 13473 of file iosubs.c.
References ARGUMENT_PRESENT, ASSERT, DACL_SECURITY_INFORMATION, IO_SD_SYS_ALL_ADM_ALL_WORLD_E, IO_SD_SYS_ALL_ADM_ALL_WORLD_E_RES_E, IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE, IO_SD_SYS_ALL_ADM_ALL_WORLD_RWE_RES_RE, IO_SD_SYS_ALL_ADM_RE, NT_SUCCESS, RtlCreateSecurityDescriptor(), RtlSetDaclSecurityDescriptor(), SECURITY_DESCRIPTOR_REVISION, SePublicDefaultDacl, SePublicDefaultUnrestrictedDacl, SePublicOpenDacl, SePublicOpenUnrestrictedDacl, SeSystemDefaultDacl, STATUS_INVALID_PARAMETER, and TRUE.
Referenced by IopCreateDefaultDeviceSecurityDescriptor().
NTSTATUS IopCreateVpb (IN PDEVICE_OBJECT DeviceObject)
Definition at line 4251 of file iosubs.c.
References ExAllocatePoolWithTag, IO_TYPE_VPB, NonPagedPool, _VPB::RealDevice, RtlZeroMemory, _VPB::Size, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _VPB::Type.
Referenced by IoCreateDevice(), and IoVerifyVolume().
NTSTATUS IopDeleteSessionSymLinks (IN PUNICODE_STRING LinkName)
Definition at line 6523 of file iosubs.c.
References _UNICODE_STRING::Buffer, DELETE, DIRECTORY_QUERY, ExAllocatePoolWithTag, ExFreePool(), FALSE, InitializeObjectAttributes, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PagedPool, Prefix, PREFIX_STRING_LENGTH, RtlAppendUnicodeStringToString(), RtlCompareUnicodeString(), RtlCopyUnicodeString(), RtlInitUnicodeString(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MORE_ENTRIES, STATUS_SUCCESS, TRUE, wcsncpy(), ZwClose(), ZwMakeTemporaryObject(), ZwOpenDirectoryObject(), ZwOpenSymbolicLinkObject(), and ZwQueryDirectoryObject().
Referenced by IoDeleteSymbolicLink().
VOID IopDoNameTransmogrify (IN PIRP Irp, IN PFILE_OBJECT FileObject, IN PREPARSE_DATA_BUFFER ReparseBuffer)
Definition at line 8776 of file iosubs.c.
References ASSERT, ExAllocatePoolWithTag, ExFreePool(), FIELD_OFFSET, IO_REPARSE_TAG_MOUNT_POINT, MAXIMUM_REPARSE_DATA_BUFFER_SIZE, MAXUSHORT, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, _REPARSE_DATA_BUFFER::PathBuffer, REPARSE_DATA_BUFFER_HEADER_SIZE, RtlCopyMemory, RtlMoveMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_IO_REPARSE_DATA_INVALID, STATUS_NAME_TOO_LONG, STATUS_REPARSE, and UNICODE_NULL.
Referenced by IopCompleteRequest(), and IopParseDevice().
VOID FASTCALL IopfCompleteRequest (IN PIRP Irp, IN CCHAR PriorityBoost)
Definition at line 3339 of file iosubs.c.
References ASSERT, _IO_STACK_LOCATION::CompletionRoutine, _IO_STACK_LOCATION::Context, _IO_STACK_LOCATION::Control, ExFreePool(), IO_REPARSE_TAG_MOUNT_POINT, IO_REPARSE_TAG_RESERVED_RANGE, IO_TYPE_IRP, IoCompleteRequest(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoMarkIrpPending, IopAbortRequest(), IopCompletePageWrite(), IopCompleteRequest(), IopDropIrp(), IopFreeIrpAndMdls(), IopFreeReserveIrp(), IopInterlockedDecrementUlong(), IopIsReserveIrp, IRP, IRP_ASSOCIATED_IRP, IRP_CLOSE_OPERATION, IRP_DEFER_IO_COMPLETION, IRP_PAGING_IO, IRP_SET_USER_EVENT, IRP_SYNCHRONOUS_PAGING_IO, KeAcquireQueuedSpinLock(), KeBugCheckEx(), KeInitializeApc(), KeInsertQueueApc(), KeReleaseQueuedSpinLock(), KernelMode, KeSetEvent(), LockQueueIoCompletionLock, LockQueueIoDatabaseLock, MmUnlockPages(), MULTIPLE_IRP_COMPLETE_REQUESTS, _MDL::Next, NT_SUCCESS, NULL, _IO_STACK_LOCATION::Parameters, PIRP, SL_ERROR_RETURNED, SL_INVOKE_ON_CANCEL, SL_INVOKE_ON_ERROR, SL_INVOKE_ON_SUCCESS, SL_PENDING_RETURNED, STATUS_IO_REPARSE_TAG_NOT_HANDLED, STATUS_MORE_PROCESSING_REQUIRED, STATUS_PENDING, STATUS_REPARSE, STATUS_SUCCESS, _ETHREAD::Tcb, VOID, and ZeroIrpStackLocation.
Referenced by IopSetIoRoutines().
VOID IopFreeIrp (IN PIRP Irp)
Definition at line 7144 of file iosubs.c.
References ASSERT, ExFreePool(), ExQueryDepthSList, ExReturnPoolQuota(), InterlockedIncrement, InterlockedPushEntrySList(), IO_TYPE_IRP, IopIrpAutoSizingEnabled, IopLargeIrpStackLocations, IoSizeOfIrp, IRP_ALLOCATED_FIXED_SIZE, IRP_ALLOCATED_MUST_SUCCEED, IRP_LOOKASIDE_ALLOCATION, IRP_QUOTA_CHARGED, IsListEmpty, KeBugCheckEx(), KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, _KPRCB::LookasideIrpFloat, LookasideLargeIrpList, LookasideSmallIrpList, MULTIPLE_IRP_COMPLETE_REQUESTS, _PP_LOOKASIDE_LIST::P, _KPRCB::PPLookasideList, PSLIST_ENTRY, and _GENERAL_LOOKASIDE::TotalFrees.
Referenced by IopSetIoRoutines().
VOID IopInsertRemoveDevice (IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Insert)
Definition at line 4224 of file iosubs.c.
References KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), and LockQueueIoDatabaseLock.
Referenced by IoCreateDevice(), and IopCompleteUnloadOrDelete().
VOID IopNotifyAlreadyRegisteredFileSystems (IN PLIST_ENTRY ListHead, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine, IN BOOLEAN SkipRaw)
Definition at line 10132 of file iosubs.c.
References CONTAINING_RECORD, DEVICE_OBJECT, _LIST_ENTRY::Flink, and TRUE.
Referenced by IoRegisterFsRegistrationChange().
VOID IopRemoveTimerFromTimerList (IN PIO_TIMER timer)
Definition at line 6418 of file iosubs.c.
References ExAcquireFastLock, ExReleaseFastLock, IopTimerCount, IopTimerLock, RemoveEntryList(), and UNREFERENCED_PARAMETER.
Referenced by IoDeleteDevice().
VOID IopShutdownBaseFileSystems (IN PLIST_ENTRY ListHead)
Definition at line 11398 of file iosubs.c.
References CONTAINING_RECORD, DEVICE_OBJECT, Executive, IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetAttachedDevice(), IopDecrementDeviceObjectRef(), IopInterlockedIncrementUlong(), IRP_MJ_SHUTDOWN, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LockQueueIoDatabaseLock, NotificationEvent, NULL, ObDereferenceObject(), ObReferenceObject, PIRP, RemoveHeadList(), STATUS_PENDING, TRUE, and VOID.
Referenced by IoShutdownSystem().
VOID IopStartNextPacket (IN PDEVICE_OBJECT DeviceObject, IN LOGICAL Cancelable)
Definition at line 11483 of file iosubs.c.
References CONTAINING_RECORD, DOE_STARTIO_NO_CANCEL, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IRP, KeRemoveDeviceQueue(), NULL, PASSIVE_LEVEL, and PIRP.
Referenced by IopStartNextPacketByKeyEx(), and IoStartNextPacket().
VOID IopStartNextPacketByKey (IN PDEVICE_OBJECT DeviceObject, IN LOGICAL Cancelable, IN ULONG Key)
Definition at line 11578 of file iosubs.c.
References CONTAINING_RECORD, DOE_STARTIO_NO_CANCEL, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IRP, KeRemoveByKeyDeviceQueue(), NULL, PASSIVE_LEVEL, and PIRP.
Referenced by IopStartNextPacketByKeyEx(), and IoStartNextPacketByKey().
VOID IopStartNextPacketByKeyEx (IN PDEVICE_OBJECT DeviceObject, IN ULONG Key, IN int Flags)
Definition at line 11810 of file iosubs.c.
References DOE_STARTIO_CANCELABLE, DOE_STARTIO_REQUESTED, DOE_STARTIO_REQUESTED_BYKEY, InterlockedDecrement, InterlockedIncrement, IopStartNextPacket(), and IopStartNextPacketByKey().
Referenced by IoStartNextPacket(), and IoStartNextPacketByKey().
NTSTATUS IopUnloadSafeCompletion (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PVOID Context)
Definition at line 13934 of file iosubs.c.
References _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::CompletionRoutine, _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::Context, _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::DeviceObject, ExFreePool(), ObDereferenceObject(), ObReferenceObject, and Status.
Referenced by IoSetCompletionRoutineEx().
NTSTATUS IoQueryFileDosDeviceName (IN PFILE_OBJECT FileObject, OUT POBJECT_NAME_INFORMATION * ObjectNameInformation)
Definition at line 13862 of file iosubs.c.
References ExAllocatePoolWithTag, ExFreePool(), IopQueryNameInternal(), KernelMode, NULL, PagedPool, Status, STATUS_BUFFER_OVERFLOW, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by CcWriteBehind(), and MiLdwPopupWorker().
NTSTATUS IoQueryFileInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, OUT PVOID FileInformation, OUT PULONG ReturnedLength)
Definition at line 9271 of file iosubs.c.
References IopQueryXxxInformation(), KernelMode, PAGED_CODE, and TRUE.
Referenced by IopGetNetworkOpenInformation(), and IopParseDevice().
NTSTATUS IoQueryVolumeInformation (IN PFILE_OBJECT FileObject, IN FS_INFORMATION_CLASS FsInformationClass, IN ULONG Length, OUT PVOID FsInformation, OUT PULONG ReturnedLength)
Definition at line 9327 of file iosubs.c.
References IopQueryXxxInformation(), KernelMode, and PAGED_CODE.
Referenced by MiAttemptPageFileExtension(), and NtCreatePagingFile().
VOID IoQueueThreadIrp (IN PIRP Irp)
Definition at line 9383 of file iosubs.c.
References IopQueueThreadIrp().
VOID IoRaiseHardError (IN PIRP Irp, IN PVPB Vpb OPTIONAL, IN PDEVICE_OBJECT RealDeviceObject)
Definition at line 9414 of file iosubs.c.
References CriticalWorkQueue, _ETHREAD::CrossThreadFlags, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExInitializeWorkItem, ExQueueWorkItem(), FALSE, FIELD_OFFSET, IO_DISK_INCREMENT, IoCompleteRequest(), IoGetCurrentIrpStackLocation, IopAbortRequest(), IopDeallocateApc(), IopRaiseHardError(), IopStartApcHardError(), _IOP_APC_HARD_ERROR_PACKET::Irp, IRP_INPUT_OPERATION, IRP_MJ_CLEANUP, IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_MOUNT_VOLUME, IRP_NOCACHE, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, IRP_VERIFIER_MASK, IS_SYSTEM_THREAD, _IOP_APC_HARD_ERROR_PACKET::Item, KeInitializeApc(), KeInsertQueueApc(), KernelMode, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, MmCopyVirtualMemory(), NonPagedPool, NT_SUCCESS, NULL, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PsGetCurrentProcess(), _IOP_APC_HARD_ERROR_PACKET::RealDeviceObject, RTL_ERRORMODE_FAILCRITICALERRORS, _ETHREAD::Tcb, _KTHREAD::Teb, THREAD_TO_PROCESS, TRUE, VOID, and _IOP_APC_HARD_ERROR_PACKET::Vpb.
BOOLEAN IoRaiseInformationalHardError (IN NTSTATUS ErrorStatus, IN PUNICODE_STRING String OPTIONAL, IN PKTHREAD Thread OPTIONAL)
Definition at line 9615 of file iosubs.c.
References ArePacketsEquivalent, ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, CONTAINING_RECORD, DelayedWorkQueue, _IOP_HARD_ERROR_PACKET::ErrorStatus, ExAcquireSpinLock, ExAllocatePoolWithTag, ExFreePool(), ExQueueWorkItem(), ExReleaseSpinLock, _IOP_HARD_ERROR_QUEUE::ExWorkItem, FALSE, _LIST_ENTRY::Flink, InsertTailList(), InterlockedIncrement, IOP_MAXIMUM_OUTSTANDING_HARD_ERRORS, IopCurrentHardError, IopDeallocateApc(), IopHardError, IopRaiseInformationalHardError(), KeInitializeApc(), KeInsertQueueApc(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NonPagedPool, NULL, _IOP_HARD_ERROR_QUEUE::NumPendingApcPopups, OriginalApcEnvironment, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PsGetCurrentThread(), RtlCopyMemory, RtlZeroMemory, STATUS_SERVICE_NOTIFICATION, STATUS_UNHANDLED_EXCEPTION, STATUS_VDM_HARD_ERROR, _IOP_HARD_ERROR_PACKET::String, _IOP_HARD_ERROR_QUEUE::ThreadStarted, TRUE, VOID, _IOP_HARD_ERROR_QUEUE::WorkQueue, _IOP_HARD_ERROR_PACKET::WorkQueueLinks, _IOP_HARD_ERROR_QUEUE::WorkQueueSemaphore, and _IOP_HARD_ERROR_QUEUE::WorkQueueSpinLock.
Referenced by CcWriteBehind(), MiCauseOverCommitPopup(), MiLdwPopupWorker(), and WmipGenerateMCAEventlog().
VOID IoRegisterBootDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
Definition at line 9906 of file iosubs.c.
References _REINIT_PACKET::Context, _REINIT_PACKET::DriverObject, _REINIT_PACKET::DriverReinitializationRoutine, DRVO_BOOTREINIT_REGISTERED, ExAllocatePoolWithTag, IopBootDriverReinitializeQueueHead, IopInterlockedInsertTailList(), _REINIT_PACKET::ListEntry, NonPagedPool, and PAGED_CODE.
VOID IoRegisterDriverReinitialization (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_REINITIALIZE DriverReinitializationRoutine, IN PVOID Context)
Definition at line 9967 of file iosubs.c.
References _REINIT_PACKET::Context, _REINIT_PACKET::DriverObject, _REINIT_PACKET::DriverReinitializationRoutine, DRVO_REINIT_REGISTERED, ExAllocatePoolWithTag, IopDriverReinitializeQueueHead, IopInterlockedInsertTailList(), _REINIT_PACKET::ListEntry, NonPagedPool, and PAGED_CODE.
VOID IoRegisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
Definition at line 10028 of file iosubs.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, DO_DEVICE_INITIALIZING, DO_LOW_PRIORITY_FILESYSTEM, DRVO_BASE_FILESYSTEM_DRIVER, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), FILE_DEVICE_CD_ROM_FILE_SYSTEM, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_DEVICE_TAPE_FILE_SYSTEM, _LIST_ENTRY::Flink, InsertHeadList(), InsertTailList(), IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopFsNotifyChangeQueueHead, IopFsRegistrationOps, IopInterlockedIncrementUlong(), IopNetworkFileSystemQueueHead, IopTapeFileSystemQueueHead, LockQueueIoDatabaseLock, _NOTIFICATION_PACKET::NotificationRoutine, NULL, PAGED_CODE, TRUE, and VOID.
Referenced by RawInitialize().
NTSTATUS IoRegisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
Definition at line 10176 of file iosubs.c.
References _LIST_ENTRY::Blink, CONTAINING_RECORD, _NOTIFICATION_PACKET::DriverObject, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExReleaseResourceLite(), InsertTailList(), IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopFsNotifyChangeQueueHead, IopNetworkFileSystemQueueHead, IopNotifyAlreadyRegisteredFileSystems(), IopTapeFileSystemQueueHead, IsListEmpty, _NOTIFICATION_PACKET::ListEntry, _NOTIFICATION_PACKET::NotificationRoutine, ObReferenceObject, PAGED_CODE, PagedPool, POOL_COLD_ALLOCATION, STATUS_DEVICE_ALREADY_ATTACHED, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
NTSTATUS IoRegisterLastChanceShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10278 of file iosubs.c.
References _SHUTDOWN_PACKET::DeviceObject, DO_SHUTDOWN_REGISTERED, ExAllocatePoolWithTag, IopInterlockedInsertHeadList(), IopNotifyLastChanceShutdownQueueHead, _SHUTDOWN_PACKET::ListEntry, NonPagedPool, ObReferenceObject, PAGED_CODE, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
NTSTATUS IoRegisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
Definition at line 10341 of file iosubs.c.
References _SHUTDOWN_PACKET::DeviceObject, DO_SHUTDOWN_REGISTERED, ExAllocatePoolWithTag, IopInterlockedInsertHeadList(), IopNotifyShutdownQueueHead, _SHUTDOWN_PACKET::ListEntry, NonPagedPool, ObReferenceObject, PAGED_CODE, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by RawInitialize(), and WmipDriverEntry().
VOID IoReleaseCancelSpinLock (IN KIRQL Irql)
Definition at line 10404 of file iosubs.c.
References KeReleaseQueuedSpinLock(), and LockQueueIoCancelLock.
Referenced by FsRtlAcknowledgeOplockBreak(), FsRtlCancelExclusiveIrp(), FsRtlCancelNotify(), FsRtlCancelOplockIIIrp(), FsRtlCancelWaitIrp(), FsRtlNotifySetCancelRoutine(), FsRtlOplockBreakToII(), FsRtlOplockBreakToNone(), FsRtlOplockCleanup(), FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlRemoveAndCompleteIrp(), FsRtlRemoveAndCompleteWaitIrp(), FsRtlRequestExclusiveOplock(), FsRtlRequestOplockII(), FsRtlUninitializeFileLock(), FsRtlUninitializeOplock(), FsRtlWaitOnIrp(), IoCancelIrp(), IopCsqCancelRoutine(), IopStartNextPacket(), IopStartNextPacketByKey(), IoStartPacket(), and WmipNotificationIrpCancel().
VOID IoReleaseVpbSpinLock (IN KIRQL Irql)
Definition at line 10435 of file iosubs.c.
References KeReleaseQueuedSpinLock(), and LockQueueIoVpbLock.
Referenced by IoGetDiskDeviceObject(), IopMountInitializeVpb(), IopReferenceVerifyVpb(), RawCheckForDismount(), and RawVerifyVolume().
VOID IoRemoveShareAccess (IN PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
Definition at line 10466 of file iosubs.c.
References _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, and PAGED_CODE.
Referenced by RawCleanup().
VOID IoRetryIrpCompletions (VOID)
Definition at line 13734 of file iosubs.c.
References APC_LEVEL, ASSERT, CONTAINING_RECORD, _LIST_ENTRY::Flink, IopCompleteRequest(), IRP, IRP_CREATE_OPERATION, IRP_RETRY_IO_COMPLETION, _ETHREAD::IrpList, KeLowerIrql, KeRaiseIrql, NULL, PIRP, and PsGetCurrentThread().
Referenced by MmAccessFault(), MmCopyToCachedPage(), and MmPrefetchPagesIntoLockedMdl().
VOID IoReuseIrp (PIRP Irp, NTSTATUS Status)
Definition at line 8180 of file iosubs.c.
References ASSERT, IopInitializeIrp, IoSizeOfIrp, IsListEmpty, NULL, and Status.
NTSTATUS IoSetCompletionRoutineEx (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PIO_COMPLETION_ROUTINE CompletionRoutine, IN PVOID Context, IN BOOLEAN InvokeOnSuccess, IN BOOLEAN InvokeOnError, IN BOOLEAN InvokeOnCancel)
Definition at line 13954 of file iosubs.c.
References _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::CompletionRoutine, _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::Context, _IO_UNLOAD_SAFE_COMPLETION_CONTEXT::DeviceObject, ExAllocatePoolWithTag, IopUnloadSafeCompletion(), IoSetCompletionRoutine, NonPagedPool, NULL, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
VOID IoSetDeviceToVerify (IN PETHREAD Thread, IN PDEVICE_OBJECT DeviceObject)
Definition at line 10560 of file iosubs.c.
NTSTATUS IoSetFileOrigin (IN PFILE_OBJECT FileObject, IN BOOLEAN Remote)
Definition at line 14626 of file iosubs.c.
References FO_REMOTE_ORIGIN, Status, STATUS_INVALID_PARAMETER_MIX, and STATUS_SUCCESS.
VOID IoSetHardErrorOrVerifyDevice (IN PIRP Irp, IN PDEVICE_OBJECT DeviceObject)
Definition at line 10599 of file iosubs.c.
NTSTATUS IoSetInformation (IN PFILE_OBJECT FileObject, IN FILE_INFORMATION_CLASS FileInformationClass, IN ULONG Length, IN PVOID FileInformation)
Definition at line 10650 of file iosubs.c.
References Executive, FALSE, FILE_SEQUENTIAL_ONLY, FILE_SYNCHRONOUS_IO_ALERT, FILE_WRITE_THROUGH, FileLinkInformation, FileModeInformation, FileMoveClusterInformation, _FILE_RENAME_INFORMATION::FileName, _IO_STACK_LOCATION::FileObject, FileRenameInformation, _FILE_OBJECT::Flags, FO_ALERTABLE_IO, FO_NO_INTERMEDIATE_BUFFERING, FO_SEQUENTIAL_ONLY, FO_SYNCHRONOUS_IO, FO_WRITE_THROUGH, IoAllocateIrp(), IoCallDriver(), IoCompleteRequest(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateIrpCleanup(), IopCancelAlertedRequest(), IopOpenLinkOrRenameTarget(), IopQueueThreadIrp(), IopReleaseFileObjectLock, IoSetNextIrpStackLocation, IRP_BUFFERED_IO, IRP_MJ_SET_INFORMATION, IRP_SYNCHRONOUS_API, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _IO_STACK_LOCATION::MajorFunction, _FILE_MODE_INFORMATION::Mode, NT_SUCCESS, NULL, ObCloseHandle(), ObDereferenceObject(), OBJ_NAME_PATH_SEPARATOR, ObReferenceObject, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), _FILE_RENAME_INFORMATION::ReplaceIfExists, _FILE_RENAME_INFORMATION::RootDirectory, _IO_STATUS_BLOCK::Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, SynchronizationEvent, TRUE, and VOID.
Referenced by MiAttemptPageFileExtension(), and MiAttemptPageFileReduction().
VOID IoSetShareAccess (IN ACCESS_MASK DesiredAccess, IN ULONG DesiredShareAccess, IN OUT PFILE_OBJECT FileObject, OUT PSHARE_ACCESS ShareAccess)
Definition at line 10990 of file iosubs.c.
References DELETE, FALSE, FILE_APPEND_DATA, FILE_EXECUTE, FILE_READ_DATA, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_WRITE_DATA, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, PAGED_CODE, and TRUE.
Referenced by RawCreate().
VOID IoSetStartIoAttributes (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN DeferredStartIo, IN BOOLEAN NonCancelable)
Definition at line 11934 of file iosubs.c.
References DOE_STARTIO_DEFERRED, and DOE_STARTIO_NO_CANCEL.
NTSTATUS IoSetSystemPartition (PUNICODE_STRING VolumeNameString)
Definition at line 14467 of file iosubs.c.
References ASSERT, _UNICODE_STRING::Buffer, IopCreateRegistryKeyEx(), IopOpenRegistryKeyEx(), KEY_ALL_ACCESS, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtClose(), NULL, REG_OPTION_NON_VOLATILE, REG_SZ, RtlInitUnicodeString(), TITLE_INDEX_VALUE, and ZwSetValueKey().
BOOLEAN IoSetThreadHardErrorMode (IN BOOLEAN EnableHardErrors)
Definition at line 11123 of file iosubs.c.
References _ETHREAD::CrossThreadFlags, FALSE, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_HARD_ERRORS_DISABLED, PS_SET_BITS, PsGetCurrentThread(), and TRUE.
Referenced by CmpCmdHiveClose(), CmpDoFileSetSize(), FsRtlGetFileSize(), FsRtlSetFileSize(), HvSyncHive(), and ObKillProcess().
VOID IoSetTopLevelIrp (IN PIRP Irp)
Definition at line 11174 of file iosubs.c.
References PsGetCurrentThread(), and _ETHREAD::TopLevelIrp.
Referenced by FsRtlCreateSectionForDataScan(), MiRemoveUnusedSegments(), and MmCreateSection().
VOID IoShutdownSystem (IN ULONG Phase)
Definition at line 11212 of file iosubs.c.
References CONTAINING_RECORD, DbgPrint(), _SHUTDOWN_PACKET::DeviceObject, ExAcquireResourceExclusiveLite(), Executive, ExFreePool(), IoBuildSynchronousFsdRequest(), IoCallDriver(), IoGetAttachedDeviceReference(), IopCdRomFileSystemQueueHead, IopDatabaseResource, IopDiskFileSystemQueueHead, IopInterlockedRemoveHeadList(), IopLinkTrackingServiceEventHandle, IopNotifyLastChanceShutdownQueueHead, IopNotifyShutdownQueueHead, IopShutdownBaseFileSystems(), IopTapeFileSystemQueueHead, IoShutdownPnpDevices(), IOV_UNLOAD_DRIVERS, IRP_MJ_SHUTDOWN, KeClearEvent(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NULL, ObDereferenceObject(), PAGED_CODE, PIRP, STATUS_PENDING, TRUE, VOID, and ZwClose().
VOID IoStartNextPacket (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable)
Definition at line 11870 of file iosubs.c.
References DOE_STARTIO_CANCELABLE, DOE_STARTIO_DEFERRED, DOE_STARTIO_REQUESTED, IopStartNextPacket(), and IopStartNextPacketByKeyEx().
VOID IoStartNextPacketByKey (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN Cancelable, IN ULONG Key)
Definition at line 11900 of file iosubs.c.
References DOE_STARTIO_CANCELABLE, DOE_STARTIO_DEFERRED, DOE_STARTIO_REQUESTED_BYKEY, IopStartNextPacketByKey(), and IopStartNextPacketByKeyEx().
VOID IoStartPacket (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp, IN PULONG Key OPTIONAL, IN PDRIVER_CANCEL CancelFunction OPTIONAL)
Definition at line 11674 of file iosubs.c.
References DISPATCH_LEVEL, DOE_STARTIO_NO_CANCEL, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), KeInsertByKeyDeviceQueue(), KeInsertDeviceQueue(), KeLowerIrql, KeRaiseIrql, NULL, and PASSIVE_LEVEL.
VOID IoStartTimer (IN PDEVICE_OBJECT DeviceObject)
Definition at line 11972 of file iosubs.c.
References DOE_DELETE_PENDING, DOE_REMOVE_PENDING, DOE_REMOVE_PROCESSED, DOE_UNLOAD_PENDING, ExAcquireFastLock, ExReleaseFastLock, IopTimerCount, IopTimerLock, _IO_TIMER::TimerFlag, TRUE, and UNREFERENCED_PARAMETER.
VOID IoStopTimer (IN PDEVICE_OBJECT DeviceObject)
Definition at line 12029 of file iosubs.c.
References ExAcquireFastLock, ExReleaseFastLock, FALSE, IopTimerCount, IopTimerLock, _IO_TIMER::TimerFlag, and UNREFERENCED_PARAMETER.
NTSTATUS IoSynchronousPageWrite (IN PFILE_OBJECT FileObject, IN PMDL MemoryDescriptorList, IN PLARGE_INTEGER StartingOffset, IN PKEVENT Event, OUT PIO_STATUS_BLOCK IoStatusBlock)
Definition at line 12074 of file iosubs.c.
References CcDataFlushes, CcDataPages, CcIsFileCached, _IO_STACK_LOCATION::FileObject, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IoGetRelatedDeviceObject(), IRP_MJ_WRITE, IRP_NOCACHE, IRP_PAGING_IO, IRP_SYNCHRONOUS_PAGING_IO, KernelMode, _IO_STACK_LOCATION::MajorFunction, PAGE_SHIFT, PAGE_SIZE, _IO_STACK_LOCATION::Parameters, PIRP, PsGetCurrentThread(), and STATUS_INSUFFICIENT_RESOURCES.
Referenced by CcZeroData(), MiCleanSection(), MiFlushSectionInternal(), MiShutdownSystem(), MiZeroPageFile(), and MiZeroPageFileFirstPage().
PEPROCESS IoThreadToProcess (IN PETHREAD Thread)
Definition at line 12188 of file iosubs.c.
References THREAD_TO_PROCESS.
VOID IoUnregisterFileSystem (IN OUT PDEVICE_OBJECT DeviceObject)
Definition at line 12223 of file iosubs.c.
References CONTAINING_RECORD, ExAcquireResourceExclusiveLite(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, IopDatabaseResource, IopFsNotifyChangeQueueHead, IopFsRegistrationOps, IopInterlockedDecrementUlong(), LockQueueIoDatabaseLock, _NOTIFICATION_PACKET::NotificationRoutine, NULL, PAGED_CODE, RemoveEntryList(), TRUE, and VOID.
Referenced by RawShutdown().
VOID IoUnregisterFsRegistrationChange (IN PDRIVER_OBJECT DriverObject, IN PDRIVER_FS_NOTIFICATION DriverNotificationRoutine)
Definition at line 12297 of file iosubs.c.
References CONTAINING_RECORD, _NOTIFICATION_PACKET::DriverObject, ExAcquireResourceExclusiveLite(), ExFreePool(), ExReleaseResourceLite(), _LIST_ENTRY::Flink, IopDatabaseResource, IopFsNotifyChangeQueueHead, _NOTIFICATION_PACKET::NotificationRoutine, ObDereferenceObject(), PAGED_CODE, RemoveEntryList(), and TRUE.
VOID IoUnregisterShutdownNotification (IN PDEVICE_OBJECT DeviceObject)
Definition at line 12358 of file iosubs.c.
References ASSERT, _LIST_ENTRY::Blink, CONTAINING_RECORD, _SHUTDOWN_PACKET::DeviceObject, DO_SHUTDOWN_REGISTERED, ExFreePool(), ExPageLockHandle, _LIST_ENTRY::Flink, IopNotifyLastChanceShutdownQueueHead, IopNotifyShutdownQueueHead, KeAcquireQueuedSpinLock(), KeReleaseQueuedSpinLock(), LockQueueIoDatabaseLock, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), ObDereferenceObject(), PAGED_CODE, and RemoveEntryList().
Referenced by IoDeleteDevice().
VOID IoUpdateShareAccess (IN OUT PFILE_OBJECT FileObject, IN OUT PSHARE_ACCESS ShareAccess)
Definition at line 12451 of file iosubs.c.
References FALSE, _IOP_FILE_OBJECT_EXTENSION::FileObjectExtensionFlags, FO_EXTENSION_IGNORE_SHARE_ACCESS_CHECK, FO_FILE_OBJECT_HAS_EXTENSION, PAGED_CODE, and TRUE.
NTSTATUS IoValidateDeviceIoControlAccess (IN PIRP Irp, IN ULONG RequiredAccess)
Definition at line 14772 of file iosubs.c.
References FILE_READ_ACCESS, FILE_READ_DATA, FILE_WRITE_ACCESS, FILE_WRITE_DATA, _IO_STACK_LOCATION::Flags, IoGetCurrentIrpStackLocation, IRP_MJ_DEVICE_CONTROL, IRP_MJ_FILE_SYSTEM_CONTROL, KernelMode, _IO_STACK_LOCATION::MajorFunction, SeComputeGrantedAccesses, SL_READ_ACCESS_GRANTED, SL_WRITE_ACCESS_GRANTED, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS IoVerifyVolume (IN PDEVICE_OBJECT DeviceObject, IN BOOLEAN AllowRawMount)
Definition at line 12532 of file iosubs.c.
References ASSERT, DO_VERIFY_VOLUME, Executive, FALSE, _IO_STACK_LOCATION::Flags, IoAllocateIrp(), IoCallDriver(), IoGetNextIrpStackLocation, IopCreateVpb(), IopDereferenceVpbAndFree(), IopInterlockedDecrementUlong(), IopMountVolume(), IopReferenceVerifyVpb(), IRP_MJ_FILE_SYSTEM_CONTROL, IRP_MN_VERIFY_VOLUME, IRP_MOUNT_COMPLETION, IRP_SYNCHRONOUS_PAGING_IO, KeInitializeEvent(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LockQueueIoVpbLock, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NotificationEvent, NT_SUCCESS, NULL, PAGED_CODE, _IO_STACK_LOCATION::Parameters, PIRP, PoVolumeDevice(), PsGetCurrentThread(), _VPB::ReferenceCount, SL_ALLOW_RAW_MOUNT, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, STATUS_WRONG_VOLUME, TRUE, and VOID.
VOID IoWriteErrorLogEntry (IN OUT PVOID ElEntry)
Definition at line 12722 of file iosubs.c.
References DelayedWorkQueue, _ERROR_LOG_ENTRY::DeviceObject, _ERROR_LOG_ENTRY::DriverObject, ExAcquireSpinLock, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), ExReleaseSpinLock, InsertTailList(), InterlockedExchangeAdd(), IopErrorLogAllocation, IopErrorLogDisabledThisBoot, IopErrorLogListHead, IopErrorLogLock, IopErrorLogPortPending, IopErrorLogThread(), IopErrorLogWorkItem, KeQuerySystemTime(), _ERROR_LOG_ENTRY::ListEntry, NULL, ObDereferenceObject(), _ERROR_LOG_ENTRY::Size, _ERROR_LOG_ENTRY::TimeStamp, and TRUE.
Variable Documentation
CONFIGURATION_INFORMATION ConfigurationInformation static
Initial value:
= {
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    FALSE,
    FALSE,
    sizeof(CONFIGURATION_INFORMATION),
    0
}
Definition at line 28 of file iosubs.c.
LOGICAL IoCountOperations = TRUE
Definition at line 49 of file iosubs.c.
LONG IoPageReadIrpAllocationFailure
Definition at line 50 of file iosubs.c.
LONG IoPageReadNonPagefileIrpAllocationFailure
Definition at line 51 of file iosubs.c.