Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/sysload.c File Reference
sysload.c File Reference
#include "mi.h"
Data Structures
struct _MI_LARGE_PAGE_DRIVER_ENTRY
Macros
#define DRIVERS_SUBDIR_NAME L"drivers\\"
#define HAL_NAME L"hal.dll"
#define KERNEL_NAME L"ntoskrnl.exe"
Typedefs
typedef struct _MI_LARGE_PAGE_DRIVER_ENTRY MI_LARGE_PAGE_DRIVER_ENTRY
typedef struct _MI_LARGE_PAGE_DRIVER_ENTRY * PMI_LARGE_PAGE_DRIVER_ENTRY
Functions
NTSTATUS LookupEntryPoint (IN PVOID DllBase, IN PSZ NameOfEntryPoint, OUT PVOID *AddressOfEntryPoint)
NTSTATUS MiBuildImportsForBootDrivers (VOID)
PVOID MiCacheImageSymbols (IN PVOID ImageBase)
LOGICAL MiCallDllUnloadAndUnloadDll (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
VOID MiCaptureImageExceptionValues (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
LOGICAL MiChargeResidentAvailable (IN PFN_NUMBER NumberOfPages, IN ULONG Id)
VOID MiClearImports (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
MM_PROTECTION_MASK MiComputeDriverProtection (IN LOGICAL SessionDriver, IN ULONG SectionProtection)
PFN_NUMBER MiDeleteSystemPageableVm (IN PMMPTE PointerPte, IN PFN_NUMBER NumberOfPtes, IN ULONG Flags, OUT PPFN_NUMBER ResidentPages OPTIONAL)
NTSTATUS MiDereferenceImports (IN PLOAD_IMPORTS ImportList)
VOID MiEnablePagingOfDriver (IN PVOID ImageHandle)
PVOID MiFindExportedRoutineByName (IN PVOID DllBase, IN PANSI_STRING AnsiImageRoutineName)
VOID MiFlushPteListFreePfns (IN PVOID *VaFlushList, IN ULONG FlushCount)
VOID MiInitializeDriverLargePageList (VOID)
LOGICAL MiInitializeLoadedModuleList (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS MiLoadImageSection (IN OUT PSECTION *InputSectionPointer, OUT PVOID *ImageBase, IN PUNICODE_STRING ImageFileName, IN ULONG LoadInSessionSpace, IN PKLDR_DATA_TABLE_ENTRY FoundDataTableEntry)
PVOID MiLocateExportName (IN PVOID DllBase, IN PCHAR FunctionName)
VOID MiLocateKernelSections (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
PVOID MiLookupImageSectionByName (IN PVOID Base, IN LOGICAL MappedAsImage, IN PCHAR SectionName, OUT PULONG SectionSize)
VOID MiMakeEntireImageCopyOnWrite (IN PSUBSECTION Subsection)
LONG MiMapCacheExceptionFilter (OUT PNTSTATUS Status, IN PEXCEPTION_POINTERS ExceptionPointer)
VOID MiMarkSectionWritable (IN PIMAGE_SECTION_HEADER SectionTableEntry)
VOID MiProcessLoaderEntry (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry, IN LOGICAL Insert)
VOID MiReloadBootLoadedDrivers (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID MiRememberUnloadedDriver (IN PUNICODE_STRING DriverName, IN PVOID Address, IN ULONG Length)
NTSTATUS MiResolveImageReferences (PVOID ImageBase, IN PUNICODE_STRING ImageFileDirectory, IN PUNICODE_STRING NamePrefix OPTIONAL, OUT PCHAR *MissingProcedureName, OUT PWSTR *MissingDriverName, OUT PLOAD_IMPORTS *LoadedImports)
VOID MiReturnFailedSessionPages (IN PMMPTE PointerPte, IN PMMPTE LastPte)
VOID MiRundownHotpatchList (PVOID PatchHead)
VOID MiSessionProcessGlobalSubsections (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
VOID MiSetPagingOfDriver (IN PMMPTE PointerPte, IN PMMPTE LastPte)
ULONG MiSetProtectionOnTransitionPte (IN PMMPTE PointerPte, IN ULONG ProtectionMask)
VOID MiSetSystemCodeProtection (IN PMMPTE FirstPte, IN PMMPTE LastPte, IN ULONG ProtectionMask)
NTSTATUS MiSnapThunk (IN PVOID DllBase, IN PVOID ImageBase, IN PIMAGE_THUNK_DATA NameThunk, OUT PIMAGE_THUNK_DATA AddrThunk, IN PIMAGE_EXPORT_DIRECTORY ExportDirectory, IN ULONG ExportSize, IN LOGICAL SnapForwarder, OUT PCHAR *MissingProcedureName)
VOID MiUpdateThunks (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PVOID OldAddress, IN PVOID NewAddress, IN ULONG NumberOfBytes)
LOGICAL MiUseLargeDriverPage (IN ULONG NumberOfPtes, IN OUT PVOID *ImageBaseAddress, IN PUNICODE_STRING PrefixedImageName, IN ULONG Pass)
VOID MiWriteProtectSystemImage (IN PVOID DllBase)
NTSTATUS MmCallDllInitialize (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry, IN PLIST_ENTRY ModuleListHead)
NTSTATUS MmCheckSystemImage (IN HANDLE ImageFileHandle, IN LOGICAL PurgeSection)
VOID MmFreeDriverInitialization (IN PVOID ImageHandle)
NTKERNELAPI PVOID MmGetSystemRoutineAddress (__in PUNICODE_STRING SystemRoutineName)
NTSTATUS MmLoadSystemImage (IN PUNICODE_STRING ImageFileName, IN PUNICODE_STRING NamePrefix OPTIONAL, IN PUNICODE_STRING LoadedBaseName OPTIONAL, IN ULONG LoadFlags, OUT PVOID *ImageHandle, OUT PVOID *ImageBaseAddress)
PUNICODE_STRING MmLocateUnloadedDriver (IN PVOID VirtualAddress)
VOID MmMakeKernelResourceSectionWritable (VOID)
PVOID MmPageEntireDriver (__in PVOID AddressWithinSection)
VOID MmResetDriverPaging (__in PVOID AddressWithinSection)
NTSTATUS MmUnloadSystemImage (IN PVOID ImageHandle)
BOOLEAN MmVerifyImageIsOkForMpUse (IN PVOID BaseAddress)
Variables
PVOID ExPoolCodeEnd
PVOID ExPoolCodeStart
LONG MiFirstDriverLoadEver = 0
PMMPTE MiKernelResourceEndPte
PMMPTE MiKernelResourceStartPte
ULONG MiLargePageAllDrivers
LIST_ENTRY MiLargePageDriverList
ULONG MiTotalUnloads
ULONG MiUnloadsSkipped
ULONG MmDriverCommit
ULONG MmEnforceWriteProtection = 1
ULONG MmLastUnloadedDriver
LOGICAL MmMakeLowMemory = TRUE
PVOID MmPoolCodeEnd
PVOID MmPoolCodeStart
PVOID MmPteCodeEnd
PVOID MmPteCodeStart
KMUTANT MmSystemLoadLock
LONG MmTotalSystemDriverPages
PUNLOADED_DRIVERS MmUnloadedDrivers
LIST_ENTRY PsLoadedModuleList
ERESOURCE PsLoadedModuleResource
PVOID PsNtosImageBase
Macro Definition Documentation
#define DRIVERS_SUBDIR_NAME L"drivers\\"
Referenced by MiResolveImageReferences().
#define HAL_NAME L"hal.dll"
Referenced by MiBuildImportsForBootDrivers(), and MmGetSystemRoutineAddress().
#define KERNEL_NAME L"ntoskrnl.exe"
Referenced by MiBuildImportsForBootDrivers(), and MmGetSystemRoutineAddress().
Typedef Documentation
typedef struct _MI_LARGE_PAGE_DRIVER_ENTRY MI_LARGE_PAGE_DRIVER_ENTRY
typedef struct _MI_LARGE_PAGE_DRIVER_ENTRY * PMI_LARGE_PAGE_DRIVER_ENTRY
Function Documentation
NTSTATUS LookupEntryPoint (IN PVOID DllBase, IN PSZ NameOfEntryPoint, OUT PVOID * AddressOfEntryPoint)
Definition at line 2003 of file initos.c.
Referenced by MmLoadSystemImage().
NTSTATUS MiBuildImportsForBootDrivers (VOID)
Definition at line 3898 of file sysload.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _LOAD_IMPORTS::Count, DbgBreakPoint(), DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, _LOAD_IMPORTS::Entry, ExAllocatePoolWithTag, ExFreePool(), FALSE, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, HAL_NAME, IMAGE_DIRECTORY_ENTRY_IAT, KERNEL_NAME, LDRP_DRIVER_DEPENDENT_DLL, _UNICODE_STRING::Length, _KLDR_DATA_TABLE_ENTRY::LoadCount, LOADED_AT_BOOT, _KLDR_DATA_TABLE_ENTRY::LoadedImports, _UNICODE_STRING::MaximumLength, NO_IMPORTS_USED, NOTHING, NULL, PAGED_CODE, PagedPool, POINTER_TO_SINGLE_ENTRY, POOL_COLD_ALLOCATION, PsLoadedModuleList, RtlEqualUnicodeString(), RtlImageDirectoryEntryToData(), RtlZeroMemory, SINGLE_ENTRY, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_FOUND, STATUS_SUCCESS, and TRUE.
Referenced by MiInitializeLoadedModuleList().
PVOID MiCacheImageSymbols (IN PVOID ImageBase)
Definition at line 4324 of file mapview.c.
References except, EXCEPTION_EXECUTE_HANDLER, IMAGE_DIRECTORY_ENTRY_DEBUG, NOTHING, NULL, PAGED_CODE, RtlImageDirectoryEntryToData(), and TRUE.
Referenced by MiMapViewOfImageSection(), and MmLoadSystemImage().
LOGICAL MiCallDllUnloadAndUnloadDll (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
Definition at line 4232 of file sysload.c.
References ASSERT, FALSE, MiLocateExportName(), MmUnloadSystemImage(), NT_SUCCESS, PAGED_CODE, Status, and TRUE.
Referenced by MiDereferenceImports().
VOID MiCaptureImageExceptionValues (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
Definition at line 690 of file sysload.c.
References _IMAGE_OPTIONAL_HEADER::DataDirectory, _IMAGE_OPTIONAL_HEADER::DllCharacteristics, IMAGE_DIRECTORY_ENTRY_EXCEPTION, IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG, IMAGE_DLLCHARACTERISTICS_NO_SEH, LongToPtr, _IMAGE_NT_HEADERS::OptionalHeader, RTL_SIZEOF_THROUGH_FIELD, RtlImageNtHeader(), IMAGE_LOAD_CONFIG_DIRECTORY32::SEHandlerCount, IMAGE_LOAD_CONFIG_DIRECTORY32::SEHandlerTable, _IMAGE_DATA_DIRECTORY::Size, IMAGE_LOAD_CONFIG_DIRECTORY32::Size, and _IMAGE_DATA_DIRECTORY::VirtualAddress.
Referenced by MiInitializeLoadedModuleList(), MiReloadBootLoadedDrivers(), and MmLoadSystemImage().
LOGICAL MiChargeResidentAvailable (IN PFN_NUMBER NumberOfPages, IN ULONG Id)
Definition at line 2698 of file sysload.c.
References FALSE, LOCK_PFN, MI_DECREMENT_RESIDENT_AVAILABLE, MI_NONPAGEABLE_MEMORY_AVAILABLE, TRUE, and UNLOCK_PFN.
Referenced by MiLoadImageSection().
VOID MiClearImports (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
Definition at line 3321 of file sysload.c.
References ExFreePool(), LOADED_AT_BOOT, NO_IMPORTS_USED, NOTHING, PAGED_CODE, and SINGLE_ENTRY.
Referenced by MmUnloadSystemImage().
MM_PROTECTION_MASK MiComputeDriverProtection (IN LOGICAL SessionDriver, IN ULONG SectionProtection)
Definition at line 6608 of file sysload.c.
References IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_READ, IMAGE_SCN_MEM_WRITE, MM_EXECUTE, MM_EXECUTE_READWRITE, MM_EXECUTE_WRITECOPY, MM_NOACCESS, MM_READONLY, MM_READWRITE, MM_WRITECOPY, MM_ZERO_ACCESS, MmEnforceWriteProtection, and TRUE.
Referenced by MiWriteProtectSystemImage().
PFN_NUMBER MiDeleteSystemPageableVm (IN PMMPTE PointerPte, IN PFN_NUMBER NumberOfPtes, IN ULONG Flags, OUT PPFN_NUMBER ResidentPages OPTIONAL)
Definition at line 5709 of file sysload.c.
References APC_LEVEL, ARGUMENT_PRESENT, ASSERT, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, FALSE, _MMWSL::FirstDynamic, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMPTE::Hard, InterlockedDecrementSizeT, KeBugCheckEx(), KeGetCurrentIrql(), KeReadTbFlushTimeStamp(), LOCK_PFN, LOCK_WORKING_SET, _MMWSLENTRY::LockedInMemory, _MMWSLENTRY::LockedInWs, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_DELETE_FLUSH_TB, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_SESSION_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiCheckPdeForPagedPool(), MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInsertPageInFreeList(), MiLocateWsle(), MiReleasePageFileSpace(), MiReleaseWsle(), MiRemoveWsle(), MiSwapWslEntries(), MiUnlinkPageFromList(), MM_BUMP_SESS_COUNTER, MM_DBG_SESSION_NP_DELVA, MM_MAXIMUM_FLUSH_COUNT, MmSessionSpace, MmSystemCacheWorkingSetList, MmSystemCacheWs, _MM_SESSION_SPACE::NonPageablePages, NOTHING, NT_SUCCESS, _MMPFN::OriginalPte, PAGE_ALIGN, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteFrame, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, _MMWSLENTRY::Valid, _MMWSLE::VirtualAddress, _MM_SESSION_SPACE::Vm, _MMSUPPORT::VmWorkingSetList, _MMPFN::WsIndex, _MM_SESSION_SPACE::Wsle, and WSLE_NULL_INDEX.
Referenced by MiFreeInitializationCode(), MiFreePoolPages(), MiSessionWideReserveImageAddress(), MiUseLargeDriverPage(), MmFreeBootRegistry(), MmFreeDriverInitialization(), and MmUnloadSystemImage().
NTSTATUS MiDereferenceImports (IN PLOAD_IMPORTS ImportList)
Definition at line 4414 of file sysload.c.
References ASSERT, CONTAINING_RECORD, _LOAD_IMPORTS::Count, _LOAD_IMPORTS::Entry, ExFreePool(), _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::LoadCount, LOADED_AT_BOOT, _KLDR_DATA_TABLE_ENTRY::LoadedImports, MiCallDllUnloadAndUnloadDll(), NO_IMPORTS_USED, PAGED_CODE, PsLoadedModuleList, SINGLE_ENTRY, SINGLE_ENTRY_TO_POINTER, STATUS_SUCCESS, and TRUE.
Referenced by MiResolveImageReferences(), and MmUnloadSystemImage().
VOID MiEnablePagingOfDriver (IN PVOID ImageHandle)
Definition at line 2831 of file sysload.c.
References DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, FIELD_OFFSET, _IMAGE_NT_HEADERS::FileHeader, _KLDR_DATA_TABLE_ENTRY::FullDllName, IMAGE_FIRST_SECTION, MiGetPteAddress, _IMAGE_SECTION_HEADER::Misc, MiSetPagingOfDriver(), MM_SYSTEM_CODE_LOCKED_DOWN, MmDisablePagingExecutive, _IMAGE_SECTION_HEADER::Name, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGE_SIZE, ROUND_TO_PAGES, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SectionAlignment, _IMAGE_SECTION_HEADER::SizeOfRawData, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by MmLoadSystemImage().
PVOID MiFindExportedRoutineByName (IN PVOID DllBase, IN PANSI_STRING AnsiImageRoutineName)
Definition at line 8402 of file sysload.c.
References _IMAGE_EXPORT_DIRECTORY::AddressOfFunctions, _IMAGE_EXPORT_DIRECTORY::AddressOfNameOrdinals, _IMAGE_EXPORT_DIRECTORY::AddressOfNames, ASSERT, IMAGE_DIRECTORY_ENTRY_EXPORT, NULL, _IMAGE_EXPORT_DIRECTORY::NumberOfFunctions, _IMAGE_EXPORT_DIRECTORY::NumberOfNames, PAGED_CODE, RtlImageDirectoryEntryToData(), strcmp(), and TRUE.
Referenced by MmGetSystemRoutineAddress().
VOID MiFlushPteListFreePfns (IN PVOID * VaFlushList, IN ULONG FlushCount)
Definition at line 2739 of file sysload.c.
References ASSERT, KeAreAllApcsDisabled(), LOCK_PFN, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_WRITE_INVALID_PTE, MiDecrementShareCount(), MiGetPteAddress, MM_MAXIMUM_FLUSH_COUNT, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::Protection, _MMPTE::Soft, TRUE, _MMPTE::u, and UNLOCK_PFN.
Referenced by MiSetPagingOfDriver().
VOID MiInitializeDriverLargePageList (VOID)
Definition at line 337 of file sysload.c.
References _MI_LARGE_PAGE_DRIVER_ENTRY::BaseName, _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, InitializeListHead(), InsertTailList(), _UNICODE_STRING::Length, _MI_LARGE_PAGE_DRIVER_ENTRY::Links, _UNICODE_STRING::MaximumLength, MiLargePageAllDrivers, MmLargePageDriverBuffer, MmLargePageDriverBufferLength, NonPagedPool, NULL, and UNICODE_WHITESPACE.
Referenced by MmInitSystem().
LOGICAL MiInitializeLoadedModuleList (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 7970 of file sysload.c.
References _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAllocatePoolWithTag, ExFreePool(), ExInitializeResourceLite(), FALSE, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, InitializeListHead(), _KLDR_DATA_TABLE_ENTRY::InLoadOrderLinks, InsertTailList(), KeInitializeSpinLock(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MiBuildImportsForBootDrivers(), MiCaptureImageExceptionValues(), MiLocateKernelSections(), MM_DBG_COMMIT_LOAD_SYSTEM_IMAGE_TEMP, MM_TRACK_COMMIT, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTotalCommittedPages, _KLDR_DATA_TABLE_ENTRY::NonPagedDebugInfo, NonPagedPool, NULL, PAGE_SHIFT, PagedPool, _KLDR_DATA_TABLE_ENTRY::PatchInformation, PsLoadedModuleSpinLock, PsNtosImageBase, RtlCopyMemory, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, TRUE, and UNICODE_NULL.
Referenced by MmInitSystem().
NTSTATUS MiLoadImageSection (IN OUT PSECTION * InputSectionPointer, OUT PVOID * ImageBase, IN PUNICODE_STRING ImageFileName, IN ULONG LoadInSessionSpace, IN PKLDR_DATA_TABLE_ENTRY FoundDataTableEntry)
Definition at line 2161 of file sysload.c.
References ASSERT, _SEGMENT::BasedAddress, _SEGMENT::ControlArea, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, DPFLTR_WARNING_LEVEL, except, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, FLG_ENABLE_KDEBUG_SYMBOL_LOAD, FLG_SHOW_LDR_SNAPS, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, InterlockedExchangeAdd(), KeStackAttachProcess(), KeUnstackDetachProcess(), _MMPTE::Long, MI_INCREMENT_RESIDENT_AVAILABLE, MI_PFN_ELEMENT, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiAllocatePfn(), MiChargeCommitment(), MiChargeResidentAvailable(), MiGetVirtualAddressMappedByPte, MiMapCacheExceptionFilter(), MiReleaseSystemPtes(), MiRemoveImageSessionWide(), MiReserveSystemPtes(), MiReturnCommitment, MiReturnFailedSessionPages(), MiSessionWideReserveImageAddress(), MiShareSessionImage(), MiUnmapViewOfSection(), MM_DBG_COMMIT_DRIVER_PAGES, MM_EXECUTE, MM_NOACCESS, MM_PTE_EXECUTE, MM_RESAVAIL_ALLOCATE_LOAD_SYSTEM_IMAGE, MM_RESAVAIL_FREE_LOAD_SYSTEM_IMAGE1, MM_RESAVAIL_FREE_LOAD_SYSTEM_IMAGE2, MM_RESAVAIL_FREE_LOAD_SYSTEM_IMAGE3, MM_RESAVAIL_FREE_LOAD_SYSTEM_IMAGE_EXCESS, MM_TRACK_COMMIT, MmDriverCommit, MmMapViewOfSection(), MmPurgeSection(), _SUBSECTION::NextSubsection, NT_SUCCESS, NtGlobalFlag, NULL, PAGE_EXECUTE, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, _MMPTE_SOFTWARE::Protection, PsGetCurrentProcess(), PsInitialSystemProcess, _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, RtlCopyMemory, _FILE_OBJECT::SectionObjectPointer, _SECTION::Segment, _MMPTE::Soft, Status, STATUS_IMAGE_MACHINE_TYPE_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_IMAGE_FORMAT, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, SystemPteSpace, _SEGMENT::TotalNumberOfPtes, TRUE, _MMPTE::u, _CONTROL_AREA::u, UNREFERENCED_PARAMETER, _MMPTE_HARDWARE::Valid, ValidKernelPte, ViewUnmap, and ZERO_LARGE.
Referenced by MmLoadSystemImage().
PVOID MiLocateExportName (IN PVOID DllBase, IN PCHAR FunctionName)
Definition at line 4299 of file sysload.c.
References _IMAGE_EXPORT_DIRECTORY::AddressOfFunctions, _IMAGE_EXPORT_DIRECTORY::AddressOfNameOrdinals, _IMAGE_EXPORT_DIRECTORY::AddressOfNames, IMAGE_DIRECTORY_ENTRY_EXPORT, NULL, _IMAGE_EXPORT_DIRECTORY::NumberOfNames, PAGED_CODE, RtlImageDirectoryEntryToData(), strcmp(), and TRUE.
Referenced by MiCallDllUnloadAndUnloadDll(), and MmCallDllInitialize().
VOID MiLocateKernelSections (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
Definition at line 7751 of file sysload.c.
References ExPoolCodeEnd, ExPoolCodeStart, _IMAGE_NT_HEADERS::FileHeader, MiGetPteAddress, _IMAGE_SECTION_HEADER::Misc, MmPoolCodeEnd, MmPoolCodeStart, MmPteCodeEnd, MmPteCodeStart, _IMAGE_SECTION_HEADER::Name, NULL, _IMAGE_FILE_HEADER::NumberOfSections, ROUND_TO_PAGES, RtlImageNtHeader(), SECTION_BASE_ADDRESS, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by MiInitializeLoadedModuleList().
PVOID MiLookupImageSectionByName (IN PVOID Base, IN LOGICAL MappedAsImage, IN PCHAR SectionName, OUT PULONG SectionSize)
VOID MiMakeEntireImageCopyOnWrite (IN PSUBSECTION Subsection)
Definition at line 6180 of file sysload.c.
References ASSERT, _MMPTE::Hard, _MMPTE::Long, MiSetProtectionOnTransitionPte(), MM_EXECUTE_WRITECOPY, MM_READWRITE, MmLockPagedPool(), MmUnlockPagedPool(), NULL, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
LONG MiMapCacheExceptionFilter (OUT PNTSTATUS Status, IN PEXCEPTION_POINTERS ExceptionPointer)
Referenced by MiLoadImageSection().
VOID MiMarkSectionWritable (IN PIMAGE_SECTION_HEADER SectionTableEntry)
Definition at line 6102 of file sysload.c.
References ASSERT, _MMPFN::e1, GET_PAGING_FILE_OFFSET, _MMPTE::Hard, IMAGE_SCN_MEM_WRITE, LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_SET_MODIFIED, MiGetByteOffset, MiGetPteAddress, MiMakeSystemAddressValidPfn(), MiMapPageInHyperSpaceAtDpc(), MiReleaseConfirmedPageFileSpace(), MiUnmapPageInHyperSpaceFromDpc, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, PsGetCurrentProcess(), _MMPTE::Soft, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and _MMPFNENTRY::WriteInProgress.
VOID MiProcessLoaderEntry (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry, IN LOGICAL Insert)
Definition at line 262 of file sysload.c.
References ExAcquireResourceExclusiveLite(), ExAcquireSpinLockAtDpcLevel, ExReleaseResourceLite(), ExReleaseSpinLockFromDpcLevel, InsertTailList(), KeLowerIrql, KeRaiseIrqlToSynchLevel(), PsLoadedModuleList, PsLoadedModuleResource, PsLoadedModuleSpinLock, RemoveEntryList(), and TRUE.
Referenced by MmLoadSystemImage(), and MmUnloadSystemImage().
VOID MiReloadBootLoadedDrivers (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 7275 of file sysload.c.
References _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _IMAGE_FILE_HEADER::Characteristics, CONST, CONTAINING_RECORD, _IMAGE_OPTIONAL_HEADER::DataDirectory, _KLDR_DATA_TABLE_ENTRY::DllBase, _KLDR_DATA_TABLE_ENTRY::EntryPoint, FALSE, _IMAGE_NT_HEADERS::FileHeader, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, _MMPTE::Hard, IMAGE_DIRECTORY_ENTRY_BASERELOC, IMAGE_FILE_RELOCS_STRIPPED, _IMAGE_OPTIONAL_HEADER::ImageBase, InitializationPhase, KeSweepIcache, LDRP_SYSTEM_MAPPED, LdrRelocateImage(), LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_PDE_MAPS_LARGE_PAGE, MI_PFN_ELEMENT, MI_ROUND_TO_SIZE, MI_SET_ACCESSED_IN_PTE, MI_SET_MODIFIED, MI_SET_PFN_DELETED, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiCaptureImageExceptionValues(), MiDecrementShareCount(), MiEnsureAvailablePageOrWait(), MiFreeContiguousPages(), MiGetPdeAddress, MiGetPteAddress, MiGetPteOffset, MiGetVirtualAddressMappedByPte, MiInitializePfnAndMakePteValid(), MiNoLowMemory, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiRemoveCachedRange(), MiReserveSystemPtes(), MiUnmapLargePages(), MiUpdateThunks(), MiUseLargeDriverPage(), MM_EXECUTE_READWRITE, MM_HIGH_LIMIT, MM_MINIMUM_VA_FOR_LARGE_PAGE, MmAvailablePages, MmMakeLowMemory, NT_SUCCESS, NULL, _IMAGE_OPTIONAL_HEADER::NumberOfRvaAndSizes, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPFN::PteAddress, _MMPFN::PteFrame, ROUND_TO_PAGES, RtlCopyMemory, RtlImageNtHeader(), _MMPFN::ShareCount, _IMAGE_DATA_DIRECTORY::Size, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INVALID_IMAGE_FORMAT, STATUS_SUCCESS, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u4, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _IMAGE_DATA_DIRECTORY::VirtualAddress, and _MMPFN::WsIndex.
Referenced by MmInitSystem().
VOID MiRememberUnloadedDriver (IN PUNICODE_STRING DriverName, IN PVOID Address, IN ULONG Length)
Definition at line 3368 of file sysload.c.
References _UNICODE_STRING::Buffer, _UNLOADED_DRIVERS::CurrentTime, _UNLOADED_DRIVERS::EndAddress, ExAllocatePoolWithTag, KeQuerySystemTime(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MI_UNLOADED_DRIVERS, MiTotalUnloads, MiUnloadsSkipped, MmLastUnloadedDriver, _UNLOADED_DRIVERS::Name, NonPagedPool, NULL, NumberOfBytes, RtlCopyMemory, RtlFreeUnicodeString(), RtlZeroMemory, and _UNLOADED_DRIVERS::StartAddress.
Referenced by MmUnloadSystemImage().
NTSTATUS MiResolveImageReferences (PVOID ImageBase, IN PUNICODE_STRING ImageFileDirectory, IN PUNICODE_STRING NamePrefix OPTIONAL, OUT PCHAR * MissingProcedureName, OUT PWSTR * MissingDriverName, OUT PLOAD_IMPORTS * LoadedImports)
Definition at line 4545 of file sysload.c.
References _strnicmp(), _IMAGE_THUNK_DATA32::AddressOfData, ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _LIST_ENTRY::Blink, _STRING::Buffer, _UNICODE_STRING::Buffer, CONTAINING_RECORD, Count, _LOAD_IMPORTS::Count, _KLDR_DATA_TABLE_ENTRY::DllBase, DRIVERS_SUBDIR_NAME, _LOAD_IMPORTS::Entry, ExAllocatePoolWithTag, ExFreePool(), FALSE, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, IMAGE_DIRECTORY_ENTRY_EXPORT, IMAGE_DIRECTORY_ENTRY_IMPORT, LDRP_LOAD_IN_PROGRESS, _STRING::Length, _UNICODE_STRING::Length, _KLDR_DATA_TABLE_ENTRY::LoadCount, _STRING::MaximumLength, _UNICODE_STRING::MaximumLength, MI_IS_SESSION_ADDRESS, MiDereferenceImports(), MiSnapThunk(), MmCallDllInitialize(), MmLoadSystemImage(), MmUnloadSystemImage(), NO_IMPORTS_USED, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, POINTER_TO_SINGLE_ENTRY, POOL_COLD_ALLOCATION, PsLoadedModuleList, RtlAnsiStringToUnicodeString(), RtlAppendStringToString(), RtlAppendUnicodeStringToString(), RtlCopyMemory, RtlEqualUnicodeString(), RtlFreeUnicodeString(), RtlImageDirectoryEntryToData(), RtlInitAnsiString(), RtlZeroMemory, STATUS_DRIVER_ENTRYPOINT_NOT_FOUND, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PROCEDURE_NOT_FOUND, STATUS_SUCCESS, TRUE, _IMAGE_THUNK_DATA32::u1, and UNICODE_NULL.
Referenced by MmLoadSystemImage().
VOID MiReturnFailedSessionPages (IN PMMPTE PointerPte, IN PMMPTE LastPte)
Definition at line 2097 of file sysload.c.
References LOCK_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiDecrementShareCount(), _MMPFN::PteFrame, _MMPFN::u4, and UNLOCK_PFN.
Referenced by MiLoadImageSection().
VOID MiRundownHotpatchList (PVOID PatchHead)
Referenced by MmUnloadSystemImage().
VOID MiSessionProcessGlobalSubsections (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry)
Definition at line 7021 of file sysload.c.
References ASSERT, _SEGMENT::ControlArea, Count, ExFreePool(), FALSE, _CONTROL_AREA::Flags, _MMSUBSECTION_FLAGS::GlobalMemory, _MMSECTION_FLAGS::GlobalOnlyPerSession, _IMAGE_ENTRY_IN_SESSION::GlobalSubs, _MMSECTION_FLAGS::Image, _IMAGE_ENTRY_IN_SESSION::ImageLoading, _MM_SESSION_SPACE::ImageLoadingCount, InterlockedDecrement, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, _IMAGE_OPTIONAL_HEADER::MajorSubsystemVersion, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_ADDRESS, MiGetPteAddress, _IMAGE_OPTIONAL_HEADER::MinorImageVersion, _IMAGE_OPTIONAL_HEADER::MinorOperatingSystemVersion, _IMAGE_OPTIONAL_HEADER::MinorSubsystemVersion, MiSessionLookupImage(), MiSetSystemCodeProtection(), MmSessionSpace, _SUBSECTION::NextSubsection, NULL, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_SIZE, PAGED_CODE, _MMSUBSECTION_FLAGS::Protection, _SESSION_GLOBAL_SUBSECTION_INFO::Protection, _SESSION_GLOBAL_SUBSECTION_INFO::PteCount, _SESSION_GLOBAL_SUBSECTION_INFO::PteIndex, _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SectionAlignment, _CONTROL_AREA::Segment, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, TRUE, _CONTROL_AREA::u, and _SUBSECTION::u.
Referenced by MmLoadSystemImage().
VOID MiSetPagingOfDriver (IN PMMPTE PointerPte, IN PMMPTE LastPte)
Definition at line 2964 of file sysload.c.
References ASSERT, FALSE, InterlockedExchangeAdd(), LOCK_WORKING_SET, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MI_PFN_ELEMENT, MiFlushPteListFreePfns(), MiGetVirtualAddressMappedByPte, MM_EXECUTE, MM_KERNEL_DEMAND_ZERO_PTE, MM_MAXIMUM_FLUSH_COUNT, MM_RESAVAIL_FREE_SET_DRIVER_PAGING, MmSystemCacheWs, MmTotalSystemDriverPages, _MMPFN::OriginalPte, PAGE_SIZE, PAGED_CODE, _MMPTE_SOFTWARE::Protection, PsGetCurrentThread(), _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, UNLOCK_WORKING_SET, and _MMPFN::WsIndex.
Referenced by MiEnablePagingOfDriver(), and MmPageEntireDriver().
ULONG MiSetProtectionOnTransitionPte (IN PMMPTE PointerPte, IN ULONG ProtectionMask)
Definition at line 2521 of file protect.c.
References FALSE, LOCK_PFN, MI_PFN_ELEMENT, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, _MMPTE::Trans, TRUE, _MMPTE::u, and UNLOCK_PFN.
Referenced by MiMakeEntireImageCopyOnWrite(), MiProtectVirtualMemory(), and MiSetProtectionOnSection().
VOID MiSetSystemCodeProtection (IN PMMPTE FirstPte, IN PMMPTE LastPte, IN ULONG ProtectionMask)
Definition at line 6264 of file sysload.c.
References _MMPTE_HARDWARE::Accessed, APC_LEVEL, ASSERT, _MMPTE_HARDWARE::Dirty, _MMPFN::e1, FALSE, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMPTE::Hard, KeGetCurrentIrql(), LOCK_PFN, LOCK_WORKING_SET, _MMPTE::Long, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_IS_PHYSICAL_ADDRESS, MI_IS_PTE_DIRTY, MI_IS_SESSION_ADDRESS, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiMakeSystemAddressValidPfnSystemWs(), MiPteToProto, MM_COPY_ON_WRITE_MASK, MM_EXECUTE_READWRITE, MM_MAXIMUM_FLUSH_COUNT, MM_READWRITE, MmSessionSpace, MmSystemCacheWs, NOTHING, NULL, _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPTE::Soft, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, _MM_SESSION_SPACE::Vm, and _MMPTE_HARDWARE::Writable.
Referenced by MiSessionProcessGlobalSubsections(), MiWriteProtectSystemImage(), and MmLoadSystemImage().
NTSTATUS MiSnapThunk (IN PVOID DllBase, IN PVOID ImageBase, IN PIMAGE_THUNK_DATA NameThunk, OUT PIMAGE_THUNK_DATA AddrThunk, IN PIMAGE_EXPORT_DIRECTORY ExportDirectory, IN ULONG ExportSize, IN LOGICAL SnapForwarder, OUT PCHAR * MissingProcedureName)
Definition at line 5184 of file sysload.c.
References _IMAGE_THUNK_DATA32::AddressOfData, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAllocatePoolWithTag, ExFreePool(), _LIST_ENTRY::Flink, _IMAGE_IMPORT_BY_NAME::Hint, IMAGE_DIRECTORY_ENTRY_EXPORT, IMAGE_ORDINAL, IMAGE_SNAP_BY_ORDINAL, _STRING::Length, MAXIMUM_FILENAME_LENGTH, _STRING::MaximumLength, _IMAGE_IMPORT_BY_NAME::Name, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, PsLoadedModuleList, RtlAnsiStringToUnicodeString(), RtlCopyMemory, RtlFreeUnicodeString(), RtlImageDirectoryEntryToData(), RtlPrefixString(), Status, STATUS_DRIVER_ENTRYPOINT_NOT_FOUND, STATUS_DRIVER_ORDINAL_NOT_FOUND, STATUS_SUCCESS, strchr(), strcmp(), strlen(), strncpy(), TRUE, and _IMAGE_THUNK_DATA32::u1.
Referenced by MiResolveImageReferences().
VOID MiUpdateThunks (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PVOID OldAddress, IN PVOID NewAddress, IN ULONG NumberOfBytes)
Definition at line 7197 of file sysload.c.
References CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, _LIST_ENTRY::Flink, IMAGE_DIRECTORY_ENTRY_IAT, NULL, RtlImageDirectoryEntryToData(), and TRUE.
Referenced by MiReloadBootLoadedDrivers().
LOGICAL MiUseLargeDriverPage (IN ULONG NumberOfPtes, IN OUT PVOID * ImageBaseAddress, IN PUNICODE_STRING PrefixedImageName, IN ULONG Pass)
Definition at line 427 of file sysload.c.
References APC_LEVEL, ASSERT, _MI_LARGE_PAGE_DRIVER_ENTRY::BaseName, CONTAINING_RECORD, CR4_PSE, FALSE, _LIST_ENTRY::Flink, _MMPTE::Hard, InterlockedExchangeAdd(), KeFeatureBits, KeGetCurrentIrql(), KF_LARGE_PAGE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_ROUND_TO_SIZE, MiAddCachedRange(), MiDeleteSystemPageableVm(), MiFindContiguousPages(), MiFreeContiguousPages(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiLargePageAllDrivers, MiMapWithLargePages(), MiReleaseSystemPtes(), MiRemoveCachedRange(), MiReturnCommitment, MM_DBG_COMMIT_RETURN_DRIVER_UNLOAD1, MM_EXECUTE_READWRITE, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE1, MM_TRACK_COMMIT, MmCached, MmHighestPossiblePhysicalPage, MmSystemRangeStart, MmTotalFreeSystemPtes, MmTotalSystemDriverPages, NULL, PAGE_SHIFT, PAGE_SIZE, RtlCopyMemory, RtlEqualUnicodeString(), SystemPteSpace, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiReloadBootLoadedDrivers(), and MmLoadSystemImage().
VOID MiWriteProtectSystemImage (IN PVOID DllBase)
Definition at line 6689 of file sysload.c.
References ASSERT, BYTES_TO_PAGES, _IMAGE_SECTION_HEADER::Characteristics, FALSE, _IMAGE_NT_HEADERS::FileHeader, IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_READ, IMAGE_SCN_MEM_WRITE, KdPrint, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_ADDRESS, MiComputeDriverProtection(), MiGetPteAddress, _IMAGE_SECTION_HEADER::Misc, MiSetSystemCodeProtection(), NULL, _IMAGE_FILE_HEADER::NumberOfSections, _IMAGE_NT_HEADERS::OptionalHeader, PAGED_CODE, RtlImageNtHeader(), _IMAGE_OPTIONAL_HEADER::SizeOfImage, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
Referenced by MmInitSystem(), and MmLoadSystemImage().
NTSTATUS MmCallDllInitialize (IN PKLDR_DATA_TABLE_ENTRY DataTableEntry, IN PLIST_ENTRY ModuleListHead)
Definition at line 8150 of file sysload.c.
References _UNICODE_STRING::Buffer, CmRegistryMachineSystemCurrentControlSetServices, ExAllocatePoolWithTag, ExFreePool(), _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MiFirstDriverLoadEver, MiLocateExportName(), MiReApplyVerifierToLoadedModules(), MiVerifierThunksAdded, NonPagedPool, NT_SUCCESS, NULL, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlCopyMemory, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and wcschr().
Referenced by MiResolveImageReferences().
NTSTATUS MmCheckSystemImage (IN HANDLE ImageFileHandle, IN LOGICAL PurgeSection)
Definition at line 5474 of file sysload.c.
References _SEGMENT::ControlArea, _FILE_STANDARD_INFORMATION::EndOfFile, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _IMAGE_NT_HEADERS::FileHeader, _CONTROL_AREA::FilePointer, FileStandardInformation, IMAGE_FILE_MACHINE_NATIVE, IMAGE_NT_OPTIONAL_HDR_MAGIC, InitializeObjectAttributes, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LdrVerifyMappedImageMatchesChecksum(), _LARGE_INTEGER::LowPart, _IMAGE_FILE_HEADER::Machine, _IMAGE_OPTIONAL_HEADER::Magic, MmPurgeSection(), MmSectionObjectType, MmVerifyImageIsOkForMpUse(), NT_SUCCESS, NtCurrentProcess, NULL, NumberOfBytes, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_EXECUTE, PAGED_CODE, _EPROCESS::Pcb, PsInitialSystemProcess, RtlImageNtHeader(), SEC_COMMIT, SEC_IMAGE, SECTION_MAP_EXECUTE, _FILE_OBJECT::SectionObjectPointer, _SECTION::Segment, Status, STATUS_IMAGE_CHECKSUM_MISMATCH, STATUS_IMAGE_MP_UP_MISMATCH, STATUS_INVALID_IMAGE_PROTECT, TRUE, ViewShare, ZwClose(), ZwCreateSection(), ZwMapViewOfSection(), ZwQueryInformationFile(), and ZwUnmapViewOfSection().
Referenced by MmLoadSystemImage(), and PsLocateSystemDll().
VOID MmFreeDriverInitialization (IN PVOID ImageHandle)
Definition at line 2575 of file sysload.c.
References ASSERT, _IMAGE_SECTION_HEADER::Characteristics, _KLDR_DATA_TABLE_ENTRY::DllBase, FALSE, _IMAGE_NT_HEADERS::FileHeader, IMAGE_SCN_MEM_DISCARDABLE, InterlockedExchangeAdd(), MI_DELETE_FLUSH_TB, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_ADDRESS, MiDeleteSystemPageableVm(), MiGetPteAddress, MiReturnCommitment, MM_DBG_COMMIT_RETURN_DRIVER_INIT_CODE, MM_RESAVAIL_FREE_DRIVER_INITIALIZATION, MM_TRACK_COMMIT, MmDriverCommit, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGE_SHIFT, ROUND_TO_PAGES, RtlImageNtHeader(), _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by IopLoadDriver().
NTKERNELAPI PVOID MmGetSystemRoutineAddress (__in PUNICODE_STRING SystemRoutineName)
Definition at line 8276 of file sysload.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceSharedLite(), ExReleaseResourceLite(), FALSE, _LIST_ENTRY::Flink, HAL_NAME, KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KERNEL_NAME, KernelMode, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MiFindExportedRoutineByName(), MmShortTime, NT_SUCCESS, NULL, PASSIVE_LEVEL, RtlEqualUnicodeString(), RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), Status, and TRUE.
NTSTATUS MmLoadSystemImage (IN PUNICODE_STRING ImageFileName, IN PUNICODE_STRING NamePrefix OPTIONAL, IN PUNICODE_STRING LoadedBaseName OPTIONAL, IN ULONG LoadFlags, OUT PVOID * ImageHandle, OUT PVOID * ImageBaseAddress)
Definition at line 761 of file sysload.c.
References _wcsnicmp(), _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _SEGMENT::BasedAddress, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, _IMAGE_FILE_HEADER::Characteristics, _NON_PAGED_DEBUG_INFO::Characteristics, _KLDR_DATA_TABLE_ENTRY::CheckSum, _IMAGE_OPTIONAL_HEADER::CheckSum, _NON_PAGED_DEBUG_INFO::CheckSum, CONTAINING_RECORD, _SEGMENT::ControlArea, _IMAGE_OPTIONAL_HEADER::DataDirectory, DbgBreakPoint(), DbgLoadImageSymbols(), DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_MM_ID, DPFLTR_TRACE_LEVEL, DPFLTR_WARNING_LEVEL, _KLDR_DATA_TABLE_ENTRY::EntryPoint, _IO_ERROR_LOG_PACKET::ErrorCode, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FILE_ATTRIBUTE_NORMAL, FILE_EXECUTE, FILE_OVERWRITE_IF, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SYNCHRONOUS_IO_NONALERT, _IMAGE_NT_HEADERS::FileHeader, _CONTROL_AREA::FilePointer, _IO_ERROR_LOG_PACKET::FinalStatus, _KLDR_DATA_TABLE_ENTRY::Flags, _NON_PAGED_DEBUG_INFO::Flags, _CONTROL_AREA::Flags, FLG_SHOW_LDR_SNAPS, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::FloppyMedia, _KLDR_DATA_TABLE_ENTRY::FullDllName, IMAGE_ADDRESSING_MODE_32BIT, IMAGE_DIRECTORY_ENTRY_DEBUG, _IMAGE_INFO::ImageAddressingMode, _IMAGE_INFO::ImageBase, _NON_PAGED_DEBUG_INFO::ImageBase, _IMAGE_INFO::ImageSectionNumber, _IMAGE_INFO::ImageSelector, _IMAGE_INFO::ImageSize, InitializeObjectAttributes, InterlockedCompareExchange(), InterlockedOr(), IoAllocateGenericErrorLogEntry(), IoWriteErrorLogEntry(), KdDebuggerEnabled, KdDebuggerNotPresent, KdPrint, KdPullRemoteFile(), KeCompactServiceTable(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseMutant(), KernelMode, KeSweepIcache, KeWaitForSingleObject(), LDRP_DEBUG_SYMBOLS_LOADED, LDRP_ENTRY_NATIVE, LDRP_ENTRY_PROCESSED, LDRP_LOAD_IN_PROGRESS, LDRP_MM_LOADED, LDRP_NON_PAGED_DEBUG_INFO, LDRP_SYSTEM_MAPPED, LdrRelocateImage(), _UNICODE_STRING::Length, _KLDR_DATA_TABLE_ENTRY::LoadCount, _KLDR_DATA_TABLE_ENTRY::LoadedImports, LookupEntryPoint(), _IMAGE_FILE_HEADER::Machine, _NON_PAGED_DEBUG_INFO::Machine, _IMAGE_OPTIONAL_HEADER::MajorImageVersion, _IMAGE_OPTIONAL_HEADER::MajorOperatingSystemVersion, MAXIMUM_FILENAME_LENGTH, _UNICODE_STRING::MaximumLength, MAXUCHAR, MI_IS_SESSION_ADDRESS, MI_LOG_SESSION_DATA_START, MI_ROUND_TO_SIZE, MiApplyDriverVerifier(), MiCacheImageSymbols(), MiCaptureImageExceptionValues(), MiEnablePagingOfDriver(), MiFirstDriverLoadEver, MiGetPteAddress, MiLoadImageSection(), MiProcessLoaderEntry(), MiResolveImageReferences(), MiSessionInsertImage(), MiSessionProcessGlobalSubsections(), MiSetSystemCodeProtection(), MiUseLargeDriverPage(), MiWriteProtectSystemImage(), MM_EXECUTE_WRITECOPY, MM_LOAD_IMAGE_AND_LOCKDOWN, MM_LOAD_IMAGE_IN_SESSION, MmCheckSystemImage(), MmIsRetryIoStatus, MmSectionObjectType, MmUnloadSystemImage(), NO_IMPORTS_USED, NON_PAGED_DEBUG_SIGNATURE, _KLDR_DATA_TABLE_ENTRY::NonPagedDebugInfo, NonPagedPool, NT_SUCCESS, NtGlobalFlag, NULL, _IMAGE_OPTIONAL_HEADER::NumberOfRvaAndSizes, _IO_ERROR_LOG_PACKET::NumberOfStrings, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, OBJ_NAME_PATH_SEPARATOR, ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGE_EXECUTE, PAGE_SHIFT, PAGED_CODE, PagedPool, _KLDR_DATA_TABLE_ENTRY::PatchInformation, POOL_COLD_ALLOCATION, PpPagePathAssign(), _IMAGE_INFO::Properties, PS_PROCESS_FLAGS_IN_SESSION, PsCallImageNotifyRoutines(), PsGetCurrentProcess(), PsImageNotifyEnabled, PsLoadedModuleList, PtrToUlong, RtlAnsiStringToUnicodeString(), RtlAppendUnicodeStringToString(), RtlCopyMemory, RtlEqualUnicodeString(), RtlFreeUnicodeString(), RtlImageNtHeader(), RtlInitAnsiString(), RtlInitString(), RtlInitUnicodeString(), RtlZeroMemory, SATISFY_OVERZEALOUS_COMPILER, SEC_IMAGE, SECTION_ALL_ACCESS, SECTION_MAP_EXECUTE, SECTION_MAP_READ, _KLDR_DATA_TABLE_ENTRY::SectionPointer, _SECTION::Segment, SharedUserData, _NON_PAGED_DEBUG_INFO::Signature, _IMAGE_DATA_DIRECTORY::Size, _NON_PAGED_DEBUG_INFO::Size, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _IMAGE_OPTIONAL_HEADER::SizeOfImage, _NON_PAGED_DEBUG_INFO::SizeOfImage, sprintf(), Status, STATUS_ALREADY_COMMITTED, STATUS_CONFLICTING_ADDRESSES, STATUS_DRIVER_ENTRYPOINT_NOT_FOUND, STATUS_DRIVER_ORDINAL_NOT_FOUND, STATUS_DRIVER_UNABLE_TO_LOAD, STATUS_IMAGE_ALREADY_LOADED, STATUS_IMAGE_CHECKSUM_MISMATCH, STATUS_IMAGE_MP_UP_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_IMAGE_PROTECT, STATUS_LOG_HARD_ERROR, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PROCEDURE_NOT_FOUND, STATUS_SUCCESS, _IO_ERROR_LOG_PACKET::StringOffset, _IMAGE_INFO::SystemModeImage, _IMAGE_FILE_HEADER::TimeDateStamp, _NON_PAGED_DEBUG_INFO::TimeDateStamp, _SEGMENT::TotalNumberOfPtes, TRUE, _CONTROL_AREA::u, UNICODE_NULL, _IO_ERROR_LOG_PACKET::UniqueErrorValue, _IMAGE_DATA_DIRECTORY::VirtualAddress, wcslen(), WrVirtualMemory, X64K, ZwClose(), ZwCreateSection(), and ZwOpenFile().
Referenced by IopLoadDriver(), MiResolveImageReferences(), and NtSetSystemInformation().
PUNICODE_STRING MmLocateUnloadedDriver (IN PVOID VirtualAddress)
Definition at line 3464 of file sysload.c.
References _UNICODE_STRING::Buffer, Index, MI_UNLOADED_DRIVERS, MmLastUnloadedDriver, _UNLOADED_DRIVERS::Name, NULL, and _UNLOADED_DRIVERS::StartAddress.
Referenced by KeBugCheck2().
VOID MmMakeKernelResourceSectionWritable (VOID)
Definition at line 7864 of file sysload.c.
References _MMPTE::Hard, MI_FLUSH_CURRENT_TB, MI_IS_PHYSICAL_ADDRESS, MI_MAKE_VALID_KERNEL_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiGetVirtualAddressMappedByPte, MiKernelResourceStartPte, MM_READWRITE, NULL, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPTE_HARDWARE::Writable, and _MMPTE_HARDWARE::Write.
Referenced by KeGetBugMessageText().
PVOID MmPageEntireDriver (__in PVOID AddressWithinSection)
Definition at line 3088 of file sysload.c.
References ASSERT, _KLDR_DATA_TABLE_ENTRY::DllBase, FALSE, KeFlushQueuedDpcs(), MI_IS_SESSION_IMAGE_ADDRESS, MiGetPteAddress, MiLookupDataTableEntry(), MiSetPagingOfDriver(), MM_SYSTEM_CODE_LOCKED_DOWN, MmDisablePagingExecutive, NULL, PAGE_SHIFT, PAGED_CODE, _KLDR_DATA_TABLE_ENTRY::SectionPointer, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, and TRUE.
VOID MmResetDriverPaging (__in PVOID AddressWithinSection)
Definition at line 3170 of file sysload.c.
References ASSERT, _IMAGE_SECTION_HEADER::Characteristics, DbgPrintEx(), _KLDR_DATA_TABLE_ENTRY::DllBase, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, FALSE, _IMAGE_NT_HEADERS::FileHeader, _KLDR_DATA_TABLE_ENTRY::FullDllName, IMAGE_SCN_MEM_DISCARDABLE, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MiGetPteAddress, MiLockCode(), MiLookupDataTableEntry(), _IMAGE_SECTION_HEADER::Misc, MM_LOCK_BY_NONPAGE, MM_SYSTEM_CODE_LOCKED_DOWN, MmDisablePagingExecutive, _IMAGE_SECTION_HEADER::Name, NOTHING, NULL, _IMAGE_FILE_HEADER::NumberOfSections, PAGED_CODE, RtlImageNtHeader(), _KLDR_DATA_TABLE_ENTRY::SectionPointer, _IMAGE_FILE_HEADER::SizeOfOptionalHeader, _IMAGE_SECTION_HEADER::SizeOfRawData, TRUE, _IMAGE_SECTION_HEADER::VirtualAddress, and _IMAGE_SECTION_HEADER::VirtualSize.
NTSTATUS MmUnloadSystemImage (IN PVOID ImageHandle)
Definition at line 3524 of file sysload.c.
References ASSERT, _SEGMENT::BasedAddress, _KLDR_DATA_TABLE_ENTRY::BaseDllName, _UNICODE_STRING::Buffer, _MM_SESSION_SPACE::CommittedPages, DbgUnLoadImageSymbols(), _KLDR_DATA_TABLE_ENTRY::DllBase, DRIVER_VERIFIER_DEADLOCK_DETECTION, ExFreePool(), FALSE, _KLDR_DATA_TABLE_ENTRY::Flags, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _SEGMENT::ImageCommitment, _IMAGE_ENTRY_IN_SESSION::ImageCountInThisSession, _KLDR_DATA_TABLE_ENTRY::InLoadOrderLinks, InterlockedExchangeAdd(), InterlockedExchangeAddSizeT, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KeReleaseMutant(), KernelMode, KeWaitForSingleObject(), LDRP_DEBUG_SYMBOLS_LOADED, LDRP_IMAGE_VERIFYING, LDRP_SYSTEM_MAPPED, _MM_DRIVER_VERIFIER_DATA::Level, _KLDR_DATA_TABLE_ENTRY::LoadCount, LOADED_AT_BOOT, _KLDR_DATA_TABLE_ENTRY::LoadedImports, MI_DELETE_FLUSH_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_SESSION_IMAGE_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_ROUND_TO_SIZE, MiActiveVerifierThunks, MiClearImports(), MiDeleteSystemPageableVm(), MiDereferenceImports(), MiFreeContiguousPages(), MiGetPdeAddress, MiGetPteAddress, MiGetPteOffset, MiProcessLoaderEntry(), MiReleaseSystemPtes(), MiRememberUnloadedDriver(), MiRemoveCachedRange(), MiRemoveImageSessionWide(), MiReturnCommitment, MiRundownHotpatchList(), MiSessionLookupImage(), MiUnmapLargePages(), MiVerifierCheckThunks(), MiVerifyingDriverUnloading(), MM_BUMP_SESS_COUNTER, MM_DBG_COMMIT_RETURN_DRIVER_UNLOAD, MM_DBG_COMMIT_RETURN_DRIVER_UNLOAD1, MM_DBG_SESSION_COMMIT_IMAGE_UNLOAD, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE, MM_RESAVAIL_FREE_UNLOAD_SYSTEM_IMAGE1, MM_TRACK_COMMIT, MmDriverCommit, MmSessionSpace, MmSnapUnloads, MmTotalSystemDriverPages, MmVerifierData, NT_SUCCESS, NULL, NumberOfBytes, ObDereferenceObject(), PAGE_SHIFT, _KLDR_DATA_TABLE_ENTRY::PatchInformation, RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), _KLDR_DATA_TABLE_ENTRY::SectionPointer, _SECTION::Segment, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, Status, STATUS_SUCCESS, SystemPteSpace, _SEGMENT::TotalNumberOfPtes, TRUE, _SEGMENT::u1, VerifierDeadlockFreePool(), and WrVirtualMemory.
Referenced by IopDeleteDriver(), IopLoadDriver(), MiCallDllUnloadAndUnloadDll(), MiResolveImageReferences(), MiSessionUnloadAllImages(), MmLoadSystemImage(), and NtSetSystemInformation().
BOOLEAN MmVerifyImageIsOkForMpUse (IN PVOID BaseAddress)
Definition at line 5686 of file sysload.c.
References _IMAGE_FILE_HEADER::Characteristics, FALSE, _IMAGE_NT_HEADERS::FileHeader, IMAGE_FILE_UP_SYSTEM_ONLY, KeNumberProcessors, NULL, PAGED_CODE, RtlImageNtHeader(), and TRUE.
Referenced by ExpInitializeExecutive(), and MmCheckSystemImage().
Variable Documentation
PVOID ExPoolCodeEnd
Definition at line 59 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID ExPoolCodeStart
Definition at line 58 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
LONG MiFirstDriverLoadEver = 0
Definition at line 28 of file sysload.c.
Referenced by MmCallDllInitialize(), and MmLoadSystemImage().
PMMPTE MiKernelResourceEndPte
Definition at line 7747 of file sysload.c.
PMMPTE MiKernelResourceStartPte
Definition at line 7746 of file sysload.c.
Referenced by MmMakeKernelResourceSectionWritable().
ULONG MiLargePageAllDrivers
Definition at line 334 of file sysload.c.
Referenced by MiInitializeDriverLargePageList(), and MiUseLargeDriverPage().
LIST_ENTRY MiLargePageDriverList
Definition at line 332 of file sysload.c.
ULONG MiTotalUnloads
Definition at line 45 of file sysload.c.
Referenced by MiRememberUnloadedDriver().
ULONG MiUnloadsSkipped
Definition at line 46 of file sysload.c.
Referenced by MiRememberUnloadedDriver().
ULONG MmDriverCommit
Definition at line 26 of file sysload.c.
Referenced by MiLoadImageSection(), MmFreeDriverInitialization(), and MmUnloadSystemImage().
ULONG MmEnforceWriteProtection = 1
Definition at line 52 of file sysload.c.
Referenced by MiComputeDriverProtection(), and MmInitSystem().
ULONG MmLastUnloadedDriver
Definition at line 44 of file sysload.c.
Referenced by MiRememberUnloadedDriver(), and MmLocateUnloadedDriver().
LOGICAL MmMakeLowMemory = TRUE
Definition at line 35 of file sysload.c.
Referenced by MiInitMachineDependent(), and MiReloadBootLoadedDrivers().
PVOID MmPoolCodeEnd
Definition at line 61 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID MmPoolCodeStart
Definition at line 60 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID MmPteCodeEnd
Definition at line 63 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
PVOID MmPteCodeStart
Definition at line 62 of file sysload.c.
Referenced by KeBugCheck2(), and MiLocateKernelSections().
KMUTANT MmSystemLoadLock
Definition at line 22 of file sysload.c.
Referenced by MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiShutdownSystem(), and MmInitSystem().
LONG MmTotalSystemDriverPages
Definition at line 24 of file sysload.c.
Referenced by MiLockCode(), MiSetPagingOfDriver(), MiUseLargeDriverPage(), MmUnloadSystemImage(), and NtQuerySystemInformation().
PUNLOADED_DRIVERS MmUnloadedDrivers
Definition at line 42 of file sysload.c.
Referenced by MiReleaseAllMemory().
LIST_ENTRY PsLoadedModuleList
Definition at line 7966 of file sysload.c.
Referenced by IopInitializeBootLogging(), IopInitializeBuiltinDriver(), IopLoadDriver(), KevUtilAddressToFileHeader(), KiPcToFileHeader(), MiBuildImportsForBootDrivers(), MiCheckCacheAttributes(), MiDereferenceImports(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiGetHighestPteConsumer(), MiLookupDataTableEntry(), MiProcessLoaderEntry(), MiReleaseAllMemory(), MiResolveImageReferences(), MiShutdownSystem(), MiSnapThunk(), MmInitSystem(), MmLoadSystemImage(), NtQuerySystemInformation(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
ERESOURCE PsLoadedModuleResource
Definition at line 7967 of file sysload.c.
Referenced by IopInitializeBootLogging(), IopLoadDriver(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiProcessLoaderEntry(), MmGetSectionRange(), MmInitSystem(), MmLockPageableDataSection(), and NtQuerySystemInformation().
PVOID PsNtosImageBase
Definition at line 7952 of file sysload.c.
Referenced by MiInitializeLoadedModuleList().