Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/filelock.c File Reference
filelock.c File Reference
#include "FsRtlP.h"
Data Structures
struct _EX_LOCK
struct _LOCK_INFO
struct _LOCK_QUEUE
struct _LOCKTREE_NODE
struct _SH_LOCK
struct _WAITING_LOCK
Macros
#define Dbg (0x20000000)
#define FsRtlAcquireCancelCollide(a) ExAcquireSpinLock(&FsRtlFileLockCancelCollideLock, a)
#define FsRtlAcquireCancelCollideAtDpc(a) ExAcquireSpinLockAtDpcLevel(&FsRtlFileLockCancelCollideLock)
#define FsRtlAcquireLockQueue(a, b) ExAcquireSpinLock(&(a)->QueueSpinLock, b)
#define FsRtlAcquireLockQueueAtDpc(a) ExAcquireSpinLockAtDpcLevel(&(a)->QueueSpinLock)
#define FsRtlCompleteLockIrp(A, B, C, D, E, F)
#define FsRtlReleaseCancelCollide(a) ExReleaseSpinLock(&FsRtlFileLockCancelCollideLock, a)
#define FsRtlReleaseCancelCollideFromDpc(a) ExReleaseSpinLockFromDpcLevel(&FsRtlFileLockCancelCollideLock)
#define FsRtlReleaseLockQueue(a, b) ExReleaseSpinLock(&(a)->QueueSpinLock, b)
#define FsRtlReleaseLockQueueFromDpc(a) ExReleaseSpinLockFromDpcLevel(&(a)->QueueSpinLock)
#define INLINE __inline
#define TAG_EXCLUSIVE_LOCK 'xeLF'
#define TAG_FILE_LOCK 'lfLF'
#define TAG_LOCK_INFO 'ilLF'
#define TAG_LOCKTREE_NODE 'nlLF'
#define TAG_SHARED_LOCK 'hsLF'
#define TAG_WAITING_LOCK 'lwLF'
Typedefs
typedef struct _EX_LOCK EX_LOCK
typedef struct _LOCK_INFO LOCK_INFO
typedef struct _LOCK_QUEUE LOCK_QUEUE
typedef struct _LOCKTREE_NODE LOCKTREE_NODE
typedef struct _EX_LOCK * PEX_LOCK
typedef struct _LOCK_INFO * PLOCK_INFO
typedef struct _LOCK_QUEUE * PLOCK_QUEUE
typedef struct _LOCKTREE_NODE * PLOCKTREE_NODE
typedef struct _SH_LOCK * PSH_LOCK
typedef struct _WAITING_LOCK * PWAITING_LOCK
typedef struct _SH_LOCK SH_LOCK
typedef struct _WAITING_LOCK WAITING_LOCK
Functions
INLINE PEX_LOCK FsRtlAllocateExclusiveLock (VOID)
PFILE_LOCK FsRtlAllocateFileLock (__in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
INLINE PLOCK_INFO FsRtlAllocateLockInfo (VOID)
INLINE PLOCKTREE_NODE FsRtlAllocateLockTreeNode (VOID)
INLINE PSH_LOCK FsRtlAllocateSharedLock (VOID)
INLINE PWAITING_LOCK FsRtlAllocateWaitingLock (VOID)
BOOLEAN FsRtlCheckLockForReadAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
BOOLEAN FsRtlCheckLockForWriteAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
BOOLEAN FsRtlCheckNoExclusiveConflict (IN PLOCK_QUEUE LockQueue, IN PLARGE_INTEGER Starting, IN PLARGE_INTEGER Ending, IN ULONG Key, IN PFILE_OBJECT FileObject, IN PVOID ProcessId)
BOOLEAN FsRtlCheckNoSharedConflict (IN PLOCK_QUEUE LockQueue, IN PLARGE_INTEGER Starting, IN PLARGE_INTEGER Ending)
INLINE VOID FsRtlCompleteLockIrpReal (IN PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, IN PVOID Context, IN PIRP Irp, IN NTSTATUS Status, IN PNTSTATUS NewStatus, IN PFILE_OBJECT FileObject)
BOOLEAN FsRtlFastCheckLockForRead (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PFILE_OBJECT FileObject, __in PVOID ProcessId)
BOOLEAN FsRtlFastCheckLockForWrite (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PVOID FileObject, __in PVOID ProcessId)
NTSTATUS FsRtlFastUnlockAll (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in_opt PVOID Context)
NTSTATUS FsRtlFastUnlockAllByKey (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context)
NTSTATUS FsRtlFastUnlockSingle (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in LARGE_INTEGER UNALIGNED *FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
NTSTATUS FsRtlFastUnlockSingleExclusive (IN PLOCK_INFO LockInfo, IN PFILE_OBJECT FileObject, IN LARGE_INTEGER UNALIGNED *FileOffset, IN PLARGE_INTEGER Length, IN PEPROCESS ProcessId, IN ULONG Key, IN PVOID Context OPTIONAL, IN BOOLEAN IgnoreUnlockRoutine, IN BOOLEAN CheckForWaiters)
NTSTATUS FsRtlFastUnlockSingleShared (IN PLOCK_INFO LockInfo, IN PFILE_OBJECT FileObject, IN LARGE_INTEGER UNALIGNED *FileOffset, IN PLARGE_INTEGER Length, IN PEPROCESS ProcessId, IN ULONG Key, IN PVOID Context OPTIONAL, IN BOOLEAN IgnoreUnlockRoutine, IN BOOLEAN CheckForWaiters)
PSH_LOCK FsRtlFindFirstOverlapInNode (IN PLOCKTREE_NODE Node, IN PLARGE_INTEGER StartingByte, IN PLARGE_INTEGER EndingByte)
PRTL_SPLAY_LINKS FsRtlFindFirstOverlappingExclusiveNode (IN PRTL_SPLAY_LINKS Tree, IN PLARGE_INTEGER StartingByte, IN PLARGE_INTEGER EndingByte, IN OUT PRTL_SPLAY_LINKS *LastEdgeNode, IN OUT PBOOLEAN GreaterThan)
PRTL_SPLAY_LINKS FsRtlFindFirstOverlappingSharedNode (IN PRTL_SPLAY_LINKS Tree, IN PLARGE_INTEGER StartingByte, IN PLARGE_INTEGER EndingByte, IN OUT PRTL_SPLAY_LINKS *LastEdgeNode, IN OUT PBOOLEAN GreaterThan)
INLINE VOID FsRtlFreeExclusiveLock (IN PEX_LOCK C)
VOID FsRtlFreeFileLock (__in PFILE_LOCK FileLock)
INLINE VOID FsRtlFreeLockInfo (IN PLOCK_INFO C)
INLINE VOID FsRtlFreeLockTreeNode (IN PLOCKTREE_NODE C)
INLINE VOID FsRtlFreeSharedLock (IN PSH_LOCK C)
INLINE VOID FsRtlFreeWaitingLock (IN PWAITING_LOCK C)
PFILE_LOCK_INFO FsRtlGetNextFileLock (__in PFILE_LOCK FileLock, __in BOOLEAN Restart)
VOID FsRtlInitializeFileLock (__in PFILE_LOCK FileLock, __in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
VOID FsRtlInitializeFileLocks (VOID)
VOID FsRtlPrivateCancelFileLockIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
BOOLEAN FsRtlPrivateCheckForExclusiveLockAccess (IN PLOCK_QUEUE LockInfo, IN PFILE_LOCK_INFO FileLockInfo)
BOOLEAN FsRtlPrivateCheckForSharedLockAccess (IN PLOCK_QUEUE LockInfo, IN PFILE_LOCK_INFO FileLockInfo)
VOID FsRtlPrivateCheckWaitingLocks (IN PLOCK_INFO LockInfo, IN PLOCK_QUEUE LockQueue, IN KIRQL OldIrql)
NTSTATUS FsRtlPrivateFastUnlockAll (IN PFILE_LOCK FileLock, IN PFILE_OBJECT FileObject, IN PEPROCESS ProcessId, IN ULONG Key, IN BOOLEAN MatchKey, IN PVOID Context OPTIONAL)
BOOLEAN FsRtlPrivateInitializeFileLock (IN PFILE_LOCK FileLock, IN BOOLEAN ViaFastCall)
VOID FsRtlPrivateInsertExclusiveLock (IN PLOCK_QUEUE LockQueue, IN PEX_LOCK NewLock)
BOOLEAN FsRtlPrivateInsertLock (IN PLOCK_INFO LockInfo, IN PFILE_OBJECT FileObject, IN PFILE_LOCK_INFO FileLockInfo)
BOOLEAN FsRtlPrivateInsertSharedLock (IN PLOCK_QUEUE LockQueue, IN PSH_LOCK NewLock)
BOOLEAN FsRtlPrivateLock (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in BOOLEAN FailImmediately, __in BOOLEAN ExclusiveLock, __out PIO_STATUS_BLOCK Iosb, __in_opt PIRP Irp, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
VOID FsRtlPrivateRemoveLock (IN PLOCK_INFO LockInfo, IN PFILE_LOCK_INFO, IN BOOLEAN CheckForWaiters)
VOID FsRtlPrivateResetLowestLockOffset (PLOCK_INFO LockInfo)
NTSTATUS FsRtlProcessFileLock (__in PFILE_LOCK FileLock, __in PIRP Irp, __in_opt PVOID Context)
VOID FsRtlSplitLocks (IN PLOCKTREE_NODE ParentNode, IN PSINGLE_LIST_ENTRY *pStartLink, IN PLARGE_INTEGER LastShadowedByte, IN PLARGE_INTEGER GlueOffset)
VOID FsRtlUninitializeFileLock (__in PFILE_LOCK FileLock)
Variables
KGUARDED_MUTEX FsRtlCreateLockInfo
NPAGED_LOOKASIDE_LIST FsRtlExclusiveLockLookasideList
SINGLE_LIST_ENTRY FsRtlFileLockCancelCollideList
KSPIN_LOCK FsRtlFileLockCancelCollideLock
PAGED_LOOKASIDE_LIST FsRtlFileLockLookasideList
NPAGED_LOOKASIDE_LIST FsRtlLockInfoLookasideList
NPAGED_LOOKASIDE_LIST FsRtlLockTreeNodeLookasideList
NPAGED_LOOKASIDE_LIST FsRtlSharedLockLookasideList
NPAGED_LOOKASIDE_LIST FsRtlWaitingLockLookasideList
Macro Definition Documentation
#define Dbg (0x20000000)
Definition at line 90 of file filelock.c.
Referenced by FsRtlCheckLockForReadAccess(), FsRtlCheckLockForWriteAccess(), FsRtlCheckNoExclusiveConflict(), FsRtlFastCheckLockForRead(), FsRtlFastCheckLockForWrite(), FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), FsRtlGetNextFileLock(), FsRtlInitializeFileLock(), FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlPrivateInsertSharedLock(), FsRtlPrivateLock(), FsRtlProcessFileLock(), and FsRtlUninitializeFileLock().
#define FsRtlAcquireCancelCollide (a) ExAcquireSpinLock(&FsRtlFileLockCancelCollideLock, a)
Definition at line 499 of file filelock.c.
Referenced by FsRtlPrivateCancelFileLockIrp(), and FsRtlUninitializeFileLock().
#define FsRtlAcquireCancelCollideAtDpc (a) ExAcquireSpinLockAtDpcLevel(&FsRtlFileLockCancelCollideLock)
Definition at line 501 of file filelock.c.
#define FsRtlAcquireLockQueue (a, b) ExAcquireSpinLock(&(a)->QueueSpinLock, b)
Definition at line 494 of file filelock.c.
Referenced by FsRtlFastCheckLockForRead(), FsRtlFastCheckLockForWrite(), FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), FsRtlGetNextFileLock(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), and FsRtlPrivateLock().
#define FsRtlAcquireLockQueueAtDpc (a) ExAcquireSpinLockAtDpcLevel(&(a)->QueueSpinLock)
Definition at line 496 of file filelock.c.
Referenced by FsRtlPrivateCancelFileLockIrp(), and FsRtlUninitializeFileLock().
#define FsRtlCompleteLockIrp (A, B, C, D, E, F)
Value:
FsRtlCompleteLockIrpReal((A)->CompleteLockIrpRoutine,  \
                                  B,                            \
                                  C,                            \
                                  D,                            \
                                  E,                            \
                                  F )
Definition at line 511 of file filelock.c.
Referenced by FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), FsRtlPrivateLock(), FsRtlProcessFileLock(), and FsRtlUninitializeFileLock().
#define FsRtlReleaseCancelCollide (a) ExReleaseSpinLock(&FsRtlFileLockCancelCollideLock, a)
Definition at line 500 of file filelock.c.
Referenced by FsRtlPrivateCancelFileLockIrp(), and FsRtlUninitializeFileLock().
#define FsRtlReleaseCancelCollideFromDpc (a) ExReleaseSpinLockFromDpcLevel(&FsRtlFileLockCancelCollideLock)
Definition at line 502 of file filelock.c.
Referenced by FsRtlPrivateCancelFileLockIrp().
#define FsRtlReleaseLockQueue (a, b) ExReleaseSpinLock(&(a)->QueueSpinLock, b)
Definition at line 495 of file filelock.c.
Referenced by FsRtlFastCheckLockForRead(), FsRtlFastCheckLockForWrite(), FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), FsRtlGetNextFileLock(), FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), and FsRtlPrivateLock().
#define FsRtlReleaseLockQueueFromDpc (a) ExReleaseSpinLockFromDpcLevel(&(a)->QueueSpinLock)
Definition at line 497 of file filelock.c.
Referenced by FsRtlUninitializeFileLock().
#define INLINE __inline
Definition at line 97 of file filelock.c.
#define TAG_EXCLUSIVE_LOCK 'xeLF'
Definition at line 100 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
#define TAG_FILE_LOCK 'lfLF'
Definition at line 101 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
#define TAG_LOCK_INFO 'ilLF'
Definition at line 102 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
#define TAG_LOCKTREE_NODE 'nlLF'
Definition at line 103 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
#define TAG_SHARED_LOCK 'hsLF'
Definition at line 104 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
#define TAG_WAITING_LOCK 'lwLF'
Definition at line 105 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
Typedef Documentation
typedef struct _EX_LOCK EX_LOCK
typedef struct _LOCK_INFO LOCK_INFO
typedef struct _LOCK_QUEUE LOCK_QUEUE
typedef struct _LOCKTREE_NODE LOCKTREE_NODE
typedef struct _EX_LOCK * PEX_LOCK
typedef struct _LOCK_INFO * PLOCK_INFO
typedef struct _LOCK_QUEUE * PLOCK_QUEUE
typedef struct _LOCKTREE_NODE * PLOCKTREE_NODE
typedef struct _SH_LOCK * PSH_LOCK
typedef struct _WAITING_LOCK * PWAITING_LOCK
typedef struct _SH_LOCK SH_LOCK
typedef struct _WAITING_LOCK WAITING_LOCK
Function Documentation
INLINE PEX_LOCK FsRtlAllocateExclusiveLock (VOID)
Definition at line 414 of file filelock.c.
References ExAllocateFromNPagedLookasideList(), and FsRtlExclusiveLockLookasideList.
Referenced by FsRtlPrivateInsertLock().
PFILE_LOCK FsRtlAllocateFileLock (__in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
Definition at line 1147 of file filelock.c.
References ExAllocateFromPagedLookasideList(), FsRtlFileLockLookasideList, FsRtlInitializeFileLock(), and NULL.
INLINE PLOCK_INFO FsRtlAllocateLockInfo (VOID)
Definition at line 441 of file filelock.c.
References ExAllocateFromNPagedLookasideList(), and FsRtlLockInfoLookasideList.
Referenced by FsRtlPrivateInitializeFileLock().
INLINE PLOCKTREE_NODE FsRtlAllocateLockTreeNode (VOID)
Definition at line 432 of file filelock.c.
References ExAllocateFromNPagedLookasideList(), and FsRtlLockTreeNodeLookasideList.
Referenced by FsRtlPrivateInsertSharedLock(), and FsRtlSplitLocks().
INLINE PSH_LOCK FsRtlAllocateSharedLock (VOID)
Definition at line 405 of file filelock.c.
References ExAllocateFromNPagedLookasideList(), and FsRtlSharedLockLookasideList.
Referenced by FsRtlPrivateInsertLock().
INLINE PWAITING_LOCK FsRtlAllocateWaitingLock (VOID)
Definition at line 423 of file filelock.c.
References ExAllocateFromNPagedLookasideList(), and FsRtlWaitingLockLookasideList.
Referenced by FsRtlPrivateLock().
BOOLEAN FsRtlCheckLockForReadAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
Definition at line 1320 of file filelock.c.
References Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, _IO_STACK_LOCATION::FileObject, FsRtlFastCheckLockForRead(), IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, _LARGE_INTEGER::LowPart, NULL, _IO_STACK_LOCATION::Parameters, _LARGE_INTEGER::QuadPart, and TRUE.
BOOLEAN FsRtlCheckLockForWriteAccess (__in PFILE_LOCK FileLock, __in PIRP Irp)
Definition at line 1421 of file filelock.c.
References Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, _IO_STACK_LOCATION::FileObject, FsRtlFastCheckLockForWrite(), IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, _LARGE_INTEGER::LowPart, NULL, _IO_STACK_LOCATION::Parameters, _LARGE_INTEGER::QuadPart, _LOCK_QUEUE::SharedLockTree, and TRUE.
BOOLEAN FsRtlCheckNoExclusiveConflict (IN PLOCK_QUEUE LockQueue, IN PLARGE_INTEGER Starting, IN PLARGE_INTEGER Ending, IN ULONG Key, IN PFILE_OBJECT FileObject, IN PVOID ProcessId)
Definition at line 2474 of file filelock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, FALSE, _FILE_LOCK_INFO::FileObject, FsRtlFindFirstOverlappingExclusiveNode(), _FILE_LOCK_INFO::Key, _EX_LOCK::LockInfo, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlRealSuccessor(), RtlSplay(), _FILE_LOCK_INFO::StartingByte, Status, and TRUE.
Referenced by FsRtlFastCheckLockForRead(), and FsRtlFastCheckLockForWrite().
BOOLEAN FsRtlCheckNoSharedConflict (IN PLOCK_QUEUE LockQueue, IN PLARGE_INTEGER Starting, IN PLARGE_INTEGER Ending)
Definition at line 2397 of file filelock.c.
References CONTAINING_RECORD, FALSE, FsRtlFindFirstOverlapInNode(), FsRtlFindFirstOverlappingSharedNode(), _LOCKTREE_NODE::HoleyNode, NULL, RtlSplay(), and TRUE.
Referenced by FsRtlFastCheckLockForWrite().
INLINE VOID FsRtlCompleteLockIrpReal (IN PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, IN PVOID Context, IN PIRP Irp, IN NTSTATUS Status, IN PNTSTATUS NewStatus, IN PFILE_OBJECT FileObject)
Definition at line 521 of file filelock.c.
References FsRtlCompleteRequest, NULL, and Status.
BOOLEAN FsRtlFastCheckLockForRead (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PFILE_OBJECT FileObject, __in PVOID ProcessId)
Definition at line 2587 of file filelock.c.
References Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _LOCK_QUEUE::ExclusiveLockTree, FsRtlAcquireLockQueue, FsRtlCheckNoExclusiveConflict(), FsRtlReleaseLockQueue, _FILE_LOCK_INFO::Key, _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, _FILE_LOCK_INFO::StartingByte, Status, and TRUE.
Referenced by FsRtlCheckLockForReadAccess().
BOOLEAN FsRtlFastCheckLockForWrite (__in PFILE_LOCK FileLock, __in PLARGE_INTEGER StartingByte, __in PLARGE_INTEGER Length, __in ULONG Key, __in PVOID FileObject, __in PVOID ProcessId)
Definition at line 2723 of file filelock.c.
References Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, _LOCK_QUEUE::ExclusiveLockTree, FsRtlAcquireLockQueue, FsRtlCheckNoExclusiveConflict(), FsRtlCheckNoSharedConflict(), FsRtlReleaseLockQueue, _FILE_LOCK_INFO::Key, _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, _LOCK_QUEUE::SharedLockTree, _FILE_LOCK_INFO::StartingByte, Status, and TRUE.
Referenced by FsRtlCheckLockForWriteAccess().
NTSTATUS FsRtlFastUnlockAll (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in_opt PVOID Context)
Definition at line 3778 of file filelock.c.
References FALSE, and FsRtlPrivateFastUnlockAll().
Referenced by FsRtlProcessFileLock().
NTSTATUS FsRtlFastUnlockAllByKey (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context)
Definition at line 3822 of file filelock.c.
References FsRtlPrivateFastUnlockAll(), and TRUE.
Referenced by FsRtlProcessFileLock().
NTSTATUS FsRtlFastUnlockSingle (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in LARGE_INTEGER UNALIGNED * FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
Definition at line 3248 of file filelock.c.
References FALSE, FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), NULL, Status, STATUS_RANGE_NOT_LOCKED, STATUS_SUCCESS, TRUE, and UNREFERENCED_PARAMETER.
Referenced by FsRtlProcessFileLock().
NTSTATUS FsRtlFastUnlockSingleExclusive (IN PLOCK_INFO LockInfo, IN PFILE_OBJECT FileObject, IN LARGE_INTEGER UNALIGNED * FileOffset, IN PLARGE_INTEGER Length, IN PEPROCESS ProcessId, IN ULONG Key, IN PVOID Context OPTIONAL, IN BOOLEAN IgnoreUnlockRoutine, IN BOOLEAN CheckForWaiters)
Definition at line 3597 of file filelock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, _FILE_LOCK_INFO::FileObject, FileOffset, FsRtlAcquireLockQueue, FsRtlFindFirstOverlappingExclusiveNode(), FsRtlFreeExclusiveLock(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateResetLowestLockOffset(), FsRtlReleaseLockQueue, _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _EX_LOCK::Links, _EX_LOCK::LockInfo, _LARGE_INTEGER::LowPart, _SINGLE_LIST_ENTRY::Next, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlDelete(), RtlRealSuccessor(), _FILE_LOCK_INFO::StartingByte, STATUS_RANGE_NOT_LOCKED, STATUS_SUCCESS, and _LOCK_QUEUE::WaitingLocks.
Referenced by FsRtlFastUnlockSingle(), and FsRtlPrivateRemoveLock().
NTSTATUS FsRtlFastUnlockSingleShared (IN PLOCK_INFO LockInfo, IN PFILE_OBJECT FileObject, IN LARGE_INTEGER UNALIGNED * FileOffset, IN PLARGE_INTEGER Length, IN PEPROCESS ProcessId, IN ULONG Key, IN PVOID Context OPTIONAL, IN BOOLEAN IgnoreUnlockRoutine, IN BOOLEAN CheckForWaiters)
Definition at line 3345 of file filelock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::FileObject, FileOffset, FsRtlAcquireLockQueue, FsRtlFindFirstOverlappingSharedNode(), FsRtlFreeLockTreeNode(), FsRtlFreeSharedLock(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateResetLowestLockOffset(), FsRtlReleaseLockQueue, FsRtlSplitLocks(), _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _SH_LOCK::LockInfo, _LOCKTREE_NODE::Locks, _LARGE_INTEGER::LowPart, _SINGLE_LIST_ENTRY::Next, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlDelete(), _LOCK_QUEUE::SharedLockTree, _FILE_LOCK_INFO::StartingByte, STATUS_RANGE_NOT_LOCKED, STATUS_SUCCESS, _LOCKTREE_NODE::Tail, and _LOCK_QUEUE::WaitingLocks.
Referenced by FsRtlFastUnlockSingle(), and FsRtlPrivateRemoveLock().
PSH_LOCK FsRtlFindFirstOverlapInNode (IN PLOCKTREE_NODE Node, IN PLARGE_INTEGER StartingByte, IN PLARGE_INTEGER EndingByte)
Definition at line 1861 of file filelock.c.
References ASSERT, CONTAINING_RECORD, _FILE_LOCK_INFO::EndingByte, FALSE, _FILE_LOCK_INFO::Length, _SH_LOCK::LockInfo, _SINGLE_LIST_ENTRY::Next, NULL, _LARGE_INTEGER::QuadPart, and _FILE_LOCK_INFO::StartingByte.
Referenced by FsRtlCheckNoSharedConflict(), and FsRtlPrivateCheckForExclusiveLockAccess().
PRTL_SPLAY_LINKS FsRtlFindFirstOverlappingExclusiveNode (IN PRTL_SPLAY_LINKS Tree, IN PLARGE_INTEGER StartingByte, IN PLARGE_INTEGER EndingByte, IN OUT PRTL_SPLAY_LINKS * LastEdgeNode, IN OUT PBOOLEAN GreaterThan)
Definition at line 1692 of file filelock.c.
References CONTAINING_RECORD, _FILE_LOCK_INFO::EndingByte, FALSE, _FILE_LOCK_INFO::Length, _EX_LOCK::Links, _EX_LOCK::LockInfo, NULL, _LARGE_INTEGER::QuadPart, RtlLeftChild, RtlRightChild, _FILE_LOCK_INFO::StartingByte, and TRUE.
Referenced by FsRtlCheckNoExclusiveConflict(), FsRtlFastUnlockSingleExclusive(), FsRtlGetNextFileLock(), FsRtlPrivateCheckForExclusiveLockAccess(), FsRtlPrivateCheckForSharedLockAccess(), and FsRtlPrivateInsertExclusiveLock().
PRTL_SPLAY_LINKS FsRtlFindFirstOverlappingSharedNode (IN PRTL_SPLAY_LINKS Tree, IN PLARGE_INTEGER StartingByte, IN PLARGE_INTEGER EndingByte, IN OUT PRTL_SPLAY_LINKS * LastEdgeNode, IN OUT PBOOLEAN GreaterThan)
Definition at line 1522 of file filelock.c.
References CONTAINING_RECORD, _FILE_LOCK_INFO::EndingByte, _LOCKTREE_NODE::Extent, FALSE, _FILE_LOCK_INFO::Length, _LOCKTREE_NODE::Links, _SH_LOCK::LockInfo, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _LARGE_INTEGER::QuadPart, RtlLeftChild, RtlRightChild, _FILE_LOCK_INFO::StartingByte, and TRUE.
Referenced by FsRtlCheckNoSharedConflict(), FsRtlFastUnlockSingleShared(), FsRtlGetNextFileLock(), FsRtlPrivateCheckForExclusiveLockAccess(), and FsRtlPrivateInsertSharedLock().
INLINE VOID FsRtlFreeExclusiveLock (IN PEX_LOCK C)
Definition at line 460 of file filelock.c.
References ExFreeToNPagedLookasideList(), and FsRtlExclusiveLockLookasideList.
Referenced by FsRtlFastUnlockSingleExclusive(), FsRtlPrivateFastUnlockAll(), and FsRtlUninitializeFileLock().
VOID FsRtlFreeFileLock (__in PFILE_LOCK FileLock)
Definition at line 1167 of file filelock.c.
References ExFreeToPagedLookasideList(), FsRtlFileLockLookasideList, and FsRtlUninitializeFileLock().
INLINE VOID FsRtlFreeLockInfo (IN PLOCK_INFO C)
Definition at line 487 of file filelock.c.
References ExFreeToNPagedLookasideList(), and FsRtlLockInfoLookasideList.
Referenced by FsRtlUninitializeFileLock().
INLINE VOID FsRtlFreeLockTreeNode (IN PLOCKTREE_NODE C)
Definition at line 478 of file filelock.c.
References ExFreeToNPagedLookasideList(), and FsRtlLockTreeNodeLookasideList.
Referenced by FsRtlFastUnlockSingleShared(), FsRtlPrivateFastUnlockAll(), FsRtlPrivateInsertSharedLock(), and FsRtlUninitializeFileLock().
INLINE VOID FsRtlFreeSharedLock (IN PSH_LOCK C)
Definition at line 451 of file filelock.c.
References ExFreeToNPagedLookasideList(), and FsRtlSharedLockLookasideList.
Referenced by FsRtlFastUnlockSingleShared(), FsRtlPrivateFastUnlockAll(), and FsRtlUninitializeFileLock().
INLINE VOID FsRtlFreeWaitingLock (IN PWAITING_LOCK C)
Definition at line 469 of file filelock.c.
References ExFreeToNPagedLookasideList(), and FsRtlWaitingLockLookasideList.
Referenced by FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateFastUnlockAll(), and FsRtlUninitializeFileLock().
PFILE_LOCK_INFO FsRtlGetNextFileLock (__in PFILE_LOCK FileLock, __in BOOLEAN Restart)
Definition at line 1956 of file filelock.c.
References CONTAINING_RECORD, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, _LOCK_QUEUE::ExclusiveLockTree, FALSE, _FILE_LOCK_INFO::FileObject, FsRtlAcquireLockQueue, FsRtlFindFirstOverlappingExclusiveNode(), FsRtlFindFirstOverlappingSharedNode(), FsRtlReleaseLockQueue, GreaterThan, _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _SH_LOCK::LockInfo, _EX_LOCK::LockInfo, _LOCK_INFO::LockQueue, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlLeftChild, RtlRealSuccessor(), _LOCK_QUEUE::SharedLockTree, _FILE_LOCK_INFO::StartingByte, and TRUE.
VOID FsRtlInitializeFileLock (__in PFILE_LOCK FileLock, __in_opt PCOMPLETE_LOCK_IRP_ROUTINE CompleteLockIrpRoutine, __in_opt PUNLOCK_ROUTINE UnlockRoutine)
Definition at line 799 of file filelock.c.
References Dbg, DebugTrace, FALSE, and NULL.
Referenced by FsRtlAllocateFileLock().
VOID FsRtlInitializeFileLocks (VOID)
Definition at line 712 of file filelock.c.
References ExInitializeNPagedLookasideList(), ExInitializePagedLookasideList(), FsRtlExclusiveLockLookasideList, FsRtlFileLockCancelCollideLock, FsRtlFileLockLookasideList, FsRtlLockInfoLookasideList, FsRtlLockTreeNodeLookasideList, FsRtlSharedLockLookasideList, FsRtlWaitingLockLookasideList, KeInitializeGuardedMutex(), KeInitializeSpinLock(), _SINGLE_LIST_ENTRY::Next, NULL, TAG_EXCLUSIVE_LOCK, TAG_FILE_LOCK, TAG_LOCK_INFO, TAG_LOCKTREE_NODE, TAG_SHARED_LOCK, and TAG_WAITING_LOCK.
Referenced by FsRtlInitSystem().
VOID FsRtlPrivateCancelFileLockIrp (IN PDEVICE_OBJECT DeviceObject, IN PIRP Irp)
Definition at line 5768 of file filelock.c.
References ASSERT, CONTAINING_RECORD, _WAITING_LOCK::Context, Dbg, DebugTrace, FALSE, FsRtlAcquireCancelCollide, FsRtlAcquireLockQueueAtDpc, FsRtlCompleteLockIrp, FsRtlFreeWaitingLock(), FsRtlReleaseCancelCollide, FsRtlReleaseCancelCollideFromDpc, FsRtlReleaseLockQueue, IoReleaseCancelSpinLock(), _WAITING_LOCK::Irp, _LOCK_INFO::LockQueue, _SINGLE_LIST_ENTRY::Next, NULL, STATUS_CANCELLED, TRUE, UNREFERENCED_PARAMETER, _LOCK_QUEUE::WaitingLocks, and _LOCK_QUEUE::WaitingLocksTail.
Referenced by FsRtlPrivateLock().
BOOLEAN FsRtlPrivateCheckForExclusiveLockAccess (IN PLOCK_QUEUE LockInfo, IN PFILE_LOCK_INFO FileLockInfo)
Definition at line 4959 of file filelock.c.
References CONTAINING_RECORD, FALSE, FsRtlFindFirstOverlapInNode(), FsRtlFindFirstOverlappingExclusiveNode(), FsRtlFindFirstOverlappingSharedNode(), _LOCKTREE_NODE::HoleyNode, _FILE_LOCK_INFO::Length, _SH_LOCK::LockInfo, _EX_LOCK::LockInfo, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _LARGE_INTEGER::QuadPart, RtlSplay(), and TRUE.
Referenced by FsRtlPrivateCheckWaitingLocks(), and FsRtlPrivateLock().
BOOLEAN FsRtlPrivateCheckForSharedLockAccess (IN PLOCK_QUEUE LockInfo, IN PFILE_LOCK_INFO FileLockInfo)
Definition at line 5071 of file filelock.c.
References CONTAINING_RECORD, FALSE, _FILE_LOCK_INFO::FileObject, FsRtlFindFirstOverlappingExclusiveNode(), _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _EX_LOCK::LockInfo, NULL, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlRealSuccessor(), RtlSplay(), _FILE_LOCK_INFO::StartingByte, Status, and TRUE.
Referenced by FsRtlPrivateCheckWaitingLocks(), and FsRtlPrivateLock().
VOID FsRtlPrivateCheckWaitingLocks (IN PLOCK_INFO LockInfo, IN PLOCK_QUEUE LockQueue, IN KIRQL OldIrql)
Definition at line 4733 of file filelock.c.
References BooleanFlagOn, CONTAINING_RECORD, _WAITING_LOCK::Context, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, FALSE, _FILE_LOCK_INFO::FileObject, _IO_STACK_LOCATION::FileObject, _IO_STACK_LOCATION::Flags, FsRtlAcquireLockQueue, FsRtlCompleteLockIrp, FsRtlFreeWaitingLock(), FsRtlPrivateCheckForExclusiveLockAccess(), FsRtlPrivateCheckForSharedLockAccess(), FsRtlPrivateInsertLock(), FsRtlPrivateRemoveLock(), FsRtlReleaseLockQueue, IoAcquireCancelSpinLock(), IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_LOCK::Irp, _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _SINGLE_LIST_ENTRY::Next, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, SL_EXCLUSIVE_LOCK, _FILE_LOCK_INFO::StartingByte, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), and FsRtlPrivateFastUnlockAll().
NTSTATUS FsRtlPrivateFastUnlockAll (IN PFILE_LOCK FileLock, IN PFILE_OBJECT FileObject, IN PEPROCESS ProcessId, IN ULONG Key, IN BOOLEAN MatchKey, IN PVOID Context OPTIONAL)
Definition at line 5279 of file filelock.c.
References CONTAINING_RECORD, _WAITING_LOCK::Context, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _LOCK_QUEUE::ExclusiveLockTree, FALSE, _FILE_LOCK_INFO::FileObject, _IO_STACK_LOCATION::FileObject, FsRtlAcquireLockQueue, FsRtlCompleteLockIrp, FsRtlFreeExclusiveLock(), FsRtlFreeLockTreeNode(), FsRtlFreeSharedLock(), FsRtlFreeWaitingLock(), FsRtlPrivateCheckWaitingLocks(), FsRtlPrivateResetLowestLockOffset(), FsRtlReleaseLockQueue, FsRtlSplitLocks(), IoAcquireCancelSpinLock(), IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_LOCK::Irp, _FILE_LOCK_INFO::Key, _EX_LOCK::Links, _SH_LOCK::LockInfo, _EX_LOCK::LockInfo, _LOCK_INFO::LockQueue, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _IO_STACK_LOCATION::Parameters, PIRP, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, RtlDelete(), RtlLeftChild, RtlRealSuccessor(), _LOCK_QUEUE::SharedLockTree, STATUS_RANGE_NOT_LOCKED, STATUS_SUCCESS, _LOCKTREE_NODE::Tail, TRUE, _LOCK_INFO::UnlockRoutine, _LOCK_QUEUE::WaitingLocks, and _LOCK_QUEUE::WaitingLocksTail.
Referenced by FsRtlFastUnlockAll(), and FsRtlFastUnlockAllByKey().
BOOLEAN FsRtlPrivateInitializeFileLock (IN PFILE_LOCK FileLock, IN BOOLEAN ViaFastCall)
Definition at line 858 of file filelock.c.
References _LOCK_INFO::CompleteLockIrpRoutine, _LOCK_QUEUE::ExclusiveLockTree, ExRaiseStatus(), FALSE, FsRtlAllocateLockInfo(), KeAcquireGuardedMutex(), KeInitializeSpinLock(), KeReleaseGuardedMutex(), _LOCK_INFO::LockQueue, _LOCK_INFO::LowestLockOffset, _SINGLE_LIST_ENTRY::Next, NOTHING, NULL, _LOCK_QUEUE::QueueSpinLock, _LOCK_QUEUE::SharedLockTree, STATUS_INSUFFICIENT_RESOURCES, TRUE, try_return, _LOCK_INFO::UnlockRoutine, _LOCK_QUEUE::WaitingLocks, and _LOCK_QUEUE::WaitingLocksTail.
Referenced by FsRtlPrivateLock().
VOID FsRtlPrivateInsertExclusiveLock (IN PLOCK_QUEUE LockQueue, IN PEX_LOCK NewLock)
Definition at line 4616 of file filelock.c.
References ASSERT, FsRtlFindFirstOverlappingExclusiveNode(), GreaterThan, NULL, RtlInitializeSplayLinks, RtlInsertAsLeftChild, RtlInsertAsRightChild, RtlLeftChild, RtlRealSuccessor(), and RtlRightChild.
Referenced by FsRtlPrivateInsertLock().
BOOLEAN FsRtlPrivateInsertLock (IN PLOCK_INFO LockInfo, IN PFILE_OBJECT FileObject, IN PFILE_LOCK_INFO FileLockInfo)
Definition at line 4264 of file filelock.c.
References ASSERT, FALSE, FsRtlAllocateExclusiveLock(), FsRtlAllocateSharedLock(), FsRtlPrivateInsertExclusiveLock(), FsRtlPrivateInsertSharedLock(), _SH_LOCK::LockInfo, _EX_LOCK::LockInfo, NULL, and TRUE.
Referenced by FsRtlPrivateCheckWaitingLocks(), and FsRtlPrivateLock().
BOOLEAN FsRtlPrivateInsertSharedLock (IN PLOCK_QUEUE LockQueue, IN PSH_LOCK NewLock)
Definition at line 4354 of file filelock.c.
References ASSERT, CONTAINING_RECORD, Dbg, DebugTrace, _LOCKTREE_NODE::Extent, FALSE, FsRtlAllocateLockTreeNode(), FsRtlFindFirstOverlappingSharedNode(), FsRtlFreeLockTreeNode(), FsRtlSplitLocks(), GreaterThan, _LOCKTREE_NODE::HoleyNode, _FILE_LOCK_INFO::Length, _LOCKTREE_NODE::Links, _SH_LOCK::LockInfo, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _LARGE_INTEGER::QuadPart, RtlDeleteNoSplay(), RtlInitializeSplayLinks, RtlInsertAsLeftChild, RtlInsertAsRightChild, RtlLeftChild, RtlRealSuccessor(), RtlRightChild, RtlSplay(), _FILE_LOCK_INFO::StartingByte, _LOCKTREE_NODE::Tail, and TRUE.
Referenced by FsRtlPrivateInsertLock().
BOOLEAN FsRtlPrivateLock (__in PFILE_LOCK FileLock, __in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PLARGE_INTEGER Length, __in PEPROCESS ProcessId, __in ULONG Key, __in BOOLEAN FailImmediately, __in BOOLEAN ExclusiveLock, __out PIO_STATUS_BLOCK Iosb, __in_opt PIRP Irp, __in_opt PVOID Context, __in BOOLEAN AlreadySynchronized)
Definition at line 3875 of file filelock.c.
References ARGUMENT_PRESENT, _WAITING_LOCK::CompleteLockIrpRoutine, _LOCK_INFO::CompleteLockIrpRoutine, _WAITING_LOCK::Context, Dbg, DebugTrace, _FILE_LOCK_INFO::EndingByte, _FILE_LOCK_INFO::ExclusiveLock, ExRaiseStatus(), FALSE, _FILE_LOCK_INFO::FileObject, FileOffset, FsRtlAcquireLockQueue, FsRtlAllocateWaitingLock(), FsRtlCompleteLockIrp, FsRtlPrivateCancelFileLockIrp(), FsRtlPrivateCheckForExclusiveLockAccess(), FsRtlPrivateCheckForSharedLockAccess(), FsRtlPrivateInitializeFileLock(), FsRtlPrivateInsertLock(), FsRtlPrivateRemoveLock(), FsRtlReleaseLockQueue, IoMarkIrpPending, IoSetCancelRoutine, _WAITING_LOCK::Irp, _FILE_LOCK_INFO::Key, _FILE_LOCK_INFO::Length, _WAITING_LOCK::Link, _LOCK_INFO::LockQueue, _SINGLE_LIST_ENTRY::Next, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, _FILE_LOCK_INFO::ProcessId, _LARGE_INTEGER::QuadPart, _FILE_LOCK_INFO::StartingByte, STATUS_INSUFFICIENT_RESOURCES, STATUS_LOCK_NOT_GRANTED, STATUS_PENDING, STATUS_SUCCESS, TRUE, try_return, UNREFERENCED_PARAMETER, _LOCK_QUEUE::WaitingLocks, and _LOCK_QUEUE::WaitingLocksTail.
Referenced by FsRtlProcessFileLock().
VOID FsRtlPrivateRemoveLock (IN PLOCK_INFO LockInfo, IN PFILE_LOCK_INFO FileLockInfo, IN BOOLEAN CheckForWaiters)
Definition at line 3169 of file filelock.c.
References ASSERT, FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), NULL, Status, STATUS_SUCCESS, and TRUE.
Referenced by FsRtlPrivateCheckWaitingLocks(), and FsRtlPrivateLock().
VOID FsRtlPrivateResetLowestLockOffset (PLOCK_INFO LockInfo)
Definition at line 5175 of file filelock.c.
References CONTAINING_RECORD, _LOCK_QUEUE::ExclusiveLockTree, _LARGE_INTEGER::HighPart, _SH_LOCK::LockInfo, _EX_LOCK::LockInfo, _LOCK_INFO::LockQueue, _LOCKTREE_NODE::Locks, _LOCK_INFO::LowestLockOffset, _LARGE_INTEGER::LowPart, _SINGLE_LIST_ENTRY::Next, NULL, _LARGE_INTEGER::QuadPart, RtlLeftChild, _LOCK_QUEUE::SharedLockTree, and _FILE_LOCK_INFO::StartingByte.
Referenced by FsRtlFastUnlockSingleExclusive(), FsRtlFastUnlockSingleShared(), and FsRtlPrivateFastUnlockAll().
NTSTATUS FsRtlProcessFileLock (__in PFILE_LOCK FileLock, __in PIRP Irp, __in_opt PVOID Context)
Definition at line 1178 of file filelock.c.
References ASSERT, BooleanFlagOn, Dbg, DebugTrace, FALSE, _IO_STACK_LOCATION::FileObject, _IO_STACK_LOCATION::Flags, FsRtlCompleteLockIrp, FsRtlCompleteRequest, FsRtlFastUnlockAll(), FsRtlFastUnlockAllByKey(), FsRtlFastUnlockSingle(), FsRtlPrivateLock(), _IO_STATUS_BLOCK::Information, IoGetCurrentIrpStackLocation, IoGetRequestorProcess(), IRP_MJ_LOCK_CONTROL, IRP_MN_LOCK, IRP_MN_UNLOCK_ALL, IRP_MN_UNLOCK_ALL_BY_KEY, IRP_MN_UNLOCK_SINGLE, _IO_STACK_LOCATION::MajorFunction, _IO_STACK_LOCATION::MinorFunction, NULL, _IO_STACK_LOCATION::Parameters, SL_EXCLUSIVE_LOCK, SL_FAIL_IMMEDIATELY, Status, _IO_STATUS_BLOCK::Status, STATUS_INVALID_DEVICE_REQUEST, and VOID.
VOID FsRtlSplitLocks (IN PLOCKTREE_NODE ParentNode, IN PSINGLE_LIST_ENTRY * pStartLink, IN PLARGE_INTEGER LastShadowedByte, IN PLARGE_INTEGER GlueOffset)
Definition at line 2870 of file filelock.c.
References ASSERT, CONTAINING_RECORD, _FILE_LOCK_INFO::EndingByte, _LOCKTREE_NODE::Extent, FALSE, FsRtlAllocateLockTreeNode(), _LOCKTREE_NODE::HoleyNode, _FILE_LOCK_INFO::Length, _LOCKTREE_NODE::Links, _SH_LOCK::LockInfo, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, _LARGE_INTEGER::QuadPart, RtlInitializeSplayLinks, RtlInsertAsLeftChild, RtlInsertAsRightChild, RtlLeftChild, RtlRealSuccessor(), RtlRightChild, _FILE_LOCK_INFO::StartingByte, _LOCKTREE_NODE::Tail, and TRUE.
Referenced by FsRtlFastUnlockSingleShared(), FsRtlPrivateFastUnlockAll(), and FsRtlPrivateInsertSharedLock().
VOID FsRtlUninitializeFileLock (__in PFILE_LOCK FileLock)
Definition at line 965 of file filelock.c.
References CONTAINING_RECORD, _WAITING_LOCK::Context, Dbg, DebugTrace, _LOCK_QUEUE::ExclusiveLockTree, FsRtlAcquireCancelCollide, FsRtlAcquireLockQueueAtDpc, FsRtlCompleteLockIrp, FsRtlFreeExclusiveLock(), FsRtlFreeLockInfo(), FsRtlFreeLockTreeNode(), FsRtlFreeSharedLock(), FsRtlFreeWaitingLock(), FsRtlReleaseCancelCollide, FsRtlReleaseLockQueueFromDpc, IoAcquireCancelSpinLock(), IoReleaseCancelSpinLock(), IoSetCancelRoutine, _WAITING_LOCK::Irp, _WAITING_LOCK::Link, _LOCKTREE_NODE::Links, _EX_LOCK::Links, _LOCK_INFO::LockQueue, _LOCKTREE_NODE::Locks, _SINGLE_LIST_ENTRY::Next, NULL, PIRP, PopEntryList, PushEntryList, RtlDeleteNoSplay(), _LOCK_QUEUE::SharedLockTree, STATUS_RANGE_NOT_LOCKED, and _LOCK_QUEUE::WaitingLocks.
Referenced by FsRtlFreeFileLock().
Variable Documentation
KGUARDED_MUTEX FsRtlCreateLockInfo
Definition at line 115 of file filelock.c.
NPAGED_LOOKASIDE_LIST FsRtlExclusiveLockLookasideList
Definition at line 138 of file filelock.c.
Referenced by FsRtlAllocateExclusiveLock(), FsRtlFreeExclusiveLock(), and FsRtlInitializeFileLocks().
SINGLE_LIST_ENTRY FsRtlFileLockCancelCollideList
Definition at line 125 of file filelock.c.
KSPIN_LOCK FsRtlFileLockCancelCollideLock
Definition at line 123 of file filelock.c.
Referenced by FsRtlInitializeFileLocks().
PAGED_LOOKASIDE_LIST FsRtlFileLockLookasideList
Definition at line 143 of file filelock.c.
Referenced by FsRtlAllocateFileLock(), FsRtlFreeFileLock(), and FsRtlInitializeFileLocks().
NPAGED_LOOKASIDE_LIST FsRtlLockInfoLookasideList
Definition at line 141 of file filelock.c.
Referenced by FsRtlAllocateLockInfo(), FsRtlFreeLockInfo(), and FsRtlInitializeFileLocks().
NPAGED_LOOKASIDE_LIST FsRtlLockTreeNodeLookasideList
Definition at line 140 of file filelock.c.
Referenced by FsRtlAllocateLockTreeNode(), FsRtlFreeLockTreeNode(), and FsRtlInitializeFileLocks().
NPAGED_LOOKASIDE_LIST FsRtlSharedLockLookasideList
Definition at line 137 of file filelock.c.
Referenced by FsRtlAllocateSharedLock(), FsRtlFreeSharedLock(), and FsRtlInitializeFileLocks().
NPAGED_LOOKASIDE_LIST FsRtlWaitingLockLookasideList
Definition at line 139 of file filelock.c.
Referenced by FsRtlAllocateWaitingLock(), FsRtlFreeWaitingLock(), and FsRtlInitializeFileLocks().