Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/regutil.c File Reference
regutil.c File Reference
#include "ntrtlp.h"
#include <ctype.h>
Macros
#define MAX_NONNULL_USTRING (MAX_USTRING - sizeof(UNICODE_NULL))
#define QuadAlignPtr(P)
#define SIZE_OF_TOKEN_INFORMATION
Functions
NTSTATUS RtlCheckRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
NTSTATUS RtlCreateRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
NTSTATUS RtlDeleteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName)
NTSTATUS RtlExpandEnvironmentStrings_U (IN PVOID Environment OPTIONAL, IN PCUNICODE_STRING Source, OUT PUNICODE_STRING Destination, OUT PULONG ReturnedLength OPTIONAL)
NTSTATUS RtlFormatCurrentUserKeyPath (OUT PUNICODE_STRING CurrentUserKeyPath)
ULONG RtlGetNtGlobalFlags (VOID)
NTSTATUS RtlOpenCurrentUser (IN ULONG DesiredAccess, OUT PHANDLE CurrentUserKey)
PVOID RtlpAllocDeallocQueryBuffer (IN OUT SIZE_T *PAllocLength OPTIONAL, IN PVOID OldKeyValueInformation OPTIONAL, IN SIZE_T OldAllocLength OPTIONAL, OUT NTSTATUS *pStatus OPTIONAL)
NTSTATUS RtlpCallQueryRegistryRoutine (IN PRTL_QUERY_REGISTRY_TABLE QueryTable, IN PKEY_VALUE_FULL_INFORMATION KeyValueInformation, IN OUT PULONG PKeyValueInfoLength, IN PVOID Context, IN PVOID Environment OPTIONAL)
NTSTATUS RtlpGetRegistryHandle (IN ULONG RelativeTo, IN PCWSTR KeyName, IN BOOLEAN WriteAccess, OUT PHANDLE Key)
NTSTATUS RtlpGetTimeZoneInfoHandle (IN BOOLEAN WriteAccess, OUT PHANDLE Key)
NTSTATUS RtlpInitCurrentUserString (OUT PUNICODE_STRING UserString)
NTSTATUS RtlpQueryRegistryDirect (IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN OUT PVOID Destination)
NTSTATUS RtlQueryRegistryValues (IN ULONG RelativeTo, IN PCWSTR Path, IN PRTL_QUERY_REGISTRY_TABLE QueryTable, IN PVOID Context, IN PVOID Environment OPTIONAL)
NTSTATUS RtlQueryTimeZoneInformation (OUT PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
NTSTATUS RtlSetActiveTimeBias (IN LONG ActiveBias)
NTSTATUS RtlSetTimeZoneInformation (IN PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
NTSTATUS RtlWriteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength)
Variables
const PWSTR RtlpRegistryPaths [RTL_REGISTRY_MAXIMUM]
const SIZE_T RtlpRegistryQueryInitialBuffersize = 0x80 + sizeof(PVOID)
const WCHAR szBias []
const WCHAR szDaylightBias []
const WCHAR szDaylightName []
const WCHAR szDaylightStart []
const WCHAR szStandardBias []
const WCHAR szStandardName []
const WCHAR szStandardStart []
Macro Definition Documentation
#define MAX_NONNULL_USTRING (MAX_USTRING - sizeof(UNICODE_NULL))
Definition at line 183 of file regutil.c.
Referenced by RtlpCallQueryRegistryRoutine().
#define QuadAlignPtr (P)
Value:
(\
    (PVOID)((((ULONG_PTR)(P)) + 7) & (-8)) \
)
Definition at line 265 of file regutil.c.
Referenced by RtlpCallQueryRegistryRoutine().
#define SIZE_OF_TOKEN_INFORMATION
Value:
sizeof(TOKEN_USER)                            \
    + sizeof( SID )                                 \
    + sizeof( ULONG ) * SID_MAX_SUB_AUTHORITIES
Definition at line 1407 of file regutil.c.
Referenced by RtlFormatCurrentUserKeyPath().
Function Documentation
NTSTATUS RtlCheckRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
Definition at line 1218 of file regutil.c.
References FALSE, NT_SUCCESS, RTL_PAGED_CODE, RtlpGetRegistryHandle(), Status, STATUS_SUCCESS, and ZwClose().
NTSTATUS RtlCreateRegistryKey (__in ULONG RelativeTo, __in PWSTR Path)
Definition at line 1239 of file regutil.c.
References NT_SUCCESS, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlpGetRegistryHandle(), Status, STATUS_SUCCESS, TRUE, and ZwClose().
NTSTATUS RtlDeleteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName)
Definition at line 1262 of file regutil.c.
References KeyValueName, NT_SUCCESS, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlInitUnicodeString(), RtlpGetRegistryHandle(), Status, TRUE, ZwClose(), and ZwDeleteValueKey().
NTSTATUS RtlExpandEnvironmentStrings_U (IN PVOID Environment OPTIONAL, IN PCUNICODE_STRING Source, OUT PUNICODE_STRING Destination, OUT PULONG ReturnedLength OPTIONAL)
Definition at line 1290 of file regutil.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, RTL_PAGED_CODE, RtlQueryEnvironmentVariable_U(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by RtlpCallQueryRegistryRoutine().
NTSTATUS RtlFormatCurrentUserKeyPath (OUT PUNICODE_STRING CurrentUserKeyPath)
Definition at line 1414 of file regutil.c.
References _UNICODE_STRING::Buffer, FALSE, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NtCurrentProcess, NtCurrentThread, NULL, OBJ_KERNEL_HANDLE, PS_IS_THREAD_IMPERSONATING, PsGetCurrentThread(), RtlAllocateStringRoutine, RtlAppendUnicodeToString(), RtlConvertSidToUnicodeString(), RtlFreeUnicodeString(), RtlLengthSidAsUnicodeString(), SIZE_OF_TOKEN_INFORMATION, Status, STATUS_NO_MEMORY, STATUS_NO_TOKEN, TOKEN_READ, TokenUser, TRUE, UNICODE_NULL, ZwClose(), ZwOpenProcessTokenEx(), ZwOpenThreadTokenEx(), and ZwQueryInformationToken().
Referenced by RtlOpenCurrentUser(), and RtlpGetRegistryHandle().
ULONG RtlGetNtGlobalFlags (VOID)
Definition at line 1397 of file regutil.c.
References NtGlobalFlag.
Referenced by RtlCreateUserProcess().
NTSTATUS RtlOpenCurrentUser (IN ULONG DesiredAccess, OUT PHANDLE CurrentUserKey)
Definition at line 1532 of file regutil.c.
References InitializeObjectAttributes, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, RTL_PAGED_CODE, RTL_REGISTRY_USER, RtlFormatCurrentUserKeyPath(), RtlFreeUnicodeString(), RtlInitUnicodeString(), RtlpRegistryPaths, Status, and ZwOpenKey().
Referenced by ExpGetCurrentUserUILanguage(), ExpSetCurrentUserUILanguage(), and NtSetDefaultLocale().
PVOID RtlpAllocDeallocQueryBuffer (IN OUT SIZE_T *PAllocLength OPTIONAL, IN PVOID OldKeyValueInformation OPTIONAL, IN SIZE_T OldAllocLength OPTIONAL, OUT NTSTATUS *pStatus OPTIONAL)
Definition at line 671 of file regutil.c.
References ARGUMENT_PRESENT, ExAllocatePoolWithTag, ExFreePool(), NULL, PagedPool, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by RtlQueryRegistryValues().
NTSTATUS RtlpCallQueryRegistryRoutine (IN PRTL_QUERY_REGISTRY_TABLE QueryTable, IN PKEY_VALUE_FULL_INFORMATION KeyValueInformation, IN OUT PULONG PKeyValueInfoLength, IN PVOID Context, IN PVOID Environment OPTIONAL)
Definition at line 270 of file regutil.c.
References _UNICODE_STRING::Buffer, DbgPrint(), FALSE, FIELD_OFFSET, _UNICODE_STRING::Length, MAX_NONNULL_USTRING, MAX_USTRING, _UNICODE_STRING::MaximumLength, NT_SUCCESS, QuadAlignPtr, REG_EXPAND_SZ, REG_MULTI_SZ, REG_NONE, REG_SZ, RTL_QUERY_REGISTRY_DIRECT, RTL_QUERY_REGISTRY_NOEXPAND, RTL_QUERY_REGISTRY_REQUIRED, RtlCopyMemory, RtlExpandEnvironmentStrings_U(), RtlpQueryRegistryDirect(), Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, and UNICODE_NULL.
Referenced by RtlQueryRegistryValues().
NTSTATUS RtlpGetRegistryHandle (IN ULONG RelativeTo, IN PCWSTR KeyName, IN BOOLEAN WriteAccess, OUT PHANDLE Key)
Definition at line 91 of file regutil.c.
References _UNICODE_STRING::Buffer, FALSE, GENERIC_READ, GENERIC_WRITE, InitializeObjectAttributes, _UNICODE_STRING::Length, MAXIMUM_ALLOWED, MAXIMUM_FILENAME_LENGTH, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, RTL_REGISTRY_ABSOLUTE, RTL_REGISTRY_HANDLE, RTL_REGISTRY_MAXIMUM, RTL_REGISTRY_OPTIONAL, RTL_REGISTRY_USER, RtlAppendUnicodeStringToString(), RtlAppendUnicodeToString(), RtlFormatCurrentUserKeyPath(), RtlFreeUnicodeString(), RtlpRegistryPaths, Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, ZwCreateKey(), and ZwOpenKey().
Referenced by RtlCheckRegistryKey(), RtlCreateRegistryKey(), RtlDeleteRegistryValue(), RtlpGetTimeZoneInfoHandle(), RtlQueryRegistryValues(), and RtlWriteRegistryValue().
NTSTATUS RtlpGetTimeZoneInfoHandle (IN BOOLEAN WriteAccess, OUT PHANDLE Key)
Definition at line 1606 of file regutil.c.
References RTL_REGISTRY_CONTROL, and RtlpGetRegistryHandle().
Referenced by RtlQueryTimeZoneInformation(), RtlSetActiveTimeBias(), and RtlSetTimeZoneInformation().
NTSTATUS RtlpInitCurrentUserString (OUT PUNICODE_STRING UserString)
NTSTATUS RtlpQueryRegistryDirect (IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength, IN OUT PVOID Destination)
Definition at line 191 of file regutil.c.
References _UNICODE_STRING::Buffer, DbgPrint(), _UNICODE_STRING::Length, MAX_USTRING, _UNICODE_STRING::MaximumLength, NULL, REG_EXPAND_SZ, REG_MULTI_SZ, REG_SZ, RtlAllocateStringRoutine, RtlCopyMemory, STATUS_BUFFER_TOO_SMALL, STATUS_NO_MEMORY, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by RtlpCallQueryRegistryRoutine().
NTSTATUS RtlQueryRegistryValues (IN ULONG RelativeTo, IN PCWSTR Path, IN PRTL_QUERY_REGISTRY_TABLE QueryTable, IN PVOID Context, IN PVOID Environment OPTIONAL)
Definition at line 706 of file regutil.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_FULL_INFORMATION::DataLength, _KEY_VALUE_FULL_INFORMATION::DataOffset, DbgPrint(), FALSE, InitializeObjectAttributes, KeyValueFullInformation, KeyValueName, _UNICODE_STRING::Length, MAXIMUM_ALLOWED, _UNICODE_STRING::MaximumLength, _KEY_VALUE_FULL_INFORMATION::Name, _KEY_VALUE_FULL_INFORMATION::NameLength, NT_SUCCESS, NtClose(), NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_MULTI_SZ, REG_NONE, RTL_PAGED_CODE, RTL_QUERY_REGISTRY_DELETE, RTL_QUERY_REGISTRY_DIRECT, RTL_QUERY_REGISTRY_NOVALUE, RTL_QUERY_REGISTRY_REQUIRED, RTL_QUERY_REGISTRY_SUBKEY, RTL_QUERY_REGISTRY_TOPKEY, RTL_REGISTRY_HANDLE, RtlInitUnicodeString(), RtlpAllocDeallocQueryBuffer(), RtlpCallQueryRegistryRoutine(), RtlpGetRegistryHandle(), RtlpRegistryQueryInitialBuffersize, Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, STATUS_NO_MORE_ENTRIES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, TRUE, _KEY_VALUE_FULL_INFORMATION::Type, UNICODE_NULL, ZwClose(), ZwDeleteValueKey(), ZwEnumerateValueKey(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by CmIsLastKnownGoodBoot(), RtlQueryTimeZoneInformation(), RtlSetActiveTimeBias(), WmipGetGuidSecurityDescriptor(), WmipQueryWmiDataBlock(), and WmipStartGlobalLogger().
NTSTATUS RtlQueryTimeZoneInformation (OUT PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
Definition at line 1625 of file regutil.c.
References _UNICODE_STRING::Buffer, _RTL_QUERY_REGISTRY_TABLE::EntryContext, FALSE, _RTL_QUERY_REGISTRY_TABLE::Flags, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, RTL_PAGED_CODE, RTL_QUERY_REGISTRY_DIRECT, RTL_REGISTRY_HANDLE, RtlpGetTimeZoneInfoHandle(), RtlQueryRegistryValues(), RtlZeroMemory, Status, szBias, szDaylightBias, szDaylightName, szDaylightStart, szStandardBias, szStandardName, szStandardStart, and ZwClose().
Referenced by WmipAddLogHeader().
NTSTATUS RtlSetActiveTimeBias (IN LONG ActiveBias)
Definition at line 1780 of file regutil.c.
References _RTL_QUERY_REGISTRY_TABLE::EntryContext, _RTL_QUERY_REGISTRY_TABLE::Flags, _RTL_QUERY_REGISTRY_TABLE::Name, NT_SUCCESS, NULL, REG_DWORD, RTL_PAGED_CODE, RTL_QUERY_REGISTRY_DIRECT, RTL_QUERY_REGISTRY_REQUIRED, RTL_REGISTRY_HANDLE, RtlpGetTimeZoneInfoHandle(), RtlQueryRegistryValues(), RtlWriteRegistryValue(), RtlZeroMemory, Status, TRUE, and ZwClose().
NTSTATUS RtlSetTimeZoneInformation (IN PRTL_TIME_ZONE_INFORMATION TimeZoneInformation)
Definition at line 1693 of file regutil.c.
References NT_SUCCESS, REG_BINARY, REG_DWORD, REG_SZ, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlpGetTimeZoneInfoHandle(), RtlWriteRegistryValue(), Status, szBias, szDaylightBias, szDaylightName, szDaylightStart, szStandardBias, szStandardName, szStandardStart, TRUE, wcslen(), and ZwClose().
NTSTATUS RtlWriteRegistryValue (IN ULONG RelativeTo, IN PCWSTR Path, IN PCWSTR ValueName, IN ULONG ValueType, IN PVOID ValueData, IN ULONG ValueLength)
Definition at line 1181 of file regutil.c.
References KeyValueName, NT_SUCCESS, RTL_PAGED_CODE, RTL_REGISTRY_HANDLE, RtlInitUnicodeString(), RtlpGetRegistryHandle(), Status, TRUE, ZwClose(), and ZwSetValueKey().
Referenced by RtlSetActiveTimeBias(), RtlSetTimeZoneInformation(), WmipSaveGuidSecurityDescriptor(), and WmipStartGlobalLogger().
Variable Documentation
const PWSTR RtlpRegistryPaths[RTL_REGISTRY_MAXIMUM]
Definition at line 82 of file rtldata.c.
Referenced by RtlOpenCurrentUser(), and RtlpGetRegistryHandle().
const SIZE_T RtlpRegistryQueryInitialBuffersize = 0x80 + sizeof(PVOID)
Definition at line 665 of file regutil.c.
Referenced by RtlQueryRegistryValues().
const WCHAR szBias[]
Definition at line 91 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().
const WCHAR szDaylightBias[]
Definition at line 96 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().
const WCHAR szDaylightName[]
Definition at line 95 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().
const WCHAR szDaylightStart[]
Definition at line 97 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().
const WCHAR szStandardBias[]
Definition at line 93 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().
const WCHAR szStandardName[]
Definition at line 92 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().
const WCHAR szStandardStart[]
Definition at line 94 of file rtldata.c.
Referenced by RtlQueryTimeZoneInformation(), and RtlSetTimeZoneInformation().