Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/mca.c File Reference
mca.c File Reference
#include "wmikmp.h"
#include <mce.h>
#include "hal.h"
#include "ntiologc.h"
#include "mcaevent.h"
Data Structures
struct MCEQUERYINFO
Macros
#define DEFAULT_MAX_CMC_SIZE 0x1000
#define DEFAULT_MAX_CPE_SIZE 0x1000
#define DEFAULT_MAX_MCA_SIZE 0x1000
#define HalpGetFwMceLogProcessorNumber(_Log) ((_Log)->ProcessorNumber)
#define MAX_ERROR_EVENT_SIZE
#define MCA_EVENT_INSTANCE_NAME L"McaEvent"
#define MCA_UNDEFINED_CPU 0xffffffff
#define MCE_STATE_ERROR -1
#define MCE_STATE_REGISTERED 1
#define MCE_STATE_RUNNING 2
#define MCE_STATE_UNINIT 0
#define WAITING_FOR_WBEM 2
#define WBEM_IS_RUNNING 1
#define WBEM_STATUS_UNKNOWN 0
#define WmipIsWbemRunning()
Typedefs
typedef MCA_EXCEPTION ERROR_LOGRECORD
typedef MCA_EXCEPTION ERROR_RECORD_HEADER
typedef MCA_EXCEPTION * PERROR_LOGRECORD
typedef MCA_EXCEPTION * PERROR_RECORD_HEADER
typedef struct MCEQUERYINFO * PMCEQUERYINFO
Functions
NTSTATUS WmipBuildMcaCmcEvent (OUT PWNODE_SINGLE_INSTANCE Wnode, IN LPGUID EventGuid, IN PERROR_LOGRECORD McaCmcEvent, IN ULONG McaCmcSize)
BOOLEAN WmipCheckIsWbemRunning (void)
NTSTATUS WmipFireOffWmiEvent (LPGUID Guid, ULONG DataSize, PVOID DataPtr)
void WmipGenerateMCAEventlog (PUCHAR ErrorLog, ULONG ErrorLogSize, BOOLEAN IsFatal)
NTSTATUS WmipGetLogFromHal (HAL_QUERY_INFORMATION_CLASS InfoClass, PVOID Token, PWNODE_SINGLE_INSTANCE *Wnode, PERROR_LOGRECORD *Mca, PULONG McaSize, ULONG MaxSize, LPGUID Guid)
NTSTATUS WmipGetLogFromHal (IN HAL_QUERY_INFORMATION_CLASS InfoClass, IN PVOID Token, IN OUT PWNODE_SINGLE_INSTANCE *Wnode, OUT PERROR_LOGRECORD *Mca, OUT PULONG McaSize, IN ULONG MaxSize, IN LPGUID Guid)
NTSTATUS WmipGetRawMCAInfo (OUT PUCHAR Buffer, IN OUT PULONG BufferSize)
void WmipInsertQueueMCEDpc (PMCEQUERYINFO QueryInfo)
void WmipIsWbemRunningDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
void WmipIsWbemRunningWorker (PVOID Context)
BOOLEAN WmipMceDelivery (IN PVOID Reserved, IN KERNEL_MCE_DELIVERY_OPERATION Operation, IN PVOID Argument2)
void WmipMceDispatchRoutine (PMCEQUERYINFO QueryInfo)
void WmipMceDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
BOOLEAN WmipMceEventDelivery (IN PVOID Reserved, IN KERNEL_MCE_DELIVERY_OPERATION Operation, IN PVOID Argument2)
void WmipMceWorkerRoutine (IN PVOID Context)
void WmipPollingDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
void WmipProcessPrevMcaLogs (void)
NTSTATUS WmipQueryLogAndFireEvent (PMCEQUERYINFO QueryInfo)
NTSTATUS WmipRegisterMcaHandler (ULONG Phase)
NTSTATUS WmipSetupWaitForWbem (void)
NTSTATUS WmipWriteMCAEventLogEvent (PUCHAR Event)
NTSTATUS WmipWriteToEventlog (NTSTATUS ErrorCode, NTSTATUS FinalStatus)
Variables
MCEQUERYINFO WmipCmcQueryInfo
ULONG WmipCoalesceCorrectedErrorInterval = 5000
ULONG WmipCorrectedEventlogCounter = 20
ULONG WmipCorrectedMCECount
LIST_ENTRY WmipCorrectedMCEHead = {&WmipCorrectedMCEHead, &WmipCorrectedMCEHead}
MCEQUERYINFO WmipCpeQueryInfo
ULONG WmipDisableMCAPopups
KDPC WmipIsWbemRunningDpc
UCHAR WmipIsWbemRunningFlag
KTIMER WmipIsWbemRunningTimer
WORK_QUEUE_ITEM WmipIsWbemRunningWorkItem
ULONG WmipMaxCorrectedMCEOutstanding = 5
MCEQUERYINFO WmipMcaQueryInfo
ULONG WmipMCEState
GUID WmipMSMCAEvent_InvalidErrorGuid = MSMCAEvent_InvalidErrorGuid
PMSMCAInfo_RawMCAData WmipRawMCA
ULONG WmipRawMCASize
ULONG WmipSingleBitEccErrorThreshold = 6
LIST_ENTRY WmipWaitingMCAEvents = {&WmipWaitingMCAEvents, &WmipWaitingMCAEvents}
ULONG WmipWbemMinuteWait = 1
Macro Definition Documentation
#define DEFAULT_MAX_CMC_SIZE 0x1000
Definition at line 162 of file mca.c.
#define DEFAULT_MAX_CPE_SIZE 0x1000
Definition at line 163 of file mca.c.
#define DEFAULT_MAX_MCA_SIZE 0x1000
Definition at line 161 of file mca.c.
#define HalpGetFwMceLogProcessorNumber (_Log) ((_Log)->ProcessorNumber)
Definition at line 31 of file mca.c.
#define MAX_ERROR_EVENT_SIZE
Value:
(((sizeof(WNODE_SINGLE_INSTANCE) + \
       (sizeof(USHORT) + sizeof(MCA_EVENT_INSTANCE_NAME)) + 7) & ~7) + \
     sizeof(MSMCAEvent_MemoryError))
Definition at line 1574 of file mca.c.
Referenced by WmipGenerateMCAEventlog().
#define MCA_EVENT_INSTANCE_NAME L"McaEvent"
Definition at line 26 of file mca.c.
Referenced by WmipFireOffWmiEvent(), and WmipGenerateMCAEventlog().
#define MCA_UNDEFINED_CPU 0xffffffff
Definition at line 27 of file mca.c.
Referenced by WmipGenerateMCAEventlog().
#define MCE_STATE_ERROR -1
Definition at line 250 of file mca.c.
Referenced by WmipRegisterMcaHandler().
#define MCE_STATE_REGISTERED 1
Definition at line 248 of file mca.c.
Referenced by WmipRegisterMcaHandler().
#define MCE_STATE_RUNNING 2
Definition at line 249 of file mca.c.
Referenced by WmipMceDelivery(), WmipMceEventDelivery(), and WmipRegisterMcaHandler().
#define MCE_STATE_UNINIT 0
Definition at line 247 of file mca.c.
#define WAITING_FOR_WBEM 2
Definition at line 229 of file mca.c.
Referenced by WmipWriteMCAEventLogEvent().
#define WBEM_IS_RUNNING 1
Definition at line 228 of file mca.c.
Referenced by WmipCheckIsWbemRunning().
#define WBEM_STATUS_UNKNOWN 0
Definition at line 227 of file mca.c.
Referenced by WmipWriteMCAEventLogEvent().
#define WmipIsWbemRunning ()
Value:
((WmipIsWbemRunningFlag == WBEM_IS_RUNNING) ? \
                                                       TRUE : \
                                                       FALSE)
Definition at line 300 of file mca.c.
Referenced by WmipGenerateMCAEventlog(), and WmipWriteMCAEventLogEvent().
Typedef Documentation
typedef MCA_EXCEPTION ERROR_LOGRECORD
Definition at line 33 of file mca.c.
typedef MCA_EXCEPTION ERROR_RECORD_HEADER
Definition at line 34 of file mca.c.
typedef MCA_EXCEPTION * PERROR_LOGRECORD
Definition at line 33 of file mca.c.
typedef MCA_EXCEPTION * PERROR_RECORD_HEADER
Definition at line 34 of file mca.c.
typedef struct MCEQUERYINFO * PMCEQUERYINFO
Function Documentation
NTSTATUS WmipBuildMcaCmcEvent (OUT PWNODE_SINGLE_INSTANCE Wnode, IN LPGUID EventGuid, IN PERROR_LOGRECORD McaCmcEvent, IN ULONG McaCmcSize)
Definition at line 401 of file mca.c.
References _MSMCAInfo_RawCMCEvent::Count, _MSMCAInfo_Entry::Data, FIELD_OFFSET, IoWMIDeviceObjectToProviderId, KeQuerySystemTime(), _MSMCAInfo_Entry::Length, NULL, PAGED_CODE, _MSMCAInfo_RawCMCEvent::Records, RtlCopyMemory, RtlZeroMemory, STATUS_SUCCESS, WmipServiceDeviceObject, WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and WNODE_FLAG_STATIC_INSTANCE_NAMES.
Referenced by WmipGetLogFromHal().
BOOLEAN WmipCheckIsWbemRunning (void)
Definition at line 1915 of file mca.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, DPFLTR_WMICORE_ID, ExFreePool(), FALSE, Handle, InitializeObjectAttributes, IoWMIWriteEvent(), IsListEmpty, _WNODE_HEADER::Linkage, NT_SUCCESS, NULL, PAGED_CODE, _LARGE_INTEGER::QuadPart, RemoveHeadList(), RtlInitUnicodeString(), Status, STATUS_SUCCESS, SYNCHRONIZE, TRUE, WBEM_IS_RUNNING, WmipDebugPrintEx, WmipEnterSMCritSection, WmipIsWbemRunningFlag, WmipLeaveSMCritSection, ZwClose(), ZwOpenEvent(), and ZwWaitForSingleObject().
Referenced by WmipIsWbemRunningWorker(), and WmipWriteMCAEventLogEvent().
NTSTATUS WmipFireOffWmiEvent (LPGUID Guid, ULONG DataSize, PVOID DataPtr)
Definition at line 340 of file mca.c.
References _WNODE_HEADER::BufferSize, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, ExAllocatePoolWithTag, ExFreePool(), _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, IoWMIWriteEvent(), KeQuerySystemTime(), MCA_EVENT_INSTANCE_NAME, memcpy(), NonPagedPool, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, RtlCopyMemory, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, Status, STATUS_INSUFFICIENT_RESOURCES, _WNODE_HEADER::TimeStamp, WmipMCAPoolTag, WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipPollingDpcRoutine().
void WmipGenerateMCAEventlog (PUCHAR ErrorLog, ULONG ErrorLogSize, BOOLEAN IsFatal)
Definition at line 1579 of file mca.c.
References _MSMCAEvent_Header::AdditionalErrors, _WNODE_HEADER::BufferSize, _MSMCAEvent_Header::Cpu, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, ExAllocatePoolWithTag, ExFreePool(), FIELD_OFFSET, _WNODE_HEADER::Flags, _WNODE_HEADER::Guid, IoRaiseInformationalHardError(), _WNODE_HEADER::Linkage, _MSMCAEvent_Header::LogToEventlog, MAX_ERROR_EVENT_SIZE, MCA_ERROR_UNKNOWN, MCA_ERROR_UNKNOWN_NO_CPU, MCA_EVENT_INSTANCE_NAME, MCA_INFO_NO_MORE_CORRECTED_ERROR_LOGS, MCA_UNDEFINED_CPU, MCA_WARNING_UNKNOWN, MCA_WARNING_UNKNOWN_NO_CPU, NT_SUCCESS, NULL, tagWNODE_SINGLE_INSTANCE::OffsetInstanceName, OffsetToPtr, PAGED_CODE, PagedPool, _MSMCAEvent_InvalidError::RawRecord, RtlCopyMemory, _MSMCAEvent_InvalidError::Size, tagWNODE_SINGLE_INSTANCE::SizeDataBlock, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_MCA_OCCURED, STATUS_SUCCESS, _MSMCAEvent_InvalidError::Type, wcscpy, WmiInsertTimestamp, WmipAssert, WmipConstructMCAErrorEvent(), WmipCorrectedEventlogCounter, WmipDisableMCAPopups, WmipIsWbemRunning, WmipMCAPoolTag, WmipMSMCAEvent_InvalidErrorGuid, WmipWriteMCAEventLogEvent(), WmipWriteToEventlog(), WNODE_FLAG_EVENT_ITEM, WNODE_FLAG_SINGLE_INSTANCE, and tagWNODE_SINGLE_INSTANCE::WnodeHeader.
Referenced by WmipProcessPrevMcaLogs(), and WmipQueryLogAndFireEvent().
NTSTATUS WmipGetLogFromHal (HAL_QUERY_INFORMATION_CLASS InfoClass, PVOID Token, PWNODE_SINGLE_INSTANCE * Wnode, PERROR_LOGRECORD * Mca, PULONG McaSize, ULONG MaxSize, LPGUID Guid)
Referenced by WmipProcessPrevMcaLogs(), and WmipQueryLogAndFireEvent().
NTSTATUS WmipGetLogFromHal (IN HAL_QUERY_INFORMATION_CLASS InfoClass, IN PVOID Token, IN OUT PWNODE_SINGLE_INSTANCE * Wnode, OUT PERROR_LOGRECORD * Mca, OUT PULONG McaSize, IN ULONG MaxSize, IN LPGUID Guid)
Definition at line 1415 of file mca.c.
References ExAllocatePoolWithTag, ExFreePool(), FIELD_OFFSET, HalQuerySystemInformation, NonPagedPool, NT_SUCCESS, NULL, PAGED_CODE, Status, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, WmipAssert, WmipBuildMcaCmcEvent(), and WmipMCAPoolTag.
NTSTATUS WmipGetRawMCAInfo (OUT PUCHAR Buffer, IN OUT PULONG BufferSize)
Definition at line 1361 of file mca.c.
References NULL, PAGED_CODE, RtlCopyMemory, STATUS_BUFFER_TOO_SMALL, STATUS_SUCCESS, and WmipRawMCASize.
Referenced by WmipQueryWmiDataBlock().
void WmipInsertQueueMCEDpc (PMCEQUERYINFO QueryInfo)
Definition at line 1081 of file mca.c.
References MCEQUERYINFO::DeliveryDpc, MCEQUERYINFO::DpcLock, KeAcquireSpinLock, KeInsertQueueDpc(), KeReleaseSpinLock(), and NULL.
Referenced by WmipMceWorkerRoutine(), and WmipRegisterMcaHandler().
void WmipIsWbemRunningDispatch (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 1867 of file mca.c.
References DelayedWorkQueue, ExQueueWorkItem(), and UNREFERENCED_PARAMETER.
Referenced by WmipSetupWaitForWbem().
void WmipIsWbemRunningWorker (PVOID Context)
Definition at line 1883 of file mca.c.
References DPFLTR_WMICORE_ID, _LARGE_INTEGER::HighPart, KeSetTimer(), _LARGE_INTEGER::LowPart, PAGED_CODE, UNREFERENCED_PARAMETER, WmipCheckIsWbemRunning(), and WmipDebugPrintEx.
Referenced by WmipSetupWaitForWbem().
BOOLEAN WmipMceDelivery (IN PVOID Reserved, IN KERNEL_MCE_DELIVERY_OPERATION Operation, IN PVOID Argument2)
Definition at line 733 of file mca.c.
References CmcAvailable, CmcSwitchToPolledMode, CpeAvailable, CpeSwitchToPolledMode, MCEQUERYINFO::DeliveryDpc, MCEQUERYINFO::DpcLock, DPFLTR_WMICORE_ID, FALSE, HAL_MCE_INTERRUPTS_BASED, KeAcquireSpinLockAtDpcLevel(), KeInsertQueueDpc(), KeReleaseSpinLockFromDpcLevel(), McaAvailable, MCE_STATE_RUNNING, NULL, MCEQUERYINFO::PollFrequency, MCEQUERYINFO::PollingDpc, MCEQUERYINFO::Token, TRUE, WmipAssert, WmipCmcQueryInfo, WmipCpeQueryInfo, WmipDebugPrintEx, WmipMcaQueryInfo, and WmipMCEState.
Referenced by WmipRegisterMcaHandler().
void WmipMceDispatchRoutine (PMCEQUERYINFO QueryInfo)
Definition at line 637 of file mca.c.
References DelayedWorkQueue, DPFLTR_WMICORE_ID, ExQueueWorkItem(), InterlockedIncrement, MCEQUERYINFO::ItemsOutstanding, WmipDebugPrintEx, and MCEQUERYINFO::WorkItem.
Referenced by WmipMceDpcRoutine(), and WmipPollingDpcRoutine().
void WmipMceDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 664 of file mca.c.
References DPFLTR_WMICORE_ID, UNREFERENCED_PARAMETER, WmipDebugPrintEx, and WmipMceDispatchRoutine().
Referenced by WmipRegisterMcaHandler().
BOOLEAN WmipMceEventDelivery (IN PVOID Reserved, IN KERNEL_MCE_DELIVERY_OPERATION Operation, IN PVOID Argument2)
Definition at line 858 of file mca.c.
References MCEQUERYINFO::DeliveryDpc, MCEQUERYINFO::DpcLock, DPFLTR_WMICORE_ID, FALSE, HAL_MCE_INTERRUPTS_BASED, KeAcquireSpinLockAtDpcLevel(), KeInsertQueueDpc(), KeReleaseSpinLockFromDpcLevel(), KERNEL_MCE_EVENTTYPE, KERNEL_MCE_EVENTTYPE_CMC, KERNEL_MCE_EVENTTYPE_CPE, KERNEL_MCE_OPERATION, KERNEL_MCE_OPERATION_GET_STATE_INFO, MCE_STATE_RUNNING, MceNotification, NULL, MCEQUERYINFO::PollFrequency, WmipCmcQueryInfo, WmipCpeQueryInfo, WmipDebugPrintEx, and WmipMCEState.
Referenced by WmipRegisterMcaHandler().
void WmipMceWorkerRoutine (IN PVOID Context)
Definition at line 540 of file mca.c.
References Count, DPFLTR_WMICORE_ID, HAL_MCE_DISABLED, InterlockedExchange(), MCEQUERYINFO::ItemsOutstanding, NT_SUCCESS, PAGED_CODE, MCEQUERYINFO::PollFrequency, Status, WmipDebugPrintEx, WmipEnterSMCritSection, WmipInsertQueueMCEDpc(), WmipLeaveSMCritSection, WmipQueryLogAndFireEvent(), and MCEQUERYINFO::WorkerInProgress.
Referenced by WmipRegisterMcaHandler().
void WmipPollingDpcRoutine (IN PKDPC Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 683 of file mca.c.
References HAL_MCE_INTERRUPTS_BASED, KeSetTimerEx(), NULL, MCEQUERYINFO::PollFrequency, MCEQUERYINFO::PollingDpc, MCEQUERYINFO::PollingTimer, PtrToUlong, _LARGE_INTEGER::QuadPart, STATUS_SUCCESS, MCEQUERYINFO::SwitchToPollErrorCode, MCEQUERYINFO::SwitchToPollGuid, UNREFERENCED_PARAMETER, WmipFireOffWmiEvent(), WmipMceDispatchRoutine(), and WmipWriteToEventlog().
Referenced by WmipRegisterMcaHandler().
void WmipProcessPrevMcaLogs (void)
Definition at line 956 of file mca.c.
References _MSMCAInfo_RawMCAData::Count, _MSMCAInfo_Entry::Data, tagWNODE_SINGLE_INSTANCE::DataBlockOffset, ExAllocatePoolWithTag, ExFreePool(), FIELD_OFFSET, HalMcaLogInformation, InitializeListHead(), InsertTailList(), IsListEmpty, _MSMCAInfo_Entry::Length, MCEQUERYINFO::MaxSize, NT_SUCCESS, NULL, OffsetToPtr, PAGED_CODE, PagedPool, _MSMCAInfo_RawMCAData::Records, _MSMCAInfo_RawMCAEvent::Records, RemoveHeadList(), RtlCopyMemory, MCEQUERYINFO::Token, TRUE, WmipGenerateMCAEventlog(), WmipGetLogFromHal(), WmipMCAPoolTag, WmipRawMCASize, and MCEQUERYINFO::WnodeGuid.
Referenced by WmipRegisterMcaHandler().
NTSTATUS WmipQueryLogAndFireEvent (PMCEQUERYINFO QueryInfo)
Definition at line 466 of file mca.c.
References DPFLTR_WMICORE_ID, ExFreePool(), FALSE, MCEQUERYINFO::InfoClass, IoWMIWriteEvent(), MCEQUERYINFO::MaxSize, NT_SUCCESS, PAGED_CODE, Status, MCEQUERYINFO::Token, WmipDebugPrintEx, WmipGenerateMCAEventlog(), WmipGetLogFromHal(), and MCEQUERYINFO::WnodeGuid.
Referenced by WmipMceWorkerRoutine().
NTSTATUS WmipRegisterMcaHandler (ULONG Phase)
Definition at line 1096 of file mca.c.
References _HAL_ERROR_INFO::CmcMaxSize, _HAL_ERROR_INFO::CmcPollingInterval, _HAL_ERROR_INFO::CpeMaxSize, _HAL_ERROR_INFO::CpePollingInterval, MCEQUERYINFO::DeliveryDpc, MCEQUERYINFO::DpcLock, DPFLTR_ERROR_LEVEL, DPFLTR_WMICORE_ID, ExInitializeWorkItem, HAL_CMC_DISABLED, HAL_CMC_INTERRUPTS_BASED, HAL_CPE_DISABLED, HAL_CPE_INTERRUPTS_BASED, HAL_ERROR_INFO_VERSION, HalErrorInformation, HalKernelErrorHandler, HalQuerySystemInformation, HalSetSystemInformation, KeInitializeDpc(), KeInitializeSpinLock(), KeInitializeTimerEx(), KERNEL_ERROR_HANDLER_VERSION, KERNEL_ERROR_HANDLER_INFO::KernelCmcDelivery, KERNEL_ERROR_HANDLER_INFO::KernelCpeDelivery, KERNEL_ERROR_HANDLER_INFO::KernelMcaDelivery, KERNEL_ERROR_HANDLER_INFO::KernelMceDelivery, KeSetTimerEx(), MCEQUERYINFO::MaxSize, _HAL_ERROR_INFO::McaMaxSize, _HAL_ERROR_INFO::McaPreviousEventsCount, MCE_STATE_ERROR, MCE_STATE_REGISTERED, MCE_STATE_RUNNING, NotificationTimer, NT_SUCCESS, NULL, PAGED_CODE, MCEQUERYINFO::PollFrequency, MCEQUERYINFO::PollingDpc, MCEQUERYINFO::PollingTimer, _LARGE_INTEGER::QuadPart, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, MCEQUERYINFO::Token, KERNEL_ERROR_HANDLER_INFO::Version, _HAL_ERROR_INFO::Version, WmipCorrectedEventlogCounter, WmipDebugPrintEx, WmipInsertQueueMCEDpc(), WmipMceDelivery(), WmipMceDpcRoutine(), WmipMceEventDelivery(), WmipMCEState, WmipMceWorkerRoutine(), WmipPollingDpcRoutine(), WmipProcessPrevMcaLogs(), and MCEQUERYINFO::WorkItem.
Referenced by WMIInitialize().
NTSTATUS WmipSetupWaitForWbem (void)
Definition at line 1830 of file mca.c.
References DPFLTR_WMICORE_ID, ExInitializeWorkItem, _LARGE_INTEGER::HighPart, KeInitializeDpc(), KeInitializeTimer(), KeSetTimer(), _LARGE_INTEGER::LowPart, NULL, PAGED_CODE, Status, STATUS_SUCCESS, WmipDebugPrintEx, WmipIsWbemRunningDispatch(), WmipIsWbemRunningWorker(), and WmipWbemMinuteWait.
Referenced by WmipWriteMCAEventLogEvent().
NTSTATUS WmipWriteMCAEventLogEvent (PUCHAR Event)
Definition at line 1777 of file mca.c.
References _WNODE_HEADER::BufferSize, _WNODE_HEADER::ClientContext, InsertTailList(), IoWMIWriteEvent(), NT_SUCCESS, PAGED_CODE, Status, STATUS_SUCCESS, WAITING_FOR_WBEM, WBEM_STATUS_UNKNOWN, WmipCheckIsWbemRunning(), WmipEnterSMCritSection, WmipIsWbemRunning, WmipIsWbemRunningFlag, WmipLeaveSMCritSection, and WmipSetupWaitForWbem().
Referenced by WmipGenerateMCAEventlog().
NTSTATUS WmipWriteToEventlog (NTSTATUS ErrorCode, NTSTATUS FinalStatus)
Definition at line 309 of file mca.c.
References _IO_ERROR_LOG_PACKET::ErrorCode, _IO_ERROR_LOG_PACKET::FinalStatus, IoAllocateErrorLogEntry(), IoWriteErrorLogEntry(), NULL, _IO_ERROR_LOG_PACKET::NumberOfStrings, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _IO_ERROR_LOG_PACKET::StringOffset, and WmipServiceDeviceObject.
Referenced by WmipGenerateMCAEventlog(), and WmipPollingDpcRoutine().
Variable Documentation
MCEQUERYINFO WmipCmcQueryInfo
Initial value:
=
{
    HalCmcLogInformation,
    HAL_CMC_DISABLED,
    NULL,
    0,
    DEFAULT_MAX_CMC_SIZE,
    MSMCAInfo_RawCMCEventGuid,
    MSMCAEvent_SwitchToCMCPollingGuid,
    MCA_WARNING_CMC_THRESHOLD_EXCEEDED,
    0
}
Definition at line 193 of file mca.c.
Referenced by WmipMceDelivery(), and WmipMceEventDelivery().
ULONG WmipCoalesceCorrectedErrorInterval = 5000
Definition at line 264 of file mca.c.
ULONG WmipCorrectedEventlogCounter = 20
Definition at line 294 of file mca.c.
Referenced by WmipGenerateMCAEventlog(), and WmipRegisterMcaHandler().
ULONG WmipCorrectedMCECount
Definition at line 287 of file mca.c.
LIST_ENTRY WmipCorrectedMCEHead = {&WmipCorrectedMCEHead, &WmipCorrectedMCEHead}
Definition at line 286 of file mca.c.
MCEQUERYINFO WmipCpeQueryInfo
Initial value:
=
{
    HalCpeLogInformation,
    HAL_CPE_DISABLED,
    NULL,
    0,
    DEFAULT_MAX_CPE_SIZE,
    MSMCAInfo_RawCorrectedPlatformEventGuid,
    MSMCAEvent_SwitchToCPEPollingGuid,
    MCA_WARNING_CPE_THRESHOLD_EXCEEDED,
    0
}
Definition at line 206 of file mca.c.
Referenced by WmipMceDelivery(), and WmipMceEventDelivery().
ULONG WmipDisableMCAPopups
Definition at line 131 of file mca.c.
Referenced by WmipGenerateMCAEventlog().
KDPC WmipIsWbemRunningDpc
Definition at line 223 of file mca.c.
UCHAR WmipIsWbemRunningFlag
Definition at line 230 of file mca.c.
Referenced by WmipCheckIsWbemRunning(), and WmipWriteMCAEventLogEvent().
KTIMER WmipIsWbemRunningTimer
Definition at line 222 of file mca.c.
WORK_QUEUE_ITEM WmipIsWbemRunningWorkItem
Definition at line 224 of file mca.c.
ULONG WmipMaxCorrectedMCEOutstanding = 5
Definition at line 281 of file mca.c.
MCEQUERYINFO WmipMcaQueryInfo
Initial value:
=
{
    HalMcaLogInformation,
    HAL_MCA_INTERRUPTS_BASED,
    NULL,
    0,
    DEFAULT_MAX_MCA_SIZE,
    MSMCAInfo_RawMCAEventGuid
}
Definition at line 183 of file mca.c.
Referenced by WmipMceDelivery().
ULONG WmipMCEState
Definition at line 251 of file mca.c.
Referenced by WmipMceDelivery(), WmipMceEventDelivery(), and WmipRegisterMcaHandler().
GUID WmipMSMCAEvent_InvalidErrorGuid = MSMCAEvent_InvalidErrorGuid
Definition at line 133 of file mca.c.
Referenced by WmipGenerateMCAEventlog().
PMSMCAInfo_RawMCAData WmipRawMCA
Definition at line 242 of file mca.c.
ULONG WmipRawMCASize
Definition at line 241 of file mca.c.
Referenced by WmipGetRawMCAInfo(), and WmipProcessPrevMcaLogs().
ULONG WmipSingleBitEccErrorThreshold = 6
Definition at line 272 of file mca.c.
LIST_ENTRY WmipWaitingMCAEvents = {&WmipWaitingMCAEvents, &WmipWaitingMCAEvents}
Definition at line 225 of file mca.c.
ULONG WmipWbemMinuteWait = 1
Definition at line 1828 of file mca.c.
Referenced by WmipSetupWaitForWbem().