Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obdevmap.c File Reference
obdevmap.c File Reference
#include "obp.h"
Functions
VOID ObDereferenceDeviceMap (IN PEPROCESS Process)
VOID ObInheritDeviceMap (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess OPTIONAL)
ULONG ObIsLUIDDeviceMapsEnabled ()
NTSTATUS ObQueryDeviceMapInformation (IN PEPROCESS TargetProcess OPTIONAL, OUT PPROCESS_DEVICEMAP_INFORMATION DeviceMapInformation, IN ULONG Flags)
NTSTATUS ObSetDeviceMap (IN PEPROCESS TargetProcess OPTIONAL, IN HANDLE DirectoryHandle)
NTSTATUS ObSetDirectoryDeviceMap (OUT PDEVICE_MAP *ppDeviceMap OPTIONAL, IN HANDLE DirectoryHandle)
Variables
ULONG ObpLUIDDeviceMapsEnabled
Function Documentation
VOID ObDereferenceDeviceMap (IN PEPROCESS Process)
Definition at line 640 of file obdevmap.c.
References NULL, ObfDereferenceDeviceMap(), ObpLockDeviceMap, and ObpUnlockDeviceMap.
Referenced by PspProcessDelete(), and PspSetPrimaryToken().
VOID ObInheritDeviceMap (IN PEPROCESS NewProcess, IN PEPROCESS ParentProcess OPTIONAL)
Definition at line 571 of file obdevmap.c.
References NULL, ObpLockDeviceMap, ObpUnlockDeviceMap, ObSystemDeviceMap, and _DEVICE_MAP::ReferenceCount.
Referenced by PspCreateProcess().
ULONG ObIsLUIDDeviceMapsEnabled ()
Definition at line 701 of file obdevmap.c.
References ObpLUIDDeviceMapsEnabled.
Referenced by IoDeleteSymbolicLink(), NtQueryInformationProcess(), and PspSetPrimaryToken().
NTSTATUS ObQueryDeviceMapInformation (IN PEPROCESS TargetProcess OPTIONAL, OUT PPROCESS_DEVICEMAP_INFORMATION DeviceMapInformation, IN ULONG Flags)
Definition at line 393 of file obdevmap.c.
References ARGUMENT_PRESENT, _OBJECT_DIRECTORY::DeviceMap, DOSDEVICE_DRIVE_CALCULATE, DOSDEVICE_DRIVE_REMOTE, _DEVICE_MAP::DriveMap, _DEVICE_MAP::DriveType, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _DEVICE_MAP::GlobalDosDevicesDirectory, NULL, ObfDereferenceDeviceMap(), ObpLockDeviceMap, ObpLUIDDeviceMapsEnabled, ObpReferenceDeviceMap(), ObpUnlockDeviceMap, ObSystemDeviceMap, PROCESS_LUID_DOSDEVICES_ONLY, PsGetCurrentProcess(), _PROCESS_DEVICEMAP_INFORMATION::Query, RtlCopyMemory, Status, STATUS_END_OF_FILE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and TRUE.
Referenced by NtQueryInformationProcess().
NTSTATUS ObSetDeviceMap (IN PEPROCESS TargetProcess OPTIONAL, IN HANDLE DirectoryHandle)
Definition at line 227 of file obdevmap.c.
References _EPROCESS::DeviceMap, _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_TRAVERSE, _DEVICE_MAP::DosDevicesDirectory, ExAllocatePoolWithTag, ExFreePool(), FALSE, _OBJECT_HEADER::Flags, _DEVICE_MAP::GlobalDosDevicesDirectory, KeGetPreviousMode, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, OB_NAMESPACE_POOL_TYPE, ObDereferenceObject(), ObfDereferenceDeviceMap(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpLockDeviceMap, ObpLockObject, ObpReferenceNameInfo(), ObpUnlockDeviceMap, ObpUnlockObject, ObReferenceObjectByHandle, ObSystemDeviceMap, PAGED_CODE, PsGetCurrentProcess(), _DEVICE_MAP::ReferenceCount, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, and TRUE.
Referenced by NtSetInformationProcess(), and ObpCreateDosDevicesDirectory().
NTSTATUS ObSetDirectoryDeviceMap (OUT PDEVICE_MAP *ppDeviceMap OPTIONAL, IN HANDLE DirectoryHandle)
Definition at line 76 of file obdevmap.c.
References _OBJECT_DIRECTORY::DeviceMap, _OBJECT_HEADER_NAME_INFO::Directory, DIRECTORY_TRAVERSE, _DEVICE_MAP::DosDevicesDirectory, ExAllocatePoolWithTag, ExFreePool(), _OBJECT_HEADER::Flags, _DEVICE_MAP::GlobalDosDevicesDirectory, KernelMode, NT_SUCCESS, NULL, OB_FLAG_PERMANENT_OBJECT, OB_NAMESPACE_POOL_TYPE, ObDereferenceObject(), OBJECT_TO_OBJECT_HEADER, ObpDereferenceNameInfo(), ObpDirectoryObjectType, ObpLockDeviceMap, ObpLockObject, ObpReferenceNameInfo(), ObpUnlockDeviceMap, ObpUnlockObject, ObReferenceObjectByHandle, ObSystemDeviceMap, PAGED_CODE, _DEVICE_MAP::ReferenceCount, RtlZeroMemory, Status, and STATUS_INSUFFICIENT_RESOURCES.
Referenced by SeGetLogonIdDeviceMap().
Variable Documentation
ULONG ObpLUIDDeviceMapsEnabled
Definition at line 188 of file obinit.c.
Referenced by ObIsLUIDDeviceMapsEnabled(), and ObQueryDeviceMapInformation().