Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psquery.c File Reference
psquery.c File Reference
#include "psp.h"
#include "winerror.h"
Macros
#define PSMAX(a, b) (((a) > (b))?(a):(b))
Functions
ULONG NtGetCurrentProcessorNumber (VOID)
NTSTATUS NtQueryInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __out_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtQueryInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __out_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtQueryPortInformationProcess (VOID)
NTSTATUS NtSetInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __in_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength)
NTSTATUS NtSetInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __in_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength)
NTSTATUS PsConvertToGuiThread (VOID)
NTKERNELAPI VOID PsEstablishWin32Callouts (__in PKWIN32_CALLOUTS_FPNS pWin32Callouts)
KPRIORITY PspComputeQuantumAndPriority (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode, __out PSCHAR QuantumReset)
NTSTATUS PspQueryPooledQuotaLimits (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, OUT PVOID ProcessInformation, IN ULONG ProcessInformationLength, OUT PULONG ReturnLength OPTIONAL, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS PspQueryQuotaLimits (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, OUT PVOID ProcessInformation, IN ULONG ProcessInformationLength, OUT PULONG ReturnLength OPTIONAL, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS PspQueryWorkingSetWatch (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, OUT PVOID ProcessInformation, IN ULONG ProcessInformationLength, OUT PULONG ReturnLength OPTIONAL, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS PspSetPrimaryToken (IN HANDLE ProcessHandle OPTIONAL, IN PEPROCESS ProcessPointer OPTIONAL, IN HANDLE TokenHandle OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL, IN BOOLEAN PrivilegeChecked)
NTSTATUS PspSetQuotaLimits (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, IN PVOID ProcessInformation, IN ULONG ProcessInformationLength, IN KPROCESSOR_MODE PreviousMode)
VOID PsSetProcessPriorityByClass (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode)
VOID PsWatchWorkingSet (IN NTSTATUS Status, IN PVOID PcValue, IN PVOID Va)
Variables
PEPROCESS ExpDefaultErrorPortProcess
PKWIN32_POWEREVENT_CALLOUT PopEventCallout
PKWIN32_POWERSTATE_CALLOUT PopStateCallout
const KPRIORITY PspPriorityTable [PROCESS_PRIORITY_CLASS_ABOVE_NORMAL+1] = {8,4,8,13,24,6,10}
PKWIN32_JOB_CALLOUT PspW32JobCallout = NULL
PKWIN32_PROCESS_CALLOUT PspW32ProcessCallout = NULL
PKWIN32_THREAD_CALLOUT PspW32ThreadCallout = NULL
BOOLEAN PsWatchEnabled = FALSE
Macro Definition Documentation
#define PSMAX (a, b) (((a) > (b))?(a):(b))
Referenced by PspQueryPooledQuotaLimits().
Function Documentation
ULONG NtGetCurrentProcessorNumber (VOID)
Definition at line 4214 of file psquery.c.
References KeGetCurrentProcessorNumber().
NTSTATUS NtQueryInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __out_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength, __out_opt PULONG ReturnLength)
Definition at line 590 of file psquery.c.
References _KPROCESS::Affinity, _PROCESS_BASIC_INFORMATION::AffinityMask, ARGUMENT_PRESENT, _PROCESS_BASIC_INFORMATION::BasePriority, _KPROCESS::BasePriority, _PROCESS_HANDLE_TRACING_ENTRY::ClientId, _HANDLE_TRACE_DB_ENTRY::ClientId, _EPROCESS::CommitCharge, _EPROCESS::Cookie, _EPROCESS::CreateTime, _KERNEL_USER_TIMES::CreateTime, _HANDLE_TRACE_DEBUG_INFO::CurrentStackIndex, DbgkOpenProcessDebugPort(), _EPROCESS::DebugPort, _EPROCESS::DefaultHardErrorProcessing, _KPROCESS::DisableBoost, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExDereferenceHandleDebugInfo(), ExFreePool(), _EPROCESS::ExitStatus, _PROCESS_BASIC_INFORMATION::ExitStatus, _EPROCESS::ExitTime, _KERNEL_USER_TIMES::ExitTime, ExReferenceHandleDebugInfo(), ExReleaseRundownProtection(), FALSE, FIELD_OFFSET, _EPROCESS::Flags, _PROCESS_PRIORITY_CLASS::Foreground, _PROCESS_HANDLE_TRACING_ENTRY::Handle, _PROCESS_HANDLE_TRACING_QUERY::Handle, _HANDLE_TRACE_DB_ENTRY::Handle, _PROCESS_HANDLE_TRACING_QUERY::HandleTrace, _LARGE_INTEGER::HighPart, _EPROCESS::InheritedFromUniqueProcessId, _PROCESS_BASIC_INFORMATION::InheritedFromUniqueProcessId, InterlockedCompareExchange(), _KPRCB::InterruptTime, KeGetCurrentPrcb(), KeGetPreviousMode, KeMaximumIncrement, KeQueryRuntimeProcess(), KeQuerySystemTime(), KeQueryValuesProcess(), KernelMode, _KERNEL_USER_TIMES::KernelTime, KeStackAttachProcess(), _KPRCB::KeSystemCalls, KeUnstackDetachProcess(), _LARGE_INTEGER::LowPart, _UNICODE_STRING::MaximumLength, min, MmGetExecuteOptions(), MmGetImageInformation(), MmGetSessionId(), MmQueryWorkingSetInformation(), NT_SUCCESS, NtCurrentProcess, NULL, ObCloseHandle(), ObDereferenceObject(), ObDereferenceProcessHandleTable(), ObGetProcessHandleCount(), ObIsLUIDDeviceMapsEnabled(), ObQueryDeviceMapInformation(), ObReferenceObjectByHandle, ObReferenceProcessHandleTable(), _IO_COUNTERS::OtherOperationCount, _KPROCESS_VALUES::OtherOperationCount, _IO_COUNTERS::OtherTransferCount, _KPROCESS_VALUES::OtherTransferCount, PAGE_SHIFT, PAGED_CODE, _MMSUPPORT::PageFaultCount, _VM_COUNTERS_EX::PageFaultCount, _VM_COUNTERS_EX::PagefileUsage, _EPROCESS::Pcb, _VM_COUNTERS_EX::PeakPagefileUsage, _EPROCESS::PeakVirtualSize, _VM_COUNTERS_EX::PeakVirtualSize, _VM_COUNTERS_EX::PeakWorkingSetSize, _EPROCESS::Peb, _PROCESS_BASIC_INFORMATION::PebBaseAddress, _PROCESS_PRIORITY_CLASS::PriorityClass, _EPROCESS::PriorityClass, _VM_COUNTERS_EX::PrivateUsage, ProbeForRead, ProbeForWriteUlong, PROCESS_DEBUG_INHERIT, PROCESS_LUID_DOSDEVICES_ONLY, PROCESS_QUERY_INFORMATION, PROCESS_VM_READ, ProcessBasicInformation, ProcessBreakOnTermination, ProcessCookie, ProcessDebugFlags, ProcessDebugObjectHandle, ProcessDebugPort, ProcessDefaultHardErrorMode, ProcessDeviceMap, ProcessExecuteFlags, ProcessHandleCount, ProcessHandleTracing, ProcessImageFileName, ProcessImageInformation, ProcessIoCounters, ProcessLdtInformation, ProcessLUIDDeviceMapsEnabled, ProcessPooledUsageAndLimits, ProcessPriorityBoost, ProcessPriorityClass, ProcessQuotaLimits, ProcessSessionInformation, ProcessTimes, ProcessVmCounters, ProcessWorkingSetWatch, ProcessWow64Information, ProcessWx86Information, PS_GET_WOW64_PROCESS, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_PROCESS_FLAGS_VDM_ALLOWED, PsGetCurrentProcess(), PsNonPagedPool, PsPagedPool, PsPageFile, PspQueryLdtInformation(), PspQueryPooledQuotaLimits(), PspQueryQuotaLimits(), PspQueryWorkingSetWatch(), PsProcessType, _LARGE_INTEGER::QuadPart, _PROCESS_DEVICEMAP_INFORMATION::Query, _VM_COUNTERS_EX::QuotaNonPagedPoolUsage, _VM_COUNTERS_EX::QuotaPagedPoolUsage, _EPROCESS::QuotaPeak, _VM_COUNTERS_EX::QuotaPeakNonPagedPoolUsage, _VM_COUNTERS_EX::QuotaPeakPagedPoolUsage, _EPROCESS::QuotaUsage, _IO_COUNTERS::ReadOperationCount, _KPROCESS_VALUES::ReadOperationCount, _IO_COUNTERS::ReadTransferCount, _KPROCESS_VALUES::ReadTransferCount, RtlCopyMemory, _EPROCESS::RundownProtect, SeLocateProcessImageName(), _PROCESS_SESSION_INFORMATION::SessionId, _PROCESS_HANDLE_TRACING_ENTRY::Stacks, _HANDLE_TRACE_DB_ENTRY::StackTrace, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _HANDLE_TRACE_DEBUG_INFO::TableSize, _PROCESS_HANDLE_TRACING_QUERY::TotalTraces, _HANDLE_TRACE_DEBUG_INFO::TraceDb, _PROCESS_HANDLE_TRACING_ENTRY::Type, _HANDLE_TRACE_DB_ENTRY::Type, UInt32x32To64, _EPROCESS::UniqueProcessId, _PROCESS_BASIC_INFORMATION::UniqueProcessId, _KERNEL_USER_TIMES::UserTime, _EPROCESS::VirtualSize, _VM_COUNTERS_EX::VirtualSize, _EPROCESS::Vm, _VM_COUNTERS_EX::WorkingSetSize, _WOW64_PROCESS::Wow64, _IO_COUNTERS::WriteOperationCount, _KPROCESS_VALUES::WriteOperationCount, _IO_COUNTERS::WriteTransferCount, and _KPROCESS_VALUES::WriteTransferCount.
Referenced by RtlSetProcessIsCritical().
NTSTATUS NtQueryInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __out_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength, __out_opt PULONG ReturnLength)
Definition at line 3041 of file psquery.c.
References _EPROCESS::ActiveThreads, _KTHREAD::Affinity, _THREAD_BASIC_INFORMATION::AffinityMask, ARGUMENT_PRESENT, _THREAD_BASIC_INFORMATION::BasePriority, _ETHREAD::Cid, _THREAD_BASIC_INFORMATION::ClientId, _KERNEL_USER_TIMES::CreateTime, _ETHREAD::CrossThreadFlags, _KTHREAD::DisableBoost, except, EXCEPTION_EXECUTE_HANDLER, _ETHREAD::ExitStatus, _THREAD_BASIC_INFORMATION::ExitStatus, _ETHREAD::ExitTime, _KERNEL_USER_TIMES::ExitTime, _LARGE_INTEGER::HighPart, _ETHREAD::IrpList, IsListEmpty, KeGetPreviousModeByThread, KeMaximumIncrement, KeQueryBasePriorityThread(), KeReadStateThread(), KernelMode, _KERNEL_USER_TIMES::KernelTime, _KTHREAD::KernelTime, _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _THREAD_BASIC_INFORMATION::Priority, _KTHREAD::Priority, ProbeForRead, ProbeForWriteUlong, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_GET_THREAD_CREATE_TIME, PsGetCurrentThread(), PsIsThreadTerminating(), PspQueryDescriptorThread(), PsThreadType, _LARGE_INTEGER::QuadPart, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_PENDING, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, _THREAD_BASIC_INFORMATION::TebBaseAddress, THREAD_QUERY_INFORMATION, THREAD_TO_PROCESS, ThreadAmILastThread, ThreadBasicInformation, ThreadBreakOnTermination, ThreadDescriptorTableEntry, ThreadIsIoPending, ThreadIsTerminated, ThreadPerformanceCount, ThreadPriorityBoost, ThreadQuerySetWin32StartAddress, ThreadTimes, TRUE, UInt32x32To64, _KERNEL_USER_TIMES::UserTime, _KTHREAD::UserTime, and _ETHREAD::Win32StartAddress.
Referenced by RtlFreeUserThreadStack(), and RtlSetThreadIsCritical().
NTSTATUS NtQueryPortInformationProcess (VOID)
Definition at line 1668 of file psquery.c.
References TRUE.
NTSTATUS NtSetInformationProcess (__in HANDLE ProcessHandle, __in PROCESSINFOCLASS ProcessInformationClass, __in_bcount(ProcessInformationLength) PVOID ProcessInformation, __in ULONG ProcessInformationLength)
Definition at line 1981 of file psquery.c.
References _EJOB::Affinity, _KPROCESS::BasePriority, CONTAINING_RECORD, _PAGEFAULT_HISTORY::CurrentIndex, _EPROCESS::DefaultHardErrorProcessing, ExAcquireResourceSharedLite(), ExAcquireRundownProtection(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExDisableHandleTracing(), ExEnableHandleTracing(), ExFreePool(), ExReleaseResourceLite(), ExReleaseRundownProtection(), FALSE, _EPROCESS::Flags, _PROCESS_HANDLE_TRACING_ENABLE_EX::Flags, _LIST_ENTRY::Flink, _PROCESS_PRIORITY_CLASS::Foreground, _PROCESS_FOREGROUND_BACKGROUND::Foreground, HIGH_PRIORITY, InterlockedCompareExchangePointer, _EPROCESS::Job, JOB_OBJECT_LIMIT_AFFINITY, JOB_OBJECT_LIMIT_PRIORITY_CLASS, _EJOB::JobLock, Ke386SetIOPL(), KeActiveProcessors, KeBoostPriorityThread(), KeEnterCriticalRegionThread(), KeGetPreviousModeByThread, KeInitializeSpinLock(), KeLeaveCriticalRegionThread(), KernelMode, KeSetAffinityProcess(), KeSetAutoAlignmentProcess(), KeSetDisableBoostProcess(), KeSetDisableBoostThread(), KeSetPriorityAndQuantumProcess(), _EJOB::LimitFlags, LOW_PRIORITY, LpcPortObjectType, MAX_WS_CATCH_INDEX, _PAGEFAULT_HISTORY::MaxIndex, MEMORY_PRIORITY_BACKGROUND, MEMORY_PRIORITY_FOREGROUND, MmGetSessionId(), MmSetExecuteOptions(), MmSetMemoryPriorityProcess(), NonPagedPool, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObDereferenceProcessHandleTable(), ObReferenceObjectByHandle, ObReferenceProcessHandleTable(), ObSetDeviceMap(), PAGED_CODE, _EPROCESS::Pcb, _PROCESS_PRIORITY_CLASS::PriorityClass, _EPROCESS::PriorityClass, _EJOB::PriorityClass, ProbeForRead, PROCESS_DEBUG_INHERIT, PROCESS_HARDERROR_ALIGNMENT_BIT, PROCESS_PRIORITY_CLASS_ABOVE_NORMAL, PROCESS_PRIORITY_CLASS_REALTIME, PROCESS_SET_INFORMATION, PROCESS_SET_PORT, PROCESS_SET_SESSIONID, PROCESS_VM_WRITE, ProcessAccessToken, ProcessAffinityMask, ProcessBasePriority, ProcessBreakOnTermination, ProcessDebugFlags, ProcessDefaultHardErrorMode, ProcessDeviceMap, ProcessEnableAlignmentFaultFixup, ProcessExceptionPort, ProcessExecuteFlags, ProcessForegroundInformation, ProcessHandleTracing, ProcessIoPortHandlers, ProcessLdtInformation, ProcessLdtSize, ProcessPriorityBoost, ProcessPriorityClass, ProcessQuotaLimits, ProcessRaisePriority, ProcessSessionInformation, ProcessUserModeIOPL, ProcessWorkingSetWatch, ProcessWx86Information, PS_CLEAR_BITS, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_NO_DEBUG_INHERIT, PS_PROCESS_FLAGS_VDM_ALLOWED, PS_SET_BITS, PsChargeProcessNonPagedPoolQuota(), PsGetCurrentThread(), PsGetNextProcessThread(), PspLockProcessExclusive(), PsProcessPriorityBackground, PsProcessPriorityForeground, PsProcessType, PspSetLdtInformation(), PspSetLdtSize(), PspSetPrimaryToken(), PspSetProcessIoHandlers(), PspSetQuotaLimits(), PspUnlockProcessExclusive(), PsReturnProcessNonPagedPoolQuota(), PsSetProcessPriorityByClass(), PsWatchEnabled, _EPROCESS::RundownProtect, SeCheckPrivilegedObject(), SeDebugPrivilege, SeIncreaseBasePriorityPrivilege, SeSinglePrivilegeCheck(), _PROCESS_SESSION_INFORMATION::SessionId, _PROCESS_DEVICEMAP_INFORMATION::Set, SeTcbPrivilege, _PAGEFAULT_HISTORY::SpinLock, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_ALREADY_SET, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, _EPROCESS::ThreadListHead, _PROCESS_HANDLE_TRACING_ENABLE_EX::TotalSlots, TRUE, _EPROCESS::WorkingSetWatch, and WS_CATCH_SIZE.
Referenced by RtlSetProcessIsCritical().
NTSTATUS NtSetInformationThread (__in HANDLE ThreadHandle, __in THREADINFOCLASS ThreadInformationClass, __in_bcount(ThreadInformationLength) PVOID ThreadInformation, __in ULONG ThreadInformationLength)
Definition at line 3503 of file psquery.c.
References _KPROCESS::Affinity, _ETHREAD::CrossThreadFlags, ExAcquireRundownProtection(), except, EXCEPTION_EXECUTE_HANDLER, ExReleaseRundownProtection(), FALSE, HIGH_PRIORITY, _KTHREAD::IdealProcessor, _EPROCESS::Job, JOB_OBJECT_LIMIT_PRIORITY_CLASS, KeGetPreviousModeByThread, KernelMode, KeSetAffinityThread(), KeSetAutoAlignmentThread(), KeSetBasePriorityThread(), KeSetDisableBoostThread(), KeSetIdealProcessorThread(), KeSetPriorityThread(), KeStackAttachProcess(), KeUnstackDetachProcess(), _EJOB::LimitFlags, LOW_PRIORITY, LOW_REALTIME_PRIORITY, MAXIMUM_PROCESSORS, _KTHREAD::NpxState, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _EPROCESS::Pcb, Priority, _EPROCESS::PriorityClass, ProbeAndReadUlong, ProbeAndWriteLong, ProbeAndWriteUlong, ProbeForRead, ProbeForReadSmallStructure, PROCESS_PRIORITY_CLASS_REALTIME, PS_CLEAR_BITS, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PS_SET_BITS, PsAssignImpersonationToken(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsGetNextProcessThread(), PspLockProcessShared(), PspUnlockProcessShared(), PsThreadType, _EPROCESS::RundownProtect, _ETHREAD::RundownProtect, SeCheckPrivilegedObject(), SeDebugPrivilege, SeIncreaseBasePriorityPrivilege, SeSinglePrivilegeCheck(), STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, _KTHREAD::Teb, THREAD_BASE_PRIORITY_IDLE, THREAD_BASE_PRIORITY_LOWRT, THREAD_BASE_PRIORITY_MAX, THREAD_BASE_PRIORITY_MIN, THREAD_SET_INFORMATION, THREAD_SET_THREAD_TOKEN, THREAD_TO_PROCESS, ThreadAffinityMask, ThreadBasePriority, ThreadBreakOnTermination, ThreadEnableAlignmentFaultFixup, ThreadHideFromDebugger, ThreadIdealProcessor, ThreadImpersonationToken, ThreadPriority, ThreadPriorityBoost, ThreadQuerySetWin32StartAddress, ThreadSetTlsArrayAddress, ThreadSwitchLegacyState, ThreadZeroTlsCell, TLS_EXPANSION_SLOTS, TLS_MINIMUM_AVAILABLE, _KTHREAD::TlsArray, TRUE, ULongToPtr, _ETHREAD::Win32StartAddress, and WOW64_GET_TEB32.
Referenced by RtlpImpersonateSelfEx(), and RtlSetThreadIsCritical().
NTSTATUS PsConvertToGuiThread (VOID)
Definition at line 4467 of file psquery.c.
References ASSERT, _KSERVICE_TABLE_DESCRIPTOR::Base, ERROR_NOT_ENOUGH_MEMORY, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _KTHREAD::IdealProcessor, KeEnterGuardedRegionThread(), KeGetPreviousModeByThread, KeLeaveGuardedRegionThread(), KERNEL_LARGE_STACK_COMMIT, KernelMode, KeServiceDescriptorTable, KeServiceDescriptorTableShadow, KeSwitchKernelStack(), KiProcessorBlock, _KTHREAD::LargeStack, _KSERVICE_TABLE_DESCRIPTOR::Limit, MmCreateKernelStack(), MmDeleteKernelStack(), NT_SUCCESS, NtCurrentTeb(), NULL, PAGED_CODE, _KPRCB::ParentNode, PERFINFO_CONVERT_TO_GUI_THREAD, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspW32ProcessCallout, PspW32ThreadCallout, PsW32ThreadCalloutInitialize, _KTHREAD::ServiceTable, Status, STATUS_ACCESS_DENIED, STATUS_ALREADY_WIN32, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, _ETHREAD::Tcb, TRUE, WIN32K_SERVICE_INDEX, and _KTHREAD::Win32Thread.
NTKERNELAPI VOID PsEstablishWin32Callouts (__in PKWIN32_CALLOUTS_FPNS pWin32Callouts)
Definition at line 4300 of file psquery.c.
References ExDesktopCloseProcedureCallout, ExDesktopDeleteProcedureCallout, ExDesktopOkToCloseProcedureCallout, ExDesktopOpenProcedureCallout, ExGlobalAtomTableCallout, ExWindowStationCloseProcedureCallout, ExWindowStationDeleteProcedureCallout, ExWindowStationOkToCloseProcedureCallout, ExWindowStationOpenProcedureCallout, ExWindowStationParseProcedureCallout, KeGdiFlushUserBatch, and PAGED_CODE.
KPRIORITY PspComputeQuantumAndPriority (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode, __out PSCHAR QuantumReset)
Definition at line 4387 of file psquery.c.
References FALSE, MEMORY_PRIORITY_BACKGROUND, MEMORY_PRIORITY_FOREGROUND, MmSetMemoryPriorityProcess(), NULL, PAGED_CODE, PROCESS_PRIORITY_CLASS_IDLE, PspForegroundQuantum, PspJobSchedulingClasses, PspPriorityTable, PsPrioritySeparation, PsProcessPriorityForeground, PsProcessPrioritySpinning, PspUseJobSchedulingClasses, _EJOB::SchedulingClass, and THREAD_QUANTUM.
Referenced by PspCreateProcess(), and PsSetProcessPriorityByClass().
NTSTATUS PspQueryPooledQuotaLimits (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, OUT PVOID ProcessInformation, IN ULONG ProcessInformationLength, OUT PULONG ReturnLength OPTIONAL, IN KPROCESSOR_MODE PreviousMode)
Definition at line 305 of file psquery.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS_QUOTA_ENTRY::Limit, _POOLED_USAGE_AND_LIMITS::NonPagedPoolLimit, _POOLED_USAGE_AND_LIMITS::NonPagedPoolUsage, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _POOLED_USAGE_AND_LIMITS::PagedPoolLimit, _POOLED_USAGE_AND_LIMITS::PagedPoolUsage, _POOLED_USAGE_AND_LIMITS::PagefileLimit, _POOLED_USAGE_AND_LIMITS::PagefileUsage, _EPROCESS_QUOTA_ENTRY::Peak, _POOLED_USAGE_AND_LIMITS::PeakNonPagedPoolUsage, _POOLED_USAGE_AND_LIMITS::PeakPagedPoolUsage, _POOLED_USAGE_AND_LIMITS::PeakPagefileUsage, PROCESS_QUERY_INFORMATION, PSMAX, PsNonPagedPool, PsPagedPool, PsPageFile, PsProcessType, _EPROCESS::QuotaBlock, _EPROCESS_QUOTA_BLOCK::QuotaEntry, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, UNREFERENCED_PARAMETER, and _EPROCESS_QUOTA_ENTRY::Usage.
Referenced by NtQueryInformationProcess().
NTSTATUS PspQueryQuotaLimits (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, OUT PVOID ProcessInformation, IN ULONG ProcessInformationLength, OUT PULONG ReturnLength OPTIONAL, IN KPROCESSOR_MODE PreviousMode)
Definition at line 207 of file psquery.c.
References ARGUMENT_PRESENT, ASSERT, except, EXCEPTION_EXECUTE_HANDLER, _QUOTA_LIMITS_EX::Flags, _LARGE_INTEGER::HighPart, KeStackAttachProcess(), KeUnstackDetachProcess(), _EPROCESS_QUOTA_ENTRY::Limit, _LARGE_INTEGER::LowPart, _QUOTA_LIMITS_EX::MaximumWorkingSetSize, _QUOTA_LIMITS_EX::MinimumWorkingSetSize, MmQueryWorkingSetInformation(), _QUOTA_LIMITS_EX::NonPagedPoolLimit, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _QUOTA_LIMITS_EX::PagedPoolLimit, _QUOTA_LIMITS_EX::PagefileLimit, _EPROCESS::Pcb, PROCESS_QUERY_INFORMATION, PsNonPagedPool, PsPagedPool, PsPageFile, PspDefaultQuotaBlock, PsProcessType, QUOTA_LIMITS_HARDWS_MAX_DISABLE, QUOTA_LIMITS_HARDWS_MAX_ENABLE, QUOTA_LIMITS_HARDWS_MIN_DISABLE, QUOTA_LIMITS_HARDWS_MIN_ENABLE, _EPROCESS::QuotaBlock, _EPROCESS_QUOTA_BLOCK::QuotaEntry, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, _QUOTA_LIMITS_EX::TimeLimit, and UNREFERENCED_PARAMETER.
Referenced by NtQueryInformationProcess().
NTSTATUS PspQueryWorkingSetWatch (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, OUT PVOID ProcessInformation, IN ULONG ProcessInformationLength, OUT PULONG ReturnLength OPTIONAL, IN KPROCESSOR_MODE PreviousMode)
Definition at line 109 of file psquery.c.
References ARGUMENT_PRESENT, _PAGEFAULT_HISTORY::CurrentIndex, ExAcquireSpinLock, except, EXCEPTION_EXECUTE_HANDLER, ExPageLockHandle, ExReleaseSpinLock, _PROCESS_WS_WATCH_INFORMATION::FaultingPc, _PROCESS_WS_WATCH_INFORMATION::FaultingVa, MAX_WS_CATCH_INDEX, _PAGEFAULT_HISTORY::MaxIndex, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PROCESS_QUERY_INFORMATION, PsProcessType, RtlCopyMemory, _PAGEFAULT_HISTORY::SpinLock, STATUS_BUFFER_TOO_SMALL, STATUS_NO_MORE_ENTRIES, STATUS_UNSUCCESSFUL, UNREFERENCED_PARAMETER, _PAGEFAULT_HISTORY::WatchInfo, and _EPROCESS::WorkingSetWatch.
Referenced by NtQueryInformationProcess().
NTSTATUS PspSetPrimaryToken (IN HANDLE ProcessHandle OPTIONAL, IN PEPROCESS ProcessPointer OPTIONAL, IN HANDLE TokenHandle OPTIONAL, IN PACCESS_TOKEN TokenPointer OPTIONAL, IN BOOLEAN PrivilegeChecked)
Definition at line 389 of file psquery.c.
References _SECURITY_SUBJECT_CONTEXT::ClientToken, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, _EPROCESS::GrantedAccess, KeGetPreviousMode, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceDeviceMap(), ObDereferenceObject(), ObGetObjectSecurity(), ObIsLUIDDeviceMapsEnabled(), ObReferenceObjectByHandle, ObReleaseObjectSecurity(), _SECURITY_SUBJECT_CONTEXT::PrimaryToken, PROCESS_CREATE_PROCESS, PROCESS_CREATE_THREAD, PROCESS_DUP_HANDLE, PROCESS_QUERY_INFORMATION, PROCESS_SET_INFORMATION, PROCESS_SET_QUOTA, PROCESS_TERMINATE, PROCESS_VM_OPERATION, PROCESS_VM_READ, PROCESS_VM_WRITE, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, PsDereferencePrimaryTokenEx, PspAssignPrimaryToken(), PsProcessType, PsReferencePrimaryToken(), SeAccessCheck(), SeAssignPrimaryTokenPrivilege, SeCheckPrivilegedObject(), SeIsChildTokenByPointer(), SeIsSiblingTokenByPointer(), SeTokenObjectType, STANDARD_RIGHTS_ALL, Status, STATUS_PRIVILEGE_NOT_HELD, TOKEN_ASSIGN_PRIMARY, and _OBJECT_TYPE::TypeInfo.
Referenced by NtAssignProcessToJobObject(), and NtSetInformationProcess().
NTSTATUS PspSetQuotaLimits (IN HANDLE ProcessHandle, IN PROCESSINFOCLASS ProcessInformationClass, IN PVOID ProcessInformation, IN ULONG ProcessInformationLength, IN KPROCESSOR_MODE PreviousMode)
Definition at line 1699 of file psquery.c.
References ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExReleaseResourceLite(), FALSE, _QUOTA_LIMITS_EX::Flags, IgnoreError, InterlockedCompareExchangePointer, _EPROCESS::Job, JOB_OBJECT_LIMIT_WORKINGSET, _EJOB::JobLock, KeEnterGuardedRegionThread(), KeLeaveGuardedRegionThread(), KeStackAttachProcess(), KeUnstackDetachProcess(), _EPROCESS_QUOTA_ENTRY::Limit, _EJOB::LimitFlags, _QUOTA_LIMITS_EX::MaximumWorkingSetSize, _EJOB::MaximumWorkingSetSize, _QUOTA_LIMITS_EX::MinimumWorkingSetSize, _EJOB::MinimumWorkingSetSize, MmAdjustWorkingSetSizeEx(), MmEnforceWorkingSetLimit(), NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _EPROCESS::Pcb, _EPROCESS_QUOTA_ENTRY::Peak, PROCESS_SET_QUOTA, _EPROCESS_QUOTA_BLOCK::ProcessCount, PS_TEST_ALL_BITS_SET, PsGetCurrentThread(), PsNonPagedPool, PsPagedPool, PsPageFile, PspDefaultNonPagedLimit, PspDefaultPagedLimit, PspDefaultPagefileLimit, PspDefaultQuotaBlock, PspInsertQuotaBlock(), PspLockWorkingSetChangeExclusiveUnsafe(), PsProcessType, PspSinglePrivCheck(), PspSinglePrivCheckAudit(), PspUnlockWorkingSetChangeExclusiveUnsafe(), QUOTA_LIMITS_HARDWS_MAX_DISABLE, QUOTA_LIMITS_HARDWS_MAX_ENABLE, QUOTA_LIMITS_HARDWS_MIN_DISABLE, QUOTA_LIMITS_HARDWS_MIN_ENABLE, _EPROCESS::QuotaBlock, _EPROCESS_QUOTA_BLOCK::QuotaEntry, _EPROCESS::QuotaPeak, _EPROCESS_QUOTA_BLOCK::ReferenceCount, _QUOTA_LIMITS_EX::Reserved1, _QUOTA_LIMITS_EX::Reserved2, _QUOTA_LIMITS_EX::Reserved3, _QUOTA_LIMITS_EX::Reserved4, _QUOTA_LIMITS_EX::Reserved5, RtlCopyMemory, RtlZeroMemory, SeIncreaseBasePriorityPrivilege, SeIncreaseQuotaPrivilege, SeSinglePrivilegeCheck(), STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and UNREFERENCED_PARAMETER.
Referenced by NtSetInformationProcess().
VOID PsSetProcessPriorityByClass (__inout PEPROCESS Process, __in PSPROCESSPRIORITYMODE PriorityMode)
Definition at line 4366 of file psquery.c.
References KeSetPriorityAndQuantumProcess(), PAGED_CODE, and PspComputeQuantumAndPriority().
Referenced by NtSetInformationProcess(), and PspApplyJobLimitsToProcess().
VOID PsWatchWorkingSet (IN NTSTATUS Status, IN PVOID PcValue, IN PVOID Va)
Definition at line 4222 of file psquery.c.
References _PAGEFAULT_HISTORY::CurrentIndex, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _PROCESS_WS_WATCH_INFORMATION::FaultingPc, _PROCESS_WS_WATCH_INFORMATION::FaultingVa, _PAGEFAULT_HISTORY::MaxIndex, NULL, PsGetCurrentProcess(), _PAGEFAULT_HISTORY::SpinLock, STATUS_PAGE_FAULT_DEMAND_ZERO, TRUE, _PAGEFAULT_HISTORY::WatchInfo, and _EPROCESS::WorkingSetWatch.
Variable Documentation
PEPROCESS ExpDefaultErrorPortProcess
Definition at line 63 of file harderr.c.
PKWIN32_POWEREVENT_CALLOUT PopEventCallout
PKWIN32_POWERSTATE_CALLOUT PopStateCallout
const KPRIORITY PspPriorityTable[PROCESS_PRIORITY_CLASS_ABOVE_NORMAL+1] = {8,4,8,13,24,6,10}
Definition at line 43 of file psquery.c.
Referenced by PspComputeQuantumAndPriority().
PKWIN32_JOB_CALLOUT PspW32JobCallout = NULL
Definition at line 4291 of file psquery.c.
Referenced by NtAssignProcessToJobObject(), NtSetInformationJobObject(), and PspJobDelete().
PKWIN32_PROCESS_CALLOUT PspW32ProcessCallout = NULL
Definition at line 4289 of file psquery.c.
Referenced by PsConvertToGuiThread(), and PspExitThread().
PKWIN32_THREAD_CALLOUT PspW32ThreadCallout = NULL
Definition at line 4290 of file psquery.c.
Referenced by PsConvertToGuiThread(), and PspExitThread().
BOOLEAN PsWatchEnabled = FALSE
Definition at line 36 of file psquery.c.
Referenced by NtSetInformationProcess().