Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmcontrl.c File Reference
cmcontrl.c File Reference
#include "cmp.h"
Functions
VOID CmGetSystemControlValues (__in PVOID SystemHiveBuffer, __inout PCM_SYSTEM_CONTROL_VECTOR ControlVector)
LANGID CmpConvertLangId (PWSTR LangIdString, ULONG LangIdStringLength)
HCELL_INDEX CmpWalkPath (PHHIVE SystemHive, HCELL_INDEX ParentCell, PWSTR Path)
Variables
CMHIVE CmControlHive
WCHAR CmDefaultLanguageId []
ULONG CmDefaultLanguageIdLength
ULONG CmDefaultLanguageIdType
WCHAR CmInstallUILanguageId []
ULONG CmInstallUILanguageIdLength
ULONG CmInstallUILanguageIdType
Function Documentation
VOID CmGetSystemControlValues (__in PVOID SystemHiveBuffer, __inout PCM_SYSTEM_CONTROL_VECTOR ControlVector)
Definition at line 57 of file cmcontrl.c.
References ASSERT, BAD_SYSTEM_CONFIG_INFO, BAD_SYSTEM_CONTROL_VALUES, CM_BUGCHECK, CM_KEY_VALUE_SMALL, CmDefaultLanguageId, CmDefaultLanguageIdLength, CmDefaultLanguageIdType, CmInstallUILanguageId, CmInstallUILanguageIdLength, CmInstallUILanguageIdType, CmpConvertLangId(), CmpFindControlSet(), CmpFindSubKeyByName(), CmpFindValueByName(), CmpGetValueData(), CmpInitHiveViewList(), CmpInitSecurityCache(), CmpIsHKeyValueSmall, CmpWalkPath(), _CM_KEY_VALUE::DataLength, ExFreePool(), FALSE, HCELL_NIL, HFILE_TYPE_PRIMARY, HINIT_FLAT, HIVE_VOLATILE, HvGetCell, HvInitializeHive(), HvReleaseCell, LANGIDFROMLCID, NT_SUCCESS, NULL, PsDefaultSystemLocaleId, PsDefaultThreadLocaleId, PsDefaultUILanguageId, PsInstallUILanguageId, REG_SZ, RtlCopyMemory, RtlInitUnicodeString(), RtlZeroMemory, TRUE, and _CM_KEY_VALUE::Type.
LANGID CmpConvertLangId (PWSTR LangIdString, ULONG LangIdStringLength)
Definition at line 371 of file cmcontrl.c.
Referenced by CmGetSystemControlValues().
HCELL_INDEX CmpWalkPath (PHHIVE SystemHive, HCELL_INDEX ParentCell, PWSTR Path)
Definition at line 306 of file cmcontrl.c.
References ASSERT, CmpFindSubKeyByName(), CmpGetNextName(), HCELL_NIL, HvGetCell, _UNICODE_STRING::Length, NULL, _HHIVE::ReleaseCellRoutine, RtlInitUnicodeString(), and TRUE.
Referenced by CmGetSystemControlValues().
Variable Documentation
CMHIVE CmControlHive
Definition at line 32 of file cmcontrl.c.
WCHAR CmDefaultLanguageId[]
Referenced by CmGetSystemControlValues().
ULONG CmDefaultLanguageIdLength
Referenced by CmGetSystemControlValues().
ULONG CmDefaultLanguageIdType
Referenced by CmGetSystemControlValues().
WCHAR CmInstallUILanguageId[]
Referenced by CmGetSystemControlValues().
ULONG CmInstallUILanguageIdLength
Referenced by CmGetSystemControlValues().
ULONG CmInstallUILanguageIdType
Referenced by CmGetSystemControlValues().