Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivebin.c File Reference
hivebin.c File Reference
#include "cmp.h"
Functions
PHBIN HvpAddBin (IN PHHIVE Hive, IN ULONG NewSize, IN HSTORAGE_TYPE Type)
BOOLEAN HvpCoalesceDiscardedBins (IN PHHIVE Hive, IN ULONG NeededSize, IN HSTORAGE_TYPE Type)
Function Documentation
PHBIN HvpAddBin (IN PHHIVE Hive, IN ULONG NewSize, IN HSTORAGE_TYPE Type)
Definition at line 38 of file hivebin.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_LISTENTRY, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_BIN_MAP, CML_HIVE, CmpCanGrowSystemHive(), CmpMapThisBin(), CmpUpdateSystemHiveHysteresis(), _HMAP_ENTRY::CmView, CONTAINING_RECORD, _HMAP_DIRECTORY::Directory, DPFLTR_CONFIG_ID, ExAllocatePoolWithTag, FALSE, _HBIN::FileOffset, _FREE_HBIN::FileOffset, _FREE_HBIN::Flags, _LIST_ENTRY::Flink, FREE_HBIN_DISCARDABLE, _CMHIVE::GrowOnlyMode, HBIN_BASE, HBIN_NIL, HBIN_SIGNATURE, HBIN_THRESHOLD, HBLOCK_SIZE, HCELL_BIG_ROUND, HCELL_TYPE_MASK, HFILE_TYPE_PRIMARY, HIVE_VOLATILE, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HMAP_INVIEW, HMAP_NEWALLOC, HSECTOR_SIZE, HTABLE_SLOTS, HvMarkDirty(), HvpAdjustHiveFreeDisplay(), HvpAllocateMap(), HvpCheckViewBoundary(), HvpCoalesceDiscardedBins(), HvpFreeMap(), HvpGetCellMap(), HvpGrowLog2(), InsertHeadList(), _UNICODE_STRING::Length, _FREE_HBIN::ListEntry, _HMAP_ENTRY::MemAlloc, NT_SUCCESS, NULL, PAGE_SIZE, PagedPool, PagedPoolCacheAligned, RemoveEntryList(), ROUND_UP, RtlCopyMemory, RtlInitializeBitMap(), RtlInitUnicodeString(), RtlNumberOfSetBits(), RtlZeroMemory, _HBIN::Signature, _HCELL::Size, _HBIN::Size, _FREE_HBIN::Size, _HBIN::Spare, Stable, TRUE, _HCELL::u, USE_OLD_CELL, VALIDATE_CELL_MAP, and Volatile.
BOOLEAN HvpCoalesceDiscardedBins (IN PHHIVE Hive, IN ULONG NeededSize, IN HSTORAGE_TYPE Type)
Definition at line 658 of file hivebin.c.
References ASSERT_HIVE_WRITER_LOCK_OWNED, BIN_MAP_ALLOCATION_TYPE, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CONTAINING_RECORD, FALSE, _FREE_HBIN::FileOffset, _FREE_HBIN::Flags, _LIST_ENTRY::Flink, FREE_HBIN_DISCARDABLE, HBLOCK_SIZE, HMAP_DISCARDABLE, HvpCheckViewBoundary(), HvpGetCellMap(), List, _FREE_HBIN::ListEntry, RemoveEntryList(), _FREE_HBIN::Size, TRUE, and VALIDATE_CELL_MAP.
Referenced by HvpAddBin().