Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcsend.c File Reference
lpcsend.c File Reference
#include "lpcp.h"
Functions
NTSTATUS LpcpRequestWaitReplyPort (IN PVOID PortAddress, IN PPORT_MESSAGE RequestMessage, OUT PPORT_MESSAGE ReplyMessage, IN KPROCESSOR_MODE AccessMode)
NTSTATUS LpcRequestPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage)
NTSTATUS LpcRequestWaitReplyPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
NTSTATUS LpcRequestWaitReplyPortEx (IN PVOID PortAddress, IN PPORT_MESSAGE RequestMessage, OUT PPORT_MESSAGE ReplyMessage)
NTSTATUS NtRequestPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage)
NTSTATUS NtRequestWaitReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
Function Documentation
NTSTATUS LpcpRequestWaitReplyPort (IN PVOID PortAddress, IN PPORT_MESSAGE RequestMessage, OUT PPORT_MESSAGE ReplyMessage, IN KPROCESSOR_MODE AccessMode)
Definition at line 1513 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_MESSAGE::Entry, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), InsertTailList(), IsListEmpty, KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _ETHREAD::KeyedEventInUse, LPC_CLIENT_DIED, LPC_DEBUG_EVENT, LPC_ERROR_EVENT, LPC_EXCEPTION, LPC_KERNELMODE_MESSAGE, LPC_PORT_CLOSED, LPC_RELEASE_WAIT_INCREMENT, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateCallbackId, LpcpGenerateMessageId, LpcpGetThreadMessage, LpcpMoveMessage(), LpcpReleaseLpcpLock, LpcpSetPortToThread, LpcpTrace, LpcpValidateClientPort(), _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_NAME_DELETED, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LPCP_PORT_QUEUE::ReceiveHead, RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_LPC_REPLY_LOST, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_THREAD_IS_TERMINATING, STATUS_UNSUCCESSFUL, STATUS_USER_APC, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, _PORT_MESSAGE::u2, _LPCP_PORT_OBJECT::WaitEvent, WrExecutive, and WrLpcReply.
Referenced by LpcRequestWaitReplyPort(), and LpcRequestWaitReplyPortEx().
NTSTATUS LpcRequestPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage)
Definition at line 1261 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_MESSAGE::Entry, FALSE, _LPCP_PORT_OBJECT::Flags, InsertTailList(), KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), LPC_CLIENT_DIED, LPC_DATAGRAM, LPC_KERNELMODE_MESSAGE, LPC_RELEASE_WAIT_INCREMENT, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateMessageId, LpcpMoveMessage(), LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyMessageId, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PsGetCurrentProcess(), PsGetCurrentThread(), _LPCP_PORT_QUEUE::ReceiveHead, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_SUCCESS, _ETHREAD::Tcb, _PORT_MESSAGE::u2, and _LPCP_PORT_OBJECT::WaitEvent.
Referenced by LpcpDeletePort(), PspExitThread(), and WmipCsrClientMessageServer().
NTSTATUS LpcRequestWaitReplyPort (__in PVOID PortAddress, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
Definition at line 2076 of file lpcsend.c.
References KernelMode, and LpcpRequestWaitReplyPort().
Referenced by IopSendMessageToTrackService().
NTSTATUS LpcRequestWaitReplyPortEx (IN PVOID PortAddress, IN PPORT_MESSAGE RequestMessage, OUT PPORT_MESSAGE ReplyMessage)
Definition at line 2091 of file lpcsend.c.
References KeGetPreviousMode, and LpcpRequestWaitReplyPort().
Referenced by DbgkpSendApiMessageLpc(), and ExpRaiseHardError().
NTSTATUS NtRequestPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage)
Definition at line 41 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LPCP_PORT_OBJECT::Flags, InsertTailList(), KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), LPC_DATAGRAM, LPC_KERNELMODE_MESSAGE, LPC_RELEASE_WAIT_INCREMENT, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateMessageId, LpcpMoveMessage(), LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyMessageId, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectSafe(), PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PROBE_ALIGNMENT, ProbeForReadSmallStructure, PsGetCurrentProcess(), PsGetCurrentThread(), _LPCP_PORT_QUEUE::ReceiveHead, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, _ETHREAD::Tcb, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, and _LPCP_PORT_OBJECT::WaitEvent.
Referenced by IopErrorLogThread().
NTSTATUS NtRequestWaitReplyPort (__in HANDLE PortHandle, __in PPORT_MESSAGE RequestMessage, __out PPORT_MESSAGE ReplyMessage)
Definition at line 430 of file lpcsend.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _PORT_DATA_INFORMATION::CountDataEntries, _PORT_DATA_INFORMATION::DataEntries, DbgBreakPoint(), _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), InsertTailList(), IsListEmpty, KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), LPC_KERNELMODE_MESSAGE, LPC_NO_IMPERSONATE, LPC_RELEASE_WAIT_INCREMENT, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_NO_IMPERSONATION, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeToPortZone(), LpcpGenerateCallbackId, LpcpGenerateMessageId, LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpSaveDataInfoMessage(), LpcpSetPortToThread, LpcpSetThreadAttributes, LpcpTrace, LpcpValidateClientPort(), _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_PORT_OBJECT::PortContext, _LPCP_MESSAGE::PortContext, PROBE_ALIGNMENT, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LPCP_PORT_QUEUE::ReceiveHead, RemoveEntryList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, Status, STATUS_INVALID_PARAMETER, STATUS_LPC_REPLY_LOST, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_THREAD_IS_TERMINATING, STATUS_USER_APC, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, _LPCP_PORT_OBJECT::WaitEvent, WrExecutive, and WrLpcReply.