Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/cache.h File Reference
cache.h File Reference
#include "perf.h"
Data Structures
struct _CACHE_MANAGER_CALLBACKS
struct _CACHE_UNINITIALIZE_EVENT
struct _CC_FILE_SIZES
struct _PUBLIC_BCB
Macros
#define CcCopyWriteWontFlush(FO, FOFF, LEN) ((LEN) <= 0X10000)
#define CcGetFileSizePointer(FO)
#define CcIsFileCached(FO)
#define CCPF_IS_PREFETCHER_ACTIVE() (CcPfNumActiveTraces)
#define CCPF_IS_PREFETCHER_ENABLED() (CcPfEnablePrefetcher)
#define CCPF_IS_PREFETCHING_FOR_BOOT() (CcPfPrefetchingForBoot)
#define CCPF_TYPE_IMAGE 0x00000001
#define CCPF_TYPE_ROM 0x00000002
#define CcReadAhead(FO, FOFF, LEN)
#define MAP_NO_READ (16)
#define MAP_WAIT (1)
#define PIN_CALLER_TRACKS_DIRTY_DATA (32)
#define PIN_EXCLUSIVE (2)
#define PIN_IF_BCB (8)
#define PIN_NO_READ (4)
#define PIN_WAIT (1)
#define VACB_MAPPING_GRANULARITY (0x40000)
#define VACB_OFFSET_SHIFT (18)
Typedefs
typedef struct _CACHE_MANAGER_CALLBACKS CACHE_MANAGER_CALLBACKS
typedef struct _CACHE_UNINITIALIZE_EVENT CACHE_UNINITIALIZE_EVENT
typedef struct _CC_FILE_SIZES CC_FILE_SIZES
typedef BOOLEAN(* PACQUIRE_FOR_LAZY_WRITE) (__in PVOID Context, __in BOOLEAN Wait)
typedef BOOLEAN(* PACQUIRE_FOR_READ_AHEAD) (__in PVOID Context, __in BOOLEAN Wait)
typedef struct _CACHE_MANAGER_CALLBACKS * PCACHE_MANAGER_CALLBACKS
typedef struct _CACHE_UNINITIALIZE_EVENT * PCACHE_UNINITIALIZE_EVENT
typedef struct _CC_FILE_SIZES * PCC_FILE_SIZES
typedef VOID(* PCC_POST_DEFERRED_WRITE) (IN PVOID Context1, IN PVOID Context2)
typedef VOID(* PDIRTY_PAGE_ROUTINE) (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in PLARGE_INTEGER OldestLsn, __in PLARGE_INTEGER NewestLsn, __in PVOID Context1, __in PVOID Context2)
typedef enum _PF_BOOT_PHASE_ID PF_BOOT_PHASE_ID
typedef VOID(* PFLUSH_TO_LSN) (__in PVOID LogHandle, __in LARGE_INTEGER Lsn)
typedef enum _PF_BOOT_PHASE_ID * PPF_BOOT_PHASE_ID
typedef struct _PUBLIC_BCB * PPUBLIC_BCB
typedef VOID(* PRELEASE_FROM_LAZY_WRITE) (__in PVOID Context)
typedef VOID(* PRELEASE_FROM_READ_AHEAD) (__in PVOID Context)
typedef struct _PUBLIC_BCB PUBLIC_BCB
Enumerations
enum _PF_BOOT_PHASE_ID {
PfKernelInitPhase = 0, PfBootDriverInitPhase = 90, PfSystemDriverInitPhase = 120, PfSessionManagerInitPhase = 150,
PfSMRegistryInitPhase = 180, PfVideoInitPhase = 210, PfPostVideoInitPhase = 240, PfBootAcceptedRegistryInitPhase = 270,
PfUserShellReadyPhase = 300, PfMaxBootPhaseId = 900
}
Functions
NTKERNELAPI BOOLEAN CcCanIWrite (__in PFILE_OBJECT FileObject, __in ULONG BytesToWrite, __in BOOLEAN Wait, __in UCHAR Retrying)
NTKERNELAPI BOOLEAN CcCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI BOOLEAN CcCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in_bcount(Length) PVOID Buffer)
NTKERNELAPI VOID CcDeferWrite (__in PFILE_OBJECT FileObject, __in PCC_POST_DEFERRED_WRITE PostRoutine, __in PVOID Context1, __in PVOID Context2, __in ULONG BytesToWrite, __in BOOLEAN Retrying)
NTKERNELAPI VOID CcFastCopyRead (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in ULONG PageCount, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI VOID CcFastCopyWrite (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in_bcount(Length) PVOID Buffer)
NTKERNELAPI VOID CcFlushCache (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __out_opt PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI LARGE_INTEGER CcGetDirtyPages (__in PVOID LogHandle, __in PDIRTY_PAGE_ROUTINE DirtyPageRoutine, __in PVOID Context1, __in PVOID Context2)
NTKERNELAPI PFILE_OBJECT CcGetFileObjectFromBcb (__in PVOID Bcb)
NTKERNELAPI PFILE_OBJECT CcGetFileObjectFromSectionPtrs (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
NTKERNELAPI LARGE_INTEGER CcGetFlushedValidData (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN BcbListHeld)
NTKERNELAPI LARGE_INTEGER CcGetLsnForFileObject (__in PFILE_OBJECT FileObject, __out_opt PLARGE_INTEGER OldestLsn)
LOGICAL CcHasInactiveViews (VOID)
NTKERNELAPI BOOLEAN CcInitializeCacheManager (VOID)
NTKERNELAPI VOID CcInitializeCacheMap (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes, __in BOOLEAN PinAccess, __in PCACHE_MANAGER_CALLBACKS Callbacks, __in PVOID LazyWriteContext)
NTKERNELAPI BOOLEAN CcIsThereDirtyData (__in PVPB Vpb)
NTKERNELAPI BOOLEAN CcMapData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID *Bcb, __deref_out_bcount(Length) PVOID *Buffer)
NTKERNELAPI VOID CcMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI VOID CcMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
NTKERNELAPI VOID CcMdlReadComplete2 (IN PFILE_OBJECT FileObject, IN PMDL MdlChain)
NTKERNELAPI VOID CcMdlWriteAbort (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
NTKERNELAPI VOID CcMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
NTKERNELAPI VOID CcMdlWriteComplete2 (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain)
VOID CcPerfFileRunDown (IN PPERFINFO_ENTRY_TABLE HashTable)
NTSTATUS CcPfBeginAppLaunch (PEPROCESS Process, PVOID Section)
NTSTATUS CcPfBeginBootPhase (PF_BOOT_PHASE_ID Phase)
NTSTATUS CcPfInitializePrefetcher (VOID)
VOID CcPfLogPageFault (IN PFILE_OBJECT FileObject, IN ULONGLONG FileOffset, IN ULONG Flags)
NTSTATUS CcPfProcessExitNotification (PEPROCESS Process)
NTSTATUS CcPfQueryPrefetcherInformation (IN SYSTEM_INFORMATION_CLASS SystemInformationClass, IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN KPROCESSOR_MODE PreviousMode, OUT PULONG Length)
NTSTATUS CcPfSetPrefetcherInformation (IN SYSTEM_INFORMATION_CLASS SystemInformationClass, IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN KPROCESSOR_MODE PreviousMode)
NTKERNELAPI BOOLEAN CcPinMappedData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __inout PVOID *Bcb)
NTKERNELAPI BOOLEAN CcPinRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID *Bcb, __deref_out_bcount(Length) PVOID *Buffer)
NTKERNELAPI VOID CcPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL *MdlChain, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI BOOLEAN CcPreparePinWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Zero, __in ULONG Flags, __out PVOID *Bcb, __deref_out_bcount(Length) PVOID *Buffer)
NTKERNELAPI BOOLEAN CcPurgeCacheSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN UninitializeCacheMaps)
NTKERNELAPI PVOID CcRemapBcb (__in PVOID Bcb)
NTKERNELAPI VOID CcRepinBcb (__in PVOID Bcb)
NTKERNELAPI VOID CcScheduleReadAhead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length)
NTKERNELAPI VOID CcSetAdditionalCacheAttributes (__in PFILE_OBJECT FileObject, __in BOOLEAN DisableReadAhead, __in BOOLEAN DisableWriteBehind)
NTKERNELAPI VOID CcSetBcbOwnerPointer (__in PVOID Bcb, __in PVOID OwnerPointer)
NTKERNELAPI VOID CcSetDirtyPageThreshold (__in PFILE_OBJECT FileObject, __in ULONG DirtyPageThreshold)
NTKERNELAPI VOID CcSetDirtyPinnedData (__in PVOID BcbVoid, __in_opt PLARGE_INTEGER Lsn)
NTKERNELAPI VOID CcSetFileSizes (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes)
NTKERNELAPI VOID CcSetLogHandleForFile (__in PFILE_OBJECT FileObject, __in PVOID LogHandle, __in PFLUSH_TO_LSN FlushToLsnRoutine)
NTKERNELAPI BOOLEAN CcSetPrivateWriteFile (PFILE_OBJECT FileObject)
NTKERNELAPI VOID CcSetReadAheadGranularity (__in PFILE_OBJECT FileObject, __in ULONG Granularity)
NTKERNELAPI BOOLEAN CcUninitializeCacheMap (__in PFILE_OBJECT FileObject, __in_opt PLARGE_INTEGER TruncateSize, __in_opt PCACHE_UNINITIALIZE_EVENT UninitializeEvent)
LOGICAL CcUnmapInactiveViews (IN ULONG NumberOfViewsToUnmap)
NTKERNELAPI VOID CcUnpinData (__in PVOID Bcb)
NTKERNELAPI VOID CcUnpinDataForThread (__in PVOID Bcb, __in ERESOURCE_THREAD ResourceThreadId)
NTKERNELAPI VOID CcUnpinRepinnedBcb (__in PVOID Bcb, __in BOOLEAN WriteThrough, __out PIO_STATUS_BLOCK IoStatus)
NTKERNELAPI NTSTATUS CcWaitForCurrentLazyWriterActivity (VOID)
VOID CcWaitForUninitializeCacheMap (IN PFILE_OBJECT FileObject)
NTKERNELAPI BOOLEAN CcZeroData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER StartOffset, __in PLARGE_INTEGER EndOffset, __in BOOLEAN Wait)
NTKERNELAPI VOID CcZeroEndOfLastPage (IN PFILE_OBJECT FileObject)
Variables
ULONG CcCopyReadNoWait
ULONG CcCopyReadNoWaitMiss
ULONG CcCopyReadWait
ULONG CcCopyReadWaitMiss
ULONG CcDataFlushes
ULONG CcDataPages
ULONG CcFastMdlReadNotPossible
ULONG CcFastMdlReadNoWait
ULONG CcFastMdlReadResourceMiss
ULONG CcFastMdlReadWait
ULONG CcFastReadNotPossible
ULONG CcFastReadNoWait
ULONG CcFastReadResourceMiss
ULONG CcFastReadWait
ULONG CcLazyWriteIos
ULONG CcLazyWritePages
ULONG CcLostDelayedWrites
ULONG CcMapDataNoWait
ULONG CcMapDataNoWaitMiss
ULONG CcMapDataWait
ULONG CcMapDataWaitMiss
ULONG CcMdlReadNoWait
ULONG CcMdlReadNoWaitMiss
ULONG CcMdlReadWait
ULONG CcMdlReadWaitMiss
PULONG CcMissCounter
LOGICAL CcPfEnablePrefetcher
LONG CcPfNumActiveTraces
LOGICAL CcPfPrefetchingForBoot
ULONG CcPinMappedDataCount
ULONG CcPinReadNoWait
ULONG CcPinReadNoWaitMiss
ULONG CcPinReadWait
ULONG CcPinReadWaitMiss
ULONG CcReadAheadIos
ULONG CcThrowAway
Macro Definition Documentation
#define CcCopyWriteWontFlush (FO, FOFF, LEN) ((LEN) <= 0X10000)
Definition at line 392 of file cache.h.
Referenced by FsRtlCopyWrite().
#define CcGetFileSizePointer (FO)
Value:
(\
    ((PLARGE_INTEGER)((FO)->SectionObjectPointer->SharedCacheMap) + 1) \
)
Definition at line 294 of file cache.h.
Referenced by FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
#define CcIsFileCached (FO)
Value:
(\
    ((FO)->SectionObjectPointer != NULL) &&                                          \
    (((PSECTION_OBJECT_POINTERS)(FO)->SectionObjectPointer)->SharedCacheMap != NULL) \
)
Definition at line 172 of file cache.h.
Referenced by IoAsynchronousPageWrite(), and IoSynchronousPageWrite().
#define CCPF_IS_PREFETCHER_ACTIVE () (CcPfNumActiveTraces)
Definition at line 799 of file cache.h.
Referenced by MiCompleteProtoPteFault(), MiDispatchFault(), MmCheckCachedPageState(), and PspExitProcess().
#define CCPF_IS_PREFETCHER_ENABLED () (CcPfEnablePrefetcher)
Definition at line 802 of file cache.h.
Referenced by PspUserThreadStartup().
#define CCPF_IS_PREFETCHING_FOR_BOOT () (CcPfPrefetchingForBoot)
Definition at line 805 of file cache.h.
#define CCPF_TYPE_IMAGE 0x00000001
Definition at line 846 of file cache.h.
Referenced by MiCompleteProtoPteFault().
#define CCPF_TYPE_ROM 0x00000002
Definition at line 847 of file cache.h.
Referenced by MiCompleteProtoPteFault(), MiDispatchFault(), MmCheckCachedPageState(), and MmCopyToCachedPage().
#define CcReadAhead (FO, FOFF, LEN)
Value:
{                       \
    if ((LEN) >= 256) {                                  \
        CcScheduleReadAhead((FO),(FOFF),(LEN));          \
    }                                                    \
}
Definition at line 556 of file cache.h.
#define MAP_NO_READ (16)
Definition at line 666 of file cache.h.
Referenced by CcMapData(), CmpMapCmView(), and CmpUnPinCmView().
#define MAP_WAIT (1)
Definition at line 658 of file cache.h.
Referenced by CcMapDataCommon(), CcMapDataForOverwrite(), CmpMapCmView(), and CmpUnPinCmView().
#define PIN_CALLER_TRACKS_DIRTY_DATA (32)
Definition at line 648 of file cache.h.
Referenced by CcPreparePinWrite().
#define PIN_EXCLUSIVE (2)
Definition at line 620 of file cache.h.
Referenced by CcPinFileData().
#define PIN_IF_BCB (8)
Definition at line 639 of file cache.h.
Referenced by CcPinFileData().
#define PIN_NO_READ (4)
Definition at line 630 of file cache.h.
Referenced by CcPinFileData().
#define PIN_WAIT (1)
Definition at line 612 of file cache.h.
Referenced by CcPinFileData(), CcPinMappedData(), CcPinRead(), and CmpFileWriteThroughCache().
#define VACB_MAPPING_GRANULARITY (0x40000)
Definition at line 31 of file cache.h.
Referenced by CcCopyRead(), CcCopyWrite(), CcCreateVacbArray(), CcFastCopyRead(), CcFastCopyWrite(), CcFreeActiveVacb(), CcGetVacbMiss(), CcGetVirtualAddress(), CcGetVirtualAddressIfMapped(), CcInitializeCacheMap(), CcPinFileData(), and CcUnmapVacbArray().
#define VACB_OFFSET_SHIFT (18)
Definition at line 32 of file cache.h.
Referenced by CcAdjustVacbLevelLockCount(), CcCopyRead(), CcCreateVacbArray(), CcExtendVacbArray(), CcFastCopyRead(), CcGetBcbListHeadLargeOffset(), CcGetVacbLargeOffset(), CcInitializeVacbs(), CcSetVacbLargeOffset(), and SetVacb().
Typedef Documentation
typedef struct _CACHE_MANAGER_CALLBACKS CACHE_MANAGER_CALLBACKS
typedef struct _CACHE_UNINITIALIZE_EVENT CACHE_UNINITIALIZE_EVENT
typedef struct _CC_FILE_SIZES CC_FILE_SIZES
typedef BOOLEAN(* PACQUIRE_FOR_LAZY_WRITE) (__in PVOID Context, __in BOOLEAN Wait)
Definition at line 91 of file cache.h.
typedef BOOLEAN(* PACQUIRE_FOR_READ_AHEAD) (__in PVOID Context, __in BOOLEAN Wait)
Definition at line 110 of file cache.h.
typedef struct _CACHE_MANAGER_CALLBACKS * PCACHE_MANAGER_CALLBACKS
typedef struct _CACHE_UNINITIALIZE_EVENT * PCACHE_UNINITIALIZE_EVENT
typedef struct _CC_FILE_SIZES * PCC_FILE_SIZES
typedef VOID(* PCC_POST_DEFERRED_WRITE) (IN PVOID Context1, IN PVOID Context2)
Definition at line 404 of file cache.h.
typedef VOID(* PDIRTY_PAGE_ROUTINE) (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in PLARGE_INTEGER OldestLsn, __in PLARGE_INTEGER NewestLsn, __in PVOID Context1, __in PVOID Context2)
Definition at line 148 of file cache.h.
typedef enum _PF_BOOT_PHASE_ID PF_BOOT_PHASE_ID
typedef VOID(* PFLUSH_TO_LSN) (__in PVOID LogHandle, __in LARGE_INTEGER Lsn)
Definition at line 163 of file cache.h.
typedef enum _PF_BOOT_PHASE_ID * PPF_BOOT_PHASE_ID
typedef struct _PUBLIC_BCB * PPUBLIC_BCB
typedef VOID(* PRELEASE_FROM_LAZY_WRITE) (__in PVOID Context)
Definition at line 101 of file cache.h.
typedef VOID(* PRELEASE_FROM_READ_AHEAD) (__in PVOID Context)
Definition at line 120 of file cache.h.
typedef struct _PUBLIC_BCB PUBLIC_BCB
Enumeration Type Documentation
enum _PF_BOOT_PHASE_ID
Enumerator
PfKernelInitPhase
PfBootDriverInitPhase
PfSystemDriverInitPhase
PfSessionManagerInitPhase
PfSMRegistryInitPhase
PfVideoInitPhase
PfPostVideoInitPhase
PfBootAcceptedRegistryInitPhase
PfUserShellReadyPhase
PfMaxBootPhaseId
Definition at line 817 of file cache.h.
Function Documentation
NTKERNELAPI BOOLEAN CcCanIWrite (__in PFILE_OBJECT FileObject, __in ULONG BytesToWrite, __in BOOLEAN Wait, __in UCHAR Retrying)
Definition at line 1710 of file copysup.c.
References BooleanFlagOn, _DEFERRED_WRITE::BytesToWrite, CACHE_NTC_DEFERRED_WRITE, CcAcquireMasterLock, CcDeferredWrites, CcDeferredWriteSpinLock, CcDirtyPageThreshold, CcIdleDelay, CcPostDeferredWrites(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcTotalDirtyPages, _DEFERRED_WRITE::DeferredWriteLinks, _SHARED_CACHE_MAP::DirtyPages, _SHARED_CACHE_MAP::DirtyPageThreshold, _DEFERRED_WRITE::Event, Executive, ExInterlockedInsertHeadList(), ExInterlockedInsertTailList(), FALSE, _DEFERRED_WRITE::FileObject, FlagOn, FO_WRITE_THROUGH, FSRTL_FLAG_LIMIT_MODIFIED_PAGES, IoIsFileOriginRemote(), IsListEmpty, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), _DEFERRED_WRITE::LimitModifiedPages, MAXUCHAR, MmEnoughMemoryForWrite, _DEFERRED_WRITE::NodeByteSize, _DEFERRED_WRITE::NodeTypeCode, NotificationEvent, NULL, PAGE_SIZE, _SECTION_OBJECT_POINTERS::SharedCacheMap, STATUS_SUCCESS, TRUE, and WRITE_CHARGE_THRESHOLD.
Referenced by CcForceWriteThrough(), CcLazyWriteScan(), CcPostDeferredWrites(), FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
NTKERNELAPI BOOLEAN CcCopyRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 34 of file copysup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _VACB::BaseAddress, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_SET_PRIVATE_CACHE_MAP, CcCopyReadExceptionFilter(), CcCopyReadNoWait, CcCopyReadNoWaitMiss, CcCopyReadWait, CcCopyReadWaitMiss, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMissCounter, CcPinFileData(), CcScheduleReadAhead(), CcThrowAway, CcUnpinFileData, DebugTrace, except, ExRaiseStatus(), FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, _SHARED_CACHE_MAP::FileSize, FlagOn, _PRIVATE_CACHE_MAP::Flags, FO_RANDOM_ACCESS, FsRtlNormalizeNtstatus(), GetActiveVacb, HOT_STATISTIC, _LARGE_INTEGER::LowPart, me, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, _SHARED_CACHE_MAP::NeedToZero, NULL, PAGE_SHIFT, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _PRIVATE_CACHE_MAP_FLAGS::ReadAheadEnabled, _PRIVATE_CACHE_MAP::ReadAheadLength, ROUND_TO_PAGES, RtlCopyBytes, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, TRUE, UNPIN, VACB_MAPPING_GRANULARITY, and VACB_OFFSET_SHIFT.
Referenced by FsRtlCopyRead().
NTKERNELAPI BOOLEAN CcCopyWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Wait, __in_bcount(Length) PVOID Buffer)
Definition at line 1081 of file copysup.c.
References ACTIVE_PAGE_IS_DIRTY, _SHARED_CACHE_MAP::ActiveVacbSpinLock, _VACB::BaseAddress, CcCopyReadExceptionFilter(), CcFreeActiveVacb(), CcMapAndCopy(), DebugTrace, ExAcquireFastLock, ExAcquireFastMutex(), except, ExRaiseStatus(), ExReleaseFastLock, ExReleaseFastMutex(), FALSE, _FSRTL_ADVANCED_FCB_HEADER::FastMutex, FileOffset, FlagOn, FO_WRITE_THROUGH, FSRTL_FLAG_ADVANCED_HEADER, FsRtlNormalizeNtstatus(), GetActiveVacb, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, me, _SHARED_CACHE_MAP::NeedToZero, _SHARED_CACHE_MAP::NeedToZeroVacb, NULL, OPTIMIZE_FIRST_PAGE, OPTIMIZE_LAST_PAGE, OPTIMIZE_MIDDLE_PAGES, PAGE_SHIFT, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlCopyBytes, RtlZeroBytes, RtlZeroMemory, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_UNEXPECTED_IO_ERROR, TRUE, and VACB_MAPPING_GRANULARITY.
Referenced by FsRtlCopyWrite().
NTKERNELAPI VOID CcDeferWrite (__in PFILE_OBJECT FileObject, __in PCC_POST_DEFERRED_WRITE PostRoutine, __in PVOID Context1, __in PVOID Context2, __in ULONG BytesToWrite, __in BOOLEAN Retrying)
Definition at line 1922 of file copysup.c.
References BooleanFlagOn, _DEFERRED_WRITE::BytesToWrite, CACHE_NTC_DEFERRED_WRITE, CcAcquireMasterLock, CcDeferredWrites, CcDeferredWriteSpinLock, CcPostDeferredWrites(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), _DEFERRED_WRITE::Context1, _DEFERRED_WRITE::Context2, _DEFERRED_WRITE::DeferredWriteLinks, _DEFERRED_WRITE::Event, ExAllocatePoolWithTag, ExInterlockedInsertHeadList(), ExInterlockedInsertTailList(), FALSE, _DEFERRED_WRITE::FileObject, FSRTL_FLAG_LIMIT_MODIFIED_PAGES, LazyWriter, _DEFERRED_WRITE::LimitModifiedPages, _DEFERRED_WRITE::NodeByteSize, _DEFERRED_WRITE::NodeTypeCode, NonPagedPool, NULL, _DEFERRED_WRITE::PostRoutine, and _LAZY_WRITER::ScanActive.
NTKERNELAPI VOID CcFastCopyRead (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in ULONG PageCount, __out_bcount(Length) PVOID Buffer, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 593 of file copysup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _VACB::BaseAddress, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_SET_PRIVATE_CACHE_MAP, CcCopyReadExceptionFilter(), CcCopyReadWait, CcCopyReadWaitMiss, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMissCounter, CcScheduleReadAhead(), CcThrowAway, DebugTrace, except, ExRaiseStatus(), FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, _SHARED_CACHE_MAP::FileSize, FlagOn, _PRIVATE_CACHE_MAP::Flags, FO_RANDOM_ACCESS, FsRtlNormalizeNtstatus(), GetActiveVacb, _LARGE_INTEGER::HighPart, HOT_STATISTIC, _LARGE_INTEGER::LowPart, me, MmCheckCachedPageState(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, _SHARED_CACHE_MAP::NeedToZero, NULL, PAGE_SHIFT, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _PRIVATE_CACHE_MAP_FLAGS::ReadAheadEnabled, _PRIVATE_CACHE_MAP::ReadAheadLength, ROUND_TO_PAGES, RtlCopyBytes, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, UNREFERENCED_PARAMETER, VACB_MAPPING_GRANULARITY, and VACB_OFFSET_SHIFT.
Referenced by FsRtlCopyRead().
NTKERNELAPI VOID CcFastCopyWrite (__in PFILE_OBJECT FileObject, __in ULONG FileOffset, __in ULONG Length, __in_bcount(Length) PVOID Buffer)
Definition at line 1399 of file copysup.c.
References ACTIVE_PAGE_IS_DIRTY, _SHARED_CACHE_MAP::ActiveVacbSpinLock, ASSERT, _VACB::BaseAddress, CcCopyReadExceptionFilter(), CcFreeActiveVacb(), CcMapAndCopy(), DebugTrace, ExAcquireFastLock, except, ExRaiseStatus(), ExReleaseFastLock, FALSE, FileOffset, FlagOn, FO_WRITE_THROUGH, FsRtlNormalizeNtstatus(), GetActiveVacb, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, MAXULONG, me, _SHARED_CACHE_MAP::NeedToZero, _SHARED_CACHE_MAP::NeedToZeroVacb, NULL, OPTIMIZE_FIRST_PAGE, OPTIMIZE_LAST_PAGE, OPTIMIZE_MIDDLE_PAGES, PAGE_SHIFT, PAGE_SIZE, RtlCopyBytes, RtlZeroBytes, RtlZeroMemory, SetActiveVacb, Status, STATUS_ACCESS_VIOLATION, STATUS_INVALID_USER_BUFFER, STATUS_UNEXPECTED_IO_ERROR, TRUE, and VACB_MAPPING_GRANULARITY.
Referenced by FsRtlCopyWrite().
NTKERNELAPI VOID CcFlushCache (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __out_opt PIO_STATUS_BLOCK IoStatus)
Definition at line 4453 of file cachesub.c.
References _SHARED_CACHE_MAP::ActivePage, _SHARED_CACHE_MAP::ActiveVacb, ARGUMENT_PRESENT, ASSERT, CALLER_TRACKS_DIRTY_DATA, CC_REQUEUE, CcAcquireByteRangeForWrite(), CcAcquireMasterLock, CcDecrementOpenCount, CcDeferredWrites, CcDirtySharedCacheMapList, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddressIfMapped(), CcIdleDelayTick, CcIncrementOpenCount, CcLazyWriteHotSpots, CcLazyWriteIos, CcLazyWritePages, CcNoDelay, CcPostDeferredWrites(), CcReleaseByteRangeFromWrite(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), ClearFlag, DebugTrace, DebugTrace2, _FILE_OBJECT::DeviceObject, _SHARED_CACHE_MAP::DirtyPages, FALSE, FILE_DEVICE_CD_ROM, _SHARED_CACHE_MAP::FileObject, FileOffset, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, _FILE_OBJECT::FsContext, FSRTL_FLAG_USER_MAPPED_FILE, GetActiveVacbAtDpcLevel, _LARGE_INTEGER::HighPart, InsertTailList(), IsListEmpty, KeQueryTickCount(), LAZY_WRITE_OCCURRED, _SHARED_CACHE_MAP::LazyWritePassCount, LazyWriter, _LARGE_INTEGER::LowPart, MAXULONG, me, mm, MM_FLUSH_ACQUIRE_FILE, MM_FLUSH_FAIL_COLLISIONS, MmFlushSection(), MmSetAddressRangeModified(), MODIFIED_WRITE_DISABLED, _SHARED_CACHE_MAP::NeedToZero, _SHARED_CACHE_MAP::NeedToZeroPage, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SHIFT, PAGE_SIZE, _SHARED_CACHE_MAP::PagesToWrite, PIN_ACCESS, PRIVATE_WRITE, _LARGE_INTEGER::QuadPart, RemoveEntryList(), RetryError, _LAZY_WRITER::ScanActive, _FILE_OBJECT::SectionObjectPointer, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, Status, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, STATUS_VERIFY_REQUIRED, TRUE, _SHARED_CACHE_MAP::ValidDataGoal, _SHARED_CACHE_MAP::ValidDataLength, WAITING_FOR_TEARDOWN, and WRITE_QUEUED.
Referenced by CcSetPrivateWriteFile(), CcWriteBehind(), CcZeroEndOfLastPage(), CmpDestroyHiveViewList(), CmpDoFileSetSize(), CmpFileFlush(), CmpFileWriteThroughCache(), CmpUnPinCmView(), and MiFlushDataSection().
NTKERNELAPI LARGE_INTEGER CcGetDirtyPages (__in PVOID LogHandle, __in PDIRTY_PAGE_ROUTINE DirtyPageRoutine, __in PVOID Context1, __in PVOID Context2)
Definition at line 292 of file logsup.c.
References _BCB::BcbLinks, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, _BCB::ByteLength, CACHE_NTC_BCB, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcIncrementOpenCount, CcReleaseMasterLock, CcUnpinFileData, CONTAINING_RECORD, _BCB::Dirty, _SHARED_CACHE_MAP::DirtyPages, _SHARED_CACHE_MAP::FileObject, _BCB::FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, IS_CURSOR, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _SHARED_CACHE_MAP::LogHandle, _BCB::NewestLsn, _BCB::NodeTypeCode, NULL, _BCB::OldestLsn, _KLOCK_QUEUE_HANDLE::OldIrql, _BCB::PinCount, _LARGE_INTEGER::QuadPart, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, UNPIN, and UNREF.
NTKERNELAPI PFILE_OBJECT CcGetFileObjectFromBcb (__in PVOID Bcb)
Definition at line 3974 of file fssup.c.
NTKERNELAPI PFILE_OBJECT CcGetFileObjectFromSectionPtrs (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
Definition at line 3923 of file fssup.c.
References CcAcquireMasterLock, CcReleaseMasterLock, and NULL.
NTKERNELAPI LARGE_INTEGER CcGetFlushedValidData (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN BcbListHeld)
Definition at line 4277 of file cachesub.c.
References ASSERT, _BITMAP_RANGE::BasePage, _BCB::BcbLinks, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_BCB, CcAcquireMasterLock, CcAcquireMasterLockAtDpcLevel, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFindBitmapRangeToClean(), CcIncrementOpenCount, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CONTAINING_RECORD, _BCB::Dirty, _SHARED_CACHE_MAP::DirtyPages, _MBCB::DirtyPages, FALSE, _BCB::FileOffset, _BITMAP_RANGE::FirstDirtyPage, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLockFromDpcLevel(), LazyWriter, MAXULONG, _SHARED_CACHE_MAP::Mbcb, _BCB::NodeTypeCode, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, _SHARED_CACHE_MAP::ValidDataGoal, and WRITE_QUEUED.
Referenced by CcWriteBehind().
NTKERNELAPI LARGE_INTEGER CcGetLsnForFileObject (__in PFILE_OBJECT FileObject, __out_opt PLARGE_INTEGER OldestLsn)
Definition at line 605 of file logsup.c.
References ARGUMENT_PRESENT, _BCB::BcbLinks, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_BCB, CONTAINING_RECORD, _BCB::Dirty, _LIST_ENTRY::Flink, _LARGE_INTEGER::HighPart, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _LARGE_INTEGER::LowPart, _BCB::NewestLsn, _BCB::NodeTypeCode, NULL, _BCB::OldestLsn, and _LARGE_INTEGER::QuadPart.
LOGICAL CcHasInactiveViews (VOID)
Definition at line 6789 of file cachesub.c.
References FALSE.
Referenced by MiTrimSegmentCache().
NTKERNELAPI BOOLEAN CcInitializeCacheManager (VOID)
NTKERNELAPI VOID CcInitializeCacheMap (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes, __in BOOLEAN PinAccess, __in PCACHE_MANAGER_CALLBACKS Callbacks, __in PVOID LazyWriteContext)
Definition at line 323 of file fssup.c.
References _SHARED_CACHE_MAP::ActiveVacbSpinLock, _CC_FILE_SIZES::AllocationSize, ASSERT, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, BEING_CREATED, CACHE_NTC_PRIVATE_CACHE_MAP, CACHE_NTC_SHARED_CACHE_MAP, _SHARED_CACHE_MAP::Callbacks, CcAcquireMasterLock, CcCleanSharedCacheMapList, CcCreateVacbArray(), CcDecrementOpenCount, CcDeleteSharedCacheMap(), CcExtendVacbArray(), CcIncrementOpenCount, CcInsertIntoCleanSharedCacheMapList(), CcReleaseMasterLock, ClearFlag, ClearMmWaiterFlag, _SHARED_CACHE_MAP::CreateEvent, DebugTrace, DebugTrace2, DEFAULT_CREATE_MODULO, _SHARED_CACHE_MAP::DirtyPages, _CACHE_UNINITIALIZE_EVENT::Event, ExAllocatePoolWithTag, Executive, ExFreePool(), ExInitializePushLock(), ExRaiseStatus(), FALSE, _PRIVATE_CACHE_MAP::FileObject, _SHARED_CACHE_MAP::FileObject, _CC_FILE_SIZES::FileSize, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FO_RANDOM_ACCESS, FO_SEQUENTIAL_ONLY, FSRTL_FLAG2_DO_MODIFIED_WRITE, FsRtlNormalizeNtstatus(), _LARGE_INTEGER::HighPart, InitializeListHead(), InsertTailList(), KeInitializeEvent(), KeInitializeSpinLock(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _SHARED_CACHE_MAP::LazyWriteContext, _LARGE_INTEGER::LowPart, me, mm, MmCreateSection(), MmDisableModifiedWriteOfSection(), MmExtendSection(), MODIFIED_WRITE_DISABLED, _CACHE_UNINITIALIZE_EVENT::Next, _SHARED_CACHE_MAP::NodeByteSize, _PRIVATE_CACHE_MAP::NodeTypeCode, _SHARED_CACHE_MAP::NodeTypeCode, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, ObDeleteCapturedInsertInfo(), ObReferenceObject, ONLY_SEQUENTIAL_ONLY_SEEN, _SHARED_CACHE_MAP::OpenCount, PAGE_READWRITE, PAGE_SIZE, PIN_ACCESS, _SHARED_CACHE_MAP::PrivateCacheMap, _PRIVATE_CACHE_MAP::PrivateLinks, _SHARED_CACHE_MAP::PrivateList, _LARGE_INTEGER::QuadPart, RANDOM_ACCESS_SEEN, _PRIVATE_CACHE_MAP::ReadAheadMask, _PRIVATE_CACHE_MAP::ReadAheadSpinLock, RemoveEntryList(), RtlZeroMemory, SEC_COMMIT, _SHARED_CACHE_MAP::Section, SECTION_MAP_READ, SECTION_MAP_WRITE, SECTION_QUERY, _SHARED_CACHE_MAP::SectionSize, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, Status, _SHARED_CACHE_MAP::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_UNEXPECTED_MM_CREATE_ERR, STATUS_UNEXPECTED_MM_EXTEND_ERR, TRUE, TRUNCATE_REQUIRED, _SHARED_CACHE_MAP::UninitializeEvent, VACB_MAPPING_GRANULARITY, _SHARED_CACHE_MAP::VacbPushLock, _SHARED_CACHE_MAP::Vacbs, _SHARED_CACHE_MAP::ValidDataGoal, _CC_FILE_SIZES::ValidDataLength, _SHARED_CACHE_MAP::ValidDataLength, WAITING_FOR_TEARDOWN, and WRITE_QUEUED.
NTKERNELAPI BOOLEAN CcIsThereDirtyData (__in PVPB Vpb)
Definition at line 517 of file logsup.c.
References CcAcquireMasterLock, CcDirtySharedCacheMapList, CcReleaseMasterLock, ClearFlag, CONTAINING_RECORD, _SHARED_CACHE_MAP::DirtyPages, FALSE, _SHARED_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, _FILE_OBJECT::Flags, _LIST_ENTRY::Flink, FO_TEMPORARY_FILE, IS_CURSOR, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, _FILE_OBJECT::Vpb, and WRITE_QUEUED.
NTKERNELAPI BOOLEAN CcMapData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID * Bcb, __deref_out_bcount(Length) PVOID * Buffer)
Definition at line 73 of file pinsup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, CcMapDataCommon(), CcMissCounter, CcThrowAway, CcUnpinFileData, DebugTrace, FALSE, FlagOn, MAP_NO_READ, me, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, NULL, PAGE_SIZE, PsGetCurrentThread(), TRUE, ULongToPtr, and UNPIN.
Referenced by CmpMapCmView(), and CmpUnPinCmView().
NTKERNELAPI VOID CcMdlRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 36 of file mdlsup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_SET_PRIVATE_CACHE_MAP, CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcMdlReadWait, CcMdlReadWaitMiss, CcMissCounter, CcScheduleReadAhead(), CcThrowAway, CONTAINING_RECORD, DebugTrace, DebugTrace2, ExRaiseStatus(), FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, _SHARED_CACHE_MAP::FileSize, FlagOn, _PRIVATE_CACHE_MAP::Flags, FO_RANDOM_ACCESS, GetActiveVacb, IoAllocateMdl(), IoFreeMdl(), IoReadAccess, KernelMode, me, mm, MmProbeAndLockPages(), MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmUnlockPages(), _SHARED_CACHE_MAP::NeedToZero, _MDL::Next, NULL, PRIVATE_CACHE_MAP_READ_AHEAD_ENABLED, PsGetCurrentThread(), _LARGE_INTEGER::QuadPart, _PRIVATE_CACHE_MAP_FLAGS::ReadAheadEnabled, _PRIVATE_CACHE_MAP::ReadAheadLength, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by FsRtlMdlReadDev().
NTKERNELAPI VOID CcMdlReadComplete (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
Definition at line 386 of file mdlsup.c.
References CcMdlReadComplete2(), FIELD_OFFSET, IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlReadComplete, NOTHING, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
NTKERNELAPI VOID CcMdlReadComplete2 (IN PFILE_OBJECT FileObject, IN PMDL MdlChain)
Definition at line 411 of file mdlsup.c.
References DebugTrace, IoFreeMdl(), me, mm, MmUnlockPages(), _MDL::Next, NULL, and UNREFERENCED_PARAMETER.
Referenced by CcMdlReadComplete(), and FsRtlMdlReadCompleteDev().
NTKERNELAPI VOID CcMdlWriteAbort (__in PFILE_OBJECT FileObject, __in PMDL MdlChain)
Definition at line 1048 of file mdlsup.c.
References CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcReleaseMasterLock, CcScheduleLazyWriteScan(), DebugTrace, _SHARED_CACHE_MAP::DirtyPages, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, InsertTailList(), IoFreeMdl(), LazyWriter, MDL_PAGES_LOCKED, me, mm, MmUnlockPages(), _MDL::Next, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, and WRITE_QUEUED.
NTKERNELAPI VOID CcMdlWriteComplete (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in PMDL MdlChain)
Definition at line 825 of file mdlsup.c.
References CcMdlWriteComplete2(), FIELD_OFFSET, IoGetRelatedDeviceObject(), _FAST_IO_DISPATCH::MdlWriteComplete, NOTHING, NULL, and _FAST_IO_DISPATCH::SizeOfFastIoDispatch.
NTKERNELAPI VOID CcMdlWriteComplete2 (IN PFILE_OBJECT FileObject, IN PLARGE_INTEGER FileOffset, IN PMDL MdlChain)
Definition at line 851 of file mdlsup.c.
References ASSERT, _MDL::ByteCount, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcSetDirtyInMask(), DebugTrace, _SHARED_CACHE_MAP::DirtyPages, ExRaiseStatus(), FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, FO_WRITE_THROUGH, FsRtlNormalizeNtstatus(), InsertTailList(), IoFreeMdl(), LazyWriter, MDL_PAGES_LOCKED, me, mm, MM_FLUSH_ACQUIRE_FILE, MmFlushSection(), MmUnlockPages(), _MDL::Next, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, STATUS_UNEXPECTED_IO_ERROR, TRUE, UNALIGNED, and WRITE_QUEUED.
Referenced by CcMdlWriteComplete(), and FsRtlMdlWriteCompleteDev().
VOID CcPerfFileRunDown (IN PPERFINFO_ENTRY_TABLE HashTable)
NTSTATUS CcPfBeginAppLaunch (PEPROCESS Process, PVOID Section)
Referenced by PspUserThreadStartup().
NTSTATUS CcPfBeginBootPhase (PF_BOOT_PHASE_ID Phase)
Referenced by IoInitSystem(), and NtInitializeRegistry().
NTSTATUS CcPfInitializePrefetcher (VOID)
Referenced by Phase1InitializationDiscard().
VOID CcPfLogPageFault (IN PFILE_OBJECT FileObject, IN ULONGLONG FileOffset, IN ULONG Flags)
Referenced by MiCompleteProtoPteFault(), MiDispatchFault(), MmCheckCachedPageState(), and MmCopyToCachedPage().
NTSTATUS CcPfProcessExitNotification (PEPROCESS Process)
Referenced by PspExitProcess().
NTSTATUS CcPfQueryPrefetcherInformation (IN SYSTEM_INFORMATION_CLASS SystemInformationClass, IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN KPROCESSOR_MODE PreviousMode, OUT PULONG Length)
Referenced by NtQuerySystemInformation().
NTSTATUS CcPfSetPrefetcherInformation (IN SYSTEM_INFORMATION_CLASS SystemInformationClass, IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN KPROCESSOR_MODE PreviousMode)
Referenced by NtSetSystemInformation().
NTKERNELAPI BOOLEAN CcPinMappedData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __inout PVOID * Bcb)
Definition at line 408 of file pinsup.c.
References BooleanFlagOn, CACHE_NTC_BCB, CcAllocateObcb(), CcFreeVirtualAddress(), CcPinFileData(), CcPinMappedDataCount, CcUnpinData(), DebugTrace, ExAcquireSharedStarveExclusive(), FALSE, FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, me, MODIFIED_WRITE_DISABLED, NOTHING, NULL, PIN_WAIT, _LARGE_INTEGER::QuadPart, TRUE, and try_return.
Referenced by CmpPinCmView().
NTKERNELAPI BOOLEAN CcPinRead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in ULONG Flags, __out PVOID * Bcb, __deref_out_bcount(Length) PVOID * Buffer)
Definition at line 640 of file pinsup.c.
References CcAllocateObcb(), CcMissCounter, CcPinFileData(), CcPinReadNoWait, CcPinReadNoWaitMiss, CcPinReadWait, CcPinReadWaitMiss, CcThrowAway, CcUnpinData(), DebugTrace, FALSE, FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, me, MODIFIED_WRITE_DISABLED, NOTHING, NULL, PIN_WAIT, _LARGE_INTEGER::QuadPart, TRUE, and try_return.
Referenced by CmpFileWriteThroughCache().
NTKERNELAPI VOID CcPrepareMdlWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __out PMDL * MdlChain, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 473 of file mdlsup.c.
References _SHARED_CACHE_MAP::BcbSpinLock, CcAcquireMasterLock, CcForceWriteThrough(), CcFreeActiveVacb(), CcFreeVirtualAddress(), CcGetVirtualAddress(), CcIncrementOpenCount, CcMapAndRead(), CcReleaseMasterLock, CcSetDirtyInMask(), CONTAINING_RECORD, DebugTrace, DebugTrace2, ExRaiseStatus(), FALSE, FileOffset, FlagOn, FO_WRITE_THROUGH, GetActiveVacb, _LARGE_INTEGER::HighPart, IoAllocateMdl(), IoFreeMdl(), IoWriteAccess, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), KernelMode, _LARGE_INTEGER::LowPart, me, mm, MmDisablePageFaultClustering, MmEnablePageFaultClustering, MmProbeAndLockPages(), MmUnlockPages(), _SHARED_CACHE_MAP::NeedToZero, _MDL::Next, NULL, _KLOCK_QUEUE_HANDLE::OldIrql, PAGE_SIZE, _LARGE_INTEGER::QuadPart, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _SHARED_CACHE_MAP::ValidDataGoal, VOID, ZERO_FIRST_PAGE, ZERO_LAST_PAGE, and ZERO_MIDDLE_PAGES.
Referenced by FsRtlPrepareMdlWriteDev().
NTKERNELAPI BOOLEAN CcPreparePinWrite (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN Zero, __in ULONG Flags, __out PVOID * Bcb, __deref_out_bcount(Length) PVOID * Buffer)
Definition at line 859 of file pinsup.c.
References CcAllocateObcb(), CcMapDataForOverwrite(), CcMissCounter, CcPinFileData(), CcSetDirtyPinnedData(), CcThrowAway, CcUnpinData(), DebugTrace, FALSE, FileOffset, FlagOn, me, NOTHING, NULL, PIN_CALLER_TRACKS_DIRTY_DATA, _LARGE_INTEGER::QuadPart, RtlZeroMemory, TRUE, and try_return.
NTKERNELAPI BOOLEAN CcPurgeCacheSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN UninitializeCacheMaps)
Definition at line 2573 of file fssup.c.
References ARGUMENT_PRESENT, ASSERT, CcAcquireMasterLock, CcCollisionDelay, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFreeActiveVacb(), CcIncrementOpenCount, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcUninitializeCacheMap(), CcUnmapVacbArray(), CcWaitOnActiveCount(), CONTAINING_RECORD, DebugTrace, DebugTrace2, _SHARED_CACHE_MAP::DirtyPages, FALSE, _PRIVATE_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, GetActiveVacbAtDpcLevel, InsertTailList(), IsListEmpty, KeDelayExecutionThread(), KernelMode, LazyWriter, me, mm, MmCanFileBeTruncated(), MmPurgeSection(), NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SIZE, PRIVATE_WRITE, _SHARED_CACHE_MAP::PrivateList, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, _SHARED_CACHE_MAP::Vacbs, VOID, and WRITE_QUEUED.
Referenced by CcPurgeAndClearCacheSection(), CcSetFileSizes(), CcUninitializeCacheMap(), CcUnmapAndPurge(), CcZeroEndOfLastPage(), CmpDestroyHiveViewList(), CmpDoFileSetSize(), CmpUnPinCmView(), and HvRefreshHive().
NTKERNELAPI PVOID CcRemapBcb (__in PVOID Bcb)
Definition at line 5162 of file cachesub.c.
References _VACB::ActiveCount, ASSERT, CACHE_NTC_BCB, CACHE_NTC_OBCB, CcAcquireVacbLock, CcBeyondVacbs, CcReleaseVacbLock, CcVacbs, and _VACB::Overlay.
NTKERNELAPI VOID CcRepinBcb (__in PVOID Bcb)
Definition at line 5239 of file cachesub.c.
References KeAcquireInStackQueuedSpinLock(), and KeReleaseInStackQueuedSpinLock().
NTKERNELAPI VOID CcScheduleReadAhead (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER FileOffset, __in ULONG Length)
Definition at line 1241 of file cachesub.c.
References ASSERT, _PRIVATE_CACHE_MAP::BeyondLastByte1, _PRIVATE_CACHE_MAP::BeyondLastByte2, CC_CLEAR_PRIVATE_CACHE_MAP, CC_SET_PRIVATE_CACHE_MAP, CcAcquireMasterLock, CcAllocateWorkQueueEntry, CcExpressWorkQueue, CcIncrementOpenCount, CcPostWorkQueue(), CcReleaseMasterLock, DebugTrace, DebugTrace2, DISABLE_READ_AHEAD, ExAcquireFastLock, ExAcquireSpinLock, ExReleaseFastLock, ExReleaseSpinLock, FALSE, FileOffset, _PRIVATE_CACHE_MAP::FileOffset1, _PRIVATE_CACHE_MAP::FileOffset2, FlagOn, _PRIVATE_CACHE_MAP::Flags, _SHARED_CACHE_MAP::Flags, FO_SEQUENTIAL_ONLY, _WORK_QUEUE_ENTRY::Function, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, me, NOISE_BITS, NULL, ObReferenceObject, PAGE_SIZE, _WORK_QUEUE_ENTRY::Parameters, PRIVATE_CACHE_MAP_READ_AHEAD_ACTIVE, _LARGE_INTEGER::QuadPart, _WORK_QUEUE_ENTRY::Read, READ_AHEAD_QUEUED, ReadAhead, _PRIVATE_CACHE_MAP_FLAGS::ReadAheadActive, _PRIVATE_CACHE_MAP::ReadAheadLength, _PRIVATE_CACHE_MAP::ReadAheadMask, _PRIVATE_CACHE_MAP::ReadAheadOffset, _PRIVATE_CACHE_MAP::ReadAheadSpinLock, ROUND_TO_PAGES, SetFlag, and TRUE.
Referenced by CcCopyRead(), CcFastCopyRead(), and CcMdlRead().
NTKERNELAPI VOID CcSetAdditionalCacheAttributes (__in PFILE_OBJECT FileObject, __in BOOLEAN DisableReadAhead, __in BOOLEAN DisableWriteBehind)
Definition at line 34 of file logsup.c.
References CcAcquireMasterLock, CcReleaseMasterLock, ClearFlag, DISABLE_READ_AHEAD, DISABLE_WRITE_BEHIND, _SHARED_CACHE_MAP::Flags, MODIFIED_WRITE_DISABLED, and SetFlag.
NTKERNELAPI VOID CcSetBcbOwnerPointer (__in PVOID Bcb, __in PVOID OwnerPointer)
Definition at line 1346 of file pinsup.c.
References ASSERT, CACHE_NTC_OBCB, ExSetResourceOwnerPointer(), and NULL.
NTKERNELAPI VOID CcSetDirtyPageThreshold (__in PFILE_OBJECT FileObject, __in ULONG DirtyPageThreshold)
Definition at line 3011 of file fssup.c.
References _SHARED_CACHE_MAP::DirtyPageThreshold, FlagOn, FSRTL_FLAG_LIMIT_MODIFIED_PAGES, NULL, and SetFlag.
NTKERNELAPI VOID CcSetDirtyPinnedData (__in PVOID BcbVoid, __in_opt PLARGE_INTEGER Lsn)
Definition at line 2557 of file cachesub.c.
References ARGUMENT_PRESENT, ASSERT, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_OBCB, CcAcquireMasterLockAtDpcLevel, CcChargePinDirtyPages, CcDirtySharedCacheMapList, CcReleaseMasterLockFromDpcLevel, CcScheduleLazyWriteScan(), DebugTrace, _SHARED_CACHE_MAP::DirtyPages, DISABLE_WRITE_BEHIND, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, InsertTailList(), KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), LazyWriter, me, NULL, PAGE_SHIFT, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, and _SHARED_CACHE_MAP::ValidDataGoal.
Referenced by CcPreparePinWrite(), CcReleaseByteRangeFromWrite(), CcUnpinRepinnedBcb(), CcZeroData(), CmpFileWriteThroughCache(), and CmpUnPinCmView().
NTKERNELAPI VOID CcSetFileSizes (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes)
Definition at line 2036 of file fssup.c.
References ASSERT, _SHARED_CACHE_MAP::BcbList, CcAcquireMasterLock, CcDecrementOpenCount, CcDeleteBcbs(), CcDeleteMbcb(), CcDirtySharedCacheMapList, CcExtendVacbArray(), CcFreeActiveVacb(), CcIncrementOpenCount, CcPurgeAndClearCacheSection(), CcPurgeCacheSection(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), DebugTrace, DebugTrace2, DEFAULT_EXTEND_MODULO, _SHARED_CACHE_MAP::DirtyPages, ExRaiseStatus(), FALSE, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FsRtlNormalizeNtstatus(), GetActiveVacbAtDpcLevel, _LARGE_INTEGER::HighPart, InsertTailList(), IsListEmpty, LazyWriter, _LARGE_INTEGER::LowPart, _SHARED_CACHE_MAP::Mbcb, me, mm, MmExtendSection(), MmFlushSection(), _SHARED_CACHE_MAP::NeedToZero, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SIZE, PIN_ACCESS, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::Section, _SHARED_CACHE_MAP::SectionSize, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, Status, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_UNEXPECTED_MM_EXTEND_ERR, TRUE, _SHARED_CACHE_MAP::VacbActiveCount, _SHARED_CACHE_MAP::ValidDataGoal, _SHARED_CACHE_MAP::ValidDataLength, and WRITE_QUEUED.
NTKERNELAPI VOID CcSetLogHandleForFile (__in PFILE_OBJECT FileObject, __in PVOID LogHandle, __in PFLUSH_TO_LSN FlushToLsnRoutine)
Definition at line 242 of file logsup.c.
References _SHARED_CACHE_MAP::FlushToLsnRoutine, and _SHARED_CACHE_MAP::LogHandle.
NTKERNELAPI BOOLEAN CcSetPrivateWriteFile (PFILE_OBJECT FileObject)
Definition at line 95 of file logsup.c.
References CcAcquireMasterLock, CcFlushCache(), CcFreeActiveVacb(), CcReleaseMasterLock, CcUnmapVacbArray(), CcWaitForCurrentLazyWriterActivity(), CcWaitOnActiveCount(), DISABLE_WRITE_BEHIND, Disabled, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, FsRtlAcquireFileExclusive(), FsRtlReleaseFile(), GetActiveVacbAtDpcLevel, MmDisableModifiedWriteOfSection(), NULL, PRIVATE_WRITE, READ_AHEAD_QUEUED, _FILE_OBJECT::SectionObjectPointer, SetFlag, _SECTION_OBJECT_POINTERS::SharedCacheMap, _SHARED_CACHE_MAP::Vacbs, and WRITE_QUEUED.
Referenced by CmpAcquireFileObjectForFile().
NTKERNELAPI VOID CcSetReadAheadGranularity (__in PFILE_OBJECT FileObject, __in ULONG Granularity)
Definition at line 1210 of file cachesub.c.
NTKERNELAPI BOOLEAN CcUninitializeCacheMap (__in PFILE_OBJECT FileObject, __in_opt PLARGE_INTEGER TruncateSize, __in_opt PCACHE_UNINITIALIZE_EVENT UninitializeEvent)
Definition at line 1092 of file fssup.c.
References ARGUMENT_PRESENT, ASSERT, CcAcquireMasterLock, CcDecrementOpenCount, CcDeleteSharedCacheMap(), CcDirtySharedCacheMapList, CcFreeActiveVacb(), CcPurgeCacheSection(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), ClearFlag, DebugTrace, DebugTrace2, _SHARED_CACHE_MAP::DirtyPages, DISABLE_WRITE_BEHIND, ExFreePool(), FALSE, _PRIVATE_CACHE_MAP::FileObject, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FORCED_WRITE_THROUGH, GetActiveVacbAtDpcLevel, InsertTailList(), IsListEmpty, KeSetEvent(), LazyWriter, me, mm, MmEnableModifiedWriteOfSection(), _PRIVATE_CACHE_MAP::NodeTypeCode, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PIN_ACCESS, PRIVATE_WRITE, _SHARED_CACHE_MAP::PrivateCacheMap, _PRIVATE_CACHE_MAP::PrivateLinks, _SHARED_CACHE_MAP::PrivateList, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, SetFlag, _VACB::SharedCacheMap, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, TRUNCATE_REQUIRED, _SHARED_CACHE_MAP::UninitializeEvent, and WRITE_QUEUED.
Referenced by CcPurgeCacheSection().
LOGICAL CcUnmapInactiveViews (IN ULONG NumberOfViewsToUnmap)
Definition at line 6824 of file cachesub.c.
References FALSE, and UNREFERENCED_PARAMETER.
Referenced by MiRemoveUnusedSegments().
NTKERNELAPI VOID CcUnpinData (__in PVOID Bcb)
Definition at line 1268 of file pinsup.c.
References CACHE_NTC_OBCB, CcUnpinData(), CcUnpinFileData, DebugTrace, ExFreePool(), FALSE, me, NULL, TRUE, and UNPIN.
Referenced by CcPinMappedData(), CcPinRead(), CcPreparePinWrite(), CcUnpinData(), CmpFileWriteThroughCache(), CmpUnmapCmView(), and CmpUnPinCmView().
NTKERNELAPI VOID CcUnpinDataForThread (__in PVOID Bcb, __in ERESOURCE_THREAD ResourceThreadId)
Definition at line 1410 of file pinsup.c.
References CACHE_NTC_OBCB, CcUnpinDataForThread(), CcUnpinFileData, DebugTrace, ExFreePool(), ExReleaseResourceForThreadLite(), me, NULL, TRUE, and UNPIN.
Referenced by CcUnpinDataForThread().
NTKERNELAPI VOID CcUnpinRepinnedBcb (__in PVOID Bcb, __in BOOLEAN WriteThrough, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 5281 of file cachesub.c.
References ASSERT, CcDeferredWrites, CcPostDeferredWrites(), CcSetDirtyPinnedData(), CcUnpinFileData, DebugTrace, DebugTrace2, ExAcquireResourceExclusiveLite(), FALSE, _SHARED_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, IsListEmpty, me, MM_FLUSH_ACQUIRE_FILE, MmFlushSection(), MmSetAddressRangeModified(), MODIFIED_WRITE_DISABLED, NULL, RetryError, _FILE_OBJECT::SectionObjectPointer, SET_CLEAN, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_SUCCESS, TRUE, and UNPIN.
NTKERNELAPI NTSTATUS CcWaitForCurrentLazyWriterActivity (VOID)
VOID CcWaitForUninitializeCacheMap (IN PFILE_OBJECT FileObject)
Definition at line 1449 of file fssup.c.
References CcAcquireMasterLock, CcReleaseMasterLock, CcScheduleLazyWriteScan(), ClearFlag, ClearMmWaiterFlag, CONTAINING_RECORD, DebugTrace, _CACHE_UNINITIALIZE_EVENT::Event, Executive, exit(), FALSE, _SHARED_CACHE_MAP::Flags, IsListEmpty, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), me, NANO_FULL_SECOND, _CACHE_UNINITIALIZE_EVENT::Next, NotificationEvent, NULL, _SHARED_CACHE_MAP::OpenCount, _SHARED_CACHE_MAP::PrivateList, _LARGE_INTEGER::QuadPart, SetFlag, SetMmWaiterFlag, Status, STATUS_TIMEOUT, TRUE, _SHARED_CACHE_MAP::UninitializeEvent, and WAITING_FOR_TEARDOWN.
Referenced by MmCreateSection().
NTKERNELAPI BOOLEAN CcZeroData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER StartOffset, __in PLARGE_INTEGER EndOffset, __in BOOLEAN Wait)
Definition at line 3224 of file fssup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, CcAggressiveZeroCount, CcAggressiveZeroThreshold, CcPinFileData(), CcSetDirtyPinnedData(), CcUnpinFileData, DebugTrace, ExAllocatePoolWithTag, Executive, ExFreePool(), ExRaiseStatus(), FALSE, FlagOn, FO_WRITE_THROUGH, _LARGE_INTEGER::HighPart, InterlockedDecrement, InterlockedIncrement, IoAllocateMdl(), IoFreeMdl(), IoGetRelatedDeviceObject(), IoReadAccess, IoSynchronousPageWrite(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LowPagePriority, _LARGE_INTEGER::LowPart, _MDL::MappedSystemVa, MAX_ZERO_TRANSFER, MAX_ZEROS_IN_CACHE, MDL_PAGES_LOCKED, MDL_SOURCE_IS_NONPAGED_POOL, _MDL::MdlFlags, me, MIN_ZERO_TRANSFER, MmAvailablePages, MmBuildMdlForNonPagedPool(), MmDisablePageFaultClustering, MmEnablePageFaultClustering, MmGetMdlPfnArray, MmGetSystemAddressForMdl, MmGetSystemAddressForMdlSafe, MmProbeAndLockPages(), MmSetAddressRangeModified(), MmUnlockPages(), MmUnmapLockedPages(), NonPagedPoolCacheAligned, NOTHING, NotificationEvent, NT_SUCCESS, NULL, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlZeroMemory, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, TRUE, try_return, and UNPIN.
Referenced by FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
NTKERNELAPI VOID CcZeroEndOfLastPage (IN PFILE_OBJECT FileObject)
Definition at line 3067 of file fssup.c.
References _SHARED_CACHE_MAP::ActiveVacb, ASSERT, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFlushCache(), CcFreeActiveVacb(), CcIncrementOpenCount, CcPurgeCacheSection(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), _SHARED_CACHE_MAP::DirtyPages, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, FSRTL_FLAG2_PURGE_WHEN_MAPPED, FSRTL_FLAG_ADVANCED_HEADER, FSRTL_FLAG_USER_MAPPED_FILE, FsRtlAcquireFileExclusive(), FsRtlReleaseFile(), GetActiveVacbAtDpcLevel, InsertTailList(), LazyWriter, _SHARED_CACHE_MAP::NeedToZero, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, RemoveEntryList(), _LAZY_WRITER::ScanActive, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, _IO_STATUS_BLOCK::Status, STATUS_SUCCESS, TRUE, and WRITE_QUEUED.
Referenced by FsRtlCreateSectionForDataScan(), MiCreateImageFileMap(), and NtCreateSection().
Variable Documentation
ULONG CcCopyReadNoWait
Definition at line 175 of file cachedat.c.
Referenced by CcCopyRead(), and NtQuerySystemInformation().
ULONG CcCopyReadNoWaitMiss
Definition at line 177 of file cachedat.c.
Referenced by CcCopyRead(), and NtQuerySystemInformation().
ULONG CcCopyReadWait
Definition at line 176 of file cachedat.c.
Referenced by CcCopyRead(), CcFastCopyRead(), and NtQuerySystemInformation().
ULONG CcCopyReadWaitMiss
Definition at line 178 of file cachedat.c.
Referenced by CcCopyRead(), CcFastCopyRead(), and NtQuerySystemInformation().
ULONG CcDataFlushes
Definition at line 190 of file cachedat.c.
Referenced by IoAsynchronousPageWrite(), IoSynchronousPageWrite(), and NtQuerySystemInformation().
ULONG CcDataPages
Definition at line 191 of file cachedat.c.
Referenced by IoAsynchronousPageWrite(), IoSynchronousPageWrite(), and NtQuerySystemInformation().
ULONG CcFastMdlReadNotPossible
Definition at line 161 of file cachedat.c.
Referenced by FsRtlMdlReadDev(), and NtQuerySystemInformation().
ULONG CcFastMdlReadNoWait
Definition at line 158 of file cachedat.c.
Referenced by NtQuerySystemInformation().
ULONG CcFastMdlReadResourceMiss
Definition at line 160 of file cachedat.c.
Referenced by NtQuerySystemInformation().
ULONG CcFastMdlReadWait
Definition at line 159 of file cachedat.c.
Referenced by FsRtlMdlReadDev(), and NtQuerySystemInformation().
ULONG CcFastReadNotPossible
Definition at line 156 of file cachedat.c.
Referenced by FsRtlCopyRead(), FsRtlIncrementCcFastReadNotPossible(), and NtQuerySystemInformation().
ULONG CcFastReadNoWait
Definition at line 153 of file cachedat.c.
Referenced by FsRtlCopyRead(), FsRtlIncrementCcFastReadNoWait(), and NtQuerySystemInformation().
ULONG CcFastReadResourceMiss
Definition at line 155 of file cachedat.c.
Referenced by FsRtlCopyRead(), FsRtlIncrementCcFastReadResourceMiss(), and NtQuerySystemInformation().
ULONG CcFastReadWait
Definition at line 154 of file cachedat.c.
Referenced by FsRtlCopyRead(), FsRtlIncrementCcFastReadWait(), and NtQuerySystemInformation().
ULONG CcLazyWriteIos
Definition at line 188 of file cachedat.c.
Referenced by CcFlushCache(), and NtQuerySystemInformation().
ULONG CcLazyWritePages
Definition at line 189 of file cachedat.c.
Referenced by CcFlushCache(), and NtQuerySystemInformation().
ULONG CcLostDelayedWrites
Definition at line 193 of file cachedat.c.
Referenced by CcWriteBehind(), and NtQuerySystemInformation().
ULONG CcMapDataNoWait
Definition at line 163 of file cachedat.c.
Referenced by CcMapDataCommon(), and NtQuerySystemInformation().
ULONG CcMapDataNoWaitMiss
Definition at line 165 of file cachedat.c.
Referenced by CcMapDataCommon(), and NtQuerySystemInformation().
ULONG CcMapDataWait
Definition at line 164 of file cachedat.c.
Referenced by CcMapDataCommon(), and NtQuerySystemInformation().
ULONG CcMapDataWaitMiss
Definition at line 166 of file cachedat.c.
Referenced by CcMapDataCommon(), and NtQuerySystemInformation().
ULONG CcMdlReadNoWait
Definition at line 180 of file cachedat.c.
Referenced by NtQuerySystemInformation().
ULONG CcMdlReadNoWaitMiss
Definition at line 182 of file cachedat.c.
Referenced by NtQuerySystemInformation().
ULONG CcMdlReadWait
Definition at line 181 of file cachedat.c.
Referenced by CcMdlRead(), and NtQuerySystemInformation().
ULONG CcMdlReadWaitMiss
Definition at line 183 of file cachedat.c.
Referenced by CcMdlRead(), and NtQuerySystemInformation().
PULONG CcMissCounter
Definition at line 195 of file cachedat.c.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapData(), CcMapDataCommon(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), CcPinRead(), CcPreparePinWrite(), and IoPageRead().
LOGICAL CcPfEnablePrefetcher
LONG CcPfNumActiveTraces
LOGICAL CcPfPrefetchingForBoot
ULONG CcPinMappedDataCount
Definition at line 168 of file cachedat.c.
Referenced by CcPinMappedData(), and NtQuerySystemInformation().
ULONG CcPinReadNoWait
Definition at line 170 of file cachedat.c.
Referenced by CcPinRead(), and NtQuerySystemInformation().
ULONG CcPinReadNoWaitMiss
Definition at line 172 of file cachedat.c.
Referenced by CcPinRead(), and NtQuerySystemInformation().
ULONG CcPinReadWait
Definition at line 171 of file cachedat.c.
Referenced by CcPinRead(), and NtQuerySystemInformation().
ULONG CcPinReadWaitMiss
Definition at line 173 of file cachedat.c.
Referenced by CcPinRead(), and NtQuerySystemInformation().
ULONG CcReadAheadIos
Definition at line 185 of file cachedat.c.
Referenced by CcPerformReadAhead(), and NtQuerySystemInformation().
ULONG CcThrowAway
Definition at line 147 of file cachedat.c.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapData(), CcMapDataForOverwrite(), CcMdlRead(), CcPerformReadAhead(), CcPinRead(), and CcPreparePinWrite().