Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/inbv.h File Reference
inbv.h File Reference
Typedefs
typedef enum _INBV_DISPLAY_STATE INBV_DISPLAY_STATE
typedef VOID(* INBV_DISPLAY_STRING_FILTER) (PUCHAR *Str)
typedef BOOLEAN(* INBV_RESET_DISPLAY_PARAMETERS) (ULONG Cols, ULONG Rows)
Enumerations
enum _INBV_DISPLAY_STATE { INBV_DISPLAY_STATE_OWNED, INBV_DISPLAY_STATE_DISABLED, INBV_DISPLAY_STATE_LOST }
Functions
NTKERNELAPI VOID InbvAcquireDisplayOwnership (VOID)
VOID InbvAcquireLock (VOID)
VOID InbvBitBlt (PUCHAR Buffer, ULONG x, ULONG y)
VOID InbvBufferToScreenBlt (PUCHAR Buffer, ULONG x, ULONG y, ULONG width, ULONG height, ULONG lDelta)
NTKERNELAPI BOOLEAN InbvCheckDisplayOwnership (VOID)
NTKERNELAPI BOOLEAN InbvDisplayString (PUCHAR Str)
BOOLEAN InbvDriverInitialize (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN ULONG Count)
NTKERNELAPI VOID InbvEnableBootDriver (BOOLEAN bEnable)
NTKERNELAPI BOOLEAN InbvEnableDisplayString (BOOLEAN bEnable)
INBV_DISPLAY_STATE InbvGetDisplayState (VOID)
PUCHAR InbvGetResourceAddress (IN ULONG ResourceNumber)
VOID InbvIndicateProgress (VOID)
NTKERNELAPI VOID InbvInstallDisplayStringFilter (INBV_DISPLAY_STRING_FILTER DisplayStringFilter)
NTKERNELAPI BOOLEAN InbvIsBootDriverInstalled (VOID)
NTKERNELAPI VOID InbvNotifyDisplayOwnershipLost (INBV_RESET_DISPLAY_PARAMETERS ResetDisplayParameters)
VOID InbvPortEnableFifo (IN ULONG DeviceId, IN BOOLEAN bEnable)
BOOLEAN InbvPortGetByte (IN ULONG BlFileId, OUT PUCHAR Input)
BOOLEAN InbvPortInitialize (IN ULONG BaudRate, IN ULONG PortNumber, IN PUCHAR PortAddress, OUT PULONG BlFileId, IN BOOLEAN IsMMIOAddress)
BOOLEAN InbvPortPollOnly (IN ULONG BlFileId)
VOID InbvPortPutByte (IN ULONG BlFileId, IN UCHAR Output)
VOID InbvPortPutString (IN ULONG BlFileId, IN PUCHAR Output)
BOOLEAN InbvPortTerminate (IN ULONG BlFileId)
VOID InbvReleaseLock (VOID)
NTKERNELAPI BOOLEAN InbvResetDisplay ()
VOID InbvScreenToBufferBlt (PUCHAR Buffer, ULONG x, ULONG y, ULONG width, ULONG height, ULONG lDelta)
VOID InbvSetBootDriverBehavior (PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID InbvSetDisplayOwnership (BOOLEAN DisplayOwned)
VOID InbvSetProgressBarCoordinates (ULONG x, ULONG y)
VOID InbvSetProgressBarSubset (ULONG Floor, ULONG Ceiling)
NTKERNELAPI VOID InbvSetScrollRegion (ULONG x1, ULONG y1, ULONG x2, ULONG y2)
NTKERNELAPI ULONG InbvSetTextColor (ULONG Color)
NTKERNELAPI VOID InbvSolidColorFill (ULONG x1, ULONG y1, ULONG x2, ULONG y2, ULONG color)
BOOLEAN InbvTestLock (VOID)
VOID InbvUpdateProgressBar (ULONG Percentage)
Typedef Documentation
typedef enum _INBV_DISPLAY_STATE INBV_DISPLAY_STATE
typedef VOID(* INBV_DISPLAY_STRING_FILTER) (PUCHAR *Str)
Definition at line 39 of file inbv.h.
typedef BOOLEAN(* INBV_RESET_DISPLAY_PARAMETERS) (ULONG Cols, ULONG Rows)
Definition at line 32 of file inbv.h.
Enumeration Type Documentation
enum _INBV_DISPLAY_STATE
Enumerator
INBV_DISPLAY_STATE_OWNED
INBV_DISPLAY_STATE_DISABLED
INBV_DISPLAY_STATE_LOST
Definition at line 23 of file inbv.h.
Function Documentation
NTKERNELAPI VOID InbvAcquireDisplayOwnership (VOID)
VOID InbvAcquireLock (VOID)
VOID InbvBitBlt (PUCHAR Buffer, ULONG x, ULONG y)
VOID InbvBufferToScreenBlt (PUCHAR Buffer, ULONG x, ULONG y, ULONG width, ULONG height, ULONG lDelta)
NTKERNELAPI BOOLEAN InbvCheckDisplayOwnership (VOID)
NTKERNELAPI BOOLEAN InbvDisplayString (PUCHAR Str)
Referenced by KeBugCheck2(), and KeGetBugMessageText().
BOOLEAN InbvDriverInitialize (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN ULONG Count)
Referenced by Phase1InitializationDiscard().
NTKERNELAPI VOID InbvEnableBootDriver (BOOLEAN bEnable)
Referenced by Phase1InitializationDiscard().
NTKERNELAPI BOOLEAN InbvEnableDisplayString (BOOLEAN bEnable)
Referenced by Phase1InitializationDiscard().
INBV_DISPLAY_STATE InbvGetDisplayState (VOID)
PUCHAR InbvGetResourceAddress (IN ULONG ResourceNumber)
VOID InbvIndicateProgress (VOID)
Referenced by IopInitializeBuiltinDriver().
NTKERNELAPI VOID InbvInstallDisplayStringFilter (INBV_DISPLAY_STRING_FILTER DisplayStringFilter)
NTKERNELAPI BOOLEAN InbvIsBootDriverInstalled (VOID)
NTKERNELAPI VOID InbvNotifyDisplayOwnershipLost (INBV_RESET_DISPLAY_PARAMETERS ResetDisplayParameters)
Referenced by Phase1InitializationDiscard().
VOID InbvPortEnableFifo (IN ULONG DeviceId, IN BOOLEAN bEnable)
BOOLEAN InbvPortGetByte (IN ULONG BlFileId, OUT PUCHAR Input)
BOOLEAN InbvPortInitialize (IN ULONG BaudRate, IN ULONG PortNumber, IN PUCHAR PortAddress, OUT PULONG BlFileId, IN BOOLEAN IsMMIOAddress)
BOOLEAN InbvPortPollOnly (IN ULONG BlFileId)
VOID InbvPortPutByte (IN ULONG BlFileId, IN UCHAR Output)
VOID InbvPortPutString (IN ULONG BlFileId, IN PUCHAR Output)
BOOLEAN InbvPortTerminate (IN ULONG BlFileId)
VOID InbvReleaseLock (VOID)
NTKERNELAPI BOOLEAN InbvResetDisplay ()
VOID InbvScreenToBufferBlt (PUCHAR Buffer, ULONG x, ULONG y, ULONG width, ULONG height, ULONG lDelta)
VOID InbvSetBootDriverBehavior (PLOADER_PARAMETER_BLOCK LoaderBlock)
VOID InbvSetDisplayOwnership (BOOLEAN DisplayOwned)
VOID InbvSetProgressBarCoordinates (ULONG x, ULONG y)
VOID InbvSetProgressBarSubset (ULONG Floor, ULONG Ceiling)
Referenced by Phase1InitializationDiscard().
NTKERNELAPI VOID InbvSetScrollRegion (ULONG x1, ULONG y1, ULONG x2, ULONG y2)
NTKERNELAPI ULONG InbvSetTextColor (ULONG Color)
NTKERNELAPI VOID InbvSolidColorFill (ULONG x1, ULONG y1, ULONG x2, ULONG y2, ULONG color)
BOOLEAN InbvTestLock (VOID)
VOID InbvUpdateProgressBar (ULONG Percentage)
Referenced by Phase1InitializationDiscard().