Windows Research Kernel v1.2: C:/Windows Research Kernel/se/subject.c File Reference
subject.c File Reference
#include "pch.h"
Functions
VOID SeCaptureSubjectContext (__out PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SeCaptureSubjectContextEx (__in PETHREAD Thread, __in PEPROCESS Process, __out PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SeLockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SepGetDefaultsSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, OUT PSID *Owner, OUT PSID *Group, OUT PSID *ServerOwner, OUT PSID *ServerGroup, OUT PACL *Dacl)
BOOLEAN SepIdAssignableAsGroup (IN PACCESS_TOKEN AToken, IN PSID Group)
BOOLEAN SepValidOwnerSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, IN PSID Owner, IN BOOLEAN ServerObject)
VOID SeReleaseSubjectContext (__inout PSECURITY_SUBJECT_CONTEXT SubjectContext)
VOID SeUnlockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
Function Documentation
VOID SeCaptureSubjectContext (__out PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 43 of file subject.c.
References PsGetCurrentProcess(), PsGetCurrentThread(), and SeCaptureSubjectContextEx().
Referenced by CmpCheckKeyAccess(), CmpNotifyChangeKey(), NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtSetUuidSeed(), PspSinglePrivCheck(), RtlpSetSecurityObject(), SeAccessCheckByType(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditSystemTimeChange(), SeCheckPrivilegedObject(), SeCloseObjectAuditAlarm(), SeDeleteObjectAuditAlarm(), SeDetailedAuditingWithToken(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtAuditThisEventWithContext(), SepAuditAssignPrimaryToken(), SeReportSecurityEvent(), SeSinglePrivilegeCheck(), WmipCheckGuidAccess(), and WmipInitializeSecurity().
VOID SeCaptureSubjectContextEx (__in PETHREAD Thread, __in PEPROCESS Process, __out PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 86 of file subject.c.
References DbgBreakPoint(), InterlockedIncrement, NULL, PAGED_CODE, PsProcessAuditId, PsReferenceImpersonationToken(), and PsReferencePrimaryToken().
Referenced by SeCaptureSubjectContext(), and SeCreateAccessStateEx().
VOID SeLockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 180 of file subject.c.
References ARGUMENT_PRESENT, PAGED_CODE, and SepAcquireTokenReadLock.
Referenced by CmpCheckCreateAccess(), CmpCheckNotifyAccess(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), RtlpNewSecurityObject(), SeAccessCheck(), and SepAccessCheckAndAuditAlarm().
VOID SepGetDefaultsSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, OUT PSID * Owner, OUT PSID * Group, OUT PSID * ServerOwner, OUT PSID * ServerGroup, OUT PACL * Dacl)
Definition at line 320 of file subject.c.
References ARGUMENT_PRESENT, _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, EffectiveToken, PAGED_CODE, _TOKEN::PrimaryGroup, _SID_AND_ATTRIBUTES::Sid, and _TOKEN::UserAndGroups.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
BOOLEAN SepIdAssignableAsGroup (IN PACCESS_TOKEN AToken, IN PSID Group)
Definition at line 392 of file subject.c.
References FALSE, Index, NULL, PAGED_CODE, RtlEqualSid(), SepAcquireTokenReadLock, SepReleaseTokenReadLock, _SID_AND_ATTRIBUTES::Sid, and _TOKEN::UserAndGroups.
Referenced by NtSetInformationToken().
BOOLEAN SepValidOwnerSubjectContext (IN PSECURITY_SUBJECT_CONTEXT SubjectContext, IN PSID Owner, IN BOOLEAN ServerObject)
Definition at line 467 of file subject.c.
References ARGUMENT_PRESENT, EffectiveToken, exit(), FALSE, _TOKEN::ImpersonationLevel, Index, NULL, PAGED_CODE, RtlEqualSid(), SecurityImpersonation, SepAcquireTokenReadLock, SepIdAssignableAsOwner(), SepReleaseTokenReadLock, SeRestorePrivilege, SeSinglePrivilegeCheck(), _SID_AND_ATTRIBUTES::Sid, TokenImpersonation, _TOKEN::TokenType, TRUE, _TOKEN::UserAndGroups, and UserMode.
Referenced by RtlpNewSecurityObject(), and RtlpSetSecurityObject().
VOID SeReleaseSubjectContext (__inout PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 261 of file subject.c.
References DbgBreakPoint(), InterlockedDecrement, NULL, PAGED_CODE, PsDereferenceImpersonationToken, PsDereferencePrimaryTokenEx, and PsGetCurrentProcess().
Referenced by CmpCheckKeyAccess(), CmpFlushNotify(), FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifyFilterChangeDirectory(), NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), NtSetUuidSeed(), PspSinglePrivCheckAudit(), RtlpSetSecurityObject(), SeAccessCheckByType(), SeAuditHandleDuplication(), SeAuditHardLinkCreation(), SeAuditLPCInvalidUse(), SeAuditProcessCreation(), SeAuditSystemTimeChange(), SeCheckPrivilegedObject(), SeCloseObjectAuditAlarm(), SeDeleteAccessState(), SeDeleteObjectAuditAlarm(), SeDetailedAuditingWithToken(), SeOperationAuditAlarm(), SepAccessCheckAndAuditAlarm(), SepAdtAuditThisEventWithContext(), SepAuditAssignPrimaryToken(), SeReportSecurityEvent(), SeSinglePrivilegeCheck(), and WmipCheckGuidAccess().
VOID SeUnlockSubjectContext (__in PSECURITY_SUBJECT_CONTEXT SubjectContext)
Definition at line 224 of file subject.c.
References ARGUMENT_PRESENT, PAGED_CODE, and SepReleaseTokenReadLock.
Referenced by CmpCheckCreateAccess(), CmpCheckNotifyAccess(), IopParseDevice(), ObCheckCreateObjectAccess(), ObCheckObjectAccess(), ObpCheckObjectReference(), ObpCheckTraverseAccess(), RtlpNewSecurityObject(), SeAccessCheck(), and SepAccessCheckAndAuditAlarm().