Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/fssup.c File Reference
fssup.c File Reference
#include "cc.h"
Macros
#define BugCheckFileId (CACHE_BUG_CHECK_FSSUP)
#define IsSyscacheFile(FO)
#define me 0x00000001
Functions
VOID CcCancelMmWaitForUninitializeCacheMap (IN PSHARED_CACHE_MAP SharedCacheMap)
VOID CcDeleteBcbs (IN PSHARED_CACHE_MAP SharedCacheMap)
VOID CcDeleteMbcb (IN PSHARED_CACHE_MAP SharedCacheMap)
VOID FASTCALL CcDeleteSharedCacheMap (IN PSHARED_CACHE_MAP SharedCacheMap, IN KIRQL ListIrql, IN ULONG ReleaseFile)
PFILE_OBJECT CcGetFileObjectFromBcb (__in PVOID Bcb)
PFILE_OBJECT CcGetFileObjectFromSectionPtrs (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
BOOLEAN CcInitializeCacheManager ()
VOID CcInitializeCacheMap (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes, __in BOOLEAN PinAccess, __in PCACHE_MANAGER_CALLBACKS Callbacks, __in PVOID LazyWriteContext)
VOID CcPurgeAndClearCacheSection (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset)
BOOLEAN CcPurgeCacheSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN UninitializeCacheMaps)
VOID CcSetDirtyPageThreshold (__in PFILE_OBJECT FileObject, __in ULONG DirtyPageThreshold)
VOID CcSetFileSizes (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes)
BOOLEAN CcUninitializeCacheMap (__in PFILE_OBJECT FileObject, __in_opt PLARGE_INTEGER TruncateSize, __in_opt PCACHE_UNINITIALIZE_EVENT UninitializeEvent)
VOID CcUnmapAndPurge (IN PSHARED_CACHE_MAP SharedCacheMap)
VOID CcWaitForUninitializeCacheMap (IN PFILE_OBJECT FileObject)
BOOLEAN CcZeroData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER StartOffset, __in PLARGE_INTEGER EndOffset, __in BOOLEAN Wait)
VOID CcZeroEndOfLastPage (IN PFILE_OBJECT FileObject)
Variables
POBJECT_TYPE IoFileObjectType
ULONG MmLargeSystemCache
Macro Definition Documentation
#define BugCheckFileId (CACHE_BUG_CHECK_FSSUP)
Definition at line 26 of file fssup.c.
#define IsSyscacheFile (FO)
Value:
(((FO) != NULL) &&                                               \
                            (*(PUSHORT)(FO)->FsContext == 0X705) &&                         \
                            FlagOn(*(PULONG)((PCHAR)(FO)->FsContext + 0x48), 0x80000000))
Definition at line 38 of file fssup.c.
#define me 0x00000001
Definition at line 32 of file fssup.c.
Referenced by CcDeleteSharedCacheMap(), CcInitializeCacheMap(), CcPurgeCacheSection(), CcSetFileSizes(), CcUninitializeCacheMap(), CcWaitForUninitializeCacheMap(), and CcZeroData().
Function Documentation
VOID CcCancelMmWaitForUninitializeCacheMap (IN PSHARED_CACHE_MAP SharedCacheMap)
Definition at line 1666 of file fssup.c.
References ClearFlag, ClearMmWaiterFlag, CONTAINING_RECORD, _CACHE_UNINITIALIZE_EVENT::Event, FALSE, KeSetEvent(), _CACHE_UNINITIALIZE_EVENT::Next, NULL, TestMmWaiterFlag, and WAITING_FOR_TEARDOWN.
Referenced by CcWriteBehind().
VOID CcDeleteBcbs (IN PSHARED_CACHE_MAP SharedCacheMap)
Definition at line 1713 of file fssup.c.
References ASSERT, _BCB::BaseAddress, _BCB::BcbLinks, _BCB::ByteLength, CACHE_NTC_BCB, CcAcquireMasterLock, CcDeallocateBcb(), CcDeductDirtyPages, CcFreeVirtualAddress(), CcReleaseMasterLock, CcUnlockVacbLevel, CONTAINING_RECORD, _BCB::Dirty, _BCB::FileOffset, _LIST_ENTRY::Flink, _BCB::NodeTypeCode, NULL, PAGE_SHIFT, _BCB::PinCount, _LARGE_INTEGER::QuadPart, RemoveEntryList(), and _BCB::Vacb.
Referenced by CcDeleteSharedCacheMap(), and CcSetFileSizes().
VOID CcDeleteMbcb (IN PSHARED_CACHE_MAP SharedCacheMap)
Definition at line 2873 of file fssup.c.
References _BITMAP_RANGE::Bitmap, _MBCB::BitmapRange2, _MBCB::BitmapRanges, CcAcquireMasterLockAtDpcLevel, CcAcquireVacbLockAtDpcLevel, CcDeallocateBcb(), CcDeallocateVacbLevel(), CcDeductDirtyPages, CcDrainVacbLevelZone(), CcReleaseMasterLockFromDpcLevel, CcReleaseVacbLockFromDpcLevel, CONTAINING_RECORD, _BITMAP_RANGE::DirtyPages, _MBCB::DirtyPages, ExFreePool(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IsListEmpty, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _BITMAP_RANGE::Links, MBCB_BITMAP_BLOCK_SIZE, NULL, RemoveEntryList(), RemoveHeadList(), RtlZeroMemory, and TRUE.
Referenced by CcDeleteSharedCacheMap(), and CcSetFileSizes().
VOID FASTCALL CcDeleteSharedCacheMap (IN PSHARED_CACHE_MAP SharedCacheMap, IN KIRQL ListIrql, IN ULONG ReleaseFile)
Definition at line 1814 of file fssup.c.
References ASSERT, CcAcquireMasterLock, CcDeleteBcbs(), CcDeleteMbcb(), CcFreeActiveVacb(), CcReleaseMasterLock, CcUnmapAndPurge(), CcWaitOnActiveCount(), ClearMmWaiterFlag, DebugTrace, _CACHE_UNINITIALIZE_EVENT::Event, ExFreePool(), FALSE, FsRtlReleaseFile(), GetActiveVacbAtDpcLevel, InitializeListHead(), InsertTailList(), IsListEmpty, IsVacbLevelReferenced(), KeSetEvent(), me, _CACHE_UNINITIALIZE_EVENT::Next, NULL, ObDereferenceObject(), RemoveEntryList(), _FILE_OBJECT::SectionObjectPointer, SetFlag, _SECTION_OBJECT_POINTERS::SharedCacheMap, VACB_SIZE_OF_FIRST_LEVEL, and WRITE_QUEUED.
Referenced by CcInitializeCacheMap(), CcUninitializeCacheMap(), and CcWriteBehind().
PFILE_OBJECT CcGetFileObjectFromBcb (__in PVOID Bcb)
Definition at line 3974 of file fssup.c.
PFILE_OBJECT CcGetFileObjectFromSectionPtrs (__in PSECTION_OBJECT_POINTERS SectionObjectPointer)
Definition at line 3923 of file fssup.c.
References CcAcquireMasterLock, CcReleaseMasterLock, and NULL.
BOOLEAN CcInitializeCacheManager ()
Definition at line 73 of file fssup.c.
References CcAggressiveZeroCount, CcAggressiveZeroThreshold, CcBugCheck, CcCapturedSystemSize, CcCleanSharedCacheMapList, CcDeferredWrites, CcDeferredWriteSpinLock, CcDirtyPageTarget, CcDirtyPageThreshold, CcDirtySharedCacheMapList, CcExpressWorkQueue, CcIdleDelayTick, CcIdleWorkerThreadList, CcInitializeVacbs(), CcLazyWriterCursor, CcNumberWorkerThreads, CcPostTickWorkQueue, CcRegularWorkQueue, CcScanDpc(), CcTwilightLookasideList, CcWorkerThread(), ExAllocatePoolWithTag, ExCriticalWorkerThreads, ExInitializeSystemLookasideList(), ExInitializeWorkItem, ExSystemLookasideListHead, _SHARED_CACHE_MAP_LIST_CURSOR::Flags, Index, InitializeListHead(), InsertTailList(), IS_CURSOR, KeInitializeDpc(), KeInitializeSpinLock(), KeInitializeTimer(), KeNumberProcessors, KeQueryTimeIncrement(), KiProcessorBlock, _PP_LOOKASIDE_LIST::L, LAZY_WRITER_IDLE_DELAY, LazyWriter, _WORK_QUEUE_ITEM::List, LookasideTwilightList, _MMSUPPORT::MaximumWorkingSetSize, MmIsThisAnNtAsSystem(), MmLargeSystem, MmMediumSystem, MmNumberOfPhysicalPages, MmQuerySystemSize(), MmSmallSystem, MmSystemCacheWs, NonPagedPool, NULL, _PP_LOOKASIDE_LIST::P, PAGE_SIZE, _KPRCB::PPLookasideList, RtlZeroMemory, _LAZY_WRITER::ScanDpc, _LAZY_WRITER::ScanTimer, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, and _LAZY_WRITER::WorkQueue.
Referenced by Phase1InitializationDiscard().
VOID CcInitializeCacheMap (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes, __in BOOLEAN PinAccess, __in PCACHE_MANAGER_CALLBACKS Callbacks, __in PVOID LazyWriteContext)
Definition at line 323 of file fssup.c.
References _SHARED_CACHE_MAP::ActiveVacbSpinLock, _CC_FILE_SIZES::AllocationSize, ASSERT, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, BEING_CREATED, CACHE_NTC_PRIVATE_CACHE_MAP, CACHE_NTC_SHARED_CACHE_MAP, _SHARED_CACHE_MAP::Callbacks, CcAcquireMasterLock, CcCleanSharedCacheMapList, CcCreateVacbArray(), CcDecrementOpenCount, CcDeleteSharedCacheMap(), CcExtendVacbArray(), CcIncrementOpenCount, CcInsertIntoCleanSharedCacheMapList(), CcReleaseMasterLock, ClearFlag, ClearMmWaiterFlag, _SHARED_CACHE_MAP::CreateEvent, DebugTrace, DebugTrace2, DEFAULT_CREATE_MODULO, _SHARED_CACHE_MAP::DirtyPages, _CACHE_UNINITIALIZE_EVENT::Event, ExAllocatePoolWithTag, Executive, ExFreePool(), ExInitializePushLock(), ExRaiseStatus(), FALSE, _PRIVATE_CACHE_MAP::FileObject, _SHARED_CACHE_MAP::FileObject, _CC_FILE_SIZES::FileSize, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FO_RANDOM_ACCESS, FO_SEQUENTIAL_ONLY, FSRTL_FLAG2_DO_MODIFIED_WRITE, FsRtlNormalizeNtstatus(), _LARGE_INTEGER::HighPart, InitializeListHead(), InsertTailList(), KeInitializeEvent(), KeInitializeSpinLock(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _SHARED_CACHE_MAP::LazyWriteContext, _LARGE_INTEGER::LowPart, me, mm, MmCreateSection(), MmDisableModifiedWriteOfSection(), MmExtendSection(), MODIFIED_WRITE_DISABLED, _CACHE_UNINITIALIZE_EVENT::Next, _SHARED_CACHE_MAP::NodeByteSize, _PRIVATE_CACHE_MAP::NodeTypeCode, _SHARED_CACHE_MAP::NodeTypeCode, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, ObDeleteCapturedInsertInfo(), ObReferenceObject, ONLY_SEQUENTIAL_ONLY_SEEN, _SHARED_CACHE_MAP::OpenCount, PAGE_READWRITE, PAGE_SIZE, PIN_ACCESS, _SHARED_CACHE_MAP::PrivateCacheMap, _PRIVATE_CACHE_MAP::PrivateLinks, _SHARED_CACHE_MAP::PrivateList, _LARGE_INTEGER::QuadPart, RANDOM_ACCESS_SEEN, _PRIVATE_CACHE_MAP::ReadAheadMask, _PRIVATE_CACHE_MAP::ReadAheadSpinLock, RemoveEntryList(), RtlZeroMemory, SEC_COMMIT, _SHARED_CACHE_MAP::Section, SECTION_MAP_READ, SECTION_MAP_WRITE, SECTION_QUERY, _SHARED_CACHE_MAP::SectionSize, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, Status, _SHARED_CACHE_MAP::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, STATUS_UNEXPECTED_MM_CREATE_ERR, STATUS_UNEXPECTED_MM_EXTEND_ERR, TRUE, TRUNCATE_REQUIRED, _SHARED_CACHE_MAP::UninitializeEvent, VACB_MAPPING_GRANULARITY, _SHARED_CACHE_MAP::VacbPushLock, _SHARED_CACHE_MAP::Vacbs, _SHARED_CACHE_MAP::ValidDataGoal, _CC_FILE_SIZES::ValidDataLength, _SHARED_CACHE_MAP::ValidDataLength, WAITING_FOR_TEARDOWN, and WRITE_QUEUED.
VOID CcPurgeAndClearCacheSection (IN PSHARED_CACHE_MAP SharedCacheMap, IN PLARGE_INTEGER FileOffset)
Definition at line 2400 of file fssup.c.
References ASSERT, CcFreeVirtualAddress(), CcGetVirtualAddress(), CcPurgeCacheSection(), CcSetDirtyInMask(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, FileOffset, FlagOn, MmFlushSection(), MmSetAddressRangeModified(), NULL, PAGE_SIZE, PRIVATE_WRITE, RtlZeroMemory, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, and TRUE.
Referenced by CcSetFileSizes().
BOOLEAN CcPurgeCacheSection (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in_opt PLARGE_INTEGER FileOffset, __in ULONG Length, __in BOOLEAN UninitializeCacheMaps)
Definition at line 2573 of file fssup.c.
References ARGUMENT_PRESENT, ASSERT, CcAcquireMasterLock, CcCollisionDelay, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFreeActiveVacb(), CcIncrementOpenCount, CcReleaseMasterLock, CcScheduleLazyWriteScan(), CcUninitializeCacheMap(), CcUnmapVacbArray(), CcWaitOnActiveCount(), CONTAINING_RECORD, DebugTrace, DebugTrace2, _SHARED_CACHE_MAP::DirtyPages, FALSE, _PRIVATE_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, GetActiveVacbAtDpcLevel, InsertTailList(), IsListEmpty, KeDelayExecutionThread(), KernelMode, LazyWriter, me, mm, MmCanFileBeTruncated(), MmPurgeSection(), NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SIZE, PRIVATE_WRITE, _SHARED_CACHE_MAP::PrivateList, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, _SHARED_CACHE_MAP::Vacbs, VOID, and WRITE_QUEUED.
Referenced by CcPurgeAndClearCacheSection(), CcSetFileSizes(), CcUninitializeCacheMap(), CcUnmapAndPurge(), CcZeroEndOfLastPage(), CmpDestroyHiveViewList(), CmpDoFileSetSize(), CmpUnPinCmView(), and HvRefreshHive().
VOID CcSetDirtyPageThreshold (__in PFILE_OBJECT FileObject, __in ULONG DirtyPageThreshold)
Definition at line 3011 of file fssup.c.
References _SHARED_CACHE_MAP::DirtyPageThreshold, FlagOn, FSRTL_FLAG_LIMIT_MODIFIED_PAGES, NULL, and SetFlag.
VOID CcSetFileSizes (__in PFILE_OBJECT FileObject, __in PCC_FILE_SIZES FileSizes)
Definition at line 2036 of file fssup.c.
References ASSERT, _SHARED_CACHE_MAP::BcbList, CcAcquireMasterLock, CcDecrementOpenCount, CcDeleteBcbs(), CcDeleteMbcb(), CcDirtySharedCacheMapList, CcExtendVacbArray(), CcFreeActiveVacb(), CcIncrementOpenCount, CcPurgeAndClearCacheSection(), CcPurgeCacheSection(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), DebugTrace, DebugTrace2, DEFAULT_EXTEND_MODULO, _SHARED_CACHE_MAP::DirtyPages, ExRaiseStatus(), FALSE, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FsRtlNormalizeNtstatus(), GetActiveVacbAtDpcLevel, _LARGE_INTEGER::HighPart, InsertTailList(), IsListEmpty, LazyWriter, _LARGE_INTEGER::LowPart, _SHARED_CACHE_MAP::Mbcb, me, mm, MmExtendSection(), MmFlushSection(), _SHARED_CACHE_MAP::NeedToZero, NT_SUCCESS, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PAGE_SIZE, PIN_ACCESS, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, _SHARED_CACHE_MAP::Section, _SHARED_CACHE_MAP::SectionSize, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, Status, _IO_STATUS_BLOCK::Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_UNEXPECTED_MM_EXTEND_ERR, TRUE, _SHARED_CACHE_MAP::VacbActiveCount, _SHARED_CACHE_MAP::ValidDataGoal, _SHARED_CACHE_MAP::ValidDataLength, and WRITE_QUEUED.
BOOLEAN CcUninitializeCacheMap (__in PFILE_OBJECT FileObject, __in_opt PLARGE_INTEGER TruncateSize, __in_opt PCACHE_UNINITIALIZE_EVENT UninitializeEvent)
Definition at line 1092 of file fssup.c.
References ARGUMENT_PRESENT, ASSERT, CcAcquireMasterLock, CcDecrementOpenCount, CcDeleteSharedCacheMap(), CcDirtySharedCacheMapList, CcFreeActiveVacb(), CcPurgeCacheSection(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), ClearFlag, DebugTrace, DebugTrace2, _SHARED_CACHE_MAP::DirtyPages, DISABLE_WRITE_BEHIND, ExFreePool(), FALSE, _PRIVATE_CACHE_MAP::FileObject, _SHARED_CACHE_MAP::FileSize, FlagOn, _SHARED_CACHE_MAP::Flags, FORCED_WRITE_THROUGH, GetActiveVacbAtDpcLevel, InsertTailList(), IsListEmpty, KeSetEvent(), LazyWriter, me, mm, MmEnableModifiedWriteOfSection(), _PRIVATE_CACHE_MAP::NodeTypeCode, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, PIN_ACCESS, PRIVATE_WRITE, _SHARED_CACHE_MAP::PrivateCacheMap, _PRIVATE_CACHE_MAP::PrivateLinks, _SHARED_CACHE_MAP::PrivateList, _LARGE_INTEGER::QuadPart, RemoveEntryList(), _LAZY_WRITER::ScanActive, SetFlag, _VACB::SharedCacheMap, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, TRUNCATE_REQUIRED, _SHARED_CACHE_MAP::UninitializeEvent, and WRITE_QUEUED.
Referenced by CcPurgeCacheSection().
VOID CcUnmapAndPurge (IN PSHARED_CACHE_MAP SharedCacheMap)
Definition at line 2811 of file fssup.c.
References CcPurgeCacheSection(), CcUnmapVacbArray(), DebugTrace, DebugTrace2, FALSE, FlagOn, mm, NULL, _FILE_OBJECT::SectionObjectPointer, TRUNCATE_REQUIRED, and VOID.
Referenced by CcDeleteSharedCacheMap().
VOID CcWaitForUninitializeCacheMap (IN PFILE_OBJECT FileObject)
Definition at line 1449 of file fssup.c.
References CcAcquireMasterLock, CcReleaseMasterLock, CcScheduleLazyWriteScan(), ClearFlag, ClearMmWaiterFlag, CONTAINING_RECORD, DebugTrace, _CACHE_UNINITIALIZE_EVENT::Event, Executive, exit(), FALSE, _SHARED_CACHE_MAP::Flags, IsListEmpty, KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), me, NANO_FULL_SECOND, _CACHE_UNINITIALIZE_EVENT::Next, NotificationEvent, NULL, _SHARED_CACHE_MAP::OpenCount, _SHARED_CACHE_MAP::PrivateList, _LARGE_INTEGER::QuadPart, SetFlag, SetMmWaiterFlag, Status, STATUS_TIMEOUT, TRUE, _SHARED_CACHE_MAP::UninitializeEvent, and WAITING_FOR_TEARDOWN.
Referenced by MmCreateSection().
BOOLEAN CcZeroData (__in PFILE_OBJECT FileObject, __in PLARGE_INTEGER StartOffset, __in PLARGE_INTEGER EndOffset, __in BOOLEAN Wait)
Definition at line 3224 of file fssup.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, ASSERT, _MDL::ByteCount, CcAggressiveZeroCount, CcAggressiveZeroThreshold, CcPinFileData(), CcSetDirtyPinnedData(), CcUnpinFileData, DebugTrace, ExAllocatePoolWithTag, Executive, ExFreePool(), ExRaiseStatus(), FALSE, FlagOn, FO_WRITE_THROUGH, _LARGE_INTEGER::HighPart, InterlockedDecrement, InterlockedIncrement, IoAllocateMdl(), IoFreeMdl(), IoGetRelatedDeviceObject(), IoReadAccess, IoSynchronousPageWrite(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), LowPagePriority, _LARGE_INTEGER::LowPart, _MDL::MappedSystemVa, MAX_ZERO_TRANSFER, MAX_ZEROS_IN_CACHE, MDL_PAGES_LOCKED, MDL_SOURCE_IS_NONPAGED_POOL, _MDL::MdlFlags, me, MIN_ZERO_TRANSFER, MmAvailablePages, MmBuildMdlForNonPagedPool(), MmDisablePageFaultClustering, MmEnablePageFaultClustering, MmGetMdlPfnArray, MmGetSystemAddressForMdl, MmGetSystemAddressForMdlSafe, MmProbeAndLockPages(), MmSetAddressRangeModified(), MmUnlockPages(), MmUnmapLockedPages(), NonPagedPoolCacheAligned, NOTHING, NotificationEvent, NT_SUCCESS, NULL, PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlZeroMemory, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, TRUE, try_return, and UNPIN.
Referenced by FsRtlCopyWrite(), and FsRtlPrepareMdlWriteDev().
VOID CcZeroEndOfLastPage (IN PFILE_OBJECT FileObject)
Definition at line 3067 of file fssup.c.
References _SHARED_CACHE_MAP::ActiveVacb, ASSERT, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcFlushCache(), CcFreeActiveVacb(), CcIncrementOpenCount, CcPurgeCacheSection(), CcReleaseMasterLock, CcScheduleLazyWriteScan(), _SHARED_CACHE_MAP::DirtyPages, ExAcquireFastMutex(), ExReleaseFastMutex(), FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, FSRTL_FLAG2_PURGE_WHEN_MAPPED, FSRTL_FLAG_ADVANCED_HEADER, FSRTL_FLAG_USER_MAPPED_FILE, FsRtlAcquireFileExclusive(), FsRtlReleaseFile(), GetActiveVacbAtDpcLevel, InsertTailList(), LazyWriter, _SHARED_CACHE_MAP::NeedToZero, NULL, _SHARED_CACHE_MAP::OpenCount, _LAZY_WRITER::OtherWork, RemoveEntryList(), _LAZY_WRITER::ScanActive, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, _IO_STATUS_BLOCK::Status, STATUS_SUCCESS, TRUE, and WRITE_QUEUED.
Referenced by FsRtlCreateSectionForDataScan(), MiCreateImageFileMap(), and NtCreateSection().
Variable Documentation
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.
Referenced by BuildQueryDirectoryIrp(), CmpAcquireFileObjectForFile(), IoAttachDevice(), IoCheckDesiredAccess(), IoComputeDesiredAccessFileObject(), IoCreateStreamFileObjectEx(), IoCreateStreamFileObjectLite(), IoGetDeviceObjectPointer(), IopCreateObjectTypes(), IopInvalidateVolumesForDevice(), IopMarkBootPartition(), IopOpenLinkOrRenameTarget(), IopParseDevice(), IopSetEaOrQuotaInformationFile(), IopTrackLink(), IopXxxControlFile(), NtCancelIoFile(), NtFlushBuffersFile(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtQueryEaFile(), NtQueryInformationFile(), NtQueryQuotaInformationFile(), NtQueryVolumeInformationFile(), NtReadFile(), NtReadFileScatter(), NtSetEaFile(), NtSetInformationFile(), NtSetVolumeInformationFile(), NtUnlockFile(), NtWriteFileGather(), ObGetObjectInformation(), ObpLookupObjectName(), PerfInfoFileNameRunDown(), WmipStartLogger(), WmipTraceIo(), WmipTranslateFileHandle(), and WmiUpdateTrace().
ULONG MmLargeSystemCache
Definition at line 222 of file mminit.c.