Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/exceptn.c File Reference
exceptn.c File Reference
#include "ki.h"
Functions
VOID KeContextFromKframes (__in PKTRAP_FRAME TrapFrame, __in PKEXCEPTION_FRAME ExceptionFrame, __inout PCONTEXT ContextRecord)
BOOLEAN KeQueryCurrentStackInformation (__out PKERNEL_STACK_LIMITS Type, __out PULONG64 LowLimit, __out PULONG64 HighLimit)
NTSTATUS KeRaiseUserException (IN NTSTATUS ExceptionCode)
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
BOOLEAN KiPreprocessFault (IN OUT PEXCEPTION_RECORD ExceptionRecord, IN PKTRAP_FRAME TrapFrame, IN OUT PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode)
PXMM_SAVE_AREA32 KxContextToKframes (__inout PKTRAP_FRAME TrapFrame, __inout PKEXCEPTION_FRAME ExceptionFrame, __in PCONTEXT ContextRecord, __in ULONG ContextFlags, __in KPROCESSOR_MODE PreviousMode)
Function Documentation
VOID KeContextFromKframes (__in PKTRAP_FRAME TrapFrame, __in PKEXCEPTION_FRAME ExceptionFrame, __inout PCONTEXT ContextRecord)
Definition at line 31 of file exceptn.c.
References APC_LEVEL, CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, CONTEXT_SEGMENTS, DR7_ACTIVE, KeGetCurrentIrql(), KeLowerIrql, KfRaiseIrql(), MODE_MASK, RPL_MASK, and UserMode.
Referenced by KiDispatchException().
BOOLEAN KeQueryCurrentStackInformation (__out PKERNEL_STACK_LIMITS Type, __out PULONG64 LowLimit, __out PULONG64 HighLimit)
Definition at line 858 of file exceptn.c.
References _KTHREAD::CalloutActive, FALSE, _KTHREAD::InitialStack, KeBugCheckActive, KeGetCurrentPrcb(), KeGetCurrentThread(), KERNEL_STACK_SIZE, _KTHREAD::LargeStack, MM_KSEG0_BASE, MM_SYSTEM_SPACE_END, _KTHREAD::StackBase, _KTHREAD::StackLimit, and TRUE.
Referenced by RtlpGetStackLimits().
NTSTATUS KeRaiseUserException (IN NTSTATUS ExceptionCode)
Definition at line 956 of file exceptn.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetCurrentThread(), KeRaiseUserExceptionDispatcher, MODE_MASK, NULL, _KTRAP_FRAME::SegCs, _KTHREAD::Teb, _KTHREAD::TrapFrame, and UserMode.
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
Definition at line 821 of file exceptn.c.
Referenced by Ki386CheckDelayedNpxTrap(), KiDispatchException(), and KiInitializeUserApc().
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
Definition at line 431 of file exceptn.c.
Referenced by Ki386CheckDelayedNpxTrap(), KiInitializeUserApc(), and KiRaiseException().
BOOLEAN KiPreprocessFault (IN OUT PEXCEPTION_RECORD ExceptionRecord, IN PKTRAP_FRAME TrapFrame, IN OUT PCONTEXT ContextRecord, IN KPROCESSOR_MODE PreviousMode)
Definition at line 443 of file decode.c.
References _DECODE_CONTEXT::DecodeEntry, FALSE, KI_EXCEPTION_ACCESS_VIOLATION, KI_EXCEPTION_GP_FAULT, KI_EXCEPTION_INTEGER_DIVIDE_BY_ZERO, KI_EXCEPTION_INVALID_OP, KiCheckForAtlThunk(), KiCodePatchCycle, KiOpDecode(), KiOpPreprocessAccessViolation(), NT_SUCCESS, NULL, OPF_AV, OPF_DIV, OPF_GP, OPF_INVAL, _DECODE_CONTEXT::Retry, STATUS_ACCESS_VIOLATION, STATUS_ILLEGAL_INSTRUCTION, STATUS_INTEGER_DIVIDE_BY_ZERO, and TRUE.
Referenced by KiDispatchException().
PXMM_SAVE_AREA32 KxContextToKframes (__inout PKTRAP_FRAME TrapFrame, __inout PKEXCEPTION_FRAME ExceptionFrame, __in PCONTEXT ContextRecord, __in ULONG ContextFlags, __in KPROCESSOR_MODE PreviousMode)
Definition at line 238 of file exceptn.c.
References CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, _DISPATCHER_HEADER::DebugActive, DR7_ACTIVE, _KTHREAD::Header, KeGetCurrentThread(), KernelMode, NULL, RPL_MASK, SANITIZE_DR7, SANITIZE_DRADDR, SANITIZE_MXCSR, and UserMode.
Referenced by KiInitializeContextThread().