Windows Research Kernel v1.2: C:/Windows Research Kernel/fsrtl/faulttol.c File Reference
faulttol.c File Reference
#include "FsRtlP.h"
Functions
NTSTATUS FsRtlBalanceReads (__in PDEVICE_OBJECT TargetDevice)
NTSTATUS FsRtlSyncVolumes (__in PDEVICE_OBJECT TargetDevice, __in_opt PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER ByteCount)
Function Documentation
NTSTATUS FsRtlBalanceReads (__in PDEVICE_OBJECT TargetDevice)
Definition at line 29 of file faulttol.c.
References ASSERT, Executive, FALSE, FT_BALANCED_READ_MODE, IoBuildDeviceIoControlRequest(), IoCallDriver(), KeInitializeEvent(), KernelMode, KeWaitForSingleObject(), NotificationEvent, NULL, PIRP, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PENDING, and STATUS_SUCCESS.
NTSTATUS FsRtlSyncVolumes (__in PDEVICE_OBJECT TargetDevice, __in_opt PLARGE_INTEGER ByteOffset, __in PLARGE_INTEGER ByteCount)
Definition at line 94 of file faulttol.c.
References STATUS_SUCCESS, and UNREFERENCED_PARAMETER.