Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/exinit.c File Reference
exinit.c File Reference
#include "exp.h"
#include <zwapi.h>
#include <inbv.h>
#include "safeboot.h"
Functions
ULONG ExComputeTickCountMultiplier (IN ULONG TimeIncrement)
NTKERNELAPI KPROCESSOR_MODE ExGetPreviousMode (VOID)
VOID ExInitializeSystemLookasideList (IN PGENERAL_LOOKASIDE Lookaside, IN POOL_TYPE Type, IN ULONG Size, IN ULONG Tag, IN USHORT Depth, IN PLIST_ENTRY ListHead)
VOID ExInitPoolLookasidePointers (VOID)
BOOLEAN ExInitSystem (VOID)
BOOLEAN ExpInitSystemPhase0 (VOID)
BOOLEAN ExpInitSystemPhase1 (VOID)
int ExSystemExceptionFilter (VOID)
NTSTATUS NtShutdownSystem (__in SHUTDOWN_ACTION Action)
Variables
ULONG ExpHydraEnabled
static ULONG ExpSuiteMask
ULONG ExpTickCountMultiplier
Function Documentation
ULONG ExComputeTickCountMultiplier (IN ULONG TimeIncrement)
Definition at line 395 of file exinit.c.
References Index.
Referenced by ExpInitializeExecutive().
NTKERNELAPI KPROCESSOR_MODE ExGetPreviousMode (VOID)
Definition at line 526 of file exinit.c.
References KeGetPreviousMode.
VOID ExInitializeSystemLookasideList (IN PGENERAL_LOOKASIDE Lookaside, IN POOL_TYPE Type, IN ULONG Size, IN ULONG Tag, IN USHORT Depth, IN PLIST_ENTRY ListHead)
Definition at line 555 of file exinit.c.
References ExAllocatePoolWithTag, ExFreePool(), ExInitializeSListHead, InsertTailList(), and Tag.
Referenced by CcInitializeCacheManager(), ExpInitSystemPhase0(), ExpInitSystemPhase1(), IoInitSystem(), and ObInitSystem().
VOID ExInitPoolLookasidePointers (VOID)
Definition at line 48 of file exinit.c.
References ExInitializeSListHead, ExpSmallNPagedPoolLookasideLists, ExpSmallPagedPoolLookasideLists, Index, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, _PP_LOOKASIDE_LIST::P, POOL_SMALL_LISTS, _KPRCB::PPNPagedLookasideList, and _KPRCB::PPPagedLookasideList.
Referenced by ExpInitializeExecutive(), and KiInitializeBootStructures().
BOOLEAN ExInitSystem (VOID)
Definition at line 100 of file exinit.c.
References ExpInitSystemPhase0(), ExpInitSystemPhase1(), ExpSystemOK(), FALSE, InitializationPhase, KeBugCheckEx(), TRUE, and UNEXPECTED_INITIALIZATION_CALL.
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
BOOLEAN ExpInitSystemPhase0 (VOID)
Definition at line 137 of file exinit.c.
References ExInitializeFastMutex, ExInitializeResourceLite(), ExInitializeSystemLookasideList(), ExNPagedLookasideListHead, ExNPagedLookasideLock, ExPagedLookasideListHead, ExPagedLookasideLock, ExpEnvironmentLock, ExpFirmwareTableProviderListHead, ExpFirmwareTableResource, ExpKeyManipLock, ExPoolLookasideListHead, ExpResourceInitialization(), ExpSmallNPagedPoolLookasideLists, ExpSmallPagedPoolLookasideLists, ExpSystemOK(), ExSystemLookasideListHead, FALSE, Index, Initialized, InitializeListHead(), KdPrint, KeInitializeSpinLock(), NonPagedPool, PagedPool, POOL_SMALL_LISTS, and TRUE.
Referenced by ExInitSystem().
BOOLEAN ExpInitSystemPhase1 (VOID)
Definition at line 240 of file exinit.c.
References ExAllocatePoolWithTag, ExInitializeSystemLookasideList(), ExpEventInitialization(), ExpEventPairInitialization(), ExpInitializeCallbacks(), ExpInitializePushLocks(), ExpKeyedEventInitialization(), ExpMutantInitialization(), ExPoolLookasideListHead, ExpProfileInitialization(), ExpSemaphoreInitialization(), ExpTimerInitialization(), ExpUuidInitialization(), ExpWin32Initialization(), ExpWorkerInitialization(), FALSE, Index, Initialized, KdPrint, KeNumberProcessors, KiProcessorBlock, List, NonPagedPool, NT_SUCCESS, NULL, _PP_LOOKASIDE_LIST::P, PagedPool, POOL_SMALL_LISTS, _KPRCB::PPNPagedLookasideList, _KPRCB::PPPagedLookasideList, RtlInitializeAtomPackage(), and TRUE.
Referenced by ExInitSystem().
int ExSystemExceptionFilter (VOID)
Definition at line 515 of file exinit.c.
References EXCEPTION_CONTINUE_SEARCH, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, and KernelMode.
Referenced by NtAllocateLocallyUniqueId(), NtAllocateUserPhysicalPages(), NtAllocateUuids(), NtAllocateVirtualMemory(), NtCreateDebugObject(), NtCreateIoCompletion(), NtCreateJobObject(), NtCreateJobSet(), NtCreateKeyedEvent(), NtCreateMutant(), NtCreateThread(), NtDebugContinue(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetNextProcess(), NtGetNextThread(), NtGetWriteWatch(), NtImpersonateThread(), NtLockVirtualMemory(), NtMapViewOfSection(), NtOpenEventPair(), NtOpenIoCompletion(), NtOpenJobObject(), NtOpenKeyedEvent(), NtOpenMutant(), NtQueryInformationJobObject(), NtQueryIoCompletion(), NtQueryMutant(), NtReleaseKeyedEvent(), NtReleaseMutant(), NtReleaseSemaphore(), NtRemoveIoCompletion(), NtSetEvent(), NtSetInformationDebugObject(), NtSetInformationObject(), NtUnlockVirtualMemory(), NtWaitForDebugEvent(), NtWaitForKeyedEvent(), ObpCaptureObjectCreateInformation(), ObpCaptureObjectName(), and SepProbeAndCaptureString_U().
NTSTATUS NtShutdownSystem (__in SHUTDOWN_ACTION Action)
Definition at line 460 of file exinit.c.
References NtSetSystemPowerState(), POWER_ACTION_CRITICAL, POWER_ACTION_DISABLE_WAKES, POWER_ACTION_OVERRIDE_APPS, PowerActionShutdown, PowerActionShutdownOff, PowerActionShutdownReset, PowerSystemSleeping3, ShutdownNoReboot, ShutdownPowerOff, ShutdownReboot, Status, and STATUS_INVALID_PARAMETER.
Variable Documentation
ULONG ExpHydraEnabled
Definition at line 40 of file exinit.c.
ULONG ExpSuiteMask static
Definition at line 41 of file exinit.c.
ULONG ExpTickCountMultiplier
Definition at line 39 of file exinit.c.
Referenced by ExpInitializeExecutive().