Windows Research Kernel v1.2: C:/Windows Research Kernel/ex/sysinfo.c File Reference
sysinfo.c File Reference
#include "exp.h"
#include "stdlib.h"
#include "string.h"
#include "vdmntos.h"
#include <nturtl.h>
#include "pool.h"
#include "stktrace.h"
#include "align.h"
Data Structures
struct _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE
Macros
#define COMPLUS_PACKAGE_ENABLE64BIT L"Enable64Bit"
#define COMPLUS_PACKAGE_INVALID (ULONG)-1
#define COMPLUS_PACKAGE_KEYPATH L"\\Registry\\Machine\\SOFTWARE\\Microsoft\\.NETFramework"
#define ROUND_UP(VALUE, ROUND)
#define WIN32K_FILE_PATH L"\\SystemRoot\\System32\\win32k.sys"
#define WIN32K_PATH_SIZE (sizeof(WIN32K_FILE_PATH) - sizeof(WCHAR))
Typedefs
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE * PSYSTEM_FIRMWARE_TABLE_HANDLER_NODE
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE SYSTEM_FIRMWARE_TABLE_HANDLER_NODE
Functions
NTSTATUS ExGetBigPoolInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
VOID ExGetCurrentProcessorCounts (__out PULONG IdleCount, __out PULONG KernelAndUser, __out PULONG Index)
VOID ExGetCurrentProcessorCpuUsage (__out PULONG CpuUsage)
NTSTATUS ExGetPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
NTSTATUS ExGetSessionPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnedEntries, IN OUT PULONG ActualEntries)
NTSTATUS ExGetSessionPoolTagInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length, IN PULONG SessionId)
BOOLEAN ExIsProcessorFeaturePresent (__in ULONG ProcessorFeature)
NTSTATUS ExLockUserBuffer (__inout_bcount(Length) PVOID Buffer, __in ULONG Length, __in KPROCESSOR_MODE ProbeMode, __in LOCK_OPERATION LockMode, __deref_out PVOID *LockedBuffer, __deref_out PVOID *LockVariable)
VOID ExpCopyProcessInfo (IN PSYSTEM_PROCESS_INFORMATION ProcessInfo, IN PEPROCESS Process, IN BOOLEAN ExtendedInformation)
VOID ExpCopyThreadInfo (IN PVOID ThreadInfoBuffer, IN PETHREAD Thread, IN BOOLEAN ExtendedInformation)
NTSTATUS ExpGetCurrentUserUILanguage (IN WCHAR *ValueName, OUT LANGID *CurrentUserUILanguageId, IN BOOLEAN bCheckGP)
NTSTATUS ExpGetHandleInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTSTATUS ExpGetHandleInformationEx (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTSTATUS ExpGetInstemulInformation (OUT PSYSTEM_VDM_INSTEMUL_INFO Info)
NTSTATUS ExpGetLockInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTSTATUS ExpGetLookasideInformation (OUT PVOID Buffer, IN ULONG BufferLength, OUT PULONG Length)
NTSTATUS ExpGetObjectInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTSTATUS ExpGetProcessInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length OPTIONAL, IN PULONG SessionId OPTIONAL, IN BOOLEAN ExtendedInformation)
NTSTATUS ExpGetProcessorIdleInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTSTATUS ExpGetProcessorPowerInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
NTSTATUS ExpGetSystemBasicInformation (OUT PSYSTEM_BASIC_INFORMATION BasicInfo)
NTSTATUS ExpGetSystemFirmwareTableInformation (IN OUT PVOID SystemFirmwareTableInformation, IN KPROCESSOR_MODE PreviousMode, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS ExpGetSystemProcessorInformation (OUT PSYSTEM_PROCESSOR_INFORMATION ProcessorInformation)
NTSTATUS ExpGetUILanguagePolicy (IN HANDLE CurrentUserKey, OUT LANGID *PolicyUILanguageId)
BOOLEAN ExpIsValidUILanguage (IN WCHAR *pLangId)
NTSTATUS ExpQueryLegacyDriverInformation (IN PSYSTEM_LEGACY_DRIVER_INFORMATION LegacyInfo, IN PULONG Length)
NTSTATUS ExpQueryModuleInformation (IN PLIST_ENTRY LoadOrderListHead, IN PLIST_ENTRY UserModeLoadOrderListHead, OUT PRTL_PROCESS_MODULES ModuleInformation, IN ULONG ModuleInformationLength, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS ExpQueryNumaAvailableMemory (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnedLength)
NTSTATUS ExpQueryNumaProcessorMap (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnedLength)
NTSTATUS ExpReadComPlusPackage (VOID)
NTSTATUS ExpRegisterFirmwareTableInformationHandler (IN OUT PVOID SystemInformation, IN ULONG SystemInformationLength, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS ExpSetCurrentUserUILanguage (IN WCHAR *ValueName, IN LANGID DefaultUILanguageId)
NTSTATUS ExpUpdateComPlusPackage (IN ULONG ComPlusPackageStatus)
NTSTATUS ExpValidateLocale (IN LCID LocaleId)
VOID ExUnlockUserBuffer (__inout PVOID LockVariable)
NTSTATUS NtQueryDefaultLocale (__in BOOLEAN UserProfile, __out PLCID DefaultLocaleId)
NTSTATUS NtQueryDefaultUILanguage (__out LANGID *DefaultUILanguageId)
NTSTATUS NtQueryInstallUILanguage (__out LANGID *InstallUILanguageId)
NTSTATUS NtQuerySystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __out_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtSetDefaultLocale (__in BOOLEAN UserProfile, __in LCID DefaultLocaleId)
NTSTATUS NtSetDefaultUILanguage (__in LANGID DefaultUILanguageId)
NTSTATUS NTAPI NtSetSystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __in_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength)
Variables
POBJECT_TYPE ExEventObjectType
LIST_ENTRY ExpFirmwareTableProviderListHead
ERESOURCE ExpFirmwareTableResource
RTL_TIME_ZONE_INFORMATION ExpTimeZoneInformation
PWD_HANDLER ExpWdHandler = NULL
PVOID ExpWdHandlerContext = NULL
ULONG ExVdmOpcodeDispatchCounts [256]
ULONG ExVdmSegmentNotPresent
static const UNICODE_STRING KeyName = RTL_CONSTANT_STRING(COMPLUS_PACKAGE_KEYPATH)
static UNICODE_STRING KeyValueName = RTL_CONSTANT_STRING(COMPLUS_PACKAGE_ENABLE64BIT)
LIST_ENTRY MmLoadedUserImageList
ULONG MmPagedPoolPage
ULONG MmSystemCachePage
MMSUPPORT MmSystemCacheWs
ULONG MmSystemCodePage
ULONG MmSystemDriverPage
ULONG MmTotalSystemCodePages
LONG MmTotalSystemDriverPages
PFN_NUMBER MmTransitionSharedPages
PFN_NUMBER MmTransitionSharedPagesPeak
ULONG VdmBopCount
WCHAR Win32kFullPath [] = WIN32K_FILE_PATH
Macro Definition Documentation
#define COMPLUS_PACKAGE_ENABLE64BIT L"Enable64Bit"
Definition at line 37 of file sysinfo.c.
#define COMPLUS_PACKAGE_INVALID (ULONG)-1
Definition at line 38 of file sysinfo.c.
Referenced by NtQuerySystemInformation().
#define COMPLUS_PACKAGE_KEYPATH L"\\Registry\\Machine\\SOFTWARE\\Microsoft\\.NETFramework"
Definition at line 36 of file sysinfo.c.
#define ROUND_UP (VALUE, ROUND)
Value:
((ULONG)(((ULONG)VALUE + \
                               ((ULONG)ROUND - 1L)) & (~((ULONG)ROUND - 1L))))
Definition at line 70 of file sysinfo.c.
Referenced by ExpGetProcessInformation().
#define WIN32K_FILE_PATH L"\\SystemRoot\\System32\\win32k.sys"
Definition at line 97 of file sysinfo.c.
#define WIN32K_PATH_SIZE (sizeof(WIN32K_FILE_PATH) - sizeof(WCHAR))
Definition at line 98 of file sysinfo.c.
Referenced by NtSetSystemInformation().
Typedef Documentation
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE * PSYSTEM_FIRMWARE_TABLE_HANDLER_NODE
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE SYSTEM_FIRMWARE_TABLE_HANDLER_NODE
Function Documentation
NTSTATUS ExGetBigPoolInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
Definition at line 5996 of file pool.c.
References ARGUMENT_PRESENT, ASSERT, ExAcquireSpinLockExclusive(), except, EXCEPTION_EXECUTE_HANDLER, ExpLargePoolTableLock, ExReleaseSpinLockExclusive(), FIELD_OFFSET, KeGetCurrentIrql(), _POOL_TRACKER_BIG_PAGES::Key, MiAllocatePoolPages(), MiFreePoolPages(), MmDeterminePoolType(), NonPagedPool, NULL, _POOL_TRACKER_BIG_PAGES::NumberOfPages, PAGE_SHIFT, PASSIVE_LEVEL, POOL_BIG_TABLE_ENTRY_FREE, PoolBigPageTableSize, PROTECTED_POOL, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and _POOL_TRACKER_BIG_PAGES::Va.
Referenced by NtQuerySystemInformation().
VOID ExGetCurrentProcessorCounts (__out PULONG IdleCount, __out PULONG KernelAndUser, __out PULONG Index)
Definition at line 6170 of file sysinfo.c.
References _KPRCB::IdleThread, KeGetCurrentPrcb(), _KPRCB::KernelTime, _KTHREAD::KernelTime, _KPRCB::Number, and _KPRCB::UserTime.
VOID ExGetCurrentProcessorCpuUsage (__out PULONG CpuUsage)
Definition at line 6142 of file sysinfo.c.
References _KPRCB::IdleThread, KeGetCurrentPrcb(), _KPRCB::KernelTime, _KTHREAD::KernelTime, UInt32x32To64, and _KPRCB::UserTime.
NTSTATUS ExGetPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnLength OPTIONAL)
Definition at line 5767 of file pool.c.
References ARGUMENT_PRESENT, ASSERT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExpGetPoolTagInfoTarget(), FIELD_OFFSET, KeGenericCallDpc(), KeGetCurrentIrql(), _POOL_TRACKER_TABLE::Key, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, NonPagedPool, NULL, NumberOfBytes, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, PASSIVE_LEVEL, _POOL_DPC_CONTEXT::PoolTrackTable, _POOL_DPC_CONTEXT::PoolTrackTableExpansion, PoolTrackTableExpansionSize, PoolTrackTableSize, _POOL_DPC_CONTEXT::PoolTrackTableSize, _POOL_DPC_CONTEXT::PoolTrackTableSizeExpansion, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExGetSessionPoolTagInfo (IN PVOID SystemInformation, IN ULONG SystemInformationLength, IN OUT PULONG ReturnedEntries, IN OUT PULONG ActualEntries)
Definition at line 5889 of file pool.c.
References ASSERT, ExpSessionPoolTrackTable, ExpSessionPoolTrackTableSize, KeGetCurrentIrql(), _POOL_TRACKER_TABLE::Key, _POOL_TRACKER_TABLE::NonPagedAllocs, _POOL_TRACKER_TABLE::NonPagedBytes, _POOL_TRACKER_TABLE::NonPagedFrees, _POOL_TRACKER_TABLE::PagedAllocs, _POOL_TRACKER_TABLE::PagedBytes, _POOL_TRACKER_TABLE::PagedFrees, PASSIVE_LEVEL, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by ExGetSessionPoolTagInformation().
NTSTATUS ExGetSessionPoolTagInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length, IN PULONG SessionId OPTIONAL)
Definition at line 4601 of file sysinfo.c.
References Count, ExGetSessionPoolTagInfo(), ExLockUserBuffer(), ExUnlockUserBuffer(), IoWriteAccess, KeGetPreviousMode, MmAttachSession(), MmDetachSession(), MmGetNextSession(), MmGetSessionId(), MmQuitNextSession(), NT_SUCCESS, NULL, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
BOOLEAN ExIsProcessorFeaturePresent (__in ULONG ProcessorFeature)
Definition at line 6047 of file sysinfo.c.
References FALSE, PF_3DNOW_INSTRUCTIONS_AVAILABLE, PF_MMX_INSTRUCTIONS_AVAILABLE, PROCESSOR_FEATURE_MAX, and SharedUserData.
NTSTATUS ExLockUserBuffer (__inout_bcount(Length) PVOID Buffer, __in ULONG Length, __in KPROCESSOR_MODE ProbeMode, __in LOCK_OPERATION LockMode, __deref_out PVOID * LockedBuffer, __deref_out PVOID * LockVariable)
Definition at line 4124 of file sysinfo.c.
References ASSERT, ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExUnlockUserBuffer(), MDL_MAPPING_CAN_FAIL, _MDL::MdlFlags, MmGetSystemAddressForMdl, MmInitializeMdl, MmProbeAndLockPages(), MmSizeOfMdl(), NonPagedPool, NULL, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by ExGetSessionPoolTagInformation(), ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), and MmGetSessionMappedViewInformation().
VOID ExpCopyProcessInfo (IN PSYSTEM_PROCESS_INFORMATION ProcessInfo, IN PEPROCESS Process, IN BOOLEAN ExtendedInformation)
Definition at line 5082 of file sysinfo.c.
References KeQueryValuesProcess(), _KPROCESS_VALUES::KernelTime, MmGetDirectoryFrameFromProcess(), ObGetProcessHandleCount(), _KPROCESS_VALUES::OtherOperationCount, _KPROCESS_VALUES::OtherTransferCount, PAGE_SHIFT, PAGED_CODE, PsNonPagedPool, PsPagedPool, PsPageFile, _KPROCESS_VALUES::ReadOperationCount, _KPROCESS_VALUES::ReadTransferCount, _KPROCESS_VALUES::UserTime, _KPROCESS_VALUES::WriteOperationCount, and _KPROCESS_VALUES::WriteTransferCount.
Referenced by ExpGetProcessInformation().
VOID ExpCopyThreadInfo (IN PVOID ThreadInfoBuffer, IN PETHREAD Thread, IN BOOLEAN ExtendedInformation)
Definition at line 5137 of file sysinfo.c.
References _SYSTEM_THREAD_INFORMATION::BasePriority, _SYSTEM_THREAD_INFORMATION::ClientId, _SYSTEM_THREAD_INFORMATION::ContextSwitches, _SYSTEM_THREAD_INFORMATION::CreateTime, KeMaximumIncrement, _SYSTEM_THREAD_INFORMATION::KernelTime, _SYSTEM_THREAD_INFORMATION::Priority, PS_GET_THREAD_CREATE_TIME, _LARGE_INTEGER::QuadPart, _SYSTEM_EXTENDED_THREAD_INFORMATION::Reserved1, _SYSTEM_EXTENDED_THREAD_INFORMATION::Reserved2, _SYSTEM_EXTENDED_THREAD_INFORMATION::Reserved3, _SYSTEM_EXTENDED_THREAD_INFORMATION::Reserved4, _SYSTEM_EXTENDED_THREAD_INFORMATION::StackBase, _SYSTEM_EXTENDED_THREAD_INFORMATION::StackLimit, _SYSTEM_THREAD_INFORMATION::StartAddress, _SYSTEM_THREAD_INFORMATION::ThreadState, UInt32x32To64, _SYSTEM_THREAD_INFORMATION::UserTime, _SYSTEM_THREAD_INFORMATION::WaitReason, _SYSTEM_THREAD_INFORMATION::WaitTime, and _SYSTEM_EXTENDED_THREAD_INFORMATION::Win32StartAddress.
Referenced by ExpGetProcessInformation().
NTSTATUS ExpGetCurrentUserUILanguage (IN WCHAR * ValueName, OUT LANGID * CurrentUserUILanguageId, IN BOOLEAN bCheckGP)
Definition at line 886 of file sysinfo.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, ExpGetUILanguagePolicy(), ExpIsValidUILanguage(), GENERIC_READ, InitializeObjectAttributes, KEY_ENUMERATE_SUB_KEYS, KeyValueName, KeyValuePartialInformation, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_SZ, RtlInitUnicodeString(), RtlOpenCurrentUser(), RtlUnicodeStringToInteger(), Status, STATUS_UNSUCCESSFUL, _KEY_VALUE_PARTIAL_INFORMATION::Type, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by NtQueryDefaultUILanguage(), and NtSetDefaultUILanguage().
NTSTATUS ExpGetHandleInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 5652 of file sysinfo.c.
References ExLockUserBuffer(), ExUnlockUserBuffer(), IoWriteAccess, KeGetPreviousMode, NT_SUCCESS, ObGetHandleInformation(), PAGED_CODE, Status, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetHandleInformationEx (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 5737 of file sysinfo.c.
References ExLockUserBuffer(), ExUnlockUserBuffer(), IoWriteAccess, KeGetPreviousMode, NT_SUCCESS, ObGetHandleInformationEx(), PAGED_CODE, Status, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetInstemulInformation (OUT PSYSTEM_VDM_INSTEMUL_INFO Info)
Definition at line 5221 of file sysinfo.c.
References _SYSTEM_VDM_INSTEMUL_INFO::BopCount, ExVdmSegmentNotPresent, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeADDR32Prefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeCLI, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeCSPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeDSPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeESPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeFSPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeGSPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeHLT, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINB, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINBimm, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINSB, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINSW, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINTnn, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINTO, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINW, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeINWimm, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeIRET, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeLOCKPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOPER32Prefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOUTB, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOUTBimm, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOUTSB, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOUTSW, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOUTW, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeOUTWimm, _SYSTEM_VDM_INSTEMUL_INFO::OpcodePOPF, _SYSTEM_VDM_INSTEMUL_INFO::OpcodePUSHF, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeREPNEPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeREPPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeSSPrefix, _SYSTEM_VDM_INSTEMUL_INFO::OpcodeSTI, RtlCopyMemory, _SYSTEM_VDM_INSTEMUL_INFO::SegmentNotPresent, STATUS_SUCCESS, VdmBopCount, and _SYSTEM_VDM_INSTEMUL_INFO::VdmOpcode0F.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetLockInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 5344 of file sysinfo.c.
References ExLockUserBuffer(), ExPageLockHandle, ExQuerySystemLockInformation(), ExUnlockUserBuffer(), IoWriteAccess, KeGetPreviousMode, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), NT_SUCCESS, Status, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetLookasideInformation (OUT PVOID Buffer, IN ULONG BufferLength, OUT PULONG Length)
Definition at line 5430 of file sysinfo.c.
References _SYSTEM_LOOKASIDE_INFORMATION::AllocateMisses, CONTAINING_RECORD, _SYSTEM_LOOKASIDE_INFORMATION::CurrentDepth, ExAcquireSpinLock, ExLockUserBuffer(), ExNPagedLookasideListHead, ExNPagedLookasideLock, ExPagedLookasideListHead, ExPagedLookasideLock, ExPoolLookasideListHead, ExQueryDepthSList, ExReleaseSpinLock, ExSystemLookasideListHead, ExUnlockUserBuffer(), _LIST_ENTRY::Flink, _SYSTEM_LOOKASIDE_INFORMATION::FreeMisses, IoWriteAccess, KeGetPreviousMode, _SYSTEM_LOOKASIDE_INFORMATION::MaximumDepth, NT_SUCCESS, _SYSTEM_LOOKASIDE_INFORMATION::Size, Status, STATUS_SUCCESS, _SYSTEM_LOOKASIDE_INFORMATION::Tag, _SYSTEM_LOOKASIDE_INFORMATION::TotalAllocates, _SYSTEM_LOOKASIDE_INFORMATION::TotalFrees, and _SYSTEM_LOOKASIDE_INFORMATION::Type.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetObjectInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 5822 of file sysinfo.c.
References ExLockUserBuffer(), ExUnlockUserBuffer(), IoWriteAccess, KeGetPreviousMode, NT_SUCCESS, ObGetObjectInformation(), PAGED_CODE, Status, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetProcessInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length OPTIONAL, IN PULONG SessionId OPTIONAL, IN BOOLEAN ExtendedInformation)
Definition at line 4230 of file sysinfo.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, CONTAINING_RECORD, ExFreePool(), ExLockUserBuffer(), ExpCopyProcessInfo(), ExpCopyThreadInfo(), ExUnlockUserBuffer(), FALSE, _LIST_ENTRY::Flink, _SYSTEM_PROCESS_INFORMATION::HandleCount, _SYSTEM_PROCESS_INFORMATION::ImageName, IoWriteAccess, IsListEmpty, KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeGetPreviousMode, KeReleaseInStackQueuedSpinLock(), KiLockDispatcherDatabaseAtSynchLevel, KiUnlockDispatcherDatabaseFromSynchLevel, leave, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, MmGetSessionId(), _SYSTEM_PROCESS_INFORMATION::NextEntryOffset, NT_SUCCESS, NULL, _SYSTEM_PROCESS_INFORMATION::NumberOfThreads, PS_PROCESS_FLAGS_PROCESS_EXITING, PsGetNextProcess(), PsIdleProcess, PsQuitNextProcess(), ROUND_UP, RtlCopyMemory, SeLocateProcessImageName(), _SYSTEM_PROCESS_INFORMATION::SessionId, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, strlen(), TRUE, and UNICODE_NULL.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetProcessorIdleInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 4959 of file sysinfo.c.
References _SYSTEM_PROCESSOR_IDLE_INFORMATION::C1Time, _SYSTEM_PROCESSOR_IDLE_INFORMATION::C1Transitions, _SYSTEM_PROCESSOR_IDLE_INFORMATION::C2Time, _SYSTEM_PROCESSOR_IDLE_INFORMATION::C2Transitions, _SYSTEM_PROCESSOR_IDLE_INFORMATION::C3Time, _SYSTEM_PROCESSOR_IDLE_INFORMATION::C3Transitions, DISPATCH_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, ExPageLockHandle, _KPRCB::IdleThread, _SYSTEM_PROCESSOR_IDLE_INFORMATION::IdleTime, KeActiveProcessors, KeGetCurrentPrcb(), KeLowerIrql, KeMaximumIncrement, KeNumberProcessors, KeQueryPerformanceCounter(), KeRaiseIrql, KeRevertToUserAffinityThread(), _KTHREAD::KernelTime, KeSetSystemAffinityThread(), MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), _KPRCB::PowerState, _LARGE_INTEGER::QuadPart, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _PROCESSOR_POWER_STATE::TotalIdleStateTime, _PROCESSOR_POWER_STATE::TotalIdleTransitions, and UInt32x32To64.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetProcessorPowerInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length)
Definition at line 4803 of file sysinfo.c.
References _SYSTEM_PROCESSOR_POWER_INFORMATION::ConstantThrottleFrequency, _SYSTEM_PROCESSOR_POWER_INFORMATION::CurrentFrequency, _SYSTEM_PROCESSOR_POWER_INFORMATION::CurrentFrequencyTime, _SYSTEM_PROCESSOR_POWER_INFORMATION::CurrentProcessorIdleTime, _SYSTEM_PROCESSOR_POWER_INFORMATION::CurrentProcessorTime, _PROCESSOR_POWER_STATE::CurrentThrottle, _SYSTEM_PROCESSOR_POWER_INFORMATION::DegradedThrottleFrequency, _PROCESSOR_POWER_STATE::DemotionCount, _SYSTEM_PROCESSOR_POWER_INFORMATION::DemotionCount, DISPATCH_LEVEL, _PROCESSOR_POWER_STATE::ErrorCount, _SYSTEM_PROCESSOR_POWER_INFORMATION::ErrorCount, except, EXCEPTION_EXECUTE_HANDLER, ExPageLockHandle, _KPRCB::IdleThread, KeActiveProcessors, KeGetCurrentPrcb(), KeLowerIrql, KeMaximumIncrement, KeNumberProcessors, KeRaiseIrql, KeRevertToUserAffinityThread(), _KPRCB::KernelTime, _KTHREAD::KernelTime, KeSetSystemAffinityThread(), _PROCESSOR_POWER_STATE::KneeThrottleIndex, _SYSTEM_PROCESSOR_POWER_INFORMATION::LastAdjustedBusyFrequency, _PROCESSOR_POWER_STATE::LastAdjustedBusyPercentage, _SYSTEM_PROCESSOR_POWER_INFORMATION::LastBusyFrequency, _PROCESSOR_POWER_STATE::LastBusyPercentage, _SYSTEM_PROCESSOR_POWER_INFORMATION::LastC3Frequency, _PROCESSOR_POWER_STATE::LastC3Percentage, _PROCESSOR_POWER_STATE::LastKernelUserTime, _SYSTEM_PROCESSOR_POWER_INFORMATION::LastProcessorIdleTime, _SYSTEM_PROCESSOR_POWER_INFORMATION::LastProcessorTime, MmLockPageableSectionByHandle(), MmUnlockPageableImageSection(), _SYSTEM_PROCESSOR_POWER_INFORMATION::NumberOfFrequencies, PROCESSOR_PERF_STATE::PercentFrequency, _PROCESSOR_POWER_STATE::PerfIdleTime, _PROCESSOR_POWER_STATE::PerfStates, _PROCESSOR_POWER_STATE::PerfStatesCount, _PROCESSOR_POWER_STATE::PerfTickCount, _KPRCB::PowerState, _PROCESSOR_POWER_STATE::ProcessorMaxThrottle, _SYSTEM_PROCESSOR_POWER_INFORMATION::ProcessorMaxThrottle, _PROCESSOR_POWER_STATE::ProcessorMinThrottle, _SYSTEM_PROCESSOR_POWER_INFORMATION::ProcessorMinThrottle, _PROCESSOR_POWER_STATE::PromotionCount, _SYSTEM_PROCESSOR_POWER_INFORMATION::PromotionCount, _PROCESSOR_POWER_STATE::RetryCount, _SYSTEM_PROCESSOR_POWER_INFORMATION::RetryCount, RtlCopyMemory, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _SYSTEM_PROCESSOR_POWER_INFORMATION::ThermalLimitFrequency, _PROCESSOR_POWER_STATE::ThermalThrottleIndex, _PROCESSOR_POWER_STATE::ThrottleLimitIndex, UInt32x32To64, and _KPRCB::UserTime.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetSystemBasicInformation (OUT PSYSTEM_BASIC_INFORMATION BasicInfo)
Definition at line 1302 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeActiveProcessors, KeMaximumIncrement, KeNumberProcessors, MM_ALLOCATION_GRANULARITY, MM_HIGHEST_USER_ADDRESS, MM_LOWEST_USER_ADDRESS, MmHighestPhysicalPage, MmLowestPhysicalPage, MmNumberOfPhysicalPages, PAGE_SIZE, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetSystemFirmwareTableInformation (IN OUT PVOID SystemFirmwareTableInformation, IN KPROCESSOR_MODE PreviousMode, OUT PULONG ReturnLength OPTIONAL)
Definition at line 6286 of file sysinfo.c.
References EX_FOR_EACH_IN_LIST, ExAcquireResourceSharedLite(), ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePoolWithTag, ExReleaseResourceLite(), _SYSTEM_FIRMWARE_TABLE_HANDLER::FirmwareTableHandler, KeEnterCriticalRegion(), KeLeaveCriticalRegion(), KernelMode, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, ProbeForRead, ProbeForWrite(), _SYSTEM_FIRMWARE_TABLE_INFORMATION::ProviderSignature, _SYSTEM_FIRMWARE_TABLE_HANDLER::ProviderSignature, RtlCopyMemory, RtlZeroMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NOT_IMPLEMENTED, _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE::SystemFWHandler, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableBuffer, _SYSTEM_FIRMWARE_TABLE_INFORMATION::TableBufferLength, and TRUE.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetSystemProcessorInformation (OUT PSYSTEM_PROCESSOR_INFORMATION ProcessorInformation)
Definition at line 1330 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeFeatureBits, KeProcessorArchitecture, KeProcessorLevel, KeProcessorRevision, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpGetUILanguagePolicy (IN HANDLE CurrentUserKey, OUT LANGID * PolicyUILanguageId)
Definition at line 734 of file sysinfo.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, ExpIsValidUILanguage(), GENERIC_READ, InitializeObjectAttributes, KeyValueName, KeyValuePartialInformation, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_SZ, RtlInitUnicodeString(), RtlUnicodeStringToInteger(), Status, STATUS_UNSUCCESSFUL, _KEY_VALUE_PARTIAL_INFORMATION::Type, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by ExpGetCurrentUserUILanguage().
BOOLEAN ExpIsValidUILanguage (IN WCHAR * pLangId)
Definition at line 6207 of file sysinfo.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, FALSE, GENERIC_READ, InitializeObjectAttributes, KeyValueName, KeyValuePartialInformation, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_SZ, RtlInitUnicodeString(), Status, TRUE, _KEY_VALUE_PARTIAL_INFORMATION::Type, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by ExpGetCurrentUserUILanguage(), and ExpGetUILanguagePolicy().
NTSTATUS ExpQueryLegacyDriverInformation (IN PSYSTEM_LEGACY_DRIVER_INFORMATION LegacyInfo, IN PULONG Length)
Definition at line 6083 of file sysinfo.c.
References _UNICODE_STRING::Buffer, IoGetLegacyVetoList(), _UNICODE_STRING::Length, NT_SUCCESS, NULL, RtlCopyMemory, RtlInitUnicodeString(), Status, and STATUS_BUFFER_OVERFLOW.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpQueryModuleInformation (IN PLIST_ENTRY LoadOrderListHead, IN PLIST_ENTRY UserModeLoadOrderListHead, OUT PRTL_PROCESS_MODULES ModuleInformation, IN ULONG ModuleInformationLength, OUT PULONG ReturnLength OPTIONAL)
Definition at line 5908 of file sysinfo.c.
References ARGUMENT_PRESENT, _STRING::Buffer, CONTAINING_RECORD, _KLDR_DATA_TABLE_ENTRY::DllBase, FALSE, FIELD_OFFSET, _KLDR_DATA_TABLE_ENTRY::Flags, _RTL_PROCESS_MODULE_INFORMATION::Flags, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, _RTL_PROCESS_MODULE_INFORMATION::FullPathName, _RTL_PROCESS_MODULE_INFORMATION::ImageBase, _RTL_PROCESS_MODULE_INFORMATION::ImageSize, _RTL_PROCESS_MODULE_INFORMATION::InitOrderIndex, _STRING::Length, _KLDR_DATA_TABLE_ENTRY::LoadCount, _RTL_PROCESS_MODULE_INFORMATION::LoadCount, _RTL_PROCESS_MODULE_INFORMATION::LoadOrderIndex, _RTL_PROCESS_MODULE_INFORMATION::MappedBase, _STRING::MaximumLength, NT_SUCCESS, NULL, OBJ_NAME_PATH_SEPARATOR, _RTL_PROCESS_MODULE_INFORMATION::OffsetToFileName, RtlUnicodeStringToAnsiString(), _KLDR_DATA_TABLE_ENTRY::SizeOfImage, Status, STATUS_BUFFER_OVERFLOW, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpQueryNumaAvailableMemory (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnedLength)
Definition at line 1225 of file sysinfo.c.
References _SYSTEM_NUMA_INFORMATION::AvailableMemory, FIELD_OFFSET, FreePageList, _SYSTEM_NUMA_INFORMATION::HighestNodeNumber, KeNodeBlock, KeNumberNodes, MmAvailablePages, PAGE_SHIFT, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and ZeroedPageList.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpQueryNumaProcessorMap (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG ReturnedLength)
Definition at line 1158 of file sysinfo.c.
References _SYSTEM_NUMA_INFORMATION::ActiveProcessorsAffinityMask, FIELD_OFFSET, _SYSTEM_NUMA_INFORMATION::HighestNodeNumber, KeNodeBlock, KeNumberNodes, STATUS_INFO_LENGTH_MISMATCH, and STATUS_SUCCESS.
Referenced by NtQuerySystemInformation().
NTSTATUS ExpReadComPlusPackage (VOID)
Definition at line 344 of file sysinfo.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, GENERIC_READ, KeyValuePartialInformation, NT_SUCCESS, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_DWORD, RTL_CONSTANT_OBJECT_ATTRIBUTES, SharedUserData, Status, _KEY_VALUE_PARTIAL_INFORMATION::Type, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by NtQuerySystemInformation().
NTSTATUS ExpRegisterFirmwareTableInformationHandler (IN OUT PVOID SystemInformation, IN ULONG SystemInformationLength, IN KPROCESSOR_MODE PreviousMode)
Definition at line 6535 of file sysinfo.c.
References _SYSTEM_FIRMWARE_TABLE_HANDLER::DriverObject, EX_FOR_EACH_IN_LIST, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, ExFreePoolWithTag, ExReleaseResourceLite(), FALSE, _SYSTEM_FIRMWARE_TABLE_HANDLER::FirmwareTableHandler, _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE::FirmwareTableProviderList, InitializeListHead(), InsertTailList(), KeEnterCriticalRegion(), KeLeaveCriticalRegion(), KernelMode, NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, PagedPool, _SYSTEM_FIRMWARE_TABLE_HANDLER::ProviderSignature, _SYSTEM_FIRMWARE_TABLE_HANDLER::Register, RemoveEntryList(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_OBJECT_NAME_EXISTS, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _SYSTEM_FIRMWARE_TABLE_HANDLER_NODE::SystemFWHandler, and TRUE.
Referenced by NtSetSystemInformation().
NTSTATUS ExpSetCurrentUserUILanguage (IN WCHAR * ValueName, IN LANGID DefaultUILanguageId)
Definition at line 807 of file sysinfo.c.
References ExpValidateLocale(), GENERIC_WRITE, InitializeObjectAttributes, KEY_ENUMERATE_SUB_KEYS, KeyValueName, MAKELCID, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, REG_SZ, RtlInitUnicodeString(), RtlOpenCurrentUser(), SORT_DEFAULT, Status, STATUS_INVALID_PARAMETER, UNICODE_NULL, ZwClose(), ZwOpenKey(), and ZwSetValueKey().
Referenced by NtSetDefaultUILanguage().
NTSTATUS ExpUpdateComPlusPackage (IN ULONG ComPlusPackageStatus)
Definition at line 403 of file sysinfo.c.
References GENERIC_WRITE, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, REG_DWORD, REG_OPTION_NON_VOLATILE, RTL_CONSTANT_OBJECT_ATTRIBUTES, Status, STATUS_OBJECT_NAME_NOT_FOUND, ZwClose(), ZwCreateKey(), ZwOpenKey(), and ZwSetValueKey().
Referenced by NtSetSystemInformation().
NTSTATUS ExpValidateLocale (IN LCID LocaleId)
Definition at line 989 of file sysinfo.c.
References _UNICODE_STRING::Buffer, _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, GENERIC_READ, InitializeObjectAttributes, KeyValueName, KeyValuePartialInformation, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, REG_SZ, RtlAppendUnicodeToString(), RtlInitUnicodeString(), RtlIntegerToUnicodeString(), Status, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, _KEY_VALUE_PARTIAL_INFORMATION::Type, UNICODE_NULL, ZwClose(), ZwOpenKey(), and ZwQueryValueKey().
Referenced by ExpSetCurrentUserUILanguage(), and NtSetDefaultLocale().
VOID ExUnlockUserBuffer (__inout PVOID LockVariable)
Definition at line 4219 of file sysinfo.c.
References ExFreePool(), and MmUnlockPages().
Referenced by ExGetSessionPoolTagInformation(), ExLockUserBuffer(), ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), and MmGetSessionMappedViewInformation().
NTSTATUS NtQueryDefaultLocale (__in BOOLEAN UserProfile, __out PLCID DefaultLocaleId)
Definition at line 465 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, MmGetSessionLocaleId(), PAGED_CODE, ProbeForWriteUlong, PsDefaultSystemLocaleId, Status, and STATUS_SUCCESS.
NTSTATUS NtQueryDefaultUILanguage (__out LANGID * DefaultUILanguageId)
Definition at line 696 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExpGetCurrentUserUILanguage(), KeGetPreviousMode, KernelMode, NT_SUCCESS, PAGED_CODE, ProbeForWriteUshort, PsInstallUILanguageId, Status, STATUS_SUCCESS, and TRUE.
NTSTATUS NtQueryInstallUILanguage (__out LANGID * InstallUILanguageId)
Definition at line 665 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, PAGED_CODE, ProbeForWriteUshort, PsInstallUILanguageId, Status, and STATUS_SUCCESS.
NTSTATUS NtQuerySystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __out_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength, __out_opt PULONG ReturnLength)
Definition at line 1391 of file sysinfo.c.
References _SYSTEM_EXCEPTION_INFORMATION::AlignmentFixupCount, ARGUMENT_PRESENT, _SYSTEM_PERFORMANCE_INFORMATION::AvailablePagedPoolPages, _SYSTEM_PERFORMANCE_INFORMATION::AvailablePages, _SYSTEM_TIMEOFDAY_INFORMATION::BootTime, _SYSTEM_TIMEOFDAY_INFORMATION::BootTimeBias, _SYSTEM_SESSION_PROCESS_INFORMATION::Buffer, _SYSTEM_EXCEPTION_INFORMATION::ByteWordEmulationCount, _SYSTEM_PERFORMANCE_INFORMATION::CacheIoCount, _SYSTEM_PERFORMANCE_INFORMATION::CacheReadCount, _SYSTEM_PERFORMANCE_INFORMATION::CacheTransitionCount, CcCopyReadNoWait, _KPRCB::CcCopyReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadNoWait, CcCopyReadNoWaitMiss, _KPRCB::CcCopyReadNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadNoWaitMiss, CcCopyReadWait, _KPRCB::CcCopyReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadWait, CcCopyReadWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadWaitMiss, CcDataFlushes, _SYSTEM_PERFORMANCE_INFORMATION::CcDataFlushes, CcDataPages, _SYSTEM_PERFORMANCE_INFORMATION::CcDataPages, CcFastMdlReadNotPossible, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadNotPossible, CcFastMdlReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadNoWait, CcFastMdlReadResourceMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadResourceMiss, CcFastMdlReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadWait, CcFastReadNotPossible, _KPRCB::CcFastReadNotPossible, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadNotPossible, CcFastReadNoWait, _KPRCB::CcFastReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadNoWait, CcFastReadResourceMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadResourceMiss, CcFastReadWait, _KPRCB::CcFastReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadWait, CcLazyWriteIos, _SYSTEM_PERFORMANCE_INFORMATION::CcLazyWriteIos, CcLazyWritePages, _SYSTEM_PERFORMANCE_INFORMATION::CcLazyWritePages, CcLostDelayedWrites, CcMapDataNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataNoWait, CcMapDataNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataNoWaitMiss, CcMapDataWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataWait, CcMapDataWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataWaitMiss, CcMdlReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadNoWait, CcMdlReadNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadNoWaitMiss, CcMdlReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadWait, CcMdlReadWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadWaitMiss, CcPfQueryPrefetcherInformation(), CcPinMappedDataCount, _SYSTEM_PERFORMANCE_INFORMATION::CcPinMappedDataCount, CcPinReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadNoWait, CcPinReadNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadNoWaitMiss, CcPinReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadWait, CcPinReadWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadWaitMiss, CcReadAheadIos, _SYSTEM_PERFORMANCE_INFORMATION::CcReadAheadIos, _CONFIGURATION_INFORMATION::CdRomCount, CmQueryRegistryQuotaInformation(), _SYSTEM_PERFORMANCE_INFORMATION::CommitLimit, _SYSTEM_PERFORMANCE_INFORMATION::CommittedPages, COMPLUS_PACKAGE_INVALID, _SYSTEM_PERFORMANCE_INFORMATION::ContextSwitches, _SYSTEM_PERFORMANCE_INFORMATION::CopyOnWriteCount, _KSERVICE_TABLE_DESCRIPTOR::Count, _SYSTEM_TIMEOFDAY_INFORMATION::CurrentTime, DbgBreakPoint(), DbgPrint(), _SYSTEM_PERFORMANCE_INFORMATION::DemandZeroCount, _SYSTEM_PERFORMANCE_INFORMATION::DirtyPagesWriteCount, _SYSTEM_PERFORMANCE_INFORMATION::DirtyWriteIoCount, _CONFIGURATION_INFORMATION::DiskCount, DPC_NORMAL, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KPRCB::DpcRequestRate, _KPRCB::DpcTime, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::DpcTime, _SYSTEM_QUERY_TIME_ADJUST_INFORMATION::Enable, ExAcquireResourceExclusiveLite(), except, EXCEPTION_EXECUTE_HANDLER, _SYSTEM_EXCEPTION_INFORMATION::ExceptionDispatchCount, ExGetBigPoolInfo(), ExGetPoolTagInfo(), ExGetSessionPoolTagInformation(), ExpCurrentTimeZoneId, ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetInstemulInformation(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpGetSystemBasicInformation(), ExpGetSystemEmulationProcessorInformation(), ExpGetSystemFirmwareTableInformation(), ExpGetSystemProcessorInformation(), ExpQueryLegacyDriverInformation(), ExpQueryModuleInformation(), ExpQueryNumaAvailableMemory(), ExpQueryNumaProcessorMap(), ExpReadComPlusPackage(), ExpTimeZoneBias, ExpWdHandler, ExpWdHandlerContext, ExQueryPoolUsage(), ExRaiseStatus(), ExReleaseResourceLite(), FALSE, _KTHREAD_SWITCH_COUNTERS::FindAny, _KTHREAD_SWITCH_COUNTERS::FindIdeal, _KTHREAD_SWITCH_COUNTERS::FindLast, _SYSTEM_PERFORMANCE_INFORMATION::FirstLevelTbFills, _SYSTEM_EXCEPTION_INFORMATION::FloatingEmulationCount, _CONFIGURATION_INFORMATION::FloppyCount, _SYSTEM_PERFORMANCE_INFORMATION::FreeSystemPtes, _KTHREAD_SWITCH_COUNTERS::IdleAny, _KTHREAD_SWITCH_COUNTERS::IdleCurrent, _KTHREAD_SWITCH_COUNTERS::IdleIdeal, _KTHREAD_SWITCH_COUNTERS::IdleLast, _SYSTEM_PERFORMANCE_INFORMATION::IdleProcessTime, _KPRCB::IdleThread, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::IdleTime, _KPRCB::InterruptCount, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::InterruptCount, _KPRCB::InterruptTime, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::InterruptTime, IoGetConfigurationInformation(), _KPRCB::IoOtherOperationCount, _SYSTEM_PERFORMANCE_INFORMATION::IoOtherOperationCount, IoOtherOperationCount, _KPRCB::IoOtherTransferCount, _SYSTEM_PERFORMANCE_INFORMATION::IoOtherTransferCount, IoOtherTransferCount, _KPRCB::IoReadOperationCount, _SYSTEM_PERFORMANCE_INFORMATION::IoReadOperationCount, IoReadOperationCount, _KPRCB::IoReadTransferCount, _SYSTEM_PERFORMANCE_INFORMATION::IoReadTransferCount, IoReadTransferCount, _KPRCB::IoWriteOperationCount, _SYSTEM_PERFORMANCE_INFORMATION::IoWriteOperationCount, IoWriteOperationCount, _KPRCB::IoWriteTransferCount, _SYSTEM_PERFORMANCE_INFORMATION::IoWriteTransferCount, IoWriteTransferCount, KdDebuggerEnabled, KdDebuggerNotPresent, _KPRCB::KeAlignmentFixupCount, KeBootTime, KeBootTimeBias, KeEnterCriticalRegion(), _KPRCB::KeExceptionDispatchCount, _KPRCB::KeFirstLevelTbFills, _KPRCB::KeFloatingEmulationCount, KeGetContextSwitches(), KeGetPreviousMode, KeGetRecommendedSharedDataAlignment(), KeInterruptTimeBias, KeLeaveCriticalRegion(), KeMaximumIncrement, KeNumberProcessors, KeQueryLogicalProcessorInformation(), KeQueryRuntimeProcess(), KeQuerySystemTime(), _SYSTEM_KERNEL_DEBUGGER_INFORMATION::KernelDebuggerEnabled, _SYSTEM_KERNEL_DEBUGGER_INFORMATION::KernelDebuggerNotPresent, KernelMode, _KPRCB::KernelTime, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::KernelTime, _KTHREAD::KernelTime, _KPRCB::KeSecondLevelTbFills, KeServiceDescriptorTableShadow, _KPRCB::KeSystemCalls, KeThreadSwitchCounters, KeTimeAdjustment, KeTimeIncrement, KeTimeSynchronization, KiAdjustDpcThreshold, KiIdealDpcRate, KiMaximumDpcQueueDepth, KiMinimumDpcRate, KiProcessorBlock, _SYSTEM_CALL_COUNT_INFORMATION::Length, _KSERVICE_TABLE_DESCRIPTOR::Limit, _SYSTEM_PERFORMANCE_INFORMATION::MappedPagesWriteCount, _SYSTEM_PERFORMANCE_INFORMATION::MappedWriteIoCount, MmAvailablePages, MmAvailablePoolInPages(), _KPRCB::MmCacheIoCount, _KPRCB::MmCacheReadCount, _KPRCB::MmCacheTransitionCount, _KPRCB::MmCopyOnWriteCount, _KPRCB::MmDemandZeroCount, _KPRCB::MmDirtyPagesWriteCount, _KPRCB::MmDirtyWriteIoCount, MmGetNumberOfFreeSystemPtes(), MmGetPageFileInformation(), MmGetSessionMappedViewInformation(), MmGetVerifierInformation(), _KPRCB::MmMappedPagesWriteCount, _KPRCB::MmMappedWriteIoCount, MmMemoryUsage(), MmPagedPoolPage, _KPRCB::MmPageFaultCount, _KPRCB::MmPageReadCount, _KPRCB::MmPageReadIoCount, MmPeakCommitment, MmQuerySystemCacheWorkingSetInformation(), MmSystemCachePage, MmSystemCodePage, MmSystemDriverPage, MmSystemRangeStart, MmTotalCommitLimit, MmTotalCommittedPages, MmTotalSystemCodePages, MmTotalSystemDriverPages, _KPRCB::MmTransitionCount, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolAllocs, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolFrees, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolLookasideHits, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolPages, NT_SUCCESS, NtGlobalFlag, NULL, NUMBER_SERVICE_TABLES, _SYSTEM_DEVICE_INFORMATION::NumberOfCdRoms, _SYSTEM_DEVICE_INFORMATION::NumberOfDisks, _SYSTEM_DEVICE_INFORMATION::NumberOfFloppies, _SYSTEM_DEVICE_INFORMATION::NumberOfParallelPorts, _SYSTEM_DEVICE_INFORMATION::NumberOfSerialPorts, _SYSTEM_CALL_COUNT_INFORMATION::NumberOfTables, _SYSTEM_DEVICE_INFORMATION::NumberOfTapes, ObGetSecurityMode(), PAGED_CODE, PagedPool, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolAllocs, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolFrees, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolLookasideHits, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolPages, _SYSTEM_PERFORMANCE_INFORMATION::PageFaultCount, _SYSTEM_PERFORMANCE_INFORMATION::PageReadCount, _SYSTEM_PERFORMANCE_INFORMATION::PageReadIoCount, _CONFIGURATION_INFORMATION::ParallelCount, _EPROCESS::Pcb, _SYSTEM_PERFORMANCE_INFORMATION::PeakCommitment, POINTER_IS_ALIGNED, _KTHREAD_SWITCH_COUNTERS::PreemptAny, _KTHREAD_SWITCH_COUNTERS::PreemptCurrent, _KTHREAD_SWITCH_COUNTERS::PreemptLast, ProbeForWrite(), ProbeForWriteUlong, PsIdleProcess, PsLoadedModuleList, PsLoadedModuleResource, _LARGE_INTEGER::QuadPart, _SYSTEM_PERFORMANCE_INFORMATION::ResidentPagedPoolPage, _SYSTEM_PERFORMANCE_INFORMATION::ResidentSystemCachePage, _SYSTEM_PERFORMANCE_INFORMATION::ResidentSystemCodePage, _SYSTEM_PERFORMANCE_INFORMATION::ResidentSystemDriverPage, RtlCopyMemory, RtlZeroMemory, _SYSTEM_PERFORMANCE_INFORMATION::SecondLevelTbFills, _CONFIGURATION_INFORMATION::SerialCount, _SYSTEM_SESSION_PROCESS_INFORMATION::SessionId, SharedUserData, _SYSTEM_SESSION_PROCESS_INFORMATION::SizeOfBuf, _SYSTEM_TIMEOFDAY_INFORMATION::SleepTimeBias, Status, STATUS_DATATYPE_MISALIGNMENT, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, _KTHREAD_SWITCH_COUNTERS::SwitchToIdle, SystemBasicInformation, SystemBigPoolInformation, SystemCallCountInformation, _SYSTEM_PERFORMANCE_INFORMATION::SystemCalls, SystemCallTimeInformation, SystemComPlusPackage, SystemContextSwitchInformation, SystemCurrentTimeZoneInformation, SystemDeviceInformation, SystemDpcBehaviorInformation, SystemEmulationBasicInformation, SystemEmulationProcessorInformation, SystemExceptionInformation, SystemExtendedHandleInformation, SystemExtendedProcessInformation, SystemFileCacheInformation, SystemFileCacheInformationEx, SystemFirmwareTableInformation, SystemFlagsInformation, SystemFullMemoryInformation, SystemHandleInformation, SystemInterruptInformation, SystemKernelDebuggerInformation, SystemLegacyDriverInformation, SystemLocksInformation, SystemLogicalProcessorInformation, SystemLookasideInformation, SystemLostDelayedWriteInformation, SystemModuleInformation, SystemNonPagedPoolInformation, SystemNumaAvailableMemory, SystemNumaProcessorMap, SystemObjectInformation, SystemObjectSecurityMode, SystemPagedPoolInformation, SystemPageFileInformation, SystemPathInformation, SystemPerformanceInformation, SystemPerformanceTraceInformation, SystemPoolTagInformation, SystemPrefetcherInformation, SystemProcessInformation, SystemProcessorIdleInformation, SystemProcessorInformation, SystemProcessorPerformanceInformation, SystemProcessorPowerInformation, SystemRangeStartInformation, SystemRecommendedSharedDataAlignment, SystemRegistryQuotaInformation, SystemSessionMappedViewInformation, SystemSessionPoolTagInformation, SystemSessionProcessInformation, SystemStackTraceInformation, SystemSummaryMemoryInformation, SystemTimeAdjustmentInformation, SystemTimeOfDayInformation, SystemVdmInstemulInformation, SystemVerifierInformation, SystemWatchdogTimerInformation, _CONFIGURATION_INFORMATION::TapeCount, _SYSTEM_QUERY_TIME_ADJUST_INFORMATION::TimeAdjustment, _SYSTEM_QUERY_TIME_ADJUST_INFORMATION::TimeIncrement, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneBias, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneId, _SYSTEM_PERFORMANCE_INFORMATION::TotalSystemCodePages, _SYSTEM_PERFORMANCE_INFORMATION::TotalSystemDriverPages, _SYSTEM_PERFORMANCE_INFORMATION::TransitionCount, TRUE, TYPE_ALIGNMENT, UInt32x32To64, _KPRCB::UserTime, and _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::UserTime.
NTSTATUS NtSetDefaultLocale (__in BOOLEAN UserProfile, __in LCID DefaultLocaleId)
Definition at line 502 of file sysinfo.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, ExpValidateLocale(), GENERIC_READ, GENERIC_WRITE, InitializeObjectAttributes, KEY_ENUMERATE_SUB_KEYS, KeyValueName, KeyValuePartialInformation, MmSetSessionLocaleId(), NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, PsDefaultSystemLocaleId, REG_DWORD, REG_SZ, RtlInitUnicodeString(), RtlOpenCurrentUser(), Status, STATUS_INVALID_PARAMETER, STATUS_UNSUCCESSFUL, _KEY_VALUE_PARTIAL_INFORMATION::Type, UNICODE_NULL, ZwClose(), ZwOpenKey(), ZwQueryValueKey(), and ZwSetValueKey().
NTSTATUS NtSetDefaultUILanguage (__in LANGID DefaultUILanguageId)
Definition at line 962 of file sysinfo.c.
References ExpGetCurrentUserUILanguage(), ExpSetCurrentUserUILanguage(), FALSE, NT_SUCCESS, and Status.
NTSTATUS NTAPI NtSetSystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __in_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength)
Definition at line 3068 of file sysinfo.c.
References _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _UNICODE_STRING::Buffer, CcPfSetPrefetcherInformation(), CmSetRegistryQuotaInformation(), CrashDumpReconfigure, _DRIVER_OBJECT::DriverStart, _SYSTEM_SET_TIME_ADJUST_INFORMATION::Enable, _SYSTEM_GDI_DRIVER_INFORMATION::EntryPoint, EVENT_MODIFY_STATE, ExAllocatePoolWithTag, ExApplyCodePatch(), except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _SYSTEM_GDI_DRIVER_INFORMATION::ExportSectionPointer, ExpRegisterFirmwareTableInformationHandler(), ExpUpdateComPlusPackage(), ExpWdHandler, ExpWdHandlerContext, ExRaiseStatus(), FALSE, FLG_BOOTONLY_VALID_BITS, FLG_KERNELMODE_VALID_BITS, IMAGE_DIRECTORY_ENTRY_EXPORT, _SYSTEM_GDI_DRIVER_INFORMATION::ImageAddress, _SYSTEM_GDI_DRIVER_INFORMATION::ImageLength, IoConfigureCrashDump(), KdUpdateTimeSlipEvent(), KeGetCurrentIrql(), KeGetPreviousMode, KeMaximumIncrement, KernelMode, KeTimeAdjustment, KeTimeSynchronization, KiAdjustDpcThreshold, KiIdealDpcRate, KiMaximumDpcQueueDepth, KiMinimumDpcRate, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, memcmp(), MM_LOAD_IMAGE_IN_SESSION, MmAddVerifierEntry(), MmAddVerifierThunks(), MmAdjustWorkingSetSizeEx(), MmCreateMirror(), MmIsSessionLeaderProcess, MmLoadSystemImage(), MmRemoveVerifierEntry(), MmSessionCreate(), MmSessionDelete(), MmSessionSetUnloadAddress(), MmSetVerifierInformation(), MmUnloadSystemImage(), NT_SUCCESS, NtGlobalFlag, NULL, ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteUlong, PsChangeQuantumTable(), PsGetCurrentProcess(), RtlCopyMemory, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), RtlZeroMemory, _SYSTEM_GDI_DRIVER_INFORMATION::SectionPointer, SeDebugPrivilege, SeIncreaseQuotaPrivilege, SeLoadDriverPrivilege, SeSinglePrivilegeCheck(), SeSystemtimePrivilege, SeTcbPrivilege, SharedNtdll32ExpInterlockedPopEntrySListEnd, SharedNtdll32ExpInterlockedPopEntrySListFault, SharedNtdll32ExpInterlockedPopEntrySListResume, SharedUserData, _IMAGE_OPTIONAL_HEADER::SizeOfImage, Status, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_NOT_IMPLEMENTED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, SystemComPlusPackage, SystemCrashDumpStateInformation, SystemDpcBehaviorInformation, SystemExtendServiceTableInformation, SystemFileCacheInformation, SystemFileCacheInformationEx, SystemFlagsInformation, SystemHotpatchInformation, SystemLoadGdiDriverInformation, SystemLoadGdiDriverInSystemSpace, SystemMirrorMemoryInformation, SystemPerformanceTraceInformation, SystemPrefetcherInformation, SystemPrioritySeperation, SystemRegisterFirmwareTableInformationHandler, SystemRegistryQuotaInformation, SystemSessionCreate, SystemSessionDetach, SystemTimeAdjustmentInformation, SystemTimeSlipNotification, SystemUnloadGdiDriverInformation, SystemVerifierAddDriverInformation, SystemVerifierInformation, SystemVerifierRemoveDriverInformation, SystemVerifierThunkExtend, SystemWatchdogTimerHandler, SystemWatchdogTimerInformation, SystemWow64SharedInformation, _SYSTEM_SET_TIME_ADJUST_INFORMATION::TimeAdjustment, TRUE, UlongToPtr, UserMode, WIN32K_PATH_SIZE, Win32kFullPath, and ZwSetSystemInformation().
Referenced by WmipRegisterFirmwareProviders().
Variable Documentation
POBJECT_TYPE ExEventObjectType
Definition at line 32 of file event.c.
LIST_ENTRY ExpFirmwareTableProviderListHead
Definition at line 106 of file sysinfo.c.
Referenced by ExpInitSystemPhase0().
ERESOURCE ExpFirmwareTableResource
Definition at line 112 of file sysinfo.c.
Referenced by ExpInitSystemPhase0().
RTL_TIME_ZONE_INFORMATION ExpTimeZoneInformation
PWD_HANDLER ExpWdHandler = NULL
Definition at line 83 of file sysinfo.c.
Referenced by KeBugCheck2(), NtQuerySystemInformation(), and NtSetSystemInformation().
PVOID ExpWdHandlerContext = NULL
Definition at line 84 of file sysinfo.c.
Referenced by KeBugCheck2(), NtQuerySystemInformation(), and NtSetSystemInformation().
ULONG ExVdmOpcodeDispatchCounts[256]
ULONG ExVdmSegmentNotPresent
Referenced by ExpGetInstemulInformation().
const UNICODE_STRING KeyName = RTL_CONSTANT_STRING(COMPLUS_PACKAGE_KEYPATH) static
Definition at line 90 of file sysinfo.c.
Referenced by CmpCacheLookup(), CmpCopySyncTree2(), CmpCreateKeyControlBlock(), CmpDoCompareKeyName(), CmpFindProfileOption(), CmpInitializeRegistryNode(), CmpLinkKeyToHive(), CmpNotifyChangeKey(), CmpWmiDumpKcb(), CmpWmiDumpKcbTable(), ExpUuidLoadSequenceNumber(), ExpUuidSaveSequenceNumber(), FsRtlGetCompatibilityModeValue(), FsRtlGetTunnelParameterValue(), IopBootLog(), IopCopyBootLogRegistryToFile(), KiMoveRegTree(), SepAdtInitializePrivilegeAuditing(), and SepAuditFailed().
UNICODE_STRING KeyValueName = RTL_CONSTANT_STRING(COMPLUS_PACKAGE_ENABLE64BIT) static
Definition at line 91 of file sysinfo.c.
Referenced by ExpGetCurrentUserUILanguage(), ExpGetUILanguagePolicy(), ExpIsValidUILanguage(), ExpSetCurrentUserUILanguage(), ExpValidateLocale(), NtSetDefaultLocale(), RtlDeleteRegistryValue(), RtlQueryRegistryValues(), and RtlWriteRegistryValue().
LIST_ENTRY MmLoadedUserImageList
Definition at line 228 of file mminit.c.
ULONG MmPagedPoolPage
Definition at line 26 of file wslist.c.
Referenced by NtQuerySystemInformation().
ULONG MmSystemCachePage
Definition at line 25 of file wslist.c.
Referenced by NtQuerySystemInformation().
MMSUPPORT MmSystemCacheWs
Definition at line 318 of file miglobal.c.
Referenced by CcInitializeCacheManager(), MiAddValidPageToWorkingSet(), MiAllocateWsle(), MiAttachAndLockWorkingSet(), MiDeleteSystemPageableVm(), MiDetachAndUnlockWorkingSet(), MiDetermineTrimAmount(), MiEliminateWorkingSetEntry(), MiEnsureAvailablePageOrWait(), MiFreeWsle(), MiFreeWsleList(), MiInitializeSystemCache(), MiLockCode(), MiMakeSystemAddressValidPfnSystemWs(), MiProcessWorkingSets(), MiRemoveWorkingSetPages(), MiSetPagingOfDriver(), MiSetSystemCodeProtection(), MiTrimAllSystemPageableMemory(), MiUnmapViewInSystemSpace(), MmAccessFault(), MmAdjustWorkingSetSizeEx(), MmCheckCachedPageState(), MmCopyToCachedPage(), MmInitSystem(), MmQuerySystemCacheWorkingSetInformation(), and MmUnmapViewInSystemCache().
ULONG MmSystemCodePage
Definition at line 24 of file wslist.c.
Referenced by NtQuerySystemInformation().
ULONG MmSystemDriverPage
Definition at line 27 of file wslist.c.
Referenced by NtQuerySystemInformation().
ULONG MmTotalSystemCodePages
Definition at line 218 of file mminit.c.
Referenced by MiEnablePagingOfDriverAtInit(), and NtQuerySystemInformation().
LONG MmTotalSystemDriverPages
Definition at line 24 of file sysload.c.
Referenced by NtQuerySystemInformation().
PFN_NUMBER MmTransitionSharedPages
Definition at line 35 of file pfnlist.c.
PFN_NUMBER MmTransitionSharedPagesPeak
Definition at line 35 of file wslist.c.
Referenced by MiAllocateWsle(), and MmQuerySystemCacheWorkingSetInformation().
ULONG VdmBopCount
Referenced by ExpGetInstemulInformation().
WCHAR Win32kFullPath[] = WIN32K_FILE_PATH
Definition at line 100 of file sysinfo.c.
Referenced by NtSetSystemInformation().