Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/pagfault.c File Reference
pagfault.c File Reference
#include "mi.h"
Macros
#define MI_PROTOTYPE_WSINDEX ((ULONG)-1)
#define STATUS_PTE_CHANGED 0x87303000
#define STATUS_REFAULT 0xC7303001
#define VARIOUS_FLAGS_ACCESS_CHECK_NEEDED 0x04
#define VARIOUS_FLAGS_DIRTY_PTE 0x01
#define VARIOUS_FLAGS_ENTERED_CRITICAL_REGION 0x10
#define VARIOUS_FLAGS_LOG_HARD_FAULT 0x08
#define VARIOUS_FLAGS_PFN_HELD 0x02
Functions
WSLE_NUMBER MiAddValidPageToWorkingSet (IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN ULONG WsleMask)
NTSTATUS FASTCALL MiCheckPdeForPagedPool (IN PVOID VirtualAddress)
NTSTATUS FASTCALL MiCheckPdeForSessionSpace (IN PVOID VirtualAddress)
PMMPTE MiCheckVirtualAddress (IN PVOID VirtualAddress, OUT PULONG ProtectCode, OUT PMMVAD *VadOut)
NTSTATUS MiCompleteProtoPteFault (IN ULONG_PTR StoreInstruction, IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN KIRQL OldIrql, IN OUT PMMPFN *LockedProtoPfn)
NTSTATUS MiDispatchFault (IN ULONG_PTR FaultStatus, IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN LOGICAL RecheckAccess, IN PEPROCESS Process, IN PVOID TrapInformation, IN PMMVAD Vad)
PMMPTE MiFindActualFaultingPte (IN PVOID FaultingAddress)
VOID MiFreeInPageSupportBlock (IN PMMINPAGE_SUPPORT Support)
PMMINPAGE_SUPPORT MiGetInPageSupportBlock (IN KIRQL OldIrql, OUT PNTSTATUS Status)
VOID MiHandleBankedSection (IN PVOID VirtualAddress, IN PMMVAD Vad)
VOID MiInitializeCopyOnWritePfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN WSLE_NUMBER WorkingSetIndex, IN PMMWSL WorkingSetList)
VOID MiInitializePfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN ULONG ModifiedState)
VOID MiInitializePfnAndMakePteValid (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN MMPTE NewPteContents)
VOID MiInitializePfnForOtherProcess (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN PFN_NUMBER ContainingPageFrame)
VOID MiInitializeReadInProgressPfn (IN PMDL Mdl, IN PMMPTE BasePte, IN PKEVENT Event, IN WSLE_NUMBER WorkingSetIndex)
VOID MiInitializeReadInProgressSinglePfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE BasePte, IN PKEVENT Event, IN WSLE_NUMBER WorkingSetIndex)
VOID MiInitializeTransitionPfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte)
BOOLEAN MiIsAddressValid (IN PVOID VirtualAddress, IN LOGICAL UseForceIfPossible)
NTSTATUS MiResolveDemandZeroFault (IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PEPROCESS Process, IN KIRQL OldIrql)
NTSTATUS MiResolveMappedFileFault (IN PMMPTE PointerPte, IN PMMINPAGE_SUPPORT *ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
NTSTATUS MiResolveMappedFileFault (IN PMMPTE PointerPte, OUT PMMINPAGE_SUPPORT *ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
NTSTATUS MiResolvePageFileFault (IN PVOID FaultingAddress, IN PMMPTE PointerPte, OUT PMMPTE CapturedPteContents, IN PMMINPAGE_SUPPORT *ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
NTSTATUS MiResolvePageFileFault (IN PVOID FaultingAddress, IN PMMPTE PointerPte, OUT PMMPTE CapturedPteContents, OUT PMMINPAGE_SUPPORT *ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
NTSTATUS MiResolveProtoPteFault (IN ULONG_PTR StoreInstruction, IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN OUT PMMPFN *LockedProtoPfn, IN PMMINPAGE_SUPPORT *ReadBlock, OUT PMMPTE CapturedPteContents, IN PEPROCESS Process, IN KIRQL OldIrql, IN PVOID TrapInformation)
NTSTATUS MiResolveProtoPteFault (IN ULONG_PTR StoreInstruction, IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN OUT PMMPFN *LockedProtoPfn, OUT PMMINPAGE_SUPPORT *ReadBlock, OUT PMMPTE CapturedPteContents, IN PEPROCESS Process, IN KIRQL OldIrql, IN PVOID TrapInformation)
NTSTATUS MiResolveTransitionFault (IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN PEPROCESS Process, IN KIRQL OldIrql, OUT PMMINPAGE_SUPPORT *InPageBlock)
VOID MiTrimPte (IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN PEPROCESS CurrentProcess, IN MMPTE NewPteContents)
NTSTATUS MiWaitForInPageComplete (IN PMMPFN Pfn2, IN PMMPTE PointerPte, IN PVOID FaultingAddress, IN PMMPTE PointerPteContents, IN PMMINPAGE_SUPPORT InPageSupport, IN PEPROCESS CurrentProcess)
BOOLEAN MmIsAddressValid (__in PVOID VirtualAddress)
Variables
ULONG MiFaultRetries
ULONG MiInPageSinglePages
ULONG MiUserFaultRetries
ULONG MmClusterPageFileReads
ULONG MmInPageSupportMinimum = 4
ULONG MmMaxTransitionCluster = 8
PMMPTE MmSharedUserDataPte
PVOID MmSpecialPoolEnd
PVOID MmSpecialPoolStart
Macro Definition Documentation
#define MI_PROTOTYPE_WSINDEX ((ULONG)-1)
Definition at line 37 of file pagfault.c.
Referenced by MiInitializeReadInProgressPfn(), MiInitializeReadInProgressSinglePfn(), MiResolveMappedFileFault(), and MiResolvePageFileFault().
#define STATUS_PTE_CHANGED 0x87303000
Definition at line 20 of file pagfault.c.
Referenced by MiDispatchFault(), and MiWaitForInPageComplete().
#define STATUS_REFAULT 0xC7303001
Definition at line 21 of file pagfault.c.
Referenced by MiDispatchFault(), MiGetInPageSupportBlock(), MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveTransitionFault(), and MiWaitForInPageComplete().
#define VARIOUS_FLAGS_ACCESS_CHECK_NEEDED 0x04
Referenced by MiDispatchFault().
#define VARIOUS_FLAGS_DIRTY_PTE 0x01
Referenced by MiDispatchFault().
#define VARIOUS_FLAGS_ENTERED_CRITICAL_REGION 0x10
Referenced by MiDispatchFault().
#define VARIOUS_FLAGS_LOG_HARD_FAULT 0x08
Referenced by MiDispatchFault().
#define VARIOUS_FLAGS_PFN_HELD 0x02
Referenced by MiDispatchFault().
Function Documentation
WSLE_NUMBER MiAddValidPageToWorkingSet (IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN ULONG WsleMask)
Definition at line 6283 of file pagfault.c.
References ASSERT, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_PROCESS_SPACE_ADDRESS, MI_IS_SESSION_ADDRESS, MI_IS_SESSION_PTE, MiAllocateWsle(), MmSessionSpace, MmSystemCacheWs, PsGetCurrentProcess(), UNREFERENCED_PARAMETER, _EPROCESS::Vm, and _MM_SESSION_SPACE::Vm.
Referenced by MiCloneProcessAddressSpace(), MiCompleteProtoPteFault(), MiDispatchFault(), MiResolveDemandZeroFault(), MiResolveTransitionFault(), and MiSessionCommitPageTables().
NTSTATUS FASTCALL MiCheckPdeForPagedPool (IN PVOID VirtualAddress)
Definition at line 4935 of file pagfault.c.
References _MMPTE::Hard, InterlockedExchangePte, _MMPTE::Long, MI_IS_KERNEL_PAGE_TABLE_ADDRESS, MI_IS_SESSION_ADDRESS, MI_IS_SESSION_PTE, MiCheckPdeForSessionSpace(), MiGetPdeAddress, MiGetPteAddress, MmSystemPagePtes, MmSystemRangeStart, PD_PER_SYSTEM, PDE_PER_PAGE, STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, STATUS_WAIT_1, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiCheckProtoPtePageState(), MiCloneProcessAddressSpace(), MiDeletePte(), MiDeleteSystemPageableVm(), MiEliminateWorkingSetEntry(), MiFreeWsleList(), MiHandleForkTransitionPte(), MiInitializeCopyOnWritePfn(), MiInitializePfn(), MiInitializePfnAndMakePteValid(), MiInitializeReadInProgressPfn(), MiInitializeReadInProgressSinglePfn(), MiInitializeTransitionPfn(), MiSwapWslEntries(), MiTrimPte(), MiUpdateLargeProtoPfns(), and MmAccessFault().
NTSTATUS FASTCALL MiCheckPdeForSessionSpace (IN PVOID VirtualAddress)
Definition at line 5032 of file pagfault.c.
References DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, FALSE, _MMPTE::Hard, Index, InterlockedExchangePte, _MMPTE::Long, MI_IS_SESSION_ADDRESS, MI_IS_SESSION_PTE, MiGetPdeAddress, MiGetPdeSessionIndex, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MmSessionSpace, _MM_SESSION_SPACE::PageTables, STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, STATUS_WAIT_1, TRUE, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiCheckPdeForPagedPool(), and MmAccessFault().
PMMPTE MiCheckVirtualAddress (IN PVOID VirtualAddress, OUT PULONG ProtectCode, OUT PMMVAD * VadOut)
Definition at line 4701 of file pagfault.c.
References _IMAGE_ENTRY_IN_SESSION::Address, CONTAINING_RECORD, _MMVAD_FLAGS2::ExtendableFile, _LIST_ENTRY::Flink, _MM_SESSION_SPACE::ImageList, _MM_PAGED_POOL_INFO::LastPteForPagedPool, _MMVAD_FLAGS::MemCommit, MI_GET_PROTECTION_FROM_VAD, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_SESSION_ADDRESS, MI_VA_TO_VPN, MiGetProtoPteAddress, MiGetPteAddress, MiHandleBankedSection(), MiLocateAddress(), MM_EXECUTE_WRITECOPY, MM_HIGHEST_USER_ADDRESS, MM_NOACCESS, MM_PAGED_POOL_START, MM_READONLY, MM_READWRITE, MM_SESSION_SPACE_WS_LOCK_ASSERT, MM_SHARED_USER_DATA_VA, MM_UNKNOWN_PROTECTION, MmPagedPoolInfo, MmSessionSpace, MmSharedUserDataPte, NULL, PAGE_ALIGN, PAGE_SHIFT, _MMVAD_FLAGS::PrivateMemory, _IMAGE_ENTRY_IN_SESSION::PrototypePtes, _MMVAD::StartingVpn, TRUE, _MMVAD::u, _MMVAD::u2, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD::VadFlags2, VadImageMap, and _MMVAD_FLAGS::VadType.
Referenced by MiFindActualFaultingPte(), MiWaitForInPageComplete(), and MmAccessFault().
NTSTATUS MiCompleteProtoPteFault (IN ULONG_PTR StoreInstruction, IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN KIRQL OldIrql, IN OUT PMMPFN * LockedProtoPfn)
Definition at line 3397 of file pagfault.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, CCPF_IS_PREFETCHER_ACTIVE, CCPF_TYPE_IMAGE, CCPF_TYPE_ROM, CcPfLogPageFault(), _SUBSECTION::ControlArea, DbgBreakPoint(), DbgPrintEx(), _CONTROL_AREA::DereferenceList, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMWSLE::e1, FALSE, FileOffset, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, GET_PAGING_FILE_OFFSET, _MMPTE::Hard, HYDRA_PROCESS, _MMSECTION_FLAGS::Image, _MMPTE::Long, _MMWSLE::Long, MI_ASSERT_NOT_SESSION_DATA, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_GET_PROTECTION_FROM_WSLE, MI_IS_SESSION_ADDRESS, MI_IS_SESSION_PTE, MI_MAKE_VALID_PTE, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MI_SET_PTE_DIRTY, MI_SNAP_DATA, MI_WRITE_VALID_PTE, MiAddValidPageToWorkingSet(), MiCached, MiGetPteAddress, MiGetSubsectionAddress, MiNonCached, MiProtoAddressForPte, MiReleaseConfirmedPageFileSpace(), MiStartingOffset(), MiTrimPte(), MiWriteCombined, MM_COPY_ON_WRITE_MASK, MM_NOCACHE, MM_PFN_LOCK_ASSERT, MM_PROTECTION_WRITE_MASK, MM_WRITECOMBINE, MM_ZERO_ACCESS, MmSystemRangeStart, NOTHING, NULL, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE::Proto, _MMPTE_SOFTWARE::Prototype, _MMPTE_PROTOTYPE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMSECTION_FLAGS::Rom, _MMPFN::ShareCount, _MMPTE::Soft, Status, STATUS_NO_MEMORY, STATUS_SUCCESS, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, and _MMPFNENTRY::WriteInProgress.
Referenced by MiDispatchFault(), and MiResolveProtoPteFault().
NTSTATUS MiDispatchFault (IN ULONG_PTR FaultStatus, IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN LOGICAL RecheckAccess, IN PEPROCESS Process, IN PVOID TrapInformation, IN PMMVAD Vad)
Definition at line 100 of file pagfault.c.
References ActiveAndValid, _ETHREAD::ActiveFaultCount, APC_LEVEL, ASSERT, _MMINPAGE_SUPPORT::BasePte, BYTE_OFFSET, _PERFINFO_HARDPAGEFAULT_INFORMATION::ByteCount, _MDL::ByteCount, _MMPFNENTRY::CacheAttribute, CCPF_IS_PREFETCHER_ACTIVE, CCPF_TYPE_ROM, CcPfLogPageFault(), _ETHREAD::Cid, _SUBSECTION::ControlArea, _MMPTE_HARDWARE::CopyOnWrite, DbgBreakPoint(), DbgPrintEx(), _CONTROL_AREA::DereferenceList, DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMWSLE::e1, _MMINPAGE_SUPPORT::e1, _MMPFN::e2, _MMPFN::Event, _MMINPAGE_SUPPORT::Event, FALSE, _PERFINFO_HARDPAGEFAULT_INFORMATION::FileObject, FileOffset, _CONTROL_AREA::FilePointer, _MMINPAGE_SUPPORT::FilePointer, _MMCLONE_DESCRIPTOR::FinalNumberOfReferences, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, FreePageList, GET_PAGING_FILE_OFFSET, _MM_SESSION_SPACE::GlobalVirtualAddress, HandleToUlong, _MMPTE::Hard, HYDRA_PROCESS, _MMSECTION_FLAGS::Image, _IO_STATUS_BLOCK::Information, _MMPFN::InPageError, InterlockedExchangeAdd(), InterlockedIncrementPfn, IoPageRead(), _MMINPAGE_SUPPORT::IoStatus, _PERFINFO_HARDPAGEFAULT_INFORMATION::IoTime, KeAreAllApcsDisabled(), KeEnterCriticalRegionThread(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeLeaveCriticalRegionThread(), KernelMode, KeSetEvent(), LOCK_PFN, LOCK_SYSTEM_WS, LOCK_WORKING_SET, LOCK_WS, _MMPTE::Long, _MMWSLE::Long, _MMINPAGE_SUPPORT::Mdl, MI_ADD_LOCKED_PAGE_CHARGE(), MI_FAULT_STATUS_INDICATES_WRITE, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE_CLUSTER, MI_IS_NOCACHE, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_PHYSICAL_ADDRESS, MI_IS_SESSION_ADDRESS, MI_IS_WRITECOMBINE, MI_MAGIC_AWE_PTEFRAME, MI_MAKE_TRANSITION_PROTOPTE_VALID, MI_MAKE_TRANSITION_PTE_VALID, MI_MAKE_VALID_PTE, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_REMOVE_LOCKED_PAGE_CHARGE(), MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MI_SET_PTE_CLEAN, MI_SET_PTE_DIRTY, MI_SNAP_DATA, MI_TRANSLATE_CACHETYPE(), MI_VA_TO_VPN, MI_WRITE_INVALID_PTE, MI_WRITE_VALID_PTE, MiAddValidPageToWorkingSet(), MiAllocateWsle(), MiCached, MiCheckControlArea(), MiCompleteProtoPteFault(), MiDecrementCloneBlockReference(), MiFreeInPageSupportBlock(), MiGetPteAddress, MiGetSubsectionAddress, MiInsertPageInFreeList(), MiLocateAddress(), MiLocateCloneAddress, MiNonCached, MiReleaseConfirmedPageFileSpace(), MiResolveDemandZeroFault(), MiResolvePageFileFault(), MiResolveProtoPteFault(), MiResolveTransitionFault(), MiRestoreTransitionPte(), MiStartingOffset(), MiTrimPte(), MiUnlinkPageFromList(), MiWaitForInPageComplete(), MiWriteCombined, MM_COPY_ON_WRITE_MASK, MM_ENORMOUS_LIMIT, MM_FREE_WSLE_SHIFT, MM_HIGH_LIMIT, MM_HIGHEST_USER_ADDRESS, MM_NOACCESS, MM_NOCACHE, MM_NOIRQL, MM_SHARED_USER_DATA_VA, MM_WRITECOMBINE, MM_ZERO_ACCESS, MM_ZERO_PTE, MmAccessFault(), MmAvailablePages, MmMaxTransitionCluster, MmSessionSpace, MmSystemRangeStart, MmWorkingSetList, MmWsle, _MMPFNENTRY::Modified, NOTHING, NT_SUCCESS, NULL, NumberOfBytes, _CONTROL_AREA::NumberOfMappedViews, _MMCLONE_DESCRIPTOR::NumberOfReferences, _MMPFN::OriginalPte, _MMINPAGE_SUPPORT::Page, PAGE_ALIGN, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PERF_FILE_IO, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_HARDFAULT, PerfInfoLogBytes(), PerfTimeStamp, _MMINPAGE_SUPPORT::Pfn, _MMINPAGE_FLAGS::PrefetchMdlHighBits, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, _LARGE_INTEGER::QuadPart, _MMPFNENTRY::ReadInProgress, _PERFINFO_HARDPAGEFAULT_INFORMATION::ReadOffset, _MMINPAGE_SUPPORT::ReadOffset, _MMSECTION_FLAGS::Rom, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _MMPTE::Soft, StandbyPageList, _IO_STATUS_BLOCK::Status, STATUS_ACCESS_VIOLATION, STATUS_ISSUE_PAGING_IO, STATUS_NO_MEMORY, STATUS_PAGE_FAULT_PAGING_FILE, STATUS_PAGE_FAULT_TRANSITION, STATUS_PTE_CHANGED, STATUS_REFAULT, STATUS_SUCCESS, _ETHREAD::Tcb, _PERFINFO_HARDPAGEFAULT_INFORMATION::ThreadId, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u1, _MMWSLE::u1, _MMINPAGE_SUPPORT::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, _CLIENT_ID::UniqueThread, UNLOCK_PFN, UNLOCK_SYSTEM_WS, UNLOCK_WORKING_SET, UNLOCK_WS, VadImageMap, _MMPTE_HARDWARE::Valid, VARIOUS_FLAGS_ACCESS_CHECK_NEEDED, VARIOUS_FLAGS_DIRTY_PTE, VARIOUS_FLAGS_ENTERED_CRITICAL_REGION, VARIOUS_FLAGS_LOG_HARD_FAULT, VARIOUS_FLAGS_PFN_HELD, _PERFINFO_HARDPAGEFAULT_INFORMATION::VirtualAddress, _MM_SESSION_SPACE::Vm, _MMPTE_HARDWARE::Write, _MMPFNENTRY::WriteInProgress, WSLE_NULL_INDEX, and ZeroPte.
Referenced by MmAccessFault().
PMMPTE MiFindActualFaultingPte (IN PVOID FaultingAddress)
Definition at line 4556 of file pagfault.c.
References _MMPTE::Hard, MI_IS_PHYSICAL_ADDRESS, MI_PTE_LOOKUP_NEEDED, MiCheckVirtualAddress(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiPteToProto, NULL, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_SOFTWARE::Prototype, _MMPTE::Soft, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MiWaitForInPageComplete().
VOID MiFreeInPageSupportBlock (IN PMMINPAGE_SUPPORT Support)
Definition at line 6665 of file pagfault.c.
References ASSERT, DISPATCH_LEVEL, ExFreePool(), ExQueryDepthSList, InterlockedDecrement, InterlockedPushEntrySList(), KeClearEvent(), KeGetCurrentIrql(), MI_EXTRACT_PREFETCH_MDL, MmInPageSupportMinimum, MmInPageSupportSListHead, NULL, and PSLIST_ENTRY.
Referenced by MiCcCompletePrefetchIos(), MiCcReleasePrefetchResources(), MiDispatchFault(), MiPhysicalViewRemover(), MiResolveProtoPteFault(), and MmCopyToCachedPage().
PMMINPAGE_SUPPORT MiGetInPageSupportBlock (IN KIRQL OldIrql, OUT PNTSTATUS Status)
Definition at line 6525 of file pagfault.c.
References ASSERT, ASSERT64, CONTAINING_RECORD, DISPATCH_LEVEL, _MMINPAGE_SUPPORT::e1, _MMINPAGE_SUPPORT::Event, ExAllocatePoolWithTag, ExQueryDepthSList, FALSE, InterlockedPopEntrySList(), InterlockedPushEntrySList(), KeGetCurrentIrql(), KeInitializeEvent(), KeReadStateEvent(), _MMINPAGE_SUPPORT::ListEntry, LOCK_PFN, _MMINPAGE_SUPPORT::LongFlags, MM_NOIRQL, MM_PFN_LOCK_ASSERT, MmInPageSupportSListHead, _SINGLE_LIST_ENTRY::Next, NonPagedPool, NotificationEvent, NULL, _MMINPAGE_SUPPORT::PrefetchMdl, _MMINPAGE_FLAGS::PrefetchMdlHighBits, PsGetCurrentThread(), PSLIST_ENTRY, STATUS_INSUFFICIENT_RESOURCES, STATUS_REFAULT, _MMINPAGE_SUPPORT::Thread, _MMINPAGE_SUPPORT::u1, UNLOCK_PFN, and _MMINPAGE_SUPPORT::WaitCount.
Referenced by MiResolveMappedFileFault(), and MiResolvePageFileFault().
VOID MiHandleBankedSection (IN PVOID VirtualAddress, IN PMMVAD Vad)
Definition at line 6741 of file pagfault.c.
References _MMBANKED_SECTION::BankedRoutine, _MMBANKED_SECTION::BankShift, _MMBANKED_SECTION::BankSize, _MMBANKED_SECTION::BankTemplate, _MMBANKED_SECTION::BasedPte, _MMBANKED_SECTION::Context, _MMBANKED_SECTION::CurrentMappedPte, FALSE, MI_FLUSH_PROCESS_TB, MiGetPteAddress, MiZeroMemoryPte, PAGE_SHIFT, PTE_SHIFT, and RtlCopyMemory.
Referenced by MiCheckVirtualAddress().
VOID MiInitializeCopyOnWritePfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN WSLE_NUMBER WorkingSetIndex, IN PMMWSL WorkingSetList)
Definition at line 5907 of file pagfault.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, _MMPTE::Hard, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_MAKE_PROTECT_NOT_WRITE_COPY, MI_PFN_ELEMENT, MI_SET_MODIFIED, MiCheckPdeForPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MM_ZERO_ACCESS, NT_SUCCESS, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE::u, _MMPFN::u1, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, _MMPTE_HARDWARE::Valid, and _MMPFN::WsIndex.
Referenced by MiCopyOnWrite().
VOID MiInitializePfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN ULONG ModifiedState)
Definition at line 5207 of file pagfault.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPTE::Hard, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_CACHING_DISABLED, MI_IS_NOCACHE, MI_IS_WRITE_COMBINE_ENABLED(), MI_IS_WRITECOMBINE, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_TRANSLATE_CACHETYPE(), MiCached, MiCheckPdeForPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MM_DEMAND_ZERO_WRITE_PTE, MM_EXECUTE_READWRITE, MM_PFN_LOCK_ASSERT, MmPaeMask, NT_SUCCESS, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and _MMPTE_HARDWARE::Valid.
Referenced by MiAddWorkingSetPage(), MiAddWsleHash(), MiAllocatePfn(), MiCcPutPagesInTransition(), MiInitializeLargePageSupport(), MiResolveDemandZeroFault(), MmAccessFault(), MmCheckCachedPageState(), MmCopyToCachedPage(), MmCreateKernelStack(), MmGrowKernelStackEx(), and MmInitializeProcessAddressSpace().
VOID MiInitializePfnAndMakePteValid (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN MMPTE NewPteContents)
Definition at line 5367 of file pagfault.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPTE::Hard, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_CACHING_DISABLED, MI_IS_WRITE_COMBINE_ENABLED(), MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiCached, MiCheckPdeForPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MM_DEMAND_ZERO_WRITE_PTE, MM_EXECUTE_READWRITE, MM_NOCACHE, MM_PFN_LOCK_ASSERT, MM_WRITECOMBINE, MmPaeMask, NT_SUCCESS, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and _MMPTE_HARDWARE::Valid.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), MiFillSystemPageDirectory(), MiInitializeSystemCache(), MiReloadBootLoadedDrivers(), MiSessionCreateInternal(), MiSessionInitializeWorkingSetList(), MmAllocateIndependentPages(), and MmInitSystem().
VOID MiInitializePfnForOtherProcess (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte, IN PFN_NUMBER ContainingPageFrame)
Definition at line 6191 of file pagfault.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPFN::InPageError, _MMPTE::Long, MI_FLUSH_TB_FOR_CACHED_ATTRIBUTE, MI_PFN_ELEMENT, MI_SET_MODIFIED, MiCached, MM_DEMAND_ZERO_WRITE_PTE, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, and _MMPFN::u4.
Referenced by MiAllocatePoolPages(), MiBuildPagedPool(), MiCcPutPagesInTransition(), MiFillSystemPageDirectory(), MiInitializeAndChargePfn(), MiMakeOutswappedPageResident(), MiSessionCommitPageTables(), MiSessionCreateInternal(), and MiSessionInitializeWorkingSetList().
VOID MiInitializeReadInProgressPfn (IN PMDL Mdl, IN PMMPTE BasePte, IN PKEVENT Event, IN WSLE_NUMBER WorkingSetIndex)
Definition at line 5635 of file pagfault.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, FALSE, _MMPTE::Hard, _MMPFN::InPageError, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_FLUSH_ENTIRE_TB_FOR_ATTRIBUTE_CHANGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_NOCACHE, MI_IS_WRITECOMBINE, MI_MAKE_TRANSITION_PTE, MI_PFN_ELEMENT, MI_PROTOTYPE_WSINDEX, MI_TRANSLATE_CACHETYPE(), MI_WRITE_INVALID_PTE, MiCached, MiCheckPdeForPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiNonCached, MiWriteCombined, MM_PFN_LOCK_ASSERT, NT_SUCCESS, NumberOfBytes, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and _MMPTE_HARDWARE::Valid.
Referenced by MiResolveMappedFileFault(), and MiResolvePageFileFault().
VOID MiInitializeReadInProgressSinglePfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE BasePte, IN PKEVENT Event, IN WSLE_NUMBER WorkingSetIndex)
Definition at line 5506 of file pagfault.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, _MMPTE::Hard, _MMPFN::InPageError, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_FLUSH_TB_FOR_INDIVIDUAL_ATTRIBUTE_CHANGE, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_NOCACHE, MI_IS_WRITECOMBINE, MI_MAKE_TRANSITION_PTE, MI_PFN_ELEMENT, MI_PROTOTYPE_WSINDEX, MI_TRANSLATE_CACHETYPE(), MI_WRITE_INVALID_PTE, MiCached, MiCheckPdeForPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MM_PFN_LOCK_ASSERT, NT_SUCCESS, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and _MMPTE_HARDWARE::Valid.
Referenced by MiResolvePageFileFault().
VOID MiInitializeTransitionPfn (IN PFN_NUMBER PageFrameIndex, IN PMMPTE PointerPte)
Definition at line 5800 of file pagfault.c.
References ASSERT, _MMPFN::e1, _MMPFN::Event, _MMPTE::Hard, KeBugCheckEx(), _MMPTE::Long, MEMORY_MANAGEMENT, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_TRANSITION_PTE, MI_PFN_ELEMENT, MI_WRITE_INVALID_PTE, MiCheckPdeForPagedPool(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MM_PFN_LOCK_ASSERT, NT_SUCCESS, NULL, _MMPFN::OriginalPte, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TransitionPage, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, and _MMPTE_HARDWARE::Valid.
Referenced by MiUpdateImageHeaderPage(), and MmCopyToCachedPage().
BOOLEAN MiIsAddressValid (IN PVOID VirtualAddress, IN LOGICAL UseForceIfPossible)
Definition at line 6037 of file pagfault.c.
References FALSE, _MMPTE::Hard, MI_CONVERT_PHYSICAL_TO_PFN, MI_IS_PHYSICAL_ADDRESS, MI_PDE_MAPS_LARGE_PAGE, MI_RESERVED_BITS_CANONICAL(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MmHighestPhysicalPage, TRUE, _MMPTE::u, UNREFERENCED_PARAMETER, and _MMPTE_HARDWARE::Valid.
Referenced by MiCanFileBeTruncatedInternal(), MiDecrementCloneBlockReference(), MiGrowWsleHash(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MiRemoveWorkingSetPages(), MiWaitForInPageComplete(), MmFlushSection(), MmIsAddressValid(), MmIsSystemAddressLocked(), MmPurgeSection(), NtLockVirtualMemory(), and NtUnlockVirtualMemory().
NTSTATUS MiResolveDemandZeroFault (IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PEPROCESS Process, IN KIRQL OldIrql)
Definition at line 1610 of file pagfault.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, _MMPFN::Event, FALSE, _MMPTE::Hard, HYDRA_PROCESS, InterlockedIncrement, KeGetCurrentPrcb(), KeZeroSinglePage, LOCK_PFN, MI_BARRIER_STAMP_ZEROED_PAGE, MI_BARRIER_SYNCHRONIZE, MI_DISABLE_CACHING, MI_GET_PAGE_COLOR_FROM_VA, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_SESSION_IMAGE_ADDRESS, MI_MAKE_VALID_PTE, MI_MAKE_VALID_USER_PTE, MI_PAGE_COLOR_VA_PROCESS, MI_PFN_ELEMENT, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_SNAP_DATA, MI_WRITE_VALID_PTE, MiAddValidPageToWorkingSet(), MiEnsureAvailablePageOrWait(), MiGetVirtualAddressMappedByPte, MiHighestUserPte, MiInitializePfn(), MiNonCached, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiRemoveZeroPage(), MiRemoveZeroPageIfAny, MiReserveSystemPtes(), MiSessionSpaceWs, MiSessionViewStart, MiTrimPte(), MiWaitForForkToComplete(), MiWriteCombined, MiZeroPhysicalPage(), MM_HIGH_LIMIT, MM_NOIRQL, MM_PFN_LOCK_ASSERT, MmAvailablePages, NULL, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, _MMPFN::PteFrame, _MMPTE::Soft, STATUS_NO_MEMORY, STATUS_PAGE_FAULT_DEMAND_ZERO, STATUS_REFAULT, SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, ValidKernelPte, _MMPTE_HARDWARE::Write, and ZeroPte.
Referenced by MiDispatchFault(), MiResolveProtoPteFault(), and MmAccessFault().
NTSTATUS MiResolveMappedFileFault (IN PMMPTE PointerPte, IN PMMINPAGE_SUPPORT * ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
Referenced by MiResolveProtoPteFault().
NTSTATUS MiResolveMappedFileFault (IN PMMPTE PointerPte, OUT PMMINPAGE_SUPPORT * ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
Definition at line 3750 of file pagfault.c.
References ASSERT, _MMINPAGE_SUPPORT::BasePte, _SUBSECTION::ControlArea, _ETHREAD::DisablePageFaultClustering, _MMINPAGE_SUPPORT::Event, _MMSECTION_FLAGS::FailAllIo, _CONTROL_AREA::FilePointer, _MMINPAGE_SUPPORT::FilePointer, _CONTROL_AREA::Flags, _ETHREAD::ForwardClusterOnly, HYDRA_PROCESS, _MMSECTION_FLAGS::Image, InterlockedExchangeAdd(), InterlockedIncrement, KeBugCheckEx(), KeGetCurrentPrcb(), _MMPTE::Long, _LARGE_INTEGER::LowPart, _MMINPAGE_SUPPORT::Mdl, MDL_IO_PAGE_READ, MDL_PAGES_LOCKED, _MDL::MdlFlags, MEMORY_MANAGEMENT, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_COLOR_FROM_SESSION, MI_PAGE_COLOR_PTE_PROCESS, MI_PFN_ELEMENT, MI_PROTOTYPE_WSINDEX, MI_ZERO_USED_PAGETABLE_ENTRIES_IN_INPAGE_SUPPORT, MiEndingOffset(), MiEnsureAvailablePageOrWait(), MiGetInPageSupportBlock(), MiGetSubsectionAddress, MiGetVirtualAddressMappedByPte, MiInitializeReadInProgressPfn(), MiInPageSinglePages, MiIsPteOnPdeBoundary, MiRemoveAnyPage(), MiRemoveZeroPage(), MiStartingOffset(), MM_HIGH_LIMIT, MM_MAXIMUM_READ_CLUSTER_SIZE, MM_PROTECTION_EXECUTE_MASK, MmAvailablePages, MmCodeClusterSize, MmDataClusterSize, MmFreeGoal, MmInitializeMdl, _KPRCB::MmPageReadCount, _KPRCB::MmPageReadIoCount, MMSECTOR_MASK, MmSessionSpace, _MMSECTION_FLAGS::NoModifiedWriting, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfPfnReferences, _MMINPAGE_SUPPORT::Page, PAGE_SHIFT, PAGE_SIZE, _MMINPAGE_SUPPORT::Pfn, _MMSUBSECTION_FLAGS::Protection, PsGetCurrentThread(), _SUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, _ETHREAD::ReadClusterSize, _MMINPAGE_SUPPORT::ReadOffset, _MMSECTION_FLAGS::Rom, RtlFillMemoryUlong(), Status, STATUS_ACCESS_VIOLATION, STATUS_IN_PAGE_ERROR, STATUS_ISSUE_PAGING_IO, STATUS_REFAULT, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, _MMPTE::u, _CONTROL_AREA::u, and _SUBSECTION::u.
NTSTATUS MiResolvePageFileFault (IN PVOID FaultingAddress, IN PMMPTE PointerPte, OUT PMMPTE CapturedPteContents, IN PMMINPAGE_SUPPORT * ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
Referenced by MiDispatchFault(), and MiResolveProtoPteFault().
NTSTATUS MiResolvePageFileFault (IN PVOID FaultingAddress, IN PMMPTE PointerPte, OUT PMMPTE CapturedPteContents, OUT PMMINPAGE_SUPPORT * ReadBlock, IN PEPROCESS Process, IN KIRQL OldIrql)
Definition at line 2506 of file pagfault.c.
References ASSERT, _MMINPAGE_SUPPORT::BasePte, BYTE_OFFSET, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMINPAGE_SUPPORT::Event, _MMPAGING_FILE::File, _MMINPAGE_SUPPORT::FilePointer, _ETHREAD::ForwardClusterOnly, GET_PAGING_FILE_NUMBER, GET_PAGING_FILE_OFFSET, _MMPTE::Hard, _LARGE_INTEGER::HighPart, HYDRA_PROCESS, InterlockedExchangeAdd(), InterlockedIncrement, KeGetCurrentPrcb(), _MMPTE::Long, _LARGE_INTEGER::LowPart, _MMINPAGE_SUPPORT::Mdl, MDL_IO_PAGE_READ, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_GET_PAGE_COLOR_FROM_SESSION, MI_GET_PAGE_COLOR_FROM_VA, MI_IS_PAGE_TABLE_ADDRESS, MI_PAGE_COLOR_VA_PROCESS, MI_PFN_ELEMENT, MI_PROTOTYPE_WSINDEX, MI_RETRIEVE_USED_PAGETABLE_ENTRIES_FROM_PTE, MI_VA_TO_VPN, MI_ZERO_USED_PAGETABLE_ENTRIES_IN_INPAGE_SUPPORT, MiEnsureAvailablePageOrWait(), MiGetInPageSupportBlock(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInitializeReadInProgressPfn(), MiInitializeReadInProgressSinglePfn(), MiInPageSinglePages, MiIsPteOnPdeBoundary, MiLocateAddress(), MiLocateSubsection(), MiRemoveAnyPage(), MM_HIGH_LIMIT, MM_HIGHEST_USER_ADDRESS, MM_MAXIMUM_READ_CLUSTER_SIZE, MM_PFN_LOCK_ASSERT, MM_PLENTY_FREE_LIMIT, MmAvailablePages, MmClusterPageFileReads, MmInitializeMdl, _KPRCB::MmPageReadCount, _KPRCB::MmPageReadIoCount, MmPagingFile, MmPagingFileDebug, MmSessionSpace, NT_SUCCESS, NULL, _MMINPAGE_SUPPORT::Page, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, _MMINPAGE_SUPPORT::Pfn, _MMPTE_SOFTWARE::Prototype, PsGetCurrentThread(), PTE_PER_PAGE, _SUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, _MMINPAGE_SUPPORT::ReadOffset, _MMPAGING_FILE::Size, _MMPTE::Soft, Status, STATUS_ISSUE_PAGING_IO, STATUS_REFAULT, _SUBSECTION::SubsectionBase, _MMPTE_SOFTWARE::Transition, _MMPTE::u, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
NTSTATUS MiResolveProtoPteFault (IN ULONG_PTR StoreInstruction, IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN OUT PMMPFN * LockedProtoPfn, IN PMMINPAGE_SUPPORT * ReadBlock, OUT PMMPTE CapturedPteContents, IN PEPROCESS Process, IN KIRQL OldIrql, IN PVOID TrapInformation)
Referenced by MiDispatchFault().
NTSTATUS MiResolveProtoPteFault (IN ULONG_PTR StoreInstruction, IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN PMMPTE PointerProtoPte, IN OUT PMMPFN * LockedProtoPfn, OUT PMMINPAGE_SUPPORT * ReadBlock, OUT PMMPTE CapturedPteContents, IN PEPROCESS Process, IN KIRQL OldIrql, IN PVOID TrapInformation)
Definition at line 2987 of file pagfault.c.
References _IMAGE_ENTRY_IN_SESSION::Address, ASSERT, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _MMPTE::Hard, _MM_SESSION_SPACE::ImageList, _IMAGE_ENTRY_IN_SESSION::ImageLoading, _MM_SESSION_SPACE::ImageLoadingCount, InterlockedIncrement, IS_PTE_NOT_DEMAND_ZERO, KeAreAllApcsDisabled(), KeGetCurrentPrcb(), KernelMode, _MMPTE::Long, MI_BREAK_ON_AV, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PROTECTION_FROM_SOFT_PTE, MI_IS_SESSION_ADDRESS, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_WRITE_INVALID_PTE, MiAccessCheck(), MiCompleteProtoPteFault(), MiFreeInPageSupportBlock(), MiHighestUserPte, MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveTransitionFault(), MM_COPY_ON_WRITE_MASK, MM_DEMAND_ZERO_WRITE_PTE, MM_EXECUTE, MM_EXECUTE_READWRITE, MM_NOIRQL, MM_PFN_LOCK_ASSERT, MM_PROTECT_FIELD_SHIFT, MmSessionSpace, NT_SUCCESS, NULL, _MMPTE_SOFTWARE::PageFileHigh, PREFETCH_PROCESS, _MMPTE_SOFTWARE::Protection, _MMPTE::Proto, _MMPTE_SOFTWARE::Prototype, _MMPTE_PROTOTYPE::ReadOnly, _MMPFN::ShareCount, _MMPTE::Soft, STATUS_ACCESS_VIOLATION, STATUS_ISSUE_PAGING_IO, STATUS_SUCCESS, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u2, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
NTSTATUS MiResolveTransitionFault (IN PVOID FaultingAddress, IN PMMPTE PointerPte, IN PEPROCESS Process, IN KIRQL OldIrql, OUT PMMINPAGE_SUPPORT * InPageBlock)
Definition at line 1919 of file pagfault.c.
References ActiveAndValid, _ETHREAD::ActiveFaultCount, _ETHREAD::ApcNeeded, ASSERT, _MMPFNENTRY::CacheAttribute, _MMPTE_HARDWARE::CopyOnWrite, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, FALSE, FreePageList, _MM_SESSION_SPACE::GlobalVirtualAddress, _MMPTE::Hard, HYDRA_PROCESS, _MMPFN::InPageError, InterlockedIncrement, InterlockedIncrementPfn, KeEnterCriticalRegionThread(), KeGetCurrentPrcb(), KeLeaveCriticalRegionThread(), LOCK_PFN, _MMPTE::Long, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_MAKE_TRANSITION_PTE_VALID, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE(), MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_PTE_CLEAN, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiAddValidPageToWorkingSet(), MiCached, MiEnsureAvailablePageOrWait(), MiGetPteAddress, MiInsertPageInFreeList(), MiNonCached, MiRestoreTransitionPte(), MiTrimPte(), MiUnlinkPageFromList(), MiWaitForInPageComplete(), MiWriteCombined, MM_HIGH_LIMIT, MM_NOCACHE, MM_NOIRQL, MM_WRITECOMBINE, MmAvailablePages, MmPagedPoolEnd, MmPagedPoolStart, MmSessionSpace, MmSpecialPoolEnd, MmSpecialPoolStart, MmSystemRangeStart, _MMPFNENTRY::Modified, NOTHING, NT_SUCCESS, NULL, _MMPFN::OriginalPte, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFNENTRY::ReadInProgress, _MMPFN::ReadStatus, RtlpStackWalksInProgress, _MMPFN::ShareCount, _MMPTE::Soft, StandbyPageList, STATUS_MULTIPLE_FAULT_VIOLATION, STATUS_NO_MEMORY, STATUS_PAGE_FAULT_TRANSITION, STATUS_REFAULT, STATUS_SUCCESS, _ETHREAD::Tcb, _MMINPAGE_SUPPORT::Thread, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_SYSTEM_WS, UNLOCK_WORKING_SET, UNLOCK_WS, _MMPTE_SOFTWARE::Valid, _MMPTE_HARDWARE::Valid, _MM_SESSION_SPACE::Vm, _MMINPAGE_SUPPORT::WaitCount, _MMPTE_HARDWARE::Write, and ZeroPte.
Referenced by MiDispatchFault(), and MiResolveProtoPteFault().
VOID MiTrimPte (IN PVOID VirtualAddress, IN PMMPTE PointerPte, IN PMMPFN Pfn1, IN PEPROCESS CurrentProcess, IN MMPTE NewPteContents)
Definition at line 6362 of file pagfault.c.
References APC_LEVEL, ASSERT, FALSE, _MMPTE::Hard, HYDRA_PROCESS, KeAreAllApcsDisabled(), KeBugCheckEx(), KeGetCurrentIrql(), LOCK_PFN, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN_DELETED, MI_IS_PTE_DIRTY, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_PFN_ELEMENT_TO_INDEX, MI_WRITE_INVALID_PTE, MiCaptureWriteWatchDirtyBit(), MiCheckPdeForPagedPool(), MiDecrementShareCountInline, MiGetPteAddress, MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, _MMPTE_SOFTWARE::Protection, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentThread(), _MMPFN::PteFrame, _MMPTE::Soft, TRUE, _MMPTE::u, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiAddWsleHash(), MiCompleteProtoPteFault(), MiDispatchFault(), MiLockCode(), MiResolveDemandZeroFault(), MiResolveTransitionFault(), MiSessionCommitPageTables(), MmAccessFault(), MmCheckCachedPageState(), and MmCopyToCachedPage().
NTSTATUS MiWaitForInPageComplete (IN PMMPFN Pfn2, IN PMMPTE PointerPte, IN PVOID FaultingAddress, IN PMMPTE PointerPteContents, IN PMMINPAGE_SUPPORT InPageSupport, IN PEPROCESS CurrentProcess)
Definition at line 4099 of file pagfault.c.
References ASSERT, BYTE_OFFSET, _MDL::ByteCount, DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, _MMPFN::e2, _MMPFN::Event, FALSE, _MM_SESSION_SPACE::GlobalVirtualAddress, HYDRA_PROCESS, _MMPFN::InPageError, KeBugCheckEx(), KERNEL_DATA_INPAGE_ERROR, KernelMode, KeWaitForSingleObject(), LOCK_PFN, LOCK_SYSTEM_WS, LOCK_WORKING_SET, LOCK_WS, _MMPTE::Long, _MDL::MappedSystemVa, MDL_MAPPED_TO_SYSTEM_VA, _MDL::MdlFlags, MI_EXTRACT_PREFETCH_MDL, MI_INSERT_USED_PAGETABLE_ENTRIES_IN_PFN, MI_IS_SYSTEM_CACHE_ADDRESS, MI_MAGIC_AWE_PTEFRAME, MI_PF_DUMMY_PAGE_PTE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_ZERO_USED_PAGETABLE_ENTRIES_IN_PFN, MiCheckVirtualAddress(), MiFaultRetries, MiFaultRetryMask, MiFindActualFaultingPte(), MiInPageSinglePages, MiIsAddressValid(), MiMapPageInHyperSpaceAtDpc(), MiPteToProto, MiUnmapPageInHyperSpaceFromDpc, MiUserFaultRetries, MiUserFaultRetryMask, MiZeroPhysicalPage(), MM_HIGHEST_USER_ADDRESS, MmIsRetryIoStatus, MmSessionSpace, MmUnmapLockedPages(), NOTHING, NT_SUCCESS, NULL, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, _MMPTE_SOFTWARE::PageFileHigh, PREFETCH_PROCESS, _MMPTE_SOFTWARE::Prototype, PsGetCurrentProcess(), PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, _MMPFN::ReadStatus, RtlFillMemoryUlong(), RtlZeroMemory, _MMPTE::Soft, STATUS_END_OF_FILE, STATUS_PTE_CHANGED, STATUS_REFAULT, STATUS_SUCCESS, STATUS_VERIFY_REQUIRED, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, _MMPFN::u4, _MM_SESSION_SPACE::Vm, and WrPageIn.
Referenced by MiCcCompletePrefetchIos(), MiDispatchFault(), and MiResolveTransitionFault().
BOOLEAN MmIsAddressValid (__in PVOID VirtualAddress)
Definition at line 6157 of file pagfault.c.
References FALSE, and MiIsAddressValid().
Referenced by KiInvokeBugCheckEntryCallbacks(), KiPcToFileHeader(), KiScanBugCheckCallbackList(), MiDetachSession(), MiInitMachineDependent(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiRemoveImageSessionWide(), MiSessionAddProcess(), MiSessionCreateInternal(), MiSessionRemoveProcess(), MiSessionWideReserveImageAddress(), MiShareSessionImage(), MmCommitSessionMappedView(), MmMapViewInSessionSpace(), MmSessionCreate(), MmSessionDelete(), MmSessionSetUnloadAddress(), MmUnmapViewInSessionSpace(), MmWorkingSetManager(), and RtlpWalkFrameChain().
Variable Documentation
ULONG MiFaultRetries
Definition at line 32 of file pagfault.c.
Referenced by MiWaitForInPageComplete().
ULONG MiInPageSinglePages
Definition at line 25 of file pagfault.c.
Referenced by MiResolveMappedFileFault(), MiResolvePageFileFault(), and MiWaitForInPageComplete().
ULONG MiUserFaultRetries
Definition at line 33 of file pagfault.c.
Referenced by MiWaitForInPageComplete().
ULONG MmClusterPageFileReads
Definition at line 35 of file pagfault.c.
Referenced by MiResolvePageFileFault().
ULONG MmInPageSupportMinimum = 4
Definition at line 23 of file pagfault.c.
Referenced by MiFreeInPageSupportBlock(), and MmInitSystem().
ULONG MmMaxTransitionCluster = 8
Definition at line 96 of file pagfault.c.
Referenced by MiDispatchFault().
PMMPTE MmSharedUserDataPte
Definition at line 24 of file mminit.c.
Referenced by MiCheckVirtualAddress().
PVOID MmSpecialPoolEnd
Referenced by MiResolveTransitionFault().
PVOID MmSpecialPoolStart
Referenced by MiResolveTransitionFault().