Windows Research Kernel v1.2: C:/Windows Research Kernel/ps/psdelete.c File Reference
psdelete.c File Reference
#include "psp.h"
Macros
#define WAIT_BATCH THREAD_WAIT_OBJECTS
Functions
NTSTATUS NtRegisterThreadTerminatePort (__in HANDLE PortHandle)
NTSTATUS NtTerminateProcess (__in_opt HANDLE ProcessHandle, __in NTSTATUS ExitStatus)
NTSTATUS NtTerminateThread (__in_opt HANDLE ThreadHandle, __in NTSTATUS ExitStatus)
VOID PsExitSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
LARGE_INTEGER PsGetProcessExitTime (VOID)
BOOLEAN PsIsThreadTerminating (__in PETHREAD Thread)
VOID PspCatchCriticalBreak (IN PCHAR Msg, IN PVOID Object, IN PUCHAR ImageFileName)
VOID PspExitApcRundown (IN PKAPC Apc)
VOID PspExitNormalApc (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
VOID PspExitProcess (IN BOOLEAN LastThreadExit, IN PEPROCESS Process)
DECLSPEC_NORETURN VOID PspExitThread (IN NTSTATUS ExitStatus)
NTSTATUS PspFreezeProcessWorker (PEPROCESS Process, PVOID Context)
VOID PspNullSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE *NormalRoutine, IN PVOID *NormalContext, IN PVOID *SystemArgument1, IN PVOID *SystemArgument2)
VOID PspProcessDelete (IN PVOID Object)
VOID PspReaper (IN PVOID Context)
NTSTATUS PspTerminateProcess (PEPROCESS Process, NTSTATUS ExitStatus)
NTSTATUS PspTerminateThreadByPointer (IN PETHREAD Thread, IN NTSTATUS ExitStatus, IN BOOLEAN DirectTerminate)
VOID PspThreadDelete (IN PVOID Object)
NTSTATUS PspWaitForUsermodeExit (IN PEPROCESS Process)
ULONG PsSetBBTNotifyRoutine (__in PBBT_NOTIFY_ROUTINE BBTNotifyRoutine)
LOGICAL PsShutdownSystem (VOID)
NTSTATUS PsTerminateProcess (PEPROCESS Process, NTSTATUS Status)
NTSTATUS PsTerminateSystemThread (__in NTSTATUS ExitStatus)
BOOLEAN PsWaitForAllProcesses (VOID)
Variables
PEPROCESS ExpDefaultErrorPortProcess
BOOLEAN PsContinueWaiting = FALSE
PBBT_NOTIFY_ROUTINE PspBBTNotifyRoutine = NULL
LARGE_INTEGER ShortTime = {(ULONG)(-10 * 1000 * 100), -1}
Macro Definition Documentation
#define WAIT_BATCH THREAD_WAIT_OBJECTS
Referenced by PsShutdownSystem().
Function Documentation
NTSTATUS NtRegisterThreadTerminatePort (__in HANDLE PortHandle)
Definition at line 1679 of file psdelete.c.
References ExAllocatePoolWithQuotaTag, KeGetPreviousModeByThread, LpcPortObjectType, _TERMINATION_PORT::Next, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, POOL_QUOTA_FAIL_INSTEAD_OF_RAISE, _TERMINATION_PORT::Port, PROTECTED_POOL, PsGetCurrentThread(), STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _ETHREAD::Tcb, and _ETHREAD::TerminationPort.
NTSTATUS NtTerminateProcess (__in_opt HANDLE ProcessHandle, __in NTSTATUS ExitStatus)
Definition at line 274 of file psdelete.c.
References ARGUMENT_PRESENT, DBG_TERMINATE_PROCESS, DbgkClearProcessDebugObject(), _EPROCESS::DebugPort, ExAcquireRundownProtection(), ExReleaseRundownProtection(), FALSE, _EPROCESS::Flags, _EPROCESS::ImageFileName, KeGetPreviousModeByThread, NT_SUCCESS, NtCurrentProcess, NULL, ObClearProcessHandleTable(), ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_TERMINATE, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsGetNextProcessThread(), PspCatchCriticalBreak(), PsProcessType, PspTerminateThreadByPointer(), _EPROCESS::RundownProtect, STATUS_NOTHING_TO_TERMINATE, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
NTSTATUS NtTerminateThread (__in_opt HANDLE ThreadHandle, __in NTSTATUS ExitStatus)
Definition at line 528 of file psdelete.c.
References _EPROCESS::ActiveThreads, ARGUMENT_PRESENT, FALSE, KeGetPreviousModeByThread, NT_SUCCESS, NtCurrentThread, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PspTerminateThreadByPointer(), PsThreadType, Status, STATUS_CANT_TERMINATE_SELF, STATUS_SUCCESS, THREAD_TERMINATE, and TRUE.
VOID PsExitSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 656 of file psdelete.c.
References PAGED_CODE, PsGetCurrentThread(), PspExitApcRundown(), PspExitThread(), and UNREFERENCED_PARAMETER.
Referenced by KiInsertQueueApc(), PspExitNormalApc(), and PspTerminateThreadByPointer().
LARGE_INTEGER PsGetProcessExitTime (VOID)
Definition at line 1736 of file psdelete.c.
References _EPROCESS::ExitTime, PAGED_CODE, and PsGetCurrentProcess().
BOOLEAN PsIsThreadTerminating (__in PETHREAD Thread)
Definition at line 1775 of file psdelete.c.
References FALSE, PS_CROSS_THREAD_FLAGS_TERMINATED, and TRUE.
Referenced by NtQueryInformationThread(), and ObpCloseHandle().
VOID PspCatchCriticalBreak (IN PCHAR Msg, IN PVOID Object, IN PUCHAR ImageFileName)
Definition at line 739 of file psdelete.c.
References CRITICAL_OBJECT_TERMINATION, DbgBreakPoint(), DbgPrint(), DbgPrompt(), FALSE, KdDebuggerEnabled, KdDebuggerNotPresent, KeBugCheckEx(), PAGED_CODE, and TRUE.
Referenced by NtTerminateProcess(), PspExitThread(), PspTerminateProcess(), and PspTerminateThreadByPointer().
VOID PspExitApcRundown (IN PKAPC Apc)
Definition at line 686 of file psdelete.c.
References ExFreePool(), and PAGED_CODE.
Referenced by PsExitSpecialApc(), PspExitNormalApc(), and PspTerminateThreadByPointer().
VOID PspExitNormalApc (IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 696 of file psdelete.c.
References _KTHREAD::ApcState, ASSERT, KeInitializeApc(), KeInsertQueueApc(), OriginalApcEnvironment, PAGED_CODE, PsExitSpecialApc(), PsGetCurrentThread(), PsGetKernelThread(), PspExitApcRundown(), PspExitNormalApc(), _ETHREAD::Tcb, TRUE, _KAPC_STATE::UserApcPending, and UserMode.
Referenced by PspExitNormalApc(), and PspTerminateThreadByPointer().
VOID PspExitProcess (IN BOOLEAN LastThreadExit, IN PEPROCESS Process)
Definition at line 1345 of file psdelete.c.
References CCPF_IS_PREFETCHER_ACTIVE, CcPfProcessExitNotification(), _EJOB::CompletionKey, _EJOB::CompletionPort, ExAcquireResourceSharedLite(), ExDereferenceCallBackBlock(), ExGetCallBackBlockRoutine(), ExReferenceCallBackBlock(), ExReleaseResourceLite(), FALSE, IoSetIoCompletion(), JOB_OBJECT_MSG_ABNORMAL_EXIT_PROCESS, JOB_OBJECT_MSG_EXIT_PROCESS, _EJOB::JobLock, KeEnterCriticalRegionThread(), KeLeaveCriticalRegionThread(), KeMaximumIncrement, MmCleanProcessAddressSpace(), NULL, ObDereferenceObject(), PAGED_CODE, PERFINFO_PROCESS_DELETE, PoRundownProcess, PS_JOB_STATUS_EXIT_PROCESS_REPORTED, PS_JOB_STATUS_LAST_REPORT_MEMORY, PS_JOB_STATUS_NOT_REALLY_ACTIVE, PS_PROCESS_FLAGS_PROCESS_EXITING, PS_PROCESS_FLAGS_SET_TIMER_RESOLUTION, PS_SET_BITS, PS_SET_CLEAR_BITS, PsGetCurrentThread(), PSP_MAX_CREATE_PROCESS_NOTIFY, PspCreateProcessNotifyRoutine, PspCreateProcessNotifyRoutineCount, STATUS_ACCESS_VIOLATION, STATUS_ARRAY_BOUNDS_EXCEEDED, STATUS_BREAKPOINT, STATUS_CONTROL_C_EXIT, STATUS_DATATYPE_MISALIGNMENT, STATUS_FLOAT_DENORMAL_OPERAND, STATUS_FLOAT_DIVIDE_BY_ZERO, STATUS_FLOAT_INEXACT_RESULT, STATUS_FLOAT_INVALID_OPERATION, STATUS_FLOAT_MULTIPLE_FAULTS, STATUS_FLOAT_MULTIPLE_TRAPS, STATUS_FLOAT_OVERFLOW, STATUS_FLOAT_STACK_CHECK, STATUS_FLOAT_UNDERFLOW, STATUS_GUARD_PAGE_VIOLATION, STATUS_ILLEGAL_INSTRUCTION, STATUS_IN_PAGE_ERROR, STATUS_INTEGER_DIVIDE_BY_ZERO, STATUS_INTEGER_OVERFLOW, STATUS_INVALID_DISPOSITION, STATUS_NONCONTINUABLE_EXCEPTION, STATUS_PRIVILEGED_INSTRUCTION, STATUS_REG_NAT_CONSUMPTION, STATUS_SINGLE_STEP, STATUS_STACK_OVERFLOW, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, and ZwSetTimerResolution().
Referenced by PspExitThread(), and PspProcessDelete().
DECLSPEC_NORETURN VOID PspExitThread (IN NTSTATUS ExitStatus)
Definition at line 794 of file psdelete.c.
References ACTIVE_EX_WORKER_THREAD_TERMINATION, _ETHREAD::ActiveExWorker, _EPROCESS::ActiveThreads, _KTHREAD::ApcQueueable, _KTHREAD::ApcState, _KTHREAD::ApcStateIndex, ASSERT, _KTHREAD::BBTData, _ETHREAD::Cid, CmNotifyRunDown(), _KTHREAD::CombinedApcDisable, CONTAINING_RECORD, _LPC_CLIENT_DIED_MSG::CreateTime, CRITICAL_PROCESS_DIED, _ETHREAD::CrossThreadFlags, DbgkExitProcess(), DbgkExitThread(), _EPROCESS::DebugPort, _KTHREAD::EnableStackSwap, except, EXCEPTION_EXECUTE_HANDLER, _EPROCESS::ExceptionPort, ExDereferenceCallBackBlock(), Executive, ExFreePool(), ExFreePoolWithTag, ExGetCallBackBlockRoutine(), _EPROCESS::ExitStatus, _ETHREAD::ExitStatus, _EPROCESS::ExitTime, _ETHREAD::ExitTime, ExReferenceCallBackBlock(), ExTimerRundown(), ExWaitForRundownProtectionRelease(), FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _EPROCESS::ImageFileName, INVALID_PROCESS_ATTACH_ATTEMPT, IoCancelThreadIo(), IS_SYSTEM_THREAD, _EPROCESS::Job, KD_DEBUGGER_ENABLED, KeBugCheckEx(), KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeFlushQueueApc(), KeForceResumeThread(), KeGetCurrentIrql(), KeLeaveCriticalRegionThread(), KeLowerIrql, KeQuerySystemTime(), KeReadStateThread(), KERNEL_APC_PENDING_DURING_EXIT, KERNEL_STACK_LOCKED_AT_EXIT, KernelMode, KeRundownThread(), KeSetProcess(), KeTerminateThread(), KeWaitForSingleObject(), _EPROCESS::LastThreadExitStatus, LPC_CLIENT_DIED, LpcExitThread(), LpcRequestPort(), MEM_RELEASE, MmCleanProcessAddressSpace(), MmDeleteTeb(), _TERMINATION_PORT::Next, NtCurrentProcess, NULL, ObCloseHandle(), ObDereferenceObject(), ObKillProcess(), ObReferenceObjectSafe(), PAGED_CODE, PASSIVE_LEVEL, _EPROCESS::Pcb, _EPROCESS::Peb, PERFINFO_THREAD_DELETE, _TERMINATION_PORT::Port, _LPC_CLIENT_DIED_MSG::PortMsg, PoRundownThread, _KAPC_STATE::Process, PROTECTED_POOL, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_GET_THREAD_CREATE_TIME, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PsDereferencePrimaryTokenEx, PsGetCurrentProcessByThread, PsGetCurrentThread(), PSP_MAX_CREATE_THREAD_NOTIFY, PspBBTNotifyRoutine, PspCatchCriticalBreak(), PspCreateThreadNotifyRoutine, PspCreateThreadNotifyRoutineCount, PspExitProcess(), PspExitProcessFromJob(), PspLockProcessExclusive(), PspUnlockProcessExclusive(), PspW32ProcessCallout, PspW32ThreadCallout, PsReferencePrimaryToken(), PsW32ThreadCalloutExit, _LARGE_INTEGER::QuadPart, _ETHREAD::RundownProtect, _KAPC::RundownRoutine, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SeAuditProcessExit(), _EPROCESS::SectionObject, SeDetailedAuditingWithToken(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_PENDING, STATUS_THREAD_IS_TERMINATING, _ETHREAD::Tcb, _KTHREAD::Teb, _ETHREAD::TerminationPort, THREAD_TO_PROCESS, _EPROCESS::ThreadListHead, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, UlongToPtr, _EPROCESS::UniqueProcessId, _CLIENT_ID::UniqueThread, UserMode, _EPROCESS::VdmObjects, _EPROCESS::Win32Process, _KTHREAD::Win32Thread, WOW64_GET_TEB32_SAFE, and ZwFreeVirtualMemory().
Referenced by PsExitSpecialApc(), and PspTerminateThreadByPointer().
NTSTATUS PspFreezeProcessWorker (PEPROCESS Process, PVOID Context)
Definition at line 1811 of file psdelete.c.
References _EPROCESS::ExceptionPort, _EPROCESS::Flags, LpcDisconnectPort(), NULL, PS_PROCESS_FLAGS_PROCESS_EXITING, PsIdleProcess, PsInitialSystemProcess, PsSuspendProcess(), STATUS_SUCCESS, and UNREFERENCED_PARAMETER.
Referenced by PsShutdownSystem().
VOID PspNullSpecialApc (IN PKAPC Apc, IN PKNORMAL_ROUTINE * NormalRoutine, IN PVOID * NormalContext, IN PVOID * SystemArgument1, IN PVOID * SystemArgument2)
Definition at line 635 of file psdelete.c.
References ExFreePool(), PAGED_CODE, and UNREFERENCED_PARAMETER.
VOID PspProcessDelete (IN PVOID Object)
Definition at line 1503 of file psdelete.c.
References _EPROCESS::ActiveProcessLinks, CID_HANDLE_DELETION, _EPROCESS::DebugPort, _EPROCESS::ExceptionPort, ExDestroyHandle(), ExFreePool(), FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, _EPROCESS::GrantedAccess, _SE_AUDIT_PROCESS_CREATION_INFO::ImageFileName, _EPROCESS::Job, KeBugCheck(), KeStackAttachProcess(), KeTerminateProcess, KeUnstackDetachProcess(), MmDeleteProcessAddressSpace(), NULL, ObDereferenceDeviceMap(), ObDereferenceObject(), ObDereferenceObjectDeferDelete(), _EPROCESS::ObjectTable, ObKillProcess(), PAGED_CODE, _EPROCESS::Pcb, PS_PROCESS_FLAGS_HAS_ADDRESS_SPACE, PsGetCurrentThread(), PspCidTable, PspDeleteLdt(), PspDeleteProcessSecurity(), PspDeleteVdmObjects(), PspDereferenceQuota(), PspExitProcess(), PspLockProcessList(), PspRemoveProcessFromJob(), PspUnlockProcessList(), PsReturnProcessNonPagedPoolQuota(), RemoveEntryList(), _EPROCESS::SeAuditProcessCreationInfo, _EPROCESS::SectionObject, _EPROCESS::UniqueProcessId, _EPROCESS::WorkingSetWatch, and WS_CATCH_SIZE.
Referenced by PspInitPhase0().
VOID PspReaper (IN PVOID Context)
Definition at line 85 of file psdelete.c.
References ASSERT, CONTAINING_RECORD, _KTHREAD::InitialStack, InterlockedCompareExchangePointer, InterlockedExchangePointer, KeWaitForContextSwap(), _KTHREAD::LargeStack, MmDeleteKernelStack(), _SINGLE_LIST_ENTRY::Next, NULL, ObDereferenceObject(), PsReaperListHead, _KTHREAD::StackBase, _ETHREAD::Tcb, and UNREFERENCED_PARAMETER.
Referenced by PspInitPhase0().
NTSTATUS PspTerminateProcess (PEPROCESS Process, NTSTATUS ExitStatus)
Definition at line 405 of file psdelete.c.
References _EPROCESS::DebugPort, FALSE, _EPROCESS::Flags, _EPROCESS::ImageFileName, NULL, ObClearProcessHandleTable(), PAGED_CODE, PS_PROCESS_FLAGS_BREAK_ON_TERMINATION, PS_PROCESS_FLAGS_PROCESS_DELETE, PS_SET_BITS, PsGetNextProcessThread(), PspCatchCriticalBreak(), PspTerminateThreadByPointer(), STATUS_NOTHING_TO_TERMINATE, and STATUS_SUCCESS.
Referenced by NtAssignProcessToJobObject(), PsEnforceExecutionTimeLimits(), PspTerminateAllProcessesInJob(), and PsTerminateProcess().
NTSTATUS PspTerminateThreadByPointer (IN PETHREAD Thread, IN NTSTATUS ExitStatus, IN BOOLEAN DirectTerminate)
Definition at line 164 of file psdelete.c.
References APC_LEVEL, ASSERT, ExAllocatePoolWithTag, ExFreePool(), FALSE, IS_SYSTEM_THREAD, KeDelayExecutionThread(), KeForceResumeThread(), KeGetCurrentIrql(), KeInitializeApc(), KeInsertQueueApc(), KernelMode, NonPagedPool, NULL, OriginalApcEnvironment, PAGED_CODE, PS_CROSS_THREAD_FLAGS_BREAK_ON_TERMINATION, PS_CROSS_THREAD_FLAGS_TERMINATED, PS_SET_BITS, PS_TEST_SET_BITS, PsExitSpecialApc(), PsGetCurrentThread(), PsGetKernelThread(), PspCatchCriticalBreak(), PspExitApcRundown(), PspExitNormalApc(), PspExitThread(), Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_TO_PROCESS, and ULongToPtr.
Referenced by NtTerminateProcess(), NtTerminateThread(), PspSystemThreadStartup(), PspTerminateProcess(), PspUserThreadStartup(), and PsTerminateSystemThread().
VOID PspThreadDelete (IN PVOID Object)
Definition at line 1631 of file psdelete.c.
References ASSERT, _ETHREAD::Cid, CID_HANDLE_DELETION, ExDestroyHandle(), _LIST_ENTRY::Flink, _KTHREAD::InitialStack, KeBugCheck(), _KTHREAD::LargeStack, MmDeleteKernelStack(), NULL, ObDereferenceObject(), PAGED_CODE, PsGetCurrentThread(), PspCidTable, PspDeleteThreadSecurity(), PspLockProcessExclusive(), PspUnlockProcessExclusive(), RemoveEntryList(), _KTHREAD::StackBase, _ETHREAD::Tcb, THREAD_TO_PROCESS, _ETHREAD::ThreadListEntry, _CLIENT_ID::UniqueThread, and _KTHREAD::Win32Thread.
Referenced by PspInitPhase0().
NTSTATUS PspWaitForUsermodeExit (IN PEPROCESS Process)
Definition at line 471 of file psdelete.c.
References Executive, FALSE, IS_SYSTEM_THREAD, KeReadStateThread(), KernelMode, KeWaitForSingleObject(), NULL, ObDereferenceObject(), ObReferenceObject, PsGetNextProcessThread(), PsQuitNextProcessThread(), STATUS_SUCCESS, _ETHREAD::Tcb, and TRUE.
Referenced by PsShutdownSystem().
ULONG PsSetBBTNotifyRoutine (__in PBBT_NOTIFY_ROUTINE BBTNotifyRoutine)
Definition at line 73 of file psdelete.c.
References FIELD_OFFSET, PAGED_CODE, and PspBBTNotifyRoutine.
LOGICAL PsShutdownSystem (VOID)
Definition at line 1854 of file psdelete.c.
References ASSERT, CONTAINING_RECORD, _SYSTEM_DLL::DllBase, Executive, FALSE, _EPROCESS::Flags, InterlockedCompareExchangePointer, KernelMode, KeWaitForMultipleObjects(), MmGetSessionId(), MmUnmapViewOfSection(), NULL, ObDereferenceObject(), ObReferenceObject, PAGED_CODE, _EPROCESS::Pcb, PoCleanShutdownEnabled(), PS_PROCESS_FLAGS_PROCESS_EXITING, PsContinueWaiting, PsEnumProcesses(), PsGetCurrentThread(), PsGetNextProcess(), PsIdleProcess, PsInitialSystemProcess, PspFreezeProcessWorker(), PspInitialSystemProcessHandle, PspShutdownJobLimits(), PspShutdownThread, PspSystemDll, PspWaitForUsermodeExit(), PsTerminateProcess(), _SYSTEM_DLL::Section, _EPROCESS::SecurityPort, Status, STATUS_NOTHING_TO_TERMINATE, STATUS_SUCCESS, STATUS_SYSTEM_SHUTDOWN, STATUS_TIMEOUT, TRUE, WAIT_BATCH, WaitAny, and ZwClose().
NTSTATUS PsTerminateProcess (PEPROCESS Process, NTSTATUS Status)
Definition at line 396 of file psdelete.c.
References PspTerminateProcess().
Referenced by PsShutdownSystem().
NTSTATUS PsTerminateSystemThread (__in NTSTATUS ExitStatus)
Definition at line 602 of file psdelete.c.
References IS_SYSTEM_THREAD, PsGetCurrentThread(), PspTerminateThreadByPointer(), STATUS_INVALID_PARAMETER, and TRUE.
Referenced by CmpLoadHiveThread(), ExpShutdownWorker(), ExpWorkerThread(), ExpWorkerThreadBalanceManager(), and WmipLogger().
BOOLEAN PsWaitForAllProcesses (VOID)
Definition at line 2035 of file psdelete.c.
References Executive, FALSE, _EPROCESS::Flags, KdPrint, KernelMode, KeWaitForSingleObject(), NULL, ObDereferenceObject(), _EPROCESS::ObjectTable, ObReferenceObject, PS_PROCESS_FLAGS_PROCESS_EXITING, PsGetNextProcess(), PsIdleProcess, PsInitialSystemProcess, PsProcessType, PsQuitNextProcess(), _LARGE_INTEGER::QuadPart, Status, STATUS_TIMEOUT, _OBJECT_TYPE::TotalNumberOfObjects, and TRUE.
Variable Documentation
PEPROCESS ExpDefaultErrorPortProcess
Definition at line 63 of file harderr.c.
BOOLEAN PsContinueWaiting = FALSE
Definition at line 1850 of file psdelete.c.
Referenced by PsShutdownSystem().
PBBT_NOTIFY_ROUTINE PspBBTNotifyRoutine = NULL
Definition at line 70 of file psdelete.c.
Referenced by PspExitThread(), and PsSetBBTNotifyRoutine().
LARGE_INTEGER ShortTime = {(ULONG)(-10 * 1000 * 100), -1}
Definition at line 64 of file psdelete.c.