Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmwrapr.c File Reference
cmwrapr.c File Reference
#include "cmp.h"
Macros
#define CmpIoFileFlush 4
#define CmpIoFileRead 1
#define CmpIoFileSetSize 3
#define CmpIoFileWrite 2
#define MAX_FILE_IO 0x10000
Functions
PVOID CmpAllocate (ULONG Size, BOOLEAN UseForIo, ULONG Tag)
NTSTATUS CmpCreateEvent (IN EVENT_TYPE eventType, OUT PHANDLE eventHandle, OUT PKEVENT *event)
NTSTATUS CmpDoFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
BOOLEAN CmpFileFlush (PHHIVE Hive, ULONG FileType, PLARGE_INTEGER FileOffset, ULONG Length)
BOOLEAN CmpFileRead (PHHIVE Hive, ULONG FileType, PULONG FileOffset, PVOID DataBuffer, ULONG DataLength)
BOOLEAN CmpFileWrite (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount, PULONG FileOffset)
BOOLEAN CmpFileWriteThroughCache (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount)
VOID CmpFree (PVOID MemoryBlock, ULONG GlobalQuotaSize)
VOID CmpUnmapCmViewSurroundingOffset (IN PCMHIVE CmHive, IN ULONG FileOffset)
Variables
BOOLEAN CmpFlushOnLockRelease
BOOLEAN CmpNoWrite
struct {
ULONG Action
HANDLE Handle
NTSTATUS Status
} CmRegistryIODebug
ULONG perftouchbuffer = 0
Macro Definition Documentation
#define CmpIoFileFlush 4
Definition at line 59 of file cmwrapr.c.
Referenced by CmpFileFlush().
#define CmpIoFileRead 1
Definition at line 56 of file cmwrapr.c.
Referenced by CmpFileRead().
#define CmpIoFileSetSize 3
Definition at line 58 of file cmwrapr.c.
Referenced by CmpDoFileSetSize().
#define CmpIoFileWrite 2
Definition at line 57 of file cmwrapr.c.
Referenced by CmpFileWrite().
#define MAX_FILE_IO 0x10000
Definition at line 54 of file cmwrapr.c.
Referenced by CmpFileRead(), and CmpFileWrite().
Function Documentation
PVOID CmpAllocate (ULONG Size, BOOLEAN UseForIo, ULONG Tag)
Definition at line 74 of file cmwrapr.c.
References CmKdPrintEx, CML_POOL, CmpClaimGlobalQuota(), CmpReleaseGlobalQuota(), DPFLTR_CONFIG_ID, ExAllocatePoolWithTag, FALSE, NULL, PagedPool, PagedPoolCacheAligned, and RtlGetCallersAddress().
Referenced by CmpInitializeHive().
NTSTATUS CmpCreateEvent (IN EVENT_TYPE eventType, OUT PHANDLE eventHandle, OUT PKEVENT * event)
Definition at line 374 of file cmwrapr.c.
References EVENT_ALL_ACCESS, FALSE, InitializeObjectAttributes, KernelMode, NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, ZwClose(), and ZwCreateEvent().
Referenced by CmpFileRead(), CmpFileWrite(), and CmpOpenHiveFiles().
NTSTATUS CmpDoFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
Definition at line 231 of file cmwrapr.c.
References _256K, ASSERT, ASSERT_HIVE_WRITER_LOCK_OWNED, ASSERT_PASSIVE_LEVEL, CcFlushCache(), CcPurgeCacheSection(), CM_FILE_GROW_INCREMENT, CM_VIEW_SIZE, CmpFlushOnLockRelease, CmpIoFileSetSize, CmpRegistryLock, CmpUnmapCmViewSurroundingOffset(), CmRegistryIODebug, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, _FILE_END_OF_FILE_INFORMATION::EndOfFile, ExIsResourceAcquiredExclusiveLite(), FALSE, FIELD_OFFSET, FileEndOfFileInformation, _CMHIVE::FileHandles, FileOffset, HFILE_TYPE_PRIMARY, _LARGE_INTEGER::HighPart, HiveWritesThroughCache, IoSetThreadHardErrorMode(), _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, ROUND_UP, Status, _IO_STATUS_BLOCK::Status, STATUS_DISK_FULL, TRUE, and ZwSetInformationFile().
Referenced by CmpFileSetSize(), HvpDoWriteHive(), HvpWriteLog(), and HvWriteHive().
BOOLEAN CmpFileFlush (PHHIVE Hive, ULONG FileType, PLARGE_INTEGER FileOffset, ULONG Length)
Definition at line 989 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CcFlushCache(), CmKdPrintEx, CML_IO, CmpIoFileFlush, CmpNoWrite, CmRegistryIODebug, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, _CMHIVE::FileObject, HiveWritesThroughCache, NT_SUCCESS, NULL, _FILE_OBJECT::SectionObjectPointer, _IO_STATUS_BLOCK::Status, TRUE, and ZwFlushBuffersFile().
Referenced by CmpInitializeHive(), and CmpSaveKeyByFileCopy().
BOOLEAN CmpFileRead (PHHIVE Hive, ULONG FileType, PULONG FileOffset, PVOID DataBuffer, ULONG DataLength)
Definition at line 411 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmpCreateEvent(), CmpIoFileRead, CmRegistryIODebug, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_TRACE_LEVEL, Executive, FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, FileOffset, _LARGE_INTEGER::HighPart, _IO_STATUS_BLOCK::Information, KernelMode, KeWaitForSingleObject(), _LARGE_INTEGER::LowPart, MAX_FILE_IO, NT_SUCCESS, NULL, ObDereferenceObject(), _IO_STATUS_BLOCK::Status, STATUS_PENDING, STATUS_SUCCESS, SynchronizationEvent, TRUE, ZwClose(), and ZwReadFile().
Referenced by CmpInitializeHive(), and CmpSaveKeyByFileCopy().
BOOLEAN CmpFileWrite (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount, PULONG FileOffset)
Definition at line 704 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CmCloseHandle, CmKdPrintEx, CML_BUGCHECK, CML_IO, CmpCreateEvent(), CmpIoFileWrite, CmpNoWrite, CmpSetHandleProtection, CmRegistryIODebug, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, DPFLTR_TRACE_LEVEL, _CM_WRITE_BLOCK::EventHandles, _CM_WRITE_BLOCK::EventObjects, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, FIELD_OFFSET, _CMHIVE::FileHandles, FileOffset, CMP_OFFSET_ARRAY::FileOffset, _LARGE_INTEGER::HighPart, _CM_WRITE_BLOCK::IoStatus, KernelMode, KeWaitForMultipleObjects(), _LARGE_INTEGER::LowPart, MAX_FILE_IO, MAXIMUM_WAIT_OBJECTS, NonPagedPool, NT_SUCCESS, NULL, ObDereferenceObject(), PAGE_SIZE, perftouchbuffer, _IO_STATUS_BLOCK::Status, STATUS_INVALID_PARAMETER_5, SynchronizationEvent, TRUE, WaitAll, _CM_WRITE_BLOCK::WaitBlockArray, and ZwWriteFile().
Referenced by CmpInitializeHive(), and CmpSaveKeyByFileCopy().
BOOLEAN CmpFileWriteThroughCache (PHHIVE Hive, ULONG FileType, PCMP_OFFSET_ARRAY offsetArray, ULONG offsetArrayCount)
Definition at line 579 of file cmwrapr.c.
References ASSERT, ASSERT_PASSIVE_LEVEL, CcFlushCache(), CcPinRead(), CcSetDirtyPinnedData(), CcUnpinData(), CM_VIEW_SIZE, CmKdPrintEx, CONTAINING_RECORD, CMP_OFFSET_ARRAY::DataBuffer, CMP_OFFSET_ARRAY::DataLength, DbgBreakPoint(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CMHIVE::FileObject, FileOffset, CMP_OFFSET_ARRAY::FileOffset, HFILE_TYPE_EXTERNAL, _LARGE_INTEGER::HighPart, HiveWritesThroughCache, _LARGE_INTEGER::LowPart, NT_SUCCESS, NULL, PIN_WAIT, RtlCopyMemory, _FILE_OBJECT::SectionObjectPointer, _IO_STATUS_BLOCK::Status, TRUE, and UNREFERENCED_PARAMETER.
Referenced by HvpDoWriteHive(), and HvWriteHive().
VOID CmpFree (PVOID MemoryBlock, ULONG GlobalQuotaSize)
Definition at line 192 of file cmwrapr.c.
References ASSERT, CmKdPrintEx, CML_POOL, CmpReleaseGlobalQuota(), DPFLTR_CONFIG_ID, ExFreePool(), and RtlGetCallersAddress().
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), CmUnloadKey(), HvFreeHive(), HvFreeHivePartial(), HvpDoWriteHive(), HvpDropAllPagedBins(), and HvpDropPagedBins().
VOID CmpUnmapCmViewSurroundingOffset (IN PCMHIVE CmHive, IN ULONG FileOffset)
Definition at line 616 of file cmmapvw.c.
Referenced by CmpDoFileSetSize().
Variable Documentation
ULONG Action
Definition at line 62 of file cmwrapr.c.
BOOLEAN CmpFlushOnLockRelease
Definition at line 56 of file cmsubs3.c.
Referenced by CmpDoFileSetSize().
BOOLEAN CmpNoWrite
Definition at line 330 of file cmdat.c.
Referenced by CmpFileFlush(), and CmpFileWrite().
struct { ... } CmRegistryIODebug
Referenced by CmpDoFileSetSize(), CmpFileFlush(), CmpFileRead(), and CmpFileWrite().
HANDLE Handle
Definition at line 63 of file cmwrapr.c.
ULONG perftouchbuffer = 0
Definition at line 31 of file cmwrapr.c.
Referenced by CmpFileWrite().
NTSTATUS Status
Definition at line 64 of file cmwrapr.c.
Referenced by CmpDoFileSetSize().