Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcp.h File Reference
lpcp.h File Reference
#include "ntos.h"
#include <zwapi.h>
Data Structures
struct _LPC_MUTEX
Macros
#define ENABLE_LPC_TRACING 0
#define LPCP_MUTEX_OWNED 0x1
#define LPCP_MUTEX_RELEASE_ON_RETURN 0x2
#define LPCP_NO_IMPERSONATION 2
#define LPCP_PORT_BIT 1
#define LPCP_THREAD_ATTRIBUTES (LPCP_PORT_BIT | LPCP_NO_IMPERSONATION)
#define LPCP_VALIDATE_REASON_IMPERSONATION 1
#define LPCP_VALIDATE_REASON_REPLY 2
#define LPCP_VALIDATE_REASON_WRONG_DATA 3
#define LpcpAcquireLpcpLock()
#define LpcpAcquireLpcpLockByThread(Thread)
#define LpcpFreeDynamicClientSecurity(DynamicSecurity) SeDeleteClientSecurity(DynamicSecurity)
#define LpcpGenerateCallbackId() LpcpNextCallbackId++; if (LpcpNextCallbackId == 0) LpcpNextCallbackId = 1;
#define LpcpGenerateMessageId() LpcpNextMessageId++; if (LpcpNextMessageId == 0) LpcpNextMessageId = 1;
#define LpcpGetDynamicClientSecurity(Thread, Port, DynamicSecurity) SeCreateClientSecurity((Thread),&(Port)->SecurityQos,FALSE,(DynamicSecurity))
#define LpcpGetMaxMessageLength() (LpcpMaxMessageSize)
#define LpcpGetThreadAttributes(T) (((ULONG_PTR)(T)->LpcWaitingOnPort) & LPCP_THREAD_ATTRIBUTES)
#define LpcpGetThreadMessage(T)
#define LpcpGetThreadPort(T)
#define LpcpInitializeLpcpLock()
#define LpcpInitilizeLogging()
#define LpcpLogEntry(_Status_, _ClientId_, _PortMessage_)
#define LpcpPrint(_x_)
#define LpcpReferencePortObject(PortHandle, PortAccess, PreviousMode, PortObject) ObReferenceObjectByHandle((PortHandle),(PortAccess),LpcPortObjectType,(PreviousMode),(PVOID *)(PortObject),NULL)
#define LpcpReleaseLpcpLock()
#define LpcpSetPortToThread(T, P) (T)->LpcWaitingOnPort = (PVOID)(((ULONG_PTR)P) | LPCP_PORT_BIT);
#define LpcpSetThreadAttributes(T, A) (T)->LpcWaitingOnPort = (PVOID)(((ULONG_PTR)(T)->LpcWaitingOnPort) | (A));
#define LpcpTrace(_x_)
#define LpcpTraceError(_Status_, _ClientId_, _PortMessage_)
Typedefs
typedef struct _LPC_MUTEX LPC_MUTEX
typedef struct _LPC_MUTEX * PLPC_MUTEX
Functions
__forceinline PLPCP_MESSAGE LpcpAllocateFromPortZone (ULONG Size)
VOID LpcpClosePort (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
VOID LpcpDeletePort (IN PVOID Object)
VOID LpcpDestroyPortQueue (IN PLPCP_PORT_OBJECT Port, IN BOOLEAN CleanupAndDestroy)
NTSTATUS LpcpExtendPortZone (VOID)
PLPCP_MESSAGE LpcpFindDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
VOID LpcpFreeDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
VOID LpcpFreePortClientSecurity (IN PLPCP_PORT_OBJECT Port)
VOID FASTCALL LpcpFreeToPortZone (IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
NTSTATUS LpcpInitializePortQueue (IN PLPCP_PORT_OBJECT Port)
VOID LpcpInitializePortZone (IN ULONG MaxEntrySize)
VOID LpcpMoveMessage (OUT PPORT_MESSAGE DstMsg, IN PPORT_MESSAGE SrcMsg, IN PVOID SrcMsgData, IN ULONG MsgType OPTIONAL, IN PCLIENT_ID ClientId OPTIONAL)
VOID LpcpSaveDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
BOOLEAN FASTCALL LpcpValidateClientPort (IN PETHREAD Thread, IN PLPCP_PORT_OBJECT ReplyPort, IN ULONG Reason)
Variables
LPC_MUTEX LpcpLock
ULONG LpcpMaxMessageSize
PAGED_LOOKASIDE_LIST LpcpMessagesLookaside
ULONG LpcpNextCallbackId
ULONG LpcpNextMessageId
ULONG LpcpTotalNumberOfMessages
Macro Definition Documentation
#define ENABLE_LPC_TRACING 0
Definition at line 296 of file lpcp.h.
#define LPCP_MUTEX_OWNED 0x1
Definition at line 364 of file lpcp.h.
Referenced by LpcExitThread(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpRequestWaitReplyPort(), LpcpSaveDataInfoMessage(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), and NtRequestWaitReplyPort().
#define LPCP_MUTEX_RELEASE_ON_RETURN 0x2
Definition at line 365 of file lpcp.h.
Referenced by LpcExitThread(), LpcpFreeToPortZone(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), and NtRequestWaitReplyPort().
#define LPCP_NO_IMPERSONATION 2
Definition at line 250 of file lpcp.h.
Referenced by NtImpersonateClientOfPort(), and NtRequestWaitReplyPort().
#define LPCP_PORT_BIT 1
Definition at line 249 of file lpcp.h.
#define LPCP_THREAD_ATTRIBUTES (LPCP_PORT_BIT | LPCP_NO_IMPERSONATION)
Definition at line 252 of file lpcp.h.
#define LPCP_VALIDATE_REASON_IMPERSONATION 1
Definition at line 276 of file lpcp.h.
Referenced by NtImpersonateClientOfPort().
#define LPCP_VALIDATE_REASON_REPLY 2
Definition at line 277 of file lpcp.h.
Referenced by LpcpRequestWaitReplyPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
#define LPCP_VALIDATE_REASON_WRONG_DATA 3
Definition at line 278 of file lpcp.h.
Referenced by LpcpCopyRequestData().
#define LpcpAcquireLpcpLock ()
Value:
{                                                                   \
    ASSERT ( LpcpLock.Owner != PsGetCurrentThread() );              \
                                                                    \
    KeAcquireGuardedMutex( &LpcpLock.Lock );                        \
    LpcpLock.Owner = PsGetCurrentThread();                          \
}
Definition at line 81 of file lpcp.h.
Referenced by LpcpCopyRequestData(), LpcpDestroyPortQueue(), LpcpFreeConMsg(), LpcpFreeToPortZone(), LpcpSaveDataInfoMessage(), NtAcceptConnectPort(), NtCompleteConnectPort(), and NtImpersonateClientOfPort().
#define LpcpAcquireLpcpLockByThread (Thread)
Value:
{                                                                   \
    ASSERT ( LpcpLock.Owner != PsGetCurrentThread() );              \
                                                                    \
    KeAcquireGuardedMutex( &LpcpLock.Lock );                        \
    LpcpLock.Owner = Thread;                                        \
}
Definition at line 89 of file lpcp.h.
Referenced by LpcExitThread(), LpcpDeletePort(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define LpcpFreeDynamicClientSecurity (DynamicSecurity) SeDeleteClientSecurity(DynamicSecurity)
Definition at line 242 of file lpcp.h.
Referenced by NtImpersonateClientOfPort().
#define LpcpGenerateCallbackId () LpcpNextCallbackId++; if (LpcpNextCallbackId == 0) LpcpNextCallbackId = 1;
Definition at line 65 of file lpcp.h.
Referenced by LpcpRequestWaitReplyPort(), and NtRequestWaitReplyPort().
#define LpcpGenerateMessageId () LpcpNextMessageId++; if (LpcpNextMessageId == 0) LpcpNextMessageId = 1;
Definition at line 62 of file lpcp.h.
Referenced by LpcpRequestWaitReplyPort(), LpcRequestPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define LpcpGetDynamicClientSecurity (Thread, Port, DynamicSecurity) SeCreateClientSecurity((Thread),&(Port)->SecurityQos,FALSE,(DynamicSecurity))
Definition at line 239 of file lpcp.h.
Referenced by NtImpersonateClientOfPort().
#define LpcpGetMaxMessageLength () (LpcpMaxMessageSize)
Definition at line 56 of file lpcp.h.
Referenced by LpcpCreatePort().
#define LpcpGetThreadAttributes (T) (((ULONG_PTR)(T)->LpcWaitingOnPort) & LPCP_THREAD_ATTRIBUTES)
Definition at line 267 of file lpcp.h.
Referenced by NtImpersonateClientOfPort().
#define LpcpGetThreadMessage (T)
Value:
(\
        (((ULONG_PTR)(T)->LpcReplyMessage) & LPCP_PORT_BIT) ? NULL :             \
            (PLPCP_MESSAGE)((ULONG_PTR)(T)->LpcReplyMessage & ~LPCP_THREAD_ATTRIBUTES)      \
    )
Definition at line 254 of file lpcp.h.
Referenced by LpcExitThread(), LpcpDestroyPortQueue(), LpcpFreeConMsg(), LpcpRequestWaitReplyPort(), NtAcceptConnectPort(), NtCompleteConnectPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
#define LpcpGetThreadPort (T)
Value:
(\
        (((ULONG_PTR)(T)->LpcReplyMessage) & LPCP_PORT_BIT) ?                    \
            (PLPCP_PORT_OBJECT)(((ULONG_PTR)(T)->LpcWaitingOnPort) & ~LPCP_THREAD_ATTRIBUTES):     \
            NULL                                                                 \
    )
Definition at line 260 of file lpcp.h.
Referenced by LpcpValidateClientPort().
#define LpcpInitializeLpcpLock ()
Value:
{                                                            \
    KeInitializeGuardedMutex( &LpcpLock.Lock );              \
    LpcpLock.Owner = NULL;                                   \
}
Definition at line 75 of file lpcp.h.
Referenced by LpcInitSystem().
#define LpcpInitilizeLogging ()
Definition at line 374 of file lpcp.h.
Referenced by LpcInitSystem().
#define LpcpLogEntry (_Status_, _ClientId_, _PortMessage_)
Definition at line 375 of file lpcp.h.
#define LpcpPrint (_x_)
Definition at line 321 of file lpcp.h.
Referenced by LpcpCreatePort(), NtAcceptConnectPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
#define LpcpReferencePortObject (PortHandle, PortAccess, PreviousMode, PortObject) ObReferenceObjectByHandle((PortHandle),(PortAccess),LpcPortObjectType,(PreviousMode),(PVOID *)(PortObject),NULL)
Definition at line 245 of file lpcp.h.
Referenced by LpcpCopyRequestData(), NtCompleteConnectPort(), NtImpersonateClientOfPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), and NtRequestWaitReplyPort().
#define LpcpReleaseLpcpLock ()
Value:
{                                                                   \
    ASSERT( LpcpLock.Owner == PsGetCurrentThread() );               \
                                                                    \
    LpcpLock.Owner = NULL;                                          \
    KeReleaseGuardedMutex( &LpcpLock.Lock );                        \
}
Definition at line 97 of file lpcp.h.
Referenced by LpcExitThread(), LpcpCopyRequestData(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeConMsg(), LpcpFreeToPortZone(), LpcpRequestWaitReplyPort(), LpcpSaveDataInfoMessage(), LpcRequestPort(), NtAcceptConnectPort(), NtCompleteConnectPort(), NtImpersonateClientOfPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define LpcpSetPortToThread (T, P) (T)->LpcWaitingOnPort = (PVOID)(((ULONG_PTR)P) | LPCP_PORT_BIT);
Definition at line 273 of file lpcp.h.
Referenced by LpcpRequestWaitReplyPort(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
#define LpcpSetThreadAttributes (T, A) (T)->LpcWaitingOnPort = (PVOID)(((ULONG_PTR)(T)->LpcWaitingOnPort) | (A));
Definition at line 270 of file lpcp.h.
Referenced by NtRequestWaitReplyPort().
#define LpcpTrace (_x_)
Definition at line 322 of file lpcp.h.
Referenced by LpcExitThread(), LpcpAllocateFromPortZone(), LpcpCreatePort(), LpcpDeletePort(), LpcpFindDataInfoMessage(), LpcpFreeDataInfoMessage(), LpcpRequestWaitReplyPort(), LpcpSaveDataInfoMessage(), LpcRequestPort(), NtAcceptConnectPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
#define LpcpTraceError (_Status_, _ClientId_, _PortMessage_)
Definition at line 376 of file lpcp.h.
Referenced by NtReplyPort(), NtReplyWaitReceivePortEx(), and NtReplyWaitReplyPort().
Typedef Documentation
typedef struct _LPC_MUTEX LPC_MUTEX
typedef struct _LPC_MUTEX * PLPC_MUTEX
Function Documentation
__forceinline PLPCP_MESSAGE LpcpAllocateFromPortZone (ULONG Size)
Definition at line 330 of file lpcp.h.
References _LPCP_MESSAGE::Entry, ExAllocateFromPagedLookasideList(), InitializeListHead(), LpcpTrace, NULL, PAGED_CODE, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _PORT_MESSAGE::u2, and UNREFERENCED_PARAMETER.
Referenced by LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
VOID LpcpClosePort (IN PEPROCESS Process OPTIONAL, IN PVOID Object, IN ACCESS_MASK GrantedAccess, IN ULONG_PTR ProcessHandleCount, IN ULONG_PTR SystemHandleCount)
Definition at line 30 of file lpcclose.c.
References FALSE, _LPCP_PORT_OBJECT::Flags, LpcpDestroyPortQueue(), PORT_TYPE, SERVER_CONNECTION_PORT, TRUE, and UNREFERENCED_PARAMETER.
Referenced by LpcInitSystem().
VOID LpcpDeletePort (IN PVOID Object)
Definition at line 113 of file lpcclose.c.
References _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ClientSectionBase, _LPCP_PORT_OBJECT::ClientThread, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, CONTAINING_RECORD, _LPC_CLIENT_DIED_MSG::CreateTime, _EPROCESS::CreateTime, _LPCP_MESSAGE::Entry, FALSE, _LPCP_PORT_OBJECT::Flags, _LIST_ENTRY::Flink, InitializeListHead(), KeDelayExecutionThread(), KernelMode, LPC_PORT_CLOSED, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LPCP_MUTEX_OWNED, LpcpAcquireLpcpLockByThread, LpcpDestroyPortQueue(), LpcpFreePortClientSecurity(), LpcpFreeToPortZone(), LpcpReleaseLpcpLock, LpcpTrace, LpcRequestPort(), _LPCP_PORT_OBJECT::MappingProcess, _PORT_MESSAGE::MessageId, MmUnmapViewOfSection(), NULL, ObDereferenceObject(), PAGED_CODE, PORT_TYPE, _LPC_CLIENT_DIED_MSG::PortMsg, PsGetCurrentProcess(), PsGetCurrentThread(), RemoveEntryList(), _LPCP_MESSAGE::Request, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_MESSAGE::SenderPort, SERVER_COMMUNICATION_PORT, SERVER_CONNECTION_PORT, _LPCP_PORT_OBJECT::ServerProcess, _LPCP_PORT_OBJECT::ServerSectionBase, Status, STATUS_NO_MEMORY, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, and _CLIENT_ID::UniqueProcess.
Referenced by LpcInitSystem().
VOID LpcpDestroyPortQueue (IN PLPCP_PORT_OBJECT Port, IN BOOLEAN CleanupAndDestroy)
Definition at line 115 of file lpcqueue.c.
References _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, CONTAINING_RECORD, _LPCP_MESSAGE::Entry, ExFreePool(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), IsListEmpty, KeReadStateSemaphore(), KeReleaseSemaphore(), LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LpcpAcquireLpcpLock, LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpReleaseLpcpLock, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, NULL, ObDereferenceObject(), PAGED_CODE, PORT_NAME_DELETED, PORT_TYPE, RemoveEntryList(), _LPCP_MESSAGE::Request, _PORT_MESSAGE::s2, _LPCP_CONNECTION_MESSAGE::SectionToMap, SERVER_CONNECTION_PORT, _PORT_MESSAGE::u2, and UNCONNECTED_COMMUNICATION_PORT.
Referenced by LpcDisconnectPort(), LpcpClosePort(), and LpcpDeletePort().
NTSTATUS LpcpExtendPortZone (VOID)
PLPCP_MESSAGE LpcpFindDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
Definition at line 640 of file lpcqueue.c.
References _PORT_MESSAGE::CallbackId, _PORT_MESSAGE::ClientId, CONTAINING_RECORD, _LIST_ENTRY::Flink, LpcpTrace, _PORT_MESSAGE::MessageId, NULL, PAGED_CODE, PORT_TYPE, PsGetCurrentProcess(), _LPCP_MESSAGE::Request, and UNCONNECTED_COMMUNICATION_PORT.
Referenced by LpcpCopyRequestData().
VOID LpcpFreeDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN ULONG MessageId, IN ULONG CallbackId, IN LPC_CLIENT_ID ClientId)
Definition at line 532 of file lpcqueue.c.
References _PORT_MESSAGE::CallbackId, _PORT_MESSAGE::ClientId, CONTAINING_RECORD, _LPCP_MESSAGE::Entry, _LIST_ENTRY::Flink, InitializeListHead(), LPCP_MUTEX_OWNED, LpcpFreeToPortZone(), LpcpTrace, _PORT_MESSAGE::MessageId, NULL, PAGED_CODE, PORT_TYPE, PsGetCurrentProcess(), RemoveEntryList(), _LPCP_MESSAGE::Request, and UNCONNECTED_COMMUNICATION_PORT.
Referenced by NtReplyPort(), NtReplyWaitReceivePortEx(), and NtReplyWaitReplyPort().
VOID LpcpFreePortClientSecurity (IN PLPCP_PORT_OBJECT Port)
Definition at line 285 of file lpcpriv.c.
References CLIENT_COMMUNICATION_PORT, PORT_DYNAMIC_SECURITY, PORT_TYPE, and SeDeleteClientSecurity.
Referenced by LpcpDeletePort().
VOID FASTCALL LpcpFreeToPortZone (IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
Definition at line 356 of file lpcqueue.c.
References _LPCP_CONNECTION_MESSAGE::ClientPort, ExFreeToPagedLookasideList(), InitializeListHead(), IsListEmpty, LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LpcpAcquireLpcpLock, LpcpMessagesLookaside, LpcpReleaseLpcpLock, NULL, ObDereferenceObject(), PAGED_CODE, and RemoveEntryList().
Referenced by LpcExitThread(), LpcpDeletePort(), LpcpDestroyPortQueue(), LpcpFreeDataInfoMessage(), LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), NtRequestWaitReplyPort(), and NtSecureConnectPort().
NTSTATUS LpcpInitializePortQueue (IN PLPCP_PORT_OBJECT Port)
Definition at line 48 of file lpcqueue.c.
References _LPCP_NONPAGED_PORT_QUEUE::BackPointer, ExAllocatePoolWithTag, InitializeListHead(), KeInitializeSemaphore(), _LPCP_PORT_OBJECT::MsgQueue, NonPagedPool, NULL, PAGED_CODE, _LPCP_NONPAGED_PORT_QUEUE::Semaphore, _LPCP_PORT_QUEUE::Semaphore, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by LpcpCreatePort(), and NtSecureConnectPort().
VOID LpcpInitializePortZone (IN ULONG MaxEntrySize)
Definition at line 337 of file lpcqueue.c.
References ExInitializePagedLookasideList(), LpcpMaxMessageSize, LpcpMessagesLookaside, and NULL.
Referenced by LpcInitSystem().
VOID LpcpMoveMessage (OUT PPORT_MESSAGE DstMsg, IN PPORT_MESSAGE SrcMsg, IN PVOID SrcMsgData, IN ULONG MsgType OPTIONAL, IN PCLIENT_ID ClientId OPTIONAL)
Referenced by LpcpRequestWaitReplyPort(), LpcRequestPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), NtRequestPort(), and NtRequestWaitReplyPort().
VOID LpcpSaveDataInfoMessage (IN PLPCP_PORT_OBJECT Port, IN PLPCP_MESSAGE Msg, IN ULONG MutexFlags)
Definition at line 446 of file lpcqueue.c.
References InsertTailList(), LPCP_MUTEX_OWNED, LpcpAcquireLpcpLock, LpcpReleaseLpcpLock, LpcpTrace, NULL, PAGED_CODE, PORT_TYPE, PsGetCurrentProcess(), and UNCONNECTED_COMMUNICATION_PORT.
Referenced by NtReplyWaitReceivePortEx(), and NtRequestWaitReplyPort().
BOOLEAN FASTCALL LpcpValidateClientPort (IN PETHREAD Thread, IN PLPCP_PORT_OBJECT ReplyPort, IN ULONG Reason)
Definition at line 1247 of file lpcreply.c.
References _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, FALSE, LpcpGetThreadPort, NULL, PORT_TYPE, SERVER_COMMUNICATION_PORT, and TRUE.
Referenced by LpcpCopyRequestData(), LpcpRequestWaitReplyPort(), NtImpersonateClientOfPort(), NtReplyPort(), NtReplyWaitReceivePortEx(), NtReplyWaitReplyPort(), and NtRequestWaitReplyPort().
Variable Documentation
LPC_MUTEX LpcpLock
Definition at line 53 of file lpcinit.c.
ULONG LpcpMaxMessageSize
Definition at line 38 of file lpcqueue.c.
Referenced by LpcpInitializePortZone().
PAGED_LOOKASIDE_LIST LpcpMessagesLookaside
Definition at line 39 of file lpcqueue.c.
Referenced by LpcpFreeToPortZone(), and LpcpInitializePortZone().
ULONG LpcpNextCallbackId
Definition at line 43 of file lpcinit.c.
ULONG LpcpNextMessageId
Definition at line 42 of file lpcinit.c.
ULONG LpcpTotalNumberOfMessages
Definition at line 37 of file lpcqueue.c.