Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/intobj.c File Reference
intobj.c File Reference
#include "ki.h"
Functions
BOOLEAN KeConnectInterrupt (__inout PKINTERRUPT Interrupt)
BOOLEAN KeDisconnectInterrupt (__inout PKINTERRUPT Interrupt)
VOID KeInitializeInterrupt (__out PKINTERRUPT Interrupt, __in PKSERVICE_ROUTINE ServiceRoutine, __in_opt PVOID ServiceContext, __out_opt PKSPIN_LOCK SpinLock, __in ULONG Vector, __in KIRQL Irql, __in KIRQL SynchronizeIrql, __in KINTERRUPT_MODE InterruptMode, __in BOOLEAN ShareVector, __in CCHAR ProcessorNumber, __in BOOLEAN FloatingSave)
Function Documentation
BOOLEAN KeConnectInterrupt (__inout PKINTERRUPT Interrupt)
Definition at line 184 of file intobj.c.
References AFFINITY_MASK, CONTAINING_RECORD, _KINTERRUPT::DispatchAddress, FALSE, HalEnableSystemInterrupt(), HalVectorToIDTEntry, HIGH_LEVEL, InitializeListHead(), InsertTailList(), _KINTERRUPT::InterruptListEntry, KeLowerIrql, KeNumberProcessors, KeRaiseIrql, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiChainedDispatch(), KiInterruptDispatch(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KxUnexpectedInterrupt0, MAXIMUM_PRIMARY_VECTOR, _KINTERRUPT::Mode, PRIMARY_VECTOR_BASE, _KINTERRUPT::ShareVector, and TRUE.
BOOLEAN KeDisconnectInterrupt (__inout PKINTERRUPT Interrupt)
Definition at line 339 of file intobj.c.
References AFFINITY_MASK, CONTAINING_RECORD, _KINTERRUPT::DispatchAddress, _KINTERRUPT::DispatchCode, FALSE, _LIST_ENTRY::Flink, HalDisableSystemInterrupt(), HalVectorToIDTEntry, _KINTERRUPT::InterruptListEntry, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KiChainedDispatch(), KiInterruptDispatch(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KxUnexpectedInterrupt0, and RemoveEntryList().
Referenced by KeConnectInterrupt().
VOID KeInitializeInterrupt (__out PKINTERRUPT Interrupt, __in PKSERVICE_ROUTINE ServiceRoutine, __in_opt PVOID ServiceContext, __out_opt PKSPIN_LOCK SpinLock, __in ULONG Vector, __in KIRQL Irql, __in KIRQL SynchronizeIrql, __in KINTERRUPT_MODE InterruptMode, __in BOOLEAN ShareVector, __in CCHAR ProcessorNumber, __in BOOLEAN FloatingSave)
Definition at line 23 of file intobj.c.
References ARGUMENT_PRESENT, CPU_INTEL, FALSE, Index, InterruptObject, KeGetCurrentPrcb(), KeInitializeSpinLock(), KiInterruptDispatch(), KiInterruptDispatchLBControl(), KiInterruptDispatchNoLock(), KiInterruptTemplate, NORMAL_DISPATCH_LENGTH, and UNREFERENCED_PARAMETER.