Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/dbgk.h File Reference
dbgk.h File Reference
Data Structures
struct _DEBUG_OBJECT
Macros
#define DEBUG_OBJECT_DELETE_PENDING (0x1)
#define DEBUG_OBJECT_KILL_ON_CLOSE (0x2)
Typedefs
typedef struct _DEBUG_OBJECT DEBUG_OBJECT
typedef struct _DEBUG_OBJECT * PDEBUG_OBJECT
Functions
NTSTATUS DbgkClearProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT SourceDebugObject)
VOID DbgkCopyProcessDebugPort (IN PEPROCESS TargetProcess, IN PEPROCESS SourceProcess)
VOID DbgkCreateThread (PETHREAD Thread, PVOID StartAddress)
VOID DbgkExitProcess (NTSTATUS ExitStatus)
VOID DbgkExitThread (NTSTATUS ExitStatus)
BOOLEAN DbgkForwardException (IN PEXCEPTION_RECORD ExceptionRecord, IN BOOLEAN DebugException, IN BOOLEAN SecondChance)
NTSTATUS DbgkInitialize (VOID)
VOID DbgkMapViewOfSection (IN HANDLE SectionHandle, IN PVOID BaseAddress, IN ULONG SectionOffset, IN ULONG_PTR ViewSize)
NTSTATUS DbgkOpenProcessDebugPort (IN PEPROCESS TargetProcess, IN KPROCESSOR_MODE PreviousMode, OUT HANDLE *pHandle)
VOID DbgkUnMapViewOfSection (IN PVOID BaseAddress)
Variables
POBJECT_TYPE DbgkDebugObjectType
Macro Definition Documentation
#define DEBUG_OBJECT_DELETE_PENDING (0x1)
Definition at line 26 of file dbgk.h.
Referenced by DbgkCopyProcessDebugPort(), DbgkpCloseObject(), DbgkpQueueMessage(), DbgkpSetProcessDebugObject(), and NtWaitForDebugEvent().
#define DEBUG_OBJECT_KILL_ON_CLOSE (0x2)
Definition at line 27 of file dbgk.h.
Referenced by DbgkpCloseObject(), NtCreateDebugObject(), and NtSetInformationDebugObject().
Typedef Documentation
typedef struct _DEBUG_OBJECT DEBUG_OBJECT
typedef struct _DEBUG_OBJECT * PDEBUG_OBJECT
Function Documentation
NTSTATUS DbgkClearProcessDebugObject (IN PEPROCESS Process, IN PDEBUG_OBJECT SourceDebugObject)
Definition at line 734 of file dbgkobj.c.
References CONTAINING_RECORD, DbgkpMarkProcessPeb(), DbgkpWakeTarget(), _DEBUG_OBJECT::EventList, _DEBUG_EVENT::EventList, ExAcquireFastMutex(), ExReleaseFastMutex(), _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IsListEmpty, _DEBUG_OBJECT::Mutex, NT_SUCCESS, NULL, ObDereferenceObject(), PAGED_CODE, _DEBUG_EVENT::Process, RemoveEntryList(), RemoveHeadList(), _DEBUG_EVENT::Status, Status, STATUS_DEBUGGER_INACTIVE, STATUS_PORT_NOT_SET, and STATUS_SUCCESS.
Referenced by NtRemoveProcessDebug(), and NtTerminateProcess().
VOID DbgkCopyProcessDebugPort (IN PEPROCESS TargetProcess, IN PEPROCESS SourceProcess)
Definition at line 354 of file dbgkobj.c.
References DEBUG_OBJECT_DELETE_PENDING, ExAcquireFastMutex(), ExReleaseFastMutex(), _DEBUG_OBJECT::Flags, _DEBUG_OBJECT::Mutex, NULL, ObReferenceObject, PAGED_CODE, and PS_PROCESS_FLAGS_NO_DEBUG_INHERIT.
Referenced by PspCreateProcess().
VOID DbgkCreateThread (PETHREAD Thread, PVOID StartAddress)
Definition at line 175 of file dbgkproc.c.
References _DBGKM_LOAD_DLL::BaseOfDll, _DBGKM_CREATE_PROCESS::BaseOfImage, _DBGKM_APIMSG::CreateProcessInfo, _DBGKM_APIMSG::CreateThread, DBGKM_FORMAT_API_MSG, DbgKmCreateProcessApi, DbgKmCreateThreadApi, DbgKmLoadDllApi, DBGKP_FIELD_FROM_IMAGE_OPTIONAL_HEADER, DbgkpSectionToFileHandle(), DbgkpSendApiMessage(), _DBGKM_CREATE_PROCESS::DebugInfoFileOffset, _DBGKM_LOAD_DLL::DebugInfoFileOffset, _DBGKM_CREATE_PROCESS::DebugInfoSize, _DBGKM_LOAD_DLL::DebugInfoSize, _EPROCESS::DebugPort, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, FILE_SHARE_DELETE, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SYNCHRONOUS_IO_NONALERT, _DBGKM_CREATE_PROCESS::FileHandle, _DBGKM_LOAD_DLL::FileHandle, _IMAGE_NT_HEADERS::FileHeader, _EPROCESS::Flags, GENERIC_READ, IMAGE_ADDRESSING_MODE_32BIT, _IMAGE_INFO::ImageAddressingMode, _IMAGE_INFO::ImageBase, _IMAGE_INFO::ImageSectionNumber, _IMAGE_INFO::ImageSelector, _IMAGE_INFO::ImageSize, InitializeObjectAttributes, _DBGKM_CREATE_PROCESS::InitialThread, KernelMode, _DBGKM_APIMSG::LoadDll, MmGetFileNameForSection(), _OBJECT_NAME_INFORMATION::Name, _DBGKM_LOAD_DLL::NamePointer, NT_SUCCESS, NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, _IMAGE_INFO::Properties, PS_PROCESS_FLAGS_CREATE_REPORTED, PS_PROCESS_FLAGS_IMAGE_NOTIFY_DONE, PS_TEST_SET_BITS, PsCallImageNotifyRoutines(), PsGetCurrentProcessByThread, PsImageNotifyEnabled, PsNtDllPathName, PsSystemDllBase, RtlImageNtHeader(), RtlInitUnicodeString(), _EPROCESS::SectionBaseAddress, _EPROCESS::SectionObject, _DBGKM_CREATE_THREAD::StartAddress, Status, _DBGKM_CREATE_THREAD::SubSystemKey, _DBGKM_CREATE_PROCESS::SubSystemKey, SYNCHRONIZE, _ETHREAD::Tcb, _KTHREAD::Teb, TRUE, _DBGKM_APIMSG::u, UlongToPtr, _EPROCESS::UniqueProcessId, wcsncpy(), and ZwOpenFile().
Referenced by PspUserThreadStartup().
VOID DbgkExitProcess (NTSTATUS ExitStatus)
Definition at line 534 of file dbgkproc.c.
References DBGKM_FORMAT_API_MSG, DbgKmExitProcessApi, DbgkpSendApiMessage(), _EPROCESS::DebugPort, _DBGKM_APIMSG::ExitProcess, _DBGKM_EXIT_PROCESS::ExitStatus, _EPROCESS::ExitTime, FALSE, KeQuerySystemTime(), NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), and _DBGKM_APIMSG::u.
Referenced by PspExitThread().
VOID DbgkExitThread (NTSTATUS ExitStatus)
Definition at line 470 of file dbgkproc.c.
References DBGKM_FORMAT_API_MSG, DbgKmExitThreadApi, DbgkpResumeProcess(), DbgkpSendApiMessage(), DbgkpSuspendProcess(), _EPROCESS::DebugPort, _DBGKM_EXIT_THREAD::ExitStatus, _DBGKM_APIMSG::ExitThread, FALSE, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_DEADTHREAD, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), and _DBGKM_APIMSG::u.
Referenced by PspExitThread().
BOOLEAN DbgkForwardException (IN PEXCEPTION_RECORD ExceptionRecord, IN BOOLEAN DebugException, IN BOOLEAN SecondChance)
Definition at line 155 of file dbgkport.c.
References DBG_EXCEPTION_NOT_HANDLED, DBGKM_FORMAT_API_MSG, DbgKmExceptionApi, DbgkpSendApiMessage(), DbgkpSendApiMessageLpc(), _EPROCESS::DebugPort, _DBGKM_APIMSG::Exception, _EPROCESS::ExceptionPort, _DBGKM_EXCEPTION::ExceptionRecord, FALSE, _DBGKM_EXCEPTION::FirstChance, _DBGKM_APIMSG::h, LPC_EXCEPTION, NT_SUCCESS, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), _DBGKM_APIMSG::ReturnedStatus, TRUE, _DBGKM_APIMSG::u, _PORT_MESSAGE::u2, and _PORT_MESSAGE::ZeroInit.
Referenced by KiDispatchException().
NTSTATUS DbgkInitialize (VOID)
Definition at line 74 of file dbgkobj.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, DbgkpCloseObject(), DbgkpDeleteObject(), DEBUG_ALL_ACCESS, DEBUG_PROCESS_ASSIGN, DEBUG_READ_EVENT, _OBJECT_TYPE_INITIALIZER::DefaultNonPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, ExInitializeFastMutex, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, _OBJECT_TYPE_INITIALIZER::Length, NonPagedPool, NT_SUCCESS, NULL, ObCreateObjectType(), PAGED_CODE, _OBJECT_TYPE_INITIALIZER::PoolType, RtlInitUnicodeString(), _OBJECT_TYPE_INITIALIZER::SecurityRequired, STANDARD_RIGHTS_EXECUTE, STANDARD_RIGHTS_READ, STANDARD_RIGHTS_WRITE, Status, SYNCHRONIZE, TRUE, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ExpInitializeExecutive().
VOID DbgkMapViewOfSection (IN HANDLE SectionHandle, IN PVOID BaseAddress, IN ULONG SectionOffset, IN ULONG_PTR ViewSize)
Definition at line 597 of file dbgkproc.c.
References _DBGKM_LOAD_DLL::BaseOfDll, DBGKM_FORMAT_API_MSG, DbgKmLoadDllApi, DbgkpSectionToFileHandle(), DbgkpSendApiMessage(), _DBGKM_LOAD_DLL::DebugInfoFileOffset, _DBGKM_LOAD_DLL::DebugInfoSize, _EPROCESS::DebugPort, except, EXCEPTION_EXECUTE_HANDLER, _DBGKM_LOAD_DLL::FileHandle, _IMAGE_NT_HEADERS::FileHeader, KeGetPreviousMode, KernelMode, _DBGKM_APIMSG::LoadDll, _DBGKM_LOAD_DLL::NamePointer, NtCurrentTeb(), NULL, _IMAGE_FILE_HEADER::NumberOfSymbols, ObCloseHandle(), PAGED_CODE, _IMAGE_FILE_HEADER::PointerToSymbolTable, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), RtlImageNtHeader(), TRUE, _DBGKM_APIMSG::u, and UNREFERENCED_PARAMETER.
Referenced by NtMapViewOfSection().
NTSTATUS DbgkOpenProcessDebugPort (IN PEPROCESS TargetProcess, IN KPROCESSOR_MODE PreviousMode, OUT HANDLE * pHandle)
Definition at line 405 of file dbgkobj.c.
References ExAcquireFastMutex(), ExReleaseFastMutex(), MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObOpenObjectByPointer(), ObReferenceObject, PAGED_CODE, Status, and STATUS_PORT_NOT_SET.
Referenced by NtQueryInformationProcess().
VOID DbgkUnMapViewOfSection (IN PVOID BaseAddress)
Definition at line 699 of file dbgkproc.c.
References _DBGKM_UNLOAD_DLL::BaseAddress, DBGKM_FORMAT_API_MSG, DbgKmUnloadDllApi, DbgkpSendApiMessage(), _EPROCESS::DebugPort, KeGetPreviousMode, KernelMode, NULL, PAGED_CODE, PS_CROSS_THREAD_FLAGS_HIDEFROMDBG, PsGetCurrentProcess(), PsGetCurrentThread(), TRUE, _DBGKM_APIMSG::u, and _DBGKM_APIMSG::UnloadDll.
Referenced by MiUnmapViewOfSection().
Variable Documentation
POBJECT_TYPE DbgkDebugObjectType
Definition at line 66 of file dbgkobj.c.
Referenced by PspCreateProcess().