Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/perf.h File Reference
perf.h File Reference
#include <wmistr.h>
#include <ntwmi.h>
#include <ntperf.h>
Data Structures
struct _PERFINFO_ENTRY_TABLE
Macros
#define PERF_ASSERT_TRACING_OFF()
#define PERF_BRANCH_TRACING_BREAKPOINT(ExceptionRecord, TrapFrame)
#define PERF_BRANCH_TRACING_OFF_KD()
#define PERF_BRANCH_TRACING_ON_KD()
#define PERF_FINISH_HOOK(_HookHandle) WmiReleaseKernelBuffer((_HookHandle).WmiBufferHeader);
#define PERF_IS_BRANCH_TRACING_ON()
#define PERF_NULL_HOOK_HANDLE (PerfNullHookHandle)
#define PERF_PF_MODLOAD_DECL()
#define PERF_PF_MODLOAD_RESTORE()
#define PERF_PF_MODLOAD_SAVE()
#define PERF_PF_SANITIZE_CONTEXT(Context)
#define PERFINFO_ADD_OBJECT_TO_ALLOCATED_TYPE_LIST(CreatorInfo, ObjectType)
#define PERFINFO_ADDPOOLPAGE(CheckType, PoolIndex, Addr, PoolDesc)
#define PERFINFO_ADDTOWS(PageFrame, Address, Pid)
#define PERFINFO_BIGFOOT_REPLACEMENT_CLAIMS(WorkingSetList, WsInfo)
#define PERFINFO_BIGFOOT_REPLACEMENT_FAULTS(WorkingSetList, WsInfo)
#define PERFINFO_BIGPOOLALLOC(Type, PTag, NumBytes, Addr)
#define PERFINFO_CLEAR_OBJECT(CurrentState, Object)
#define PERFINFO_CONVERT_TO_GUI_THREAD(EThread)
#define PERFINFO_DECLARE_OB_ENUMERATE_ALLOCATED_OBJECTS_BY_TYPE()
#define PERFINFO_DECLARE_OBJECT(Object)
#define PERFINFO_DECREFCNT(PageFrame, Flag, Type)
#define PERFINFO_DEFINE_OB_ENUMERATE_ALLOCATED_OBJECTS_BY_TYPE()
#define PERFINFO_DELETE_STACK(PointerPte, NumberOfPtes)
#define PERFINFO_DETACH_PROCESS(KThread, KProcess)
#define PERFINFO_DO_PAGEFAULT_CLUSTERING() 1
#define PERFINFO_DRIVER_INTENTIONAL_DELAY()
#define PERFINFO_DRIVER_STACKTRACE()
#define PERFINFO_EXALLOCATEPOOLWITHTAG_DECL()
#define PERFINFO_EXFREEPOOLWITHTAG_DECL()
#define PERFINFO_FAULT_NOTIFICATION(Address, TrapInfo)
#define PERFINFO_FREEPOOL(Addr)
#define PERFINFO_FREEPOOLPAGE(CheckType, PoolIndex, Addr, PoolDesc)
#define PERFINFO_GET_PAGE_INFO(PointerPte)
#define PERFINFO_GET_PAGE_INFO_REPLACEMENT(PointerPte)
#define PERFINFO_GET_PAGE_INFO_WITH_DECL(PointerPte)
#define PERFINFO_GROW_STACK(EThread)
#define PERFINFO_HIBER_ADJUST_PAGECOUNT_FOR_BBTBUFFER(pPageCount)
#define PERFINFO_HIBER_DUMP_PERF_BUFFER()
#define PERFINFO_HIBER_HANDLE_BBTBUFFER_RANGE(HiberContext)
#define PERFINFO_HIBER_PAUSE_LOGGING()
#define PERFINFO_HIBER_REINIT_TRACE()
#define PERFINFO_HIBER_START_LOGGING()
#define PERFINFO_HIVECELL_REFERENCE_FLAT(Hive, pcell, Cell)
#define PERFINFO_HIVECELL_REFERENCE_PAGED(Hive, pcell, Cell, Type, Map)
#define PERFINFO_IMAGE_LOAD(LdrDataTableEntry)
#define PERFINFO_IMAGE_UNLOAD(Address)
#define PERFINFO_INIT_KTHREAD(KThread)
#define PERFINFO_INIT_TRACEFLAGS(OptnString, SpecificOptn)
#define PERFINFO_INITIALIZE_OBJECT_ALLOCATED_TYPE_LIST_HEAD(NewObjectType)
#define PERFINFO_INSERT_FRONT_STANDBY(Page)
#define PERFINFO_INSERTINLIST(Page, ListHead)
#define PERFINFO_INSWAP_PROCESS(OutProcess)
#define PERFINFO_IS_ANY_GROUP_ON() (PPerfGlobalGroupMask != NULL)
#define PERFINFO_IS_GROUP_ON(_Group) PerfIsGroupOnInGroupMask(_Group, PPerfGlobalGroupMask)
#define PERFINFO_IS_LOGGING_TO_PERFMEM() (FALSE)
#define PERFINFO_LOG_FILE_CREATE(FileObject, CompleteName)
#define PERFINFO_LOG_MARK(PMARK)
#define PERFINFO_LOG_MARK_SPRINTF(PMARK, VARIABLE)
#define PERFINFO_LOG_PREFETCH_BEGIN_TRACE(ScenarioId, ScenarioType, Process)
#define PERFINFO_LOG_PREFETCH_END_TRACE(ScenarioId, ScenarioType, Process, Status)
#define PERFINFO_LOG_PREFETCH_METADATA(PrefetchHeader)
#define PERFINFO_LOG_PREFETCH_METADATA_END(PrefetchHeader, Status)
#define PERFINFO_LOG_PREFETCH_READ(FileObject, Offset, ByteCount)
#define PERFINFO_LOG_PREFETCH_READLIST(RequestId, ReadList)
#define PERFINFO_LOG_PREFETCH_REQUEST(RequestId, NumLists, RequestLists)
#define PERFINFO_LOG_PREFETCH_SCENARIO(PrefetchHeader, ScenarioId, ScenarioType)
#define PERFINFO_LOG_PREFETCH_SCENARIO_END(PrefetchHeader, Status)
#define PERFINFO_LOG_PREFETCH_SECTIONS(PrefetchHeader, PrefetchType, PagesToPrefetch)
#define PERFINFO_LOG_PREFETCH_SECTIONS_END(PrefetchHeader, Status, PagesRequested)
#define PERFINFO_LOG_WS_REMOVAL(Type, WsInfo)
#define PERFINFO_LOG_WS_REPLACEMENT(WsInfo)
#define PERFINFO_MMINIT_START()
#define PERFINFO_MOD_PAGE_WRITER3()
#define PERFINFO_MUNG_FILE_OBJECT_TYPE_INITIALIZER(init)
#define PERFINFO_PAGE_INFO_DECL()
#define PERFINFO_PAGE_INFO_REPLACEMENT_DECL()
#define PERFINFO_POOL_ALLOC_COMMON(Type, PTag, NumBytes)
#define PERFINFO_POOLALLOC(Type, PTag, NumBytes)
#define PERFINFO_POOLALLOC_ADDR(Addr)
#define PERFINFO_POOLALLOC_EARLYEXIT()
#define PERFINFO_POWER_BATTERY_LIFE_INFO(_RemainingCapacity, _Rate)
#define PERFINFO_POWER_IDLE_STATE_CHANGE(_PState, _Direction)
#define PERFINFO_PRIVATE_COPY_ON_WRITE(CopyFrom, PAGE_SIZE)
#define PERFINFO_PRIVATE_PAGE_DEMAND_ZERO(VirtualAddress)
#define PERFINFO_PROCESS_CREATE(EProcess) WmiTraceProcess(EProcess, TRUE);
#define PERFINFO_PROCESS_DELETE(EProcess) WmiTraceProcess(EProcess, FALSE);
#define PERFINFO_REG_DELETE_KEY(KeyControlBlock)
#define PERFINFO_REG_DELETE_VALUE(KeyControlBlock, ValueName)
#define PERFINFO_REG_DUMP_CACHE()
#define PERFINFO_REG_ENUM_KEY(KeyControlBlock, Index)
#define PERFINFO_REG_ENUM_VALUE(KeyControlBlock, Index)
#define PERFINFO_REG_KCB_CREATE(kcb)
#define PERFINFO_REG_NOTIFY(NotifiedKCB, ModifiedKCB)
#define PERFINFO_REG_PARSE(kcb, RemainingName)
#define PERFINFO_REG_QUERY_KEY(KeyControlBlock)
#define PERFINFO_REG_QUERY_MULTIVALUE(KeyControlBlock, CurrentName)
#define PERFINFO_REG_QUERY_VALUE(KeyControlBlock, ValueName)
#define PERFINFO_REG_SET_VALUE(KeyControlBlock)
#define PERFINFO_REG_SET_VALUE_DECL()
#define PERFINFO_REG_SET_VALUE_DONE(ValueName)
#define PERFINFO_REG_SET_VALUE_EXIST()
#define PERFINFO_REG_SET_VALUE_NEW()
#define PERFINFO_REGPARSE(kcb, RemainingName)
#define PERFINFO_REGPARSE_END(status)
#define PERFINFO_REMOVE_OBJECT_FROM_ALLOCATED_TYPE_LIST(CreatorInfo, ObjectHeader)
#define PERFINFO_SECTION_CREATE(ControlArea)
#define PERFINFO_SECTION_CREATE1(File)
#define PERFINFO_SEGMENT_DELETE(FileName)
#define PERFINFO_SHUTDOWN_DUMP_PERF_BUFFER()
#define PERFINFO_SHUTDOWN_LOG_LAST_MEMORY_SNAPSHOT()
#define PERFINFO_SIGNAL_OBJECT(CurrentState, Object)
#define PERFINFO_SOFTFAULT(PageFrame, Address, Type)
#define PERFINFO_STACKWALK_THRESHHOLD_CM_DECL
#define PERFINFO_STACKWALK_THRESHHOLD_DECL
#define PERFINFO_THREAD_CREATE(EThread, ITeb) WmiTraceThread(EThread, ITeb, TRUE); \
#define PERFINFO_THREAD_DELETE(EThread) WmiTraceThread(EThread, NULL, FALSE);
#define PERFINFO_UNLINKFREEPAGE(Index, Location)
#define PERFINFO_UNLINKPAGE(Index, Location)
#define PERFINFO_UNMUNG_FILE_OBJECT_TYPE_INITIALIZER(init)
#define PERFINFO_UNWAIT_OBJECT(Object, Status)
#define PERFINFO_UNWAIT_OBJECTS(Object, CountIn, WaitType, WaitStatus)
#define PERFINFO_WAIT_ON_OBJECT(Object)
#define PERFINFO_WAIT_ON_OBJECTS(Object, CountIn, WaitType)
#define PERFINFO_WAITLOGGED_DECL
#define PERFINFO_WSMANAGE_ACTUALTRIM(Trim)
#define PERFINFO_WSMANAGE_CHECK()
#define PERFINFO_WSMANAGE_DECL()
#define PERFINFO_WSMANAGE_DUMPENTRIES()
#define PERFINFO_WSMANAGE_DUMPENTRIES_CLAIMS()
#define PERFINFO_WSMANAGE_DUMPENTRIES_FAULTS()
#define PERFINFO_WSMANAGE_DUMPWS(VmSupport, SampledAgeCounts)
#define PERFINFO_WSMANAGE_FINALACTION(TrimAction)
#define PERFINFO_WSMANAGE_LOGINFO_CLAIMS(TrimAction)
#define PERFINFO_WSMANAGE_LOGINFO_FAULTS(TrimAction)
#define PERFINFO_WSMANAGE_STARTLOG()
#define PERFINFO_WSMANAGE_STARTLOG_CLAIMS()
#define PERFINFO_WSMANAGE_STARTLOG_FAULTS()
#define PERFINFO_WSMANAGE_TOTRIM(Trim)
#define PERFINFO_WSMANAGE_TRIMACTION(TrimAction)
#define PERFINFO_WSMANAGE_TRIMEND_CLAIMS(Criteria)
#define PERFINFO_WSMANAGE_TRIMEND_FAULTS(Criteria)
#define PERFINFO_WSMANAGE_TRIMWS(Process, SessionSpace, VmSupport)
#define PERFINFO_WSMANAGE_TRIMWS_CLAIMINFO(VmSupport)
#define PERFINFO_WSMANAGE_TRIMWS_CLAIMINFO(VmSupport)
#define PERFINFO_WSMANAGE_WAITFORWRITER_CLAIMS()
#define PERFINFO_WSMANAGE_WAITFORWRITER_FAULTS()
#define PERFINFO_WSMANAGE_WILLTRIM(ReductionGoal, FreeGoal)
#define PERFINFO_WSMANAGE_WILLTRIM_CLAIMS(Criteria)
#define PERFINFO_WSMANAGE_WILLTRIM_FAULTS(Criteria)
#define PerfTimeStamp(TS) TS.QuadPart = (*WmiGetCpuClock)();
Typedefs
typedef struct _PERFINFO_ENTRY_TABLE PERFINFO_ENTRY_TABLE
typedef enum _PERFINFO_START_LOG_LOCATION PERFINFO_START_LOG_LOCATION
typedef struct _PERFINFO_ENTRY_TABLE * PPERFINFO_ENTRY_TABLE
typedef enum _PERFINFO_START_LOG_LOCATION * PPERFINFO_START_LOG_LOCATION
Enumerations
enum _PERFINFO_START_LOG_LOCATION { PERFINFO_START_LOG_AT_BOOT, PERFINFO_START_LOG_POST_BOOT, PERFINFO_START_LOG_FROM_GLOBAL_LOGGER }
Functions
VOID ObPerfHandleTableWalk (PEPROCESS Process, PPERFINFO_ENTRY_TABLE HashTable)
__inline LONGLONG PerfGetCycleCount ()
BOOLEAN PerfInfoAddToFileHash (PPERFINFO_ENTRY_TABLE HashTable, PVOID ObjectPointer)
ULONG PerfInfoCalcHashValue (PVOID Key, ULONG Len)
VOID PerfInfoFlushProfileCache (VOID)
NTSTATUS PerfInfoLogBytes (USHORT HookId, PVOID Data, ULONG NumBytes)
NTSTATUS PerfInfoLogBytesAndUnicodeString (USHORT HookId, PVOID SourceData, ULONG SourceByteCount, PUNICODE_STRING String)
NTSTATUS PerfInfoLogFileName (PVOID FileObject, PUNICODE_STRING SourceString)
VOID FASTCALL PerfInfoLogInterrupt (IN PVOID ServiceRoutine, IN ULONG RetVal, IN ULONGLONG InitialTime)
NTSTATUS PerfInfoReserveBytes (PPERFINFO_HOOK_HANDLE Hook, USHORT HookId, ULONG BytesToReserve)
NTSTATUS PerfInfoStartLog (PERFINFO_GROUPMASK *pGroupMask, PERFINFO_START_LOG_LOCATION StartLogLocation)
NTSTATUS PerfInfoStopLog (VOID)
VOID FASTCALL PerfProfileInterrupt (IN KPROFILE_SOURCE Source, IN PVOID InstructionPointer)
Variables
const PERFINFO_HOOK_HANDLE PerfNullHookHandle
PERFINFO_GROUPMASK * PPerfGlobalGroupMask
Macro Definition Documentation
#define PERF_ASSERT_TRACING_OFF ()
Definition at line 332 of file perf.h.
#define PERF_BRANCH_TRACING_BREAKPOINT (ExceptionRecord, TrapFrame)
Definition at line 331 of file perf.h.
#define PERF_BRANCH_TRACING_OFF_KD ()
Definition at line 325 of file perf.h.
#define PERF_BRANCH_TRACING_ON_KD ()
Definition at line 326 of file perf.h.
#define PERF_FINISH_HOOK (_HookHandle) WmiReleaseKernelBuffer((_HookHandle).WmiBufferHeader);
Definition at line 100 of file perf.h.
Referenced by PerfInfoLogBytes(), PerfInfoLogBytesAndUnicodeString(), PerfInfoProcessRunDown(), PerfInfoSysModuleRunDown(), and WmiSetMark().
#define PERF_IS_BRANCH_TRACING_ON ()
Definition at line 333 of file perf.h.
#define PERF_NULL_HOOK_HANDLE (PerfNullHookHandle)
Definition at line 28 of file perf.h.
Referenced by PerfInfoReserveBytes().
#define PERF_PF_MODLOAD_DECL ()
Definition at line 327 of file perf.h.
#define PERF_PF_MODLOAD_RESTORE ()
Definition at line 329 of file perf.h.
#define PERF_PF_MODLOAD_SAVE ()
Definition at line 328 of file perf.h.
#define PERF_PF_SANITIZE_CONTEXT (Context)
Definition at line 330 of file perf.h.
#define PERFINFO_ADD_OBJECT_TO_ALLOCATED_TYPE_LIST (CreatorInfo, ObjectType)
Definition at line 208 of file perf.h.
Referenced by ObpAllocateObject().
#define PERFINFO_ADDPOOLPAGE (CheckType, PoolIndex, Addr, PoolDesc)
Definition at line 209 of file perf.h.
Referenced by __bcount().
#define PERFINFO_ADDTOWS (PageFrame, Address, Pid)
Definition at line 210 of file perf.h.
#define PERFINFO_BIGFOOT_REPLACEMENT_CLAIMS (WorkingSetList, WsInfo)
Definition at line 211 of file perf.h.
#define PERFINFO_BIGFOOT_REPLACEMENT_FAULTS (WorkingSetList, WsInfo)
Definition at line 212 of file perf.h.
#define PERFINFO_BIGPOOLALLOC (Type, PTag, NumBytes, Addr)
Definition at line 213 of file perf.h.
Referenced by __bcount().
#define PERFINFO_CLEAR_OBJECT (CurrentState, Object)
Definition at line 214 of file perf.h.
#define PERFINFO_CONVERT_TO_GUI_THREAD (EThread)
Value:
if (PERFINFO_IS_GROUP_ON(PERF_MEMORY)) {                                                            \
        PERFINFO_THREAD_INFORMATION _ThreadInfo;                                                        \
        _ThreadInfo.ProcessId = HandleToUlong((EThread)->Cid.UniqueProcess);                            \
        _ThreadInfo.ThreadId = HandleToUlong((EThread)->Cid.UniqueThread);                              \
        _ThreadInfo.StackBase = (EThread)->Tcb.StackBase;                                               \
        _ThreadInfo.StackLimit = (EThread)->Tcb.StackLimit;                                             \
        _ThreadInfo.UserStackBase = 0;                                                                  \
        _ThreadInfo.UserStackLimit = 0;                                                                 \
        _ThreadInfo.StartAddr = 0;                                                                      \
        _ThreadInfo.Win32StartAddr = 0;                                                                 \
        _ThreadInfo.WaitMode = -1;                                                                      \
        PerfInfoLogBytes(                                                                               \
            PERFINFO_LOG_TYPE_CONVERTTOGUITHREAD,                                                       \
            &_ThreadInfo,                                                                               \
            sizeof(_ThreadInfo)                                                                         \
            );                                                                                          \
    }
Definition at line 167 of file perf.h.
Referenced by PsConvertToGuiThread().
#define PERFINFO_DECLARE_OB_ENUMERATE_ALLOCATED_OBJECTS_BY_TYPE ()
Definition at line 215 of file perf.h.
#define PERFINFO_DECLARE_OBJECT (Object)
Definition at line 216 of file perf.h.
Referenced by NtClearEvent(), NtPulseEvent(), NtReleaseMutant(), NtReleaseSemaphore(), NtResetEvent(), NtSetEvent(), NtWaitForSingleObject(), and ObpWaitForMultipleObjects().
#define PERFINFO_DECREFCNT (PageFrame, Flag, Type)
Definition at line 217 of file perf.h.
#define PERFINFO_DEFINE_OB_ENUMERATE_ALLOCATED_OBJECTS_BY_TYPE ()
Definition at line 218 of file perf.h.
#define PERFINFO_DELETE_STACK (PointerPte, NumberOfPtes)
Definition at line 219 of file perf.h.
#define PERFINFO_DETACH_PROCESS (KThread, KProcess)
Definition at line 220 of file perf.h.
#define PERFINFO_DO_PAGEFAULT_CLUSTERING () 1
Definition at line 221 of file perf.h.
#define PERFINFO_DRIVER_INTENTIONAL_DELAY ()
Definition at line 222 of file perf.h.
#define PERFINFO_DRIVER_STACKTRACE ()
Definition at line 223 of file perf.h.
#define PERFINFO_EXALLOCATEPOOLWITHTAG_DECL ()
Definition at line 224 of file perf.h.
Referenced by __bcount().
#define PERFINFO_EXFREEPOOLWITHTAG_DECL ()
Definition at line 225 of file perf.h.
#define PERFINFO_FAULT_NOTIFICATION (Address, TrapInfo)
Definition at line 226 of file perf.h.
#define PERFINFO_FREEPOOL (Addr)
Definition at line 227 of file perf.h.
Referenced by ExFreePoolWithTag().
#define PERFINFO_FREEPOOLPAGE (CheckType, PoolIndex, Addr, PoolDesc)
Definition at line 228 of file perf.h.
Referenced by ExDeferredFreePool(), and ExFreePoolWithTag().
#define PERFINFO_GET_PAGE_INFO (PointerPte)
Definition at line 229 of file perf.h.
#define PERFINFO_GET_PAGE_INFO_REPLACEMENT (PointerPte)
Definition at line 230 of file perf.h.
#define PERFINFO_GET_PAGE_INFO_WITH_DECL (PointerPte)
Definition at line 231 of file perf.h.
#define PERFINFO_GROW_STACK (EThread)
Definition at line 232 of file perf.h.
Referenced by MmGrowKernelStackEx().
#define PERFINFO_HIBER_ADJUST_PAGECOUNT_FOR_BBTBUFFER (pPageCount)
Definition at line 233 of file perf.h.
#define PERFINFO_HIBER_DUMP_PERF_BUFFER ()
Definition at line 234 of file perf.h.
#define PERFINFO_HIBER_HANDLE_BBTBUFFER_RANGE (HiberContext)
Definition at line 235 of file perf.h.
#define PERFINFO_HIBER_PAUSE_LOGGING ()
Definition at line 236 of file perf.h.
#define PERFINFO_HIBER_REINIT_TRACE ()
Definition at line 237 of file perf.h.
#define PERFINFO_HIBER_START_LOGGING ()
Definition at line 238 of file perf.h.
#define PERFINFO_HIVECELL_REFERENCE_FLAT (Hive, pcell, Cell)
Definition at line 239 of file perf.h.
Referenced by HvpGetCellFlat().
#define PERFINFO_HIVECELL_REFERENCE_PAGED (Hive, pcell, Cell, Type, Map)
Definition at line 240 of file perf.h.
Referenced by HvpGetCellMapped(), and HvpGetCellPaged().
#define PERFINFO_IMAGE_LOAD (LdrDataTableEntry)
Definition at line 241 of file perf.h.
#define PERFINFO_IMAGE_UNLOAD (Address)
Definition at line 242 of file perf.h.
#define PERFINFO_INIT_KTHREAD (KThread)
Definition at line 243 of file perf.h.
#define PERFINFO_INIT_TRACEFLAGS (OptnString, SpecificOptn)
Definition at line 244 of file perf.h.
Referenced by ExpInitializeExecutive().
#define PERFINFO_INITIALIZE_OBJECT_ALLOCATED_TYPE_LIST_HEAD (NewObjectType)
Definition at line 245 of file perf.h.
Referenced by ObCreateObjectType().
#define PERFINFO_INSERT_FRONT_STANDBY (Page)
Definition at line 246 of file perf.h.
#define PERFINFO_INSERTINLIST (Page, ListHead)
Definition at line 247 of file perf.h.
#define PERFINFO_INSWAP_PROCESS (OutProcess)
Definition at line 248 of file perf.h.
#define PERFINFO_IS_ANY_GROUP_ON () (PPerfGlobalGroupMask != NULL)
Definition at line 96 of file perf.h.
Referenced by WmiSetMark().
#define PERFINFO_IS_GROUP_ON (_Group) PerfIsGroupOnInGroupMask(_Group, PPerfGlobalGroupMask)
Definition at line 98 of file perf.h.
Referenced by KiCalibrateTimeAdjustment(), KiExecuteDpc(), KiProcessTimerDpcTable(), KiRetireDpcList(), MiDecrementShareCount(), MiDispatchFault(), MiInsertPageInFreeList(), MiRemovePageByColor(), MiRemovePageFromList(), MmInSwapProcess(), PerfInfoStopLog(), PerfProfileInterrupt(), WmipFlushActiveBuffers(), and WmiSetMark().
#define PERFINFO_IS_LOGGING_TO_PERFMEM () (FALSE)
Definition at line 206 of file perf.h.
#define PERFINFO_LOG_FILE_CREATE (FileObject, CompleteName)
Value:
if (PERFINFO_IS_GROUP_ON(PERF_FILENAME_ALL)){                                                       \
        PerfInfoLogFileName(FileObject, CompleteName);                                                  \
    }
Definition at line 154 of file perf.h.
#define PERFINFO_LOG_MARK (PMARK)
Definition at line 249 of file perf.h.
#define PERFINFO_LOG_MARK_SPRINTF (PMARK, VARIABLE)
Definition at line 250 of file perf.h.
#define PERFINFO_LOG_PREFETCH_BEGIN_TRACE (ScenarioId, ScenarioType, Process)
Definition at line 334 of file perf.h.
#define PERFINFO_LOG_PREFETCH_END_TRACE (ScenarioId, ScenarioType, Process, Status)
Definition at line 335 of file perf.h.
#define PERFINFO_LOG_PREFETCH_METADATA (PrefetchHeader)
Definition at line 338 of file perf.h.
#define PERFINFO_LOG_PREFETCH_METADATA_END (PrefetchHeader, Status)
Definition at line 339 of file perf.h.
#define PERFINFO_LOG_PREFETCH_READ (FileObject, Offset, ByteCount)
Definition at line 344 of file perf.h.
#define PERFINFO_LOG_PREFETCH_READLIST (RequestId, ReadList)
Definition at line 343 of file perf.h.
#define PERFINFO_LOG_PREFETCH_REQUEST (RequestId, NumLists, RequestLists)
Definition at line 342 of file perf.h.
#define PERFINFO_LOG_PREFETCH_SCENARIO (PrefetchHeader, ScenarioId, ScenarioType)
Definition at line 340 of file perf.h.
#define PERFINFO_LOG_PREFETCH_SCENARIO_END (PrefetchHeader, Status)
Definition at line 341 of file perf.h.
#define PERFINFO_LOG_PREFETCH_SECTIONS (PrefetchHeader, PrefetchType, PagesToPrefetch)
Definition at line 336 of file perf.h.
#define PERFINFO_LOG_PREFETCH_SECTIONS_END (PrefetchHeader, Status, PagesRequested)
Definition at line 337 of file perf.h.
#define PERFINFO_LOG_WS_REMOVAL (Type, WsInfo)
Definition at line 251 of file perf.h.
#define PERFINFO_LOG_WS_REPLACEMENT (WsInfo)
Definition at line 252 of file perf.h.
#define PERFINFO_MMINIT_START ()
Definition at line 205 of file perf.h.
#define PERFINFO_MOD_PAGE_WRITER3 ()
Definition at line 253 of file perf.h.
#define PERFINFO_MUNG_FILE_OBJECT_TYPE_INITIALIZER (init)
Definition at line 254 of file perf.h.
Referenced by IopCreateObjectTypes().
#define PERFINFO_PAGE_INFO_DECL ()
Definition at line 255 of file perf.h.
#define PERFINFO_PAGE_INFO_REPLACEMENT_DECL ()
Definition at line 256 of file perf.h.
#define PERFINFO_POOL_ALLOC_COMMON (Type, PTag, NumBytes)
Definition at line 257 of file perf.h.
#define PERFINFO_POOLALLOC (Type, PTag, NumBytes)
Definition at line 258 of file perf.h.
Referenced by __bcount().
#define PERFINFO_POOLALLOC_ADDR (Addr)
Definition at line 259 of file perf.h.
Referenced by __bcount().
#define PERFINFO_POOLALLOC_EARLYEXIT ()
Definition at line 260 of file perf.h.
#define PERFINFO_POWER_BATTERY_LIFE_INFO (_RemainingCapacity, _Rate)
Definition at line 261 of file perf.h.
#define PERFINFO_POWER_IDLE_STATE_CHANGE (_PState, _Direction)
Definition at line 262 of file perf.h.
#define PERFINFO_PRIVATE_COPY_ON_WRITE (CopyFrom, PAGE_SIZE)
Definition at line 263 of file perf.h.
#define PERFINFO_PRIVATE_PAGE_DEMAND_ZERO (VirtualAddress)
Definition at line 264 of file perf.h.
#define PERFINFO_PROCESS_CREATE (EProcess) WmiTraceProcess(EProcess, TRUE);
Definition at line 199 of file perf.h.
Referenced by PspCreateThread().
#define PERFINFO_PROCESS_DELETE (EProcess) WmiTraceProcess(EProcess, FALSE);
Definition at line 190 of file perf.h.
Referenced by PspExitProcess().
#define PERFINFO_REG_DELETE_KEY (KeyControlBlock)
Definition at line 265 of file perf.h.
Referenced by CmDeleteKey().
#define PERFINFO_REG_DELETE_VALUE (KeyControlBlock, ValueName)
Definition at line 266 of file perf.h.
Referenced by CmDeleteValueKey().
#define PERFINFO_REG_DUMP_CACHE ()
Definition at line 267 of file perf.h.
#define PERFINFO_REG_ENUM_KEY (KeyControlBlock, Index)
Definition at line 268 of file perf.h.
Referenced by CmEnumerateKey().
#define PERFINFO_REG_ENUM_VALUE (KeyControlBlock, Index)
Definition at line 269 of file perf.h.
Referenced by CmEnumerateValueKey().
#define PERFINFO_REG_KCB_CREATE (kcb)
Definition at line 270 of file perf.h.
Referenced by CmpCreateKeyControlBlock().
#define PERFINFO_REG_NOTIFY (NotifiedKCB, ModifiedKCB)
Definition at line 271 of file perf.h.
#define PERFINFO_REG_PARSE (kcb, RemainingName)
Definition at line 272 of file perf.h.
#define PERFINFO_REG_QUERY_KEY (KeyControlBlock)
Definition at line 273 of file perf.h.
Referenced by CmQueryKey().
#define PERFINFO_REG_QUERY_MULTIVALUE (KeyControlBlock, CurrentName)
Definition at line 274 of file perf.h.
Referenced by CmQueryMultipleValueKey().
#define PERFINFO_REG_QUERY_VALUE (KeyControlBlock, ValueName)
Definition at line 275 of file perf.h.
Referenced by CmQueryValueKey().
#define PERFINFO_REG_SET_VALUE (KeyControlBlock)
Definition at line 277 of file perf.h.
Referenced by CmSetValueKey().
#define PERFINFO_REG_SET_VALUE_DECL ()
Definition at line 276 of file perf.h.
Referenced by CmSetValueKey().
#define PERFINFO_REG_SET_VALUE_DONE (ValueName)
Definition at line 278 of file perf.h.
Referenced by CmSetValueKey().
#define PERFINFO_REG_SET_VALUE_EXIST ()
Definition at line 279 of file perf.h.
Referenced by CmSetValueKey().
#define PERFINFO_REG_SET_VALUE_NEW ()
Definition at line 280 of file perf.h.
Referenced by CmSetValueKey().
#define PERFINFO_REGPARSE (kcb, RemainingName)
Definition at line 281 of file perf.h.
#define PERFINFO_REGPARSE_END (status)
Definition at line 282 of file perf.h.
#define PERFINFO_REMOVE_OBJECT_FROM_ALLOCATED_TYPE_LIST (CreatorInfo, ObjectHeader)
Definition at line 283 of file perf.h.
Referenced by ObpFreeObject().
#define PERFINFO_SECTION_CREATE (ControlArea)
Definition at line 161 of file perf.h.
#define PERFINFO_SECTION_CREATE1 (File)
Definition at line 284 of file perf.h.
#define PERFINFO_SEGMENT_DELETE (FileName)
Definition at line 285 of file perf.h.
#define PERFINFO_SHUTDOWN_DUMP_PERF_BUFFER ()
Definition at line 287 of file perf.h.
#define PERFINFO_SHUTDOWN_LOG_LAST_MEMORY_SNAPSHOT ()
Definition at line 286 of file perf.h.
#define PERFINFO_SIGNAL_OBJECT (CurrentState, Object)
Definition at line 288 of file perf.h.
#define PERFINFO_SOFTFAULT (PageFrame, Address, Type)
Definition at line 289 of file perf.h.
#define PERFINFO_STACKWALK_THRESHHOLD_CM_DECL
Definition at line 290 of file perf.h.
#define PERFINFO_STACKWALK_THRESHHOLD_DECL
Definition at line 291 of file perf.h.
#define PERFINFO_THREAD_CREATE (EThread, ITeb) WmiTraceThread(EThread, ITeb, TRUE); \
Definition at line 202 of file perf.h.
Referenced by PspCreateThread().
#define PERFINFO_THREAD_DELETE (EThread) WmiTraceThread(EThread, NULL, FALSE);
Definition at line 193 of file perf.h.
Referenced by PspExitThread().
#define PERFINFO_UNLINKFREEPAGE (Index, Location)
Definition at line 292 of file perf.h.
#define PERFINFO_UNLINKPAGE (Index, Location)
Definition at line 293 of file perf.h.
#define PERFINFO_UNMUNG_FILE_OBJECT_TYPE_INITIALIZER (init)
Definition at line 294 of file perf.h.
Referenced by IopCreateObjectTypes().
#define PERFINFO_UNWAIT_OBJECT (Object, Status)
Definition at line 295 of file perf.h.
#define PERFINFO_UNWAIT_OBJECTS (Object, CountIn, WaitType, WaitStatus)
Definition at line 296 of file perf.h.
#define PERFINFO_WAIT_ON_OBJECT (Object)
Definition at line 297 of file perf.h.
#define PERFINFO_WAIT_ON_OBJECTS (Object, CountIn, WaitType)
Definition at line 298 of file perf.h.
#define PERFINFO_WAITLOGGED_DECL
Definition at line 299 of file perf.h.
#define PERFINFO_WSMANAGE_ACTUALTRIM (Trim)
Definition at line 300 of file perf.h.
#define PERFINFO_WSMANAGE_CHECK ()
Definition at line 301 of file perf.h.
#define PERFINFO_WSMANAGE_DECL ()
Definition at line 302 of file perf.h.
#define PERFINFO_WSMANAGE_DUMPENTRIES ()
Definition at line 303 of file perf.h.
#define PERFINFO_WSMANAGE_DUMPENTRIES_CLAIMS ()
Definition at line 304 of file perf.h.
#define PERFINFO_WSMANAGE_DUMPENTRIES_FAULTS ()
Definition at line 305 of file perf.h.
#define PERFINFO_WSMANAGE_DUMPWS (VmSupport, SampledAgeCounts)
Definition at line 306 of file perf.h.
#define PERFINFO_WSMANAGE_FINALACTION (TrimAction)
Definition at line 307 of file perf.h.
#define PERFINFO_WSMANAGE_LOGINFO_CLAIMS (TrimAction)
Definition at line 308 of file perf.h.
#define PERFINFO_WSMANAGE_LOGINFO_FAULTS (TrimAction)
Definition at line 309 of file perf.h.
#define PERFINFO_WSMANAGE_STARTLOG ()
Definition at line 310 of file perf.h.
#define PERFINFO_WSMANAGE_STARTLOG_CLAIMS ()
Definition at line 311 of file perf.h.
#define PERFINFO_WSMANAGE_STARTLOG_FAULTS ()
Definition at line 312 of file perf.h.
#define PERFINFO_WSMANAGE_TOTRIM (Trim)
Definition at line 313 of file perf.h.
#define PERFINFO_WSMANAGE_TRIMACTION (TrimAction)
Definition at line 314 of file perf.h.
#define PERFINFO_WSMANAGE_TRIMEND_CLAIMS (Criteria)
Definition at line 315 of file perf.h.
#define PERFINFO_WSMANAGE_TRIMEND_FAULTS (Criteria)
Definition at line 316 of file perf.h.
#define PERFINFO_WSMANAGE_TRIMWS (Process, SessionSpace, VmSupport)
Definition at line 317 of file perf.h.
#define PERFINFO_WSMANAGE_TRIMWS_CLAIMINFO (VmSupport)
Definition at line 319 of file perf.h.
#define PERFINFO_WSMANAGE_TRIMWS_CLAIMINFO (VmSupport)
Definition at line 319 of file perf.h.
#define PERFINFO_WSMANAGE_WAITFORWRITER_CLAIMS ()
Definition at line 320 of file perf.h.
#define PERFINFO_WSMANAGE_WAITFORWRITER_FAULTS ()
Definition at line 321 of file perf.h.
#define PERFINFO_WSMANAGE_WILLTRIM (ReductionGoal, FreeGoal)
Definition at line 322 of file perf.h.
#define PERFINFO_WSMANAGE_WILLTRIM_CLAIMS (Criteria)
Definition at line 323 of file perf.h.
#define PERFINFO_WSMANAGE_WILLTRIM_FAULTS (Criteria)
Definition at line 324 of file perf.h.
#define PerfTimeStamp (TS) TS.QuadPart = (*WmiGetCpuClock)();
Definition at line 149 of file perf.h.
Referenced by KiExecuteDpc(), KiProcessTimerDpcTable(), KiRetireDpcList(), MiDispatchFault(), and WmiTraceContextSwap().
Typedef Documentation
typedef struct _PERFINFO_ENTRY_TABLE PERFINFO_ENTRY_TABLE
typedef enum _PERFINFO_START_LOG_LOCATION PERFINFO_START_LOG_LOCATION
typedef struct _PERFINFO_ENTRY_TABLE * PPERFINFO_ENTRY_TABLE
typedef enum _PERFINFO_START_LOG_LOCATION * PPERFINFO_START_LOG_LOCATION
Enumeration Type Documentation
enum _PERFINFO_START_LOG_LOCATION
Enumerator
PERFINFO_START_LOG_AT_BOOT
PERFINFO_START_LOG_POST_BOOT
PERFINFO_START_LOG_FROM_GLOBAL_LOGGER
Definition at line 30 of file perf.h.
Function Documentation
VOID ObPerfHandleTableWalk (PEPROCESS Process, PPERFINFO_ENTRY_TABLE HashTable)
Referenced by PerfInfoFileNameRunDown().
__inline LONGLONG PerfGetCycleCount ()
Definition at line 130 of file perf.h.
References RDTSC().
Referenced by WmiGetClock(), and WmipStartLogger().
BOOLEAN PerfInfoAddToFileHash (PPERFINFO_ENTRY_TABLE HashTable, PVOID ObjectPointer)
Referenced by CcPerfFileRunDown().
ULONG PerfInfoCalcHashValue (PVOID Key, ULONG Len)
Definition at line 370 of file hooks.c.
References abs(), RNDM_CONSTANT, and RNDM_PRIME.
Referenced by PerfInfoAddToFileHash().
VOID PerfInfoFlushProfileCache (VOID)
Definition at line 39 of file hooks.c.
References _PERFINFO_SAMPLED_PROFILE_CACHE::Entries, FALSE, FIELD_OFFSET, InterlockedDecrement, InterlockedIncrement, PERFINFO_LOG_TYPE_SAMPLED_PROFILE_CACHE, PerfInfoLogBytes(), PerfInfoSampledProfileCaching, PerfInfoSampledProfileFlushInProgress, and PerfProfileCache.
Referenced by PerfInfoProfileUninit(), and WmipTraceLoadImage().
NTSTATUS PerfInfoLogBytes (USHORT HookId, PVOID Data, ULONG NumBytes)
Definition at line 75 of file logging.c.
References NT_SUCCESS, PERF_FINISH_HOOK, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), RtlCopyMemory, Status, and STATUS_SUCCESS.
Referenced by KiCalibrateTimeAdjustment(), KiExecuteDpc(), KiProcessTimerDpcTable(), KiRetireDpcList(), MiDecrementShareCount(), MiDispatchFault(), MiLogPfnInformation(), MmIdentifyPhysicalMemory(), MmInSwapProcess(), MmPerfSnapShotValidPhysicalMemory(), PerfInfoFlushProfileCache(), PerfInfoLogInterrupt(), and PerfProfileInterrupt().
NTSTATUS PerfInfoLogBytesAndUnicodeString (USHORT HookId, PVOID SourceData, ULONG SourceByteCount, PUNICODE_STRING String)
Definition at line 262 of file hooks.c.
References _UNICODE_STRING::Buffer, _UNICODE_STRING::Length, MAX_FILENAME_TO_LOG, NT_SUCCESS, NULL, PERF_FINISH_HOOK, PERFINFO_APPLY_OFFSET_GIVING_TYPE, PERFINFO_HOOK_HANDLE_TO_DATA, PerfInfoReserveBytes(), RtlCopyMemory, Status, STATUS_SUCCESS, and UNICODE_NULL.
Referenced by PerfInfoLogFileName().
NTSTATUS PerfInfoLogFileName (PVOID FileObject, PUNICODE_STRING SourceString)
Definition at line 326 of file hooks.c.
References FIELD_OFFSET, _PERFINFO_FILENAME_INFORMATION::HashKeyFileNamePointer, _UNICODE_STRING::Length, NULL, PERFINFO_LOG_TYPE_FILENAME_CREATE, PerfInfoLogBytesAndUnicodeString(), Status, and STATUS_SUCCESS.
Referenced by PerfInfoFileNameRunDown().
VOID FASTCALL PerfInfoLogInterrupt (IN PVOID ServiceRoutine, IN ULONG RetVal, IN ULONGLONG InitialTime)
Definition at line 220 of file hooks.c.
References _PERFINFO_INTERRUPT_INFORMATION::InitialTime, PERFINFO_LOG_TYPE_INTERRUPT, PerfInfoLogBytes(), _PERFINFO_INTERRUPT_INFORMATION::ReturnValue, and _PERFINFO_INTERRUPT_INFORMATION::ServiceRoutine.
NTSTATUS PerfInfoReserveBytes (PPERFINFO_HOOK_HANDLE Hook, USHORT HookId, ULONG BytesToReserve)
Definition at line 28 of file logging.c.
References FIELD_OFFSET, _WMI_TRACE_PACKET::HookId, MAXUSHORT, NULL, _PERFINFO_TRACE_HEADER::Packet, PERF_ASSERT, PERF_NULL_HOOK_HANDLE, _PERFINFO_HOOK_HANDLE::PerfTraceHeader, Status, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _PERFINFO_HOOK_HANDLE::WmiBufferHeader, and WmiReserveWithPerfHeader().
Referenced by PerfInfoLogBytes(), PerfInfoLogBytesAndUnicodeString(), PerfInfoProcessRunDown(), PerfInfoSysModuleRunDown(), and WmiSetMark().
NTSTATUS PerfInfoStartLog (PERFINFO_GROUPMASK * pGroupMask, PERFINFO_START_LOG_LOCATION StartLogLocation)
Definition at line 98 of file perfsup.c.
References FALSE, IoPerfInit(), IoPerfReset(), KeGetPreviousMode, KernelMode, MmEmptyAllWorkingSets(), NT_SUCCESS, NULL, PERF_BIGFOOT, PERF_CONTEXT_SWITCH, PERF_DRIVERS, PERF_FILENAME, PERF_FILENAME_ALL, PERF_FOOTPRINT, PERF_MEMORY, PERF_PROC_THREAD, PERF_PROFILE, PerfGlobalGroupMask, PERFINFO_CLEAR_GROUPMASK, PERFINFO_OR_GROUP_WITH_GROUPMASK, PERFINFO_START_LOG_AT_BOOT, PERFINFO_START_LOG_FROM_GLOBAL_LOGGER, PerfInfoFileNameRunDown(), PerfInfoProcessRunDown(), PerfInfoProfileInit(), PerfInfoProfileUninit(), PerfInfoSysModuleRunDown(), PerfIsGroupOnInGroupMask(), PerfSetLogging(), PPerfGlobalGroupMask, SeSinglePrivilegeCheck(), SeSystemProfilePrivilege, Status, STATUS_NO_SUCH_PRIVILEGE, STATUS_SUCCESS, TRUE, UserMode, WmiStartContextSwapTrace(), and WmiStopContextSwapTrace().
Referenced by WmipStartLogger(), and WmiUpdateTrace().
NTSTATUS PerfInfoStopLog (VOID)
Referenced by WmipStopLoggerInstance().
VOID FASTCALL PerfProfileInterrupt (IN KPROFILE_SOURCE Source, IN PVOID InstructionPointer)
Definition at line 103 of file hooks.c.
References _PERFINFO_SAMPLED_PROFILE_INFORMATION::Count, _PERFINFO_SAMPLED_PROFILE_CACHE::Entries, HandleToUlong, _PERFINFO_SAMPLED_PROFILE_INFORMATION::InstructionPointer, PERF_PROFILE, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_SAMPLED_PROFILE, PERFINFO_LOG_TYPE_SAMPLED_PROFILE_CACHE, PERFINFO_SAMPLED_PROFILE_CACHE_MAX, PerfInfoLogBytes(), PerfInfoProfileSourceActive, PerfInfoSampledProfileCaching, PerfInfoSampledProfileFlushInProgress, PerfProfileCache, PsGetCurrentThread(), _PERFINFO_SAMPLED_PROFILE_CACHE::Sample, and _PERFINFO_SAMPLED_PROFILE_INFORMATION::ThreadId.
Variable Documentation
const PERFINFO_HOOK_HANDLE PerfNullHookHandle
Definition at line 23 of file perfdata.c.
PERFINFO_GROUPMASK* PPerfGlobalGroupMask
Definition at line 22 of file perfdata.c.
Referenced by PerfInfoStartLog(), PerfInfoStopLog(), and WmipAddLogHeader().