Windows Research Kernel v1.2: C:/Windows Research Kernel/io/iomgr/complete.c File Reference
complete.c File Reference
#include "iomgr.h"
Functions
VOID IopDeleteIoCompletion (IN PVOID Object)
VOID IopFreeMiniPacket (PIOP_MINI_COMPLETION_PACKET MiniPacket)
NTKERNELAPI NTSTATUS IoSetIoCompletion (IN PVOID IoCompletion, IN PVOID KeyContext, IN PVOID ApcContext, IN NTSTATUS IoStatus, IN ULONG_PTR IoStatusInformation, IN BOOLEAN Quota)
NTSTATUS NtCreateIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Count OPTIONAL)
NTSTATUS NtOpenIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSTATUS NtQueryIoCompletion (__in HANDLE IoCompletionHandle, __in IO_COMPLETION_INFORMATION_CLASS IoCompletionInformationClass, __out_bcount(IoCompletionInformationLength) PVOID IoCompletionInformation, __in ULONG IoCompletionInformationLength, __out_opt PULONG ReturnLength)
NTSTATUS NtRemoveIoCompletion (__in HANDLE IoCompletionHandle, __out PVOID *KeyContext, __out PVOID *ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER Timeout)
NTSTATUS NtSetIoCompletion (__in HANDLE IoCompletionHandle, __in PVOID KeyContext, __in_opt PVOID ApcContext, __in NTSTATUS IoStatus, __in ULONG_PTR IoStatusInformation)
Function Documentation
VOID IopDeleteIoCompletion (IN PVOID Object)
Definition at line 855 of file complete.c.
References CONTAINING_RECORD, _LIST_ENTRY::Flink, IoFreeIrp(), IopCompletionPacketIrp, IopFreeMiniPacket(), IRP, KeRundownQueue(), NULL, _IOP_MINI_COMPLETION_PACKET::PacketType, and PIRP.
Referenced by IopCreateObjectTypes().
VOID IopFreeMiniPacket (PIOP_MINI_COMPLETION_PACKET MiniPacket)
Definition at line 790 of file complete.c.
References ExFreePool(), ExQueryDepthSList, ExReturnPoolQuota(), InterlockedPushEntrySList(), IopCompletionPacketQuota, KeGetCurrentPrcb(), _PP_LOOKASIDE_LIST::L, LookasideCompletionList, _PP_LOOKASIDE_LIST::P, _IOP_MINI_COMPLETION_PACKET::PacketType, _KPRCB::PPLookasideList, PSLIST_ENTRY, and _GENERAL_LOOKASIDE::TotalFrees.
Referenced by IopDeleteIoCompletion(), and NtRemoveIoCompletion().
NTKERNELAPI NTSTATUS IoSetIoCompletion (IN PVOID IoCompletion, IN PVOID KeyContext, IN PVOID ApcContext, IN NTSTATUS IoStatus, IN ULONG_PTR IoStatusInformation, IN BOOLEAN Quota)
Definition at line 665 of file complete.c.
References _IOP_MINI_COMPLETION_PACKET::ApcContext, ExAllocatePoolWithQuotaTag, except, EXCEPTION_EXECUTE_HANDLER, FALSE, InterlockedPopEntrySList(), IopCompletionPacketMini, IopCompletionPacketQuota, _IOP_MINI_COMPLETION_PACKET::IoStatus, _IOP_MINI_COMPLETION_PACKET::IoStatusInformation, KeGetCurrentPrcb(), KeInsertQueue(), _IOP_MINI_COMPLETION_PACKET::KeyContext, _PP_LOOKASIDE_LIST::L, _IOP_MINI_COMPLETION_PACKET::ListEntry, LookasideCompletionList, LowPoolPriority, NonPagedPool, NOTHING, NULL, _PP_LOOKASIDE_LIST::P, _IOP_MINI_COMPLETION_PACKET::PacketType, PAGED_CODE, _KPRCB::PPLookasideList, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _GENERAL_LOOKASIDE::TotalAllocates.
Referenced by IopXxxControlFile(), NtLockFile(), NtSetInformationJobObject(), NtSetIoCompletion(), PsChangeJobMemoryUsage(), PsEnforceExecutionTimeLimits(), PspAddProcessToJob(), PspCreateThread(), PspExitProcess(), PspFoldProcessAccountingIntoJob(), and PsReportProcessMemoryLimitViolation().
NTSTATUS NtCreateIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Count OPTIONAL)
Definition at line 45 of file complete.c.
References Count, except, ExSystemExceptionFilter(), Handle, IoCompletionObjectType, KeGetPreviousMode, KeInitializeQueue(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, and Status.
NTSTATUS NtOpenIoCompletion (__out PHANDLE IoCompletionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 172 of file complete.c.
References except, ExSystemExceptionFilter(), Handle, IoCompletionObjectType, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSTATUS NtQueryIoCompletion (__in HANDLE IoCompletionHandle, __in IO_COMPLETION_INFORMATION_CLASS IoCompletionInformationClass, __out_bcount(IoCompletionInformationLength) PVOID IoCompletionInformation, __in ULONG IoCompletionInformationLength, __out_opt PULONG ReturnLength)
Definition at line 275 of file complete.c.
References ARGUMENT_PRESENT, C_ASSERT, except, ExSystemExceptionFilter(), IO_COMPLETION_QUERY_STATE, IoCompletionBasicInformation, IoCompletionObjectType, KeGetPreviousMode, KeReadStateQueue(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteUlong, ProbeForWriteUlongAligned32(), Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_INVALID_INFO_CLASS.
NTSTATUS NtRemoveIoCompletion (__in HANDLE IoCompletionHandle, __out PVOID * KeyContext, __out PVOID * ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in_opt PLARGE_INTEGER Timeout)
Definition at line 479 of file complete.c.
References _IOP_MINI_COMPLETION_PACKET::ApcContext, ARGUMENT_PRESENT, CONTAINING_RECORD, except, ExSystemExceptionFilter(), _IO_STATUS_BLOCK::Information, IO_COMPLETION_MODIFY_STATE, IoCompletionObjectType, IoFreeIrp(), IopCompletionPacketIrp, IopFreeMiniPacket(), _IOP_MINI_COMPLETION_PACKET::IoStatus, _IOP_MINI_COMPLETION_PACKET::IoStatusInformation, IRP, KeGetPreviousMode, KeRemoveQueue(), KernelMode, _IOP_MINI_COMPLETION_PACKET::KeyContext, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _IOP_MINI_COMPLETION_PACKET::PacketType, PIRP, ProbeAndReadLargeInteger, ProbeForWriteIoStatus, ProbeForWriteUlong_ptr, Status, _IO_STATUS_BLOCK::Status, STATUS_SUCCESS, STATUS_TIMEOUT, and STATUS_USER_APC.
NTSTATUS NtSetIoCompletion (__in HANDLE IoCompletionHandle, __in PVOID KeyContext, __in_opt PVOID ApcContext, __in NTSTATUS IoStatus, __in ULONG_PTR IoStatusInformation)
Definition at line 411 of file complete.c.
References IO_COMPLETION_MODIFY_STATE, IoCompletionObjectType, IoSetIoCompletion(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, Status, and TRUE.