Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/pfndec.c File Reference
pfndec.c File Reference
#include "mi.h"
Functions
VOID MiBadRefCount (__in PMMPFN Pfn1)
VOID FASTCALL MiDecrementReferenceCount (IN PMMPFN Pfn1, IN PFN_NUMBER PageFrameIndex)
VOID FASTCALL MiDecrementShareCount (IN PMMPFN Pfn1, IN PFN_NUMBER PageFrameIndex)
Variables
ULONG MmFrontOfList
Function Documentation
VOID MiBadRefCount (__in PMMPFN Pfn1)
Definition at line 331 of file pfndec.c.
References _MMPFN::e1, KeBugCheckEx(), MmPfnDatabase, _MMPFNENTRY::PageLocation, PFN_LIST_CORRUPT, and _MMPFN::u3.
Referenced by MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), and MiFreePoolPages().
VOID FASTCALL MiDecrementReferenceCount (IN PMMPFN Pfn1, IN PFN_NUMBER PageFrameIndex)
Definition at line 202 of file pfndec.c.
References ActiveAndValid, ASSERT, GET_PAGING_FILE_OFFSET, InterlockedDecrementPfn, KeBugCheckEx(), MI_IS_PFN(), MI_IS_PFN_DELETED, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiReleaseConfirmedPageFileSpace(), MiRestoreTransitionPte(), MM_PFN_LOCK_ASSERT, MmBadPageListHead, MmFrontOfList, MmModifiedPageListHead, MmStandbyPageListHead, PFN_LIST_CORRUPT, and StandbyPageList.
Referenced by MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiDecrementReferenceCountForAwePage(), MiDecrementShareCount(), MiFreeNonPagedPool(), MiPurgeTransitionList(), MiRemoveImageHeaderPage(), MiUpdateImageHeaderPage(), MmReturnMemoryForHibernate(), and MxConvertToLargePage().
VOID FASTCALL MiDecrementShareCount (IN PMMPFN Pfn1, IN PFN_NUMBER PageFrameIndex)
Definition at line 27 of file pfndec.c.
References ActiveAndValid, ASSERT, GET_PAGING_FILE_OFFSET, InterlockedDecrementPfn, KeBugCheckEx(), MI_IS_PFN(), MI_IS_PFN_DELETED, MI_MAKE_VALID_PTE_TRANSITION, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_WRITE_INVALID_PTE, MiDecrementReferenceCount(), MiGetByteOffset, MiInsertPageInFreeList(), MiIsProtoAddressValid(), MiMapPageInHyperSpaceAtDpc(), MiReleaseConfirmedPageFileSpace(), MiUnmapPageInHyperSpaceFromDpc, MM_PFN_LOCK_ASSERT, NULL, _PERFINFO_PFN_INFORMATION::PageFrameIndex, PERF_MEMORY, PERFINFO_IS_GROUP_ON, PERFINFO_LOG_TYPE_ZEROSHARECOUNT, PerfInfoLogBytes(), PFN_LIST_CORRUPT, _MMPTE_SOFTWARE::Protection, PsGetCurrentProcess(), _MMPTE::Soft, StandbyPageList, TransitionPage, and _MMPTE::u.
Referenced by MiCopyOnWrite(), MiDecrementCloneBlockReference(), MiDeletePte(), MiDeletePteList(), MiDeleteSystemPageableVm(), MiDeleteValidSystemPte(), MiDereferenceSessionFinal(), MiDoneWithThisPageGetAnother(), MiDownShareCountFlushEntireTb(), MiEnablePagingOfDriverAtInit(), MiFlushPteListFreePfns(), MiFreeContiguousPages(), MiHandleForkTransitionPte(), MiOutPageSingleKernelStack(), MiProcessValidPteList(), MiReleaseProcessReferenceToSessionDataPage(), MiReloadBootLoadedDrivers(), MiRemoveMappedPtes(), MiReturnFailedSessionPages(), MiSessionCreateInternal(), MiSessionPageTableRelease(), MmDeleteKernelStack(), MmDeleteProcessAddressSpace(), MmFreeBootRegistry(), MmFreeContiguousMemory(), MmFreeIndependentPages(), MmFreeLoaderBlock(), and MmOutSwapProcess().
Variable Documentation
ULONG MmFrontOfList
Definition at line 22 of file pfndec.c.
Referenced by MiDecrementReferenceCount(), and MmUnmapViewInSystemCache().