Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/exceptn.c File Reference
exceptn.c File Reference
#include "ki.h"
#include "kix86.h"
Macros
#define BYTES_PER_FP_REGISTER 10
#define BYTES_PER_FX_REGISTER 16
#define FN_BITS_PER_TAGWORD 16
#define FN_TAG_EMPTY 0x3
#define FN_TAG_MASK 0x3
#define FX_TAG_VALID 0x1
#define NUMBER_OF_FP_REGISTERS 8
Functions
VOID KeContextFromKframes (__in PKTRAP_FRAME TrapFrame, __in PKEXCEPTION_FRAME ExceptionFrame, __inout PCONTEXT ContextFrame)
VOID KeContextToKframes (__inout PKTRAP_FRAME TrapFrame, __inout PKEXCEPTION_FRAME ExceptionFrame, __in PCONTEXT ContextFrame, __in ULONG ContextFlags, __in KPROCESSOR_MODE PreviousMode)
NTSTATUS KeRaiseUserException (IN NTSTATUS ExceptionCode)
VOID Ki386AdjustEsp0 (IN PKTRAP_FRAME TrapFrame)
BOOLEAN KiCheckForAtlThunk (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT Context)
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
BOOLEAN KiEm87StateToNpxFrame (OUT PFLOATING_SAVE_AREA NpxFrmae)
ULONG KiEspFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
VOID KiEspToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG Esp)
BOOLEAN KiNpxFrameToEm87State (IN PFLOATING_SAVE_AREA NpxFrmae)
ULONG KiSegSsFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
VOID KiSegSsToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG SegSs)
Variables
BOOLEAN KeI386FxsrPresent
BOOLEAN KeI386XMMIPresent
UCHAR VdmUserCr0MapIn []
Macro Definition Documentation
#define BYTES_PER_FP_REGISTER 10
Definition at line 28 of file exceptn.c.
Referenced by KeContextToKframes().
#define BYTES_PER_FX_REGISTER 16
Definition at line 29 of file exceptn.c.
Referenced by KeContextToKframes().
#define FN_BITS_PER_TAGWORD 16
Definition at line 23 of file exceptn.c.
Referenced by KeContextToKframes().
#define FN_TAG_EMPTY 0x3
Definition at line 24 of file exceptn.c.
Referenced by KeContextToKframes().
#define FN_TAG_MASK 0x3
Definition at line 25 of file exceptn.c.
Referenced by KeContextToKframes().
#define FX_TAG_VALID 0x1
Definition at line 26 of file exceptn.c.
Referenced by KeContextToKframes().
#define NUMBER_OF_FP_REGISTERS 8
Definition at line 27 of file exceptn.c.
Referenced by KeContextToKframes().
Function Documentation
VOID KeContextFromKframes (__in PKTRAP_FRAME TrapFrame, __in PKEXCEPTION_FRAME ExceptionFrame, __inout PCONTEXT ContextFrame)
Definition at line 289 of file exceptn.c.
References APC_LEVEL, CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXTENDED_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_i386, CONTEXT_INTEGER, CONTEXT_SEGMENTS, _FLOATING_SAVE_AREA::ControlWord, _FX_SAVE_AREA::Cr0NpxState, _FLOATING_SAVE_AREA::DataOffset, _FLOATING_SAVE_AREA::DataSelector, DR7_RESERVED_MASK, EFLAGS_V86_MASK, _FLOATING_SAVE_AREA::ErrorOffset, _FLOATING_SAVE_AREA::ErrorSelector, _FX_SAVE_AREA::FnArea, FRAME_EDITED, _FX_SAVE_AREA::FxArea, KeGetCurrentIrql(), KeI386FxsrPresent, KeI386NpxPresent, KeLowerIrql, KeRaiseIrql, KGDT_R0_CODE, KGDT_R0_PCR, KGDT_R3_DATA, KiEm87StateToNpxFrame(), KiEspFromTrapFrame(), KiFlushNPXState(), KiSegSsFromTrapFrame(), KiUpdateDr7(), MAXIMUM_SUPPORTED_EXTENSION, MODE_MASK, NULL, _FLOATING_SAVE_AREA::RegisterArea, RPL_MASK, RtlCopyMemory, SEGMENT_MASK, SIZE_OF_80387_REGISTERS, _FLOATING_SAVE_AREA::StatusWord, _FLOATING_SAVE_AREA::TagWord, TRUE, _FX_SAVE_AREA::U, UNREFERENCED_PARAMETER, and UserMode.
VOID KeContextToKframes (__inout PKTRAP_FRAME TrapFrame, __inout PKEXCEPTION_FRAME ExceptionFrame, __in PCONTEXT ContextFrame, __in ULONG ContextFlags, __in KPROCESSOR_MODE PreviousMode)
Definition at line 569 of file exceptn.c.
References APC_LEVEL, ASSERT, BYTES_PER_FP_REGISTER, BYTES_PER_FX_REGISTER, CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXTENDED_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_INTEGER, CONTEXT_SEGMENTS, _FNSAVE_FORMAT::ControlWord, _FXSAVE_FORMAT::ControlWord, CR0_EM, CR0_MP, CR0_PE, CR0_TS, _FX_SAVE_AREA::Cr0NpxState, _KPRCB::CurrentThread, _FNSAVE_FORMAT::DataOffset, _FXSAVE_FORMAT::DataOffset, _FNSAVE_FORMAT::DataSelector, _FXSAVE_FORMAT::DataSelector, _DISPATCHER_HEADER::DebugActive, DR_MASK, EFLAGS_IOPL_MASK, EFLAGS_V86_MASK, _FNSAVE_FORMAT::ErrorOffset, _FXSAVE_FORMAT::ErrorOffset, _FXSAVE_FORMAT::ErrorOpcode, _FNSAVE_FORMAT::ErrorSelector, _FXSAVE_FORMAT::ErrorSelector, FALSE, FN_BITS_PER_TAGWORD, FN_TAG_EMPTY, FN_TAG_MASK, _FX_SAVE_AREA::FnArea, FX_TAG_VALID, _FX_SAVE_AREA::FxArea, _KTHREAD::Header, Index, _KTHREAD::Iopl, KeGetCurrentIrql(), KeGetCurrentThread(), KeGetPcr(), KeI386FxsrPresent, KeI386NpxPresent, KeLowerIrql, KeRaiseIrql, KeRaiseIrqlToSynchLevel(), KernelMode, KGDT_R3_CODE, KGDT_R3_DATA, Ki386AdjustEsp0(), KiDebugRegisterContextOffsets, KiDebugRegisterTrapOffsets, KiEspToTrapFrame(), KiFlushNPXState(), KiNpxFrameToEm87State(), KiRecordDr7(), KiSegSsToTrapFrame(), MAXIMUM_SUPPORTED_EXTENSION, MODE_MASK, _FXSAVE_FORMAT::MXCsr, _KPCR::NtTib, NULL, NUMBER_OF_FP_REGISTERS, _KPCR::Prcb, PsGetCurrentProcess(), _FNSAVE_FORMAT::RegisterArea, _FXSAVE_FORMAT::RegisterArea, RPL_MASK, RtlCopyMemory, RtlZeroMemory, SANITIZE_DR6, SANITIZE_DR7, SANITIZE_DRADDR, SANITIZE_FLAGS, SANITIZE_MXCSR, SANITIZE_SEG, _NT_TIB::Self, SIZE_OF_80387_REGISTERS, SIZE_OF_FX_REGISTERS, _FNSAVE_FORMAT::StatusWord, _FXSAVE_FORMAT::StatusWord, _FNSAVE_FORMAT::TagWord, _FXSAVE_FORMAT::TagWord, _KTHREAD::Teb, TRUE, _FX_SAVE_AREA::U, UNREFERENCED_PARAMETER, UserMode, _EPROCESS::VdmObjects, VdmUserCr0MapIn, and VOID.
Referenced by KiDispatchException().
NTSTATUS KeRaiseUserException (IN NTSTATUS ExceptionCode)
Definition at line 1467 of file exceptn.c.
References _KTRAP_FRAME::Eip, KeGetCurrentThread(), KiEspFromTrapFrame(), MODE_MASK, NULL, ProbeForWriteSmallStructure(), _KTRAP_FRAME::SegCs, _KTHREAD::Teb, _KTHREAD::TrapFrame, and UserMode.
Referenced by ExMapHandleToPointerEx(), ObpCloseHandle(), and ObpCloseHandleTableEntry().
VOID Ki386AdjustEsp0 (IN PKTRAP_FRAME TrapFrame)
Referenced by KeContextToKframes().
BOOLEAN KiCheckForAtlThunk (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT Context)
Definition at line 1531 of file exceptn.c.
References FALSE, KiEmulateAtlThunk(), and TRUE.
Referenced by KiDispatchException().
ULONG KiCopyInformation (IN OUT PEXCEPTION_RECORD ExceptionRecord1, IN PEXCEPTION_RECORD ExceptionRecord2)
Definition at line 1428 of file exceptn.c.
References EXCEPTION_EXECUTE_HANDLER, and RtlCopyMemory.
VOID KiDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN KPROCESSOR_MODE PreviousMode, IN BOOLEAN FirstChance)
Definition at line 1034 of file exceptn.c.
References ASSERT, CONTEXT_ALIGN, CONTEXT_ALIGNED_SIZE, CONTEXT_DEBUG_REGISTERS, CONTEXT_EXTENDED_REGISTERS, CONTEXT_FLOATING_POINT, CONTEXT_FULL, CONTEXT_LENGTH, CONTEXT_ROUND, CONTEXT_SEGMENTS, _CONTEXT::ContextFlags, DbgkForwardException(), DebugService(), _CONTEXT::EFlags, EFLAGS_AC_MASK, EFLAGS_TF_MASK, EFLAGS_V86_MASK, _CONTEXT::Eip, _CONTEXT::Esp, except, EXCEPTION_EXECUTE_FAULT, EXCEPTION_MAXIMUM_PARAMETERS, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionFlags, ExRaiseException(), FALSE, _EPROCESS::Flags, KdDebuggerEnabled, KdIgnoreUmExceptions, KdIsThisAKdTrap(), KeBugCheckEx(), KeContextFromKframes(), KeContextToKframes(), _KPRCB::KeExceptionDispatchCount, KeFeatureBits, KeGetCurrentPrcb(), KeI386XMMIPresent, KERNEL_MODE_EXCEPTION_NOT_HANDLED, KernelMode, KeUserExceptionDispatcher, KF_GLOBAL_32BIT_EXECUTE, KF_GLOBAL_32BIT_NOEXECUTE, KGDT_R3_CODE, KGDT_R3_DATA, KGDT_R3_TEB, KI_EXCEPTION_ACCESS_VIOLATION, KiCheckForAtlThunk(), KiCopyInformation(), KiDebugRoutine, KiEspToTrapFrame(), KiPreprocessFault(), KiSegSsToTrapFrame(), KMODE_EXCEPTION_NOT_HANDLED, NtCurrentProcess, NULL, _EXCEPTION_RECORD::NumberParameters, PF_NX_ENABLED, ProbeForWrite(), ProbeForWriteSmallStructure(), PsGetCurrentProcess(), RPL_MASK, RtlCopyMemory, RtlDispatchException(), SANITIZE_SEG, _CONTEXT::SegCs, SharedUserData, STATUS_ACCESS_VIOLATION, STATUS_BREAKPOINT, STATUS_DATATYPE_MISALIGNMENT, STATUS_SINGLE_STEP, STATUS_STACK_OVERFLOW, STATUS_WX86_BREAKPOINT, STATUS_WX86_SINGLE_STEP, TRUE, UserMode, and ZwTerminateProcess().
BOOLEAN KiEm87StateToNpxFrame (OUT PFLOATING_SAVE_AREA NpxFrmae)
Referenced by KeContextFromKframes().
ULONG KiEspFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
Definition at line 57 of file exceptn.c.
References EFLAGS_V86_MASK, FRAME_EDITED, KernelMode, and MODE_MASK.
Referenced by KeContextFromKframes(), KeRaiseUserException(), and KiEspToTrapFrame().
VOID KiEspToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG Esp)
Definition at line 107 of file exceptn.c.
References APC_LEVEL, EFLAGS_V86_MASK, FRAME_EDITED, KeBugCheckEx(), KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrql, KernelMode, KiEspFromTrapFrame(), MODE_MASK, and SET_OF_INVALID_CONTEXT.
Referenced by KeContextToKframes(), and KiDispatchException().
BOOLEAN KiNpxFrameToEm87State (IN PFLOATING_SAVE_AREA NpxFrmae)
Referenced by KeContextToKframes().
ULONG KiSegSsFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
Definition at line 200 of file exceptn.c.
References EFLAGS_V86_MASK, KernelMode, KGDT_R0_DATA, MODE_MASK, and RPL_MASK.
Referenced by KeContextFromKframes().
VOID KiSegSsToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG SegSs)
Definition at line 238 of file exceptn.c.
References EFLAGS_V86_MASK, MODE_MASK, RPL_MASK, SEGMENT_MASK, and UserMode.
Referenced by KeContextToKframes(), and KiDispatchException().
Variable Documentation
BOOLEAN KeI386FxsrPresent
Definition at line 32 of file i386init.c.
Referenced by KeContextFromKframes(), and KeContextToKframes().
BOOLEAN KeI386XMMIPresent
Definition at line 215 of file kernlini.c.
Referenced by KiDispatchException().
UCHAR VdmUserCr0MapIn[]
Referenced by KeContextToKframes().