Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/mapview.c File Reference
mapview.c File Reference
#include "mi.h"
Data Structures
struct _NTSYM
Macros
#define MI_BP_BADMAPS() (MiStopBadMaps & 0x1)
#define PageSize PAGE_SIZE
#define ROUND_TO_PAGES64(Size) (((UINT64)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))
Typedefs
typedef struct _NTSYM NTSYM
typedef struct _NTSYM * PNTSYM
Functions
NTSTATUS MiAddViewsForSection (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL, IN KIRQL OldIrql, OUT PULONG Waited)
NTSTATUS MiAddViewsForSectionWithPfn (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL)
PVOID MiCacheImageSymbols (IN PVOID ImageBase)
LOGICAL MiCheckCacheAttributes (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute)
NTSTATUS MiCheckPurgeAndUpMapCount (IN PCONTROL_AREA ControlArea, IN LOGICAL FailIfSystemViews)
VOID MiConvertStaticSubsections (IN PCONTROL_AREA ControlArea)
VOID MiDereferenceControlArea (IN PCONTROL_AREA ControlArea)
VOID MiFillSystemPageDirectory (PVOID Base, SIZE_T NumberOfBytes)
VOID MiFillSystemPageDirectory (IN PVOID Base, IN SIZE_T NumberOfBytes)
VOID MiFreeSessionSpaceMap (VOID)
LOGICAL MiInitializeSystemSpaceMap (PVOID InputSession OPTIONAL)
PVOID MiInsertInSystemSpace (IN PMMSESSION Session, IN ULONG SizeIn64k, IN PCONTROL_AREA ControlArea)
VOID MiInsertPhysicalViewAndRefControlArea (IN PEPROCESS Process, IN PCONTROL_AREA ControlArea, IN PMI_PHYSICAL_VIEW PhysicalView)
VOID MiLoadUserSymbols (IN PCONTROL_AREA ControlArea, IN PVOID StartingAddress, IN PEPROCESS Process)
VOID MiMapLargePageSection (IN PEPROCESS Process, IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN MM_PROTECTION_MASK ProtectionMask)
NTSTATUS MiMapViewInSystemSpace (IN PVOID Section, IN PMMSESSION Session, OUT PVOID *MappedBase, IN OUT PSIZE_T ViewSize)
NTSTATUS MiMapViewOfDataSection (IN PCONTROL_AREA ControlArea, IN PEPROCESS Process, IN PVOID *CapturedBase, IN PLARGE_INTEGER SectionOffset, IN PSIZE_T CapturedViewSize, IN PSECTION Section, IN SECTION_INHERIT InheritDisposition, IN ULONG ProtectionMask, IN SIZE_T CommitSize, IN ULONG_PTR ZeroBits, IN ULONG AllocationType)
NTSTATUS MiMapViewOfImageSection (IN PCONTROL_AREA ControlArea, IN PEPROCESS Process, IN PVOID *CapturedBase, IN PLARGE_INTEGER SectionOffset, IN PSIZE_T CapturedViewSize, IN PSECTION Section, IN SECTION_INHERIT InheritDisposition, IN ULONG_PTR ZeroBits, IN ULONG AllocationType, IN SIZE_T ImageCommitment)
NTSTATUS MiMapViewOfPhysicalSection (IN PCONTROL_AREA ControlArea, IN PEPROCESS Process, IN PVOID *CapturedBase, IN PLARGE_INTEGER SectionOffset, IN PSIZE_T CapturedViewSize, IN ULONG ProtectionMask, IN ULONG_PTR ZeroBits, IN ULONG AllocationType)
LOGICAL MiReferenceSubsection (IN PMSUBSECTION MappedSubsection)
ULONG MiRemoveFromSystemSpace (IN PMMSESSION Session, IN PVOID Base, OUT PCONTROL_AREA *ControlArea)
VOID MiRemoveMappedPtes (IN PVOID BaseAddress, IN ULONG NumberOfPtes, IN PCONTROL_AREA ControlArea, IN PMMSUPPORT WorkingSetInfo)
VOID MiRemoveViewsFromSection (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL)
VOID MiRemoveViewsFromSectionWithPfn (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL)
HANDLE MiSecureVirtualMemory (IN PVOID Address, IN SIZE_T Size, IN ULONG ProbeMode, IN LOGICAL AddressSpaceMutexHeld)
VOID MiSetControlAreaSymbolsLoaded (IN PCONTROL_AREA ControlArea)
NTSTATUS MiSetPageModified (IN PMMVAD Vad, IN PVOID Address)
NTSTATUS MiUnmapViewInSystemSpace (IN PMMSESSION Session, IN PVOID MappedBase)
VOID MiUnsecureVirtualMemory (IN HANDLE SecureHandle, IN LOGICAL AddressSpaceMutexHeld)
NTSTATUS MmGetSessionMappedViewInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length, IN PULONG SessionId OPTIONAL)
NTSTATUS MmMapViewInSessionSpace (__in PVOID Section, __deref_inout_bcount(*ViewSize) PVOID *MappedBase, __inout PSIZE_T ViewSize)
NTSTATUS MmMapViewInSystemSpace (__in PVOID Section, __deref_inout_bcount(*ViewSize) PVOID *MappedBase, __inout PSIZE_T ViewSize)
NTSTATUS MmMapViewOfSection (__in PVOID SectionToMap, __in PEPROCESS Process, __deref_inout_bcount(*CapturedViewSize) PVOID *CapturedBase, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout PLARGE_INTEGER SectionOffset, __inout PSIZE_T CapturedViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in WIN32_PROTECTION_MASK Win32Protect)
HANDLE MmSecureVirtualMemory (__in_bcount(Size) PVOID Address, __in SIZE_T Size, __in ULONG ProbeMode)
NTSTATUS MmUnmapViewInSessionSpace (__in PVOID MappedBase)
NTSTATUS MmUnmapViewInSystemSpace (__in PVOID MappedBase)
VOID MmUnsecureVirtualMemory (__in HANDLE SecureHandle)
NTSYSAPI NTSTATUS NTAPI NtAreMappedFilesTheSame (__in PVOID File1MappedAsAnImage, __in PVOID File2MappedAsFile)
NTSTATUS NtMapViewOfSection (__in HANDLE SectionHandle, __in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout_opt PLARGE_INTEGER SectionOffset, __inout PSIZE_T ViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in WIN32_PROTECTION_MASK Win32Protect)
Variables
ULONG MiStopBadMaps
ULONG MiSubsectionsConvertedToDynamic
const ULONG MMDB = 'bDmM'
LIST_ENTRY MmLoadedUserImageList
MMSESSION MmSession
const ULONG MMVADKEY
Macro Definition Documentation
#define MI_BP_BADMAPS () (MiStopBadMaps & 0x1)
Definition at line 32 of file mapview.c.
Referenced by MiCheckCacheAttributes().
#define PageSize PAGE_SIZE
Referenced by MiSecureVirtualMemory().
#define ROUND_TO_PAGES64 (Size) (((UINT64)(Size) + PAGE_SIZE - 1) & ~(PAGE_SIZE - 1))
Definition at line 45 of file mapview.c.
Referenced by MiMapViewOfDataSection().
Typedef Documentation
typedef struct _NTSYM NTSYM
typedef struct _NTSYM * PNTSYM
Function Documentation
NTSTATUS MiAddViewsForSection (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL, IN KIRQL OldIrql, OUT PULONG Waited)
Definition at line 2885 of file mapview.c.
References ASSERT, _MSUBSECTION::ControlArea, _CONTROL_AREA::DereferenceList, _MSUBSECTION::DereferenceList, ExAllocatePoolWithTag, ExFreePool(), _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::Image, InsertHeadList(), LOCK_PFN, _MMPTE::Long, MI_SNAP_SUB, MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MiFillMemoryPte, MiGetSubsectionAddressForPte, MM_PFN_LOCK_ASSERT, MMSECT, MmUnusedSubsectionList, _MSUBSECTION::NextSubsection, NULL, _MSUBSECTION::NumberOfMappedViews, PagedPool, _MMSECTION_FLAGS::PhysicalMemory, POOL_MM_ALLOCATION, _MMPTE_SOFTWARE::Protection, _MMPTE_SOFTWARE::Prototype, _MSUBSECTION::PtesInSubsection, RemoveEntryList(), _CONTROL_AREA::Segment, _SEGMENT::SegmentPteTemplate, _MMPTE::Soft, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _MMSUBSECTION_FLAGS2::SubsectionAccessed, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MSUBSECTION::u2, UNLOCK_PFN, and _MSUBSECTION::UnusedPtes.
Referenced by MiAddViewsForSectionWithPfn(), and MmMapViewInSystemCache().
NTSTATUS MiAddViewsForSectionWithPfn (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL)
Definition at line 2748 of file mapview.c.
References APC_LEVEL, ASSERT, KeGetCurrentIrql(), LOCK_PFN, MiAddViewsForSection(), and Status.
Referenced by MiAddMappedPtes(), MiCcPrepareReadInfo(), and MiMapViewOfDataSection().
PVOID MiCacheImageSymbols (IN PVOID ImageBase)
Definition at line 4324 of file mapview.c.
References except, EXCEPTION_EXECUTE_HANDLER, IMAGE_DIRECTORY_ENTRY_DEBUG, NOTHING, NULL, PAGED_CODE, RtlImageDirectoryEntryToData(), and TRUE.
Referenced by MiMapViewOfImageSection(), and MmLoadSystemImage().
LOGICAL MiCheckCacheAttributes (IN PFN_NUMBER PageFrameIndex, IN PFN_NUMBER NumberOfPages, IN MI_PFN_CACHE_ATTRIBUTE CacheAttribute)
Definition at line 998 of file mapview.c.
References APC_LEVEL, ASSERT, _MMPFNENTRY::CacheAttribute, DbgBreakPoint(), DbgPrintEx(), DPFLTR_ERROR_LEVEL, DPFLTR_MM_ID, _MMPFN::e1, FALSE, _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, KeGetCurrentIrql(), LOCK_PFN, MI_BP_BADMAPS, MI_IS_PFN(), MI_PFN_ELEMENT, MiCached, MiLookupDataTableEntry(), MiNonCached, MiNotMapped, MiWriteCombined, MM_HIGHEST_USER_ADDRESS, NULL, PAGE_SHIFT, PAGE_SIZE, PsLoadedModuleList, RtlCaptureStackBackTrace(), RtlZeroMemory, StackTrace, TRUE, _MMPFN::u3, and UNLOCK_PFN.
Referenced by MiMapViewOfPhysicalSection().
NTSTATUS MiCheckPurgeAndUpMapCount (IN PCONTROL_AREA ControlArea, IN LOGICAL FailIfSystemViews)
Definition at line 4160 of file mapview.c.
References ASSERT, _EVENT_COUNTER::Event, FALSE, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KernelMode, KeWaitForSingleObject(), LOCK_PFN, MiFreeEventCounter(), MiGetEventCounter(), NULL, _EVENT_COUNTER::RefCount, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, UNLOCK_PFN, UNLOCK_PFN_AND_THEN_WAIT, and WrVirtualMemory.
Referenced by MiMapViewInSystemSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), and MiShareSessionImage().
VOID MiConvertStaticSubsections (IN PCONTROL_AREA ControlArea)
Definition at line 3293 of file mapview.c.
References ASSERT, _MSUBSECTION::DereferenceList, _LIST_ENTRY::Flink, MI_SNAP_SUB, MiRemoveViewsFromSection(), MiSubsectionsConvertedToDynamic, _MSUBSECTION::NextSubsection, NOTHING, NULL, _MSUBSECTION::NumberOfMappedViews, _MSUBSECTION::PtesInSubsection, _MSUBSECTION::SubsectionBase, _MMSUBSECTION_FLAGS2::SubsectionConverted, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, _MSUBSECTION::u, and _MSUBSECTION::u2.
VOID MiDereferenceControlArea (IN PCONTROL_AREA ControlArea)
Definition at line 1867 of file mapview.c.
References LOCK_PFN, and MiCheckControlArea().
Referenced by MiMapViewInSystemSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), and MiShareSessionImage().
VOID MiFillSystemPageDirectory (PVOID Base, SIZE_T NumberOfBytes)
Referenced by MiMapViewInSystemSpace().
VOID MiFillSystemPageDirectory (IN PVOID Base, IN SIZE_T NumberOfBytes)
Definition at line 5186 of file mapview.c.
References ASSERT, _MMPTE::Hard, LOCK_PFN, MI_GET_PAGE_COLOR_FROM_PTE, MI_WRITE_VALID_PTE, MiChargeCommitmentCantExpand(), MiEnsureAvailablePageOrWait(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiInitializePfnAndMakePteValid(), MiInitializePfnForOtherProcess(), MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiRemoveZeroPage(), MM_DBG_COMMIT_FILL_SYSTEM_DIRECTORY, MM_HIGH_LIMIT, MM_TRACK_COMMIT, MmAvailablePages, MmSystemPageDirectory, MmSystemPagePtes, NULL, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, PD_PER_SYSTEM, PDE_PER_PAGE, TRUE, _MMPTE::u, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and ValidKernelPde.
VOID MiFreeSessionSpaceMap (VOID)
Definition at line 5872 of file mapview.c.
References ExFreePool(), KeBugCheckEx(), MiRemoveBitMap, MmSessionSpace, NULL, PAGED_CODE, _MM_SESSION_SPACE::Session, SESSION_HAS_VALID_VIEWS_ON_EXIT, _MM_SESSION_SPACE::SessionId, _MMSESSION::SystemSpaceBitMap, _MMSESSION::SystemSpaceHashEntries, _MMSESSION::SystemSpaceHashSize, and _MMSESSION::SystemSpaceViewTable.
Referenced by MiDereferenceSessionFinal().
LOGICAL MiInitializeSystemSpaceMap (PVOID InputSession OPTIONAL)
Definition at line 5757 of file mapview.c.
References ARGUMENT_PRESENT, ASSERT, ExAllocatePoolWithTag, FALSE, KeInitializeGuardedMutex(), MiCreateBitMap, MiRemoveBitMap, MiSessionViewStart, MiSystemViewStart, MM_BUMP_SESSION_FAILURES, MM_SESSION_FAILURE_NO_NONPAGED_POOL, MM_SESSION_FAILURE_NO_SESSION_PAGED_POOL, MmSession, MmSessionViewSize, MmSystemViewSize, NonPagedPool, NULL, PAGE_SIZE, PagedPool, RtlClearAllBits(), RtlZeroMemory, _MMSESSION::SystemSpaceBitMap, _MMSESSION::SystemSpaceHashEntries, _MMSESSION::SystemSpaceHashKey, _MMSESSION::SystemSpaceHashSize, _MMSESSION::SystemSpaceViewLock, _MMSESSION::SystemSpaceViewLockPointer, _MMSESSION::SystemSpaceViewStart, _MMSESSION::SystemSpaceViewTable, TRUE, and X64K.
Referenced by MiBuildPagedPool(), and MiSessionCreateInternal().
PVOID MiInsertInSystemSpace (IN PMMSESSION Session, IN ULONG SizeIn64k, IN PCONTROL_AREA ControlArea)
Definition at line 5534 of file mapview.c.
References ASSERT, ExAllocatePoolWithTag, ExFreePool(), LOCK_SYSTEM_VIEW_SPACE, MI_64K_ALIGN, NO_BITS_FOUND, NonPagedPool, NULL, PAGED_CODE, PagedPool, RtlFindClearBitsAndSet(), RtlZeroMemory, UNLOCK_SYSTEM_VIEW_SPACE, and X64K.
Referenced by MiMapViewInSystemSpace().
VOID MiInsertPhysicalViewAndRefControlArea (IN PEPROCESS Process, IN PCONTROL_AREA ControlArea, IN PMI_PHYSICAL_VIEW PhysicalView)
Definition at line 939 of file mapview.c.
References ASSERT, LOCK_PFN, MiInsertNode(), NULL, UNLOCK_PFN, and VadDevicePhysicalMemory.
Referenced by MiMapViewOfPhysicalSection().
VOID MiLoadUserSymbols (IN PCONTROL_AREA ControlArea, IN PVOID StartingAddress, IN PEPROCESS Process)
Definition at line 1729 of file mapview.c.
References _UNICODE_STRING::Buffer, _KLDR_DATA_TABLE_ENTRY::CheckSum, _IMAGE_OPTIONAL_HEADER::CheckSum, CONTAINING_RECORD, DbgLoadImageSymbols(), _KLDR_DATA_TABLE_ENTRY::DllBase, ExAcquireResourceExclusiveLite(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExReleaseResourceLite(), _LIST_ENTRY::Flink, _KLDR_DATA_TABLE_ENTRY::FullDllName, IMAGE_NT_OPTIONAL_HDR64_MAGIC, _KLDR_DATA_TABLE_ENTRY::InLoadOrderLinks, InsertTailList(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), _UNICODE_STRING::Length, _KLDR_DATA_TABLE_ENTRY::LoadCount, _IMAGE_OPTIONAL_HEADER::Magic, _UNICODE_STRING::MaximumLength, MMDB, MmLoadedUserImageList, NonPagedPool, NOTHING, NT_SUCCESS, NULL, _IMAGE_NT_HEADERS::OptionalHeader, PsLoadedModuleResource, RtlCopyMemory, RtlFreeAnsiString(), RtlImageNtHeader(), RtlUnicodeStringToAnsiString(), RtlZeroMemory, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _IMAGE_OPTIONAL_HEADER::SizeOfImage, Status, TRUE, and UNICODE_NULL.
Referenced by MiMapViewOfImageSection().
VOID MiMapLargePageSection (IN PEPROCESS Process, IN PVOID StartingAddress, IN PVOID EndingAddress, IN PMMVAD Vad, IN MM_PROTECTION_MASK ProtectionMask)
Definition at line 3368 of file mapview.c.
References ASSERT, _MMPTE::Hard, _SEGMENT_FLAGS::LargePages, LOCK_PFN, LOCK_WS_UNSAFE, MI_GET_PAGE_FRAME_FROM_PTE, MI_MAKE_PDE_MAP_LARGE_PAGE, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_SET_ACCESSED_IN_PTE, MI_SET_PTE_DIRTY, MI_WRITE_VALID_PTE, MiGetPdeAddress, MiGetPteAddress, MM_VA_MAPPED_BY_PDE, PAGE_SHIFT, _MMPTE_HARDWARE::PageFrameNumber, PsGetCurrentThread(), _CONTROL_AREA::Segment, _SEGMENT::SegmentFlags, _MMPFN::ShareCount, _MMPTE::u, _MMPFN::u2, UNLOCK_PFN, UNLOCK_WS_UNSAFE, VadLargePageSection, _MMPTE_HARDWARE::Valid, and _MMPTE_HARDWARE::Write.
Referenced by MiMapViewOfDataSection().
NTSTATUS MiMapViewInSystemSpace (IN PVOID Section, IN PMMSESSION Session, OUT PVOID * MappedBase, IN OUT PSIZE_T ViewSize)
Definition at line 4800 of file mapview.c.
References ASSERT, BYTES_TO_PAGES, _SEGMENT::ControlArea, FALSE, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, LOCK_SYSTEM_VIEW_SPACE, MiAddMappedPtes(), MiCheckPurgeAndUpMapCount(), MiDereferenceControlArea(), MiFillSystemPageDirectory(), MiGetPteAddress, MiInsertInSystemSpace(), MiRemoveFromSystemSpace(), MiSessionCommitPageTables(), NT_SUCCESS, NULL, NumberOfBytes, PAGED_CODE, _MMSECTION_FLAGS::Rom, RtlClearBits(), _CONTROL_AREA::Segment, Status, STATUS_INVALID_VIEW_SIZE, STATUS_NO_MEMORY, STATUS_SUCCESS, _CONTROL_AREA::u, UNLOCK_SYSTEM_VIEW_SPACE, and X64K.
Referenced by MmMapViewInSessionSpace(), and MmMapViewInSystemSpace().
NTSTATUS MiMapViewOfDataSection (IN PCONTROL_AREA ControlArea, IN PEPROCESS Process, IN PVOID * CapturedBase, IN PLARGE_INTEGER SectionOffset, IN PSIZE_T CapturedViewSize, IN PSECTION Section, IN SECTION_INHERIT InheritDisposition, IN ULONG ProtectionMask, IN SIZE_T CommitSize, IN ULONG_PTR ZeroBits, IN ULONG AllocationType)
Definition at line 3504 of file mapview.c.
References ASSERT, BYTES_TO_PAGES, _MMVAD_FLAGS::CommitCharge, _MMEXTEND_INFO::CommittedSize, _MMVAD::ControlArea, _MMVAD_FLAGS2::CopyOnWrite, _MMVAD::EndingVpn, ExAllocatePoolWithTag, ExFreePool(), _MMVAD_FLAGS2::ExtendableFile, _MMVAD_LONG::ExtendedInfo, _SEGMENT::ExtendInfo, FALSE, _MMVAD_FLAGS2::FileOffset, _SEGMENT::FirstMappedVa, _MMVAD::FirstPrototypePte, _MMVAD_FLAGS2::Inherit, InterlockedExchangeAddSizeT, InterlockedIncrement, KeAcquireGuardedMutexUnsafe(), KeFeatureBits, KeReleaseGuardedMutexUnsafe(), KF_LARGE_PAGE, _SEGMENT_FLAGS::LargePages, _MMVAD::LastContiguousPte, LOCK_WS_UNSAFE, _MMPTE::Long, _MMVAD_FLAGS2::LongVad, MEM_DOS_LIM, MEM_RESERVE, MEM_TOP_DOWN, MI_ALIGN_TO_SIZE, MI_IS_GUARD, MI_IS_PTE_PROTECTION_COPY_WRITE, MI_VA_TO_VPN, MI_WRITE_INVALID_PTE, MiAddViewsForSectionWithPfn(), MiChargeCommitment(), MiCheckForConflictingVadExistence(), MiCheckPurgeAndUpMapCount(), MiDereferenceControlArea(), MiFindEmptyAddressRange(), MiFindEmptyAddressRangeDown, MiInsertVad(), MiInsertVadCharges(), MiMapLargePageSection(), MiRemoveViewsFromSectionWithPfn(), MiReturnCommitment, MM_DBG_COMMIT_MAPVIEW_DATA, MM_EXECUTE_READWRITE, MM_HIGHEST_VAD_ADDRESS, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NOACCESS, MM_READWRITE, MM_TRACK_COMMIT, MM_USER_ADDRESS_RANGE_LIMIT, MmSectionBasedMutex, MmSectionCommitMutex, MmSharedCommit, MMVADKEY, _SUBSECTION::NextSubsection, _MMVAD_FLAGS::NoChange, NonPagedPool, NT_SUCCESS, NULL, _SEGMENT::NumberOfCommittedPages, PAGE_SHIFT, PAGE_SIZE, _MMVAD_FLAGS::Protection, PsGetCurrentThread(), _SUBSECTION::PtesInSubsection, _MMEXTEND_INFO::ReferenceCount, ROUND_TO_PAGES64, RtlZeroMemory, SEC_NO_CHANGE, _MMVAD_FLAGS2::SecNoChange, _SEGMENT::SegmentFlags, _SEGMENT::SegmentPteTemplate, _SEGMENT::SizeOfSegment, _MMVAD::StartingVpn, Status, STATUS_COMMITMENT_LIMIT, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_9, STATUS_INVALID_VIEW_SIZE, STATUS_NO_MEMORY, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _SEGMENT::TotalNumberOfPtes, _SEGMENT_FLAGS::TotalNumberOfPtes4132, TRUE, _MMPTE::u, _MMVAD::u, _SEGMENT::u2, _MMVAD::u2, _MMVAD_LONG::u4, UNLOCK_WS_UNSAFE, _SUBSECTION::UnusedPtes, _MMVAD::VadFlags, _MMVAD::VadFlags2, ViewShare, and X64K.
Referenced by MmMapViewOfSection().
NTSTATUS MiMapViewOfImageSection (IN PCONTROL_AREA ControlArea, IN PEPROCESS Process, IN PVOID * CapturedBase, IN PLARGE_INTEGER SectionOffset, IN PSIZE_T CapturedViewSize, IN PSECTION Section, IN SECTION_INHERIT InheritDisposition, IN ULONG_PTR ZeroBits, IN ULONG AllocationType, IN SIZE_T ImageCommitment)
_WIN64
Definition at line 1904 of file mapview.c.
References ASSERT, BYTES_TO_PAGES, _MMVAD_FLAGS::CommitCharge, _MMVAD::ControlArea, _MMVAD::EndingVpn, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _MMVAD::FirstPrototypePte, FLG_ENABLE_KDEBUG_SYMBOL_LOAD, _MMSUBSECTION_FLAGS::GlobalMemory, _MMPTE::Hard, IMAGE_ADDRESSING_MODE_32BIT, IMAGE_FILE_MACHINE_I386, _IMAGE_INFO::ImageAddressingMode, _IMAGE_INFO::ImageBase, _IMAGE_INFO::ImageSectionNumber, _IMAGE_INFO::ImageSelector, _IMAGE_INFO::ImageSize, _MMVAD_FLAGS2::Inherit, KeFeatureBits, KeGetPreviousMode, KeSweepIcacheRange, KF_LARGE_PAGE, _MMVAD::LastContiguousPte, LOCK_WS_UNSAFE, MEM_LARGE_PAGES, MI_64K_ALIGN, MI_ALIGN_TO_SIZE, MI_VA_TO_VPN, MiAllocateAweInfo(), MiAllocateLargePages(), MiCacheImageSymbols(), MiCheckForConflictingVadExistence(), MiCheckPurgeAndUpMapCount(), MiDereferenceControlArea(), MiFindEmptyAddressRange(), MiFindEmptyAddressRangeDown, MiFreeLargePages(), MiInsertAweInfo(), MiInsertVad(), MiInsertVadCharges(), MiLoadUserSymbols(), MiReleasePhysicalCharges(), MiSetControlAreaSymbolsLoaded(), MiSetPageModified(), MiUnmapViewOfSection(), MM_ALLOCATION_FILLS_VAD, MM_EXECUTE_READWRITE, MM_EXECUTE_WRITECOPY, MM_HIGHEST_VAD_ADDRESS, MM_LOWEST_USER_ADDRESS, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NOACCESS, MM_USER_ADDRESS_RANGE_LIMIT, MmHighestUserAddress, MMVADKEY, MmVirtualBias, _SUBSECTION::NextSubsection, NonPagedPool, NT_SUCCESS, NtGlobalFlag, NULL, PAGE_SHIFT, PAGE_SIZE, _IMAGE_INFO::Properties, _MMPTE_SOFTWARE::Protection, _MMVAD_FLAGS::Protection, _MMPTE_SOFTWARE::Prototype, PsCallImageNotifyRoutines(), PsGetCurrentThread(), PsImageNotifyEnabled, PsInitialSystemProcess, RtlCopyMemory, RtlZeroMemory, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _MMPTE::Soft, _MMVAD::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_IMAGE_MACHINE_TYPE_MISMATCH, STATUS_IMAGE_NOT_AT_BASE, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_MEMORY, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _SUBSECTION::SubsectionFlags, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _SUBSECTION::u, _MMVAD::u, _MMVAD::u2, UNLOCK_WS_UNSAFE, UNMAP_ADDRESS_SPACE_HELD, USER_SHARED_DATA, _MMVAD::VadFlags, _MMVAD::VadFlags2, VadImageMap, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, ViewShare, and X64K.
Referenced by MmMapViewOfSection().
NTSTATUS MiMapViewOfPhysicalSection (IN PCONTROL_AREA ControlArea, IN PEPROCESS Process, IN PVOID * CapturedBase, IN PLARGE_INTEGER SectionOffset, IN PSIZE_T CapturedViewSize, IN ULONG ProtectionMask, IN ULONG_PTR ZeroBits, IN ULONG AllocationType)
Definition at line 1148 of file mapview.c.
References ASSERT, CacheType, _MMVAD_LONG::ControlArea, _MMVAD_LONG::EndingVpn, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, ExFreePool(), FALSE, _MMVAD_LONG::FirstPrototypePte, _MMPTE::Hard, _MMVAD_FLAGS2::Inherit, KeFeatureBits, KF_LARGE_PAGE, _MMVAD_LONG::LastContiguousPte, LOCK_PFN, LOCK_WS_UNSAFE, _MMPTE::Long, _MMVAD_FLAGS2::LongVad, MEM_LARGE_PAGES, MEM_RESERVE, MEM_TOP_DOWN, MI_64K_ALIGN, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DISABLE_CACHING, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_GUARD, MI_IS_NOCACHE, MI_IS_PFN(), MI_IS_WRITECOMBINE, MI_MAKE_PDE_MAP_LARGE_PAGE, MI_MAKE_VALID_USER_PTE, MI_PAGE_FRAME_INDEX_MUST_BE_CACHED, MI_PFN_ELEMENT, MI_PHYSICAL_VIEW_KEY, MI_PREPARE_FOR_NONCACHED, MI_SET_ACCESSED_IN_PTE, MI_SET_PTE_DIRTY, MI_SET_PTE_WRITE_COMBINE, MI_TRANSLATE_CACHETYPE(), MI_VA_TO_VPN, MI_WRITE_VALID_PTE, MiAllocateLargePages(), MiCached, MiCheckCacheAttributes(), MiCheckForConflictingVadExistence(), MiCreatePhysicalVadRoot(), MiFindEmptyAddressRange(), MiFindEmptyAddressRangeDown, MiGetNextVad, MiGetPdeAddress, MiGetPreviousVad, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInsertPhysicalViewAndRefControlArea(), MiInsertVad(), MiInsertVadCharges(), MiIsPteOnPdeBoundary, MiMakePdeExistAndMakeValid(), MiNonCached, MiNonCachedCollisions, MiRemoveVad(), MiRemoveVadCharges(), MiReturnPageTablePageCommitment(), MiWriteCombined, MM_HIGHEST_VAD_ADDRESS, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NOACCESS, MM_NOIRQL, MM_USER_ADDRESS_RANGE_LIMIT, MM_VA_MAPPED_BY_PDE, MM_VIEW_UNMAP, MmCached, MmNonCached, MmWriteCombined, NonPagedPool, NT_SUCCESS, NULL, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMVAD_FLAGS::Protection, PsGetCurrentThread(), PTE_PER_PAGE, RtlZeroMemory, _MMPFN::ShareCount, _MMVAD_LONG::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_9, STATUS_NO_MEMORY, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMVAD::u, _MMVAD_LONG::u, _MMPFN::u2, _MMVAD_LONG::u2, UNLOCK_PFN, UNLOCK_WS, UNLOCK_WS_UNSAFE, _MI_PHYSICAL_VIEW::Vad, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_LONG::VadFlags, _MMVAD_LONG::VadFlags2, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Write, and X64K.
Referenced by MmMapViewOfSection().
LOGICAL MiReferenceSubsection (IN PMSUBSECTION MappedSubsection)
Definition at line 2802 of file mapview.c.
References ASSERT, FALSE, MI_SNAP_SUB, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MM_PFN_LOCK_ASSERT, NULL, RemoveEntryList(), and TRUE.
Referenced by MiUpControlAreaRefs(), MmFlushSection(), and MmPurgeSection().
ULONG MiRemoveFromSystemSpace (IN PMMSESSION Session, IN PVOID Base, OUT PCONTROL_AREA * ControlArea)
Definition at line 5687 of file mapview.c.
References DRIVER_UNMAPPING_INVALID_VIEW, KeBugCheckEx(), and PAGED_CODE.
Referenced by MiMapViewInSystemSpace(), and MiUnmapViewInSystemSpace().
VOID MiRemoveMappedPtes (IN PVOID BaseAddress, IN ULONG NumberOfPtes, IN PCONTROL_AREA ControlArea, IN PMMSUPPORT WorkingSetInfo)
Definition at line 827 of file mapcache.c.
References ASSERT, _MSUBSECTION::ControlArea, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_PFN, LOCK_WORKING_SET, _MMPTE::Long, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiCheckControlArea(), MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiGetSubsectionAddress, MiMakeSystemAddressValidPfn(), MiPteToProto, MiRemoveViewsFromSection(), MiTerminateWsle(), MM_MAXIMUM_FLUSH_COUNT, MmSystemPagePtes, NOTHING, NULL, _MMPFN::OriginalPte, PAGE_SIZE, PD_PER_SYSTEM, PDE_PER_PAGE, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MSUBSECTION::PtesInSubsection, _MMPTE::Soft, _MSUBSECTION::SubsectionBase, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, and _MMPFN::WsIndex.
Referenced by MiUnmapViewInSystemSpace().
VOID MiRemoveViewsFromSection (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL)
Definition at line 3155 of file mapview.c.
References ASSERT, _MSUBSECTION::ControlArea, _CONTROL_AREA::DereferenceList, _MSUBSECTION::DereferenceList, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::Image, InsertTailList(), MI_SNAP_SUB, MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MM_PFN_LOCK_ASSERT, MmUnusedSubsectionList, _MSUBSECTION::NextSubsection, NULL, _MSUBSECTION::NumberOfMappedViews, _MMSECTION_FLAGS::PhysicalMemory, _MSUBSECTION::PtesInSubsection, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MMSUBSECTION_FLAGS::SubsectionStatic, _CONTROL_AREA::u, and _MSUBSECTION::u.
Referenced by MiAppendSubsectionChain(), MiConvertStaticSubsections(), MiRemoveMappedPtes(), MiRemoveViewsFromSectionWithPfn(), and MmUnmapViewInSystemCache().
VOID MiRemoveViewsFromSectionWithPfn (IN PMSUBSECTION StartMappedSubsection, IN UINT64 LastPteOffset OPTIONAL)
Definition at line 3246 of file mapview.c.
References APC_LEVEL, ASSERT, KeGetCurrentIrql(), LOCK_PFN, MiRemoveViewsFromSection(), and UNLOCK_PFN.
Referenced by MiCcReleasePrefetchResources(), and MiMapViewOfDataSection().
HANDLE MiSecureVirtualMemory (IN PVOID Address, IN SIZE_T Size, IN ULONG ProbeMode, IN LOGICAL AddressSpaceMutexHeld)
Definition at line 5972 of file mapview.c.
References _ETHREAD::AddressSpaceOwner, ASSERT, _MMVAD::Balance, _MM_AVL_TABLE::BalancedRoot, _MMVAD::EndingVpn, _MMADDRESS_LIST::EndVpn, _MMSECURE_ENTRY::EndVpn, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, Handle, InitializeListHead(), InsertTailList(), KeAreAllApcsDisabled(), _MMVAD::LeftChild, _MMSECURE_ENTRY::List, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _MMPTE::Long, _MMVAD::LongFlags, _MMSECURE_ENTRY::LongFlags2, _MMVAD_LONG::LongFlags2, _MMVAD_FLAGS2::LongVad, _MMVAD_FLAGS::MemCommit, MI_ALIGN_TO_SIZE, MI_MAKE_PARENT, MI_PDE_MAPS_LARGE_PAGE, MI_VA_TO_VPN, MiDoesPdeExistAndMakeValid(), MiDoesPpeExistAndMakeValid, MiDoesPxeExistAndMakeValid, MiGetPdeAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MiLocateAddress(), MiPhysicalViewAdjuster(), MM_EXECUTE_READWRITE, MM_EXECUTE_WRITECOPY, MM_HIGHEST_USER_ADDRESS, MM_NOACCESS, MM_NOIRQL, MM_READWRITE, _MMVAD_FLAGS2::MultipleSecured, _MMVAD_FLAGS::NoChange, _MM_AVL_TABLE::NodeHint, NonPagedPool, NULL, _MMVAD_FLAGS2::OneSecured, PAGE_READONLY, PAGE_SIZE, PAGE_SIZE_X86NT, PAGED_CODE, PageSize, _MMVAD::Parent, _MMVAD_FLAGS::PrivateMemory, ProbeForWrite(), _MMVAD_FLAGS::Protection, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMVAD_FLAGS2::ReadOnly, _MMADDRESS_NODE::RightChild, _MMVAD::RightChild, RtlCopyMemory, RtlZeroMemory, SANITIZE_PARENT_NODE, _MMVAD_LONG::Secured, _MMVAD::StartingVpn, _MMADDRESS_LIST::StartVpn, _MMSECURE_ENTRY::StartVpn, TRUE, _MMPTE::u, _MMVAD::u, _MMVAD_LONG::u, _MMVAD::u1, _MMSECURE_ENTRY::u2, _MMVAD::u2, _MMVAD_LONG::u2, _MMVAD_LONG::u3, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_LONG::VadFlags, _MMSECURE_ENTRY::VadFlags2, _MMVAD::VadFlags2, _MMVAD_LONG::VadFlags2, _EPROCESS::VadFreeHint, VadLargePages, _EPROCESS::VadRoot, VadRotatePhysical, _MMVAD_FLAGS::VadType, and VadWriteWatch.
Referenced by MmSecureVirtualMemory().
VOID MiSetControlAreaSymbolsLoaded (IN PCONTROL_AREA ControlArea)
Definition at line 1699 of file mapview.c.
References LOCK_PFN, and UNLOCK_PFN.
Referenced by MiMapViewOfImageSection().
NTSTATUS MiSetPageModified (IN PMMVAD Vad, IN PVOID Address)
Definition at line 4474 of file mapview.c.
References ASSERT, _EPROCESS::CommitCharge, _EPROCESS::CommitChargeLimit, _EPROCESS::CommitChargePeak, _MMPFN::e1, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _MMPTE::Hard, _EPROCESS::Job, _EPROCESS::JobStatus, LOCK_PFN, LOCK_WS_UNSAFE, MI_FLUSH_SINGLE_TB, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_IS_PTE_DIRTY, MI_PFN_ELEMENT, MI_SET_MODIFIED, MI_SET_PTE_CLEAN, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiChargeCommitment(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiReleasePageFileSpace(), MiReturnCommitment, MM_DBG_COMMIT_IMAGE, MM_DBG_COMMIT_INSERT_VAD, MM_MAX_COMMIT, MM_TRACK_COMMIT, NT_SUCCESS, NULL, _MMPFN::OriginalPte, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PsChangeJobMemoryUsage(), PsChargeProcessPageFileQuota(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsReportProcessMemoryLimitViolation(), PsReturnProcessPageFileQuota(), _MMPTE::Soft, Status, STATUS_COMMITMENT_LIMIT, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS_UNSAFE, _MMPTE_HARDWARE::Valid, and _MMPFNENTRY::WriteInProgress.
Referenced by MiMapViewOfImageSection().
NTSTATUS MiUnmapViewInSystemSpace (IN PMMSESSION Session, IN PVOID MappedBase)
Definition at line 5469 of file mapview.c.
References _MM_SESSION_SPACE::GlobalVirtualAddress, LOCK_SYSTEM_VIEW_SPACE, MiRemoveFromSystemSpace(), MiRemoveMappedPtes(), MmSessionSpace, MmSystemCacheWs, PAGE_SHIFT, PAGED_CODE, RtlClearBits(), STATUS_SUCCESS, UNLOCK_SYSTEM_VIEW_SPACE, _MM_SESSION_SPACE::Vm, and X64K.
Referenced by MmUnmapViewInSessionSpace(), and MmUnmapViewInSystemSpace().
VOID MiUnsecureVirtualMemory (IN HANDLE SecureHandle, IN LOGICAL AddressSpaceMutexHeld)
Definition at line 6627 of file mapview.c.
References ASSERT, CONTAINING_RECORD, ExFreePool(), FALSE, _EPROCESS::Flags, _LIST_ENTRY::Flink, IsListEmpty, List, _MMSECURE_ENTRY::List, _MMVAD_LONG::List, LOCK_ADDRESS_SPACE, _MMVAD_LONG::LongFlags2, _MMVAD_FLAGS2::LongVad, MiLocateAddress(), _MMVAD_FLAGS2::MultipleSecured, _MMVAD_FLAGS::NoChange, _MMVAD_FLAGS2::OneSecured, PAGED_CODE, _MMVAD_FLAGS::PrivateMemory, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcess(), RemoveEntryList(), _MMVAD_FLAGS2::SecNoChange, _MMSECURE_ENTRY::StartVpn, _MMVAD_LONG::u, _MMVAD_LONG::u2, _MMVAD_LONG::u3, UNLOCK_ADDRESS_SPACE, _MMVAD_LONG::VadFlags, and _MMVAD_LONG::VadFlags2.
Referenced by MmUnsecureVirtualMemory().
NTSTATUS MmGetSessionMappedViewInformation (OUT PVOID SystemInformation, IN ULONG SystemInformationLength, OUT PULONG Length, IN PULONG SessionId OPTIONAL)
Definition at line 4970 of file mapview.c.
References _MMSESSION::BitmapFailures, ExLockUserBuffer(), ExUnlockUserBuffer(), Index, IoWriteAccess, KeGetPreviousMode, LOCK_SYSTEM_VIEW_SPACE, MmAttachSession(), MmDetachSession(), MmGetNextSession(), MmGetSessionId(), MmQuitNextSession(), MmSessionSpace, NO_BITS_FOUND, NT_SUCCESS, NULL, RtlFindClearBits(), RtlFindLongestRunClear(), _MM_SESSION_SPACE::Session, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, _MMSESSION::SystemSpaceBitMap, TRUE, UNLOCK_SYSTEM_VIEW_SPACE, and X64K.
Referenced by NtQuerySystemInformation().
NTSTATUS MmMapViewInSessionSpace (__in PVOID Section, __deref_inout_bcount *ViewSize PVOID * MappedBase, __inout PSIZE_T ViewSize)
Definition at line 4747 of file mapview.c.
References ASSERT, _NTSYM::Flags, MiMapViewInSystemSpace(), MmIsAddressValid(), MmSessionSpace, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _MM_SESSION_SPACE::Session, STATUS_NOT_MAPPED_VIEW, and TRUE.
Referenced by MiSessionWideReserveImageAddress().
NTSTATUS MmMapViewInSystemSpace (__in PVOID Section, __deref_inout_bcount *ViewSize PVOID * MappedBase, __inout PSIZE_T ViewSize)
Definition at line 4700 of file mapview.c.
References MiMapViewInSystemSpace(), MmSession, and PAGED_CODE.
Referenced by MiSessionWideReserveImageAddress().
NTSTATUS MmMapViewOfSection (__in PVOID SectionToMap, __in PEPROCESS Process, __deref_inout_bcount *CapturedViewSize PVOID * CapturedBase, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout PLARGE_INTEGER SectionOffset, __inout PSIZE_T CapturedViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in WIN32_PROTECTION_MASK Win32Protect)
Definition at line 619 of file mapview.c.
References _SEGMENT::ControlArea, FALSE, _CONTROL_AREA::Flags, _SECTION::Flags, _LARGE_INTEGER::HighPart, _MMSECTION_FLAGS::Image, _SEGMENT::ImageCommitment, _SECTION::InitialPageProtection, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, MEM_RESERVE, MiIsProtectionCompatible(), MiMakeProtectionMask(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MM_HIGHEST_VAD_ADDRESS, MM_INVALID_PROTECTION, _MMSECTION_FLAGS::NoCache, PAGE_EXECUTE_READWRITE, PAGE_NOCACHE, PAGE_READWRITE, PAGE_WRITECOMBINE, PAGED_CODE, _MMSECTION_FLAGS::PhysicalMemory, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentProcess(), _LARGE_INTEGER::QuadPart, _SECTION::Segment, _SECTION::SizeOfSection, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_10, STATUS_INVALID_PARAMETER_5, STATUS_INVALID_PARAMETER_9, STATUS_INVALID_VIEW_SIZE, STATUS_PROCESS_IS_TERMINATING, STATUS_SECTION_PROTECTION, TRUE, _CONTROL_AREA::u, _SECTION::u, _SEGMENT::u1, UNLOCK_ADDRESS_SPACE, and _MMSECTION_FLAGS::WriteCombined.
Referenced by MiLoadImageSection(), MmCreatePeb(), MmInitializeProcessAddressSpace(), NtAcceptConnectPort(), NtMapViewOfSection(), NtSecureConnectPort(), Phase1InitializationDiscard(), and PsMapSystemDll().
HANDLE MmSecureVirtualMemory (__in_bcount(Size) PVOID Address, __in SIZE_T Size, __in ULONG ProbeMode)
Definition at line 5928 of file mapview.c.
References FALSE, and MiSecureVirtualMemory().
Referenced by CmpSetValueKeyExisting().
NTSTATUS MmUnmapViewInSessionSpace (__in PVOID MappedBase)
Definition at line 5429 of file mapview.c.
References ASSERT, _NTSYM::Flags, MiUnmapViewInSystemSpace(), MmIsAddressValid(), MmSessionSpace, PAGED_CODE, PS_PROCESS_FLAGS_IN_SESSION, PsGetCurrentProcess(), _MM_SESSION_SPACE::Session, STATUS_NOT_MAPPED_VIEW, and TRUE.
Referenced by MiSessionWideReserveImageAddress().
NTSTATUS MmUnmapViewInSystemSpace (__in PVOID MappedBase)
Definition at line 5398 of file mapview.c.
References MiUnmapViewInSystemSpace(), and PAGED_CODE.
Referenced by MiSessionWideReserveImageAddress().
VOID MmUnsecureVirtualMemory (__in HANDLE SecureHandle)
Definition at line 6596 of file mapview.c.
References FALSE, and MiUnsecureVirtualMemory().
Referenced by CmpSetValueKeyExisting().
NTSYSAPI NTSTATUS NTAPI NtAreMappedFilesTheSame (__in PVOID File1MappedAsAnImage, __in PVOID File2MappedAsFile)
Definition at line 4357 of file mapview.c.
References _MMVAD::ControlArea, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _SECTION_OBJECT_POINTERS::ImageSectionObject, LOCK_ADDRESS_SPACE, MiFindImageSectionObject(), MiLocateAddress(), NULL, _MMVAD_FLAGS::PrivateMemory, PsGetCurrentProcess(), _FILE_OBJECT::SectionObjectPointer, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INVALID_ADDRESS, STATUS_NOT_SAME_DEVICE, STATUS_SUCCESS, _CONTROL_AREA::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, and _MMVAD::VadFlags.
NTSTATUS NtMapViewOfSection (__in HANDLE SectionHandle, __in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout_opt PLARGE_INTEGER SectionOffset, __inout PSIZE_T ViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in WIN32_PROTECTION_MASK Win32Protect)
Definition at line 181 of file mapview.c.
References ARGUMENT_PRESENT, _SEGMENT::ControlArea, DbgkMapViewOfSection(), except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), _CONTROL_AREA::Flags, KeGetPreviousModeByThread, KernelMode, _LARGE_INTEGER::LowPart, MEM_DOS_LIM, MEM_LARGE_PAGES, MEM_RESERVE, MEM_TOP_DOWN, MiMakeProtectionMask(), MM_HIGHEST_VAD_ADDRESS, MM_INVALID_PROTECTION, MM_MAXIMUM_ZERO_BITS, MM_USER_ADDRESS_RANGE_LIMIT, MmHighestPhysicalPage, MmMakeSectionAccess, MmMapViewOfSection(), MmSectionObjectType, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMSECTION_FLAGS::PhysicalMemory, PROBE_ALIGNMENT, ProbeForWritePointer, ProbeForWriteSmallStructure(), ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _LARGE_INTEGER::QuadPart, RtlFindMostSignificantBit(), SEC_NO_CHANGE, _SECTION::Segment, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_IMAGE_NOT_AT_BASE, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_INVALID_PARAMETER_6, STATUS_INVALID_PARAMETER_8, STATUS_INVALID_PARAMETER_9, STATUS_MAPPED_ALIGNMENT, _ETHREAD::Tcb, _CONTROL_AREA::u, ViewShare, ViewUnmap, X64K, and ZERO_LARGE.
Variable Documentation
ULONG MiStopBadMaps
Definition at line 31 of file mapview.c.
ULONG MiSubsectionsConvertedToDynamic
Definition at line 43 of file mapview.c.
Referenced by MiConvertStaticSubsections().
const ULONG MMDB = 'bDmM'
Definition at line 25 of file mapview.c.
Referenced by MiLoadUserSymbols().
LIST_ENTRY MmLoadedUserImageList
Definition at line 228 of file mminit.c.
Referenced by MiLoadUserSymbols().
MMSESSION MmSession
Definition at line 47 of file mapview.c.
Referenced by MiInitializeSystemSpaceMap(), MiReleaseAllMemory(), and MmMapViewInSystemSpace().
const ULONG MMVADKEY
Definition at line 22 of file allocvm.c.
Referenced by MiMapViewOfDataSection(), and MiMapViewOfImageSection().