Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmwrapr2.c File Reference
cmwrapr2.c File Reference
#include "cmp.h"
Functions
BOOLEAN CmpFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
Variables
BOOLEAN CmpNoWrite
KEVENT EndRegistryCommand
KEVENT StartRegistryCommand
Function Documentation
BOOLEAN CmpFileSetSize (PHHIVE Hive, ULONG FileType, ULONG FileSize, ULONG OldFileSize)
Definition at line 42 of file cmwrapr2.c.
References ASSERT, ASSERT_HIVE_WRITER_LOCK_OWNED, CmKdPrintEx, CML_BUGCHECK, CmpDoFileSetSize(), DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, NT_SUCCESS, and TRUE.
Referenced by CmpInitializeHive(), and CmpLoadHiveThread().
Variable Documentation
BOOLEAN CmpNoWrite
Definition at line 330 of file cmdat.c.
KEVENT EndRegistryCommand
KEVENT StartRegistryCommand