Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmchek2.c File Reference
cmchek2.c File Reference
#include "cmp.h"
Functions
BOOLEAN CmpValidateHiveSecurityDescriptors (IN PHHIVE Hive, OUT PBOOLEAN ResetSD)
Variables
ULONG CmpUsedStorage
Function Documentation
BOOLEAN CmpValidateHiveSecurityDescriptors (IN PHHIVE Hive, OUT PBOOLEAN ResetSD)
Definition at line 28 of file cmchek2.c.
References ASSERT, _CM_KEY_SECURITY::Blink, CmDoSelfHeal, CmKdPrintEx, CML_SEC, CmMarkSelfHeal, CmpAddSecurityCellToCache(), CmpAdjustSecurityCacheSize(), CmpDestroySecurityCache(), CmpDumpSecurityDescriptor, CmpFindSecurityCellCacheIndex(), CmpInitSecurityCache(), _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_SECURITY::Flink, HvGetCell, HvIsCellAllocated(), HvMarkCellDirty(), Index, NT_SUCCESS, NULL, _CM_KEY_SECURITY::ReferenceCount, _CM_KEY_NODE::Security, SeValidSecurityDescriptor(), and TRUE.
Referenced by CmCheckRegistry().
Variable Documentation
ULONG CmpUsedStorage
Definition at line 119 of file cmdat2.c.