Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/acledit.c File Reference
acledit.c File Reference
#include <ntrtlp.h>
#include <seopaque.h>
Macros
#define FirstAce(Acl) ((PVOID)((PUCHAR)(Acl) + sizeof(ACL)))
#define LongAligned(ptr) (LongAlign(ptr) == ((PVOID)(ptr)))
#define NextAce(Ace) ((PVOID)((PUCHAR)(Ace) + ((PACE_HEADER)(Ace))->AceSize))
#define WordAligned(ptr) (WordAlign(ptr) == ((PVOID)(ptr)))
Functions
NTSTATUS RtlAddAccessAllowedAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ACCESS_MASK AccessMask, IN PSID Sid)
NTSTATUS RtlAddAccessAllowedAceEx (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid)
NTSTATUS RtlAddAccessAllowedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
NTSTATUS RtlAddAccessDeniedAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ACCESS_MASK AccessMask, IN PSID Sid)
NTSTATUS RtlAddAccessDeniedAceEx (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid)
NTSTATUS RtlAddAccessDeniedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
NTSTATUS RtlAddAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG StartingAceIndex, IN PVOID AceList, IN ULONG AceListLength)
NTSTATUS RtlAddAuditAccessAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ACCESS_MASK AccessMask, IN PSID Sid, IN BOOLEAN AuditSuccess, IN BOOLEAN AuditFailure)
NTSTATUS RtlAddAuditAccessAceEx (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid, IN BOOLEAN AuditSuccess, IN BOOLEAN AuditFailure)
NTSTATUS RtlAddAuditAccessObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid, IN BOOLEAN AuditSuccess, IN BOOLEAN AuditFailure)
NTSTATUS RtlAddCompoundAce (IN PACL Acl, IN ULONG AceRevision, IN UCHAR CompoundAceType, IN ACCESS_MASK AccessMask, IN PSID ServerSid, IN PSID ClientSid)
NTSTATUS RtlCreateAcl (IN PACL Acl, IN ULONG AclLength, IN ULONG AclRevision)
NTSTATUS RtlDeleteAce (IN OUT PACL Acl, IN ULONG AceIndex)
BOOLEAN RtlFirstFreeAce (IN PACL Acl, OUT PVOID *FirstFree)
NTSTATUS RtlGetAce (IN PACL Acl, ULONG AceIndex, OUT PVOID *Ace)
VOID RtlpAddData (IN PVOID From, IN ULONG FromSize, IN PVOID To, IN ULONG ToSize)
NTSTATUS RtlpAddKnownAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid, IN UCHAR NewType)
NTSTATUS RtlpAddKnownObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid, IN UCHAR NewType)
VOID RtlpDeleteData (IN PVOID Data, IN ULONG RemoveSize, IN ULONG TotalSize)
NTSTATUS RtlQueryInformationAcl (IN PACL Acl, OUT PVOID AclInformation, IN ULONG AclInformationLength, IN ACL_INFORMATION_CLASS AclInformationClass)
NTSTATUS RtlSetInformationAcl (IN PACL Acl, IN PVOID AclInformation, IN ULONG AclInformationLength, IN ACL_INFORMATION_CLASS AclInformationClass)
BOOLEAN RtlValidAcl (IN PACL Acl)
Macro Definition Documentation
#define FirstAce (Acl) ((PVOID)((PUCHAR)(Acl) + sizeof(ACL)))
Definition at line 36 of file acledit.c.
Referenced by RtlAddAce(), RtlDeleteAce(), RtlFirstFreeAce(), and RtlGetAce().
#define LongAligned (ptr) (LongAlign(ptr) == ((PVOID)(ptr)))
Definition at line 50 of file acledit.c.
Referenced by RtlValidAcl().
#define NextAce (Ace) ((PVOID)((PUCHAR)(Ace) + ((PACE_HEADER)(Ace))->AceSize))
Definition at line 48 of file acledit.c.
Referenced by RtlAddAce(), RtlDeleteAce(), RtlFirstFreeAce(), and RtlGetAce().
#define WordAligned (ptr) (WordAlign(ptr) == ((PVOID)(ptr)))
Definition at line 51 of file acledit.c.
Referenced by RtlValidAcl().
Function Documentation
NTSTATUS RtlAddAccessAllowedAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ACCESS_MASK AccessMask, IN PSID Sid)
Definition at line 1636 of file acledit.c.
References ACCESS_ALLOWED_ACE_TYPE, RTL_PAGED_CODE, and RtlpAddKnownAce().
NTSTATUS RtlAddAccessAllowedAceEx (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid)
Definition at line 1695 of file acledit.c.
References ACCESS_ALLOWED_ACE_TYPE, RTL_PAGED_CODE, and RtlpAddKnownAce().
NTSTATUS RtlAddAccessAllowedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
Definition at line 2037 of file acledit.c.
References ACCESS_ALLOWED_ACE_TYPE, ACCESS_ALLOWED_OBJECT_ACE_TYPE, NULL, RTL_PAGED_CODE, RtlpAddKnownAce(), and RtlpAddKnownObjectAce().
NTSTATUS RtlAddAccessDeniedAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ACCESS_MASK AccessMask, IN PSID Sid)
Definition at line 1756 of file acledit.c.
References ACCESS_DENIED_ACE_TYPE, RTL_PAGED_CODE, and RtlpAddKnownAce().
NTSTATUS RtlAddAccessDeniedAceEx (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid)
Definition at line 1816 of file acledit.c.
References ACCESS_DENIED_ACE_TYPE, RTL_PAGED_CODE, and RtlpAddKnownAce().
NTSTATUS RtlAddAccessDeniedObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid)
Definition at line 2124 of file acledit.c.
References ACCESS_DENIED_ACE_TYPE, ACCESS_DENIED_OBJECT_ACE_TYPE, NULL, RTL_PAGED_CODE, RtlpAddKnownAce(), and RtlpAddKnownObjectAce().
NTSTATUS RtlAddAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG StartingAceIndex, IN PVOID AceList, IN ULONG AceListLength)
Definition at line 747 of file acledit.c.
References ACCESS_MAX_MS_V2_ACE_TYPE, ACCESS_MAX_MS_V3_ACE_TYPE, ACCESS_MAX_MS_V4_ACE_TYPE, ACL_REVISION3, ACL_REVISION4, FirstAce, NextAce, NULL, RTL_PAGED_CODE, RtlFirstFreeAce(), RtlpAddData(), RtlValidAcl(), STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlAddAuditAccessAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ACCESS_MASK AccessMask, IN PSID Sid, IN BOOLEAN AuditSuccess, IN BOOLEAN AuditFailure)
Definition at line 1878 of file acledit.c.
References FAILED_ACCESS_ACE_FLAG, RTL_PAGED_CODE, RtlpAddKnownAce(), SUCCESSFUL_ACCESS_ACE_FLAG, and SYSTEM_AUDIT_ACE_TYPE.
NTSTATUS RtlAddAuditAccessAceEx (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid, IN BOOLEAN AuditSuccess, IN BOOLEAN AuditFailure)
Definition at line 1955 of file acledit.c.
References FAILED_ACCESS_ACE_FLAG, RTL_PAGED_CODE, RtlpAddKnownAce(), SUCCESSFUL_ACCESS_ACE_FLAG, and SYSTEM_AUDIT_ACE_TYPE.
NTSTATUS RtlAddAuditAccessObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid, IN BOOLEAN AuditSuccess, IN BOOLEAN AuditFailure)
Definition at line 2211 of file acledit.c.
References FAILED_ACCESS_ACE_FLAG, NULL, RTL_PAGED_CODE, RtlpAddKnownAce(), RtlpAddKnownObjectAce(), SUCCESSFUL_ACCESS_ACE_FLAG, SYSTEM_AUDIT_ACE_TYPE, and SYSTEM_AUDIT_OBJECT_ACE_TYPE.
NTSTATUS RtlAddCompoundAce (IN PACL Acl, IN ULONG AceRevision, IN UCHAR CompoundAceType, IN ACCESS_MASK AccessMask, IN PSID ServerSid, IN PSID ClientSid)
Definition at line 1127 of file acledit.c.
References ACCESS_ALLOWED_COMPOUND_ACE_TYPE, _ACE_HEADER::AceFlags, _ACE_HEADER::AceSize, _ACE_HEADER::AceType, ACL_REVISION3, ACL_REVISION4, _KNOWN_COMPOUND_ACE::CompoundAceType, _KNOWN_COMPOUND_ACE::Header, _KNOWN_COMPOUND_ACE::Mask, NULL, RTL_PAGED_CODE, RtlCopySid(), RtlFirstFreeAce(), RtlValidAcl(), RtlValidSid(), SeLengthSid, _KNOWN_COMPOUND_ACE::SidStart, STATUS_ALLOTTED_SPACE_EXCEEDED, STATUS_INVALID_ACL, STATUS_INVALID_SID, STATUS_REVISION_MISMATCH, and STATUS_SUCCESS.
NTSTATUS RtlCreateAcl (IN PACL Acl, IN ULONG AclLength, IN ULONG AclRevision)
Definition at line 116 of file acledit.c.
References MAX_ACL_REVISION, MAX_USTRING, RTL_PAGED_CODE, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
NTSTATUS RtlDeleteAce (IN OUT PACL Acl, IN ULONG AceIndex)
Definition at line 924 of file acledit.c.
References _ACE_HEADER::AceSize, FirstAce, NextAce, RTL_PAGED_CODE, RtlFirstFreeAce(), RtlpDeleteData(), RtlValidAcl(), STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
BOOLEAN RtlFirstFreeAce (IN PACL Acl, OUT PVOID * FirstFree)
Definition at line 2317 of file acledit.c.
References FALSE, FirstAce, NextAce, NULL, RTL_PAGED_CODE, and TRUE.
Referenced by RtlAddAce(), RtlAddCompoundAce(), RtlDeleteAce(), RtlpAddKnownAce(), RtlpAddKnownObjectAce(), and RtlQueryInformationAcl().
NTSTATUS RtlGetAce (IN PACL Acl, ULONG AceIndex, OUT PVOID * Ace)
Definition at line 1025 of file acledit.c.
References FirstAce, NextAce, RTL_PAGED_CODE, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and ValidAclRevision.
VOID RtlpAddData (IN PVOID From, IN ULONG FromSize, IN PVOID To, IN ULONG ToSize)
Definition at line 2402 of file acledit.c.
Referenced by RtlAddAce().
NTSTATUS RtlpAddKnownAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN PSID Sid, IN UCHAR NewType)
Definition at line 1271 of file acledit.c.
References _ACE_HEADER::AceFlags, _ACE_HEADER::AceSize, _ACE_HEADER::AceType, ACL_REVISION4, FAILED_ACCESS_ACE_FLAG, _KNOWN_ACE::Header, _KNOWN_ACE::Mask, NULL, RTL_PAGED_CODE, RtlCopySid(), RtlFirstFreeAce(), RtlValidAcl(), RtlValidSid(), SeLengthSid, _KNOWN_ACE::SidStart, STATUS_ALLOTTED_SPACE_EXCEEDED, STATUS_INVALID_ACL, STATUS_INVALID_PARAMETER, STATUS_INVALID_SID, STATUS_REVISION_MISMATCH, STATUS_SUCCESS, SUCCESSFUL_ACCESS_ACE_FLAG, SYSTEM_AUDIT_ACE_TYPE, and VALID_INHERIT_FLAGS.
Referenced by RtlAddAccessAllowedAce(), RtlAddAccessAllowedAceEx(), RtlAddAccessAllowedObjectAce(), RtlAddAccessDeniedAce(), RtlAddAccessDeniedAceEx(), RtlAddAccessDeniedObjectAce(), RtlAddAuditAccessAce(), RtlAddAuditAccessAceEx(), and RtlAddAuditAccessObjectAce().
NTSTATUS RtlpAddKnownObjectAce (IN OUT PACL Acl, IN ULONG AceRevision, IN ULONG AceFlags, IN ACCESS_MASK AccessMask, IN GUID *ObjectTypeGuid OPTIONAL, IN GUID *InheritedObjectTypeGuid OPTIONAL, IN PSID Sid, IN UCHAR NewType)
Definition at line 1434 of file acledit.c.
References ACE_INHERITED_OBJECT_TYPE_PRESENT, ACE_OBJECT_TYPE_PRESENT, _ACE_HEADER::AceFlags, _ACE_HEADER::AceSize, _ACE_HEADER::AceType, ACL_REVISION4, ARGUMENT_PRESENT, FAILED_ACCESS_ACE_FLAG, _KNOWN_OBJECT_ACE::Flags, _KNOWN_OBJECT_ACE::Header, _KNOWN_OBJECT_ACE::Mask, NULL, RTL_PAGED_CODE, RtlCopyMemory, RtlCopySid(), RtlFirstFreeAce(), RtlValidAcl(), RtlValidSid(), SeLengthSid, _KNOWN_OBJECT_ACE::SidStart, STATUS_ALLOTTED_SPACE_EXCEEDED, STATUS_INVALID_ACL, STATUS_INVALID_PARAMETER, STATUS_INVALID_SID, STATUS_REVISION_MISMATCH, STATUS_SUCCESS, SUCCESSFUL_ACCESS_ACE_FLAG, SYSTEM_AUDIT_ACE_TYPE, SYSTEM_AUDIT_OBJECT_ACE_TYPE, and VALID_INHERIT_FLAGS.
Referenced by RtlAddAccessAllowedObjectAce(), RtlAddAccessDeniedObjectAce(), and RtlAddAuditAccessObjectAce().
VOID RtlpDeleteData (IN PVOID Data, IN ULONG RemoveSize, IN ULONG TotalSize)
Definition at line 2482 of file acledit.c.
Referenced by RtlDeleteAce().
NTSTATUS RtlQueryInformationAcl (IN PACL Acl, OUT PVOID AclInformation, IN ULONG AclInformationLength, IN ACL_INFORMATION_CLASS AclInformationClass)
Definition at line 489 of file acledit.c.
References _ACL_SIZE_INFORMATION::AceCount, _ACL_SIZE_INFORMATION::AclBytesFree, _ACL_SIZE_INFORMATION::AclBytesInUse, _ACL_REVISION_INFORMATION::AclRevision, AclRevisionInformation, AclSizeInformation, NULL, RTL_PAGED_CODE, RtlFirstFreeAce(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and ValidAclRevision.
NTSTATUS RtlSetInformationAcl (IN PACL Acl, IN PVOID AclInformation, IN ULONG AclInformationLength, IN ACL_INFORMATION_CLASS AclInformationClass)
Definition at line 643 of file acledit.c.
References _ACL_REVISION_INFORMATION::AclRevision, AclRevisionInformation, RTL_PAGED_CODE, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, and ValidAclRevision.
BOOLEAN RtlValidAcl (IN PACL Acl)
Definition at line 204 of file acledit.c.
References _ACE_HEADER::AceSize, ACL_REVISION2, ACL_REVISION3, ACL_REVISION4, COMPOUND_ACE_IMPERSONATION, except, EXCEPTION_EXECUTE_HANDLER, FALSE, IsCompoundAceType, IsKnownAceType, IsObjectAceType, LongAligned, _SID::Revision, RTL_PAGED_CODE, RtlObjectAceInheritedObjectTypePresent, RtlObjectAceObjectTypePresent, RtlObjectAceSid, SeLengthSid, SID_MAX_SUB_AUTHORITIES, SID_REVISION, _SID::SubAuthorityCount, TRUE, ValidAclRevision, and WordAligned.
Referenced by RtlAddAce(), RtlAddCompoundAce(), RtlDeleteAce(), RtlpAddKnownAce(), and RtlpAddKnownObjectAce().