Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntregapi.h File Reference
ntregapi.h File Reference
Data Structures
struct _KEY_BASIC_INFORMATION
struct _KEY_CACHED_INFORMATION
struct _KEY_FLAGS_INFORMATION
struct _KEY_FULL_INFORMATION
struct _KEY_NAME_INFORMATION
struct _KEY_NODE_INFORMATION
struct _KEY_OPEN_SUBKEYS_INFORMATION
struct _KEY_USER_FLAGS_INFORMATION
struct _KEY_VALUE_BASIC_INFORMATION
struct _KEY_VALUE_ENTRY
struct _KEY_VALUE_FULL_INFORMATION
struct _KEY_VALUE_PARTIAL_INFORMATION
struct _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64
struct _KEY_WRITE_TIME_INFORMATION
struct _REG_NOTIFY_INFORMATION
struct KEY_PID_ARRAY
Macros
#define KEY_ALL_ACCESS
#define KEY_CREATE_LINK (0x0020)
#define KEY_CREATE_SUB_KEY (0x0004)
#define KEY_ENUMERATE_SUB_KEYS (0x0008)
#define KEY_EXECUTE
#define KEY_NOTIFY (0x0010)
#define KEY_QUERY_VALUE (0x0001)
#define KEY_READ
#define KEY_SET_VALUE (0x0002)
#define KEY_WOW64_32KEY (0x0200)
#define KEY_WOW64_64KEY (0x0100)
#define KEY_WOW64_RES (0x0300)
#define KEY_WRITE
#define REG_CREATED_NEW_KEY (0x00000001L)
#define REG_FORCE_RESTORE (0x00000008L)
#define REG_FORCE_UNLOAD 1
#define REG_INIT_BOOT_ACCEPTED_BASE (0x0002)
#define REG_INIT_BOOT_ACCEPTED_MAX REG_INIT_BOOT_ACCEPTED_BASE + 999
#define REG_INIT_BOOT_SETUP (0x0001)
#define REG_INIT_BOOT_SM (0x0000)
#define REG_INIT_MAX_VALID_CONDITION REG_INIT_BOOT_ACCEPTED_MAX
#define REG_LATEST_FORMAT 2
#define REG_LEGAL_CHANGE_FILTER
#define REG_LEGAL_OPTION
#define REG_MAX_KEY_NAME_LENGTH 512
#define REG_MAX_KEY_VALUE_NAME_LENGTH 32767
#define REG_NO_COMPRESSION 4
#define REG_NO_LAZY_FLUSH (0x00000004L)
#define REG_NOTIFY_CHANGE_ATTRIBUTES (0x00000002L)
#define REG_NOTIFY_CHANGE_LAST_SET (0x00000004L)
#define REG_NOTIFY_CHANGE_NAME (0x00000001L)
#define REG_NOTIFY_CHANGE_SECURITY (0x00000008L)
#define REG_OPENED_EXISTING_KEY (0x00000002L)
#define REG_OPTION_BACKUP_RESTORE (0x00000004L)
#define REG_OPTION_CREATE_LINK (0x00000002L)
#define REG_OPTION_NON_VOLATILE (0x00000000L)
#define REG_OPTION_OPEN_LINK (0x00000008L)
#define REG_OPTION_RESERVED (0x00000000L)
#define REG_OPTION_VOLATILE (0x00000001L)
#define REG_REFRESH_HIVE (0x00000002L)
#define REG_STANDARD_FORMAT 1
#define REG_WHOLE_HIVE_VOLATILE (0x00000001L)
Typedefs
typedef struct _KEY_BASIC_INFORMATION KEY_BASIC_INFORMATION
typedef struct _KEY_CACHED_INFORMATION KEY_CACHED_INFORMATION
typedef struct _KEY_FLAGS_INFORMATION KEY_FLAGS_INFORMATION
typedef struct _KEY_FULL_INFORMATION KEY_FULL_INFORMATION
typedef enum _KEY_INFORMATION_CLASS KEY_INFORMATION_CLASS
typedef struct _KEY_NAME_INFORMATION KEY_NAME_INFORMATION
typedef struct _KEY_NODE_INFORMATION KEY_NODE_INFORMATION
typedef struct _KEY_OPEN_SUBKEYS_INFORMATION KEY_OPEN_SUBKEYS_INFORMATION
typedef enum _KEY_SET_INFORMATION_CLASS KEY_SET_INFORMATION_CLASS
typedef struct _KEY_USER_FLAGS_INFORMATION KEY_USER_FLAGS_INFORMATION
typedef struct _KEY_VALUE_BASIC_INFORMATION KEY_VALUE_BASIC_INFORMATION
typedef struct _KEY_VALUE_ENTRY KEY_VALUE_ENTRY
typedef struct _KEY_VALUE_FULL_INFORMATION KEY_VALUE_FULL_INFORMATION
typedef enum _KEY_VALUE_INFORMATION_CLASS KEY_VALUE_INFORMATION_CLASS
typedef struct _KEY_VALUE_PARTIAL_INFORMATION KEY_VALUE_PARTIAL_INFORMATION
typedef struct _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64 KEY_VALUE_PARTIAL_INFORMATION_ALIGN64
typedef struct _KEY_WRITE_TIME_INFORMATION KEY_WRITE_TIME_INFORMATION
typedef struct _KEY_BASIC_INFORMATION * PKEY_BASIC_INFORMATION
typedef struct _KEY_CACHED_INFORMATION * PKEY_CACHED_INFORMATION
typedef struct _KEY_FLAGS_INFORMATION * PKEY_FLAGS_INFORMATION
typedef struct _KEY_FULL_INFORMATION * PKEY_FULL_INFORMATION
typedef struct _KEY_NAME_INFORMATION * PKEY_NAME_INFORMATION
typedef struct _KEY_NODE_INFORMATION * PKEY_NODE_INFORMATION
typedef struct _KEY_OPEN_SUBKEYS_INFORMATION * PKEY_OPEN_SUBKEYS_INFORMATION
typedef struct _KEY_USER_FLAGS_INFORMATION * PKEY_USER_FLAGS_INFORMATION
typedef struct _KEY_VALUE_BASIC_INFORMATION * PKEY_VALUE_BASIC_INFORMATION
typedef struct _KEY_VALUE_ENTRY * PKEY_VALUE_ENTRY
typedef struct _KEY_VALUE_FULL_INFORMATION * PKEY_VALUE_FULL_INFORMATION
typedef struct _KEY_VALUE_PARTIAL_INFORMATION * PKEY_VALUE_PARTIAL_INFORMATION
typedef struct _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64 * PKEY_VALUE_PARTIAL_INFORMATION_ALIGN64
typedef struct _KEY_WRITE_TIME_INFORMATION * PKEY_WRITE_TIME_INFORMATION
typedef struct _REG_NOTIFY_INFORMATION * PREG_NOTIFY_INFORMATION
typedef enum _REG_ACTION REG_ACTION
typedef struct _REG_NOTIFY_INFORMATION REG_NOTIFY_INFORMATION
Enumerations
enum _KEY_INFORMATION_CLASS {
KeyBasicInformation, KeyNodeInformation, KeyFullInformation, KeyNameInformation,
KeyCachedInformation, KeyFlagsInformation, MaxKeyInfoClass
}
enum _KEY_SET_INFORMATION_CLASS { KeyWriteTimeInformation, KeyUserFlagsInformation, MaxKeySetInfoClass }
enum _KEY_VALUE_INFORMATION_CLASS {
KeyValueBasicInformation, KeyValueFullInformation, KeyValuePartialInformation, KeyValueFullInformationAlign64,
KeyValuePartialInformationAlign64, MaxKeyValueInfoClass
}
enum _REG_ACTION { KeyAdded, KeyRemoved, KeyModified }
Functions
NTSYSCALLAPI NTSTATUS NTAPI NtCompactKeys (__in ULONG Count, __in_ecount(Count) HANDLE KeyArray[])
NTSYSCALLAPI NTSTATUS NTAPI NtCompressKey (__in HANDLE Key)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __reserved ULONG TitleIndex, __in_opt PUNICODE_STRING Class, __in ULONG CreateOptions, __out_opt PULONG Disposition)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteKey (__in HANDLE KeyHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateValueKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
NTSYSCALLAPI NTSTATUS NTAPI NtFlushKey (__in HANDLE KeyHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtInitializeRegistry (__in USHORT BootCondition)
NTSYSCALLAPI NTSTATUS NTAPI NtLoadKey (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile)
NTSYSCALLAPI NTSTATUS NTAPI NtLoadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags)
NTSYSCALLAPI NTSTATUS NTAPI NtLoadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags, __in_opt HANDLE TrustClassKey)
NTSYSCALLAPI NTSTATUS NTAPI NtLockProductActivationKeys (__inout_opt ULONG *pPrivateVer, __out_opt ULONG *pSafeMode)
NTSYSCALLAPI NTSTATUS NTAPI NtLockRegistryKey (__in HANDLE KeyHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtNotifyChangeKey (__in HANDLE KeyHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
NTSYSCALLAPI NTSTATUS NTAPI NtNotifyChangeMultipleKeys (__in HANDLE MasterKeyHandle, __in_opt ULONG Count, __in_ecount_opt(Count) OBJECT_ATTRIBUTES SlaveObjects[], __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryKey (__in HANDLE KeyHandle, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryMultipleValueKey (__in HANDLE KeyHandle, __inout_ecount(EntryCount) PKEY_VALUE_ENTRY ValueEntries, __in ULONG EntryCount, __out_bcount(*BufferLength) PVOID ValueBuffer, __inout PULONG BufferLength, __out_opt PULONG RequiredBufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryOpenSubKeys (__in POBJECT_ATTRIBUTES TargetKey, __out PULONG HandleCount)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryOpenSubKeysEx (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG BufferLength, __out_bcount(BufferLength) PVOID Buffer, __out PULONG RequiredSize)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
NTSYSCALLAPI NTSTATUS NTAPI NtRenameKey (__in HANDLE KeyHandle, __in PUNICODE_STRING NewName)
NTSYSCALLAPI NTSTATUS NTAPI NtReplaceKey (__in POBJECT_ATTRIBUTES NewFile, __in HANDLE TargetHandle, __in POBJECT_ATTRIBUTES OldFile)
NTSYSCALLAPI NTSTATUS NTAPI NtRestoreKey (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Flags)
NTSYSCALLAPI NTSTATUS NTAPI NtSaveKey (__in HANDLE KeyHandle, __in HANDLE FileHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSaveKeyEx (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Format)
NTSYSCALLAPI NTSTATUS NTAPI NtSaveMergedKeys (__in HANDLE HighPrecedenceKeyHandle, __in HANDLE LowPrecedenceKeyHandle, __in HANDLE FileHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationKey (__in HANDLE KeyHandle, __in KEY_SET_INFORMATION_CLASS KeySetInformationClass, __in_bcount(KeySetInformationLength) PVOID KeySetInformation, __in ULONG KeySetInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in_opt ULONG TitleIndex, __in ULONG Type, __in_bcount_opt(DataSize) PVOID Data, __in ULONG DataSize)
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadKey (__in POBJECT_ATTRIBUTES TargetKey)
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG Flags)
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in_opt HANDLE Event)
Macro Definition Documentation
#define KEY_ALL_ACCESS
Value:
((STANDARD_RIGHTS_ALL        |\
                                  KEY_QUERY_VALUE            |\
                                  KEY_SET_VALUE              |\
                                  KEY_CREATE_SUB_KEY         |\
                                  KEY_ENUMERATE_SUB_KEYS     |\
                                  KEY_NOTIFY                 |\
                                  KEY_CREATE_LINK)            \
                                  &                           \
                                 (~SYNCHRONIZE))
Definition at line 68 of file ntregapi.h.
Referenced by CmpCreateObjectTypes(), CmpHiveRootSecurityDescriptor(), CmpSetNetworkValue(), CmpSetSystemValues(), IopBootLog(), IopCopyBootLogRegistryToFile(), IopInitializeBuiltinDriver(), IopSafebootDriverLoad(), IopStoreSystemPartitionInformation(), IoSetSystemPartition(), IoWMISuggestInstanceName(), KeSetup80387OrEmulate(), and KiMoveRegTree().
#define KEY_CREATE_LINK (0x0020)
Definition at line 45 of file ntregapi.h.
Referenced by CmpCreateControlSet(), CmpDoCreate(), and CmpLinkKeyToHive().
#define KEY_CREATE_SUB_KEY (0x0004)
Definition at line 42 of file ntregapi.h.
Referenced by CmpCheckCreateAccess(), and CmRenameKey().
#define KEY_ENUMERATE_SUB_KEYS (0x0008)
Definition at line 43 of file ntregapi.h.
Referenced by ExpGetCurrentUserUILanguage(), ExpSetCurrentUserUILanguage(), NtEnumerateKey(), and NtSetDefaultLocale().
#define KEY_EXECUTE
Value:
((KEY_READ)                   \
                                  &                           \
                                 (~SYNCHRONIZE))
Definition at line 64 of file ntregapi.h.
Referenced by CmpCreateObjectTypes().
#define KEY_NOTIFY (0x0010)
Definition at line 44 of file ntregapi.h.
Referenced by CmpCheckNotifyAccess(), and NtNotifyChangeMultipleKeys().
#define KEY_QUERY_VALUE (0x0001)
Definition at line 40 of file ntregapi.h.
Referenced by CmGetSystemDriverList(), NtEnumerateValueKey(), NtQueryKey(), NtQueryMultipleValueKey(), NtQueryValueKey(), SepAdtInitializePrivilegeAuditing(), and SepRegQueryHelper().
#define KEY_READ
Value:
((STANDARD_RIGHTS_READ       |\
                                  KEY_QUERY_VALUE            |\
                                  KEY_ENUMERATE_SUB_KEYS     |\
                                  KEY_NOTIFY)                 \
                                  &                           \
                                 (~SYNCHRONIZE))
Definition at line 50 of file ntregapi.h.
Referenced by CmGetSystemDriverList(), CmInitSystem1(), CmLoadKey(), CmpAddAliasEntry(), CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreatePredefined(), CmpCreateRegistryRoot(), CmpDoCreate(), CmpDoOpen(), CmpHiveRootSecurityDescriptor(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpLinkHiveToMaster(), CmpRemoveFromHiveFileList(), CmpSaveBootControlSet(), CmShutdownSystem(), FsRtlGetCompatibilityModeValue(), FsRtlGetTunnelParameterValue(), FsRtlpIsDfsEnabled(), IoInitSystem(), IopLoadUnloadDriver(), IopUnloadDriver(), NtQueryOpenSubKeys(), and NtQueryOpenSubKeysEx().
#define KEY_SET_VALUE (0x0002)
Definition at line 41 of file ntregapi.h.
Referenced by NtDeleteValueKey(), NtSetInformationKey(), NtSetValueKey(), SepAdtInitializePrivilegeAuditing(), and SepAuditFailed().
#define KEY_WOW64_32KEY (0x0200)
Definition at line 46 of file ntregapi.h.
#define KEY_WOW64_64KEY (0x0100)
Definition at line 47 of file ntregapi.h.
#define KEY_WOW64_RES (0x0300)
Definition at line 48 of file ntregapi.h.
Referenced by NtCreateKey(), and NtOpenKey().
#define KEY_WRITE
Value:
((STANDARD_RIGHTS_WRITE      |\
                                  KEY_SET_VALUE              |\
                                  KEY_CREATE_SUB_KEY)         \
                                  &                           \
                                 (~SYNCHRONIZE))
Definition at line 58 of file ntregapi.h.
Referenced by CmGetSystemDriverList(), CmInitSystem1(), CmpAddAliasEntry(), CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreateObjectTypes(), CmpCreatePerfKeys(), CmpDoCreate(), CmpDoOpen(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpLinkHiveToMaster(), CmpRemoveFromHiveFileList(), CmpSaveBootControlSet(), NtCompactKeys(), NtCompressKey(), NtLockRegistryKey(), NtRenameKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define REG_CREATED_NEW_KEY (0x00000001L)
Definition at line 111 of file ntregapi.h.
Referenced by CmpCloneControlSet(), CmpCreateControlSet(), CmpDoCreate(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpLinkKeyToHive(), CmpParseKey(), and CmpSaveBootControlSet().
#define REG_FORCE_RESTORE (0x00000008L)
Definition at line 128 of file ntregapi.h.
Referenced by CmRestoreKey().
#define REG_FORCE_UNLOAD 1
Definition at line 133 of file ntregapi.h.
Referenced by CmUnloadKey(), and NtUnloadKey2().
#define REG_INIT_BOOT_ACCEPTED_BASE (0x0002)
Definition at line 167 of file ntregapi.h.
Referenced by NtInitializeRegistry().
#define REG_INIT_BOOT_ACCEPTED_MAX REG_INIT_BOOT_ACCEPTED_BASE + 999
Definition at line 168 of file ntregapi.h.
Referenced by NtInitializeRegistry().
#define REG_INIT_BOOT_SETUP (0x0001)
Definition at line 158 of file ntregapi.h.
Referenced by NtInitializeRegistry().
#define REG_INIT_BOOT_SM (0x0000)
Definition at line 157 of file ntregapi.h.
#define REG_INIT_MAX_VALID_CONDITION REG_INIT_BOOT_ACCEPTED_MAX
Definition at line 170 of file ntregapi.h.
Referenced by NtInitializeRegistry().
#define REG_LATEST_FORMAT 2
Definition at line 118 of file ntregapi.h.
Referenced by NtSaveKeyEx().
#define REG_LEGAL_CHANGE_FILTER
Value:
(REG_NOTIFY_CHANGE_NAME          |\
                 REG_NOTIFY_CHANGE_ATTRIBUTES    |\
                 REG_NOTIFY_CHANGE_LAST_SET      |\
                 REG_NOTIFY_CHANGE_SECURITY)
Definition at line 145 of file ntregapi.h.
Referenced by NtNotifyChangeMultipleKeys().
#define REG_LEGAL_OPTION
Value:
(REG_OPTION_RESERVED            |\
                 REG_OPTION_NON_VOLATILE        |\
                 REG_OPTION_VOLATILE            |\
                 REG_OPTION_CREATE_LINK         |\
                 REG_OPTION_BACKUP_RESTORE      |\
                 REG_OPTION_OPEN_LINK)
Definition at line 99 of file ntregapi.h.
Referenced by NtCreateKey().
#define REG_MAX_KEY_NAME_LENGTH 512
Definition at line 176 of file ntregapi.h.
Referenced by CmpCopySyncTree2(), CmpGetNextName(), CmpInitializeKeyNameString(), CmpNotifyChangeKey(), and NtRenameKey().
#define REG_MAX_KEY_VALUE_NAME_LENGTH 32767
Definition at line 175 of file ntregapi.h.
Referenced by CmpCopyKeyPartial(), CmpInitializeValueNameString(), CmpMergeKeyValues(), CmpSyncKeyValues(), and NtSetValueKey().
#define REG_NO_COMPRESSION 4
Definition at line 119 of file ntregapi.h.
Referenced by NtSaveKeyEx().
#define REG_NO_LAZY_FLUSH (0x00000004L)
Definition at line 127 of file ntregapi.h.
Referenced by CmLoadKey(), and NtLoadKeyEx().
#define REG_NOTIFY_CHANGE_ATTRIBUTES (0x00000002L)
Definition at line 141 of file ntregapi.h.
Referenced by CmpSecurityMethod().
#define REG_NOTIFY_CHANGE_LAST_SET (0x00000004L)
Definition at line 142 of file ntregapi.h.
Referenced by CmDeleteValueKey(), CmSetValueKey(), NtUnloadKey2(), and NtUnloadKeyEx().
#define REG_NOTIFY_CHANGE_NAME (0x00000001L)
Definition at line 140 of file ntregapi.h.
Referenced by CmDeleteKey(), CmpDoCreateChild(), CmpLinkHiveToMaster(), CmpReportNotify(), and CmRestoreKey().
#define REG_NOTIFY_CHANGE_SECURITY (0x00000008L)
Definition at line 143 of file ntregapi.h.
Referenced by CmpSecurityMethod().
#define REG_OPENED_EXISTING_KEY (0x00000002L)
Definition at line 112 of file ntregapi.h.
Referenced by CmpDoOpen().
#define REG_OPTION_BACKUP_RESTORE (0x00000004L)
Definition at line 93 of file ntregapi.h.
Referenced by CmpDoCreate(), CmpDoOpen(), NtUnloadKey2(), and NtUnloadKeyEx().
#define REG_OPTION_CREATE_LINK (0x00000002L)
Definition at line 90 of file ntregapi.h.
Referenced by CmpCreateControlSet(), CmpDoCreate(), CmpDoOpen(), and CmpLinkKeyToHive().
#define REG_OPTION_NON_VOLATILE (0x00000000L)
Definition at line 84 of file ntregapi.h.
Referenced by CmpSaveBootControlSet(), ExpUpdateComPlusPackage(), IopStoreSystemPartitionInformation(), and IoSetSystemPartition().
#define REG_OPTION_OPEN_LINK (0x00000008L)
Definition at line 97 of file ntregapi.h.
#define REG_OPTION_RESERVED (0x00000000L)
Definition at line 82 of file ntregapi.h.
#define REG_OPTION_VOLATILE (0x00000001L)
Definition at line 87 of file ntregapi.h.
Referenced by CmpAddToHiveFileList(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreatePredefined(), CmpDoCreate(), CmpDoCreateChild(), CmpLinkKeyToHive(), IopOpenRegistryKey(), KeSetup80387OrEmulate(), and KiMoveRegTree().
#define REG_REFRESH_HIVE (0x00000002L)
Definition at line 126 of file ntregapi.h.
Referenced by CmRestoreKey().
#define REG_STANDARD_FORMAT 1
Definition at line 117 of file ntregapi.h.
Referenced by NtSaveKeyEx().
#define REG_WHOLE_HIVE_VOLATILE (0x00000001L)
Definition at line 125 of file ntregapi.h.
Referenced by CmRestoreKey().
Typedef Documentation
typedef struct _KEY_BASIC_INFORMATION KEY_BASIC_INFORMATION
typedef struct _KEY_CACHED_INFORMATION KEY_CACHED_INFORMATION
typedef struct _KEY_FLAGS_INFORMATION KEY_FLAGS_INFORMATION
typedef struct _KEY_FULL_INFORMATION KEY_FULL_INFORMATION
typedef enum _KEY_INFORMATION_CLASS KEY_INFORMATION_CLASS
typedef struct _KEY_NAME_INFORMATION KEY_NAME_INFORMATION
typedef struct _KEY_NODE_INFORMATION KEY_NODE_INFORMATION
typedef struct _KEY_OPEN_SUBKEYS_INFORMATION KEY_OPEN_SUBKEYS_INFORMATION
typedef enum _KEY_SET_INFORMATION_CLASS KEY_SET_INFORMATION_CLASS
typedef struct _KEY_USER_FLAGS_INFORMATION KEY_USER_FLAGS_INFORMATION
typedef struct _KEY_VALUE_BASIC_INFORMATION KEY_VALUE_BASIC_INFORMATION
typedef struct _KEY_VALUE_ENTRY KEY_VALUE_ENTRY
typedef struct _KEY_VALUE_FULL_INFORMATION KEY_VALUE_FULL_INFORMATION
typedef enum _KEY_VALUE_INFORMATION_CLASS KEY_VALUE_INFORMATION_CLASS
typedef struct _KEY_VALUE_PARTIAL_INFORMATION KEY_VALUE_PARTIAL_INFORMATION
typedef struct _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64 KEY_VALUE_PARTIAL_INFORMATION_ALIGN64
typedef struct _KEY_WRITE_TIME_INFORMATION KEY_WRITE_TIME_INFORMATION
typedef struct _KEY_BASIC_INFORMATION * PKEY_BASIC_INFORMATION
typedef struct _KEY_CACHED_INFORMATION * PKEY_CACHED_INFORMATION
typedef struct _KEY_FLAGS_INFORMATION * PKEY_FLAGS_INFORMATION
typedef struct _KEY_FULL_INFORMATION * PKEY_FULL_INFORMATION
typedef struct _KEY_NAME_INFORMATION * PKEY_NAME_INFORMATION
typedef struct _KEY_NODE_INFORMATION * PKEY_NODE_INFORMATION
typedef struct _KEY_OPEN_SUBKEYS_INFORMATION * PKEY_OPEN_SUBKEYS_INFORMATION
typedef struct _KEY_USER_FLAGS_INFORMATION * PKEY_USER_FLAGS_INFORMATION
typedef struct _KEY_VALUE_BASIC_INFORMATION * PKEY_VALUE_BASIC_INFORMATION
typedef struct _KEY_VALUE_ENTRY * PKEY_VALUE_ENTRY
typedef struct _KEY_VALUE_FULL_INFORMATION * PKEY_VALUE_FULL_INFORMATION
typedef struct _KEY_VALUE_PARTIAL_INFORMATION * PKEY_VALUE_PARTIAL_INFORMATION
typedef struct _KEY_VALUE_PARTIAL_INFORMATION_ALIGN64 * PKEY_VALUE_PARTIAL_INFORMATION_ALIGN64
typedef struct _KEY_WRITE_TIME_INFORMATION * PKEY_WRITE_TIME_INFORMATION
typedef struct _REG_NOTIFY_INFORMATION * PREG_NOTIFY_INFORMATION
typedef enum _REG_ACTION REG_ACTION
typedef struct _REG_NOTIFY_INFORMATION REG_NOTIFY_INFORMATION
Enumeration Type Documentation
enum _KEY_INFORMATION_CLASS
Enumerator
KeyBasicInformation
KeyNodeInformation
KeyFullInformation
KeyNameInformation
KeyCachedInformation
KeyFlagsInformation
MaxKeyInfoClass
Definition at line 238 of file ntregapi.h.
enum _KEY_SET_INFORMATION_CLASS
Enumerator
KeyWriteTimeInformation
KeyUserFlagsInformation
MaxKeySetInfoClass
Definition at line 259 of file ntregapi.h.
enum _KEY_VALUE_INFORMATION_CLASS
Enumerator
KeyValueBasicInformation
KeyValueFullInformation
KeyValuePartialInformation
KeyValueFullInformationAlign64
KeyValuePartialInformationAlign64
MaxKeyValueInfoClass
Definition at line 306 of file ntregapi.h.
enum _REG_ACTION
Enumerator
KeyAdded
KeyRemoved
KeyModified
Definition at line 321 of file ntregapi.h.
Function Documentation
NTSYSCALLAPI NTSTATUS NTAPI NtCompactKeys (__in ULONG Count, __in_ecount(Count) HANDLE KeyArray[])
Definition at line 5248 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CM_VIEW_SIZE, CmKdPrintEx, CML_NTAPI, CML_NTAPI_ARGS, CmMoveKey(), CmpLockRegistryExclusive(), CmpUnlockRegistry(), CONTAINING_RECORD, Count, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, ExAllocatePool, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _CMHIVE::GrowOffset, _CMHIVE::GrowOnlyMode, HBLOCK_SIZE, Hive, KeGetPreviousMode, KEY_WRITE, _HHIVE::_DUAL::Length, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PagedPool, ProbeForRead, SeBackupPrivilege, SeSinglePrivilegeCheck(), Stable, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _HHIVE::Storage, TRUE, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtCompressKey (__in HANDLE Key)
Definition at line 5438 of file ntapi.c.
References _HHIVE::BaseBlock, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmCompressKey(), CmKdPrintEx, CML_NTAPI, CmpLockRegistryExclusive(), CmpUnlockRegistry(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, KeGetPreviousMode, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _HBASE_BLOCK::RootCell, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, and STATUS_PRIVILEGE_NOT_HELD.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes, __reserved ULONG TitleIndex, __in_opt PUNICODE_STRING Class, __in ULONG CreateOptions, __out_opt PULONG Disposition)
Definition at line 132 of file ntapi.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpAddKeyTracker, CmpExceptionFilter, _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, DbgPrintEx(), _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, EndWmiCmTrace, except, FALSE, Handle, HookKcbFromHandleForWmiCmTrace, HvShutdownComplete, INVALID_WRITE_OPERATION, KeGetPreviousMode, KernelMode, KEY_WOW64_RES, _UNICODE_STRING::Length, LongToHandle, NT_SUCCESS, NtClose(), NULL, ObDereferenceObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, PO_CLEAN_SHUTDOWN_REGISTRY, PoCleanShutdownEnabled(), _CM_PARSE_CONTEXT::PredefinedHandle, PROBE_ALIGNMENT, ProbeAndReadUnicodeStringEx, ProbeAndZeroHandle, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteUlong, PsGetCurrentProcessId(), PsGetCurrentProcessImageFileName, PsGetCurrentThreadId(), REG_LEGAL_OPTION, REG_OPTION_PREDEF_HANDLE, REGISTRY_ERROR, StartWmiCmTrace, STATUS_INVALID_PARAMETER, STATUS_PREDEFINED_HANDLE, STATUS_SUCCESS, STATUS_TOO_LATE, _CM_PARSE_CONTEXT::TitleIndex, TRUE, _CM_KEY_BODY::Type, UNREFERENCED_PARAMETER, and UserMode.
Referenced by CmInitSystem1(), CmpAddAliasEntry(), CmpCloneControlSet(), CmpCreateControlSet(), CmpInitializeHardwareConfiguration(), CmpInitializeRegistryNode(), CmpLinkKeyToHive(), CmpSaveBootControlSet(), and CmpSetNetworkValue().
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteKey (__in HANDLE KeyHandle)
Definition at line 392 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmDeleteKey(), CmIsKcbReadOnly, CmKdPrintEx, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DELETE, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, _OBJECT_HANDLE_INFORMATION::HandleAttributes, HookKcbForWmiCmTrace, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, _REG_DELETE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, _CM_KEY_CONTROL_BLOCK::ParentKcb, RegNtPostDeleteKey, RegNtPreDeleteKey, SeDeleteObjectAuditAlarm(), StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_SUCCESS, and TRUE.
Referenced by KiMoveRegTree().
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName)
Definition at line 499 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmDeleteValueKey(), CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, KeGetPreviousMode, KEY_SET_VALUE, _CM_KEY_BODY::KeyControlBlock, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_DELETE_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUnicodeStringEx, ProbeForRead, RegNtPostDeleteValueKey, RegNtPreDeleteValueKey, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, TRUE, UserMode, and _REG_DELETE_VALUE_KEY_INFORMATION::ValueName.
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 624 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmEnumerateKey(), CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, Index, _REG_ENUMERATE_KEY_INFORMATION::Index, KeGetPreviousMode, KEY_ENUMERATE_SUB_KEYS, KeyBasicInformation, _CM_KEY_BODY::KeyControlBlock, KeyFullInformation, _REG_ENUMERATE_KEY_INFORMATION::KeyInformation, _REG_ENUMERATE_KEY_INFORMATION::KeyInformationClass, KeyNodeInformation, _REG_ENUMERATE_KEY_INFORMATION::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_ENUMERATE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, RegNtPostEnumerateKey, RegNtPreEnumerateKey, _REG_ENUMERATE_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateValueKey (__in HANDLE KeyHandle, __in ULONG Index, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 786 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmEnumerateValueKey(), CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, Index, _REG_ENUMERATE_VALUE_KEY_INFORMATION::Index, KeGetPreviousMode, KEY_QUERY_VALUE, _CM_KEY_BODY::KeyControlBlock, KeyValueBasicInformation, KeyValueFullInformation, _REG_ENUMERATE_VALUE_KEY_INFORMATION::KeyValueInformation, _REG_ENUMERATE_VALUE_KEY_INFORMATION::KeyValueInformationClass, KeyValuePartialInformation, _REG_ENUMERATE_VALUE_KEY_INFORMATION::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_ENUMERATE_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, RegNtPostEnumerateValueKey, RegNtPreEnumerateValueKey, _REG_ENUMERATE_VALUE_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtFlushKey (__in HANDLE KeyHandle)
Definition at line 950 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmFlushKey(), CmKdPrintEx, CML_NTAPI, CmpLockKCBShared, CmpLockRegistry(), CmpUnlockKCB, CmpUnlockRegistry(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, FALSE, HookKcbForWmiCmTrace, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, StartWmiCmTrace, and STATUS_KEY_DELETED.
Referenced by CmpInterlockedFunction().
NTSYSCALLAPI NTSTATUS NTAPI NtInitializeRegistry (__in USHORT BootCondition)
Definition at line 1030 of file ntapi.c.
References CcPfBeginBootPhase(), CM_PAGED_CODE, CmBootAcceptFirstTime, CmFirstTime, CmKdPrintEx, CML_NTAPI, CmpCmdInit(), CmpHoldLazyFlush, CmpLazyFlush(), CmpLockRegistryExclusive(), CmpRaiseSelfHealWarningForSystemHives(), CmpSaveBootControlSet(), CmpSetVersionData(), CmpUnlockRegistry(), DPFLTR_CONFIG_ID, FALSE, HalEndOfBoot, IopCopyBootLogRegistryToFile(), KeGetPreviousMode, PfBootAcceptedRegistryInitPhase, PfSMRegistryInitPhase, PoInitHiberServices(), REG_INIT_BOOT_ACCEPTED_BASE, REG_INIT_BOOT_ACCEPTED_MAX, REG_INIT_BOOT_SETUP, REG_INIT_MAX_VALID_CONDITION, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, TRUE, UserMode, WmiBootPhase1(), and ZwInitializeRegistry().
NTSYSCALLAPI NTSTATUS NTAPI NtLoadKey (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile)
Definition at line 3159 of file ntapi.c.
References NtLoadKeyEx(), and NULL.
NTSYSCALLAPI NTSTATUS NTAPI NtLoadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags)
Definition at line 3207 of file ntapi.c.
References NtLoadKeyEx(), and NULL.
NTSYSCALLAPI NTSTATUS NTAPI NtLoadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in POBJECT_ATTRIBUTES SourceFile, __in ULONG Flags, __in_opt HANDLE TrustClassKey)
Definition at line 3260 of file ntapi.c.
References ALLOCATE_WITH_QUOTA, ARGUMENT_PRESENT, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmLoadKey(), CmpNameFromAttributes(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), KeEnterCriticalRegion(), KeGetPreviousMode, KeLeaveCriticalRegion(), _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _OBJECT_ATTRIBUTES::ObjectName, ObReferenceObjectByHandle, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForReadSmallStructure, REG_NO_LAZY_FLUSH, RtlCopyMemory, _OBJECT_ATTRIBUTES::SecurityDescriptor, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, and UserMode.
Referenced by NtLoadKey(), and NtLoadKey2().
NTSYSCALLAPI NTSTATUS NTAPI NtLockProductActivationKeys (__inout_opt ULONG * pPrivateVer, __out_opt ULONG * pSafeMode)
NTSYSCALLAPI NTSTATUS NTAPI NtLockRegistryKey (__in HANDLE KeyHandle)
Definition at line 5510 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmLockKcbForWrite(), CmpLockRegistry(), CmpUnlockRegistry(), END_LOCK_CHECKPOINT, KeGetPreviousMode, KernelMode, KEY_WRITE, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), and STATUS_PRIVILEGE_NOT_HELD.
NTSYSCALLAPI NTSTATUS NTAPI NtNotifyChangeKey (__in HANDLE KeyHandle, __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
Definition at line 1219 of file ntapi.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_NTAPI, DPFLTR_CONFIG_ID, NtNotifyChangeMultipleKeys(), and NULL.
NTSYSCALLAPI NTSTATUS NTAPI NtNotifyChangeMultipleKeys (__in HANDLE MasterKeyHandle, __in_opt ULONG Count, __in_ecount_opt(Count) OBJECT_ATTRIBUTES SlaveObjects[], __in_opt HANDLE Event, __in_opt PIO_APC_ROUTINE ApcRoutine, __in_opt PVOID ApcContext, __out PIO_STATUS_BLOCK IoStatusBlock, __in ULONG CompletionFilter, __in BOOLEAN WatchTree, __out_bcount_opt(BufferSize) PVOID Buffer, __in ULONG BufferSize, __in BOOLEAN Asynchronous)
Definition at line 1375 of file ntapi.c.
References _CM_ASYNC_USER_POST_BLOCK::Apc, APC_LEVEL, ARGUMENT_PRESENT, ASSERT, _CM_POST_BLOCK_UNION::AsyncKernel, _CM_POST_BLOCK_UNION::AsyncUser, _OBJECT_ATTRIBUTES::Attributes, BAD_NOTIFY_CONTEXT, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmLockHive, CmpAllocateMasterPostBlock, CmpAllocateSlavePostBlock, CmpDummyApc(), CmpExceptionFilter, CmpFreePostBlock(), CmpLockRegistry(), CmpLockTwoHashEntriesShared(), CmpNotifyChangeKey(), CmpPostApc(), CmpPostApcRunDown(), CmpRemoveEntryList, CmpSetIoStatus, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CmUnlockHive, _CM_KEY_CONTROL_BLOCK::ConvKey, CurrentApcEnvironment, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, _CM_ASYNC_KERNEL_POST_BLOCK::Event, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, Executive, FALSE, _LIST_ENTRY::Flink, HvShutdownComplete, _CM_ASYNC_USER_POST_BLOCK::IoStatusBlock, KeClearEvent(), KeGetCurrentThread(), KeGetPreviousMode, KeInitializeApc(), KeIsAttachedProcess(), KeLowerIrql, KeRaiseIrql, KernelMode, KeWaitForSingleObject(), KEY_NOTIFY, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, LOCK_POST_LIST, _CM_POST_BLOCK::NotifyList, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, PostAsyncKernel, PostAsyncUser, PostSynchronous, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWrite(), PsGetCurrentProcess(), _CM_ASYNC_KERNEL_POST_BLOCK::QueueType, REG_LEGAL_CHANGE_FILTER, REGISTRY_ERROR, _CM_SYNC_POST_BLOCK::Status, STATUS_ALERTED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PENDING, STATUS_SUCCESS, STATUS_TOO_LATE, STATUS_UNSUCCESSFUL, STATUS_USER_APC, _CM_POST_BLOCK_UNION::Sync, _CM_SYNC_POST_BLOCK::SystemEvent, _CM_POST_BLOCK::ThreadList, TRUE, _CM_POST_BLOCK::u, UNLOCK_POST_LIST, _CM_ASYNC_USER_POST_BLOCK::UserEvent, UserMode, _CM_ASYNC_KERNEL_POST_BLOCK::WorkItem, and ZwClose().
Referenced by NtNotifyChangeKey().
NTSYSCALLAPI NTSTATUS NTAPI NtOpenKey (__out PHANDLE KeyHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 2028 of file ntapi.c.
References _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpAddKeyTracker, CmpExceptionFilter, _CM_PARSE_CONTEXT::CreateOperation, DPFLTR_CONFIG_ID, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, FALSE, Handle, HookKcbFromHandleForWmiCmTrace, HvShutdownComplete, KeGetPreviousMode, KernelMode, KEY_WOW64_RES, _UNICODE_STRING::Length, LongToHandle, NT_SUCCESS, NtClose(), NULL, ObDereferenceObject(), ObOpenObjectByName(), ObReferenceObjectByHandle, PROBE_ALIGNMENT, ProbeAndReadUnicodeStringEx, ProbeAndZeroHandle, ProbeForRead, ProbeForReadSmallStructure, RtlZeroMemory, StartWmiCmTrace, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_PREDEFINED_HANDLE, STATUS_SUCCESS, STATUS_TOO_LATE, TRUE, _CM_KEY_BODY::Type, and UserMode.
Referenced by CmGetSystemDriverList(), CmpAddAliasEntry(), CmpCloneControlSet(), CmpCreateControlSet(), CmpCreatePerfKeys(), CmpInterlockedFunction(), CmpSaveBootControlSet(), CmpSetSystemValues(), and SepAdtInitializePrivilegeAuditing().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryKey (__in HANDLE KeyHandle, __in KEY_INFORMATION_CLASS KeyInformationClass, __out_bcount_opt(Length) PVOID KeyInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 2189 of file ntapi.c.
References CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CmpCallCallBacks(), CmpKeyInfoProbeAlingment(), CmPostCallbackNotification, CmQueryKey(), DPFLTR_CONFIG_ID, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, _OBJECT_HANDLE_INFORMATION::GrantedAccess, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, KeGetPreviousMode, KEY_QUERY_VALUE, KeyBasicInformation, KeyCachedInformation, _CM_KEY_BODY::KeyControlBlock, KeyFlagsInformation, KeyFullInformation, _REG_QUERY_KEY_INFORMATION::KeyInformation, _REG_QUERY_KEY_INFORMATION::KeyInformationClass, KeyNameInformation, KeyNodeInformation, _REG_QUERY_KEY_INFORMATION::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_QUERY_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, RegNtPostQueryKey, RegNtPreQueryKey, _REG_QUERY_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
Referenced by IopLoadDriver().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryMultipleValueKey (__in HANDLE KeyHandle, __inout_ecount(EntryCount) PKEY_VALUE_ENTRY ValueEntries, __in ULONG EntryCount, __out_bcount *BufferLength PVOID ValueBuffer, __inout PULONG BufferLength, __out_opt PULONG RequiredBufferLength)
Definition at line 4191 of file ntapi.c.
References ARGUMENT_PRESENT, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::BufferLength, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, CmQueryMultipleValueKey(), DPFLTR_CONFIG_ID, EndWmiCmTrace, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::EntryCount, except, EXCEPTION_EXECUTE_HANDLER, ExRaiseStatus(), HookKcbForWmiCmTrace, KeGetPreviousMode, KEY_QUERY_VALUE, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUlong, ProbeForWrite(), ProbeForWriteUlong, RegNtPostQueryMultipleValueKey, RegNtPreQueryMultipleValueKey, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::RequiredBufferLength, StartWmiCmTrace, Status, STATUS_INSUFFICIENT_RESOURCES, TRUE, UserMode, _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::ValueBuffer, and _REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION::ValueEntries.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryOpenSubKeys (__in POBJECT_ATTRIBUTES TargetKey, __out PULONG HandleCount)
Definition at line 4750 of file ntapi.c.
References _OBJECT_ATTRIBUTES::Attributes, _HHIVE::BaseBlock, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpLockRegistry(), CmpLockTwoHashEntriesExclusive(), CmpOpenSubKeys, CmpSearchForOpenSubKeys(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), _CM_KEY_CONTROL_BLOCK::ConvKey, DbgPrintEx(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _HBASE_BLOCK::FileName, Hive, KeGetPreviousMode, KernelMode, KEY_READ, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_KEY_CONTROL_BLOCK::ParentKcb, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWriteUlong, _HBASE_BLOCK::RootCell, RtlInitUnicodeString(), SearchAndCount, Status, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, UserMode, and ZwClose().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryOpenSubKeysEx (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG BufferLength, __out_bcount(BufferLength) PVOID Buffer, __out PULONG RequiredSize)
Definition at line 4905 of file ntapi.c.
References _OBJECT_ATTRIBUTES::Attributes, _HHIVE::BaseBlock, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, _QUERY_OPEN_SUBKEYS_CONTEXT::Buffer, _QUERY_OPEN_SUBKEYS_CONTEXT::BufferLength, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpLockRegistry(), CmpLockTwoHashEntriesExclusive(), CmpSearchForOpenSubKeys(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), _CM_KEY_CONTROL_BLOCK::ConvKey, _QUERY_OPEN_SUBKEYS_CONTEXT::CurrentNameBuffer, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FIELD_OFFSET, Hive, KeGetPreviousMode, KernelMode, KEY_READ, _QUERY_OPEN_SUBKEYS_CONTEXT::KeyBodyToIgnore, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_KEY_CONTROL_BLOCK::ParentKcb, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWrite(), ProbeForWriteUlong, _QUERY_OPEN_SUBKEYS_CONTEXT::RequiredSize, _HBASE_BLOCK::RootCell, SearchAndCount, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _QUERY_OPEN_SUBKEYS_CONTEXT::StatusCode, _QUERY_OPEN_SUBKEYS_CONTEXT::UsedLength, UserMode, and ZwClose().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, __out_bcount_opt(Length) PVOID KeyValueInformation, __in ULONG Length, __out PULONG ResultLength)
Definition at line 2370 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, CmQueryValueKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, KeGetPreviousMode, KEY_QUERY_VALUE, _CM_KEY_BODY::KeyControlBlock, KeyValueBasicInformation, KeyValueFullInformation, KeyValueFullInformationAlign64, _REG_QUERY_VALUE_KEY_INFORMATION::KeyValueInformation, _REG_QUERY_VALUE_KEY_INFORMATION::KeyValueInformationClass, KeyValuePartialInformation, KeyValuePartialInformationAlign64, _REG_QUERY_VALUE_KEY_INFORMATION::Length, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_QUERY_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForWriteUlong, RegNtPostQueryValueKey, RegNtPreQueryValueKey, _REG_QUERY_VALUE_KEY_INFORMATION::ResultLength, StartWmiCmTrace, STATUS_INVALID_PARAMETER, TRUE, UNICODE_NULL, UserMode, and _REG_QUERY_VALUE_KEY_INFORMATION::ValueName.
Referenced by CmpCreateControlSet(), CmpInterlockedFunction(), IoInitSystem(), IopLoadDriver(), and SepAdtInitializePrivilegeAuditing().
NTSYSCALLAPI NTSTATUS NTAPI NtRenameKey (__in HANDLE KeyHandle, __in PUNICODE_STRING NewName)
Definition at line 5084 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmpFlushNotifiesOnKeyBodyList(), CmpLockRegistryExclusive(), CmPostCallbackNotification, CmpUnlockRegistry(), CmRenameKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KEY_WRITE, _CM_KEY_BODY::KeyControlBlock, _UNICODE_STRING::Length, _REG_RENAME_KEY_INFORMATION::NewName, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_NAME_PATH_SEPARATOR, _REG_RENAME_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadUnicodeString, ProbeForRead, REG_MAX_KEY_NAME_LENGTH, RegNtPostRenameKey, RegNtPreRenameKey, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, TRUE, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtReplaceKey (__in POBJECT_ATTRIBUTES NewFile, __in HANDLE TargetHandle, __in POBJECT_ATTRIBUTES OldFile)
Definition at line 4068 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmIsKcbReadOnly, CmKdPrintEx, CML_NTAPI, CML_NTAPI_ARGS, CmpNameFromAttributes(), CmReplaceKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, ExFreePool(), KeEnterCriticalRegion(), KeGetPreviousMode, KeLeaveCriticalRegion(), _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, and STATUS_PRIVILEGE_NOT_HELD.
NTSYSCALLAPI NTSTATUS NTAPI NtRestoreKey (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Flags)
Definition at line 2555 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmIsKcbReadOnly, CmKdPrintEx, CML_NTAPI, CmRestoreKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeRestorePrivilege, SeSinglePrivilegeCheck(), STATUS_ACCESS_DENIED, STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwRestoreKey().
NTSYSCALLAPI NTSTATUS NTAPI NtSaveKey (__in HANDLE KeyHandle, __in HANDLE FileHandle)
Definition at line 2679 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmKdPrintEx, CML_NTAPI, CmSaveKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, HSYS_MINOR, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwSaveKey().
NTSYSCALLAPI NTSTATUS NTAPI NtSaveKeyEx (__in HANDLE KeyHandle, __in HANDLE FileHandle, __in ULONG Format)
Definition at line 2764 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmDumpKey(), CmKdPrintEx, CML_NTAPI, CmSaveKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, HSYS_MINOR, HSYS_WHISTLER, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, REG_LATEST_FORMAT, REG_NO_COMPRESSION, REG_STANDARD_FORMAT, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwSaveKeyEx().
NTSYSCALLAPI NTSTATUS NTAPI NtSaveMergedKeys (__in HANDLE HighPrecedenceKeyHandle, __in HANDLE LowPrecedenceKeyHandle, __in HANDLE FileHandle)
Definition at line 2871 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmKdPrintEx, CML_NTAPI, CmSaveMergedKeys(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, KeGetPreviousMode, _CM_KEY_BODY::KeyControlBlock, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, SeBackupPrivilege, SeSinglePrivilegeCheck(), STATUS_PRIVILEGE_NOT_HELD, UserMode, and ZwSaveMergedKeys().
NTSYSCALLAPI NTSTATUS NTAPI NtSetInformationKey (__in HANDLE KeyHandle, __in KEY_SET_INFORMATION_CLASS KeySetInformationClass, __in_bcount(KeySetInformationLength) PVOID KeySetInformation, __in ULONG KeySetInformationLength)
Definition at line 3894 of file ntapi.c.
References ASSERT, BEGIN_LOCK_CHECKPOINT, CM_PAGED_CODE, CmAreCallbacksRegistered, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmPostCallbackNotification, CmSetKeyUserFlags(), CmSetLastWriteTimeKey(), DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HookKcbForWmiCmTrace, HookKcbFromHandleForWmiCmTrace, KeGetPreviousMode, KEY_SET_VALUE, _CM_KEY_BODY::KeyControlBlock, _REG_SET_INFORMATION_KEY_INFORMATION::KeySetInformation, _REG_SET_INFORMATION_KEY_INFORMATION::KeySetInformationClass, _REG_SET_INFORMATION_KEY_INFORMATION::KeySetInformationLength, KeyUserFlagsInformation, KeyWriteTimeInformation, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_SET_INFORMATION_KEY_INFORMATION::Object, ObReferenceObjectByHandle, ProbeAndReadLargeInteger, ProbeAndReadUlong, RegNtPostSetInformationKey, RegNtPreSetInformationKey, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_UNSUCCESSFUL, TRUE, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtSetValueKey (__in HANDLE KeyHandle, __in PUNICODE_STRING ValueName, __in_opt ULONG TitleIndex, __in ULONG Type, __in_bcount_opt(DataSize) PVOID Data, __in ULONG DataSize)
Definition at line 2976 of file ntapi.c.
References BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmAreCallbacksRegistered, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpCallCallBacks(), CmpExceptionFilter, CmPostCallbackNotification, CmSetValueKey(), _REG_SET_VALUE_KEY_INFORMATION::Data, _REG_SET_VALUE_KEY_INFORMATION::DataSize, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EndWmiCmTrace, ExAllocatePoolWithQuotaTag, except, ExFreePool(), HookKcbForWmiCmTrace, KeGetPreviousMode, KEY_SET_VALUE, _CM_KEY_BODY::KeyControlBlock, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), _REG_SET_VALUE_KEY_INFORMATION::Object, ObReferenceObjectByHandle, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, REG_MAX_KEY_VALUE_NAME_LENGTH, RegNtPostSetValueKey, RegNtPreSetValueKey, RtlCopyMemory, StartWmiCmTrace, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, _REG_SET_VALUE_KEY_INFORMATION::TitleIndex, TRUE, _REG_SET_VALUE_KEY_INFORMATION::Type, UNICODE_NULL, UserMode, and _REG_SET_VALUE_KEY_INFORMATION::ValueName.
Referenced by CmpAddAliasEntry(), CmpAddDockingInfo(), CmpCreateControlSet(), CmpInitializeRegistryNode(), CmpInterlockedFunction(), CmpLinkKeyToHive(), CmpSetNetworkValue(), CmpSetSystemValues(), and IopStoreSystemPartitionInformation().
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadKey (__in POBJECT_ATTRIBUTES TargetKey)
Definition at line 3466 of file ntapi.c.
References NtUnloadKey2().
Referenced by CmpDeleteCloneTree().
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadKey2 (__in POBJECT_ATTRIBUTES TargetKey, __in ULONG Flags)
Definition at line 3504 of file ntapi.c.
References ASSERT, _OBJECT_ATTRIBUTES::Attributes, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CM_PAGED_CODE, CM_UNLOAD_KCB_LOCKED, CM_UNLOAD_REG_LOCKED_EX, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpFlushNotify(), CmpLockRegistry(), CmpLockRegistryExclusive(), CmpLockTwoHashEntriesExclusive(), CmpReportNotify(), CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), CmUnloadKey(), _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _CM_KEY_CONTROL_BLOCK::Delete, _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, IsHiveFrozen, KeGetPreviousMode, KernelMode, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, LOCK_HIVE_LOAD, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, _CM_KEY_CONTROL_BLOCK::ParentKcb, _CM_PARSE_CONTEXT::PredefinedHandle, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, REG_FORCE_UNLOAD, REG_NOTIFY_CHANGE_LAST_SET, REG_OPTION_BACKUP_RESTORE, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_CANNOT_DELETE, STATUS_KEY_DELETED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_TOO_LATE, _CM_PARSE_CONTEXT::TitleIndex, TRUE, UNLOCK_HIVE_LOAD, UserMode, and ZwClose().
Referenced by NtUnloadKey().
NTSYSCALLAPI NTSTATUS NTAPI NtUnloadKeyEx (__in POBJECT_ATTRIBUTES TargetKey, __in_opt HANDLE Event)
Definition at line 3710 of file ntapi.c.
References ARGUMENT_PRESENT, _OBJECT_ATTRIBUTES::Attributes, BEGIN_LOCK_CHECKPOINT, _UNICODE_STRING::Buffer, _CM_PARSE_CONTEXT::Class, CM_PAGED_CODE, CmIsKcbReadOnly, CmKdPrintEx, CML_EXCEPTION, CML_NTAPI, CML_NTAPI_ARGS, CmpFlushNotify(), CmpLockRegistryExclusive(), CmpReportNotify(), CmpUnlockRegistry(), CmUnloadKeyEx(), _CM_PARSE_CONTEXT::CreateLink, _CM_PARSE_CONTEXT::CreateOperation, _CM_PARSE_CONTEXT::CreateOptions, _CM_KEY_CONTROL_BLOCK::Delete, _CM_PARSE_CONTEXT::Disposition, DPFLTR_CONFIG_ID, END_LOCK_CHECKPOINT, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeClearEvent(), KeGetPreviousMode, KernelMode, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _UNICODE_STRING::Length, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_KERNEL_HANDLE, _OBJECT_ATTRIBUTES::ObjectName, ObOpenObjectByName(), ObReferenceObjectByHandle, _CM_PARSE_CONTEXT::OriginatingPoint, _CM_PARSE_CONTEXT::PredefinedHandle, ProbeAndReadStructure, ProbeAndReadUnicodeStringEx, ProbeForRead, REG_NOTIFY_CHANGE_LAST_SET, REG_OPTION_BACKUP_RESTORE, SeRestorePrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_DENIED, STATUS_KEY_DELETED, STATUS_PENDING, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _CM_PARSE_CONTEXT::TitleIndex, TRUE, UserMode, and ZwClose().