Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcconn.c File Reference
lpcconn.c File Reference
#include "lpcp.h"
Functions
PVOID LpcpFreeConMsg (IN PLPCP_MESSAGE *Msg, PLPCP_CONNECTION_MESSAGE *ConnectMsg, IN PETHREAD CurrentThread)
NTSYSAPI NTSTATUS NTAPI NtConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
NTSTATUS NtSecureConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __in_opt PSID RequiredServerSid, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
Function Documentation
PVOID LpcpFreeConMsg (IN PLPCP_MESSAGE * Msg, PLPCP_CONNECTION_MESSAGE * ConnectMsg, IN PETHREAD CurrentThread)
Definition at line 1171 of file lpcconn.c.
References _LPCP_MESSAGE::Entry, InitializeListHead(), IsListEmpty, LpcpAcquireLpcpLock, LpcpGetThreadMessage, LpcpReleaseLpcpLock, NULL, RemoveEntryList(), and _LPCP_CONNECTION_MESSAGE::SectionToMap.
Referenced by NtSecureConnectPort().
NTSYSAPI NTSTATUS NTAPI NtConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
Definition at line 42 of file lpcconn.c.
References NtSecureConnectPort(), and NULL.
Referenced by IopConnectLinkTrackingPort(), and IopErrorLogConnectPort().
NTSTATUS NtSecureConnectPort (__out PHANDLE PortHandle, __in PUNICODE_STRING PortName, __in PSECURITY_QUALITY_OF_SERVICE SecurityQos, __inout_opt PPORT_VIEW ClientView, __in_opt PSID RequiredServerSid, __inout_opt PREMOTE_PORT_VIEW ServerView, __out_opt PULONG MaxMessageLength, __inout_opt PVOID ConnectionInformation, __inout_opt PULONG ConnectionInformationLength)
Definition at line 83 of file lpcconn.c.
References ARGUMENT_PRESENT, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_CONNECTION_MESSAGE::ClientPort, _LPCP_PORT_OBJECT::ClientSectionBase, _LPCP_CONNECTION_MESSAGE::ClientView, _PORT_MESSAGE::ClientViewSize, _LPCP_PORT_OBJECT::ConnectedPort, _LPCP_PORT_OBJECT::ConnectionPort, _SECURITY_QUALITY_OF_SERVICE::ContextTrackingMode, _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), FALSE, FIELD_OFFSET, _LPCP_PORT_OBJECT::Flags, Handle, _LARGE_INTEGER::HighPart, InitializeListHead(), InsertTailList(), KeEnterCriticalRegionThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KeReadStateSemaphore(), KeReleaseSemaphore(), KernelMode, KeSetEvent(), KeWaitForSingleObject(), _PORT_VIEW::Length, _LARGE_INTEGER::LowPart, LPC_CONNECTION_REQUEST, _LPCP_PORT_OBJECT::LpcDataInfoChainHead, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeConMsg(), LpcpFreeToPortZone(), LpcpGenerateMessageId, LpcpInitializePortQueue(), LpcPortObjectType, LpcpReleaseLpcpLock, LpcpTrace, _ETHREAD::LpcReplyChain, _LPCP_PORT_OBJECT::LpcReplyChainHead, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MappingProcess, _LPCP_PORT_OBJECT::MaxConnectionInfoLength, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, MmMapViewOfSection(), MmSectionObjectType, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NtClose(), NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), ObReferenceObject, ObReferenceObjectByHandle, ObReferenceObjectByName(), PAGE_READWRITE, PAGED_CODE, PagedPool, PORT_ALL_ACCESS, PORT_CONNECT, PORT_DYNAMIC_SECURITY, PORT_NAME_DELETED, PORT_TYPE, PORT_WAITABLE, ProbeAndReadStructure, ProbeAndReadUlong, ProbeForWrite(), ProbeForWriteHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, PsDereferencePrimaryTokenEx, PsGetCurrentProcess(), PsGetCurrentThread(), PsReferencePrimaryToken(), _LPCP_PORT_QUEUE::ReceiveHead, _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, RtlCopyMemory, RtlEqualSid(), RtlZeroMemory, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, SeCaptureSid(), SeCreateClientSecurity(), SECTION_MAP_READ, SECTION_MAP_WRITE, _PORT_VIEW::SectionHandle, _PORT_VIEW::SectionOffset, _LPCP_CONNECTION_MESSAGE::SectionToMap, SECURITY_DYNAMIC_TRACKING, _LPCP_PORT_OBJECT::SecurityQos, _LPCP_PORT_QUEUE::Semaphore, SeQueryInformationToken(), SeReleaseSid(), SERVER_CONNECTION_PORT, _LPCP_PORT_OBJECT::ServerProcess, _LPCP_CONNECTION_MESSAGE::ServerView, _SID_AND_ATTRIBUTES::Sid, _LPCP_PORT_OBJECT::StaticSecurity, Status, STATUS_INVALID_PARAMETER, STATUS_INVALID_PORT_HANDLE, STATUS_NO_MEMORY, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_OBJECT_TYPE_MISMATCH, STATUS_PORT_CONNECTION_REFUSED, STATUS_SERVER_SID_MISMATCH, STATUS_SUCCESS, STATUS_USER_APC, _ETHREAD::Tcb, TokenUser, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _TOKEN_USER::User, _PORT_VIEW::ViewBase, _PORT_VIEW::ViewSize, ViewUnmap, _LPCP_PORT_OBJECT::WaitEvent, and WrExecutive.
Referenced by NtConnectPort().