Windows Research Kernel v1.2: C:/Windows Research Kernel/se/seaudit.c File Reference
seaudit.c File Reference
#include "pch.h"
Macros
#define INVALID_OBJECT_TYPE_LIST_INDEX 0xFFFFFFFF
Functions
NTSTATUS NtAccessCheckAndAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ACCESS_MASK DesiredAccess, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
NTSTATUS NtAccessCheckByTypeAndAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in ACCESS_MASK DesiredAccess, __in AUDIT_EVENT_TYPE AuditType, __in ULONG Flags, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
NTSTATUS NtAccessCheckByTypeResultListAndAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in ACCESS_MASK DesiredAccess, __in AUDIT_EVENT_TYPE AuditType, __in ULONG Flags, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out_ecount(ObjectTypeListLength) PACCESS_MASK GrantedAccess, __out_ecount(ObjectTypeListLength) PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
NTSTATUS NtAccessCheckByTypeResultListAndAuditAlarmByHandle (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in HANDLE ClientToken, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in ACCESS_MASK DesiredAccess, __in AUDIT_EVENT_TYPE AuditType, __in ULONG Flags, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out_ecount(ObjectTypeListLength) PACCESS_MASK GrantedAccess, __out_ecount(ObjectTypeListLength) PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
NTSTATUS NtCloseObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in BOOLEAN GenerateOnClose)
NTSTATUS NtDeleteObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in BOOLEAN GenerateOnClose)
NTSTATUS NtOpenObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in_opt PSECURITY_DESCRIPTOR SecurityDescriptor, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in ACCESS_MASK GrantedAccess, __in_opt PPRIVILEGE_SET Privileges, __in BOOLEAN ObjectCreation, __in BOOLEAN AccessGranted, __out PBOOLEAN GenerateOnClose)
NTSTATUS NtPrivilegedServiceAuditAlarm (__in PUNICODE_STRING SubsystemName, __in PUNICODE_STRING ServiceName, __in HANDLE ClientToken, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
NTSTATUS NtPrivilegeObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
VOID SeAuditHandleCreation (__in PACCESS_STATE AccessState, __in HANDLE Handle)
BOOLEAN SeAuditingFileEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
BOOLEAN SeAuditingFileEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
BOOLEAN SeAuditingFileOrGlobalEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
BOOLEAN SeAuditingHardLinkEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
BOOLEAN SeAuditingHardLinkEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
BOOLEAN SeCheckAuditPrivilege (__in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE PreviousMode)
VOID SeCloseObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle, __in BOOLEAN GenerateOnClose)
VOID SeDeleteObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle)
VOID SeObjectReferenceAuditAlarm (__in_opt PLUID OperationID, __in PVOID Object, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in_opt PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
VOID SeOpenObjectAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
VOID SeOpenObjectForDeleteAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
NTSTATUS SepAccessCheckAndAuditAlarm (IN PUNICODE_STRING SubsystemName, IN PVOID HandleId, IN PHANDLE ClientToken OPTIONAL, IN PUNICODE_STRING ObjectTypeName, IN PUNICODE_STRING ObjectName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN ACCESS_MASK DesiredAccess, IN AUDIT_EVENT_TYPE AuditType, IN ULONG Flags, IN POBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, OUT PACCESS_MASK GrantedAccess, OUT PNTSTATUS AccessStatus, OUT PBOOLEAN GenerateOnClose, IN BOOLEAN ReturnResultList)
VOID SepAuditTypeList (IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN PNTSTATUS AccessStatus, IN ULONG StartIndex, OUT PBOOLEAN GenerateSuccessAudit, OUT PBOOLEAN GenerateFailureAudit)
VOID SepExamineSacl (IN PACL Sacl, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, OUT PBOOLEAN GenerateAudit, OUT PBOOLEAN GenerateAlarm)
VOID SepExamineSaclEx (IN PACL Sacl, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN BOOLEAN ReturnResultList, IN PNTSTATUS AccessStatus, IN PACCESS_MASK GrantedAccess, IN PSID PrincipalSelfSid, OUT PBOOLEAN GenerateSuccessAudit, OUT PBOOLEAN GenerateFailureAudit)
BOOLEAN SepFilterPrivilegeAudits (IN ULONG Flags, IN PPRIVILEGE_SET PrivilegeSet)
VOID SepFreeCapturedString (IN PUNICODE_STRING CapturedString)
BOOLEAN SepInitializePrivilegeFilter (BOOLEAN Verbose)
VOID SepProbeAndCaptureString_U (IN PUNICODE_STRING SourceString, OUT PUNICODE_STRING *DestString)
VOID SePrivilegedServiceAuditAlarm (__in_opt PUNICODE_STRING ServiceName, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
VOID SePrivilegeObjectAuditAlarm (__in HANDLE Handle, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
VOID SepSetAuditInfoForObjectType (IN UCHAR AceFlags, IN ACCESS_MASK AccessMask, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN BOOLEAN ReturnResultList, IN ULONG ObjectTypeIndex, IN PNTSTATUS AccessStatus, IN PACCESS_MASK GrantedAccess, OUT PBOOLEAN GenerateSuccessAudit, OUT PBOOLEAN GenerateFailureAudit)
BOOLEAN SepSinglePrivilegeCheck (LUID DesiredPrivilege, IN PACCESS_TOKEN Token, IN KPROCESSOR_MODE PreviousMode)
Variables
PLUID const * SepFilterPrivileges = SepFilterPrivilegesShort
const PLUID SepFilterPrivilegesLong []
const PLUID SepFilterPrivilegesShort []
const PLUID SepServicesFilterPrivileges []
Macro Definition Documentation
#define INVALID_OBJECT_TYPE_LIST_INDEX 0xFFFFFFFF
Referenced by SepExamineSaclEx().
Function Documentation
NTSTATUS NtAccessCheckAndAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in ACCESS_MASK DesiredAccess, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
Definition at line 1794 of file seaudit.c.
References AuditEventObjectAccess, FALSE, NULL, PAGED_CODE, SepAccessCheckAndAuditAlarm(), and UNREFERENCED_PARAMETER.
NTSTATUS NtAccessCheckByTypeAndAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in ACCESS_MASK DesiredAccess, __in AUDIT_EVENT_TYPE AuditType, __in ULONG Flags, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out PACCESS_MASK GrantedAccess, __out PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
Definition at line 1855 of file seaudit.c.
References FALSE, NULL, PAGED_CODE, SepAccessCheckAndAuditAlarm(), and UNREFERENCED_PARAMETER.
NTSTATUS NtAccessCheckByTypeResultListAndAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in ACCESS_MASK DesiredAccess, __in AUDIT_EVENT_TYPE AuditType, __in ULONG Flags, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out_ecount(ObjectTypeListLength) PACCESS_MASK GrantedAccess, __out_ecount(ObjectTypeListLength) PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
Definition at line 1921 of file seaudit.c.
References NULL, PAGED_CODE, SepAccessCheckAndAuditAlarm(), TRUE, and UNREFERENCED_PARAMETER.
NTSTATUS NtAccessCheckByTypeResultListAndAuditAlarmByHandle (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in HANDLE ClientToken, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSID PrincipalSelfSid, __in ACCESS_MASK DesiredAccess, __in AUDIT_EVENT_TYPE AuditType, __in ULONG Flags, __in_ecount_opt(ObjectTypeListLength) POBJECT_TYPE_LIST ObjectTypeList, __in ULONG ObjectTypeListLength, __in PGENERIC_MAPPING GenericMapping, __in BOOLEAN ObjectCreation, __out_ecount(ObjectTypeListLength) PACCESS_MASK GrantedAccess, __out_ecount(ObjectTypeListLength) PNTSTATUS AccessStatus, __out PBOOLEAN GenerateOnClose)
Definition at line 1987 of file seaudit.c.
References PAGED_CODE, SepAccessCheckAndAuditAlarm(), TRUE, and UNREFERENCED_PARAMETER.
NTSTATUS NtCloseObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in BOOLEAN GenerateOnClose)
Definition at line 2468 of file seaudit.c.
References ASSERT, EffectiveToken, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlCopySid(), SeCaptureSubjectContext(), SeCheckAuditPrivilege(), SeLengthSid, SepAdtCloseObjectAuditAlarm(), SepFreeCapturedString(), SepProbeAndCaptureString_U(), SepTokenUserSid, SeReleaseSubjectContext(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PRIVILEGE_NOT_HELD, and STATUS_SUCCESS.
NTSTATUS NtDeleteObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in BOOLEAN GenerateOnClose)
Definition at line 2598 of file seaudit.c.
References ASSERT, EffectiveToken, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, PagedPool, RtlCopySid(), SeCaptureSubjectContext(), SeCheckAuditPrivilege(), SeLengthSid, SepAdtDeleteObjectAuditAlarm(), SepFreeCapturedString(), SepProbeAndCaptureString_U(), SepTokenUserSid, SeReleaseSubjectContext(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PRIVILEGE_NOT_HELD, and STATUS_SUCCESS.
NTSTATUS NtOpenObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in PUNICODE_STRING ObjectTypeName, __in PUNICODE_STRING ObjectName, __in_opt PSECURITY_DESCRIPTOR SecurityDescriptor, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in ACCESS_MASK GrantedAccess, __in_opt PPRIVILEGE_SET Privileges, __in BOOLEAN ObjectCreation, __in BOOLEAN AccessGranted, __out PBOOLEAN GenerateOnClose)
Definition at line 2054 of file seaudit.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, ASSERT, AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _TOKEN::ImpersonationLevel, IsValidPrivilegeCount, KeGetPreviousMode, KernelMode, leave, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, _PRIVILEGE_SET::PrivilegeCount, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteBoolean, PsGetCurrentProcess(), PsProcessAuditId, RtlCopyMemory, RtlpSaclAddrSecurityDescriptor, SeCaptureSecurityDescriptor(), SeCaptureSubjectContext(), SeCheckAuditPrivilege(), SecurityIdentification, SepAdtAuditThisEventWithContext(), SepAdtOpenObjectAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepExamineSacl(), SepFreeCapturedString(), SepProbeAndCaptureString_U(), SeReleaseSecurityDescriptor(), SeReleaseSubjectContext(), SeTokenObjectType, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TOKEN_QUERY, TokenImpersonation, _TOKEN::TokenType, TRUE, and UNREFERENCED_PARAMETER.
NTSTATUS NtPrivilegedServiceAuditAlarm (__in PUNICODE_STRING SubsystemName, __in PUNICODE_STRING ServiceName, __in HANDLE ClientToken, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
Definition at line 709 of file seaudit.c.
References ANYSIZE_ARRAY, ARGUMENT_PRESENT, ASSERT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _TOKEN::ImpersonationLevel, IsValidPrivilegeCount, KeGetPreviousMode, KernelMode, leave, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, _PRIVILEGE_SET::PrivilegeCount, ProbeForRead, ProbeForReadSmallStructure, RtlCopyMemory, SeCaptureSubjectContext(), SeCheckAuditPrivilege(), SecurityIdentification, SepAdtPrivilegedServiceAuditAlarm(), SepFreeCapturedString(), SepProbeAndCaptureString_U(), SeReleaseSubjectContext(), SeTokenObjectType, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TOKEN_QUERY, TokenImpersonation, and _TOKEN::TokenType.
NTSTATUS NtPrivilegeObjectAuditAlarm (__in PUNICODE_STRING SubsystemName, __in_opt PVOID HandleId, __in HANDLE ClientToken, __in ACCESS_MASK DesiredAccess, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
Definition at line 407 of file seaudit.c.
References ANYSIZE_ARRAY, ASSERT, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _TOKEN::ImpersonationLevel, IsValidPrivilegeCount, KeGetPreviousMode, KernelMode, leave, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, _PRIVILEGE_SET::PrivilegeCount, ProbeForRead, ProbeForReadSmallStructure, _SECURITY_SUBJECT_CONTEXT::ProcessAuditId, RtlCopyMemory, SeCaptureSubjectContext(), SeCheckAuditPrivilege(), SecurityIdentification, SepAdtPrivilegeObjectAuditAlarm(), SepFreeCapturedString(), SepProbeAndCaptureString_U(), SeReleaseSubjectContext(), SeTokenObjectType, Status, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, TOKEN_QUERY, TokenImpersonation, and _TOKEN::TokenType.
VOID SeAuditHandleCreation (__in PACCESS_STATE AccessState, __in HANDLE Handle)
Definition at line 3478 of file seaudit.c.
References ASSERT, AuditCategoryObjectAccess, DBG, FALSE, Handle, IsValidPrivilegeCount, NULL, PAGED_CODE, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, PsGetCurrentProcessId(), SepAdtOpenObjectAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SeSubsystemName, TRUE, and VOID.
Referenced by ObDuplicateObject(), and ObpCreateHandle().
BOOLEAN SeAuditingFileEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 4584 of file seaudit.c.
References AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, PAGED_CODE, SepAdtAuditThisEvent, and UNREFERENCED_PARAMETER.
BOOLEAN SeAuditingFileEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
Definition at line 4620 of file seaudit.c.
References AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, PAGED_CODE, SepAdtAuditThisEventWithContext(), and UNREFERENCED_PARAMETER.
BOOLEAN SeAuditingFileOrGlobalEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
Definition at line 4538 of file seaudit.c.
References AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, EffectiveToken, FALSE, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), and TRUE.
BOOLEAN SeAuditingHardLinkEvents (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 4662 of file seaudit.c.
References _ACL::AceCount, AuditCategoryObjectAccess, FALSE, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEvent, and TRUE.
BOOLEAN SeAuditingHardLinkEventsWithContext (__in BOOLEAN AccessGranted, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in_opt PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext)
Definition at line 4714 of file seaudit.c.
References _ACL::AceCount, AuditCategoryObjectAccess, FALSE, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), and TRUE.
BOOLEAN SeCheckAuditPrivilege (__in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in KPROCESSOR_MODE PreviousMode)
Definition at line 200 of file seaudit.c.
References _LUID_AND_ATTRIBUTES::Attributes, _PRIVILEGE_SET::Control, KernelMode, _LUID_AND_ATTRIBUTES::Luid, NULL, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, SeAuditPrivilege, SepPrivilegeCheck(), and SePrivilegedServiceAuditAlarm().
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), and SepAccessCheckAndAuditAlarm().
VOID SeCloseObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle, __in BOOLEAN GenerateOnClose)
Definition at line 3578 of file seaudit.c.
References EffectiveToken, PAGED_CODE, SeCaptureSubjectContext(), SepAdtCloseObjectAuditAlarm(), SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and UNREFERENCED_PARAMETER.
Referenced by ObpCloseHandleTableEntry().
VOID SeDeleteObjectAuditAlarm (__in PVOID Object, __in HANDLE Handle)
Definition at line 3642 of file seaudit.c.
References EffectiveToken, PAGED_CODE, SeCaptureSubjectContext(), SepAdtDeleteObjectAuditAlarm(), SepTokenUserSid, SeReleaseSubjectContext(), SeSubsystemName, Status, and UNREFERENCED_PARAMETER.
Referenced by NtDeleteKey(), and NtMakeTemporaryObject().
VOID SeObjectReferenceAuditAlarm (__in_opt PLUID OperationID, __in PVOID Object, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in_opt PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
Definition at line 3404 of file seaudit.c.
References AuditCategoryDetailedTracking, EffectiveToken, FALSE, KernelMode, NULL, PAGED_CODE, RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), SepAdtObjectReferenceAuditAlarm(), SepExamineSacl(), and UNREFERENCED_PARAMETER.
Referenced by ObpCheckObjectReference().
VOID SeOpenObjectAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
Definition at line 2734 of file seaudit.c.
References ARGUMENT_PRESENT, AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, _TOKEN::AuditData, _SECURITY_TOKEN_AUDIT_DATA::DenyMask, EffectiveToken, ExAllocatePool, ExFreePool(), FALSE, _AUX_ACCESS_DATA::GenericMapping, _SECURITY_TOKEN_AUDIT_DATA::GrantMask, KernelMode, _AUX_ACCESS_DATA::MaximumAuditMask, _UNICODE_STRING::MaximumLength, _OBJECT_NAME_INFORMATION::Name, NULL, PAGED_CODE, PagedPool, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, RtlCopyUnicodeString(), RtlMapGenericMask(), RtlpSaclAddrSecurityDescriptor, SeMaximumAuditMask(), SepAdtAuditThisEventWithContext(), SepAdtOpenObjectAuditAlarm(), SepExamineSacl(), SepFilterPrivilegeAudits(), SepQueryNameString(), SepQueryTypeString(), SeSubsystemName, TRUE, and UNREFERENCED_PARAMETER.
Referenced by IopParseDevice(), and ObCheckObjectAccess().
VOID SeOpenObjectForDeleteAuditAlarm (__in PUNICODE_STRING ObjectTypeName, __in_opt PVOID Object, __in_opt PUNICODE_STRING AbsoluteObjectName, __in PSECURITY_DESCRIPTOR SecurityDescriptor, __in PACCESS_STATE AccessState, __in BOOLEAN ObjectCreated, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode, __out PBOOLEAN GenerateOnClose)
Definition at line 3067 of file seaudit.c.
References ARGUMENT_PRESENT, AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, _TOKEN::AuditData, _SECURITY_TOKEN_AUDIT_DATA::DenyMask, EffectiveToken, ExAllocatePool, ExFreePool(), FALSE, _AUX_ACCESS_DATA::GenericMapping, _SECURITY_TOKEN_AUDIT_DATA::GrantMask, KernelMode, _UNICODE_STRING::MaximumLength, _OBJECT_NAME_INFORMATION::Name, NULL, PAGED_CODE, PagedPool, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, RtlCopyUnicodeString(), RtlMapGenericMask(), RtlpSaclAddrSecurityDescriptor, SepAdtAuditThisEventWithContext(), SepAdtOpenObjectAuditAlarm(), SepAdtOpenObjectForDeleteAuditAlarm(), SepExamineSacl(), SepFilterPrivilegeAudits(), SepQueryNameString(), SepQueryTypeString(), SeSubsystemName, TRUE, and UNREFERENCED_PARAMETER.
NTSTATUS SepAccessCheckAndAuditAlarm (IN PUNICODE_STRING SubsystemName, IN PVOID HandleId, IN PHANDLE ClientToken OPTIONAL, IN PUNICODE_STRING ObjectTypeName, IN PUNICODE_STRING ObjectName, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN PSID PrincipalSelfSid, IN ACCESS_MASK DesiredAccess, IN AUDIT_EVENT_TYPE AuditType, IN ULONG Flags, IN POBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN PGENERIC_MAPPING GenericMapping, OUT PACCESS_MASK GrantedAccess, OUT PNTSTATUS AccessStatus, OUT PBOOLEAN GenerateOnClose, IN BOOLEAN ReturnResultList)
Definition at line 1018 of file seaudit.c.
References ARGUMENT_PRESENT, ASSERT, AUDIT_ALLOW_NO_PRIVILEGE, AuditCategoryDirectoryServiceAccess, AuditCategoryObjectAccess, AuditCategoryPrivilegeUse, AuditEventDirectoryServiceAccess, AuditEventObjectAccess, _SECURITY_SUBJECT_CONTEXT::ClientToken, EffectiveToken, ExAllocateLocallyUniqueId(), ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, GENERIC_ALL, GENERIC_EXECUTE, GENERIC_READ, GENERIC_WRITE, _SECURITY_SUBJECT_CONTEXT::ImpersonationLevel, IsValidObjectTypeListCount, KeGetPreviousMode, KernelMode, leave, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PagedPool, _SECURITY_SUBJECT_CONTEXT::PrimaryToken, ProbeForReadSmallStructure, ProbeForWrite(), ProbeForWriteBoolean, ProbeForWriteUlong, PsGetCurrentProcess(), PsProcessAuditId, READ_CONTROL, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, SeCaptureObjectTypeList(), SeCaptureSecurityDescriptor(), SeCaptureSid(), SeCaptureSubjectContext(), SeCheckAuditPrivilege(), SecurityIdentification, SeFreeCapturedObjectTypeList(), SeLockSubjectContext(), SepAccessCheck(), SepAdtAuditThisEventWithContext(), SepAdtOpenObjectAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), SepExamineSaclEx(), SepFreeCapturedString(), SepProbeAndCaptureString_U(), SePrivilegePolicyCheck(), SepTokenIsOwner(), SeReleaseSecurityDescriptor(), SeReleaseSid(), SeReleaseSubjectContext(), SeTokenObjectType, SeUnlockSubjectContext(), Status, STATUS_ACCESS_DENIED, STATUS_BAD_IMPERSONATION_LEVEL, STATUS_GENERIC_NOT_MAPPED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_INVALID_SECURITY_DESCR, STATUS_NO_IMPERSONATION_TOKEN, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, TOKEN_QUERY, TRUE, VOID, and WRITE_DAC.
Referenced by NtAccessCheckAndAuditAlarm(), NtAccessCheckByTypeAndAuditAlarm(), NtAccessCheckByTypeResultListAndAuditAlarm(), and NtAccessCheckByTypeResultListAndAuditAlarmByHandle().
VOID SepAuditTypeList (IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN PNTSTATUS AccessStatus, IN ULONG StartIndex, OUT PBOOLEAN GenerateSuccessAudit, OUT PBOOLEAN GenerateFailureAudit)
Definition at line 3857 of file seaudit.c.
References Index, NT_SUCCESS, OBJECT_FAILURE_AUDIT, OBJECT_SUCCESS_AUDIT, PAGED_CODE, and TRUE.
Referenced by SepSetAuditInfoForObjectType().
VOID SepExamineSacl (IN PACL Sacl, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN BOOLEAN AccessGranted, OUT PBOOLEAN GenerateAudit, OUT PBOOLEAN GenerateAlarm)
Definition at line 3702 of file seaudit.c.
References FAILED_ACCESS_ACE_FLAG, FALSE, FirstAce, INHERIT_ONLY_ACE, MAXIMUM_ALLOWED, NextAce, NULL, PAGED_CODE, RtlEqualMemory, SeAnonymousLogonSid, SeLengthSid, SepSidInToken(), SeWorldSid, SUCCESSFUL_ACCESS_ACE_FLAG, SYSTEM_AUDIT_ACE_TYPE, and TRUE.
Referenced by NtOpenObjectAuditAlarm(), SeObjectReferenceAuditAlarm(), SeOpenObjectAuditAlarm(), and SeOpenObjectForDeleteAuditAlarm().
VOID SepExamineSaclEx (IN PACL Sacl, IN PACCESS_TOKEN Token, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList OPTIONAL, IN ULONG ObjectTypeListLength, IN BOOLEAN ReturnResultList, IN PNTSTATUS AccessStatus, IN PACCESS_MASK GrantedAccess, IN PSID PrincipalSelfSid, OUT PBOOLEAN GenerateSuccessAudit, OUT PBOOLEAN GenerateFailureAudit)
Definition at line 4049 of file seaudit.c.
References FAILED_ACCESS_ACE_FLAG, FALSE, FirstAce, Index, INHERIT_ONLY_ACE, INVALID_OBJECT_TYPE_LIST_INDEX, MAXIMUM_ALLOWED, NextAce, NT_SUCCESS, NULL, PAGED_CODE, RtlEqualMemory, RtlObjectAceObjectType, RtlObjectAceSid, SeAnonymousLogonSid, SeLengthSid, SepObjectInTypeList(), SepSetAuditInfoForObjectType(), SepSidInToken(), SeWorldSid, SUCCESSFUL_ACCESS_ACE_FLAG, SYSTEM_AUDIT_ACE_TYPE, SYSTEM_AUDIT_OBJECT_ACE_TYPE, and TRUE.
Referenced by SepAccessCheckAndAuditAlarm().
BOOLEAN SepFilterPrivilegeAudits (IN ULONG Flags, IN PPRIVILEGE_SET PrivilegeSet)
Definition at line 4453 of file seaudit.c.
References ARGUMENT_PRESENT, FALSE, NULL, PAGED_CODE, RtlEqualLuid, SEP_SERVICES_FILTER, SepFilterPrivileges, SepServicesFilterPrivileges, and TRUE.
Referenced by SeOpenObjectAuditAlarm(), SeOpenObjectForDeleteAuditAlarm(), SepAdtPrivilegedServiceAuditAlarm(), SepAdtPrivilegeObjectAuditAlarm(), and SePrivilegedServiceAuditAlarm().
VOID SepFreeCapturedString (IN PUNICODE_STRING CapturedString)
Definition at line 371 of file seaudit.c.
References ExFreePool(), and PAGED_CODE.
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), and SepAccessCheckAndAuditAlarm().
BOOLEAN SepInitializePrivilegeFilter (BOOLEAN Verbose)
Definition at line 4422 of file seaudit.c.
References SepFilterPrivilegesLong, SepFilterPrivilegesShort, and TRUE.
Referenced by SepAdtInitializePrivilegeAuditing().
VOID SepProbeAndCaptureString_U (IN PUNICODE_STRING SourceString, OUT PUNICODE_STRING * DestString)
Definition at line 260 of file seaudit.c.
References _UNICODE_STRING::Buffer, ExAllocatePoolWithTag, except, ExFreePool(), ExSystemExceptionFilter(), _UNICODE_STRING::Length, MAXUSHORT, NULL, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, and STATUS_SUCCESS.
Referenced by NtCloseObjectAuditAlarm(), NtDeleteObjectAuditAlarm(), NtOpenObjectAuditAlarm(), NtPrivilegedServiceAuditAlarm(), NtPrivilegeObjectAuditAlarm(), and SepAccessCheckAndAuditAlarm().
VOID SePrivilegedServiceAuditAlarm (__in_opt PUNICODE_STRING ServiceName, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted)
Definition at line 944 of file seaudit.c.
References ASSERT, EffectiveToken, IsValidPrivilegeCount, PAGED_CODE, RtlEqualSid(), SeExports, _SE_EXPORTS::SeLocalServiceSid, SeLocalSystemSid, _SE_EXPORTS::SeNetworkServiceSid, SEP_SERVICES_FILTER, SepAdtPrivilegedServiceAuditAlarm(), SepFilterPrivilegeAudits(), SepTokenUserSid, and SeSubsystemName.
Referenced by ObpIncrementHandleCount(), PspSinglePrivCheckAudit(), RtlpNewSecurityObject(), SeCheckAuditPrivilege(), and SeSinglePrivilegeCheck().
VOID SePrivilegeObjectAuditAlarm (__in HANDLE Handle, __in PSECURITY_SUBJECT_CONTEXT SubjectSecurityContext, __in ACCESS_MASK DesiredAccess, __in PPRIVILEGE_SET Privileges, __in BOOLEAN AccessGranted, __in KPROCESSOR_MODE AccessMode)
Definition at line 628 of file seaudit.c.
References KernelMode, PAGED_CODE, SepAdtPrivilegeObjectAuditAlarm(), and SeSubsystemName.
Referenced by ObpCreateHandle(), and SeCheckPrivilegedObject().
VOID SepSetAuditInfoForObjectType (IN UCHAR AceFlags, IN ACCESS_MASK AccessMask, IN ACCESS_MASK DesiredAccess, IN PIOBJECT_TYPE_LIST ObjectTypeList, IN ULONG ObjectTypeListLength, IN BOOLEAN ReturnResultList, IN ULONG ObjectTypeIndex, IN PNTSTATUS AccessStatus, IN PACCESS_MASK GrantedAccess, OUT PBOOLEAN GenerateSuccessAudit, OUT PBOOLEAN GenerateFailureAudit)
Definition at line 3945 of file seaudit.c.
References FAILED_ACCESS_ACE_FLAG, MAXIMUM_ALLOWED, NT_SUCCESS, OBJECT_FAILURE_AUDIT, OBJECT_SUCCESS_AUDIT, PAGED_CODE, SepAuditTypeList(), SUCCESSFUL_ACCESS_ACE_FLAG, and TRUE.
Referenced by SepExamineSaclEx().
BOOLEAN SepSinglePrivilegeCheck (LUID DesiredPrivilege, IN PACCESS_TOKEN Token, IN KPROCESSOR_MODE PreviousMode)
Definition at line 144 of file seaudit.c.
References ASSERT, _LUID_AND_ATTRIBUTES::Attributes, _LUID::HighPart, _LUID::LowPart, _LUID_AND_ATTRIBUTES::Luid, PAGED_CODE, PRIVILEGE_SET_ALL_NECESSARY, SepPrivilegeCheck(), and SeTcbPrivilege.
Referenced by SepAccessCheck(), and SePrivilegePolicyCheck().
Variable Documentation
PLUID const* SepFilterPrivileges = SepFilterPrivilegesShort
Definition at line 4419 of file seaudit.c.
Referenced by SepFilterPrivilegeAudits().
const PLUID SepFilterPrivilegesLong[]
Initial value:
=
    {
        &SeChangeNotifyPrivilege,
        &SeAuditPrivilege,
        &SeCreateTokenPrivilege,
        &SeAssignPrimaryTokenPrivilege,
        &SeBackupPrivilege,
        &SeRestorePrivilege,
        &SeDebugPrivilege,
        NULL
    }
Definition at line 4374 of file seaudit.c.
Referenced by SepInitializePrivilegeFilter().
const PLUID SepFilterPrivilegesShort[]
Initial value:
=
    {
        &SeChangeNotifyPrivilege,
        &SeAuditPrivilege,
        &SeCreateTokenPrivilege,
        &SeAssignPrimaryTokenPrivilege,
        &SeDebugPrivilege,
        NULL
    }
Definition at line 4397 of file seaudit.c.
Referenced by SepInitializePrivilegeFilter().
const PLUID SepServicesFilterPrivileges[]
Initial value:
=
    {
        &SeSystemtimePrivilege,
        NULL
    }
Definition at line 4413 of file seaudit.c.
Referenced by SepFilterPrivilegeAudits().