Windows Research Kernel v1.2: C:/Windows Research Kernel/lpc/lpcrecv.c File Reference
lpcrecv.c File Reference
#include "lpcp.h"
Functions
NTSTATUS NtReplyWaitReceivePort (__in HANDLE PortHandle, __out_opt PVOID *PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage)
NTSTATUS NtReplyWaitReceivePortEx (__in HANDLE PortHandle, __out_opt PVOID *PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage, __in_opt PLARGE_INTEGER Timeout)
Function Documentation
NTSTATUS NtReplyWaitReceivePort (__in HANDLE PortHandle, __out_opt PVOID * PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage)
Definition at line 28 of file lpcrecv.c.
References NtReplyWaitReceivePortEx(), NULL, and PAGED_CODE.
Referenced by NtListenPort().
NTSTATUS NtReplyWaitReceivePortEx (__in HANDLE PortHandle, __out_opt PVOID * PortContext, __in_opt PPORT_MESSAGE ReplyMessage, __out PPORT_MESSAGE ReceiveMessage, __in_opt PLARGE_INTEGER Timeout)
Definition at line 102 of file lpcrecv.c.
References ARGUMENT_PRESENT, _PORT_MESSAGE::CallbackId, _ETHREAD::Cid, CLIENT_COMMUNICATION_PORT, _PORT_MESSAGE::ClientId, _LPCP_PORT_OBJECT::ConnectionPort, DbgBreakPoint(), _LPCP_MESSAGE::Entry, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _LPCP_PORT_OBJECT::Flags, InitializeListHead(), IS_SYSTEM_THREAD, IsListEmpty, KdBreakPoint, KeGetPreviousMode, KeReleaseSemaphore(), KeResetEvent(), KernelMode, KeWaitForSingleObject(), LPC_CONNECTION_REQUEST, LPC_KERNELMODE_MESSAGE, LPC_REPLY, LPC_REQUEST, _ETHREAD::LpcExitThreadCalled, LPCP_MUTEX_OWNED, LPCP_MUTEX_RELEASE_ON_RETURN, LPCP_VALIDATE_REASON_REPLY, LpcpAcquireLpcpLockByThread, LpcpAllocateFromPortZone(), LpcpFreeDataInfoMessage(), LpcpFreeToPortZone(), LpcpGetThreadMessage, LpcpMoveMessage(), LpcpPrint, LpcpReferencePortObject, LpcpReleaseLpcpLock, LpcpSaveDataInfoMessage(), LpcpTrace, LpcpTraceError, LpcpValidateClientPort(), _ETHREAD::LpcReceivedMessageId, _ETHREAD::LpcReceivedMsgIdValid, _ETHREAD::LpcReplyChain, _ETHREAD::LpcReplyMessage, _ETHREAD::LpcReplyMessageId, _ETHREAD::LpcReplySemaphore, LpcWaitablePortObjectType, _LPCP_PORT_OBJECT::MaxMessageLength, _PORT_MESSAGE::MessageId, _LPCP_PORT_OBJECT::MsgQueue, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PORT_TYPE, PORT_WAITABLE, _LPCP_MESSAGE::PortContext, ProbeAndReadLargeInteger, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), ProbeForWriteUlong, PsGetCurrentProcess(), PsGetCurrentThread(), PsLookupProcessThreadByCid(), _LARGE_INTEGER::QuadPart, _LPCP_PORT_QUEUE::ReceiveHead, RemoveEntryList(), RemoveHeadList(), _LPCP_MESSAGE::RepliedToThread, _LPCP_MESSAGE::Request, RtlCopyMemory, _PORT_MESSAGE::s1, _PORT_MESSAGE::s2, _LPCP_PORT_QUEUE::Semaphore, Status, STATUS_INVALID_PARAMETER, STATUS_NO_MEMORY, STATUS_PORT_DISCONNECTED, STATUS_PORT_MESSAGE_TOO_LONG, STATUS_REPLY_MESSAGE_MISMATCH, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, THREAD_TO_PROCESS, TRUE, _PORT_MESSAGE::u1, _PORT_MESSAGE::u2, _CLIENT_ID::UniqueProcess, _CLIENT_ID::UniqueThread, UserMode, _LPCP_PORT_OBJECT::WaitEvent, and WrLpcReceive.
Referenced by NtReplyWaitReceivePort().