Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/apcuser.c File Reference
apcuser.c File Reference
#include "ki.h"
Functions
NTSTATUS KiContinueEx (IN PCONTEXT ContextRecord, IN BOOLEAN TestAlert, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
DECLSPEC_NOINLINE VOID KiContinuePreviousModeUser (IN PCONTEXT ContextRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
VOID KiInitializeUserApc (IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN PKNORMAL_ROUTINE NormalRoutine, IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Function Documentation
NTSTATUS KiContinueEx (IN PCONTEXT ContextRecord, IN BOOLEAN TestAlert, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
Definition at line 87 of file apcuser.c.
References APC_LEVEL, _KTHREAD::ApcState, CONTEXT_ALIGN, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeContextToKframes(), KeGetCurrentIrql(), KeGetCurrentThread(), KeLowerIrql, KernelMode, KeTestAlertThread(), KfRaiseIrql(), KiContinuePreviousModeUser(), KiDeliverApc(), leave, NULL, _KTHREAD::PreviousMode, ProbeForReadSmallStructure, ProbeForWriteSmallStructure(), Status, STATUS_SUCCESS, _KAPC_STATE::UserApcPending, and UserMode.
DECLSPEC_NOINLINE VOID KiContinuePreviousModeUser (IN PCONTEXT ContextRecord, IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame)
Definition at line 28 of file apcuser.c.
References _CONTEXT::ContextFlags, KeContextToKframes(), RtlCopyMemory, and UserMode.
Referenced by KiContinueEx().
VOID KiInitializeUserApc (IN PKEXCEPTION_FRAME ExceptionFrame, IN PKTRAP_FRAME TrapFrame, IN PKNORMAL_ROUTINE NormalRoutine, IN PVOID NormalContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
Definition at line 223 of file apcuser.c.
Referenced by KiDeliverApc(), and PspUserThreadStartup().