Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/thredini.c File Reference
thredini.c File Reference
#include "ki.h"
Functions
VOID KiInitializeContextThread (IN PKTHREAD Thread, IN PKSYSTEM_ROUTINE SystemRoutine, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext OPTIONAL, IN PCONTEXT ContextRecord OPTIONAL)
Function Documentation
VOID KiInitializeContextThread (IN PKTHREAD Thread, IN PKSYSTEM_ROUTINE SystemRoutine, IN PKSTART_ROUTINE StartRoutine OPTIONAL, IN PVOID StartContext OPTIONAL, IN PCONTEXT ContextRecord OPTIONAL)
Definition at line 23 of file thredini.c.
References APC_LEVEL, ARGUMENT_PRESENT, CONTEXT_CONTROL, CONTEXT_DEBUG_REGISTERS, CONTEXT_FLOATING_POINT, _CONTEXT::ContextFlags, KERNEL_STACK_SIZE, KernelMode, KiStartSystemThread(), KiStartUserThread(), KiStartUserThreadReturn(), KTRAP_FRAME_LENGTH, KxContextToKframes(), NULL, RPL_MASK, RtlZeroMemory, _KTRAP_FRAME::SegCs, and UserMode.
Referenced by KeInitThread().