Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/i386/init386.c File Reference
init386.c File Reference
#include "mi.h"
Data Structures
struct _MI_LARGE_VA_RANGES
Macros
#define MI_IS_PTE_VALID(PTE) ((PTE)->u.Hard.Valid == 1)
#define MI_LARGE_ALL 0x3
#define MI_LARGE_KERNEL_HAL 0x2
#define MI_LARGE_PFN_DATABASE_AND_NONPAGED_POOL 0x1
#define MI_MAX_LARGE_VA_RANGES 3
#define MM_LARGE_PAGE_MINIMUM ((255*1024*1024) >> PAGE_SHIFT)
#define MM_PFN_MAPPED_BY_PDE (MM_VA_MAPPED_BY_PDE >> PAGE_SHIFT)
Typedefs
typedef struct _MI_LARGE_VA_RANGES MI_LARGE_VA_RANGES
typedef struct _MI_LARGE_VA_RANGES * PMI_LARGE_VA_RANGES
Functions
PMEMORY_ALLOCATION_DESCRIPTOR MiFindDescriptor (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
VOID MiInitMachineDependent (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
LOGICAL MiIsRegularMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
VOID MiReportPhysicalMemory (VOID)
VOID MxConvertToLargePage (IN PVOID VirtualAddress, IN PVOID EndVirtualAddress)
PFN_NUMBER MxGetNextPage (IN PFN_NUMBER PagesNeeded, IN LOGICAL UseSlush)
PFN_NUMBER MxPagesAvailable (VOID)
Variables
ULONG MiLargeVaRangeIndex
MI_LARGE_VA_RANGES MiLargeVaRanges [MI_MAX_LARGE_VA_RANGES]
PFN_NUMBER MiSlushDescriptorBase
PFN_NUMBER MiSlushDescriptorCount
PVOID MmHyperSpaceEnd
ULONG MmLargeStackSize
ULONG MmLargeSystemCache
LOGICAL MmMakeLowMemory
LOGICAL MmPagedPoolMaximumDesired
PMEMORY_ALLOCATION_DESCRIPTOR MxFreeDescriptor
ULONG MxMapLargePages = MI_LARGE_ALL
MEMORY_ALLOCATION_DESCRIPTOR MxOldFreeDescriptor
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor1
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor2
ULONG MxPfnAllocation
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor1
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor2
Macro Definition Documentation
#define MI_IS_PTE_VALID (PTE) ((PTE)->u.Hard.Valid == 1)
Definition at line 759 of file init386.c.
Referenced by MiInitMachineDependent().
#define MI_LARGE_ALL 0x3
Definition at line 112 of file init386.c.
Referenced by MiInitMachineDependent().
#define MI_LARGE_KERNEL_HAL 0x2
Definition at line 110 of file init386.c.
Referenced by MiInitMachineDependent().
#define MI_LARGE_PFN_DATABASE_AND_NONPAGED_POOL 0x1
Definition at line 109 of file init386.c.
Referenced by MiInitMachineDependent().
#define MI_MAX_LARGE_VA_RANGES 3
Definition at line 116 of file init386.c.
#define MM_LARGE_PAGE_MINIMUM ((255*1024*1024) >> PAGE_SHIFT)
Definition at line 62 of file init386.c.
Referenced by MiInitMachineDependent().
#define MM_PFN_MAPPED_BY_PDE (MM_VA_MAPPED_BY_PDE >> PAGE_SHIFT)
Definition at line 121 of file init386.c.
Referenced by MiFindDescriptor(), MiInitMachineDependent(), MiReportPhysicalMemory(), and MxConvertToLargePage().
Typedef Documentation
typedef struct _MI_LARGE_VA_RANGES MI_LARGE_VA_RANGES
typedef struct _MI_LARGE_VA_RANGES * PMI_LARGE_VA_RANGES
Function Documentation
PMEMORY_ALLOCATION_DESCRIPTOR MiFindDescriptor (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
Definition at line 716 of file init386.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, CONTAINING_RECORD, _LIST_ENTRY::Flink, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderFirmwareTemporary, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MM_PFN_MAPPED_BY_PDE, NULL, and _MEMORY_ALLOCATION_DESCRIPTOR::PageCount.
Referenced by MiInitMachineDependent().
VOID MiInitMachineDependent (IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Definition at line 763 of file init386.c.
References _4gb, _x4gb, ActiveAndValid, ALTERNATE_BASE, ASSERT, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, _LIST_ENTRY::Blink, _MMCOLOR_TABLES::Blink, BYTE_OFFSET, BYTES_TO_PAGES, _MMPFNENTRY::CacheAttribute, CONTAINING_RECORD, _MMCOLOR_TABLES::Count, _KPROCESS::DirectoryTableBase, _KLDR_DATA_TABLE_ENTRY::DllBase, _MMPFN::e1, _MMPFN::e2, _MI_LARGE_VA_RANGES::EndVirtualAddress, ExpMultiUserTS, FALSE, FIRST_MAPPING_PTE, _LIST_ENTRY::Flink, _MMPFN::Flink, _MMCOLOR_TABLES::Flink, FreePageList, _MMPTE_HARDWARE::Global, HalQueryMaxHotPlugMemoryAddress, HalQuerySystemInformation, _MMPTE::Hard, HYPER_SPACE, InitializationPhase, InitializePool(), InitializeSListHead(), _MMPFN::InPageError, INSTALL_MORE_MEMORY, KeBugCheckEx(), KeFeatureBits, KeGetCurrentPrcb(), KeGetPcr(), KeNodeBlock, KeNumberNodes, KERNEL_LARGE_STACK_SIZE, KERNEL_STACK_SIZE, KernelVerifier, KeSweepDcache, KF_GLOBAL_PAGE, KF_LARGE_PAGE, KF_PAT, KSEG0_BASE, _MMPTE_HARDWARE::LargePage, LAST_MAPPING_PTE, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderBad, LoaderBBTMemory, LoaderFirmwarePermanent, LoaderFirmwareTemporary, LoaderFree, LoaderHALCachedMemory, LoaderLoadedProgram, LoaderOsloaderStack, LoaderSpecialMemory, LoaderXIPRom, LOCK_PFN, _MMPTE::Long, _MMSUPPORT::MaximumWorkingSetSize, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MI_64K_ALIGN, MI_ADD_EXECUTE_TO_VALID_PTE_IF_PAE, MI_DEFAULT_MAX_PAGES, MI_DTC_BOOTED_3GB_MAX_PAGES, MI_DTC_MAX_PAGES, MI_FLUSH_CURRENT_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PAGE_TABLE_ADDRESS, MI_IS_PTE_VALID, MI_LARGE_ALL, MI_LARGE_KERNEL_HAL, MI_LARGE_PFN_DATABASE_AND_NONPAGED_POOL, MI_MAKE_PDE_MAP_LARGE_PAGE, MI_PFN_ELEMENT, MI_PTE_LOOKUP_NEEDED, MI_ROUND_TO_SIZE, MI_WRITE_VALID_PTE, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiAddExpansionNonPagedPool(), MiAddExtraSystemPteRanges(), MiCached, MiComputeInitialLargePage(), MiDetermineNode, MiDetermineUserGlobalPteMask(), MiFindDescriptor(), MiFirstReservedZeroingPte, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPteOffset, MiGetPxeAddress, MiGetVirtualAddressMappedByPde, MiGetVirtualAddressMappedByPte, MiGetVirtualAddressMappedByPxe, MiIncrementSystemPtes(), MiInitializeNonPagedPool(), MiInitializeNonPagedPoolThresholds(), MiInitializeSystemPtes(), MiInitialLargePage, MiInitialLargePageSize, MiInsertPageInFreeList(), MiInsertPageInList(), MiIsPteOnPdeBoundary, MiIsPteOnPpeBoundary, MiIsRegularMemory(), MiIsVirtualAddressOnPdeBoundary, MiLargeVaRangeIndex, MiLastVadBit, MiMaximumSystemCacheSizeExtra, _MMSUPPORT::MinimumWorkingSetSize, MiNoLowMemory, MiRemoveAnyPage(), MiRequestedSystemPtes, MiReserveSystemPtes(), MiSlushDescriptorBase, MiSlushDescriptorCount, MiSystemCacheStartExtra, MiSystemViewStart, MiUseMaximumSystemSpace, MiUseMaximumSystemSpaceEnd, MiZeroMemoryPte, MM_CRASH_DUMP_VA, MM_DEBUG_VA, MM_EMPTY_LIST, MM_HIGHEST_VAD_ADDRESS, MM_KSEG0_BASE, MM_KSEG2_BASE, MM_LARGE_PAGE_MINIMUM, MM_LOWEST_NONPAGED_SYSTEM_START, MM_MAX_ADDITIONAL_NONPAGED_POOL, MM_MAX_INITIAL_NONPAGED_POOL, MM_MAX_PAGED_POOL, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_PAGED_POOL_START, MM_PFN_MAPPED_BY_PDE, MM_PTE_ACCESS_MASK, MM_PTE_GLOBAL_MASK, MM_READONLY, MM_READWRITE, MM_SECONDARY_COLORS_DEFAULT, MM_SECONDARY_COLORS_MAX, MM_SECONDARY_COLORS_MIN, MM_SESSION_SPACE_DEFAULT, MM_SHARED_USER_DATA_VA, MM_SYSTEM_CACHE_END_EXTRA, MM_SYSTEM_RANGE_START, MM_SYSTEM_SPACE_END, MM_SYSTEM_SPACE_START, MM_VA_MAPPED_BY_PDE, MM_WRITECOPY, MmBadPageListHead, MmBootImageSize, MmCrashDumpPte, MmCrashDumpVa, MmDebugPte, MmDebugVa, MmDefaultMaximumNonPagedPool, MmDynamicPfn, MmFirstReservedMappingPte, MmFreePagesByColor, MmHighestPhysicalPage, MmHighestPossiblePhysicalPage, MmHyperSpaceEnd, MmInitializeProcessAddressSpace(), MmIsAddressValid(), MmLargePageMinimum, MmLargeStackSize, MmLargeSystemCache, MmLastReservedMappingPte, MmLowestPhysicalPage, MmMakeLowMemory, MmMaxAdditionNonPagedPoolPerMb, MmMaximumNonPagedPoolInBytes, MmMaximumNonPagedPoolInPages, MmMaximumNonPagedPoolPercent, MmMinAdditionNonPagedPoolPerMb, MmMinimumNonPagedPoolSize, MmNonPagedPoolEnd, MmNonPagedPoolExpansionStart, MmNonPagedPoolStart, MmNonPagedSystemStart, MmNumberOfPhysicalPages, MmNumberOfSystemPtes, MmPaeMask, MmPagedPoolMaximumDesired, MmPfnDatabase, MmProtectFreedNonPagedPool, MmProtectToPteMask, MmPteGlobal, MmSecondaryColorMask, MmSecondaryColorNodeShift, MmSecondaryColors, MmSizeOfNonPagedPoolInBytes, MmSizeOfPagedPoolInBytes, MmSpecialPoolEnd, MmSpecialPoolStart, MmSpecialPoolTag, MmSubsectionBase, MmSystemCacheWorkingSetList, MmSystemProcessWorkingSetMax, MmSystemProcessWorkingSetMin, MmVerifyDriverBufferLength, MmVirtualBias, MmWorkingSetList, MxConvertToLargePage(), MxGetNextPage(), MxMapLargePages, MxPagesAvailable(), MxPfnAllocation, MxPopulatePageDirectories(), MxTotalFreePages, NonPagedPool, NT_SUCCESS, NULL, NUMBER_OF_MAPPING_PTES, NUMBER_OF_ZEROING_PTES, NumberOfBytes, _MMPTE_HARDWARE::Owner, _EPROCESS::PaeTop, PAGE_ALIGN, PAGE_DIRECTORY2_MASK, PAGE_DIRECTORY_MASK, PAGE_SHIFT, PAGE_SIZE, _MMPFNENTRY::PageColor, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _MMPTE_SOFTWARE::PageFileHigh, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _EPROCESS::Pcb, PD_PER_SYSTEM, PDE_BASE, PDE_PER_PAGE, PPE_PER_PAGE, PrototypePte, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), PTE_PER_PAGE, PTE_SHIFT, _MMPFN::PteAddress, _MMPFN::PteFrame, PXE_PER_PAGE, _LARGE_INTEGER::QuadPart, _MMPFNENTRY::Rom, RtlCompareMemoryUlong(), RtlCopyMemory, RtlZeroMemory, _KPRCB::SecondaryColorMask, _KPCR::SecondLevelCacheAssociativity, _KPCR::SecondLevelCacheSize, _MMPFN::ShareCount, _KLDR_DATA_TABLE_ENTRY::SizeOfImage, _MMPTE::Soft, strstr(), SystemPteSpace, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, VAD_BITMAP_SPACE, _MMPTE_HARDWARE::Valid, ValidKernelPde, ValidKernelPdeLocal, ValidKernelPte, ValidKernelPteLocal, ValidUserPte, _MI_LARGE_VA_RANGES::VirtualAddress, _EPROCESS::Vm, _EPROCESS::WorkingSetPage, X64K, and ZeroedPageList.
LOGICAL MiIsRegularMemory (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PFN_NUMBER PageFrameIndex)
Definition at line 608 of file init386.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, CONTAINING_RECORD, FALSE, _LIST_ENTRY::Flink, _MEMORY_ALLOCATION_DESCRIPTOR::ListEntry, LoaderBBTMemory, LoaderFirmwarePermanent, LoaderSpecialMemory, _MEMORY_ALLOCATION_DESCRIPTOR::MemoryType, MiSlushDescriptorBase, MiSlushDescriptorCount, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, and TRUE.
Referenced by MiInitMachineDependent().
VOID MiReportPhysicalMemory (VOID)
Definition at line 390 of file init386.c.
References ASSERT, _PHYSICAL_MEMORY_RUN::BasePage, DbgPrintEx(), DPFLTR_MM_ID, DPFLTR_WARNING_LEVEL, FALSE, _MMPTE::Hard, MI_GET_PAGE_FRAME_FROM_PTE, MiAddCachedRange(), MiGetPteAddress, MiLargeVaRangeIndex, MiRemoveCachedRange(), MM_PFN_MAPPED_BY_PDE, MmPhysicalMemoryBlock, MxMapLargePages, NULL, _PHYSICAL_MEMORY_DESCRIPTOR::NumberOfRuns, _PHYSICAL_MEMORY_RUN::PageCount, _PHYSICAL_MEMORY_DESCRIPTOR::Run, TRUE, _MMPTE::u, _MMPTE_HARDWARE::Valid, and _MI_LARGE_VA_RANGES::VirtualAddress.
VOID MxConvertToLargePage (IN PVOID VirtualAddress, IN PVOID EndVirtualAddress)
Definition at line 236 of file init386.c.
References ASSERT, _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, _MMPFN::e1, _MMPFN::e2, FALSE, _MMPTE::Hard, _MMPTE_HARDWARE::LargePage, LOCK_PFN, _MMPTE::Long, MI_FLUSH_ENTIRE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT, MI_SET_GLOBAL_STATE, MI_SET_PFN_DELETED, MI_WRITE_VALID_PTE_NEW_PAGE, MiAddExpansionNonPagedPool(), MiDecrementReferenceCount(), MiGetPdeAddress, MiGetVirtualAddressMappedByPte, MM_PFN_MAPPED_BY_PDE, MmSystemPagePtes, MmVirtualBias, MxMapLargePages, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PD_PER_SYSTEM, PDE_PER_PAGE, PTE_PER_PAGE, _MMPFN::ShareCount, StandbyPageList, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and ValidKernelPde.
Referenced by MiInitMachineDependent().
PFN_NUMBER MxGetNextPage (IN PFN_NUMBER PagesNeeded, IN LOGICAL UseSlush)
Definition at line 125 of file init386.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::BasePage, INSTALL_MORE_MEMORY, KeBugCheckEx(), MmNumberOfPhysicalPages, NULL, _MEMORY_ALLOCATION_DESCRIPTOR::PageCount, and TRUE.
Referenced by MiInitMachineDependent().
PFN_NUMBER MxPagesAvailable (VOID)
Definition at line 206 of file init386.c.
References _MEMORY_ALLOCATION_DESCRIPTOR::PageCount.
Referenced by MiInitMachineDependent().
Variable Documentation
ULONG MiLargeVaRangeIndex
Definition at line 118 of file init386.c.
Referenced by MiInitMachineDependent(), and MiReportPhysicalMemory().
MI_LARGE_VA_RANGES MiLargeVaRanges[MI_MAX_LARGE_VA_RANGES]
Definition at line 119 of file init386.c.
PFN_NUMBER MiSlushDescriptorBase
Definition at line 85 of file init386.c.
Referenced by MiInitMachineDependent(), and MiIsRegularMemory().
PFN_NUMBER MiSlushDescriptorCount
Definition at line 86 of file init386.c.
Referenced by MiInitMachineDependent(), and MiIsRegularMemory().
PVOID MmHyperSpaceEnd
Definition at line 69 of file init386.c.
Referenced by MiInitializeWorkingSetList(), MiInitMachineDependent(), and MmCreateProcessAddressSpace().
ULONG MmLargeStackSize
Definition at line 41 of file procsup.c.
Referenced by MiInitMachineDependent().
ULONG MmLargeSystemCache
Definition at line 222 of file mminit.c.
Referenced by MiInitMachineDependent().
LOGICAL MmMakeLowMemory
Definition at line 35 of file sysload.c.
Referenced by MiInitMachineDependent().
LOGICAL MmPagedPoolMaximumDesired
Definition at line 53 of file mminit.c.
Referenced by MiBuildPagedPool(), MiInitMachineDependent(), and MmInitSystem().
PMEMORY_ALLOCATION_DESCRIPTOR MxFreeDescriptor
Definition at line 81 of file init386.c.
ULONG MxMapLargePages = MI_LARGE_ALL
Definition at line 114 of file init386.c.
Referenced by MiInitMachineDependent(), MiReportPhysicalMemory(), and MxConvertToLargePage().
MEMORY_ALLOCATION_DESCRIPTOR MxOldFreeDescriptor
Definition at line 92 of file init386.c.
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor1
Definition at line 93 of file init386.c.
MEMORY_ALLOCATION_DESCRIPTOR MxOldSlushDescriptor2
Definition at line 94 of file init386.c.
ULONG MxPfnAllocation
Definition at line 79 of file init386.c.
Referenced by MiInitMachineDependent().
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor1
Definition at line 82 of file init386.c.
PMEMORY_ALLOCATION_DESCRIPTOR MxSlushDescriptor2
Definition at line 83 of file init386.c.