Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmse.c File Reference
cmse.c File Reference
#include "cmp.h"
Macros
#define SECURITY_CELL_LENGTH(pDescriptor)
Functions
NTSTATUS CmpAssignSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PCM_KEY_NODE Node, IN PSECURITY_DESCRIPTOR SecurityDescriptor)
NTSTATUS CmpAssignSecurityDescriptorWrapper (IN PVOID Object, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor)
BOOLEAN CmpCheckCreateAccess (IN PUNICODE_STRING RelativeName, IN PSECURITY_DESCRIPTOR Descriptor, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK AdditionalAccess, OUT PNTSTATUS AccessStatus)
NTSTATUS CmpCheckKeyAccess (IN PHHIVE Hive, IN HCELL_INDEX NodeCell, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK DesiredAccess)
BOOLEAN CmpCheckNotifyAccess (IN PCM_NOTIFY_BLOCK NotifyBlock, IN PHHIVE Hive, IN PCM_KEY_NODE Node)
NTSTATUS CmpDoAccessCheckOnSubtree (PHHIVE HiveToCheck, HCELL_INDEX Cell, KPROCESSOR_MODE PreviousMode, ACCESS_MASK DesiredAccess, BOOLEAN CheckRoot)
BOOLEAN CmpFindMatchingDescriptorCell (IN PCMHIVE CmHive, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ULONG Type, OUT PHCELL_INDEX MatchingCell, OUT OPTIONAL PCM_KEY_SECURITY_CACHE *CachedSecurityPointer)
VOID CmpFreeSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell)
PCM_KEY_SECURITY CmpGetKeySecurity (IN PHHIVE Hive, IN PCM_KEY_NODE Key, OUT PHCELL_INDEX SecurityCell)
PSECURITY_DESCRIPTOR CmpHiveRootSecurityDescriptor (VOID)
BOOLEAN CmpInsertSecurityCellList (IN PHHIVE Hive, IN HCELL_INDEX NodeCell, IN HCELL_INDEX SecurityCell)
NTSTATUS CmpQuerySecurityDescriptorInfo (IN PCM_KEY_CONTROL_BLOCK kcb, IN PSECURITY_INFORMATION SecurityInformation, OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG Length, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor)
VOID CmpRemoveSecurityCellList (IN PHHIVE Hive, IN HCELL_INDEX SecurityCell)
ULONG CmpSecurityExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointers)
NTSTATUS CmpSecurityMethod (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
NTSTATUS CmpSetSecurityDescriptorInfo (IN PCM_KEY_CONTROL_BLOCK kcb, IN PSECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR ModificationDescriptor, IN OUT PSECURITY_DESCRIPTOR *ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Macro Definition Documentation
#define SECURITY_CELL_LENGTH (pDescriptor)
Value:
FIELD_OFFSET(CM_KEY_SECURITY,Descriptor) + \
    RtlLengthSecurityDescriptor(pDescriptor)
Definition at line 84 of file cmse.c.
Referenced by CmpAssignSecurityDescriptor(), and CmpSetSecurityDescriptorInfo().
Function Documentation
NTSTATUS CmpAssignSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PCM_KEY_NODE Node, IN PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 1007 of file cmse.c.
References ASSERT, ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_NODE, _UNICODE_STRING::Buffer, CM_KEY_SECURITY_SIGNATURE, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpFindMatchingDescriptorCell(), CmpInsertSecurityCellList(), _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, NULL, _CM_KEY_SECURITY::ReferenceCount, RtlCopyMemory, RtlLengthSecurityDescriptor(), SECURITY_CELL_LENGTH, _CM_KEY_SECURITY::Signature, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, and STATUS_SUCCESS.
Referenced by CmpAssignSecurityDescriptorWrapper(), CmpCopyKeyPartial(), and CmpSyncKeyValues().
NTSTATUS CmpAssignSecurityDescriptorWrapper (IN PVOID Object, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor)
Definition at line 148 of file cmse.c.
References ASSERT, ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, CM_PAGED_CODE, CmpAssignSecurityDescriptor(), CmpAssignSecurityToKcb(), CmpSecurityExceptionFilter(), except, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NT_SUCCESS, NULL, ObAssignObjectSecurityDescriptor(), PagedPool, _CM_KEY_NODE::Security, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by CmpDoCreateChild(), and CmpSecurityMethod().
BOOLEAN CmpCheckCreateAccess (IN PUNICODE_STRING RelativeName, IN PSECURITY_DESCRIPTOR Descriptor, IN PACCESS_STATE AccessState, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK AdditionalAccess, OUT PNTSTATUS AccessStatus)
Definition at line 1255 of file cmse.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpKeyObjectType, DPFLTR_CONFIG_ID, _OBJECT_TYPE_INITIALIZER::GenericMapping, KEY_CREATE_SUB_KEY, NULL, SeAccessCheck(), SeLockSubjectContext(), SeUnlockSubjectContext(), TRUE, _OBJECT_TYPE::TypeInfo, and UNREFERENCED_PARAMETER.
Referenced by CmpDoCreate().
NTSTATUS CmpCheckKeyAccess (IN PHHIVE Hive, IN HCELL_INDEX NodeCell, IN KPROCESSOR_MODE PreviousMode, IN ACCESS_MASK DesiredAccess)
Definition at line 2070 of file cmse.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, CM_PAGED_CODE, CmpKeyObjectType, DACL_SECURITY_INFORMATION, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY::DescriptorLength, ExAllocatePool, ExFreePool(), FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, GROUP_SECURITY_INFORMATION, HvGetCell, HvReleaseCell, NT_SUCCESS, NULL, OWNER_SECURITY_INFORMATION, PagedPool, SACL_SECURITY_INFORMATION, SeAccessCheck(), SeCaptureSubjectContext(), _CM_KEY_NODE::Security, SeQuerySecurityDescriptorInfo(), SeReleaseSubjectContext(), Status, STATUS_ACCESS_DENIED, STATUS_BUFFER_TOO_SMALL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, and _OBJECT_TYPE::TypeInfo.
Referenced by CmpDoAccessCheckOnSubtree(), and CmRenameKey().
BOOLEAN CmpCheckNotifyAccess (IN PCM_NOTIFY_BLOCK NotifyBlock, IN PHHIVE Hive, IN PCM_KEY_NODE Node)
Definition at line 1338 of file cmse.c.
References ASSERT_CM_LOCK_OWNED, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmLockHiveSecurityShared, CmpFindSecurityCellCacheIndex(), CmpKeyObjectType, CmUnlockHiveSecurity, DPFLTR_CONFIG_ID, FALSE, _OBJECT_TYPE_INITIALIZER::GenericMapping, Index, KEY_NOTIFY, NULL, SeAccessCheck(), SeLockSubjectContext(), SeUnlockSubjectContext(), Status, TRUE, _OBJECT_TYPE::TypeInfo, and UserMode.
Referenced by CmpNotifyTriggerCheck().
NTSTATUS CmpDoAccessCheckOnSubtree (PHHIVE HiveToCheck, HCELL_INDEX Cell, KPROCESSOR_MODE PreviousMode, ACCESS_MASK DesiredAccess, BOOLEAN CheckRoot)
Definition at line 2208 of file cmse.c.
References ASSERT_CM_LOCK_OWNED_EXCLUSIVE, Cell, CMP_CHECK_REGISTRY_STACK_ENTRY::Cell, CMP_CHECK_REGISTRY_STACK_ENTRY::CellChecked, CMP_CHECK_REGISTRY_STACK_ENTRY::ChildIndex, CMP_MAX_REGISTRY_DEPTH, CmpCheckKeyAccess(), CmpFindSubKeyByNumber(), ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, HCELL_NIL, HvGetCell, NT_SUCCESS, NULL, PagedPool, PROTECTED_POOL, _HHIVE::ReleaseCellRoutine, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmRenameKey().
BOOLEAN CmpFindMatchingDescriptorCell (IN PCMHIVE CmHive, IN PSECURITY_DESCRIPTOR SecurityDescriptor, IN ULONG Type, OUT PHCELL_INDEX MatchingCell, OUT OPTIONAL PCM_KEY_SECURITY_CACHE * CachedSecurityPointer)
Definition at line 901 of file cmsecache.c.
References ARGUMENT_PRESENT, _CM_KEY_SECURITY_CACHE::Cell, CmpSecConvKey(), CmpSecHashTableSize, CONTAINING_RECORD, _CM_KEY_SECURITY_CACHE::ConvKey, _CM_KEY_SECURITY_CACHE::Descriptor, _CM_KEY_SECURITY_CACHE::DescriptorLength, FALSE, _LIST_ENTRY::Flink, HvGetCellType, IsListEmpty, List, PAGED_CODE, RtlEqualMemory, RtlLengthSecurityDescriptor(), and TRUE.
Referenced by CmpAssignSecurityDescriptor(), and CmpSetSecurityDescriptorInfo().
VOID CmpFreeSecurityDescriptor (IN PHHIVE Hive, IN HCELL_INDEX Cell)
Definition at line 1709 of file cmse.c.
References ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_NODE, ASSERT_SECURITY, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpRemoveSecurityCellList(), DPFLTR_CONFIG_ID, HCELL_NIL, HvFreeCell(), HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyNode, _CELL_DATA::_u::KeySecurity, NULL, _CM_KEY_SECURITY::ReferenceCount, _CM_KEY_NODE::Security, and _CELL_DATA::u.
Referenced by CmpFreeKeyByCell(), and CmpSyncKeyValues().
PCM_KEY_SECURITY CmpGetKeySecurity (IN PHHIVE Hive, IN PCM_KEY_NODE Key, OUT PHCELL_INDEX SecurityCell)
Definition at line 1415 of file cmse.c.
References ASSERT, ASSERT_NODE, ASSERT_SECURITY, _UNICODE_STRING::Buffer, CM_KEY_NODE_SIGNATURE, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, DPFLTR_CONFIG_ID, HvGetCell, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, and NULL.
Referenced by CmpSetSecurityDescriptorInfo().
PSECURITY_DESCRIPTOR CmpHiveRootSecurityDescriptor (VOID)
Definition at line 1484 of file cmse.c.
References _ACE_HEADER::AceFlags, ACL_REVISION, ALLOCATE_SECURITY_DESCRIPTOR, ASSERT, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CONTAINER_INHERIT_ACE, DOMAIN_ALIAS_RID_ADMINS, DPFLTR_CONFIG_ID, ExAllocatePool, ExFreePool(), FALSE, KEY_ALL_ACCESS, KEY_READ, NT_SUCCESS, NULL, PagedPool, REGISTRY_ERROR, RtlAddAccessAllowedAce(), RtlCopyMemory, RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlGetAce(), RtlInitializeSid(), RtlLengthRequiredSid(), RtlSetDaclSecurityDescriptor(), RtlSubAuthoritySid(), RtlValidSid(), SECURITY_BUILTIN_DOMAIN_RID, SECURITY_DESCRIPTOR_REVISION, SECURITY_LOCAL_SYSTEM_RID, SECURITY_NT_AUTHORITY, SECURITY_RESTRICTED_CODE_RID, SECURITY_WORLD_RID, SECURITY_WORLD_SID_AUTHORITY, SeLengthSid, Status, and TRUE.
Referenced by CmInitSystem1(), CmpCreateRegistryRoot(), CmpInitializeHiveList(), and CmpInitializeSystemHive().
BOOLEAN CmpInsertSecurityCellList (IN PHHIVE Hive, IN HCELL_INDEX NodeCell, IN HCELL_INDEX SecurityCell)
Definition at line 1803 of file cmse.c.
References ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_NODE, ASSERT_SECURITY, _CM_KEY_SECURITY::Blink, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpAddSecurityCellToCache(), DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_SECURITY::Flink, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseFreeCellRefArray(), HvTrackCellRef(), KEY_HIVE_ENTRY, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, _CM_KEY_NODE::Security, TRUE, and Volatile.
Referenced by CmpAssignSecurityDescriptor().
NTSTATUS CmpQuerySecurityDescriptorInfo (IN PCM_KEY_CONTROL_BLOCK kcb, IN PSECURITY_INFORMATION SecurityInformation, OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG Length, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor)
Definition at line 1181 of file cmse.c.
References CM_PAGED_CODE, CmKdPrintEx, CML_SEC, DPFLTR_CONFIG_ID, SeQuerySecurityDescriptorInfo(), Status, and UNREFERENCED_PARAMETER.
Referenced by CmpSecurityMethod().
VOID CmpRemoveSecurityCellList (IN PHHIVE Hive, IN HCELL_INDEX SecurityCell)
Definition at line 1987 of file cmse.c.
References ASSERT, ASSERT_HIVE_SECURITY_LOCK_OWNED, _CM_KEY_SECURITY::Blink, Cell, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpRemoveFromSecurityCache(), DPFLTR_CONFIG_ID, _CM_KEY_SECURITY::Flink, HvGetCell, HvReleaseCell, and NULL.
Referenced by CmpFreeSecurityDescriptor(), and CmpSetSecurityDescriptorInfo().
ULONG CmpSecurityExceptionFilter (IN PEXCEPTION_POINTERS ExceptionPointers)
Definition at line 107 of file cmse.c.
References DbgBreakPoint(), DbgPrintEx(), DPFLTR_CONFIG_ID, DPFLTR_ERROR_LEVEL, except, and EXCEPTION_EXECUTE_HANDLER.
Referenced by CmpAssignSecurityDescriptorWrapper(), and CmpSecurityMethod().
NTSTATUS CmpSecurityMethod (IN PVOID Object, IN SECURITY_OPERATION_CODE OperationCode, IN PSECURITY_INFORMATION SecurityInformation, IN OUT PSECURITY_DESCRIPTOR SecurityDescriptor, IN OUT PULONG CapturedLength, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 206 of file cmse.c.
References ASSERT, ASSERT_KCB_LOCKED, ASSERT_KEY_OBJECT, AssignSecurityDescriptor, BAD_SECURITY_METHOD, CM_BUGCHECK, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CmLockHiveSecurityExclusive, CmpAssignSecurityDescriptorWrapper(), CmpLockHiveFlusherShared, CmpLockKCBExclusive, CmpLockKCBShared, CmpLockRegistry(), CmpQuerySecurityDescriptorInfo(), CmpReportNotify(), CmpSecurityExceptionFilter(), CmpSetSecurityDescriptorInfo(), CmpUnlockHiveFlusher, CmpUnlockKCB, CmpUnlockRegistry(), CmUnlockHiveSecurity, _CM_KEY_CONTROL_BLOCK::Delete, DeleteSecurityDescriptor, DPFLTR_CONFIG_ID, except, FALSE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, NonPagedPool, NT_SUCCESS, NULL, PagedPool, QuerySecurityDescriptor, REG_NOTIFY_CHANGE_ATTRIBUTES, REG_NOTIFY_CHANGE_SECURITY, REGISTRY_ERROR, SetSecurityDescriptor, Status, STATUS_KEY_DELETED, STATUS_UNSUCCESSFUL, and TRUE.
Referenced by CmpCreateObjectTypes().
NTSTATUS CmpSetSecurityDescriptorInfo (IN PCM_KEY_CONTROL_BLOCK kcb, IN PSECURITY_INFORMATION SecurityInformation, IN PSECURITY_DESCRIPTOR ModificationDescriptor, IN OUT PSECURITY_DESCRIPTOR * ObjectsSecurityDescriptor, IN POOL_TYPE PoolType, IN PGENERIC_MAPPING GenericMapping)
Definition at line 471 of file cmse.c.
References ASSERT, ASSERT_HIVE_SECURITY_LOCK_OWNED, ASSERT_KCB_LOCKED_EXCLUSIVE, ASSERT_SECURITY, BAD_SECURITY_CACHE, _CM_KEY_SECURITY::Blink, CM_BUGCHECK, CM_KEY_SECURITY_SIGNATURE, CM_PAGED_CODE, CmKdPrintEx, CML_SEC, CmpAddSecurityCellToCache(), CmpAssignSecurityToKcb(), CmpFindMatchingDescriptorCell(), CmpFindSecurityCellCacheIndex(), CmpGetKeySecurity(), CmpRemoveEntryList, CmpRemoveFromSecurityCache(), CmpRemoveSecurityCellList(), CmpSecConvKey(), CmpSecHashTableSize, _CM_KEY_SECURITY_CACHE::ConvKey, DCmCheckRegistry, _CM_KEY_SECURITY::Descriptor, _CM_KEY_SECURITY_CACHE::Descriptor, _CM_KEY_SECURITY::DescriptorLength, DPFLTR_CONFIG_ID, ExFreePool(), FALSE, _CM_KEY_SECURITY::Flink, HCELL_NIL, Hive, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReallocateCell(), HvReleaseFreeCellRefArray(), HvTrackCellRef(), Index, InsertTailList(), KeQuerySystemTime(), _CM_KEY_NODE::LastWriteTime, _CM_KEY_SECURITY_CACHE::List, NT_SUCCESS, NULL, _CM_KEY_SECURITY::ReferenceCount, REGISTRY_ERROR, RtlCopyMemory, RtlLengthSecurityDescriptor(), _CM_KEY_NODE::Security, SECURITY_CELL_LENGTH, SeSetSecurityDescriptorInfo(), _CM_KEY_SECURITY::Signature, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_SUCCESS, TRUE, and UNREFERENCED_PARAMETER.
Referenced by CmpSecurityMethod().