Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmparse2.c File Reference
cmparse2.c File Reference
#include "cmp.h"
Functions
NTSTATUS CmpDoCreate (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN PCMHIVE OriginatingHive OPTIONAL, OUT PVOID *Object)
NTSTATUS CmpDoCreateChild (IN PHHIVE Hive, IN HCELL_INDEX ParentCell, IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN USHORT Flags, OUT PHCELL_INDEX KeyCell, OUT PVOID *Object)
BOOLEAN CmpOKToFollowLink (IN PCMHIVE OrigHive, IN PCMHIVE DestHive)
VOID CmpReLockKcbArray (IN PULONG LockedKcbs, IN BOOLEAN LockExclusive)
ULONG CmpUnLockKcbArray (IN PULONG LockedKcbs, IN ULONG Exempt)
Variables
PCM_KEY_CONTROL_BLOCK CmpKeyControlBlockRoot
Function Documentation
NTSTATUS CmpDoCreate (IN PHHIVE Hive, IN HCELL_INDEX Cell, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN PCMHIVE OriginatingHive OPTIONAL, OUT PVOID * Object)
Definition at line 44 of file cmparse2.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, ASSERT, ASSERT_HASH_ENTRY_LOCKED_EXCLUSIVE, ASSERT_KCB_LOCKED_EXCLUSIVE, CmIsKcbReadOnly, CmKdPrintEx, CML_PARSE, CmpAddSubKey(), CmpCheckCreateAccess(), CmpCleanUpSubKeyInfo(), CmpDoCreateChild(), CmpFindSubKeyByName(), CmpFreeKeyByCell(), CmpLockHiveFlusherShared, CmpOKToFollowLink(), CmpRemoveKeyControlBlock(), CmpUnlockHiveFlusher, CmUpcaseUnicodeChar, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CM_KEY_CONTROL_BLOCK::KcbLastWriteTime, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, KeGetPreviousMode, KeQuerySystemTime(), KEY_CREATE_LINK, KEY_READ, KEY_SYM_LINK, KEY_WRITE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyNode, _CM_KEY_NODE::LastWriteTime, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, NT_SUCCESS, NULL, ObDereferenceObjectDeferDelete(), OBJ_NAME_PATH_SEPARATOR, _CM_KEY_CONTROL_BLOCK::ParentKcb, REG_CREATED_NEW_KEY, REG_OPTION_BACKUP_RESTORE, REG_OPTION_CREATE_LINK, REG_OPTION_VOLATILE, SeBackupPrivilege, SeRestorePrivilege, SeSinglePrivilegeCheck(), STATUS_ACCESS_DENIED, STATUS_CHILD_MUST_BE_VOLATILE, STATUS_INSUFFICIENT_RESOURCES, STATUS_NO_LOG_SPACE, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_REPARSE, STATUS_SUCCESS, TRUE, _CELL_DATA::u, Volatile, WRITE_DAC, and WRITE_OWNER.
Referenced by CmpParseKey().
NTSTATUS CmpDoCreateChild (IN PHHIVE Hive, IN HCELL_INDEX ParentCell, IN PSECURITY_DESCRIPTOR ParentDescriptor OPTIONAL, IN PACCESS_STATE AccessState, IN PUNICODE_STRING Name, IN KPROCESSOR_MODE AccessMode, IN PCM_PARSE_CONTEXT Context, IN PCM_KEY_CONTROL_BLOCK ParentKcb, IN USHORT Flags, OUT PHCELL_INDEX KeyCell, OUT PVOID * Object)
Definition at line 416 of file cmparse2.c.
References ASSERT, _CM_KEY_NODE::Class, _CM_KEY_NODE::ClassLength, CM_KCB_KEY_NON_EXIST, CM_KEY_NODE_SIGNATURE, CmKdPrintEx, CML_PARSE, CmLockHiveSecurityExclusive, CMP_CREATE_KCB_KCB_LOCKED, CMP_ENLIST_KCB_LOCKED_EXCLUSIVE, CmpAssignSecurityDescriptorWrapper(), CmpCopyName(), CmpCreateKeyControlBlock(), CmpDereferenceKeyControlBlockWithLock(), CmpHKeyNodeSize, CmpKeyObjectType, CmpRemoveKeyControlBlock(), CmpReportNotify(), CmUnlockHiveSecurity, _CHILD_LIST::Count, DbgBreakPoint(), _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, EnlistKeyBodyWithKCB(), except, EXCEPTION_EXECUTE_HANDLER, _CM_KEY_CONTROL_BLOCK::ExtFlags, FALSE, _CM_KEY_NODE::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvReleaseCell, KeQuerySystemTime(), KEY_BODY_TYPE, KEY_COMP_NAME, KEY_PREDEF_HANDLE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_BODY::KeyControlBlock, _CM_KEY_CONTROL_BLOCK::KeyHive, _CELL_DATA::_u::KeyString, _CM_KEY_NODE::LastWriteTime, leave, _CHILD_LIST::List, _CM_KEY_NODE::MaxClassLen, _CM_KEY_NODE::MaxNameLen, _CM_KEY_NODE::MaxValueDataLen, _CM_KEY_NODE::MaxValueNameLen, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, _CM_KEY_BODY::NotifyBlock, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObDereferenceObjectDeferDelete(), _CM_KEY_NODE::Parent, _OBJECT_TYPE_INITIALIZER::PoolType, _CM_KEY_BODY::ProcessID, PsGetCurrentProcessId(), _CM_KEY_CONTROL_BLOCK::RefCount, REG_NOTIFY_CHANGE_NAME, REG_OPTION_PREDEF_HANDLE, REG_OPTION_VOLATILE, RtlCopyMemory, SeAssignSecurity(), _CM_KEY_NODE::Security, SeDeassignSecurity(), _CM_KEY_NODE::Signature, _CM_KEY_NODE::Spare, Stable, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_NAME_NOT_FOUND, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, _CM_KEY_BODY::Type, _OBJECT_TYPE::TypeInfo, _CELL_DATA::u, _CM_KEY_NODE::ValueList, and Volatile.
Referenced by CmpCreateLinkNode(), and CmpDoCreate().
BOOLEAN CmpOKToFollowLink (IN PCMHIVE OrigHive, IN PCMHIVE DestHive)
Definition at line 3155 of file cmparse.c.
References ASSERT, CM_CMHIVE_FLAG_UNTRUSTED, CmpLockHiveListShared, CmpUnlockHiveList, CONTAINING_RECORD, Fail, FALSE, _LIST_ENTRY::Flink, NULL, PAGED_CODE, TRUE, and _CMHIVE::TrustClassEntry.
Referenced by CmpDoCreate(), CmpDoOpen(), and CmpGetSymbolicLink().
VOID CmpReLockKcbArray (IN PULONG LockedKcbs, IN BOOLEAN LockExclusive)
Definition at line 3427 of file cmparse.c.
References CM_PAGED_CODE, CmpLockHashEntryByIndexExclusive, CmpLockHashEntryByIndexShared, and Count.
ULONG CmpUnLockKcbArray (IN PULONG LockedKcbs, IN ULONG Exempt)
Definition at line 3408 of file cmparse.c.
References CM_PAGED_CODE, CmpUnlockHashEntryByIndex, and Count.
Referenced by CmpCacheLookup(), CmpDoOpen(), and CmpParseKey().
Variable Documentation
PCM_KEY_CONTROL_BLOCK CmpKeyControlBlockRoot
Definition at line 74 of file cmdat2.c.