Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/logsup.c File Reference
logsup.c File Reference
#include "cc.h"
Macros
#define me 0x0000040
Functions
LARGE_INTEGER CcGetDirtyPages (__in PVOID LogHandle, __in PDIRTY_PAGE_ROUTINE DirtyPageRoutine, __in PVOID Context1, __in PVOID Context2)
LARGE_INTEGER CcGetLsnForFileObject (__in PFILE_OBJECT FileObject, __out_opt PLARGE_INTEGER OldestLsn)
BOOLEAN CcIsThereDirtyData (__in PVPB Vpb)
VOID CcSetAdditionalCacheAttributes (__in PFILE_OBJECT FileObject, __in BOOLEAN DisableReadAhead, __in BOOLEAN DisableWriteBehind)
VOID CcSetLogHandleForFile (__in PFILE_OBJECT FileObject, __in PVOID LogHandle, __in PFLUSH_TO_LSN FlushToLsnRoutine)
NTKERNELAPI BOOLEAN CcSetPrivateWriteFile (PFILE_OBJECT FileObject)
Macro Definition Documentation
#define me 0x0000040
Definition at line 26 of file logsup.c.
Function Documentation
LARGE_INTEGER CcGetDirtyPages (__in PVOID LogHandle, __in PDIRTY_PAGE_ROUTINE DirtyPageRoutine, __in PVOID Context1, __in PVOID Context2)
Definition at line 292 of file logsup.c.
References _BCB::BcbLinks, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, _BCB::ByteLength, CACHE_NTC_BCB, CcAcquireMasterLock, CcDecrementOpenCount, CcDirtySharedCacheMapList, CcIncrementOpenCount, CcReleaseMasterLock, CcUnpinFileData, CONTAINING_RECORD, _BCB::Dirty, _SHARED_CACHE_MAP::DirtyPages, _SHARED_CACHE_MAP::FileObject, _BCB::FileOffset, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, IS_CURSOR, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _SHARED_CACHE_MAP::LogHandle, _BCB::NewestLsn, _BCB::NodeTypeCode, NULL, _BCB::OldestLsn, _KLOCK_QUEUE_HANDLE::OldIrql, _BCB::PinCount, _LARGE_INTEGER::QuadPart, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, UNPIN, and UNREF.
LARGE_INTEGER CcGetLsnForFileObject (__in PFILE_OBJECT FileObject, __out_opt PLARGE_INTEGER OldestLsn)
Definition at line 605 of file logsup.c.
References ARGUMENT_PRESENT, _BCB::BcbLinks, _SHARED_CACHE_MAP::BcbList, _SHARED_CACHE_MAP::BcbSpinLock, CACHE_NTC_BCB, CONTAINING_RECORD, _BCB::Dirty, _LIST_ENTRY::Flink, _LARGE_INTEGER::HighPart, KeAcquireInStackQueuedSpinLock(), KeReleaseInStackQueuedSpinLock(), _LARGE_INTEGER::LowPart, _BCB::NewestLsn, _BCB::NodeTypeCode, NULL, _BCB::OldestLsn, and _LARGE_INTEGER::QuadPart.
BOOLEAN CcIsThereDirtyData (__in PVPB Vpb)
Definition at line 517 of file logsup.c.
References CcAcquireMasterLock, CcDirtySharedCacheMapList, CcReleaseMasterLock, ClearFlag, CONTAINING_RECORD, _SHARED_CACHE_MAP::DirtyPages, FALSE, _SHARED_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, _FILE_OBJECT::Flags, _LIST_ENTRY::Flink, FO_TEMPORARY_FILE, IS_CURSOR, SetFlag, _SHARED_CACHE_MAP::SharedCacheMapLinks, _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks, TRUE, _FILE_OBJECT::Vpb, and WRITE_QUEUED.
VOID CcSetAdditionalCacheAttributes (__in PFILE_OBJECT FileObject, __in BOOLEAN DisableReadAhead, __in BOOLEAN DisableWriteBehind)
Definition at line 34 of file logsup.c.
References CcAcquireMasterLock, CcReleaseMasterLock, ClearFlag, DISABLE_READ_AHEAD, DISABLE_WRITE_BEHIND, _SHARED_CACHE_MAP::Flags, MODIFIED_WRITE_DISABLED, and SetFlag.
VOID CcSetLogHandleForFile (__in PFILE_OBJECT FileObject, __in PVOID LogHandle, __in PFLUSH_TO_LSN FlushToLsnRoutine)
Definition at line 242 of file logsup.c.
References _SHARED_CACHE_MAP::FlushToLsnRoutine, and _SHARED_CACHE_MAP::LogHandle.
NTKERNELAPI BOOLEAN CcSetPrivateWriteFile (PFILE_OBJECT FileObject)
Definition at line 95 of file logsup.c.
References CcAcquireMasterLock, CcFlushCache(), CcFreeActiveVacb(), CcReleaseMasterLock, CcUnmapVacbArray(), CcWaitForCurrentLazyWriterActivity(), CcWaitOnActiveCount(), DISABLE_WRITE_BEHIND, Disabled, FALSE, FlagOn, _SHARED_CACHE_MAP::Flags, FsRtlAcquireFileExclusive(), FsRtlReleaseFile(), GetActiveVacbAtDpcLevel, MmDisableModifiedWriteOfSection(), NULL, PRIVATE_WRITE, READ_AHEAD_QUEUED, _FILE_OBJECT::SectionObjectPointer, SetFlag, _SECTION_OBJECT_POINTERS::SharedCacheMap, _SHARED_CACHE_MAP::Vacbs, and WRITE_QUEUED.
Referenced by CmpAcquireFileObjectForFile().