Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/mapcache.c File Reference
mapcache.c File Reference
#include "mi.h"
Macros
#define X256K 0x40000
Functions
NTSTATUS MiAddMappedPtes (IN PMMPTE FirstPte, IN PFN_NUMBER NumberOfPtes, IN PCONTROL_AREA ControlArea)
VOID MiInitializeSystemCache (IN ULONG MinimumWorkingSet, IN ULONG MaximumWorkingSet)
LONG MiMapCacheExceptionFilter (IN PNTSTATUS Status, IN PEXCEPTION_POINTERS ExceptionPointer)
VOID MiRemoveMappedPtes (IN PVOID BaseAddress, IN ULONG NumberOfPtes, IN PCONTROL_AREA ControlArea, IN PMMSUPPORT Ws)
BOOLEAN MmCheckCachedPageState (IN PVOID SystemCacheAddress, IN BOOLEAN SetToZero)
NTSTATUS MmCopyToCachedPage (IN PVOID SystemCacheAddress, IN PVOID UserBuffer, IN ULONG Offset, IN SIZE_T CountInBytes, LOGICAL ExposeZeroPageOk)
LOGICAL MmIsSystemCacheAddress (IN PVOID VirtualAddress)
NTSTATUS MmMapViewInSystemCache (IN PVOID SectionToMap, OUT PVOID *CapturedBase, IN OUT PLARGE_INTEGER SectionOffset, IN OUT PULONG CapturedViewSize)
VOID MmUnlockCachedPage (IN PVOID AddressInCache)
VOID MmUnmapViewInSystemCache (IN PVOID BaseAddress, IN PVOID SectionToUnmap, IN ULONG AddToFront)
Variables
ULONG MiMapCacheFailures
PMMPTE MmFirstFreeSystemCache
ULONG MmFrontOfList
PMMPTE MmLastFreeSystemCache
PMMPTE MmSystemCachePteBase
Macro Definition Documentation
#define X256K 0x40000
Definition at line 30 of file mapcache.c.
Referenced by MiInitializeSystemCache(), MmMapViewInSystemCache(), and MmUnmapViewInSystemCache().
Function Documentation
NTSTATUS MiAddMappedPtes (IN PMMPTE FirstPte, IN PFN_NUMBER NumberOfPtes, IN PCONTROL_AREA ControlArea)
Definition at line 341 of file mapcache.c.
References ASSERT, _MMPTE::Long, MI_WRITE_INVALID_PTE, MiAddViewsForSectionWithPfn(), MiProtoAddressForKernelPte, MM_COLOR_MASK, _SUBSECTION::NextSubsection, NT_SUCCESS, NULL, PTE_SHIFT, _SUBSECTION::PtesInSubsection, Status, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, and _MMPTE::u.
Referenced by MiMapViewInSystemSpace(), and MiShareSessionImage().
VOID MiInitializeSystemCache (IN ULONG MinimumWorkingSet, IN ULONG MaximumWorkingSet)
Definition at line 1236 of file mapcache.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, _MMWSL::FirstDynamic, _MMWSL::FirstFree, _MMPTE::Hard, _MMWSL::HashTable, _MMWSL::HashTableSize, _MMWSL::HashTableStart, _MMWSL::HighestPermittedHashAddress, _MMWSL::LastEntry, _MMWSL::LastInitializedWsle, _MMPTE::List, LOCK_PFN, _MMWSLE::Long, _MMSUPPORT::MaximumWorkingSetSize, MI_COMPUTE_PAGES_SPANNED, MI_GET_PAGE_COLOR_FROM_PTE, MI_PTE_BASE_FOR_LOWEST_KERNEL_ADDRESS, MiAllowWorkingSetExpansion(), MiGetPteAddress, MiInitializePfnAndMakePteValid(), _MMSUPPORT::MinimumWorkingSetSize, MiRemoveZeroPage(), MiSystemCacheEndExtra, MiSystemCacheStartExtra, MM_EMPTY_PTE_LIST, MM_FREE_WSLE_SHIFT, MM_MAXIMUM_WORKING_SET, MmResidentAvailablePages, MmSystemCacheEnd, MmSystemCachePteBase, MmSystemCacheStart, MmSystemCacheWorkingSetList, MmSystemCacheWs, MmSystemCacheWsle, _MMPTE_LIST::NextEntry, _MMWSL::NextSlot, NULL, PAGE_ALIGN, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMWSLE::u1, UNLOCK_PFN, _MMWSL::UsedPageTableEntries, ValidKernelPte, _MMSUPPORT::VmWorkingSetList, _MMSUPPORT::WorkingSetSize, _MMWSL::Wsle, WSLE_NULL_INDEX, and X256K.
Referenced by MmInitSystem().
LONG MiMapCacheExceptionFilter (IN PNTSTATUS Status, IN PEXCEPTION_POINTERS ExceptionPointer)
Definition at line 2627 of file mapcache.c.
References EXCEPTION_EXECUTE_HANDLER, STATUS_ACCESS_VIOLATION, STATUS_IN_PAGE_ERROR, and STATUS_INVALID_USER_BUFFER.
Referenced by MmCopyToCachedPage().
VOID MiRemoveMappedPtes (IN PVOID BaseAddress, IN ULONG NumberOfPtes, IN PCONTROL_AREA ControlArea, IN PMMSUPPORT Ws)
Definition at line 827 of file mapcache.c.
References ASSERT, _MSUBSECTION::ControlArea, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_PFN, LOCK_WORKING_SET, _MMPTE::Long, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_FLUSH_ENTIRE_TB, MI_FLUSH_MULTIPLE_TB, MI_FLUSH_SINGLE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_WRITE_VALID_PTE, MI_WRITE_ZERO_PTE, MiCheckControlArea(), MiDecrementShareCount(), MiDecrementShareCountInline, MiGetPteAddress, MiGetSubsectionAddress, MiMakeSystemAddressValidPfn(), MiPteToProto, MiRemoveViewsFromSection(), MiTerminateWsle(), MM_MAXIMUM_FLUSH_COUNT, MmSystemPagePtes, NOTHING, NULL, _MMPFN::OriginalPte, PAGE_SIZE, PD_PER_SYSTEM, PDE_PER_PAGE, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MSUBSECTION::PtesInSubsection, _MMPTE::Soft, _MSUBSECTION::SubsectionBase, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _MMPFN::u1, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WORKING_SET, _MMPTE_HARDWARE::Valid, and _MMPFN::WsIndex.
Referenced by MiUnmapViewInSystemSpace().
BOOLEAN MmCheckCachedPageState (IN PVOID SystemCacheAddress, IN BOOLEAN SetToZero)
Definition at line 1434 of file mapcache.c.
References ActiveAndValid, ASSERT, _MMPFNENTRY::CacheAttribute, CCPF_IS_PREFETCHER_ACTIVE, CCPF_TYPE_ROM, CcPfLogPageFault(), _SUBSECTION::ControlArea, _MMPFN::e1, _MMWSLE::e1, _MMPFN::e2, FALSE, FileOffset, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _MMPFN::InPageError, InterlockedIncrementPfn, KernelMode, LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, _MMWSLE::Long, MI_BARRIER_SYNCHRONIZE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_MAKE_VALID_KERNEL_PTE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_SET_GLOBAL_STATE, MI_SNAP_DATA, MI_WRITE_VALID_PTE, MiAllocateWsle(), MiCached, MiGetPteAddress, MiGetSubsectionAddress, MiHighestUserPte, MiInitializePfn(), MiMakeSystemAddressValidPfnSystemWs(), MiNonCached, MiProtoAddressForPte, MiPteToProto, MiRemoveZeroPage(), MiStartingOffset(), MiTrimPte(), MiUnlinkPageFromList(), MiWriteCombined, MM_HIGH_LIMIT, MM_NOCACHE, MM_WRITECOMBINE, MM_ZERO_ACCESS, MmAccessFault(), MmAvailablePages, MmSystemCacheWs, NOTHING, NULL, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, _MMSECTION_FLAGS::Rom, _MMPFN::ShareCount, _MMPTE::Soft, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMWSLE::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_SYSTEM_WS, and _MMPTE_HARDWARE::Valid.
Referenced by CcCopyRead(), CcFastCopyRead(), CcMapAndCopy(), CcMapAndRead(), CcMapDataForOverwrite(), and CcPerformReadAhead().
NTSTATUS MmCopyToCachedPage (IN PVOID SystemCacheAddress, IN PVOID UserBuffer, IN ULONG Offset, IN SIZE_T CountInBytes, LOGICAL ExposeZeroPageOk)
Definition at line 1805 of file mapcache.c.
References ActiveAndValid, _ETHREAD::ActiveFaultCount, _ETHREAD::ApcNeeded, ASSERT, _MMPFNENTRY::CacheAttribute, CCPF_TYPE_ROM, CcPfLogPageFault(), _MMINPAGE_FLAGS::Completed, _SUBSECTION::ControlArea, Copy, DISPATCH_LEVEL, _MMPFN::e1, _MMWSLE::e1, _MMINPAGE_SUPPORT::e1, _MMPFN::e2, _MMPFN::Event, _MMINPAGE_SUPPORT::Event, except, EXCEPTION_EXECUTE_HANDLER, FALSE, FileOffset, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _IO_STATUS_BLOCK::Information, _MMPFN::InPageError, InterlockedIncrementPfn, IoRetryIrpCompletions(), _MMINPAGE_SUPPORT::IoStatus, KeEnterCriticalRegionThread(), KeGetCurrentIrql(), KeLeaveCriticalRegionThread(), KeSetEvent(), LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, _MMWSLE::Long, MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_FLUSH_ENTIRE_TB_FOR_ATTRIBUTE_CHANGE, MI_GET_PAGE_COLOR_FROM_PTE, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_IS_NOCACHE, MI_IS_WRITECOMBINE, MI_MAGIC_AWE_PTEFRAME, MI_MAKE_VALID_KERNEL_PTE, MI_MAKE_VALID_PTE, MI_PFN_ELEMENT, MI_PTE_OWNER_KERNEL, MI_REMOVE_LOCKED_PAGE_CHARGE(), MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_GLOBAL_STATE, MI_SET_MODIFIED, MI_SET_PTE_DIRTY, MI_SNAP_DATA, MI_TRANSLATE_CACHETYPE(), MI_WRITE_VALID_PTE, MiAllocateWsle(), MiCached, MiEnsureAvailablePageOrWait(), MiFreeInPageSupportBlock(), MiGetInPageSupportBlock(), MiGetPteAddress, MiGetSubsectionAddress, MiGetVirtualAddressMappedByPte, MiInitializePfn(), MiInitializeTransitionPfn(), MiInsertPageInFreeList(), MiMakeSystemAddressValidPfnSystemWs(), MiMapCacheExceptionFilter(), MiNonCached, MiProtoAddressForPte, MiPteToProto, MiReleaseSystemPtes(), MiRemoveAnyPage(), MiRemoveZeroPageIfAny, MiReserveSystemPtes(), MiRestoreTransitionPte(), MiStartingOffset(), MiTrimPte(), MiUnlinkPageFromList(), MiWriteCombined, MiZeroPhysicalPage(), MM_HIGH_LIMIT, MM_LOW_LIMIT, MM_NOCACHE, MM_READWRITE, MM_WRITECOMBINE, MM_ZERO_ACCESS, MmAvailablePages, MmResetPageFaultReadAhead, MmSavePageFaultReadAhead, MmSetPageFaultReadAhead, MmSystemCacheWs, _MMPFNENTRY::Modified, NOTHING, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfPfnReferences, _MMPFN::OriginalPte, _MMPTE_HARDWARE::Owner, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, _MMPFNENTRY::PageLocation, PASSIVE_LEVEL, _MMINPAGE_SUPPORT::Pfn, _MMPTE_SOFTWARE::Protection, _MMWSLENTRY::Protection, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MMPFN::PteFrame, _MMPFNENTRY::ReadInProgress, _MMPFN::ReadStatus, _MMSECTION_FLAGS::Rom, RtlCopyBytes, RtlZeroMemory, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _MMPTE::Soft, StandbyPageList, Status, _IO_STATUS_BLOCK::Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_MULTIPLE_FAULT_VIOLATION, STATUS_SUCCESS, SystemPteSpace, _ETHREAD::Tcb, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u1, _MMWSLE::u1, _MMINPAGE_SUPPORT::u1, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_SYSTEM_WS, _MMPTE_HARDWARE::Valid, and _MMINPAGE_SUPPORT::WaitCount.
LOGICAL MmIsSystemCacheAddress (IN PVOID VirtualAddress)
Definition at line 2731 of file mapcache.c.
References MI_IS_SYSTEM_CACHE_ADDRESS.
NTSTATUS MmMapViewInSystemCache (IN PVOID SectionToMap, OUT PVOID * CapturedBase, IN OUT PLARGE_INTEGER SectionOffset, IN OUT PULONG CapturedViewSize)
Definition at line 47 of file mapcache.c.
References APC_LEVEL, ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _MMSECTION_FLAGS::BeingPurged, BYTES_TO_PAGES, _SEGMENT::ControlArea, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _SECTION::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _MMSECTION_FLAGS::Image, KeBugCheckEx(), KeGetCurrentIrql(), KeReadTbFlushTimeStamp(), _MMPTE::List, LOCK_PFN, _MMPTE::Long, MEMORY_MANAGEMENT, MI_FLUSH_ENTIRE_TB, MI_WRITE_INVALID_PTE, MiAddViewsForSection(), MiCheckControlArea(), MiCompareTbFlushTimeStamp(), MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiMapCacheFailures, MiProtoAddressForKernelPte, MM_COLOR_MASK, MM_EMPTY_LIST, MM_EMPTY_PTE_LIST, MM_FLUSH_COUNTER_MASK, MmFirstFreeSystemCache, MmSystemCacheEnd, MmSystemCachePteBase, _MMPTE_LIST::NextEntry, _SUBSECTION::NextSubsection, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfSystemCacheViews, PAGE_SHIFT, PTE_SHIFT, _SUBSECTION::PtesInSubsection, _MMSECTION_FLAGS::Rom, _SECTION::Segment, Status, STATUS_NO_MEMORY, STATUS_NOT_MAPPED_DATA, STATUS_SUCCESS, _SUBSECTION::SubsectionBase, _MMPTE::u, _CONTROL_AREA::u, _SECTION::u, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, and X256K.
Referenced by CcGetVacbMiss(), and Phase1InitializationDiscard().
VOID MmUnlockCachedPage (IN PVOID AddressInCache)
Definition at line 2681 of file mapcache.c.
References ASSERT, _MMPFN::e2, _MMPTE::Hard, KeBugCheckEx(), LOCK_PFN, MEMORY_MANAGEMENT, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiGetPteAddress, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPFN::u3, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by CcFreeActiveVacb().
VOID MmUnmapViewInSystemCache (IN PVOID BaseAddress, IN PVOID SectionToUnmap, IN ULONG AddToFront)
Definition at line 455 of file mapcache.c.
References APC_LEVEL, ASSERT, _SEGMENT::ControlArea, _MSUBSECTION::ControlArea, _MMPFN::e1, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _MMSECTION_FLAGS::Image, KeBugCheckEx(), KeGetCurrentIrql(), KeReadTbFlushTimeStamp(), _MMPTE::List, LOCK_PFN, LOCK_SYSTEM_WS, _MMPTE::Long, MEMORY_MANAGEMENT, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_PFN_ELEMENT, MI_WRITE_ZERO_PTE, MiCheckControlArea(), MiDecrementShareCountInline, MiGetPteAddress, MiGetSubsectionAddress, MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiPteToProto, MiRemoveViewsFromSection(), MiTerminateWsle(), MM_EMPTY_PTE_LIST, MM_FLUSH_COUNTER_MASK, MmFrontOfList, MmSystemCachePteBase, MmSystemCacheWs, _MMPTE_LIST::NextEntry, _MSUBSECTION::NextSubsection, NULL, _CONTROL_AREA::NumberOfMappedViews, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfSystemCacheViews, _MMPFN::OriginalPte, PAGE_SIZE, _MMSECTION_FLAGS::PhysicalMemory, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentThread(), _MMPFN::PteAddress, _MSUBSECTION::PtesInSubsection, RtlCompareMemoryUlong(), _CONTROL_AREA::Segment, _MMPFN::ShareCount, _MMPTE::Soft, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MMPFN::u1, _MMPFN::u2, _MMPFN::u3, UNLOCK_PFN, UNLOCK_SYSTEM_WS, _MMPTE_HARDWARE::Valid, _MMPFN::WsIndex, and X256K.
Referenced by CcUnmapVacb(), and Phase1InitializationDiscard().
Variable Documentation
ULONG MiMapCacheFailures
Definition at line 38 of file mapcache.c.
Referenced by MmMapViewInSystemCache().
PMMPTE MmFirstFreeSystemCache
Definition at line 32 of file mapcache.c.
Referenced by MmMapViewInSystemCache().
ULONG MmFrontOfList
Definition at line 22 of file pfndec.c.
Referenced by MiDecrementReferenceCount(), and MmUnmapViewInSystemCache().
PMMPTE MmLastFreeSystemCache
Definition at line 34 of file mapcache.c.
PMMPTE MmSystemCachePteBase
Definition at line 36 of file mapcache.c.
Referenced by MiInitializeSystemCache(), MmMapViewInSystemCache(), and MmUnmapViewInSystemCache().