Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/flushbuf.c File Reference
flushbuf.c File Reference
#include "mi.h"
Functions
ULONG MiFlushRangeFilter (IN PEXCEPTION_POINTERS ExceptionPointers, IN PVOID *BaseAddress, IN PSIZE_T Length, IN PLOGICAL Retry)
NTSTATUS NtFlushInstructionCache (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in SIZE_T Length)
NTSTATUS NtFlushWriteBuffer (VOID)
Function Documentation
ULONG MiFlushRangeFilter (IN PEXCEPTION_POINTERS ExceptionPointers, IN PVOID * BaseAddress, IN PSIZE_T Length, IN PLOGICAL Retry)
Definition at line 67 of file flushbuf.c.
References EXCEPTION_EXECUTE_HANDLER, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionInformation, _EXCEPTION_RECORD::ExceptionRecord, ROUND_TO_PAGES, STATUS_ACCESS_VIOLATION, and TRUE.
Referenced by NtFlushInstructionCache().
NTSTATUS NtFlushInstructionCache (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in SIZE_T Length)
Definition at line 149 of file flushbuf.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, KeStackAttachProcess(), KeSweepIcache, KeSweepIcacheRange, KeUnstackDetachProcess(), MiFlushRangeFilter(), NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _EPROCESS::Pcb, ProbeForRead, PROCESS_VM_WRITE, PsProcessType, Status, and STATUS_SUCCESS.
NTSTATUS NtFlushWriteBuffer (VOID)
Definition at line 39 of file flushbuf.c.
References KeFlushWriteBuffer(), PAGED_CODE, and STATUS_SUCCESS.