Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/largepag.c File Reference
largepag.c File Reference
#include "ki.h"
Macros
#define PTES_PER_PAGE (PAGE_SIZE / sizeof(HARDWARE_PTE))
Functions
PVOID Ki386AllocateContiguousMemory (IN OUT PIDENTITY_MAP IdentityMap, IN ULONG Pages, IN BOOLEAN Low4Meg)
PHYSICAL_ADDRESS Ki386BuildIdentityBuffer (IN OUT PIDENTITY_MAP IdentityMap, IN PVOID StartVa, IN ULONG Length, OUT PULONG PagesToMap)
VOID Ki386ClearIdentityMap (IN PIDENTITY_MAP IdentityMap)
PVOID Ki386ConvertPte (IN OUT PHARDWARE_PTE Pte)
BOOLEAN Ki386CreateIdentityMap (IN OUT PIDENTITY_MAP IdentityMap, IN PVOID StartVa, IN PVOID EndVa)
VOID Ki386EnableTargetLargePage (IN PIDENTITY_MAP IdentityMap)
BOOLEAN Ki386IdentityMapMakeValid (IN OUT PIDENTITY_MAP IdentityMap, IN PHARDWARE_PTE PageTableEntry, OUT PVOID *Page OPTIONAL)
BOOLEAN Ki386MapAddress (IN OUT PIDENTITY_MAP IdentityMap, IN ULONG Va, IN PHYSICAL_ADDRESS PhysicalAddress)
Macro Definition Documentation
#define PTES_PER_PAGE (PAGE_SIZE / sizeof(HARDWARE_PTE))
Definition at line 57 of file largepag.c.
Referenced by Ki386CreateIdentityMap().
Function Documentation
PVOID Ki386AllocateContiguousMemory (IN OUT PIDENTITY_MAP IdentityMap, IN ULONG Pages, IN BOOLEAN Low4Meg)
Definition at line 233 of file largepag.c.
References FALSE, _LARGE_INTEGER::HighPart, _LARGE_INTEGER::LowPart, NULL, PAGE_SIZE, and RtlZeroMemory.
Referenced by Ki386BuildIdentityBuffer(), Ki386IdentityMapMakeValid(), and Ki386MapAddress().
PHYSICAL_ADDRESS Ki386BuildIdentityBuffer (IN OUT PIDENTITY_MAP IdentityMap, IN PVOID StartVa, IN ULONG Length, OUT PULONG PagesToMap)
Definition at line 523 of file largepag.c.
References ADDRESS_AND_SIZE_TO_SPAN_PAGES, _LARGE_INTEGER::HighPart, Ki386AllocateContiguousMemory(), MmGetPhysicalAddress(), PAGE_SIZE, _LARGE_INTEGER::QuadPart, RtlCopyMemory, and TRUE.
Referenced by Ki386CreateIdentityMap().
VOID Ki386ClearIdentityMap (IN PIDENTITY_MAP IdentityMap)
Definition at line 654 of file largepag.c.
References MmFreeContiguousMemory().
PVOID Ki386ConvertPte (IN OUT PHARDWARE_PTE Pte)
Definition at line 488 of file largepag.c.
References ASSERT, _LARGE_INTEGER::LowPart, MmGetPhysicalAddress(), PAGE_SHIFT, and _LARGE_INTEGER::QuadPart.
Referenced by Ki386CreateIdentityMap().
BOOLEAN Ki386CreateIdentityMap (IN OUT PIDENTITY_MAP IdentityMap, IN PVOID StartVa, IN PVOID EndVa)
Definition at line 60 of file largepag.c.
References FALSE, Ki386BuildIdentityBuffer(), Ki386ConvertPte(), Ki386MapAddress(), _LARGE_INTEGER::LowPart, MmGetPhysicalAddress(), PAGE_SIZE, PPI_BITS, PTES_PER_PAGE, _LARGE_INTEGER::QuadPart, RtlZeroMemory, TRUE, and _HARDWARE_PTE_X86::Valid.
Referenced by KiInitMachineDependent().
VOID Ki386EnableTargetLargePage (IN PIDENTITY_MAP IdentityMap)
Definition at line 681 of file largepag.c.
References Ki386EnableCurrentLargePage().
BOOLEAN Ki386IdentityMapMakeValid (IN OUT PIDENTITY_MAP IdentityMap, IN PHARDWARE_PTE PageTableEntry, OUT PVOID *Page OPTIONAL)
Definition at line 307 of file largepag.c.
References ARGUMENT_PRESENT, FALSE, Ki386AllocateContiguousMemory(), NULL, PAGE_SHIFT, and TRUE.
Referenced by Ki386MapAddress().
BOOLEAN Ki386MapAddress (IN OUT PIDENTITY_MAP IdentityMap, IN ULONG Va, IN PHYSICAL_ADDRESS PhysicalAddress)
Definition at line 383 of file largepag.c.
References FALSE, Ki386AllocateContiguousMemory(), Ki386IdentityMapMakeValid(), KiGetPdeIndex, KiGetPpeIndex, KiGetPteIndex, NULL, PAGE_SHIFT, _HARDWARE_PTE_X86::PageFrameNumber, TRUE, _HARDWARE_PTE_X86::Valid, and _HARDWARE_PTE_X86::Write.
Referenced by Ki386CreateIdentityMap().