Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/hypermap.c File Reference
hypermap.c File Reference
#include "mi.h"
Functions
PVOID MiMapPageInHyperSpace (IN PEPROCESS Process, IN PFN_NUMBER PageFrameIndex, IN PKIRQL OldIrql)
PVOID MiMapPageInHyperSpaceAtDpc (IN PEPROCESS Process, IN PFN_NUMBER PageFrameIndex)
PVOID MiMapPagesToZeroInHyperSpace (IN PMMPFN Pfn1, IN PFN_COUNT NumberOfPages)
VOID MiUnmapPagesInZeroSpace (IN PVOID VirtualAddress, IN PFN_COUNT NumberOfPages)
Variables
PMMPTE MiFirstReservedZeroingPte
Function Documentation
PVOID MiMapPageInHyperSpace (IN PEPROCESS Process, IN PFN_NUMBER PageFrameIndex, IN PKIRQL OldIrql)
Definition at line 26 of file hypermap.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, _MMPFN::e1, FALSE, _MMPTE::Hard, LOCK_HYPERSPACE, _MMPTE::Long, MI_DISABLE_CACHING, MI_FLUSH_PROCESS_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_PFN_ELEMENT, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MmFirstReservedMappingPte, NUMBER_OF_MAPPING_PTES, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPFN::u3, UNREFERENCED_PARAMETER, _MMPTE_HARDWARE::Valid, and ValidPtePte.
Referenced by MiCopyOnWrite(), MiMakeOutswappedPageResident(), MiSnapCopyMemory(), MiZeroPhysicalPage(), MmCreateProcessAddressSpace(), MmInitializeHandBuiltProcess2(), MmInitializeProcessAddressSpace(), and MmOutSwapProcess().
PVOID MiMapPageInHyperSpaceAtDpc (IN PEPROCESS Process, IN PFN_NUMBER PageFrameIndex)
Definition at line 160 of file hypermap.c.
References ASSERT, _MMPFNENTRY::CacheAttribute, DISPATCH_LEVEL, _MMPFN::e1, FALSE, _MMPTE::Hard, KeGetCurrentIrql(), LOCK_HYPERSPACE_AT_DPC, _MMPTE::Long, MI_DISABLE_CACHING, MI_FLUSH_PROCESS_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_IS_PFN(), MI_PFN_ELEMENT, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MmFirstReservedMappingPte, NUMBER_OF_MAPPING_PTES, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE::u, _MMPFN::u3, UNREFERENCED_PARAMETER, _MMPTE_HARDWARE::Valid, and ValidPtePte.
Referenced by MiCopyHeaderIfResident(), MiDecrementShareCount(), MiGatherMappedPages(), MiInsertPageInFreeList(), MiInsertPageInList(), MiInsertStandbyListAtFront(), MiMapWithLargePages(), MiMarkSectionWritable(), MiRestoreTransitionPte(), MiSnapCopyMemory(), MiUnmapLargePages(), MiUpdateSystemPdes(), MiWaitForInPageComplete(), MmDeleteProcessAddressSpace(), and MmInSwapProcess().
PVOID MiMapPagesToZeroInHyperSpace (IN PMMPFN Pfn1, IN PFN_COUNT NumberOfPages)
Definition at line 292 of file hypermap.c.
References ASSERT, _MMPTE::Hard, KeGetCurrentIrql(), _MMPTE::Long, MI_DISABLE_CACHING, MI_FLUSH_ENTIRE_TB, MI_GET_PAGE_FRAME_FROM_PTE, MI_PFN_ELEMENT_TO_INDEX, MI_SET_PTE_WRITE_COMBINE, MI_WRITE_VALID_PTE, MiFirstReservedZeroingPte, MiGetVirtualAddressMappedByPte, MiNonCached, MiWriteCombined, MM_EMPTY_LIST, NUMBER_OF_ZEROING_PTES, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _MMPTE::u, _MMPTE_HARDWARE::Valid, and ValidPtePte.
Referenced by MmZeroPageThread().
VOID MiUnmapPagesInZeroSpace (IN PVOID VirtualAddress, IN PFN_COUNT NumberOfPages)
Definition at line 427 of file hypermap.c.
References ASSERT, _MMPTE::Hard, KeGetCurrentIrql(), MiGetPteAddress, MiZeroMemoryPte, NUMBER_OF_ZEROING_PTES, PASSIVE_LEVEL, _MMPTE::u, and _MMPTE_HARDWARE::Valid.
Referenced by MmZeroPageThread().
Variable Documentation
PMMPTE MiFirstReservedZeroingPte
Definition at line 22 of file hypermap.c.
Referenced by MiInitMachineDependent(), and MiMapPagesToZeroInHyperSpace().