Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/amd64/ipi.c File Reference
ipi.c File Reference
#include "ki.h"
Functions
DECLSPEC_NOINLINE VOID KiIpiProcessRequests (VOID)
VOID KiIpiSendPacket (IN KAFFINITY TargetSet, IN PKIPI_WORKER WorkerFunction, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
DECLSPEC_NOINLINE PKAFFINITY KiIpiSendRequest (IN KAFFINITY TargetSet, IN ULONG64 Parameter, IN ULONG64 Count, IN ULONG64 RequestType)
VOID KiIpiSignalPacketDone (IN PKIPI_CONTEXT SignalDone)
VOID KiRestoreProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
VOID KiSaveProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Function Documentation
DECLSPEC_NOINLINE VOID KiIpiProcessRequests (VOID)
Definition at line 142 of file ipi.c.
References AFFINITY_MASK, ASSERT, _REQUEST_SUMMARY::Count, _KPRCB::CurrentPacket, FALSE, IPI_FLUSH_ALL, IPI_FLUSH_MULTIPLE, IPI_FLUSH_MULTIPLE_IMMEDIATE, IPI_FLUSH_PROCESS, IPI_FLUSH_SINGLE, IPI_INVALIDATE_ALL, IPI_PACKET_READY, _REQUEST_SUMMARY::IpiRequest, _REQUEST_SUMMARY::IpiSynchType, KeFlushCurrentTb(), KeGetCurrentPrcb(), KiFlushProcessTb(), KiFlushSingleTb(), KiProcessorBlock, _KPRCB::PacketBarrier, _REQUEST_SUMMARY::Parameter, ReadForWriteAccess, SetMember, _KPRCB::SetMember, _REQUEST_SUMMARY::Summary, and _KPRCB::TargetSet.
VOID KiIpiSendPacket (IN KAFFINITY TargetSet, IN PKIPI_WORKER WorkerFunction, IN PVOID Parameter1, IN PVOID Parameter2, IN PVOID Parameter3)
Definition at line 521 of file ipi.c.
References ASSERT, DISPATCH_LEVEL, IPI_PACKET_READY, KeGetCurrentIrql(), KiIpiSendRequest(), and UNREFERENCED_PARAMETER.
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeIpiGenericCall(), KeStartProfile(), KeStopProfile(), and KxFlushEntireTb().
DECLSPEC_NOINLINE PKAFFINITY KiIpiSendRequest (IN KAFFINITY TargetSet, IN ULONG64 Parameter, IN ULONG64 Count, IN ULONG64 RequestType)
Definition at line 323 of file ipi.c.
References AFFINITY_MASK, ASSERT, Count, _REQUEST_SUMMARY::Count, DISPATCH_LEVEL, FALSE, HalRequestIpi(), IPI_FLUSH_MULTIPLE, IPI_FLUSH_MULTIPLE_IMMEDIATE, IPI_PACKET_READY, _REQUEST_SUMMARY::IpiRequest, _REQUEST_SUMMARY::IpiSynchType, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeYieldProcessor, KiProcessorBlock, NULL, _KPRCB::Number, _KPRCB::PacketBarrier, _REQUEST_SUMMARY::Parameter, SetMember, _KPRCB::SetMember, _REQUEST_SUMMARY::Summary, _KPRCB::TargetSet, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushSingleTb(), KeInvalidateAllCaches(), KeStartAllProcessors(), KiIpiSendPacket(), and KxFlushEntireTb().
VOID KiIpiSignalPacketDone (IN PKIPI_CONTEXT SignalDone)
Definition at line 590 of file ipi.c.
References KeGetCurrentPrcb(), _KPRCB::PacketBarrier, SetMember, _KPRCB::SetMember, _KPRCB::TargetSet, and UNREFERENCED_PARAMETER.
Referenced by KiFlushTargetEntireTb(), KiFlushTargetMultipleTb(), KiFlushTargetProcessTb(), KiFlushTargetSingleTb(), KiIpiGenericCallTarget(), KiStartProfileInterrupt(), and KiStopProfileInterrupt().
VOID KiRestoreProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 23 of file ipi.c.
References CONTEXT_FULL, _KPROCESSOR_STATE::ContextFrame, KeContextToKframes(), KeGetCurrentPrcb(), KernelMode, KiRestoreProcessorControlState(), MODE_MASK, _KPRCB::ProcessorState, UNREFERENCED_PARAMETER, and UserMode.
Referenced by KiFreezeTargetExecution().
VOID KiSaveProcessorState (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 86 of file ipi.c.
References CONTEXT_FULL, _CONTEXT::ContextFlags, _KPROCESSOR_STATE::ContextFrame, KeContextFromKframes(), KeGetCurrentPrcb(), KiSaveProcessorControlState(), _KPRCB::ProcessorState, and UNREFERENCED_PARAMETER.
Referenced by KiFreezeTargetExecution().