Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntexapi.h File Reference
ntexapi.h File Reference
Data Structures
struct _ATOM_BASIC_INFORMATION
struct _ATOM_TABLE_INFORMATION
struct _BOOT_ENTRY
struct _BOOT_ENTRY_LIST
struct _BOOT_OPTIONS
struct _CACHE_DESCRIPTOR
struct _DRIVER_VERIFIER_THUNK_PAIRS
struct _EFI_DRIVER_ENTRY
struct _EFI_DRIVER_ENTRY_LIST
struct _EVENT_BASIC_INFORMATION
struct _FILE_PATH
struct _HARDERROR_MSG
struct _KUSER_SHARED_DATA
struct _MUTANT_BASIC_INFORMATION
struct _NAPDATA
struct _SEMAPHORE_BASIC_INFORMATION
struct _SYSDBG_BUS_DATA
struct _SYSDBG_CONTROL_SPACE
struct _SYSDBG_IO_SPACE
struct _SYSDBG_MSR
struct _SYSDBG_PHYSICAL
struct _SYSDBG_VIRTUAL
struct _SYSTEM_BASIC_INFORMATION
struct _SYSTEM_CALL_COUNT_INFORMATION
struct _SYSTEM_DEVICE_INFORMATION
struct _SYSTEM_EXCEPTION_INFORMATION
struct _SYSTEM_EXTENDED_THREAD_INFORMATION
struct _SYSTEM_FIRMWARE_TABLE_HANDLER
struct _SYSTEM_FIRMWARE_TABLE_INFORMATION
struct _SYSTEM_GDI_DRIVER_INFORMATION
struct _SYSTEM_KERNEL_DEBUGGER_INFORMATION
struct _SYSTEM_LEGACY_DRIVER_INFORMATION
struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION
struct _SYSTEM_LOOKASIDE_INFORMATION
struct _SYSTEM_MEMORY_INFO
struct _SYSTEM_MEMORY_INFORMATION
struct _SYSTEM_NUMA_INFORMATION
struct _SYSTEM_PERFORMANCE_INFORMATION
struct _SYSTEM_PROCESS_INFORMATION
struct _SYSTEM_PROCESSOR_IDLE_INFORMATION
struct _SYSTEM_PROCESSOR_INFORMATION
struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION
struct _SYSTEM_PROCESSOR_POWER_INFORMATION
struct _SYSTEM_QUERY_TIME_ADJUST_INFORMATION
struct _SYSTEM_REGISTRY_QUOTA_INFORMATION
struct _SYSTEM_SESSION_PROCESS_INFORMATION
struct _SYSTEM_SET_TIME_ADJUST_INFORMATION
struct _SYSTEM_THREAD_INFORMATION
struct _SYSTEM_TIMEOFDAY_INFORMATION
struct _SYSTEM_VDM_INSTEMUL_INFO
struct _TIMER_BASIC_INFORMATION
struct _VARIABLE_NAME
struct _VARIABLE_NAME_AND_VALUE
struct _WINDOWS_OS_OPTIONS
Macros
#define BOOT_ENTRY_ATTRIBUTE_ACTIVE 0x00000001
#define BOOT_ENTRY_ATTRIBUTE_DEFAULT 0x00000002
#define BOOT_ENTRY_ATTRIBUTE_REMOVABLE_MEDIA 0x00000008
#define BOOT_ENTRY_ATTRIBUTE_VALID_BITS
#define BOOT_ENTRY_ATTRIBUTE_WINDOWS 0x00000004
#define BOOT_ENTRY_VERSION 1
#define BOOT_OPTIONS_FIELD_COUNTDOWN 0x00000001
#define BOOT_OPTIONS_FIELD_HEADLESS_REDIRECTION 0x00000004
#define BOOT_OPTIONS_FIELD_HEADLESS_REDIRECTION 0x00000004
#define BOOT_OPTIONS_FIELD_NEXT_BOOT_ENTRY_ID 0x00000002
#define BOOT_OPTIONS_FIELD_NEXT_BOOT_ENTRY_ID 0x00000002
#define BOOT_OPTIONS_FIELD_TIMEOUT 0x00000001
#define BOOT_OPTIONS_VERSION 1
#define CACHE_FULLY_ASSOCIATIVE 0xFF
#define DOSDEVICE_DRIVE_CALCULATE 1
#define DOSDEVICE_DRIVE_CDROM 5
#define DOSDEVICE_DRIVE_FIXED 3
#define DOSDEVICE_DRIVE_RAMDISK 6
#define DOSDEVICE_DRIVE_REMOTE 4
#define DOSDEVICE_DRIVE_REMOVABLE 2
#define DOSDEVICE_DRIVE_UNKNOWN 0
#define DRIVER_VERIFIER_DEADLOCK_DETECTION 0x0020
#define DRIVER_VERIFIER_DMA_VERIFIER 0x0080
#define DRIVER_VERIFIER_ENHANCED_IO_CHECKING 0x0040
#define DRIVER_VERIFIER_EXPOSE_IRP_HISTORY 0x0400
#define DRIVER_VERIFIER_FORCE_IRQL_CHECKING 0x0002
#define DRIVER_VERIFIER_HARDWARE_VERIFICATION 0x0100
#define DRIVER_VERIFIER_INJECT_ALLOCATION_FAILURES 0x0004
#define DRIVER_VERIFIER_IO_CHECKING 0x0010
#define DRIVER_VERIFIER_SPECIAL_POOLING 0x0001
#define DRIVER_VERIFIER_SYSTEM_BIOS_VERIFICATION 0x0200
#define DRIVER_VERIFIER_TRACK_POOL_ALLOCATIONS 0x0008
#define EFI_DRIVER_ENTRY_VERSION 1
#define EVENT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define EVENT_MODIFY_STATE 0x0002
#define EVENT_PAIR_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE)
#define EVENT_QUERY_STATE 0x0001
#define FILE_PATH_TYPE_ARC 1
#define FILE_PATH_TYPE_ARC_SIGNATURE 2
#define FILE_PATH_TYPE_EFI 4
#define FILE_PATH_TYPE_MAX FILE_PATH_TYPE_EFI
#define FILE_PATH_TYPE_MIN FILE_PATH_TYPE_ARC
#define FILE_PATH_TYPE_NT 3
#define FILE_PATH_VERSION 1
#define FLG_APPLICATION_VERIFIER 0x00000100
#define FLG_BOOTONLY_VALID_BITS
#define FLG_CRITSEC_EVENT_CREATION 0x10000000
#define FLG_DEBUG_INITIAL_COMMAND 0x00000004
#define FLG_DEBUG_INITIAL_COMMAND_EX 0x04000000
#define FLG_DISABLE_DBGPRINT 0x08000000
#define FLG_DISABLE_PAGE_KERNEL_STACKS 0x00080000
#define FLG_DISABLE_PROTDLLS 0x80000000
#define FLG_DISABLE_STACK_EXTENSION 0x00010000
#define FLG_ENABLE_CLOSE_EXCEPTIONS 0x00400000
#define FLG_ENABLE_CSRDEBUG 0x00020000
#define FLG_ENABLE_EXCEPTION_LOGGING 0x00800000
#define FLG_ENABLE_HANDLE_EXCEPTIONS 0x40000000
#define FLG_ENABLE_HANDLE_TYPE_TAGGING 0x01000000
#define FLG_ENABLE_KDEBUG_SYMBOL_LOAD 0x00040000
#define FLG_ENABLE_SYSTEM_CRIT_BREAKS 0x00100000
#define FLG_HEAP_DISABLE_COALESCING 0x00200000
#define FLG_HEAP_ENABLE_FREE_CHECK 0x00000020
#define FLG_HEAP_ENABLE_TAG_BY_DLL 0x00008000
#define FLG_HEAP_ENABLE_TAGGING 0x00000800
#define FLG_HEAP_ENABLE_TAIL_CHECK 0x00000010
#define FLG_HEAP_PAGE_ALLOCS 0x02000000
#define FLG_HEAP_VALIDATE_ALL 0x00000080
#define FLG_HEAP_VALIDATE_PARAMETERS 0x00000040
#define FLG_KERNEL_STACK_TRACE_DB 0x00002000
#define FLG_KERNELMODE_VALID_BITS
#define FLG_LDR_TOP_DOWN 0x20000000
#define FLG_MAINTAIN_OBJECT_TYPELIST 0x00004000
#define FLG_POOL_ENABLE_TAGGING 0x00000400
#define FLG_SHOW_LDR_SNAPS 0x00000002
#define FLG_STOP_ON_EXCEPTION 0x00000001
#define FLG_STOP_ON_HUNG_GUI 0x00000008
#define FLG_USER_STACK_TRACE_DB 0x00001000
#define FLG_USERMODE_VALID_BITS
#define FLG_VALID_BITS 0xFFFFFDFF
#define HARDERROR_FLAGS_DEFDESKTOPONLY 0x00020000
#define HARDERROR_OVERRIDE_ERRORMODE 0x10000000
#define HARDERROR_PARAMETERS_FLAGSPOS 4
#define KEYEDEVENT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | KEYEDEVENT_WAIT | KEYEDEVENT_WAKE)
#define KEYEDEVENT_WAIT 0x0001
#define KEYEDEVENT_WAKE 0x0002
#define LTP_PC_SMT 0x1
#define MAX_WOW64_SHARED_ENTRIES 16
#define MAXIMUM_HARDERROR_PARAMETERS 5
#define MAXIMUM_NUMA_NODES 16
#define MUTANT_ALL_ACCESS
#define MUTANT_QUERY_STATE 0x0001
#define NX_SUPPORT_POLICY_ALWAYSOFF 0
#define NX_SUPPORT_POLICY_ALWAYSON 1
#define NX_SUPPORT_POLICY_OPTIN 2
#define NX_SUPPORT_POLICY_OPTOUT 3
#define PF_3DNOW_INSTRUCTIONS_AVAILABLE 7
#define PF_ALPHA_BYTE_INSTRUCTIONS 5
#define PF_COMPARE_EXCHANGE_DOUBLE 2
#define PF_FLOATING_POINT_EMULATED 1
#define PF_FLOATING_POINT_PRECISION_ERRATA 0
#define PF_MMX_INSTRUCTIONS_AVAILABLE 3
#define PF_NX_ENABLED 12
#define PF_PAE_ENABLED 9
#define PF_PPC_MOVEMEM_64BIT_OK 4
#define PF_RDTSC_INSTRUCTION_AVAILABLE 8
#define PF_SSE_DAZ_MODE_AVAILABLE 11
#define PF_XMMI64_INSTRUCTIONS_AVAILABLE 10
#define PF_XMMI_INSTRUCTIONS_AVAILABLE 6
#define PROCESSOR_ALPHA_21064 21064
#define PROCESSOR_AMD_X8664 8664
#define PROCESSOR_ARCHITECTURE_ALPHA 2
#define PROCESSOR_ARCHITECTURE_ALPHA64 7
#define PROCESSOR_ARCHITECTURE_AMD64 9
#define PROCESSOR_ARCHITECTURE_ARM 5
#define PROCESSOR_ARCHITECTURE_IA32_ON_WIN64 10
#define PROCESSOR_ARCHITECTURE_IA64 6
#define PROCESSOR_ARCHITECTURE_INTEL 0
#define PROCESSOR_ARCHITECTURE_MIPS 1
#define PROCESSOR_ARCHITECTURE_MSIL 8
#define PROCESSOR_ARCHITECTURE_PPC 3
#define PROCESSOR_ARCHITECTURE_SHX 4
#define PROCESSOR_ARCHITECTURE_UNKNOWN 0xFFFF
#define PROCESSOR_ARM720 1824
#define PROCESSOR_ARM820 2080
#define PROCESSOR_ARM920 2336
#define PROCESSOR_ARM_7TDMI 70001
#define PROCESSOR_FEATURE_MAX 64
#define PROCESSOR_HITACHI_SH3 10003
#define PROCESSOR_HITACHI_SH3E 10004
#define PROCESSOR_HITACHI_SH4 10005
#define PROCESSOR_INTEL_386 386
#define PROCESSOR_INTEL_486 486
#define PROCESSOR_INTEL_IA64 2200
#define PROCESSOR_INTEL_PENTIUM 586
#define PROCESSOR_MIPS_R4000 4000
#define PROCESSOR_MOTOROLA_821 821
#define PROCESSOR_OPTIL 0x494f
#define PROCESSOR_PPC_601 601
#define PROCESSOR_PPC_603 603
#define PROCESSOR_PPC_604 604
#define PROCESSOR_PPC_620 620
#define PROCESSOR_SHx_SH3 103
#define PROCESSOR_SHx_SH4 104
#define PROCESSOR_STRONGARM 2577
#define PROFILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | PROFILE_CONTROL)
#define PROFILE_CONTROL 0x0001
#define SEMAPHORE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
#define SEMAPHORE_MODIFY_STATE 0x0002
#define SEMAPHORE_QUERY_STATE 0x0001
#define TIME_ZONE_ID_DAYLIGHT 2
#define TIME_ZONE_ID_STANDARD 1
#define TIME_ZONE_ID_UNKNOWN 0
#define TIMER_ALL_ACCESS
#define TIMER_MODIFY_STATE 0x0002
#define TIMER_QUERY_STATE 0x0001
#define VARIABLE_ATTRIBUTE_NON_VOLATILE 0x00000001
#define VARIABLE_INFORMATION_NAMES 1
#define VARIABLE_INFORMATION_VALUES 2
#define WINDOWS_OS_OPTIONS_SIGNATURE "WINDOWS"
#define WINDOWS_OS_OPTIONS_VERSION 1
Typedefs
typedef enum _ALTERNATIVE_ARCHITECTURE_TYPE ALTERNATIVE_ARCHITECTURE_TYPE
typedef struct _ATOM_BASIC_INFORMATION ATOM_BASIC_INFORMATION
typedef enum _ATOM_INFORMATION_CLASS ATOM_INFORMATION_CLASS
typedef struct _ATOM_TABLE_INFORMATION ATOM_TABLE_INFORMATION
typedef struct _BOOT_ENTRY BOOT_ENTRY
typedef struct _BOOT_ENTRY_LIST BOOT_ENTRY_LIST
typedef struct _BOOT_OPTIONS BOOT_OPTIONS
typedef struct _CACHE_DESCRIPTOR CACHE_DESCRIPTOR
typedef struct _DRIVER_VERIFIER_THUNK_PAIRS DRIVER_VERIFIER_THUNK_PAIRS
typedef struct _EFI_DRIVER_ENTRY EFI_DRIVER_ENTRY
typedef struct _EFI_DRIVER_ENTRY_LIST EFI_DRIVER_ENTRY_LIST
typedef struct _EVENT_BASIC_INFORMATION EVENT_BASIC_INFORMATION
typedef enum _EVENT_INFORMATION_CLASS EVENT_INFORMATION_CLASS
typedef struct _FILE_PATH FILE_PATH
typedef struct _HARDERROR_MSG HARDERROR_MSG
typedef enum _HARDERROR_RESPONSE HARDERROR_RESPONSE
typedef enum _HARDERROR_RESPONSE_OPTION HARDERROR_RESPONSE_OPTION
typedef struct _KUSER_SHARED_DATA KUSER_SHARED_DATA
typedef enum _LOGICAL_PROCESSOR_RELATIONSHIP LOGICAL_PROCESSOR_RELATIONSHIP
typedef struct _MUTANT_BASIC_INFORMATION MUTANT_BASIC_INFORMATION
typedef enum _MUTANT_INFORMATION_CLASS MUTANT_INFORMATION_CLASS
typedef struct _NAPDATA NAPDATA
typedef struct _ATOM_BASIC_INFORMATION * PATOM_BASIC_INFORMATION
typedef struct _ATOM_TABLE_INFORMATION * PATOM_TABLE_INFORMATION
typedef struct _BOOT_ENTRY * PBOOT_ENTRY
typedef struct _BOOT_ENTRY_LIST * PBOOT_ENTRY_LIST
typedef struct _BOOT_OPTIONS * PBOOT_OPTIONS
typedef struct _CACHE_DESCRIPTOR * PCACHE_DESCRIPTOR
typedef struct _DRIVER_VERIFIER_THUNK_PAIRS * PDRIVER_VERIFIER_THUNK_PAIRS
typedef ULONG_PTR(* PDRIVER_VERIFIER_THUNK_ROUTINE) (IN PVOID Context)
typedef struct _EFI_DRIVER_ENTRY * PEFI_DRIVER_ENTRY
typedef struct _EFI_DRIVER_ENTRY_LIST * PEFI_DRIVER_ENTRY_LIST
typedef struct _EVENT_BASIC_INFORMATION * PEVENT_BASIC_INFORMATION
typedef struct _FILE_PATH * PFILE_PATH
typedef NTSTATUS(__cdecl * PFNFTH) (PSYSTEM_FIRMWARE_TABLE_INFORMATION)
typedef struct _HARDERROR_MSG * PHARDERROR_MSG
typedef struct _KUSER_SHARED_DATA * PKUSER_SHARED_DATA
typedef struct _MUTANT_BASIC_INFORMATION * PMUTANT_BASIC_INFORMATION
typedef struct _NAPDATA * PNAPDATA
typedef enum _PROCESSOR_CACHE_TYPE PROCESSOR_CACHE_TYPE
typedef USHORT * PRTL_ATOM
typedef struct _SEMAPHORE_BASIC_INFORMATION * PSEMAPHORE_BASIC_INFORMATION
typedef struct _SYSDBG_BUS_DATA * PSYSDBG_BUS_DATA
typedef enum _SYSDBG_COMMAND * PSYSDBG_COMMAND
typedef struct _SYSDBG_CONTROL_SPACE * PSYSDBG_CONTROL_SPACE
typedef struct _SYSDBG_IO_SPACE * PSYSDBG_IO_SPACE
typedef struct _SYSDBG_MSR * PSYSDBG_MSR
typedef struct _SYSDBG_PHYSICAL * PSYSDBG_PHYSICAL
typedef struct _SYSDBG_VIRTUAL * PSYSDBG_VIRTUAL
typedef struct _SYSTEM_BASIC_INFORMATION * PSYSTEM_BASIC_INFORMATION
typedef struct _SYSTEM_CALL_COUNT_INFORMATION * PSYSTEM_CALL_COUNT_INFORMATION
typedef struct _SYSTEM_DEVICE_INFORMATION * PSYSTEM_DEVICE_INFORMATION
typedef struct _SYSTEM_EXCEPTION_INFORMATION * PSYSTEM_EXCEPTION_INFORMATION
typedef struct _SYSTEM_EXTENDED_THREAD_INFORMATION * PSYSTEM_EXTENDED_THREAD_INFORMATION
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER * PSYSTEM_FIRMWARE_TABLE_HANDLER
typedef struct _SYSTEM_FIRMWARE_TABLE_INFORMATION * PSYSTEM_FIRMWARE_TABLE_INFORMATION
typedef struct _SYSTEM_GDI_DRIVER_INFORMATION * PSYSTEM_GDI_DRIVER_INFORMATION
typedef struct _SYSTEM_KERNEL_DEBUGGER_INFORMATION * PSYSTEM_KERNEL_DEBUGGER_INFORMATION
typedef struct _SYSTEM_LEGACY_DRIVER_INFORMATION * PSYSTEM_LEGACY_DRIVER_INFORMATION
typedef struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION * PSYSTEM_LOGICAL_PROCESSOR_INFORMATION
typedef struct _SYSTEM_LOOKASIDE_INFORMATION * PSYSTEM_LOOKASIDE_INFORMATION
typedef struct _SYSTEM_MEMORY_INFO * PSYSTEM_MEMORY_INFO
typedef struct _SYSTEM_MEMORY_INFORMATION * PSYSTEM_MEMORY_INFORMATION
typedef struct _SYSTEM_NUMA_INFORMATION * PSYSTEM_NUMA_INFORMATION
typedef struct _SYSTEM_PERFORMANCE_INFORMATION * PSYSTEM_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESS_INFORMATION * PSYSTEM_PROCESS_INFORMATION
typedef struct _SYSTEM_PROCESSOR_IDLE_INFORMATION * PSYSTEM_PROCESSOR_IDLE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_INFORMATION * PSYSTEM_PROCESSOR_INFORMATION
typedef struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION * PSYSTEM_PROCESSOR_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_POWER_INFORMATION * PSYSTEM_PROCESSOR_POWER_INFORMATION
typedef struct _SYSTEM_QUERY_TIME_ADJUST_INFORMATION * PSYSTEM_QUERY_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_REGISTRY_QUOTA_INFORMATION * PSYSTEM_REGISTRY_QUOTA_INFORMATION
typedef struct _SYSTEM_SESSION_PROCESS_INFORMATION * PSYSTEM_SESSION_PROCESS_INFORMATION
typedef struct _SYSTEM_SET_TIME_ADJUST_INFORMATION * PSYSTEM_SET_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_THREAD_INFORMATION * PSYSTEM_THREAD_INFORMATION
typedef struct _SYSTEM_TIMEOFDAY_INFORMATION * PSYSTEM_TIMEOFDAY_INFORMATION
typedef struct _SYSTEM_VDM_INSTEMUL_INFO * PSYSTEM_VDM_INSTEMUL_INFO
typedef VOID(* PTIMER_APC_ROUTINE) (__in PVOID TimerContext, __in ULONG TimerLowValue, __in LONG TimerHighValue)
typedef struct _TIMER_BASIC_INFORMATION * PTIMER_BASIC_INFORMATION
typedef struct _VARIABLE_NAME * PVARIABLE_NAME
typedef struct _VARIABLE_NAME_AND_VALUE * PVARIABLE_NAME_AND_VALUE
typedef struct _WINDOWS_OS_OPTIONS * PWINDOWS_OS_OPTIONS
typedef USHORT RTL_ATOM
typedef struct _SEMAPHORE_BASIC_INFORMATION SEMAPHORE_BASIC_INFORMATION
typedef enum _SEMAPHORE_INFORMATION_CLASS SEMAPHORE_INFORMATION_CLASS
typedef enum _SHUTDOWN_ACTION SHUTDOWN_ACTION
typedef struct _SYSDBG_BUS_DATA SYSDBG_BUS_DATA
typedef enum _SYSDBG_COMMAND SYSDBG_COMMAND
typedef struct _SYSDBG_CONTROL_SPACE SYSDBG_CONTROL_SPACE
typedef struct _SYSDBG_IO_SPACE SYSDBG_IO_SPACE
typedef struct _SYSDBG_MSR SYSDBG_MSR
typedef struct _SYSDBG_PHYSICAL SYSDBG_PHYSICAL
typedef struct _SYSDBG_VIRTUAL SYSDBG_VIRTUAL
typedef SIZE_T SYSINF_PAGE_COUNT
typedef struct _SYSTEM_BASIC_INFORMATION SYSTEM_BASIC_INFORMATION
typedef struct _SYSTEM_CALL_COUNT_INFORMATION SYSTEM_CALL_COUNT_INFORMATION
typedef struct _SYSTEM_DEVICE_INFORMATION SYSTEM_DEVICE_INFORMATION
typedef struct _SYSTEM_EXCEPTION_INFORMATION SYSTEM_EXCEPTION_INFORMATION
typedef struct _SYSTEM_EXTENDED_THREAD_INFORMATION SYSTEM_EXTENDED_THREAD_INFORMATION
typedef enum _SYSTEM_FIRMWARE_TABLE_ACTION SYSTEM_FIRMWARE_TABLE_ACTION
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER SYSTEM_FIRMWARE_TABLE_HANDLER
typedef struct _SYSTEM_FIRMWARE_TABLE_INFORMATION SYSTEM_FIRMWARE_TABLE_INFORMATION
typedef struct _SYSTEM_GDI_DRIVER_INFORMATION SYSTEM_GDI_DRIVER_INFORMATION
typedef enum _SYSTEM_INFORMATION_CLASS SYSTEM_INFORMATION_CLASS
typedef struct _SYSTEM_KERNEL_DEBUGGER_INFORMATION SYSTEM_KERNEL_DEBUGGER_INFORMATION
typedef struct _SYSTEM_LEGACY_DRIVER_INFORMATION SYSTEM_LEGACY_DRIVER_INFORMATION
typedef struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION SYSTEM_LOGICAL_PROCESSOR_INFORMATION
typedef struct _SYSTEM_LOOKASIDE_INFORMATION SYSTEM_LOOKASIDE_INFORMATION
typedef struct _SYSTEM_MEMORY_INFO SYSTEM_MEMORY_INFO
typedef struct _SYSTEM_MEMORY_INFORMATION SYSTEM_MEMORY_INFORMATION
typedef struct _SYSTEM_NUMA_INFORMATION SYSTEM_NUMA_INFORMATION
typedef struct _SYSTEM_PERFORMANCE_INFORMATION SYSTEM_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESS_INFORMATION SYSTEM_PROCESS_INFORMATION
typedef struct _SYSTEM_PROCESSOR_IDLE_INFORMATION SYSTEM_PROCESSOR_IDLE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_INFORMATION SYSTEM_PROCESSOR_INFORMATION
typedef struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_POWER_INFORMATION SYSTEM_PROCESSOR_POWER_INFORMATION
typedef struct _SYSTEM_QUERY_TIME_ADJUST_INFORMATION SYSTEM_QUERY_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_REGISTRY_QUOTA_INFORMATION SYSTEM_REGISTRY_QUOTA_INFORMATION
typedef struct _SYSTEM_SESSION_PROCESS_INFORMATION SYSTEM_SESSION_PROCESS_INFORMATION
typedef struct _SYSTEM_SET_TIME_ADJUST_INFORMATION SYSTEM_SET_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_THREAD_INFORMATION SYSTEM_THREAD_INFORMATION
typedef struct _SYSTEM_TIMEOFDAY_INFORMATION SYSTEM_TIMEOFDAY_INFORMATION
typedef struct _SYSTEM_VDM_INSTEMUL_INFO SYSTEM_VDM_INSTEMUL_INFO
typedef struct _TIMER_BASIC_INFORMATION TIMER_BASIC_INFORMATION
typedef enum _TIMER_INFORMATION_CLASS TIMER_INFORMATION_CLASS
typedef struct _VARIABLE_NAME VARIABLE_NAME
typedef struct _VARIABLE_NAME_AND_VALUE VARIABLE_NAME_AND_VALUE
typedef struct _WINDOWS_OS_OPTIONS WINDOWS_OS_OPTIONS
Enumerations
enum _ALTERNATIVE_ARCHITECTURE_TYPE { StandardDesign, NEC98x86, EndAlternatives }
enum _ATOM_INFORMATION_CLASS { AtomBasicInformation, AtomTableInformation }
enum _EVENT_INFORMATION_CLASS { EventBasicInformation }
enum _HARDERROR_RESPONSE {
ResponseReturnToCaller, ResponseNotHandled, ResponseAbort, ResponseCancel,
ResponseIgnore, ResponseNo, ResponseOk, ResponseRetry,
ResponseYes, ResponseTryAgain, ResponseContinue
}
enum _HARDERROR_RESPONSE_OPTION {
OptionAbortRetryIgnore, OptionOk, OptionOkCancel, OptionRetryCancel,
OptionYesNo, OptionYesNoCancel, OptionShutdownSystem, OptionOkNoWait,
OptionCancelTryContinue
}
enum _LOGICAL_PROCESSOR_RELATIONSHIP { RelationProcessorCore, RelationNumaNode, RelationCache }
enum _MUTANT_INFORMATION_CLASS { MutantBasicInformation }
enum _PROCESSOR_CACHE_TYPE { CacheUnified, CacheInstruction, CacheData, CacheTrace }
enum _SEMAPHORE_INFORMATION_CLASS { SemaphoreBasicInformation }
enum _SHUTDOWN_ACTION { ShutdownNoReboot, ShutdownReboot, ShutdownPowerOff }
enum _SYSDBG_COMMAND {
SysDbgQueryModuleInformation, SysDbgQueryTraceInformation, SysDbgSetTracepoint, SysDbgSetSpecialCall,
SysDbgClearSpecialCalls, SysDbgQuerySpecialCalls, SysDbgBreakPoint, SysDbgQueryVersion,
SysDbgReadVirtual, SysDbgWriteVirtual, SysDbgReadPhysical, SysDbgWritePhysical,
SysDbgReadControlSpace, SysDbgWriteControlSpace, SysDbgReadIoSpace, SysDbgWriteIoSpace,
SysDbgReadMsr, SysDbgWriteMsr, SysDbgReadBusData, SysDbgWriteBusData,
SysDbgCheckLowMemory, SysDbgEnableKernelDebugger, SysDbgDisableKernelDebugger, SysDbgGetAutoKdEnable,
SysDbgSetAutoKdEnable, SysDbgGetPrintBufferSize, SysDbgSetPrintBufferSize, SysDbgGetKdUmExceptionEnable,
SysDbgSetKdUmExceptionEnable, SysDbgGetTriageDump, SysDbgGetKdBlockEnable, SysDbgSetKdBlockEnable
}
enum _SYSTEM_FIRMWARE_TABLE_ACTION { SystemFirmwareTable_Enumerate, SystemFirmwareTable_Get }
enum _SYSTEM_INFORMATION_CLASS {
SystemBasicInformation, SystemProcessorInformation, SystemPerformanceInformation, SystemTimeOfDayInformation,
SystemPathInformation, SystemProcessInformation, SystemCallCountInformation, SystemDeviceInformation,
SystemProcessorPerformanceInformation, SystemFlagsInformation, SystemCallTimeInformation, SystemModuleInformation,
SystemLocksInformation, SystemStackTraceInformation, SystemPagedPoolInformation, SystemNonPagedPoolInformation,
SystemHandleInformation, SystemObjectInformation, SystemPageFileInformation, SystemVdmInstemulInformation,
SystemVdmBopInformation, SystemFileCacheInformation, SystemPoolTagInformation, SystemInterruptInformation,
SystemDpcBehaviorInformation, SystemFullMemoryInformation, SystemLoadGdiDriverInformation, SystemUnloadGdiDriverInformation,
SystemTimeAdjustmentInformation, SystemSummaryMemoryInformation, SystemMirrorMemoryInformation, SystemPerformanceTraceInformation,
SystemObsolete0, SystemExceptionInformation, SystemCrashDumpStateInformation, SystemKernelDebuggerInformation,
SystemContextSwitchInformation, SystemRegistryQuotaInformation, SystemExtendServiceTableInformation, SystemPrioritySeperation,
SystemVerifierAddDriverInformation, SystemVerifierRemoveDriverInformation, SystemProcessorIdleInformation, SystemLegacyDriverInformation,
SystemCurrentTimeZoneInformation, SystemLookasideInformation, SystemTimeSlipNotification, SystemSessionCreate,
SystemSessionDetach, SystemSessionInformation, SystemRangeStartInformation, SystemVerifierInformation,
SystemVerifierThunkExtend, SystemSessionProcessInformation, SystemLoadGdiDriverInSystemSpace, SystemNumaProcessorMap,
SystemPrefetcherInformation, SystemExtendedProcessInformation, SystemRecommendedSharedDataAlignment, SystemComPlusPackage,
SystemNumaAvailableMemory, SystemProcessorPowerInformation, SystemEmulationBasicInformation, SystemEmulationProcessorInformation,
SystemExtendedHandleInformation, SystemLostDelayedWriteInformation, SystemBigPoolInformation, SystemSessionPoolTagInformation,
SystemSessionMappedViewInformation, SystemHotpatchInformation, SystemObjectSecurityMode, SystemWatchdogTimerHandler,
SystemWatchdogTimerInformation, SystemLogicalProcessorInformation, SystemWow64SharedInformation, SystemRegisterFirmwareTableInformationHandler,
SystemFirmwareTableInformation, SystemModuleInformationEx, SystemVerifierTriageInformation, SystemSuperfetchInformation,
SystemMemoryListInformation, SystemFileCacheInformationEx, MaxSystemInfoClass
}
enum _TIMER_INFORMATION_CLASS { TimerBasicInformation }
Functions
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TickCountMultiplier)==0x4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, InterruptTime)==0x8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemTime)==0x14)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TimeZoneBias)==0x20)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ImageNumberLow)==0x2C)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ImageNumberHigh)==0x2E)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtSystemRoot)==0x30)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, MaxStackTraceDepth)==0x238)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, CryptoExponent)==0x23C)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TimeZoneId)==0x240)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, LargePageMinimum)==0x244)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Reserved2)==0x248)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtProductType)==0x264)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ProductTypeIsValid)==0x268)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtMajorVersion)==0x26C)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtMinorVersion)==0x270)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ProcessorFeatures)==0x274)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Reserved1)==0x2B4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Reserved3)==0x2B8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TimeSlip)==0x2BC)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, AlternativeArchitecture)==0x2C0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemExpirationDate)==0x2C8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SuiteMask)==0x2D0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, KdDebuggerEnabled)==0x2D4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NXSupportPolicy)==0x2D5)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ActiveConsoleId)==0x2D8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, DismountCount)==0x2DC)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ComPlusPackage)==0x2E0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, LastSystemRITEventTickCount)==0x2E4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NumberOfPhysicalPages)==0x2E8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SafeBootMode)==0x2EC)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TraceLogging)==0x2F0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TestRetInstruction)==0x2F8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemCall)==0x300)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemCallReturn)==0x304)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemCallPad)==0x308)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TickCount)==0x320)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TickCountQuad)==0x320)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Wow64SharedInformation)==0x334)
NTSTATUS NapClearData (VOID)
NTSTATUS NapGetApiCount (OUT PULONG NapApiCount)
NTSTATUS NapPause (VOID)
NTSTATUS NapResume (VOID)
NTSTATUS NapRetrieveData (OUT NAPDATA *NapApiData, OUT PCHAR **NapApiNames, OUT PLARGE_INTEGER *NapCounterFrequency)
NTSYSCALLAPI NTSTATUS NTAPI NtAddAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
NTSYSCALLAPI NTSTATUS NTAPI NtAddBootEntry (__in PBOOT_ENTRY BootEntry, __out_opt PULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtAddDriverEntry (__in PEFI_DRIVER_ENTRY DriverEntry, __out_opt PULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateLocallyUniqueId (__out PLUID Luid)
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateUuids (__out PULARGE_INTEGER Time, __out PULONG Range, __out PULONG Sequence, __out PCHAR Seed)
NTSYSCALLAPI NTSTATUS NTAPI NtCancelTimer (__in HANDLE TimerHandle, __out_opt PBOOLEAN CurrentState)
NTSYSCALLAPI NTSTATUS NTAPI NtClearEvent (__in HANDLE EventHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in EVENT_TYPE EventType, __in BOOLEAN InitialState)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Flags)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN InitialOwner)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateProfile (__out PHANDLE ProfileHandle, __in HANDLE Process OPTIONAL, __in PVOID ProfileBase, __in SIZE_T ProfileSize, __in ULONG BucketSize, __in PULONG Buffer, __in ULONG BufferSize, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY Affinity)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in LONG InitialCount, __in LONG MaximumCount)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in TIMER_TYPE TimerType)
NTSYSCALLAPI NTSTATUS NTAPI NtDelayExecution (__in BOOLEAN Alertable, __in PLARGE_INTEGER DelayInterval)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteAtom (__in RTL_ATOM Atom)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteBootEntry (__in ULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteDriverEntry (__in ULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtDisplayString (__in PUNICODE_STRING String)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateBootEntries (__out_bcount_opt(*BufferLength) PVOID Buffer, __inout PULONG BufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateDriverEntries (__out_bcount(*BufferLength) PVOID Buffer, __inout PULONG BufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateSystemEnvironmentValuesEx (__in ULONG InformationClass, __out PVOID Buffer, __inout PULONG BufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtFindAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
NTSYSCALLAPI NTSTATUS NTAPI NtModifyBootEntry (__in PBOOT_ENTRY BootEntry)
NTSYSCALLAPI NTSTATUS NTAPI NtModifyDriverEntry (__in PEFI_DRIVER_ENTRY DriverEntry)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtPulseEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryBootEntryOrder (__out_ecount_opt(*Count) PULONG Ids, __inout PULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryBootOptions (__out_bcount_opt(*BootOptionsLength) PBOOT_OPTIONS BootOptions, __inout PULONG BootOptionsLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDefaultLocale (__in BOOLEAN UserProfile, __out PLCID DefaultLocaleId)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDefaultUILanguage (__out LANGID *DefaultUILanguageId)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDriverEntryOrder (__out_ecount(*Count) PULONG Ids, __inout PULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryEvent (__in HANDLE EventHandle, __in EVENT_INFORMATION_CLASS EventInformationClass, __out_bcount(EventInformationLength) PVOID EventInformation, __in ULONG EventInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationAtom (__in RTL_ATOM Atom, __in ATOM_INFORMATION_CLASS AtomInformationClass, __out_bcount(AtomInformationLength) PVOID AtomInformation, __in ULONG AtomInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInstallUILanguage (__out LANGID *InstallUILanguageId)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryIntervalProfile (__in KPROFILE_SOURCE ProfileSource, __out PULONG Interval)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryMutant (__in HANDLE MutantHandle, __in MUTANT_INFORMATION_CLASS MutantInformationClass, __out_bcount(MutantInformationLength) PVOID MutantInformation, __in ULONG MutantInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryPerformanceCounter (__out PLARGE_INTEGER PerformanceCounter, __out_opt PLARGE_INTEGER PerformanceFrequency)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySemaphore (__in HANDLE SemaphoreHandle, __in SEMAPHORE_INFORMATION_CLASS SemaphoreInformationClass, __out_bcount(SemaphoreInformationLength) PVOID SemaphoreInformation, __in ULONG SemaphoreInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemEnvironmentValue (__in PUNICODE_STRING VariableName, __out_bcount(ValueLength) PWSTR VariableValue, __in USHORT ValueLength, __out_opt PUSHORT ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemEnvironmentValueEx (__in PUNICODE_STRING VariableName, __in LPGUID VendorGuid, __out_bcount_opt(*ValueLength) PVOID Value, __inout PULONG ValueLength, __out_opt PULONG Attributes)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __out_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemTime (__out PLARGE_INTEGER SystemTime)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryTimer (__in HANDLE TimerHandle, __in TIMER_INFORMATION_CLASS TimerInformationClass, __out_bcount(TimerInformationLength) PVOID TimerInformation, __in ULONG TimerInformationLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryTimerResolution (__out PULONG MaximumTime, __out PULONG MinimumTime, __out PULONG CurrentTime)
NTSYSCALLAPI NTSTATUS NTAPI NtRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
NTSYSCALLAPI NTSTATUS NTAPI NtReleaseKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtReleaseMutant (__in HANDLE MutantHandle, __out_opt PLONG PreviousCount)
NTSYSCALLAPI NTSTATUS NTAPI NtReleaseSemaphore (__in HANDLE SemaphoreHandle, __in LONG ReleaseCount, __out_opt PLONG PreviousCount)
NTSYSCALLAPI NTSTATUS NTAPI NtResetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
NTSYSCALLAPI NTSTATUS NTAPI NtSetBootEntryOrder (__in_ecount(Count) PULONG Ids, __in ULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtSetBootOptions (__in PBOOT_OPTIONS BootOptions, __in ULONG FieldsToChange)
NTSYSCALLAPI NTSTATUS NTAPI NtSetDefaultHardErrorPort (__in HANDLE DefaultHardErrorPort)
NTSYSCALLAPI NTSTATUS NTAPI NtSetDefaultLocale (__in BOOLEAN UserProfile, __in LCID DefaultLocaleId)
NTSYSCALLAPI NTSTATUS NTAPI NtSetDefaultUILanguage (__in LANGID DefaultUILanguageId)
NTSYSCALLAPI NTSTATUS NTAPI NtSetDriverEntryOrder (__in_ecount(Count) PULONG Ids, __in ULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtSetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
NTSYSCALLAPI NTSTATUS NTAPI NtSetEventBoostPriority (__in HANDLE EventHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSetHighEventPair (__in HANDLE EventPairHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSetHighWaitLowEventPair (__in HANDLE EventPairHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
NTSYSCALLAPI NTSTATUS NTAPI NtSetLowEventPair (__in HANDLE EventPairHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSetLowWaitHighEventPair (__in HANDLE EventPairHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemEnvironmentValue (__in PUNICODE_STRING VariableName, __in PUNICODE_STRING VariableValue)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemEnvironmentValueEx (__in PUNICODE_STRING VariableName, __in LPGUID VendorGuid, __in_bcount_opt(ValueLength) PVOID Value, __in ULONG ValueLength, __in ULONG Attributes)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __in_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemTime (__in_opt PLARGE_INTEGER SystemTime, __out_opt PLARGE_INTEGER PreviousTime)
NTSYSCALLAPI NTSTATUS NTAPI NtSetTimer (__in HANDLE TimerHandle, __in PLARGE_INTEGER DueTime, __in_opt PTIMER_APC_ROUTINE TimerApcRoutine, __in_opt PVOID TimerContext, __in BOOLEAN ResumeTimer, __in_opt LONG Period, __out_opt PBOOLEAN PreviousState)
NTSYSCALLAPI NTSTATUS NTAPI NtSetTimerResolution (__in ULONG DesiredTime, __in BOOLEAN SetResolution, __out PULONG ActualTime)
NTSYSCALLAPI NTSTATUS NTAPI NtSetUuidSeed (__in PCHAR Seed)
NTSYSCALLAPI NTSTATUS NTAPI NtShutdownSystem (__in SHUTDOWN_ACTION Action)
NTSYSCALLAPI NTSTATUS NTAPI NtStartProfile (__in HANDLE ProfileHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtStopProfile (__in HANDLE ProfileHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtSystemDebugControl (__in SYSDBG_COMMAND Command, __inout_bcount_opt(InputBufferLength) PVOID InputBuffer, __in ULONG InputBufferLength, __out_bcount_opt(OutputBufferLength) PVOID OutputBuffer, __in ULONG OutputBufferLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtTranslateFilePath (__in PFILE_PATH InputFilePath, __in ULONG OutputType, __out_bcount_opt(*OutputFilePathLength) PFILE_PATH OutputFilePath, __inout_opt PULONG OutputFilePathLength)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitHighEventPair (__in HANDLE EventPairHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitLowEventPair (__in HANDLE EventPairHandle)
Macro Definition Documentation
#define BOOT_ENTRY_ATTRIBUTE_ACTIVE 0x00000001
Definition at line 171 of file ntexapi.h.
#define BOOT_ENTRY_ATTRIBUTE_DEFAULT 0x00000002
Definition at line 172 of file ntexapi.h.
#define BOOT_ENTRY_ATTRIBUTE_REMOVABLE_MEDIA 0x00000008
Definition at line 174 of file ntexapi.h.
#define BOOT_ENTRY_ATTRIBUTE_VALID_BITS
Value:
(\
            BOOT_ENTRY_ATTRIBUTE_ACTIVE  | \
            BOOT_ENTRY_ATTRIBUTE_DEFAULT   \
            )
Definition at line 176 of file ntexapi.h.
#define BOOT_ENTRY_ATTRIBUTE_WINDOWS 0x00000004
Definition at line 173 of file ntexapi.h.
#define BOOT_ENTRY_VERSION 1
Definition at line 169 of file ntexapi.h.
#define BOOT_OPTIONS_FIELD_COUNTDOWN 0x00000001
Definition at line 263 of file ntexapi.h.
#define BOOT_OPTIONS_FIELD_HEADLESS_REDIRECTION 0x00000004
Definition at line 265 of file ntexapi.h.
#define BOOT_OPTIONS_FIELD_HEADLESS_REDIRECTION 0x00000004
Definition at line 265 of file ntexapi.h.
#define BOOT_OPTIONS_FIELD_NEXT_BOOT_ENTRY_ID 0x00000002
Definition at line 264 of file ntexapi.h.
#define BOOT_OPTIONS_FIELD_NEXT_BOOT_ENTRY_ID 0x00000002
Definition at line 264 of file ntexapi.h.
#define BOOT_OPTIONS_FIELD_TIMEOUT 0x00000001
Definition at line 192 of file ntexapi.h.
#define BOOT_OPTIONS_VERSION 1
Definition at line 190 of file ntexapi.h.
#define CACHE_FULLY_ASSOCIATIVE 0xFF
Definition at line 1269 of file ntexapi.h.
Referenced by KiSetCacheInformation(), KiSetCacheInformationAmd(), and KiSetCacheInformationIntel().
#define DOSDEVICE_DRIVE_CALCULATE 1
Definition at line 2496 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink(), and ObQueryDeviceMapInformation().
#define DOSDEVICE_DRIVE_CDROM 5
Definition at line 2500 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink().
#define DOSDEVICE_DRIVE_FIXED 3
Definition at line 2498 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink().
#define DOSDEVICE_DRIVE_RAMDISK 6
Definition at line 2501 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink().
#define DOSDEVICE_DRIVE_REMOTE 4
Definition at line 2499 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink(), and ObQueryDeviceMapInformation().
#define DOSDEVICE_DRIVE_REMOVABLE 2
Definition at line 2497 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink().
#define DOSDEVICE_DRIVE_UNKNOWN 0
Definition at line 2495 of file ntexapi.h.
Referenced by ObpProcessDosDeviceSymbolicLink().
#define DRIVER_VERIFIER_DEADLOCK_DETECTION 0x0020
Definition at line 1039 of file ntexapi.h.
Referenced by MmFreeContiguousMemory(), and MmUnloadSystemImage().
#define DRIVER_VERIFIER_DMA_VERIFIER 0x0080
Definition at line 1041 of file ntexapi.h.
#define DRIVER_VERIFIER_ENHANCED_IO_CHECKING 0x0040
Definition at line 1040 of file ntexapi.h.
#define DRIVER_VERIFIER_EXPOSE_IRP_HISTORY 0x0400
Definition at line 1044 of file ntexapi.h.
#define DRIVER_VERIFIER_FORCE_IRQL_CHECKING 0x0002
Definition at line 1032 of file ntexapi.h.
#define DRIVER_VERIFIER_HARDWARE_VERIFICATION 0x0100
Definition at line 1042 of file ntexapi.h.
#define DRIVER_VERIFIER_INJECT_ALLOCATION_FAILURES 0x0004
Definition at line 1033 of file ntexapi.h.
#define DRIVER_VERIFIER_IO_CHECKING 0x0010
Definition at line 1035 of file ntexapi.h.
#define DRIVER_VERIFIER_SPECIAL_POOLING 0x0001
Definition at line 1031 of file ntexapi.h.
#define DRIVER_VERIFIER_SYSTEM_BIOS_VERIFICATION 0x0200
Definition at line 1043 of file ntexapi.h.
#define DRIVER_VERIFIER_TRACK_POOL_ALLOCATIONS 0x0008
Definition at line 1034 of file ntexapi.h.
#define EFI_DRIVER_ENTRY_VERSION 1
Definition at line 296 of file ntexapi.h.
#define EVENT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
Definition at line 381 of file ntexapi.h.
Referenced by CmpCreateEvent(), ExpEventInitialization(), IoCreateNotificationEvent(), IoCreateSynchronizationEvent(), IoInitSystem(), and MiCreateMemoryEvent().
#define EVENT_MODIFY_STATE 0x0002
Definition at line 380 of file ntexapi.h.
Referenced by BuildQueryDirectoryIrp(), IopXxxControlFile(), MiCreateMemoryEvent(), NtClearEvent(), NtLockFile(), NtNotifyChangeDirectoryFile(), NtNotifyChangeMultipleKeys(), NtPulseEvent(), NtReadFile(), NtReadFileScatter(), NtResetEvent(), NtSetEvent(), NtSetEventBoostPriority(), NtSetSystemInformation(), NtSignalAndWaitForSingleObject(), NtUnloadKeyEx(), NtWriteFile(), NtWriteFileGather(), and SeRmInitPhase1().
#define EVENT_PAIR_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE)
Definition at line 479 of file ntexapi.h.
Referenced by ExpEventPairInitialization().
#define EVENT_QUERY_STATE 0x0001
Definition at line 379 of file ntexapi.h.
Referenced by MiCreateMemoryEvent(), and NtQueryEvent().
#define FILE_PATH_TYPE_ARC 1
Definition at line 135 of file ntexapi.h.
#define FILE_PATH_TYPE_ARC_SIGNATURE 2
Definition at line 136 of file ntexapi.h.
#define FILE_PATH_TYPE_EFI 4
Definition at line 138 of file ntexapi.h.
#define FILE_PATH_TYPE_MAX FILE_PATH_TYPE_EFI
Definition at line 141 of file ntexapi.h.
#define FILE_PATH_TYPE_MIN FILE_PATH_TYPE_ARC
Definition at line 140 of file ntexapi.h.
#define FILE_PATH_TYPE_NT 3
Definition at line 137 of file ntexapi.h.
#define FILE_PATH_VERSION 1
Definition at line 133 of file ntexapi.h.
#define FLG_APPLICATION_VERIFIER 0x00000100
Definition at line 2667 of file ntexapi.h.
Referenced by ExMapHandleToPointerEx().
#define FLG_BOOTONLY_VALID_BITS
Value:
(FLG_KERNEL_STACK_TRACE_DB       | \
                                        FLG_MAINTAIN_OBJECT_TYPELIST    | \
                                        FLG_ENABLE_CSRDEBUG             | \
                                        FLG_DEBUG_INITIAL_COMMAND       | \
                                        FLG_DEBUG_INITIAL_COMMAND_EX    | \
                                        FLG_DISABLE_PAGE_KERNEL_STACKS)
Definition at line 2716 of file ntexapi.h.
Referenced by NtSetSystemInformation().
#define FLG_CRITSEC_EVENT_CREATION 0x10000000
Definition at line 2691 of file ntexapi.h.
#define FLG_DEBUG_INITIAL_COMMAND 0x00000004
Definition at line 2659 of file ntexapi.h.
#define FLG_DEBUG_INITIAL_COMMAND_EX 0x04000000
Definition at line 2688 of file ntexapi.h.
#define FLG_DISABLE_DBGPRINT 0x08000000
Definition at line 2689 of file ntexapi.h.
#define FLG_DISABLE_PAGE_KERNEL_STACKS 0x00080000
Definition at line 2679 of file ntexapi.h.
Referenced by MmInPageKernelStack(), and MmOutPageKernelStack().
#define FLG_DISABLE_PROTDLLS 0x80000000
Definition at line 2694 of file ntexapi.h.
#define FLG_DISABLE_STACK_EXTENSION 0x00010000
Definition at line 2676 of file ntexapi.h.
Referenced by MiCheckForUserStackOverflow().
#define FLG_ENABLE_CLOSE_EXCEPTIONS 0x00400000
Definition at line 2683 of file ntexapi.h.
Referenced by ExpInitializeExecutive(), ObpCloseHandle(), and ObpCloseHandleTableEntry().
#define FLG_ENABLE_CSRDEBUG 0x00020000
Definition at line 2677 of file ntexapi.h.
Referenced by RtlCreateUserProcess().
#define FLG_ENABLE_EXCEPTION_LOGGING 0x00800000
Definition at line 2684 of file ntexapi.h.
Referenced by ExpInitializeExecutive(), and RtlDispatchException().
#define FLG_ENABLE_HANDLE_EXCEPTIONS 0x40000000
Definition at line 2693 of file ntexapi.h.
Referenced by ExMapHandleToPointerEx().
#define FLG_ENABLE_HANDLE_TYPE_TAGGING 0x01000000
Definition at line 2686 of file ntexapi.h.
#define FLG_ENABLE_KDEBUG_SYMBOL_LOAD 0x00040000
Definition at line 2678 of file ntexapi.h.
Referenced by ExpInitializeExecutive(), IoInitSystem(), MiLoadImageSection(), and MiMapViewOfImageSection().
#define FLG_ENABLE_SYSTEM_CRIT_BREAKS 0x00100000
Definition at line 2681 of file ntexapi.h.
Referenced by RtlSetProcessIsCritical(), and RtlSetThreadIsCritical().
#define FLG_HEAP_DISABLE_COALESCING 0x00200000
Definition at line 2682 of file ntexapi.h.
#define FLG_HEAP_ENABLE_FREE_CHECK 0x00000020
Definition at line 2663 of file ntexapi.h.
#define FLG_HEAP_ENABLE_TAG_BY_DLL 0x00008000
Definition at line 2674 of file ntexapi.h.
#define FLG_HEAP_ENABLE_TAGGING 0x00000800
Definition at line 2669 of file ntexapi.h.
#define FLG_HEAP_ENABLE_TAIL_CHECK 0x00000010
Definition at line 2662 of file ntexapi.h.
#define FLG_HEAP_PAGE_ALLOCS 0x02000000
Definition at line 2687 of file ntexapi.h.
#define FLG_HEAP_VALIDATE_ALL 0x00000080
Definition at line 2665 of file ntexapi.h.
#define FLG_HEAP_VALIDATE_PARAMETERS 0x00000040
Definition at line 2664 of file ntexapi.h.
#define FLG_KERNEL_STACK_TRACE_DB 0x00002000
Definition at line 2672 of file ntexapi.h.
Referenced by ExInitializeResourceLite(), ExpInitializeExecutive(), ObDupHandleProcedure(), ObDuplicateObject(), ObInitSystem(), ObpCaptureHandleInformation(), ObpCaptureHandleInformationEx(), ObpCloseHandleTableEntry(), ObpCreateHandle(), ObpCreateUnnamedHandle(), ObpEnumFindHandleProcedure(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
#define FLG_KERNELMODE_VALID_BITS
Value:
(FLG_STOP_ON_EXCEPTION           | \
                                        FLG_SHOW_LDR_SNAPS              | \
                                        FLG_STOP_ON_HUNG_GUI            | \
                                        FLG_POOL_ENABLE_TAGGING         | \
                                        FLG_ENABLE_KDEBUG_SYMBOL_LOAD   | \
                                        FLG_ENABLE_CLOSE_EXCEPTIONS     | \
                                        FLG_ENABLE_EXCEPTION_LOGGING    | \
                                        FLG_ENABLE_HANDLE_TYPE_TAGGING  | \
                                        FLG_DISABLE_DBGPRINT            | \
                                        FLG_ENABLE_HANDLE_EXCEPTIONS      \
                                       )
Definition at line 2723 of file ntexapi.h.
Referenced by NtSetSystemInformation().
#define FLG_LDR_TOP_DOWN 0x20000000
Definition at line 2692 of file ntexapi.h.
#define FLG_MAINTAIN_OBJECT_TYPELIST 0x00004000
Definition at line 2673 of file ntexapi.h.
Referenced by ObCreateObjectType().
#define FLG_POOL_ENABLE_TAGGING 0x00000400
Definition at line 2668 of file ntexapi.h.
#define FLG_SHOW_LDR_SNAPS 0x00000002
Definition at line 2658 of file ntexapi.h.
Referenced by MiLoadImageSection(), and MmLoadSystemImage().
#define FLG_STOP_ON_EXCEPTION 0x00000001
Definition at line 2657 of file ntexapi.h.
#define FLG_STOP_ON_HUNG_GUI 0x00000008
Definition at line 2660 of file ntexapi.h.
#define FLG_USER_STACK_TRACE_DB 0x00001000
Definition at line 2671 of file ntexapi.h.
#define FLG_USERMODE_VALID_BITS
Value:
(FLG_STOP_ON_EXCEPTION           | \
                                        FLG_SHOW_LDR_SNAPS              | \
                                        FLG_HEAP_ENABLE_TAIL_CHECK      | \
                                        FLG_HEAP_ENABLE_FREE_CHECK      | \
                                        FLG_HEAP_VALIDATE_PARAMETERS    | \
                                        FLG_HEAP_VALIDATE_ALL           | \
                                        FLG_APPLICATION_VERIFIER        | \
                                        FLG_HEAP_ENABLE_TAGGING         | \
                                        FLG_USER_STACK_TRACE_DB         | \
                                        FLG_HEAP_ENABLE_TAG_BY_DLL      | \
                                        FLG_DISABLE_STACK_EXTENSION     | \
                                        FLG_ENABLE_SYSTEM_CRIT_BREAKS   | \
                                        FLG_HEAP_DISABLE_COALESCING     | \
                                        FLG_DISABLE_PROTDLLS            | \
                                        FLG_HEAP_PAGE_ALLOCS            | \
                                        FLG_CRITSEC_EVENT_CREATION      | \
                                        FLG_LDR_TOP_DOWN)
Definition at line 2698 of file ntexapi.h.
#define FLG_VALID_BITS 0xFFFFFDFF
Definition at line 2696 of file ntexapi.h.
#define HARDERROR_FLAGS_DEFDESKTOPONLY 0x00020000
Definition at line 2108 of file ntexapi.h.
#define HARDERROR_OVERRIDE_ERRORMODE 0x10000000
Definition at line 2112 of file ntexapi.h.
Referenced by ExpRaiseHardError().
#define HARDERROR_PARAMETERS_FLAGSPOS 4
Definition at line 2107 of file ntexapi.h.
#define KEYEDEVENT_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | KEYEDEVENT_WAIT | KEYEDEVENT_WAKE)
Definition at line 923 of file ntexapi.h.
Referenced by ExpKeyedEventInitialization().
#define KEYEDEVENT_WAIT 0x0001
Definition at line 921 of file ntexapi.h.
Referenced by ExpKeyedEventInitialization(), and NtWaitForKeyedEvent().
#define KEYEDEVENT_WAKE 0x0002
Definition at line 922 of file ntexapi.h.
Referenced by ExpKeyedEventInitialization(), and NtReleaseKeyedEvent().
#define LTP_PC_SMT 0x1
Definition at line 1260 of file ntexapi.h.
Referenced by KeQueryLogicalProcessorInformation().
#define MAX_WOW64_SHARED_ENTRIES 16
Definition at line 2205 of file ntexapi.h.
#define MAXIMUM_HARDERROR_PARAMETERS 5
Definition at line 2110 of file ntexapi.h.
Referenced by ExpSystemErrorHandler(), ExRaiseHardError(), and NtRaiseHardError().
#define MAXIMUM_NUMA_NODES 16
Definition at line 1241 of file ntexapi.h.
#define MUTANT_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|\
                          MUTANT_QUERY_STATE)
Definition at line 552 of file ntexapi.h.
Referenced by ExpMutantInitialization().
#define MUTANT_QUERY_STATE 0x0001
Definition at line 550 of file ntexapi.h.
Referenced by NtQueryMutant().
#define NX_SUPPORT_POLICY_ALWAYSOFF 0
Definition at line 2223 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define NX_SUPPORT_POLICY_ALWAYSON 1
Definition at line 2224 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define NX_SUPPORT_POLICY_OPTIN 2
Definition at line 2225 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define NX_SUPPORT_POLICY_OPTOUT 3
Definition at line 2226 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define PF_3DNOW_INSTRUCTIONS_AVAILABLE 7
Definition at line 2150 of file ntexapi.h.
Referenced by ExIsProcessorFeaturePresent(), and KiInitializeKernel().
#define PF_ALPHA_BYTE_INSTRUCTIONS 5
Definition at line 2148 of file ntexapi.h.
#define PF_COMPARE_EXCHANGE_DOUBLE 2
Definition at line 2145 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define PF_FLOATING_POINT_EMULATED 1
Definition at line 2144 of file ntexapi.h.
#define PF_FLOATING_POINT_PRECISION_ERRATA 0
Definition at line 2143 of file ntexapi.h.
Referenced by KiInitMachineDependent().
#define PF_MMX_INSTRUCTIONS_AVAILABLE 3
Definition at line 2146 of file ntexapi.h.
Referenced by ExIsProcessorFeaturePresent(), and KiInitializeKernel().
#define PF_NX_ENABLED 12
Definition at line 2155 of file ntexapi.h.
Referenced by KiDispatchException(), and KiInitializeKernel().
#define PF_PAE_ENABLED 9
Definition at line 2152 of file ntexapi.h.
Referenced by KiInitializeKernel(), and KiInitializePcr().
#define PF_PPC_MOVEMEM_64BIT_OK 4
Definition at line 2147 of file ntexapi.h.
#define PF_RDTSC_INSTRUCTION_AVAILABLE 8
Definition at line 2151 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define PF_SSE_DAZ_MODE_AVAILABLE 11
Definition at line 2154 of file ntexapi.h.
#define PF_XMMI64_INSTRUCTIONS_AVAILABLE 10
Definition at line 2153 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define PF_XMMI_INSTRUCTIONS_AVAILABLE 6
Definition at line 2149 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define PROCESSOR_ALPHA_21064 21064
Definition at line 1934 of file ntexapi.h.
#define PROCESSOR_AMD_X8664 8664
Definition at line 1932 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_ALPHA 2
Definition at line 1954 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_ALPHA64 7
Definition at line 1959 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_AMD64 9
Definition at line 1961 of file ntexapi.h.
Referenced by KiInitializeKernel().
#define PROCESSOR_ARCHITECTURE_ARM 5
Definition at line 1957 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_IA32_ON_WIN64 10
Definition at line 1962 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_IA64 6
Definition at line 1958 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_INTEL 0
Definition at line 1952 of file ntexapi.h.
Referenced by ExpGetSystemEmulationProcessorInformation(), and KiInitializeKernel().
#define PROCESSOR_ARCHITECTURE_MIPS 1
Definition at line 1953 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_MSIL 8
Definition at line 1960 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_PPC 3
Definition at line 1955 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_SHX 4
Definition at line 1956 of file ntexapi.h.
#define PROCESSOR_ARCHITECTURE_UNKNOWN 0xFFFF
Definition at line 1964 of file ntexapi.h.
#define PROCESSOR_ARM720 1824
Definition at line 1946 of file ntexapi.h.
#define PROCESSOR_ARM820 2080
Definition at line 1947 of file ntexapi.h.
#define PROCESSOR_ARM920 2336
Definition at line 1948 of file ntexapi.h.
#define PROCESSOR_ARM_7TDMI 70001
Definition at line 1949 of file ntexapi.h.
#define PROCESSOR_FEATURE_MAX 64
Definition at line 2185 of file ntexapi.h.
Referenced by ExIsProcessorFeaturePresent().
#define PROCESSOR_HITACHI_SH3 10003
Definition at line 1939 of file ntexapi.h.
#define PROCESSOR_HITACHI_SH3E 10004
Definition at line 1940 of file ntexapi.h.
#define PROCESSOR_HITACHI_SH4 10005
Definition at line 1941 of file ntexapi.h.
#define PROCESSOR_INTEL_386 386
Definition at line 1928 of file ntexapi.h.
#define PROCESSOR_INTEL_486 486
Definition at line 1929 of file ntexapi.h.
#define PROCESSOR_INTEL_IA64 2200
Definition at line 1931 of file ntexapi.h.
#define PROCESSOR_INTEL_PENTIUM 586
Definition at line 1930 of file ntexapi.h.
#define PROCESSOR_MIPS_R4000 4000
Definition at line 1933 of file ntexapi.h.
#define PROCESSOR_MOTOROLA_821 821
Definition at line 1942 of file ntexapi.h.
#define PROCESSOR_OPTIL 0x494f
Definition at line 1950 of file ntexapi.h.
#define PROCESSOR_PPC_601 601
Definition at line 1935 of file ntexapi.h.
#define PROCESSOR_PPC_603 603
Definition at line 1936 of file ntexapi.h.
#define PROCESSOR_PPC_604 604
Definition at line 1937 of file ntexapi.h.
#define PROCESSOR_PPC_620 620
Definition at line 1938 of file ntexapi.h.
#define PROCESSOR_SHx_SH3 103
Definition at line 1943 of file ntexapi.h.
#define PROCESSOR_SHx_SH4 104
Definition at line 1944 of file ntexapi.h.
#define PROCESSOR_STRONGARM 2577
Definition at line 1945 of file ntexapi.h.
#define PROFILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | PROFILE_CONTROL)
Definition at line 862 of file ntexapi.h.
Referenced by ExpProfileInitialization().
#define PROFILE_CONTROL 0x0001
Definition at line 861 of file ntexapi.h.
Referenced by NtCreateProfile(), NtStartProfile(), and NtStopProfile().
#define SEMAPHORE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|0x3)
Definition at line 624 of file ntexapi.h.
Referenced by ExpSemaphoreInitialization().
#define SEMAPHORE_MODIFY_STATE 0x0002
Definition at line 622 of file ntexapi.h.
Referenced by NtReleaseSemaphore(), and NtSignalAndWaitForSingleObject().
#define SEMAPHORE_QUERY_STATE 0x0001
Definition at line 621 of file ntexapi.h.
Referenced by NtQuerySemaphore().
#define TIME_ZONE_ID_DAYLIGHT 2
Definition at line 1143 of file ntexapi.h.
#define TIME_ZONE_ID_STANDARD 1
Definition at line 1142 of file ntexapi.h.
#define TIME_ZONE_ID_UNKNOWN 0
Definition at line 1141 of file ntexapi.h.
#define TIMER_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|\
                          TIMER_QUERY_STATE|TIMER_MODIFY_STATE)
Definition at line 697 of file ntexapi.h.
Referenced by ExpTimerInitialization().
#define TIMER_MODIFY_STATE 0x0002
Definition at line 695 of file ntexapi.h.
Referenced by NtCancelTimer(), and NtSetTimer().
#define TIMER_QUERY_STATE 0x0001
Definition at line 694 of file ntexapi.h.
Referenced by NtQueryTimer().
#define VARIABLE_ATTRIBUTE_NON_VOLATILE 0x00000001
Definition at line 99 of file ntexapi.h.
#define VARIABLE_INFORMATION_NAMES 1
Definition at line 101 of file ntexapi.h.
#define VARIABLE_INFORMATION_VALUES 2
Definition at line 102 of file ntexapi.h.
#define WINDOWS_OS_OPTIONS_SIGNATURE "WINDOWS"
Definition at line 152 of file ntexapi.h.
#define WINDOWS_OS_OPTIONS_VERSION 1
Definition at line 154 of file ntexapi.h.
Typedef Documentation
typedef enum _ALTERNATIVE_ARCHITECTURE_TYPE ALTERNATIVE_ARCHITECTURE_TYPE
typedef struct _ATOM_BASIC_INFORMATION ATOM_BASIC_INFORMATION
typedef enum _ATOM_INFORMATION_CLASS ATOM_INFORMATION_CLASS
typedef struct _ATOM_TABLE_INFORMATION ATOM_TABLE_INFORMATION
typedef struct _BOOT_ENTRY BOOT_ENTRY
typedef struct _BOOT_ENTRY_LIST BOOT_ENTRY_LIST
typedef struct _BOOT_OPTIONS BOOT_OPTIONS
typedef struct _CACHE_DESCRIPTOR CACHE_DESCRIPTOR
typedef struct _DRIVER_VERIFIER_THUNK_PAIRS DRIVER_VERIFIER_THUNK_PAIRS
typedef struct _EFI_DRIVER_ENTRY EFI_DRIVER_ENTRY
typedef struct _EFI_DRIVER_ENTRY_LIST EFI_DRIVER_ENTRY_LIST
typedef struct _EVENT_BASIC_INFORMATION EVENT_BASIC_INFORMATION
typedef enum _EVENT_INFORMATION_CLASS EVENT_INFORMATION_CLASS
typedef struct _FILE_PATH FILE_PATH
typedef struct _HARDERROR_MSG HARDERROR_MSG
typedef enum _HARDERROR_RESPONSE HARDERROR_RESPONSE
typedef enum _HARDERROR_RESPONSE_OPTION HARDERROR_RESPONSE_OPTION
typedef struct _KUSER_SHARED_DATA KUSER_SHARED_DATA
typedef enum _LOGICAL_PROCESSOR_RELATIONSHIP LOGICAL_PROCESSOR_RELATIONSHIP
typedef struct _MUTANT_BASIC_INFORMATION MUTANT_BASIC_INFORMATION
typedef enum _MUTANT_INFORMATION_CLASS MUTANT_INFORMATION_CLASS
typedef struct _NAPDATA NAPDATA
typedef struct _ATOM_BASIC_INFORMATION * PATOM_BASIC_INFORMATION
typedef struct _ATOM_TABLE_INFORMATION * PATOM_TABLE_INFORMATION
typedef struct _BOOT_ENTRY * PBOOT_ENTRY
typedef struct _BOOT_ENTRY_LIST * PBOOT_ENTRY_LIST
typedef struct _BOOT_OPTIONS * PBOOT_OPTIONS
typedef struct _CACHE_DESCRIPTOR * PCACHE_DESCRIPTOR
typedef struct _DRIVER_VERIFIER_THUNK_PAIRS * PDRIVER_VERIFIER_THUNK_PAIRS
typedef ULONG_PTR(* PDRIVER_VERIFIER_THUNK_ROUTINE) (IN PVOID Context)
Definition at line 1013 of file ntexapi.h.
typedef struct _EFI_DRIVER_ENTRY * PEFI_DRIVER_ENTRY
typedef struct _EFI_DRIVER_ENTRY_LIST * PEFI_DRIVER_ENTRY_LIST
typedef struct _EVENT_BASIC_INFORMATION * PEVENT_BASIC_INFORMATION
typedef struct _FILE_PATH * PFILE_PATH
typedef NTSTATUS(__cdecl * PFNFTH) (PSYSTEM_FIRMWARE_TABLE_INFORMATION)
Definition at line 363 of file ntexapi.h.
typedef struct _HARDERROR_MSG * PHARDERROR_MSG
typedef struct _KUSER_SHARED_DATA * PKUSER_SHARED_DATA
typedef struct _MUTANT_BASIC_INFORMATION * PMUTANT_BASIC_INFORMATION
typedef struct _NAPDATA * PNAPDATA
typedef enum _PROCESSOR_CACHE_TYPE PROCESSOR_CACHE_TYPE
typedef USHORT * PRTL_ATOM
Definition at line 2739 of file ntexapi.h.
typedef struct _SEMAPHORE_BASIC_INFORMATION * PSEMAPHORE_BASIC_INFORMATION
typedef struct _SYSDBG_BUS_DATA * PSYSDBG_BUS_DATA
typedef enum _SYSDBG_COMMAND * PSYSDBG_COMMAND
typedef struct _SYSDBG_CONTROL_SPACE * PSYSDBG_CONTROL_SPACE
typedef struct _SYSDBG_IO_SPACE * PSYSDBG_IO_SPACE
typedef struct _SYSDBG_MSR * PSYSDBG_MSR
typedef struct _SYSDBG_PHYSICAL * PSYSDBG_PHYSICAL
typedef struct _SYSDBG_VIRTUAL * PSYSDBG_VIRTUAL
typedef struct _SYSTEM_BASIC_INFORMATION * PSYSTEM_BASIC_INFORMATION
typedef struct _SYSTEM_CALL_COUNT_INFORMATION * PSYSTEM_CALL_COUNT_INFORMATION
typedef struct _SYSTEM_DEVICE_INFORMATION * PSYSTEM_DEVICE_INFORMATION
typedef struct _SYSTEM_EXCEPTION_INFORMATION * PSYSTEM_EXCEPTION_INFORMATION
typedef struct _SYSTEM_EXTENDED_THREAD_INFORMATION * PSYSTEM_EXTENDED_THREAD_INFORMATION
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER * PSYSTEM_FIRMWARE_TABLE_HANDLER
typedef struct _SYSTEM_FIRMWARE_TABLE_INFORMATION * PSYSTEM_FIRMWARE_TABLE_INFORMATION
typedef struct _SYSTEM_GDI_DRIVER_INFORMATION * PSYSTEM_GDI_DRIVER_INFORMATION
typedef struct _SYSTEM_KERNEL_DEBUGGER_INFORMATION * PSYSTEM_KERNEL_DEBUGGER_INFORMATION
typedef struct _SYSTEM_LEGACY_DRIVER_INFORMATION * PSYSTEM_LEGACY_DRIVER_INFORMATION
typedef struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION * PSYSTEM_LOGICAL_PROCESSOR_INFORMATION
typedef struct _SYSTEM_LOOKASIDE_INFORMATION * PSYSTEM_LOOKASIDE_INFORMATION
typedef struct _SYSTEM_MEMORY_INFO * PSYSTEM_MEMORY_INFO
typedef struct _SYSTEM_MEMORY_INFORMATION * PSYSTEM_MEMORY_INFORMATION
typedef struct _SYSTEM_NUMA_INFORMATION * PSYSTEM_NUMA_INFORMATION
typedef struct _SYSTEM_PERFORMANCE_INFORMATION * PSYSTEM_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESS_INFORMATION * PSYSTEM_PROCESS_INFORMATION
typedef struct _SYSTEM_PROCESSOR_IDLE_INFORMATION * PSYSTEM_PROCESSOR_IDLE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_INFORMATION * PSYSTEM_PROCESSOR_INFORMATION
typedef struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION * PSYSTEM_PROCESSOR_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_POWER_INFORMATION * PSYSTEM_PROCESSOR_POWER_INFORMATION
typedef struct _SYSTEM_QUERY_TIME_ADJUST_INFORMATION * PSYSTEM_QUERY_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_REGISTRY_QUOTA_INFORMATION * PSYSTEM_REGISTRY_QUOTA_INFORMATION
typedef struct _SYSTEM_SESSION_PROCESS_INFORMATION * PSYSTEM_SESSION_PROCESS_INFORMATION
typedef struct _SYSTEM_SET_TIME_ADJUST_INFORMATION * PSYSTEM_SET_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_THREAD_INFORMATION * PSYSTEM_THREAD_INFORMATION
typedef struct _SYSTEM_TIMEOFDAY_INFORMATION * PSYSTEM_TIMEOFDAY_INFORMATION
typedef struct _SYSTEM_VDM_INSTEMUL_INFO * PSYSTEM_VDM_INSTEMUL_INFO
typedef VOID(* PTIMER_APC_ROUTINE) (__in PVOID TimerContext, __in ULONG TimerLowValue, __in LONG TimerHighValue)
Definition at line 725 of file ntexapi.h.
typedef struct _TIMER_BASIC_INFORMATION * PTIMER_BASIC_INFORMATION
typedef struct _VARIABLE_NAME * PVARIABLE_NAME
typedef struct _VARIABLE_NAME_AND_VALUE * PVARIABLE_NAME_AND_VALUE
typedef struct _WINDOWS_OS_OPTIONS * PWINDOWS_OS_OPTIONS
typedef USHORT RTL_ATOM
Definition at line 2739 of file ntexapi.h.
typedef struct _SEMAPHORE_BASIC_INFORMATION SEMAPHORE_BASIC_INFORMATION
typedef enum _SEMAPHORE_INFORMATION_CLASS SEMAPHORE_INFORMATION_CLASS
typedef enum _SHUTDOWN_ACTION SHUTDOWN_ACTION
typedef struct _SYSDBG_BUS_DATA SYSDBG_BUS_DATA
typedef enum _SYSDBG_COMMAND SYSDBG_COMMAND
typedef struct _SYSDBG_CONTROL_SPACE SYSDBG_CONTROL_SPACE
typedef struct _SYSDBG_IO_SPACE SYSDBG_IO_SPACE
typedef struct _SYSDBG_MSR SYSDBG_MSR
typedef struct _SYSDBG_PHYSICAL SYSDBG_PHYSICAL
typedef struct _SYSDBG_VIRTUAL SYSDBG_VIRTUAL
typedef SIZE_T SYSINF_PAGE_COUNT
Definition at line 1196 of file ntexapi.h.
typedef struct _SYSTEM_BASIC_INFORMATION SYSTEM_BASIC_INFORMATION
typedef struct _SYSTEM_CALL_COUNT_INFORMATION SYSTEM_CALL_COUNT_INFORMATION
typedef struct _SYSTEM_DEVICE_INFORMATION SYSTEM_DEVICE_INFORMATION
typedef struct _SYSTEM_EXCEPTION_INFORMATION SYSTEM_EXCEPTION_INFORMATION
typedef struct _SYSTEM_EXTENDED_THREAD_INFORMATION SYSTEM_EXTENDED_THREAD_INFORMATION
typedef enum _SYSTEM_FIRMWARE_TABLE_ACTION SYSTEM_FIRMWARE_TABLE_ACTION
typedef struct _SYSTEM_FIRMWARE_TABLE_HANDLER SYSTEM_FIRMWARE_TABLE_HANDLER
typedef struct _SYSTEM_FIRMWARE_TABLE_INFORMATION SYSTEM_FIRMWARE_TABLE_INFORMATION
typedef struct _SYSTEM_GDI_DRIVER_INFORMATION SYSTEM_GDI_DRIVER_INFORMATION
typedef enum _SYSTEM_INFORMATION_CLASS SYSTEM_INFORMATION_CLASS
typedef struct _SYSTEM_KERNEL_DEBUGGER_INFORMATION SYSTEM_KERNEL_DEBUGGER_INFORMATION
typedef struct _SYSTEM_LEGACY_DRIVER_INFORMATION SYSTEM_LEGACY_DRIVER_INFORMATION
typedef struct _SYSTEM_LOGICAL_PROCESSOR_INFORMATION SYSTEM_LOGICAL_PROCESSOR_INFORMATION
typedef struct _SYSTEM_LOOKASIDE_INFORMATION SYSTEM_LOOKASIDE_INFORMATION
typedef struct _SYSTEM_MEMORY_INFO SYSTEM_MEMORY_INFO
typedef struct _SYSTEM_MEMORY_INFORMATION SYSTEM_MEMORY_INFORMATION
typedef struct _SYSTEM_NUMA_INFORMATION SYSTEM_NUMA_INFORMATION
typedef struct _SYSTEM_PERFORMANCE_INFORMATION SYSTEM_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESS_INFORMATION SYSTEM_PROCESS_INFORMATION
typedef struct _SYSTEM_PROCESSOR_IDLE_INFORMATION SYSTEM_PROCESSOR_IDLE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_INFORMATION SYSTEM_PROCESSOR_INFORMATION
typedef struct _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION
typedef struct _SYSTEM_PROCESSOR_POWER_INFORMATION SYSTEM_PROCESSOR_POWER_INFORMATION
typedef struct _SYSTEM_QUERY_TIME_ADJUST_INFORMATION SYSTEM_QUERY_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_REGISTRY_QUOTA_INFORMATION SYSTEM_REGISTRY_QUOTA_INFORMATION
typedef struct _SYSTEM_SESSION_PROCESS_INFORMATION SYSTEM_SESSION_PROCESS_INFORMATION
typedef struct _SYSTEM_SET_TIME_ADJUST_INFORMATION SYSTEM_SET_TIME_ADJUST_INFORMATION
typedef struct _SYSTEM_THREAD_INFORMATION SYSTEM_THREAD_INFORMATION
typedef struct _SYSTEM_TIMEOFDAY_INFORMATION SYSTEM_TIMEOFDAY_INFORMATION
typedef struct _SYSTEM_VDM_INSTEMUL_INFO SYSTEM_VDM_INSTEMUL_INFO
typedef struct _TIMER_BASIC_INFORMATION TIMER_BASIC_INFORMATION
typedef enum _TIMER_INFORMATION_CLASS TIMER_INFORMATION_CLASS
typedef struct _VARIABLE_NAME VARIABLE_NAME
typedef struct _VARIABLE_NAME_AND_VALUE VARIABLE_NAME_AND_VALUE
typedef struct _WINDOWS_OS_OPTIONS WINDOWS_OS_OPTIONS
Enumeration Type Documentation
enum _ALTERNATIVE_ARCHITECTURE_TYPE
Enumerator
StandardDesign
NEC98x86
EndAlternatives
Definition at line 2157 of file ntexapi.h.
enum _ATOM_INFORMATION_CLASS
Enumerator
AtomBasicInformation
AtomTableInformation
Definition at line 2766 of file ntexapi.h.
enum _EVENT_INFORMATION_CLASS
Enumerator
EventBasicInformation
Definition at line 389 of file ntexapi.h.
enum _HARDERROR_RESPONSE
Enumerator
ResponseReturnToCaller
ResponseNotHandled
ResponseAbort
ResponseCancel
ResponseIgnore
ResponseNo
ResponseOk
ResponseRetry
ResponseYes
ResponseTryAgain
ResponseContinue
Definition at line 2093 of file ntexapi.h.
enum _HARDERROR_RESPONSE_OPTION
Enumerator
OptionAbortRetryIgnore
OptionOk
OptionOkCancel
OptionRetryCancel
OptionYesNo
OptionYesNoCancel
OptionShutdownSystem
OptionOkNoWait
OptionCancelTryContinue
Definition at line 2081 of file ntexapi.h.
enum _LOGICAL_PROCESSOR_RELATIONSHIP
Enumerator
RelationProcessorCore
RelationNumaNode
RelationCache
Definition at line 1254 of file ntexapi.h.
enum _MUTANT_INFORMATION_CLASS
Enumerator
MutantBasicInformation
Definition at line 560 of file ntexapi.h.
enum _PROCESSOR_CACHE_TYPE
Enumerator
CacheUnified
CacheInstruction
CacheData
CacheTrace
Definition at line 1262 of file ntexapi.h.
enum _SEMAPHORE_INFORMATION_CLASS
Enumerator
SemaphoreBasicInformation
Definition at line 632 of file ntexapi.h.
enum _SHUTDOWN_ACTION
Enumerator
ShutdownNoReboot
ShutdownReboot
ShutdownPowerOff
Definition at line 2632 of file ntexapi.h.
enum _SYSDBG_COMMAND
Enumerator
SysDbgQueryModuleInformation
SysDbgQueryTraceInformation
SysDbgSetTracepoint
SysDbgSetSpecialCall
SysDbgClearSpecialCalls
SysDbgQuerySpecialCalls
SysDbgBreakPoint
SysDbgQueryVersion
SysDbgReadVirtual
SysDbgWriteVirtual
SysDbgReadPhysical
SysDbgWritePhysical
SysDbgReadControlSpace
SysDbgWriteControlSpace
SysDbgReadIoSpace
SysDbgWriteIoSpace
SysDbgReadMsr
SysDbgWriteMsr
SysDbgReadBusData
SysDbgWriteBusData
SysDbgCheckLowMemory
SysDbgEnableKernelDebugger
SysDbgDisableKernelDebugger
SysDbgGetAutoKdEnable
SysDbgSetAutoKdEnable
SysDbgGetPrintBufferSize
SysDbgSetPrintBufferSize
SysDbgGetKdUmExceptionEnable
SysDbgSetKdUmExceptionEnable
SysDbgGetTriageDump
SysDbgGetKdBlockEnable
SysDbgSetKdBlockEnable
Definition at line 1992 of file ntexapi.h.
enum _SYSTEM_FIRMWARE_TABLE_ACTION
Enumerator
SystemFirmwareTable_Enumerate
SystemFirmwareTable_Get
Definition at line 350 of file ntexapi.h.
enum _SYSTEM_INFORMATION_CLASS
Enumerator
SystemBasicInformation
SystemProcessorInformation
SystemPerformanceInformation
SystemTimeOfDayInformation
SystemPathInformation
SystemProcessInformation
SystemCallCountInformation
SystemDeviceInformation
SystemProcessorPerformanceInformation
SystemFlagsInformation
SystemCallTimeInformation
SystemModuleInformation
SystemLocksInformation
SystemStackTraceInformation
SystemPagedPoolInformation
SystemNonPagedPoolInformation
SystemHandleInformation
SystemObjectInformation
SystemPageFileInformation
SystemVdmInstemulInformation
SystemVdmBopInformation
SystemFileCacheInformation
SystemPoolTagInformation
SystemInterruptInformation
SystemDpcBehaviorInformation
SystemFullMemoryInformation
SystemLoadGdiDriverInformation
SystemUnloadGdiDriverInformation
SystemTimeAdjustmentInformation
SystemSummaryMemoryInformation
SystemMirrorMemoryInformation
SystemPerformanceTraceInformation
SystemObsolete0
SystemExceptionInformation
SystemCrashDumpStateInformation
SystemKernelDebuggerInformation
SystemContextSwitchInformation
SystemRegistryQuotaInformation
SystemExtendServiceTableInformation
SystemPrioritySeperation
SystemVerifierAddDriverInformation
SystemVerifierRemoveDriverInformation
SystemProcessorIdleInformation
SystemLegacyDriverInformation
SystemCurrentTimeZoneInformation
SystemLookasideInformation
SystemTimeSlipNotification
SystemSessionCreate
SystemSessionDetach
SystemSessionInformation
SystemRangeStartInformation
SystemVerifierInformation
SystemVerifierThunkExtend
SystemSessionProcessInformation
SystemLoadGdiDriverInSystemSpace
SystemNumaProcessorMap
SystemPrefetcherInformation
SystemExtendedProcessInformation
SystemRecommendedSharedDataAlignment
SystemComPlusPackage
SystemNumaAvailableMemory
SystemProcessorPowerInformation
SystemEmulationBasicInformation
SystemEmulationProcessorInformation
SystemExtendedHandleInformation
SystemLostDelayedWriteInformation
SystemBigPoolInformation
SystemSessionPoolTagInformation
SystemSessionMappedViewInformation
SystemHotpatchInformation
SystemObjectSecurityMode
SystemWatchdogTimerHandler
SystemWatchdogTimerInformation
SystemLogicalProcessorInformation
SystemWow64SharedInformation
SystemRegisterFirmwareTableInformationHandler
SystemFirmwareTableInformation
SystemModuleInformationEx
SystemVerifierTriageInformation
SystemSuperfetchInformation
SystemMemoryListInformation
SystemFileCacheInformationEx
MaxSystemInfoClass
Definition at line 1050 of file ntexapi.h.
enum _TIMER_INFORMATION_CLASS
Enumerator
TimerBasicInformation
Definition at line 705 of file ntexapi.h.
Function Documentation
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TickCountMultiplier) = =0x4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, InterruptTime) = =0x8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemTime) = =0x14)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TimeZoneBias) = =0x20)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ImageNumberLow) = =0x2C)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ImageNumberHigh) = =0x2E)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtSystemRoot) = =0x30)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, MaxStackTraceDepth) = =0x238)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, CryptoExponent) = =0x23C)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TimeZoneId) = =0x240)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, LargePageMinimum) = =0x244)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Reserved2) = =0x248)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtProductType) = =0x264)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ProductTypeIsValid) = =0x268)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtMajorVersion) = =0x26C)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NtMinorVersion) = =0x270)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ProcessorFeatures) = =0x274)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Reserved1) = =0x2B4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Reserved3) = =0x2B8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TimeSlip) = =0x2BC)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, AlternativeArchitecture) = =0x2C0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemExpirationDate) = =0x2C8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SuiteMask) = =0x2D0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, KdDebuggerEnabled) = =0x2D4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NXSupportPolicy) = =0x2D5)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ActiveConsoleId) = =0x2D8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, DismountCount) = =0x2DC)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, ComPlusPackage) = =0x2E0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, LastSystemRITEventTickCount) = =0x2E4)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, NumberOfPhysicalPages) = =0x2E8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SafeBootMode) = =0x2EC)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TraceLogging) = =0x2F0)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TestRetInstruction) = =0x2F8)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemCall) = =0x300)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemCallReturn) = =0x304)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, SystemCallPad) = =0x308)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TickCount) = =0x320)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, TickCountQuad) = =0x320)
C_ASSERT (FIELD_OFFSET(KUSER_SHARED_DATA, Wow64SharedInformation) = =0x334)
NTSTATUS NapClearData (VOID)
NTSTATUS NapGetApiCount (OUT PULONG NapApiCount)
NTSTATUS NapPause (VOID)
NTSTATUS NapResume (VOID)
NTSTATUS NapRetrieveData (OUT NAPDATA * NapApiData, OUT PCHAR ** NapApiNames, OUT PLARGE_INTEGER * NapCounterFrequency)
NTSYSCALLAPI NTSTATUS NTAPI NtAddAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
Definition at line 53 of file exatom.c.
References ARGUMENT_PRESENT, COPY_STACK_SIZE, except, EXCEPTION_EXECUTE_HANDLER, ExGlobalAtomTableCallout, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, ProbeForWriteUshort, RtlAddAtomToAtomTable(), RtlCopyMemory, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and UNICODE_NULL.
NTSYSCALLAPI NTSTATUS NTAPI NtAddBootEntry (__in PBOOT_ENTRY BootEntry, __out_opt PULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtAddDriverEntry (__in PEFI_DRIVER_ENTRY DriverEntry, __out_opt PULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateLocallyUniqueId (__out PLUID Luid)
Definition at line 67 of file luid.c.
References ExAllocateLocallyUniqueId(), except, ExSystemExceptionFilter(), KeGetPreviousMode, KernelMode, ProbeForWriteSmallStructure(), and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateUuids (__out PULARGE_INTEGER Time, __out PULONG Range, __out PULONG Sequence, __out PCHAR Seed)
Definition at line 628 of file uuid.c.
References ExAcquireFastMutexUnsafe(), except, ExpAllocateUuids(), ExpUuidSaveSequenceNumberIf(), ExReleaseFastMutexUnsafe(), ExSystemExceptionFilter(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KernelMode, _UUID_CACHED_VALUES_STRUCT::NodeId, NT_SUCCESS, PAGED_CODE, ProbeForWriteSmallStructure(), ProbeForWriteUlongAligned32(), _LARGE_INTEGER::QuadPart, RtlCopyMemory, SEED_SIZE, Status, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtCancelTimer (__in HANDLE TimerHandle, __out_opt PBOOLEAN CurrentState)
Definition at line 710 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, ARGUMENT_PRESENT, CONTAINING_RECORD, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, except, EXCEPTION_EXECUTE_HANDLER, ExpWakeTimerListLock, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, KeCancelTimer(), KeGetPreviousMode, KeReadStateTimer(), KeRemoveQueueApc(), KeRemoveQueueDpc(), KernelMode, _ETIMER::KeTimer, _ETIMER::Lock, NOTHING, NT_SUCCESS, NULL, ObDereferenceObjectEx(), ObReferenceObjectByHandle, ProbeForWriteBoolean, RemoveEntryList(), Status, _KAPC::Thread, TIMER_MODIFY_STATE, _ETIMER::TimerApc, _ETIMER::TimerDpc, and _ETIMER::WakeTimerListEntry.
NTSYSCALLAPI NTSTATUS NTAPI NtClearEvent (__in HANDLE EventHandle)
Definition at line 125 of file event.c.
References EVENT_MODIFY_STATE, KeClearEvent(), KeGetPreviousMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in EVENT_TYPE EventType, __in BOOLEAN InitialState)
Definition at line 180 of file event.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KeInitializeEvent(), KernelMode, NOTHING, NotificationEvent, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, Status, STATUS_INVALID_PARAMETER, and SynchronizationEvent.
Referenced by IoInitSystem(), and SepInitializationPhase1().
NTSYSCALLAPI NTSTATUS NTAPI NtCreateEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 121 of file eventpr.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KeInitializeEventPair(), _EEVENT_PAIR::KernelEventPair, KernelMode, NOTHING, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in ULONG Flags)
Definition at line 198 of file keyedevent.c.
References except, ExInitializePushLock(), ExSystemExceptionFilter(), Handle, InitializeListHead(), KeGetPreviousMode, KernelMode, _KEYED_EVENT_OBJECT::Lock, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForReadSmallStructure, Status, STATUS_INVALID_PARAMETER_4, and _KEYED_EVENT_OBJECT::WaitQueue.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in BOOLEAN InitialOwner)
Definition at line 152 of file mutant.c.
References except, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KeInitializeMutant(), KernelMode, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateProfile (__out PHANDLE ProfileHandle, __in HANDLE Process OPTIONAL, __in PVOID ProfileBase, __in SIZE_T ProfileSize, __in ULONG BucketSize, __in PULONG Buffer, __in ULONG BufferSize, __in KPROFILE_SOURCE ProfileSource, __in KAFFINITY Affinity)
Definition at line 204 of file profile.c.
References _EPROFILE::Affinity, ARGUMENT_PRESENT, _EPROFILE::BucketSize, _EPROFILE::Buffer, _EPROFILE::BufferSize, DbgPrint(), except, EXCEPTION_EXECUTE_HANDLER, FALSE, Handle, InitializeObjectAttributes, KeGetPreviousMode, KernelMode, _EPROFILE::LockedBufferAddress, MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, ObCreateObject, ObDereferenceObject(), ObInsertObject(), OBJ_EXCLUSIVE, ObReferenceObjectByHandle, _EPROCESS::Pcb, ProbeForWrite(), ProbeForWriteHandle, _EPROFILE::Process, PROCESS_QUERY_INFORMATION, PROFILE_CONTROL, _EPROFILE::ProfileSource, PsProcessType, _EPROFILE::RangeBase, _EPROFILE::RangeSize, _EPROFILE::Segment, SeSinglePrivilegeCheck(), SeSystemProfilePrivilege, Status, STATUS_BUFFER_OVERFLOW, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_7, and STATUS_PRIVILEGE_NOT_HELD.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in LONG InitialCount, __in LONG MaximumCount)
Definition at line 121 of file semphore.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KeInitializeSemaphore(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, Status, and STATUS_INVALID_PARAMETER.
NTSYSCALLAPI NTSTATUS NTAPI NtCreateTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in TIMER_TYPE TimerType)
Definition at line 488 of file timer.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExpTimerDpcRoutine(), FALSE, Handle, KeGetPreviousMode, KeInitializeDpc(), KeInitializeSpinLock(), KeInitializeTimerEx(), KernelMode, NOTHING, NotificationTimer, NT_SUCCESS, NULL, ObCreateObject, ObInsertObject(), ProbeForWriteHandle, Status, STATUS_INVALID_PARAMETER_4, SynchronizationTimer, and _ETIMER::TimerDpc.
NTSYSCALLAPI NTSTATUS NTAPI NtDelayExecution (__in BOOLEAN Alertable, __in PLARGE_INTEGER DelayInterval)
Definition at line 24 of file delay.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeDelayExecutionThread(), KeGetPreviousMode, KernelMode, and ProbeForReadSmallStructure.
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteAtom (__in RTL_ATOM Atom)
Definition at line 263 of file exatom.c.
References ExGlobalAtomTableCallout, NULL, PAGED_CODE, RtlDeleteAtomFromAtomTable(), and STATUS_ACCESS_DENIED.
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteBootEntry (__in ULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtDeleteDriverEntry (__in ULONG Id)
NTSYSCALLAPI NTSTATUS NTAPI NtDisplayString (__in PUNICODE_STRING String)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateBootEntries (__out_bcount_opt *BufferLength PVOID Buffer, __inout PULONG BufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateDriverEntries (__out_bcount *BufferLength PVOID Buffer, __inout PULONG BufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtEnumerateSystemEnvironmentValuesEx (__in ULONG InformationClass, __out PVOID Buffer, __inout PULONG BufferLength)
NTSYSCALLAPI NTSTATUS NTAPI NtFindAtom (__in_bcount_opt(Length) PWSTR AtomName, __in ULONG Length, __out_opt PRTL_ATOM Atom)
Definition at line 158 of file exatom.c.
References ARGUMENT_PRESENT, COPY_STACK_SIZE, except, EXCEPTION_EXECUTE_HANDLER, ExGlobalAtomTableCallout, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, PAGED_CODE, ProbeForRead, ProbeForWriteUshort, RtlCopyMemory, RtlLookupAtomInAtomTable(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, and UNICODE_NULL.
NTSYSCALLAPI NTSTATUS NTAPI NtModifyBootEntry (__in PBOOT_ENTRY BootEntry)
NTSYSCALLAPI NTSTATUS NTAPI NtModifyDriverEntry (__in PEFI_DRIVER_ENTRY DriverEntry)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenEvent (__out PHANDLE EventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 305 of file event.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenEventPair (__out PHANDLE EventPairHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 233 of file eventpr.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenKeyedEvent (__out PHANDLE KeyedEventHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 309 of file keyedevent.c.
References except, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForReadSmallStructure, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenMutant (__out PHANDLE MutantHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 272 of file mutant.c.
References except, ExSystemExceptionFilter(), Handle, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenSemaphore (__out PHANDLE SemaphoreHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 252 of file semphore.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenTimer (__out PHANDLE TimerHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 620 of file timer.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, NOTHING, NT_SUCCESS, NULL, ObOpenObjectByName(), ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtPulseEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
Definition at line 395 of file event.c.
References ARGUMENT_PRESENT, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, ExpEventBoost, FALSE, KeGetPreviousMode, KePulseEvent(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryBootEntryOrder (__out_ecount_opt *Count PULONG Ids, __inout PULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryBootOptions (__out_bcount_opt *BootOptionsLength PBOOT_OPTIONS BootOptions, __inout PULONG BootOptionsLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDefaultLocale (__in BOOLEAN UserProfile, __out PLCID DefaultLocaleId)
Definition at line 465 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, MmGetSessionLocaleId(), PAGED_CODE, ProbeForWriteUlong, PsDefaultSystemLocaleId, Status, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDefaultUILanguage (__out LANGID * DefaultUILanguageId)
Definition at line 696 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, ExpGetCurrentUserUILanguage(), KeGetPreviousMode, KernelMode, NT_SUCCESS, PAGED_CODE, ProbeForWriteUshort, PsInstallUILanguageId, Status, STATUS_SUCCESS, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryDriverEntryOrder (__out_ecount *Count PULONG Ids, __inout PULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryEvent (__in HANDLE EventHandle, __in EVENT_INFORMATION_CLASS EventInformationClass, __out_bcount(EventInformationLength) PVOID EventInformation, __in ULONG EventInformationLength, __out_opt PULONG ReturnLength)
Definition at line 489 of file event.c.
References ARGUMENT_PRESENT, EVENT_QUERY_STATE, EventBasicInformation, _EVENT_BASIC_INFORMATION::EventState, _EVENT_BASIC_INFORMATION::EventType, except, EXCEPTION_EXECUTE_HANDLER, _KEVENT::Header, KeGetPreviousMode, KeReadStateEvent(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWrite(), ProbeForWriteUlong, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, and _DISPATCHER_HEADER::Type.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInformationAtom (__in RTL_ATOM Atom, __in ATOM_INFORMATION_CLASS AtomInformationClass, __out_bcount(AtomInformationLength) PVOID AtomInformation, __in ULONG AtomInformationLength, __out_opt PULONG ReturnLength)
Definition at line 301 of file exatom.c.
References ARGUMENT_PRESENT, AtomBasicInformation, _ATOM_TABLE_INFORMATION::Atoms, AtomTableInformation, except, EXCEPTION_EXECUTE_HANDLER, ExGlobalAtomTableCallout, FIELD_OFFSET, _ATOM_BASIC_INFORMATION::Flags, KeGetPreviousMode, KernelMode, _ATOM_BASIC_INFORMATION::Name, _ATOM_BASIC_INFORMATION::NameLength, NT_SUCCESS, NULL, _ATOM_TABLE_INFORMATION::NumberOfAtoms, PAGED_CODE, ProbeForWrite(), ProbeForWriteUlong, RtlQueryAtomInAtomTable(), RtlQueryAtomsInAtomTable(), Status, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SUCCESS, UNICODE_NULL, and _ATOM_BASIC_INFORMATION::UsageCount.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryInstallUILanguage (__out LANGID * InstallUILanguageId)
Definition at line 665 of file sysinfo.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, PAGED_CODE, ProbeForWriteUshort, PsInstallUILanguageId, Status, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryIntervalProfile (__in KPROFILE_SOURCE ProfileSource, __out PULONG Interval)
Definition at line 757 of file profile.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeQueryIntervalProfile(), KernelMode, NOTHING, ProbeForWriteUlong, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryMutant (__in HANDLE MutantHandle, __in MUTANT_INFORMATION_CLASS MutantInformationClass, __out_bcount(MutantInformationLength) PVOID MutantInformation, __in ULONG MutantInformationLength, __out_opt PULONG ReturnLength)
Definition at line 368 of file mutant.c.
References ARGUMENT_PRESENT, Count, except, ExSystemExceptionFilter(), KeGetCurrentThread(), KeGetPreviousMode, KeReadStateMutant(), KernelMode, MUTANT_QUERY_STATE, MutantBasicInformation, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_INVALID_INFO_CLASS.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryPerformanceCounter (__out PLARGE_INTEGER PerformanceCounter, __out_opt PLARGE_INTEGER PerformanceFrequency)
Definition at line 821 of file profile.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeQueryPerformanceCounter(), KernelMode, ProbeForWriteSmallStructure(), and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySemaphore (__in HANDLE SemaphoreHandle, __in SEMAPHORE_INFORMATION_CLASS SemaphoreInformationClass, __out_bcount(SemaphoreInformationLength) PVOID SemaphoreInformation, __in ULONG SemaphoreInformationLength, __out_opt PULONG ReturnLength)
Definition at line 343 of file semphore.c.
References ARGUMENT_PRESENT, Count, _SEMAPHORE_BASIC_INFORMATION::CurrentCount, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeReadStateSemaphore(), KernelMode, _SEMAPHORE_BASIC_INFORMATION::MaximumCount, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, SEMAPHORE_QUERY_STATE, SemaphoreBasicInformation, Status, STATUS_INFO_LENGTH_MISMATCH, and STATUS_INVALID_INFO_CLASS.
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemEnvironmentValue (__in PUNICODE_STRING VariableName, __out_bcount(ValueLength) PWSTR VariableValue, __in USHORT ValueLength, __out_opt PUSHORT ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemEnvironmentValueEx (__in PUNICODE_STRING VariableName, __in LPGUID VendorGuid, __out_bcount_opt *ValueLength PVOID Value, __inout PULONG ValueLength, __out_opt PULONG Attributes)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __out_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength, __out_opt PULONG ReturnLength)
Definition at line 1391 of file sysinfo.c.
References _SYSTEM_EXCEPTION_INFORMATION::AlignmentFixupCount, ARGUMENT_PRESENT, _SYSTEM_PERFORMANCE_INFORMATION::AvailablePagedPoolPages, _SYSTEM_PERFORMANCE_INFORMATION::AvailablePages, _SYSTEM_TIMEOFDAY_INFORMATION::BootTime, _SYSTEM_TIMEOFDAY_INFORMATION::BootTimeBias, _SYSTEM_SESSION_PROCESS_INFORMATION::Buffer, _SYSTEM_EXCEPTION_INFORMATION::ByteWordEmulationCount, _SYSTEM_PERFORMANCE_INFORMATION::CacheIoCount, _SYSTEM_PERFORMANCE_INFORMATION::CacheReadCount, _SYSTEM_PERFORMANCE_INFORMATION::CacheTransitionCount, CcCopyReadNoWait, _KPRCB::CcCopyReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadNoWait, CcCopyReadNoWaitMiss, _KPRCB::CcCopyReadNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadNoWaitMiss, CcCopyReadWait, _KPRCB::CcCopyReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadWait, CcCopyReadWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcCopyReadWaitMiss, CcDataFlushes, _SYSTEM_PERFORMANCE_INFORMATION::CcDataFlushes, CcDataPages, _SYSTEM_PERFORMANCE_INFORMATION::CcDataPages, CcFastMdlReadNotPossible, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadNotPossible, CcFastMdlReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadNoWait, CcFastMdlReadResourceMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadResourceMiss, CcFastMdlReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastMdlReadWait, CcFastReadNotPossible, _KPRCB::CcFastReadNotPossible, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadNotPossible, CcFastReadNoWait, _KPRCB::CcFastReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadNoWait, CcFastReadResourceMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadResourceMiss, CcFastReadWait, _KPRCB::CcFastReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcFastReadWait, CcLazyWriteIos, _SYSTEM_PERFORMANCE_INFORMATION::CcLazyWriteIos, CcLazyWritePages, _SYSTEM_PERFORMANCE_INFORMATION::CcLazyWritePages, CcLostDelayedWrites, CcMapDataNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataNoWait, CcMapDataNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataNoWaitMiss, CcMapDataWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataWait, CcMapDataWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMapDataWaitMiss, CcMdlReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadNoWait, CcMdlReadNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadNoWaitMiss, CcMdlReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadWait, CcMdlReadWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcMdlReadWaitMiss, CcPfQueryPrefetcherInformation(), CcPinMappedDataCount, _SYSTEM_PERFORMANCE_INFORMATION::CcPinMappedDataCount, CcPinReadNoWait, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadNoWait, CcPinReadNoWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadNoWaitMiss, CcPinReadWait, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadWait, CcPinReadWaitMiss, _SYSTEM_PERFORMANCE_INFORMATION::CcPinReadWaitMiss, CcReadAheadIos, _SYSTEM_PERFORMANCE_INFORMATION::CcReadAheadIos, _CONFIGURATION_INFORMATION::CdRomCount, CmQueryRegistryQuotaInformation(), _SYSTEM_PERFORMANCE_INFORMATION::CommitLimit, _SYSTEM_PERFORMANCE_INFORMATION::CommittedPages, COMPLUS_PACKAGE_INVALID, _SYSTEM_PERFORMANCE_INFORMATION::ContextSwitches, _SYSTEM_PERFORMANCE_INFORMATION::CopyOnWriteCount, _KSERVICE_TABLE_DESCRIPTOR::Count, _SYSTEM_TIMEOFDAY_INFORMATION::CurrentTime, DbgBreakPoint(), DbgPrint(), _SYSTEM_PERFORMANCE_INFORMATION::DemandZeroCount, _SYSTEM_PERFORMANCE_INFORMATION::DirtyPagesWriteCount, _SYSTEM_PERFORMANCE_INFORMATION::DirtyWriteIoCount, _CONFIGURATION_INFORMATION::DiskCount, DPC_NORMAL, _KDPC_DATA::DpcCount, _KPRCB::DpcData, _KPRCB::DpcRequestRate, _KPRCB::DpcTime, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::DpcTime, _SYSTEM_QUERY_TIME_ADJUST_INFORMATION::Enable, ExAcquireResourceExclusiveLite(), except, EXCEPTION_EXECUTE_HANDLER, _SYSTEM_EXCEPTION_INFORMATION::ExceptionDispatchCount, ExGetBigPoolInfo(), ExGetPoolTagInfo(), ExGetSessionPoolTagInformation(), ExpCurrentTimeZoneId, ExpGetHandleInformation(), ExpGetHandleInformationEx(), ExpGetInstemulInformation(), ExpGetLockInformation(), ExpGetLookasideInformation(), ExpGetObjectInformation(), ExpGetProcessInformation(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpGetSystemBasicInformation(), ExpGetSystemEmulationProcessorInformation(), ExpGetSystemFirmwareTableInformation(), ExpGetSystemProcessorInformation(), ExpQueryLegacyDriverInformation(), ExpQueryModuleInformation(), ExpQueryNumaAvailableMemory(), ExpQueryNumaProcessorMap(), ExpReadComPlusPackage(), ExpTimeZoneBias, ExpWdHandler, ExpWdHandlerContext, ExQueryPoolUsage(), ExRaiseStatus(), ExReleaseResourceLite(), FALSE, _KTHREAD_SWITCH_COUNTERS::FindAny, _KTHREAD_SWITCH_COUNTERS::FindIdeal, _KTHREAD_SWITCH_COUNTERS::FindLast, _SYSTEM_PERFORMANCE_INFORMATION::FirstLevelTbFills, _SYSTEM_EXCEPTION_INFORMATION::FloatingEmulationCount, _CONFIGURATION_INFORMATION::FloppyCount, _SYSTEM_PERFORMANCE_INFORMATION::FreeSystemPtes, _KTHREAD_SWITCH_COUNTERS::IdleAny, _KTHREAD_SWITCH_COUNTERS::IdleCurrent, _KTHREAD_SWITCH_COUNTERS::IdleIdeal, _KTHREAD_SWITCH_COUNTERS::IdleLast, _SYSTEM_PERFORMANCE_INFORMATION::IdleProcessTime, _KPRCB::IdleThread, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::IdleTime, _KPRCB::InterruptCount, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::InterruptCount, _KPRCB::InterruptTime, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::InterruptTime, IoGetConfigurationInformation(), _KPRCB::IoOtherOperationCount, _SYSTEM_PERFORMANCE_INFORMATION::IoOtherOperationCount, IoOtherOperationCount, _KPRCB::IoOtherTransferCount, _SYSTEM_PERFORMANCE_INFORMATION::IoOtherTransferCount, IoOtherTransferCount, _KPRCB::IoReadOperationCount, _SYSTEM_PERFORMANCE_INFORMATION::IoReadOperationCount, IoReadOperationCount, _KPRCB::IoReadTransferCount, _SYSTEM_PERFORMANCE_INFORMATION::IoReadTransferCount, IoReadTransferCount, _KPRCB::IoWriteOperationCount, _SYSTEM_PERFORMANCE_INFORMATION::IoWriteOperationCount, IoWriteOperationCount, _KPRCB::IoWriteTransferCount, _SYSTEM_PERFORMANCE_INFORMATION::IoWriteTransferCount, IoWriteTransferCount, KdDebuggerEnabled, KdDebuggerNotPresent, _KPRCB::KeAlignmentFixupCount, KeBootTime, KeBootTimeBias, KeEnterCriticalRegion(), _KPRCB::KeExceptionDispatchCount, _KPRCB::KeFirstLevelTbFills, _KPRCB::KeFloatingEmulationCount, KeGetContextSwitches(), KeGetPreviousMode, KeGetRecommendedSharedDataAlignment(), KeInterruptTimeBias, KeLeaveCriticalRegion(), KeMaximumIncrement, KeNumberProcessors, KeQueryLogicalProcessorInformation(), KeQueryRuntimeProcess(), KeQuerySystemTime(), _SYSTEM_KERNEL_DEBUGGER_INFORMATION::KernelDebuggerEnabled, _SYSTEM_KERNEL_DEBUGGER_INFORMATION::KernelDebuggerNotPresent, KernelMode, _KPRCB::KernelTime, _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::KernelTime, _KTHREAD::KernelTime, _KPRCB::KeSecondLevelTbFills, KeServiceDescriptorTableShadow, _KPRCB::KeSystemCalls, KeThreadSwitchCounters, KeTimeAdjustment, KeTimeIncrement, KeTimeSynchronization, KiAdjustDpcThreshold, KiIdealDpcRate, KiMaximumDpcQueueDepth, KiMinimumDpcRate, KiProcessorBlock, _SYSTEM_CALL_COUNT_INFORMATION::Length, _KSERVICE_TABLE_DESCRIPTOR::Limit, _SYSTEM_PERFORMANCE_INFORMATION::MappedPagesWriteCount, _SYSTEM_PERFORMANCE_INFORMATION::MappedWriteIoCount, MmAvailablePages, MmAvailablePoolInPages(), _KPRCB::MmCacheIoCount, _KPRCB::MmCacheReadCount, _KPRCB::MmCacheTransitionCount, _KPRCB::MmCopyOnWriteCount, _KPRCB::MmDemandZeroCount, _KPRCB::MmDirtyPagesWriteCount, _KPRCB::MmDirtyWriteIoCount, MmGetNumberOfFreeSystemPtes(), MmGetPageFileInformation(), MmGetSessionMappedViewInformation(), MmGetVerifierInformation(), _KPRCB::MmMappedPagesWriteCount, _KPRCB::MmMappedWriteIoCount, MmMemoryUsage(), MmPagedPoolPage, _KPRCB::MmPageFaultCount, _KPRCB::MmPageReadCount, _KPRCB::MmPageReadIoCount, MmPeakCommitment, MmQuerySystemCacheWorkingSetInformation(), MmSystemCachePage, MmSystemCodePage, MmSystemDriverPage, MmSystemRangeStart, MmTotalCommitLimit, MmTotalCommittedPages, MmTotalSystemCodePages, MmTotalSystemDriverPages, _KPRCB::MmTransitionCount, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolAllocs, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolFrees, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolLookasideHits, _SYSTEM_PERFORMANCE_INFORMATION::NonPagedPoolPages, NT_SUCCESS, NtGlobalFlag, NULL, NUMBER_SERVICE_TABLES, _SYSTEM_DEVICE_INFORMATION::NumberOfCdRoms, _SYSTEM_DEVICE_INFORMATION::NumberOfDisks, _SYSTEM_DEVICE_INFORMATION::NumberOfFloppies, _SYSTEM_DEVICE_INFORMATION::NumberOfParallelPorts, _SYSTEM_DEVICE_INFORMATION::NumberOfSerialPorts, _SYSTEM_CALL_COUNT_INFORMATION::NumberOfTables, _SYSTEM_DEVICE_INFORMATION::NumberOfTapes, ObGetSecurityMode(), PAGED_CODE, PagedPool, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolAllocs, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolFrees, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolLookasideHits, _SYSTEM_PERFORMANCE_INFORMATION::PagedPoolPages, _SYSTEM_PERFORMANCE_INFORMATION::PageFaultCount, _SYSTEM_PERFORMANCE_INFORMATION::PageReadCount, _SYSTEM_PERFORMANCE_INFORMATION::PageReadIoCount, _CONFIGURATION_INFORMATION::ParallelCount, _EPROCESS::Pcb, _SYSTEM_PERFORMANCE_INFORMATION::PeakCommitment, POINTER_IS_ALIGNED, _KTHREAD_SWITCH_COUNTERS::PreemptAny, _KTHREAD_SWITCH_COUNTERS::PreemptCurrent, _KTHREAD_SWITCH_COUNTERS::PreemptLast, ProbeForWrite(), ProbeForWriteUlong, PsIdleProcess, PsLoadedModuleList, PsLoadedModuleResource, _LARGE_INTEGER::QuadPart, _SYSTEM_PERFORMANCE_INFORMATION::ResidentPagedPoolPage, _SYSTEM_PERFORMANCE_INFORMATION::ResidentSystemCachePage, _SYSTEM_PERFORMANCE_INFORMATION::ResidentSystemCodePage, _SYSTEM_PERFORMANCE_INFORMATION::ResidentSystemDriverPage, RtlCopyMemory, RtlZeroMemory, _SYSTEM_PERFORMANCE_INFORMATION::SecondLevelTbFills, _CONFIGURATION_INFORMATION::SerialCount, _SYSTEM_SESSION_PROCESS_INFORMATION::SessionId, SharedUserData, _SYSTEM_SESSION_PROCESS_INFORMATION::SizeOfBuf, _SYSTEM_TIMEOFDAY_INFORMATION::SleepTimeBias, Status, STATUS_DATATYPE_MISALIGNMENT, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED, STATUS_SUCCESS, _KTHREAD_SWITCH_COUNTERS::SwitchToIdle, SystemBasicInformation, SystemBigPoolInformation, SystemCallCountInformation, _SYSTEM_PERFORMANCE_INFORMATION::SystemCalls, SystemCallTimeInformation, SystemComPlusPackage, SystemContextSwitchInformation, SystemCurrentTimeZoneInformation, SystemDeviceInformation, SystemDpcBehaviorInformation, SystemEmulationBasicInformation, SystemEmulationProcessorInformation, SystemExceptionInformation, SystemExtendedHandleInformation, SystemExtendedProcessInformation, SystemFileCacheInformation, SystemFileCacheInformationEx, SystemFirmwareTableInformation, SystemFlagsInformation, SystemFullMemoryInformation, SystemHandleInformation, SystemInterruptInformation, SystemKernelDebuggerInformation, SystemLegacyDriverInformation, SystemLocksInformation, SystemLogicalProcessorInformation, SystemLookasideInformation, SystemLostDelayedWriteInformation, SystemModuleInformation, SystemNonPagedPoolInformation, SystemNumaAvailableMemory, SystemNumaProcessorMap, SystemObjectInformation, SystemObjectSecurityMode, SystemPagedPoolInformation, SystemPageFileInformation, SystemPathInformation, SystemPerformanceInformation, SystemPerformanceTraceInformation, SystemPoolTagInformation, SystemPrefetcherInformation, SystemProcessInformation, SystemProcessorIdleInformation, SystemProcessorInformation, SystemProcessorPerformanceInformation, SystemProcessorPowerInformation, SystemRangeStartInformation, SystemRecommendedSharedDataAlignment, SystemRegistryQuotaInformation, SystemSessionMappedViewInformation, SystemSessionPoolTagInformation, SystemSessionProcessInformation, SystemStackTraceInformation, SystemSummaryMemoryInformation, SystemTimeAdjustmentInformation, SystemTimeOfDayInformation, SystemVdmInstemulInformation, SystemVerifierInformation, SystemWatchdogTimerInformation, _CONFIGURATION_INFORMATION::TapeCount, _SYSTEM_QUERY_TIME_ADJUST_INFORMATION::TimeAdjustment, _SYSTEM_QUERY_TIME_ADJUST_INFORMATION::TimeIncrement, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneBias, _SYSTEM_TIMEOFDAY_INFORMATION::TimeZoneId, _SYSTEM_PERFORMANCE_INFORMATION::TotalSystemCodePages, _SYSTEM_PERFORMANCE_INFORMATION::TotalSystemDriverPages, _SYSTEM_PERFORMANCE_INFORMATION::TransitionCount, TRUE, TYPE_ALIGNMENT, UInt32x32To64, _KPRCB::UserTime, and _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION::UserTime.
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySystemTime (__out PLARGE_INTEGER SystemTime)
Referenced by RtlRunEncodeUnicodeString().
NTSYSCALLAPI NTSTATUS NTAPI NtQueryTimer (__in HANDLE TimerHandle, __in TIMER_INFORMATION_CLASS TimerInformationClass, __out_bcount(TimerInformationLength) PVOID TimerInformation, __in ULONG TimerInformationLength, __out_opt PULONG ReturnLength)
Definition at line 846 of file timer.c.
References ARGUMENT_PRESENT, _KTIMER::DueTime, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeReadStateTimer(), KernelMode, _ETIMER::KeTimer, KiQueryInterruptTime, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, ProbeForWriteSmallStructure(), ProbeForWriteUlong, _LARGE_INTEGER::QuadPart, _ULARGE_INTEGER::QuadPart, _TIMER_BASIC_INFORMATION::RemainingTime, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, TIMER_QUERY_STATE, TimerBasicInformation, and _TIMER_BASIC_INFORMATION::TimerState.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryTimerResolution (__out PULONG MaximumTime, __out PULONG MinimumTime, __out PULONG CurrentTime)
NTSYSCALLAPI NTSTATUS NTAPI NtRaiseHardError (__in NTSTATUS ErrorStatus, __in ULONG NumberOfParameters, __in ULONG UnicodeStringParameterMask, __in_ecount(NumberOfParameters) PULONG_PTR Parameters, __in ULONG ValidResponseOptions, __out PULONG Response)
Definition at line 606 of file harderr.c.
References ARGUMENT_PRESENT, _UNICODE_STRING::Buffer, DbgPrint(), except, EXCEPTION_EXECUTE_HANDLER, ExpRaiseHardError(), ExRaiseHardError(), KdDebuggerEnabled, KeGetPreviousMode, KernelMode, MAXIMUM_HARDERROR_PARAMETERS, _UNICODE_STRING::MaximumLength, NOTHING, OptionAbortRetryIgnore, OptionCancelTryContinue, OptionOk, OptionOkCancel, OptionOkNoWait, OptionRetryCancel, OptionShutdownSystem, OptionYesNo, OptionYesNoCancel, PAGED_CODE, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteUlong, RtlCopyMemory, Status, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_4, STATUS_SUCCESS, and STATUS_SYSTEM_IMAGE_BAD_SIGNATURE.
Referenced by PsLocateSystemDll().
NTSYSCALLAPI NTSTATUS NTAPI NtReleaseKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 383 of file keyedevent.c.
References ASSERT, CONTAINING_RECORD, except, Executive, ExSystemExceptionFilter(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), InsertHeadList(), IsListEmpty, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), KEYEDEVENT_WAKE, _ETHREAD::KeyedEventInUse, _ETHREAD::KeyedWaitChain, _ETHREAD::KeyedWaitSemaphore, _ETHREAD::KeyedWaitValue, KEYVALUE_RELEASE, LOCK_KEYED_EVENT_EXCLUSIVE, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PASSIVE_LEVEL, ProbeForRead, PsGetCurrentProcessByThread, PsGetCurrentThread(), RemoveEntryList(), SEMAPHORE_INCREMENT, Status, STATUS_INVALID_PARAMETER_1, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, UNLOCK_KEYED_EVENT_EXCLUSIVE, UNLOCK_KEYED_EVENT_EXCLUSIVE_UNSAFE, and _KEYED_EVENT_OBJECT::WaitQueue.
NTSYSCALLAPI NTSTATUS NTAPI NtReleaseMutant (__in HANDLE MutantHandle, __out_opt PLONG PreviousCount)
Definition at line 505 of file mutant.c.
References ARGUMENT_PRESENT, Count, except, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KeReleaseMutant(), KernelMode, MUTANT_INCREMENT, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtReleaseSemaphore (__in HANDLE SemaphoreHandle, __in LONG ReleaseCount, __out_opt PLONG PreviousCount)
Definition at line 476 of file semphore.c.
References ARGUMENT_PRESENT, Count, except, EXCEPTION_EXECUTE_HANDLER, ExpSemaphoreBoost, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KeReleaseSemaphore(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, SEMAPHORE_MODIFY_STATE, Status, and STATUS_INVALID_PARAMETER.
NTSYSCALLAPI NTSTATUS NTAPI NtResetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
Definition at line 620 of file event.c.
References ARGUMENT_PRESENT, EVENT_MODIFY_STATE, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KeResetEvent(), KernelMode, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtSetBootEntryOrder (__in_ecount(Count) PULONG Ids, __in ULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtSetBootOptions (__in PBOOT_OPTIONS BootOptions, __in ULONG FieldsToChange)
NTSYSCALLAPI NTSTATUS NTAPI NtSetDefaultHardErrorPort (__in HANDLE DefaultHardErrorPort)
Definition at line 918 of file harderr.c.
References ExpDefaultErrorPort, ExReadyForErrors, HardErrorState, KeGetPreviousMode, LpcPortObjectType, NT_SUCCESS, NULL, ObReferenceObject, ObReferenceObjectByHandle, PAGED_CODE, PsGetCurrentProcess(), SeSinglePrivilegeCheck(), SeTcbPrivilege, STARTED, Status, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetDefaultLocale (__in BOOLEAN UserProfile, __in LCID DefaultLocaleId)
Definition at line 502 of file sysinfo.c.
References _KEY_VALUE_PARTIAL_INFORMATION::Data, _KEY_VALUE_PARTIAL_INFORMATION::DataLength, ExpValidateLocale(), GENERIC_READ, GENERIC_WRITE, InitializeObjectAttributes, KEY_ENUMERATE_SUB_KEYS, KeyValueName, KeyValuePartialInformation, MmSetSessionLocaleId(), NT_SUCCESS, NULL, OBJ_CASE_INSENSITIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_KERNEL_HANDLE, PAGED_CODE, PsDefaultSystemLocaleId, REG_DWORD, REG_SZ, RtlInitUnicodeString(), RtlOpenCurrentUser(), Status, STATUS_INVALID_PARAMETER, STATUS_UNSUCCESSFUL, _KEY_VALUE_PARTIAL_INFORMATION::Type, UNICODE_NULL, ZwClose(), ZwOpenKey(), ZwQueryValueKey(), and ZwSetValueKey().
NTSYSCALLAPI NTSTATUS NTAPI NtSetDefaultUILanguage (__in LANGID DefaultUILanguageId)
Definition at line 962 of file sysinfo.c.
References ExpGetCurrentUserUILanguage(), ExpSetCurrentUserUILanguage(), FALSE, NT_SUCCESS, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtSetDriverEntryOrder (__in_ecount(Count) PULONG Ids, __in ULONG Count)
NTSYSCALLAPI NTSTATUS NTAPI NtSetEvent (__in HANDLE EventHandle, __out_opt PLONG PreviousState)
Definition at line 712 of file event.c.
References ARGUMENT_PRESENT, EVENT_MODIFY_STATE, except, ExpEventBoost, ExSystemExceptionFilter(), FALSE, KeGetPreviousMode, KernelMode, KeSetEvent(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PERFINFO_DECLARE_OBJECT, ProbeForWriteLong, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtSetEventBoostPriority (__in HANDLE EventHandle)
Definition at line 800 of file event.c.
References EVENT_MODIFY_STATE, _KEVENT::Header, KeGetPreviousMode, KeSetEventBoostPriority(), NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, STATUS_OBJECT_TYPE_MISMATCH, and _DISPATCHER_HEADER::Type.
NTSYSCALLAPI NTSTATUS NTAPI NtSetHighEventPair (__in HANDLE EventPairHandle)
Definition at line 621 of file eventpr.c.
References EVENT_PAIR_INCREMENT, FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetHighEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetHighWaitLowEventPair (__in HANDLE EventPairHandle)
Definition at line 504 of file eventpr.c.
References KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetHighWaitLowEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetIntervalProfile (__in ULONG Interval, __in KPROFILE_SOURCE Source)
Definition at line 730 of file profile.c.
References KeSetIntervalProfile(), and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtSetLowEventPair (__in HANDLE EventPairHandle)
Definition at line 563 of file eventpr.c.
References EVENT_PAIR_INCREMENT, FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetLowEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetLowWaitHighEventPair (__in HANDLE EventPairHandle)
Definition at line 445 of file eventpr.c.
References KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeSetLowWaitHighEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemEnvironmentValue (__in PUNICODE_STRING VariableName, __in PUNICODE_STRING VariableValue)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemEnvironmentValueEx (__in PUNICODE_STRING VariableName, __in LPGUID VendorGuid, __in_bcount_opt(ValueLength) PVOID Value, __in ULONG ValueLength, __in ULONG Attributes)
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemInformation (__in SYSTEM_INFORMATION_CLASS SystemInformationClass, __in_bcount_opt(SystemInformationLength) PVOID SystemInformation, __in ULONG SystemInformationLength)
Definition at line 3068 of file sysinfo.c.
References _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, ASSERT, _UNICODE_STRING::Buffer, CcPfSetPrefetcherInformation(), CmSetRegistryQuotaInformation(), CrashDumpReconfigure, _DRIVER_OBJECT::DriverStart, _SYSTEM_SET_TIME_ADJUST_INFORMATION::Enable, _SYSTEM_GDI_DRIVER_INFORMATION::EntryPoint, EVENT_MODIFY_STATE, ExAllocatePoolWithTag, ExApplyCodePatch(), except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), _SYSTEM_GDI_DRIVER_INFORMATION::ExportSectionPointer, ExpRegisterFirmwareTableInformationHandler(), ExpUpdateComPlusPackage(), ExpWdHandler, ExpWdHandlerContext, ExRaiseStatus(), FALSE, FLG_BOOTONLY_VALID_BITS, FLG_KERNELMODE_VALID_BITS, IMAGE_DIRECTORY_ENTRY_EXPORT, _SYSTEM_GDI_DRIVER_INFORMATION::ImageAddress, _SYSTEM_GDI_DRIVER_INFORMATION::ImageLength, IoConfigureCrashDump(), KdUpdateTimeSlipEvent(), KeGetCurrentIrql(), KeGetPreviousMode, KeMaximumIncrement, KernelMode, KeTimeAdjustment, KeTimeSynchronization, KiAdjustDpcThreshold, KiIdealDpcRate, KiMaximumDpcQueueDepth, KiMinimumDpcRate, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, memcmp(), MM_LOAD_IMAGE_IN_SESSION, MmAddVerifierEntry(), MmAddVerifierThunks(), MmAdjustWorkingSetSizeEx(), MmCreateMirror(), MmIsSessionLeaderProcess, MmLoadSystemImage(), MmRemoveVerifierEntry(), MmSessionCreate(), MmSessionDelete(), MmSessionSetUnloadAddress(), MmSetVerifierInformation(), MmUnloadSystemImage(), NT_SUCCESS, NtGlobalFlag, NULL, ObReferenceObjectByHandle, _IMAGE_NT_HEADERS::OptionalHeader, PAGED_CODE, PagedPool, ProbeAndReadUnicodeStringEx, ProbeForRead, ProbeForReadSmallStructure, ProbeForWriteUlong, PsChangeQuantumTable(), PsGetCurrentProcess(), RtlCopyMemory, RtlImageDirectoryEntryToData(), RtlImageNtHeader(), RtlZeroMemory, _SYSTEM_GDI_DRIVER_INFORMATION::SectionPointer, SeDebugPrivilege, SeIncreaseQuotaPrivilege, SeLoadDriverPrivilege, SeSinglePrivilegeCheck(), SeSystemtimePrivilege, SeTcbPrivilege, SharedNtdll32ExpInterlockedPopEntrySListEnd, SharedNtdll32ExpInterlockedPopEntrySListFault, SharedNtdll32ExpInterlockedPopEntrySListResume, SharedUserData, _IMAGE_OPTIONAL_HEADER::SizeOfImage, Status, STATUS_ACCESS_DENIED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_IMAGE_FORMAT, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_2, STATUS_NO_MEMORY, STATUS_NOT_IMPLEMENTED, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, SystemComPlusPackage, SystemCrashDumpStateInformation, SystemDpcBehaviorInformation, SystemExtendServiceTableInformation, SystemFileCacheInformation, SystemFileCacheInformationEx, SystemFlagsInformation, SystemHotpatchInformation, SystemLoadGdiDriverInformation, SystemLoadGdiDriverInSystemSpace, SystemMirrorMemoryInformation, SystemPerformanceTraceInformation, SystemPrefetcherInformation, SystemPrioritySeperation, SystemRegisterFirmwareTableInformationHandler, SystemRegistryQuotaInformation, SystemSessionCreate, SystemSessionDetach, SystemTimeAdjustmentInformation, SystemTimeSlipNotification, SystemUnloadGdiDriverInformation, SystemVerifierAddDriverInformation, SystemVerifierInformation, SystemVerifierRemoveDriverInformation, SystemVerifierThunkExtend, SystemWatchdogTimerHandler, SystemWatchdogTimerInformation, SystemWow64SharedInformation, _SYSTEM_SET_TIME_ADJUST_INFORMATION::TimeAdjustment, TRUE, UlongToPtr, UserMode, WIN32K_PATH_SIZE, Win32kFullPath, and ZwSetSystemInformation().
Referenced by WmipRegisterFirmwareProviders().
NTSYSCALLAPI NTSTATUS NTAPI NtSetSystemTime (__in_opt PLARGE_INTEGER SystemTime, __out_opt PLARGE_INTEGER PreviousTime)
NTSYSCALLAPI NTSTATUS NTAPI NtSetTimer (__in HANDLE TimerHandle, __in PLARGE_INTEGER DueTime, __in_opt PTIMER_APC_ROUTINE TimerApcRoutine, __in_opt PVOID TimerContext, __in BOOLEAN ResumeTimer, __in_opt LONG Period, __out_opt PBOOLEAN PreviousState)
Definition at line 981 of file timer.c.
References _ETIMER::ActiveTimerListEntry, _ETHREAD::ActiveTimerListHead, _ETHREAD::ActiveTimerListLock, _ETIMER::ApcAssociated, ARGUMENT_PRESENT, CONTAINING_RECORD, CurrentApcEnvironment, ExAcquireSpinLock, ExAcquireSpinLockAtDpcLevel, except, EXCEPTION_EXECUTE_HANDLER, ExpTimerApcRoutine(), ExpWakeTimerListLock, ExReleaseSpinLock, ExReleaseSpinLockFromDpcLevel, FALSE, _LIST_ENTRY::Flink, InsertTailList(), KeCancelTimer(), KeGetPreviousMode, KeInitializeApc(), KeReadStateTimer(), KeRemoveQueueApc(), KeRemoveQueueDpc(), KernelMode, KeSetTimerEx(), _ETIMER::KeTimer, _ETIMER::Lock, NOTHING, NT_SUCCESS, NULL, ObDereferenceObjectEx(), ObReferenceObjectByHandle, _ETIMER::Period, PoWakeTimerSupported, ProbeForReadSmallStructure, ProbeForWriteBoolean, PsGetCurrentThread(), RemoveEntryList(), Status, STATUS_INVALID_PARAMETER_6, STATUS_TIMER_RESUME_IGNORED, _ETHREAD::Tcb, _KAPC::Thread, TIMER_MODIFY_STATE, _ETIMER::TimerApc, _ETIMER::TimerDpc, TRUE, _ETIMER::WakeTimer, and _ETIMER::WakeTimerListEntry.
NTSYSCALLAPI NTSTATUS NTAPI NtSetTimerResolution (__in ULONG DesiredTime, __in BOOLEAN SetResolution, __out PULONG ActualTime)
NTSYSCALLAPI NTSTATUS NTAPI NtSetUuidSeed (__in PCHAR Seed)
Definition at line 541 of file uuid.c.
References ASSERT, CACHE_LOCAL_ONLY, CACHE_VALID, except, EXCEPTION_EXECUTE_HANDLER, ExpUuidCacheValid, ExRaiseStatus(), FALSE, KeGetPreviousMode, KernelMode, _UUID_CACHED_VALUES_STRUCT::NodeId, NT_SUCCESS, PAGED_CODE, ProbeForReadSmallStructure, RtlCompareMemory(), RtlCopyMemory, SeCaptureSubjectContext(), SEED_SIZE, SeQueryAuthenticationIdToken(), SeQuerySubjectContextToken, SeReleaseSubjectContext(), Status, STATUS_ACCESS_DENIED, STATUS_SUCCESS, SYSTEM_LUID, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtShutdownSystem (__in SHUTDOWN_ACTION Action)
Definition at line 460 of file exinit.c.
References NtSetSystemPowerState(), POWER_ACTION_CRITICAL, POWER_ACTION_DISABLE_WAKES, POWER_ACTION_OVERRIDE_APPS, PowerActionShutdown, PowerActionShutdownOff, PowerActionShutdownReset, PowerSystemSleeping3, ShutdownNoReboot, ShutdownPowerOff, ShutdownReboot, Status, and STATUS_INVALID_PARAMETER.
NTSYSCALLAPI NTSTATUS NTAPI NtStartProfile (__in HANDLE ProfileHandle)
Definition at line 499 of file profile.c.
References ACTIVE_PROFILE_LIMIT, _EPROFILE::Affinity, ASSERT, _EPROFILE::BucketSize, _EPROFILE::Buffer, _EPROFILE::BufferSize, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, Executive, ExFreePool(), ExpCurrentProfileUsage, FALSE, IoWriteAccess, KeGetPreviousMode, KeInitializeProfile(), KeReleaseMutex(), KernelMode, KeStartProfile(), KeWaitForSingleObject(), _EPROFILE::LockedBufferAddress, _EPROFILE::Mdl, MmCached, MmInitializeMdl, MmMapLockedPagesSpecifyCache(), MmProbeAndLockPages(), MmSizeOfMdl(), MmUnlockPages(), NonPagedPool, NormalPagePriority, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _EPROFILE::Process, PROFILE_CONTROL, _EPROFILE::ProfileObject, ProfileObject, _EPROFILE::ProfileSource, _EPROFILE::RangeBase, _EPROFILE::RangeSize, _EPROFILE::Segment, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_PROFILING_AT_LIMIT, STATUS_PROFILING_NOT_STOPPED, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtStopProfile (__in HANDLE ProfileHandle)
Definition at line 651 of file profile.c.
References ASSERT, Executive, ExFreePool(), FALSE, KeGetPreviousMode, KeReleaseMutex(), KernelMode, KeStopProfile(), KeWaitForSingleObject(), _EPROFILE::LockedBufferAddress, _EPROFILE::Mdl, MmUnlockPages(), MmUnmapLockedPages(), NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PROFILE_CONTROL, _EPROFILE::ProfileObject, ProfileObject, Status, STATUS_PROFILING_NOT_STARTED, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtSystemDebugControl (__in SYSDBG_COMMAND Command, __inout_bcount_opt(InputBufferLength) PVOID InputBuffer, __in ULONG InputBufferLength, __out_bcount_opt(OutputBufferLength) PVOID OutputBuffer, __in ULONG OutputBufferLength, __out_opt PULONG ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtTranslateFilePath (__in PFILE_PATH InputFilePath, __in ULONG OutputType, __out_bcount_opt *OutputFilePathLength PFILE_PATH OutputFilePath, __inout_opt PULONG OutputFilePathLength)
NTSYSCALLAPI NTSTATUS NTAPI NtWaitForKeyedEvent (__in HANDLE KeyedEventHandle, __in PVOID KeyValue, __in BOOLEAN Alertable, __in_opt PLARGE_INTEGER Timeout)
Definition at line 552 of file keyedevent.c.
References ASSERT, CONTAINING_RECORD, except, Executive, ExSystemExceptionFilter(), FALSE, _LIST_ENTRY::Flink, InitializeListHead(), InsertTailList(), IsListEmpty, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeLeaveCriticalRegionThread(), KeReleaseSemaphore(), KernelMode, KeWaitForSingleObject(), KEYEDEVENT_WAIT, _ETHREAD::KeyedEventInUse, _ETHREAD::KeyedWaitChain, _ETHREAD::KeyedWaitSemaphore, _ETHREAD::KeyedWaitValue, KEYVALUE_RELEASE, LOCK_KEYED_EVENT_EXCLUSIVE, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PASSIVE_LEVEL, ProbeForRead, PsGetCurrentProcessByThread, PsGetCurrentThread(), RemoveEntryList(), SEMAPHORE_INCREMENT, Status, STATUS_INVALID_PARAMETER_1, STATUS_SUCCESS, _ETHREAD::Tcb, THREAD_TO_PROCESS, TRUE, UNLOCK_KEYED_EVENT_EXCLUSIVE, UNLOCK_KEYED_EVENT_EXCLUSIVE_UNSAFE, and _KEYED_EVENT_OBJECT::WaitQueue.
NTSYSCALLAPI NTSTATUS NTAPI NtWaitHighEventPair (__in HANDLE EventPairHandle)
Definition at line 385 of file eventpr.c.
References FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeWaitForHighEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.
NTSYSCALLAPI NTSTATUS NTAPI NtWaitLowEventPair (__in HANDLE EventPairHandle)
Definition at line 325 of file eventpr.c.
References FALSE, KeGetPreviousMode, _EEVENT_PAIR::KernelEventPair, KeWaitForLowEventPair, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, Status, and SYNCHRONIZE.