Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/debug.c File Reference
debug.c File Reference
#include "ki.h"
Macros
#define FREEZE_ACTIVE 0x20
#define IDBG 1
Functions
BOOLEAN KeFreezeExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
KCONTINUE_STATUS KeSwitchFrozenProcessor (IN ULONG ProcessorNumber)
VOID KeThawExecution (IN BOOLEAN Enable)
VOID KiFreezeTargetExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
VOID KiPollFreezeExecution (VOID)
Variables
PKDEBUG_ROUTINE KiDebugRoutine = &KdpStub
PKPRCB KiFreezeOwner
KIRQL KiOldIrql
Macro Definition Documentation
#define FREEZE_ACTIVE 0x20
Definition at line 41 of file debug.c.
Referenced by KeFreezeExecution(), KeSwitchFrozenProcessor(), and KiFreezeTargetExecution().
#define IDBG 1
Definition at line 33 of file debug.c.
Function Documentation
BOOLEAN KeFreezeExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 54 of file debug.c.
References AFFINITY_MASK, ClearMember, Count, FALSE, Flag, FREEZE_ACTIVE, FREEZE_BACKUP, FREEZE_FROZEN, FREEZE_OWNER, FREEZE_SKIPPED_PROCESSOR, FrozenState, HIGH_LEVEL, _KPRCB::IpiFrozen, KeAcquireSpinLockAtDpcLevel(), KeActiveProcessors, KeBugCheckActive, KeDisableInterrupts(), KeEnableInterrupts(), KeFindFirstSetLeftAffinity, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeRaiseIrql, KeStallExecutionProcessor(), KeTryToAcquireSpinLockAtDpcLevel(), KeYieldProcessor, KiFreezeExecutionLock, KiFreezeFlag, KiFreezeLockBackup, KiIpiServiceRoutine(), KiOldIrql, KiProcessorBlock, KiSendFreeze(), _KPRCB::Number, _KPRCB::SkipTick, TARGET_FROZEN, TRUE, and UNREFERENCED_PARAMETER.
KCONTINUE_STATUS KeSwitchFrozenProcessor (IN ULONG ProcessorNumber)
Definition at line 386 of file debug.c.
References ContinueError, ContinueNextProcessor, ContinueProcessorReselected, FREEZE_ACTIVE, FREEZE_OWNER, FrozenState, _KPRCB::IpiFrozen, KeGetCurrentPrcb(), KeNumberProcessors, KeYieldProcessor, KiProcessorBlock, TARGET_FROZEN, and UNREFERENCED_PARAMETER.
VOID KeThawExecution (IN BOOLEAN Enable)
Definition at line 448 of file debug.c.
References Flag, FREEZE_BACKUP, KeEnableInterrupts(), KeFlushCurrentTb(), KeLowerIrql, KeSweepCurrentDcache, KeSweepCurrentIcache, KiFreezeExecutionLock, KiFreezeFlag, KiFreezeLockBackup, KiOldIrql, KiReleaseSpinLock(), KiSendThawExecution(), and TRUE.
VOID KiFreezeTargetExecution (IN PKTRAP_FRAME TrapFrame, IN PKEXCEPTION_FRAME ExceptionFrame)
Definition at line 255 of file debug.c.
References CONTEXT_TO_PROGRAM_COUNTER, _KPROCESSOR_STATE::ContextFrame, ContinueError, ContinueNextProcessor, DbgBreakPoint(), _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, _EXCEPTION_RECORD::ExceptionRecord, FALSE, FREEZE_ACTIVE, FrozenState, HIGH_LEVEL, _KPRCB::IpiFrozen, KeBugCheckActive, KeDisableInterrupts(), KeEnableInterrupts(), KeFlushCurrentTb(), KeGetCurrentPrcb(), KeLowerIrql, KeRaiseIrql, KeSweepCurrentDcache, KeSweepCurrentIcache, KeYieldProcessor, KiDebugSwitchRoutine, KiFreezeExecutionLock, KiFreezeLockBackup, KiRestoreProcessorState(), KiSaveProcessorState(), NULL, _KPRCB::ProcessorState, RtlZeroMemory, RUNNING, _KPRCB::SkipTick, Status, STATUS_WAKE_SYSTEM_DEBUGGER, TARGET_FROZEN, TRUE, and UNREFERENCED_PARAMETER.
Referenced by KiAcquireQueuedSpinLockCheckForFreeze(), KiCheckForFreezeExecution(), and KiPollFreezeExecution().
VOID KiPollFreezeExecution (VOID)
Definition at line 529 of file debug.c.
References InterlockedExchangeAdd(), IPI_FREEZE, KeGetCurrentPrcb(), KeYieldProcessor, KiFreezeTargetExecution(), NULL, and _KPRCB::RequestSummary.
Referenced by KeBugCheck2(), KiCalibrateTimeAdjustment(), and KiIpiGenericCallTarget().
Variable Documentation
PKDEBUG_ROUTINE KiDebugRoutine = &KdpStub
Definition at line 28 of file debug.c.
Referenced by KiDispatchException().
PKPRCB KiFreezeOwner
Definition at line 50 of file debug.c.
KIRQL KiOldIrql
Definition at line 47 of file debug.c.
Referenced by KeFreezeExecution(), and KeThawExecution().