Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/hal.h File Reference
hal.h File Reference
#include "pshpack1.h"
#include "poppack.h"
Data Structures
struct _BUS_HANDLER
struct _CMC_DRIVER_INFO
struct _CPE_DRIVER_INFO
struct _DEVICE_CONTROL_CONTEXT
struct _DEVICE_DESCRIPTION
struct _DMA_ADAPTER
struct _DMA_OPERATIONS
struct _HAL_AMLI_BAD_IO_ADDRESS_LIST
struct _HAL_BUS_INFORMATION
struct _HAL_CALLBACKS
struct _HAL_DEVICE_CONTROL
struct _HAL_ERROR_INFO
struct _HAL_MCA_INTERFACE
struct _HAL_NUMA_TOPOLOGY_INTERFACE
struct _HAL_PLATFORM_INFORMATION
struct _HAL_POWER_INFORMATION
struct _HAL_PROCESSOR_FEATURE
struct _HAL_PROCESSOR_SPEED_INFO
struct _HAL_PROFILE_SOURCE_INFORMATION
struct _HAL_PROFILE_SOURCE_INFORMATION_EX
struct _HAL_PROFILE_SOURCE_INTERVAL
struct _HAL_PROFILE_SOURCE_LIST
struct _MAP_REGISTER_ENTRY
struct _MCA_DRIVER_INFO
struct _OEM_FONT_FILE_HEADER
struct _PARTITION_DESCRIPTOR
struct _PM_DISPATCH_TABLE
struct _SCATTER_GATHER_ELEMENT
struct _SCATTER_GATHER_LIST
struct _SUPPORTED_RANGE
struct _SUPPORTED_RANGES
struct DEBUG_DEVICE_ADDRESS
struct DEBUG_DEVICE_DESCRIPTOR
struct DEBUG_MEMORY_REQUIREMENTS
struct HAL_DISPATCH
struct HAL_PRIVATE_DISPATCH
struct KERNEL_ERROR_HANDLER_INFO
Macros
#define BOOT_RECORD_SIGNATURE (0xaa55)
#define BOOT_SIGNATURE_OFFSET ((0x200 / 2) - 1)
#define BUS_HANDLER_VERSION 1
#define BUS_SUPPORTED_RANGE_VERSION 1
#define CmcKernelToken KernelReserved[1]
#define CpeKernelToken KernelReserved[2]
#define DEVICE_DESCRIPTION_VERSION 0
#define DEVICE_DESCRIPTION_VERSION1 1
#define DEVICE_DESCRIPTION_VERSION2 2
#define HAL_CMC_DISABLED HAL_MCE_DISABLED
#define HAL_CMC_INTERRUPTS_BASED HAL_MCE_INTERRUPTS_BASED
#define HAL_CPE_DISABLED HAL_MCE_DISABLED
#define HAL_CPE_INTERRUPTS_BASED HAL_MCE_INTERRUPTS_BASED
#define HAL_DISPATCH_VERSION 3
#define HAL_ERROR_INFO_VERSION 0x2
#define HAL_MCA_DISABLED HAL_MCE_DISABLED
#define HAL_MCA_INTERRUPTS_BASED HAL_MCE_INTERRUPTS_BASED
#define HAL_MCE_DISABLED ((ULONG)0)
#define HAL_MCE_INTERRUPTS_BASED ((ULONG)-1)
#define HAL_PLATFORM_ACPI_TABLES_CACHED 0x20L
#define HAL_PLATFORM_DISABLE_PTCG 0x04L
#define HAL_PLATFORM_DISABLE_UC_MAIN_MEMORY 0x08L
#define HAL_PLATFORM_DISABLE_WRITE_COMBINING 0x01L
#define HAL_PLATFORM_ENABLE_WRITE_COMBINING_MMIO 0x10L
#define HAL_PRIVATE_DISPATCH_VERSION 2
#define HalAllocateMapRegisters HALPDISPATCH->HalAllocateMapRegisters
#define HalDereferenceBusHandler HALDISPATCH->HalDereferenceBusHandler
#define HALDISPATCH (&HalDispatchTable)
#define HalDispatchTableVersion HALDISPATCH->Version
#define HalEndMirroring HALDISPATCH->HalEndMirroring
#define HalEndOfBoot HALDISPATCH->HalEndOfBoot
#define HalGetDmaAdapter HALDISPATCH->HalGetDmaAdapter
#define HalGetDmaAlignmentRequirement() 1L
#define HalGetInterruptTranslator HALDISPATCH->HalGetInterruptTranslator
#define HalHaltSystem HALPDISPATCH->HalHaltSystem
#define HalHandlerForBus HALPDISPATCH->HalHandlerForBus
#define HalHandlerForConfigSpace HALPDISPATCH->HalHandlerForConfigSpace
#define HalInitPnpDriver HALDISPATCH->HalInitPnpDriver
#define HalInitPowerManagement HALDISPATCH->HalInitPowerManagement
#define HalLocateHiberRanges HALPDISPATCH->HalLocateHiberRanges
#define HalMirrorPhysicalMemory HALDISPATCH->HalMirrorPhysicalMemory
#define HalMirrorVerify HALDISPATCH->HalMirrorVerify
#define HALPDISPATCH (&HalPrivateDispatchTable)
#define HalQueryBusSlots HALDISPATCH->HalQueryBusSlots
#define HalQuerySystemInformation HALDISPATCH->HalQuerySystemInformation
#define HalReferenceBusHandler HALDISPATCH->HalReferenceBusHandler
#define HalReferenceHandlerForBus HALDISPATCH->HalReferenceHandlerForBus
#define HalRegisterBusHandler HALPDISPATCH->HalRegisterBusHandler
#define HalResetDisplay HALPDISPATCH->HalResetDisplay
#define HalSetSystemInformation HALDISPATCH->HalSetSystemInformation
#define HalSetWakeAlarm HALPDISPATCH->HalSetWakeAlarm
#define HalSetWakeEnable HALPDISPATCH->HalSetWakeEnable
#define HalStartMirroring HALDISPATCH->HalStartMirroring
#define HalVectorToIDTEntry HALPDISPATCH->HalVectorToIDTEntry
#define KdCheckPowerButton HALPDISPATCH->KdCheckPowerButton
#define KdGetAcpiTablePhase0 HALPDISPATCH->KdGetAcpiTablePhase0
#define KdMapPhysicalMemory64 HALPDISPATCH->KdMapPhysicalMemory64
#define KdReleasePciDeviceForDebugging HALPDISPATCH->KdReleasePciDeviceForDebugging
#define KdSetupPciDeviceForDebugging HALPDISPATCH->KdSetupPciDeviceForDebugging
#define KdUnmapVirtualAddress HALPDISPATCH->KdUnmapVirtualAddress
#define KERNEL_ERROR_HANDLER_VERSION 0x2
#define KERNEL_MCA_CORRECTED 0x2
#define KERNEL_MCA_PREVIOUS 0x1
#define KERNEL_MCA_UNKNOWN 0x0
#define KERNEL_MCE_EVENTTYPE(_Reserved) ((USHORT)(ULONG_PTR)(_Reserved))
#define KERNEL_MCE_EVENTTYPE_CMC 0x02
#define KERNEL_MCE_EVENTTYPE_CPE 0x03
#define KERNEL_MCE_EVENTTYPE_INIT 0x01
#define KERNEL_MCE_EVENTTYPE_MASK 0xffff
#define KERNEL_MCE_EVENTTYPE_MCA 0x00
#define KERNEL_MCE_OPERATION(_Reserved) ((USHORT)((((ULONG_PTR)(_Reserved)) >> KERNEL_MCE_OPERATION_SHIFT) & KERNEL_MCE_OPERATION_MASK))
#define KERNEL_MCE_OPERATION_CLEAR_STATE_INFO 0x1
#define KERNEL_MCE_OPERATION_GET_STATE_INFO 0x2
#define KERNEL_MCE_OPERATION_MASK 0xffff
#define KERNEL_MCE_OPERATION_SHIFT 16
#define McaKernelToken KernelReserved[0]
#define NUM_PARTITION_TABLE_ENTRIES 4
#define OEM_FONT_CHARACTER_SET 255
#define OEM_FONT_FAMILY (3 << 4)
#define OEM_FONT_ITALIC 0
#define OEM_FONT_STRIKEOUT 0
#define OEM_FONT_TYPE 0
#define OEM_FONT_UNDERLINE 0
#define OEM_FONT_VERSION 0x200
#define PARTITION_ACTIVE_FLAG 0x80
#define PARTITION_BUFFER_SIZE 2048
#define PARTITION_TABLE_OFFSET (0x1be / 2)
Typedefs
typedef struct _BUS_HANDLER BUS_HANDLER
typedef IN ULONG BusNumber
typedef struct _CMC_DRIVER_INFO CMC_DRIVER_INFO
typedef struct _CPE_DRIVER_INFO CPE_DRIVER_INFO
typedef struct _DEVICE_CONTROL_CONTEXT DEVICE_CONTROL_CONTEXT
typedef struct _DEVICE_DESCRIPTION DEVICE_DESCRIPTION
typedef struct _DMA_ADAPTER DMA_ADAPTER
typedef struct _DMA_OPERATIONS DMA_OPERATIONS
typedef struct _HAL_AMLI_BAD_IO_ADDRESS_LIST HAL_AMLI_BAD_IO_ADDRESS_LIST
typedef struct _HAL_BUS_INFORMATION HAL_BUS_INFORMATION
typedef struct _HAL_CALLBACKS HAL_CALLBACKS
typedef struct _HAL_DEVICE_CONTROL HAL_DEVICE_CONTROL_CONTEXT
typedef enum _HAL_DISPLAY_BIOS_INFORMATION HAL_DISPLAY_BIOS_INFORMATION
typedef struct _HAL_ERROR_INFO HAL_ERROR_INFO
typedef struct _HAL_MCA_INTERFACE HAL_MCA_INTERFACE
typedef struct _HAL_NUMA_TOPOLOGY_INTERFACE HAL_NUMA_TOPOLOGY_INTERFACE
typedef struct _HAL_PLATFORM_INFORMATION HAL_PLATFORM_INFORMATION
typedef struct _HAL_POWER_INFORMATION HAL_POWER_INFORMATION
typedef struct _HAL_PROCESSOR_FEATURE HAL_PROCESSOR_FEATURE
typedef struct _HAL_PROCESSOR_SPEED_INFO HAL_PROCESSOR_SPEED_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION HAL_PROFILE_SOURCE_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION_EX HAL_PROFILE_SOURCE_INFORMATION_EX
typedef struct _HAL_PROFILE_SOURCE_INTERVAL HAL_PROFILE_SOURCE_INTERVAL
typedef struct _HAL_PROFILE_SOURCE_LIST HAL_PROFILE_SOURCE_LIST
typedef enum _HAL_QUERY_INFORMATION_CLASS HAL_QUERY_INFORMATION_CLASS
typedef enum _HAL_SET_INFORMATION_CLASS HAL_SET_INFORMATION_CLASS
typedef ULONG HALNUMAPAGETONODE
typedef BOOLEAN(* KERNEL_CMC_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
typedef BOOLEAN(* KERNEL_CPE_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
typedef BOOLEAN(* KERNEL_MCA_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
typedef BOOLEAN(* KERNEL_MCE_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
typedef struct _MAP_REGISTER_ENTRY MAP_REGISTER_ENTRY
typedef struct _MCA_DRIVER_INFO MCA_DRIVER_INFO
typedef struct _OEM_FONT_FILE_HEADER OEM_FONT_FILE_HEADER
typedef NTSTATUS(* PADJUSTRESOURCELIST) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN OUT PIO_RESOURCE_REQUIREMENTS_LIST *pResourceList)
typedef NTSTATUS(* PALLOCATE_ADAPTER_CHANNEL) (IN PDMA_ADAPTER DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
typedef PVOID(* PALLOCATE_COMMON_BUFFER) (IN PDMA_ADAPTER DmaAdapter, IN ULONG Length, OUT PPHYSICAL_ADDRESS LogicalAddress, IN BOOLEAN CacheEnabled)
typedef struct _PARTITION_DESCRIPTOR PARTITION_DESCRIPTOR
typedef NTSTATUS(* PASSIGNSLOTRESOURCES) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN ULONG SlotNumber, IN OUT PCM_RESOURCE_LIST *AllocatedResources)
typedef NTSTATUS(* PBUILD_MDL_FROM_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PSCATTER_GATHER_LIST ScatterGather, IN PMDL OriginalMdl, OUT PMDL *TargetMdl)
typedef NTSTATUS(* PBUILD_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PDRIVER_LIST_CONTROL ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice, IN PVOID ScatterGatherBuffer, IN ULONG ScatterGatherLength)
typedef struct _BUS_HANDLER * PBUS_HANDLER
typedef NTSTATUS(* PCALCULATE_SCATTER_GATHER_LIST_SIZE) (IN PDMA_ADAPTER DmaAdapter, IN OPTIONAL PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, OUT PULONG ScatterGatherListSize, OUT OPTIONAL PULONG pNumberOfMapRegisters)
typedef struct _CMC_DRIVER_INFO * PCMC_DRIVER_INFO
typedef struct _CPE_DRIVER_INFO * PCPE_DRIVER_INFO
typedef struct DEBUG_DEVICE_ADDRESS * PDEBUG_DEVICE_ADDRESS
typedef struct DEBUG_DEVICE_DESCRIPTOR * PDEBUG_DEVICE_DESCRIPTOR
typedef struct DEBUG_MEMORY_REQUIREMENTS * PDEBUG_MEMORY_REQUIREMENTS
typedef NTSTATUS(* PDEVICE_CONTROL) (IN PHAL_DEVICE_CONTROL_CONTEXT Context)
typedef VOID(* PDEVICE_CONTROL_COMPLETION) (IN struct _DEVICE_CONTROL_CONTEXT *ControlContext)
typedef struct _DEVICE_CONTROL_CONTEXT * PDEVICE_CONTROL_CONTEXT
typedef struct _DEVICE_DESCRIPTION * PDEVICE_DESCRIPTION
typedef struct _DMA_ADAPTER * PDMA_ADAPTER
typedef struct _DMA_OPERATIONS * PDMA_OPERATIONS
typedef VOID(* PDRIVER_CMC_EXCEPTION_CALLBACK) (IN PVOID Context, IN PCMC_EXCEPTION CmcLog)
typedef VOID(* PDRIVER_CPE_EXCEPTION_CALLBACK) (IN PVOID Context, IN PCPE_EXCEPTION CmcLog)
typedef VOID(* PDRIVER_EXCPTN_CALLBACK) (IN PVOID Context, IN PMCA_EXCEPTION BankLog)
typedef VOID(* PDRIVER_LIST_CONTROL) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp, IN PSCATTER_GATHER_LIST ScatterGather, IN PVOID Context)
typedef PDRIVER_EXCPTN_CALLBACK PDRIVER_MCA_EXCEPTION_CALLBACK
typedef BOOLEAN(* PFLUSH_ADAPTER_BUFFERS) (IN PDMA_ADAPTER DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN ULONG Length, IN BOOLEAN WriteToDevice)
typedef VOID(* PFREE_ADAPTER_CHANNEL) (IN PDMA_ADAPTER DmaAdapter)
typedef VOID(* PFREE_COMMON_BUFFER) (IN PDMA_ADAPTER DmaAdapter, IN ULONG Length, IN PHYSICAL_ADDRESS LogicalAddress, IN PVOID VirtualAddress, IN BOOLEAN CacheEnabled)
typedef VOID(* PFREE_MAP_REGISTERS) (IN PDMA_ADAPTER DmaAdapter, PVOID MapRegisterBase, ULONG NumberOfMapRegisters)
typedef ULONG(* PGET_DMA_ALIGNMENT) (IN PDMA_ADAPTER DmaAdapter)
typedef NTSTATUS(* PGET_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PDRIVER_LIST_CONTROL ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice)
typedef ULONG(* PGET_SET_DEVICE_INSTANCE_DATA) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN PDEVICE_HANDLER_OBJECT DeviceHandler, IN ULONG DataType, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
typedef ULONG(* PGETINTERRUPTVECTOR) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG BusInterruptLevel, IN ULONG BusInterruptVector, OUT PKIRQL Irql, OUT PKAFFINITY Affinity)
typedef ULONG(* PGETSETBUSDATA) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
typedef struct _HAL_AMLI_BAD_IO_ADDRESS_LIST * PHAL_AMLI_BAD_IO_ADDRESS_LIST
typedef struct _HAL_BUS_INFORMATION * PHAL_BUS_INFORMATION
typedef struct _HAL_CALLBACKS * PHAL_CALLBACKS
typedef struct _HAL_DEVICE_CONTROL * PHAL_DEVICE_CONTROL_CONTEXT
typedef struct HAL_DISPATCH * PHAL_DISPATCH
typedef enum _HAL_DISPLAY_BIOS_INFORMATION * PHAL_DISPLAY_BIOS_INFORMATION
typedef struct _HAL_ERROR_INFO * PHAL_ERROR_INFO
typedef struct _HAL_PLATFORM_INFORMATION * PHAL_PLATFORM_INFORMATION
typedef struct _HAL_POWER_INFORMATION * PHAL_POWER_INFORMATION
typedef struct HAL_PRIVATE_DISPATCH * PHAL_PRIVATE_DISPATCH
typedef struct _HAL_PROCESSOR_SPEED_INFO * PHAL_PROCESSOR_SPEED_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION * PHAL_PROFILE_SOURCE_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION_EX * PHAL_PROFILE_SOURCE_INFORMATION_EX
typedef struct _HAL_PROFILE_SOURCE_INTERVAL * PHAL_PROFILE_SOURCE_INTERVAL
typedef struct _HAL_PROFILE_SOURCE_LIST * PHAL_PROFILE_SOURCE_LIST
typedef enum _HAL_QUERY_INFORMATION_CLASS * PHAL_QUERY_INFORMATION_CLASS
typedef BOOLEAN(* PHAL_RESET_DISPLAY_PARAMETERS) (IN ULONG Columns, IN ULONG Rows)
typedef enum _HAL_SET_INFORMATION_CLASS * PHAL_SET_INFORMATION_CLASS
typedef NTSTATUS(* pHalAllocateMapRegisters) (IN struct _ADAPTER_OBJECT *DmaAdapter, IN ULONG NumberOfMapRegisters, IN ULONG BaseAddressCount, OUT PMAP_REGISTER_ENTRY MapRegsiterArray)
typedef NTSTATUS(* pHalAssignSlotResources) (IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN INTERFACE_TYPE BusType, IN ULONG BusNumber, IN ULONG SlotNumber, IN OUT PCM_RESOURCE_LIST *AllocatedResources)
typedef NTSTATUS(* pHalEndMirroring) (IN ULONG PassNumber)
typedef VOID(* pHalEndOfBoot) (VOID)
typedef VOID(FASTCALL * pHalExamineMBR) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG MBRTypeIdentifier, OUT PVOID *Buffer)
typedef BOOLEAN(* pHalFindBusAddressTranslation) (IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress, IN OUT PULONG_PTR Context, IN BOOLEAN NextBus)
typedef struct _DMA_ADAPTER *(* pHalGetDmaAdapter) (IN PVOID Context, IN struct _DEVICE_DESCRIPTION *DeviceDescriptor, OUT PULONG NumberOfMapRegisters)
typedef NTSTATUS(* pHalGetInterruptTranslator) (IN INTERFACE_TYPE ParentInterfaceType, IN ULONG ParentBusNumber, IN INTERFACE_TYPE BridgeInterfaceType, IN USHORT Size, IN USHORT Version, OUT PTRANSLATOR_INTERFACE Translator, OUT PULONG BridgeBusNumber)
typedef VOID(* pHalHaltSystem) (VOID)
typedef NTSTATUS(* pHalInitPnpDriver) (VOID)
typedef NTSTATUS(* pHalInitPowerManagement) (IN PPM_DISPATCH_TABLE PmDriverDispatchTable, OUT PPM_DISPATCH_TABLE *PmHalDispatchTable)
typedef VOID(FASTCALL * pHalIoAssignDriveLetters) (IN struct _LOADER_PARAMETER_BLOCK *LoaderBlock, IN PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, OUT PSTRING NtSystemPathString)
typedef NTSTATUS(FASTCALL * pHalIoReadPartitionTable) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN BOOLEAN ReturnRecognizedPartitions, OUT struct _DRIVE_LAYOUT_INFORMATION **PartitionBuffer)
typedef NTSTATUS(* PHALIOREADWRITEHANDLER) (IN BOOLEAN fRead, IN ULONG dwAddr, IN ULONG dwSize, IN OUT PULONG pdwData)
typedef NTSTATUS(FASTCALL * pHalIoSetPartitionInformation) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG PartitionNumber, IN ULONG PartitionType)
typedef NTSTATUS(FASTCALL * pHalIoWritePartitionTable) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG SectorsPerTrack, IN ULONG NumberOfHeads, IN struct _DRIVE_LAYOUT_INFORMATION *PartitionBuffer)
typedef VOID(* pHalLocateHiberRanges) (IN PVOID MemoryMap)
typedef VOID(* PHALMCAINTERFACELOCK) (VOID)
typedef NTSTATUS(* PHALMCAINTERFACEREADREGISTER) (IN UCHAR BankNumber, IN OUT PVOID Exception)
typedef VOID(* PHALMCAINTERFACEUNLOCK) (VOID)
typedef NTSTATUS(* pHalMirrorPhysicalMemory) (IN PHYSICAL_ADDRESS PhysicalAddress, IN LARGE_INTEGER NumberOfBytes)
typedef NTSTATUS(* pHalMirrorVerify) (IN PHYSICAL_ADDRESS PhysicalAddress, IN LARGE_INTEGER NumberOfBytes)
typedef HALNUMAPAGETONODE(* PHALNUMAPAGETONODE) (IN ULONG_PTR PhysicalPageNumber)
typedef NTSTATUS(* PHALNUMAQUERYPROCESSORNODE) (IN ULONG ProcessorNumber, OUT PUSHORT Identifier, OUT PUCHAR Node)
typedef NTSTATUS(* pHalQueryBusSlots) (IN PBUS_HANDLER BusHandler, IN ULONG BufferSize, OUT PULONG SlotNumbers, OUT PULONG ReturnedLength)
typedef NTSTATUS(* pHalQuerySystemInformation) (IN HAL_QUERY_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN OUT PVOID Buffer, OUT PULONG ReturnedLength)
typedef NTSTATUS(* pHalRegisterBusHandler) (IN INTERFACE_TYPE InterfaceType, IN BUS_DATA_TYPE AssociatedConfigurationSpace, IN ULONG BusNumber, IN INTERFACE_TYPE ParentBusType, IN ULONG ParentBusNumber, IN ULONG SizeofBusExtensionData, IN PINSTALL_BUS_HANDLER InstallBusHandlers, OUT PBUS_HANDLER *BusHandler)
typedef BOOLEAN(* pHalResetDisplay) (VOID)
typedef NTSTATUS(* pHalSetSystemInformation) (IN HAL_SET_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN PVOID Buffer)
typedef VOID(* pHalSetWakeAlarm) (IN ULONGLONG WakeTime, IN PTIME_FIELDS WakeTimeFields)
typedef VOID(* pHalSetWakeEnable) (IN BOOLEAN Enable)
typedef NTSTATUS(* pHalStartMirroring) (VOID)
typedef BOOLEAN(* pHalTranslateBusAddress) (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
typedef UCHAR(* pHalVectorToIDTEntry) (ULONG Vector)
typedef NTSTATUS(* PHIBERNATEBRESUMEBUS) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler)
typedef NTSTATUS(* PINSTALL_BUS_HANDLER) (IN PBUS_HANDLER Bus)
typedef VOID(* pKdCheckPowerButton) (VOID)
typedef PVOID(* pKdGetAcpiTablePhase0) (IN struct _LOADER_PARAMETER_BLOCK *LoaderBlock, IN ULONG Signature)
typedef PVOID(* pKdMapPhysicalMemory64) (IN PHYSICAL_ADDRESS PhysicalAddress, IN ULONG NumberPages)
typedef NTSTATUS(* pKdReleasePciDeviceForDebugging) (IN OUT PDEBUG_DEVICE_DESCRIPTOR PciDevice)
typedef NTSTATUS(* pKdSetupPciDeviceForDebugging) (IN PVOID LoaderBlock, OPTIONAL IN OUT PDEBUG_DEVICE_DESCRIPTOR PciDevice)
typedef VOID(* pKdUnmapVirtualAddress) (IN PVOID VirtualAddress, IN ULONG NumberPages)
typedef struct KERNEL_ERROR_HANDLER_INFO * PKERNEL_ERROR_HANDLER_INFO
typedef enum KERNEL_MCE_DELIVERY_OPERATION * PKERNEL_MCE_DELIVERY_OPERATION
typedef struct _PM_DISPATCH_TABLE PM_DISPATCH_TABLE
typedef struct _MAP_REGISTER_ENTRY * PMAP_REGISTER_ENTRY
typedef PHYSICAL_ADDRESS(* PMAP_TRANSFER) (IN PDMA_ADAPTER DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN OUT PULONG Length, IN BOOLEAN WriteToDevice)
typedef struct _MCA_DRIVER_INFO * PMCA_DRIVER_INFO
typedef struct _OEM_FONT_FILE_HEADER * POEM_FONT_FILE_HEADER
typedef struct _PARTITION_DESCRIPTOR * PPARTITION_DESCRIPTOR
typedef struct _PM_DISPATCH_TABLE * PPM_DISPATCH_TABLE
typedef VOID(* PPUT_DMA_ADAPTER) (PDMA_ADAPTER DmaAdapter)
typedef VOID(* PPUT_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PSCATTER_GATHER_LIST ScatterGather, IN BOOLEAN WriteToDevice)
typedef NTSTATUS(* PQUERY_BUS_SLOTS) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG BufferSize, OUT PULONG SlotNumbers, OUT PULONG ReturnedLength)
typedef ULONG(* PREAD_DMA_COUNTER) (IN PDMA_ADAPTER DmaAdapter)
typedef PDEVICE_HANDLER_OBJECT(* PREFERENCE_DEVICE_HANDLER) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG SlotNumber)
typedef struct _SCATTER_GATHER_ELEMENT * PSCATTER_GATHER_ELEMENT
typedef struct _SCATTER_GATHER_LIST * PSCATTER_GATHER_LIST
typedef struct _SUPPORTED_RANGE * PSUPPORTED_RANGE
typedef struct _SUPPORTED_RANGES * PSUPPORTED_RANGES
typedef BOOLEAN(* PTRANSLATEBUSADDRESS) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
typedef struct _SCATTER_GATHER_ELEMENT SCATTER_GATHER_ELEMENT
typedef struct _SCATTER_GATHER_LIST SCATTER_GATHER_LIST
typedef struct _SUPPORTED_RANGE SUPPORTED_RANGE
typedef struct _SUPPORTED_RANGES SUPPORTED_RANGES
Enumerations
enum _HAL_DISPLAY_BIOS_INFORMATION { HalDisplayInt10Bios, HalDisplayEmulatedBios, HalDisplayNoBios }
enum _HAL_QUERY_INFORMATION_CLASS {
HalInstalledBusInformation, HalProfileSourceInformation, HalInformationClassUnused1, HalPowerInformation,
HalProcessorSpeedInformation, HalCallbackInformation, HalMapRegisterInformation, HalMcaLogInformation,
HalFrameBufferCachingInformation, HalDisplayBiosInformation, HalProcessorFeatureInformation, HalNumaTopologyInterface,
HalErrorInformation, HalCmcLogInformation, HalCpeLogInformation, HalQueryMcaInterface,
HalQueryAMLIIllegalIOPortAddresses, HalQueryMaxHotPlugMemoryAddress, HalPartitionIpiInterface, HalPlatformInformation,
HalQueryProfileSourceList, HalInitLogInformation
}
enum _HAL_SET_INFORMATION_CLASS {
HalProfileSourceInterval, HalProfileSourceInterruptHandler, HalMcaRegisterDriver, HalKernelErrorHandler,
HalCmcRegisterDriver, HalCpeRegisterDriver, HalMcaLog, HalCmcLog,
HalCpeLog, HalGenerateCmcInterrupt, HalProfileSourceTimerHandler
}
enum KERNEL_MCE_DELIVERY_OPERATION {
MceNotification, McaAvailable, CmcAvailable, CpeAvailable,
CmcSwitchToPolledMode, CpeSwitchToPolledMode
}
Functions
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID HalAcquireDisplayOwnership (IN PHAL_RESET_DISPLAY_PARAMETERS ResetDisplayParameters)
NTHALAPI NTSTATUS HalAdjustResourceList (IN OUT PIO_RESOURCE_REQUIREMENTS_LIST *pResourceList)
DECLSPEC_DEPRECATED_DDK NTHALAPI NTSTATUS HalAllocateAdapterChannel (IN PADAPTER_OBJECT AdapterObject, IN PWAIT_CONTEXT_BLOCK Wcb, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine)
DECLSPEC_DEPRECATED_DDK NTHALAPI PVOID HalAllocateCommonBuffer (IN PADAPTER_OBJECT AdapterObject, IN ULONG Length, OUT PPHYSICAL_ADDRESS LogicalAddress, IN BOOLEAN CacheEnabled)
NTHALAPI PVOID HalAllocateCrashDumpRegisters (IN PADAPTER_OBJECT AdapterObject, IN OUT PULONG NumberOfMapRegisters)
NTSTATUS HalAllocateMapRegisters (IN struct _ADAPTER_OBJECT *DmaAdapter, IN ULONG NumberOfMapRegisters, IN ULONG BaseAddressCount, OUT PMAP_REGISTER_ENTRY MapRegsiterArray)
NTHALAPI BOOLEAN HalAllProcessorsStarted (VOID)
DECLSPEC_DEPRECATED_DDK NTHALAPI NTSTATUS HalAssignSlotResources (IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN INTERFACE_TYPE BusType, IN ULONG BusNumber, IN ULONG SlotNumber, IN OUT PCM_RESOURCE_LIST *AllocatedResources)
NTHALAPI VOID HalCalibratePerformanceCounter (IN LONG volatile *Number, IN ULONGLONG NewCount)
NTHALAPI VOID HalDisableSystemInterrupt (IN ULONG Vector, IN KIRQL Irql)
NTHALAPI VOID HalDisplayString (PUCHAR String)
NTHALAPI BOOLEAN HalEnableSystemInterrupt (IN ULONG Vector, IN KIRQL Irql, IN KINTERRUPT_MODE InterruptMode)
NTSTATUS HalEnumerateEnvironmentVariablesEx (IN ULONG InformationClass, OUT PVOID Buffer, IN OUT PULONG BufferLength)
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID HalFreeCommonBuffer (IN PADAPTER_OBJECT AdapterObject, IN ULONG Length, IN PHYSICAL_ADDRESS LogicalAddress, IN PVOID VirtualAddress, IN BOOLEAN CacheEnabled)
DECLSPEC_DEPRECATED_DDK NTHALAPI PADAPTER_OBJECT HalGetAdapter (IN PDEVICE_DESCRIPTION DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalGetBusData (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Length)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalGetBusDataByOffset (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
NTHALAPI ARC_STATUS HalGetEnvironmentVariable (IN PCHAR Variable, IN USHORT Length, OUT PCHAR Buffer)
NTHALAPI NTSTATUS HalGetEnvironmentVariableEx (IN PWSTR VariableName, IN LPGUID VendorGuid, OUT PVOID Value, IN OUT PULONG ValueLength, OUT PULONG Attributes OPTIONAL)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalGetInterruptVector (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN ULONG BusInterruptLevel, IN ULONG BusInterruptVector, OUT PKIRQL Irql, OUT PKAFFINITY Affinity)
DECLSPEC_DEPRECATED_DDK NTSTATUS HalGetScatterGatherList (IN PADAPTER_OBJECT DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PDRIVER_LIST_CONTROL ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice)
NTHALAPI VOID HalHandleNMI (IN OUT PVOID NmiInformation)
NTSTATUS HaliAdjustResourceListRange (IN PSUPPORTED_RANGES SupportedRanges, IN PSUPPORTED_RANGE InterruptRanges, IN OUT PIO_RESOURCE_REQUIREMENTS_LIST *pResourceList)
VOID FASTCALL HaliDereferenceBusHandler (IN PBUS_HANDLER BusHandler)
VOID FASTCALL HaliDerefernceBusHandler (IN PBUS_HANDLER BusHandler)
struct _DMA_ADAPTER * HaliGetDmaAdapter (IN PVOID Context, IN struct _DEVICE_DESCRIPTION *DeviceDescriptor, OUT PULONG NumberOfMapRegisters)
NTSTATUS HaliGetInterruptTranslator (IN INTERFACE_TYPE ParentInterfaceType, IN ULONG ParentBusNumber, IN INTERFACE_TYPE BridgeInterfaceType, IN USHORT Size, IN USHORT Version, OUT PTRANSLATOR_INTERFACE Translator, OUT PULONG BridgeBusNumber)
NTSTATUS HaliHandlePCIConfigSpaceAccess (IN BOOLEAN Read, IN ULONG Addr, IN ULONG Size, IN OUT PULONG pData)
PBUS_HANDLER FASTCALL HaliHandlerForBus (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber)
PBUS_HANDLER FASTCALL HaliHandlerForConfigSpace (IN BUS_DATA_TYPE ConfigSpace, IN ULONG BusNumber)
NTSTATUS HaliInitPnpDriver (VOID)
NTSTATUS HaliInitPowerManagement (IN PPM_DISPATCH_TABLE PmDriverDispatchTable, IN OUT PPM_DISPATCH_TABLE *PmHalDispatchTable)
VOID HaliLocateHiberRanges (IN PVOID MemoryMap)
NTHALAPI VOID HalInitializeProcessor (IN ULONG Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTHALAPI BOOLEAN HalInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
NTSTATUS HaliQueryBusSlots (IN PBUS_HANDLER BusHandler, IN ULONG BufferSize, OUT PULONG SlotNumbers, OUT PULONG ReturnedLength)
NTSTATUS HaliQuerySystemInformation (IN HAL_SET_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN OUT PVOID Buffer, OUT PULONG ReturnedLength)
VOID FASTCALL HaliReferenceBusHandler (IN PBUS_HANDLER BusHandler)
PBUS_HANDLER FASTCALL HaliReferenceHandlerForBus (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber)
NTSTATUS HaliRegisterBusHandler (IN INTERFACE_TYPE InterfaceType, IN BUS_DATA_TYPE AssociatedConfigurationSpace, IN ULONG BusNumber, IN INTERFACE_TYPE ParentBusType, IN ULONG ParentBusNumber, IN ULONG SizeofBusExtensionData, IN PINSTALL_BUS_HANDLER InstallBusHandlers, OUT PBUS_HANDLER *BusHandler)
NTSTATUS HaliSetSystemInformation (IN HAL_SET_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN PVOID Buffer)
DECLSPEC_DEPRECATED_DDK NTHALAPI BOOLEAN HalMakeBeep (IN ULONG Frequency)
VOID HalpInitBusHandler (VOID)
NTHALAPI VOID HalProcessorIdle (VOID)
DECLSPEC_DEPRECATED_DDK VOID HalPutDmaAdapter (IN PADAPTER_OBJECT DmaAdapter)
DECLSPEC_DEPRECATED_DDK VOID HalPutScatterGatherList (IN PADAPTER_OBJECT DmaAdapter, IN PSCATTER_GATHER_LIST ScatterGather, IN BOOLEAN WriteToDevice)
NTHALAPI VOID HalQueryDisplayParameters (OUT PULONG WidthInCharacters, OUT PULONG HeightInLines, OUT PULONG CursorColumn, OUT PULONG CursorRow)
NTHALAPI BOOLEAN HalQueryRealTimeClock (OUT PTIME_FIELDS TimeFields)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalReadDmaCounter (IN PADAPTER_OBJECT AdapterObject)
NTHALAPI VOID HalReportResourceUsage (VOID)
NTHALAPI VOID HalRequestIpi (IN KAFFINITY Mask)
NTHALAPI VOID FASTCALL HalRequestSoftwareInterrupt (KIRQL RequestIrql)
NTHALAPI VOID HalReturnToFirmware (IN FIRMWARE_REENTRY Routine)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalSetBusData (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Length)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalSetBusDataByOffset (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
NTHALAPI VOID HalSetDisplayParameters (IN ULONG CursorColumn, IN ULONG CursorRow)
NTHALAPI ARC_STATUS HalSetEnvironmentVariable (IN PCHAR Variable, IN PCHAR Value)
NTSTATUS HalSetEnvironmentVariableEx (IN PWSTR VariableName, IN LPGUID VendorGuid, IN PVOID Value, IN ULONG ValueLength, IN ULONG Attributes)
NTHALAPI ULONG_PTR HalSetProfileInterval (IN ULONG_PTR Interval)
NTHALAPI BOOLEAN HalSetRealTimeClock (IN PTIME_FIELDS TimeFields)
NTHALAPI ULONG HalSetTimeIncrement (IN ULONG DesiredIncrement)
NTHALAPI BOOLEAN HalStartNextProcessor (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PKPROCESSOR_STATE ProcessorState)
NTHALAPI VOID HalStartProfileInterrupt (KPROFILE_SOURCE ProfileSource)
NTHALAPI VOID HalStopProfileInterrupt (KPROFILE_SOURCE ProfileSource)
ULONG FASTCALL HalSystemVectorDispatchEntry (IN ULONG Vector, OUT PKINTERRUPT_ROUTINE **FlatDispatch, OUT PKINTERRUPT_ROUTINE *NoConnection)
DECLSPEC_DEPRECATED_DDK NTHALAPI BOOLEAN HalTranslateBusAddress (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
DECLSPEC_DEPRECATED_DDK NTHALAPI BOOLEAN IoFlushAdapterBuffers (IN PADAPTER_OBJECT AdapterObject, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN ULONG Length, IN BOOLEAN WriteToDevice)
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID IoFreeAdapterChannel (IN PADAPTER_OBJECT AdapterObject)
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID IoFreeMapRegisters (IN PADAPTER_OBJECT AdapterObject, IN PVOID MapRegisterBase, IN ULONG NumberOfMapRegisters)
DECLSPEC_DEPRECATED_DDK NTHALAPI PHYSICAL_ADDRESS IoMapTransfer (IN PADAPTER_OBJECT AdapterObject, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN OUT PULONG Length, IN BOOLEAN WriteToDevice)
NTHALAPI ULONG KdPortGetByte (OUT PUCHAR Input)
NTHALAPI BOOLEAN KdPortInitialize (PDEBUG_PARAMETERS DebugParameters, PLOADER_PARAMETER_BLOCK LoaderBlock, BOOLEAN Initialize)
NTHALAPI ULONG KdPortPollByte (OUT PUCHAR Input)
NTHALAPI VOID KdPortPutByte (IN UCHAR Output)
NTHALAPI VOID KdPortRestore (VOID)
NTHALAPI VOID KdPortSave (VOID)
NTHALAPI VOID KeFlushWriteBuffer (VOID)
NTHALAPI LARGE_INTEGER KeQueryPerformanceCounter (OUT PLARGE_INTEGER PerformanceFrequency OPTIONAL)
NTHALAPI VOID KeStallExecutionProcessor (IN ULONG MicroSeconds)
typedef PBUS_HANDLER (FASTCALL *pHalHandlerForBus)(IN INTERFACE_TYPE InterfaceType
typedef VOID (FASTCALL *pHalRefernceBusHandler)(IN PBUS_HANDLER BusHandler)
Variables
HAL_DISPATCH HalDispatchTable
HAL_PRIVATE_DISPATCH HalPrivateDispatchTable
Macro Definition Documentation
#define BOOT_RECORD_SIGNATURE (0xaa55)
Definition at line 161 of file hal.h.
Referenced by HalExamineMBR(), IoReadPartitionTable(), IoSetPartitionInformation(), and IoWritePartitionTable().
#define BOOT_SIGNATURE_OFFSET ((0x200 / 2) - 1)
Definition at line 155 of file hal.h.
Referenced by HalExamineMBR(), IoReadPartitionTable(), IoSetPartitionInformation(), and IoWritePartitionTable().
#define BUS_HANDLER_VERSION 1
Definition at line 922 of file hal.h.
#define BUS_SUPPORTED_RANGE_VERSION 1
Definition at line 890 of file hal.h.
#define CmcKernelToken KernelReserved[1]
Definition at line 1987 of file hal.h.
#define CpeKernelToken KernelReserved[2]
Definition at line 1988 of file hal.h.
#define DEVICE_DESCRIPTION_VERSION 0
Definition at line 115 of file hal.h.
#define DEVICE_DESCRIPTION_VERSION1 1
Definition at line 116 of file hal.h.
#define DEVICE_DESCRIPTION_VERSION2 2
Definition at line 117 of file hal.h.
#define HAL_CMC_DISABLED HAL_MCE_DISABLED
Definition at line 1967 of file hal.h.
Referenced by WmipRegisterMcaHandler().
#define HAL_CMC_INTERRUPTS_BASED HAL_MCE_INTERRUPTS_BASED
Definition at line 1966 of file hal.h.
Referenced by WmipRegisterMcaHandler().
#define HAL_CPE_DISABLED HAL_MCE_DISABLED
Definition at line 1974 of file hal.h.
Referenced by WmipRegisterMcaHandler().
#define HAL_CPE_INTERRUPTS_BASED HAL_MCE_INTERRUPTS_BASED
Definition at line 1973 of file hal.h.
Referenced by WmipRegisterMcaHandler().
#define HAL_DISPATCH_VERSION 3
Definition at line 1592 of file hal.h.
#define HAL_ERROR_INFO_VERSION 0x2
Definition at line 1924 of file hal.h.
Referenced by WmipRegisterMcaHandler().
#define HAL_MCA_DISABLED HAL_MCE_DISABLED
Definition at line 1977 of file hal.h.
#define HAL_MCA_INTERRUPTS_BASED HAL_MCE_INTERRUPTS_BASED
Definition at line 1976 of file hal.h.
#define HAL_MCE_DISABLED ((ULONG)0)
Definition at line 1960 of file hal.h.
Referenced by WmipMceWorkerRoutine().
#define HAL_MCE_INTERRUPTS_BASED ((ULONG)-1)
Definition at line 1959 of file hal.h.
Referenced by WmipMceDelivery(), WmipMceEventDelivery(), and WmipPollingDpcRoutine().
#define HAL_PLATFORM_ACPI_TABLES_CACHED 0x20L
Definition at line 2046 of file hal.h.
#define HAL_PLATFORM_DISABLE_PTCG 0x04L
Definition at line 2043 of file hal.h.
#define HAL_PLATFORM_DISABLE_UC_MAIN_MEMORY 0x08L
Definition at line 2044 of file hal.h.
Referenced by MiInitializeCacheOverrides().
#define HAL_PLATFORM_DISABLE_WRITE_COMBINING 0x01L
Definition at line 2042 of file hal.h.
Referenced by MiInitializeCacheOverrides().
#define HAL_PLATFORM_ENABLE_WRITE_COMBINING_MMIO 0x10L
Definition at line 2045 of file hal.h.
Referenced by MiInitializeCacheOverrides().
#define HAL_PRIVATE_DISPATCH_VERSION 2
Definition at line 1666 of file hal.h.
#define HalAllocateMapRegisters HALPDISPATCH->HalAllocateMapRegisters
Definition at line 1676 of file hal.h.
#define HalDereferenceBusHandler HALDISPATCH->HalDereferenceBusHandler
Definition at line 1601 of file hal.h.
#define HALDISPATCH (&HalDispatchTable)
Definition at line 1588 of file hal.h.
#define HalDispatchTableVersion HALDISPATCH->Version
Definition at line 1594 of file hal.h.
#define HalEndMirroring HALDISPATCH->HalEndMirroring
Definition at line 1610 of file hal.h.
#define HalEndOfBoot HALDISPATCH->HalEndOfBoot
Definition at line 1612 of file hal.h.
Referenced by NtInitializeRegistry().
#define HalGetDmaAdapter HALDISPATCH->HalGetDmaAdapter
Definition at line 1606 of file hal.h.
#define HalGetDmaAlignmentRequirement () 1L
Definition at line 303 of file hal.h.
Referenced by IoCreateDevice().
#define HalGetInterruptTranslator HALDISPATCH->HalGetInterruptTranslator
Definition at line 1607 of file hal.h.
#define HalHaltSystem HALPDISPATCH->HalHaltSystem
Definition at line 1674 of file hal.h.
Referenced by KiBugCheckDebugBreak().
#define HalHandlerForBus HALPDISPATCH->HalHandlerForBus
Definition at line 1669 of file hal.h.
#define HalHandlerForConfigSpace HALPDISPATCH->HalHandlerForConfigSpace
Definition at line 1670 of file hal.h.
#define HalInitPnpDriver HALDISPATCH->HalInitPnpDriver
Definition at line 1603 of file hal.h.
Referenced by IoInitSystem().
#define HalInitPowerManagement HALDISPATCH->HalInitPowerManagement
Definition at line 1604 of file hal.h.
#define HalLocateHiberRanges HALPDISPATCH->HalLocateHiberRanges
Definition at line 1671 of file hal.h.
#define HalMirrorPhysicalMemory HALDISPATCH->HalMirrorPhysicalMemory
Definition at line 1611 of file hal.h.
#define HalMirrorVerify HALDISPATCH->HalMirrorVerify
Definition at line 1613 of file hal.h.
#define HALPDISPATCH (&HalPrivateDispatchTable)
Definition at line 1662 of file hal.h.
#define HalQueryBusSlots HALDISPATCH->HalQueryBusSlots
Definition at line 1597 of file hal.h.
#define HalQuerySystemInformation HALDISPATCH->HalQuerySystemInformation
Definition at line 1595 of file hal.h.
Referenced by KeNumaInitialize(), KeQueryIntervalProfile(), KiInitMachineDependent(), MiInitializeCacheOverrides(), MiInitMachineDependent(), WmipGetLogFromHal(), and WmipRegisterMcaHandler().
#define HalReferenceBusHandler HALDISPATCH->HalReferenceBusHandler
Definition at line 1600 of file hal.h.
#define HalReferenceHandlerForBus HALDISPATCH->HalReferenceHandlerForBus
Definition at line 1599 of file hal.h.
#define HalRegisterBusHandler HALPDISPATCH->HalRegisterBusHandler
Definition at line 1668 of file hal.h.
#define HalResetDisplay HALPDISPATCH->HalResetDisplay
Definition at line 1675 of file hal.h.
#define HalSetSystemInformation HALDISPATCH->HalSetSystemInformation
Definition at line 1596 of file hal.h.
Referenced by KeSetIntervalProfile(), and WmipRegisterMcaHandler().
#define HalSetWakeAlarm HALPDISPATCH->HalSetWakeAlarm
Definition at line 1673 of file hal.h.
#define HalSetWakeEnable HALPDISPATCH->HalSetWakeEnable
Definition at line 1672 of file hal.h.
#define HalStartMirroring HALDISPATCH->HalStartMirroring
Definition at line 1609 of file hal.h.
#define HalVectorToIDTEntry HALPDISPATCH->HalVectorToIDTEntry
Definition at line 1681 of file hal.h.
Referenced by KeConnectInterrupt(), KeDisconnectInterrupt(), and KiGetVectorInfo().
#define KdCheckPowerButton HALPDISPATCH->KdCheckPowerButton
Definition at line 1680 of file hal.h.
#define KdGetAcpiTablePhase0 HALPDISPATCH->KdGetAcpiTablePhase0
Definition at line 1679 of file hal.h.
#define KdMapPhysicalMemory64 HALPDISPATCH->KdMapPhysicalMemory64
Definition at line 1682 of file hal.h.
#define KdReleasePciDeviceForDebugging HALPDISPATCH->KdReleasePciDeviceForDebugging
Definition at line 1678 of file hal.h.
#define KdSetupPciDeviceForDebugging HALPDISPATCH->KdSetupPciDeviceForDebugging
Definition at line 1677 of file hal.h.
#define KdUnmapVirtualAddress HALPDISPATCH->KdUnmapVirtualAddress
Definition at line 1683 of file hal.h.
#define KERNEL_ERROR_HANDLER_VERSION 0x2
Definition at line 1888 of file hal.h.
Referenced by WmipRegisterMcaHandler().
#define KERNEL_MCA_CORRECTED 0x2
Definition at line 1904 of file hal.h.
#define KERNEL_MCA_PREVIOUS 0x1
Definition at line 1903 of file hal.h.
#define KERNEL_MCA_UNKNOWN 0x0
Definition at line 1902 of file hal.h.
#define KERNEL_MCE_EVENTTYPE (_Reserved) ((USHORT)(ULONG_PTR)(_Reserved))
Definition at line 1912 of file hal.h.
Referenced by WmipMceEventDelivery().
#define KERNEL_MCE_EVENTTYPE_CMC 0x02
Definition at line 1909 of file hal.h.
Referenced by WmipMceEventDelivery().
#define KERNEL_MCE_EVENTTYPE_CPE 0x03
Definition at line 1910 of file hal.h.
Referenced by WmipMceEventDelivery().
#define KERNEL_MCE_EVENTTYPE_INIT 0x01
Definition at line 1908 of file hal.h.
#define KERNEL_MCE_EVENTTYPE_MASK 0xffff
Definition at line 1911 of file hal.h.
#define KERNEL_MCE_EVENTTYPE_MCA 0x00
Definition at line 1907 of file hal.h.
#define KERNEL_MCE_OPERATION (_Reserved) ((USHORT)((((ULONG_PTR)(_Reserved)) >> KERNEL_MCE_OPERATION_SHIFT) & KERNEL_MCE_OPERATION_MASK))
Definition at line 1920 of file hal.h.
Referenced by WmipMceEventDelivery().
#define KERNEL_MCE_OPERATION_CLEAR_STATE_INFO 0x1
Definition at line 1915 of file hal.h.
#define KERNEL_MCE_OPERATION_GET_STATE_INFO 0x2
Definition at line 1916 of file hal.h.
Referenced by WmipMceEventDelivery().
#define KERNEL_MCE_OPERATION_MASK 0xffff
Definition at line 1917 of file hal.h.
#define KERNEL_MCE_OPERATION_SHIFT 16
Definition at line 1918 of file hal.h.
#define McaKernelToken KernelReserved[0]
Definition at line 1986 of file hal.h.
#define NUM_PARTITION_TABLE_ENTRIES 4
Definition at line 148 of file hal.h.
Referenced by IoReadPartitionTable(), IoSetPartitionInformation(), and IoWritePartitionTable().
#define OEM_FONT_CHARACTER_SET 255
Definition at line 36 of file hal.h.
#define OEM_FONT_FAMILY (3 << 4)
Definition at line 37 of file hal.h.
#define OEM_FONT_ITALIC 0
Definition at line 33 of file hal.h.
#define OEM_FONT_STRIKEOUT 0
Definition at line 35 of file hal.h.
#define OEM_FONT_TYPE 0
Definition at line 32 of file hal.h.
#define OEM_FONT_UNDERLINE 0
Definition at line 34 of file hal.h.
#define OEM_FONT_VERSION 0x200
Definition at line 31 of file hal.h.
#define PARTITION_ACTIVE_FLAG 0x80
Definition at line 173 of file hal.h.
Referenced by IoReadPartitionTable(), and IoWritePartitionTable().
#define PARTITION_BUFFER_SIZE 2048
Definition at line 167 of file hal.h.
Referenced by IoReadPartitionTable().
#define PARTITION_TABLE_OFFSET (0x1be / 2)
Definition at line 154 of file hal.h.
Referenced by HalExamineMBR(), IoReadPartitionTable(), IoSetPartitionInformation(), and IoWritePartitionTable().
Typedef Documentation
typedef struct _BUS_HANDLER BUS_HANDLER
typedef IN ULONG BusNumber
Definition at line 1042 of file hal.h.
typedef struct _CMC_DRIVER_INFO CMC_DRIVER_INFO
typedef struct _CPE_DRIVER_INFO CPE_DRIVER_INFO
typedef struct _DEVICE_CONTROL_CONTEXT DEVICE_CONTROL_CONTEXT
typedef struct _DEVICE_DESCRIPTION DEVICE_DESCRIPTION
typedef struct _DMA_ADAPTER DMA_ADAPTER
typedef struct _DMA_OPERATIONS DMA_OPERATIONS
typedef struct _HAL_AMLI_BAD_IO_ADDRESS_LIST HAL_AMLI_BAD_IO_ADDRESS_LIST
typedef struct _HAL_BUS_INFORMATION HAL_BUS_INFORMATION
typedef struct _HAL_CALLBACKS HAL_CALLBACKS
typedef struct _HAL_DEVICE_CONTROL HAL_DEVICE_CONTROL_CONTEXT
typedef enum _HAL_DISPLAY_BIOS_INFORMATION HAL_DISPLAY_BIOS_INFORMATION
typedef struct _HAL_ERROR_INFO HAL_ERROR_INFO
typedef struct _HAL_MCA_INTERFACE HAL_MCA_INTERFACE
typedef struct _HAL_NUMA_TOPOLOGY_INTERFACE HAL_NUMA_TOPOLOGY_INTERFACE
typedef struct _HAL_PLATFORM_INFORMATION HAL_PLATFORM_INFORMATION
typedef struct _HAL_POWER_INFORMATION HAL_POWER_INFORMATION
typedef struct _HAL_PROCESSOR_FEATURE HAL_PROCESSOR_FEATURE
typedef struct _HAL_PROCESSOR_SPEED_INFO HAL_PROCESSOR_SPEED_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION HAL_PROFILE_SOURCE_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION_EX HAL_PROFILE_SOURCE_INFORMATION_EX
typedef struct _HAL_PROFILE_SOURCE_INTERVAL HAL_PROFILE_SOURCE_INTERVAL
typedef struct _HAL_PROFILE_SOURCE_LIST HAL_PROFILE_SOURCE_LIST
typedef enum _HAL_QUERY_INFORMATION_CLASS HAL_QUERY_INFORMATION_CLASS
typedef enum _HAL_SET_INFORMATION_CLASS HAL_SET_INFORMATION_CLASS
typedef ULONG HALNUMAPAGETONODE
Definition at line 1758 of file hal.h.
typedef BOOLEAN(* KERNEL_CMC_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
Definition at line 1884 of file hal.h.
typedef BOOLEAN(* KERNEL_CPE_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
Definition at line 1885 of file hal.h.
typedef BOOLEAN(* KERNEL_MCA_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
Definition at line 1883 of file hal.h.
typedef BOOLEAN(* KERNEL_MCE_DELIVERY) (PVOID Reserved, KERNEL_MCE_DELIVERY_OPERATION Operation, PVOID Argument2)
Definition at line 1886 of file hal.h.
typedef struct _MAP_REGISTER_ENTRY MAP_REGISTER_ENTRY
typedef struct _MCA_DRIVER_INFO MCA_DRIVER_INFO
typedef struct _OEM_FONT_FILE_HEADER OEM_FONT_FILE_HEADER
typedef NTSTATUS(* PADJUSTRESOURCELIST) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN OUT PIO_RESOURCE_REQUIREMENTS_LIST *pResourceList)
Definition at line 820 of file hal.h.
typedef NTSTATUS(* PALLOCATE_ADAPTER_CHANNEL) (IN PDMA_ADAPTER DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine, IN PVOID Context)
Definition at line 2101 of file hal.h.
typedef PVOID(* PALLOCATE_COMMON_BUFFER) (IN PDMA_ADAPTER DmaAdapter, IN ULONG Length, OUT PPHYSICAL_ADDRESS LogicalAddress, IN BOOLEAN CacheEnabled)
Definition at line 2086 of file hal.h.
typedef struct _PARTITION_DESCRIPTOR PARTITION_DESCRIPTOR
typedef NTSTATUS(* PASSIGNSLOTRESOURCES) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject OPTIONAL, IN ULONG SlotNumber, IN OUT PCM_RESOURCE_LIST *AllocatedResources)
Definition at line 839 of file hal.h.
typedef NTSTATUS(* PBUILD_MDL_FROM_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PSCATTER_GATHER_LIST ScatterGather, IN PMDL OriginalMdl, OUT PMDL *TargetMdl)
Definition at line 2197 of file hal.h.
typedef NTSTATUS(* PBUILD_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PDRIVER_LIST_CONTROL ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice, IN PVOID ScatterGatherBuffer, IN ULONG ScatterGatherLength)
Definition at line 2183 of file hal.h.
typedef PBUS_HANDLER
typedef NTSTATUS(* PCALCULATE_SCATTER_GATHER_LIST_SIZE) (IN PDMA_ADAPTER DmaAdapter, IN OPTIONAL PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, OUT PULONG ScatterGatherListSize, OUT OPTIONAL PULONG pNumberOfMapRegisters)
Definition at line 2173 of file hal.h.
typedef struct _CMC_DRIVER_INFO * PCMC_DRIVER_INFO
typedef struct _CPE_DRIVER_INFO * PCPE_DRIVER_INFO
typedef struct DEBUG_DEVICE_ADDRESS * PDEBUG_DEVICE_ADDRESS
typedef struct DEBUG_DEVICE_DESCRIPTOR * PDEBUG_DEVICE_DESCRIPTOR
typedef struct DEBUG_MEMORY_REQUIREMENTS * PDEBUG_MEMORY_REQUIREMENTS
typedef NTSTATUS(* PDEVICE_CONTROL) (IN PHAL_DEVICE_CONTROL_CONTEXT Context)
Definition at line 874 of file hal.h.
typedef VOID(* PDEVICE_CONTROL_COMPLETION) (IN struct _DEVICE_CONTROL_CONTEXT *ControlContext)
Definition at line 740 of file hal.h.
typedef struct _DEVICE_CONTROL_CONTEXT * PDEVICE_CONTROL_CONTEXT
typedef struct _DEVICE_DESCRIPTION * PDEVICE_DESCRIPTION
typedef struct _DMA_ADAPTER * PDMA_ADAPTER
typedef struct _DMA_OPERATIONS* PDMA_OPERATIONS
Definition at line 2073 of file hal.h.
typedef VOID(* PDRIVER_CMC_EXCEPTION_CALLBACK) (IN PVOID Context, IN PCMC_EXCEPTION CmcLog)
Definition at line 1998 of file hal.h.
typedef VOID(* PDRIVER_CPE_EXCEPTION_CALLBACK) (IN PVOID Context, IN PCPE_EXCEPTION CmcLog)
Definition at line 2009 of file hal.h.
typedef VOID(* PDRIVER_EXCPTN_CALLBACK) (IN PVOID Context, IN PMCA_EXCEPTION BankLog)
Definition at line 1851 of file hal.h.
typedef VOID(* PDRIVER_LIST_CONTROL) (IN struct _DEVICE_OBJECT *DeviceObject, IN struct _IRP *Irp, IN PSCATTER_GATHER_LIST ScatterGather, IN PVOID Context)
Definition at line 2146 of file hal.h.
typedef PDRIVER_EXCPTN_CALLBACK PDRIVER_MCA_EXCEPTION_CALLBACK
Definition at line 1858 of file hal.h.
typedef BOOLEAN(* PFLUSH_ADAPTER_BUFFERS) (IN PDMA_ADAPTER DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN ULONG Length, IN BOOLEAN WriteToDevice)
Definition at line 2109 of file hal.h.
typedef VOID(* PFREE_ADAPTER_CHANNEL) (IN PDMA_ADAPTER DmaAdapter)
Definition at line 2118 of file hal.h.
typedef VOID(* PFREE_COMMON_BUFFER) (IN PDMA_ADAPTER DmaAdapter, IN ULONG Length, IN PHYSICAL_ADDRESS LogicalAddress, IN PVOID VirtualAddress, IN BOOLEAN CacheEnabled)
Definition at line 2093 of file hal.h.
typedef VOID(* PFREE_MAP_REGISTERS) (IN PDMA_ADAPTER DmaAdapter, PVOID MapRegisterBase, ULONG NumberOfMapRegisters)
Definition at line 2122 of file hal.h.
typedef ULONG(* PGET_DMA_ALIGNMENT) (IN PDMA_ADAPTER DmaAdapter)
Definition at line 2137 of file hal.h.
typedef NTSTATUS(* PGET_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PDRIVER_LIST_CONTROL ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice)
Definition at line 2154 of file hal.h.
typedef ULONG(* PGET_SET_DEVICE_INSTANCE_DATA) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN PDEVICE_HANDLER_OBJECT DeviceHandler, IN ULONG DataType, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
Definition at line 861 of file hal.h.
typedef ULONG(* PGETINTERRUPTVECTOR) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG BusInterruptLevel, IN ULONG BusInterruptVector, OUT PKIRQL Irql, OUT PKAFFINITY Affinity)
Definition at line 800 of file hal.h.
typedef ULONG(* PGETSETBUSDATA) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
Definition at line 789 of file hal.h.
typedef struct _HAL_AMLI_BAD_IO_ADDRESS_LIST * PHAL_AMLI_BAD_IO_ADDRESS_LIST
typedef struct _HAL_BUS_INFORMATION * PHAL_BUS_INFORMATION
typedef struct _HAL_CALLBACKS * PHAL_CALLBACKS
typedef struct _HAL_DEVICE_CONTROL * PHAL_DEVICE_CONTROL_CONTEXT
typedef struct HAL_DISPATCH * PHAL_DISPATCH
typedef enum _HAL_DISPLAY_BIOS_INFORMATION * PHAL_DISPLAY_BIOS_INFORMATION
typedef struct _HAL_ERROR_INFO * PHAL_ERROR_INFO
typedef struct _HAL_PLATFORM_INFORMATION * PHAL_PLATFORM_INFORMATION
typedef struct _HAL_POWER_INFORMATION * PHAL_POWER_INFORMATION
typedef struct HAL_PRIVATE_DISPATCH * PHAL_PRIVATE_DISPATCH
typedef struct _HAL_PROCESSOR_SPEED_INFO * PHAL_PROCESSOR_SPEED_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION * PHAL_PROFILE_SOURCE_INFORMATION
typedef struct _HAL_PROFILE_SOURCE_INFORMATION_EX * PHAL_PROFILE_SOURCE_INFORMATION_EX
typedef struct _HAL_PROFILE_SOURCE_INTERVAL * PHAL_PROFILE_SOURCE_INTERVAL
typedef struct _HAL_PROFILE_SOURCE_LIST * PHAL_PROFILE_SOURCE_LIST
typedef enum _HAL_QUERY_INFORMATION_CLASS * PHAL_QUERY_INFORMATION_CLASS
typedef BOOLEAN(* PHAL_RESET_DISPLAY_PARAMETERS) (IN ULONG Columns, IN ULONG Rows)
Definition at line 187 of file hal.h.
typedef enum _HAL_SET_INFORMATION_CLASS * PHAL_SET_INFORMATION_CLASS
typedef NTSTATUS(* pHalAllocateMapRegisters) (IN struct _ADAPTER_OBJECT *DmaAdapter, IN ULONG NumberOfMapRegisters, IN ULONG BaseAddressCount, OUT PMAP_REGISTER_ENTRY MapRegsiterArray)
Definition at line 1415 of file hal.h.
typedef NTSTATUS(* pHalAssignSlotResources) (IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN INTERFACE_TYPE BusType, IN ULONG BusNumber, IN ULONG SlotNumber, IN OUT PCM_RESOURCE_LIST *AllocatedResources)
Definition at line 1382 of file hal.h.
typedef NTSTATUS(* pHalEndMirroring) (IN ULONG PassNumber)
Definition at line 1455 of file hal.h.
typedef VOID(* pHalEndOfBoot) (VOID)
Definition at line 1531 of file hal.h.
typedef VOID(FASTCALL * pHalExamineMBR) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG MBRTypeIdentifier, OUT PVOID *Buffer)
Definition at line 1241 of file hal.h.
typedef BOOLEAN(* pHalFindBusAddressTranslation) (IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress, IN OUT PULONG_PTR Context, IN BOOLEAN NextBus)
Definition at line 1439 of file hal.h.
typedef struct _DMA_ADAPTER*(* pHalGetDmaAdapter) (IN PVOID Context, IN struct _DEVICE_DESCRIPTION *DeviceDescriptor, OUT PULONG NumberOfMapRegisters)
Definition at line 1330 of file hal.h.
typedef NTSTATUS(* pHalGetInterruptTranslator) (IN INTERFACE_TYPE ParentInterfaceType, IN ULONG ParentBusNumber, IN INTERFACE_TYPE BridgeInterfaceType, IN USHORT Size, IN USHORT Version, OUT PTRANSLATOR_INTERFACE Translator, OUT PULONG BridgeBusNumber)
Definition at line 1347 of file hal.h.
typedef VOID(* pHalHaltSystem) (VOID)
Definition at line 1395 of file hal.h.
typedef NTSTATUS(* pHalInitPnpDriver) (VOID)
Definition at line 1296 of file hal.h.
typedef NTSTATUS(* pHalInitPowerManagement) (IN PPM_DISPATCH_TABLE PmDriverDispatchTable, OUT PPM_DISPATCH_TABLE *PmHalDispatchTable)
Definition at line 1315 of file hal.h.
typedef VOID(FASTCALL * pHalIoAssignDriveLetters) (IN struct _LOADER_PARAMETER_BLOCK *LoaderBlock, IN PSTRING NtDeviceName, OUT PUCHAR NtSystemPath, OUT PSTRING NtSystemPathString)
Definition at line 1250 of file hal.h.
typedef NTSTATUS(FASTCALL * pHalIoReadPartitionTable) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN BOOLEAN ReturnRecognizedPartitions, OUT struct _DRIVE_LAYOUT_INFORMATION **PartitionBuffer)
Definition at line 1259 of file hal.h.
typedef NTSTATUS(* PHALIOREADWRITEHANDLER) (IN BOOLEAN fRead, IN ULONG dwAddr, IN ULONG dwSize, IN OUT PULONG pdwData)
Definition at line 1782 of file hal.h.
typedef NTSTATUS(FASTCALL * pHalIoSetPartitionInformation) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG PartitionNumber, IN ULONG PartitionType)
Definition at line 1268 of file hal.h.
typedef NTSTATUS(FASTCALL * pHalIoWritePartitionTable) (IN PDEVICE_OBJECT DeviceObject, IN ULONG SectorSize, IN ULONG SectorsPerTrack, IN ULONG NumberOfHeads, IN struct _DRIVE_LAYOUT_INFORMATION *PartitionBuffer)
Definition at line 1277 of file hal.h.
typedef VOID(* pHalLocateHiberRanges) (IN PVOID MemoryMap)
Definition at line 1143 of file hal.h.
typedef VOID(* PHALMCAINTERFACELOCK) (VOID)
Definition at line 1808 of file hal.h.
typedef NTSTATUS(* PHALMCAINTERFACEREADREGISTER) (IN UCHAR BankNumber, IN OUT PVOID Exception)
Definition at line 1820 of file hal.h.
typedef VOID(* PHALMCAINTERFACEUNLOCK) (VOID)
Definition at line 1814 of file hal.h.
typedef NTSTATUS(* pHalMirrorPhysicalMemory) (IN PHYSICAL_ADDRESS PhysicalAddress, IN LARGE_INTEGER NumberOfBytes)
Definition at line 1461 of file hal.h.
typedef NTSTATUS(* pHalMirrorVerify) (IN PHYSICAL_ADDRESS PhysicalAddress, IN LARGE_INTEGER NumberOfBytes)
Definition at line 1468 of file hal.h.
typedef HALNUMAPAGETONODE(* PHALNUMAPAGETONODE) (IN ULONG_PTR PhysicalPageNumber)
Definition at line 1762 of file hal.h.
typedef NTSTATUS(* PHALNUMAQUERYPROCESSORNODE) (IN ULONG ProcessorNumber, OUT PUSHORT Identifier, OUT PUCHAR Node)
Definition at line 1768 of file hal.h.
typedef NTSTATUS(* pHalQueryBusSlots) (IN PBUS_HANDLER BusHandler, IN ULONG BufferSize, OUT PULONG SlotNumbers, OUT PULONG ReturnedLength)
Definition at line 1287 of file hal.h.
typedef NTSTATUS(* pHalQuerySystemInformation) (IN HAL_QUERY_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN OUT PVOID Buffer, OUT PULONG ReturnedLength)
Definition at line 1198 of file hal.h.
typedef NTSTATUS(* pHalRegisterBusHandler) (IN INTERFACE_TYPE InterfaceType, IN BUS_DATA_TYPE AssociatedConfigurationSpace, IN ULONG BusNumber, IN INTERFACE_TYPE ParentBusType, IN ULONG ParentBusNumber, IN ULONG SizeofBusExtensionData, IN PINSTALL_BUS_HANDLER InstallBusHandlers, OUT PBUS_HANDLER *BusHandler)
Definition at line 1012 of file hal.h.
typedef BOOLEAN(* pHalResetDisplay) (VOID)
Definition at line 1401 of file hal.h.
typedef NTSTATUS(* pHalSetSystemInformation) (IN HAL_SET_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN PVOID Buffer)
Definition at line 1224 of file hal.h.
typedef VOID(* pHalSetWakeAlarm) (IN ULONGLONG WakeTime, IN PTIME_FIELDS WakeTimeFields)
Definition at line 1136 of file hal.h.
typedef VOID(* pHalSetWakeEnable) (IN BOOLEAN Enable)
Definition at line 1130 of file hal.h.
typedef NTSTATUS(* pHalStartMirroring) (VOID)
Definition at line 1449 of file hal.h.
typedef BOOLEAN(* pHalTranslateBusAddress) (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
Definition at line 1372 of file hal.h.
typedef UCHAR(* pHalVectorToIDTEntry) (ULONG Vector)
Definition at line 1433 of file hal.h.
typedef NTSTATUS(* PHIBERNATEBRESUMEBUS) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler)
Definition at line 881 of file hal.h.
typedef NTSTATUS(* PINSTALL_BUS_HANDLER) (IN PBUS_HANDLER Bus)
Definition at line 1006 of file hal.h.
typedef VOID(* pKdCheckPowerButton) (VOID)
Definition at line 1525 of file hal.h.
typedef PVOID(* pKdGetAcpiTablePhase0) (IN struct _LOADER_PARAMETER_BLOCK *LoaderBlock, IN ULONG Signature)
Definition at line 1518 of file hal.h.
typedef PVOID(* pKdMapPhysicalMemory64) (IN PHYSICAL_ADDRESS PhysicalAddress, IN ULONG NumberPages)
Definition at line 1537 of file hal.h.
typedef NTSTATUS(* pKdReleasePciDeviceForDebugging) (IN OUT PDEBUG_DEVICE_DESCRIPTOR PciDevice)
Definition at line 1512 of file hal.h.
typedef NTSTATUS(* pKdSetupPciDeviceForDebugging) (IN PVOID LoaderBlock, OPTIONAL IN OUT PDEBUG_DEVICE_DESCRIPTOR PciDevice)
Definition at line 1505 of file hal.h.
typedef VOID(* pKdUnmapVirtualAddress) (IN PVOID VirtualAddress, IN ULONG NumberPages)
Definition at line 1544 of file hal.h.
typedef struct KERNEL_ERROR_HANDLER_INFO * PKERNEL_ERROR_HANDLER_INFO
typedef enum KERNEL_MCE_DELIVERY_OPERATION * PKERNEL_MCE_DELIVERY_OPERATION
typedef struct _PM_DISPATCH_TABLE PM_DISPATCH_TABLE
typedef struct _MAP_REGISTER_ENTRY * PMAP_REGISTER_ENTRY
typedef PHYSICAL_ADDRESS(* PMAP_TRANSFER) (IN PDMA_ADAPTER DmaAdapter, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN OUT PULONG Length, IN BOOLEAN WriteToDevice)
Definition at line 2128 of file hal.h.
typedef struct _MCA_DRIVER_INFO * PMCA_DRIVER_INFO
typedef struct _OEM_FONT_FILE_HEADER * POEM_FONT_FILE_HEADER
typedef struct _PARTITION_DESCRIPTOR * PPARTITION_DESCRIPTOR
typedef struct _PM_DISPATCH_TABLE * PPM_DISPATCH_TABLE
typedef VOID(* PPUT_DMA_ADAPTER) (PDMA_ADAPTER DmaAdapter)
Definition at line 2082 of file hal.h.
typedef VOID(* PPUT_SCATTER_GATHER_LIST) (IN PDMA_ADAPTER DmaAdapter, IN PSCATTER_GATHER_LIST ScatterGather, IN BOOLEAN WriteToDevice)
Definition at line 2166 of file hal.h.
typedef NTSTATUS(* PQUERY_BUS_SLOTS) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG BufferSize, OUT PULONG SlotNumbers, OUT PULONG ReturnedLength)
Definition at line 852 of file hal.h.
typedef ULONG(* PREAD_DMA_COUNTER) (IN PDMA_ADAPTER DmaAdapter)
Definition at line 2141 of file hal.h.
typedef PDEVICE_HANDLER_OBJECT(* PREFERENCE_DEVICE_HANDLER) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN ULONG SlotNumber)
Definition at line 827 of file hal.h.
typedef struct _SCATTER_GATHER_ELEMENT * PSCATTER_GATHER_ELEMENT
typedef struct _SCATTER_GATHER_LIST * PSCATTER_GATHER_LIST
typedef struct _SUPPORTED_RANGE * PSUPPORTED_RANGE
typedef struct _SUPPORTED_RANGES * PSUPPORTED_RANGES
typedef BOOLEAN(* PTRANSLATEBUSADDRESS) (IN struct _BUS_HANDLER *BusHandler, IN struct _BUS_HANDLER *RootHandler, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
Definition at line 811 of file hal.h.
typedef struct _SCATTER_GATHER_ELEMENT SCATTER_GATHER_ELEMENT
typedef struct _SCATTER_GATHER_LIST SCATTER_GATHER_LIST
typedef struct _SUPPORTED_RANGE SUPPORTED_RANGE
typedef struct _SUPPORTED_RANGES SUPPORTED_RANGES
Enumeration Type Documentation
enum _HAL_DISPLAY_BIOS_INFORMATION
Enumerator
HalDisplayInt10Bios
HalDisplayEmulatedBios
HalDisplayNoBios
Definition at line 1729 of file hal.h.
enum _HAL_QUERY_INFORMATION_CLASS
Enumerator
HalInstalledBusInformation
HalProfileSourceInformation
HalInformationClassUnused1
HalPowerInformation
HalProcessorSpeedInformation
HalCallbackInformation
HalMapRegisterInformation
HalMcaLogInformation
HalFrameBufferCachingInformation
HalDisplayBiosInformation
HalProcessorFeatureInformation
HalNumaTopologyInterface
HalErrorInformation
HalCmcLogInformation
HalCpeLogInformation
HalQueryMcaInterface
HalQueryAMLIIllegalIOPortAddresses
HalQueryMaxHotPlugMemoryAddress
HalPartitionIpiInterface
HalPlatformInformation
HalQueryProfileSourceList
HalInitLogInformation
Definition at line 1154 of file hal.h.
enum _HAL_SET_INFORMATION_CLASS
Enumerator
HalProfileSourceInterval
HalProfileSourceInterruptHandler
HalMcaRegisterDriver
HalKernelErrorHandler
HalCmcRegisterDriver
HalCpeRegisterDriver
HalMcaLog
HalCmcLog
HalCpeLog
HalGenerateCmcInterrupt
HalProfileSourceTimerHandler
Definition at line 1181 of file hal.h.
enum KERNEL_MCE_DELIVERY_OPERATION
Enumerator
MceNotification
McaAvailable
CmcAvailable
CpeAvailable
CmcSwitchToPolledMode
CpeSwitchToPolledMode
Definition at line 1873 of file hal.h.
Function Documentation
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID HalAcquireDisplayOwnership (IN PHAL_RESET_DISPLAY_PARAMETERS ResetDisplayParameters)
NTHALAPI NTSTATUS HalAdjustResourceList (IN OUT PIO_RESOURCE_REQUIREMENTS_LIST * pResourceList)
DECLSPEC_DEPRECATED_DDK NTHALAPI NTSTATUS HalAllocateAdapterChannel (IN PADAPTER_OBJECT AdapterObject, IN PWAIT_CONTEXT_BLOCK Wcb, IN ULONG NumberOfMapRegisters, IN PDRIVER_CONTROL ExecutionRoutine)
Referenced by IoAllocateAdapterChannel().
DECLSPEC_DEPRECATED_DDK NTHALAPI PVOID HalAllocateCommonBuffer (IN PADAPTER_OBJECT AdapterObject, IN ULONG Length, OUT PPHYSICAL_ADDRESS LogicalAddress, IN BOOLEAN CacheEnabled)
NTHALAPI PVOID HalAllocateCrashDumpRegisters (IN PADAPTER_OBJECT AdapterObject, IN OUT PULONG NumberOfMapRegisters)
NTSTATUS HalAllocateMapRegisters (IN struct _ADAPTER_OBJECT * DmaAdapter, IN ULONG NumberOfMapRegisters, IN ULONG BaseAddressCount, OUT PMAP_REGISTER_ENTRY MapRegsiterArray)
NTHALAPI BOOLEAN HalAllProcessorsStarted (VOID)
Referenced by Phase1InitializationDiscard().
DECLSPEC_DEPRECATED_DDK NTHALAPI NTSTATUS HalAssignSlotResources (IN PUNICODE_STRING RegistryPath, IN PUNICODE_STRING DriverClassName OPTIONAL, IN PDRIVER_OBJECT DriverObject, IN PDEVICE_OBJECT DeviceObject, IN INTERFACE_TYPE BusType, IN ULONG BusNumber, IN ULONG SlotNumber, IN OUT PCM_RESOURCE_LIST * AllocatedResources)
NTHALAPI VOID HalCalibratePerformanceCounter (IN LONG volatile * Number, IN ULONGLONG NewCount)
Referenced by KiCalibrateTimeAdjustment().
NTHALAPI VOID HalDisableSystemInterrupt (IN ULONG Vector, IN KIRQL Irql)
Referenced by KeDisconnectInterrupt().
NTHALAPI VOID HalDisplayString (PUCHAR String)
NTHALAPI BOOLEAN HalEnableSystemInterrupt (IN ULONG Vector, IN KIRQL Irql, IN KINTERRUPT_MODE InterruptMode)
Referenced by KeConnectInterrupt().
NTSTATUS HalEnumerateEnvironmentVariablesEx (IN ULONG InformationClass, OUT PVOID Buffer, IN OUT PULONG BufferLength)
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID HalFreeCommonBuffer (IN PADAPTER_OBJECT AdapterObject, IN ULONG Length, IN PHYSICAL_ADDRESS LogicalAddress, IN PVOID VirtualAddress, IN BOOLEAN CacheEnabled)
DECLSPEC_DEPRECATED_DDK NTHALAPI PADAPTER_OBJECT HalGetAdapter (IN PDEVICE_DESCRIPTION DeviceDescription, IN OUT PULONG NumberOfMapRegisters)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalGetBusData (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Length)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalGetBusDataByOffset (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
NTHALAPI ARC_STATUS HalGetEnvironmentVariable (IN PCHAR Variable, IN USHORT Length, OUT PCHAR Buffer)
NTHALAPI NTSTATUS HalGetEnvironmentVariableEx (IN PWSTR VariableName, IN LPGUID VendorGuid, OUT PVOID Value, IN OUT PULONG ValueLength, OUT PULONG Attributes OPTIONAL)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalGetInterruptVector (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN ULONG BusInterruptLevel, IN ULONG BusInterruptVector, OUT PKIRQL Irql, OUT PKAFFINITY Affinity)
DECLSPEC_DEPRECATED_DDK NTSTATUS HalGetScatterGatherList (IN PADAPTER_OBJECT DmaAdapter, IN PDEVICE_OBJECT DeviceObject, IN PMDL Mdl, IN PVOID CurrentVa, IN ULONG Length, IN PDRIVER_LIST_CONTROL ExecutionRoutine, IN PVOID Context, IN BOOLEAN WriteToDevice)
NTHALAPI VOID HalHandleNMI (IN OUT PVOID NmiInformation)
Referenced by KiProcessNMI().
NTSTATUS HaliAdjustResourceListRange (IN PSUPPORTED_RANGES SupportedRanges, IN PSUPPORTED_RANGE InterruptRanges, IN OUT PIO_RESOURCE_REQUIREMENTS_LIST * pResourceList)
VOID FASTCALL HaliDereferenceBusHandler (IN PBUS_HANDLER BusHandler)
VOID FASTCALL HaliDerefernceBusHandler (IN PBUS_HANDLER BusHandler)
struct _DMA_ADAPTER* HaliGetDmaAdapter (IN PVOID Context, IN struct _DEVICE_DESCRIPTION * DeviceDescriptor, OUT PULONG NumberOfMapRegisters)
NTSTATUS HaliGetInterruptTranslator (IN INTERFACE_TYPE ParentInterfaceType, IN ULONG ParentBusNumber, IN INTERFACE_TYPE BridgeInterfaceType, IN USHORT Size, IN USHORT Version, OUT PTRANSLATOR_INTERFACE Translator, OUT PULONG BridgeBusNumber)
NTSTATUS HaliHandlePCIConfigSpaceAccess (IN BOOLEAN Read, IN ULONG Addr, IN ULONG Size, IN OUT PULONG pData)
PBUS_HANDLER FASTCALL HaliHandlerForBus (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber)
PBUS_HANDLER FASTCALL HaliHandlerForConfigSpace (IN BUS_DATA_TYPE ConfigSpace, IN ULONG BusNumber)
NTSTATUS HaliInitPnpDriver (VOID)
NTSTATUS HaliInitPowerManagement (IN PPM_DISPATCH_TABLE PmDriverDispatchTable, IN OUT PPM_DISPATCH_TABLE * PmHalDispatchTable)
VOID HaliLocateHiberRanges (IN PVOID MemoryMap)
NTHALAPI VOID HalInitializeProcessor (IN ULONG Number, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by KiInitializeBootStructures().
NTHALAPI BOOLEAN HalInitSystem (IN ULONG Phase, IN PLOADER_PARAMETER_BLOCK LoaderBlock)
Referenced by ExpInitializeExecutive(), and Phase1InitializationDiscard().
NTSTATUS HaliQueryBusSlots (IN PBUS_HANDLER BusHandler, IN ULONG BufferSize, OUT PULONG SlotNumbers, OUT PULONG ReturnedLength)
NTSTATUS HaliQuerySystemInformation (IN HAL_SET_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN OUT PVOID Buffer, OUT PULONG ReturnedLength)
VOID FASTCALL HaliReferenceBusHandler (IN PBUS_HANDLER BusHandler)
PBUS_HANDLER FASTCALL HaliReferenceHandlerForBus (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber)
NTSTATUS HaliRegisterBusHandler (IN INTERFACE_TYPE InterfaceType, IN BUS_DATA_TYPE AssociatedConfigurationSpace, IN ULONG BusNumber, IN INTERFACE_TYPE ParentBusType, IN ULONG ParentBusNumber, IN ULONG SizeofBusExtensionData, IN PINSTALL_BUS_HANDLER InstallBusHandlers, OUT PBUS_HANDLER * BusHandler)
NTSTATUS HaliSetSystemInformation (IN HAL_SET_INFORMATION_CLASS InformationClass, IN ULONG BufferSize, IN PVOID Buffer)
DECLSPEC_DEPRECATED_DDK NTHALAPI BOOLEAN HalMakeBeep (IN ULONG Frequency)
VOID HalpInitBusHandler (VOID)
NTHALAPI VOID HalProcessorIdle (VOID)
DECLSPEC_DEPRECATED_DDK VOID HalPutDmaAdapter (IN PADAPTER_OBJECT DmaAdapter)
DECLSPEC_DEPRECATED_DDK VOID HalPutScatterGatherList (IN PADAPTER_OBJECT DmaAdapter, IN PSCATTER_GATHER_LIST ScatterGather, IN BOOLEAN WriteToDevice)
NTHALAPI VOID HalQueryDisplayParameters (OUT PULONG WidthInCharacters, OUT PULONG HeightInLines, OUT PULONG CursorColumn, OUT PULONG CursorRow)
NTHALAPI BOOLEAN HalQueryRealTimeClock (OUT PTIME_FIELDS TimeFields)
Referenced by Phase1InitializationDiscard().
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalReadDmaCounter (IN PADAPTER_OBJECT AdapterObject)
NTHALAPI VOID HalReportResourceUsage (VOID)
Referenced by Phase1InitializationDiscard().
NTHALAPI VOID HalRequestIpi (IN KAFFINITY Mask)
Referenced by KiIpiSendRequest().
NTHALAPI VOID FASTCALL HalRequestSoftwareInterrupt (KIRQL RequestIrql)
NTHALAPI VOID HalReturnToFirmware (IN FIRMWARE_REENTRY Routine)
Referenced by CmBootLastKnownGood(), and KeBugCheck2().
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalSetBusData (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Length)
DECLSPEC_DEPRECATED_DDK NTHALAPI ULONG HalSetBusDataByOffset (IN BUS_DATA_TYPE BusDataType, IN ULONG BusNumber, IN ULONG SlotNumber, IN PVOID Buffer, IN ULONG Offset, IN ULONG Length)
NTHALAPI VOID HalSetDisplayParameters (IN ULONG CursorColumn, IN ULONG CursorRow)
NTHALAPI ARC_STATUS HalSetEnvironmentVariable (IN PCHAR Variable, IN PCHAR Value)
Referenced by CmBootLastKnownGood().
NTSTATUS HalSetEnvironmentVariableEx (IN PWSTR VariableName, IN LPGUID VendorGuid, IN PVOID Value, IN ULONG ValueLength, IN ULONG Attributes)
NTHALAPI ULONG_PTR HalSetProfileInterval (IN ULONG_PTR Interval)
Referenced by KeSetIntervalProfile().
NTHALAPI BOOLEAN HalSetRealTimeClock (IN PTIME_FIELDS TimeFields)
Referenced by KeSetSystemTime().
NTHALAPI ULONG HalSetTimeIncrement (IN ULONG DesiredIncrement)
NTHALAPI BOOLEAN HalStartNextProcessor (IN PLOADER_PARAMETER_BLOCK LoaderBlock, IN PKPROCESSOR_STATE ProcessorState)
Referenced by KeStartAllProcessors().
NTHALAPI VOID HalStartProfileInterrupt (KPROFILE_SOURCE ProfileSource)
Referenced by KeStartProfile(), and KiStartProfileInterrupt().
NTHALAPI VOID HalStopProfileInterrupt (KPROFILE_SOURCE ProfileSource)
Referenced by KeStopProfile(), and KiStopProfileInterrupt().
ULONG FASTCALL HalSystemVectorDispatchEntry (IN ULONG Vector, OUT PKINTERRUPT_ROUTINE ** FlatDispatch, OUT PKINTERRUPT_ROUTINE * NoConnection)
Referenced by KiGetVectorInfo().
DECLSPEC_DEPRECATED_DDK NTHALAPI BOOLEAN HalTranslateBusAddress (IN INTERFACE_TYPE InterfaceType, IN ULONG BusNumber, IN PHYSICAL_ADDRESS BusAddress, IN OUT PULONG AddressSpace, OUT PPHYSICAL_ADDRESS TranslatedAddress)
DECLSPEC_DEPRECATED_DDK NTHALAPI BOOLEAN IoFlushAdapterBuffers (IN PADAPTER_OBJECT AdapterObject, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN ULONG Length, IN BOOLEAN WriteToDevice)
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID IoFreeAdapterChannel (IN PADAPTER_OBJECT AdapterObject)
DECLSPEC_DEPRECATED_DDK NTHALAPI VOID IoFreeMapRegisters (IN PADAPTER_OBJECT AdapterObject, IN PVOID MapRegisterBase, IN ULONG NumberOfMapRegisters)
DECLSPEC_DEPRECATED_DDK NTHALAPI PHYSICAL_ADDRESS IoMapTransfer (IN PADAPTER_OBJECT AdapterObject, IN PMDL Mdl, IN PVOID MapRegisterBase, IN PVOID CurrentVa, IN OUT PULONG Length, IN BOOLEAN WriteToDevice)
NTHALAPI ULONG KdPortGetByte (OUT PUCHAR Input)
NTHALAPI BOOLEAN KdPortInitialize (PDEBUG_PARAMETERS DebugParameters, PLOADER_PARAMETER_BLOCK LoaderBlock, BOOLEAN Initialize)
NTHALAPI ULONG KdPortPollByte (OUT PUCHAR Input)
NTHALAPI VOID KdPortPutByte (IN UCHAR Output)
NTHALAPI VOID KdPortRestore (VOID)
NTHALAPI VOID KdPortSave (VOID)
NTHALAPI VOID KeFlushWriteBuffer (VOID)
Referenced by NtFlushWriteBuffer().
NTHALAPI LARGE_INTEGER KeQueryPerformanceCounter (OUT PLARGE_INTEGER PerformanceFrequency OPTIONAL)
Referenced by ExpAllocateUuids(), ExpGetProcessorIdleInformation(), KiCalibrateTimeAdjustment(), KiInitMachineDependent(), NtQueryPerformanceCounter(), WmipAddLogHeader(), and WmipGetPerfCounter().
NTHALAPI VOID KeStallExecutionProcessor (IN ULONG MicroSeconds)
Referenced by KeBugCheck2(), and KeFreezeExecution().
typedef PBUS_HANDLER (FASTCALL * pHalHandlerForBus)
typedef VOID (FASTCALL * pHalRefernceBusHandler)
Variable Documentation
HAL_DISPATCH HalDispatchTable
HAL_PRIVATE_DISPATCH HalPrivateDispatchTable