Windows Research Kernel v1.2: C:/Windows Research Kernel/ob/obhandle.c File Reference
obhandle.c File Reference
#include "obp.h"
Macros
#define GENERIC_ACCESS (GENERIC_READ | GENERIC_WRITE | GENERIC_EXECUTE | GENERIC_ALL)
#define OBP_CREATOR_BACKTRACE_INDEX_MASK OBP_CREATOR_BACKTRACE_LIMIT
#define OBP_CREATOR_BACKTRACE_LIMIT 0x7fff
Functions
NTSTATUS NtDuplicateObject (__in HANDLE SourceProcessHandle, __in HANDLE SourceHandle, __in_opt HANDLE TargetProcessHandle, __out_opt PHANDLE TargetHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Options)
VOID ObDereferenceProcessHandleTable (PEPROCESS SourceProcess)
NTSTATUS ObDuplicateObject (IN PEPROCESS SourceProcess, IN HANDLE SourceHandle, IN PEPROCESS TargetProcess OPTIONAL, OUT PHANDLE TargetHandle OPTIONAL, IN ACCESS_MASK DesiredAccess, IN ULONG HandleAttributes, IN ULONG Options, IN KPROCESSOR_MODE PreviousMode)
NTSTATUS ObGetHandleInformation (OUT PSYSTEM_HANDLE_INFORMATION HandleInformation, IN ULONG Length, OUT PULONG ReturnLength OPTIONAL)
NTSTATUS ObGetHandleInformationEx (OUT PSYSTEM_HANDLE_INFORMATION_EX HandleInformation, IN ULONG Length, OUT PULONG ReturnLength OPTIONAL)
ULONG ObGetProcessHandleCount (PEPROCESS Process)
NTSTATUS ObpCaptureHandleInformation (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PVOID HandleTableEntry, IN HANDLE HandleIndex, IN ULONG Length, IN OUT PULONG RequiredLength)
NTSTATUS ObpCaptureHandleInformation (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleIndex, IN ULONG Length, IN OUT PULONG RequiredLength)
NTSTATUS ObpCaptureHandleInformationEx (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO_EX *HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleIndex, IN ULONG Length, IN OUT PULONG RequiredLength)
NTSTATUS ObpChargeQuotaForObject (IN POBJECT_HEADER ObjectHeader, IN POBJECT_TYPE ObjectType, OUT PBOOLEAN NewObject)
USHORT ObpComputeGrantedAccessIndex (ACCESS_MASK GrantedAccess)
NTSTATUS ObpCreateHandle (IN OB_OPEN_REASON OpenReason, IN PVOID Object, IN POBJECT_TYPE ExpectedObjectType OPTIONAL, IN PACCESS_STATE AccessState, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN POBP_LOOKUP_CONTEXT LookupContext, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
NTSTATUS ObpCreateUnnamedHandle (IN PVOID Object, IN ACCESS_MASK DesiredAccess, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
VOID ObpDecrementHandleCount (PEPROCESS Process, POBJECT_HEADER ObjectHeader, POBJECT_TYPE ObjectType, ACCESS_MASK GrantedAccess)
NTSTATUS ObpIncrementHandleCount (OB_OPEN_REASON OpenReason, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, PACCESS_STATE AccessState OPTIONAL, KPROCESSOR_MODE AccessMode, ULONG Attributes)
NTSTATUS ObpIncrementHandleDataBase (IN POBJECT_HEADER ObjectHeader, IN PEPROCESS Process, OUT PULONG NewProcessHandleCount)
NTSTATUS ObpIncrementUnnamedHandleCount (PACCESS_MASK DesiredAccess, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, KPROCESSOR_MODE AccessMode, ULONG Attributes)
POBJECT_HANDLE_COUNT_ENTRY ObpInsertHandleCount (POBJECT_HEADER ObjectHeader)
ACCESS_MASK ObpTranslateGrantedAccessIndex (USHORT GrantedAccessIndex)
NTSTATUS ObpValidateDesiredAccess (IN ACCESS_MASK DesiredAccess)
PHANDLE_TABLE ObReferenceProcessHandleTable (PEPROCESS SourceProcess)
USHORT RtlLogUmodeStackBackTrace (VOID)
Macro Definition Documentation
#define GENERIC_ACCESS (GENERIC_READ | GENERIC_WRITE | GENERIC_EXECUTE | GENERIC_ALL)
Definition at line 25 of file obhandle.c.
Referenced by ObDuplicateObject(), ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
#define OBP_CREATOR_BACKTRACE_INDEX_MASK OBP_CREATOR_BACKTRACE_LIMIT
Definition at line 33 of file obhandle.c.
Referenced by ObpCaptureHandleInformation(), and ObpCaptureHandleInformationEx().
#define OBP_CREATOR_BACKTRACE_LIMIT 0x7fff
Definition at line 32 of file obhandle.c.
Referenced by ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
Function Documentation
NTSTATUS NtDuplicateObject (__in HANDLE SourceProcessHandle, __in HANDLE SourceHandle, __in_opt HANDLE TargetProcessHandle, __out_opt PHANDLE TargetHandle, __in ACCESS_MASK DesiredAccess, __in ULONG HandleAttributes, __in ULONG Options)
Definition at line 727 of file obhandle.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, NT_SUCCESS, NULL, ObDereferenceObject(), ObDuplicateObject(), ObReferenceObjectByHandle, ProbeForWriteHandle, PROCESS_DUP_HANDLE, PsProcessType, Status, and STATUS_SUCCESS.
VOID ObDereferenceProcessHandleTable (PEPROCESS SourceProcess)
Definition at line 150 of file obhandle.c.
References ExReleaseRundownProtection(), and _EPROCESS::RundownProtect.
Referenced by NtQueryInformationProcess(), NtSetInformationProcess(), ObClearProcessHandleTable(), ObDuplicateObject(), ObFindHandleForObject(), ObGetProcessHandleCount(), and ObInitProcess().
NTSTATUS ObDuplicateObject (IN PEPROCESS SourceProcess, IN HANDLE SourceHandle, IN PEPROCESS TargetProcess OPTIONAL, OUT PHANDLE TargetHandle OPTIONAL, IN ACCESS_MASK DesiredAccess, IN ULONG HandleAttributes, IN ULONG Options, IN KPROCESSOR_MODE PreviousMode)
Definition at line 210 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _ACCESS_STATE::AuxData, _HANDLE_TABLE_ENTRY::CreatorBackTraceIndex, DUPLICATE_CLOSE_SOURCE, DUPLICATE_SAME_ACCESS, DUPLICATE_SAME_ATTRIBUTES, ExCreateHandle(), ExMapHandleToPointer(), ExSetHandleInfo(), ExUnlockHandleTableEntry(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _ACCESS_STATE::GenerateOnClose, GENERIC_ACCESS, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HANDLE_INFORMATION::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, _OBJECT_HANDLE_INFORMATION::HandleAttributes, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NtClose(), NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, ObDereferenceObject(), ObDereferenceProcessHandleTable(), ObDuplicateHandle, OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, OBP_CREATOR_BACKTRACE_LIMIT, ObpComputeGrantedAccessIndex(), ObpDecrementHandleCount(), ObpEncodeProtectClose, ObpIncrementHandleCount(), ObpReferenceProcessObjectByHandle(), ObpValidateDesiredAccess(), ObReferenceProcessHandleTable(), PsGetCurrentProcess(), RtlLogStackBackTrace(), RtlLogUmodeStackBackTrace(), RtlMapGenericMask(), RtlZeroMemory, SeAuditHandleCreation(), SeAuditHandleDuplication(), SeCreateAccessState(), _OBJECT_TYPE_INITIALIZER::SecurityProcedure, SeDefaultObjectMethod(), SeDeleteAccessState(), SeDetailedAuditingWithToken(), SeQuerySubjectContextToken, Status, STATUS_ACCESS_DENIED, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ACCESS_STATE::SubjectSecurityContext, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by DbgkpOpenHandles(), and NtDuplicateObject().
NTSTATUS ObGetHandleInformation (OUT PSYSTEM_HANDLE_INFORMATION HandleInformation, IN ULONG Length, OUT PULONG ReturnLength OPTIONAL)
Definition at line 888 of file obhandle.c.
References ARGUMENT_PRESENT, ExSnapShotHandleTables(), FIELD_OFFSET, ObpCaptureHandleInformation(), PAGED_CODE, Status, and STATUS_INFO_LENGTH_MISMATCH.
Referenced by ExpGetHandleInformation().
NTSTATUS ObGetHandleInformationEx (OUT PSYSTEM_HANDLE_INFORMATION_EX HandleInformation, IN ULONG Length, OUT PULONG ReturnLength OPTIONAL)
Definition at line 950 of file obhandle.c.
References ARGUMENT_PRESENT, ExSnapShotHandleTablesEx(), FIELD_OFFSET, ObpCaptureHandleInformationEx(), PAGED_CODE, Status, and STATUS_INFO_LENGTH_MISMATCH.
Referenced by ExpGetHandleInformationEx().
ULONG ObGetProcessHandleCount (PEPROCESS Process)
Definition at line 173 of file obhandle.c.
References _HANDLE_TABLE::HandleCount, ObDereferenceProcessHandleTable(), and ObReferenceProcessHandleTable().
Referenced by ExpCopyProcessInfo(), and NtQueryInformationProcess().
NTSTATUS ObpCaptureHandleInformation (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO * HandleEntryInfo, IN HANDLE UniqueProcessId, IN PVOID HandleTableEntry, IN HANDLE HandleIndex, IN ULONG Length, IN OUT PULONG RequiredLength)
Referenced by ObGetHandleInformation().
NTSTATUS ObpCaptureHandleInformation (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO * HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleIndex, IN ULONG Length, IN OUT PULONG RequiredLength)
Definition at line 1012 of file obhandle.c.
References _OBJECT_HEADER::Body, FLG_KERNEL_STACK_TRACE_DB, _OBJECT_TYPE::Index, NtGlobalFlag, OBJ_HANDLE_ATTRIBUTES, OBP_CREATOR_BACKTRACE_INDEX_MASK, ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpTranslateGrantedAccessIndex(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and _OBJECT_HEADER::Type.
NTSTATUS ObpCaptureHandleInformationEx (IN OUT PSYSTEM_HANDLE_TABLE_ENTRY_INFO_EX * HandleEntryInfo, IN HANDLE UniqueProcessId, IN PHANDLE_TABLE_ENTRY ObjectTableEntry, IN HANDLE HandleIndex, IN ULONG Length, IN OUT PULONG RequiredLength)
Definition at line 1113 of file obhandle.c.
References _OBJECT_HEADER::Body, FLG_KERNEL_STACK_TRACE_DB, _OBJECT_TYPE::Index, NtGlobalFlag, OBJ_HANDLE_ATTRIBUTES, OBP_CREATOR_BACKTRACE_INDEX_MASK, ObpDecodeGrantedAccess, ObpGetHandleAttributes, ObpTranslateGrantedAccessIndex(), Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_SUCCESS, and _OBJECT_HEADER::Type.
Referenced by ObGetHandleInformationEx().
NTSTATUS ObpChargeQuotaForObject (IN POBJECT_HEADER ObjectHeader, IN POBJECT_TYPE ObjectType, OUT PBOOLEAN NewObject)
Definition at line 2201 of file obhandle.c.
References FALSE, _OBJECT_HEADER_QUOTA_INFO::NonPagedPoolCharge, NULL, OB_FLAG_DEFAULT_SECURITY_QUOTA, OB_FLAG_NEW_OBJECT, OBJECT_HEADER_TO_QUOTA_INFO(), _OBJECT_HEADER_QUOTA_INFO::PagedPoolCharge, PsChargeSharedPoolQuota(), PsGetCurrentProcess(), SE_DEFAULT_SECURITY_QUOTA, _OBJECT_HEADER_QUOTA_INFO::SecurityDescriptorCharge, STATUS_QUOTA_EXCEEDED, STATUS_SUCCESS, and TRUE.
Referenced by ObInsertObject(), ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
USHORT ObpComputeGrantedAccessIndex (ACCESS_MASK GrantedAccess)
Referenced by ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
NTSTATUS ObpCreateHandle (IN OB_OPEN_REASON OpenReason, IN PVOID Object, IN POBJECT_TYPE ExpectedObjectType OPTIONAL, IN PACCESS_STATE AccessState, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN POBP_LOOKUP_CONTEXT LookupContext, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
Definition at line 2475 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _HANDLE_TABLE_ENTRY_INFO::AuditMask, _HANDLE_TABLE_ENTRY::CreatorBackTraceIndex, EncodeKernelHandle, ExCreateHandle(), ExMapHandleToPointer(), ExSetHandleInfo(), ExUnlockHandleTableEntry(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeGetPreviousMode, KeLeaveCriticalRegionThread(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, ObCreateHandle, ObDereferenceObject(), OBJ_AUDIT_OBJECT_CLOSE, OBJ_HANDLE_ATTRIBUTES, OBJ_KERNEL_HANDLE, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, OBP_CREATOR_BACKTRACE_LIMIT, ObpComputeGrantedAccessIndex(), ObpDecrementHandleCount(), ObpDecrPointerCountEx, ObpEncodeProtectClose, ObpGetObjectTable, ObpIncrementHandleCount(), ObpIncrPointerCountEx, ObpKernelHandleTable, ObpReleaseLookupContext(), ObpValidateIrql, PAGED_CODE, _EPROCESS::Pcb, _PRIVILEGE_SET::PrivilegeCount, _AUX_ACCESS_DATA::PrivilegesUsed, PsGetCurrentProcess(), PsInitialSystemProcess, RtlLogStackBackTrace(), RtlLogUmodeStackBackTrace(), SeAuditHandleCreation(), SePrivilegeObjectAuditAlarm(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_OBJECT_TYPE_MISMATCH, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ObInsertObject(), ObOpenObjectByName(), and ObOpenObjectByPointer().
NTSTATUS ObpCreateUnnamedHandle (IN PVOID Object, IN ACCESS_MASK DesiredAccess, IN ULONG ObjectPointerBias OPTIONAL, IN ULONG Attributes, IN KPROCESSOR_MODE AccessMode, OUT PVOID *ReferencedNewObject OPTIONAL, OUT PHANDLE Handle)
Definition at line 2886 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _HANDLE_TABLE_ENTRY::CreatorBackTraceIndex, EncodeKernelHandle, ExCreateHandle(), FALSE, FLG_KERNEL_STACK_TRACE_DB, _HANDLE_TABLE_ENTRY::GrantedAccess, _HANDLE_TABLE_ENTRY::GrantedAccessIndex, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), NT_SUCCESS, NtGlobalFlag, NULL, _HANDLE_TABLE_ENTRY::ObAttributes, OBJ_HANDLE_ATTRIBUTES, OBJ_KERNEL_HANDLE, _HANDLE_TABLE_ENTRY::Object, OBJECT_TO_OBJECT_HEADER, OBP_CREATOR_BACKTRACE_LIMIT, ObpComputeGrantedAccessIndex(), ObpDecrementHandleCount(), ObpDecrPointerCountEx, ObpEncodeProtectClose, ObpGetObjectTable, ObpIncrementUnnamedHandleCount(), ObpIncrPointerCountEx, ObpKernelHandleTable, ObpValidateIrql, PAGED_CODE, _EPROCESS::Pcb, PsGetCurrentProcess(), PsInitialSystemProcess, RtlLogStackBackTrace(), RtlLogUmodeStackBackTrace(), Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, TRUE, _OBJECT_HEADER::Type, _OBJECT_TYPE::TypeInfo, and _OBJECT_TYPE_INITIALIZER::ValidAccessMask.
Referenced by ObInsertObject().
VOID ObpDecrementHandleCount (PEPROCESS Process, POBJECT_HEADER ObjectHeader, POBJECT_TYPE ObjectType, ACCESS_MASK GrantedAccess)
Definition at line 2307 of file obhandle.c.
References ASSERT, _OBJECT_HEADER::Body, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_HANDLE_COUNT_DATABASE::CountEntries, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, _OBJECT_HEADER::Flags, _OBJECT_HANDLE_COUNT_ENTRY::HandleCount, _OBJECT_HEADER::HandleCount, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, _OBJECT_HANDLE_COUNT_DATABASE::HandleCountEntries, InterlockedDecrement, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, NULL, OB_FLAG_EXCLUSIVE_OBJECT, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_HANDLE_INFO_EXISTS(), OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), ObpBeginTypeSpecificCallOut, ObpDecrHandleCount, ObpDeleteNameCheck(), ObpEndTypeSpecificCallOut, ObpLockObject, ObpUnlockObject, PAGED_CODE, _OBJECT_HANDLE_COUNT_ENTRY::Process, ProcessHandleCount, _OBJECT_HEADER_HANDLE_INFO::SingleEntry, _OBJECT_TYPE::TotalNumberOfHandles, and _OBJECT_TYPE::TypeInfo.
Referenced by ObDuplicateObject(), ObpCloseHandleTableEntry(), ObpCreateHandle(), and ObpCreateUnnamedHandle().
NTSTATUS ObpIncrementHandleCount (OB_OPEN_REASON OpenReason, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, PACCESS_STATE AccessState OPTIONAL, KPROCESSOR_MODE AccessMode, ULONG Attributes)
Definition at line 1532 of file obhandle.c.
References ACCESS_SYSTEM_SECURITY, ARGUMENT_PRESENT, _LUID_AND_ATTRIBUTES::Attributes, _OBJECT_TYPE_INITIALIZER::CloseProcedure, _PRIVILEGE_SET::Control, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, FALSE, _OBJECT_HEADER::Flags, GENERIC_ACCESS, GENERIC_ALL, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HEADER::HandleCount, _OBJECT_TYPE::HighWaterNumberOfHandles, InsertTailList(), InterlockedIncrement, KernelMode, leave, _LUID_AND_ATTRIBUTES::Luid, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, OB_FLAG_EXCLUSIVE_OBJECT, ObCheckObjectAccess(), ObCreateHandle, ObDuplicateHandle, OBJ_EXCLUSIVE, OBJ_FORCE_ACCESS_CHECK, OBJ_INHERIT, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_EXCLUSIVE_PROCESS, OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObOpenHandle, ObpBeginTypeSpecificCallOut, ObpChargeQuotaForObject(), ObpDecrHandleCount, ObpEndTypeSpecificCallOut, ObpEnterObjectTypeMutex, ObpIncrementHandleDataBase(), ObpIncrHandleCount, ObpIsKernelExclusiveObject(), ObpLeaveObjectTypeMutex, ObpLockObject, ObpUnlockObject, ObpValidateIrql, _OBJECT_TYPE_INITIALIZER::OpenProcedure, PAGED_CODE, _PRIVILEGE_SET::Privilege, PRIVILEGE_SET_ALL_NECESSARY, _PRIVILEGE_SET::PrivilegeCount, ProcessHandleCount, PsGetCurrentProcess(), RtlMapGenericMask(), SeAppendPrivileges(), SePrivilegeCheck(), SePrivilegedServiceAuditAlarm(), SeSecurityPrivilege, Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _OBJECT_TYPE::TotalNumberOfHandles, TRUE, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_HEADER_CREATOR_INFO::TypeList, UserMode, and VOID.
Referenced by ObDupHandleProcedure(), ObDuplicateObject(), and ObpCreateHandle().
NTSTATUS ObpIncrementHandleDataBase (IN POBJECT_HEADER ObjectHeader, IN PEPROCESS Process, OUT PULONG NewProcessHandleCount)
Definition at line 1364 of file obhandle.c.
References _OBJECT_HANDLE_COUNT_DATABASE::CountEntries, _OBJECT_HANDLE_COUNT_ENTRY::HandleCount, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, _OBJECT_HANDLE_COUNT_DATABASE::HandleCountEntries, NULL, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_HANDLE_INFO_EXISTS(), ObpInsertHandleCount(), PAGED_CODE, _OBJECT_HANDLE_COUNT_ENTRY::Process, _OBJECT_HEADER_HANDLE_INFO::SingleEntry, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by ObpIncrementHandleCount(), and ObpIncrementUnnamedHandleCount().
NTSTATUS ObpIncrementUnnamedHandleCount (PACCESS_MASK DesiredAccess, PEPROCESS Process, PVOID Object, POBJECT_TYPE ObjectType, KPROCESSOR_MODE AccessMode, ULONG Attributes)
Definition at line 1918 of file obhandle.c.
References _OBJECT_TYPE_INITIALIZER::CloseProcedure, _OBJECT_HEADER_QUOTA_INFO::ExclusiveProcess, FALSE, _OBJECT_HEADER::Flags, GENERIC_ACCESS, GENERIC_ALL, _OBJECT_TYPE_INITIALIZER::GenericMapping, _OBJECT_HEADER::HandleCount, _OBJECT_TYPE::HighWaterNumberOfHandles, InsertTailList(), InterlockedIncrement, leave, _OBJECT_TYPE_INITIALIZER::MaintainHandleCount, MAXIMUM_ALLOWED, NT_SUCCESS, NULL, OB_FLAG_EXCLUSIVE_OBJECT, ObCreateHandle, OBJ_EXCLUSIVE, OBJ_INHERIT, OBJECT_HEADER_TO_CREATOR_INFO(), OBJECT_HEADER_TO_EXCLUSIVE_PROCESS, OBJECT_HEADER_TO_QUOTA_INFO_EXISTS(), OBJECT_TO_OBJECT_HEADER, ObpBeginTypeSpecificCallOut, ObpChargeQuotaForObject(), ObpDecrHandleCount, ObpEndTypeSpecificCallOut, ObpEnterObjectTypeMutex, ObpIncrementHandleDataBase(), ObpIncrHandleCount, ObpLeaveObjectTypeMutex, ObpLockObject, ObpUnlockObject, ObpValidateIrql, _OBJECT_TYPE_INITIALIZER::OpenProcedure, PAGED_CODE, ProcessHandleCount, PsGetCurrentProcess(), RtlMapGenericMask(), Status, STATUS_ACCESS_DENIED, STATUS_INVALID_PARAMETER, STATUS_SUCCESS, STATUS_UNSUCCESSFUL, _OBJECT_TYPE::TotalNumberOfHandles, TRUE, _OBJECT_TYPE::TypeInfo, _OBJECT_TYPE::TypeList, _OBJECT_HEADER_CREATOR_INFO::TypeList, UNREFERENCED_PARAMETER, and VOID.
Referenced by ObpCreateUnnamedHandle().
POBJECT_HANDLE_COUNT_ENTRY ObpInsertHandleCount (POBJECT_HEADER ObjectHeader)
Definition at line 1214 of file obhandle.c.
References _OBJECT_HANDLE_COUNT_DATABASE::CountEntries, ExAllocatePoolWithTag, ExFreePool(), _OBJECT_HEADER::Flags, _OBJECT_HEADER_HANDLE_INFO::HandleCountDataBase, _OBJECT_HANDLE_COUNT_DATABASE::HandleCountEntries, NULL, OB_FLAG_SINGLE_HANDLE_ENTRY, OBJECT_HEADER_TO_HANDLE_INFO(), PAGED_CODE, PagedPool, RtlCopyMemory, RtlZeroMemory, and _OBJECT_HEADER_HANDLE_INFO::SingleEntry.
Referenced by ObpIncrementHandleDataBase().
ACCESS_MASK ObpTranslateGrantedAccessIndex (USHORT GrantedAccessIndex)
Referenced by ObDupHandleProcedure(), ObpCaptureHandleInformation(), ObpCaptureHandleInformationEx(), ObpCloseHandleTableEntry(), ObpEnumFindHandleProcedure(), ObpReferenceProcessObjectByHandle(), ObpWaitForMultipleObjects(), ObReferenceFileObjectForWrite(), and ObReferenceObjectByHandle().
NTSTATUS ObpValidateDesiredAccess (IN ACCESS_MASK DesiredAccess)
Definition at line 3152 of file obhandle.c.
References STATUS_ACCESS_DENIED, and STATUS_SUCCESS.
Referenced by ObDuplicateObject().
PHANDLE_TABLE ObReferenceProcessHandleTable (PEPROCESS SourceProcess)
Definition at line 107 of file obhandle.c.
References ExAcquireRundownProtection(), ExReleaseRundownProtection(), NULL, _EPROCESS::ObjectTable, and _EPROCESS::RundownProtect.
Referenced by NtQueryInformationProcess(), NtSetInformationProcess(), ObClearProcessHandleTable(), ObDuplicateObject(), ObFindHandleForObject(), ObGetProcessHandleCount(), and ObInitProcess().
USHORT RtlLogUmodeStackBackTrace (VOID)
Definition at line 610 of file stktrace.c.
References FALSE, NULL, RtlpCaptureStackTraceForLogging(), RtlpLogCapturedStackTrace(), and TRUE.
Referenced by ObDuplicateObject(), ObpCreateHandle(), and ObpCreateUnnamedHandle().