Windows Research Kernel v1.2: C:/Windows Research Kernel/se/tokenset.c File Reference
tokenset.c File Reference
#include "pch.h"
Functions
NTSTATUS NtSetInformationToken (__in HANDLE TokenHandle, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __in_bcount(TokenInformationLength) PVOID TokenInformation, __in ULONG TokenInformationLength)
VOID SepAppendDefaultDacl (__in PTOKEN Token, __in PACL PAcl)
VOID SepAppendPrimaryGroup (__in PTOKEN Token, __in PSID PSid)
NTSTATUS SepExpandDynamic (__in PTOKEN Token, __in ULONG NewLength)
VOID SepFreeDefaultDacl (__in PTOKEN Token)
VOID SepFreePrimaryGroup (__in PTOKEN Token)
VOID SepModifyTokenPolicyCounter (__in PSEP_AUDIT_POLICY TokenPolicy, __in BOOLEAN bIncrement)
NTSTATUS SeSetSessionIdToken (__in PACCESS_TOKEN Token, __in ULONG SessionId)
Function Documentation
NTSTATUS NtSetInformationToken (__in HANDLE TokenHandle, __in TOKEN_INFORMATION_CLASS TokenInformationClass, __in_bcount(TokenInformationLength) PVOID TokenInformation, __in ULONG TokenInformationLength)
Definition at line 38 of file tokenset.c.
References _SEP_AUDIT_POLICY_CATEGORIES::AccountLogon, _SEP_AUDIT_POLICY_CATEGORIES::AccountManagement, _ACL::AclSize, ARGUMENT_PRESENT, ASSERT, AuditCategoryAccountLogon, AuditCategoryAccountManagement, AuditCategoryDetailedTracking, AuditCategoryDirectoryServiceAccess, AuditCategoryLogon, AuditCategoryObjectAccess, AuditCategoryPolicyChange, AuditCategoryPrivilegeUse, AuditCategorySystem, _TOKEN::AuditPolicy, _TOKEN_AUDIT_POLICY_ELEMENT::Category, _TOKEN::DefaultDacl, _TOKEN::DefaultOwnerIndex, _SEP_AUDIT_POLICY_CATEGORIES::DetailedTracking, _SEP_AUDIT_POLICY_CATEGORIES::DirectoryServiceAccess, _TOKEN::DynamicCharged, except, EXCEPTION_EXECUTE_HANDLER, FALSE, Index, KeGetPreviousMode, KernelMode, _SEP_AUDIT_POLICY_CATEGORIES::Logon, _TOKEN::LogonSession, NT_SUCCESS, NULL, ObDereferenceObject(), _SEP_AUDIT_POLICY_CATEGORIES::ObjectAccess, ObReferenceObjectByHandle, _TOKEN::OriginatingLogonSession, _TOKEN_ORIGIN::OriginatingLogonSession, _SEP_AUDIT_POLICY::Overlay, PAGED_CODE, PagedPool, _TOKEN_AUDIT_POLICY::Policy, _SEP_AUDIT_POLICY_CATEGORIES::PolicyChange, _TOKEN_AUDIT_POLICY::PolicyCount, _SEP_AUDIT_POLICY::PolicyElements, _TOKEN_AUDIT_POLICY_ELEMENT::PolicyMask, _SEP_AUDIT_POLICY::PolicyOverlay, _TOKEN::PrimaryGroup, _SEP_AUDIT_POLICY_CATEGORIES::PrivilegeUse, ProbeForRead, RtlCopyMemory, RtlEqualSid(), RtlIsZeroLuid, SeCaptureAcl(), SeCaptureAuditPolicy(), SeCaptureSid(), SeLengthSid, SepAcquireTokenReadLock, SepAcquireTokenWriteLock, SepAppendDefaultDacl(), SepAppendPrimaryGroup(), SepDeReferenceLogonSessionDirect(), SepExpandDynamic(), SepFreeDefaultDacl(), SepFreePrimaryGroup(), SepIdAssignableAsGroup(), SepIdAssignableAsOwner(), SepModifyTokenPolicyCounter(), SepReleaseTokenReadLock, SepReleaseTokenWriteLock, SeReleaseAcl(), SeReleaseAuditPolicy(), SeReleaseSid(), SeSetSessionIdToken(), SeSinglePrivilegeCheck(), _SEP_AUDIT_POLICY_OVERLAY::SetBit, SeTcbPrivilege, SeTokenObjectType, _SID_AND_ATTRIBUTES::Sid, Status, STATUS_ALLOTTED_SPACE_EXCEEDED, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_OWNER, STATUS_INVALID_PARAMETER, STATUS_INVALID_PRIMARY_GROUP, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, _SEP_AUDIT_POLICY_CATEGORIES::System, TOKEN_ADJUST_DEFAULT, TOKEN_ADJUST_SESSIONID, TOKEN_SESSION_NOT_REFERENCED, TokenAuditPolicy, TokenDefaultDacl, _TOKEN::TokenFlags, TokenOrigin, TokenOwner, TokenPrimaryGroup, TokenSessionId, TokenSessionReference, TRUE, and _TOKEN::UserAndGroups.
VOID SepAppendDefaultDacl (__in PTOKEN Token, __in PACL PAcl)
Definition at line 1218 of file tokenset.c.
References ARGUMENT_PRESENT, ASSERT, PAGED_CODE, RtlCopyMemory, and SeLengthSid.
Referenced by NtSetInformationToken().
VOID SepAppendPrimaryGroup (__in PTOKEN Token, __in PSID PSid)
Definition at line 1140 of file tokenset.c.
References ARGUMENT_PRESENT, ASSERT, PAGED_CODE, RtlCopyMemory, and SeLengthSid.
Referenced by NtSetInformationToken().
NTSTATUS SepExpandDynamic (__in PTOKEN Token, __in ULONG NewLength)
Definition at line 953 of file tokenset.c.
References ExAllocatePoolWithTag, ExFreePool(), NULL, PagedPool, RtlCopyMemory, SeLengthSid, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by NtSetInformationToken().
VOID SepFreeDefaultDacl (__in PTOKEN Token)
Definition at line 1077 of file tokenset.c.
References ARGUMENT_PRESENT, NULL, PAGED_CODE, RtlMoveMemory, and SeLengthSid.
Referenced by NtSetInformationToken().
VOID SepFreePrimaryGroup (__in PTOKEN Token)
Definition at line 1018 of file tokenset.c.
References ARGUMENT_PRESENT, PAGED_CODE, RtlMoveMemory, and SeLengthSid.
Referenced by NtSetInformationToken().
VOID SepModifyTokenPolicyCounter (__in PSEP_AUDIT_POLICY TokenPolicy, __in BOOLEAN bIncrement)
Routine Description:
This modifies the global SepTokenPolicyCounter hint which records the number of
tokens in the system with per user auditing settings.
Arguments:
TokenPolicy - the policy which should be reflected in the hint.
bIncrement - boolean indicating if this policy is being added (TRUE) or
    deleted (FALSE) from the counters.
Return Value:
None.
Definition at line 880 of file tokenset.c.
References ASSERT, AuditCategoryAccountLogon, AuditCategoryAccountManagement, AuditCategoryDetailedTracking, AuditCategoryDirectoryServiceAccess, AuditCategoryLogon, AuditCategoryObjectAccess, AuditCategoryPolicyChange, AuditCategoryPrivilegeUse, AuditCategorySystem, InterlockedExchangeAdd(), and SepTokenPolicyCounter.
Referenced by NtSetInformationToken().
NTSTATUS SeSetSessionIdToken (__in PACCESS_TOKEN Token, __in ULONG SessionId)
Definition at line 1290 of file tokenset.c.
References FALSE, PAGED_CODE, SepAcquireTokenWriteLock, SepReleaseTokenWriteLock, and STATUS_SUCCESS.
Referenced by NtSetInformationToken().