Windows Research Kernel v1.2: C:/Windows Research Kernel/mm/sectsup.c File Reference
sectsup.c File Reference
#include "mi.h"
Macros
#define DELETE_ON_CLOSE 0x1
#define DEREF_SEGMENT 0x2
#define DEVICE_PHYSICAL_MEMORY L"\\Device\\PhysicalMemory"
#define MI_INSTRUMENT_DEREF_ACTION(i)
#define MI_LOG_DEREF_INFO(a, b, c)
#define TYPE_SECTION L"Section"
Typedefs
typedef enum _SEGMENT_DEREFERENCE_OBJECT BALANCE_OBJECT
Enumerations
enum _SEGMENT_DEREFERENCE_OBJECT { SegmentDereference, UsedSegmentCleanup, SegMaximumObject }
Functions
ULONG MiCanFileBeTruncatedInternal (IN PSECTION_OBJECT_POINTERS SectionPointer, IN PLARGE_INTEGER NewFileSize OPTIONAL, IN LOGICAL BlockNewViews, OUT PKIRQL PreviousIrql)
VOID MiCheckControlArea (IN PCONTROL_AREA ControlArea, IN KIRQL PreviousIrql)
LOGICAL MiCheckControlAreaStatus (IN SECTION_CHECK_TYPE SectionCheckType, IN PSECTION_OBJECT_POINTERS SectionObjectPointers, IN ULONG DelayClose, OUT PCONTROL_AREA *ControlAreaOut, OUT PKIRQL PreviousIrql)
VOID MiCheckForControlAreaDeletion (IN PCONTROL_AREA ControlArea)
VOID MiCleanSection (IN PCONTROL_AREA ControlArea, IN LOGICAL DirtyDataPagesOk)
VOID MiDereferenceControlAreaBySection (IN PCONTROL_AREA ControlArea, IN ULONG UserRef)
VOID MiDereferenceSegmentThread (IN PVOID StartContext)
VOID MiFreeEventCounter (IN PEVENT_COUNTER Support)
PEVENT_COUNTER MiGetEventCounter (VOID)
VOID FASTCALL MiInsertBasedSection (IN PSECTION Section)
VOID FASTCALL MiRemoveBasedSection (IN PSECTION Section)
VOID MiRemoveUnusedSegments (VOID)
VOID MiSectionDelete (IN PVOID Object)
ULONG MiSectionInitialization ()
VOID MiSegmentDelete (PSEGMENT Segment)
BOOLEAN MmCanFileBeTruncated (__in PSECTION_OBJECT_POINTERS SectionPointer, __in_opt PLARGE_INTEGER NewFileSize)
ULONG MmDoesFileHaveUserWritableReferences (IN PSECTION_OBJECT_POINTERS SectionPointer)
BOOLEAN MmForceSectionClosed (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN DelayClose)
NTSTATUS MmGetFileNameForAddress (IN PVOID ProcessVa, OUT PUNICODE_STRING FileName)
NTSTATUS MmGetFileNameForSection (IN PSECTION SectionObject, OUT POBJECT_NAME_INFORMATION *FileNameInfo)
PFILE_OBJECT MmGetFileObjectForSection (IN PVOID Section)
PFILE_OBJECT * MmPerfUnusedSegmentsEnumerate (VOID)
Variables
POBJECT_TYPE IoFileObjectType
MMPAGE_FILE_EXPANSION MiPageFileContract
const GENERIC_MAPPING MiSectionMapping
ULONG MiSubsectionActions
ULONG MiSubsectionsProcessed
const ULONG MMCONTROL
SIZE_T MmSharedCommit = 0
ULONG MmUnusedSegmentForceFree
Macro Definition Documentation
#define DELETE_ON_CLOSE 0x1
Referenced by MiCheckControlArea().
#define DEREF_SEGMENT 0x2
Referenced by MiCheckControlArea().
#define DEVICE_PHYSICAL_MEMORY L"\\Device\\PhysicalMemory"
Referenced by MiSectionInitialization().
#define MI_INSTRUMENT_DEREF_ACTION (i)
Definition at line 3315 of file sectsup.c.
Referenced by MiRemoveUnusedSegments().
#define MI_LOG_DEREF_INFO (a, b, c)
Definition at line 41 of file sectsup.c.
Referenced by MiRemoveUnusedSegments().
#define TYPE_SECTION L"Section"
Referenced by MiSectionInitialization().
Typedef Documentation
typedef enum _SEGMENT_DEREFERENCE_OBJECT BALANCE_OBJECT
Enumeration Type Documentation
enum _SEGMENT_DEREFERENCE_OBJECT
Enumerator
SegmentDereference
UsedSegmentCleanup
SegMaximumObject
Definition at line 57 of file sectsup.c.
Function Documentation
ULONG MiCanFileBeTruncatedInternal (IN PSECTION_OBJECT_POINTERS SectionPointer, IN PLARGE_INTEGER NewFileSize OPTIONAL, IN LOGICAL BlockNewViews, OUT PKIRQL PreviousIrql)
Definition at line 3070 of file sectsup.c.
References ARGUMENT_PRESENT, ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _SUBSECTION::ControlArea, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMSECTION_FLAGS::Image, _MAPPED_FILE_SEGMENT::LastSubsectionHint, LOCK_PFN, _LARGE_INTEGER::LowPart, MiEndingOffset(), MiIsAddressValid(), MmFlushForWrite, MmFlushImageSection(), _SUBSECTION::NextSubsection, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfUserReferences, PAGE_SIZE, _LARGE_INTEGER::QuadPart, _MMSECTION_FLAGS::Rom, _CONTROL_AREA::Segment, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
Referenced by MmCanFileBeTruncated(), and MmPurgeSection().
VOID MiCheckControlArea (IN PCONTROL_AREA ControlArea, IN KIRQL PreviousIrql)
Definition at line 2302 of file sectsup.c.
References Action, ASSERT, DELETE_ON_CLOSE, DEREF_SEGMENT, _EVENT_COUNTER::Event, FALSE, KeSetEvent(), MI_INSERT_UNUSED_SEGMENT, MI_UNUSED_SEGMENTS_SURPLUS, MiCleanSection(), MiPurgeImageSection(), MiRemoveImageSectionObject(), MiSegmentDelete(), MM_PFN_LOCK_ASSERT, MmUnusedSegmentCleanup, NULL, TRUE, and UNLOCK_PFN.
Referenced by MiDereferenceControlArea(), MiDereferenceControlAreaBySection(), MiDispatchFault(), MiFlushRelease(), MiRemoveMappedPtes(), MiRemoveMappedView(), MiShutdownSystem(), MiWriteComplete(), MmCreateSection(), MmFlushImageSection(), MmFlushSection(), MmMapViewInSystemCache(), MmPurgeSection(), and MmUnmapViewInSystemCache().
LOGICAL MiCheckControlAreaStatus (IN SECTION_CHECK_TYPE SectionCheckType, IN PSECTION_OBJECT_POINTERS SectionObjectPointers, IN ULONG DelayClose, OUT PCONTROL_AREA * ControlAreaOut, OUT PKIRQL PreviousIrql)
Definition at line 2603 of file sectsup.c.
References ASSERT, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, CheckBothSection, CheckImageSection, CheckUserDataSection, _MMSECTION_FLAGS::DeleteOnClose, _EVENT_COUNTER::Event, FALSE, _CONTROL_AREA::Flags, InterlockedPushEntrySList(), KeDelayExecutionThread(), KeEnterCriticalRegionThread(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KernelMode, KeWaitForSingleObject(), _EVENT_COUNTER::ListEntry, LOCK_PFN, MiFreeEventCounter(), MiGetEventCounter(), MmEventCountSListHead, MmShortTime, NULL, _CONTROL_AREA::NumberOfMappedViews, _CONTROL_AREA::NumberOfSectionReferences, _CONTROL_AREA::NumberOfUserReferences, PSLIST_ENTRY, _EVENT_COUNTER::RefCount, TRUE, _CONTROL_AREA::u, UNLOCK_PFN, UNLOCK_PFN_AND_THEN_WAIT, _CONTROL_AREA::WaitingForDeletion, and WrPageOut.
Referenced by MmFlushImageSection(), and MmForceSectionClosed().
VOID MiCheckForControlAreaDeletion (IN PCONTROL_AREA ControlArea)
Definition at line 2509 of file sectsup.c.
References ASSERT, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, InsertTailList(), KeReleaseSemaphore(), _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMDEREFERENCE_SEGMENT_HEADER::Lock, MI_UNUSED_SEGMENTS_REMOVE_CHARGE, MiRemoveImageSectionObject(), MM_PFN_LOCK_ASSERT, MmDereferenceSegmentHeader, NULL, RemoveEntryList(), and _MMDEREFERENCE_SEGMENT_HEADER::Semaphore.
Referenced by MiRemoveUnusedSegments(), and MiRestoreTransitionPte().
VOID MiCleanSection (IN PCONTROL_AREA ControlArea, IN LOGICAL DirtyDataPagesOk)
Definition at line 1255 of file sectsup.c.
References APC_LEVEL, ASSERT, _MDL::ByteCount, _SUBSECTION::ControlArea, _MMPFN::e1, _MMPFN::e2, FALSE, _CONTROL_AREA::Flags, FreePageList, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _IO_STATUS_BLOCK::Information, IoSynchronousPageWrite(), IS_PTE_NOT_DEMAND_ZERO, KdPrint, KeBugCheckEx(), KeClearEvent(), KeDelayExecutionThread(), KeInitializeEvent(), KeLowerIrql, KernelMode, KeWaitForSingleObject(), LOCK_PFN, _MMPTE::Long, _MDL::MappedSystemVa, MDL_MAPPED_TO_SYSTEM_VA, MDL_PAGES_LOCKED, _MDL::MdlFlags, MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_INITIALIZE_ZERO_MDL, MI_IS_PFN_DELETED, MI_PFN_ELEMENT, MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MI_SET_MODIFIED, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE, MiCheckProtoPtePageState(), MiDecrementShareCountInline, MiDeferredUnlockPages(), MiEndingOffset(), MiGetPteAddress, MiGetSubsectionAddress, MiInsertPageInFreeList(), MiIoRetryMask, MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), MiReleasePageFileSpace(), MiRemoveImageSectionObject(), MiSegmentDelete(), MiStartingOffset(), MiUnlinkPageFromList(), Mm30Milliseconds, MM_MAXIMUM_WRITE_CLUSTER, MM_NOIRQL, MmIsRetryIoStatus, MmMappedFileIoComplete, MmModifiedWriteClusterSize, MmShortTime, MmUnmapLockedPages(), _MMPFNENTRY::Modified, _SUBSECTION::NextSubsection, NotificationEvent, NT_SUCCESS, NULL, _MMPFN::OriginalPte, PAGE_SIZE, _MMPTE_TRANSITION::PageFrameNumber, _MMPFNENTRY::PageLocation, POOL_CORRUPTION_IN_FILE_AREA, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteAddress, _MMPFN::PteFrame, _SUBSECTION::PtesInSubsection, _LARGE_INTEGER::QuadPart, _MDL::Size, _MMPTE::Soft, _MDL::StartVa, Status, _IO_STATUS_BLOCK::Status, _SUBSECTION::SubsectionBase, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, UNLOCK_PFN_AND_THEN_WAIT, _MMPTE_HARDWARE::Valid, and WrPageOut.
Referenced by MiCheckControlArea(), MiRemoveUnusedSegments(), MmFlushImageSection(), and MmForceSectionClosed().
VOID MiDereferenceControlAreaBySection (IN PCONTROL_AREA ControlArea, IN ULONG UserRef)
Definition at line 672 of file sectsup.c.
References LOCK_PFN, and MiCheckControlArea().
Referenced by MiSectionDelete().
VOID MiDereferenceSegmentThread (IN PVOID StartContext)
Definition at line 799 of file sectsup.c.
References ASSERT, CONTAINING_RECORD, _CONTROL_AREA::DereferenceList, DISPATCH_LEVEL, _MMPAGE_FILE_EXPANSION::Event, ExAcquireSpinLock, ExReleaseSpinLock, FALSE, _MMSECTION_FLAGS::FilePointerNull, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, IsListEmpty, KdPrint, KeClearEvent(), KeGetCurrentIrql(), KeSetEvent(), KeSetPriorityThread(), KeWaitForMultipleObjects(), _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMDEREFERENCE_SEGMENT_HEADER::Lock, LOW_REALTIME_PRIORITY, _ETHREAD::MemoryMaker, MI_CONTRACT_PAGEFILES, MiAttemptPageFileReduction(), MiExtendPagingFiles(), MiRemoveUnusedSegments(), MiSegmentDelete(), MmDereferenceSegmentHeader, MmUnusedSegmentCleanup, NULL, PsGetCurrentThread(), RemoveHeadList(), _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, SegMaximumObject, _CONTROL_AREA::Segment, SegmentDereference, _MMDEREFERENCE_SEGMENT_HEADER::Semaphore, Status, _ETHREAD::Tcb, _CONTROL_AREA::u, UNREFERENCED_PARAMETER, UsedSegmentCleanup, UserMode, WaitAny, and WrVirtualMemory.
Referenced by MiFlushSectionInternal(), MiIdentifyPfn(), MiIssuePageExtendRequest(), and MiSectionInitialization().
VOID MiFreeEventCounter (IN PEVENT_COUNTER Support)
Definition at line 2938 of file sectsup.c.
References ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, ExFreePool(), ExQueryDepthSList, InterlockedDecrement, InterlockedPopEntrySList(), InterlockedPushEntrySList(), KeGetCurrentIrql(), MmEventCountSListHead, NULL, and PSLIST_ENTRY.
Referenced by MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), and MmCreateSection().
PEVENT_COUNTER MiGetEventCounter (VOID)
Definition at line 2868 of file sectsup.c.
References ASSERT, CONTAINING_RECORD, DISPATCH_LEVEL, _EVENT_COUNTER::Event, ExAllocatePoolWithTag, ExQueryDepthSList, FALSE, InterlockedPopEntrySList(), KeClearEvent(), KeGetCurrentIrql(), KeInitializeEvent(), _EVENT_COUNTER::ListEntry, MmEventCountSListHead, NonPagedPool, NotificationEvent, NULL, PSLIST_ENTRY, and _EVENT_COUNTER::RefCount.
Referenced by MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), and MmCreateSection().
VOID FASTCALL MiInsertBasedSection (IN PSECTION Section)
Definition at line 89 of file sectsup.c.
References ASSERT, MiInsertNode(), and MmSectionBasedRoot.
Referenced by MmCreateSection().
VOID FASTCALL MiRemoveBasedSection (IN PSECTION Section)
Definition at line 125 of file sectsup.c.
References MiRemoveNode(), and MmSectionBasedRoot.
Referenced by MiSectionDelete().
VOID MiRemoveUnusedSegments (VOID)
Definition at line 3320 of file sectsup.c.
References _MMSECTION_FLAGS::Accessed, ASSERT, _MMSECTION_FLAGS::BeingDeleted, CcUnmapInactiveViews(), CONTAINING_RECORD, _MSUBSECTION::ControlArea, _SECTION_OBJECT_POINTERS::DataSectionObject, _CONTROL_AREA::DereferenceList, _MSUBSECTION::DereferenceList, _MMPFN::e1, _MMPFN::e2, _MMPAGE_FILE_EXPANSION::Event, ExAcquireSpinLock, ExFreePool(), ExReleaseSpinLock, FALSE, _CONTROL_AREA::FilePointer, _MMSECTION_FLAGS::FilePointerNull, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, FreePageList, FSRTL_FSP_TOP_LEVEL_IRP, FsRtlAcquireFileForCcFlushEx(), FsRtlReleaseFileForCcFlush(), _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _SECTION_OBJECT_POINTERS::ImageSectionObject, InsertTailList(), IoSetTopLevelIrp(), IsListEmpty, KeBugCheckEx(), KeDelayExecutionThread(), KernelMode, KeSetEvent(), _MMDEREFERENCE_SEGMENT_HEADER::ListHead, _MMDEREFERENCE_SEGMENT_HEADER::Lock, LOCK_PFN, _MMPTE::Long, MI_CONTRACT_PAGEFILES, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_INSERT_UNUSED_SEGMENT, MI_INSTRUMENT_DEREF_ACTION, MI_LOG_DEREF_INFO, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_UNUSED_SEGMENTS_REMOVE_CHARGE, MI_UNUSED_SEGMENTS_SURPLUS, MI_UNUSED_SUBSECTIONS_COUNT_INSERT, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MiAttemptPageFileReduction(), MiCheckForControlAreaDeletion(), MiCheckProtoPtePageState(), MiCleanSection(), MiDecrementShareCountInline, MiExtendPagingFiles(), MiFlushSectionInternal(), MiInsertPageInFreeList(), MiIsPteOnPdeBoundary, MiReleasePageFileSpace(), MiSegmentDelete(), MiSubsectionActions, MiSubsectionsProcessed, MiUnlinkPageFromList(), MM_FLUSH_FAIL_COLLISIONS, MM_FLUSH_IN_PARALLEL, MM_FLUSH_SEG_DEREF, MmDereferenceSegmentHeader, MmShortTime, MmUnusedSegmentCount, MmUnusedSegmentForceFree, MmUnusedSegmentList, MmUnusedSubsectionList, _MMPFNENTRY::Modified, _CONTROL_AREA::ModifiedWriteCount, _MMSECTION_FLAGS::Networked, _SUBSECTION::NextSubsection, _MMSECTION_FLAGS::NoModifiedWriting, NOTHING, NT_SUCCESS, NULL, _CONTROL_AREA::NumberOfMappedViews, _MSUBSECTION::NumberOfMappedViews, _CONTROL_AREA::NumberOfPfnReferences, _CONTROL_AREA::NumberOfSectionReferences, _MMPFN::OriginalPte, PAGE_SIZE, _MMPFNENTRY::PageLocation, _MMSECTION_FLAGS::PhysicalMemory, PIRP, POOL_CORRUPTION_IN_FILE_AREA, _MMPTE_SOFTWARE::Prototype, _MMPFN::PteFrame, _SUBSECTION::PtesInSubsection, _MSUBSECTION::PtesInSubsection, RemoveHeadList(), _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, _MMSECTION_FLAGS::Rom, _FILE_OBJECT::SectionObjectPointer, _CONTROL_AREA::Segment, _MMPTE::Soft, Status, STATUS_ENCOUNTERED_WRITE_IN_PROGRESS, STATUS_FILE_LOCK_CONFLICT, STATUS_SUCCESS, _MMSUBSECTION_FLAGS2::SubsectionAccessed, _SUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionBase, _MSUBSECTION::SubsectionFlags, _MSUBSECTION::SubsectionFlags2, _MMSUBSECTION_FLAGS::SubsectionStatic, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MSUBSECTION::u, _MSUBSECTION::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, and _MMPTE_HARDWARE::Valid.
Referenced by MiDereferenceSegmentThread().
VOID MiSectionDelete (IN PVOID Object)
Definition at line 712 of file sectsup.c.
References _SECTION::Address, ASSERT, _SEGMENT::ControlArea, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _SECTION::Flags, _MMSECTION_FLAGS::Image, _SECTION::InitialPageProtection, InterlockedDecrement, KeAcquireGuardedMutex(), KeReleaseGuardedMutex(), MiDereferenceControlAreaBySection(), MiRemoveBasedSection(), MmSectionBasedMutex, NULL, PAGE_EXECUTE_READWRITE, PAGE_READWRITE, _SECTION::Segment, _MMADDRESS_NODE::StartingVpn, _CONTROL_AREA::u, _SECTION::u, _MMSECTION_FLAGS::UserReference, _MMSECTION_FLAGS::UserWritable, and _CONTROL_AREA::WritableUserReferences.
Referenced by MiSectionInitialization().
ULONG MiSectionInitialization ()
Definition at line 958 of file sectsup.c.
References ASSERT, _MM_AVL_TABLE::BalancedRoot, _UNICODE_STRING::Buffer, _SEGMENT::ControlArea, _OBJECT_TYPE_INITIALIZER::DefaultPagedPoolCharge, _OBJECT_TYPE_INITIALIZER::DeleteProcedure, DEVICE_PHYSICAL_MEMORY, ExAllocatePoolWithTag, ExFreePool(), FALSE, _CONTROL_AREA::Flags, _OBJECT_TYPE_INITIALIZER::GenericMapping, Handle, InitializeObjectAttributes, _SECTION::InitialPageProtection, _OBJECT_TYPE_INITIALIZER::InvalidAttributes, KernelMode, _OBJECT_TYPE_INITIALIZER::Length, _UNICODE_STRING::Length, _MMPTE::Long, _SECTION::LongFlags, _UNICODE_STRING::MaximumLength, MiDereferenceSegmentThread(), MiSectionDelete(), MiSectionMapping, MMCONTROL, MmSectionBasedRoot, MmSectionObjectType, NonPagedPool, NT_SUCCESS, NtClose(), NULL, _MM_AVL_TABLE::NumberGenericTableElements, _CONTROL_AREA::NumberOfSectionReferences, ObCreateObject, ObCreateObjectType(), ObInsertObject(), OBJ_KERNEL_EXCLUSIVE, OBJ_OPENLINK, OBJ_PERMANENT, PAGE_EXECUTE_READWRITE, PagedPool, _MMADDRESS_NODE::Parent, PHYSICAL_ADDRESS_BITS, _MMSECTION_FLAGS::PhysicalMemory, _OBJECT_TYPE_INITIALIZER::PoolType, PsCreateSystemThread(), _LARGE_INTEGER::QuadPart, RtlZeroMemory, SECTION_ALL_ACCESS, SECTION_MAP_READ, _CONTROL_AREA::Segment, _SECTION::Segment, _SEGMENT::SegmentPteTemplate, _SECTION::SizeOfSection, Status, THREAD_ALL_ACCESS, TRUE, TYPE_SECTION, _MMPTE::u, _CONTROL_AREA::u, _SECTION::u, _MMADDRESS_NODE::u1, _OBJECT_TYPE_INITIALIZER::UseDefaultObject, _OBJECT_TYPE_INITIALIZER::ValidAccessMask, and ZwClose().
VOID MiSegmentDelete (PSEGMENT Segment)
Definition at line 157 of file sectsup.c.
References ASSERT, _MMPFN::AweAllocation, _SEGMENT::BasedAddress, _MMSECTION_FLAGS::BeingCreated, _MMSECTION_FLAGS::BeingDeleted, _SEGMENT::ControlArea, _SECTION_OBJECT_POINTERS::DataSectionObject, DbgUnLoadImageSymbols(), _MMSECTION_FLAGS::DebugSymbolsLoaded, _CONTROL_AREA::DereferenceList, _MSUBSECTION::DereferenceList, _MMPFN::e1, _MMPFN::e2, _EVENT_COUNTER::Event, ExAcquireSpinLockAtDpcLevel, ExFreePool(), ExReleaseSpinLockFromDpcLevel, FALSE, _MMSECTION_FLAGS::File, _FILE_OBJECT::FileName, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _LIST_ENTRY::Flink, _MMSECTION_FLAGS::GlobalOnlyPerSession, _MMPTE::Hard, _MMSECTION_FLAGS::Image, _SECTION_OBJECT_POINTERS::ImageSectionObject, InterlockedExchangeAddSizeT, IS_PTE_NOT_DEMAND_ZERO, KeSetEvent(), _SEGMENT_FLAGS::LargePages, _MMDEREFERENCE_SEGMENT_HEADER::Lock, LOCK_PFN, _MMPTE::Long, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_PAGE_FRAME_FROM_TRANSITION_PTE, MI_INCREMENT_RESIDENT_AVAILABLE, MI_IS_PFN_DELETED, MI_PFN_ELEMENT, MI_SET_PFN_DELETED, MI_UNUSED_SEGMENTS_REMOVE_CHARGE, MI_UNUSED_SUBSECTIONS_COUNT_REMOVE, MI_WRITE_ZERO_PTE, MiDecrementShareCountInline, MiGetPteAddress, MiInsertPageInFreeList(), MiIsPteOnPdeBoundary, MiMakeSystemAddressValidPfn(), MiReleasePageFileSpace(), MiReturnCommitment, MiUnlinkPageFromList(), MM_DBG_COMMIT_RETURN_SEGMENT_DELETE1, MM_DBG_COMMIT_RETURN_SEGMENT_DELETE2, MM_DBG_COMMIT_RETURN_SEGMENT_DELETE3, MM_RESAVAIL_FREE_LARGE_PAGES_PF_BACKED, MM_TRACK_COMMIT, MmDereferenceSegmentHeader, MmSharedCommit, _SUBSECTION::NextSubsection, _MSUBSECTION::NextSubsection, _SEGMENT::NonExtendedPtes, NT_SUCCESS, NULL, _SEGMENT::NumberOfCommittedPages, ObDereferenceObject(), _MMPFN::OriginalPte, _MMPTE_TRANSITION::PageFrameNumber, _MMPTE_HARDWARE::PageFrameNumber, _MMPTE_SOFTWARE::Prototype, _MMPFNENTRY::PrototypePte, PsGetCurrentProcess(), _MMPFN::PteAddress, _MMPFN::PteFrame, RemoveEntryList(), _MMSECTION_FLAGS::Rom, RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), _FILE_OBJECT::SectionObjectPointer, _SEGMENT::SegmentFlags, _MMPFN::ShareCount, _MMPTE::Soft, Status, _SUBSECTION::SubsectionBase, _MMPTE::Trans, _MMPTE_SOFTWARE::Transition, TRUE, _MMPTE::u, _CONTROL_AREA::u, _MMPFN::u2, _MMPFN::u3, _MMPFN::u4, UNLOCK_PFN, _MMPTE_HARDWARE::Valid, _CONTROL_AREA::WaitingForDeletion, and _CONTROL_AREA::WritableUserReferences.
Referenced by MiCheckControlArea(), MiCleanSection(), MiDereferenceSegmentThread(), and MiRemoveUnusedSegments().
BOOLEAN MmCanFileBeTruncated (__in PSECTION_OBJECT_POINTERS SectionPointer, __in_opt PLARGE_INTEGER NewFileSize)
Definition at line 3008 of file sectsup.c.
References ARGUMENT_PRESENT, FALSE, MiCanFileBeTruncatedInternal(), TRUE, and UNLOCK_PFN.
Referenced by CcPurgeCacheSection().
ULONG MmDoesFileHaveUserWritableReferences (IN PSECTION_OBJECT_POINTERS SectionPointer)
Definition at line 610 of file sectsup.c.
References LOCK_PFN, NULL, UNLOCK_PFN, and _CONTROL_AREA::WritableUserReferences.
BOOLEAN MmForceSectionClosed (__in PSECTION_OBJECT_POINTERS SectionObjectPointer, __in BOOLEAN DelayClose)
Definition at line 1143 of file sectsup.c.
References ASSERT, _MMSECTION_FLAGS::BeingDeleted, CheckBothSection, _CONTROL_AREA::Flags, MiCheckControlAreaStatus(), MiCleanSection(), NULL, _CONTROL_AREA::NumberOfMappedViews, TRUE, _CONTROL_AREA::u, and UNLOCK_PFN.
NTSTATUS MmGetFileNameForAddress (IN PVOID ProcessVa, OUT PUNICODE_STRING FileName)
Definition at line 2129 of file sectsup.c.
References ASSERT, _UNICODE_STRING::Buffer, _MMVAD::ControlArea, ExAllocatePoolWithTag, ExFreePool(), _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::Image, _UNICODE_STRING::Length, LOCK_ADDRESS_SPACE, MiLocateAddress(), _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObDereferenceObject(), ObQueryNameString(), ObReferenceObject, PAGED_CODE, PagedPool, _MMVAD_FLAGS::PrivateMemory, PsGetCurrentProcess(), RtlMoveMemory, Status, STATUS_INVALID_ADDRESS, STATUS_NO_MEMORY, STATUS_SECTION_NOT_IMAGE, TRUE, _CONTROL_AREA::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, and _MMVAD::VadFlags.
Referenced by DbgkpPostFakeModuleMessages().
NTSTATUS MmGetFileNameForSection (IN PSECTION SectionObject, OUT POBJECT_NAME_INFORMATION * FileNameInfo)
Definition at line 2031 of file sectsup.c.
References ExAllocatePoolWithTag, ExFreePool(), NT_SUCCESS, NULL, NumberOfBytes, ObQueryNameString(), PagedPool, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_NO_MEMORY, STATUS_SECTION_NOT_IMAGE, and STATUS_SUCCESS.
PFILE_OBJECT MmGetFileObjectForSection (IN PVOID Section)
Definition at line 2262 of file sectsup.c.
References ASSERT, KeGetCurrentIrql(), NULL, and PASSIVE_LEVEL.
Referenced by PsReferenceProcessFilePointer().
PFILE_OBJECT* MmPerfUnusedSegmentsEnumerate (VOID)
Definition at line 3213 of file sectsup.c.
References ASSERT, CONTAINING_RECORD, ExAllocatePoolWithTag, ExFreePool(), _CONTROL_AREA::FilePointer, _LIST_ENTRY::Flink, KeGetCurrentIrql(), LOCK_PFN, MmUnusedSegmentCount, MmUnusedSegmentList, NonPagedPool, NULL, ObReferenceObject, PASSIVE_LEVEL, and UNLOCK_PFN.
Referenced by PerfInfoFileNameRunDown().
Variable Documentation
POBJECT_TYPE IoFileObjectType
Definition at line 243 of file iodata.c.
MMPAGE_FILE_EXPANSION MiPageFileContract
Definition at line 1777 of file modwrite.c.
Referenced by MiContractPagingFiles().
const GENERIC_MAPPING MiSectionMapping
Initial value:
= {
    STANDARD_RIGHTS_READ |
        SECTION_QUERY | SECTION_MAP_READ,
    STANDARD_RIGHTS_WRITE |
        SECTION_MAP_WRITE,
    STANDARD_RIGHTS_EXECUTE |
        SECTION_MAP_EXECUTE,
    SECTION_ALL_ACCESS
}
Definition at line 68 of file sectsup.c.
Referenced by MiSectionInitialization().
ULONG MiSubsectionActions
Definition at line 46 of file sectsup.c.
Referenced by MiRemoveUnusedSegments().
ULONG MiSubsectionsProcessed
Definition at line 45 of file sectsup.c.
Referenced by MiRemoveUnusedSegments().
const ULONG MMCONTROL
Definition at line 22 of file creasect.c.
Referenced by MiCreateImageFileMap(), MiCreatePagingFileMap(), MiSectionInitialization(), and MmCreateSection().
SIZE_T MmSharedCommit = 0
Definition at line 48 of file sectsup.c.
Referenced by MiCreateImageFileMap(), MiCreatePagingFileMap(), MiMapViewOfDataSection(), MiSegmentDelete(), MmCommitSessionMappedView(), and NtAllocateVirtualMemory().
ULONG MmUnusedSegmentForceFree
Definition at line 43 of file sectsup.c.
Referenced by MiRemoveUnusedSegments(), MiShutdownSystem(), and MiTrimSegmentCache().