Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/mutntobj.c File Reference
mutntobj.c File Reference
#include "ki.h"
Macros
#define ASSERT_MUTANT(E)
Functions
VOID KeInitializeMutant (__out PRKMUTANT Mutant, __in BOOLEAN InitialOwner)
VOID KeInitializeMutex (__out PRKMUTANT Mutant, __in ULONG Level)
LONG KeReadStateMutant (__in PRKMUTANT Mutant)
LONG KeReleaseMutant (__inout PRKMUTANT Mutant, __in KPRIORITY Increment, __in BOOLEAN Abandoned, __in BOOLEAN Wait)
LONG KeReleaseMutex (__inout PRKMUTANT Mutex, __in BOOLEAN Wait)
Macro Definition Documentation
#define ASSERT_MUTANT (E)
Value:
{                    \
    ASSERT((E)->Header.Type == MutantObject); \
}
Definition at line 29 of file mutntobj.c.
Referenced by KeReadStateMutant(), KeReleaseMutant(), and KeReleaseMutex().
Function Documentation
VOID KeInitializeMutant (__out PRKMUTANT Mutant, __in BOOLEAN InitialOwner)
Definition at line 34 of file mutntobj.c.
References _LIST_ENTRY::Blink, FALSE, _KTHREAD::Header, InitializeListHead(), InsertHeadList(), KeGetCurrentThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), _KTHREAD::MutantListHead, MutantObject, NULL, TRUE, and _DISPATCHER_HEADER::Type.
Referenced by MmInitSystem(), and NtCreateMutant().
VOID KeInitializeMutex (__out PRKMUTANT Mutant, __in ULONG Level)
Definition at line 93 of file mutntobj.c.
References FALSE, InitializeListHead(), MutantObject, NULL, and UNREFERENCED_PARAMETER.
Referenced by ExpProfileInitialization(), PspLdtInitialize(), RawInitializeVcb(), and WmipDriverEntry().
LONG KeReadStateMutant (__in PRKMUTANT Mutant)
Definition at line 140 of file mutntobj.c.
References ASSERT_MUTANT.
Referenced by NtQueryMutant(), and RawCheckForDismount().
LONG KeReleaseMutant (__inout PRKMUTANT Mutant, __in KPRIORITY Increment, __in BOOLEAN Abandoned, __in BOOLEAN Wait)
Definition at line 172 of file mutntobj.c.
References ASSERT, ASSERT_MUTANT, DISPATCH_LEVEL, ExRaiseStatus(), FALSE, IsListEmpty, KeGetCurrentIrql(), KeGetCurrentThread(), KeLeaveCriticalRegionThread(), KiLockDispatcherDatabase, KiUnlockDispatcherDatabase(), KiWaitTest(), NULL, RemoveEntryList(), STATUS_ABANDONED, STATUS_MUTANT_NOT_OWNED, TRUE, _KTHREAD::WaitIrql, and _KTHREAD::WaitNext.
Referenced by ExpDeleteMutant(), KeReleaseMutex(), MiEnablePagingTheExecutive(), MiFindInitializationCode(), MiShutdownSystem(), MmLoadSystemImage(), MmUnloadSystemImage(), NtReleaseMutant(), and NtSignalAndWaitForSingleObject().
LONG KeReleaseMutex (__inout PRKMUTANT Mutex, __in BOOLEAN Wait)
Definition at line 310 of file mutntobj.c.
References ASSERT_MUTANT, FALSE, and KeReleaseMutant().
Referenced by NtStartProfile(), NtStopProfile(), PspQueryDescriptorThread(), PspQueryLdtInformation(), PspSetLdtInformation(), PspSetLdtSize(), PsSetLdtEntries(), PsSetProcessLdtInfo(), RawCheckForDismount(), RawCleanup(), RawClose(), RawCreate(), RawUserFsCtrl(), RawVerifyVolume(), WmipLeaveCritSection(), and WmipLeaveTraceCritSection().