Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/rtlassig.c File Reference
rtlassig.c File Reference
#include "ntrtlp.h"
#include "seopaque.h"
#include "sertlp.h"
Macros
#define ULONG_PTR_SDEND(_Adr) ((ULONG_PTR)(_Adr) + (ULONG_PTR)(_Adr##Size))
#define ULONG_ROUND_UP(x, y) ((ULONG)(x) + ((y)-1) & ~((y)-1))
Functions
NTSTATUS RtlAbsoluteToSelfRelativeSD (__in PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __out_bcount(*BufferLength) PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
NTSTATUS RtlMakeSelfRelativeSD (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __out_bcount(*BufferLength) PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
VOID RtlpQuerySecurityDescriptor (__in PISECURITY_DESCRIPTOR SecurityDescriptor, __deref_out PSID *Owner, __out PULONG OwnerSize, __deref_out PSID *PrimaryGroup, __out PULONG PrimaryGroupSize, __deref_out PACL *Dacl, __out PULONG DaclSize, __deref_out PACL *Sacl, __out PULONG SaclSize)
NTSTATUS RtlSelfRelativeToAbsoluteSD (__in PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __out_bcount_part_opt(*AbsoluteSecurityDescriptorSize,*AbsoluteSecurityDescriptorSize) PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __inout PULONG AbsoluteSecurityDescriptorSize, __out_bcount_part_opt(*DaclSize,*DaclSize) PACL Dacl, __inout PULONG DaclSize, __out_bcount_part_opt(*SaclSize,*SaclSize) PACL Sacl, __inout PULONG SaclSize, __out_bcount_part_opt(*OwnerSize,*OwnerSize) PSID Owner, __inout PULONG OwnerSize, __out_bcount_part_opt(*PrimaryGroupSize,*PrimaryGroupSize) PSID PrimaryGroup, __inout PULONG PrimaryGroupSize)
NTSTATUS RtlSelfRelativeToAbsoluteSD2 (__inout_bcount(*pBufferSize) PSECURITY_DESCRIPTOR pSelfRelativeSecurityDescriptor, __inout PULONG pBufferSize)
Macro Definition Documentation
#define ULONG_PTR_SDEND (_Adr) ((ULONG_PTR)(_Adr) + (ULONG_PTR)(_Adr##Size))
Referenced by RtlSelfRelativeToAbsoluteSD2().
#define ULONG_ROUND_UP (x, y) ((ULONG)(x) + ((y)-1) & ~((y)-1))
Referenced by RtlSelfRelativeToAbsoluteSD2().
Function Documentation
NTSTATUS RtlAbsoluteToSelfRelativeSD (__in PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __out_bcount *BufferLength PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
Definition at line 320 of file rtlassig.c.
References RTL_PAGED_CODE, RtlMakeSelfRelativeSD(), RtlpAreControlBitsSet, SE_SELF_RELATIVE, and STATUS_BAD_DESCRIPTOR_FORMAT.
NTSTATUS RtlMakeSelfRelativeSD (__in PSECURITY_DESCRIPTOR SecurityDescriptor, __out_bcount *BufferLength PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __inout PULONG BufferLength)
Definition at line 193 of file rtlassig.c.
References _SECURITY_DESCRIPTOR_RELATIVE::Dacl, FIELD_OFFSET, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR_RELATIVE::Owner, RTL_PAGED_CODE, RtlCopyMemory, RtlPointerToOffset, RtlpQuerySecurityDescriptor(), RtlpSetControlBits, RtlZeroMemory, _SECURITY_DESCRIPTOR_RELATIVE::Sacl, SE_SELF_RELATIVE, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
Referenced by RtlAbsoluteToSelfRelativeSD(), and RtlpSysVolCheckOwnerAndSecurity().
VOID RtlpQuerySecurityDescriptor (__in PISECURITY_DESCRIPTOR SecurityDescriptor, __deref_out PSID * Owner, __out PULONG OwnerSize, __deref_out PSID * PrimaryGroup, __out PULONG PrimaryGroupSize, __deref_out PACL * Dacl, __out PULONG DaclSize, __deref_out PACL * Sacl, __out PULONG SaclSize)
Definition at line 385 of file rtlassig.c.
References LongAlignSize, NULL, RTL_PAGED_CODE, RtlpDaclAddrSecurityDescriptor, RtlpGroupAddrSecurityDescriptor, RtlpOwnerAddrSecurityDescriptor, RtlpSaclAddrSecurityDescriptor, and SeLengthSid.
Referenced by RtlMakeSelfRelativeSD(), RtlSelfRelativeToAbsoluteSD(), and RtlSelfRelativeToAbsoluteSD2().
NTSTATUS RtlSelfRelativeToAbsoluteSD (__in PSECURITY_DESCRIPTOR SelfRelativeSecurityDescriptor, __out_bcount_part_opt *,*AbsoluteSecurityDescriptorSize PSECURITY_DESCRIPTOR AbsoluteSecurityDescriptor, __inout PULONG AbsoluteSecurityDescriptorSize, __out_bcount_part_opt *,*DaclSize PACL Dacl, __inout PULONG DaclSize, __out_bcount_part_opt *,*SaclSize PACL Sacl, __inout PULONG SaclSize, __out_bcount_part_opt *,*OwnerSize PSID Owner, __inout PULONG OwnerSize, __out_bcount_part_opt *,*PrimaryGroupSize PSID PrimaryGroup, __inout PULONG PrimaryGroupSize)
Definition at line 32 of file rtlassig.c.
References _ACL::AclSize, _SECURITY_DESCRIPTOR::Dacl, _SECURITY_DESCRIPTOR::Group, NULL, _SECURITY_DESCRIPTOR::Owner, RTL_PAGED_CODE, RtlMoveMemory, RtlpAreControlBitsSet, RtlpClearControlBits, RtlpQuerySecurityDescriptor(), _SECURITY_DESCRIPTOR::Sacl, SE_SELF_RELATIVE, SeLengthSid, STATUS_BAD_DESCRIPTOR_FORMAT, STATUS_BUFFER_TOO_SMALL, and STATUS_SUCCESS.
NTSTATUS RtlSelfRelativeToAbsoluteSD2 (__inout_bcount *pBufferSize PSECURITY_DESCRIPTOR pSelfRelativeSecurityDescriptor, __inout PULONG pBufferSize)
Definition at line 469 of file rtlassig.c.
References ASSERT, C_ASSERT, _SECURITY_DESCRIPTOR_RELATIVE::Control, _SECURITY_DESCRIPTOR::Control, _SECURITY_DESCRIPTOR_RELATIVE::Dacl, _SECURITY_DESCRIPTOR::Dacl, FIELD_OFFSET, _SECURITY_DESCRIPTOR_RELATIVE::Group, _SECURITY_DESCRIPTOR::Group, _SECURITY_DESCRIPTOR_RELATIVE::Owner, _SECURITY_DESCRIPTOR::Owner, RTL_PAGED_CODE, RtlMoveMemory, RtlpAreControlBitsSet, RtlpClearControlBits, RtlpQuerySecurityDescriptor(), _SECURITY_DESCRIPTOR_RELATIVE::Sacl, _SECURITY_DESCRIPTOR::Sacl, SE_SELF_RELATIVE, STATUS_BAD_DESCRIPTOR_FORMAT, STATUS_BUFFER_TOO_SMALL, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_SUCCESS, ULONG_PTR_SDEND, and ULONG_ROUND_UP.
Referenced by RtlpSysVolCheckOwnerAndSecurity().