Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivefree.c File Reference
hivefree.c File Reference
#include "cmp.h"
Macros
#define LogHiveFree(_hive_)
Functions
VOID HvFreeHive (PHHIVE Hive)
VOID HvFreeHivePartial (PHHIVE Hive, HCELL_INDEX Start, HSTORAGE_TYPE Type)
Macro Definition Documentation
#define LogHiveFree (_hive_)
Definition at line 26 of file hivefree.c.
Referenced by HvFreeHive().
Function Documentation
VOID HvFreeHive (PHHIVE Hive)
Definition at line 34 of file hivefree.c.
References ASSERT, _HHIVE::BaseBlock, _HHIVE::BaseBlockAlloc, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, _RTL_BITMAP::Buffer, CmKdPrintEx, CML_BIN_MAP, CmpFree(), CmpReleaseGlobalQuota(), _HHIVE::DirtyAlloc, _HHIVE::DirtyVector, DPFLTR_CONFIG_ID, FALSE, _HBASE_BLOCK::FileName, _FREE_HBIN::Flags, _HHIVE::Flat, _HHIVE::Free, FREE_HBIN_DISCARDABLE, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HTABLE_SLOTS, HvpFreeHiveFreeDisplay(), HvpFreeMap(), HvpGetBinMemAlloc(), HvpGetCellMap(), _HHIVE::_DUAL::Length, LogHiveFree, _HHIVE::_DUAL::Map, NULL, _HHIVE::ReadOnly, _FREE_HBIN::Size, Stable, _HHIVE::Storage, VALIDATE_CELL_MAP, and Volatile.
Referenced by CmLoadKey(), CmpDestroyTemporaryHive(), CmpFreeAllMemory(), CmpInitializeHive(), and CmUnloadKey().
VOID HvFreeHivePartial (PHHIVE Hive, HCELL_INDEX Start, HSTORAGE_TYPE Type)
Definition at line 167 of file hivefree.c.
References ASSERT, Bin, _HMAP_ENTRY::BinAddress, _HMAP_ENTRY::BlockAddress, CmpFree(), CmpReleaseGlobalQuota(), CmpUpdateSystemHiveHysteresis(), _HHIVE::DirtyCount, _HHIVE::DirtyVector, FALSE, _FREE_HBIN::Flags, _HHIVE::Flat, FREE_HBIN_DISCARDABLE, HBIN_BASE, HBLOCK_SIZE, HCELL_TYPE_MASK, HMAP_DISCARDABLE, HMAP_INPAGEDPOOL, HSECTOR_SIZE, HTABLE_SLOTS, HvpAdjustHiveFreeDisplay(), HvpFreeMap(), HvpGetBinMemAlloc(), HvpGetCellMap(), _HHIVE::_DUAL::Length, _FREE_HBIN::ListEntry, _HHIVE::_DUAL::Map, _HHIVE::ReadOnly, RemoveEntryList(), RtlClearBits(), RtlNumberOfSetBits(), _FREE_HBIN::Size, _RTL_BITMAP::SizeOfBitMap, Stable, _HHIVE::Storage, and VALIDATE_CELL_MAP.
Referenced by HvpTruncateBins(), and HvRefreshHive().