Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmapi2.c File Reference
cmapi2.c File Reference
#include "cmp.h"
Functions
NTSTATUS CmDeleteKey (IN PCM_KEY_BODY KeyBody)
Function Documentation
NTSTATUS CmDeleteKey (IN PCM_KEY_BODY KeyBody)
Definition at line 29 of file cmapi2.c.
References ASSERT, ASSERT_CELL_DIRTY, Cell, CmKdPrintEx, CML_CM, CmpCleanUpSubKeyInfo(), CmpFlushNotifiesOnKeyBodyList(), CmpFreeKeyByCell(), CmpLockHiveFlusherShared, CmpLockRegistry(), CmpLockTwoHashEntriesExclusive(), CmpMarkAllBinsReadOnly, CmpRemoveKeyControlBlock(), CmpReportNotify(), CmpUnlockHiveFlusher, CmpUnlockRegistry(), CmpUnlockTwoHashEntries(), _CM_KEY_CONTROL_BLOCK::ConvKey, _CM_KEY_CONTROL_BLOCK::Delete, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _CM_KEY_CONTROL_BLOCK::Flags, HCELL_NIL, Hive, HvGetCell, HvReleaseCell, _CM_KEY_CONTROL_BLOCK::KcbMaxNameLen, KeQuerySystemTime(), KEY_NO_DELETE, _CM_KEY_CONTROL_BLOCK::KeyCell, _CM_KEY_CONTROL_BLOCK::KeyHive, _CM_KEY_NODE::LastWriteTime, _CM_KEY_NODE::MaxNameLen, NT_SUCCESS, NULL, _CM_KEY_NODE::Parent, _CM_KEY_CONTROL_BLOCK::ParentKcb, PERFINFO_REG_DELETE_KEY, REG_NOTIFY_CHANGE_NAME, Stable, STATUS_CANNOT_DELETE, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by NtDeleteKey().