Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/i386.h File Reference
i386.h File Reference
Data Structures
struct _DESCRIPTOR
struct _HARDWARE_PTE_X86
struct _HARDWARE_PTE_X86PAE
struct _KCALLOUT_FRAME
struct _KDPC_DATA
struct _KFLOATING_SAVE
struct _KGDTENTRY
struct _KIDTENTRY
struct _KiIoAccessMap
struct _KNONVOLATILE_CONTEXT_POINTERS
struct _KPCR
struct _KPRCB
struct _KPROCESSOR_STATE
struct _KSPECIAL_REGISTERS
struct _KSWITCHFRAME
struct _KTRAP_FRAME
struct _KTSS
struct _LDTINFORMATION
struct _PROCESS_IO_PORT_HANDLER_INFORMATION
struct _VDM_IO_HANDLER
struct _VDM_IO_HANDLER_FUNCTIONS
Macros
#define _i386_
#define _PCR fs:[0]
#define ALLOC_DATA_PRAGMA 1
#define ALLOC_PRAGMA 1
#define ALTERNATE_BASE (0xe1000000 - 16 * 1024 * 1024)
#define APC_LEVEL 1
#define CLOCK1_LEVEL 28
#define CLOCK2_LEVEL 28
#define CR0_AM 0x00040000
#define CR0_CD 0x40000000
#define CR0_EM 0x00000004
#define CR0_ET 0x00000010
#define CR0_MP 0x00000002
#define CR0_NE 0x00000020
#define CR0_NW 0x20000000
#define CR0_PE 0x00000001
#define CR0_PG 0x80000000
#define CR0_TS 0x00000008
#define CR0_WP 0x00010000
#define CR4_DE 0x00000008
#define CR4_FXSR 0x00000200
#define CR4_MCE 0x00000040
#define CR4_PAE 0x00000020
#define CR4_PGE 0x00000080
#define CR4_PSE 0x00000010
#define CR4_PVI 0x00000002
#define CR4_TSD 0x00000004
#define CR4_VME 0x00000001
#define CR4_XMMEXCPT 0x00000400
#define DEFAULT_PROFILE_INTERVAL 39063
#define DF_TSS_DESC_OFFSET 0x50
#define DISPATCH_LENGTH NORMAL_DISPATCH_LENGTH
#define DISPATCH_LEVEL 2
#define DPL_SYSTEM 0
#define DPL_USER 3
#define DR6_LEGAL 0x0000e00f
#define DR7_ACTIVE 0x00000055
#define DR7_LEGAL 0xffff0155
#define DR7_MASK_SHIFT 16
#define DR7_OVERRIDE_MASK ((0x0FUL) << DR7_MASK_SHIFT)
#define DR7_OVERRIDE_V 0x04
#define DR7_RESERVED_MASK 0x0000DC00
#define DR_MASK(Bit) (((UCHAR)(1UL << (Bit))))
#define DR_REG_MASK (DR_MASK(0) | DR_MASK(1) | DR_MASK(2) | DR_MASK(3) | DR_MASK(6))
#define DR_VALID_MASK (DR_REG_MASK | DR_MASK (7) | DR_MASK (DR7_OVERRIDE_V))
#define EFLAG_SELECT (EFLAG_SIGN | EFLAG_ZERO)
#define EFLAG_SIGN 0x8000
#define EFLAG_ZERO 0x4000
#define EFLAGS_AF_MASK 0x00000010L
#define EFLAGS_ALIGN_CHECK 0x00040000L
#define EFLAGS_CF_MASK 0x00000001L
#define EFLAGS_DF_MASK 0x00000400L
#define EFLAGS_ID_MASK 0x00200000L
#define EFLAGS_INTERRUPT_MASK 0x00000200L
#define EFLAGS_IOPL_MASK 0x00003000L
#define EFLAGS_NT 0x00004000L
#define EFLAGS_OF_MASK 0x00000800L
#define EFLAGS_PF_MASK 0x00000004L
#define EFLAGS_RF 0x00010000L
#define EFLAGS_SF_MASK 0x00000080L
#define EFLAGS_TF 0x00000100L
#define EFLAGS_USER_SANITIZE 0x003f4dd7L
#define EFLAGS_V86_MASK 0x00020000L
#define EFLAGS_VIF 0x00080000L
#define EFLAGS_VIP 0x00100000L
#define EFLAGS_ZF_MASK 0x00000040L
#define ExAcquireFastLock(Lock, OldIrql) ExAcquireSpinLock(Lock, OldIrql)
#define ExAcquireSpinLock(Lock, OldIrql) KeAcquireSpinLock((Lock), (OldIrql))
#define ExAcquireSpinLockAtDpcLevel(Lock) KeAcquireSpinLockAtDpcLevel(Lock)
#define ExInterlockedAddUlong ExfInterlockedAddUlong
#define ExInterlockedDecrementLong(Addend, Lock) Exfi386InterlockedDecrementLong(Addend)
#define ExInterlockedExchangeUlong(Target, Value, Lock) Exfi386InterlockedExchangeUlong(Target,Value)
#define ExInterlockedIncrementLong(Addend, Lock) Exfi386InterlockedIncrementLong(Addend)
#define ExInterlockedInsertHeadList ExfInterlockedInsertHeadList
#define ExInterlockedInsertTailList ExfInterlockedInsertTailList
#define ExInterlockedPopEntryList ExfInterlockedPopEntryList
#define ExInterlockedPushEntryList ExfInterlockedPushEntryList
#define ExInterlockedRemoveHeadList ExfInterlockedRemoveHeadList
#define ExRaiseException RtlRaiseException
#define ExRaiseStatus RtlRaiseStatus
#define ExReleaseFastLock(Lock, OldIrql) ExReleaseSpinLock(Lock, OldIrql)
#define ExReleaseSpinLock(Lock, OldIrql) KeReleaseSpinLock((Lock), (OldIrql))
#define ExReleaseSpinLockFromDpcLevel(Lock) KeReleaseSpinLockFromDpcLevel(Lock)
#define FLUSH_MULTIPLE_MAXIMUM 32
#define FRAME_EDITED 0xfff8
#define GRAN_BYTE 0
#define GRAN_PAGE 1
#define GUARD_PAGE_SIZE PAGE_SIZE
#define HIGH_LEVEL 31
#define HIGHWORD(l) ((USHORT)(((ULONG)(l)>>16) & 0xffff))
#define I386_80387_NP_VECTOR 0x07
#define IDT_DFH_VECTOR 8
#define IDT_NMI_VECTOR 2
#define IMAGE_FILE_MACHINE_NATIVE 0x014c
#define INITIAL_STALL_COUNT 100
#define INITIALIZE_DIRECTORY_TABLE_BASE(dirbase, pfn) *((PULONG)(dirbase)) = ((pfn) << PAGE_SHIFT)
#define INT_DIRECTION_MAP_SIZE 32
#define InterlockedCompareExchange64(Destination, ExChange, Comperand) ExfInterlockedCompareExchange64(Destination, &(ExChange), &(Comperand))
#define InterlockedCompareExchangeAcquire InterlockedCompareExchange
#define InterlockedCompareExchangeAcquire64 InterlockedCompareExchange64
#define InterlockedCompareExchangePointer(Destination, ExChange, Comperand) (PVOID)InterlockedCompareExchange((PLONG)Destination, (LONG)ExChange, (LONG)Comperand)
#define InterlockedCompareExchangePointerAcquire InterlockedCompareExchangePointer
#define InterlockedCompareExchangePointerRelease InterlockedCompareExchangePointer
#define InterlockedCompareExchangeRelease InterlockedCompareExchange
#define InterlockedCompareExchangeRelease64 InterlockedCompareExchange64
#define InterlockedDecrement(Addend) (InterlockedExchangeAdd (Addend, -1)-1)
#define InterlockedDecrementAcquire InterlockedDecrement
#define InterlockedDecrementRelease InterlockedDecrement
#define InterlockedDecrementSizeT(a) InterlockedDecrement((LONG *)a)
#define InterlockedExchangeAcquire64 InterlockedExchange64
#define InterlockedExchangeAddSizeT(a, b) InterlockedExchangeAdd((LONG *)a, b)
#define InterlockedExchangePointer(Target, Value) (PVOID)InterlockedExchange((PLONG)Target, (LONG)Value)
#define InterlockedIncrement(Addend) (InterlockedExchangeAdd (Addend, 1)+1)
#define InterlockedIncrementAcquire InterlockedIncrement
#define InterlockedIncrementRelease InterlockedIncrement
#define InterlockedIncrementSizeT(a) InterlockedIncrement((LONG *)a)
#define IO_ACCESS_MAP_NONE 0
#define IOPM_COUNT 1
#define IOPM_SIZE 8192
#define IPI_LEVEL 29
#define IsNEC_98 (SharedUserData->AlternativeArchitecture == NEC98x86)
#define IsNotNEC_98 (SharedUserData->AlternativeArchitecture != NEC98x86)
#define Isx86FeaturePresent(_f_) ((KiBootFeatureBits & (_f_)) != 0)
#define KeFillEntryTb(Virtual) KiFlushSingleTb (Virtual);
#define KeFlushIoBuffers(Mdl, ReadOperation, DmaOperation)
#define KeGetDcacheFillSize() 1L
#define KeIsIdleHaltSet(Prcb, Number) ((Prcb)->Sleeping != 0)
#define KeMemoryBarrierWithoutFence() _ReadWriteBarrier()
#define KeSweepCurrentDcache()
#define KeSweepCurrentIcache()
#define KeSweepDcache(AllProcessors)
#define KeSweepIcache(AllProcessors)
#define KeSweepIcacheRange(AllProcessors, BaseAddress, Length)
#define KeYieldProcessor() __asm { rep nop }
#define KF_3DNOW 0x00004000
#define KF_AMDK6MTRR 0x00008000
#define KF_CMOV 0x00000008
#define KF_CMPXCHG8B 0x00000080
#define KF_CR4 0x00000004
#define KF_DTS 0x00020000
#define KF_FAST_SYSCALL 0x00001000
#define KF_FXSR 0x00000800
#define KF_GLOBAL_32BIT_EXECUTE 0x40000000
#define KF_GLOBAL_32BIT_NOEXECUTE 0x80000000
#define KF_GLOBAL_PAGE 0x00000010
#define KF_LARGE_PAGE 0x00000020
#define KF_MMX 0x00000100
#define KF_MTRR 0x00000040
#define KF_NOEXECUTE 0x20000000
#define KF_PAT 0x00000400
#define KF_RDTSC 0x00000002
#define KF_V86_VIS 0x00000001
#define KF_WORKING_PTE 0x00000200
#define KF_XMMI 0x00002000
#define KF_XMMI64 0x00010000
#define KI_BEGIN_KERNEL_RESERVED 0xffdf0000
#define KI_USER_SHARED_DATA 0xffdf0000
#define KiComputeIopmOffset(MapNumber)
#define KiIsThreadNumericStateSaved(a) (a->NpxState != NPX_STATE_LOADED)
#define KIP0PCRADDRESS 0xffdff000
#define KiPcr() KeGetPcr()
#define KiQueryInterruptTime(CurrentTime)
#define KiQueryTickCount(CurrentCount)
#define KiRequestSoftwareInterrupt(RequestIrql) HalRequestSoftwareInterrupt(RequestIrql)
#define KiReturnHandlerAddressFromIDT(Vector) MAKEULONG(KiPcr()->IDT[HalVectorToIDTEntry(Vector)].ExtendedOffset, KiPcr()->IDT[HalVectorToIDTEntry(Vector)].Offset)
#define KiRundownThread(a)
#define KiSetHandlerAddressToIDT(Vector, HandlerAddress)
#define KiSynchIrql SYNCH_LEVEL
#define KSEG0_BASE 0x80000000
#define KTRAP_FRAME_ALIGN (sizeof(ULONG))
#define KTRAP_FRAME_LENGTH (sizeof(KTRAP_FRAME))
#define KTRAP_FRAME_ROUND (KTRAP_FRAME_ALIGN-1)
#define LOW_LEVEL 0
#define LOWWORD(l) ((USHORT)((ULONG)l & 0x0000ffff))
#define MACHINE_TYPE_EISA 1
#define MACHINE_TYPE_ISA 0
#define MACHINE_TYPE_MCA 2
#define MAKEULONG(x, y)
#define MINIMUM_PROFILE_INTERVAL 1221
#define MM_HIGHEST_USER_ADDRESS MmHighestUserAddress
#define MM_LOWEST_SYSTEM_ADDRESS (PVOID)0xC0800000
#define MM_LOWEST_USER_ADDRESS (PVOID)0x10000
#define MM_SYSTEM_RANGE_START MmSystemRangeStart
#define MM_USER_PROBE_ADDRESS MmUserProbeAddress
#define MmGetProcedureAddress(Address) (Address)
#define MmLockPagableCodeSection(Address) MmLockPageableDataSection(Address)
#define MmLockPagableDataSection(Address) MmLockPageableDataSection(Address)
#define MmLockPageableCodeSection(Address) MmLockPageableDataSection(Address)
#define MODE_MASK 1
#define NMI_TSS_DESC_OFFSET 0x58
#define NORMAL_DISPATCH_LENGTH 106
#define NPX_STATE_LOADED 0
#define NPX_STATE_NOT_LOADED (CR0_TS | CR0_MP)
#define PAGE_SHIFT 12L
#define PAGE_SIZE 0x1000
#define PASSIVE_LEVEL 0
#define PCR_MAJOR_VERSION 1
#define PCR_MINOR_VERSION 1
#define PDE_BASE PDE_BASE_X86
#define PDE_BASE_X86 0xc0300000
#define PDE_BASE_X86PAE 0xc0600000
#define PDE_TOP PDE_TOP_X86
#define PDE_TOP_X86 0xC0300FFF
#define PDE_TOP_X86PAE 0xC0603FFF
#define PDI_SHIFT PDI_SHIFT_X86
#define PDI_SHIFT PDI_SHIFT_X86
#define PDI_SHIFT_X86 22
#define PDI_SHIFT_X86 22
#define PDI_SHIFT_X86PAE 21
#define PDI_SHIFT_X86PAE 21
#define PIOPM_SIZE 8196
#define POWER_LEVEL 30
#define PRCB_BUILD_DEBUG 0x0001
#define PRCB_BUILD_UNIPROCESSOR 0x0002
#define PRCB_MAJOR_VERSION 1
#define PRCB_MINOR_VERSION 1
#define PROFILE_LEVEL 27
#define PTE_BASE 0xc0000000
#define PTE_TOP PTE_TOP_X86
#define PTE_TOP_X86 0xC03FFFFF
#define PTE_TOP_X86PAE 0xC07FFFFF
#define PTI_SHIFT 12
#define PTI_SHIFT 12
#define RESULT_NEGATIVE ((EFLAG_SIGN & ~EFLAG_ZERO) & EFLAG_SELECT)
#define RESULT_POSITIVE ((~EFLAG_SIGN & ~EFLAG_ZERO) & EFLAG_SELECT)
#define RESULT_ZERO ((~EFLAG_SIGN & EFLAG_ZERO) & EFLAG_SELECT)
#define RPL_MASK 3
#define SANITIZE_DR6(Dr6, mode) (((Dr6) & DR6_LEGAL))
#define SANITIZE_DR7(Dr7, mode) (((Dr7) & DR7_LEGAL))
#define SANITIZE_DRADDR(DrReg, mode)
#define SANITIZE_FLAGS(eFlags, mode)
#define SANITIZE_MXCSR(_mxcsr_) ((_mxcsr_) & KiMXCsrMask)
#define SANITIZE_SEG(segCS, mode)
#define SEGMENT_MASK 0xffff
#define SELECTOR_TABLE_INDEX 0x04
#define SetNEC_98 SharedUserData->AlternativeArchitecture = NEC98x86
#define SetNotNEC_98 SharedUserData->AlternativeArchitecture = StandardDesign
#define SharedUserData ((KUSER_SHARED_DATA * const) KI_USER_SHARED_DATA)
#define SYNCH_LEVEL (IPI_LEVEL-2)
#define TYPE_CODE 0x10
#define TYPE_DATA 0x12
#define TYPE_LDT 0x02
#define TYPE_TSS 0x01
Typedefs
typedef HARDWARE_PTE_X86 HARDWARE_PTE
typedef struct _HARDWARE_PTE_X86 HARDWARE_PTE_X86
typedef struct _HARDWARE_PTE_X86PAE HARDWARE_PTE_X86PAE
typedef enum _INTERLOCKED_RESULT INTERLOCKED_RESULT
typedef struct _KCALLOUT_FRAME KCALLOUT_FRAME
typedef struct _DESCRIPTOR KDESCRIPTOR
typedef struct _KDPC_DATA KDPC_DATA
typedef struct _KFLOATING_SAVE KFLOATING_SAVE
typedef struct _KGDTENTRY KGDTENTRY
typedef struct _KIDTENTRY KIDTENTRY
typedef struct _KiIoAccessMap KIIO_ACCESS_MAP
typedef UCHAR KINT_DIRECTION_MAP[INT_DIRECTION_MAP_SIZE]
typedef UCHAR KIO_ACCESS_MAP[IOPM_SIZE]
typedef struct _KNONVOLATILE_CONTEXT_POINTERS KNONVOLATILE_CONTEXT_POINTERS
typedef struct _KPCR KPCR
typedef struct _KPRCB KPRCB
typedef struct _KPROCESSOR_STATE KPROCESSOR_STATE
typedef struct _KSPECIAL_REGISTERS KSPECIAL_REGISTERS
typedef struct _KSWITCHFRAME KSWITCHFRAME
typedef struct _KTRAP_FRAME KTRAP_FRAME
typedef struct _KTSS KTSS
typedef struct _LDTINFORMATION LDTINFORMATION
typedef ULONG PFN_COUNT
typedef ULONG PFN_NUMBER
typedef PHARDWARE_PTE_X86 PHARDWARE_PTE
typedef struct _HARDWARE_PTE_X86 * PHARDWARE_PTE_X86
typedef struct _HARDWARE_PTE_X86PAE * PHARDWARE_PTE_X86PAE
typedef KCALLOUT_FRAME * PKCALLOUT_FRAME
typedef struct _DESCRIPTOR * PKDESCRIPTOR
typedef struct _KDPC_DATA * PKDPC_DATA
typedef KTRAP_FRAME * PKEXCEPTION_FRAME
typedef struct _KFLOATING_SAVE * PKFLOATING_SAVE
typedef struct _KGDTENTRY * PKGDTENTRY
typedef KIDTENTRY * PKIDTENTRY
typedef KIO_ACCESS_MAP * PKIO_ACCESS_MAP
typedef struct _KNONVOLATILE_CONTEXT_POINTERS * PKNONVOLATILE_CONTEXT_POINTERS
typedef struct _KPCR * PKPCR
typedef struct _KPRCB * PKPRCB
typedef struct _KPROCESSOR_STATE * PKPROCESSOR_STATE
typedef struct _KSPECIAL_REGISTERS * PKSPECIAL_REGISTERS
typedef struct _KSWITCHFRAME * PKSWITCHFRAME
typedef KTRAP_FRAME * PKTRAP_FRAME
typedef struct _KTSS * PKTSS
typedef struct _LDTINFORMATION * PLDTINFORMATION
typedef ULONG * PPFN_NUMBER
typedef struct _PROCESS_IO_PORT_HANDLER_INFORMATION * PPROCESS_IO_PORT_HANDLER_INFORMATION
typedef struct _KPRCB PRKPRCB
typedef struct _PROCESS_IO_PORT_HANDLER_INFORMATION PROCESS_IO_PORT_HANDLER_INFORMATION
typedef LONG * PSPFN_NUMBER
typedef struct _VDM_IO_HANDLER * PVDM_IO_HANDLER
typedef struct _VDM_IO_HANDLER_FUNCTIONS * PVDM_IO_HANDLER_FUNCTIONS
typedef LONG SPFN_NUMBER
typedef struct _VDM_IO_HANDLER VDM_IO_HANDLER
typedef struct _VDM_IO_HANDLER_FUNCTIONS VDM_IO_HANDLER_FUNCTIONS
Enumerations
enum _INTERLOCKED_RESULT { ResultNegative = RESULT_NEGATIVE, ResultZero = RESULT_ZERO, ResultPositive = RESULT_POSITIVE }
Functions
void __cdecl _disable (void)
void __cdecl _enable (void)
VOID _ReadWriteBarrier (VOID)
C_ASSERT (((FIELD_OFFSET(KPRCB, LockQueue)+sizeof(KSPIN_LOCK_QUEUE)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, NpxThread)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, CcFastReadNoWait)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PPLookasideList)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PPNPagedLookasideList)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PPPagedLookasideList)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PacketBarrier)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, CurrentPacket)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, DpcData)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, DpcRoutineActive))&(1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, CallDpc)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, WaitListHead)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, ChainedInterruptList)+32)&(64-1))==0)
C_ASSERT (((FIELD_OFFSET(KPRCB, NpxSaveArea)+32)&(16-1))==0)
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.ExceptionList)==FIELD_OFFSET(KPCR, Used_ExceptionList))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.StackBase)==FIELD_OFFSET(KPCR, Used_StackBase))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.StackLimit)==FIELD_OFFSET(KPCR, PerfGlobalGroupMask))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.SubSystemTib)==FIELD_OFFSET(KPCR, TssCopy))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.FiberData)==FIELD_OFFSET(KPCR, ContextSwitches))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.ArbitraryUserPointer)==FIELD_OFFSET(KPCR, SetMemberCopy))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.Self)==FIELD_OFFSET(KPCR, Used_Self))
C_ASSERT ((FIELD_OFFSET(KPCR, PrcbData)&(64-1))==32)
C_ASSERT (sizeof(BOOLEAN)==sizeof(UCHAR))
C_ASSERT ((((ULONG) DR_VALID_MASK)&~((ULONG)((UCHAR) 0xFF)))==0)
C_ASSERT ((DR7_ACTIVE &DR7_OVERRIDE_MASK)==0)
C_ASSERT ((DR7_RESERVED_MASK &DR7_OVERRIDE_MASK)==0)
C_ASSERT ((DR7_OVERRIDE_MASK &DR7_LEGAL)==DR7_OVERRIDE_MASK)
C_ASSERT ((DR7_RESERVED_MASK &DR7_LEGAL)==0)
VOID NTAPI CPUID (ULONG InEax, PULONG OutEax, PULONG OutEbx, PULONG OutEcx, PULONG OutEdx)
NTKERNELAPI INTERLOCKED_RESULT FASTCALL Exfi386InterlockedDecrementLong (IN PLONG Addend)
NTKERNELAPI ULONG FASTCALL Exfi386InterlockedExchangeUlong (IN PULONG Target, IN ULONG Value)
NTKERNELAPI INTERLOCKED_RESULT FASTCALL Exfi386InterlockedIncrementLong (IN PLONG Addend)
NTKERNELAPI LONGLONG FASTCALL ExfInterlockedCompareExchange64 (IN OUT LONGLONG volatile *Destination, IN PLONGLONG ExChange, IN PLONGLONG Comperand)
FORCEINLINE LONG InterlockedAnd (IN OUT LONG volatile *Target, LONG Set)
FORCEINLINE LONG FASTCALL InterlockedCompareExchange (IN OUT LONG volatile *Destination, IN LONG Exchange, IN LONG Comperand)
FORCEINLINE LONG FASTCALL InterlockedExchange (IN OUT LONG volatile *Target, IN LONG Value)
FORCEINLINE LONG FASTCALL InterlockedExchangeAdd (IN OUT LONG volatile *Addend, IN LONG Increment)
FORCEINLINE LONG InterlockedOr (IN OUT LONG volatile *Target, IN LONG Set)
NTSTATUS NTAPI Ke386CallBios (IN ULONG BiosCommand, IN OUT PCONTEXT BiosArguments)
VOID NTAPI Ke386GetGdtEntryThread (struct _KTHREAD *Thread, ULONG Offset, PKGDTENTRY Descriptor)
BOOLEAN NTAPI Ke386IoSetAccessProcess (struct _KPROCESS *Process, ULONG MapNumber)
BOOLEAN NTAPI Ke386QueryIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
VOID NTAPI Ke386SetDescriptorProcess (struct _KPROCESS *Process, ULONG Offset, LDT_ENTRY LdtEntry)
BOOLEAN NTAPI Ke386SetIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
VOID NTAPI Ke386SetIOPL (VOID)
VOID NTAPI Ke386SetLdtProcess (struct _KPROCESS *Process, PLDT_ENTRY Ldt, ULONG Limit)
NTSTATUS NTAPI Ke386SetVdmInterruptHandler (IN struct _KPROCESS *Process, IN ULONG Interrupt, IN USHORT Selector, IN ULONG Offset, IN BOOLEAN Gate32)
BOOLEAN KeDisableInterrupts (VOID)
NTKERNELAPI VOID KeFlushCurrentTb (VOID)
FORCEINLINE ULONG KeGetContextSwitches (PKPRCB Prcb)
NTHALAPI KIRQL NTAPI KeGetCurrentIrql ()
FORCEINLINE ULONG KeGetCurrentNodeShiftedColor (VOID)
FORCEINLINE PKPRCB NTAPI KeGetCurrentPrcb (VOID)
FORCEINLINE ULONG NTAPI KeGetCurrentProcessorNumber (VOID)
FORCEINLINE struct _KTHREAD *NTAPI KeGetCurrentThread (VOID)
FORCEINLINE PKPCR NTAPI KeGetPcr (VOID)
NTSTATUS NTAPI KeI386AbiosCall (IN USHORT LogicalId, IN struct _DRIVER_OBJECT *DriverObject, IN PUCHAR RequestBlock, IN USHORT EntryPoint)
NTSTATUS NTAPI KeI386AllocateGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
USHORT NTAPI KeI386Call16BitCStyleFunction (IN ULONG EntryOffset, IN ULONG EntrySelector, IN PUCHAR Parameters, IN ULONG Size)
VOID NTAPI KeI386Call16BitFunction (IN OUT PCONTEXT Regs)
NTSTATUS NTAPI KeI386FlatToGdtSelector (IN ULONG SelectorBase, IN USHORT Length, IN USHORT Selector)
NTSTATUS NTAPI KeI386GetLid (IN USHORT DeviceId, IN USHORT RelativeLid, IN BOOLEAN SharedLid, IN struct _DRIVER_OBJECT *DeviceObject, OUT PUSHORT LogicalId)
NTSTATUS NTAPI KeI386ReleaseGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
NTSTATUS NTAPI KeI386ReleaseLid (IN USHORT LogicalId, IN struct _DRIVER_OBJECT *DeviceObject)
NTSTATUS NTAPI KeI386SetGdtSelector (ULONG Selector, PKGDTENTRY GdtValue)
VOID NTAPI KeI386VdmInitialize (VOID)
FORCEINLINE ULONG NTAPI KeIsExecutingDpc (VOID)
FORCEINLINE VOID KeMemoryBarrier (VOID)
VOID NTAPI KeOptimizeProcessorControlState (VOID)
VOID NTAPI KeProfileInterrupt (IN KIRQL OldIrql, IN KTRAP_FRAME TrapFrame)
NTKERNELAPI VOID NTAPI KeProfileInterruptWithSource (IN struct _KTRAP_FRAME *TrapFrame, IN KPROFILE_SOURCE ProfileSource)
VOID NTAPI KeQueryTickCount (OUT PLARGE_INTEGER CurrentCount)
NTKERNELAPI NTSTATUS NTAPI KeRestoreFloatingPointState (IN PKFLOATING_SAVE FloatSave)
NTKERNELAPI NTSTATUS NTAPI KeSaveFloatingPointState (OUT PKFLOATING_SAVE FloatSave)
VOID NTAPI KeUpdateRuntime (IN KIRQL OldIrql, IN KTRAP_FRAME TrapFrame)
VOID NTAPI KeUpdateSystemTime (IN KIRQL OldIrql, IN KTRAP_FRAME TrapFrame)
FORCEINLINE VOID NTAPI KeVdmClearApcThreadAddress (IN PKAPC Apc)
BOOLEAN NTAPI KeVdmInsertQueueApc (IN PKAPC Apc, IN struct _KTHREAD *Thread, IN KPROCESSOR_MODE ApcMode, IN PKKERNEL_ROUTINE KernelRoutine, IN PKRUNDOWN_ROUTINE RundownRoutine OPTIONAL, IN PKNORMAL_ROUTINE NormalRoutine OPTIONAL, IN PVOID NormalContext OPTIONAL, IN KPRIORITY Increment)
ULONG Ki386DispatchOpcode (IN PKTRAP_FRAME TrapFrame)
ULONG Ki386DispatchOpcodeV86 (IN PKTRAP_FRAME TrapFrame)
BOOLEAN NTAPI Ki386GetSelectorParameters (IN USHORT Selector, OUT PULONG Flags, OUT PULONG Base, OUT PULONG Limit)
VOID FASTCALL KiAcquireSpinLock (IN PKSPIN_LOCK SpinLock)
VOID NTAPI KiEditIopmDpc (IN struct _KDPC *Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
ULONG NTAPI KiEspFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
VOID NTAPI KiEspToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG Esp)
FORCEINLINE VOID KiFlushProcessTb (VOID)
FORCEINLINE VOID KiFlushSingleTb (IN PVOID Virtual)
VOID FASTCALL KiReleaseSpinLock (IN PKSPIN_LOCK SpinLock)
ULONG NTAPI KiSegSsFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
VOID NTAPI KiSegSsToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG SegSs)
VOID NTAPI KiSetIRR (IN ULONG SWInterruptMask)
VOID NTAPI KiUpdateRunTime (VOID)
VOID NTAPI KiUpdateSystemTime (VOID)
ULONGLONG FASTCALL RDMSR (IN ULONG MsrRegister)
LONGLONG NTAPI RDTSC (VOID)
NTHALAPI VOID NTAPI READ_PORT_BUFFER_UCHAR (PUCHAR Port, PUCHAR Buffer, ULONG Count)
NTHALAPI VOID NTAPI READ_PORT_BUFFER_ULONG (PULONG Port, PULONG Buffer, ULONG Count)
NTHALAPI VOID NTAPI READ_PORT_BUFFER_USHORT (PUSHORT Port, PUSHORT Buffer, ULONG Count)
NTHALAPI UCHAR NTAPI READ_PORT_UCHAR (PUCHAR Port)
NTHALAPI ULONG NTAPI READ_PORT_ULONG (PULONG Port)
NTHALAPI USHORT NTAPI READ_PORT_USHORT (PUSHORT Port)
NTKERNELAPI VOID NTAPI READ_REGISTER_BUFFER_UCHAR (PUCHAR Register, PUCHAR Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI READ_REGISTER_BUFFER_ULONG (PULONG Register, PULONG Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI READ_REGISTER_BUFFER_USHORT (PUSHORT Register, PUSHORT Buffer, ULONG Count)
NTKERNELAPI UCHAR NTAPI READ_REGISTER_UCHAR (PUCHAR Register)
NTKERNELAPI ULONG NTAPI READ_REGISTER_ULONG (PULONG Register)
NTKERNELAPI USHORT NTAPI READ_REGISTER_USHORT (PUSHORT Register)
NTHALAPI VOID NTAPI WRITE_PORT_BUFFER_UCHAR (PUCHAR Port, PUCHAR Buffer, ULONG Count)
NTHALAPI VOID NTAPI WRITE_PORT_BUFFER_ULONG (PULONG Port, PULONG Buffer, ULONG Count)
NTHALAPI VOID NTAPI WRITE_PORT_BUFFER_USHORT (PUSHORT Port, PUSHORT Buffer, ULONG Count)
NTHALAPI VOID NTAPI WRITE_PORT_UCHAR (PUCHAR Port, UCHAR Value)
NTHALAPI VOID NTAPI WRITE_PORT_ULONG (PULONG Port, ULONG Value)
NTHALAPI VOID NTAPI WRITE_PORT_USHORT (PUSHORT Port, USHORT Value)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_BUFFER_UCHAR (PUCHAR Register, PUCHAR Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_BUFFER_ULONG (PULONG Register, PULONG Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_BUFFER_USHORT (PUSHORT Register, PUSHORT Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_UCHAR (PUCHAR Register, UCHAR Value)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_ULONG (PULONG Register, ULONG Value)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_USHORT (PUSHORT Register, USHORT Value)
VOID NTAPI WRMSR (IN ULONG MsrRegister, IN ULONGLONG MsrValue)
Variables
ULONG KeI386CpuStep
ULONG KeI386CpuType
ULONG KeI386EFlagsAndMaskV86
ULONG KeI386EFlagsOrMaskV86
BOOLEAN KeI386FxsrPresent
ULONG KeI386MachineType
BOOLEAN KeI386NpxPresent
ULONG KeI386VirtualIntExtensions
ULONG KiBootFeatureBits
ULONG KiInterruptTemplate [NORMAL_DISPATCH_LENGTH]
PULONG KiInterruptTemplate2ndDispatch
PULONG KiInterruptTemplateDispatch
PULONG KiInterruptTemplateObject
ULONG KiMXCsrMask
NTKERNELAPI PVOID MmHighestUserAddress
NTKERNELAPI PVOID MmSystemRangeStart
NTKERNELAPI ULONG MmUserProbeAddress
Macro Definition Documentation
#define _i386_
Definition at line 24 of file i386.h.
#define _PCR fs:[0]
Definition at line 2632 of file i386.h.
Referenced by KeGetCurrentPrcb(), KeGetCurrentProcessorNumber(), and KeGetPcr().
#define ALLOC_DATA_PRAGMA 1
Definition at line 74 of file i386.h.
#define ALLOC_PRAGMA 1
Definition at line 68 of file i386.h.
#define ALTERNATE_BASE (0xe1000000 - 16 * 1024 * 1024)
Definition at line 1981 of file i386.h.
Referenced by MiInitMachineDependent().
#define APC_LEVEL 1
Definition at line 162 of file i386.h.
Referenced by CmNotifyRunDown(), CmpNotifyChangeKey(), CmpPostApcRunDown(), CmpPostNotify(), CmpReportNotifyHelper(), ExAllocatePoolSanityChecks(), ExFreePoolSanityChecks(), ExpLockHandleTableEntry(), ExUnlockHandleTableEntry(), IoAsynchronousPageWrite(), IoCancelFileOpen(), IoCancelThreadIo(), IopCancelAlertedRequest(), IopCloseFile(), IopDeleteFile(), IopDisassociateThreadIrp(), IopParseDevice(), IopSynchronousServiceTail(), IoRetryIrpCompletions(), KeAcquireGuardedMutex(), KeAcquireGuardedMutexUnsafe(), KeAreAllApcsDisabled(), KeContextFromKframes(), KeContextToKframes(), KeDelayExecutionThread(), KeDetachProcess(), KeEnterGuardedRegionThread(), KeLeaveGuardedRegionThread(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), KeRemoveQueue(), KeSaveFloatingPointState(), KeTryToAcquireGuardedMutex(), KeUnstackDetachProcess(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), Ki386CheckDelayedNpxTrap(), Ki386CheckDivideByZeroTrap(), KiCheckForKernelApcDelivery(), KiContinue(), KiContinueEx(), KiDeliverApc(), KiEspToTrapFrame(), KiExitDispatcher(), KiInitializeContextThread(), KiInitializeKernel(), KiInsertQueueApc(), KiPreprocessInvalidOpcodeFault(), KiQuantumEnd(), KiSendSoftwareInterrupt(), MiAddViewsForSectionWithPfn(), MiAllocateContiguousMemory(), MiAllocatePagesForMdl(), MiCancelWriteOfMappedPfn(), MiCheckCacheAttributes(), MiCleanSection(), MiDeleteSystemPageableVm(), MiDispatchFault(), MiFlushComplete(), MiFlushSectionInternal(), MiFreeContiguousPages(), MiGatherMappedPages(), MiGatherPagefilePages(), MiMappedPageWriter(), MiQueueWorkingSetRequest(), MiRemoveViewsFromSectionWithPfn(), MiSetSystemCodeProtection(), MiTrimAllSystemPageableMemory(), MiTrimPte(), MiUseLargeDriverPage(), MmAccessFault(), MmAttachSession(), MmDetachSession(), MmFreeIndependentPages(), MmFreePagesFromMdl(), MmGatherMemoryForHibernate(), MmGetNextSession(), MmGetPreviousSession(), MmGetSessionById(), MmMapViewInSystemCache(), MmPurgeSection(), MmQuerySystemCacheWorkingSetInformation(), MmQueryWorkingSetInformation(), MmQuitNextSession(), MmSetPageProtection(), MmUnmapViewInSystemCache(), NtCancelIoFile(), NtNotifyChangeMultipleKeys(), NtQueryInformationFile(), NtSetInformationFile(), NtYieldExecution(), Ps386GetVdmIoHandler(), Psp386CreateVdmIoListHead(), Psp386InstallIoHandler(), Psp386RemoveIoHandler(), PspTerminateThreadByPointer(), PspUserThreadStartup(), xxAcquireFastMutex(), xxAcquireFastMutexUnsafe(), xxReleaseFastMutex(), xxReleaseFastMutexUnsafe(), and xxTryToAcquireFastMutex().
#define CLOCK1_LEVEL 28
Definition at line 166 of file i386.h.
#define CLOCK2_LEVEL 28
Definition at line 167 of file i386.h.
#define CR0_AM 0x00040000
Definition at line 119 of file i386.h.
#define CR0_CD 0x40000000
Definition at line 117 of file i386.h.
Referenced by KiLoadMTRR(), and KiLoadPAT().
#define CR0_EM 0x00000004
Definition at line 109 of file i386.h.
Referenced by KeContextToKframes(), KeRestoreFloatingPointState(), KeSaveFloatingPointState(), Ki386CheckDelayedNpxTrap(), KiInitializeContextThread(), and KipWorkAroundCompiler().
#define CR0_ET 0x00000010
Definition at line 107 of file i386.h.
#define CR0_MP 0x00000002
Definition at line 110 of file i386.h.
Referenced by KeContextToKframes(), KeRestoreFloatingPointState(), KeSaveFloatingPointState(), Ki386CheckDelayedNpxTrap(), KiInitializeContextThread(), and KipWorkAroundCompiler().
#define CR0_NE 0x00000020
Definition at line 121 of file i386.h.
#define CR0_NW 0x20000000
Definition at line 118 of file i386.h.
Referenced by KiLoadMTRR(), and KiLoadPAT().
#define CR0_PE 0x00000001
Definition at line 111 of file i386.h.
Referenced by KeContextToKframes().
#define CR0_PG 0x80000000
Definition at line 106 of file i386.h.
#define CR0_TS 0x00000008
Definition at line 108 of file i386.h.
Referenced by KeContextToKframes(), KeRestoreFloatingPointState(), KeSaveFloatingPointState(), Ki386CheckDelayedNpxTrap(), and KipWorkAroundCompiler().
#define CR0_WP 0x00010000
Definition at line 120 of file i386.h.
#define CR4_DE 0x00000008
Definition at line 129 of file i386.h.
Referenced by KiInitializeKernel().
#define CR4_FXSR 0x00000200
Definition at line 134 of file i386.h.
#define CR4_MCE 0x00000040
Definition at line 132 of file i386.h.
#define CR4_PAE 0x00000020
Definition at line 131 of file i386.h.
#define CR4_PGE 0x00000080
Definition at line 133 of file i386.h.
Referenced by KiLoadMTRR(), and KiLoadPAT().
#define CR4_PSE 0x00000010
Definition at line 130 of file i386.h.
Referenced by KiInitializeKernel(), and MiUseLargeDriverPage().
#define CR4_PVI 0x00000002
Definition at line 127 of file i386.h.
#define CR4_TSD 0x00000004
Definition at line 128 of file i386.h.
#define CR4_VME 0x00000001
Definition at line 126 of file i386.h.
#define CR4_XMMEXCPT 0x00000400
Definition at line 135 of file i386.h.
#define DEFAULT_PROFILE_INTERVAL 39063
Definition at line 1824 of file i386.h.
#define DF_TSS_DESC_OFFSET 0x50
Definition at line 885 of file i386.h.
Referenced by KiDummyDoubleFaultHandler().
#define DISPATCH_LENGTH NORMAL_DISPATCH_LENGTH
Definition at line 99 of file i386.h.
#define DISPATCH_LEVEL 2
Definition at line 163 of file i386.h.
Referenced by CcDereferenceFileOffset(), CcGetVirtualAddress(), CcGetVirtualAddressIfMapped(), CcReferenceFileOffset(), ExAcquireSpinLockShared(), ExAllocatePoolSanityChecks(), ExDeletePoolTagTable(), ExFreePoolSanityChecks(), ExfUnblockPushLock(), ExfWakePushLock(), ExNotifyCallback(), ExpGetPoolTagInfoTarget(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExRegisterCallback(), ExReleaseSpinLockExclusive(), ExReleaseSpinLockShared(), ExTryAcquireSpinLockExclusive(), ExUnregisterCallback(), FsRtlCreateSectionForDataScan(), IoGetStackLimits(), IoQueueWorkItem(), IoStartPacket(), Ke386QueryIoAccessMap(), KeAcquireInStackQueuedSpinLock(), KeAcquireQueuedSpinLock(), KeAcquireSpinLockRaiseToDpc(), KeAlertResumeThread(), KeAlertThread(), KeAttachProcess(), KeBoostPriorityThread(), KeCancelTimer(), KeDelayExecutionThread(), KeDeregisterNmiCallback(), KeDetachProcess(), KeFlushQueueApc(), KeFlushQueuedDpcs(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeGenericCallDpc(), KeInsertHeadQueue(), KeInsertQueue(), KeInsertQueueApc(), KeInsertQueueDpc(), KePulseEvent(), KeQueryBasePriorityThread(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeReadyThread(), KeRegisterNmiCallback(), KeReleaseMutant(), KeReleaseSemaphore(), KeRemoveEntryDeviceQueue(), KeRemoveQueue(), KeRemoveQueueApc(), KeResetEvent(), KeResumeThread(), KeRevertToUserAffinityThread(), KeRundownQueue(), KeRundownThread(), KeSaveFloatingPointState(), KeSetAffinityProcess(), KeSetAffinityThread(), KeSetBasePriorityThread(), KeSetEvent(), KeSetEventBoostPriority(), KeSetPhysicalCacheTypeRange(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeSetProcess(), KeSetQuantumProcess(), KeSetSystemAffinityThread(), KeSetSystemTime(), KeSetTimerEx(), KeSignalGateBoostPriority(), KeStackAttachProcess(), KeStartProfile(), KeStopProfile(), KeSuspendThread(), KeTerminateThread(), KeTestAlertThread(), KeThawAllThreads(), KeTryToAcquireQueuedSpinLock(), KeTryToAcquireSpinLock(), KeUnstackDetachProcess(), KeUpdateRunTime(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiAcquireInStackQueuedSpinLockForDpc(), KiAcquireKobjectLock(), KiAcquirePrcbLock(), KiAcquireSpinLockForDpc(), KiAcquireThreadLock(), KiAcquireTimerTableLock(), KiAcquireTwoPrcbLocks(), KiAmdK6MtrrSetMemoryType(), KiCompleteEffectiveRangeChange(), KiCompleteTimer(), KiDeferredReadyThread(), KiExitDispatcher(), KiIdleSchedule(), KiInitializeKernel(), KiIpiSendPacket(), KiIpiSendRequest(), KiLockStepOtherProcessors(), KiOpPatchCode(), KiProcessTimerDpcTable(), KiQuantumEnd(), KiReleaseInStackQueuedSpinLockForDpc(), KiReleaseKobjectLock(), KiReleasePrcbLock(), KiReleaseSpinLockForDpc(), KiReleaseThreadLock(), KiReleaseTimerTableLock(), KiReleaseTwoPrcbLocks(), KiRetireDpcList(), KiTimerExpiration(), KiTryToAcquireThreadLock(), MiAttemptPageFileExtension(), MiAttemptPageFileReduction(), MiDereferenceSegmentThread(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiMapPageInHyperSpaceAtDpc(), MiSnapCopyMemory(), MiUpdateSystemPdes(), MmAdvanceMdl(), MmCopyToCachedPage(), MmMapLockedPagesWithReservedMapping(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmUnmapReservedMapping(), NtCreateSection(), NtYieldExecution(), RtlCaptureStackContext(), RtlDispatchException(), RtlpCaptureStackLimits(), RtlUnwind(), RtlWalkFrameChain(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), WmipReleaseTraceBuffer(), WmipSwitchBuffer(), and WmiTraceEvent().
#define DPL_SYSTEM 0
Definition at line 874 of file i386.h.
Referenced by Ke386SetLdtProcess(), and KeI386FlatToGdtSelector().
#define DPL_USER 3
Definition at line 873 of file i386.h.
#define DR6_LEGAL 0x0000e00f
Definition at line 1545 of file i386.h.
#define DR7_ACTIVE 0x00000055
Definition at line 1569 of file i386.h.
Referenced by KeContextFromKframes(), KxContextToKframes(), PspGetContext(), and PspSetContext().
#define DR7_LEGAL 0xffff0155
Definition at line 1547 of file i386.h.
#define DR7_MASK_SHIFT 16
Definition at line 1563 of file i386.h.
#define DR7_OVERRIDE_MASK ((0x0FUL) << DR7_MASK_SHIFT)
Definition at line 1566 of file i386.h.
Referenced by KiProcessDebugRegister(), KiRecordDr7(), and KiUpdateDr7().
#define DR7_OVERRIDE_V 0x04
Definition at line 1555 of file i386.h.
Referenced by KiProcessDebugRegister(), KiRecordDr7(), and KiUpdateDr7().
#define DR7_RESERVED_MASK 0x0000DC00
Definition at line 1568 of file i386.h.
Referenced by KeContextFromKframes(), KiProcessDebugRegister(), KiRecordDr7(), and KiUpdateDr7().
#define DR_MASK (Bit) (((UCHAR)(1UL << (Bit))))
Definition at line 1557 of file i386.h.
Referenced by KeContextToKframes(), KiProcessDebugRegister(), KiRecordDr7(), and KiUpdateDr7().
#define DR_REG_MASK (DR_MASK(0) | DR_MASK(1) | DR_MASK(2) | DR_MASK(3) | DR_MASK(6))
Definition at line 1560 of file i386.h.
Referenced by KiProcessDebugRegister(), KiRecordDr7(), and KiUpdateDr7().
#define DR_VALID_MASK (DR_REG_MASK | DR_MASK (7) | DR_MASK (DR7_OVERRIDE_V))
Definition at line 1561 of file i386.h.
#define EFLAG_SELECT (EFLAG_SIGN | EFLAG_ZERO)
Definition at line 2018 of file i386.h.
#define EFLAG_SIGN 0x8000
Definition at line 2016 of file i386.h.
#define EFLAG_ZERO 0x4000
Definition at line 2017 of file i386.h.
#define EFLAGS_AF_MASK 0x00000010L
Definition at line 1489 of file i386.h.
#define EFLAGS_ALIGN_CHECK 0x00040000L
Definition at line 1500 of file i386.h.
#define EFLAGS_CF_MASK 0x00000001L
Definition at line 1487 of file i386.h.
#define EFLAGS_DF_MASK 0x00000400L
Definition at line 1494 of file i386.h.
#define EFLAGS_ID_MASK 0x00200000L
Definition at line 1503 of file i386.h.
#define EFLAGS_INTERRUPT_MASK 0x00000200L
Definition at line 1493 of file i386.h.
Referenced by Ke386CallBios(), and MiTrimAllSystemPageableMemory().
#define EFLAGS_IOPL_MASK 0x00003000L
Definition at line 1496 of file i386.h.
Referenced by Ke386SetIOPL(), KeContextToKframes(), and KiInitializeUserApc().
#define EFLAGS_NT 0x00004000L
Definition at line 1497 of file i386.h.
#define EFLAGS_OF_MASK 0x00000800L
Definition at line 1495 of file i386.h.
#define EFLAGS_PF_MASK 0x00000004L
Definition at line 1488 of file i386.h.
#define EFLAGS_RF 0x00010000L
Definition at line 1498 of file i386.h.
#define EFLAGS_SF_MASK 0x00000080L
Definition at line 1491 of file i386.h.
#define EFLAGS_TF 0x00000100L
Definition at line 1492 of file i386.h.
#define EFLAGS_USER_SANITIZE 0x003f4dd7L
Definition at line 1505 of file i386.h.
#define EFLAGS_V86_MASK 0x00020000L
Definition at line 1499 of file i386.h.
Referenced by Ke386CallBios(), KeBugCheck2(), KeContextFromKframes(), KeContextToKframes(), Ki386CheckDelayedNpxTrap(), Ki386CheckDivideByZeroTrap(), KiDispatchException(), KiEspFromTrapFrame(), KiEspToTrapFrame(), KiInitializeUserApc(), KiNextIStreamByte(), KiSegSsFromTrapFrame(), and KiSegSsToTrapFrame().
#define EFLAGS_VIF 0x00080000L
Definition at line 1501 of file i386.h.
#define EFLAGS_VIP 0x00100000L
Definition at line 1502 of file i386.h.
#define EFLAGS_ZF_MASK 0x00000040L
Definition at line 1490 of file i386.h.
#define ExAcquireFastLock (Lock, OldIrql) ExAcquireSpinLock(Lock, OldIrql)
Definition at line 633 of file i386.h.
Referenced by CcCopyWrite(), CcFastCopyWrite(), CcFreeActiveVacb(), CcGetActiveVacb(), CcScheduleReadAhead(), CcSetActiveVacb(), IopCheckHardErrorEmpty(), IopRemoveHardErrorPacket(), IopRemoveTimerFromTimerList(), IoStartTimer(), and IoStopTimer().
#define ExAcquireSpinLock (Lock, OldIrql) KeAcquireSpinLock((Lock), (OldIrql))
Definition at line 593 of file i386.h.
Referenced by CcPostDeferredWrites(), CcScheduleReadAhead(), CcSetActiveVacb(), ExDeleteNPagedLookasideList(), ExDeletePagedLookasideList(), ExGetNextWakeTime(), ExInterlockedExtendZone(), ExpAcquireLockRoutine(), ExpDeleteTimer(), ExpGetLookasideInformation(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpScanGeneralLookasideList(), ExpTimerApcRoutine(), ExRecordCallerInHashTable(), ExTimerRundown(), IopErrorLogGetEntry(), IopErrorLogRequeueEntry(), IopTimerDispatch(), IoRaiseInformationalHardError(), IoWriteErrorLogEntry(), KeI386AllocateGdtSelectors(), KeI386FlatToGdtSelector(), KeI386GetLid(), KeI386ReleaseGdtSelectors(), KeI386ReleaseLid(), MiAttemptPageFileReduction(), MiCheckForControlAreaDeletion(), MiCheckPteRelease(), MiCheckPteReserve(), MiContractPagingFiles(), MiDereferenceIoSpace(), MiDereferenceSegmentThread(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiIsProbeActive(), MiIssuePageExtendRequest(), MiIssuePageExtendRequestNoWait(), MiMapWithLargePages(), MiReferenceIoSpace(), MiReleaseSplitSystemPtes(), MiRemoveIoSpaceMap(), MiRemovePteTracker(), MiRemoveUnusedSegments(), MiUnmapLargePages(), MmIsIoSpaceActive(), NtCancelTimer(), NtSetTimer(), PspDereferenceQuotaBlock(), PspExpandQuota(), PspGivebackQuota(), PspInsertQuotaBlock(), PspQueryWorkingSetWatch(), and PsWatchWorkingSet().
#define ExAcquireSpinLockAtDpcLevel (Lock) KeAcquireSpinLockAtDpcLevel(Lock)
Definition at line 595 of file i386.h.
Referenced by CcFreeActiveVacb(), CcPerformReadAhead(), CcSetActiveVacb(), ExpTimerApcRoutine(), ExpTimerDpcRoutine(), ExTimerRundown(), MiProcessLoaderEntry(), MiSegmentDelete(), NtCancelTimer(), NtSetTimer(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
#define ExInterlockedAddUlong ExfInterlockedAddUlong
Definition at line 2046 of file i386.h.
#define ExInterlockedDecrementLong (Addend, Lock) Exfi386InterlockedDecrementLong(Addend)
Definition at line 2038 of file i386.h.
#define ExInterlockedExchangeUlong (Target, Value, Lock) Exfi386InterlockedExchangeUlong(Target,Value)
Definition at line 2041 of file i386.h.
#define ExInterlockedIncrementLong (Addend, Lock) Exfi386InterlockedIncrementLong(Addend)
Definition at line 2035 of file i386.h.
#define ExInterlockedInsertHeadList ExfInterlockedInsertHeadList
Definition at line 2047 of file i386.h.
#define ExInterlockedInsertTailList ExfInterlockedInsertTailList
Definition at line 2048 of file i386.h.
#define ExInterlockedPopEntryList ExfInterlockedPopEntryList
Definition at line 2050 of file i386.h.
#define ExInterlockedPushEntryList ExfInterlockedPushEntryList
Definition at line 2051 of file i386.h.
#define ExInterlockedRemoveHeadList ExfInterlockedRemoveHeadList
Definition at line 2049 of file i386.h.
#define ExRaiseException RtlRaiseException
Definition at line 40 of file i386.h.
#define ExRaiseStatus RtlRaiseStatus
Definition at line 41 of file i386.h.
#define ExReleaseFastLock (Lock, OldIrql) ExReleaseSpinLock(Lock, OldIrql)
Definition at line 640 of file i386.h.
Referenced by CcCopyWrite(), CcFastCopyWrite(), CcFreeActiveVacb(), CcGetActiveVacb(), CcScheduleReadAhead(), CcSetActiveVacb(), IopCheckHardErrorEmpty(), IopRemoveHardErrorPacket(), IopRemoveTimerFromTimerList(), IoStartTimer(), and IoStopTimer().
#define ExReleaseSpinLock (Lock, OldIrql) KeReleaseSpinLock((Lock), (OldIrql))
Definition at line 594 of file i386.h.
Referenced by CcPostDeferredWrites(), CcScheduleReadAhead(), CcSetActiveVacb(), ExDeleteNPagedLookasideList(), ExDeletePagedLookasideList(), ExGetNextWakeTime(), ExInterlockedExtendZone(), ExpDeleteTimer(), ExpGetLookasideInformation(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpReleaseLockRoutine(), ExpRemovePoolTrackerExpansion(), ExpScanGeneralLookasideList(), ExpTimerApcRoutine(), ExRecordCallerInHashTable(), ExTimerRundown(), IopErrorLogGetEntry(), IopErrorLogRequeueEntry(), IopTimerDispatch(), IoRaiseInformationalHardError(), IoWriteErrorLogEntry(), KeI386AllocateGdtSelectors(), KeI386FlatToGdtSelector(), KeI386GetLid(), KeI386ReleaseGdtSelectors(), KeI386ReleaseLid(), MiAttemptPageFileReduction(), MiCheckForControlAreaDeletion(), MiCheckPteRelease(), MiCheckPteReserve(), MiContractPagingFiles(), MiDereferenceIoSpace(), MiDereferenceSegmentThread(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiIsProbeActive(), MiIssuePageExtendRequest(), MiIssuePageExtendRequestNoWait(), MiMapWithLargePages(), MiReferenceIoSpace(), MiReleaseSplitSystemPtes(), MiRemoveIoSpaceMap(), MiRemovePteTracker(), MiRemoveUnusedSegments(), MiUnmapLargePages(), MmIsIoSpaceActive(), NtCancelTimer(), NtSetTimer(), PspDereferenceQuotaBlock(), PspExpandQuota(), PspGivebackQuota(), PspInsertQuotaBlock(), PspQueryWorkingSetWatch(), and PsWatchWorkingSet().
#define ExReleaseSpinLockFromDpcLevel (Lock) KeReleaseSpinLockFromDpcLevel(Lock)
Definition at line 596 of file i386.h.
Referenced by CcFreeActiveVacb(), CcPerformReadAhead(), CcSetActiveVacb(), ExpTimerApcRoutine(), ExpTimerDpcRoutine(), ExTimerRundown(), MiProcessLoaderEntry(), MiSegmentDelete(), NtCancelTimer(), NtSetTimer(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
#define FLUSH_MULTIPLE_MAXIMUM 32
Definition at line 62 of file i386.h.
Referenced by KeFlushMultipleTb().
#define FRAME_EDITED 0xfff8
Definition at line 1750 of file i386.h.
Referenced by KeContextFromKframes(), KiEspFromTrapFrame(), and KiEspToTrapFrame().
#define GRAN_BYTE 0
Definition at line 876 of file i386.h.
#define GRAN_PAGE 1
Definition at line 877 of file i386.h.
Referenced by KiCloneSelector().
#define GUARD_PAGE_SIZE PAGE_SIZE
Definition at line 1870 of file i386.h.
Referenced by MiCheckForUserStackOverflow().
#define HIGH_LEVEL 31
Definition at line 170 of file i386.h.
Referenced by __out_bcount(), KeBugCheck2(), KeConnectInterrupt(), KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeEnterKernelDebugger(), KeFreezeExecution(), KeInsertQueueDpc(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), KeSetProfileIrql(), KeSetSystemTime(), KiCompleteEffectiveRangeChange(), KiExecuteDpc(), KiFreezeTargetExecution(), KiInitializeKernel(), KiInitializePAT(), KiInitMachineDependent(), MmMapLockedPagesSpecifyCache(), and MmMapLockedPagesWithReservedMapping().
#define HIGHWORD (l) ((USHORT)(((ULONG)(l)>>16) & 0xffff))
Definition at line 242 of file i386.h.
Referenced by KeI386FlatToGdtSelector().
#define I386_80387_NP_VECTOR 0x07
Definition at line 1800 of file i386.h.
Referenced by KeSetup80387OrEmulate().
#define IDT_DFH_VECTOR 8
Definition at line 883 of file i386.h.
Referenced by KiSetHaltedNmiandDoubleFaultHandler().
#define IDT_NMI_VECTOR 2
Definition at line 882 of file i386.h.
Referenced by KiSetHaltedNmiandDoubleFaultHandler().
#define IMAGE_FILE_MACHINE_NATIVE 0x014c
Definition at line 33 of file i386.h.
Referenced by MmCheckSystemImage().
#define INITIAL_STALL_COUNT 100
Definition at line 232 of file i386.h.
#define INITIALIZE_DIRECTORY_TABLE_BASE (dirbase, pfn) *((PULONG)(dirbase)) = ((pfn) << PAGE_SHIFT)
Definition at line 1987 of file i386.h.
Referenced by MmCreateProcessAddressSpace(), and MmInSwapProcess().
#define INT_DIRECTION_MAP_SIZE 32
Definition at line 918 of file i386.h.
Referenced by KiInitializeTSS2().
#define InterlockedCompareExchange64 (Destination, ExChange, Comperand) ExfInterlockedCompareExchange64(Destination, &(ExChange), &(Comperand))
Definition at line 2429 of file i386.h.
Referenced by ExAllocateLocallyUniqueId(), ExInsertTailNBQueue(), ExRemoveHeadNBQueue(), KiOpPatchCode(), KxAcquireSpinLock(), KxTryToAcquireSpinLock(), KxWaitForSpinLockAndAcquire(), MiChargeCommitment(), MiChargeCommitmentCantExpand(), MiChargeTemporaryCommitmentForReduction(), MiUpdateWsle(), and PspInterlockedCompareExchangeQuota().
#define InterlockedCompareExchangeAcquire InterlockedCompareExchange
Definition at line 2454 of file i386.h.
Referenced by ExAcquireSpinLockShared(), ExTryAcquireSpinLockExclusive(), and xxTryToAcquireFastMutex().
#define InterlockedCompareExchangeAcquire64 InterlockedCompareExchange64
Definition at line 2456 of file i386.h.
#define InterlockedCompareExchangePointer (Destination, ExChange, Comperand) (PVOID)InterlockedCompareExchange((PLONG)Destination, (LONG)ExChange, (LONG)Comperand)
Definition at line 2426 of file i386.h.
Referenced by CmpConstructName(), CmpDoQueueLateUnloadWorker(), CmpDumpKeyBodyList(), CmpFlushNotifiesOnKeyBodyList(), CmUnloadKey(), DelistKeyBodyFromKCB(), EnlistKeyBodyWithKCB(), ExAcquirePushLockShared(), ExAcquirePushLockSharedAssumeNoOwner(), ExAcquireRundownProtectionEx(), ExBlockPushLock(), ExConvertPushLockExclusiveToShared(), ExDeferredFreePool(), ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExfAcquireRundownProtection(), ExfConvertPushLockExclusiveToShared(), ExFreePoolWithTag(), ExfReleasePushLock(), ExfReleasePushLockExclusive(), ExfReleasePushLockShared(), ExfReleaseRundownProtection(), ExfTryAcquirePushLockShared(), ExfTryToWakePushLock(), ExfWaitForRundownProtectionRelease(), ExfWakePushLock(), ExpAddTagForBigPages(), ExpAllocateExclusiveWaiterEvent(), ExpAllocateSharedWaiterSemaphore(), ExpLockHandleTableEntry(), ExpOptimizePushLockList(), ExReleasePushLock(), ExReleasePushLockShared(), ExReleasePushLockSharedAssumeSingleOwner(), ExReleaseRundownProtectionEx(), ExSetHandleInfo(), ExTryAcquirePushLockShared(), ExTryConvertPushLockSharedToExclusive(), ExWaitForRundownProtectionReleaseCacheAware(), InterlockedPopEntrySingleList(), InterlockedPushEntrySingleList(), IoChangeFileObjectFilterContext(), KeInsertQueueDpc(), KeRegisterNmiCallback(), KxReleaseQueuedSpinLock(), KxTryToAcquireQueuedSpinLock(), MiDeferredUnlockPages(), MiInsertAweInfo(), MmUnlockPages(), NtAssignProcessToJobObject(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtSetInformationFile(), NtSetInformationProcess(), ObpDeferObjectDeletion(), ObpProcessRemoveObjectQueue(), PsImpersonateClient(), PspReaper(), PspSetQuotaLimits(), PsSetThreadWin32Thread(), PsShutdownSystem(), SeLocateProcessImageName(), WmipStartLogger(), and WmipSwitchBuffer().
#define InterlockedCompareExchangePointerAcquire InterlockedCompareExchangePointer
Definition at line 2458 of file i386.h.
Referenced by ExAcquireRundownProtection(), ExFastRefAddAdditionalReferenceCounts(), ExFastReference(), and ExWaitForRundownProtectionRelease().
#define InterlockedCompareExchangePointerRelease InterlockedCompareExchangePointer
Definition at line 2459 of file i386.h.
Referenced by ExFastRefCompareSwapObject(), ExFastRefDereference(), and ExReleaseRundownProtection().
#define InterlockedCompareExchangeRelease InterlockedCompareExchange
Definition at line 2455 of file i386.h.
#define InterlockedCompareExchangeRelease64 InterlockedCompareExchange64
Definition at line 2457 of file i386.h.
#define InterlockedDecrement (Addend) (InterlockedExchangeAdd (Addend, -1)-1)
Definition at line 2364 of file i386.h.
Referenced by CcZeroData(), CmpDelayCloseWorker(), CmpDereferenceKeyControlBlockWithLock(), CmpReferenceKeyControlBlock(), CmpRemoveFromDelayedClose(), ExDereferenceHandleDebugInfo(), ExFreePoolWithTag(), ExfReleasePushLock(), ExfReleasePushLockShared(), ExfReleaseRundownProtection(), ExpFindAndRemoveTagBigPages(), ExpFreeHandleTableEntry(), ExpShutdownWorker(), ExpWorkerThread(), ExReturnPoolQuota(), ExUuidCreate(), FsRtlCancelNotify(), FsRtlNotifyCleanup(), FsRtlNotifySetCancelRoutine(), IopAcquireFileObjectLock(), IopAllocateIrpPrivate(), IopRaiseInformationalHardError(), IopStartNextPacketByKeyEx(), KeBugCheck2(), KeEnterKernelDebugger(), KeSignalCallDpcDone(), KeSignalCallDpcSynchronize(), KiCalibrateTimeAdjustment(), KiIpiGenericCallTarget(), KiOpSingleProcCopy(), MiAllocateLargeZeroPages(), MiCauseOverCommitPopup(), MiDecrementCloneBlockReference(), MiDereferenceSession(), MiFindContiguousPages(), MiFlushAllPages(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiLockCode(), MiReleaseProcessReferenceToSessionDataPage(), MiRemoveMappedView(), MiReserveSystemPtes(), MiSectionDelete(), MiSessionOutSwapProcess(), MiSessionProcessGlobalSubsections(), MiSessionRemoveImage(), MiTrimAllSystemPageableMemory(), MmCreateSection(), MmDeleteKernelStack(), MmGatherMemoryForHibernate(), MmInitSystem(), MmLockPageableSectionByHandle(), MmMapLockedPagesSpecifyCache(), MmUnlockPageableImageSection(), NtTraceEvent(), ObDereferenceObjectDeferDelete(), ObfDereferenceObject(), ObpDecrementHandleCount(), ObpDereferenceNameInfo(), ObpDestroySecurityDescriptorHeader(), ObpFreeObject(), PerfInfoFlushProfileCache(), PspDereferenceQuota(), PspDereferenceQuotaBlock(), PsRemoveCreateThreadNotifyRoutine(), PsRemoveLoadImageNotifyRoutine(), PsSetCreateProcessNotifyRoutine(), RtlpWalkFrameChain(), SepDeReferenceLogonSession(), SeReleaseSubjectContext(), WmiFlushTrace(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipDecrementIrpCount(), WmipDoUnreferenceRegEntry(), WmipEventNotification(), WmipFreeTraceBufferPool(), WmipGetFreeBuffer(), WmipInitializeRegistration(), WmipPopFreeContextSwapBuffer(), WmipPushDirtyBuffer(), WmipPushFreeBuffer(), WmipQueryLogger(), WmipRegistrationWorker(), WmipReleaseTraceBuffer(), WmipReserveTraceBuffer(), WmipStartLogger(), WmipSwitchBuffer(), WmipTraceFile(), WmipTraceIo(), WmipUnreferenceEntry(), WmipVerifyLoggerInfo(), WmiStopTrace(), and WmiUpdateTrace().
#define InterlockedDecrementAcquire InterlockedDecrement
Definition at line 2451 of file i386.h.
Referenced by xxAcquireFastMutex(), and xxAcquireFastMutexUnsafe().
#define InterlockedDecrementRelease InterlockedDecrement
Definition at line 2452 of file i386.h.
Referenced by ExReleaseSpinLockShared().
#define InterlockedDecrementSizeT (a) InterlockedDecrement((LONG *)a)
Definition at line 2463 of file i386.h.
Referenced by MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MI_REMOVE_LOCKED_PAGE_CHARGE(), MI_REMOVE_LOCKED_PAGE_CHARGE_AND_DECREF(), MiDecrementReferenceCountForAwePage(), MiDeleteSystemPageableVm(), MiDeleteValidSystemPte(), MiFreeWsle(), MiFreeWsleList(), MiInitializeSessionPool(), and MiReleaseWsle().
#define InterlockedExchangeAcquire64 InterlockedExchange64
Definition at line 2453 of file i386.h.
Referenced by KzAcquireSpinLock().
#define InterlockedExchangeAddSizeT (a, b) InterlockedExchangeAdd((LONG *)a, b)
Definition at line 2461 of file i386.h.
Referenced by __bcount(), ExDeferredFreePool(), ExFreePoolWithTag(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), MiAddWorkingSetPage(), MiAllocatePagesForMdl(), MiAllocatePoolPages(), MiAttemptPageFileReduction(), MiBuildPagedPool(), MiCleanPhysicalProcessPages(), MiCreateImageFileMap(), MiCreatePagingFileMap(), MiDereferenceSessionFinal(), MiExtendPagingFileMaximum(), MiExtendPagingFiles(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), MiInPageSingleKernelStack(), MiInsertPageFileInList(), MiMapViewOfDataSection(), MiOutPageSingleKernelStack(), MiSegmentDelete(), MiSessionCommitPageTables(), MiSessionInitializeWorkingSetList(), MiShareSessionImage(), MmAdjustWorkingSetSizeEx(), MmAdvanceMdl(), MmCleanProcessAddressSpace(), MmCommitSessionMappedView(), MmCreateKernelStack(), MmCreateProcessAddressSpace(), MmDeleteKernelStack(), MmDeleteProcessAddressSpace(), MmFreeBootRegistry(), MmFreeLoaderBlock(), MmFreePagesFromMdl(), MmGrowKernelStackEx(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmUnloadSystemImage(), MmUnlockPages(), MmUnmapLockedPages(), MmUnmapReservedMapping(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), and NtFreeUserPhysicalPages().
#define InterlockedExchangePointer (Target, Value) (PVOID)InterlockedExchange((PLONG)Target, (LONG)Value)
Definition at line 2174 of file i386.h.
Referenced by ExDestroyHandle(), ExFastRefSwapObject(), ExfReInitializeRundownProtection(), ExfRundownCompleted(), ExfUnblockPushLock(), ExpAllocateHandleTableEntrySlow(), ExReInitializeRundownProtection(), ExReInitializeRundownProtectionCacheAware(), ExRundownCompleted(), ExRundownCompletedCacheAware(), InterlockedFlushSingleList(), IoCancelIrp(), IopDeleteDevice(), KiAcquireQueuedSpinLockCheckForFreeze(), KxAcquireQueuedSpinLock(), ObpProcessRemoveObjectQueue(), PspReaper(), PsSetThreadWin32Thread(), WmipFlushActiveBuffers(), and WmipFreeTraceBufferPool().
#define InterlockedIncrement (Addend) (InterlockedExchangeAdd (Addend, 1)+1)
Definition at line 2351 of file i386.h.
Referenced by __bcount(), CcZeroData(), CmLockKcbForWrite(), CmpAddToDelayedClose(), CmpLazyFlushWorker(), CmpLoadHiveThread(), CmpReferenceKeyControlBlock(), ExDeferredFreePool(), ExFreePoolWithTag(), ExpAddTagForBigPages(), ExpAllocateHandleTableEntry(), ExpCreateWorkerThread(), ExpFindAndRemoveTagBigPages(), ExpInsertPoolTrackerExpansion(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), ExpUpdateDebugInfo(), ExpWorkerThread(), ExReferenceHandleDebugInfo(), ExSetHandleInfo(), FsRtlNotifyFilterChangeDirectory(), IoCreateDevice(), IopAcquireFileObjectLock(), IoPageRead(), IopFreeIrp(), IopStartNextPacketByKeyEx(), IopUpdateOtherOperationCount(), IopUpdateReadOperationCount(), IopUpdateWriteOperationCount(), IopXxxControlFile(), IoRaiseInformationalHardError(), IoWMIWriteEvent(), KeBugCheck2(), KeSignalCallDpcSynchronize(), KiClearTbFlushTimeStampBusy(), KiLockStepExecution(), MiAllocateLargeZeroPages(), MiAllocateWsle(), MiCauseOverCommitPopup(), MiCcPutPagesInTransition(), MiCloneProcessAddressSpace(), MiCopyOnWrite(), MiFindContiguousPages(), MiFlushAllPages(), MiGatherPagefilePages(), MiIsProbeActive(), MiMapViewOfDataSection(), MiReleaseSystemPtes(), MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveProtoPteFault(), MiResolveTransitionFault(), MiSessionAddProcess(), MiSessionCreateInternal(), MiSessionInSwapProcess(), MiSessionOutSwapProcess(), MiSessionWideReserveImageAddress(), MiSnapPagefileWrite(), MiTrimAllSystemPageableMemory(), MiZeroPageWorker(), MmAccessFault(), MmCreateKernelStack(), MmCreateSection(), MmGatherMemoryForHibernate(), MmIsIoSpaceActive(), MmLockPageableSectionByHandle(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmUnmapLockedPages(), ObLogSecurityDescriptor(), ObpAllocateObject(), ObpIncrementHandleCount(), ObpIncrementUnnamedHandleCount(), ObpReferenceSecurityDescriptor(), PerfInfoFlushProfileCache(), PsChargeSharedPoolQuota(), PspInheritQuota(), PsSetCreateProcessNotifyRoutine(), PsSetCreateThreadNotifyRoutine(), PsSetLoadImageNotifyRoutine(), RtlpWalkFrameChain(), SeCaptureSubjectContextEx(), SeGetLogonIdDeviceMap(), SepCreateToken(), SepDuplicateLogonSessionReference(), SepDuplicateToken(), SepFilterToken(), SepReferenceLogonSession(), WmipAddLogHeader(), WmipAllocateFreeBuffers(), WmipAllocEntry(), WmipAllocRegEntry(), WmipFindRegEntryByDevice(), WmipGenerateFileName(), WmipGetFreeBuffer(), WmipMceDispatchRoutine(), WmipPopFreeContextSwapBuffer(), WmipPushDirtyBuffer(), WmipPushDirtyContextSwapBuffer(), WmipPushFreeBuffer(), WmipQueueRegWork(), WmipReserveTraceBuffer(), WmipStartLogger(), WmipSwitchBuffer(), and WmipVerifyLoggerInfo().
#define InterlockedIncrementAcquire InterlockedIncrement
Definition at line 2449 of file i386.h.
#define InterlockedIncrementRelease InterlockedIncrement
Definition at line 2450 of file i386.h.
Referenced by xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
#define InterlockedIncrementSizeT (a) InterlockedIncrement((LONG *)a)
Definition at line 2462 of file i386.h.
Referenced by MI_ADD_LOCKED_PAGE_CHARGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_MODIFIED_PAGE(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MiAddWorkingSetPage(), MiAddWsleHash(), MiAllocateWsle(), MiInitializeSessionPool(), and MiLockCode().
#define IO_ACCESS_MAP_NONE 0
Definition at line 925 of file i386.h.
Referenced by Ke386QueryIoAccessMap(), Ke386SetIoAccessMap(), KeInitializeProcess(), and KiInitializeTSS().
#define IOPM_COUNT 1
Definition at line 921 of file i386.h.
Referenced by Ke386IoSetAccessProcess(), Ke386QueryIoAccessMap(), Ke386SetIoAccessMap(), and KiInitializeTSS2().
#define IOPM_SIZE 8192
Definition at line 927 of file i386.h.
Referenced by Ke386QueryIoAccessMap(), and KiSetIoMap().
#define IPI_LEVEL 29
Definition at line 168 of file i386.h.
Referenced by KeIpiGenericCall(), and KiOpPatchCode().
#define IsNEC_98 (SharedUserData->AlternativeArchitecture == NEC98x86)
Definition at line 3055 of file i386.h.
#define IsNotNEC_98 (SharedUserData->AlternativeArchitecture != NEC98x86)
Definition at line 3056 of file i386.h.
#define Isx86FeaturePresent (_f_) ((KiBootFeatureBits & (_f_)) != 0)
Definition at line 3367 of file i386.h.
#define KeFillEntryTb (Virtual) KiFlushSingleTb (Virtual);
Definition at line 505 of file i386.h.
Referenced by MiSetDirtyBit().
#define KeFlushIoBuffers (Mdl, ReadOperation, DmaOperation)
Definition at line 559 of file i386.h.
#define KeGetDcacheFillSize () 1L
Definition at line 497 of file i386.h.
#define KeIsIdleHaltSet (Prcb, Number) ((Prcb)->Sleeping != 0)
Definition at line 2787 of file i386.h.
Referenced by KeInsertQueueDpc(), and KiDeferredReadyThread().
#define KeMemoryBarrierWithoutFence () _ReadWriteBarrier()
Definition at line 2850 of file i386.h.
Referenced by ExReleaseSpinLockExclusive(), IopCompleteRequest(), KeEnterCriticalRegionThread(), KeEnterGuardedRegionThread(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegionThread(), KeTestSpinLock(), and KiReleaseThreadLock().
#define KeSweepCurrentDcache ()
Definition at line 550 of file i386.h.
Referenced by KeThawExecution(), and KiFreezeTargetExecution().
#define KeSweepCurrentIcache ()
Definition at line 553 of file i386.h.
Referenced by KeThawExecution(), and KiFreezeTargetExecution().
#define KeSweepDcache (AllProcessors)
Definition at line 549 of file i386.h.
Referenced by KeInitializeInterrupt(), and MiInitMachineDependent().
#define KeSweepIcache (AllProcessors)
Definition at line 552 of file i386.h.
Referenced by KeDisconnectInterrupt(), MiReloadBootLoadedDrivers(), MmLoadSystemImage(), and NtFlushInstructionCache().
#define KeSweepIcacheRange (AllProcessors, BaseAddress, Length)
Definition at line 555 of file i386.h.
Referenced by MiCopyHeaderIfResident(), MiMapViewOfImageSection(), and NtFlushInstructionCache().
#define KeYieldProcessor () __asm { rep nop }
Definition at line 563 of file i386.h.
Referenced by ExAcquireSpinLockExclusive(), ExAcquireSpinLockShared(), ExfAcquirePushLockExclusive(), ExfAcquirePushLockShared(), ExTimedWaitForUnblockPushLock(), ExTryAcquireSpinLockExclusive(), KeFreezeExecution(), KeGenericCallDpc(), KeIpiGenericCall(), KeLoopTbFlushTimeStampUnlocked(), KeSignalCallDpcSynchronize(), KeStartAllProcessors(), KeSwitchFrozenProcessor(), KeTestSpinLock(), KeTryToAcquireGuardedMutex(), KeWaitForContextSwap(), KiAcquireKobjectLock(), KiAcquireQueuedSpinLockCheckForFreeze(), KiFreezeTargetExecution(), KiIpiSendRequest(), KiIpiStallOnPacketTargetsPrcb(), KiIpiWaitForRequestBarrier(), KiLockStepExecution(), KiOpSingleProcCopy(), KiPollFreezeExecution(), KiProcessorStart(), KiSendFreeze(), KiSendThawExecution(), KiSetTbFlushTimeStampBusy(), KiStartWaitAcknowledge(), KxTryToAcquireQueuedSpinLock(), KxTryToAcquireSpinLock(), KxWaitForLockChainValid(), KxWaitForLockOwnerShip(), KxWaitForSpinLockAndAcquire(), KzAcquireSpinLock(), and xxTryToAcquireFastMutex().
#define KF_3DNOW 0x00004000
Definition at line 3353 of file i386.h.
#define KF_AMDK6MTRR 0x00008000
Definition at line 3354 of file i386.h.
#define KF_CMOV 0x00000008
Definition at line 3342 of file i386.h.
#define KF_CMPXCHG8B 0x00000080
Definition at line 3346 of file i386.h.
#define KF_CR4 0x00000004
Definition at line 3341 of file i386.h.
#define KF_DTS 0x00020000
Definition at line 3356 of file i386.h.
#define KF_FAST_SYSCALL 0x00001000
Definition at line 3351 of file i386.h.
#define KF_FXSR 0x00000800
Definition at line 3350 of file i386.h.
#define KF_GLOBAL_32BIT_EXECUTE 0x40000000
Definition at line 3358 of file i386.h.
#define KF_GLOBAL_32BIT_NOEXECUTE 0x80000000
Definition at line 3359 of file i386.h.
#define KF_GLOBAL_PAGE 0x00000010
Definition at line 3343 of file i386.h.
#define KF_LARGE_PAGE 0x00000020
Definition at line 3344 of file i386.h.
#define KF_MMX 0x00000100
Definition at line 3347 of file i386.h.
#define KF_MTRR 0x00000040
Definition at line 3345 of file i386.h.
#define KF_NOEXECUTE 0x20000000
Definition at line 3357 of file i386.h.
#define KF_PAT 0x00000400
Definition at line 3349 of file i386.h.
#define KF_RDTSC 0x00000002
Definition at line 3340 of file i386.h.
#define KF_V86_VIS 0x00000001
Definition at line 3339 of file i386.h.
Referenced by KiGetFeatureBits().
#define KF_WORKING_PTE 0x00000200
Definition at line 3348 of file i386.h.
Referenced by KeStartAllProcessors(), and KiGetFeatureBits().
#define KF_XMMI 0x00002000
Definition at line 3352 of file i386.h.
#define KF_XMMI64 0x00010000
Definition at line 3355 of file i386.h.
#define KI_BEGIN_KERNEL_RESERVED 0xffdf0000
Definition at line 1999 of file i386.h.
#define KI_USER_SHARED_DATA 0xffdf0000
Definition at line 2004 of file i386.h.
Referenced by MmInitSystem().
#define KiComputeIopmOffset (MapNumber)
Value:
(MapNumber == IO_ACCESS_MAP_NONE) ?         \
        (USHORT)(sizeof(KTSS)) :                    \
        (USHORT)(FIELD_OFFSET(KTSS, IoMaps[MapNumber-1].IoMap))
Definition at line 1001 of file i386.h.
Referenced by Ke386IoSetAccessProcess(), KeInitializeProcess(), KiInitializeBootStructures(), and KiInitializeTSS().
#define KiIsThreadNumericStateSaved (a) (a->NpxState != NPX_STATE_LOADED)
Definition at line 2888 of file i386.h.
Referenced by KiOutSwapKernelStacks().
#define KIP0PCRADDRESS 0xffdff000
Definition at line 2000 of file i386.h.
Referenced by KeGetPcr().
#define KiPcr () KeGetPcr()
Definition at line 2641 of file i386.h.
Referenced by Ke386GetGdtEntryThread(), Ke386QueryIoAccessMap(), KiLoadIopmOffset(), and KiSetIoMap().
#define KiQueryInterruptTime (CurrentTime)
Value:
while (TRUE) {                                                                      \
        (CurrentTime)->HighPart = SharedUserData->InterruptTime.High1Time;              \
        (CurrentTime)->LowPart = SharedUserData->InterruptTime.LowPart;                 \
        if ((CurrentTime)->HighPart == SharedUserData->InterruptTime.High2Time) break;  \
        _asm { rep nop }                                                                \
    }
Definition at line 705 of file i386.h.
Referenced by KeQueryInterruptTime(), KiCheckDueTime(), KiComputeDueTime(), KiComputeWaitInterval(), KiInsertTimerTable(), KiSetDueTime(), KiTimerExpiration(), and NtQueryTimer().
#define KiQueryTickCount (CurrentCount)
Value:
while (TRUE) {                                                      \
        (CurrentCount)->HighPart = KeTickCount.High1Time;               \
        (CurrentCount)->LowPart = KeTickCount.LowPart;                  \
        if ((CurrentCount)->HighPart == KeTickCount.High2Time) break;   \
        _asm { rep nop }                                                \
    }
Definition at line 693 of file i386.h.
Referenced by KeQueryTickCount().
#define KiRequestSoftwareInterrupt (RequestIrql) HalRequestSoftwareInterrupt(RequestIrql)
Definition at line 270 of file i386.h.
Referenced by KeDetachProcess(), KeFlushQueuedDpcs(), KeInsertQueueDpc(), KeSetTimerEx(), KeUnstackDetachProcess(), KeUpdateRunTime(), KiCheckForKernelApcDelivery(), KiCompleteTimer(), KiExitDispatcher(), and KiInsertQueueApc().
#define KiReturnHandlerAddressFromIDT (Vector) MAKEULONG(KiPcr()->IDT[HalVectorToIDTEntry(Vector)].ExtendedOffset, KiPcr()->IDT[HalVectorToIDTEntry(Vector)].Offset)
Definition at line 2875 of file i386.h.
Referenced by KiGetVectorInfo().
#define KiRundownThread (a)
Definition at line 2917 of file i386.h.
Referenced by KeTerminateThread().
#define KiSetHandlerAddressToIDT (Vector, HandlerAddress)
Value:
{\
    UCHAR IDTEntry = HalVectorToIDTEntry(Vector); \
    ULONG Ha = (ULONG)HandlerAddress; \
    KeGetPcr()->IDT[IDTEntry].ExtendedOffset = HIGHWORD(Ha); \
    KeGetPcr()->IDT[IDTEntry].Offset = LOWWORD(Ha); \
}
Definition at line 2865 of file i386.h.
Referenced by KeSetup80387OrEmulate(), and KiConnectVectorAndInterruptObject().
#define KiSynchIrql SYNCH_LEVEL
Definition at line 186 of file i386.h.
#define KSEG0_BASE 0x80000000
Definition at line 1980 of file i386.h.
Referenced by MiInitMachineDependent(), MmFreeLoaderBlock(), and MmInitSystem().
#define KTRAP_FRAME_ALIGN (sizeof(ULONG))
Definition at line 1743 of file i386.h.
Referenced by Ke386SetIOPL().
#define KTRAP_FRAME_LENGTH (sizeof(KTRAP_FRAME))
Definition at line 1742 of file i386.h.
Referenced by KiInitializeContextThread().
#define KTRAP_FRAME_ROUND (KTRAP_FRAME_ALIGN-1)
Definition at line 1744 of file i386.h.
#define LOW_LEVEL 0
Definition at line 161 of file i386.h.
#define LOWWORD (l) ((USHORT)((ULONG)l & 0x0000ffff))
Definition at line 249 of file i386.h.
Referenced by KeI386FlatToGdtSelector().
#define MACHINE_TYPE_EISA 1
Definition at line 193 of file i386.h.
#define MACHINE_TYPE_ISA 0
Definition at line 192 of file i386.h.
#define MACHINE_TYPE_MCA 2
Definition at line 194 of file i386.h.
#define MAKEULONG (x, y)
Value:
(((((ULONG)(x))<<16) & 0xffff0000) | \
    ((ULONG)(y) & 0xffff))
Definition at line 258 of file i386.h.
#define MINIMUM_PROFILE_INTERVAL 1221
Definition at line 1832 of file i386.h.
Referenced by KeSetIntervalProfile().
#define MM_HIGHEST_USER_ADDRESS MmHighestUserAddress
Definition at line 1887 of file i386.h.
Referenced by CmpSetValueKeyExisting(), ExFreePoolSanityChecks(), ExpGetSystemBasicInformation(), ExpInitializeExecutive(), MiCheckCacheAttributes(), MiCheckVirtualAddress(), MiCloneProcessAddressSpace(), MiDeleteAddressesInWorkingSet(), MiDeletePteList(), MiDispatchFault(), MiEliminateWorkingSetEntry(), MiFindEmptyAddressRange(), MiFreeWsleList(), MiGetWorkingSetInfoList(), MiMakeSystemAddressValid(), MiMakeSystemAddressValidPfn(), MiMakeSystemAddressValidPfnSystemWs(), MiMakeSystemAddressValidPfnWs(), MiResolvePageFileFault(), MiReturnPageTablePageCommitment(), MiSecureVirtualMemory(), MiTrimPte(), MiWaitForInPageComplete(), MmAccessFault(), MmFreeMappingAddress(), MmMapUserAddressesToPage(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmProtectMdlSystemAddress(), MmUnmapLockedPages(), MmUnmapReservedMapping(), NtCreateProfile(), NtFlushVirtualMemory(), NtFreeVirtualMemory(), NtLockVirtualMemory(), NtProtectVirtualMemory(), NtQueryVirtualMemory(), NtReadVirtualMemory(), NtUnlockVirtualMemory(), NtUnmapViewOfSection(), NtWriteVirtualMemory(), PspIsDescriptorValid(), RtlImageNtHeaderEx(), RtlpImageDirectoryEntryToData32(), and RtlpImageDirectoryEntryToData64().
#define MM_LOWEST_SYSTEM_ADDRESS (PVOID)0xC0800000
Definition at line 1913 of file i386.h.
#define MM_LOWEST_USER_ADDRESS (PVOID)0x10000
Definition at line 1906 of file i386.h.
Referenced by ExpGetSystemBasicInformation(), MiFindEmptyAddressRangeDownBasedTree(), MiFindEmptyAddressRangeDownTree(), MiFindEmptyAddressRangeInTree(), and MiMapViewOfImageSection().
#define MM_SYSTEM_RANGE_START MmSystemRangeStart
Definition at line 1888 of file i386.h.
Referenced by KeAcquireGuardedMutexUnsafe(), KeReleaseGuardedMutexUnsafe(), MiFreePoolPages(), MiInitMachineDependent(), MiMapSinglePage(), MiUnmapSinglePage(), MmGetSizeOfBigPoolAllocation(), MmInitializeProcessAddressSpace(), xxAcquireFastMutexUnsafe(), and xxReleaseFastMutexUnsafe().
#define MM_USER_PROBE_ADDRESS MmUserProbeAddress
Definition at line 1898 of file i386.h.
Referenced by MmProbeAndLockPages(), ProbeForRead(), ProbeForWrite(), and ProbeForWriteSmallStructure().
#define MmGetProcedureAddress (Address) (Address)
Definition at line 1920 of file i386.h.
Referenced by MiFindInitializationCode().
#define MmLockPagableCodeSection (Address) MmLockPageableDataSection(Address)
Definition at line 1922 of file i386.h.
#define MmLockPagableDataSection (Address) MmLockPageableDataSection(Address)
Definition at line 1923 of file i386.h.
#define MmLockPageableCodeSection (Address) MmLockPageableDataSection(Address)
Definition at line 1921 of file i386.h.
Referenced by MmInitSystem(), and WmipStartGlobalLogger().
#define MODE_MASK 1
Definition at line 215 of file i386.h.
Referenced by KeContextFromKframes(), KeContextToKframes(), KeRaiseUserException(), KeUpdateRunTime(), KiEspFromTrapFrame(), KiEspToTrapFrame(), KiInitializeUserApc(), KiPreprocessInvalidOpcodeFault(), KiRestoreProcessorState(), KiSegSsFromTrapFrame(), and KiSegSsToTrapFrame().
#define NMI_TSS_DESC_OFFSET 0x58
Definition at line 884 of file i386.h.
Referenced by KiDummyNmiHandler().
#define NORMAL_DISPATCH_LENGTH 106
Definition at line 98 of file i386.h.
Referenced by KeInitializeInterrupt().
#define NPX_STATE_LOADED 0
Definition at line 144 of file i386.h.
Referenced by KeRestoreFloatingPointState(), and KeSaveFloatingPointState().
#define NPX_STATE_NOT_LOADED (CR0_TS | CR0_MP)
Definition at line 143 of file i386.h.
Referenced by KeRestoreFloatingPointState(), KeSaveFloatingPointState(), Ki386CheckDelayedNpxTrap(), and KiInitializeContextThread().
#define PAGE_SHIFT 12L
Definition at line 1852 of file i386.h.
Referenced by __bcount(), __out_bcount(), CcAcquireByteRangeForWrite(), CcCopyRead(), CcCopyWrite(), CcDeleteBcbs(), CcFastCopyRead(), CcFastCopyWrite(), CcFlushCache(), CcFreeActiveVacb(), CcGetFlushedValidData(), CcInitializeVacbs(), CcMapAndCopy(), CcSetDirtyInMask(), CcSetDirtyPinnedData(), CcUnpinFileDataEx(), ExFreePoolWithTag(), ExGetBigPoolInfo(), ExpAddTagForBigPages(), ExpCopyProcessInfo(), ExpExpandBigPageTable(), ExpFindAndRemoveTagBigPages(), ExpInsertPoolTrackerExpansion(), ExpQueryNumaAvailableMemory(), IoAsynchronousPageWrite(), IoBuildPartialMdl(), IoPageRead(), IoSynchronousPageWrite(), Ki386ConvertPte(), Ki386IdentityMapMakeValid(), Ki386MapAddress(), KiCloneSelector(), MiAddExtraSystemPteRanges(), MiAllocateLargePages(), MiAllocateLargeZeroPages(), MiAllocatePagesForMdl(), MiAllocatePoolPages(), MiAttemptPageFileExtension(), MiAttemptPageFileReduction(), MiBuildPagedPool(), MiCancelWriteOfMappedPfn(), MiCaptureWriteWatchDirtyBit(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiCheckCacheAttributes(), MiCheckForContiguousMemory(), MiCheckPteRelease(), MiCheckPteReserve(), MiCheckVirtualAddress(), MiCleanPhysicalProcessPages(), MiCloneProcessAddressSpace(), MiComputeInitialLargePage(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreatePagingFileMap(), MiCreatePebOrTeb(), MiDoMappedCopy(), MiFindContiguousMemory(), MiFindContiguousMemoryInPool(), MiFindEmptyAddressRangeDownTree(), MiFindEmptyAddressRangeInTree(), MiFindLargePageMemory(), MiFlushSectionInternal(), MiFreeLargePages(), MiFreePoolPages(), MiGatherMappedPages(), MiGatherPagefilePages(), MiGrowWsleHash(), MiHandleBankedSection(), MiIdentifyPfn(), MiInitializeLoadedModuleList(), MiInitializeNonPagedPoolThresholds(), MiInitializeSessionIds(), MiInitializeSessionPool(), MiInitializeSystemPtes(), MiInitMachineDependent(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiLoadImageSection(), MiMakeOutswappedPageResident(), MiMapBBTMemory(), MiMapLargePageSection(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiMapWithLargePages(), MiReloadBootLoadedDrivers(), MiRemoveImageSessionWide(), MiRemoveMappedView(), MiReserveAlignedSystemPtes(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiSessionInitializeWorkingSetList(), MiSessionPoolBigPageTable(), MiSessionPoolBigPageTableSize(), MiSessionPoolTrackTable(), MiSessionPoolTrackTableSize(), MiSessionWideInitializeAddresses(), MiSessionWideReserveImageAddress(), MiShareSessionImage(), MiStartingOffset(), MiUnmapLargePages(), MiUnmapViewInSystemSpace(), MiUnmapViewOfSection(), MiUpdateSystemPdes(), MiUseLargeDriverPage(), MiWaitForInPageComplete(), MiZeroAwePageWorker(), MiZeroPageFile(), MiZeroPageWorker(), MmAdjustWorkingSetSizeEx(), MmAdvanceMdl(), MmCleanProcessAddressSpace(), MmCommitSessionMappedView(), MmExtendSection(), MmFlushSection(), MmFreeContiguousMemory(), MmFreeDriverInitialization(), MmGatherMemoryForHibernate(), MmGetPhysicalAddress(), MmGetSizeOfBigPoolAllocation(), MmGetVirtualForPhysical(), MmInitializeProcessAddressSpace(), MmInitSystem(), MmInSwapProcess(), MmIsIoSpaceActive(), MmLoadSystemImage(), MmMapMemoryDumpMdl(), MmMapUserAddressesToPage(), MmMapViewInSystemCache(), MmPageEntireDriver(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmQuerySystemCacheWorkingSetInformation(), MmQueryWorkingSetInformation(), MmRaisePoolQuota(), MmResourcesAvailable(), MmReturnMemoryForHibernate(), MmSetBankedSection(), MmSetPageProtection(), MmUnloadSystemImage(), MmUnlockPages(), MmUnmapLockedPages(), MmZeroPageThread(), NtAllocateUserPhysicalPages(), NtCreatePagingFile(), NtFreeUserPhysicalPages(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtMapUserPhysicalPages(), NtMapViewOfSection(), NtQueryInformationJobObject(), NtQueryInformationProcess(), NtResetWriteWatch(), and NtSetInformationJobObject().
#define PAGE_SIZE 0x1000
Definition at line 1844 of file i386.h.
Referenced by __bcount(), CcAcquireByteRangeForWrite(), CcAllocateObcb(), CcCanIWrite(), CcCopyWrite(), CcCreateVacbArray(), CcExtendVacbArray(), CcFastCopyWrite(), CcFlushCache(), CcFreeActiveVacb(), CcInitializeCacheManager(), CcInitializeCacheMap(), CcLazyWriteScan(), CcMapAndCopy(), CcMapAndRead(), CcMapData(), CcMapDataForOverwrite(), CcPerformReadAhead(), CcPinFileData(), CcPrepareMdlWrite(), CcPurgeAndClearCacheSection(), CcPurgeCacheSection(), CcScheduleReadAhead(), CcSetDirtyInMask(), CcSetFileSizes(), CcZeroData(), CmInitSystem1(), CmpAddSecurityCellToCache(), CmpAllocateDelayItem(), CmpAllocateKeyControlBlock(), CmpFileWrite(), CmpPrefetchHiveFile(), ExFreePoolSanityChecks(), ExFreePoolWithTag(), ExInsertPoolTag(), ExpAllocateMidLevelTable(), ExpExpandBigPageTable(), ExpFreeHandleTable(), ExpGetSystemBasicInformation(), ExpInitializeExecutive(), ExpInsertPoolTrackerExpansion(), ExQueryPoolBlockSize(), HalExamineMBR(), HalpDeleteMountLetter(), HalpQueryDriveLayout(), HvInitializeHive(), HvMarkDirty(), HvpAddBin(), HvpGetCellMapped(), HvpGetHiveHeader(), HvpRecoverData(), HvpWriteLog(), HvRefreshHive(), IoAsynchronousPageWrite(), IoPageRead(), IopLoadDriver(), IoSetPartitionInformation(), IoSynchronousPageWrite(), IoWritePartitionTable(), Ke386CallBios(), KeBugCheck2(), Ki386AllocateContiguousMemory(), Ki386BuildIdentityBuffer(), Ki386CreateIdentityMap(), KiI386PentiumLockErrataFixup(), KiInitializeKernel(), KiInvokeBugCheckEntryCallbacks(), MiAddHalIoMappings(), MiAddWorkingSetPage(), MiAdjustWorkingSetManagerParameters(), MiAllocatePagesForMdl(), MiAllocatePoolPages(), MiAttemptPageFileExtension(), MiAttemptPageFileReduction(), MiBuildPagedPool(), MiCanFileBeTruncatedInternal(), MiCcCompletePrefetchIos(), MiCcPutPagesInTransition(), MiCheckCacheAttributes(), MiCheckForUserStackOverflow(), MiCleanSection(), MiClearStackGuardBits(), MiCloneProcessAddressSpace(), MiComputeInitialLargePage(), MiCopyHeaderIfResident(), MiCreateDataFileMap(), MiCreateImageFileMap(), MiCreatePageTablesForPhysicalRange(), MiCreatePagingFileMap(), MiCreatePebOrTeb(), MiDecommitPages(), MiDeletePageTablesForPhysicalRange(), MiDeleteVirtualAddresses(), MiDispatchFault(), MiEnablePagingOfDriver(), MiEnablePagingOfDriverAtInit(), MiEnablePagingTheExecutive(), MiFindContiguousMemoryInPool(), MiFindEmptyAddressRangeDownBasedTree(), MiFindEmptyAddressRangeDownTree(), MiFindEmptyAddressRangeInTree(), MiFindInitializationCode(), MiFlushDirtyBitsToPfn(), MiFlushSectionInternal(), MiFreePoolPages(), MiGatherMappedPages(), MiGatherPagefilePages(), MiGrowWsleHash(), MiInitializeCommitment(), MiInitializeMemoryEvents(), MiInitializeNonPagedPool(), MiInitializeReadInProgressPfn(), MiInitializeSystemCache(), MiInitializeSystemPtes(), MiInitializeSystemSpaceMap(), MiInitializeWorkingSetList(), MiInitMachineDependent(), MiInPageSingleKernelStack(), MiInsertPageInFreeList(), MiInsertWsleHash(), MiIsEntireRangeCommitted(), MiLoadImageSection(), MiMakeOutswappedPageResident(), MiMapBBTMemory(), MiMapLockedPagesInUserSpace(), MiMapViewOfDataSection(), MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MiNoPagesLastChance(), MiOutPageSingleKernelStack(), MiProtectFreeNonPagedPool(), MiProtectVirtualMemory(), MiPteSListExpansionWorker(), MiPurgeImageSection(), MiQueryAddressState(), MiReloadBootLoadedDrivers(), MiRemoveMappedPtes(), MiRemoveUnusedSegments(), MiRemoveWorkingSetPages(), MiReserveAlignedSystemPtes(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiSecureVirtualMemory(), MiSessionInitializeWorkingSetList(), MiSessionProcessGlobalSubsections(), MiSessionWideReserveImageAddress(), MiSetPagingOfDriver(), MiShutdownSystem(), MiTrimSegmentCache(), MiTrimWorkingSet(), MiUnmapLockedPagesInUserSpace(), MiUnmapViewOfSection(), MiUseLargeDriverPage(), MiVerifyImageHeader(), MiWaitForInPageComplete(), MiWriteComplete(), MiZeroAwePageWorker(), MiZeroPageFile(), MiZeroPageFileFirstPage(), MiZeroPageWorker(), MmAccessFault(), MmAdjustWorkingSetSizeEx(), MmAdvanceMdl(), MmCommitSessionMappedView(), MmCopyToCachedPage(), MmCreatePeb(), MmCreateProcessAddressSpace(), MmExtendSection(), MmFlushVirtualMemory(), MmFreeLoaderBlock(), MmFreePagesFromMdl(), MmGrowKernelStackEx(), MmInitializeProcessAddressSpace(), MmInitSystem(), MmInPageKernelStack(), MmMapMemoryDumpMdl(), MmOutPageKernelStack(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmReleaseDumpAddresses(), MmSetAddressRangeModified(), MmSetBankedSection(), MmSetMemoryPriorityProcess(), MmUnmapIoSpace(), MmUnmapReservedMapping(), MmUnmapViewInSystemCache(), MxPopulatePageDirectories(), NtAllocateUserPhysicalPages(), NtAllocateVirtualMemory(), NtFreeVirtualMemory(), NtGetWriteWatch(), NtLockVirtualMemory(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtMapViewOfSection(), NtQueryVirtualMemory(), NtReadFileScatter(), NtResetWriteWatch(), NtSetInformationJobObject(), NtUnlockVirtualMemory(), NtWriteFileGather(), ObInitSystem(), PerfInfoFileNameRunDown(), Phase1InitializationDiscard(), PspSetLdtInformation(), PspSetLdtSize(), PsSetProcessLdtInfo(), RtlpCaptureStackLimits(), RtlpExtendStackTraceDataBase(), RtlpTouchMemory(), SepRmCommandServerThreadInit(), WmipFinalizeHeader(), WmipInitContext(), WmipStartGlobalLogger(), and WmipStartLogger().
#define PASSIVE_LEVEL 0
Definition at line 160 of file i386.h.
Referenced by __bcount(), CcPerfFileRunDown(), ExCreatePoolTagTable(), ExDeletePoolTagTable(), ExGetBigPoolInfo(), ExGetPoolTagInfo(), ExGetSessionPoolTagInfo(), ExpWorkerThread(), IopStartNextPacket(), IopStartNextPacketByKey(), IopSynchronousServiceTail(), IoStartPacket(), IoVolumeDeviceToDosName(), KiCheckForKernelApcDelivery(), KiExecuteDpc(), KiInitializeContextThread(), KiInitializeUserApc(), MiAccessCheck(), MiAddWorkingSetPage(), MiAttachAndLockWorkingSet(), MiCcCompletePrefetchIos(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiDecrementReferenceCountForAwePage(), MiDetachAndUnlockWorkingSet(), MiFindImageSectionObject(), MiFlushSectionInternal(), MiGatherPagefilePages(), MiMapPagesToZeroInHyperSpace(), MiPteSListExpansionWorker(), MiSessionPoolBigPageTable(), MiSessionPoolBigPageTableSize(), MiSessionPoolLookaside(), MiSessionPoolTrackTable(), MiSessionPoolTrackTableSize(), MiUnmapPagesInZeroSpace(), MmAccessFault(), MmAvailablePoolInPages(), MmCopyToCachedPage(), MmFreeBootRegistry(), MmFreeMappingAddress(), MmGetDirectoryFrameFromProcess(), MmGetExecuteOptions(), MmGetFileObjectForSection(), MmGetSystemRoutineAddress(), MmIdentifyPhysicalMemory(), MmIsMemoryAvailable(), MmPerfSnapShotValidPhysicalMemory(), MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), MmPrefetchPagesIntoLockedMdl(), MmSetExecuteOptions(), MmUnlockPages(), NtAllocateUserPhysicalPages(), NtFreeUserPhysicalPages(), NtGetWriteWatch(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtReleaseKeyedEvent(), NtResetWriteWatch(), NtWaitForKeyedEvent(), PspExitThread(), and PspUserThreadStartup().
#define PCR_MAJOR_VERSION 1
Definition at line 1382 of file i386.h.
Referenced by KiInitializeBootStructures(), and KiInitializePcr().
#define PCR_MINOR_VERSION 1
Definition at line 1381 of file i386.h.
Referenced by KiInitializeBootStructures(), and KiInitializePcr().
#define PDE_BASE PDE_BASE_X86
Definition at line 1964 of file i386.h.
Referenced by MiBuildPagedPool(), MiCloneProcessAddressSpace(), MiDetermineUserGlobalPteMask(), MiInitializeWorkingSetList(), MiInitMachineDependent(), MiMapWithLargePages(), MiUnmapLargePages(), MiWriteComplete(), MmCreateProcessAddressSpace(), MmInitializeProcessAddressSpace(), MmInitSystem(), MmInSwapProcess(), and MmOutSwapProcess().
#define PDE_BASE_X86 0xc0300000
Definition at line 1953 of file i386.h.
#define PDE_BASE_X86PAE 0xc0600000
Definition at line 1954 of file i386.h.
#define PDE_TOP PDE_TOP_X86
Definition at line 1966 of file i386.h.
Referenced by MiDetermineUserGlobalPteMask().
#define PDE_TOP_X86 0xC0300FFF
Definition at line 1957 of file i386.h.
#define PDE_TOP_X86PAE 0xC0603FFF
Definition at line 1960 of file i386.h.
#define PDI_SHIFT PDI_SHIFT_X86
Definition at line 1936 of file i386.h.
#define PDI_SHIFT PDI_SHIFT_X86
Definition at line 1936 of file i386.h.
#define PDI_SHIFT_X86 22
Definition at line 1932 of file i386.h.
#define PDI_SHIFT_X86 22
Definition at line 1932 of file i386.h.
#define PDI_SHIFT_X86PAE 21
Definition at line 1933 of file i386.h.
#define PDI_SHIFT_X86PAE 21
Definition at line 1933 of file i386.h.
#define PIOPM_SIZE 8196
Definition at line 929 of file i386.h.
Referenced by KiInitializeTSS2().
#define POWER_LEVEL 30
Definition at line 169 of file i386.h.
#define PRCB_BUILD_DEBUG 0x0001
Definition at line 1070 of file i386.h.
Referenced by KiInitializeBootStructures(), and KiInitializePcr().
#define PRCB_BUILD_UNIPROCESSOR 0x0002
Definition at line 1071 of file i386.h.
Referenced by KiInitializeBootStructures(), and KiInitializePcr().
#define PRCB_MAJOR_VERSION 1
Definition at line 1068 of file i386.h.
Referenced by KiInitializeBootStructures(), and KiInitializePcr().
#define PRCB_MINOR_VERSION 1
Definition at line 1069 of file i386.h.
Referenced by KiInitializeBootStructures(), and KiInitializePcr().
#define PROFILE_LEVEL 27
Definition at line 165 of file i386.h.
Referenced by KeSetProfileIrql().
#define PTE_BASE 0xc0000000
Definition at line 1972 of file i386.h.
Referenced by MiDetermineUserGlobalPteMask(), MiEliminateWorkingSetEntry(), MiFreeWsleList(), MiIdentifyPfn(), MiUpdateWsle(), MmAccessFault(), and MmCreateProcessAddressSpace().
#define PTE_TOP PTE_TOP_X86
Definition at line 1965 of file i386.h.
Referenced by MiEliminateWorkingSetEntry(), MiFreeWsleList(), MiIdentifyPfn(), MiInitializeSystemPtes(), and MiWriteComplete().
#define PTE_TOP_X86 0xC03FFFFF
Definition at line 1956 of file i386.h.
#define PTE_TOP_X86PAE 0xC07FFFFF
Definition at line 1959 of file i386.h.
#define PTI_SHIFT 12
Definition at line 1947 of file i386.h.
#define PTI_SHIFT 12
Definition at line 1947 of file i386.h.
#define RESULT_NEGATIVE ((EFLAG_SIGN & ~EFLAG_ZERO) & EFLAG_SELECT)
Definition at line 2020 of file i386.h.
#define RESULT_POSITIVE ((~EFLAG_SIGN & ~EFLAG_ZERO) & EFLAG_SELECT)
Definition at line 2022 of file i386.h.
#define RESULT_ZERO ((~EFLAG_SIGN & EFLAG_ZERO) & EFLAG_SELECT)
Definition at line 2021 of file i386.h.
#define RPL_MASK 3
Definition at line 216 of file i386.h.
Referenced by KeContextFromKframes(), KeContextToKframes(), KeInvalidAccessAllowed(), KeStartAllProcessors(), KiCheckForSListAddress(), KiDispatchException(), KiInitializeBootStructures(), KiInitializeContextThread(), KiOpDecode(), KiOpPreprocessAccessViolation(), KiSegSsFromTrapFrame(), KiSegSsToTrapFrame(), KxContextToKframes(), PspGetContext(), PspSetContext(), and PsSetLdtEntries().
#define SANITIZE_DR6 (Dr6, mode) (((Dr6) & DR6_LEGAL))
Definition at line 1578 of file i386.h.
Referenced by KeContextToKframes().
#define SANITIZE_DR7 (Dr7, mode) (((Dr7) & DR7_LEGAL))
Definition at line 1580 of file i386.h.
Referenced by KeContextToKframes(), KxContextToKframes(), and PspSetContext().
#define SANITIZE_DRADDR (DrReg, mode)
Value:
(\
    (mode) == KernelMode ?                      \
        (DrReg) :                               \
        (((PVOID)DrReg <= MM_HIGHEST_USER_ADDRESS) ?   \
            (DrReg) :                           \
            (0)                                 \
        )                                       \
    )
Definition at line 1582 of file i386.h.
Referenced by KeContextToKframes(), KxContextToKframes(), and PspSetContext().
#define SANITIZE_FLAGS (eFlags, mode)
Value:
(\
    ((mode) == KernelMode ? \
        ((0x00000000L) | ((eFlags) & 0x003f0fd7)) : \
        ((EFLAGS_INTERRUPT_MASK) | ((eFlags) & EFLAGS_USER_SANITIZE))))
Definition at line 1536 of file i386.h.
Referenced by KeContextToKframes(), and KiInitializeUserApc().
#define SANITIZE_MXCSR (_mxcsr_) ((_mxcsr_) & KiMXCsrMask)
Definition at line 1598 of file i386.h.
Referenced by KeContextToKframes(), KxContextToKframes(), and PspSetContext().
#define SANITIZE_SEG (segCS, mode)
Value:
(\
    ((mode) == KernelMode ? \
        ((0x00000000L) | ((segCS) & 0xfffc)) : \
        ((0x00000003L) | ((segCS) & 0xffff))))
Definition at line 1519 of file i386.h.
Referenced by KeContextToKframes(), KiDispatchException(), and KiInitializeUserApc().
#define SEGMENT_MASK 0xffff
Definition at line 224 of file i386.h.
Referenced by KeContextFromKframes(), and KiSegSsToTrapFrame().
#define SELECTOR_TABLE_INDEX 0x04
Definition at line 879 of file i386.h.
Referenced by PspQueryDescriptorThread(), and PsSetLdtEntries().
#define SetNEC_98 SharedUserData->AlternativeArchitecture = NEC98x86
Definition at line 3057 of file i386.h.
#define SetNotNEC_98 SharedUserData->AlternativeArchitecture = StandardDesign
Definition at line 3058 of file i386.h.
#define SharedUserData ((KUSER_SHARED_DATA * const) KI_USER_SHARED_DATA)
Definition at line 2005 of file i386.h.
Referenced by ExIsProcessorFeaturePresent(), ExpInitializeExecutive(), ExpReadComPlusPackage(), IopXxxControlFile(), KeSetSystemTime(), KiCalibrateTimeAdjustment(), KiDispatchException(), KiInitializeKernel(), KiInitializePcr(), KiInitMachineDependent(), MmInitSystem(), MmLoadSystemImage(), NtQuerySystemInformation(), NtSetSystemInformation(), Phase1InitializationDiscard(), PspLookupKernelUserEntryPoints(), PspUserThreadStartup(), WmipDriverEntry(), and WmipEnableDisableTrace().
#define SYNCH_LEVEL (IPI_LEVEL-2)
Definition at line 182 of file i386.h.
Referenced by KeAcquireInStackQueuedSpinLockRaiseToSynch(), KeAcquireQueuedSpinLockRaiseToSynch(), KeAcquireSpinLockRaiseToSynch(), KeConnectInterrupt(), KeDisconnectInterrupt(), KeIpiGenericCall(), KeTryToAcquireQueuedSpinLockRaiseToSynch(), KiAcquireDispatcherLockRaiseToSynch(), KiExitDispatcher(), KiInitMachineDependent(), KiTryToAcquireDispatcherLockRaiseToSynch(), RtlLookupFunctionTable(), and RtlPcToFileHeader().
#define TYPE_CODE 0x10
Definition at line 868 of file i386.h.
#define TYPE_DATA 0x12
Definition at line 869 of file i386.h.
Referenced by KeI386FlatToGdtSelector(), and KiInitializeAbios().
#define TYPE_LDT 0x02
Definition at line 871 of file i386.h.
Referenced by Ke386SetLdtProcess().
#define TYPE_TSS 0x01
Definition at line 870 of file i386.h.
Typedef Documentation
typedef HARDWARE_PTE_X86 HARDWARE_PTE
Definition at line 831 of file i386.h.
typedef struct _HARDWARE_PTE_X86 HARDWARE_PTE_X86
typedef struct _HARDWARE_PTE_X86PAE HARDWARE_PTE_X86PAE
typedef enum _INTERLOCKED_RESULT INTERLOCKED_RESULT
typedef struct _KCALLOUT_FRAME KCALLOUT_FRAME
typedef struct _DESCRIPTOR KDESCRIPTOR
typedef struct _KDPC_DATA KDPC_DATA
typedef struct _KFLOATING_SAVE KFLOATING_SAVE
typedef struct _KGDTENTRY KGDTENTRY
typedef struct _KIDTENTRY KIDTENTRY
typedef struct _KiIoAccessMap KIIO_ACCESS_MAP
typedef UCHAR KINT_DIRECTION_MAP[INT_DIRECTION_MAP_SIZE]
Definition at line 919 of file i386.h.
typedef UCHAR KIO_ACCESS_MAP[IOPM_SIZE]
Definition at line 932 of file i386.h.
typedef struct _KNONVOLATILE_CONTEXT_POINTERS KNONVOLATILE_CONTEXT_POINTERS
typedef struct _KPCR KPCR
typedef struct _KPRCB KPRCB
typedef struct _KPROCESSOR_STATE KPROCESSOR_STATE
typedef struct _KSPECIAL_REGISTERS KSPECIAL_REGISTERS
typedef struct _KSWITCHFRAME KSWITCHFRAME
typedef struct _KTRAP_FRAME KTRAP_FRAME
typedef struct _KTSS KTSS
typedef struct _LDTINFORMATION LDTINFORMATION
typedef ULONG PFN_COUNT
Definition at line 53 of file i386.h.
typedef ULONG PFN_NUMBER
Definition at line 56 of file i386.h.
typedef PHARDWARE_PTE_X86 PHARDWARE_PTE
Definition at line 832 of file i386.h.
typedef struct _HARDWARE_PTE_X86 * PHARDWARE_PTE_X86
typedef struct _HARDWARE_PTE_X86PAE * PHARDWARE_PTE_X86PAE
typedef KCALLOUT_FRAME* PKCALLOUT_FRAME
Definition at line 1773 of file i386.h.
typedef struct _DESCRIPTOR * PKDESCRIPTOR
typedef struct _KDPC_DATA * PKDPC_DATA
typedef KTRAP_FRAME* PKEXCEPTION_FRAME
Definition at line 1740 of file i386.h.
typedef struct _KFLOATING_SAVE * PKFLOATING_SAVE
typedef struct _KGDTENTRY * PKGDTENTRY
typedef KIDTENTRY* PKIDTENTRY
Definition at line 899 of file i386.h.
typedef KIO_ACCESS_MAP* PKIO_ACCESS_MAP
Definition at line 934 of file i386.h.
typedef struct _KNONVOLATILE_CONTEXT_POINTERS * PKNONVOLATILE_CONTEXT_POINTERS
typedef struct _KPCR * PKPCR
typedef struct _KPRCB * PKPRCB
typedef struct _KPROCESSOR_STATE * PKPROCESSOR_STATE
typedef struct _KSPECIAL_REGISTERS * PKSPECIAL_REGISTERS
typedef struct _KSWITCHFRAME * PKSWITCHFRAME
typedef KTRAP_FRAME* PKTRAP_FRAME
Definition at line 1739 of file i386.h.
typedef struct _KTSS * PKTSS
typedef struct _LDTINFORMATION * PLDTINFORMATION
typedef ULONG * PPFN_NUMBER
Definition at line 56 of file i386.h.
typedef struct _PROCESS_IO_PORT_HANDLER_INFORMATION * PPROCESS_IO_PORT_HANDLER_INFORMATION
typedef struct _KPRCB PRKPRCB
typedef struct _PROCESS_IO_PORT_HANDLER_INFORMATION PROCESS_IO_PORT_HANDLER_INFORMATION
typedef LONG * PSPFN_NUMBER
Definition at line 55 of file i386.h.
typedef struct _VDM_IO_HANDLER * PVDM_IO_HANDLER
typedef struct _VDM_IO_HANDLER_FUNCTIONS * PVDM_IO_HANDLER_FUNCTIONS
typedef LONG SPFN_NUMBER
Definition at line 55 of file i386.h.
typedef struct _VDM_IO_HANDLER VDM_IO_HANDLER
typedef struct _VDM_IO_HANDLER_FUNCTIONS VDM_IO_HANDLER_FUNCTIONS
Enumeration Type Documentation
enum _INTERLOCKED_RESULT
Enumerator
ResultNegative
ResultZero
ResultPositive
Definition at line 2064 of file i386.h.
Function Documentation
void __cdecl _disable (void)
Referenced by KiProcessorStart(), KiRetireDpcList(), and KiTimerExpiration().
void __cdecl _enable (void)
Referenced by ExpInitializeExecutive(), KeEnableInterrupts(), KiInitializeKernel(), KiRetireDpcList(), and KiTimerExpiration().
VOID _ReadWriteBarrier (VOID)
C_ASSERT (((FIELD_OFFSET(KPRCB, LockQueue)+sizeof(KSPIN_LOCK_QUEUE)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, NpxThread)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, CcFastReadNoWait)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PPLookasideList)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PPNPagedLookasideList)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PPPagedLookasideList)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, PacketBarrier)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, CurrentPacket)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, DpcData)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, DpcRoutineActive))&(1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, CallDpc)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, WaitListHead)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, ChainedInterruptList)+32)&(64-1)) = =0)
C_ASSERT (((FIELD_OFFSET(KPRCB, NpxSaveArea)+32)&(16-1)) = =0)
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.ExceptionList) = =FIELD_OFFSET(KPCR, Used_ExceptionList))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.StackBase) = =FIELD_OFFSET(KPCR, Used_StackBase))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.StackLimit) = =FIELD_OFFSET(KPCR, PerfGlobalGroupMask))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.SubSystemTib) = =FIELD_OFFSET(KPCR, TssCopy))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.FiberData) = =FIELD_OFFSET(KPCR, ContextSwitches))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.ArbitraryUserPointer) = =FIELD_OFFSET(KPCR, SetMemberCopy))
C_ASSERT (FIELD_OFFSET(KPCR, NtTib.Self) = =FIELD_OFFSET(KPCR, Used_Self))
C_ASSERT ((FIELD_OFFSET(KPCR, PrcbData)&(64-1)) = =32)
C_ASSERT (sizeof(BOOLEAN) = =sizeof(UCHAR))
C_ASSERT ((((ULONG) DR_VALID_MASK)&~((ULONG)((UCHAR) 0xFF))) = =0)
C_ASSERT ((DR7_ACTIVE &DR7_OVERRIDE_MASK) = =0)
C_ASSERT ((DR7_RESERVED_MASK &DR7_OVERRIDE_MASK) = =0)
C_ASSERT ((DR7_OVERRIDE_MASK &DR7_LEGAL) = =DR7_OVERRIDE_MASK)
C_ASSERT ((DR7_RESERVED_MASK &DR7_LEGAL) = =0)
VOID NTAPI CPUID (ULONG InEax, PULONG OutEax, PULONG OutEbx, PULONG OutEcx, PULONG OutEdx)
Referenced by KiGetCacheInformation(), KiGetCpuVendor(), KiGetFeatureBits(), KiInitMachineDependent(), and KiProcessorStart().
NTKERNELAPI INTERLOCKED_RESULT FASTCALL Exfi386InterlockedDecrementLong (IN PLONG Addend)
NTKERNELAPI ULONG FASTCALL Exfi386InterlockedExchangeUlong (IN PULONG Target, IN ULONG Value)
NTKERNELAPI INTERLOCKED_RESULT FASTCALL Exfi386InterlockedIncrementLong (IN PLONG Addend)
NTKERNELAPI LONGLONG FASTCALL ExfInterlockedCompareExchange64 (IN OUT LONGLONG volatile * Destination, IN PLONGLONG ExChange, IN PLONGLONG Comperand)
FORCEINLINE LONG InterlockedAnd (IN OUT LONG volatile * Target, LONG Set)
Definition at line 2519 of file i386.h.
References InterlockedCompareExchange().
Referenced by ExfWakePushLock(), KiClearIdleSummary(), KiClearSMTSummary(), KiReleaseKobjectLock(), KiReleasePrcbLock(), and KiReleaseThreadLock().
FORCEINLINE LONG FASTCALL InterlockedCompareExchange (IN OUT LONG volatile * Destination, IN LONG Exchange, IN LONG Comperand)
Definition at line 2411 of file i386.h.
Referenced by CmpAddToDelayedClose(), CmpDelayDerefKeyControlBlock(), CmpDereferenceKeyControlBlock(), CmpRemoveFromDelayedClose(), ExpAllocateHandleTableEntry(), ExpAllocateHandleTableEntrySlow(), ExpFreeHandleTableEntry(), ExpInsertPoolTrackerInline(), ExpInterlockedExchange(), ExpMoveFreeHandles(), ExpWorkerThread(), InterlockedAnd(), InterlockedOr(), KeBalanceSetManager(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), KeSwapProcessOrStack(), KiAcquireFastMutex(), KiAcquireGuardedMutex(), KiAcquireKobjectLock(), KiAcquireQueuedSpinLockCheckForFreeze(), KiSendFreeze(), KiSetTbFlushTimeStampBusy(), MiChargeCommitment(), MiChargeCommitmentCantExpand(), MiChargeTemporaryCommitmentForReduction(), MiFreeLargePageMemory(), MiIssuePageExtendRequestNoWait(), MiReleaseSystemPtes(), MiSessionCreateInternal(), MiUpdateWsle(), MiWriteComplete(), MmAdvanceMdl(), MmFreePagesFromMdl(), MmLoadSystemImage(), MmLockPageableSectionByHandle(), MmSessionCreate(), MmUnlockPages(), NtQueryInformationProcess(), ObDereferenceSecurityDescriptor(), ObpAuditObjectAccess(), ObpSafeInterlockedIncrementLong(), ObpTryReferenceNameInfoExclusive(), PspInterlockedCompareExchangeQuota(), PspUserThreadStartup(), RtlInterlockedSetClearBits(), RtlpLogExceptionHandler(), SepDeReferenceLogonSessionDirect(), WmipStartLogger(), WmipStopLoggerInstance(), WmipTraceIo(), WmiTraceEvent(), WmiUpdateTrace(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
FORCEINLINE LONG FASTCALL InterlockedExchange (IN OUT LONG volatile * Target, IN LONG Value)
Definition at line 2328 of file i386.h.
Referenced by ExpMoveFreeHandles(), IopAcquireFastLock(), IopAcquireFileObjectLock(), IopAllocateReserveIrp(), IopDeleteFile(), IopFreeReserveIrp(), KeInsertQueueDpc(), KeSignalCallDpcSynchronize(), KiQuantumEnd(), KzAcquireSpinLock(), KzTryToAcquireSpinLock(), MiExtendPagingFiles(), MiPteSListExpansionWorker(), PspInterlockedExchangeQuota(), WmipDeregisterDevice(), WmipLogger(), WmipMceWorkerRoutine(), WmipStartLogger(), WmipStopLoggerInstance(), and WmiUpdateTrace().
FORCEINLINE LONG FASTCALL InterlockedExchangeAdd (IN OUT LONG volatile * Addend, IN LONG Increment)
Definition at line 2382 of file i386.h.
Referenced by __bcount(), CmpClaimGlobalQuota(), CmpReleaseGlobalQuota(), CmRegisterCallback(), CmUnRegisterCallback(), ExDeferredFreePool(), ExDereferenceHandleDebugInfo(), ExEnableHandleTracing(), ExFreePoolWithTag(), ExpAllocateHandleTableEntrySlow(), ExReleasePushLockExclusive(), ExReleaseRundownProtectionEx(), ExWaitForRundownProtectionReleaseCacheAware(), IoFreeErrorLogEntry(), IopAllocateErrorLogEntry(), IopErrorLogThread(), IoWriteErrorLogEntry(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), KiAdjustIrpCredits(), KiPollFreezeExecution(), MiAllocatePoolPages(), MiCcPutPagesInTransition(), MiDispatchFault(), MiFindContiguousMemoryInPool(), MiFreePoolPages(), MiGatherPagefilePages(), MiLoadImageSection(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiSetPagingOfDriver(), MiUseLargeDriverPage(), MmCreateKernelStack(), MmDeleteKernelStack(), MmFreeDriverInitialization(), MmUnloadSystemImage(), ObDereferenceSecurityDescriptor(), ObLogSecurityDescriptor(), ObpDeleteNameCheck(), ObpReferenceSecurityDescriptor(), ObpReleaseExclusiveNameLock(), ObReferenceSecurityDescriptor(), PspInterlockedAddQuota(), PspInterlockedSubtractQuota(), SepModifyTokenPolicyCounter(), WmipReserveTraceBuffer(), xxReleaseFastMutex(), and xxReleaseFastMutexUnsafe().
FORCEINLINE LONG InterlockedOr (IN OUT LONG volatile * Target, IN LONG Set)
Definition at line 2541 of file i386.h.
References InterlockedCompareExchange().
Referenced by ExpFindAndRemoveTagBigPages(), ExUnlockHandleTableEntry(), KiSetIdleSummary(), KiSetSMTSummary(), and MmLoadSystemImage().
NTSTATUS NTAPI Ke386CallBios (IN ULONG BiosCommand, IN OUT PCONTEXT BiosArguments)
Definition at line 52 of file biosc.c.
References _KTHREAD::ApcState, ASSERT, CONTEXT_FULL, _DISPATCHER_HEADER::DebugActive, EFLAGS_INTERRUPT_MASK, EFLAGS_V86_MASK, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FIELD_OFFSET, _KTHREAD::Header, INT_10_TEB, INT_OPCODE, _KiIoAccessMap::IoMap, _KTSS::IoMapBase, _KTSS::IoMaps, IOPM_OFFSET, _KPROCESS::IopmOffset, KeGetCurrentThread(), KeGetPcr(), KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), KGDT_TSS, Ki386IopmSaveArea, Ki386SetupAndExitToV86Code(), NonPagedPool, NULL, PAGE_SIZE, _KAPC_STATE::Process, PS_CLEAR_BITS, PS_PROCESS_FLAGS_VDM_ALLOWED, PS_SET_BITS, PsGetCurrentProcess(), RtlCopyMemory, RtlZeroMemory, STATUS_NO_MEMORY, STATUS_SUCCESS, _KPCR::TSS, V86_BOP_OPCODE, V86_CODE_ADDRESS, VDM_TIB_ADDRESS, and _EPROCESS::VdmObjects.
VOID NTAPI Ke386GetGdtEntryThread (struct _KTHREAD * Thread, ULONG Offset, PKGDTENTRY Descriptor)
Referenced by PspQueryDescriptorThread().
BOOLEAN NTAPI Ke386IoSetAccessProcess (struct _KPROCESS * Process, ULONG MapNumber)
BOOLEAN NTAPI Ke386QueryIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
Definition at line 192 of file iopm.c.
References DISPATCH_LEVEL, FALSE, IO_ACCESS_MAP_NONE, IOPM_COUNT, IOPM_SIZE, KeLowerIrql, KeRaiseIrql, KiPcr, RtlCopyMemory, and TRUE.
VOID NTAPI Ke386SetDescriptorProcess (struct _KPROCESS * Process, ULONG Offset, LDT_ENTRY LdtEntry)
Referenced by PspSetLdtInformation(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
BOOLEAN NTAPI Ke386SetIoAccessMap (ULONG MapNumber, PKIO_ACCESS_MAP IoAccessMap)
Definition at line 76 of file iopm.c.
References _KTHREAD::ApcState, FALSE, IO_ACCESS_MAP_NONE, IOPM_COUNT, KeGenericCallDpc(), KeGetCurrentThread(), KiSetIoMap(), _MAPINFO::MapNumber, _MAPINFO::MapSource, _MAPINFO::Process, _KAPC_STATE::Process, and TRUE.
VOID NTAPI Ke386SetIOPL (VOID)
Definition at line 394 of file iopm.c.
References ALIGN_UP, _KTHREAD::ApcState, CONTEXT_CONTROL, _CONTEXT::ContextFlags, _CONTEXT::EFlags, EFLAGS_IOPL_MASK, _KTHREAD::InitialStack, _KPROCESS::Iopl, _KTHREAD::Iopl, KeContextFromKframes(), KeContextToKframes(), KeGetCurrentThread(), KTRAP_FRAME_ALIGN, NULL, _KAPC_STATE::Process, and UserMode.
Referenced by NtSetInformationProcess().
VOID NTAPI Ke386SetLdtProcess (struct _KPROCESS * Process, PLDT_ENTRY Ldt, ULONG Limit)
Referenced by PspSetLdtInformation(), PspSetLdtSize(), PsSetLdtEntries(), and PsSetProcessLdtInfo().
NTSTATUS NTAPI Ke386SetVdmInterruptHandler (IN struct _KPROCESS * Process, IN ULONG Interrupt, IN USHORT Selector, IN ULONG Offset, IN BOOLEAN Gate32)
BOOLEAN KeDisableInterrupts (VOID)
Referenced by KeBugCheck2(), KeEnterKernelDebugger(), KeFreezeExecution(), KeRemoveQueueDpc(), KiCalibrateTimeAdjustment(), KiFreezeTargetExecution(), KiI386PentiumLockErrataFixup(), KiLoadMTRR(), and KiLoadPAT().
NTKERNELAPI VOID KeFlushCurrentTb (VOID)
Referenced by KeThawExecution(), KiFlushTargetEntireTb(), KiFreezeTargetExecution(), KiInitializeKernel(), KiIpiProcessRequests(), and KxFlushEntireTb().
FORCEINLINE ULONG KeGetContextSwitches (PKPRCB Prcb)
Definition at line 1464 of file i386.h.
References CONTAINING_RECORD, and _KPCR::ContextSwitches.
Referenced by NtQuerySystemInformation().
NTHALAPI KIRQL NTAPI KeGetCurrentIrql ()
Referenced by __bcount(), CcDereferenceFileOffset(), CcGetVirtualAddress(), CcGetVirtualAddressIfMapped(), CcPerfFileRunDown(), CcReferenceFileOffset(), ExAllocatePoolSanityChecks(), ExCreatePoolTagTable(), ExDeletePoolTagTable(), ExFreePoolSanityChecks(), ExGetBigPoolInfo(), ExGetPoolTagInfo(), ExGetSessionPoolTagInfo(), ExpGetPoolTagInfoTarget(), ExpLockHandleTableEntry(), ExpWorkerThread(), ExRegisterCallback(), ExReleaseSpinLockExclusive(), ExReleaseSpinLockShared(), ExTryAcquireSpinLockExclusive(), ExUnlockHandleTableEntry(), ExUnregisterCallback(), FsRtlCreateSectionForDataScan(), FsRtlWorkerThread(), IoGetStackLimits(), IoQueueWorkItem(), IoVolumeDeviceToDosName(), KeAcquireGuardedMutex(), KeAcquireGuardedMutexUnsafe(), KeAlertResumeThread(), KeAlertThread(), KeAreAllApcsDisabled(), KeAttachProcess(), KeBoostPriorityThread(), KeBugCheck2(), KeCancelTimer(), KeContextFromKframes(), KeContextToKframes(), KeDeregisterNmiCallback(), KeDetachProcess(), KeEnterGuardedRegionThread(), KeFlushQueueApc(), KeForceAttachProcess(), KeForceResumeThread(), KeFreezeAllThreads(), KeFreezeExecution(), KeGenericCallDpc(), KeInsertHeadQueue(), KeInsertQueue(), KeInsertQueueApc(), KeIpiGenericCall(), KeLeaveGuardedRegionThread(), KePulseEvent(), KeQueryBasePriorityThread(), KeQueryRuntimeProcess(), KeQueryValuesProcess(), KeReadyThread(), KeRegisterNmiCallback(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), KeReleaseMutant(), KeReleaseSemaphore(), KeRemoveEntryDeviceQueue(), KeRemoveQueueApc(), KeResetEvent(), KeRestoreFloatingPointState(), KeResumeThread(), KeRevertToUserAffinityThread(), KeRundownQueue(), KeRundownThread(), KeSaveFloatingPointState(), KeSetAffinityProcess(), KeSetAffinityThread(), KeSetBasePriorityThread(), KeSetEvent(), KeSetEventBoostPriority(), KeSetPhysicalCacheTypeRange(), KeSetPriorityAndQuantumProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeSetProcess(), KeSetQuantumProcess(), KeSetSystemAffinityThread(), KeSetSystemTime(), KeSetTimerEx(), KeSignalGateBoostPriority(), KeStackAttachProcess(), KeStartProfile(), KeStopProfile(), KeSuspendThread(), KeTerminateThread(), KeTestAlertThread(), KeThawAllThreads(), KeTryToAcquireGuardedMutex(), KeUnstackDetachProcess(), KeWaitForGate(), Ki386CheckDelayedNpxTrap(), Ki386CheckDivideByZeroTrap(), KiAcquireInStackQueuedSpinLockForDpc(), KiAcquireKobjectLock(), KiAcquirePrcbLock(), KiAcquireSpinLockForDpc(), KiAcquireThreadLock(), KiAcquireTimerTableLock(), KiAcquireTwoPrcbLocks(), KiAmdK6MtrrSetMemoryType(), KiCheckForKernelApcDelivery(), KiCompleteEffectiveRangeChange(), KiContinue(), KiContinueEx(), KiDeliverApc(), KiEspToTrapFrame(), KiExecuteDpc(), KiExitDispatcher(), KiIpiSendPacket(), KiIpiSendRequest(), KiLockStepOtherProcessors(), KiOpPatchCode(), KiPreprocessInvalidOpcodeFault(), KiReleaseInStackQueuedSpinLockForDpc(), KiReleaseKobjectLock(), KiReleasePrcbLock(), KiReleaseSpinLockForDpc(), KiReleaseThreadLock(), KiReleaseTimerTableLock(), KiReleaseTwoPrcbLocks(), KiRetireDpcList(), KiStartProfileInterrupt(), KiStopProfileInterrupt(), KiTryToAcquireThreadLock(), MiAddViewsForSectionWithPfn(), MiAllocateContiguousMemory(), MiAllocatePagesForMdl(), MiAttachAndLockWorkingSet(), MiAttemptPageFileExtension(), MiAttemptPageFileReduction(), MiCcCompletePrefetchIos(), MiCcPrepareReadInfo(), MiCcPutPagesInTransition(), MiCheckCacheAttributes(), MiDeleteSystemPageableVm(), MiDereferenceSegmentThread(), MiDetachAndUnlockWorkingSet(), MiDispatchFault(), MiFlushComplete(), MiFlushSectionInternal(), MiFreeContiguousPages(), MiFreeEventCounter(), MiFreeInPageSupportBlock(), MiGetEventCounter(), MiGetInPageSupportBlock(), MiInsertIoSpaceMap(), MiInsertPteTracker(), MiMapPageInHyperSpaceAtDpc(), MiMapPagesToZeroInHyperSpace(), MiPteSListExpansionWorker(), MiQueueWorkingSetRequest(), MiRemoveViewsFromSectionWithPfn(), MiSessionPoolBigPageTable(), MiSessionPoolBigPageTableSize(), MiSessionPoolLookaside(), MiSessionPoolTrackTable(), MiSessionPoolTrackTableSize(), MiSetSystemCodeProtection(), MiSnapCopyMemory(), MiTrimAllSystemPageableMemory(), MiTrimPte(), MiUnmapPagesInZeroSpace(), MiUpdateSystemPdes(), MiUseLargeDriverPage(), MmAccessFault(), MmAdvanceMdl(), MmAttachSession(), MmAvailablePoolInPages(), MmCopyToCachedPage(), MmDetachSession(), MmFreeBootRegistry(), MmFreeIndependentPages(), MmFreeMappingAddress(), MmFreePagesFromMdl(), MmGetDirectoryFrameFromProcess(), MmGetExecuteOptions(), MmGetFileObjectForSection(), MmGetNextSession(), MmGetPreviousSession(), MmGetSessionById(), MmGetSystemRoutineAddress(), MmIdentifyPhysicalMemory(), MmIsMemoryAvailable(), MmMapLockedPagesWithReservedMapping(), MmMapViewInSystemCache(), MmPerfSnapShotValidPhysicalMemory(), MmPerfUnusedSegmentsEnumerate(), MmPerfVadTreeWalk(), MmPrefetchPagesIntoLockedMdl(), MmProtectMdlSystemAddress(), MmPurgeSection(), MmQuerySystemCacheWorkingSetInformation(), MmQueryWorkingSetInformation(), MmQuitNextSession(), MmSetExecuteOptions(), MmSetPageProtection(), MmUnlockPages(), MmUnmapReservedMapping(), MmUnmapViewInSystemCache(), NtAllocateUserPhysicalPages(), NtCreateSection(), NtFreeUserPhysicalPages(), NtGetWriteWatch(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtReleaseKeyedEvent(), NtResetWriteWatch(), NtSetSystemInformation(), NtWaitForKeyedEvent(), ObfDereferenceObject(), PspExitThread(), PspTerminateThreadByPointer(), RtlCaptureStackContext(), RtlDispatchException(), RtlLookupFunctionTable(), RtlpCaptureStackLimits(), RtlPcToFileHeader(), RtlpGetStackLimits(), RtlUnwind(), RtlWalkFrameChain(), SepCreateToken(), SepDuplicateToken(), SepFilterToken(), WmipReleaseTraceBuffer(), WmipSwitchBuffer(), WmiTraceEvent(), xxAcquireFastMutex(), xxAcquireFastMutexUnsafe(), xxReleaseFastMutex(), xxReleaseFastMutexUnsafe(), and xxTryToAcquireFastMutex().
FORCEINLINE ULONG KeGetCurrentNodeShiftedColor (VOID)
Definition at line 2667 of file i386.h.
References FIELD_OFFSET.
FORCEINLINE PKPRCB NTAPI KeGetCurrentPrcb (VOID)
Definition at line 2685 of file i386.h.
References _PCR, FIELD_OFFSET, and _KPCR::Prcb.
Referenced by __bcount(), ExAllocateFromPPLookasideList(), ExFreePoolWithTag(), ExFreeToPPLookasideList(), ExGetCurrentProcessorCounts(), ExGetCurrentProcessorCpuUsage(), ExInitPoolLookasidePointers(), ExpGetProcessorIdleInformation(), ExpGetProcessorPowerInformation(), ExpScanSystemLookasideList(), ExpSystemErrorHandler(), IoGetStackLimits(), IoMakeAssociatedIrp(), IopAllocateIrpPrivate(), IopFreeIrp(), IopFreeMiniPacket(), IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IopUpdateReadOperationCount(), IopUpdateReadTransferCount(), IopUpdateWriteOperationCount(), IopUpdateWriteTransferCount(), IoSetIoCompletion(), KeBugCheck2(), KeDelayExecutionThread(), KeFlushMultipleTb(), KeFlushProcessTb(), KeFlushQueuedDpcs(), KeFlushSingleTb(), KeFreezeExecution(), KeGenericCallDpc(), KeInitializeInterrupt(), KeInsertQueueDpc(), KeInvalidateAllCaches(), KeIpiGenericCall(), KeQueryCurrentStackInformation(), KeRemoveQueue(), KeRestoreFloatingPointState(), KeRevertToUserAffinityThread(), KeSaveFloatingPointState(), KeSetSystemAffinityThread(), KeSignalGateBoostPriority(), KeStartAllProcessors(), KeStartProfile(), KeStopProfile(), KeSwitchFrozenProcessor(), KeTerminateThread(), KeTestForWaitersQueuedSpinLock(), KeUpdateRunTime(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), KiAcquireInStackQueuedSpinLockForDpc(), KiAcquireQueuedSpinLockCheckForFreeze(), KiAcquireSpinLockForDpc(), KiAdjustQuantumThread(), KiAttachProcess(), KiCalibrateTimeAdjustment(), KiCheckForFreezeExecution(), KiCompleteEffectiveRangeChange(), KiDeferredReadyThread(), KiDispatchException(), KiExitDispatcher(), KiFreezeTargetExecution(), KiGetCpuVendor(), KiGetFeatureBits(), KiIdleSchedule(), KiInitializeBootStructures(), KiInitializeMTRR(), KiInitializePAT(), KiInitMachineDependent(), KiInsertDeferredReadyList(), KiIpiProcessRequests(), KiIpiSendRequest(), KiIpiSignalPacketDone(), KiIpiStallOnPacketTargets(), KiIpiStallOnPacketTargetsPrcb(), KiLoadFastSyscallMachineSpecificRegisters(), KiLockStepExecution(), KiLockStepOtherProcessors(), KiPollFreezeExecution(), KiProcessNMI(), KiProcessTimerDpcTable(), KiQuantumEnd(), KiReleaseInStackQueuedSpinLockForDpc(), KiReleaseSpinLockForDpc(), KiRestoreProcessorState(), KiSaveProcessorState(), KiSendThawExecution(), KiSetCacheInformation(), KiSetCacheInformationAmd(), KiSetCacheInformationIntel(), KiSetCpuVendor(), KiSetProcessorType(), KiSwapProcess(), KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), KiTimerExpiration(), KiTimerListExpire(), KxFlushEntireTb(), KxQueueReadyThread(), MiAllocatePagesForMdl(), MiAllocateWsle(), MiCcPutPagesInTransition(), MiComputeInitialLargePage(), MiCopyOnWrite(), MiDispatchFault(), MiFindLargePageMemory(), MiGatherMappedPages(), MiGatherPagefilePages(), MiInitMachineDependent(), MiResolveDemandZeroFault(), MiResolveMappedFileFault(), MiResolvePageFileFault(), MiResolveProtoPteFault(), MiResolveTransitionFault(), MmAccessFault(), MmGetNodeColor(), NtQueryInformationProcess(), NtYieldExecution(), ObInitSystem(), PspUserThreadStartup(), RtlDispatchException(), RtlUnwind(), and WmipConstructMCAErrorEvent().
FORCEINLINE ULONG NTAPI KeGetCurrentProcessorNumber (VOID)
Definition at line 2727 of file i386.h.
References _PCR, FIELD_OFFSET, and _KPCR::Number.
Referenced by ExAcquireCacheAwarePushLockShared(), EXP_GET_CURRENT_RUNDOWN_REF(), ExpInsertPoolTrackerInline(), ExpRemovePoolTrackerExpansion(), ExpRemovePoolTrackerInline(), KeGenericCallDpc(), KiOpPatchCode(), KiOpSingleProcCopy(), KiSendThawExecution(), MmProbeAndLockPages(), MmProbeAndLockSelectedPages(), NtGetCurrentProcessorNumber(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), WmipReserveTraceBuffer(), and WmiTraceContextSwap().
FORCEINLINE struct _KTHREAD* NTAPI KeGetCurrentThread (VOID)
Definition at line 2748 of file i386.h.
References _KPRCB::CurrentThread, FIELD_OFFSET, and _KPCR::PrcbData.
Referenced by CmLoadKey(), CmpCreateKeyControlBlock(), CmpDoOpen(), CmpTryConvertKCBLockSharedToExclusive(), CmpTryToLockHashEntryByIndexExclusive(), ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExChangeHandle(), ExCompareExchangeCallBack(), ExCreateHandleTable(), ExDisableHandleTracing(), ExDupHandleTable(), ExEnableHandleTracing(), ExEnumHandleTable(), ExpAllocateHandleTableEntry(), ExpExpandResourceOwnerTable(), ExpFindCurrentThread(), ExpFindEmptyEntry(), ExpFreeHandleTableEntry(), ExpLockHandleTableEntry(), ExpShutdownWorkerThreads(), ExpWaitForResource(), ExpWorkerThreadBalanceManager(), ExReferenceCallBackBlock(), ExReferenceHandleDebugInfo(), ExReleaseResourceForThreadLite(), ExReleaseResourceLite(), ExRemoveHandleTable(), ExSetHandleInfo(), ExSnapShotHandleTables(), ExSnapShotHandleTablesEx(), ExUnlockHandleTableEntry(), ExUuidCreate(), IoCreateFile(), IopBootLogToFile(), IopCopyBootLogRegistryToFile(), IopInvalidateVolumesForDevice(), IopSetDeviceSecurityDescriptor(), IopUpdateOtherOperationCount(), IopUpdateOtherTransferCount(), IopUpdateReadOperationCount(), IopUpdateReadTransferCount(), IopUpdateWriteOperationCount(), IopUpdateWriteTransferCount(), Ke386CallBios(), Ke386SetIoAccessMap(), Ke386SetIOPL(), KeAcquireGuardedMutex(), KeAcquireGuardedMutexUnsafe(), KeAcquireSpinLockEx(), KeAreAllApcsDisabled(), KeAreApcsDisabled(), KeAttachProcess(), KeBalanceSetManager(), KeBugCheck2(), KeCheckIfStackExpandCalloutActive(), KeContextToKframes(), KeDelayExecutionThread(), KeDetachProcess(), KeEnterCriticalRegion(), KeEnterCriticalRegionThread(), KeEnterGuardedRegion(), KeEnterGuardedRegionThread(), KeFlushQueuedDpcs(), KeForceAttachProcess(), KeFreezeAllThreads(), KeInitializeMutant(), KeLeaveCriticalRegion(), KeLeaveCriticalRegionThread(), KeLeaveGuardedRegion(), KeLeaveGuardedRegionThread(), KePulseEvent(), KeQueryCurrentStackInformation(), KeRaiseUserException(), KeReleaseGuardedMutex(), KeReleaseGuardedMutexUnsafe(), KeReleaseMutant(), KeReleaseSemaphore(), KeRemoveQueue(), KeRestoreFloatingPointState(), KeRevertToUserAffinityThread(), KeRundownThread(), KeSaveFloatingPointState(), KeSetEvent(), KeSetEventBoostPriority(), KeSetKernelStackSwapEnable(), KeSetPriorityZeroPageThread(), KeSetProcess(), KeSetSystemAffinityThread(), KeSignalGateBoostPriority(), KeStackAttachProcess(), KeSwapProcessOrStack(), KeTerminateThread(), KeTestAlertThread(), KeThawAllThreads(), KeTryToAcquireGuardedMutex(), KeUnstackDetachProcess(), KeUpdateRunTime(), KeUserModeCallback(), KeWaitForGate(), KeWaitForMultipleObjects(), KeWaitForSingleObject(), Ki386CheckDelayedNpxTrap(), KiCheckForKernelApcDelivery(), KiContinueEx(), KiDeliverApc(), KiExecuteDpc(), KiInitializeUserApc(), KiInitMachineDependent(), KiInsertQueue(), KiInsertQueueApc(), KiOp_MOVAPS(), KiOp_MOVDQA(), KiOpPatchCode(), KiOpPreprocessAccessViolation(), KiProcessDebugRegister(), KiQuantumEnd(), KiRecordDr7(), KiSuspendThread(), KiUpdateDr7(), KxAcquireSpinLock(), KxContextToKframes(), KxReleaseSpinLock(), KxTryToAcquireSpinLock(), KxWaitForSpinLockAndAcquire(), MiAllocatePagesForMdl(), MiCheckControlAreaStatus(), MiCheckPurgeAndUpMapCount(), MiDereferenceSessionFinal(), MiFindContiguousPages(), MiFindInitializationCode(), MiFindLargePageMemory(), MiFreeLargePageMemory(), MiLoadUserSymbols(), MiLookupDataTableEntry(), MiModifiedPageWriter(), MiProtectVirtualMemory(), MiRemoveUserPhysicalPagesVad(), MiSnapPagefileWrite(), MiUnlinkWorkingSet(), MiZeroAwePageWorker(), MiZeroPageWorker(), MmAccessFault(), MmExtendSection(), MmGatherMemoryForHibernate(), MmGetSectionRange(), MmGetSystemRoutineAddress(), MmGrowKernelStackEx(), MmIdentifyPhysicalMemory(), MmLoadSystemImage(), MmLockPageableDataSection(), MmLockPageableSectionByHandle(), MmPerfSnapShotValidPhysicalMemory(), MmUnloadSystemImage(), MmUnlockPageableImageSection(), MmZeroPageThread(), NtAllocateUuids(), NtNotifyChangeMultipleKeys(), NtQueryMutant(), NtYieldExecution(), ObAuditObjectAccess(), ObDuplicateObject(), ObKillProcess(), ObpCreateHandle(), Phase1InitializationDiscard(), PsGetCurrentThreadStackBase(), PsGetCurrentThreadStackLimit(), PspSetContext(), RtlpCaptureStackLimits(), RtlpGetStackLimits(), RtlpTraceDatabaseAcquireLock(), RtlWalkFrameChain(), WmipLogger(), WmipStartLogger(), WmiStopContextSwapTrace(), WmiUpdateTrace(), xxAcquireFastMutex(), xxAcquireFastMutexUnsafe(), xxReleaseFastMutex(), xxReleaseFastMutexUnsafe(), and xxTryToAcquireFastMutex().
FORCEINLINE PKPCR NTAPI KeGetPcr (VOID)
Definition at line 2645 of file i386.h.
References _PCR, FIELD_OFFSET, KIP0PCRADDRESS, and _KPCR::SelfPcr.
Referenced by Ke386CallBios(), KeContextToKframes(), KeSetup80387OrEmulate(), KeStartAllProcessors(), KiClearBusyBitInTssDescriptor(), KiGetCacheInformation(), KiI386PentiumLockErrataFixup(), KiInitializeBootStructures(), KiInitializeKernel(), KiInitializeMTRR(), KiInitSpinLocks(), KiSetCacheInformation(), KiSetHaltedNmiandDoubleFaultHandler(), MiComputeInitialLargePage(), MiInitMachineDependent(), and RtlpCaptureStackLimits().
NTSTATUS NTAPI KeI386AbiosCall (IN USHORT LogicalId, IN struct _DRIVER_OBJECT * DriverObject, IN PUCHAR RequestBlock, IN USHORT EntryPoint)
NTSTATUS NTAPI KeI386AllocateGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
Definition at line 446 of file abiosc.c.
References ExAcquireSpinLock, ExReleaseSpinLock, _KFREE_GDT_ENTRY::Flink, KiAbiosGdt, KiAbiosGdtLock, KiFreeGdtListHead, KiNumberFreeSelectors, STATUS_ABIOS_SELECTOR_NOT_AVAILABLE, and STATUS_SUCCESS.
USHORT NTAPI KeI386Call16BitCStyleFunction (IN ULONG EntryOffset, IN ULONG EntrySelector, IN PUCHAR Parameters, IN ULONG Size)
VOID NTAPI KeI386Call16BitFunction (IN OUT PCONTEXT Regs)
NTSTATUS NTAPI KeI386FlatToGdtSelector (IN ULONG SelectorBase, IN USHORT Length, IN USHORT Selector)
Definition at line 555 of file abiosc.c.
References _KGDTENTRY::BaseLow, _KGDTENTRY::Bits, _KGDTENTRY::Bytes, DPL_SYSTEM, ExAcquireSpinLock, ExReleaseSpinLock, HIGHBYTE, HIGHWORD, _KGDTENTRY::HighWord, KeNumberProcessors, KiAbiosGdt, KiAbiosGdtLock, KiAbiosPresent, _KGDTENTRY::LimitLow, LOWBYTE, LOWWORD, RESERVED_GDT_ENTRIES, STATUS_ABIOS_INVALID_SELECTOR, STATUS_ABIOS_NOT_PRESENT, STATUS_SUCCESS, and TYPE_DATA.
NTSTATUS NTAPI KeI386GetLid (IN USHORT DeviceId, IN USHORT RelativeLid, IN BOOLEAN SharedLid, IN struct _DRIVER_OBJECT * DeviceObject, OUT PUSHORT LogicalId)
NTSTATUS NTAPI KeI386ReleaseGdtSelectors (OUT PUSHORT SelectorArray, IN USHORT NumberOfSelectors)
Definition at line 504 of file abiosc.c.
References ExAcquireSpinLock, ExReleaseSpinLock, _KFREE_GDT_ENTRY::Flink, KiAbiosGdt, KiAbiosGdtLock, KiFreeGdtListHead, KiNumberFreeSelectors, and STATUS_SUCCESS.
NTSTATUS NTAPI KeI386ReleaseLid (IN USHORT LogicalId, IN struct _DRIVER_OBJECT * DeviceObject)
NTSTATUS NTAPI KeI386SetGdtSelector (ULONG Selector, PKGDTENTRY GdtValue)
Definition at line 112 of file gdtsup.c.
References ClearMember, CONTAINING_RECORD, _KPCR::GDT, KeActiveProcessors, KeFindFirstSetLeftAffinity, KGDT_NUMBER, KiProcessorBlock, PAGED_CODE, STATUS_SUCCESS, and STATUS_UNSUCCESSFUL.
VOID NTAPI KeI386VdmInitialize (VOID)
Referenced by Phase1InitializationDiscard().
FORCEINLINE ULONG NTAPI KeIsExecutingDpc (VOID)
Definition at line 2765 of file i386.h.
References _KPRCB::DpcRoutineActive, FIELD_OFFSET, and _KPCR::PrcbData.
Referenced by ExAcquireResourceExclusiveLite(), ExAcquireResourceSharedLite(), ExAcquireSharedStarveExclusive(), ExAcquireSharedWaitForExclusive(), ExConvertExclusiveToSharedLite(), ExDeleteResourceLite(), ExOkayToLockRoutine(), ExTryToAcquireResourceExclusiveLite(), FsRtlCopyRead(), FsRtlCopyWrite(), FsRtlMdlReadDev(), KeAttachProcess(), KeForceAttachProcess(), KeSetPriorityThread(), KeSetPriorityZeroPageThread(), KeStackAttachProcess(), KiDeliverApc(), MiAllocatePoolPages(), MiChargeCommitmentPfnLockHeld(), MmMapLockedPagesSpecifyCache(), and MmResourcesAvailable().
FORCEINLINE VOID KeMemoryBarrier (VOID)
Definition at line 2838 of file i386.h.
Referenced by ExAcquireReleasePushLockExclusive(), ExDupHandleTable(), ExpAllocateHandleTableEntry(), ExTryAcquireReleasePushLockExclusive(), ExUnblockPushLock(), KeInsertQueueDpc(), KeIsWaitListEmpty(), KeLoopTbFlushTimeStampUnlocked(), KeReadTbFlushTimeStamp(), KiDeliverApc(), KiExecuteDpc(), KiInsertQueueApc(), KiInsertTimerTable(), KiRetireDpcList(), KxWaitForLockOwnerShip(), MiAppendSubsectionChain(), MiCcPrepareReadInfo(), MmFlushVirtualMemory(), NtFreeUserPhysicalPages(), NtMapUserPhysicalPages(), NtMapUserPhysicalPagesScatter(), NtSetInformationJobObject(), PspChargeQuota(), and PspWriteTebImpersonationInfo().
VOID NTAPI KeOptimizeProcessorControlState (VOID)
Definition at line 2891 of file kernlini.c.
VOID NTAPI KeProfileInterrupt (IN KIRQL OldIrql, IN KTRAP_FRAME TrapFrame)
NTKERNELAPI VOID NTAPI KeProfileInterruptWithSource (IN struct _KTRAP_FRAME * TrapFrame, IN KPROFILE_SOURCE ProfileSource)
VOID NTAPI KeQueryTickCount (OUT PLARGE_INTEGER CurrentCount)
Definition at line 97 of file miscc.c.
References KiQueryTickCount.
Referenced by CcFlushCache(), MiAllocatePoolPages(), and MiCreatePebOrTeb().
NTKERNELAPI NTSTATUS NTAPI KeRestoreFloatingPointState (IN PKFLOATING_SAVE FloatSave)
Definition at line 337 of file misc.c.
References ALIGN_ADJUST, ASSERT, FLOAT_SAVE::Context, FLOAT_SAVE::ContextAddressAsULONG, _CONTROL_WORD::ControlWord, _FNSAVE_FORMAT::ControlWord, _FXSAVE_FORMAT::ControlWord, CR0_EM, CR0_MP, CR0_TS, FLOAT_SAVE::Cr0NpxState, _FX_SAVE_AREA::Cr0NpxState, ExFreePool(), FLOAT_SAVE::Fcw, FLOAT_SAVE::Flags, FLOAT_SAVE_ALIGN_ADJUSTED, FLOAT_SAVE_COMPLETE_CONTEXT, FLOAT_SAVE_FREE_CONTEXT_HEAP, FLOAT_SAVE_RESERVED, FLOAT_SAVE_VALID, _FX_SAVE_AREA::FnArea, _FX_SAVE_AREA::FxArea, _KTHREAD::Header, _KTHREAD::InitialStack, INVALID_FLOATING_POINT_STATE, FLOAT_SAVE::Irql, KeBugCheckEx(), KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeI386FxsrPresent, KeI386NpxPresent, KeI386XMMIPresent, Kix86LdMXCsr(), _CONTROL_WORD::MXCsr, _FXSAVE_FORMAT::MXCsr, NPX_STATE_LOADED, NPX_STATE_NOT_LOADED, _DISPATCHER_HEADER::NpxIrql, _FX_SAVE_AREA::NpxSavedCpu, _KTHREAD::NpxState, _KPRCB::NpxThread, NULL, FLOAT_SAVE::PreviousNpxIrql, RtlCopyMemory, STATUS_SUCCESS, _FNSAVE_FORMAT::StatusWord, _FXSAVE_FORMAT::StatusWord, _FNSAVE_FORMAT::TagWord, _FXSAVE_FORMAT::TagWord, FLOAT_SAVE::Thread, FLOAT_SAVE::u, and _FX_SAVE_AREA::U.
NTKERNELAPI NTSTATUS NTAPI KeSaveFloatingPointState (OUT PKFLOATING_SAVE FloatSave)
Definition at line 94 of file misc.c.
References ALIGN_ADJUST, APC_LEVEL, ASSERT, FLOAT_SAVE::Context, FLOAT_SAVE::ContextAddressAsULONG, _CONTROL_WORD::ControlWord, _FNSAVE_FORMAT::ControlWord, _FXSAVE_FORMAT::ControlWord, CR0_EM, CR0_MP, CR0_TS, FLOAT_SAVE::Cr0NpxState, _FX_SAVE_AREA::Cr0NpxState, DISPATCH_LEVEL, ExAllocatePoolWithTag, FLOAT_SAVE::Fcw, FLOAT_SAVE::Flags, FLOAT_SAVE_ALIGN_ADJUSTED, FLOAT_SAVE_COMPLETE_CONTEXT, FLOAT_SAVE_FREE_CONTEXT_HEAP, FLOAT_SAVE_VALID, _FX_SAVE_AREA::FnArea, _FX_SAVE_AREA::FxArea, _KTHREAD::Header, _KTHREAD::InitialStack, FLOAT_SAVE::Irql, KeGetCurrentIrql(), KeGetCurrentPrcb(), KeGetCurrentThread(), KeI386FxsrPresent, KeI386NpxPresent, KeI386XMMIPresent, Kix86FnSave(), Kix86FxSave(), Kix86LdMXCsr(), Kix86StMXCsr(), _CONTROL_WORD::MXCsr, _FXSAVE_FORMAT::MXCsr, NonPagedPool, NPX_STATE_LOADED, NPX_STATE_NOT_LOADED, _DISPATCHER_HEADER::NpxIrql, _KPRCB::NpxSaveArea, _FX_SAVE_AREA::NpxSavedCpu, _KTHREAD::NpxState, _KPRCB::NpxThread, FLOAT_SAVE::PreviousNpxIrql, RtlCopyMemory, STATUS_ILLEGAL_FLOAT_CONTEXT, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, FLOAT_SAVE::Thread, FLOAT_SAVE::u, and _FX_SAVE_AREA::U.
VOID NTAPI KeUpdateRuntime (IN KIRQL OldIrql, IN KTRAP_FRAME TrapFrame)
VOID NTAPI KeUpdateSystemTime (IN KIRQL OldIrql, IN KTRAP_FRAME TrapFrame)
FORCEINLINE VOID NTAPI KeVdmClearApcThreadAddress (IN PKAPC Apc)
Definition at line 3271 of file i386.h.
References FALSE, and NULL.
BOOLEAN NTAPI KeVdmInsertQueueApc (IN PKAPC Apc, IN struct _KTHREAD * Thread, IN KPROCESSOR_MODE ApcMode, IN PKKERNEL_ROUTINE KernelRoutine, IN PKRUNDOWN_ROUTINE RundownRoutine OPTIONAL, IN PKNORMAL_ROUTINE NormalRoutine OPTIONAL, IN PVOID NormalContext OPTIONAL, IN KPRIORITY Increment)
ULONG Ki386DispatchOpcode (IN PKTRAP_FRAME TrapFrame)
ULONG Ki386DispatchOpcodeV86 (IN PKTRAP_FRAME TrapFrame)
BOOLEAN NTAPI Ki386GetSelectorParameters (IN USHORT Selector, OUT PULONG Flags, OUT PULONG Base, OUT PULONG Limit)
VOID FASTCALL KiAcquireSpinLock (IN PKSPIN_LOCK SpinLock)
Referenced by KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeInsertQueueDpc(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), KeRemoveQueueDpc(), KiTimedChainedDispatch2ndLvl(), and KiTimedInterruptDispatch().
VOID NTAPI KiEditIopmDpc (IN struct _KDPC * Dpc, IN PVOID DeferredContext, IN PVOID SystemArgument1, IN PVOID SystemArgument2)
ULONG NTAPI KiEspFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
Definition at line 57 of file exceptn.c.
References EFLAGS_V86_MASK, FRAME_EDITED, KernelMode, and MODE_MASK.
Referenced by KeContextFromKframes(), KeRaiseUserException(), and KiEspToTrapFrame().
VOID NTAPI KiEspToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG Esp)
Definition at line 107 of file exceptn.c.
References APC_LEVEL, EFLAGS_V86_MASK, FRAME_EDITED, KeBugCheckEx(), KeGetCurrentIrql(), KeLowerIrql, KeRaiseIrql, KernelMode, KiEspFromTrapFrame(), MODE_MASK, and SET_OF_INVALID_CONTEXT.
Referenced by KeContextToKframes(), and KiDispatchException().
FORCEINLINE VOID KiFlushProcessTb (VOID)
Definition at line 524 of file i386.h.
Referenced by KeFlushProcessTb(), KiFlushTargetProcessTb(), and KiIpiProcessRequests().
FORCEINLINE VOID KiFlushSingleTb (IN PVOID Virtual)
Definition at line 512 of file i386.h.
Referenced by KeFlushMultipleTb(), KeFlushSingleTb(), KiFlushTargetMultipleTb(), KiFlushTargetSingleTb(), KiIpiProcessRequests(), MmMapMemoryDumpMdl(), and MmReleaseDumpAddresses().
VOID FASTCALL KiReleaseSpinLock (IN PKSPIN_LOCK SpinLock)
Referenced by KeDeregisterBugCheckCallback(), KeDeregisterBugCheckReasonCallback(), KeInsertQueueDpc(), KeRegisterBugCheckCallback(), KeRegisterBugCheckReasonCallback(), KeRemoveQueueDpc(), KeThawExecution(), KiTimedChainedDispatch2ndLvl(), and KiTimedInterruptDispatch().
ULONG NTAPI KiSegSsFromTrapFrame (IN PKTRAP_FRAME TrapFrame)
Definition at line 200 of file exceptn.c.
References EFLAGS_V86_MASK, KernelMode, KGDT_R0_DATA, MODE_MASK, and RPL_MASK.
Referenced by KeContextFromKframes().
VOID NTAPI KiSegSsToTrapFrame (IN PKTRAP_FRAME TrapFrame, IN ULONG SegSs)
Definition at line 238 of file exceptn.c.
References EFLAGS_V86_MASK, MODE_MASK, RPL_MASK, SEGMENT_MASK, and UserMode.
Referenced by KeContextToKframes(), and KiDispatchException().
VOID NTAPI KiSetIRR (IN ULONG SWInterruptMask)
VOID NTAPI KiUpdateRunTime (VOID)
VOID NTAPI KiUpdateSystemTime (VOID)
ULONGLONG FASTCALL RDMSR (IN ULONG MsrRegister)
Referenced by KiAmdK6InitializeMTRR(), KiGetFeatureBits(), KiInitializeMTRR(), and KiLoadMTRR().
LONGLONG NTAPI RDTSC (VOID)
Referenced by KiInitializeInterruptTimersDpc(), KiInitMachineDependent(), KiTimedChainedDispatch2ndLvl(), KiTimedInterruptDispatch(), and PerfGetCycleCount().
NTHALAPI VOID NTAPI READ_PORT_BUFFER_UCHAR (PUCHAR Port, PUCHAR Buffer, ULONG Count)
NTHALAPI VOID NTAPI READ_PORT_BUFFER_ULONG (PULONG Port, PULONG Buffer, ULONG Count)
NTHALAPI VOID NTAPI READ_PORT_BUFFER_USHORT (PUSHORT Port, PUSHORT Buffer, ULONG Count)
NTHALAPI UCHAR NTAPI READ_PORT_UCHAR (PUCHAR Port)
Referenced by KiGetFeatureBits().
NTHALAPI ULONG NTAPI READ_PORT_ULONG (PULONG Port)
NTHALAPI USHORT NTAPI READ_PORT_USHORT (PUSHORT Port)
NTKERNELAPI VOID NTAPI READ_REGISTER_BUFFER_UCHAR (PUCHAR Register, PUCHAR Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI READ_REGISTER_BUFFER_ULONG (PULONG Register, PULONG Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI READ_REGISTER_BUFFER_USHORT (PUSHORT Register, PUSHORT Buffer, ULONG Count)
NTKERNELAPI UCHAR NTAPI READ_REGISTER_UCHAR (PUCHAR Register)
NTKERNELAPI ULONG NTAPI READ_REGISTER_ULONG (PULONG Register)
NTKERNELAPI USHORT NTAPI READ_REGISTER_USHORT (PUSHORT Register)
NTHALAPI VOID NTAPI WRITE_PORT_BUFFER_UCHAR (PUCHAR Port, PUCHAR Buffer, ULONG Count)
NTHALAPI VOID NTAPI WRITE_PORT_BUFFER_ULONG (PULONG Port, PULONG Buffer, ULONG Count)
NTHALAPI VOID NTAPI WRITE_PORT_BUFFER_USHORT (PUSHORT Port, PUSHORT Buffer, ULONG Count)
NTHALAPI VOID NTAPI WRITE_PORT_UCHAR (PUCHAR Port, UCHAR Value)
Referenced by KiGetFeatureBits().
NTHALAPI VOID NTAPI WRITE_PORT_ULONG (PULONG Port, ULONG Value)
NTHALAPI VOID NTAPI WRITE_PORT_USHORT (PUSHORT Port, USHORT Value)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_BUFFER_UCHAR (PUCHAR Register, PUCHAR Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_BUFFER_ULONG (PULONG Register, PULONG Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_BUFFER_USHORT (PUSHORT Register, PUSHORT Buffer, ULONG Count)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_UCHAR (PUCHAR Register, UCHAR Value)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_ULONG (PULONG Register, ULONG Value)
NTKERNELAPI VOID NTAPI WRITE_REGISTER_USHORT (PUSHORT Register, USHORT Value)
VOID NTAPI WRMSR (IN ULONG MsrRegister, IN ULONGLONG MsrValue)
Referenced by KiAmdK6MtrrWRMSR(), KiGetFeatureBits(), KiLoadFastSyscallMachineSpecificRegisters(), KiLoadMTRR(), and KiLoadPAT().
Variable Documentation
ULONG KeI386CpuStep
Definition at line 36 of file i386init.c.
Referenced by KiInitializeKernel().
ULONG KeI386CpuType
Definition at line 35 of file i386init.c.
Referenced by KiInitializeKernel().
ULONG KeI386EFlagsAndMaskV86
ULONG KeI386EFlagsOrMaskV86
BOOLEAN KeI386FxsrPresent
Definition at line 32 of file i386init.c.
Referenced by Ki386CheckDelayedNpxTrap(), KiInitializeContextThread(), and KiInitializeKernel().
ULONG KeI386MachineType
Definition at line 30 of file i386init.c.
Referenced by KiInitializeMachineType().
BOOLEAN KeI386NpxPresent
Definition at line 31 of file i386init.c.
Referenced by KeContextFromKframes(), KeContextToKframes(), KeRestoreFloatingPointState(), KeSaveFloatingPointState(), KeSetup80387OrEmulate(), KiInitializeContextThread(), KiInitializeKernel(), and KiInitMachineDependent().
ULONG KeI386VirtualIntExtensions
ULONG KiBootFeatureBits
Definition at line 38 of file i386init.c.
Referenced by KiInitializeKernel().
ULONG KiInterruptTemplate[NORMAL_DISPATCH_LENGTH]
Referenced by KeInitializeInterrupt(), KiConnectVectorAndInterruptObject(), and KiGetVectorInfo().
PULONG KiInterruptTemplate2ndDispatch
Referenced by KiConnectVectorAndInterruptObject(), and KiGetVectorInfo().
PULONG KiInterruptTemplateDispatch
Referenced by KiConnectVectorAndInterruptObject().
PULONG KiInterruptTemplateObject
Referenced by KeInitializeInterrupt().
ULONG KiMXCsrMask
Definition at line 34 of file i386init.c.
Referenced by KiInitMachineDependent().
NTKERNELAPI PVOID MmHighestUserAddress
Referenced by MiDeletePte(), MiMapViewOfImageSection(), MmAccessFault(), MmCleanProcessAddressSpace(), and MmInitSystem().
NTKERNELAPI PVOID MmSystemRangeStart
Referenced by ExpInitializeExecutive(), MI_ADD_LOCKED_PAGE_CHARGE_FOR_PROBE(), MiCheckPdeForPagedPool(), MiCompleteProtoPteFault(), MiDispatchFault(), MiInitializeSystemPtes(), MiResolveTransitionFault(), MiUseLargeDriverPage(), MmAccessFault(), MmCreateProcessAddressSpace(), MmInitSystem(), MmLockPageableSectionByHandle(), and NtQuerySystemInformation().
NTKERNELAPI ULONG MmUserProbeAddress
Referenced by ExpWorkerThread(), ExQueueWorkItem(), and MmInitSystem().