Windows Research Kernel v1.2: C:/Windows Research Kernel/config/hivesum.c File Reference
hivesum.c File Reference
#include "cmp.h"
Functions
ULONG HvpHeaderCheckSum (PHBASE_BLOCK BaseBlock)
Function Documentation
ULONG HvpHeaderCheckSum (PHBASE_BLOCK BaseBlock)
Definition at line 26 of file hivesum.c.
Referenced by HvInitializeHive(), HvpDoWriteHive(), HvpGetHiveHeader(), HvpGetLogHeader(), HvpWriteLog(), and HvWriteHive().