Windows Research Kernel v1.2: C:/Windows Research Kernel/wmi/callouts.c File Reference
callouts.c File Reference
#include <stdio.h>
#include <ntos.h>
#include <zwapi.h>
#include <evntrace.h>
#include "wmikmp.h"
#include "tracep.h"
Data Structures
struct _TRACE_DEVICE
struct _TRACE_FILE_WORK_ITEM
Macros
#define _WMIKM_
#define ETW_WORK_ITEM_LIMIT 64
#define MAX_FILENAME_TO_LOG 4096
Typedefs
typedef struct _TRACE_DEVICE * PTRACE_DEVICE
typedef struct _TRACE_FILE_WORK_ITEM * PTRACE_FILE_WORK_ITEM
typedef struct _TRACE_DEVICE TRACE_DEVICE
typedef struct _TRACE_FILE_WORK_ITEM TRACE_FILE_WORK_ITEM
Functions
VOID FASTCALL WmipDisableKernelTrace (IN ULONG EnableFlags)
VOID FASTCALL WmipEnableKernelTrace (IN ULONG EnableFlags)
PWMI_LOGGER_CONTEXT FASTCALL WmipIsLoggerOn (IN ULONG LoggerId)
VOID WmipSetTraceNotify (IN PDEVICE_OBJECT DeviceObject, IN ULONG TraceClass, IN ULONG Enable)
VOID WmipTraceFile (IN PVOID TraceFileContext)
VOID WmipTraceIo (IN ULONG DiskNumber, IN PIRP Irp, IN PVOID Counters)
VOID WmipTraceLoadImage (IN PUNICODE_STRING ImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
VOID WmipTraceNetwork (IN ULONG GroupType, IN PVOID EventInfo, IN ULONG EventInfoLen, IN PVOID Reserved)
VOID FASTCALL WmipTracePageFault (IN NTSTATUS Status, IN PVOID VirtualAddress, IN PVOID TrapFrame)
VOID WmipTraceRegistry (IN NTSTATUS Status, IN PVOID Kcb, IN LONGLONG ElapsedTime, IN ULONG Index, IN PUNICODE_STRING KeyName, IN UCHAR Type)
VOID WmipTraceVolMgr (IN PIRP ParentIrp, IN PIRP ChildIrp)
VOID FASTCALL WmiStartContextSwapTrace ()
VOID FASTCALL WmiStopContextSwapTrace ()
VOID FASTCALL WmiTraceContextSwap (IN PETHREAD OldEThread, IN PETHREAD NewEThread)
NTKERNELAPI VOID FASTCALL WmiTraceProcess (IN PEPROCESS Process, IN BOOLEAN Create)
NTKERNELAPI VOID WmiTraceThread (IN PETHREAD Thread, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN Create)
Variables
PVOID WmipDiskIoNotify = NULL
LONG WmipFileIndex = 0
PFILE_OBJECT * WmipFileTable = NULL
ULONG WmipKernelLoggerStartedOnce = 0
PVOID WmipTdiIoNotify = NULL
ULONG WmipTraceFileFlag = FALSE
LONG WmipTraceProcessRef = 0
PVOID WmipVolMgrIoNotify = NULL
LONG WmipWorkItemCounter = 0
Macro Definition Documentation
#define _WMIKM_
Definition at line 36 of file callouts.c.
#define ETW_WORK_ITEM_LIMIT 64
Definition at line 40 of file callouts.c.
Referenced by WmipTraceIo().
#define MAX_FILENAME_TO_LOG 4096
Definition at line 39 of file callouts.c.
Referenced by WmipTraceIo().
Typedef Documentation
typedef struct _TRACE_DEVICE * PTRACE_DEVICE
typedef struct _TRACE_FILE_WORK_ITEM * PTRACE_FILE_WORK_ITEM
typedef struct _TRACE_DEVICE TRACE_DEVICE
typedef struct _TRACE_FILE_WORK_ITEM TRACE_FILE_WORK_ITEM
Function Documentation
VOID FASTCALL WmipDisableKernelTrace (IN ULONG EnableFlags)
Definition at line 346 of file callouts.c.
References CmSetTraceNotifyRoutine(), CONTAINING_RECORD, _TRACE_DEVICE::DeviceObject, _REGENTRY::DeviceObject, _IO_STACK_LOCATION::DeviceObject, ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, _REGENTRY::Flags, _LIST_ENTRY::Flink, Index, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoInitializeIrp(), IoSetNextIrpStackLocation, IoSizeOfIrp, IoWMIDeviceObjectToProviderId, IRP_MN_SET_TRACE_NOTIFY, MAX_FILE_TABLE_SIZE, MmSetPageFaultNotifyRoutine(), NULL, PAGED_CODE, PagedPool, PIRP, PsGetCurrentThread(), REGENTRY_FLAG_TRACED, RtlZeroMemory, STATUS_WMI_TRY_AGAIN, _TRACE_DEVICE::TraceClass, TRACEPOOLTAG, TRUE, WmipDiskIoNotify, WmipEnterSMCritSection, WmipForwardWmiIrp(), WmipInUseRegEntryCount, WmipInUseRegEntryHead, WmipLeaveSMCritSection, WmipServiceDeviceObject, WmipTdiIoNotify, WmipTraceFileFlag, WmipVolMgrIoNotify, WMIREG_FLAG_TRACE_NOTIFY_MASK, WMIREG_NOTIFY_DISK_IO, WMIREG_NOTIFY_TDI_IO, and WMIREG_NOTIFY_VOLMGR_IO.
Referenced by WmipStopLoggerInstance(), and WmiUpdateTrace().
VOID FASTCALL WmipEnableKernelTrace (IN ULONG EnableFlags)
Definition at line 141 of file callouts.c.
References CmSetTraceNotifyRoutine(), CONTAINING_RECORD, _TRACE_DEVICE::DeviceObject, _REGENTRY::DeviceObject, _IO_STACK_LOCATION::DeviceObject, ExAllocatePoolWithTag, ExFreePoolWithTag, FALSE, _REGENTRY::Flags, _LIST_ENTRY::Flink, Index, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoInitializeIrp(), IoSetNextIrpStackLocation, IoSizeOfIrp, IoWMIDeviceObjectToProviderId, IRP_MN_SET_TRACE_NOTIFY, MmSetPageFaultNotifyRoutine(), NULL, PAGED_CODE, PagedPool, PIRP, PsGetCurrentThread(), PsSetLoadImageNotifyRoutine(), REGENTRY_FLAG_TRACED, RtlZeroMemory, STATUS_WMI_TRY_AGAIN, _TRACE_DEVICE::TraceClass, TRACEPOOLTAG, TRUE, WmipDiskIoNotify, WmipEnterSMCritSection, WmipForwardWmiIrp(), WmipInUseRegEntryCount, WmipInUseRegEntryHead, WmipKernelLoggerStartedOnce, WmipLeaveSMCritSection, WmipServiceDeviceObject, WmipTdiIoNotify, WmipTraceFileFlag, WmipTraceIo(), WmipTraceLoadImage(), WmipTraceNetwork(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmipVolMgrIoNotify, WMIREG_FLAG_TRACE_NOTIFY_MASK, WMIREG_NOTIFY_DISK_IO, WMIREG_NOTIFY_TDI_IO, and WMIREG_NOTIFY_VOLMGR_IO.
Referenced by WmipStartLogger(), and WmiUpdateTrace().
PWMI_LOGGER_CONTEXT FASTCALL WmipIsLoggerOn (IN ULONG LoggerId)
Definition at line 1964 of file callouts.c.
References MAXLOGGERS, NULL, WmipIsValidLogger, and WmipLoggerContext.
Referenced by WmipTraceFile(), WmipTraceIo(), WmipTraceLoadImage(), WmipTracePageFault(), WmipTraceRegistry(), WmipTraceVolMgr(), WmiReserveWithPerfHeader(), WmiTraceProcess(), and WmiTraceThread().
VOID WmipSetTraceNotify (IN PDEVICE_OBJECT DeviceObject, IN ULONG TraceClass, IN ULONG Enable)
Definition at line 503 of file callouts.c.
References _IO_STACK_LOCATION::DeviceObject, FALSE, IoAllocateIrp(), IoFreeIrp(), IoGetCurrentIrpStackLocation, IoSetNextIrpStackLocation, IoWMIDeviceObjectToProviderId, IRP_MN_SET_TRACE_NOTIFY, NULL, PIRP, STATUS_WMI_TRY_AGAIN, WmipDiskIoNotify, WmipForwardWmiIrp(), WmipServiceDeviceObject, WmipTdiIoNotify, WmipVolMgrIoNotify, WMIREG_NOTIFY_DISK_IO, WMIREG_NOTIFY_TDI_IO, and WMIREG_NOTIFY_VOLMGR_IO.
Referenced by IoWMIRegistrationControl().
VOID WmipTraceFile (IN PVOID TraceFileContext)
Definition at line 1362 of file callouts.c.
References ALIGN_TO_POWER2, ASSERT, _UNICODE_STRING::Buffer, _TRACE_FILE_WORK_ITEM::BufferSize, EVENT_TRACE_GROUP_FILE, ExFreePool(), FIELD_OFFSET, _TRACE_FILE_WORK_ITEM::FileObject, _WMI_TRACE_PACKET::Group, InterlockedDecrement, _UNICODE_STRING::Length, MAXLOGGERS, _OBJECT_NAME_INFORMATION::Name, NT_SUCCESS, NULL, ObDereferenceObject(), ObQueryNameString(), _PERFINFO_TRACE_HEADER::Packet, PAGED_CODE, RtlCopyMemory, Status, TraceDebug, _WMI_TRACE_PACKET::Type, UNICODE_NULL, WmipDereferenceLogger, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), WmipWorkItemCounter, WmiReserveWithPerfHeader(), and WmiTraceAlignment.
Referenced by WmipTraceIo().
VOID WmipTraceIo (IN ULONG DiskNumber, IN PIRP Irp, IN PVOID Counters)
Definition at line 1026 of file callouts.c.
References ASSERT, _TRACE_FILE_WORK_ITEM::BufferSize, _WMI_DISKIO_READWRITE::ByteOffset, DelayedWorkQueue, _WMI_DISKIO_READWRITE::DiskNumber, ETW_WORK_ITEM_LIMIT, EVENT_TRACE_GROUP_IO, ExAllocatePoolWithTag, ExFreePool(), ExInitializeWorkItem, ExQueueWorkItem(), _FILE_OBJECT::FileName, _TRACE_FILE_WORK_ITEM::FileObject, _WMI_DISKIO_READWRITE::FileObject, _WMI_TRACE_PACKET::Group, _LARGE_INTEGER::HighPart, _WMI_DISKIO_READWRITE::HighResResponseTime, InterlockedCompareExchange(), InterlockedDecrement, IoFileObjectType, IoGetCurrentIrpStackLocation, IRP_ASSOCIATED_IRP, IRP_MJ_READ, IRP_PAGING_IO, _WMI_DISKIO_READWRITE::IrpAddr, _WMI_DISKIO_READWRITE::IrpFlags, KernelMode, _UNICODE_STRING::Length, _WMI_LOGGER_CONTEXT::LoggerId, _LARGE_INTEGER::LowPart, _IO_STACK_LOCATION::MajorFunction, MAX_FILE_TABLE_SIZE, MAX_FILENAME_TO_LOG, NonPagedPool, NT_SUCCESS, NULL, ObReferenceObjectByPointer(), _SYSTEM_TRACE_HEADER::Packet, _IO_STACK_LOCATION::Parameters, PIRP, _LARGE_INTEGER::QuadPart, _WMI_DISKIO_READWRITE::ResponseTime, _WMI_DISKIO_READWRITE::Size, Status, TraceDebug, TRACEPOOLTAG, _WMI_TRACE_PACKET::Type, UNREFERENCED_PARAMETER, UserMode, WmipDereferenceLogger, WmipFileIndex, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), WmipTraceFile(), WmipTraceFileFlag, WmipWorkItemCounter, WmiReserveWithSystemHeader(), and _TRACE_FILE_WORK_ITEM::WorkItem.
Referenced by WmipEnableKernelTrace().
VOID WmipTraceLoadImage (IN PUNICODE_STRING ImageName, IN HANDLE ProcessId, IN PIMAGE_INFO ImageInfo)
Definition at line 1452 of file callouts.c.
References _WMI_LOGGER_CONTEXT::EnableFlags, FIELD_OFFSET, _WMI_IMAGELOAD_INFORMATION::FileName, HandleToUlong, _WMI_TRACE_PACKET::HookId, _WMI_IMAGELOAD_INFORMATION::ImageBase, _WMI_IMAGELOAD_INFORMATION::ImageSize, MAXLOGGERS, NULL, _SYSTEM_TRACE_HEADER::Packet, PAGED_CODE, PerfInfoFlushProfileCache(), _WMI_IMAGELOAD_INFORMATION::ProcessId, RtlCopyMemory, TraceDebug, UNICODE_NULL, UNREFERENCED_PARAMETER, WMI_LOG_TYPE_PROCESS_LOAD_IMAGE, WmipDereferenceLogger, WmipEventLogger, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
Referenced by WmipEnableKernelTrace().
VOID WmipTraceNetwork (IN ULONG GroupType, IN PVOID EventInfo, IN ULONG EventInfoLen, IN PVOID Reserved)
Definition at line 975 of file callouts.c.
References FIELD_OFFSET, _WMI_TRACE_PACKET::HookId, NULL, _PERFINFO_TRACE_HEADER::Packet, RtlCopyMemory, UNREFERENCED_PARAMETER, WmipKernelLogger, WmipLoggerContext, WmipReleaseTraceBuffer(), and WmiReserveWithPerfHeader().
Referenced by WmipEnableKernelTrace().
VOID FASTCALL WmipTracePageFault (IN NTSTATUS Status, IN PVOID VirtualAddress, IN PVOID TrapFrame)
Definition at line 883 of file callouts.c.
References DbgPrintEx(), DPFLTR_INFO_LEVEL, DPFLTR_WMILIB_ID, EVENT_TRACE_GROUP_MEMORY, _WMI_TRACE_PACKET::Group, NULL, _SYSTEM_TRACE_HEADER::Packet, STATUS_PAGE_FAULT_COPY_ON_WRITE, STATUS_PAGE_FAULT_DEMAND_ZERO, STATUS_PAGE_FAULT_GUARD_PAGE, STATUS_PAGE_FAULT_PAGING_FILE, STATUS_PAGE_FAULT_TRANSITION, _WMI_TRACE_PACKET::Type, WmipIsLoggerOn(), WmipKernelLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
Referenced by WmipEnableKernelTrace().
VOID WmipTraceRegistry (IN NTSTATUS Status, IN PVOID Kcb, IN LONGLONG ElapsedTime, IN ULONG Index, IN PUNICODE_STRING KeyName, IN UCHAR Type)
Definition at line 1535 of file callouts.c.
References EVENT_TRACE_GROUP_REGISTRY, except, EXCEPTION_EXECUTE_HANDLER, _WMI_TRACE_PACKET::Group, Index, NULL, _SYSTEM_TRACE_HEADER::Packet, PAGED_CODE, RtlCopyMemory, RtlZeroMemory, Status, _WMI_TRACE_PACKET::Type, UNICODE_NULL, WmipIsLoggerOn(), WmipKernelLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
Referenced by WmipEnableKernelTrace().
VOID WmipTraceVolMgr (IN PIRP ParentIrp, IN PIRP ChildIrp)
Definition at line 1314 of file callouts.c.
References _WMI_TRACE_PACKET::HookId, NULL, _SYSTEM_TRACE_HEADER::Packet, WMI_LOG_TYPE_VOLMGR, WmipIsLoggerOn(), WmipKernelLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
Referenced by WmipEnableKernelTrace().
VOID FASTCALL WmiStartContextSwapTrace ()
Definition at line 1821 of file callouts.c.
References MAXIMUM_PROCESSORS, PAGED_CODE, RtlZeroMemory, and WmipContextSwapProcessorBuffers.
Referenced by PerfInfoStartLog().
VOID FASTCALL WmiStopContextSwapTrace ()
Definition at line 1867 of file callouts.c.
References _KTHREAD::Affinity, AFFINITY_MASK, KeGetCurrentThread(), KeNumberProcessors, KeRevertToUserAffinityThread(), KeSetSystemAffinityThread(), NULL, PAGED_CODE, WmipContextSwapProcessorBuffers, WmipIsValidLogger, WmipKernelLogger, WmipLoggerContext, and WmipPushDirtyContextSwapBuffer().
Referenced by PerfInfoStartLog(), and PerfInfoStopLog().
VOID FASTCALL WmiTraceContextSwap (IN PETHREAD OldEThread, IN PETHREAD NewEThread)
Definition at line 1655 of file callouts.c.
References ASSERT, _WMI_BUFFER_HEADER::CurrentOffset, FIELD_OFFSET, HandleToUlong, _WMI_TRACE_PACKET::HookId, KeGetCurrentProcessorNumber(), _PERFINFO_TRACE_HEADER::Marker, _WMI_CONTEXTSWAP::NewThreadId, _WMI_CONTEXTSWAP::NewThreadPriority, _WMI_CONTEXTSWAP::NewThreadQuantum, NULL, _WMI_BUFFER_HEADER::Offset, _WMI_CONTEXTSWAP::OldThreadId, _WMI_CONTEXTSWAP::OldThreadIdealProcessor, _WMI_CONTEXTSWAP::OldThreadPriority, _WMI_CONTEXTSWAP::OldThreadQuantum, _WMI_CONTEXTSWAP::OldThreadState, _WMI_CONTEXTSWAP::OldThreadWaitMode, _WMI_CONTEXTSWAP::OldThreadWaitReason, _PERFINFO_TRACE_HEADER::Packet, PERFINFO_LOG_TYPE_CONTEXTSWAP, PERFINFO_TRACE_MARKER, PerfTimeStamp, _WMI_TRACE_PACKET::Size, _PERFINFO_TRACE_HEADER::SystemTime, WMI_CTXSWAP_EVENTSIZE_ALIGNMENT, WmipContextSwapProcessorBuffers, WmipPopFreeContextSwapBuffer(), and WmipPushDirtyContextSwapBuffer().
NTKERNELAPI VOID FASTCALL WmiTraceProcess (IN PEPROCESS Process, IN BOOLEAN Create)
Definition at line 564 of file callouts.c.
References _STRING::Buffer, _WMI_LOGGER_CONTEXT::EnableFlags, ExFreePool(), _WMI_PROCESS_INFORMATION::ExitStatus, FALSE, FIELD_OFFSET, HandleToUlong, _WMI_TRACE_PACKET::HookId, _STRING::Length, _UNICODE_STRING::Length, MAXLOGGERS, MmGetDirectoryFrameFromProcess(), MmGetSessionId(), NT_SUCCESS, NULL, _SYSTEM_TRACE_HEADER::Packet, PAGED_CODE, _WMI_PROCESS_INFORMATION::PageDirectoryBase, _WMI_PROCESS_INFORMATION::ParentId, _WMI_PROCESS_INFORMATION::ProcessId, PsDereferencePrimaryTokenEx, PsReferencePrimaryToken(), RtlCopyMemory, RtlFreeAnsiString(), RtlUnicodeStringToAnsiString(), SeLengthSid, SeLocateProcessImageName(), SeQueryInformationToken(), _WMI_PROCESS_INFORMATION::SessionId, _SID_AND_ATTRIBUTES::Sid, _WMI_PROCESS_INFORMATION::Sid, Status, STATUS_SEVERITY_ERROR, STATUS_SUCCESS, strlen(), TokenUser, TraceDebug, TRUE, _TOKEN_USER::User, WMI_LOG_TYPE_PROCESS_CREATE, WMI_LOG_TYPE_PROCESS_DELETE, WmipAssert, WmipDereferenceLogger, WmipEventLogger, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
NTKERNELAPI VOID WmiTraceThread (IN PETHREAD Thread, IN PINITIAL_TEB InitialTeb OPTIONAL, IN BOOLEAN Create)
Definition at line 760 of file callouts.c.
References _WMI_LOGGER_CONTEXT::EnableFlags, HandleToUlong, _WMI_TRACE_PACKET::HookId, MAXLOGGERS, NULL, _SYSTEM_TRACE_HEADER::Packet, PAGED_CODE, _WMI_THREAD_INFORMATION::ProcessId, _WMI_EXTENDED_THREAD_INFORMATION::ProcessId, _WMI_EXTENDED_THREAD_INFORMATION::StackBase, _WMI_EXTENDED_THREAD_INFORMATION::StackLimit, _WMI_EXTENDED_THREAD_INFORMATION::StartAddr, _WMI_THREAD_INFORMATION::ThreadId, _WMI_EXTENDED_THREAD_INFORMATION::ThreadId, TraceDebug, _WMI_EXTENDED_THREAD_INFORMATION::UserStackBase, _WMI_EXTENDED_THREAD_INFORMATION::UserStackLimit, _WMI_EXTENDED_THREAD_INFORMATION::WaitMode, _WMI_EXTENDED_THREAD_INFORMATION::Win32StartAddr, WMI_LOG_TYPE_THREAD_CREATE, WMI_LOG_TYPE_THREAD_DELETE, WmipDereferenceLogger, WmipEventLogger, WmipIsLoggerOn(), WmipKernelLogger, WmipReferenceLogger, WmipReleaseTraceBuffer(), and WmiReserveWithSystemHeader().
Variable Documentation
PVOID WmipDiskIoNotify = NULL
Definition at line 127 of file callouts.c.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
LONG WmipFileIndex = 0
Definition at line 118 of file callouts.c.
Referenced by WmipTraceIo().
PFILE_OBJECT* WmipFileTable = NULL
Definition at line 120 of file callouts.c.
Referenced by WmipStartLogger().
ULONG WmipKernelLoggerStartedOnce = 0
Definition at line 125 of file callouts.c.
Referenced by WmipEnableKernelTrace().
PVOID WmipTdiIoNotify = NULL
Definition at line 128 of file callouts.c.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
ULONG WmipTraceFileFlag = FALSE
Definition at line 117 of file callouts.c.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipTraceIo().
LONG WmipTraceProcessRef = 0
Definition at line 126 of file callouts.c.
PVOID WmipVolMgrIoNotify = NULL
Definition at line 129 of file callouts.c.
Referenced by WmipDisableKernelTrace(), WmipEnableKernelTrace(), and WmipSetTraceNotify().
LONG WmipWorkItemCounter = 0
Definition at line 119 of file callouts.c.
Referenced by WmipTraceFile(), and WmipTraceIo().