Windows Research Kernel v1.2: C:/Windows Research Kernel/cache/ccperf.c File Reference
ccperf.c File Reference
#include "cc.h"
Functions
VOID CcPerfFileRunDown (PPERFINFO_ENTRY_TABLE HashTable)
Function Documentation
VOID CcPerfFileRunDown (PPERFINFO_ENTRY_TABLE HashTable)
Definition at line 26 of file ccperf.c.
References ASSERT, CcAcquireMasterLock, CcCleanSharedCacheMapList, CcDirtySharedCacheMapList, CcReleaseMasterLock, CONTAINING_RECORD, _SHARED_CACHE_MAP::FileObject, FlagOn, _SHARED_CACHE_MAP::Flags, _LIST_ENTRY::Flink, IS_CURSOR, KeGetCurrentIrql(), PASSIVE_LEVEL, PerfInfoAddToFileHash(), _SHARED_CACHE_MAP::SharedCacheMapLinks, and _SHARED_CACHE_MAP_LIST_CURSOR::SharedCacheMapLinks.
Referenced by PerfInfoFileNameRunDown().