Windows Research Kernel v1.2: C:/Windows Research Kernel/inc/ntmmapi.h File Reference
ntmmapi.h File Reference
Data Structures
struct _FILEOFFSET_INFORMATION
struct _MEMORY_BASIC_INFORMATION
struct _MEMORY_BASIC_INFORMATION32
struct _MEMORY_FRAME_INFORMATION
struct _MEMORY_WORKING_SET_BLOCK
struct _MEMORY_WORKING_SET_EX_BLOCK
struct _MEMORY_WORKING_SET_EX_INFORMATION
struct _MEMORY_WORKING_SET_INFORMATION
struct _MMPFN_IDENTITY
struct _MMPFN_MEMSNAP_INFORMATION
struct _PAGEDIR_INFORMATION
struct _SECTION_IMAGE_INFORMATION
struct _SECTION_IMAGE_INFORMATION64
struct _SECTIONBASICINFO
Macros
#define MAP_PROCESS 1L
#define MAP_SYSTEM 2L
#define MEM_4MB_PAGES 0x80000000
#define MEM_COMMIT 0x1000
#define MEM_DECOMMIT 0x4000
#define MEM_DOS_LIM 0x40000000
#define MEM_EXECUTE_OPTION_DISABLE 0x1
#define MEM_EXECUTE_OPTION_DISABLE_THUNK_EMULATION 0x4
#define MEM_EXECUTE_OPTION_ENABLE 0x2
#define MEM_EXECUTE_OPTION_EXECUTE_DISPATCH_ENABLE 0x10
#define MEM_EXECUTE_OPTION_IMAGE_DISPATCH_ENABLE 0x20
#define MEM_EXECUTE_OPTION_PERMANENT 0x8
#define MEM_EXECUTE_OPTION_VALID_FLAGS 0x3f
#define MEM_FREE 0x10000
#define MEM_IMAGE SEC_IMAGE
#define MEM_LARGE_PAGES 0x20000000
#define MEM_MAPPED 0x40000
#define MEM_PHYSICAL 0x400000
#define MEM_PRIVATE 0x20000
#define MEM_RELEASE 0x8000
#define MEM_RESERVE 0x2000
#define MEM_RESET 0x80000
#define MEM_TOP_DOWN 0x100000
#define MEM_WRITE_WATCH 0x200000
#define MMPFNLIST_ACTIVE 6
#define MMPFNLIST_BAD 5
#define MMPFNLIST_FREE 1
#define MMPFNLIST_MODIFIED 3
#define MMPFNLIST_MODIFIEDNOWRITE 4
#define MMPFNLIST_STANDBY 2
#define MMPFNLIST_TRANSITION 7
#define MMPFNLIST_ZERO 0
#define MMPFNUSE_AWEPAGE 9
#define MMPFNUSE_DRIVERLOCKPAGE 10
#define MMPFNUSE_FILE 1
#define MMPFNUSE_METAFILE 8
#define MMPFNUSE_NONPAGEDPOOL 5
#define MMPFNUSE_PAGEDPOOL 4
#define MMPFNUSE_PAGEFILEMAPPED 2
#define MMPFNUSE_PAGETABLE 3
#define MMPFNUSE_PROCESSPRIVATE 0
#define MMPFNUSE_SESSIONPRIVATE 7
#define MMPFNUSE_SYSTEMPTE 6
#define PAGE_EXECUTE 0x10
#define PAGE_EXECUTE_READ 0x20
#define PAGE_EXECUTE_READWRITE 0x40
#define PAGE_EXECUTE_WRITECOPY 0x80
#define PAGE_GUARD 0x100
#define PAGE_NOACCESS 0x01
#define PAGE_NOCACHE 0x200
#define PAGE_READONLY 0x02
#define PAGE_READWRITE 0x04
#define PAGE_WRITECOMBINE 0x400
#define PAGE_WRITECOPY 0x08
#define SEC_BASED 0x200000
#define SEC_COMMIT 0x8000000
#define SEC_FILE 0x800000
#define SEC_GLOBAL 0x20000000
#define SEC_IMAGE 0x1000000
#define SEC_LARGE_PAGES 0x80000000
#define SEC_NO_CHANGE 0x400000
#define SEC_NOCACHE 0x10000000
#define SEC_RESERVE 0x4000000
#define SECTION_ALL_ACCESS
#define SECTION_EXTEND_SIZE 0x0010
#define SECTION_MAP_EXECUTE 0x0008
#define SECTION_MAP_EXECUTE_EXPLICIT 0x0020
#define SECTION_MAP_READ 0x0004
#define SECTION_MAP_WRITE 0x0002
#define SECTION_QUERY 0x0001
#define SEGMENT_ALL_ACCESS SECTION_ALL_ACCESS
#define WRITE_WATCH_FLAG_RESET 0x01
Typedefs
typedef struct _FILEOFFSET_INFORMATION FILEOFFSET_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION MEMORY_BASIC_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION32 MEMORY_BASIC_INFORMATION32
typedef struct _MEMORY_FRAME_INFORMATION MEMORY_FRAME_INFORMATION
typedef enum _MEMORY_INFORMATION_CLASS MEMORY_INFORMATION_CLASS
typedef struct _MEMORY_WORKING_SET_BLOCK MEMORY_WORKING_SET_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_BLOCK MEMORY_WORKING_SET_EX_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_INFORMATION MEMORY_WORKING_SET_EX_INFORMATION
typedef struct _MEMORY_WORKING_SET_INFORMATION MEMORY_WORKING_SET_INFORMATION
typedef struct _MMPFN_IDENTITY MMPFN_IDENTITY
typedef struct _MMPFN_MEMSNAP_INFORMATION MMPFN_MEMSNAP_INFORMATION
typedef struct _PAGEDIR_INFORMATION PAGEDIR_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION * PMEMORY_BASIC_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION32 * PMEMORY_BASIC_INFORMATION32
typedef struct _MEMORY_WORKING_SET_BLOCK * PMEMORY_WORKING_SET_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_BLOCK * PMEMORY_WORKING_SET_EX_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_INFORMATION * PMEMORY_WORKING_SET_EX_INFORMATION
typedef struct _MEMORY_WORKING_SET_INFORMATION * PMEMORY_WORKING_SET_INFORMATION
typedef struct _MMPFN_IDENTITY * PMMPFN_IDENTITY
typedef struct _MMPFN_MEMSNAP_INFORMATION * PMMPFN_MEMSNAP_INFORMATION
typedef struct _SECTIONBASICINFO * PSECTION_BASIC_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION * PSECTION_IMAGE_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION64 * PSECTION_IMAGE_INFORMATION64
typedef struct _SECTIONBASICINFO SECTION_BASIC_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION SECTION_IMAGE_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION64 SECTION_IMAGE_INFORMATION64
typedef enum _SECTION_INFORMATION_CLASS SECTION_INFORMATION_CLASS
typedef enum _SECTION_INHERIT SECTION_INHERIT
Enumerations
enum _MEMORY_INFORMATION_CLASS { MemoryBasicInformation, MemoryMappedFilenameInformation, MemoryRegionInformation, MemoryWorkingSetExInformation }
enum _SECTION_INFORMATION_CLASS { SectionBasicInformation, SectionImageInformation, MaxSectionInfoClass }
enum _SECTION_INHERIT { ViewShare = 1, ViewUnmap = 2 }
Functions
C_ASSERT (sizeof(MEMORY_BASIC_INFORMATION)==sizeof(MEMORY_BASIC_INFORMATION32))
struct DECLSPEC_ALIGN (16) _MEMORY_BASIC_INFORMATION64
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __out_ecount(*NumberOfPages) PULONG_PTR UserPfnArray)
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __in ULONG_PTR ZeroBits, __inout PSIZE_T RegionSize, __in ULONG AllocationType, __in ULONG Protect)
NTSYSCALLAPI NTSTATUS NTAPI NtAreMappedFilesTheSame (__in PVOID File1MappedAsAnImage, __in PVOID File2MappedAsFile)
NTSYSCALLAPI NTSTATUS NTAPI NtCreatePagingFile (__in PUNICODE_STRING PageFileName, __in PLARGE_INTEGER MinimumSize, __in PLARGE_INTEGER MaximumSize, __in ULONG Priority)
NTSYSCALLAPI NTSTATUS NTAPI NtCreateSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PLARGE_INTEGER MaximumSize, __in ULONG SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle)
NTSYSCALLAPI NTSTATUS NTAPI NtExtendSection (__in HANDLE SectionHandle, __inout PLARGE_INTEGER NewSectionSize)
NTSYSCALLAPI NTSTATUS NTAPI NtFlushInstructionCache (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in SIZE_T Length)
NTSYSCALLAPI NTSTATUS NTAPI NtFlushVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __out PIO_STATUS_BLOCK IoStatus)
NTSYSCALLAPI NTSTATUS NTAPI NtFlushWriteBuffer (VOID)
NTSYSCALLAPI NTSTATUS NTAPI NtFreeUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __in_ecount(*NumberOfPages) PULONG_PTR UserPfnArray)
NTSYSCALLAPI NTSTATUS NTAPI NtFreeVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG FreeType)
NTSYSCALLAPI NTSTATUS NTAPI NtGetWriteWatch (__in HANDLE ProcessHandle, __in ULONG Flags, __in PVOID BaseAddress, __in SIZE_T RegionSize, __out_ecount(*EntriesInUserAddressArray) PVOID *UserAddressArray, __inout PULONG_PTR EntriesInUserAddressArray, __out PULONG Granularity)
NTSYSCALLAPI NTSTATUS NTAPI NtLockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
NTSYSCALLAPI NTSTATUS NTAPI NtMapUserPhysicalPages (__in PVOID VirtualAddress, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
NTSYSCALLAPI NTSTATUS NTAPI NtMapUserPhysicalPagesScatter (__in_ecount(NumberOfPages) PVOID *VirtualAddresses, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
NTSYSCALLAPI NTSTATUS NTAPI NtMapViewOfSection (__in HANDLE SectionHandle, __in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout_opt PLARGE_INTEGER SectionOffset, __inout PSIZE_T ViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in ULONG Win32Protect)
NTSYSCALLAPI NTSTATUS NTAPI NtOpenSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
NTSYSCALLAPI NTSTATUS NTAPI NtProtectVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG NewProtect, __out PULONG OldProtect)
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySection (__in HANDLE SectionHandle, __in SECTION_INFORMATION_CLASS SectionInformationClass, __out_bcount(SectionInformationLength) PVOID SectionInformation, __in SIZE_T SectionInformationLength, __out_opt PSIZE_T ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtQueryVirtualMemory (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in MEMORY_INFORMATION_CLASS MemoryInformationClass, __out_bcount(MemoryInformationLength) PVOID MemoryInformation, __in SIZE_T MemoryInformationLength, __out_opt PSIZE_T ReturnLength)
NTSYSCALLAPI NTSTATUS NTAPI NtReadVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
NTSYSCALLAPI NTSTATUS NTAPI NtResetWriteWatch (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in SIZE_T RegionSize)
NTSYSCALLAPI NTSTATUS NTAPI NtUnlockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID *BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
NTSYSCALLAPI NTSTATUS NTAPI NtUnmapViewOfSection (__in HANDLE ProcessHandle, __in PVOID BaseAddress)
NTSYSCALLAPI NTSTATUS NTAPI NtWriteVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in_bcount(BufferSize) CONST VOID *Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Variables
MEMORY_BASIC_INFORMATION64
* PMEMORY_BASIC_INFORMATION64
Macro Definition Documentation
#define MAP_PROCESS 1L
Definition at line 351 of file ntmmapi.h.
Referenced by NtLockVirtualMemory(), and NtUnlockVirtualMemory().
#define MAP_SYSTEM 2L
Definition at line 352 of file ntmmapi.h.
Referenced by NtLockVirtualMemory(), and NtUnlockVirtualMemory().
#define MEM_4MB_PAGES 0x80000000
Definition at line 335 of file ntmmapi.h.
#define MEM_COMMIT 0x1000
Definition at line 322 of file ntmmapi.h.
Referenced by ExRaiseHardError(), MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MiQueryAddressState(), NtAllocateVirtualMemory(), NtQueryVirtualMemory(), Phase1InitializationDiscard(), RtlCreateEnvironment(), RtlCreateUserProcess(), RtlInitializeStackTraceDataBase(), RtlpCreateStack(), RtlpExtendStackTraceDataBase(), RtlSetEnvironmentStrings(), RtlSetEnvironmentVariable(), and SepAdtCopyToLsaSharedMemory().
#define MEM_DECOMMIT 0x4000
Definition at line 324 of file ntmmapi.h.
Referenced by NtFreeVirtualMemory().
#define MEM_DOS_LIM 0x40000000
Definition at line 334 of file ntmmapi.h.
Referenced by MiMapViewOfDataSection(), and NtMapViewOfSection().
#define MEM_EXECUTE_OPTION_DISABLE 0x1
Definition at line 354 of file ntmmapi.h.
Referenced by MmGetExecuteOptions(), and MmSetExecuteOptions().
#define MEM_EXECUTE_OPTION_DISABLE_THUNK_EMULATION 0x4
Definition at line 356 of file ntmmapi.h.
Referenced by MmGetExecuteOptions(), and MmSetExecuteOptions().
#define MEM_EXECUTE_OPTION_ENABLE 0x2
Definition at line 355 of file ntmmapi.h.
Referenced by MmGetExecuteOptions(), and MmSetExecuteOptions().
#define MEM_EXECUTE_OPTION_EXECUTE_DISPATCH_ENABLE 0x10
Definition at line 358 of file ntmmapi.h.
Referenced by MmGetExecuteOptions(), and MmSetExecuteOptions().
#define MEM_EXECUTE_OPTION_IMAGE_DISPATCH_ENABLE 0x20
Definition at line 359 of file ntmmapi.h.
Referenced by MmGetExecuteOptions(), and MmSetExecuteOptions().
#define MEM_EXECUTE_OPTION_PERMANENT 0x8
Definition at line 357 of file ntmmapi.h.
Referenced by MmGetExecuteOptions(), and MmSetExecuteOptions().
#define MEM_EXECUTE_OPTION_VALID_FLAGS 0x3f
Definition at line 360 of file ntmmapi.h.
Referenced by MmSetExecuteOptions().
#define MEM_FREE 0x10000
Definition at line 326 of file ntmmapi.h.
Referenced by NtQueryVirtualMemory().
#define MEM_IMAGE SEC_IMAGE
Definition at line 347 of file ntmmapi.h.
Referenced by NtQueryVirtualMemory().
#define MEM_LARGE_PAGES 0x20000000
Definition at line 333 of file ntmmapi.h.
Referenced by MiMapViewOfImageSection(), MiMapViewOfPhysicalSection(), MmInitializeProcessAddressSpace(), NtAllocateVirtualMemory(), NtMapViewOfSection(), and PsMapSystemDll().
#define MEM_MAPPED 0x40000
Definition at line 328 of file ntmmapi.h.
Referenced by NtQueryVirtualMemory().
#define MEM_PHYSICAL 0x400000
Definition at line 332 of file ntmmapi.h.
Referenced by NtAllocateVirtualMemory().
#define MEM_PRIVATE 0x20000
Definition at line 327 of file ntmmapi.h.
Referenced by NtQueryVirtualMemory().
#define MEM_RELEASE 0x8000
Definition at line 325 of file ntmmapi.h.
Referenced by ExRaiseHardError(), NtFreeVirtualMemory(), Phase1InitializationDiscard(), PspExitThread(), RtlCreateEnvironment(), RtlDestroyEnvironment(), RtlFreeUserThreadStack(), RtlpFreeStack(), RtlSetEnvironmentStrings(), RtlSetEnvironmentVariable(), SepAdtCopyToLsaSharedMemory(), and SepRmCallLsa().
#define MEM_RESERVE 0x2000
Definition at line 323 of file ntmmapi.h.
Referenced by MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MiMapViewOfDataSection(), MiMapViewOfPhysicalSection(), MiQueryAddressState(), MmMapViewOfSection(), NtAllocateVirtualMemory(), NtMapViewOfSection(), NtQueryVirtualMemory(), RtlCreateUserProcess(), and RtlpCreateStack().
#define MEM_RESET 0x80000
Definition at line 329 of file ntmmapi.h.
Referenced by NtAllocateVirtualMemory().
#define MEM_TOP_DOWN 0x100000
Definition at line 330 of file ntmmapi.h.
Referenced by MiMapViewOfDataSection(), MiMapViewOfPhysicalSection(), MmCreatePeb(), NtAllocateVirtualMemory(), and NtMapViewOfSection().
#define MEM_WRITE_WATCH 0x200000
Definition at line 331 of file ntmmapi.h.
Referenced by NtAllocateVirtualMemory().
#define MMPFNLIST_ACTIVE 6
Definition at line 139 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNLIST_BAD 5
Definition at line 138 of file ntmmapi.h.
#define MMPFNLIST_FREE 1
Definition at line 134 of file ntmmapi.h.
#define MMPFNLIST_MODIFIED 3
Definition at line 136 of file ntmmapi.h.
#define MMPFNLIST_MODIFIEDNOWRITE 4
Definition at line 137 of file ntmmapi.h.
#define MMPFNLIST_STANDBY 2
Definition at line 135 of file ntmmapi.h.
#define MMPFNLIST_TRANSITION 7
Definition at line 140 of file ntmmapi.h.
#define MMPFNLIST_ZERO 0
Definition at line 133 of file ntmmapi.h.
#define MMPFNUSE_AWEPAGE 9
Definition at line 151 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_DRIVERLOCKPAGE 10
Definition at line 152 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_FILE 1
Definition at line 143 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_METAFILE 8
Definition at line 150 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_NONPAGEDPOOL 5
Definition at line 147 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_PAGEDPOOL 4
Definition at line 146 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_PAGEFILEMAPPED 2
Definition at line 144 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_PAGETABLE 3
Definition at line 145 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_PROCESSPRIVATE 0
Definition at line 142 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_SESSIONPRIVATE 7
Definition at line 149 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define MMPFNUSE_SYSTEMPTE 6
Definition at line 148 of file ntmmapi.h.
Referenced by MiIdentifyPfn().
#define PAGE_EXECUTE 0x10
Definition at line 312 of file ntmmapi.h.
Referenced by MiLoadImageSection(), MmCheckSystemImage(), MmLoadSystemImage(), PsLocateSystemDll(), and RtlCreateUserProcess().
#define PAGE_EXECUTE_READ 0x20
Definition at line 313 of file ntmmapi.h.
#define PAGE_EXECUTE_READWRITE 0x40
Definition at line 314 of file ntmmapi.h.
Referenced by KiOpPatchCode(), MiCreateDataFileMap(), MiProtectVirtualMemory(), MiSectionDelete(), MiSectionInitialization(), MiSessionWideReserveImageAddress(), MiSetProtectionOnSection(), MmCreateSection(), MmExtendSection(), and MmMapViewOfSection().
#define PAGE_EXECUTE_WRITECOPY 0x80
Definition at line 315 of file ntmmapi.h.
Referenced by MiProtectVirtualMemory(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
#define PAGE_GUARD 0x100
Definition at line 316 of file ntmmapi.h.
Referenced by MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MiIsProtectionCompatible(), MiIsPteProtectionCompatible(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MiSetProtectionOnSection(), MmCreateSection(), NtAllocateVirtualMemory(), NtCreateSection(), and RtlpCreateStack().
#define PAGE_NOACCESS 0x01
Definition at line 308 of file ntmmapi.h.
Referenced by MiGetPageProtection(), MiGetWorkingSetInfoList(), MiMakeProtectionMask(), MiProtectAweRegion(), MiProtectVirtualMemory(), MiQueryAddressState(), MiSetProtectionOnSection(), MmCreateSection(), NtAllocateVirtualMemory(), NtCreateSection(), and NtQueryVirtualMemory().
#define PAGE_NOCACHE 0x200
Definition at line 317 of file ntmmapi.h.
Referenced by MiIsProtectionCompatible(), MiIsPteProtectionCompatible(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MmCreateSection(), MmMapViewOfSection(), NtAllocateVirtualMemory(), and NtCreateSection().
#define PAGE_READONLY 0x02
Definition at line 309 of file ntmmapi.h.
Referenced by CmpSetValueKeyExisting(), FsRtlCreateSectionForDataScan(), KiI386PentiumLockErrataFixup(), MiGetPageProtection(), MiGetWorkingSetInfoList(), MiProtectAweRegion(), MiQueryAddressState(), MiSecureVirtualMemory(), MmCreatePeb(), and NtQueryVirtualMemory().
#define PAGE_READWRITE 0x04
Definition at line 310 of file ntmmapi.h.
Referenced by CcInitializeCacheMap(), ExRaiseHardError(), FsRtlCreateSectionForDataScan(), MiCheckForUserStackOverflow(), MiClearStackGuardBits(), MiCreateDataFileMap(), MiGetPageProtection(), MiGetWorkingSetInfoList(), MiInPageSingleKernelStack(), MiProtectAweRegion(), MiProtectVirtualMemory(), MiQueryAddressState(), MiSectionDelete(), MiSetProtectionOnSection(), MmCreateSection(), MmExtendSection(), MmInitializeProcessAddressSpace(), MmMapViewOfSection(), NtAcceptConnectPort(), NtAllocateVirtualMemory(), NtSecureConnectPort(), Phase1InitializationDiscard(), PsMapSystemDll(), RtlCreateEnvironment(), RtlCreateUserProcess(), RtlInitializeStackTraceDataBase(), RtlpCreateStack(), RtlpExtendStackTraceDataBase(), RtlSetEnvironmentStrings(), RtlSetEnvironmentVariable(), SepAdtCopyToLsaSharedMemory(), and SepRmCommandServerThreadInit().
#define PAGE_WRITECOMBINE 0x400
Definition at line 318 of file ntmmapi.h.
Referenced by MiIsProtectionCompatible(), MiIsPteProtectionCompatible(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MmCreateSection(), MmMapViewOfSection(), NtAllocateVirtualMemory(), and NtCreateSection().
#define PAGE_WRITECOPY 0x08
Definition at line 311 of file ntmmapi.h.
Referenced by MiProtectVirtualMemory(), MiSetProtectionOnSection(), and NtAllocateVirtualMemory().
#define SEC_BASED 0x200000
Definition at line 337 of file ntmmapi.h.
Referenced by MiCreatePagingFileMap(), MmCreateSection(), NtCreateSection(), and NtQuerySection().
#define SEC_COMMIT 0x8000000
Definition at line 342 of file ntmmapi.h.
Referenced by CcInitializeCacheMap(), FsRtlCreateSectionForDataScan(), MiCreatePagingFileMap(), MiSessionWideReserveImageAddress(), MmCheckSystemImage(), MmCreateSection(), NtCreateSection(), NtQuerySection(), Phase1InitializationDiscard(), and SepRmCommandServerThreadInit().
#define SEC_FILE 0x800000
Definition at line 339 of file ntmmapi.h.
Referenced by FsRtlCreateSectionForDataScan(), and NtQuerySection().
#define SEC_GLOBAL 0x20000000
Definition at line 344 of file ntmmapi.h.
Referenced by NtQuerySection().
#define SEC_IMAGE 0x1000000
Definition at line 340 of file ntmmapi.h.
Referenced by MmCheckSystemImage(), MmCreateSection(), MmLoadSystemImage(), NtCreateSection(), NtQuerySection(), PsLocateSystemDll(), and RtlCreateUserProcess().
#define SEC_LARGE_PAGES 0x80000000
Definition at line 345 of file ntmmapi.h.
Referenced by MiCreatePagingFileMap(), MmCreateSection(), and NtCreateSection().
#define SEC_NO_CHANGE 0x400000
Definition at line 338 of file ntmmapi.h.
Referenced by MiMapViewOfDataSection(), MmCreatePeb(), MmCreateSection(), NtCreateSection(), and NtMapViewOfSection().
#define SEC_NOCACHE 0x10000000
Definition at line 343 of file ntmmapi.h.
Referenced by MmCreateSection(), NtCreateSection(), and NtQuerySection().
#define SEC_RESERVE 0x4000000
Definition at line 341 of file ntmmapi.h.
Referenced by MiCreatePagingFileMap(), MmCreateSection(), NtCreateSection(), and NtQuerySection().
#define SECTION_ALL_ACCESS
Value:
(STANDARD_RIGHTS_REQUIRED|SECTION_QUERY|\
                            SECTION_MAP_WRITE |      \
                            SECTION_MAP_READ |       \
                            SECTION_MAP_EXECUTE |    \
                            SECTION_EXTEND_SIZE)
Definition at line 299 of file ntmmapi.h.
Referenced by MiSectionInitialization(), MiSessionWideReserveImageAddress(), MmLoadSystemImage(), Phase1InitializationDiscard(), PsLocateSystemDll(), RtlCreateUserProcess(), and SepRmCommandServerThreadInit().
#define SECTION_EXTEND_SIZE 0x0010
Definition at line 296 of file ntmmapi.h.
Referenced by NtExtendSection().
#define SECTION_MAP_EXECUTE 0x0008
Definition at line 295 of file ntmmapi.h.
Referenced by MiSessionWideReserveImageAddress(), MmCheckSystemImage(), MmLoadSystemImage(), and PspCreateProcess().
#define SECTION_MAP_EXECUTE_EXPLICIT 0x0020
Definition at line 297 of file ntmmapi.h.
#define SECTION_MAP_READ 0x0004
Definition at line 294 of file ntmmapi.h.
Referenced by CcInitializeCacheMap(), MiSectionInitialization(), MmLoadSystemImage(), NtAcceptConnectPort(), and NtSecureConnectPort().
#define SECTION_MAP_WRITE 0x0002
Definition at line 293 of file ntmmapi.h.
Referenced by CcInitializeCacheMap(), NtAcceptConnectPort(), and NtSecureConnectPort().
#define SECTION_QUERY 0x0001
Definition at line 292 of file ntmmapi.h.
Referenced by CcInitializeCacheMap(), and NtQuerySection().
#define SEGMENT_ALL_ACCESS SECTION_ALL_ACCESS
Definition at line 306 of file ntmmapi.h.
#define WRITE_WATCH_FLAG_RESET 0x01
Definition at line 349 of file ntmmapi.h.
Referenced by NtGetWriteWatch().
Typedef Documentation
typedef struct _FILEOFFSET_INFORMATION FILEOFFSET_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION MEMORY_BASIC_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION32 MEMORY_BASIC_INFORMATION32
typedef struct _MEMORY_FRAME_INFORMATION MEMORY_FRAME_INFORMATION
typedef enum _MEMORY_INFORMATION_CLASS MEMORY_INFORMATION_CLASS
typedef struct _MEMORY_WORKING_SET_BLOCK MEMORY_WORKING_SET_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_BLOCK MEMORY_WORKING_SET_EX_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_INFORMATION MEMORY_WORKING_SET_EX_INFORMATION
typedef struct _MEMORY_WORKING_SET_INFORMATION MEMORY_WORKING_SET_INFORMATION
typedef struct _MMPFN_IDENTITY MMPFN_IDENTITY
typedef struct _MMPFN_MEMSNAP_INFORMATION MMPFN_MEMSNAP_INFORMATION
typedef struct _PAGEDIR_INFORMATION PAGEDIR_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION * PMEMORY_BASIC_INFORMATION
typedef struct _MEMORY_BASIC_INFORMATION32 * PMEMORY_BASIC_INFORMATION32
typedef struct _MEMORY_WORKING_SET_BLOCK * PMEMORY_WORKING_SET_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_BLOCK * PMEMORY_WORKING_SET_EX_BLOCK
typedef struct _MEMORY_WORKING_SET_EX_INFORMATION * PMEMORY_WORKING_SET_EX_INFORMATION
typedef struct _MEMORY_WORKING_SET_INFORMATION * PMEMORY_WORKING_SET_INFORMATION
typedef struct _MMPFN_IDENTITY * PMMPFN_IDENTITY
typedef struct _MMPFN_MEMSNAP_INFORMATION * PMMPFN_MEMSNAP_INFORMATION
typedef struct _SECTIONBASICINFO * PSECTION_BASIC_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION * PSECTION_IMAGE_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION64 * PSECTION_IMAGE_INFORMATION64
typedef struct _SECTIONBASICINFO SECTION_BASIC_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION SECTION_IMAGE_INFORMATION
typedef struct _SECTION_IMAGE_INFORMATION64 SECTION_IMAGE_INFORMATION64
typedef enum _SECTION_INFORMATION_CLASS SECTION_INFORMATION_CLASS
typedef enum _SECTION_INHERIT SECTION_INHERIT
Enumeration Type Documentation
enum _MEMORY_INFORMATION_CLASS
Enumerator
MemoryBasicInformation
MemoryMappedFilenameInformation
MemoryRegionInformation
MemoryWorkingSetExInformation
Definition at line 30 of file ntmmapi.h.
enum _SECTION_INFORMATION_CLASS
Enumerator
SectionBasicInformation
SectionImageInformation
MaxSectionInfoClass
Definition at line 193 of file ntmmapi.h.
enum _SECTION_INHERIT
Enumerator
ViewShare
ViewUnmap
Definition at line 282 of file ntmmapi.h.
Function Documentation
C_ASSERT (sizeof(MEMORY_BASIC_INFORMATION) = =sizeof(MEMORY_BASIC_INFORMATION32))
struct DECLSPEC_ALIGN (16)
Definition at line 65 of file ntmmapi.h.
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __out_ecount *NumberOfPages PULONG_PTR UserPfnArray)
Definition at line 1415 of file physical.c.
References _4gb, ASSERT, ASSERT64, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _MMPFN::AweReferenceCount, _RTL_BITMAP::Buffer, _MDL::ByteCount, ExAcquireCacheAwarePushLockExclusive(), ExAllocatePoolWithTag, except, ExFreePool(), ExReleaseCacheAwarePushLockExclusive(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, InterlockedExchangeAddSizeT, _EPROCESS::JobStatus, KeGetCurrentIrql(), KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOWEST_USABLE_PHYSICAL_ADDRESS, LOWEST_USABLE_PHYSICAL_PAGE, MAXULONG, MAXULONG_PTR, MI_ALLOCATION_IS_AWE, MI_CHECK_BIT, MI_FRAME_TO_BITMAP_INDEX, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_BIT, MiAllocateAweInfo(), MiAllocatePagesForMdl(), MiCached, MiFreeAweInfo(), MiInsertAweInfo(), MmFreePagesFromMdl(), MmHighestPossiblePhysicalPage, MmVadPhysicalPages, _MDL::Next, NonPagedPool, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PASSIVE_LEVEL, _EPROCESS::Pcb, ProbeForWrite(), ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PS_PROCESS_FLAGS_VM_DELETED, PsChangeJobMemoryUsage(), PsChargeProcessNonPagedPoolQuota(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _MMPFN::PteAddress, _AWEINFO::PushLock, _LARGE_INTEGER::QuadPart, RtlClearAllBits(), RtlCopyMemory, RtlInitializeBitMap(), SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, Status, STATUS_COMMITMENT_LIMIT, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_2, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPFN::u2, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesBitMap, and _AWEINFO::VadPhysicalPagesLimit.
NTSYSCALLAPI NTSTATUS NTAPI NtAllocateVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __in ULONG_PTR ZeroBits, __inout PSIZE_T RegionSize, __in ULONG AllocationType, __in ULONG Protect)
Definition at line 54 of file allocvm.c.
References _4gb, ASSERT, _EPROCESS::AweInfo, _MI_PHYSICAL_VIEW::BitMap, BYTES_TO_PAGES, _EPROCESS::CommitCharge, _MMVAD_FLAGS::CommitCharge, _EPROCESS::CommitChargeLimit, _EPROCESS::CommitChargePeak, _MMVAD::ControlArea, _MMVAD::EndingVpn, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExSystemExceptionFilter(), _MMVAD_FLAGS2::ExtendableFile, FALSE, _MMVAD_FLAGS2::FileOffset, _CONTROL_AREA::FilePointer, _EPROCESS::Flags, _SECTION::InitialPageProtection, InterlockedExchangeAddSizeT, _EPROCESS::Job, _EPROCESS::JobStatus, KeAcquireGuardedMutexUnsafe(), KeFeatureBits, KeGetPreviousModeByThread, KeReleaseGuardedMutexUnsafe(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), KF_LARGE_PAGE, LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, _MMPTE::Long, _CONTROL_AREA::LongFlags, _SECTION::LongFlags, _MMVAD::LongFlags, MEM_COMMIT, MEM_LARGE_PAGES, MEM_PHYSICAL, MEM_RESERVE, MEM_RESET, MEM_TOP_DOWN, MEM_WRITE_WATCH, _MMVAD_FLAGS::MemCommit, MI_64K_ALIGN, MI_ALIGN_TO_SIZE, MI_GET_USED_PTES_HANDLE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_INCREMENT_USED_PTES_BY_HANDLE, MI_IS_PTE_PROTECTION_COPY_WRITE, MI_PHYSICAL_VIEW_KEY, MI_PTE_LOOKUP_NEEDED, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_WRITE_INVALID_PTE, MI_WRITEWATCH_VIEW_KEY, MiAllocateAweInfo(), MiAllocateLargePages(), MiAweViewInserter(), MiCalculatePageCommitment(), MiChargeCommitment(), MiCheckForConflictingVad, MiCheckForConflictingVadExistence(), MiCheckSecuredVad(), MiCreatePageTablesForPhysicalRange(), MiCreatePhysicalVadRoot(), MiFindEmptyAddressRange(), MiFindEmptyAddressRangeDown, MiFlushAcquire(), MiFlushRelease(), MiFreeAweInfo(), MiGetNextVad, MiGetPageProtection(), MiGetPdeAddress, MiGetPreviousVad, MiGetProtoPteAddress, MiGetPteAddress, MiGetVirtualAddressMappedByPte, MiInsertAweInfo(), MiInsertNode(), MiInsertVad(), MiInsertVadCharges(), MiIsPteOnPdeBoundary, MiMakePdeExistAndMakeValid(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MiRemoveVad(), MiRemoveVadCharges(), MiResetVirtualMemory(), MiReturnCommitment, MiReturnPageTablePageCommitment(), MiSetProtectionOnSection(), MM_DBG_COMMIT_ALLOCVM_PROCESS, MM_DBG_COMMIT_ALLOCVM_PROCESS2, MM_DBG_COMMIT_ALLOCVM_SEGMENT, MM_DBG_COMMIT_RETURN_ALLOCVM2, MM_DBG_COMMIT_RETURN_ALLOCVM_SEGMENT, MM_DECOMMIT, MM_HIGHEST_VAD_ADDRESS, MM_INVALID_PROTECTION, MM_MAX_COMMIT, MM_MAXIMUM_ZERO_BITS, MM_MINIMUM_VA_FOR_LARGE_PAGE, MM_NOACCESS, MM_NOIRQL, MM_TRACK_COMMIT, MM_USER_ADDRESS_RANGE_LIMIT, MmExtendSection(), MmSectionCommitMutex, MmSharedCommit, _MMVAD_FLAGS::NoChange, NonPagedPool, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, _SEGMENT::NumberOfCommittedPages, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_EXECUTE_WRITECOPY, PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_READWRITE, PAGE_SIZE, PAGE_WRITECOMBINE, PAGE_WRITECOPY, PAGED_CODE, _EPROCESS::Pcb, _EPROCESS::PeakVirtualSize, _EPROCESS::PhysicalVadRoot, _MMVAD_FLAGS::PrivateMemory, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, _MMPTE_SOFTWARE::Protection, _MMVAD_FLAGS::Protection, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PS_PROCESS_FLAGS_VM_DELETED, PS_SET_BITS, PsChangeJobMemoryUsage(), PsChargeProcessNonPagedPoolQuota(), PsChargeProcessPageFileQuota(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, PsReportProcessMemoryLimitViolation(), PsReturnProcessNonPagedPoolQuota(), PsReturnProcessPageFileQuota(), _LARGE_INTEGER::QuadPart, ROUND_TO_PAGES, RtlClearAllBits(), RtlFindMostSignificantBit(), RtlInitializeBitMap(), RtlZeroMemory, SATISFY_OVERZEALOUS_COMPILER, _CONTROL_AREA::Segment, _SECTION::Segment, _SEGMENT::SegmentPteTemplate, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_ALREADY_COMMITTED, STATUS_COMMITMENT_LIMIT, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_INVALID_PARAMETER_5, STATUS_INVALID_PARAMETER_6, STATUS_NO_MEMORY, STATUS_NOT_SUPPORTED, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPTE::u, _CONTROL_AREA::u, _SECTION::u, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MMVAD::u2, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, _MI_PHYSICAL_VIEW::Vad, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD::VadFlags2, VadLargePages, VadLargePageSection, _EPROCESS::VadRoot, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, VadWriteWatch, _EPROCESS::VirtualSize, _EPROCESS::VmTopDown, and X64K.
NTSYSCALLAPI NTSTATUS NTAPI NtAreMappedFilesTheSame (__in PVOID File1MappedAsAnImage, __in PVOID File2MappedAsFile)
Definition at line 4357 of file mapview.c.
References _MMVAD::ControlArea, FALSE, _CONTROL_AREA::FilePointer, _CONTROL_AREA::Flags, _MMSECTION_FLAGS::GlobalOnlyPerSession, _SECTION_OBJECT_POINTERS::ImageSectionObject, LOCK_ADDRESS_SPACE, MiFindImageSectionObject(), MiLocateAddress(), NULL, _MMVAD_FLAGS::PrivateMemory, PsGetCurrentProcess(), _FILE_OBJECT::SectionObjectPointer, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INVALID_ADDRESS, STATUS_NOT_SAME_DEVICE, STATUS_SUCCESS, _CONTROL_AREA::u, _MMVAD::u, UNLOCK_ADDRESS_SPACE, and _MMVAD::VadFlags.
NTSYSCALLAPI NTSTATUS NTAPI NtCreatePagingFile (__in PUNICODE_STRING PageFileName, __in PLARGE_INTEGER MinimumSize, __in PLARGE_INTEGER MaximumSize, __in ULONG Priority)
Definition at line 329 of file modwrite.c.
References ACL_REVISION, _MMPAGE_FILE_EXPANSION::ActualExpansion, ASSERT, _MMPAGING_FILE::Bitmap, _MMPAGING_FILE::BootPartition, _UNICODE_STRING::Buffer, _FILE_FS_DEVICE_INFORMATION::Characteristics, CreateFileTypeNone, DACL_SECURITY_INFORMATION, DBG_UNREFERENCED_PARAMETER, DbgPrintEx(), _FILE_OBJECT::DeviceObject, DO_SYSTEM_BOOT_PARTITION, DPFLTR_INFO_LEVEL, DPFLTR_MM_ID, _FILE_END_OF_FILE_INFORMATION::EndOfFile, _MMPAGING_FILE::Entry, _MMPAGE_FILE_EXPANSION::Event, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), FALSE, _MMPAGING_FILE::File, FILE_ALL_ACCESS, FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_SYSTEM, FILE_DELETE_ON_CLOSE, FILE_DEVICE_DFS_FILE_SYSTEM, FILE_DEVICE_DFS_VOLUME, FILE_DEVICE_DISK_FILE_SYSTEM, FILE_DEVICE_NETWORK_FILE_SYSTEM, FILE_FLOPPY_DISKETTE, FILE_NO_COMPRESSION, FILE_NO_INTERMEDIATE_BUFFERING, FILE_OPEN, FILE_READ_DATA, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SUPERSEDE, FILE_WRITE_DATA, FileEndOfFileInformation, FileFsDeviceInformation, _MMPAGING_FILE::FileHandle, _MMPAGING_FILE::FreeSpace, InitializeObjectAttributes, _MMPAGE_FILE_EXPANSION::InProgress, IO_NO_PARAMETER_CHECKING, IO_OPEN_PAGING_FILE, IoCreateFile(), IoGetRelatedDeviceObject(), IoInitializeCrashDump(), IoQueryVolumeInformation(), KdPrint, KeAcquireGuardedMutex(), KeGetPreviousMode, KeInitializeEvent(), KeReleaseGuardedMutex(), KernelMode, _UNICODE_STRING::Length, _LARGE_INTEGER::LowPart, MAX_PAGE_FILES, MAXIMUM_FILENAME_LENGTH, _UNICODE_STRING::MaximumLength, _MMPAGING_FILE::MaximumSize, MI_MAXIMUM_PAGEFILE_SIZE, MiChargeCommitment(), MiCheckPageFileMapping(), MiCreateBitMap, MiExtendPagingFileMaximum(), MiInsertPageFileInList(), MiIssuePageExtendRequest(), MINIMUM_PAGE_FILE_SIZE, _MMPAGING_FILE::MinimumSize, MiReleaseModifiedWriter(), MiRemoveBitMap, MiReturnCommitment, MiZeroPageFileFirstPage(), MM_PAGING_FILE_MDLS, MmModifiedWriteClusterSize, MmNumberOfPagingFiles, MmPageFileCreationLock, MmPagingFile, MmPagingFileHeader, MmSystemPageFileLocated, MmTotalCommitLimit, MmTotalCommitLimitMaximum, MmTotalCommittedPages, NonPagedPool, NotificationEvent, NT_SUCCESS, NULL, ObDereferenceObject(), OBJ_CASE_INSENSITIVE, OBJ_KERNEL_HANDLE, ObReferenceObjectByHandle, PAGE_SHIFT, PAGED_CODE, PagedPool, _MMPAGING_FILE::PageFileName, _MMPAGE_FILE_EXPANSION::PageFileNumber, _MMPAGING_FILE::PageFileNumber, _MMMOD_WRITER_MDL_ENTRY::PagingFile, _MMMOD_WRITER_MDL_ENTRY::PagingListHead, PpPagePathAssign(), PROBE_ALIGNMENT, ProbeForRead, ProbeForReadSmallStructure, _LARGE_INTEGER::QuadPart, _MMPAGE_FILE_EXPANSION::RequestedExpansionSize, ROUND64_TO_PAGES, RtlAddAccessAllowedAce(), RtlClearBits(), RtlCopyMemory, RtlCreateAcl(), RtlCreateSecurityDescriptor(), RtlLengthSid(), RtlSetAllBits(), RtlSetDaclSecurityDescriptor(), RtlZeroMemory, SeAliasAdminsSid, SeCreatePagefilePrivilege, _FILE_OBJECT::SectionObjectPointer, SECURITY_DESCRIPTOR_REVISION, _MMPAGE_FILE_EXPANSION::Segment, SeLocalSystemSid, SeSinglePrivilegeCheck(), _MMPAGING_FILE::Size, Status, _IO_STATUS_BLOCK::Status, STATUS_DISK_FULL, STATUS_FLOPPY_VOLUME, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_NOT_FOUND, STATUS_OBJECT_NAME_INVALID, STATUS_PRIVILEGE_NOT_HELD, STATUS_SUCCESS, STATUS_TOO_MANY_PAGING_FILES, STATUS_UNRECOGNIZED_VOLUME, SYNCHRONIZE, TRUE, WRITE_DAC, ZwClose(), ZwSetInformationFile(), and ZwSetSecurityObject().
NTSYSCALLAPI NTSTATUS NTAPI NtCreateSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in_opt POBJECT_ATTRIBUTES ObjectAttributes, __in_opt PLARGE_INTEGER MaximumSize, __in ULONG SectionPageProtection, __in ULONG AllocationAttributes, __in_opt HANDLE FileHandle)
Definition at line 132 of file creasect.c.
References ARGUMENT_PRESENT, ASSERT, CcZeroEndOfLastPage(), _SEGMENT::ControlArea, DISPATCH_LEVEL, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CONTROL_AREA::FilePointer, Handle, KeDelayExecutionThread(), KeGetCurrentIrql(), KeGetPreviousMode, KernelMode, MmCreateSection(), MmHalfSecond, NT_SUCCESS, NULL, ObInsertObject(), PAGE_GUARD, PAGE_NOACCESS, PAGE_NOCACHE, PAGE_WRITECOMBINE, PROBE_ALIGNMENT, ProbeForReadSmallStructure, ProbeForWriteHandle, SEC_BASED, SEC_COMMIT, SEC_IMAGE, SEC_LARGE_PAGES, SEC_NO_CHANGE, SEC_NOCACHE, SEC_RESERVE, _CONTROL_AREA::Segment, Status, STATUS_FILE_LOCK_CONFLICT, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_6, and ZERO_LARGE.
NTSYSCALLAPI NTSTATUS NTAPI NtExtendSection (__in HANDLE SectionHandle, __inout PLARGE_INTEGER NewSectionSize)
Definition at line 86 of file extsect.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, MmExtendSection(), MmSectionObjectType, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROBE_ALIGNMENT, ProbeForWriteSmallStructure(), SECTION_EXTEND_SIZE, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtFlushInstructionCache (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in SIZE_T Length)
Definition at line 149 of file flushbuf.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousMode, KernelMode, KeStackAttachProcess(), KeSweepIcache, KeSweepIcacheRange, KeUnstackDetachProcess(), MiFlushRangeFilter(), NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _EPROCESS::Pcb, ProbeForRead, PROCESS_VM_WRITE, PsProcessType, Status, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtFlushVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __out PIO_STATUS_BLOCK IoStatus)
Definition at line 43 of file flushsec.c.
References except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousMode, KernelMode, MM_HIGHEST_USER_ADDRESS, MmFlushVirtualMemory(), NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGED_CODE, ProbeForWriteIoStatus, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PsProcessType, Status, and STATUS_INVALID_PARAMETER_2.
NTSYSCALLAPI NTSTATUS NTAPI NtFlushWriteBuffer (VOID)
Definition at line 39 of file flushbuf.c.
References KeFlushWriteBuffer(), PAGED_CODE, and STATUS_SUCCESS.
NTSYSCALLAPI NTSTATUS NTAPI NtFreeUserPhysicalPages (__in HANDLE ProcessHandle, __inout PULONG_PTR NumberOfPages, __in_ecount *NumberOfPages PULONG_PTR UserPfnArray)
Definition at line 2013 of file physical.c.
References _4gb, ASSERT, ASSERT64, _MMPFN::AweAllocation, _EPROCESS::AweInfo, _RTL_BITMAP::Buffer, _MDL::ByteCount, _MMPTE_FLUSH_LIST::Count, ExAcquireCacheAwarePushLockExclusive(), except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExReleaseCacheAwarePushLockExclusive(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedExchangeAddSizeT, _EPROCESS::JobStatus, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeMemoryBarrier(), KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOWEST_USABLE_PHYSICAL_PAGE, MAXULONG, MI_CHECK_BIT, MI_CLEAR_BIT, MI_FLUSH_PROCESS_TB, MI_FRAME_TO_BITMAP_INDEX, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PFN_DELETED, MI_WRITE_ZERO_PTE_NO_LOGGING, MiCaptureUlongPtrArray(), MiFlushPteList(), MiGetVirtualAddressMappedByPte, MM_MAXIMUM_FLUSH_COUNT, MmCreateMdl(), MmFreePagesFromMdl(), MmInitializeMdl, MmVadPhysicalPages, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, NumberOfBytes, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PASSIVE_LEVEL, _EPROCESS::Pcb, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_JOB_STATUS_REPORT_PHYSICAL_PAGE_CHANGES, PS_PROCESS_FLAGS_VM_DELETED, PsChangeJobMemoryUsage(), PsGetCurrentProcess(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _MMPFN::PteAddress, _AWEINFO::PushLock, RtlCopyMemory, SATISFY_OVERZEALOUS_COMPILER, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMPFN::u2, _MMPFN::u4, UNLOCK_ADDRESS_SPACE, _AWEINFO::VadPhysicalPages, _AWEINFO::VadPhysicalPagesBitMap, _MMPTE_HARDWARE::Valid, and VERY_SMALL_COPY_STACK_SIZE.
NTSYSCALLAPI NTSTATUS NTAPI NtFreeVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG FreeType)
Definition at line 42 of file freevm.c.
References ASSERT, _EPROCESS::CommitCharge, _MMVAD_FLAGS::CommitCharge, _MMVAD::EndingVpn, _MMVAD_SHORT::EndingVpn, ExAllocatePoolWithTag, except, EXCEPTION_EXECUTE_HANDLER, ExFreePool(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _EPROCESS::JobStatus, KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MEM_DECOMMIT, MEM_RELEASE, MI_INCREMENT_TOTAL_PROCESS_COMMIT, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiAweViewRemover(), MiCalculatePageCommitment(), MiCheckSecuredVad(), MiDecommitPages(), MiDeletePageTablesForPhysicalRange(), MiDeleteVirtualAddresses(), MiFreeLargePages(), MiGetNextVad, MiGetPreviousVad, MiGetPteAddress, MiInsertVad(), MiInsertVadCharges(), MiLocateAddress(), MiPhysicalViewRemover(), MiReleasePhysicalCharges(), MiRemoveUserPhysicalPagesVad(), MiRemoveVad(), MiRemoveVadCharges(), MiReturnCommitment, MiReturnPageTablePageCommitment(), MiUnmapViewOfSection(), MM_DBG_COMMIT_RETURN_NTFREEVM1, MM_DBG_COMMIT_RETURN_NTFREEVM2, MM_HIGHEST_USER_ADDRESS, MM_SECURE_DELETE_CHECK, MM_TRACK_COMMIT, _MMVAD_FLAGS::NoChange, NonPagedPool, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _EPROCESS::Pcb, _MMVAD_FLAGS::PrivateMemory, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_JOB_STATUS_REPORT_COMMIT_CHANGES, PS_PROCESS_FLAGS_VM_DELETED, PsChangeJobMemoryUsage(), PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, PsReturnProcessPageFileQuota(), _MMVAD::StartingVpn, _MMVAD_SHORT::StartingVpn, Status, STATUS_FREE_VM_NOT_AT_BASE, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_MEMORY_NOT_ALLOCATED, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_UNABLE_TO_DELETE_SECTION, STATUS_UNABLE_TO_FREE_VM, _ETHREAD::Tcb, TRUE, _MMVAD::u, _MMVAD_SHORT::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, UNMAP_ADDRESS_SPACE_HELD, UNMAP_ROTATE_PHYSICAL_OK, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, _MMVAD_SHORT::VadFlags, VadLargePages, VadRotatePhysical, _MMVAD_FLAGS::VadType, VadWriteWatch, and _EPROCESS::VirtualSize.
Referenced by RtlFreeUserThreadStack().
NTSYSCALLAPI NTSTATUS NTAPI NtGetWriteWatch (__in HANDLE ProcessHandle, __in ULONG Flags, __in PVOID BaseAddress, __in SIZE_T RegionSize, __out_ecount *EntriesInUserAddressArray PVOID * UserAddressArray, __inout PULONG_PTR EntriesInUserAddressArray, __out PULONG Granularity)
Definition at line 25 of file wrtwatch.c.
References ASSERT, _MI_PHYSICAL_VIEW::BitMap, COPY_STACK_SIZE, _MMPTE_FLUSH_LIST::Count, _MMPFN::e1, _MI_PHYSICAL_VIEW::EndingVpn, ExAllocatePoolWithTag, except, ExFreePool(), ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, KeGetCurrentIrql(), KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_PFN, LOCK_WS, MAXULONG_PTR, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_WORKING_SET_FROM_PTE, MI_IS_PTE_DIRTY, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_SET_PTE_IN_WORKING_SET, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiFindNodeOrParent(), MiFlushPteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MM_HIGHEST_VAD_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, NO_BITS_FOUND, NonPagedPool, NT_SUCCESS, NtCurrentProcess, NULL, NumberOfBytes, ObDereferenceObject(), ObReferenceObjectByHandle, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, PASSIVE_LEVEL, _EPROCESS::Pcb, _EPROCESS::PhysicalVadRoot, ProbeForWrite(), ProbeForWriteUlong, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, RtlCheckBit, RtlClearBit(), RtlCopyMemory, RtlFindSetBits(), SATISFY_OVERZEALOUS_COMPILER, _RTL_BITMAP::SizeOfBitMap, _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_INVALID_PARAMETER_5, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS, _MI_PHYSICAL_VIEW::Vad, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, VadWriteWatch, _MMPTE_HARDWARE::Valid, and WRITE_WATCH_FLAG_RESET.
NTSYSCALLAPI NTSTATUS NTAPI NtLockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
Definition at line 24 of file lockvm.c.
References _ETHREAD::AddressSpaceOwner, ASSERT, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE::Hard, KeAreAllApcsDisabled(), KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MAP_PROCESS, MAP_SYSTEM, MI_PFN_ELEMENT, MI_VPN_TO_VA, MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiIsAddressValid(), MiLocateAddress(), MiLocateWsle(), MiMakePdeExistAndMakeValid(), _MMSUPPORT::MinimumWorkingSetSize, MiSwapWslEntries(), MM_FLUID_WORKING_SET, MM_HIGHEST_USER_ADDRESS, MM_NOIRQL, MmWorkingSetList, MmWsle, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsProcessType, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), Status, STATUS_ACCESS_VIOLATION, STATUS_INCOMPATIBLE_FILE_MAP, STATUS_INVALID_PARAMETER, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, STATUS_WAS_LOCKED, STATUS_WORKING_SET_QUOTA, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u1, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadLargePageSection, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMPFN::WsIndex, and WSLE_NULL_INDEX.
NTSYSCALLAPI NTSTATUS NTAPI NtMapUserPhysicalPages (__in PVOID VirtualAddress, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
Definition at line 118 of file physical.c.
References ARGUMENT_PRESENT, ASSERT, _EPROCESS::AweInfo, _AWEINFO::AweVadRoot, _RTL_BITMAP::Buffer, COPY_STACK_SIZE, _MMPTE_FLUSH_LIST::Count, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), ExAllocatePoolWithTag, ExFreePool(), ExReleaseCacheAwarePushLockShared(), _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedCompareExchangePointer, InterlockedExchangePte, InterlockedZeroPointer, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KeMemoryBarrier(), _MMPTE::Long, MAXULONG_PTR, MI_CHECK_BIT, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PTE_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiCaptureUlongPtrArray(), MiFindNodeOrParent(), MiFlushPteList(), MiGetPteAddress, MiHighestUserPte, MM_MAXIMUM_FLUSH_COUNT, MM_READWRITE, NonPagedPool, NOTHING, NT_SUCCESS, NULL, NumberOfBytes, PAGE_ALIGN, PAGE_SHIFT, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _AWEINFO::PhysicalViewHint, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _AWEINFO::PushLock, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, _MMPTE::u, _MMPFN::u2, VadAwe, _AWEINFO::VadPhysicalPagesBitMap, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and ZeroPte.
NTSYSCALLAPI NTSTATUS NTAPI NtMapUserPhysicalPagesScatter (__in_ecount(NumberOfPages) PVOID * VirtualAddresses, __in ULONG_PTR NumberOfPages, __in_ecount_opt(NumberOfPages) PULONG_PTR UserPfnArray)
Definition at line 633 of file physical.c.
References ARGUMENT_PRESENT, ASSERT, _EPROCESS::AweInfo, _AWEINFO::AweVadRoot, _RTL_BITMAP::Buffer, _MMPTE_FLUSH_LIST::Count, _MI_PHYSICAL_VIEW::EndingVpn, ExAcquireCacheAwarePushLockShared(), ExAllocatePoolWithTag, ExFreePool(), ExReleaseCacheAwarePushLockShared(), _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, InterlockedCompareExchangePointer, InterlockedExchangePte, InterlockedZeroPointer, KeEnterGuardedRegionThread(), KeGetCurrentIrql(), KeGetCurrentProcessorNumber(), KeLeaveGuardedRegionThread(), KeMemoryBarrier(), _MMPTE::Long, MAXULONG_PTR, MI_CHECK_BIT, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_PFN_IS_AWE, MI_SET_PTE_DIRTY, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MiCaptureUlongPtrArray(), MiFindNodeOrParent(), MiFlushPteList(), MiGetPteAddress, MiHighestUserPte, MM_MAXIMUM_FLUSH_COUNT, MM_READWRITE, NonPagedPool, NT_SUCCESS, NULL, NumberOfBytes, PAGE_SIZE, _MMPTE_HARDWARE::PageFrameNumber, PASSIVE_LEVEL, _AWEINFO::PhysicalViewHint, PsGetCurrentProcessByThread, PsGetCurrentThread(), _MMPFN::PteAddress, _AWEINFO::PushLock, _MMPFN::ShareCount, _RTL_BITMAP::SizeOfBitMap, SMALL_COPY_STACK_SIZE, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_INSUFFICIENT_RESOURCES, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, _MMPTE::u, _MMVAD::u, _MMPFN::u2, _MI_PHYSICAL_VIEW::Vad, VadAwe, _MMVAD::VadFlags, _AWEINFO::VadPhysicalPagesBitMap, _MMVAD_FLAGS::VadType, _MI_PHYSICAL_VIEW::VadType, _MMPTE_HARDWARE::Valid, and ZeroPte.
NTSYSCALLAPI NTSTATUS NTAPI NtMapViewOfSection (__in HANDLE SectionHandle, __in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __in ULONG_PTR ZeroBits, __in SIZE_T CommitSize, __inout_opt PLARGE_INTEGER SectionOffset, __inout PSIZE_T ViewSize, __in SECTION_INHERIT InheritDisposition, __in ULONG AllocationType, __in ULONG Win32Protect)
Definition at line 181 of file mapview.c.
References ARGUMENT_PRESENT, _SEGMENT::ControlArea, DbgkMapViewOfSection(), except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), _CONTROL_AREA::Flags, KeGetPreviousModeByThread, KernelMode, _LARGE_INTEGER::LowPart, MEM_DOS_LIM, MEM_LARGE_PAGES, MEM_RESERVE, MEM_TOP_DOWN, MiMakeProtectionMask(), MM_HIGHEST_VAD_ADDRESS, MM_INVALID_PROTECTION, MM_MAXIMUM_ZERO_BITS, MM_USER_ADDRESS_RANGE_LIMIT, MmHighestPhysicalPage, MmMakeSectionAccess, MmMapViewOfSection(), MmSectionObjectType, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_SHIFT, PAGE_SIZE, PAGED_CODE, _MMSECTION_FLAGS::PhysicalMemory, PROBE_ALIGNMENT, ProbeForWritePointer, ProbeForWriteSmallStructure(), ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _LARGE_INTEGER::QuadPart, RtlFindMostSignificantBit(), SEC_NO_CHANGE, _SECTION::Segment, Status, STATUS_CONFLICTING_ADDRESSES, STATUS_IMAGE_NOT_AT_BASE, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_3, STATUS_INVALID_PARAMETER_4, STATUS_INVALID_PARAMETER_6, STATUS_INVALID_PARAMETER_8, STATUS_INVALID_PARAMETER_9, STATUS_MAPPED_ALIGNMENT, _ETHREAD::Tcb, _CONTROL_AREA::u, ViewShare, ViewUnmap, X64K, and ZERO_LARGE.
NTSYSCALLAPI NTSTATUS NTAPI NtOpenSection (__out PHANDLE SectionHandle, __in ACCESS_MASK DesiredAccess, __in POBJECT_ATTRIBUTES ObjectAttributes)
Definition at line 4982 of file creasect.c.
References except, EXCEPTION_EXECUTE_HANDLER, Handle, KeGetPreviousMode, KernelMode, MmSectionObjectType, NULL, ObOpenObjectByName(), PAGED_CODE, ProbeForWriteHandle, and Status.
NTSYSCALLAPI NTSTATUS NTAPI NtProtectVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG NewProtect, __out PULONG OldProtect)
Definition at line 50 of file protect.c.
References except, EXCEPTION_EXECUTE_HANDLER, FALSE, KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), MiMakeProtectionMask(), MiProtectVirtualMemory(), MM_HIGHEST_USER_ADDRESS, MM_INVALID_PROTECTION, NOTHING, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, _EPROCESS::Pcb, ProbeForWritePointer, ProbeForWriteUlong, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, Status, STATUS_INVALID_PAGE_PROTECTION, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, _ETHREAD::Tcb, and TRUE.
NTSYSCALLAPI NTSTATUS NTAPI NtQuerySection (__in HANDLE SectionHandle, __in SECTION_INFORMATION_CLASS SectionInformationClass, __out_bcount(SectionInformationLength) PVOID SectionInformation, __in SIZE_T SectionInformationLength, __out_opt PSIZE_T ReturnLength)
Definition at line 28 of file querysec.c.
References _SECTION::Address, ARGUMENT_PRESENT, _MMSECTION_FLAGS::Based, _MMSECTION_FLAGS::Commit, _SEGMENT::ControlArea, except, EXCEPTION_EXECUTE_HANDLER, _MMSECTION_FLAGS::File, _CONTROL_AREA::Flags, _SECTION::Flags, _MMSECTION_FLAGS::GlobalMemory, _MMSECTION_FLAGS::Image, _SEGMENT::ImageInformation, KeGetPreviousMode, KernelMode, MmSectionObjectType, _MMSECTION_FLAGS::NoCache, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWrite(), ProbeForWriteUlong_ptr, _MMSECTION_FLAGS::Reserve, SEC_BASED, SEC_COMMIT, SEC_FILE, SEC_GLOBAL, SEC_IMAGE, SEC_NOCACHE, SEC_RESERVE, SECTION_QUERY, SectionBasicInformation, SectionImageInformation, _SECTION::Segment, _SECTION::SizeOfSection, _MMADDRESS_NODE::StartingVpn, Status, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_INFO_CLASS, STATUS_SECTION_NOT_IMAGE, _CONTROL_AREA::u, _SECTION::u, and _SEGMENT::u2.
NTSYSCALLAPI NTSTATUS NTAPI NtQueryVirtualMemory (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in MEMORY_INFORMATION_CLASS MemoryInformationClass, __out_bcount(MemoryInformationLength) PVOID MemoryInformation, __in SIZE_T MemoryInformationLength, __out_opt PSIZE_T ReturnLength)
Definition at line 39 of file queryvm.c.
References _2gb, _4gb, _MEMORY_BASIC_INFORMATION::AllocationBase, _MEMORY_BASIC_INFORMATION::AllocationProtect, ARGUMENT_PRESENT, ASSERT, _MM_AVL_TABLE::BalancedRoot, _MEMORY_BASIC_INFORMATION::BaseAddress, _MMVAD::ControlArea, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, FALSE, _CONTROL_AREA::FilePointer, _EPROCESS::Flags, KeGetPreviousModeByThread, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), _MMVAD::LeftChild, LOCK_ADDRESS_SPACE, LOCK_WS_SHARED, MEM_COMMIT, MEM_FREE, MEM_IMAGE, MEM_MAPPED, MEM_PRIVATE, MEM_RESERVE, MemoryBasicInformation, MemoryMappedFilenameInformation, MemoryWorkingSetExInformation, MI_CONVERT_FROM_PTE_PROTECTION, MI_VA_TO_VPN, MI_VPN_TO_VA, MiGetNextVad, MiGetWorkingSetInfo(), MiGetWorkingSetInfoList(), MiQueryAddressState(), MM_HIGHEST_USER_ADDRESS, MM_HIGHEST_VAD_ADDRESS, MM_SHARED_USER_DATA_VA, NOTHING, NT_SUCCESS, NtCurrentProcess, NULL, _MM_AVL_TABLE::NumberGenericTableElements, ObDereferenceObject(), ObQueryNameString(), ObReferenceObject, ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_NOACCESS, PAGE_READONLY, PAGE_SIZE, _EPROCESS::Pcb, _MMVAD_FLAGS::PrivateMemory, ProbeForWrite(), ProbeForWriteUlong_ptr, PROCESS_QUERY_INFORMATION, _MEMORY_BASIC_INFORMATION::Protect, _MMVAD_FLAGS::Protection, PS_PROCESS_FLAGS_VM_DELETED, PS_PROCESS_FLAGS_WOW64_4GB_VA_SPACE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, _MEMORY_BASIC_INFORMATION::RegionSize, _MMADDRESS_NODE::RightChild, _MMVAD::RightChild, _MMVAD::StartingVpn, _MEMORY_BASIC_INFORMATION::State, Status, STATUS_FILE_INVALID, STATUS_INFO_LENGTH_MISMATCH, STATUS_INVALID_ADDRESS, STATUS_INVALID_INFO_CLASS, STATUS_INVALID_PARAMETER, STATUS_INVALID_PARAMETER_5, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, _ETHREAD::Tcb, TRUE, _MEMORY_BASIC_INFORMATION::Type, _MMVAD::u, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_SHARED, _MMVAD::VadFlags, VadImageMap, _EPROCESS::VadRoot, VadRotatePhysical, _MMVAD_FLAGS::VadType, and X64K.
NTSYSCALLAPI NTSTATUS NTAPI NtReadVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __out_bcount(BufferSize) PVOID Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesRead)
Definition at line 92 of file readwrt.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousModeByThread, KernelMode, MM_HIGHEST_USER_ADDRESS, MmCopyVirtualMemory(), NOTHING, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong_ptr, PROCESS_VM_READ, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, Status, STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by RtlFreeUserThreadStack().
NTSYSCALLAPI NTSTATUS NTAPI NtResetWriteWatch (__in HANDLE ProcessHandle, __in PVOID BaseAddress, __in SIZE_T RegionSize)
Definition at line 607 of file wrtwatch.c.
References ASSERT, _MI_PHYSICAL_VIEW::BitMap, _MMPTE_FLUSH_LIST::Count, _MMPFN::e1, _MI_PHYSICAL_VIEW::EndingVpn, FALSE, _EPROCESS::Flags, _MMPTE_FLUSH_LIST::FlushVa, _MMPTE::Hard, KeGetCurrentIrql(), KeGetPreviousModeByThread, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_PFN, LOCK_WS, MI_CAPTURE_DIRTY_BIT_TO_PFN, MI_GET_PAGE_FRAME_FROM_PTE, MI_GET_WORKING_SET_FROM_PTE, MI_IS_PTE_DIRTY, MI_MAKE_VALID_USER_PTE, MI_PFN_ELEMENT, MI_SET_PTE_IN_WORKING_SET, MI_VA_TO_VPN, MI_VPN_TO_VA, MI_VPN_TO_VA_ENDING, MI_WRITE_VALID_PTE_NEW_PROTECTION, MiFindNodeOrParent(), MiFlushPteList(), MiGetPdeAddress, MiGetPpeAddress, MiGetPteAddress, MiGetPxeAddress, MiGetVirtualAddressMappedByPte, MiIsPteOnPdeBoundary, MM_HIGHEST_VAD_ADDRESS, MM_MAXIMUM_FLUSH_COUNT, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, _MMPFN::OriginalPte, PAGE_SHIFT, PAGE_SIZE, PASSIVE_LEVEL, _EPROCESS::Pcb, _EPROCESS::PhysicalVadRoot, PROCESS_VM_OPERATION, _MMPTE_SOFTWARE::Protection, _MMPFNENTRY::PrototypePte, PS_PROCESS_FLAGS_USING_WRITE_WATCH, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, RtlClearBits(), SATISFY_OVERZEALOUS_COMPILER, _RTL_BITMAP::SizeOfBitMap, _MMPTE::Soft, _MMVAD::StartingVpn, _MI_PHYSICAL_VIEW::StartingVpn, Status, STATUS_INVALID_PARAMETER_1, STATUS_INVALID_PARAMETER_2, STATUS_INVALID_PARAMETER_3, STATUS_SUCCESS, TableFoundNode, _ETHREAD::Tcb, TRUE, _MMPTE::u, _MMVAD::u, _MI_PHYSICAL_VIEW::u, _MMPFN::u3, UNLOCK_PFN, UNLOCK_WS, _MI_PHYSICAL_VIEW::Vad, _MMVAD::VadFlags, _MMVAD_FLAGS::VadType, VadWriteWatch, and _MMPTE_HARDWARE::Valid.
NTSYSCALLAPI NTSTATUS NTAPI NtUnlockVirtualMemory (__in HANDLE ProcessHandle, __inout PVOID * BaseAddress, __inout PSIZE_T RegionSize, __in ULONG MapType)
Definition at line 571 of file lockvm.c.
References ASSERT, _MMVAD::EndingVpn, except, EXCEPTION_EXECUTE_HANDLER, ExSystemExceptionFilter(), FALSE, _EPROCESS::Flags, _MMPTE::Hard, KeGetPreviousMode, KernelMode, KeStackAttachProcess(), KeUnstackDetachProcess(), LOCK_ADDRESS_SPACE, LOCK_WS_UNSAFE, MAP_PROCESS, MAP_SYSTEM, MI_PFN_ELEMENT, MI_VPN_TO_VA, MiFreeWsle(), MiGetPteAddress, MiIsAddressValid(), MiLocateAddress(), MiLocateWsle(), MiSwapWslEntries(), MM_HIGHEST_USER_ADDRESS, MmWorkingSetList, MmWsle, NT_SUCCESS, NtCurrentProcess, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGE_ALIGN, PAGE_SIZE, PAGED_CODE, _MMPTE_HARDWARE::PageFrameNumber, _EPROCESS::Pcb, ProbeForWritePointer, ProbeForWriteUlong_ptr, PROCESS_VM_OPERATION, PS_PROCESS_FLAGS_VM_DELETED, PsGetCurrentThread(), PsProcessType, SeLockMemoryPrivilege, SeSinglePrivilegeCheck(), Status, STATUS_INVALID_PARAMETER, STATUS_NOT_LOCKED, STATUS_PRIVILEGE_NOT_HELD, STATUS_PROCESS_IS_TERMINATING, STATUS_SUCCESS, TRUE, _MMPTE::u, _MMVAD::u, _MMPFN::u1, UNLOCK_ADDRESS_SPACE, UNLOCK_WS_AND_ADDRESS_SPACE, UNLOCK_WS_UNSAFE, VadAwe, VadDevicePhysicalMemory, _MMVAD::VadFlags, VadLargePages, VadLargePageSection, VadRotatePhysical, _MMVAD_FLAGS::VadType, _MMPTE_HARDWARE::Valid, _EPROCESS::Vm, _MMPFN::WsIndex, and WSLE_NULL_INDEX.
NTSYSCALLAPI NTSTATUS NTAPI NtUnmapViewOfSection (__in HANDLE ProcessHandle, __in PVOID BaseAddress)
Definition at line 29 of file umapview.c.
References KeGetPreviousMode, MiUnmapViewOfSection(), MM_HIGHEST_USER_ADDRESS, NT_SUCCESS, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, PROCESS_VM_OPERATION, PsProcessType, Status, STATUS_NOT_MAPPED_VIEW, and UserMode.
NTSYSCALLAPI NTSTATUS NTAPI NtWriteVirtualMemory (__in HANDLE ProcessHandle, __in_opt PVOID BaseAddress, __in_bcount(BufferSize) CONST VOID * Buffer, __in SIZE_T BufferSize, __out_opt PSIZE_T NumberOfBytesWritten)
Definition at line 226 of file readwrt.c.
References ARGUMENT_PRESENT, except, EXCEPTION_EXECUTE_HANDLER, KeGetPreviousModeByThread, KernelMode, MM_HIGHEST_USER_ADDRESS, MmCopyVirtualMemory(), NOTHING, NULL, ObDereferenceObject(), ObReferenceObjectByHandle, PAGED_CODE, ProbeForWriteUlong_ptr, PROCESS_VM_WRITE, PsGetCurrentProcessByThread, PsGetCurrentThread(), PsProcessType, Status, STATUS_ACCESS_VIOLATION, STATUS_SUCCESS, and _ETHREAD::Tcb.
Referenced by RtlRemoteCall().
Variable Documentation
MEMORY_BASIC_INFORMATION64
Definition at line 75 of file ntmmapi.h.
* PMEMORY_BASIC_INFORMATION64
Definition at line 75 of file ntmmapi.h.