Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/i386/exdsptch.c File Reference
exdsptch.c File Reference
#include "ntrtlp.h"
Data Structures
struct _DISPATCHER_CONTEXT
struct HANDLERLIST
Typedefs
typedef struct _DISPATCHER_CONTEXT DISPATCHER_CONTEXT
Functions
BOOLEAN RtlDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord)
VOID RtlInvalidHandlerDetected (PVOID Handler, PULONG FunctionTable, ULONG FunctionTableLength)
BOOLEAN RtlIsValidHandler (IN PEXCEPTION_ROUTINE Handler)
EXCEPTION_DISPOSITION RtlpExecuteHandlerForException (IN PEXCEPTION_RECORD ExceptionRecord, IN PVOID EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PVOID DispatcherContext, IN PEXCEPTION_ROUTINE ExceptionRoutine)
EXCEPTION_DISPOSITION RtlpExecuteHandlerForUnwind (IN PEXCEPTION_RECORD ExceptionRecord, IN PVOID EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PVOID DispatcherContext, IN PEXCEPTION_ROUTINE ExceptionRoutine)
VOID RtlUnwind (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue)
Variables
int HandlerCount
HANDLERLIST HandlerList [5]
Typedef Documentation
typedef struct _DISPATCHER_CONTEXT DISPATCHER_CONTEXT
Function Documentation
BOOLEAN RtlDispatchException (IN PEXCEPTION_RECORD ExceptionRecord, IN PCONTEXT ContextRecord)
Definition at line 127 of file exdsptch.c.
References DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, _KPRCB::DpcStack, EXCEPTION_CHAIN_END, EXCEPTION_NESTED_CALL, EXCEPTION_NONCONTINUABLE, EXCEPTION_STACK_INVALID, _EXCEPTION_RECORD::ExceptionCode, ExceptionContinueExecution, ExceptionContinueSearch, _EXCEPTION_RECORD::ExceptionFlags, ExceptionNestedException, _EXCEPTION_RECORD::ExceptionRecord, FALSE, FLG_ENABLE_EXCEPTION_LOGGING, _EXCEPTION_REGISTRATION_RECORD::Handler, Index, KeGetCurrentIrql(), KeGetCurrentPrcb(), KERNEL_STACK_SIZE, NtGlobalFlag, _EXCEPTION_RECORD::NumberParameters, RtlIsValidHandler(), RtlpExecuteHandlerForException(), RtlpGetRegistrationHead(), RtlpGetStackLimits(), RtlpLogExceptionHandler(), RtlpLogLastExceptionDisposition(), RtlRaiseException(), STATUS_INVALID_DISPOSITION, STATUS_NONCONTINUABLE_EXCEPTION, and TRUE.
Referenced by KiDispatchException(), RtlRaiseException(), and RtlRaiseStatus().
VOID RtlInvalidHandlerDetected (PVOID Handler, PULONG FunctionTable, ULONG FunctionTableLength)
Definition at line 67 of file exdsptch.c.
Referenced by RtlIsValidHandler().
BOOLEAN RtlIsValidHandler (IN PEXCEPTION_ROUTINE Handler)
Definition at line 78 of file exdsptch.c.
References FALSE, LongToPtr, RtlInvalidHandlerDetected(), RtlLookupFunctionTable(), and TRUE.
Referenced by RtlDispatchException().
EXCEPTION_DISPOSITION RtlpExecuteHandlerForException (IN PEXCEPTION_RECORD ExceptionRecord, IN PVOID EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PVOID DispatcherContext, IN PEXCEPTION_ROUTINE ExceptionRoutine)
Referenced by RtlDispatchException().
EXCEPTION_DISPOSITION RtlpExecuteHandlerForUnwind (IN PEXCEPTION_RECORD ExceptionRecord, IN PVOID EstablisherFrame, IN OUT PCONTEXT ContextRecord, IN OUT PVOID DispatcherContext, IN PEXCEPTION_ROUTINE ExceptionRoutine)
Referenced by RtlUnwind(), and RtlUnwindEx().
VOID RtlUnwind (IN PVOID TargetFrame OPTIONAL, IN PVOID TargetIp OPTIONAL, IN PEXCEPTION_RECORD ExceptionRecord OPTIONAL, IN PVOID ReturnValue)
Definition at line 371 of file exdsptch.c.
References ARGUMENT_PRESENT, CONTEXT_CONTROL, CONTEXT_INTEGER, CONTEXT_SEGMENTS, _CONTEXT::ContextFlags, DISPATCH_LEVEL, _KPRCB::DpcRoutineActive, _KPRCB::DpcStack, _CONTEXT::Eax, _CONTEXT::Esp, EXCEPTION_CHAIN_END, EXCEPTION_EXIT_UNWIND, EXCEPTION_NONCONTINUABLE, EXCEPTION_UNWINDING, _EXCEPTION_RECORD::ExceptionAddress, _EXCEPTION_RECORD::ExceptionCode, ExceptionCollidedUnwind, ExceptionContinueSearch, _EXCEPTION_RECORD::ExceptionFlags, _EXCEPTION_RECORD::ExceptionRecord, FALSE, KeGetCurrentIrql(), KeGetCurrentPrcb(), KERNEL_STACK_SIZE, _EXCEPTION_REGISTRATION_RECORD::Next, NULL, _EXCEPTION_RECORD::NumberParameters, RtlpCaptureContext(), RtlpExecuteHandlerForUnwind(), RtlpGetRegistrationHead(), RtlpGetStackLimits(), RtlpUnlinkHandler(), RtlRaiseException(), STATUS_BAD_STACK, STATUS_INVALID_DISPOSITION, STATUS_INVALID_UNWIND_TARGET, STATUS_UNWIND, TRUE, ZwContinue(), and ZwRaiseException().
Variable Documentation
int HandlerCount
Definition at line 64 of file exdsptch.c.
HANDLERLIST HandlerList[5]
Definition at line 63 of file exdsptch.c.
Referenced by Psp386InsertVdmIoHandlerBlock().