Windows Research Kernel v1.2: C:/Windows Research Kernel/rtl/peb.c File Reference
peb.c File Reference
#include "ntrtlp.h"
Functions
NTSYSAPI NTSTATUS NTAPI RtlCheckProcessParameters (PVOID p1, PWSTR p2, PULONG p3, ULONG v1)
PPEB RtlGetCurrentPeb (VOID)
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetProcessIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetThreadIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
Function Documentation
NTSYSAPI NTSTATUS NTAPI RtlCheckProcessParameters (PVOID p1, PWSTR p2, PULONG p3, ULONG v1)
Definition at line 123 of file peb.c.
PPEB RtlGetCurrentPeb (VOID)
Definition at line 28 of file peb.c.
References PAGED_CODE, _EPROCESS::Peb, and PsGetCurrentProcess().
Referenced by RtlSetProcessIsCritical(), and RtlSetThreadIsCritical().
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetProcessIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
Definition at line 39 of file peb.c.
References ARGUMENT_PRESENT, FALSE, FLG_ENABLE_SYSTEM_CRIT_BREAKS, NtCurrentProcess, NtQueryInformationProcess(), NtSetInformationProcess(), NULL, ProcessBreakOnTermination, RtlGetCurrentPeb(), Status, and STATUS_UNSUCCESSFUL.
NTSYSAPI NTSTATUS STDAPIVCALLTYPE RtlSetThreadIsCritical (IN BOOLEAN NewValue, OUT PBOOLEAN OldValue OPTIONAL, IN BOOLEAN CheckFlag)
Definition at line 81 of file peb.c.
References ARGUMENT_PRESENT, FALSE, FLG_ENABLE_SYSTEM_CRIT_BREAKS, NtCurrentThread, NtQueryInformationThread(), NtSetInformationThread(), NULL, RtlGetCurrentPeb(), Status, STATUS_UNSUCCESSFUL, and ThreadBreakOnTermination.