Windows Research Kernel v1.2: C:/Windows Research Kernel/ke/i386/trapc.c File Reference
trapc.c File Reference
#include "ki.h"
Data Structures
struct KMOD
Macros
#define GETREG(frame, reg) ((PULONG) (((ULONG) frame)+reg))[0]
#define REG(field) ((ULONG)(&((KTRAP_FRAME *)0)->field))
Typedefs
typedef struct KMOD * PKMOD
Functions
BOOLEAN FASTCALL KeInvalidAccessAllowed (__in_opt PVOID TrapInformation)
BOOLEAN Ki386CheckDelayedNpxTrap (IN PKTRAP_FRAME UserFrame, IN PFX_SAVE_AREA NpxFrame)
NTSTATUS Ki386CheckDivideByZeroTrap (IN PKTRAP_FRAME UserFrame)
VOID FASTCALL KiCheckForSListAddress (IN PKTRAP_FRAME TrapFrame)
UCHAR KiNextIStreamByte (IN PKTRAP_FRAME UserFrame, IN PUCHAR *istream)
VOID KipWorkAroundCompiler (USHORT *StatusWord, USHORT *ControlWord)
VOID KipWorkAroundCompiler (IN PUSHORT StatusWord, IN PUSHORT ControlWord)
Variables
static KMOD MOD32 []
struct {
UCHAR ModRm
UCHAR Opcode1
UCHAR Opcode2
UCHAR type
} NoWaitNpxInstructions []
static UCHAR RM32 []
static UCHAR RM8 []
Macro Definition Documentation
#define GETREG (frame, reg) ((PULONG) (((ULONG) frame)+reg))[0]
Definition at line 38 of file trapc.c.
Referenced by Ki386CheckDelayedNpxTrap(), and Ki386CheckDivideByZeroTrap().
#define REG (field) ((ULONG)(&((KTRAP_FRAME *)0)->field))
Definition at line 37 of file trapc.c.
Typedef Documentation
typedef struct KMOD * PKMOD
Function Documentation
BOOLEAN FASTCALL KeInvalidAccessAllowed (__in_opt PVOID TrapInformation)
Definition at line 754 of file trapc.c.
References ARGUMENT_PRESENT, _KTRAP_FRAME::Eip, ExpInterlockedPopEntrySListFault(), FALSE, KeUserPopEntrySListFault, KGDT_R0_CODE, KGDT_R3_CODE, RPL_MASK, _KTRAP_FRAME::SegCs, and TRUE.
Referenced by MiAccessCheck(), and MmAccessFault().
BOOLEAN Ki386CheckDelayedNpxTrap (IN PKTRAP_FRAME UserFrame, IN PFX_SAVE_AREA NpxFrame)
Definition at line 328 of file trapc.c.
References APC_LEVEL, CR0_EM, CR0_MP, CR0_TS, KMOD::Disp, EFLAGS_V86_MASK, except, EXCEPTION_EXECUTE_HANDLER, _EXCEPTION_RECORD::ExceptionAddress, FALSE, GETREG, KeGetCurrentIrql(), KeGetCurrentThread(), KeI386FxsrPresent, KeLowerIrql, KeRaiseIrql, KGDT_R0_CODE, KiCopyInformation(), KiDispatchException(), KiNextIStreamByte(), KipWorkAroundCompiler(), ModRm, NOTHING, NoWaitNpxInstructions, NPX_STATE_NOT_LOADED, _KTHREAD::NpxState, NULL, Opcode1, Opcode2, ProbeAndWriteUshort, RM32, KMOD::RmDisplace, KMOD::RmDisplaceOnly, KMOD::RmSib, TRUE, and UserMode.
NTSTATUS Ki386CheckDivideByZeroTrap (IN PKTRAP_FRAME UserFrame)
Definition at line 91 of file trapc.c.
References APC_LEVEL, KMOD::Disp, EFLAGS_V86_MASK, FALSE, GETREG, KeBugCheck(), KeGetCurrentIrql(), KeRaiseIrql, KGDT_R0_CODE, ProbeAndReadChar, ProbeAndReadUchar, ProbeAndReadUlong, ProbeAndReadUshort, RM32, RM8, KMOD::RmDisplace, KMOD::RmDisplaceOnly, KMOD::RmSib, STATUS_INTEGER_DIVIDE_BY_ZERO, STATUS_INTEGER_OVERFLOW, TRUE, and UNEXPECTED_KERNEL_MODE_TRAP.
VOID FASTCALL KiCheckForSListAddress (IN PKTRAP_FRAME TrapFrame)
Definition at line 701 of file trapc.c.
References ExpInterlockedPopEntrySListEnd(), ExpInterlockedPopEntrySListResume(), KeUserPopEntrySListEnd, KeUserPopEntrySListResume, KGDT_R0_CODE, KGDT_R3_CODE, and RPL_MASK.
UCHAR KiNextIStreamByte (IN PKTRAP_FRAME UserFrame, IN PUCHAR * istream)
Definition at line 296 of file trapc.c.
References EFLAGS_V86_MASK, KGDT_R0_CODE, and ProbeAndReadUchar.
Referenced by Ki386CheckDelayedNpxTrap().
VOID KipWorkAroundCompiler (USHORT * StatusWord, USHORT * ControlWord)
Referenced by Ki386CheckDelayedNpxTrap().
VOID KipWorkAroundCompiler (IN PUSHORT StatusWord, IN PUSHORT ControlWord)
Definition at line 670 of file trapc.c.
References CR0_EM, CR0_MP, and CR0_TS.
Variable Documentation
KMOD MOD32[] static
Initial value:
= {
         5,     4,   0x20,   4,
      0xff,     4,   0xff,   1,
      0xff,     4,   0xff,   4,
      0xff,  0xff,   0x00,   0
}
Definition at line 69 of file trapc.c.
UCHAR ModRm
Definition at line 78 of file trapc.c.
Referenced by Ki386CheckDelayedNpxTrap().
struct { ... } NoWaitNpxInstructions[]
Initial value:
= {
      0xDB, 0xE3, 0,  1,
      0xDB, 0xE2, 0,  1,
      0xD9, 0x06, 1,  1,
      0xDD, 0x06, 1,  1,
      0xD9, 0x07, 1,  2,
      0xDD, 0x07, 1,  3,
      0xDF, 0xE0, 0,  4,
                    0x00, 0x00, 0,  1
}
Referenced by Ki386CheckDelayedNpxTrap().
UCHAR Opcode1
Definition at line 77 of file trapc.c.
Referenced by Ki386CheckDelayedNpxTrap().
UCHAR Opcode2
Definition at line 77 of file trapc.c.
Referenced by Ki386CheckDelayedNpxTrap().
UCHAR RM32[] static
Initial value:
= {
       REG(Eax),
       REG(Ecx),
       REG(Edx),
       REG(Ebx),
       REG(HardwareEsp),
       REG(Ebp),
       REG(Esi),
       REG(Edi)
}
Definition at line 47 of file trapc.c.
Referenced by Ki386CheckDelayedNpxTrap(), and Ki386CheckDivideByZeroTrap().
UCHAR RM8[] static
Initial value:
= {
       REG(Eax),
       REG(Ecx),
       REG(Edx),
       REG(Ebx),
       REG(Eax) + 1,
       REG(Ecx) + 1,
       REG(Edx) + 1,
       REG(Ebx) + 1
}
Definition at line 58 of file trapc.c.
Referenced by Ki386CheckDivideByZeroTrap().
UCHAR type
Definition at line 78 of file trapc.c.