Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmvalue.c File Reference
cmvalue.c File Reference
#include "cmp.h"
Functions
NTSTATUS CmpAddValueToList (IN PHHIVE Hive, IN HCELL_INDEX ValueCell, IN ULONG Index, IN ULONG Type, IN OUT PCHILD_LIST ChildList)
BOOLEAN CmpFindNameInList (IN PHHIVE Hive, IN PCHILD_LIST ChildList, IN PUNICODE_STRING Name, IN OPTIONAL PULONG ChildIndex, OUT PHCELL_INDEX CellIndex)
HCELL_INDEX CmpFindValueByName (PHHIVE Hive, PCM_KEY_NODE KeyNode, PUNICODE_STRING Name)
BOOLEAN CmpFreeValue (PHHIVE Hive, HCELL_INDEX Cell)
BOOLEAN CmpFreeValueData (PHHIVE Hive, HCELL_INDEX DataCell, ULONG DataLength)
BOOLEAN CmpGetValueData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize, IN OUT PVOID *Buffer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
BOOLEAN CmpMarkValueDataDirty (IN PHHIVE Hive, IN PCM_KEY_VALUE Value)
NTSTATUS CmpRemoveValueFromList (IN PHHIVE Hive, IN ULONG Index, IN OUT PCHILD_LIST ChildList)
NTSTATUS CmpSetValueDataExisting (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX OldDataCell)
NTSTATUS CmpSetValueDataNew (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX ValueCell, OUT PHCELL_INDEX DataCell)
PCELL_DATA CmpValueToData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize)
Function Documentation
NTSTATUS CmpAddValueToList (IN PHHIVE Hive, IN HCELL_INDEX ValueCell, IN ULONG Index, IN ULONG Type, IN OUT PCHILD_LIST ChildList)
Definition at line 487 of file cmvalue.c.
References ASSERT, ASSERT_CELL_DIRTY, ASSERT_HIVE_FLUSHER_LOCKED, CM_MAX_REASONABLE_VALUES, CM_PAGED_CODE, Count, FALSE, HBLOCK_SIZE, HCELL_NIL, HvAllocateCell(), HvGetCell, HvReallocateCell(), HvReleaseCell, Index, _CELL_DATA::_u::KeyList, NULL, ROUND_UP, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _CELL_DATA::u.
Referenced by CmpCopyKeyPartial(), CmpMergeKeyValues(), CmpSetValueKeyNew(), and CmpSyncKeyValues().
BOOLEAN CmpFindNameInList (IN PHHIVE Hive, IN PCHILD_LIST ChildList, IN PUNICODE_STRING Name, IN OPTIONAL PULONG ChildIndex, OUT PHCELL_INDEX CellIndex)
Definition at line 77 of file cmvalue.c.
References ARGUMENT_PRESENT, ASSERT, _UNICODE_STRING::Buffer, CM_PAGED_CODE, CmpCompareCompressedName(), FALSE, _CM_KEY_VALUE::Flags, HCELL_NIL, HvGetCell, HvReleaseCell, _CELL_DATA::_u::KeyList, _UNICODE_STRING::Length, List, _UNICODE_STRING::MaximumLength, _CM_KEY_VALUE::Name, _CM_KEY_VALUE::NameLength, NULL, RtlCompareUnicodeString(), TRUE, _CELL_DATA::u, and VALUE_COMP_NAME.
Referenced by CmDeleteValueKey(), CmpCopyKeyPartial(), CmpFindValueByName(), CmpMergeKeyValues(), CmpSyncKeyValues(), and CmSetValueKey().
HCELL_INDEX CmpFindValueByName (PHHIVE Hive, PCM_KEY_NODE KeyNode, PUNICODE_STRING Name)
Definition at line 40 of file cmvalue.c.
References ASSERT, CM_PAGED_CODE, CmpFindNameInList(), FALSE, HCELL_NIL, and NULL.
Referenced by CmGetSystemControlValues(), CmpAddDriverToList(), CmpFindControlSet(), CmpFindNLSData(), CmpFindProfileOption(), CmpFindTagIndex(), CmpGetSymbolicLink(), CmpIsLoadType(), CmpMarkCurrentValueDirty(), CmpSetCurrentProfile(), CmpSortDriverList(), CmpValidateSelect(), and CmQueryMultipleValueKey().
BOOLEAN CmpFreeValue (PHHIVE Hive, HCELL_INDEX Cell)
Definition at line 952 of file cmvalue.c.
References ASSERT, CM_PAGED_CODE, CmpFreeValueData(), _CM_KEY_VALUE::Data, _CM_KEY_VALUE::DataLength, FALSE, HvFreeCell(), HvGetCell, HvReleaseCell, NULL, and TRUE.
Referenced by CmDeleteValueKey(), CmpFreeKeyByCell(), CmpFreeKeyValues(), and CmpSetValueKeyNew().
BOOLEAN CmpFreeValueData (PHHIVE Hive, HCELL_INDEX DataCell, ULONG DataLength)
Definition at line 832 of file cmvalue.c.
References ASSERT, ASSERT_BIG_DATA, CM_PAGED_CODE, CmpIsHKeyValueBig, CmpIsHKeyValueSmall, _CM_BIG_DATA::Count, FALSE, HCELL_NIL, HvFreeCell(), HvGetCell, HvIsCellAllocated(), HvReleaseCell, _CM_BIG_DATA::List, NULL, and TRUE.
Referenced by CmpCopyValue(), CmpFreeValue(), and CmpSetValueKeyExisting().
BOOLEAN CmpGetValueData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize, IN OUT PVOID * Buffer, OUT PBOOLEAN Allocated, OUT PHCELL_INDEX CellToRelease)
Definition at line 235 of file cmvalue.c.
References ASSERT, ASSERT_BIG_DATA, ASSERT_KEY_VALUE, CM_KEY_VALUE_BIG, CM_PAGED_CODE, CmpIsHKeyValueBig, CmpIsHKeyValueSmall, _CM_BIG_DATA::Count, ExAllocatePoolWithTag, ExFreePool(), FALSE, HCELL_NIL, HvGetCell, HvReleaseCell, leave, _CM_BIG_DATA::List, NULL, PagedPool, RtlCopyMemory, and TRUE.
Referenced by CmGetSystemControlValues(), CmpCopyValue(), CmpFindTagIndex(), CmpGetSymbolicLink(), CmpGetValueDataFromCache(), CmpValueToData(), and CmQueryMultipleValueKey().
BOOLEAN CmpMarkValueDataDirty (IN PHHIVE Hive, IN PCM_KEY_VALUE Value)
Definition at line 706 of file cmvalue.c.
References ASSERT_BIG_DATA, ASSERT_HIVE_FLUSHER_LOCKED, ASSERT_KEY_VALUE, CM_PAGED_CODE, CmpIsHKeyValueBig, CmpIsHKeyValueSmall, _CM_BIG_DATA::Count, FALSE, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, _CM_BIG_DATA::List, NULL, and TRUE.
Referenced by CmDeleteValueKey(), CmpMarkKeyDirty(), CmpMarkKeyValuesDirty(), and CmpSetValueKeyExisting().
NTSTATUS CmpRemoveValueFromList (IN PHHIVE Hive, IN ULONG Index, IN OUT PCHILD_LIST ChildList)
Definition at line 617 of file cmvalue.c.
References ASSERT, ASSERT_CELL_DIRTY, CM_PAGED_CODE, Count, HCELL_NIL, HvFreeCell(), HvGetCell, HvReallocateCell(), HvReleaseCell, Index, _CELL_DATA::_u::KeyList, NULL, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and _CELL_DATA::u.
Referenced by CmDeleteValueKey().
NTSTATUS CmpSetValueDataExisting (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX OldDataCell)
Definition at line 1271 of file cmvalue.c.
References ASSERT, ASSERT_BIG_DATA, CM_KEY_VALUE_BIG, CM_PAGED_CODE, Count, _CM_BIG_DATA::Count, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvReallocateCell(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CM_BIG_DATA::List, NULL, RtlCopyMemory, Status, STATUS_INSUFFICIENT_RESOURCES, and STATUS_SUCCESS.
Referenced by CmpSetValueKeyExisting().
NTSTATUS CmpSetValueDataNew (IN PHHIVE Hive, IN PVOID Data, IN ULONG DataSize, IN ULONG StorageType, IN HCELL_INDEX ValueCell, OUT PHCELL_INDEX DataCell)
Definition at line 1012 of file cmvalue.c.
References ASSERT, ASSERT_HIVE_FLUSHER_LOCKED, CM_BIG_DATA_SIGNATURE, CM_KEY_VALUE_BIG, CM_KEY_VALUE_SMALL, CM_PAGED_CODE, CmKdPrintEx, CML_EXCEPTION, CmpIsHKeyValueBig, Count, _CM_BIG_DATA::Count, DPFLTR_CONFIG_ID, except, EXCEPTION_EXECUTE_HANDLER, FALSE, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), _CM_BIG_DATA::List, NULL, RtlCopyMemory, _CM_BIG_DATA::Signature, STATUS_INSUFFICIENT_RESOURCES, STATUS_SUCCESS, and TRUE.
Referenced by CmpCopyValue(), CmpSetValueKeyExisting(), and CmpSetValueKeyNew().
PCELL_DATA CmpValueToData (IN PHHIVE Hive, IN PCM_KEY_VALUE Value, OUT PULONG realsize)
Definition at line 420 of file cmvalue.c.
References ASSERT, BIG_CELL_ERROR, CM_BUGCHECK, CM_PAGED_CODE, CmpGetValueData(), ExFreePool(), FALSE, NULL, REGISTRY_ERROR, and TRUE.
Referenced by CmpAddDriverToList(), CmpFindControlSet(), CmpFindNLSData(), CmpFindProfileOption(), CmpFindTagIndex(), CmpIsLoadType(), CmpSetCurrentProfile(), and CmpSortDriverList().