Windows Research Kernel v1.2: C:/Windows Research Kernel/config/cmindex.c File Reference
cmindex.c File Reference
#include "cmp.h"
Functions
BOOLEAN CmpAddSubKey (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
HCELL_INDEX CmpAddToLeaf (PHHIVE Hive, HCELL_INDEX LeafCell, HCELL_INDEX NewKey, PUNICODE_STRING NewName)
LONG CmpCompareInIndex (PHHIVE Hive, PUNICODE_STRING SearchName, ULONG Count, PCM_KEY_INDEX Index, PHCELL_INDEX Child)
ULONG CmpComputeHashKey (IN ULONG HashStart, IN PUNICODE_STRING Name)
ULONG CmpComputeHashKeyForCompressedName (IN ULONG HashStart, IN PWCHAR Source, IN ULONG SourceLength)
LONG CmpDoCompareKeyName (PHHIVE Hive, PUNICODE_STRING SearchName, HCELL_INDEX Cell)
HCELL_INDEX CmpDoFindSubKeyByNumber (PHHIVE Hive, PCM_KEY_INDEX Index, ULONG Number)
HCELL_INDEX CmpDuplicateIndex (PHHIVE Hive, HCELL_INDEX IndexCell, ULONG StorageType)
HCELL_INDEX CmpFindSubKeyByHash (PHHIVE Hive, PCM_KEY_FAST_INDEX FastIndex, PUNICODE_STRING SearchName)
HCELL_INDEX CmpFindSubKeyByName (PHHIVE Hive, PCM_KEY_NODE Parent, PUNICODE_STRING SearchName)
HCELL_INDEX CmpFindSubKeyByNumber (PHHIVE Hive, PCM_KEY_NODE Node, ULONG Number)
ULONG CmpFindSubKeyInLeaf (PHHIVE Hive, PCM_KEY_INDEX Index, PUNICODE_STRING SearchName, PHCELL_INDEX Child)
ULONG CmpFindSubKeyInRoot (PHHIVE Hive, PCM_KEY_INDEX Index, PUNICODE_STRING SearchName, PHCELL_INDEX Child)
BOOLEAN CmpMarkIndexDirty (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
BOOLEAN CmpRemoveSubKey (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
BOOLEAN CmpRemoveSubKeyCellNoCellRef (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
HCELL_INDEX CmpSelectLeaf (PHHIVE Hive, PCM_KEY_NODE ParentKey, PUNICODE_STRING NewName, HSTORAGE_TYPE Type, PHCELL_INDEX *RootPointer)
HCELL_INDEX CmpSplitLeaf (PHHIVE Hive, HCELL_INDEX RootCell, ULONG RootSelect, HSTORAGE_TYPE Type)
BOOLEAN CmpUpdateParentForEachSon (PHHIVE Hive, HCELL_INDEX Parent)
Function Documentation
BOOLEAN CmpAddSubKey (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
Definition at line 1270 of file cmindex.c.
References _HHIVE::Allocate, ASSERT, _UNICODE_STRING::Buffer, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_MAX_FAST_INDEX, CM_MAX_INDEX, CM_PAGED_CODE, CmKdPrintEx, CML_INDEX, CmpAddToLeaf(), CmpCompressedNameSize(), CmpCopyCompressedName(), CmpSelectLeaf(), _CM_KEY_INDEX::Count, DPFLTR_CONFIG_ID, FALSE, _CM_KEY_NODE::Flags, _HHIVE::Free, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvMarkCellDirty(), HvReleaseCell, Index, KEY_COMP_NAME, _UNICODE_STRING::Length, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, _CM_KEY_INDEX::Signature, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, TRUE, UseFastIndex, and UseHashIndex.
Referenced by CmpCopySyncTree2(), CmpCreateLinkNode(), CmpDoCreate(), and CmRenameKey().
HCELL_INDEX CmpAddToLeaf (PHHIVE Hive, HCELL_INDEX LeafCell, HCELL_INDEX NewKey, PUNICODE_STRING NewName)
Definition at line 1542 of file cmindex.c.
References ASSERT, _UNICODE_STRING::Buffer, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CmKdPrintEx, CML_INDEX, CmpCompareInIndex(), CmpComputeHashKey(), CmpFindSubKeyInLeaf(), _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, DBG, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, _CM_INDEX::HashKey, HCELL_NIL, HvGetCell, HvGetCellSize(), HvMarkCellDirty(), HvReallocateCell(), HvReleaseCell, INVALID_INDEX, _UNICODE_STRING::Length, List, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _CM_INDEX::NameHint, NULL, RtlMoveMemory, _CM_KEY_FAST_INDEX::Signature, and _CM_KEY_INDEX::Signature.
Referenced by CmpAddSubKey().
LONG CmpCompareInIndex (PHHIVE Hive, PUNICODE_STRING SearchName, ULONG Count, PCM_KEY_INDEX Index, PHCELL_INDEX Child)
Definition at line 772 of file cmindex.c.
References _UNICODE_STRING::Buffer, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CmpDoCompareKeyName(), CmUpcaseUnicodeChar, Count, HCELL_NIL, _UNICODE_STRING::Length, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _CM_INDEX::NameHint, and _CM_KEY_INDEX::Signature.
Referenced by CmpAddToLeaf(), CmpFindSubKeyInLeaf(), and CmpFindSubKeyInRoot().
ULONG CmpComputeHashKey (IN ULONG HashStart, IN PUNICODE_STRING Name)
Definition at line 2989 of file cmindex.c.
References ASSERT, CmUpcaseUnicodeChar, and OBJ_NAME_PATH_SEPARATOR.
Referenced by CmpAddInfoAfterParseFailure(), CmpAddToLeaf(), CmpFindSubKeyByHash(), CmpFindValueByNameFromCache(), CmpGetValueKeyFromCache(), and CmpParseKey().
ULONG CmpComputeHashKeyForCompressedName (IN ULONG HashStart, IN PWCHAR Source, IN ULONG SourceLength)
Definition at line 3016 of file cmindex.c.
References CmUpcaseUnicodeChar.
Referenced by CmpAddInfoAfterParseFailure(), and CmpGetValueKeyFromCache().
LONG CmpDoCompareKeyName (PHHIVE Hive, PUNICODE_STRING SearchName, HCELL_INDEX Cell)
Definition at line 896 of file cmindex.c.
References _UNICODE_STRING::Buffer, CmpCompareCompressedName(), _CM_KEY_NODE::Flags, HvGetCell, HvReleaseCell, KEY_COMP_NAME, KeyName, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, RtlCompareUnicodeString(), and TRUE.
Referenced by CmpCompareInIndex(), CmpFindSubKeyByHash(), and CmpSelectLeaf().
HCELL_INDEX CmpDoFindSubKeyByNumber (PHHIVE Hive, PCM_KEY_INDEX Index, ULONG Number)
Definition at line 1043 of file cmindex.c.
References ASSERT, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, Count, _CM_KEY_INDEX::Count, FALSE, HCELL_NIL, HvGetCell, HvReleaseCell, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NULL, and _CM_KEY_INDEX::Signature.
Referenced by CmpFindSubKeyByNumber().
HCELL_INDEX CmpDuplicateIndex (PHHIVE Hive, HCELL_INDEX IndexCell, ULONG StorageType)
Definition at line 2730 of file cmindex.c.
References ASSERT, ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, _CM_KEY_INDEX::Count, FALSE, HCELL_NIL, HvDuplicateCell(), HvFreeCell(), HvGetCell, HvGetCellType, HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), Index, _CM_KEY_INDEX::List, NULL, _CM_KEY_INDEX::Signature, and TRUE.
Referenced by CmpDuplicateKey(), and CmRenameKey().
HCELL_INDEX CmpFindSubKeyByHash (PHHIVE Hive, PCM_KEY_FAST_INDEX FastIndex, PUNICODE_STRING SearchName)
Definition at line 3037 of file cmindex.c.
References ASSERT, _CM_INDEX::Cell, CM_KEY_HASH_LEAF, CM_PAGED_CODE, CmpComputeHashKey(), CmpDoCompareKeyName(), _CM_KEY_FAST_INDEX::Count, DBG, FALSE, _CM_INDEX::HashKey, HCELL_NIL, _CM_KEY_FAST_INDEX::List, and _CM_KEY_FAST_INDEX::Signature.
Referenced by CmpFindSubKeyByName().
HCELL_INDEX CmpFindSubKeyByName (PHHIVE Hive, PCM_KEY_NODE Parent, PUNICODE_STRING SearchName)
Definition at line 193 of file cmindex.c.
References ASSERT, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, CmKdPrintEx, CML_INDEX, CmpFindSubKeyByHash(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvIsCellAllocated(), HvReleaseCell, INVALID_INDEX, NULL, _CM_KEY_INDEX::Signature, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, and _CM_KEY_NODE::SubKeyLists.
Referenced by CmGetSystemControlValues(), CmpCopySyncTree2(), CmpDoCreate(), CmpFindControlSet(), CmpFindDrivers(), CmpFindNLSData(), CmpFindProfileOption(), CmpMarkCurrentValueDirty(), CmpParseKey(), CmpSortDriverList(), CmpSyncSubKeysAfterDelete(), CmpValidateSelect(), CmpWalkPath(), and CmRenameKey().
HCELL_INDEX CmpFindSubKeyByNumber (PHHIVE Hive, PCM_KEY_NODE Node, ULONG Number)
Definition at line 968 of file cmindex.c.
References CmKdPrintEx, CML_INDEX, CmpDoFindSubKeyByNumber(), DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvReleaseCell, Index, NULL, Stable, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and Volatile.
Referenced by CmEnumerateKey(), CmpCheckRegistry2(), CmpCopySyncTree2(), CmpDeleteTree(), CmpDoAccessCheckOnSubtree(), CmpFindDrivers(), CmpFindProfileOption(), CmpShiftAllCells2(), CmpSyncSubKeysAfterDelete(), and CmpUpdateParentForEachSon().
ULONG CmpFindSubKeyInLeaf (PHHIVE Hive, PCM_KEY_INDEX Index, PUNICODE_STRING SearchName, PHCELL_INDEX Child)
Definition at line 611 of file cmindex.c.
References ASSERT, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CmKdPrintEx, CML_INDEX, CmpCompareInIndex(), _CM_KEY_INDEX::Count, DPFLTR_CONFIG_ID, HCELL_NIL, INVALID_INDEX, _CM_KEY_INDEX::Signature, and TRUE.
Referenced by CmpAddToLeaf(), CmpFindSubKeyByName(), CmpMarkIndexDirty(), and CmpRemoveSubKey().
ULONG CmpFindSubKeyInRoot (PHHIVE Hive, PCM_KEY_INDEX Index, PUNICODE_STRING SearchName, PHCELL_INDEX Child)
Definition at line 310 of file cmindex.c.
References ASSERT, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmKdPrintEx, CML_INDEX, CmpCompareInIndex(), _CM_KEY_INDEX::Count, DPFLTR_CONFIG_ID, HCELL_NIL, HvGetCell, HvReleaseCell, INVALID_INDEX, _CM_KEY_INDEX::List, NULL, _CM_KEY_INDEX::Signature, and TRUE.
Referenced by CmpFindSubKeyByName(), CmpMarkIndexDirty(), CmpRemoveSubKey(), and CmpSelectLeaf().
BOOLEAN CmpMarkIndexDirty (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
Definition at line 2311 of file cmindex.c.
References ASSERT, _UNICODE_STRING::Buffer, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmpCompressedNameSize(), CmpCopyCompressedName(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvGetCell, HvIsCellAllocated(), HvMarkCellDirty(), HvReleaseCell, Index, INVALID_INDEX, KEY_COMP_NAME, _UNICODE_STRING::Length, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, PagedPool, _CM_KEY_INDEX::Signature, _HHIVE::StorageTypeCount, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpMarkKeyDirty(), CmpMarkKeyParentDirty(), and CmRenameKey().
BOOLEAN CmpRemoveSubKey (PHHIVE Hive, HCELL_INDEX ParentKey, HCELL_INDEX TargetKey)
Definition at line 2485 of file cmindex.c.
References ASSERT, ASSERT_CELL_DIRTY, _UNICODE_STRING::Buffer, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CmpCompressedNameSize(), CmpCopyCompressedName(), CmpFindSubKeyInLeaf(), CmpFindSubKeyInRoot(), _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, ExAllocatePool, ExFreePool(), FALSE, _CM_KEY_NODE::Flags, HCELL_NIL, HvFreeCell(), HvGetCell, HvGetCellType, HvIsCellAllocated(), HvReleaseCell, INVALID_INDEX, KEY_COMP_NAME, _UNICODE_STRING::Length, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, _UNICODE_STRING::MaximumLength, _CM_KEY_NODE::Name, _CM_KEY_NODE::NameLength, NULL, PagedPool, RtlMoveMemory, _CM_KEY_INDEX::Signature, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpFreeKeyByCell(), and CmRenameKey().
BOOLEAN CmpRemoveSubKeyCellNoCellRef (PHHIVE Hive, HCELL_INDEX Parent, HCELL_INDEX Child)
Definition at line 1123 of file cmindex.c.
References ASSERT, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_ROOT, CM_PAGED_CODE, _CM_KEY_FAST_INDEX::Count, _CM_KEY_INDEX::Count, FALSE, HvGetCell, HvMarkCellDirty(), HvReleaseCell, Index, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NULL, RtlMoveMemory, _CM_KEY_INDEX::Signature, Stable, _CM_KEY_NODE::SubKeyCounts, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpCheckRegistry2().
HCELL_INDEX CmpSelectLeaf (PHHIVE Hive, PCM_KEY_NODE ParentKey, PUNICODE_STRING NewName, HSTORAGE_TYPE Type, PHCELL_INDEX * RootPointer)
Definition at line 1767 of file cmindex.c.
References ASSERT, _CM_INDEX::Cell, CM_KEY_FAST_LEAF, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CM_KEY_INDEX_ROOT, CM_MAX_INDEX, CmKdPrintEx, CML_INDEX, CmpDoCompareKeyName(), CmpFindSubKeyInRoot(), CmpSplitLeaf(), _CM_KEY_INDEX::Count, DPFLTR_CONFIG_ID, FALSE, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseFreeCellRefArray(), HvTrackCellRef(), Index, INVALID_INDEX, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NULL, _CM_KEY_INDEX::Signature, _CM_KEY_NODE::SubKeyLists, and TRUE.
Referenced by CmpAddSubKey().
HCELL_INDEX CmpSplitLeaf (PHHIVE Hive, HCELL_INDEX RootCell, ULONG RootSelect, HSTORAGE_TYPE Type)
Definition at line 2091 of file cmindex.c.
References ASSERT, CM_KEY_HASH_LEAF, CM_KEY_INDEX_LEAF, CmKdPrintEx, CML_INDEX, _CM_KEY_INDEX::Count, DPFLTR_CONFIG_ID, FALSE, FIELD_OFFSET, HCELL_NIL, HvAllocateCell(), HvFreeCell(), HvGetCell, HvGetCellSize(), HvGetCellType, HvMarkCellDirty(), HvReallocateCell(), HvReleaseCell, HvReleaseFreeCellRefArray(), HvTrackCellRef(), List, _CM_KEY_FAST_INDEX::List, _CM_KEY_INDEX::List, NULL, RtlMoveMemory, _CM_KEY_INDEX::Signature, and UseHashIndex.
Referenced by CmpSelectLeaf().
BOOLEAN CmpUpdateParentForEachSon (PHHIVE Hive, HCELL_INDEX Parent)
Definition at line 2887 of file cmindex.c.
References ASSERT, ASSERT_CM_EXCLUSIVE_HIVE_ACCESS, CM_PAGED_CODE, CmpFindSubKeyByNumber(), Count, FALSE, HCELL_NIL, HvGetCell, HvMarkCellDirty(), HvReleaseCell, NULL, _CM_KEY_NODE::Parent, Stable, _CM_KEY_NODE::SubKeyCounts, TRUE, and Volatile.
Referenced by CmMoveKey(), and CmRenameKey().